### ISSUE TITLE
conditional import syntax for vars_files does not read all files in list

### ISSUE THREAD

**Issue by amoe** [ansible/ansible#10010]
##### Issue Type:

Bug Report
##### Ansible Version:

```
amoe@kruis2:~/dev/ansible/test_vars_files$ ansible --version
ansible 1.9 (devel 02bc014bcd) last updated 2015/01/15 10:02:09 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 8c8be0e48c) last updated 2015/01/14 15:02:30 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD ffa8abf979) last updated 2015/01/14 15:02:34 (GMT +100)
  v2/ansible/modules/core: (detached HEAD 27d5e5124f) last updated 2015/01/14 15:02:40 (GMT +100)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2015/01/14 15:02:45 (GMT +100)
  configured module search path = None
```

Also reproduces on 1.8.2
##### Environment:

Debian Wheezy
##### Summary:

According to comments on #8881, providing a list to vars_files should read all of the files in the list.  However, only the first one in the list gets read and parsed for variable definitions.
##### Steps To Reproduce:

`playbook.yml`:

```

---
- hosts: localhost
  vars_files:
- [ "vars/blah.yml", "vars/blah2.yml" ]
  tasks:
- debug: msg="{{ MY_VAR }}"
- debug: msg="{{ VAR_A }}"
- debug: msg="{{ VAR_B }}"
- debug: msg="{{ VAR_C }}"
```

`vars/blah.yml`:

```

---
MY_VAR: FROM_BLAH_DOT_YML
VAR_A: "FOO"
VAR_B: "BAR"
```

`vars/blah2.yml`:

```

---
MY_VAR: FROM_BLAH2_DOT_YML
VAR_A: "BAZ"
VAR_C: "QUUX"
```
##### Expected Results:

```
PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [debug msg="{{ MY_VAR }}"] ********************************************** 
ok: [localhost] => {
"msg": "FROM_BLAH2_DOT_YML"
}

TASK: [debug msg="{{ VAR_A }}"] *********************************************** 
ok: [localhost] => {
"msg": "FOO"
}

TASK: [debug msg="{{ VAR_B }}"] *********************************************** 
ok: [localhost] => {
"msg": "BAR"
}

TASK: [debug msg="{{ VAR_C }}"] *********************************************** 
ok: [localhost] => {
"msg": "QUUX"
}
```
##### Actual Results:

```
PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [debug msg="{{ MY_VAR }}"] ********************************************** 
ok: [localhost] => {
"msg": "FROM_BLAH_DOT_YML"
}

TASK: [debug msg="{{ VAR_A }}"] *********************************************** 
ok: [localhost] => {
"msg": "FOO"
}

TASK: [debug msg="{{ VAR_B }}"] *********************************************** 
ok: [localhost] => {
"msg": "BAR"
}

TASK: [debug msg="{{ VAR_C }}"] *********************************************** 
fatal: [localhost] => One or more undefined variables: 'VAR_C' is undefined

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
       to retry, use: --limit @/home/amoe/playbook.retry

localhost                  : ok=4    changed=0    unreachable=1    failed=0   
```

**Comment by bcoca** [comment]
so I think you are misunderstanding here:
try:
  vars_files: [ "vars/blah.yml", "vars/blah2.yml" ]

or 
  vars_files: 
        - "vars/blah.yml"
        - "vars/blah2.yml"

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

As mentioned above, I think you confusing the conditional syntax with the list syntax, you can see it explained here http://docs.ansible.com/playbooks_conditionals.html

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by amoe** [comment]
Hi, I still think this is a bug, although I described it wrong in the title.  The bug is with the 'conditional import' syntax, as you linked to: http://docs.ansible.com/playbooks_conditionals.html#conditional-imports

The following example taken from the documentation:

```
vars_files:
  - "vars/common.yml"
  - [ "vars/{{ ansible_os_family }}.yml", "vars/os_defaults.yml" ]
```

implies that `vars/{{ ansible_os_family }}.yml` _and_ `vars/os_defaults.yml` should be read for variable definitions.  As demonstrated by the example output in this issue, this is not happening.  Please can you reopen this issue?

**Comment by bcoca** [comment]
No, the expected behavior is that vars/{{ ansible_os_family }}.yml is read if it exists, only if it doesn't will vars/os_defaults.yml get read, that is why it is 'conditional'.
