### ISSUE TITLE
Feature request: Ansible-pull daemon mode

### ISSUE THREAD

**Issue by skorokithakis** [ansible/ansible#10033]
I am thinking of writing a daemon mode for Ansible-pull. It would run an HTTP server, rather than launching with cron, and it would run a deployment whenever a particular endpoint was hit.

This is so you can configure Github webhooks, so you don't have to poll for changes. Would you merge something like this if I wrote it?

**Comment by sivel** [comment]
Instead of an issue, this should be sent to the ansible-devel mailing list for discussion.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
- development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by skorokithakis** [comment]
Thanks, I already implementaed this in PR #10041
