### ISSUE TITLE
Bug Report: Ansible does not work with TLS enabled on a Docker daemon

### ISSUE THREAD

**Issue by technolo-g** [ansible/ansible#10032]
##### Summary:

After enabling TLS for Docker connections in the environment, Ansbile does not seem to use the settings.
##### Steps To Reproduce:

When the following env vars are set:

```
DOCKER_HOST=tcp://dockerhost01:2376
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/mbajor/Dev/docker-swarm/master/tls
```

and the following playbook is run:

```

---

- hosts: local
  connection: local
  gather_facts: False
  vars:
    docker_host: "{{ lookup('env','DOCKER_HOST') }}"
  tasks:
  - name: Run an Nginx container
    docker: >
      docker_url={{ docker_host }}
      image=nginx:latest
      publish_all_ports=True
      hostname=nginx
      state=running
      count=10
    register: nginx_container
```

The following error output occurs:

```
PLAY [local] ******************************************************************

TASK: [Run an Nginx container] ************************************************
failed: [localhost] => {"changed": false, "failed": true}
msg: ConnectionError(ProtocolError('Connection aborted.', BadStatusLine('\x15\x03\x01\x00\x02\x02\n',)),)

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/mbajor/demo_containers.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

Which appears to indicate that it is making a connection over HTTP
##### Expected Results:

I would expect Ansible to connect to the Docker daemon and provision the containers
##### Actual Results:

Ansible exits with a '2' status code

**Comment by lorin** [comment]
Related: https://github.com/ansible/ansible-modules-core/pull/272

**Comment by abadger** [comment]
I believe that this is fixed in devel and the stable-1.9 branch (will be in 1.9rc2).  Care to test that out?

**Comment by abadger** [comment]
PR with the change is here: https://github.com/ansible/ansible-modules-core/pull/926

**Comment by jimi-c** [comment]
Closing per the above.
