### ISSUE TITLE
Run_once does not accept parameters

### ISSUE THREAD

**Issue by mikesac** [ansible/ansible#10049]
Issue Type: Bug Report

Ansible Version:1.7.2 , 1.8.2

Environment: MacOs X 10.9.5

Summary:

run_once doesn't accept a variable as value, checking documentation I didn't find anything asserting this should not be supported.

Steps To Reproduce: 

Run this playbook on any multiple-ip hosts

```

---

- hosts: "local-frontend"
  tasks:

  - name: test parametrized run_once
    debug: msg="Single index mode {{ do_run_once}} "
    run_once: do_run_once|bool

```

returns the following:

```
ansible-playbook test.yml -i multi_hosts_2chain -e "do_run_once=True"

PLAY [local-frontend] ********************************************************* 

GATHERING FACTS *************************************************************** 
ok: [192.168.0.20]
ok: [192.168.0.10]

TASK: [test parametrized run_once] ******************************************** 
ok: [192.168.0.20] => {
    "msg": "Single index mode True "
}
ok: [192.168.0.10] => {
    "msg": "Single index mode True "
}

PLAY RECAP ******************************************************************** 
192.168.0.10               : ok=2    changed=0    unreachable=0    failed=0   
192.168.0.20               : ok=2    changed=0    unreachable=0    failed=0   
```

No syntax error , but run_once:true has not be accepted as a valid instruction.

**Comment by calebwoods** [comment]
I'm also seeing this issue on Ansible 1.9.0.1 and 1.9.2.  Is there a work around for using variable to toggle `run_once`?

**Comment by bcoca** [comment]
so this is fixed in current devel, just one note:

`run_once: "{{do_run_once|bool}}"`

so I'm closing this issue.

**Comment by calebwoods** [comment]
@bcoca what version would that fix be released in, if it is in current devel?

**Comment by bcoca** [comment]
yes, current devel which will be 2.0
