### ISSUE TITLE
Task with include print no information

### ISSUE THREAD

**Issue by jtyr** [ansible/ansible#10060]
When I use `include` in a task, the run of `ansible-playbook` don't show any information about the task. For example if I have:

```
- name: Including some other file
  include: some_other_file.yaml
  when: some_condition
```

I would expect so see:

```
TASK: [myrole | Including some other file] ***************************************** 
skipping: [myhost]
```

if the condition is false.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

Includes are not real tasks, they act more like 'preprocessing macros' when compiling the play for running. A 'when' added to the include is actually added to every task included, it does not make the include itself conditional.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
