### ISSUE TITLE
Module ini_file should be capable of comments in files

### ISSUE THREAD

**Issue by ogmueller** [ansible/ansible#10071]
I found the bug #4522 and read the documentation of the module "ini_file", which states, that ini_file will remove all comments.

The issue is though, that they are required sometimes. One example is the module files in PHP:

``` ini
# /etc/php5/mods-available/opcache.ini
; configuration for php ZendOpcache module
; priority=05
zend_extension=opcache.so
```

The comment ";priority=05" is essential and used by some CLI commands like "php5enmod". If the comment is missing, it will place the module in the wrong order. Those comments are really important.

Could someone please enable comment support for the module "ini_file".
It seemed to be working in the past. I found it in [Ansible Changelog v1.7.1](https://raw.githubusercontent.com/ansible/ansible/v1.7.1/CHANGELOG.md) where it says "\* support ; comments in INI file module".

**Comment by razvanphp** [comment]
+1 for this feature, I think people should use less templates, so they can keep up with packages updates.

One requirement tho, when the item is defined in the conf file, but commented out, it should replace that line, and not add another one at the end of the section. The reason is of course because there are some comments before that line related to possible values etc. See php.ini for example.

Thank you!

**Comment by razvanphp** [comment]
Also, the backup function is pretty useless now, for example if you change 4 values in the ini file, you will have only one backup with the state before the 4th change, and not the state before the 1st change.

**Comment by purificant** [comment]
+1

**Comment by noseka1** [comment]
I created an ini_file2 module that leaves the comments in the INI file untouched. I'm using it as a drop in replacement for the ini_file module. For further information you can refer to:
http://alesnosek.com/blog/2015/08/03/improving-ansibles-ini-file-module/

The ini_file2 source code as well as test scripts can be found at:
https://github.com/noseka1/ini_file2

If there is an interested I'd be happy to prepare a Git branch that would replace the ini_file implementation with the implementation found in ini_file2.

**Comment by jpbarbosa** [comment]
+1

**Comment by rightaway** [comment]
@noseka1 Fantastic! It solves **all** the problems I described a long time ago in #5860 (removing comments, reordering entries within a section, adding spaces around the `=`, making keys lowercase, removing blank quotation marks `""` as values).

This is far superior than the default ini_file module and needs to replace it. Could you create a pull request? As suggested by the guy who closed #5860.

**Comment by razvanphp** [comment]
@noseka1 ping!

Please make us a big favor and create a pull request to replace the current ini_file module with your implementation. Let's hope this will get soon into official ansible release. Too bad such a basic thing we need every day is ignored...

**Comment by noseka1** [comment]
Sorry, for the very late response. Ok, I'll create a pull request later today.

**Comment by noseka1** [comment]
Ok, pull request submitted https://github.com/ansible/ansible-modules-core/pull/2385

**Comment by cervajs** [comment]
@noseka1 is it possible to preserve quotation marks in values ?
i have problem with passwords which contains characters like "=" . they must be in quotation marks

**Comment by razvanphp** [comment]
Also, documentation should be updated, right now it still says comments are stripped.

**Comment by noseka1** [comment]
@cervajs This is a sample command that will preserve the quotation marks:
ini_file2: dest="file.ini" section=section option=key value='"newvalue"'

The resulting ini file looks like this:
[section]
key = "newvalue"

If this doesn't work for you, please, be more specific in what you're trying to achieve. Thanks.

**Comment by noseka1** [comment]
@razvanphp Yes, you're right. Please, could you open an issue for that?

**Comment by bcoca** [comment]
closing via merged https://github.com/ansible/ansible-modules-core/commit/7f59773460d79b3dae34c375ba68caea1bfc09a8
