### ISSUE TITLE
Can we put a shell script into the ansible git repository directory?

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#10081]
like ~/ansible/update.sh

```
#!/bin/sh
git pull --rebase
git submodule update --init --recursive
```

**Comment by ghost** [comment]
@bcoca  do you accept pull request?

**Comment by abadger** [comment]
Looks like you could submit a pull request rather than a bug report for this.  I think a shell script would be good.  I think it should be placed in the hacking directory rather than the toplevel.

**Comment by abadger** [comment]
Ah -- Now I see that you referenced a pull request.  Closing this bug in favor of the PR.
