### ISSUE TITLE
Playbook yaml formatting syntax error caused by a couple of spaces, why?

### ISSUE THREAD

**Issue by hyperfocus1338** [ansible/ansible#10088]
Hello,

I'm having this annoying formatting error and I don't know why. This works:

```

---
- name: upload git config to fix proxy problem
  copy: src=roles/bootstrap/templates/gitconfig dest={{ user_home }}/.gitconfig owner={{ user }} group={{ user }} mode=0644
```

But this doesn't:

```

---
- name: upload git config to fix proxy problem
  copy: src=roles/bootstrap/templates/gitconfig 
        dest={{ user_home }}/.gitconfig 
        owner={{ user }} 
        group={{ user }} 
        mode=0644
```

It gives me:

```
ERROR: Syntax Error while loading YAML script, /path/to/git-proxy-fix.yml
Note: The error may actually appear before this position: line 4, column 1

  copy: src=roles/bootstrap/templates/gitconfig dest={{ user_home }}/.gitconfig
        owner={{ user }}
^
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"


Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

I have my whole playbook in the second way of formatting actions, I can't figure out why the second one gives a syntax error and the first one doesn't. How can I fix this?

**Comment by jliu70** [comment]
Maybe you can use Ansible-lint to help verify YAML syntax?  It usually will report on extra white spaces.

**Comment by hyperfocus1338** [comment]
The issue went away when I stopped using variables, so consider this solved. Still strange behavior, wanted to report it anyway. Yaml lint says both ways are valid yaml.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by marnelfr** [comment]
It's a pretty old subject but it could help someone:
The ansible command also showed me:

with_items:
      - {{ foo }}
Should be written as:
    with_items:
      - "{{ foo }}"

I fix this just by correcting the indentation in my yml file

**Comment by GangaramD** [comment]
Here i don't see any indentation syntax issue, the issue  is due to the missing double quotes  `"{{ user_home }}/.gitconfig "`

After changes the snippet would look like,


       name: upload git config to fix proxy problem
       copy: src=roles/bootstrap/templates/gitconfig 
                 dest="{{ user_home }}/.gitconfig" 
                 owner="{{ user }}" 
                 group="{{ user }}" 
                 mode=0644
