### ISSUE TITLE
"changed = False" when changing the referent on an already existing symlink

### ISSUE THREAD

**Issue by chris-gilmore** [ansible/ansible#1008]
In module 'file':
In the case when [ prev_state == 'link', state == 'link', old_src != src ], there appears to be a missing "changed = True".

**Comment by mpdehaan** [comment]
Please provide the action line from the playbook you are using and the output from 'ansible --version'.

**Comment by chris-gilmore** [comment]
If you look in https://github.com/ansible/ansible/blob/release-0.6/library/file, I think there should be the following line below line 337 and at the same indentation as line 337:
changed = True
