### ISSUE TITLE
Shell checksum validation fails on large files

### ISSUE THREAD

**Issue by axos88** [ansible/ansible#10086]
Current##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.2
  configured module search path = None
##### Environment:

Linux
##### Summary:

Current implementation reads whole file into memory. For files larger than available memory, it fails.
##### Steps To Reproduce:

Try fetching a large file from a remote server
##### Expected Results:

It should work
##### Actual Results:

 {"changed": false, "file": "/root/foobar-folyondar-sport.tar.gz", "msg": "unable to calculate the checksum of the remote file"}

(and the file does not get created locally)

**Comment by abadger** [comment]
Merged pull request.  Closing bug report :-)
