### ISSUE TITLE
setup.py not python3 friendly

### ISSUE THREAD

**Issue by gilou** [ansible/ansible#10094]
Hi,

When installing via pip with python3, it fails:

```
File "setup.py", line 12
    print "Ansible now needs setuptools in order to build. " \
                                                           ^
SyntaxError: Missing parentheses in call to 'print'
```

I'd assume this is to be backward compatible, but using print() in setup.py will probably fix it, then using `__future__` or any other 2to3 magic if compatibility with Python < 2.6 is a requirement there.

Not doing a PR, as I'm not sure what the policy is in this regard, but this is trivial, unless there are python3 incompatibilities somewhere else.

(This was tested on devel, 53a3644ecd49dc7e9ee1a5ba5131a9298055dd33)

**Comment by abadger** [comment]
Thanks!  I've merged your fix.
