### ISSUE TITLE
inventory is -i/--inventory-file on command line, "hostfile" in ansible.cfg

### ISSUE THREAD

**Issue by stenwt** [ansible/ansible#10104]
This seems arbitrary and confusing. Specifying "inventory" in ansible.cfg does nothing. The parameter, per docs at http://docs.ansible.com/intro_configuration.html is "hostfile".

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by maxamillion** [comment]
@bcoca I don't think this is a user question, is this really not considered to be an issue? 

There's inconsistent vocabulary which makes documentation unclear. If anything I would think this is an RFE to add consistency.
