### ISSUE TITLE
Unexpected output from ad-hoc redirect

### ISSUE THREAD

**Issue by vaporup** [ansible/ansible#10108]
Hi,

I am trying to collect all the facts from some systems and redirect the output to a file.
But using more than 1 fork, corrupts the output.

Doing it without a redirect, the output in the shell looks OK.

**prod-scansys.py** is my dynamic inventory script

ansible -f 1 -i prod-scansys.py all -m setup -u root > /tmp/test-1-fork.json
ansible -i prod-scansys.py all -u root -m setup  > /tmp/test-5-forks.json
- /tmp/test-1-fork.json looks fine
- /tmp/test-5-forks.json has mixed data

Here is a small snippet of the **/tmp/test-5-forks.json** content

```
        {
            "device": "/dev/mapper/srv001-srv+mysql",
            "fstype"srv001 | success >> {
"ansible_facts": {
```

As you can see, facts from different servers are mixed
which seems to be caused from the asynchronous return of the data.

Ansible Version 1.8.2 from the Ubuntu Precise PPA

Is this correct behaviour because without redirecting there is no problem
in the shell with more than 1 fork.

**Comment by sivel** [comment]
Instead of trying to do this type of redirect, you should instead look at using the `-t/--tree` argument.

The ansible ad-hoc command does not output valid JSON anyway on the CLI, with the tree argument you will get valid JSON files.

**Comment by vaporup** [comment]
Yeah, I remove the prefixed strings to make it valid JSON.
I did not use the tree argument because I pipe the output to **jq** after I made it valid JSON.
But it takes very long with 1 fork only and more forks don't work as described above...

**Comment by jctanner** [comment]
Ansible 1.8 added the fact caching feature which does allow to store facts into a json file without requiring extra redirect magic. http://docs.ansible.com/ansible/playbooks_variables.html#fact-caching

The other options are to use the template module and a to_nice_json filter to write out hostvars or use/write a custom callback plugin to store outputs as json.
