### ISSUE TITLE
sourcing env-setup produces stderr output 

### ISSUE THREAD

**Issue by wjimenez5271** [ansible/ansible#10109]
when sourcing the `env-setup` to setup ansible from source, I get the following output from stderr:

```
no previously-included directories found matching 'lib/ansible/modules/core/.git'
no previously-included directories found matching 'lib/ansible/modules/extras/.git'
```

I understand these are harmless based on https://github.com/ansible/ansible/issues/9951, however when sourcing this as part of my bash environment, this error becomes distracting each time I load a new shell. My workaround has been to redir stderr to /dev/null (in addition to stdout):

```
source ~/ansible/hacking/env-setup &> /dev/null
```

 but this seems less than ideal especially if there was an actual error I needed to be aware of. Is it possible to address this somehow? Or at least send it to stdout somehow? 

Thanks!

**Comment by abadger** [comment]
Does 

```
source ~/ansible/hacking/env-setup -q
```

satisfy your need?

**Comment by wjimenez5271** [comment]
@abadger Yes! that seems to work quite nicely. Perhaps this would be a helpful tip in the Installing Ansible doc? Is that something I can/should submit a PR for?

**Comment by abadger** [comment]
If it's along with the existing documentation on env-setup, that would be fine.  Thanks!
