### ISSUE TITLE
"script" module uses remote shell

### ISSUE THREAD

**Issue by ont** [ansible/ansible#10107]
**ansible version: 1.8.2**

Core module `script` always try to run script under user's default shell. When default shell is `fish` then there is a small problem. Here is a part of command being executed which was catched via `-vvv` option to `ansible-playbook`:

``` bash
ssh -C -tt ... root@some_host LANG=C LC_CTYPE=C /root/.ansible/tmp/ansible-tmp-1422366769.27-94901620936339/some_script.sh
```

... and `fish` doesn't understand `ENVNAME=VALUE` syntax. As a result whole command fails.

**possible solution**
Command must be wrapped into `/bin/sh -c "[...command...]"`  call

**Comment by abadger** [comment]
This should be addressed by setting the ansible_shell_type variable to fish for the host(s) in question: http://docs.ansible.com/intro_inventory.html#list-of-behavioral-inventory-parameters

I'm pasting the mailing list information below in case you need more help to get ansible_shell_type to work:

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
