### ISSUE TITLE
Perl version of ansible.module_utils

### ISSUE THREAD

**Issue by PWBENNETT** [ansible/ansible#10118]
If nobody objects, I'm going to write and contribute (to CPAN)  `Ansible::ModuleUtils.pm` to make it as easy to write modules in Perl as it is in Python (well, broadly as easy, I don't know the details yet). More info when I've got more to share.

**Comment by PWBENNETT** [comment]
I'll be keeping the development _outside_ the Ansible codebase (for now), at https://github.com/PWBENNETT/perl-Ansible-Module

**Comment by bcoca** [comment]
nice,

before you start, take a look at the v2 side of the tree as some changes
are happening, like deprecating the simple key=val interface to modules
(shifting towards the json).

## 

Brian Coca

**Comment by PWBENNETT** [comment]
Ah. I already kinda have started, but the way the code's coming together, it'll be easy enough to check `ARGV` for JSON before trying to parse it as key=value pairs.

**Comment by bcoca** [comment]
once done, we should add link to module development docs

**Comment by PWBENNETT** [comment]
Once done, I don't really have any objection to the Perl code moving _inside_ the Ansible codebase, if it's easy (and thuswise linked into the docs). For now, development is definitely best _outside_ it, because I mostly code by the power of wishful thinking, and that tends to not play well with a production project.

One thing that might be useful ... I'm probably going to have to write some moderately extensive API documentation for the Python original to make sure the Perl version is feature (and bug) compatible. I have no qualms whatsoever about merging my final API docs into the official Ansible docs.

**Comment by PWBENNETT** [comment]
I've started in on trying to clone some of the Python docs to Perl idioms, at https://github.com/PWBENNETT/perl-Ansible-Module/blob/master/lib/Ansible/Module.pm#L76 but don't think for one minute that it's even nearly complete. It's still very much a work in progress. I really need to sit down with a pot of coffee and the ansible_Module API documentation...

**Comment by PWBENNETT** [comment]
Oh, and I still haven't properly absorbed the JSON-based ARGV instead of key=value based, but I think I'm starting to get there.

**Comment by bcoca** [comment]
happy to hear you are active on this again. Since this requires no action on our part, I'm going to close this ticket, it will still work to direct google searches to your efforts and if you need anything on our side you can drop by ansible-devel (mailing list or irc).
