### ISSUE TITLE
host-pattern `ansible` vs `ansible-playbook`

### ISSUE THREAD

**Issue by fukawi2** [ansible/ansible#10124]
When running `ansible-playbook`, the `-l` option is available to limit the hosts to run on. This host-pattern can be comma or semicolon delimited.

The `ansible` command only accept a semicolon separate list of hosts for it's host pattern though. This requires quoting the string when running in shells where semicolon is a treated specially (eg, bash). If a comma-delimited list is given, ansible aborts with a "No hosts matched" error which is confusing, especially if you copy-paste a string of hosts from an earlier `ansible-playbook` command.

Can `ansible` accept a comma-delimited host-pattern like `ansible-playbook`?

**Comment by bcoca** [comment]
it can, but in the same place -i, which defines the current inventory

-i 'localhost,' works on both tools, ansible requires that you define the
target still, so you can add "all" at the end and it will target all the
hosts defined in -i (localhost in this case).

## 

Brian Coca

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by fukawi2** [comment]
​It was meant as a feature request/enhancement since there is disparity
between how the 2 tools interpret what a "host pattern" is.
