### ISSUE TITLE
No output from register in name

### ISSUE THREAD

**Issue by yerrysherry** [ansible/ansible#1013]
Hallo,
# cat test-register.yml

---
- hosts: aaagerrit-on-1-mgt
  user: root
  
  tasks:
  - name: cat test.txt
    local_action: command cat /var/tmp/test.txt
    register: var_test
  - name: copy ${var_test.stdout}
    action: command ls

The test.txt looks like this
# cat /var/tmp/test.txt

this is a test

ansible-playbook test-register.yml -vvvv

PLAY [aaagerrit-on-1-mgt] ********************\* 

GATHERING FACTS ********************\* 
<aaagerrit-on-1-mgt> ESTABLISH CONNECTION FOR USER: root
<aaagerrit-on-1-mgt> EXEC "$SHELL" -c 'mkdir -p /var/tmp/ansible-1346961867.88-108125590560644 && echo /var/tmp/ansible-1346961867.88-108125590560644'
<aaagerrit-on-1-mgt> REMOTE_MODULE setup 
<aaagerrit-on-1-mgt> PUT /tmp/tmpDKfwiF TO /var/tmp/ansible-1346961867.88-108125590560644/setup
<aaagerrit-on-1-mgt> EXEC "$SHELL" -c 'chmod u+x /var/tmp/ansible-1346961867.88-108125590560644/setup'
<aaagerrit-on-1-mgt> EXEC "$SHELL" -c /var/tmp/ansible-1346961867.88-108125590560644/setup
<aaagerrit-on-1-mgt> EXEC "$SHELL" -c 'rm -rf /var/tmp/ansible-1346961867.88-108125590560644/'
ok: [aaagerrit-on-1-mgt]

TASK: [cat test.txt] ********************\* 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: root
<127.0.0.1> EXEC "$SHELL" -c 'mkdir -p /var/tmp/ansible-1346961868.3-94373576820511 && echo /var/tmp/ansible-1346961868.3-94373576820511'
<127.0.0.1> REMOTE_MODULE command cat /var/tmp/test.txt
<127.0.0.1> PUT /tmp/tmple3Vrt TO /var/tmp/ansible-1346961868.3-94373576820511/command
<127.0.0.1> EXEC "$SHELL" -c 'chmod u+x /var/tmp/ansible-1346961868.3-94373576820511/command'
<127.0.0.1> EXEC "$SHELL" -c /var/tmp/ansible-1346961868.3-94373576820511/command
<127.0.0.1> EXEC "$SHELL" -c 'rm -rf /var/tmp/ansible-1346961868.3-94373576820511/'
ok: [aaagerrit-on-1-mgt] => {"changed": true, "cmd": ["cat", "/var/tmp/test.txt"], "delta": "0:00:00.002066", "end": "2012-09-06 22:04:28.867247", "rc": 0, "start": "2012-09-06 22:04:28.865181", "stderr": "", "stdout": "this is a test"}

TASK: [copy ${var_test.stdout}] ********************\* 
<aaagerrit-on-1-mgt> ESTABLISH CONNECTION FOR USER: root
<aaagerrit-on-1-mgt> EXEC "$SHELL" -c 'mkdir -p /var/tmp/ansible-1346961869.07-162198306523242 && echo /var/tmp/ansible-1346961869.07-162198306523242'
<aaagerrit-on-1-mgt> REMOTE_MODULE command ls
<aaagerrit-on-1-mgt> PUT /tmp/tmp9wSSnI TO /var/tmp/ansible-1346961869.07-162198306523242/command
<aaagerrit-on-1-mgt> EXEC "$SHELL" -c 'chmod u+x /var/tmp/ansible-1346961869.07-162198306523242/command'
<aaagerrit-on-1-mgt> EXEC "$SHELL" -c /var/tmp/ansible-1346961869.07-162198306523242/command
<aaagerrit-on-1-mgt> EXEC "$SHELL" -c 'rm -rf /var/tmp/ansible-1346961869.07-162198306523242/'
ok: [aaagerrit-on-1-mgt] => {"changed": true, "cmd": ["ls"], "delta": "0:00:00.001617", "end": "2012-09-06 22:04:29.280279", "rc": 0, "start": "2012-09-06 22:04:29.278662", "stderr": "", "stdout": "\u00e8!"}

PLAY RECAP ********************\* 
aaagerrit-on-1-mgt             : ok=3    changed=2    unreachable=0    failed=0    

TASK: [copy ${var_test.stdout}] ********************\* 

I thought, I should see this:

TASK: [this is a test] ********************\* 

Regards,
Gerrit

**Comment by mpdehaan** [comment]
register variables are per host, so  you won't see that expanded in the task headings.
