### ISSUE TITLE
A variable inserted a new parameter into the module args. Be sure to quote variables if they contain equal signs

### ISSUE THREAD

**Issue by sgabee** [ansible/ansible#10159]
I get an error when I try to run the following code:
- name: source level environment
  shell: source /xxx/SAS/PROD/Lev1/_level_env.sh; echo LEVEL_ROOT=$LEVEL_ROOT;
  register: sasLevel
- debug: var=sasLevel
- debug: var=sasLevel.stdout_lines
- set_fact: sasLevel_{{item}}
  with_items: sasLevel.stdout_lines

The result is as following:
TASK: [sas | debug var=sasLevel.stdout_lines] *********************************
ok: [sassrv] => {
    "sasLevel.stdout_lines": [
        "LEVEL_ROOT=/xxx/SAS/PROD/Lev1"
    ]
}

TASK: [sas | set_fact sasLevel_{{item}}] **************************************
fatal: [sassrv] => A variable inserted a new parameter into the module args. Be sure to quote variables if they contain equal signs (for example: "{{var}}").

FATAL: all hosts have already failed -- aborting

**Comment by mscherer** [comment]
Hi, could you try to paste again the code in a way that would not be interpreted as markdown ?

**Comment by sgabee** [comment]
Unfortunately, I cannot reproduce this issue. That is all I have now.
Actually, I was trying to solve this issue during the night and I have a solution.
In my opinion, the issue comes from the different version of Ansible. This code is not valid any more with this version. Anyway. The solution is to use read_facts command to define variables from the file.

name: source level environment
read_facts: varname=sasLevel file=/xxx/SAS/PROD/Lev1/level_env.sh flat=true

Thank you for your support!
