### ISSUE TITLE
expand validation to work with upstart 

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#10152]
Issue Type: Bug Report
Ansible Version: 1.9 (off devel, as of 5eafa1e7c3) 
Environment: Target: Ubuntu 14.04; Control machine: OS X 10.9.5 
Summary:

The template 'validate' command does not work with upstart configs as the temporary filename used for the action does not end in .conf (and instead is passed to init-checkconf as 'source').

This was referenced in passing in https://github.com/ansible/ansible/issues/9112 on September 24th, with @bcoca providing a "it wasn't meant to work for everything" statement (which I've warmed on when thinking about potential work-arounds).  I'm still opening the issue in case anyone has a clever idea of how to fix this and as a target for future searches.

Potential work-arounds: 
- not using the validate command on upstart templates 
- running init-checkconf in a future task and adding a failed_when clause
- using a customized init-checkconf script
- the template module allowing for a parameter that functions like "temporary_filename" as a work-around for scripts/programs that do file extension checks 
- my employer hiring an intern to verify my configs (and optionally act as a scapegoat when I break things) 

Steps To Reproduce:

Use the template module with the validate command for an upstart file.

Task:

```
- name: UWSGI should start with the OS
  template:
    src: upstart_emperor.conf
    dest: "/etc/init/uwsgi.conf"
    owner: root
    group: root
    mode: 0544
    validate: "init-checkconf %s"
```

Template (arbitary for contents, just needs to exist):

```
description "uWSGI Emperor"
start on runlevel [2345]
stop on runlevel [06]

exec /usr/local/bin/uwsgi --ini "/etc/uwsgi/emperor.ini"
```

run `ansible-playbook` with the playbook containing the task calling that template. 

Expected Results:

init-checkconfig should run against the file and either output:

```
File /etc/init/uwsgi.conf: syntax ok
```

or:

```
ERROR: File /etc/init/uwsgi.conf: syntax invalid
```

or should error out if the destination parameter given to the template module does not end in .conf.

Actual Results:

Running the task:

```
TASK: [uwsgi | UWSGI should start with the OS] ********************************
failed: [127.0.0.1] => {"failed": true}
msg: failed to validate: rc:1 error:ERROR: File must end in .conf
```

results in init-checkconf raising this error with a simple: 

   echo "$filename" | egrep -q '.conf$' || die "File must end in .conf"

With the variable printed on error, we have: 

```
msg: failed to validate: rc:1 error:ERROR: File must end in .conf ... Filename: source
```

Where 'source' as the filename is failing the file extension check.

**Comment by jooadam** [comment]
I still think that validation of changed configuration and rollback if needed should be handled by Ansible, rather than the user. Right now I am ditching validation of configuration files, because it is so much hassle.

**Comment by opoplawski** [comment]
Similar with trying to validate with systemd-analyze verify - it needs the appropriate .service, .timer, etc. suffix.

**Comment by thoughtless** [comment]
I am experiencing the same problem with Ubuntu Unity's `.desktop` files. My workaround is a script like this, which I use to validate:

``` sh
cp "$1" "$1.desktop"
desktop-file-validate "$1.desktop"
rm "$1.desktop"
```

**Comment by bcoca** [comment]
I'm going to close this, as I'm quoted above 'the validate option is for simple checks and not meant to work with everything'.

I recommend using a task with block/rescue to revert the changes instead.
