### ISSUE TITLE
Please document "--vault-password-file" in cli manpages

### ISSUE THREAD

**Issue by edrozenberg** [ansible/ansible#10177]
Hello,

It would be great if the manpages for ansible and ansible-playbook would document the option "--vault-password-file."  Currently the option can be discovered only by searching the internet.

Regards,
--Ed

**Comment by cemo** [comment]
+1

**Comment by mixpix3ls** [comment]
Looks like this can be closed given the following in Ansible 2.1.0.0:

$ **man ansible**
_--vault-password-file=VAULT_PASSWORD_FILE
A file containing the vault password to be used during the decryption of vault encrypted files. Be sure to keep this file secured if it is used. If the file is executable, it will be run its standard output will be used as the password._

$ **man ansible-playbook**
_--vault-password-file=VAULT_PASSWORD_FILE
Vault password file._

**Comment by edrozenberg** [comment]
Thanks, sounds great, trying to confirm but on Mac, when installing Ansible with PIP no man pages are installed. And Homebrew installation of Ansible is not recommended on Mac, I ran into problems with it. Will have to check on Linux instead.

**Comment by edrozenberg** [comment]
Confirmed the fixed manpages - on Linux installation of Ansible 2.1.0.0.
