### ISSUE TITLE
Missing/problematic support for su_pass in ssh.py

### ISSUE THREAD

**Issue by robparrott** [ansible/ansible#10170]
The following use of ansible-playbook with remote "su"-ing to root:

```
 ansible-playbook --su --ask-su-pass all mybook.yaml
```

Fails when we use the default ssh transport (and hence `ssh.py`) but succeeds when we use use the `transport = paramiko` connection driver.

The failure in the ssh driver occurred at this line:
- https://github.com/ansible/ansible/blob/release1.8.2/lib/ansible/runner/connection_plugins/ssh.py#L338

since the `self.runner.sudo_pass` variable is `None`. It makes sense that it is `None` since we aren't using sudo, but not sure why we ended up at this line in the first place. It appears that `utils.su_prompts.check_su_prompt(sudo_output)` does not evaluate to true so we end up in a sudo-specific loop.  

This code is quite complicated; it may make sense to break out "su"-related action into a separate block for maintainability reasons.

**Comment by sivel** [comment]
It looks like there is just some additional logic that needs to happen in that if statement to send the correct password perhaps similar to what is on line 351.

That specific loop is checking for the content in stderr.  We are overloading the meaning of the word "sudo" in various variables there since su was added.

**Comment by robparrott** [comment]
Right, and I suspect that the "overloading" makes the code harder to maintain, and hence error prone.

I also suspect that not that many people use su anymore, so this may be a backwater of ansible development. Our use case: we are using ansible to bring hosts into compliance (ssh pubkey + passwordless sudo), so just need to get hosts bootstrapped, and we won't touch su again.

**Comment by sivel** [comment]
The su use is actually pretty high.

**Comment by bcoca** [comment]
so there is a corner case where this fails, looking at fix. I'm refactoring most of this code soon in efforts of generalizing privilege escalation but will try to get in a fix soon.
