### ISSUE TITLE
why custom facts have to be pushed to the remote system?

### ISSUE THREAD

**Issue by r1k0** [ansible/ansible#10173]
Hi guys,

I have a need to gather more facts from a remote system so I made a custom fact. In this case I need the nfs mount points.

``` bash
#!/bin/bash

nfsmount="$(mount -l -t nfs)"

oldIFS=$IFS
IFS='
'
lines=( $nfsmount )
IFS=$oldIFS

cat <<EOF
[
EOF

for i in "${lines[@]}"; do
  if ! [ "$i" == "${lines[${#lines[@]}-1]}" ]; then
    echo "\"$i\","
  else
    echo "\"$i\""
  fi
done

cat <<EOF
]
EOF
```

It runs like this:

``` bash
root ~ # cat /home/rik/bla 
[all]
vsrv1942.int.belbone.Be
root ~ # ansible all -i /home/rik/bla -m setup -a "filter=ansible_local"
vsrv1942.int.belbone.Be | success >> {
    "ansible_facts": {
        "ansible_local": {
            "nfsmounts": [
                "zonecust1.nas-car.xxx.be:/ifs/zonecust1/mount6 on /pkg/sw type nfs (ro,noatime,rsize=32768,wsize=32768,soft,intr,tcp,nfsvers=3,addr=10.220.0.35)"
            ]
        }
    }, 
    "changed": false
}

root ~ # 
```

To have this I have to create on the remote system /etc/ansible/fact.d/nfsmounts.fact and push my fact there.

I don't understand why ansible requires the user to push his custom fact remotely.
I would expect ansible to let the user put the custom fact on the local system where ansible runs under /etc/ansible/fact.d. Ansible should pick it up and push it like it does for modules.

Why is this not consistent with the way ansible works? Ansible makes so much effort to have a minimal footprint on the remote host and there is that custom fact the user has to make sure it's pushed remotely.
The doc confirms that "If a remotely managed system has an “/etc/ansible/facts.d” directory, any files in this directory ending in ”.fact”, can be JSON, INI, or executable files returning JSON, and these can supply local facts in Ansible."

Why is this implemented this way? What am I missing?

**Comment by r1k0** [comment]
From my user point view, it's then easier to make a simple task out of this custom fact, register my output and work on that output so I don't have to create temp dirs on my remote (customer) hosts.

In addition how do I automate that with ansible? How do I automate cleanly and simply my custom fact push?
By creating tasks that would:
- create /etc/ansible/fact.d
- push custom fact
- run setup module
- remove /etc/ansible/fact.d

that's not convenient at all IMHO.

**Comment by bcoca** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

As a short answer, there are custom fact tasks/modules (bigip_facts, ec2_facts, etc), they just needed to return a json with { 'ansible_facts': ...} and you can run it as a normal task.

local facts are a additional way to add machine specific facts that can be static json or scripts, it is in addition, not instead, of fact tasks.
