### ISSUE TITLE
ansible-vault: missing editor message unclear

### ISSUE THREAD

**Issue by tspivey** [ansible/ansible#10182]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.8.2
  configured module search path = None
```
##### Environment:

Running Ubuntu 14.04.1 LTS.
##### Summary:

When ansible-vault invokes an editor, for example when creating a new file,
and that editor is not found,
the message presented is unclear about exactly what is going on.
##### Steps To Reproduce:
1. run: EDITOR=testing ansible-vault create test
##### Expected Results:

I expected ansible-vault to give me a bit more information to what was happening. For example, something like:

```
ERROR: Failed to launch editor: [Errno 2] No such file or directory
```

Maybe even what editor it was trying to launch.
##### Actual Results:

```
tyler@ubuntu:~$ EDITOR=testing ansible-vault create test
Vault password:
Confirm Vault password:
ERROR: [Errno 2] No such file or directory
```

**Comment by jcranky** [comment]
Which ansible version includes this fix? I'm using `ansible 2.0.1.0` and this is still happening. Took me a while to understand the problem.

**Comment by ssbarnea** [comment]
Such a joy, 3 guys spending 20 minutes before we found the same bug, a fully ansible experience.

**Comment by mrafieee** [comment]
JUST found never mind!

vim is the default editor!

how did you solve this?

I am running `ansible 2.0.0.2 (detached HEAD 7de237c5a1) last updated 2016/04/14 11:13:26 (GMT -400)
` 

and I have same proble in Debian stretch 9
