### ISSUE TITLE
connection type ssh, pipelining enabled, sudo, no requiretty in /etc/sudoers, results in task timeout

### ISSUE THREAD

**Issue by dmlary** [ansible/ansible#10180]
Issue Type: Bug Report
Ansible Version:

```
ansible 1.8.2
  configured module search path = None
```

Environment:
  Control system: Mac OSX
  Managed System: Ubuntu 14.04

Summary:
There is a syntax error in the ssh command used by ansible to create a connection and execute a sudo command on the target system (Ubuntu 14.04).  When the playbook runs from my control system (a Mac running OSX), I get the following output:

```
[macbook] dmlary:~/src/ansible-playbook> ansible --sudo -K -c ssh -vvvv -a 'ls' trusty
GATHERING FACTS ***************************************************************
<X.X.X.X> ESTABLISH CONNECTION FOR USER: dmlary
<X.X.X.X> REMOTE_MODULE command ls
<X.X.X.X> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/dmlary/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 X.X.X.X /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=ruvaixihqkqjdcvjzaklljaykditggfq] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-ruvaixihqkqjdcvjzaklljaykditggfq; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'"'"''
fatal: [trusty] => ssh connection error waiting for sudo or su password prompt
```

Running the ssh command by hand reveals the following error after the connection is established and authenticated:

```
[...]
debug1: Sending command: /bin/sh -c sudo -k && sudo -H -S -p "[sudo via ansible, key=ruvaixihqkqjdcvjzaklljaykditggfq] password: " -u root /bin/sh -c 'echo SUDO-SUCCESS-ruvaixihqkqjdcvjzaklljaykditggfq; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
[...]
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-u user] file ...
```

Notice the `debug1` line above; there are no quotes surrounding the command being passed to `/bin/sh`.  Running a similar command by hand on the target system (with shell debugging enabled), I get this:

```
dmlary@trusty:~$ /bin/sh -xvc sudo -k && echo it worked
+ sudo
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-u user] file ...
```

It appears as if `/bin/sh` is eating the `-k`.  When we run the command fully quoted, we get the expected results:

```
dmlary@trusty:~$ /bin/sh -xvc 'sudo -k && echo it worked'
+ sudo -k
+ echo it worked
it worked
```

As previously stated, this is a Ubuntu 14.04 system, so `/bin/sh` is linked to `/bin/dash`.

```
dmlary@trusty:~$ ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Feb 19  2014 /bin/sh -> dash
```

I can get the command to execute correctly from the control system (the Mac) by placing double quotes within the outer-most single quotes of the command passed to ssh, and escaping the double quotes to the `-p` flag of `sudo`:

```
ssh -t -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/dmlary/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 X.X.X.X /bin/bash -xvc '"sudo -k && sudo -H -S -p \"[sudo via ansible, key=aqwowfvneqmfeajjcckpqpkzuiyreeoq] password: \" -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-aqwowfvneqmfeajjcckpqpkzuiyreeoq; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'"'"'"'
```

There is one similar issue, #9544, that has comments reflecting this behavior after a fix for a paramiko hang has been merged.  This is likely the problem that the commenter is encountering.

**Comment by abadger** [comment]
I am unable to replicate this problem using 1.8.2 on a Fedora machine to talk to Ubuntu14.04.  My output is different as well.  For instance, I get prompted for a password.  Not being prompted for a sudo password would definitely cause the error you are seeing.  Have you posted the complete output from running your command?

```
$ ansible --sudo -K -c ssh -vvvv -a 'ls /root/' ubuntu14           (07:29:41)
sudo password: 
<ubuntu14> ESTABLISH CONNECTION FOR USER: badger
<ubuntu14> REMOTE_MODULE command ls /root/
<ubuntu14> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/badger/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 ubuntu14 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1423409387.03-269149789527102 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1423409387.03-269149789527102 && echo $HOME/.ansible/tmp/ansible-tmp-1423409387.03-269149789527102'
<ubuntu14> PUT /var/tmp/tmpUgpshf TO /home/badger/.ansible/tmp/ansible-tmp-1423409387.03-269149789527102/command
<ubuntu14> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/badger/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 ubuntu14 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=iyuauyksdavtujldavldaitwlehtrkoj] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-iyuauyksdavtujldavldaitwlehtrkoj; LANG=C LC_CTYPE=C /usr/bin/python /home/badger/.ansible/tmp/ansible-tmp-1423409387.03-269149789527102/command; rm -rf /home/badger/.ansible/tmp/ansible-tmp-1423409387.03-269149789527102/ >/dev/null 2>&1'"'"''
ubuntu14 | success | rc=0 >>
ansible_testing
```

(Note: it appears the linked issue is different.  It talks about ansible hanging and expects it to time out instead.  In your care, you are getting a timeout but are expecting a command to run successfully).

**Comment by bcoca** [comment]
fyi, that you don't see quotes in the return is just a formatting issue on
the error reporting side, the code quotes everything after 'sh -c'

## 

Brian Coca

**Comment by dmlary** [comment]
I am prompted for the sudo password, I just didn't include it in the bug report (sorry).  Full output:

```
[macbook] dmlary:~/src/ansible-playbook> ansible --sudo -K -c ssh -vvvv -a 'ls /root/' trusty
sudo password:
<X.X.X.X> ESTABLISH CONNECTION FOR USER: dmlary
<X.X.X.X> REMOTE_MODULE command ls /root/
<X.X.X.X> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/dmlary/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 X.X.X.X /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=ejcjqojcsxnarcbdhpnsxlooqjkuroeu] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-ejcjqojcsxnarcbdhpnsxlooqjkuroeu; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'"'"''
trusty | FAILED => ssh connection error waiting for sudo or su password prompt
```

Similar to you, I'm unable to get this to reproduce on another control machine.  The one experiencing the problem is running OSX 10.8.5, with OpenSSH 5.9p1.  The one where it works is running OSX 10.9.5, with OpenSSH 6.2p2.  I'm going to try to upgrade ssh on the problem system (via homebrew) and see if this resolves the issue.

**Comment by dmlary** [comment]
And that was a quick rule-out.  The OpenSSH version is not the problem.  Next guess: python version; problem system is running 2.7.2, working system is 2.7.5.  Both are the default python included in OSX.

**Comment by dmlary** [comment]
Alright, I'm baffled.  I've updated everything I can imagine (short of upgrading the full OS), and verified the new versions are being executed, but I've had no luck in getting the command to succeed.

```
[macbook] dmlary:~/src/ansible-playbook> ssh -V
OpenSSH_6.7p1, OpenSSL 1.0.2 22 Jan 2015
[macbook] dmlary:~/src/ansible-playbook> python --version
Python 2.7.9
[macbook] dmlary:~/src/ansible-playbook> ansible --version
ansible 1.9 (devel 8f06ba2bc1) last updated 2015/02/08 11:07:43 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 600fc15b42) last updated 2015/02/08 11:08:02 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 77485f6c6a) last updated 2015/02/08 11:08:10 (GMT -500)
  v2/ansible/modules/core: (detached HEAD 600fc15b42) last updated 2015/02/08 11:08:18 (GMT -500)
  v2/ansible/modules/extras: (detached HEAD 77485f6c6a) last updated 2015/02/08 11:08:26 (GMT -500)
  configured module search path = None
[macbook] dmlary:~/src/ansible-playbook> ansible --sudo -K -c ssh -vvvv -a 'ls /root/' trusty
sudo password:
<X.X.X.X> ESTABLISH CONNECTION FOR USER: dmlary
<X.X.X.X> REMOTE_MODULE command ls /root/
<X.X.X.X> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/dmlary/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 X.X.X.X /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=muwcqzbzeasiajnpkuelcwllvetyipqg] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-muwcqzbzeasiajnpkuelcwllvetyipqg; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'"'"''
trusty | FAILED => ssh connection error waiting for sudo or su password prompt
```

Any ideas?

**Comment by dmlary** [comment]
If the verbose output of ansible is correct, then the final argument to the ssh command is not quoted correctly.  The issue here is that ssh will take all arguments (that aren't flags) as the command to execute on the remote host.  Those arguments are executed using `system()`.  The way things are executing now, ssh on the control host is being invoked as `exec('ssh', '-C', '-vvv', [...], '192.168.1.1', '/bin/sh', '-c', 'sudo -k && [...]')`.  As a result, the quoting around the `-c` argument is lost when passed to the ssh server.  On that side they end up doing an `exec('/bin/sh', '-c', 'sudo', '-k', '&&', [...])`.  This is because the server doesn't perform an `exec()` with the arguments that came from the client, it appears to call `system()` instead.  To verify this you can run `ssh <host> "ls / && echo ran via system()"`.  If the command were being executed via any of the flavors of `exec()`, the output would be very different.

Now all of that aside, I have no damn clue why it works some places and not others.

**Comment by dmlary** [comment]
Ok, despite my last comment, quoting is not the root cause of this issue.

I hopped on the target system and started tailing `/var/log/auth.log` while running the ansible command.  I noticed that within a few seconds of authenticating, I'd get the following errors:

```
Jan 18 18:05:54 trusty sudo: pam_unix(sudo:auth): conversation failed
Jan 18 18:05:54 trusty sudo: pam_unix(sudo:auth): auth could not identify password for [dmlary]
```

A while later, ansible would time out.  I ran it again, and hit ctrl-C in ansible as soon as I saw the sudo error message appear in the auth log.  I then re-ran the ansible command and it worked.

It appears as though the hang only occurs when the first command sent to the target following the initial connect is the `sudo` command.  If I kill ansible and retry immediately, while the control connection is still established, everything works.  

The command @abadger posted first creates the `$HOME/.ansible/tmp/[...]` directory, before executing the sudo.  Is there any way I can enable that command (for testing), or you can disable it to attempt to reproduce?

**Comment by dmlary** [comment]
Reviewed my ansible.cfg and found that I had `pipelining` enabled.  When I disabled it, the problem went away.  I've verified that my `/etc/sudoers` file does not have `requiretty` set; it's the default sudoers file from a clean install.

**Comment by jstasiak** [comment]
Edit for clarity: **this comment should be ignored, it's not related to the issue**

For what it's worth I'm experiencing similar (or even the same) issue.
- Ansible 1.9.1 from PyPI
- Debian 7
- Python 2.7.3

This is what Ansible passes to `subprocess.Popen`:

``` python
# without pipelining, result: works ok
[
    'ssh',
    '-C',
    '-tt',
    '-vvv',
    '-i',
    'PATH_TO_SSH_KEY',
    '-o',
    'KbdInteractiveAuthentication=no',  
    '-o',
    'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey',
    '-o',
    'PasswordAuthentication=no',
    '-o',
    'User=admin',
    '-o',
    'ConnectTimeout=10',
    'IP_ADDRESS',
    "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1433322706.7-193671476492749 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1433322706.7-193671476492749 && echo $HOME/.ansible/tmp/ansible-tmp-1433322706.7-193671476492749'",
]

# with pipelining, result: sudo usage information message is triggered

[
    'ssh',
    '-C',
    '-vvv',
    '-i',
    'PATH_TO_SSH_KEY',
    '-o',
    'KbdInteractiveAuthentication=no',  
    '-o',
    'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey',
    '-o',
    'PasswordAuthentication=no',
    '-o',
    'User=admin',
    '-o',
    'ConnectTimeout=10',
    'IP_ADDRESS,
    u'/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=bckiuwlzoyzguzzlqxffqdwoofroruhy] password: " -u root /bin/sh -c \'"\'"\'echo BECOME-SUCCESS-bckiuwlzoyzguzzlqxffqdwoofroruhy; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python\'"\'"\'\'',
]
```

From what I see the issue does _not_ exist in devel (3e2e81d8960) anymore.

**Comment by jstasiak** [comment]
Please disregard my previous comment, it was unrelated issue connected to the fact that the SSH key I was pointing Ansible to was incorrect.

**Comment by jimi-c** [comment]
@dmlary since this is a somewhat complex issue, could you please test against the current devel branch and see if you are still seeing this issue there?

**Comment by jerrac** [comment]
When using stable-1.9, I run into this issue as well.

```
ansible --sudo -K -c ssh -vvvv -a 'ls' -i inventory.ini --vault-password-file     ../../.vaultpass.txt example.tld
SUDO password: 
<ip.ip.ip.ip> ESTABLISH CONNECTION FOR USER: username
<ip.ip.ip.ip> REMOTE_MODULE command ls
<ip.ip.ip.ip> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/username/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 ip.ip.ip.ip /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=rlsdtnfaeztqejnabmgjzclfiitfztdv] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-rlsdtnfaeztqejnabmgjzclfiitfztdv; LANG=C LC_CTYPE=C /usr/bin/    python'"'"''
example.tld | FAILED => ssh connection error while waiting for sudo password prompt
```

After commenting out `pipelining = True`, the command listed all files in my users directory.

When I checked out the devel branch and uncommented `pipelining = True`. The command also worked. 

So devel is fixed. Which is nice for development work, but not so nice if you are trying to run in production while using pipelining. 

Edit:
My desktop is Ubuntu 14.04
example.tld is Ubuntu 14.04
My ansible push server is Ubuntu 12.04, turning off pipelining on that server fixed it there as well. It's running 1.9.2 from pip.

**Comment by jimi-c** [comment]
@jerrac understood. However, since this change did require some extensive rewriting of how the become sub-system works I don't think we'd be able to backport this to the stable-1.9 branch.

As a result, I'm going to go ahead and close this for now, as we are aiming at releasing 2.0 in about a month, at which time this will be generally available. For the record, we typically close issues once they're fixed in devel, so this is standard operating procedure.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
