### ISSUE TITLE
Attribute 'skipped' is not set on command module output when using 'creates'.

### ISSUE THREAD

**Issue by Sgydoo** [ansible/ansible#10196]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible 1.8.2 - installed via the EPEL repository:

```
$ ansible --version
ansible 1.8.2
  configured module search path = /usr/share/ansible
```
##### Environment:

Issue reproducible on Oracle Linux 6.5 and Amazon Linux 2014.09.
##### Summary:

In Ansible 1.8.2, the 'skipped' attribute on a registered variable is not being set in the output from a 'command' module task using 'creates'. This makes it difficult to control subsequent tasks.

This issue is not present in Ansible 1.7 (EPEL) or Ansible 1.7.1 (Debian Wheezy).
##### Steps To Reproduce:

Playbook - skipped.yml:

```

---
- hosts: all
  tasks:
    - name: Check whether file exists
      command: /bin/true creates=/tmp/file
      register: check_file

    - name: debug check_file
      debug: var=check_file

    - name: Pause for 1 second
      pause: seconds=1
      when: not check_file|skipped
```

Inventory File - hosts:

```
[local]
localhost   ansible_connection=local
```

Command:

```
ansible-playbook -i hosts skipped.yml
```
##### Expected Results:

This is the 'check_file' variable using previous version Ansible 1.7 from EPEL

```
TASK: [debug check_file] ****************************************************** 
ok: [localhost] => {
    "check_file": {
        "changed": false, 
        "cmd": "/bin/true", 
        "invocation": {
            "module_args": "/bin/true creates=/tmp/file", 
            "module_name": "command"
        }, 
        "rc": 0, 
        "skipped": true, 
        "stderr": false, 
        "stdout": "skipped, since /tmp/file exists", 
        "stdout_lines": [
            "skipped, since /tmp/file exists"
        ]
    }
}
```
##### Actual Results:

This is the 'check_file' variable using Ansible 1.8.2. The output is identical except the 'skipped' attribute is missing, causing the skipped macro to return false. In this case the following 'pause' task always runs whether the file exists or not.

```
TASK: [debug check_file] ****************************************************** 
ok: [localhost] => {
    "check_file": {
        "changed": false, 
        "cmd": "/bin/true", 
        "invocation": {
            "module_args": "/bin/true creates=/tmp/file", 
            "module_name": "command"
        }, 
        "rc": 0, 
        "stderr": false, 
        "stdout": "skipped, since /tmp/file exists", 
        "stdout_lines": [
            "skipped, since /tmp/file exists"
        ]
    }
}
```

**Comment by abadger** [comment]
Looks like this was an intentional change: https://github.com/ansible/ansible/issues/8645

The rationale is that if creates= is satisfied then this is really more of a changed=False status, not a skipped status (which is more for not running the task at all).  Does checking the changed attribute of the registered value allow you to accomplish what you need to?

**Comment by Sgydoo** [comment]
Yes, it looks like checking the changed attribute does the trick.

In summary, this playbook works in versions 1.7, 1.7.1 and 1.8.2:

```
---
- hosts: all
  tasks:
    - name: Check whether file exists
      command: /bin/true creates=/tmp/file
      register: check_file

    - name: debug check_file
      debug: var=check_file

    - name: "Pause for 1 second if /tmp/file doesn't exist"
      pause: seconds=1
      when: check_file|changed
```

Thanks for your help!

Simon.

**Comment by bcoca** [comment]
closing as this is how it is meant to work
