### ISSUE TITLE
Use localhost ansible_python_interpreter with local_action/delegate_to

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#1019]
Thanks to a tip earlier, I'm using `ansible_python_interpreter` to jiggle with the Python version nodes can use: hosts in my inventory have that variable set accordingly.

Installing 0.7 now allows me to use some of the new cool features, but I find certain inconsistencies:
1. Jinja2 templates don't use the specified interpreter. The following code complains that `simplejson` cannot be imported, though the Python-2.7.3 I point to with `ansible_python_interpreter` can, indeed, `import json`:

```
{{ ansible_facts | to_json }}
```
1. A Playbook which has a `local_action: template src=xx.j2 dest=/tmp/xx` uses the default `/usr/bin/python` on the target system (i.e. `127.0.0.1`) instead of that configured with `ansible_python_interpreter`.

**Comment by jpmens** [comment]
First point probably due to second point: the template was being run in the `local_action`.

**Comment by mpdehaan** [comment]
So not a bug?

**Comment by jpmens** [comment]
I think 2nd point is a bug. (Sorry: it's formatted as 1. a second time...)

**Comment by mpdehaan** [comment]
local_action does not require that the given host be in inventory and always picks 127.0.0.1

we /could/ try an explicit lookup of whatever is specified in delegate_to (aka try localhost then 127.0.0.1 if local_action)  and try to use those variables, although currently the various variables made available to the host are usable in the local_action line.  We'd want to only add ansible_python_interpreter from that inventory record if it exists (and being cool about it if it was not there) to the inject directionary.

**Comment by jpmens** [comment]
I've just tested the following:

```
cat hosts
[clients]
a1.ww.mens.de
k4.ww.mens.de ansible_python_interpreter=/tmp/foo
```

with this playbook:

```
---
- hosts: clients
  user: f2
  sudo: True
  tasks:
  - name: Tell master
    action: shell echo "${ansible_fqdn} done" >> /tmp/list
    delegate_to: k4.ww.mens.de
```

expecting `delegate_to` to fail due to impossible Python interpreter. Unfortunately, it doesn't fail. :-)

I think it's important to pass on `ansible_python_interpreter` to whichever host I'm delegating to; "localhost" and "127.0.0.1" as well.

**Comment by mpdehaan** [comment]
fix pushed

**Comment by jpmens** [comment]
Not working in 0.8.tar
