### ISSUE TITLE
make fetch use slurp when sudo is set?

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#1020]
0.7 release: using `fetch` module, I experience the following of which I'd consider the first a bug, the rest cosmetic or documentation issues: (All examples running in a Playbook with `sudo: true`)
1. `fetch` cannot retrieve, say, `/etc/sudoers` (mode 0640). Verbose shows `msg=no read permission on remote file, not transferring, ignored`, `changed: false`; this is a bug.
2. Fetching a non-existent file from remote shows up as "ok" (green). Probably fine, ought to be documented though.

BTW, solved the first with

```
- action: command install -m 444 /etc/sudoers /etc/sudoers.pre-ansible creates /etc/sudoers.pre-ansible
- action: fetch ....
```

Just gotta love Ansible! :-)

**Comment by mpdehaan** [comment]
Seems like you were just running as a user without permission on the file?

Not a bug?

**Comment by jpmens** [comment]
I wrote:

> All examples running in a Playbook with sudo: true

I think it is a bug: I can `copy` _to_ the machine and overwrite any file, so I should be able to `fetch` any file _from_ that same machine. :)

**Comment by mpdehaan** [comment]
Ah, that.

We would have to make fetch use slurp if sudo is set.

Doable, just not a good fit for large files.
