### ISSUE TITLE
ansible-vault view writes world readable files in /tmp

### ISSUE THREAD

**Issue by NicolasLM** [ansible/ansible#10214]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.2
##### Environment:

Debian 7
##### Summary:

`ansible-vault view` do not set the proper umask when writing the temporary file to /tmp. Thus on many systems it makes the file world readable. Files managed by ansible-vault often containing sensitive data, this may be a security issue.
##### Steps To Reproduce:

```
ansible-vault view yourfile.yml
ls -l /tmp
```

Expected Results:

```
$ ll /tmp/
total 4.0K
-rw------- 1 admin admin 183 Feb 11 12:44 tmpsh0oJU
```

Actual Results:

```
$ ll /tmp/
total 4.0K
-rw-r--r-- 1 admin admin 183 Feb 11 12:45 tmpXC744q
```

**Comment by bcoca** [comment]
closed through merged PR
