### ISSUE TITLE
The authorized_keys documentation does not specify that giving key a URL is available since 1.9

### ISSUE THREAD

**Issue by hawkowl** [ansible/ansible#10223]
##### Issue Type:

(Documentation) Bug Report
##### Ansible Version:

1.7.1, 1.8.2 (now devel)
##### Environment:

N/A, but OS X
##### Summary:

The documentation (http://docs.ansible.com/authorized_key_module.html) says that using the key param with a URL will download and use that key, however it's not available in any "released" Ansible, and the documentation does not say that it requires the (unreleased) 1.9.
##### Steps To Reproduce:
1. See this in the docs:

```
# Using github url as key source
- authorized_key: user=charlie key=https://github.com/charlie.keys
```
1. Try it in 1.8.2
##### Expected Results:

It works as per the documentation
##### Actual Results:

It doesn't work, as it's not in an Ansible I could get through pip. The docs should say that it's available in 1.9 and up, to make it clear that it's a new feature.

(That being said, the new feature is wonderful, thankyou <3 )

Thanks to jmainguy on IRC for helping me track it down!

**Comment by bcoca** [comment]
added https://github.com/ansible/ansible-modules-core/commit/55b06568b0d02965808071141f0126a9d0cd30ae to document this, it will go to docs.ansible.com on next rebuild

**Comment by hawkowl** [comment]
Thanks! :)
