### ISSUE TITLE
Provide host UUID in Ansible facts

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#10221]
Ansible should provide a consistent machine ID (UUID) in facts, if available. Sources of consistent UUIDs are, according to [machine-id](http://man7.org/linux/man-pages/man5/machine-id.5.html) manpage:
- `/etc/machine-id`
- `/var/lib/dbus/machine-id`

If these aren't available on a system, as an alternative, Ansible could provide a random UUID in a separate fact, depending on presence of `uuidgen` utility on Ansible Controller host. Then user could grab that randomly generated UUID and save it in local Ansible facts for later consistent use, for example:

```
var_uuid: '{{ ansible_local.root.uuid | default(ansible_machine_id | default(ansible_random_uuid)) }}'
```

UUID can be used to identify a host uniquely for accounting, tracking virtual machines or containers across systems, etc.

**Comment by bcoca** [comment]
I'm fine with pulling existing uuid, but would not want to create and track our own as there can be divergence when not forcing the use of a  centralized data store (which currently ansible does not require). I would leave that for other tools.

**Comment by mihirvj** [comment]
I am looking into implementing this. I am new to this project, so please pardon any silly question. Can you tell me where should we put this pulled UUID? I mean what should we nest it under?

**Comment by drybjed** [comment]
@mihirvj I think something like `ansible_machine_id` for the `/etc/machine-id` / `/var/lib/dbus/machine-id` contents.

**Comment by mihirvj** [comment]
Added to commit #10235

**Comment by drybjed** [comment]
@mihirvj You should probably post that in a separate PR.

**Comment by mihirvj** [comment]
Did it in #10284. Thanks
