### ISSUE TITLE
apt module should list changed packages (updates/downgrades/installs/...) in check mode

### ISSUE THREAD

**Issue by ibotty** [ansible/ansible#10239]
Maybe only when --diff is also specified.

I might implement that myself, if there is support of this idea.

**Comment by ibotty** [comment]
that's a feature idea, but i can't add any labels afaict.

**Comment by sivel** [comment]
This issue should probably be logged in the ansible-modules-core repo, since that is where the apt module is located.

**Comment by bcoca** [comment]
closing this as it is in wrong repo and we already have a PR to track it in the correct one (linked above).
