### ISSUE TITLE
wrong umask calculation in AnsibleModule.atomic_move

### ISSUE THREAD

**Issue by stratoukos** [ansible/ansible#10257]
The correct permission for a new file are calculated using `0666 ^ umask`. While xor yields the correct result for the most common umask (022) it is incorrect. For example a umask of 077 should create files with 600 permissions, but ansible creates them with 611 (0666 ^ 0077).

The correct calculation is `0666 & ~umask`

**Comment by abadger** [comment]
that looks right to me.  @stratoukos, if you want to open a PR for your change I can merge it so people know you fixed it.  If that's too much trouble I can just adjust the code.  Whichever you prefer.

**Comment by bcoca** [comment]
closed through #10258 10258

**Comment by stratoukos** [comment]
Shouldn't this be fixed for the 1.8 release as well? I can cherry pick the patch on top of release1.8.4.
