### ISSUE TITLE
Unable to Set Umask / Mode for Git Module

### ISSUE THREAD

**Issue by bbakersmith** [ansible/ansible#10279]
There appears to be no way to make the Git module (among others) respect any umask setting besides the Ansible default of 022. I have tried globally setting umask using pam_umask, and locally with .bashrc.

All our Git repos need group read / write permissions, not the Ansible default 600. Can you tell me how this can be overridden? Instead I've had to resort to using shell commands rather than the Git module, because that allows me to set umask manually before executing git clone.

**Comment by eigood** [comment]
I tried to send in a MR for this, but it got closed.  I'll resend.

**Comment by jctanner** [comment]
Resolved by https://github.com/ansible/ansible-modules-core/pull/4473
