### ISSUE TITLE
Mention 'is undefined' in docs instead of 'is not defined'

### ISSUE THREAD

**Issue by hkariti** [ansible/ansible#10273]
##### Issue Type:

Documentation report
##### Ansible Version:

1.8.2
##### Environment:

NA
##### Summary:

The docs mention using 'is not defined' for checking if a variable is undefined. However, this fails for nested dicts:

```
- hosts: localhost
  tasks:
    - debug:
      when: a.b.c.d is not defined
```

throws an error, while `a.b.c.d is undefined` skips the task as expected.

**Comment by bcoca** [comment]
closed via merged #11735
