### ISSUE TITLE
Slow deployment using winrm over https

### ISSUE THREAD

**Issue by cerowain** [ansible/ansible#10288]
Sorry, first bug report here.  Let me know if I've messed anything up, not provided enough info.

Issue Type: Bug Report
I'm not 100% sure it is a bug, perhaps there is a reason for the way it is.

Ansible Version: ansible 1.9
Freshly built RPM from git - ansible-1.9-0.git201502182043

Environment: CentOS 6.5

Summary:

I found on updating Ansible I found that a test playbook to windows took a long time to run.  
Debug output showed that it was attempting to use http rather than https for the endpoint despite my port being set to 5986. 
Further investigation showed that the transport_schemes in winrm.py ordered the schemes for https as 
kerberos-https
plaintext-http
plaintext-https

As I was not using kerberos it was falling to plaintext-http

I believe the correct code should be 

transport_schemes = {
        'http': [('kerberos', 'http'), ('plaintext', 'http'), ('plaintext', 'https')],
        'https': [('kerberos', 'https'), ('plaintext', 'https'), ('plaintext', 'http')],
        }

Changing to this sped up windows connections as the http connection no longer had to time out.

Steps To Reproduce:

Run Ansible playbook against windows host.

Expected Results:
Ansible will use the https transport before http

Actual Results:

Ansible uses http transport before https

<oxygenwin05-1> endpoint=http://oxygenwin05-1:5986/wsman transport=plaintext
<oxygenwin05-1>
<oxygenwin05-1> endpoint=https://oxygenwin05-1:5986/wsman transport=plaintext

**Comment by cerowain** [comment]
This looks to have been addressed in bug #10316

**Comment by bcoca** [comment]
closing through merged #10316
