### ISSUE TITLE
extra-vars doesn't work with chroot connection type

### ISSUE THREAD

**Issue by rofinn** [ansible/ansible#10299]
##### Ansible Version:

```
ansible --version
ansible 1.8.4
  configured module search path = None
```
##### Environment:

Probably not related but it is 'Debian 3.2.57-3+deb7u1 x86_64 GNU/Linux'
##### Summary:

Using `--extra-vars` with a chroot connection type doesn't work.  More specifically, the playbook will complete without error if the extra vars aren't used or if they are defined elsewhere, but the values supplied appear to be ignored.
##### Steps To Reproduce:

Given a Debian chroot environment, created via [bootstrap-vz](https://github.com/andsens/bootstrap-vz) and located at `/target/71c89a96/root`. If I run the following playbook:

```
# test.yml

---
- hosts: all
  tasks:
    - debug: msg="{{ foo }}"
```

with the following inventory file located at `/target/71c89a96/root/tmp/bootstrap-inventory`

```
/target/71c89a96/root ansible_connection=chroot
```

like so

```
ansible-playbook -i /target/71c89a96/root/tmp/bootstrap-inventory test.yml --extra-vars "foo=bar"
```
##### Actual Results:

I get the following output

```

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [/target/71c89a96/root]

TASK: [debug msg="{{ foo }}"] *************************************************
fatal: [/target/71c89a96/root] => One or more undefined variables: 'foo' is undefined

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
to retry, use: --limit @/root/test.retry
```
##### Expected Results:

I've tested that this works outside of the chroot like so.

```
$ hostname > inventory
$ ansible-playbook -i inventory test.yml --extra-vars "foo=bar" --connection=local
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [ip-10-120-175-173]

TASK: [debug msg="{{ foo }}"] ************************************************* 
ok: [ip-10-120-175-173] => {
    "msg": "bar"
}

PLAY RECAP ******************************************************************** 
```

**Comment by abadger** [comment]
# Cannot Reproduce

@Rory-Finnegan and I took a look at this together at pycon and couldn't reproduce it with several chroots produced outside of bootstrap-vz.  We think that the setup of the chroot needs some tweaking rather than ansible.
