### ISSUE TITLE
Ability to change state of node in F5

### ISSUE THREAD

**Issue by perzizzle** [ansible/ansible#10307]
Issue Type:

Feature Idea

Ansible Version:

ansible 1.8.2

Environment:

RHEL 6.5

Summary:

As part of the bigip_node module I would like the ability to set the state of a node. This would accomplish the equivalent of going to Local Traffic>Nodes>$nodeName>State=enabled|disabled|forced offline from the web interface.

Steps To Reproduce:

Not applicable

Expected Results:

Not applicable

Actual Results:

Not applicable

**Comment by srgvg** [comment]
This might be a simple addition to the `extras/network/f5/bigip_node.py` module I can look into.

BTW, shouldn't this be a ticket in the https://github.com/ansible/ansible-modules-extras repo?

**Comment by perzizzle** [comment]
Moved to ansible-modules-extras
