### ISSUE TITLE
Add support for documenting custom modules deprecated facts

### ISSUE THREAD

**Issue by ismaGNU** [ansible/ansible#10303]
Since 1.8.2 (correct if I am wrong) it is not possible to return facts like old times:

ex: "changed=True msg=Ok"

Instead you always have to provided a JSON fact in order to work, like:

ex: {"changed":"true", msg:"ok"}

I have to rewrite a custom shell script that suddenly began to fail. I have trouble to find these kind of documentation.

Thanks in advance!

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
