### ISSUE TITLE
Default command line parameters

### ISSUE THREAD

**Issue by mavimo** [ansible/ansible#1031]
Create a default `.ansible` file to store dafault value for command line params, so each execution user don't need to specify all parameters.

When i create a filel `.ansible` in the project folder (/home/myuser/myproject/ ) containing:

```
inventory=/home/myuser/some/folder/inventory/project-hosts
extra-vars=somevar|somevalue
```

from folder `/home/myuser/myproject/` I can execute:

```
ansible-playbook myproject.yml
```

inside

```
ansible-playbook -i /home/myuser/some/folder/inventory/project-hosts -extra-vars somevar=somevalue myproject.yml
```

This can help people that use ansible in some different projects without typing all required params each time (yes, i know I can write a small pash script each time, but using .ansible file can help do have default value overridable from CLI, without adding params in playbooks).

**Comment by mpdehaan** [comment]
There already is a configuration file, see the examples directory

It is searched for in either: /etc/ansible/ansible.cfg, or ~/ansible.cfg

It allows specifying -i, and I will accept patches to make it accept the values for --extra-vars

I don't think we want one in the project folder, this would be a good case for having a shell script wrapper or Makefile

**Comment by mavimo** [comment]
Sorry, I missed this information from docs, thanks!
