### ISSUE TITLE
Question: best platform to run client from?

### ISSUE THREAD

**Issue by blysik** [ansible/ansible#10333]
Hi,

I want to be able to do Ansible runs across large (2k+) fleets of machines, with the usual problems that may be present in large deployments.  (Some hosts aren't pinging, some are pinging but don't respond well to ssh, variety of operating systems.)

Which platform is the best supported in terms off ssh and development for running Ansible from?

Currently I'm running Mac OS X Yosemite, but I know ssh versions have been suspect in the past. 

Thanks in advance.

**Comment by bcoca** [comment]
I ran from gentoo, freebsd, debian and ubuntu without any issues, any
rhel/centos and derivatives should also work fine.

## 

Brian Coca

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
