### ISSUE TITLE
verify that the git module is happy to be run a second time

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1034]
Someone reported a problem on the second wakeup of ansible-pull because the directory already existed.

See if this occurs.

**Comment by cocoy** [comment]
Using devel branch ansible, my output is below. Seems git module works fine.:: 

$ ansible-pull -U git://github.com/cocoy/ansible-playbooks.git -d /mnt/playbooks  
cmd=ansible all -c local -m git -a "repo=git://github.com/cocoy/ansible-playbooks.git dest=/mnt/playbooks version=HEAD"
localhost | success >> {
    "after": "952aaa8", 
    "before": "952aaa8", 
    "changed": false
}

cmd=ansible-playbook -c local local.yml 

PLAY [localhost] ********************\* 

GATHERING FACTS ********************\* 
ok: [localhost]

TASK: [install python-software-properties] ********************\* 
ok: [localhost]

TASK: [add nginx ppa if it ubuntu 10.04 and up] ********************\* 
ok: [localhost]

TASK: [update apt repo] ********************\* 
ok: [localhost]

TASK: [install nginx] ********************\* 
ok: [localhost]

TASK: [copy fixed init for nginx] ********************\* 
ok: [localhost]

TASK: [service nginx] ********************\* 
ok: [localhost]

TASK: [write nginx.conf] ********************\* 
ok: [localhost]

PLAY RECAP ********************\* 
localhost                      : ok=8    changed=2    unreachable=0    failed=0

**Comment by mpdehaan** [comment]
thanks for testing! closing!

**Comment by drzraf** [comment]
Using Ansible 0.7, a simple:

> git: repo=https://github.com/xxx.git dest=/bla/foo
> can't be run twice.
> fatal: destination path '/bla/foo' already exists and is not an empty directory.
> {"cmd": "/usr/bin/git clone --origin origin --recursive https://github.com/xxx.git /bla/foo/", "failed": true, "rc": 128}

It's not simple to reproduce, I still have to find the reason this happens.
