### ISSUE TITLE
task name not being templated

### ISSUE THREAD

**Issue by abadger** [ansible/ansible#10347]
Currently many name fields are being displayed with jinja templates unexpanded.  This is because the name field is being displayed in a callback when the task is started but the proper variables aren't all known until the task is run on a specific host (so that we can look up inventory variables for instance).  Fixing the display issue is very hard on v1 and we're reworking both display and variable handling in v2 so we should look at making the name field properly expand there.

Sample Playbook:

```

---

---
- hosts: localhost
  vars:
    - volume_ids:
      - 'abc'
      - 'def'
      - 'ghi'
  tasks:
    - name: "{{volume_ids|to_json}}"
      debug: msg="{{volume_ids|to_json}}"
```

Expected output:

```
$ ansible-playbook to_json.yml                          *[devel]  (14:30:14)

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [[\"abc\", \"def\", \"ghi\"]] ************************************************ 
ok: [localhost] => {
    "msg": "[\"abc\", \"def\", \"ghi\"]"
}
```

Actual output:

```
$ ansible-playbook to_json.yml                          *[devel]  (14:30:14)

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [{{volume_ids|to_json}}] ************************************************ 
ok: [localhost] => {
    "msg": "[\"abc\", \"def\", \"ghi\"]"
}
```

brought to my attention in Issue #10321

**Comment by abadger** [comment]
Discussion of some variables that simply can't exist at the name level (because they are per-host and name field goes along with multiple hosts: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ansible-project/hvBRb1lojns/netBUWDdgv8J

**Comment by jimi-c** [comment]
No longer an issue in devel, closing.

**Comment by jimi-c** [comment]
Spoke too soon, this actually fails on devel right now with a traceback:

<pre>
TASK [setup] ********************************************************************
ok: [localhost]
Traceback (most recent call last):
  File "/data/devel/ansible/bin/ansible-playbook", line 66, in <module>
    sys.exit(cli.run())
  File "/data/devel/ansible/lib/ansible/cli/playbook.py", line 161, in run
    results = pbex.run()
  File "/data/devel/ansible/lib/ansible/executor/playbook_executor.py", line 137, in run
    result = self._tqm.run(play=play)
  File "/data/devel/ansible/lib/ansible/executor/task_queue_manager.py", line 258, in run
    return strategy.run(iterator, connection_info)
  File "/data/devel/ansible/lib/ansible/plugins/strategies/linear.py", line 198, in run
    self._tqm.send_callback('v2_playbook_on_task_start', temp_task, is_conditional=False)
  File "/data/devel/ansible/lib/ansible/executor/task_queue_manager.py", line 303, in send_callback
    method(*args, **kwargs)
  File "/data/devel/ansible/lib/ansible/plugins/callback/default.py", line 119, in v2_playbook_on_task_start
    self._display.banner("TASK [%s]" % task.get_name().strip())
AttributeError: 'list' object has no attribute 'strip'
</pre>

**Comment by jimi-c** [comment]
Fixed (for real) now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by abadger** [comment]
Do we still need to document which classes of bats won't be available here?

**Comment by jimi-c** [comment]
Yes, it would most likely be good to document that somewhere (if it isn't already).
