### ISSUE TITLE
httplib2 is not installed

### ISSUE THREAD

**Issue by dwest-ee** [ansible/ansible#10343]
Hi,

On Ubuntu 14:04 when trying to use the URI module, ansible returns 'httplib2 is not installed'.

I have confirmed python is installed and with httplib2.

/usr/bin/python -c "import httplib2; print httplib2.**file**"
/usr/lib/python2.7/dist-packages/httplib2/**init**.pyc

I have also attempted to use ansible_python_interpreter pointing to "/usr/bin/python"

**Comment by sivel** [comment]
Make sure it is installed on the target server where the module is executing

**Comment by dwest-ee** [comment]
Thanks @sivel it is. The confirmation is from the targets...

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by turtlemonvh** [comment]
Thanks for the tip about installing on the targets.

:thumbsup:
