### ISSUE TITLE
[Vault] running an inventory file with Vault

### ISSUE THREAD

**Issue by niccoX** [ansible/ansible#10344]
The inventory file contains ssh login details as hostnames, user/password.

I run the playbook with a script, (RUN). 

./RUN inventory file.yml --ask-vault-pass

It's not able to decrypt the file while it's checking (ssh) each VM that is in the inventory, as it's still getting encrypted info from the inventory.

**Comment by jimi-c** [comment]
Hi @niccoX sorry to take so long to follow up on this but can you provide some example scripts and/or more info as to what it is you're trying to accomplish here?

**Comment by bcoca** [comment]
ansible can now use a vaulted inventory file, so I'm going to close this ticket.
