### ISSUE TITLE
Minor feature: Replace variables in name: fields when displayed on stdout

### ISSUE THREAD

**Issue by dwcramer** [ansible/ansible#10356]
If in my playbook I do:
- name: Install Ruby {{ ruby_version }}
  It would be cool if when that message displays on stdout, it replaced {{ ruby_version }} with the value for that variable.

**Comment by abadger** [comment]
Thanks, this is a duplicate: https://github.com/ansible/ansible/issues/10347

We're looking into getting this working in the v2 tree.

**Comment by dwcramer** [comment]
Sorry I keep opening dups. I did look for it but didn't find it using the keywords I was thinking of.

**Comment by bcoca** [comment]
@dwcramer no worries, many times the titles do not match the underlying issue very well
