### ISSUE TITLE
assemble module does not appear to inherit from file module

### ISSUE THREAD

**Issue by cegeddin** [ansible/ansible#1036]
This is my task:
- name: Assemble and restart iptables if necessary
  action: > 
    assemble src=/etc/ansible/iptables dest=/etc/sysconfig/iptables 
    owner=root group=root mode=0644

When running that task, I get the error:
{"failed": true, "msg": "unsupported parameter for module: group"}

This error repeats for each of the owner/group/mode parameters.  My best guess is that it is not
pulling the file module inherit correctly. 

I get this error in both 0.7 and 0.8.  I did not test it with 0.6.

When removing all of the file module arguments, the task completes successfully.

**Comment by mpdehaan** [comment]
Hmm... yeah -- It just needs to mark those arguments as being valid, by
doing what things like lineinfile and others do, basically.

**Comment by cegeddin** [comment]
'k.

I've not had a chance to dig through lineinfile yet, I'll try to get back to that
as soon as I can.  \

**Comment by mpdehaan** [comment]
also -- assemble also has a server side module that we need to get rid of,
and make it daisy chain...

getting rid of the server side module and then making it call the
daisy_chain_args stuff will probably fix most of it, though it should also
probably add the legal arguments to the file module to it's list of
acceptable arguments like the others.

**Comment by mpdehaan** [comment]
should all be fixed from a recent merge, can you help retest?

**Comment by stijnopheide** [comment]
yes, this works now. Thanks!
