### ISSUE TITLE
Syntax error trying to provision archlinux

### ISSUE THREAD

**Issue by kpaulsson** [ansible/ansible#10364]
I am having problem with provisioning archlinux inside Vagrant-virtualbox.
I installed Python 3.4.3

and do get: 
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --private-key=/home/admin/Vagrant/LinuxFromScratch/.vagrant/machines/default/virtualbox/private_key --user=vagrant --connection=ssh --limit='default' --inventory-file=/home/admin/Vagrant/LinuxFromScratch/.vagrant/provisioners/ansible/inventory playbook.yml

PLAY [all] *******************************************************************\* 

GATHERING FACTS **************************************************************\* 
failed: [default] => {"failed": true, "parsed": false}
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1425253103.45-275537316539940/setup", line 569
    except OSError, e:
                  ^
SyntaxError: invalid syntax

TASK: [Hello world] **********************************************************\* 
FATAL: no hosts matched or all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/home/admin/playbook.retry

default                    : ok=0    changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

Some kind of syntax error. Is my python install too modern?

**Comment by sivel** [comment]
Ansible requires Python 2 on the machines it manages. See:

http://docs.ansible.com/intro_installation.html#managed-node-requirements

http://docs.ansible.com/faq.html#how-do-i-handle-python-pathing-not-having-a-python-2-x-in-usr-bin-python-on-a-remote-machine

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
