### ISSUE TITLE
subprocess is useless in ansible/inventory/__init__.py now.

### ISSUE THREAD

**Issue by vitan** [ansible/ansible#10361]
Hi, 

Seem you guy can need remove this line https://github.com/ansible/ansible/blob/release1.8.4/lib/ansible/inventory/__init__.py#L23, or subprocess is useless now.

**Comment by amenonsen** [comment]
This is not a feature idea, and it doesn't appear to be a bug either. It should be closed.

**Comment by jctanner** [comment]
Code has changed quite a bit since this issue was opened.
