### ISSUE TITLE
Revise default for ansible_python_interpeter inside virtual env

### ISSUE THREAD

**Issue by DXist** [ansible/ansible#10378]
From #ansible IRC chat:

```
[21:04] <dxist> hi! Why does ansible looks for python interpreter by hardcoded /usr/bin/python? Why is not /usr/bin/env python a default value?
...
[21:07] <xtristan> dxist: good question. the answer i received is that /usr/bin/python is more predictably versioned than having the env respond with python3.  also, there's some inconsistency with how redhat-variants treat python (symlinks as python2.7, python2, etc)
```

If ansible is invoked inside python virtual env it doesn't use virtual env python interpreter. This is not obvious.

I see a couple of ways to handle the issue:
- if VIRTUAL_ENV environment variable is set change default for `ansible_python_interpreter` to `/usr/bin/env python`. I guess virtualenv interpreter naming is consistent across platforms.
- if VIRTUAL_ENV environment variable is set and `ansible_python_interpreter` is not overridden hint user about the details mentioned by `xtristan`.

**Comment by sivel** [comment]
See also: http://docs.ansible.com/faq.html#how-do-i-handle-python-pathing-not-having-a-python-2-x-in-usr-bin-python-on-a-remote-machine

Additionally, `ansible_python_interpreter` is set correctly for you in the scenario where you use implicit localhost.   Implicit localhost, means that you do not have to explicitly add localhost to your inventory, ansible will implicitly add one during run time.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by DXist** [comment]
@sivel, thank you for pointing me to implicit localhost. Personally, I prefer to use the same playbook for localhost and remote machines. I explicitly separate local and nonlocal inventories. And I am not happy when I always have to set `ansible_python_interpreter` for localhost.
