### ISSUE TITLE
Ansible didn't load group_vars file correctly

### ISSUE THREAD

**Issue by vankhoa011** [ansible/ansible#10370]
Hi 
I make a playbook with structure:

ansible-test/
├── playbook.yaml
└── staging
    ├── group_vars
    │   ├── test1
    │   └── test2
    └── inventory

**playbook.yaml:**
- hosts: test1
  gather_facts: false
  tasks:
  - debug: var={{ env_name }}
- hosts: test2
  gather_facts: false
  tasks:
  - debug: var={{ env_name }}

**staging:**
[test1]
127.0.0.1
[test2]
127.0.0.1

**test1**
env_name: test1
**test2**
env_name: test2

The result:
PLAY [test1] ******************************************************************

TASK: [debug var={{env_name}}] ************************************************
ok: [127.0.0.1] => {
    "test2": "{{ test2 }}"
}

PLAY [test2] ******************************************************************

TASK: [debug var={{env_name}}] ************************************************
ok: [127.0.0.1] => {
    "test2": "{{ test2 }}"
}

PLAY RECAP ********************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0

When ansible access test1 host, It load test2 in group_vars.
But I think It should load test1 in group_vars.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

However, however what is happening is that:
- You are accessing groups (test1, test2) not hosts, you only have one host (127.0.0.1). 
- Vars do not change by group in a play's hosts entry, it is set by group membership when inventory is loaded, last loaded 'wins'.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
