### ISSUE TITLE
Check that vault password is correct before running playbook

### ISSUE THREAD

**Issue by MrMMorris** [ansible/ansible#10379]
**Issue Type:** Feature Idea

**Ansible Version:** 1.8.2

**Environment:** N/A

**Summary:**

Currently, ansible does not check that the provided vault pass is correct before running the playbook. This can be frustrating as you won't know the password was wrong until you hit an encrypted file in the run and can mean a lot of easily avoidable failures.

**Steps To Reproduce:**

Create an ansible-vault encrypted file and add it to a playbook. Run with `--ask-vault-pass` and supply **incorrect** password

**Expected Results:**

If the vault pass supplied at the prompt is wrong, the playbook won't run

**Actual Results:**

The playbook runs regardless of whether or not the vault pass is correct and you won't know until it comes across an encrypted file and errors with `Decryption failed`

**Comment by MrMMorris** [comment]
xtristan in IRC made a reasonable argument that:

> one could argue in the other direction that it's preferred to not have the job fail out if it doesn't require decryption, especially when the target is N-servers.

but I think it's reasonable to assume that if I am explicitly using the `--ask-vault-pass` flag, then I am expecting to need to decrypt something :heart:

**Bonus Feature:**

Check if there are vaulted files in the scope of the referenced playbook and ask the user if they forgot `--ask-vault-pass`, although this would probably be non-trivial and may only confuse :sweat_smile:

**Comment by ghost** [comment]
Would the desired behavior be that the job also errors out early if `--vault-password-file` or `vault_password_file` (in an Ansible.cfg) is set "incorrectly?"  

The `--ask-vault-pass` is a pretty explicit way to say "use $password for this play," so I understand the reason for this github issue, but I want to make sure we don't create a scenario in which the vault-password is verified for playbooks that don't make use of encrypted content (or make it harder to support different passwords).

**Comment by MrMMorris** [comment]
I think that makes sense because the password file can only contain a single password according to the docs, yes? 

> I want to make sure we don't create a scenario in which the vault-password is verified for playbooks that don't make use of encrypted content

Again, I guess it could check the playbook for encrypted content before deciding if a password is required, but I know implementing that is probably more intensive... I'm not sure the best/easiest way to handle that. Maybe just put in the `incorrect vault pass` prompt something like `make sure your vault pass is correct or required for this playbook`  :blush:

**Comment by bcoca** [comment]
since ansible can dynamically load vault encrypted files there is no good
way to 'preemptively check the password', ansible will only know it is
incorrect when it tries to load a file, detects that it is 'vaulted' and
then tries to decrypt it.

you CAN have plays load a file early in vars_file: to force early
decryption and that way short circuit the play before any tasks are done if
the password is incorrect.

**Comment by ghost** [comment]
> I think that makes sense because the password file can only contain a single password according to the docs, yes?

Sure, but that doesn't always have to be the case.  In my current environment, it would be hugely useful to have different vault PWs for dev/qa/prod.

> Again, I guess it could check the playbook for encrypted content before deciding if a password is required

As @bcoca states, that's a non-trivial thing to do.  

My initial-thought is exercising the decrypt function against some dummy-encrypted file, but I haven't really thought this through.

**Comment by bcoca** [comment]
@tfishersp I normally would invoke each env separately, having diff passwords and only allowing for 1 actually prevented 'cross environment' errors.

**Comment by jctanner** [comment]
As stated previously, ansible doesn't attempt decrypt until necessary. One solution is a pre-task or pre-play to include a vaulted file to validate decryption and halt the play.

**Comment by backbord** [comment]
FYI, I've had success with a `local_action copy` tasks using `check_mode: yes`.
```
- name: ensure vault can be decrypted
  check_mode: yes  # do not actually copy
  local_action:
    module: copy
    src: <vault file name>
    dest: /tmp/foobar  # hopefully, /tmp is writable for me
```
It stops the playbook when the vault cannot be decrypted.
I chose `local_action` to avoid ssh overhead.

Please let me know if you have any comments, concerns, or improvements to this idea.

Perhaps this helps the next one who stumbles across this thread.

**Comment by rodrigofalco** [comment]
You can just encrypt some message into a var( in this sample, named success_decription_message), containing for example "Decryption success", and use that var in a debug line, for example may be in the pre-tasks, so that your pass is validated as soon as possible.

  pre_tasks:
    - debug: msg="{{ success_decription_message }}"
