### ISSUE TITLE
ansible_distribution not set within Docker container

### ISSUE THREAD

**Issue by bkeroackdsc** [ansible/ansible#10380]
Using Ansible to provision inside of Docker containers (based on https://github.com/phusion/passenger-docker ), `ansible_distribution` does not appear to be set despite the container being Ubuntu-based. The following is the lsb_release output from inside the container:

``` bash
root@a25be1bb9004:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:    14.04
Codename:   trusty
```

The following error message is triggered:

```
fatal: [localhost] => error while evaluating conditional: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
```

I cannot find any documentation on how `ansible_distribution` is set or when it would not be expected to be present. I'm working around the issue by manually setting `ansible_distribution` in the playbook vars.

**Comment by bcoca** [comment]
are  you gathering facts?

**Comment by bkeroackdsc** [comment]
That might be it. I have `gather_facts: False`

**Comment by bcoca** [comment]
well, that is the problem, you cannot have a fact set if you do not gather them, ansible_distribution is a fact.
