### ISSUE TITLE
Allow overriding "ansible_python_interpreter" not sys.executable

### ISSUE THREAD

**Issue by LiteWait** [ansible/ansible#10384]
When Ansible Python API code is run from Django under uWSGI, the sys.executable is being returned as /usr/bin/uwsgi instead of Python.  This means playbooks can't be executed.  Looking for a way to override this, or a feature request to add a configuration variable to override it.

**Comment by sivel** [comment]
I assume this is for implicit localhost?  If so, then be explicit and create an inventory with localhost and supply `ansible_python_interpreter`

**Comment by LiteWait** [comment]
Matt, thanks.  We just discovered that.
