### ISSUE TITLE
Is it possible to use an ansible-vault encrypted inventory file?

### ISSUE THREAD

**Issue by jerrac** [ansible/ansible#10408]
I'd like to encrypt my inventory file with ansible-vault, then run playbooks against that file. Something like:

```
ansible-playbook -i encrypted.inventory --vault-password-file /media/encryptedusbdrive/.vault_pass.txt --sudo apply.yml
```

Currently, if I try that, it does not work. Ansible acts like the targeted hosts do not exist in my inventory file. I assume because ansible isn't actually decrypting the inventory file before trying to use it.

Is it possible to make this work?

I prefer to keep my ssh and sudo passwords in my inventory files using ansible vars. That makes it a lot easier to run playbooks, I don't have to keep typing my passwords over and over. If I could encrypt this file, it would also help with keeping passwords secure when distributing them to my coworkers. Via git repos and other methods.

One suggestion from IRC was ssh-keys and passwordless sudo. I do have ssh-keys set up. But enabling passwordless sudo lessens my servers security. So I'm not interested in doing that. That also would not help with securely distributing the passwords to coworkers.

Are there any other methods to eliminate the need to enter my passwords when running playbooks, as well as help securely distribute them to coworkers?

**Comment by jhawkesworth** [comment]
You can use host_vars and or group_vars files/folders which you can encrypt
with vault. By using groups of groups you can set things like usernames
which could be the same on many servers but keep passwords encrypted per
host in host_vars folder.

Hope this helps..

Jon

**Comment by jerrac** [comment]
But host_vars and group_vars files only apply after the ssh user/pass and
sudo user/pass information has been loaded. Or is there a way to reference
vars files from the inventory file that achieves the same effect as putting
ansible_ssh_pass and ansible_sudo_pass variables in the inventory file?

I understand how to encrypt normal vars files, then use the appropriate
vault flags when running the playbook. It's encrypting the usernames and
passwords that Ansible uses to ssh into a server and run sudo commands that
I'm trying to figure out how to do.

--David Reagan

**Comment by sivel** [comment]
You can put ansible_ssh_user and ansible_ssh_pass in group_vars or host_vars.

Also as this is a question and not really an issue, you should use the ansible-project mailing list instead of github.

**Comment by jerrac** [comment]
So, if I put `ansible_sudo_pass` in host_vars/app.blah.tld.yml ansible will use that the same as if I put it in the inventory file? I thought ansible didn't load the vars until after it checked the inventory.

Hmm... Is there documentation on how Ansible bootstraps inventory/host_vars/group_vars/etc? I've spent a lot of time reading the docs and I can't find find anything on it... Did I just miss something?

This is a potential bug report/potential feature request issue. It also was posted at the end of the day when I just didn't think of the google group. So, it's not really that bad of a thing to be on github.

**Comment by sivel** [comment]
Have you actually tried using `host_vars` or `group_vars`?

While docs are good, actually trying something can answer a lot of questions. Then if it doesn't work, you can ask why and give an example of how it doesn't work.

For example if you look at the Intro Windows page, you will see these vars being specified in a group vars file.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case putting them in vault for others to use still requires them having the vault password, which will give them direct access also. For a truly secure way to share playbooks with credentials you need something like tower (http://ansible.com/tower), otherwise setup the system so each can use his own credentials to do the work.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by ciphernaut** [comment]
If you really needed to obfuscate your inventory you could use a pre_task to populate your inventory via add_host.
