### ISSUE TITLE
User is not read from .ssh/config to override the default

### ISSUE THREAD

**Issue by evanmoran** [ansible/ansible#1041]
First off thanks for a great product. I'm really loving the power of it!

Now to jump into it -- my issue is that I have a ton of stuff in .ssh/config to allow me to ssh directly when necessary. At the same time I'm logging into many servers that don't have my username, so the default doesn't make sense for me. The solution currently is to use command line `-u` to choose a username each time, but sadly I don't remember all the usernames. That is why it is in the .ssh/config!

In my ideal world there would be levels of specification:

```
Command line arguments 
Ansible settings found elsewhere
.ssh/config
Reasonable defaults
```

So if you specify nothing it uses the default as is. If you specify info in .ssh/config it overrides the defaults, but if you override the username on the commandline that wins. 

Let me know if this is something you want done and I can work on a patch.

**Comment by mpdehaan** [comment]
I think we're open to this provided -u is not specified (make sure you cover both ansible and ansible-playbooks) AND that if if -u is specified and it is NOT in the config file, it works as it does now also.  (So if no --user for /usr/bin/ansible-playbook AND not set in remote_user)

And it probably should just be done for -c ssh for starters.  Paramiko reading SSH config feels weird to me still.

**Comment by mpdehaan** [comment]
Open to pull request, but closing the ticket since it's kind of an RFE.
