### ISSUE TITLE
registered variable or fact is unavailable in second play with hosts: 127.0.0.1

### ISSUE THREAD

**Issue by mblakele** [ansible/ansible#10424]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.4
  configured module search path = None
##### Environment:

OSX 10.10.2, using homebrew to install ansible.
##### Summary:

When a playlist has two plays with `hosts: 127.0.0.1`, facts or registered variables from the first play fall out of scope for the second play.
##### Steps To Reproduce:

Evaluate this playbook `test.yml`:

```
# test.yml
- hosts: 127.0.0.1
  tasks:
    - set_fact: hostname_test='fubar'
    - add_host: name='{{ hostname_test }}'
      register: resp
    - debug: msg='{{ resp }}'

- hosts: 127.0.0.1
  tasks:
    - debug: msg='resp={{ resp|default("None") }}'
    - debug: msg='hostname_test={{ hostname_test|default("None") }}'
    - debug: msg='resp={{ hostvars["127.0.0.1"]["resp"]|default("None") }}'
    - debug:
        msg='hostname_test={{ hostvars["127.0.0.1"]["hostname_test"]
        |default("None") }}'
# end
$ ansible-playbook test.yml 
```

The ansible inventory may also be relevant:

```
localhost ansible_connection=local ansible_python_interpreter=/usr/local/bin/python
```
##### Expected Results:

```
PLAY [127.0.0.1] **************************************************************

GATHERING FACTS ***************************************************************
ok: [127.0.0.1]

TASK: [set_fact hostname_test='fubar'] ****************************************
ok: [127.0.0.1]

TASK: [add_host name='{{ hostname_test }}'] ***********************************
ok: [127.0.0.1]

TASK: [debug msg='{{ resp }}'] ************************************************
ok: [127.0.0.1] => {
    "msg": "{'invocation': {'module_name': u'add_host', 'module_args': u\"name='fubar'\"}, 'new_host': u'fubar'}"
}

PLAY [127.0.0.1] **************************************************************

GATHERING FACTS ***************************************************************
ok: [127.0.0.1]

TASK: [debug msg='resp=None'] *************************************************
ok: [127.0.0.1] => {
    "msg": "resp={'invocation': {'module_name': u'add_host', 'module_args': u\"name='fubar'\"}, 'new_host': u'fubar'}"
}

TASK: [debug msg='hostname_test=None'] ****************************************
ok: [127.0.0.1] => {
    "msg": "hostname_test=fubar"
}

TASK: [debug msg='resp={{ hostvars["127.0.0.1"]["resp"]|default("None") }}'] ***
ok: [127.0.0.1] => {
    "msg": "resp={'invocation': {'module_name': u'add_host', 'module_args': u\"name='fubar'\"}, 'new_host': u'fubar'}"
}

TASK: [debug msg='hostname_test={{ hostvars["127.0.0.1"]["hostname_test"] |default("None") }}'] ***
ok: [127.0.0.1] => {
    "msg": "hostname_test=fubar"
}

PLAY RECAP ********************************************************************
127.0.0.1                  : ok=4    changed=0    unreachable=0    failed=0
127.0.0.1                  : ok=5    changed=0    unreachable=0    failed=0
```
##### Actual Results:

```
PLAY [127.0.0.1] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [set_fact hostname_test='fubar'] **************************************** 
ok: [127.0.0.1]

TASK: [add_host name='{{ hostname_test }}'] *********************************** 
ok: [127.0.0.1]

TASK: [debug msg='{{ resp }}'] ************************************************ 
ok: [127.0.0.1] => {
    "msg": "{'invocation': {'module_name': u'add_host', 'module_args': u\"name='fubar'\"}, 'new_host': u'fubar'}"
}

PLAY [127.0.0.1] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [debug msg='resp=None'] ************************************************* 
ok: [localhost] => {
    "msg": "resp=None"
}

TASK: [debug msg='hostname_test=None'] **************************************** 
ok: [localhost] => {
    "msg": "hostname_test=None"
}

TASK: [debug msg='resp={{ hostvars["127.0.0.1"]["resp"]|default("None") }}'] *** 
ok: [localhost] => {
    "msg": "resp={'invocation': {'module_name': u'add_host', 'module_args': u\"name='fubar'\"}, 'new_host': u'fubar'}"
}

TASK: [debug msg='hostname_test={{ hostvars["127.0.0.1"]["hostname_test"] |default("None") }}'] *** 
ok: [localhost] => {
    "msg": "hostname_test=fubar"
}

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=4    changed=0    unreachable=0    failed=0   
localhost                  : ok=5    changed=0    unreachable=0    failed=0   
```

Both plays are declared as `host: 127.0.0.1` but the second play runs as if it were `hosts: localhost`. Possibly this is done after a reverse lookup somewhere inside ansible? Because of this the variable scope appears to change for the second play. This causes the variables `resp` and `hostname_test` to be undefined.

Possible workarounds: Use `hostvars["127.0.0.1"]` as in the test case, or declare `hosts: localhost` for both plays. However there may be similar situations where ansible quietly remaps a hostname to some other value. If the value is not easily determined, that may be difficult to work around.

**Comment by sivel** [comment]
I cannot duplicate this in current devel nor in `v1.9.0-0.1.rc1`

**Comment by bcoca** [comment]
registered vars are not designed to survive across plays, facts are and in my tests I always get the fact in 2nd play.

127.0.0.1/localhost is a special case, if you don't have it defined in inventory ansible will still allow it as a target, so in some circumstances it might have weird results.

**Comment by mblakele** [comment]
@bcoca What do you mean when you say "registered vars are not designed to survive across plays"? My test output above shows that the registered variable `resp` is still available in the second play, as long as I access it via `hostvars["127.0.0.1"]["resp"]`. When I use `hosts: localhost` for both plays, the registered variable is accessible as `resp` in the second play, just like the set fact, with no extra work needed.

I also noticed a docs passage at http://docs.ansible.com/playbooks_variables.html#registered-variables

> Registered variables are valid on the host the remainder of the playbook run, which is the same as the lifetime of “facts” in Ansible. Effectively registered variables are just like facts.

I think that should be "...valid on the host [for] the remainder..." but the meaning seems clear to me. A playbook can contain multiple plays. If a variable is valid for the rest of the playbook run, then it is valid for multiple plays. The lifetime of a registered variable is the same as a the lifetime of a fact.

I can't explain the different results you and sivel are seeing. I'd expect a simple playbook like this to produce consistent results, even in different environments.

**Comment by jimi-c** [comment]
Looking at this with the current devel branch, and I cannot reproduce it either:

<pre>
# ansible-playbook -vv 10424.yml 
Using /etc/ansible/ansible.cfg as config file
2 plays in 10424.yml
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [127.0.0.1]
TASK [set_fact hostname_test=fubar] *********************************************
ok: [127.0.0.1] => {"changed": false, "ansible_facts": {"hostname_test": "fubar"}}
TASK [add_host name=fubar] ******************************************************
changed: [127.0.0.1] => {"add_host": {"groups": [], "host_vars": {}, "host_name": "fubar"}, "changed": true}
TASK [debug msg={u'add_host': {u'host_vars': {}, u'groups': [], u'host_name': u'fubar'}, u'changed': True}] ***
ok: [127.0.0.1] => {
    "msg": {
        "add_host": {
            "groups": [], 
            "host_vars": {}, 
            "host_name": "fubar"
        }, 
        "changed": true
    }, 
    "changed": false
}
PLAY: ***************************************************************************
TASK [debug msg=resp={u'add_host': {u'host_vars': {}, u'groups': [], u'host_name': u'fubar'}, u'changed': True}] ***
ok: [127.0.0.1] => {
    "msg": "resp={u'add_host': {u'groups': [], u'host_vars': {}, u'host_name': u'fubar'}, u'changed': True}", 
    "changed": false
}
TASK [debug msg=hostname_test=fubar] ********************************************
ok: [127.0.0.1] => {
    "msg": "hostname_test=fubar", 
    "changed": false
}
TASK [debug msg=resp={u'add_host': {u'host_vars': {}, u'groups': [], u'host_name': u'fubar'}, u'changed': True}] ***
ok: [127.0.0.1] => {
    "msg": "resp={u'add_host': {u'groups': [], u'host_vars': {}, u'host_name': u'fubar'}, u'changed': True}", 
    "changed": false
}
TASK [debug msg=hostname_test=fubar] ********************************************
ok: [127.0.0.1] => {
    "msg": "hostname_test=fubar", 
    "changed": false
}
PLAY RECAP **********************************************************************
127.0.0.1                  : ok=8    changed=1    unreachable=0    failed=0   
</pre>

The assertion above by @bcoca is not correct, assuming the plays are executed at the same time (when there are multiple plays within one playbook, or more than one playbook is specified).

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by mmajis** [comment]
FWIW, I just reproduced this with version 1.9.2 after running into the issue elsewhere.

The behavior described by @mblakele occurs if  `localhost` and `127.0.0.1` are both used, i.e. `localhost` in inventory and `127.0.0.1` in the play hosts clause or the other way.

The variables are available in the second play if the inventory is empty or if the inventory and hosts clause both use the same value.

Similar behavior can be seen without having neither `127.0.0.1` nor `localhost` in the inventory but using them both in separate hosts clauses. Let's say there's a playbook that passes variables and facts between plays using `localhost`. Then introducing a single play for `127.0.0.1` before the other two causes the variable and facts values to disappear. The offending play can be simply a debug action:

``` yaml
# test.yml
- hosts: 127.0.0.1
  gather_facts: no
  connection: local
  tasks:
    - debug: msg="Just a message which has no effect on the rest of the playbook"

- hosts: localhost
  tasks:
    - set_fact: hostname_test='fubar'
    - add_host: name='{{ hostname_test }}'
      register: resp
    - debug: msg='{{ resp }}'

- hosts: localhost
  tasks:
    - debug: msg='resp={{ resp|default("None") }}'
    - debug: msg='hostname_test={{ hostname_test|default("None") }}'
    - debug: msg='resp={{ hostvars["127.0.0.1"]["resp"]|default("None") }}'
    - debug:
        msg='hostname_test={{ hostvars["127.0.0.1"]["hostname_test"]
        |default("None") }}'
    - assert:
        that:
          - "hostname_test == 'fubar'"
# end
```

Running the above with either an empty inventory or an inventory with `127.0.0.1` defined will fail. If `localhost` is defined in the inventory, the run will succeed.

**Comment by dsoprea** [comment]
Bump. I just ran into this ticket and it seems like there was an issue here. We're sure that it's not to be investigated based on @mmajis's report?

**Comment by tima** [comment]
@dsoprea Are you reporting this problem still is happening in v2.2.1 or the v2.3 RC that's been release? If so you'll need to file a new issue where it will get picked up by the core engineers. Bumping closed tickets don't get picked up by them.

**Comment by edwardofclt** [comment]
It's still happening in 2.4.1

**Comment by tima** [comment]
@edward-of-clt please read the comment before yours:

> Are you reporting this problem still is happening in v2.2.1 or the v2.3 RC that's been release? If so you'll need to file a new issue where it will get picked up by the core engineers. Bumping closed tickets don't get picked up by them.

**Comment by mihai-satmarean** [comment]
Happens here too

**Comment by edwardofclt** [comment]
Is the problem that you're storing it in the localhost variable group, but you're referencing 127.0.0.1.

**Comment by mihai-satmarean** [comment]
Oh. Sorry, I have a slightly different issue.
The first play has host 127.0.0.1
And the second has hosts: {{ target }}
And it does not load the host and group vars for target
Tested on macosx and Linux centos 7
Thanks!

Pe 16 mar. 2018, la 16:45, Edward Herbert <notifications@github.com> a scris:

**Comment by edwardofclt** [comment]
@mihai-satmarean do me a favor, post the playbook. :)
