### ISSUE TITLE
with_items behaves unexpected with a list of lists

### ISSUE THREAD

**Issue by hwmrocker** [ansible/ansible#10443]
```
- name: installing memcached configs
  debug: msg={{item}}
  # template:
  #   src: "{{ item[0] }}"
  #   dest: "{{ item[1] }}"
  with_items:
    - [memcached.conf.j2, /etc/memcached.conf]
    - [bla1, bla2]
  tags: [memcached, msgpoker, foobar]
  notify:
    - reload memcached
```

i would expect, that `{{item}}` is a list of two elements and not just one element.

when i use the template i get an error that template `m` could not be found.

the debug output is:

```
ok: [perconamaster-pmtest-64-1] => (item=memcached.conf.j2) => {
    "item": "memcached.conf.j2", 
    "msg": "memcached.conf.j2"
}
ok: [perconamaster-pmtest-64-1] => (item=/etc/memcached.conf) => {
    "item": "/etc/memcached.conf", 
    "msg": "/etc/memcached.conf"
}
ok: [perconamaster-pmtest-64-1] => (item=bla1) => {
    "item": "bla1", 
    "msg": "bla1"
}
ok: [perconamaster-pmtest-64-1] => (item=bla2) => {
    "item": "bla2", 
    "msg": "bla2"
}
```

i use ansible version 1.8.4

**Comment by srgvg** [comment]
See #10052

**Comment by hwmrocker** [comment]
@srvg thx for the info

I found a workaround, you have to use a list of list of lists:

```
- name: installing memcached configs
  debug: msg={{item}}
  # template:
  #   src: "{{ item[0] }}"
  #   dest: "{{ item[1] }}"
  with_items:
    - [[memcached.conf.j2, /etc/memcached.conf]]
    - [[bla1, bla2]]
  tags: [memcached, msgpoker, foobar]
  notify:
    - reload memcached
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by hwmrocker** [comment]
I think it is a bug, because the documentation does not mention that the lists are flattened by one level.

I updated the docs and made a pull request, to make it obvious to the users how `with_items` work.

The way it works is very counter intuitive (at least for someone with background as a developer), but can be very useful in some cases.

This should be documented.
