### ISSUE TITLE
Synchronize.py module failing for Rhel 5.5 (Tikanga) (rsync --out-format= <<CHANGED>>%i %n%L: unknown option)

### ISSUE THREAD

**Issue by coolkunal** [ansible/ansible#10442]
When i am running ansible playbook from rhel 5.5(Tikanga) i am getting following error:
failed: [ip -> 127.0.0.1] => {"cmd": "rsync --delay-updates -FF --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"/prd/file.tar.gz/roles/server/files/abc.tar.tgz\" \"root@remoteip:/tmp\"", "failed": true, "rc": 1}
msg: rsync: --out-format=<<CHANGED>>%i %n%L: unknown option
rsync error: syntax or usage error (code 1) at main.c(1231) [client=2.6.8]

FATAL: all hosts have already failed -- aborting

I am using synchronize module of ansible for copying operation which is failing since rsync: --out-format=<<CHANGED>>%i %n%L: unknown option..
i have also changed synchronize.py module by adding some lines of code to avoid the above prblem..
Please look into this as for rhel 5.5 its not working

Thanks and Regards,
Kunal Dembla

**Comment by bcoca** [comment]
We need a bit more info, could you reformat the issue using the template https://github.com/ansible/ansible/blob/devel/ISSUE_TEMPLATE.md ?

**Comment by jctanner** [comment]
Closing due to submitter timeout.
