### ISSUE TITLE
Ansible Docker Module Errors out.

### ISSUE THREAD

**Issue by bdastur** [ansible/ansible#10453]
Summary:
Executing a task using the docker module throws an error. Note that the same task was working fine on the same host, but has suddenly started throwing and error.  

Also if I convert this to execute the task using command module it works.

I am executing the following task from my playbook to start a docker container.

```
- name: Start the Galera Docker Service 
  docker:
    name: "mariadb_v1"
    image: "{{ dockers.mariadb.image_id }}" 
    volumes: "{{ dockers.mariadb.host_data_dir }}:{{ dockers.mariadb.host_data_dir }}"
    stdin_open: yes
    ports: "3306:3306, 4567:4567"
    privileged: yes
    net: "host"
    command: "{{ dockers.mariadb.host_data_dir }}/mariadb_start.sh"
  when: command_result.stdout == "" 
```

TASK: [galera_server | Start the Galera Docker Service] **********************\* 
<172.22.191.206> ESTABLISH CONNECTION FOR USER: centos
...
<172.22.191.206> REMOTE_MODULE docker ports='3306:3306, 4567:4567' net=host volumes=/dockers/mariadb:
/dockers/mariadb command=/dockers/mariadb/mariadb_start.sh image=e9198fa0274a name=mariadb_v1
<172.22.191.207> REMOTE_MODULE docker ports='3306:3306, 4567:4567' net=host volumes=/dockers/mariadb:
/dockers/mariadb command=/dockers/mariadb/mariadb_start.sh image=e9198fa0274a name=mariadb_v1
<172.22.191.208> REMOTE_MODULE docker ports='3306:3306, 4567:4567' net=host volumes=/dockers/mariadb:
/dockers/mariadb command=/dockers/mariadb/mariadb_start.sh image=e9198fa0274a name=mariadb_v1
<172.22.191.206> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/
bdastur/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication
=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentic
ation=no -o User=centos -o ConnectTimeout=120 172.22.191.206 /bin/sh -c 'sudo -k && sudo -H -S -p "[s
udo via ansible, key=pxezevjstnzroeefsfsjkhiraikpqaht] password: " -u root /bin/sh -c "echo BECOME-SU
CCESS-pxezevjstnzroeefsfsjkhiraikpqaht; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python"'
<172.22.191.207> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/
bdastur/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication
=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentic
ation=no -o User=centos -o ConnectTimeout=120 172.22.191.207 /bin/sh -c 'sudo -k && sudo -H -S -p "[s
udo via ansible, key=rnyxokantfsypwbjkmurcqcjfzaboxmp] password: " -u root /bin/sh -c "echo BECOME-SU
CCESS-rnyxokantfsypwbjkmurcqcjfzaboxmp; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python"'
<172.22.191.208> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/
bdastur/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication
=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentic
ation=no -o User=centos -o ConnectTimeout=120 172.22.191.208 /bin/sh -c 'sudo -k && sudo -H -S -p "[s
udo via ansible, key=wcfuqrjabayucinpbrncciuuxvjtzyap] password: " -u root /bin/sh -c "echo BECOME-SU
CCESS-wcfuqrjabayucinpbrncciuuxvjtzyap; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python"'
failed: [172.22.191.206] => {"failed": true, "parsed": false}
BECOME-SUCCESS-pxezevjstnzroeefsfsjkhiraikpqaht
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: /etc/ssh_config line 102: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 25739
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
Traceback (most recent call last):
  File "<stdin>", line 3032, in <module>
  File "<stdin>", line 1406, in main
  File "<stdin>", line 1274, in started
  File "<stdin>", line 1185, in start_containers
TypeError: start() got an unexpected keyword argument 'pid_mode'
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 1

**Comment by abadger** [comment]
This should be filed against the docker-modules-core repository.  It looks like you are using ansible from a checkout.  I think I see that the pid_mode parameter recently added requires docker-py-1.0.0... Going to try and see if I can trace that further for you but if I don't get back to this shortly it's because I got waylaid into something else... Would be good to refile this into the correct repository if that happens so that it doesn't get lost.

**Comment by abadger** [comment]
PR where this was added: https://github.com/ansible/ansible-modules-core/pull/890

**Comment by abadger** [comment]
Okay, could you test out this pull request and see if it fixes the issue for you:
https://github.com/ansible/ansible-modules-core/pull/936

To use pid_mode, you'd need to update your docker-py (and possibly docker server).  If you don't specify pid_mode, then with the Pull Request applied you should no longer get this traceback.

**Comment by bdastur** [comment]
Thanks for your input. I will try your suggestion and see if that fixes the issue. 
Also, one thing was not clear to me in your last comment. You mentioned with the Pull Request applied you should no longer get this traceback. Do you mean the docker pull request? Because the operation with the docker module I am doing is a docker run. The image is already available on the host.

**Comment by abadger** [comment]
@bdastur If you apply the change in https://github.com/ansible/ansible-modules-core/pull/936 then the error should no longer occur.  "pull request" in this context meant a github pull request (how patches are proposed and pulled into the ansible git repository).  It didn't have anything to do with what the docker module itself was doing.
