### ISSUE TITLE
unclear documentation of set_fact module ...

### ISSUE THREAD

**Issue by breathe** [ansible/ansible#10458]
I'm using ansible 1.8.4

```
ncohen@breathe ~ [2]> ansible --version
ansible 1.8.4
  configured module search path = None
```

I think the documentation of the set set_fact module is unclear (http://docs.ansible.com/set_fact_module.html)

> This module allows setting new variables. Variables are set on a host-by-host basis just like facts
> discovered by the setup module. These variables will survive between plays.

I would think that 'these variables will survive between plays' suggests a different semantics than the current behavior.  My expectation based on that description was that facts defined by the module would behave as though these facts had been defined as by a file in /etc/facts.d/  -- such that ansible host -m setup would include any facts previously defined on that host via set_fact task ...

**Comment by redbaron** [comment]
IMHO docs are very clear what this operation does. It is usually next to impossible to document what particular operation doesn't do. If it doesn't say that it drops file into /etc/facts.d/ or in any other way affects setup module then, wel... it doesn't do any of that

**Comment by breathe** [comment]
My words were not to imply the docs suggested a particular mechanism that the module does not in fact do -- but rather that the semantics of the module are not clear.  The docs as written imply to me semantics as I describe.  Reading the docs -- I still don't understand what it means for a fact to "survive between plays".

How does this module behave at all "just like facts discovered by the setup module".  If that is the case why do facts defined via set_fact never appear when setup module is run?

I'm going to disagree with you about the docs being clear because I still don't understand what this module does and I searched around quite a bit trying to gain clarity before posting this issue.

**Comment by redbaron** [comment]
It does what docs say. It sets variable  per host, which survives between plays. Could it be that you confuse play and playbook?

**Comment by breathe** [comment]
For a new ansible user 'between plays' is actually a pretty non-specific way to refer to a span of time, particularly when you are talking about a module which is explicitly about producing a non-default scope and lifetime for a variable.  Hunting around I see someone else had roughly the exact same confusion as me a year ago after reading these docs: http://ansible-project.narkive.com/8o5aNnUk/suggestions-for-additions-to-set-fact-s-documentation

Now that I understand what the module is actually doing, may I suggest small changes to the documentation which could greatly clarify this:

> This module allows setting new facts during play execution. Variables are set on a host-by-host 
> basis and will be created in the same namespace as facts discovered by the setup module. These 
> variables will survive between plays during the same playbook run."

Note that -- observationally -- I know the above description is actually incorrect (facts defined via set_fact don't go into ansible_facts namespace or ansible_local namespace.  I put that suggestion here simply as an attempt to indicate how misleading 'just like the setup module' is as part of a description of this module's behaviour.

I _think_ this is what the module does:

> This module allows setting new variables during play execution with a value that will survive between
> plays during a playbook run.  These variables are created in inventory scope and are valid on the host
> the remainder of the playbook run (similar to registered variables).

Examples could potentially indicate the module in use.  (Maybe an example like this doesn't belong in docs but I include it here so someone finding this issue later can at least find clarity if clarity for this module's docs remains undesirable).

```
- hosts: host1.example.com
  tasks:
    - name: set_fact defined facts are not persistent across playbook runs
      debug: msg="i will never have learned anything by this point (a_new_fact is not yet defined at this point during playbook run and never will be)"

    - name: set a fact during one play
      set_fact:
          a_new_fact: "learning should be useful"

- hosts: host1.example.com
  tasks:
    - name: and reference that fact during another play on that host
      debug: msg="I agree that {{ a_new_fact }}"

- hosts: host2.example.com
  remote_user: root
  tasks:
    - name: or reference that fact during another play from another host
      debug: msg="I also agree that {{ hostvars['host1.example.com']['a_new_fact'] }}"
```

**Comment by redbaron** [comment]
There is no such thing as "default scope". Every var belongs to the scope where it is defined. set_fact sets variable in hostvars which is persist throughout the invocation of ansible-playbook.

As of the reference to setup module (and therefore facts), maybe it is just me not being native English speaker, but in current version of docs I can't see any meaning, other than using "setup" module as an example of what "host-by-host"  variable look like (and how can be used) from user point of view.

**Comment by bcoca** [comment]
I'm going to close this issue as this discussion seems good but limited, please to bring this up in ansible-devel (larger audience) and then send a PR to update the docs.

I agree this could be clearer but we also want to keep module docs simple and concise.

**Comment by breathe** [comment]
Where I used the words 'non-default' I wasn't trying to indicate the scope this module is defining variables in -- I was trying to capture the fact that this module defines variables in _some_ scope with _some_ lifetime and that the module should clearly document these since its impossible to know what the module does without documentation of that.

In the clarification to the documentation that I suggested, I used the phrase 'inventory scope' which I cribbed from the discussion of this issue:  https://github.com/ansible/ansible/issues/8758

I'm a native english speaker and a new user to ansible -- I found the docs confusing.  I was confused in exactly the same way as at least one other person who was motivated to write to the mailing list as I linked above.

(sorry for continuing this discussion of a closed issue, had typed this already when the issue was externally closed).

**Comment by pebreo** [comment]
I found this discussion cleared my initial confusion. This line was especially clarifying: "These 
variables will survive between plays DURING the same PLAYBOOK RUN." [emphasis mine]

**Comment by ghost** [comment]
Suffered from same confusion. Clarified by reading this issue.

**Comment by kimu** [comment]
Same confusion here. Again clarified only reading this issue. The documentation has not changed yet since this issue was first opened two years ago. Apparently there is some sort of opposition to make the documentation clearer.

**Comment by antitree** [comment]
Same confusion. Seems like a reasonable fix.

**Comment by DrHofman** [comment]
Same confusion here, would be nice to have this in the docs

**Comment by ksylvan** [comment]
Same confusion here.
