### ISSUE TITLE
libvirt_lxc connection won't work on non-SElinux enabled platforms (like Ubuntu)

### ISSUE THREAD

**Issue by fghaas** [ansible/ansible#10450]
There is a long-standing bug in virsh that will affect users of Ubuntu or any platform that does not ship SElinux:

https://www.redhat.com/archives/libvirt-users/2013-July/msg00146.html

On Ubuntu platforms, the only advertised security model for LXC, per `virsh -c lxc:/// capabilities`, is `none`:

``` xml
    <secmodel>
      <model>none</model>
      <doi>0</doi>
    </secmodel>
```

When executing `virsh -c lxc:/// lxc-enter-namespace` like the libvirt_lxc connection plugin does, this results in the following error:

```
$ virsh -c lxc:/// lxc-enter-namespace test /bin/bash
libvirt:  error : argument unsupported: Security model none cannot be entered
```

The libvirt_lxc connection plugin would see this on every `exec_command`, `put_file` and `fetch_file`, making the plugin rather unusable under the circumstances. 

The workaround suggested in the ML thread is to invoke `lxc-enter-namespace` with the `--noseclabel` option:

```
$ virsh -c lxc:/// lxc-enter-namespace --noseclabel test /bin/bash
root@test:/#
```

I'm hesitant to send a patch for `libvirt_lxc.py` to that effect though, because I have no way to test on an SElinux-enabled LXC system.

**Comment by jctanner** [comment]
This should have been resolved by https://github.com/ansible/ansible/pull/14910
