### ISSUE TITLE
Internal system is interpreting the password has being a template

### ISSUE THREAD

**Issue by couto** [ansible/ansible#10468]
**Issue Type:** Bug Report

**Ansible Version:**

```
❯ ansible --version
ansible 1.8.4
  configured module search path = None
```

**Environment:**
- Host: 

```
❯ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.10.2
BuildVersion:   14C1510
```
- Managed OS: N/A

**Steps To Reproduce:**

```
ansible-playbook -i _provision/inventory _provision/common.yml --ask-vault-pass --ask-sudo-pass
```

When asked for the sudo password, insert the following: `Gr[Y+JBp.8i92M)9{%D{y<9xZ` (this password has been revoked). The role common.yml itself is irrelevant, but it asks for sudo by starting with:

```

---

- hosts: staging
  sudo: yes
```

**Expected Results:**
It should start running the playbook on the remote machine

**Actual Results:**

```
❯ ansible-playbook -i _provision/inventory _provision/common.yml --ask-vault-pass --ask-sudo-pass -vvvv
sudo password:
Vault password:

PLAY [staging] ****************************************************************

GATHERING FACTS ***************************************************************
fatal: [REDACTED IP] => template error while templating string: Encountered unknown tag 'D'.

TASK: [common | Update apt cache] *********************************************
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/couto/common.retry

[REDACTED IP]              : ok=0    changed=0    unreachable=1    failed=0
```

It seems to me, that the above password is being interpreted by the internal template system, since by chance the password contains the `{%` chars.

**Comment by luenix** [comment]
It seems that the workaround is running `ansible-playbook` while being within the root environment.

I experienced this bug on a fresh Ubuntu 14.04 AWS instance when I went to utilize @zach-adams' hgv-deploy-full Ansible Playbook. A sheepish `sudo su` beforehand allowed everything to complete successfully.
