### ISSUE TITLE
Error when using plugins/inventory/openstack.py with shade 0.3.0

### ISSUE THREAD

**Issue by dwcramer** [ansible/ansible#10469]
I'm attempting to use openstack.py with the latest version of shade (0.3.0) and receive the following error:

```
Traceback (most recent call last):
  File "openstack.py", line 161, in <module>
    main()
  File "openstack.py", line 151, in main
    inventory.list_instances()
  File "openstack.py", line 121, in list_instances
    groups = self.get_host_groups()
  File "openstack.py", line 80, in get_host_groups
    groups = self.get_host_groups_from_cloud()
  File "openstack.py", line 99, in get_host_groups_from_cloud
    meta = cloud.get_server_meta(server)
  File "/home/ubuntu/archive/ansible/venv/local/lib/python2.7/site-packages/shade/__init__.py", line 915, in get_server_meta
    server_vars = meta.get_hostvars_from_server(self, server)
  File "/home/ubuntu/archive/ansible/venv/local/lib/python2.7/site-packages/shade/meta.py", line 116, in get_hostvars_from_server
    image_name = cloud.get_image_name(image_id)
  File "/home/ubuntu/archive/ansible/venv/local/lib/python2.7/site-packages/shade/__init__.py", line 492, in get_image_name
    self._image_cache[image_id] = None
AttributeError: 'OpenStackCloud' object has no attribute '_image_cache'
(venv)ubuntu@bastion:~/archive/ansible/plugins/inventory$ pip show shade

---
Name: shade
Version: 0.3.0
Location: /home/ubuntu/archive/ansible/venv/lib/python2.7/site-packages
Requires: pbr, os-client-config, six, python-novaclient, python-keystoneclient, python-glanceclient, python-cinderclient, python-neutronclient, python-troveclient, python-ironicclient, python-swiftclient, dogpile.cache
(venv)ubuntu@bastion:~/archive/ansible/plugins/inventory$
```

I'm hoping @emonty will know what's up. 

Addendum: When I comment out line 492 of shade/__init__py, the _image_cache error goes away and I make it to another error:

```
  File "/home/ubuntu/archive/ansible/venv/local/lib/python2.7/site-packages/shade/meta.py", line 115, in get_hostvars_from_server
    image_id = server.image['id']
TypeError: string indices must be integers
```

When I wrap shade/meta.py 115 in a try/except, the script succeeds and I get my inventory!

```
    try:
        image_id = server.image['id']
    except:
    image_id = "None"
```

Note: I'm running this against Cisco's OpenStack installation and it may indeed be some unique characteristic of it that causes it to sometimes have null values for server.image['id']. However, it would be cool if this didn't kill openstack.py.

**Comment by emonty** [comment]
WOW. Ok - there are two bugs there, one i've got a patch for already but forgot to release (will do that this morning) The second one is ... well ... wow. However, thanks - because shade's purpose in life is, sadly, to find all of the places where clouds are different and special like that. I will go through and add in some more defense there ...

**Comment by emonty** [comment]
@dwcramer it sounds like perhaps server.image is just a string in your install ... could you do me a favor and confirm that?

**Comment by emonty** [comment]
And/or try this patch: https://gist.github.com/c019f353cd935d9fd45e and see if it works ...

**Comment by emonty** [comment]
https://gist.github.com/c11d4cd43b19ed7a63cd <-- sorry, I clearly meant the non-broken version here

**Comment by dwcramer** [comment]
I'll give the patches a try. Wrt server.image, if I put in a print(server.image), it prints out six object and blows up on the 7th. I believe that 7th vm was spun up from a volume. In Horizon, the field for server.image is empty.

**Comment by emonty** [comment]
AH - boot from volume - that would make perfect sense as to why image would be broken.

**Comment by dwcramer** [comment]
Yeah, I think this is just an edge case. I get the same error with that gist (2nd one) btw:

```
Traceback (most recent call last):
  File "openstack.py", line 161, in <module>
    main()
  File "openstack.py", line 151, in main
    inventory.list_instances()
  File "openstack.py", line 121, in list_instances
    groups = self.get_host_groups()
  File "openstack.py", line 80, in get_host_groups
    groups = self.get_host_groups_from_cloud()
  File "openstack.py", line 99, in get_host_groups_from_cloud
    meta = cloud.get_server_meta(server)
  File "/home/ubuntu/archive/ansible/venv/local/lib/python2.7/site-packages/shade/__init__.py", line 915, in get_server_meta
    server_vars = meta.get_hostvars_from_server(self, server)
  File "/home/ubuntu/archive/ansible/venv/local/lib/python2.7/site-packages/shade/meta.py", line 120, in get_hostvars_from_server
    image_id = server.image['id']
TypeError: string indices must be integers
```

**Comment by emonty** [comment]
Awesome. I appreciate you poking at it for me. Could you try one more:
https://gist.github.com/e1de0f65d868a73b02b4
I think this one should be defensive enough ...

**Comment by dwcramer** [comment]
Still a type problem in there:

```
  File "/home/ubuntu/archive/ansible/venv/local/lib/python2.7/site-packages/shade/meta.py", line 117, in get_hostvars_from_server
    image_id = server.image.get('id', None)
AttributeError: 'unicode' object has no attribute 'get'
```

**Comment by emonty** [comment]
Oh - hrm. Perhaps I should do getattr(server.image, 'get') rather than checking for getitem. (sorry for "debugging-through-github-comments" ... however, that does show that it's a pure unicode object, so that awesome. Now, if only there was a safe way to check for string status that worked in both 2 and 3. _headdesk_

**Comment by emonty** [comment]
One more if you don't mind:

https://gist.github.com/19d8bd90483720bf5379

**Comment by dwcramer** [comment]
That works! 
Glad to help. Let me know if you need anything else.

**Comment by emonty** [comment]
For the record, fix is here: https://review.openstack.org/#/c/164691/ ... will respond here again when we cut a release with that fix.

**Comment by dwcramer** [comment]
Excellent, thanks!

**Comment by emonty** [comment]
shade 0.4.0 is released which contains this fix and one for the other problem ... so you should be set.

**Comment by dwcramer** [comment]
Thanks!
