### ISSUE TITLE
Add Fedora 21 to the ansible-galaxy meta template

### ISSUE THREAD

**Issue by jansauer** [ansible/ansible#10473]
Fedora version 21 is out since 9 December 2014 but not listed in the meta/main.yml template created by ansible-galaxy init.

I'm not 100% certain that this is the right repo for that bug. Tried adding the version myself but the list of possible platforms ist queried from the galaxy api ([/bin/ansible-galaxy#L314](https://github.com/ansible/ansible/blob/4f5ca4bb4c7f69bc153c6d819dded0974aced2f3/bin/ansible-galaxy#L314)).

Ansible Version: 1.8.3
Environment: OSX 10.10
Steps To Reproduce: ansible-galaxy init test
Expected Results: Entry with 21 in test/meta/main.yml after line 38

**Comment by bcoca** [comment]
this is already true in devel as we generate it from python:

```
  #- name: Fedora
  #  versions:
  #  - all
  #  - 16
  #  - 17
  #  - 18
  #  - 19
  #  - 20
  #  - 21
  #  - 22

```
