### ISSUE TITLE
Ansible's actions on a remote server are influenced by the local, even if ssh'd as root

### ISSUE THREAD

**Issue by pearofducks** [ansible/ansible#10475]
##### Environment:

**Local:** OSX 10.10.2
**Remote:** Debian 7
##### Summary:

When doing:
`user:foobar $ ansible-playbook -i remote-server, playbook.yml`

(where remote-server is root@some-server in ssh configs)

and attempting to do

```
sudo: yes
sudo_user: foobar
```

unexpected results will occur - in this case actions won't actually happen as foobar, but as root.
##### Steps To Reproduce:

Run ansible as a local user, and attempt to take sudo + sudo_user actions as that user on a remote server, while ssh'd as root.

Example:

**playbook test.yml**:

```

---
- hosts: all
  tasks:
  - command: whoami
    sudo: yes
    sudo_user: foobar
```

**Failure example** (foobar is the user on the _local_ system):
`foobar $ ansible-playbook -i remote, test.yml`

Result:
`changed: [remote] => {"changed": true, "cmd": ["whoami"], "stderr": "", "stdout": "root", "warnings": []}`

**Success example** (barfoo is the user on the _local_ system):
`barfoo $ ansible-playbook -i remote, test.yml`

Result:
`changed: [remote] => {"changed": true, "cmd": ["whoami"], "stderr": "", "stdout": "foobar", "warnings": []}`
##### Expected Results:

Regardless of the local user, if ssh'd in as root and performing sudo_user actions, the actions should take place as that user.
##### Actual Results:

If the local user and the sudo_user are the same username, the command actually runs as root.

**Comment by bcoca** [comment]
I cannot reproduce this issue, using both debian7 and centos7 as remotes, running your play:

```
---
- hosts: 'debtest:centos7test'
  tasks:
  - command: whoami
    sudo: yes
    sudo_user: bcoca

```

```
#> ansible-playbook play.yml -k -u root -v
changed: [debtest] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.003295", "end": "2015-03-19 15:27:27.756981", "rc": 0, "start": "2015-03-19 15:27:27.753686", "stderr": "", "stdout": "bcoca", "warnings": []}

changed: [centos7test] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.006709", "end": "2015-03-19 15:27:26.599774", "rc": 0, "start": "2015-03-19 15:27:26.593065", "stderr": "", "stdout": "bcoca", "warnings": []}
```

**Comment by pearofducks** [comment]
I have this reproduced with two essentially new Debian hosts. Post a junk pubkey and I'll give you access to both?

**Comment by bcoca** [comment]
do you have ansible_sudo_user or ansible_ssh_user set in inventory for those hosts?

**Comment by ebastos** [comment]
I was able to reproduce the error with 1.8.4, but seems to be fixed on devel:

```
[15:44] ebastos@main:~/projects/github/ansible ((v1.8.4))$ ansible-playbook  /tmp/test.yml -v -k
SSH password: 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [10.0.2.21]

TASK: [command whoami] ******************************************************** 
changed: [10.0.2.21] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.003689", "end": "2015-03-20 15:44:48.498357", "rc": 0, "start": "2015-03-20 15:44:48.494668", "stderr": "", "stdout": "root", "warnings": []}

PLAY RECAP ******************************************************************** 
10.0.2.21                  : ok=2    changed=1    unreachable=0    failed=0   

[15:44] ebastos@main:~/projects/github/ansible ((v1.8.4))$ git checkout devel
Previous HEAD position was ebc8d48... Version bump for release 1.8.4
Switched to branch 'devel'
Your branch is up-to-date with 'origin/devel'.
[15:44] ebastos@main:~/projects/github/ansible (devel)$ ansible-playbook  /tmp/test.yml -v -k
SSH password: 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [10.0.2.21]

TASK: [command whoami] ******************************************************** 
changed: [10.0.2.21] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.003828", "end": "2015-03-20 15:45:05.099689", "rc": 0, "start": "2015-03-20 15:45:05.095861", "stderr": "", "stdout": "ebastos", "warnings": []}

PLAY RECAP ******************************************************************** 
10.0.2.21                  : ok=2    changed=1    unreachable=0    failed=0   
```

**Comment by pearofducks** [comment]
No, nothing in inventory at all.

Confirmed fixed on devel though!
