### ISSUE TITLE
ignore_errors on a fire and forget reboot command results in unreachable host ssh error

### ISSUE THREAD

**Issue by cknapp** [ansible/ansible#10472]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.4
  configured module search path = None
##### Environment:

CentOS Linux release 7.0.1406 (Core) 
##### Summary:

I am trying to reboot a remote machine using the fire and forget technique describe in [1] and [2]. With poll 0, async 0, and ignore_errors: true, I am getting an SSH error: "fatal: [dc-cmp-01.example.com] => SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh" when executing "command: reboot". 

N.B. This may be related to upgrading from ansible-1.8.2-1.el7.noarch to ansible-1.8.4-1.el7.noarch. Normally I would downgrade and retest, but yum is failing to rollback the transaction. I am fairly certain this task was working before the upgrade, I have been using it for a while. 

[1] http://docs.ansible.com/playbooks_async.html
[2] https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back
##### Steps To Reproduce:

Run the following task:

```
- name: reboot with new kernel
  command: reboot
  async: 0
  poll: 0
  ignore_errors: yes
```
##### Expected Results:

I expect the machine to reboot, and ansible to properly ignore any ssh error. 
##### Actual Results:

ansible-playbook output:

```
[chester@deepthought management_layer]$ ansible-playbook -vvvvv --ask-vault-pass -i stage site.yml --start-at "reboot with new kernel"
Vault password: 

PLAY [component] ************************************************************** 

PLAY [component] ************************************************************** 

GATHERING FACTS *************************************************************** 
<dc-cmp-01.example.com> 
<dc-cmp-01.example.com> 
<dc-cmp-01.example.com> IdentityFile=/home/chester/.ssh/id_rsa_production ConnectTimeout=10 PasswordAuthentication=no 'LANG=C LC_CTYPE=C /usr/bin/python' KbdInteractiveAuthentication=no User=root ControlPath=/home/chester/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey ControlMaster=auto Port=22 ControlPersist=60s
<dc-cmp-02.example.com> 
<dc-cmp-02.example.com> 
<dc-cmp-02.example.com> IdentityFile=/home/chester/.ssh/id_rsa_production ConnectTimeout=10 PasswordAuthentication=no 'LANG=C LC_CTYPE=C /usr/bin/python' KbdInteractiveAuthentication=no User=root ControlPath=/home/chester/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey ControlMaster=auto Port=22 ControlPersist=60s
ok: [dc-cmp-01.example.com]
ok: [dc-cmp-02.example.com]

TASK: [component | reboot with new kernel] ************************************ 
<dc-cmp-01.example.com> 
<dc-cmp-01.example.com> 
<dc-cmp-02.example.com> 
<dc-cmp-02.example.com> 
<dc-cmp-01.example.com> IdentityFile=/home/chester/.ssh/id_rsa_production ConnectTimeout=10 PasswordAuthentication=no 'LANG=C LC_CTYPE=C /usr/bin/python' KbdInteractiveAuthentication=no User=root ControlPath=/home/chester/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey ControlMaster=auto Port=22 ControlPersist=60s
<dc-cmp-02.example.com> IdentityFile=/home/chester/.ssh/id_rsa_production ConnectTimeout=10 PasswordAuthentication=no 'LANG=C LC_CTYPE=C /usr/bin/python' KbdInteractiveAuthentication=no User=root ControlPath=/home/chester/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey ControlMaster=auto Port=22 ControlPersist=60s
fatal: [dc-cmp-01.example.com] => SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh
fatal: [dc-cmp-02.example.com] => SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/chester/site.retry

dc-cmp-01.example.com      : ok=1    changed=0    unreachable=1    failed=0   
dc-cmp-02.example.com      : ok=1    changed=0    unreachable=1    failed=0   

```

Important to note...the command does go through. I can see that the machine is properly rebooted and comes back up.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

However, however what is happening is that:
- ignore errors applies to the task returning in error, not to connection issues which always take the host out of rotation. 

We would suggest:
- issue the reboot w/o async and then just have a wait_for task to pause the play until the host is responsive again.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by cknapp** [comment]
@bcoca Thanks for your suggestion: 

These are the tasks I'm using now:

```
- name: reboot with new kernel
  command: reboot
  #async: 0
  poll: 0
  ignore_errors: yes

- name: Waiting for VM to reboot with new kernel
  local_action: wait_for host="{{ target }}.{{ domain }}" port=22 state=started timeout=300
```

I still see the following errors:

```
TASK: [component | reboot with new kernel] ************************************ 
<dc-cmp-01.example.com> 
<dc-cmp-02.example.com> 
<dc-cmp-02.example.com> 
<dc-cmp-01.example.com> 
<dc-cmp-02.example.com> IdentityFile=/home/chester/.ssh/id_rsa_production ConnectTimeout=10 PasswordAuthentication=no 'LANG=C LC_CTYPE=C /usr/bin/python' KbdInteractiveAuthentication=no User=root ControlPath=/home/chester/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey ControlMaster=auto Port=22 ControlPersist=60s
<dc-cmp-01.example.com> IdentityFile=/home/chester/.ssh/id_rsa_production ConnectTimeout=10 PasswordAuthentication=no 'LANG=C LC_CTYPE=C /usr/bin/python' KbdInteractiveAuthentication=no User=root ControlPath=/home/chester/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey ControlMaster=auto Port=22 ControlPersist=60s
fatal: [dc-cmp-02.example.com] => SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh
fatal: [dc-cmp-01.example.com] => SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh

FATAL: all hosts have already failed -- aborting
```

**Comment by davidfokkema** [comment]
I'd like to reopen this bug report. I have the problem, and been using the solution, described here: http://stackoverflow.com/questions/26677064/create-and-use-group-without-restart. With a new version of ansible, this no longer works. That is, ansible fails hard. I now have no other way to have a nice speedy ansible run, and create new users and groups.

**Comment by bcattle** [comment]
I can confirm that this appears to have broken in upgrading to Ansible 2.1

**Comment by michaelsmoody** [comment]
@bcoca I can confirm this is broken in 2.1 on our install also

**Comment by dj80hd** [comment]
@cknapp i found a work around using 'shutdown -t 5 -r' instead of 'reboot'

**Comment by peterroelants** [comment]
I have the same issue, changing the reboot command to `sleep 5 && shutdown -r` seems to make it work.

```
    - name: Restart machine
      command: sleep 5 && shutdown -r now "Reboot triggered by Ansible script"
      async: 1
      poll: 0
      ignore_errors: true
      become: true
      become_method: sudo
    - name: Wait for machine to restart
      local_action:
        module: wait_for
          host={{ inventory_hostname }}
          port=22
          delay=15
          timeout=300
          state=started
      become: false
```

**Comment by rafaelhenrique** [comment]
this dont work for me:

`sleep 5 && shutdown -r now "Reboot triggered by Ansible script"`

i use:

`shutdown -r -t 5 "Reboot triggered by Ansible script"`

5 equals 5 minutes.

**Comment by davidfokkema** [comment]
@rafaelhenrique sleep 5 means five *seconds*, not minutes, so it will finish much quicker than you might expect. Shutdown -t 5 *does* mean five minutes, so there is a difference. If that is not your problem, please be a bit more specific than: “this doesn’t work.”

**Comment by rafaelhenrique** [comment]
Hi @davidfokkema after some time thinking and redoing, redoing, redoing succeeded to make reboot work the "correct" way as follows ....

```
  - name: Reboot EC2 instance.
    shell: sleep 5 && logger "Reboot triggered by Ansible script" && shutdown -r now "Reboot triggered by Ansible script"
    async: 1
    poll: 0
    become: true
    tags:
      - reboot

  - name: Wait for instance reboot.
    local_action:
      module: wait_for
        host={{ ansible_ssh_host }}
        port={{ ansible_port }}
        delay=15
        timeout=120
        state=started
    become: false
    tags:
      - reboot
```

Removing `become_method: sudo` everything is fine

**Comment by davidfokkema** [comment]
@rafaelhenrique Yes, this part of my setup has taken me lots of time as well. And I needed to revisit it several times already, when something in Ansible changes. The first part of your playbook is virtually identical to what I use. For the second part, you could make a few changes. You can drop the `{{ ansible_ssh_host }}` variable requirements and the `state=started` by using the `wait_for_connection` module:
```
- name: wait for server to come back
  wait_for_connection:
  args:
    delay: 15
    timeout: 120
```
It's short and sweet, and actually works across vagrant boxes and external IPs.

**Comment by rafaelhenrique** [comment]
Cool! :smile:

**Comment by Klaas-** [comment]
I came across this problem today aswell, I don't think making the reboot task async is necessary (I like to use --check so I wanted to avoid async)

I just run this within a playbook to update my systems using yum

```
# run yum update, reboot server if needed
- name: Install all pending updates
  yum:
    name: "*"
    state: latest
  register: yum_updated

# reboot when yum has changed
- name: reboot if needed after updates
  shell: shutdown -r +1
  when: yum_updated.changed

# delay to be sure system has shutdown before trying
- name: Wait for system to become reachable again
  wait_for_connection:
    timeout: 900
    delay: 120
    sleep: 5
  when: yum_updated.changed
```

shutdown will exit 0 and it won't kill the shell immediately because of the +1 (shutdown in one minute) so ansible doesn't error. The wait for connection may need a little more tweaking depending on your environment.
