### ISSUE TITLE
ansible_distribution fact populates as "RedHat" on Oracle Linux systems

### ISSUE THREAD

**Issue by Logos01** [ansible/ansible#10485]
`ansible oracle_linux_os_instance -m setup -a 'filter=ansible_distribution'` will return:  
`oracle_linux_os_instance | success >> {`
`"ansible_facts": {`
`"ansible_distribution": "RedHat"`
`},`
`"changed": false`
`}`

ansible_lsb.id seems to populate properly on these systems.

/etc/redhat-release on said system is being populated _by Oracle_ as:
`Red Hat Enterprise Linux Server release 6.5 (Santiago)`

**Comment by bcoca** [comment]
As discussed in IRC this is caused by Oracle having a package that 'lies' and pretends to be redhat. Still we need to deal with it and correctly detect what the system is and it looks like checking for lsb data first is the solution.
