### ISSUE TITLE
Copy module gives confusing error message

### ISSUE THREAD

**Issue by AndreasDavour** [ansible/ansible#1048]
When trying to copy to a non existing directory, ansible just say it's not writable. Correct, but misleading. File not found or similar message would make more sense.

rpm -qa | grep ansible
ansible-0.7-0.git201208150235.fc17.noarch

[ante@orcus templates]$ ansible swixsession00.sx1:swixsession00.sx2 -m copy -a "src=memcached-nrpe.j2 dest=/etc/nrpe.d/memcache.cfg"
swixsession00.sx1 | FAILED >> {
    "failed": true, 
    "module": "copy", 
    "msg": "Destination /etc/nrpe.d not writable"

**Comment by mpdehaan** [comment]
Want to send me a patch?

**Comment by AndreasDavour** [comment]
I can't write python to save my life.

**Comment by mpdehaan** [comment]
That kind of dilemma may make a good movie.  Perhaps something involving unix and an archaeological park of some kind.  Ok, thx, will look

-- Michael

**Comment by mpdehaan** [comment]
closing per above, thanks @sfromm !
