### ISSUE TITLE
Recursive playbooks include crash

### ISSUE THREAD

**Issue by jody-frankowski** [ansible/ansible#10495]
It seems that ansible doesn't detect recursive (cyclic?) includes and just crashes. It would be nice if ansible could check for this problem and issue a warning.

Issue Type: Bug report

Ansible Version:

```
ansible 1.8.4
  configured module search path = None
```

Steps To Reproduce:
Create a playbook that includes itself.

Expected Results:
Issue a warning.

Actual Results:

```
RuntimeError: maximum recursion depth exceeded
```

**Comment by bcoca** [comment]
The current error seems correct, specially considering we allow for dynamic includes now and they could take different paths depending on current execution.
