### ISSUE TITLE
Error when debugging build of Docker Image (STDOUT)

### ISSUE THREAD

**Issue by bsodmike** [ansible/ansible#10519]
Ansible: 1.8.2
OS X Yosemite, 10.10.2

Here's some context,

``` yaml
- name: Build base image
  shell: docker build -t {{docker_image_namespace}}/trusty-base {{docker_yard_dir}}/base
  register: docker_build

- debug: msg="{{ docker_build.stdout }}"
```

I've only been able to get this to work as `- debug: var=docker_build.stdout`, however, this does not print STDOUT, but rather shows the var contents, including '\n' chars in a really long string.

```
TASK: [docker-base | debug msg="{{ docker_build.stdout }}"] *******
fatal: [10.22.22.22] => A variable inserted a new parameter into the module args. Be sure to quote variables if they contain equal signs (for example: "{{var}}").

FATAL: all hosts have already failed -- aborting
```

Thoughts?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by bsodmike** [comment]
Hi @bcoca Thanks for your reply but this is not a 'user question'.  This problem has been reported before in tickets such as #8260.  I've opened an issue there, thanks for your help.  https://groups.google.com/forum/#!topic/ansible-project/0QYcTCaW9nM

**Comment by abadger** [comment]
To expand on @bcoca's reply; in the ticket you link to mpdehaan said this:

> Yep, this is going to be a legitimate thing now (i.e. we're not going to be able to make a change here), because of the way we must guard against argument insertion from potentially untrusted data sources.
> 
> There are easy fixes though [example for lineinfile omited]
>  https://github.com/ansible/ansible/issues/8260#issuecomment-49939533

So this is simply the way that ansible works now.  It becomes a user question as there are ways to write the playbook to achieve the same thing without running into this particular, purposeful, limitation of the parser.  So on the mailing list we can help you discover a syntax for the playbook that will let you achieve your end goal.

(v1 at least... v2 we're rewriting the parser which may allow us to fix this but I can't make any promises... it's a tough problem trying to balance the security concerns here with the three parsers (PyYAML, jinja2, and ansible's own parsing) and strings that end users want to use.)

**Comment by bsodmike** [comment]
Thanks @abadger appreciate your elucidation - look forward to discussing this via the mailing list.  Cheers!
