### ISSUE TITLE
with_items introduces a '#' when using escaped braces

### ISSUE THREAD

**Issue by andrewkcarter** [ansible/ansible#10535]
Using Ansible 1.7.2 on Centos 6.6 (installed from EPEL), I'm trying to execute a command which contains escaped brackets. I get different results when I move the command into an items list. Here it is boiled down to a trivial example:

This works:

```
- shell: echo special {{ '{{' }} string {{ '}}' }} test
```

Verbose output shows Ansible executes this:
<server-1> ESTABLISH CONNECTION FOR USER: root
<server-1> REMOTE_MODULE command **echo special {{ string }} test** #USE_SHELL

However, this doesn't:

```
- shell: echo {{ item }}
  with_items:
    - special {{ '{{' }} string {{ '}}' }} test
```

When this same string is executed from a list of items, the resulting command has '#' characters in place of one bracket in each occurance:
<server-1> ESTABLISH CONNECTION FOR USER: root
<server-1> REMOTE_MODULE command **echo special {# string #} test** #USE_SHELL

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Ansible rewrites any returned {{ }} to {# #} to avoid code injection, this is not happening when running the command but when reporting the output of it.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
