### ISSUE TITLE
sudo=true in config confuses argument parsing

### ISSUE THREAD

**Issue by shepmaster** [ansible/ansible#10547]
### Steps to reproduce

```
# touch play.yml
# ansible-playbook --ask-sudo-pass play.yml
Usage: ansible-playbook playbook.yml

ansible-playbook: error: Sudo arguments ('--sudo', '--sudo-user', and '--ask-sudo-pass') and su arguments ('-su', '--su-user', and '--ask-su-pass') and become arguments ('--become', '--become-user', and '--ask-become-pass') are exclusive of each other
```
### Potential cause

[This code](https://github.com/ansible/ansible/blob/8a0b8629e86efeddec7da5f8976231deee000f7f/v2/ansible/utils/cli.py#L268-L280) migrates `--ask-sudo-pass` to the new `become` options, _but does not remove the sudo setting_. Then [this code](https://github.com/ansible/ansible/blob/8a0b8629e86efeddec7da5f8976231deee000f7f/v2/ansible/utils/cli.py#L283-L301) fails because both settings are set. 
### Version

```
# ansible-playbook --version
ansible-playbook 1.9.0.1
  configured module search path = None
```

**Comment by bcoca** [comment]
so I cannot reproduce the issue and the code you are looking at is in v2 which is not used in 1.9

**Comment by bcoca** [comment]
checked v2 and the validation code runs before the normalization code, so this should not happen even when using the v2 binaries.

**Comment by shepmaster** [comment]
@bcoca sorry, didn't realize about the default branch not being 1.9.

[Here's the 1.9 normalization](https://github.com/ansible/ansible/blob/a00056723fe8798bf6b18607a26d73d1a306c610/lib/ansible/utils/__init__.py#L1157-L1169) and [and 1.9 checking](https://github.com/ansible/ansible/blob/a00056723fe8798bf6b18607a26d73d1a306c610/lib/ansible/utils/__init__.py#L1644-L1657) code.

Normalization happens on [line 132](https://github.com/ansible/ansible/blob/a00056723fe8798bf6b18607a26d73d1a306c610/bin/ansible-playbook#L132), and the mutually exclusive happens at [line 112](https://github.com/ansible/ansible/blob/a00056723fe8798bf6b18607a26d73d1a306c610/bin/ansible-playbook#L112), so the ordering looks right. I added some prints to those parts of my installed code, and can clearly see that the checking for exclusive happens _before_ the normalization. Now I just have to figure out why multiple values are being set.

**Comment by shepmaster** [comment]
@bcoca OK, I got this to reproduce in a fresh Ubuntu docker container. Turns out the issue is with having a config file. Sorry for the misleading initial report:

```
# cat conf
[defaults]
sudo = True

# touch foo.yml

# ANSIBLE_CONFIG=./conf ansible-playbook foo.yml
Usage: ansible-playbook playbook.yml

ansible-playbook: error: Sudo arguments ('--sudo', '--sudo-user', and '--ask-sudo-pass') and su arguments ('-su', '--su-user', and '--ask-su-pass') and become arguments ('--become', '--become-user', and '--ask-become-pass') are exclusive of each other
```

**Comment by bcoca** [comment]
ok, this makes more sense, had missed this test case

**Comment by dh-harald** [comment]
Set become to default False and become_user to default empty. Because this default values prevent to use sudo or su

**Comment by bcoca** [comment]
please test the PR above
