### ISSUE TITLE
Add a migration how-to for Ansible 1.9

### ISSUE THREAD

**Issue by sebastianneubauer** [ansible/ansible#10541]
I haven't found one so far, maybe there aren't that many migration things, but at least I had an issue with missing space which was perfectly fine in 1.8.X but is not in 1.9:

wrong:

```
    roles:
        - { role: ...,
                packages:[...]
          }
```

correct:

```
    roles:
        - { role: ...,
                packages: [...]
          }
```

**Comment by bcoca** [comment]
So we did not expect differences to appear, in this case your YAML was invalid (the space is required by the spec) but the python YAML parser that was used was 'permissive' and let this pass. To increase processing speed we now default to a C based parser which seems to be stricter about the spec.

**Comment by sebastianneubauer** [comment]
You are right, I know it is not a bug in ansible. But it took me quite some time to find and debug this and I thought maybe when I share it here, it might help someone who has the same problem... ,-) And in the end it doesn't matter where a "bug" is, it's annoying when things break after an update, even if it is a clear user mistake like in my case..
