### ISSUE TITLE
random  minutes

### ISSUE THREAD

**Issue by danbuntu** [ansible/ansible#10540]
Hi

I'm trying to set servers to check if they need a reboot and if so reboot at 03:{{random number of minutes}}

if I use:

random_number: "{{ 60 | random }}"

it doesn't padd with leading zeros and so fails to run

 shutdown -r 03:3 won't work
 shutdown -r 03:03 will work

how do I achieve this please?

**Comment by sivel** [comment]
I believe what you want is:

```
"{{ '%02d'|format(60|random) }}"
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
