### ISSUE TITLE
playbook sudo: yes roles are not executed as sudo.

### ISSUE THREAD

**Issue by erickeller** [ansible/ansible#10550]
Issue Type:

Bug

Ansible Version:  1.9.0.1 from ppa stable.

Environment:

Linux Ubuntu 12.04 host to Linux Debian wheezy target.

Summary:

playbook roles are not executed as sudo anymore.

Steps To Reproduce:

consider the following playbook working with 1.7.2 but no more working with the 1.9.0.1:

test.yml

```
- hosts: test
  roles:
    - role: addgroups
      sudo: yes
```

roles/addgroups/tasks/main.yml

```

---
- name: add toto group
  group: name=toto state=present
```

Expected Results:

add the test group without any failure.

Actual Results:

failed: [zoo] => {"failed": true, "name": "test"}
msg: groupadd: Permission denied.
groupadd: cannot lock /etc/group; try again later

digging into the verbose mode we can observe that the addgroups role is still called with sudo with older version i.e. 1.7.2 and not any more called with sudo with 1.9.0.1

1.7.2

```
u'/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=hgpjwxwhvkcrvjywzmwiwhxnnamxrfln] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-hgpjwxwhvkcrvjywzmwiwhxnnamxrfln; LANG=C LC_CTYPE=C /usr/bin/python /home/test/.ansible/tmp/ansible-tmp-1427390484.81-80330223816703/group\'"
```

1.9.0.1

```
/bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python /home/test/.ansible/tmp/ansible-tmp-1427392790.43-74683051810820/group
```

Cheers

**Comment by erickeller** [comment]
ugly workaround:
in roles/addgroups/tasks/main.yml

```
---
- name: add toto group
  group: name=toto state=present
  sudo: yes
```

**Comment by int3h** [comment]
:+1:

**Comment by sivel** [comment]
A git bisect has led me to the following commit as where the problem was introduced: de5eae2007d4138730582e876770d3b24c863753

**Comment by jder** [comment]
This also seems to affect task includes. The following seems to cause all included tasks to be sudo'ed on 1.8.4 but not 1.9.0.1:

```
  - include: mytasks.yml
    sudo: yes
```

**Comment by bcoca** [comment]
please test the above PR, it now works for my tests but I would like confirmation it also clears your issues.

**Comment by lueschem** [comment]
Many thanks - I can confirm that the above PR does fix the issue (I used the same playbook as erickeller did - we have submitted the issue together).

**Comment by jder** [comment]
Works for me, too, both for included tasks and role dependencies. Thanks!

**Comment by bcoca** [comment]
merged into devel and will probably be out in a 1.9.1 soon
