### ISSUE TITLE
(ask) Sudo password problem

### ISSUE THREAD

**Issue by dh-harald** [ansible/ansible#10561]
Hi,

After I've upgraded ansible to ansible 1.9.0.1, i've got a problem with ask_sudo_password.
(server asks for sudo password)

(ansible runs on arch linux, the target system is CentOS6)
With earlier versions of ansible (1.8.2, 1.8.4) runs fine

My settings:
sudo_user      = root
sudo           = True
# ask_sudo_pass = True

become=False
# become_method='sudo'

become_user=''
# become_ask_pass=False

(to fix problem in issue #10547)

In playbook:
...
sudo: True
...

and the command:
ansible -m setup <server> -K
SUDO password: 
xxxxxx server xxxxxx | FAILED => ssh connection closed waiting for a privilege escalation password prompt

**Comment by bcoca** [comment]
closing this as duplicate of  #10547, hopefully fixed by #10559

**Comment by dh-harald** [comment]
Hi,

I think, it's a duplicate of #10550, because
sudo_user was in my ansible.conf, sudo: True in playbook, and sudo_user wasn't processed...
