### ISSUE TITLE
vsphere_guest Error ... 

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#10569]
Hi all 
i have bug or what ever you can think on but i geting an error and i just dont know why !!! and i want to slam the Server!!! 
i am using vsphere_guest  to get info from my vcenter and create new VMs and i getting this ERROR 

vsphere_guest vcenter_hostname=XXXXXX guest=ansible password=VALUE_HIDDEN username=

failed: [ansible2] => {"failed": true}
msg: unsupported parameter for module: username
- name: Test
  hosts: all
  connection: local
  
  tasks: 
  - vsphere_guest:
      vcenter_hostname: vcenter
      username: name
      password: pass
      guest: server
      vmware_guest_facts: yes

ansible 1.9.0.1
  configured module search path = None
pysphere-0.1.8

if i use python to connect the Vcenter it is working ...  but ansible .... not 
i dont know how to get more info i am using -vvvv but , i think maybe the issue in the vcenter but i don't know what to look for 

Thanks

**Comment by aioue** [comment]
@noamgr can you paste the raw, unformatted task code please?

Screenshot would be fine.

**Comment by ghost** [comment]
Hi it is not relevant any more SORRY  :-) ... it was my mistake as i didn't know that if you have folder named library ansible automatic use the local in the role folder 
and i have in the folder some vsphere_guest  ... so i get error ... its take me 3 days to understand as ansible  dont say "overwrite local module "

and again sorry i will close the case  

Noam
