### ISSUE TITLE
Problems with os.access test for execute bit on AIX

### ISSUE THREAD

**Issue by mklambert** [ansible/ansible#1057]
I'm trying to get ansible up and running on an AIX server and I ran into a problem with the host file handling. The `__init__` method of the Inventory object in `ansible/inventory/__init__.py` is using the function `os.access` to determine if the submitted host_list is executable. However, this test is known to have problems on some platforms when it is run as root, as described in [this Python bug report](http://bugs.python.org/issue14706).

Due to this issue, my attempts to run ansible using a vanilla hosts files fail when  the `os.access` call  succeeds, causing `__init__` to attempt to run the non-executable hosts file and an OSError exception is generated.

I was able to work-around this problem  by replacing the call to `os.access` with `os.stat` tests, eg -

This:

``` python
elif (stat.S_IXUSR & os.stat(host_list)[stat.ST_MODE] or
      stat.S_IXGRP & os.stat(host_list)[stat.ST_MODE] or
      stat.S_IXOTH & os.stat(host_list)[stat.ST_MODE]):
```

rather than this:

``` python
elif os.access(host_list, os.X_OK):
```

I don't know if this is a good general solution to this problem but it's worked for me so far.

I'm running the development branch of ansible using AIX 6.1 with Python v2.6.7.

**Comment by mpdehaan** [comment]
Sounds reasonable.   I would make a function in utils called "is_executable" rather than inlining that call, and use that where needed.

Can you send me a pull request that does this?

**Comment by mklambert** [comment]
Will do.

**Comment by mklambert** [comment]
There's another os.access check for the execute bit in the module include file module_common.py. Should the utility function be added to that file, too, or would you prefer an inline call for this particular case?

**Comment by mpdehaan** [comment]
Yeah, We should define a new function there and use it where required in
modules that need it.

**Comment by mpdehaan** [comment]
done, thanks!
