### ISSUE TITLE
copy behavior changed from ansible 1.8 to 1.9 devel

### ISSUE THREAD

**Issue by andrewgdavis** [ansible/ansible#10576]
##### Issue Type:

“Bug Report”
##### Ansible Version:

```
ansible 1.9 (devel d628f3f591) last updated 2015/03/27 11:05:49 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 5d776936cc) last updated 2015/03/27 10:18:52 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 400166a655) last updated 2015/03/27 10:18:57 (GMT -700)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/03/27 10:19:02 (GMT -700)
  v2/ansible/modules/extras: (detached HEAD 400166a655) last updated 2015/03/27 10:19:14 (GMT -700)
  configured module search path = None
```
##### Environment:

OS X 10.9.5
##### Summary:

The copy behavior has changed from ansible 1.8 to 1.9 (devel).  Specifically: sub directories found in src are not recursively copied to dest.
##### Steps To Reproduce:

```
ansible-galaxy init test_copy
```

Create src directory foo and place sub directories and content in it.

```
mkdir -p test_copy/files/foo/sub1/sub/
echo "xxx" > test_copy/files/foo/sub1/sub/data.txt
```

The playbook yml: test.yml

```
- name: test for copy
  hosts: 127.0.0.1
  connection: local
  gather_facts: no

  roles:
    - test_copy
```

then the task found in test_copy/tasks/main.yml:

```

---
# tasks file for test_copy
- name: delete dest dir
  file:
    path=bar
    state=absent

- name: create dest dir
  file:
    path=bar
    state=directory

- name: test
  copy: src=foo/ dest=bar/
```

run the test: 

```
ansible-playbook test.yml
```
##### Expected Results:

results should be the same as ansible 1.8 which are:

```
TASK: [test_copy | test] ******************************************************
changed: [127.0.0.1] => {"changed": true, "checksum": "38170c08cb458fd4879c34b6f608294c50312bbb", "dest": "bar/sub1/sub/data.txt", "gid": 1402748881, "group": "1402748881", "md5sum": "6de9439834c9147569741d3c9c9fc010", "mode": "0644", "owner": "adavis", "size": 4, "src": "/Users/adavis/.ansible/tmp/ansible-tmp-1427737709.58-221755553244082/source", "state": "file", "uid": 1402748881}
```
##### Actual Results:

```
TASK: [test_copy | test] ******************************************************
failed: [127.0.0.1] => {"checksum": "38170c08cb458fd4879c34b6f608294c50312bbb", "failed": true}
msg: Destination directory bar/sub1/sub does not exist
```

**Comment by bcoca** [comment]
are the dirs empty? if so it could be a dupe  of #10567

**Comment by andrewgdavis** [comment]
the src has sub directories.  there is data in foo/sub1/sub/data.txt

But yes, the bugs are related.  I reverted the change from [https://github.com/ansible/ansible/issues/9092]

and the behavior is as expected.  (but that does not help fix the bug 9092

**Comment by abadger** [comment]
This is a change in behaviour but it is not a bug.  The documentation for copy specifies that dest must be an absolute path.  If you change your playbook like this things should start working:

``` diff
-  copy: src=foo/ dest=bar/
+  copy: src=foo/ dest=~/bar/
```

Fixing the recursion error closed the loophole which allowed relative paths in dest to work.

**Comment by andrewgdavis** [comment]
Ok. Thanks!
