### ISSUE TITLE
Synchronize doesn't respect  ansible.cfg ssh_args

### ISSUE THREAD

**Issue by dopry** [ansible/ansible#10570]
We use a custom ssh.config with ansible. It should respect the ssh_args we set in the general config, or we should have a way to specify ssh arguments for rsync through the module.

**Comment by m-o-e** [comment]
Why is this tagged as "feature_idea" when it is clearly a bug? :beetle: 

`ssh_args` should be used by all SSH-operations, including `synchronize`.

Currently `synchronize` will fail in scenarios where the contents of  `ssh_args`
are mandatory to reach a remote host (e.g. hardcoded proxy host, credentials or key overrides).

Bug is still present in current git HEAD:

```
ansible 2.0.0 (devel 31ebafcbdd) last updated 2015/10/20 19:01:20 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 14f32de7a6) last updated 2015/10/20 19:01:24 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD eeeb1264d3) last updated 2015/10/20 19:01:28 (GMT +200)
```

**Comment by adarazs** [comment]
This is indeed really inconvenient to circumvent, you have to compress a directory (because fetch doesn't support multiple files), fetch it, then uncompress the file, instead of one synchronize step. This is a serious bug, not a feature_idea.

**Comment by solojavier** [comment]
@bcoca Can we label this issue correctly?

**Comment by tima** [comment]
Related to #16767

**Comment by jimi-c** [comment]
@tima / @abadger  Is this still a problem? I thought we had fixed this a while back.

**Comment by tima** [comment]
@jimi-c I think we did that this particular issue could be closed. https://github.com/ansible/ansible/issues/16767 is a bit different and is arguably a bug.

**Comment by sivel** [comment]
This was resolved in https://github.com/ansible/ansible/commit/bce79c67c3657ccf24bea9685eb158c5aab70e2e / https://github.com/ansible/ansible/pull/15306

**Comment by jimi-c** [comment]
Thanks @sivel, that's what I thought.
