### ISSUE TITLE
ansible-playbook  disable verbose

### ISSUE THREAD

**Issue by weldpua2008** [ansible/ansible#10582]
Helo 

I can't find how to disable  verbose messages in ansible-playbook.

Example:

> PLAY [Role] ***************************************************************
> GATHERING FACTS ***************************************************************
> ok: [127.0.0.1]
> TASK: [base-devel-go | Install go lang support] *******************************
> ok: [127.0.0.1]

We can use only exit code to determine where if there were errors.

Also I'm using ansible-playbook as source-example for my flow. It will be pretty if there was such example

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
