### ISSUE TITLE
Using "keys" as key in a dict breaks ansible runs

### ISSUE THREAD

**Issue by pieterlexis** [ansible/ansible#10581]
Because "keys" is a function of a dict the following task + var fails:

```
vars:
  duplicity:
    keys:
      - 'F2FFE1A7'
      - '7EED19F3'
      - 'D2E71575'

tasks:
  - name: 'Import GPG public keys for backups'                                     
    shell: gpg --recv-key {{ item }}                                               
    with_items: duplicity.keys
```

With the following error:

```
...
failed: [machine1] => (item=<built-in method keys of dict object at 0x7f4ce4244a28>) => {"changed": true, "cmd": "gpg --recv-key <built-in method keys of dict object at 0x7f4ce4244a28>", "delta": "0:00:00.013751", "end": "2015-03-31 08:14:21.334793", "item": "<built-in method keys of dict object at 0x7f4ce4244a28>", "rc": 2, "start": "2015-03-31 08:14:21.321042", "warnings": []}
stderr: Syntax error: end of file unexpected (expecting word)
...
```

Renaming "keys" to something else (like pubkeys), works like a charm:

```
- hosts: localhost
  vars:
   - duplicity:                                                                       
       pubkeys: 
           - 'F2FFE1A7'
           - '7EED19F3'
           - 'D2E71575'
  tasks:
    - name: 'Import GPG public keys for backups'                                     
      debug: var={{ item }}
      with_items: duplicity.pubkeys
```

```
...
ok: [localhost] => (item=F2FFE1A7) => {
    "item": "F2FFE1A7",
    "var": {
        "F2FFE1A7": "F2FFE1A7"
    }
}
...
```

**Comment by jpmens** [comment]
I confirm this fails in latest devel as well.

**Comment by bcoca** [comment]
I expect this to break in all versions of ansible

**Comment by bcoca** [comment]
closing this as there is no good way to document all possible python keywords that will break when used as a key.

**Comment by tersmitten** [comment]
We have the [same problem](https://github.com/Oefenweb/ansible-composer/issues/11) using the `update` keyword as a key.

@bcoca Maybe we can improve [this section](https://github.com/ansible/ansible/blob/devel/docsite/rst/YAMLSyntax.rst#gotchas) of the docs?

**Comment by bcoca** [comment]
not really a yaml gotcha, if any it would require it's own section (which might include or link yaml gotchas also).

**Comment by lazartravica** [comment]
I've come around this problem by using square brackets for dict key access:

In my case:
`{{ (keys.stdout | from_json)['keys'] }}`

Instead of:
`{{ (keys.stdout | from_json).keys }}`

Hope this helps!
