### ISSUE TITLE
group_vars/all parsed for each host, slow on large file size

### ISSUE THREAD

**Issue by wenottingham** [ansible/ansible#10584]
Proxying for a customer.

Our group_vars/all is very large (megabytes) and parsing
it takes several seconds. Unfortuntely it appears it is parsed at least once
for every targeted host, so targeting a thousand hosts means job takes hours
to complete (even in parallell) even if it should only take a few minutes  
(Fabric does it in 10 minutes).

**Comment by srgvg** [comment]
On 31 March 2015 at 15:55, Bill Nottingham notifications@github.com wrote:

> . Unfortuntely it appears it is parsed at least once
> for every targeted host,

​Which version of ansible? That should not happen any more since 1.7

​

**Comment by wenottingham** [comment]
Aha. Dug out of the rest of the response - pre-1.6.x. Closing.
