### ISSUE TITLE
Typo in gitpull example.

### ISSUE THREAD

**Issue by GR360RY** [ansible/ansible#1059]
There is a typo in the last action for logrotate configuration:

dest=/etc/logrorate.d/ansible-pull

Should be /etc/logrotate.d/ansible-pull

...
- name: Create logrotate entry for ansible-pull.log
    action: template src=templates/etc_logrotate.d_ansible-pull.j2 dest=/etc/logrorate.d/ansible-pull owner=root group=root mode=0644

**Comment by mpdehaan** [comment]
Ha, yeah, I need to watch those pull requests a bit closer.  Thanks very much for spotting.
