### ISSUE TITLE
manage aws users, groups & policies

### ISSUE THREAD

**Issue by MasseGuillaume** [ansible/ansible#10594]
users: https://console.aws.amazon.com/iam/home#users
groups: https://console.aws.amazon.com/iam/home#groups
policies: https://console.aws.amazon.com/iam/home#policies
...

are not managed by ansible.

**Comment by viper233** [comment]
boto/boto#2956 looks like we might be limited upstream for listing IAM policies. I'm interested in get a list of the AWS managed IAM polices to attach to new roles. It's possible via the API, http://docs.aws.amazon.com/IAM/latest/APIReference/API_ListPolicies.html and the cli

```
aws iam list-policies
```

**Comment by wyaeld** [comment]
@viper233 boto3 merged support for this a long time ago, in 0.0.11

Doesn't look to be anything blocking changes here

**Comment by jxn** [comment]
@MasseGuillaume & @wyaeld iam_policy and iam roles are both in ansible as of 2.0, and can manage users, groups, and policies.

**Comment by l1x** [comment]
@jxn these are in Ansible 2.0 but only for inline policies. I have just created groups, users and policies (attaching policies to groups) and every policy comes up as inline. There is no way to set for example managed: true that would be an easy way of implementing support for managed policies.

I am curious when is going to be supported by Ansible to use managed policies.

**Comment by pierreant-p** [comment]
+1 For having AWS Managed policies implemented in Ansible !

**Comment by shaunbrady** [comment]
+1 Added this to boto2, and now I'm interested in using it with Ansible.  I'm not sure if this issue is more interested in policies or the ability to list users/groups/policies, but I'm personally interested in both.

**Comment by wraithm** [comment]
Now that @shaunbrady's managed policy PR is merged into boto, what's the status of this issue?

**Comment by shaunbrady** [comment]
@wimnat Has a PR https://github.com/ansible/ansible-modules-extras/pull/2201 I have not had time to test/contribute it yet.  Check it out!

**Comment by jimi-c** [comment]
Any follow-up here? It seems to be resolved, so if we don't hear back soon we'll close this.

**Comment by wimnat** [comment]
iam_role module is now merged which supports managed policies. I'm working on iam_user module to do the same. ETA a month or two. I'd say this can be closed.

**Comment by jimi-c** [comment]
@wimnat thanks, I'll go ahead and close it then.
