### ISSUE TITLE
Lineinfile backup doesn't work on FAT32

### ISSUE THREAD

**Issue by dbrgn** [ansible/ansible#10591]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.9.0.1
  configured module search path = None
```
##### Environment:

Running on Arch Linux, managing Raspbian on a Raspberry Pi.
##### Summary:

When using the lineinfile module with backup=yes on a FAT32 file system, I get an exception.

It appears that some of the characters (I think at least the colon in the timestamp) are invalid on FAT32.
##### Steps To Reproduce:

I used the following task:

``` yaml
- name: Enable systemd.
  lineinfile:
    dest: /boot/cmdline.txt
    state: present
    regexp: '^(.* rootwait)$'
    line: '\1 init=/bin/systemd'
    backrefs: yes
    backup: yes
```
##### Expected Results:

It works :)
##### Actual Results:

``` python
Traceback (most recent call last):
  File "<stdin>", line 2199, in <module>
  File "<stdin>", line 394, in main
  File "<stdin>", line 281, in present
  File "<stdin>", line 1706, in backup_local
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 22] invalid mode ('wb') or filename: '/boot/cmdline.txt.2015-04-01@14:28:29~'
```

**Comment by dbrgn** [comment]
A possible fix would be to use a unix timestamp or alternatively `20150401142829` instead. Might this introduce reverse compatibility issues of some form?

This code could also live in a try-except block.

**Comment by bcoca** [comment]
many of our file operations will fail on non POSIX file systems, still this should not be a traceback

**Comment by dbrgn** [comment]
This is very simple to fix though. So I think it's worth the effort :)

Alternatively, a way to specify the destination path for the backup file would be even better.

**Comment by bcoca** [comment]
it is already in a try block, it does not capture IOErrors though, which it should.

as for this being a 'simple' fix, yes, if we wan't to break backwards compatibility, it is simple, but we don't.

**Comment by xiegeo** [comment]
Please fix this, FAT32 is required in some situation, such as the raspberry pi boot partition.

An opt in option to alternative backup file names should not break backwards compatibility.
