### ISSUE TITLE
Ansible-galaxy does not support .yaml?

### ISSUE THREAD

**Issue by MrMMorris** [ansible/ansible#10609]
**Issue Type:**

Bug Report

**Ansible Version:**

```
ansible 1.9 (detached HEAD 85cfe1bd52) last updated 2015/03/19 10:05:19 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 76198a8223) last updated 2015/03/19 10:05:20 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD cb848fcd9e) last updated 2015/03/19 10:05:20 (GMT -700)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/03/14 20:17:41 (GMT -700)
  v2/ansible/modules/extras: (detached HEAD 46e316a20a) last updated 2015/03/14 20:18:07 (GMT -700)
```

**Environment:**

Running from OSX

**Summary:**

Get error when trying to pull a role using ansible-galaxy that has a .yaml extension on the meta file

**Steps To Reproduce:**

`ansible-galaxy install https://github.com/picotrading/ansible-ulimit`

**Expected Results:**

Role installed successfully

**Actual Results:**

```
- executing: git clone https://github.com/picotrading/ansible-ulimit ansible-ulimit
- executing: git archive --prefix=ansible-ulimit/ --output=/tmp/tmpCiF82H.tar master
- error: this role does not appear to have a meta/main.yml file.
- ansible-ulimit was NOT installed successfully.
```

`meta/main.yml` seems to be hardcoded in the bin:
https://github.com/ansible/ansible/blob/devel/bin/ansible-galaxy#L518

**Comment by jctanner** [comment]
@MrMMorris roles have always required .yml files. You can include other task files from the main.yml by whatever extension you'd like, but the convention is .yml. In your roles dir, run "ansible-galaxy init foo" if you would like to see a default directory and file structure.
