### ISSUE TITLE
Job submit by Ansible Tower by got this "msg: Failed to lock apt for exclusive operation" 

### ISSUE THREAD

**Issue by sukenneth** [ansible/ansible#10604]
I have an Ansible Tower installed, and there is a playbook yml file as below:
###### 

---
- hosts: all
  tasks:
  - name: Installs nginx web server
    apt: pkg=nginx state=installed update_cache=true
    handlers:
  - name: Start Nginx
    service: name=nginx state=started
    ##########################################

I tested it by ansible-playbook command line with -s -k parameter by vagrant user, and it works fine.
vagrant@server01:~$ ansible-playbook -s -k /tmp/nginx.yml

However, it didn't work when I move the nginx.yml to Ansible Tower project and job. when it submit the job and always got the below error message, my credential user is vagrant with ssh key setup and login by sudo password 
###### 

Identity added: /tmp/ansible_tower_x1TPr4/tmpPVgbZl (/tmp/ansible_tower_x1TPr4/tmpPVgbZl)
SSH password: 
sudo password [defaults to SSH password]: 

PLAY [all] *******************************************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [192.168.80.106]

TASK: [Installs nginx web server] ********************************************\* 
failed: [192.168.80.106] => {"failed": true}
msg: Failed to lock apt for exclusive operation

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/var/lib/awx/mesos.retry

192.168.80.106             : ok=1    changed=0    unreachable=0    failed=1   
###### 

I believe this maybe the sudo permission, but don't know how to fix in Ansible Tower as the same file submit by command line works. 

Appreciate if someone could point out the issue maybe?
thanks!

**Comment by sukenneth** [comment]
My Ansible

 --version
ansible 1.8.4
  configured module search path = None

**Comment by sukenneth** [comment]
My Ansible
--version
ansible 1.8.4
configured module search path = None

My OS 
Ubuntu 14.04

**Comment by bcoca** [comment]
for tower, send questions to support@ansible.com

On Thu, Apr 2, 2015 at 1:54 PM, sukenneth notifications@github.com wrote:

> My Ansible
> --version
> ansible 1.8.4
> configured module search path = None
> 
> My OS
> Ubuntu 14.04
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible/issues/10604#issuecomment-88990965.

## 

Brian Coca

**Comment by sukenneth** [comment]
oh, ok, thanks!
