### ISSUE TITLE
Please provide deb packages for Ubuntu Utopic

### ISSUE THREAD

**Issue by laurentj** [ansible/ansible#10617]
[The ppa repository](https://launchpad.net/~ansible/+archive/ubuntu/ansible) does not provide packages for Ubuntu Utopic.

**Comment by mrdrmmn** [comment]
I was just coming to open the same issue.  utopic has been out almost 6 months and vivid should be dropping in 10 days.  Perhaps both can be knocked out at the same time?

The main reason I felt this was worthy of opening an issue is that the installation documentation indicates using the ppa for installs on ubuntu as to correct way to do it.  If the ppa is not going to be kept up to date for new releases, then it probably should not be documented as the primary install method for ubuntu and rather listed as a secondary option on ubuntu.

Perhaps using the ppa is not/was not intended as the primary source for ansible on ubuntu, but it "feels" like that was the intent.

**Comment by geerlingguy** [comment]
Utopic was [EOL'ed in June last year](https://lists.ubuntu.com/archives/ubuntu-announce/2015-July/000197.html)... does Ansible support the non-LTS versions of Ubuntu? It might be good to have a general guideline for what distros Ansible's packaging will support, and how long those packages will be maintained (for RHEL, Deb/Ubuntu, etc.).

**Comment by jctanner** [comment]
utopic is no longer a supported release http://fridge.ubuntu.com/2015/07/03/ubuntu-14-10-utopic-unicorn-reaches-end-of-life-on-july-23-2015/
