### ISSUE TITLE
TypeError: varLookup() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by titanous** [ansible/ansible#1064]
Since bf47bb475305a66836e007c0c7f895af4aa88990 I've been getting this error on some plays:

```
Traceback (most recent call last):
  File "/home/ubuntu/ansible/lib/ansible/runner/__init__.py", line 224, in _executor
    exec_rc = self._executor_internal(host)
  File "/home/ubuntu/ansible/lib/ansible/runner/__init__.py", line 261, in _executor_internal
    items = utils.varLookup(self.basedir, items, inject)
TypeError: varLookup() takes exactly 2 arguments (3 given)
```

It looks like calls to `utils.varLookup` ([here's the one that's blowing up](https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/__init__.py#L261)) were updated with a new signature, but the [method itself](https://github.com/ansible/ansible/blob/devel/lib/ansible/utils.py#L185-194) doesn't seem to have the three argument signature.

**Comment by titanous** [comment]
Here's an example play that causes this error:

``` yaml
- name: add authorized keys
  action: authorized_key user=deploy key="$item" state=present
  with_items: $deploy_user_keys
```

**Comment by mpdehaan** [comment]
Ok, I'll revert the patch for now.

**Comment by mpdehaan** [comment]
Ok, reverted.

We'll get the FILE/PIPE stuff back in later.

@dhozac -- want to try to reapply and fix the above?

**Comment by titanous** [comment]
Thanks!

**Comment by mpdehaan** [comment]
merged, per above, thanks @dhozac!
