### ISSUE TITLE
Syntax error on new installation 

### ISSUE THREAD

**Issue by felixgao** [ansible/ansible#10653]
I did a pip3 install ansible on osx mavericks 
...omitting many lines
  Running setup.py install for ansible
    changing mode of build/scripts-3.4/ansible from 644 to 755
    changing mode of build/scripts-3.4/ansible-playbook from 644 to 755
    changing mode of build/scripts-3.4/ansible-pull from 644 to 755
    changing mode of build/scripts-3.4/ansible-doc from 644 to 755
    changing mode of build/scripts-3.4/ansible-galaxy from 644 to 755
    changing mode of build/scripts-3.4/ansible-vault from 644 to 755
    Sorry: TabError: inconsistent use of tabs and spaces in indentation (group.py, line 124
    changing mode of /usr/local/bin/ansible to 755
    changing mode of /usr/local/bin/ansible-doc to 755
    changing mode of /usr/local/bin/ansible-galaxy to 755
    changing mode of /usr/local/bin/ansible-playbook to 755
    changing mode of /usr/local/bin/ansible-pull to 755
    changing mode of /usr/local/bin/ansible-vault to 755
Successfully installed PyYAML-3.11 ansible-1.9.0.1 ecdsa-0.13 paramiko-1.15.2 pycrypto-2.6.1

``` sh
 /usr/local/bin/ansible
  File "/usr/local/bin/ansible", line 203
    except errors.AnsibleError, e:
                              ^
```

**Comment by sivel** [comment]
python 3 is not supported by ansible yet.  You must use python 2 to run ansible as of this time.  As such you will need to use `pip` or `pip2` instead of `pip3`

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
