### ISSUE TITLE
v2: no json output, all tasks are "empty"

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#10650]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 2.0 (devel 9e5c65babd)
##### Environment:

Mac OS 10.10.3
##### Summary:

`gather_facts` seems to be broken, other modules behaviour look odd as well.
##### Steps To Reproduce:
1. Clone the latest version, set env
   
   ```
   git clone -b devel --recursive https://github.com/ansible/ansible.git ansible
   cd ansible
   source v2/hacking/env-setup
   ```
2. Try to get facts from any host:
   
   ```
   ansible -m setup -i hosts.yml -vvv certs_12
   ```
3. Try other module with the following task:
   
   ```
   - name: test
   shell: echo ok > /tmp/test
   ```
##### Expected Results:

Json with facts, starting with:

```
certs_12 | success >> {
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [
```

```
TASK: [test] ****************************************************************** 
changed: [certs_12]
```
##### Actual Results:

No facts. The same with other modules: they just become “green” without any actual work done.

```
$ ansible -m setup -i hosts.yml certs_12

PLAY: <no name specified> *******************************************************

TASK [setup] ********************************************************************
ok: [certs_12]
```

``````
TASK [test] *********************************************************************
ok: [certs_12]
```.
``````

**Comment by bcoca** [comment]
I'm not sure what this means, can you fill in the template?

**Comment by hryamzik** [comment]
@bcoca my bad, here you are (see updated issue).

**Comment by bcoca** [comment]
ah, callback does not seem to be implemented for ad-hoc yet

**Comment by hryamzik** [comment]
So is there any way to get tasks executed?

**Comment by bcoca** [comment]
i believe they are getting executed, you might not just be getting the output you want

**Comment by hryamzik** [comment]
Nope, `/tmp/test` is not created with this version of ansible.

**Comment by jimi-c** [comment]
The callback is implemented, however since I moved v2 to using a new callback API it needs to be updated with the new method names. I'll get this fixed, but it also will require a little more work to prevent multiple callbacks from being fired off by default as v2 properly uses callbacks as plugins.

**Comment by hryamzik** [comment]
@jimi-c so is there any commit with working modules? I'm dying on playing with `include` + `with_items`.

**Comment by jimi-c** [comment]
I've fixed the "minimal" callback so the `ansible` command should show the output now too. Before this, only the `ansible-playbook` command would correctly show the callback output.

**Comment by jimi-c** [comment]
This should all be cleared up now, so closing.

Thanks!
