### ISSUE TITLE
AnsibleModule doing json conversion of param

### ISSUE THREAD

**Issue by sacharya** [ansible/ansible#10659]
When a param is loaded into the AnsibleModule, if the param happens to be json content, the module reads it as dict and there is no way to get the actual raw content.

eg. copy: content={{ lookup('file', 'myfile.json') }} dest="~/myfile.json"

The module shouldn't manipulate the param at all.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

First, you can just copy: src=myfile.json dest="~/myfile.json" in which case the content won't be processed. 

When putting data into content= you are getting it parsed at least 3 times and interpreted, this is before the module ever getting it, there is no way to avoid this. This option is not meant to deal with complex data but for simple/short pieces of text, for anything more complex we recommend using the template module.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
