### ISSUE TITLE
Use submodules for plugins

### ISSUE THREAD

**Issue by xakraz** [ansible/ansible#10657]
**Issue Type:**

Feature Idea

**Ansible Version:**

Ansible 1.9.X and above

**Environment**

Ubuntu, Debian, MacOS

**Summary**

There are multiple ways to install Ansible
- Running From Source
- Latest Release Via OS Packages
- Latest Releases Via Pip

However, plugins distribution is not well formalized.
- From source you get the "plugins" directory, which is not included into PIP package.
- http://docs.ansible.com/developing_plugins.html#distributing-plugins and http://docs.ansible.com/intro_configuration.html speak about plugins distribution and path where deploy them.
- But there is nothing about the "inventory" plugins, which are part of ansible sources `plugins/inventory`.

**Steps To Reproduce:**

**Expected Results:**

It would be nice to have a dedicated repository `ansible-plugins` to submit plugins (extract like `ansible-example` #9705.

It could behave like `ansible-modules-core` and be a git submodule and so beeing distributed via PIP properly or released as a dedicated pip package since it is already merged in Ansible source tree.

**Actual Results:**

**Comment by bcoca** [comment]
you might get a better discussion going by posting this to ansible-devel

**Comment by jimi-c** [comment]
Since we have collapsed the modules now, we will not be doing any more submodules for the foreseeable future. As such we will close this now.

Thanks!
