### ISSUE TITLE
Doc - developing_plugins.html#distributing-plugins

### ISSUE THREAD

**Issue by xakraz** [ansible/ansible#10655]
**Issue Type:**

Documentation Report

**Ansible Version:**

All

**Environment:**

Does not apply

**Summary:**

 inconsistency about plugins path in Ansible

I don't know yet how to fix the doc and submit a PR but : 
- http://docs.ansible.com/intro_configuration.html : Mention default plugins path like

``` shell
/usr/share/ansible_plugins/action_plugins
```
- http://docs.ansible.com/developing_plugins.html#distributing-plugins : Mention default plugin path is 

``` shell
/usr/share/ansible/plugins
```

**Steps To Reproduce:**

**Expected Results:**

**Actual Results:**

**Comment by bcoca** [comment]
These are subject to change by the package maintainers downstream, we reflect the default/expected locations.
