### ISSUE TITLE
support inline comments in ~/.ansible.cfg

### ISSUE THREAD

**Issue by est** [ansible/ansible#10660]
~/.ansible.cfg was

```
[defaults]
timeout = 10 # seconds
```

result was

```
~$ ansible all -m ping
Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 36, in <module>
    from ansible.runner import Runner
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 36, in <module>
    import ansible.constants as C
  File "/usr/local/lib/python2.7/site-packages/ansible/constants.py", line 110, in <module>
    DEFAULT_TIMEOUT           = get_config(p, DEFAULTS, 'timeout',          'ANSIBLE_TIMEOUT',          10, integer=True)
  File "/usr/local/lib/python2.7/site-packages/ansible/constants.py", line 40, in get_config
    return int(value)
ValueError: invalid literal for int() with base 10: '10 # seconds'
```

Can we support comments in config?

**Comment by tersmitten** [comment]
> Lines beginning with '#' or ';' are ignored and may be used to provide comments.
> 
> Configuration files may include comments, prefixed by specific characters (# and ;). Comments may appear on their own in an otherwise empty line, or may be entered in lines holding values or section names. In the latter case, they need to be preceded by a whitespace character to be recognized as a comment. (For backwards compatibility, only ; starts an inline comment, while # does not.)

See https://docs.python.org/2/library/configparser.html

**Comment by bcoca** [comment]
closing this as we depend on configparser for parsing ansible.cfg and we are stuck with what it provides, as @tersmitten copied above.
