### ISSUE TITLE
sudo and sudo_user don't work at the playbook-level under certain conditions

### ISSUE THREAD

**Issue by pearofducks** [ansible/ansible#10672]
##### Summary:

sudo + sudo_user don't work when used as:

```
- include: tasks/test.yml
  sudo: yes
  sudo_user: test
```

but do work at the task-level:

```
- name: echo username
  shell: whoami
  register: result_of_test
  sudo: yes
  sudo_user: test
```

This doesn't seem like a problem with Vagrant itself, but might be related to how Vagrant is calling Ansible (which seems to only be through available flags/settings[1]) - either way it causes unreliable behavior.
##### Steps To Reproduce:

Run `vagrant up` with the following files:

**Vagrantfile**

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "chef/debian-7.8"
  config.vm.hostname = "test"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
```

**playbook.yml**

```

---
- hosts: all
  tasks:
  - name: Modify users
    user: >
      home=/home/test
      name=test
      password=$1$saltsalt$qjXMvbEw8oaL.CzflDtaK/
      shell=/bin/bash
      groups=sudo
      state=present
    sudo: yes
  - include: tasks/test.yml
    sudo: yes
    sudo_user: test
```

**tasks/test.yml**

```

---
- name: echo user
  shell: whoami
  register: result_of_test
- name: display
  debug: msg={{result_of_test.stdout}}
```
##### Expected Results:

`whoami` should result in a current user of `test`

_or, at the very least the results should be consistent between playbook-level and task-level flag changes_
##### Actual Results:

`whoami` results in `vagrant` being the active user

---

[1] Vagrant displays the Ansible call as:

```
==> default: Running provisioner: ansible...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --private-key=/Users/pear/test/vaganstest/.vagrant/machines/default/vmware_fusion/private_key --user=vagrant --connection=ssh --limit='default' --inventory-file=/Users/pear/test/vaganstest/.vagrant/provisioners/ansible/inventory playbook.yml
```

**Comment by bcoca** [comment]
there is a bug with sudo and include, that should be fixed in current devel, but not at play level. Please test again with current devel.

**Comment by pearofducks** [comment]
Confirmed working against current devel. Thanks :)
