### ISSUE TITLE
Service module state=restarted, will error if the service hasn't been started yet

### ISSUE THREAD

**Issue by evanmoran** [ansible/ansible#1067]
Currently the service _does_ restart even when the service is stopped initially, but the error stops the rest of the scripts from running. So if you set multiple services to restart only the first will do so.

**Comment by mpdehaan** [comment]
Need lots more information.  What service?  What OS?  What does your playbook say? What version of Ansible?

-- Michael

**Comment by mpdehaan** [comment]
Also, what error?

-- Michael

**Comment by evanmoran** [comment]
My apologies for not adding more data. It doesn't work on all of my services so I just assumed it independent of platform. Here is my info:

Ansible version:

```
ansible 0.8
```

Platform: 

```
Ubuntu Server 12.04.1 LTS
```

Services: 
- mongodb 
- node server running express

The error is the standard error `start` gives when it is stopping something already stopped: 

```
stop: Unknown instance: 
```

Here is the rule in ansible:

```
tasks:

  - name: restart.production.db
    action: service name=mongodb state=restarted
```

Here is the log from ansible:

```
TASK: [restart.production.db] ********************* 
<server1> ESTABLISH CONNECTION FOR USER: ubuntu
<server1> EXEC ['ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', u'User=ubuntu', 'server1', 'mkdir -p $HOME/.ansible/tmp/ansible-1348168702.71-230565376820433 && chmod a+rx $HOME/.ansible/tmp/ansible-1348168702.71-230565376820433 && echo $HOME/.ansible/tmp/ansible-1348168702.71-230565376820433']
<server1> REMOTE_MODULE service name=mongodb state=restarted
<server1> PUT /var/folders/td/s3t2rx052374k3p15gclfbjw0000gn/T/tmpUgVb0g TO /home/ubuntu/.ansible/tmp/ansible-1348168702.71-230565376820433/service
<server1> EXEC ['ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', u'User=ubuntu', 'server1', u'chmod u+x /home/ubuntu/.ansible/tmp/ansible-1348168702.71-230565376820433/service']
<server1> EXEC ['ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', u'User=ubuntu', 'server1', u'sudo -k && sudo -p "[sudo via ansible, key=rwnzjzenevwgkwwsdmfmgeubhmasoqow] password: " -u root "$SHELL" -c /home/ubuntu/.ansible/tmp/ansible-1348168702.71-230565376820433/service']
<server1> EXEC ['ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', u'User=ubuntu', 'server1', 'rm -rf /home/ubuntu/.ansible/tmp/ansible-1348168702.71-230565376820433/']
failed: [server1] => {"failed": true, "msg": "stop: Unknown instance: \n"}
```

**Comment by mpdehaan** [comment]
Hmm, Ubuntu/upstart specific, I agree this error is unacceptable.  Thanks for clarifying and will get someone to take a look.

-- Michael

**Comment by mpdehaan** [comment]
Anyone in Ubuntu land want to take a look at this one?  @sfromm or @dhozac perhaps?

(I forget what you guys use)

**Comment by sfromm** [comment]
I'm more of a fedora / redhat user, but I have an ubuntu vm I can poke at.

On Tue, Sep 25, 2012 at 5:41 PM, Michael DeHaan notifications@github.comwrote:

> Anyone in Ubuntu land want to take a look at this one? @sfrommhttps://github.com/sfrommor
> @dhozac https://github.com/dhozac perhaps?
> 
> (I forget what you guys use)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/1067#issuecomment-8875294.

## 

Stephen Fromm

**Comment by sfromm** [comment]
For background, the service module does a _stop_ and _start_ action on the service.  The first service command returns a rc 1 and prints the message _Unknown instance_ on stderr.  The second service command returns rc 0 and a typical started message on stdout.  Because the service adds the two return codes together, it determines there was a failure and includes the stderr message but not the stdout.  PR #1096 resolves this issue in my testing.  @evanmoran, please try and let us know.

**Comment by mpdehaan** [comment]
Thanks very much @sfromm, closing this for now.   @evanmoran, if this does not work for you, let me know and we can reopen it.

**Comment by evanmoran** [comment]
@sfromm  @mpdehaan  This works perfectly. Thank you for the great fix!

**Comment by such** [comment]
I have the same issue with openvpn service:

```
failed: [XX.XX.XX.XX] => {"failed": true, "item": ""}
msg:  * Stopping virtual private network daemon(s)...
 *   No VPN is running.
 * Starting virtual private network daemon(s)...
 *   Autostarting VPN 'vpn'
```

I'm using:

```
ansible 1.3
```

The service is run on:

```
Ubuntu 12.04.2 LTS
```

Edit: my bad, the output was a bit confusing but it was actually failing because I was not sudoing. No issue then.
