### ISSUE TITLE
when statement doesnt work with include

### ISSUE THREAD

**Issue by rahulmehrotra1** [ansible/ansible#10682]
when statement doesn't get evaluated properly and always returns true when used in combination of include statement

to reproduce the error

**_site.yml**_

```

---
- include: rds/rds.yml
- include: elasticache/elasticache.yml
- include: acralyzer.yml 
  when: env == "prod"
- { include: npmserver.yml, when: env == "prod" }

```

then executing using the following statement

`ansible-playbook site.yml --ask-vault-pass --extra-vars "env=dev" -vvvv`

irrespective of the value of **_env**_ when statement gets evaluated as true and npmserver.yml & acralyzer.yml gets executed.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

In any case, when clauses do not apply to the include itself but to every task included.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
