### ISSUE TITLE
Bug: Numbers and booleans are converted into template string when they shouldn't

### ISSUE THREAD

**Issue by dorianpula** [ansible/ansible#10694]
Numbers and booleans are converted to template string when they shouldn't be converted.

Affected issue: v2 milestone

Steps to reproduce:
- Install ansible v2 via `pip install -e .`
- Run non destructive integration tests:

```
cd ansible/test/integration
ansible-playbook non_destructive.yml -i inventory -e @integration_config.yml  -vvvv -k -K  
```

Test result:

```
TASK: [test_template | compare templated file to known good] ****************** 
<127.0.0.1> REMOTE_MODULE command diff ~/ansible_testing/foo.templated ~/ansible_testing/foo.txt #USE_SHELL
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1428957144.09-3485271703689 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1428957144.09-3485271703689 && echo $HOME/.ansible/tmp/ansible-tmp-1428957144.09-3485271703689']
<127.0.0.1> PUT /tmp/tmpJk8rv3 TO /home/dorian.pula/.ansible/tmp/ansible-tmp-1428957144.09-3485271703689/command
<127.0.0.1> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/env python /home/dorian.pula/.ansible/tmp/ansible-tmp-1428957144.09-3485271703689/command; rm -rf /home/dorian.pula/.ansible/tmp/ansible-tmp-1428957144.09-3485271703689/ >/dev/null 2>&1']
failed: [testhost] => {"changed": true, "cmd": "diff ~/ansible_testing/foo.templated ~/ansible_testing/foo.txt", "delta": "0:00:00.001880", "end": "2015-04-13 16:32:24.124525", "rc": 1, "start": "2015-04-13 16:32:24.122645", "warnings": []}
stdout: 4c4
<     "bool": "True", 

---
>     "bool": true, 
6c6
<     "number": "5", 

---
>     "number": 5, 

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
```

Expected result: Tests pass and numbers and booleans are not escaped by Jinja2.

Changes related to PR: https://github.com/ansible/ansible/pull/10465  However issue not resolved by PR for v2 milestone.

**Comment by abadger** [comment]
@feanil I guess it's goodthat we added those integration tests ;-)  Any ideas on what to do here?

**Comment by abadger** [comment]
@feanil Note: @mchlumsky is looking at htis at the sprints as well.

**Comment by mchlumsky** [comment]
Ok, so it looks like the test now passes:

TASK [test_template : compare templated file to known good] *********************
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
127.0.0.1 EXEC mkdir -p $HOME/.ansible/tmp/ansible-tmp-1429029883.23-175453219681554 && echo $HOME/.ansible/tmp/ansible-tmp-1429029883.23-175453219681554
127.0.0.1 PUT /tmp/tmpjoMZC3 TO /root/.ansible/tmp/ansible-tmp-1429029883.23-175453219681554/command
127.0.0.1 EXEC LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1429029883.23-175453219681554/command; rm -rf /root/.ansible/tmp/ansible-tmp-1429029883.23-175453219681554/ >/dev/null 2>&1
changed: [testhost] => {"changed": true, "end": "2015-04-14 12:44:43.339999", "stdout": "", "cmd": "diff ~/ansible_testing/foo.templated ~/ansible_testing/foo.txt", "start": "2015-04-14 12:44:43.334684", "delta": "0:00:00.005315", "stderr": "", "rc": 0, "invocation": {"module_name": "command", "module_args": {"_raw_params": "diff ~/ansible_testing/foo.templated ~/ansible_testing/foo.txt", "_uses_shell": true}}, "stdout_lines": [], "warnings": []}

Can you re-test?

I am running the tests like this:
ansible-playbook non_destructive.yml -i inventory -e @integration_config.yml -e ansible_ssh_user=root  -vvvv -c local

**Comment by abadger** [comment]
@dorianpula ^ That request to retest is for you.  We are hoping that this is fixed now but want to confirm it's not just a difference in how you had your environment setup to run the test vs how we do.

**Comment by dorianpula** [comment]
@abadger Confirmed that particular bug no longer affects.  Another one later on fails:

```
TASK [test_template : ensure file mode did not change] **************************
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: dorian.pula
ok: [testhost] => {"msg": "all assertions passed", "changed": false}

TASK [test_template : setup directory for test] *********************************
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: dorian.pula
<127.0.0.1> EXEC sshpass -d12 ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/ansible-ssh-%h-%p-%r" -o Port=22 -o GSSAPIAuthentication=no -o PubkeyAuthentication=no -o ConnectTimeout=15 127.0.0.1 mkdir -p $HOME/.ansible/tmp/ansible-tmp-1429110074.94-104417729248515 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1429110074.94-104417729248515 && echo $HOME/.ansible/tmp/ansible-tmp-1429110074.94-104417729248515
<127.0.0.1> PUT /tmp/tmpUIm5vS TO /home/dorian.pula/.ansible/tmp/ansible-tmp-1429110074.94-104417729248515/file
<127.0.0.1> EXEC sshpass -d12 ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/ansible-ssh-%h-%p-%r" -o Port=22 -o GSSAPIAuthentication=no -o PubkeyAuthentication=no -o ConnectTimeout=15 127.0.0.1 LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/dorian.pula/.ansible/tmp/ansible-tmp-1429110074.94-104417729248515/file; rm -rf /home/dorian.pula/.ansible/tmp/ansible-tmp-1429110074.94-104417729248515/ >/dev/null 2>&1
fatal: [testhost]: FAILED! => {"group": "dorian.pula", "uid": 1124085206, "changed": false, "owner": "dorian.pula", "failed": true, "state": "directory", "gid": 1124085206, "mode": "0775", "msg": "chown failed", "invocation": {"module_name": "file", "module_args": {"dest": "/home/dorian.pula/ansible_testing/template-dir", "owner": "nobody", "state": "directory", "group": "root", "mode": "0755"}}, "path": "/home/dorian.pula/ansible_testing/template-dir", "size": 4096}

PLAY RECAP **********************************************************************
testhost                   : ok=20   changed=6    unreachable=0    failed=1 
```

However this particular issue has been resolved for me.
