### ISSUE TITLE
Feature idea: within-host parallelization for with_items loops

### ISSUE THREAD

**Issue by wincent** [ansible/ansible#10695]
This has come up before (for example, see [this mailing list thread](https://groups.google.com/forum/#!topic/ansible-devel/lhvukkszKUA)), but the basic idea is that you may want to run a large number of `command` module operations on a single host in parallel via `with_items` if they don't have any dependencies on one another.

In that thread, the specific example is a 10-host inventory, but with about 500 commands to run on each host, each command taking 2 seconds.

It seems that Ansible has multi-host parallelism baked into it deeply, but doing any kind of within-host parallelism requires some hackery. For example, you can trick Ansible into using it's multi-host parallelism by creating fake inventory entries and having a play that targets those "hosts", which are really all just aliases of the same machine ([as suggested here](https://groups.google.com/d/msg/ansible-project/8Yh4jy68Kmk/GJC2y44XjNAJ)). Depending on the complexity of your playbook, this might get complicated to do, and it obfuscates what's really going on for people reading the playbook.

Another thing you can do is to run a script that has some parallelism internally (for example, you can template out a script that forks and runs multiple commands) but then you lose some of the nice things that Ansible gives you around change-detection and reporting.

So, the idea here is effectively to add some kind of option to Ansible to signal that it should try running multiple entries from a `with_items` list in parallel (probably a number indicating the desired level maximum of concurrent tasks) when connecting to a particular host. I can see this as being most useful with the `command` module (or perhaps the `shell` module), but there may be other use cases as well.

**Comment by zeelot** [comment]
+1. This would be very useful to me with template files. I manage upstart scripts with ansible and sometimes need to create 100+ upstart scripts on a server and I could theoretically write all of them at once without any trouble. Running them one by one takes a _very_ long time.

**Comment by realcnbs** [comment]
+1. Voting for this one, this feature can save lots of time of useless staring at the one-by-one slow execution.

**Comment by mackstann** [comment]
Just googled to see if this existed and wound up here. It'd be very useful. In some cases it can save lots of time, and it could be optional so that it doesn't cause any harm in cases where parallel jobs could step on each other.

**Comment by mm0** [comment]
+1 This would be a great feature

**Comment by LLParse** [comment]
+1. I would love to see this feature included in a future release. My particular use case is operating on a REST web service where several resources need to be created. Similar to the way multi-host tasks are parallelized, I'd need to control the number of forks on a per-task basis. Maybe this option could be implemented for `with_items` loops, with the default being 1 (existing functionality). When this new option is > 1, any registered output's results would necessarily be out-of-order, but I think that would be okay for the majority of cases where single-host parallelization is desired.

**Comment by nicocesar** [comment]
+1 my usecase involves creating tens of firewalling rules with gce_net module. they can all be done in parallel.  I'm  using `with_items` too

**Comment by nerzhul** [comment]
:+1:

**Comment by ThePixelDeveloper** [comment]
:+1:

**Comment by redrampage** [comment]
+1. I have a lot of simple templates to generate, it takes forever.

**Comment by akme** [comment]
:+1:

**Comment by sapun** [comment]
+1

**Comment by stevenalowe** [comment]
+1 yes please. I'm running multiple experiments at once on a multi-core VM

**Comment by clickfreak** [comment]
+1

**Comment by bcoca** [comment]
closing as a subset of #12086

**Comment by doker78** [comment]
+1

**Comment by mindcurv-jerald** [comment]
+1

**Comment by isaacegglestone** [comment]
+1

**Comment by isaacegglestone** [comment]
+1

**Comment by singhr49** [comment]
This is most needed feature. I've 50+ filesystems which need to be created, I can't wait each one to complete. 
+1
