### ISSUE TITLE
Knowing whether a playbook is run in check mode

### ISSUE THREAD

**Issue by astorije** [ansible/ansible#10696]
##### Issue Type:

Feature Idea
##### Ansible Version:

To this day, this feature does not exist. I am running `ansible 1.9.0.1`.
##### Environment:

N/A
##### Summary:

It is natively impossible to know from a task, a role, or a playbook, if we are running in [check mode](http://docs.ansible.com/playbooks_checkmode.html) or not.
##### Steps To Reproduce:

It can be very useful though. For example, some module (`ufw`, `git`, ...) require that the underlying executable must be installed. Lots of roles do that as a first task. If the task is run in check mode for the first time, the role will fail. Same applies if you try to do changes to a user that was not created, to create a symlink on a file that was not copied over yet, ...

In some cases, just knowing that we are in check mode is enough (although I agree that some cases require more work, like checking the presence of an executable which `which`, the presence of a user with `id`, ... but in the end, knowing that we are in check mode is still very valuable even in those cases).
##### Expected Results:

A variable? An extra fact? A extra directive at the same level than `always_run`, `when`, ... ? Not sure what is the best way to present this but I'd be happy to have others' opinions.
##### Actual Results:

Since it's not part of Ansible yet, it's still doable but through very [hacky solutions](http://stackoverflow.com/questions/28729567/skip-ansible-task-when-running-in-check-mode). This same page also shows some more use cases for this.

**Comment by hsingh** [comment]
:+1:

**Comment by selivan** [comment]
+1 for this issue
