### ISSUE TITLE
catch invalid options in playbooks

### ISSUE THREAD

**Issue by mgwilliams** [ansible/ansible#107]
Would be nice if the following would generate an error:

``` yaml```
- name: something will change
  action: copy src=foo dest=bar
  natify: 
  - restart-some-service
```

Note that notify is misspelled as natify.

If this is accepted as a bug, feel free to assign to me ;-).

**Comment by mpdehaan** [comment]
sounds completely reasonable

probably should be done via constants like:

VALID_TASK_OPTIONS = [ 'notify', ...]
VALID_HANDLER_OPTIONS = []

etc

**Comment by mpdehaan** [comment]
looks like I am unable to assign to someone outside the commit group, but if you'd like to fix it, that would be great.

thanks again for all your work and feedback on Ansible, it is much appreciated.

**Comment by mpdehaan** [comment]
suggest we defer this until after some playbook refactoring I intend to do a bit later...

**Comment by mpdehaan** [comment]
disagree with this actually, as you can comment things in YAML and that shouldn't be illegal
