### ISSUE TITLE
authorized_key module does not accept file as an argument for the key parameter

### ISSUE THREAD

**Issue by nszceta** [ansible/ansible#10702]
The key parameter accepts a key verbatim or a URL but does not support a file path in v1.9.0.1

Passing with_file into the module results in:
fatal: could not locate file in lookup: /path/to/key.pub

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
