### ISSUE TITLE
Jinja2 lstrip_blocks as a default

### ISSUE THREAD

**Issue by aabdnn** [ansible/ansible#10725]
Dear Ansible devs,

We often have long and complex templates, with lots of Jinja2 loops and conditionals. It's handy to indent them, so to make it easier to read the template.

I see that "trim_blocks" is already the default in the template module. I think it makes sense to also set "lstrip_blocks". Users can easily override this by adding a '+' in the start tag.

The Jinja2 documentation suggests that "trim_blocks" and "lstrip_blocks" works well in combination, so it would be nice to have it as an ansible default.

**Comment by asmartin** [comment]
I have also found this to be a problem in my templates, for example loops will result in incorrect "double" indentation once the template is expanded, so I would find this enhancement useful as well

**Comment by franklinwise** [comment]
:+1:  agree

**Comment by bcoca** [comment]
you can easily add this using template overrides, add `#jinja2: lstrip_blocks: True` to the top of the template

**Comment by ghost** [comment]
I tried this and it does not work:

<pre>
user@host:~/ansible-playbooks$ ansible --version
ansible 1.9.1
</pre>

<pre>
test.yml :
---
 - hosts: '{{ hostlist }}'
   remote_user: root
   vars:
    - qwerty: true
    - item:
      - asdf1
      - asdf2
      - asdf3
      - asdf4
   tasks:
    - template: src=test.j2 dest=/tmp/test
</pre>

test.j2:

<pre>
#jinja2: lstrip_blocks: True
# {{ ansible_managed }}
{% for i in item %}
{{ i }}
        {% for j in item %}
        {{ j }}
        {% endfor %}
{% endfor %}
blob
        {% if qwerty %}
        inner blob
        {% endif %}
endblob
</pre>

expected results (based on my understanding of http://jinja.pocoo.org/docs/dev/templates/#whitespace-control):

<pre>
# Ansible managed: DO NOT EDIT BY HAND
asdf1
        asdf1
        asdf2
        asdf3
        asdf4
asdf2
        asdf1
        asdf2
        asdf3
        asdf4
asdf3
        asdf1
        asdf2
        asdf3
        asdf4
asdf4
        asdf1
        asdf2
        asdf3
        asdf4
blob
        inner blob
endblob
</pre>

actual results:

<pre>
# Ansible managed: DO NOT EDIT BY HAND
asdf1
                asdf1
                asdf2
                asdf3
                asdf4
        asdf2
                asdf1
                asdf2
                asdf3
                asdf4
        asdf3
                asdf1
                asdf2
                asdf3
                asdf4
        asdf4
                asdf1
                asdf2
                asdf3
                asdf4
blob
                inner blob
        endblob
</pre>

edit: version

**Comment by bcoca** [comment]
I cannot speak to the results, but the header feature did put the override into the jinja2 environment class, dumping it shows the configuration present.

**Comment by ghost** [comment]
How do you dump the configuration to see this?

**Comment by bcoca** [comment]
deubgger, and inspect the environment object

**Comment by jbruggem** [comment]
This problem also affects me. For some reason, jinja2 changes indentation on lines without any template code in it.

**Comment by ghost** [comment]
Using latest ansible (2.0.1 IIRC?) and I'm running into this issue. I've tried adding `#jinja2: lstrip_blocks: True` and removing; there is no change to the file on the filesystem; ansible does not believe it needs to be updated. I tried running the playbook with `-vvvvv` and I did not see the debug information that @bcoca mentioned; if you can give me more info I'll surely provide it. Basically, how do I print the environment?

Also, if I recall correctly this was working properly in a pre-2.0 version as I have it in some of my templates and even remember asking on IRC about it.

**Comment by SoumenDass** [comment]
I'm facing the same issue. Mentioning "#jinja2: trim_blocks: True, lstrip_blocks: True" has no effect whatsoever. Loops always result in an extra newline at the end. Various combinations of "%-" only end-up removing newline between loop elements which is not what I want.

**Comment by cvicente** [comment]
Same problem here. The override is not working. Ansible 2.0.2.0

**Comment by aptituz** [comment]
To the people having problem with the magic comment:
Have you double-checked that those magic comment is the very first line (literally) in your template? ansible does check for it with startswith (AFAICT) so it actually has to start the file. This way it works for me with ansible 2.1.0.0.

**Comment by kravietz** [comment]
@aptituz That was it, thanks!

**Comment by ghost** [comment]
Hi @aptituz ,

thank you for pointing this out. But I think it's still an issue:

```
#jinja2: trim_blocks: True, lstrip_blocks: True
# {{ ansible_managed }}

# Device
DEVICE="{{ item }}"
TYPE="Ethernet"
ONBOOT="yes"
NM_CONTROLLED="no"
BOOTPROTO="none"
PEERDNS="no"

{% if network.ethernet[item].ipv4.cidr | ipv4 %}
  # IPv4
  IPADDR="{{ network.ethernet[item].ipv4.cidr | ipaddr('address') }}"
  PREFIX="{{ network.ethernet[item].ipv4.cidr | ipaddr('prefix') }}"
    {% if network.ethernet[item].ipv4.cidr | ipaddr('size') == 1 %}
      SCOPE="peer {{ network.ethernet[item].ipv4.gateway | ipv4 }}"
    {% elif network.ethernet[item].ipv4.gateway | ipv4 %}
      GATEWAY="{{ network.ethernet[item].ipv4.cidr | ipaddr('net') | ipaddr('1') }}"
    {% endif %}
{% endif %}

# IPv6
{% if network.ethernet[item].ipv6.cidr | ipv6 %}
  IPV6INIT="yes"
  IPV6ADDR="{{ network.ethernet[item].ipv6.cidr | ipv6 }}"
  IPV6_DEFAULTGW="{{ network.ethernet[item].ipv6.gateway | ipv6 }}"
  IPV6_DEFAULTDEV="{{ item }}"
  IPV6_PEERDNS="no"
{% else %}
  IPV6INIT="no"
{% endif %}
```

I'd have exspected that the magic comment is set correctly and the output should've been rendered without any identation.

**Comment by yanc0** [comment]
This worked for me:

`#jinja2: trim_blocks: "true", lstrip_blocks: "false"`

You have to surround values by `"`

Hope this help ;)

**Comment by alikins** [comment]
Looks like this is working given the caveats of needing to be set in the first line of the template.

**Comment by yajo** [comment]
FTR If you're templating a YAML file, this makes it sane:

    #jinja2: lstrip_blocks: "true", trim_blocks: "false"

**Comment by OJFord** [comment]
@alikins I'm confused by the resolution here - the request was for it to be the _default_, so is "it works if you specify it" to be taken as "no, wontfix, we don't want this to be the default"?

Is there at least a way of specifying it globally for ansible, so it's not needed in every template?
