### ISSUE TITLE
Register variable is modified even if the step is skipped?!

### ISSUE THREAD

**Issue by pepee16** [ansible/ansible#10728]
I've got simple playbook with two tasks, both use command module and output is registered. One task is for RHEL6 and the other for RHEL7. Both share the same variable, because in one play just one task of the two will be played in the time, but if fact even if the second step is skipped, register variable is modified....

---PLAYBOOK EXAMPLE---
- name: Check, if httpd is running on RHEL6.
  command: bash -c "service httpd status|grep -E 'httpd (pid  [0-9]*) is running'"
  register: httpd_running_go
  when: local_rhel_major_release == 6
  ignore_errors: yes
  sudo: yes
- name: DEBUG
  debug: var=httpd_running_go
- name: Check, if httpd is running on RHEL7.
  command: bash -c "service httpd status|grep 'Active. active (running)'"
  register: httpd_running_go
  when: local_rhel_major_release == 7
  ignore_errors: yes
  sudo: yes
- name: DEBUG
  ## debug: var=httpd_running_go

------OUTPUT EXAMPLE---------
TASK: [Check, if httpd is running on RHEL6.] ***\* 
failed: [localhost] => {"changed": true, "cmd": ["bash", "-c", "service httpd status|grep -E 'httpd (pid  [0-9]*) is running'"], "delta": "0:00:00.026705", "end": "2015-04-15 15:48:35.292366", "rc": 1, "start": "2015-04-15 15:48:35.265661", "warnings": []}
...ignoring

TASK: [DEBUG] *****************************************\* 
ok: [localhost] => {
    "var": {
        "httpd_running_go": {
            "changed": true, 
            "cmd": [
                "bash", 
                "-c", 
                "service httpd status|grep -E 'httpd (pid  [0-9]_) is running'"
            ], 
            "delta": "0:00:00.026705", 
            "end": "2015-04-15 15:48:35.292366", 
            "invocation": {
                "module_args": "bash -c \"service httpd status|grep -E 'httpd (pid  [0-9]_) is running'\"", 
                "module_name": "command"
            }, 
            "rc": 1, 
            "start": "2015-04-15 15:48:35.265661", 
            "stderr": "", 
            "stdout": "", 
            "stdout_lines": [], 
            "warnings": []
        }
    }
}

TASK: [Check, if httpd is running on RHEL7.] ***\* 
skipping: [localhost]

TASK: [DEBUG] *****************************************\* 
ok: [localhost] => {
    "var": {
        "httpd_running_go": {
            "changed": false, 
            "skipped": true
        }
    }
}

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

As a short answer, yes, vars are registered when task is skipped, this way other tasks can query it (var|skipped) to find out if it was.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
