### ISSUE TITLE
Oracle Linux no longer detected as a Red Hat clone

### ISSUE THREAD

**Issue by mavit** [ansible/ansible#10742]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.9.0.1
  configured module search path = None
```
##### Environment:

Oracle Linux Server release 7.1
##### Summary:

Oracle Linux is (mostly) built from the same SRPMs as Red Hat Enterprise Linux, so the `ansible_os_family` fact should be set to `RedHat`.  This used to work in Ansible 1.8.

I believe that this is a consequence of pull #10508.
##### Steps To Reproduce:

``` bash
ansible -m setup localhost | grep os_family
```
##### Expected Results:

```
        "ansible_os_family": "RedHat", 
```
##### Actual Results:

```
        "ansible_os_family": "Oracle Linux",
```

**Comment by william20111** [comment]
is this actually a bug? Like you said its mostly built from same SRPMs. And you can run the unbreakable kernel which is vastly different. I think current results are correct.

**Comment by bcoca** [comment]
closing this as we do not consider it a bug but a work around Oracle misrepresentation.

**Comment by mavit** [comment]
If this is the expected behaviour, then what is the `ansible_os_family` fact supposed to be for?  It's set to `RedHat` on both CentOS (which is very similar to Oracle Linux) and Fedora (which is significantly different to RHEL).  We have another fact, `ansible_distribution`, for telling these distributions apart from each other.

By the way, I have commit d8be6fec65415407e5970ac06fd40e06b5b6af22 which I'm happy to turn into a pull request if you reconsider.

**Comment by bcoca** [comment]
sorry, mixed things, yes, family should still be redhat but distro must be oracle linux.
