### ISSUE TITLE
git module intermittent ssh connection errors

### ISSUE THREAD

**Issue by kilburn** [ansible/ansible#10748]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.9.0.1
  configured module search path = None
```
##### Environment:

Controller: OS X 10.10.2
Controlled: Ubuntu 14.04
##### Summary:

Ansible consistently fails when updating several git repositories on a `git` + `with_items` task. The first time around (when the repos are initially cloned) works fine, but afterwards it consistently fails after checking the first few repositories.
##### Steps To Reproduce:

I can reproduce this problem in a fairly minimal setup. I have a clean `Ubuntu 14.04` virtual machine as the `web.dev.test` host (ip mapped through `/etc/hosts`), and setup in the `inventory` file as follows:

```
[servers]
web.dev.test
```

I also have a simple playbook `example.yml`:

``` ---
- hosts: all
  tasks:
    - name: git clone a bunch of repositories
      git: repo=git@github.com:kilburn/ansible-test.git accept_hostkey=yes version=master
        dest=/tmp/copy{{ item }}
      with_items: ['1', '2', '3', '4', '5', '6', '7', '8']
```

Authentication is done through  SSH agent forwarding (and working properly). Obviously you should replace `git@github.com:kilburn/ansible-test.git` by a repository that is accessible to you (the content does not matter).
##### Expected Results:

Running the playbook a first time should clone or update all repositories, each time, without errors.
##### Actual Results:

The task usually fails after processing a few items. It does not happen every time, so please give it a few tries.

```
$ ansible-playbook -i inventory example.yml 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [web.dev.test]

TASK: [git clone a bunch of repositories] ************************************* 
ok: [web.dev.test] => (item=1)
ok: [web.dev.test] => (item=2)
ok: [web.dev.test] => (item=3)
ok: [web.dev.test] => (item=4)
failed: [web.dev.test] => (item=5) => {"cmd": "/usr/bin/git ls-remote origin -h refs/heads/master", "failed": true, "item": "5", "rc": 128}
stderr: ssh_exchange_identification: Connection closed by remote host
fatal: The remote end hung up unexpectedly

msg: ssh_exchange_identification: Connection closed by remote host
fatal: The remote end hung up unexpectedly
failed: [web.dev.test] => (item=6) => {"cmd": "/usr/bin/git ls-remote origin -h refs/heads/master", "failed": true, "item": "6", "rc": 128}
stderr: ssh_exchange_identification: Connection closed by remote host
fatal: The remote end hung up unexpectedly

msg: ssh_exchange_identification: Connection closed by remote host
fatal: The remote end hung up unexpectedly
failed: [web.dev.test] => (item=7) => {"cmd": "/usr/bin/git ls-remote origin -h refs/heads/master", "failed": true, "item": "7", "rc": 128}
stderr: ssh_exchange_identification: Connection closed by remote host
fatal: The remote end hung up unexpectedly

msg: ssh_exchange_identification: Connection closed by remote host
fatal: The remote end hung up unexpectedly
failed: [web.dev.test] => (item=8) => {"cmd": "/usr/bin/git ls-remote origin -h refs/heads/master", "failed": true, "item": "8", "rc": 128}
stderr: ssh_exchange_identification: Connection closed by remote host
fatal: The remote end hung up unexpectedly

msg: ssh_exchange_identification: Connection closed by remote host
fatal: The remote end hung up unexpectedly

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/kilburn/example.retry

web.dev.test               : ok=1    changed=0    unreachable=0    failed=1  
```

Also, it does not always fail on the same item:

```
$ ansible-playbook -i inventory example.yml 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [web.dev.test]

TASK: [git clone a bunch of repositories] ************************************* 
ok: [web.dev.test] => (item=1)
ok: [web.dev.test] => (item=2)
ok: [web.dev.test] => (item=3)
ok: [web.dev.test] => (item=4)
ok: [web.dev.test] => (item=5)
ok: [web.dev.test] => (item=6)
ok: [web.dev.test] => (item=7)
failed: [web.dev.test] => (item=8) => {"cmd": "/usr/bin/git ls-remote origin -h refs/heads/master", "failed": true, "item": "8", "rc": 128}
stderr: ssh_exchange_identification: Connection closed by remote host
fatal: The remote end hung up unexpectedly

msg: ssh_exchange_identification: Connection closed by remote host
fatal: The remote end hung up unexpectedly

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/kilburn/example.retry

web.dev.test               : ok=1    changed=0    unreachable=0    failed=1   
```
##### Observations
- No settings were modified between these two runs
- I found the issue while working on a non-github-hosted git repository, so it is not a github-specific issue.
- I have tried enabling/disabling pipelining and ssh's `ControlPersist`. They make no difference.

I am out of ideas on what could the cause be :(

**Comment by kilburn** [comment]
Okay, I have more surprising information. I have tried to catch something by running `strace -p PID_OF_SSHD -f` in the controlled machine and then running the task.

Obviously, everything runs much slower but after quite a lot of tries I simply do not get any errors while stracing. Stop the tracing and it fails again quite quickly.

It may be some kind of racing condition...

**Comment by fle** [comment]
Same kind of problem here :(

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
