### ISSUE TITLE
Inventory group_vars/all folder not expanded when using inventory folders

### ISSUE THREAD

**Issue by rayalan** [ansible/ansible#10741]
##### Issue Type:

Bug Report 
##### Ansible Version:

1.8.2, 1.9.0.1
##### Environment:

Running from: OS X 10.8
Managing: N/A
##### Summary:

My inventory structure looks like this:

```
inventory/group_vars/all 
inventory/staging/static
```

When I run a playbook like this, group_vars/all doesn't get loaded:

```
ansible-playbook -i inventory/staging myplaybook.yml
```

If I rearrange the inventory like this:

```
cp inventory/staging/static inventory/staticstaging 
ansible-playbook -i inventory/staticstaging myplaybook.yml
```

Ansible loads group_vars/all. 
##### Steps To Reproduce:

inventory/group_vars/all

```
ansible_user : root 
```

inventory/staging/static:

```
host 
```

Playbook

```

---
- name: Failing playbook
  hosts: all
  user: "{{ ansible_user }}"
  tasks:
     - debug: msg="This failed to load {{ ansible_user }} up above, so this message doesnt' matter"
```
##### Expected Results:

```
ok: [host] => {
    "msg": "This failed to load root up above, so this message doesnt' matter"
}
```
##### Actual Results:

```
fatal: [host] => SSH Error: command-line line 0: garbage at end of line; "ansible_user"
```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Group vars are not available at play level, so what you are trying to do will never work.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
