### ISSUE TITLE
Setting sudo: yes in vars/main.yml is ignored

### ISSUE THREAD

**Issue by ipanousis** [ansible/ansible#10743]
Hi,

I just **upgraded from 1.8.4 to 1.9.0.1** and while my roles and inventory SSH configuration are unchanged:

**Inventory SSH Configuration:**

```
[group1:vars]
ansible_ssh_user=deployment
ansible_ssh_private_key_file=./files/dev/deployment_rsa
ansible_sudo_pass=password123
```

**my_role/vars/main.yml:**

```

---
sudo: yes
```

**This previously working task my_role/tasks/main.yml:**

```

---
- name: install jdk
  yum: pkg=jdk-{{ jdk_package_version }} state=present
```

**is now failing with:**

```
failed: [host1] => {"failed": true}
msg: Error from repoquery: ['/usr/bin/repoquery', '--show-duplicates', '--plugins', '--quiet', '-q', '--disablerepo=*', '--pkgnarrow=installed', '--qf', '%{name}-%{version}-%{release}.%{arch}', 'jdk-1.2.27.1.0-3707']: Could not set cachedir: [Errno 13] Permission denied: '/var/tmp/yum-deployment-aVYwNt'
Error: Could not make cachedir, exiting
```

whereas before the ansible upgrade it was working fine. I am **not** passing any sudo / user related configuration in CLI.

If I add sudo: yes to every task in the tasks/main.yml it works, but clearly this is not something I want to do.

Has something changed in the sudo / user precedence in the new ansible version that I should know about? This seems like a bug to me but I could be wrong..

Thanks in advance,
Yannis

**Comment by bcoca** [comment]
so sudo is not a var, it was never meant to work from vars/main.yml, that said, there was a bug in 1.9.0.1 that prevented it from working when calling a role:
- roles: {role: rolename, sudo: true}

this has been fixed, please try your setup with current devel or the 1.9.1rc2

**Comment by ipanousis** [comment]
Hi,

I think I'm going something wrong in my installation from source because, after following the instructions on http://docs.ansible.com/intro_installation.html#running-from-source and then running my playbook, I get this error:

```
ERROR: shell is not a legal parameter in an Ansible task or handler
```

My system is CentOS 6.6 with kernel 2.6.32-504.3.3.el6.x86_64.

Regards,
Yannis

**Comment by udondan** [comment]
@bcoca 

> that said, there was a bug in 1.9.0.1 that prevented it from working when calling a role:
> 
> roles: {role: rolename, sudo: true}

Probably the same counts for dependencies? At least that's my current problem. I tried to install other versions to test, but none of them work, failing with following errors when calling ansible-playbook:

Current devel / v1.9.1-0.2.rc2 / v1.9.1-0.3.rc3:

```
Traceback (most recent call last):
  File "/tmp/ansible/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/tmp/ansible/bin/ansible-playbook", line 101, in main
    default=C.DEFAULT_FORCE_HANDLERS, action='store_true',
AttributeError: 'module' object has no attribute 'DEFAULT_FORCE_HANDLERS'
```

v1.9.0-1 / v1.9.0-2 / v1.9.1-0.1.rc1:

```
Usage: ansible-playbook playbook.yml

ansible-playbook: error: no such option: --extra-vars
```

**Comment by bcoca** [comment]
@udondan your installation seems to be messed up

**Comment by udondan** [comment]
My installation is that i checked out the corresponding git tag to /tmp. This is how I tested the devel branch previously. Ain't that right?

Calling my playbook then with an absolute path to ansible-playbook:

```
/tmp/ansible/bin/ansible-playbook -i inventory/some setup.yml --extra-vars "hostgroup=staging"
```

**Comment by bcoca** [comment]
i just did same and I don't have those issues

**Comment by kyriesent** [comment]
@udondan I don't know if you're still getting `AttributeError: 'module' object has no attribute 'DEFAULT_FORCE_HANDLERS'` but I just ran into it today.

I had to run this:

```
sudo rm -rf /usr/local/lib/python2.7/dist-packages/ansible-1.9-py2.7.egg/
```

`ansible-playbook` was importing an outdated module from that python directory instead of the one in the source directory, which was causing the error. Your fix might be different based on if/where you had ansible previously installed.

Hope that helps.

All the best :+1:

**Comment by bcoca** [comment]
I'm gong to close this issue as i was unable to make sudo work from a vars file going back several versions. Also, we never meant to  do so and it is not a feature we plan to support (we already do in inventory vars, and the play itself). The rest of the issues here seem installation related and not apropos the original ticket.

**Comment by udondan** [comment]
@kyriesent Thanks, yes, it was the same (or a very similar) problem in my setup. I previously installed Ansible via brew. Even though I deleted it with brew, some files in `/usr/local/lib` survived and had to be removed manually.
