### ISSUE TITLE
get_mount_facts does not work without lsblk

### ISSUE THREAD

**Issue by rosowiecki** [ansible/ansible#10746]
Gathering facts doesn't work without lsblk utility; ansible fails with message:

failed: [somehost] => {"cmd": "None -ln --output UUID /dev/sdb12", "failed": true, "rc": 257}

**Comment by bcoca** [comment]
test the PR linked above and confirm that this fixes your issue

**Comment by rosowiecki** [comment]
ansible 1.9.0.1

I haven't tested your patch: first I've tried to workaround this issue by providing fake lsblk (ln -s /bin/true /bin/lsblk) and it seems cause of my recent problems is not here.

failed: [japanH4-SN0102] => {"cmd": "/bin/lsblk -ln --output UUID /dev/sdb12", "failed": true, "rc": 257}
msg: Traceback (most recent call last):
  File "<stdin>", line 1650, in run_command
  File "/usr/lib64/python2.4/subprocess.py", line 550, in **init**
    errread, errwrite)
  File "/usr/lib64/python2.4/subprocess.py", line 988, in _execute_child
    data = os.read(errpipe_read, 1048576) # Exceptions limited to 1 MB
  File "<stdin>", line 1796, in _handle_timeout
TimeoutError: Timer expired

What timer expires here, roughly around UUID facts gathering?

**Comment by bcoca** [comment]
most fact gathering has a timer attached in case queries get 'stuck'

**Comment by rosowiecki** [comment]
Is there a way to increase this timer? I've got timeout=60 in my ansible.cfg but it seems to be only ssh connection timeout, becuse my fact gathering fails about 10 seconds.

**Comment by bcoca** [comment]
its hardcoded into the method

 @timeout(10)

more than 10s trying to get block data is too much.

## 

Brian Coca

**Comment by rosowiecki** [comment]
After manual increase of get_mount_facts timeout to 60: it passed (needed about 15 seconds to complete ;)

What's most strange: get_mount_facfs is called wit try... except: TimeoutError but it fails anyway! How is it possible? Is it because this exception is raised in decorator code?
