### ISSUE TITLE
how ansible_env.PATH is set in SSH session?

### ISSUE THREAD

**Issue by esazhin** [ansible/ansible#10752]
I hope this is OK to ask this question here:
I'm having problems with some hosts running ansible: it complains that there is no simplejson module found. I figured that it is something to do with the way ansible_env.PATH is set as somehow it picks up a very old version of python and i can't figure out where it comes from. I posted the question on stackoverflow and found other people asking the same thing - but there is still no definitive answer.
I would like to know how this variable is getting set and how i can affect it to make sure that the right version of python is used on the host?
http://stackoverflow.com/questions/29289472/ansible-how-ansible-env-path-is-set-in-ssh-session
http://grokbase.com/t/gg/ansible-project/1479n0d0qp/ansible-env-path-how-is-it-set

thanks a lot!

**Comment by sivel** [comment]
I believe you are chasing the wrong rabbit down the wrong hole.

Take a look at http://docs.ansible.com/faq.html#how-do-i-handle-python-pathing-not-having-a-python-2-x-in-usr-bin-python-on-a-remote-machine

You will need to set `ansible_python_interpreter` via inventory or similar to specify the location of your correct python binary.

**Comment by esazhin** [comment]
very well may be;) I know about the ansible_python_interpreter and it does resolve the simplejson problem, so I'm covered on that aspect. 
I think I now understand that if i need the PATH on the target host to be changed i can use the environment:PATH to change that for the Play or use absolute paths to commands (especially shell ones)
just got a bit confused here;) 
This probably can be closed - thank you!

**Comment by bcoca** [comment]
closing as per discussion above
