### ISSUE TITLE
regex_replace breaks on variable subsitition

### ISSUE THREAD

**Issue by maquis196** [ansible/ansible#10751]
Basically I'm setting zookeeper ID via the number in the hostname but due to an earlier mis-name I need to be able to override this.

However, as my little playbook shows, this doesn't work as a variable.

```
- hosts: localhost
  gather_facts: no
  vars:
   regex_sub: "{{ 'eu-events-p06' | regex_replace('^[a-z].*0(.*)$', '\\1') }}"
  tasks: 
     - debug: msg="{{ 'eu-events-p06' | regex_replace('^[a-z].*0(.*)$', '\\1') }}"
     - debug: msg="{{ regex_sub }}"
```

Sorry if this is a dupe, I can't seem to find another bug like this. For the record I'm on Ansible 1.9.0.1, this is also broken in last 1.7 release.

Cheers,
Chris

**Comment by maquis196** [comment]
Whoops, the output I got was;

```
PLAY [localhost] ************************************************************** 

TASK: [debug msg="6"] ********************************************************* 

ok: [localhost] => {
    "msg": "6"
}

TASK: [debug msg="{{ regex_sub }}"] ******************************************* 

ok: [localhost] => {
    "msg": "\u0001"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by sivel** [comment]
Take a look at https://github.com/ansible/ansible/issues/10067#issuecomment-72732873

I imagine that comment should clear things up

**Comment by bcoca** [comment]
closing this as we already have other bugs that point to this issue, which I've made note to solve by updating the documentation
