### ISSUE TITLE
Feature request: detect Solaris OpenCSW python packages

### ISSUE THREAD

**Issue by erikbrowning** [ansible/ansible#10756]
My organization uses solaris in a few places and on those machines we install packages from OpenCSW. When python is installed it gets installed to "/opt/csw/bin/python", and not "/usr/bin/python"

To work around this we will set the ansible_python_interpreter thusly:

ansible_python_interpreter: "/opt/csw/bin/python"

This works but is rather inelegant, especially when there are groups that contain a mix of solaris and linux machines (we're in a period of transition). Ansible can't connect and determine the OS without finding python, so we can't have it use one or the other dynamically.

So... can ansible try to /usr/bin/python and, if not found, try /opt/csw/bin/python instead?

**Comment by sivel** [comment]
Is `/opt/csw/bin/` in your `PATH`?  If so the following configuration may work:

```
ansible_python_interpreter: "/usr/bin/env python"
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
