### ISSUE TITLE
AnsibleModule.fail_json() send error message to stdout make it invisible on the CLI

### ISSUE THREAD

**Issue by romain-dartigues** [ansible/ansible#10764]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 2.0.0 (devel f4172fb9da) last updated 2015/04/18 19:42:59 (GMT +200)
  lib/ansible/modules/core: (detached HEAD a19fa6ba48) last updated 2015/04/18 19:43:07 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD df7fcc90d9) last updated 2015/04/18 19:43:15 (GMT +200)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/04/18 19:43:24 (GMT +200)
  v2/ansible/modules/extras: (detached HEAD df7fcc90d9) last updated 2015/04/18 19:43:35 (GMT +200)
  configured module search path = None
```
##### Environment:

Irrevelant (Slackware GNU/Linux).
##### Summary:

Error message is not shown by [InventoryScript()](https://github.com/ansible/ansible/blob/c3d34a538613eea3d6db03a700211887f697b443/lib/ansible/inventory/script.py#L48) when generated by [AnsibleModule.fail_json()](https://github.com/ansible/ansible/blob/faadb6830899138de2dfcfca3973a898c5ace3a2/lib/ansible/module_utils/basic.py#L1242) because the latter output it to `stdout` and the former expect the error string to be found on `stderr`.
##### Steps To Reproduce:

``` sh-session
$ ln -s /path/to/ansible/modules/core/cloud/digital_ocean/digital_ocean.py
$ ansible -m ping -u root -i digital_ocean.py all
ERROR: Inventory script (digital_ocean.py) had an execution error:
```
##### Expected Results:

``` sh-session
$ ansible -m ping -u root -i digital_ocean.py all
ERROR: Inventory script (digital_ocean.py) had an execution error: {"msg": "this module requires key=value arguments (['<<INCLUDE_ANSIBLE_MODULE_ARGS>>'])", "failed": true}
```
##### Actual Results:

(see steps)

**Comment by sivel** [comment]
Your issue stems from something completely different, in that `/path/to/ansible/modules/core/cloud/digital_ocean/digital_ocean.py` is not the digital ocean inventory script.

That file you reference is the digital ocean module as documented at http://docs.ansible.com/digital_ocean_module.html

The inventory scripts are not shipped with the ansible release, and only exist within the git repository at https://github.com/ansible/ansible/tree/devel/plugins/inventory

You will need to manually download the inventory plugin.

As such, I believe this issue and the associated pull request to be invalid.

**Comment by romain-dartigues** [comment]
Hi sivel,

i know (afterhand) that the script i used is not the one it was supposed to be, but the error generated by fail_json() is still sent to stdout, which is not, i belive, the right place to be.

**Comment by sivel** [comment]
Changing that may prevent Ansible from being able to grab the result from the module.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

So you seem to have tried using a task module as an inventory script, as @sivel comments above the solution is actually using the correct inventory script. fail_json is meant for modules and captured by ansible-playbook/ansible and should not be used in inventory scripts.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by romain-dartigues** [comment]
Indeed it was a misunderstanding, after a night of sleep i understood Ansible was expecting to get the command result from stdout, even if it was an error.

Sorry for my initial obstinacy.

Regards.
