### ISSUE TITLE
ternary() filter does not appear to work as documented

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#10763]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 2.0.0 (devel f4172fb9da) last updated 2015/04/18 09:55:10 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 2970b339eb) last updated 2014/11/06 13:57:19 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD ad181b7aa9) last updated 2014/11/06 13:57:33 (GMT +100)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/11/06 13:57:45 (GMT +100)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/11/06 13:57:58 (GMT +100)
  configured module search path = None
```
##### Environment:

OSX 10.9.5
##### Summary:

The ternary() filter does not appear to work as [documented](http://docs.ansible.com/playbooks_filters.html#other-useful-filters)
##### Steps To Reproduce:

Use this playbook:

```
- hosts: localhost
  vars:
    foo: "{{ ansible_os_family == 'Debian' | ternary('Mr','Ms') }}"
  tasks:
    - set_fact: bar="{{ ansible_os_family == 'Debian' | ternary('Mr','Ms') }}"
    - debug: var=foo
    - debug: var=bar
```
##### Expected Results:

That the variables foo and bar would be set to either "Mr" or "Mrs". Instead they are set to the string "False"
##### Actual Results:

```
TASK: [set_fact bar="{{ ansible_os_family == "Debian" | ternary('Mr','Ms') }}"] ***
ok: [localhost]

TASK: [debug var=foo] *********************************************************
ok: [localhost] => {
    "var": {
        "foo": "False"
    }
}

TASK: [debug var=bar] *********************************************************
ok: [localhost] => {
    "var": {
        "bar": "False"
    }
}
```

**Comment by MrMMorris** [comment]
Yes! I was running into this too:

``` yaml
- docker:
    image: "company/tv-server:{{ item }}-latest"
    links:
      - "{{ 'production' in node_envs | ternary('foo' + item, omit) }}"
  with_items: node_envs
```

`msg: Docker API Error: Could not get container for True`

**Comment by sivel** [comment]
Take a look at https://github.com/ansible/ansible/pull/10767

I've submitted a pull request to update the docs.

@candlerb, what you need is: `"{{ (ansible_os_family == 'Debian') | ternary('Mr','Ms') }}"` to apply the `ternary` filter to the evaluation instead of just the string `'Debian'`.

The addition is the `()` around the evaluation of `ansible_os_family == 'Debian'`

**Comment by candlerb** [comment]
That works, thank you.

I found there is an [open bug](https://github.com/mitsuhiko/jinja2/issues/379) on jinja2 for not documenting operator precedence. I believe that it implicitly uses the same operator precedences as python, which would be reasonable, except that jinja2 uses the pipe operator for applying filters to expressions, not bitwise-OR of its operands.
