### ISSUE TITLE
Mocking ansible in python 3?

### ISSUE THREAD

**Issue by weldpua2008** [ansible/ansible#10771]
Hello,
I read [why not to upgrade to Python 3? #1409]https://github.com/ansible/ansible/issues/1409).
I want write code as python 3-compitable. But when I use my code and try to see python 3.x problem's I see:

``` python
Traceback (most recent call last):
  File "test_repository.py", line 19, in <module>
    from api.repository.repository import Repository
  File "/home.local/valerys/rde_1_3/rdepyui/tests/../api/repository/repository.py", line 2, in <module>
    import ansible.runner
  File "/usr/local/lib/python3.4/dist-packages/ansible/runner/__init__.py", line 402
    except errors.AnsibleError, e:
                              ^
SyntaxError: invalid syntax
```

Maybe there is project to move ansible on python 3? or some mock object? that I can use instead of ansible object?

Regards.

**Comment by mscherer** [comment]
The work to port ansible to python 3 is made on the v2 engine. See http://fr.slideshare.net/jimi-c/whats-new-in-v2-ansiblefest-london-2015 slide 22 for how to use it and the rest to see what was changed.

The python 3 port is also using six as a library to achieve compatibility with both python 2 and 3, for the rest, as you started a discussion on the list, could you please close this bug ?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
