### ISSUE TITLE
Uniform access on complex variables

### ISSUE THREAD

**Issue by ThomasSteinbach** [ansible/ansible#10775]
I used to define variables in the following way:

```

---
mysql:
  config:
    bind_address: 127.0.0.1
  root:
    password: ''
    remote_access: absent
```

This style of writing is appealing to read and non repititive. Inside the artifacts of the role I can reference such variables like `{{ mysql.root.password }}`. However I am not able to override those variables by referencing them the same way from other roles, playbooks or the console. It took me some hours to find out, that the access of complex variables is not conform all over Ansible, which mades me working with Ansible more difficult. Currently I define my variables the following way:

```
mysql_config_bindAddress: 127.0.0.1
mysql_root_password: ''
mysql_root_remoteAccess: absent
```

But this style is not as readable as the one from above and you have to repeat the whole thought path for every variable.

Is it worth to think about making the variable access to the upper variable definition uniform all over Ansible? Not just because of the better variable definition style but also because of the more intuitive usage of Ansible.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

You should look at ansible.cfg, specifically at the hash_behaviour setting which would allow you to use the first form and merge (default is replace) with variables defined in other places.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
