### ISSUE TITLE
Lookup module occansionally fails with `cannot create the path for the password lookup: <directory> (error was [Errno 17] File exists: '<directory>')`

### ISSUE THREAD

**Issue by wjam** [ansible/ansible#10784]
## Issue Type

Bug Report
## Ansible Version

1.9.1 rc1
## Environment

[Ansible run from a docker container](https://github.com/generiklimited/ansible-docker) to manage Ubuntu 14.04.
## Summary:

The `lookup` module can occasionally fail when running against multiple hosts. The message received is `fatal: [<IP ADDRESS>] => cannot create the path for the password lookup: <DIRECTORY> (error was [Errno 17] File exists: '<DIRECTORY>')`.

I believe the issue is that [this line](https://github.com/ansible/ansible/blob/5dce745868720379f69c7b307a3addeafbea66e3/v2/ansible/plugins/lookup/password.py#L105) needs to check to see if the error was that the directory already exists.
## Steps To Reproduce:

Note that this issue is occurring within a sizeable Ansible code base, so the exact details might not be correct.
1. Add a variable in vars which gets its value from the `lookup` module (e.g. `mysql_password: "{{ lookup('password', 'credentials/service/mysqlpassword') }}"`)
2. Create a playbook which targets multiple hosts which uses the new variable 
3. Run a number of times, making sure to remove the created file before each run.
## Expected Results:

Password file is created at the correct location and the value stored within it is used on all of the hosts.
## Actual Results:

The `lookup` module will occasionally throw an error complaining that the directory the password file should be created in already exists.

**Comment by bcoca** [comment]
this looks like a race condition on the multiprocessing side, 2 threads check if the file exists (it doesn't) and then both try to create it, the first one succeeding and the 2nd one failing. We might need to add a preemptive lock here.

**Comment by bcoca** [comment]
fixed via #11127
