### ISSUE TITLE
Bitwise Operator in Ansible 

### ISSUE THREAD

**Issue by rahulinux** [ansible/ansible#10782]
I'm having requirement where to launch ec2 instances in multiple available zones. 

Here what I've tried 

```
     - name: Launching {{ Server }} Instances
       ec2:
         key_name: "{{  key_name }}"
         instance_type: "{{ type }}"
         instance_tags:
              Name: "{{ Server }}"
              Env: "{{ Env }}"
         image: "{{ image_id }}"
         wait: yes
         group_id: "{{ group_id }}"
         count: 1
         count_tag:
              Name: "{{ Server }}"
              Env: "{{ Env }}"
         vpc_subnet_id: vpc_subnet_id[{{ 1 & item }}]
         region: "{{ region }}"
         assign_public_ip: no
         zone: zone[{{ 1 & item}}]
       register: ec2
       with_sequence: start=1 end={{ count }}
```

So I've two items in zone list and vpc subnet list, it should use random item from two list by expanding `1 & {{ item }}` but it's help

Error : 

```
fatal: [localhost] => template error while templating string: unexpected char u'&' at 10
```

Could you please suggest/advice on the same.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by rahulinux** [comment]
I have found the solution : 

```
vpc_subnet_id: "{{ vpc_subnet_id[ (1).__and__(item|int) ] }}"
```
