### ISSUE TITLE
 Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-tmp-1429541305.27-40930732276629 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1429541305.27-40930732276629 && echo $HOME/.ansible/tmp/ansible-tmp-1429541305.27-40930732276629, exited with result 127

### ISSUE THREAD

**Issue by RaviKKK** [ansible/ansible#10783]
I am getting above issue when I ran playbook .

How to resolve this error ?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by RaviKKK** [comment]
my remote node doesn't have python and using raw module to execute the command
