### ISSUE TITLE
set_fact does not work with with_items

### ISSUE THREAD

**Issue by flisky** [ansible/ansible#10796]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.0.1
##### Environment:

N/A
##### Summary:

`set_fact` doesn't update VAR_CACHE every times with `with_items`
##### Steps To Reproduce:

```

---
- hosts: all
  gather_facts: false
  tasks:
    - set_fact: var={{ item }}
      when: item != inventory_hostname and var is undefined
      with_items:
        - 127.0.0.1
        - 127.0.0.2
        - 127.0.0.3

    - debug: var={{ var }}
```

`ansible-playbook -i "127.0.0.1," test.yml`
##### Expected Results:

```
PLAY [all] ******************************************************************** 

TASK: [set_fact var={{ item }}] *********************************************** 
skipping: [127.0.0.1] => (item=127.0.0.1)
ok: [127.0.0.1] => (item=127.0.0.2)

TASK: [debug var={{ var }}] *************************************************** 
ok: [127.0.0.1] => {
    "127.0.0.2": "127.0.0.2"
}

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

```
PLAY [all] ******************************************************************** 

TASK: [set_fact var={{ item }}] *********************************************** 
skipping: [127.0.0.1] => (item=127.0.0.1)
ok: [127.0.0.1] => (item=127.0.0.2)
ok: [127.0.0.1] => (item=127.0.0.3)

TASK: [debug var={{ var }}] *************************************************** 
ok: [127.0.0.1] => {
    "127.0.0.3": "127.0.0.3"
}

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

This works as i would expect it to, you set the same var in the loop so it should hold the last value it was set to.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by flisky** [comment]
Okay, thank you for the input.

Maybe I would do it in a jinja way (2.8, currently under dev): 
`{{ items|reject("equalto", inventory_hostname)|first }}`
