### ISSUE TITLE
Ansible install or upgrade issue

### ISSUE THREAD

**Issue by kmonticolo** [ansible/ansible#10797]
Hi, there
I used ansible-1.6.7 with success, but when I upgrade or uninstall and install again using pip: pip install ansible --upgrade and run ansible-playbook, I got error that no module named ansible.playbook:

$ ansible-playbook  
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 44, in <module>
    import ansible.playbook
ImportError: No module named ansible.playbook

[root@kmonticolo ~]# pip install ansible 
Downloading/unpacking ansible
  Downloading ansible-1.9.0.1.tar.gz (916Kb): 916Kb downloaded
  Running setup.py egg_info for package ansible

```
no previously-included directories found matching 'v2'
no previously-included directories found matching 'docsite'
no previously-included directories found matching 'ticket_stubs'
no previously-included directories found matching 'packaging'
no previously-included directories found matching 'test'
no previously-included directories found matching 'hacking'
no previously-included directories found matching 'lib/ansible/modules/core/.git'
no previously-included directories found matching 'lib/ansible/modules/extras/.git'
```

Requirement already satisfied (use --upgrade to upgrade): paramiko in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.6 in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): ecdsa>=0.11 in /usr/local/lib/python2.7/site-packages (from paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/local/lib/python2.7/site-packages (from jinja2->ansible)
Installing collected packages: ansible
  Running setup.py install for ansible
    changing mode of build/scripts-2.7/ansible from 600 to 755
    changing mode of build/scripts-2.7/ansible-playbook from 600 to 755
    changing mode of build/scripts-2.7/ansible-pull from 600 to 755
    changing mode of build/scripts-2.7/ansible-doc from 600 to 755
    changing mode of build/scripts-2.7/ansible-galaxy from 600 to 755
    changing mode of build/scripts-2.7/ansible-vault from 600 to 755

```
no previously-included directories found matching 'v2'
no previously-included directories found matching 'docsite'
no previously-included directories found matching 'ticket_stubs'
no previously-included directories found matching 'test'
no previously-included directories found matching 'hacking'
no previously-included directories found matching 'lib/ansible/modules/core/.git'
no previously-included directories found matching 'lib/ansible/modules/extras/.git'
changing mode of /usr/local/bin/ansible to 755
changing mode of /usr/local/bin/ansible-playbook to 755
changing mode of /usr/local/bin/ansible-pull to 755
changing mode of /usr/local/bin/ansible-doc to 755
changing mode of /usr/local/bin/ansible-galaxy to 755
changing mode of /usr/local/bin/ansible-vault to 755
```

Successfully installed ansible
Cleaning up...
[root@kmonticolo ~]# uname -a
OpenBSD kmonticolo 5.6 GENERIC.MP#0 i386

And now as newly created user i've got this:

[root@kmonticolo ~]# useradd -m test
[root@kmonticolo ~]# su - test
$ ansible-playbook  
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 44, in <module>
    import ansible.playbook
ImportError: No module named ansible.playbook
$

**Comment by bcoca** [comment]
you need to remove the previous version as it seems to still be there and causing conflicts

**Comment by kmonticolo** [comment]
Solved, premissions were not sufficient enough for a nonroot user.
