### ISSUE TITLE
mysql_* modules should offer a my.cnf path parameter

### ISSUE THREAD

**Issue by drzraf** [ansible/ansible#10795]
That'd allow easy indempotence for distributions where a default and secure system user exists.
This is the case on Debian where the autogenerated file _/etc/mysql/debian.cnf_ contains all the
necessary credentials for maintenance tasks.
One could set/reset it's root password and uses _/etc/mysql/debian.cnf_ for Ansible related tasks.

**Comment by muffl0n** [comment]
I already created a PR for that. See ansible/ansible-modules-core#63

**Comment by jimi-c** [comment]
Following up on old issues, and the above PR was merged so I'll close this now.

Thanks!
