### ISSUE TITLE
better output on undefined variable for assert

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#10790]
Issue Type: Bug Report

Ansible Version:

ansible-playbook 2.0.0 (devel 3db5d8199d) last updated 2015/04/20 14:33:31 (GMT -400)
  lib/ansible/modules/core: (detached HEAD a19fa6ba48) last updated 2015/04/20 14:37:19 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD df7fcc90d9) last updated 2015/04/20 14:37:23 (GMT -400)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/04/20 14:37:28 (GMT -400)
  v2/ansible/modules/extras: (detached HEAD df7fcc90d9) last updated 2015/04/20 14:37:32 (GMT -400)
  configured module search path = None

Environment: OS X control host.  Target host N/A.

Summary: The 'Assert' module does not resolve variables in Jinja.

Steps To Reproduce:

Run the following Playbook: 

```

---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    - instance_vpc_tag_value: "{{ vpc_tag_value }}"
  tasks:
      - assert:
        that:
          - instance_vpc_tag_value is defined
        msg: Required parameters missing.

        - debug: msg="{{instance_vpc_tag_value}}"
```

Expected Results:  The assertion should fail as `vpc_tag_value` has not been set and return the msg defined in the task.

Actual Results:  The variable is not looked up during the `assert` and does not fail to resolve until it is called in the debug module:

```
PLAY [localhost] **************************************************************

TASK: [assert ] ***************************************************************
ok: [localhost]

TASK: [debug msg="{{instance_vpc_tag_value}}"] ********************************
fatal: [localhost] => One or more undefined variables: 'vpc_tag_value' is undefined

FATAL: all hosts have already failed -- aborting
```

**Comment by sivel** [comment]
To me it seems like this is working as expected.

You are checking if the `instance_vpc_tag_value` is defined, which it is, however it is assigned to a variable that is undefined.  You aren't testing the value with an `is defined` you are testing whether jinja2 knows of the variable itself.

If you change the assert to:

```
      - assert:
        that:
          - instance_vpc_tag_value
```

Then the assert fails, although it fails with a wonderful uncaught UndefinedError exception.

**Comment by ghost** [comment]
Ah, I can live with that behavior.  I'll close this to prevent others from spending time reading the bug report.  Thanks @sivel.

**Comment by sivel** [comment]
It might be worth fixing that traceback though.  I'd leave the ticket open for now..  Just my 2 cents, for what they are worth :)

**Comment by ghost** [comment]
Yeah, that's fair.  If anyone wants, I can create a new GH issue for "exception on undefined variable for assert module should return a prettier error."  I'd imagine the output looking like the truthiness check ("One or more undefined variables...").

**Comment by jimi-c** [comment]
Following up on older issues, and it looks like since 2.0 we handle the error for bare variables much better:
<pre>
TASK [assert] *****************************************************************************************************************************************************************************************************
task path: /home/jamesc/testing/10790.yml:4
fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "The conditional check 'instance_vpc_tag_value' failed. The error was: error while evaluating conditional (instance_vpc_tag_value): 'instance_vpc_tag_value' is undefined"
}
</pre>
As such, I'll go ahead and close this now.

Thanks!
