### ISSUE TITLE
Got error 8 when ask_pass = true

### ISSUE THREAD

**Issue by pdostal** [ansible/ansible#10803]
Hi all,

firt of all, thanks for Ansible - I love them !

But I probably found something confusing: When I set `ask_pass = true` in `ansible.cfg` I get:
`{'msg': 'FAILED: [Errno 8] nodename nor servname provided, or not known', 'failed': True}`
I'm running `Ansible 1.9` on `OS X 10.10.3` against fresh `Debian 7.0 x64` server.

I tried a lots of options but it still doesn't work so it'll be probably a bug :cry:

**Comment by rpoojary** [comment]
Is there any update on this issue ???

**Comment by bcoca** [comment]
i have not been able to reproduce this on 1.9.1, can you test it there?

**Comment by pdostal** [comment]
I successfully installed version `2.0.0` and it's still the same:

```
~/server/sudo • • cat ansible.cfg
[defaults]
remote_user = root
ask_pass = true
~/server/sudo • cat hosts
[all]
sorrel
~/server/sudo • ssh root@sorrel uname -a
root@sorrel.pdostal.cz's password:
Linux sorrel 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux
~/server/sudo • ansible-playbook -i hosts main.yml -vvvv
SSH password:

PLAY [sudo] *******************************************************************

GATHERING FACTS ***************************************************************
<sorrel> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO sorrel
fatal: [sorrel] => {'msg': 'FAILED: [Errno 8] nodename nor servname provided, or not known', 'failed': True}

TASK: [Install sudo] **********************************************************
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/pavel/main.retry

sorrel                     : ok=0    changed=0    unreachable=1    failed=0
~/server/sudo •
```

**Comment by JMStudiosJoe** [comment]
I am having same issue with: ansible -m ping all -i hosts.ini -k
dbserver2 | FAILED => FAILED: [Errno 8] nodename nor servname provided, or not known
server1.example.com | FAILED => FAILED: [Errno 8] nodename nor servname provided, or not known
dbserver1 | FAILED => FAILED: [Errno 8] nodename nor servname provided, or not known
server2.example.com | FAILED => FAILED: [Errno 8] nodename nor servname provided, or not known
webserver1 | FAILED => FAILED: [Errno 8] nodename nor servname provided, or not known
webserver2 | FAILED => FAILED: [Errno 8] nodename nor servname provided, or not known
webserver3 | FAILED => FAILED: [Errno 8] nodename nor servname provided, or not known

if I use -vvvv

<webserver2> ESTABLISH CONNECTION FOR USER: josephrichardson on PORT 22 TO webserver2
webserver2 | FAILED => FAILED: [Errno 8] nodename nor servname provided, or not known
<server1.example.com> ESTABLISH CONNECTION FOR USER: josephrichardson on PORT 22 TO server1.example.com
server1.example.com | FAILED => FAILED: [Errno 8] nodename nor servname provided, or not known
<server2.example.com> ESTABLISH CONNECTION FOR USER: josephrichardson on PORT 22 TO server2.example.com
server2.example.com | FAILED => FAILED: [Errno 8] nodename nor servname provided, or not known
<webserver3> ESTABLISH CONNECTION FOR USER: josephrichardson on PORT 22 TO webserver3
webserver3 | FAILED => FAILED: [Errno 8] nodename nor servname provided, or not known
<dbserver1> ESTABLISH CONNECTION FOR USER: josephrichardson on PORT 22 TO dbserver1
<webserver1> ESTABLISH CONNECTION FOR USER: josephrichardson on PORT 22 TO webserver1
dbserver1 | FAILED => FAILED: [Errno 8] nodename nor servname provided, or not known
webserver1 | FAILED => FAILED: [Errno 8] nodename nor servname provided, or not known
<dbserver2> ESTABLISH CONNECTION FOR USER: josephrichardson on PORT 22 TO dbserver2
dbserver2 | FAILED => FAILED: [Errno 8] nodename nor servname provided, or not known

**Comment by bcoca** [comment]
so this is an error from ssh when it cannot resolve the hostname

**Comment by JMStudiosJoe** [comment]
Any idea how to fix it?

**Comment by bcoca** [comment]
yes, but this is not an ansible issue at this point, it is either dns or lack of access

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by lhoss** [comment]
Definitely seems a bug, as initially posted:
I got the same issue (with ansible 2.0.2 on Mac-OS-X 10.9.5), when targeting a host configured (only) in .ssh/config  (not in DNS or /etc/hosts):
`ansible-playbook deploy-users.yml -i ~/hosts  --sudo  --ask-sudo-pass --ask-pass -u $user -l $host`

but ansible indeed works as usual (with ssh/config), without using "--ask-pass":
`ansible-playbook deploy-users.yml -i ~/hosts  --sudo  -u root -l $host`

**Comment by moltar** [comment]
Confirm this is a bug as well. It gets triggered when you have hostnames defined in `~/.ssh/config` that are not actual valid hostnames (i.e. aliases) and when `--ask-pass` is defined.

**Comment by jessegit** [comment]
Fix/workaround: you'll need to make sure you have `sshpass` installed and define `-c ssh` to ansible.
