### ISSUE TITLE
Unable to connect to ec2-host (errors with permission denied errors) in AWS

### ISSUE THREAD

**Issue by dnraj** [ansible/ansible#10822]
Unable to connect to ec2-host (errors with permission denied errors) in AWS.
1. Have the following entry in inventory file
2. Following command was executed
   ansible -vvv test_ansible --user ansible --private-key=/home/ansible/.ssh/id_rsa -m ping --become-user=ansible

It is trying to connect as ec2-user@ec2_remotehost |FAILED> SSH Error: Permission denied (publickey).
while connecting to ec2_remotehost:22

If this is already fixed, let me know the bug number and I can close this as duplicate.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
