### ISSUE TITLE
SSH ControlPath should not be overridden by default

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#10826]
Ansible overrides the ControlPath directive by default, ignoring what is set in ~/.ssh/config

This means that connections that work with ControlPersist using ControlPath can fail to persist connections under Ansible's ControlPath

This bug only appears when using a very long hostname (or a very long $HOME path) 

```
ControlPath "/home/wthames/.ansible/cp/ansible-ssh-really-quite-long-hostname-goes-here-22-wthames.vqyVXKLvElBLRR83" too long for Unix domain socket
```

Really I would expect Ansible to use the same ControlPath as the underlying ssh configuration.

**Comment by bcoca** [comment]
There are a couple of reasons we are not going to do this, first this is already configurable from ansible.cfg and users can disable if they need to. The other is that ansible needs to control the connection and associated permissions, sometimes, this does not 'play well with others'. To avoid breaking/being broken by other apps by default, ansible uses it's own path.  But if you are sure this won't happen or are fine dealing with the issues, you are able to change this w/o any code updates.

**Comment by ghost** [comment]
I am posting here just to share some resource locations others might find useful:
- [control path ansible configuration](http://docs.ansible.com/ansible/intro_configuration.html#control-path)
- Location of configuration

```
* ANSIBLE_CONFIG (an environment variable)
* ansible.cfg (in the current directory)
* .ansible.cfg (in the home directory)
* /etc/ansible/ansible.cfg
```
