### ISSUE TITLE
Lookup Passwords in Loops Should Not Generate Same Password

### ISSUE THREAD

**Issue by timfaraci** [ansible/ansible#10843]
I believe when generating passwords they should be unique. When generating multiple passwords through a loop it results in the same password. Use cases where you want the same password across multiple entries should be toggled with a flag.

Example:

```
   - name: Create directories with password in the name (This is used for Crush FTP Magic Directory).
     file: path=/home/{{ item.key }}__{{ lookup('password', 'chars=digits') }} mode=0755 state=directory
     with_dict: dict
```

Output of Directories Created:

Dir1__qApDPxfONGEdHQ_F37UX
Dir1__qApDPxfONGEdHQ_F37UX
Dir1__qApDPxfONGEdHQ_F37UX
Dir1__qApDPxfONGEdHQ_F37UX

**Comment by sivel** [comment]
Dup of #10844

**Comment by mscherer** [comment]
I think there is a misunderstanding on what the password lookup does. It work as intended, which is to generate a password and store it in a file, so you can have reproductible lookup. 

What you want would be achieved with pipe lookup and mkpasswd, so I would be inclided to close that bug, since that's not a bug, but a feature of password lookup.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The password lookup is database backed so when calling it with the same info it gives the same result, this allows for predictable retrieval of randomly generated passwords. If you don't want the same password in a loop, give it different inputs (filename), or as suggested above use a different lookup.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
