### ISSUE TITLE
provisioning server side modules

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1085]
seems like it would be crazy easy to have some guest creation server side modules

PXE could probably be done, dare I say it, even without Cobbler

what about VMware?

bring this up in the list a bit once we have a bit of an idea what these may look like

**Comment by dagwieers** [comment]
I am finishing 5 modules useful for provisioning:
- **network_facts**: module to get network facts from DNS and a YAML network-inventory (fqdn, network, netmask, gateway, extras)
- **esx_facts**: module to get facts from a VMware system using vSphere (name, interfaces/mac-addresses, uuid, processor, memory)
- **ilo_facts**: module to get facts from HP iLO (name, interfaces/mac-addresses, uuid, bios-info, hardware info)
- **esx_boot**: module to (pxe/iso) boot a VMware system using vSphere
- **ilo_boot**: module to (pxe/iso/floppy) boot a system using HP iLO

**Comment by mpdehaan** [comment]
That sounds great.

vsphere launching and ilo in particular would be fantastic.

**Comment by jhoekx** [comment]
I have a [virt_boot](https://github.com/jhoekx/ansible-virt-boot) module that's working for my uses, no provisioning, but changing the boot order.

Question: does it make sense to keep it in a separate module (like ilo_boot and esx_boot) or should it be merged in the existing virt module?

**Comment by mpdehaan** [comment]
If anything, we should rename the existing virt module to libvirt, since it
only supports certain module types.   However that would technically break
backward compat, so it should probably go with a small tweak in runner so
that if you say "virt" it will call libvirt for you, so it's mostly just a
documentation change to the end user.

As for merging all the virt modules together, I worry that otherwise it
would get rather long, and the the different modules are likely going to
require different modules.

ilo is definitely not a virt thing, anyway.

**Comment by mpdehaan** [comment]
see ansible-provisioning repo

**Comment by dagwieers** [comment]
This module has move to its own project at: http://github.com/ansible-provisioning/ansible-provisioning

You can find the decision and reasoning for this at: https://groups.google.com/forum/?fromgroups=#!topic/ansible-project/b5iAsqD92rU
