### ISSUE TITLE
Feature Idea: Yum update only if already installed

### ISSUE THREAD

**Issue by bputt** [ansible/ansible#10856]
##### Summary:

I have multiple servers that depending on their purpose contain different packages from the yum repo. Instead of having to run yum update *, I'd prefer to have a list of packages that I mark to be updated. I'd like to be able to run Ansible across all of my servers and be able to update the package BUT only if it's installed. You can assume that I can't specify a list of packages per server/group, it would be a general list.
##### Steps To Reproduce:

-name: Update package if exists
  yum: state=latest name=package_name install=false
##### Expected Results:

if(package_name is installed)
    Yum will update that package
else
    Nothing happens, returns an OK status
##### Actual Results:

n/a

**Comment by bcoca** [comment]
fyi, we are aware of some rpm_facts kind of modules that might be contributed soon that would let you contrast the list of installed packages and allow for this functionality w/o modifying this module

**Comment by bputt** [comment]
I assume rpm_facts will allow me to use logic similar to this?

yum: state=latest name=package_name
when: package_name in rpm_facts

**Comment by bcoca** [comment]
yes, but i was thinking more on using a with_items:

```
with_items: installed_packages|intersection(mypkglist)
```

**Comment by bputt** [comment]
Yes, you're right, it would need to use a with_items statement

**Comment by bcoca** [comment]
you can probably hack the same thing right now with "- shell: rpm -qa"

**Comment by bputt** [comment]
thanks for the tip, I'll play with the response so that I can effectively use

register: yum_install
changed_when: yum_install.stdout.find('XYZ') >= 0

**Comment by razvanphp** [comment]
Can we make this more general, eg. for Debian apt?

I find myself ALWAYS in the position of running specific tasks only if some package is installed.

**Comment by gembin** [comment]
is it possible to have this ?

```
for package in packages
if package installed 
then
     upgrade package
else
     install package
```

**Comment by ironicbadger** [comment]
+1

**Comment by jctanner** [comment]
Hi!

As of April of 2016, we have started using the Ansible Proposal process (https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md) for large feature ideas, such as this.  If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!
