### ISSUE TITLE
How to use pbrun_exe

### ISSUE THREAD

**Issue by wimvandijck** [ansible/ansible#10854]
Hi,

running ansible 2.0.0 from git repo.
I'm very excited to try out the new become feature with powerbroker, but I'm struggling to get it to work with our setup.
I realize this feature is still alpha btw ;)

I read that there is a setting ''pbrun_exe", just like su_exe, but I cannot get it to work.
I would like to try it, since our powerbroker profiles are very strict and pbrun can run very few commands.
However, for installation purposes we can get root elevation, so pbrun su root is allowed.
So I would basically like to run all commands that way.

This works fine for adhoc commands btw, if I use su_exe = pbrun su root, then I can run single commands and even modules.
But for playbooks this doesn't seem to work.

Any pointers on how I can get this to work?

Kind regards,
Wim

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

In any case ansible does not support chaining privilege escalation methods and requires permissive access to run commands as a user http://docs.ansible.com/become.html (read notes)
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
