### ISSUE TITLE
Retrieving current hostname of device being acted upon, from within a Python module?

### ISSUE THREAD

**Issue by lamoni** [ansible/ansible#10850]
In the event of a custom python module requiring connection=local, where is the best injection point for making the hostname currently being acted upon accessible from within a Python module?

As of right now, it does not look like Ansible injects the current hostname into a module, thus the current hostname isn't accessible without using a contrived "host" module argument that gets filled in by a Playbook.

e.g.
Assuming my /etc/ansible/hosts file looks like:
[devices]
router1
router2

ansible all -m "mycustommodule.py" --module-path="/home/lamoni" -connection=local

Some possibilities, assuming I am not just overlooking a way that currently exists to get that hostname:
A. Inject it as a module param in _configure_module (don't like this idea, as we run the risk of collision with actual module args)
B. Resort to having a playbook only for the sake of passing the inventory_hostname through as a module arg
C. Action plugin - I don't like this idea just because it seems like a pretty generic requirement to want the current hostname from within a module

**Comment by lamoni** [comment]
I've submitted PR10851 in reference to this as a possible solution.  In short, I am injecting the conn.host hostname value into module_args (we are already injecting two other values through there ('CHECKMODE', 'NO_LOG'), and I think the current device-under-execution's hostname is a general enough data item that the injection point is suitable.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible-devel on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
