### ISSUE TITLE
Support User-Specified Order of Operations in Host Patterns

### ISSUE THREAD

**Issue by Kurt-von-Laven** [ansible/ansible#10862]
##### Issue Type:

Feature Idea
##### Ansible Version:

devel
##### Environment:

N/A
##### Summary:

Support user-specified order of operations in host patterns. I believe at least some of the relevant code is located in [Inventory._get_hosts()](https://github.com/ansible/ansible/blob/61a30e5f49c14319c43f9321631a7c3f6f8b6554/lib/ansible/inventory/__init__.py#L201).
##### Steps To Reproduce:

```

---
-
  hosts: (a:b):&c
  tasks:
    - debug: msg="Matched hosts that are either in both a and c or in both b and c (or in all three)."

-
  hosts: a:(b:&c)
  tasks:
    - debug: msg="Matched hosts that are either in a or in both b and c (or in all three)."
```
##### Expected Results:

```
PLAY [(a:b):&c] ***************************************************************

GATHERING FACTS ***************************************************************
ok: [matched_hosts_1]

TASK: [debug msg="Matched hosts that are either in both a and c or in both b and c (or in all three)."] ***
ok: [matched_hosts_1] => {
    "msg": "Matched hosts that are either in both a and c or in both b and c (or in all three)."
}

PLAY [a:(b:&c)] ***************************************************************

GATHERING FACTS ***************************************************************
ok: [matched_hosts_2]

TASK: [debug msg="Matched hosts that are either in a or in both b and c (or in all three)."] ***
ok: [matched_hosts_2] => {
    "msg": "Matched hosts that are either in a or in both b and c (or in all three)."
}

PLAY RECAP ********************************************************************
matched_hosts_1                  : ok=2    changed=0    unreachable=0    failed=0
matched_hosts_2                  : ok=2    changed=0    unreachable=0    failed=0
```

Host patterns support parentheses syntax for specifying order of operations.
##### Actual Results:

```
PLAY [(a:b):&c] ***************************************************************
skipping: no hosts matched

PLAY [a:(b:&c)] ***************************************************************
skipping: no hosts matched

PLAY RECAP ********************************************************************
```

This is to be expected since parentheses currently are not supported in host patterns.

**Comment by davedevelopment** [comment]
I'm interested in something like this, my particular use case is to enumerate after an intersect, e.g. `(worker:&production)[0]` - one instance that is both a worker and in production.

**Comment by jnerin** [comment]
Yes, please. My use case similar. Instances tagged as production or testing_env1, testing_env2, etc... and also as frontend, backend, management, etc... and I want to apply something to `(testing_env1:testing_env2:testing_env3):&(frontend:backend)`. All the instances on the environments I listed that are also in either frontend or backend.

**Comment by bcoca** [comment]
closing in favor of #16973
