### ISSUE TITLE
fetch: checkum failing on FreeBSD targets

### ISSUE THREAD

**Issue by tom--** [ansible/ansible#10877]
##### Issue Type:

Bug Report
##### Ansible Version:

Fails with
- ansible 1.9.0.1
- ansible 1.8.4

Does **not** fail with
- ansible 1.8.2
##### Environment:

Control: Mac OS X 10.10.2 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64

Target: FreeBSD 9.3-RELEASE-p10 #0: Tue Feb 24 21:28:03 UTC 2015
##### Summary:

Checksum is failing for any fetch from target to control. 
##### Steps To Reproduce:

```
- fetch:
    src: "/etc/passwd"
    dest: "/tmp/test"
```
##### Expected Results:

No failure.
##### Actual Results:

failed: [int3] => {"checksum": "c7087d1d5228292030790631f9704c917e07923c", "dest": "/tmp/test/int3/etc/passwd", "failed": true, "file": "/etc/passwd", "md5sum": "d7d51960be535e352a9d01592caf0a15", "remote_checksum": "Unmatched", "remote_md5sum": null}

msg: checksum mismatch

**Comment by abadger** [comment]
Works for me with freebsd10.... I'll have to download freebsd9 to test that.  Is there anything custom about your setup?  Custom shell, python, etc?

**Comment by tom--** [comment]
I don't think so.

On the target the shell is `/bin/tcsh` and Python is from ports and recent:

```
Python 2.7.9 (default, Apr  7 2015, 13:29:40)
[GCC 4.2.1 20070831 patched [FreeBSD]] on freebsd9
```

On the control host I have tried from both bash and fish and Python is from Homebrew:

```
Python 2.7.9 (default, Jan  7 2015, 11:50:42)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
```

I don't believe either machine has a weird Python environment but I'm not a Python expert.

I have tested now with Ansible 1.9.1 and the pathology persists.

**Comment by abadger** [comment]
Looks like tcsh may be the culprit.  I was able to replicate your issue on freebsd10 with /bin/tcsh as my shell.  Setting shell to /bin/sh works.  Diagnosing further.

**Comment by tom--** [comment]
tcsh is quite popular among freebsd users.

**Comment by abadger** [comment]
I think that at least currently, this is working as expected and you're supposed to specify `ansible_shell_type=csh` for remote machines that use csh or tcsh.  For instance, this works for me:

`ansible-playbook fetch-test.yml -e 'ansible_shell_type=csh'`

For production, you probably want to specify that inside of your inventory rather than at the command line.  Documentation on ansible_shell_type is here: http://docs.ansible.com/intro_inventory.html#list-of-behavioral-inventory-parameters

**Comment by abadger** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, what is happening is that:
- ansible needs to know whether it is talking to a bourne compatible shell or not to properly format the commands it passes over ssh to the remote machine.  If the remote machine is not bourne compatible (in this case, tcsh) then we need to tell ansible to use alternate rules to format its commands.

We would suggest:
- Setting `ansible_shell_type=csh` in the inventory file for hosts where the remote user uses tcsh as their shell.  Something like:

```
[tcsh]
freebsd09
freebsd10

[tcsh:vars]
ansible_shell_type=csh
```

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
