### ISSUE TITLE
inventory_hostnames lookup does not work with an encrypted vault file

### ISSUE THREAD

**Issue by klynch** [ansible/ansible#10875]
Issue Type:
Bug Report

Ansible Version:
ansible 1.9.1

Environment:
N/A

Summary:
The `inventory_hostnames` lookup does not respect Ansible vaults. Using the two in unison fails with the folllowing error: "A vault password must be specified to decrypt /path/to/vault_file".

Steps To Reproduce:

Create an encrypted vault file and run a task similar to the following:

```
- name: print out all inventory hosts
  debug:
    msg: "This is a hostname: {{ item }}"
  run_once: true
  with_inventory_hostnames: hosts
```

Expected Results:

```
TASK: [print out all inventory hosts] ***************************************** 
ok: [host1] => (item=host1) => {
    "item": "host1", 
    "msg": "This is a hostname: host1"
}
...
```

Actual Results:

```
TASK: [print out all inventory hosts] ***************************************** 
fatal: [ny1-prod6-web001.int.peer1.squarespace.net] => A vault password must be specified to decrypt /opt/ansible/group_vars/spark-manager

FATAL: all hosts have already failed -- aborting
```

**Comment by bcoca** [comment]
closing this in favor of the pr #10876
