### ISSUE TITLE
Add documentation for privilege_escalation/become to ansible.cfg

### ISSUE THREAD

**Issue by nickhammond** [ansible/ansible#10881]
By looking at the example file [here](https://raw.githubusercontent.com/ansible/ansible/devel/examples/ansible.cfg) it looks as though the new group would look similar to this:

```
[privilege_escalation]
become=True
become_method='sudo'
become_user='root'
become_ask_pass=False
```

I can create a pull request to add that section to the docs, just wanted to confirm that will be the correct setup moving forward.

Docs:
- [Become docs](http://docs.ansible.com/become.html)
- [Ansible configuration file docs](http://docs.ansible.com/intro_configuration.html)

**Comment by jctanner** [comment]
Resolved by https://github.com/ansible/ansible/commit/d7fb917fe1af9692cf5197064a53499abe1e59f9
