### ISSUE TITLE
Ansible with Packer, root

### ISSUE THREAD

**Issue by IMikkeI** [ansible/ansible#10888]
I am using Ansible 1.9 and Packer to create and install new package on a Debian VM.

Packer run my playbook, but the installation of the package fail because I am not root.

Can anyone give me an example of a playbook which install a package on a Debian ? (With of course the possibility to be root in order to run apt-get install)

Thanks for any help

**Comment by IMikkeI** [comment]
My actual playbook (which is not ok) is the following (I install fortune for a basic example)

 hosts: all
   user: root

   tasks:
      apt: name=fortune state=installed

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
