### ISSUE TITLE
The documentation for ec2_ami represents the state of Ansible per the devel branch, not stable

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#10894]
The [ec2 ami module](http://docs.ansible.com/ec2_ami_module.html) documentation references 'tags' which only exist as of the devel branch, not 1.9 stable.

Line in [devel](https://github.com/ansible/ansible-modules-core/blob/e971543bd45c0e4b2affa0acf0cfbf7ea1964b1a/cloud/amazon/ec2_ami.py#L260)

Missing in [1.9 stable](https://github.com/ansible/ansible-modules-core/blob/4d27a18743a72e3a447f573ab84e1a1fb652d9cf/cloud/amazon/ec2_ami.py)

This could lead to confusion and unhappy users.

**Comment by bcoca** [comment]
https://github.com/ansible/ansible-modules-core/commit/9028e9d4be8a3dbb96c81a799e18f3adf63d9fd0 it will appear in the docs site on the next push
