### ISSUE TITLE
ask_sudo_pass in ansible.cfg has no effect

### ISSUE THREAD

**Issue by edrozenberg** [ansible/ansible#10891]
Ansible 1.9.1 Mac OSX 10.10

I set in ansible.cfg:

```
ask_sudo_pass = True
```

But when running the playbook it does not ask for a password. At cli **--ask-sudo-pass** works fine.
Also **ask_pass** in the ansible.cfg works as expected.

My ansible.cfg:

```
###########################
# Config file for ansible #
###########################

# NOTES:
# o If [ssh_connection] Pipelining = True then when using “sudo:” operations
#   you must first disable ‘requiretty’ in /etc/sudoers on all managed hosts.

[defaults]
hostfile            = hosts/hosts.ini
remote_user         = root
nocows              = 0
ask_sudo_pass       = True
vault_password_file = ~/.ansible/vault/password.txt

[ssh_connection]
pipelining  = True
```

**Comment by rternosky** [comment]
I see the same issue on Ubuntu 14.04.2, ansible 1.9.1. I was using Ansible 1.5.4 and my tasks ran fine, I upgraded to 1.9.1 and it stopped prompting for my password (for sudo). If I add a "-K" flag to the ansible-playbook command it prompts as it should.

**Comment by bcoca** [comment]
confirmed, this was probably introduced in 1.9 with the become update.
