### ISSUE TITLE
Ansible requires -i and host pattern when local connection is specified

### ISSUE THREAD

**Issue by baughj** [ansible/ansible#10890]
**Issue Type**: Bug Report
**Ansible Version**: 1.9.0.1

**Environment**: OSX Yosemite / Ubuntu 14.04 LTS 

**Summary**

Ansible requires `-i` and host pattern when `-c local` is specified.

Ansible requires an inventory file and a host pattern to be specified even when the connection type is local, which seems odd to me, unless I am completely misunderstanding what is meant by a local connection. The inventory file must exist, but it can also be empty, which implies to me that not specifying it should be supported.

**Steps To Reproduce**

Run Ansible with `-c local`, e.g.

`ansible -c local -m shell -a "ls /tmp >/dev/null`

**Expected Results**

Command would succeed without host pattern or -i flag:

```
[baughj@caputina tmp]$ ansible -c local -m shell -a "ls /tmp >/dev/null"
localhost | success | rc=0 >>
```

**Actual Results**

Ansible requires both `-i` and a host pattern. 

```
[baughj@caputina tmp]$ ansible -c local -m shell -a "ls /tmp >/dev/null" 
Usage: ansible <host-pattern> [options] 
<snip>
[baughj@caputina tmp]$ ansible -c local -m shell -a "ls /tmp >/dev/null" localhost
ERROR: Unable to find an inventory file, specify one with -i ?
[baughj@caputina tmp]$ touch foobar
[baughj@caputina tmp]$ ansible -i foobar -c local -m shell -a "ls /tmp >/dev/null" localhost
localhost | success | rc=0 >>
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
