### ISSUE TITLE
docs do not seem to match allow_duplicates behavior

### ISSUE THREAD

**Issue by usernamenumber** [ansible/ansible#10912]
The [docs](http://docs.ansible.com/playbooks_roles.html#role-dependencies) say: "By default, roles can also only be added as a dependency once - if another role also lists it as a dependency it will not be run again. This behavior can be overridden by adding allow_duplicates: yes to the meta/main.yml file"

We are then shown an example of several related roles: `car`, which calls `wheel` four times as a dependency, which in turn depends on `brake` and `tire`. The example says that if you set `allow_duplicates: yes` in `wheel/meta/main.yml`, it will run `wheel`, `brake`, and `tire` each four times.  

After noticing some behavior that didn't seem to match this, I re-created this example using ansible v1.9.1 on Ubuntu 14, giving each role a simple debug task. 

If I set `allow_duplicates: yes` on `wheel`, I actually see this behavior (in fact, I see this regardless of how `allow_duplicates` is set):

```
$ ansible-playbook -c local -i localhost, car.yml  | grep 'TASK\|skipped'
TASK: [tire | debug msg='tire(n=1)'] ******************************************
TASK: [brake | debug msg='brake(n=1)'] ****************************************
TASK: [wheel | debug msg='wheel(n=1)'] ****************************************
TASK: [wheel | debug msg='wheel(n=2)'] ****************************************
TASK: [wheel | debug msg='wheel(n=3)'] ****************************************
TASK: [wheel | debug msg='wheel(n=4)'] ****************************************
TASK: [car | debug msg='car'] *************************************************
```

However, if I set `allow_duplicates` for _`brake`_, I see the expected behavior for it:

```
$ ansible-playbook -c local -i localhost, car.yml  | grep 'TASK\|skipped'
TASK: [tire | debug msg='tire(n=1)'] ******************************************
TASK: [brake | debug msg='brake(n=1)'] ****************************************
TASK: [wheel | debug msg='wheel(n=1)'] ****************************************
TASK: [brake | debug msg='brake(n=2)'] ****************************************
TASK: [wheel | debug msg='wheel(n=2)'] ****************************************
TASK: [brake | debug msg='brake(n=3)'] ****************************************
TASK: [wheel | debug msg='wheel(n=3)'] ****************************************
TASK: [brake | debug msg='brake(n=4)'] ****************************************
TASK: [wheel | debug msg='wheel(n=4)'] ****************************************
TASK: [car | debug msg='car'] *************************************************
```

Applying `allow_duplicates` to specific roles instead of recursively to all of a role's dependencies, and honoring explicit dependency calls to a role (e.g. `car` calling `wheel`) regardless of that setting, makes more sense to me than what is described in the docs anyway, so I hope that this is just a simple matter of correcting the docs (or me, if I'm misunderstanding something).

**Comment by jimi-c** [comment]
I'm seeing the proper behavior in devel/2.2, so I'm going to go ahead and close this. Sorry for the late follow-up, and thanks!

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
