### ISSUE TITLE
get_url: https with explicit port fails to validate certificate

### ISSUE THREAD

**Issue by telbizov** [ansible/ansible#10924]
The get_url module fails to validate the SSL certificate when the URL contains 'https://' scheme with an explicit port in it. Example: `https://host:4443/path/to/something`

To reproduce run:

```
ansible -i inventory host -m get_url -a 'url="https://host:4443/path/to/something" dest=/usr/local/sbin/something validate_certs=yes owner=root group=root mode=0755'
```

The error is:

```
"Request failed", "response": "An unknown error occurred: an integer is required"
```

The bug is in `urls.py:379`. The port variable is actually left as a string when the port is parsed out of the URL as opposed to being an integer when the port is implicitly set to 443. A simple `port = int(port)` would do I think. The patch below works for me:

```
--- urls.original.py    2015-05-05 16:13:41.000000000 -0700
+++ urls.py 2015-05-05 16:57:51.000000000 -0700
@@ -377,6 +377,7 @@
                 netloc = netloc.split('@', 1)[1]
             if ':' in netloc:
                 hostname, port = netloc.split(':', 1)
+                port = int(port)
             else:
                 hostname = netloc
                 port = 443
```

**Comment by jimi-c** [comment]
Hi @telbizov, could you send this to us in a pull request so you receive credit for the fix? Thanks!

**Comment by telbizov** [comment]
@jimi-c I was just about to do that and I found out that it is actually already fixed in the master branch

https://github.com/ansible/ansible/commit/6e65ccabc3dac26a89cf2b1782ed160327320528#diff-3448ba8582852f79eb0d697763e046d8

I guess @sidick already beat me by a few days ;)
I'd assume this will be out in the next release? I'll close this issue now.
