### ISSUE TITLE
Not able to override chroot path for ansible_connection=chroot?

### ISSUE THREAD

**Issue by tetherit** [ansible/ansible#10921]
I cannot find any documentation for the chroot connection and I have tried asking on #ansible and googling. When I need to override the ssh host, I can do:

``` python
ansible_ssh_host: '{{ ip | default("vpn.%s.%s" % (inventory_hostname, domain)) }}'
```

How would I do the same to override the chroot_path outside of the inventory?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

I believe you can just set the inventory_hostname or ansible_ssh_host to the path
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
