### ISSUE TITLE
Variable from wrong host group is read

### ISSUE THREAD

**Issue by usrenmae** [ansible/ansible#10927]
# Problem

When having the same variable with different values defined for different host groups with group_vars folder separation, wrong group can feed the value to the variable.
# Versions affected
- 1.9.1
- 2.dev
# How to reproduce

``` bash
$ tree
.
├── group_vars
│   ├── a
│   └── b
├── hosts
└── test.yml

$ cat hosts
[a]
localhost ansible_connection=local ansible_sudo=False ansible_gather_facts=False
[b]
localhost ansible_connection=local ansible_sudo=False ansible_gather_facts=False

$ cat group_vars/a

---
aa: from_a

$ cat group_vars/b

---
aa: from_b

$ cat test.yml

---
- hosts: a
  tasks:
    - debug: msg={{aa}}
```

And the result is 

``` bash
$ ansible-playbook -i hosts test.yml

PLAY [a] **********************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [debug msg={{aa}}] ******************************************************
ok: [localhost] => {
    "msg": "from_b"
}

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

Expected result:

```
...
TASK: [debug msg={{aa}}] ******************************************************
ok: [localhost] => {
    "msg": "from_a"
}
...
```

**Comment by srgvg** [comment]
This is expected behaviour. Variables are merged down to the host level. Which group you target in a play doesn't  change that.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

@svg post explains why.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
