### ISSUE TITLE
host variables are not set

### ISSUE THREAD

**Issue by dh-harald** [ansible/ansible#10939]
Hi,

I've a host, and i'm setting a variable in group_vars/all

group_vars/all:
environment: prod

if I run the role playbook, environment variable is empty:

TASK: [role | debug var=environment] ************************************\* 
ok: [server1] => {
    "var": {
        "environment": {}
    }
}

But hostvars is set

TASK: [role | debug var=hostvars[inventory_hostname].environment] *******\* 
ok: [server1] => {
    "var": {
        "hostvars[inventory_hostname].environment": "prod"
    }
}

I'm using ansible version 1.9.1 on arch linux (server1 is CentOS)

**Comment by HitScan** [comment]
This is likely because "environment" is a reserved variable name ([similar to hostvars, groups, and group_names](http://docs.ansible.com/playbooks_variables.html#magic-variables-and-how-to-access-information-about-other-hosts)) It's possible that this has only recently been enforced, though.

**Comment by bcoca** [comment]
has @HitScan mentions environment is a reserved keyword, closing this as this is not expected to work.
