### ISSUE TITLE
Error "invalid selinux context" in template module when using vxfs (veritas cluster) filesystem

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#10931]
Issue Type:
Bug Report

Ansible Version: 
ansible 1.8.2

Environment:
Running from RHEL 6.5
SELinux is running in permissive mode ("logging only")

Summary:
Template modules fail to generate a template file when the destination is on an vxfs filesystem:

msg: invalid selinux context

FATAL: all hosts have already failed -- aborting

Steps To Reproduce:
From the playbook:
-name: Ensure config file for deployment exists
  template:
    src="deploy.cfg"
    dest="/path/on/vxfs/filesystem/deploy.cfg"

The playbook was executed as user root. Setting se\* settings does not help.

Expected Results:
File will be generated with template engine

Actual Results:
myhost> PUT /tmp/tmpKrHpKN TO /root/.ansible/tmp/ansible-tmp-1430919691.46-42912766588713/source
<myhost> PUT /tmp/tmp8p_ATr TO /root/.ansible/tmp/ansible-tmp-1430919691.46-42912766588713/copy
<myhost> EXEC /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1430919691.46-42912766588713/copy; rm -rf /root/.ansible/tmp/ansible-tmp-1430919691.46-42912766588713/ >/dev/null 2>&1'
failed: [myhost] => {"cur_context": ["unconfined_u", "object_r", "vxfs_t", "s0"], "failed": true, "gid": 0, "group": "root", "input_was": ["system_u", "object_r", "default_t", "s0"], "mode": "0644", "new_context": ["system_u", "object_r", "default_t", "s0"], "owner": "root", "path": "/path/on/vxfs/filesystem/.ansible_tmpSWb01kdeploy.cfg", "secontext": "unconfined_u:object_r:vxfs_t:s0", "size": 31559, "state": "file", "uid": 0}
msg: invalid selinux context

FATAL: all hosts have already failed -- aborting

There are also some bugs that this happend in the past on NFS and ZFS Filesystems also:
https://github.com/ansible/ansible/issues/5632
https://github.com/ansible/ansible/issues/7009

Maybe someone can use this code https://github.com/jimi-c/ansible/commit/ed0fcb96390e18711521ecff7714253935f0a239 to fix this issue?

Maybe setting selinux context is not necessary when selinux is in permissive mode.

Another Solution may be using copy instead of move, but I am not sure if this has to be atomic.

**Comment by TristanCacqueray** [comment]
Oh hi! I've reported another similar issue with overlayfs here: #10930.
What's the feasibility to have an option per steps to ignore selinux context errors ?

**Comment by nathanhruby** [comment]
As a METOO, this happens on glusterfs filesystems, and I assume any fs that is network enabled and has a provided mount time context.

For me, switching gluster mount to NFS was an easy solution, but I spent a few hours trying to figure out what may have been going on.

**Comment by bcoca** [comment]
we might need to make this configurable

```
selinux_fs_ignore=nfs,overlayfs,glusterfs,anything fuse?
```

**Comment by bcoca** [comment]
can you supply samples of /proc/mounts of those filesystems on an selinux enabled box? 
nfs currently works because it has it's own context, I supposed these also have one.

**Comment by dmertl** [comment]
I'm having a similar issue when using the template module to copy a file to a Vagrant synced folder. It tries to set a new context type, but cannot (not allowed by Vagrant).

Example playbook + vagrant: https://gist.github.com/dmertl/2ee3480b80081d108f08

**Comment by bcoca** [comment]
what really would help is samples from /proc/mounts (you can obscure the mount points/sources)

**Comment by nathanhruby** [comment]
CentOS 7.1 Machine with Gluster 3.6.3

```
[root@hosty-groupname-i-567dab94.awsusw1.dev ~]# grep glusterfs /proc/mounts
localhost:/hosty_groupname /var/someco/awsusw1.dev/hosty_groupname fuse.glusterfs rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072 0 0
[root@hosty-groupname-i-567dab94.awsusw1.dev ~]# grep glusterfs /etc/fstab
localhost:/hosty_groupname /var/someco/awsusw1.dev/hosty_groupname glusterfs defaults 0 0
[root@hosty-groupname-i-567dab94.awsusw1.dev ~]# cd /var/someco/awsusw1.dev/hosty_groupname
[root@hosty-groupname-i-567dab94.awsusw1.dev hosty_groupname]# echo yhullo > thar
[root@hosty-groupname-i-567dab94.awsusw1.dev hosty_groupname]# ll -lZ thar
-rw-r--r--. root root system_u:object_r:fusefs_t:s0    thar
[root@hosty-groupname-i-567dab94.awsusw1.dev hosty_groupname]#

```

**Comment by bcoca** [comment]
^ try out the linked PR and let me know

**Comment by nathanhruby** [comment]
will do this afternoon

**Comment by dmertl** [comment]
@bcoca I'm using Vagrant with VirtualBox and that uses the 'vboxsf' file system:

```
none /var/www/html vboxsf rw,nodev,relatime 0 0
```

I tested with the change made in your PR, adding `or 'vboxsf' in fstype` and it resolved the problem.

**Comment by bcoca** [comment]
ok, updated patch, made list configurable but by default it does nfs, fuse and vboxfs (wait is it that or vboxsf?)

**Comment by dmertl** [comment]
@bcoca It's "vboxsf" for VirtualBox Shared Folder I believe.

**Comment by bcoca** [comment]
ok redid patch, please test and confirm that it fixes 'all of the above' (or option D)

**Comment by dmertl** [comment]
@bcoca confirmed fixes virtual box shared folders

**Comment by ghost** [comment]
Thanky you for your patch. Nice that this fixes the virtual box stuff, but it does NOT fix my issue with veritas filesystem (vxfs).

I have merged the patch in our version but this does not solve the problem. Same error as before.

I also umcomment the list and added "vxfs" to the list. I also tried to comment out the list and add "vxfs" to the constant list:

DEFAULT_SELINUX_SPECIAL_FS = get_config(p, 'selinux', 'special_context_filesystems', None, 'fuse, nfs, vboxsf, vxfs', islist=True)

But nothing solved that problem.
Here is a cat /proc/mount

root@myhost:~ # cat /proc/mounts | grep vxfs
/dev/vx/dsk/veritasdiskgroup/veritasvolume01 /export/mypath vxfs rw,relatime,mntlock=VCS,delaylog,largefiles,ioerror=mwdisable 0 0

root@myhost:~ # cat /proc/mounts 
rootfs / rootfs rw 0 0
proc /proc proc rw,relatime 0 0
sysfs /sys sysfs rw,seclabel,relatime 0 0
devtmpfs /dev devtmpfs rw,seclabel,relatime,size=264570676k,nr_inodes=66142669,mode=755 0 0
devpts /dev/pts devpts rw,seclabel,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /dev/shm tmpfs rw,seclabel,relatime 0 0
/dev/mapper/vg_root-lv_root / ext4 rw,seclabel,relatime,barrier=1,data=ordered 0 0
none /selinux selinuxfs rw,relatime 0 0
devtmpfs /dev devtmpfs rw,seclabel,relatime,size=264570676k,nr_inodes=66142669,mode=755 0 0
/proc/bus/usb /proc/bus/usb usbfs rw,relatime 0 0
/dev/sda1 /boot ext4 rw,seclabel,relatime,barrier=1,data=ordered 0 0
/dev/mapper/vg_root-lv_opt /export/opt ext4 rw,seclabel,relatime,barrier=1,data=ordered 0 0
/dev/mapper/vg_root-lv_tmp /tmp ext4 rw,seclabel,relatime,barrier=1,data=ordered 0 0
none /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
/etc/auto.misc /misc autofs rw,relatime,fd=6,pgrp=3528,timeout=300,minproto=5,maxproto=5,indirect 0 0
-hosts /net autofs rw,relatime,fd=12,pgrp=3528,timeout=300,minproto=5,maxproto=5,indirect 0 0
none /dev/odm vxodmfs rw,relatime 0 0
sunrpc /var/lib/nfs/rpc_pipefs rpc_pipefs rw,relatime 0 0
/dev/vx/dsk/veritasdiskgroup/veritasvolume01 /export/mypath vxfs rw,relatime,mntlock=VCS,delaylog,largefiles,ioerror=mwdisable 0 0

Is vxfs the wrong string for adding to the list?
Or do I have to add some of se\* variables to my playbook like selevel, serole, setype, seuser?

Please note that selinux is only permissive on my system.

**Comment by dmertl** [comment]
@layer7 The string you add to the config should match what's in your `/proc/mounts`, so "vxfs" looks right.

The patch is skipping the selinux context setting if the path to the file matches a mount point that has a file system defined in `special_context_filesystems`. So if the file is in `/export/mypath`, it should get the special treatment.

**Comment by ghost** [comment]
Thank you for this information.

I am using the path /path/on/vxfs/filesystem/deploy.cfg

where /path/on/vxfs is a symlink which points to /export/mypath.
 So I assume that this patch does not work when using symlinks. Am I right?

Is there any posibility to extend this patch that the path of the file will be analysed and resolved to the real target and then detects that the real target is on such a file system and then skip the selinux contect settings? This shouldn't be a big thing and other people will also use sylinks and will have the same problem.

**Comment by tannerjfco** [comment]
> other people will also use symlinks and will have the same problem.

I have hit exactly that problem. It would be super helpful if possible for this special fs check to work with symlinked paths.

**Comment by ghost** [comment]
@tannerjfco 

I also have still this issue. The Problem is that this bug here is closed and nobody will read was we have written.
Can you please open a new issue and post the issue number here? I want to do that since month but I don't have the time.
