### ISSUE TITLE
ansible_distribution is wrongly reported as 'RedHat' under CentOS 7.1

### ISSUE THREAD

**Issue by vmalloc** [ansible/ansible#10937]

**Comment by mightydok** [comment]
Cant confirm for last devel and stable branch:
[root@localhost ansible]# cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)

[root@localhost ansible]# ansible -ihosts -u ans -k -m setup all -a "filter=ansible_distribution*"
SSH password:
127.0.0.1 | success >> {
    "ansible_facts": {
        "ansible_distribution": "CentOS",
        "ansible_distribution_major_version": "7",
        "ansible_distribution_release": "Core",
        "ansible_distribution_version": "7.1.1503"
    },
    "changed": false
}

For fresh vagrant box with centos 7.1.

@vmalloc can you provide more details? Ansible version, OS version.
Can u try to check problem with latest ansible version from devel branch?

Can u provide same output for setup module?

**Comment by vmalloc** [comment]
Yes. My host reports this under `/etc/redhat-release`:

```
Derived from Red Hat Enterprise Linux 7.1 (Source)
```

And thus the release seems to be identified as RedHat:

```
host-003 | success >> {
    "ansible_facts": {
        "ansible_distribution": "RedHat",
        "ansible_distribution_major_version": "7",
        "ansible_distribution_release": "Core",
        "ansible_distribution_version": "7.1.1503"
    },
    "changed": false
}
```

**Comment by bcoca** [comment]
so you changed your /etc/redhat-release to show redhat?

**Comment by mightydok** [comment]
According to this - http://lists.centos.org/pipermail/centos-announce/2015-April/021010.html @vmalloc you just need to run yum update and problem will be fixed.
@bcoca i will try to update ansible code to prefer /etc/os-release if present.

**Comment by vmalloc** [comment]
@mightydok will try it. Thanks!

**Comment by vmalloc** [comment]
Seems to work for me. Thanks!
