### ISSUE TITLE
Ansible script module does not send boolean argument to powershell script

### ISSUE THREAD

**Issue by alextricity25** [ansible/ansible#10947]
In the powershell script, we have defined a boolean parameter like so: 
Param(
                [bool]$boolvariable
)
And I run the script module against it like so:
script: rax_ConfigureAppFabric.ps1 $True

However, it seems like the script module always treats this argument as a string, so the powershell script fails. 
Anyway to get around this? A bug maybe?

**Comment by cchurch** [comment]
I've fixed this bug and added a test via https://github.com/ansible/ansible/pull/12051
