### ISSUE TITLE
variables set via vars_prompt and set_fact can not be used in playbook hosts line

### ISSUE THREAD

**Issue by tjbaker** [ansible/ansible#10942]
The following playbook skips the second play and prints "skipping: no hosts matched" when run via:

```
# enter localhost when prompted
ansible-playbook -i "foo," bug.yml
```

If you pass the variable in via the command line it works.

```
ansible-playbook -i "foo," bug.yml -e "machine=localhost"
```

Expected Result: variables set via vars_prompt and set_fact should resolve in the hosts line of subsequent plays

Testcase

```

---

- name: bug test
  hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: machine
      prompt: specify the machine
      private: false

  pre_tasks:

    - name: "set_vars"
      set_fact: machine={{ machine }}

  tasks:

    - debug: msg="machine={{ machine }}"

- name: connect to var_prompt provided hosts
  # also fails if you use {{ hostvars['localhost']['machine']}}
  hosts: "{{ machine }}"
  gather_facts: True

  tasks:

    - debug: msg="{{ lookup('pipe','date') }}"
```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The hosts: line gets resolved before any play is run (play 'compile' time), so there is no way set_fact or vars/vars_prompt can affect this line. This is not a feature we currently support.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by tjbaker** [comment]
Can you refer me to the documentation where it states the hosts line can only reference static "facts" from inventory files?  If this isn't stated, I'd like to see the documentation updated to reflect this.  Otherwise, shame on me for not reading more closely!  :-)

**Comment by bcoca** [comment]
Actually you cannot use inventory vars either as hosts: is used to locate which variables are to become available. I don't believe there is an explicit doc section stating this nor otherwise.
