### ISSUE TITLE
[FeatureRequest] Be able to get the resolved parameters in a module

### ISSUE THREAD

**Issue by lyrixx** [ansible/ansible#10961]
Hello,

I would like to implement a module that will lives in a role to be able share it
(internally for now).

It's a role to manage [consul](https://consul.io).

In order to be flexible, I set some default configurations about directories an
path in the `defaults/main.yml` file. (Quickly: consul is a daemon that load all
files in a defined directory (like `/etc/consul.d`))

Then, I want to provide a module called `consul_service` that will validate the
configuration, convert it to json, dump it to the configuration directory, and
finally reload consul at the end of the Ansible run.

But I hit a wall: I'm unable to get the resolved configuration in a simple way.
I need it to be able to dump the configuration of the new service in the config
dir.

I already used an ansible cookbook for chef, and it was easy to do this thing.

So:
1. I'm unable to get resolved configuration in a module
2. I did not find a way to `notify` a "service" in a module

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case it sounds like you are doing too much inside the module, there are already ansible modules that do the things you ask for and are easy to incorporate into your role, register the output that creates the configuration, use template to update the files if they need changing and then that can use the notify: keyword to restart the service or not.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
