### ISSUE TITLE
SSH User parameter is not explicitly set when requested/defined while matching the invoking user

### ISSUE THREAD

**Issue by shawnferry** [ansible/ansible#10962]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible --version
ansible 1.9 (devel ede94dd7f8) last updated 2015/03/29 14:04:17 (GMT -400)
  lib/ansible/modules/core: (devel 791a28d6a8) last updated 2015/04/06 17:57:40 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD cb848fcd9e) last updated 2015/04/03 15:14:36 (GMT -400)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/02/26 12:26:47 (GMT -400)
  v2/ansible/modules/extras: (detached HEAD 46e316a20a) last updated 2015/04/03 15:14:36 (GMT -400)
  configured module search path = None
```
##### Ansible Configuration:

pipelining = True
##### Environment:

it's an invocation error but OS X 
##### Summary:

If I happen to have a ~/.ssh/config that defines User for a swath of hosts it is used instead of the explicitly defined user on the command line or inventory the result is unexpected failure. 

As expected using -u on the command line overrides the value of ansible_ssh_user and ansible_ssh_user is applied if it differed from the invoking user. However, if I have explicitly provided a user and that user matches my user name the ssh invocation remains implicit.  
##### Steps To Reproduce:

ansible lab -m ping -vvv modified as below
###### -u bob;  ansible_ssh_user=sue

```
ConnectTimeout=10 ... User=bob ... ControlPersist=60s
```
###### ansible_ssh_user=sue

```
ConnectTimeout=10 ... User=sue ... ControlPersist=60s
```
###### -u sferry; ansible_ssh_user=sue

```
ConnectTimeout=10 ... (No User Parameter) ... ControlPersist=60s
```
###### ansible_ssh_user=sferry

```
ConnectTimeout=10 ... (No User Parameter) ... ControlPersist=60s
```
##### Expected Results:

 if I request a specific user with -u or ansible_ssh_user it should be explicitly provided to ssh 
##### Actual Results:

When logged in user matches requested or defined user no User parameter is passed to ssh.

**Comment by bcoca** [comment]
this was done explicitly to allow for using the 'current' user's .ssh/config

**Comment by shawnferry** [comment]
If I pass a command line user argument I expect that it will always be used as the User argument to ssh. If I want to allow .ssh/config to take precedence I would expect some sort of special case argument  ?'-u none'?  However, and in my case I instead don't provide a user argument when I want to use the .ssh/config which matches the behavior of ssh from the command line.

I think this is a relatively uncommon case. I'm working in a number of environments with mixed logins and bootstrapping into ansible. Clearly I could unset the User argument in .ssh/config and I will once my predominant use case is ansible and my user id. My real problem is the lack of least surprise for this one use case in which an explicitly provided user is silently ignored.

As was commented out of band, v2 is coming so I'll look into submitting a pull but there are other things occupying my time at the moment. 

| WhoAmI | Command Line | ansible_ssh_user | .ssh/config | Result User Arg | Source |
| --- | --- | --- | --- | --- | --- |
| sferry | - | - | - | - | Implicit (sferry) |
| sferry | - | - | joe | joe | .ssh/config |
| sferry | - | sue | joe | sue | ansible_ssh_user |
| sferry | bob | sue | joe | bob | command line |
| sferry | bob | - | joe | bob | command line |
| sferry | sferry | - | joe | - | .ssh/config |
| sferry | sferry | sferry | joe | - | .ssh/config |
