### ISSUE TITLE
UnicodeDecodeError when using ec2.py swallows real error from remote hosts

### ISSUE THREAD

**Issue by nickstenning** [ansible/ansible#10960]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.9.1
  configured module search path = None
```
##### Ansible Configuration:

This is vanilla ansible installed from the `ansible/ansible` PPA:

```
$ apt-cache show ansible
Package: ansible
Priority: optional
Section: admin
Installed-Size: 4189
Maintainer: Michael DeHaan <michael.dehaan@gmail.com>
Architecture: all
Version: 1.9.1-1ppa~trusty
Depends: python, python-support (>= 0.90), python-jinja2, python-yaml, python-paramiko, python-httplib2, python-crypto (>= 2.6), sshpass
Filename: pool/main/a/ansible/ansible_1.9.1-1ppa~trusty_all.deb
Size: 623674
MD5sum: 5fe93ff14c633238b8b11f8dab9017c1
SHA1: 7bac5506f8e453195a9efdc29dabaaf60f3b4d7e
SHA256: 006717c54311d131d0270570b8fb92624f5deba4af477d42826e1318c431b022
Description-en: A radically simple IT automation platform
 A radically simple IT automation platform that makes your applications and
 systems easier to deploy. Avoid writing scripts or custom code to deploy and
 update your applications— automate in a language that approaches plain English,
 using SSH, with no agents to install on remote systems.
Description-md5: ddfdff3530378f98f78630ce2aed5fe8
```

And I haven't changed any configuration files:

```
$ debsums -ac ansible
[NO OUTPUT]
```
##### Environment:

Ubuntu 14.04.2:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:    14.04
Codename:   trusty
```

If it helps, I'm using AMI `ami-cc3b3ea4` in us-east-1.

The locale appears to be correctly configure both on the machine running ansible and the client hosts:

```
$ env | egrep 'LC|LANG'
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
$ ssh 10.1.1.47 "env | egrep 'LC|LANG'"
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
```
##### Summary:

When using the `ec2.py` dynamic inventory, errors from remote hosts get swallowed and a `UnicodeDecodeError` is reported in their place, apparently because the error message contains unicode characters.
##### Steps To Reproduce:
1. Provision some machines in EC2 that you can reference with the dynamic inventory.
2. Break ansible by making the user ansible connects as unable to write to the default ansible tmp directory (`$HOME/.ansible/tmp/`).
3. Run the `ping` module against those machines.
##### Expected Results:

Expect to see the same errors as when running ansible with a static hosts file, namely:

```
$ ansible -i ec2.py --list-hosts tag_Type_app > hosts
$ ansible -i hosts -m ping all
10.1.1.47 | FAILED => Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-tmp-1431103805.94-163759797546743 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1431103805.94-163759797546743 && echo $HOME/.ansible/tmp/ansible-tmp-1431103805.94-163759797546743, exited with result 1: mkdir: cannot create directory ‘/home/ansible/.ansible’: Permission denied

10.1.1.46 | FAILED => Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-tmp-1431103805.94-76657610650604 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1431103805.94-76657610650604 && echo $HOME/.ansible/tmp/ansible-tmp-1431103805.94-76657610650604, exited with result 1: mkdir: cannot create directory ‘/home/ansible/.ansible’: Permission denied
```

**N.B.** The errors above are not the errors I'm reporting, they are expected due to the configuration of the remote hosts.
##### Actual Results:

The error relating to permissions is swallowed and replaced with a `UnicodeDecodeError`:

```
$ ansible -i ec2.py -m ping tag_Type_app
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 84, in _executor_hook
    return_data = multiprocessing_runner._executor(host, new_stdin)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 591, in _executor
    self.callbacks.on_unreachable(host, msg)
  File "/usr/lib/pymodules/python2.7/ansible/callbacks.py", line 395, in on_unreachable
    display("%s | FAILED => %s" % (host, res), stderr=True, color='red', runner=self.runner)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 514: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 84, in _executor_hook
    return_data = multiprocessing_runner._executor(host, new_stdin)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 591, in _executor
    self.callbacks.on_unreachable(host, msg)
  File "/usr/lib/pymodules/python2.7/ansible/callbacks.py", line 395, in on_unreachable
    display("%s | FAILED => %s" % (host, res), stderr=True, color='red', runner=self.runner)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 514: ordinal not in range(128)
```

**Comment by rncry** [comment]
We're seeing this problem too, some errors are reported normally, some not.

**Comment by rncry** [comment]
I've submitted a hacky pull request to fix this. Another solution is adding:

import sys
sys.setdefaultencoding('UTF8')

to your sitecustomize.py file (found somewhere like: /usr/lib/python2.7/site-packages/ create it if it doesn't exist) although this will change ALL your python scripts to be utf-8 by default(!)

**Comment by abadger** [comment]
IIRC, in v1's code we want to transform everything into a byte str before calling display().  So the fix is probably to modify callbacks.py something like this:

```
@@ -392,6 +392,7 @@ class CliRunnerCallbacks(DefaultRunnerCallbacks):
     def on_unreachable(self, host, res):
         if type(res) == dict:
             res = res.get('msg','')
+        res = to_bytes(res)
         display("%s | FAILED => %s" % (host, res), stderr=True, color='red', runner=self.runner)
         if self.options.tree:
             utils.write_tree_file(
```

Do you get a traceback using the latest devel branch as well?  If so, it will give me a clue as to where this needs to be fixed in v2's code (and if not, then it's already working there ;-)

**Comment by abadger** [comment]
The above commit should fix this in the stable-1.9 branch.  I think there's still a potential to run into this in v2 so working on a set of fixes there.

**Comment by abadger** [comment]
Committed this for v2: 49a148056c86a5ef047a3004a7a0190349adef2b

I think there's still places where we can get tracebacks in v2 at a higher level but the proper place to fix that is by transforming byte str into unicode types where the data comes into the process.

**Comment by securitybites** [comment]
Im having this issue in the latest dev build using EC2. Opened issue https://github.com/ansible/ansible/issues/13303
