### ISSUE TITLE
SSH connection got stuck when IP and host have different keys in known_hosts

### ISSUE THREAD

**Issue by jyrkiput** [ansible/ansible#10975]
In following situatation, I'd like to have some kind of error report, but now the connection just got stuck.

I reinstalled one machine, and tried to use same IP and host after installation. The initial ansible connection reported nicely

> fatal: [node2-jenkins-slave.dev.sysart.fi] => Using a SSH password instead of a key is not possible because Host Key checking is enabled and sshpass does not support this.  Please add this host's fingerprint to your known_hosts file to manage this host.

After adding doing this and trying to connect, the connection got stuck

> ansible -i hosts node2-jenkins-slave.dev.sysart.fi -m ping -u root -k -vvvv
> SSH password: 
> <node2-jenkins-slave.dev.sysart.fi> ESTABLISH CONNECTION FOR USER: root
> <node2-jenkins-slave.dev.sysart.fi> REMOTE_MODULE ping
> <node2-jenkins-slave.dev.sysart.fi> EXEC sshpass -d6 ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/jyrki/.ansible/cp/ansible-ssh-%h-%p-%r" -o GSSAPIAuthentication=no -o PubkeyAuthentication=no -o User=root -o ConnectTimeout=10 node2-jenkins-slave.dev.sysart.fi /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1431337315.21-244074993784678 && echo $HOME/.ansible/tmp/ansible-tmp-1431337315.21-244074993784678'

I think that the reason for this had something to do with the warning I got with ssh

> ssh node2-jenkins-slave.dev.sysart.fi
> Warning: the ECDSA host key for 'node2-jenkins-slave.dev.sysart.fi' differs from the key for the IP >address '192.168.179.43'
> Offending key for IP in /home/jyrki/.ssh/known_hosts:107
> Matching host key in /home/jyrki/.ssh/known_hosts:133

After removing both keys and adding the host to known_hosts, everything worked.

**Comment by jean-christophe-manciot** [comment]
Same issue here

**Comment by bortek** [comment]
same here. I would like to have a flag to force access a new host key!

**Comment by jctanner** [comment]
There are 2 separate components to this issue:
1. A bad key in known_hosts
2. ssh-pass getting stuck on interactive input for something other than the string "assword:" which is what it is coded to look for.

The bad key can be mitigated by using the ansible config option to ignore host keys so that the option is passed into ssh. However, this is not a recommended way to assure secure connections. 

As suggested above, sshpass does -not- handle sending yes/no to accepting keys. You need to do that manually or by accepting all keys. If sshpass encounters some prompt that doesn't end in 'assword', it hangs. I suspect that is the "hang" you encountered.

**Comment by vesharma** [comment]
Simple solution is adding a 
# add hosts ssh key to known_hosts 
ssh-keyscan -H 192.168.0.1 >> /home/vesharma/.ssh/known_hosts
and restart ssh service
 /bin/systemctl reload sshd.service

[amit@localhost inventory]$ cat firstinventory
[web]
192.168.238.130
192.168.238.133

[amit@localhost inventory]$ ansible web  -a 'java -version' -i firstinventory -u root -k
SSH password:
192.168.238.133 | SUCCESS | rc=0 >>
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b12)
OpenJDK 64-Bit Server VM (build 25.131-b12, mixed mode)

192.168.238.130 | SUCCESS | rc=0 >>
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
