### ISSUE TITLE
try to chroot command through raw action not working

### ISSUE THREAD

**Issue by czytom** [ansible/ansible#1097]
I have in my playbook action:
- name: chroot to installed system
  action: shell chroot /mnt /bin/bash

If I try run this playbook it stops on above task. Only way is to cancel playbook run
I tested in on ansible-0.7

**Comment by mpdehaan** [comment]
If you're starting an interactive shell in a playbook run ("/bin/bash" -- not the shell module itself), that would be totally expected.  Don't do that.    Since you're trying to automate something, run a script, not an interactive shell.

**Comment by czytom** [comment]
so as I understand, you're saying that ansible is totaly unasable if I need to do chroot and then work within new environment - I can't use ansible for that. So it's strange becasue it should be easy managed ssh connection but it seems to be something more which start smelling bad.

**Comment by mpdehaan** [comment]
On Wed, Sep 26, 2012 at 8:49 AM, Krzysztof Tomczyk <notifications@github.com

> wrote:
> 
> so as I understand, you're saying that ansible is totaly unasable if I
> need to do chroot and then work within new environment - I can't use
> ansible for that. So it's strange becasue it should be easy managed ssh
> connection but it seems to be something more which start smelling bad.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/1097#issuecomment-8888514.

The "/bin/bash" is the problem.  Ansible is not a tool for spawning
interactive shells, if you want that, just use SSH directly.   It's a tool
for hands-off automation and command execution.

**Comment by mpdehaan** [comment]
On Wed, Sep 26, 2012 at 9:02 AM, Michael DeHaan michael.dehaan@gmail.comwrote:

> On Wed, Sep 26, 2012 at 8:49 AM, Krzysztof Tomczyk <
> notifications@github.com> wrote:
> 
> > so as I understand, you're saying that ansible is totaly unasable if I
> > need to do chroot and then work within new environment - I can't use
> > ansible for that. So it's strange becasue it should be easy managed ssh
> > connection but it seems to be something more which start smelling bad.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/1097#issuecomment-8888514.
> 
> The "/bin/bash" is the problem.  Ansible is not a tool for spawning
> interactive shells, if you want that, just use SSH directly.   It's a tool
> for hands-off automation and command execution.

It's possible for for making it support chroots by making changes to the
connection modules (paramiko and ssh), I imagine.    But this would be a
contextual thing, not something you'd do with a single module.
- hosts: somegroup
  chroot: /path/to/chroot
  ...

Patches would be accepted depending on what levels of complexity they
added.   I have a feeling it would be non trivial.

**Comment by czytom** [comment]
ok, I will try to submit some patches. I tried to make some workaround but it seems in some area very problematic, for example I need to set passwd for root user in system that I'm creating in chroot directory. I tried to run chroot without passing shell parameter, effect is the same

**Comment by czytom** [comment]
I thought that ansible should be totally independent fo any package on managed side (excluding sshd), but it seems that without right version of python it's impossible to provision machine. Maybe adding simple check for remote python version is a resolution?

**Comment by mpdehaan** [comment]
Pretty much every distribution already has a workable 2.x.

What are you using?

Not really interested in adding an additional remote check because the path
could be anywhere.

This is what ansible_python_interpeter is for.

Anyway, generalized discussion belongs on the mailing list, not on the
issue tracker -- this isn't a bug so much.

**Comment by mmoya** [comment]
(FTR) See PR #2082.
