### ISSUE TITLE
 copy module: input file not found at 

### ISSUE THREAD

**Issue by fbrbovic** [ansible/ansible#10972]
Issue Type:

Bug Report

Ansible Version:

ansible 1.9.1

Ansible Configuration:

No settings have been changed

Environment:

Tower installed on Centos 7    managing other Centos 7 servers.

Summary:

I have a role which tries to copy a local (tower server) public key to a remote server
but I am getting an error `input file not found at`   but I checked and files is there on the local centos 7 server with tower.  I am running a job thru Tower. 

Steps To Reproduce:

I have a role which tries to copy a local (tower server) public key to a remote server
Like so : 

```
- name: Create the github SSH public key file
  copy: src=/var/lib/awx/keys/id_rsa.pub
        dest=/root/.ssh/id_rsa_github.pub
        mode=0644
        owner=root
        group=root
```

I am getting an error back 

```
fatal: [server] => input file not found at /var/lib/awx/keys/id_rsa.pub or /var/lib/awx/keys/id_rsa.pub
```

I checked and file is there , I also tried setting ownership of the file of : awx  thinking maybe it will help but still getting the same error

Expected Results:

I am expecting it to copy the local file to remote server

Actual Results:

I am getting an error back 

```
fatal: [server] => input file not found at /var/lib/awx/keys/id_rsa.pub or /var/lib/awx/keys/id_rsa.pub
```

Does anyone have any idea whats wrong ?

**Comment by mightydok** [comment]
@fbrbovic can you make: ls -la /var/lib/awx/keys/id_rsa.pub on tower server?
Can you somehow publish debug logs for ansible?

**Comment by bennojoy** [comment]
@fbrbovic  it might be because of proot settings in tower. can you please raise this in support.ansible.com

**Comment by bcoca** [comment]
closing as this is a tower question
