### ISSUE TITLE
Unclear sentence in playbook introduction documentation

### ISSUE THREAD

**Issue by alexmuller** [ansible/ansible#10970]
The [documentation that gives an introduction to playbooks](https://github.com/ansible/ansible/blob/ded6e9be671e63829659ff52d656e2a0eefd4d49/docsite/rst/playbooks_intro.rst#hosts-and-users) says:

> Support for running things from as another user is also available

This doesn't make sense to me. I'm not sure what it's supposed to say or I'd send a pull request.

**Comment by bcoca** [comment]
s/from//
