### ISSUE TITLE
Failed to lock apt for exclusive operation

### ISSUE THREAD

**Issue by truptimali** [ansible/ansible#10989]
I am using ansible 2.0 - the development version. I have read many threads on the above issue and essentially all suggested to make sure we are doing sudo = True. I tried with Sudo true at playbook level , include level and now inside ansible.cfg as well. But I am still getting the same error.
When I ran the playbook in -vvvv mode here is what I see - 

<212.71.255.79> EXEC ssh -C -tt -vvv -F ssh.config -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 212.71.255.79 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=fvzlrgtvogqmaybuqufnxzunpgmwmajo] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-fvzlrgtvogqmaybuqufnxzunpgmwmajo; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1431423533.2-123716523690549/apt; rm -rf /root/.ansible/tmp/ansible-tmp-1431423533.2-123716523690549/ >/dev/null 2>&1'"'"''
failed: [swift-package-cache-01] => (item=swift,python-swiftclient,openssh-server,rsync) => {"failed": true, "item": "swift,python-swiftclient,openssh-server,rsync"}
msg: Failed to lock apt for exclusive operation

I was expecting message as SUDO_SUCCESS instead of BECOME_SUCCESS. But I think that shud be fine. Can some one please guide me? I have also tried reboot.

**Comment by abadger** [comment]
You'll want to take this question to the mailing list which is better suited for the back and forth needed to diagnose user questions.  You should probably post things like your playbook (or the subset that seems relevant), how you're invoking ansible, and the error message you have above.

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
