### ISSUE TITLE
Module group fails when removing (local) group with LDAP enabled

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#1100]
If you want to remove a local group when LDAP is enabled and LDAP also exports the same group (hence the removal) the group module bails out with a message "groupdel: cannot remove the primary group of user 'some_user"', where some_user is in fact in LDAP.

I was expecting the user and group modules to take care of locally defined users/groups (only), despite the LDAP config. I don't know if this is (at all) solvable.

**Comment by mpdehaan** [comment]
Added you to the project since I think you wanted this ticket, so now I can assign things to you.

Let me know if you didn't!

**Comment by dagwieers** [comment]
I rather wanted to be assigned to #1099, because I don't know if this one is fixable the way it is implemented now. The only solutions I see are:
- Manage files directly (rather than using tools)
- Disabling/enabling ldap/nis/... in nsswitch when using tools

I don't think you can make useradd/usermod/userdel work on local user-accounts only. So the workaround at this time is to modify nsswitch before and after.

**Comment by mpdehaan** [comment]
ok, I'm not sure what to do about this one so I'm just going to close it.   It seems like it possibly could be a doc item, but also that it may be unlikely many folks will hit it

**Comment by jacobweber** [comment]
You could use lgroup\* and luser\* for this, at least on some operating systems. This would be nice to have as an option for the user and group modules; maybe a local=yes switch.
