### ISSUE TITLE
ansible  inventory script ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by baxiaoshi** [ansible/ansible#11007]
cat inventory/get_hosts.py 

```
#!/usr/sbin/python2.7
#import argparse
import redis 
import json 
import sys


def get_all_members(parsed_args=""):
    r = redis.StrictRedis(host='172.16.1.220')
    return_data = {'local':'127.0.0.1'}
    all_groups =  r.keys()
    for group in all_groups:
        return_data[group] = {'hosts':[]}
        for host in r.hkeys(group):
                return_data[group]['hosts'].append(host)
    print json.dumps(return_data,indent=4)

def get_group_members(groupname):
    print json.dumps({groupname:r.hkeys(groupname)})

def get_host(host):
    print json.dumps(host)

if __name__ == "__main__":
    print sys.argv
    if len(sys.argv) == 2 and (sys.argv[1] == '--list'):
        get_all_members()
```

When I use the following command execution ansible

```
ansible --inventory-file=/etc/ansible/inventory/get_hosts.py  all 
```

to me:

```
  File "/usr/local/python/lib/python2.7/json/decoder.py", line 346, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python/lib/python2.7/json/decoder.py", line 365, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

My English is not very good, thank you!

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case it seems your script is not returning valid JSON.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by srgvg** [comment]
@baxiaoshi did you check the output of your script?

the problem is probably you left out this print statement in the main loop:

```
print sys.argv
```

**Comment by baxiaoshi** [comment]
Thank you, have been solved, in another machine before I write the script, and then copied to the machine, may has something to do with TAB Spaces of vim, have been solved
