### ISSUE TITLE
Removing requirepass in redis.conf, tower returns error PUT returned: 500

### ISSUE THREAD

**Issue by laapsaap** [ansible/ansible#11020]
I am trying enabling fact caching in combination with Ansible Tower, so apparently requirepass has to be uncommented in redis.conf.

When I do that, the facts show... but when I launch a job in Ansible Tower it shows me

```
Failed updating job 89 with variables. PUT returned: 500
```
## Ansible Version:

LATEST Fedora EPEL version + LATEST Ansible Tower
## Ansible Configuration:

Default Ansible Tower on CentOS7
## Environment:

Default Ansible Tower on CentOS7
## Summary:

Enabling fact caching needs NOAUTH, removing Requirepass in redis.conf makes Ansible Tower unusable.
## Steps To Reproduce:
1. ansible.cfg set fact_caching = redis
2. redis.conf remove requirepass
3. restart everything
4. ansible tower jobs -> Failed updating job 89 with variables. PUT returned: 500
## Expected Results:

Money
## Actual Results:

Headache

**Comment by abadger** [comment]
@laapsaap Hey,  I think this is probably a question that will be better answered by the support department.  You can reach them by emailing support@ansible.com.

I do see in the Tower User Guide (Under "General Installation Notes") that the configuration you're talking about is known not to work:

> If using Ansible 1.8 or later, ensure that fact caching using Redis is not enabled in ansible.cfg on the Tower machine
> - From _General Installation Notes_ of http://releases.ansible.com/ansible-tower/docs/tower_user_guide-latest.pdf 

but support will likely have more information on alternatives than I do just from the User Guide.
