### ISSUE TITLE
api based dynamic inventory

### ISSUE THREAD

**Issue by leemason** [ansible/ansible#11021]
im a php guy and python just isnt my thing.

As a result im struggling with what i want to do concerning a dynamic inventory which should be such a simple thing.

it would be nice if a inventory plugin could be created with accepts an api url to fetch the inventory.

for example:

`ansible -i url.py --inventory-url=http://...../inventory.json -m ......`

based on the docs for dynamic inventory it would be great if the above could be included in the core with some core "request types" for url based inventories (--list becomes ?list=true, --host <hostname> becomes ?host=<hostname>, etc).

this would allow anybody from any language to develop rest apis which respond to ansible inventory calls with json responses without needing to know how to write python code.

as i said at the start, if i knew how to i would have coded this myself and offered it to the core, but im lacking in that area.

it could also be shortened so instead of -i url.py and providing a url ansible core could check if -i is a directory OR is a url and call the core url inventory lookup script without needing to bloat the command line.

imo this would be a huge plus and im sure other none-python developers would love to see this too.

**Comment by sivel** [comment]
Dynamic inventory scripts can be written in any language as long as they return the correct structure, they just have to be local executable files.

**Comment by bcoca** [comment]
closing this as you can write the inventory script in php, the only requirements are that it accepts certain options and returns a json structure, as stated in docs
