### ISSUE TITLE
feature request: (auto) import (local) custom python library

### ISSUE THREAD

**Issue by kinvaris** [ansible/ansible#11022]
Hi,
I've got a custom ansible module with some standard imports like:
`import requests
import json
import sys
from pprint import pprint`
but when I develop a custom python library and include the main class like this: 
`from InfoBlox.infoblox import Infoblox`, I get some errors when I deploy the ansible playbook because the (extra imported) python module is not automatically transfered to 
`/home/$USER/.ansible/tmp/ansible-tmp/` 

**ERRORS:** 
`Traceback (most recent call last):
  File "/home/$USER/.ansible/tmp/ansible-tmp/custom-ansible-module", line 7, in <module>
    from InfoBlox.infoblox import Infoblox
ImportError: No module named InfoBlox.infoblox
`

But when I run this **without** ansible-playbook (or without the import), it (partially) works...
When I test the module (locally) with `ansible/hacking/test-module -m custom-ansible-module`, it works.

So, my employer suggested to create a feature request.

**Comment by bcoca** [comment]
libraries required by modules need to be installed in the system the module runs. You can use a OS package manager module or pip to do so.

Also you should test that non core modules are installed and give an appropriate error message if not,  check ec2.py and it's handling of the boto library.

**Comment by paulnice** [comment]
I don't think it's a good idea to put unwanted python modules to the global python installation.
Especially when the module doesn't exist in pypi and/or package manager.
