### ISSUE TITLE
Add 'source' option to 'dependencies' in the meta/main.yml

### ISSUE THREAD

**Issue by CptLausebaer** [ansible/ansible#11031]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.9.0 (detached HEAD d76f8deed5) last updated 2015/04/27 14:58:48 (GMT +200)
##### Environment:

“N/A”
##### Summary:

The `ansible-galaxy`-command can install roles from a requirement-file, so it is possible to install roles from an intern corporate Git-server instead of the official ansible-galaxy. The problem is that if the role has dependencies it tries to fetch these roles from the official ansible-galaxy.

The Solution would be to define the source of the dependencies in the main/meta.yml file of the first role.

``` yml

---
# file: ROLE/meta/main.yml
dependencies:
    - { role: my_corporate_role1, src:git+https://git@ourgitlabhost/example-group/my_corporate_role1.git }
    - { role: my_corporate_role2, src:git+https://git@ourgitlabhost/example-group/my_corporate_role2.git }

```
##### Steps To Reproduce:

Create a role with dependencies which are not hosted on ansible-galaxy.
for example Bitbucket:

``` yml

---
# file: ROLE/meta/main.yml

# role that a I want my role to depend on: https://bitbucket.org/marklee77/ansible-role-roundcube.git
dependencies:
  - { role: marklee77.roundcube }
```
##### Expected Results:

The `ansible-galaxy`-command installs my role which has dependencies and installs the dependencies from there source.
##### Actual Results:

The `ansible-galaxy`-command installs my role which has dependencies and fails to install the dependencies because they are not hosted on ansible-galaxy.

**Comment by bcoca** [comment]
I'm actually working on this for the v2 engine

**Comment by BarthV** [comment]
Hi,
Is this feature present on v2 devel branch ?

**Comment by jaytaylor** [comment]
This still causes me pain on a continual basis.  Is anyone able to comment on whether this has been addressed or elaborate on the plans?

**Comment by jaytaylor** [comment]
Greetings,

This still causes me pain on a continual basis as it seems to prohibit role dependencies from being resolved.

Is anyone able to comment on whether this has been addressed or elaborate on the plans?

**Comment by CptLausebaer** [comment]
Hi,

there should be an option in the `ansible.cfg` configuration to define a custom roles "repository" , so that `ansible-galaxy` tries to fetch roles from this server first and then tries to find the role in the public ansible-galaxy. I'm thinking of something like [satis](https://github.com/composer/satis), which provides a private repository for [composer](https://github.com/composer/composer)-packages.

To complete my example above:

``` ini
---
# ansible.cfg

[galaxy]
ansible_custom_roles_repo = http://ourgitlabhost/example-ansible-galaxy-group/
```

``` yaml
---
# requirements.yml
- src: company-role-1
- src: company-role-2
- src: company-role-3
- src: company-role-4

...

```

**Comment by jaytaylor** [comment]
I agree that sounds like a useful feature.

Are you certain it is the same as this dependency src issue, or should this
feature request be filed separately as its own issue?

**Comment by CptLausebaer** [comment]
I don't think that it is exactly the same issue, because there are already multiple ways to adress the source of a role (e.g. you can define the whole uri for each role to install like explained at the [docs](http://docs.ansible.com/ansible/galaxy.html#advanced-control-over-role-requirements-files) ), but I think there should be a uniform method to search and dissolve dependencies for non-public ansible roles, which are hosted at a private gitlab or other scm-hosts.

**Comment by fwisehc** [comment]
+1

**Comment by xrow** [comment]
If you would also allow us to decide if the role comes wiht or without the .git folder would be a plus. I would like to do a change and commit instanly.

**Comment by bcoca** [comment]
superseded by https://github.com/ansible/proposals/issues/23#issuecomment-234942874
