### ISSUE TITLE
Evaluate other host's vars in the context of that other host

### ISSUE THREAD

**Issue by hkariti** [ansible/ansible#11047]
##### Issue Type:

Feature Idea
##### Ansible Version:

1.9.0
##### Ansible Configuration:

NA
##### Environment:

NA
##### Summary:

When accessing another host's variables through `hostvars.hostname.variable_name`, if the value of `variable_name` is templated, the template is evaluated using the current's host available variables instead of the variable's host of origin. It requires putting more variables in more generic groups such as `all`, making them noisier.
##### Steps To Reproduce:

host_vars/origin:

``` yaml
var: "123"
template: "{{ 'templ_' + var }}"
```

``` bash
ansible destination -m debug -a 'msg={{hostvars.origin.template}}'
```
##### Expected Results:

```
destination | success >> {
    "msg": "templ_123"
}
```
##### Actual Results:

```
destination | success >> {
    "msg": "{{ 'templ_' + var }}"
}
```

**Comment by jimi-c** [comment]
Hi @hkariti, this is actually working in devel now:

<pre>
# ansible testing -i inv -m debug -a "msg={{hostvars.origin.template}}"
testing | SUCCESS => {
    "changed": false, 
    "msg": "templ_123", 
    "verbose_always": true
}
</pre>

Thanks!
