### ISSUE TITLE
question about how to represent "colon then space" in YAML

### ISSUE THREAD

**Issue by pjoakimsson** [ansible/ansible#1104]
Seems execution fails due to YAML interpretation when you use colons in command.

I.e.:

``` code
action: command echo "a: b"

ERROR: Syntax Error while loading YAML script, ./test.yml
Note: The error may actually appear before this position: line 24, column 30
    - name: array test
      action: command echo 'a: b'
                             ^
```

**Comment by mpdehaan** [comment]
This is the Python YAML parser which is a bit beyond our control, though I agree it is annoying.  If you remove the space between the letter and the colon, it's happy, but it seems you can't easily escape the string.

Now, technically we could attempt to fix this by preprocessing the YAML file and replacing the string, and then fixing it back inside of utils.py's varReplace, but we would have to take care to only process lines that were inside of existing quotes, so as to not upset any actual valid YAML.  

I'm leaving this open but it shouldn't be too terrible to get a workaround.    This should also be reported to PyYAML.

**Comment by pjoakimsson** [comment]
Seems to be a known issue...
http://pyyaml.org/wiki/YAMLColonInFlowContext

**Comment by mpdehaan** [comment]
This is not quite YAML flow context, flow context is basically inline JSON.

IMHO, this should work and is a YAML bug unrelated to that.

**Comment by pjoakimsson** [comment]
Ah, ok. Sorry for that... I'm fairly new to both ansible and YAML.

**Comment by mpdehaan** [comment]
Don't be sorry!

YAML is usually friendly, this is news to me too :)

I'll see about reporting it to the PyYAML people, there is probably a way
we can work around it.

Until then, if you can leave off the space after the colon, that seems to
work.

You could also use a ansible variable to contain that string.

**Comment by dhozac** [comment]
Or quote the whole thing, e.g.
action: "command echo 'a: b'"

**Comment by mpdehaan** [comment]
Ah, point, I was trying to quote the substring.  I think that's sufficient.

**Comment by pjoakimsson** [comment]
Sneaky. 

Escaped double-quoting is even better if you want to use variables:
action: "shell echo \"a: b\" > /tmp/file.txt"

**Comment by prologic** [comment]
I ran into this recently as well with the following:

``` sh
$ ansible-playbook -u root -l hub.local hub.yml 
ERROR: Syntax Error while loading YAML script, /Users/s2092651/work/ccaih/playbooks/roles/plone/tasks/sudo.yml
Note: The error may actually appear before this position: line 6, column 46

          regexp="\%webdevs\ ALL\=\(plone\)\ NOPASSWD\:\ ALL"
          line="%webdevs ALL=(plone) NOPASSWD: ALL"
                                             ^

$ cat roles/plone/tasks/sudo.yml 
---
- name: Allow webdevs to sudo -u plone
  action: lineinfile
          dest=/etc/sudoers.d/webdevs
          regexp="\%webdevs\ ALL\=\(plone\)\ NOPASSWD\:\ ALL"
          line="%webdevs ALL=(plone) NOPASSWD: ALL"
          state=present

$ 
```

I would like to see this fixed in the pyyaml parser (upstream). Bit of an annoying parser bug :)

**Comment by bcoca** [comment]
try quoting the full module line, like this:

action: 'lineinfile
          dest=/etc/sudoers.d/webdevs
          regexp="\%webdevs\ ALL\=(plone)\ NOPASSWD:\ ALL"
          line="%webdevs ALL=(plone) NOPASSWD: ALL"
          state=present'

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by zachys** [comment]
I found using a double-double quotes after : to do the trick for me:
`- NOT_A_REPO="fatal:"" Not a git repository (or any of the parent directories):"" .git"`
