### ISSUE TITLE
how can I use ansible-playbooks to check if the host has been restarted as I hoped

### ISSUE THREAD

**Issue by BlueShells** [ansible/ansible#11043]
I want to reboot a host ,but after I run the reboot command ,I want to check if host reboot as hoped ,only method I can do now is :
- pause: minutes=1
  - name: test if the host reboot as we hoped
    ping:
    remote_user: root
    register: is_rebooted
  - name: reboot the host -f
    command: reboot -f
    when: is_rebooted.ping=="pong"

but this maybe not the best answer,I tried to use loop but failed ,how can I check this ?

thanks

**Comment by bennojoy** [comment]
Hi!

Thanks very much for your interest in Ansible. It sincerely means a lot to us.
maybe this should help you... 

https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back

Also This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!

**Comment by BlueShells** [comment]
@bennojoy I found what truely problem I have ,and does this a bug ?

why we need to write like this 

---
- name: restart the host
  
    shell: sleep 2&& reboot
  
    when: is_alive.ping=="pong"
  
    async: 1
  
    poll: 0
  
  ##   ignore_errors: true

to  avoid some error like 

fatal: [system2] => SSH Error: Shared connection to system2 closed.

as @jder says:

"I think what's going on is that when you launch an async process on the remote host (with async: 1), what it does is run a small synchronous process which sleeps for 1 second and then returns a small amount of JSON, as well as actually starting the async job. The problem is that if the SSH connection is torn down before the small synchronous job finishes, Ansible treats this as an unreachable error. I'm not sure what the "right" solution is (and I don't see changes here since 1.8.1), but this workaround works for me:"

https://github.com/ansible/ansible/issues/10616
