### ISSUE TITLE
Add validate recipes to the docs

### ISSUE THREAD

**Issue by astorije** [ansible/ansible#11048]
##### Issue Type:

Documentation Report
##### Summary:

To this day, several modules have a validate command: [`template`](http://docs.ansible.com/template_module.html), [`lineinfile`](http://docs.ansible.com/lineinfile_module.html), [`copy`](http://docs.ansible.com/copy_module.html), [`replace`](http://docs.ansible.com/replace_module.html) (Did I forget any?).

As reminder, it works like this:

> validation to run before copying into place. Use %s in the command to indicate the current file to validate. The command is passed securely so shell features like expansion and pipes won't work.

I find this to be extremely powerful yet not often used on roles you can find online. Experience and readings showed me that it's because it's not trivial. I often find myself browsing the examples in the doc to find that nice command.
It would be nice to have a list of recipes to test services after their configuration in the doc. What do you admins think of that?
Until it gets accepted, or if you don't see the value of it, I propose to list those I know or already found in the examples in the next section of this issue. Please comment with more and I'll add to the list.
##### Steps To Reproduce:

Known recipes:
- **Apache**: `apache2ctl -f %s -t` or `/usr/sbin/apache2ctl -f %s -t`?
- **Configuration files in JavaScript** (syntax): `esvalidate %s` (using the [esprima](https://www.npmjs.com/package/esprima) npm package)
- **Configuration files in JSON** (syntax): `jsonlint %s` (using the [jsonlint](https://www.npmjs.com/package/jsonlint) npm package)
- **Nginx** _(main configuration file only!)_: `nginx -t -c %s`
- **OpenSSH server**: `sshd -T -f %s`
- **sudoers file**: `visudo -cf %s`
- **syslog-ng**: `syslog-ng -F -s -f %s` or `/sbin/syslog-ng -F -s -f %s`?
##### Expected Results:

Unknown or desired recipes:
- apt
- apticron
- *.bashrc file
- exim4, with update-exim4.conf.conf, something like `nginx -bV -C %s`, ...
- fail2ban
- Gunicorn: `gunicorn -c %s --check-config APP_MODULE` but needs to be run from the project directory. Can we do that with `validate`?
- /etc/hosts file: http://www.trilug.org/pipermail/trilug/Week-of-Mon-20131021/069966.html ?
- lynis
- mpd
- Nginx `server` config (sort of virtualhosts)
- rkhunter: `rkhunter -C --configfile %s` _Does not work for `.local` files!_
- samba
- Supervisor

**Comment by astorije** [comment]
Added `syslog-ng`.

**Comment by astorije** [comment]
Not sure if the documentation/list should mention `whatever --check %s` or `/path/to/whatever --check %s`. I personally use the former version successfully, but I find the latter one on different examples.

**Comment by bcoca** [comment]
This might make a nice doc page to which the modules could link to.

also
`nginx -t -c %s`

**Comment by astorije** [comment]
Nice @bcoca! On Debian Wheezy (nginx 1.2.1 from apt), `man nginx` doesn't document `-c` but `nginx -h` does!

Agreed regarding the doc page, but I believe we need to compile more services beforehand. We can start by listing all the services that need validation.

**Comment by astorije** [comment]
I added a list of services for which I am using one of these modules and that are not validated. I'll look into validation recipes for those and update the list.

**Comment by astorije** [comment]
Added exim4 to the unknown recipe list.

**Comment by astorije** [comment]
Added syntax checking of JavaScript and JSON files.

**Comment by bcoca** [comment]
Since there has not been much traction with this, I'm going to close, feel free to submit a PR if you ever get around to creating a list.
