### ISSUE TITLE
ansible -a  and playbook shell command run a remote script fail

### ISSUE THREAD

**Issue by targetoyes** [ansible/ansible#11052]
for example     ansible -a "./script(restart some process)"  and playbook (shell command  raw) run a remote script,and it's ok by server using centos(process was restarted),but failed by ubuntu(actually script was run but process not start).I can't find where the problem was, but the command that ssh remote "./script" was ok,Ansible must be use ssh module but the result was different.

**Comment by bennojoy** [comment]
Hi @targetoyes 

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!
