### ISSUE TITLE
Debug messages (dark blue) nearly unreadable on dark background

### ISSUE THREAD

**Issue by wolph** [ansible/ansible#11050]
Is there any easy way to change this? It's pretty much impossible for me to read this without selecting the text now.

![image](https://cloud.githubusercontent.com/assets/270571/7759254/254d366a-0010-11e5-8d40-da997ea67867.png)

**Comment by bennojoy** [comment]
Hi!

you could do  export ANSIBLE_NOCOLOR=1 or set nocolor=1 in ansible.cfg

Also Thanks very much for your interest in Ansible. It sincerely means a lot to us.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!

**Comment by wolph** [comment]
Your answer pretty much confirms that it's not possible. I'll see if I can
make a pull request soon :)

**Comment by ElijahLynn** [comment]
@WoLpH Did you get a chance to work on this at all?

My text shows as black on black, not even blue on black. I am guessing that is because it is aiming for a default of a white terminal? 

I think it would be good to have an `ANSIBLE_COLOR_SCHEME` of `dark` or `light`.

**Comment by bcoca** [comment]
not full color scheme, but i added toggle for the prompt https://github.com/ansible/ansible/pull/42953

the rest are already configurable, i just thought that 'highlight' was not best one to keep the console prompt on

**Comment by wolph** [comment]
@ElijahLynn honestly... I monkey patched it and didn't get to writing the pull request anymore. 

There have been a lot of changes in the mean time so it might already be possible to change without much effort.

Personally I'm not using Ansible right now so I don't need it for the time being
