### ISSUE TITLE
route53: add support to create and delete dns zones

### ISSUE THREAD

**Issue by jalbstmeijer** [ansible/ansible#11068]
Currently it seems the the module route53 can only manage zone records, but not the zone it self.

**Comment by wkoszek** [comment]
@jalbstmeijer Not sure why this is opened, since with the current official `route53_zone` module I am able to create/delete zone records, i.e.: my domain is `domain.com` and I can make `some.domain.com` just fine in Route 53. I use it for testing in fact, before I apply the playbook to the production domain.

**Comment by wkoszek** [comment]
@bennojoy @jimi-c I believe we can close this issue, unless I misunderstood it.

**Comment by tomislacker** [comment]
@wkoszek fwiw I'm actively using the module right now at least on `ansible-2.2.0.0` without issues so unless something broke in 2.3, I'd at least vote for closure.

**Comment by jalbstmeijer** [comment]
This issue was opened on May 26, 2015 against the stable 1.9.x Ansible.
The route53_zone module was added in the stable Ansible 2 .0 release in 2016. (http://docs.ansible.com/ansible/route53_zone_module.html)

So that explains why this request was opened than and is not actual anymore.

**Comment by tomislacker** [comment]
@jalbstmeijer I was only commenting because of the labels that are *[then incorrectly]* applied.

**Comment by jalbstmeijer** [comment]
Reacted on "@jalbstmeijer Not sure why this is opened," from wkoszek and confirmed that from my point of view this issue can be closed too.

**Comment by jalbstmeijer** [comment]
I assume I can close it as I opened it.
