### ISSUE TITLE
Task with_items: 

### ISSUE THREAD

**Issue by MarcusCaepio** [ansible/ansible#11069]
Hi all,

I am new to Ansible and I am trying use the template module to create different config files.

```
Here is what I got:
├── group_vars
│   └── web
└── web
    ├── tasks
    │   └── main.yml
    └── templates
        └── virtualhost.conf
```

group_vars/web:

```
domain:
- alpha
- bravo
- charly
```

/web/tasks/main.yml:

```
- name: 7. Add Template Module
  template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{domain}}.conf
  with_items: domain
```

I want, that the task creates a file with each array field in the domain list. So, what I expect are three files, named alpha.conf beta.conf and charly.conf. But I just got one file, called ['alpha', 'bravo', 'charly'].conf

Job message:

```
src=virtualhost.conf dest=/etc/apache2/sites-available/['alpha', 'bravo', 'charly'].conf
```

Can you tell my how to fix this?

Kind regards,

Marcus

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
