### ISSUE TITLE
synchronize swaps the source and target in the output

### ISSUE THREAD

**Issue by urajio** [ansible/ansible#11067]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.1
  configured module search path = None
##### Ansible Configuration:

```
[defaults]
inventory       = ~/inventory
```
##### Environment:

Running at: Mac OS X 10.10.3
Managing: Debian 7.8
##### Summary:

synchronize works, but swaps the source and target in the output result.
##### Steps To Reproduce:

file "inventory":

```
[office-servers]
server1 ansible_ssh_host=192.168.1.1

[office-servers:vars]
ansible_ssh_user=root
ansible_ssh_private_key_file=~/.ssh/id_rsa_office
```

file "office-servers.yml':

```
- hosts: office-servers
  remote_user: root
  gather_facts: no
  roles:
    - firehol
```

file "roles/firehol/tasks/main.yml":

```
- name: Sync common files
  synchronize: archive=no recursive=yes times=yes perms=yes checksum=yes src=common/etc/firehol/ dest=/etc/firehol
```
##### Expected Results:

`changed: [127.0.0.1 -> server1]`
##### Actual Results:

ansible-playbook office-servers.yml 

```
PLAY [office-servers] ********************************************************* 

TASK: [firehol | Sync common files] ******************************************* 
changed: [server1 -> 127.0.0.1]

PLAY RECAP ******************************************************************** 
server1                  : ok=1    changed=1    unreachable=0    failed=0  
```

**Comment by bcoca** [comment]
Soo not sure what the problem is here, as your expected results match your actual results.

**Comment by urajio** [comment]
Problem purely cosmetic: 
`changed: [server1 -> 127.0.0.1]`
instead of 
`changed: [127.0.0.1 -> server1]`

**Comment by abadger** [comment]
Current output in 2.0.0.2 is:

```
TASK [firehol : Sync common files] *********************************************
changed: [rhel6-test]
```

We no longer specify both hosts, just the inventory_host.  So this issue seems to no longer apply.
