### ISSUE TITLE
0.7 ansible-playbook fail on if there is no or wrong python version (>3.x)

### ISSUE THREAD

**Issue by czytom** [ansible/ansible#1106]
I'm trying to create playbook where the first step is python-2.7.x installation. Playbook run fails if ansible try to gather facts. It only works if gathering facts are disabled.

**Comment by mpdehaan** [comment]
Not really enough information here.   Tip: never say "doesn't work" in a bug report -- share /HOW/ it doesn't work.

What OS?  What's the Output from running the command?    What messages did you get?

Potential further debugging:  If you run ansible <hostname> -m setup what happens?

**Comment by mpdehaan** [comment]
Ok, you have some stuff in the subject.

Seems like you might want to set ansible_python_interpreter as a host variable to specify the path to Python.

Ansible does not support Python 3.0 (yet, and not in immediate plan as long as 2.X is available in distros)

**Comment by czytom** [comment]
I have python 3.2 on remote machine. At first step I want to install python 2.7 on remote. When I run ansible-playbook with gather_facts: true then I got:

 ansible-playbook -u root install_gentoo.yml --tags "initial_config" -k
SSH password: 

PLAY [varnishpm01] ********************\* 

GATHERING FACTS ********************\* 
failed: [varnishpm01] => {"failed": true, "msg": "  File \"/var/tmp/ansible-1348747582.26-162443050825828/setup\", line 129\r\n\n    except OSError, e:\r\n\n                  ^\r\n\nSyntaxError: invalid syntax\r\n", "parsed": false}

TASK: [set python 2.7 for system] ********************\* 
no hosts matched or remaining

TASK: [set system profile] ********************\* 
no hosts matched or remaining

TASK: [set default timezone] ********************\* 
no hosts matched or remaining

PLAY RECAP ********************\* 
varnishpm01                    : ok=0    changed=0    unreachable=0    failed=1    

With gather_facts: false it's working

ansible -m works like a charm

**Comment by mpdehaan** [comment]
Thanks

sent ansible_python_interpreter=/path/to/correct/python as a host or group
variable and it will use the correct python.

It replaces the interpreter line on the fly when transferring the module.

**Comment by mpdehaan** [comment]
s/sent/set/

**Comment by czytom** [comment]
but on remote there is no correct python - there is only incorrect (for ansible) version 3.2

**Comment by mpdehaan** [comment]
Yeah, you are going to need a 2.x for now.

I'll accept patches to make the modules 3.x compliant if they don't break
anything else -- the modules must also run successfully on 2.4 and higher.

**Comment by czytom** [comment]
i can do on host: ansible -m raw -a 'emerge =dev-lang/python-2.7*' host
but when I'm embeding it in playbook I got mentioned problem

**Comment by czytom** [comment]
what I wanted to have is working playbook even if on remote host there is no python. It works with ansible command like you see above but it breaks on ansible-playbook

**Comment by mpdehaan** [comment]
Ah, that.

Yeah if you are just going to be using raw all the time and nothing else,
you can set gather_facts: False

(None of the other python modules will work though, obviously, and even
copy has a Python component to support idempotency and other details)

On Thu, Sep 27, 2012 at 8:36 AM, Krzysztof Tomczyk <notifications@github.com
