### ISSUE TITLE
docker_image: docker_version_api parameter returns 'unsupported parameter'

### ISSUE THREAD

**Issue by jameskyle** [ansible/ansible#11074]
```
- name: build the squid container
  docker_image: path="/Users/jkyle/Projects/Docker/docker-squid/" 
                name="jkyle/squid"
                state=present
                docker_api_version=1.17
```

Error: 

msg: unsupported parameter for module: docker_api_version

Im using the @devel branch updated as of this posting.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

i would expect this error as the docker_image module does not have that as an available parameter. That is supported by the docker module though.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by bcoca** [comment]
This PR is trying to add that parameter:
https://github.com/ansible/ansible-modules-core/pull/1411

**Comment by jameskyle** [comment]
My incentive for the parameter was getting a client/server API mismatch from docker_image....should I file a bug on that?
