### ISSUE TITLE
1.9.1 pip package doesn't contain proper extra modules

### ISSUE THREAD

**Issue by smoya** [ansible/ansible#11082]
An example is the `consul` module.
I checked the package downloading the source and the modules are not updated.
- **Issue Type**: Bug Report
- **Ansible Version**: 1.9.1 (pip)
- **Summary**: 1.9.1 pip package doesn't contain proper extra modules
- **Steps to reproduce**: Download the [latest release package](http://releases.ansible.com/ansible/ansible-latest.tar.gz) and check the extra modules dir. 
- **Expected Results**: consul module installed on 1.9.1 as official documentation says.
- **Actual Results**: `ERROR: consul is not a legal parameter in an Ansible task or handler`

**Comment by bcoca** [comment]
the consul module has been recently added to current devel, the release version will be 2.0, I'll update the module docs as it was submitted during 1.9 but did not get merged until after.

**Comment by bcoca** [comment]
I fixed via c223716bc7ccf2d0ac7995b36f76cca8ccd5bfda, docs will be refreshed on next scheduled update. Closing this ticket, also note that this is the wrong repo as the modules live in github.com/ansible/ansible-modules-extra
