### ISSUE TITLE
pass group var dict to role in playbook throws exception when hash_behaviour=merge

### ISSUE THREAD

**Issue by d-a-n** [ansible/ansible#11098]
When a variable is defined inside the playbook it gets passed to the role correctly. However when it's defined in `group_vars/all.yml` Ansilbe won't find it (undefined) and exits with an error:

`fatal: [vagrant] => failed to combine variables, expected dicts but got a 'dict' and a 'unicode'`

The unicode parameter is actually "`(Undefined,)`".

This only happens if hash_behaviour=merge.

```
# site.yml
vars:
  var_in_playbook: bar

roles:
  # this works
  - { role: test, my_role_var: "{{ var_in_playbook }}" }

  # this doesn't 
  - { role: test, my_role_var: "{{ var_in_group_vars }}" }
```

Is there any workaround to this issue?

**Comment by d-a-n** [comment]
It seems that this is the same as #11053

**Comment by jtktam** [comment]
maybe #11132 is related to this? how it handles group vars?

**Comment by bcoca** [comment]
where are your play, inventory and group_vars directory located?

**Comment by d-a-n** [comment]
@bcoca pretty much the default directory layout:

**group_vars/all.yml**

```
user:
  name: John
  email: debug@abc.com
```

**roles/test/tasks/main.yml**

```
- debug: var=my_role_var
```

**ansible.cfg**

```
[defaults]
gathering = smart
hash_behaviour=merge
```

**inv**

```
localhost ansible_connection=local
```

**play.yml**

```
---
- hosts: all

  vars_files:
    - vault.yml

  roles:
    - { role: test, my_role_var: "{{ user }}" }
```

**vault.yml**

```
user:
  pass: "123"
```

I would expect that the `user` dict will be joined and then passed to the role but running the play (`ansible-playbook -i inv play.yml`) will results in:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [test | debug var=my_role_var] ****************************************** 
fatal: [localhost] => failed to combine variables, expected dicts but got a 'dict' and a 'unicode'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/dev/play.retry

localhost                  : ok=1    changed=0    unreachable=1    failed=0 
```

This error is not thrown when `hash_behaviour=merge`is not set but then the user dict will not be merged obviously.

**Comment by d-a-n** [comment]
I think #9729 is also related.

**Comment by d-a-n** [comment]
@bcoca do you need more infos than the provided above?

Do you have any idea what could cause this error? I would really like to fix this myself but don't know where to start.

**Comment by bcoca** [comment]
what ansible/os/python version?

**Comment by d-a-n** [comment]
@bcoca I've tested on latest stable as well as on current development (v2) branch.

OSX 10.10.4 / Python 2.7.9

**Comment by bcoca** [comment]
can you change the variable from 'user'? It is a reserved keyword and might clash

**Comment by d-a-n** [comment]
yes, this is just an example. it happens with all my variables named differently.

**Comment by d-a-n** [comment]
@bcoca I've renamed the variable and uploaded the above play for easy reproduction of this issue: https://drive.google.com/file/d/0B_T7WQGumQLORlFvRTk4dFI1ZWM/view?usp=sharing

Just download and run with `ansible-playbook -i inv play.yml`.

**Comment by d-a-n** [comment]
@bcoca this issue still has the `needs_info` tag. What else is missing?

**Comment by d-a-n** [comment]
fixed in dev by https://github.com/ansible/ansible/commit/30c1a2d86192fedc706b43a76c26c6e4c31a6fe0
