### ISSUE TITLE
with_first_found search everywhere

### ISSUE THREAD

**Issue by debo** [ansible/ansible#11095]
Hey there, I decided to add some further information about `with_first_found` because I faced some problems with it during some experiments of mine and I noticed that other people are having issues using `with_first_found` and the way it looks for file.

It has been said that `with_first_found` and lookup in general looks into `./files/`, truth is that for what I noticed it looks in every single subdirectory of a role folder even when used with `include_vars`.

I hope this help to shed some light on the matter.

**Comment by bcoca** [comment]
this has been fixed in 2.2, it is now more 'intelligent' and defaults to vars/templates or files depending on the task at hand. You can still control the exact paths searched via the `paths` option.

**Comment by debo** [comment]
@bcoca thanks a lot for the update, appreciated and thanks for keep improving ansible.
