### ISSUE TITLE
Add this line to documentation?

### ISSUE THREAD

**Issue by jamarcus-deloitte** [ansible/ansible#1111]
Hi,
I was having some trouble installing on CentOS 5.8 today.  I was getting errors regarding ansible.runner when I ran ansible, instead of the help.

I found that running this from a git checkout fixed the issue:

python26 setup.py install

Hope this might be a good addition to the install doc.

James

**Comment by mpdehaan** [comment]
docs bugs go here:  https://github.com/ansible/ansible-docs (please refile it over there so it doesn't get lost)... Thanks!
