### ISSUE TITLE
allow variables to be used in host filters

### ISSUE THREAD

**Issue by aioue** [ansible/ansible#11128]
allow variables to be used in host filters
- hosts: all:!{{ some_var }}

Version
1.9.1

Currently does not replace the template var with variable data.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
