### ISSUE TITLE
Race condition in fetch module

### ISSUE THREAD

**Issue by jconway** [ansible/ansible#11126]
In ansible/lib/ansible/plugins/action/fetch.py at lines 128 and 129 there is a race condition.
128             if not os.path.isdir(os.path.dirname(dest)): 
129                 os.makedirs(os.path.dirname(dest)) 
If the destination directory does not exist, this code attempts to create it. However if multiple python threads are doing this simultaneously, it is possible for one thread to create the directory in the interval between the test on line 128 and the create on line 129. When that happens the losing thread throws:
  OSError: [Errno 17] File exists
Several solutions are discussed here: http://stackoverflow.com/questions/12468022/python-fileexists-error-when-making-directory

**Comment by bcoca** [comment]
test patch above, it should solve this issue and a few others that had the same cause.

**Comment by jconway** [comment]
Awesome -- thanks for such a quick response! It might not be possible to test patched version in the environment where I discovered this, but I will check. FWIW the patch looks good to me.
