### ISSUE TITLE
CLI become options are ultimately ignored

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#11136]
At this point I am not exactly sure where this is happening, however the become options provided on the CLI are ultimately ignored.

I have however determined that when `ConnectionInformation` is initiated, that the attributes are properly set via the 'set_options`method.  Immediately afterwards,`set_play`is executed and the options are set to`None`.

Commenting out the call to `set_play`, the attributes on `ConnectionInformation` remain correct, but by the time that `make_become_cmd` is executed, `self.become` has been set to `False`.

Other than `set_play` overwriting the variables when it probably shouldn't, I haven't been able to track down what else is setting `ConnectionInformation.become` to `False` before `make_become_cmd`.

**Comment by sivel** [comment]
I've made a small amount of progress.  It seems to stem from this line in the `Become` class:

```
_become              = FieldAttribute(isa='bool', default=False)
```

It appears as though this field is processed "late" and overrides an already Truthy value for `connection_info.become`.

I'm not super familiar with the new codebase yet, so I'm not sure where these `FieldAttribute`s are evaluated at.

**Comment by bcoca** [comment]
last time we encountered this issue was a question of precedence and how the values were merged
