### ISSUE TITLE
ansible_ssh_host is overriden

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#11130]
In `ansible.inventory.host` `ipv4_address` is set to the inventory_hostname.  https://github.com/ansible/ansible/blob/d1b43712870f5331a58abe115911725619264ca5/lib/ansible/inventory/host.py#L78

Later in `ansible.executor.task_executor._get_connection` `self._connection_info.remote_addr` is set to the `ipv4_address`.  https://github.com/ansible/ansible/blob/d1b43712870f5331a58abe115911725619264ca5/lib/ansible/executor/task_executor.py#L374

Before that re-assignment in `_get_connection`, `remote_addr` is correct, after that assignment, it is now the inventory_hostname.

I am not sure what the "correct" fix is, but removing the re-assignment in `_get_connection` seems to resolve the issue for me.

**Comment by bcoca** [comment]
closing via #11131
