### ISSUE TITLE
ImportError: No module named six.moves

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#11141]
##### Issue Type:

Bug Report
##### Ansible Version:

$ ansible --version
Traceback (most recent call last):
  File "/Users/tanner/projects/ansible.git/ansible/bin/ansible", line 39, in <module>
    from ansible.utils.display import Display
  File "/Users/tanner/projects/ansible.git/ansible/lib/ansible/utils/display.py", line 28, in <module>
    from ansible import constants as C
  File "/Users/tanner/projects/ansible.git/ansible/lib/ansible/constants.py", line 26, in <module>
    from six.moves import configparser
ImportError: No module named six.moves

$ git show
commit 3e2e81d896067170e72ca2999fe84c1ba81b9604
Author: Brian Coca <brian.coca+git@gmail.com>
##### Ansible Configuration:

Did June 3, 12:28am CDT

$ git pull
$ git submodule update --init --recursive
##### Environment:

OS X Yosemite 10.10.3
$ python --version
Python 2.7.6

$ pip freeze
ansible==2.0.0
ecdsa==0.13
epdb==0.12
httplib2==0.9
isodate==0.5.1
Jinja2==2.7.3
kerberos==1.2.2
MarkupSafe==0.23
nose==1.3.6
paramiko==1.15.2
passlib==1.6.2
pycrypto==2.6.1
pywinrm==0.0.3
PyYAML==3.11
xmltodict==0.9.2
##### Summary:

https://github.com/influxdb/influxdb-python/issues/6 says "...dependency on six is removed in 0.1.5" but after the pull I cannot get ansible to run
##### Steps To Reproduce:

$ git clone git@github.com:ansible/ansible.git
$ cd ansible
$ git pull; git submodule update --init --recursive
$ source hacking/env-setup
$ ansible --version
##### Expected Results:

Ansible version
##### Actual Results:

Traceback (most recent call last):
  File "/Users/tanner/projects/ansible.git/ansible/bin/ansible", line 39, in <module>
    from ansible.utils.display import Display
  File "/Users/tanner/projects/ansible.git/ansible/lib/ansible/utils/display.py", line 28, in <module>
    from ansible import constants as C
  File "/Users/tanner/projects/ansible.git/ansible/lib/ansible/constants.py", line 26, in <module>
    from six.moves import configparser
ImportError: No module named six.moves

**Comment by basictheprogram** [comment]
Installing six seems fix the "ansible --version" problem.

$ pip install six
Collecting six
  Using cached six-1.9.0-py2.py3-none-any.whl
Installing collected packages: six
Successfully installed six-1.9.0

$ ansible --version
ansible 2.0.0 (devel 3e2e81d896) last updated 2015/06/03 00:37:25 (GMT -500)
  lib/ansible/modules/core: (detached HEAD b138411671) last updated 2015/06/03 00:37:46 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 1276420a3a) last updated 2015/06/03 00:37:50 (GMT -500)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/03 00:37:54 (GMT -500)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/03 00:37:58 (GMT -500)
  configured module search path = None

But now all my plays that worked before the pull fail.

fatal: [www.*********.com]: FAILED! => {"failed": true, "exception": "Traceback (most recent call last):\n  File \"/Users/tanner/projects/ansible.git/ansible/lib/ansible/executor/process/worker.py\", line 118, in run\n    executor_result = TaskExecutor(host, task, job_vars, new_connection_info, self._new_stdin, self._loader, shared_loader_obj).run()\n  File \"/Users/tanner/projects/ansible.git/ansible/lib/ansible/executor/task_executor.py\", line 107, in run\n    res = self._execute()\n  File \"/Users/tanner/projects/ansible.git/ansible/lib/ansible/executor/task_executor.py\", line 211, in _execute\n    self._connection = self._get_connection(variables)\n  File \"/Users/tanner/projects/ansible.git/ansible/lib/ansible/executor/task_executor.py\", line 383, in _get_connection\n    if sys.platform.startswith('darwin') and self._connection_info.remote_pass:\nAttributeError: 'ConnectionInformation' object has no attribute 'remote_pass'\n", "stdout": ""}

**Comment by bennojoy** [comment]
#11140 seems to fix it

**Comment by basictheprogram** [comment]
Does that mean six is now a requirement for ansible? #11140 seems to fix the ssh problem but not the six.moves problem (unless I have six installed)

**Comment by sivel** [comment]
Yes, six is a dependency for ansible now, and is already listed in setup.py as well as the packaging instructions.

**Comment by basictheprogram** [comment]
I see it in setup.py but I think the documentation needs to be updated.

http://docs.ansible.com/intro_installation.html

Ansible also uses the following Python modules that need to be installed:

$ sudo pip install paramiko PyYAML Jinja2 httplib2

**Comment by bcoca** [comment]
the doc site doesn't  get updated immediately on change, we normally do it a couple of times per week, it should be updated soon.

**Comment by lucasrodes** [comment]
I am having the same problem, but since I do not have root privileges I cannot simply install six. What should I do? Thanks!

**Comment by basictheprogram** [comment]
Install stuff in a different location, where you have write access?

http://bit.ly/1T1Gv32
Installing Python Modules

I run everything in virtualenv.

> On May 9, 2016, at 1:00 PM, Lucas Rodés notifications@github.com wrote:
> 
> I am having the same problem, but since I do not have root privileges I cannot simply install six. What should I do? Thanks!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub https://github.com/ansible/ansible/issues/11141#issuecomment-217939943

## 

Bob Tanner tanner@real-time.com                                 | Phone : 952-943-8700
http://www.real-time.com, Linux, OSX, VMware, Windows | Fax      : 952-943-8500
Key fingerprint = 9906 320A 8BB6 64AD 96A7  7785 CBFB 10BF 568B F98C
