### ISSUE TITLE
Fast Forward Function / Feature

### ISSUE THREAD

**Issue by xrow** [ansible/ansible#11145]
Hi,

I have been using ansible now for a couple of months. My problem is that playbooks get bigger and bigger and execution gets longer and longer. It would be good to have some kind of fast forward function / goto function for debugging. On each playbook run I need to wait 2 minutes to see the result. That doesn`t make me efficent. I want to jump directly to a certain task / role and skip the onces from before and maybe ignore dependancies. The play book command could be altered with on option. 

What do you think?

**Comment by tgerla** [comment]
The --start-at-task option should do exactly this.

**Comment by xrow** [comment]
WOW, Thanks.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by xrow** [comment]
I will...
