### ISSUE TITLE
Enhancement: Option to add -o in SSH parameters. 

### ISSUE THREAD

**Issue by ashish235** [ansible/ansible#11160]
I 've an automation use case where I need to ssh into hosts using password without manual intervention. This is possible only when I add -oStrictHostKeyChecking=no to my SSH command. Using Ansible I can't add this parameter to my inventory file. Will -o be supported in future releases?

**Comment by bennojoy** [comment]
Hi 

you can set ssh paramaters in ansible.cfg    http://docs.ansible.com/intro_configuration.html#ssh-args and also set host check vai http://docs.ansible.com/intro_configuration.html#host-key-checking

Also 

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!

**Comment by ashish235** [comment]
@bennojoy, thanks it helped. I 'd like to tell you that I 'm loving Ansible. Cheers!
