### ISSUE TITLE
sudo password broken after v2 modules merge

### ISSUE THREAD

**Issue by agunnerson-ibm** [ansible/ansible#11169]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 2.0.0 (devel f3f3fb7c49) last updated 2015/06/04 14:13:40 (GMT -400)
  lib/ansible/modules/core: (detached HEAD b138411671) last updated 2015/06/04 14:01:51 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 1276420a3a) last updated 2015/06/04 14:01:52 (GMT -400)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/02 10:07:39 (GMT -400)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/02 10:07:43 (GMT -400)
  configured module search path = None
```
##### Ansible Configuration:

Nothing has been changed. The inventory file is a simple file with a single IP with no host/group variables.
##### Environment:

Tested in Ubuntu 15.04 and OSX 10.10, but very likely affects all OS's.
##### Summary:

Ever since the v2 modules merge, using sudo with a password no longer works. It simply hangs until sudo times out. ~~This is likely due to code that was commented out during the v1 -> v2 transition: https://github.com/ansible/ansible/blob/f3f3fb7c491effe9e61ae5a429ac796558c2963a/lib/ansible/plugins/connections/ssh.py#L313~~
##### Steps To Reproduce:

Run any ansible command with `-K --sudo`.
##### Expected Results:

Ansible uses sudo password and runs the command successfully.
##### Actual Results:

Hangs until sudo times out. For example:

```
ansible -i inventories/docker-centos docker-centos -a 'echo hello!' -Kk --sudo -u centos -vvvv
SSH password:
SUDO password[defaults to SSH password]:
<A.B.C.D> ESTABLISH CONNECTION FOR USER: centos on PORT 22 TO A.B.C.D
<A.B.C.D> EXEC mkdir -p $HOME/.ansible/tmp/ansible-tmp-1433441710.88-220550492594694 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1433441710.88-220550492594694 && echo $HOME/.ansible/tmp/ansible-tmp-1433441710.88-220550492594694
<A.B.C.D> PUT /var/folders/kt/pybkvyxx1wd8817w14c6j244b_vsfb/T/tmpveHrr4 TO /home/centos/.ansible/tmp/ansible-tmp-1433441710.88-220550492594694/command
<A.B.C.D> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=ghlibrayvgtoraakhczsmedaybcuklmn] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-ghlibrayvgtoraakhczsmedaybcuklmn; LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/centos/.ansible/tmp/ansible-tmp-1433441710.88-220550492594694/command; rm -rf /home/centos/.ansible/tmp/ansible-tmp-1433441710.88-220550492594694/ >/dev/null 2>&1'"'"''
A.B.C.D | FAILED! => {u'msg': u'[sudo via ansible, key=ghlibrayvgtoraakhczsmedaybcuklmn] password: \r\n', u'failed': True, u'changed': False, u'parsed': False, u'invocation': {u'module_name': u'command', u'module_args': {u'_raw_params': u'echo hello!'}}}
```

**Comment by sivel** [comment]
I believe this is due to 2 things.

`self._connection_info.become_pass` is set to `False` by the time it is needed.  Not sure of the cause there.

Also, I believe that sudo/su/become functionality for passworded become has only been implemented in the `paramiko` connection plugin at this point, and not the `ssh` connection plugin.

**Comment by agunnerson-ibm** [comment]
@sivel Thanks for the reply!

I haven't taken a close look at the code yet, so I'm not too sure (I was just looking at a diff between v1 and v2). As far as the connection plugin, I am using `paramiko`. With `ssh`, I get:

```
ansible -i inventories/docker-centos docker-centos -a 'echo hello!' -Kk --sudo -u centos -vvvv -c ssh
SSH password:
SUDO password[defaults to SSH password]:
<A.B.C.D> ESTABLISH SSH CONNECTION FOR USER: centos
A.B.C.D | FAILED! => {'msg': u"ERROR! to use the 'ssh' connection type with passwords, you must install the sshpass program", 'failed': True}
```

**Comment by lekum** [comment]
The same faulty behavior described happens when using a `local` connection with `-K` option.

**Comment by sivel** [comment]
The local plugin, does not have that functionality implemented either.

I just submitted #11183 which prevents `become_pass` from being emptied.  This leads us to another set of issues:

1) `success_key` and `prompt` are not passed to `exec_command` of the connection plugin
2) `check_su_prompt` no longer exists in v2, and I am not sure of the reason yet.

**Comment by bcoca** [comment]
@sivel ... 'on my list, to be implemented'

**Comment by bcoca** [comment]
so as of now ssh, paramiko and local should all support all privilege escalation methods they supported before (local still does not support su, but it did not do so before either).

**Comment by agunnerson-ibm** [comment]
Can confirm that it is working with the `ssh` connection type. EDIT: This is with `sudo`

```
ansible 2.0.0 (devel ff251a0dcc) last updated 2015/06/22 10:55:56 (GMT -400)
  lib/ansible/modules/core: (detached HEAD cf273bbaeb) last updated 2015/06/22 10:56:04 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD dd6e8f354a) last updated 2015/06/22 10:56:04 (GMT -400)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/02 10:07:39 (GMT -400)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/02 10:07:43 (GMT -400)
  configured module search path = None
```
