### ISSUE TITLE
Add DOCUMENTATION docstring to all modules

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1116]
This is a tracker ticket for completing the docs work.

This includes some modules that are just action plugins /stubs.

cc @jpmens 

(We should also integrate the manpage builder part of the script once complete, but not until then)

**Comment by mavimo** [comment]
Status on:
- https://docs.google.com/a/agavee.com/spreadsheet/ccc?key=0Aq4q7nXKMUBzdGt1dWFmWTFwNGlBLWt3LU1UNGo1MWc&pli=1#gid=0

PS: all user can change the status and track update

**Comment by jpmens** [comment]
Very useful, thanks!

**Comment by mavimo** [comment]
You can also see the translations status / preview for web interface on:
- http://agavee.com/ansible-docs/

**Comment by jpmens** [comment]
Just seven more to go!

**Comment by jpmens** [comment]
Except for `async_status` they're all complete and look pretty much OK.

@mpdehaan You added `async_wrapper` to the BLACKLIST in `module_formatter`, so I a) am not entirely sure what to do about `async_status` and b) don't really have a clue what to write about it ...

I'll add DOCUMENTATION to it, basically just with a link to the doc page.

**Comment by mpdehaan** [comment]
I think this one is basically done save for a final review pass by me and whatever tweaks we want.  A huge thanks for getting this together, this will save a lot of work in the future and also opens up lots of neat options.

**Comment by mpdehaan** [comment]
Yep, we're all done now.

I'll make a review pass a bit later, thanks everyone for all the hard work!
  This will make future module documentation efforts much much easier and
also enables the manpage/PDF doc options!

**Comment by mpdehaan** [comment]
things look good, manpages are checked in and generated docs are live.
