### ISSUE TITLE
ansible-galaxy install throws an error when the role-file option is used.

### ISSUE THREAD

**Issue by bandesz** [ansible/ansible#11179]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 2.0.0 (devel a4ebee4b16) last updated 2015/06/05 11:02:21 (GMT +000)
  lib/ansible/modules/core: (detached HEAD b138411671) last updated 2015/06/05 11:02:40 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 1276420a3a) last updated 2015/06/05 11:03:14 (GMT +000)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/05 11:04:10 (GMT +000)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/05 11:04:48 (GMT +000)
  configured module search path = None
```
##### Environment:

Debian 8.0
##### Summary:

ansible-galaxy install throws an error when the role-file option is used.
##### Steps To Reproduce:

```
$ ansible-galaxy install -r requirements-roles-3rd.yml -p ./roles-3rd/
```
##### Expected Results:

Great success. 
##### Actual Results:

```
Traceback (most recent call last):
  File "/home/vagrant/ansible/bin/ansible-galaxy", line 66, in <module>
    sys.exit(cli.run())
  File "/home/vagrant/ansible/lib/ansible/cli/galaxy.py", line 134, in run
    self.execute()
  File "/home/vagrant/ansible/lib/ansible/cli/__init__.py", line 96, in execute
    fn()
  File "/home/vagrant/ansible/lib/ansible/cli/galaxy.py", line 321, in execute_install
    role_name = self.args.pop(0).strip()
IndexError: pop from empty list
```

**Comment by bcoca** [comment]
I had not finished implementing all galaxy functions, this is high on my todo list.

**Comment by dkinzer** [comment]
I'm getting this same error: 

```
#ansible --version:
ansible 2.0.0 (devel 4705a79a98) last updated 2015/06/16 11:04:58 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 9acc7c402f) last updated 2015/06/16 11:05:01 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 2f967a949f) last updated 2015/06/16 11:05:03 (GMT -400)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/16 11:05:04 (GMT -400)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/16 11:05:06 (GMT -400)
  configured module search path = None
#uname
Linux linux 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bcoca** [comment]
expected, as I mentioned above this has not been implemented yet

**Comment by chouseknecht** [comment]
@bcoca - started looking into [11548](https://github.com/ansible/ansible/issues/11548) and ended up here. After getting past the error on line 321 (Index error: pop form empty list) I hit the missing 'role_yaml_parse', which used to be part of ansible.utils.  

Guessing maybe things are not completely done with the move to v2. I'm way out of the loop as far as the strategy with the bits left in v1/utils.  Is there anything I can do to help? 

Would love to chat and catch up. Will be starting back at Ansible on 7/20 to work on Galaxy.  In the meantime, feel free to reach out to me - chouseknecht at gmail.

--Chris

**Comment by bcoca** [comment]
v1/ is there for testing convenience, it won't survive the release of 2.0 and won't be included anywhere, this was left so people did not have to switch to the last_v1 tag to test if an issue was cause by the v2 engine.

I'll get back to this next week and see where we are at, some people had already started adding this back.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
