### ISSUE TITLE
source v1/hacking/env-setup python: can't open file 'setup.py'

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#11171]
As discussed here: https://goo.gl/tsZ4CM
##### Issue Type:

Bug Report
##### Ansible Version:

$ ansible --version
ansible 2.0.0 (devel f3f3fb7c49) last updated 2015/06/04 14:11:06 (GMT -500)
  lib/ansible/modules/core: (detached HEAD b138411671) last updated 2015/06/03 00:37:46 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 1276420a3a) last updated 2015/06/03 00:37:50 (GMT -500)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/03 00:37:54 (GMT -500)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/03 00:37:58 (GMT -500)
  configured module search path = None
##### Ansible Configuration:

$ git pull; git submodule update --init --recursive
##### Environment:

OS X Yosemite 10.10.3

$ python -V
Python 2.7.6

$ pip freeze
ansible==2.0.0
ecdsa==0.13
epdb==0.12
httplib2==0.9.1
isodate==0.5.1
Jinja2==2.7.3
kerberos==1.2.2
MarkupSafe==0.23
nose==1.3.7
paramiko==1.15.2
passlib==1.6.2
pycrypto==2.6.1
pywinrm==0.0.3
PyYAML==3.11
six==1.9.0
xmltodict==0.9.2
##### Summary:

source v1/hacking/env-setup cannot find the setup.py

In the posting at https://goo.gl/tsZ4CM it says, "...  switch back to using the old v1 codebase from a git checkout, simply source the hacking script in the v1 directory instead:" 
##### Steps To Reproduce:

$ source v1/hacking/env-setup
python: can't open file 'setup.py': [Errno 2] No such file or directory

Setting up Ansible to run out of checkout...
##### Expected Results:

Be able to use the v1 ansible code base
##### Actual Results:

python: can't open file 'setup.py': [Errno 2] No such file or directory

**Comment by sivel** [comment]
Does that prevent you from being able to use v1?  It doesn't affect me.

**Comment by sivel** [comment]
From the mailing list it sounds like ansible will work from the v1 directory without the setup.py.  Since this is just a temporary thing (having a v1 directory), and setup.py doesn't seem to affect anything, I'd suggest we don't worry about it.

**Comment by basictheprogram** [comment]
After the last git pull everything is working as expected, even without the setup.py.

**Comment by bcoca** [comment]
closing as 'working now'
