### ISSUE TITLE
MAC-OS issue 

### ISSUE THREAD

**Issue by Moody210** [ansible/ansible#11191]
I tried to install Ansible to MAC-OS V10.9.5 but I always received the below error 
$ ansible all -m ping --ask-pass
SSH password: 
localhost | FAILED! => {'msg': u"ERROR! The module ping was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem.", 'failed': True}
$ 

Any clue

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case, there are the instructions for installing Ansible: http://docs.ansible.com/intro_installation.html

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
