### ISSUE TITLE
Is there a way to skip handlers?

### ISSUE THREAD

**Issue by dcodix** [ansible/ansible#11195]
I am trying to reuse all playbooks and roles in 2 different scenarios:
1) Maintain the config in all the servers.
2) Create AMIs with that config.

In an autoscaling environment I will be able to generate AMIs with the new configs and easily substitute the old instances with the new AMI, but for really small changes I would like to be able to apply them directly on the running servers. I also want to be able to apply them directly on the servers in emergency cases.

The problem I am facing is that in the AMI creation I don't want to start o restart services, I don't want the handlers to be executed.

For now I tried tagging the handlers and skip the tag, but the handler runs anyway. I also tried to use a "when" clause on the handler with a variable defined by me, but it also runs anyway.

So, is there any way I can stop handlers from running when I am creatig AMIs ?
If there isn't I think it would be a great feature to be able to have a bit more control of handlers.

Thanks!

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
