### ISSUE TITLE
Fork doesn't appear to work

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#112]
We are working with ansible to bring some semblance of automation into our infrastructure, in all, its a pretty nice project. 

However we have noticed that using fork doesn't appear to make a difference in execution time. Perhaps it is a mis-understanding of how fork should work, but if we are copying files, shouldn't it open the connection, start the transfer and move to the next one?
What we are noticing is ansible waits for the transfer to complete before moving on.

This isn't really an urgent issue, but if you have a chance to look at it, that would be great. Thanks :)

**Comment by mpdehaan** [comment]
Outstanding catch.   Thanks very much.

At some point in the past we refactored the runner loop to avoid a multiprocessing glitch, and the join loop was executing in the for loop, not outside.  I've pushed a fix to correct this.

Thanks!

**Comment by mpdehaan** [comment]
.

**Comment by ghost** [comment]
awesome, thanks :)
