### ISSUE TITLE
ec2_asg documentation wrongly declares the launch_config_name atribute as not required

### ISSUE THREAD

**Issue by igoratencompass** [ansible/ansible#11209]
When using ec2_asg I get:

TASK: [ec2_asg ] **************************************************************
failed: [localhost] => {"failed": true}
msg: Missing required arguments for autoscaling group create/update: launch_config_name

where is in the module man page:

http://docs.ansible.com/ec2_asg_module.html

this attribute is listed as not required.

This is on Ansible 1.9.1

**Comment by gregdek** [comment]
The docs are auto-generated by the code. 

@igoratencompass maybe you could try your hand at a patch. :)

https://github.com/ansible/ansible-modules-core/blob/devel/cloud/amazon/ec2_asg.py#L46

(Although it's possible that the behavior here is more complex, where it's required in some cases but not in others -- worth taking a look.)
