### ISSUE TITLE
Unrelated env vars can break Ansible templates

### ISSUE THREAD

**Issue by cespare** [ansible/ansible#11203]
This broke when we upgraded from 1.7.2 to 1.9.1.

```
$ cat > wat.yml

---
- hosts: localhost
  tasks:
    - local_action: template src=wat.j2 dest=/tmp/wat.txt
$ cat > wat.j2
hello
$ ansible-playbook wat.yml

PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
ok: [127.0.0.1]

TASK: [template src=wat.j2 dest=/tmp/wat.txt] *********************************
changed: [127.0.0.1 -> 127.0.0.1]

PLAY RECAP ********************************************************************
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0

$ foobar='{%a' ansible-playbook wat.yml

PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
ok: [127.0.0.1]

TASK: [template src=wat.j2 dest=/tmp/wat.txt] *********************************
Failed to template {%a: template error while templating string: Encountered unknown tag 'a'.
fatal: [127.0.0.1 -> 127.0.0.1] => Failed to template {%a: template error while templating string: Encountered unknown tag 'a'.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/caleb/wat.retry

127.0.0.1                  : ok=1    changed=0    unreachable=1    failed=0
```

**Comment by bcoca** [comment]
do you have a lookup('env', 'foobar') ?

**Comment by cespare** [comment]
@bcoca no. That is an entire repro; there is no other code involved.

**Comment by jhawkesworth** [comment]
I'm not familiar with the syntax in this command line.  Can you explain
what it is intended to do:

   foobar='{%a' ansible-playbook wat.yml

**Comment by bcoca** [comment]
it just declares the foobar variable for that command, no need to export it
to make it available for others.

**Comment by cespare** [comment]
(Not that it matters, but the reason I ran into this was my ZSH prompt configuration means I have some color escape sequences in a variable `$vcs_info_msg_0_`.)

**Comment by abadger** [comment]
For some reason, your recipe doesn't produce an error for me.  I pasted directly from your initial comment but it just works, no error.  Can you think of anything else that might be special about your playbook or environment?  Does this also occur if you run from a different user account?

**Comment by cespare** [comment]
@abadger thanks for the info; I reproed on several machines but they all had the same Ansible config. After reading your comment I tried on a fresh machine and I now see that this problem only happens when this line is in our inventory file:

```
[localhost]
127.0.0.1 ansible_connection=local
```

It seems that this is no longer needed in Ansible 1.9.1 and so I've removed it.

I see that the problem still happens if I use `hosts: localhost` but not `local_action`, like this:

```
# wat.yml
---
- hosts: localhost
  tasks:
    - template: src=wat.j2 dest=/tmp/wat.txt
```

**Comment by jimi-c** [comment]
@cespare can you also try this on the latest devel branch? There have been a lot of improvements there as well, which should prevent errors like this from occurring.

**Comment by cespare** [comment]
Can't repro anymore on devel. Thanks.

**Comment by jimi-c** [comment]
Thanks for following up!
