### ISSUE TITLE
running `vncserver' with Ansible gave different result than running it directly via SSH

### ISSUE THREAD

**Issue by zym1010** [ansible/ansible#11211]
## background

I have a shell script that tries to restart a vncserver (tightvncserver + xfce4) on my vagrant machine (Ubuntu 12.04 server, https://atlas.hashicorp.com/ubuntu/boxes/precise64):

```
#!/bin/bash
vncserver -kill :3
sleep 3
vncserver :3
sleep 3
```

which is saved to `~/restart_vncserver.sh`.
## problem

I tried two ways to run this script.
1. `vagrant ssh` then `./restart_vncserver.sh`, which works as expected, giving me xfce desktop when accessing the computer through port 5903 and `vnc:` protocol.
2. write a playbook containing line `shell: ~/restart_vncserver.sh`, which didn't give expected result, giving me gray screen when accessing the computer.

After running script through Ansible (method 2), the log file `~/.vnc/vagrant-ubuntu-precise-64:3.log` gives following error lines, compared to the log file after running script through SSH (method 1).

```
xscreensaver: 04:56:45: SIGHUP received: restarting...
xscreensaver: 04:56:45: running as vagrant/vagrant (1001/1001)

xfwm4: Fatal IO error 11 (Resource temporarily unavailable) on X server :3.0.
xfdesktop: Fatal IO error 11 (Resource temporarily unavailable) on X server :3.0.
```

I also tried other modules, like `raw, command`, or send command through `ansible`, or another box (`ubuntu/precise64`) and none of them worked.
## More details.

I installed `build-essential, automake, checkinstall` and  `xfce4, xfce4-goodies, tightvncserver, gnome-icon-theme-full, firefox`, and `expect` using Ansible playbooks before running the above script, and the xstartup file is as follows.

```
#!/bin/bash
xrdb "$HOME/.Xresources"
startxfce4 &
```

**Comment by bennojoy** [comment]
Hi!

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

It seems like a problem with tty disconecting, can you try adding ' nohup' to the script. or not let the tty disconnect by adding   async:99999999 (high value) and poll: 0

Also This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!

**Comment by zym1010** [comment]
Thanks, it indeed works!
I will send such things to Google group next time. Sorry I am new to Ansible and have no idea what constitutes a general bug and what's a more specific issue.
