### ISSUE TITLE
ansible_distribution is "NA" on Arch Linux

### ISSUE THREAD

**Issue by remexre** [ansible/ansible#11216]
```
$ ansible localhost -m setup -a 'filter=ansible_distribution'
127.0.0.1 | success >> {
    "ansible_facts": {
        "ansible_distribution": "NA"
    }, 
    "changed": false
}
```

**Comment by bcoca** [comment]
I cannot reproduce this in the latest stable or current devel

**Comment by remexre** [comment]
On Arch Linux, with:

```
$ ansible --version
ansible 1.9.1
  configured module search path = None
$ pacman -Q ansible 
ansible 1.9.1-2
```

**Comment by bcoca** [comment]
try in latest devel, should be fixed via f174682e1903e246c9f7389e2e76ffcca4a04c28

**Comment by bcoca** [comment]
funny thing, the bug was only present in devel, not in 1.9.1

**Comment by remexre** [comment]
Arch Linux's `platform.dist()` and `platform.linux_distribution()` return `('', '', '')` with Python 2.
[https://bugs.python.org/issue20454](https://bugs.python.org/issue20454)

**Comment by bcoca** [comment]
The code does not depend only on that, my change just ensures not to ovewrite valid data if it is already there. I tested the fact gathering and it correctly identifies the machines as 'Archlinux' distribution.

**Comment by remexre** [comment]
Ok, thanks then.
