### ISSUE TITLE
win_copy and win_file documented but missing

### ISSUE THREAD

**Issue by slimandslam** [ansible/ansible#11220]
The win_copy and win_file modules are documented as existing but they are missing from the latest release of Ansible (v 1.9.1)

http://docs.ansible.com/win_copy_module.html
http://docs.ansible.com/win_file_module.html

J

**Comment by bcoca** [comment]
the version added is incorrect, these have been added in 2.0, but were submitted when 1.8 was about to be released, hence the doc mistake.

**Comment by bcoca** [comment]
fixed via commit 16ba1fc0e97a7e25d6c70862c3264fb028454b15 in http://github.com/ansible/ansible-modules-core repo

**Comment by jhawkesworth** [comment]
Hmm..., unfortunately there was a bug reported with that version of
win_copy - https://github.com/ansible/ansible-modules/core/issues/1404 -
which I have fixed via 2 PRs:

https://github.com/ansible/ansible/pull/11115
and
https://github.com/ansible/ansible-modules-core/pull/1438

now the second PR has merge conflicts.

@bcoca - what's the best way forward - unmerging 384 or fixing the 1438
merge conflict?

**Comment by bcoca** [comment]
just rebase, the conflict is my fault due to the docs update, your version added is actually correct and not mine (2.0)

**Comment by jhawkesworth** [comment]
ok will rebase, thanks

**Comment by jhawkesworth** [comment]
done, but realised i favoured the wrong version number while rebasing so just pushed another commit.  must stop trying to get stuff done on the train.  Hope multiple commits ok, do you need me to squash?
