### ISSUE TITLE
known_hosts module doesn't work

### ISSUE THREAD

**Issue by holms** [ansible/ansible#11222]
### Issue type:

bug report
### Ansible Version:

```
$ ansible --version
ansible 1.9.1
  configured module search path = None
```
### Environment:

OSX Yosemite: 10.10.2 (14C1514)
Ansible Installed from Pip
### Summary:

First of all I'm not sure how to use it, as provided example not something I need. Second thing it seems to be doesn't create a file, third it seems to be can't receive server key by itself which seems to be insanely wrong to me. If we have dedicated module for known_hosts why not to do everything at once?

Anyway the problem is they way I use it doesn't work for me.
### Steps To Reproduce:

```
- name: App | Tell the host about our servers it might want to ssh to
  known_hosts: path='/root/.ssh/known_hosts' host='bitbucket.org' key="AAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw=="
```
### Expected Results:

Should work with no question.
### Actual Results:

```
TASK: [shrinktheapp | App | Tell the host about our servers it might want to ssh to] ***
failed: [staging.shrinktheapp.com] => {"cmd": "/usr/bin/ssh-keygen -F bitbucket.org -f /tmp/tmpJEJhlp", "failed": true, "rc": 1}
stderr: line 1 missing key: AAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrg...
/tmp/tmpJEJhlp is not a valid known_hosts file.

msg: line 1 missing key: AAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrg...
/tmp/tmpJEJhlp is not a valid known_hosts file.

```

**Comment by bcoca** [comment]
this is not the correct repo for this issue, you want http://github.com/ansible/ansible-modules-extras
