### ISSUE TITLE
Using ~ user shortcut for ssh config file argument in ssh_args doesn't find ssh config.

### ISSUE THREAD

**Issue by marcus-ahle** [ansible/ansible#11224]
### Issue Type:

Bug Report
### Ansible Version:

1.8.4
### Ansible Configuration:

Default out of box
### Environment:

OSX 10.10
### Summary:

I created `ansible.cfg` and it resides at the level of playbooks. It contains:

```
[defaults]
host_key_checking = False
timeout = 60

[ssh_connection]
ssh_args = -F ~/.ssh/aws-ssh-config
```

When I run my playbook I get the following error:

```
fatal: [10.0.6.212] => SSH encountered an unknown error. The output was:
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
Can't open user config file ~/.ssh/aws-ssh-config: No such file or directory
```

If I change `ansible.cfg`to:

```
[defaults]
host_key_checking = False
timeout = 60

[ssh_connection]
ssh_args = -F /Users/username/.ssh/aws-ssh-config
```

it works fine.

I can also ssh successfully without error by doing `ssh -F ~/.ssh/aws-ssh-config 10.0.6.212`
### Steps To Reproduce:
- Create an ssh config in your user's ssh directory (if one doesn't exist)
- Create ansible.cfg and supply `ssh_args = -F ~/.ssh/configfilename`
- Attempt to run playbook using supplied ssh args
- Change ansible.cfg to use the full path to your ssh config rather than with the ~
- Attempt to run playbook and notice that it works.
### Expected Results:

The playbook should be able to SSH successfully.
### Actual Results:

SSH fails with the following message:

```
fatal: [10.0.6.212] => SSH encountered an unknown error. The output was:
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
Can't open user config file ~/.ssh/aws-ssh-config: No such file or directory
```

**Comment by sivel** [comment]
So, this is an SSH issue rather than ansible, as SSH does not allow use of `~` in the path to the config file.  The shell is responsible for expanding the `~`.  It would require ansible iterating through the `ssh_args` and trying to turn everything into full paths.

**Comment by marcus-ahle** [comment]
Ahh, yes. Good catch on that. Closing this as that request is out of scope.
