### ISSUE TITLE
ansible 2.0.0 ignoring private-key option. 

### ISSUE THREAD

**Issue by rexroof** [ansible/ansible#11227]
ansible -i temp_inventory -u root --private-key=keyfile_rsa -m ping all

works in ansible 1.9.1 and I see -o IdentityFile="keyfile_rsa" in the -vvvv output.

With ansible 2.0.0  (devel f2934eeb0a) the same exact command fails and the -vvvv output doesn't contain the keyfile in any output.

**Comment by sivel** [comment]
This is addressed in https://github.com/ansible/ansible/pull/11163

**Comment by bcoca** [comment]
fixed through merge of #11163
