### ISSUE TITLE
Is there way to log realtime output of commands to logfile?

### ISSUE THREAD

**Issue by shuogawa** [ansible/ansible#11233]
I know that ansible can not show realtime output of commands to user consle.
#3887

But I want to see realtime output of commands.

My solution is 

```
- shell: "echo '( \
  make very_long_time \
)' | /bin/bash -x 2>&1 | tee -a /tmp/ansible.log"
```

This solution works well.

But this supports only shell module.

Is there way to log realtime output of commands to logfile for all modules?

**Comment by shuogawa** [comment]
Sorry, My solution can not detect error status.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case, ansible already logs what it runs on the target server, you can add a ansible.log to the master with that information also through a setting in ansible.cfg, another option is using a callback plugin that logs to syslog.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
