### ISSUE TITLE
Jinja filter password_hash does not work correctly

### ISSUE THREAD

**Issue by saminiemi** [ansible/ansible#11244]
Hi!

I have tried to generate encrypted password hash with password_hash filter. But it gives me wrong results.

Test playbook:

```
- hosts: default
  connection: local
  tasks:
    - debug: msg="Pass {{ 'exampletext' | password_hash('sha512')  }}"
```

I got result:
debug msg="Pass $6FTpWXL4Wvg."

When encrypted string should be something like:
$6$djcPQAXy$EQkcQoFE9LjCJrUfF2mC9adJU.4HLvhx0.I4iSGbSinuhmj/F88l/QYFfcC73qcjOhGKH4UCAjqqiVqbH/jSE/

I have got same kind result with sha1, sha256 filters also.

My Ansible version is 1.9.1, on osx yosemite.

Any help would be appreciate!

Br,
Sami Niemi

**Comment by bcoca** [comment]
I don't have OS X, but cannot reproduce this on any version of linux or bsd.

this does depend on the underlying python supporting the hash methods, can you try:
`python -c 'import crypt; print crypt.crypt("exampletext", "$6$mysalt$")'`

**Comment by bennojoy** [comment]
it seems like crypt in osx  uses 'des' https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/crypt.3.html

using passlib if installed on the machine might be the way to go here

**Comment by bcoca** [comment]
we avoided passlib due to other compatibility issues and it not being universally installed, we might need to do some conditional magic for the OS X case, I would also open a bug with Apple as DES has been outdated for so long even the mention of it being outdated seems outdated.

**Comment by saminiemi** [comment]
Thanks for nice answers. I could reproduce problem with a line bcoca gave: 
~% python -c 'import crypt; print crypt.crypt("exampletext", "$6$mysalt$")'
$6FTpWXL4Wvg.

On same time on our Debian production enviroment command gives us a proper result. So we can live with this but sure it would be nice to get it work on OS X. Compared to earlier solutions for password encrypting on Ansible, password_hash filter seems to be very convient way.

Br,
Sami

**Comment by sivel** [comment]
@saminiemi A commit was just merged into devel which will require the python passlib module for `password_hash` when running on OS X.  See #11251 

This will be included in the upcoming Ansible 2.0 release.

**Comment by mihai-satmarean** [comment]
I  get similar problems on Centos7 but a bit different scenario:

When I am changing/setting a password using vars_prompt and 

```
  vars_prompt:
    - name: "newpass"
       prompt: "Enter a password for the user"    
       private: yes    
       confirm: yes     

  tasks:
    - name: Change user password
      user: name={{ uuser }} password="{{ newpass | password_hash('sha512')  }}"
```

the password that is set is not working.

But if the same variable is passed as an extra-vars parameter it is working.

**Comment by glaszig** [comment]
in the meantime, for anybody waiting for ansible 2.0: [a passlib filter plugin](https://gist.github.com/glaszig/1ba07d81d010b653f92d) i quickly threw together.

**Comment by dankeder** [comment]
@glaszig Your passlib filter plugin works flawlessly, thank you!
