### ISSUE TITLE
{{ lookup('file','xxx') }} not working at all in v2

### ISSUE THREAD

**Issue by jaseclamp** [ansible/ansible#11243]
echo "test" > test
cat playbook.yml

```

---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: test
    debug: msg="file contents is {{ lookup('file', 'test') }}"
```

ansible-playbook playbook.yml -vvv

TASK [test] *********************************************************************
ESTABLISH LOCAL CONNECTION FOR USER: jaseclamp
fatal: [localhost]: FAILED! => {"failed": true, "exception": "Traceback (most recent call last):\n  File \"/Library/Python/2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/executor/process/worker.py\", line 118, in run\n    executor_result = TaskExecutor(host, task, job_vars, new_connection_info, self._new_stdin, self._loader, shared_loader_obj).run()\n  File \"/Library/Python/2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/executor/task_executor.py\", line 107, in run\n    res = self._execute()\n  File \"/Library/Python/2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/executor/task_executor.py\", line 226, in _execute\n    self._task.post_validate(templar=templar)\n  File \"/Library/Python/2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/playbook/task.py\", line 191, in post_validate\n    super(Task, self).post_validate(templar)\n  File \"/Library/Python/2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/playbook/base.py\", line 258, in post_validate\n    value = templar.template(getattr(self, name))\n  File \"/Library/Python/2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/template/__init__.py\", line 176, in template\n    d[k] = self.template(v, convert_bare=convert_bare)\n  File \"/Library/Python/2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/template/**init**.py\", line 158, in template\n    result = self._do_template(variable, preserve_trailing_newlines=preserve_trailing_newlines)\n  File \"/Library/Python/2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/template/__init__.py\", line 268, in _do_template\n    res = j2_concat(rf)\n  File \"<template>\", line 9, in root\n  File \"/Library/Python/2.7/site-packages/jinja2/runtime.py\", line 193, in call\n    return __obj(_args, *_kwargs)\n  File \"/Library/Python/2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/template/__init__.py\", line 220, in _lookup\n    ran = instance.run(_args, variables=self._available_variables, *_kwargs)\n  File \"/Library/Python/2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/plugins/lookup/file.py\", line 57, in run\n    ret.append(contents.rstrip())\nAttributeError: 'tuple' object has no attribute 'rstrip'\n", "stdout": ""}

ansible --version
2.0.0

Any ideas?? I was forced to upgrade to 2.0 to use digital ocean api v2 but now this lookup file that was working is no longer working anywhere. Is there a workaround?

**Comment by bcoca** [comment]
this was temporarily broken in devel (my fault) but should be working now

**Comment by jaseclamp** [comment]
Getting a little depressed trying to use v2. I'm using it because I have to to work with digitalocean v2 api but.. is there a stable branch which mostly works?? (sheepish grin). 

I'm trying to do simple things like mentioned in the docs: 

```
 - debug: var=hostvars
```

Yeilds: 

```
TASK [debug var=hostvars] *******************************************************
ok: [128.199.113.237] => {
    "changed": false, 
    "hostvars": {}
}
```

Seems like all variables like 'environment' are empty. Trying to debug why I'm having an SSH connect problem right after droplet create but with no variable debug it's hard. 

Also group_vars/all isn't working any more, i'm having to manually include like so: 

```
vars_files:
  - group_vars/all
```

**Comment by bcoca** [comment]
normally devel is very stable, but v2 is a huge change so we did expect a few bugs, that said if this is a different bug than before please open a new ticket and we'll address it as soon as we can.

Since the file issue (this bug) was fixed, I'm closing this ticket.
