### ISSUE TITLE
Service Module does not use same Service Manager Package as Service command

### ISSUE THREAD

**Issue by dagnello** [ansible/ansible#11250]
Target environment: Ubuntu 14.04.1 LTS
Ansible Host environment: Ubuntu 14.04.1 LTS, Ansible 1.9.1-1ppa~trusty

Repro:
1. use apt module to install zookeeper and zookeeperd
2. use service module to stop zookeeper
3. log into target machine, zookeeper is still running

What is happening:
- zookeeper is installing init scripts for both init.d and upstart
- service zookeeper start/stop/restart uses upstart init script (zookeeper is started by apt this way when installed)
- using Ansible's service module to start/stop/restart zookeeper, the init.d script is used instead.  This creates the potential for a second instance of zookeeper to be launched, and Ansible is unable to stop the first (upstart launched) instance.

**Comment by bcoca** [comment]
- this is the wrong place for the ticket, github.com/ansible/ansible-modules-core is where the service module lives
- this was a known issue and should be 'fixed' in the latest stable
