### ISSUE TITLE
with_dict doesn't work after commit 47aeff1636cfc158d72a54370eb3135469264ca2

### ISSUE THREAD

**Issue by ssbljk** [ansible/ansible#11264]
There is line 41 changed in lib/ansible/utils/listify.py
in commit no: aed429554dc86385408133988da5caba44dce891
and since then with_dict keeps returning error:
FAILED! => {"msg": "ERROR! with_dict expects a dict", "failed": true}

After I replaced that line with one from  47aeff1636cfc158d72a54370eb3135469264ca2
it works again.

**Comment by bcoca** [comment]
fixed via f576d29b6b8071f56498facc48c32f8b12bbcb73
