### ISSUE TITLE
add  --diff option to synchronize module

### ISSUE THREAD

**Issue by dwt** [ansible/ansible#11262]
##### Steps To Reproduce:
- Use sync in a playbook
- add --diff --check options to running the playbook
- See no diff appear in the output

**Comment by rbu** [comment]
I'd be interested in this. Even a list of files with what changed about them (creating, removing, content changed, properties changed) would be much more helpful than what ansible currently outputs.

**Comment by ghost** [comment]
no diff on synchronize is a big pain point with using ansible for me. There is never a time I want to run a playbook and not know _exactly_ whats changing.

**Comment by eikenb** [comment]
+1

Would prefer not to need an external script to do this.

**Comment by towolf** [comment]
This can be closed after @bcoca merged it:kissing_heart:, no?

**Comment by bcoca** [comment]
closing as per above

**Comment by ghost** [comment]
@towolf in which release will this feature be first available?
(Will it be available in ansible 1.X?)

**Comment by towolf** [comment]
Hopefully in 2.1.0.

I don't think it's going to be backported to 1.9 stable series.
