### ISSUE TITLE
Add permission changes to file's --diff mode

### ISSUE THREAD

**Issue by pako-pl** [ansible/ansible#11263]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
file module

##### SUMMARY
It would be very nice if --diff mode also showed permission changes, in addition to file contents changes. For now it only says that a file changed without any further explanation. Is it possible to display a summary of what changed - owner, group or mode with "before" and "after" values? Making a mistake when changing permissions can be very dangerous, so having more information would make applying changes less stressful :-).

**Comment by sigio** [comment]
Seems ansible shows diff's for mode changes now ... sadly it shows these in decimal instead of octal, making it hard to see what actually happened:

```
TASK [common : restrict permissions in /var/log] *******************************
changed: [munged] => (item={u'path': u'/var/log', u'mode': u'0711'})
--- before
+++ after
@@ -1,4 +1,4 @@
 {
-    "mode": 449, 
+    "mode": 457, 
     "path": "/var/log"
 }

```

**Comment by bcoca** [comment]
good point, i should make sure that is always octal

**Comment by bcoca** [comment]
updated, now shows octal

**Comment by gothicx** [comment]
This looks fixed to me on version 2.6 - dev.

```
--- before
+++ after
@@ -1,4 +1,4 @@
 {
-    "mode": "0755",
+    "mode": "0750",
     "path": "/tmp/test.txt"
 }
```

**Comment by gothicx** [comment]
bug_resolved

**Comment by bcoca** [comment]
closing as per above, this was done long ago.
