### ISSUE TITLE
Make 'ansible-galaxy install -r requirements.yml' idempotent

### ISSUE THREAD

**Issue by tjanez** [ansible/ansible#11266]
##### Issue Type:

Bug Report/Feature Idea
##### Ansible Version:

```
ansible 1.9.1
  configured module search path = None
```
##### Ansible Configuration:

``` ini
[defaults]                                                                      
log_path = ../.tmp/ansible.log                                                  
# path to the directory containing roles                                        
roles_path = roles                                                              
hash_behaviour = merge                                                          
error_on_undefined_vars = yes                                                   
host_key_checking=False
```
##### Environment:

N/A
##### Summary:

Running `ansible-galaxy install -r requirements.yml` should be idempotent (e.g. it should behave like `pip install -r requirements.txt`).
##### Steps To Reproduce:
1. Create `requirements.yml` file with the following contents:
   
   ``` yaml
   # nodejs role
   - src: https://github.com/nodesource/ansible-nodejs-role
     version: 592a239dca52e1c5ff79cfefd0072efe3831428e
     name: nodejs
   ```
2. Run `ansible-galaxy install -r requirements.yml`.
3. Re-run `ansible-galaxy install -r requirements.yml`.
##### Expected Results:

``` bash
[tadej@tlinux64 admin]$ ansible-galaxy install -r requirements.yml
- executing: git clone https://github.com/nodesource/ansible-nodejs-role nodejs
- executing: git archive --prefix=nodejs/ --output=/tmp/tmpVoJEMx.tar 592a239dca52e1c5ff79cfefd0072efe3831428e
- extracting nodejs to roles/nodejs
- nodejs was installed successfully
```

On the second run, `ansible-galaxy` should detect that the `nodejs` role is already installed and make sure the installed version matches the version specified in `requirements.yml`.
##### Actual Results:

``` bash
[tadej@tlinux64 admin]$ ansible-galaxy install -r requirements.yml
- executing: git clone https://github.com/nodesource/ansible-nodejs-role nodejs
- executing: git archive --prefix=nodejs/ --output=/tmp/tmpVoJEMx.tar 592a239dca52e1c5ff79cfefd0072efe3831428e
- extracting nodejs to roles/nodejs
- nodejs was installed successfully
[tadej@tlinux64 admin]$ ansible-galaxy install -r requirements.yml
- executing: git clone https://github.com/nodesource/ansible-nodejs-role nodejs
- executing: git archive --prefix=nodejs/ --output=/tmp/tmp73DSKM.tar 592a239dca52e1c5ff79cfefd0072efe3831428e
- extracting nodejs to roles/nodejs
- error: the specified role nodejs appears to already exist. Use --force to replace it.
- nodejs was NOT installed successfully.
- you can use --ignore-errors to skip failed roles.
```
##### Additional Info:
- One can specify `--ignore-errors` to ignore the failed roles, however, this is not the appropriate solution, since this would also ignore errors where `ansible-galaxy` failed to fetch a role from a remote server.
- It should be possible to obtain the version of the installed role via `meta/.galaxy_install_info` file. For example, for the `nodejs` role installed before, it has the following contents:
  
  ```
  {install_date: 'Mon Jun 15 11:56:40 2015', version: 592a239dca52e1c5ff79cfefd0072efe3831428e}
  ```

**Comment by srkiNZ84** [comment]
:+1:

**Comment by lorefnon** [comment]
:+1: Another problem with ignore-errors is that the complete archive tarball will be downloaded each time.  The error is encountered only when extraction is attempted.

**Comment by igormukhingmailcom** [comment]
+1

**Comment by katoquro** [comment]
+1

**Comment by conorsch** [comment]
+1

**Comment by aussielunix** [comment]
see https://github.com/ansible/galaxy-issues/issues/49

**Comment by andre487** [comment]
+1

**Comment by asagage** [comment]
+1

**Comment by jesselang** [comment]
+1

**Comment by geerlingguy** [comment]
Should this issue be closed in favor of https://github.com/ansible/galaxy-issues/issues/49 ? Seems odd to have the same issue in two places.

Also, this has come up again in a case where it would be nice to have galaxy itself handle role installation idempotently. Some scripts that set up an Ansible project have to make sure the roles are installed and up to date, and right now that means either doing a bunch of version checking in the scripts, or running with `--force` and making Galaxy download all the roles every time setup is run.

**Comment by dltj** [comment]
Wherever it makes sense to get attention from someone who can scratch the itch to fix it.  I'll note, though, that there are more people subscribed to this ticket than there are to the other...

**Comment by bcoca** [comment]
keep this one open the ansible/galaxy-issues repo is for the galaxy website, not the ansible-galaxy command line tool

**Comment by geerlingguy** [comment]
@bcoca - Note that, with the Vagrant 1.8.0 release (which includes a new [`ansible_local` provisioner](https://docs.vagrantup.com/v2/provisioning/ansible_local.html)), Galaxy might start seeing a _lot_ more downloads... by default it installs roles in a configured roles file with `--force`, to make sure all roles are the latest versions defined in the roles file at all times.

I'm guessing it won't crush the Ansible Galaxy infrastructure, but it's worth noting as every time you run `vagrant provision` on a VM using the new provisioner it will take an extra minute or two to install/reinstall every role.

**Comment by haad** [comment]
+1 This would be very welcome as using ansible-galaxy is quite problematic right now.

**Comment by fernandogrd** [comment]
I would like that feature as well, I was using ansible-galaxy install -r requirements.yml, but I've just stopped, because a lot was broken when I tried to build a new virtualenv.

**Comment by drybjed** [comment]
:+1:

**Comment by scottcunningham** [comment]
:+1:

**Comment by rowleyaj** [comment]
This is labelled as a `feature_idea`. @bcoca where does this sit in the plans for the core team?

**Comment by spiette** [comment]
+1

**Comment by paulmcgoldrick** [comment]
+1

**Comment by yeroc** [comment]
+1

**Comment by panickervinod** [comment]
+1

**Comment by nhooey** [comment]
Please stop adding useless `+1` messages and notifying everyone. Use GitHub's "reaction" feature instead. @yeorc @panickervinod @paulmcgoldrick @spiette

**Comment by yeroc** [comment]
@nhooey Not sure whether you're speaking on behalf of the Ansible maintainers or not but if you are then the CONTRIBUTING.md file in the ansible source repo and the various sub-projects along with the [community contributions](http://docs.ansible.com/ansible/community.html) page should be updated to reflect the appropriate manner in which to vote for an issue.  Since the Github reactions feature was implemented relatively recently casual users can't be expected to be aware of this, nor is there complete consensus on the usage of this feature with some projects continuing to recommend a ["+1" comment](https://github.com/elastic/kibana/blob/df0cad1874c2560d5f3b18f2600ac251fdac0769/CONTRIBUTING.md) and others adopting ["+1" reactions](https://github.com/twbs/bootstrap/blob/6a070e95be58b68239b59ab9db47500669200953/CONTRIBUTING.md).  Either way, the Ansible maintainers should provide clear guidelines before embarking on comments such as yours.

More pedantically, please spell my handle correctly! ;)  

Apologies to everyone else on this issue for the spam.

**Comment by likg** [comment]
Recent commit broke correct work of --force flag for ansible-galaxy for roles without specific tag. For example, now it`s not possible to fetch latest changes from bare git repo. 
```
# cat ansible-roles.yml
- src: https://github.com/bennojoy/nginx

# First run:
# ansible-galaxy install -f -r ansible-roles.yml
- extracting nginx to /etc/ansible/roles/nginx
- nginx was installed successfully

# Repeated run, regadless of new commits in repo
# ansible-galaxy install -f -r ansible-roles.yml
- nginx is already installed, skipping.

**Comment by jctanner** [comment]
resolved_by_pr https://github.com/ansible/ansible/pull/12904
