### ISSUE TITLE
EC2 tasks: add support for VPC ClassicLink

### ISSUE THREAD

**Issue by phraktle** [ansible/ansible#11260]
EC2 tasks should expose options to enabling ClassicLink (see 
https://aws.amazon.com/blogs/aws/classiclink-private-communication-between-classic-ec2-instances-vpc-resources/)

**Comment by bennojoy** [comment]
Hi!

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

This appears to be something that should be filed against another project or bug tracker, and let us explain our reasons for thinking this:

To enable classiclink the work would to create a new module or enable the existing modules to support classiclink, the repo for ansible modules are ansible-modules-core and ansible-modules-extras. 

If you can stop by the tracker or forum for one of those projects, we'd appreciate it.

Should you still wish to discuss things further, or if you disagree with our thought process, please stop by one of our two mailing lists:

https://groups.google.com/forum/#!forum/ansible-project
https://groups.google.com/forum/#!forum/ansible-devel
We'd be happy to discuss things.

Thank you once again!
