### ISSUE TITLE
Remote job suspended ,How can i handle it ? Can i see the real time output ?

### ISSUE THREAD

**Issue by world520ai** [ansible/ansible#11277]
When i use ansible to execute yum to install something. but in fact ,The remote host auto update system, then it startup a yum Process .
    So the ansible wait there forever ,How can I do something usefull ? I'm  confused.
       The other hand ,Can I see the real output of ansible ?  I feel i am blind when the ansible is executing.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
