### ISSUE TITLE
Unable to clone ansible

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#11279]
the file lib/ansible/executor/task_queue_manager.py: contains the string ":" in the filename, which leaves me unable to clone (or do anything) to the ansible repo. I'm sure the filename is a typo.

**Comment by bcoca** [comment]
found bogus file, deleted it, will update repo soon

**Comment by bcoca** [comment]
fixed via 423f1233c8dfe7c39852c66f8d982b841b679e9c
