### ISSUE TITLE
NameError: global name 'success_key' is not defined

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#11285]
##### Issue Type:

Bug Report
##### Ansible Version:

$ ansible --version
ansible 2.0.0 (devel 30c1a2d861) last updated 2015/06/16 11:18:20 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 9acc7c402f) last updated 2015/06/10 17:06:47 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 2f967a949f) last updated 2015/06/10 17:06:47 (GMT -500)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/03 00:37:54 (GMT -500)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/03 00:37:58 (GMT -500)
  configured module search path = None
##### Ansible Configuration:

I was (aka using v1 code base)
$ source v1/hacking/env-setup

Now I'm (using v2 code base)
$ source hacking/env-setup
##### Environment:

OS X Yosemite 10.10.3

$ python -V
Python 2.7.6

$ pip freeze
ansible==2.0.0
ecdsa==0.13
epdb==0.12
httplib2==0.9.1
isodate==0.5.1
Jinja2==2.7.3
kerberos==1.2.2
MarkupSafe==0.23
nose==1.3.7
paramiko==1.15.2
passlib==1.6.2
pycrypto==2.6.1
pywinrm==0.0.3
PyYAML==3.11
six==1.9.0
xmltodict==0.9.2
##### Summary:

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.  Thanks!
##### Steps To Reproduce:

Applied 98f5534

$ source hacking/env-setup
ansible-playbook --ask-pass --ask-sudo-pass -i production-servers linux-servers.yml -vvvv
SSH password:
SUDO password[defaults to SSH password]:
##### Expected Results:

I assume the plays would run to completion like then do in v1.
##### Actual Results:

``` python
fatal: [host.domain.com]: FAILED! => {"failed": true, "exception": "Traceback (most recent call last):\n  File \"/Users/tanner/projects/ansible.git/ansible/lib/ansible/executor/process/worker.py\", line 118, in run\n    executor_result = TaskExecutor(host, task, job_vars, new_connection_info, self._new_stdin, self._loader, shared_loader_obj).run()\n  File \"/Users/tanner/projects/ansible.git/ansible/lib/ansible/executor/task_executor.py\", line 111, in run\n    res = self._execute()\n  File \"/Users/tanner/projects/ansible.git/ansible/lib/ansible/executor/task_executor.py\", line 266, in _execute\n    result = self._handler.run(task_vars=variables)\n  File \"/Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/action/normal.py\", line 27, in run\n    return self._execute_module(tmp, task_vars=task_vars)\n  File \"/Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/action/__init__.py\", line 348, in _execute_module\n    tmp = self._make_tmp_path()\n  File \"/Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/action/__init__.py\", line 156, in _make_tmp_path\n    result = self._low_level_execute_command(cmd, None, sudoable=False)\n  File \"/Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/action/__init__.py\", line 449, in _low_level_execute_command\n    rc, stdin, stdout, stderr = self._connection.exec_command(cmd, tmp, in_data=in_data, sudoable=sudoable)\n  File \"/Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/connections/paramiko_ssh.py\", line 227, in exec_command\n    if success_key in become_output or \\\nNameError: global name 'success_key' is not defined\n", "stdout": ""}
```

**Comment by bcoca** [comment]
fixed in my devel branch, will merge soon

**Comment by basictheprogram** [comment]
Work around is to 

$ source v1/hacking/env-setup

And all plays function as expected.

**Comment by bcoca** [comment]
my fixes were merged, please confirm that it now works for you

**Comment by basictheprogram** [comment]
Simple things are working as expected, but I'd like to run the full playbook tonight during the maintenance window. I'll post back here my results.

**Comment by basictheprogram** [comment]
(after re-reading this I can see as this as a new/different issue, NameError: global name 'success_key' is not defined was fixed by the last pull.)

Looks like a playbook and --tags in v1 gives changed results but none of the plays play in v2.

VMware virtual host running linux.
Snapshot to save the unpatched state.

```
$ source v1/hacking/env-setup
$ cd ../playbooks/
$ ansible-playbook --ask-pass --ask-sudo-pass  -i testing-servers linux-servers.yml --tags "apt"
SSH password:
SUDO password[defaults to SSH password]:
PLAY [linux-servers] **********************************************************
GATHERING FACTS ***************************************************************
ok: [host.domain.com]
TASK: [common | package update (apt)] *****************************************
ok: [host.domain.com]
TASK: [common | package upgrade (apt)] ****************************************
changed: [host.domain.com]
PLAY RECAP ********************************************************************
host.domain.com     : ok=2    changed=1    unreachable=0    failed=0
```

Roll back virtual machine to unpatch state.

```
$ source hacking/env-setup
$ cd ../playbooks/
$ ansible-playbook --ask-pass --ask-sudo-pass  -i testing-servers linux-servers.yml --tags "apt"
SSH password:
SUDO password[defaults to SSH password]:
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [host.domain.com]
PLAY RECAP **********************************************************************
host.domain.com    : ok=1    changed=0    unreachable=0    failed=0
```

I know for sure there's 2 plays, so "ok=1" isn't right. I also know there are multiple patches to this virtual machine so "changed=0" is not right.

```
---
# file: linux-servers.yml

- hosts: linux-servers
  remote_user: ansible-user
  roles:
    - common
```

```
---
# file: roles/common/tasks/main.yml

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
- include: debian.yml
  when: ansible_os_family == 'Debian'
- include: suse.yml
  when: ansible_os_family == 'Suse' or ansible_os_family == 'openSUSE'
- include: solaris.yml
  when: ansible_os_family == 'Solaris'
```

The virtual machine is debian.

```
---
# tasks file for roles/common/tasks/debian.yml

# Only run "update_cache=yes" if the last one is more than 3600 seconds ago
- name: package update (apt)
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes
  always_run: yes
  tags: apt

# Update all packages to the latest version
- name: package upgrade (apt)
  apt: upgrade=dist
  sudo: yes
  always_run: yes
  tags:  apt
```

**Comment by bcoca** [comment]
so closing this ticket as the original problem is gone, please open a new ticket for the tagging issue
