### ISSUE TITLE
AIX WPAR handling is inefficient and possibly buggy

### ISSUE THREAD

**Issue by kstrauser** [ansible/ansible#11289]
The `lib/ansible/module_utils/facts.py:AIXNetwork.get_interfaces_info` method is structured like:

```
rc, out, err = module.run_command([ifconfig_path, '-a'])
for line in out.split('\n'):
    ...
    uname_path = module.get_bin_path('uname')
    if uname_path:
        rc, out, err = module.run_command([uname_path, '-W'])
```

This has two big problems:
1. It uses `subprocess.Popen` to run `uname -W` _for each line in ifconfig_. This is a performance issue because shelling out is expensive and this data isn't going to change during run on a single host. It should be collected once and then reused.
2. Note that `out` is overwritten inside the loop. It won't break the loop, which is iterating over `out.split('\n')` and not `out` directly. However, that may cause breakage in further edits that expect `out` to keep the same information throughout the loop. Consider using unique variable names like `ifconfig_out`,`entstat_out`, etc. to avoid weird, hard-to-debug errors later.

/cc @bmanojlovic who contributed this code.

**Comment by jctanner** [comment]
The code in devel (2.3) still has this inefficient behavior. I'm guessing it was just a mistaken indentation? https://github.com/ansible/ansible/pull/11290 was never merged and I suspect will never get rebased.

**Comment by kstrauser** [comment]
I don't have access to a machine to test this against anymore.
