### ISSUE TITLE
wishlist: show ssh port if not standard in output

### ISSUE THREAD

**Issue by joshunger** [ansible/ansible#11291]
Would be helpful to show the ssh port if it is not standard in the output?  For example, I am running an Ansible playbook against localhost and localhost 2022 which is boot2docker.  It would be helpful to differentiate between the two.  Currently, the port number is not displayed.

For example, default port -

```
ok: [localhost] => {
    "msg": "demo"
}
```

Non-standard port -

```
ok: [localhost:2022] => {
    "msg": "demo"
}
```

**Comment by bcoca** [comment]
a workaround is using aliases in the inventory and ansible_ssh_host/ansible_ssh_port variables to point to the host.

**Comment by joshunger** [comment]
@bcoca thanks, I just figured that out too.  

`boot2docker ansible_ssh_port=2022 ansible_ssh_host=127.0.0.1 ansible_ssh_user=docker ansible_ssh_private_key_file=~/.ssh/id_boot2docker`

You can close this issue if you don't think it would be helpful.  Thanks.
