### ISSUE TITLE
top level vars_plugins directory not picked when targeting a nested inventory

### ISSUE THREAD

**Issue by juliedavila** [ansible/ansible#11303]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.1 (detached HEAD b47d1d7e69) last updated 2015/06/15 10:38:02 (GMT -400)
  lib/ansible/modules/core: (devel 8ce2a18921) last updated 2015/04/21 15:50:13 (GMT -400)
  lib/ansible/modules/extras: (devel db64a6b584) last updated 2015/04/21 15:50:19 (GMT -400)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2015/03/23 16:08:27 (GMT -400)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2015/03/23 16:08:27 (GMT -400)
  configured module search path = None
##### Ansible Configuration:

default
##### Environment:

OSX to OSX, a local action playbook
##### Summary:

When targeting an inventory that is nested, ansible doesn't seem to pick up top level (as opposed to root level) plugin directories, though I've only tested with `vars_plugins`. The directory does get picked up as long as the inventory file is also top-level or if ansible.cfg is explicitly told to pickup the vars_plugin directory as such: `vars_plugins       = ./vars_plugins`
##### Steps To Reproduce:

Create a `vars_plugins/` directory at `$project_root` with a trivial plugin that prints a message whether in init or other functions, create a host file in `$project_root/dir1/dir2/hosts` then run `ansible-playbook someplaybook.yml -i dir1/dir2/hosts`
##### Expected Results:

The message gets printed
##### Actual Results:

Nothing gets printed

**Comment by bcoca** [comment]
In general plugin dirs should only get picked up when relative to play or in role, aside from those specifically configured. 

That aside, the inventory does not traverse upwards either, so ansible will have no reason to look at `$project_root` unless you specifically tell it to.

**Comment by scareything** [comment]
"In general plugin dirs should only get picked up when relative to play or in role"

This is exactly the issue - plugins in the vars_plugins directory relative to the playbook are not being loaded as described in the doc at http://docs.ansible.com/ansible/developing_plugins.html:

"In addition, plugins can be shipped in a subdirectory relative to a top-level playbook, in folders named the same as indicated above."

Specific configuration in ansible.cfg was necessary.

**Comment by nailgun** [comment]
@bcoca In my opinion this issue was closed by error. I confirm the problem exists. vars_plugins directory is in the same dir level as the top-level playbook. And it isn't being found by ansible.

Specifying "vars_plugins = ./vars_plugins" in ansible.cfg fixes this.

Please reopen the issue.
