### ISSUE TITLE
add --installroot option to yum module

### ISSUE THREAD

**Issue by MartinDE90** [ansible/ansible#11310]
<b>Issue Type:</b> Feature Idea
<b>Ansible Version:</b> 1.9.1
<b>Ansible Configuration:</b> nothing changed
<b>Environment:</b> RHEL/CentOS 7
<b>Summary:</b>
I'm trying to keep some software installed into a non-standard directory. Currently using the yum module I can't specify an alternative installroot path. 
<b>Expected Results:</b>
I would like to be able to add --installroot option like I can do this with yum in linux.

**Comment by jctanner** [comment]
Duplicate of https://github.com/ansible/ansible-modules-core/issues/1558
