### ISSUE TITLE
roles handler uses previous value. 

### ISSUE THREAD

**Issue by varunpalekar** [ansible/ansible#11311]
#### Ansible version : ansible 1.9.1

I am using [ansible-redis](https://github.com/DavidWittman/ansible-redis) role for installing two redis server one by one though playbook as: 

```
vars: 
    redis_port: 6379
roles: 
    - { role: ../playbooks/roles/ansible-redis-master, 
      redis_version: "{{redis_version}}" ,
      redis_install_dir: "/opt/redis_9921" ,
      redis_port: 9921 ,
      redis_bind: "{{ethernet.private.ip_address}}",
      sudo: yes }

    - { role: ../playbooks/roles/ansible-redis-master, 
      redis_version: "{{redis_version}}" ,
      redis_install_dir: "/opt/redis" ,
      redis_port: "{{redis_port}}" ,
      redis_bind: "{{ethernet.private.ip_address}}",
      sudo: yes }
```

But in running handler `restart redis` though second time role run, it has previous value of `redis_port` variable, i.e.,  9921, which is unexpected. 
I am sharing you the run logs of notification of both role run below. 
#### First run with redis_port: 9921 ,

```
NOTIFIED: [../playbooks/roles/ansible-redis-master | restart redis] ***********
<IP ADDRESS> REMOTE_MODULE service name=redis_9921 state=restarted
changed: [prod-redis] => {"changed": true, "name": "redis_9921", "state": "started"}

TASK: [../playbooks/roles/ansible-redis-master | ensure redis is running] *****
<IP ADDRESS> REMOTE_MODULE service name=redis_9921 state=started
ok: [prod-redis] => {"changed": false, "name": "redis_9921", "state": "started"}
```
#### Second run with redis_port: 6379

```
NOTIFIED: [../playbooks/roles/ansible-redis-master | restart redis] ***********
<IP ADDRESS> REMOTE_MODULE service name=redis_9921 state=restarted
changed: [prod-redis] => {"changed": true, "name": "redis_9921", "state": "started"}

TASK: [../playbooks/roles/ansible-redis-master | ensure redis is running] *****
<IP ADDRESS> REMOTE_MODULE service name=redis_6379 state=started
changed: [prod-redis] => {"changed": true, "name": "redis_6379", "state": "started"}
```

In above it uses `9921` value of variable `redis_port` only for handlers, not for the task. 

Please help me on this, due to this I lost some redis data on the production. It can be a major issue.

**Comment by alikins** [comment]
Looking at the defaults in that role, https://github.com/DavidWittman/ansible-redis/blob/master/defaults/main.yml, redis_port=6379 is also the default (https://github.com/DavidWittman/ansible-redis/blob/master/defaults/main.yml#L24)

Could this be falling back to the default somehow? As opposed to reusing the value from the first role? 

Does behavior change if you flip the order of the roles?

**Comment by varunpalekar** [comment]
@alikins May be problem is due to handler runs variables. Second time handler won't get updated to new variable.

**Comment by jctanner** [comment]
I think I have reproduced the described behavior with a simple version of the redis role ...

```
PLAY [el7host] **************************************************************** 

TASK: [redis-master | print redis_port var inside the role] ******************* 
changed: [el7host] => {
    "changed": true,
    "var": {
        "redis_port": "9921"
    }
}

TASK: [redis-master | print redis_port var inside the role] ******************* 
changed: [el7host] => {
    "changed": true,
    "var": {
        "redis_port": "6379"
    }
}

NOTIFIED: [redis-master | restart redis] ************************************** 
ok: [el7host] => {
    "msg": "redis_9921"
}

PLAY RECAP ******************************************************************** 
el7host                    : ok=3    changed=2    unreachable=0    failed=0   
```

The handler is notified twice, but only runs once which is the expected behavior. Based on what I gather from the role's files, it wants to restart a particular redis instance. If the handler only fires once, it'll never restart all the expected instances. That means the role was written without considering that it might be called multiple times in the same playbook with different variables.  The role should flush handlers before finishing execution.

Please file a bug on the role's issue tracker: https://github.com/DavidWittman/ansible-redis/issues
