### ISSUE TITLE
user module errors: usermod: user $USER is currently used by process 813

### ISSUE THREAD

**Issue by maxamillion** [ansible/ansible#11324]
When attempting to use the `user` module I receive an error up running. I'm running Fedora 22 x86_64 Server (in the event that matters/helps).

Here's the task:

``` yaml
- name: Verify User created
  user:
    name: "{{non_root_user}}"
    home: /home/"{{non_root_user}}"
    append: yes
    groups: mock,dockerroot
```

And verbose output when I run:

```
TASK: [Verify User created] *************************************************** 
<localhost> REMOTE_MODULE user groups=mock,dockerroot name=admiller home='/home/"admiller"'
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1434730227.48-25173687899362 && echo $HOME/.ansible/tmp/ansible-tmp-1434730227.48-25173687899362']
<localhost> PUT /tmp/tmpp0iojE TO /root/.ansible/tmp/ansible-tmp-1434730227.48-25173687899362/user
<localhost> EXEC ['/bin/sh', '-c', u'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1434730227.48-25173687899362/user; rm -rf /root/.ansible/tmp/ansible-tmp-1434730227.48-25173687899362/ >/dev/null 2>&1']
failed: [localhost] => {"failed": true, "name": "admiller", "rc": 8}
msg: usermod: user admiller is currently used by process 813


FATAL: all hosts have already failed -- aborting
```

Ansible version info:

```
$ ansible --version
ansible 1.9.1
  configured module search path = None
```

**Comment by bcoca** [comment]
i would expect this same message if i manually try to modify the user the same way.

**Comment by maxamillion** [comment]
Unfortunately that is not the case (Note: the `(0)`  and `(2)` respectively in my PS1 are the exit codes of the corresponding previous command:

```
$ usermod -a -d /home/admiller -G mock,dockerroot admiller
[13:49:39|root@pseudogen(0) ~]
$ ansible-playbook ~admiller/ansible/fedora-laptop/laptop-i3.yml -i ~admiller/ansible/fedora-laptop/inventory.txt -t userconf -vvvv

PLAY [Fedora Package Install - i3] ******************************************** 

GATHERING FACTS *************************************************************** 
<localhost> REMOTE_MODULE setup
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1434739784.95-224477461504332 && echo $HOME/.ansible/tmp/ansible-tmp-1434739784.95-224477461504332']
<localhost> PUT /tmp/tmpdBlN5y TO /root/.ansible/tmp/ansible-tmp-1434739784.95-224477461504332/setup
<localhost> EXEC ['/bin/sh', '-c', u'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1434739784.95-224477461504332/setup; rm -rf /root/.ansible/tmp/ansible-tmp-1434739784.95-224477461504332/ >/dev/null 2>&1']
ok: [localhost]

TASK: [Verify User created] *************************************************** 
<localhost> REMOTE_MODULE user groups=mock,dockerroot name=admiller home='/home/"admiller"'
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1434739786.52-267724264303908 && echo $HOME/.ansible/tmp/ansible-tmp-1434739786.52-267724264303908']
<localhost> PUT /tmp/tmpma1PGs TO /root/.ansible/tmp/ansible-tmp-1434739786.52-267724264303908/user
<localhost> EXEC ['/bin/sh', '-c', u'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1434739786.52-267724264303908/user; rm -rf /root/.ansible/tmp/ansible-tmp-1434739786.52-267724264303908/ >/dev/null 2>&1']
failed: [localhost] => {"failed": true, "name": "admiller", "rc": 8}
msg: usermod: user admiller is currently used by process 813


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/laptop-i3.retry

localhost                  : ok=1    changed=0    unreachable=0    failed=1   

[13:49:46|root@pseudogen(2) ~]
```

**Comment by bcoca** [comment]
can you try with:

 home: /home/{{non_root_user}}

**Comment by maxamillion** [comment]
@bcoca - That worked, thanks! ... not sure if you would like to leave this open as an issue or not, this playbook worked in older versions of ansible but fails in 1.9. That being said, I'm still happy to close it if you are because it's possible it was working for me and it shouldn't have been. Thank you.

**Comment by bcoca** [comment]
so the issue seems to be that now we conserve the quotes  /home/"{{user}}" and then it fails in comparing the strings '/home/user1' vs '/home/"user1"' and tries to change the user, hence the error.

I'm also not sure if this is a bug or the expected correct behavior at this point, it seems that changes to the key=val parser caused this.

**Comment by sivel** [comment]
I would expect the above behavior to be the correct behavior.  You are quoting part of the line and not the whole line so the quotes should be included in the resultant string.

The appropriate way would be:

```
    home: "/home/{{non_root_user}}"
```

**Comment by bcoca** [comment]
so after discussing with several parties, I'm going to close this w/o marking it as a bug, the directories were not matching, the user module assumed it needed to make a change, but the user was logged in and doing stuff, hence the error. All worked as it should.

**Comment by shadyb** [comment]
I am having similar issues; Task below:

    - name: Create nginx webroot user
      user: name={{ nginx_webroot_owner }} shell=/sbin/nologin home=/usr/share/nginx/html system=yes

Output:

    TASK: [nginx | Create nginx webroot user] *************************************
    <hud.by> ESTABLISH CONNECTION FOR USER: janitor
    <hud.by> REMOTE_MODULE user name=nginx-www shell=/sbin/nologin home=/usr/share/nginx/html system=yes
    <hud.by> EXEC ssh -C -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=3050 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=janitor -o ConnectTimeout=10 hud.by /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=cdwbtfcgptpgbhwkbejovoksmrztrhrw] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-cdwbtfcgptpgbhwkbejovoksmrztrhrw; LANG=C LC_CTYPE=C /usr/bin/python'"'"''
    failed: [hud.by] => {"failed": true, "name": "nginx-www", "rc": 8}
    msg: usermod: user nginx-www is currently used by process 4630

Ansible version: 1.9.2

This role is pretty old and has worked for a few versions of ansible except 1.9.
