### ISSUE TITLE
Broken notification with msg notification

### ISSUE THREAD

**Issue by ssenaria** [ansible/ansible#11322]
Running v1.9.2 but it appears to be broken with the latest pull.

Error:

```
NOTIFIED: [perl | announce_hipchat] *******************************************
failed: [server1 -> 127.0.0.1] => {"failed": true}
msg: unable to sent msg: global name 'urllib' is not defined
```

System with error:

```
$ ansible --version
ansible 1.9.2 (stable-1.9 65fc0161a8) last updated 2015/06/19 09:56:06 (GMT -400)
```

On a system that works, I am running:

```
$ ansible --version
ansible 1.9.2 (stable-1.9 b70caac618) last updated 2015/06/04 20:52:04 (GMT +000)
```

**Comment by abadger** [comment]
Thanks.  I see the issue and will push a fix to a few modules shortly.

**Comment by abadger** [comment]
Okay, I've pushed that commit to both the devel branch and the stable-1.9 branch and updated the submodule refs for ansible/ansible to pull in the new commits.  That should fix this issue for you.

Thanks for reporting it!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by ssenaria** [comment]
Still broken ...

```
NOTIFIED: [restart | announce_hipchat] ****************************************
failed: [server1-> 127.0.0.1] => {"failed": true}
msg: failed to send message, return status=400
failed: [server2 -> 127.0.0.1] => {"failed": true}
msg: failed to send message, return status=400
```

**Comment by bcoca** [comment]
can you run with -vvvv?

**Comment by memelet** [comment]
I'm having this problem with 1.9.2-1 both from pip install and from source:

```
ansible❯ ansible-playbook -vvvv -i inventory/aws/staging playbooks/deploy/svc-mono-server.yml -e "tenant=tft plant=tft version=2.4-1401"
 [WARNING]: non fatal error while trying to template play variables: ERROR!
Failed to template {{ lookup('template', '../files/mono-server/run.sh.j2') |
regex_replace('', '\') }}: ERROR! template error while templating string:
unexpected char u"'" at 76


PLAY [Deploy mono-server] *****************************************************

TASK: [Get container settings] ************************************************
<10.0.137.160> ESTABLISH CONNECTION FOR USER: bkaplan
<10.0.137.160> REMOTE_MODULE consul_kv key=vimana/mono-server/tft/container dc=production action=get
<10.0.137.160> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=30m -o ControlPath="/Users/bkaplan/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 10.0.137.160 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
failed: [localhost -> 10.0.137.160] => {"failed": true, "parsed": false}
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /Users/bkaplan/.ssh/config
debug1: /Users/bkaplan/.ssh/config line 99: Applying options for 10.0.*
debug1: /Users/bkaplan/.ssh/config line 105: Applying options for *
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 24098
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
Traceback (most recent call last):
  File "<stdin>", line 2621, in <module>
  File "<stdin>", line 311, in main
  File "<stdin>", line 193, in run_cmd
  File "<stdin>", line 220, in _make_api_call
  File "<stdin>", line 253, in _setup_request
NameError: global name 'urllib' is not defined
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 1


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/bkaplan/svc-mono-server.retry
```

**Comment by akuznecov** [comment]
+1

Installed with `pip`
```
» ansible --version
ansible 1.9.2
```

```
TASK: [security-user | HipChat notification] ********************************** 
failed: [www.xxx.yyy.zzz] => {"failed": true}
msg: unable to sent msg: global name 'urllib' is not defined

FATAL: all hosts have already failed -- aborting
```

**Comment by vfarcic** [comment]
+1

**Comment by akuznecov** [comment]
I had this issue too, but it was caused by using manually cloned main and extra role repositories and defined paths to them on ansible.cfg
Problem gone after removing line from ansible.cfg

**Comment by thekindofme** [comment]
+1

**Comment by abadger** [comment]
@thekindofme This particular issue was fixed and pushed to the stable1.9 and devel branch in June.  I've just verfied  that 1.9.3 includes this fix.

If you are having similar symptoms, please open a new bug report on the https://github.com/ansible/ansible-modules-extras/ repository (assuming that this is a problem you are seeing with the hipchat module.  If it's a different module, it might be in thehttps://github.com/ansible/ansible-modules-core/ repository instead.)  with information on what version of ansible you are encountering the error on, the output of running with -vvvv as bcoca requested earlier, and information on how to reproduce.  Thanks!
