### ISSUE TITLE
group_vars/all.yml variables not available for hosts: filter

### ISSUE THREAD

**Issue by aioue** [ansible/ansible#11326]
#### Issue Type:

Bug Report
#### Ansible Version:

1.9.1
#### Ansible Configuration:

n/a
#### Environment:

OS X 10.10.3
#### Summary:

Variables from `group_vars/all.yml` cannot be referenced in a `hosts:` filter.

Since `all` variables belong to all groups, they should be available at the very start of play execution.

Variable that _are_ available to the `hosts:` filter are at the playbook level using `vars:` or `include_vars:`, `extra_vars` on the command line, and groups from the inventory collection.
#### Steps To Reproduce:

group_vars/all.yml:

```

---
foo: bar
```

playbook.yml:

```
- hosts:
  - build_{{ foo }}

  tasks:
  - debug: var="{{ foo }}"
```
#### Expected Results:

Matches hosts in group `build_bar`

``` shell
PLAY [build_bar] **************************

<...debug foo variable hosts>
```
#### Actual Results:

``` shell
PLAY [build_{{ foo }}] **************************
skipping: no hosts matched
```

**Comment by bcoca** [comment]
not a bug, no inventory variables (including group/host_vars)  are available at this stage as the host selection has not happened yet

. That the 'all' group will always be loaded does not mean it should be available beforehand.

**Comment by ankurkgupta** [comment]
@bcoca is there any workaround to have a global variable that can be used for specifying hosts filter?
