### ISSUE TITLE
Bug: Ansible can't deal with a home directory that contains spaces

### ISSUE THREAD

**Issue by fgimian** [ansible/ansible#11332]
Hey there guys, loving Ansible!

I moved my home directory to `/Volumes/Fotsies Home/fots` on my Mac and noticed that Ansible was not correctly quoting scripts and so my run was failing and creating the scripts in my current directory under `Home`.  After renaming the volume to Data (i.e. `/Volumes/Data/fots`), everything is working well again.

May be worth touching up when there's time :smile: 

Cheers
Fotis

**Comment by bcoca** [comment]
Can you show examples? most of the directory access is quoted so it should be able to deal with this.

**Comment by fgimian** [comment]
Sure, will get to this on the weekend as I'm a little busy on a project at the moment.  Bear with me for another day or so and I'll pop some output into the ticket :smile:

**Comment by fgimian** [comment]
Sorry for the delay, here's an example.  I've put a blank line between commands to make it easier to read:

```
fotsies-mac:~ $ cat hosts
localhost ansible_connection=local

fotsies-mac:~ $ ansible --version
ansible 1.9.1
  configured module search path = None

fotsies-mac:~ $ pwd
/Volumes/Data/Test User Home

fotsies-mac:~ $ ansible all -i hosts -m ping
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.9.1_2/libexec/lib/python2.7/site-packages/ansible/runner/connection_plugins/local.py", line 114, in put_file
    shutil.copyfile(in_path, out_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/Volumes/Data/Test User Home/.ansible/tmp/ansible-tmp-1435583980.01-244873417751719/ping'
localhost | FAILED => failed to transfer file to /Volumes/Data/Test User Home/.ansible/tmp/ansible-tmp-1435583980.01-244873417751719/ping

fotsies-mac:~ $ ansible all -vvvv -i hosts -m ping
<localhost> REMOTE_MODULE ping
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1435583985.14-258162511503399 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1435583985.14-258162511503399 && echo $HOME/.ansible/tmp/ansible-tmp-1435583985.14-258162511503399']
<localhost> PUT /var/folders/v0/pqrdw3ks20qg61s25gtscykr0000gp/T/tmp7f9VbB TO /Volumes/Data/Test User Home/.ansible/tmp/ansible-tmp-1435583985.14-258162511503399/ping
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.9.1_2/libexec/lib/python2.7/site-packages/ansible/runner/connection_plugins/local.py", line 114, in put_file
    shutil.copyfile(in_path, out_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/Volumes/Data/Test User Home/.ansible/tmp/ansible-tmp-1435583985.14-258162511503399/ping'
localhost | FAILED => failed to transfer file to /Volumes/Data/Test User Home/.ansible/tmp/ansible-tmp-1435583985.14-258162511503399/ping
fotsies-mac:~ $ 
```

Cheers
Fotis

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
