### ISSUE TITLE
Ansible and Makefile problem

### ISSUE THREAD

**Issue by kaldown** [ansible/ansible#11337]
Hello.
I recently faced some problem with Makefiles using ansible-playbook with -m shell --connection-local
Here some examples:

```
- name: building this
  shell: cd {{ this.path }} && make build

..... ERROR: ....
FRONTEND: lib/rnic.js: building done
FRONTEND: lib/report.js: building done
FRONTEND: lib/schedule.js: building done

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/this.retry

192.168.10.2               : ok=3    changed=2    unreachable=0    failed=1   

```

But if I go this dir, and run make build manually, there would be no problem.
I have a big playbook, but everything works fine, except only Makefiles.

Make an advice, maybe using shell is such bad idea, or should I rewrite all Makefiles with ansible-like scenarios ?

Thanks.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by bcoca** [comment]
In any case the list will need more information. Can you try running this with verbose output? (-vvvv) 

Also, FYI, instead of cd, you can use chdir= argument to shell.
