### ISSUE TITLE
Commands module doesn't properly remove creates= or chdir= if path contains escape char

### ISSUE THREAD

**Issue by giulianob** [ansible/ansible#1134]
For example:
action: command touch /somefile creates=/etc/some\ thing/test

From looking at the code, it appears creates= gets replaced by doing a string replace. However, the needle for replacement is "creates=/etc/some thing/test" while the haystack (the arg string) is "/somefile creates=/etc/some\ thing/test" therefore the replacement never happens and touch gets called with creates=... as an argument.

**Comment by mpdehaan** [comment]
pretty sure we were using shlex here.   I'll look into it.

**Comment by giulianob** [comment]
Ignore my last comment. I missed the pipes.quote call.

**Comment by giulianob** [comment]
Just tested it with lots of spaces. Looks good to me.
