### ISSUE TITLE
Git Module: Documentation Report

### ISSUE THREAD

**Issue by jonhatalla** [ansible/ansible#11358]
##### Issue Type:

Documentation Report for the git module - there is no mention that git binaries are required.  Other core modules with requirements report these at the top of the file. (for example, http://docs.ansible.com/s3_module.html)
##### Ansible Version:

`ansible 1.9.1`
##### Ansible Configuration:

no changes
##### Environment:

N/A
##### Summary:

The git module has a dependency/requirement on git binaries being installed, however this is not stated in the documentation. 
http://docs.ansible.com/git_module.html
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

Used the module to download a git repo.  It failed.  Solution was incredibly simple, and the other reason this is being reported is for completeness of documentation. And maybe to save someone else a few seconds in the future.

**Comment by bcoca** [comment]
report should have gone to http://github.com/ansible/ansible-modules-core, in any case fixed via 
https://github.com/ansible/ansible-modules-core/commit/2d3e93e55823d03891e1c6612e959ee785f17575
