### ISSUE TITLE
Add DOCUMENTATION notes to .rst template

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#1136]
Notes aren't used in the `hacking/templates/rst.j2`. This is a reminder that we have to add them.

Maybe assign this ticket to me? (Didn't follow recent discussion wether assignment to individual is possible; if so, kindly do so @mpdehaan)

**Comment by mpdehaan** [comment]
Yep, I can for anybody already added to the org.  Which you are!   Thanks!

**Comment by jpmens** [comment]
FWIW, I don't see this ticked under "assigned to me". (Might be a github thing, though :)

**Comment by jpmens** [comment]
PEBKAC

**Comment by jpmens** [comment]
Fixed in https://github.com/ansible/ansible/pull/1157
