### ISSUE TITLE
GATHERING FACTS error on openvz container

### ISSUE THREAD

**Issue by ticktockhouse** [ansible/ansible#11368]
I have a couple of openvz containers which fail when I attempt to gather facts on them. This is a shame because it seems that if any of the key/value pairs are missing, the whole gather_facts step fails. In this case, it appears that there is no "swapcached" value.

```
failed: [machine] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1435154235.24-256016898287708/setup", line 4278, in ?
    main()
  File "/root/.ansible/tmp/ansible-tmp-1435154235.24-256016898287708/setup", line 137, in main
data = run_setup(module)
  File "/root/.ansible/tmp/ansible-tmp-1435154235.24-256016898287708/setup", line 81, in run_setup
    facts = ansible_facts(module)
  File "/root/.ansible/tmp/ansible-tmp-1435154235.24-256016898287708/setup", line 4217, in ansible_facts
    facts.update(Hardware().populate())
  File "/root/.ansible/tmp/ansible-tmp-1435154235.24-256016898287708/setup", line 2339, in populate
    self.get_memory_facts()
  File "/root/.ansible/tmp/ansible-tmp-1435154235.24-256016898287708/setup", line 2361, in get_memory_facts
    self.facts['memory_mb'] = {
KeyError: 'swapcached'
```

Is there a workaround or solution?

**Comment by bcoca** [comment]
only current workaround is to not gather facts, but this should not be hard to fix, my only worry is that a few other errors like it might appear.

**Comment by sysadmin75** [comment]
I have access to an openvz container and I ran '-m setup' on it and it ran without giving any errors.

So my question to @ticktockhouse ...
Why do you think there should be a fact called 'swapcached'?
I do see
        "ansible_memory_mb": {
            "nocache": {
                "free": 31943,
                "used": 825
            },
            "real": {
                "free": 28134,
                "total": 32768,
                "used": 4634
            },
            "swap": {
                "cached": null,
                "free": 0,
                "total": 0,
                "used": 0
            }
        },

So my fact gathering does have swap cached but it's null. It was set to null because swap cached is set from the file /proc/meminfo. And swapcached isn't defined in my file. I would imagine that's because this container hasn't swapped memory yet.
I did check some other containers and they do have SwapCached running.

Maybe you need to change your playbook to check if the fact is set.

**Comment by ticktockhouse** [comment]
Hi @sysadmin75,

My mistake - the fact should be 'swap.cached'. I was going be the error thrown above when gathering facts (or running 'ansible -m setup'). As I understand it, OpenVZ desn't have swap internal to the VM, but uses swap from the hypervisor if it needs to. Whatever the case, it doesn't present any swap memory to the VM. cat /proc/meminfo doesn't have a "SwapCached" line and Ansible (or the version that I'm running, at least, throws the above error as a result. On my system, 'ansible --version', gives 'ansible 1.9 (devel fef435cc2a) last updated 2015/01/29 13:33:00 (GMT +100)'. Should I update?

Just to clarify, I don't need this fact to continue with my role, it's just that after the error is thrown, the play fails, and i can't continue...

**Comment by bcoca** [comment]
So I found the line that causes this:

`'cached': memstats.get('swapcached'),`

and it should be simple to fix by just adding the optional default to the get

`'cached': memstats.get('swapcached', None),` or 'N/A' or 0? need to decide what default makes sense.

**Comment by bcoca** [comment]
actually, nevermind, this was already fixed by changing to use the get method, update to either the stable version or current devel and it should work. Closing this ticket as there is nothing to do.
