### ISSUE TITLE
ec2 dynamic_inventory tag issue

### ISSUE THREAD

**Issue by jpcarey** [ansible/ansible#11362]
The special characters escape to underscores in ec2.py does not appear to work poperly.
I have the following tag for an ec2 instance:
`aws:cloudformation:stack-name => imdev-flask-3-2-298-l1FiTlA`
Per the docs, this should translate to an underscore between stack and name: 'ec2_tag_aws_cloudformation_stack_name'
This does not work, and produced the following var undefined error:
`One or more undefined variables: 'ec2_tag_aws_cloudformation_stack_name' is undefined`
running ec2.py, the actual output is "ec2_tag_aws_cloudformation_stack-name": "imdev-flask-3-2-298-l1FiTlA"
If I try to use in the ec2.py form, ansible will throw an error for the invalid character:
`Failed to template msg="{{ ec2_tag_aws_cloudformation_stack-name == removed_version }}": Unable to look up a name or access an attribute in template string. Make sure your variable name does not contain invalid characters like '-'.`
However, accessing through the hostvars allows reference to the item with the "-". Ex:
`"{{  hostvars[inventory_hostname]['ec2_tag_aws_cloudformation_stack-name'] }}"`

**Comment by bennojoy** [comment]
@jpcarey85  are you using the latest  ec2.py  ?  https://github.com/ansible/ansible/blob/devel/plugins/inventory/ec2.py

**Comment by jpcarey** [comment]
I am using 576832e, but it looks like this might be fixed with c7f3362. I'll grab the latest and give it a try.

**Comment by jpcarey** [comment]
Latest ec2.py worked properly.  Might be nice to have some versioning...
