### ISSUE TITLE
Change in conditional result between 1.8 and 1.9

### ISSUE THREAD

**Issue by dlip** [ansible/ansible#11378]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8/1.9.1
##### Ansible Configuration:

no changes
##### Environment:

Centos 6
##### Summary:

A conditional that was working as I expected in 1.8 started resolving to true unexpectedly when upgrading to 1.9. It can be resolved by making the expression more explicit, but I thought I'd let you know just in case you didn't intend this effect. 
##### Steps To Reproduce:

When running this playbook in 1.8 with say_hello=false other_var=false would not print hello, but in 1.9.1 it executes

```
- hosts: localhost
  pre_tasks:
    - debug: msg="hello"
      when: say_hello and other_var is defined
```

```
ansible-playbook test.yml -e 'say_hello=false other_var=false'
```

```
TASK: [debug msg="hello"] *****************************************************
ok: [localhost] => {
    "msg": "hello"
}
```

It seems to be evaluating it like this:
`say_hello is defined and other_var is defined`

It can be fixed by being more explicit:
`say_hello == "true" and other_var is defined`
or
`say_hello and (other_var is defined)`
##### Expected Results:

Should not print hello
##### Actual Results:

Prints hello

**Comment by bcoca** [comment]
say_hello='false' might be interpreted as a string, try say_hello|bool to ensure it is evaluated as a boolean, we've updated this in current devel and should be a lot smarter about booleans.

**Comment by bcoca** [comment]
closing as per above
