### ISSUE TITLE
create 'when' as an alternative to only_if

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1138]
From my email to the mailing list

So only_if is pretty flexible and it will stay around.    We'll need it.

However I've never really been comfortable with asking people to write
Python expressions in a language that intentionally seeks to AVOID
such expressions.
This small corner of ansible is asking folks to understand a
programming language we obviously want to hide.

As such, I think "easy conditionals" becomes an interesting mini-theme
for the 0.9 release.

Tentative syntax follows.

Imagine if you could do things without Python or quoting:
- action: ...
  when_defined: foo

when_defined: some.var.foo

when_equal: command.rc 1

when_successful: command_register_result

when_failed:  command_register_result

when_greater_than: some.var.foo 12

when_all_of:
      - equal: result  0
      - find: some_command.stdout some_string

when_one_of:
      - equal: result.rc 0
      - equal: result2.rc 1

And, like before, you should be able to save 'when' tests in vars, like so:

when:  $is_rhel6

Internally, these would compile down to only_if expressions, but would
not require writing Python, quoting, or remembering what data types to
cast things to.  As a result, we keep conditional logic
simple, and make things easier to read.

**Comment by command-tab** [comment]
I like this idea a lot, particularly that it hides the underlying language!

**Comment by mpdehaan** [comment]
should also include a 'changed' function

**Comment by mpdehaan** [comment]
seems to be useful to also be able to attach a when or series of when's to a play, and have it auto-apply to all tasks underneath.

Though if playbooks import playbooks, we may have to be a little careful.

People may also expect when to be attachable to imports, so we should make sure that raises an error OR auto-applies the when to all things imported

**Comment by mpdehaan** [comment]
done, see examples/playbooks/conditionals_part_2.yml

syntax ended up being different to be more flexible
