### ISSUE TITLE
Ansible shows task processed while remote server is down

### ISSUE THREAD

**Issue by trompx** [ansible/ansible#11388]
Hello,

I don't know what kind of cache ansible has but I have two VMs started with vagrant :
- dev VM 
- ansible VM to provision the dev VM

When trying to prevent root login with "PermitRootLogin no". I struggle at first but noticed there was a bug on ubuntu 14.04 to restart ssh.

After restarting correctly ssh (stop then start), when trying to ssh to my dev VM with root, it was restricted, all good, but when replaying the playbook with the ansible VM, the task were still processed (while the playbook was used with root user so it should not be able to do anything).

I then "vagrant halt" my dev VM and tried again to run the playbook, same, the tasks were still proccessed with "ok" status... Same if I vagrant reload my ansible VM.

Any idea what's going on ?
1. Is there a way to specify an array of users to start a playbook (that would be really helpful) ?

**Comment by bcoca** [comment]
so this is not a ansible cache, this is how ssh itself works, specially when using control/persist master options.

by default ssh on restart will keep active connections alive, since you are already logged in as root and have a persistent connection it will not hit the rule.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
