### ISSUE TITLE
Documentation for the known_hosts module incorrectly refers to the 'path' argument as 'name'

### ISSUE THREAD

**Issue by josephsussman** [ansible/ansible#11395]
**Issue Type:**

Documentation Report

**Ansible Version:**

N/A

**Ansible Configuration:**

N/A

**Environment:**

N/A

**Summary:**

I noticed that a parameter called `name` is mentioned in the Options table in the following document:
http://docs.ansible.com/known_hosts_module.html

Based on the Examples and some experimentation, it appears that this should be `host`.

**Steps To Reproduce:**
1. Navigate to http://docs.ansible.com/known_hosts_module.html
2. Take note of the `name` parameter mentioned in the Options table and the `host` parameter used in the Examples.

**Expected Results:**

The Options table should mention the `host` parameter.

**Actual Results:**

The Options table mentions the `name` parameter, which is invalid for use with the known_hosts module.

**Comment by bcoca** [comment]
host is an alias for name, they both work.
