### ISSUE TITLE
Documentation is unclear on how to create groups of groups

### ISSUE THREAD

**Issue by jerrac** [ansible/ansible#11397]
Issue Type: Documentation Report

This documentation http://docs.ansible.com/intro_inventory.html#groups-of-groups-and-group-variables is what I am referring to. It is unclear that you need to add ":children" to the parent group's name in order for Ansible to know you are dealing with a group of groups.

It took me several experiments, and almost giving it up as buggy, for me to figure out what was needed. 

Could you state explicitly that group of groups needs the ":children" suffix?

Thanks!

**Comment by bcoca** [comment]
added to my todo list, but FYI you can also submit a PR as the documentation is part of this repo.

**Comment by jerrac** [comment]
Ah, looks like @mikeputnam has beat me to it. :+1: 

I was just going to take a look and see if I could figure out decent wording.
