### ISSUE TITLE
Variables About Other Hosts

### ISSUE THREAD

**Issue by raulSevilla** [ansible/ansible#11400]
I'm getting problems while trying to access variables from another host in my Ansible template.
I'm using a SSH proxycommand configuration to access 'internal' instances in EC2.
My inventory host file is like: 

```
cat  /etc/hosts
[test1]
test1
[test2]
test2
```

My SSH configuration:

```
Host test1
User ubuntu
IdentityFile /home/dev/.ssh/private-key
Hostname XX.XX.XX.XX
StrictHostKeyChecking no

Host test2
User ubuntu
IdentityFile /home/dev/.ssh/private-key
Hostname 10.0.1.10
ProxyCommand ssh -F /home/dev/thing/ssh_config -W %h:%p test1
StrictHostKeyChecking no
ControlMaster auto
ControlPath /home/dev/.ssh/tmp/%h_%p_%r

```

and my template is like:

{{ hostvars['test1'] }}
{{ hostvars['test2'] }}

The first line in the previous template gives me all host variables, but the second, only shows:
{'inventory_hostname': 'test2', 'group_names': ['test2'], 'inventory_hostname_short': 'test2'}

Why is this happening?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
