### ISSUE TITLE
Playbook relative callback_plugins not loaded

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#11411]
In testing playbook relative `callback_plugins`, it looks like `push_basedir` is not called early enough.

`TaskQueueManager._load_callbacks` is called before `Playbook._load_playbook_data`.  This prevents a playbook relative `callback_plugins` directory from functioning properly.

**Comment by sivel** [comment]
@jimi-c I tried the gist you provided (which one change to fix the spelling of basedirs), and it did not seem to resolve the problem.

I added 2 debug print statements, to see order of execution, and see:

```
LOADING CALLBACKS

PLAY: ***************************************************************************

TASK [test] *********************************************************************
MODIFYING _BASEDIRS
changed: [localhost]

PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

So it still looks like the callback plugins are loaded super early, which in a way makes sense.

If we can get this working, it may be possible to easily override the default `stdout` callback type, with a custom callback plugin altogether.  That would just be a bonus.

It looks like in order to make this work, we need to be able to inject the `playbook_dir` into the basedirs before `TaskQueueManager` is instantiated.  We could look at injecting new callbacks after TaskQueueManager instantiation, but that could limit the ability to override the stdout callback like mentioned above.

I've tested the following, which appears to work:

```
diff --git a/lib/ansible/executor/playbook_executor.py b/lib/ansible/executor/playbook_executor.py
index 4e77838..c1e34d6 100644
--- a/lib/ansible/executor/playbook_executor.py
+++ b/lib/ansible/executor/playbook_executor.py
@@ -20,6 +20,7 @@ from __future__ import (absolute_import, division, print_function)
 __metaclass__ = type

 import signal
+import os.path

 from ansible import constants as C
 from ansible.errors import *
@@ -30,6 +31,8 @@ from ansible.template import Templar
 from ansible.utils.color import colorize, hostcolor
 from ansible.utils.debug import debug

+from ansible.plugins import callback_loader
+
 class PlaybookExecutor:

     '''
@@ -46,6 +49,10 @@ class PlaybookExecutor:
         self._options          = options
         self.passwords         = passwords

+        for playbook_path in self._playbooks:
+            callback_path = os.path.join(os.path.dirname(playbook_path), 'callback_plugins')
+            callback_loader.add_directory(callback_path)
+
         if options.listhosts or options.listtasks or options.listtags or options.syntax:
             self._tqm = None
         else:
diff --git a/lib/ansible/plugins/__init__.py b/lib/ansible/plugins/__init__.py
index bbbe0bd..0b21ec9 100644
--- a/lib/ansible/plugins/__init__.py
+++ b/lib/ansible/plugins/__init__.py
@@ -302,6 +302,7 @@ class PluginLoader:
                     self._module_cache[path] = imp.load_source('.'.join([self.package, name]), path)

                 if kwargs.get('class_only', False):
                     obj = getattr(self._module_cache[path], self.class_name)
                 else:
                     obj = getattr(self._module_cache[path], self.class_name)(*args, **kwargs)
```

The only thing I didn't get working, and it may be unrelated, is being able to override the single `stdout` callback.

Also, since the callbacks are loaded so early, I'm not sure that shipping callbacks in a role for example would work.

Let me know your thoughts.

**Comment by jimi-c** [comment]
Testing this patch:

<pre>
diff --git a/lib/ansible/executor/task_queue_manager.py b/lib/ansible/executor/task_queue_manager.py
index b1d905b..169b08c 100644
--- a/lib/ansible/executor/task_queue_manager.py
+++ b/lib/ansible/executor/task_queue_manager.py
@@ -60,6 +60,7 @@ class TaskQueueManager:
         self._options          = options
         self._stats            = AggregateStats()
         self.passwords         = passwords
+        self._stdout_callback  = stdout_callback
 
         # a special flag to help us exit cleanly
         self._terminated = False
@@ -73,9 +74,6 @@ class TaskQueueManager:
 
         self._final_q = multiprocessing.Queue()
 
-        # load callback plugins
-        self._callback_plugins = self._load_callbacks(stdout_callback)
-
         # create the pool of worker threads, based on the number of forks specified
         try:
             fileno = sys.stdin.fileno()
@@ -206,6 +204,9 @@ class TaskQueueManager:
         are done with the current task).
         '''
 
+        # load callback plugins
+        self._callback_plugins = self._load_callbacks(self._stdout_callback)
+
         if play.vars_prompt:
             for var in play.vars_prompt:
                 if 'name' not in var:
diff --git a/lib/ansible/playbook/role/__init__.py b/lib/ansible/playbook/role/__init__.py
index c24e649..c84f0f8 100644
--- a/lib/ansible/playbook/role/__init__.py
+++ b/lib/ansible/playbook/role/__init__.py
@@ -37,7 +37,7 @@ from ansible.playbook.helpers import load_list_of_blocks
 from ansible.playbook.role.include import RoleInclude
 from ansible.playbook.role.metadata import RoleMetadata
 from ansible.playbook.taggable import Taggable
-from ansible.plugins import get_all_plugin_loaders
+from ansible.plugins import get_all_plugin_loaders, push_basedir
 from ansible.utils.vars import combine_vars
 
 
@@ -136,6 +136,8 @@ class Role(Base, Become, Conditional, Taggable):
         self._variable_manager = role_include.get_variable_manager()
         self._loader           = role_include.get_loader()
 
+        push_basedir(self._role_path)
+
         if parent_role:
             self.add_parent(parent_role)
 
diff --git a/lib/ansible/plugins/strategies/__init__.py b/lib/ansible/plugins/strategies/__init__.py
index 180cf32..6eae821 100644
--- a/lib/ansible/plugins/strategies/__init__.py
+++ b/lib/ansible/plugins/strategies/__init__.py
@@ -29,7 +29,7 @@ from ansible.inventory.group import Group
 from ansible.playbook.handler import Handler
 from ansible.playbook.helpers import load_list_of_blocks
 from ansible.playbook.role import ROLE_CACHE, hash_params
-from ansible.plugins import filter_loader, lookup_loader, module_loader
+from ansible.plugins import _basedirs, filter_loader, lookup_loader, module_loader
 from ansible.utils.debug import debug
 
 
@@ -44,6 +44,7 @@ class SharedPluginLoaderObj:
     the forked processes over the queue easier
     '''
     def __init__(self):
+        self.basdirs       = _basedirs[:]
         self.filter_loader = filter_loader
         self.lookup_loader = lookup_loader
         self.module_loader = module_loader
diff --git a/lib/ansible/template/__init__.py b/lib/ansible/template/__init__.py
index 1841560..8ce243f 100644
--- a/lib/ansible/template/__init__.py
+++ b/lib/ansible/template/__init__.py
@@ -29,7 +29,7 @@ from jinja2.runtime import StrictUndefined
 
 from ansible import constants as C
 from ansible.errors import AnsibleError, AnsibleFilterError, AnsibleUndefinedVariable
-from ansible.plugins import filter_loader, lookup_loader
+from ansible.plugins import _basedirs, filter_loader, lookup_loader
 from ansible.template.safe_eval import safe_eval
 from ansible.template.template import AnsibleJ2Template
 from ansible.template.vars import AnsibleJ2Vars
@@ -60,6 +60,8 @@ class Templar:
         self._available_variables = variables
 
         if shared_loader_obj:
+            global _basedirs
+            _basedirs = shared_loader_obj.basedirs[:]
             self._filter_loader = getattr(shared_loader_obj, 'filter_loader')
             self._lookup_loader = getattr(shared_loader_obj, 'lookup_loader')
         else:
</pre>

Test setup:

<pre>
### ./test.yml
- hosts: localhost
  gather_facts: no
  roles:
  - test
### ./roles/test/callback_plugins/foo.py
from ansible.plugins.callback import CallbackBase
print("this is the foo callback plugin")
class CallbackModule(CallbackBase):
    CALLBACK_VERSION = 2.0
</pre>

Output:

<pre>
$ ansible-playbook -vv test.yml
1 plays in test.yml
this is the foo callback plugin
PLAY: ***************************************************************************
PLAY RECAP **********************************************************************
</pre>

So this appears to fix things, as the print statement from the callback code in the role is displayed.

**Comment by sivel** [comment]
I'll give this a test tomorrow morning and report back.

**Comment by sivel** [comment]
@jimi-c LGTM.  Your new diff appears to work fine, except that in `SharedPluginLoaderObj.__init__` you have `self.basdirs` which is missing an `e` (should be `self.basedirs`)

Output:

```
CallbackModule.__init__
CallbackModule.v2_playbook_on_play_start

PLAY: ***************************************************************************

TASK [test] *********************************************************************
changed: [localhost]

PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

Example callback just for posterity:

```
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

from ansible.plugins.callback import CallbackBase

class CallbackModule(CallbackBase):
    CALLBACK_VERSION = 2.0

    def __init__(self, display):
        super(CallbackModule, self).__init__(display)
        self._display.display('CallbackModule.__init__')

    def v2_playbook_on_play_start(self, play):
        self._display.display('CallbackModule.v2_playbook_on_play_start')
```

**Comment by jimi-c** [comment]
Yep, I saw that typo and fixed it right after pushing that commit.

**Comment by jimi-c** [comment]
Closing now, thanks!

**Comment by jimi-c** [comment]
Commits were 927072546b4ffb12d6642643d44551de945b390f and 9785e5397eb0c761bcbb5655ef3a3dffe1f301d0

**Comment by rajeevd18** [comment]
hi ,

Need help. I am new to Ansible. Version I am using 2.3.0.
I tried both version of  human_log.py provided by Cliff, I am not seeing the format line -wise .

"For Ansible 2.x, please check out https://gist.github.com/dmsima... and/or https://github.com/n0ts/ansibl..."

The output before callback:
changed: [localhost] => (item=df /) => {"changed": true, "item": "df /", "rc": 0, "stderr": "", "stdout": "Filesystem     1K-blocks     Used Available Use% Mounted on\n/dev/sda1       73400320 16653756  56272996  23% /\n", "stdout_lines": ["Filesystem     1K-blocks     Used Available Use% Mounted on", "/dev/sda1       73400320 16653756  56272996  23% /"]}
changed: [localhost] => (item=cat /etc/hosts|grep -i localhost) => {"changed": true, "item": "cat /etc/hosts|grep -i localhost", "rc": 0, "stderr": "", "stdout": "127.0.0.1\tlocalhost\n::1             localhost ipv6-localhost ipv6-loopback\n", "stdout_lines": ["127.0.0.1\tlocalhost", "::1             localhost ipv6-localhost ipv6-loopback"]}


The output after callback: 
changed: [localhost] => (item=df /) => {"changed": true, "item": "df /", "rc": 0, "stderr": "", "stdout": "Filesystem     1K-blocks     Used Available Use% Mounted on\n/dev/sda1       73400320 16653740  56273012  23% /\n", "stdout_lines": ["Filesystem     1K-blocks     Used Available Use% Mounted on", "/dev/sda1       73400320 16653740  56273012  23% /"]}

msg: All items completed

msg: All items completed
changed: [localhost] => (item=cat /etc/hosts|grep -i localhost) => {"changed": true, "item": "cat /etc/hosts|grep -i localhost", "rc": 0, "stderr": "", "stdout": "127.0.0.1\tlocalhost\n::1             localhost ipv6-localhost ipv6-loopback\n", "stdout_lines": ["127.0.0.1\tlocalhost", "::1             localhost ipv6-localhost ipv6-loopback"]}
==================

Appreciate if someone can advice.

Thanks much
Raj

**Comment by jimi-c** [comment]
@rajeevd18 the best place to ask for help is on IRC or our mailing lists:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

**Comment by rajeevd18** [comment]
Thanks you James, I posted on the forum


Rajeev
