### ISSUE TITLE
Feature: run_once_per: "{{ ansible_machine_id }}"

### ISSUE THREAD

**Issue by vdboor** [ansible/ansible#11437]
There have been mutliple suggestions for running a task "once per group". However, I think the following would give a nice benefit over existing idea's.

I'd love to see a syntax such as:

`run_once_per: {{ variable }}`.

Examples:
- `run_once_per: ansible_ssh_host`
- `run_once_per: database_name`

This would give admins the option to limit certain tasks (such as db upgrades). I don't find the hack of `when: inventory_hostname == webservers[0]` sufficient, because some sites may only run at `webservers[1]` for example. Some sites may share the same database, others use a different one (e.g. multiple beta/production sites in a single playbook).

Internally, Ansible could keep a set of "have I seen {{ variable }} before?" and skip the task if that's the case. If I have more time, I'd be happy to contribute this feature, but for now I'd figured it would be better to at least report it - and see if there is feedback on this idea.

**Comment by srgvg** [comment]
How excatly would the host a task runs on be matched with that `{{ variable }}`?

"have I seen {{ variable }} before?" sounds a bit fuzzy  :)

**Comment by sivel** [comment]
Can you perhaps explain how the existing `run_once` does not meet your needs?  Also be aware that you can use `delegate_to` with `run_once` to define the specific host you would like the task to execute on.

**Comment by vdboor** [comment]
Thanks for the quick reply guys!

>  How excatly would the host a task runs on be matched with that {{ variable }}?
> "have I seen {{ variable }} before?" sounds a bit fuzzy :)

Perhaps this is better explained in pseudocode:

```
for task in playbook_tasks:
    seen = set()
    for host in selected_hosts:
        if task.run_once_per:
            value = evaluate_jinja2(task.run_once_per, current_context)
            if value in seen:
                skip_this_task   # a previous host is already running this task.
                continue
            seen.add(value)

        execute_task_on_host(task, host)
```

> Can you perhaps explain how the existing run_once does not meet your needs? 
> Also be aware that you can use delegate_to with run_once to define the specific host you would like the task to execute on.

It seems a lot can be hacked by using delegate_to properly, though it may require some hostname hacking.

I have a playbook that updates multiple websites. To leverage ansible's power, each canonical domain name is a host entry in the inventory file (so it has it's group_vars and host_vars) - but with an an `ansible_ssh_host` attached that defines where it should be deployed. Super flexible and it gives parallel execution too regardless of where the sites are hosted.

Now, some sites use database1, others use database2. Both databases reside on the same db server.
The db-update task should run once for database1, and once for database2.

So I guess that could be hacked now by having two hostnames for the database, so you can combine `run_once` with `delegate_to` but it seems a bit hacky.

Some other tasks (e.g. flush memcached) should be executed once per actual server. I guess delegate_to can be used for that case.

In both cases `run_once_per: "{{ database_name }}"` or `run_once_per: "{{ ansible_machine_id }}"` offers much more control and imho gives clarity over what is intended.

**Comment by bcoca** [comment]
I would actually recommend making it a play over the database server group, in which case the task will only run once per each database. If you need to run the task from a webserver, you can then use delegate_to, it will still run only once per db and no need to use run_once.

Im closing this ticket as I don't see us implementing this feature as ansible already has ways to achieve this.
