### ISSUE TITLE
file / mkdir nonatomic checks

### ISSUE THREAD

**Issue by jan-grant** [ansible/ansible#11455]
We caught this due to a broken playbook, nonetheless it bears fixing.

The behaviour was caught due to a delegate_to: localhost; file: dest=/tmp/foo state=directory. This ran once per host in the target group.

Basically, ansible raced itself: it checked that the directory was not present (multiple times) then attempted to create it. Some of those creations failed with an OSError 17 - EEXIST.

The file module should probably simply attempt a mkdir (which'll happen atomically) and then catch and deal with the resulting errors - determining, for instance, that a directory already existed there.

I appreciate that this is a corner case; you might want to WONTFIX this - there's no atomic test-and-set on a posix filesystem.

**Comment by jan-grant** [comment]
(Raising the bug even if it's closed so that people might find it in future.)

**Comment by bcoca** [comment]
we were aware of the race condition, the check happens mostly to be able to return changed=true/false and we should ignore eexist when trying to create (we do this in other parts of the code already).

**Comment by bcoca** [comment]
closing as it is known issue that modules that operate on same file cannot run concurrently on same host w/o issues.
