### ISSUE TITLE
Commandline option --ask-become-pass

### ISSUE THREAD

**Issue by pujan14** [ansible/ansible#11471]
Hi,

From ansible 1.9 there is new privilege escalation method and thus new command line options.
To use ansible with sudo and password it should be used like ansible-playbook --become --ask-become-pass
Here I think --ask-become-pass implicitly means that user wants to use --become and thus ansible-playbook --ask-become-pass should work same as ansible-playbook --become --ask-become-pass.

**Comment by bcoca** [comment]
no, as you may have a play that only has a few tasks you want to use privilege escalation for, you will still need the password but you don't want to globally force all tasks to run as a different user.
