### ISSUE TITLE
Unexpected variable behaviour in roles / includes

### ISSUE THREAD

**Issue by iby** [ansible/ansible#11476]
Consider having this:

```
roles
  role1
    tasks
      main.yml
      task1.yml
    vars
      task1.yml
```

Task `main.yml` does something like this:

``` yml
- include_vars: task1.yml
- include: task1.yml
```

And `vars/task1.yml` has something like this:

``` yml
dt: "{{ hostvars[play_hosts[0]].ansible_date_time }}"
timestamp: "{{ dt.year }}-{{ dt.month }}-{{ dt.day }}-{{ dt.hour }}-{{ dt.minute }}-{{ dt.second }}"
```

When vars get included they are automatically set as facts, but not as properly rendered values, but as actual the text, e.g., `timestamp: "{{ dt.year }}-{{ dt.month }}-{{ dt.day }}-{{ dt.hour }}-{{ dt.minute }}-{{ dt.second }}"` instead of `2015-01-01-01-01-01`.

When accessing them within the same host they get rendered as values, so that doesn't come as a problem. But if I want to reuse `timestamp` var / fact on other hosts, I run into whole bunch of problems, because it is effectively a template, not a value, because it references other host-specific variables, i.e., `dt` in this case. As a workaround I can do this on the host where I included those vars:

``` yml
timestamp: "{{ timestamp }}"
```

This will update the fact value from template to the actual rendered value.

I also noticed that if I rename `vars/task1.yml` into `vars/main.yml` to automatically include the variables, they don't appear in facts. They are still accessible, but not visible when debugging. That seems like a serious inconsistency between roles and includes?

Hope this makes sense and useful in some way.

**Comment by bcoca** [comment]
this is how it actually behaves, vars don't get templated when included, but when used, which of course then depends on the host's gathered facts and the timestamp when that happened.

include_vars sets vars as facts for the current host, main/vars.yml gets imported as play variables, not host variables. I've always thought we should have named it include_facts, not include_vars, basically it works as a file version of set_fact.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
