### ISSUE TITLE
Where have the special template variables gone??

### ISSUE THREAD

**Issue by tonk** [ansible/ansible#11479]
I'm running Ansible develop version, straight from Github and since a couple of weeks I have a problem
I cannot explain. I think it's since the switch to v2 as the default tree, but I'm not completely sure of that.

I have a lot of templates (almost all of them) that start of with:

```
#
# Ansible information:
#     Filename : {{ template_path|replace("/etc/ansible", "...") }}
#     Filedate : {{ ansible_managed }}
#     Hostname : {{ ansible_hostname }}
#
```

But since the problem started I get errors about the `template_path` variable not being found.

Looking further it seems that none of the (six) special template variables can be found.
(`ansible_managed`, etc).

When I look into the code I see the comments in `./lib/ansible/modules/core/files/template.py`
but there is no code.

Has this code been moved or accidentally removed?

**Comment by bcoca** [comment]
I think they are  'not ported yet', we rewrote most of the core and some features have not been completed.

**Comment by tonk** [comment]
Aah, I thought I messed up something. I thought v2 was almost done, my bad.

If time permits I'll have a look if I can lend a hand.

**Comment by bcoca** [comment]
almost ... but this is one thing we had not done yet

**Comment by bcoca** [comment]
closing via f67949e42c3db5a0c6c242eecdd963f78cbfeb4d
