### ISSUE TITLE
make test_galaxy fails

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#11486]
A lot of code that was at the heart of ansible-galaxy has been ripped out and not replaced. 

This means that make test_galaxy trivially fails

We need something to replace ansible.utils.role_yaml_parse and ansible.utils.role_spec_parse, and make test_galaxy should pass its tests (those tests exist for a reason!)

**Comment by bcoca** [comment]
i'm still in the process of reworking the interaction with roles for the install function, most of the other functionality is there.

**Comment by bcoca** [comment]
closing as dupe of #11179
