### ISSUE TITLE
Add CHANGELOG entry for version 1.9.2

### ISSUE THREAD

**Issue by astorije** [ansible/ansible#11499]
Right now the [CHANGELOG](https://github.com/ansible/ansible/blob/2c9d1257ba59e01c093a901cf53a7323c56f4f85/CHANGELOG.md) contains info for version 1.9.1 and future version 2.0 but not for the most recent version 1.9.2.

**Comment by bcoca** [comment]
fixed via 2962047b438e46e874efa3bec846eeb60e0b89e8

**Comment by astorije** [comment]
Thanks @bcoca!
