### ISSUE TITLE
changes introduced by #9404 not documented

### ISSUE THREAD

**Issue by Lx** [ansible/ansible#11491]
##### Issue Type:

Documentation Report
##### Ansible Version:

```
$ ansible --version
ansible 1.9.2
  configured module search path = None
```
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

Pull Request #9404 by @mmoya (merged on 31 Jan 2015) introduces `retry_files_enabled` and `retry_files_save_path` configuration settings, but these are not described in [the current documentation for such settings](http://docs.ansible.com/intro_configuration.html#general-defaults).
##### Steps To Reproduce:

[Google `ansible "retry_files_enabled"`](https://google.com/?q=ansible+%22retry_files_enabled%22).
##### Expected Results:

Official Ansible documentation describing the `retry_files_enabled` and `retry_files_save_path` configuration settings and how to use them.
##### Actual Results:

A [single official Ansible example configuration file](https://github.com/ansible/ansible/blob/devel/examples/ansible.cfg) with this description for the two settings:

```
# retry files
```

**Comment by StephenWeber** [comment]
Appears to be addressed in [devel](https://github.com/ansible/ansible/blob/devel/examples/ansible.cfg#L171-L174) and [v2.0.0-0.8.rc3](https://github.com/ansible/ansible/blob/v2.0.0-0.8.rc3/examples/ansible.cfg#L171-L174) by #12417

Is this sufficient to close the issue?

**Comment by jimi-c** [comment]
Sorry for the late follow-up, but it does appear that these options have since been documented so we will close this issue now.

Thanks!
