### ISSUE TITLE
FAILED => SSH Error: buffer_append_space: insufficient buffer space

### ISSUE THREAD

**Issue by amosbird** [ansible/ansible#11509]
I'm using ansible on Msys2 to manage my linux cluster, however I keep getting "buffer_append_space: insufficient buffer space". What's wrong?

**Comment by bcoca** [comment]
so that sounds like a resource issue, also we do not support cygwin as a controller.

In any case this is a question, more appropriate for the mailing lists/irc channel than as a bug report.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
