### ISSUE TITLE
Typo http://docs.ansible.com/stat_module.html

### ISSUE THREAD

**Issue by duanebc** [ansible/ansible#11516]
Size in bytes for a plain file, ammount of data for some special files

Was just looking at this documentation, hope this is the correct place.  Will post link on IRC.

**Comment by illogicalextend** [comment]
What?

You can open a pull request if you found a typo.

**Comment by bcoca** [comment]
I don't understand what you are trying to ask/propose, so as @illogicalextend mentions please open a PR with the doc changed, if that is what you want.  Closing this ticket.
