### ISSUE TITLE
yum module in ansible 1.9.2 fails when package already installed

### ISSUE THREAD

**Issue by aabdnn** [ansible/ansible#11526]
Issue Type: Bug Report

Ansible Version:

$ ansible --version
ansible 1.9.2
  configured module search path = None

Ansible Configuration:

ANSIBLE_HOST_KEY_CHECKING=no
ANSIBLE_INVENTORY=/Users/anandb/repos/ripe/ansible/hosts
ANSIBLE_GATHERING=smart
ANSIBLE_REMOTE_TEMP=/tmp
ANSIBLE_SSH_CONTROL_PATH=/Users/anandb/.ssh/mux/%%r@%%h:%%p
ANSIBLE_HASH_BEHAVIOUR=merge
ANSIBLE_TIMEOUT=75
ANSIBLE_RETRY_FILES_ENABLED=no
ANSIBLE_SSH_PIPELINING=yes

Environment:

Managing CentOS 6 from OSX 10.10.4

Summary:

An ansible task to install 3 packages using "yum", that works under Ansible 1.9.1, fails under 1.9.2.

Steps To Reproduce:

On a newly-installed CentOS 6 system (which already has exim installed by kickstart), run the following task:
- yum: name={{ item }}
  with_items:
  - epel-release
  - exim
  - python-virtualenv

NB: "exim" and "python-virtualenv" are only available in the EPEL repository. That's why my task first installed the "epel-release" package, which makes available the epel yum repo files. The next 2 installation steps will be able to find "exim" and "python-virtualenv" in the EPEL repo and install/update/skip them as needed.

Expected Results:

Ansible should first install epel-release, then skip installing exim (which is already installed), and finally install python-virtualenv.

Actual Results:

failed: [ns1.nl-ams.as112.ripe.net] => (item=epel-release,exim,python-virtualenv) => {"changed": false, "failed": true, "item": "epel-release,exim,python-virtualenv", "rc": 0, "results": ["exim-4.72-7.el6.x86_64 providing exim is already installed"]}
msg: No Package matching 'python-virtualenv' found available, installed or updated

**Comment by abadger** [comment]
Moved issue to the module repo: https://github.com/ansible/ansible-modules-core/issues/1687
