### ISSUE TITLE
win_chocolatey missing/broken in Ansible 1.9.2

### ISSUE THREAD

**Issue by slimandslam** [ansible/ansible#11539]
Ansible 1.9.2 on MacOSX.

This code:

tasks:
    - name: Get Powershell remoting script
      win_chocolatey:
      name: PSWindowsUpdate
      state: present

responds with:

ERROR: state is not a legal parameter in an Ansible task or handler

the documentation for win_chocolatey says:

New in version 1.9

**Comment by jhawkesworth** [comment]
Could be formatting getting lost in my mail client but I think your
indentation might be incorrect. Can you check your playbook is valid yaml?
I use the yamllint site or notepad++ to check my yaml is OK.

Hope this helps

Jon

**Comment by slimandslam** [comment]
yamllint says it's valid YML.

**Comment by legleux** [comment]
It's valid _YAML_, but it's not the correct syntax for an ansible play. That is you're not telling ansible what you _think_ you're telling ansible.

For both of your presented problems, the indentation is wrong.
It's slightly confusing if you're not used to looking at YAML but http://www.yamllint.com/ does make it more obvious. 
Indentation is necessary. or if you get mad... just do this:
tasks:
    - name: Get Powershell remoting script
      win_chocolatey: name=PSWindowsUpdate state=present

**Comment by legleux** [comment]
Github just lost my indentation. Bad example. I am assuming what you posted on the mailing list is verbatim what you tried, which had the wrong indentation. I posted a reply there that had the correct formatting.

**Comment by slimandslam** [comment]
You're correct.  Please close this issue.
