### ISSUE TITLE
Race condition running a playbook concurrency

### ISSUE THREAD

**Issue by alexclifford** [ansible/ansible#11543]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible 1.9.2
##### Ansible Configuration:

```
[defaults]
library = /etc/ansible/library
```
##### Environment:

Ubuntu 14.04 LTS
##### Summary:

When a playbook is run more than once concurrency from one host to another a suspected race condition occurs
##### Steps To Reproduce:

I think there might be a race condition in the function involving https://github.com/ansible/ansible/blob/5ce3988d8693357f671f3fbec43b2d3b862db5f6/v1/ansible/utils/__init__.py#L319

If I run the same playbook twice against the same host it is possible that one of the runs dies with the following:

```
GATHERING FACTS ***
fatal: [web.tst.example.com] => Could not make dir /var/lib/jenkins/.ansible/cp: [Errno 17] File exists: '/var/lib/jenkins/.ansible/cp'
```

My use case is I have Jenkins jobs running a playbook against a host that manages Apache config along with some application specific settings. Even if I do run two Jenkins jobs at the same time the above doesn't always happen so it leads me to suspect a race condition during the temporary directory creation.

Is there a reason this directory isn't also unique per run as the things placed under it?
##### Expected Results:

I'd expect each separate playbook run not to try to create and delete the same directory so they can happily run side by side.
##### Actual Results:

If I run the same playbook twice against the same host it is possible that one of the runs dies with the following:

```
GATHERING FACTS ***
fatal: [web.tst.example.com] => Could not make dir /var/lib/jenkins/.ansible/cp: [Errno 17] File exists: '/var/lib/jenkins/.ansible/cp'
```

**Comment by bcoca** [comment]
duplicate, already fixed via #11127
