### ISSUE TITLE
can't work [ dot or source command ]???

### ISSUE THREAD

**Issue by my-dev** [ansible/ansible#11542]
Nice to meet you.

Ansible is very nice tool!!!

Now, I wanna do below

----------------------------------------
shell: |
  echo "export JAVA_HOME=/usr/java/default
  export MYPATH=/usr/local/xxx
  export PATH=\$MYPATH/bin:\$JAVA_HOME/bin:\$PATH" > /etc/profile.d/zzz.sh
  source /etc/profile.d/zzz.sh
----------------------------------------

but,  this environment variables is not reflected...

[ . /etc/profile.d/zzz.sh ] is similar too...

If you can do, please teach me how to do this...

**Comment by bcoca** [comment]
you are better using the environment keyword:

environment:
   JAVA_HOME: /usr/java/default
   MYPATH=/usr/local/xxx 
   PATH=\$MYPATH/bin:\$JAVA_HOME/bin:\$PATH" > /etc/profile.d/zzz.sh

also note that the environment for one task is not kept for the next

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by my-dev** [comment]
Hi!

Mr or Mrs, boca...

I see...Thank you for your advise.
I try it soon.

Thank you.
