### ISSUE TITLE
Add Solaris platform to ansible-galaxy

### ISSUE THREAD

**Issue by mcarpenter** [ansible/ansible#11547]
bin/ansible-galaxy:

```
# Below are all platforms currently available. Just uncomment
# the ones that apply to your role. If you don't see your 
# platform on this list, let us know and we'll get it added!
```

So here I am :) I don't see Solaris in this list, which should include versions 10 and 11.

This is probably enough detail . Although Solaris does have sub-releases (Solaris 10 calls them updates eg 10u3, 11 calls them SRUs written eg 11.2) I can't think of a scenario where I'd need to differentiate on sub-release version and collecting minor versions obviously increases maintenance overhead. (I see Red Hat versions only extend as far as the major version number, too, so there is precedent).

**Comment by bcoca** [comment]
cc @gregdek platforms are pulled from the galaxy server

**Comment by liquidat** [comment]
The support should include - and differentiate - Solaris 10 and 11:
- name: Solaris
  versions:
  - all
  - 10
  - 11.0
  - 11.1
  - 11.2
  - 11.3

**Comment by gregdek** [comment]
@liquidat could you do us a favor and file at https://github.com/ansible/galaxy-issues/issues? We've got some other platform adds we'll be doing soon, so we should be able to get to this quickly.

**Comment by liquidat** [comment]
Done, see https://github.com/ansible/galaxy-issues/issues/102
