### ISSUE TITLE
ansible-galaxy -p doens't override requirements.yml path

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/ansible#11548]
##### Issue Type:

"Bug Report"
##### Ansible Version:

1.9.2
##### Ansible Configuration:

Nothing of note.
http://pastebin.com/1uz0NUEq
##### Environment:

N/A
##### Summary:

`-p` command line option does not override Ansible galaxy role installation from file with `path` variable specified.
##### Steps To Reproduce:

`requirements.yml`

```
- src: https://github.com/chrismeyersfsu/role-required_vars
  path: who_cares
  name: required_vars
```

`ansible-galaxy install -r requirements.yml -p /tmp/ --force`
##### Expected Results:

For `role-required_vars/*` role to be installed in `/tmp/required_vars`
##### Actual Results:

`role-required_vars/*` is installed in `./who_cares/required_vars`

**Comment by chrismeyersfsu** [comment]
Tried to test on devel branch and ran into this problem https://github.com/ansible/ansible/issues/11549

**Comment by bcoca** [comment]
can you test against current devel, this seems to be working for me now

```
#>ansible-galaxy install -r req.yml -vvvv -p /var/tmp
Using /etc/ansible/ansible.cfg as config file
- extracting required_vars to /var/tmp/required_vars
- required_vars was installed successfully
```

**Comment by chrismeyersfsu** [comment]
Works ! :tada: :balloon:
