### ISSUE TITLE
Regression:  ansible_version variable not defined in Ansible 2.0

### ISSUE THREAD

**Issue by trinitronx** [ansible/ansible#11545]
A variable `ansible_version` and `version_compare` filter were added in #6619 & #6584 (ansible/ansible@d240e2b9fbed63cb1e23289af392450eb081e119) to allow playbooks to check Ansible version for feature / module compatibility.  This feature has vanished in Ansible 2.0.

I wrote a test playbook to check for this, and ran against multiple versions of Ansible:

`playbooks/ad-hoc/test_ansible_version.yml`:

``` yaml
- name: Test Ansible Version
  hosts: localhost
  gather_facts: true
  tasks:
    - name: What is ansible_version?
      debug:
        var=ansible_version
## Example Usage (also breaks due to syntax error in 2.0)
#    - assert:
#      that:
#        - "{{ ansible_version is defined }}"
#        - "{{ ansible_version|version_compare(1.9.2, '>=') }}"
```

It appears that the function which determines ansible version has moved from: [`lib/ansible/utils/__init__.py`](https://github.com/ansible/ansible/pull/6619/files#diff-cea96e7ed2dad65a7b37c9b9daa86d62R650) to [`lib/ansible/cli/__init__.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/__init__.py#L339).  It used to have been set here: [`lib/ansible/playbook/__init__.py`](https://github.com/ansible/ansible/pull/6619/files#diff-fc760c36dc6711859d36682f1b52b8f9R180).

The commits where things were moved were:
- ansible/ansible@040a39f249b1de57befb485ab7ee406f4cd9898a
- ansible/ansible@ce3ef7f4c16e47d5a0b5600e1c56c177b7c93f0d

Hope this helps track it down!
## Broken in Ansible 2.0

```
→ ansible --version
ansible 2.0.0 (devel b5f3e84014) last updated 2015/07/09 03:22:51 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 8257053756) last updated 2015/07/09 03:22:58 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 639902ff20) last updated 2015/07/09 03:22:59 (GMT +000)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/07/09 03:23:01 (GMT +000)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/07/09 03:23:03 (GMT +000)
  configured module search path = /opt/ansible/ansible/library

→ ansible-playbook -i inventory/hosts  playbooks/ad-hoc/test_ansible_version.yml  -vv --diff
Using /tmp/ops-ansible-playbooks/ansible.cfg as config file
1 plays in playbooks/ad-hoc/test_ansible_version.yml

PLAY: Test Ansible Version ******************************************************

TASK [setup] ********************************************************************
ok: [127.0.0.1]

TASK [What is ansible_version?] *************************************************
ok: [127.0.0.1] => {
    "changed": false,
    "ansible_version": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP **********************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0
```
## Works in older versions of Ansible

```
→ ansible-playbook --version
ansible-playbook 1.9.0.1
  configured module search path = /usr/share/ansible

→ ansible-playbook -i inventory/hosts playbooks/ad-hoc/test_ansible_version.yml  -vv --diff

PLAY [Test Ansible Version] ***************************************************

GATHERING FACTS ***************************************************************
<127.0.0.1> REMOTE_MODULE setup

ok: [127.0.0.1]

TASK: [What is ansible_version?] **********************************************

ok: [127.0.0.1] => {
    "var": {
        "ansible_version": {
            "full": "1.9.0.1",
            "major": 1,
            "minor": 9,
            "revision": 0,
            "string": "1.9.0.1\n  configured module search path = /usr/share/ansible"
        }
    }
}

PLAY RECAP ********************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0
```

```
→ ansible-playbook --version
ansible-playbook 1.9.2
  configured module search path = /usr/share/ansible

→ ansible-playbook -i inventory/racktables.py  playbooks/ad-hoc/test_ansible_version.yml  -vv --diff

PLAY [Test Ansible Version] ***************************************************

GATHERING FACTS ***************************************************************
<localhost> REMOTE_MODULE setup

ok: [localhost]

TASK: [What is ansible_version?] **********************************************

ok: [localhost] => {
    "var": {
        "ansible_version": {
            "full": "1.9.2",
            "major": 1,
            "minor": 9,
            "revision": 2,
            "string": "1.9.2\n  configured module search path = /usr/share/ansible"
        }
    }
}

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by nicolasrusconi** [comment]
Any chance that this was broken again in 2.1.0.0?

I get the following error

`
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "blockinfile"}, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/c7/wbkyhcfj69dcsvp3464g0knh0000gn/T/ansible_LdWHtB/ansible_module_blockinfile.py\", line 290, in <module>\n    main()\n  File \"/var/folders/c7/wbkyhcfj69dcsvp3464g0knh0000gn/T/ansible_LdWHtB/ansible_module_blockinfile.py\", line 226, in main\n    if ANSIBLE_VERSION.startswith('1.'):\nNameError: global name 'ANSIBLE_VERSION' is not defined\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
`

**Comment by jimi-c** [comment]
@nicolasrusconi variables are case-sensitive, so `ANSIBLE_VERSION` needs to be lower case.

**Comment by nicolasrusconi** [comment]
thanks @jimi-c , it looks like it was an issue in 2.1.0.0 release, see https://groups.google.com/forum/#!topic/ansible-project/JdnsZfQot70

**Comment by alform** [comment]
Blockinfile still has the problem in  v2.2.0 (ansible 2.2.0 (devel 787616cb39) last updated 2016/07/08 13:28:53 (GMT +200))

**Comment by abadger** [comment]
It does not have the problem.  Make sure that you've updated the ansible-modules-extras submodule, not just the main ansible/ansible repository.  Here's the current code that's in the devel branch: https://github.com/ansible/ansible-modules-extras/blob/devel/files/blockinfile.py#L247

and in the stable-2.1 branch: https://github.com/ansible/ansible-modules-extras/blob/stable-2.1/files/blockinfile.py#L247

which show that the current code is not using ANSIBLE_VERSION.

**Comment by alform** [comment]
That was indeed what was biting me. git submodule update --recursive set it straight. Thank you @abadger for pointing it out.
