### ISSUE TITLE
Ansible not reading environment variables in /etc/bash.bashrc 

### ISSUE THREAD

**Issue by gadelkareem** [ansible/ansible#11550]
ansible_env only gets the environment variables in /etc/environment which has some limitation with defining them. Is that be design or a possible bug?

**Comment by bcoca** [comment]
no bug, ansible is a batch utility and does not do an interactive login nor source .bashrc

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
