### ISSUE TITLE
Ansible is unable to configure multiple permitopen authorized_key options

### ISSUE THREAD

**Issue by mulander** [ansible/ansible#11559]
The ansible documentation states that:

> ```
>  A string of ssh key options to be prepended to the key in the authorized_keys file
> ```

source: http://docs.ansible.com/authorized_key_module.html

The ssh documentation states:

> permitopen="host:port"
>    Limit local port forwarding with ssh(1) -L such that it may only connect to the specified host and port. IPv6 addresses can be specified by enclosing the address in square brackets. **Multiple permitopen options may be applied separated by commas.** No pattern matching is performed on the specified hostnames, they must be literal domains or addresses. A port specification of \* matches any port.

With the above in mind I'm testing the following ansible rule:

``` yaml

  authorized_key: user={{ item }}
                  key_options='no-agent-forwarding,no-X11-forwarding,permitopen="10.9.8.1:8080",permitopen="10.9.8.1:9001",permitopen="10.9.8.1:7767",permitopen="10.9.8.1:9900",permitopen="localhost:3001",permitopen="localhost:3002",permitopen="localhost:3003"'
                  key="{{ lookup('file', 'public_keys/' + item + '.pub') }}"
                  path="/home/{{ item }}/.ssh/authorized_keys"
                  manage_dir=no
                  state=present
```

This results in a key being added but with subsequent permitopen options being overwritten by the last parsed value:

```
root@build:~# cat /home/mulander/.ssh/authorized_keys 
no-agent-forwarding,no-X11-forwarding,permitopen="localhost:3003",permitopen="localhost:3003",permitopen="localhost:3003",permitopen="localhost:3003",permitopen="localhost:3003",permitopen="localhost:3003",permitopen="localhost:3003" ssh-rsa AAA
```

Please notice that all hosts and ports were replaced by `localhost:3003` which is the last `permitopen` entry. This overwrites both the host & port. The issue is most probably caused by parsing the values into a `dict` using the `permitopen` as the key. The value should be kept as an array in order not to loose configuration.

Tested on ansible 1.7.2

**Comment by bcoca** [comment]
# Should This Be Filed Elsewhere?

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be something that should be filed against another project or bug tracker, and let us explain our reasons for thinking this:
- authorized_keys actually lives under http://github.com/ansible/ansible-modules-core

If you can stop by the tracker or forum for one of those projects, we'd appreciate it.  

Should you still wish to discuss things further, or if you disagree with our thought process, please stop by one of our two mailing lists:
- https://groups.google.com/forum/#!forum/ansible-project
- https://groups.google.com/forum/#!forum/ansible-devel

We'd be happy to discuss things.

Thank you once again!

**Comment by mulander** [comment]
Thank you for pointing me to the correct repository. The issue [has been reported](https://github.com/ansible/ansible-modules-core/issues/1715).
