### ISSUE TITLE
Add element to array for multiple array

### ISSUE THREAD

**Issue by dazorni** [ansible/ansible#11558]
If tried to go over a multiple array and save a element only if the state `skipped` is not `true` or doesn't exist. I think code is easier to understand for all of us, so i made an example in php.

``` php
$result = [
  'results' => [
    [
      'ssh_key' => [
        'id' => 100001,
        'name' =>'username'
      ]
    ],
    [
      'ssh_key' => [
        'id' => 100002,
        'name' =>'username'
      ]
    ],
    [
      'skipped' => true
    ]
  ]
];

$keyIds = [];

foreach ($result['results'] as $item) {
  if (! array_key_exists('skipped', $item) || $item['skipped'] != true)
    $keyIds[] = $item['ssh_key']['id'];
}

// result
array(1) {
  [0] => int(100001),
  [1] => int(100002)
}

```

Is there a way to do exactly the same in ansible? I tried a lot!

Thanks for your help!

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
