### ISSUE TITLE
sshpass fails to handle custom (FreeBSD) ssh prompt causing hangs

### ISSUE THREAD

**Issue by sysfu** [ansible/ansible#11565]
Issue Type: Bug Report

Ansible Version: 1.9.2

Ansible Configuration: 
[defaults]
hostfile=inventory
roles_path=roles

Environment:
Controller - Parabola GNU/Linux x64
Target - FreeBSD 10 x64

Summary: [Long standing bug in sshpass](http://sourceforge.net/p/sshpass/bugs/12/) dependency causes ansible commands using SSH username-password authentication to fail. Running the same command via SSH key authentication works fine.

Steps To Reproduce:
Setup a new FreeBSD 10x target. Attempt to run the following command against the new target

```
ansible -vvvv hostname.tld -u root -k -m raw -a 'uname' 
```

Expected Results:
Command completes and returns raw module output (in this case, uname)

Actual Results:
Command hangs indefinitely.

**Comment by bcoca** [comment]
This is due to ~~Openssh~~ FreeBSD using their own custom prompt ~~(hardcoded in the C source)~~  and sshpass not adapting to it. ~~This will probably start appearing elsewhere as distros upgrade to the latest Openssh.~~

The workaround is to not use password prompts (ssh keys), but this is very limiting, specially when trying to automate BSD bootstrapping.

**Comment by bcoca** [comment]
so it seems to come from a FreeBSD pam module https://forums.freebsd.org/threads/sshd-custom-password-prompt.38184/

This also includes it's own workaround by customizing the prompt to the one most other systems use. 

the change was to pam_unix.so not to Openssh as I first thought.

**Comment by bcoca** [comment]
a better workaround use the paramiko connection, which bypasses the sshpass call

**Comment by asifiqbal** [comment]
paramiko does not work for freebsd systems that have sftp disabled

**Comment by opsec** [comment]
Please have a look at

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=204819
and
https://lists.freebsd.org/pipermail/freebsd-stable/2015-November/083710.html
and following posts.

**Comment by bcoca** [comment]
sshpass has been updated to handle this but this version is not included in any OS/distro i've seen yet.

**Comment by f-andrey** [comment]
This patch sshpass need patching ansible ssh.py, for send new parameter -P and his value

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be something that should be filed against another project or bug tracker, and let us explain our reasons for thinking this:
- sshpass has patched this issue and added the -P flag, but no releases have been made. If they do make a release and the distros pull it down, we can look into patching ansible to take in a user defined prompt string. Until then, we aren't going to be able to do anything short of rewriting sshpass.

If you can stop by the tracker or forum for one of those projects, we'd appreciate it.  

Should you still wish to discuss things further, or if you disagree with our thought process, please stop by one of our two mailing lists:
- https://groups.google.com/forum/#!forum/ansible-project
- https://groups.google.com/forum/#!forum/ansible-devel

We'd be happy to discuss things.

Thank you once again!

**Comment by agaffney** [comment]
Just FYI, the original password prompt can be restored on FreeBSD by changing the following line in `/etc/pam.d/sshd` from:

```
auth            required        pam_unix.so             no_warn try_first_pass
```

to:

```
auth            required        pam_unix.so             no_warn try_first_pass authtok_prompt=Password:
```

After this, `sshpass` once again works as expected.
