### ISSUE TITLE
Too few tags (none) from ec2.py inventory script for RDS instances

### ISSUE THREAD

**Issue by zentavr** [ansible/ansible#11569]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
contrib/inventory/ec2.py

##### ANSIBLE VERSION
N/A

##### SUMMARY
In fact it was cloned from [here](https://github.com/ansible/ansible-modules-extras/issues/668)

When using [ec2.py](https://github.com/ansible/ansible/blob/devel/contrib/inventory/ec2.py) inventory script, it returns no tags for RDS instances.
Saying, when it is a regular EC2 node, we have this:

```
"172.29.5.134": {
    "ec2__in_monitoring_element": false, 
    "ec2_ami_launch_index": "0", 
    "ec2_architecture": "x86_64", 
    "ec2_client_token": "", 
    "ec2_dns_name": "", 
    "ec2_ebs_optimized": false, 
    "ec2_eventsSet": "", 
    "ec2_group_name": "", 
    "ec2_hypervisor": "xen", 
    "ec2_id": "i-3ace31c4", 
    "ec2_image_id": "ami-d85e75b0", 
    "ec2_instance_profile": "", 
    "ec2_instance_type": "m3.medium", 
    "ec2_ip_address": "", 
    "ec2_item": "", 
    "ec2_kernel": "aki-919dcaf8", 
    "ec2_key_name": "devkey", 
    "ec2_launch_time": "2015-07-01T00:44:19.000Z", 
    "ec2_monitored": false, 
    "ec2_monitoring": "", 
    "ec2_monitoring_state": "disabled", 
    "ec2_persistent": false, 
    "ec2_placement": "us-east-1b", 
    "ec2_platform": "", 
    "ec2_previous_state": "", 
    "ec2_previous_state_code": 0, 
    "ec2_private_dns_name": "ip-172-29-5-134.ec2.internal", 
    "ec2_private_ip_address": "172.29.5.134", 
    "ec2_public_dns_name": "", 
    "ec2_ramdisk": "", 
    "ec2_reason": "", 
    "ec2_region": "us-east-1", 
    "ec2_requester_id": "", 
    "ec2_root_device_name": "/dev/sda1", 
    "ec2_root_device_type": "ebs", 
    "ec2_security_group_ids": "sg-dd42aeba", 
    "ec2_security_group_names": "public", 
    "ec2_sourceDestCheck": "true", 
    "ec2_spot_instance_request_id": "", 
    "ec2_state": "running", 
    "ec2_state_code": 16, 
    "ec2_state_reason": "", 
    "ec2_subnet_id": "subnet-09f38250", 
    "ec2_tag_Name": "arenaci", 
    "ec2_tag_deployment": "ansible", 
    "ec2_tag_environment": "arenaci2", 
    "ec2_tag_role": "all", 
    "ec2_virtualization_type": "paravirtual", 
    "ec2_vpc_id": "vpc-19e3ef7c"
  }
```

but RDS instance has only:

```
"usersdb-shard1-devshared.c2i4io1knn7g.us-east-1.rds.amazonaws.com": {
    "ec2_DBInstance": "", 
    "ec2_DBName": "devshared", 
    "ec2_OptionGroupMembership": "", 
    "ec2_OptionGroupMemberships": "", 
    "ec2_OptionGroupName": "default:mysql-5-6", 
    "ec2_PubliclyAccessible": "false", 
    "ec2_Status": "in-sync", 
    "ec2__address": "usersdb-shard1-devshared.c2i4io1knn7g.us-east-1.rds.amazonaws.com", 
    "ec2__in_endpoint": false, 
    "ec2__port": 3306, 
    "ec2_allocated_storage": 20, 
    "ec2_auto_minor_version_upgrade": true, 
    "ec2_availability_zone": "us-east-1d", 
    "ec2_backup_retention_period": 8, 
    "ec2_character_set_name": "", 
    "ec2_create_time": "2015-06-29T23:34:15.674Z", 
    "ec2_engine": "mysql", 
    "ec2_engine_version": "5.6.22", 
    "ec2_id": "usersdb-shard1-devshared", 
    "ec2_instance_class": "db.m1.small", 
    "ec2_iops": "", 
    "ec2_latest_restorable_time": "2015-07-01T01:00:01Z", 
    "ec2_license_model": "general-public-license", 
    "ec2_master_username": "idle", 
    "ec2_multi_az": false, 
    "ec2_preferred_backup_window": "03:00-03:30", 
    "ec2_preferred_maintenance_window": "wed:04:00-wed:04:30", 
    "ec2_status": "available", 
    "ec2_status_infos": ""
  }
```

I expect to have more `ec2_tag_****` keys for it.
Seems like boto.rds2 supports `list_tags_for_resource()` call to do this.

**Comment by bfin** [comment]
+1
It'd be nice to be able to use the same tag-based grouping logic that we can use for other EC2 instances.

**Comment by sanear** [comment]
Been awhile, I know, but +1 from me - would love to see this functionality so I can more easily treat RDS instances similarly to ordinary EC2 instances.

**Comment by deyvsh** [comment]
I had a quick look at implementing this but there are the following snags:
- ec2.py currently uses boto.rds not boto.rds2, and the migration is fiddly
- list_tags_for_resource() requires an ARN. Generating an ARN requires the account id. Getting the account id from AWS programmatically is not straightforward (it's all hacks). This problem also applies to boto3.

I might have time to implement something but I can't imagine it being clean enough to get into the core with what I know now. If anyone knows, or can think of, a workaround for the ARN issue that would help.

**Comment by aioue** [comment]
Related https://github.com/ansible/ansible/issues/14464

**Comment by aioue** [comment]
Here is a working example using boto3 https://github.com/ansible/ansible/pull/15609

**Comment by nethershaw** [comment]
#15609 does not solve this issue. It provides tags for RDS clusters, but not RDS instances.

Why would clusters have received this fix before instances? What obstacles remain to expose the resource tags of RDS instances via dynamic inventory?

**Comment by aioue** [comment]
@deyvsh to tag the RDS clusters, I pulled the user like so: https://github.com/ansible/ansible/pull/16606/files#diff-c2e371537339bbab5d9d0cc5d6cb7adcR607

and then built the ARN: https://github.com/ansible/ansible/pull/16606/files#diff-c2e371537339bbab5d9d0cc5d6cb7adcR625

I don't have time to tag 'traditional' RDS instances atm, but that PR should point you in the right direction.

**Comment by deyvsh** [comment]
Thanks @aioue. Not sure when I'll have time to give it a go, but I really appreciate the pointer.

**Comment by jctanner** [comment]
cc @willthames

**Comment by willthames** [comment]
@jctanner thanks for cc'ing me on this. 

My view is that this is easy to do in boto3 (because the result of `describe_db_instances` contains the ARN that is needed to use with `list_tags_for_resource` - while there are workarounds, I can't be bothered with them), and hard to do with `boto.rds` or `boto.rds2`. 

So, there are a few options:
* Do nothing, don't let people group rds instances by tag (unpopular with anyone who wants this feature)
* Implement the various workarounds to get the ARN just using boto, and then call `boto.rds2.list_tags_for_resource` to get the tags (a bit hacky)
* Create a dual boto/boto3 solution, where people without boto can still use `boto.rds` but can't use tags, and people with boto3 can get tags (most work, least popular with implementors)
* Convert the rds part of the inventory script to boto3 only, drop support for boto for rds (unpopular with anyone who can't use boto3 - I'm not sure if anyone is in this particular situation these days)

All new AWS modules are allowed to be boto3 only, but existing modules are not currently allowed to drop boto support. Applying the same conclusion to the inventory script would probably lead to the hacky solution.

**Comment by ElijahLynn** [comment]
I have created a PR to 'get tags for RDS instances' based on @willthames suggestion. It is boto3 only but figured I would at least get that part working and post publicly. 

https://github.com/ansible/ansible/pull/23989

**Comment by s-hertel** [comment]
resolved_by_pr #23989
