### ISSUE TITLE
Add punycode filter to jinja2

### ISSUE THREAD

**Issue by dwt** [ansible/ansible#11572]
Hi there,

I've just noticed that this filter seems to be missing, which can make it hard to deal with international domains where you need to ensure that the punycode and the normal form can be used.

This should be quite simple and should allow dealing with punycode much easier.

**Comment by bcoca** [comment]
we add filters on top of the provided by jinja2, we do not remove any, you might just need to upgrade your jinaj2 version.

**Comment by bcoca** [comment]
actually this is already supported, but not through a filter

```
- hosts: localhost
  vars:
    myuri: "www.Alliancefrançaise.nu"
  tasks:
    - debug: msg="{{myuri.encode('punycode')}}"
    - debug: msg="{{myuri.encode('punycode').decode('punycode')}}"
    - debug: msg="{{myuri.encode('idna')}}"
    - debug: msg="{{myuri.encode('idna').decode('idna')}}"
```

results:

```
TASK [debug msg=www.Alliancefranaise.nu-dbc] ************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "www.Alliancefranaise.nu-dbc"
}

TASK [debug msg=www.Alliancefrançaise.nu] ***************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "www.Alliancefrançaise.nu"
}

TASK [debug msg=www.xn--alliancefranaise-npb.nu] ********************************
ok: [localhost] => {
    "changed": false, 
    "msg": "www.xn--alliancefranaise-npb.nu"
}

TASK [debug msg=www.alliancefrançaise.nu] ***************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "www.alliancefrançaise.nu"
}

PLAY RECAP **********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0   
```

so closing this as the feature exists

**Comment by dwt** [comment]
Wow, thanks for the quick reply.  I would appreciate if this is mentioned in the docs (preferably with the filter documentation) as that was the natural place where I looked for this (and I imagine others will too).
