### ISSUE TITLE
Docker and Ansible Vault: how to use securely?

### ISSUE THREAD

**Issue by saada** [ansible/ansible#11578]
Ansible Vault requires to prompt the user for a password or a file containing the password. But if I'm running Ansible inside of a [container](https://registry.hub.docker.com/u/ansible/ubuntu14.04-ansible/), I cannot prompt the user for a password. 

How can I run a playbook using vars encrypted by Vault during a Docker build?
How can I do it without exposing a password file?
Is there a best practice?

**Comment by jimi-c** [comment]
Hi @saada, this is a question more appropriately directed at the mailing list:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks

Generally, we try to limit Github issues to bug reports and code submissions rather than general help and/or tips. Thanks!

**Comment by jimi-c** [comment]
Alternatively, we also have two IRC channels on Freenode (#ansible and #ansible-devel), if you'd like more live help. The #ansible channel typically has well over 1000 people in it, and most questions are answered very quickly there.
