### ISSUE TITLE
powershell.ps1 is not equal across v2 and v1

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#11580]
Ping @jhawkesworth shouldn't these two files have the same contents?

**Comment by jhawkesworth** [comment]
Yes, I agree they should be the same, v1 is I think correct
Get-FileChecksum is preferred as it uses SHA1 for checksum instead of MD5.  This reflects changes made in the python code base a few months ago to use SHA1 instead of MD5 for checksums (I believe this allows FIPS 140 compliance).

**Comment by bcoca** [comment]
fixed via 8793308c39bf064106f08b74e5cb468c94bf1d83
