### ISSUE TITLE
Do not fail when a skip_tag matches nothing

### ISSUE THREAD

**Issue by warrenseine** [ansible/ansible#11597]
Hi,

It often happens, in my case, that Ansible throws telling me that a "tag" I'm willing to skip doesn't exist. Through I totally understand that it's made in order to prevent typos in the tags, it's quite frustrating.

Since I'm skipping it, could we just ignore the invalid tag?

Usually, it's only invalid because I commented out some roles in order to speed up the provisioning during development.

Regards,
Warren.

**Comment by bcoca** [comment]
dupe of #10510
