### ISSUE TITLE
control_path value not read from local ansible.cfg

### ISSUE THREAD

**Issue by peterlacko** [ansible/ansible#11596]
Hello,
I'm using ansible for managing ec2 instances. After updating system (to Fedora 22) and also ansible (to 1.9.2) I got an error about too long name for Unix domain socket. So I changed control path in local ansible.cfg to `control_path=%(directory)s/%%h-%%r` which should solve the problem, but value of control_path is ignored and default value `%(directory)s/ansible-ssh-%%h-%%p-%%r` is used instead. Other values like private_key_file, roles_path etc. specified in config file are used. I dug into it a little and found out workaround: setting env variable ANSIBLE_SSH_CONTROL_PATH to `'%(directory)s/%%h-%%r'` which actually changes control path.

**Comment by bcoca** [comment]
did you set control_path in the ssh_connection section?

**Comment by peterlacko** [comment]
That's it, thanks and closing issue :+1:
