### ISSUE TITLE
sudo with NFS root_squash

### ISSUE THREAD

**Issue by craigyk** [ansible/ansible#11602]
I'm having a problem that I think might be related to trying to use unusable with sudo from an account whose home directory is on an NFS share exported with root_squash.

failed: [eppec-node3] => {"failed": true, "parsed": false}
BECOME-SUCCESS-yftrjxrfpulmcrwqshadicpydekbegaq
/usr/bin/python: can't open file '/home/users/yoshiokc/.ansible/tmp/ansible-tmp-1436997442.28-30952344109479/setup': [Errno 13] Permission denied

Any thoughts?

Thanks,
-Craig

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by bcoca** [comment]
In any case, the easy solution is changing which directory ansible uses as remote temp, through ANSIBLE_REMOTE_TEMP env variable or remote_tmp in ansible.cfg
