### ISSUE TITLE
Boolean True "value cannot be parsed to boolean"

### ISSUE THREAD

**Issue by trompx** [ansible/ansible#11600]
Hello,

I use a jinja template to create an environment variable config file and ansible converts all variable set to "true" or "yes" in group_vars to "True" with uppercase resulting in "value cannot be parsed to boolean [ true/1/on/yes OR false/0/off/no ]" error when trying to launch an elasticsearch docker container. 

To debug, I tried directly in the command line. This fails miserably : 

```
-e ES_MASTER=True
```

while

```
-e ES_MASTER=true
```

works totally fine.

Is there a way to correct this in ansible so it does not add that uppercase "T" which I don't know why it is adding in the first place^^

Thanks

**Comment by bcoca** [comment]
have you tried -e ES_MASTER='True'

**Comment by trompx** [comment]
Hello @bcoca, thanks for your input. But unfortunatly, -e ES_MASTER='True' fails too.

One solution is to use "lower".

```
ES_MASTER: "{{ es_master | lower }}"
ES_DATA: "{{ es_data | lower }}"
```

But it is more a hack. I think ansible should not automatically convert on/yes/true to True.

**Comment by bcoca** [comment]
No need for lower |string should also work.

this conversion happens on purpose because otherwise all booleans passed to ansible would be strings instead and 'false' would end up being True (non empty string).

I'm going to close this ticket as this is expected functionality.
