### ISSUE TITLE
Add an apt upgrade='apt-upgrade' option that runs `apt-get upgrade`, not aptitude.

### ISSUE THREAD

**Issue by dotsdl** [ansible/ansible#11601]
##### Issue Type:

“Feature Idea”
##### Ansible Version:

ansible 1.9.2
##### Ansible Configuration:

N/A
##### Environment:

Ubuntu 14.04
##### Summary:

Add an apt upgrade='apt-upgrade' option that runs `apt-get upgrade`, not aptitude.
##### Steps To Reproduce:

I would like to be able to run a task like:

```
- name: apt-upgrade
  apt: update_cache=yes upgrade=apt-upgrade
```

that is equivalent to running in the shell:

```
apt-get upgrade
```

At present, there is no option that includes this functionality the current ones are:
- yes or safe: `aptitude safe-upgrade`
- full: `aptitude full-upgrade`
- dist: `apt-get dist-upgrade`

The reason this is desirable is because all of the above options will upgrade the kernel if a new one is available, whereas `apt-get upgrade` holds these back by default. In many cases one might want to upgrade the package using the more conservative `apt-get upgrade`, so it would be great if it's exposed as an upgrade option.

**Comment by abadger** [comment]
Hi, The apt module code lives in a different repository.  Before this gets along thread of comments would you be willing to move this over to https://github.com/ansible/ansible-modules-core ?  Thanks!

**Comment by dotsdl** [comment]
No problem. Apologies for sticking this in the wrong place!

**Comment by dotsdl** [comment]
This issue is now here: https://github.com/ansible/ansible-modules-core/issues/1741

**Comment by agamdua** [comment]
Would love to reopen this since https://github.com/ansible/ansible-modules-core/issues/1741 has been closed after the "repomerge"

**Comment by jctanner** [comment]
@agamdua the issue was moved to https://github.com/ansible/ansible/issues/22673
