### ISSUE TITLE
Directive "become" (sudo) not working unless using ANSIBLE_KEEP_REMOTE_FILES=1, CentOS 6.6

### ISSUE THREAD

**Issue by tiangolo** [ansible/ansible#11611]
**Issue Type:**

Bug Report

**Ansible Version:**

```
ansible 2.0.0 (devel ba7243c5f9) last updated 2015/07/16 14:23:48 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 291fef3b34) last updated 2015/07/16 14:44:41 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD ff2386faf4) last updated 2015/07/16 14:45:26 (GMT +000)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/07/16 14:46:09 (GMT +000)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/07/16 14:47:03 (GMT +000)
  configured module search path = None
```

**Ansible Configuration:**

I changed transport for paramiko, if I do:

```
diff ~/ansible/examples/ansible.cfg ~/.ansible.cfg
```

I get:

```
23c23
< transport      = smart

---
> transport      = paramiko
```

**Environment:**

_Control Machine_: 

Ubuntu 14.04, made with:

```
vagrant init chef/ubuntu-14.04
vagrant up
```

_Managed Node_:

CentOS 6.6, made with:

```
vagrant init chef/centos-6.6
vagrant up
```

Note: both machines have set up private networks, omitted for brevity.

**Summary:**

Connecting as root, `become` is not working, I get `ERROR! ssh connection closed waiting for password prompt`. 

But it works if I set the variable `ANSIBLE_KEEP_REMOTE_FILES=1`.

**Note:** my intention is to connect as root, become user postgres and create a user and DB. To use the modules `postgresql_db`, etc, I need to be the postgres user, but that user (by default) doesn't have a password, so I need to connect as root and become postgres. The problem also applies for other users, so I made the issue as general as possible (becoming user vagrant).

**Steps To Reproduce:**

Playbook file, main.yml:

```

---
- name: test become
  remote_user: root
  hosts: main_node

  tasks:
    - name: Test become
      become_user: vagrant
      become: True
      command: whoami
      register: the_user

    - name: Debug become
      debug:
        msg: "{{ the_user }}"
```

To get the error:

```
ansible-playbook main.yml --ask-pass -i ansible_hosts
```

To make it work:

```
ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook main.yml --ask-pass -i ansible_hosts
```

**Expected Results:**

Running:

```
ansible-playbook main.yml --ask-pass -i ansible_hosts
```

should work and do not give errors, and return the same results as giving the variable `ANSIBLE_KEEP_REMOTE_FILES=1`.

As I understand, the variable `ANSIBLE_KEEP_REMOTE_FILES=1` should be used for debug only and shouldn't be needed to make `become` work.

The outputs of those commands are below, I omit them here for brevity.

**Actual Results:**

When I run:

```
ansible-playbook main.yml --ask-pass -i ansible_hosts
```

I get:

```
PLAY: test become ***************************************************************

TASK [setup] ********************************************************************
ok: [192.168.27.90]

TASK [Test become] **************************************************************
fatal: [192.168.27.90]: FAILED! => {
    "failed": true,
    "msg": "ERROR! ssh connection closed waiting for password prompt"
}

PLAY RECAP **********************************************************************
192.168.27.90              : ok=1    changed=0    unreachable=0    failed=1
```

But when I run:

```
ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook main.yml --ask-pass -i ansible_hosts
```

I get:

```
PLAY: test become ***************************************************************

TASK [setup] ********************************************************************
ok: [192.168.27.90]

TASK [Test become] **************************************************************
changed: [192.168.27.90]

TASK [Debug become] *************************************************************
ok: [192.168.27.90] => {
    "changed": false,
    "msg": {
        "changed": true,
        "cmd": [
            "whoami"
        ],
        "delta": "0:00:00.002802",
        "end": "2015-07-16 15:36:10.563435",
        "invocation": {
            "module_args": {
                "_raw_params": "whoami"
            },
            "module_name": "command"
        },
        "rc": 0,
        "start": "2015-07-16 15:36:10.560633",
        "stderr": "",
        "stdout": "vagrant",
        "stdout_lines": [
            "vagrant"
        ]
    }
}

PLAY RECAP **********************************************************************
192.168.27.90              : ok=3    changed=1    unreachable=0    failed=0
```

**Comment by jimi-c** [comment]
@tiangolo could you please show the output of the command when run with `-vvv` but without keeping the remote files? I'm wanting to see exactly the step on which it's failing.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by tiangolo** [comment]
Awesome! That was fast. 
I confirm that this commit fixes the bug. Thanks!
