### ISSUE TITLE
SSLValidation not working

### ISSUE THREAD

**Issue by Phyks** [ansible/ansible#11617]
Hi,

There seem to be a problem in the SSL validation, leading to invalid results. For instance, when using `get_url` module like this:

```
get_url: url=https://download.owncloud.org/community/owncloud-latest.zip dest=/tmp/owncloud-latest.zip
```

The task fails due to an invalid certificate:

```
TASK: [webservices | Download Owncloud] *************************************** 
failed: [host] => {"failed": true}
msg: SSL Certificate does not belong to download.owncloud.org.  Make sure the url has a certificate that belongs to it or use validate_certs=False (insecure)

FATAL: all hosts have already failed -- aborting
```

However, downloading the same URL using `wget` on the remote host does not trigger any SSL warning:

```
% wget https://download.owncloud.org/community/owncloud-latest.zip
converted 'https://download.owncloud.org/community/owncloud-latest.zip' (ANSI_X3.4-1968) -> 'https://download.owncloud.org/community/owncloud-latest.zip' (UTF-8)
--2015-07-17 00:27:15--  https://download.owncloud.org/community/owncloud-latest.zip
Resolving download.owncloud.org (download.owncloud.org)... 209.126.100.233, 144.76.105.220
Connecting to download.owncloud.org (download.owncloud.org)|209.126.100.233|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 36004533 (34M) [application/zip]
Saving to: 'owncloud-latest.zip'

owncloud-latest.zip        2%[                                   ] 872.00K   426KB/s 
```

Thanks

**Comment by abadger** [comment]
This is mostly the same as this: https://github.com/ansible/ansible/issues/11579#issuecomment-121775819

In other words, SNI is unimplemented in the python stdlib urllib2 module until python 2.7.9 and therefore attempting to connect to https://download.owncloud.org/ with python less than 2.7.9 will get the wrong certificate.  There are some workarounds listed in that ticket that can deal with SNI if you can't use python >=2.7.9.  If you can use python >= 2.7.9 you also need the fix to ansible code mentioned in that comment to make things work.  that fix should be in our next release as well.

**Comment by Phyks** [comment]
Ok, I'll move on using wget / curl I think to handle this. Indeed, it is mostly the same issue.

Problem is debian stable is stuck with Python 2.7.3, and for the vast majority of users, the only solution would be to move to Python 3 to be safe, I think. But this is some long time work.

Thanks for the answer!
