### ISSUE TITLE
add option to apt to allow unauthenticated packages

### ISSUE THREAD

**Issue by FlorinAndrei** [ansible/ansible#11620]
If I try to install a deb package which was not signed / authenticated, the apt module fails. Additionally, there is no way to pass --allow-unauthenticated to apt-get with this module.

I have a few home-grown packages which are stored in secure locations. There's no need to sign them. I need to pass the --allow-unauthenticated to apt-get for these packages.

Thanks.

**Comment by FlorinAndrei** [comment]
There is a workaround, but it's super-ugly: every time I install one of those packages, I have to do this first:

```
- name: super-ugly hack to allow unauthenticated packages to install
  copy: content='APT::Get::AllowUnauthenticated "true";' dest=/etc/apt/apt.conf.d/99temp owner=root group=root mode=0644
```

And after the package is installed, I need to remove the hack:

```
- name: remove hack that allows unauthenticated packages to install
  file: path=/etc/apt/apt.conf.d/99temp state=absent
```

It's not something I'm happy to keep in my playbooks for too long. :(

**Comment by rey** [comment]
+1

**Comment by rajpan** [comment]
+1

**Comment by fpoli** [comment]
+1

**Comment by resmo** [comment]
feature has been implemented https://github.com/ansible/ansible-modules-core/pull/2023
