### ISSUE TITLE
parameterized playbook includes?

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1162]
include: playbook.yml a=2 b=3 c=4

we can do it with tasks, why not?

see also: handlers

make sure with_items also works with these includes as it now works with task includes

**Comment by abondis** [comment]
I'm trying to get this to work and having an issue with variables replacement
for include: playbook.yml a=2
$a in the playbook gets replaced, but not ${a} in ${something.${a}.sthgelse}.
I tried with varReplace_, template_ but still the same issue.

**Comment by nicolaasuni** [comment]
I am also interested in this feature to avoid code duplication.
abondis: is your code shared somewhere?

**Comment by nicolaasuni** [comment]
Additionally, it will be even better if we can use with_items with playbooks include:

include: playbook.yml myvar=$item
with_item:
    - a
    - b
    - c

**Comment by mpdehaan** [comment]
We can do that with tasks, so yes, this should also be possible when we do
this.

**Comment by nicolaasuni** [comment]
Any news about this feature? I think that this one is very important because allows to avoid code duplication.
Is there someone working on it who can share the code so I can help?

**Comment by mpdehaan** [comment]
This is one of about 3 features this release that I have relatively
specific architecture needs on, and while I can generally accept patches on
almost anything new or self-contained, when things get big, I need to
familiarize myself with them
as they get built in.

If the patch is small and self contained, perhaps.

However, it's probably better if you can wait.

I do anticipate there are enough "must haves" in 0.9 that it will probably
be another 1.5 month release cycle versus our usual 1 month.   I'm trying
to manage scope as much as possible but this is definitely one of those
things
we want.

**Comment by mpdehaan** [comment]
will be handled by above PR when I have a chance to test it, so closing this ticket.

**Comment by progre55** [comment]
the following case is not working:
- name: Register lines
  local_action: command /usr/bin/env ls -1 /some/dir/files/
  register: myfiles
- include: ./tasks/mytask.yml myfile=${item}
  with_items: ${myfiles.stdout_lines}

it passes in the literal "${myfiles.stdout_lines}" char by char, like item=$ item={ item=m item=y, etc

but the following works:

vars:
  myfiles:
    - file1
    - file2
- include: ./tasks/mytask.yml myfile=${item}
  with_items: $myfiles
