### ISSUE TITLE
cron module has no way to disable jobs temporarily by commenting them out

### ISSUE THREAD

**Issue by FlorinAndrei** [ansible/ansible#11636]
It would make life that much easier if I could do something like state=disabled in the cron module, to the effect that the cron job would not be removed, but instead just commented out. This would help a lot when testing many versions of the same job, etc. Thanks.

**Comment by bcoca** [comment]
First, this is the wrong repo to ask for features for the cron module, you want https://github.com/ansible/ansible-modules-core

second, there is already a PR for this https://github.com/ansible/ansible-modules-core/pull/878
