### ISSUE TITLE
Connection closed waiting for privilege escalation password prompt

### ISSUE THREAD

**Issue by rmullinnix** [ansible/ansible#11633]
Pulled recent devel from git - experienced issue and isolated to commit point
Have tried with sudo and --ask-sudo-pass as well as with become and --ask-become-pass.  Preceding tasks of file: for creating directory work.

SLES 11 SP3

task copy works at commit point - dc63bbf0b9686db297de8d0bb801cba0418f88f2 (June 17, 2015)
does not work at commit point - 194b85338f0cae2d986f371508b37a2961d98dfb (June 17, 2015)
ERROR! Connection closed waiting for privilege escalation password prompt:
- name: Create consul-template config
  copy: src="01-consul-template.conf" dest="{{ consul_template_config_dir }}/01-consul-template.conf"

Verbose output is equivalent between the two up to this point
<msp0lnand001.etdbw.com> ESTABLISH SSH CONNECTION FOR USER: tg8855
<msp0lnand001.etdbw.com> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 msp0lnand001.etdbw.com /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=kwinvgdxmqggrhhvnvpjkhgnwocpufrw] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-kwinvgdxmqggrhhvnvpjkhgnwocpufrw; rc=flag; [ -r /etc/consul-template/conf.d/01-consul-template.conf ] || rc=2; [ -f /etc/consul-template/conf.d/01-consul-template.conf ] || rc=1; [ -d /etc/consul-template/conf.d/01-consul-template.conf ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/etc/consul-template/conf.d/01-consul-template.conf && exit 0; (python -c '"'"'"'"'"'"'"'"'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1();
afile = open("'"'"'"'"'"'"'"'"'/etc/consul-template/conf.d/01-consul-template.conf'"'"'"'"'"'"'"'"'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
        hasher.update(buf)
        buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())'"'"'"'"'"'"'"'"' 2>/dev/null) || (python -c '"'"'"'"'"'"'"'"'import sha; BLOCKSIZE = 65536; hasher = sha.sha();
afile = open("'"'"'"'"'"'"'"'"'/etc/consul-template/conf.d/01-consul-template.conf'"'"'"'"'"'"'"'"'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
        hasher.update(buf)
        buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())'"'"'"'"'"'"'"'"' 2>/dev/null) || (echo '"'"'"'"'"'"'"'"'0  '"'"'"'"'"'"'"'"'/etc/consul-template/conf.d/01-consul-template.conf)'"'"''
<msp0lnand001.etdbw.com> ESTABLISH SSH CONNECTION FOR USER: tg8855
<msp0lnand001.etdbw.com> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 msp0lnand001.etdbw.com mkdir -p $HOME/.ansible/tmp/ansible-tmp-1437167920.48-182501296239349 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1437167920.48-182501296239349 && echo $HOME/.ansible/tmp/ansible-tmp-1437167920.48-182501296239349

 the one that succeeds has the additional output where the other one stops:

<msp0lnand001.etdbw.com> ESTABLISH SSH CONNECTION FOR USER: tg8855
<msp0lnand001.etdbw.com> PUT /tmp/tmphhgjpz TO /home/tg8855/.ansible/tmp/ansible-tmp-1437167920.48-182501296239349/file
<msp0lnand001.etdbw.com> ESTABLISH SSH CONNECTION FOR USER: tg8855
<msp0lnand001.etdbw.com> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 msp0lnand001.etdbw.com /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=gptcrbwurujzncotdqfurvildirzxbqv] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-gptcrbwurujzncotdqfurvildirzxbqv; LANG=C LC_MESSAGES=C LC_CTYPE=C /usr/bin/python /home/tg8855/.ansible/tmp/ansible-tmp-1437167920.48-182501296239349/file; rm -rf /home/tg8855/.ansible/tmp/ansible-tmp-1437167920.48-182501296239349/ >/dev/null 2>&1'"'"''

**Comment by rmullinnix** [comment]
I believe self.prompt is not initialized in lib/ansible/plugins/connections/ssh.py if sudoable is not true, resulting in a a true branch at the point of -- if self.prompt: , which it should not take.

Fix - line 347 in lib/ansible/plugins/connections/ssh.py - self.prompt = None

I'm not a python programmer, so don't feel comfortable doing a PR

**Comment by bcoca** [comment]
folding into #11611

**Comment by bcoca** [comment]
FYI, self.prompt is initialized in  `lib/ansible/plugins/connections/__init__.py#L61`, which is the base class `__init__` method which the ssh plugin calls via:

```
super(Connection, self).__init__(*args, **kwargs)
```
