### ISSUE TITLE
ansible-vault should prompt for a password when it needs to, as in v1.9

### ISSUE THREAD

**Issue by amenonsen** [ansible/ansible#11651]
Issue type:

Bug report

Ansible version:

devel@a8ba9cac3

Ansible configuration:

NA

Environment:

NA

Summary:

In ansible 1.9, running ansible-vault interactively prompts for the password. With devel, it breaks unless you explicitly specify --ask-vault-pass, which is pretty tedious.

(Note this is about running ansible-vault directly, not specifying --ask-vault-pass to ansible-playbook.)

I was going to work up a PR to fix this, but I thought I'd note it here for the record. (But if someone else wants to fix it, please feel free. It should be a simple fix.)

Steps to reproduce:

ansible-vault view encrypted-file

Expected results:

Prompt for vault password (as Ansible 1.9 does).

Actual results:

ERROR! A password is required to use Ansible's Vault

**Comment by bcoca** [comment]
forgot to submit this fix, had it for a while, f66ba9274530c9057db4857c0f2860b146e4c316
