### ISSUE TITLE
Galaxy Suggestion: Add Number of Reviews

### ISSUE THREAD

**Issue by IanVS** [ansible/ansible#11652]
##### Issue Type:

“Feature Idea”
##### Summary:

The ratings are somewhat useful, but a vital component to them are missing, and that's number of reviews.  Seeing a 5.0 and a 4.6 on the search page doesn't mean much if there is only one review for the former and 10 for the latter.
##### Expected Results:

It would be great to have something like Amazon, showing the number of reviews as well as average.  Often, I'm looking for the most-often used package anyway, and this would be a big help in finding them.

**Comment by bcoca** [comment]
cc @gregdek

**Comment by gregdek** [comment]
Thanks for the suggestion, @IanVS -- it's being tracked internally for potential addition as an upcoming feature.

**Comment by IanVS** [comment]
Great, thanks!
