### ISSUE TITLE
On the 2.x / devel, parameters are not propagated to windows module commands on the remote windows host(s)

### ISSUE THREAD

**Issue by brianlloyd** [ansible/ansible#11661]
##### Issue Type:

Bug Report.
##### Ansible Version:

ansible 2.0.0 (devel 6bff315ed8) last updated 2015/07/20 11:54:35 (GMT -400)
##### Ansible Configuration:

No changes - stock ansible configuration.
##### Environment:

Results of uname -a: Darwin Brian-Lloyds-MacBook-Pro.local 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64
##### Summary:

On the 2.x / devel github source, parameters are not propagated to windows module commands on the remote windows host.
##### Steps To Reproduce:

Given the following playbook:

---
- hosts: windows
  
  tasks:
      - name: test copy
        win_copy: src=../ansible-testing/test.txt dest=c:\test\test.txt

The result is an error:

<52.11.9.216> EXEC PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -File "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1437429216.04-162277422500825\win_copy.ps1"
<52.11.9.216> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-EncodedCommand', 'UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABVAG4AcgBlAHMAdAByAGkAYwB0AGUAZAAgAC0ARgBpAGwAZQAgACIAQwA6AFwAVQBzAGUAcgBzAFwAQQBkAG0AaQBuAGkAcwB0AHIAYQB0AG8AcgBcAEEAcABwAEQAYQB0AGEAXABMAG8AYwBhAGwAXABUAGUAbQBwAFwAYQBuAHMAaQBiAGwAZQAtAHQAbQBwAC0AMQA0ADMANwA0ADIAOQAyADEANgAuADAANAAtADEANgAyADIANwA3ADQAMgAyADUAMAAwADgAMgA1AFwAXAB3AGkAbgBfAGMAbwBwAHkALgBwAHMAMQAiAA==']
<52.11.9.216> WINRM RESULT <Response code 1, out "{"msg":"missing requ", err "">
fatal: [52.11.9.216]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "missing required argument: src"
}

PLAY RECAP **********************************************************************
52.11.9.216                : ok=1    changed=0    unreachable=0    failed=1   

This appears to be because in 2.x/devel the "arguments" file is not being copied to the remote host, and the path the arguments file is not being added as an argument to the remote command so that the Parse-Args function can handle it.
##### Expected Results:

Ansible should PUT the arguments file to the remote Windows host and pass the path to that temp file as an argument to any module that takes params.
##### Actual Results:

As noted above, no parameters file is created for any windows module (tested a few - win_copy is a simple example), thus all windows modules that require params fail when checking for the existence of their first parameter.

I have worked around this for now by sourcing the v1 version of hacking/env_setup. Doing this results in the appropriate parameters file being created on the remote host and its path being appropriately passed in the encoded powershell command sent to the remote host.

**Comment by cchurch** [comment]
I'm aware, got a fix in the works.
