### ISSUE TITLE
ssh debug information in stderr output

### ISSUE THREAD

**Issue by ghTravis** [ansible/ansible#11682]
Hi,

I'm experiencing in ansible 1.9.2 an issue where debug information is sent to stderr when using the default (smart) CONNECTION setting. Currently running a simple noop module that echo's "noop". We have a wrapper shell script around this call that is set to use /bin/sh -xe which specifies that the script will immediately exit on a non 0 return code. It seems that this stderr output is causing our script to fail, even though ansible has determined that "rc" is 0 and the command was successful.

`X.X.X.X | success >> {
    "changed": true,
    "rc": 0,
    "stderr": "OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011\ndebug1: Reading configuration data /etc/ssh_config\r\ndebug1: /etc/ssh_config line 20: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: mux_client_request_session: master session id: 2\r\nShared connection to X.X.X.X closed.\r\n",
    "stdout": "+ echo noop\r\nnoop\r\n"
}`

Doing some more troubleshooting, we've found that if we specify `-c paramiko` it doesn't output the debug information, additionally downgrading to ansible 1.8.4 via pip also removes this issue.

**Comment by bcoca** [comment]
This output should only appear when you are using -vvvv, which is then an expected result, even when everything is OK.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by ghTravis** [comment]
Hi,

Sorry, I wasn't clear on the command we run. We do not specify the -vvvv option and we receive the aforementioned stderr output.

Here's the shell script for proof:

```
#!/bin/sh
inv=$1
shift
script=$1
shift
ansible all -i "$inv" -m script -a "$script" -u root
```

**Comment by zais** [comment]
@ghTravis, did you fixed issue with debug info in stderr?
