### ISSUE TITLE
Include of handlers does nothing, even silence if file does not exists

### ISSUE THREAD

**Issue by Hubbitus** [ansible/ansible#11694]
##### Issue Type:

Bug Report
##### Ansible Version:

$ ansible --version
ansible 2.0.0

Master 7124504
##### Ansible Configuration:

Hope irrelevant
##### Environment:

Fedora 22
##### Summary:

In version 1.9.2 it lead to error:

```
ERROR: file could not read: /home/pasha/Projects/Ansible.cfg/test-dev/some/non/existent/path
```

In 2.0 if included path does not esistt ansible do not thrown any error nor on include (parsing) stage nor on fire handlers by non-existence name.
##### Steps To Reproduce:

TestHandlerInclude.yml playbook:

```
- hosts: local
  handlers:
    - include: some/non/existent/path
    - name: test handler
      debug: msg="Test handler fired"
  tasks:
# Uncomment give error: ERROR! the file_name '/home/pasha/Projects/Ansible.cfg/test-dev/roles/sdth' does not exist, or is not readable
#    - include: roles/sdth

    - name: Test shell task which always should fire change
      local_action: shell date
      notify:
        - test handler
```
##### Expected Results:

1) Fail with error if included path can't be included
2) Fail with error if requested handler can't be notified (better provide possibility make it optional as by https://github.com/ansible/ansible/issues/10839)
##### Actual Results:

This playbook fail on ansible 1.9.2 with error:

```
ERROR: file could not read: /home/pasha/Projects/Ansible.cfg/test-dev/some/non/existent/path
```

But seams just fully ignore include in ansible 2.0:

```
/usr/bin/ansible-playbook -v /home/pasha/Projects/Ansible.cfg/test-dev/TestHandlerInclude.yml
Using /home/pasha/Projects/Ansible.cfg/ansible.cfg as config file

PLAY ****************************************************************************

TASK [setup] ********************************************************************
ok: [server1.local]

TASK [Test shell task which always should fire change] **************************
changed: [server1.local] => {"changed": true, "cmd": "date", "delta": "0:00:00.002779", "end": "2015-07-22 13:46:37.847877", "rc": 0, "start": "2015-07-22 13:46:37.845098", "stderr": "", "stdout": "Wed Jul 22 13:46:37 MSK 2015", "stdout_lines": ["Wed Jul 22 13:46:37 MSK 2015"], "warnings": []}

RUNNING HANDLER [test handler] **************************************************
ok: [server1.local] => {
    "changed": false, 
    "msg": "Test handler fired"
}

PLAY RECAP **********************************************************************
server1.local              : ok=3    changed=1    unreachable=0    failed=0
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by Hubbitus** [comment]
I discover same functionality in master 7d8afad28c46ec04e6a32d5aff65bde2d5ab54c5:

```
PLAY ****************************************************************************

TASK [setup] ********************************************************************
ok: [server1.local]

TASK [Test shell task which always should fire change] **************************
changed: [server1.local]

RUNNING HANDLER [test handler] **************************************************
ok: [server1.local] => {
    "changed": false, 
    "msg": "Test handler fired"
}

PLAY RECAP **********************************************************************
server1.local              : ok=3    changed=1    unreachable=0    failed=0
```

Sorry, I have no time follow one more devel mail list.
