### ISSUE TITLE
allow --sudo to take a username to sudo to

### ISSUE THREAD

**Issue by mgwilliams** [ansible/ansible#117]

**Comment by mpdehaan** [comment]
playbooks should also take 

sudo: username

in addition to:

sudo: True

**Comment by weaselkeeper** [comment]
Looking at the devel codebase, this is already done?

**Comment by mpdehaan** [comment]
not done, sudo w/ password works, but you can only sudo to root.

**Comment by mpdehaan** [comment]
seems to be no demand for this one, can be done with authorized_keys and logging in as whoever, will accept PR though

**Comment by wm-pseudo** [comment]
I can assure that this feature is badly needed in our case. We have centralized accounts and home directories for logging in, but our software must be run as a local non-root user. Please consider re-opening the issue and raising the priority.

**Comment by mpdehaan** [comment]
Patches are accepted.

On Wed, May 2, 2012 at 9:35 AM, wm-pseudo
reply@reply.github.com
wrote:
