### ISSUE TITLE
Allow flat role structure (x.yml instead of x/main.yml)

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#11700]
When writing simple roles without complex includes and conditionals, it would be nice to be able to reduce subdir clutter. Tasks, handlers, vars and meta could also be single files instead of subdirs, like so:

```
role/
  tasks.yml
  handlers.yml
  vars.yml
  meta.yml
```

**Comment by bcoca** [comment]
closing as dupe of #4359

**Comment by Vladimir-csp** [comment]
Oops, sorry.
My +1 to #4359 then.
