### ISSUE TITLE
Get MemoryError when fetching large file

### ISSUE THREAD

**Issue by vincentsmh** [ansible/ansible#11702]
I always get the following error message when trying to fetch a about 2GB file.

fatal: [x.x.x.x] => failed to parse: 
SUDO-SUCCESS-cfbftfjqyemugnxnudmbnfkjbidswsqm
Traceback (most recent call last):
  File "/home/xxx/.ansible/tmp/ansible-tmp-1437624645.89-38788504027242/slurp", line 1167, in <module>
    main()
  File "/home/xxx/.ansible/tmp/ansible-tmp-1437624645.89-38788504027242/slurp", line 67, in main
    data = base64.b64encode(file(source).read())
  File "/usr/lib/python2.7/base64.py", line 53, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
MemoryError

**Comment by gagomes** [comment]
@vincentsmh 

The most recent version I found containing the code that led to this issue is 1.7.2. Please upgrade to a more recent version and update this ticket if the issue still persists

**Comment by vincentsmh** [comment]
Do you have the same experience on 'copy' module? (local to remote copy)

**Comment by gagomes** [comment]
@vincentsmh 

I did not attempt to reproduce it. From the stack trace you posted above, it was obvious that that piece of code was attempting to read the whole file into memory at once, thus failing when it hit insufficient amounts of memory. 

I have reviewed the current source code which is currently at version 1.9.2-1. The piece of code responsible for this failure was last present in version 1.7.2. 

It would be highly recommended that you upgrade to a newer version, preferably something closer to 1.9.2-1 than to 1.7.3 (the first version without that code).

**Comment by bcoca** [comment]
closing as this is fixed in both current stable and development

**Comment by fernando-villalba** [comment]
This is back on version 2.1, when using the copy module and a large file, it hogs all memory and crashes.

**Comment by boedah** [comment]
I also got this on 1.9.4.
But not for all large files. Sometimes it works for ~1GB, sometimes it fails for 350MB...

**Comment by rammie** [comment]
Experiencing the same issue in 2.1

**Comment by gagomes** [comment]
@fernando-villalba  @boedah  @rammie 

Could you please post a sample playbook to help reproduce the issue and/or provide more details of your problem? 

Things that may help speedup fixing this issue:
- Stack Traces
- The file size in bytes of the file that lead to this issue
- A sample playbook

**Comment by sivel** [comment]
Please note that when using `fetch` on a large file this can happen, and there are notes documenting this on the docs page for `fetch` along with information on how best to get around it (http://docs.ansible.com/ansible/fetch_module.html)

> When running fetch with become, the slurp module will also be used to fetch the contents of the file for determining the remote checksum. This effectively doubles the transfer size, and depending on the file size can consume all available memory on the remote or local hosts causing a MemoryError. Due to this it is advisable to run this module without become whenever possible

**Comment by boedah** [comment]
@sivel : good catch.
So it is basically a RTFM? ;)

Even if I cannot quite understand why slurp is needed if `become` is used.
Also it states:

> This effectively doubles the transfer size, …

So this would mean the error also will show up without `become` but for larger files?

I just checked the source, and it seems the checksum is calculated regardless of the `validate_checksum` option (which is only used to throw an error in mismatch).
Does the checksum calculation itself consume that much memory?

Here are some more infos:

_Task_

Standard but with `become`

```
  fetch:
    fail_on_missing: yes
    flat: yes
    src: "/some/archive.tar"
    dest: "/local/archive.tar"
    mode: "0600"
    owner: root
    group: some_group
```

_Stacktrace_

```
TASK: [Fetch File] ****************************
fatal: [127.0.0.1 -> li10] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 789, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 1036, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/action_plugins/fetch.py", line 85, in run
    remote_data = base64.b64decode(slurpres.result['content'])
  File "/usr/lib/python2.7/base64.py", line 73, in b64decode
    return binascii.a2b_base64(s)
MemoryError
```

_File Size_

Think the file size does not matter here (as it depends on the available host memory).

**Comment by sivel** [comment]
@boedah, when using `become`, we assume that we cannot directly get the checksum of the file, due to the possibility of not having permissions to view the file.  This is because `become` does not necessarily mean using elevated permissions, it could be used for becoming another non-privlieged user.

As such, we `slurp` the file, which first reads the whole file into memory on the remote host, then base64 encodes it.  This in itself, will cause the process to consume 2x times the file size in memory.  At which point if successful, the full base64 contents are transferred back across the SSH connection to perform the checksum locally.  If the checksum does not match, then the contents of the file are retrieved again, this time not base64 encoded.

Due to this behavior, if a machine has 1GB of RAM, and you are fetching a 600MB file with `become: true`, it will read that 600MB file into memory, then base64 encode it, which consumes at this point over 1.2GB of RAM, causing a MemoryError.  In fact, just the process of reading the 600MB file into memory could cause a MemoryError depending on available resources.

As such, whenever possible, you should always mark `fetch` tasks with `become: false`, to prevent this from happening.

**Comment by boedah** [comment]
@sivel thanks, understood.

Would it be possible to check beforehand if a file is readable?

**Comment by Challa-shekhar** [comment]
i keep getting this when trying out       Ansible 2.1.0.0

```
 - name: Copy Middleware Installer
   copy: src={{ mw_installer }}
            dest={{ installables_home }}
            owner={{ oracle_user }}
            group={{ oracle_group }}
```

I am trying to copy the mw installer that is 1 GB. the target system has 16 GB memory and has lot of space left..the master from where i run ansible has 1 GB of RAM.

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 124, in run
 res = self._execute()
File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 446, in _execute
result = self._handler.run(task_vars=variables)
File "/usr/lib/python2.7/site-packages/ansible/plugins/action/copy.py", line 156, in run
source_full = self._loader.get_real_file(source_full)
File "/usr/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 334, in get_real_file
data = f.read()
MemoryError

fatal: [10.135.239.23]: FAILED! => {"failed": true, "msg": "Unexpected failure during module        
```

execution.", "stdout": ""}

**Comment by appcara-kaminglau** [comment]
I'm still encountering same issue above on both Ansible 2.0.2 and 2.1.1. File size is about 400MB.

Playbook

```
   - name: fetch the redis database dump
      fetch: src=/var/lib/redis/dump.rdb dest="{{ playbook_dir }}/backup/{{ ansible_date_time.date }}-{{ ansible_date_time.hour + ansible_date_time.minute + ansible_date_time.second }}-{{ ansible_hostname }}.rdb" flat=yes
      become: false

```

Stack trace...

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 124, in run
    res = self._execute()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 448, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/fetch.py", line 72, in run
    slurpres = self._execute_module(module_name='slurp', module_args=dict(src=source), task_vars=task_vars, tmp=tmp)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 644, in _execute_module
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 723, in _low_level_execute_command
    out = to_unicode(stdout, errors=encoding_errors)
  File "/usr/lib/python2.7/dist-packages/ansible/utils/unicode.py", line 100, in to_unicode
    return text_type(obj, 'utf-8', errors)
MemoryError

fatal: [redis]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Comment by grizmin** [comment]
It seems the issue has not been fixed.

root@ansible:/etc/ansible/playbooks/javanodes[env: qa1]# ansible --version
ansible 2.2.0 (devel 15ee97d214) last updated 2016/10/03 13:05:00 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 7de287237f) last updated 2016/07/17 11:35:06 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 68ca157f3b) last updated 2016/07/17 11:35:10 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

root@ansible:/etc/ansible/playbooks/javanodes[env: qa1]# ansible qansible qa1-feeder3 -m copy -a "src=/root/.ansible/assets/jdk-8u66-linux-x64.tar.gz dest=/tmp/jdk-8u66-linux-x64.tar.gz" -vvv
Using /etc/ansible/ansible.cfg as config file
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/root/ansible/lib/ansible/executor/task_executor.py", line 122, in run
    res = self._execute()
  File "/root/ansible/lib/ansible/executor/task_executor.py", line 488, in _execute
    result = self._handler.run(task_vars=variables)
  File "/root/ansible/lib/ansible/plugins/action/copy.py", line 153, in run
    source_full = self._loader.get_real_file(source_full)
  File "/root/ansible/lib/ansible/parsing/dataloader.py", line 398, in get_real_file
    if is_encrypted_file(f):
  File "/root/ansible/lib/ansible/parsing/vault/__init__.py", line 152, in is_encrypted_file
    b_vaulttext = to_bytes(to_text(vaulttext, encoding='ascii', errors='strict'), encoding='ascii', errors='strict')
  File "/root/ansible/lib/ansible/module_utils/_text.py", line 183, in to_text
    return obj.decode(encoding, errors)
MemoryError

qa1-feeder3 | FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
root@ansible:/etc/ansible/playbooks/javanodes[env: qa1]#
root@ansible:/etc/ansible/playbooks/javanodes[env: qa1]# ls -lath /root/.ansible/assets/jdk-8u66-linux-x64.tar.gz
-rw-r--r-- 1 root root 173M Jul 19 21:45 /root/.ansible/assets/jdk-8u66-linux-x64.tar.gz
THere is no memory overcommit allowed on the VM.
VM has 1g memory and nothing running except ansible.

**Comment by serialdoom** [comment]
still happening for

```
ansible --version
 ansible 2.2.0.0
```

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: MemoryError
fatal: [ds01]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

and the file is about 2GB

**Comment by gadelkareem** [comment]
Happening here with v2.2 with copy
```
- name: Deploying archive
  copy: src={{ local_archive }}
        dest={{ remote_archive }}
        backup=no
  when: bz2.stat.exists == False and dir.stat.exists == False
  retries: 10
```
from vagrant
    vagrant memory = 3000
    vagrant cpus = 2

**Comment by jurajseffer** [comment]
`unarchive` module fails with Ansible 2.2.0.0 for a ~400MB tar.gz archive on a 7GB ram machine.
```
12/01/2017 06:00:37An exception occurred during task execution. To see the full traceback, use -vvv. The error was: MemoryError
12/01/2017 06:00:37fatal: [localhost]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Comment by Wenzel** [comment]
Hi! 
using ansible `ansible 2.2.0.0` here and i have the same issue.
I tried to copy a `26G` qcow2 file.

**Comment by sihanwang41** [comment]
Hi,
same issue in 2.2.1. Copy 300mb file, it failed with MemoryError

copy_hugefile.yml
---
- hosts: lb
  become: yes

  tasks:
    - name: Copy huge file
      fetch: src=/tmp/300mb.log dest=/tmp

it failed with
TASK [Copy huge file] **********************************************************
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 126, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 502, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/fetch.py", line 73, in run
    slurpres = self._execute_module(module_name='slurp', module_args=dict(src=source), task_vars=task_vars, tmp=tmp)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 664, in _execute_module
    data = self._parse_returned_data(res)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 709, in _parse_returned_data
    filtered_output, warnings = _filter_non_json_lines(res.get('stdout', u''))
  File "/usr/local/lib/python2.7/dist-packages/ansible/module_utils/json_utils.py", line 45, in _filter_non_json_lines
    lines = data.splitlines()
MemoryError

fatal: [192.168.111.162]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}

**Comment by behrangsa** [comment]
This should be re-opened. Still happens with Ansible `2.3.0.0`.

**Comment by hvisage** [comment]
It is definitely an issue where I have to use become as the file is dumped in a location I'll need to "become" to get to, otherwise I'll have to copy (in my case) the file out to a different place to be able to not break other security issues

**Comment by alxndr13** [comment]
Still happens with 2.6.4

**Comment by ankitcharolia** [comment]
still happens with latest ansible version :(

**Comment by laviua** [comment]
2.7.1 the same

**Comment by mirageglobe** [comment]
yep same with 2.7.4 ... erm just a random suggestion.. cant there be a check for remote available memory vs filesize before initiating the slurp function; built into the fetch function? at least a simple message or workaround rather than just failing.

**Comment by elliott2019** [comment]
2.7.4 not work……
