### ISSUE TITLE
allow_duplicates not working

### ISSUE THREAD

**Issue by MorphBonehunter** [ansible/ansible#11707]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.2
  configured module search path = None
##### Environment:

Arch Linux
##### Summary:

Taken from my Post here: https://groups.google.com/forum/#!topic/ansible-project/lsFr9tAUdUE
Yesterday i took another try on the role dependency feature and realize that this doesn't work as i expect this as the dependencies are not multiple executed with the "allow_duplicates: yes" feature enabled and also not executed when i use Tags on the roles.
##### Steps To Reproduce:

I try to explain what i mean with an sample playbook/roles:

```
$ cat play-test.yml

---
- name: dependency test
  gather_facts: false
  hosts: localhost

  roles:
    - { role: feature1 }
    - { role: feature2 }

$ cat roles/feature1/tasks/main.yml

---
- name: in feature1
  debug: msg="here we are in feature1"

$ cat roles/feature1/meta/main.yml

---
allow_duplicates: yes
dependencies:
  - { role: base }

$ cat roles/feature2/tasks/main.yml

---
- name: in feature2
  debug: msg="here we are in feature2"

$ cat roles/feature2/meta/main.yml

---
allow_duplicates: yes
dependencies:
  - { role: base }

$ cat roles/base/tasks/main.yml

---
- name: in base
  debug: msg="here we are in base"
```

I would expect because of the allow_duplicates: yes that the basic role is executed twice but that doesn't happen:

```
$ ansible-playbook play-test.yml

PLAY [dependency test] ********************************************************

TASK: [base | in base] ********************************************************
ok: [localhost] => {
    "msg": "here we are in base"
}

TASK: [feature1 | in feature1] ************************************************
ok: [localhost] => {
    "msg": "here we are in feature1"
}

TASK: [feature2 | in feature2] ************************************************
ok: [localhost] => {
    "msg": "here we are in feature2"
}

PLAY RECAP ********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

After that I extend the example with another pice named tags:

```
$ cat play-test.yml

---
- name: dependency test
  gather_facts: false
  hosts: localhost

  roles:
    - { role: feature1, tags: feature1 }
    - { role: feature2, tags: feature2 }
```

This gives me another strage behavior if you look at the following output (i used --list-tags for simplicity):

```
$ ansible-playbook play-test.yml --list-tasks

playbook: play-test.yml

  play #1 (dependency test):    TAGS: []
    in base TAGS: [feature1]
    in feature1 TAGS: [feature1]
    in feature2 TAGS: [feature2]
```

As there is still "allow_duplicates: yes" active, i would expect the execution of base 2 times.
So i try the following (as this is my initial intention to use role dependencys and tags):

```
$ ansible-playbook play-test.yml --list-tasks -t feature1

playbook: play-test.yml

  play #1 (dependency test):    TAGS: []
    in base TAGS: [feature1]
    in feature1 TAGS: [feature1]
```

Looks OK to me, but then:

```
$ ansible-playbook play-test.yml --list-tasks -t feature2

playbook: play-test.yml

  play #1 (dependency test):    TAGS: []
    in feature2 TAGS: [feature2]
```

So in the second try the base role isn't run at all.
This is definitely not the expected behavior. In the role "feature2" the dependency is set to the "basic" role and in my eyes if i specify an role with an tag the dependency should run (like the first one).

Did i miss something?

BTW: This is the inverse behavior as i realized in this bug: #9578
This was closed with:

```
this is expected, the 'no duplicates' is not just on role name but on the role 'signature' so by passing different tags you make them 'differnt roles'."
```

It seems that this breaks on the way from 1.7.2 to 1.9.2

All in all i'm really confused about the actual behavior with the meta - dependency stuff and the tags stuff.

In the docs the Tags feature is described with "If you have a large playbook it may become useful to be able to run a specific part of the configuration without running the whole playbook."
But when someone try to use it together with the dependency feature this is broken.
- the old behavior is to run the dependency for every Tag Keyword (witch it is not what i expect from the combination)
- actually the dependency is only run once on the first role defined in playbook which depends on the role

**Comment by jimi-c** [comment]
Hi @MorphBonehunter, the problem is because `allow_duplicates` needs to be set on the base role, not in each of the intermediate roles. Move it there and this should work for you.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by MorphBonehunter** [comment]
Thanks @jimi-c, that explains a lot.
I've move the "allow_duplicates: yes" to the base role and delete the entry in all other roles and it works like you sad...so that was my fault.
But something is still strange (thats why i'm posting here again) when i remove the "allow_duplicates: yes" also in the base role i got the following:

```
ansible-playbook play-test.yml --list-tasks

playbook: play-test.yml

  play #1 (dependency test):    TAGS: []
    in base TAGS: [feature1]
    in feature1 TAGS: [feature1]
    in feature2 TAGS: [feature2]
```

That one works expected. Then i tried to use the "-t" switch:

```
 $ ansible-playbook play-test.yml --list-tasks -t feature1

playbook: play-test.yml

  play #1 (dependency test):    TAGS: []
    in base TAGS: [feature1]
    in feature1 TAGS: [feature1]

 $ ansible-playbook play-test.yml --list-tasks -t feature2

playbook: play-test.yml

  play #1 (dependency test):    TAGS: []
    in feature2 TAGS: [feature2]
```

So in the second case the base role isn't executed and this i think is not as expected.

BTW: I've also update my Thread in the Google Group: 
https://groups.google.com/forum/#!topic/ansible-project/lsFr9tAUdUE

**Comment by jimi-c** [comment]
Yes, that is a bug with the "diamond" pattern of role use, which has been fixed in the devel branch. That was a particularly nasty long-standing bug which was nearly impossible to correct in the original code base, and one of the reasons contributing to the refactoring that is 2.0.
