### ISSUE TITLE
skip tags

### ISSUE THREAD

**Issue by awasilyev** [ansible/ansible#11716]
Ok, we can run only tasks/roles market by some tags.
It will be nice to have ability to run all tasks/roles which does not market with some specified tags.

**Comment by bcoca** [comment]
have you looked as --skip-tags

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
