### ISSUE TITLE
Ansible hangs when strategy: free

### ISSUE THREAD

**Issue by ynnt** [ansible/ansible#11713]
Playbook:

<pre>---
- hosts: all
  sudo: yes
  strategy: free
  tasks:
  - name: fetch dump
    fetch: src=/tmp/dump.rdb dest=/tmp/{{ inventory_hostname }}
</pre>

Command:
`ansible-playbook -i hosts test_str.yml --ask-sudo-pass  -vvv`

Output:

<pre>SUDO password:
1 plays in test_str.yml

PLAY ****************************************************************************

TASK [setup] ********************************************************************
<example.com> ESTABLISH SSH CONNECTION FOR USER: arseniy
<example.com> EXEC ssh -C -tt -q -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=arseniy -o ConnectTimeout=10 example.com mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1437677728.34-220898981465849" && chmod a+rx "$HOME/.ansible/tmp/ansible-tmp-1437677728.34-220898981465849" && echo "$HOME/.ansible/tmp/ansible-tmp-1437677728.34-220898981465849"
<example.com> ESTABLISH SSH CONNECTION FOR USER: arseniy
<example.com> PUT /var/folders/m3/m5hb5gbx3g57d60cj9nb30x40000gp/T/tmpt5hIFp TO /home/arseniy/.ansible/tmp/ansible-tmp-1437677728.34-220898981465849/setup
<example.com> ESTABLISH SSH CONNECTION FOR USER: arseniy
<example.com> EXEC ssh -C -tt -q -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=arseniy -o ConnectTimeout=example.com /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=rzxwzgrdjhibssyapvbxjaryppftqjlz] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-rzxwzgrdjhibssyapvbxjaryppftqjlz; LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/arseniy/.ansible/tmp/ansible-tmp-1437677728.34-220898981465849/setup; rm -rf "/home/arseniy/.ansible/tmp/ansible-tmp-1437677728.34-220898981465849/" >/dev/null 2>&1'"'"''
ok: [node11]
^C
PLAY RECAP **********************************************************************
node11                     : ok=1    changed=0    unreachable=0    failed=0
</pre>

After this line:
`ok: [node11]`
ansible hung and nothing occured until I canceled task.

**Comment by bcoca** [comment]
fixed via 88e1ef8c9bc6434786ce10dbf0ed46a5b2448c1c

**Comment by ynnt** [comment]
Yes, now it works, thank you.
