### ISSUE TITLE
Ansible iam module documentation gives wrong information.

### ISSUE THREAD

**Issue by xuchen81** [ansible/ansible#11711]
http://docs.ansible.com/ansible/iam_module.html

It says iam - Manage IAM users, groups, roles and keys as title, but iam_type key only accepts user, group, role, it does not manage keys at all. I tried to get the server key, but it does not work. The documentation needs to be updated, it will confuse a lot of people.

**Comment by bcoca** [comment]
cc @defionscod

**Comment by mscherer** [comment]
I guess the right CC is better, so it should be @defionscode  

Also, I am not familliar with ec2, but it seems to be able to remove and add access keys to user, so isn't it what the summary is saying ? (cause I could make a PR, but no idea on what to say there)

**Comment by juliedavila** [comment]
Documentation clarified via https://github.com/ansible/ansible-modules-core/pull/3245

**Comment by juliedavila** [comment]
See what happens when I'm CC'd properly? ;)

**Comment by bcoca** [comment]
closing via mergted https://github.com/ansible/ansible-modules-core/issues/3245
