### ISSUE TITLE
Yum does not use localinstall when specifying an rpm

### ISSUE THREAD

**Issue by rothgar** [ansible/ansible#11727]
Ansible Version: 1.9.2

Ansible Configuration: no changes

Environment: running from RedHat 7.1 to RedHat 7.1

Summary:
When specifying an rpm to install on a host that is not register I get an error.

```
- yum: name=http://server/package.rpm state=present
```

gives the error

```
subscription-manager\nThis system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.\n
```

if the host is not registered with subscription-manager.

Steps to reproduce:
Un-register a system using `subscription-manager unregister` and optionally `subscription-manager clean` and then run the yum task above.

Expected results:
when specifying an rpm package to yum the yum localinstall command should be used which does dependency checking but no registration verification.

**Comment by mscherer** [comment]
So, if I use:

```
- yum: name={{ item }}
  with_items:
  - foo
  - http://server/package.rpm
```

What do we expect to happen ?
(I would say "fail"), but before going into bug fix mode, i would check)

**Comment by mscherer** [comment]
Also, this should have been filled on another git repository ( https://github.com/ansible/ansible-modules-core ), here is the PR I propose as a fix ( for now, just for discussion )

https://github.com/ansible/ansible-modules-core/pull/1803

**Comment by jimi-c** [comment]
Hi @rothgar, @mscherer is correct, could you please open this issue on the ansible-modules-core repo? We'll close this one now.

Thanks!
