### ISSUE TITLE
docs bug on host key checking

### ISSUE THREAD

**Issue by thoraxe** [ansible/ansible#11725]
http://docs.ansible.com/ansible/intro_getting_started.html#host-key-checking

```
[defaults]
host_key_checking = False
```

Gives an error:

```
ERROR: hosts:2: Invalid ini entry: False - need more than 1 value to unpack
```

I'm not sure if this is an older version of Ansible bug or not. I'm using ansible 1.9.1 on F20.

**Comment by bcoca** [comment]
i created an ansible.cfg with just that and there is no error. It is either picking up a different ansible.cfg or it is happening at anothe rpoint in the file.

**Comment by thoraxe** [comment]
Actually I was thinking this goes in a hosts file, and not in ansible.cfg. Sorry for the noise.
