### ISSUE TITLE
Allow vars file includes from vars files

### ISSUE THREAD

**Issue by adeck** [ansible/ansible#11728]
To allow for hierarchical structuring.
Specifically, this matters most for the defaults/ directory, where employing `include_vars` from the playbook itself would have the undesirable effect of increasing the precedence of the variables within the file.

I suppose this could also be resolved by simply associating different files with different priorities, and adding an option to `include_vars` which specifies the the variables defined therein are defaults, to be overridden. Mainly, though, hierarchical structuring is what I'm hoping for.

The current alternative is a "flat" defaults/main.yml, which contains every possible var which would need a default. This rapidly becomes unreadably lengthy.

**Comment by bcoca** [comment]
the thing is that vars files are pure YAML, which does not include a 'include' facility, that said something can be wrapped around it. 

Currently we allow for more than main.yml to be included either via vars_files in a play or include_vars as a task. But I'll keep the ticket open in case someone feels like they can implement this feature and think he can convince core to accept it.

**Comment by bcoca** [comment]
so after more thought, I'm going to close this ticket, as there are already ways to achieve the same result w/o the need of further development.

**Comment by adeck** [comment]
Well, the issue isn't that you can't include more vars files, the issue is (specifically with the `defaults` directory) that you can't have multiple vars files with that lowest, default priority.

So, if I used `include_vars` or `vars_files` in the role itself, I might be overriding variables set elsewhere. There are ways to ameliorate this, but they're really hacky.
