### ISSUE TITLE
v2 breakage: --list-tasks doesn't list tasks inside roles

### ISSUE THREAD

**Issue by amenonsen** [ansible/ansible#11737]
Issue type: Bug report
Ansible version: devel@5be384ba
Ansible configuration: NA
Environment: NA
Summary:

While investigating #6216 I found that `--list-tasks` in devel doesn't list tasks inside roles.

Steps to reproduce:

Run

```
ansible-playbook x.yml --list-tasks
```

on a playbook that includes some roles.

Expected results:

Tasks inside roles are listed.

Actual results:

Tasks inside roles aren't listed, only pre_tasks/post_tasks are.

**Comment by amenonsen** [comment]
Also, `--list-tags` seems to do much the same thing as `--list-tasks` (i.e. it doesn't list tags; but the task names aren't wrapped in `[]`).

**Comment by amenonsen** [comment]
Sorry, I meant to link to PR #9914, not issue #6216.

**Comment by bcoca** [comment]
both are not implemented yet, I started to but blocks and role loading were not finalized yet so they don't really work well. It is still on my todo.

--list-tags actually depends on --list-tasks so that will probably be the implementation order

**Comment by bcoca** [comment]
fixed via c0c094c413539ca629d39037a1319266ee21e23d
