### ISSUE TITLE
Make ec2.py inventory script importable

### ISSUE THREAD

**Issue by adamhadani** [ansible/ansible#11745]
Trying to build off the work in ec2.py, one is tempted to try and have a new script import the stock one and then derive from Ec2Inventory. 
I've actually been using this technique but had to make a slight modification to the ec2.py script.

I've created a PR for this issue ( #11744 ) for your kind consideration.

Note: this Issue is a clone of the original issue ( #8700 ) I created on this a while back which was closed due to ansible modules repositories branching out.

**Comment by bcoca** [comment]
closing and keeping track of the request in  #11744
