### ISSUE TITLE
v2 relative path with with_fileglob ... resolves the path relative roles/<rolename>/files 

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#11746]
##### Issue Type:

Bug Report
##### Ansible Version:

 ansible --version
ansible 2.0.0 (devel c56a304ad9) last updated 2015/07/26 16:43:12 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 2bfddb015d) last updated 2015/07/26 16:43:13 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 14fffa5b53) last updated 2015/07/24 12:24:44 (GMT -500)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/03 00:37:54 (GMT -500)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/03 00:37:58 (GMT -500)
  config file =
  configured module search path = None
##### Ansible Configuration:

$ source hacking/env-setup
##### Environment:

OS X Yosemite 10.10.4

$ python -V
Python 2.7.6

$ pip freeze
ansible==2.0.0
coverage==3.7.1
coveralls==0.5
docopt==0.6.2
ecdsa==0.13
epdb==0.12
httplib2==0.9.1
isodate==0.5.1
Jinja2==2.7.3
kerberos==1.2.2
linecache2==1.0.0
MarkupSafe==0.23
mock==1.0.1
nose==1.3.7
paramiko==1.15.2
passlib==1.6.2
pycallgraph==1.0.1
pycrypto==2.6.1
pywinrm==0.0.3
PyYAML==3.11
requests==2.7.0
six==1.9.0
traceback2==1.4.0
unittest2==1.0.1
xmltodict==0.9.2
##### Summary:

[Loops](http://docs.ansible.com/ansible/playbooks_loops.html) says with_fileglob "When using a relative path with with_fileglob in a role, Ansible resolves the path relative to the roles/<rolename>/files directory." but debugging shows this not to be true.
##### Steps To Reproduce:

A play from main.yml from the nagios-servers role that lives in /Volumes/Warrior1TB/Users/tanner/projects/ansible.git/playbooks/roles/nagios-servers/tasks

``` yaml
- name: deploy ssl keys and certificates
  copy: >
      src={{ item }}
      dest=/etc/ssl/private/
      owner=root
      group=root
      mode=0644
  with_fileglob:
      - z*
  sudo: yes
```

```
$ source hacking/env-setup
$ cd ../playbooks/
$ ansible-playbook -i vagrant_inventory --private-key private_key -u vagrant vagrant.yml -vv
PLAY ****************************************************************************
TASK [setup] ********************************************************************
ok: [default]
<snip>
TASK [nagios-servers : deploy ssl keys and certificates] ************************
ok: [default] => {"changed": false, "msg": "All items completed", "results": [{"changed": false, "checksum": "e438cb27db8f5a95d30895eb026a4bc054a4880a", "dest": "/etc/ssl/private/zimbra-test.yml", "gid": 0, "group": "root", "item": "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/playbooks/zimbra-test.yml", "mode": "0644", "owner": "root", "path": "/etc/ssl/private/zimbra-test.yml", "size": 97, "state": "file", "uid": 0}]}
<snip>
```

Changing the play to look like this:

``` yaml
- name: deploy ssl keys and certificates
  copy: >
      src={{ item }}
      dest=/etc/ssl/private/
      owner=root
      group=root
      mode=0644
  with_fileglob:
      - roles/nagios-servers/files/private/*.key
  sudo: yes
```

Then I things work as expected.

```
TASK [nagios-servers : deploy ssl keys and certificates] ************************
changed: [default] => {"changed": true, "msg": "All items completed", "results": [{"changed": true, "checksum": "efef8a929184a1d7b60e7b6e109ab1353c7ba0f7", "dest": "/etc/ssl/private/host1.key", "gid": 0, "group": "root", "item": "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/playbooks/roles/nagios-servers/files/private/host1.key", "md5sum": "ea57738ef5c61f907b7ef57ddccc437d", "mode": "0644", "owner": "root", "size": 887, "src": "/home/vagrant/.ansible/tmp/ansible-tmp-1437948349.4-171971408204783/source", "state": "file", "uid": 0}, {"changed": true, "checksum": "6bcdfade8828b63ebf0906bd704e8209c8057f89", "dest": "/etc/ssl/private/host2.key", "gid": 0, "group": "root", "item": "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/playbooks/roles/nagios-servers/files/private/host2.key", "md5sum": "873b872bc7f328a059c3e6cb105d1d49", "mode": "0644", "owner": "root", "size": 2968, "src": "/home/vagrant/.ansible/tmp/ansible-tmp-1437948349.64-139826384825646/source", "state": "file", "uid": 0}]}
```
##### Expected Results:

I'd assume using the relative path with_fileglob: would put me into /Volumes/Warrior1TB/Users/tanner/projects/ansible.git/playbooks/roles/nagios-servers/files

Might be a documentation out-of-date-issue as I believe [Loops](http://docs.ansible.com/ansible/playbooks_loops.html) still references the pre v2 code base. But if v2 changed behavior many of my with_fileglob: plays break and users should be warned of the breakage.
##### Actual Results:

The relative path with with_fileglob: is being set to /Volumes/Warrior1TB/Users/tanner/projects/ansible.git/playbooks/

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
