### ISSUE TITLE
problem running rax.py

### ISSUE THREAD

**Issue by jkarneges** [ansible/ansible#11758]
I downloaded rax.py into an inventory directory and marked it executable:

```
$ ls -l inventory/
total 16
-rw-rw-r-- 1 justin justin   140 Jul 27 13:14 hosts
-rwxrwxr-x 1 justin justin 11974 Jul 27 14:42 rax.py
```

(Note: the [docs](http://docs.ansible.com/ansible/guide_rax.html) don't actually say where to get the file, but after some googling I found it here [here](https://raw.githubusercontent.com/ansible/ansible/devel/lib/ansible/module_utils/rax.py).

But I get an error when trying to use it:

```
$ RAX_CREDS_FILE=raxcreds.conf ansible all -i inventory/ -m setup
ERROR: problem running /home/justin/tmp/inventory/rax.py --list ([Errno 8] Exec format error)
```

**Comment by jkarneges** [comment]
Figured it out. Various links around the internet are incorrect now that v2 development takes place in the devel branch. Here's the link to rax.py that a stable version user will need:
https://raw.githubusercontent.com/ansible/ansible/v1.9.2-1/plugins/inventory/rax.py

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
