### ISSUE TITLE
with_items bug (or yum?)

### ISSUE THREAD

**Issue by nicolaasuni** [ansible/ansible#1175]
```
Using the Ansible version on GitHub (ansible-0.8-0.git201210010233).
When executing the following task:

- name: install GIT
  action: yum pkg=$item state=installed
  with_items:
    - git

I am getting the following error:

failed: [xx.xx.xx.xx] => {"changed": false, "failed": true, "item": "", "msg": "No Package matching '' found available, installed or updated", "rc": 0, "results": []}
```

**Comment by mpdehaan** [comment]
With items and yum is working fine for me.

Please check that you're not using an old library module directory.

If you are still having problems, there may be a bug with the yum module.

Can you see if you can execute it normally from the command line:

ansible <hostname> -m -a "pkg=git state=installed"

and see what happens?

**Comment by nicolaasuni** [comment]
to reproduce the problem you can use these 3 files:
http://pastebin.com/tw24msX4

**Comment by mpdehaan** [comment]
fixed today per pull requests, closing ... let me know if you disagree but I think we agreed we're good to go

Thanks!

**Comment by nicolaasuni** [comment]
OK. Now it works. Thank you :)
