### ISSUE TITLE
unarchive module fails if archive contains files with non-ascii file names

### ISSUE THREAD

**Issue by apechinsky** [ansible/ansible#11763]
- ubuntu 14.04
- ansible 1.9.2
1. create archive (zip or tar) containing file with non-ascii name
2. run the following command

```
  ansible all -i localhost, -m unarchive -a 'src=archive.zip dest=.' -vvvv
```

result:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-7: ordinal not in range(128)

**Comment by jimi-c** [comment]
Hi @apechinsky, I believe this has been corrected in the devel branch. Would you mind giving this a test there and letting us know if you still see the same issue?

Thanks!

**Comment by jimi-c** [comment]
For example, this bug was recently closed: https://github.com/ansible/ansible/issues/11348

**Comment by edouard-lopez** [comment]
Updating to **`ansible 1.9.4` doesn't fix** problem:

```
failed: [192.168.5.x.x] => {"failed": true, "parsed": false}
BECOME-SUCCESS-qnkykixeazpxmwuggqpojklnbkebtngy
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1451905237.06-218757393623996/unarchive", line 1904, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1451905237.06-218757393623996/unarchive", line 290, in main
    res_args['changed'] = module.set_fs_attributes_if_different(file_args, res_args['changed'])
  File "/root/.ansible/tmp/ansible-tmp-1451905237.06-218757393623996/unarchive", line 1099, in set_fs_attributes_if_different
    file_args['path'], file_args['mode'], changed
  File "/root/.ansible/tmp/ansible-tmp-1451905237.06-218757393623996/unarchive", line 937, in set_mode_if_different
    path_stat = os.lstat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 30: ordinal not in range(128)
OpenSSH_6.9p1 Ubuntu-2, OpenSSL 1.0.2d 9 Jul 2015
debug1: Reading configuration data /home/elopez/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 192.168.5.x.x closed.


FATAL: all hosts have already failed -- aborting
```

## Environment

### Linux Distribution

```
$ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 15.10
    Release:        15.10
    Codename:       wily
```

### Ansible

```
$ ansible --version
ansible 1.9.4
  configured module search path = None
```

### Task

```
- name: Unarchive app
  unarchive: src={{app_name}}.zip dest={{ app_dir }}
  tags: [archivist]
```

**Comment by jimi-c** [comment]
@edouard-lopez as mentioned, the fix is in the devel branch, not the stable-1.9 branch. Due to the amount of work involved in devel/2.0, many patches cannot simply be backported, and instead require the problem to be completely reworked. We can mark this as being a bug for 1.9 still, however there is no guarantee we'll fix it as we move forward. We weigh that against the severity of the bug vs. the work involved.

**Comment by edouard-lopez** [comment]
@jimi-c installing the `devel` version fix it, thanks.

**Comment by abadger** [comment]
Closing as this was fixed in devel and at this point it's unlikely we will backport it to 1.9.
