### ISSUE TITLE
include task ignores when condition

### ISSUE THREAD

**Issue by emanation** [ansible/ansible#11760]
Hello. 
I was thinking that doing wrong but changing task type to debug shows that it works.

main.yml file in a "create_user" role has task

```
- name: extra keys for {{ username }} user
  debug: var=sshpubkeys
  when: sshpubkeys is defined
```

sshpubkeys is defined at groups_vars/groupname.yml and if file exists I see

```
TASK: [create_user | extra keys for ansibletest user] *** 
ok: [myserver.com] => {
    "var": {
        "sshpubkeys": [
            "user1",
            "user2"
        ]
    }
}
```

If groups_vars/groupname.yml file is absent this task is skipped

Problem occurs if task is include instead of debug

```
- name: extra keys for {{ username }} user
  include: allow_users.yml
  when: sshpubkeys is defined
```

and groups_vars/groupname.yml is missed

allow_users.yml included file has 

```

---
- name: Set up Relevant Developers authorized_keys for the {{ username }} user
  authorized_key: user={{ username }}
                  key="{{ lookup('file', 'public_keys/ssh/'+item ) }}"
  with_items: "{{ sshpubkeys }}"
```

and seems file is included unconditionally 

```
TASK: [create_user | Set up Relevant Developers authorized_keys for the mrweb user] *** 
fatal: [myserver.com] => with_items expects a list or a set

FATAL: all hosts have already failed -- aborting
```

Also I don't see in this Play output of `TASK: [create_user | extra keys for ansibletest user]`

ansibletest is defined when role is called.

```
- { role: create_user, username: ansibletest, tags: [ 'common', 'users' ] }
```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The include itself cannot be negated, the when condition is applied to all the included tasks.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
