### ISSUE TITLE
Rackspace - rax_cbs.py, minimum size has changed

### ISSUE THREAD

**Issue by hbokh** [ansible/ansible#11770]
Please change the minimum size of an Ansible-created Rackspace Cloud Block Storage in module `rax_cbs.py`.  
The default minimum size has been lowered to 75GB and is not 100GB anymore. When a playbook is run with `size: 75` this error occurs:

```
TASK: [Storage volume create request] *****************************************
failed: [localhost -> 127.0.0.1] => {"failed": true}
msg: Volume sizes must be integers between 100 and 1024.
```

The Rackspace webGUI says: '75-1024 GB. Can't be resized later.".
So please change the value of 100 into 75.

**Comment by angstwad** [comment]
That's correct -- sizes recently changed to a lower limit of 75. I'll take a look and open a PR resolving this.

**Comment by angstwad** [comment]
@hbokh Please upgrade the installed `pyrax` version to 1.9.4.   **This is not an issue in core Ansible.**   This issue was resolved by the release of v1.9.4 in `pyrax`: https://github.com/rackspace/pyrax/commit/73059566ab91570c966e6e86338c666bc7f528ed

And please be advised: issues for Rackspace modules should be opened in https://github.com/ansible/ansible-modules-core.

**Comment by bcoca** [comment]
closing as per comment abovfe

**Comment by hbokh** [comment]
Thanks all. FYI this DOES happen with pyrax 1.9.4.

**Comment by angstwad** [comment]
@hbokh I think there's another issue happening.  There is nothing in the rax_cbs module that enforces volume sizes - it merely passes the size into Pyrax, and bubbles up the error to Ansible if there is one.

Version 1.9.4 in Pyrax removes the code which creates this error: https://github.com/rackspace/pyrax/commit/70d5c10feceebd9be3991858b047f6587bef5e5e#diff-2e3d76a4376063f981b23bec57927619L254

Please validate that the Python environment in which you're running Ansible has access to the latest version of pyrax.  You might also consider installing Ansible inside a virtualenv and installing pyrax there, to minimize any ambiguity in your Python package environment.  

I've validated that this does work from the checkout of the latest version of ansible in devel.  
Please make sure that if you're executing this connection locally, that you set the appropriate values.  I have pyrax 1.9.4 installed locally in my virtualenv, so I have to set my hosts file to point to my virtualenv's python interpreter.  **I suspect that Ansible is invoking an interpreter that does not have the latest pyrax installed.**  

My inventory:

```
[local]
localhost ansible_python_interpreter=/Users/paul4611/Projects/Python/virtualenvs/ansible/bin/python ansible_connection=local
```

```
$ ansible -i hosts -m rax_cbs -a "name=testvolume1 size=75 creds_file=~/.rackspace_cloud_credentials region=DFW" all
localhost | SUCCESS => {
    "changed": true,
    "volume": {
        "HUMAN_ID": false,
        "NAME_ATTR": "name",
        "attachments": [],
        "availability_zone": "nova",
        "bootable": "false",
        "created_at": "2015-07-29T16:10:44.000000",
        "description": "",
        "display_description": "",
        "display_name": "testvolume1",
        "encrypted": false,
        "get_details": true,
        "human_id": null,
        "id": "7a5efe01-e15e-4d8c-8d9b-3383b4de272c",
        "loaded": true,
        "metadata": {},
        "name": "testvolume1",
        "size": 75,
        "snapshot_id": null,
        "source_volid": null,
        "status": "creating",
        "volume_type": "SATA"
    }
}
```
