### ISSUE TITLE
setting a list of vars: on a block: results in a weird error

### ISSUE THREAD

**Issue by amenonsen** [ansible/ansible#11779]
Issue type: Bug report
Ansible version: devel
Ansible configuration: NA
Environment: NA
Summary:

The following works as expected:

```

---
- hosts: localhost
  vars:
    - a: 42
    - b: 31
  tasks:
    - debug: msg="{{a+b}}"
```

But if I set the vars like this on a block, it breaks with a weird error message as shown below:

```

---
- hosts: localhost
  tasks:
    - block:
        - debug: msg="{{a+b}}"
      vars:
        - a: 42
        - b: 31
```

If I use the following syntax, it works in both cases:

```
vars:
  a: 42
  b: 31
```

Steps to reproduce:

Run `ansible-playbook -i/dev/null second_playbook_above.yml`

Expected behaviour:

```
TASK [debug msg={{a + b}}] ******************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "73"
}
```

(This is with vars: set on the play.)

Actual behaviour:

```
PLAY ****************************************************************************
Unexpected Exception: dictionary update sequence element #0 has length 1; 2 is required
the full traceback was:

Traceback (most recent call last):
  File "/home/ams/extern/ansible/ansible/bin/ansible-playbook", line 79, in <module>
    sys.exit(cli.run())
  File "/home/ams/extern/ansible/ansible/lib/ansible/cli/playbook.py", line 148, in run
    results = pbex.run()
  File "/home/ams/extern/ansible/ansible/lib/ansible/executor/playbook_executor.py", line 139, in run
    result = self._tqm.run(play=play)
  File "/home/ams/extern/ansible/ansible/lib/ansible/executor/task_queue_manager.py", line 192, in run
    return strategy.run(iterator, play_context)
  File "/home/ams/extern/ansible/ansible/lib/ansible/plugins/strategies/linear.py", line 201, in run
    task_vars = self._variable_manager.get_vars(loader=self._loader, play=iterator._play, host=host, task=task)
  File "/home/ams/extern/ansible/ansible/lib/ansible/vars/__init__.py", line 236, in get_vars
    all_vars = self._combine_vars(all_vars, task.get_vars())
  File "/home/ams/extern/ansible/ansible/lib/ansible/playbook/task.py", line 198, in get_vars
    all_vars.update(self._block.get_vars())
  File "/home/ams/extern/ansible/ansible/lib/ansible/playbook/block.py", line 65, in get_vars
    all_vars.update(self.vars)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

(This is with vars: set on the block.)

**Comment by jimi-c** [comment]
Vars were not supposed to be allowed on blocks directly (or other playbook objects except for Play), so removing that.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by amenonsen** [comment]
`playbooks_roles.rst` says this:

```
Starting in 1.0, variables can also be passed to include files using an alternative syntax,
which also supports structured variables::

    tasks:

      - include: wordpress.yml
        vars:
            wp_user: timmy
            ssh_keys:
              - keys/one.txt
              - keys/two.txt
```

…and of course, this is broken by the commit 71867f9 and you can no longer set vars on an include.
