### ISSUE TITLE
inventory_hostname not passed to windows node when using delegate_to

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#11773]
In this example, the expected result is to have inventory_hostname be the target node name. However, when delegating to windows node, the value is empty. Running the latest commit, v1 branch.
- name: test
  win_some_module:
    host_name= "{{ inventory_hostname }}"
  delegate_to: some_windows-node

**Comment by bcoca** [comment]
v1 is dead code: https://github.com/ansible/ansible/blob/devel/v1/README.md
it is only there to allow for fast testing if an issue in devel is from v2 engine or pre existing.

**Comment by trondhindenes** [comment]
gotcha. I'm still forced to use v1 until #11462 is resolved, unfortunately.

**Comment by bcoca** [comment]
understood, but we won't be fixing bugs against it nor accepting PRs, at most we would consider against stable-1.9 which might be the source of a 1.9.3 release
