### ISSUE TITLE
ssh_args slow down

### ISSUE THREAD

**Issue by fgarcia** [ansible/ansible#11786]
Looks like using `ssh_args` causes an slowdown

```
[ssh_connection]
ssh_args = -o ForwardAgent=yes
```

Adding the above config lines caused my playbook execution time to go from 13 seconds to 4:48

Maybe the presence of ssh_args kills all SSH optimizations?

**Comment by bcoca** [comment]
read the comments above, if you don't add -o ControlMaster=auto -o ControlPersist=60s, you loose a huge speed optimization.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
