### ISSUE TITLE
su hangs indefinitely in 1.9+ while it is working fine in 1.6.10

### ISSUE THREAD

**Issue by olauret** [ansible/ansible#11788]
## Bug Description:

Simple ansible-playbook indefinitely hangs when using su. This can be repeated indefinitely. 
## Version affected:
- ansible 1.9.1
- ansible 1.9.2
## Version not affected (using the same script):
- ansible 1.6.10
## Environment tested on
- Linux Redhat/Centos
- Python version: 2.6.6
## Other details:
- The playbook is working fine if su is not used. Root credential is correct.
- Using the ping module with su works fine.
- The password prompt is "Password:" (without the quotes)
#### Main file:
- name: Install app on my servers
  hosts: my_hosts
  gather_facts: no
  remote_user: my_user
  su: yes
  
  roles:
  - app_install
#### app_install role (under tasks/main.yml)
- name: query whoami
  shell: whoami
### Log

> [PROJECT] myotheruser@myprodserver# ansible-playbook -i hosts -k --ask-su-pass my_playbook.yml -vvvv
> SSH password:
> SU password[defaults to SSH password]:
> 
> PLAY [Install app on my servers] ************************************
> 
> TASK: [app_install | query whoami] ***
> <my_server.mydomain.com> ESTABLISH CONNECTION FOR USER: my_user on PORT 22 TO my_server.mydomain.com
> <my_server.mydomain.com> REMOTE_MODULE command whoami #USE_SHELL
> <my_server.mydomain.com> EXEC /bin/sh -c 'mkdir -p /tmp/.ansible_my_user/tmp/ansible-tmp-1438014075.95-221459817104733 && chmod a+rx /tmp/.ansible_my_user/tmp/ansible-tmp-1438014075.95-221459817104733 && echo /tmp/.ansible_my_user/tmp/ansible-tmp-1438014075.95-221459817104733'
> <my_server.mydomain.com> PUT /tmp/tmp6UGeFE TO /tmp/.ansible_my_user/tmp/ansible-tmp-1438014075.95-221459817104733/command
> <my_server.mydomain.com> EXEC /bin/sh -c 'su root -c "/bin/sh -c '"'"'echo BECOME-SUCCESS-xzmbgooensxgrlbezhnlngbagojwbczg; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /tmp/.ansible_my_user/tmp/ansible-tmp-1438014075.95-221459817104733/command; rm -rf /tmp/.ansible_my_user/tmp/ansible-tmp-1438014075.95-221459817104733/ >/dev/null 2>&1'"'"'"'
### Extra tests

I have run the command below on the remote server. It is presenting the "Password:" prompt and execute correctly the command.

> /bin/sh -c 'su root -c "/bin/sh -c '"'"'echo BECOME-SUCCESS-xzmbgooensxgrlbezhnlngbagojwbczg; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /tmp/.ansible_my_user/tmp/ansible-tmp-1438014075.95-221459817104733/command; rm -rf /tmp/.ansible_my_user/tmp/ansible-tmp-1438014075.95-221459817104733/ >/dev/null 2>&1'"'"'"

**Comment by jimi-c** [comment]
Hi @olauret, we reworked a lot of the sudo/su/become code in the current devel branch. Could you do a quick test to see if you're still seeing this problem with the latest git checkout?

**Comment by olauret** [comment]
Hi jimi-c, Thank you coming back to me for this issue. I actually tried the solution the solution proposed in issue #9847 and it solves my problem. So I guess we can consider this case as a duplicate of the other one. Sorry for this, I should have search it better better opening it

**Comment by jimi-c** [comment]
Ahh great, thanks for spotting the dupe!
