### ISSUE TITLE
FAILED! => {"failed": true, "msg": "ERROR! Connection error waiting for privilege escalation password prompt: "}

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#11796]
##### Issue Type:

Bug Report
##### Ansible Version:

 ansible --version
ansible 2.0.0 (devel 769b0d92ee) last updated 2015/07/29 21:36:56 (GMT -500)
  lib/ansible/modules/core: (detached HEAD a46b3a4dc4) last updated 2015/07/28 16:17:43 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD e30d8b84fe) last updated 2015/07/28 16:17:44 (GMT -500)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/03 00:37:54 (GMT -500)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/03 00:37:58 (GMT -500)
  config file = /Volumes/Warrior1TB/Users/tanner/projects/ansible.git/playbooks/ansible.cfg
  configured module search path = None
##### Ansible Configuration:

$ source hacking/env-setup

Testing --become since --ask-sudo-pass is deprecated, edited my ansible.cfg  as follows:

```
#sudo_user      = root
#ask_sudo_pass = True
#ask_pass      = True
```

Setting default for [privilege_escalation]

```
[privilege_escalation]
become=True
become_method=sudo
become_user=root
become_ask_pass=True
```
##### Environment:

OS X Yosemite 10.10.4

$ python -V
Python 2.7.6

$ pip freeze
ansible==2.0.0
coverage==3.7.1
coveralls==0.5
docopt==0.6.2
ecdsa==0.13
epdb==0.12
httplib2==0.9.1
isodate==0.5.1
Jinja2==2.7.3
kerberos==1.2.2
linecache2==1.0.0
MarkupSafe==0.23
mock==1.0.1
nose==1.3.7
paramiko==1.15.2
passlib==1.6.2
pycallgraph==1.0.1
pycrypto==2.6.1
pywinrm==0.0.3
PyYAML==3.11
requests==2.7.0
six==1.9.0
traceback2==1.4.0
unittest2==1.0.1
xmltodict==0.9.2
##### Summary:

Setting become variables results in a 

fatal: [testing]: FAILED! => {"failed": true, "msg": "ERROR! Connection error waiting for privilege escalation password prompt: "}
##### Steps To Reproduce:

```
$ source hacking/env-setup
$ cd ../playbooks/
$ ansible-playbook -i vagrant_ansible_inventory vagrant.yml -vvvv
Using /very/long/path/to/ansible.cfg as config file
SUDO password:
1 plays in /very/long/path/vagrant.yml
Loaded callback default of type stdout, v2.0

PLAY ****************************************************************************
TASK [setup] ********************************************************************
<10.x.x.x> ESTABLISH SSH CONNECTION FOR USER: ansible
<10.x.x.x> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=600s -o ControlPath="/tmp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 10.x.x.x mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1438242874.74-249296609616610" && chmod a+rx "$HOME/.ansible/tmp/ansible-tmp-1438242874.74-249296609616610" && echo "$HOME/.ansible/tmp/ansible-tmp-1438242874.74-249296609616610"
<10.x.x.x> ESTABLISH SSH CONNECTION FOR USER: ansible
<10.x.x.x> PUT /var/folders/d_/bm7rvz154jb_2djkqybb503h0000gp/T/tmpb_HVxg TO /home/ansible/.ansible/tmp/ansible-tmp-1438242874.74-249296609616610/setup
<10.x.x.x> ESTABLISH SSH CONNECTION FOR USER: ansible
<10.x.x.x> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=600s -o ControlPath="/tmp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 10.x.x.x /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=usdcomnxrnidgeuojlngnqarewdnnosk] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-usdcomnxrnidgeuojlngnqarewdnnosk; LANG=C LC_MESSAGES=C LC_CTYPE=C /usr/bin/python ; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1438242874.74-249296609616610/" >/dev/null 2>&1'"'"''
fatal: [testing]: FAILED! => {"failed": true, "msg": "ERROR! Connection error waiting for privilege escalation password prompt: "}

NO MORE HOSTS LEFT **************************************************************
PLAY RECAP **********************************************************************
testing                    : ok=0    changed=0    unreachable=0    failed=1
```
##### Expected Results:

I assume the plays would run to completion like it does when I using '-k -K' on the command line
##### Actual Results:

fatal: [testing]: FAILED! => {"failed": true, "msg": "ERROR! Connection error waiting for privilege escalation password prompt: "}

**Comment by basictheprogram** [comment]
The setup script is copied but it looks like the setup script is not executed. Just python gets executed?

Running the commands by hand is below.  If I type in the ansible password I get dropped into the python interpreter. But the password prompt is display, so the error message is confusing. 

```
/bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=gxbbgsudxyqdsmlrywaxmhyjrdhgkmdc] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-gxbbgsudxyqdsmlrywaxmhyjrdhgkmdc; LANG=C LC_MESSAGES=C LC_CTYPE=C /usr/bin/python ; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1438243402.96-155513060521741/" '"'"''
[sudo via ansible, key=gxbbgsudxyqdsmlrywaxmhyjrdhgkmdc] password:
BECOME-SUCCESS-gxbbgsudxyqdsmlrywaxmhyjrdhgkmdc
Python 2.7.6 (default, Mar 22 2014, 22:59:56)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by basictheprogram** [comment]
```
sudo -H -S -p
     -S, --stdin
                 Write the prompt to the standard error and read the password
                 from the standard input instead of using the terminal device.
                 The password must be followed by a newline character.
```

lib/ansible/plugins/connections/ssh.py:380 only checks become_output but doesn't the sudo -S put everything on stderr? 

Looks like the only place become_output would get changed is at ssh.py:396 walking the code via debugger p.stdout is never in rfd.

This works around the problem.  

``` diff
diff --git a/lib/ansible/plugins/connections/ssh.py b/lib/ansible/plugins/connections/ssh.py
index b0b8a3d..74141dc 100644
--- a/lib/ansible/plugins/connections/ssh.py
+++ b/lib/ansible/plugins/connections/ssh.py
@@ -389,6 +389,7 @@ class Connection(ConnectionBase):
                     elif p.stderr in rfd:
                         chunk = p.stderr.read()
                         become_errput += chunk
+                        become_output += chunk
                         self.check_incorrect_password(become_errput)

                     elif p.stdout in rfd:
```

This also fixes my problem.

``` diff
diff --git a/lib/ansible/plugins/connections/ssh.py b/lib/ansible/plugins/connections/ssh.py
index b0b8a3d..a674017 100644
--- a/lib/ansible/plugins/connections/ssh.py
+++ b/lib/ansible/plugins/connections/ssh.py
@@ -377,7 +377,7 @@ class Connection(ConnectionBase):
                 become_errput = ''
                 while True:
                     self._display.debug('Waiting for Privilege Escalation input')
-                    if self.check_become_success(become_output) or self.check_password_prompt(become_output):
+                    if self.check_become_success(become_errput) or self.check_password_prompt(become_errput):
                         break

                     rfd, wfd, efd = select.select([p.stdout, p.stderr], [], [p.stdout], self._play_context.timeout)
@@ -398,7 +398,7 @@ class Connection(ConnectionBase):
                     if not chunk:
                         raise AnsibleError('Connection closed waiting for privilege escalation password prompt: %s ' % become_output)

-                if not self.check_become_success(become_output):
+                if not self.check_become_success(become_errput):
                     self._display.debug("Sending privilege escalation password.")
                     stdin.write(self._play_context.become_pass + '\n')
                 else:
```

When using become_method=sudo it looks like the sudo_flags is not honored.

**Comment by jimi-c** [comment]
@basictheprogram what is the OS of the machine you're connecting to? I've not been able to reproduce this error. Using the `-S`, the prompt is written to stderr but the rest of the output should still be going to stdout.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by basictheprogram** [comment]
Pristine install of Ubuntu 14.04.2 with no patches. 

Should have refreshed tab before responding. Did not see the ticket closed. Sorry.
