### ISSUE TITLE
fireball mode should timeout

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#1181]
```
ansible 0.8 (devel 886a17853f) last updated 2012/10/01 14:52:52 (GMT +200)
```

Running the following command against a server on which I _purposely_ killed the fireball daemon never returns:

```
ansible a1.ww.mens.de -T 10 -c fireball -m ping
```

(Using -T was an attempt -- I didn't expect the timeout to work :-)

**Comment by mpdehaan** [comment]
merging this into #1107
