### ISSUE TITLE
overriding dictionary variables in extra-vars

### ISSUE THREAD

**Issue by nirjar1** [ansible/ansible#11812]
##### Issue Type:

   Feature Idea
##### Ansible Version:

ansible 1.9.2
##### Ansible Configuration:

no changes
##### Environment:

N/A
##### Summary:

Ability to override nested dictionary variables defined in vars file with `--extra-vars` option passed in command line. 
##### Steps To Reproduce:

say a var file has content like below. 

```
repo:
  branch: int
  url: git@github:user/repo.git
  dest: "/var/code"
```

Now I want to override the value for repo.branch from extra-vars. but none of the below works.

 `--extra-vars "repo.branch=exec_refactor"`
`--extra-vars "repo[branch]=exec_refactor"`
##### Expected Results:

The branch var nested inside repo should be overridden when using either of the above methods.
##### Actual Results:

Currently the variables are not being overridden and the one defined in the var file is retained.

**Comment by bcoca** [comment]
you can do this using the json formatting
`-e "{'repo': {'branch': 'exec_refactor'}}"`

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by FelikZ** [comment]
> you can do this using the json formatting
> -e "{'repo': {'branch': 'exec_refactor'}}"

This will work, but replace the whole `repo` key content. There is a way to influence this behaviour by changing the merge strategy to `merge` instead of `replace`. But this will work globally for **all** configuration, while it would be nice to have an ability to change a single sub-key without changing the whole strategy.

The `key.sub_key` notation looks perfect for that, IMO.

**Comment by vmindru** [comment]
> you can do this using the json formatting
> `-e "{'repo': {'branch': 'exec_refactor'}}"`

the above will not work, instead of amending a key it overwrites the entire var. 

```
repo:
  branch: exec_refactor
  other_important_key: very_important
```
```
[vmindru@lsv-vm107 4]$ cat playbook.yml 
---
- hosts: localhost
  vars:
    foo:
      bar:
        key: "value"
        important_key: "important_value"
      baz:
        key: "value"
  tasks:
  - name: print
    debug:
      msg: "{{ foo }}" 
[vmindru@lsv-vm107 4]$ ansible-playbook playbook.yml -e '{foo: { bar: { important_key: "blah" }}}' 
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [print] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "bar": {
            "important_key": "blah"
        }
    }
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

[vmindru@lsv-vm107 4]$ 
```

**Comment by rhino5oh** [comment]
Give this a shot, seems to work for me and does NOT replace the entire dictionary:

```
-e '{ "cluster_defaults_override":{ "kubectl_user":"ubuntu" } }'
```

In this example, `cluster_defaults_override` is the dictionary, `kubectl_user` is the key you want to change, and `ubuntu` is the value.

Seems very similar to previous examples, but the single/double quotes are swapped
