### ISSUE TITLE
fireball daemon dies on spurious junk sent to it

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#1182]
Fireball started up on node, all ok.

Use `fireball_sender.py` to send any old packet to it, results in

```
Oct  1 17:53:04 a1 ansible-fireball: exception caught, exiting fireball mode: Invalid ciphertext signature
```

That is _very_ dangerous.

**Comment by mpdehaan** [comment]
Am aware told you it was prototypical -- in plan to fix prior to release RSN

-- Michael

**Comment by jpmens** [comment]
I meant this as a reminder only. Didn't mean to sound the way I probbly did, sorry.

**Comment by mpdehaan** [comment]
Np just did not want anyone to think it was an oversight.  All good

-- Michael

**Comment by mpdehaan** [comment]
merging with #1107, already in there IIRC
