### ISSUE TITLE
DigitalOcean Dynamic Inventory: support private_ip 

### ISSUE THREAD

**Issue by marcosgm** [ansible/ansible#11830]
When using private_networking, the API reports "ip_address": "10.132.156.108", and the Ansible Inventory gets the private IP instead of the public one, which is useless. We actually need to look for the public IP inside the networks list
            "networks": {
               "v4": [
                  {
                    "gateway": "10.132.0.1",
                    "ip_address": "10.132.156.108",
                    "netmask": "255.255.0.0",
                    "type": "private"
                  },
                  {
                    "gateway": "45.55.64.1",
                    "ip_address": "45.55.85.125",
                    "netmask": "255.255.224.0",
                    "type": "public"
                  }
                ],
We detect the feature here:
                 "features": [
                   "private_networking",
                   "virtio"],

**Comment by jimi-c** [comment]
The above commit was merged, so closing this.

Thanks!
