### ISSUE TITLE
chroot plugin: "ImportError: No module named callbacks"

### ISSUE THREAD

**Issue by rlott** [ansible/ansible#11861]
My setup (I build a deb package from the source 'devel' branch using 'make deb'): 

```
~/git/stash/rl-ansible-dcs-rootfs# ansible-playbook --version
ansible-playbook 2.0.0
  config file = /home/etdev/.ansible.cfg
  configured module search path = None
~/git/stash/rl-ansible-dcs-rootfs# dpkg -l | grep ansible
ii  ansible                               2.0.0-0.git201508051552.fad4486.devel~unstable all          A radically simple IT automation platform
```

I'm getting the following error when I run a simple shell task within the chroot plugin environment: 

```
TASK [include] ******************************************************************
included: tasks/install-packages.yml for build/rootfs

TASK [Create package listing] ***************************************************
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/executor/process/worker.py", line 118, in run
    executor_result = TaskExecutor(host, task, job_vars, new_play_context, self._new_stdin, self._loader, shared_loader_obj).run()
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 117, in run
    res = self._execute()
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 277, in _execute
    self._connection = self._get_connection(variables)
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 452, in _get_connection
    connection = connection_loader.get(conn_type, self._play_context, self._new_stdin)
  File "/usr/lib/pymodules/python2.7/ansible/plugins/__init__.py", line 287, in get
    self._module_cache[path] = imp.load_source('.'.join([self.package, name]), path)
  File "/usr/lib/pymodules/python2.7/ansible/plugins/connections/chroot.py", line 30, in <module>
    from ansible.callbacks import vvv
ImportError: No module named callbacks

fatal: [build/rootfs]: FAILED! => {"failed": true, "stdout": ""}
```

In examining the source code in GitHub, line 30 does show that it is trying to import callbacks:

```
from ansible.callbacks import vvv
```

In my git checkout, there doesn't appear to be any file corresponding to this (i.e. nothing in the v2 directory: 

```
~/git/github/ansible$ find . -type f -name 'callbacks*'
./v1/ansible/callbacks.py
```

I also searched the GitHub repository online and didn't find anything corresponding to v2. 

Should there be a v2/ansible/callbacks.py or should the offending line be removed?

**Comment by bcoca** [comment]
chroot plugin is still not working with v2.

**Comment by rlott** [comment]
Ah, I see. So, is version 1.9.2 the recommended version?

**Comment by bcoca** [comment]
1.9.2 is the current stable

**Comment by rlott** [comment]
So, if I wanted to use the chroot plugin, what version/tag would you recommend?

**Comment by abadger** [comment]
Checkout the stable-1.9 branch

**Comment by jimi-c** [comment]
@rlott we've pushed up some fixes for the chroot connection to port it to the v2 base, so you should be able to test it now. I've done some limited testing, and it appears to work:

<pre>
# cat inv 
[chroots]
/root/testing/11861/ch1
#/root/testing/11861/ch2
#/root/testing/11861/ch3
# cat test.yml 
- hosts: chroots
  gather_facts: no
  connection: chroot
  tasks:
  - ping:
  - command: pwd
# ansible-playbook -i inv test.yml -vv
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY ***************************************************************************
TASK [ping] ********************************************************************
ok: [/root/testing/11861/ch1] => {"changed": false, "ping": "pong"}
TASK [command] *****************************************************************
changed: [/root/testing/11861/ch1] => {"changed": true, "cmd": ["pwd"], "delta": "0:00:01.003358", "end": "2015-08-26 20:39:16.552802", "rc": 0, "start": "2015-08-26 20:39:15.549444", "stderr": "", "stdout": "/", "stdout_lines": ["/"], "warnings": []}
PLAY RECAP *********************************************************************
/root/testing/11861/ch1    : ok=2    changed=1    unreachable=0    failed=0   
</pre>

**Comment by jimi-c** [comment]
Since the above is working for me, and there's been no feedback, I'll go ahead and close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by rlott** [comment]
Thanks, all. Sorry I haven't been able to respond or to test the new changes. I've been swamped at work. If I see any problems in future, I'll follow jimi-c's instructions above.
