### ISSUE TITLE
extra_vars don't override variable in delegate_to

### ISSUE THREAD

**Issue by hkariti** [ansible/ansible#11860]
##### Issue Type:

  Bug Report
##### Ansible Version:

ansible 1.9.2 (detached HEAD f974ff6972) last updated 2015/08/05 17:42:07 (GMT +300)
##### Ansible Configuration:

default
##### Environment:

mac os, ubuntu
##### Summary:

When using a variable in `delegate_to`, the variable isn't overridden when passing `-e`. Only the instance of the variable in `delegate_to` isn't overridden.
##### Steps To Reproduce:

playbook:

```

---
- hosts: localhost
  vars:
   variable: default
  gather_facts: no
  tasks:
    - debug: message=hi
      delegate_to: "{{variable}}"
```

command:

```
ansible-playbook delegate_to.yml -e variable=new
```
##### Expected Results:

```
TASK: [debug msg=asd] *********************************************************
ok: [localhost -> new] => {
    "msg": "hi"
}
```
##### Actual Results:

```
TASK: [debug msg=asd] *********************************************************
ok: [localhost -> default] => {
    "msg": "hi"
}
```

**Comment by bcoca** [comment]
closing as this now works in devel and 2.0.1 as expected
