### ISSUE TITLE
Hide warning when using rsync locally

### ISSUE THREAD

**Issue by warrenseine** [ansible/ansible#11873]
Hi,

`Consider using synchronize module rather than running rsync`

I often see this informative warning telling me to prefer the `synchronize` module over the `shell` module when using `rsync`.

However, `synchronize` is not equivalent to `rsync` when copying local directories on the remote host (to be clear: _from_  the remote host _to_ the remote host). I'm basically using it as `cp` with fine-grained controls. Specifically, `rsync` allows idempotent behavior with the `-i` flag listing the changes made between directories.

Here's an example:

```
shell: rsync -azri --no-owner --no-group foo bar/
register: result
changed_when: result.stdout
```

Would it make sense to hide the warning in that case? Or better, support local copy inside the `synchronize` module (which AFAIK is a wrapper around `rsync`)?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by abadger** [comment]
I don't know if I would tell people using rsync to use synchronize instead
either (synchronize is just too limited) however I'm not sure if your use
case can't be handled by synchronize.

Does this do what you want?

```
- synchronize:
    dest: /var/tmp/destination
    src: /var/tmp/src
  delegate_to: "{{ inventory_hostname }}"
```
