### ISSUE TITLE
Add Solaris password handling to user module

### ISSUE THREAD

**Issue by rawiriblundell** [ansible/ansible#1188]
Hi there,
the user module works for the most part when adding a user to Solaris nodes, however it does not work correctly with passwords.

My python skills are basically non-existent, but I'm guessing the issue lies here (first example of this code, it reoccurs later on):

```
 77         elif key == 'password' and kwargs[key] is not None:
 78             cmd.append('-p')
 79             cmd.append(kwargs[key])
```

i.e. use the -p feature of (GNU) useradd/usermod/etc.  Unfortunately on Solaris, -p is for "project name", so trying to set a user password with i.e. name=newuser password=Welcome1 we get the hilarious response:

```
"msg": "UX: /usr/sbin/usermod: ERROR: project Welcome1 does not exist.  
 Choose another.\nUX: /usr/sbin/usermod: Welcome1 name should be all
 lower case or numeric.\n",
```

The usual way to bulk script password changes for Solaris is with expect, cssh or pssh, which is what I'm trying to get away from, and instead use ansible.

The other way is to work with the shadowfile directly.  There's a few ways to achieve this with ansible already, (e.g. raw module + sed, lineinfile module) but that lacks appropriate file locking (unless you playbook a sequence I guess), and the user module should look after this anyway IMHO.

Solaris defaults to simple crypt passwords with a 2-char salt e.g.

```
python -c 'import crypt; print crypt.crypt("Welcome1","DC")'
DC5qa4BDdc6jI
```

If you manually vi that into /etc/shadow, "newuser" can now login with the password "Welcome1".

However, beware that Sol 9 onwards allows md5 encryption on passwords, the way to check being something like:

```
grep "CRYPT_DEFAULT=" /etc/security/policy.conf | grep -v "#"
CRYPT_DEFAULT=__unix__
```

In this instance, __unix__ is returned, which means plain old crypt.

As it stands, the user module creates the user and a shadow entry appears like so:

Sol8:

```
newuser:*LK*:::::::
```

Sol10:

```
newuser:UP:::::::
```

Ideally it would look more like (using DC for the password salt, obviously you want to randomise)

```
newuser:DC5qa4BDdc6jI:0::::::
```

Other nice-to-haves (possibly another issue ticket) would be user locking, unlocking and expiry to force a password change at next login.  This would possibly use state=locked, state=unlocked and state=expired respectively.

passwd -l  for locking appears to exist in most versions of passwd
passwd -u for unlocking appears in some versions
passwd -d appears to be the alternative to unlocking
passwd -f exists in a couple of versions of passwd for forcing a password change
chage -d 0 appears to be the Linux alternative for the above

Again, yes, all of these can be done with the raw module, but it would still be preferable to have the user module handle it IMHO.  If this does get to be too hard though, maybe it would be easiest to split the user module off into OS specific modules e.g. user-linux, user-sunos, user-hpux and so on.

Hope that braindump wasn't too messy to follow.  I'm looking forward to the discussion.

**Comment by mpdehaan** [comment]
Seeing I'm _not_ a Solaris user, leaving this feature request open isn't going to pick up much traction.  

You're going to need to send me a pull request or get someone to build this for you.

Perhaps try IRC or the mailing list to recruit a Solaris user, though if your Python skills are mostly nonexistant, maybe now is a great time!

Solaris support in the user module would be nice, I agree.
