### ISSUE TITLE
template module creates backups as owner root

### ISSUE THREAD

**Issue by erriapo** [ansible/ansible#11886]
I have a task that runs a template with **sudo**=Yes and **backup**=Yes. The owner and group is set to an account `gb` with a lower privilege than root. The templated file that is uploaded has the owner set to `gb`. But the backups are owned by`root`.

I would like the ability to configure the template module to changed the owner/group of the backup files to be the same as uid/gid specified.

E.g.

```
- name: Copy foo.config
  template: src=foo.config dest=/data5/foo.config owner=gb group=gb mode=0644 backup=Yes
  ignore_errors: True
  sudo: Yes
```

**Comment by angystardust** [comment]
I'm interested in this as well!

**Comment by bcoca** [comment]
this was fixed a while back when the backup was changed to 'copy with permissions'.
