### ISSUE TITLE
Ansible Truck Factor

### ISSUE THREAD

**Issue by gavelino** [ansible/ansible#11897]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Ansible** and obtained a value of **2**.

The developers responsible for this TF are:

James Cammarata - author of 54% of the files
Michael DeHaan - author of 25% of the files

To validate our results, we would like to ask **Ansible** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Ansible**?

(b) Do you agree that **Ansible** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Ansible** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by sivel** [comment]
I'd recommend reaching out to those individuals directly instead of creating a github issue.  As such, I'm going to close this since it isn't really an issue, and we use github issues for actually tracking problems and not questions.

**Comment by robynbergeron** [comment]
@gavelino - Feel free to send me an email, I'm happy to chat with you about finding a way to share your questions outside of GitHub.

In the meantime: thanks for your efforts around metrics and the health of open source projects in general - it's work that is valuable to everyone in the land of open source communities. Cheers!

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
