### ISSUE TITLE
Update hashing algorithms 

### ISSUE THREAD

**Issue by frite** [ansible/ansible#11904]
Hello,
I was playing with Ansible and in the hashing.py file (found in the utils folder) I found that SHA-1 and MD5 are being used. As such, I suggest updating the file (I can do it with a pull req) to either SHA-256 (or more) and as a fallback SHA-1.
Regards

**Comment by abadger** [comment]
This won't work. That function needs to have an algorithm that's available
on the clients.  Sha1 is the only such algorithm.  Md5 isn't available on
fips systems. Sha256 isn't available on systems that don't have hashlib.

You might be able to find places that this function is used and propose
chances to those functions to use a different hash algorithm or one that is
configurable (we just took a pr to deprecate the sha256 checksum parameter
in get_url in favour of a generic checksum param that includes the hash
algorithm requested.)
