### ISSUE TITLE
boto profile not being used by ec2_vpc

### ISSUE THREAD

**Issue by glnds** [ansible/ansible#11919]
Issue Type: Bug Report

Ansible Version:  1.9.2

boto version: 2.38.0

Ansible Configuration: nothing special

Environment: OX 10.10.4

**Summary:**

ec2 module is running fine with the usage of **profile** and **region**. 
ec2_vpc however gives an authentication error with the same values specified for **profile** and **region**

If i manually set the variables

```
export AWS_ACCESS_KEY_ID=...
export AWS_SECRET_ACCESS_KEY=...
export AWS_REGION=...
```

and re-run the playbook it runs fine....

**Steps To Reproduce:**

playbook:

```
# vim:ft=ansible:

---
- name: define a vpc
  hosts: localhost
  gather_facts: False
  tasks:
  - name: setup a vpc
    ec2_vpc:
      state: present
      cidr_block: 177.1.0.0/16
      resource_tags: { "Environment":"Development" }
      region: eu-west-1
      profile: a-boto-profile
```

**Expected Results:**

```
PLAY [define a vpc] ***********************************************************

TASK: [setup a vpc] ***********************************************************
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/glnd/.ansible/tmp/ansible-tmp-1439277437.74-229076630158256/ec2_vpc", line 2436, in <module>
    main()
  File "/Users/glnd/.ansible/tmp/ansible-tmp-1439277437.74-229076630158256/ec2_vpc", line 624, in main
    (vpc_dict, new_vpc_id, subnets_changed, changed) = create_vpc(module, vpc_conn)
  File "/Users/glnd/.ansible/tmp/ansible-tmp-1439277437.74-229076630158256/ec2_vpc", line 511, in create_vpc
    for idx, val in enumerate(subnets):
TypeError: 'NoneType' object is not iterable


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
```

Yeah i know i get an error as well but you get the point ;)

My full playbook using ec2_vpc is working fine if the environment variables are set, this is more or less a copy from the [documentation](http://docs.ansible.com/ansible/ec2_vpc_module.html)

**Actual Results**:

```
failed: [localhost] => {"failed": true}
msg: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials

FATAL: all hosts have already failed -- aborting
```

**Comment by snakelab** [comment]
Same behaviour here. I am using ec2.ini with "boto_profile = prod" and it works perfect while executing "ec2.py --list" but not with "ansible-playbook ....".

Then i got the same error message:
"No handler was ready to authenticate. 1 handlers were checked. ['QuerySignatureV2AuthHandler'] Check your credentials"

**Comment by slavkad** [comment]
I am seeing similar behavior (on 1.9.5)

I am trying to use sts to generate temp keys.
tried several ways to get them into the play.

via environment
via properties to the ec2_vpc 
they were being ignored.

finally 

I just created a user in aws.. generated api keys.. and used those.. added them to ec2_vpc and was able to create the vpc.

error I was getting was
`failed: [localhost -> 127.0.0.1] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/some_user/.ansible/tmp/ansible-tmp-1460754725.27-238323442000004/ec2_vpc", line 2470, in <module>
    main()
  File "/Users/some_user/.ansible/tmp/ansible-tmp-1460754725.27-238323442000004/ec2_vpc", line 625, in main
    (vpc_dict, new_vpc_id, subnets_changed, changed) = create_vpc(module, vpc_conn)
  File "/Users/some_user/.ansible/tmp/ansible-tmp-1460754725.27-238323442000004/ec2_vpc", line 276, in create_vpc
    previous_vpc = find_vpc(module, vpc_conn, id, cidr_block)
  File "/Users/some_user/.ansible/tmp/ansible-tmp-1460754725.27-238323442000004/ec2_vpc", line 230, in find_vpc
    previous_vpcs = vpc_conn.get_all_vpcs(None, {'cidr': cidr, 'state': 'available'})
  File "/Library/Python/2.7/site-packages/boto/vpc/**init**.py", line 111, in get_all_vpcs
    return self.get_list('DescribeVpcs', params, [('item', VPC)])
  File "/Library/Python/2.7/site-packages/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 401 Unauthorized
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>8c2e2ed7-5c5f-4409-bd73-de407a903c9d</RequestID></Response>

FATAL: all hosts have already failed -- aborting`

i am finding that overall how aws creds are getting utilized in ec2 modules is not consistent

**Comment by szinck** [comment]
This appears to be in 2.1.1.0 as well

**Comment by s-hertel** [comment]
Closing because ec2_vpc is deprecated in 2.3 and won't be fixed. Use ec2_vpc_net along with supporting modules including ec2_vpc_igw, ec2_vpc_route_table, ec2_vpc_subnet, ec2_vpc_dhcp_options, ec2_vpc_nat_gateway, ec2_vpc_nacl.
