### ISSUE TITLE
"No Kerberos credentials available" when connecting to Windows domain account

### ISSUE THREAD

**Issue by bleloch** [ansible/ansible#11924]
Issue Type:

Ansible Version:

ansible 1.9.2

Ansible Configuration:

Vanilla configuration (new build)

Environment:

CentOS 7.1

Summary:

I'm currently trying to test connectivity to a Windows host from my control machine - I'm running the standard "ansible windows -m win_ping" and when I use a local account to auth, it works fine. However, when I auth with a domain account, I get the following error:

ie-aws-dv-mo-01.earth.my-domain.com | FAILED => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/**init**.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 964, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file, delegate_host)
  File "/usr/lib/python2.7/site-packages/ansible/runner/connection.py", line 52, in connect
    self.active = conn.connect()
  File "/usr/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 140, in connect
    self.protocol = self._winrm_connect()
  File "/usr/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 96, in _winrm_connect
    protocol.send_message('')
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 190, in send_message
    return self.transport.send_message(message)
  File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 219, in send_message
    krb_ticket = KerberosTicket(self.krb_service)
  File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 166, in __init__
    kerberos.authGSSClientStep(krb_context, '')
GSSError: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('No Kerberos credentials available', -1765328243))

Steps To Reproduce:

1) Follow standard Windows setup instructions - http://docs.ansible.com/ansible/intro_windows.html (note - I also had to install krb5-devel & python-devel in order for pip install kerberos to work)

2) Add Windows server you wish to test ping into group_vars/windows.yml, including known local admin account. Test with "ansible windows -m win_ping" and observe results

3) Reconfigure windows.yml, using a known domain admin account (syntax I am using is <username>@<domain>), test with "ansible windows -m win_ping" and observe results

Expected Results:

Both steps 2 and 3 should return a successful pong, i.e.

ie-aws-dv-mo-01.earth.my-domain.com | success >> {
    "changed": false,
    "ping": "pong"
}

Actual Results:

Step 2 works successfully

Step 3 throws the stacktrace provided in the summary.

**Comment by jhawkesworth** [comment]
I think you may need to configure your ansible controller to be a kerberos client, so that it knows how to communicate with your windows domain controllers.  Have you configured /etc/krb5.conf and entered at the least the name of your domain and primary and secondary domain controllers?

If you have configured /etc/krb5.conf then try logging in to the domain manually as follows

kinit your_domain_user@YOUR.FULLY.QUALIFIED.DOMAIN.COM

(note the bit after @ has to be in upper case as kerberos is case sensitive, unlike most of windows).

Please let us know how you get on.

Jon

**Comment by bleloch** [comment]
Thanks for the reply Jon - this did indeed fix the problem. I'll close the issue now.

Thanks again

Leo
