### ISSUE TITLE
registered variables not spanning multiple hosts

### ISSUE THREAD

**Issue by cfrazee-janrain** [ansible/ansible#11933]
```
 - name: find hostname of riak server number 0
 shell: echo '{{ inventory_hostname }}' >/tmp/stuff.log 2>&1
 register: riak_primary_host
 when: '"-0." in inventory_hostname'

- name: cluster the node if I am not riak host 0 and host 0 is not in ring members
shell: echo '{{ riak_primary_host.stdout }}' >/tmp/stuff.log
#    shell: riak-admin cluster join riak@{{ riak_primary_host }}'
when: '"-0." not in inventory_hostname and "-0." not in ring_members'
```

The "when" statements work fine, and as you can see below the inventory_hostname is defined 

```
root@riak-ec2-storage:/tmp# cat stuff.log
riak-ec2-storage-0.multi.prod.sp.domain_name_extracted.com
```

However when other network nodes try to access the object "riak_primary_host.stdout"  I get the below error:

```
fatal: [riak-ec2-storage-1.multi.prod.sp.domain_name_extracted.com] => One or more undefined
variables: 'dict object' has no attribute 'stdout'
```

I have tried various other forms such as "riak_primary_host.0.stdout" and  riak_primary_host.[0].stdout", both which complain that the element is not defined.

Any suggestions, as I am grasping at straws at this point of how to make a variable from inventory_hostname that is preserved and accessible by all hosts, irregardless of the host accessing it.

Thanks ahead of time! :-)

**Comment by sivel** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
