### ISSUE TITLE
[devel] Python Interpreter not taken in account for template checksum

### ISSUE THREAD

**Issue by Xowap** [ansible/ansible#11968]
**Issue Type**: Bug Report

**Ansible Version**
Latest version of `devel`

**Ansible Configuration**

```
[defaults]
remote_user = core

[ssh_connection]
ssh_args = -o StrictHostKeyChecking=no
pipelining = True
```

Also `ansible_python_interpreter` is set to `/home/core/bin/python` on the relevant servers.

I ran the same tests with `pipelining` to False as well.

**Environment**
I try to send a template to my CoreOS servers. They have no Python by default, so the interpreter is manually installed in `/home/core/bin/python`.

**Summary**
Trying to use the `template` action will result in an error 4, which is "No python interpreter".

**Steps to reproduce**
On a server bootstraped with the `defunctzombie.coreos-bootstrap` playbook, try to send a template.

``` yml
- name: generate cloud config
  template: src=cloud-config.yml dest=/home/core/cloud-config.yml
  register: cloud_config_update
```

**Expected results**
The file generated by template should be uploaded to the remote server. This is what happens in `1.9`.

**Actual results**

```
<myhost.mydomain.com> ESTABLISH SSH CONNECTION FOR USER: core
<myhost.mydomain.com> EXEC ssh -C -tt -q -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=core -o ConnectTimeout=10 myhost.mydomain.com (umask 22 && mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1439633685.62-228244614437096" && echo "$HOME/.ansible/tmp/ansible-tmp-1439633685.62-228244614437096")                                                                                                     
<myhost.mydomain.com> ESTABLISH SSH CONNECTION FOR USER: core
<myhost.mydomain.com> EXEC ssh -C -tt -q -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=core -o ConnectTimeout=10 myhost.mydomain.com rc=flag; [ -r /home/core/cloud-config.yml ] || rc=2; [ -f /home/core/cloud-config.yml ] || rc=1; [ -d /home/core/cloud-config.yml ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/home/core/cloud-config.yml && exit 0; (python -c 'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1();
afile = open("'/home/core/cloud-config.yml'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
        hasher.update(buf)
        buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())' 2>/dev/null) || (python -c 'import sha; BLOCKSIZE = 65536; hasher = sha.sha();
afile = open("'/home/core/cloud-config.yml'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
        hasher.update(buf)
        buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())' 2>/dev/null) || (echo '0  '/home/core/cloud-config.yml)
fatal: [myhost.mydomain.com]: FAILED! => {"changed": false, "failed": true, "msg": "failed to checksum remote file. Checksum error code: 4"}
```

As you can see, it seems that the Python interpreter is simply `python` and not the one specified in `ansible_python_interpreter`. This results in an error code `4`. The value for the servers in question is `/home/core/bin/python`.

**Comment by Xowap** [comment]
I guess the issue can be pinpointed to here: https://github.com/ansible/ansible/commit/62d79568be16084718bda2d890b2b4e1d10cc41d#diff-b5da923916c47f1f7a18dfcbfc84b260R244

**Comment by abadger** [comment]
The commit you point to is for v2 (which eventually migrated to what's currently in the devel branch).  1.9 wouldn't have that code.

**Comment by Xowap** [comment]
@abadger indeed, I'm running on `devel`, it works fine in `1.9`

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by Xowap** [comment]
@jimi-c excellent, this works. Thanks :)
