### ISSUE TITLE
[1.9.2] Ansible gets confused and converts " to '

### ISSUE THREAD

**Issue by hrstoyanov** [ansible/ansible#11963]
The issues is  described in this stakoverflow thread, along with a temp workaround:
http://stackoverflow.com/questions/31969872/why-ansible-always-replaces-double-quotes-with-single-quotes-in-templates/32014283

**Comment by bcoca** [comment]
This is a result of the jinja2 templating and trying to establish a type, seeing the [ ] makes it look like jinja2 returned a list, then when you stringify it again for output the default quoting (single) is added.

**Comment by bcoca** [comment]
to output exactly the same as you defined in the file:
`value: '["/usr/bin/runit", "{{somevar}}"]'`

I see 2 workarounds:
1. as in so comment,  in the definition precede with space:
   `value: ' ["/usr/bin/runit", "{{somevar}}"]'`
2. or use json filter in output
   `{{value|to_json}}`
   which results in the quotes you wanted but w/o the leading space.

**Comment by hrstoyanov** [comment]
Thanks Brian,
I tried  t_o_json_, and it did not work for other reasons. Only 1. works.
Wanted to bring this to the attention of the Ansible team. It was pretty
nasty to me, since I spent quite a bit of time with this issue before
asking for help.

On Fri, Aug 14, 2015 at 7:55 PM, Brian Coca notifications@github.com
wrote:

> to output exactly the same as you defined in the file:
> value: '["/usr/bin/runit", "{{somevar}}"]'
> 
> I see 2 workarounds:
> 
>    1.
> 
>    as in so comment, in the definition precede with space:
>    value: ' ["/usr/bin/runit", "{{somevar}}"]'
>    2.
> 
>    or use json filter in output
>    {{value|to_json}}
>    which results in the quotes you wanted but w/o the leading space.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible/issues/11963#issuecomment-131282088.

## 

/ Hristo Stoyanov

**Comment by bcoca** [comment]
what does 'not work' mean? i tested with a docker file and the to_json worked to produce the exact output needed.

**Comment by hrstoyanov** [comment]
Can you please add your code as an answer to the stackoverflow question? Thanks

**Comment by bcoca** [comment]
I don't use SO, but posting here:
play.yml

```
- hosts: localhost
  gather_facts: false
  vars:
    somevar: tweety
    value1: '["/usr/bin/runit", "{{somevar}}"]'
    value2: ' ["/usr/bin/runit", "{{somevar}}"]'
  tasks:
   - template: src=test.j2 dest=/tmp/test
```

test.j2:

```
CMD {{value1}}
CMD {{value2}}
CMD {{value1|to_json}}
```

results in /tmp/test:

```
CMD ['/usr/bin/runit', 'tweety']
CMD  ["/usr/bin/runit", "tweety"]
CMD ["/usr/bin/runit", "tweety"]
```

**Comment by bcoca** [comment]
closing as to_json should fixes this as does the previous workaround
