### ISSUE TITLE
TypeError: 'NoneType' object is not iterable when a host is not reachable with strategy free

### ISSUE THREAD

**Issue by Hoshpak** [ansible/ansible#11965]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.0.0 (devel 4fc905b1d5) last updated 2015/08/14 22:36:03 (GMT +200)
  lib/ansible/modules/core: (detached HEAD dea5f5d15e) last updated 2015/08/14 22:36:07 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 210ee3febc) last updated 2015/08/14 22:36:11 (GMT +200)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/08/14 22:36:14 (GMT +200)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/08/14 22:36:17 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
##### Ansible Configuration:

$ source hacking/env-setup
##### Environment:

Debian jessie amd64

$ python -v 
Python 2.7.9

$ pip freeze
Cheetah==2.4.4
IPy==0.81
Jinja2==2.7.3
M2Crypto==0.21.1
MarkupSafe==0.23
Pillow==2.6.1
PyYAML==3.11
Pygments==2.0.1
SOAPpy==0.12.22
Sphinx==1.2.3
ansible==2.0.0
argparse==1.2.1
astroid==1.3.7
chardet==2.3.0
colorama==0.3.2
configobj==5.0.6
croniter==0.3.4
defusedxml==0.4.1
docutils==0.12
ecdsa==0.11
feedparser==5.1.3
html5lib==0.999
httplib2==0.9
logilab-common==1.0.2
lxml==3.4.2
meld==3.12.1
msgpack-python==0.4.2
numpy==1.8.2
paramiko==1.15.1
pep8==1.5.7
pycrypto==2.6.1
pygobject==3.14.0
pylint==1.4.4
python-apt==0.9.3.11
python-dateutil==2.2
python-debian==0.1.27
python-debianbts==1.11
pytz==2012c
pyzmq==14.4.0
reportbug==6.6.3
reportlab==3.1.8
requests==2.4.3
roman==2.0.0
salt==2015.5.3
six==1.8.0
smbus==1.1
urllib3==1.9.1
vboxapi==1.0
wsgiref==0.1.2
wstools==0.4.3
wxPython==3.0.1.1
wxPython-common==3.0.1.1
##### Summary:

When a host is unreachable, ansible-playbook throws an "TypeError: 'NoneType' object is not iterable" if "strategy: free" is selected in the playbook.
##### Steps To Reproduce:
1. Clone the ansible git repository and run "source hacking/env-setup". 
2. Create several VMs with ssh configured. Write their IP addresses into an inventory file
3. Create a playbook with "strategy: free" and several plays (I just used "shell: echo Test" to test this)
4. Run the playbook to test if it works properly: "ansible-playbook -vvv -u root -i inventory test-playbook.yml"
5. Shut down one or more of the VMs so they are no longer reachable
6. Run the playbook again

Once the host which is not reachable is reached, ansible-playbook stops execution and throws the exception.
##### Expected Results:

I expected that a fatal error would be reported like it happens with other strategy plugins (e.g. linear) but the playbook run would finish even if one or more hosts are down.
##### Actual Results:

```
fatal: [192.168.178.97]: FAILED! => {"failed": true, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which  will enable SSH debugging output to help diagnose the issue"}
Unexpected Exception: 'NoneType' object is not iterable
the full traceback was:

Traceback (most recent call last):
  File "/tmp/ansible/ansible/bin/ansible-playbook", line 79, in <module>
    sys.exit(cli.run())
  File "/tmp/ansible/ansible/lib/ansible/cli/playbook.py", line 135, in run
    results = pbex.run()
  File "/tmp/ansible/ansible/lib/ansible/executor/playbook_executor.py", line 141, in run
    result = self._tqm.run(play=play)
  File "/tmp/ansible/ansible/lib/ansible/executor/task_queue_manager.py", line 192, in run
    return strategy.run(iterator, play_context)
  File "/tmp/ansible/ansible/lib/ansible/plugins/strategies/free.py", line 77, in run
    (state, task) = iterator.get_next_task_for_host(host, peek=True)
TypeError: 'NoneType' object is not iterable
```

**Comment by bcoca** [comment]
so i can confirm this happens when there is more than 1 play, if it is only 1 play everything works normally (hosts fail but play then reports this).

**Comment by bcoca** [comment]
Playing around it a bit more, it only happens in the first play is 'free', the strategy of the 2nd play does not matter.
