### ISSUE TITLE
Compatibility with Openbsd "doas"

### ISSUE THREAD

**Issue by yannh** [ansible/ansible#11972]
Hello, I am currently playing with ansible on OpenBSD 5.8 (to be released later this year). I am having issues with privileges escalation, as OpenBSD 5.8 has replaced "sudo" with "doas", cf: 

http://www.tedunangst.com/flak/post/doas
http://www.openbsd.org/58.html

I have tried setting this in my config file: 

```
sudo_exe=/usr/bin/doas
sudo_flags=
```

But I think ansible still pass more parameters to sudo than just "-u", and therefore I get the following error:

```
doas: unknown option -- k
usage: doas [-ns] [-C config] [-u user] command [args]
```

Am I missing something? If not, It would be very helpful to be able to use "doas" as a replacement for "sudo" in ansible!

Thanks!

**Comment by yannh** [comment]
I just gave this a quick shot, turns out it won't be as easy to implement as I had hoped. Doas does not allow to set environment variables before running an actual command:

bash-4.3# doas "ls"
bash-4.3# doas "LANG=en_US.UTF-8 ls"
doas: LANG=en_US.UTF-8 ls: command not found

And this is massively used by ansible.

**Comment by yannh** [comment]
@mutemule this is awesome, thank you very much! I didn't know you could pass environment variables to doas using the env keyword. 

[Edit]: ok, I get the trick now.

**Comment by mutemule** [comment]
@yannh Yeah, it's functional, but it's not ideal. It would be nice if ansible passed along the environment variables and the commands to run as distinct variables, so environment variables could be handled appropriately.

However, given the constraints we have, this does work.

**Comment by sysfu** [comment]
Are there any plans to backport this to Ansible 1.9.4? Or do we have to upgrade to v2 to get doas support for OpenBSD?
