### ISSUE TITLE
with_sequence skips if start and end are equal

### ISSUE THREAD

**Issue by mrebbert** [ansible/ansible#11979]
$ ansible --version
ansible 1.9.2

Actually, a task with with_sequence skips, if the set start and end would be equal. I would expect that the task would run once.

Example:

Given: 
instance_count.stdout: the actual count of running container.
instances: the number of container, which should run.

```
- name: create the defined docker instance with cli.
  command: "docker -H \"{{ docker_host }}\" run \
                  -d \
                  --name \"{{ item }}\" \
                  ...
                  \"{{ docker_registry_server }}/{{ container_image }}:{{ docker_image_tag }}\""
  when: instance_count.stdout|int+1 <= instances|int
  with_sequence: start={{instance_count.stdout|int+1}} end={{instances|int}} format={{container_image}}-%02x
```

So, if i got two container running (which means instance_count.stdout|int+1==3) and i want to increase the count up to three container (instances==3) i would expect that ths task would run once. 
Otherwise, if i set instances=4 it would run the task two times (and i got two container more).

From my point of view this could not be handled similar to the count of 0.

BTW: I know that there's a docker module, but it seems that it's too fragile at the moment.

Best,
Markus

**Comment by bcoca** [comment]
count=0 also gets skipped.

```
- hosts: localhost
  gather_facts: False
  tasks:
    - name: test with_sequence not failing on count == 0
      debug: msg='previously failed with backward counting error'
      with_sequence: count=0
```

results in 

```
PLAY ***************************************************************************

TASK [test with_sequence not failing on count == 0] ****************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0   
```

**Comment by mrebbert** [comment]
As i said, i don't think it has to be the same behavior, when i use start and end.
How should i implement only one (1x) iteration?

```
with_sequence: start=1 end=1
```

results in 0 iterations.

```
with_sequence: start=1 end=2
```

results in two iterations.

If start and end are the same it must not have to skip.

**Comment by bcoca** [comment]
point taken, not sure why that is happening, but it seems that in the first case the count should be 1

**Comment by mrebbert** [comment]
+1

Thx!

**Comment by vaishnav-piyush** [comment]
+1

**Comment by bhadra9999** [comment]
Hi All,
Build ec2 instances with attaching multiple tags names :-
  For example- I have launched one ec2 instance with tag name "websever1" the next builds of ec2 instances should start with tag name webserver2 , webserver3 .... automatically.


Note: No two ec2 instances have same tag name. 

please help me
