### ISSUE TITLE
Unexpected Exception: 'NoneType' object has no attribute 'run_state' when a host is not reachable with strategy linear

### ISSUE THREAD

**Issue by Hoshpak** [ansible/ansible#11982]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.0.0 (devel 4068598c15) last updated 2015/08/17 19:12:58 (GMT +200)
  lib/ansible/modules/core: (detached HEAD dea5f5d15e) last updated 2015/08/17 19:13:02 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 210ee3febc) last updated 2015/08/17 19:13:06 (GMT +200)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/08/17 19:13:09 (GMT +200)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/08/17 19:13:13 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
##### Ansible Configuration:

$ source hacking/env-setup
##### Environment:

Debian jessie amd64

$ python -v
Python 2.7.9

$ pip freeze
Cheetah==2.4.4
IPy==0.81
Jinja2==2.7.3
M2Crypto==0.21.1
MarkupSafe==0.23
Pillow==2.6.1
PyYAML==3.11
Pygments==2.0.1
SOAPpy==0.12.22
Sphinx==1.2.3
ansible==2.0.0
argparse==1.2.1
astroid==1.3.7
chardet==2.3.0
colorama==0.3.2
configobj==5.0.6
croniter==0.3.4
defusedxml==0.4.1
docutils==0.12
ecdsa==0.11
feedparser==5.1.3
html5lib==0.999
httplib2==0.9
logilab-common==1.0.2
lxml==3.4.2
meld==3.12.1
msgpack-python==0.4.2
numpy==1.8.2
paramiko==1.15.1
pep8==1.5.7
pycrypto==2.6.1
pygobject==3.14.0
pylint==1.4.4
python-apt==0.9.3.11
python-dateutil==2.2
python-debian==0.1.27
python-debianbts==1.11
pytz==2012c
pyzmq==14.4.0
reportbug==6.6.3
reportlab==3.1.8
requests==2.4.3
roman==2.0.0
salt==2015.5.3
six==1.8.0
smbus==1.1
urllib3==1.9.1
vboxapi==1.0
wsgiref==0.1.2
wstools==0.4.3
wxPython==3.0.1.1
wxPython-common==3.0.1.1
##### Summary:

When a host is unreachable, ansible-playbook throws an "AttributeError: 'NoneType' object has no attribute 'run_state'" if "strategy: linear" is selected in the playbook or none is selected explicitely.
##### Steps To Reproduce:
1. Clone the ansible git repository and run "source hacking/env-setup".
   1. Create several VMs with ssh configured. Write their IP addresses into an inventory file
   2. Create a playbook with "strategy: free" and several plays (I just used "shell: echo Test" to test this)
2. Run the playbook to test if it works properly: "ansible-playbook -vvv -u root -i inventory test-playbook.yml"
3. Shut down one or more of the VMs so they are no longer reachable
4. Run the playbook again

Once the host which is not reachable is reached, ansible-playbook stops execution and throws the exception.
##### Expected Results:

I expected that a fatal error would be reported like it happens with other ansible versions (tested with 1.9.1) but the playbook run would finish even if one or more hosts are down.
##### Actual Results:

```
Unexpected Exception: 'NoneType' object has no attribute 'run_state'
the full traceback was:

Traceback (most recent call last):
  File "/tmp/ansible-test/ansible/bin/ansible-playbook", line 79, in <module>
    sys.exit(cli.run())
  File "/tmp/ansible-test/ansible/lib/ansible/cli/playbook.py", line 135, in run
    results = pbex.run()
  File "/tmp/ansible-test/ansible/lib/ansible/executor/playbook_executor.py", line 141, in run
    result = self._tqm.run(play=play)
  File "/tmp/ansible-test/ansible/lib/ansible/executor/task_queue_manager.py", line 192, in run
   return strategy.run(iterator, play_context)
  File "/tmp/ansible-test/ansible/lib/ansible/plugins/strategies/linear.py", line 147, in run
    host_tasks = self._get_next_task_lockstep(hosts_left, iterator)
  File "/tmp/ansible-test/ansible/lib/ansible/plugins/strategies/linear.py", line 109, in _get_next_task_lockstep
    return _advance_selected_hosts(hosts, lowest_cur_block, PlayIterator.ITERATING_TASKS)
  File "/tmp/ansible-test/ansible/lib/ansible/plugins/strategies/linear.py", line 91, in _advance_selected_hosts
    if s.run_state == cur_state and s.cur_block == cur_block:
AttributeError: 'NoneType' object has no attribute 'run_state'
```

**Comment by Hoshpak** [comment]
I just had a look at the code of linear.py and believe that I found the reason for the exeception. "host_state_task" is assigned in line 87 and is a tuply which usuall contains an object of type ansible.executor.play_iterator.HostState and another if type ansible.playbook.task.Task. If a host is not reachable, the tuply will instead contain (None, None). Since the if-clause in line 88 checks if "host_state_task" is None, this will not match in this case. I tried to change the clause to check if host_state_task[0] is None and this way, no exeception will be thrown. I don't know what the proper way to fix this issue is though.

**Comment by bcoca** [comment]
try this patch:

```
diff --git a/lib/ansible/plugins/strategies/linear.py b/lib/ansible/plugins/strategies/linear.py
index dd24b8b..99623b5 100644
--- a/lib/ansible/plugins/strategies/linear.py
+++ b/lib/ansible/plugins/strategies/linear.py
@@ -88,6 +88,8 @@ class StrategyModule(StrategyBase):
                 if host_state_task is None:
                     continue
                 (s, t) = host_state_task
+                if t is None:
+                    continue
                 if s.run_state == cur_state and s.cur_block == cur_block:
                     new_t = iterator.get_next_task_for_host(host)
```
