### ISSUE TITLE
ansible play hangs on MacOSX

### ISSUE THREAD

**Issue by shirou** [ansible/ansible#11988]
### Ansible Version:

```
ansible-playbook 2.0.0
  config file = /Users/shirou/tmp/ansible/ansible.cfg
  configured module search path = None
```

installed from 7eaacaf66e070106035227ea4bd2a13a41691426
### Ansible Configuration:

nothing special.
### Environment:
- Mac OS X (yosemite)
- Python 2.7.9
### Summary:

ansible-playbook command hangs up after this error.

```
Traceback (most recent call last):
  File "/Users/shirou/Works/VEnvs/ansiblev2/lib/python2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/executor/process/result.py", line 103, in run
    result = self._read_worker_result()
  File "/Users/shirou/Works/VEnvs/ansiblev2/lib/python2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/executor/process/result.py", line 75, in _read_worker_result
    if rslt_q.qsize() > 0:
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 143, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError

PLAY ***************************************************************************

TASK [debug msg=hangs] *********************************************************
```

I thinks because `Queue.qsize()` is not implemented at Mac OS X.
see https://github.com/python/cpython/blob/829b49cbd2e4b1d573470da79ca844b730120f3d/Lib/multiprocessing/queues.py#L116
### Steps To Reproduce:

run any playbook like

```
- hosts: all
  gather_facts: no
  connection: local
  tasks:
    - debug: msg="hangs"
```
### Expected Results:

play runs.
### Actual Results:

It seems play hang up.

**Comment by bcoca** [comment]
@shirou please confirm that PR fixes the issue, I don't have OS X to test on

**Comment by shirou** [comment]
Thank you for quick fix! It works on my environment.

**Comment by bitmensch** [comment]
I just ran into the same issue on Mac OS X. I can verify that the PR fixes this.
