### ISSUE TITLE
Command-line flags (variable weight) not respected (bug or a feature?)

### ISSUE THREAD

**Issue by sirkubax** [ansible/ansible#11991]
When I have variable defined
    ansible_ssh_private_key_file=keyXXX

It has higher priority than command line flags:
ansible -m ping somehost -vvvvv --private-key=some_key

While it is working when running
ansible -m ping somehost -vvvvv  -e 'ansible_ssh_private_key_file=some_key'

I've looked into the application files:
    runner/init.py
Look's like here the 'private_key_file' get's overridden 
    actual_private_key_file = inject.get('ansible_ssh_private_key_file', self.private_key_file)

---

I'm not sure if that is a bug, or a feature.
I don't use '--private-key' option, but my colleague have pointed that out, so I did have a look at that behaviour.

Since 
'--private-key' -> private_key_file -> ansible_ssh_private_key_file
it should be in the same "class" as extra vars in my opinion

Based on 
http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
well, it does not say a word about command line flags (only -e variables)
Could we clarify that?

**Comment by amenonsen** [comment]
Per discussion with @jimi-c, this is a feature. It would make more sense if _all_ command-line flags overrode inventory settings, but «--extra-vars» is the only one for which this is actually true. For compatibility with 1.9, this behaviour is being retained in v2.

**Comment by bcoca** [comment]
So the rationale is that most command line flags will override the ansible.cfg and environment, but these are generic settings, per host settings override generic settings, -e lets you set per host settings in a global fashion that overrides everything else.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
