### ISSUE TITLE
local_action being run on target host instead of local machine

### ISSUE THREAD

**Issue by orderedchaosdev** [ansible/ansible#11998]
Issue Type:  Bug Report

Ansible Version: 
ansible 2.0.0 (devel 86100da3a0) last updated 2015/08/18 13:23:59 (GMT -700)
  lib/ansible/modules/core: (detached HEAD dea5f5d15e) last updated 2015/08/18 13:23:11 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 210ee3febc) last updated 2015/08/18 13:23:11 (GMT -700)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/08/18 13:23:11 (GMT -700)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/08/18 13:23:11 (GMT -700)

Ansible Configuration:

We define remote_user to be root
and transport to be ssh

Environment:  Centos 6.7

Summary:

When running 
from ansible 2.0.0. (devel 464a436f8f)
local_actions run on the local machine as they should

When running from:
ansible 2.0.0 (devel 86100da3a0) last updated 2015/08/18 13:23:59 (GMT -700)
  lib/ansible/modules/core: (detached HEAD dea5f5d15e) last updated 2015/08/18 13:23:11 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 210ee3febc) last updated 2015/08/18 13:23:11 (GMT -700)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/08/18 13:23:11 (GMT -700)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/08/18 13:23:11 (GMT -700)
They run on the inventory host machine even thought it is a local_action

Steps To Reproduce:

Run playbook

```

---

- hosts: sample-host
  tasks:
    - name: testing localaction
      local_action: shell hostname
      register: testingoutput
    - debug: var=testingoutput
```

Expected Results:
ansible 2.0.0. (devel 464a436f8f)

```
TASK [testing localaction] *****************************************************
changed: [sample-host] => {"changed": true, "cmd": "hostname", "delta": "0:00:00.002314", "end": "2015-08-18 13:59:34.326815", "rc": 0, "start": "2015-08-18 13:59:34.324501", "stderr": "", "stdout": "ansible-server.sample", "stdout_lines": ["ansible-server.sample"], "warnings": []}

TASK [debug var=testingoutput] *************************************************
ok: [sample-host] => {
    "changed": false, 
    "testingoutput": {
        "changed": true, 
        "cmd": "hostname", 
        "delta": "0:00:00.002314", 
        "end": "2015-08-18 13:59:34.326815", 
        "rc": 0, 
        "start": "2015-08-18 13:59:34.324501", 
        "stderr": "", 
        "stdout": "ansible-server.sample", 
        "stdout_lines": [
            "ansible-server.sample"
        ], 
        "warnings": []
    }
}
```

Actual Results:
ansible 2.0.0 (devel 86100da3a0)

```
TASK [testing localaction] *****************************************************
changed: [sample-host] => {"changed": true, "cmd": "hostname", "delta": "0:00:00.003015", "end": "2015-08-18 13:55:46.846948", "rc": 0, "start": "2015-08-18 13:55:46.843933", "stderr": "", "stdout": "sample-host.sample", "stdout_lines": ["sample-host.sample"], "warnings": []}

TASK [debug var=testingoutput] *************************************************
ok: [sample-host] => {
    "changed": false, 
    "testingoutput": {
        "changed": true, 
        "cmd": "hostname", 
        "delta": "0:00:00.003015", 
        "end": "2015-08-18 13:55:46.846948", 
        "rc": 0, 
        "start": "2015-08-18 13:55:46.843933", 
        "stderr": "", 
        "stdout": "sample-host.sample", 
        "stdout_lines": [
            "sample-host.sample"
        ], 
        "warnings": []
    }
}
```

**Comment by bcoca** [comment]
confirmed the issue, as a workaround connection: local still works as it should

**Comment by bcoca** [comment]
so local_action is an alias to delegate_to: localhost, which seems to also not be working

**Comment by bcoca** [comment]
confirm that the PR fixes this issue for you also.

**Comment by orderedchaosdev** [comment]
Initial tests show this fixing it I'm going to run a few more tests and report back success or failure

**Comment by orderedchaosdev** [comment]
I'm having an issue with a template now that is being generated as a local action
"AttributeError: 'HostVars' object has no attribute '_inventory'"
it just uses hostvars[host].ip which we define for every host it was working before

**Comment by orderedchaosdev** [comment]
ip_address_template.j2

```
{% for host in groups['all_host_vars']|sort %}
{% if hostvars[host].inactive is undefined %}
{% if hostvars[host].ip is defined %}
{{ hostvars[host].ip }}
{% endif %}
{% endif %}
{% endfor %}
```

being run in a role

```
---
 - name: generate ip address list
   local_action: template src=ip_address_template.j2 dest={{ans_tmp_dir}}iplist.txt
```
