### ISSUE TITLE
Third task of a block is ignored in an included file

### ISSUE THREAD

**Issue by gbandet** [ansible/ansible#11995]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.0.0
##### Ansible Configuration:

No change
##### Environment:

Gentoo Linux but probably does not matter.
##### Summary:

If a playbook includes another file for its tasks, and this second file contains a block of multiple tasks, the third task of the block is not executed
In all the tests I've done when trying to understand the problem, it was always the third task which was ignored.
##### Steps To Reproduce:

Run `ansible-playbook test.yml` with these files:
- test.yml

```
- hosts: all 
  tasks: 
    - include: include.yml
```
- include.yml

```
- block: 
    - debug: msg="Test 1" 
    - debug: msg="Test 2" 
    - debug: msg="Test 3" 
    - debug: msg="Test 4" 
    - debug: msg="Test 5"
```
##### Expected Results:

All five tasks are executed.
##### Actual Results:

The third task is ignored.

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [test]

TASK [include] *****************************************************************
included: include.yml for test

TASK [debug msg=Test 1] ********************************************************
ok: [test] => {
    "changed": false, 
    "msg": "Test 1"
}

TASK [debug msg=Test 2] ********************************************************
ok: [test] => {
    "changed": false, 
    "msg": "Test 2"
}

TASK [debug msg=Test 4] ********************************************************
ok: [test] => {
    "changed": false, 
    "msg": "Test 4"
}

TASK [debug msg=Test 5] ********************************************************
ok: [test] => {
    "changed": false, 
    "msg": "Test 5"
}

PLAY RECAP *********************************************************************
test                       : ok=6    changed=0    unreachable=0    failed=0
```

**Comment by gbandet** [comment]
After some other tests, I've found other problems related to this.
- If a block has 3 or more tasks, then the following tasks/blocks are not executed too. So with the following include.yml, only debug 1, 2, 4, 5 are executed.

```
- block: 
    - debug: msg="Test 1" 
    - debug: msg="Test 2" 
    - debug: msg="Test 3" 
    - debug: msg="Test 4" 
    - debug: msg="Test 5" 
- debug: msg="TEST 6" 
- block: 
    - debug: msg="Test 7"
```
- With 2 tasks in the block, the next top-level task/block is ignored but the execution continues after it. With the code below, debug 1, 2 and 7 are executed. It seems that the "ignored third task" is reported to the parent list.

```
- block: 
    - debug: msg="Test 1" 
    - debug: msg="Test 2" 
- debug: msg="TEST 6" 
- block: 
    - debug: msg="Test 7"
```

**Comment by chrrrles** [comment]
Also seeing this behavior... investigating.

**Comment by fvant** [comment]
I have a similar behaviour but not with block: 

roles/Myrole/tasks has 4 files:

a.yml
b.yml
c.yml
main.yml

and main.yml  - includes a.yml  etc

but only the first include gets executed. No error/warning. When i swap b.yml with a.yml , still only the first one get run.
I can add task above the first include and it gets executed just fine.

Anything (task or include) after the first - include: does nothing.

**Comment by jimi-c** [comment]
@fvant that is a separate issue, could you please create a new issue for this with an example which reproduces it? Thanks!

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
