### ISSUE TITLE
ansible is caching connections?

### ISSUE THREAD

**Issue by tvb** [ansible/ansible#12006]
I am having this weird issue where it seems ansible is caching the connecting.
Working on Ubuntu 14.04.3 LTS and ansible 1.9.2.

```
root@deploy:~/ansible$ ansible -m command -a "ip a " -i host1/inventory app1.blaat -verbose
app1.host1 | success | rc=0 >>
1: [output stripped]
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether aa:01:73:60:b6:6d brd ff:ff:ff:ff:ff:ff
    [output stripped]
```

But running the same command against another inventory and another host I am receiving the same results?!

```
 root@deploy:~/ansible$ ansible -m command -a "ip a " -i host2/inventory app1.host2 -verbose
app1.host2 | success | rc=0 >>
1: [output stripped]
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether aa:01:73:60:b6:6d brd ff:ff:ff:ff:ff:ff
   [output stripped]
```

Checking on the actual app1.host2 though ssh:

```
(test) root@app1:~# ip a
1: [output stripped]
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether aa:01:78:00:bf:2f brd ff:ff:ff:ff:ff:ff
   [output stripped]
```

Notice the mac address is actually different then what ansible is telling me.
This problem is giving me weird results in the playbook I am using against those hosts. I verified that the JSON cache files ansible is producing has the same content for app1.host1 as app1.hosts2.

I have no clue on what this is causing..

**Comment by bcoca** [comment]
Ansible itself does not cache connections, but if you ssh is new enough it will be using control master/persist which allows ssh itself to cache connections, you can disable this by overriding ssh args in ansible.cfg or switching to paramiko as a transport.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by tvb** [comment]
@bcoca Sorry for bugging you, but which 'args' are you referring to?

[edit] I tried to set    

```
ControlMaster no
ControlPath none
```

in mij ssh/config and in the ansible.cfg as -o options for ssh_args but none has effect. The output is still the same. 

Fun fact; The same hosts always give the wrong output, probably because the ip addresses are the same and only the proxy IPs are different. In reality those hosts are really two separate instances but apparently ansible does think otherwise.

[ansible] -> [public ip x] -> {host 1} (10.0.0.20)
[ansible] -> [public ip a] -> {host 2} (10.0.0.20)

**Comment by tvb** [comment]
Ok, I can confirm the follow settings in the ansible.cfg fixes my issue:

```
[ssh_connection]
ssh_args            = -o ControlMaster=no -o ControlPersist=no
control_path       = /dev/null
```

**Comment by bcoca** [comment]
you don't need that many changes
just setting it this way should be enough

ssh_args            = ''

another option is to switch to using paramiko.

## 

Brian Coca
