### ISSUE TITLE
Tasks that take a long time give no indication of how long

### ISSUE THREAD

**Issue by CorySpitzer** [ansible/ansible#12010]
When running a playbook, some tasks might take quite a while to finish. It would great if there was some feedback as to the progress of that task. Should I expect it to take a minute or 30? Or is it stuck and will  make no progress at all?

**Comment by chrrrles** [comment]
There is no deterministic way to estimate the running progress for a general Ansible task.  The best suggestion to handle blocking situations is to write playbooks using asynchronous actions for tasks expected to have long running times.
