### ISSUE TITLE
Variable evaluation in task names inconsistent

### ISSUE THREAD

**Issue by bezerker** [ansible/ansible#12028]
Version: ansible-playbook 1.9.2
It appears that variable evaluation within task names is inconsistent. If a task name inside a role contains a variable it appears to be only be evaluated if passed as a role parameter.  Even if that variable is overridden via command line, the task name will still use the old variable evaluation.

test-play.yml

```

---
- hosts: localhost
  vars:
    testvar2: bar
  roles:
  - { role: test, testvar: foo }
```

roles/test/tasks/main.yml

```

---
- name: Echo variable testvar with value {{ testvar }}
  debug: msg="testvar is {{ testvar }}"

- name: Echo variable testvar2 with value {{ testvar2 }}
  debug: msg="testvar2 is {{ testvar2 }}"
```

A normal playbook run displays the following:

```
TASK: [test | Echo variable testvar with value foo] *************************** 
ok: [localhost] => {
    "msg": "testvar is foo"
}

TASK: [test | Echo variable testvar2 with value {{ testvar2 }}] *************** 
ok: [localhost] => {
    "msg": "testvar2 is bar"
}
```

However overriding testvar to baz on the playbook command line will return an interesting result.

```
TASK: [test | Echo variable testvar with value foo] *************************** 
ok: [localhost] => {
    "msg": "testvar is baz"
}
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.


This is not inconsistent, extra vars (command line) are always available for templating, as can be vars used during role import. Vars in the play or hosts get declared too late to be used in name templating.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
