### ISSUE TITLE
fact caching does not store the host_vars or group_vars

### ISSUE THREAD

**Issue by feliksik** [ansible/ansible#12048]
I run a playbook for hostA that contains  references to hostB: 
`{{hostvars['hostB'].somevar}}`
This somevar is defined in the file `host_vars/hostB`

This only works when I run a playbook for both hostA and hostB, as they must gather each other facts (even though these facts are already on disk!). This is all fine as there is fact caching. 

However: although the fact caching module (`fact_caching = jsonfile`) does store the `cachedir/hostB` file on my disk, **this file does not include the variables from `host_vars/hostB`**. So I can still not run the playbook on hostA without also running it on hostB. 

(also applies for `group_vars/groupABCD`)

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Fact caching  is for 'caching facts', group and host vars are not included, this was never intended to cache inventory variables just facts gathered from hosts to avoid the expense of gathering them every time. The host_vars are not at all related to facts, they are part of inventory loading and should be available independent of fact gathering or caching.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by feliksik** [comment]
thanks for the kind way of pointing me to that  @bcoca
