### ISSUE TITLE
Fix the binary copy wart (core edition)

### ISSUE THREAD

**Issue by garthk** [ansible/ansible#12060]
Neither of the following obvious approaches work for storing `/etc/ssh/ssh_host_key` in an Ansible vault, i.e. a vars file:
- YAML 1.1's `!binary` ([spec](http://yaml.org/spec/1.1/), [tag draft](http://yaml.org/type/binary.html)), because the parser fails
- `copy` with `content` set to `"{{ ssh_host_key|b64decode }}"`, because the Jinja2 template engine [corrupts the result](https://groups.google.com/forum/#!topic/ansible-devel/lR0k2S0GIQw/discussion)

All the workarounds I've found involve writing to temporary files and decoding them, plus use of `register` and `changed_when` to detect whether the target really changed or not.

Could we add the `!binary` parser to avoid the need to use Jinja2, or fix our use of Jinja2, or fix Jinja2?

See also: ansible/ansible-modules-core#1961

**Comment by abadger** [comment]
i don't beleive that we can get information from the playbook to the modules without passing the strings through jinja2 so I don't think that there's an easy way to do this at this time without a workaround like you talk about.

For vault in particular, @bcoca has some ideas about referencing vault files directly from parameters.  best to try to engage him on that particular point.

**Comment by abadger** [comment]
Here's the vault ticket with bcoca's ideas: https://github.com/ansible/ansible/issues/7298

Closing htis ticket as a duplicate.
