### ISSUE TITLE
csvfile delimiter should use string, not unicode.

### ISSUE THREAD

**Issue by shirou** [ansible/ansible#12062]
### Issue Type:

Bug Report
### Ansible Version:

ansible 1.9.2
### Ansible Configuration:

nothing special.
### Environment:
- Mac OS X (yosemite)
- Python 2.7.8
### Summary:

When I use csvfile lookup with variables, it cauces error

```
"delimiter" must be string, not unicode
```
### Steps To Reproduce:

```
debug: msg="{{ lookup('csvfile', item + ' file=test.csv delimiter=, col=2') }}"
```
### Expected Results:

lookup works
### Actual Results:

```
TASK: [debug ] **************************************************************** 
fatal: [foo] => Failed to template status={{ lookup('csvfile', inventory_hostname + ' file=list.csv delimiter=, col=3') }}: csvfile: "delimiter" must be string, not unicode
```

There is another person who met same problem on the ML.
https://groups.google.com/d/msg/ansible-project/wCCPzHG6ucM/3AWR_-KOOzUJ

It seems  csv delimiter should be string, not unicode. In my environment, changing these files 
- https://github.com/ansible/ansible/blob/d35b9569006be8b6fb2090b24969b678166386e2/lib/ansible/plugins/lookup/csvfile.py#L33
- https://github.com/ansible/ansible/blob/5be384bab02a4a6cfdc6854e84b005bfcb162034/v1/ansible/runner/lookup_plugins/csvfile.py#L32

to 

```
            creader = csv.reader(f, delimiter=str(delimiter))
```

works fine.

**Comment by arturmartins** [comment]
+1
Same problem here.

Changed `/usr/share/pyshared/ansible/runner/lookup_plugins/csvfile.py` according to @shirou's workaround and it worked.
