### ISSUE TITLE
INI inventory file requires nested groups to be declared in a specific order?

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1208]
If a group is to include other groups, it seems the other groups must be defined ahead of them in the file.

It would be nice if this were not the case and you could list them in any order.

**Comment by dagwieers** [comment]
Shouldn't this be the INI inventory file ?

**Comment by mpdehaan** [comment]
typo, yes

**Comment by dhozac** [comment]
Example file:

```
[webservers:children]
web-cluster
intranets

[web-cluster:children]
web-cluster-01
web-cluster-02

[web-cluster-01]
web01.example.com
web02.example.com

[web-cluster-02]
web11.example.com
web12.example.com

[intranets]
intranet.example.com
```

**Comment by dagwieers** [comment]
Thanks again Daniel ! This was another one of my outstanding bugs !
