### ISSUE TITLE
Ansible win_unzip not working for 17mb file - from windows to windows

### ISSUE THREAD

**Issue by Robby123** [ansible/ansible#12080]
Is there a file size limit on the zip file when using win_unzip?

fatal: []: FAILED! => {"changed": false, "failed": true, "msg": "Error unzipping /path/to/zip.zip to path/to/dir"}

**Comment by jhawkesworth** [comment]
Probably not a file size limit per se, but you might be hitting some other quota or limit as winrm imposes some (configurable) limits on what remotely-run powershell is allowed to do.

This article below describes increasing max amount of memory allowed per process, but there are other limits too which you can see by examining winrm configuration.

http://blogs.technet.com/b/heyscriptingguy/archive/2013/07/30/learn-how-to-configure-powershell-memory.aspx

Always worth a quick check in your event logs to see if something was reported there too.

Hope this helps,

Jon

**Comment by jhawkesworth** [comment]
@Robby123 - would love to know what you discovered so that others can learn what the fix was in future.

**Comment by jaimess** [comment]
just try with `drive:\\foo\\bar` style in your path instead of `drive:/foo/bar`
it would be nice to be consistent between linux and windos modules.

**Comment by vmichnowicz** [comment]
I was using forward slashes as well and getting this error. As @jaimess said this worked for me:

```
- name: unzip the code
    win_unzip: src=C:\\Windows\\Temp\\myzip.zip dest=C:\\Windows\\Temp\\myzip
```
