### ISSUE TITLE
Allow fine grained fact gathering

### ISSUE THREAD

**Issue by bcoca** [ansible/ansible#12088]
allow doing subsets of current facts or the inclusion of any existing _facts module, default is current setup module full facts:

```
- hosts: all
  gathering: minimal, network, ec2
```

**Comment by preflightsiren** [comment]
+1

**Comment by Yannig** [comment]
@bcoca: I'm working on this feature.

Here is a simple example:
- Default behavior:

```
ansible -m setup localhost
ansible -m setup -a "gathering=all" localhost
```
- network set:

```
ansible -m setup -a "gathering=network" localhost
```
- hardware set (longest facts to retrieve):

```
ansible -m setup -a "gathering=hardware" localhost
```
- minimal set:

```
ansible -m setup -a "gathering=min" localhost
```

**Comment by bcoca** [comment]
closing via #13443
