### ISSUE TITLE
autodocument all plugins

### ISSUE THREAD

**Issue by bcoca** [ansible/ansible#12089]
As we currently keep module docs in the modules themselves and use that to generate docs both in ansible-doc and docs.ansible.com, we should be able to do the same for lookup, callback, connection, filter, inventory, vars, etc  plugin types.

The current python variables way is a bit onerous, something based on docstrings might be easier and not interfere with execution.

**Comment by jpmens** [comment]
+1 for documenting these _within_ the files. IMO it wouldn't be necessary to be able to `ansible-doc` them, but a generator which then spits out their documentation somehow -- well yes.
