### ISSUE TITLE
some options not preserved from ansible.cfg

### ISSUE THREAD

**Issue by jpetrelliswork** [ansible/ansible#12111]
##### Issue Type:

Bug Report
##### Ansible Version:

2.0.0 devel
##### Ansible Configuration:

ask_pass=True
##### Environment:

SLES11SP2/SP3
##### Summary:

Some options from ansible.cfg are not preserved during processing.  
Similar, but didn't fix all affected options: https://github.com/ansible/ansible/commit/0de83ad2890ff6bb7a98572010e9148cc192a864 
##### Steps To Reproduce:
- Set ask_pass=True in Ansible.cfg
- Run ansible.  It will not prompt for password.
##### Expected Results:

Ansible should prompt for password.
##### Actual Results:

Ansible does not prompt for password.

Notes:
Looking at the fix linked above, I found the following in lib/ansible/cli/**init**.py:

```
257: parser.add_option('--ask-vault-pass', default=False, dest='ask_vault_pass', action='store_true',
301: parser.add_option('--ask-become-pass', default=False, dest='become_ask_pass', action='store_true',
306: parser.add_option('-k', '--ask-pass', default=False, dest='ask_pass', action='store_true',
324: parser.add_option("-C", "--check", default=False, dest='check', action='store_true',
328: parser.add_option("-D", "--diff", default=False, dest='diff', action='store_true',
```

306 should use the values from constants.py (similar for others as well):
parser.add_option('-k', '--ask-pass', default=C.DEFAULT_ASK_PASS, dest='ask_pass', action='store_true',

**Comment by jimi-c** [comment]
cc @bcoca
