### ISSUE TITLE
Module authorized_key can corrupt authorized_keys file and lock Ansible out

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#1211]
When you have a filesystem full condition on /root (or whatever user) you risk loosing your authorized_keys. The module should in fact copy the file next to the existing authorized_keys and move it over the existing one only when finished.

I will look at this.

**Comment by mpdehaan** [comment]
Agreed!

**Comment by mpdehaan** [comment]
it really should probably just edit as a temp file and then daisy chain into the 'copy' module.

**Comment by sfromm** [comment]
@dagwieers Are you working on this?  If not, I have a patch I can submit.  See https://github.com/sfromm/ansible/commit/329cd5a3f1953d70069b4064497668f038e331e4

**Comment by sfromm** [comment]
I can replicate the problem.  I'll try to isolate where it happens.

**Comment by sfromm** [comment]
ugh, wrong issue.  please ignore the last one.

**Comment by dagwieers** [comment]
I'd probably would implement it differently (make the copy in the same directory as the destination, rather than in a potentially different filesystem), but if it works, fine for me.

**Comment by sfromm** [comment]
@dagwieers Easy enough to make the temp file in the same directory.  I'll rework what I have and submit that.
