### ISSUE TITLE
Using group_by with ansible_container causes everything to be added to the same group

### ISSUE THREAD

**Issue by mavit** [ansible/ansible#12125]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 1.9.2
  configured module search path = None
```
##### Ansible Configuration:

Reproduced with default config.
##### Environment:

Solaris 10, 11.
##### Summary:

With certain keys, `group_by` dumps all hosts into the same group, regardless of expected differences in the keys.  I can reproduce the below problem using the `ansible_container` variable but not the `ansible_virtualization_type` variable; it's not clear to me how these variables differ in nature.
##### Steps To Reproduce:

```
- hosts: host-g:host-z
  tasks:
    - group_by: key=container_{{ ansible_container | default('global') }}
    - debug: var=groups
```

In this example, `host-z` is a container, and `host-g` is not a container.
##### Expected Results:

```
ok: [host-g] => {
    "var": {
        "groups": {
            "container_global": [
                "host-g"
             ],
             "container_zone": [
                "host-z"
            ]
        }
    }
}
```
##### Actual Results:

```
ok: [host-g] => {
    "var": {
        "groups": {
            "container_global": [
                "host-g",
                "host-z"
            ]
        }
    }
}
```

**Comment by bennojoy** [comment]
@mavit  so is the ansible_container variable populated in host-g host-z ?

so if you do ansible -i "host-g," host-g -m setup | grep ansible_container what do you get ?

**Comment by mavit** [comment]
@bennojoy: In this example, `host-z` is a container, and `host-g` is not a container.  Variable `ansible_container` is populated only on `host-z`, and is undefined on `host-g`.  The code that does this is https://github.com/ansible/ansible/blob/v1.9.2-1/lib/ansible/module_utils/facts.py#L2594.

**Comment by bennojoy** [comment]
@mavit  yeah i was just wondering if this variable 'ansible_container' is getting set , as from the output it seems like the variable is not set on either hosts hence container_global is being returned, If the variable is set then it might be some other issue also is the container name 'host-z' ? there might be an issue if the group name has a '-' character in it.

**Comment by mavit** [comment]
The container type of `host-z` is `zone`.  By permuting the hosts the test-case is run on, it can be made to put all hosts in the group `container_zone` instead of `container_global`.

**Comment by mavit** [comment]
I retested this with Ansible version 2.1.1.0, and no-longer see the issue.
