### ISSUE TITLE
synchronize: destination host not interpolated

### ISSUE THREAD

**Issue by tquenolle** [ansible/ansible#12120]
##### Issue Type:
- Bug Report
##### Ansible Version:

2.0.0
##### Environment:

Gentoo
##### Summary:

Having defined `ansible_ssh_host: "{{ some_variable }}"` in group_vars  results in synchronize calling: `rsync /path/to/src root@{{ some_variable}}:/path/to/dest`

The destination host is not replaced by the actual value before the call resulting in an error:
`Could not resolve hostname {{ some_variable }}`
##### Steps To Reproduce:

In a playbook:

``` yaml
      synchronize:
        src: "/home/infra/solr/"
        dest: "/home/solr/collections/"
```

In etc/ansible/group_vars/your_group:

``` yaml
ansible_ssh_host: "{{ private_ip }}"
```

In etc/ansible/host_vars/some_host

``` yaml
private_ip: xxx.xxx.xxx.xxx
```
##### Expected Results:

I expect synchronize to call:
`rsync /path/to/src root@xxx.xxx.xxx.xxx:/path/to/dest`
##### Actual Results:

```
failed: [solr1-stg] => 
  (item=tquenolle_project) => {
    "cmd": "rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPersist=60s -F etc/ansible/ssh_config' --out-format='<<CHANGED>>%i %n%L' \"/home/infra/solr/solr-stg/tquenolle_project\" \"root@{{ private_ip }}:/home/solr/collections/tquenolle_project\"",
  "failed": true,
  "item": "tquenolle_project",
  "msg": "ssh: Could not resolve hostname {{ private_ip }}: Name or service not known\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]\n", "rc": 255}
```

**Comment by chrrrles** [comment]
This is the expected behavior, and maybe not well understood-- yet it deserves explaining why as it is very important that group variables are processed before their member host variables.  This order of precedence is mentioned in http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable:

```
Remember: Child groups override parent groups, and hosts always override their groups.
```

This probably is not the clearest explanation for how group and host variables are instantiated - that is better documented in the code for Ansible's VariableManager:

```
        The order of precedence is:
        - play->roles->get_default_vars (if there is a play context)
        - group_vars_files[host] (if there is a host context)
        - host_vars_files[host] (if there is a host context)
        - host->get_vars (if there is a host context)
        - fact_cache[host] (if there is a host context)
        - vars_cache[host] (if there is a host context)
        - play vars (if there is a play context)
        - play vars_files (if there's no host context, ignore
          file names that cannot be templated)
        - task->get_vars (if there is a task context)
        - extra vars
```
