### ISSUE TITLE
Error when rendering stdout output that contains {% sequence

### ISSUE THREAD

**Issue by willharris** [ansible/ansible#12123]
I have a command that greps ps output for varnish processes:

```
  tasks:
    - name: Get Varnish process status
      shell: ps ax -o pid,command | grep varnish | grep -v grep
      register: varnishprocs
      changed_when: false

    - debug: var=varnishprocs.stdout_lines
```

One of these processes is the `varnishncsa` process, which has a log format syntax similar to Jinja2's. When the debug command tries to render the lines, it generates an error:

```
fatal: [rms-v1] => Failed to template {{varnishprocs.stdout_lines}}: Failed to template  5428 /usr/sbin/varnishd -P /run/varnishd.pid -a :80 -T localhost:6082 -f /etc/varnish/unleash-live.vcl -S /etc/varnish/secret -s malloc,24G
 5431 /usr/sbin/varnishd -P /run/varnishd.pid -a :80 -T localhost:6082 -f /etc/varnish/unleash-live.vcl -S /etc/varnish/secret -s malloc,24G
26863 varnishncsa -F %t - %s - %{CF-Connecting-IP}i %U %{X-Platform}o %{Varnish:hitmiss}x - %D (%T)
32191 /usr/bin/varnishncsa -a -w /var/log/varnish/varnishncsa.log -D -P /run/varnishncsa/varnishncsa.pid -F "%{CF-Connecting-IP}i|%u|%{%Y-%m-%d}t|%{%H:%M:%S}t|%{%z}t|%m|%{Host}i|%U|%q|%s|%b|%{Referer}i|%{User-agent}i|%{Varnish:time_firstbyte}x|%T|%D|%{Varnish:handling}x|%{X-FE-Varnish-Obj-TTL}o|%{X-FE-Varnish-Backend}o|%{X-FE-Varnish-Obj-Stat}o|%{VCL_Log:backend}x|%{VCL_Log:normalize1}x|%{VCL_Log:normalize2}x": template error while templating string: Encountered unknown tag 'Y'.
```

I have not found a way to work around this without modifying the grep command. For example, adding either of the following will fix the problem:

```
| sed 's/{//g'
```

```
| sed 's/%//g'
```

This seems rather hacky though, and distorts the output obviously. It would be nice to have a filter or something to mark the output as to not be templatized.

**Comment by jimi-c** [comment]
Hi @willharris, what version of Ansible are you running?

**Comment by willharris** [comment]
Sorry, of course: 1.9.2, python 2.7.10

**Comment by jimi-c** [comment]
Thanks, is there any chance you could test this against devel? The debug action plugin has several changes in it which should prevent this from failing outright as above.

**Comment by willharris** [comment]
Sure will try it out. Need two weeks as I'm travelling at the moment.

**Comment by willharris** [comment]
Had a chance to test against devel, but essentially the same result:

```
(ans-env)[11:31:13] 🎸 ~/Workspaces/ansible % ap --version
ansible-playbook 2.0.0 (devel 90e005d234) last updated 2015/09/10 11:30:53 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 34655e8e29) last updated 2015/09/10 11:30:57 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 6a3cf63351) last updated 2015/09/10 11:31:02 (GMT +200)
  config file = /Users/harris/Workspaces/ansible/ansible.cfg
  configured module search path = None
(ans-env)[11:31:17] 🎸 ~/Workspaces/ansible % ap status.yml -i caches

PLAY ***************************************************************************
skipping: no hosts matched

PLAY ***************************************************************************

TASK [Get Varnish process status] **********************************************
ok: [rms-v1]
ok: [rms-v2]
ERROR! template error while templating string: Encountered unknown tag 'Y'.
```

Also tested with 1.9.3 and got same as with 1.9.2.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
