### ISSUE TITLE
"module not found" when using delegate_to 127.0.0.1

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#12132]
In a playbook I'm delegating to 127.0.0.1 This errors out with a module not found when running off the v2 codebase. The actual task can be found here: https://github.com/trondhindenes/ansibleroles-winreboot/blob/master/tasks/main.yml. When running on the v1 codebase everything works. Using the same module in an ad-hoc command works fine (on both v1 and v2). 

The stat module is exactly where it should be, so I'm guessing there's some bug with delegate_to using v2.

**Comment by bcoca** [comment]
hmm, it might be getting confused because the target is windows and it might be looking for a .ps1 extension in stead of a .py.

Can you try changing delegate_to: 127.0.0.1 to connection: local?

**Comment by trondhindenes** [comment]
Hi, connection: local does not work. It still tries to execute against the windows node instead of localhost

**Comment by jhawkesworth** [comment]
Hey, this sounds very simliar to
https://github.com/ansible/ansible/issues/12056 (which chris church root
cause is covered by https://github.com/ansible/ansible/issues/12053)

**Comment by trondhindenes** [comment]
Yup, probably the same. I was sure I'd seen this before somehow. Closing this issue since it's covered in more detail in #12056 / #12053
