### ISSUE TITLE
{ role: foo, when: bar is defined } runs without evaluating the condition

### ISSUE THREAD

**Issue by kwerey** [ansible/ansible#12142]
Heya. I found some weird behaviour going on in response to the construction in Ansible 1.9.0.1:

 `- { role: blah, when: "blah is defined" }` 

For this snippet:

```
  - name: Check if check_mk is defined
    debug: var="{{ check_mk }}"
    tags: cmk
    when: "check_mk is defined"

  roles:
  - { role: check_mk, when: "check_mk is defined" }
  - { role: artifactory, when: "artifactory is defined" }
```

I get this output:

```
GATHERING FACTS *************************************************************** 
ok: [test-vm]

TASK: [Check if check_mk is defined] ****************************************** 
skipping: [test-vm]

TASK: [check_mk | ensure nagios is running prior to check_mk install] ********* 
failed: [test-vm] => {"failed": true}
msg: no service or tool found for: nagios

FATAL: all hosts have already failed -- aborting
```

Expected behaviour: comparators work the same for tasks and roles

Actual behaviour: 
- comparison operators other than `is defined` seem to evaluate correctly for roles. This works fine, for example:

`- { role: check_mk, when: "random_var != 45" }`
- running a role conditionally on an `is defined` statement always runs the role. The `is defined` comparator does not seem to be evaluated correctly.

Any insight into it much appreciated, even if it's just 'oh, that was fixed in version 1.9.X'!

**Comment by jimi-c** [comment]
@kwerey can you share what that failed task is? Conditionals applied in this way should be pre-pended to each task's, so it should evaluate the `foo is undefined` conditional before doing anything else. I believe the only time that is not true is with tasks that use a with_ loop, but that doesn't seem to be the case here.

**Comment by kwerey** [comment]
@jimi-c No, it's not a loop - I know `with_dict` has some buggy behaviour when it comes to conditionals, but this one is about as linear as you can get:

```
- name: ensure nagios is running prior to check_mk install
  service:
    name: nagios
    pattern: "/usr/sbin/nagios -d /etc/nagios/nagios.cfg"
    state: started
    enabled: yes
```

Thanks for taking a look at this so quickly.

**Comment by kwerey** [comment]
For anyone else hitting this, the workaround I went with was just split the role calls up into plays that run against the specific host groups:

```
- name: Run common roles
  hosts:  linux_hosts
  sudo: yes
  tags: [ common, foo, bar ]

  roles: 
  - foo
  - bar

- name: For blah servers, run blah
  hosts: blah-servers
  sudo: yes
  tags: [ blah ]

  roles: 
  - blah
```

In cases where you don't wanna do that, you can stick `when:` statements on every task in the role.

**Comment by jimi-c** [comment]
That's very odd, but testing against devel I'm not seeing it. Can you run a quick test if possible against devel to see if the problem persists?

**Comment by kwerey** [comment]
Cool cool. I was running on 1.9.0, I've pulled devel. 

```
ansible --version
ansible 2.0.0 (devel 0880687f9d) last updated 2015/08/28 19:10:46 (GMT +100)
```

I don't think there's anything funky in my ansible config. Hash behaviour is set to merge, gather_facts is implicit. 

Running this:

```
- name: Run the role.
  hosts: test-case-1
  pre_tasks:

  - debug: var="someothervar"
    when: '"someothervar" is defined'
  roles: 

  - { role: check_mk, when: '"someothervar" is defined' }
```

Gives me:

```
ansible-playbook -i inventory/hosts main.yml --tags blah

PLAY [Create Vagrantfile with target hosts.] ***********************************

PLAY [Run the role.] ***********************************************************

TASK [setup] *******************************************************************
ok: [unarchive-test-case-1]

TASK [debug var=someothervar] **************************************************
ok: [unarchive-test-case-1] => {
    "changed": false, 
    "someothervar": "VARIABLE IS NOT DEFINED!"
}

TASK [check_mk : ensure nagios is running prior to check_mk install] ***********
fatal: [unarchive-test-case-1]: FAILED! => {"changed": false, "failed": true, "msg": "no service or tool found for: nagios"}

PLAY RECAP *********************************************************************
unarchive-test-case-1      : ok=2    changed=0    unreachable=0    failed=1   
```

Interestingly changing the conditional to `when: '3 == 35'` gives us:

```
TASK [check_mk : ensure nagios is running prior to check_mk install] ***********
 [WARNING]: Error when using <bound method CallbackModule.v2_runner_on_skipped of <ansible.plugins.callback.default.CallbackModule object
at 0x10218a490>>: global name 'C' is not defined
```

I'll see if I can replicate the same thing with a different role another day, but it's 8pm here, so time to put down the interesting technical problem and get some dinner :)

**Comment by jimi-c** [comment]
@kwerey I just fixed that callback issue as well, as another user had reported it.

**Comment by jimi-c** [comment]
Hrm, I also see you're using tags when running this, which you didn't mention earlier, however I'm not seeing that change anything unless your tags are contained within your role/tasks/main.yml file (meaning applied to tasks there directly)?

**Comment by jimi-c** [comment]
No, even then I'm not seeing a task in that role run.

**Comment by kwerey** [comment]
Yeah, soz, that's me debugging in a kinda silly way - I wrote the test I wanted to do, then pasted into a playbook that had a "make a handy test VM" play set up with an appropriate dictionary to feed into it & a hosts definition I knew had nothing weird going on. Between writing the test I wanted to use and running it I changed:

```
- name: Run the role.
  hosts: test-case-1
  pre_tasks:
```

To:

```
- name: Run the role.
  hosts: unarchive-test-case-1
  tags: [ blah ]
  pre_tasks:
```

(For some reason that made more sense at the time than making a whole new file to test from.)

Anyway, I couldn't find evidence of anyone else running into this issue by googling it, though I'm not sure how many people would have a complicated enough ecosystem of roles to want to use this kind of logic. If you can think of any weirdness that could be going on in my local environment to cause it, I'm happy to go investigate and report back - it's an odd enough behaviour that I'm curious.

**Comment by jimi-c** [comment]
@kwerey I see your problem:

<pre>
- { role: check_mk, when: '"someothervar" is defined' }
</pre>

The quotes around `someothervar` mean it's evaluated as a string (which is always true, because it's not zero-length) and not a variable. Simply remove the quotes around that and you should be fixed.

**Comment by kwerey** [comment]
Naw, that wasn't what was messing me up - the first example I pasted was `when: "check_mk is defined"`, and that had the same behaviour.

But I found it and it was a completely dumb error on my part - the role I was running sets a check_mk variable:

```
GATHERING FACTS *************************************************************** 
ok: [unarchive-test-case-1]

TASK: [debug var="check_mk"] ************************************************** 
ok: [unarchive-test-case-1] => {
    "var": {
        "check_mk": "check_mk"
    }
}

TASK: [check_mk | debug var=check_mk] ***************************************** 
ok: [unarchive-test-case-1] => {
    "var": {
        "check_mk": {
            "interface": "eth0"
        }
    }
}
```

Thanks for your help! Closing issue.

**Comment by jimi-c** [comment]
No problem, glad you identified it.

Thanks!
