### ISSUE TITLE
Unable to splat arguments in windows script

### ISSUE THREAD

**Issue by perzizzle** [ansible/ansible#12149]
Ansible Version: 1.9.2
OS: RHEL 6.5

I recently upgraded from ansible 1.8 to 1.9. Since then splatting has stopped working. This was originally fixed in https://github.com/ansible/ansible/pull/10664 as discussed on https://groups.google.com/forum/#!starred/ansible-project/jojvFohOwqM. This pull request included some unit tests that seem to have been removed. I added them back and ran:
TEST_FLAGS="-t test_win_script -i /etc/ansible/hosts" make test_winrm
...
TASK: [test_win_script | run test script that takes parameters passed via splatting] ***
changed: [server] => {"changed": true, "rc": 0, "stderr": "", "stdout": "\n\n\n"}

TASK: [test_win_script | check that script ran and received parameters via splatting] ***
failed: [server] => {"assertion": "test_script_with_splatting_result.stdout_lines[0] == 'this'", "evaluated_to": false, "failed": true}

FATAL: all hosts have already failed -- aborting

If you change line 60 of /usr/lib/python2.6/site-packages/ansible/runner/shell_plugins/powershell.py to be return ' '.join(['&'] + cmd_parts) and then re-run the unit tests they all pass.

TASK: [test_win_script | run test script that takes splatted parameters from a variable] ***
changed: [server] => {"changed": true, "rc": 0, "stderr": "", "stdout": "THIS\nTHAT\nOTHER\n"}

TASK: [test_win_script | check that script ran and received parameters via splatting from a variable] ***
ok: [server] => {"msg": "all assertions passed"}

**Comment by jhawkesworth** [comment]
I could be wrong but I think this has been tackled in v2. Worth trying the
v2 alpha to see if it is fixed.

**Comment by nitzmahone** [comment]
working for v2, closing

**Comment by perzizzle** [comment]
@nitzmahone what version of ansible did you get this to work on? I'm using ansible 2.0.1.0 and when i try to "splat" I get errors like:

Cannot convert the "@{'datacenter'='dc1';'job'='admin-console-master';'AppPoolName'='AdminConsole';'build'='759';}\" value of type\"System.String\" to type \"System.Collections.Hashtable\

**Comment by nitzmahone** [comment]
Splat integration tests for win_script are passing on devel and stable-2.0- if it's not working for you, I'd suspect an escaping issue of some sort... (there haven't been any changes that should have affected that since initial 2.0)

**Comment by cchurch** [comment]
@perzizzle Try removing the outermost double quotes.

**Comment by perzizzle** [comment]
@cchurch you were correct there was an additional quote in my call to the script module. Thanks!
