### ISSUE TITLE
Ansible help

### ISSUE THREAD

**Issue by Robby123** [ansible/ansible#12141]
I am currently using a host Linux machine with a windows node, my aim is to download a zip file on either machine and then run jinja2 template on the files in the zip. Then by the end the new files will need to be on the windows node. I have tried using win_copy to transfer the files but this takes too long, a share won't be possible. Any other ideas?

**Comment by jhawkesworth** [comment]
Please can you ask 'how do I this'-type questions on ansible mailing list or the irc channel.  This helps to keep the github issue tracker just for tracking actual bugs.

I suggest adding a web server to your stack and then using win_get_url to fetch the zip file onto which ever machine needs it from the web server.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
