### ISSUE TITLE
ssh connections fail with long host names due to ControPath length

### ISSUE THREAD

**Issue by mdomsch** [ansible/ansible#12144]
Symptom:
ansible, using ssh connections, will fail imediately after successful SSH login, with no useful messages shown via -vvvv.  Plain ssh connections work.

Using ssh LogLevel DEBUG, you see this message:
mkdir: missing operand
Try 'mkdir --help' for more information.

Root Cause:
In my configuration, I am using the long DNS hostname of an AWS EC2 instance.  The ansible ControlPath variable is normally set to 
ControlPath="$HOME/.ansible/cp/ansible-ssh-%h-%p-%r"

However, in this case, when %h has 49 characters in it (maybe more, maybe less), ssh fails to create that socket, as the file name is too long.

The solution is, instead of using %h-%p-%r, to use %C (hash of %h-%p-%r) which is short enough not to cause the failure to create the socket.

I do not know when %C was introduced.  I do know that CentOS 7 does _NOT_ have it, while Fedora 22 does, so somewhere between openssh-clients-6.6.1p1-12.el7_1.x86_64 and openssh-clients-6.9p1-4.fc22.x86_64.  This means you cannot make a blanket move to using %C there to address it.

**Comment by chrrrles** [comment]
##### Issue Type:

Can you help us out in labelling this by telling us what kind of ticket this this?  You can say:
- Bug Report
- Feature Idea
- Feature Pull Request
- New Module Pull Request
- Bugfix Pull Request
- Documentation Report
- Docs Pull Request

##### Ansible Version:

Let us know what version of Ansible you are using.  Please supply the verbatim output from running “ansible --version”.  If you're filing a ticket on a version of Ansible which is not the latest, we'd greatly appreciate it if you could retest on the latest version first.  We don't expect you to test against the development branch most of the time, but we may ask for that if you have cycles.  Thanks!

##### Ansible Configuration:

What have you changed about your Ansible installation?  What configuration settings have you changed/added/removed?  Compare your /etc/ansible/ansible.cfg against a clean version from Github and let us know what's different.

##### Environment:

What OS are you running Ansible from and what OS are you managing?  Examples include RHEL 5/6, Centos 5/6, Ubuntu 12.04/13.10, *BSD, Solaris.  If this is a generic feature request or it doesn’t apply, just say “N/A”.  Not all tickets may be about operating system related things and we understand that.

##### Summary:

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.  Thanks!

##### Steps To Reproduce:

If this is a bug ticket, please enter the steps you use to reproduce the problem in the space below.  If this is a feature request, please enter the steps you would use to use the feature.  If an example playbook is useful, please include a short reproducer inline, indented by four spaces.  If a longer one is necessary, linking to one uploaded to gist.github.com would be great.  Much appreciated!

##### Expected Results:

Please enter your expected results in this space.  When running the steps supplied above in the previous section, what did you expect to happen?  If showing example output, please indent your output by four spaces so it will render correctly in GitHub's viewer thingy.

##### Actual Results:

Please enter your actual results in this space.  When running the steps supplied above, what actually happened?  If you are showing example output, please indent your output by four spaces so it will render correctly in GitHub.  Thanks again!

**Comment by chrrrles** [comment]
Hi @mdomsch  - can you help us reproduce / fix this bug by filling out our issue template?  Thanks!

**Comment by mdomsch** [comment]
Issue Type:

Bug Report

Ansible Version:

ansible-1.9.2

Ansible Configuration:

nothing in ansible.cfg

Environment:

Fedora 22 x86_64 with ansible installed from Fedora repos

Summary:

ansible, using ssh connections, will fail imediately after successful SSH login, with no useful messages shown via -vvvv. Plain ssh connections work.

Using ssh LogLevel DEBUG, you see this message:
mkdir: missing operand
Try 'mkdir --help' for more information.

Steps To Reproduce:

Have something like this in ~/.ssh/config:
Host aws-ansible
    HostName ec2-111-111-111-111.us-west-2.compute.amazonaws.com

Run ansible or ansible-playbook.

ansible all -i hosts -m setup

Expected Results:

successful execution

Actual Results:

Immediate fail, after SSH login has succeeded.

$ ansible all -i environment/aws-ansible -m ping

aws-ansible | FAILED => SSH Error: unix_listener: "/home/mdomsch/.ansible/cp/ansible-ssh-ec2-111-111-111-111.us-west-2.compute.amazonaws.com-22-centos.sqgEPqNcEXZuXSpV" too long for Unix domain socket

Proposed fix:
Shortening the name of the ControlPath socket fixes this.

**Comment by jimi-c** [comment]
This is actually a known issue, and something that is beyond our control, which is why we allow the SSH options for the control persist settings to be configured in ansible.cfg. See the documentation here: http://docs.ansible.com/ansible/intro_configuration.html#control-path

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
