### ISSUE TITLE
2.0 variable in handler regression

### ISSUE THREAD

**Issue by mattwillsher** [ansible/ansible#12154]
Issue Type:

Bug Report

Ansible Version:

```
ansible 2.0.0 (devel 6154ed1dda) last updated 2015/08/29 08:17:32 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 66288d48a2) last updated 2015/08/28 18:59:50 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 8d8f1c510d) last updated 2015/08/28 18:59:56 (GMT +100)
  config file = /Users/matt/Development/ansible/ansible.cfg
  configured module search path = None
```

Ansible Configuration:

```
[defaults]
inventory=inventory/hosts
roles_path=roles:galaxy
gathering = smart
fact_caching = jsonfile
fact_caching_connection = factcache
fact_caching_timeout = 86400

[privilege_escalation]
become=True

[ssh_connection]
pipelining = True
ssh_args=-o ControlMaster=auto -o ControlPersist=30m -o ControlPath=/tmp/ansible-ssh-%h-%p-%r
```

Environment:

Local: Darwin heron.local 15.0.0 Darwin Kernel Version 15.0.0: Mon Aug 10 17:09:09 PDT 2015; root:xnu-3247.1.99~3/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin
Remote: CentOS 7.1

Summary:

In the role/handlers/mail.yml

``` yaml

---
- name: reload_sshd
  service:
    name: '{{ sshd_service }}'
    state: reloaded
  when: sshd_allow_reload
```

throws:

```
EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=30m -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 lux.wilsys.net LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python
fatal: [lux.wilsys.net]: FAILED! => {"changed": false, "failed": true, "msg": "OpenSSH_6.9p1, LibreSSL 2.1.7\r\ndebug1: Reading configuration data /Users/matt/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 20: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 102: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 39726\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nTraceback (most recent call last):\n  File \"<stdin>\", line 3226, in <module>\n  File \"<stdin>\", line 1482, in main\n  File \"<stdin>\", line 574, in get_service_status\n  File \"<stdin>\", line 555, in get_systemd_service_status\n  File \"<stdin>\", line 531, in get_systemd_status_dict\nValueError: need more than 1 value to unpack\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n", "parsed": false}
```

Replacing the variable with the service name works. 
This worked under 1.x

Steps To Reproduce:

See above

Expected Results:

Variable value gets inserted, service reloads.

Actual Results:

See above.

**Comment by jimi-c** [comment]
Hi @mattwillsher, where is that variable being defined?

**Comment by mattwillsher** [comment]
Hi @jimi-c - via vars/ in https://github.com/willshersystems/ansible-sshd which get included via a   include_vars & with_first_found in the tasks/main.yml

**Comment by jimi-c** [comment]
Looking at the detailed output from the `msg` field, this error is actually occuring on the remote side:

<pre>
OpenSSH_6.9p1, LibreSSL 2.1.7
debug1: Reading configuration data /Users/matt/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 20: Applying options for *
debug1: /etc/ssh/ssh_config line 102: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 39726
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
Traceback (most recent call last):
  File "<stdin>", line 3226, in <module>
  File "<stdin>", line 1482, in main
  File "<stdin>", line 574, in get_service_status
  File "<stdin>", line 555, in get_systemd_service_status
  File "<stdin>", line 531, in get_systemd_status_dict
ValueError: need more than 1 value to unpack
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 1
</pre>

Looking into this further.

**Comment by jimi-c** [comment]
@mattwillsher can you run your ansible command with the environment variable `ANSIBLE_KEEP_REMOTE_FILES=1` prepended to it? This will keep the module code on the remote system, which you can then examine. Could you find the `MODULE_COMPLEX_ARGS` value set in the file and share it here (be sure to filter out any data which may be sensitive).

**Comment by mattwillsher** [comment]
```  
# grep MODULE_COMPLEX_ARGS .ansible/tmp/ansible-tmp-1441111466.97-257056593325193/service
MODULE_COMPLEX_ARGS = '{"state": "reloaded", "name": "{{ sshd_service }}"}'
        params = json_dict_unicode_to_bytes(json.loads(MODULE_COMPLEX_ARGS))
```

**Comment by bcoca** [comment]
ok, as expected, the templating is not happening, but what really puzzles me is that systemctl does not return an error.

**Comment by mattwillsher** [comment]
`/usr/bin/systemctl show {{ sshd_service }}`

outputs:

```
Id=\x7b\x7b.service
Names=\x7b\x7b.service
Description=\x7b\x7b.service
LoadState=not-found
ActiveState=inactive
SubState=dead
InactiveExitTimestampMonotonic=0
ActiveEnterTimestampMonotonic=0
ActiveExitTimestampMonotonic=0
InactiveEnterTimestampMonotonic=0
CanStart=yes
CanStop=yes
---->8 snip ----
```

$? == 0

**Comment by bcoca** [comment]
opened https://github.com/systemd/systemd/issues/1105, but looking at workaround in current service module

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment]
@bcoca also pushed a fix for the system module to properly check the status of a service via systemd to determine if the service specified actually exists.

Thanks!
