### ISSUE TITLE
ansible_os_family = "NA" on Manjaro host

### ISSUE THREAD

**Issue by pgmillon** [ansible/ansible#12169]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.1
##### Ansible Configuration:

Standard
##### Environment:

Running a virtualenv on Arch.
##### Summary:

ansible_os_family returns "NA" for my Manjaro machine.
##### Steps To Reproduce:

ansible -m setup |grep ansible_os_family
##### Expected Results:

```
"ansible_os_family": "Archlinux",
```
##### Actual Results:

```
"ansible_os_family": "NA", 
```

**Comment by toshywoshy** [comment]
Please check pull request #12261
