### ISSUE TITLE
ImportError: cannot import name AnsibleOptionsError in v2.0.0-0.1.alpha1 release

### ISSUE THREAD

**Issue by metmajer** [ansible/ansible#12160]
Hi there,

I am a huge fan of Ansible and just figured out some new features in the `v2.0.0-0.1.alpha1` that I immediately wanted to give a try. When I download and extract this release though on my Mac, I get the following error when invoking `./bin/ansible`:

```
metmajer$ ./bin/ansible
Traceback (most recent call last):
  File "./bin/ansible", line 39, in <module>
    from ansible.errors import AnsibleError, AnsibleOptionsError, AnsibleParserError
ImportError: cannot import name AnsibleOptionsError
```

This error does not happen in any of the previous releases of v1.9.

**Comment by jimi-c** [comment]
Hi @metmajer, did you source the `hacking/env-setup` script or otherwise install Ansible 2.0 alpha? As is, if you have an existing installation of Ansible, it will try and use the old files (which obviously don't have many of the newer classes in them).

If you're just trying the 2.0 alpha out, I highly recommend using the script above, as it simply modifies your PYTHONPATH and some other environment variables to use Ansible from the source code directory. This is a non-permanent change, and once the shell/session is closed your system is back to the state it was in before sourcing the script. See http://docs.ansible.com/ansible/intro_installation.html#running-from-source for more details.

**Comment by metmajer** [comment]
Thanks @jimi-c, I've overlooked that step. That helps!

**Comment by jimi-c** [comment]
No problem, glad it was an easy one :)

Thanks!

**Comment by chymian** [comment]
hello :)
I do have the same problem on debian, using 2.2.0-0.git201606132206.62e6f6b.devel~unstable using a deb, which I build out of the tree yesterday.
It's stays the same when I source the hacking/env-setup…

```
ansible-playbook site.yml -t rancher
```

The playbook Snippet:

```
- name: Setting up Rancher Server
  hosts: "rancher"
  become: yes
  become_user: root
  strategy: debug
  roles:
    - { role: eb8.rancher, tags: ["rancher"] }
```

```
PLAY [Setting up Rancher Server] ***********************************************
ERROR! Unexpected Exception: cannot import name linear
the full traceback was:

Traceback (most recent call last):
  File "/net/han33/usr/src/ansible/bin/ansible-playbook", line 97, in <module>
    exit_code = cli.run()
  File "/net/han33/usr/src/ansible/lib/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/net/han33/usr/src/ansible/lib/ansible/executor/playbook_executor.py", line 143, in run
    result = self._tqm.run(play=play)
  File "/net/han33/usr/src/ansible/lib/ansible/executor/task_queue_manager.py", line 232, in run
    strategy = strategy_loader.get(new_play.strategy, self)
  File "/net/han33/usr/src/ansible/lib/ansible/plugins/__init__.py", line 333, in get
    self._module_cache[path] = self._load_module_source('.'.join([self.package, name]), path)
  File "/net/han33/usr/src/ansible/lib/ansible/plugins/__init__.py", line 319, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/net/han33/usr/src/ansible/lib/ansible/plugins/strategy/debug.py", line 9, in <module>
    from ansible.plugins.strategy import linear
ImportError: cannot import name linear
```

Do I miss something?

**Comment by jimi-c** [comment]
@chymian that is a completely unrelated error, could you please open a new issue for this? Thanks! It does seem like you've gotten a bad installation somehow, as the `linear.py` file should be installed with Ansible. Most likely you have an old installation of Ansible?

**Comment by danielkza** [comment]
I'm seeing the same issue with Ansible 2.1.0.0 in Fedora 24.

**Comment by mikefaille** [comment]
I have the same issue as @danielkza  with  Ansible 2.1.0.0 in Fedora 24.

**Comment by timka** [comment]
@danielkza @mikefaille @chymian It's a separate issue #16825

**Comment by timka** [comment]
A workaround.

Change line

```
from ansible.plugins.strategy import linear
```

to

```
import ansible.plugins.strategy.linear as linear
```
