### ISSUE TITLE
Bug Report - Variable defined in `group_vars` not picked up by `when`

### ISSUE THREAD

**Issue by blagarde** [ansible/ansible#12179]
## Version

```
$ ansible --version
ansible 1.9.2
  configured module search path = None
```
## Ansible Configuration

Vanilla
## Environment

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty
```
## Summary

``` bash
$ tree 
.
├── group_vars
│   └── all.yml     <- bar: "{{foo == 'value2'}}"
├── test
│   ├── group_vars
│   │   └── all.yml <- foo: value1
│   └── inventory
└── test.yml        <- "when: not bar" gets incorrectly skipped although bar correctly recognized as False
```
## Repro steps, Actual results, Expected results

I made a repo with repro steps [here](https://github.com/blagarde/ansible_groupvars_bug/tree/master).

**Comment by chrrrles** [comment]
The git repo is a good start, but it will also help us if you can fill our issue report template:

##### Issue Type:

Can you help us out in labelling this by telling us what kind of ticket this this?  You can say:
- Bug Report
- Feature Idea
- Feature Pull Request
- New Module Pull Request
- Bugfix Pull Request
- Documentation Report
- Docs Pull Request

##### Ansible Version:

Let us know what version of Ansible you are using.  Please supply the verbatim output from running “ansible --version”.  If you're filing a ticket on a version of Ansible which is not the latest, we'd greatly appreciate it if you could retest on the latest version first.  We don't expect you to test against the development branch most of the time, but we may ask for that if you have cycles.  Thanks!

##### Ansible Configuration:

What have you changed about your Ansible installation?  What configuration settings have you changed/added/removed?  Compare your /etc/ansible/ansible.cfg against a clean version from Github and let us know what's different.

##### Environment:

What OS are you running Ansible from and what OS are you managing?  Examples include RHEL 5/6, Centos 5/6, Ubuntu 12.04/13.10, *BSD, Solaris.  If this is a generic feature request or it doesn’t apply, just say “N/A”.  Not all tickets may be about operating system related things and we understand that.

##### Summary:

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.  Thanks!

##### Steps To Reproduce:

If this is a bug ticket, please enter the steps you use to reproduce the problem in the space below.  If this is a feature request, please enter the steps you would use to use the feature.  If an example playbook is useful, please include a short reproducer inline, indented by four spaces.  If a longer one is necessary, linking to one uploaded to gist.github.com would be great.  Much appreciated!

##### Expected Results:

Please enter your expected results in this space.  When running the steps supplied above in the previous section, what did you expect to happen?  If showing example output, please indent your output by four spaces so it will render correctly in GitHub's viewer thingy.

##### Actual Results:

Please enter your actual results in this space.  When running the steps supplied above, what actually happened?  If you are showing example output, please indent your output by four spaces so it will render correctly in GitHub.  Thanks again!

**Comment by blagarde** [comment]
Hello,
I am not sure I understand. I did fill in all of the headers from the issue
template. What extra information am I expected to provide?
Thanks!
Baptiste

2015-09-01 19:08 GMT+02:00 notifications@github.com:

**Comment by chrrrles** [comment]
Thanks @blagarde - closing as this is fixed in devel:

```

TASK [not bar] *****************************************************************
changed: [localhost] => {"changed": true, "cmd": "date", "delta": "0:00:00.003705", "end": "2015-09-01 14:02:42.459751", "rc": 0, "start": "2015-09-01 14:02:42.456046", "stderr": "", "stdout": "Tue Sep  1 14:02:42 CDT 2015", "stdout_lines": ["Tue Sep  1 14:02:42 CDT 2015"], "warnings": []}

```

**Comment by blagarde** [comment]
Awesome, thanks!
