### ISSUE TITLE
ansible not making parallel connections

### ISSUE THREAD

**Issue by orderedchaosdev** [ansible/ansible#12193]
Issue Type: 

Bug Report

Ansible Version:

```
ansible 2.0.0 (devel f162990cb3) last updated 2015/09/01 14:59:17 (GMT -700)
  lib/ansible/modules/core: (detached HEAD bbcfb1092a) last updated 2015/09/01 12:51:05 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD b8803306d1) last updated 2015/09/01 12:51:06 (GMT -700)
```

Ansible Configuration:

```
forks=50
inventory=~/<inventory directory>
transport=ssh
remote_user=root
```

Environment:

Centos 6.7 up to date as of 01SEP2015 from base repos and epel

Summary:

It seems as though in the latest version of devel tasks are not running in parallel. When I watch an execution of a playbook with -vvvv in the setup stage I only see one debug message at a time and then its ok and in the old one it would make several connections.

Steps To Reproduce:

Have a inventory of about 100 hosts with different ping times.
This is just a simplified way I believe this can be seen. 

```
ansible hosts -m ping
```

Expected Results:

From 

```
ansible 2.0.0 (detached HEAD 464a436f8f) last updated 2015/08/20 14:06:50 (GMT -700)
  lib/ansible/modules/core: (detached HEAD dea5f5d15e) last updated 2015/08/20 14:06:50 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 210ee3febc) last updated 2015/08/20 14:06:50 (GMT -700)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/08/20 14:06:50 (GMT -700)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/08/20 14:06:50 (GMT -700)
```

I would expect the hosts to somewhat come back in a consistent order but not always the exact same order due to ping times. so

```
host-1 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
host-3 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
host-2 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
host-4 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
```

Actual Results:

```
host-1 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
host-2 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
host-3 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
host-4 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
```

Everytime it is in this order and it is much slower.  From looking at connections from my system the new version does not seem to be making multiple connections.

**Comment by orderedchaosdev** [comment]
If you would like I could copy paste the setup section of a playbook run but it is just as I described. Old version, multiple connections and the setup facts return in somewhat random order. New version, one connection at a time and facts return in a serial 1 like order

**Comment by jimi-c** [comment]
The debug output uses a lock to synchronize output, so it will look serialized that way. That doesn't mean the forks aren't operating in parallel.

**Comment by orderedchaosdev** [comment]
what about just the stdout that is output while a play is running. Is that also locked in the new version with no -vvvv

**Comment by orderedchaosdev** [comment]
I have been trying to figure out the cause behind the major runtime difference between the old version I listed above and the current development branch since the slowdown is so bad we have to stay on the old version.

**Comment by orderedchaosdev** [comment]
Until I find better examples I'm going to close this issue
