### ISSUE TITLE
Unexpected / confusing behaviour of ansible_python_interpreter

### ISSUE THREAD

**Issue by caprazzo** [ansible/ansible#1221]
Hi.

I was trying to use ansible_python_interpreter to force remote hosts to use a different interpreter

$ cat ansible-stage-hosts
[staging]
fcpa01 ansible_python_interpreter=/home/fds/rms/usr/bin/python
fcpb01 ansible_python_interpreter=/home/fds/rms/usr/bin/python

$ ansible -v  -i ansible-stage-hosts all -m command -a 'which python' -u rms
fcpa01 | success | rc=0 >>
/usr/bin/python

fcpb01 | success | rc=0 >>
/usr/bin/python

To make sure that the variable was being picked up, I changed the hosts file:
$ cat ansible-stage-hosts
[staging]
fcpa01 ansible_python_interpreter=/home/fds/rms/usr/bin/python-FAIL
fcpb01 ansible_python_interpreter=/home/fds/rms/usr/bin/python-FAIL

$ ansible -v  -i ansible-stage-hosts all -m command -a 'which python' -u rms
fcpa01 | FAILED >> {
    "failed": true,
    "msg": "/bin/bash: /home/fds/rms/.ansible/tmp/ansible-1349279780.25-91402749213723/command: /home/fds/rms/usr/bin/python-FAIL: bad interpreter: No such file or
directory\r\n",
    "parsed": false
}

fcpb01 | FAILED >> {
    "failed": true,
    "msg": "/bin/bash: /home/fds/rms/.ansible/tmp/ansible-1349279780.47-167496872291969/command: /home/fds/rms/usr/bin/python-FAIL: bad interpreter: No such file or directory\r\n",
    "parsed": false
}

Thanks
-teo

**Comment by mpdehaan** [comment]
Ansible python interpreter does not change your path only what calls the module

Not a bug

-- Michael

**Comment by mpdehaan** [comment]
Also, take out the fail

ansible_python_interpreter=/home/fds/rms/usr/bin/python-FAIL

I'm totally at a loss here why you you think it should WORK when you set
the interpreter to a path you don't have installed

**Comment by caprazzo** [comment]
Hi,
the forced error was just to validate that the variable was in fact being
picked up. The failure was expected.

Ok, let's clarify this:
- the command module is being executed by the correct interpreter
- but the actual command is executed with a shell that ignores env
  variables from .bash_profile

Correct?

On 3 October 2012 17:04, Michael DeHaan notifications@github.com wrote:

> Also, take out the fail
> 
> ansible_python_interpreter=/home/fds/rms/usr/bin/python-FAIL
> 
> I'm totally at a loss here why you you think it should WORK when you set
> the interpreter to a path you don't have installed
> 
> On Wed, Oct 3, 2012 at 11:58 AM, Michael DeHaan michael.dehaan@gmail.comwrote:
> 
> > Ansible python interpreter does not change your path only what calls the
> > module
> > 
> > Not a bug
> > 
> > -- Michael
> > 
> > On Oct 3, 2012, at 11:56 AM, Matteo Caprari notifications@github.com
> > wrote:
> > 
> > Hi.
> > 
> > I was trying to use ansible_python_interpreter to force remote hosts to
> > use a different interpreter
> > 
> > $ cat ansible-stage-hosts
> > [staging]
> > fcpa01 ansible_python_interpreter=/home/fds/rms/usr/bin/python
> > fcpb01 ansible_python_interpreter=/home/fds/rms/usr/bin/python
> > 
> > $ ansible -v -i ansible-stage-hosts all -m command -a 'which python' -u
> > rms
> > fcpa01 | success | rc=0 >>
> > /usr/bin/python
> > 
> > fcpb01 | success | rc=0 >>
> > /usr/bin/python
> > 
> > To make sure that the variable was being picked up, I changed the hosts
> > file:
> > $ cat ansible-stage-hosts
> > [staging]
> > fcpa01 ansible_python_interpreter=/home/fds/rms/usr/bin/python-FAIL
> > fcpb01 ansible_python_interpreter=/home/fds/rms/usr/bin/python-FAIL
> > 
> > $ ansible -v -i ansible-stage-hosts all -m command -a 'which python' -u
> > rms
> > fcpa01 | FAILED >> {
> > "failed": true,
> > "msg": "/bin/bash:
> > /home/fds/rms/.ansible/tmp/ansible-1349279780.25-91402749213723/command:
> > /home/fds/rms/usr/bin/python-FAIL: bad interpreter: No such file or
> > directory\r\n",
> > "parsed": false
> > }
> > 
> > fcpb01 | FAILED >> {
> > "failed": true,
> > "msg": "/bin/bash:
> > 
> > /home/fds/rms/.ansible/tmp/ansible-1349279780.47-167496872291969/command:
> > /home/fds/rms/usr/bin/python-FAIL: bad interpreter: No such file or
> > directory\r\n",
> > "parsed": false
> > }
> > 
> > Thanks
> > -teo
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ansible/ansible/issues/1221>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/1221#issuecomment-9111654.

## 

:Matteo Caprari
matteo.caprari@gmail.com

**Comment by mpdehaan** [comment]
Ok, thanks for clarifying.  It was hard for me to tell what you expected to
work and what you didn't expect to work.

.bash_profile is not executed, true.

.bashrc is probably what you want if you want to set environment variables

http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html

Note that some calls deliberately try to source binaries in known paths to
avoid someone setting a bad PATH in the .bash profile, and with things like
easy_install you may want to consider virtualenv.

**Comment by caprazzo** [comment]
Ok, thanks for the explanation, I'll look into virtualenv.

For the time being, I'm going to use the shell module and setting the path
inline.

Thanks
-teo

On 3 October 2012 17:42, Michael DeHaan notifications@github.com wrote:

> Ok, thanks for clarifying. It was hard for me to tell what you expected to
> work and what you didn't expect to work.
> 
> .bash_profile is not executed, true.
> 
> .bashrc is probably what you want if you want to set environment variables
> 
> http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html
> 
> Note that some calls deliberately try to source binaries in known paths to
> avoid someone setting a bad PATH in the .bash profile, and with things like
> easy_install you may want to consider virtualenv.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/1221#issuecomment-9113048.

## 

:Matteo Caprari
matteo.caprari@gmail.com
