### ISSUE TITLE
Name is a required parameter for cron, but documentation notes it otherwise

### ISSUE THREAD

**Issue by mgirouard** [ansible/ansible#12235]
##### Issue Type:

Documentation Report
##### Ansible Version:

1.9.2
##### Ansible Configuration:

Default
##### Environment:

Local: MacOS Yosemitie
Remote: Centos 7
##### Summary:

The [documentation](http://docs.ansible.com/ansible/cron_module.html#options) states that the `name` parameter on the cron task is not required, but upon running a cron task without specifying the name, the play fails.

I haven't looked into the significance to the name parameter, but I'm assuming it's important. When I updated my playbook to include the name, I couldn't see it displayed in the output. If it's used internally, it's perhaps best to simply update the docs to note the correct value. If it's not actually required, I'd recommend updating the module to not force the required value.

This appears to be related to #10335, #1166. 
##### Steps To Reproduce:

Create a playbook with a cron task, like the following:

```

---
- hosts: all
- tasks:
    - name: Install logwatch cron job for root
      cron: hour=0 minute=0 job="logwatch"
```
##### Expected Results:

The task to run without error

```
TASK: [Install logwatch cron job for root] ************************************
ok: [default]
```
##### Actual Results:

```
TASK: [Install logwatch cron job for root] ************************************
failed: [default] => {"failed": true}
msg: missing required arguments: name

FATAL: all hosts have already failed -- aborting
```

**Edit:** Clarified wording

**Comment by mgirouard** [comment]
I just realized that the docs are in a separate repository. If this is a docs-related issue, I can close this out and submit a PR there.

**Comment by jimi-c** [comment]
Hi @mgirouard, yes please do. Thanks!
