### ISSUE TITLE
yum doesnt have force

### ISSUE THREAD

**Issue by ryanobjc** [ansible/ansible#1223]
if i am installing locally developed/unsigned packages I cant use the 'yum' module to install

**Comment by mpdehaan** [comment]
True, it doesn't.

You can disable GPG checking in your yum config as a workaround.

@skvidal -- what were your thoughts on exposing force?  I think we had decided against but I can't remember why.

**Comment by skvidal** [comment]
force and install unsigned are not the same thing.

installing unsigned local pkgs is something you can set in the yum config options.

localpkg_gpgcheck  Either  `1' or`0'. This tells yum whether or
              not it should perform a GPG signature check  on  local  packages
              (packages in a file, not in a repositoy).  The default is `0'.

set that in your yum.conf

if we want to set all yum options from the ansible module that will require some considerable work - especially to make it work with rhel5
