### ISSUE TITLE
with_flattened uses content of existing variables for the item values

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#12249]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible `stable-1.9`, Ansible `devel`
##### Ansible Configuration:

Standard configuration
##### Environment:

Debian, Ubuntu
##### Summary:

`with_flattened` uses content of existing variables to template `item` values.
##### Steps To Reproduce:

```

---

- hosts: localhost
  gather_facts: False

  vars:
    ferm: 'not-ferm-in-variable'
    ferm_packages: [ 'ferm' ]

  tasks:

    - name: Check variable
      debug:
        msg: 'Variable is {{ ferm }}'

    - name: Check with_items
      debug:
        msg: 'with_items is {{ item }}'
      with_items: ferm_packages

    - name: Check with_flattened
      debug:
        msg: 'with_flattened is {{ item }}'
      with_flattened:
        - [ 'ferm' ]
        - ferm_packages
```
##### Expected Results:

```
TASK: [Check variable] ******************************************************** 
ok: [localhost] => {
    "msg": "Variable is not-ferm-in-variable"
}

TASK: [Check with_items] ****************************************************** 
ok: [localhost] => (item=ferm) => {
    "item": "ferm", 
    "msg": "with_items is ferm"
}

TASK: [Check with_flattened] ************************************************** 
ok: [localhost] => (item=ferm) => {
    "item": "ferm", 
    "msg": "with_flattened is ferm"
}
ok: [localhost] => (item=ferm) => {
    "item": "ferm", 
    "msg": "with_flattened is ferm"
}
```
##### Actual Results:

```
TASK: [Check variable] ******************************************************** 
ok: [localhost] => {
    "msg": "Variable is not-ferm-in-variable"
}

TASK: [Check with_items] ****************************************************** 
ok: [localhost] => (item=ferm) => {
    "item": "ferm", 
    "msg": "with_items is ferm"
}

TASK: [Check with_flattened] ************************************************** 
ok: [localhost] => (item=not-ferm-in-variable) => {
    "item": "not-ferm-in-variable", 
    "msg": "with_flattened is not-ferm-in-variable"
}
ok: [localhost] => (item=not-ferm-in-variable) => {
    "item": "not-ferm-in-variable", 
    "msg": "with_flattened is not-ferm-in-variable"
}
```

**Comment by drybjed** [comment]
After a conversation with @jimi-c on IRC we decided that this issue cannot be resolved right now without affecting the way Ansible resolves "bare variables", so I'm closing this issue for now. The best way to handle this seems to be careful choice of the variable names to avoid clashes with important strings like package names.

**Comment by jimi-c** [comment]
As discussed, we intend to deprecate "bare" variables when used within lookups (for both with_ loops and `{{lookup('foo', ..)}}` usage) to make it easier/more obvious when variables are in play. However that will be post-2.0 release.

**Comment by hughsaunders** [comment]
@jimi-c Could we reopen this as v2 has been released?

**Comment by jimi-c** [comment]
@hughsaunders i don't think there's any resolution possible at this time. We've added a deprecation to doing this: `with_items: foo` to give notice to users that they need to do `with_items: "{{foo}}" if they really mean for that to be a variable. So in 2.2 we will no longer template that value unless it contains variable syntax.
