### ISSUE TITLE
authorized_key module has a documentation error

### ISSUE THREAD

**Issue by tessiof** [ansible/ansible#12242]
Documentation example:

> \- authorized_key: user=root key=public_keys/doe-jane state=present
>                   exclusive=yes

But **key=public_keys/doe-jane** is not a valid way to point to a key file. This error happens: 

> failed: [localhost] => {"failed": true}
> msg: invalid key specified: public_keys/doe-jane
> 
> FATAL: all hosts have already failed -- aborting

The correct code should be:

> \- authorized_key: user=root key="{{ lookup('file', 'public_keys/doe-jane') }}" state=present
>                   exclusive=yes

**Comment by toshywoshy** [comment]
Please be more specific which documentation, as it seems correct in the module documentation and as such should be correct in the other documentation

**Comment by tessiof** [comment]
I'm running the latest ansible stable:

> $ ansible --version
> ansible 1.9.2

In the last line of the module documentation:

> $ ansible-doc authorized_key
> ...
> - authorized_key: user=root key=public_keys/doe-jane state=present
>                  exclusive=yes

Also in the module [web page](http://docs.ansible.com/ansible/authorized_key_module.html): 
![authorized](https://cloud.githubusercontent.com/assets/2301644/9699267/d211e918-53b2-11e5-8401-1c6e2321d1d2.png)

**Comment by toshywoshy** [comment]
Yes, I see that in 1.9.2 that was the case, however it has been changed, the automatic documentation generation must be still lagging. In the current devel it is correct and it will therefor become correct after regeneration of the documentation

**Comment by abadger** [comment]
Fix committed to stable branch here: https://github.com/ansible/ansible-modules-core/commit/1106ec080463c85090bbb4d12d7159deb4f79840

Documentation on the website rebuilt from latest devel.

Thanks for filing a bug to let us know!
