### ISSUE TITLE
Since Version 1.9.3: yum name=* state=latest doesn't work anymore 

### ISSUE THREAD

**Issue by olblak** [ansible/ansible#12248]
Hi, 
Since ansible 1.9.3, yum update all packages doesn't work anymore.
The same command works on ansible 1.9.2

$ansible  8.8.8.8 -m yum -a "name=\* state=latest"
8.8.8.8 | FAILED >> {
    "changed": false, 
    "errors": "unexpected state", 
    "failed": true, 
    "msg": "we should never get here unless this all failed", 
    "results": ""
}

Regards,

**Comment by abadger** [comment]
Thanks for reporting this.  Issue is being tracked here: https://github.com/ansible/ansible-modules-core/issues/2013 

A fix has been committed and is linked from the issue if you'd like to test it out.  We're figuring out the timeframe of 1.9.4 to address this.
