### ISSUE TITLE
Setting forks > 20 results in "Unexpected Exception: [Errno 24] Too many open files"

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#12259]
##### Issue Type:

Bug Report
##### Ansible Version:

`v2.0.0-0.2.alpha2` (or latest devel, and way back pre-June at least)
##### Ansible Configuration:

```
[defaults]
roles_path = ~/Dropbox/VMs/roles
nocows = 1
hostfile = /etc/ansible/hosts
forks = 25     
host_key_checking=False
```
##### Environment:

Mac OS X 10.10.5 Yosemite
##### Summary:

I've had my ansible.cnf `forks` set to `25` so certain operations would run a bit faster across large numbers of hosts. However, when I was using Ansible 2.0.0 (devel branch, tested with many releases from the past few months), I would get the following error:

```
$ ansible all -m ping
Unexpected Exception: [Errno 24] Too many open files
```

If I reduce the number of `forks` to 20 or fewer, Ansible runs fine, and this error is never shown.

Note that I could set forks to astronomical numbers (I tested 100, 200, 500, and even 5000000 on my Mac) and there were no issues completing basic `ansible` commands like pinging all hosts.
##### Steps To Reproduce:
1. Make sure you're running Ansible 2.0.0 (devel).
2. Either set `forks=25` in ansible.cfg or run the following command with `--forks=25`
3. Run `ansible all -m ping`
##### Expected Results:

Ansible pings all hosts.
##### Actual Results:

Ansible fails, with the following debug output:

```
$ ansible all -m ping --forks=50 -vvv
Using /etc/ansible/ansible.cfg as config file
Unexpected Exception: [Errno 24] Too many open files
the full traceback was:

Traceback (most recent call last):
  File "/Users/jgeerling/Dropbox/Development/GitHub/drupal-vm/ansible/bin/ansible", line 79, in <module>
  File "/Users/jgeerling/Dropbox/Development/GitHub/drupal-vm/ansible/lib/ansible/cli/adhoc.py", line 152, in run
  File "/Users/jgeerling/Dropbox/Development/GitHub/drupal-vm/ansible/lib/ansible/executor/task_queue_manager.py", line 96, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 63, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
OSError: [Errno 24] Too many open files
```

**Comment by sivel** [comment]
This is related to OSX using very low limits.  You will need to raise them from their default of 200 like so:

```
sudo launchctl limit maxfiles 1024 2048
```

After this I normally place the following in `.profile` or `.bash_profile`

```
ulimit -n 1024
ulimit -u 1024
```

**Comment by geerlingguy** [comment]
@sivel - You're correct, and wow, it's quite low!

```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited
```

Ansible < 2.0.0 didn't have this issue—were there really just that many fewer files involved? What's the main culprit? I admit I haven't been as involved in the 2.0.0 release cycle as I wanted to be, but I didn't think the architecture shift would be quite so dramatic.

**Comment by jimi-c** [comment]
It's possible we're using more multiprocessing primitives, which require file handles (queues, etc.), so that may be the reason.

**Comment by bcoca** [comment]
made doc update in any case 91a5d06c213e1e6e1c8ad792e604a49dc61b9f15

**Comment by geerlingguy** [comment]
Docs update is helpful, and this sounds good; I've upped the limits and don't have an issue any longer. The majority of users can probably live with < 20 forks regardless, and on machines where Tower and/or other Ansible runners may live, limits are higher by default (I think 1024 on Ubuntu 14.04?), so this shouldn't be much of an issue there.

**Comment by tetherit** [comment]
Do NOT follow these instructions. They are incorrect and dangerous:

```
$ sudo launchctl limit maxfiles 1024 2048
update_terminalapp_cwd:6: pipe failed: too many open files in system                                                                                                                                    
zsh: pipe failed: too many open files in system
```

Once this command is ran, all the apps start crashing and you have to hold the power button for 5 seconds to power down your Mac. This is a Macbook Pro 13" Retina running El Capitan.

These are the defaults on El Capitan:

```
$ sudo launchctl limit
    cpu         unlimited      unlimited      
    filesize    unlimited      unlimited      
    data        unlimited      unlimited      
    stack       8388608        67104768       
    core        0              unlimited      
    rss         unlimited      unlimited      
    memlock     unlimited      unlimited      
    maxproc     709            1064           
    maxfiles    256            unlimited    
```

I tred this but it also does not help :( -

```
$ sudo launchctl limit maxfiles 4096 unlimited
$ ansible-playbook --forks=25 timeboxes-scan.yml         
Unexpected Exception: [Errno 24] Too many open files
```

**Comment by ppearcy** [comment]
To echo hackeron's comment, those instructions in commit 91a5d06 are dangerous and will force to have to hard reboot.

**Comment by jimi-c** [comment]
@hackeron you're still setting the soft limit, you may need to increase that even further.

**Comment by tetherit** [comment]
@jimi-c  example?

**Comment by rdmarsh** [comment]
Just to also confirm, running the `sudo launchctl` command resulted in having to power cycle my mac.

I'm seeing this fail at around `--forks=22` on `ansible 2.0.0.1`

**Comment by kinghrothgar** [comment]
To update launchctl without killing OS X place this in `/Library/LaunchDaemons/limit.maxfiles.plist` and reboot:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
        "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>limit.maxfiles</string>
    <key>ProgramArguments</key>
    <array>
    <string>launchctl</string>
    <string>limit</string>
    <string>maxfiles</string>
    <string>524288</string>
    <string>524288</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>ServiceIPC</key>
    <false/>
</dict>
</plist>
```

**Comment by t1891** [comment]
Hey, do anyone know if @kinghrothgar solution worked, or do anyone experience any problems?

**Comment by tonglil** [comment]
@t1891 I haven't had any problems.
OS X 10.11.3

```
cat limit.maxfiles.plist 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>limit.maxfiles</string>
        <key>ProgramArguments</key>
        <array>
            <string>launchctl</string>
            <string>limit</string>
            <string>maxfiles</string>
            <string>524288</string>
            <string>524288</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>ServiceIPC</key>
        <false/>
    </dict>
</plist>
```

**Comment by t1891** [comment]
@tonglil 
Thanks, I tried it and it works for me! :)

**Comment by jimi-c** [comment]
Hi all, as there are workarounds mentioned above, and this is not an issue with Ansible per-se, I'm going to go ahead and close this now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by geerlingguy** [comment]
Ha, a few years later ran into the same issue on a new macOS box with forks set to 25. Glad this info is here, saved me twice now!

**Comment by bcomnes** [comment]
@sivel, or @jimi-c can you edit @sivel's comment to add a note about how it no longer works on newer macOS, or to tell the reader to keep reading the rest of the thread?  Superficially, it looks like a reasonable suggestion, but it actually doesn't work and can screw up your computer in weird and hard to fix ways.  Jut got bit by that, as it looks like a few others.
