### ISSUE TITLE
Create a standard way to specify parameters to lookup plugins

### ISSUE THREAD

**Issue by abadger** [ansible/ansible#12255]
A couple recent bugs lead me to find that lookup modules have a variety of ways of specifying their parameters:
- https://github.com/ansible/ansible-modules-core/issues/1968
- https://github.com/ansible/ansible-modules-extras/issues/857

After some discussion, we probably want to add an additional standard ways to specify and parse parameters to lookup plugins. We'd officially support something like the following (examples only. Exact syntax subject to change as it's thought through):

```
- pass: "{{ lookup( 'password', [{ term: "/dir with spaces/", length: 25, } ]) }}"
- debug:
  msg: "{{ item }}"
  with_password:
  - term: "/dir with spaces/"
    length: 25
- debug:
  msg: "{{ item }}"
  with_password:
    - "/dir with spaces"
```

We would deprecate the former methods of specifying parameters:

```
- pass: "{{ lookup('password', '/dir_without_spaces length=25') }}"
```

I don't know if we'd continue to support the current style of arg passing that has support from the code when used via lookup() but not when used via when_\* and that some plugins (for instance, password), are currently ignoring.

```
- pass: "{{ lookup('password', ["/dir with spaces"], length=25) }}"
# No when_password: style equivalent of the above.
```

These are ideas for post-2.0... not enough time until then to work one of these solutions to completion.

**Comment by quinot** [comment]
Interesting, your suggested syntax is similar to what is used in my LDAP lookup module:
  https://github.com/quinot/ansible-plugin-lookup_ldap
except that I didn't use the "term: XXX" syntax. Instead, an item is a term by default (if it is a string), and overrides one or more configuration parameters if it is a dict. I will keep an eye on this issue, so that when some standard mechanism is defined, I can leverage it as well and simplify the module.

**Comment by jimi-c** [comment]
Going to move this to a proposal, so closing here.

**Comment by scottsb** [comment]
Was this ever turned into a proposal or otherwise further addressed? I don't see anything in the proposals repository or in the docs about this.

**Comment by BarbzYHOOL** [comment]
Is this implemented??

I just tested and it doesn't work on 2.7
