### ISSUE TITLE
Add a managed nodes requirement: SFTP subsystem

### ISSUE THREAD

**Issue by iliv** [ansible/ansible#12274]
Hello,

Availability of SFTP subsytem appears to be a crucial requirement that may render ansible broken if not met. Currently ansible doesn't detect nor describe lack of SFTP subsystem in a meaningful way that would suggest to a user that may need to make sure their managed systems meet this requirement, or, alternatively, fails to suggest that scp_if_ssh=True can be used to work around this problem.

I request that http://docs.ansible.com/ansible/intro_installation.html#managed-node-requirements gets updated with a note about SFTP subsystem as a managed nodes requirement.

Ivan

**Comment by bcoca** [comment]
done 246e602fceb7bcddac7263d942d2a7173f9f815d

**Comment by iliv** [comment]
Thank you bcoca.
