### ISSUE TITLE
v2 regression: fetch/su is broken

### ISSUE THREAD

**Issue by amenonsen** [ansible/ansible#12290]
Using the latest unmodified devel (@e2e9319f), a task like this:

```
- fetch: src=/etc/motd dest=motd
  su: yes
```

produces this in the debug output:

```
<raven.toroid.org> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/ams/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi
-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 raven.toroid.org /bin/sh -c 'su  root -c "/bin/sh -c '"'"'echo BECOME-SUCCESS-nrkohdhsakbxamjlftxhmfgphtzxevls; rc=flag;
 [ -r /etc/motd ] || rc=2; [ -f /etc/motd ] || rc=1; [ -d /etc/motd ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/etc/motd && exit 0; (python -c '"'"'"'"'"'"'"'"'import hashlib;
 BLOCKSIZE = 65536; hasher = hashlib.sha1();
afile = open("'"'"'"'"'"'"'"'"'/etc/motd'"'"'"'"'"'"'"'"'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
        hasher.update(buf)
        buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())'"'"'"'"'"'"'"'"' 2>/dev/null) || (python -c '"'"'"'"'"'"'"'"'import sha; BLOCKSIZE = 65536; hasher = sha.sha();
afile = open("'"'"'"'"'"'"'"'"'/etc/motd'"'"'"'"'"'"'"'"'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
        hasher.update(buf)
        buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())'"'"'"'"'"'"'"'"' 2>/dev/null) || (echo '"'"'"'"'"'"'"'"'0  '"'"'"'"'"'"'"'"'/etc/motd)'"'"'"'
 24251 1441789764.96724: Handling privilege escalation password prompt.
 24251 1441789764.96734: Waiting for Privilege Escalation input
 24251 1441789764.97364: Read next chunks
 24251 1441789764.97372: stderr chunk is: [removed, irrelevant ssh output]

 24251 1441789764.97394: Waiting for Privilege Escalation input
 24251 1441789764.97403: Read next chunks
 24251 1441789765.33084: stderr chunk is: debug1: mux_client_request_session: master session id: 2^M

 24251 1441789765.33136: Waiting for Privilege Escalation input
 24251 1441789765.33157: Read next chunks
 24251 1441789765.69062: stdout chunk is: /bin/sh: -c: line 0: syntax error near unexpected token `('^M
/bin/sh: -c: line 0: `su  root -c "/bin/sh -c 'echo BECOME-SUCCESS-nrkohdhsakbxamjlftxhmfgphtzxevls; rc=flag; [ -r /etc/motd ] || rc=2; [ -f /etc/motd ] || rc=1; [ -d /etc/motd ] && rc=3; python -V 2>/dev/null ||
rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/etc/motd && exit 0; (python -c '"'"'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1();'^M
```

Notice the `/bin/sh: -c: line 0: syntax error near unexpected token `(`

**Comment by amenonsen** [comment]
I notice that we do this in `playbook/play_context.py`, in the `make_become_cmd` method:

```
                prompt = detect_su_prompt
                becomecmd = '%s %s %s -c "%s -c %s"' % (exe, flags, self.become_user, executable, success_cmd)
                ...
            return ('%s -c %s' % (executable, pipes.quote(becomecmd)))
```

And so we issue `sh -c 'su root -c 'sh -c 'command'''` or `sh -c 'sudo 'sh -c 'command''` (with extra quoting). I do not know why we don't just use `su -c 'command'` or `sudo sh -c 'command'`. Indeed, when I change the code to do this, I can no longer reproduce the shell error above.

**Comment by jimi-c** [comment]
@amenonsen the above patch fixes this, and also passes the following test playbook:

<pre>
- hosts: all
  gather_facts: no
  remote_user: testing
  tasks:
  - command: whoami
  - command: whoami
    become: yes
    become_method: sudo
  - command: whoami
    become: yes
    become_method: su
  - fetch: src=/etc/hosts dest=/tmp/
  - fetch: src=/etc/passwd dest=/tmp/
    become: yes
    become_method: sudo
  - fetch: src=/etc/shadow dest=/tmp/
    become: yes
    become_method: su
</pre>

When run:

<pre>
TASK [command] *****************************************************************
changed: [awxlocal] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.001569", "end": "2015-09-20 08:12:53.779747", "rc": 0, "start": "2015-09-20 08:12:53.778178", "stderr": "", "stdout": "testing", "stdout_lines": ["testing"], "warnings": []}
TASK [command] *****************************************************************
changed: [awxlocal] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.001440", "end": "2015-09-20 08:12:53.922317", "rc": 0, "start": "2015-09-20 08:12:53.920877", "stderr": "", "stdout": "root", "stdout_lines": ["root"], "warnings": []}
TASK [command] *****************************************************************
changed: [awxlocal] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.001540", "end": "2015-09-20 08:12:54.086455", "rc": 0, "start": "2015-09-20 08:12:54.084915", "stderr": "", "stdout": "root", "stdout_lines": ["root"], "warnings": []}
TASK [fetch dest=/tmp/ src=/etc/hosts] *****************************************
changed: [awxlocal] => {"changed": true, "checksum": "5beaa461c1878cd5fc23a46a37f543b4b3628a0b", "dest": "/tmp/awxlocal/etc/hosts", "md5sum": "2eadc1e7ebf3572b44e120b46472dafe", "remote_checksum": "5beaa461c1878cd5fc23a46a37f543b4b3628a0b", "remote_md5sum": null}
TASK [fetch dest=/tmp/ src=/etc/passwd] ****************************************
changed: [awxlocal] => {"changed": true, "checksum": "8bc22051fa5e475f92fa9af8c889144fe4207972", "dest": "/tmp/awxlocal/etc/passwd", "md5sum": "9a0d7bc68563cf326dfb37faa867b0bd", "remote_checksum": "8bc22051fa5e475f92fa9af8c889144fe4207972", "remote_md5sum": null}
TASK [fetch dest=/tmp/ src=/etc/shadow] ****************************************
changed: [awxlocal] => {"changed": true, "checksum": "f58b07aae7c39eb14f50a6eeb2bb27e6caa074a2", "dest": "/tmp/awxlocal/etc/shadow", "md5sum": "4ce3c26026f755954ff0fafae3cadf30", "remote_checksum": "f58b07aae7c39eb14f50a6eeb2bb27e6caa074a2", "remote_md5sum": null}
PLAY RECAP *********************************************************************
awxlocal                   : ok=6    changed=6    unreachable=0    failed=0   
</pre>

When re-run:

<pre>
TASK [command] *****************************************************************
changed: [awxlocal] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.001555", "end": "2015-09-20 08:13:10.183234", "rc": 0, "start": "2015-09-20 08:13:10.181679", "stderr": "", "stdout": "testing", "stdout_lines": ["testing"], "warnings": []}
TASK [command] *****************************************************************
changed: [awxlocal] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.001539", "end": "2015-09-20 08:13:10.323168", "rc": 0, "start": "2015-09-20 08:13:10.321629", "stderr": "", "stdout": "root", "stdout_lines": ["root"], "warnings": []}
TASK [command] *****************************************************************
changed: [awxlocal] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.001589", "end": "2015-09-20 08:13:10.483456", "rc": 0, "start": "2015-09-20 08:13:10.481867", "stderr": "", "stdout": "root", "stdout_lines": ["root"], "warnings": []}
TASK [fetch dest=/tmp/ src=/etc/hosts] *****************************************
ok: [awxlocal] => {"changed": false, "checksum": "5beaa461c1878cd5fc23a46a37f543b4b3628a0b", "dest": "/tmp/awxlocal/etc/hosts", "file": "/etc/hosts", "md5sum": "2eadc1e7ebf3572b44e120b46472dafe"}
TASK [fetch dest=/tmp/ src=/etc/passwd] ****************************************
ok: [awxlocal] => {"changed": false, "checksum": "8bc22051fa5e475f92fa9af8c889144fe4207972", "dest": "/tmp/awxlocal/etc/passwd", "file": "/etc/passwd", "md5sum": "9a0d7bc68563cf326dfb37faa867b0bd"}
TASK [fetch dest=/tmp/ src=/etc/shadow] ****************************************
ok: [awxlocal] => {"changed": false, "checksum": "f58b07aae7c39eb14f50a6eeb2bb27e6caa074a2", "dest": "/tmp/awxlocal/etc/shadow", "file": "/etc/shadow", "md5sum": "4ce3c26026f755954ff0fafae3cadf30"}
</pre>

cc @bcoca

**Comment by jimi-c** [comment]
Due to the nature of this change, I would definitely like some increased testing, especially on BSD systems (which traditionally have caused us more command quoting issues).

**Comment by bcoca** [comment]
so i cannot reproduce this anymore, @amenonsen  please check against current head, it seems other work has fixed this as a side effect.

**Comment by amenonsen** [comment]
Still happens for me.

```
fatal: [raven.toroid.org]: FAILED! => {"failed": true, "msg": "ERROR! Timeout (0s) waiting for privilege escalation prompt: /bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `su  root -c \"/bin/sh -c 'echo BECOME-SUCCESS-zffxclzljewksgggykwkqwusobdtpzua; rc=flag; [ -r /etc/shadow ] || rc=2; [ -f /etc/shadow ] || rc=1; [ -d /etc/shadow ] && rc=3; python -V 2>/dev/null || rc=4; [ x\"$rc\" != \"xflag\" ] && echo \"${rc}  \"/etc/shadow && exit 0; (python -c '\"'\"'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1();'\n"}
```

**Comment by bcoca** [comment]
Noting here info from IRC discussions:

This seems to happen in certain combinations of Debian/Openssh when using the ssh connection plugin, but not paramiko. 

@amenonsen seems to have fix related to become command construction in  the works.

**Comment by amenonsen** [comment]
I've submitted a minimal fix for the quoting problem in PR #13176 (along with a fix to make `doas` support work properly on OpenBSD), and opened a new issue #13179 about a problem I discovered while testing the fix.

**Comment by amenonsen** [comment]
I did some more research on this. Here's what happens.
1. The `fetch` module calls `_remote_checksum`, which constructs a command, say `foo` (but we know that foo contains embedded double-quote characters).
2. `make_become_cmd` calls `pipes.quote()` on the above command (so we end up with `'echo XXX; foo'` where single quotes are escaped as `'"'"'` but double quotes aren't escaped at all), and then interpolates it into the `su` command string using `'… "%s -c %s"' % (…, success_cmd)`. This is simply **wrong**; the first unescaped internal double quote will terminate the argument string.
3. We send this command to the remote host, and get an error back from `/bin/sh` that is some variation of `/bin/sh: syntax error: `(' unexpected`.
4. `_remote_checksum` splits this up and returns `/bin/sh:` as its result checksum value.
5. Back in the fetch module, if we're using `become` (which we are, via su), we ignore the result of the `_remote_checksum()` call and fetch the data via `slurp` and recalculate the remote checksum.
6. Then the code goes on to transfer the file etc. and the `fetch` task succeeds.

https://gist.github.com/anonymous/2353b9cd0dcb5a8ff3c2 is the command produced in step (2) above and executed on the remote host. If you cut and paste this command into a shell, you'll get the same `unexpected (` error. (It's harmless: even if it succeeds, the worst it could do is to print a digest of `/etc/foo`.)

This is not in any way specific to my system or any particular version of the shell. I've seen it happen on three different versions of Debian now, on OpenBSD and FreeBSD, and Red Hat. Everyone I've asked to try the gist above has reported identical errors on their systems (including @willthames on Fedora). The same thing even happens with `-c paramiko`, it's just that it doesn't log the incoming data the same way, so I didn't notice the error. (I added some additional logging around `_remote_checksum` and verified that it also gets exactly the same `/bin/sh` error.)

TL;DR: we quote su commands incorrectly, and remote checksum commands fail, but when we're using su we ignore it and always recalculate the checksum, so the `fetch:` task succeeds.

@bcoca The only mystery is why you don't see the same error, but at this point I wonder if you're just missing it in among all the debug output (which is the only place where it's visible).

My fix is correct, and should be merged.

**Comment by amenonsen** [comment]
If anyone is curious, this can be reproduced easily using the following command. Substitute a suitable hostname for `some.ho.st`:

```
$ ANSIBLE_DEBUG=1 ansible -i 'some.ho.st,' -vvv --su --ask-su-pass all -m fetch -a "src=/etc/motd dest=/tmp/" &> experiment.12290
$ grep error experiment.12290
>>>/bin/sh: -c: line 0: syntax error near unexpected token `('
```

If you do **not** see the above error, then I would be very interested in seeing your `experiment.12290` file.

**Comment by amenonsen** [comment]
BTW, note that we should avoid issuing the checksum command altogether in copy/fetch if we're using become; it would save one completely unnecessary SSH connection. If this fix gets merged, I'll submit a separate PR for that one.

**Comment by mgedmin** [comment]
FWIW I can reproduce:

```
$ ansible --version
ansible 2.0.0 (devel 9b9fb51d9d) last updated 2015/11/18 11:45:05 (GMT +300)
  lib/ansible/modules/core: (detached HEAD b1c0249045) last updated 2015/11/18 11:45:09 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 7da1f8d4ca) last updated 2015/11/18 11:45:09 (GMT +300)
  config file = 
  configured module search path = Default w/o overrides

$ ANSIBLE_DEBUG=1 ansible -i 'fridge,' -vvv --su -R mg --ask-su-pass all -m fetch -a "src=/etc/motd dest=/tmp/" &> /tmp/experiment.12290

$ grep error /tmp/experiment.12290
>>>/bin/sh: 1: Syntax error: "(" unexpected
 15264 1447848952.78899: stdout=/bin/sh: 1: Syntax error: "(" unexpected

```

The command itself succeeds despite that error, and I find I have a /tmp/fridge/etc/motd file on my local machine.

**Comment by willthames** [comment]
```
 8679 1448343047.08197: Initial state: awaiting_prompt: <function detect_su_prompt at 0x7fc8b19499b0>
  8679 1448343049.07617: stdout chunk (state=0):
>>>/bin/sh: -c: line 0: syntax error near unexpected token `('^M
/bin/sh: -c: line 0: `su  root -c "/bin/sh -c 'echo BECOME-SUCCESS-xdlntdlwfpzbmlvdorjevbxswtkbrvls; rc=flag; [ -r /etc/motd ] || rc=2; [ -f /etc/motd ] || rc=1; [ -d /etc/motd ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/etc/motd && exit 0; (python -c '"'"'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1();'^M
<<<
  8679 1448343049.08505: stdout chunk (state=0):
>>><<<
  8679 1448343049.08519: command execution done: rc=1
  8679 1448343049.08524: stdout=/bin/sh: -c: line 0: syntax error near unexpected token `('^M
/bin/sh: -c: line 0: `su  root -c "/bin/sh -c 'echo BECOME-SUCCESS-xdlntdlwfpzbmlvdorjevbxswtkbrvls; rc=flag; [ -r /etc/motd ] || rc=2; [ -f /etc/motd ] || rc=1; [ -d /etc/motd ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/etc/motd && exit 0; (python -c '"'"'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1();'^M
, stderr=
  8679 1448343049.08528: done with _low_level_execute_command() (/bin/sh -c 'su  root -c "/bin/sh -c '"'"'echo BECOME-SUCCESS-xdlntdlwfpzbmlvdorjevbxswtkbrvls; rc=flag; [ -r /etc/motd ] || rc=2; [ -f /etc/motd ] || rc=1; [ -d /etc/motd ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/etc/motd && exit 0; (python -c '"'"'"'"'"'"'"'"'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1();
```
