### ISSUE TITLE
winrm: connection port/schema hardwired

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#12304]
##### Issue Type:

Bug Report
##### Ansible Version:
- 2.0
- 1.9.x
##### Summary:

in https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connections/winrm.py#L86 it is defined that http can only be used if port is 5985. You can not use http connection on a different port.

Although SSL should preferred, this hardwiring should be avoided. There is NAT (e.g. for vagrant, cloud), where other ports must be used for connection.
##### Expected Results:

there should be an option for specifing if ssl should be used or not. E.g.

http on default port

```
ansible_connection: winrm-nonssl
```

http on 55985

```
ansible_ssh_port: 55985
ansible_connection: winrm-nonssl
```

https (default) on default port 5596

```
ansible_connection: winrm
```

**Comment by cchurch** [comment]
Will be addressed by https://github.com/ansible/ansible/pull/12054

**Comment by cchurch** [comment]
This issue has been resolved in v2 via https://github.com/ansible/ansible/pull/12054.

You can explicitly specify `ansible_winrm_scheme=http` or `ansible_winrm_scheme=https` to override the default behavior (http if 5985 else https).
