### ISSUE TITLE
set_fact blows away registered variables

### ISSUE THREAD

**Issue by neocortical** [ansible/ansible#12301]
Issue Type: bug report (or I am completely misunderstanding something)

Ansible version: 2 (devel branch)

This issue appears to have introduced by this commit: https://github.com/ansible/ansible/commit/56d7f3889d5550ab6dc105bdb48471d29f71446e

Description: When calling `set_fact` and creating a new variable with a value from a registered variable, the registered variable's value is replaced with "VARIABLE IS NOT DEFINED!". 

The following playbook reproduces the issue: 

``` yaml

---

- 
  hosts: localhost
  connection: local
  gather_facts: False
  vars: 
    bar: baz
  tasks:

    - name: register a var
      debug: var=bar
      register: foo

    - name: inspect foo var
      debug: var=foo

    - name: Set a fact
      set_fact: qux="{{ foo.bar }}"

    - name: inspect qux
      debug: var=qux

    - name: foo var no longer exists
      debug: var=foo
```

Expected behavior: Prior to commit 56d7f38, the output is as expected: 

```
PLAY ***************************************************************************

TASK [register a var] **********************************************************
ok: [localhost] => {
    "bar": "baz", 
    "changed": false
}

TASK [inspect foo var] *********************************************************
ok: [localhost] => {
    "changed": false, 
    "foo": {
        "_ansible_verbose_always": true, 
        "bar": "baz", 
        "changed": false
    }
}

TASK [Set a fact] **************************************************************
ok: [localhost]

TASK [inspect qux] *************************************************************
ok: [localhost] => {
    "changed": false, 
    "qux": "baz"
}

TASK [foo var no longer exists] ************************************************
ok: [localhost] => {
    "changed": false, 
    "foo": {
        "_ansible_verbose_always": true, 
        "bar": "baz", 
        "changed": false
    }
}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0  
```

Observed behavior: From 56d7f38 on, the output is: 

```
PLAY ***************************************************************************

TASK [register a var] **********************************************************
ok: [localhost] => {
    "bar": "baz", 
    "changed": false
}

TASK [inspect foo var] *********************************************************
ok: [localhost] => {
    "changed": false, 
    "foo": {
        "_ansible_verbose_always": true, 
        "bar": "baz", 
        "changed": false
    }
}

TASK [Set a fact] **************************************************************
ok: [localhost]

TASK [inspect qux] *************************************************************
ok: [localhost] => {
    "changed": false, 
    "qux": "baz"
}

TASK [foo var no longer exists] ************************************************
ok: [localhost] => {
    "changed": false, 
    "foo": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0  
```

Environment: Mac OS X Yosemite, Python 2.7.10

**Comment by jimi-c** [comment]
@neocortical set_fact always had the ability to override registered variables (see #8758 for instance, where that was broken). I believe this is broken somewhere else in the code since that change.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by neocortical** [comment]
Thanks for the fast turnaround! Verified that devel/HEAD is now working as expected for me.

To be clear, I wasn't trying to overwrite a registered variable, only read it into another variable using set_fact. But problem solved in any case.
