### ISSUE TITLE
Question about inventory

### ISSUE THREAD

**Issue by Samuel1989** [ansible/ansible#12321]
Hi all,

I have a quick question about the Ansible inventory that I am hoping someone is able to answer.

I am having a small issue with inventory vars, in my inventory I have something like the following:

```
[instance1]
192.168.1.1

[instance1:vars]
url=http://instance1.co.uk
var=hello2

[instance2]
192.168.1.1

[instance2:vars]
url=http://instance2.co.uk
var=hello2
```

The issue I am experiencing is that the "instance2" variables are being applied to both instance1 and instance2 (assuming because they share the same hardware?)

Is this intended behaviour? Or is what I am trying to achieve perfectly reasonable? Does anyone have any recommendations on this?

I am using Ansible v1.9.1.

Any help would be greatly appreciated.

Thank you,
Sam

**Comment by srgvg** [comment]
Yes, this is intended behaviour. A host inherits all variables from the groups he is member of.
A better place for question is BTW the mailing list.

**Comment by Samuel1989** [comment]
Thanks @srvg 

I will ask on the mailing list if there are anyways I can achieve the above.

Sam

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
