### ISSUE TITLE
Basic Authentication failed for windows(Server 2012) on centos(Ansible control machine)

### ISSUE THREAD

**Issue by jugalporwal** [ansible/ansible#12324]
<192.168.199.93> ESTABLISH WINRM CONNECTION FOR USER:  on PORT 5986 TO 192.168.199.93
<192.168.199.93> WINRM CONNECT: transport=plaintext endpoint=https://192.168.199.93:5986/wsman
<192.168.199.93> WINRM CONNECTION ERROR: 401 Unauthorized. basic auth failed
192.168.199.93 | FAILED => 401 Unauthorized. basic auth failed

my windows.yaml file
ansible_ssh_user: Administrator@DOMAIN_NAME.COM
ansible_ssh_pass: some_password
ansible_ssh_port: 5986
ansible_connection: winrm

Using ansible 1.9.2

**Comment by vladimirmartsul** [comment]
Try this two things:
1) Remove "_@ETBDENVER.com_" from `ansible_ssh_user`
2) Quote all values (ex `ansible_ssh_pass: 'ETBd0m@in'`)

**Comment by jugalporwal** [comment]
@vladimirmartsul  Nope..doesnt work
ansible_ssh_user: 'Administrator'
ansible_ssh_pass: 'some_password'
ansible_ssh_port: '5986'
ansible_connection: 'winrm'

**Comment by jhawkesworth** [comment]
Unless your password contains characters that have a special meaning in yaml, I think quoting all of the values is unnecessary (although probably not going to do any harm).

Getting a 401 is a good sign - you've connected to the winrm service.

I suggest checking the event log to see why your login has failed.  Most obvious reason would be incorrect password for the username.  Bear in mind with the @ some domain you are attempting to connect as a local user which must already exist on that machine (Unlikely for their not to be a user called Administrator, but perhaps your Administrator domain password differs from the local Administrator password.

By the way, this strikes me as more of a 'user question' than necessarily a bug - in future can I suggest asking on the ansible project mailing list or the IRC channel - there are probably more people who can help there than who monitor the ansible bug reports.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
