### ISSUE TITLE
Windows 2012 server authectication fails from CentOS machine

### ISSUE THREAD

**Issue by jugalporwal** [ansible/ansible#12326]
<192.168.199.93> ESTABLISH CONNECTION FOR USER: 
<192.168.199.93> REMOTE_MODULE win_ping
<192.168.199.93> EXEC sshpass -d6 ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=5986 -o GSSAPIAuthentication=no -o PubkeyAuthentication=no -o User= -o ConnectTimeout=60 192.168.199.93 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1441976408.11-34771582076000 && echo $HOME/.ansible/tmp/ansible-tmp-1441976408.11-34771582076000'
EXEC previous known host file not found for 192.168.199.93
192.168.199.93 | FAILED => SSH Error: Connection timed out during banner exchange
    while connecting to 192.168.199.93:5986
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

ansible 1.9.2
windows.yaml file : 
nsible_ssh_user: 'Administrator'
ansible_ssh_pass: 'secretpassword'
ansible_ssh_port: '5986'
anisble_connection: 'winrm'

**Comment by jhawkesworth** [comment]
try renaming your windows.yaml to 
windows.yml and changing the contents to be as follows:

ansible_ssh_user: Administrator
ansible_ssh_pass: secretpassword
ansible_ssh_port: 5986
ansible_connection: winrm

you have a couple of typos in the file and possibly the .yaml name may be confusing things too.

At the moment ansible is trying to connect via ssh, which points to it not being able to understand your configuration.

**Comment by jugalporwal** [comment]
@jhawkesworth Thank u..!!There was an issue with the username and password i was using for accessing my windows server. It worked with the same .yaml file. Another simple and not so ansible question how do i subscribe to the ansible-project@googlegroups.com ?i tried to post my question there considering that it is a public group but it was not delivered

**Comment by jhawkesworth** [comment]
@jugalporwal You are welcome.

I think you need to log in with a google account in order to post to any google group.  If I recall, first posts to these lists are moderated so might take a little while to be approved.

**Comment by jhawkesworth** [comment]
Please can you close this ticket now to keep the issue tracker up to date?

**Comment by jugalporwal** [comment]
ok Thank You once again.!!closing the ticket :)
