### ISSUE TITLE
Running playbook with multiple inventory files ignores vars

### ISSUE THREAD

**Issue by eaigner** [ansible/ansible#12338]
Assume 2 inventory files, `prod` and `test` residing in the `inventory/` directory looking like this

File `prod`

```
[proxies]
host1 ansible_ssh_host=123.456.789.100

[proxies:vars]
app_name=app
```

File `test`

```
[proxies]
host1 ansible_ssh_host=123.456.789.101

[proxies:vars]
app_name=app-test
```

When running a playbook with multiple inventory files like this

```
ansible-playbook proxies.yml -i inventory/
```

ansible will only use the variables of one inventory files, not the variables belonging to the specific inventory.

**Comment by srgvg** [comment]
It _does_ use the variables of everything under `inventory/`. However as your example defines the same variables on both places, only one value "wins" (Can't say which, but that is related to sort order etc.)

You define the same `host1` in both sub inventories. Variables from different groups a host is part of, are merged down.

I'm not even sure from your example what else you are expecting. You define the same groups and hosts in both files. Vars' values are different. Then you target the inventory containing both files. According to which logic should a specific "sub-inventory" be picked?

All in all, this is a classic misunderstanding on how inventory, groups and variables work. Variables are always calculated down onto the hosts, according to a certain precedence.

HTH,

**Comment by eaigner** [comment]
I don't see it as a classic misunderstanding, but just erroneous behavior. Why would I expect that context specific variables are merged with others that are clearly meant for another environment?

**Comment by eaigner** [comment]
If variables are grouped by just their names regardless of which file they reside in, I don't really understand what the point of multiple inventory files would be in the first place.

**Comment by srgvg** [comment]
What more can I say? It just doesn't work in the way you expect.

When you say you launch `ansible-playbook proxies.yml -i inventory/`, and looking at your example here. What exactly do you expect to happen? You target the group `proxies` which is defined in both file in `inventory/`. According to what logic should ansible pick one of those files?

(This is more a discussion for the mailing list. It's really not a bug.)

**Comment by eaigner** [comment]
Well I'd expect that ansible sees the group names as fully qualified like `prod.proxies` and `test.proxies`

**Comment by amenonsen** [comment]
That's just not how it works.

**Comment by eaigner** [comment]
Yep, apparently ;). But thanks for clarifying.
