### ISSUE TITLE
Allow modules without .py extension to override core modules.

### ISSUE THREAD

**Issue by cchurch** [ansible/ansible#12332]
Following #12330, need to implement 4b895f04e398deb9c156d4e8b6435073fc2e6f18 in a way that doesn't break Windows support.

> Fix order of loading of modules.
> 
> Allows ANSIBLE_LIBRARY to overload core modules even if the module in ANSIBLE_LIBRARY doesn't have a .py extension.

**Comment by jimi-c** [comment]
Closing as this has been resolved by https://github.com/ansible/ansible/pull/12420.
