### ISSUE TITLE
[Bug report] Permission error with become_user

### ISSUE THREAD

**Issue by aruhier** [ansible/ansible#12340]
> Ansible version: 2.0 commit f0efe1ecb0c7c0f3966a1950bbc94e792b12d3d2
> OS: ArchLinux, up to date
> Ansible configuration: not changed

Hello,
When I use the become_user directive, I get a permission error:

> "msg": "Source /tmp/ansible-tmp-1442167195.81-61742141891521/source not readable" 

I'm running my playbook as root, and then I su as a normal user for some specific tasks. For example:

```
- name: copy public ssh key for gitolite for pkgbuild user
  become_user: pkgbuild
  copy:
    content="{{ ssh_keys["gitolite_global"]["public"] }}"
    dest="~/.ssh/gitolite_global.pub"
```

The problem is that file `/tmp/ansible-tmp-1442167195.81-61742141891521/source` has the 600 permission for the root user, so the user pkgbuild can not read it. I tried with the 1.9 version, what is working without any issue.

Thanks !

**Comment by Kr08ti** [comment]
Hi,
If you are trying to copy the public ssh key from your root user to "pkgbuild user",  you don't need to become that user. Since you are running your playbook as root, u have all the privileges over other users.
A much easier way to copy the public ssh key is:

```
- name: Copy the public ssh key for gitolite for pkgbuild user
  copy: src=~/.ssh/gitolite.pub dest="/home/pkgbuild/~/.ssh/gitolite_global.pub"  owner=gitolite group=gitolite mode=644
```

Hopefully this will solve the issue which you are facing.
Thanks !

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

In any case, you need to have `become: True` in the task as having become_user alone does not trigger privilege escalation.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
