### ISSUE TITLE
[bug] Ansible evaluates 'with_items' argument even if 'when: false'

### ISSUE THREAD

**Issue by mearsten** [ansible/ansible#12344]
Bug Report.
##### Ansible Version:

> ansible 2.0.0 (devel f0efe1ecb0) last updated 2015/09/14 03:19:53 (GMT +300)
>   lib/ansible/modules/core: (detached HEAD 4de4bd0be6) last updated 2015/09/14 03:19:58 (GMT +300)
>   lib/ansible/modules/extras: (detached HEAD ea1bd0b078) last updated 2015/09/14 03:20:02 (GMT +300)
>   config file = /etc/ansible/ansible.cfg
>   configured module search path = None
##### Ansible Configuration:

/etc/ansible/ansible.cfg is completely identical to one from github.
##### Environment:

Ubuntu 14.04.3 LTS (amd64)
##### Summary:

Ansible evaluates the value of 'with_items' even if the argument of 'when' is false.
##### Steps To Reproduce:

<pre>
# cat playbook.yml
- hosts: localhost
  vars:
    - var1:
        some_key:
          - item1
          - item2
    - var2: 'nonexistent_key'

  tasks:
    - debug: msg="this is going to be skipped"
      when: false
      with_items: "{{ var1[var2] }}"
</pre>

Just run that playbook

<pre>% ansible-playbook playbook.yml</pre>

##### Expected Results:

The task should be skipped successfully. Argument of 'with_items' should not be evaluated at all.
##### Actual Results:

On latest Ansible I get a warning. And it says that task has been skipped due to wrong reason.

<pre>
% ansible-playbook playbook.yml
    # .... skipped ....
TASK [debug msg=this is going to be skipped] ***********************************
[DEPRECATION WARNING]: Skipping task due to undefined attribute, in the future this will be a fatal error.. This feature will be removed in a future release. Deprecation warnings can be disabled by setting
 deprecation_warnings=False in ansible.cfg.
skipping: [localhost]
    # .... skipped ....
</pre>

On Ansible 1.9.3 I get an error:

<pre>
% ansible-playbook playbook.yml
    # .... skipped ....
TASK: [debug msg="this is going to be skipped"] ******************************* 
fatal: [localhost] => with_items expects a list or a set

FATAL: all hosts have already failed -- aborting
</pre>

**Comment by sivel** [comment]
This is expected as the when statement is applied to each iteration of the task when using with_items as opposed to the declaration of the task.

**Comment by Oliboy50** [comment]
Then what is the right way of doing this now:

```
- name: Create mysql databases
  mysql_db: name={{ item.name }} state=present
  with_items: mysql.databases
  when: mysql.databases is defined
```

**Comment by sivel** [comment]
The correct way to handle this is to get rid of the `when` statement and replace the `with_items` statement with the following:

```
with_items: mysql.databases|default([])
```

In the above the `default` filter will default the value to an empty list, effectively making it iterable but with no elements to iterate over.

**Comment by Oliboy50** [comment]
exactly what I've done, thanks for the answer

**Comment by thmshmm** [comment]
What if mysql is undefined? I get a deprecation warning.

**Comment by ghost** [comment]
`with_items: mysql.databases|default([])`

This info really should be in the loops docs, just happened across this by chance and its helped me no end.

**Comment by bcoca** [comment]
it is in the conditional docs, which are listed first.
http://docs.ansible.com/ansible/playbooks_conditionals.html#loops-and-conditionals
