### ISSUE TITLE
PIP Install Fails on OSX

### ISSUE THREAD

**Issue by djallits** [ansible/ansible#12354]
OSX 10.10.5
Xcode 6.4 (6E35b)
CLT Path: /Applications/Xcode.app
Python v2.7
PIP v7.1.2
Ansible v1.9.3

```
sudo easy_install pip
sudo CFLAGS=-Qunused-arguments CPPFLAGS=-Qunused-arguments pip install ansible
```

Error Message:

Command "/usr/bin/python -c "import setuptools, tokenize;**file**='/private/tmp/pip-build-Ohvx9N/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-fVWI2H-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-Ohvx9N/pycrypto

**Comment by djallits** [comment]
Resolved. Apple Xcode Command Line tools have to be installed from the command line and not from the Xcode GUI by running `xcode-select --install`

**Comment by jideshv** [comment]
After installing the xcode command line tools you now also have to accept the apple license agreement.

I found the easiest way to do this is run `sudo gcc` and follow the instructions.

**Comment by OddEssay** [comment]
I had a slightly different fix for this: Another user on the same Mac had been using Xcode, which appeared to have changed some config options for the system. Using the `xcode-select --reset` command fixed it and I was then able to install with pip fine.
