### ISSUE TITLE
register: does not handle YAML arrays

### ISSUE THREAD

**Issue by isotopp** [ansible/ansible#12367]
Trying to register multiple variables in YAML array syntax:

 kk:playbooks kris$ cat p.yml
    # vim:ft=ansible:
    - hosts: server
      user: root

```
  tasks:
    - name: test something
      command: echo test
      register:
        - a
        - b

    - debug: var=a

    - debug: var=b
```

This explodes:

```
kk:playbooks kris$ ansible-playbook  p.yml

PLAY [server] *****************************************************************

TASK: [test something] ********************************************************
changed: [server]
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.9.3/libexec/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/Cellar/ansible/1.9.3/libexec/bin/ansible-playbook", line 264, in main
    pb.run()
  File "/usr/local/Cellar/ansible/1.9.3/libexec/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 348, in run
    if not self._run_play(play):
  File "/usr/local/Cellar/ansible/1.9.3/libexec/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 789, in _run_play
    if not self._run_task(play, task, False):
  File "/usr/local/Cellar/ansible/1.9.3/libexec/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 540, in _run_task
    _register_play_vars(host, result)
  File "/usr/local/Cellar/ansible/1.9.3/libexec/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 514, in _register_play_vars
    utils.update_hash(self.VARS_CACHE, host, {task.register: result})
TypeError: unhashable type: 'list'
```

It is the type that makes it explode, that is

```
register: [ a ]
```

is already sufficient to make it blow.

```
kk:playbooks kris$ cat q.yml
# vim:ft=ansible:
- hosts: server
  user: root

  tasks:
    - name: test something
      command: echo test
      notify:
        - one
        - two

  handlers:
    - name: one
      command: echo one

    - name: two
      command: echo two
```

works just as expected, so I'd expect duplicating the parameter handling from handlers in register would fix the problem.

Related to #12364

**Comment by amenonsen** [comment]
Register doesn't (and never did) take a list of variables. Where did you get the idea that this would work?

**Comment by isotopp** [comment]
I know that this is currently not valid syntax. Yet, there are still two problems here, which need to be addressed:

a. This must not stacktrace, but handled with a proper error message.
b. Optionally it would be useful to be able to register more than one variable in order to do stuff with it.

The b case has been suggested in https://plus.google.com/+OlufLorenzen/posts/PiEfCRQu9wg (my answer points the person asking the question into the direction of handlers, which in this particular case are generally more suitable, but it still is an annoying limitation that you can only register one variable).

**Comment by amenonsen** [comment]
As for (a), it doesn't die with a backtrace in devel (but what it actually does isn't very useful: none of the variables are defined afterwards).

**Comment by jimi-c** [comment]
As @amenonsen noted above, this was silently not blowing up in devel, so I've gone ahead and merged in the above patch to correct this.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
