### ISSUE TITLE
Second "register:"/"when:" task unregisters variable from first task

### ISSUE THREAD

**Issue by athompso** [ansible/ansible#12364]
I have a playbook where I need to find out if "xinetd" is already running or not, as I do not want to restart it, only reload it if it's already running.  So I created this:

```
 74   - name: check if xinetd is already running (non-Debian)
 75     shell: service xinetd status
 76     when: ansible_system == "Linux" and ansible_os_family != "Debian"
 77     register: xinetd_running
 78     changed_when: 0 == 1
 79     ignore_errors: yes
 80 
 81   - name: check if xinetd is already running (Debian)
 82     shell: ps ax | grep -q xinetd
 83     when: ansible_system == "Linux" and ansible_os_family == "Debian"
 84     register: xinetd_running
 85     changed_when: 0 == 1
 86     ignore_errors: yes
 87 
 88   - name: reload xinetd configuration
 89     service: name=xinetd state=reloaded
 90     when: ansible_system == "Linux" and xinetd_running.rc != '0'
 91 
 92   - name: start xinetd
 93     service: name=xinetd state=enabled 
 94     when: ansible_system == "Linux" and xinetd_running.rc == '0'
```

Much to my surprise, this always fails on non-Debian systems, because the second task, although fenced with "when: Debian", actually _unregisters_ `xinetd_running` instead of merely being a no-op.

Please either fix the behaviour, or document it.  I spent over an hour trying to figure out what on earth I was doing wrong.  (Someone already opened another issue about improving the error message, which presumably would have shortened the troubleshooting time considerably...)

**Comment by bcoca** [comment]
fixed via ~~3e49c1e365490106c61e20e35d486e9de064ec02~~ 43ea5f0853f95024d273c118de90a8b654f330b5

**Comment by Finkregh** [comment]
I cant find that commit https://github.com/ansible/ansible/commit/3e49c1e365490106c61e20e35d486e9de064ec02 :(

**Comment by bcoca** [comment]
corrected
