### ISSUE TITLE
Documentation need clarification wrt ansible_ssh_* hostvars

### ISSUE THREAD

**Issue by TimJones** [ansible/ansible#12394]
In the [Inventory](http://docs.ansible.com/ansible/intro_inventory.html) document page, it lists `ansible_ssh_args` and `ansible_ssh_extra_args` as supported hostvars that change the behaviour of the SSH connection. I was developing a dynamic inventory script to take advantage of these until I discovered that setting them did nothing, looked into the code of ansible and a few PRs to see that these are v2.0 features not yet available.

The documentation really should be updated to reflect that these are currently unsupported in any official release.

**Comment by dmkc** [comment]
+1

**Comment by bcoca** [comment]
There is note just above http://docs.ansible.com/ansible/intro_inventory.html#host-variables that documents that. closing via 32cb2fa21536ae23ba15a1a3dd0e7a3b552036b3
