### ISSUE TITLE
[bug] get_file_parser() takes exactly 2 arguments (2 given)

### ISSUE THREAD

**Issue by jshrake** [ansible/ansible#12403]
This recent commit https://github.com/ansible/ansible/commit/c8f2483d6d3ff6ef4aedc2572e287539dbb73a0b#diff-614654ef35f5425c0270de89e92b1bedL37 requires updating the call site at
https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/dir.py#L112

**Comment by jimi-c** [comment]
@jshrake see my comment on the code below yours - looking at that line in source now that has been corrected already. Please confirm if you're still seeing the problem.

Thanks!

**Comment by jshrake** [comment]
Resolved by https://github.com/ansible/ansible/commit/ee840f302935022c950a026e006591e6c43d71ca

**Comment by jimi-c** [comment]
Ahh good, @bcoca got it already. Thanks!
