### ISSUE TITLE
synchronize uses wrong SSH user

### ISSUE THREAD

**Issue by jonashaag** [ansible/ansible#12413]
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.3
##### Ansible Configuration:

Inventory:

```
[hosts]
MY_HOST ansible_connection=ssh ansible_ssh_user=MY_REMOTE_USER ansible_python_interpreter=python2
```
##### Environment:

Tested with: OS X client, Arch Linux host and Ubuntu 12.04 client, Debian 7 host
##### Summary:

The synchronize module takes the wrong SSH user into account for the destination specification passed to rsync. The client's username is taken instead of the host's username.

The code lines responsible for this are https://github.com/ansible/ansible/blob/5d67420df042f052c2cd79b7d41983e4759ee50b/lib/ansible/runner/action_plugins/synchronize.py#L161-L162. A dump of the `inject` dict can be found here: https://gist.github.com/jonashaag/9452e60baee13d4ddbaa. (`"j"` is the client user.) It looks to my like `inject['hostvars']['ansible_ssh_user']` should be taken, not `inject['ansible_ssh_user']`.
##### Steps To Reproduce:

```
$ ansible -i inventory all -m synchronize -vvvv -a "src=MY_SRC dest=MY_DEST"
```
##### Expected Results:

Rsync command should be

```
"rsync ... \"MY_SRC\" \"MY_REMOTE_USER@MY_HOST:MY_DEST\""
```
##### Actual Results:

Rsync command is

```
"rsync ... \"MY_SRC\" \"j@MY_HOST:MY_DEST\""
```

Full debug output:

```
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1442478957.19-94834020006991 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1442478957.19-94834020006991 && echo $HOME/.ansible/tmp/ansible-tmp-1442478957.19-94834020006991']
<127.0.0.1> PUT /var/folders/s9/x8z3gqmx2xqbhkfh2_3l4sfr0000gn/T/tmpy7AWnI TO /Users/j/.ansible/tmp/ansible-tmp-1442478957.19-94834020006991/synchronize
<127.0.0.1> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /private/tmp/env/bin/python2.7 /Users/j/.ansible/tmp/ansible-tmp-1442478957.19-94834020006991/synchronize; rm -rf /Users/j/.ansible/tmp/ansible-tmp-1442478957.19-94834020006991/ >/dev/null 2>&1']
MY_HOST | FAILED >> {
    "cmd": "rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no -o Port=XXXXX' --out-format='<<CHANGED>>%i %n%L' \"MY_SRC\" \"j@MY_HOST:MY_DEST\"",
    "failed": true,
    "msg": "Permission denied (publickey).\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at /SourceCache/rsync/rsync-45/rsync/io.c(453) [sender=2.6.9]\n",
    "rc": 255
}
```

**Comment by zhoufeng1989** [comment]
I got the same problem, set `remote_user` in ansible config file solve this.
see docs. http://docs.ansible.com/ansible/intro_configuration.html#remote-user

**Comment by dhbaird** [comment]
Issue is impacting me.

**Comment by dhbaird** [comment]
The workaround suggested by @zhoufeng1989 worked for me.

**Comment by tima** [comment]
This report is for a version of Ansible before 2.0. The synchronize module, action plugin and core engine was re-written at that time. If you are still experiencing this error with the latest stable version of Ansible, please resubmit with updated information using the standard issue guidelines. 

Thanks.

wontfix
