### ISSUE TITLE
using variables in delegate_to does not work

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#1241]
I'm using delegate_to with a variable in the playbook pasted hereafter.
I upgraded to the last commit as per an hour ago, which includes the code that allows for variables in the delegate_to stanza, alas, that does not seem to work:
###### # Playbook snippet

  tasks:
- name: get peer name
  local_action: shell bash -c 'H=${ansible_hostname} && [ ${H#${H%?}} = 1 ] && echo ${H/%-1/-2} || echo ${H/%-2/-1}'
  register: my_peer_name
- name: Get Public Key
  action: shell cat ~/.ssh/id_rsa.pub
  register: public_key
- name: Add Public Key to peer server
  action: authorized_key user=root key=${public_key.stdout}
  delegate_to: ${my_peer_name.stdout}-mgt.mmis.be
  ###### # Playbook snippet

Note, I'm using the ${my_peer_name.stdout} variable in other places, where it works flawlessly.
###### # Error

TASK: [Add Public Key to peer server] ********************\* 
<${my_peer_name.stdout}-mgt.mmis.be> ESTABLISH CONNECTION FOR USER: root
fatal: [nme-inventaris-pr-2-mgt] => {'msg': 'FAILED: [Errno -2] Name or service not known', 'failed': True}

**Comment by mpdehaan** [comment]
Looks like it worked fine to me, just that you don't have a host there.

It tried to contact a host named:   nme-inventaris-pr-2-mgt

If it did not work, I would have expected it try to contact:

"${my_peer_name.stdout}-mgt.mmis.be"

**Comment by srgvg** [comment]
nme-inventaris-pr-2-mgt is the host the play is running against
the said variable refers to nme-inventaris-pr-1, hence delegating to nme-inventaris-pr-1-mgt.mmis.be

both hosts are available and referenced in the hosts file

**Comment by jpalley** [comment]
Currently - as far as I understand the ansible internals - the delegate_to variable substitution is happening when the task is loaded.  Thus, the delegate_to does not substitute a "registered" variable.

I suppose we need to update the runner to also do the substitution at that point to make the behavior consistent?

I am not at a coding computer to do this right these days, but can later.

**Comment by mpdehaan** [comment]
yeah, that sounds like it exactly.

We can just do the replacements later instead of earlier.

**Comment by jpalley** [comment]
I think I put it in tasks.py because I saw first saw the action and name substitution happening there (which I assume was where substitution was happening before "register"). 

Those substitutions (name/action) are still there.  I assume they're superfluous as well and should be deleted?

**Comment by mpdehaan** [comment]
I would probably leave them and just also replace them later, in case some
API consumer finds them useful.

Templates are pretty low cost.

What is being done above is a bit of an edge case anyway.

**Comment by mpdehaan** [comment]
@jpalley any progress?

**Comment by mpdehaan** [comment]
fixed in c16572b for 0.8

**Comment by srgvg** [comment]
Tested and approved, thx!
