### ISSUE TITLE
Ansible fails to load Yaml file with equal-sign as value

### ISSUE THREAD

**Issue by sascha-egerer** [ansible/ansible#12412]
Ansible fails when loading a Yaml file like this:

``` yml
--- 
  foo: 
    - =
```

The Yaml file is valid (see http://www.yamllint.com/) but ansible fails with `ERROR: Syntax Error while loading YAML script ...`

Putting quotes around the equal-sign works but i can't do that in my case as this file will be generated by a Yaml parser. So using a workaround is not an option.

**Comment by jimi-c** [comment]
@sascha-egerer that may be valid YAML per the spec, however PyYAML is what is blowing up on this (not our code), so I'm not sure what we can do in this case.

**Comment by sascha-egerer** [comment]
I already thought about that. But looks like the PyYAML Project is very inactive... 
Ah just found a corrosponding issue in the PyYAML tracker. http://pyyaml.org/ticket/140

**Comment by jimi-c** [comment]
@sascha-egerer ok, since this is an upstream issue, I'll go ahead and close this. As you noted, really the only way around this for now is to quote that line, so I'd look to your YAML output method to see if there is an option to force quoting strings.

Thanks!

**Comment by sascha-egerer** [comment]
Yes thanks. Just noted the the bug tracker has been moved to bitbucket. I've created a new bug report there. https://bitbucket.org/xi/pyyaml/issues/49/plain-equal-sign-as-node-content-results
