### ISSUE TITLE
Cannot trigger handler with variable in name

### ISSUE THREAD

**Issue by pmahoney** [ansible/ansible#12427]
##### Issue Type:

Bug Report
##### Ansible Version:

2.0.0-0.2.alpha2
##### Ansible Configuration:

```
$ ansible-playbook --version
ansible-playbook 2.0.0
  config file = 
  configured module search path = None
```
##### Environment:

Running ansible on OS X 10.10
##### Summary:

I'm trying to parameterize a role for managing a number of very similar deployments. The role's tasks trigger a restart handler, which is identical for each deployment except for the name of the app. [This comment](https://github.com/ansible/ansible/issues/4853#issuecomment-28719258) implies it is possible to include a variable in the name of a handler. However, with Ansible 2.0.0-0.2.alpha2 I am unable to successfully trigger the handler with a variable in its name.
##### Steps To Reproduce:

Example files:

```
$ find ./ -type f | while read f; do printf "\n# file %s\n" "$f"; cat "$f"; done

# file ./inventory
[webservers]
remotehost

# file ./roles/param/handlers/main.yml
- name: "restart {{ app }}"
  shell: "echo restarting {{ app }}"

- name: echo test
  shell: "echo test"

# file ./roles/param/tasks/main.yml
- name: "install {{ app }}"
  shell: "echo installing {{ app }}"
  notify:
    - "restart {{ app }}"
    - echo test

# file ./roles/param/vars/main.yml

---
app: changeme

# file ./site.yml

---
- include: webservers.yml

# file ./webservers.yml

---
- hosts: webservers
  roles:
    - role: roles/param
      app: app1
    - role: roles/param
      app: app2
```

Modify the inventory file as appropriate, then run:

```
$ ansible-playbook -i inventory site.yml 
```
##### Expected Results:

I expect the following handlers to be run: `echo test`, `restart app1`, `restart app2`.
##### Actual Results:

However, only the (statically named) `echo test` is run:

```
$ ansible-playbook -i inventory site.yml 

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [remotehost]

TASK [param : install app1] ****************************************************
changed: [remotehost]

TASK [param : install app2] ****************************************************
changed: [remotehost]

RUNNING HANDLER [param : echo test] ********************************************
changed: [remotehost]

PLAY RECAP *********************************************************************
remotehost                 : ok=4    changed=3    unreachable=0    failed=0   
```
- Is this technique supported?
- If so, did I misconfigure something?

Thanks,
Patrick

**Comment by pmahoney** [comment]
I tested this behavior in 1.9.3, and I _am_ able to trigger the handler with variable in name:

```
TASK: [roles/param | install app1] ******************************************** 
changed: [remotehost]

TASK: [roles/param | install app2] ******************************************** 
changed: [remotehost]

NOTIFIED: [roles/param | restart app1] **************************************** 
changed: [remotehost]

NOTIFIED: [roles/param | echo test] ******************************************* 
changed: [remotehost]

NOTIFIED: [roles/param | restart app2] **************************************** 
changed: [remotehost]

PLAY RECAP ******************************************************************** 
remotehost                 : ok=6    changed=5    unreachable=0    failed=0   
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
