### ISSUE TITLE
ansible's setup module returns ansible_virtualization_role = host on XEN domU domain but should return guest value

### ISSUE THREAD

**Issue by czytom** [ansible/ansible#1242]
If I run ansible -m setup on xen domU I got: ansible_virtualization_role = host
If I run ansible -m setup on xen dom0 I got also: ansible_virtualization_role = host

The difference is that on domU /proc/xen/capabilites is empty and on dom0 there is control_d value.

**Comment by mpdehaan** [comment]
Here's the code that sets that currently (in library/setup), a patch to fix it would be welcome.  I don't have a Xen machine around to test on at the moment.

```
  if os.path.exists("/proc/xen"):

        self.facts['virtualization_type'] = 'xen'

        if os.path.exists('/proc/xen/capabilities'):

            self.facts['virtualization_role'] = 'host'

        else:

            self.facts['virtualization_role'] = 'guest'
```

**Comment by mpdehaan** [comment]
Here's the code that sets that currently (in library/setup), a patch to fix
it would be welcome.  I don't have a Xen machine around to test on at the
moment.

```
  if os.path.exists("/proc/xen"):
        self.facts['virtualization_type'] = 'xen'
        if os.path.exists('/proc/xen/capabilities'):
            self.facts['virtualization_role'] = 'host'
        else:
            self.facts['virtualization_role'] = 'guest'
```

On Fri, Oct 5, 2012 at 11:10 AM, Krzysztof Tomczyk <notifications@github.com

**Comment by mpdehaan** [comment]
I'm not working on this.  Send me a patch?

**Comment by arrfab** [comment]
Update : i've just created a Pull-request for that issue : https://github.com/ansible/ansible/pull/1542
