### ISSUE TITLE
Ansible - how can I use states for this problem

### ISSUE THREAD

**Issue by Robby123** [ansible/ansible#12439]
I am running ansible with multiple windows hosts, the playbook I am using contains several tasks. Sometimes one of the tasks fails on some of the hosts - how can I run the playbook again so that it only executes tasks if they failed the time before?

Can states be used?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
