### ISSUE TITLE
pcrypto pip install on OS X Yosemite

### ISSUE THREAD

**Issue by NathanDotTo** [ansible/ansible#12454]
CC=clang sudo -E pip install pycrypto

I had to use the command above to install pycrypto on OS X Yosemite. It might be useful to note that here: http://docs.ansible.com/ansible/intro_installation.html

Regards

Nathan

**Comment by jimi-c** [comment]
Hi @NathanDotTo, go ahead and send us a PR to update that, but for now I'm going to close this as it's not really an Ansible issue.

Thanks!

**Comment by NathanDotTo** [comment]
Apologies for the delay, PR created.

https://u1890311.ct.sendgrid.net/wf/click?upn=6AA-2Fr2t-2Fy7YZ08UxW-2F09Z0H4PUBmh0iElZPtPBxECr9HkNpgkn5UnHqQX69AMsuSClXX-2FuUWZEfIgqMUQjG66w-3D-3D_s5UH8bhnBaopYjthcNSRcfied-2F6Ca9EvsG7a7LQj4eJlC-2FR55oNGjPdcppzWD-2FyTfOGS9sq-2Fw8P-2FwFLtego0VpIDT2I723q-2FVN1Gs5XhoGjuJmYNfJ2ycEO3UrAjiUnq4XFyH5t1oILD3uov-2BVS-2BTeQ6eVAotrTis3YPiamp4pg0e2EUaOFjoSQEI5XFXwNmj2xAfOEiWk3sXHNdmYePw9E-2BZKZwRKsdShLS9jNmoyAETiV22ov9tEqx2alXv9NVHPYlrTDcbo0Zbu9UQ6LJmfsiMmHOsEmgANQSLmzwhjvRFZzuO9zP2x2uByPx4aKQJCnjuMjqd0m1iOo09TXZPw-3D-3D

Regards

Nathan

> On 21 Sep 2015, at 18:02, James Cammarata notifications@github.com wrote:
> 
> Hi @NathanDotTo, go ahead and send us a PR to update that, but for now I'm going to close this as it's not really an Ansible issue.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Nathan John Sowatskey
Programmable Infrastructure, DevOps and SDN
nathan@nathan.to
www.linkedin.com/in/nathandevops
XMPP: nathandotto@im.koderoot.net
Google: nathanjohnsowatskey@gmail.com
Skype: nathan_sowatskey
Twitter: NathanDotTo
https://u1890311.ct.sendgrid.net/wf/click?upn=I8d8wtfIjxeRpasNC075ZdoV4WtpL0CRyE9EjXuOhGQncSh2pZGdm-2BGbx9dZnM26_s5UH8bhnBaopYjthcNSRcfied-2F6Ca9EvsG7a7LQj4eJlC-2FR55oNGjPdcppzWD-2FyTfOGS9sq-2Fw8P-2FwFLtego0VpIDT2I723q-2FVN1Gs5XhoGjuJmYNfJ2ycEO3UrAjiUnq4XFyH5t1oILD3uov-2BVS-2BTeQ6eVAotrTis3YPiamp4pg0e2EUaOFjoSQEI5XFXwNm-2FirSuLgI16U-2BuqNTk2zimr-2B5R4gApspvcr0Y9qhSnLYBgOsbCdyX1Dh3zWcDkDcZb-2BKPNgExfhGQgELC4thX96Uou9I6iPEeNt6J8r2YkHTvVslzpA-2FVL2Z6PRXNLBZIbE3pwoiLQ6yURTrniIwHGg-3D-3D

**Comment by NathanDotTo** [comment]
Changed the text to indicate that the dependency is from paramiko.

Regards

Nathan
