### ISSUE TITLE
make host_vars and group_vars accessible to /usr/bin/ansible

### ISSUE THREAD

**Issue by mkmik** [ansible/ansible#1245]
Sometimes it's useful to be able to quickly run `ansible` and have the same per host variables available for ansible-playbook (in particular `ansible_python_interpreter` host var)

**Comment by mkmik** [comment]
Actually my problem is that `InventoryScript` doesn't allow parsing per host variables from the script json output.
I could bundle per host vars with the `hosts` script instead of relying on `host_vars`

**Comment by mpdehaan** [comment]
I am having trouble following, can you give me a detailed example?

**Comment by mkmik** [comment]
Sure, sorry:

given a `/etc/ansime/hosts` file which contains:

```
[mygroup]
oldhost
```

If I run:

```
ansible mygroup -m ping
```

I'll get:

```
oldhost | FAILED >> {
    "failed": true, 
    "msg": "Traceback (most recent call last):\r\n\n  File \"/var/tmp/ansible-1349554829.08-137644492505521/ping\", line 48, in ?\r\n\n    import simplejson as json\r\n\nImportError: No module named simplejson\r\n", 
    "parsed": false
}
```

Because  there is an old python installation on that machine.

---

Now, I found out that my setting the `ansible_python_interpreter` within the inventory file, like this:

```
[mygroup]
oldhost ansible_python_interpreter=/usr/bin/python2.6
```

it works:

```
oldhost | success >> {
    "ping": "pong"
}
```

(same thing with ansible-playbook)

---

Now, I wanted to generate my host list dynamically. I could generate my hosts file using a script,
but I really liked the idea that the hosts file could be a script itself, so I tried it out.

But, it turns out that when `hosts` is a script, ansible doesn't parse its output as the INI format, but as a json,
and you cannot encode variables in that json.

So, the doc says I could put per host variables in hosts_var/oldhost, so I  tried to put this content in `host_vars/oldhost`:

```
---
ansible_python_interpreter: /usr/bin/python2.6

```

Then I tried:

`ansible mygroup -m ping`

But I get the error message  stating that simplejson cannot be loaded.
I looked in the sources and saw that the `host_vars/*` files are loaded only in `lib/ansible/playbook/play.py`
so this means that they cannot be honored when running plain `ansible`.
(I also checked with strace, the `host_vars/oldhost` file is not opened)

This was my original bug report.

---

Then I realized that it didn't work even with `ansible-playbook pingtest.yml`

This time, I checked with strace, and the `host_vars/oldhost` is indeed opened:

```
stat("host_vars/oldhost", {st_mode=S_IFREG|0664, st_size=51, ...}) = 0
open("host_vars/oldhost", O_RDONLY) = 3
```

So, I have the feeling that in playbook mode this variable is loaded correctly, but probably it's applied too late in the process.

I guess that `ansible_python_interpreter` isn't designed to be overridable that way,
but that's probably the topic of another ticket.

I still believe that the behavior of `ansible` and `ansible-playbook` should be as possibly consistent with respect to how the inventory is parsed.

**Comment by mpdehaan** [comment]
Ok thanks.  I think I follow enough to understand how to reproduce.   Seems easy enough to track down.

Btw inventory scripts can set variables...

**Comment by mkmik** [comment]
> Btw inventory scripts can set variables..

ah good to know, I noticed now that the inventory script is called again to get vars for each host:

I logged the calls to the inventory script:

```
CALLED INVENTORY ['/home/marko/Projects/ansible-playbooks/hosts', '--list']
CALLED INVENTORY ['/home/marko/Projects/ansible-playbooks/hosts', '--host', 'oldhost']
```

thanks

**Comment by mpdehaan** [comment]
Previously we had not fixed this as host and group vars were implemented on top of the playbook API.  I think we can do this cleanly now in usr bin ansible by instead of using the Runner API, dynamically building a special one task play with the right callbacks so the output remains the same.  Will make things much simpler.

**Comment by mpdehaan** [comment]
slating for 0.9 as this is a mid-sized change close to the release date

**Comment by mpdehaan** [comment]
Conversation with @dhozac means I think we want to try to bring this under inventory code (not Runner) for 0.9.  Making a note so I don't forget.

**Comment by mpdehaan** [comment]
done!

**Comment by TomFrost** [comment]
Following up on this, as the 'done' here is a little misleading.

I have a similar use case, in that I'm using the included ec2.py plugin to generate my inventory.  That script makes groups for each of the keypairs that servers have been launched with, so group_vars is _incredibly_ convenient to specify the ansible_ssh_private_key_file for each keypair group.  That gives seamless and transparent access to the servers, without my entire dev team needing to add each key to their own personal ssh-agent.  I just check the keys into our ansible playbook repo with git-crypt, and we're done.

Problem is, with the latest master on Github, that works with ansible-playbook, but not ansible.  It would appear that group_vars is still not being processed when /usr/bin/ansible is invoked, which is what makes this closed ticket a little misleading.  We simply can't fire off one-off ansible commands without a lot of additional configuration on each individual dev machine.

Am I missing something? If not, it would be good to talk about adding this functionality.
