### ISSUE TITLE
GLPI support

### ISSUE THREAD

**Issue by camlafit** [ansible/ansible#12466]
Hi

I've developed an inventory script to get data from [glpi](http://www.glpi-project.org/). 
It's published here : https://github.com/Webelys/glpi_ansible

Maybe can be usefull to others.

**Comment by jimi-c** [comment]
Hi @camlafit, could you please instead submit this as a PR? I'll close this otherwise, as it is not a bug report. Thanks!

**Comment by camlafit** [comment]
Hi

Ok I'll prepare a PR.

Thanks
