### ISSUE TITLE
extend cache plugins to cover inventory

### ISSUE THREAD

**Issue by bcoca** [ansible/ansible#12476]
### Issue Type:

Feature Idea
### Summary:

Extend the fact cache plugin to support a 'generic' cache that allows for inventory information and facts about a host to be cached. 

Currently some inventory scripts implement their own caching system, it would be nice to offer this to all inventories by default and let user configure it from ansible. Aside from consolidating many cache re-implementations it would allow for consistent expiration controls.

**Comment by timend** [comment]
+1 

We adapted caching for `azure_rm.py` from `ec2.py`, but only in a very brittle way. (No automatic refresh after configuration changes, mostly ignoring other command line options.)

I would also find it quite nice if Ansible implemented some cache on the inventory querying side. On the other hand the dynamic inventory scripts themselves can provide more tailored caches, e.g. by caching their remote calls to Cloud APIs and partial cache invalidation, respecting inventory specific configuration etc.

Any further progress/thoughts on this issue?

**Comment by bcoca** [comment]
closing in favor of https://github.com/ansible/proposals/issues/41
