### ISSUE TITLE
Ansible-playbook much much slower after this check in

### ISSUE THREAD

**Issue by evanccnyc** [ansible/ansible#12477]
Ansible devel branch (2.0)
Mac OS X client side

I have been able to reproduce this with the following steps:

1) EC2 Host with Ubuntu 14.04
2) Use a pem file to login and the ubuntu user
3) use become/sudo
4

Since this checkin:  https://github.com/ansible/ansible/commit/81bf88b6e052cdf72aef079e551a5a075d6ac85c
(determined by git bisect)

The time to run a playbook has increased significantly: 3-4x what it was before. Before this checkin it was much much faster.

cc @jimi-c

**Comment by jimi-c** [comment]
@evanccnyc do you have a large number of hosts in your inventory? I'm unclear exactly why this patch would slow things down, other than the fact that a large # of hosts would be brought into hostvars (but that should have been happening anyway in older code too).

**Comment by jimi-c** [comment]
Also, I would expect it to impact performance both when sudo was used and not.

**Comment by geerlingguy** [comment]
See related: https://github.com/ansible/ansible/issues/12239#issuecomment-142642288
