### ISSUE TITLE
gather_facts: Stuck when Remote is booted from archiso

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#12474]
I'm trying to create an os_installation_ansible_playbook for automatic installation of various linux distributions. By doing this, I learned that gather_facts works with an installed archlinux but not with the archiso installation iso. 

Python2 is installed and running on the archiso and ansible commands/modules are working. Are there any other dependencies for the Client to match?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
