### ISSUE TITLE
global name 'module_name' is not defined

### ISSUE THREAD

**Issue by adolgert** [ansible/ansible#12495]
The script used the async keyword on a module that doesn't support async. The error message refers to an undefined variable. In the latest checkout, it's in lib/ansible/executor/task_executor.py, line 530.

if self._task.async != 0:
    raise AnsibleError("async mode is not supported with the %s module" % module_name)

That "module_name" isn't in scope.

Happy Coding,
Drew

**Comment by bcoca** [comment]
does this fix it for you?

```
diff --git a/lib/ansible/executor/task_executor.py b/lib/ansible/executor/task_executor.py
index afe9605..e45b757 100644
--- a/lib/ansible/executor/task_executor.py
+++ b/lib/ansible/executor/task_executor.py
@@ -517,7 +517,7 @@ class TaskExecutor:

         if self._task.action in self._shared_loader_obj.action_loader:
             if self._task.async != 0:
-                raise AnsibleError("async mode is not supported with the %s module" % module_name)
+                raise AnsibleError("async mode is not supported with the %s module" % self._task.action)
             handler_name = self._task.action
         elif self._task.async == 0:
             handler_name = 'normal'
```

**Comment by adolgert** [comment]
Yes! I went through to reintroduce the error, and it produces the correct error message now.
+1 for alacrity. Thanks!
