### ISSUE TITLE
powershell.ps1 strictmode breaks a ton of modules

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#12497]
I noticed set-strictmode got turned on in a recent commit.

This breaks a ton of modules both in core and extra. Strictmode throws errors left and right and requires a very "correct" language implementation. My recommendation is that we turn this off for now. If we want to enable strictmode later we need a better testing harness for powershell modules so that we can test if each module can run with strictmode.

I'm not against turning on strictmode down the line, but now is definetely not the right time.

(ping @cchurch )

**Comment by trondhindenes** [comment]
Created PR #12525

**Comment by nitzmahone** [comment]
As a compromise to keep things working without destabilizing stuff too close to 2.0 release, I went through and disabled strict mode on individual modules that would clearly be broken by it (only in 2.0-stable branch). I'll be doing some more testing, and will mark any non-obvious failures the same way. Most of the fixes are trivial (modules not using Get-Attr or Get-Ansible-Param for parameter presence testing is the most common issue).

I'll try to get around to fixing the obvious ones in devel soon...

**Comment by dreamcat4** [comment]
Example how to temp. disable strictmode (per-module):

https://github.com/ansible/ansible-modules-extras/blob/40acb516fd5b344bb832758fc660a1d04a6b14d3/windows/win_iis_webbinding.ps1#L24-L25

**Comment by nitzmahone** [comment]
I _think_ we've got all these fixed as of 2.1.1, closing...
