### ISSUE TITLE
[PROBLEM FOUND] template error while templating string: Encountered unknown tag 'S'

### ISSUE THREAD

**Issue by jhagg** [ansible/ansible#12491]
in  #11366 I wrote about a problem I had with version 1.9. Now that I tried 1.9.3 I still get the error.
However, I got some more info.

Apparently it is the shell prompt settings on the remote host that is causing the problem.
I set the prompt to '%m{%S%n%s}%!>' and %S isn't available in python I guess.
Anyway, changing PS1 & co made it work.

This is not a very practical solution though. And the shell is forced thru /etc/passwd.
I guess that ansible parses the output of the command and gets the shell prompt output also.

Is there a workaround that doesn't involve changing prompts? :-)
This seems to be quite dangerous if login files on the remote hosts can affect ansible that bad.

So, is the solution only to use special users with /bin/sh as shell or is there an easier solution?

**Comment by jhagg** [comment]
By the way, this problem did not affect ansible  version 1.7 or older. Strange.

**Comment by jimi-c** [comment]
@jhagg yes, per the previous issue, this should be resolved in devel, if not please let us know. I'll hold this issue open until then.

**Comment by jhagg** [comment]
Yes, I tried devel (2.0.0-0.git20150923222) and it worked. I understand that 'devel' is exactly that, but are there any known backwards compatibility problems with devel compared to 1.7 or 1.9?

**Comment by jimi-c** [comment]
@jhagg there is actually another issue covering this (https://github.com/ansible/ansible/issues/12469), which we'll fix for the 1.9.4 version. So I'm going to close this as well, and you can keep track of the issue above.

Thanks!

**Comment by jhagg** [comment]
Seems as if devel somehow does something strange when I use '-t' option to limit it to one role (tags).
It walks (slowly) thru each role, which 1.7 didn't do.

**Comment by jimi-c** [comment]
Go ahead and open a new issue for that.
