### ISSUE TITLE
Run a batch file in windows using ansible

### ISSUE THREAD

**Issue by jugalporwal** [ansible/ansible#12520]
Hi,

I want to run a run.bat file present on my remote windows node using my control node (CentOS) . Is it possible? If not is there any alternative to do so?

**Comment by amenonsen** [comment]
The bug tracker is meant to report bugs. For questions about how to use Ansible, please ask on IRC or the mailing list.

**Comment by jugalporwal** [comment]
After repeated attempts I'm still not able to post to the mailing list. Hence I'm forced to ask my questions here.

**Comment by jimi-c** [comment]
@jugalporwal have you registered? There is also a first time approval required, which is how we reduce spam.

**Comment by jugalporwal** [comment]
@jimi-c Please let me know how do i register for it??

**Comment by jimi-c** [comment]
@jugalporwal you simply send a message to it, you just need to login with a Google account: https://groups.google.com/forum/#!forum/ansible-project

Click the "New Topic" button and post.

We'll go ahead and close this now.
