### ISSUE TITLE
ansible becomes unstable while executing pm2 through command module

### ISSUE THREAD

**Issue by lakshmantgld** [ansible/ansible#12541]
### Issue Type:

Bug Report
### Ansible Version:

1.9.2
### Ansible Configuration:

no changes made to .cfg. cfg points to dynamic inventory
### Enviroment:

controlling machine: ubuntu 14.04 and client: ubuntu 14.04
### summary:

motive is to restart node app named "www" using PM2. It successfully restarts when using command module in cmdline. 

```
ansible tag_type_eg -m command -a "sudo pm2 restart www"
```

but fails when performing the same in playbook using command module.

```
sudo: True
command: pm2 restart www
```

gives me an error stating  process not found. This is wierd. It works when used in cmdline but fails in playbook.
### Steps To Reproduce:

install pm2 using npm in client of version: 0.14.0
run a node app using pm2.

now, create a playbook to restart node app using pm2 through command module as shown above.
### Expected results:

node app should be restarted 
### Actual Results:

gives an error stating process cannot be found. this is wierd

**Comment by bcoca** [comment]
can you paste the full actual error?

**Comment by lakshmantgld** [comment]
![error stack](https://cloud.githubusercontent.com/assets/6481030/10181305/75542aa8-6751-11e5-9b35-ba785b191e0e.png)
This is the error i get when executing through command module from playbooks

**Comment by lakshmantgld** [comment]
@bcoca i have updated the error stack. waiting for the fix. or is something wrong with my setup?

**Comment by bcoca** [comment]
that does not look like an ansible issue, the error is coming from pm2

**Comment by lakshmantgld** [comment]
OK. Solved it by restarting the pm2 itself.

'''
service: name-pm2-init.sh state=restarted
'''
