### ISSUE TITLE
blocks don't take run_once

### ISSUE THREAD

**Issue by amenonsen** [ansible/ansible#12559]
With ansible devel, it's possible to specify `delegate_to` on a block, but `run_once` isn't accepted.

**Comment by ghost** [comment]
literally just used my first block, and i was using it specifically to try a run_once on it, so i'd say its a fairly intuitive expectation of the block feature

**Comment by vikas027** [comment]
Please add `ignore_errors` also in block. I got error for it too.

``` bash
# ansible-playbook -v vikas027.yaml
ERROR! 'ignore_errors' is not a valid attribute for a Block
```
