### ISSUE TITLE
v2: task with assert + run_once only fails the current play

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#12563]
```
ansible 2.0.0 (devel 8095b027bf) last updated 2015/09/29 20:00:39 (GMT +200)
  lib/ansible/modules/core: (detached HEAD a4ac171a07) last updated 2015/09/29 15:50:49 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 3c8c716801) last updated 2015/09/29 15:50:49 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = None
```

Using the default inventory, run a simple playbook with these two plays:

```

---
- hosts:        all
  gather_facts: False
  tasks:
  - assert:
      that: [ False ]
    run_once:   True
  - debug:

- hosts:        all
  tasks:
  - debug:
```

This play is expected to fail at the very first task, and execute nothing more. However, while the remaining part of the first play is not executed, the second play is still fully executed.
The tasks in the second play even are executed on the host `green.example.com` - which was the host choosen in the `run_once` loop, while that host is still marked as failed in the recap:

[2.0.0 (devel 8095b027bf)] serge@goldorak:~/tmp$ ansible-playbook main.yml -c local
 [WARNING]: somebody cleverly deleted cowsay or something during the PB run.  heh.

PLAY ***************************************************************************

TASK [assert that=[False]] *****************************************************
fatal: [green.example.com]: FAILED! => {"assertion": false, "changed": false, "evaluated_to": false, "failed": true}

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [blue.example.com]
ok: [green.example.com]
ok: [192.168.100.10]
ok: [192.168.100.1]
ok: [alpha.example.org]
ok: [192.168.1.100]
ok: [beta.example.org]
ok: [www001.example.com]
ok: [www002.example.com]
ok: [192.168.1.110]
ok: [www003.example.com]
ok: [www006.example.com]
ok: [db01.intranet.mydomain.net]
ok: [www004.example.com]
ok: [www005.example.com]
ok: [db-100-node.example.com]
ok: [db02.intranet.mydomain.net]
ok: [db-99-node.example.com]
ok: [10.25.1.56]
ok: [10.25.1.57]
ok: [db-101-node.example.com]

TASK [debug] *******************************************************************
ok: [green.example.com] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [blue.example.com] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [192.168.100.1] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [192.168.100.10] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [alpha.example.org] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [beta.example.org] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [192.168.1.100] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [192.168.1.110] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [www001.example.com] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [www002.example.com] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [www003.example.com] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [www004.example.com] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [www005.example.com] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [www006.example.com] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [db02.intranet.mydomain.net] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [db01.intranet.mydomain.net] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [10.25.1.56] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [10.25.1.57] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [db-99-node.example.com] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [db-100-node.example.com] => {
    "changed": false, 
    "msg": "here we are"
}
ok: [db-101-node.example.com] => {
    "changed": false, 
    "msg": "here we are"
}

PLAY RECAP *********************************************************************
10.25.1.56                 : ok=2    changed=0    unreachable=0    failed=0  
10.25.1.57                 : ok=2    changed=0    unreachable=0    failed=0  
192.168.1.100              : ok=2    changed=0    unreachable=0    failed=0  
192.168.1.110              : ok=2    changed=0    unreachable=0    failed=0  
192.168.100.1              : ok=2    changed=0    unreachable=0    failed=0  
192.168.100.10             : ok=2    changed=0    unreachable=0    failed=0  
alpha.example.org          : ok=2    changed=0    unreachable=0    failed=0  
beta.example.org           : ok=2    changed=0    unreachable=0    failed=0  
blue.example.com           : ok=2    changed=0    unreachable=0    failed=0  
db-100-node.example.com    : ok=2    changed=0    unreachable=0    failed=0  
db-101-node.example.com    : ok=2    changed=0    unreachable=0    failed=0  
db-99-node.example.com     : ok=2    changed=0    unreachable=0    failed=0  
db01.intranet.mydomain.net : ok=2    changed=0    unreachable=0    failed=0  
db02.intranet.mydomain.net : ok=2    changed=0    unreachable=0    failed=0  
green.example.com          : ok=2    changed=0    unreachable=0    failed=1  
www001.example.com         : ok=2    changed=0    unreachable=0    failed=0  
www002.example.com         : ok=2    changed=0    unreachable=0    failed=0  
www003.example.com         : ok=2    changed=0    unreachable=0    failed=0  
www004.example.com         : ok=2    changed=0    unreachable=0    failed=0  
www005.example.com         : ok=2    changed=0    unreachable=0    failed=0  
www006.example.com         : ok=2    changed=0    unreachable=0    failed=0   

```
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
