### ISSUE TITLE
Get 'copy' to write the file with the correct permissions from the start

### ISSUE THREAD

**Issue by pas256** [ansible/ansible#1258]
It would be great if the copy module write the 'dest' file with the correct permissions in 1 operation.

Currently, the copy module writes the file, and the separately does a chmod.

For most operations this is fine. The exception is for writing a file to `/etc/sudoers.d` while using `sudo=True` in your playbook. 

If `/etc/sudoers.d/*` is not 100% correct, it causes all sudo actions to fail (at least on Ubuntu 12.04).

mdehaan believes:

>  it would be doable, with some work
>  so we would need to move the chmod logic into AnsibleModuleCommon
>  and then simplify file and everything else that daisy chains into it
>  please file a github ticket and we could do it in 0.9
> it could cut down on a slew of operations, I like the idea very much

...so here it is.

**Comment by pas256** [comment]
Ok, so the above comments might not apply to this exact situation. Talking more, the copy module is just doing an mv operation, then a chmod. If we reverse the operations so that the chmod is done before the mv, then mv will preserve the permissions, and the "sudoers.d" issue will be averted.

**Comment by mpdehaan** [comment]
Basically this request is about adding chmod and chown support to the copy module, but I also believe we can eliminate most daisy chaining if we do this intelligently and move most of the file code into module common as utility functions.
This also brings a significant acceleration of file operation performance.

**Comment by mpdehaan** [comment]
This is not in place just yet, but the changes I have just pushed to allow usage of file functions in any module (as they are now used in copy) allows us to apply the "set_file_attributes_if_different" function before the move instead of after (or maybe before and after if we're paranoid).   Easily possible now.  In queue.

**Comment by mpdehaan** [comment]
we think this is good now
