### ISSUE TITLE
Accept regexp support for -l/--limit option

### ISSUE THREAD

**Issue by sylr** [ansible/ansible#12588]
Hi,

It would be really useful if the --limit option could accept regular expressions instead of just globs i.e.

``` shell
ansible-playbook -i inventory/prod -l pwet[2-5][0-9] prod-accounts.yml
```

Regards.

**Comment by amenonsen** [comment]
`--limit '~regexp'`

**Comment by sivel** [comment]
As mentioned, this can be achieved by prefixing your limit pattern with a `~`.

This is documented at http://docs.ansible.com/ansible/intro_patterns.html

> Most people don’t specify patterns as regular
> expressions, but you can. Just start the pattern 
> with a ‘~’:
> 
> ~(web|db).*.example.com

**Comment by sylr** [comment]
Thanks.

I would be great to mention this in the output of the help (-h/--help)

Regards.
