### ISSUE TITLE
Python 3 support for AnsibleModule.log()

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#12586]
I need a place to discuss this before I can submit a pull request, and I don't think a [discussion in the comments of a merged PR](https://github.com/ansible/ansible/pull/12568#discussion_r40802626) is a good place for that.

At the moment, AnsibleModule.log('anything') converts the argument to UTF-8 bytes, which fails on Python 3:

```
======================================================================
ERROR: test_module_utils_basic_ansible_module_user_and_group (units.module_utils.test_basic.TestModuleUtilsBasic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mg/src/ansible/test/units/module_utils/test_basic.py", line 547, in test_module_utils_basic_ansible_module_user_and_group
    argument_spec = dict(),
  File "/home/mg/src/ansible/lib/ansible/module_utils/basic.py", line 479, in __init__
    self._log_invocation()
  File "/home/mg/src/ansible/lib/ansible/module_utils/basic.py", line 1316, in _log_invocation
    self.log(msg, log_args=log_args)
  File "/home/mg/src/ansible/lib/ansible/module_utils/basic.py", line 1277, in log
    self._log_to_syslog(msg)
  File "/home/mg/src/ansible/lib/ansible/module_utils/basic.py", line 1251, in _log_to_syslog
    syslog.syslog(syslog.LOG_INFO, msg)
TypeError: [priority,] message string
```

**Comment by mgedmin** [comment]
> So this whole method needs to be reworked for python3 compatibility.

I still think my original fix is good, with the possible exception of error handling when API users mistakenly provide a value that isn't a string (bytes/str/unicode).

**Comment by abadger** [comment]
> > So this whole method needs to be reworked for python3 compatibility.
> 
> I still think my original fix is good, with the possible exception of error handling when API users mistakenly provide a value that isn't a string (bytes/str/unicode).

bcoca just updated the log method.  before, it was also doing a fair bit of string manipulation above the code that we're working on now. ( I think it's moved to _log_invocation() which we might need to fix as well).

**Comment by mgedmin** [comment]
I'm confused.  The comment I remember writing was much longer than [the one I see here now](https://github.com/ansible/ansible/issues/12586#issuecomment-144651484).

**Comment by mgedmin** [comment]
> bcoca just updated the log method

That was what was causing the merge conflict for #12568, which was why I rebased that PR.

> The comment I remember writing was much longer than the one I see here now.

It's possible I hit preview and forgot to hit Update before closing the browser tab.
I'll try to recreate the main points.  I was mostly answering [your comments](https://github.com/ansible/ansible/pull/12568#discussion_r40802626) point by point:

> I wonder if we need to also catch things that are not text (for instance a number)?

I don't think so.  The current code raises TypeError if you don't pass text (in the syslog.syslog() case).

My original suggested change would replace that TypeError with an AttributeError: int object has no attribute 'encode', which was why I added the explicit `raise TypeError` in this PR.

> The previous code handled that further down with a format string

Only when systemd-journal is installed; otherwise `msg` is passed directly to syslog.syslog().

> I took a look at systemd.journal on fedora21.

Here I actually missed the subtle point of it being better to pass unicode on Python 2 and assumed it was fine to pass bytes (str) on Python 2 and unicode (str) on Python 3

> Also took a look at syslog on fedora 21

bytes (str) on Python 2 and unicode (str) on Python 3.

And since I missed the point about journal, that's why I said "I still think my original fix is good".

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible or #ansible-devel on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
