### ISSUE TITLE
Can't connect via SSH after OSX 10.11 (El Capitan) Upgrade

### ISSUE THREAD

**Issue by mcalhoun** [ansible/ansible#12594]
I upgraded my workstation to El Capitan last night and now connecting to a virtualbox-hosted VM doesn't seem to be working via ssh, although I can ssh locally. I'm using the latest source release (fe0e4f27ad82c4b5844a3a18922fa1857242a33b). 

See below:

[~/D/C/d/dv-ansible|ruby-2.2.1]‹master*› »»»» cat inventory/vagrant                                                                                                                                                                                                  0|10:42:43

[vagrant-linux]
vagrant2 ansible_ssh_host=localhost ansible_ssh_user=root ansible_ssh_pass=vagrant ansible_ssh_port=2200⏎

[~/D/C/d/dv-ansible|ruby-2.2.1]‹master*› »»»» ansible vagrant-linux -i inventory/vagrant -m ping -vvv                                                                                                                                                                0|10:42:20
Using /[redacted]/dv-ansible/ansible.cfg as config file
<localhost> ESTABLISH CONNECTION FOR USER: root on PORT 2200 TO localhost
vagrant2 | UNREACHABLE!

[~/D/C/d/dv-ansible|ruby-2.2.1]‹master*› »»»» ssh root@localhost -p 2200                                                                                                                                                                                             3|10:42:23
root@localhost's password: vagrant
Last login: Thu Oct  1 14:42:14 2015 from 10.0.2.2
Welcome to your Vagrant-built virtual machine.
[root@localhost ~]# exit
logout
Connection to localhost closed.

**Comment by jimi-c** [comment]
Hi @mcalhoun, which version of Ansible is this occurring on?

**Comment by mcalhoun** [comment]
I'm using the latest source code on the devel branch (fe0e4f2).

**Comment by jimi-c** [comment]
Thanks, we have some users that have upgraded and we'll try to reproduce this.

**Comment by mcalhoun** [comment]
Thanks! Let me know if I can be of assistance in troubleshooting.

**Comment by amenonsen** [comment]
@mcalhoun Please run with `-vvvvv` and post the output? And if the problem doesn't become clearer from doing so, perhaps you could cut-and-paste the ssh command that ansible actually executes and see what happens?

**Comment by tgerla** [comment]
If this datapoint helps, my Vagrant+El Capitan+ansible devel is working fine.

```
Timothys-MacBook-Pro:ansible tgerla$ ssh -V
OpenSSH_6.9p1, LibreSSL 2.1.7
Timothys-MacBook-Pro:ansible tgerla$ ansible --version
vansible 2.0.0 (devel 775486c9d6) last updated 2015/10/01 10:59:11 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 50912c9092) last updated 2015/07/09 15:41:19 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD dec7d95d51) last updated 2015/07/09 15:41:20 (GMT -400)
  config file =
  configured module search path = None
Timothys-MacBook-Pro:ansible tgerla$ vagrant --version
Vagrant 1.7.2
```

**Comment by jimi-c** [comment]
@mcalhoun and you may want to try it with the stable-1.9 branch, just to pinpoint if it's something new or if this is some overall environmental configuration issue regarding ssh after the upgrade.

**Comment by mcalhoun** [comment]
Here's some of the requested output...I'll switch to 1.9 and see if that works...

[~/D/C/d/dv-ansible|ruby-2.2.1]‹master*› »»»» ansible vagrant-linux -i inventory/vagrant -m ping -vvvv                                                                                                                                                               0|12:02:05
Using /[redacted]/dv-ansible/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<localhost> ESTABLISH CONNECTION FOR USER: root on PORT 2200 TO localhost
vagrant2 | UNREACHABLE!

[~/D/C/d/dv-ansible|ruby-2.2.1]‹master*› »»»» ssh -V                                                                                                                                                                                                                 0|12:04:55
OpenSSH_6.9p1, LibreSSL 2.1.7

[~/D/C/d/dv-ansible|ruby-2.2.1]‹master*› »»»» ansible --version                                                                                                                                                                                                      0|12:04:57
ansible 2.0.0 (devel 9c42a4cc69) last updated 2015/10/01 12:04:27 (GMT -400)
  lib/ansible/modules/core: (detached HEAD b9090a8146) last updated 2015/10/01 09:22:49 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 962afeed54) last updated 2015/10/01 09:22:49 (GMT -400)
  config file = /[redacted]/dv-ansible/ansible.cfg
  configured module search path = /[redacted]/ansible/library

**Comment by mcalhoun** [comment]
Switching to 1.9 works...

[~/D/C/d/dv-ansible|ruby-2.2.1]‹master*› »»»» ansible --version                                                                                                                                                                                                     0|12:09:03
ansible 1.9.4 (stable-1.9 a07ca04a75) last updated 2015/10/01 12:06:57 (GMT -400)
  lib/ansible/modules/core: (detached HEAD da496f9bcc) last updated 2015/10/01 12:08:01 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 81b345401f) last updated 2015/10/01 12:08:01 (GMT -400)
  configured module search path = /[redacted]/ansible/library

[~/D/C/d/dv-ansible|ruby-2.2.1]‹master*› »»»» ansible vagrant-linux -i inventory/vagrant -m ping                                                                                                                                                                    0|12:09:09
vagrant2 | success >> {
    "changed": false,
    "ping": "pong"
}

**Comment by jimi-c** [comment]
@mcalhoun could you also run the devel version with `-vvvvv` and share the output there? Just please be sure to censor any sensitive information in it before doing so..

**Comment by jimi-c** [comment]
You might also want to run this simplified command instead of your full playbook:

<pre>
ansible -m setup -i 127.0.0.1, -c ssh -e ansible_ssh_port=2222 --private-key /path/to/your/vagrant/private_key -u vagrant all -v
</pre>

**Comment by kevinawoo** [comment]
I'm getting the same error on the latest `devel`, `1.9.4` and `stable-1.9`.

Its similar to:

``` bash
$ ssh -V
OpenSSH_6.9p1, LibreSSL 2.1.7

$ openssl version
OpenSSL 1.0.2a 19 Mar 2015

$ ansible --version
ansible 2.0.0 (detached HEAD a1f6de8745) last updated 2015/10/02 17:57:11 (GMT -700)
  lib/ansible/modules/core: (detached HEAD dbc860daaa) last updated 2015/10/02 17:57:11 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 9f5420e459) last updated 2015/10/02 17:57:12 (GMT -700)
  config file = /Users/kevin/tools/ansible.cfg
  configured module search path = None


$ ansible-playbook -i hosts/staging deploy.yml --extra-var 'serial=1 github_ref=staging' -vvvvv
Using /Users/kevin/tools/ansible.cfg as config file
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default). This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
1 plays in deploy.yml
Loaded callback default of type stdout, v2.0

PLAY ***************************************************************************

TASK [setup] *******************************************************************
<ec2-amazon-amazon.amazon.com> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<ec2-amazon-amazon.amazon.com> SSH: ansible.cfg set ssh_args: (-o)(ForwardAgent=yes)(-o)(ControlMaster=auto)(-o)(ControlPersist=1h)
<ec2-amazon-amazon.amazon.com> SSH: ANSIBLE_HOST_KEY_CHECKING/host_key_checking disabled: (-o)(StrictHostKeyChecking=no)
<ec2-amazon-amazon.amazon.com> SSH: ANSIBLE_PRIVATE_KEY_FILE/private_key_file/ansible_ssh_private_key_file set: (-o)(IdentityFile="/Users/kevin/.ssh/SSH-Access.pem")
<ec2-amazon-amazon.amazon.com> SSH: ansible_password/ansible_ssh_pass not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<ec2-amazon-amazon.amazon.com> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User=ubuntu)
<ec2-amazon-amazon.amazon.com> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<ec2-amazon-amazon.amazon.com> SSH: PlayContext set ssh_common_args: ()
<ec2-amazon-amazon.amazon.com> SSH: PlayContext set ssh_extra_args: ()
<ec2-amazon-amazon.amazon.com> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/Users/kevin/.ansible/cp/ansible-ssh-%h-%p-%r)
<ec2-amazon-amazon.amazon.com> SSH: EXEC ssh -C -vvv -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=1h -o StrictHostKeyChecking=no -o 'IdentityFile="/Users/kevin/.ssh/SSH-Access.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/kevin/.ansible/cp/ansible-ssh-%h-%p-%r ec2-amazon-amazon.amazon.com LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python
fatal: [staging-01]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
```

I'm able to run it on a different setup

``` bash
$ ssh -V
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011

$ openssl version
OpenSSL 1.0.2d 9 Jul 2015
```

**Comment by bcoca** [comment]
so the actual errors is what i would expect from ssh if there is a networking issue (dns, route, etc)
can you try:

```
ssh -C -vvv -o User=ubuntu -o 'IdentityFile="/Users/kevin/.ssh/SSH-Access.pem"' ec2-amazon-amazon.amazon.com
```

**Comment by kevinawoo** [comment]
The **El Captain** machine is down right now, but it's not working on my other machine either. However I'm still able to run ansible.

``` bash
ssh -C -vvv -o 'IdentityFile="/Users/kevin/.ssh/SSH-Access.pem"' ec2-amazon-amazon.amazon.com
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /Users/kevin/.ssh/config
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: /etc/ssh_config line 102: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to ec2-amazon-amazon.amazon.com [100.100.100.100] port 22.
debug1: Connection established.
debug3: Incorrect RSA1 identifier
debug3: Could not load "/Users/kevin/.ssh/SSH-Access.pem" as a RSA1 public key
debug1: identity file /Users/kevin/.ssh/SSH-Access.pem type -1
debug1: identity file /Users/kevin/.ssh/SSH-Access.pem-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.2
debug1: Remote protocol version 2.0, remote software version OpenSSH_5.9p1 Debian-5ubuntu1.7
debug1: match: OpenSSH_5.9p1 Debian-5ubuntu1.7 pat OpenSSH_5*
debug2: fd 3 setting O_NONBLOCK
debug3: load_hostkeys: loading entries for host "ec2-amazon-amazon.amazon.com" from file "/Users/kevin/.ssh/known_hosts"
debug3: load_hostkeys: found key type RSA in file /Users/kevin/.ssh/known_hosts:28
debug3: load_hostkeys: loaded 1 keys
debug3: order_hostkeyalgs: prefer hostkeyalgs: ssh-rsa-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-rsa
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: kex_parse_kexinit: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ssh-rsa-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-rsa,ssh-dss-cert-v01@openssh.com,ssh-dss-cert-v00@openssh.com,ssh-dss
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: zlib@openssh.com,zlib,none
debug2: kex_parse_kexinit: zlib@openssh.com,zlib,none
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit: first_kex_follows 0
debug2: kex_parse_kexinit: reserved 0
debug2: kex_parse_kexinit: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit: first_kex_follows 0
debug2: kex_parse_kexinit: reserved 0
debug2: mac_setup: found hmac-md5
debug1: kex: server->client aes128-ctr hmac-md5 zlib@openssh.com
debug2: mac_setup: found hmac-md5
debug1: kex: client->server aes128-ctr hmac-md5 zlib@openssh.com
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(1024<1024<8192) sent
debug1: expecting SSH2_MSG_KEX_DH_GEX_GROUP
debug2: dh_gen_key: priv key bits set: 133/256
debug2: bits set: 526/1024
debug1: SSH2_MSG_KEX_DH_GEX_INIT sent
debug1: expecting SSH2_MSG_KEX_DH_GEX_REPLY
debug1: Server host key: RSA aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa
debug3: load_hostkeys: loading entries for host "ec2-amazon-amazon.amazon.com" from file "/Users/kevin/.ssh/known_hosts"
debug3: load_hostkeys: found key type RSA in file /Users/kevin/.ssh/known_hosts:28
debug3: load_hostkeys: loaded 1 keys
debug3: load_hostkeys: loading entries for host "100.100.100.100" from file "/Users/kevin/.ssh/known_hosts"
debug3: load_hostkeys: found key type RSA in file /Users/kevin/.ssh/known_hosts:28
debug3: load_hostkeys: loaded 1 keys
debug1: Host 'ec2-amazon-amazon.amazon.com' is known and matches the RSA host key.
debug1: Found key in /Users/kevin/.ssh/known_hosts:28
debug2: bits set: 508/1024
debug1: ssh_rsa_verify: signature correct
debug2: kex_derive_keys
debug2: set_newkeys: mode 1
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug2: set_newkeys: mode 0
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: /Users/kevin/.ssh/ec2_west.pem (0x111111111111),
debug2: key: /Users/kevin/.ssh/ec2_east.pem (0x111111111111),
debug2: key: /Users/kevin/.ssh/id_rsa (0x111111111111),
debug2: key: /Users/kevin/.ssh/SSH-Access.pem (0x0), explicit
debug1: Authentications that can continue: publickey
debug3: start over, passed a different list publickey
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /Users/kevin/.ssh/ec2_west.pem
debug3: send_pubkey_test
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey
debug1: Offering RSA public key: /Users/kevin/.ssh/ec2_east.pem
debug3: send_pubkey_test
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey
debug1: Offering RSA public key: /Users/kevin/.ssh/id_rsa
debug3: send_pubkey_test
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey
debug1: Trying private key: /Users/kevin/.ssh/SSH-Access.pem
debug1: read PEM private key done: type RSA
debug3: sign_and_send_pubkey: RSA aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
Permission denied (publickey).
```

I was able to recreate it by installing the latest openssh on my old machine.

``` bash
$ brew install openssh
```

**Comment by bcoca** [comment]
so that confirms this is an ssh problem not really an ansible issue

**Comment by bcoca** [comment]
can you try using ansible adding `-c paramiko` on the command line?

**Comment by kevinawoo** [comment]
It works beautifully!. Thanks!

**Comment by mcalhoun** [comment]
Just to be clear, the original issue I reported in this thread is still occurring (with a3ed9fc131a098cbfedb515ef8728cc7d084ce13) and "-c paramiko" has no effect on the issue. I can ssh outside of ansible just fine using the same username/password, but when using ansible it's not working.

**Comment by bcoca** [comment]
@mcalhoun it seems your problem is slightly different, can you show us the output when using -vvvv?

**Comment by mcalhoun** [comment]
[~/D/C/d/dv-ansible|ruby-2.2.1]‹master*› »»»» ansible vagrant-linux -i inventory/vagrant -m ping -vvvv                                                                                                                0|10:23:10
Using /Users/[redacted]/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<localhost> ESTABLISH CONNECTION FOR USER: root on PORT 2200 TO localhost
vagrant2 | UNREACHABLE! => {
    "changed": false,
    "msg": "ERROR! [Errno 61] Connection refused",
    "unreachable": true
}

This is on the most recent devel banch pull. If I checkout stable-1.9, then the identical command works fine. I can also SSH directly (outside of ansible) without issue.

**Comment by bcoca** [comment]
it does not seem to be using ssh, can you run ansible directly?

**Comment by mcalhoun** [comment]
@bcoca I'm not sure what you mean...I am running ansible with the following command...

ansible vagrant-linux -i inventory/vagrant -m ping -vvvv 

Are you suggesting that I do something else?

**Comment by jimi-c** [comment]
@mcalhoun are you including the full output? Using that level of verbosity means there should be more ssh debugging information included. For example, here's the output from a ping to one of my VM's:

<pre>
# ansible -m ping -vvvv ubuntu1404
Using /etc/ansible/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<192.168.122.113> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.122.113> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=4 -tt 192.168.122.113 mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1444077513.95-114561904060082" && echo "$HOME/.ansible/tmp/ansible-tmp-1444077513.95-114561904060082"
<192.168.122.113> PUT /tmp/tmpNr_ni8 TO /root/.ansible/tmp/ansible-tmp-1444077513.95-114561904060082/ping
<192.168.122.113> SSH: EXEC scp -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=4 /tmp/tmpNr_ni8 [192.168.122.113]:/root/.ansible/tmp/ansible-tmp-1444077513.95-114561904060082/ping
<192.168.122.113> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.122.113> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=4 -tt 192.168.122.113 LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1444077513.95-114561904060082/ping; rm -rf "/root/.ansible/tmp/ansible-tmp-1444077513.95-114561904060082/" > /dev/null 2>&1
ubuntu1404 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
</pre>

**Comment by mcalhoun** [comment]
Yes, the full command and full output are below...

ansible vagrant-linux -i inventory/vagrant -m ping -vvvv

Using /Users/[redacted]/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
ESTABLISH CONNECTION FOR USER: root on PORT 2200 TO localhost
vagrant2 | UNREACHABLE! => {
"changed": false,
"msg": "ERROR! [Errno 61] Connection refused",
"unreachable": true
}

**Comment by marccacatua** [comment]
Hi.
My SSH does´t work too. But my message is:
Corrupted MAC on input.
ssh_packet_read: message authentication code incorrect

Can you help me with that?
Regards,

**Comment by geerlingguy** [comment]
I've been doing a ton of testing with Vagrant, VirtualBox, VMware Fusion, and Ansible (both 1.9.3 and 2.0.0 devel at multiple revisions) on El Capitan and haven't run into this issue at all... I wonder if it's an environment thing? For El Capitan, I upgraded my Mac, but didn't change any particular settings on the system (no exotic hacks to disable new security features or anything).

I've tested [Drupal VM](https://github.com/geerlingguy/drupal-vm) on both VirtualBox and VMware, and I've tested each of the VM configurations inside [ansible-vagrant-examples](https://github.com/geerlingguy/ansible-vagrant-examples) one by one (some many, many times), and didn't have any issues either running Ansible playbooks manually connecting through private IPs configured by Vagrant, or through the connection that's automatically set up by Vagrant (e.g. 127.0.0.1 on port 2222 or 2200, etc.).

Here's the version I just used again to re-run a bunch of the VM provisioning tests:

```
$ ansible --version
ansible 2.0.0 (devel 9e364c2eb5) last updated 2015/10/06 23:06:49 (GMT -400)
  lib/ansible/modules/core: (detached HEAD d659c79db7) last updated 2015/10/06 23:06:49 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/06 23:06:50 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = None
```

**Comment by geerlingguy** [comment]
@mcalhoun - Are you using a publicly-available vagrant box? And could you give a Vagrantfile/config that can be used to reproduce the issue?

**Comment by mcalhoun** [comment]
@geerlingguy What's weird is that this same configuration works just fine if I check out the stable-1.9 branch but doesn't work on the devl branch. 

For completeness I've also tried this with no ansible.cfg just to make sure it wasn't anything in the config file. I got the same result.

Here are the steps I'm taking:

```
$ vagrant up linux [wait for box to boot]
$ ansible vagrant-linux -i inventory/vagrant -m ping -vvvv [I get the error - ESTABLISH CONNECTION FOR USER: root on PORT 2200 TO localhost
vagrant2 | UNREACHABLE!]
$ cat inventory/vagrant

[vagrant-linux]
vagrant2 ansible_ssh_host=localhost ansible_ssh_user=root ansible_ssh_pass=vagrant ansible_ssh_port=2200⏎

$ ssh root@localhost -p 2200
root@localhost's password: vagrant
Last login: Wed Oct 7 08:42:14 2015 from 10.0.2.2
Welcome to your Vagrant-built virtual machine.
[root@localhost ~]# exit
logout
Connection to localhost closed.
```

Below are my versions (keeping up with the latest source every few hours by cron) and VagrantFile...

```
»»»» ansible --version                                                                                                                                                       
ansible 2.0.0 (devel 9e364c2eb5) last updated 2015/10/07 09:00:01 (GMT -400)
  lib/ansible/modules/core: (detached HEAD d659c79db7) last updated 2015/10/06 16:47:03 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/06 16:47:03 (GMT -400)
  config file = /Users/[redacted]/ansible.cfg
  configured module search path = /Users/[redacted]/ansible/library
```

## VagrantFile

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "win" do |win|
    win.vm.box = "mcalhoun/win2012stdeval"
    win.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
    win.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
    win.vm.provider "virtualbox" do |vb|
      vb.gui = true
    end
  end

  config.vm.define "linux" do |linux|
    linux.vm.box = "nrel/CentOS-6.6-x86_64"
    linux.vm.network :forwarded_port, guest: 22, host: 2200, id: "ssh", auto_correct: true
    linux.vm.provider "virtualbox" do |vb|
      vb.gui = true
    end
  end
end
```

**Comment by amenonsen** [comment]
Based on the `ESTABLISH CONNECTION FOR USER: root on PORT 2200 TO localhost` message, ansible is choosing to use the paramiko transport, not ssh. Does it work if you use `-c ssh`?

**Comment by mcalhoun** [comment]
@amenonsen You are absolutely correct! Using the -c ssh flag fixes the issue. 

Any idea why stable-1.9 works without the flag and devel needs the flag?

Thanks!
Matt

**Comment by jimi-c** [comment]
@mcalhoun when using `smart` as the transport, we attempt to use ssh with optimal settings (ControlPersist, etc). If that fails, we fall back to using paramiko, which is typically faster when those optimal settings aren't available. So, based on this, it appears we're falling back to paramiko and there's some bug there on the newest OSX version.

**Comment by bcoca** [comment]
except on OS X we used to have a kernel crash when using ssh and ~~control persist~~ sshpass for OS X machines 'smart' always defaults to paramiko

**Comment by jimi-c** [comment]
We only do that if an ssh password is specified:

<pre>
       if sys.platform.startswith('darwin') and self._play_context.password:
</pre>

**Comment by bcoca** [comment]
ah, so that might be way only some people see it, those using keys will now be using the newer ssh, those using passwords would still be on paramiko.

**Comment by geerlingguy** [comment]
@bcoca / @jimi-c - That would explain why I'm unable to see the problem—I've only tried using keys, not ever specifying a password.

**Comment by jimi-c** [comment]
Just as an update while we're still looking at why this may be happening, set `transport = ssh` in your ansible.cfg to work around this bug for the time being.

**Comment by sivel** [comment]
This may be caused with paramiko as a result of pycrypto.

pycrypto is a compiled C module, which means that is was linked against a specific version of python and El Capitan provides a python upgrade.

Since upgrading to El Capitan, I've had to re-compile any C modules that I have for other projects.

Does re-installing pycrypto resolve the issue?  I cannot easily test this right now.

**Comment by quentinsf** [comment]
In case it's a useful datapoint, my El Capitan machine will only connect to my ubuntu VMs if I either (a) set pipelining off or (b) set transport to paramiko.

But I may have a slightly unusual Python installation - am rebuilding things to see if that helps.

**Comment by tqh** [comment]
If it is any help I had to shorten control path in El Capitan. See http://docs.ansible.com/ansible/intro_configuration.html#configuration-file

**Comment by jimi-c** [comment]
Per this comment on another issue from @mcalhoun, we believe the core issue reporte has been resolved. If anyone else is still seeing issues with this, please open a new issue and be sure to test specifically if you're seeing the problem with `-c paramiko` or `-c ssh` rather than the default (`smart`).

Thanks!
