### ISSUE TITLE
Include statement uses wrong path when not included from tasks/main.yml

### ISSUE THREAD

**Issue by llernestal** [ansible/ansible#12609]
**To reproduce:**
Playbook

```
hosts: 127.0.0.1
connection: local
roles:
  - test_role
```

test_role/tasks/main.yml

```

---

- include: test1.yml
```

test_role/tasks/test1.yml

```

---

- include: test2.yml
```

test_role/tasks/test2.yml

```

---

- name: output
  debug: msg="Hello world!"
```

This fails with message:

```
TASK [test_role : include] *********************************************************
included: tasks/test2.yml for localhost
fatal: [localhost]: FAILED! => {"failed": true, "reason": "ERROR! the file_name '/tasks/test2.yml' does not exist, or is not readable"}
```

**Comment by jimi-c** [comment]
HI @llernestal, I was unable to reproduce this, even backing up to a commit 2 weeks ago:

<pre>
# ansible-playbook -vv playbooks/test.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in playbooks/test.yml
PLAY ***************************************************************************
TASK [setup] *******************************************************************
ok: [127.0.0.1 -> localhost]
TASK [test_role : include] *****************************************************
included: test1.yml for 127.0.0.1
TASK [test_role : include] *****************************************************
included: test2.yml for 127.0.0.1
TASK [test_role : output] ******************************************************
ok: [127.0.0.1 -> localhost] => {
    "changed": false, 
    "msg": "Hello world!"
}
PLAY RECAP *********************************************************************
127.0.0.1                  : ok=4    changed=0    unreachable=0    failed=0   
</pre>

I tried with paths relative to the playbook as well, with the same result (the above is the output from one such example).

Is there any other info you can share to help us reproduce this?

**Comment by llernestal** [comment]
Well now on `2.0.0 (devel af1f462ba0)` I can't reproduce it either... I must have run it with a docker image containing older ansible version. Sorry for the inconvenience! ;)

**Comment by jimi-c** [comment]
No problem! Glad it wasn't just me :)
