### ISSUE TITLE
Ansible2 : `roles` and `with_items`

### ISSUE THREAD

**Issue by Ekleog** [ansible/ansible#12623]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 2.0.0 (devel a89412ecb1) last updated 2015/09/29 21:45:10 (GMT +200)
  lib/ansible/modules/core: (detached HEAD a4ac171a07) last updated 2015/09/30 02:14:07 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 3c8c716801) last updated 2015/09/30 02:14:07 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = None
```

Also tested with `v2.0.0-0.2-alpha2` ; I can test with any other version of your choice.
##### Ansible Configuration:

I changed `#!/usr/bin/env python` to `/usr/bin/env python2` in `ansible-playbook`.

Changes to `/etc/ansible/ansible.cfg` ; excluding comment-only hunks, result of `diff /etc/ansible/ansible.cfg examples/ansible.cfg`:

``` diff
81c92,94
< ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}

---
> #ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
> # This short version is better used in templates as it won't flag the file as changed every run.
> ansible_managed = Ansible managed: {file} on {host}
115,120c128,134
< action_plugins     = /usr/share/ansible_plugins/action_plugins
< callback_plugins   = /usr/share/ansible_plugins/callback_plugins
< connection_plugins = /usr/share/ansible_plugins/connection_plugins
< lookup_plugins     = /usr/share/ansible_plugins/lookup_plugins
< vars_plugins       = /usr/share/ansible_plugins/vars_plugins
< filter_plugins     = /usr/share/ansible_plugins/filter_plugins

---
> #action_plugins     = /usr/share/ansible/plugins/action
> #callback_plugins   = /usr/share/ansible/plugins/callback
> #connection_plugins = /usr/share/ansible/plugins/connection
> #lookup_plugins     = /usr/share/ansible/plugins/lookup
> #vars_plugins       = /usr/share/ansible/plugins/vars
> #filter_plugins     = /usr/share/ansible/plugins/filter
> #test_plugins       = /usr/share/ansible/plugins/test
```
##### Environment:

Running on Archlinux, managing using `local` connection.
##### Summary:

I am trying to write a role that uses `with_items` along with `roles`, with Ansible 2. Unfortunately, the `item` variable does not seem exported.
##### Steps To Reproduce:

Try running the following playbook, that includes a dummy role.

File `vpnclients.yml`

``` yaml

---
- hosts: vpnclients
  roles:
    - role: openvpn-client
      openvpn_client_server: "{{ item }}"
      with_items: "{{ groups['vpnservers'] }}"
```

File `roles/openvpn-client/tasks/main.yml`

``` yaml

---
- debug: msg='calling for server {{ openvpn_client_server }}'
```
##### Expected Results:

Without the `{{ openvpn_client_server }}` part, I get the expected `calling for server` output.
##### Actual Results:

Instead, with the `{{ openvpn_client_server }}` part, I get the following error message:

```
fatal: [hostname]: FAILED! => {"failed": true, "msg": "ERROR! ERROR! 'item' is undefined"}
```

**Comment by jimi-c** [comment]
@Ekleog this is not supported syntax. You cannot use with_ loops on roles in this manner, and any loops should be done within the role.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by skinlayers** [comment]
@jimi-c According to ansible-example/language_features/roletest2.yml, this should be supported. Any idea if this worked at one point, but was later removed? We should probably update the example if that's the case.

https://github.com/ansible/ansible-examples/blob/master/language_features/roletest2.yml

**Comment by PumpkinSeed** [comment]
I got the same problem, and I found this: http://rogersherman.com/a-simple-how-to-passing-a-loop-to-an-ansible-role/

**Comment by aboyett** [comment]
@skinlayers that example using with_items was modified the day after @PumpkinSeed's comment in commit https://github.com/ansible/ansible-examples/commit/f72887ab1b762363c89392fb56c4d6569c5893c9
though the comment, https://github.com/ansible/ansible-examples/blob/f72887ab1b762363c89392fb56c4d6569c5893c9/language_features/roletest2.yml#L35-L36 no longer makes sense after the modification
