### ISSUE TITLE
More informative error message when field receives invalid JSON

### ISSUE THREAD

**Issue by samzhang111** [ansible/ansible#12624]
In a task, I used a string where a dictionary was expected. The error I received was `msg: dictionary requested, could not parse JSON or key=value` (https://github.com/idano/home/blob/master/lib/ansible/module_utils/basic.py#L694). This contained no information about which line in my configuration was wrong.

To figure out which of my values was wrong, I patched my local install of Ansible to spit out the key and value of the field. Any interest in a pull request?

**Comment by jimi-c** [comment]
@samzhang111 yes, please send one in.

Thanks!

**Comment by samzhang111** [comment]
Hm, nevermind, looks like that's already caught in this commit for 2.0.0: https://github.com/ansible/ansible/commit/be6db1a730270a8e89636da9630dcac8e3e093fc

:)
