### ISSUE TITLE
'delegate_to: localhost': unsupported parameter for module on v2

### ISSUE THREAD

**Issue by Tahvok** [ansible/ansible#12647]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.0.0 (devel 5ae74f7d38) last updated 2015/10/06 17:05:11 (GMT +300)
  lib/ansible/modules/core: (detached HEAD d659c79db7) last updated 2015/10/06 17:05:13 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/06 17:05:13 (GMT +300)
  config file = /home/albert/.ansible.cfg
  configured module search path = None
##### Environment:

Arch linux
Remote machine: centos 7
##### Summary:

When running a task with `delegate_to: localhost` or `delegate_to: 127.0.0.1` an error is received.

No problem on 1.9.3
##### Steps To Reproduce:

Run the following playbook:

``` yaml

---
- hosts: serbtest
  tasks:
    - shell: "whoami"
      delegate_to: localhost
```
##### Expected Results:

The task should run on localhost
##### Actual Results:

The following error is received. The error is different for some modules:

This warning is received first:

```
 [WARNING]: no remote address found for delegated host localhost, using its name by default
```

And then a similar error:

`shell` module:

```
fatal: [serbtest -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: b'_uses_shell'"}
```

 `replace` module:

```
fatal: [serbtest -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: b'replace'"}
```

**Comment by jimi-c** [comment]
@Tahvok it looks like you may not have updated the submodules, or your system is finding old modules. I did identify one bug here (using 'localhost' is not resetting the connection type to `local`), however after fixing that this runs as expected:

<pre>
ansible-playbook -vv 12647.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in 12647.yml
PLAY ***************************************************************************
TASK [setup] *******************************************************************
ok: [awxlocal]
TASK [command] *****************************************************************
changed: [awxlocal] => {"changed": true, "cmd": "whoami", "delta": "0:00:00.003073", "end": "2015-10-06 17:10:41.673279", "rc": 0, "start": "2015-10-06 17:10:41.670206", "stderr": "", "stdout": "testing", "stdout_lines": ["testing"], "warnings": []}
TASK [command] *****************************************************************
 [WARNING]: no remote address found for delegated host localhost, using its name by default
changed: [awxlocal -> localhost] => {"changed": true, "cmd": "whoami", "delta": "0:00:00.003563", "end": "2015-10-06 17:10:41.771844", "rc": 0, "start": "2015-10-06 17:10:41.768281", "stderr": "", "stdout": "root", "stdout_lines": ["root"], "warnings": []}
PLAY RECAP *********************************************************************
awxlocal                   : ok=3    changed=2    unreachable=0    failed=0   
</pre>

Can you confirm how you installed this, and if you have any old installations?

**Comment by Tahvok** [comment]
I have removed the repository, and recreated it now:

```
┌(albert@albert-arch)─(10:28:45 Wed Oct 07)
└─(~/git)─> git clone git://github.com/ansible/ansible.git --recursive
Cloning into 'ansible'...
remote: Counting objects: 96563, done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 96563 (delta 48), reused 0 (delta 0), pack-reused 96457
Receiving objects: 100% (96563/96563), 35.01 MiB | 714.00 KiB/s, done.
Resolving deltas: 100% (57311/57311), done.
Checking connectivity... done.
Submodule 'lib/ansible/modules/core' (https://github.com/ansible/ansible-modules-core) registered for path 'lib/ansible/modules/core'
Submodule 'lib/ansible/modules/extras' (https://github.com/ansible/ansible-modules-extras) registered for path 'lib/ansible/modules/extras'
Cloning into 'lib/ansible/modules/core'...
remote: Counting objects: 28665, done.
remote: Total 28665 (delta 0), reused 0 (delta 0), pack-reused 28665
Receiving objects: 100% (28665/28665), 7.82 MiB | 952.00 KiB/s, done.
Resolving deltas: 100% (18962/18962), done.
Checking connectivity... done.
Submodule path 'lib/ansible/modules/core': checked out 'd659c79db7335a7a81594f7d977cb6bb67e9c5a3'
Cloning into 'lib/ansible/modules/extras'...
remote: Counting objects: 27478, done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 27478 (delta 15), reused 0 (delta 0), pack-reused 27440
Receiving objects: 100% (27478/27478), 7.49 MiB | 1.07 MiB/s, done.
Resolving deltas: 100% (18140/18140), done.
Checking connectivity... done.
Submodule path 'lib/ansible/modules/extras': checked out '0ff1776a8424b166f632ee9199a04d85454dd76d'
(ansible)
┌(albert@albert-arch)─(10:29:53 Wed Oct 07)
└─(~/git)─> cd ./ansible
(ansible)
┌(albert@albert-arch)─(10:30:12 Wed Oct 07)
└─(~/git/ansible)─> source ./hacking/env-setup
running egg_info
creating lib/ansible.egg-info
writing requirements to lib/ansible.egg-info/requires.txt
writing lib/ansible.egg-info/PKG-INFO
writing top-level names to lib/ansible.egg-info/top_level.txt
writing dependency_links to lib/ansible.egg-info/dependency_links.txt
writing manifest file 'lib/ansible.egg-info/SOURCES.txt'
reading manifest file 'lib/ansible.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'v2'
no previously-included directories found matching 'docsite'
no previously-included directories found matching 'ticket_stubs'
no previously-included directories found matching 'packaging'
no previously-included directories found matching 'test'
no previously-included directories found matching 'hacking'
no previously-included directories found matching 'lib/ansible/modules/core/.git'
no previously-included directories found matching 'lib/ansible/modules/extras/.git'
writing manifest file 'lib/ansible.egg-info/SOURCES.txt'

Setting up Ansible to run out of checkout...

PATH=/home/albert/git/ansible/bin:/home/albert/.virtualenvs/ansible/bin:/home/albert/git/ansible/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/albert/.gem/ruby/2.2.0/bin:/opt/android-sdk/tools:/home/albert/bin
PYTHONPATH=/home/albert/git/ansible/lib:
MANPATH=/home/albert/git/ansible/docs/man:

Remember, you may wish to specify your host file with -i

Done!

(ansible)
```

Still got the same error:

```
┌(albert@albert-arch)─(10:30:29 Wed Oct 07)
└─(✗)─(~/ansible)─> ansible --version
ansible 2.0.0 (devel 9e364c2eb5) last updated 2015/10/07 10:29:32 (GMT +300)
  lib/ansible/modules/core: (detached HEAD d659c79db7) last updated 2015/10/07 10:29:43 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/07 10:29:53 (GMT +300)
  config file = /home/albert/ansible/ansible.cfg
  configured module search path = None
(ansible)
┌(albert@albert-arch)─(10:31:58 Wed Oct 07)
└─(~/ansible)─> ansible-playbook tests/shell.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [serbtest]

TASK [command] *****************************************************************
 [WARNING]: no remote address found for delegated host localhost, using its name by default

fatal: [serbtest -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: b'_raw_params'"}

PLAY RECAP *********************************************************************
serbtest                   : ok=1    changed=0    unreachable=0    failed=1   

(ansible)
```

It's not my first time running from source. I usually just update the repository with this commands:
$ git pull --rebase
$ git submodule update --init --recursive

And source env:
$ source ./hacking/env-setup

The strange thing is that running `git submodule update --init --recursive` on the repo (the new one I just cloned, and the old) would return nothing. As if something is broken:

```
┌(albert@albert-arch)─(10:34:14 Wed Oct 07)
└─(~/git/ansible)─> git submodule update --init --recursive
(ansible)
┌(albert@albert-arch)─(10:34:30 Wed Oct 07)
└─(~/git/ansible)─> 
```

**Comment by jimi-c** [comment]
Per further debugging, we've identified two other bugs (one of which is directly related to this, the other indirectly), so closing this as not an issue.

Thanks!
