### ISSUE TITLE
Add git commit hash to ansible --version (or --version -v)

### ISSUE THREAD

**Issue by fabianbadoi** [ansible/ansible#12641]
I've been using ansible for a few months now and have just had a problem after upgrading and had to downgrade back.

Unfortunately, I didn't know which commit to checkout and I spent a fair deal of time trying to find one that worked. A colleague of mine had a working installation, but didn't know which commit. Both his installation and all the versions I had had `$ ansible --version -> 2.0.0`.

I'd like to propose adding the git commit hash to the output of --version to aid in debugging upgrade problems, especially since the ["What version to pick?"](http://docs.ansible.com/ansible/intro_installation.html#what-version-to-pick) section of the installation guide recommends installing from the devel branch.

A list of previously installed versions with the time of updating would be even better.

Thank you for your time.

**Comment by bcoca** [comment]
already there:

```
ansible 2.0.0 (devel de155c6b14) last updated 2015/10/12 10:20:55 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 79e253053a) last updated 2015/10/09 12:34:13 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 205115ea1f) last updated 2015/10/09 12:34:15 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = /home/bcoca/work/ansible-modules-core:/home/bcoca/work/ansible-modules-extras
```
