### ISSUE TITLE
Local fact not passed

### ISSUE THREAD

**Issue by ticktockhouse** [ansible/ansible#12655]
Hello,

Ansible_version: 1.9.2 stable

I have a custom fact, generated via bash:

```
#!/bin/bash

MYSQL_PW=$(cat /etc/psa/.psa.shadow)

cat << EOF
{

    "pw":"$MYSQL_PW"

}
EOF
```

When I run this on the command line, it gives the expected output:

```
{

    "pw":"$AES-128-xxxx$xxxxxxxxxxxxxxxxxxx$xxxxxxxxxxxxxxxxxxx"

}
```

(note: the above is obfuscated)

However when I use the setup module, the value of "pw" is empty:

```
"ansible_local": {
            "mysql": {
                "pw": ""
            }
        },
```

I tested this by catting another file, and this gave the expected string when ran standalone and via the setup module:

```
......
MYSQL_PW=$(cat /usr/local/psa/version)
.....
```

gives

```
"ansible_local": {
       "mysql": {
           "pw": "12.0.18 Ubuntu 14.04 1200150817.13"
       }
   },
```

which is what we expect. I think the error is due to the presence of "$" in the output of the first fact-generating script, but I'm not sure how to get round this.

**Comment by sivel** [comment]
The likely problem is that you aren't creating valid JSON.  Instead of a shell script it would likely be worthwhile to use a language with JSON serialization support, such as Python.

**Comment by sivel** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
