### ISSUE TITLE
ansible-galaxy --install tracebacks

### ISSUE THREAD

**Issue by wenottingham** [ansible/ansible#12651]
##### Issue Type:

Bug Report
##### Ansible Version:

2.0 beta 1

Alternatively:

```
-bash-4.2$ ansible --version
Unexpected Exception: cannot import name range
the full traceback was:

Traceback (most recent call last):
  File "/bin/ansible", line 66, in <module>
    from ansible.cli.adhoc import AdHocCLI as mycli
  File "/usr/lib/python2.7/site-packages/ansible/cli/adhoc.py", line 22, in <module>
    from ansible.executor.task_queue_manager import TaskQueueManager
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 34, in <module>
    from ansible.playbook.play_context import PlayContext
  File "/usr/lib/python2.7/site-packages/ansible/playbook/play_context.py", line 30, in <module>
    from six.moves import range
ImportError: cannot import name range
```
##### Ansible Configuration:

Nothing special
##### Environment:

CentOS 7, Fedora 22
##### Summary:

```
$ ansible-galaxy install -r roles/requirements.yml -p roles/ --force -vvv
Using /home/notting/.ansible.cfg as config file
- extracting owncloud to roles/owncloud
- owncloud was installed successfully
Unexpected Exception: 'NoneType' object is not iterable
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 79, in <module>
    sys.exit(cli.run())
  File "/usr/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 125, in run
    self.execute()
  File "/usr/lib/python2.7/site-packages/ansible/cli/__init__.py", line 96, in execute
    fn()
  File "/usr/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 351, in execute_install
    for dep in role_dependencies:
TypeError: 'NoneType' object is not iterable
```

```
$ cat roles/requirements.yml
- src: http://github.com/wenottingham/ansible-role-owncloud
  name: owncloud
```
##### Steps To Reproduce:

see above commandline and requirements file
##### Expected Results:

succeeds without traceback
##### Actual Results:

succeeds with traceback

**Comment by wenottingham** [comment]
In this case, the role's metadata has:

```
dependencies:
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
```

**Comment by wenottingham** [comment]
Dumb fix:

```
diff --git a/lib/ansible/cli/galaxy.py b/lib/ansible/cli/galaxy.py
index 16aff1f..5fce43f 100644
--- a/lib/ansible/cli/galaxy.py
+++ b/lib/ansible/cli/galaxy.py
@@ -348,6 +348,8 @@ class GalaxyCLI(CLI):
             # install dependencies, if we want them
             if not no_deps and installed:
                 role_dependencies = role.metadata.get('dependencies', [])
+                if not role_dependencies:
+                    role_dependencies = []
                 for dep in role_dependencies:
                     self.display.debug('Installing dep %s' % dep)
                     dep_req = RoleRequirement()
```

Correct fix:
... have galaxy role parser coerce None for all metadata items? (It currently doesn't do any postprocessing of the yaml-returned data.)

**Comment by bcoca** [comment]
try now, i think i fixed via 638bc14566f8f1044d1bbd8f57e68c348ec82b89

**Comment by jimi-c** [comment]
This is two issues as well, the --version option is causing a traceback in a different section of code, which should be fixed.

**Comment by bcoca** [comment]
version issue has it's own ticket already #12004

**Comment by wenottingham** [comment]
:+1: :shipit:

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
