### ISSUE TITLE
log_driver: fluentd in Docker module

### ISSUE THREAD

**Issue by halest** [ansible/ansible#12665]
Hello,

I am trying to automate some dockerization-processes, but according to the documenation, the currently available log_drivers do not include fluentd and it will not recognize the parameter.
Is adding fluentd planned for the near future? Is there a workaround for this?

Thanks

**Comment by jimi-c** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
