### ISSUE TITLE
Expand cache plugin to include inventory

### ISSUE THREAD

**Issue by bcoca** [ansible/ansible#12670]
##### Issue Type:
- Feature Idea
##### Ansible Version:

Future
##### Ansible Configuration:

N/A
##### Environment:

All
##### Summary:

Allow current fact cache plugin to also be used to cache inventory information, this will remove the need for inventory scripts to keep their own cache and allow control of the cache from within ansible. Also this allows us to remove several different caching implementations done in the inventory scripts.

in ansible.cfg:
inventory_cache: yes/no
or make it a key returned from the inventory script itself 'cacheable: yes/no' (assume no if absent).

This will also allow the new `meta: refresh_inventory` directive to easily bypass the cache.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by vazhnov** [comment]
Added in 49d88cef9c5cef2dde0424c6cbe3fb5a237cecd4

**Comment by bcoca** [comment]
no, that commit does not do anything of the sort

**Comment by bcoca** [comment]
dupe of #12476
