### ISSUE TITLE
ansible running shell on wrong machine

### ISSUE THREAD

**Issue by orderedchaosdev** [ansible/ansible#12697]
Issue Type:

Bug Report

Ansible Version:

ansible devel 17c75df

Ansible Configuration:

N/A

Environment:

N/A

Summary:

Running a basic shell command returns the output from the wrong host

Steps To Reproduce:

```
ansible host-1 -m shell -a "hostname"
```

Expected Results:

```
host-1.com
```

Actual Results:

```
ansible-server.com
```

**Comment by bcoca** [comment]
I cannot reproduce this, can you give us more information on how to do so?

**Comment by orderedchaosdev** [comment]
I will check it again on the current devel branch later today

**Comment by orderedchaosdev** [comment]
Sorry for late response, it was resolved in a newer devel branch.
