### ISSUE TITLE
Unable to provide access to user on same database while repeating script

### ISSUE THREAD

**Issue by amitk79** [ansible/ansible#12721]
Hello,

Ansible Version: 1.9.2
Environment: Ubuntu 14.04

Summary:
I am running mysql_user module to create database and then add user and provide access to that user on defined items.

But when I am running same script again, it is failing on providing access.

Script I was using:
- name: Create  databases
  mysql_db: login_host=127.0.0.1 login_user=root login_port=3307 login_password= name="{{db_user}}" state=present collation=utf8_general_ci encoding=utf8
- name: Add deploy DB user and allow access to database2
  mysql_user: login_host=127.0.0.1 login_user=root login_port=3307 login_password= name="{{db_user}}" password="{{db_pass}}" host="{{item}}" priv="{{db}}".*:ALL,GRANT state=present
  with_items:
  - "{{ansible_hostname}}"
  - 127.0.0.1
  - ::1
  - "{{custom_server}}"

It is failing on providing access to  - "{{ansible_hostname}}" other 3 items are working good and shows OK.

Here is screenshot of error:

![imgo 2](https://cloud.githubusercontent.com/assets/6582086/10456910/4f7f13c0-71e1-11e5-8029-4c094d969f79.jpg)

When I look into db users, there is already username present with access to anible_hostname variable.

I have to then delete that user manually and it worked after that.

Can you please let us know what should be possible reason for it or anything wrong I am doing ?

Note: It was failing  only on one machine, I was not able to reproduce this error on other machines.

**Comment by amitk79** [comment]
Gentle Reminder: Can we have any update on it please  ?
We need to fix an issue on client side so early response will be appreciated.

**Comment by abadger** [comment]
Hi, it looks like this is a problem with the mysql_user module which lives in a separate repository.  If you could refile it here: https://github.com/ansible/ansible-modules-core/  that would help out.  I noticed that this is only failing for you on one machine out of three.  When you refile, could you include some information about some of the differences between the machine?  is the failing one using a different version of mysql?  Are they all the same operating system?  Is the MySQL-python package version the same for all of them?  Thanks!
