### ISSUE TITLE
ansible playbook failed to run because of SSH 

### ISSUE THREAD

**Issue by gbane2012** [ansible/ansible#12729]
I am trying to run a playbook and Ansible failed and whenever I run the script with the debug( ansible-playbook - i inventory/prod deploy_system_status.yml -vvvv)
i am having error : permission denied (publickey) 
root@ip-172-16-20-180:/var/lib/jenkins/jobs/build-cs-utils/workspace/playbooks# ansible-playbook -i inventory/prod deploy_system_status.yml -vvvv
Enter the version you want to deploy: 

PLAY [Deploy to status  servers] *********************************************\* 

GATHERING FACTS **************************************************************\* 
<172.16.21.129> ESTABLISH CONNECTION FOR USER: ubuntu
<172.16.21.129> REMOTE_MODULE setup
<172.16.21.129> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o IdentityFile="/root/credentials/ansible_id_rsa" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 172.16.21.129 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1444745533.97-6293361069708 && echo $HOME/.ansible/tmp/ansible-tmp-1444745533.97-6293361069708'
fatal: [prodstatus0] => SSH Error: Permission denied (publickey).
    while connecting to 172.16.21.129:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

TASK: [nodejs_app | Put upstart script in place] *****************************\* 
FATAL: no hosts matched or all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/deploy_system_status.retry

prodstatus0                : ok=0    changed=0    unreachable=1    failed=0

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
