### ISSUE TITLE
Custom filter plugins become unavailable part way through a playbook

### ISSUE THREAD

**Issue by RusDavies** [ansible/ansible#12738]
# Issue

A custom filter may become unavailable part way through a playbook, after already having been used at least once & without apparent problems.

A git repo demonstrating this problem is provided [here](https://github.com/RusDavies/ansible_plugin_problem/tree/master).  The "master" branch provides a playbook that demonstrates the issue, whereas the "works" branch demonstrates the same playbook with an include statement commented out (in `roles/eg-role/tasks/main.yml`), which then seems to allow success.

Of note, the playbook fails if the include is present at all, even with all of the contents of the included file commented out.  

The same playbook seems to work without issue on Ansible 1.9.3.  
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = None
```
##### Ansible Configuration:

Stock, per Fedora 21. 
##### Environment:

Stock Fedora 21
##### Summary:

A custom filter becomes unavailable part way through a playbook, even though it was successfully used at least once. 
##### Steps To Reproduce:

Success on Ansible 1.9.3:
1. Checkout the master branch of [this repository](https://github.com/RusDavies/ansible_plugin_problem)
2. Install Ansible 1.9.3 from stock Fedora repositories
3. Run ```ansible-playbook -vvv eg.yml'
4. Observe the playbook completes successfully

Fail on Ansible 2.0.30
1. Install Ansible 2.0.0.x from git (see [here](http://docs.ansible.com/ansible/intro_installation.html#latest-release-via-yum))
2. Rerun ```ansible-playbook -vvv eg.yml' on [the playbook](https://github.com/RusDavies/ansible_plugin_problem)
3. Observe that the playbook outputs from task "eg-role : debug var=eg_destroy", indicating one successful use of the custom filter plugin
4. Observe that the playbook fails in task "eg-role : debug var=eg_create", with an error about the (already used) custom filter not being available.

Quasi-Success on Ansible 2.0.0:
1. Checkout the "works" branch of [this repo](https://github.com/RusDavies/ansible_plugin_problem) (which merely comments out an include in `roles/eg-role/tasks/main.yml`) 
2. Rerun ```ansible-playbook -vvv eg.yml'
3. Observe the playbook completes successfully, albeit with missing functionality
##### Expected Results:

The playbook should complete successfully, with the custom plugin being available upon each invocation. 
##### Actual Results:

The playbook in this git repo works on Ansible 1.9.3; but not on Ansible 2.0.X, wherein it fails with a ``no filter named 'byattr'` error, as follows: 

``` shell
$ ansible-playbook eg.yml 

PLAY [Manage 'eg' Resources] ***************************************************

TASK [include_vars] ************************************************************
ok: [localhost -> localhost]

TASK [eg-role : Ensure the existence and basic structure of the state file] ****
included: ./state-file.yml for localhost

TASK [eg-role : Ensure the state file exists] **********************************
ok: [localhost -> localhost]

TASK [eg-role : Ensure the sections in the state file exist] *******************
ok: [localhost] => (item=vpcs)

TASK [eg-role : Manage EG items (destroy)] *************************************
included: destroy.yml for localhost

TASK [eg-role : Extract the examples with state=0] *****************************
 [WARNING]: no remote address found for delegated host 127.0.0.1, using its name by default

ok: [localhost -> localhost]

TASK [eg-role : debug var=eg_destroy] ******************************************
ok: [localhost -> localhost] => {
    "changed": false, 
    "eg_destroy": [
        {
            "name": "eg_1", 
            "state": 0
        }
    ]
}

TASK [eg-role : Ensure the existence and basic structure of the state file] ****
included: ./state-file.yml for localhost

TASK [eg-role : Ensure the state file exists] **********************************
ok: [localhost -> localhost]

TASK [eg-role : Ensure the sections in the state file exist] *******************
ok: [localhost] => (item=vpcs)

TASK [eg-role : Manage EG items (create)] **************************************
included: create.yml for localhost

TASK [eg-role : Extract the examples with state=1] *****************************
 [WARNING]: no remote address found for delegated host 127.0.0.1, using its name by default

fatal: [localhost -> 127.0.0.1]: FAILED! => {"failed": true, "msg": "ERROR! template error while templating string: no filter named 'byattr'"}

PLAY RECAP *********************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=1  
```

**Comment by RusDavies** [comment]
## Additional observations:
1. Adding my custom filter directly into `lib/ansible/plugins/filter/core.py` works fine.  
2. Similarly, adding the filter as a new file `lib/ansible/plugins/filter/btinc.py` also works. 
3. So does renaming the original custom filter plugin from `./filter_plugins/core.py` to `./filter_plugins/btinc.py`
4. Finally, deliberately giving the custom filter plugin a filename that already exists under `lib/ansible/plugins/filter/` results in the reported failure. 

Therefore, it would seem that some kind of overwriting is happening, when giving a custom filter plugin a non-unique filename in Ansible 2.0.0.

## Conclusion:
1. This issue can be avoided by taking care to give a unique file name to custom filter plugins. 
2. Ansible 1.9.3 doesn't exhibit this behaviour.  
3. IMHO, the 1.9.3 behaviour is preferable, wherein the user didn't need to be aware of all filter plugin filenames that exist, in order to avoid a conflict.  

Although I now have a work-around, I'm leaving this issue open, because I consider the new behaviour to be a bug.   At the very least, the [documentation](http://docs.ansible.com/ansible/developing_plugins.html) should make note of the need to use unique filenames.

**Comment by jimi-c** [comment]
Hi @RusDavies, as you noted this bug is tied to the core.py file name (and was previously reported here: https://github.com/ansible/ansible/issues/11481). I thought we had fixed that, but apparently we simply worked around it. I was never quite able to pin down why/where in the plugin loader code this was breaking, but for now I'd recommend renaming your file to avoid conflicting with those we have in the directory we ship.

**Comment by RusDavies** [comment]
Thanks @jimi-c .  To be clear, for the benefit of others, it's not just `core.py` that conflicts, but also any filename that already exists as a core filter, such as `ipaddr.py`.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
