### ISSUE TITLE
Environment var `ANSIBLE_INVENTORY` not being used on OS X 

### ISSUE THREAD

**Issue by ssteinerx** [ansible/ansible#12746]
Running a devel branch checkout on OS X 10.7.5 with Python 2.7.10.

Docs (http://docs.ansible.com/ansible/intro_installation.html) say this:

```
$ echo "127.0.0.1" > ~/ansible_hosts
$ export ANSIBLE_INVENTORY=~/ansible_hosts
```

And added ANSIBLE_INVENTORY to .bash_profile; it shows up in the environment as you can see below.

But I get this (IP's manually XXX'd out):

```
# python -V
Python 2.7.10

# cat $ANSIBLE_INVENTORY
127.0.0.1
209.XXX.XXX.225

# ansible  all -m ping
ERROR: Unable to find an inventory file, specify one with -i ?

# ansible  all -m ping -i $ANSIBLE_INVENTORY
209.XXX.XXX.225 | success >>{
    "changed": false,
    "ping": "pong"
}
127.0.0.1 | success >> {
    "changed": false,
    "ping": "pong"
}
```

**Comment by ssteinerx** [comment]
Brew version from a while ago vs. manual install conflict.

**Comment by whyvez** [comment]
@ssteinerx I installed Ansible via Homebrew and am having the same issue. Can you explain how you solved the problem? Setting the `ANSIBLE_INVENTORY` env var and sourcing it from my `~/.bash_profile` but 'ansible-playbook` doesn't seem to use it.

**Comment by bcoca** [comment]
@whyvez homebrew breaks some of the defaults, that is why we removed it from our docs as recommended install method. I suggest you use pip and/or run from git instead.
