### ISSUE TITLE
known_hosts module with local_action will fail (due to (not) locking) when doing multiple updates

### ISSUE THREAD

**Issue by sigio** [ansible/ansible#12743]
ansible 1.9.2

(This should maybe be in ansible/extra-modules ?)

I have a role (to deploy new VM's), that after installation will probe the ssh-fingerprints of the newly build VM's, and try to add these to the running user's know_hosts file using the known_hosts module and local_action:

--------- part of the role ------
- name: Find ssh fingerprint
  shell: "ssh-keyscan {{kickstart_ip}}"
  delegate_to: "{{vmhost}}"
  register: sshfingerprint
- name: Remove old known_host entries
  local_action: "known_hosts name='{{kickstart_ip}}' state=absent"
  sudo: no
- name: Add fingerprint to known_hosts
  local_action: "known_hosts name='{{kickstart_ip}}' state=present key='{{sshfingerprint.stdout}}'"
  sudo: no                                                                                                    

---

However, this will mostly fail on one or more hosts (when running with 4 hosts) due to:

TASK: [buildvm | Remove old known_host entries] ******************************\* 
changed: [testvm3 -> 127.0.0.1]
failed: [testvm4 -> 127.0.0.1] => {"cmd": "/usr/bin/ssh-keygen -R 172.16.4.14 -f /home/mark/.ssh/known_hosts", "failed": true, "rc": 255}
stderr: link /home/mark/.ssh/known_hosts to /home/mark/.ssh/known_hosts.old: File exists

msg: link /home/mark/.ssh/known_hosts to /home/mark/.ssh/known_hosts.old: File exists
changed: [testvm2 -> 127.0.0.1]
failed: [testvm1 -> 127.0.0.1] => {"cmd": "/usr/bin/ssh-keygen -R 172.16.4.11 -f /home/mark/.ssh/known_hosts", "failed": true, "rc": 255}
stderr: link /home/mark/.ssh/known_hosts to /home/mark/.ssh/known_hosts.old: No such file or directory

msg: link /home/mark/.ssh/known_hosts to /home/mark/.ssh/known_hosts.old: No such file or directory

In this case, it worked fine on 2 entries, and failed on the other 2, due to a race condition.
It seems there is no way to limit this by using 'serial: 1' or something, as this can't be done within a role.

I guess the known_hosts module should create a lock and check for that, and wait if a lock is present, to prevent it from trying to run multiple times simultaniously.

**Comment by jimi-c** [comment]
@sigio yes, this should be moved to ansible-modules-extras.

Thanks!

**Comment by jmehnle** [comment]
So, can the Ansible maintainers please move this issue to the `ansible-modules-extra` tracker? Otherwise I'm going to file a 100% identical issue there in a few days.

**Comment by jimi-c** [comment]
@jmehnle go for it, we can't relocate issues ourselves and preserve ownership, so we generally ask the original reporter to do so. As this one has not, feel free to open a new issue for it yourself.

**Comment by jmehnle** [comment]
Filed as https://github.com/ansible/ansible-modules-extras/issues/2489.
