### ISSUE TITLE
plugins/callback/profile_tasks.py: wrong timing / skipped tasks

### ISSUE THREAD

**Issue by jlaffaye** [ansible/ansible#12762]
## Wrong timing for the last task when running handlers

The report includes the total execution time of the handlers for the last task.
## Skipped tasks not handled

When a taks, is skipped, the following warning is printed:

```
[WARNING]: Error when using <bound method CallbackModule.v2_runner_on_skipped of <ansible.plugins.callback.profile_tasks.CallbackModule object at 0x7f1722fdb350>>: 'item'
```

**Comment by bcoca** [comment]
2 issues reported, I cannot reproduce the 'skipped' issue

i was able to reproduce the handler issue
