### ISSUE TITLE
{{ group_names }} now includes 'all' group

### ISSUE THREAD

**Issue by sylr** [ansible/ansible#12763]
Hi,

Before VariableManager existed, the **{{ group_names }}** var was filled with the result of **Host.get_variables()** which strips down the 'all' group (https://github.com/ansible/ansible/blob/release1.8.4/lib/ansible/inventory/host.py#L64).

Now magic vars seems to be populated with the **VariableManager._get_magic_variables()** (https://github.com/ansible/ansible/blob/devel/lib/ansible/vars/__init__.py#L333) but the explicit strip down of the 'all' group has disappeared.

Is this change of behaviour wanted ?

**Comment by jimi-c** [comment]
@sylr looks like this was an oversight, which should be fixed.

Thanks for catching it!
