### ISSUE TITLE
state=link not using sudo properly

### ISSUE THREAD

**Issue by binoche9** [ansible/ansible#12768]
Hi,

I'm trying to use the file module to create a symbolic link, and despite the fact that I'm giving my role sudo permissions, it doesn't want to create the link due to a lack of permission.

Here's my action:

```
file: src=~/node_modules/casperjs/bin/casperjs
      path=/usr/local/bin/casperjs
      state=link
      force=yes
become: yes
become_user: ubuntu
```

And I get this error:

> failed: [default] => {"failed": true, "path": "/usr/local/bin/casperjs", "state": "absent"}
> msg: Error while linking: [Errno 13] Permission denied

Meanwhile, if I do `sudo ln -s ~/node_modules/casperjs/bin/casperjs /usr/local/bin/casperjs` in the terminal directly, that works without complains.

Clearly sudo is needed because I'm creating a link in the root directory, but for some reason the sudo permissions is not being used by the file module. Other tasks like `apt:` that need sudo permissions work fine, so it seems to me that the problem is with the file module.

I'm currently using Ansible 1.9.3 and trying to configure Ubuntu 14.04.

Please let me know if I'm overlooking anything. Thanks!

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case, it seems you are misunderstanding the become_user setting, the way you have it translates to `sudo -u ubuntu ln -s ...`. Remove it and it should work with the default 'root'.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
