### ISSUE TITLE
ansible-pull is broken in V2

### ISSUE THREAD

**Issue by mbobakov** [ansible/ansible#12777]
on all v2 branches

```
▶ date -u
Fri Oct 16 09:50:43 UTC 2015

▶ git status          
On branch devel
Your branch is up-to-date with 'origin/devel'.
nothing to commit, working directory clean
```

next 

```
▶ ansible-pull -d /tmp/sensu_checks_repo -U 'https://<REPO>.git' -vvv localhost
No config file found; using defaults
Starting Ansible Pull at 2015-10-16 12:41:59
<...CUT...>
Unexpected Exception: 'module' object has no attribute 'split'
the full traceback was:

Traceback (most recent call last):
  File "/home/mbobakov/ansible/bin/ansible-pull", line 80, in <module>
    sys.exit(cli.run())
  File "/home/mbobakov/ansible/lib/ansible/cli/pull.py", line 159, in run
    rc, out, err = run_cmd(cmd, live=True)
  File "/home/mbobakov/ansible/lib/ansible/utils/cmd_functions.py", line 28, in run_cmd
    cmdargs = shlex.split(cmd)
AttributeError: 'module' object has no attribute 'split'

```

**Comment by bcoca** [comment]
weird, split was added to shlex in 2.3, what version of python are you using?

**Comment by mbobakov** [comment]
Problem not in Python. I'm trying 2.6 and 2.7.
You are using not original shlex. You are using a wrapper with same name:  https://github.com/ansible/ansible/blob/14c80b8a04a2b950f550ba20ee3640257ad36e38/lib/ansible/utils/shlex.py and it don't contain method 'split'
Then this wrapper including in https://github.com/ansible/ansible/blob/12a2585e84be7fdf40e07ca1415f4938e95de1f3/lib/ansible/utils/cmd_functions.py#L20

//Sorry for my English =(

**Comment by bcoca** [comment]
ah, that was a recent update, I was not aware of cc @abadger
