### ISSUE TITLE
Ansible install via pip git+https gives RuntimeWarnings

### ISSUE THREAD

**Issue by ashemedai** [ansible/ansible#12778]
##### Issue Type:

Bug Report
##### Ansible Version:

2.0.0-devel
##### Environment:

Ubuntu 14.04, Python 2.7.6, git 1.9.1, pip 7.1.2
##### Summary:

Installing Ansible devel via pip install git+https yields a working Ansible installation, however using it yields a lot of RuntimeWarnings.
##### Steps To Reproduce:

% virtualenv ansible-test
% cd ansible-test
% source bin/activate
% pip install -U git+https://github.com/ansible/ansible
% rehash
% which ansible
/home/ashemedai/ansible-test/bin/ansible
% cd /path/to/ansible/playbooks
##### Expected Results:

% ansible-playbook playbooks/test.yml -i inventory/local -K
SUDO password:

PLAY [Test] ********************************************************************
##### Actual Results:

% ansible-playbook playbooks/test.yml -i inventory/local -K
SUDO password: 
/home/ashemedai/ansible-test/local/lib/python2.7/site-packages/ansible/plugins/filter/ipaddr.py:18: RuntimeWarning: Parent module '/home/ashemedai/ansible-test/local/lib/python2' not found while handling absolute import
  from functools import partial
/home/ash/ansible-test/local/lib/python2.7/site-packages/ansible/plugins/filter/ipaddr.py:19: RuntimeWarning: Parent module '/home/ashemedai/ansible-test/local/lib/python2' not found while handling absolute import
  import types
/home/ashemedai/ansible-test/local/lib/python2.7/site-packages/ansible/plugins/filter/ipaddr.py:22: RuntimeWarning: Parent module '/home/ashemedai/ansible-test/local/lib/python2' not found while handling absolute import
  import netaddr
/home/ashemedai/ansible-test/local/lib/python2.7/site-packages/ansible/plugins/filter/ipaddr.py:31: RuntimeWarning: Parent module '/home/ashemedai/ansible-test/local/lib/python2' not found while handling absolute import
  from ansible import errors
/home/ashemedai/ansible-test/local/lib/python2.7/site-packages/ansible/plugins/test/core.py:18: RuntimeWarning: Parent module '/home/ashemedai/ansible-test/local/lib/python2' not found while handling absolute import
  import re
/home/ashemedai/ansible-test/local/lib/python2.7/site-packages/ansible/plugins/test/core.py:19: RuntimeWarning: Parent module '/home/ashemedai/ansible-test/local/lib/python2' not found while handling absolute import
  from ansible import errors
/home/ashemedai/ansible-test/local/lib/python2.7/site-packages/ansible/plugins/test/files.py:18: RuntimeWarning: Parent module '/home/ashemedai/ansible-test/local/lib/python2' not found while handling absolute import
  from os.path import isdir, isfile, isabs, exists, lexists, islink, samefile, ismount
/home/ashemedai/ansible-test/local/lib/python2.7/site-packages/ansible/plugins/test/files.py:19: RuntimeWarning: Parent module '/home/ashemedai/ansible-test/local/lib/python2' not found while handling absolute import
  from ansible import errors

PLAY [Test] ********************************************************************

And many more lines like this.

Installing via a git clone, followed by a git submodule update, and installing via pip install -e yields a working Ansible 2 installation in virtualenv though.

**Comment by drybjed** [comment]
Confirming that the issue started after https://github.com/ansible/ansible/commit/d923d05a33431e9c4c9d3d03bdb4bbdfd4b90447 commit.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
