### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by arunthampi** [ansible/ansible#1278]
ansible crashes with this stack trace. This is an intermittent error and I'm not able to produce it consistently :(

```
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 245, in _executor
    exec_rc = self._executor_internal(host)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 300, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 384, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/action_plugins/copy.py", line 68, in run
    remote_md5 = self.runner._remote_md5(conn, tmp, dest)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 467, in _remote_md5
    return data.split()[0]
IndexError: list index out of range
```

this is the task where it fails

```
- name: setup stunnel to be enabled
  action: copy src=../../../global/files/default_stunnel4 dest=/etc/default/stunnel4 owner=root group=root mode=0660
```

The default_stunnel4 file is like so:

```
# /etc/default/stunnel
# Julien LEMOINE <speedblue@debian.org>
# September 2003

# Change to one to enable stunnel automatic startup
ENABLED=1
FILES="/etc/stunnel/*.conf"
OPTIONS=""

# Change to one to enable ppp restart scripts
PPP_RESTART=0
```

**Comment by mpdehaan** [comment]
First I've heard of this, unfortunately.   Here's something to try...

If you run with "-v -v -v" it will show the commands it is executing and
you can see the md5 command that fails.

There shouldn't be any randomness to it, I'd think, but it is likely the
remote md5 sum command is failing for some reason.

If you can identify the command and rerun it locally, we can find out what
it is returning and amend our call to deal with it.

The command should already deal with the file being missing and so forth,
and for the different md5 commands between systems.

The code is currently set to capture the /last/ non blank line of the md5
command, so the problem may still be with spurious warning
that may be filtered out incorrectly.

I can't be sure from what I have now, but the output of the command would
be useful.  If it's intermittent, would it be frequent enough
to reproduce if you had the full command?

**Comment by mpdehaan** [comment]
For what it's worth, I can definitely put in a workaround for the index out of range problem if the md5 command is failing intermittently, and we could just assume the file needs to be replaced in that particular case.

Though it would be better to know what is going on before we add that.

It may also be worth trying 0.8/devel, to pick up any fixes in the connection plugins.

**Comment by mpdehaan** [comment]
@arunthampi 

If you can test with 771c865 (in 0.8) it will now capture the error message when this occurs so we can fix it.   When it captures the error it also goes on to assume a different md5sum, which is fine, and will not affect whether the handler detects change correctly.  (This just means it may transfer a file unneccessarily, which is ok).   

If we can get the output back from a time when it fails, we can see what is wrong with the command and how we have to intercept the parsing of it.   Usually we intercept this level of static in the output in the connection plugins, so it should be an easy fix.

Please let me know.  Thanks!
