### ISSUE TITLE
Wrong attribution in README?

### ISSUE THREAD

**Issue by alflanagan** [ansible/ansible#12785]
I'll be happy to submit a pull request, but can't believe I'm the first to notice:

"Releases are named after Led Zeppelin songs."

Except most of the names in RELEASES.txt that I checked are actually by Van Halen, except the last two (The Kinks and David Bowie?)

**Comment by bcoca** [comment]
might need tweaking:

old releases after Van Halen, from 2.0 and going forward Led Zeppelin

**Comment by alflanagan** [comment]
Which I would realize if I'd properly checked the revision history. I've created a pull request with a clarification for those annoying OCD types who have to actually check these things. ;-)
Thanks.
