### ISSUE TITLE
Filter out returned data from modules if it came from a parameter marked as no_log

### ISSUE THREAD

**Issue by abadger** [ansible/ansible#12792]
Modules can have parameters marked as no_log.  That way you can give, for instance, a clear text password string and ansible won't log it in the list of parameters that it sent to a module.  However, it doesn't currently remove it from output of the module.  We should be able to look at all the strings we were given as values in parameters listed as no_log and then check for their presence in the output.  If the values are present, then remove them from the output.

**Comment by bcoca** [comment]
basically a filter function we need to call from exit_json and fail_json

**Comment by abadger** [comment]
Perhaps it would make sense to also have heuristic_log_sanitize() run the filter.

**Comment by bcoca** [comment]
i forgot we had that already, yes, seems perfect expansion of that function

**Comment by abadger** [comment]
See also c2d188baff9b0d6076187f36bf63543967c705a1 for the first half of this change.
