### ISSUE TITLE
variable from first play does not carry over to later plays

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#12814]
Issue Type: Bug Report
Ansible Version: 1.9.4
OS: Ubuntu 14.04

In the first play, I am trying to slurp a file's content on server A and store it in a variable. In the second play, I want to write out the contents of that variable to a file on server B.

inventory file:

<pre>
[serverA]
172.19.99.15
[serverB]
172.19.99.16
</pre>

playbook:

<pre>

---
- name: part one of playbook
  hosts: serverA
  gather_facts: no

  tasks:
   - name: slurp a file 
     slurp: src=/tmp/test.txt
     register: fileContents

   - debug: msg="{{ fileContents.content | b64decode }}"

- name: part two of playbook
  hosts: serverB
  gather_facts: no

  tasks:
   - debug: msg="{{ fileContents.content | b64decode }}"

   - name: write out contents of fileContents to a file
     file: "dest=/tmp/test.txt content={{ fileContents | b64decode }}"
</pre>

execution:

<pre>
$ ansible-playbook main.yml -i inventory -u root -k
SSH password: 

PLAY [part one of playbook] *********************************************** 

TASK: [slurp a file] ********************************************************** 
ok: [172.19.99.15]

TASK: [debug msg="{{ fileContents.content | b64decode }}"] ******************** 
ok: [172.19.99.15] => {
    "msg": "This is a test file to be slurped by ansible.\n"
}

PLAY [part two of playbook] *********************************************** 

TASK: [debug msg="{{ fileContents.content | b64decode }}"] **************************************** 
fatal: [172.19.99.16] => One or more undefined variables: 'fileContents' is undefined

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/tmp/main.retry

172.19.99.15              : ok=1    changed=0    unreachable=0    failed=0   
172.19.99.16              : ok=0    changed=0    unreachable=1    failed=0   
</pre>

**Comment by sivel** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
