### ISSUE TITLE
[v2] delegate_to shows incorrect delegated host

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#12819]
**Issue Type:** Bug Report
**Ansible Version:**

> ansible 2.0.0 (devel 1280e2296c) last updated 2015/10/19 08:38:39 (GMT +300)
>   lib/ansible/modules/core: (detached HEAD 5da7cf696c) last updated 2015/10/19 08:39:02 (GMT +300)
>   lib/ansible/modules/extras: (detached HEAD 632de528a0) last updated 2015/10/19 08:39:02 (GMT +300)

**Summary:**

When you've a task running that delegates somewhere else, Ansible shows it as "localhost -> localhost", instead of "localhost -> somewherreelse".

This doesn't happen _always_, but it's very easy to reproduce.

**Steps to Reproduce:**

Assume you've got a couple of machines called 'fridge' and 'muskatas'.
- Create an inventory file `hosts`:

```
fridge
```
- Create a playbook `test.yml`:

```

---
- hosts: localhost
  gather_facts: no
  tasks:
    - command: hostname
      delegate_to: muskatas
- hosts: fridge
  gather_facts: no
  tasks:
    - command: hostname
      delegate_to: muskatas
```
- Run `ansible-playbook -i hosts test.yml -v`

**Expected Results:**

```
PLAY [localhost] ************************************************************** 

TASK: [command hostname] ****************************************************** 
changed: [localhost -> muskatas] => {"changed": true, "cmd": ["hostname"], "delta": "0:00:00.001949", "end": "2015-10-19 09:39:22.972770", "rc": 0, "start": "2015-10-19 09:39:22.970821", "stderr": "", "stdout": "muskatas", "warnings": []}

PLAY [fridge] ***************************************************************** 

TASK: [command hostname] ****************************************************** 
changed: [fridge -> muskatas] => {"changed": true, "cmd": ["hostname"], "delta": "0:00:00.001933", "end": "2015-10-19 09:39:23.162487", "rc": 0, "start": "2015-10-19 09:39:23.160554", "stderr": "", "stdout": "muskatas", "warnings": []}

PLAY RECAP ******************************************************************** 
fridge                     : ok=1    changed=1    unreachable=0    failed=0   
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```

**Actual Results:**

```
Using /etc/ansible/ansible.cfg as config file

PLAY ***************************************************************************

TASK [command] *****************************************************************
changed: [localhost -> localhost] => {"changed": true, "cmd": ["hostname"], "delta": "0:00:00.001993", "end": "2015-10-19 09:37:04.205071", "rc": 0, "start": "2015-10-19 09:37:04.203078", "stderr": "", "stdout": "muskatas", "stdout_lines": ["muskatas"], "warnings": []}

PLAY ***************************************************************************

TASK [command] *****************************************************************
changed: [fridge -> localhost] => {"changed": true, "cmd": ["hostname"], "delta": "0:00:00.001939", "end": "2015-10-19 09:37:04.477565", "rc": 0, "start": "2015-10-19 09:37:04.475626", "stderr": "", "stdout": "muskatas", "stdout_lines": ["muskatas"], "warnings": []}

PLAY RECAP *********************************************************************
fridge                     : ok=1    changed=1    unreachable=0    failed=0   
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```

Note the changed lines saying `[localhost -> localhost]` and `[fridge -> localhost]` instead of `-> muskatas`.

Note how the actual stdout from running `hostname` confirms that the task is being delegated correctly.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
