### ISSUE TITLE
Document module documentation

### ISSUE THREAD

**Issue by timlnx** [ansible/ansible#1284]
Need reference material on modules.html for DOCUMENTATION strings.

Maybe add a reference document in the examples/ directory.

Bonus points: In the docsite directory make a symlink to ../examples/DOCUMENTATION (**clarification**: symlink because I _think_ sphinx won't look outside of a certain path you say your doc tree lives in) and use some RST/Sphinx wizardry to include the example document right in modules.html

**Comment by mpdehaan** [comment]
FYI, I am very tempted to remove the C() and I() and M() macros and just make some regex that turns URLs into links.

I would not document any of those.

**Comment by mpdehaan** [comment]
cc @jpmens

**Comment by timlnx** [comment]
@mpdehaan I left out the macros and sent in the PR, #1320

**Comment by jpmens** [comment]
**Please** don't remove the I(), C() and M() macros; I'll see if I can find how to fix the Sphinx CSS to make them less orangy ;-)

**Comment by mpdehaan** [comment]
Yeah I know a lot of effort went into this so I don't want to discount
that.   It meant well.

My issues is not only the orangeness, but also that no one is applying them
consistently.

You will find that, among also being highly megalomanical as a project
leader, I also really really like things to be consistent, and I find that
frustrating.

I don't really want them highlighted.   Single quoting and actual italics
may be reasonable, but if folks aren't going to use them completely
consistently, I'd really rather not have them, as they are a confusing "Not
Invented Here"
thing that I think makes our documentation more difficult to understand.
I think single quoting important terms solves the problem nicely.

The other thing I want this gone for is eventually various code will be
able to use this data directly, and I don't want it to have to parse the
description strings.

**Comment by jpmens** [comment]
> I also really really like things to be consistent

Agreed.

> I don't really want them highlighted.   Single quoting and actual italics
> may be reasonable

I understand you don't want them highlighted, and neither do I, but I am trying to find a solution which allows us to create documentation which looks good. I feel it's important to distinguish types of data, particularly if we (well, I) pursue the LaTeX way ...

The highlighting (orangy stuff) in Sphynx is in the CSS, which is trivial to tweak. I don't want colouring either, but I find it pleasing to see good-looking documentation.

> I don't want it to have to parse the
> description strings.

I feel parsing (with a regex) the description strings is going to be easier than finding some method of automatically parsing URLs (and maybe other future stuff). I'll admit to grasping for arguments to try and convince you ..... :-)

I've been thinking we could enable a more consistent approach with macros of the form  `F(filename)`, `M(modulename)`, `O(optionname)` work? I'm not sure whether that really makes things better, but if it helps to make documenters apply "formatting" more consistently, it may be the way to go.

`</ends_pleading>`

**Comment by mpdehaan** [comment]
I would rather see things like links or see also stuff broken out into
different data.

My ultimate use of this will be for things like bash completions, text UIs,
and Web UI have built-in information about module help.

Ultimately I have a LOT of experience dealing with pull requests form
people, and I can see them not adding these on a very very very very
regular basis, and not using them consistently, and this kind of makes my
life a headache trying to review and keep constant.

If we want to generate the PDF, I don't think it's a total loss if quoted
things appear as 'foo' versus monotype in the PDF.
