### ISSUE TITLE
Ansible Galaxy install fails when requirements.yml is empty

### ISSUE THREAD

**Issue by Ari-E-S** [ansible/ansible#12841]
It seems the issue is limited to the loop over the roles.

/lib/ansible/cli/galaxy.py#L313

```
 for role in yaml.safe_load(f.read()):
```

Possible solutions include checking if the result of yaml.safe_load(f.read()) is None or enclosing the whole loop in a try/except block.

**Comment by jimi-c** [comment]
ping @chouseknecht

**Comment by bcoca** [comment]
fixed via 1ecad5aed2ba51705ec04abf717e80d44490b5dd

**Comment by scottsb** [comment]
Is it necessary for Ansible to throw an exception when the requirements file is empty? For automation purposes, it seems like it would be better for it to just do nothing but still return successfully. A notice could be written to standard out noting that nothing was installed.

**Comment by Ari-E-S** [comment]
+1
An empty YAML file is still valid YAML and I don't think it is an error to have no requirements.

**Comment by fredleger** [comment]
+1
I don't really see the point to throw an error. This is tricky and i have to download a fake role for testing some roles with CI using the same template. Marked as fixed but this is stille the case with recent versions of ansible installed with pip (2.2.0). Which version is fixing this ?

**Comment by bcarpio** [comment]
Can we get a second look at this or should we open a second bug report for it? There is no reason to throw an exception when the requirements.yml file is empty. This forces me to build ansible roles which are inconsistent from a templating perspective. I have to comment out the requirements_path for roles which do not have requirements.

**Comment by jimi-c** [comment]
Requirements files are not required, nor are they read automatically. It makes sense to print a message here to the user that nothing was found in the file.

**Comment by bcarpio** [comment]
So if we look at how this feature works in other configuration management systems (puppet ... chef ... salt) the dependency files can be empty. For instance in puppet the .fixtures file can be empty ...

**Comment by pastephens** [comment]
> Requirements files are not required, nor are they read automatically. It makes sense to print a message here to the user that nothing was found in the file.

It's not "printing a message" - it's throwing an exception and stopping ansible.

**Comment by thirstydeveloper** [comment]
Can this be re-opened? I too would want execution to continue (perhaps with a warning) if the requirements is empty.
