### ISSUE TITLE
[v2]The windows iis modules how to obtain multiple application of information in the directory?

### ISSUE THREAD

**Issue by BenMo158** [ansible/ansible#12848]
[v2] My application directory structure:
www.tiger.com (site):
|
|---internal (directory)
|-------|
|-------|___ v4.0.5 (application)
|
|---v4.5.5 (application)

I can use the:
ansible iis01 -m win_iis_webapplication -a "name=v4.5.5 site=www.tiger.com"
for v4.5.5 infomation,
But now,How to obtain "inetnal/v4.0.5" information?

**Comment by chrrrles** [comment]
Have you tried using the physical_path option for win_iis_webapplication?

**Comment by BenMo158** [comment]
No,from "win_iis_webapplication", "Pthysical_path" is I'm going to get the information
like:
- win_iis_website: name=www.tiger.com
  register: info
- debug: msg="{{ info.site.PathysicalPath }}"
