### ISSUE TITLE
Ansible 2.0 breaks "here" documents in shell scripts

### ISSUE THREAD

**Issue by larsks** [ansible/ansible#12856]
I wanted to embed a "here" document (e.g. `cat <<EOF ...`) in a `shell:` script in my playbook, like this:

```
shell: |
  . credentials/keystonerc_admin

  cat <<-EOF
  auth_url: "$OS_AUTH_URL"
  username: "$OS_USERNAME"
  password: "$OS_PASSWORD"
  tenant_name: "$OS_TENANT_NAME"
  EOF
```

In 1.9.4, this breaks because the magic processing that looks for
module arguments in the command string resulted in the following
script:

```
. credentials/keystonerc_admin

 cat <<-EOF
 auth_url: \"$OS_AUTH_URL\"
 username: \"$OS_USERNAME\"
 password: \"$OS_PASSWORD\"
 tenant_name: \"$OS_TENANT_NAME\"
 EOF
```

Note the extra space (` `) at the beginning of every line, which
breaks shell parsing.  It was possible to fix this by passing the
script directly to the`cmd` parameter, which would bypass the magic
"look for arguments" processing:

```
shell:
  cmd: |
    . credentials/keystonerc_admin

    cat <<-EOF
    auth_url: "$OS_AUTH_URL"
    username: "$OS_USERNAME"
    password: "$OS_PASSWORD"
    tenant_name: "$OS_TENANT_NAME"
    EOF
```

This worked great.  But then Ansible 2.0 came along, and the above
fails with:

```
unsupported parameter for module: cmd
```

And without the `cmd:` parameter, it fails the same was as in 1.9.4.

**Comment by larsks** [comment]
So, looking through the code, it looks a possible source of the problem is the parsing code in `lib/ansible/parsing/splitter.py`, which uses `split_args` to split up the arguments and then re-assembles them with `' '.join(...)`.  This seems like the wrong thing to do, especially when receiving a YAML literal block.  There are a few ways of fixing this:
- Add back the `cmd` parameter, for providing an argument that doesn't get processed by `splitter.py`.
- If no keyword arguments are found, return the argument string verbatim rather than splitting/re-assembling it
- I had a third idea, but it just slipped my mind.

Any preferences?

**Comment by jimi-c** [comment]
Hi @larsks, in 2.0 you can actually use `_raw_params` for the `cmd` parameter, which works fine in my testing. I can add some code to the `preprocess_data()` method for Task to convert this automatically internally.

**Comment by larsks** [comment]
You mean, put code in that would remap `cmd` to `_raw_params`?  I guess that works for me, but then suddenly everything supports a `cmd` parameter.  Would it make more sense to do this in the `command` module itself?  I don't have a strong feeling on the matter, I guess, since both solutions will result in properly handled shell scripts...

**Comment by larsks** [comment]
@jimi-c, take a look at the PR I just submitted.  This is a two-line change that implements the second option from my earlier comment: if there are no keyword arguments discovered, just return the raw string.  With this change in place, this works just fine:

```
- hosts: localhost
  tasks:
    - shell: |
        cat <<EOF
        This is
        a test.
        EOF
      register: output

    - debug:
        var: output
```

**Comment by jimi-c** [comment]
@larsks no, only command/shell/script would support it. Here's the working patch I have:

<pre>
diff --git a/lib/ansible/playbook/task.py b/lib/ansible/playbook/task.py
index b66c331..3527cee 100644
--- a/lib/ansible/playbook/task.py
+++ b/lib/ansible/playbook/task.py
@@ -171,6 +171,15 @@ class Task(Base, Conditional, Taggable, Become):
         args_parser = ModuleArgsParser(task_ds=ds)
         (action, args, delegate_to) = args_parser.parse()
 
+        # the command/shell/script modules used to support the `cmd` arg,
+        # which corresponds to what we now call _raw_params, so move that
+        # value over to _raw_params (assuming it is empty)
+        if action in ('command', 'shell', 'script'):
+            if 'cmd' in args:
+                if args.get('_raw_params', '') != '':
+                    raise AnsibleError("The 'cmd' argument cannot be used when other raw parameters are specified. Please put everything in one or the other place.", obj=ds)
+                args['_raw_params'] = args.pop('cmd')
+
         new_ds['action']      = action
         new_ds['args']        = args
         new_ds['delegate_to'] = delegate_to
</pre>

**Comment by larsks** [comment]
I am a little more comfortable with my solution, because it doesn't require special-casing specific modules in `task.py`.  I mean, what if I want to be able to pass verbatim scripts to something else that is not `command` or `shell` or `script`?

**Comment by jimi-c** [comment]
We already filter out things which may try to populate _raw_params to a subset of modules.

**Comment by larsks** [comment]
Huh.  I didn't know that. 

I think my solution is still more obvious to someone using Ansible (you want a shell scripts?  Here's your shell script.), but I guess either solution solves my immediate problem.

**Comment by jimi-c** [comment]
Yep, I'm going to merge in my fix, as it follows the pattern in the code we already have.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
