### ISSUE TITLE
Documentation correction: stat_module (stat.lnk_source)

### ISSUE THREAD

**Issue by emiel** [ansible/ansible#12850]
The Ansible docs (http://docs.ansible.com/ansible/stat_module.html) state that 'lnk_source' is a boolean when in fact it contains the actual symlink source, i.e. a pathname.

```
ok: [api82.smartpr.dev] => {
    "var": {
        "current_symlink.stat.lnk_source": "/home/foobar/21102015-1445431274-908472971"
    }
}

$ ansible --version
ansible 1.9.3
```

**Comment by adsnjhfyeqw231eas** [comment]
visiting this link you have mentioned http://docs.ansible.com/ansible/stat_module.html and searching for the string lnk_source shows up, it is a String, not a Boolean :)

**Comment by emiel** [comment]
Looks like it has already been corrected by this commit: https://github.com/ansible/ansible-modules-core/commit/2b33c92e7ab24612d2d10c0c68fa08fc806733b0

I'm closing this ticket. :)

**Comment by bcoca** [comment]
sorry, forgot to update this ticket after the fix
