### ISSUE TITLE
[v2] local_action sudo=no is not enforced, failing the task

### ISSUE THREAD

**Issue by saeeda** [ansible/ansible#12851]
The task is: 
  local_action: wait_for port=22 host={{ ansible_ssh_host }} delay=10 timeout=300

When playbook has sudo = yes and local_action task has sudo = no, it still uses root.

> TASK [Local Action] **********************************************************
> ESTABLISH LOCAL CONNECTION FOR USER: u_user
> server_ip EXEC (umask 22 && mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1445383120.89-269045649329606" && echo "$HOME/.ansible/tmp/ansible-tmp-1445383120.89-269045649329606")
> server_ip PUT /var/folders/nn/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/T/tmpjqmeNP TO /Users/u_user/.ansible/tmp/ansible-tmp-1445383120.89-269045649329606/wait_for
> server_ip EXEC /bin/sh -c 'sudo -H -n -S -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-hcbrfqpuzguaycslnvsatztucccaykwz; LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/u_user/.ansible/tmp/ansible-tmp-1445383120.89-269045649329606/wait_for; rm -rf "/Users/u_user/.ansible/tmp/ansible-tmp-1445383120.89-269045649329606/" > /dev/null 2>&1'"'"''
> fatal: [server_ip]: FAILED! => {"changed": false, "failed": true, "msg": "sudo: a password is required\n", "parsed": false}

Stating sudo = no at playbook and not mentioning sudo at the task, would not call sudo, and task would successfully execute. 

> TASK [Local Action] **********************************************************
> ESTABLISH LOCAL CONNECTION FOR USER: u_user
> server_ip EXEC (umask 22 && mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1445383144.71-197741969101841" && echo "$HOME/.ansible/tmp/ansible-tmp-1445383144.71-197741969101841")
> server_ip PUT /var/folders/nn/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/T/tmpvNCNVG TO /Users/u_user/.ansible/tmp/ansible-tmp-1445383144.71-197741969101841/wait_for
> server_ip EXEC LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/u_user/.ansible/tmp/ansible-tmp-1445383144.71-197741969101841/wait_for; rm -rf "/Users/u_user/.ansible/tmp/ansible-tmp-1445383144.71-197741969101841/" > /dev/null 2>&1
> ok: [server_ip] => {"changed": false, "elapsed": 10, "path": null, "port": 22, "search_regex": null, "state": "started"}

ansible --version 
ansible 2.0.0 (detached HEAD 5ae74f7d38) last updated 2015/10/20 16:34:41 (GMT -400)
  lib/ansible/modules/core: (detached HEAD d659c79db7) last updated 2015/10/20 16:34:57 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/20 16:35:01 (GMT -400)

**Comment by jimi-c** [comment]
Hi @saeeda, with which version of Ansible are you seeing this failure?

**Comment by jimi-c** [comment]
@saeeda, using the following playbook, I was not able to reproduce this:

<pre>
- hosts: awxlocal
  sudo: yes
  tasks:
  - local_action: wait_for port=22 host={{ ansible_ssh_host }} delay=1 timeout=300
    sudo: no
</pre>

Output:

<pre>
TASK [wait_for delay=1 host={{ ansible_ssh_host }} port=22 timeout=300] ********
task path: /home/jamesc/testing/12851/test.yml:4
ESTABLISH LOCAL CONNECTION FOR USER: testing
localhost EXEC (umask 22 && mkdir -p "$(echo $HOME/.ansible/tmp/ansible-tmp-1445483002.55-112009366223489)" && echo "$(echo $HOME/.ansible/tmp/ansible-tmp-1445483002.55-112009366223489)")
localhost PUT /tmp/tmp2VW0nb TO /home/jamesc/.ansible/tmp/ansible-tmp-1445483002.55-112009366223489/wait_for
localhost EXEC LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/jamesc/.ansible/tmp/ansible-tmp-1445483002.55-112009366223489/wait_for; rm -rf "/home/jamesc/.ansible/tmp/ansible-tmp-1445483002.55-112009366223489/" > /dev/null 2>&1
ok: [awxlocal -> localhost] => {"changed": false, "elapsed": 1, "path": null, "port": 22, "search_regex": null, "state": "started"}
</pre>

Is there any additional information you can provide, such as your playbook, which might help reproduce this?

**Comment by saeeda** [comment]
Setting become_user directive in the local_action task resolved the issue.
- name: restart and wait
  hosts: test1
  sudo: yes
  gather_facts: no
  
  tasks:
  - name: restart server
    shell: /sbin/shutdown -r now "Reboot triggered by Ansible"
    async: 0
    poll: 0
    ignore_errors: true
  - local_action: wait_for port=22 host="{{ ansible_ssh_host }}" search_regex=OpenSSH delay=10
    become: yes
    become_user: user

**Comment by amenonsen** [comment]
I can't reproduce the original problem either; this should be closed now.

**Comment by jimi-c** [comment]
Per the above, closing this now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by daino3** [comment]
I was getting this same error with the following playbook (ansible 2.4.3.0):

```
- hosts: all
  sudo: yes
  gather_facts: True
  
  tasks:
      - name: get the username running the deploy
        sudo: no
        local_action: shell command whoami
        register: username_on_host


```

All I had to do is change `sudo: no` to `become: no` (and probably read the docs better)

**Comment by ghost** [comment]
**become: no** is enough (ansible 2.4.2.0 on MacOS)
I got warning message for "sudo: no".  
 [WARNING]: Ignoring invalid attribute: sudo .  

```
- name: create public_keys directory if it does not existing.
  become: no
  local_action: file path=public_keys state=directory
```
