### ISSUE TITLE
Allow plugins to be included locally with a playbook as an alternative to global install

### ISSUE THREAD

**Issue by evan** [ansible/ansible#1285]
Having plugins and callback_plugins installed globally is inconvenient.

**Comment by mpdehaan** [comment]
agree there should be options.

@dhozac had a patch to allow this relative to the playbook dir but it's causing issues with multiprocessing for me.  I'll slot this into 0.9 where I may need to cherry-pick his changes slowly to see what's up in my environment.

**Comment by mpdehaan** [comment]
this is all done for 0.8

**Comment by evan** [comment]
Awesome!
