### ISSUE TITLE
v2 - Local Action does not appear to be handed off to local from remote

### ISSUE THREAD

**Issue by Etherdaemon** [ansible/ansible#12860]
**Issue Type:**

Bug Report

**Ansible Version**
ansible --version
ansible 2.0.0 (detached HEAD 5ae74f7d38) last updated 2015/10/18 19:39:15 (GMT +1000)

Running Ansible from source - v2.0.0-0.3.beta1

*\* Ansible Config Changes:**
inventory      = china_aws_inventory/ec2.py
ansible_python_interpreter = /usr/local/bin/python

**Environment:**
OSX 10.10.5
Running Ansible from source - v2.0.0-0.3.beta1
Running boto (2.38.0) and boto3 (1.1.4)
Python 2.7.10

**Summary:**

When specifying a remote host initially and then performing an action which is required on the local host, the action is not handed off to the local from the remote. Testing of the same playbook on 1.9.4 Ansible works as expected.

**Steps To Reproduce:**

```

---
- name: Termination Script
  hosts: ec2
  gather_facts: False
  connection: local
  vars: 
    - region: 'cn-north-1'
  tasks:
    - name: Gather EC2 facts
      local_action: ec2_facts

    - debug: var=hostvars[inventory_hostname]
    - debug: "msg={{ hostvars[inventory_hostname]['ec2_id'] }}"

    - name: Terminate instances 
      local_action: ec2
        profile='china'
        state='absent'
        instance_ids='{{ ec2_id }}'
        region='{{ region }}'
        wait=True
```

**Expected Results:**

```
TASK: [debug msg={{ hostvars[inventory_hostname]['ec2_id'] }}] ****************
ok: [10.237.3.62] => {
    "msg": "i-f2fc90ca"
}

msg:
 i-f2fc90ca

TASK: [Terminate instances] ***************************************************
changed: [10.237.3.62 -> 127.0.0.1]

PLAY RECAP ********************************************************************
10.237.3.62                : ok=4    changed=1    unreachable=0    failed=0
```

**Actual Results:**

```
TASK [debug msg={{ hostvars[inventory_hostname]['ec2_id'] }}] ******************
ok: [10.237.3.62] => {
    "changed": false,
    "msg": "i-f2fc90ca"
}
TASK [Terminate instances] *****************************************************
fatal: [10.237.3.62]:  FAILED! => {"changed": false, "failed": true, "msg": "boto required for this module"}*
```

**Comment by bcoca** [comment]
can you test with the latest HEAD, there were some updates done to local action since the 18th that might have fixed this already.

**Comment by Etherdaemon** [comment]
Pulled latest update. Appears to be the same result unfortunately.

```
TASK [debug msg={{ hostvars[inventory_hostname]['ec2_id'] }}] ******************
ok: [10.237.7.45] => {
    "changed": false,
    "msg": "i-90c8a4a8"
}

TASK [Terminate instances] *****************************************************
fatal: [10.237.7.45]: FAILED! => {"changed": false, "failed": true, "msg": "boto required for this module"}

PLAY RECAP *********************************************************************
10.237.7.45                : ok=3    changed=0    unreachable=0    failed=1
```

**$ ansible --version**
     ansible 2.0.0 (detached HEAD 5ae74f7d38) last updated 2015/10/22 12:41:44 (GMT +1000)
      lib/ansible/modules/core: (detached HEAD d659c79db7) last updated 2015/10/22 12:41:57 (GMT +1000)
      lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/22 12:41:57 (GMT +1000)
      config file = /Users/Etherdaemon/personal/coderepos/ansible/ansible.cfg
      configured module search path = None

**Comment by Etherdaemon** [comment]
Actually - it looks like it does work after all - just appears to come from the remote host even though it is trying to execute from the Ansible host.

I also had to pop in the following into my bash profile - note that this location is different due to python being installed via Homebrew than other systems.

```
export PYTHONPATH="/Users/<Username>/ansible/lib:$PYTHONPATH"
export PYTHONPATH="/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages:$PYTHONPATH"
```

Running the execute after that results in the following:

```
TASK [Terminate instances] *****************************************************
ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
10.237.3.235 EXEC (umask 22 && mkdir -p <REMOVED> )
10.237.3.235 PUT <REMOVED>
10.237.3.235 EXEC LANG=C LC_MESSAGES=C LC_CTYPE=C /usr/bin/python <REMOVED>
changed: [10.237.3.235] => {"changed": true, "instance_ids": ["i-22ddb11a"], <REMOVED>}

PLAY RECAP *********************************************************************
```

**Comment by jimi-c** [comment]
@Etherdaemon since you are still executing against a list of inventory hosts, you need to add the `run_once: yes` option to the task, so that it is really only run the one time.

As this has been resolved, we'll go ahead and close this now.  If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by bcoca** [comment]
fyi, if using dynamic inventory you don't need to call ec2_facts, but if not and you are using it to get the ec2_id, please note that it MUST execute on the target server and not use 'local' to get the data.

**Comment by Etherdaemon** [comment]
Ok cool - thanks Brian.
