### ISSUE TITLE
remove the C() M() and I() functions from the module formatter

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1286]
These are inconsistently applied throughout all of the modules and I can't expect anyone to maintain them correctly or consistently.

It is easier to remove them and just make something that turns the URLs into automatic links by way of a regex.

Make it so and simplify the mechanisms of the module formatter script in the process.

And probably give it a quiet mode as well.

**Comment by mpdehaan** [comment]
Pretty much all the macros in other words

**Comment by jpmens** [comment]
Please don't remove them: I think we'll like this when going to LaTeX/PDF. Original intention was to make sure we can produce constant-width for filenames, etc. 

Over the next few days, I'll see if I can rework current library/\* DOCUMENTATION to use those more consistently.

(related: #1284)

**Comment by jpmens** [comment]
related: #1267

**Comment by mpdehaan** [comment]
due to popular demand, I'm not going to remove these, since I think the linking of "M" in the docs is useful.

However I have noticed inconsistent usage of C and I and B, and it would be nice to get this cleaned up.
