### ISSUE TITLE
include: fails during exception processing

### ISSUE THREAD

**Issue by larsks** [ansible/ansible#12876]
Given a playbook like this:

```
- hosts: localhost
  tasks:
    - block:

        - include: failing_tasklist.yml

      always:

        - include: cleanup_tasklist.yml
```

Where `failing_tasklist.yml` looks like this:

```
- name: fail on purpose
  fail:
    msg: 'breaking things'
```

And `cleanup_tasklist.yml` looks like this:

```
- name: clean up
  debug:
    msg: 'cleaning things up'
```

I would expect Ansible to run `cleanup_tasklist.yml`, but the
resulting playbook run looks like this:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [include] *****************************************************************
included: /home/lars/tmp/block-include-testcase/failing_tasklist.yml for localhost

TASK [fail on purpose] *********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "breaking things"}

TASK [include] *****************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1   
```

So while it is parsing the `include` statement in the `always` section, it doesn't appear to be running it.  The `cleanup_tasklist.yml` tasklist **is** run if there are no failures in the `block:` tasks, e.g.:

```
- hosts: localhost
  tasks:
    - block:

        - debug:
            msg: not breaking

      always:

        - include: cleanup_tasklist.yml
```

**Comment by larsks** [comment]
To save you some copy-and-pasting, here's the testcase as a git repository:
- https://github.com/larsks/ansible-testcase-always-include

**Comment by larsks** [comment]
The problem is here, in `lib/ansible/playbook/included_file.py`:

```
def process_include_results(results, tqm, iterator, loader, variable_manager): included_files = []

    for res in results:
        if res._host.name in tqm._failed_hosts:
            continue
```

If we are handling an exception, then of course `res._host.name` is in
`tqm._failed_hosts`.  At first glance, this seems like the wrong place
to be making this check (shouldn't this be happening per-task
already?), but I'm not familiar enough with the code to make that
determination.

**Comment by jimi-c** [comment]
@larsks I agree, I think we can remove that without an ill-effect. I believe the host would not hit the include task if it had failed already, so checking that there is not required.

**Comment by jimi-c** [comment]
I do already have a complex include example in the `samples/` directory, which you can test as follows:

<pre>
# ansible-playbook -vv -i localhosts test_include.yml 
</pre>

^ Running this with those lines removed shows the output I'd expect, so I'll go ahead and commit that fix.

**Comment by larsks** [comment]
Oh, sorry, I just sent in a PR for same.  Feel free to ignore for yours...

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
