### ISSUE TITLE
ERROR! The requested action was not found in configured module paths. Additionally, core modules are missing.

### ISSUE THREAD

**Issue by hyperfocus1338** [ansible/ansible#12871]
##### Issue Type:

Playbook stops while usually keeps running. Newly introduced bug.
##### Ansible Version:

v2.0.0-0.3.beta1
##### Ansible Configuration:

Default, nothing changed after installation from checkout or release package.
##### Environment:

Ubuntu 15.04 docker image
##### Summary:

Error in the title. Complete error:

```
ERROR! The requested action was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem.

The error appears to have been in '/tmp/nginx/roles/nginx/handlers/main.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: restart nginx
  ^ here
```

Complete document `handlers/main.yml` where it fails:

```

---
- name: restart nginx
  service: name=nginx state=restarted

- name: reload nginx
  service: name=nginx state=reloaded

- name: start nginx, if not running
  service: name=nginx state=started

- name: stop nginx, if running
  service: name=nginx state=stopped

```

Nothing wrong... this worked before.
##### Steps To Reproduce:

Running from a Dockerfile and error occurs when Ansible was installed from both checkout (git pull) and from released package (v2.0.0-0.3.beta1). Relevant portion install procedure checkout:

```
RUN apt-get -y update
RUN apt-get install -y git python-yaml python-httplib2 python-dev python-pip python-keyczar python-software-properties python-configparser python-pycurl python-mysqldb 
RUN pip install paramiko Jinja2 six
RUN git clone http://github.com/ansible/ansible.git /tmp/ansible
RUN cd /tmp/ansible && make && make install
RUN cd /tmp/ansible && git pull --rebase && git submodule update --init --recursive
```

Relevant portion install procedure from package:

```
RUN apt-get -y update
RUN apt-get install -y git wget python-yaml python-httplib2 python-dev python-pip python-keyczar python-software-properties python-configparser python-pycurl python-mysqldb 
RUN pip install paramiko Jinja2 six
RUN cd /tmp && wget https://github.com/ansible/ansible/archive/v2.0.0-0.3.beta1.tar.gz && tar -xvzf v2.0.0-0.3.beta1.tar.gz && mv ansible-2.0.0-0.3.beta1 ansible
RUN cd /tmp/ansible && make && make install
```
##### Expected Results:

Continue running like normal
##### Actual Results:

Stopped at error described in summary

Any ideas? Thanks for helping.

**Comment by sivel** [comment]
As described in the error message, the submodules are not being properly cloned.

I'd recommend just using pip to install this, such as:

```
pip install git+https://github.com/ansible/ansible.git@v2.0.0-0.3.beta1#egg=ansible
```

That will pull down the repo, specifically the `v2.0.0-0.3.beta1` tag, recursively update the submodules, and install.

**Comment by sivel** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by hyperfocus1338** [comment]
Sorry for the late reply. Running `pip install git+https://github.com/ansible/ansible.git@v2.0.0-0.3.beta1#egg=ansible` still gives me the same error..

**Comment by twekberg** [comment]
I'm getting the same error. I rebooted my VM and when I tried my normal playbook it started complaining. Did you get a useful reponse, or how did you work around this problem?

**Comment by milosgajdos** [comment]
Sam error here. This is how I installed ansible:

```
pip install paramiko PyYAML Jinja2 httplib2 six boto "git+git://github.com/ansible/ansible.git@stable-2.1"
```

I'm getting exactly the same error as being reported here and rejected by Ansible devs:

```
ansible-playbook site.yml
ERROR! The requested action was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem.
```

**Comment by alevensalor** [comment]
Same error on the apt package install in Ubuntu 0n 2.2.0.0

```ERROR! The requested action was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem.

The error appears to have been in '/home/c2-maintenance/dmons/sitegate_update/Playbooks/roles/update/tasks/rescue/alreadyRunning.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Not running rescue, since the error is "Already Running"
  ^ here


The error appears to have been in '/home/c2-maintenance/dmons/sitegate_update/Playbooks/roles/update/tasks/rescue/alreadyRunning.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Not running rescue, since the error is "Already Running"
  ^ here

c2-maintenance@ansible-control-test:~/Playbooks$ ansible --version
ansible 2.2.0.0
  config file = /home/c2-maintenance/dmons/sitegate_update/Playbooks/ansible.cfg
  configured module search path = ['/usr/share/ansible/modules/']
```

**Comment by kwidholm-tm** [comment]
I have this error in ansible v 2.1.1.0

This happens both when installing ansible via git clone devel checkout (and doing source hacking/env-setup), and also when installing like so `pip install git+git://github.com/ansible/ansible.git@v2.1.1.0-1`.

None of my playbooks work any longer. I have an extensive repository of them configuring everything from VPCs to Load Balancers to Database slaves. They all fail with *exactly* the same kind of error as reported in this thread.

```
ERROR! The requested action was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem.

The error appears to have been in '/path/to/foo/bar.yml': line 8, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Update All Packages (Debian/Ubuntu)
      ^ here
```

From the way I read this, it appears the core 'name' module does not exist or cannot be found or imported correctly during the ansible build.
