### ISSUE TITLE
Error when using bound method CallbackModule

### ISSUE THREAD

**Issue by messiahUA** [ansible/ansible#12885]
Fresh git pulled repo, i'm following official documentation and when I execute "ansible all -m ping":

`[WARNING]: Error when using <bound method CallbackModule.v2_runner_on_ok of </ansible/lib/ansible/plugins/callback/minimal.CallbackModule object at 0x7fdbbcfd8d90>>:
'TaskResult' object has no attribute 'copy'`

`[WARNING]: Error when using <bound method CallbackModule.v2_runner_on_unreachable of </ansible/lib/ansible/plugins/callback/minimal.CallbackModule object at 0x7fdbbcfd8d90>>:
'TaskResult' object has no attribute 'copy'`

**Comment by bcoca** [comment]
can you show output of `ansible --version` and run the command with -vvvv to show full traceback?

**Comment by mcalhoun** [comment]
I'm also getting the same

$ ansible --version  
ansible 2.0.0 (devel 08ca749c94) last updated 2015/10/23 12:00:01 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 3fa6626094) last updated 2015/10/22 14:00:08 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD b65a583902) last updated 2015/10/22 14:00:08 (GMT -400)
  config file = /Users/[redacted]/ansible.cfg
  configured module search path = /Users/[redacted]/library

$ ansible [redacted] -i inventory/production -m ping -vvvv --limit [redacted]  
Using /Users/[redacted]/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<den3pns01> ESTABLISH SSH CONNECTION FOR USER: root
<den3pns01> SSH: EXEC ssh -C -vvv -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=20 -o ControlPath=/Users/[redacted]/.ansible/cp/ansible-ssh-%h-%p-%r -tt [redacted] mkdir -p "$(echo $HOME/.ansible/tmp/ansible-tmp-1445616520.37-162206503101228)" && echo "$(echo $HOME/.ansible/tmp/ansible-tmp-1445616520.37-162206503101228)"
 [WARNING]: Error when using <bound method CallbackModule.v2_runner_on_unreachable of </Users/[redacted]/ansible/lib/ansible/plugins/callback/minimal.CallbackModule object at 0x109856590>>: 'TaskResult' object has no attribute 'copy'

**Comment by abadger** [comment]
Sorry about that.  Should be fixed with this commit: https://github.com/ansible/ansible/commit/99c6f77e593a36ac26341d77fddd898665bde3ae
