### ISSUE TITLE
CA Certificate File Path

### ISSUE THREAD

**Issue by azenakhi** [ansible/ansible#12884]
Hello,

I have a problem with Ansible about the ca_file_path variable inside the config file ansible.cfg.

I redefined this variable for using another path. But, Ansible always use the default path system /etc/ssl/certificats. For example, I want use the os_file_path = /tools/product/ansible/cacert.crt. But, he doesn’t work.

See here :

https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/urls.py
method : def get_ca_certs(self).

I tried to understand to simulate that method, I think the variable "ca_file_path" is never used.

Thank you by advance.

**Comment by pathcl** [comment]
@azenakhi it should be simple to have a workaround. In which system are you?

paths_checked.append('/tools/product/ansible/cacert.crt')

**Comment by abadger** [comment]
We think that ca_file_path may be an outdated example that we need to remove from the sample config file.  That hasn't been used since at least 1.7.0 (Could be even earlier... 1.7.0 is just the furthest back in history that I checked).

What are you actually trying to do?  (What is your ansible playbook that's failing)?  We may be able to recommend something for you if we know what you're actually trying to do.

**Comment by azenakhi** [comment]
Thank for your message.

My problem is simple: I wanted make my custom certificate path inside ansible.cfg in order ansible to take this changement.

Best regards.

**Comment by abadger** [comment]
custom certificate path to do what?  There's different potential solutions depending on what you are trying to actually accomplish.

**Comment by azenakhi** [comment]
I wanted put my cacert.crt inside the path for example /usr/local/cacert.crt.

**Comment by abadger** [comment]
What playbook or ansible command line command will this make work for you?

**Comment by azenakhi** [comment]
Thank you for you help.

**Comment by abadger** [comment]
I would have liked to have helped more but would have needed more information.

Perhaps these links will be of assistance to either you or to someone coming across this via google (they're how to add ca certificates on red hat-based and ubuntu/debian linux distributions:
- https://www.happyassassin.net/2015/01/14/trusting-additional-cas-in-fedora-rhel-centos-dont-append-to-etcpkitlscertsca-bundle-crt-or-etcpkitlscert-pem/
- http://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate
