### ISSUE TITLE
Bug in ansible-tower-setup-2.3.1 on CentOS 6.3

### ISSUE THREAD

**Issue by vikas027** [ansible/ansible#12898]
There is a bug in [ansible-tower-setup-2.3.1.tar.gz](http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-2.3.1.tar.gz) for CentOS 6.3 (may be others too). However, it works fine on CentOS 6.6.

Problem is that `/etc/yum.repos.d/epel-6.repo` created while installing/upgrading Ansible Tower, contains mirrorlist which is not valid for CentOS 6.3.

``` bash
# cat /etc/yum.repos.d/epel-6.repo.bkup | head -n 8
[epel]
name=Extra Packages for Enterprise Linux 6 - $basearch
#baseurl=http://download.fedoraproject.org/pub/epel/6/$basearch
mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
#

# yum repolist
...
...
Error: Cannot retrieve metalink for repository: epel. Please verify its path and try again
#
```

I was able to fix this by modifying the file `ansible-tower-setup-2.3.1/roles/packages_el/files/epel-6.repo` as below.

``` bash
[epel]
name=Extra Packages for Enterprise Linux 6 - $basearch
baseurl=http://download.fedoraproject.org/pub/epel/6/$basearch
#mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
```

**Comment by sivel** [comment]
For tower support you will want to go through https://support.ansible.com/

**Comment by vikas027** [comment]
Thanks @sivel , I have raised a case with them.
