### ISSUE TITLE
make 'notify' templatable

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#12907]
There's no way to call notify with parameters, like:

``` yaml
notify: nginx {{ action }}
```

There're some workarounds but they look too complicated.

**Comment by jimi-c** [comment]
I believe we already support this, at least in devel/2.0:

<pre>
- hosts: localhost
  gather_facts: no
  vars:
    foo: bar
  tasks:
  - debug: msg="notifying the {{foo}} handler"
    changed_when: true
    notify: "handler {{foo}}"
  handlers:
  - name: handler bar
    debug: msg="here i am"
</pre>

And when run:

<pre>
PLAY ***************************************************************************
TASK [debug msg=notifying the {{foo}} handler] *********************************
NOTIFIED HANDLER handler bar
changed: [localhost] => {
    "changed": true, 
    "msg": "notifying the bar handler"
}
RUNNING HANDLER [handler bar] **************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "here i am"
}
PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
</pre>

Unless there's something I'm missing above?

**Comment by hryamzik** [comment]
@jimi-c perfect, thanks. I didn't have time to switch to 2.0 yet. Closing,

**Comment by jimi-c** [comment]
Thanks for following up!
