### ISSUE TITLE
Is it possible to bounce winrm on a windows node?

### ISSUE THREAD

**Issue by Robby123** [ansible/ansible#12913]
I have been having issues with winrm when using ansible, one of the solutions is to restart winrm on each node manually after every playbook. I have tried creating a playbook which can remotely restart winrm using the 'raw' module and also tried the 'win_service' module - but these both return a HTTP error 500 when running

**Comment by abadger** [comment]
This sounds like more of a question than a bug report.  You'll probably get more responses by posting to the user's mailing list than here as more windows users will see it there.

I'll paste the mailing list information below.

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
