### ISSUE TITLE
New EC2 Run Command Feature

### ISSUE THREAD

**Issue by madmod** [ansible/ansible#12924]
I just wanted to start a discussion of Amazon's new [EC2 Run Command feature](https://aws.amazon.com/ec2/run-command/?sc_ichannel=em&sc_icountry=global&sc_icampaigntype=launch&sc_icampaign=em_154127070&sc_idetail=em_10668014515&ref_=pe_411040_154127070_7) and how it might be best integrated with Ansible. From what I can tell it's primary use is to run Powershell scripts and shell commands on many Windows hosts at once. If it is possible to apply Ansible tasks in bulk for groups of hosts this could provide very significant performance benefits over the current Powershell remoting communication method. It seems to me that another potential benefit of this could be easy bootstraping of new instances to enable Powershell remoting for the existing Ansible communication method. As I haven't yet used Ansible to provision any Windows hosts, but plan to do so in the near future, I would like to get some feedback on the practicality and potential utility of this compared to current methods.

**Comment by jimi-c** [comment]
Hi @madmod, we generally reserve Github issues for bugs/PRs, so I'd recommend starting this discussion on the Ansible devel mailing list (https://groups.google.com/forum/#!forum/ansible-devel), or in the #ansible-devel IRC channel on Freenode.

Thanks!
