### ISSUE TITLE
Should ANSIBLE_HOSTS override ansible.cfg?

### ISSUE THREAD

**Issue by larsks** [ansible/ansible#1292]
The ansible package available in Fedora provides an `/etc/ansible/ansible.cfg` that includes:

```
hostfile = /etc/ansible/hosts
```

Due to the way ansible searches for the inventory file this makes it impossible for a normal user to use `ANSIBLE_HOSTS` to specify the location of a new hostfile.  I'm unsure if this should be considered a packaging bug or an ansible bug, but it's frustrating because it means that out of the box one can't follow the "Getting Started" documentation.

**Comment by mpdehaan** [comment]
Some of those environment variables are in the course of being deprecated.

But it's also totally NOT impossible.

Just add a ~/.ansible.cfg and you can override anything you want.

I'll file this for looking at in terms of documentation so we can mention it earlier, but this is the preferred way of doing things.

**Comment by larsks** [comment]
The `ansible(1)` man page doesn't mention the `~/.ansible.cfg` configuration, which should probably be placed in the `FILES` section.

**Comment by larsks** [comment]
Push request that updates the man page is [#1306](https://github.com/ansible/ansible/pull/1306).
