### ISSUE TITLE
verify path_dwim function works relative to either playbook if included at different levels

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1293]
If I include a playbook a level deeper and the playbook uses a dest= or other parameter, the path used should work from both playbooks and depths.

This is what the utils.path_dwim function is intended to solve.

Make sure it works.

**Comment by mpdehaan** [comment]
path_dwim in runner probably needs to take the array of basedirs, not just the one

**Comment by bostrick** [comment]
while these might be related, i think #1411 is a reasonable approach, as currently the "None" at https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/task.py#L141 filters all the way down to os.path.join and thorws an exception for relative references...

**Comment by mpdehaan** [comment]
this is not the same thing, FWIW

**Comment by mpdehaan** [comment]
I believe this needs to be fixed in #1615 so not for this release, since it is relatively broad-sweeping and we have a week left in this month, it is probably not time to change it.
