### ISSUE TITLE
ResultProcess must not modify the TaskResult it shares with its _final_q serialization thread.

### ISSUE THREAD

**Issue by itldo** [ansible/ansible#12937]
## Ansible Version:

```
$ ansible --version
  ansible 2.0.0 (devel 87269599a0) last updated 2015/10/27 20:54:45 (GMT +000)
  lib/ansible/modules/core: (detached HEAD eeaeeb5a1f) last updated 2015/10/27 21:09:39 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 949b124e05) last updated 2015/10/27 21:09:39 (GMT +000)
    ...
```
## Environment

```
Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.54-2 x86_64 GNU/Linux
```
## Summary

Ansible intermittently issues the following error and then hangs:

```
Traceback (most recent call last):
 File "/opt/anaconda/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
RuntimeError: dictionary changed size during iteration
```

The cause is the following code that sends the entire result object including any _ansible_notify items
to the result queue and then proceeds to modify the result object with a `result_item.pop('_ansible_notify')` _at the same time the queuing thread is serializing the result dictionary_. The queuing thread throws and hangs the result queue worker process.

executor/process/result.py:
    ...

``` python
124                     if result._task.loop:
125                         # this task had a loop, and has more than one result, so
126                         # loop over all of them instead of a single result
127                         result_items = result._result['results']
128                     else:
129                         result_items = [ result._result ]
130
131                     for result_item in result_items:
132                         # if this task is notifying a handler, do it now
133                         if '_ansible_notify' in result_item:
134                             if result.is_changed():
135                                 # The shared dictionary for notified handlers is a proxy, which
136                                 # does not detect when sub-objects within the proxy are modified.
137                                 # So, per the docs, we reassign the list so the proxy picks up and
138                                 # notifies all other threads
139                                 for notify in result_item['_ansible_notify']:
140                                     self._send_result(('notify_handler', result, notify))
141                             # now remove the notify field from the results, as its no longer needed
142                             result_item.pop('_ansible_notify')
```

The python documentation for multiprocessing.Queue.put https://docs.python.org/2/library/multiprocessing.html#pipes-and-queues is misleading when it says

```
When an object is put on a queue, the object is pickled
and a background thread later flushes the pickled data to an underlying pipe.
```

Instead the object is put on a queue and is then serialized in a separate sending thread.
Thus the queued object is shared between the thread that put the object and the pickling thread.
## Steps to Reproduce.

This is difficult to reproduce consistently because it is a multithreading problem.
Of course it is happening often enough for me and the hanging is a serious problem because
ansible is part of a larger automated system. (I can't just control-C and try again).

It helps to run a task that has a loop that generates many notify events.
## Workaround

I'm going to try eliminating line 142,  result_item.pop, and allow the internal _ansible_notify attribute 
through.
## Solutions

Just some thoughts:
- Add some code like strip_internal_keys that strips internal keys on the receiving side of the result queue instead of the sending side?
- Don't send the whole result object as part of the notify_handler?
- Send a copy of the result object stripped of its internal keys.

Thanks

-tim

**Comment by amenonsen** [comment]
I didn't see this issue earlier. I have been having exactly the same problem that @itldo describes above. It sounds like it happens less often for me, but still often enough to be annoying (especially because the only thing I can do is start again from scratch). Perhaps this merits P2?

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
