### ISSUE TITLE
V2 synchronize module copies to control machine, not the remote

### ISSUE THREAD

**Issue by basz** [ansible/ansible#12944]
I have a synchronise task that isn't working correctly with a checkout of devel. I went back to the first alpha release and they all show the same behaviour (latest is atm @174de11)
- synchronize: src="../files/000-default-html/" dest="/var/www/html" archive=yes

After some trail and error I found that an attempt is made to synchronise to my local machine. Confirmed by creating /var/www/html running the play and then listing it contents.

Concluding it seems the command is incorrectly running as a local action
- local_action: synchronize: src="../files/000-default-html/" dest="/var/www/html" archive=yes

fatal: [s01]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"_local_rsync_path": "rsync", "archive": "yes", "dest": "/var/www/html", "dest_port": 2222, "src": "/path/to/project/provisioning/ansible/roles/provision.apache/files/../files/000-default-html/"}, "module_name": "synchronize"}, "msg": "sudo: a password is required\n", "parsed": false}

note the `dest` property isn't something like `vagrant@127.0.0.1:/var/www/html`

**Comment by abadger** [comment]
The module args you are seeing are simply the arguments you gave to the
module in the playbook.  So they are not a representation of what rsync
itself is being given.

Are you giving synchronize the first task (without local_action) or the
second?  The second definitely would try to copy a file from the local
machine to another directory on the local machine.  The first should be
working to copy from the local machine to the hosts listed in the play's
hosts: field.

**Comment by basz** [comment]
I am running without local_action and see files being copied to the control machine.

I thought I saw vagrant@127.0.0.1 in the dest property when I did some tests with ansible 1.9. Not sure now though

**Comment by abadger** [comment]
I just tried the latest devel with the following playbook:

```
---
- hosts: rhel6
  tasks:
    - synchronize: src="../files/000-default-html/" dest="/var/tmp/html" archive=yes
```

It synced from the source directory on my local machine to rhel6:/var/tmp/html correctly.

```
$ ansible-playbook 12944.yml                           *[devel]  (09:33:11)

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [rhel6]

TASK [synchronize dest=/var/tmp/html src=../files/000-default-html/ archive=yes] ***
changed: [rhel6]

PLAY RECAP *********************************************************************
rhel6                      : ok=2    changed=1    unreachable=0    failed=0   
[pts/37@roan /srv/ansible/ansible-friday]$ ls -al /var/tmp/html                                 *[devel]  (09:33:20)
ls: cannot access /var/tmp/html: No such file or directory
[pts/37@roan /srv/ansible/ansible-friday]$ ssh rhel6 ls -al /var/tmp/html/                      *[devel]  (09:33:28)
total 16
drwxrwxr-x. 2 badger badger 4096 Oct 28 09:07 .
drwxrwxrwt. 9 root   root   4096 Oct 28 09:33 ..
-rw-rw-r--. 1 badger badger    6 Oct 28 09:07 hello
-rw-rw-r--. 1 badger badger    6 Oct 28 09:07 world
```

So it seems like the source and dest are working properly for me.  Perhaps it's a different problem that you're having?

**Comment by basz** [comment]
> So it seems like the source and dest are working properly for me. Perhaps it's a different problem that you're having?

Must have because now synchronize works as expected... I don't know what is going on and feel a little silly. The created files are still there on my control machine as proof... but yes now things work... weird...

What the exact process of building & installing ansible from source? What I do is;

```
git checkout v2.0.0-0.4.beta2
python setup.py clean
python setup.py build
sudo python setup.py install
```

**Comment by abadger** [comment]
I usually use the hackingenv-setup script... it' not really for building but for using an ansible checkout as a developer.  It sets environment variables to use the checkout instead of whatever is on the system.

```
git checkout  v2.0.0-0.4.beta2
git submodule update
source ./hacking/env-setup
```

Your recipe for building and installing looks almost correct to me at first glance.  Just needs to add the git submodule update to set the modules to be the correct version as well.

Feel free to open a new ticket if you notice this happening again.
