### ISSUE TITLE
stat islnk False when file is a symlink

### ISSUE THREAD

**Issue by Gillingham** [ansible/ansible#12967]
Client:
- OS X
- ansible (1.9.4)
- Python 2.7.10

Target:
- Solaris 10
- Python 2.7.1

stat output:

``` json
{"changed": false, "stat": {"atime": 1441132349.203048, "ctime": 1441132247.244298, "dev": 67174405, "exists": true, "gid": 248, "inode": 91943, "isblk": false, "ischr": false, "isdir": true, "isfifo": false, "isgid": false, "islnk": false, "isreg": false, "issock": false, "isuid": false, "mode": "0755", "mtime": 1441132247.244298, "nlink": 6, "path": "/home/rampage/tps/php/php", "pw_name": "rampage", "rgrp": true, "roth": true, "rusr": true, "size": 6, "uid": 50001, "wgrp": false, "woth": false, "wusr": true, "xgrp": true, "xoth": true, "xusr": true}}
```

When in reality: 
ls -l /home/rampage/tps/php/php
lrwxrwxrwx 1 rampage 248 9 Sep  1 18:32 /home/rampage/tps/php/php -> php5.6.12/

**Comment by Gillingham** [comment]
Maybe I'm mis-understanding the function of follow for stat here. When I don't set follow=true I get back from stat that is is a link and it has a lnk_source being the destination.

I was under the assumption if I used follow=true the stat.path would be the links destination, which it isn't.

**Comment by sivel** [comment]
When `follow` is set to `True`, the module will use `os.stat` which will follow the symlink, and give you stat information for the followed symlink (i.e. the real file).

Setting `follow` to `False` which is the default, will cause the module to use `os.lstat`, which will not follow the symlink, and instead give you information about the link, instead of the followed file.

**Comment by Gillingham** [comment]
@sivel 

> When follow is set to True, the module will use os.stat which will follow the symlink, and give you stat information for the followed symlink (i.e. the real file).

That seems to be not-functioning as expected, as the output in my initial post is from the call on the symlink with follow=true , yet the path information is not from the linked destination

**Comment by sivel** [comment]
Which path?  `path` is always the path that you passed in, not the followed path.  If `follow` is `False`, `lnk_source` will be the path to the real file, otherwise `lnk_source` will not exist.

**Comment by Gillingham** [comment]
With follow=true: `"path": "/home/rampage/tps/php/php"`
but that path is a symlink, `/home/rampage/tps/php/php -> php5.6.12/`

**Comment by sivel** [comment]
`path` in the return data is always the `path` specified in calling the module.  See https://github.com/ansible/ansible-modules-core/pull/10 for the introduction of this feature.

Also, this issue was created in the wrong repository and I do not believe it is actually a bug.

**Comment by sivel** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
