### ISSUE TITLE
/etc/anisble folder not created

### ISSUE THREAD

**Issue by vnitinv** [ansible/ansible#12961]
I did "pip install ansible" but  I dont see /etc/ansible folder getting created.
Is that I need to create it?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case, /etc/ansible is a default location ansible looks into for certain things, but it is not required.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
