### ISSUE TITLE
Add wily in ppa

### ISSUE THREAD

**Issue by zigarn** [ansible/ansible#12977]
https://launchpad.net/~ansible/+archive/ubuntu/ansible does not propose wily.

**Comment by abadger** [comment]
Thanks for pointing this out.  We should be able to get that added sometime next week.

**Comment by abadger** [comment]
wily builds are now listed in the ppa.  Thanks to jlaska for adding that (and making a fix to the .deb build)!

**Comment by zigarn** [comment]
Thanks.
