### ISSUE TITLE
unable to install git on red hat 6.0

### ISSUE THREAD

**Issue by himanshukgit** [ansible/ansible#12984]
[root@localhost etc]# yum install git
Loaded plugins: product-id, refresh-packagekit, security, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Setting up Install Process
No package git available.
Error: Nothing to do
[root@localhost etc]# su -
[root@localhost ~]# ls
anaconda-ks.cfg  install.log  install.log.syslog
[root@localhost ~]# yum install git
Loaded plugins: product-id, refresh-packagekit, security, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Setting up Install Process
No package git available.
Error: Nothing to do
[root@localhost ~]# ^C
[root@localhost ~]# ^C

**Comment by machacekondra** [comment]
This is unrelated to ansible. You have to setup your repos properly, then you will be able to install git. (see man subscription-manager)

**Comment by sivel** [comment]
You may want to reach out to your hosting provider, RedHat, or try some forums related to Linux or RedHat troubleshooting.  As this is not Ansible related I'm closing this issue.
