### ISSUE TITLE
ansible-vault changes permission of files when encrypting/decrypting

### ISSUE THREAD

**Issue by mblarsen** [ansible/ansible#12987]
When using ansible-vault the file permissions are changed to

```
-rw-r--r--
```

I expected them to be the same. This is especially relevant when using ansible-vault for keys (that would have: 600), that would otherwise have to open rights.

ansible 2.0.0 (devel 92dd563a75)

**Comment by bcoca** [comment]
fixed via 00bc74404a8d2894f303f4612353417e4e94a156
