### ISSUE TITLE
'when: (item.copy)' fails (always True) when variable is called 'copy'.

### ISSUE THREAD

**Issue by ypid** [ansible/ansible#12990]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.4 and ansible devel (d341ba14a5f4b974d41f4b11f678b356c89f79d9)
##### Ansible Configuration:

Default configuration
##### Environment:

Debian Jessie
##### Summary:

In a `when` condition `item.copy` always evaluates to True regardless of the actual value of `item.copy`.

Has `copy` some special meaning when used as key in a list of dicts that I am unaware of?
##### Steps To Reproduce:

``` YAML
- hosts: localhost
  vars:
    test_list:
      - name: 'test'

        # Can also be completely removed thus being undefined.
        copy: False

        some_other_name: False

  tasks:
    - debug: var=test_list
    - debug:
        msg: 'False'
      when: (item.some_other_name)
      with_items: test_list
    - debug:
        msg: 'False'
      when: (item.copy)
      with_items: test_list
```
##### Expected Results:

```
TASK [debug msg=False] *********************************************************
skipping: [localhost] => (item={u'some_other_name': False, u'copy': False, u'name': u'test'})

TASK [debug msg=False] *********************************************************
skipping: [localhost] => (item={u'some_other_name': False, u'copy': False, u'name': u'test'})
```
##### Actual Results:

```
TASK [debug msg=False] *********************************************************
skipping: [localhost] => (item={u'some_other_name': False, u'copy': False, u'name': u'test'})

TASK [debug msg=False] *********************************************************
ok: [localhost] => (item={u'some_other_name': False, u'copy': False, u'name': u'test'}) => {
    "item": {
        "copy": false,
        "name": "test",
        "some_other_name": false
    },
    "msg": "False"
}
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

This happens to be a method of the underlying variable object `copy()` which returns true on success, which should happen unless you are out of memory.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by ypid** [comment]
Apparently some words are reserved. `item['copy']` works somehow but is also not reliable. As discussed in IRC it is best to avoid all names which are valid object names on items. Maybe it would be useful to document this somewhere (beyond this issue)?

```
>>> dir({})
['__class__', '__cmp__', '__contains__', '__delattr__', '__delitem__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'has_key', 'items', 'iteritems', 'iterkeys', 'itervalues', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values', 'viewitems', 'viewkeys', 'viewvalues']
```
