### ISSUE TITLE
known_hosts giving cryptic error 

### ISSUE THREAD

**Issue by bitwombat** [ansible/ansible#13009]
I have a task to learn/store a remote machine's fingerprint on the machine being configured so that a ssh tunnel works without prompting.  That task has run on Vagrant and EC2 instances, no problem, but is failing on my latest EC2 machine (which is a copy of one it worked on).

So it should work.

```
- name: Learn the admin machine's fingerprint
  known_hosts: path='/etc/ssh/ssh_known_hosts'
               name={{ admin_ip }}
               key="{{ lookup('pipe', 'ssh-keyscan -H ' ~ admin_ip ) }}"
```

This is the output:

```
failed: [99.64.132.2] => {"failed": true, "parsed": false}
BECOME-SUCCESS-poodxqqnkfldwlcombboucraylwzgozd
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1446498622.78-229061994980780/known_hosts", line 1859, in <module>
    main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1446498622.78-229061994980780/known_hosts", line 249, in main
    results = enforce_state(module,module.params)
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1446498622.78-229061994980780/known_hosts", line 96, in enforce_state
    if key is not None and key[-1]!='\n':
IndexError: string index out of range
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /home/gbell/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 99.64.132.2 closed.
```

Ansible issue?  Or something I can/should be debugging?

**Comment by bitwombat** [comment]
ANSWER:  ssh-keyscan fails silently if it can't ssh to the destination.  In my case I had the wrong IP address (it had changed since last successful run of this task).

It would be good if Ansible said "Error: key variable set but empty" instead of being angry at the attempt to access key[-1] and giving me a Python stack trace.

**Comment by bcoca** [comment]
the stacktrace should still be avoided, keeping this open

**Comment by bcoca** [comment]
should have closed cause this is in the wrong repo, but here is the fix http://github.com/ansible/ansible-modules-extras/commit/9fb6054500a9841ed4aa73733581fe248aaf7bf1
