### ISSUE TITLE
Issue with lib/ansible.egg-info/ ownership when running from source as different users

### ISSUE THREAD

**Issue by mcalhoun** [ansible/ansible#13004]
We have the need to run ansible from cron as root (to ensure the 'ansible' user exists on all remote hosts and its key is present in authorized_keys) as well as the the 'ansible' user. 

The problem is that when root sources ./hacking/env-setup, the directory lib/ansible.egg-info/ becomes owned by root and the ansible user can no longer run the ./hacking/env-setup without getting permission errors. 

Is there a better way to have this work than maintaining two separate versions of the source code?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
