### ISSUE TITLE
copy module doesn't follow symbolic directory

### ISSUE THREAD

**Issue by justinligraph** [ansible/ansible#13013]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME:

copy action plugin
##### ANSIBLE VERSION

2.0.1.0
##### SUMMARY

I am copying a folder, foo, which has a subfolder, foo1, which is a symbolic link to another folder say /root/myfoo1. copy module won't copy it to remote location.

**Comment by jimi-c** [comment]
@justinligraph with which version of Ansible are you seeing this occur?

**Comment by keithkostol** [comment]
I can confirm this bug in both 2.0.1.0 (Ubuntu repo) as well as the devel branch from git (pulled today).  

I have attached a small self contained demo.  It copies a directory that includes a couple symlinks to /tmp/ of the local machine.  One symlink is pointed to a file (called "link_to_file"), one is pointed to a directory (called "link_to_dir").  The directory that "link_to_dir" points to never gets copied (dir2), however the file that "link_to_file" points to does (file2).  
[bugtest.tar.gz](https://github.com/ansible/ansible/files/230957/bugtest.tar.gz)
