### ISSUE TITLE
dmidecode fails with permission denied

### ISSUE THREAD

**Issue by hadrienk** [ansible/ansible#13020]
Running the setup (ansible/module_utils/facts.py) on a machine without the required /sys values fails with 

```
/dev/mem: Operation not permitted
```

Using the sudo switch does not help.

**Comment by hadrienk** [comment]
seems that the following line is not executed with appropriate privileges

``` python
(rc, out, err) = module.run_command('%s -s %s' % (dmi_bin, v))
```

**Comment by bcoca** [comment]
the setup.py gets run with sudo, not the commands under it

**Comment by hadrienk** [comment]
Aren't the facts retrieved using this modules? In the case of a playbook
run with sudo it is not working either. Is that a design decision or a bug?

**Comment by bcoca** [comment]
I think i did not make myself clear, there is no need for the run_command to use sudo if setup.py is already run as sudo, in that case the command should work. I tested on several distros and I cannot reproduce the issue, can you supply more information? we need a minimal reproducible case.

**Comment by hadrienk** [comment]
I see.

I am running version 1.9 on gentoo. The target system is a CentOS 5.4.

Is there a way I can gather more information without modifying the code?

**Comment by hadrienk** [comment]
I assumed the -K switch implied the sudo would be used. With the -s switch it works fine.
