### ISSUE TITLE
Ansible - is it possible to set a time limit for a task?

### ISSUE THREAD

**Issue by Robby123** [ansible/ansible#13035]
I am currently running a task on a windows node which executes a 'raw' command, however sometimes this command can hang and never end - is it possible to give the task a timeout of about 5 mins and then end it if it hasn't completed within that time?

**Comment by sivel** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
