### ISSUE TITLE
Can't set User in ssh_config

### ISSUE THREAD

**Issue by sheldonh** [ansible/ansible#13032]
##### Issue Type:

But Report
##### Ansible Version:

```
ansible-playbook 2.0.0 (devel 4b75308439) last updated 2015/11/04 11:12:46 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 5b64993b22) last updated 2015/11/04 11:12:59 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD f281eb2b30) last updated 2015/11/04 11:12:59 (GMT +200)
  config file = /home/sheldonh/git/heisenberg-ansible/ansible.cfg
  configured module search path = None
```
##### Ansible Configuration:

In `ansible.cfg` I refer to a custom `ssh_config`:

```
[ssh_connection]
ssh_args = -F ./ssh_config -q
```

The `ssh_config` configures SSH proxy through a bastion:

```
Host bastion
    User                   ec2-user
    HostName               1.2.3.4
    ProxyCommand           none
    BatchMode              yes
    PasswordAuthentication no
    StrictHostKeyChecking  yes
    UserKnownHostsFile     ./known_hosts.bastion

Host *
    ServerAliveInterval    60
    TCPKeepAlive           yes
    ProxyCommand           ssh -o UserKnownHostsFile=./known_hosts.bastion -a -W %h:%p ec2-user@1.2.3.4
    ControlMaster          auto
    ControlPath            ~/.ssh/mux-%r@%h:%p
    ControlPersist         8h
    StrictHostKeyChecking  yes
    UserKnownHostsFile     ./known_hosts
```

Inventory does not set `ansible_ssh_user` for the bastion host.
##### Environment:

N/A
##### Summary:

As of c271c0e, Ansible now overrides the ssh User option, using my local username, with `-o User=sheldonh`.

Thus it is no longer possible to set the User in a custom `ssh_config`. It must now be set with ansible_ssh_user in inventory.

If that was an intentional change, it's probably worth mentioning in the release notes.

I'm not sure what the change was intended to fix, so I can't recommend a way forward yet.
##### Steps To Reproduce:

See `Ansible Configuration` above. Then apply a play to `hosts: bastion` (which I do to wait for SSH to become available on instances behind the bastion), using `ansible-playbook -vvvv` to observe the SSH command.
##### Expected Results:

```
ssh -C -vvv -F ./ssh_config -q -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -tt bastion ...
```
##### Actual Results:

```
ssh -C -vvv -F ./ssh_config -q -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=sheldonh -o ConnectTimeout=10 -tt bastion
```

Note that the User option is now overriden, since the command line option supersedes the one specified in the `ssh_config`.

**Comment by bcoca** [comment]
updated changelog in 38cc0705c640135023f1589ff9d1bf1994a98b84

if you want to respect the .ssh/config do not set the user, this is now inline with how ssh itself works.

**Comment by sheldonh** [comment]
Mmmkay. This doesn't sound true: "Leaving it unset will still use the same user and respect .ssh/config". This is the problem I'm reporting: leaving it unset does not respect `.ssh/config`, but instead overrides it with the local username.
