### ISSUE TITLE
ansible-galaxy init has different default directory than ansible-galaxy install

### ISSUE THREAD

**Issue by Petrox** [ansible/ansible#13031]
Issue Type: Bug Report
Ansible Version: 1.9.4
Ansible Configuration:

I use ansible in a "standalone" way, so my stuff is not in /etc, but I've got an ansible dir under version control, an ansible.cfg and roles directory, playbooks directory, files directory too.

The ansible.cfg has:

```
roles_path    = roles
```

Environment: Ubuntu 14.04 trusty + ansible 1.9.4 from PPA

Summary:

 When I'm installing a role with ansible-galaxy, it respects the "roles" path found in the ansible.cfg in the current directory.

 When I do ansible-galaxy init some.role , it does not respect the roles path found in ansible.cfg, but it uses the current directory. (As it's in the manual.)

 As these features both create roles in my environment, I believe they should work symmetrically, when standing in the same directory, and working with the same ansible.cfg, the resulting role should born under the roles directory.

 The current state:

```
$ ansible-galaxy init --help
...
  -p INIT_PATH, --init-path=INIT_PATH
                        The path in which the skeleton role will be created.
                        The default is the ***current working directory***.
...
```

So it works like documented, but this behaviour it conflicts with the install actions default parameters:

```
$ ansible-galaxy install --help
...  
  -p ROLES_PATH, --roles-path=ROLES_PATH
                        The path to the directory containing your roles. The
                        default is the **roles_path configured in your
                        ansible.cfg file (/etc/ansible/roles if not
                        configured)**
...
```

So fixing the problem would:
- need changing the init code
- need changing the init help text
- need fixing the docs
- cause some discomfort for the users who already use galaxy-ansible init
- fortunately this is a manual process (it's not a too common usecase to programmatically generate roles)
  
  I am willing to create a pull request with the changes if you decide this default setting harmonization would benefit ansible-galaxy in the longterm.

Steps To Reproduce:

```
mkdir someansibletesting
cd someansibletesting
```

copy an ansible.cfg here, with 

```
roles_path    = roles
```

Good result:

```
$ ansible-galaxy install tommarshall.mycli
- downloading role 'mycli', owned by tommarshall
- downloading role from https://github.com/tommarshall/ansible-role-mycli/archive/master.tar.gz
- extracting tommarshall.mycli to roles/tommarshall.mycli
- tommarshall.mycli was installed successfully

$ ls -ld roles/tommarshall.mycli/
drwxrwxr-x 1 vagrant vagrant 4096 Nov  4 08:25 roles/tommarshall.mycli/
```

Expected Results:

The some.role should born under roles as it's set in the ansible.cfg

```
$ ansible-galaxy init some.role
- roles/some.role was created successfully
$ ls -ld roles/some.role
drwxrwxr-x 1 vagrant vagrant 4096 Nov  4 08:26 roles/some.role
$ ls -ld some.role
ls: cannot access some.role: No such file or directory
```

Actual Results:

**Works as documented**, but does not work as **expected**:

```
$ ansible-galaxy init some.role
- some.role was created successfully
$ ls -ld roles/some.role
ls: cannot access roles/some.role: No such file or directory
$ ls -ld some.role
drwxrwxr-x 1 vagrant vagrant 4096 Nov  4 08:26 some.role
```

**Comment by ssbarnea** [comment]
My vote is for keeping this behaviour as is and eventually making more obvious the difference. Here is an important reason for this: we do keep our community roles in a different role directory than internal ones and when we create a new role we do not want to create it inside the first role search PATH, we do want to create it in current directory, like now.

**Comment by jimi-c** [comment]
As there has been no movement or any work done on this in over 6 months, we're going to go ahead and close this now. I do feel that changing the behavior from how it currently is could cause problems, so we do not have any plans to change this.

If you would like to continue the discussion or revisit this idea, please move the conversation to the devel mailing list or IRC channel, or bring it up at one of our bi-weekly community meetings
- https://groups.google.com/forum/#!forum/ansible-devel
- #ansible-devel or #ansible-meeting (Tuesdays and Thursdays) on Freenode

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by zemmali** [comment]
**Use Ansible galaxy init to create a default 'common' role**

`ansible-galaxy init common --init-path=${PROJECT_PATH}/roles/`
