### ISSUE TITLE
Synchronize module asks for password

### ISSUE THREAD

**Issue by messiahUA** [ansible/ansible#13034]
**Issue Type:** Bug Report
**Ansible Version:** ansible 2.0.0 (devel 061b83c)
**Ansible Configuration:** become=yes
**Environment:** Debian 7

**Summary:**
Synchronize module asks for password when using sudo (become) and ssh key-based auth using ssh-agent.

**Steps To Reproduce:**
1. Setup ssh key-auth (ssh-agent).
2. Execute:

```
ansible server -m synchronize -a "src=scripts dest=/root/test"
```

**Expected Results:** Synchronize module should not ask for password.

**Actual Results:**

```
user@server's password:
user@server's password:
user@server's password:

fatal: [server]: FAILED! => {"changed": false, "cmd": "rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --rsync-path=\"sudo rsync\" --out-format='<<CHANGED>>%i %n%L' \"/home/user/playbooks/roles/role/files/scripts\" \"user@server:/root/test\"", "failed": true, "msg": "Permission denied, please try again.\r\nPermission denied, please try again.\r\nPermission denied (publickey,password).\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]\n", "rc": 255}
```

**Comment by philltomlinson** [comment]
I have seen something similar when running the shell module along with a with_items. It runs the first command but then on the second one it prompts for a key password and fails the task:

```
-name: Shell commands
 shell: "{{item}}"
 with_items:
  - echo "test 1"
  - echo "test 2"
```

When running the playbook you get prompted for a key

```
Enter passphrase for key '/home/vagrant/.ssh/id_rsa':
```

**Comment by jimi-c** [comment]
@philltomlinson could you please open a new issue for that?

**Comment by jimi-c** [comment]
Also, was that with ssh-agent too?

**Comment by philltomlinson** [comment]
Yes - it was with ssh-agent too. It works on v2.0.0-0.3.beta1 tag but not on later tags.

Will raise a new issue to track that.

**Comment by philltomlinson** [comment]
Issue #13062 Opened

**Comment by messiahUA** [comment]
I've updated to devel 79c311a33f and now I get root instead of user:

```
root@server's password:
root@server's password:
root@server's password:
server | FAILED! => {
    "changed": false,
    "cmd": "rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --rsync-path=\"sudo rsync\" --out-format='<<CHANGED>>%i %n%L' \"scripts\" \"server:/root/test\"",
    "failed": true,
    "invocation": {
        "module_args": {
            "_local_rsync_path": "rsync",
            "dest": "server:/root/test",
            "rsync_path": "\"sudo rsync\"",
            "src": "scripts"
        },
        "module_name": "synchronize"
    },
    "msg": "Permission denied, please try again.\r\nPermission denied, please try again.\r\nPermission denied (publickey,password).\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]\n",
    "rc": 255
}

```

**Comment by messiahUA** [comment]
As of f873cc0fb54f309aa9ece4e4127bdf1071d1bfd7 it works as expected as far as I see.

**Comment by jacobweber** [comment]
I am seeing this on ansible 2.0.0.1:

```
$ ansible server --become -m synchronize -a 'src=/tmp/foo/ dest=/tmp/foo'
ansible@server's password: 
ansible@server's password: 
ansible@server's password: 
server | FAILED! => {
    "changed": false, 
    "cmd": "rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --rsync-path=\"sudo rsync\" --out-format='<<CHANGED>>%i %n%L' \"/tmp/foo/\" \"ansible@server:/tmp/foo\"", 
    "failed": true, 
    "msg": "Permission denied, please try again.\r\nPermission denied, please try again.\r\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(600) [sender=3.0.6]\n", 
    "rc": 255
}
```

On the other hand:

```
$ ansible server --become -m ping
server | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
```

Both hosts are on CentOS 6.7. The same command works on Ansible 1.9.

**Comment by abadger** [comment]
From some notes in #13825, it sounds like this should be fixed now that  #13825 has been fixed.  If anyone would care to test this with a checkout of the devel or stable-2.0 branch (or 2.0.1rc1 when we create that tarball) that would be great.

**Comment by abadger** [comment]
Closing as it should be fixed by the solution to #13825

**Comment by ramayer** [comment]
I think I'm seeing the same thing on the version of ansible that was distributed with Ubuntu16.04. 

Any good workarounds?

**Comment by rishibamba** [comment]
Synchronize breaking on ansible 2.3.1.0 too. Rest modules working fine.
RHEL 7

Error:  "failed": true, "msg": "Permission denied, please try again.\r\nPermission denied, please try again.\r\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]\n", "rc": 255}
