### ISSUE TITLE
Unexpected Exception: Values instance has no attribute 'serial'

### ISSUE THREAD

**Issue by RusDavies** [ansible/ansible#13037]
##### Issue Type:

 Bug Report
##### Ansible Version:

2.0.0 (devel branch on github)

I've noticed the issue in commit 0abeff45115689cd8e1262c8c666c9263977c499.  It was in this commit that the problematic use of 'self._options.serial' is introduced.
##### Ansible Configuration:

Stock Fedora 21
##### Environment:

Fedora 21
Ansible from devel branch 
##### Summary:

Attempting to run any playbook results in the following exception:

``` bash
Unexpected Exception: Values instance has no attribute 'serial'
```
##### Steps To Reproduce:
1. Install from devel branch
2. Run any playbook
3. Observe exception
##### Expected Results:

Playbook should run without throwing exceptions.
##### Actual Results:

Running any playbook results in the following exception: 

``` bash
$ ansible-playbook -vvv test.yml 
Using /etc/ansible/ansible.cfg as config file
Unexpected Exception: Values instance has no attribute 'serial'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 84, in <module>
    sys.exit(cli.run())
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 140, in run
    pbex = PlaybookExecutor(playbooks=self.args, inventory=inventory, variable_manager=variable_manager, loader=loader, display=self.display, options=self.options, passwords=passwords)
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 59, in __init__
    self._tqm = TaskQueueManager(inventory=inventory, variable_manager=variable_manager, loader=loader, display=display, options=options, passwords=self.passwords)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 97, in __init__
    num_workers = min(self._options.forks, self._options.serial, len(self._inventory.list_hosts()))
AttributeError: Values instance has no attribute 'serial'
```
##### Aditional notes

The issue seems to stem from the introduction of 'self._options.serial' in commit 0abeff45115689cd8e1262c8c666c9263977c499.  Is there a missing import, such as `import serial`, or `from serial import serial`?

**Comment by Yannig** [comment]
+1
