### ISSUE TITLE
Bracket+colon targetting pattern not working

### ISSUE THREAD

**Issue by elouanKeryell-Even** [ansible/ansible#13043]
### Issue Type:

Bug Report
### Ansible Version:

```
$ ansible --version
ansible 1.9.4
```
### Ansible Configuration:

No changes (I'm deploying Virtual Machines on a cloud platform and the only ansible-related thing I do in my deployment script is installing the package.)
### Environment:

CentOS 7
### Summary:

This kind of targetting pattern doesn't work :

`- hosts: group[0:1]`
### Steps To Reproduce:
- Create a group with at least two hosts in your inventory. Mine looks like:

```
[slave]
212.128.50.165
212.128.50.166
212.128.50.164
212.128.50.162
```
- Create a minimal playbook targetting that group with a bracket+colon pattern:

```
# cat test-playbook.yml

---
- hosts: slave[0:2]

  tasks:
  - name: test ping
    ping:
```
- Execute playbook:

`# ansible-playbook test-playbook.yml`
### Expected Results:

Referring to [the docs](http://docs.ansible.com/ansible/intro_patterns.html), I would have expected this to work.

```
212.128.50.165 | success >> {
    "changed": false,
    "ping": "pong"
}

212.128.50.164 | success >> {
    "changed": false,
    "ping": "pong"
}
```
### Actual Results:

```
# ansible-playbook test-playbook.yml

PLAY [slave[0:2]] *************************************************************
skipping: no hosts matched

PLAY RECAP ********************************************************************

```

**Comment by amenonsen** [comment]
Your pattern works exactly as documented in version 2.0. I know it was broken for some time in 1.x; maybe `slave[0-3]` will accomplish what you want there (note the off-by-one). That syntax is no longer supported.

**Comment by elouanKeryell-Even** [comment]
Ok I tested with a dash instead of the colon and it works.

However, the docs also mention syntax `slave[0:]`, and the dash-equivalent syntax `slave[0-]` doesn't work neither. If I was to fix the doc, should I remove the mention to that or is there really a way to do it?

**Comment by amenonsen** [comment]
No, I don't think there's any working way to do the `slave[0:]` thing in 1.9.
