### ISSUE TITLE
Vault encrypted group_vars are exposed when running playbook commands that fail.

### ISSUE THREAD

**Issue by NeMO84** [ansible/ansible#13052]
I ran into what seems like a security leak issue when provisioning a server. I was bootstrapping a CoreOS server and one of the tasks I have requires the login in to DockerHub. Luckily, there is a docker command that allows the login to happen via parameters. Here is the task command I am using:

```
docker login -e {{ docker_email }} -u {{ docker_username }} -p {{ docker_password }}
```

I decided to use group_vars to store those details and then ran the vault encrypt command on the group vars file. So far everything seemed to be going good. When I ran the playbook, it failed at the login step, as expected, because I had typed the username wrong. 

But what got my attention is that the error message exposed the original password as it echoed out the error message (I replaced my sensitive info):

> TASK: [Login to DockerHub] ***************************************************\* 
> failed: [job-01] => {"changed": true, "cmd": "docker login -e johndoe@site.com -u jdoe -p P@$$", "delta": "0:00:00.194040", "end": "2015-11-05 22:46:15.901788", "rc": 1, "start": "2015-11-05 22:46:15.707748", "warnings": []}
> stderr: Error response from daemon: Registration: "email is already associated with an account"
> FATAL: all hosts have already failed -- aborting

The error is expected and the failure is expected. I am wondering if there is any way to hide/encrypt the error message when a vaulted variable is used within the module; in this case the command module.

**Comment by bcoca** [comment]
this is what the `no_log` directive is for, once unencrypted there is no real way to distinguish between a vault and non vault var/value

**Comment by abadger** [comment]
So your updated playbook task should look something like this:

```
    - command: "docker login -e {{ docker_email }} -u {{ docker_username }} -p {{ docker_password }}"
      no_log: True
```
