### ISSUE TITLE
ansible is ignoring user settings on ~/.ssh/config

### ISSUE THREAD

**Issue by dnegreira** [ansible/ansible#13057]
Hi,

Im trying to set a remote ssh user via ~/.ssh/config but ansible is not using that user.
On the changelog I see the following line.

"We do not ignore the explicitly set login user for ssh when it matches the 'current user' anymore, this allows overriding .ssh/config when it is set explicitly. Leaving it unset will still use the same user and respect .ssh/config."

But this is currently not happening, the user is still ignored if I set in the options in ~/.ssh/config.

Steps to reproduce:

set a user  on ~/.ssh/config like:

```
Host 127.0.0.1
User Username
```

Create a dummy playbook:

```

---
- hosts: localhost
roles: 
  - nginx
```

Create a dummy inventory file like:

```
[localhost]
127.0.0.1
```

Run ansible-playbook with a different user than defined in User above and you will see that the ssh option  "-o User=" is passed as an argument with the username that it is running the playbook and not the one specified in the ~/.ssh/config 

```
whoami
dnegreira
```

```
ansible-playbook -vvvv tests.yml -i inventory 
No config file found; using defaults
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default). This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
2 plays in tests.yml
Loaded callback default of type stdout, v2.0

PLAY ***************************************************************************

TASK [setup] *******************************************************************
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: dnegreira
<127.0.0.1> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=dnegreira -o ConnectTimeout=10 .....................................
```

So it seems ansible is ignoring the ~/.ssh/config options although I defined a username there.

**Comment by amenonsen** [comment]
This is the same problem as reported in #13032; I haven't looked into it carefully, but isn't c271c0eb relevant? It looks to me as though that's always going to set `ansible_user` and therefore pass in `-o User=…`.

**Comment by dnegreira** [comment]
It should pass the -o User= but in this case it should pass the one defined in ~/.ssh/config and, as you refered from what i understand in that code it is always passing the current user running the command and not the one defined in ~/.ssh/config.

**Comment by amenonsen** [comment]
No no, that's not how it works. Ansible doesn't (and shouldn't) look at `~/.ssh/config` at all, so there's no question of including the `-o User=x` based on that file; what you want Ansible to do in this case is not set User on the command-line at all, because specifying it there makes it override the setting in the config file (which is read and interpreted by ssh). But yeah, that commit looks like it'll always lead to the user being set on the command-line, leading to the problem that you're seeing.

**Comment by dnegreira** [comment]
You are absolutely correct.

**Comment by bcoca** [comment]
No, that commit only sets information for the RETURN data, after calling ssh, I just tested and if user/remote_user is NOT set, .ssh/config is picked up and used.

The change was to not ignore the remote_user anymore when set, which was not overriding .ssh/config as people intended when explicitly setting the user. Ansible now works much closer to how ssh works by not ignoring explicit settings and passing them to ssh.

It is not clear if you are explicitly or not setting the remote_user, can you confirm which is the case?

**Comment by dnegreira** [comment]
remote_user is not defined in any part of the ansible playbook or ansible configuration when this happens.

**Comment by bcoca** [comment]
your .ssh/config does not seem correct, is `User` indented?

**Comment by bcoca** [comment]
hmm, nvmd, my test was flawed, yes that last commit introduces the issue as it resets the connection var, but that was not supposed to be used in 'current task' only in return values. That does not seem to be the case anymore.

**Comment by bcoca** [comment]
reverted https://github.com/ansible/ansible/commit/c271c0eb04f540bce8a4d6544cbcbc36dd2835a3 as I was wrong about what this actually did in the end.

**Comment by dnegreira** [comment]
I confirm that after the revert it is working as expected. Thanks!

**Comment by umeboshi2** [comment]
```
cypress.littledebian.org | FAILED => SSH encountered an unknown error. The output was:                                                                          
OpenSSH_6.7p1 Debian-5, OpenSSL 1.0.1k 8 Jan 2015                               
debug1: Reading configuration data /freespace/home/umeboshi/.ssh/config         
debug1: /freespace/home/umeboshi/.ssh/config line 22: Applying options for cypress.littledebian.org                                                             
debug1: /freespace/home/umeboshi/.ssh/config line 34: Applying options for *    
debug1: Reading configuration data /etc/ssh/ssh_config                          
debug1: /etc/ssh/ssh_config line 22: Applying options for *                     
debug1: auto-mux: Trying existing master                                        
debug1: Control socket "/freespace/home/umeboshi/.ansible/cp/ansible-ssh-cypress.littledebian.org-22-umeboshi" does not exist                                   
debug2: ssh_connect: needpriv 0                                                 
debug1: Connecting to cypress.littledebian.org [23.126.215.162] port 22.        
```

Here is the relevant part of ~/.ssh/config:

```
Host cypress.littledebian.org
    Port 23

```

**Comment by umeboshi2** [comment]
This is from the docs:

"If you have hosts that run on non-standard SSH ports you can put the port number after the hostname with a colon. Ports listed in your SSH config file won’t be used with the paramiko connection but will be used with the openssh connection."

The docs seem to indicate that my ssh config will be read and used by openssh, and I was surprised when ssh debug reads the config, yet still seems to want to connect to port 22 regardless.
