### ISSUE TITLE
inventory variables should have more weight

### ISSUE THREAD

**Issue by RainerW** [ansible/ansible#13054]
When running a playbook, variables defined in the inventory ( or inventory groups) should have a higher weight then playbook group_vars. They should actually be at the same 'level' als the extra vars ( http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable ).

Why?
Because inventories are a commandline option and naturally they are therefore very specific for a given environment. One would expected them to overwrite playbooks variables.
E.g. we use the same playbook in all our enviroments. And let the designated site-teams provide their inventory with environment specific endpoints, key and certs etc. And these should not be checked in a low(er) security repository ( even with vault ).

Workarounds:
- extra vars
  This works, but does not have the power of groups, so you cannot have one site.yml run, but  differences in group variables.
- group_vars
  Will overwrite the inventory, but not playbook variables ( that only works with extra vars ).

Suggestion:
Sort variable precedence from the less specific ones to more specific ones:
- role defaults
- playbook group_vars
- playbook host_vars
- host facts
- registered vars
- set_facts
- play vars
- play vars_prompt
- play vars_files
- role and include vars
- block vars (only for tasks in block)
- task vars (only for the task)
- > inventory vars <
- > inventory group_vars <
- > inventory host_vars <
- extra vars

**Comment by abadger** [comment]
This is something to discuss on the mailing list and then open a ticket if the consensus there is that this is a change we want to implement.  Looking at where inventory has sat historically, I think it's likely the consensus will be that it's too big a backwards compatibility break to change.  However your CLI rationale is worth mentioning to see if it persuades anyone.  I'll paste the list information below.

# Submission Received

Can you please post on ansible-development list so we can talk about this idea with the wider group?
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you once again for this and your interest in Ansible!
