### ISSUE TITLE
Documentation says "True" and "False", ansible says "yes" and "no"

### ISSUE THREAD

**Issue by larsks** [ansible/ansible#1305]
Based on the [documentation](http://ansible.cc/docs/modules.html#user), I had:

```
- action: user name=localadmin system=yes state=present home=/var/lib/localadmin createhome=False
```

And ansible complained:

```
failed: [10.243.28.11] => {"failed": true, "msg": "value of createhome must be one of: yes,no, got: False"}
```

**Comment by mpdehaan** [comment]
Yes/no is correct, we can fix docs, thanks!

**Comment by larsks** [comment]
I wonder if maybe the docs are correct and ansible needs fixing...because other boolean options (e.g., `sudo`) take `True` and `False` instead of `yes` or `no`.  Or maybe you should accept all four strings anywhere a boolean is expected (and have a single routine that turns True/False/yes/no/true/false into a boolean value).

**Comment by mpdehaan** [comment]
sudo takes True/False

modules take yes/no but also are smart enough to take True/False if you
feed them that.  They already deal with all of this.

The config file is a new thing so it's not all in the docs perfectly yet.

Patience, grasshopper!

**Comment by mpdehaan** [comment]
In other words, we have that function that takes the boolean stuff
already.  If you see a module that doesn't use it, let me know which.

grep the library sources for module.boolean and choices=module.BOOLEANS

**Comment by mpdehaan** [comment]
ah, module was not using that.   Fixing!  Thanks!
