### ISSUE TITLE
IndexError: list index out of range due to commit 3c35655b529751e608403e88ccc9fc2ef68ccc42

### ISSUE THREAD

**Issue by RusDavies** [ansible/ansible#13061]
##### Issue Type:

Bug Report
##### Ansible Version:

2.0.0 from devel branch
##### Ansible Configuration:

Stock Fedora 21
##### Environment:

Fedora 21
Ansible from devel branch

`/etc/ansible/hosts` defined with 1 group but no hosts, as follows: 

```
[webservers]
```

Trivial playbook, acting only on localhost, as follows:

``` yaml

---
- name: Test
  hosts: localhost
  gather_facts: false
  tasks: 
    - name: Hello World
      command: echo Hello World
```
##### Summary:

Commit 3c35655b529751e608403e88ccc9fc2ef68ccc42 changed the way `num_workers` is calculated. 

Previously, with no hosts defined, but with localhost being implicit, `num_workers` would be 1. 

With the new change, for the same scenario, `num_workers` is 0.  This causes an `IndexError: list index out of range` in subsequent code. 
##### Steps To Reproduce:
1. Ensure /etc/ansible/hosts is configured as described above
2. Create the playbook described above
3. Run the playbook
4. Observe an `IndexError`` exception is thrown
5. Add a single host to the group in /etc/ansible/hosts
6. Run again
7. Observe success
##### Expected Results:

Prior to commit 3c35655b529751e608403e88ccc9fc2ef68ccc42, for the case where no hosts are defined, and with localhost being implicit, the described playbook would run without error.  
##### Actual Results:

Since commit 3c35655b529751e608403e88ccc9fc2ef68ccc42, the same scenario results in the following error being thrown:

```
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 84, in <module>
    sys.exit(cli.run())
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 142, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 140, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 229, in run
    return strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 237, in run
    self._queue_task(host, task, task_vars, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 150, in _queue_task
    (worker_prc, main_q, rslt_q) = self._workers[self._cur_worker]
IndexError: list index out of range
```
##### Additional Information.

The problem is in how `num_workers` is calculated, in line 98 of commit 3c35655b529751e608403e88ccc9fc2ef68ccc42.  

Given that localhost is implicit, then `num_workers` should never be less than 1, yet is calculated as 0 for the case of no hosts defined. 

Modiifying line 98 of commit 3c35655b529751e608403e88ccc9fc2ef68ccc42 as follows seems to mitigate the issue:

``` python
 num_workers = max(1, min(self._options.forks, len(self._inventory.list_hosts())))
```

**Comment by bcoca** [comment]
was already fixed in 931eb16e55b364878973f8e891cd021462aaa74e
