### ISSUE TITLE
Empty with_* should skip task

### ISSUE THREAD

**Issue by jonashaag** [ansible/ansible#13096]
This is a ticket to remind about #1408, which remains unfixed so far.

**Comment by bcoca** [comment]
so I cannot seem to reproduce this issue in 1.9.4 (nor 2.0)

```ansible-playbook --version
ansible-playbook 1.9.4
  configured module search path = None

```

my play:

```
- hosts: localhost
  gather_facts: False
  vars:
    mylist: []
  tasks:
  - debug: var=item
    with_items: "{{mylist}}"

```

my results:
```

---

< PLAY [localhost] >

---

```
    \   ^__^
     \  (oo)\_______
        (__)\       )\/\
            ||----w |
            ||     ||
```

---

< TASK: debug var=item >

---

```
    \   ^__^
     \  (oo)\_______
        (__)\       )\/\
            ||----w |
            ||     ||
```

skipping: [localhost]

---

< PLAY RECAP >

---

```
    \   ^__^
     \  (oo)\_______
        (__)\       )\/\
            ||----w |
            ||     ||
```

localhost                  : ok=0    changed=0    unreachable=0    failed=0  

```
```

**Comment by jonashaag** [comment]
Maybe this has something to do with having ``"{{...}}"` around the expression, which I don't have.

**Comment by bcoca** [comment]
then it might be confused with a literal string

**Comment by bcoca** [comment]
i removed the " {{ }}" and it still skips the task

**Comment by jonashaag** [comment]
Okay, in my case it's `groups['some group']` which can be empty. It also chokes if the list is `null`.

**Comment by bcoca** [comment]
so tested with  `groups['empty']` and it is still skipped. As for null/None,  any value that is not a list or empty list will be converted to an item in a list. So a null variable is turned int a null element in a list.

Unless you can show me an example of an empty list not being skipped I'm going to consider this a non issue.

**Comment by jonashaag** [comment]
The root cause here seems to be that `groups['missing group']` is `null` and not `[]`, which I expected it to be. But that's probably for good reasons. I'm not sure it makes sense to default the `groups` dict to the empty list.

I'll close this; sorry for taking your time, I should've debugged this issue in more detail before opening the ticket.

**Comment by bcoca** [comment]
wierd, when i defined the 'empty' group i got an empty list 

```
/etc/ansible/hosts
[empty]
```

**Comment by jonashaag** [comment]
Yes but if you leave the `[empty]` out entirely, so the group is _missing_, not _empty_, then it'll be null.
