### ISSUE TITLE
fact_caching_connection don't handle path expansion of ~ nor $HOME

### ISSUE THREAD

**Issue by davidfischer-ch** [ansible/ansible#13094]
Version: 1.9 but probably also devel.

When I configure a fact caching directory using the jsonfile cache plugin, I am specifying its path using the ~ or $HOME variable. This works with other parameters like retry_files_save_path but not with fact_caching_connection ... Ansible fails with a message that the directory does not exist. What is false.

**Comment by jimi-c** [comment]
@davidfischer-ch could you check devel? We have cleaned up a lot of issues there in regards to stuff like this, so this is probably fixed.

**Comment by bcoca** [comment]
In this case current devel also does not do path expansions as this parameter is mostly used for network locations, only the jsonfile plugin overloads it for use as a path. Other parameters that are clearly and only paths do get expanded.
