### ISSUE TITLE
"mode" in various module is not working if you put directly the octal value

### ISSUE THREAD

**Issue by sterfield** [ansible/ansible#13115]
# context
- Ansible version: 1.9.4
- OS targeted: confirmed on Mac OS and Debian *
# steps to reproduce
1. create a file, for example /tmp/test
2. create a file with this code:

``` yaml

---
- hosts: all
  tasks:
      file:
        path: /tmp/test
        mode: 4755
```
1. execute the playbook

``` bash
ansible -i <target> -u root -k test_mode.yml
```
# Current results

The file will have some strange rights:

```
--w--w--wt  1 root  root  0 Nov 10 16:48 /tmp/test
```
# Expected results

The file should have the correct rights:

``` bash
chmod 4755 /tmp/test
ls -l /tmp/test
-rwsr-xr-x  1 root  root  0 Nov 10 16:48 /tmp/test
```
# Additional note
- The quick workaround is to put the octal parameters between quotes and the issue disappear.
- The issue is not present if you put the mode in octal, without specifying set uid or set gid. For example, this works:

```
...
mode: 0755
...
```

The result: 

```
-rwxr-xr-x  1 root  root  0 Nov 10 16:48 /tmp/test
```
- This issue is present in multiple modules, confirmed with "file" and "copy" module.
- If you use a file "mode" in symbolic notation, it works fine.

Thanks!

**Comment by sivel** [comment]
If the mode does not start with a `0`, you need to quote the mode, otherwise it is assumed to be a decimal mode instead of an octal mode.  Decimal mode `4755` is equivalent to octal mode `011223`, which causes your strange permissions.

Solutions:

```
mode: 04755
```

or 

```
mode: "4755"
```

**Comment by sivel** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
