### ISSUE TITLE
copy_module will move file instead copying it (remote_src=true)

### ISSUE THREAD

**Issue by theraser** [ansible/ansible#13128]
Issue Type: Bug Report
Ansible Version: ansible 2.0.0 (devel b2a9111b22) last updated 2015/11/11 15:03:24 (GMT +200)
Environment: Ubuntu 15.04
Summary: Ansible will not copy but move a file when called with force=no and remote_src=true
Steps to reproduce:

``` YAML
copy: src=/usr/share/php5/php.ini-production dest=/tmp/test.conf remote_src=true
```

Expected Result: _/usr/share/php5/php.ini-production_ will be **copied** to _/tmp/test.conf_

Actual Result: _/usr/share/php5/php.ini-production_ will be **moved** to _/tmp/test.conf_; source file is removed. Ansible will fail when source file system is read-only as it cannot remove the file (/usr is mounted read-only in this example):

`fatal: [removed]: FAILED! => {"changed": false, "failed": true, "msg": "{\"msg\": \"Could not replace file: /usr/share/php5/php.ini-production to /tmp/test.conf: [Errno 30] Read-only file system: '/usr/share/php5/php.ini-production'\", \"failed\": true}\r\nException OSError: (2, 'No such file or directory', '/tmp/.ansible_tmp8zPmHVtest.conf') in <bound method _TemporaryFileWrapper.__del__ of <closed file '<fdopen>', mode 'w+b' at 0x7f241188c4b0>> ignored\r\n", "parsed": false}`

**Comment by chrrrles** [comment]
I am unable to replicate this bug using the latest 2.0.0 (devel 478c6c756a) - Is there more information that you may provide to recreate the condition?

**Comment by chrrrles** [comment]
@theraser can you test this again with the latest devel? -- I was unable to duplicate the issue.

**Comment by bcoca** [comment]
fixed via http://github.com/ansible/ansible-modules-core/commit/6e37f1dcef0e38ea6b9222cf49aa66df0e3a3c45
