### ISSUE TITLE
Missing documentation for lookup plugin dig

### ISSUE THREAD

**Issue by azaghal** [ansible/ansible#13126]
**Issue Type:** Documentation Report
**Ansible Version:** 1.9.4
**Ansible Configuration:** N/A
**Environment:** Debian Jessie (N/A?)

**Summary:**

Lookup plugin **dig** is not documented on the http://docs.ansible.com/ansible/playbooks_lookups.html page.

**Expected results:**

Lookup plugin **dig** is documented.

**Actual results:**

Lookup plugin **dig** is not documented.

**Comment by azaghal** [comment]
This is probably  a very easy thing to provide - unless someone beats me to it, I'll try to submit a pull request.

**Comment by chrrrles** [comment]
Hi azaghai - Documentation for this plugin is welcome.  Were you planning on creating a new section, or adding it to the "More Lookups" part of the page?

cc'ing @docschick

**Comment by bcoca** [comment]
we are also thinking of 'autodocumenting' all plugins like we currently do with modules, so lookup, filter, connection, etc should all get documented and appear in the site once added. But this is still in the planning stage so go ahead and submit the docs as we'll need them for the plugin anyways.

**Comment by azaghal** [comment]
I'm not sure, to be honest, but it feels like it would be better to have a new section with less frequently uses lookups. Another choice could be to have more of a dedicated reference-like section for plugins in general, and perhaps this could be a start of it (i.e. introduce a couple of lookups in practical examples, and move rest to this separate section)?

But, in the end, whatever you would prefer as location :)

**Comment by azaghal** [comment]
Given @bcoca 's comment - perhaps for now I can add it in same part of docs as where the rest of lookups are mentioned? Although this one is a bit more complex, I think.

**Comment by mscherer** [comment]
So, can this bug be closed, since the patch was merged ?

**Comment by docschick** [comment]
Closing based on merges for missing docs.
