### ISSUE TITLE
Handlers upgrades

### ISSUE THREAD

**Issue by apenney** [ansible/ansible#1312]
It would be nice to be able to do custom actions upon errors.  I have a use case where I wish to iterate over a list of git branches and do a git pull/clone for each in turn.  If a branch has been deleted it would be nice to detect a git pull failure and allow the handler to remove the files on disk.

Other examples might be "if this command fails to run for any reason, the handler should flag the node as broken in the LB" etc.

**Comment by mpdehaan** [comment]
It has also been requested a few times to have a way to flag a handler such that always runs, even if something previous fails.

This may also imply a step that always runs, always.

Fair warning on those above cases -- This previously got squashed because there was too many different ways to interpret it and none of the use cases were all encompassing.

**Comment by bcoca** [comment]
What about something like this?

handlers:  
    - name: restart apache
      action: service name=apache state=restarted on=all|error|any|#

all: runs if all notifiers succeed (default)
error: execute if any notifier fails
any: run if any notifier succeeds 
# (threshold), least number of tasks that must succeed or fail to execute, use negative for fail (-2 = 2 or more tasks must fail to execute)

This covers most cases I can think of.

**Comment by mpdehaan** [comment]
That would imply it's just an argument to the module, not so much flagging
it for a 'why'.

I'll work on syntax... there are a few things in the queue ahead of this.

**Comment by bcoca** [comment]
does this make more sense?:

<pre>
- name: restart apache
action: service name=apache state=restarted 
trigger_on=all|error|any|#
</pre>

**Comment by dhozac** [comment]
I don't think it makes any sense to set this on the handler. I think this should be a notify_on_failure: that notifies a /different/ handler. As for the second use-case (running something on any error), it seems like a play version of the same.

**Comment by mpdehaan** [comment]
let's discuss this on list, it's of high enough general interest and not
everyone looks at the tickets.

**Comment by mpdehaan** [comment]
see also #1358 discussion, which I am closing, only because it's kind of all related.

**Comment by mpdehaan** [comment]
It should be noted that pre_task and post_tasks allow some level of handler flushing (when they run now) as well as you can say:

tasks:
- meta: flush_handlers

to run them at any time.

Given the other stuff can be implemented with "when" I don't think we need the rest.

Handlers are allowed to have conditionals attached.

**Comment by kevinburke** [comment]
I just came across this. One of the use cases in both tickets was something like 

```
notify: supervisor restart {{ service_name }}
```

or 

```
notify: supervisor restart service_name=apache
```

I've searched all over and it still doesn't seem like there's a good way to do that.
