### ISSUE TITLE
Fix for issue #12952 has broken debug ability to print collections e.g. hostvars[inventory_hostname]

### ISSUE THREAD

**Issue by j3ffrw** [ansible/ansible#13125]
## Ansible Version:

<pre><code>
$ ansible-playbook --version
ansible-playbook 2.0.0 (detached HEAD 21b76dee6f) last updated 2015/11/11 11:38:00 (GMT +800)
  lib/ansible/modules/core: (devel b1e2fe3dea) last updated 2015/11/11 08:00:37 (GMT +800)
  lib/ansible/modules/extras: (devel 9ec7fdebb7) last updated 2015/11/11 08:01:35 (GMT +800)
  config file = 
  configured module search path = None
</code></pre>

## Ansible Configuration:

<p>no changes made from github except from checking out w/c commit broke the functionality</p>

## Environment:

<pre><code>
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 17.2 Rafaela
Release:    17.2
Codename:   rafaela
</code></pre>

## Summary:

<p>
Hi, the fix for issue #12952 has broken ability to print collections 
commit: 21b76dee6f169d2e398cdb5426a108651328123b
</p>

## Steps To Reproduce:

<p>Create the inventory file and play.yml</p>

- inventory

<pre><code>host1 ansible_ssh_host=127.0.0.1 ansible_ssh_port=22

[myhostgroup]
host1</code></pre>

- play.yml

<pre><code>- hosts: all
  connection: local
  vars:
    var1: "1"
    var2: "2"
  tasks:
    - debug: var={{item}}
      with_items: [ 'var1', 'var2' ]
    - debug: var="{{hostvars[inventory_hostname]}}"</code></pre>

<p>Run playbook.</p>

<pre><code>ANSIBLE_NOCOWS=1 ansible-playbook -i inventory play.yml</code></pre>

## Expected Results:

<pre><code>TASK [debug var={{item}}] ******************************************************
ok: [host1] => (item=var1) => {
    "item": "var1", 
    "var1": "1"
}
ok: [host1] => (item=var2) => {
    "item": "var2", 
    "var2": "2"
}

TASK [debug var={{hostvars[inventory_hostname]}}] ******************************
ok: [host1] => {
    "changed": false, 
    "invocation": {
...
        "var1": "1", 
        "var2": "2"
    }
}</code></pre>

## Actual Results:

<pre><code>TASK [debug var={{item}}] ******************************************************
ok: [host1] => (item=var1) => {
    "item": "var1", 
    "var1": "1"
}
ok: [host1] => (item=var2) => {
    "item": "var2", 
    "var2": "2"
}

TASK [debug var={{hostvars[inventory_hostname]}}] ******************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: unhashable type: 'dict'
fatal: [host1]: FAILED! => {"failed": true, "stdout": ""}</code></pre>

**Comment by bcoca** [comment]
you should not be using moustaches, what is happening is that in 2.0 it is templating item and hostvars BEFORE using vars, if you remove {{ }} this works, var= should not be templated unless the result is the name of a variable

**Comment by bcoca** [comment]
```
  tasks:
    - debug: var=item
      with_items: [ 'var1', 'var2' ]
    - debug: var=hostvars[inventory_hostname]
```

**Comment by bcoca** [comment]
closing as per above
