### ISSUE TITLE
Mesos Marathon Module 

### ISSUE THREAD

**Issue by aabed** [ansible/ansible#13138]
I think it will be nice if I can provision machines on Marathon using ansible 
I don't know if anyone is working on that right now
I'd like to work on such a feature

So if it's welcomed, I am raising a flag that I will be working on it
P.S: I am a beginner and kinda slow, So it will take time to develop such a module

Regards

**Comment by bcoca** [comment]
the mailing list ansible-devel is a more proper place to ask this question, this is for bugs and feature requests.

**Comment by lhoss** [comment]
In the meantime https://github.com/ansible/ansible/pull/34294
Also there's a good alternative module: https://github.com/teralytics/ansible-marathon-module
( disclaimer: released by my employer)
