### ISSUE TITLE
BUG: UnboundLocalError: local variable 'task_action' referenced before assignment

### ISSUE THREAD

**Issue by xjg2010go** [ansible/ansible#13148]
hi: 
   when I use ansible2.0  playbook to test loop nested. It can not run correctly.this is  my test.yml.
- hosts: all
  vars:
    listvar1:
  - 'a'
  - 'b'
  - 'c'
    tasks:
  - shell: echo "nested test a={{ item[0] }} b={{ item[1] }}"
    with_nested:
    - listvar1
    - [ 1, 2, 3 ]
  
  when  I run "ansible-playbook  test.yml" ,it return me:
  An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'task_action' referenced before assignment

when I run ansible 1.9.4.  It can run correctly.no errors. Please Help me.Thanks.

**Comment by jimi-c** [comment]
Hi @xjg2010go, this bug should have been fixed over a week ago, are you using the latest version of ansible from git?

**Comment by xjg2010go** [comment]
thanks, the latest version has no problem. resloved.

**Comment by jimi-c** [comment]
Excellent, thanks for the follow up! Closing this now.
