### ISSUE TITLE
tags not added to tasks included with taggs= option

### ISSUE THREAD

**Issue by cinek810** [ansible/ansible#13154]
Type: Bug report.
Version: 2.0
Environment: Centos 6.6
Summary:
When I execute playbook where tasks are included (the same for tasks included in roles tasks) and the taggs option is added to include statement tasks are not executed through ansible-playbook -t TAG unless each of tasks doesn't have TAG added independently. 
The same tests with previous version (for instance 1.9) of ansible were working properly. 

If someone can point me where should I look around for this issue in code I can volunteer to help.

To reproduce one can use files and commands like below:
My files looks like:

```
[root@localhost test]# cat test.yml 
- hosts: localhost
  tasks: 
  - include: test-inc.yml  taggs=tak
[root@localhost test]# cat test-inc.yml 
- name: test
  debug: var="{{ansible_all_ipv4_addresses}}"
```

I'm testing with:

```
[root@localhost test]# ansible-playbook test.yml  


PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [include taggs=tak] *******************************************************
included: /tmp/test/test-inc.yml for localhost

TASK [test] ********************************************************************
ok: [localhost] => {
    "changed": false, 
    "{{ansible_all_ipv4_addresses}}": [
        "10.3.7.157"
    ]
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   

[root@localhost test]# ansible-playbook -t tak test.yml   
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [include taggs=tak] *******************************************************
included: /tmp/test/test-inc.yml for localhost

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

```

**Comment by sivel** [comment]
It appears as though you have a spelling error.  The correct spelling is `tags` with a single `g`.

**Comment by sivel** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by cinek810** [comment]
I've done a few test, the spelling error is just in issue submission:

<code>
[root@cinek2 test]# cat test.yml 
- hosts: localhost
  tasks: 
  - include: test-inc.yml  tags=tak

[root@cinek2 test]# cat test-inc.yml 
- name: test
  debug: var="{{ansible_all_ipv4_addresses}}"

[root@cinek2 test]# ansible-playbook test.yml 

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [include tags=tak] ********************************************************
included: /tmp/test/test-inc.yml for localhost

TASK [test] ********************************************************************
ok: [localhost] => {
    "changed": false, 
    "{{ansible_all_ipv4_addresses}}": [
        "10.3.7.157"
    ]
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   

[root@cinek2 test]# ansible-playbook -t tak test.yml 
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [include tags=tak] ********************************************************
included: /tmp/test/test-inc.yml for localhost

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

</code>

**Comment by bcoca** [comment]
also that form is deprecated, to pass on tags you should do it as a task directive

```
- hosts: localhost
  tasks: 
  - include: test-inc.yml  
    tags: ['tak']
```

**Comment by cinek810** [comment]
my main problem is that I was using this in roles, ex. in 
front/tasks/main.yml
-include: nginx.yml tags:ngnix
-include: varnish.yml tags:varnish
-include: monitoring.yml tags:monitoring

app/tasks/main.yml
-include: php-cgi.yml tags:php
-include: fpm-monitoring.yml tags:monitoring

and it was very usefull because I was able to (for example) reconfigure just monitoring on whole infrastructure, despite of the servers role with very simple command and I didn't have to add tags: to all tasks in all monitoring.yml 's
