### ISSUE TITLE
tags not added to tasks included with tags= option

### ISSUE THREAD

**Issue by cinek810** [ansible/ansible#13155]
Type: Bug report.
Version: 2.0
Environment: Centos 6.6
Summary:

I'm opening second time, because I made a spelling mistake in previous issue submission, but this is not the main problem. Checked this.

When I execute playbook where tasks are included (the same for tasks included in roles tasks) and the taggs option is added to include statement tasks are not executed through ansible-playbook -t TAG unless each of tasks doesn't have TAG added independently.
The same tests with previous version (for instance 1.9) of ansible were working properly.

If someone can point me where should I look around for this issue in code I can volunteer to help.

To reproduce one can use files and commands like below:
My files looks like:
<code>
[root@cinek2 test]# cat test.yml 
- hosts: localhost
  tasks: 
  - include: test-inc.yml  tags=tak

[root@cinek2 test]# cat test-inc.yml 
- name: test
  debug: var="{{ansible_all_ipv4_addresses}}"

[root@cinek2 test]# ansible-playbook test.yml 

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [include tags=tak] ********************************************************
included: /tmp/test/test-inc.yml for localhost

TASK [test] ********************************************************************
ok: [localhost] => {
    "changed": false, 
    "{{ansible_all_ipv4_addresses}}": [
        "10.3.7.157"
    ]
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   

[root@cinek2 test]# ansible-playbook -t tak test.yml 
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [include tags=tak] ********************************************************
included: /tmp/test/test-inc.yml for localhost

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

</code>

And with ansible 1.9:
<code>
[root@cinek tmp]# cat /tmp/test.yml 
- hosts: localhost
  tasks: 
  - include: test-inc.yml  tags=tak
    [root@cinek tmp]# cat /tmp/test-inc.yml 
- name: test
  debug: var="{{ansible_all_ipv4_addresses}}"

[root@cinek tmp]# ansible-playbook test.yml 

PLAY [localhost] *************************************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [localhost]

TASK: [test] *****************************************************************\* 
ok: [localhost] => {
    "var": {
        "['10.3.7.151']": "['10.3.7.151']"
    }
}

PLAY RECAP *******************************************************************\* 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

[root@cinek tmp]# ansible-playbook -t tak test.yml 

PLAY [localhost] *************************************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [localhost]

TASK: [test] *****************************************************************\* 
ok: [localhost] => {
    "var": {
        "['10.3.7.151']": "['10.3.7.151']"
    }
}

PLAY RECAP *******************************************************************\* 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

</code>

**Comment by jimi-c** [comment]
@cinek810 this was resolved, are you using the latest version of devel?

**Comment by cinek810** [comment]
no I'm using 2.0-beta2 from tarball. How can I find appropriate commit ? I'd prefer changing only this part instead of going to devel branch to verify it's fixed.

**Comment by cinek810** [comment]
I've checked with beta3 version and  can confirm that it's solved solved.
