### ISSUE TITLE
ini_file module does not create destination file

### ISSUE THREAD

**Issue by theraser** [ansible/ansible#13158]
Issue Type: Bug Report
Ansible Version: ansible-playbook 2.0.0 (devel 5d645f3a8b) last updated 2015/11/13 13:27:13 (GMT +200)
Environment: Ubuntu 15.04
Summary: ini_file does not create the destination file when it does not exist
Steps to reproduce:

``` yaml
- name: set test configuration
  ini_file: 
    dest=/etc/foobar.conf   
    section="test"
    option="key1"
    value="value1"
    state=present
```

Expected Result: _/etc/foobar.conf_ should be created as it does not exist
Actual Result:

``` yaml
TASK [test : set test configuration] *************************************
fatal: [an.onymo.us]: FAILED! => {"changed": false, "failed": true, "msg": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1447425334.23-78870519539583/ini_file\", line 2128, in <module>\r\n    main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1447425334.23-78870519539583/ini_file\", line 211, in main\r\n    changed = do_ini(module, dest, section, option, value, state, backup)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1447425334.23-78870519539583/ini_file\", line 108, in do_ini\r\n    ini_file = open(filename, 'r')\r\nIOError: [Errno 2] No such file or directory: '/etc/foobar.conf'\r\n", "parsed": false}
```

Using Ansible 1.9.4 the destination file gets created, just as expected

**Comment by theraser** [comment]
To add some additional information: This bug seems to be introduced with [7f59773460d79b3dae34c375ba68caea1bfc09a8](https://github.com/ansible/ansible-modules-core/commit/7f59773460d79b3dae34c375ba68caea1bfc09a8). Using older version [3993f4e9674ad3d325aed1c3ca43f5e2f81c9b9c](https://github.com/ansible/ansible-modules-core/commit/3993f4e9674ad3d325aed1c3ca43f5e2f81c9b9c) everything works as expected

**Comment by chrrrles** [comment]
Closing as fixed.
