### ISSUE TITLE
Issue when using ":" for key:value custom facts, no consistency on the results

### ISSUE THREAD

**Issue by nicolas-g** [ansible/ansible#13163]
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.4
##### Environment:

Controller OSX 10.10.5
Targe nodes CentOS 6.6
##### Summary:

Using ":" as a key:value format in /etc/ansible/facts/\* it seems the behavior varies, sometimes omitting one of the values and displaying only the first one while other times if I have only 1 line using ":" and the others are without then it's displaying the output accurate .
##### Steps To Reproduce:

Different examples bellow : 
###### 1

```
[tags]
role:db
role:slave
```

```
success >> {
    "ansible_facts": {
        "ansible_local": {
            "monitoring": {
                "tags": {
                    "role": "slave"
                }
            },
```
###### 2

```
[tags]
role:db=
role:slave=
```

```
success >> {
    "ansible_facts": {
        "ansible_local": {
            "monitoring": {
                "tags": {
                    "role": "slave="
                }
            },
```
###### 3

```
[tags]
role:db=
slave=
```

```
success >> {
    "ansible_facts": {
        "ansible_local": {
            "monitoring": {
                "tags": {
                    "role": "db=",
                    "slave": ""
                }
            },
```
###### 4

```
[tags]
role:db=
role:slave=
```

```
success >> {
    "ansible_facts": {
        "ansible_local": {
            "monitoring": {
                "tags": {
                    "role": "slave="
                }
            },
```
###### 5

```
[tags]
role:db
role:slave
```

```
success >> {
    "ansible_facts": {
        "ansible_local": {
            "monitoring": {
                "tags": {
                    "role": "slave"
                }
            },
```
##### Expected Results:

```
[tags]
role:db
role:slave
```

```
success >> {
    "ansible_facts": {
        "ansible_local": {
            "monitoring": {
                "tags": {
                    "role": "db",
                    "role": "slave"
                }
            },
```
##### Actual Results:

See steps To Reproduce section.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

So you have 2 keys at the same level 'role' which is mostly invalid, the JSON spec allows this but does not specify what to do, but most parsers drop one of the keys, a few create a list and assign it to the keys. In this case the Python JSON parser is just overwriting the duplicates and using the last one found. 

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
