### ISSUE TITLE
2.0 not reading vars for host in multiple inventory sources

### ISSUE THREAD

**Issue by leucos** [ansible/ansible#13187]
It seems that ansible 2.0 as of 07b588f6c0 does not support multiple inventory files in
the same directory, like it did before.

```
$ grep elastic1 inventories/devel/*
inventories/devel/generated:elastic1 from_generated="yes"
inventories/devel/hosts:elastic1 from_hosts="yes"
```

So here we have two inventory files (named `generated` and `hosts`). In
each file, we define a variable for the host `elastic1` (respectively
`from_generated` and `from_hosts`) and set is to the string "yes".

With 1.9.4, all is fine:

```
$ ansible --version
ansible 1.9.4
configured module search path = None
$ ansible elastic1 -i inventories/devel/ -m debug -a
'msg="{{from_generated}} {{from_hosts}}"'
elastic1 | success >> {
    "msg": "yes yes"
}
```

Now ansible 2.0b3:

```
$ ansible --version
ansible 2.0.0 (detached HEAD 07b588f6c0) last updated 2015/11/16
20:52:36 (GMT +200)
$ ansible elastic1 -i inventories/devel/ -m debug -a
'msg="{{from_generated}} {{from_hosts}}"'
elastic1 | FAILED! => {
    "failed": true,
    "msg": "ERROR! 'from_hosts' is undefined"
}
$ ansible elastic1 -i inventories/devel/ -m debug -a
'msg="{{from_generated}}"'
elastic1 | SUCCESS => {
    "changed": false,
    "msg": "yes"
}
```

If I rename `generated` to `zippy`:

```
$ mv inventories/devel/generated inventories/devel/zippy
$ ansible elastic1 -i inventories/devel/ -m debug -a
'msg="{{from_generated}}"'
elastic1 | FAILED! => {
    "failed": true,
    "msg": "ERROR! 'from_generated' is undefined"
}
$ ansible elastic1 -i inventories/devel/ -m debug -a 'msg="{{from_hosts}}"'
elastic1 | SUCCESS => {
    "changed": false,
    "msg": "yes"
}
```

So it seems Ansible now reads inventory from the first file found (sorted
alpha) and stops here.

**Comment by bcoca** [comment]
i tested and ansible reads the multiple files (tested the host list and found hosts only in file1, file2 and in common). So this seems to be an issue with the caching working 'too well' and not loading the extra vars of a repeat host.

**Comment by itldo** [comment]
This is related to #13081 (Strange inventory behavior with inventory directory).

I dug into this yesterday in a crash course on ansible variables and inventories with the following observations.

There are two competing mechanisms for looking up host variables:
- one is based on Inventory.get_host_variables, which will recognize variables from 'dir' and 'script' (dynamic) inventories, but not necessarily an 'ini' static inventory. Vars for Hosts read from dynamic inventories can get populated this way. Also, this is used to 'get_magic_variables' as part of setting up a Task's variable collection, but only dumps them under the special 'vars' variable.
  In short, a Task's top level variables obtained from a static inventory might be missing some host variables, but special variable vars.XXX that includes dynamic inventories will actually have them.
- another is based on Host.vars, which depends on which instance of a host from multiple inventories that you happen to lookup. 'ini' static inventories will each create their own instance of a Host and advertise it to Groups that they know about. If an inventory mentions only the Host without providing variables, then you get a Host with nothing but magic variables. Host variables don't get merged out of a static inventory. In this case the Host you find is the "last" Host found after ansible searches through a bunch of groups. So it depends on what groups exist and which is considered "last" during a selection of Hosts based on groups and implementation sorting order. I imagine that adding a group in one inventory and not the other, can indirectly change which set of  variables that you access for a Host. You may suddenly end up with an instance of the Host that was cached for different Inventory, if that group suddenly becomes the "last" Group. I haven't had time yet, but may try to test that scenario. I think it was happening to me.

Based on the above observations and the lack of an example in the documentation, I am assuming that _the same Host cannot be mentioned explicitly in multiple inventories_. I would like ansible behavior to be defined to permit this if it was not intended in the first place.

[Static Groups of Dynamic Groups](http://docs.ansible.com/ansible/intro_dynamic_inventory.html#id9) does provide and example of sharing the same Group among inventories.
So one workaround might be to turn all hosts into groups containing a single host, and then reference only Groups among inventories. Blech.

**Comment by itldo** [comment]
I can't image that the current behavior for Inventory Host variables was ever really defined.

Can we define what the official behavior should be?
For example, which of these should be true?
- Host variables defined in different inventories will be merged according to {{ some precedence rules }}.
- Host variables defined in different inventories will be merged with conflicts resulting in an {{ error , warning, undefined manner }}.
- Hosts may be mentioned in multiple inventories, but may have variables defined in at most one inventory.
- Dynamic Groups may be children of Static Groups.

**Comment by bitmensch** [comment]
+1 for getting this specified more accurately and allowing multiple inventories (may it be static or dynamic ones) to be merged

**Comment by bitmensch** [comment]
Could someone of the core developers comment on this one? I would consider this a major issue (P1) when running a playbook + inventory in production with undefined behavior.

So, are there any plans to get this specified (so it is not undefined behavior anymore) and/or opinions regarding backwards-compatibility?

**Comment by jimi-c** [comment]
Hi all, this appears to have been the same bug as #13397, which was fixed by f467f1770f8885b657fa01270b6f2909249d1f93. Testing the above example on the devel or stable-2.0 branches show it's working as expected:

<pre>
# ansible --version
ansible 2.1.0 (devel f467f1770f) last updated 2015/12/03 15:26:46 (GMT -400)
  lib/ansible/modules/core: (detached HEAD cd9a7667aa) last updated 2015/12/03 14:45:56 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 3c4f954f0f) last updated 2015/12/03 14:45:56 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
# ansible elastic1 -i inventories/ -m debug -a 'msg="{{from_generated}} {{from_hosts}}"'
elastic1 | SUCCESS => {
    "changed": false, 
    "msg": "yes yes"
}
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment]
And, just for completeness, here's the output from stable-2.0:

<pre>
# ansible --version
ansible 2.0.0 (stable-2.0 6aa1b6d9b1) last updated 2015/12/03 15:27:10 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 273112c56d) last updated 2015/12/03 16:06:02 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD e46e2e1d6f) last updated 2015/12/03 16:06:02 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
# ansible elastic1 -i inventories/ -m debug -a 'msg="{{from_generated}} {{from_hosts}}"'
elastic1 | SUCCESS => {
    "changed": false, 
    "msg": "yes yes"
}
</pre>

**Comment by dejlek** [comment]
I also use directories as inventories (for different environments - production, staging, test, etc), and I am hitting the same bug with Ansible 2.3.1.0 complaining with errors like this one: `ERROR! no host vars as host is not in inventory: production-parservice-c1` ... It all works with Ansible 2.2.1.0 so I have no choice but to continue using this version...
