### ISSUE TITLE
copy module resolves paths relative to project root directory instead of role root.

### ISSUE THREAD

**Issue by derekmahar** [ansible/ansible#13198]
In Ansible 2.0.0 on the devel branch, the copy module fails to resolve paths relative to the role base.  Instead, it resolves them relative to the top-level project base.

For example, the following `copy` task in role `application` looks for directory `certificates` in `/home/dmahar/Projects/deployer` instead of `/home/dmahar/Projects/deployer/roles/application/certificates` or `/home/dmahar/Projects/deployer/roles/application/files/certificates`:

```
- name: Deploy application certificates
  copy: src=certificates/{{ application_name }}/ dest={{ application_resource_directory_root }}/{{ application_name }}/certificates owner={{ application_owner }} group={{ application_group }}
```

```
TASK [application : Deploy application certificates] ***************************
fatal: [192.168.11.122]: FAILED! => {"changed": false, "failed": true, "msg": "could not find src=/home/derek/Projects/deployer/certificates/ice-web"}
```

Should `copy` search for files relative to "roles/application/files" or "roles/application"?

**Comment by bcoca** [comment]
it should look in several locations in order, the one in the error seems to be the last one tried.

**Comment by derekmahar** [comment]
This is my bad.  Source of the problem is that **none** of the following paths exist for application **ice-web** (since it doesn't have any certificates):

```
/home/derek/Projects/deployer/certificates/ice-web
/home/derek/Projects/deployer/roles/application/certificates/ice-web
/home/derek/Projects/deployer/roles/application/files/certificates/ice-web
```

However, similar paths do exist for application **fatca-web** (it has certificates), but the script fails before it reaches this application.

Shouldn't `copy` just ignore source paths that don't exist?

**Comment by derekmahar** [comment]
I fixed the problem by changing both the `copy` task and the directory structure for role `application`:

```
- name: Deploy application resources
  copy: src={{ application_name }}/ dest={{ application_resource_directory_root }}/{{ application_name }} owner={{ application_owner }} group={{ application_group }}
```

```
roles/application/files/ice-web
roles/application/files/fatca-web
roles/application/files/fatca-web/certificates
```

```
TASK [application : Deploy application resources] ******************************
ok: [192.168.11.122]
```

Target directories:

```
/etc/opes/fatca-web
/etc/opes/fatca-web/certificates
/etc/opes/ice-web
```

**Comment by derekmahar** [comment]
I closed this issue, but I still think that `copy`, like `files`, should ignore paths that don't exist, or at least do so optionally.

**Comment by firecat53** [comment]
I think this should be re-opened for fixing (unless I'm misunderstanding something). In 1.9x, the copy module would correctly search (as implied in the 'Best Practices' document) and find files in the roles/\<role name\>/files/ directory. With 2.0, an absolute path to the files/ directory within the role has to be specified.

For example, the following play worked fine until upgrading:

    - name: configure fail2ban for sshd
      copy:
        src: etc/fail2ban/jail.local
        dest: /etc/fail2ban/jail.local
        mode: 0644

Where the jail.local file is in \<root\>/roles/common/files/etc/fail2ban/jail.local, the task is in \<root\>/roles/common/tasks/main.yml and the playbook is \<root\>/provision.yml.

Thanks,
Scott
