### ISSUE TITLE
Documentation compilation fails for latest Ansible

### ISSUE THREAD

**Issue by safiyat** [ansible/ansible#13195]
I tried compiling the ansible doc on readthedocs.org [here](https://readthedocs.org/projects/ansible/builds/3486695/), but encountered an error saying:
`IOError: [Errno 2] No such file or directory: u'/home/docs/checkouts/readthedocs.org/user_builds/ansible/checkouts/stable/docsite/_build/doctrees-readthedocs/index.doctree'`

I filed an [issue](https://github.com/sphinx-doc/sphinx/issues/2119) with [sphinx](https://github.com/sphinx-doc/sphinx) but they said its a misconfiguration in the ansible doc directory.

Many builds prior to this one too have failed. Look [here](https://readthedocs.org/projects/ansible/builds/).

Please check and fix.

**Comment by bcoca** [comment]
I cannot reproduce the problem and docs currently are building correctly.

Note that doc builds break frequently as they include  new modules/docs updates, we don't test it pre merge as it is a lot of noise, we do get notified internally and fix the docs builds ourselves. Also the docs don't get published automatically so this is not a problem for the docsite.
