### ISSUE TITLE
ec2_find_ami module not included in 1.9.4 release

### ISSUE THREAD

**Issue by littlemove** [ansible/ansible#13196]
##### Issue Type:
- Bug Report
##### Ansible Version:

1.9.4
##### Ansible Configuration:

N/A
##### Environment:

Running on OSX El Capitan. Installed via homebrew.
##### Summary:

The release found in https://releases.ansible.com/ansible/ansible-1.9.4.tar.gz does not include the core module ec2_find_ami
##### Steps To Reproduce:
1. Get `https://releases.ansible.com/ansible/ansible-1.9.4.tar.gz`
2. Uncompress and go to `ansible-1.9.4/lib/ansible/modules/core/cloud/amazon`
##### Expected Results:

ec2_ami_find.py should be present.
##### Actual Results:

Found the _old(?)_ version ec2_ami_search.py

**Comment by bcoca** [comment]
And I would not expect it to, as stated in http://docs.ansible.com/ansible/ec2_ami_find_module.html
it is a new module in 2.0

**Comment by littlemove** [comment]
Short answer:
Oh, you're absolutely right @bcoca. Sorry for the inconvenience and thanks for answering.

BTW it seems to work on 1.9.4 anyway.

**Comment by bcoca** [comment]
most new modules can just be copied and will work, they are designed to be mostly self contained small scripts.
