### ISSUE TITLE
modules try to include json, fail on hosts with simplejson

### ISSUE THREAD

**Issue by tronicum** [ansible/ansible#13231]
type: Bug Report
ansible version: git latest as of today
environment: ansible host: debian 7.9, ansible clients: centos 5 and 6
summary: some modules (like the puppet module) try to include json. clients (like centos 5) which have simplejson install fail. some module have a nice try/except for json or simplejson.

i could use the try/except and fix the other modules if you want and provide a pull request. my actuall problem wont work if i move from json to simplejson but that is probably an other issue.

**Comment by bcoca** [comment]
modules should not be including json as module_utils/basic.py already does the simplejson/json thing to get the correct one as 'json'.

I fixed the puppet module, i'll do a quick search for others, in the future please open a ticket in the appropriate module repo against the specific module so we can fix it.

**Comment by tronicum** [comment]
i made a pull request https://github.com/ansible/ansible-modules-extras/pull/1284 to remove all the json imports from modules.
