### ISSUE TITLE
pip module: passing --use-mirrors breaks in debian squeeze

### ISSUE THREAD

**Issue by briceburg** [ansible/ansible#1325]
The vanilla/stock version of python-virtualenv does not support the --use-mirrors argument, causing the pip module to fail with;

" install: error: no such option: --use-mirrors"  

when e.g. trying to install from a requirements.txt file via something like;

```
pip requirements=$application_dir/requirements.txt virtualenv=$virtualenv_dir
```

Debian Squeeze bundles;

python: 2.6.6  (via python pkg)
pip: 0.7.2 (via python-pip pkg)
virtualenv: 1.4.9  (via python-virtualenv pkg) ; **\* and should use --no-site-packages  when installing the virtual environment ***

Is it possible to drop the --use-mirrors or to detect virtualenv+pip versions accordingly??

**Comment by mpdehaan** [comment]
Hmm.   I'll accept patches.  I have no resources to work on this, nor do I use it.  I would suspect it would be reasonably easy to detect if it were available as an option or even try/except it somehow.

@mattupstate wrote this orginally and might be interested in fixing if you are not.

**Comment by mpdehaan** [comment]
workaround would be to just execute pip with the command module and specify a "creates=" to a file that it would install, and you can pass whatever flags you need.

should get you unstuck.   anyway, the above should ping Matt.

**Comment by mattupstate** [comment]
@briceburg Is upgrading pip not an option? That version of pip is grossly outdated. Otherwise I would use the command module as @mpdehaan said.

**Comment by briceburg** [comment]
@mattupstate  I'm sure pip will be updated in the next version of Debian. Current Debian stable (6.0) rolls the above mentioned version. They're slow to update as always, but definitely my preferred server distribution. Every once in awhile I'll use a backport... but prefer to run a stock version to keep security+updates as simple as possible.

Will go with the command line. Is there any real necessary reason for the --use-mirrors flag? Personally I'd want to explicitly call this as I trust PyPy sources over a potentially hacked mirror.

**Comment by mpdehaan** [comment]
Brice,

Easiest thing for you might be to change the source of the module to not
pass the flag.

We use mirrors for all of our other package stuff every day, so I'm not
sure I would treat PyPy differently.

--Michael

**Comment by mattupstate** [comment]
Going to agree with @mpdehaan here. --use-mirrors is mostly a safety net for all too common HTTP errors.
