### ISSUE TITLE
consider dropping the 'force' option on the file module

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1326]
The idea of converting files to links to directories and so forth is a bit sketchy, and conflicts with some of the underlying things I need to do to support fileglob.

I think it can go, but make sure.   And remove it if it can.

**Comment by mpdehaan** [comment]
yep, lots of issues with force.  It goes.   Willing to accept patches to re-add if they don't break with_fileglob and so on.

**Comment by chris-gilmore** [comment]
The changelog for 0.8 still has this line in it:
added force=yes|no (default no) option for file module, which allows transition between files to directories and so on
