### ISSUE TITLE
Using Ansible with Docker

### ISSUE THREAD

**Issue by westover** [ansible/ansible#13275]
I am using Docker to execute my playbook as part of my Dockerfile. But I have noticed that I get no incremental output from Ansible. This is presenting with Ansible 1.9.4 and Docker 1.9.2 With the length of time it takes for my playbook to run as it is responsible for full provisioning on a fresh container it would be nice to see more incremental output. The interesting thing is that this doesn't seem to be intrinsic to Docker as unquieted apt-get seems to stream by in nearly real time. But I get no Ansible output until the step is over.

**Comment by bitmensch** [comment]
To see incremental output when ansible is getting called as a subprocess you need to make sure environment variable `PYTHONUNBUFFERED` is set, e.g. `PYTHONUNBUFFERED=1`.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
