### ISSUE TITLE
skippy callback module - object has no attribute 'v2_playbook_item_on_skipped'

### ISSUE THREAD

**Issue by johnarnold** [ansible/ansible#13282]
VERSION:

Running from source, git pull and submodule update as of this morning.

johnar@acs-trusty8:~/NetworkManagement/acs/ansible$ sudo ~/ansible/bin/ansible --version
ansible 2.0.0 (devel 70de8bc96f) last updated 2015/11/24 18:28:34 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 0e043f8c58) last updated 2015/11/24 18:29:11 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD e46e2e1d6f) last updated 2015/11/24 18:29:11 (GMT +000)
  config file = /home/johnar/NetworkManagement/acs/ansible/ansible.cfg
  configured module search path = library:library/ixia

ERROR:

 [WARNING]: Error when using <bound method CallbackModule.v2_runner_on_ok of
</home/johnar/ansible/lib/ansible/plugins/callback/skippy.CallbackModule object at 0x7f0d02d05310>>: 'CallbackModule' object has no attribute
'v2_playbook_item_on_skipped'

I checked skippy.py, there is definitely no v2_playbook_item_on_skipped in there.

**Comment by bcoca** [comment]
fixed via 0ec60ac09b86e434523fdfde929efa98c456fc8a

the base class should have all events and not require derived plugins to implement them all unless they want to.
