### ISSUE TITLE
Introduce ansible_docker_host parameter for connection=docker

### ISSUE THREAD

**Issue by ThomasSteinbach** [ansible/ansible#13294]
The [Docker Command Line Reference](http://docs.docker.com/engine/reference/commandline/cli/) lists a parameter `-H` or `--host`:

```
-H, --host=[]: The socket(s) to talk to the Docker daemon in the format of tcp://host:port/path, unix:///path/to/socket, fd://* or fd://socketfd.
```

This parameter should be accepted by the new Docker connection, introduced in Ansible 2.0. Here two examples of possible usage within the inventory:

```
mycontainer ansible_connection=docker ansible_docker_host="tcp://host:port/path"
```

... and within a playbook:

```
- name: do something
  hosts: containerxyz
  connection: docker
  docker_host: "tcp://host:port/path"
  ...
```

( Label feature_idea )

**Comment by bitmensch** [comment]
@ThomasSteinbach Not sure if you are aware of, but you can already set the docker host via environment variable `DOCKER_HOST` prior to calling `ansible-playbook` (although this is global and not per inventory host). But probably it is sufficient for your use case.

**Comment by bcoca** [comment]
@benjixx great workaround, but we should really add connection variables to allow for hosts/groups to target different container hosts.

**Comment by bitmensch** [comment]
@bcoca I agree. There could be use cases for that where you want to run multiple independent docker hosts which are not connected via something like `docker-swarm`.

**Comment by ThomasSteinbach** [comment]
@benjixx Thank you for your hint. In fact it takes more than just setting the docker host. My upper description was not very complete as you have to tell Docker where to find necessary keys and certificates for authentication.

I created an (example) code change with which you can use the docker connection plugin in the following manner:

```
- name: do something
  hosts: containerxyz
  connection: docker
  connections_args: "--tlsverify --tlscacert=/path/to/ca.pem --tlscert=/path/to/client-cert.pem --tlskey=/path/to/client-key.pem -H=tcp://myserver.org:4243"
```

It is awesome to see how you can start a docker container and deploy its configuration inside with Ansible - both on a remote server. With the direct Docker deployment you can avoid file/folder volume mounts (e.g for config files under /etc) and deploy them directly into the data volume container.

**Comment by bcoca** [comment]
I would make these new options align with existing connection vars, though we might need to create new ones for the cacert

**Comment by ThomasSteinbach** [comment]
@bcoca Is there anything I should do? I did not get that from your answer.

**Comment by ThomasSteinbach** [comment]
The issue is solved as with the merge of the related pull request. But before closing this issue I would like to know if there is a documentation of the docker connector I can update? I haven't found one yet.

Btw, remote connection parameters and others for could be passed via `ansible_docker_extra_args`

**Comment by abadger** [comment]
we should probably add the documentation to: https://github.com/ansible/ansible/blob/devel/docsite/rst/intro_inventory.rst   We don't currently have a page dedicated to connection plugins.  Might be a good things to have but someone would have to start writing it.

**Comment by ThomasSteinbach** [comment]
I started a subsection describing the non ssh based connection types, the new Docker connection parameter from this issue included:

https://github.com/ansible/ansible/pull/15155
