### ISSUE TITLE
acl module changed behavior (default acl also adds user acl)

### ISSUE THREAD

**Issue by hloeffler** [ansible/ansible#13291]
Type: Bug

in ansible 2.0 the acl module wants to be smarter than me:

if i use:

```
 - acl: name=/testdir etype=user entity=test permissions="r" default=yes state=present
```

it also adds the acl "user:test:r--"

in 1.9.4 it only adds a new default acl

**Comment by chrrrles** [comment]
CC'ing @astorije @bcoca

**Comment by jimi-c** [comment]
If I had to guess, this would be related to e95bcaeb8a98ec280acccadbb5491efc0c1679af on that repo.

Since this is module related, could you please reopen this on ansible/ansible-modules-core?

Thanks!

**Comment by hloeffler** [comment]
done:
https://github.com/ansible/ansible-modules-core/issues/2598

could you please tag it for v2 over there

**Comment by jimi-c** [comment]
Done as well.

**Comment by hloeffler** [comment]
reopen in "ansible/ansible-modules-core" ?
this is v2 prio because it breaks playbooks
