### ISSUE TITLE
Bug Report: with_fileglob skips when condition

### ISSUE THREAD

**Issue by OnlyLoveOleg** [ansible/ansible#13296]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0 (stable-2.0 1e968d34cb) last updated 2015/11/19 21:38:04 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 64147ab795) last updated 2015/11/19 21:38:20 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 1a0ff8a8c8) last updated 2015/11/19 21:38:21 (GMT +000)
##### Ansible Configuration:

pretty basic just the following edited:

```
display_skipped_hosts = True
...
[accelerate]
accelerate_port = 5099
accelerate_timeout = 30
accelerate_connect_timeout = 5.0
accelerate_daemon_timeout = 30
...
vault_password_file = /path/to/my/file
```
##### Environment:

Management:

```
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
```

remote:

```
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"

or

RHEL 6
```
##### Summary:

When using with_fileglob and condition in a task for example to copy files to remote using the template module the condition seems to be skipped or with_fileglob kicks before even the the condition is false.
##### Steps To Reproduce:

if the variable sudoers_d not defined the tasks seems to fail

```
- name: Copy sudoers.d files to remote
  template:
   src={{item}}
   dest=/etc/sudoers.d/{{ item | basename }}
   validate='visudo -cf %s'
   owner=root group=root mode=0440
  when: sudoers_d is defined
  with_fileglob:
   - "{{ sudoers_d }}/*"
```
##### Expected Results:

expecting the task evaluate the when condition first and skip on undefined variable.
##### Actual Results:

```
TASK [sudo : Copy sudoers.d files to remote] ***********************************
fatal: [somehost01.example.org]: FAILED! => {"failed": true, "msg": "ERROR! 'sudoers_d' is undefined"}
```

**Comment by bcoca** [comment]
This is not a bug, all with clauses get executed BEFORE the when: as the when: can include 'item' to make each iteration of the loop conditional.

To avoid undefined errors:

```
- name: Copy sudoers.d files to remote
  template:
   src={{item}}
   dest=/etc/sudoers.d/{{ item | basename }}
   validate='visudo -cf %s'
   owner=root group=root mode=0440
  with_fileglob:
   - "{{ sudoers_d|default('/nonexistant') }}/*"
```

**Comment by OnlyLoveOleg** [comment]
bcoca,

Thanks for checking the report and great advice.

Cheers,
Tal
