### ISSUE TITLE
bundle module + argsfile in one tarball and chain exec_commands with &

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#133]
We can transfer just one file with SFTP and also can chmod + run in one step, vastly reducing the number of paramiko ops we perform.

In doing so, we can also used a "fixed" tmpdir path, something like

~/.ansible/username_hostname/

That we do NOT clean up, to remove the need to rm -rf the tempdir.

We must have the "copy" and "template" module auto cleanup the src file if it decides to replace a file, however, to save disk space.

This should improve speed for operations by 3-4x

(Assigning to mgw since it's his idea and he wanted to do it)

**Comment by mpdehaan** [comment]
may be worth seeing if python libraries for working with tarfiles are faster than the system call, can happen later though

**Comment by mpdehaan** [comment]
mgw, are you actively working on this one?  If not, I may wish to tackle it soon (like this weekend).   Let me know!

**Comment by mpdehaan** [comment]
closing this, I'll still review a pull request for it but it's not on the must-have features list...

**Comment by mgwilliams** [comment]
Yes, I'm working on it... I was away since Wednesday, so a bit backed up.

On Mon, Apr 16, 2012 at 11:21 PM, Michael DeHaan
reply@reply.github.com
wrote:
