### ISSUE TITLE
Vault Password File is not working with a playbook

### ISSUE THREAD

**Issue by ddavison** [ansible/ansible#13304]
**Issue Type**
Bug Report

**Ansible Version**

``` bash
$ ansible --version
ansible 1.9.2
  configured module search path = None
```

**Ansible Configuration**
changed `remote_tmp` to

``` ini
remote_tmp = /tmp
```

**Environment**

``` sh
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10
DISTRIB_CODENAME=wily
DISTRIB_DESCRIPTION="Ubuntu 15.10"
```

**Summary**
Running a playbook with the `--vault-password-file` flag does not work.

**Steps to reproduce**
_~/.vaultpw_
`plaintextpassword`

Run a playbook with the vault password file:

``` sh
ansible-playbook playbook.yml --vault-password-file ~/.vaultpw
```

_(same format as described in the [vault docs](http://docs.ansible.com/ansible/playbooks_vault.html))_

**Expected Results**
The playbook runs with the vault password, non-interactive.

**Actual Results**
Console outputs:

``` sh
ERROR: problem running / h o m e / u b u n t u / . v a u l t p w ([Errno 8] Exec format error)
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case it seems the file has executable permissions set and ansible is trying to execute a script that retrieves the password instead of just reading the file, try `chmod a-x ~/.vaultpw`.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by sivel** [comment]
What are the permissions of that file?  It sounds like that file is executable, and therefore Ansible is trying to execute it as a script that will produce the output instead of just reading the file.

**Comment by ddavison** [comment]
The permissions were `0700`.. changed it to `0600` and that definitely appeared to work :)  Thanks so much! and sorry about that.

**Comment by gabrielgiordan** [comment]
Hey guys, I've tried everything to make it work on Windows, chmod, changing properties, creating the file on Ubuntu and then putting on Windows, but I just can't remove the executable bit from the .vault_pass file, any solution on this for Windows hosts?

`ERROR! Problem running vault password script / m n t / c / v m / v p s - 3 g b - c o r r e t o r a / t r e l l i s / v a u l t / . v a u l t _ p a s s ([Errno 8] Exec format error). If this is not a script, remove the executable bit from the file.`

**Comment by daBONDi** [comment]
@gabrielgiordan you need to adduse the Mount point permission in your vagrant file


Like this one:
```
      vm_config.vm.synced_folder "./ansible", "/opt/it-infra", id: "it-infra", owner: "vagrant", group: "vagrant", mount_options: ["dmode=775,fmode=664"]
```

**Comment by sushrut-desora** [comment]
@gabrielgiordan Your problem might be related to this question https://github.com/Microsoft/WSL/issues/81
I changed the file permissions by using the file properties on windows
file(right-click) > Properties > Security > Advanced > (Select User) > Edit > Show advanced permission >  Uncheck execute file

**Comment by C0missar** [comment]
Got the unmount to work once I moved out of /mnt/c to /.  But the mount doesn't work, giving an error (Ubuntu 18.04, Windows 10 version 1709 build 16299.726)

$ sudo umount /mnt/c
$ sudo mount -t drvfs C: /mnt/c -o metadata
mount: /mnt/c: wrong fs type, bad option, bad superblock on C:, missing codepage or helper program, or other error.

$ mount -l
rootfs on / type lxfs (rw,noatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,noatime)
