### ISSUE TITLE
User module documentation lists false requirements

### ISSUE THREAD

**Issue by 36roentgen** [ansible/ansible#13305]
http://docs.ansible.com/ansible/user_module.html

lists:
- useradd
- userdel
- usermod

as requirements, however the users modules work on BSD's and perhaps other platforms which don't have those utilities.

**Comment by bcoca** [comment]
yep, that is outdated as the initial implementation was linux only, when we expanded the platforms supported we should have updated the requirements.

**Comment by timani** [comment]
Is there somewhere to find the current requirements? I can submit a PR with the changes.

**Comment by bcoca** [comment]
fixed by #20229
