### ISSUE TITLE
Unable to use jinja2 templates in tasks/main.yml is it possible?

### ISSUE THREAD

**Issue by svetlyak40wt** [ansible/ansible#13314]
Hi! I'm trying to implement firewall rules management with `ufw` module. Idea is to have list of ports to be accessable from sources somewhere in host variables. For example, I have this in my `group_vars/consul_servers`:

```
ufw_open_docker_from_sources:
  - {port: 8500, src: consul_agents}
  - {port: 8301, src: consul_agents}
```

Where `consul_agents` is a group name.

And I have a `firewall/main.yml` in my `rules`, where I'm trying to expand this list of ports and groups into some tasks:

```
{% for item in hostvars['ufw_open_docker_from_sources'] %}
{% for host in groups[item.src] %}
- name: Enable access to some docker ports from particular source
  ufw:
    insert=1
    route=yes
    rule=allow
    port={{ item.port }}
    src={{ hostvars[host]['ip'] }}
{% endfor %}
{% endfor %}
```

But this does not work because of error:

```
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/Users/art/projects/ansible/with-roles/roles/firewall/tasks/main.yml': line 25, column 2, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


{% for item in hostvars['ufw_open_docker_from_sources'] %}
 ^ here
```

Is it possible to overcome this limitation?

**Comment by sivel** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by svetlyak40wt** [comment]
Thank you @sivel, I wrote to the mail list.
