### ISSUE TITLE
Add support for AWS Security Token Service

### ISSUE THREAD

**Issue by droxer** [ansible/ansible#13316]
AWS Security Token Service is really important feature, I am thinking its worth to have it in Ansible v1.9. 

I created [PR](https://github.com/ansible/ansible-modules-core/pull/2557) on [ansible-modules-core](https://github.com/ansible/ansible-modules-core).

**Comment by abadger** [comment]
Closing as the pulll request https://github.com/ansible/ansible-modules-core/pull/2421 is sufficient to track this.
