### ISSUE TITLE
awx.main.commands.run_socketio_service Invalid connect path received: index.html

### ISSUE THREAD

**Issue by playgroundctl** [ansible/ansible#13335]
hi guys,

i installed the Ansible Tower app.
and i realized that it runs on port 8080 using HTTPS.
i am very sorry about asking the following but couldn't find it in the documentation:

what is the exact URL that Tower is listening to ?
now am using https://nl-ams02c-ispctl01.SNIP!:8080
and am getting a blank page saying "Tower version 2.4.1"
and the logs are saying :
`@nl-ams02c-ispctl01 tower]# 2015-11-27 04:04:01,011 WARNING  awx.main.commands.run_socketio_service Invalid connect path received: index.html`

does it happen to have any idea what might be cause ?

**Comment by sivel** [comment]
For tower support please see https://support.ansible.com
