### ISSUE TITLE
become fail if used on windows target - v2.0.0-0.6.rc1

### ISSUE THREAD

**Issue by juju4** [ansible/ansible#13331]
If using a multiplatform role which has 'become: yes' statement, role fails if executed on windows as it tries to call /bin/sh and sudo.
It probably should be ignored on Windows.

```
TASK [setup] *******************************************************************
fatal: [192.168.2.109]: FAILED! => {"changed": false, "failed": true, "msg": "#< CLIXML\r\n<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><Obj S=\"progress\" RefId=\"0\"><TN RefId=\"0\"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N=\"SourceId\">1</I64><PR N=\"Record\"><AV>Préparation des modules à la première utilisation.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S=\"progress\" RefId=\"1\"><TNRef RefId=\"0\" /><MS><I64 N=\"SourceId\">1</I64><PR N=\"Record\"><AV>Préparation des modules à la première utilisation.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><S S=\"Error\">/bin/sh : Le terme «/bin/sh» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou _x000D__x000A_</S><S S=\"Error\">programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès _x000D__x000A_</S><S S=\"Error\">est correct et réessayez._x000D__x000A_</S><S S=\"Error\">Au caractère Ligne:1 : 1_x000D__x000A_</S><S S=\"Error\">+ /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '\"'\"'echo BECOME-SUCCESS ..._x000D__x000A_</S><S S=\"Error\">+ ~~~~~~~_x000D__x000A_</S><S S=\"Error\">    + CategoryInfo          : ObjectNotFound: (/bin/sh:String) [], CommandNotFoundException_x000D__x000A_</S><S S=\"Error\">    + FullyQualifiedErrorId : CommandNotFoundException_x000D__x000A_</S><S S=\"Error\"> _x000D__x000A_</S></Objs>", "parsed": false}
```

**Comment by bcoca** [comment]
you can set `ansible_become` to false in inventory for your windows hosts. In any case this should have given an error before winrm was used as `sudo` is an unsupported become method for that connection plugin (we plan to add `runas` in the future).

**Comment by bcoca** [comment]
@juju4 could you please update the main comment to use the issue template?https://github.com/ansible/ansible/blob/devel/ISSUE_TEMPLATE.md 

Currently we don't have enough information to deal with your bug.

**Comment by juju4** [comment]
Issue Type:    Bug Report
Ansible Version: 2.0.0-0.6.rc1
Environment: Host: lubuntu trusty, guest win10

Summary:
using become/sudo on windows environment is triggering an error whereas it should be ignored (at least until runas is available)
For now, it tries to call unix command on windows.

Steps To Reproduce:
Just create any tasks with 'become: yes' like '- win_file: "path={{ bin_path }} state=directory"'
become can be inherited from playbooks/site whereas tasks are from a role.

```
- hosts: myhost 
  become: yes 
  roles:
    - test
```

```
# role test, tasks
- win_file: "path=c:\\temp state=directory"
```

Expected Results:
create c:\temp

Actual Results:
Above error
