### ISSUE TITLE
vars/main.yml variables content overwritten by later roles in playbook

### ISSUE THREAD

**Issue by Etherdaemon** [ansible/ansible#13341]
**Issue Type:**

Bug Report

**Ansible Version**
ansible 2.0.0 (detached HEAD f2225395f9) last updated 2015/11/28 17:55:43 (GMT +1000)
  lib/ansible/modules/core: (detached HEAD 0e043f8c58) last updated 2015/11/28 17:55:04 (GMT +1000)
  lib/ansible/modules/extras: (detached HEAD e46e2e1d6f) last updated 2015/11/28 17:55:22 (GMT +1000)
  config file =
  configured module search path = Default w/o overrides

**Environment:**
OSX 10.11.1
Running Ansible from source - v2.0.0-0.6.rc1
Running boto (2.38.0) and boto3 (1.1.4)
Python 2.7.10

**Summary:**

When roles are included, variables defined in the defaults of later roles are being included in earlier roles (and if the variable is defined in both - the latter role overrides the current running role).

**Steps To Reproduce:**

```
roles/role1/defaults/main.yml
 ---
  <empty>

roles/role1/tasks/main.yml
 ---

 - name: Debugging test_variable inside role1
   debug:
     msg: "test_variable is defined: {{ test_variable is defined }}"

roles/role2/defaults/main.yml
 ---
  testing_variable: "setting_variable"

roles/role2/tasks/main.yml
 ---

- name: Debugging test_variable inside role2
  debug:
    msg: "test_variable is defined: {{ test_variable is defined }}"

site.yml

---
- name: Running play for testing variable importation
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - { role: role1 }
    - { role: role2 }
```

**Expected Results:**

```
PLAY [Running play for testing variable importation] ************************************

TASK [role1 : Debugging test_variable inside role1] ****************************
ok: [127.0.0.1] => {
    "changed": false,
    "msg": "test_variable is defined: False"
 }

TASK [role2 : Debugging test_variable inside role2] ****************************
 ok: [127.0.0.1] => {
    "changed": false,
    "msg": "test_variable is defined: True"
 }

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0
```

**Actual Results:**

```
PLAY [Running play for testing variable importation] ************************************

TASK [role1 : Debugging test_variable inside role1] ****************************
ok: [127.0.0.1] => {
    "changed": false,
    "msg": "test_variable is defined: True"
 }

TASK [role2 : Debugging test_variable inside role2] ****************************
 ok: [127.0.0.1] => {
    "changed": false,
    "msg": "test_variable is defined: True"
 }

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0
```

**Additional Notes:**
It looks like this has been raised before late last year and @jimi-c  had added a PR but I think it's regressed again since. https://github.com/ansible/ansible/issues/9168

**Comment by jimi-c** [comment]
@Etherdaemon I just retested with the #9219 sample I had and I'm seeing the correct results:

<pre>
TASK [test1 : debug var=role_name] *********************************************
ok: [localhost] => {
    "changed": false, 
    "role_name": "test1"
}
TASK [test1 : debug var=role_uuid] *********************************************
ok: [localhost] => {
    "changed": false, 
    "role_uuid": "ecff3d02-31f9-41bd-847d-22400aa540f5"
}
TASK [test1 : debug var=myvar] *************************************************
ok: [localhost] => {
    "changed": false, 
    "myvar": "test1"
}
TASK [test2 : debug var=role_name] *********************************************
ok: [localhost] => {
    "changed": false, 
    "role_name": "test2"
}
TASK [test2 : debug var=role_uuid] *********************************************
ok: [localhost] => {
    "changed": false, 
    "role_uuid": "61b86110-2088-4acb-b876-cc035798f298"
}
TASK [test2 : debug var=myvar] *************************************************
ok: [localhost] => {
    "changed": false, 
    "myvar": "test2"
}
</pre>

I'll test with your example above to see if this is actually a different bug.

**Comment by jimi-c** [comment]
So yeah, this is expected behavior, all variables in `defaults/main.yml` are read into the global scope. The one caveat is that a role will prefer its own defaults over those of another roles, but since `role1` above does not define the variable it is used from `role2`. 

In general, it's best to try and avoid variable collisions like this by prefixing them with the role name, and to avoid tightly coupling roles by making them depend on variables defined in another role.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by Etherdaemon** [comment]
@jimi-c just to clarify.  You are saying that it is expected behavior that variables in role2/defaults/main.yml are loaded into global scope even before that role is actually run.  EG. If a play includes roles1,2,3 in that order, all 3 roles variables are loaded at the start of the play rather than as each role is included??

**Comment by jimi-c** [comment]
@Etherdaemon yes, that's how Ansible has functioned since role defaults were implemented.
