### ISSUE TITLE
requirements.yml not working

### ISSUE THREAD

**Issue by strarsis** [ansible/ansible#13340]
Using the following requirements.yml as simple example:

```
- src: peru.vmwaretools
```

The file got a yml extension as required for ansible-galaxy 
to detect it is a YAML file and not a simple list text file.

Instructing ansible-galaxy to use this file:

```
$ ansible-galaxy install -r requirements.yml
```

Error mesage despite the user + role exist (https://galaxy.ansible.com/detail#/role/2509):

```
downloading role 'vmwaretools', owned by -%20src%3A%20peru
Sorry, - src: peru.vmwaretools was not found on galaxy.ansible.com.
```

This issue also occurs with other roles from ansible galaxy 
like with the example from the ansible docs:
http://docs.ansible.com/ansible/galaxy.html#advanced-control-over-role-requirements-files

```
 - src: yatesr.timezone
```

Debian Jessie amd64
ansible 1.7.2

**Comment by umeboshi2** [comment]
@strarsis I just bounced into this issue looking for something else, but parsing requirements.yml seems to require ansible >=1.8.

**Comment by bcoca** [comment]
As per comment above, that feature is not available for that version of Ansible

**Comment by strarsis** [comment]
The reason for the old ansible version was that I installed it from Debian Jessie repository 
instead from the ansible PPA.
