### ISSUE TITLE
Ansible is converting " to '

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#13353]
Within my role: `<role>/defaults/main.yml` I have a variable named:

```

---
<role>:
    cassandra_nodes: ["10.0.1.60"]
```

The relevant template section: `"cassandra_node": {{ <role>.cassandra_nodes }}`

Upon execution of this role; the template converts it to:

`"cassandra_node": ['10.0.1.60']`

This is a problem because I have a json configuration that requires the `'` to be `"`.

Seems related to http://stackoverflow.com/questions/31969872/why-ansible-always-replaces-double-quotes-with-single-quotes-in-templates

If I do: `"cassandra_node": {{ <role>.cassandra_nodes | to_json }}` I get the correct output; but it shouldn't be converting the `"` to `'`.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The conversion is happening here at the YAML level, as `["10.0.1.60"]` is shorthand for a YAML list, in any case this would have been converted after templating, which ansible does,  as it matches also a python list.

Try doing this:

```
 cassandra_nodes: ' ["10.0.1.60"]'
```

The leading space should avoid the ansible conversion, the quotes should avoid the YAML one, 
or use the `|to_json` filter when using the variable for output

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by ghost** [comment]
I tried the `cassandra_nodes: ' ["10.0.1.60"]'` method and it did not work. I had to use the `|to_json` method.
