### ISSUE TITLE
Solution for 401 Unauthorized winrm

### ISSUE THREAD

**Issue by vikas027** [ansible/ansible#13369]
I am not quite sure if this is the correct forum to correct documentation. Variables listed in the [documentation](http://docs.ansible.com/ansible/intro_windows.html#inventory) does not work for Windows servers. I am on latest stable version 1.9.4-1 
##### WORKING

``` bash
ansible_ssh_user = vikas027@mydomain.com
ansible_ssh_pass = my_domain_password
ansible_ssh_port = 5986
ansible_connection = winrm
```
##### NOT WORKING

``` bash
ansible_user = vikas027@mydomain.com
ansible_password = my_domain_password
ansible_port = 5986
ansible_connection = winrm
```

**Comment by vikas027** [comment]
Just noticed the blue box saying the variables which are not working are for 2.0 and less. Closing the issue.

**Comment by agaillar** [comment]
Hello, 

i have the same error but i used ansible 2.0.1.0 / CentOS 6.3.
The connection with winRM to WS2012 Hosts is : 
- Ok with {ansible_ssh_user,ansible_ssh_pass...}.
- KO (error 401) with {ansible_user,ansible_pass...}.
