### ISSUE TITLE
ansible-pull security

### ISSUE THREAD

**Issue by pixelrebel** [ansible/ansible#13364]
I have dozens of hosts using ansible-pull in a cron job to auto-update. 

What happens if someone compromises my repo ansible-pull fetches from?  That person could rewrite the playbook in the repo to install and run anything they wish.  Create a botnet? No problem, just update the playbook local.yml, then watch your hosts come online.

So how can we introduce code signing into ansible-pull?

**Comment by bcoca** [comment]
git itself can do signature verification on code, it would require that 'authorized devs' public keys are published to your servers as part of the ansible-pull install and probably not much modification to the ansible-pull itself.  

Most of the work will be updating the git plugin to have a 'verify' state. 

The other version control plugins supported would also have to be looked into.

**Comment by pixelrebel** [comment]
Thanks for the reply @bcoca.  I found some documentation on [git signing](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). 

It looks like ansible git module supports "[verify_commit](http://docs.ansible.com/ansible/git_module.html)" in v2.0.  Can I pass this option downstream to ansible-pull, or does this option need to be written into ansible-pull?

**Comment by bcoca** [comment]
yes, it would have to be updated

**Comment by mscherer** [comment]
It was already added in 6f1189630324 back in June.

**Comment by bcoca** [comment]
nice! i'll make sure this is in the changelog, its a nice feature. Closing this ticket as its been implemented.

**Comment by pixelrebel** [comment]
Sweet!  Thanks @bcoca

**Comment by bcoca** [comment]
you are welcome (taking all the credit by just updating the changelog)
