### ISSUE TITLE
Ansible confusing ERROR: tag(s) not found in playbook

### ISSUE THREAD

**Issue by philbert** [ansible/ansible#13375]
**Ansible Version:**
1.9.4

**Ansible Configuration:**
nothing special

**Environment:**
OSX

**Summary:**
Ansible returns a confusing error `ERROR: tag(s) not found in playbook`, when a role has a tag but no tasks to execute.

My confusion with the error is that I had not added any tags on any tasks inside the roles. I added them only on the inclusion of the role in the playbook. 

Ansible's handling of tags on roles (as opposed to on tasks) seems to be inconsistent.

**Steps To Reproduce:**
with a playbook as follows:
base-playbook.yml

```

---
  - name: base-playbook
    hosts: webservers
    roles:
      - { role: something, tags: something }
```

Where role "something" exists but the contents of roles/something/tasks/main.yml is empty, Ansible fails in the following way:

```
ansible-playbook -i inventory.ini base-playbook.yml --tags something

ERROR: tag(s) not found in playbook: something.  possible values:
```

**Expected Results:**
I expected Ansible would have succeeded execution as it would if no roles were in the playbook:

```
ansible-playbook -i inventory.ini empty.yml

PLAY [empty] ******************************************************************

GATHERING FACTS ***************************************************************
ok: [unicorn]

PLAY RECAP ********************************************************************
unicorn                    : ok=1    changed=0    unreachable=0    failed=0
```

Where empty.yml contains only the following:

```

---
  - name: empty-playbook
    hosts: webservers
```

**Actual Result:**
Because of the error that ansible returned me, I spent about trying to figure out why it did not seem to correctly parse the tag that I added on the role in the playbook. 

```
ansible-playbook -i inventory.ini base-playbook.yml --tags something

ERROR: tag(s) not found in playbook: something.  possible values:
```

**Comment by sivel** [comment]
When `tags` is applied to a role, it is actually applying the tags to each individual task in the role.  If your role has no tasks, then the tags are never applied, and don't exist.

**Comment by philbert** [comment]
Yeah I figured it was trying to do something smart like that. My problem with the error as it appears doesn't make sense unless you know the internal workings of Ansible. It meant that I could only proceed experimentally by trial and error, which can be time consuming and frustrating.

Of course, a role with no tasks is not really intentional, it's just that I'm in a very early stage of development of the project I'm on and I had a break for a week or so where I forgot that I'd commented out all the tasks in the role. 

Maybe this issue goes in the box "a fringe case where the error handling could be improved".

**Comment by bcoca** [comment]
well, in 2.0 missing tags will not error out (yet), but this does seem like an interesting corner case, it should affect empty plays and includes also.

**Comment by hloeffler** [comment]
https://github.com/ansible/ansible/issues/13292

**Comment by bcoca** [comment]
closing as per above, this is not issue in 2.x
