### ISSUE TITLE
Include no longer relative in v2

### ISSUE THREAD

**Issue by rektide** [ansible/ansible#13378]
Hi. Behavior has changed in v2: if you include something in a directory, and then try to include from there, resolving the include happens from the original playbook's directory, not the first include's directory. This is a change from 1.x.

`playbook.yaml`:

```

---
- hosts :all
  tasks:
  - include: subdir/a.yaml
```

`subdir/a.yaml`: `- include: b.yaml`

`subdir/b.yaml`: `- debug: msg=success`

Previously this would have worked. In v2, Ansible looks for b.yaml in the top level-directory (used strace to see what it was looking for), not inside of `subdir` (relative to where the include was launched from), where 1.x used to.

Currently on: ansible 2.0.0 (devel 96fcfe45d0) last updated 2015/11/23 23:29:12

**Comment by jimi-c** [comment]
Hi @rektide, I see you're using a slightly older version, however I'm pretty sure we fixed this quite a while ago. For example, here is the output of your provided sample on the `stable-2.0` branch as of today:

<pre>
# ansible-playbook -vv test.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY ***************************************************************************
TASK [include] *****************************************************************
included: /root/testing/13378/subdir/a.yml for localhost
TASK [include] *****************************************************************
included: /root/testing/13378/subdir/b.yml for localhost
TASK [debug msg=success] *******************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "success"
}
PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
</pre>

I see the same result even if I back up to the https://github.com/ansible/ansible/commit/96fcfe45d089497d6328fb07619570ac5c0d6c54 commit. Can you please test against the most recent devel and/or stable-2.0 and see if your issue remains? If so, could you please provide more information to help us reproduce this?

Thanks!

**Comment by rektide** [comment]
Ah, apologies. I finally got a good isolation on the unexpected behavior I was seeing.

playbook.yaml:

```
---
- hosts: all
  tasks:
  - include: subdir/a.yaml
```

subdir/a.yaml:

```
- include: seconddir/b.yaml
```

subdir/seconddir/b.yaml:

```
- include: c.yaml
```

subdir/seconddir/c.yaml:

```
- debug: msg=win
```

Results in:

```
TASK [setup] *******************************************************************
ok: [127.0.0.1]

TASK [include] *****************************************************************
included: /home/rektide/foo/subdir/a.yaml for 127.0.0.1

TASK [include] *****************************************************************
included: /home/rektide/foo/subdir/seconddir/b.yaml for 127.0.0.1

TASK [include] *****************************************************************
fatal: [127.0.0.1]: FAILED! => {"failed": true, "reason": "ERROR! the file_name '/home/rektide/foo/c.yaml' does not exist, or is not readable"}
```

So it's the third include where working directory context becomes lost. This is affecting my existing numerous-year-old scripts and does appear to be a regression. 

There are quite a number of workarounds involving adding redundant pathing information. I've tried to create a comprehensive set of working and non-working modifications to this test case at https://github.com/rektide/ansible-nested-includes-13378 . I have not yet found a way for nested includes to not lose path context though, and would like to see path-relative includes work at arbitrary depths (currently only works to depth 2).

I am now running:

```
ansible 2.1.0 (devel d203438a2c) last updated 2015/12/15 18:36:41 (GMT -400)
  lib/ansible/modules/core: (detached HEAD e6b7b17326) last updated 2015/12/15 18:50:47 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD f3251de29c) last updated 2015/12/15 18:50:47 (GMT -400)
  config file = 
```

**Comment by jimi-c** [comment]
Ok I can confirm seeing this. I'll dig into it.

**Comment by jimi-c** [comment]
This should be resolved in stable-2.0/devel, if you can confirm?

**Comment by rektide** [comment]
Yup, seeing this fixed! Big help, many many thanks!

**Comment by dcodix** [comment]
Hi there.

Just today I tryied to change to the ansible 2.0.0.
I thught I got this same problem (calling task with relative paths didn't work as expected), but trying the example from above it seems to work ok.

But yet it didn't work for my playbooks.

Finally I found out (and I think it might be a related problem), that it works ok if the calls are made from a "normal" playbook, but not if they are done from within a role.

Following the above example. If the call to "subdir/a.yaml" is made (as above) from the playbook "playbook.yaml" it works perfectly. But if instead "playbook.yaml" where to be the "main.yaml" in a "my_role/tasks/main.yaml" it would not work.

It seems to me that in this case the relative path is relative to the path where the playbook calling the role is.

I think this "problem" might be related.

UPDATE:
Sorry guys I was wrong in my diagnostic. The problem is not because of the roles but because I am passing the path to the playbook via variable.
In the esable above it will fail if the first include is a variable.
If
- include: subdir/a.yaml
  is instad 
- include: {{ a_file_path }}

In that situation it will not be able to include "b.yaml"

**Comment by xidui** [comment]
@dcodix +1
I also met this problem in `2.0.1.0`

**Comment by ololduck** [comment]
HI everyone.
I'm also seeing the issue in `2.0.2.0`.

**Comment by HelioCampos** [comment]
Hi guys,
- I'm also having this same problem. Let me give you the data i have:

```
ansible 2.0.1.0
  config file =
  configured module search path = Default w/o overrides
ansible-playbook 2.0.1.0
  config file =
  configured module search path = Default w/o overrides
My OS:
   Name: Mac OS X Al Captain
   Version: 10.11.4 (15E65)
   Python: 2.7.10
The Server's OS:
   Name: Amazon linux
   Version: 2016.03
   Python: 2.7.10
```
- I'm running the role described at:

```
dj-wasabi.zabbix-agent (https://github.com/dj-wasabi/ansible-zabbix-agent)
```
- This is the main.yml

```
-
  hosts: web-homolog
  roles:
    - role: dj-wasabi.zabbix-agent
      ansible_distribution_major_version: 6
  tasks:
    - include: tasks/userparameter.yml application_name='nginx' application_test='$(service nginx status | egrep -o "pid" | tr -d "\n") == "pid"' }
    - include: tasks/userparameter.yml application_name='unicorn' application_test='-s /srv/www/shared/pids/unicorn.pid -a $(cat /srv/www/shared/pids/unicorn.pid | tr -d "\n") -eq $(ps -ef f | egrep [u]nicorn | head -1 | awk "{ print $2 }" | tr -d "\n")' }
```
- It's the additional tasks described above that we are having troubles with.
- This is the error we are getting running from the directory "/Users/helio.campos/Documents/ansible
  ":

```
ansible-playbook zabbix/zabbix_agent.yml -i ./hosts --check

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [XXXXX]

TASK [dj-wasabi.zabbix-agent : Include OS-specific variables] ******************
ok: [XXXXX]

TASK [dj-wasabi.zabbix-agent : Install the correct repository] *****************
included: /usr/local/etc/ansible/roles/dj-wasabi.zabbix-agent/tasks/RedHat.yml for XXXXX

TASK [dj-wasabi.zabbix-agent : RedHat | Set short version name] ****************
ok: [XXXXX]

TASK [dj-wasabi.zabbix-agent : RedHat | Use EPEL package name] *****************
skipping: [XXXXX]

TASK [dj-wasabi.zabbix-agent : RedHat | Install basic repo file] ***************
ok: [XXXXX]

TASK [dj-wasabi.zabbix-agent : RedHat | Installing zabbix-agent] ***************
ok: [XXXXX]

TASK [dj-wasabi.zabbix-agent : RedHat | Enable the service] ********************
ok: [XXXXX]

TASK [dj-wasabi.zabbix-agent : Install the correct repository] *****************
ok: [XXXXX]

TASK [dj-wasabi.zabbix-agent : Install the correct repository] *****************
ok: [XXXXX]

TASK [dj-wasabi.zabbix-agent : Fail invalid specified agent_listeninterface] ***
ok: [XXXXX]

TASK [dj-wasabi.zabbix-agent : Get IP of agent_listeninterface when no agent_listenip specified] ***
ok: [XXXXX]

TASK [dj-wasabi.zabbix-agent : Default agent_listenip to all when not specified] ***
ok: [XXXXX]

TASK [dj-wasabi.zabbix-agent : Fail invalid specified agent_listenip] **********
skipping: [10.33.2.232]

TASK [dj-wasabi.zabbix-agent : Configure zabbix-agent] *************************
ok: [XXXXX]

TASK [dj-wasabi.zabbix-agent : Create include dir zabbix-agent] ****************
ok: [XXXXX]

TASK [dj-wasabi.zabbix-agent : Make sure the zabbix-agent service is running] **
ok: [XXXXX]

TASK [dj-wasabi.zabbix-agent : Create hostgroups] ******************************
skipping: [XXXXX]

TASK [dj-wasabi.zabbix-agent : Create a new host or update an existing host's info] ***
skipping: [XXXXX]

TASK [dj-wasabi.zabbix-agent : Updating host configuration with macros] ********
skipping: [XXXXX] => (item=zabbix_macros)

TASK [include] *****************************************************************
fatal: [XXXXX]: FAILED! => {"failed": true, "reason": "the file_name '/Users/helio.campos/Documents/ansible/zabbix/tasks/userparameter.yml }' does not exist, or is not readable"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @zabbix/zabbix_agent.retry

PLAY RECAP *********************************************************************
10.33.2.232                : ok=11   changed=1    unreachable=0    failed=1
```
- And this is the files I have in this path:

```
/Users/helio.campos/Documents/ansible
/Users/helio.campos/Documents/ansible/hosts
/Users/helio.campos/Documents/ansible/zabbix
/Users/helio.campos/Documents/ansible/zabbix/1
/Users/helio.campos/Documents/ansible/zabbix/tasks
/Users/helio.campos/Documents/ansible/zabbix/tasks/userparameter.yml
/Users/helio.campos/Documents/ansible/zabbix/templates
/Users/helio.campos/Documents/ansible/zabbix/templates/model.conf
/Users/helio.campos/Documents/ansible/zabbix/zabbix_agent.retry
/Users/helio.campos/Documents/ansible/zabbix/zabbix_agent.yml
```
- This is the "/Users/helio.campos/Documents/ansible/zabbix/tasks/userparameter.yml":

```
---

- name: "Installing {{ application_name }} monitoring configuration"
  template:
        src=model.conf.j2
        dest="/etc/zabbix/zabbix_agentd.d/userparameter.conf"
        owner=zabbix
        group=zabbix
        mode=0755
  notify: restart zabbix-agent
  become: yes
```
- And, finally, this is our template:

```
# This is an sample userparameters file.
UserParameter={{ application_name }}.status,[ {{ application_test }} ] && echo 1 || echo 0
```
- Can anyone point me what am I doing wrong?
