### ISSUE TITLE
CallbackModule.v2_runner_on_failed prevents tasks from running, git bisect done

### ISSUE THREAD

**Issue by Christoph-D** [ansible/ansible#13370]
Issue Type: Bug report
Ansible Version: ansible 2.0.0 (stable-2.0 204e27ca66)
Ansible Configuration: No changes from original
Environment: Ubuntu 14.04, hosts mixed Ubuntu 14.04/Debian wheezy.

Summary:
According to git bisect 984729016e3ea20e27c60fa5110cfca19580370f is responsible for introducing the error described below.  When I revert the changes introduced by this commit to lib/ansible/plugins/strategy/free.py, the error disappears.

Unfortunately, I do not understand the changes well enough to provide a patch, but I hope my report helps.

Steps To Reproduce:
Run a playbook with "strategy: free" and a few roles/includes.  I cannot provide further details at this point because this playbook is private.

Expected Results:
No error.

Actual Results:

```
[WARNING]: Error when using <bound method CallbackModule.v2_runner_on_failed of
</home/christoph/ansible-dev/lib/ansible/plugins/callback/default.CallbackModule
object at 0x7fec8bf56690>>: 'NoneType' object has no attribute 'loop'
```

preventing this task from running on the remaining hosts.

**Comment by jimi-c** [comment]
Hi @Christoph-D, could you please create a simple reproducer for this? I'm unable to reproduce it with the limited information you've provided.

**Comment by Christoph-D** [comment]
I posted a test case on https://github.com/Christoph-D/ansible-issue-13370 .
It calls out to 8 remote hosts, but doesn't do anything except printing a debug message after including a role and then a yml file.

The output of "ansible-playbook site.yml" is in the file error.log.

I also observed that the error disappears when I remove the line "strategy: free".

**Comment by bcoca** [comment]
I can reproduce with a simple include, but need at least 7 hosts
play.yml

```
- hosts: all
  gather_facts: False
  strategy: free
  tasks:
    - include: test.yml
```

test.yml

```
- debug: var=inventory_hostname
```

output:

```
 __________________________________________________ 
< TASK [debug msg=included {{inventory_hostname}}] >
 -------------------------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost] => {
    "changed": false, 
    "msg": "included localhost"
}
ok: [localhost2] => {
    "changed": false, 
    "msg": "included localhost2"
}
ok: [localhost3] => {
    "changed": false, 
    "msg": "included localhost3"
}
ok: [localhost4] => {
    "changed": false, 
    "msg": "included localhost4"
}
ok: [localhost5] => {
    "changed": false, 
    "msg": "included localhost5"
}
ok: [localhost6] => {
    "changed": false, 
    "msg": "included localhost6"
}
Unexpected Exception: 'NoneType' object has no attribute '_block'
```

**Comment by Christoph-D** [comment]
@mcsalgado Your commit 0f9d9bafb2ed8acaabf0d96bbb38933839b5d9c7 fixes the issue at hand, but introduces a new bug.  Replace test.yml in your test case with:

```
- block:
  - debug: msg=A
- block:
  - debug: msg=B
```

Then the message "A" is printed twice by each host.

After reading a little more of the source code, it seems to me that there were to problems
1. PlayIterator.add_tasks() bailed on an empty task list.
2. The variable all_blocks was overwritten in every iteration of the loop over included_files.

I created the pull request #13394 with a proposed solution.

**Comment by Christoph-D** [comment]
I should add that I would appreciate it if someone more knowledgeable about the code base than me could review 9a6ae1d62a773285c23cc095f43d91ef86112f6e in particular.  I do not know all the implications of this patch.

**Comment by mcsalgado** [comment]
Oh I see, I misunderstood how PlayIterator.add_tasks() works. Well, it was worth a try to learn something!

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
