### ISSUE TITLE
Problem with latest ansible (build from source) and debian: unwanted environment variables

### ISSUE THREAD

**Issue by roberthartung** [ansible/ansible#13399]
I am using `ansible -m ping nodes2 -u root -vvvv` to ping my nodes. They seem to be unreachable but in the end, the following ssh command does not work:

SH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/potato/.ansible/cp/ansible-ssh-%h-%p-%r -tt 172.16.1.172 LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 python -uc 'import sys; [sys.stdout.write(s) for s in iter(sys.stdin.readline, "**EOF__942d747a0772c3284ffb5920e234bd57**\n")]'| LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python

The problem here are the LC_ALL, LC_MESSAGES and LANG variables. As soon as I remove them everything works fine. I guess this is because the locale is not available on my target system. How do I remove these variables or set them correctly?

**Comment by amenonsen** [comment]
You can set ANSIBLE_MODULE_LANG in the environment.

**Comment by bcoca** [comment]
also module_lang in ansible.cfg

On Wed, Dec 2, 2015 at 8:24 AM, Abhijit Menon-Sen notifications@github.com
wrote:

> You can set ANSIBLE_MODULE_LANG in the environment.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible/issues/13399#issuecomment-161353070.

## 

Brian Coca

**Comment by amenonsen** [comment]
Why isn't the default whatever LANG is set to on the control node?

**Comment by bcoca** [comment]
not sure why, but it makes sense it should be.

## 

Brian Coca

**Comment by amenonsen** [comment]
I just submitted PR #13403 to change that.

**Comment by bcoca** [comment]
fixed via merged #13403
