### ISSUE TITLE
[v2] "win_iis_webbinding" module require additional parameters to run?

### ISSUE THREAD

**Issue by BenMo158** [ansible/ansible#13390]
<b>I was run<b>

``` json
ansible iis01 -m win_iis_webbinding -a "name=tiger"
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: +     ~~~~~~~~~~~~~~~~~~~
iis01 | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Property 'host_header' cannot be found on this object. Make sure that it exists."
}
```

<b>I need run this,it's work<b>

``` json
ansible iis01 -m win_iis_webbinding -a "name=tiger host_header=www.tiger.com protocol=http port=8083 ip=127.0.0.1"
iis01 | SUCCESS => {
    "added": [], 
    "changed": false, 
    "matched": [], 
    "parameters": {
        "HostHeader": "www.tiger.com", 
        "IPAddress": "127.0.0.1", 
        "Name": "tiger", 
        "Port": "8083", 
        "Protocol": "http"
    }, 
    "removed": []
}
```

**Comment by BenMo158** [comment]
<b>I mean, I have an existing site --"tiger"<b>,
I want to get the binding information for the "tiger"
I perform this

``` json
ansible iis01 -m win_iis_webbinding -a "name=tiger"
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: +     ~~~~~~~~~~~~~~~~~~~
iis01 | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Property 'host_header' cannot be found on this object. Make sure that it exists."
}
```

so,I had to carry out to pass

``` json
ansible iis01 -m win_iis_webbinding -a "name=tiger host_header=www.tiger.com protocol=http port=8083 ip=127.0.0.1"
```

<b>"host_header" "protocol" "port" "ip" parameters into the default option.

**Comment by nitzmahone** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
