### ISSUE TITLE
Transient failure caused by new pipelining patch.

### ISSUE THREAD

**Issue by abadger** [ansible/ansible#13411]
I've been testing a moderate sized playbook for fedora infrastructure.  the new requiretty + pipelining patch is causing a very strange problem.

The playbook has 136 tasks to create and configure a certain host.  A second host gets 123 tasks and skips 13.  When I run the devel branch with pipelining on the host that has 136 tasks always fails.  The one with 123 tasks never has.  However, the task that fails is not stable.  In every run I've made so far it's been a different task.  (All of the tasks that failed thus far have run on both hosts but I think that's just a percentage chance.. I don't think the tasks necessarily have to run on both).

The traceback I get back from the host is either a SyntaxError or  an IndentationError:

```
<noc02.fedoraproject.org> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=90 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt noc02.fedoraproject.org LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 python -uc 'import sys; [sys.stdout.write(s) for s in iter(sys.stdin.readline, "__EOF__942d747a0772c3284ffb5920e234bd57__\n")]'| LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python
fatal: [noc01.phx2.fedoraproject.org]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"name": "root", "password": "$6$77Ba4HEk$X1ejN6W0yRy6NZeG0R2WoSS5d8EPiZJPukFrY7pklxlB.39o5mbKW3Sxd4WSs7VK4B4EVPLaBjDFBE7TSRtTY0", "state": "present"}, "module_name": "user"}, "msg": "  File \"<stdin>\", line 1\r\n    o\" ]\r\n       ^\r\nSyntaxError: EOL while scanning string literal\r\nTraceback (most recent call last):\r\n  File \"<string>\", line 1, in <module>\r\nIOError: [Errno 32] Broken pipe\r\nOpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /root/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 32625\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to noc01.phx2.fedoraproject.org closed.\r\n", "parsed": false}
```

jimi pointed out that this is what happens if we pipe a module into python and python thinks it has a tty ( copy and paste a module into the interactive prompt and that's the error you get).

Sure enough, if I set pipelining = False in the ansible.cfg, I can't provoke the error anymore.  If I switch to the stable-2.0 branch, I also can't provoke the error.  So it seems that something about the patch to use python to stream the module in pipelining mode is intermittently failing to do what it's supposed to.  Intermittently, the python that actually executes the module thinks it has a tty and runs in interactive mode causing the error.

**Comment by amenonsen** [comment]
Do you happen to have/can you get debug output from a failing invocation?

**Comment by abadger** [comment]
Here's the output from one task header to the next task header:

https://gist.github.com/abadger/3bfe17f47db7b5ef0d22

**Comment by abadger** [comment]
Reverting the commit in devel for now as @amenonsen will be busy for a few days and others are busy with the 2.0 release. I'll leave this open for now as we'll want to remerge once the problems with the code are fixed.

**Comment by jimi-c** [comment]
Closing, per the above.
