### ISSUE TITLE
ansible-galaxy install does not work in stable-2.0

### ISSUE THREAD

**Issue by rboudrie** [ansible/ansible#13419]
I have successfully installed Ansible 1.8.1 and 1.9 without difficulty.  When I attempt to install Ansible 2.0 on linux, I get the following:

```
lrmk225:~/shared-webstorage/storage/hdfssvc/playbooks/build # ansible-galaxy install -r requirements.txt -f
ERROR! Could not open readme: [Errno 2] No such file or directory: '/usr/local/lib64/python2.6/site-packages/ansible-2.0.0-py2.6.egg/ansible/galaxy/data/readme'
```

I tried creating an empty readme in this location, but that just shifts the error to:

```
lrmk225:~/shared-webstorage/storage/hdfssvc/playbooks/build # ansible-galaxy install -r requirements.txt -f
ERROR! Could not open metadata_template.j2: [Errno 2] No such file or directory: '/usr/local/lib64/python2.6/site-packages/ansible-2.0.0-py2.6.egg/ansible/galaxy/data/metadata_template.j2'
```

Is this a known issue?    This was reported to me by another individual in my organization, and I duplicated it on a different system.

**Comment by rboudrie** [comment]
The "requirements.txt" file I used in my command contained one line:  
foobar_common.tar.gz,2.2.0.0.73760.718a938,foobar_common

(the product name was renamed to foobar for the sake of privacy)

**Comment by bcoca** [comment]
how are you installing ansible?, those 2 files are in setup.py and should be included

**Comment by rboudrie** [comment]
I suspect the problem is because I was installing Ansible 2.0 by building the package (the system I was using does not have repo access.

I used this same procedure to build Ansible 1.8.1 and 1.9 and did not have any problems.  Other users in my organization have reported the same problem.

git clone https://github.com/ansible/ansible.git
git checkout -b stable-2.0 origin/stable-2.0
git pull --rebase; git submodule update --init --recursive
cd ./ansible
source ./hacking/env-setup
make rpm
cd rpm-build/
tar -zxvf stable-2.0.tar.gz 
cd stable-2.0
python setup.py build
python setup.py install

**Comment by NPrescott** [comment]
Experiencing the same using the recommended installation for OSX (via pip) on all ansible-galaxy commands:
- Python 2.7.9
- Version: 2.0.0
  
  ```
  > ansible-galaxy info
  ERROR! Could not open readme: [Errno 2] No such file or directory: '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/galaxy/data/readme'
  
  > ansible-galaxy list --version
  ansible-galaxy 2.0.0
  ```

**Comment by sebastianneubauer** [comment]
same here with new released ansible version 2.0.0.0 on pypi...

```
pip install ansible
ansible-galaxy install some_role
ERROR! Could not open readme: [Errno 2] No such file or directory: '/tmp/ansible_test/local/lib/python2.7/site-packages/ansible/galaxy/data/readme'
```

**Comment by sebastianneubauer** [comment]
the "data" folder from `lib/ansible/galaxy/data` is missing in the package on pypi

**Comment by sebastianneubauer** [comment]
#13813 could be a fix for this, but not tested...

**Comment by bcoca** [comment]
so it seems that our testing was done with newer version of setuptools which did pickup the data directory, but our deployment machine used an older one ... :-(

**Comment by geerlingguy** [comment]
Ditto; this is causing <del>some</del> all of my Travis CI role builds to fail (e.g. https://travis-ci.org/geerlingguy/ansible-role-php-xdebug/builds/101866644).

**Comment by abadger** [comment]
We're discussing right now whether to push out a bugfix that's just fixing this and another packaging problem.  We should have a decision soon and if we spin an update with just those fixed, that should be later today.  A workaround for people needing things to work "right now" is to download the contents of https://github.com/ansible/ansible/tree/stable-2.0/lib/ansible/galaxy/data and drop it into the correct directory.
- https://raw.githubusercontent.com/ansible/ansible/stable-2.0/lib/ansible/galaxy/data/travis.j2
- https://raw.githubusercontent.com/ansible/ansible/stable-2.0/lib/ansible/galaxy/data/metadata_template.j2
- https://raw.githubusercontent.com/ansible/ansible/stable-2.0/lib/ansible/galaxy/data/readme
- https://raw.githubusercontent.com/ansible/ansible/stable-2.0/lib/ansible/galaxy/data/test_playbook.j2

**Comment by arknoll** [comment]
@abadger Any update on the status on pushing a fix today?

**Comment by abadger** [comment]
Branch that we've assembled this and two other packaging fixes is here: https://github.com/ansible/ansible/tree/stable-2.0.0.1

**Comment by geerlingguy** [comment]
@abadger - Awesome! Please let us know when it's published on pip—I'll rerun my tests and make sure everything's happy.

**Comment by sebastianneubauer** [comment]
this might be the best workaround until a fix is released: upgrade setuptools and then "pip install git+https://github.com/ansible/ansible.git@v2.0.0.0-1" which will repackage correctly...

**Comment by abadger** [comment]
2.0.0.1 is now live on pypi: https://pypi.python.org/pypi/ansible
