### ISSUE TITLE
lineinfile error file not exist if use --ask-sudo-pass

### ISSUE THREAD

**Issue by roumano** [ansible/ansible#13415]
Issue Type:
    Bug Report

Ansible Version:
ansible --version
ansible 1.9.4
  configured module search path = None

Ansible Configuration:
Also Tested with ansible.cfg  from Github
Environment:
Running on a fedora 22
OS Managing : CentOS release 6.7 (Final)
Summary:

Module lineinfile in error is using with sudo

Steps To Reproduce:

1) Create this playbook :
- hosts: XXXXX
  tasks:
  - lineinfile:
    create=no
    dest=/etc/sssd/sssd.conf
    regexp="^sudo_timed "
    insertafter="^[sudo]"
    line="sudo_timed = true"

2 ) execute it  :

ansible-playbook sudo_not_after.yml -i hosts_sch -K

Expected Results:

Same as when running via root user :

ansible-playbook sudo_not_after.yml -i hosts_sch 

PLAY [XXXXXX] **********************************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [XXXXXX]

TASK: [lineinfile create=no dest=/etc/sssd/sssd.conf regexp="^sudo_timed " insertafter="^[sudo]" line="sudo_timed = true"] **\* 
ok: [XXXXXX]

PLAY RECAP *******************************************************************\* 
XXXXXX               : ok=2    changed=0    unreachable=0    failed=0   

Actual Results:
SUDO password: 

PLAY [XXXXXX] **********************************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [XXXXXX]

TASK: [lineinfile create=no dest=/etc/sssd/sssd.conf regexp="^sudo_timed " insertafter="^[sudo]" line="sudo_timed = true"] **\* 
failed: [XXXXXX] => {"failed": true, "rc": 257}
msg: Destination /etc/sssd/sssd.conf does not exist !

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/home/cia/sudo_not_after.retry

XXXXXX               : ok=1    changed=0    unreachable=0    failed=1

**Comment by roumano** [comment]
Forget my request, i have forget to use the "-s" argument ....

But why it's asking my password via the --ask-sudo-pass and don't use it

**Comment by bcoca** [comment]
because you can set sudo at play or task level, so the password might still be needed and it does not imply forcing sudo for the whole playbook.
