### ISSUE TITLE
ansible ppa: 404 Not Found (Debian Jessie)

### ISSUE THREAD

**Issue by strarsis** [ansible/ansible#13423]
I added the ansible ppa as apt repository:

```
# apt-add-repository -y ppa:ansible/ansible
```

When running apt-get update following error occurs:

```
[...]
Err http://ppa.launchpad.net jessie/main amd64 Packages
  404  Not Found
[...]
W: Failed to fetch http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found
[...]
E: Some index files failed to download. They have been ignored, or old ones used instead.
[...]
```

aptitude versions lists only the ansible package from Debian repository:

```
Package ansible:
i   1.7.2+dfsg-2                                                         stable                                            500

Package ansible-doc:
p   1.7.2+dfsg-2                                                         stable                                            500

Package ansible-fireball:
p   1.7.2+dfsg-2                                                         stable                                            500

Package ansible-node-fireball:
p   1.7.2+dfsg-2                                                         stable                                            500
```

System is Debian Jessie amd64.

**Comment by abadger** [comment]
PPAs are a built for Ubuntu releases, not Debian.  There may be a way to configure a Debian installation to use packages from a PPA but that would be a question to ask of debian users.  It won't be a code problem with ansible.

If you can't get in touch with any Debian users, you can try the ansible mailing list to see if anyone there is trying to do what you are doing (however, I think it's more likely that you'll find people running PPAs on Debian on the Debian lists).  I'll post the Ansible mailing list information below.

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by tersmitten** [comment]
ppa's are an Ubuntu (only) thing as far as I know

**Comment by strarsis** [comment]
Instead using a package, I now install the latest ansible globally using pyhton pip and it works well.
