### ISSUE TITLE
Syslog facility

### ISSUE THREAD

**Issue by alopropoz** [ansible/ansible#1342]
It would be nice to have ability to set syslog facility (now LOG_USER is default and can not be changed).

**Comment by jpmens** [comment]
Trying to help get issues solved to the best of my abilities ... ;)

IIRC, @mpdehaan said recently it is very difficult to get ansible_cfg args into the runner. I've been looking at how this could be done, and have come up with the following code (tested against 0.8).

People can set their desired syslog facility by creating a hostvar, e.g.:

```
syslogfacility=LOG_NEWS
```

Should this in any way be an acceptable solution, I'll gladly submit pull request for current _devel_.

Proposed solution:

``` diff

--- ansible-0.8/lib/ansible/module_common.py    2012-10-20 02:30:41.000000000 +0200
+++ ../ansible/ansible-0.8/lib/ansible/module_common.py 2012-10-25 15:30:52.000000000 +0200
@@ -223,7 +223,7 @@
             journal.sendv(*journal_args)
         else:
             msg = ''
-            syslog.openlog('ansible-%s' % os.path.basename(__file__))
+            syslog.openlog('ansible-%s' % os.path.basename(__file__), 0, syslog.LOG_USER)
             for arg in log_args:
                 msg = msg + arg + '=' + str(log_args[arg]) + ' '
             syslog.syslog(syslog.LOG_NOTICE, 'Invoked with %s' % msg)

--- ansible-0.8/lib/ansible/runner/__init__.py  2012-10-20 02:30:41.000000000 +0200
+++ ../ansible/ansible-0.8/lib/ansible/runner/__init__.py   2012-10-25 15:31:18.000000000 +0200
@@ -562,11 +572,15 @@
         module_data = ""
         is_new_style=False

+   syslogfacility = 'LOG_USER'
+   if 'syslogfacility' in inject:
+       syslogfacility = inject['syslogfacility']
         with open(in_path) as f:
             module_data = f.read()
             if module_common.REPLACER in module_data:
                 is_new_style=True
             module_data = module_data.replace(module_common.REPLACER, module_common.MODULE_COMMON)
+            module_data = module_data.replace('syslog.LOG_USER', "syslog.%s" % syslogfacility)
             encoded_args = "\"\"\"%s\"\"\"" % module_args.replace("\"","\\\"")
             module_data = module_data.replace(module_common.REPLACER_ARGS, encoded_args)

```

**Comment by sfromm** [comment]
I was thinking that as part of the implementation, one could add a constant to lib/ansible/constants.py, eg DEFAULT_SYSLOG_FACILITY, that could also be defined in ansible.cfg.  Thoughts?

**Comment by mpdehaan** [comment]
Yes, definitely.

Note it should prob only be passed to new style modules as it may break ones that do not anticipate the new param

**Comment by jpmens** [comment]
> i can see if i can help #1342 along

@sfromm : yes, gladly ;-)

**Comment by mpdehaan** [comment]
closed per above, thanks!
