### ISSUE TITLE
ERROR: unable to find an inventory file, specify one with -i ?

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#13427]
huzhifeng@s ~ $ ansible -v all --list-hosts
ERROR: Unable to find an inventory file, specify one with -i ?
huzhifeng@s ~ $ ls -l /etc/ansible/hosts
-rw-rw-r-- 1 huzhifeng huzhifeng 152 Dec  4 15:23 /etc/ansible/hosts

**Comment by ghost** [comment]
I provided hosts file as the guide told me . but ansible still show me the errors.
 I am fresh install ansible 1.9.4

**Comment by ghost** [comment]
huzhifeng@s ~ $ ansible --version
ansible 1.9.4
  configured module search path = None

**Comment by lvii** [comment]
Is there a **local config** like `~/.ansible.cfg` or `running/ansible/path/ansible.cfg` has a different `inventory` option in the local config ?

**Comment by ghost** [comment]
No. fresh install.

**Comment by ghost** [comment]
```
huzhifeng@s ~ $ ls .ansible.cfg
ls: cannot access .ansible.cfg: No such file or directory

```

**Comment by ghost** [comment]
The problem resolved myself. i found a $ANSIBLE_INVENTORY  ENV variable in .bashrc
