### ISSUE TITLE
Bug: unable to run parallel forks

### ISSUE THREAD

**Issue by voidzero** [ansible/ansible#13434]
Ansible version: ansible 1.9.4, packages on my Funtoo (Gentoo-like) system were updated recently.

Ansible only works when I supply `-f 1`. More than one fork will cause the following error:

<pre>
PLAY [recursor] *************************************************************** 

TASK: [recursor | Some funky task] ************************************** 
Process SyncManager-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 558, in _run_server
    server.serve_forever()
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 184, in serve_forever
    t.start()
  File "/usr/lib/python2.7/threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/python-exec/python2.7/ansible-playbook", line 264, in main
    pb.run()
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 348, in run
    if not self._run_play(play):
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 789, in _run_play
    if not self._run_task(play, task, False):
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 497, in _run_task
    results = self._run_task_internal(task, include_failed=include_failed)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 439, in _run_task_internal
    results = runner.run()
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1490, in run
    results = self._parallel_exec(hosts)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1375, in _parallel_exec
    job_queue = manager.Queue()
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 667, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 565, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 175, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 432, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
EOFError
</pre>

**Comment by bcoca** [comment]
anything in logs? dmesg? An error like this is normally a resource issue.

**Comment by voidzero** [comment]
Yeah, I figured the same thing. Nothing in dmesg. But the fact that this usually points towards resource issues is what is making this so weird: the server is a beast with a lot of those... and nothing indicates that any resource is full. Any idea where else I can look?

**Comment by voidzero** [comment]
Additionally, ulimit -a looks normal and the only thing that has changed is that packages were updated. So it seems like one of those might have introduced some bug... _gasp_
I recompiled python itself just to be sure, and ansible as well. Isn't it weird that this problem does not occur with `-f 1`?

**Comment by abadger** [comment]
Yeah, this doesn't seem like a problem with ansible's code but something about your environment.  You probably want to post to the mailing list because there's only a few of us developers  here whereas the mailing list will have a bunch of people who are using ansible and might have encountered something like this before.  I'll paste the mailing list info below:

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by voidzero** [comment]
Wish I had the time. Personal reasons cause me to be bit low on time for the coming weeks to really dive into this (or much else of anything technical for that matter).

Apparently the behaviour I described appears to be related to grsecurity (pax actually). With kernel.pax.softmode=1, parallel execution works. But with 0, it doesn't. I can temporarily switch to softmode but that's more of a workaround. I'm not really familiar with Python either, so for now I'll have to leave it at this. Hopefully someone with a better skill set can pick this up if so desired. Cheers.

**Comment by bcoca** [comment]
So when you compile the kernel make sure 'emulate trampolines' (EMUTRAMP) is set in the PAX options, this is needed for Python to run correctly under PAX. Otherwise Python cannot generate code and flag it as executable, which it needs to do to create the Ansible workers.

**Comment by voidzero** [comment]
Yes, thing is that emutramp is an enabled option already, and the python binary /usr/bin/python2.7 is correctly set with paxctl as well. Any idea if I need to check pax flags on other files?

**Comment by bcoca** [comment]
not that i know of, that was all that as needed for it to work on my gentoo box.

**Comment by voidzero** [comment]
Ok as a reference to anyone who stumbles upon this same issue at some point... I _finally_ found the proper way to handle this. Apparently, aside from the kernel option `PAX_EMUTRAMP=y` (which I already had), one also needs to set `CONFIG_PAX_MPROTECT_COMPAT=y`. That option was lacking from my kernel, and caused problems with ansible as well as other stuff (e.g. fail2ban). :+1:
