### ISSUE TITLE
test for file existance before running first playbook

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#1345]
Being an idiot, I have a tendancy to type

```
ansible-playbook foo.yaml host.example.com
```

instead of

```
ansible-playbook foo.yaml -l host.example.com
```

The impact:
- the playbook is first run across all hosts (which I didn't want)
- then after this has completed, I get an error saying file not found: host.example.com

Can I suggest that if multiple playbooks are listed on the command line, that they are tested for existence _before_ the command starts any work?

**Comment by mpdehaan** [comment]
Really what you should be doing here is keeping your hosts in seperate inventory files, if you want to avoid the risk of leaving off "-l", checking for the file prior to ignition won't save you from leaving it completely off.

That being said, checking for files prior to launch is reasonable.

**Comment by candlerb** [comment]
> Really what you should be doing here is keeping your hosts in seperate inventory files

The playbook does specify the appropriate `hosts:` to which this playbook is applicable. I am using -l as a way to test the playbook against a single host, before I decide to apply it to everything.

(Some "dry-run" functionality would be nice too, but that's clearly under separate discussion, and the ticket was closed)

**Comment by mpdehaan** [comment]
good, yes we have reasons re dry run -- most tools that offer it are not really saying anything about side effects, so we prefer to not pretend.   That all being said, we're also crazy dynamic, because you can do things based on the results of other commands and states.
