### ISSUE TITLE
ansible-pull not working in 2.0.0

### ISSUE THREAD

**Issue by pixelrebel** [ansible/ansible#13458]
On OS X 10.8, git version 2.3.5:
 Same command works in 1.9.4, but failed in 2.0.0.  The underlying git module command works in 2.0.0.

```
$ ansible --version
ansible 2.0.0
  config file = 
  configured module search path = Default w/o overrides
$ ls -al /opt/myproj/lib
ls: /opt/myproj/lib: No such file or directory
$ sudo ansible-pull -o --key-file=/private/var/root/.ssh/github_id_rsa -i "localhost," -d /opt/myproj/lib -U git@github.com:myuser/myrepo.git -C stable
Starting Ansible Pull at 2015-12-07 11:00:57
/usr/local/bin/ansible-pull -o --key-file=/private/var/root/.ssh/github_id_rsa -i localhost, -d /opt/myproj/lib -U git@github.com:myuser/myrepo.git -C stable
Repository has not changed, quitting.
$ sudo pip uninstall ansible
Successfully uninstalled ansible-2.0.0
$ sudo CFLAGS=-Qunused-arguments CPPFLAGS=-Qunused-arguments pip install ansible
Successfully installed ansible-1.9.4
$ ansible --version
ansible 1.9.4
  configured module search path = None
$ sudo ansible-pull -o --key-file=/private/var/root/.ssh/github_id_rsa -i "localhost," -d /opt/myproj/lib -U git@github.com:myuser/myrepo.git -C stable
Starting ansible-pull at 2015-12-07 11:01:59
localhost | success >> {
    "after": "72ac77bb2b692b3fec5a0b1234c871d7f85a5849", 
    "before": null, 
    "changed": true
}


PLAY [simple update from v1.0.0 to v1.0.2] ************************************ 
skipping: no hosts matched

PLAY RECAP ******************************************************************** 
```

In 2.0.0 no matter what I put in the command, including a key file that doesn't exist (should throw an error) it always returns `Repository has not changed, quitting.`

**Comment by jimi-c** [comment]
Hi @pixelrebel, how did you install 2.0 here? It's odd that it's not reporting some standard info there with the `--version` option.

**Comment by pixelrebel** [comment]
Hi @jimi-c, I downloaded `ansible-2.0.0-0.6.rc1.tar.gz` from the releases in github.  After uncompressing,  I `cd` into the directory and run `sudo CFLAGS=-Qunused-arguments CPPFLAGS=-Qunused-arguments python setup.py install`

Was that right?

**Comment by bcoca** [comment]
fixes to ansible-pull are included in rc2, try that to confirm it fixes your issues

**Comment by pixelrebel** [comment]
Hi @bcoca, looks like this release doesn't include the core modules.  Can you please point me to instructions for installing these separately?  In https://github.com/ansible/ansible-modules-core the readme says `There should be no need to install this repo separately as it should be included in any Ansible install using the official documented methods.`

**Comment by jimi-c** [comment]
@pixelrebel I just grabbed the rc2 tar from here (http://releases.ansible.com/ansible/), and checked to make sure the modules were there:

<pre>
$ find ansible-2.0.0/lib/ansible/modules/ -name "*.py" | wc -l
526
</pre>

Are you sourcing the `hacking/env-setup` script?

**Comment by pixelrebel** [comment]
Thanks @jimi-c, I was using the `tar` from github releases.  It's working now.

I can also confirm ansible-pull is working properly in 2.0.0-rc2 just as it was in 1.9.4.  I will be testing new features shortly.

**Comment by jimi-c** [comment]
@pixelrebel excellent, thanks for the follow up!
