### ISSUE TITLE
per task silencing of warnings

### ISSUE THREAD

**Issue by phy1729** [ansible/ansible#13468]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 2.0.0 (detached HEAD 958da26d18)
##### Ansible Configuration:

None.
##### Environment:

N/A
##### Summary:

If I have an task like

```
shell: curl -s http://some.url.example/foo | sed '/asdf /!d;s///'
```

I get a bright pink warning

```
[WARNING]: Consider using get_url module rather than running curl
```

It'd be nice if this warning could be turned off on a per task basis. The warnings are useful in general, but sometimes they are false positives and the author knows better.
##### Steps To Reproduce:

```
- shell: curl -s http://some.url.example/foo | sed '/asdf /!d;s///'
  ignore_warnings: yes
```

Would not have the bright pink warning.

**Comment by quentinsf** [comment]
Agreed - I've just switched to 2.0, and I get warnings when I use 'git' to do something that the git module can't do, and 'tar' to do something that the unarchive module can't do.

It would be very nice to be able to override them.

**Comment by CodeSturgeon** [comment]
It would be nice to have the warnings suppressed explicitly as above, but it can be done inline. Just add `warn=no` to the the command/shell play. It's in the [config docs](http://docs.ansible.com/ansible/intro_configuration.html#command-warnings) and it's a listed in the [command](http://docs.ansible.com/ansible/command_module.html) and [shell](http://docs.ansible.com/ansible/shell_module.html) modules. I mention that here as I found this issue before the docs.

**Comment by dmromanov** [comment]
@quentinsf In this case it would be better to fix modules so they would not throw warnings on tasks they could not do. Silencing them would be just a work-around.

In addition it would be great if `warn=no` would be moved from module-level API (shell, command) to a global level (correct me if I am wrong) like `become`. So it could be used on a specific task as well on an entire playbook

**Comment by bcoca** [comment]
shell has 'warn' option since 1.8 that controls this, closing as 'already implemented'

**Comment by mahemoff** [comment]
Example usage:

```
- name: Check the folder
  shell: ls ./somedir
  args:
    warn: false
```

[shell docs](https://docs.ansible.com/ansible/shell_module.html)
