### ISSUE TITLE
Ansible ignore_errors construct is not really deprecated, despite the documentation states so.

### ISSUE THREAD

**Issue by fangchin** [ansible/ansible#1347]
In **[Ignoring Failed Commands](http://ansible.cc/docs/playbooks2.html?highlight=ignore_errors)**,  there is a short note, quoted "_Deprecated since version 0.6._".

But this construct is quite useful in many places.  As such, after a few email exchanges on the ansible mailing list, the aforementioned quoted statement is deemed as a documentation error.  Please fix.

**Comment by mpdehaan** [comment]
Should say added in 0.6 I believe

-- Michael

**Comment by fangchin** [comment]
Double checked the latest `CHANGELOG.md`, please see below.  So, we recommend to update the [official doc](http://ansible.cc/docs/playbooks2.html#ignore_errors) to eliminate confusion.

```
0.6 "Cabo" -- August 6, 2012

playbooks:

[...]
* ignore_errors: True on a task can be used to allow a task to fail and not stop the play
* with_items with the apt/yum module will install/remove/update everything in a single command
```

**Comment by mpdehaan** [comment]
fixed
