### ISSUE TITLE
Mark added/removed newlines in --diff mode, like in "git diff" output [feature_idea].

### ISSUE THREAD

**Issue by selivan** [ansible/ansible#13492]
If only newline symbol was added/removed, output of --diff mode may be confusing for user:

```
TASK: [common | install /etc/timezone] **************************************** 
--- before: /etc/timezone
+++ after: /tmp/tmpuzXAH7
@@ -1 +1 @@
-Asia/Baghdad
+Asia/Baghdad
changed: [redmine]
```

This leads to problems like this: https://github.com/ansible/ansible/issues/13476 https://github.com/ansible/ansible/issues/8443

I think, it would be more convenient and error-prone to explicitly mark newline add/remove in --diff output, like `git diff` does.

**Comment by mgedmin** [comment]
I think #14094 is a duplicate.

**Comment by bcoca** [comment]
closing as per above
