### ISSUE TITLE
Notifications don't run if a subsequent task fails

### ISSUE THREAD

**Issue by mnot** [ansible/ansible#1350]
I often see a notification not run because a subsequent task fails, bailing out everything else.

The problem is that on the next run, the notification isn't triggered, because the task that generates it doesn't change anything.

This comes up in testing more often than elsewhere.

I.e., notifications from tasks that succeed should always run, regardless of the success of subsequent (unrelated) tasks.

**Comment by mpdehaan** [comment]
asked you to comment on the other one

**Comment by mpdehaan** [comment]
comments added to other ticket...these need to be considered together
