### ISSUE TITLE
when: statement replaces a variable with the value of another

### ISSUE THREAD

**Issue by alvarogmj** [ansible/ansible#13506]
##### Issue Type:

Bug Report
##### Ansible Version:

Latest beta, from the downloads page (ansible-2.0.0-0.7.rc2.tar.gz)
##### Ansible Configuration:

Stock ansible.cfg + json facts cache enabled
##### Environment:

RHEL 6, python2.6
##### Summary:

Value of a variable gets changed to the value of another when using includes / when statements.
##### Steps To Reproduce:

Run ansible-playbook with the attached test files (changing inventory and host_vars to point to a real server), playbook file is "node_servers.yml"

```
ansible-playbook -i inventory node_servers.yml
```
##### Expected Results:

With the test case, the playbook should fail with the following message:

```
TASK [node_servers : Stop nodes] ***********************************************
fatal: [avnvld01.sgdcelab.sabre.com]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check '{{ 'not_found' != hostvars[inventory_hostname]['app_info_' ~ customer]['version'] }}' failed. The error was: ERROR! 'dict' object has no attribute u\"app_info_test\""}
```
##### Actual Results:

The value of 'customer' is replaced by the value of the 'hosts' dictionary, loaded from 'test/config/vars.yml' by an include task in install.yml:

```
TASK [node_servers : Stop nodes] ***********************************************
fatal: [avnvld01.sgdcelab.sabre.com]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check '{{ 'not_found' != hostvars[inventory_hostname]['app_info_' ~ customer]['version'] }}' failed. The error was: ERROR! 'dict' object has no attribute u\"app_info_{u'name': u'server2.example.com', u'port': 9000}\""}
```

Repository with test files:
https://github.com/alvarogmj/ansible-test-case/tree/master/issue13506

**Comment by alvarogmj** [comment]
I'm unable to upload a zip file, so I'll create a repository for the test code.

**Comment by alvarogmj** [comment]
I was able to reduce the test case further: the first thing I tried with this code today was to remove the 'app_info_' part in the when clause (leaving just "customer" instead of "'app_info_' ~ customer"), and got the same effect.

**Comment by bcoca** [comment]
I have not been able to reproduce, please let us know when you can provide the test case.

**Comment by alvarogmj** [comment]
https://github.com/alvarogmj/ansible-test-case/tree/master/issue13506 is the test case. Running "ansible-playbook -i inventory node_servers.yml" from the "ansible" directory displays the error.

**Comment by alvarogmj** [comment]
I found a work-around: use "set_fact" before the problematic blocks:
- set_fact: customer="{{ customer }}"

Not ideal, but it allows me to continue working while the root cause is found.

**Comment by alvarogmj** [comment]
I'd like to know if this will be accepted as a bug or is a side-effect of doing something wrong, so I can avoid the problem entirely.

**Comment by bcoca** [comment]
so the issue is not with `when`, but you nesting `with_items`, the 2nd invocation overwrites `item` of the first, as documented the way to use both vars is using `set_fact` as you already figured out.

https://docs.ansible.com/ansible/playbooks_loops.html#loops-and-includes
