### ISSUE TITLE
Dynamic inventories with command options does not work

### ISSUE THREAD

**Issue by sebi-hgdata** [ansible/ansible#13516]
Using ansible 2.0.0 - 157230c3e83731e :
It seems that specifying a dynamic inventory and parameters do not work as descried at http://docs.ansible.com/ansible/intro_dynamic_inventory.html#other-inventory-scripts .

I have a python dynamic inventory file that I want to use like :  --inventory-file="inventories/local/hosts --profile"

**Comment by sivel** [comment]
You are correct.  That does not work and I am not sure it ever did. Those docs should be changed.

The correct way to get external provided options into the inventory is either by a config file or env vars.

**Comment by bcoca** [comment]
already fixed via dcedfbe26c2aacc901fe5ef84b51103feb92990f
