### ISSUE TITLE
git - Failed to pull the private repository

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#1352]
I'm using ansible git module to pull my private repository. But it's not working and not even showing any errors. This is my code.

```
- name: Pull notikum repository
  action: git repo=git@github.com:rkumarnirmal/Notikum.git dest=~/Notikum
```

I've also set my SSH and added the keys to Github.

**Comment by mpdehaan** [comment]
Please ask about this one on the mailing list.

There's not enough information here and it's easier to discuss with others.
