### ISSUE TITLE
Occur 'module does not exist' error when use the include in playbook, two python version exist on system

### ISSUE THREAD

**Issue by beafuture** [ansible/ansible#13539]
Hi guys:

I install ansible in centos5 system,and there are two python version, one is python2.4 (no  MySQLdb module) ,it's the default, another is python2.6 installed by myself (including  MySQLdb module).
I install pip use python2.6, and then install ansible use pip, all works is fines. but when I use include in playbook will occur error ，because the file included to playbook is run with python2.4,It is missing MySQLdb modules in python2.4.
example playbook:

```
- name: test
  hosts: all
  user: root
  gather_facts: false
  tasks:
    - include: mysqldump.yml
```

mysqldump.yml:

```
- name: dump db template
  mysql_db: login_host=10.1.2.3 login_port=3306 login_user=root login_password=123456 state=dump name=db_template target=/tmp/template.sql
  run_once: true
  delegate_to: '127.0.0.1'
```

Run this playbook will get this error:
failed: [10.1.2.3 -> 127.0.0.1] => {"failed": true}
msg: the python mysqldb module is required

Is this a bug?

**Comment by sivel** [comment]
You need to specify the path to python26 via the `ansible_python_interpreter` inventory variable as described at http://docs.ansible.com/ansible/faq.html#how-do-i-handle-python-pathing-not-having-a-python-2-x-in-usr-bin-python-on-a-remote-machine
