### ISSUE TITLE
Tilde expansion fails with copy module

### ISSUE THREAD

**Issue by lukehoersten** [ansible/ansible#13531]
- **Issue Type:** Bug Report
- **Ansible Version:** ansible-2.0.0-0.7.rc2
- **Environment:** Ubuntu Server 15.04 (Vivid Vervet) cloud image on AWS EC2
- **Summary:** Running the copy module with the dest requiring tilde expansion results in an index out of bounds error.
- **Steps To Reproduce:**
  Run the copy module with a tilde expansion in the dest path.

The following is output from `-vvv` run of the `copy` module with `~project-build/repo` as the dest.

```
[...]
internal echo ~project-build
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/process/worker.py", line 135, in run
    shared_loader_obj,
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 402, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/action/copy.py", line 148, in run
    dest = self._remote_expand_user(dest)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 336, in _remote_expand_user
    initial_fragment = data['stdout'].strip().splitlines()[-1]
IndexError: list index out of range
```

Manually expanding the tilde to `/home/` avoids the issue.

[Here's the offending line.](https://github.com/ansible/ansible/blob/eefb4931dd4e9489ff68aa332493e5ef2468d121/lib/ansible/plugins/action/__init__.py#L336)

**Comment by bcoca** [comment]
can you test with latest stable-2.0 or devel? i cannot reproduce this issue on those.

**Comment by ueg1990** [comment]
why are you using ~project-build/repo instead of ~/project-build/repo. isnt the former incorrect?

**Comment by bcoca** [comment]
both are correct, but mean different things, `~project-build` means home of 'project-build' user, `~/project-build` means 'project-build' subdirectory of the home of the current user.

**Comment by lukehoersten** [comment]
@bcoca please link me to the package you want me to try.

**Comment by bitmensch** [comment]
@LukeHoersten You can usually install the `devel` version @bcoca is referring to via:

```
pip install git+https://github.com/ansible/ansible.git@devel#egg=ansible
```

**Comment by lukehoersten** [comment]
Looks like it's fixed in the version you provided @benjixx  - thanks.
