### ISSUE TITLE
Not working $group_names

### ISSUE THREAD

**Issue by alopropoz** [ansible/ansible#1354]
only_if condition like " 'webservers' in $group_names " becomes " 'webservers' in webservers " when vars are substituted and this causes an error. Offending commit is dfee6e19cad77c8f19fa0dcc558b1d1254963126

**Comment by mpdehaan** [comment]
Templating substitution isn't going to work here.   We're going to need to fix this with the proposed 'when' operator in 0.9.

**Comment by mpdehaan** [comment]
See #1348.

There's nothing wrong with the group_names variable, but rather it is being expanded in only_if differently than elsewhere.  We could possibly template only_if differently.   So, I'm reconsidering whether a fix may be possible, it might.

**Comment by mpdehaan** [comment]
See if 25162c9 (now pushed) fixes this for you.  It should.

**Comment by alopropoz** [comment]
Yes, now it works like before, thank you.
