### ISSUE TITLE
ansible-pull should support --skip-tags

### ISSUE THREAD

**Issue by DSpeichert** [ansible/ansible#13541]
Issue Type: Feature Idea
Ansible Version: ansible 1.9.2
  configured module search path = None

Ansible Configuration: None
Environment: N/A

Summary:

ansible-pull should allow "--skip-tags" flag just as ansible-playbook does. It does support "--tags" and the reverse would be very helpful.

Steps To Reproduce:

I believe this features is equally useful as in ansible-playbook command.

Expected Results: N/A
Actual Results: N/A

**Comment by bcoca** [comment]
already done in 2.0
