### ISSUE TITLE
variables in ansible_managed should be available for use in playbooks

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#13540]
The default configuration for ansible_managed is:
`ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}`

The variables uid, host, and file can't be used directly in playbooks.

If you wanted to use the uid variable, you have to run a local task to obtain it:

<pre>---
- hosts: all

  tasks:
   - name: get local username
     local_action: command /usr/bin/whoami 
     register: local_username
     connection: local

   - name: output value of {{ local_username }}
     debug: msg="Local username is {{ local_username.stdout }}"
</pre>

Can we make these variables available for use in playbooks ?

**Comment by bcoca** [comment]
no need to do a local action, you can get the info through lookups

```
local_user_name: {{ lookup('env', 'USER') }}
hostname: {{ lookup('env', 'HOSTNAME') }}
```

file makes no sense outside of template

**Comment by ghost** [comment]
I didn't know that was possible. That works so I'll just use that. Thanks for the help.
