### ISSUE TITLE
bug: passing variables to playbook include is not working

### ISSUE THREAD

**Issue by nicolaasuni** [ansible/ansible#1355]
The following include line is set on a file that is included on another playbook:

 "- include: playbook.yml varname=varvalue"

fails with the following message:

 ERROR: file not found: playbook.yml varname=varvalue

The playbook.yml file exist and works if I remove the varname=varvalue from the include.

I am using the Ansible version of
Tue Oct 16 20:16:40 2012 -0700

on CentOS 6.3 updated

**Comment by mpdehaan** [comment]
Not a bug, we never said it worked -- that's only true of imported tasks.

There is an open ticket to add this in 0.9.
