### ISSUE TITLE
[2.0-rc1] ansible-galaxy no longer respects path in requirements file

### ISSUE THREAD

**Issue by lae** [ansible/ansible#13563]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.0.0 (f2225395f96d5c309dddc66fafd984862d99b708)
##### Ansible Configuration:

no changes
##### Environment:

Arch Linux
##### Summary:

My existing requirements.yml files from using 1.9.4 and older now don't install roles into their specified directories, but instead tries to use the global roles directory.
##### Steps To Reproduce:

Just using a random role from GitHub:

```
$ cd $(mktemp -d)
$ cat >requirements.yml <<<EOL
- src: git+https://github.com/sfromm/ansible-epel.git
  name: epel
  path: ./
EOL
$ ansible-galaxy install -r requirements.yml 
```
##### Expected Results:

```
$ ansible-galaxy install -r requirements.yml 
- executing: git clone https://github.com/sfromm/ansible-epel.git epel
- executing: git archive --prefix=epel/ --output=/tmp/tmp4UEDr0.tar HEAD
- extracting epel to ./epel
- epel was installed successfully
```
##### Actual Results:

```
$ ansible-galaxy install -r requirements.yml 
- extracting epel to /etc/ansible/roles/epel
 [WARNING]: - epel was NOT installed successfully: ERROR! Could not update files in /etc/ansible/roles/epel: [Errno 13]
Permission denied: '/etc/ansible/roles'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by chrrrles** [comment]
How are you setting roles-path for ansible-galaxy.  Have you tried this?:

```
$ ansible-galaxy install -r requirements.yml --roles-path=./
```

**Comment by lae** [comment]
Using --roles-path works as described. Is the path parameter in requirements.yml being deprecated in favor of this flag, though? It's still documented here: https://github.com/ansible/ansible/blob/devel/docsite/rst/galaxy.rst#advanced-control-over-role-requirements-files

**Comment by jimi-c** [comment]
cc @chouseknecht

**Comment by chrrrles** [comment]
@lae Ahhh, I see it now.  I believe the referenced PR will fix your bug, may you test it also?

**Comment by chrrrles** [comment]
cc @docschick

**Comment by chouseknecht** [comment]
I tested with the code change found in PR 13577.  Adding 'path' back into the VALID_SPEC_KEYS list in requirements.py works. 

Here's my ansible.cfg file pointing roles_path to a directory:

```
[defaults]
roles_path=~/projects/roles
```

Here's my requirements.yml specifying an explicit path:

```
$ cat requirements.yml
- src: chouseknecht.ansible-grub
  path: ./
```

Running ansible-galaxy with -r requirements.yml installed the role to the explicit  path as expected:

```
$ ansible-galaxy install -s https://galaxy-qa.ansible.com -r requirements.yml
- downloading role 'ansible-grub', owned by chouseknecht
- downloading role from https://github.com/chouseknecht/ansible-grub/archive/v0.1.1.tar.gz
- extracting chouseknecht.ansible-grub to ./chouseknecht.ansible-grub
- chouseknecht.ansible-grub was installed successfully
```

**Comment by docschick** [comment]
Doesn't look like a docs change is needed and I confirmed this with @chouseknecht.  I'm removing the docs_report label.

**Comment by chrrrles** [comment]
https://github.com/ansible/ansible/commit/851c0058b148ce041af5ca5c9fbdf25ff854cf8f

**Comment by chrrrles** [comment]
Should we keep `path` in role's yaml spec even though it allows the requirements author to overwrite arbitrary paths?

**Comment by bcoca** [comment]
this is not a feature we want to support, it was introduced in 1.9 but I don't think any admin wants the requirements file setting the 'local' path to install for users, specially dangerous is the "./" in the examples as you have no clue on where a user is executing `ansible-galaxy` from.

**Comment by jagibson** [comment]
Bummer. This was handy for downloading a versioned inventory directory into the root of the playbook.

**Comment by Caroga** [comment]
Really? This is kinda harsh. Many of my projects are depending on this feature, as each project contains there own build folder where the roles are supposed to be installed, which is now broken..

**Comment by lae** [comment]
Use --roles-path, my use case is similar to yours and that's what I'm doing.

**Comment by Caroga** [comment]
I will try and use that, thank you for the quick tip!

**Comment by LadyNamedLaura** [comment]
This really breaks a lot of setups where it is wanted to keep the roles inside the tree used.
If it is a problem of "you have no clue on where a user is executing ansible-galaxy from" (as @bcoca says) 
Then just fix it so that the paths are always relative to the requirements file.

Don't go deleting features if the current implementation is just slightly broken, fix the implementation!

**Comment by lae** [comment]
@SimonPe You are still able to keep roles inside of the tree. Please see previous comments.

**Comment by LadyNamedLaura** [comment]
@lae: well, but I can no longer control the path from inside a file, checked into git, I'll have to educate all developer of which --roles-path to use in which trees. I am not going to do that.

I am not saying developers are stupid, but they just don't care. They do a git clone/pull of the tree I give them, can run ansible-galaxy -r requirements.yml, and then ansible-playbook whatever they want/need to deploy their app. (and yes having them run ansible-galaxy was already hard enough, they still forget it, luckily they don't need to do it often.)

**Comment by lae** [comment]
@SimonPe Ah. I actually just have a script in the playbook that does the roles initialization/upgrade called update_roles.sh, so nothing really changed for us. e.g.

```
#!/bin/bash
cd roles
ansible-galaxy install -r requirements.yml --force -p ../galaxy_roles/
ls -1 ../galaxy_roles | xargs -L1 -I{} ln -sfv ../galaxy_roles/{} {}
```

(I have a separate directory to store galaxy roles so that they don't get committed to git/I don't have to specify each and every role in .gitignore)

That said, I've been moving towards actually making roles installable to and usable from /etc/ansible/roles in the past few months, so I'm really only using this for legacy playbooks.

**Comment by retr0h** [comment]
> this is not a feature we want to support, it was introduced in 1.9 but I don't think any admin wants the requirements file setting the 'local' path to install for users, specially dangerous is the "./" in the examples as you have no clue on where a user is executing ansible-galaxy from.

I love how these assumptions are made without consulting the community.  As the person who introduced this change into 1.9, I find this rather annoying.

**Comment by dccampbell** [comment]
The hackish solutions to utilizing remote roles are bad enough as it is, this is yet another hoop to jump through. It already feels absurd there's no way to have a playbook just automatically download it's requirements, now on top of reminding everyone they have to run galaxy first they have to pass a path argument along with it. We're going to end up writing bash scripts just to execute our playbooks...

**Comment by lae** [comment]
That is effectively what I just did, isn't it. (see above)

**Comment by dccampbell** [comment]
It is, and my implication was that it's a pretty big red flag that something is wrong with the workflow when that's the necessary solution.

**Comment by dfarrell07** [comment]
This broke OpenDaylight automation, and I imagine many other Ansible downstreams. Feels like you're playing pretty fast and loose with backwards incompatible changes.

**Comment by via** [comment]
There are cases where you might want to have different paths for different roles, which was part of our use case for the path: setting in the requirements file.  Dropping support for this means we need multiple ansible-galaxy instances each with different -p options.  It shouldn't hurt anyone to have the option still work, why was this decision made?

**Comment by jagibson** [comment]
@bcoca can you explain what you mean by, "I don't think any admin wants the requirements file setting the 'local' path to install for users." 

We almost exclusively run ansible-galaxy from the top-level of the individual playbook directory as I'm sure is common (via a Jenkins job).  Since you are specifying the path in requirements.yml anyway, I don't see the danger except perhaps for dependent roles.  If the roles aren't in the expected place relative to the playbook they should fail to load.

For me it's nice if you loading your inventory as just another role from galaxy.  It seems more intuitive to be able to put the inventory directory at the root of the playbook rather than inside or the roles directory.  It's also easier for someone new to ansible to understand what's going on.

Perhaps a whitelist could be specified in ansible.cfg for allowing multiple alternate paths besides the roles directory?

**Comment by dccampbell** [comment]
IMHO, package/dependency management has been solved well already by a number of tools, and there's no good reason not to just imitate them. My team was a bit baffled when Galaxy wasn't as straight-forward and simple to use as tools like Composer.

https://getcomposer.org/doc/00-intro.md#dependency-management
http://bundler.io/rationale.html
https://code.facebook.com/posts/1840075619545360/yarn-a-new-package-manager-for-javascript/

**Comment by beporter** [comment]
I found this thread trying to make galaxy behave like I expected. I'm new to Ansible but I know php and node. It feels to me like Galaxy as a whole could learn a lot from npm(/yarn) and composer. Neither one gets everything right, but they've already faced and solved a lot of these problems. For my part, I plan to back away slowly and let Galaxy mature some more before I consider it again. 😞

**Comment by juandiego26** [comment]
@chrrrles worked for me 👍

**Comment by chadswen** [comment]
I'm about two years too late for suggestions here, but for my own curiosity was something like [directory variables](http://docs.ansible.com/ansible/latest/playbooks_variables.html#magic-variables-and-how-to-access-information-about-other-hosts) considered for usage inside requirements.yml as a replacement for relative paths?

As in:
```yaml
- src: https://example.com/example1.git
  version: master
  name: example1
  scm: git
  path: "{{ requirements_dir }}/example_roles"
```

**Comment by retr0h** [comment]
I ended up writing [gilt](http://gilt.readthedocs.io/en/latest/).  I don't want to use roles uploaded to galaxy anyways, since they are usually behind or not released properly, instead I prefer to stick to git branches, tags, or shas.

Also, gilt allows for pathing in the config, and plucking out files inside a repo, which don't need to conform to the meta/main.yml structure galaxy requires.  This means we can manage libraries, plugins, playbooks, and monolith repos with the same tooling.

**Comment by rafi** [comment]
I switched to using [Git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules).. Simple and efficient.

**Comment by jagibson** [comment]
For my particular issue 2.4 solves the problem since it can support multiple inventory locations.
