### ISSUE TITLE
_do_handler_run() takes at least 5 arguments (5 given)

### ISSUE THREAD

**Issue by cmacrae** [ansible/ansible#13560]
##### Issue Type:

Bug Report
##### Ansible Version:

`v2.0.0-0.7.rc2`
##### Ansible Configuration:

`ansible.cfg`

``` ini
[defaults]

remote_tmp     = $HOME/.ansible/tmp
pattern        = *
forks          = 16
poll_interval  = 15
sudo_user      = root
remote_user    = root
transport      = smart
remote_port    = 22
module_lang    = C
gathering = implicit
roles_path    = roles/external:roles/internal
host_key_checking = False
sudo_exe = sudo
timeout = 10
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}

[accelerate]

accelerate_port = 5099
accelerate_timeout = 30
accelerate_connect_timeout = 5.0
accelerate_daemon_timeout = 30
```
##### Environment:

Control node OS: Fedora 23
Destination node OS: CentOS 7
##### Summary:

A role I wrote and maintain has a `notify` for a `get_url` task.
This notifies a handler which includes a playbook.
When a change for the `get_url` task triggers the handler, the following is returned:

```
Unexpected Exception: _do_handler_run() takes at least 5 arguments (5 given)
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 84, in <module>
    sys.exit(cli.run())
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 149, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 149, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 249, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 205, in run
    self._execute_meta(task, play_context, iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 641, in _execute_meta
    self.run_handlers(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 528, in run_handlers
    result = self._do_handler_run(handler, handler_name, iterator=iterator, play_context=play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 592, in _do_handler_run
    notified_hosts=included_file._hosts[:],
TypeError: _do_handler_run() takes at least 5 arguments (5 given)
```
##### Steps To Reproduce:

[The `get_url` task with the `notify`](https://github.com/RocketChat/Rocket.Chat.Ansible/blob/ansible_2.0/tasks/main.yml#L79)
[The handler](https://github.com/RocketChat/Rocket.Chat.Ansible/blob/ansible_2.0/handlers/main.yml#L6)
[The playbook included by the handler](https://github.com/RocketChat/Rocket.Chat.Ansible/blob/ansible_2.0/tasks/upgrade.yml)

The `- meta: flush_handlers` task does not affect this in any way. The same happens with or without it, or regardless of its position in the playbook.
##### Expected Results:

The handler should run, include the playbook, and execute the tasks within said playbook.
##### Thanks

Thanks in advance for any help on this! Please do let me know if there's any further information I can provide that would aid investigation. :+1:

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by cmacrae** [comment]
Awesome, thanks!
