### ISSUE TITLE
[Feature Idea] diff output for lineinfile with --diff

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#13565]
| Breif |  |
| --- | --- |
| Issue Type: | Feature Idea |
| Ansible Version: | 1.9.4 (latest pypi) |
| Ansible Configuration: | nocows |
| Environment: | Ubuntu LTS Based / Any |
| Summary: | `diff` mode support for `lineinfile` |
##### Ansible Version verbatim output

```
ansible 1.9.4
  configured module search path = None
```
##### Ansible Configuration

```
+[defaults]
+nocows = 1
```
##### Environment

Host Ubuntu14.04 or derivities (Linux Mint Cinnamon 17.2) / Target Ubuntu >= 12.04
## Summary

The core module `lineinfile` does not support the diff flag/mode. This leads to deploying changes with total blindness to what was removed and changed; Offering only what was intended to be added as described by the original lineinfile call.
## Reproduction

Steps To Reproduce:
1. Use core module `lineinfile` to change a file with the `--diff` flag/mode.

Expected Results:
- Diff-style output of what changed (similar to templates).

Actual Results:
- No diff or change details displayed.

**Comment by towolf** [comment]
The above PR should fix this issue.

**Comment by towolf** [comment]
You shouldn't have closed this prematurely. The pull request mentioned above hasn't been merged yet.

**Comment by ghost** [comment]
:bow: my mistake
