### ISSUE TITLE
ansible_ssh_common_args is not respected

### ISSUE THREAD

**Issue by metakermit** [ansible/ansible#13571]
I am trying to set a beacon server (ssh proxy to jump through to get to the final destination) and I tried to follow your recommendation from [this FAQ entry](http://docs.ansible.com/ansible/faq.html#how-do-i-configure-a-jump-host-to-access-servers-that-i-have-no-direct-access-to) to declare `ansible_ssh_common_args` as the ssh/scp/sftp argument. It did not change the ssh commands ansible issues, though, which results in SSH errors:

```
PLAY [boplive] ****************************************************************
skipping: no hosts matched

PLAY [boplive_physical] *******************************************************

GATHERING FACTS ***************************************************************
<localhost> ESTABLISH CONNECTION FOR USER: root
<localhost> REMOTE_MODULE setup
<localhost> EXEC ssh -C -tt -vvv -F ssh.cfg -o StrictHostKeyChecking=no -o Port=XXXX -o IdentityFile="/Users/kermit/.ssh/id_rsa" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 localhost /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1450276023.46-229566512191722 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1450276023.46-229566512191722 && echo $HOME/.ansible/tmp/ansible-tmp-1450276023.46-229566512191722'
fatal: [BopsterNuc] => SSH Error: Can't open user config file ssh.cfg: No such file or directory
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

TASK: [common | timezone | Configure the Timezone] ****************************
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/kermit/bopidy.retry

BopsterNuc                 : ok=0    changed=0    unreachable=1    failed=0
```

I would expect there to be an additional option `-o "ProxyCommand ssh myuser@beacon-server nc %h %p"` which I specified in the appropriate _group_vars/<group_name>_ file.

I managed to overcome the problem by following [this tutorial](https://medium.com/@paulskarseth/ansible-bastion-host-proxycommand-e6946c945d30#.tb7jdawdw) (the official docs are very vague on this topic, BTW). The suggested solution, however requires me to specify a global ssh.cfg file. I would rather just apply these settings for groups of hosts, because I use the same playbook to deploy some VMs which are publicly accessible too (so avoiding proxying makes things faster).

Ansible version 1.9.4.

**Comment by bcoca** [comment]
ansible_ssh_common_args is a 2.0 feature

**Comment by bcoca** [comment]
its documented here:

http://docs.ansible.com/ansible/faq.html#how-do-i-configure-a-jump-host-to-access-servers-that-i-have-no-direct-access-to

but we should also add here:
http://docs.ansible.com/ansible/intro_inventory.html#list-of-behavioral-inventory-parameters

**Comment by metakermit** [comment]
OK, so all of the docs.ansible.com documentation applies to 2.0 already? Because on the downloads page I only saw some rc versions of 2.0 so far. Do you perhaps know how can I upgrade to 2.0 using pip? It always keeps me on the 1.9.x versions when I do `pip install --upgrade ansible` and `pip install ansible==2.0` complains that it can't find that version.

**Comment by metakermit** [comment]
Thanks for the link, but I already included that FAQ link in the first post ;)

**Comment by bcoca** [comment]
it does say in the faq `Ansible 2`, that is why i included it again, but it should also appear in inventory intro.

**Comment by metakermit** [comment]
ok, thanks!
