### ISSUE TITLE
Not skipping with_items

### ISSUE THREAD

**Issue by iwai** [ansible/ansible#13598]
Top of role in meta/main.yml

```

---
allow_duplicates: yes
dependencies:
  - { role: "{{ common_roles }}/common.amzn", when: "ansible_distribution == 'Amazon'" }
```

In common.amzn role

```
  - debug: var=monitor

  - copy: src="monitor/{{ item }}.sh" dest=/home/scripts/ owner=root group=root mode=0775
    with_items: "{{ monitor.processes }}"
    when: monitor is defined
```

This playbook locate not a Amazon distribution and undefined monitor variable.

excuted report is this

```
TASK: [{{ common_roles }}/common.amzn | debug var=monitor] ******************** 
skipping: [127.0.0.1]

TASK: [{{ common_roles }}/common.amzn ] *************** 
fatal: [127.0.0.1] => with_items expects a list or a set

FATAL: all hosts have already failed -- aborting
```

```
# ansible --version
ansible 1.9.4
# cat /etc/redhat-release 
CentOS release 6.7 (Final)
```

**Comment by bcoca** [comment]
not a bug, you cannot use `when` to avoid `with_items` running as `when` evaluates per item. use this instead:

`with_items: "{{ (monitor|default({})).processes|default([]) }}"`

**Comment by travisdetert** [comment]
I think most would agree this behaves like a bug, as the assumption is that when should see this doesn't exist, and thus never reach evaluating with_items

**Comment by dannyman** [comment]
As a user, I would find it advantageous if the error message dropped the hint that @bcoca does right here.
