### ISSUE TITLE
debug command fails when msg is undefined, despite check 'when: msg is defined'

### ISSUE THREAD

**Issue by daraosn** [ansible/ansible#13599]
#### HEAD

Ansible 1.9.4
OSX 10.10.5
Python 2.7.10

Ansible configuration:

```
[defaults]
roles_path=playbook/galaxy-roles:playbook/roles
inventory=playbook/inventory
host_key_checking = False

gathering = smart
fact_caching = jsonfile
fact_caching_connection = /tmp/ansible_facts
fact_caching_timeout = 86400

[privilege_escalation]
become=True
```
#### BODY

I have a role called 'debug', it has a task:
`roles/debug/tasks/main.yml`

```

---
- debug:
    msg: "{{ msg }}"
    when: msg is defined
```

When I call that role from another one, it will fail if `msg` is not defined, despite the check with `when`.

`roles/another_role/metas/main.yml`

```

---
dependencies:
  - role: debug
    msg: 'test'

  - role: debug

  - role: debug
    msg: 'test2'
```

The first time the role is called it works fine, for the second it fails though, so the third is not run.

I was expecting the role to run without problems if `msg` was undefined.

The error using `vvvv` verbose output:

```
TASK: [debug | debug ] ********************************************************
<localhost> ESTABLISH CONNECTION FOR USER: ubuntu
ok: [localhost] => {
    "msg": "test"
}

TASK: [debug | debug ] ********************************************************
<localhost> ESTABLISH CONNECTION FOR USER: ubuntu
fatal: [localhost] => One or more undefined variables: 'msg' is undefined

FATAL: all hosts have already failed -- aborting
```

---

If instead of using `debug` I use, let's say, `command: "echo {{ msg }}"`  the playbook runs as expected:

`roles/debug/tasks/main.yml`

```

---
- command: "echo {{ msg }}"
  when: msg is defined
```

**Comment by bcoca** [comment]
your 'when' is incorrectly indented and Ansible is passing it as a parameter to debug and not evaluating it:

```
- debug:
    msg: "{{ msg }}"
  when: msg is defined
```

**Comment by daraosn** [comment]
@bcoca yeah, that fixes it, thanks for clarifying. I'm closing the issue.
