### ISSUE TITLE
multiple inventory sources feature yields empty host list

### ISSUE THREAD

**Issue by gilday** [ansible/ansible#13604]
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.4
##### Ansible Configuration:

no changes
##### Environment:

CentOS 7
##### Summary:

[Using Multiple Inventory Sources](http://docs.ansible.com/ansible/intro_dynamic_inventory.html#using-multiple-inventory-sources) states that users should be able to configure ansible to use a directory of static and / or dynamic inventories. Setting the inventory parameter to a directory yields an empty host list.
##### Steps To Reproduce:

```
mkdir inventories
echo "foo" > inventories/foo.ini
echo "bar" > inventories/bar.ini
ansible all -i inventories -m debug -a "var=inventory_hostname"
```
##### Expected Results:

ansible prints two debug messages - one for each host
##### Actual Results:

ansible prints "No hosts matched"

**Comment by bcoca** [comment]
remove the .ini extension, it gets ignored in directories as they are normally the config file for dynamic inventory scripts.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
