### ISSUE TITLE
Parallel tasks

### ISSUE THREAD

**Issue by chengchengmu** [ansible/ansible#13601]
Hello,

I have been trying to understand how to make ansible run tasks in parallel and why it does not really work for me.

To test it I have a little playbook : 

```

---
- hosts: test
#  serial: 3
  tasks:

  - name: show time
    shell: echo $(date) && sleep 5
```

In the /etc/ansible/ansible.cfg, I have `forks          = 50` and my ansible version is `1.9.4
`.
I launch this playbook against 3 hosts, and I have this result : 

```
  ansible-playbook -vv -i hosts par.yml 

PLAY [test] ******************************************************************* 

GATHERING FACTS *************************************************************** 
<104.155.33.255> REMOTE_MODULE setup
<104.155.44.118> REMOTE_MODULE setup
<104.155.72.91> REMOTE_MODULE setup
ok: [104.155.33.255]
ok: [104.155.44.118]
ok: [104.155.72.91]

TASK: [show time] ************************************************************* 
<104.155.44.118> REMOTE_MODULE command echo $(date) && sleep 5 #USE_SHELL
<104.155.33.255> REMOTE_MODULE command echo $(date) && sleep 5 #USE_SHELL
<104.155.72.91> REMOTE_MODULE command echo $(date) && sleep 5 #USE_SHELL
changed: [104.155.44.118] => {"changed": true, "cmd": "echo $(date) && sleep 5", "delta": "0:00:05.004494", "end": "2015-12-18 16:31:40.506679", "rc": 0, "start": "2015-12-18 16:31:35.502185", "stderr": "", "stdout": "Fri Dec 18 16:31:35 UTC 2015", "warnings": []}
changed: [104.155.33.255] => {"changed": true, "cmd": "echo $(date) && sleep 5", "delta": "0:00:05.006183", "end": "2015-12-18 16:31:45.623886", "rc": 0, "start": "2015-12-18 16:31:40.617703", "stderr": "", "stdout": "Fri Dec 18 16:31:40 UTC 2015", "warnings": []}
changed: [104.155.72.91] => {"changed": true, "cmd": "echo $(date) && sleep 5", "delta": "0:00:05.007773", "end": "2015-12-18 16:31:50.742663", "rc": 0, "start": "2015-12-18 16:31:45.734890", "stderr": "", "stdout": "Fri Dec 18 16:31:45 UTC 2015", "warnings": []}

PLAY RECAP ******************************************************************** 
104.155.33.255             : ok=2    changed=1    unreachable=0    failed=0   
104.155.44.118             : ok=2    changed=1    unreachable=0    failed=0   
104.155.72.91              : ok=2    changed=1    unreachable=0    failed=0   
```

The tasks is executed sequentially on hosts.
By uncommenting the line `#serial: 3`, the result is the same.

What do you think ?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by chengchengmu** [comment]
@bcoca Well this seems rather be big big bug than user question, could you re-open this topic please ?
