### ISSUE TITLE
win_get_url: Doesn't work on ansible v2.x

### ISSUE THREAD

**Issue by dreamcat4** [ansible/ansible#13611]
Works fine on 1.9.4. But not on v2.1.x (devel)

``` yaml
- name: Copy PinTo10.exe to remote machine
  win_get_url:
    url: http://nginx.ansible/windows/apps/freeware/pinto10/PinTo10.exe
    dest: "{{ binpath }}/PinTo10.exe"
    force: no
```

error:

``` sh
TASK [0_base : Copy PinTo10.exe to remote machine] *****************************
task path: /home/id/ansible/windows/roles/0_base/tasks/deps.yml:48
<ga-z170x-g3> ESTABLISH WINRM CONNECTION FOR USER: ansible on PORT 5986 TO ga-z170x-g3
<ga-z170x-g3> EXEC (New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1450542657.72-168838600839135").FullName | Write-Host -Separator '';
<ga-z170x-g3> PUT "/tmp/tmpBM2ERw" TO "C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1450542657.72-168838600839135\win_get_url.ps1"
<ga-z170x-g3> EXEC Try
{
& "C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1450542657.72-168838600839135\win_get_url.ps1"
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1450542657.72-168838600839135" -Force -Recurse -ErrorAction SilentlyContinue }
fatal: [ga-z170x-g3]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"dest": "c:/program files/_bin/PinTo10.exe", "force": false, "url": "http://nginx.ansible/windows/apps/freeware/pinto10/PinTo10.exe"}, "module_name": "win_get_url"}, "msg": "Error downloading http://nginx.ansible/windows/apps/freeware/pinto10/PinTo10.exe to c:/program files/_bin/PinTo10.exe You cannot call a method on a null-valued expression."}

PLAY RECAP *********************************************************************
ga-z170x-g3                : ok=23   changed=1    unreachable=0    failed=1   

```

**Comment by dreamcat4** [comment]
That was after disabling the new powershell `Set-StrictMode`

**Comment by dreamcat4** [comment]
Ping @nitzmahone

It seems I tried this module today just a few hours after you pushed up your recent strict-mode fixes. Was it working for you?

**Comment by nitzmahone** [comment]
Strange, that playbook works fine for me (after changing the URL to something I can reach, of course) in both stable-2.0 and devel branches. Are you sure you updated your modules/core submodule correctly? We don't move the ansible submodule pointer on every commit, so you'd have to explicitly checkout origin/devel or origin/stable-2.0 from ansible-modules-core...

**Comment by dreamcat4** [comment]
Weird. Don't know anymore. I've gone back to 1.9.4 now.

**Comment by dreamcat4** [comment]
Wait minute:

What windows / powershell verisons are you on? I'm on win10 / powershell 5.0

I _think_ my devel checkout today was good. It certainly was from a clean working area. Straight from git. The cmds I ran to get up to speed were:

```
git pull
git submodule update --init --recursive
```

**Comment by nitzmahone** [comment]
Your submodule update process won't get you the absolute latest bits-
you'll get whatever SHA the ansible/ansible submodule pointer was last
pointed at in the current branch. To get the most up to date, instead, do
something like:

cd lib/ansible/modules/core
git fetch
git checkout origin/devel (or origin/stable-2.0, or whatever)

I was testing on 2012R2 + PS4 and 2008R2 + PS3, but shouldn't matter-
there's nothing that breaks in PS5 in there...

**Comment by dreamcat4** [comment]
OK thanks for letting me know. I didn't do that and so you're right... I may have missed your last fix.

Will be sure to retest that way ^^ (manual checkout) on the next occasion. Just leaving v2.0 alone for time being and back on 1.9.4.

**Comment by nitzmahone** [comment]
Going to close this for now- please reopen if you see this behavior again.

Thanks!

**Comment by dreamcat4** [comment]
Hi there.
Come back after a long time not used. Since last time, my system upgraded ansible to official v2.0.0.2 package on ubuntu. Its still happening to me.

Weird.

**Comment by dreamcat4** [comment]
OK this seems to be happening only with `force = no`. Then its probably this one:

https://github.com/ansible/ansible-modules-core/issues/2146

**Comment by dreamcat4** [comment]
Indeed yes. Its solved by that. Just not been released yet on ubuntu. Needs something newer than > v2.0.0.2.

Checking out `devel` branch from git works though. Fix has been merged 23 days ago.
