### ISSUE TITLE
ansible 1.9.4 groups 

### ISSUE THREAD

**Issue by bigHosting** [ansible/ansible#13618]
Trying to get automatic icinga deployment w Ansible working. I have defined gruops in hosts file for different roles and now I'm trying to get the list of roles and copy files. So for each group name I want to copy associated template file.

vars:
groups: "{%- set icinga_groups = [] -%}{% for group in groups|sort if group != 'all' and not 'aggreg' in group and group != 'ungrouped' and group != 'umsrv' -%}{% set _ = icinga_groups.append(group) -%}{%- endfor -%}{{ icinga_groups }}"

In task file:
- debug: msg="{{ icinga.groups }}"
  when: inventory_hostname in groups['monitoring']
  tags: [ monitoring, icinga, icingaconfigs, AB ]
- name: icinga - copy files associated w group names
  template: src={{ templ_dir }}/etc/icinga/objects/hsec-service-{{item }}.cfg.j2 dest=/etc/icinga/objects/hsec-service-{{item}}.cfg  owner=icinga group=icinga mode=0640 backup=n
  with_items: "{{ icinga.groups }}"
  when: inventory_hostname in groups['monitoring']
  tags: [ monitoring, icinga, icingaconfigs, AB ]
  # notify: restart icinga

$ ansible-playbook -b --ask-become-pass -k -l nagios.domain.com icinga.yml --extra-vars="user=USER" --tags=AB
TASK: [debug msg="{{ icinga.groups }}"] **************************************\* 
ok: [nagios.domain.com] => {
    "msg": "['av', 'avproxies', 'backup', 'dbservers', 'dev', 'elasticsearch', 'graylog', 'mal', 'mongod', 'monitoring', 'webservers']"  
}

This fails with: 
failed: [nagios.domain.com] => (item=umsrvnewtest) => {"failed": true, "item": "umsrvnewtest"}
msg: Boolean n not in either boolean list
ok: [nagios.domain.com] => (item=vmextra)
failed: [nagios.domain.com] => (item=vpnloggers) => {"failed": true, "item": "vpnloggers"}
msg: Boolean n not in either boolean list
ok: [nagios.domain.com] => (item=webservers)

FATAL: all hosts have already failed -- aborting

Is there an easier way or am I running into a bug ?
Thank you,
Mario

**Comment by resmo** [comment]
Please use ML for questions. btw I could help, we setup an icinga2 env with 5000 checks and 1000 hosts distributed checker nodes just with ansible...

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
