### ISSUE TITLE
Bug : tasks are not executed in parallel

### ISSUE THREAD

**Issue by chengchengmu** [ansible/ansible#13621]
Ansible should run tasks in parallel but it does not apparently.
I already opened a ticket for this bug here https://github.com/ansible/ansible/issues/13601 Please @bcoca don't close it this time with an automatic answer

To test it I have a little playbook : 

```

---
- hosts: test
#  serial: 3
  tasks:

  - name: show time
    shell: echo $(date) && sleep 5
```

In the /etc/ansible/ansible.cfg, I have `forks          = 50` and my ansible version is `1.9.4
`.
I launch this playbook against 3 hosts, and I have this result : 

```
  ansible-playbook -vv -i hosts par.yml 

PLAY [test] ******************************************************************* 

GATHERING FACTS *************************************************************** 
<104.155.33.255> REMOTE_MODULE setup
<104.155.44.118> REMOTE_MODULE setup
<104.155.72.91> REMOTE_MODULE setup
ok: [104.155.33.255]
ok: [104.155.44.118]
ok: [104.155.72.91]

TASK: [show time] ************************************************************* 
<104.155.44.118> REMOTE_MODULE command echo $(date) && sleep 5 #USE_SHELL
<104.155.33.255> REMOTE_MODULE command echo $(date) && sleep 5 #USE_SHELL
<104.155.72.91> REMOTE_MODULE command echo $(date) && sleep 5 #USE_SHELL
changed: [104.155.44.118] => {"changed": true, "cmd": "echo $(date) && sleep 5", "delta": "0:00:05.004494", "end": "2015-12-18 16:31:40.506679", "rc": 0, "start": "2015-12-18 16:31:35.502185", "stderr": "", "stdout": "Fri Dec 18 16:31:35 UTC 2015", "warnings": []}
changed: [104.155.33.255] => {"changed": true, "cmd": "echo $(date) && sleep 5", "delta": "0:00:05.006183", "end": "2015-12-18 16:31:45.623886", "rc": 0, "start": "2015-12-18 16:31:40.617703", "stderr": "", "stdout": "Fri Dec 18 16:31:40 UTC 2015", "warnings": []}
changed: [104.155.72.91] => {"changed": true, "cmd": "echo $(date) && sleep 5", "delta": "0:00:05.007773", "end": "2015-12-18 16:31:50.742663", "rc": 0, "start": "2015-12-18 16:31:45.734890", "stderr": "", "stdout": "Fri Dec 18 16:31:45 UTC 2015", "warnings": []}

PLAY RECAP ******************************************************************** 
104.155.33.255             : ok=2    changed=1    unreachable=0    failed=0   
104.155.44.118             : ok=2    changed=1    unreachable=0    failed=0   
104.155.72.91              : ok=2    changed=1    unreachable=0    failed=0   
```

By uncommenting the line `#serial: 3`, the result is the same.

We expect tasks to be executed in parallel (http://docs.ansible.com/ansible/intro_adhoc.html#parallelism-and-shell-commands)
In this simple case the tasks are executed sequentially on hosts.

**Comment by bcoca** [comment]
Ansible does work in parallel, you are hitting something that is forcing serialization, that is why i sent you to the mailing list.

**Comment by chengchengmu** [comment]
@bcoca Thank you for the tip

This forced serialization is due to ssh key checking ...
By adding `host_key_checking = False` (commented by default) in the ansible configuration file, tasks are successfully executed in parallel.

It could be great for the community to add some topic in the official FAQ or http://docs.ansible.com/ansible/intro_adhoc.html#parallelism-and-shell-commands
