### ISSUE TITLE
group_by creates incorrect groups

### ISSUE THREAD

**Issue by tersmitten** [ansible/ansible#13634]
We have two mysql masters and I wanted to create an active/passive group based on which server has the [VIP](https://en.wikipedia.org/wiki/Virtual_IP_address):

```
# ansible all -i inventory.py --limit tiers-production-app-mysql -m setup -a 'filter=ansible_eth1_1'
db-02.example.com | success >> {
    "ansible_facts": {}, 
    "changed": false
}

db-01.example.com | success >> {
    "ansible_facts": {
        "ansible_eth1_1": {
            "ipv4": {
                "address": "10.0.2.75", 
                "netmask": "255.255.255.255", 
                "network": "10.0.2.75"
            }
        }
    }, 
    "changed": false
```

So in the cause above, `db-01.example.com` is the master.

The debug playbook below shows the correct group names:

```
# ansible-playbook -i inventory.py all-debug.yml --limit tiers-production-app-mysql -vv;

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
<1.2.3.75> REMOTE_MODULE setup
<1.2.3.76> REMOTE_MODULE setup
ok: [db-02.example.com]
ok: [db-01.example.com]

TASK: [debug ] **************************************************************** 
ok: [db-01.example.com] => {
    "msg": "tiers-production-app-mysql-replication-master-active"
}
ok: [db-02.example.com] => {
    "msg": "tiers-production-app-mysql-replication-master-passive"
}
```

Now comes the strange thing. I expected the `group_by` statement below to work:

```
    - name: create dynamic active / passive groups
      group_by:
        key: "tiers-production-app-mysql-replication-master-{{ 'active' if ansible_eth1_1 is defined else 'passive' }}"
```

But **it doesn't**, the following statement does:

```
    - name: create dynamic active / passive groups
      group_by:
        key: "tiers-production-app-mysql-replication-master-{{ 'active' if hostvars[inventory_hostname]['ansible_eth1_1'] is defined else 'passive' }}"
```

When I debug `ansible_eth1_1` (use it as a group name), both machines have the **same values**. So it looks like variables are not been reset.

**Comment by jimi-c** [comment]
Hi @tersmitten, with which version of Ansible are you seeing this?

**Comment by tersmitten** [comment]
@jimi-c: Version 1.9.3

**Comment by tersmitten** [comment]
@jimi-c Any progress on this bug?

**Comment by jimi-c** [comment]
@tersmitten still dealing with 2.0 release issues. We're going to try and go through things set to stable-1.9's milestone ASAP, and we'll review this at that time.

**Comment by mavit** [comment]
Duplicate of #12125?

**Comment by jimi-c** [comment]
@tersmitten sorry I never got back to this, but looking now I'm not seeing the issue in stable-1.9, stable-2.1, or devel. Is this still a bug for you?

**Comment by tersmitten** [comment]
I'm still seeing this in `1.9.6`, `2.1.1.0` seems to work fine

**Comment by jimi-c** [comment]
Ok, unfortunately 1.9.6 is only getting security fixes at this point, so you'll have to continue using your workaround unless you upgrade.

**Comment by tersmitten** [comment]
No worries, the workaround is just fine and we stopped using `group_by` a while ago
