### ISSUE TITLE
Using fireball mode without specifying port doesn't work

### ISSUE THREAD

**Issue by abourget** [ansible/ansible#1363]
Using this playbook:
- hosts: dev_christian
  sudo: True
  user: ubuntu
  connection: ssh
  tasks:
  - action: fireball
- hosts: dev_christian
  connection: fireball
  # port: 5099
  
  tasks:
  - action: shell echo "Boo"
  - action: shell echo "Boo"

with the current development branch, if we omit the "port: 5099", fireball mode assumes it's port 22 (it is passed as "remote_port" from the playbook down to the Runner).

Using fireball mode should assume a default port of 5099, and we should indeed be able to change it, but it'd be best if it was documented.  Or at least is the docs showed it was required for the fireball connection mode to succeed.

I'd be willing to tweak the docs with my findings.. I'd just want to know the expected or wanted behavior.

**Comment by mpdehaan** [comment]
It's not a doc issue, it's a recent code thing.  Good catch.

**Comment by mpdehaan** [comment]
Should be fixed in ee26853

**Comment by abourget** [comment]
Great :) works, thanks :+1: :100:
