### ISSUE TITLE
fireball mode crashes if no keyczar is present

### ISSUE THREAD

**Issue by abourget** [ansible/ansible#1364]
The traceback is about a global "AesKey" not being defined in lib/ansible/utils.py ..

When using fireball mode, if utils.KEYCZAR_AVAILABLE is False, we should warn the user to tell him to install python-keyczar, and gracefully shut down.

**Comment by mpdehaan** [comment]
fixed

**Comment by abourget** [comment]
Great! Thanks :)  :109:

**Comment by mpdehaan** [comment]
No problem.

I am confused by the emoticon.  Is the 109 Meitnerium ?

**Comment by abourget** [comment]
Yeah, actually I just discovered it.. I have no clue what it means.. it does seem to be related.. but I wouldn't know its meaning :) Sorry for the distraction :)
