### ISSUE TITLE
Role search path precedence change in v2

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#13645]
In 1.9 the path precedence appears to be:
1. playbook_dir/roles/
2. playbook_dir/

In 2.0 the path precedence has changed to what appears to be
1. playbook_dir/
2. playbook_dir/roles/

To validate this, the file tree looks like:

```
.
├── ansible.cfg
├── roles
│   └── test
│       └── tasks
│           └── main.yml
├── test
│   └── tasks
│       └── main.yml
└── test.yml
```

ansible.cfg in this case is completely empty.
#### test.yml

```

---
- hosts: all
  gather_facts: false
  roles:
    - test
```

Each `main.yml` should contain a single debug, each with different message such as:

```
- debug: msg=in_roles_dir
```

```
- debug: msg=in_playbook_dir
```

This causes a completely non-role related directory in the `playbook_dir` to potentially, override an actual role of the same name in the `roles` directory.

**Comment by Yannig** [comment]
The code behind this behaviour is in this file: https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/__init__.py

Specifically the following code:

``` python
    def _get_hostgroup_vars(self, host=None, group=None, new_pb_basedir=False):
        """
        Loads variables from group_vars/<groupname> and host_vars/<hostname> in directories parallel
        to the inventory base directory or in the same directory as the playbook.  Variables in the playbook
        dir will win over the inventory dir if files are in both.
        """

        results = {}
        scan_pass = 0
        _basedir = self.basedir()

        # look in both the inventory base directory and the playbook base directory
        # unless we do an update for a new playbook base dir
        if not new_pb_basedir:
            basedirs = [_basedir, self._playbook_basedir] # <= here
        else:
            basedirs = [self._playbook_basedir] # <= and here

        for basedir in basedirs:
            # this can happen from particular API usages, particularly if not run
            # from /usr/bin/ansible-playbook
            if basedir in ('', None):
                basedir = './'

```

Lately, I was working on a patch to be able to add additionals directories (you can check it here: https://github.com/ansible/ansible/pull/12628) but I was wondering if it can be interesting to change also this directories.

**Comment by bcoca** [comment]
@Yannig role loading is unrelated to inventory group/host var loading

**Comment by bcoca** [comment]
relevant code seems to be in https://github.com/ansible/ansible/blob/deve/lib/ansible/playbook/role/definition.py#L144 and from my read (as wrong as it looks) `<playdir>/roles` should be read first

**Comment by bcoca** [comment]
but my tests concur, the wrong role gets loaded.

**Comment by bcoca** [comment]
problem is that it matches in line https://github.com/ansible/ansible/blob/deve/lib/ansible/playbook/role/definition.py#140 above

**Comment by Yannig** [comment]
@bcoca I was off topic :)

**Comment by bcoca** [comment]
@sivel can you confirm that the above PR fixes the issue for you?
