### ISSUE TITLE
[win_file] path gets garbled and not accepted due to backslash in that path

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#13658]
Snippet from my playbook:
`win_file: path=c:\my\repository state=directory`

What happens, is that the \r in the path causese win_file.ps1 to choke. After that the directory is not created.

Workaround for me is to double escape the \r:
`win_file: path=c:\my\\repository state=directory`

Output from WINRM (via `-vvvvvv`):

```
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
    <S S="Error">Test-Path : Illegal characters in path._x000D__x000A_</S>
    <S S="Error">At C:\Users\jan\AppData\Local\Temp\ansible-tmp-1450939435.51-32875335993443\w_x000D__x000A_</S>
    <S S="Error">in_file.ps1:290 char:5_x000D__x000A_</S>
    <S S="Error">+ If (Test-Path $path)_x000D__x000A_</S>
    <S S="Error">+     ~~~~~~~~~~~~~~~_x000D__x000A_</S>
    <S S="Error">+ CategoryInfo          : InvalidArgument: (C:\myepository:String) [Test-  _x000D__x000A_</S>
    <S S="Error">Path], ArgumentException_x000D__x000A_</S>
    <S S="Error">+ FullyQualifiedErrorId : ItemExistsArgumentError,Microsoft.PowerShell.Com _x000D__x000A_</S>
    <S S="Error">mands.TestPathCommand_x000D__x000A_</S>
    <S S="Error">_x000D__x000A_</S>
    <S S="Error">New-Item : Illegal characters in path._x000D__x000A_</S>
    <S S="Error">At C:\Users\jan\AppData\Local\Temp\ansible-tmp-1450939435.51-32875335993443\w_x000D__x000A_</S>
    <S S="Error">in_file.ps1:329 char:9_x000D__x000A_</S>
    <S S="Error">+         New-Item -ItemType directory -Path $path_x000D__x000A_</S>
    <S S="Error">+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_x000D__x000A_</S>
    <S S="Error">+ CategoryInfo          : InvalidArgument: (C:\myepository:String) [New-I  _x000D__x000A_</S>
    <S S="Error">tem], ArgumentException_x000D__x000A_</S>
    <S S="Error">+ FullyQualifiedErrorId : ItemExistsArgumentError,Microsoft.PowerShell.Com _x000D__x000A_</S>
    <S S="Error">mands.NewItemCommand_x000D__x000A_</S>
    <S S="Error">_x000D__x000A_</S>
</Objs>
```

(update: by the way, maybe not a win_file specific problem, because I have the same issue with all path-like parameters in win_unzip)

Used version:
ansible 2.1.0 (devel d89d7951e6) last updated 2015/12/23 17:51:57 (GMT +200)

Used on Azure, Windows server 2012 R2

**Comment by jhawkesworth** [comment]
I think you just have to treat windows paths a bit differently than Unix style paths. 

As well as double backslashes you can also single or double quote the path. 

Also, avoid trailing backslashes at the end of a line in your playbook, as yaml treats them as line continuations.

You may actually also be able to use forward slash as a separator as powershell handles this. However older windows executables won't handle this so it depends on what the module you are using actually does, so personally I don't use this in my playbooks. 

Also worth adding that the integration tests have loads of useful examples. 

Hope this helps.

**Comment by ghost** [comment]
Thanks for your comment.
Well, I thought I should use backslashes because in the examples provided in http://docs.ansible.com/ansible/list_of_windows_modules.html mostly backslashes are used. (now and then also forward slashes).

But I changed my script to forward slashes instead of backslashes, and it went pretty well, except for one module: win_unzip which can only handle backslashes. Errors are thrown when I use forward slashes with win_unzip.

Forward slashes seem to work fine with the following modules I use in my playbook: 
- win_file
- win_get_url
- raw
- win_service
- win_copy

But I think you admit there is something strange going on with my initial problem: the \r. :)

Thanks for pointing me to the integration tests!

**Comment by jhawkesworth** [comment]
I expect \r is being treated as an escape sequence. I recall something
similar happening when trying to use \t inside c:\temp which got
interpreted as a tab character. This was a little while ago though and
things may have changed in ansible 2.0 code.

Worth a quick look at the yaml spec if you are planning on not quoting
windows paths.

I suspect win_unzip may be different because it uses pscx under the hood.

**Comment by jimi-c** [comment]
@janhoeve with which version of Ansible are you seeing this? @nitzmahone and I worked on several improvements to path escaping specifically for Windows hosts in devel/stable-2.0, so you might want to try one of those branches if you're currently running 1.9.x.

**Comment by ghost** [comment]
I am using:
`ansible 2.1.0 (devel d89d795) last updated 2015/12/23 17:51:57 (GMT +200)`
Do you suggest downgrading to the devel/stable-2.0 branch to test this?

**Comment by jimi-c** [comment]
@janhoeve just wanted to make sure, devel is 2.1.0 and should be the same as the stable-2.0 branch in this regard.

**Comment by nitzmahone** [comment]
Argh. This looks like more escaping issues (specifically in the KV parser, which we didn't beat on as hard), plus a bug where the module wasn't written to fail on errors (so the true error "Illegal characters in path" is being masked). 

As a workaround, if you change from the KV syntax to classic YAML syntax, it'll work as you expect with no special escaping or quoting. eg: 

```
win_file: 
  path: c:\my\repository 
  state: directory
```

I'll hit the module part today (so at least you'll get a useful error back), but not sure if if we want to try and squeeze more blood from the KV parser before 2.0 RC4. @jimi-c ?

**Comment by nitzmahone** [comment]
Fixed module failure masking with https://github.com/ansible/ansible-modules-core/commit/33014c6db1ce757d0ffa065e6c9924ac4db1cacc (and cherry-picked to stable-2.0). Still need to decide what to do about KV escaping issue (if anything).

**Comment by nitzmahone** [comment]
Rallying around https://github.com/ansible/ansible/issues/15787 - the rest of this issue would be covered if we fixed it, so closing this one.
