### ISSUE TITLE
ansible-pull does not respect ansible.cfg in pulled repo

### ISSUE THREAD

**Issue by robinro** [ansible/ansible#13688]
while researching/fixing #13681 I realized where that the problem is actual another assumption: ansible-pull in v2 setups up all standard ansible arguments (`-l`, `-i`, ...) **before** cloning the repository. There is a workaround for the inventory-pull, but for anything else it completely ignores the ansible.cfg file inside the pulled repository. This breaks existing 1.9 behavior.

Suggestion: Allow explicitly passed arguments to ansible-pull and forward them to the ansible-playbook call. For anything that is not passed explicitly, don't append it to the ansible-playbook call, but let ansible-playbook figure out the values by itself. It then has access to the ansible.cfg in the pulled repo.

**Comment by robinro** [comment]
for this issue only the `inventory` option is relevant, all others are already not passed to ansible-playbook if they are empty

**Comment by bcoca** [comment]
closing via merged #14220

**Comment by robinro** [comment]
#14220 does not fix this

I have an inventory _inside_ the checked out repo.
1.9.4 runs ansible-playbook inside the checked out repo, reads the ansible.cfg there and uses the inventory scripts inside the repo.

This version now leads to `skipping: no hosts matched`, because we use the fqdn for the playbook, but only `-l localhost,127.0.0.1,::1` is used (by default because the global inventory is empty).

For a list of cases that should work in my opinion, please see
https://github.com/ansible/ansible/pull/13689#issuecomment-167775860

@bcoca Sorry to drag this out, but the current fix still breaks existing 1.9 behavior. Please reopen.

**Comment by bcoca** [comment]
@robinro are you passing inventory options to ansible-pull? please give detailed info to reproduce.

**Comment by robinro** [comment]
@bcoca no, I assume the ansible-playbook command to read the ansible.cfg inside in repo and then use the inventory specified there. This breaks if `-i` is given.

**Comment by bcoca** [comment]
The -i passed to ansible-pull is for explicitly passing to ansible-playbook and SHOULD override any ansible.cfg setting.

**Comment by robinro** [comment]
Ok, but I don't _want_ to pass -i, because I want to use the inventory defined _inside_ the repo. So I need ansible-playbook to be called _without_ `-i` for my setup to continue work.

**Comment by bcoca** [comment]
```
        if self.options.inventory:
            cmd += ' -i "%s"' % self.options.inventory
```

^ as i read the code, that is already true

**Comment by robinro** [comment]
If you read this code, it seems to be, but `self.options.inventory` is never empty, because if the user does not specify it, it gets set to some default constant (localhost,127.0.0.1,::1).

See my suggested fix to not set it in the case of ansible-pull
https://github.com/ansible/ansible/pull/13689/files

**Comment by bcoca** [comment]
lets see if this makes sense, seems less intrusive to me (fixes both issues):

```
diff --git a/lib/ansible/cli/pull.py b/lib/ansible/cli/pull.py
index e099555..c29f5d5 100644
--- a/lib/ansible/cli/pull.py
+++ b/lib/ansible/cli/pull.py
@@ -166,7 +166,7 @@ class PullCLI(CLI):

         bin_path = os.path.dirname(os.path.abspath(sys.argv[0]))
         # hardcode local and inventory/host as this is just meant to fetch the repo
-        cmd = '%s/ansible -i "localhost," -c local %s -m %s -a "%s" all' % (bin_path, base_opts, self.options.module_name, repo_opts)
+        cmd = '%s/ansible -i "localhost," %s -m %s -a "%s" all' % (bin_path, base_opts, self.options.module_name, repo_opts)

         for ev in self.options.extra_vars:
             cmd += ' -e "%s"' % ev
@@ -198,7 +198,7 @@ class PullCLI(CLI):
         cmd = '%s/ansible-playbook %s %s' % (bin_path, base_opts, playbook)
         if self.options.vault_password_file:
             cmd += " --vault-password-file=%s" % self.options.vault_password_file
-        if self.options.inventory:
+        if self.options.inventory != C.DEFAULT_HOST_LIST:
             cmd += ' -i "%s"' % self.options.inventory
         for ev in self.options.extra_vars:
             cmd += ' -e "%s"' % ev
@@ -208,6 +208,8 @@ class PullCLI(CLI):
             cmd += ' -t "%s"' % self.options.tags
         if self.options.subset:
             cmd += ' -l "%s"' % self.options.subset
+        else:
+            cmd += ' -l "%s"' % limit_opts

         os.chdir(self.options.dest)
```

**Comment by robinro** [comment]
This is fragile if someone ever changes the use of `C.DEFAULT_HOST_LIST` in **init**. I felt changing it there is more honest. It should not be set to any default anyhow in my opinion.

**Comment by robinro** [comment]
why do you reintroduce `limit_opts` here? It's not really needed, right?

**Comment by bcoca** [comment]
We want to restrict playbook execution to the 'current host', if someone adds 'all' and puts in a ful inventory you might have the host attempt to do multiple machines. This can be forced by adding `--limit 'all'` if the user really wants that.

**Comment by robinro** [comment]
right...

The last diff (+import) works for me. The complete version I now used is at  #14242

**Comment by gvenka008c** [comment]
@robinro I am running into below issue while using ansible-pull. For some reason it is not reading my static host file (hosts) and also not running dynamic inventory script (openstack.py). Can you please suggest if the below way method is right?

#ansible-pull -U git@github.com:XPlat/caps-sps.git -d /home/gvenka008c/caps-sps --inventory=/home/gvenka008c/caps-sps/jenkins_mesos/ansible/inventory/ --key-file=/home/gvenka008c/.ssh/gvenka008c /home/gvenka008c/caps-sps/jenkins_mesos/ansible/jenkins_mesos_icinga.yml
Starting Ansible Pull at 2016-03-17 03:09:10
/usr/bin/ansible-pull -U git@github.com:XPlat/caps-sps.git -d /home/gvenka008c/caps-sps --inventory=/home/gvenka008c/caps-sps/jenkins_mesos/ansible/inventory --key-file=/home/gvenka008c/.ssh/gvenka008c /home/gvenka008c/caps-sps/jenkins_mesos/ansible/jenkins_mesos_icinga.yml
82ddf8b3-91c9-42d5-92d3-00fe7bf21d31 | SUCCESS => {
    "after": "36e7682d6fc33d0db95ad163ec819c290e39a55e",
    "before": "36e7682d6fc33d0db95ad163ec819c290e39a55e",
    "changed": false
}

PLAY ***************************************************************************
skipping: no hosts matched

**Comment by robinro** [comment]
I'm not sure specifying an inventory within the checkout out repo works, because it might try to read it before the pull (check the code for that).

What we do is put an `ansible.cfg` config inside the repo that sets the inventory, which is then used.
