### ISSUE TITLE
File module broken for links

### ISSUE THREAD

**Issue by jpalley** [ansible/ansible#1369]
The following two lines were added to the file module (343).  

```
if src is not None and os.path.isdir(path):
    params['path'] = path = os.path.join(path, os.path.basename(src))
```

This breaks a number of my plays where I want to create a link from one directory to another.  For example:

action: file src=/home/app/releases/${deploy_time.stdout} dest=/home/app/current state=link

I would fix this, but I'm not clear the purpose of adding the above lines?  Or am I doing something wrong?

**Comment by mpdehaan** [comment]
The reason is to support the with_fileglob.   It probably needs to add an "and state != 'link'" or similar.

**Comment by mpdehaan** [comment]
If you'd like to fix this, I can test tonight.  Today is the last day for 0.8 testing so that would be ideal.

**Comment by mpdehaan** [comment]
thanks!
