### ISSUE TITLE
Execution hangs and failure not respected when using include statements

### ISSUE THREAD

**Issue by renekalff** [ansible/ansible#13699]
**Issue Type: Bug Report**

**Ansible Version:**
ansible 2.0.0 (detached HEAD a2120a3d63) last updated 2015/12/30 16:14:04 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 5777c28f50) last updated 2015/12/30 16:14:13 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 14b81df29c) last updated 2015/12/30 16:14:13 (GMT +200)
  config file = /Users/rkalff/Projects/TestAnsible/test/ansible.cfg
  configured module search path = Default w/o overrides

**Ansible Configuration:**

```
[defaults]
hostfile = hosts
remote_user = vagrant
private_key_file = ~/.vagrant.d/insecure_private_key
host_key_checking = False
```

**Environment:**
OS X El Capitan (10.11.1)

**Summary:**
When executing on multiple hosts in parallel and a single host fails execution never ends when there is a include task after the failure. See test3.yml

When the failure occurs in an included task file and there is another included task file after the failure the failure is not respected and different tasks run in parallel on different hosts. See test5.yml

All tests run as expected on 1.9.3

**Steps To Reproduce:**
See https://github.com/renekalff/ansible_bug_report_1

**Expected Results:**
A) That ansible-playbook returns to the prompt in test3.yml
B) That no tasks are executed for a host after failure in test5.yml

**Actual Results:**
See play_results folder in: https://github.com/renekalff/ansible_bug_report_1

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by renekalff** [comment]
In test5.yml a failed host (host2) still resumes executing when the last task for host1 is being run. It generates the following output:

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [host2]
ok: [host1]

TASK [debug] *******************************************************************
ok: [host1] => {
    "msg": "start of test 4"
}
ok: [host2] => {
    "msg": "start of test 4"
}

TASK [include] *****************************************************************
included: /Users/rkalff/Projects/TestProjects/ansible_bug_report_1/includes/include2.yml for host1, host2

TASK [fail] ********************************************************************
skipping: [host1]
fatal: [host2]: FAILED! => {"changed": false, "failed": true, "msg": "failure in include"}

TASK [debug] *******************************************************************
ok: [host1] => {
    "msg": "first debug message"
}

TASK [debug] *******************************************************************
ok: [host1] => {
    "msg": "second debug message"
}

TASK [include] *****************************************************************
included: /Users/rkalff/Projects/TestProjects/ansible_bug_report_1/includes/include1.yml for host1

TASK [debug] *******************************************************************
ok: [host1] => {
    "msg": "include 1"
}

TASK [debug] *******************************************************************
ok: [host1] => {
    "msg": "final debug message"
}
ok: [host2] => {
    "msg": "first debug message"
}

TASK [debug] *******************************************************************
ok: [host2] => {
    "msg": "second debug message"
}

TASK [include] *****************************************************************
included: /Users/rkalff/Projects/TestProjects/ansible_bug_report_1/includes/include1.yml for host2

TASK [debug] *******************************************************************
ok: [host2] => {
    "msg": "include 1"
}

TASK [debug] *******************************************************************
ok: [host2] => {
    "msg": "final debug message"
}

PLAY RECAP *********************************************************************
host1                      : ok=8    changed=0    unreachable=0    failed=0   
host2                      : ok=8    changed=0    unreachable=0    failed=1
