### ISSUE TITLE
make sure Fedora/EPEL package review request gets through

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#137]
https://bugzilla.redhat.com/show_bug.cgi?id=809882

mpdehaan to follow up with eck.

**Comment by timlnx** [comment]
My topic branch is here:

https://github.com/tbielawa/ansible/tree/packaging

I am addressing the current feedback from the reviewer.

> Hi,
> 
> a few note :
> - you should explicitely say the version of python to use in BuildRequires 
>   https://fedoraproject.org/wiki/Packaging:Python#BuildRequires

Fixed.

> - the python macro are already defined on Fedora, so no need to add them again

Fixed. Only set if RHEL 5.

> - Prefix is forbidden

Fixed.

> - buildRoot should not be used, except for EPEL 5
>   https://fedoraproject.org/wiki/Packaging:Guidelines#BuildRoot_tag

Fixed. Only set if RHEL 5.

> - so does %defattr, %clean and rm in %install 

I don't understand what you mean by this. Can you please expand?

> - --record=INSTALLED_FILES is not used, and is not recommended
>   https://fedoraproject.org/wiki/Packaging:Python#Byte_compiling

Removed.

> - it seems that %{_datadir}/ansible/ would end unowned

I think this is fixed now.

> - I am not sure, but I think that "-n %{name}-%{version}" is uneeded, becuase
>   tha's the default

Correct. Removed this too.

> - the guideline ask for consistency when using macro to reference path :
>   %config(noreplace) /etc/ansible/hosts
>   %config(noreplace) %{_sysconfdir}/ansible/

Fixed. Consolidated to just the latter.

> - %{_mandir}/man1/*.gz
>   that's not mandatory, but I think that's better to not hardcode the prefix used
>   here, as this could be changed in the future ( ie, be something else than gz )

**Comment by timlnx** [comment]
Also, modified the man page inclusion stuff.

**Comment by timlnx** [comment]
Updated bugzilla:

https://bugzilla.redhat.com/show_bug.cgi?id=809882#c3

**Comment by laroche** [comment]
Installing ansible on a stripped down installation shows that even basic commands need PyYAML
installed, so I think this should be added as an "Requires:" to the spec file.

best regards,

Florian La Roche

**Comment by mpdehaan** [comment]
agreed.

PyYAML is required only if using ansible-playbook and the inventory file, so it COULD be conditionally included, but there is no reason to not include this for the spec.

**Comment by mpdehaan** [comment]
added PyYAML to the spec file on the integration branch

**Comment by laroche** [comment]
Even for ping, PyYAML seems to get dragged in:

ansible 10.251.252.20 -m ping
Traceback (most recent call last):
  File "/usr/bin/ansible", line 27, in <module>
    import ansible.runner
  File "/usr/lib/python2.6/site-packages/ansible/runner.py", line 35, in <module>
    from ansible import utils
  File "/usr/lib/python2.6/site-packages/ansible/utils.py", line 25, in <module>
    import yaml
ImportError: No module named yaml

**Comment by mpdehaan** [comment]
sure, yeah it is listed in the docs as a requirement anyway.

No sense having people go out of their way to avoid it...

**Comment by timlnx** [comment]
Got a response back from the reviewer. Addressed his latest concerns.

Also, we formally decided in IRC today not to target EPEL 5. Those changes have been represented in the spec file.

**Comment by timlnx** [comment]
Got some more feedback from reviewer. Just license and source related issues at this point.

See also: #284

**Comment by timlnx** [comment]
Thanks for handling the PR @mpdehaan, I think we just addressed the last of the reviewers points.

**Comment by timlnx** [comment]
Package review complete! Time to get repos made and start uploading some packages!

**Comment by timlnx** [comment]
Pending:
- Repos
- Package Build

Here's where I get hazy. I know that after I upload an update of an existing package it goes into -pending and sits for a a little while (longer for EPEL). BUT you can expedite this process (in a manner of speaking) by having registered users give +1's on the updates tracker indicating that the new package installed and ran/tested correctly for them. Not sure if this applies to new packages.

After package is built it goes into updates-pending.
- Package Signed && Uploaded into the repos.

**Comment by mpdehaan** [comment]
outstanding

the very lame kudos process could be bypassed manually a couple of years ago by requesting a push directly to stable.  I hope this is the case because it was a terrible design to require everyone to have Fedora accounts.

**Comment by timlnx** [comment]
SCM admin request submitted.

**Comment by timlnx** [comment]
- SCM Admin request processed
- Sources uploaded
- Building f15, f16, and f17 branches now

**Comment by mpdehaan** [comment]
rock.  I owe you that $beverage at some point, and obviously I got out cheap :)

If you can request EPEL 6 at least, that would be awesome.  I know
EPEL 5 may require some hoops because of the different Python but
maybe it's not too bad.

On Sun, May 6, 2012 at 7:23 PM, Tim 'Shaggy' Bielawa
reply@reply.github.com
wrote:

**Comment by timlnx** [comment]
**Fedora 15**
- Build Information
  - http://koji.fedoraproject.org/koji/buildinfo?buildID=317670
- bodhi - 2012-05-06 23:43:32
  - This update has reached the stable karma threshold and will be pushed to the stable updates repository

**Fedora 16**
- Build Information
  - http://koji.fedoraproject.org/koji/buildinfo?buildID=317669
- bodhi - 2012-05-06 23:43:32
  - This update has reached the stable karma threshold and will be pushed to the stable updates repository

**Fedora 17**
- Build Information
  - http://koji.fedoraproject.org/koji/buildinfo?buildID=317667
- Bodhi is lagging on processing the push to stable. I'll check on it again later tonight -- but it shouldn't be a problem.
  - https://admin.fedoraproject.org/updates/ansible-0.3.1-1.fc17

**Rawhide**
- Master branch pushed and built
- Build Information
  - Automatically tagged for f18 (dist-rawhide)
  - http://koji.fedoraproject.org/koji/taskinfo?taskID=4058658

**Comment by timlnx** [comment]
Yes. I mean to submit an epel 6 update some time. Forgot about that in
the initial request.

$beverage++

On Sun, May 6, 2012 at 7:39 PM, Michael DeHaan
reply@reply.github.com
wrote:

> rock.  I owe you that $beverage at some point, and obviously I got out cheap :)
> 
> If you can request EPEL 6 at least, that would be awesome.  I know
> EPEL 5 may require some hoops because of the different Python but
> maybe it's not too bad.
> 
> On Sun, May 6, 2012 at 7:23 PM, Tim 'Shaggy' Bielawa
> reply@reply.github.com
> wrote:
> 
> > - SCM Admin request processed
> > - Sources uploaded
> > - Building f15, f16, and f17 branches now
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/ansible/ansible/issues/137#issuecomment-5541764
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ansible/ansible/issues/137#issuecomment-5541867

## 

--Tim Bielawa
http://lnx.cx

**Comment by timlnx** [comment]
**Fedora 17**
- bodhi - 2012-05-07 00:14:03
  - This update has reached the stable karma threshold and will be pushed to the stable updates repository

**Comment by timlnx** [comment]
External Tasks Pending:
- Repository admins sign packages
- Repository admins do final package push into repos

**Comment by mpdehaan** [comment]
external tasks means "not us", right?  :)

**Comment by timlnx** [comment]
== fedora project signing key holders
On May 6, 2012 8:49 PM, "Michael DeHaan" <
reply@reply.github.com>
wrote:

**Comment by mpdehaan** [comment]
Are they the keymasters?

I am the gatekeeper.

**Comment by timlnx** [comment]
I am the terror that uploads packages in the night!
On May 6, 2012 9:03 PM, "Michael DeHaan" <
reply@reply.github.com>
wrote:

**Comment by timlnx** [comment]
EL6 branch request submitted.

https://bugzilla.redhat.com/show_bug.cgi?id=809882#c17

**Comment by timlnx** [comment]
EL6 branch created.

FC17 pushed to stable. Pending: 15 and 16

Need to push a build for EL6.

**Comment by mpdehaan** [comment]
awesome.

**Comment by timlnx** [comment]
Wlmost there. f17 got through. el6 is in testing. Waiting on the package repo signers to get their shit together ( _<3 you guys_) and sign the f15/6 packages.

**Comment by mpdehaan** [comment]
closing!
