### ISSUE TITLE
window modules auth not working as expected with 2.0

### ISSUE THREAD

**Issue by modonnel** [ansible/ansible#13705]
I have a valid  Kerberos ticket on a host with 2.0 and the following playbook fails.
## modonnel@appl303-stc:~/tmp/playbook $ cat win_test.yaml
- name: Test Windows
  hosts: ws3-adm-stc
  vars:
  ansible_ssh_user: modonneladmin@GLOBAL.TUDOR.COM
  ansible_ssh_port: 5986
  ansible_connection: winrm
  tasks:
- name: test ping
  action: win_ping

modonnel@appl303-stc:~/tmp/playbook $ ansible-playbook win_test.yaml -vvvv
Using /home/modonnel/.ansible.cfg as config file
1 plays in win_test.yaml
Loaded callback default of type stdout, v2.0
PLAY [Test Windows] ************************************************************
TASK [setup] *******************************************************************
<ws3-adm-stc> ESTABLISH WINRM CONNECTION FOR USER: modonneladmin@GLOBAL.TUDOR.COM on PORT 5986 TO ws3-adm-stc
fatal: [ws3-adm-stc]: FAILED! => {"failed": true, "msg": "ERROR! ssl: 401 Unauthorized."}
NO MORE HOSTS LEFT *************************************************************
PLAY RECAP *********************************************************************
ws3-adm-stc : ok=0 changed=0 unreachable=0 failed=1
modonnel@appl303-stc:~/tmp/playbook $

It works fine on a host running 1.9.3
modonnel@adm1-stc:~/tmp/playbook $ ANSIBLE_NOCOWS=1 ansible-playbook win_test.yaml

PLAY [Test Windows] ***********************************************************

GATHERING FACTS ***************************************************************
ok: [ws3-adm-stc]

TASK: [test ping] *************************************************************
ok: [ws3-adm-stc]

PLAY RECAP ********************************************************************
ws3-adm-stc                : ok=2    changed=0    unreachable=0    failed=0

modonnel@adm1-stc:~/tmp/playbook $ ansible --version
ansible 1.9.3
  configured module search path = /home/modonnel/ansible/playbooks/library;/usr/share/ansible
modonnel@adm1-stc:~/tmp/playbook $

Thanks,
Mike

**Comment by nitzmahone** [comment]
This playbook works fine against my test lab (switched the username, etc) using Kerberos auth with both stable-2.0 and devel. Which version of pywinrm are you running with 2.0? 0.1.1 may give a better error message (though the behavior shouldn't change). Also, how are you running 2.0 (from source [hash?], from an RC tarball, etc)? This stuff hasn't changed in a few months, so anything relatively recent should get the job done.

**Comment by modonnel** [comment]
You're right, my fault for not testing this thoroughly enough before opening this issue.  I only run ansible 2.0 on a single host and that host had an issue.  It's not been resolved please close this issue. 

thanks again

**Comment by ajalex909** [comment]
I am getting the same error 401 as above. I am running ansible 2.0 in aws cloud. I am able to ping linux servers but for windows its through the below error. I have followed the documentation as it is.

ubuntu@ansiblecontroller:~/playbooks$ ansible-playbook windowsupdates.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
fatal: [CFTesting.xxxx.xxxxxx.local]: FAILED! => {"failed": true, "msg": "ERROR! ssl: 401 Unauthorized."}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
CFTesting.xxxx.xxxxxx.local : ok=0    changed=0    unreachable=0    failed=1

**Comment by jhawkesworth** [comment]
@ajalex909  please see my comment on https://github.com/ansible/ansible/issues/13977

If you still have a problem I'd recommend opening a new issue, rather than commenting on closed tickets as your comments may not be noticed.
