### ISSUE TITLE
Ansible docs links on Google throw 404

### ISSUE THREAD

**Issue by bryandowning** [ansible/ansible#13717]
##### Issue Type:

Documentation Report
##### Ansible Version:

N/A
##### Ansible Configuration:

N/A
##### Environment:

Chrome on OSX
##### Summary:

The Ansible docs were moved to http://docs.ansible.com/ansible/, but Google has page results cached for http://docs.ansible.com/. The is no redirect in place, so all links from Google 404.
##### Steps To Reproduce:
- Google "ansible file"
- Click the first link
##### Expected Results:

The link should redirect to http://docs.ansible.com/ansible/list_of_files_modules.html
##### Actual Results:

The link throws a 404: http://docs.ansible.com/list_of_files_modules.html

**Comment by bcoca** [comment]
we had missed the redirect when we migrated the docs to a new host, it is working now.
