### ISSUE TITLE
Ansible documentation site is down

### ISSUE THREAD

**Issue by conorgil** [ansible/ansible#13711]
I am getting a 404 on all pages which I try to visit on the documentation site (https://docs.ansible.com/).

**Comment by bahrmichael** [comment]
same for community page http://docs.ansible.com/community.html

**Comment by conorgil** [comment]
the entire subdomain appears to be offline

**Comment by bessarabov** [comment]
I also got 404 some time ago, but now https://docs.ansible.com/ is working fine.

**Comment by jimi-c** [comment]
Closing, as the docs issue isn't really an Ansible core issue, and we've been working on getting a workaround stood up.

Thanks!
