### ISSUE TITLE
local connection + sudo + pipelining + raw fails waiting for password prompt

### ISSUE THREAD

**Issue by abadger** [ansible/ansible#13728]
```
$ ansible -m raw localhost -a 'echo connection' --sudo -K -vvvv -c local          
Using /etc/ansible/ansible.cfg as config file
SUDO password: 
Loaded callback minimal of type stdout, v2.0
ESTABLISH LOCAL CONNECTION FOR USER: badger
127.0.0.1 EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=dsvxgavwyxalsjrucewuzwdyxmpasolo] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-dsvxgavwyxalsjrucewuzwdyxmpasolo; echo connection'"'"''
localhost | FAILED | rc=0 >>
ERROR! privilege output closed while waiting for password prompt:
BECOME-SUCCESS-dsvxgavwyxalsjrucewuzwdyxmpasolo
connection


[pts/36@roan /srv/ansible/ansible-friday]$ ansible -m raw localhost -a '/bin/echo connection' --sudo -K -vvvv -c local
SUDO password: 
localhost | SUCCESS | rc=0 >>
connection


[pts/36@roan /srv/ansible/ansible-friday]$ ansible -m raw -i 'rhel7-test,' '*' -a 'echo connection' --sudo -K
SUDO password: 
rhel7-test | SUCCESS | rc=0 >>

connection


[pts/36@roan /srv/ansible/ansible-friday]$ ansible -m raw -i 'rhel7-test,' '*' -a '/bin/echo connection' --sudo -K
SUDO password: 
rhel7-test | SUCCESS | rc=0 >>

connection


[pts/36@roan /srv/ansible/ansible-friday]$                                                      *[devel]  (20:03:38)
```

The first run is the problem run.  The rest work.  Could it be a problem with the echo shell builtin (since the version with full path to echo works?)  I also notice that the full path to echo but still running on localhost has one less newline in its output (between the header and "connection") than the output when run over ssh.  Maybe that's a clue?

This does work in 1.9.x:

```
$ ansible -m raw localhost -a 'echo connection' --sudo -K
SUDO password: 
localhost | success | rc=0 >>
connection

$
```

**EDIT:** pipelining must be on

**Comment by Yannig** [comment]
I don't know but this issue seems to be related https://github.com/ansible/ansible/pull/13636

**Comment by amenonsen** [comment]
(Sorry, I wasn't paying attention to this before.)

> Could it be a problem with the echo shell builtin (since the version
> with full path to echo works?)

Here's the code from local.py:

```
become_output = ''
while not self.check_become_success(become_output) and not self.check_password_prompt(become_output):

    rfd, wfd, efd = select.select([p.stdout, p.stderr], [], [p.stdout, p.stderr], self._play_context.timeout)
    if p.stdout in rfd:
        chunk = p.stdout.read()
    elif p.stderr in rfd:
        chunk = p.stderr.read()
    else:
        stdout, stderr = p.communicate()
        raise AnsibleError('timeout waiting for privilege escalation password prompt:\n' + become_output)
    if not chunk:
        stdout, stderr = p.communicate()
        raise AnsibleError('privilege output closed while waiting for password prompt:\n' + become_output)
        become_output += chunk
    if not self.check_become_success(become_output):
        p.stdin.write(self._play_context.become_pass + '\n')
```

Here we start by select()ing on the output of the subprocess. Our first
p.stdout.read() results in 'BECOME-SUCCESS-xxx\nconnection\n', which is
added to become_output. The proximate cause of the problem is that
check_become_success() still returns False because it does:

```
    return self._play_context.success_key == output.rstrip()
```

So it's expecting a single line of output, not multiple lines. We should
certainly not change that (it solved various related and easy-to-trigger
problems in ssh.py), but even if we did change it (e.g., to
`success_key in output`), it would **still** be wrong, because the
"connection\n" part of the output would be silently lost.

Summary:
1. #13636 is wrong (i.e., it only hides the problem).
2. It breaks particularly for the shell builtin because the
   BECOME-SUCCESS string and the echo output are returned together; in
   the other cases, there's an exec() in between, so it's a later read
   that returns the actual output.
3. The real fix is to accumulate output from the subprocess, go through
   it line-by-line and take prompt/success decisions based on only the
   relevant line.

@Yannig do you feel like making that change? It would be nearly a
straight port of the logic from ssh.py.

**Comment by Yannig** [comment]
@amenonsen thanks for your feedback

I have already conclude that https://github.com/ansible/ansible/pull/13636 was wrong. After looking at ssh code, was wondering if it maybe a better way of retrieving this code. I was also wondering if it maybe possible to get some common code in parent class.

But anyway, I'll try to do that and if I get some drawback, I'll keep you in touch.

**Comment by amenonsen** [comment]
@Yannig Sounds good. I'm happy to help if you have any questions. Thanks for working on this.

**Comment by Yannig** [comment]
After digging into this issue, I found that the problem come from a bad success_key value. Here is a simple one line patch that fix this issue:

``` patch
diff --git a/lib/ansible/plugins/action/__init__.py b/lib/ansible/plugins/action/__init__.py
index 3f4fff5..2970d38 100644
--- a/lib/ansible/plugins/action/__init__.py
+++ b/lib/ansible/plugins/action/__init__.py
@@ -505,6 +505,7 @@ class ActionBase(with_metaclass(ABCMeta, object)):
             cmd = self._play_context.make_become_cmd(cmd, executable=executable)

         display.debug("_low_level_execute_command(): executing: %s" % (cmd,))
+        self._connection._play_context = self._play_context
         rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)

         # stdout and stderr may be either a file-like or a bytes object.
```

I'm now looking after this to understand why we change this connection reference (or why we don't have the same value).

**Comment by Yannig** [comment]
@amenonsen: what do you think about?

**Comment by amenonsen** [comment]
@Yannig your patch may be correct, but it doesn't fix the problem:

```
$ ansible -m raw localhost -a 'echo connection' --sudo -K -vvvv                
No config file found; using defaults
SUDO password: 
Loaded callback minimal of type stdout, v2.0
ESTABLISH LOCAL CONNECTION FOR USER: ams
127.0.0.1 EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=bwartzdfocuvrmbkioqjfsjwzuklkrwa] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-bwartzdfocuvrmbkioqjfsjwzuklkrwa; echo connection'"'"''
localhost | FAILED | rc=0 >>
ERROR! privilege output closed while waiting for password prompt:
BECOME-SUCCESS-bwartzdfocuvrmbkioqjfsjwzuklkrwa
connection
```

AFAICS, the problems I pointed out in my earlier mail are still relevant, whether or not the success key is correctly set.

**Comment by Yannig** [comment]
@amenonsen Thanks for your feedback.

The patch above works this time:

```
ansible -m raw localhost -a 'echo connection' --sudo -K -vvvv
Using /etc/ansible/ansible.cfg as config file
SUDO password: 
Loaded callback minimal of type stdout, v2.0
ESTABLISH LOCAL CONNECTION FOR USER: yannig
127.0.0.1 EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=nzwyjtrkuutfvtvmlvikqzfoznbrcsjh] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-nzwyjtrkuutfvtvmlvikqzfoznbrcsjh; echo connection'"'"''
localhost | SUCCESS | rc=0 >>
connection
```

I have also tried to port local connector against the same code as ssh plugin but the work seems to be quite big. What about fixing this issue quickly for the moment and have a bigger refactoring for a next big version?

It maybe a good idea to share common code on a new class to avoid duplicate effort but it may need some refactoring.

**Comment by Yannig** [comment]
Last, I have a little patch laying around that add a little more of clarity whether or not to launch make_become_cmd. Here it is:

``` patch
diff --git a/lib/ansible/playbook/play_context.py b/lib/ansible/playbook/play_context.py
index 6b19f4c..3125a13 100644
--- a/lib/ansible/playbook/play_context.py
+++ b/lib/ansible/playbook/play_context.py
@@ -413,6 +413,9 @@ class PlayContext(Base):

         return new_info

+    def check_make_become_cmd(self):
+        return self.become and (C.BECOME_ALLOW_SAME_USER or not (self.become_user == self.remote_user))
+
     def make_become_cmd(self, cmd, executable=None):
         """ helper function to create privilege escalation commands """

diff --git a/lib/ansible/plugins/action/__init__.py b/lib/ansible/plugins/action/__init__.py
index 79a7311..37c57c9 100644
--- a/lib/ansible/plugins/action/__init__.py
+++ b/lib/ansible/plugins/action/__init__.py
@@ -500,9 +500,7 @@ class ActionBase(with_metaclass(ABCMeta, object)):
             display.debug("_low_level_execute_command(): no command, exiting")
             return dict(stdout='', stderr='')

-        allow_same_user = C.BECOME_ALLOW_SAME_USER
-        same_user = self._play_context.become_user == self._play_context.remote_user
-        if sudoable and self._play_context.become and (allow_same_user or not same_user):
+        if sudoable and self._play_context.check_make_become_cmd():
             display.debug("_low_level_execute_command(): using become for this command")
             cmd = self._play_context.make_become_cmd(cmd, executable=executable)
             # Updating connection context to share same success_key
```

**Comment by Yannig** [comment]
What do you think about?

**Comment by amenonsen** [comment]
@Yannig I can't understand how your fix works when the first `.read()` returns `BECOME-SUCCESS-xxx\nconnection\n`. I'm convinced by your analysis that the wrong success key is being passed in, but even once that's fixed, `check_become_success()` will work only by accident with multiline input.

**Comment by ktaragorn** [comment]
@Yannig @amenonsen Feels like the solution you guys are discussing fits my problem better than the one in this post. @Yannig 's one liner fixes my issue perfectly but I still see this test failing.

**Comment by ktaragorn** [comment]
Hi guys I figured out this problems probable solution. In `ssh.py` they use `for l in chunk.splitlines(True):` Split lines would take care of this multiline issue I believe??

**Comment by ktaragorn** [comment]
We probably need to port over `_examine_output` from `ssh.py` to get this issue fixed

**Comment by Yannig** [comment]
@ktaragorn Thanks for you feedback. Can you please provide a way to reproduce the problem you are talking about?

**Comment by ktaragorn** [comment]
@Yannig I am running this on an ansible with the changes of my PR applied

```
karthikt@Karthiks-MacBook-Pro:~/Documents/work/<folder>/ansible (ruby-2.3.0 u=)
$ ansible -m raw localhost -a 'echo connection' --sudo -K -vvvv
Using /Users/karthikt/Documents/work/travelmob_2_3_bac/ansible/ansible.cfg as config file
SUDO password:
Loaded callback minimal of type stdout, v2.0
ESTABLISH LOCAL CONNECTION FOR USER: karthikt
localhost EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=utolysmvclgnlrmsadycjmgppnjfrgau] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-utolysmvclgnlrmsadycjmgppnjfrgau; echo connection'"'"''
localhost | SUCCESS | rc=0 >>
connection



karthikt@Karthiks-MacBook-Pro:~/Documents/work/<folder>/ansible (ruby-2.3.0 u=)
$ ansible -m raw localhost -a 'echo connection' --sudo -K -vvvv
Using /Users/karthikt/Documents/work/travelmob_2_3_bac/ansible/ansible.cfg as config file
SUDO password:
Loaded callback minimal of type stdout, v2.0
ESTABLISH LOCAL CONNECTION FOR USER: karthikt
localhost EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=ghddlarjcczcifaeuxdymhduuqtufkut] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-ghddlarjcczcifaeuxdymhduuqtufkut; echo connection'"'"''
localhost | FAILED | rc=0 >>
ERROR! privilege output closed while waiting for password prompt:
BECOME-SUCCESS-ghddlarjcczcifaeuxdymhduuqtufkut
connection


```

As you can see your test case passes in 1 round but repeating again causes a failure. This is with sudo timing out with a non 0 timeout

**Comment by ktaragorn** [comment]
I am not yet sure why the first round succeeds but the 2nd failure is very likely due to the `become_output` having multiple lines. This is avoided in `ssh.py` by doing `chunk.splitlines` (BTW i agree with you it is sad that there is so much duplicated effort and logic here)

**Comment by ktaragorn** [comment]
You are also probably right in your guess that this is something to do with the `echo` built in, since I was able to get it to work with `ls` along with your own `/bin/echo`. But the fix will take care of that as well i would think.

**Comment by ktaragorn** [comment]
This issue can be fixed by changing the 2 `read` calls to `readline`. This is a similar effect as the `splitlines` call. The command succeeds, but I am not sure if it has any other adverse effects

**Comment by amenonsen** [comment]
Whether it succeeds or not is just a question of whether the output is flushed between the success key and the program output. When using the builtin, it probably isn't; when executing an external program, it is. So if the read() returns a single-line string, it works.

**Comment by ktaragorn** [comment]
That's probably it

**Comment by Yannig** [comment]
@ktaragorn I think the following patch will resolve your issue:

``` patch
diff --git a/lib/ansible/plugins/connection/__init__.py b/lib/ansible/plugins/connection/__init__.py
index ff00bc0..bea8e5b 100644
--- a/lib/ansible/plugins/connection/__init__.py
+++ b/lib/ansible/plugins/connection/__init__.py
@@ -206,7 +206,10 @@ class ConnectionBase(with_metaclass(ABCMeta, object)):
         pass

     def check_become_success(self, output):
-        return self._play_context.success_key == output.rstrip()
+        for line in output.splitlines(True):
+            if self._play_context.success_key == line.rstrip():
+                return True
+        return False

     def check_password_prompt(self, output):
         if self._play_context.prompt is None:
```

Can you confirm?

**Comment by ktaragorn** [comment]
@Yannig when you say my issue you mean this issue or #13763??
This patch might resolve this issue, but is much more of a change than just changing the `.read` to `.readline` as I have mentioned earlier.

This patch will not solve #13763 and I repeat your understanding is flawed.. both of these issues are independent of each other.

Your comment mentions #13763 and I have tested your patch without my fix. It fails with `privilege output closed while waiting for password prompt:` without `,timestamp_timeout=0` in visudo and with `timeout waiting for privilege escalation password prompt` if the timeout is present.

**Comment by abadger** [comment]
Thanks @Yannig for the fix, @amenonsen and @ktaragorn for the reviews and analysis.  Fix applied to devel and to stable-2.0.

**Comment by chronos-tachyon** [comment]
What's the timeline on a new PPA release with the bugfix?

**Comment by onnimonni** [comment]
I'm still having this issue on ansible `2.1.1.0`.

It works for ansible versions `1.9.6` and `2.0.2.0`

Connection: local
System: OS X 10.11.6

```
$ ansible -m raw localhost -a 'echo connection' --sudo -K -vvvv
No config file found; using defaults
SUDO password:
Loaded callback minimal of type stdout, v2.0
ESTABLISH LOCAL CONNECTION FOR USER: onnimonni
127.0.0.1 EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=owfibcjxqucbqimxkcvlfqhrcuhrnkez] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-owfibcjxqucbqimxkcvlfqhrcuhrnkez; echo connection'"'"''
localhost | FAILED | rc=0 >>
ERROR! privilege output closed while waiting for password prompt:
BECOME-SUCCESS-owfibcjxqucbqimxkcvlfqhrcuhrnkez
connection
```
