### ISSUE TITLE
No handlers could be found for logger "paramiko.transport"

### ISSUE THREAD

**Issue by rbairi** [ansible/ansible#13721]
I've installed python 2.7.11, and ansible 1.9.4. . But testing the installation with simple ansible ping is failing. Ansible 2 also gives the same error. (My LINUX version:  2.6.32-431.29.2.el6.x86_64 #1 SMP). Both paramiko and pycrypto seem to be up to date.
# ERROR
# ansible all -m ping

No handlers could be found for logger "paramiko.transport"
127.0.0.1 | FAILED => FAILED: Error reading SSH protocol banner[Errno 104] Connection reset by peer
# python -V

Python 2.7.11
# pip install --upgrade paramiko

Requirement already up-to-date: paramiko in /usr/local/lib/python2.7/site-packages/paramiko-1.16.0-py2.7.egg
Requirement already up-to-date: pycrypto!=2.4,>=2.1 in /usr/local/lib/python2.7/site-packages/pycrypto-2.6.1-py2.7-linux-x86_64.egg (from paramiko)
Requirement already up-to-date: ecdsa>=0.11 in /usr/local/lib/python2.7/site-packages/ecdsa-0.13-py2.7.egg (from paramiko)
# pip install --upgrade pycrypto

Requirement already up-to-date: pycrypto in /usr/local/lib/python2.7/site-packages/pycrypto-2.6.1-py2.7-linux-x86_64.egg
# cat $ANSIBLE_HOSTS

127.0.0.1
# ansible --version

ansible 1.9.4
  configured module search path = None
# Similar error with Ansible 2
# ansible --version

ansible 2.1.0
  config file =
  configured module search path = Default w/o overrides
# ansible all -m ping

No handlers could be found for logger "paramiko.transport"
127.0.0.1 | UNREACHABLE! => {
    "changed": false,
    "msg": "ERROR! Error reading SSH protocol banner[Errno 104] Connection reset by peer",
    "unreachable": true
}

**Comment by chrrrles** [comment]
Could not reproduce your problem with python 2.7.11 on ansible 2.0 or stable.  May you paste the output from running the command in verbose mode (-vvvv)?

**Comment by rbairi** [comment]
I found the problem.
I was not able to ssh to 127.0.0.1.
When I replaced with fully qualified name of the host or the actual IP, it worked.
Sorry for the inconvenience. This can be closed.
