### ISSUE TITLE
expanduser resolves home dir on master not target

### ISSUE THREAD

**Issue by j3p0uk** [ansible/ansible#13734]
If expanduser is used to resolve a path this resolves on the local master, which means the machine upon which ansible is executed must have the correct resolution of the home directory as opposed to the target machine.

I would expect that the target machine should always be used to resolve the expanduser filter, as a flow where I create a user, and then want to copy files into that users home directory should work.

**Comment by bcoca** [comment]
This is expected, all filters act on data on the 'master', most modules that use path do expand user and expand vars themselves remotely, if they don't that should be added to the specific module.

**Comment by j3p0uk** [comment]
OK – I could open a separate issue about the mount module, but it seems like the sort of boilerplate that should be shared code, rather than pushed into all of the different modules.

Is there a better way for me to raise the issue?

Thanks, 
JP :)

**Comment by bcoca** [comment]
there is boilerplate in 2.0, the module just has to declare an option as type 'path', which will automatically do this.
