### ISSUE TITLE
'ansible-galaxy install' is completely unusable when any flags are passed

### ISSUE THREAD

**Issue by habnabit** [ansible/ansible#13743]
**Issue Type:** Bug Report

**Ansible Version:** 2.0.0. The bug was introduced in 21775d7866c7953d4d953c271c0a18e227e4bc66, and is still present in fcd074d40f32ef52ed286678293984125ff51008, which is the version I discovered it in.

**Ansible Configuration:** None. This occurs before I can even get to running `ansible-playbook` at all, as `ansible-galaxy` is failing to do anything.

**Environment:** Discovered on ubuntu 14.04; verified and git-bisected on OS X 10.11.

**Summary:**

`ansible-galaxy install` (and presumably other subcommands too) no longer accepts any flags.

**Steps To Reproduce:**

`ansible-galaxy install -f`

**Expected Results:**

```
Usage: ansible-galaxy install [options] [-r FILE | role_name(s)[,version] | scm+role_repo_url[,version] | tar_file(s)]

Options:
  -f, --force           Force overwriting an existing role
  -h, --help            show this help message and exit
  -c, --ignore-certs    Ignore SSL certificate validation errors.
  -i, --ignore-errors   Ignore errors and continue with the next specified
                        role.
  -n, --no-deps         Don't download roles listed as dependencies
  -r ROLE_FILE, --role-file=ROLE_FILE
                        A file containing a list of roles to be imported
  -p ROLES_PATH, --roles-path=ROLES_PATH
                        The path to the directory containing your roles. The
                        default is the roles_path configured in your
                        ansible.cfg file (/etc/ansible/roles if not
                        configured)
  -s API_SERVER, --server=API_SERVER
                        The API server destination
  -v, --verbose         verbose mode (-vvv for more, -vvvv to enable
                        connection debugging)
  --version             show program's version number and exit
ERROR! - you must specify a user/role name or a roles file
```

**Actual Results:**

```
Usage: ansible-galaxy [delete|import|info|init|install|list|login|remove|search|setup] [--help] [options] ...

ansible-galaxy: error: no such option: -f
```

**Comment by habnabit** [comment]
It appears that the issue is that `self.parser.parse_args()` is called before `self.parser.add_option(...)` is called for subcommand-specific options. Hacking subcommands into optparse seems to be a losing prospect. I _personally_ would suggest using [click](http://click.pocoo.org/6/) for argument parsing.

**Comment by bcoca** [comment]
this was fix for #12004, which I should have tested with arguments that are ONLY available when specifying an action.

**Comment by bcoca** [comment]
reverted offending commit

**Comment by mrlesmithjr** [comment]
Is this issue resolved or not? I am getting the following error which has never been an issue until upgrading to 2.0.
Unexpected Exception: local variable 'f' referenced before assignment

running the following
ansible-galaxy install -r requirements.yml -p ./ -i -f

and will -vvv the traceback is
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 85, in <module>
    sys.exit(cli.run())
  File "/Library/Python/2.7/site-packages/ansible/cli/galaxy.py", line 152, in run
    self.execute()
  File "/Library/Python/2.7/site-packages/ansible/cli/**init**.py", line 99, in execute
    fn()
  File "/Library/Python/2.7/site-packages/ansible/cli/galaxy.py", line 399, in execute_install
    installed = role.install()
  File "/Library/Python/2.7/site-packages/ansible/galaxy/role.py", line 289, in install
    self._write_galaxy_install_info()
  File "/Library/Python/2.7/site-packages/ansible/galaxy/role.py", line 139, in _write_galaxy_install_info
    f.close()
UnboundLocalError: local variable 'f' referenced before assignment

**Comment by abadger** [comment]
This issue is resolved.  The traceback you are getting is a different problem (yours is about a variable named "f" while this issue was about passing the "-f" command line flag.)

I think I see what the problem is that you're encountering.  Give me a few minutes and I think I can work up something to fix it.

**Comment by abadger** [comment]
That should fix the traceback.  Pushed to both devel and stable-2.0.  note that I'm not 100% sure what is causing the file to fail to open.  It's possible that I've solved the traceback but there's still some troubleshooting that needs to be done beyond that.

**Comment by mrlesmithjr** [comment]
Cool. I will do some additional testing tomorrow.

On Wed, Jan 13, 2016 at 11:55 PM, Toshio Kuratomi notifications@github.com
wrote:

> That should fix the traceback. Pushed to both devel and stable-2.0. note
> that I'm not 100% sure what is causing the file to fail to open. It's
> possible that I've solved the traceback but there's still some
> troubleshooting that needs to be done beyond that.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible/issues/13743#issuecomment-171529531.

## 

Twitter @mrlesmithjr http://twitter.com/mrlesmithjr
Blog EverythingShouldBeVirtual.com
Interested in blog sponsorship? Go to http://bit.ly/10Aj7Sq

**Comment by mrlesmithjr** [comment]
Just re-read what you mentioned. I was indeed getting this traceback when using -f with ansible-galaxy
ansible-galaxy install -r requirements.yml -p ./ -i -f

w/out using -f it runs just fine.
