### ISSUE TITLE
ERROR! Include tasks should not specify tags in more than one way (both via args and directly on the task)

### ISSUE THREAD

**Issue by ktosiek** [ansible/ansible#13753]
##### Ansible Version:

ansible-playbook 2.0.0 (stable-2.0 fcd074d40f) last updated 2016/01/07 12:20:55 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 0b8ae0da8b) last updated 2016/01/07 12:21:00 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 5b47600c2b) last updated 2016/01/07 12:21:00 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### Summary:

The "tag style mixing" message shows up where it doesn't really make sense - I'm mixing styles between import levels, and not on a single import.
##### Steps To Reproduce:

Run `ansible-playbook -i localhost, -c local site.yml`

site.yml

```
- hosts: all
  tasks:
    - include: tagging.yml
      tags: aaa
```

tagging.yml

```
- include: tagged.yml tags=bbb
```

tagged.yml

```
- shell: echo yup!
```
##### Expected Results:

The playbook running.
##### Actual Results:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [include] *****************************************************************
included: /home/tkontusz/ansible-tags/tagging.yml for localhost

TASK [include] *****************************************************************
ERROR! Include tasks should not specify tags in more than one way (both via args and directly on the task)

The error appears to have been in '/home/tkontusz/ansible-tags/tagging.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- include: tagged.yml tags=bbb
  ^ here


PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```

**Comment by jimi-c** [comment]
Yes, this is a minor change to prevent problems with includes in 2.0. Your second include should use tags as a task-level parameter rather than as a parameterized argument:

<pre>
- include: tagged.yml
  tags: bbb
</pre>

**Comment by ktosiek** [comment]
Oh, so it is about mixing those two styles in one _playbook_, not one_task_? If so, I got mislead by the message.

Dnia 11 stycznia 2016 18:06:32 CET, James Cammarata notifications@github.com napisał(a):

> Yes, this is a minor change to prevent problems with includes in 2.0.
> Your second include should use tags as a task-level parameter rather
> than as a parameterized argument:
> 
> <pre>
> - include: tagged.yml
>  tags: bbb
> </pre>
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ansible/ansible/issues/13753#issuecomment-170619550

## 

Wysłane za pomocą K-9 Mail.

**Comment by jimi-c** [comment]
Well, it is on the task. It's due to the way they're merged from the parent include. To that task, it looks like tags are set in two places.

**Comment by selivan** [comment]
Had the same problem. I suggest to change error message to ''Include tasks should not specify tags in more than one way (both via args and directly on the task). Mixing tag specify styles is prohibited for whole import hierarchy, not only for single import statement."

**Comment by ktosiek** [comment]
@selivan this looks much better, can you make a PR? I hope it'll get merged.

**Comment by selivan** [comment]
@ktosiek done: https://github.com/ansible/ansible/pull/14031

**Comment by ktosiek** [comment]
Fixed in #14031

**Comment by mcameron** [comment]
Distinct galaxy roles with different maintainers have to agree on a tag style?

**Comment by ktosiek** [comment]
@mcameron no, they have to change to the new style :-)

**Comment by mcameron** [comment]
Which style is 'new'?

**Comment by ktosiek** [comment]
The more structured one, tags: [a, b, c]

Dnia 21 marca 2016 14:51:56 CET, Max Cameron notifications@github.com napisał(a):

> Which style is 'new'?
> 
> ---
> 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/ansible/ansible/issues/13753#issuecomment-199290357

## 

Wysłane za pomocą K-9 Mail.

**Comment by mcameron** [comment]
Hey @galaxydevelopers, you heard it hear first: there's a new specification in town, it's been finalised in a github comment on a closed issue, now go and change your modules. _sigh_  Hope you can see how this negatively affects the experience for ansible end users.
