### ISSUE TITLE
Breaking change to roles between v2.0.0-0.8.rc3 and v2.0.0-0.9.rc4

### ISSUE THREAD

**Issue by devoncrouse** [ansible/ansible#13757]
Hello,

We noticed a regression back to 0.9.x behavior for finding roles between these two tags:

With `playbooks` and `roles` in the same directory, running something like the following was working fine:

``` bash
ansible-playbook [options] playbooks/myplaybook.yaml
```

With v2.0.0-0.9.rc4, it can no longer find the roles referenced in the playbook:

```
ERROR! the role 'myrole' was not found in /Users/devon.crouse/projects/myproject/playbooks/roles:/Users/devon.crouse/projects/myproject/playbooks:/etc/ansible/roles
```

Was this an intentional change?

**Comment by bcoca** [comment]
roles should be in the expected paths, either adjacent to the playbook (looking first in roles subdir) or in a common roles directory.

i'm not sure where you expected them to be found

**Comment by devoncrouse** [comment]
The following organization works on rc3, but not rc4... So unless there was a known breaking change, I would expect them to continue to be found there.

```
drwxr-xr-x   5 devon.crouse  staff   170B Jan  7 10:44 group_vars
drwxr-xr-x@ 21 devon.crouse  staff   714B Jan  7 10:44 roles
drwxr-xr-x   5 devon.crouse  staff   170B Jan  7 15:11 playbooks
```

**Comment by bcoca** [comment]
not sure how that works as roles are not searched for in directories above playbooks, even in rc3

**Comment by bcoca** [comment]
So this ONLY works if your current working directory is that one, rc3 mistakenly used 'cwd' to load roles, this is not a pattern we want, if you ran same playbook from your home, a temp dir, etc it would also fail.

This is expected behavior and not the one you saw in rc3, closing this ticket.

**Comment by devoncrouse** [comment]
Okay, thanks.
