### ISSUE TITLE
local_action fails on localhost

### ISSUE THREAD

**Issue by jkleint** [ansible/ansible#1377]
It seems `local_action` tries to run on `127.0.0.1`, which is not the same as `localhost`:

```
- hosts: localhost    # This can be anything
  tasks: 
  - local_action: command echo This is local.
```

```
$ ANSIBLE_NOCOWS=1 ansible-playbook localaction.yml 

PLAY [localhost] ********************* 

GATHERING FACTS ********************* 
ok: [localhost]

TASK: [command echo This is local.] ********************* 
fatal: [localhost] => host not found: 127.0.0.1

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************* 
localhost                      : ok=1    changed=0    unreachable=1    failed=0    
```

If I add `127.0.0.1` to my `hosts`, it works fine; but with `localhost` in my `hosts`, it does not.  (This is with revision 6aafb42f).

**Comment by mpdehaan** [comment]
local_action is intended to force the connection type to local as well.

I need to investigate what happened to that, which will solve your problem
via another means.

(Still curious about your OS/configuration and what you did to disable that
working...)

**Comment by mpdehaan** [comment]
was misreading this earlier -- just a host inventory thing, not a network
thing.  ok.

you shouldn't need it in inventory, so two things should happen ... (A) it
should try both, (B) it should be cool if it isn't in either

**Comment by mpdehaan** [comment]
should be covered by #1378 (in part)

I still need to make sure the connection type is overriden.

**Comment by mpdehaan** [comment]
and... done
