### ISSUE TITLE
Ansible 2.0 prompts for vars_prompt when --extra-vars is used

### ISSUE THREAD

**Issue by chlunde** [ansible/ansible#13770]
##### Issue Type

Bug Report
##### Ansible Version

2.0 from the "stable-2.0" branch, commit 91c7691a92e63580216e0e5c657b689361330beb

```
$ ansible --version
ansible 2.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### Ansible Configuration

No changes
##### Environment

RHEL 7
##### Summary

Ansible 2.0 stops execution and requests the user to enter variables specified with `vars_prompt` even if the same variable has been specified on the comand line.

Ansible 1.9.4 does not prompt for `vars_prompt` if `--extra-vars` specifies the same variable.
###### playbook.yml

``` yaml

---
- hosts: all
  gather_facts: False
  vars_prompt:
    - name: x
      prompt: 'Enter value for x'
  tasks:
    - local_action: debug var=x
```

```
$ cat inventory
localhost

$ ansible-playbook -i inventory playbook.yml -e x=1
```
##### Expected Results:

Non-interactive run, as on 1.9.4:

```
$ ansible-playbook --version
ansible-playbook 1.9.4
  configured module search path = None

$ ansible-playbook -i inventory playbook.yml -e x=foo

PLAY [all] ********************************************************************

TASK: [debug var=x] ***********************************************************
ok: [localhost -> 127.0.0.1] => {
    "var": {
        "x": "foo"
    }
}

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```
##### Actual Results:

The user is prompted:

```
$ ansible-playbook -i inventory playbook.yml -e x=foo
Enter value for x:
```

**Comment by bcoca** [comment]
so there is code that checks for this (and it used to work) https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/playbook_executor.py#L114

But for some reason `play.vars` is now always empty.

**Comment by bcoca** [comment]
@chlunde can you test the PR above and confirm the fix?

**Comment by chlunde** [comment]
Thanks! It works as expected on my playbook now.

**Comment by ThomasSteinbach** [comment]
Where is this behavior documented? I can't find anything in the official docs.

**Comment by bcoca** [comment]
Since extra vars have higher priority than play vars, it makes sense that there is no need to prompt for a value you have already overridden. Still, we should make note in vars_prompts docs about this.
