### ISSUE TITLE
Include in ansible.cfg

### ISSUE THREAD

**Issue by luqasz** [ansible/ansible#13781]
Hi

I know that `ansible.cfg` files are not merged. Do you plan to (or will accept pull requests) implement `include` statements ? For me, it would be very useful since I do use `ssh_args=""` and I do not want to uncomment it every time I do a checkout from git.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
