### ISSUE TITLE
Ansible 2.0.0 treats union as union | unique

### ISSUE THREAD

**Issue by artur-fijalkowski-sap** [ansible/ansible#13799]
- debug: msg="{{ [2,2,2,2] | union([1,1,1,1]) }}"

Outputs following array:
[ 2, 1]

This means union worked as union | unique instead.

**Comment by bcoca** [comment]
they are 'set theory' filters, which operate on unique lists (sets)

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by artur-fijalkowski-sap** [comment]
Ok. So what is the operator that can be used to merge two arrays?

**Comment by bcoca** [comment]
```
- debug: msg="{{ [2,2,2,2] + [1,1,1,1] }}"
```
