### ISSUE TITLE
ansible setup file is not per-session unique

### ISSUE THREAD

**Issue by skvidal** [ansible/ansible#138]
If I am running ansible from multiple sessions on the same set of machines - doing very different things:

for example one session from a cron job retrieving certain specific information
and another session from the cli issuing a 'do this now command' 

then /etc/ansible/setup is in a race to be written from those two sessions.

It would be best if the file was copied to the tmpdir that ansible makes, modified/updated and then atomically written back to /etc/ansible/setup (if we even want /etc/ansible/setup to be written back on each run, instead of being a configurable location to edit for future runs).

**Comment by mpdehaan** [comment]
we are going to make it username-hostname unique at least, in the proposal to remove the delete_files logic

**Comment by mpdehaan** [comment]
going to be resolved by #133
