### ISSUE TITLE
module not identified in "missing interpreter line" error message

### ISSUE THREAD

**Issue by MikeSpreitzer** [ansible/ansible#13816]
lib/ansible/plugins/action/**init**.py includes this:

``` python
        if not shebang:
            raise AnsibleError("module is missing interpreter line")
```

This is not as helpful as it could be.  It would be better if this message identified the module in question.

**Comment by MikeSpreitzer** [comment]
PR #11561 attempted to fix this, but was misdirected at the extinct testing directory branch headed by "v1".  I will make a new PR that fixes this correctly.

**Comment by MikeSpreitzer** [comment]
Thanks, @bcoca, for the quick fix.  Can you please back-port this to 1.9 too?

**Comment by bcoca** [comment]
if we start working on a 1.9 release, i'll add this to the wishlist
