### ISSUE TITLE
Problem with my self developed shell module

### ISSUE THREAD

**Issue by ilove2git** [ansible/ansible#13811]
hi,

  I wrote a simple shell script and made it as Ansible module with putting it under Library Path. I ran the module and got the failure message. However, I can tell from the output message that the shell module has been run actually. So I don't understand why Ansible returns such failure message.

Below has the detail, the OS type of target system is AIX

root@b1a52ef5f33f:/usr/share/my_modules# ansible aix -m getos
9.123.195.164 | FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "",
    "module_stdout": "AIX lpar1 1 7 00CB4D6E4C00\r\n",
    "msg": "MODULE FAILURE",
    "parsed": false
}

root@b1a52ef5f33f:/usr/share/my_modules# cat getos
# !/bin/sh

uname -a

Meanwhile, I used the test-module utility to test my shell module and see error with "ValueError: No JSON object could be decoded". So I assume that is the root cause maybe. 

root@b1a52ef5f33f:/ansible# hacking/test-module -m /usr/share/my_modules/getos
- including generated source, if any, saving to: /root/.ansible_module_generated
- this may offset any line numbers in tracebacks/debuggers!
  ***********************************
  RAW OUTPUT
  Linux b1a52ef5f33f 4.1.13-boot2docker #1 SMP Fri Nov 20 19:05:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

---

INVALID OUTPUT FORMAT
Linux b1a52ef5f33f 4.1.13-boot2docker #1 SMP Fri Nov 20 19:05:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Traceback (most recent call last):
  File "hacking/test-module", line 167, in runtest
    results = json.loads(out)
  File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

I'm not sure whether i am right. But even so, i still have no idea how to solve my problem.

Would you please help me out? Thanks very much

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- IRC: #ansible-devel on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case, modules need to return JSON to Ansible, from the stdout i can see you are just returning plain text.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
