### ISSUE TITLE
No detailed examples for expect module' usage for playbook

### ISSUE THREAD

**Issue by alwqx** [ansible/ansible#13810]
Hi everyone:
I use ansible , AWS (China regin) and Docker. I want to pull a docker image from third party registry. To do this I should first run `docker login daocloud.io`. So I use [`expect module`](http://docs.ansible.com/ansible/expect_module.html). Bellow is my playbook:

```
  - hosts: mesos_slave
    remote_user: ec2-user
    sudo: yes
    vars:
      - dc_path: /home/ec2-user/deploy/mesos-slave
    tasks:
    - name: mkdir deploy diretory
      command: /usr/bin/mkdir -p /home/ec2-user/deploy/mesos-slave
   ..........
    - expect:
        command: docker login daocloud.io
        responses:
          - Username: foo
          - Password: bar
          - Email: foo@126.com
```

When I run `ansible-playbook deploy_mesos_slave.yml`. It return an error:

```
ERROR: expect is not a legal parameter in an Ansible task or handler
```

I search [ansible examples](https://github.com/ansible/ansible-examples) and [google](https://www.google.com.hk/#newwindow=1&safe=strict&q=ansible+expect) but can not find expect examples or detailed usage. 

So I want to know how to use expect correctly and resolve my problems.

Thanks.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by alwqx** [comment]
ok,Thanks very much.
