### ISSUE TITLE
Ansible 2.0 update succeeds but fails

### ISSUE THREAD

**Issue by slimandslam** [ansible/ansible#13820]
As mentioned here:  https://groups.google.com/forum/#!topic/ansible-project/PhxLaE3LHlE

I ran my usual Ansible upgrade for Ansible on my MacOSX (v10.11) laptop and it appeared to upgrade me:

$ sudo -H pip install --upgrade ansible --user python
Password:
Collecting ansible
  Downloading ansible-2.0.0.0.tar.gz (1.5MB)
    100% |################################| 1.5MB 172kB/s
Requirement already up-to-date: python in /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
Requirement already up-to-date: paramiko in /Library/Python/2.7/site-packages (from ansible)
Requirement already up-to-date: jinja2 in /Library/Python/2.7/site-packages (from ansible)
Requirement already up-to-date: PyYAML in /Library/Python/2.7/site-packages (from ansible)
Collecting setuptools (from ansible)
  Using cached setuptools-19.2-py2.py3-none-any.whl
Requirement already up-to-date: pycrypto>=2.6 in /Library/Python/2.7/site-packages (from ansible)
Requirement already up-to-date: ecdsa>=0.11 in /Library/Python/2.7/site-packages (from paramiko->ansible)
Requirement already up-to-date: MarkupSafe in /Library/Python/2.7/site-packages (from jinja2->ansible)
Installing collected packages: setuptools, ansible
  Running setup.py install for ansible
Successfully installed ansible-2.0.0.0 setuptools-1.1.6
$

However, when I type this at the command line, I'm still on v1.94:

$ ansible --version
ansible 1.9.4
  configured module search path = None
$

**Comment by abadger** [comment]
This isn't a problem with ansible but with how pip upgrade is working.  For some reason once pip --upgrade is done there's two versions of ansible on your system.  Some people have reported that explicitly telling pip to remove and then install ansible fixes the problem for them:

```
pip uninstall ansible
pip install ansible
```

I have been unable to reproduce the problem case to begin with so I'm not sure in what circumstances that would work and in which cases something else might be needed.

If it doesn't work for you, you'll need to look around your system for other places that an older version of ansible might be loaded from and remove those.

**Comment by bcoca** [comment]
you might be hitting the 'protected files' feature that OS X rolled out with 'el capitan' which prevents pip from updating the files (using sudo is a good sign of this).

**Comment by slimandslam** [comment]
Yes, I am running El Capitan (macosx 10.11.2)

**Comment by viper233** [comment]
It's possible to get around this issue by installing python via homebrew and then again, using pip to install Ansible.
http://apple.stackexchange.com/questions/209572/how-to-use-pip-after-the-el-capitan-max-os-x-upgrade

**Comment by franz-josef-kaiser** [comment]
Or just: Install *Ansible via Homebrew*, which will install/ pour the correct and needed Python version anyway.
