### ISSUE TITLE
Ansible 2.0 install from pip seems incomplete (missing 'extract' filter)

### ISSUE THREAD

**Issue by Woodham** [ansible/ansible#13821]
It seems like the release of Ansible 2.0 on pip is incomplete. After installing I am trying to use the 'extract' filter, but I'm getting the error message `no filter named 'extract'`.

After comparing the file `ansible/plugins/filter/core.py` at https://pypi.python.org/pypi/ansible/2.0.0.0 with the one in this repository, it seems like it's missing at least one line at the bottom:

```
# array and dict lookups
'extract': extract,
```

(This is in fact missing from rc4 as well - is it possible the version on pypi is actually rc4?)

**Comment by bcoca** [comment]
extract is scheduled for 2.1, i see that the docs say 2.0 but that is incorrect, fixed in 06b0161e6d215d316aa5cb93b5b09a766ef4463d

**Comment by YAmikep** [comment]
@bcoca 
Any advice on how to extract values from a dict in the meanwhile? 
I have a list of dicts and would like to combine a specific value of those dicts into a list.

Thanks

**Comment by YAmikep** [comment]
Nevermind, I just found a way using the Jinja2 [map](http://jinja.pocoo.org/docs/dev/templates/#map) filter and the `attribute` parameter:
`"{{ list_of_dict|map(attribute='attr_name')|list }}"`

**Comment by eduardohl** [comment]
Thanks, really useful, this should be added to doc
