### ISSUE TITLE
hostvars in template doesn't work as expected in v2.0.0.1

### ISSUE THREAD

**Issue by hyperized** [ansible/ansible#13838]
In 1.9 I could do the following in a template:

```
{{ hostvars | to_nice_json }} 
```

However in 2.0 it no longer works as expected, it generates the following error:

```
AnsibleError: ERROR! an unexpected type error occurred. Error was exceptions must be old-style classes or derived from BaseException, not type
```

When using the variable in a template (without jinja filter) I now get:

```
<ansible.vars.hostvars.HostVars object at 0x7faf24cae050>
```

This would explain the error. (Could you mention Error in there one more time ;)?)

I could be something wrong here, but I would expect this to still work as the following lines work like they do in 1.9:

```
{{ vars | to_nice_json }}
{{ environment | to_nice_json }}
{{ group_names | to_nice_json }}
{{ groups | to_nice_json }}
```

**Comment by bcoca** [comment]
this should work:
`{{ hostvars[inventory_hostname] | to_nice_json }}`

hostvars has always been 'special', in 2.0 we made it load lazily and currently cannot read through all the keys, but if you supply a hostname it should work.

if you really  need to dump all hosts:

```
{% for host in groups['all'] %}
{{ hostvars[host]|to_nice_json }}
{% endfor %}
```

**Comment by bcoca** [comment]
we seem to have a slew of errors here:
`fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! the field 'args' has an invalid value ([]), and could not be converted to an dict. Error was: exceptions must be old-style classes or derived from BaseException, not type\n\nThe error appears to have been in '/home/bcoca/work/ansible/play.yml': line 5, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: debug\n      ^ here\n"}`

Got this by raising the raw exception directly in https://github.com/ansible/ansible/blob/devel/lib/ansible/template/__init__.py#L482

**Comment by faascape** [comment]
Hello, i think i have something related to the current problem :
I want to add all ip of a group in /etc/host of current server.
I use 

```
- name: add ip address of all app hosts  in /etc/hosts
  lineinfile: dest=/etc/hosts line="{{ hostvars[item].internal_ip }} {{ hostvars[item].inventory_hostname }}"
  with_items:
    groups['app']
  sudo: yes
```

That was working fine in 1.9.x

but with V2, i got :

```
fatal: [build] FAILED! => {"failed": true, "msg": "ERROR! 'ansible.vars.hostvars.Hostvars object' has no attribute u\"groups['dvlp_gate']\""}
```

dvlp_gate is a name in my group 'app'.

**Comment by bcoca** [comment]
@faascape try with:
`  with_items:  "{{ groups['app'] }}"`

**Comment by faascape** [comment]
Thanks a lot for this fast answer !

I don't have the error anymore. Seems ok for me.

**Comment by basictheprogram** [comment]
I can add the exception is only thrown for the following:
{{ vars | to_nice_json }} 
{{ hostvars | to_nice_json }} 

These calls work as expected
{{ environment | to_nice_json }} 
{{ group_names | to_nice_json }}
{{ groups | to_nice_json }}

**Comment by andyl** [comment]
when is ansible going to stabilize and stop breaking my playbooks??
