### ISSUE TITLE
v2 doesn't allow variables in mysql_user module

### ISSUE THREAD

**Issue by p53** [ansible/ansible#13837]
Hi,

i have this code:

```
- name: Setup monitoring account
  mysql_user: login_user=root login_password="{{ mysql_root_passwd }}"
              user="{{ db_users['monitoring'] }}" password="{{ mysql_mon_passwd }}"
              priv=*.*:SELECT,REPLICATION\ CLIENT state=present
  when: port_count.stdout|int == 1
```

and i store passwords in ansible vault and users in separate group vars file

I am getting this error:

```
FAILED! => {"failed": true, "reason": "ERROR! this task 'mysql_user' has extra params, which is only allowed in the following modules: command, shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta\n\nThe error appears to have been in '/home/lumpy/pipeliner/roles/mariadb_base/tasks/configure.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Setup monitoring account\n  ^ here\n"}
```

**Comment by sivel** [comment]
I believe the reason is in the `priv` argument. I think you will need to quote its value such as:

```
priv="*.*:SELECT,REPLICATION\ CLIENT"
```

I do not believe this has anything to do with using variables. Perhaps due to the new parser being more strict.

**Comment by bcoca** [comment]
as stated above this is not a variable issue but a quoting one, the parser now recognizes problems that previously were ignored and might have been performing actions in an unintended way.

**Comment by alec9** [comment]
Same happens to me:

      - name: Create demo database user
        mysql_user:
          name=demo
          password=demo
          priv="demo.*ALL"
          host='%' state
          state=present

The error message is the same

> ERROR! this task 'mysql_user' has extra params, which is only allowed in the following modules: shell, win_shell, include_vars, add_host, raw, include_role, meta, set_fact, include, import_tasks, script, import_role, include_tasks, group_by, command, win_command
