### ISSUE TITLE
bare variables in with_* loops are not printing a deprecation warning

### ISSUE THREAD

**Issue by abadger** [ansible/ansible#13852]
In 2.0's changelog we specified that with_\* loops with bare variables are deprecated.  However, the code is not printing a deprecation warning. (Sample playbook:)

```

---
- hosts: localhost
  vars:
    looper:
      - 1
      - 2
  tasks:
  - debug: var=item
    with_items: looper
```

Problem code: https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/task_executor.py#L173

**Comment by bcoca** [comment]
fixed via dc15eb806e1b5c040aedb0565218d26c369eb453
