### ISSUE TITLE
Synchronize module ignores ansible_ssh_extra_args

### ISSUE THREAD

**Issue by gdw2** [ansible/ansible#13859]
Somwhat similar to #5109, the Synchronize module doesn't pickup the `ansible_ssh_extra_args`.  Is it supposed to?  If not, it would be a nice feature.

**Comment by gdw2** [comment]
Of course, adding the following config option to the synchronize task seems to be a decent workaround:

`rsync_opts: --rsh "ssh {{ansible_ssh_extra_args}}"`

**Comment by tima** [comment]
This should have been addressed in v2.0 with the introduction of `use_ssh_args` param in the synchronize action plugin here: https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/synchronize.py#L336
