### ISSUE TITLE
2.0 - fatal error on file task creating directory

### ISSUE THREAD

**Issue by tannerjfco** [ansible/ansible#13854]
I'm encountering this issue with Ansible 2.0 Stable running against Ubuntu 14.04 systems. This error occurs both in running `against a remote host, and running locally. The failing task is a simple file task creating a directory:

```
- name: create source directory
  file: path=/opt/source state=directory mode=0755
```

The resulting error:

```
 FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "There was an issue creating /opt/source as requested: set_fs_attributes_if_different() takes exactly 3 arguments (4 given)", "owner": "root", "path": "/opt/source", "size": 4096, "state": "directory", "uid": 0}
```

**Comment by jimi-c** [comment]
Hi @tannerjfco, did you upgrade Ansible when installing it? I'm wondering if this is picking up something from an old install, our integration tests use the code mentioned in the error quite a bit.

**Comment by jimi-c** [comment]
Alternatively, did you have a devel version of Ansible installed at some point?

**Comment by tannerjfco** [comment]
No, this is being run on a base Ubuntu 14.04 VM with no previous existing installation.

**Comment by bcoca** [comment]
can you run with -vvvv? and show us the output

**Comment by tannerjfco** [comment]
Here's the output with the added verbosity

```
TASK [ansible.nginx : create source directory] *********************************
task path: /tmp/packer-provisioner-ansible-local/roles/ansible.nginx/tasks/main.yml:23
task path: /tmp/packer-provisioner-ansible-local/roles/ansible.nginx/tasks/main.yml:23
ESTABLISH LOCAL CONNECTION FOR USER: vagrant
ESTABLISH LOCAL CONNECTION FOR USER: vagrant
127.0.0.1 EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1452720241.83-208555460263507 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1452720241.83-208555460263507 )" )
127.0.0.1 EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1452720241.83-208555460263507 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1452720241.83-208555460263507 )" )
127.0.0.1 PUT /tmp/tmpAMCrFr TO /home/vagrant/.ansible/tmp/ansible-tmp-1452720241.83-208555460263507/file
127.0.0.1 PUT /tmp/tmpAMCrFr TO /home/vagrant/.ansible/tmp/ansible-tmp-1452720241.83-208555460263507/file
127.0.0.1 EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-qucztjpyxxspqhaueptzwpzpwtcyvwfl; LANG=en_US.utf8 LC_ALL=en_US.utf8 LC_MESSAGES=en_US.utf8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1452720241.83-208555460263507/file; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1452720241.83-208555460263507/" > /dev/null 2>&1'"'"''
127.0.0.1 EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-qucztjpyxxspqhaueptzwpzpwtcyvwfl; LANG=en_US.utf8 LC_ALL=en_US.utf8 LC_MESSAGES=en_US.utf8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1452720241.83-208555460263507/file; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1452720241.83-208555460263507/" > /dev/null 2>&1'"'"''
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "invocation": {"module_args": {"backup": null, "content": null, "delimiter": null, "diff_peek": null, "directory_mode": null, "follow": false, "force": false, "group": null, "mode": "0755", "original_basename": null, "owner": null, "path": "/opt/source", "recurse": false, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": null, "state": "directory", "validate": null}, "module_name": "file"}, "mode": "0755", "msg": "There was an issue creating /opt/source as requested: set_fs_attributes_if_different() takes exactly 3 arguments (4 given)", "owner": "root", "path": "/opt/source", "size": 4096, "state": "directory", "uid": 0}
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "invocation": {"module_args": {"backup": null, "content": null, "delimiter": null, "diff_peek": null, "directory_mode": null, "follow": false, "force": false, "group": null, "mode": "0755", "original_basename": null, "owner": null, "path": "/opt/source", "recurse": false, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": null, "state": "directory", "validate": null}, "module_name": "file"}, "mode": "0755", "msg": "There was an issue creating /opt/source as requested: set_fs_attributes_if_different() takes exactly 3 arguments (4 given)", "owner": "root", "path": "/opt/source", "size": 4096, "state": "directory", "uid": 0}
```

**Comment by abadger** [comment]
@tannerjfco How are you installing ansible?  ansible-2.0.0.1-1ppa from the ansible ppa is working for me.  A look at the code shows that   /usr/share/pyshared/ansible/module_utils/basic.py has the three argument version of set_fs_attributes_if_different and so do the modules that call it (in particular /usr/share/pyshared/ansible/modules/core/files/file.py ).

If you are running from a git checkout, it could be a mismatch between the branch of ansible and the branch of the modules.  In the ansible devel branch we've changed the parameters of set_fs_attributes_if_different() to a 4 parameter version.  So if you checked out ansible, did a git submodule update --init to checkout the modules as submodules, and then switched the ansible branch to stable-2.0 but did not also change the submodules then the submodules will still be on the devel branch.

It should be as simple as running git submodule update --init again to make the module checkout correspond to the checkout of the ansible repo.

**Comment by tannerjfco** [comment]
Thanks,

I believe the issue was that I was using the git installation method for pip ( e.g. `pip install git+git://github.com/ansible/ansible.git@v2.0.0.0-1` ) while using dev/rc releases of ansible 2. Using the normal `pip install ansible` method resolved the issue.

**Comment by abadger** [comment]
Cool.  I'll go ahead and close this then.

**Comment by assarbad** [comment]
@abadger just to say thanks - Thanks! - and to let you know that your remark really helped. Just ran into the same issue and was about to open a ticket, but ran a search first and found this one.
