### ISSUE TITLE
Restore 1.9.4 to PyPi

### ISSUE THREAD

**Issue by foozmeat** [ansible/ansible#13863]
I'm sorry if this is the wrong place for this issue

After running into a bug in 2.0.0.1 today I decided to roll back to 1.9.4. Unfortunately it's been removed from PyPi. I think 1.9.4 should be restored so users can easily rollback without reverting to a pip install from the source.

Thanks for all of the hard work on 2.0!

**Comment by abadger** [comment]
I've unhidden the 1.9.4 release on pypi for now.  It looks like we have pypi set to autohide old releases and I didn't touch that for now.  We'll probably need to decide whether autohiding makes sense in this period while people want to get both 1.9.4 and 2.0.x

**Comment by foozmeat** [comment]
:clap:

**Comment by foozmeat** [comment]
```
$yolk -V ansible
ansible 2.0.0.1
ansible 1.9.4
```
