### ISSUE TITLE
Ansible is not using user PATH

### ISSUE THREAD

**Issue by cescoferraro** [ansible/ansible#13866]
Why does not ansible use my user path? 
It does not happen with regular ssh.
I could not find any workaround on the docs.

Regular ssh

```
$ssh cesco@localhost echo $PATH
/Users/cesco/.pyenv/shims:/Users/cesco/.local/bin:./bin:/usr/local/bin:/usr/local/sbin:/Users/cesco/.dotfiles/bin:/Users/cesco/.rbenv/shims:/Users/cesco/Code/Go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```

With ansible

```
- hosts: localhost
  tasks:
    - debug: msg={{ ansible_env.PATH }}
    - debug: msg={{ lookup('env','PATH') }}
```

```
TASK [debug] *******************************************************************
task path: /***
ok: [localhost] => {
    "msg": "/usr/bin:/bin:/usr/sbin:/sbin"
}

TASK [debug] *******************************************************************
task path: /****
ok: [localhost] => {
    "msg": "/Users/cesco/.pyenv/versions/2.7.11/bin:/usr/local/Cellar/pyenv/20151222/libexec:/Users/cesco/.pyenv/shims:/Users/cesco/.local/bin:./bin:/usr/local/bin:/usr/local/sbin:/Users/cesco/.dotfiles/bin:/Users/cesco/.rbenv/shims:/Users/cesco/Code/Go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
}
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
