### ISSUE TITLE
Ansible 2.0 hostgroup vars issues

### ISSUE THREAD

**Issue by retr0h** [ansible/ansible#13873]
I’m using a [custom vars plugin](https://github.com/blueboxgroup/ursula/blob/master/plugins/vars/default_vars.py) under ansible 1.9.  However, it looks as though the host object which [run](https://github.com/ansible/ansible/blob/4ba7158282f148c90c72f824d6ebcd1a9953b580/lib/ansible/inventory/vars_plugins/noop.py#L38) is passed is missing the group/host_vars from inventory.

I have tracked this down to what appears to be a bug with [_get_hostgroup_vars](https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/__init__.py#L702).

`basedirs = [_basedir, self._playbook_basedir]` is a list containing the path to my inventory as specified by `-i` and None (since playbook_basedir is False).  Since the loop is iterated before returning to the caller, the None directory fails to load inventory and returns an empty dict to the caller.

Ansible 1.9 was retaining the previous [result](https://github.com/ansible/ansible/blob/stable-1.9/lib/ansible/inventory/__init__.py#L651), each time through the loop.

When removing None items from the `basedirs` list, the plugin works as expected.

```
    def _get_hostgroup_vars(self, host=None, group=None, new_pb_basedir=False):
        """
        Loads variables from group_vars/<groupname> and host_vars/<hostname> in directories parallel
        to the inventory base directory or in the same directory as the playbook.  Variables in the playbook
        dir will win over the inventory dir if files are in both.
        """

        results = {}
        scan_pass = 0
        _basedir = self.basedir()

        # look in both the inventory base directory and the playbook base directory
        # unless we do an update for a new playbook base dir
        if not new_pb_basedir:
            basedirs = [_basedir, self._playbook_basedir] # <--- None at end of list here causes the problem.
        else:
            basedirs = [self._playbook_basedir]

        for basedir in basedirs:
            # this can happen from particular API usages, particularly if not run
            # from /usr/bin/ansible-playbook
            if basedir in ('', None):
                basedir = './'
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by retr0h** [comment]
@bcoca I've already done this, and nobody has responded.  This is a bug, I am willing to fix it :/

**Comment by bcoca** [comment]
not a bug, we changed the API in 2.0 and were aware many custom vars, connection, lookup and callback plugins would break. We intend to have migration guides for all but have not had time to write them yet.

**Comment by retr0h** [comment]
@bcoca could you explain how it isn't a bug?  The code returns an empty dict when  self._playbook_basedir isn't set.  Can you please describe how it isn't a bug, and the proper work-a-round?

**Comment by retr0h** [comment]
This issue was fixed at https://github.com/ansible/ansible/pull/13902

**Comment by retr0h** [comment]
@bcoca any chance we can get a new build released to pypi? :)

**Comment by bcoca** [comment]
retr0h 2.0.1 rc1 is coming soon
