### ISSUE TITLE
Can I use the docker module to push the image to my private registry?

### ISSUE THREAD

**Issue by 0xMadao** [ansible/ansible#13875]
I have check the `docker`、`docker_image` and the `docker_login` module , but I can't find the way to push(pull) the image to(from) my private registry. Can anybody tell me how to do that ?

**Comment by hloeffler** [comment]
please use the mailinglist for that kind of questions:
https://groups.google.com/forum/#!forum/ansible-project

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
