### ISSUE TITLE
Deprecated platform.dist

### ISSUE THREAD

**Issue by shaba** [ansible/ansible#13874]
Hello.
platform.dist() is deprecated since version 2.6 and recommended use platform.linux_distribution().
But platform.linux_distribution (and platform.dist too) is deprecated since version 3.5, will be removed in version 3.7.
May be use https://github.com/nir0s/ld for detect linux distributive?

**Comment by bcoca** [comment]
Since we don't support Python3 yet (much less 3.7?) and 2.4-2.7 do have it, we are going to keep that and not introduce another external dependency.
