### ISSUE TITLE
Ansible 2.0 failing when remote shell is fish

### ISSUE THREAD

**Issue by jurgenhaas** [ansible/ansible#13882]
This has been reported at https://groups.google.com/forum/#!topic/ansible-project/2JDkLFsvMcA and my example is this one:

```
ansible -i inventory crcweb -m ping -vvv
Using /home/jurgenhaas/.ansible.cfg as config file
<crcweb> ESTABLISH SSH CONNECTION FOR USER: jurgenhaas
<crcweb> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=jurgenhaas -o ConnectTimeout=10 -o ControlPath=/home/jurgenhaas/.ansible/cp/ansible-ssh-%h-%p-%r -tt crcweb '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1452763749.58-212919486518705 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1452763749.58-212919486518705 )" )'
<crcweb> PUT /tmp/tmpEhWM_e TO       ^/ping
<crcweb> SSH: EXEC scp -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=jurgenhaas -o ConnectTimeout=10 -o ControlPath=/home/jurgenhaas/.ansible/cp/ansible-ssh-%h-%p-%r /tmp/tmpEhWM_e '[crcweb]:'"'"'      ^/ping'"'"''
crcweb | FAILED! => {
    "failed": true, 
    "msg": "ERROR! failed to transfer file to       ^/ping:\n\nscp:       ^/ping: No such file or directory\n"
}
```

When changing the remote shell, it is working just fine.

**Comment by abadger** [comment]
Is the shell type set to fish for these hosts?

http://docs.ansible.com/ansible/intro_inventory.html#list-of-behavioral-inventory-parameters

**Comment by fspadini** [comment]
The local shell is zsh, the remote term is sh.

The issue is that my local TERM environment (xterm-256color) was getting used by paramiko and openssh and sent to the remote system.

Temporary workaround, "TERM=vt100 ansible -i ... -m ping" makes everything work peachy.

One interesting thing to note is that enabling pipelining makes the problem go away. I was able to track down the issue in the paramiko code,
paramiko_ssh.py:219:            chan.get_pty(term=os.getenv('TERM', 'vt100'),

The local environment is getting used for TERM instead of always forcing vt100, I couldn't find the corresponding openssh code.

Hope this helps.

**Comment by abadger** [comment]
@fspadini these two issues are probably separate.  So I opened a new issue for yours: https://github.com/ansible/ansible/issues/13895

**Comment by jurgenhaas** [comment]
@abadger thanks for picking this up. However, I'm not sure what you're asking with your link above. The ansible_connection is ssh but I can't define fish as the shell there, do I?

**Comment by jurgenhaas** [comment]
Interesting though, when trying the suggestion from @fspadini to enable pipelining, then I'm getting this error:

```
crcweb | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Unsupported use of '='. To run 'LC_ALL=de_DE.UTF-8' with a modified environment, please use 'env LANG=de_DE.UTF-8 LC_ALL=de_DE.UTF-8…'\nfish: LANG=de_DE.UTF-8 LC_ALL=de_DE.UTF-8 LC_MESSAGES=de_DE.UTF-8 /usr/bin/python\n      ^\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "parsed": false
}
```

**Comment by jurgenhaas** [comment]
Sorry @fspadini I wasn't fully reading the content at your above link. I now saw that there is a new inventory variable ansible_shell_type which I can set to fish and that is working fine.

I just wonder what would be the best practice about this. Right now I included that in my inventory for everything, so all users and all hosts are expected to be using fish. But what if that wasn't the case? In the past, Ansible did not require that setting, right?

**Comment by bcoca** [comment]
it did if you wanted to use the fish shell, but sometimes this 'worked' because /bin/sh was being forced, which also created some 'interesting' bugs.

you can set ansible_shell_type per host or group, so not all hosts need that.

**Comment by fspadini** [comment]
@abadger cheers - sorry for mixing up the issues!

**Comment by oppianmatt** [comment]
What do you do if different users have different shells? A group of admins who have their own accounts but have sudo access. Some have fish, some have bash. How do (if we can) we set ansible_shell_type  as an environment variable ?

**Comment by jurgenhaas** [comment]
That's a very good question and it could get even more complex. E.g. what if you're setting up a new host which originally doesn't have fish installed but as part of the playbook this will get installed. This will then probably fail half way through the play.

I still don't get it why this became a problem now and wasn't present before version 2.

**Comment by bcoca** [comment]
so this might be an issue with the removal of the hardcoded /bin/sh that used to precede commands, in the attempt to make it more flexible and comply closer to what shells people had configured.

**Comment by oppianmatt** [comment]
Is there way to force ansible to be consistent and use a particular shell for it's play (that is can we have it using /bin/sh)? Seems like this will produce different results based on what shell is configured for the current user. Consistency should be key.

Having the ability to specify a shell to use gives you other functionality like an audit. You could have a shell that logs everything and just wraps bash for example.

**Comment by bcoca** [comment]
^ please test above PR, It should 'fix' most of these issues

**Comment by jurgenhaas** [comment]
I've tested the PR and it is working fine, but only if the ansible_shell_type is _not_ set to fish. Which is fine, from my point of view.
