### ISSUE TITLE
Ansible 2.0 and ansible_ssh_user

### ISSUE THREAD

**Issue by nocive** [ansible/ansible#13888]
Hi guys,

Since I upgraded to ansible 2, I'm facing issues with some tasks I have that depend on `ansible_ssh_user` value, which now is always `null` in my setup.

Found this bit in the changelog which I suppose explains my problem:

> We do not ignore the explicitly set login user for ssh when it matches the 'current user' anymore, this allows overriding .ssh/config when it is set explicitly. Leaving it unset will still use the same user and respect .ssh/config. This also means ansible_ssh_user can now return a None value.

How is one supposed to read/know the user being used by ansible on the remote hosts with ansible 2 without having to look at `ansible_env.SUDO_USER` or `ansible_user_id` depending on `become` being `false` or `true`?

With sudo

```
$ ansible all -i localhost, --sudo -m debug -a 'var=ansible_ssh_user'
localhost | SUCCESS => {
    "ansible_ssh_user": null
}
```

Without sudo

```
$ ansible all -i localhost, -m debug -a 'var=ansible_ssh_user'
localhost | SUCCESS => {
    "ansible_ssh_user": null
}
```

**Comment by bcoca** [comment]
No need to rely on facts, if ansible_ssh_user is null the user used is in the master's $USER environment variable:
lookup('env','USER')

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by nocive** [comment]
Thanks for the quick reply @bcoca, makes sense.
