### ISSUE TITLE
Bug Report: ansible fact pkg_mgr wron on Solaris 11: pkg instead of pkg5

### ISSUE THREAD

**Issue by liquidat** [ansible/ansible#13885]
Issue Type:
    Bug Report

Ansible Version:
    $ ansible --version                                           1 
    ansible 1.9.4
      configured module search path = None

Ansible Configuration:
Using the Fedora shipped ansible.cfg. Compared to the Github version most of the variables are commented out and thus defaults are used almost everywhere.

Environment:
- Client: Fedora 23
- Server: Solaris 11

Summary:
On Solaris 11 the variable ansible_pkg_mgr is determined wrong:

```
$ ansible krypton -m setup -a "filter=*pkg*"
krypton | success >> {
    "ansible_facts": {
        "ansible_pkg_mgr": "pkg"
    }, 
    "changed": false
}
```

"pkg" is not the proper package manager on Solaris, it needs to be "pkg5":

```
$ ansible krypton -m pkg -a "name=web/server/apache-24 state=absent"
krypton | FAILED => module pkg not found in configured module paths
$ ansible krypton -m pkg5 -a "name=web/server/apache-24 state=absent"
krypton | success >> {
    "changed": false, 
    "msg": "", 
    "results": []
}
```

Steps To Reproduce:
- query the variable ansible_pkg_mgr
- try to use the resulting value as a module
- see that there is no corresponding module

Expected Results:
- the value for ansible_pkg_mgr should be pkg5, which is the software packaging module actually used on Solaris 11

Actual Results:
- the variable was set to pkg which is not the actual packaging module for Solaris 11

**Comment by bcoca** [comment]
we do not set it by version but by detecting the binary, can you detail how we would detect pkg5 vs pkg? currently we look for /usr/bin/pkg and if found we set it to 'pkg' or '/usr/sbin/pkgadd'  and set it to 'svr4pkg'

**Comment by liquidat** [comment]
But there is no module 'pkg' at all, given http://docs.ansible.com/ansible/list_of_packaging_modules.html .

So I do not understand why to set it to that value anyway. I would follow your above described routine, but when it finds '/usr/bin/pkg' the value of the variable should be set to 'pkg5', not to 'pkg'.

**Comment by pfuetz** [comment]
Did you check:

http://docs.oracle.com/cd/E23824_01/html/E24456/index.html
and specifically:
http://docs.oracle.com/cd/E23824_01/html/E24456/package-1.html#scrolltoc

I would not test for availability of "pkg", I would use

"uname -r" or "uname -v",

because the packaging changes did occur with the introduction of Solaris 11.

HTH,

Matthias

**Comment by bcoca** [comment]
No, i just looked at the existing code, it is not something I wrote.

The thing about Solaris (less common in other OSs) is that in many cases people use alternate package managers to what is supplied by Sun/Oracle. I'm remiss about changing detection to be OS version specific vs tool binary detection.

**Comment by liquidat** [comment]
Right now there is no solution to this situation thus I close this bug right now.
