### ISSUE TITLE
task to run external playbook

### ISSUE THREAD

**Issue by akostadinov** [ansible/ansible#13890]
In some occasions you can be provided by an ansible playbook for some setup. To adapt to specific needs one may need to add tasks before and/or after that playbook.

So imagine I'm provided with a playbook by another dept so I can't really control the playbook. To avoid complicated processing I want to write a new playbook that just includes the third party playbook somewhere. Please provide a way to do so. `roles` and `inlcudes` are not a good workaround as I don't have control over the base playbook as well I don't want to constantly monitor changes in the base playbook to keep necessary roles/includes same as the base playbook. My only option now is to reconstruct the playbook but this is not so nice.

**Comment by bcoca** [comment]
it seems you are asking to be able to execute your playbook first, which you can already do by just ordering them in the command line:
`ansible-playbook mybook.yml providedbook.yml`

**Comment by akostadinov** [comment]
hmm, I think that would do, thank you!
