### ISSUE TITLE
password_hash('md5') fails

### ISSUE THREAD

**Issue by TimJones** [ansible/ansible#13891]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.0.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

The password_hash('md5') Jinja filter fails when a fixed salt is not supplied.
##### Steps To Reproduce:

```
$ ansible -m debug -a msg="{{ 'whatever'|password_hash('md5') }}" localhost
```
##### Expected Results:

```
localhost | SUCCESS => {
    "msg": "$1$y03Fxmbn$YENXo38/pZ8NszrW/DQ6D1"
}
```
##### Actual Results:

```
localhost | FAILED! => {
    "failed": true, 
    "msg": "ERROR! the field 'args' has an invalid value ([]), and could not be converted to an dict. Error was: salt too large (md5_crypt requires <= 8 chars)"
}
```

**Comment by TimJones** [comment]
Problem is on this line https://github.com/ansible/ansible/blob/v2.0.0.0-1/lib/ansible/plugins/filter/core.py#L228 , range(16) should only be range(8) for MD5. Salt size probably should be selected alongside `hashtype`.

**Comment by TimJones** [comment]
I was just preparing a PR for this :) One thing to one though, blowfish has, I think, a 22 character hash. Not sure how it behaves with a smaller hash...

**Comment by bcoca** [comment]
if you have better solution, please create the PR, this was a quick hack
