### ISSUE TITLE
Ansible 1.9.4 missing from PPA

### ISSUE THREAD

**Issue by gwagner** [ansible/ansible#13898]
I am unable to install 1.9.4 from https://launchpad.net/~ansible/+archive/ubuntu/ansible

I would like a working version of ansible, since 2.0.0.1 == broken

**Comment by bcoca** [comment]
The Ubuntu PPA only lets us have a single version up, we are looking at ways to work around this, till then https://launchpad.net/~ansible/+archive/ubuntu/ansible/+builds?build_text=&build_state=built has all the previous versions (sadly not usable by apt).

**Comment by gwagner** [comment]
For anyone who finds this and wants to run a version of ansible that is not full of bugs (which are not edge case bugs i might add) here are the steps you should use on ubuntu.  This is specific to trusty, but should be usable with other ubuntu versions by replacing the download URL:

```
# Make sure we are up to date
/usr/bin/apt-get update

# Download working ansible deb package
wget https://launchpad.net/~ansible/+archive/ubuntu/ansible/+build/8129693/+files/ansible_1.9.4-1ppa~trusty_all.deb -O /tmp/ansible.deb

# Manually install deps
apt-get install -y python-support \
  python-jinja2 \
  python-yaml \
  python-paramiko \
  python-httplib2 \
  python-crypto sshpass

# Install Package
dpkg -i /tmp/ansible.deb

# Remove downloaded package
rm -f /tmp/ansible.deb
```

**Comment by vitz3** [comment]
@bcoca @gwagner Thank you very much! I'll be sure to lock this version! 2.0.0.2 broke all my playbooks with:

`ERROR! Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\`

**Comment by jpalomaki** [comment]
FYI: There appears to be a new 1.9.x Ansible PPA now: https://launchpad.net/~ansible/+archive/ubuntu/ansible-1.9

**Comment by siathalysedI** [comment]
I think it is resolved here https://github.com/ansible/ansible/issues/5725#issuecomment-118381617

**Comment by bcoca** [comment]
closing as per per above (new ppa for 1.9)

**Comment by gwagner** [comment]
New script to use the new PPA

```
# Make sure we are up to date
/usr/bin/apt-get update

# Download working ansible deb package
wget https://launchpad.net/~ansible/+archive/ubuntu/ansible-1.9/+files/ansible_1.9.4-1ppa~trusty_all.deb -O /tmp/ansible.deb

# Manually install deps
apt-get install -y python-support \
  python-jinja2 \
  python-yaml \
  python-paramiko \
  python-httplib2 \
  python-crypto sshpass

# Install Package
dpkg -i /tmp/ansible.deb

# Remove downloaded package
rm -f /tmp/ansible.deb
```

**Comment by jogaco** [comment]
@gwagner thanks for the tip!

**Comment by drzraf** [comment]
This ubuntu package makes my day. 

I just confirm that since Debian testing dropped 1.9 in favour of 2.0 all is broken 
(and Debian Stable is < 1.8 which misses a lot of useful stuff)

(2.0.x is so far so broken that new "features" are not even worth it. I can't even find a simple CHANGE.txt stating explicitly how modules would have to be rewritten to the new API)

**Comment by pprados** [comment]
Where we can find a version for Ubuntu Xenia ?

Thanks

**Comment by FlorinAndrei** [comment]
There's no ansible-1.9 packaged for Xenial apparently. Could someone add it to the repo? Thanks!

**Comment by CarlosCuevas** [comment]
also need 1.9 for xenial

**Comment by richard-gtv** [comment]
+1 for a xenial package.

**Comment by abarnas** [comment]
Try this: https://launchpad.net/ubuntu/xenial/amd64/ansible/1.9.4-1
