### ISSUE TITLE
ansible failing with terminal control codes in the output

### ISSUE THREAD

**Issue by abadger** [ansible/ansible#13895]
From https://groups.google.com/forum/#!topic/ansible-project/2JDkLFsvMcA

I'm having some trouble with the new Ansible 2 when trying to run ping on a host that works with 1.9.4.

I'm getting the following:

```
$ ansible -i test all -m ping -u root -vvvvv -c paramiko

Loaded callback minimal of type stdout, v2.0
<10.10.0.242> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO 10.10.0.242
<10.10.0.242> EXEC mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1452643119.18-173252181839542 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1452643119.18-173252181839542 )"
<10.10.0.242> PUT /var/folders/1d/nqrbvtz120nb7r2rjqzpvs7m0000gn/T/tmpjR2gSS TO /home/root/.ansible/tmp/ansible-tmp-1452643119.18-173252181839542/ping
<10.10.0.242> EXEC LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/root/.ansible/tmp/ansible-tmp-1452643119.18-173252181839542/ping; rm -rf "/home/root/.ansible/tmp/ansible-tmp-1452643119.18-173252181839542/" > /dev/null 2>&1
10.10.0.242 | FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "ping"
    },
    "module_stderr": "",
    "module_stdout": "\u001b[?1034h{\"invocation\": {\"module_args\": {\"data\": null}}, \"changed\": false, \"ping\": \"pong\"}\r\n",
    "msg": "MODULE FAILURE",
    "parsed": false
}
```

Previously on 1.9.4 I would get:

```
$ ansible -i test all -m ping -u root -vvvvv -c paramiko
<10.10.0.242> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO 10.10.0.242
<10.10.0.242> REMOTE_MODULE ping
<10.10.0.242> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1452643204.88-178243528154466 && echo $HOME/.ansible/tmp/ansible-tmp-1452643204.88-178243528154466'
<10.10.0.242> PUT /var/folders/1d/nqrbvtz120nb7r2rjqzpvs7m0000gn/T/tmpqHPWsg TO /home/root/.ansible/tmp/ansible-tmp-1452643204.88-178243528154466/ping
<10.10.0.242> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/root/.ansible/tmp/ansible-tmp-1452643204.88-178243528154466/ping; rm -rf /home/root/.ansible/tmp/ansible-tmp-1452643204.88-178243528154466/ >/dev/null 2>&1'
10.10.0.242 | success >> {
    "changed": false,
    "ping": "pong"
}
```

Any idea what the culprit might be?  At first glance the only real difference I can see is that the older version had /bin/sh -c in front, but that could just be a change in logging.

Update from: https://github.com/ansible/ansible/issues/13882#issuecomment-171723283

The local shell is zsh, the remote term is sh.

The issue is that my local TERM environment (xterm-256color) was getting used by paramiko and openssh and sent to the remote system.

Temporary workaround, "TERM=vt100 ansible -i ... -m ping" makes everything work peachy.

One interesting thing to note is that enabling pipelining makes the problem go away. I was able to track down the issue in the paramiko code,
paramiko_ssh.py:219: chan.get_pty(term=os.getenv('TERM', 'vt100'),

The local environment is getting used for TERM instead of always forcing vt100, I couldn't find the corresponding openssh code.

/cc @fspadini

**Comment by fspadini** [comment]
I couldn't find any way to override the detected term being passed on besides overriding it temporarily for the ansible command - is there a config option I didn't catch in the docs?

**Comment by abadger** [comment]
No but I haven't replicated it yet.  I wonder if there's an ssh server side config that, in my test environment is keeping TERM from being set on the remote side.  (when I do an `ssh HOSTNAME export| grep TERM`  I see that TERM is not set.)

**Comment by abadger** [comment]
So for my testing I found a few things.  Firstly, allocation of the pseudo-tty on the remote machine is important for this.  `ssh -tt HOSTNAME export|grep TERM` does show the TERM being propogated to the remote machine.

Setting AcceptEnv in the remote machine's sshd_config also allows the TERM variable to be sent.  I haven't found a way to turn this off clientside or for pseudo-ttys though.

Finally, I still can't replicate the error.  Running from fedora 21 to rhel6 with /bin/zsh on the ansible controller and /bin/sh on the rhel6 box, I do see that the TERM variable is set to xterm-256color on the remote machine but I don't see any escape codes in the returned output:

```
$ ansible -i 'rhel6-test,' '*' -m shell  -a 'export'|grep TERM                              (16:20:19)
export TERM="xterm-256color"
$ ansible -i 'rhel6-test,' '*' -m ping  -vvvvv -c paramiko                                  (16:22:11)
Using /etc/ansible/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<rhel6-test> ESTABLISH CONNECTION FOR USER: None on PORT 22 TO rhel6-test
<rhel6-test> EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1452817353.6-172146100132012 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1452817353.6-172146100132012 )" )
<rhel6-test> PUT /var/tmp/tmpDlNYUP TO /home/badger/.ansible/tmp/ansible-tmp-1452817353.6-172146100132012/ping
<rhel6-test> EXEC LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/badger/.ansible/tmp/ansible-tmp-1452817353.6-172146100132012/ping; rm -rf "/home/badger/.ansible/tmp/ansible-tmp-1452817353.6-172146100132012/" > /dev/null 2>&1
rhel6-test | SUCCESS => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "data": null
        }, 
        "module_name": "ping"
    }, 
    "ping": "pong"
}
```

Is there any other information you can give us?  Which operating systems the two hosts are running?

**Comment by zeuben** [comment]
Seems that i am having a similar issue going from OSX to Centos 7.
It works on another machine that is also Centos7 (prod) and another machine that is Centos 6.5 (dev)
Here is debug output

`ansible staging -m ping -u zeuben -vvvv
Loaded callback minimal of type stdout, v2.0
<750staging.com> ESTABLISH SSH CONNECTION FOR USER: zeuben
<750staging.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=zeuben -o ConnectTimeout=10 -o ControlPath=/Users/zeuben/.ansible/cp/ansible-ssh-%h-%p-%r -tt 750staging.com '/bin/sh -c '"'"'( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1457576242.2-34034941543318 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1457576242.2-34034941543318 `" )'"'"''
/home/zeuben/.ansible/tmp/ansible-tmp-1457576242.2-34034941543318/ping
<750staging.com> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=zeuben -o ConnectTimeout=10 -o ControlPath=/Users/zeuben/.ansible/cp/ansible-ssh-%h-%p-%r '[750staging.com]'
750staging.com | FAILED! => {
    "failed": true,
    "msg": "failed to transfer file to \u001b[?25h\u001b[0G\u001b[K\u001b[?25h\u001b[0G\u001b[K/home/zeuben/.ansible/tmp/ansible-tmp-1457576242.2-34034941543318/ping:\nsftp> put /var/folders/_l/6gnz4_255k90h3f2kqtrn3cm0000gn/T/tmpRsXCvu '\u001b[?25h\u001b[0G\u001b[K\u001b[?25h\u001b[0G\u001b[K/home/zeuben/.ansible/tmp/ansible-tmp-1457576242.2-34034941543318/ping'\n\nOpenSSH_7.1p2, OpenSSL 1.0.2e 3 Dec 2015\r\ndebug1: Reading configuration data /opt/local/etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 89371\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension \"posix-rename@openssh.com\" revision 1\r\ndebug2: Server supports extension \"statvfs@openssh.com\" revision 2\r\ndebug2: Server supports extension \"fstatvfs@openssh.com\" revision 2\r\ndebug2: Server supports extension \"hardlink@openssh.com\" revision 1\r\ndebug2: Server supports extension \"fsync@openssh.com\" revision 1\r\ndebug3: Sent message fd 9 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /home/zeuben size 0\r\ndebug3: Looking up /var/folders/_l/6gnz4_255k90h3f2kqtrn3cm0000gn/T/tmpRsXCvu\r\ndebug3: Sent message fd 9 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn't stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/home/zeuben/\\033[?25h\\033[0G\\033[K\\033[?25h\\033[0G\\033[K/home/zeuben/.ansible/tmp/ansible-tmp-1457576242.2-34034941543318/ping\r\nremote open(\"/home/zeuben/\\033[?25h\\033[0G\\033[K\\033[?25h\\033[0G\\033[K/home/zeuben/.ansible/tmp/ansible-tmp-1457576242.2-34034941543318/ping\"): No such file or directory\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n"
}`

**Comment by zozo6015** [comment]
I was having the same issues and it got fixed when I installed python on the remote machines.

**Comment by drewdavies** [comment]
I experienced the same issue, had me pulling my hair out for the last few hours. All came down to my TERM being set as xterm-256color.

<img width="812" alt="screen shot 2016-04-12 at 2 19 37 pm" src="https://cloud.githubusercontent.com/assets/2984277/14475962/d81c2bc0-00b9-11e6-9cf8-674b8cff0e37.png">

**Comment by cknave** [comment]
Another way this presented: `stat` commands only worked with `become: yes`.  I suspect `become` clears the TERM environment.

`TERM=vt100 ansible-playbook ...` fixed this for me as well.

**Comment by bcoca** [comment]
@cknave not become, most privilege escalation 'sanitize' the environment (sudo does by default).

**Comment by sivel** [comment]
I have a PR open that may resolve this as well, although it stills needs to be discussed: https://github.com/ansible/ansible/pull/15337

**Comment by sivel** [comment]
This has been resolved in https://github.com/ansible/ansible/pull/15337
