### ISSUE TITLE
getting started documentation error

### ISSUE THREAD

**Issue by makuk66** [ansible/ansible#139]
http://ansible.github.com/gettingstarted.html#running-from-checkout says:

```
cat "127.0.0.1" > ~/ansible_hosts
```

which should be:

```
echo "127.0.0.1" > ~/ansible_hosts
```

**Comment by mpdehaan** [comment]
thanks for the heads up and good catch.

for future reference, docs project -- https://github.com/ansible/ansible.github.com

**Comment by mpdehaan** [comment]
fixed, thanks!
