### ISSUE TITLE
Ansible 2.0 programmatically

### ISSUE THREAD

**Issue by asg1612** [ansible/ansible#13906]
Hi, 

I use Ansible 1.9 programmatically and works fine!. Now with the version 2.0 it is break down...

I followed this example: 
https://serversforhackers.com/running-ansible-programmatically

The main problem is modules like PlayBook doesn't exist
Are there any possibility of doing it with ansible 2.0?

**Comment by sivel** [comment]
Please see the following docs page for information on the new Python API in v2:

http://docs.ansible.com/ansible/developing_api.html
