### ISSUE TITLE
Ansible Tower: stdout capture is missing error

### ISSUE THREAD

**Issue by wintechdevops** [ansible/ansible#13904]
I have upgraded Ansible to 2.0.0.1 and running Ansible Tower 2.4.3.

After I upgraded to Ansible 2.0 I started getting the following error every time I try and run a job in Tower:  stdout capture is missing

Any suggestions what could be causing this?

**Comment by sangrealest** [comment]
tower 3.0.1 also has this problem, the same jobs could run perfectly before I did a backup and restore ansible tower

**Comment by andelf** [comment]
Solved by change celery's run user to root.
ugly but works.

UPDATE: 
change supervisor/conf.d/tower.conf

ADD:
```ini
[program:awx-celeryd]
......
environment=HOME="/var/lib/awx",USER="awx"
......
```

**Comment by smcracraft** [comment]
Did you mean environment=HOME="/var/lib/awx",USER="root" ?

**Comment by andelf** [comment]
@smcracraft 
no, run celeryd as root solves, but it's better to add missing environment variables for running under normal user(awx)。
