### ISSUE TITLE
Variable in dependency name is undefined when passing via group_vars

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#13915]
**Issue Type:**
     Bug Report

**Ansible Version:**
     ansible 2.1.0 (devel 1b82de2354) last updated 2016/01/15 11:34:19 (GMT -400)

**Ansible Configuration:**
ansible.cfg

[defaults]
roles_path = ../common/roles
inventory = ./hosts
remote_user = root
ask_pass = true
transport = paramiko
record_host_keys = false
host_key_checking = false
deprecation_warnings=False

**Environment:**
Centos 7

**Summary:**
When using a group var to pass a variable used in a dependency name the execution errors with variable is undefined.  This behavior works if you define the variable in a vars file included in the playbook or if you directly define the variable in the playbook.

**Steps To Reproduce:**

```
/playbook.yml

---
- hosts: all
  roles:
  - { role: test }

/hosts
[dev]
targetvm

/group_vars/dev/main.yml
somevar: test2

../common/roles/test/tasks/main.yml
- debug: msg="somevar is {{somevar}}"

../common/roles/test/meta/main.yml
dependencies:
 - "{{somevar}}"

../common/roles/test2/tasks/main.yml
- debug: msg="somevar is {{somevar}}"
```

**Expected Results:**
The variable in the group_vars should be used in the interpretation of the role dependency

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [targetvm]

TASK [test2 : debug] ************************************************************
ok: [targetvm] => {
    "msg": "somevar is test2"
}

TASK [test : debug] *************************************************************
ok: [targetvm] => {
    "msg": "somevar is test2"
}
```

**Actual Results:**
`ERROR! 'somevar' is undefined`

**Comment by bcoca** [comment]
i'm not sure this should work as roles get imported and processed BEFORE host vars are available.

**Comment by ghost** [comment]
Ah, that makes sense. That very well could be the way it needs to run.  I just found it odd that I could use variables declared in other locations in the dependency name and that variables declared using a group_var worked anywhere else.  In my example above, if you hard code the dependency everything works fine.  I was just hoping to use a more dynamic implementation.

**Comment by OAuthBringer** [comment]
I've encountered a similar issue.  We've got multiple roles that are dependent on the same version of the JDK and we want to centralize those variables in `group_vars/all` and keep jdk updates as consistent as possible.


group_vars/all/jdk.yaml:
```
  jdk_version: <version>
  jdk_url: <url>
```

roles/elasticsearch/test/unit.yaml:
```
hosts: all
vars:
  elasticsearch_jdk_url: "{{ jdk_url }}"
  elasticsearch_udk_version: "{{ jdk_url }}"
```

If I execute the unit test (using vagrant) in `2.1.0.0` or `2.0.x` the global group_var propgates to the unit test and things execute fine.  In `2.2.0.0` however I get the jdk variables undefined error reported above.

I'm not sure if the behavior in `2.2.0.0` is a fix and the other versions are a bug, but based on my understanding of group_var precedence it should be available.  Feedback on this would be helpful so we can figure out how to best evaluate our tests.


# UPDATE

I went back and incremented through the different ansible versions.  The failure begins at `2.1.1.0` (pypi) and persists through `2.2.0.0`

**Comment by bcoca** [comment]
I'm going to close this ticket as the vars used are not available to be used in this fashion.

@neolytics, im not sure i understand your issue, but it seems unrelated to scope, if you can open a ticket witha  simple reproducer we can take a look at it.
