### ISSUE TITLE
wrong version of file core module in Debian package

### ISSUE THREAD

**Issue by netsandbox** [ansible/ansible#13912]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.0.0.2
  config file = /home/cloos/.ansible.cfg
  configured module search path = Default w/o overrides
##### Environment:

Ubuntu 15.10
##### Summary:

Running a task with the file modules gives me the error described in https://github.com/ansible/ansible-modules-core/issues/2585, which was fixes with c6fdd38 in November.

Comparing `/usr/share/pyshared/ansible/modules/core/files/file.py` with https://github.com/ansible/ansible-modules-core/blob/devel/files/file.py shows that the Debian (Ubuntu) package installs not the latest version of the module.
Maybe other modules are also affected (doesn't checked this).

**Comment by bcoca** [comment]
devel is not a good comparison as it has changes not present in 2.0.0.2
https://github.com/ansible/ansible-modules-core/blob/stable-2.0.0.1/files/file.py should be the file to compare to (there were no module changes between 2.0.0.0, 2.0.0.1 and 2.0.0.2

**Comment by bcoca** [comment]
that said, the bug you mention IS present in the release, i'll backport the fix to stable-2.0 and the next release of the 2.0.x tree will have it. (now fixed)

**Comment by netsandbox** [comment]
@bcoca Thanks for the quick reply and the fix.

From other projects here I'm used to land in the stable branch if I browse to the repository.
But here I land in the devel branch. Is this intentional?

**Comment by bcoca** [comment]
devel is for 'next stable release', for current stable releases we have stable-2.0 and stable-1.9 branches
