### ISSUE TITLE
Feature Idea: get SSH key from credstash/other lookups

### ISSUE THREAD

**Issue by jagibson** [ansible/ansible#13927]
Issue Type:
Feature Idea

Summary:
It would be very handy to be able to pull SSH private keys from credstash or other lookup providers.

Some benefits (credstash):
- Keys would no longer have to be permanently stored on the same host that Ansible is run from.
- Don't have to worry about weak vault passwords.
- Versionable
- No need to store keys in source control (via vault)

Caveats:
OpenSSH requires that a key be loaded from a file whether you are using straight-up ssh or the ssh-agent.  As such, the key should be downloaded to the Ansible temp directory and deleted at the end of the play.  Ideally if the run is cancelled with Ctrl-C there should still be an escape sequence to remove the key file.

Possible implementation:
Probably the easiest way to do this would be to add a 'ansible_ssh_private_key' host parameter that would take input and write it to a temporary key file for use.  This would also allow flexibility for loading keys from other non-file methods.  The downside is that someone could do something dumb like put their private key directly into a play- but that's not really much different from using ansible_ssh_pass.

Example play:

```
- hosts:
  vars:
    - ansible_ssh_private_key: {{ lookup('credstash', 'my-other-password', region='us-west-1') }}
```

**Comment by bcoca** [comment]
you can already do this, not only with credstash, but with vault and other lookups for secure data.

**Comment by jagibson** [comment]
@bcoca You can?  The only way I can figure out how to do is to set up a task to write the key to a file and then load it with ansible_ssh_private_key_file in a separate play.  This is less then ideal because, 1. It requires extras tasks in your play and 2. you have to remember to delete the key file when done.

Or is ansible_ssh_private_key (note no 'file') an undocumented feature?

**Comment by sivel** [comment]
`ansible_ssh_private_key_file` must be the path to a file.  I have solved this in the past by having a role or included playbook that fetches the keys, adds them to an ssh-agent with a timeout, and deletes the file and setting `ansible_ssh_private_key_file` for the host to the location where it lived when adding to the agent.

The file need not actually be present for ssh-agent to still work.
