### ISSUE TITLE
Symbol '$' inside variables fails with different errors

### ISSUE THREAD

**Issue by j9** [ansible/ansible#1392]
When using '$' symbol inside variables, ansble fails with various errors.

For instance, having variable defined like this:
    - error_var_01: "^[[:blank:]]+address ${valid_var}$"

Error output: https://gist.github.com/3923302

If variable is defined with '$' escaped with backslash:
    - error_var_01: "^[[:blank:]]+address ${valid_var}\$"

Error output: https://gist.github.com/3923309

Sample playbook, that reproduce the errors can be found here: https://gist.github.com/3923311

**Comment by mpdehaan** [comment]
working on this now.

**Comment by mpdehaan** [comment]
fix pushed for 0.9, we can consider backporting this to 0.8 if we decide to do a dot release.

Thanks!

**Comment by j9** [comment]
Thanks!
