### ISSUE TITLE
Faster ansible via safe concurrent task execution

### ISSUE THREAD

**Issue by bhouston** [ansible/ansible#13935]
We are using ansible for our https://clara.io service.  Our ansible scripts are pretty intense.

I notice that they are slow, slower than they need to be.

The main thing is that there are a number of operations that are blocking, but that do not necessarily have to be.
- Installing a package.  It blocks all other tasks and it can take a while.
- Downloading a zip.
- Unzipping a package.
- Pulling the latest source from github.com
- Checking the status of the system.
- Running npm install.
- Compiling source.

Basically during a 10 minute ansible session to upgrade our production machines, the machines are basically not doing anything for most of the time, they are waiting on some blocking operation in ansible.

I wonder if there was a way to specify that some operations are async and atomic.  Downloading files or checking the current status of the system to determine if one needs to update do not change the system state and thus can be run asynchronously.

The other thing one could do is to have tasks declare what they modify and one serializes the tasks based on what they modify (these can be arbitrary names, just assigned to tasks even, basically lock names), thus ensuring correct results, while achieving parallelism of tasks that do not modify the same things.

I guess the downside is this would add some complexity to ansible, but I think it could be something that people do not need to use, it is just an added layer that enables much more optimized deploys.

I am not attempting to design the full system that needs to be implemented (I didn't think this through fully) rather just trying to suggest a way forward that will have tremendous benefits for those like use that run ansible many times a day on many machines.

**Comment by bhouston** [comment]
BTW I wrote while waiting for an ansible deploy.

**Comment by aabdnn** [comment]
Ansible can run tasks asynchronously in the background, and poll for their status later. Does this help you?

http://docs.ansible.com/ansible/playbooks_async.html

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
