### ISSUE TITLE
all the playbooks examples in docs are missing colons

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1394]
Things like 

"fetch src="

are everywhere.

Acceptable would be "action: fetch"

or "fetch:"

but leaving off the colon just makes it confusing.

I think we lost this in the course of converting the module docs over and need to fix all of the examples so they have colons.

**Comment by mpdehaan** [comment]
@jpmens want to help with this?

**Comment by jpmens** [comment]
Certainly.
Will submit super-duper-jumbo-colon-doc-patch this evening or early tomorrow morning (CET)

BTW: I don't think colons were lost, but rather that we all documented /usr/bin/ansible - like instead of playbook-syntax :)

**Comment by jpmens** [comment]
Do you want old-style `action: fetch` or new-style `fetch:` @mpdehaan ?
(New probably better)

**Comment by mpdehaan** [comment]
Seeing 0.8 is released and we want folks to upgrade, I think I'm okay with
new style.

We'll probably go back and make all the docs everywhere new style after one
more release and everyone has already upgraded.
