### ISSUE TITLE
etcd API verssion V1 and not current V2

### ISSUE THREAD

**Issue by moshe0076** [ansible/ansible#13946]
Hi,

I cant get values from etcd using lookup.
It looks like the API version is hardcoded in etcd.py (self.baseurl = '%s/v1/keys'). 

Thanks,

Moshe

**Comment by bcoca** [comment]
it should be able to support both, this should be configurable

**Comment by moshe0076** [comment]
Hi,

Any news?

Thanks,

Moshe.

**Comment by scheetz** [comment]
+1

**Comment by berlic** [comment]
Dirty fix to support v2 call and response: https://gist.github.com/berlic/98fcd4d80c6db78e946e9f9f31d65510
Place `etcd2.py` into `lookup_plugins` and call `lookup` with `etcd2` parameter.

**Comment by sssahas** [comment]
+1

**Comment by bcoca** [comment]
This is already supported, you just need to set an env variable to change the default 'v1'

`ANSIBLE_ETCD_VERSION="v2" ansible-playbook ....`
