### ISSUE TITLE
local_action ignored when setting ansible_connection on Ansible 2.0.0.2

### ISSUE THREAD

**Issue by tetherit** [ansible/ansible#13955]
I have this task:

```
- name: Check current path
  become: false
  local_action: shell pwd
```

I am running it through a playbook:

```
 roles:
    - { role: common, ansible_connection: chroot }
```

When this tasks runs, instead of delegating to local_action, it still runs in the chroot :(

```
TASK [common : Check current path] ********************************************
task path: /data/deployer/xanview-ansible/roles/common/tasks/main.yml:7
</data/timebox-bootstrap> THIS IS A LOCAL CHROOT DIR
</data/timebox-bootstrap> EXEC ['/usr/sbin/chroot', u'/data/timebox-bootstrap', '/bin/sh', '-c', u'LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /usr/bin/python']
changed: [icomply-tsi0001 -> None] => {"changed": true, "cmd": "pwd", "delta": "0:00:00.033407", "end": "2016-01-18 14:30:07.967476", "invocation": {"module_args": {"_raw_params": "pwd", "_uses_shell": true, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 0, "start": "2016-01-18 14:30:07.934069", "stderr": "", "stdout": "/", "stdout_lines": ["/"], "warnings": []}
```

Any ideas?

**Comment by henninge** [comment]
I have a similar problem, I think. This was with the command module and stopped working with 2.0.0.x. This is now faling with "file or directory not found":

```
local_action: command relative/to/playbook.sh
```

I worked around it by using an absolute path:

```
local_action: command /my/playbooks/relative/to/playbook.sh
```

I think these may be related.

**Comment by tetherit** [comment]
This does not seem to be related and setting an absolute path does not help. The problem is the absolute path is looked for in the chroot, rather than as a local action.

The "local_action" bit is effectively ignored :(

**Comment by bcoca** [comment]
local_action will not override ansible_connection, `set connection: chroot` at the play level

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by tetherit** [comment]
The solution is not to set "ansible_connection", but rather to just set "connection", thank you bcoca for your help!

**Comment by tetherit** [comment]
Seems this solution no longer works with ansible 2.1.1.0 -- connection: local is just ignored :(

This is in my playbook, it worked in 2.0.0.2 but is ignored in 2.1.1.0:

```
  roles:
    - { role: common, connection: 'chroot', tags: [ 'minimal' ] }
```

When I set ansible_connection: 'chroot' instead it works, but then this local_action uses chroot instead of connection: local:

```
- name: Check if we have a crt/key for the serial
  local_action:
    module: stat
    path: 'host_files/{{ vpn_domain }}/hosts/{{ serial }}/openvpn-certs/{{ serial }}.key'
  connection: local
  register: timebox_key
```
