### ISSUE TITLE
Performance issues with over 9000 groups

### ISSUE THREAD

**Issue by towolf** [ansible/ansible#13956]
We have ~~over 9000~~ 8500 groups coming out of a dynamic inventory script and formatted as JSON. Assigned to those groups are about half that number of unique hosts. This means hosts are member of several groups at once. The inventory data coming from an internal database is basically key-value property pairs made into group identifiers:

``` json
   "host.os=Debian_6.0" : {
      "hosts" : [
         "127.0.xxx.xxx",
         "127.0.xxx.xxx"
      ]
   },
   "host.os=FreeBSD" : {
      "hosts" : [
         "127.0.xxx.xxx",
         "127.0.xxx.xxx",
       [ ... lots more ...]
         "127.0.xxx.xxx",
         "127.0.xxx.xxx"
      ]
   },
   "host.os=FreeBSD_10.1" : {
      "hosts" : [
         "127.0.xxx.xxx",
         "127.0.xxx.xxx"
      ]
   },
   "host.os=FreeBSD_7.3" : {
      "hosts" : [
         "127.0.xxx.xxx"
      ]
   },

[... and so on ...]
```

This scheme facilitates playbook host patterns like:

``` yaml
    hosts: host.os=Debian_6.0:!host.os=FreeBSD:&status=productive
```

So we have a lot of these kind of groups. 7500 groups contain only one host and
a few groups contain thousands. We also include a `_meta` object in the JSON
which supplies `hostvars` for each host with up to 30 host specific variables.

**The problem is that parsing and sorting through our inventory takes over 20 seconds.**

I have tried to work out the hot spots during parsing this large inventory and
identified a few locations.
- Looking at the file system and checking for  `group_vars/*` files for several
  relative paths and for every group and in multiple passes is very expensive.
  
  Even an `os.path.realpath` (which serves as a fancy string concatenation) has
  to stat 35000 times and takes more than 5 seconds. Not to mention what
  happens inside the `add_group_vars_file()` function.
  
  ```
  Total time: 27.3202 s
  File: /home/towolf/src/local/ansible.upstream/lib/ansible/inventory/__init__.py
  Function: _get_hostgroup_vars at line 702
  
  Line #      Hits         Time  Per Hit   % Time  Line Contents
  ==============================================================
     702                                               @profile
     703                                               def _get_hostgroup_vars(self, host=None, group=None, new_pb_basedir=False):
     704                                                   """
     705                                                   Loads variables from group_vars/<groupname> and host_vars/<hostname> in directories parallel
     706                                                   to the inventory base directory or in the same directory as the playbook.  Variables in the playbook
     707                                                   dir will win over the inventory dir if files are in both.
     708                                                   """
     709
     710     24877        35363      1.4      0.1          results = {}
     711     24877        31044      1.2      0.1          scan_pass = 0
     712     24877      1719067     69.1      6.3          _basedir = self.basedir()
     713
     714                                                   # look in both the inventory base directory and the playbook base directory
     715                                                   # unless we do an update for a new playbook base dir
     716     24877        38816      1.6      0.1          if not new_pb_basedir:
     717     24877        41675      1.7      0.2              basedirs = [_basedir, self._playbook_basedir]
     718                                                   else:
     719                                                       basedirs = [self._playbook_basedir]
     720C                                           
     721     74631       121290      1.6      0.4          for basedir in basedirs:
     722                                                       # this can happen from particular API usages, particularly if not run
     723                                                       # from /usr/bin/ansible-playbook
     724     49754        82384      1.7      0.3              if basedir in ('', None):
     725     12438        15767      1.3      0.1                  basedir = './'
     726                                           
     727     49754        63313      1.3      0.2              scan_pass = scan_pass + 1
     728                                           
     729                                                       # it's not an eror if the directory does not exist, keep moving
     730     49754       410588      8.3      1.5              if not os.path.exists(basedir):
     731                                                           continue
     732                                           
     733                                                       # save work of second scan if the directories are the same
     734     49754        89221      1.8      0.3              if _basedir == self._playbook_basedir and scan_pass != 1:
     735                                                           continue
     736                                           
     737     49754        67523      1.4      0.2              if group and host is None:
     738                                                           # load vars in dir/group_vars/name_of_group
     739     34212      5457260    159.5     20.0                  base_path = os.path.realpath(os.path.join(basedir, "group_vars/%s" % group.name))
     740     34212     11411194    333.5     41.8                  results = self._variable_manager.add_group_vars_file(base_path, self._loader)
     741     15542        22108      1.4      0.1              elif host and group is None:
     742                                                           # same for hostvars in dir/host_vars/name_of_host
     743     15542      2483568    159.8      9.1                  base_path = os.path.realpath(os.path.join(basedir, "host_vars/%s" % host.name))
     744     15542      5201313    334.7     19.0                  results = self._variable_manager.add_host_vars_file(base_path, self._loader)
     745                                           
     746                                                   # all done, results is a dictionary of variables for this particular host.
     747     24877        28735      1.2      0.1          return results
  ```
  
     It would be better to  turn this around and make a file listing **once**
     of every possible `group_vars` directory relative to the inventory and the
     playbook, and then checking against the filenames in that set instead of
     the file system directly.
  
     I implemented this in a branch in my repo and this saves 12 seconds.
- In the same method the basename relative to the inventory is evaluated every
  time a group is checked even though it is constant. I suggest caching
  this in a private property.
- The parser from `json.loads()` in `python-json` and `simplejson` seems to
  always return Unicode strings. Ansible however recursively checks every
  string in the input in `json_dict_bytes_to_unicode()` to see if it needs to
  be converted from byte string. This calls `isinstance` about 3 million times
  for no good reason:
  
  ```
  Total time: 3.25549 s
  File: /home/towolf/src/local/ansible.upstream/lib/ansible/module_utils/basic.py
  Function: json_dict_bytes_to_unicode at line 349
  
  Line #      Hits         Time  Per Hit   % Time  Line Contents
  ==============================================================
     349                                           @profile
     350                                           def json_dict_bytes_to_unicode(d, encoding='utf-8'):
     351                                               ''' Recursively convert dict keys and values to byte str
     352                                           
     353                                                   Specialized for json return because this only handles, lists, tuples,
     354                                                   and dict container types (the containers that the json module returns)
     355                                               '''
     356                                           
     357    510291       635723      1.2     19.5      if isinstance(d, bytes):
     358                                                   return unicode(d, encoding)
     359    510291       535639      1.0     16.5      elif isinstance(d, dict):
     360     24179       146484      6.1      4.5          return dict(imap(json_dict_bytes_to_unicode, iteritems(d), repeat(encoding)))
     361    486112       492564      1.0     15.1      elif isinstance(d, list):
     362     15183       118530      7.8      3.6          return list(imap(json_dict_bytes_to_unicode, d, repeat(encoding)))
     363    470929       472485      1.0     14.5      elif isinstance(d, tuple):
     364    150689       664279      4.4     20.4          return tuple(imap(json_dict_bytes_to_unicode, d, repeat(encoding)))
     365                                               else:
     366    320240       189790      0.6      5.8          return d
  ```
  
     Commenting out the line that does 
  
  ```
     self.raw  = json_dict_bytes_to_unicode(self.raw)
  ```
  
     saves about 2-3 seconds.
- Checking for membership in a python `set()`  is much faster than lookup in
  lists. I saved an addition 2 seconds by changing data structures like
  `group.child_groups()` from lists to sets.

**Comment by towolf** [comment]
I have prepared a test case for this issue at: https://github.com/towolf/ansible-large-inventory-testcase

The inventory is structurally identical to our production version, with anonymized strings.

**Comment by towolf** [comment]
I have also prepared a pull request with a suggested fix for the storm of lstats when looking for group_var files.

**Comment by hloeffler** [comment]
@bcoca @jimi-c please look, we need this kind of speed too :)

**Comment by jimi-c** [comment]
I'm not sure we can remove the `self.raw  = json_dict_bytes_to_unicode(self.raw)` bit, as it's critical to ensuring we're dealing with unicode only. The other change we can consider, though we're still working on resolving some of the higher criticality issues from the 2.0 release, so we'll try and get to this as soon as possible.

**Comment by towolf** [comment]
Agreed about the priority, seeing the current rate of new issues.

About the recursive `to_unicode`, can I supply a pull request that first checks a short JSON string to see if unicode strings are always returned? This could avoid having to check the big JSON recursively.

**Comment by towolf** [comment]
Solved this slightly differently in the PR above.

**Comment by towolf** [comment]
Updated the to_unicode PR after input from @abadger.

**Comment by towolf** [comment]
@jimi-c, is it a good time to revisit this issue? We have a PR prepared that largely ameliorates this issue.

PR #13957 reverses the group_vars file lookup by making a directory listing first and checking against that instead of hitting the file system for thousands of file stats.

This shortens the parsing of our group-heavy inventory from over 20 seconds to 8 seconds.

**Comment by Yannig** [comment]
Hi,

I have an old PR of mine that could help you. You can check it out here: https://github.com/ansible/ansible/pull/13168

I have updated it to run with last version of Ansible. Using your inventory, I was able do gain about 50% in time completion. Here's some result on my machine with and without the patch:
- without patch:

```
time ansible-playbook -i inventory.sh playbook.yml
[...]
real    0m10.216s
user    0m9.471s
sys     0m0.902s
```
- with my PR:

```
time ansible-playbook -i inventory.sh playbook.yml
[...]
real    0m4.753s
user    0m4.330s
sys     0m0.596s
```

Hope it helps

**Comment by towolf** [comment]
Thanks for the suggestion, but AFAICT, your PR is more-or-less subsumed by mine, i.e., `basedir` doesn't even need to get checked anymore. But the two PRs pursue the same goal.

**Comment by jimi-c** [comment]
@towolf since your PR above was merged, I believe this is ok to close?

**Comment by towolf** [comment]
@jimi-c, yes inventory parsing is much improved after the recent changes that went in. For the record, the current `devel` with my towolf/ansible-large-inventory-testcase repository completes in 3.7 second, not over 20. I still want to submit a PR for refactoring some of the inventory data structures from `list` to `set`, i.e., the last item in my issue above.

There are now other places during playbook execution where performance is terrible though.

**Comment by jimi-c** [comment]
Great, thanks! And we're working on the other places... devel/stable-2.1 includes a fix for bad host/group var loading which cut cpu/memory usage in half in my testing, though it is still slower and more memory-hungry than 1.9.x.

**Comment by towolf** [comment]
@jimi-c as promised I submitted another PR https://github.com/ansible/ansible/pull/16413 to shave off a further 25% of inventory parsing time inside `Group.add_child_group()`. Please check it out.
