### ISSUE TITLE
setup module fails on OpenVZ container with Ansible 2.0.0.1

### ISSUE THREAD

**Issue by aibor** [ansible/ansible#13951]
**Issue Type:**
Bug Report

**Ansible Version:**
2.0.0.1
This issue is not present in ansible 1.9.

**Ansible Configuration:**
N/A

**Environment:**
Ansible host: Debian Jessie
Target host: CentOS6 OpenVZ container: `2.6.32-5-openvz-amd64`

**Summary:**
When running `ansible -m setup` for the container, the module fails with `MODULE FAILURE` and a python exception stack trace.

**Expected Results:**
JSON Output of facts of the target host.

**Actual Results:**

```
Traceback (most recent call last):
File "<stdin>", line 5142, in <module>
File "<stdin>", line 140, in main
File "<stdin>", line 84, in run_setup
File "<stdin>", line 5080, in ansible_facts
File "<stdin>", line 4740, in populate
File "<stdin>", line 4746, in get_virtual_facts
File "<stdin>", line 5068, in get_file_lines
File "<stdin>", line 5063, in get_file_content
UnboundLocalError: local variable 'datafile' referenced before assignment
```

**Steps To Reproduce:**
Looking at the code, it seems to result from [facts.py line 2667](https://github.com/ansible/ansible/blob/7de237c5a1742660bc240c15e97a1f5b0d1611a8/lib/ansible/module_utils/facts.py#L2667) as `/proc/1/cgroup`is available, but not readable from within the container, which results in the exception in [line 2984](https://github.com/ansible/ansible/blob/7de237c5a1742660bc240c15e97a1f5b0d1611a8/lib/ansible/module_utils/facts.py#L2984), which I can reproduce in the container with the following snippet:

```
>>> def read_cgroup():
...   try:
...     f = open('/proc/1/cgroup')
...   finally:
...     f.close()
...
>>> read_cgroup()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in read_cgroup
UnboundLocalError: local variable 'f' referenced before assignment
```

Comparing the virtualization environment detection of ansible 1.9 with 2.0, it appears that in the former version the function returned before opening that file when in OpenVZ environment.

If you need any further information regarding the OpenVZ environment, please let me know.

**Comment by bcoca** [comment]
```

**Comment by bcoca** [comment]
can you try running with the following patch?

```
diff --git a/lib/ansible/module_utils/facts.py b/lib/ansible/module_utils/facts.py
index a214b6b..c5dc1f9 100644
--- a/lib/ansible/module_utils/facts.py
+++ b/lib/ansible/module_utils/facts.py
@@ -2987,6 +2987,9 @@ def get_file_content(path, default=None, strip=True):
                 data = data.strip()
             if len(data) == 0:
                 data = default
+        except:
+            # todo: issue warning about unreadable file?
+            pass
         finally:
             datafile.close()
     return data
```

**Comment by aibor** [comment]
Thank you for the quick reply.

Unfortunately, your patch doesn't change anything. The same exception is thrown, as the `finally` block is still processed and datafile is still undefined, as the exception is thrown in the call of `open()`. An additional check in the `finally` block helps to produce the expected result:

```
diff --git a/lib/ansible/module_utils/facts.py b/lib/ansible/module_utils/facts.py
index 796ebc9..5fa2b40 100644
--- a/lib/ansible/module_utils/facts.py
+++ b/lib/ansible/module_utils/facts.py
@@ -2974,14 +2974,19 @@ def get_file_content(path, default=None, strip=True):
     data = default
     if os.path.exists(path) and os.access(path, os.R_OK):
         try:
+            datafile = None
             datafile = open(path)
             data = datafile.read()
             if strip:
                 data = data.strip()
             if len(data) == 0:
                 data = default
+        except:
+            # todo: issue warning about unreadable file?
+            pass
         finally:
-            datafile.close()
+            if datafile is not None:
+                datafile.close()
     return data

def get_file_lines(path):
```

**Comment by bcoca** [comment]
it also broke 2.4 compatibility, pushed in patch that should fix it correctly

closing via a773486432ae03fac53a5e176ba46d0d187762b8
