### ISSUE TITLE
simple ssh can send this comand, but raw or script module does not

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#13963]
Hi,

I can do:
`ssh root@172.30.22.1 "((exec sleep 21)&) && exit"`

But this command is not working
`ansible all -i "172.30.22.1," -u root -c ssh -m raw -a "((exec sleep 21)&) && exit" -k`

If I put in a script, is not working too.
Tried with a playbook, nothing.

Circumstances:
- I cannot put python (embedded devices).
- I cannot use nohup, disown. I found this way works in busybox.
- What I'm trying to do is to flash OpenWRT routers as background, now is working with simple ssh, but the same command with ansible is not working.

How I check if is working? With:
`ps | grep sleep`

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by ghost** [comment]
Thanks for pointing me to the discussion places,

For me this thing is a bug, perhaps not exactly related to ansible, because ansible uses [paramiko](http://www.paramiko.org/) for ssh connections. I will show here the solution to make it easy for people that arrive here. How I solve it? Preventing this modules to do the task of putting a process in background, for example in the playbook use:

`local_action: script myscript.sh {{ ansible_host }}`
or
`local_action: script myscript.sh {{ inventory_hostname }}`

and in the script:
`ssh root@$1 "( sleep 21 ) & exit"`

note: I did not tested with nohup or disown.
