### ISSUE TITLE
included tasks do not execute when running playbook with ansible api

### ISSUE THREAD

**Issue by jiangshengwu** [ansible/ansible#13962]
I have a simple test role located in `/etc/ansible/roles/test/tasks/main.yml` like this:

```

---
- roles/common/tasks/facts.yml
- include: test.yml
```

And I use the example code of **Python API 2.0** found in [Documentation](http://docs.ansible.com/ansible/developing_api.html). Then I've encountered a strange problem.

On my develop machine which is a Mac, everything works fine, but when I run it on the production machine whose operating system is CentOS 7, the two included tasks can't be executed. Here is the output:

```
PLAY [Test Play] **************************************************************

TASK [setup] *******************************************************************
ok: [10.85.0.20]

TASK [test : include] **********************************************************
included: /etc/ansible/roles/common/tasks/facts.yml for 10.85.0.20

TASK [test : include] **********************************************************
included: /etc/ansible/roles/test/tasks/test.yml for 10.85.0.20
```

You see, it did including operation, but nothing actually executed.

And the correct output would be: 

```
PLAY [Test Play] **************************************************************

TASK [setup] *******************************************************************
ok: [10.85.0.20]

TASK [test : include] **********************************************************
included: /Users/Jiang/projects/ecs-ansible/roles/common/tasks/facts.yml for 10.85.0.20

TASK [test : facts.d dir] ******************************************************
ok: [10.85.0.20]

TASK [test : facts file] *******************************************************
changed: [10.85.0.20]

TASK [test : get facts from pluto] *********************************************
changed: [10.85.0.20]

TASK [test : setup] ************************************************************
ok: [10.85.0.20]

TASK [test : include] **********************************************************
included: /Users/Jiang/projects/ecs-ansible/roles/test/tasks/test.yml for 10.85.0.20

TASK [test : debug] ************************************************************
ok: [10.85.0.20] => {
    "msg": "15.0"
}
```

Version:
- OSX 10.11.4 beta & ansible 2.1.0 (devel 36aa89ac7e) last updated 2016/01/18 14:48:31 (GMT +800)
- CentOS 7.1.1503 & ansible 2.1.0 (devel 36aa89ac7e) last updated 2016/01/18 23:05:26 (GMT +800)

Could someone help me to solve this? Thanks.

---

Update:

I just rollbacked to ansible 2.0, it worked. Maybe it's a bug in 2.1.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- IRC: #ansible-devel on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by senreese** [comment]
I have the exact same issue on CentOS Linux release 7.2.1511 (Core). It happened right after I updated Ansible to the latest version today.

A playbook named book.yml includes a role named chud.

In roles/chud/tasks/main.yml is just one include statement, to a file named testing.yml.

In the file testing.yml is a single task to touch a file, or debug message a variable, doesn't matter.

All you will see when you run the playbook is the light blue line saying

 Included: /junk/roles/chud/tasks/testing.yml

Nothing is actually executed.

This appears to be a bug, not a user question. Rolling back to the old version of Ansible solved the issue for me too.

**Comment by nathanielks** [comment]
+1, same thing is happening to me.

**Comment by rjnienaber** [comment]
For anyone else hitting this link, the reason why I was getting this problem is that I was specifying tags that caused included modules to be skipped over. So even though it shows as being 'included', it's actually being skipped over. Once I picked the right tag, the included tasks started working as expected.

**Comment by slapula** [comment]
I don't know if this is tag related since I seem to be running into this issue with a pretty simple playbook that doesn't utilize tags.  I am also running CentOS 7.1 & Ansible 2.1.0.  When I go back to Ansible 2.0, the playbook executes my roles without issue.

**Comment by robbiedyer** [comment]
Was any reason for the seemingly unexplained silent skipping of included plays found? My example:

```
- name: Create VM
  hosts: stage.host
  user: root
  gather_facts: no

  tasks:

    - add_host:
        name: "{{ hostname }}"
        groups: stage
        ip: "{{ ip }}"

    - name: Print variables
      debug:
        msg: "{{ hostvars[hostname] }}  {{ ip }}"

- include: config/git.yml

- include: config/oh-my-zsh.yml

- include: config/templates.yml
```
All the includes at the end of the snippet are completely ignored.

**Comment by robbiedyer** [comment]
I've found my issue was apparently incorrect indentation. The include playbook line was indented too far and therefore wasn't inline with the other tasks. I believe it was due to not including it before the tasks in the root playbook and also not including it inline with the other tasks that caused it to be ignored. Correct me if this shouldn't be the case however.

**Comment by subsy** [comment]
I think Im seeing something similar/related as referenced above in #28438
