### ISSUE TITLE
GCE documentation too vague

### ISSUE THREAD

**Issue by atrauzzi** [ansible/ansible#13989]
Looking at this page: https://github.com/ansible/ansible/blob/devel/docsite/rst/guide_gce.rst

Unfortunately, I'm not able to get a working setup based on the instructions.  There seems to be a lot of ambiguity, specifically when talking about a `gce.py` file.  I'm also unsure really what I'm required to install and how.

Perhaps someone who knows this module and inventory driver better can clarify things or simplify the instructions for someone starting from scratch.

**Comment by bcoca** [comment]
cc @erjohnso

**Comment by erjohnso** [comment]
Ack @atrauzzi, thanks for flagging it. I do believe these docs are in need of a review and refresh!

Have you managed to get things working or are you still stuck?  If you have some time and patience, I'd love to walk through it with you and get these docs cleaned up.  It would really help to have a fresh pair of eyes like yours on it to ensure they doc is solid for new users.

Thanks for the /cc Brian!

**Comment by atrauzzi** [comment]
No, I wasn't able to get much of anything working.  Email me (my git username at gmail) if you'd like and we can collaborate however works best for you.
