### ISSUE TITLE
ansible_user variable undefined in Ansible 2.1 (devel) when --user is not supplied

### ISSUE THREAD

**Issue by NielsH** [ansible/ansible#13982]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.1.0 (devel 1f7492171e) last updated 2016/01/19 11:51:05 (GMT +200)
  lib/ansible/modules/core: (detached HEAD ffea58ee86) last updated 2016/01/19 11:55:13 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD e9450df878) last updated 2016/01/19 11:55:15 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

No special changes
##### Environment:

NA
##### Summary:

In Ansible 2, `ansible_ssh_user` was replaced with `ansible_user`.  
When ansible connects without the `--user` flag it'll attempt to connect with the current username on the local system. In ansible version <2 I could still get `ansible_ssh_user` this way. However, with ansible 2, I can only get the `ansible_user` variable when `--user` is supplied. Otherwise, `ansible_user` is a null value.
##### Steps To Reproduce:

```
Not working:
ansible -i hosts dev -m debug -a msg="{{ ansible_user }}" --ask-pass
IP1 | SUCCESS => {
    "msg": null
}
IP2 | SUCCESS => {
    "msg": null
}

Working:
ansible -i hosts dev -m debug -a msg="{{ ansible_user }}" --user nielsh --ask-pass
IP1 | SUCCESS => {
    "msg": "nielsh"
}
IP2 | SUCCESS => {
    "msg": "nielsh"
}

```
##### Expected Results:

I expect `ansible_user` to work even if `--user` is not supplied, by falling back to the default user, which is the current local user, the same that is used to login via SSH.
##### Actual Results:

Without `--user`, `ansible_user` is not defined.

**Comment by bcoca** [comment]
its not undefined, its null, that is how it is supposed to be. The connection itself will NOT pass a user to ssh, which then uses the current user, this is done to allow the use of .ssh/config when not specifying a user.

**Comment by NielsH** [comment]
In ansible 1.9, using `ansible_ssh_user` did work even without supplying `--user`. Since the docs mention `ansible_user` replacing `ansible_ssh_user` in v2, should the docs not also mention how the two differ from each other? I assumed the functionality would be the same since this is all the documentation says about it:

```
Note
Ansible 2.0 has deprecated the “ssh” from ansible_ssh_user, ansible_ssh_host, and ansible_ssh_port to become ansible_user, ansible_host, and ansible_port. If you are using a version of Ansible prior to 2.0, you should continue using the older style variables (ansible_ssh_*). These shorter variables are ignored, without warning, in older versions of Ansible.
```

**Comment by bcoca** [comment]
And in https://github.com/ansible/ansible/blob/devel/CHANGELOG.md you also see that ansible_ssh_user now returns NULL when the user is not specified.

**Comment by jmehnle** [comment]
If the variable is not undefined, how come I'm getting this error then?

```
fatal: [<host redacted>]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ansible_user' is undefined\n\nThe error appears to have been in 'roles/base/tasks/main.yml': line 224, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Send notification message via Slack\n  ^ here\n"}
```

The relevant task being:

```
- name: Send notification message via Slack
  slack:
    domain=<domain redacted>
    token="{{ vault_slack_token }}"
    msg="{{ inventory_hostname }} ansible run completed by {{ ansible_user }}"
```

**Comment by tkurki** [comment]
Bumped against this is as well, found this, possibly related: https://github.com/ansible/ansible/issues/14519

**Comment by dkasak** [comment]
I just encountered this, in the same scenario as mentioned in #14519 (setting the shell of the remote account with the same username as my local account). As mentioned there, this seems like quite a useful piece of information to have from a playbook. Can we get some more attention on this one, please?

**Comment by joelnb** [comment]
@dkasak not sure if it's the official way but I found I could replace `{{ ansible_ssh_user }}` with `{{ ansible_user_id }}` and the playbooks picked up the correct user even when running without any user explicitly set.

EDIT: Looks like this gist will show you exactly what the differences are because that is not exactly the same: https://gist.github.com/ramondelafuente/9819526
