### ISSUE TITLE
atomic_move inside docker fails for /etc/hosts

### ISSUE THREAD

**Issue by pgrange** [ansible/ansible#13981]
When running ansible inside a docker container, ansible will fail if we try to change some systems file, such as /etc/hosts.

This issue is related to this docker issue : https://github.com/docker/docker/issues/9295

You can reproduce with the following code : https://github.com/pgrange/ansible_docker_resource_busy

I wrote an uggly, untested, patch just to validate an alternative that would consist of overwriting the content of the target file instead of renaming or copying. This patch is available here : https://github.com/pgrange/ansible/commit/844eb0bfea04473719e195fcad73a515516f1df6

**Comment by bcoca** [comment]
Basically docker says to not do this, to use their command line options.

**Comment by bcoca** [comment]
@pgrange I'm not liking the solution ... but it has nothing to do with your code, its the artificial limitation added at the source ...

I would consider the patch, but if we add an update_atomically=yes|no option to trigger it.

**Comment by pgrange** [comment]
@bcoca sorry for the delay and thank you for your answer.

I forgot to explain my use case. First of all, I do not use ansible to configure a docker container. But I use a docker container to validate an ansible role before applying it on actual servers.

The idea here is to write ansible roles in a kind of TDD way. Running the role on the container, then asserting some states on this container to ensure role behaves as expected.

Is docker appropriate to do that is an open question but the fact is, exept for this issue, it is working quite well.

I make this precision so that you can understand that I do not want to tweak my ansible role so that it can run inside a docker container. Since the container is just a mean to test the role that will be executed on actual production servers.

I need some clarification on your suggestion. Do you suggest to introduce a global configuration option "update_atomically=yes|no" that one can set in a ansible.cfg file for instance and that will apply to every module that relies on update_atomically ? Or do your suggest to add such an option directly to the lineinfile module for instance ?

The first option could solve my issue. The second, not so much. Let me know which option you suggest.

Just so you know, I took inspiration in the patch that has been added to handle errno 26 (text file busy) which happens on vagrant synced folders:

https://github.com/ansible/ansible/commit/013c4631e3a65035471d85aabd9227c0fa701e10

And I think both issues compare quite well. Here, we introduce a patch to deal with errno.EBUSY for docker instead of errno 26 for vagrant. OK, the way we work around the issue is different (and the patch is crap ;)).

Thanks,
Pascal.

**Comment by bcoca** [comment]
so did this 70ac47ae61eb3c0cb2e33a342128ef1a7653b17b based on @pgrange's code (py2.4/py3 compatibility sucks)

i'm thinking of adding a 'unsafe_writes=no|yes' with a very strongly worded description to the modules that operate on files to enable this .... still, this feels like working around with a bad hack across a purposefully broken implementation.

**Comment by bcoca** [comment]
closing this as `unsafe_writes` was added as an option to most 'file modules' for 2.2. We are still working out some kinks, but that is tracked in another ticket.
