### ISSUE TITLE
Regression: Errors out when user can't write to /var/log even if they can to /var/log/ansible.log #4852

### ISSUE THREAD

**Issue by gsker** [ansible/ansible#13990]
BUG REPORT
**Version:** ansible 2.0.0.2 Installed from the ubuntu PPA
**Configuration:**  I took the original cfg file and only changed log_path to /var/log/ansible.log
**Environment:** Ubuntu 14.04 on both sides.
**Steps to reproduce:**
    As root:
    make /var/log/ansible.log writeable  (chgrp admin /var/log/ansible.log ;chmod 775 /var/log/ansible.log)
    make /var/log not writeable (chgrp syslog /var/log; chmod 775 /var/log)
   (my user is in the admin group but not in the syslog group)
   As me:
    ansible --list-hosts all

**Expected Results**
    An error saying that there are no hosts configured in the inventory
**Actual Results**
    [WARNING]: log file at /var/log/ansible.log is not writeable, aborting
And then the inventory error
**History and Fix**
Original report: https://github.com/ansible/ansible/issues/4852
This popped up in 2.0. The location for the code in my install is display.py.  The fix is the same as the one
in this commit:  https://github.com/jinnko/ansible/commit/d4ec7b2e96bb8cf86a6118e6303e1edafda687af 
except applied to /usr/share/pyshared/ansible/utils/display.py
( https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/display.py )
**Change Line 54:**
if (os.path.exists(path) and not os.access(path, os.W_OK)) **_or_** not os.access(os.path.dirname(path), os.W_OK):
**To**
if (os.path.exists(path) and not os.access(path, os.W_OK)) **_and_** not  os.access(os.path.dirname(path), os.W_OK):

**Comment by r1k0** [comment]
I confirm the same issue here:

```
rik@gentoo ~/git/ansible $ cat ansible.cfg | grep log_path
log_path              = /var/log/ansible.log
rik@gentoo ~/git/ansible $ ll /var/log/ansible.log 
-rw-r--r-- 1 rik rik 158592271 Jan 21 14:26 /var/log/ansible.log
rik@gentoo ~/git/ansible $ ansible-playbook --version
[WARNING]: log file at /var/log/ansible.log is not writeable, aborting

ansible-playbook 2.0.0.2
  config file = /home/rik/git/ansible/ansible.cfg
  configured module search path = /usr/share/ansible:/home/kbruneel/git/ansible/library
rik@gentoo ~/git/ansible $ ansible-playbook datacenter_gitlab.yml -D -C 
[WARNING]: log file at /var/log/ansible.log is not writeable, aborting

^C [ERROR]: User interrupted execution

rik@gentoo ~/git/ansible $ 
rik@gentoo ~/git/ansible $ 
rik@gentoo ~/git/ansible $ With ansible-1.9.4^C
rik@gentoo ~/git/ansible $ 
rik@gentoo ~/git/ansible $ 
rik@gentoo ~/git/ansible $ 
rik@gentoo ~/git/ansible $ 
rik@gentoo ~/git/ansible $ cat ansible.cfg | grep log_path
log_path              = /var/log/ansible.log
rik@gentoo ~/git/ansible $ ll /var/log/ansible.log 
-rw-r--r-- 1 rik rik 158592360 Jan 21 14:26 /var/log/ansible.log
rik@gentoo ~/git/ansible $ ansible-playbook --version
ansible-playbook 1.9.4
  configured module search path = /usr/share/ansible:/home/kbruneel/git/ansible/library
rik@gentoo ~/git/ansible $ ansible-playbook datacenter_gitlab.yml -D -C 

PLAY [gitlab_prod] ************************************************************ 

GATHERING FACTS *************************************************************** 
^CERROR: interrupted
rik@gentoo ~/git/ansible $
```

**Comment by sivang** [comment]
is this fixed already?
