### ISSUE TITLE
Regression: ansible requires access to api server for local dependencies

### ISSUE THREAD

**Issue by compuguy** [ansible/ansible#13991]
##### Issue Type:

Bug Report - Regression
##### Ansible Version:

2.0.0.2 - from PPA
##### Ansible Configuration:

Other than upgrading to 2.0.0.2, no config change
##### Environment:

Ubuntu 15.10
##### Summary:

Ansible 2.0.0.2 via the ansible-galaxy command, will not pull from a local github enerprise dependencies, without an internet connection to https://galaxy.ansible.com/api/. Ansible version 1.9.4 had no issues pulling down local dependencies from github enterprise.
##### Steps To Reproduce:

Be on a network without internet access, but has hosted git repos on it (github-enterprise, etc). The playbook is not publicly hosted.

Run dependency script: command used: ansible galaxy install -r requirements.yml
##### Expected Results:

Command runs successfully, standard output
##### Actual Results:

ERROR! The API server (https://galaxy.ansible.com/api/) is not responding, please try again later.

**Comment by compuguy** [comment]
Note as of Ansible 2.0.1.0 this is still broken. Since my workplace's network doesn't have internet, this is preventing any of our github-enterprise hosted roles from updating, restricting us to ansible versions pre 2.x.x.x.

**Comment by compuguy** [comment]
After doing some searching through the issues, it looks like there is a pull request that will add an offline option for galaxy: #14486 

Without this merge, I and anyone using ansible and ansible-galaxy with an internet limited network are limitied to using pre 2.x versions of ansible.

**Comment by timss** [comment]
Thanks for sharing. I guess [patching](https://patch-diff.githubusercontent.com/raw/ansible/ansible/pull/14486.patch) that PR is the way to go while we wait.

**Comment by willthames** [comment]
Proposed fix in #15593
