### ISSUE TITLE
Yum cannot install after upgrade without specifying version

### ISSUE THREAD

**Issue by rmacian** [ansible/ansible#13996]
Issue Type: Bug Report

Ansible Configuration:
ansible 2.0.0.2

Environment:

From OSX El Capitan to CentOs 6.4

Summary:

Yum module fails to install packages after upgrading from 1.9.4 to 2.0.0 without a clear error message. 
Steps To Reproduce:

Create a simple task

``` yaml
- name: test
  yum: name=lynx state=latest 
  tags: test
```

Execute the task within a playbook with -t=test and  --limit to 1 host

if the package is already installed via yum from the console, the playbook detects that is already installed and exits OK

Expected Results:

Package should be installed

Actual Results:

exit code with -vvvv

``` console
fatal: [esjc-dsmm-as03s.om-s.dsn.inet]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"conf_file": null, "disable_gpg_check": false, "disablerepo": null, "enablerepo": null, "exclude": null, "install_repoquery": true, "list": null, "name": ["lynx"], "state": "latest", "update_cache": false}, "module_name": "yum"}, "msg": "Error from rpm: ['/bin/rpm', '-q', '--qf', '%{name}-%{version}-%{release}.%{arch}', 'lynx']: "}
```

**Comment by abadger** [comment]
That commit coupled with the commit in ansible/ansible that it depends on should fix this.  Let us know in a new bug if it's still not working for you with those changes.  the changes have been pushed to the devel and stable-2.0 branches so should be in the 2.0.1 release.
