### ISSUE TITLE
Error while executing ansible commands -  "failed": true,  "msg": "ERROR! paramiko is not installed"

### ISSUE THREAD

**Issue by engbalaji** [ansible/ansible#14002]
Issue Type:

Error executing the Ansible commands in remote hosts

Bug Report
Ansible Version:
Ansible 2.0.0.1

Ansible Configuration:

Nothing, i just finished installing the ansible in Oracle Linuc 6.4 (same kernal as RHEL 6), after the installation when i try to execute any ansible core commands (such as Ping, file or Setup) are showing following error

[root@wautomation-tst01 ~]# ansible -vvv werindbalajil01 -m ping
Using /etc/ansible/ansible.cfg as config file
werindbalajil01 | FAILED! => {
    "failed": true,
    "msg": "ERROR! paramiko is not installed"
}

Environment:

OEL 6.3
[root@wautomation-tst01 ansible]# uname -a
Linux wautomation-tst01.us.int.rci.com 2.6.39-400.109.4.el6uek.x86_64 #1 SMP Mon Jul 22 11:44:00 PDT 2013 x86_64 x86_64 x86_64 GNU/Linux

Python version 
[root@wautomation-tst01 ansible]# python --version
Python 2.6.6

Summary:

When i try to use the basic ansible command it coming with following error 
[root@wautomation-tst01 ~]# ansible -vvv werindbalajil01 -m ping
Using /etc/ansible/ansible.cfg as config file
werindbalajil01 | FAILED! => {
    "failed": true,
    "msg": "ERROR! paramiko is not installed"
}

Steps To Reproduce:

running any ansuble core commands. E.g

[root@wautomation-tst01 ~]# ansible werindbalajil01 -m ping
werindbalajil01 | FAILED! => {
    "failed": true,
    "msg": "ERROR! paramiko is not installed"
}
[root@wautomation-tst01 ~]# ansible -vvv werindbalajil01 -m ping
Using /etc/ansible/ansible.cfg as config file
werindbalajil01 | FAILED! => {
    "failed": true,
    "msg": "ERROR! paramiko is not installed"
}

Expected Results:

 | SUCCESS => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": null
        },
        "module_name": "ping"
    },
    "ping": "pong"
}

Actual Results:

[root@wautomation-tst01 ~]# ANSIBLE_DEBUG=1 ansible -vvv werindbalajil01 -m ping
  2557 1452362993.51001: starting run
Using /etc/ansible/ansible.cfg as config file
  2557 1452362993.74537: in VariableManager get_vars()
  2557 1452362993.74583: done with get_vars()
  2557 1452362993.76058: getting the remaining hosts for this loop
  2557 1452362993.76133: done getting the remaining hosts for this loop
  2557 1452362993.76180: building list of next tasks for hosts
  2557 1452362993.76204: getting the next task for host werindbalajil01
  2557 1452362993.76249: done getting next task for host werindbalajil01
  2557 1452362993.76276:  ^ task is: TASK: meta
  2557 1452362993.76300:  ^ state is: HOST STATE: block=0, task=1, rescue=0, always=0, role=None, run_state=1, fail_state=0, pending_setup=False, tasks child state? None, rescue child state? None, always child state? None
  2557 1452362993.76324: done building task lists
  2557 1452362993.76345: counting tasks in each state of execution
  2557 1452362993.76365: done counting tasks in each state of execution
  2557 1452362993.76385: advancing hosts in ITERATING_TASKS
  2557 1452362993.76407: starting to advance hosts
  2557 1452362993.76427: getting the next task for host werindbalajil01
  2557 1452362993.76451: done getting next task for host werindbalajil01
  2557 1452362993.76472:  ^ task is: TASK: meta
  2557 1452362993.76493:  ^ state is: HOST STATE: block=0, task=1, rescue=0, always=0, role=None, run_state=1, fail_state=0, pending_setup=False, tasks child state? None, rescue child state? None, always child state? None
  2557 1452362993.76516: done advancing hosts to next task
  2557 1452362993.76814: done queuing things up, now waiting for results queue to drain
  2557 1452362993.76842: waiting for pending results...
  2557 1452362993.76862: no more pending results, returning what we have
  2557 1452362993.76883: results queue empty
  2557 1452362993.76903: getting the remaining hosts for this loop
  2557 1452362993.76926: done getting the remaining hosts for this loop
  2557 1452362993.76969: building list of next tasks for hosts
  2557 1452362993.76991: getting the next task for host werindbalajil01
  2557 1452362993.77017: done getting next task for host werindbalajil01
  2557 1452362993.77039:  ^ task is: TASK: ping
  2557 1452362993.77059:  ^ state is: HOST STATE: block=1, task=1, rescue=0, always=0, role=None, run_state=1, fail_state=0, pending_setup=False, tasks child state? None, rescue child state? None, always child state? None
  2557 1452362993.77079: done building task lists
  2557 1452362993.77098: counting tasks in each state of execution
  2557 1452362993.77122: done counting tasks in each state of execution
  2557 1452362993.77141: advancing hosts in ITERATING_TASKS
  2557 1452362993.77160: starting to advance hosts
  2557 1452362993.77179: getting the next task for host werindbalajil01
  2557 1452362993.77201: done getting next task for host werindbalajil01
  2557 1452362993.77223:  ^ task is: TASK: ping
  2557 1452362993.77243:  ^ state is: HOST STATE: block=1, task=1, rescue=0, always=0, role=None, run_state=1, fail_state=0, pending_setup=False, tasks child state? None, rescue child state? None, always child state? None
  2557 1452362993.77263: done advancing hosts to next task
  2557 1452362993.77288: getting variables
  2557 1452362993.77311: in VariableManager get_vars()
  2557 1452362993.77360: done with get_vars()
  2557 1452362993.77409: done getting variables
  2557 1452362993.77429: sending task start callback, copying the task so we can template it temporarily
  2557 1452362993.77448: done copying, going to template now
  2557 1452362993.77470: done templating
  2557 1452362993.77492: here goes the callback...
  2557 1452362993.77516: sending task start callback
  2557 1452362993.77538: entering _queue_task() for werindbalajil01/TASK: ping
  2557 1452362993.77559: werindbalajil01 - putting task (TASK: ping) in queue
  2557 1452362993.77578: worker is 1 (out of 1 available)
  2557 1452362993.77736: exiting _queue_task() for werindbalajil01/TASK: ping
  2557 1452362993.77822: done queuing things up, now waiting for results queue to drain
  2557 1452362993.77837: waiting for pending results...
  2567 1452362993.77969: running TaskExecutor() for werindbalajil01/TASK: ping
  2567 1452362993.77989: in run()
  2567 1452362993.78115: calling self._execute()
  2567 1452362993.80524: starting attempt loop
  2567 1452362993.80565: running the handler
  2567 1452362993.80731: _low_level_execute_command(): starting
  2567 1452362993.80750: _low_level_execute_command(): executing: ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1452362993.81-270355194533225 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1452362993.81-270355194533225 )" )
  2567 1452362993.80794: done running TaskExecutor() for werindbalajil01/TASK: ping
  2567 1452362993.80800: sending task result
  2567 1452362993.80847: done sending task result
  2567 1452362993.80851: WORKER PROCESS EXITING
  2566 1452362993.80977: worker 0 has data to read
  2566 1452362993.81099: got a result from worker 0: <ansible.executor.task_result.TaskResult object at 0x18267d0>
  2566 1452362993.81114: sending result: [u'host_task_failed', u'<ansible.executor.task_result.TaskResult object at 0x18267d0>']
  2566 1452362993.81144: done sending result
  2557 1452362993.81396: got result from result worker: [u'host_task_failed', u'<ansible.executor.task_result.TaskResult object at 0x20d4150>']
  2557 1452362993.81426: marking werindbalajil01 as failed
  2557 1452362993.81446: getting the next task for host werindbalajil01
  2557 1452362993.81463: done getting next task for host werindbalajil01
  2557 1452362993.81480:  ^ task is: None
  2557 1452362993.81494:  ^ state is: HOST STATE: block=1, task=1, rescue=0, always=0, role=None, run_state=4, fail_state=2, pending_setup=False, tasks child state? None, rescue child state? None, always child state? None
werindbalajil01 | FAILED! => {
    "failed": true,
    "msg": "ERROR! paramiko is not installed"
}
  2557 1452362993.81572: no more pending results, returning what we have
  2557 1452362993.81600: results queue empty
  2557 1452362993.81622: getting the remaining hosts for this loop
  2557 1452362993.81649: done getting the remaining hosts for this loop
  2557 1452362993.81695: building list of next tasks for hosts
  2557 1452362993.81720: getting the next task for host werindbalajil01
  2557 1452362993.81747: done getting next task for host werindbalajil01
  2557 1452362993.81766:  ^ task is: None
  2557 1452362993.81786:  ^ state is: HOST STATE: block=1, task=1, rescue=0, always=0, role=None, run_state=4, fail_state=2, pending_setup=False, tasks child state? None, rescue child state? None, always child state? None
  2557 1452362993.81807: done building task lists
  2557 1452362993.81826: counting tasks in each state of execution
  2557 1452362993.81844: done counting tasks in each state of execution
  2557 1452362993.81863: all hosts are done, so returning None's for all hosts
  2557 1452362993.81883: done queuing things up, now waiting for results queue to drain
  2557 1452362993.81907: waiting for pending results...
  2557 1452362993.81927: no more pending results, returning what we have
  2557 1452362993.81949: results queue empty
  2557 1452362993.81969: running handlers
  2557 1452362993.82096: RUNNING CLEANUP

**Comment by jimi-c** [comment]
I have seen this occur when some requirements for paramiko are not installed. I would open up a python shell and type `import paramiko` to see if any errors are raised.

**Comment by engbalaji** [comment]
I tried installing "paramiko" it came out with already installed. But Python shell received an error "module not found"

**Comment by engbalaji** [comment]
I got following error importing paramiko 

> > > import paramiko
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named paramiko

tried installing the paramiko 

[root@wautomation-tst01 ansible]# pip install --upgrade paramiko
Requirement already up-to-date: paramiko in /usr/lib/python2.6/site-packages
Requirement already up-to-date: ecdsa>=0.11 in /usr/lib/python2.6/site-packages/ecdsa-0.13-py2.6.egg (from paramiko)
Requirement already up-to-date: pycrypto!=2.4,>=2.1 in /usr/lib64/python2.6/site-packages (from paramiko)

**Comment by jimi-c** [comment]
I would recommend fully uninstalling and the reinstalling paramiko and pycrypto.

**Comment by jhawkesworth** [comment]
I'd also recommend logging out and in again.

I haven't seen this specific problem but had to do this to pick up correct
environment after running
pip install --upgrade <some package>
in the past

**Comment by engbalaji** [comment]
@jimi-c - uninstall & reinstall helped. Now the remote connections are working without any issues.

**Comment by jimi-c** [comment]
Excellent, I'll go ahead and close this issue then.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by chusiang** [comment]
I fixed it with upgrade pip and some python package with pip, thank you  for @jhawkesworth .

```
$ sudo pip install -U pip
$ sudo pip install -U pyasn1 setuptools ...
```
