### ISSUE TITLE
ImportError: No module named runner

### ISSUE THREAD

**Issue by s270987763** [ansible/ansible#14018]
when I use ansible 2.0.0.2 in python
## In [1]: import ansible.runner

ImportError                               Traceback (most recent call last)
<ipython-input-1-dc0444011ae8> in <module>()
----> 1 import ansible.runner

ImportError: No module named runner

ansible.runner removing?

how can I resolve this problem?

**Comment by bcoca** [comment]
python API changed, read the details here http://docs.ansible.com/ansible/developing_api.html

closing this as it is not a bug nor feature reqeust

**Comment by s270987763** [comment]
http://docs.ansible.com/ansible/developing_api.html#python-api-pre-2-0
this example looks not changed

**Comment by whmove** [comment]
When the document can be updated.

**Comment by bcoca** [comment]
please read that page, yes, the pre 2.0 example has not changed ... as it shouldn't.

**Comment by eyablokov** [comment]
I have the same problem (question) in Homebrew on OS X.
Please, update the documentation and describe how we should use it now.
