### ISSUE TITLE
Become can't sudo without password

### ISSUE THREAD

**Issue by nervo** [ansible/ansible#14022]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.0.0.2
  config file =
  configured module search path = Default w/o overrides
##### Ansible Configuration:

Nothing particular
##### Environment:

Running from OSX 10.11.2, ansible installed via homebrew
Target OS, up to date debian wheezy
##### Summary:

It seems that we can't use become (default sudo adapter) without defining a sudo password.
##### Steps To Reproduce:

Just run

```
ansible foo -a "whoami" -b
```

Or

```
ansible foo -a "whoami" -s
```
##### Expected Results:

```
foo | SUCCESS | rc=0 >>
root
```
##### Actual Results:

```
foo | FAILED | rc=0 >>
ERROR! Missing sudo password
```

Of course, sudo without password is well configured on the target machine, and everything is ok with ansible 1.9

**Comment by chrrrles** [comment]
I was unable to duplicate your bug with stable 2.0 - can you paste the output from running the command with verbose logging (-vvvv) ?

**Comment by nervo** [comment]
Of course.
That's pretty interesting, i've joined the verbose output of both version 1.9.4 and 2.0.0.2

(sensible informations are obfuscated by [***])

### 1.9.4

```
$ ansible -i hosts [******] -a "whoami" -b -vvvv
<[******]> ESTABLISH CONNECTION FOR USER: [***]
<[******]> REMOTE_MODULE command whoami
<[******]> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/[***]/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 [******] /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1453362681.86-178760134935903 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1453362681.86-178760134935903 && echo $HOME/.ansible/tmp/ansible-tmp-1453362681.86-178760134935903'
<[******]> PUT /var/folders/gf/yzblymdj07j5h58mx8hl3g140000gn/T/tmpZmrJp3 TO /home/[***]/.ansible/tmp/ansible-tmp-1453362681.86-178760134935903/command
<[******]> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/[***]/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 [******] /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=yamxmrjsupfwzftyrucblfkliusebqgi] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-yamxmrjsupfwzftyrucblfkliusebqgi; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/[***]/.ansible/tmp/ansible-tmp-1453362681.86-178760134935903/command; rm -rf /home/[***]/.ansible/tmp/ansible-tmp-1453362681.86-178760134935903/ >/dev/null 2>&1'"'"''
[******] | success | rc=0 >>
root
```

Note that in this case, the user is well discovered as [***]

### 2.0.0.2

```
$ ansible -i hosts [******] -a "whoami" -b -vvvv
Using /[******]/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<[******]> ESTABLISH SSH CONNECTION FOR USER: None
<[******]> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/[***]/.ansible/cp/ansible-ssh-%h-%p-%r -tt [******] '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1453362473.91-197228348190300 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1453362473.91-197228348190300 )" )'
<[******]> PUT /var/folders/gf/yzblymdj07j5h58mx8hl3g140000gn/T/tmpFNGLQU TO /home/[***]/.ansible/tmp/ansible-tmp-1453362473.91-197228348190300/command
<[******]> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/[***]/.ansible/cp/ansible-ssh-%h-%p-%r '[[******]]'
<[******]> ESTABLISH SSH CONNECTION FOR USER: None
<[******]> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/[***]/.ansible/cp/ansible-ssh-%h-%p-%r -tt [******] '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-dkczdvrfopbjcuygajybgfkvykqlhzhl; LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8 LC_MESSAGES=fr_FR.UTF-8 /usr/bin/python /home/[***]/.ansible/tmp/ansible-tmp-1453362473.91-197228348190300/command; rm -rf "/home/[***]/.ansible/tmp/ansible-tmp-1453362473.91-197228348190300/" > /dev/null 2>&1'"'"'"'"'"'"'"'"''"'"''
[******] | FAILED | rc=0 >>
ERROR! Missing sudo password
```

Note that in this case, user does not seem to be discovered ("None")

Please not also that the evocated ansible.cfg is as simple as:

```
[defaults]
roles_path = /[******]/ansible:/usr/local/etc/ansible/roles
```

And also note that the way of sshing to the targetted host is defined in a ~/.ssh/config file, especially with a gateway:

```
Host *.[******]
    User                    [***]
    IdentityFile            ~/.ssh/[***]
    ForwardAgent            yes
    ProxyCommand            ssh [***]@[******] "nc %h %p"
    StrictHostKeyChecking   no
    HashKnownHosts          no
Host [******]
    User                    [***]
    IdentityFile            ~/.ssh/[***]
    ForwardAgent            yes
    StrictHostKeyChecking   no
    HashKnownHosts          no
```

**Comment by jimrazmus** [comment]
I am experiencing the same issue.  Running Mac OS X 10.11.2 with the devel branch against Centos 7.

I noticed that the sudo invocation includes '-S'.  The manual says:

 '-S' option causes sudo to read the password from the standard input instead of the terminal device.  The password must be followed by a newline character.

Although, running this:  sudo -H -S -n -u root /bin/sh -c /bin/sh -c  does give me a root prompt without requiring a password.  The invoking user is in the wheel group and sudoers includes the NOPASSWD option for that group.

**Comment by nervo** [comment]
Ah, i've got something !
In our situation, the guilty is the "-n" sudo parameter introduced in ansible 2

```
 -n, --non-interactive
             Avoid prompting the user for input of any kind.  If a password is required for the command to run, sudo will display an error message and exit.
```

If i directly run sudo on the target os with it:

```
$  sudo -n whoami
sudo: sorry, a password is required to run sudo
```

And without it:

```
$  sudo whoami   
root
```

**Comment by chmac** [comment]
I just found [this](http://docs.ansible.com/ansible/intro_configuration.html#sudo-flags) in the docs:

> Note that ‘-n’ will conflict with using password-less sudo auth, such as pam_ssh_agent_auth. In some situations you may wish to add or remove flags, but in general most users will not need to change this setting::

That `-n` flag kills us. I was able to overcome this by adding this to our `ansible.cfg` file:

```
[defaults]
sudo_flags=-H -S
```

Also posted [the solution here](http://www.callum-macdonald.com/2016/03/09/ansible-and-pam-ssh-agent-auth/), hopefully saves some folks the hours I spent tracking this down... :-)

**Comment by nervo** [comment]
Woo, nice catch, thx !
We are exactly in the same situation, using pam_ssh_agent_auth.
Btw, @chrrrles, any chance to have an official solution without a dedicated configuration file ?

**Comment by bcoca** [comment]
@nervo, the config would be the official way to fix this,  you can also set it on ansible_sudo_flags per group or per host.

closing this ticket as the configuration is there specifically for this type of issues.

**Comment by ursachec** [comment]
Just going to mention this here in case someone else finds themselves in the same situation:

Having started with `ansible` only two hours ago, I wasn't really sure what was happening in the background while trying to automate a simple `nginx` installation.

Being an avid user of `ssh` config files, I made the wrong assumption that whatever `ansible` was running on the server will not require a password when running as a `sudo` user. Somehow that lead me down a path trying to debug my local `ansible` configuration when all was needed was to pass the `--ask-sudo-pass` parameter.

**Comment by paulcalabro** [comment]
Just to add another possible solution I just discovered: make sure you have the ability to run `/bin/sh` via sudo. I tested with the `-n` flag above and then suddenly saw issues regarding timeouts waiting for input. I did some further testing on the remote server and determined  that this was the source of my particular issue (observed via `-vvv`): 

`sudo -H -S -u root /bin/sh -c <commands to run ansible stuff>`

I needed to add `/bin/sh` to my /etc/sudoers file for my user.

ps. Thanks @bcoca for catching the incorrect usage of my `become` flag in another post.

**Comment by Akhiles7** [comment]
@paulcalabro 

Adding /bin/sh for your user to /etc/sudoers file actually doing your user root, as you can create any *sh file with ANYTHING you want and run it as your user like 'sudo sh mysuperfile.sh'. Nothing stops you (or any1 who can login by this user on your system) to corrupt all the system by user that "seems to be not root"...

I ended up to using shell instead of module...

```
- name: WF restart
  shell: "sudo systemctl restart {{ wf_service }}"
```
While I have this for my user in sudoers:
`myuser myhost = (root) NOPASSWD: /usr/bin/systemctl *wildfly*`

If any1 knows how to make module work without creating second root from your user - please share.

Upd:
As an workaround (need to be checked) you can modify sudo rule to smth like:
`myuser myhost = (root) NOPASSWD: /bin/sh -c *'some_ansible_stuff_marker'*`
to allow only running this with some pre-set arguments, though if some1 knows that marker he can create sh file with name containing that marker :)

Upd2:
Worked with:
`myuser myhost = (root) NOPASSWD: /bin/sh *python* *systemd.py*`
At least it is a bit safer - we limited running under root only systemd.py using python binary. Off course now some1 can just create python script that would be called systemd.py and run it as root thus do whatever he want to do with the system but using python at this time ;)

**Comment by goferito** [comment]
@Akhiles7 use raw instead of shell (`raw: "sudo systemctl restart wtf-service"`)
Then you can just have your sudoers with that one command.

**Comment by xarses** [comment]
I, like @Akhiles7 have a prescriptive /etc/sudoers which has a list of commands that users are allowed to use with `NOPASSWD`. a reduced set, specifically those that belong to impersonation and audit escapes (shells and su) are either outright blocked for some users, or allowed after providing the password.

is there a formulaic way to prevent ansible from "reshelling" all of the commands via sudo/become wrappers. either a host, playbook, or ansible.conf would be the most reasonable entry points. Switching individual tasks to `raw` as @goferito functionally accomplishes this, but is not scalable as it requires modifying every task that I may ever use.
