### ISSUE TITLE
variables scope when including playbooks

### ISSUE THREAD

**Issue by nicolaasuni** [ansible/ansible#1403]
On the 0.8 version, when including several playbooks the variables defined on each "vars" section where local to the playbook. Now, on the 0.9 version, seems that the variables have a global scope, so variables with the same name are overwritten!
All my scripts written for 0.8 version are not working with the 0.9 version.

On the following example the "myvar" variable is assigned to the last value "B" on 0.9 and the first playbook is executed with this value. While in the 0.8 version the first playbook was executed with the A value and the second with the B value.

---

playbookALL.yml:
- include: playbookA.yml
- include: playbookB.yml

---

playbookA.yml:
- hosts: HostA
  user: root
  
  vars_files:
  - ../../vars/VarsGlobal.yml
  
  vars:
   myvar: "A"
  
  tasks:
  - include: ../../tasks/dosomething.yml

---

playbookB.yml:
- hosts: HostB
  user: root
  
  vars_files:
  - ../../vars/VarsGlobal.yml
  
  vars:
   myvar: "B"
  
  tasks:
  - include: ../../tasks/dosomething.yml

---

**Comment by nicolaasuni** [comment]
As suggested by daniel_hozac:

git revert c5469f636782e4ce403cb2a62193e590cd943528

fixes the problem, so it should be easy to fix.

**Comment by mpdehaan** [comment]
Strangely, this passed the tests.  Which means we need more variable tests.
  I'll revert this ASAP.

**Comment by mpdehaan** [comment]
reversion pushed.   I'll file a ticket to make --extra-vars work at higher
priority differently.
