### ISSUE TITLE
strategy: free messes up the terminal it is run in

### ISSUE THREAD

**Issue by orderedchaosdev** [ansible/ansible#14033]
Issue Type:

Bug Report

```
ansible 2.1.0 (devel c9a5f7ea7e) last updated 2016/01/11 13:13:55 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 33014c6db1) last updated 2016/01/11 13:13:54 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 82a4cf84be) last updated 2016/01/11 13:13:54 (GMT -700)

```

Ansible Configuration:

```
transport: ssh
```

Environment:

Centos 6

Summary:

Using strategy: free seems to send control characters or other special characters to the terminal and break it.

Steps To Reproduce:

I just made a simple four host test group and ran a shell command on each host to get hostname.
I'm sorry I can't make detailed test examples for a few days because I can't risk running random commands on my control server and need to set up a test group to test this safely.

Expected Results:

Playbook runs with each host running independent of each other.

Actual Results:

The playbook itself seems to execute as expected but the terminal becomes messed up in various ways such as font being changed or it looking like some of the output from ansible was executed as commands in the terminal.
I have seen fonts change, the command history have strings of output from the playbook run output, and the echo of characters typed in the terminal not working.

**Comment by bcoca** [comment]
fixed via 74506297338b706bfd973b10814027db65fa12c2
