### ISSUE TITLE
Extra modules missing from 2.0.0.2 release via pip

### ISSUE THREAD

**Issue by wholroyd** [ansible/ansible#14059]
In particular, I was trying to use the `ec2_vpc_net_facts` module. For whatever reason, the installation via pip seems to be missing this module as well as a couple others even though they have been around for a while.

I took a file list from a machine where I...
- installed from pip (2.0.0.2)
- installed from github source using `make && make install` (devel branch, 2.1.0)
- github clone directory (devel branch, 2.1.0)

The modules missing are...
- ec2_vpc_net_facts.py
- ecs_service.py
- ecs_service_facts.py

Outputs are at https://gist.github.com/wholroyd/87943f3f71fd0f09fa8f. If you want to see the pip issue yourself, I caught the problem in fresh built docker image `wholroyd/centos-ansible:latest`.

**Comment by bcoca** [comment]
so the ecs_service modules are not expected to be there, they are flagged as part of 2.1, as for the ec2_vpc_net_facts, it was a bug, but it is already fixed in the stable-2.0 branch and will be part of the next point release.
