### ISSUE TITLE
authorized_key and $FILE macro -- docs need to have quotes

### ISSUE THREAD

**Issue by jtognazzi** [ansible/ansible#1405]
I performed some simple tests with the authorized_key and $FILE macro and it seems to me that the $FILE macro needs to be quoted:
tasks:
    - authorized_key user=$item key="$FILE(/keys/$user1)"
      with_items:
         - pinky
         - brain
         - snowball

without the quote I have the following error:
 {"failed": true, "msg": "this module requires key=value arguments"}

In the docs it is mentionned twice without the quotes...
[Getting values from files](http://ansible.cc/docs/playbooks2.html?highlight=pipe#getting-values-from-files)
[authorized_key module documentation](http://ansible.cc/docs/modules.html#authorized-key)

**Comment by mpdehaan** [comment]
I suspect we've got some spaces in the file output and that's what's doing it.

We'll update the docs... thanks!

**Comment by mpdehaan** [comment]
fix pushing shortly, thanks
