### ISSUE TITLE
Template module deleting directories.

### ISSUE THREAD

**Issue by adamrmelnyk** [ansible/ansible#14056]
ansible 2.0.0.2, OS X 10.11.2, target is Ubuntu 14.04

When using the template module, I included `state=absent`
 to see if that would remove some files from the server without having to write some other playbook. Ansible came back with the message:

```
< TASK [list files in directory] >

changed: [23.41.251.190]
changed: [23.41.251.190]

< TASK [debug] >

ok: [23.41.251.190] => {
    "msg": "my_fake_dir"
}

.
.
.

changed: [23.41.251.190] => (item=some-file.conf)
failed: [23.41.251.190] => (item=some-other-file.conf) => {"changed": true, "failed": true, "item": "some-other-file.conf", "msg": "unsupported parameter for module: state"}
failed: [23.41.251.190] => (item=some-other-other-file.conf) => {"changed": true, "failed": true, "item": "some-other-other-file.conf", "msg": "unsupported parameter for module: state"}
```

```
- name: Testing A Bug
  hosts: application_servers
  sudo: yes
  vars_files:
    - "vars/common-vault.yml"
  tasks:
    - name: create the fake directory
      file: path=/home/ubuntu/my_fake_dir state=directory
    - name: list files in directory
      command: ls /home/ubuntu/
      register: list
    - debug: msg="{{ list.stdout }}"
    - name: Add some files to my fake directory
      template: src=my_test_files/{{ item }} dest=/home/ubuntu/my_fake_dir owner=root group=root
      with_items:
        - some-file.conf
        - some-other-file.conf
        - some-other-other-file.conf
    - name: Accidentally delete the directory
      template: src=my_test_files/{{ item }} dest=/home/ubuntu/my_fake_dir owner=root group=root state=absent
      with_items:
        - some-file.conf
        - some-other-file.conf
        - some-other-other-file.conf
```

The playbook won't continue after that so I checked manually and the directory is missing. Though Ansible warns me about the module state being unsupported. Adding it causes the directory `my_fake_dir` to be deleted.

**Comment by sivel** [comment]
I assume this is due to with the fact that you are specifying a `dest` which is a directory, instead of using something like:

```
dest="/home/ubuntu/my_fake_dir/{{ item }}"
```

And because we copy the tasks args, when creating args for the copy/file modules, I assume state is getting passed down, and nuking the directory, because it doesn't have the appropriate context of what the task was meant to do.

**Comment by adamrmelnyk** [comment]
Excellent. That looks like it fixed my problem. Thanks @sivel!

**Comment by bcoca** [comment]
still, this is a nasty bug that should not happen even by accident

**Comment by sivel** [comment]
@bcoca agreed

**Comment by adamrmelnyk** [comment]
@sivel It deleted some config files on the server I sorta needed which was not so awesome. :(. oh well.
