### ISSUE TITLE
optional timestapms on output

### ISSUE THREAD

**Issue by akostadinov** [ansible/ansible#14052]
Hello, I see #2454 but I think it was not really resolved. There is posted a callback plug-in, it's possible that I don't understand but it seems to me, to use that, you need to modify playbook. While it is useful to be able to get timestamps just by running any playbook (optionally).

So my request is to provide a timestamp options to ansible.

**Comment by bcoca** [comment]
no need to modify playbook, just add a callback plugin (drop in callback_plugins dir) or enable one shipped with ansible:

```
ansible.cfg:
allback_whitelist = profile_tasks
```

**Comment by akostadinov** [comment]
when you run from a CI system playbooks that you do not own, it is much easier to just add a parameter to the executable. Also it makes a lot of sense, sometimes you need timestamps, sometimes external logger provides them. So IMHO it makes sense to have a native ansible option to add timestamps... my 2 cents. It looks a good number of users +1ed it but old ticket was closed for non-collaborators.

**Comment by bcoca** [comment]
Every entry in ansible.cfg has an equivalent environment variable:
ANSIBLE_CALLBACK_WHITELIST

## 

Brian Coca

**Comment by akostadinov** [comment]
@bcoca , thank you, that works real nice and I guess shows timestamps for the specific hosts, not the time message appeared in console. Very useful.
