### ISSUE TITLE
Module "command" prints warning when executing apt-get autoremove

### ISSUE THREAD

**Issue by sandrinr** [ansible/ansible#14050]
Ansible version 2.0.0.2 running on OSX.

When using a task like this one:

```
- name: Check if packages need to be autoremoved
  command: apt-get --dry-run autoremove
  register: check_autoremove
  changed_when: False
```

Then I get the warning:

```
[WARNING]: Consider using apt-get module rather than running apt-get.
```

Although the `apt` module does not support the `autoremove` functionality.  Note: I only know the `apt` module. AFAIK there is no `apt-get` module as suggested in the warning.

**Comment by jimi-c** [comment]
This is really just a suggestion, as it's detected a module (in this case the apt module) overlaps with the command you're running. It can be ignored.

Thanks!

**Comment by ssbarnea** [comment]
Warnigns were not invented to be ignored. The fact that ansible  team you decided to "deprecate" apt usage without properly implementing our apt module does not mean that user have to "ignore" this unneeded spam. 

It seems to be like a bug while implementing the deprecation feature. At least we need a way to disable warnings for specific tasks. 

I tried to use [command_warnings](http://docs.ansible.com/ansible/intro_configuration.html#command-warnings): no at the task level but it seems that they are not supported, and disabling them globally does not make more sense either.

**Comment by edillmann** [comment]
this work's for me :

```
- name: Cleanup apt cache
  command: apt-get clean warn=no
  changed_when: False
```

**Comment by SupremeGit** [comment]
ssbarnea is correct.

WARNINGS WERE NOT MEANT TO BE IGNORED.
... UNLESS I SPECIFICALLY DECIDE TO IGNORE THEM.

But the useless fools who develop ansible seem to believe they can spew a billion useless warnings AND THEN NOT EVEN ALLOW ME TO HIDE THE WARNINGS I HAVE CAREFULLY CONSIDERED AND DECIDED TO IGNORE. 

How is anyone supposed to notice REAL warnings they might actually be interested in, when they cannot disable the millions of spurious warnings that they know they're not interested in.

When users see a task generating a spurious, infuriating, and inappropriate warning, we MUST be able to silence it, SO WE CAN ACTUALLY NOTICE WHEN/IF A REAL WARNING IS GENERATED ELSEWHERE.

Preventing users from silencing these warnings only buries real warnings in spurious garbage, and leads ot users just ignoring every warning they see.

A METHOD MUST BE PROVIDED TO DISABLE THESE USELESS AND INCORRECT WARNINGS.

**Comment by ssbarnea** [comment]
@SupremeGit I hope people will not take you comments personal and instead will what it really matters. I do sustain your points, less the way of putting it ;)

**Comment by bcoca** [comment]
@SupremeGit  soo, you basically want `warn: off` ? the command module already has this.

**Comment by SupremeGit** [comment]
Ah.
Ok, i stand corrected. Thanks for the tip. Apologies for my attitude. Christ on a bike, Ansible is a frustrating and annoying thing at times. It does wind me up.

**Comment by EricoCartmanez** [comment]
# Disabling warnings
```
- name: Using curl to connect to a host via SOCKS proxy (unsupported in uri). Ordinarily this would throw a warning.
  shell: curl --socks5 localhost:9000 http://www.ansible.com
  args:
    warn: False
```
