### ISSUE TITLE
2.0.0.2: Get MemoryError when fetching large file 

### ISSUE THREAD

**Issue by brendam** [ansible/ansible#14064]
I'm getting an error similar to #11702 when using fetch for large files in Ansible 2.0.0.2. The files that have been failing are 8Gb or more. Not sure what the smallest file that will fail is.

```
FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):
File "/home/ubuntu/.ansible/tmp/ansible-tmp-1453419255.99-154763899674185/slurp", line 2010, in <module>
  main()
File "/home/ubuntu/.ansible/tmp/ansible-tmp-1453419255.99-154763899674185/slurp", line 70, in main
   data = base64.b64encode(file(source).read())
MemoryError
", "msg": "MODULE FAILURE", "parsed": false}
```

command in the playbook is:
`fetch: src={{ server_backup_partition | quote }}/{{ inventory_hostname | lower }}-{{ ansible_date_time.date | quote }}.tar.gz dest={{ local_backup_dir }}/ flat=yes fail_on_missing=yes`

Running as an adhoc command works:

`ansible Server1 -m fetch -a "src=/mnt/backup-2016-01-22.tar.gz dest=/Volumes/projects/ flat=yes"`

I'm using Ansible 2.0.0.2 with Python 2.7.10 on OSX 10.10.5 and the server is Ubuntu trusty.

**Comment by sivel** [comment]
When running in a playbook, is your task using "become" or "sudo"?

Looks like when run with elevated permissions slurp will be used to calculate the checksum, which could cause memory errors.

I can see that you aren't running with become as an ad-hoc command.

If you are using become in your play, try setting `become: no` on your task and see if that resolves the issue.

**Comment by brendam** [comment]
yes I am using become. I'll test your suggestion, thanks.

**Comment by brendam** [comment]
That worked, fetched a 12.6G file without any problem. Thanks @sivel!

**Comment by sivel** [comment]
I've opened a pull request at https://github.com/ansible/ansible-modules-core/pull/2858 that adds a note about the potential problems of running `fetch` with `become`.  Closing this issue.
