### ISSUE TITLE
ssh key connection on openshift

### ISSUE THREAD

**Issue by amjadbooxmedia** [ansible/ansible#14069]
| UNREACHABLE! => {
    "changed": false, 
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 22 && mkdir -p \"$( echo $HOME/.ansible/tmp/ansible-tmp-1453454818.34-93920951582093 )\" && echo \"$( echo $HOME/.ansible/tmp/ansible-tmp-1453454818.34-93920951582093 )\" ), exited with result 1: mkdir: cannot create directory `/var/lib/openshift/5649c22b7628e1ea2d0000bc//.ansible': Permission denied\r\n", 
    "unreachable": true
}

**Comment by jimi-c** [comment]
@amjadbooxmedia could you please provide more details regarding the problem you're having? Using https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md is a good start.

**Comment by vbotka** [comment]
In my case the problem described above disappeared when I removed an empy vars_file from the playbok.

```
#  vars_files:                                                                                                                        
#    - ~/.ansible/vars/do-bsd-test.yml                                                                                                
```

vars_file size was 0 created with touch command.

```
> ll ~/.ansible/vars/do-bsd-test.yml 
-rw-rw-r-- 1 vlado vlado 0 Sep  6 10:38 /home/vlado/.ansible/vars/do-bsd-test.yml
```

My 2 cents. Thank you for the effort. Cheers!
-vlado

**Comment by jimi-c** [comment]
@vbotka interesting, was it different permissions? I'm curious how any zero-length file (even with bad permissions) would cause an unreachable error to occur. With which version of Ansible did you see this occur?
