### ISSUE TITLE
group_vars not working as expected 

### ISSUE THREAD

**Issue by ttbigc** [ansible/ansible#14060]
##### Summary:

From my understanding group_vars should handle nested or "children group" vars based of the following inventory INI file:
/etc/ansible/hosts:
[ADC-8]
scepter.test.com
[ADC-1]
orb.test.com
[ADC:children]
ADC-8
ADC-1

/etc/ansible/group_vars/ADC/ADC-8.yml:
ntp_servers:
- 10.1.1.1
- 10.1.1.2

/etc/ansible/group_vars/ADC/ADC-1.yml:
ntp_servers:
- 192.1.1.100
- 192.1.1.200

/etc/ansible/group_vars/ADC/all.yml
common_vars:
- test1

However host orb is picking up ntp_servers value from ADC-8 instead of ADC-1. Is this a bug or am I not understanding how to correctly implement nested(children) groups?

Tested with both playbook run and -m debug -a "var=ntp_servers" which returns returns ntp_servers 10.1.1.1 & 10.1.1.2 for both host orb and scepter.

**Comment by ttbigc** [comment]
Tested on both ansible 1.9.4 and 2.1.0 which makes me believe not a bug but how I am implementing but from documentation I am uncertain to expected behavior of group_vars

**Comment by mattwillsher** [comment]
@ttbigc the group vars file names are:

```
group_vars/ADC-8
group_vars/ADC-1
group_vars/all
```

No need for .yml or the sub dir. 

Content is a standard yml file. e.g:

```
---
key: value
something: 2
```

Do this help?

**Comment by ttbigc** [comment]
No Matt this does not help. As I mentioned above I believe I have the concept correct however it is not working as I feel it should. I should be able to have "children" groups that can also contain an all var file along with group specific:

group_vars/ADC/ADC-8.yml
group_vars/ADC/ADC-1.yml
group_vars/ADC/all
group_vars/all

Issue is Ansible seems to always take ntp_server var from ADC-8 and never look at ADC-1. It does pull additional vars from all as expected. Does ansible not handle this type of nested group_var behavior?

Also I know I do not have to have the .yml but that is just a preference as both ways should work.

**Comment by mattwillsher** [comment]
What if you take ADC-8.yml and ADC-1 out of the ADC directory? My understanding of the docs is that ADC/\* will all get included for the ADC group members and hence will have two conflicting ntp_servers lists for all servers in the ADC group. If you move those two vars files out of ADC/ does that work as expected?

group_vars/ADC/all and group_vars/all will still apply to all members of ADC and all hosts regardless of group respectively.

**Comment by ttbigc** [comment]
Thanks Matt. You are correct and that I should basically remove the folder ADC. 
I went back and re-read the group_vars docs and I can see how I read more into it than what I should of.
Appreciate your time and help! Closing issue.
