### ISSUE TITLE
--limit should take commas

### ISSUE THREAD

**Issue by skvidal** [ansible/ansible#1407]
Right now hosts are separated in --limit with ; or : but -i takes commas as a divider. Make comma optional to  do the same.

**Comment by dagwieers** [comment]
+1

**Comment by skvidal** [comment]
On Mon, 22 Oct 2012, Dag Wieers wrote:

> +1

if this is acceptable I'll send an utterly trivial patch to make this 
work.

-sv

**Comment by mpdehaan** [comment]
Totally acceptable.  Make it so, #1

**Comment by skvidal** [comment]
https://github.com/ansible/ansible/pull/1416
