### ISSUE TITLE
 [python3] [bug] Unexpected Exception: name 'basestring' is not defined

### ISSUE THREAD

**Issue by ashemedai** [ansible/ansible#14070]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.0.0.2
  config file = 
  configured module search path = Default w/o overrides
##### Ansible Configuration:

ansible.cfg used in this case:

[defaults]
command_warnings = True
deprecation_warnings = True
error_on_undefined_vars = True
fact_caching = memory
gathering = smart
roles_path = roles
system_warnings = True
##### Environment:

Linux 2-1b 4.2.0-25-generic #30-Ubuntu SMP Mon Jan 18 12:31:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux (Xubuntu 15.10)
##### Summary:

`Unexpected Exception: name 'basestring' is not defined` when running a playbook with Python 3.4.3+.
##### Steps To Reproduce:

Pip install ansible under Python 3. Run playbook which contains some roles (haven't been able to determine the minimal set that triggers this to share it).
Tested it with Python 2 (2.7.10) does not give this error.
##### Expected Results:

Playbook to run without failure.
##### Actual Results:

```
% ansible-playbook -C playbooks/xxx.yaml -i inventory/staging -K --ask-vault-pass
SUDO password: 
Vault password: 
Unexpected Exception: name 'basestring' is not defined
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 85, in <module>
    sys.exit(cli.run())
  File "/usr/local/lib/python3.4/dist-packages/ansible/cli/playbook.py", line 150, in run
    results = pbex.run()
  File "/usr/local/lib/python3.4/dist-packages/ansible/executor/playbook_executor.py", line 87, in run
    self._tqm.load_callbacks()
  File "/usr/local/lib/python3.4/dist-packages/ansible/executor/task_queue_manager.py", line 149, in load_callbacks
    elif isinstance(self._stdout_callback, basestring):
NameError: name 'basestring' is not defined
```

**Comment by ashemedai** [comment]
http://www.rfk.id.au/blog/entry/preparing-pyenchant-for-python-3/ details a possible solution.

**Comment by jimi-c** [comment]
We have workarounds for this, and we've been cleaning up the code for py3, however it's still a process and we're not ready to start accepting issues on this. If you want to send a PR to address it, feel free, however I'm going to close this issue right now.

Thanks!

**Comment by felipelerena** [comment]
What do you mean you are not ready to accept issues on this? Man, you just leave the issue open until you have time to fix it, you don't close it just because you have no time...

This issue is big because many people (as me) can't use ansible with Python 3

**Comment by gbarosio** [comment]
I have no time to read.
