### ISSUE TITLE
[2.0] loop output now happens at the end of loop, not on each item

### ISSUE THREAD

**Issue by SteveEdson** [ansible/ansible#14072]
Previously, before 2.0, each step (using `with_items`) within a task would echo out the status as it happened. This allowed the user to see the progress and to know that Ansible is still running.

However, since 2.0, it now only show the steps once the task has finished as a whole. 
This is makes it feel like the tasks have hung / stopped and it really makes everything feel much, much slower.

Is there a reason for this change? In my opinion, it has a massive negative affect of the UX as it appears that no progress is being made and that the script needs to be terminated.

This issue initially caused me to open #13835, as I thought it wasn't working at all.

Thanks.

**Comment by bcoca** [comment]
known issue, unintended consequence on how we deal with loops now, but we do plan on fixing it.

**Comment by ktaragorn** [comment]
@bcoca is there a reason this isnt being addressed right now (waiting for other developments etc?) or can I take a whack at it?

**Comment by bcoca** [comment]
take a whack at it, viewed right now as lower priority than most other issues, this is a 'display timing' not something that is really broken.

**Comment by SteveEdson** [comment]
While this is being discussed, would it also be possible to take into account the number of items when displaying the summary, for example I get:

`localhost                  : ok=10   changed=2    unreachable=0    failed=0`

but within those 2 tasks, 5 items changed, Maybe something like `changed=2 (5 items)` perhaps?

**Comment by bcoca** [comment]
@SteveEdson open a new feature request ticket for that

**Comment by SteveEdson** [comment]
No problem, opened #14373

**Comment by SteveEdson** [comment]
Thanks everyone :+1:
