### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by khinze** [ansible/ansible#14084]
Hi there,

Im getting the error:
[Errno 2] No such file or directory
Im running ansible version 2.0.0.2:

Location: /usr/local/lib/python2.7/dist-packages
Requires: paramiko, jinja2, PyYAML, setuptools, pycrypto
- name: Gradle Build
  command: 'gradle build'
  args:
    chdir: /home/ubuntu/dev/myapp

The path exists. 

Any recommendation to why this might be happening and how to solve it.

**Comment by khinze** [comment]
FAILED! => {"changed": false, "cmd": "gradle build", "failed": true, "invocation": {"module_args": {"_raw_params": "gradle build", "_uses_shell": false, "chdir": "/home/ubuntu/dev/myapp", "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "msg": "[Errno 2] No such file or directory", "rc": 2}

**Comment by tomekit** [comment]
Did you solve it? Facing similar problem.

**Comment by thewolf** [comment]
try adding these two params: -become --ask-become-pass
