### ISSUE TITLE
UnboundLocalError: local variable 'l_value' referenced before assignment in j2 template

### ISSUE THREAD

**Issue by mattwillsher** [ansible/ansible#14088]
The following block of code was working up until recently, but has, in the past few weeks, broken for some people on CentOS 6.7. The issue appears to be that `value` in the  `body_option` macro is not declared. Explicitly setting 'set value = undefined' at the top of `body_option` 'fixes' the problem but seems somewhat counter intuitive.  I suspect some thing has changed in Jinja2 (or Ansible's interaction with certain versions of it?). Any help understanding what's going on here and why it's changed recently would be appreciated - the rest of the role makes heavy use of passing undefined variables to toggle setting, and I'm a little concerned that might all break at some point too.

https://github.com/willshersystems/ansible-sshd/blob/master/templates/sshd_config.j2 is the full code, https://github.com/willshersystems/ansible-sshd/issues/32 is the issue raised about the problem and https://github.com/willshersystems/ansible-sshd/pull/34 is the PR with the fix.

```
{% macro render_option(key,value,indent=false) %}
{%   if value is defined %}
{%     if indent == true %}  {% endif %}
{%     if value is sameas true %}
{{ key }} yes
{%     elif value is sameas false %}
{{ key }} no
{%     elif value is string or value is number %}
{{ key }} {{ value }}
{%     else %}
{%       for i in value %}
{{ key }} {{ i }}
{%       endfor %}
{%     endif %}
{%   endif %}
{% endmacro %}
{% macro body_option(key,override) %}
{%   if override is defined %}
{%     set value = override %}
{%   elif sshd[key] is defined %}
{%     set value = sshd[key] %}
{%   elif sshd_defaults[key] is defined and sshd_skip_defaults != true %}
{%     set value = sshd_defaults[key] %}
{%   endif %}
{{ render_option(key,value) -}}
{% endmacro %}
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
