### ISSUE TITLE
Ansible evaluates the {{ ansible_maintained }} as change

### ISSUE THREAD

**Issue by sedrubal** [ansible/ansible#14097]
- Issue Type: Feature Idea
- Ansible Configuration: `-`
- Environment: `fedora:23`
- Ansible Version:

```
ansible 1.9.4
  configured module search path = None
```
- Summary:

A file containing `{{ ansible_maintained }}` will be updated every time even if there were no changes.
- Expected Results:

Ansible should check if there are changes beside the `{{ ansible_maintained }}` tag and then update the file or not.
- Actual Results:

Ansible seems to see the `{{ ansible_maintained }}` tag and thinks there are changes.

**Comment by sedrubal** [comment]
Oh, I'm sorry, sometimes this isn't evaluated as change. Is there a timeout, maybe?

**Comment by ktaragorn** [comment]
@sedrubal you might need to report this one in the core module repository @ https://github.com/ansible/ansible-modules-core . If possible get it fully replicable, that would be very helpful.

**Comment by sedrubal** [comment]
OK thanks.

**Comment by ktaragorn** [comment]
@sedrubal Please do close this one once u open another over at the modules repo

**Comment by sedrubal** [comment]
I close it now because I'm absolutely not sure, if it's really a bug...
