### ISSUE TITLE
service: name=jenkins enabled=yes not working

### ISSUE THREAD

**Issue by psi-4ward** [ansible/ansible#14103]
```
$ ansible ... -m service -a "name=jenkins enabled=yes"

<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant on PORT 2222 TO 127.0.0.1
<127.0.0.1> EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1453719480.5-262397764983596 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1453719480.5-262397764983596 )" )
<127.0.0.1> PUT /tmp/tmpjg8kt1 TO /home/vagrant/.ansible/tmp/ansible-tmp-1453719480.5-262397764983596/service
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-pyplcmqcjuyjamybfagmkplpnnbvnnsc; LANG=de_DE.UTF-8 LC_ALL=de_DE.UTF-8 LC_MESSAGES=de_DE.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1453719480.5-262397764983596/service; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1453719480.5-262397764983596/" > /dev/null 2>&1'"'"''
jenkins | SUCCESS => {
    "changed": false, 
    "enabled": true, 
    "invocation": {
        "module_args": {
            "arguments": "", 
            "enabled": true, 
            "name": "jenkins", 
            "pattern": null, 
            "runlevel": "default", 
            "sleep": null, 
            "state": null
        }, 
        "module_name": "service"
    }, 
    "name": "jenkins"
}
```

but 

```
$ systemctl status jenkins
● jenkins.service - Jenkins
   Loaded: loaded (/etc/systemd/system/jenkins.service; disabled; vendor preset: disabled)
```

So the Service Module does not enable my jenkins.service.
I can enable it using `systemctl enable jenkins` and enabling another Unit works too.

Any hints how to track this bug?

**Comment by chrrrles** [comment]
May you give us more information such as the version of Ansible are you running, and with which platforms?

##### Issue Type:

Can you help us out in labelling this by telling us what kind of ticket this this?  You can say:
- Bug Report
- Feature Idea
- Feature Pull Request
- New Module Pull Request
- Bugfix Pull Request
- Documentation Report
- Docs Pull Request

##### Ansible Version:

Let us know what version of Ansible you are using.  Please supply the verbatim output from running “ansible --version”.  If you're filing a ticket on a version of Ansible which is not the latest, we'd greatly appreciate it if you could retest on the latest version first.  We don't expect you to test against the development branch most of the time, but we may ask for that if you have cycles.  Thanks!

##### Ansible Configuration:

What have you changed about your Ansible installation?  What configuration settings have you changed/added/removed?  Compare your /etc/ansible/ansible.cfg against a clean version from Github and let us know what's different.

##### Environment:

What OS are you running Ansible from and what OS are you managing?  Examples include RHEL 5/6, Centos 5/6, Ubuntu 12.04/13.10, *BSD, Solaris.  If this is a generic feature request or it doesn’t apply, just say “N/A”.  Not all tickets may be about operating system related things and we understand that.

##### Summary:

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.  Thanks!

##### Steps To Reproduce:

If this is a bug ticket, please enter the steps you use to reproduce the problem in the space below.  If this is a feature request, please enter the steps you would use to use the feature.  If an example playbook is useful, please include a short reproducer inline, indented by four spaces.  If a longer one is necessary, linking to one uploaded to gist.github.com would be great.  Much appreciated!

##### Expected Results:

Please enter your expected results in this space.  When running the steps supplied above in the previous section, what did you expect to happen?  If showing example output, please indent your output by four spaces so it will render correctly in GitHub's viewer thingy.

##### Actual Results:

Please enter your actual results in this space.  When running the steps supplied above, what actually happened?  If you are showing example output, please indent your output by four spaces so it will render correctly in GitHub.  Thanks again!

**Comment by psi-4ward** [comment]
- Issue: Bug
- Version: `ansible 2.0.0.2`
- `ansible.cfg`: default from Archlinux Pkg
- Guest: Vagrant Box with CentOS 7

**Reproduce**: Sadly i dont know how.
I have (a simple) Systemd Unit file deployed into `/etc/systemd/system/jenkins.service`

I would expect `systemctl status jenkins` tells me `enabled` after `service name=jenkins enabled=yes`.
As mentioned, it works for other units _and_ i can enable the Jenkins Service manually by invoking `systemctl enable jenkins`.

I know you can't fix a bug which is not reproduceable in your env so perhaps you could give me some hints how to track this issue?

**Comment by psi-4ward** [comment]
I took a deeper look into `service.py`.
The Module searches for init.d scripts first and i had a `/etc/init.d/jenkins` file.
Removed it and the service module enables the systemd unit as expected.

**Comment by chrrrles** [comment]
Thanks @psi-4ward
