### ISSUE TITLE
Bug report. Callbacks print out before PLAY RECAP not after

### ISSUE THREAD

**Issue by luqasz** [ansible/ansible#14114]
Hi

I'd like to report a bug on callbacks behavior.
##### Ansible Version:

ansible 2.0.0.2
##### Ansible Configuration:

callback_plugins = ~/.ansible/plugins/callback_plugins/
##### Environment:

Running on mac osx with python 2.7.11
##### Summary:

Callback output from `v2_playbook_on_stats` is printed before `PLAY RECAP` and not after. I've placed my callback in `~/.ansible/plugins/callback_plugins/` directory. When I move it into virtualenv in `~/.virtualenvs/myansible/lib/python2.7/site-packages/ansible/plugins/callback`, output is printed after `PLAY RECAP`.
To display any information from my cllback I use `self._display.display` method.
##### Steps To Reproduce:

See above
##### Expected Results:

All callbacks output from `v2_playbook_on_stats` should be printed after `PLAY RECAP`

**Comment by bcoca** [comment]
PLAY RECAP is just printed by the default callback when called through v2_playbook_on_stats, I'm not sure if what you are saying is that the stdout plugin should run before any others on every event.

**Comment by luqasz** [comment]
If I only whitelist `callback_whitelist = timer` (which is shipped with ansible) it's output is is printed after `PLAY RECAP`. IMO stdout plugin should always be run first.

**Comment by bcoca** [comment]
from reading the code, this should always be the case, sending events loops over the list of loaded callback plugins, the stdout plugin is always the first on the list. I'll try testing this to see if i can reproduce the issue.

**Comment by luqasz** [comment]
Thanks.

**Comment by bcoca** [comment]
verified, this does seem to be an issue, not sure why as everything gets loaded AFTER the stdout plugin and changing the location should not matter
