### ISSUE TITLE
"SyntaxError: invalid syntax" when running `ansible`

### ISSUE THREAD

**Issue by gebn** [ansible/ansible#14119]
I seem to be coming across a strange error related to the Python version:

```
[kings:~]$ ansible
Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 39, in <module>
    from ansible.errors import AnsibleError, AnsibleOptionsError, AnsibleParserError
  File "/usr/local/lib/python3.2/dist-packages/ansible/errors/__init__.py", line 29, in <module>
    from ansible.utils.unicode import to_unicode, to_str
  File "/usr/local/lib/python3.2/dist-packages/ansible/utils/unicode.py", line 108
    return u''
             ^
SyntaxError: invalid syntax
```

I'm not sure how unicode literals got into a Python 3 file. I'm running Ansible on a Raspberry Pi (Raspbian 7), installed using `pip-3.2 install ansible`.

**Comment by sivel** [comment]
Ansible does not officially support python3 at this time.  There has been some work put into making Ansible support python3, but we are not yet ready to start accepting issues related to python3 incompatibilities.

However, please feel free to provide pull requests to resolve areas of python3 incompatibilities.

For the time being, you should install Ansible using python2/pip2.

**Comment by gebn** [comment]
In that case, might it be worth removing it from the pip3 index to stop others falling into the same trap? I'll look into contributing to Ansible once I've got it up and running!

**Comment by richard-scott** [comment]
I second this motion to remove the package from pip3. 

I've just tried to install it using pip3 as it was listed as a package you could install and I couldn't figure out why it gave so many errors during the install.

Maybe it is also worth noting it on the [documentation ](http://docs.ansible.com/ansible/intro_installation.html#latest-releases-via-pip)that pip3 is not supported

**Comment by bcoca** [comment]
@https://pypi.python.org/pypi/ansible/2.0.0.2 <= its listed as python 2.6 an 2.7 not much more we can do if pip3 ignores this. 

Also docs already state that it requires python2 and does not work in python3 (yet) so that should be enough to infer that the python3 install tool should not be used either.

**Comment by sivel** [comment]
I've checked in with the pypi maintainers, and there is no way of preventing pypi from offering up a package to pip3.
