### ISSUE TITLE
git module fails on updating after a SHA (or tag) checkout

### ISSUE THREAD

**Issue by chris-gilmore** [ansible/ansible#1412]
When using the git module to checkout a SHA or tag release, we are left in a 'detached HEAD' state and therefore not on any branch:
* (no branch)
This works fine.
However, the next time the git module runs, we find that the pull subroutine fails with the following message:
There are no candidates for merging among the refs that you just fetched.
Generally this means that you provided a wildcard refspec which had no
matches on the remote end.

Would it not be sufficient to simply do a 'git fetch' rather than a 'git pull', since the switch_version subroutine does a 'git checkout'?  This would avoid the above error.

**Comment by mpdehaan** [comment]
What do you get for "ansible --version" ?

**Comment by chris-gilmore** [comment]
ansible 0.8

**Comment by sfromm** [comment]
@chris-gilmore What are the options you are providing the git module?

**Comment by sfromm** [comment]
I can replicate the issue.  I'll try to isolate it.

**Comment by chris-gilmore** [comment]
The error occurs after "git pull -u origin".

**Comment by sfromm** [comment]
@chris-gilmore what version of git are you using?

**Comment by chris-gilmore** [comment]
git version 1.7.4.5

**Comment by sfromm** [comment]
Yes, you are using ansible 0.8.  I'm asking about the version of git installed on the target host.

**Comment by chris-gilmore** [comment]
Sorry about my misunderstanding.  I've just edited my last comment.

**Comment by sfromm** [comment]
I have a fix that I'll cleanup and submit this afternoon.

**Comment by chris-gilmore** [comment]
@mpdehaan Can this bug-fix go into ansible 0.8.1?

**Comment by sfromm** [comment]
This seems to work:

```
$ ansible all -i 'testnode,' -m git -a "repo=git://github.com/ansible/ansible.git dest=/tmp/ansible version=HEAD"
testnode | success >> {
    "after": "d585fe8", 
    "before": null, 
    "changed": true
}

$ ansible all -i 'testnode,' -m git -a "repo=git://github.com/ansible/ansible.git dest=/tmp/ansible version=0.7"
testnode | success >> {
    "after": "2bf9a92", 
    "before": "d585fe8", 
    "changed": true
}

$ ansible all -i 'testnode,' -m git -a "repo=git://github.com/ansible/ansible.git dest=/tmp/ansible version=0.8"
testnode | success >> {
    "after": "e072271", 
    "before": "2bf9a92", 
    "changed": true
}

$ ansible all -i 'testnode,' -m git -a "repo=git://github.com/ansible/ansible.git dest=/tmp/ansible version=HEAD"
testnode | success >> {
    "after": "d585fe8", 
    "before": "e072271", 
    "changed": true
}
```

Tested with git 1.7.1, 1.7.4.1, and 1.7.11.7.

**Comment by mpdehaan** [comment]
Should be fixed by above.  Thanks @sfromm!   Let me know if this works for you @chris-gilmore.   Thanks!

**Comment by chris-gilmore** [comment]
@sfromm Is it true that your 'fix' would checkout the HEAD branch from a (no branch) and then checkout the requested version.  If so, this intermediate HEAD branch would change files in the checkout directory in such a way that The User would not like.

Again I ask, would it be possible to replace the 'git pull' with just a 'git fetch' in the pull subroutine?

**Comment by mpdehaan** [comment]
I do not approve of sarcastic quotes, please realize this is a volunteer effort.

**Comment by sfromm** [comment]
Swapping out git-pull for git-fetch is doable.  It just requires vetting all the assumptions in the git module based on git-pull and making sure this still correctly handles previous issues.  I've updated the git module, but need to run more tests before submitting a PR.

**Comment by chris-gilmore** [comment]
Thanks @sfromm .
May I suggest one additional feature?
Some projects have submodules that need to be pulled in.
I believe it would always be safe (even if the project has no submodules) to do the following after the last call to switch_version:
git submodule update --init --recursive
