### ISSUE TITLE
Ansible 2.0.0.2 - Temp directory is not cleaned up properly

### ISSUE THREAD

**Issue by wholroyd** [ansible/ansible#14134]
All the directories within the `remote_tmp` directory are empty. If the files within them aren't required, then the directory shouldn't be either.

<img width="1440" alt="virtualbox_fedora_26_01_2016_13_17_47" src="https://cloud.githubusercontent.com/assets/147990/12590151/70c8d2fa-c42f-11e5-9ed1-f78b75551ee0.png">

**Comment by bcoca** [comment]
hmm, we seem to be good at removing the temp dirs for the module execution, but some other internal stuff that does 'pre checks' seems to not do the same.

**Comment by khalavak** [comment]
I am seeing the same behaviour where `remote_tmp` directory is not cleaned properly  after successful playbook runs. Any idea when this will be fixed?

**Comment by bcoca** [comment]
finally fixed by #15501, should be out in 2.1
