### ISSUE TITLE
Problem with Inventory.HOSTS_PATTERNS_CACHE using API

### ISSUE THREAD

**Issue by micafer** [ansible/ansible#14154]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### Ansible Configuration:

```
[defaults]
hostfile       = /etc/ansible/hosts
become_user      = root
become_method    = sudo
transport      = smart
remote_port    = 22
host_key_checking = False
timeout = 10
[paramiko_connection]
record_host_keys=False
[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=900s
pipelining = True
[accelerate]
```
##### Environment:

Ubuntu 14.04 and Ubuntu 14.04
##### Summary:

I'm calling Ansible from a daemon that calls the Ansible library.
When I make two successive calls to the API to perform a functionality equivalent to ansible-playbook command, in the second call when creating the Inventory object, in particular in “get_hosts” function the variable HOSTS_PATTERNS_CACHE has a the previous pattern_hash (in my case “all”) with the data of the previous call, so I get this error:

```
“no host vars as host is not in inventory: <ip_of_the_previous_call>”
```
##### Steps To Reproduce:

As it is produced calling the API is not easy to reproduce. But mainly you have to call ansible-playbook twice with different hosts in the same execution (not removing variables from memory).
##### Expected Results:

The playbook executed correctly.
##### Actual Results:

The current error is:

```
“no host vars as host is not in inventory: <ip_of_the_first_call>”
```

**Comment by jimi-c** [comment]
This has been corrected in devel and will be included in 2.0.1. The commit responsible for fixing it is 391420d88f7c8dd691833cd0edb1fe4c31b9c191, if you wish to cherry-pick it temporarily.

Thanks!
