### ISSUE TITLE
local_action sudo issue

### ISSUE THREAD

**Issue by wojons** [ansible/ansible#1415]
Hello guys,

When i run a playbook like this

---
- hosts: mongoservers
  user: ec2-user
  sudo: True
  tasks:
  - name: copy mongo repo file
    local_action: shell rsync /home/ansible/files/yum.repos/10gen.repo $inventory_hostname:/tmp/yum.repos.d/10gen.repo

When the local action runs it trys to run sudo on that also and i dont have sudo on my ansible user for good reason :). Is there a flag we can add like. local_sudo: True. I have been reading the code but not feeling like I know it enough o add something like that.

**Comment by mpdehaan** [comment]
Please ask questions on the mailing list vs the ticket queue.

That all being said, in 0.9, you can already set "sudo: False" on a task.   You could also start a new play, which is equivalent.  Up to you.

**Comment by wojons** [comment]
What i am saying that. I want to be able to do sudo on the remote machine and normal user on local machine.

**Comment by mpdehaan** [comment]
Yeah, I'm aware.

You can set sudo: False on individual tasks or start a new play, both will
allow what you want.

local_action /will/ sudo if you have sudo set if it's in the same play.

Some people expect one way, some another, so this is what we are doing.

**Comment by wojons** [comment]
Oh okay will you point me to where in the docs I can find how to sudo for a select action. or maybe there is a list of all the yaml features.

**Comment by mpdehaan** [comment]
The sudo on an individual task isn't documented yet.   Need to fix that.

It is just:

tasks:

```
- action:  foo ....
  sudo: False
```

**Comment by kafecho** [comment]
I read this: http://notepad.bobkmertz.com/2008/04/using-sudo-on-remote-rsync-session-via.html and then wrote my playbook action as: 

 name: Recursively copy the solr folder via rsync to /opt/jetty/
    local_action: shell rsync -av -e "ssh" --rsync-path="sudo rsync" solr [your ansible user here]@192.168.56.101:/opt/jetty/
    sudo: False

This works for me.

**Comment by mpdehaan** [comment]
BTW, you usually want an "${inventory_hostname} in the destination when you are using local_action with rsync.

"local_action" says "on behalf of this host, do this locally", and the hostname variable is how you say where that other host is.

**Comment by kafecho** [comment]
Sorry, you are right, this is a copy and paste typo from my part. I did indeed used the inventory_hostname variable in my yaml file.

The action I actually used is:
- name: Recursively copy the solr folder via rsync to /opt/jetty/
  local_action: shell rsync -av -e "ssh" --rsync-path="sudo rsync" files/solr/
  [ansible user]@$inventory_hostname:/opt/jetty/solr/
    sudo: False
