### ISSUE TITLE
template: src absolute path required in Ansible v2

### ISSUE THREAD

**Issue by nicolas-g** [ansible/ansible#14161]
##### Issue Type:
- Bug Report
##### Ansible Version:

Ansible : 2.0.0.2 
##### Environment:

Controller OS X  :  10.11.3
Target : CentOS 6.7
##### Summary:

Templates stored under our shared role are failing to be deployed from tasks in other roles.

This used to work fine in Ansible 1.9 and it's currently a major problem to migrate because of high number of templates we deploy that way , if we change that in our shared role it means once we update to Ansible v2 it will break the compatibility to run palybooks with version 1. .
##### Steps To Reproduce:

```
# roles/shared/templates/config.conf.j2
```

```
# roles/shared/tasks/deploy.yml

- name: deploy config
  template: src=config.conf.j2 dest=/etc/project/config.conf
```

```
roles/web/taks/main.yml :
- include: ../../shared/tasks/deploy.yml
```
##### Expected Results:

In Ansible 1.9.4 template is deployed successful .
##### Actual Results:

In Ansible 2.0.0.2 this fails :

```
TASK [web : deploy config] ************************
fatal: [server001.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "IOError: [Errno 2] No such file or directory: u'/src/Ansible/config.conf.j2'"}
```

In order for this to work on version 2 I have to change the src path to ../shared/templates/config.conf.j2 but this will break compatibility with Ansible version 1 :

```
# roles/shared/tasks/deploy.yml

- name: deploy config
  template: src=../shared/templates/config.conf.j2 dest=/etc/project/config.conf
```

**Comment by bcoca** [comment]
includes are not 'role aware' so they will only look into 'templates/ subdir' from point of include or from the play.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

As mentioned above includes are not aware of other roles so should not be expected to respect role pathing rules unless invoked from inside a role.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by nicolas-g** [comment]
I'll take this that Ansible version 2 breaks by design the backward compatibility regarding the template path as it was in version 1.9 .

**Comment by bcoca** [comment]
No and yes, 1.9 did some incorrect pathing that was never intended, proper pathing is the following:

  `src=<file>` will search in order:

```
#if in role:
  rolename/templates/<file>
  rolename/tasks/<file>
  rolename/<file>
# always
play_dir/templates/<file>
play_dir/<file>
```

**Comment by nicolas-g** [comment]
thanks for the explanation.

**Comment by fdemmer** [comment]
@bcoca 

can you please clarify, whether templates in subdirectories are supported?

with 1.9 i had this role:

```
- name: configure django secret settings
  template: >
    src="settings/secret.py.j2"
    dest="{{ install_path }}/{{ service_name }}/{{ secret_settings }}"
```

the template is in `rolename/templates/settings/secret.py.j2` so it matches the pattern `rolename/templates/<file>`, but only if `<file>` may contain a relative path.

can i still organize my templates in subdirectories?

**Comment by cubranic** [comment]
@bcoca:

> `src=<file>` will search in order:
> 
> ```
> #if in role:
>   rolename/templates/<file>
>   rolename/tasks/<file>
>   rolename/<file>
> # always
> play_dir/templates/<file>
> play_dir/<file>
> ```

what if `rolename` is actually a dependent of another role, `role1`? It would be useful to include `role1/templates`, etc. in this search path too.

**Comment by bcoca** [comment]
working on making it so, this is what i want it to look like in the end:

```
# if in role:
  for role in roles #ordered from current and goes up the dependency list
    role.name/templates/<file>
    role.name/tasks/<file>
    role.name/<file>
# always
play_dir/templates/<file>
play_dir/<file>
```

**Comment by cubranic** [comment]
That would be exactly what I hoped for, thanks.
