### ISSUE TITLE
Running as a user after running in sudo - fails.

### ISSUE THREAD

**Issue by pkit** [ansible/ansible#1417]
Running without sudo:

$ ansible -i ansible_hosts -u user --private-key=../user.pem test -m ping
192.168.6.101 | FAILED => failed to parse: {"ping": "pong"}

/bin/bash: /tmp/del.log: Permission denied

Running with sudo:

$ ansible -i ansible_hosts -u user --private-key=../user.pem test -s -m shell -a 'ls -al /tmp/del.log'
192.168.6.101 | success | rc=0 >>
-rw-r--r-- 1 root root 0 Oct 23 01:52 /tmp/del.log

As we can see there is indeed /tmp/del.log file with zero length in /tmp, owned by root.

**Comment by pkit** [comment]
Bug is related to commit https://github.com/ansible/ansible/commit/95d90e38e79844de38865d7e3cc64d1fadf1f08a
I suppose the /tmp/del.log was there all the time, but trying to remove it surfaced the bug.

**Comment by mpdehaan** [comment]
Not sure how the second part is related to the changing command, we're not
trying to delete a del.log

I'll recheck the devel branch sudo code attribute handling regardless.

**Comment by mpdehaan** [comment]
Ah, my fault... del.log was left in from debugging ... I was confused since you included it in your ansible command.   There's no need for it and I've replaced it with /dev/null.

Thanks for the heads up, fix pushed
