### ISSUE TITLE
Non-POSIX /bin/sh is not respected since v2.0

### ISSUE THREAD

**Issue by Akint** [ansible/ansible#14176]
Problem description:
Dollar parents ( $(...) ), which aren't supported on non-POSIX shells (for example, Solaris 10's one), have been used in lib/ansible/plugins/shell/sh.py since v2.0. For example, tmp dir is being created as "/export/home/akint/$( echo /export/home/akint/.ansible/tmp/" instead of "/export/home/akint/.ansible/tmp/" because of 'mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1453972288.64-179689601296487 )"' during connection initialization. 

I have found 2 ways it could be fixed:
1. Use backticks ( `...` ) instead of dollar parents:
   
   ``` diff
         diff --git a/lib/ansible/plugins/shell/sh.py b/lib/ansible/plugins/shell/sh.py
         index 8b20338..16b715a 100644
         --- a/lib/ansible/plugins/shell/sh.py
         +++ b/lib/ansible/plugins/shell/sh.py
         @@ -35,8 +35,8 @@ class ShellModule(object):
              _SHELL_REDIRECT_ALLNULL = '> /dev/null 2>&1'
              _SHELL_AND = '&&'
              _SHELL_OR = '||'
         -    _SHELL_SUB_LEFT = '"$('
         -    _SHELL_SUB_RIGHT = ')"'
         +    _SHELL_SUB_LEFT = '"`'
         +    _SHELL_SUB_RIGHT = '`"'
              _SHELL_GROUP_LEFT = '('
              _SHELL_GROUP_RIGHT = ')'
   ```
2. Set "executable = /bin/bash" in ansible.cfg. It starts complaining: "Invalid shell type specified (bash), or the plugin for that shell type is missing.", but can be fixed by copying lib/ansible/plugins/shell/sh.py to lib/ansible/plugins/shell/bash.py

Described clauses have been tested with "ping" module:

```
ansible solaris10-host -m ping -vvvv
```

**Comment by abadger** [comment]
As a temporatry workaround, does setting `executable = /bin/bash` in the config file and 

```
[all:vars]
ansible_shell_type=sh
```

In inventory work?

**Comment by abadger** [comment]
Tested on fedora and centos6 with the following shells: /bin/sh /bin/bash /bin/dash /bin/zsh /bin/ksh /bin/tcsh /bin/csh /bin/fish (should use its own definition of _SHELL_SUB_RIGHT and LEFT).  All worked.  You've tested the change with /bin/sh on Solaris10.  So this seems safe to apply.  Will add it now.

**Comment by Akint** [comment]
Temporary workaround worked.
Anyway, the problem is solved with your commits, thank you!
