### ISSUE TITLE
vim syntax

### ISSUE THREAD

**Issue by akostadinov** [ansible/ansible#14183]
Hello, not sure this is the right place to put such a feature request. But it will be very useful if ansible team could maintain vim syntax `https://github.com/chase/vim-ansible-yaml`. Based on README the author is looking for a maintainer.

**Comment by lystor** [comment]
+1

**Comment by groggemans** [comment]
+1

**Comment by SebastienElet** [comment]
:+1:

**Comment by bcoca** [comment]
So after consulting the rest of the committers,  no one has the expertise nor has expressed the will to maintain this. Also they noted that there are other maintained Ansible Vim plugins available.

For these reasons I'm closing this ticket, sorry.
