### ISSUE TITLE
Strange things with first_available_file part 2

### ISSUE THREAD

**Issue by tonk** [ansible/ansible#1418]
I was trying to reopen #1391 but that doesn't work.

Michael fixed the relative/absolute path in `first_available_file`, but it seems that it looks for the wrong path now

I do this

```
  - name: Deploy postfix main.cf
    template: src=${item} dest=/etc/postfix/main.cf owner=root mode=0440
    first_available_file:
        - main.cf.in=${ansible_hostname}
        - main.cf.in
```

and get 

```
TASK: [Deploy postfix main.cf] ********************* 
fatal: [master] => {'msg': 'unable to process as utf-8: playbooks/postfix/playbooks/postfix/main.cf.in',      failed': True}
fatal: [master] => {'msg': 'unable to process as utf-8: playbooks/postfix/playbooks/postfix/main.cf.in',  'failed': True}

FATAL: all hosts have already failed -- aborting
```

My `main.cf.in` and/or `main.cf.in=${ansible_hostname}` are in directory `/etc/ansible/playbooks/postfix` and the error message shows the `playbooks/postfix` being doubled.

I believe this to be wrong.

Thanks,
    TonK

**Comment by mpdehaan** [comment]
There's already a ticket open to make path_dwim take a list of possible paths.   

The error about 'utf-8' though is the real root error and I'm curious as to why you are getting it.

**Comment by tonk** [comment]
If the `utf-8` error is the root of all my evil I'm curious as well. This because when I specify the absolute path the error goes away.

**Comment by mpdehaan** [comment]
If you want to dig around, the problem is very likely that utils.path_dwim is calling template (which it should) but that is causing problems in this case.
