### ISSUE TITLE
user and groups modules modify in check mode

### ISSUE THREAD

**Issue by avatar4d** [ansible/ansible#14184]
The uid/gid in ansible differed from the one on the remote system. The remote system was changed despite running in check mode.

**Comment by jimi-c** [comment]
Hi @avatar4d, could you please provide more detail to help us reproduce the issue? With which version of Ansible were you running?

**Comment by avatar4d** [comment]
I ran ansible-playbook -C on a playbook that had both user and group
modules. The uid/gid were different in ansible files vs on remote system
and it changed them despite running with -C. I'm running 2.0.0.2 (installed
via pip) on OS X El Capitan. Remote system was FreeBSD 10.2.

Chad

**Comment by Vladimir-csp** [comment]
Confirmed also when running on Ubuntu Trusty. Remote host where the problem appears is FreeBSD.

**Comment by mattclay** [comment]
Confirmed for the user module running on FreeBSD 10.2.

```
# grep test /etc/passwd
test:*:1001:1001:User &:/home/test:/bin/sh
```

```
# ansible localhost -m user -a 'name=test uid=1002' --check
localhost | SUCCESS => {
    "append": false,
    "changed": true,
    "comment": "User &",
    "group": 1001,
    "home": "/home/test",
    "move_home": false,
    "name": "test",
    "shell": "/bin/sh",
    "state": "present",
    "uid": 1002
}
```

```
# grep test /etc/passwd
test:*:1002:1001:User &:/home/test:/bin/sh
```

**Comment by mattclay** [comment]
I'm not seeing any issue with the code or behavior of the group module on FreeBSD. However, the user module will change the uid/gid in check mode.
