### ISSUE TITLE
ansible_user variable is empty during play

### ISSUE THREAD

**Issue by r0bj** [ansible/ansible#14195]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0.2
##### Ansible Configuration:

default
##### Environment:

Managing from: OS X 10.11.3
Managed host: Ubuntu 15.10

On managing host user `rob`:

```
id
uid=501(rob)
```
##### Summary:

Variable `ansible_user` in `None` during play runtime.
The solution is to add `-u` parameter from command line.
##### Steps To Reproduce:

test.yml:

```

---

- name: test
  hosts: all
  tasks:
    - debug: var=ansible_user
```
##### Expected Results:

```
ansible-playbook -i hosts test.yml

PLAY [test] ********************************************************************

TASK [setup] *******************************************************************
ok: [vagrant]

TASK [debug] *******************************************************************
ok: [vagrant] => {
    "ansible_user": "rob"
}
```
##### Actual Results:

```
ansible-playbook -i hosts test.yml

PLAY [test] ********************************************************************

TASK [setup] *******************************************************************
ok: [vagrant]

TASK [debug] *******************************************************************
ok: [vagrant] => {
    "ansible_user": null
}
```

Adding `-u rob` to command line parameter:

```
ansible-playbook -i hosts -u rob test.yml

PLAY [test] ********************************************************************

TASK [setup] *******************************************************************
ok: [vagrant]

TASK [debug] *******************************************************************
ok: [vagrant] => {
    "ansible_user": "rob"
}
```

**Comment by bcoca** [comment]
This is not a bug, the variable reflects if the remote user is set or not in the play.

When calling the connection plugins each one will decide what to do in this case, most of them just use the 'current user executing this process', which is what the ssh command does by default.

**Comment by r0bj** [comment]
Thanks.
So how can I know the current user which was used to ssh login during play?
In ansible 1.9.x variable ansible_ssh_user was containing the current user.

**Comment by bcoca** [comment]
ansible_ssh_user was updated to mirror this behavior (it is in changelog), but it is easy enough to use default to lookup the 'current user' if the variable is none:

`user_used: "{{ansible_user|default(lookup('env', 'USER')) }}"` 

you can also use ansible_ssh_user in that expression

**Comment by r0bj** [comment]
I'v done a test.

test.yml:

```
---
- name: test
  hosts: all
  tasks:
    - debug: var=ansible_user
    - debug: msg={{ ansible_user | default(lookup('env', 'USER')) }}
```

```
ansible-playbook -i hosts test.yml

PLAY [test] ********************************************************************

TASK [setup] *******************************************************************
ok: [vagrant]

TASK [debug] *******************************************************************
ok: [vagrant] => {
    "ansible_user": null
}

TASK [debug] *******************************************************************
ok: [vagrant] => {
    "msg": ""
}
```

This is because variable `ansible_user` is defined but has value `null`.

Do you know matbe any other workaround for that?

**Comment by sivel** [comment]
I think you need to use the 2nd argument for `default` to specify to use pythons truthiness checks:

```
- debug: msg={{ ansible_user | default(lookup('env', 'USER'), True) }}
```

**Comment by einarc** [comment]
@sivel Why do these kind of tickets that are misinterpretations do not end up in the docs? It would save you having to answer the same questions down the line; and most importantly make working with Ansible easier. The documentation could seriously use some more clarifications that are already found in threads like this. Because in many cases it is not clear enough and this is about the 3rd or 4th time that I see the same thing happen.

I mean, this bug is already a dupe.

**Comment by kayrus** [comment]
What if ansible script gets root access using `su`, not `sudo`? I still have to figure out which user is used to connect to server.

**Comment by kayrus** [comment]
`ansible_env.PWD|basename` somehow works in all cases.
