### ISSUE TITLE
user module is not respecting system umask

### ISSUE THREAD

**Issue by karnauskas** [ansible/ansible#14198]
When I'm creating user with Ansible and specifying createhome=yes, home directory is created with different permissions than ones specified by server umask. I don't see how to adjust home directory permissions with same module as well.

**Comment by jimi-c** [comment]
Hi @nkts, could you please provide some examples which help us reproduce this? Knowing which systems and version of Ansible you're running on would be helpful.

**Comment by karnauskas** [comment]
Hah, strange, I have rerun all steps to gather information - can't reproduce problem.
