### ISSUE TITLE
ansible user is not set as user in ssh_config

### ISSUE THREAD

**Issue by Fei-Guang** [ansible/ansible#14203]
```
$cat ~/.ssh/config
Host qa-hlm
   User stack
```

ssh will use stack user to login qa-hlm

```
$ssh qa-hlm
stack@qa-hlm
```

why ansible don't use the user from ssh config ?

```
$ansible-playbook nova.yml
<qa-hlm> ESTABLISH SSH CONNECTION FOR USER: None
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case, ansible never reads .ssh/config, it lets ssh do that and use the user set there.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
