### ISSUE TITLE
Static inventory and host address parsing

### ISSUE THREAD

**Issue by liedekef** [ansible/ansible#14205]
Hi all,

I have an inventory script that gives me something like "hostA+hostB" as a hostname, and my ssh config is like:

```
Host *+*
        ForwardAgent yes
        ProxyCommand ssh -q $(echo %h | sed 's/+[^+]*$//;s/\([^+%%]*\)%%\([^+]*\)$/\2 -l \1/;s/:/ -p /') nc  $(echo %h | sed 's/^.*+//;/:/!s/$/ %p/;s/:/ /')
```

Using this syntax, my inventory script can - based on other info - set a SSH jump host by simply prepending the hostname with the jumphost if need be. This avoids to put in a proxycommand line per host, or per ip-range or any other difficult jumphost-solution I've read.
Now this syntax (hostA+hostB) worked fine in 1.9\* versions of ansible, and still works ok if returned by a inventory script in 2.0. But if I use a static inventory file and put in "hostA+hostB", I get a syntax error saying that the port can't be determined.
So it seems some extra check is done if using static inventory files, which is very confusing.
I've narrowed it down to lib/ansible/parsing/utils/addresses.py , function parse_address. For now I make that function just immediately return:

```
return (address, '22')
```

so now I got my "old" behaviour back for static files ...
Maybe an option could be added to eliminate this check if desired?

**Comment by dagwieers** [comment]
@liedekef It would help if a minimal example is provided that reproduces the ill-behaviour. Since the project has scarce resources (helping with bug triage) any help to make the team more efficient will not only help the project in general, but also increases any chance to have this looked at and fixed :-)

I tried to reproduce your case, and the below information would have helped me to understand and to reproduce it. However it seems to work fine for me with v2.0.0.0, v2.0.0.1 and v2.0.0.2 :-)

**inventory3**:

``` ini
[group]
localhost
localhost+localhost
```

**~/.ssh/config**:

```
Host *+*
        ForwardAgent yes
        ProxyCommand ssh -q $(echo %h | sed 's/+[^+]*$//;s/\([^+%%]*\)%%\([^+]*\)$/\2 -l \1/;s/:/ -p /') nc  $(echo %h | sed 's/^.*+//;/:/!s/$/ %p/;s/:/ /')
```

**test67.yml**:

``` yaml
- hosts: group
  tasks:
  - command: echo test
```

Output on **Ansible v1.9.4**:

```
[dag@moria ansible.testing]$ ansible-playbook -i inventory3 -l group test67.yml

PLAY [group] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]
ok: [localhost+localhost]

TASK: [command echo test] ***************************************************** 
changed: [localhost+localhost]
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
localhost+localhost        : ok=2    changed=1    unreachable=0    failed=0   
```

Output on **Ansible v2.0.0.2**:

```
[dag@moria ansible.testing]$ ansible-playbook -i inventory3 -l group test67.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]
ok: [localhost+localhost]

TASK [command] *****************************************************************
changed: [localhost]
changed: [localhost+localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
localhost+localhost        : ok=2    changed=1    unreachable=0    failed=0   
```

**Comment by dagwieers** [comment]
@liedekef I think you can also simplify your **ProxyCommand** rule with the below:

```
ProxyCommand ssh -q $(H=%h; echo "${H%%+*}") nc $(H=%h; echo "${H#*+} %p")
```
or even better:
```
ProxyCommand ssh -q -oLogLevel=ERROR $(H=%h; echo "${H%%+*}") nc $(H=%h; echo "${H#*+} %p")
```

Since you're using Bash syntax already, you can take advantage of **Parameter Expansion**. Unfortunately it means you need to first assign it to a Bash variable, but at least you avoid forking.

**Comment by liedekef** [comment]
I confirm that it works ok in the latest release, so I'll close this.

**Comment by dagwieers** [comment]
Thanks !
