### ISSUE TITLE
Conditional role inclusion expands the passed variables even if the role is being skipped

### ISSUE THREAD

**Issue by romanrev** [ansible/ansible#14201]
Issue Type: Bug Report
Ansible Version: 2.0.0.1
Ansible Configuration: nothing changed
Environment: OS X 10.11.2
Summary:

Conditional role inclusion in a play still tries to expand variables passed onto this role, even if the role is being skipped

Steps To Reproduce:

Given a play of this kind:

```
...
  roles:
    - { role: some_role,
        some_var: "{{ some_value }}",
        when: some_value is defined,
        tags: [ tag1, tag2 ]
      }
```

when the `some_value` variable is undefined, one gets an error `ERROR! ERROR! 'some_value' is undefined` even though the output clearly shows that the role is being skipped:

```
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
```

Expected Results:

The role should be skipped without the error, as was the behaviour of Ansible 1.9.4

Actual Results:

```
...
TASK [some_role : description of first task in that role] **
task path: /Users/some_user/some/path/to/roles/some_role/tasks/main.yml:2
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
ERROR! ERROR! 'some_value' is undefined
```

**Comment by bcoca** [comment]
this is not a bug, role imports cannot be skipped, so the call needs to be valid.

the when: condition is applied to all tasks in a role, not to the action of importing the role

**Comment by romanrev** [comment]
@bcoca could you please explain why it worked differently in Ansible 1.9.4?

**Comment by hloeffler** [comment]
i think breaking 1.9.4 is a bug
closing is fast here sometimes

**Comment by romanrev** [comment]
@bcoca Please find below the output from the Ansible 1.9.4 with the following input:

```
cat > undefined_var_test_role_inclusion.yml <<EOF
---
- hosts: all
  connection: local
  gather_facts: false

  roles:

  - { role: some_role,
      some_var: "{{ some_value }}",
      when: some_value is defined,
      tags: [ tag1, tag2 ]
    }
EOF
mkdir -p roles/some_role/tasks
cat > roles/some_role/tasks/main.yml <<EOF
---
- name: reference the some_var variable
  local_action: >
    shell
    echo {{ some_var }}

- name: reference the some_var variable in a loop
  local_action: >
    shell
    echo {{ item }}
  with_items: some_var

- debug: var=some_result
EOF

$ ansible-playbook -i localhost, ./undefined_var_test_role_inclusion.yml -vvv

PLAY [all] ********************************************************************

TASK: [some_role | reference the some_var variable] ***************************
skipping: [localhost]

TASK: [some_role | reference the some_var variable in a loop] *****************
skipping: [localhost] => (item=some_var)

TASK: [some_role | debug var=some_result] *************************************
skipping: [localhost]

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

**Comment by romanrev** [comment]
Now with ansible-playbook from the develop branch:

```
$ ansible-playbook --version
ansible-playbook 2.1.0 (devel a584ab3420) last updated 2016/02/02 18:36:05 (GMT +1100)
  lib/ansible/modules/core: (detached HEAD a19fa6ba48) last updated 2015/04/25 10:47:42 (GMT +1100)
  lib/ansible/modules/extras: (detached HEAD df7fcc90d9) last updated 2015/04/25 10:47:42 (GMT +1100)
  config file =
  configured module search path = Default w/o overrides
```

I get this:

```
No config file found; using defaults
1 plays in ./undefined_var_test_role_inclusion.yml

PLAY ***************************************************************************

TASK [some_role : reference the some_var variable] *****************************
task path: /Users/roman/Dev/ansible-bugs/roles/some_role/tasks/main.yml:2
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks
 so that the environment value uses the full variable syntax ('{{some_var}}').
This feature will be removed in a future release. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
ERROR! 'some_value' is undefined
```

And my apologies, I have not explicitly stated in my original bug report _how_ I am referencing the assigned variable:
It appears that when the variable is referenced no in a loop `with_items`, the task is ignored (1st task), while in the second task - when the variable is referenced in a loop `with_items`, the task breaks (2nd task)

@bcoca could you please reopen the issue? Or alternatively I can file another one with proper description

**Comment by bcoca** [comment]
It did not work in 1.9, the errors were just ignored, which lead to unexpected and undefined behavior.

2.0 is much more strict about these things and will error out when the variables are undefined, keywords are misspelled or duplicated. The playbooks 'ran' in 1.9 but did not really 'work' as intended, so we do not consider this a breakage as we are now reporting the errors correctly.

You can use `|default([])`  in with_items should avoid the undefined error and still skip the task.

**Comment by romanrev** [comment]
@bcoca I still consider it a bug - that Ansible 2.x applies the "when variable is defined" condition only to the tasks which do not use the `with_items` loop. Even if I add an explicit "when defined" condition to the above role:

```
- name: reference the some_var variable in a loop
  local_action: >
    shell
    echo {{ item }}
  with_items: some_var
  when: some_var is defined
```

it still errors out. However, if I use the above task as a stand-alone task in the playbook, Ansible 2.x happily ignores the task.
To me, this looks like an inconsistency and a bug: degradation from the previous version behaviour which was correct.

Please reconsider your decision to qualify that as a "feature".
What you proposed is a workaround and the logic of using a default filter is inherently incorrect in my case: the list should not be empty.

**Comment by bcoca** [comment]
the when: is applied to ALL tasks, the issue here is that a previously ignored Exception/error was being lost and now it is reported. 

`when` and `with_` have not changed on how they work in this case, error reporting has changed to actually report the error. Other things that 'ran' unreported until this fix were misspelled directives or duplicate directives so this:

for example:

```
- name: stuff
  shell: echo hi
  when: condition is defined
  when: condition is not defined
```

the 1st when was ignored as only 1 entry is possible, 1.9 'runs' this silently ignoring the error and the user gets an unexpected result. Many people hit these problems `wehn:` vs `when:` would also run in 1.9 but now offer an error in 2.0.

**Comment by bcoca** [comment]
Also, if default([]) is 'incorrect' in your case, then the when condition is also incorrect.

**Comment by romanrev** [comment]
@bcoca you have still not explained why when the `some_var` is undefined the task

```
- name: reference the some_var variable in a loop
  local_action: >
    shell
    echo {{ item }}
  with_items: some_var
  when: some_var is defined
```

it is ignored in a play however is being reported as an error in a role.
It's good that you have fixed the bug in error reporting that you have just outlined, however another bug seems to be not fixed.

**Comment by romanrev** [comment]
> Also, if default([]) is 'incorrect' in your case, then the when condition is also incorrect.

No, that's not true. The whole role should be ignored in case the `some_var` is undefined. However, if it is defined, it can't be an empty list.

**Comment by sivel** [comment]
`when` statements are only ever applied to tasks.  When you specify a `when` statement on a role, Ansible is merging the `when` statement down onto each individual task.

Another thing to note is that `when` statements are interpreted for each iteration of a `with_` loop, so effectively `when` statements are evaluated after `with_` loops.  As a result, if a `with_` loop such as `witth_items` tries to loop over an undefined variable, you will run into the error you have described.

You will need to ensure that all `when` statements provided to a `role` will work on all tasks of the role, including those that have `with_items` loops.

The basic idea is that you should always ensure that variables you may loop over, are at least an empty list, as opposed to being undefined.  This was the reason for the use of the `default` filter, by causing the default filter make an item that should be a list, into at minimum an empty list.

An empty list will satisfy `with_items` but will prevent the task from running, due having no elements to loop over.

**Comment by romanrev** [comment]
@sivel: I get everything what you are saying, but you have also not explained the reason behind the inconsistency I reported above (https://github.com/ansible/ansible/issues/14201#issuecomment-179521835)

Ansible 2.x **does not produce error** on the task with the `with_items` loop with `when: some_var is defined` condition when it is used _in a play_, however it does produce an error when that task is used in a role.

Just to reiterate and make it as possibly clear as I can:

My main point is that Ansible 2.x does not error when the above mentioned task is being used in a play, but does error when the task is used in a role. It should either:
- emit an error ​_all the time_​ regardless of where the task is, and then one can use bold statements such as “when using `with_items` loop please make sure to define a variable that is used in the loop, regardless of the `when:` condition or it will error!”, or
- not emit an error in case the `when: some_var is defined` is supplied in a task with  a `with_items: some_var` loop - **regardless** of whether the task is in a role or a play

**Comment by leoluk** [comment]
@bcoca How to conditionally skip role imports, then?

I have some roles that pull in a number of dependencies. I need a way to skip these.

**Comment by romanrev** [comment]
@leoluk since this issue was not reopened, a new issue #14383 has been created to address this and there seems to be a fix already pushed to the newest version
