### ISSUE TITLE
ERROR! Syntax Error while loading YAML.

### ISSUE THREAD

**Issue by EricWang93** [ansible/ansible#14204]
Ansible tool execute YAML script
there is my code and when I execute it, the error message is prompted:"ERROR! Syntax Error while loading YAML."

```

---
- hosts: localhost
connection: local
user:root
sudo:yes
tasks:
- name: Run the shell script
shell: Desktop/test.sh run 
and I have no idea where the error is it... could anyone help me?
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/Users/appledev118/Desktop/work/first-playbook.yml': line 3, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- hosts: localhost
connection: local
^ here
```

**Comment by pako-pl** [comment]
There's no indentation (whitespace) before your properties. See for example:

http://ess.khhq.net/wiki/YAML_Tutorial

**Comment by EricWang93** [comment]
@pako-pl thanks, this is the first I used ansible, and it is solved.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by asadrao11** [comment]
Try This.
--- 
- 
  connection: "local user:root sudo:yes"
  hosts: localhost
  tasks: 
    - 
      name: "Run the shell script"
      shell: "Desktop/test.sh run"

**Comment by asadrao11** [comment]
--- 
- 
  connection: "local user:root sudo:yes"
  hosts: localhost
  tasks: 
    - 
      name: "Run the shell script"
      shell: "Desktop/test.sh run"

**Comment by huiminzeng** [comment]
hello everyone! I just got the same issue. But the solutions are not working for me. Here is my playbook.
<img width="157" alt="playbook" src="https://user-images.githubusercontent.com/38716719/39690503-a8ae660e-51da-11e8-99b7-73322333a7b4.PNG">
If i add # to all the lines of second task (rocketchat installation), the first task runs just fine. So, basically, it is due to the docker_service part, right? Could you please help me? Thx!

**Comment by chethansgowda** [comment]
Hi All, I am new to ansible and learning on my own. I encountered the same issue. as "ERROR! Syntax Error while loading YAML." 
My  playbook looks like this.  I am not able to run this please help

**Comment by chethansgowda** [comment]
my playbook is not attached in the above comment. It looks like this
 -name: configuring Nginx
  hosts: all
  tasks:
          -name: install Nginx
           apt: name=nginx state=latest
  tasks:
          -name: Ensure Nginx is running
           service:
            name: nginx
            state: started
