### ISSUE TITLE
Need to add a ansible version lock feature

### ISSUE THREAD

**Issue by zz** [ansible/ansible#14200]
When I upgrade to Ansible 2.0, I found have some bug, such as can't access "ec2_tag_" var in template moudle. So I think add to version lock to playbook is a good idea, this will be more safe for production envrironments and CI environments,  such as

```
- hosts: all
  ansible_version: 
  - 1.9.3
  - 1.9.4
```

**Comment by zz** [comment]
If don't use the match version, playbook will don't run.

**Comment by bcoca** [comment]
you can create an assert task that does this already:

```
- assert:
   that:   ansible_version.full|version_compare('1.9', 'eq', strict=False)
```

or 

```
- fail:
  when: ansible_version.full not in ['1.9.3', '1.9.4']
```

**Comment by zz** [comment]
@bcoca Cool, but I think also need to display a user friendly message for end user, such as  junior sysadmin or QA team. and the assert task will run for each host and display the fail message for all hosts.

**Comment by bcoca** [comment]
fail has a msg= option for just that

**Comment by zz** [comment]
but if you have 1000 servers to run, need to check 1000 times? and output 1000 error messages.

**Comment by hloeffler** [comment]
run_once ?

**Comment by zz** [comment]
I still think also need a standard method to do this for production environment. That's right?

**Comment by bcoca** [comment]
that will work in production, not sure what else you are looking for.

**Comment by solojavier** [comment]
I think this issue can be closed since the `assert` or `fail` already does the expected functionality...

**Comment by resmo** [comment]
closing (functionality already exists)
