### ISSUE TITLE
Include of handlers does nothing

### ISSUE THREAD

**Issue by h0nIg** [ansible/ansible#14209]
issue https://github.com/ansible/ansible/issues/11694 was fixed but its not working with current 2.0.2

**Comment by bcoca** [comment]
so, there is no 2.0.2 version (2.0.1 is in release candidate), I'm guessing you mrean 2.0.0.2 and that was released BEFORE the ticket was fixed, so please check against devel or the release candidate and reopen if it is still an issue.
