### ISSUE TITLE
$last_result incorrectly documented as part of 0.8

### ISSUE THREAD

**Issue by mkmik** [ansible/ansible#1420]
The documentation says that there is a special variable `$last_result` (available from 0.8).

The only mention of the string last_result in the release-0.8 branch is in the `./docsite/rst/playbooks2.rst` file.

However, it seems that this feature was superseded by the ability to register the result into a variable
(05a128c2be)

**Comment by mpdehaan** [comment]
Nice catch.

**Comment by mpdehaan** [comment]
How about sending me a patch to the rst file to remove the reference?

**Comment by nigelm** [comment]
I noticed this around the same time... see pull requst
https://github.com/ansible/ansible/pull/1429
