### ISSUE TITLE
hostvars is "empty-ish"

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#1424]
ansible 0.8 here.

The following template works in a playbook with up to about 175 hosts:

``` jinja2
{% for k, v in hostvars.iteritems() -%}

1. {{ hostvars[k]['ansible_default_ipv4']['address'] }}
2. key = {{ k }}
3. ansible_hostname = {{ v['ansible_hostname'] }}

4. {{ v | to_json }}

{% endfor %}
```

Above that number of hosts, the playbook fails for _all_ nodes with the following error:

```
fatal: [www.example.net] => {'msg': "'dict object' has no attribute 'ansible_default_ipv4'", 'failed': True}
```

If I remove the line marked `1`  in the template, leaving everything else in, the template is correctly executed. The `| to_json` call also shows me, that the attribute I'm wanting actually is in the JSON:

``` json
4. {"ansible_product_serial": "NA", "ansible_form_factor": "Rack Mount Chassis",
 "ansible_product_version": "NA", "ansible_product_uuid": "NA", "module_setup": true, "ansible_distribution_version": "11", "ansible_processor_cores": 2, "ansible_bios_version": "P51", "ansible_processor": ["Intel(R) Xeon(TM) CPU 3.20GHz", "Intel(R) Xeon(TM) CPU 3.20GHz", "Intel(R) Xeon(TM) CPU 3.20GHz", "Intel(R) Xeon(TM) CPU 3.20GHz"], "ansible_lo": {"device": "lo", "macaddress": "00:00:00:00:00:00", "type": "loopback", "ipv4": {"netmask": "255.0.0.0", "network": "127.0.0.0", "address": "127.0.0.1"}, "mtu": "16436"}, "ansible_memtotal_mb": 3897, "ansible_architecture": "x86_64", "ansible_default_ipv4": {"macaddress": "00:00:00:61:0a:97", "network": "192.168.20.0", "mtu": "1500", "alias": "bond0", "netmask": "255.255.254.0", "address": "192.168.21.172", "interface": "bond0", "type": "ether", "gateway": "192.168.20.1"}, "ansible_swapfree_mb": 1026,
```

Ticket opened after discussing with @dhozac

**Comment by mpdehaan** [comment]
Assume one of you is working on this?

**Comment by jpmens** [comment]
After talking with @dhozac about this, I've completed a run of 1,000 hosts using above template without errors on my workstation, running `ansible 0.9 (devel 41b012f92e) last updated 2012/10/25 15:58:10 (GMT +200)`.

In other words: this issue manifests itself either only on `0.8` (which we can probably live with) or it's platform-specific.

Closing for now.

**Comment by mpdehaan** [comment]
ok, the way 0.8 and prior pass Runner around _could_ be it, seems like it's gone now, so that's good.  Thanks for the heads up.
