### ISSUE TITLE
No handlers could be found for logger "paramiko.transport"

### ISSUE THREAD

**Issue by groggemans** [ansible/ansible#14247]
When I try to use paramiko for the ssh connection to a router I get the following error and ansible just hangs.

> No handlers could be found for logger "paramiko.transport"

 In Ansible 1.9.4 this worked just fine, after updating to ansible 2+ (2.0.0.2  pip and 2.1.0 devel checkout) i got this error.

Using `-vvvv` isn't showing anything useful either.

`ansible router -m raw -a "system clock print"`

> Loaded callback minimal of type stdout, v2.0
> <192.168.10.1> ESTABLISH CONNECTION FOR USER: management on PORT 22 TO 192.168.10.1
> <192.168.10.1> EXEC system clock print
> No handlers could be found for logger "paramiko.transport"

The router runs RouterOS and the `system clock print` command just prints the time (debugging).
Using password or key doesn't seem to make a difference.

This is the same error as in issue #13721, but I can ssh into the host just fine. I can also run the command without paramiko but the `-tt` option doesn't work on RouterOS (connection doesn't close, that's why I use paramiko).

**Comment by groggemans** [comment]
There is also no way to disable pseudo tty allocation (`-tt`) using ansible variables. `ansible_ssh_extra_args` is inserted before `-tt` so overwriting it with `-T` when using openssh is also not possible.

Even when altering the ssh args in the ansible.cfg the `-tt` option is added automaticly.
(This was possible before v2.0 if I remember correctly, I used it to circumvent an earlier paramiko problem)

**Comment by bcoca** [comment]
the `No handlers could be found for logger "paramiko.transport`' is just a warning and can be ignored, can you strace the process to figure out what it is stuck on? does the ssh transport work?

**Comment by groggemans** [comment]
I forgot to try to quit the connection manually. The following did work;

 `ansible router -m raw -a "system clock print; quit"` 
(`quit` is the same as `exit` on a normal *nix OS)

It prints the output of the command but also the word "interrupted". So connecting isn't the problem, it seems closing the connection is.

This works both using paramiko and openssh. Maybe the problem is RouterOS? Although the problem only arises in ansible 2+.

strace gave me this (only last few lines, let me know if you need more);

```
stat("/home/groggemans/ansible/lib/ansible/plugins/action/async.py", {st_mode=S_IFREG|0664, st_size=3337, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/raw.pyc", {st_mode=S_IFREG|0664, st_size=1248, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/normal.py", {st_mode=S_IFREG|0664, st_size=1774, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/unarchive.py", {st_mode=S_IFREG|0664, st_size=4317, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/copy.py", {st_mode=S_IFREG|0664, st_size=13475, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/add_host.py", {st_mode=S_IFREG|0664, st_size=3011, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/assemble.py", {st_mode=S_IFREG|0664, st_size=5765, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/fail.py", {st_mode=S_IFREG|0664, st_size=1391, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/assert.py", {st_mode=S_IFREG|0664, st_size=2472, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/set_fact.py", {st_mode=S_IFREG|0664, st_size=1914, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/script.py", {st_mode=S_IFREG|0664, st_size=4261, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/pause.py", {st_mode=S_IFREG|0664, st_size=6707, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/raw.py", {st_mode=S_IFREG|0664, st_size=1708, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/debug.py", {st_mode=S_IFREG|0664, st_size=2562, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/package.py", {st_mode=S_IFREG|0664, st_size=2611, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/__init__.py", {st_mode=S_IFREG|0664, st_size=27761, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/win_template.py", {st_mode=S_IFREG|0664, st_size=1169, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/include_vars.py", {st_mode=S_IFREG|0664, st_size=2027, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/fetch.py", {st_mode=S_IFREG|0664, st_size=8449, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/win_copy.py", {st_mode=S_IFREG|0664, st_size=1153, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/template.py", {st_mode=S_IFREG|0664, st_size=8561, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/group_by.py", {st_mode=S_IFREG|0664, st_size=1556, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/synchronize.py", {st_mode=S_IFREG|0664, st_size=10841, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/patch.py", {st_mode=S_IFREG|0664, st_size=2563, ...}) = 0
stat("/home/groggemans/ansible/lib/ansible/plugins/action/__init__.pyc", {st_mode=S_IFREG|0664, st_size=20255, ...}) = 0
poll([{fd=3, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
open("/dev/urandom", O_RDONLY|O_CLOEXEC) = 10
fcntl(10, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
fcntl(10, F_SETFD, FD_CLOEXEC)          = 0
getuid()                                = 1000
getppid()                               = 8205
read(10, "\362\265-\242\371\307\177\214\341\6\0\250\336ji]", 16) = 16
close(10)                               = 0
gettid()                                = 8208
open("/home/groggemans/ansible/lib/ansible/plugins/action/raw.py", O_RDONLY) = 10
fstat(10, {st_mode=S_IFREG|0664, st_size=1708, ...}) = 0
fstat(10, {st_mode=S_IFREG|0664, st_size=1708, ...}) = 0
open("/home/groggemans/ansible/lib/ansible/plugins/action/raw.pyc", O_RDONLY) = 12
fstat(12, {st_mode=S_IFREG|0664, st_size=1248, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3d914c8000
read(12, "\3\363\r\n\320\343\246Vc\0\0\0\0\0\0\0\0\3\0\0\0@`\1\0sL\0\0\0d\0"..., 4096) = 1248
fstat(12, {st_mode=S_IFREG|0664, st_size=1248, ...}) = 0
read(12, "", 4096)                      = 0
close(12)                               = 0
munmap(0x7f3d914c8000, 4096)            = 0
close(10)                               = 0
stat("hosts", {st_mode=S_IFREG|0664, st_size=437, ...}) = 0
stat("hosts", {st_mode=S_IFREG|0664, st_size=437, ...}) = 0
getcwd("/home/groggemans/workdir/lab001/ansible-old", 1024) = 44
stat("hosts", {st_mode=S_IFREG|0664, st_size=437, ...}) = 0
dup(0)                                  = 10
fstat(10, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 3), ...}) = 0
fcntl(10, F_GETFL)                      = 0x8002 (flags O_RDWR|O_LARGEFILE)
wait4(8213, 0x7ffc8dfe437c, WNOHANG, NULL) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f3d914b39d0) = 8214
select(0, NULL, NULL, NULL, {0, 100})   = 0 (Timeout)
poll([{fd=3, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
poll([{fd=3, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 100})   = 0 (Timeout)
```

Than the poll/select functions keep going forever.
So I assume the router keeps the connection open and Ansible just keeps polling the child process to see if it finished yet? Using openssh it also hangs on a similar clone/select/poll sequence.

I know that using openssh this is due to the fact it's using pseudo-tty allocation (tested with manual ssh command, and RouterOS docs confirm it's not supported). Could it be that since 2.0+ the paramiko ssh parameters changed and something similar now also happens when using paramiko?

**Comment by bcoca** [comment]
yes, it is probably due to changes in the connection plugins, I'll download and setup a copy of routerOS to try to debug this.

**Comment by groggemans** [comment]
Great! You can always let me know if I need to test something on the the hardware (MIPS architecture).

**Comment by bcoca** [comment]
hmm, does not seem like i can debug this as it requires me buying the routerOS ....

**Comment by bcoca** [comment]
@groggemans can you test with current devel? we have fixed a few issues with shells that might have cause this issue you see.

**Comment by groggemans** [comment]
```
ansible 2.1.0 (devel 5cd3f71792) last updated 2016/02/02 22:25:38 (GMT +200)
lib/ansible/modules/core: (detached HEAD 93d02189f6) last updated 2016/02/02 22:26:27 (GMT +200)
lib/ansible/modules/extras: (detached HEAD fff5ae6994) last updated 2016/02/02 22:26:27 (GMT +200)
config file = /home/groggemans/workdir/lab001/ansible-old/ansible.cfg
configured module search path = Default w/o overrides
```

@bcoca still exactly the same issue and the same strace output.

I did run this on a system that also has ansible 2.0.0.2 installed using pip. Can this intervene? Or is it safe to assume the source setup script masks this installation completely?

**Comment by bcoca** [comment]
The source setup should mask other versions. This looks like a problem with the ssh connection getting stuck. It is probably not a hung/blocked process as timeouts would be hit as no keepalive communication would happen.

Sadly w/o being able to test directly I can only speculate. Does the ssh transport not work at all?

**Comment by groggemans** [comment]
It goes wrong after the connection is made and the remote command is executed. If I append `quit` (equal to `exit` on normal *nix OS) to the remote command, ansible does print the output of the executed command, and reports the normal program flow was interrupted.

I can't test until Monday, but I'll have a look at the ansible source code and see if I can figure it out myself. I'll get in touch through IRC if I have a question or run into trouble!

**Comment by groggemans** [comment]
I found the problem!

In the past a PTY was only used when the command needed to be executed as root. An [if statement](https://github.com/ansible/ansible/blob/stable-1.9/lib/ansible/runner/connection_plugins/paramiko_ssh.py#L215) prevented the code from always using it. Since v2+ a PTY is always used unless specifically disabled in the ansible.cfg [(here)](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/paramiko_ssh.py#L218).

Because RouterOS doesn't properly support PTY's the connection stays open/active and ansible hangs.

This means there is no real bug (using a PTY by default is good) and there is a config option to disable the use of the PTY.

I do however want to request to add the same option for OpenSSH as this is the only reason OpenSSH can't be used with RouterOS and it is a lot faster then paramiko. Should I make a new issue for this?

**Comment by bcoca** [comment]
yes, open a ticket for that, currently if you enable pipelining it will not create a tty, but I'm not sure we need one aside from dealing with privilege escalation and passwords.

**Comment by bcoca** [comment]
closing this as per above.
