### ISSUE TITLE
How do I access facts in custom plugins?

### ISSUE THREAD

**Issue by moon-musick** [ansible/ansible#14256]
I'd like to use a fact's value in a custom filter plugin without the need to provide it explicitly as an argument.

What do I need to do to get the value inside of a plugin (i.e. in the body of a custom plugin function) ? I haven't been able to find anything on topic in official documentation.

**Comment by sivel** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
