### ISSUE TITLE
ansible-playbook 2.0.0.2 fails to load /etc/ansible/ansible.cfg 

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#14269]
After updating ansible, the ansible-playbook command no longer finds the default configuration file.  

There is no ansible.cfg in my current directory, nor in my home directory, nor is there an ANSIBLE_CONFIG environment variable; so, it should be using /etc/ansible/ansible.cfg 

I'm running this on OSX El Capitan.   

```
$ ls /etc/ansible
ansible.cfg 

$ ansible-playbook --version
ansible-playbook 2.0.0.2
  config file = 
  configured module search path = Default w/o overrides
```

**Comment by bcoca** [comment]
run with -v , it should show which config it found.

**Comment by ghost** [comment]
The --version switch also shows the config: **config file = [blank]**

The -v switch on a playbook run says: *_No config file found; using defaults"_

Yet, it's definitely there: /etc/ansible/ansible.cfg 

I can copy that config to my working directory and it gets picked up just fine.

**Comment by dagwieers** [comment]
What are the permissions/ownership of `/etc/ansible` and `/etc/ansible/ansible.cfg` ?
Can you also try doing: **strace -f -e file ansible-playbook --version 2>&1 | grep ansible.cfg** ?

For me this returns:

```
[dag@moria ansible.dag]$ strace -f -e file ansible-playbook --version 2>&1 | grep ansible.cfg
stat("/home/dag/home-made/ansible.dag/ansible.cfg", {st_mode=S_IFREG|0664, st_size=249, ...}) = 0
open("/home/dag/home-made/ansible.dag/ansible.cfg", O_RDONLY) = 5
  config file = /home/dag/home-made/ansible.dag/ansible.cfg

[dag@moria ansible.dag]$ rm -f ansible.cfg 

[dag@moria ansible.dag]$ strace -f -e file ansible-playbook --version 2>&1 | grep ansible.cfg
stat("/home/dag/home-made/ansible.dag/ansible.cfg", 0x7ffefd9b5500) = -1 ENOENT (No such file or directory)
stat("/home/dag/.ansible.cfg", 0x7ffefd9b5500) = -1 ENOENT (No such file or directory)
stat("/etc/ansible/ansible.cfg", {st_mode=S_IFREG|0644, st_size=10301, ...}) = 0
open("/etc/ansible/ansible.cfg", O_RDONLY) = 5
  config file = /etc/ansible/ansible.cfg
```

PS I am also running v2.0.0.2 in this example.

**Comment by ghost** [comment]
They were root:wheel but had the same thought earlier and changed to my own username:group.  The config file is read/write for anybody (no execute except the folder itself).  Unfortunately there's no strace command on OSX.

**Comment by dagwieers** [comment]
Please try: **dtruss -f ansible-playbook --version 2>&1 | grep ansible.cfg** (or something similar) instead.

You may want to try: **dtruss -f -t stat ansible-playbook --version 2>&1 | grep ansible.cfg** and 
**dtruss -f -t open ansible-playbook --version 2>&1 | grep ansible.cfg** to see if that helps as well.

See: https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/dtruss.1m.html

**Comment by ghost** [comment]
I have to sudo dtruss (no surprise) but then it complains about dtrace.  In any event, the work-around is to put the ansible.cfg in your working directory if you encounter this.  

`"dtrace cannot control executables signed with restricted entitlements".`

**Comment by dagwieers** [comment]
It would have been nice to understand why `/etc/ansible/ansible.cfg` cannot be used on your system.
And then fix it. Oh well...

**Comment by sivel** [comment]
How was Ansible installed?  I only ask as if it was installed via homebrew (which we don't recommend) because they patch Ansible to change all references of `/etc/ansible` to use `/usr/local/etc/ansible`

**Comment by ghost** [comment]
Yes, it was brewed: ansible-2.0.0.2.el_capitan.bottle.tar.gz

There is no /usr/local/etc/ansible however.  No worries, we'll be installing this on more Macs so if it happens again I'll actually  debug the thing to completion.

**Comment by ghost** [comment]
It's defaulting to /usr/local/etc/ansbile rather than /etc/ansible, as sivel pointed out.

**Comment by sivel** [comment]
Just to mention this here also, brew is not a recommended installation method for Ansible.  Installing via pip either with the system Python (preferred) or with homebrew installed Python is the recommended way.
