### ISSUE TITLE
module (config_template) is missing interpreter line

### ISSUE THREAD

**Issue by jfcoz** [ansible/ansible#14266]
When using ceph-ansible with the devel or stable-2.0 branch of ansible I get : 

```
TASK [ceph-common : generate ceph configuration file] **************************
fatal: [mon1.ceph.pp.sd.lbn.fr]: FAILED! => {"failed": true, "msg": "module (config_template) is missing interpreter line"}
fatal: [mon2.ceph.pp.sd.lbn.fr]: FAILED! => {"failed": true, "msg": "module (config_template) is missing interpreter line"}
fatal: [mon3.ceph.pp.sd.lbn.fr]: FAILED! => {"failed": true, "msg": "module (config_template) is missing interpreter line"}
```

In config_template there is not shebang but : 

`# this is a virtual module that is entirely implemented server sid`

Do you have an idea ?
Thanks

**Comment by bcoca** [comment]
config_template? that is not an ansible module

**Comment by sivel** [comment]
This sounds like an issue should be opened with https://github.com/ceph/ceph-ansible

There is the potential that although you are pulling in their 'library' you are not properly configured to pull in their `action_plugins`

**Comment by jfcoz** [comment]
Thank you, I just was in the bad directory when launching ansible
