### ISSUE TITLE
Retemplate on with_item loop broken in 2.0

### ISSUE THREAD

**Issue by k0ste** [ansible/ansible#14286]
Source of playbook:

``` yaml

---
- name: jedi
  gather_facts: false
  no_log: false
  hosts: 127.0.0.1
  vars:
  - jedi_instance: 'client'
  - jedi_client:
    - { name: 'name1',
        jedi: 'vader'
      }
    - { name: 'name2',
        jedi: 'luke'
      }
  tasks:
  - name: 1. Check var jedi_instance, should be client
    debug: msg="{{ jedi_instance }}"
  - name: 2. Check var jedi_client without retemplate, should return full list
    debug: msg="{{ jedi_client }}"
  - name: 3. Check name in jedi_client without retemplate, should return name1,name2
    debug: msg="{{ item.name }}"
    with_items: "{{ jedi_client }}"
  - name: 4. Check name in jedi_client with retemplate and with_items (nested), should return name1,name2
    debug: msg="{{ item.name }}"
    with_items: "{{ 'jedi_' + jedi_instance }}"
    ignore_errors: true
  - name: 5. Check name in jedi_client with retempate with_items (what I need), should return name1,name2
    debug: msg="{{ item.name }}"
    with_items: "jedi_{{ jedi_instance }}"
    ignore_errors: true
```

Works on Ansble 1.9.4 as expected

```
ansible-playbook --version
ansible-playbook 1.9.4
```

```
PLAY [jedi] ******************************************************************* 

TASK: [1. Check var jedi_instance, should be client] ************************** 
ok: [127.0.0.1] => {
    "msg": "client"
}

TASK: [2. Check var jedi_client without retemplate, should return full list] *** 
ok: [127.0.0.1] => {
    "msg": "[{'jedi': 'vader', 'name': 'name1'}, {'jedi': 'luke', 'name': 'name2'}]"
}

TASK: [3. Check name in jedi_client without retemplate, should return name1,name2] *** 
ok: [127.0.0.1] => (item={'jedi': 'vader', 'name': 'name1'}) => {
    "item": {
        "jedi": "vader",
        "name": "name1"
    },
    "msg": "name1"
}
ok: [127.0.0.1] => (item={'jedi': 'luke', 'name': 'name2'}) => {
    "item": {
        "jedi": "luke",
        "name": "name2"
    },
    "msg": "name2"
}

TASK: [4. Check name in jedi_client with retemplate and with_items (nested), should return name1,name2] *** 
ok: [127.0.0.1] => (item={'jedi': 'vader', 'name': 'name1'}) => {
    "item": {
        "jedi": "vader",
        "name": "name1"
    },
    "msg": "name1"
}
ok: [127.0.0.1] => (item={'jedi': 'luke', 'name': 'name2'}) => {
    "item": {
        "jedi": "luke",
        "name": "name2"
    },
    "msg": "name2"
}

TASK: [5. Check name in jedi_client with retempate with_items (what I need), should return name1,name2] *** 
ok: [127.0.0.1] => (item={'jedi': 'vader', 'name': 'name1'}) => {
    "item": {
        "jedi": "vader",
        "name": "name1"
    },
    "msg": "name1"
}
ok: [127.0.0.1] => (item={'jedi': 'luke', 'name': 'name2'}) => {
    "item": {
        "jedi": "luke",
        "name": "name2"
    },
    "msg": "name2"
}

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=5    changed=0    unreachable=0    failed=0   
```

On 2.0 not work.

```
ansible-playbook --version
ansible-playbook 2.0.0.2
```

```
PLAY [jedi] ********************************************************************

TASK [1. Check var jedi_instance, should be client] ****************************
ok: [127.0.0.1] => {
    "msg": "client"
}

TASK [2. Check var jedi_client without retemplate, should return full list] ****
ok: [127.0.0.1] => {
    "msg": [
        {
            "jedi": "vader", 
            "name": "name1"
        }, 
        {
            "jedi": "luke", 
            "name": "name2"
        }
    ]
}

TASK [3. Check name in jedi_client without retemplate, should return name1,name2] ***
ok: [127.0.0.1] => (item={u'jedi': u'vader', u'name': u'name1'}) => {
    "item": {
        "jedi": "vader", 
        "name": "name1"
    }, 
    "msg": "name1"
}
ok: [127.0.0.1] => (item={u'jedi': u'luke', u'name': u'name2'}) => {
    "item": {
        "jedi": "luke", 
        "name": "name2"
    }, 
    "msg": "name2"
}

TASK [4. Check name in jedi_client with retemplate and with_items (nested), should return name1,name2] ***
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "ERROR! 'unicode object' has no attribute 'name'"}
...ignoring

TASK [5. Check name in jedi_client with retempate with_items (what I need), should return name1,name2] ***
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "ERROR! 'unicode object' has no attribute 'name'"}
...ignoring

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=5    changed=0    unreachable=0    failed=0   
```

**Comment by k0ste** [comment]
May be some syntax is deprecated? I read google group from now up to dec 2015, change log and porting guide, solution not found.

**Comment by dagwieers** [comment]
The error makes sense, you provide a string to with_items, and not a list of dictionaries. This string (a unicode string) does not have any property 'name', hence the error you see.

The obvious (and only?) solution (but also a very ugly one !) is sending it through the  to_json filter, similar to:

```
with_items: '{{ variable | to_json }}'
```

How to apply this to your use-case seems not trivial to me. I would not prefix-namespace your dictionary, but instead use a dictionary syntax as well.

``` yaml
  vars:
  - jedi_instance: 'client'
  - jedi:
      client:
      - name: 'name1',
        jedi: 'vader'
      - name: 'name2',
        jedi: 'luke'
```

Then you can do:

```
with_items: jedi[instance]
```

**Comment by k0ste** [comment]
dagwieers, I can't use dict. This [is why](https://groups.google.com/forum/#!searchin/ansible-project/k0ste/ansible-project/J9aNksRvDmg/2WISD0Nr01wJ) and [this is solution](https://github.com/k0ste/ansible-role-openvpn-ldap).

> The error makes sense, you provide a string to with_items, and not a dictionary.

You don't understand. I replace example playbook and logs for a greater understanding of the problem.

The key of the problem, on 2.0:

jedi_{{ jedi_instance }} != {{ jedi_client }}

on 1.9.4 and prev.:
jedi_{{ jedi_instance }} == {{ jedi_client }}
or {{ 'jedi_' + jedi_instance }} == {{ jedi_client }}
How you like.

**Comment by dagwieers** [comment]
@k0ste I am working within the "realm" of how it currently works in v2. Whether this behaviour is how it is supposed to work, or in fact a bug is not something I can help you with. That's up to whoever designed it like it is. I don't know if it is the intention to have it working exactly as it was on v2 (or whether you were using something that was not intended to work in v1.9).

**Comment by k0ste** [comment]
Any news?

**Comment by bcoca** [comment]
@k0ste that was always considered 'invalid', we were not actually even aware it 'worked'

if this is in a conditional, no need to use {{}} (only place you shouldn't), for dynamic variable resolution we've always shown this manner:

`when: hostvars[inventory_hostname]['jedi_' + jedi_instance] == jedi_client`

@dagwieers 
`with_items: '{{ variable | to_json }}'`
this is incorrect as to_json returns a string with JSON, variables will be typed directly:
`with_items: '{{ variable }}'`
 if not (leading spaces can prevent it) this would be the proper way to get the data to ansible:
`with_items: '{{ variable | from_json }}'`

**Comment by bcoca** [comment]
I'm going to close this ticket as we don't plan on trying to enable this method:
`with_items: "jedi_{{ jedi_instance }}"`

Which really only 'worked by accident' in previous versions due to ignored errors and a an infinite recursive templating loop.

the proper way to do this was and is:
`with_items:  "{{hostvars[inventory_hostname]['jedi_' + jedi_instance]}}"`

**Comment by k0ste** [comment]
@bcoca, don't work.

> the proper way to do this was and is:
> with_items: "{{hostvars[inventory_hostname]['jedi_' + jedi_instance]}}"

``` yaml
  - name: 6. Bcoca check
    debug: msg="{{ item.name }}"
    with_items: "{{hostvars[inventory_hostname]['jedi_' + jedi_instance]}}"
```

```
TASK [5. Check name in jedi_client with retempate with_items (what I need), should return name1,name2] ***
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "ERROR! 'unicode object' has no attribute 'name'"}
...ignoring

TASK [6. Bcoca check] **********************************************************

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=5    changed=0    unreachable=0    failed=0   
```

debug module returned nothing.

**Comment by bcoca** [comment]
sounds like the var returned is not a dictionary, i would check the structure with:

`- debug: msg='{{hostvars[inventory_hostname]['jedi_' + jedi_instance]}}"`

**Comment by k0ste** [comment]
I test on playbook on first post.

``` yaml
  - name: 6. Bcoca check
    debug: msg="{{ item.name }}"
    with_items: "{{hostvars[inventory_hostname]['jedi_' + jedi_instance]}}"
  - name: 7. Bcoca check 2
    debug: msg="{{hostvars[inventory_hostname]['jedi_' + jedi_instance]}}"
```

```
TASK [6. Bcoca check] **********************************************************

TASK [7. Bcoca check 2] ********************************************************
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "ERROR! 'dict object' has no attribute u'jedi_client'"}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=5    changed=0    unreachable=0    failed=1   
```

**Comment by bcoca** [comment]
It seems you have an undefined var (jedi_instance = 'client') and `jedi_client` is reported as not a valid var for the host (is it in vars[]?). I don't see this being a bug at this point we can follow up on your issue in IRC or the mailing list.

**Comment by k0ste** [comment]
@bcoca, I use playbook from [this](https://github.com/ansible/ansible/issues/14286#issue-130947857) post.

After I add vars from playbook to host_vars - your method is works, thanks.
To access 'vars' defined in playbook, need to use this:

``` yaml
with_items: "{{ vars['jedi_' + jedi_instance] }}"
```

This is all is pretty simple, now I understand. Sorrowfully this is hard to find in docs.

Resolved.
