### ISSUE TITLE
Wishlist: hide 'include' tasks when not in verbose mode

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#14285]
One of the changes in Ansible 2 is that it now reports all `include` tasks.

This is a bit painful, especially when you've a big playbook and use `--tags` to select just a few of the tasks -- all the include statements for roles irrelevant to what I'm debugging now tend to hide the actual tasks being run in between the includes.

Suggestion: hide `include` tasks by default.  Show them if an error happens, or if the user asks for more verbosity (by passing at least one `-v` to `ansible-playbook`).

**Comment by bcoca** [comment]
so going to close this as a no, it is simple to override the default callback to do this and the actual include issue should go away once we fix how inclusion and tags work.

**Comment by mgedmin** [comment]
> the actual include issue should go away once we fix how inclusion and tags work

This is very interesting!  Do you have a bug open describing the planned changes, or something like that?

**Comment by bcoca** [comment]
just the report, no pr yet #13507
