### ISSUE TITLE
Help (maybe bug) using with_items in combination with groups and jinja2 filter

### ISSUE THREAD

**Issue by hExPY** [ansible/ansible#14302]
Hey guys,

i think i found a bug since version 2.0.0.0

> ansible --version
> ansible 2.0.1.0
>   config file = /zuul/home/immonet/ansible/ansible.cfg
>   configured module search path = Default w/o overrides

When i try to run this task (part of a role) and the variable lbhostsgen is "**head**":

> ```
>  - name: blacklist current server in pen processes
>    #shell: echo disabling "{{ inventory_hostname }}" >> /tmp/tmpoutput.log
>    shell: penctl 127.0.0.1:8124 server `penctl 127.0.0.1:8124 servers | grep \`host {{ inventory_hostname }} | awk '{print $NF}'\` | awk '{print $1}'` blacklist 86400
>    register: lb_block
>    delegate_to: "{{ item }}"
>    with_items: groups.uaweb | intersect(groups.{{ lbhostsgen }}
> ```

I get this strange error while executing:

> **TASK [wildfly-service-deploy : blacklist current server in pen processes] ******
> task path: /zuul/home/immonet/ansible/roles/wildfly-service-deploy/tasks/main.yml:21
> <( groups.uaweb | intersect(groups.head) )> ESTABLISH SSH CONNECTION FOR USER: None
> <( groups.uaweb | intersect(groups.head) )> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/zuul/home/immonet/.ansible/cp/ansible-ssh-%h-%p-%r -tt '( groups.uaweb | intersect(groups.head) )' '/bin/sh -c '"'"'( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1454578044.06-45666928488707 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1454578044.06-45666928488707 )" )'"'"''
> fatal: [vsvc-head1]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"item": "( groups.uaweb | intersect(groups.head) )", "msg": "SSH encountered an unknown error. The output was:\nOpenSSH_6.0p1 Debian-4+deb7u2, OpenSSL 1.0.1e 11 Feb 2013\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for _\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/zuul/home/immonet/.ansible/cp/ansible-ssh-( groups.uaweb | intersect(groups.head) )-22-immonet\" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\nssh: Could not resolve hostname ( groups.uaweb | intersect(groups.head) ): Name or service not known\r\n", "unreachable": true}]}
>   to retry, use: --limit @/zuul/home/immonet/ansible/relocation-employee.retry_*

This is my inventory file:

> [head]
> vua-head
> vsvc-head1
> vuaphp1
> 
> [uaweb]
> vua-head
> vua-rc1

With my understanding ansible isn't able to resolve the with_items parameter **groups.uaweb | intersect(groups.{{ lbhostsgen }}**.

Maybe you guys can help me out.

Kind regards,
Marvyn

**Comment by dagwieers** [comment]
Jup, in YAML what you wrote is considered a string and Ansible is now also interpreting it as a string (or in fact it accepts it as a list with one item for your convenience). The difficulty here obviously is when should the argument (when string) be interpreted as an expression, and when is it intended to be a string ? Are there any exceptions, I don't know ?

I have seen various reports (eg. #14286) about this breaking older code with Ansible v2. Not sure if this is being worked on currently, or whether this is a regression.

**Comment by hExPY** [comment]
Hi @dagwieers,

thanks for telling me whats the problem. Do you know any solution to fix it?
I mean i only want to iterate trough a list of hosts which includes all hosts which are in Group A and Group B. (group_a:&group_b)

**Comment by dagwieers** [comment]
@hExPY Can you test if this works for you:

``` yaml
with_items: '{{ groups.uaweb | intersect(groups[lbhostsgen]) }}'
```

But that's a workaround at best.

I would like to know from the powers-that-be if this is intentional or a regression in v2.

**Comment by hExPY** [comment]
Hey @dagwieers your workaround works perfectly.
Just for completion:
You missed a clamp:
with_items: '{{ groups.uaweb | intersect(groups[lbhostsgen]**)** }}'

Kind regards,
Marvyn

**Comment by dagwieers** [comment]
I went back in time and fixed the example :-)
Thanks for reporting back and closing the issue !
