### ISSUE TITLE
default tcsh makes ansible choke

### ISSUE THREAD

**Issue by andrewrothstein** [ansible/ansible#14309]
My default shell on a target machine is tcsh. The ansible connection process looks like it's feeding sh syntax through the ssh pipe which is causing the host to choke.

The scriptlet looks like:

```
( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1454599214.47-262731913175217 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1454599214.47-262731913175217 )"; 
```

The `$()` syntax doesn't work in tcsh. Is this in anyway configurable?

I tried having ssh launch sh but that didn't seem to work. It just sort of hung.

**Comment by bcoca** [comment]
already fixed in devel via 42e312d3bd0516ceaf2b4533ac643bd9e05163cd, it should be out all future releases.
