### ISSUE TITLE
[WARNING]: log file at /var/log/ansible.log is not writeable, aborting

### ISSUE THREAD

**Issue by udondan** [ansible/ansible#14320]
##### Issue Type:

 Bug Report
##### Ansible Version:

2.0.0.2
##### Ansible Configuration:

`ansible.cfg` contains:

```
# Activating logging
log_path = /var/log/ansible.log
```
##### Environment:

CentOS 7
##### Summary:

When the file given in `log_path` is writable but the parent folder is not, Ansible complains with

```
[WARNING]: log file at /var/log/ansible.log is not writeable, aborting
```

But that's not the case.
1. The file is writable
2. It only is complaining and telling it's aborting, but actually it then continues to run the whole playbook.
3. Also the log will be filled with all events as expected.

The file definitely is writable by everyone:

```
$ ls -l /var/log/ansible.log
-rwxrwxrwx 1 root root 815 Feb  5 15:34 /var/log/ansible.log
```

The folder `/var/log` obviously is not:

```
$ ls -l /var | grep log
drwxr-xr-x. 14 root root  4096 Feb  5 13:32 log
```

If the folder /var/log is made writable by everyone, the warning is gone.
##### Steps To Reproduce:
1. Set `log_path` to a file where the parent folder is not writable by Ansible
2. Run any Ansible command
##### Expected Results:

No warning should be shown. The file is writable. It is not relevant if the parent directory is writable or not.
##### Actual Results:

```
[WARNING]: log file at /var/log/ansible.log is not writeable, aborting
```

Even though ansible claims the file is not writable and it will abort the play, it will continue to run the whole playbook and also logs all events to the given file.

**Comment by bcoca** [comment]
dupe of already fixed #13990, fix will be out in future releases

**Comment by udondan** [comment]
Ah, thanks. I searched the issues before but github filters the closed issues by default.

**Comment by MatthewBooth** [comment]
Not fixed, still having this issue in 2018

**Comment by Aisuko** [comment]
Same issue. Looks like not fixed.
```
[WARNING]: log file at /var/log/ansible.log is not writeable and we cannot create it, aborting

ansible 2.4.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

```

**Comment by Aisuko** [comment]
Alright,  I realized this can not be a solution,it only solve this issue

After I add `log_path= ./ansible.log` to `ansible.cfg`.
I input `ansible --version` got error

```
[WARNING]: log file at /etc/ansible/ansible.log is not writeable and we cannot create it, aborting

ansible 2.4.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

```

So, I input command `sudo ansible  --version`, ansible.log created sucessed

```
ansible 2.4.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

```

Ps: If you want to save ansible logs ,you must be run command like `sudo ansible-playbook xx.yml`. You can find ansible.log under `/etc/ansible` folder.
