### ISSUE TITLE
Retry outputs blank lines for every retry

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#14321]
So I've upgraded from 1.9.4. to 2.0.0.2 using PIP.

In this playbook I have this piece of code:

```
 - name: Get loadbalancer output
    shell: echo "show stat" | nc -U /var/lib/haproxy/stats | grep "{{ backend }},{{ inventory_hostname }}"
    register: output
    delegate_to: "{{ loadbalancer }}"
    become: True
    become_user: root
    when: "'www4' in inventory_hostname or 'www5' in inventory_hostname"
    until: "',UP,' in output.stdout"
    retries: 24 
    delay: 10 
```

In 1.9.4. , when it was executing this task, there was no output.
in 2.0.0.2. Every time it checks, it will echo 2 new lines to my shell. Since the boot time for this service is at least 160 seconds, I have a completely black shell (yes I can scroll up to see the rest of the playbook). I'm not sure if this is expected behaviour, but I hope you can agree that this is not very handy if you want to read the output of your playbook, with having 60 blank lines in your output.

**Comment by jimi-c** [comment]
This is a known change from 1.9.x, it previously only used to show the retry messages when using a certain level of verbosity. I'll hold this open for now as we should be able to revert this back to 1.9.x behavior.

**Comment by ghost** [comment]
Hmmm. The bug is worse than I thought.

The lines aren't blank but my Putty cant handle the Dark grey output, l ike so:

`FAILED - RETRYING: TASK: Check if Server is back online in Loadbalancer (14 retries left). Result was: {u'changed': True, u'end': u'2016-02-10 13:39:54.976824', u'stdout': u'foo,bar,0,0,1,32,,10785899,7639994219,182591911470,,0,,23,19010,69,0,UP 1/3,40,1,0,6,15,1,3683,,1,3,2,,6676661,,2,1,,131,L7OK,200,30,0,9400801,1022034,299269,44691,0,0,,,,97,7,,,,,0,OK,,0,1,139,150,', u'cmd': u'echo "show stat" | nc -U /var/lib/haproxy/stats | grep "foo,bar"', u'rc': 0, u'start': u'2016-02-10 13:39:54.965519', u'stderr': u'', u'delta': u'0:00:00.011305', 'invocation': {'module_name': u'command', u'module_args': {u'creates': None, u'executable': None, u'chdir': None, u'_raw_params': u'echo "show stat" | nc -U /var/lib/haproxy/stats | grep "foo,bar"', u'removes': None, u'warn': True, u'_uses_shell': True}}, 'stdout_lines': [u'foo,bar,0,0,1,32,,10785899,7639994219,182591911470,,0,,23,19010,69,0,UP 1/3,40,1,0,6,15,1,3683,,1,3,2,,6676661,,2,1,,131,L7OK,200,30,0,9400801,1022034,299269,44691,0,0,,,,97,7,,,,,0,OK,,0,1,139,150,'], u'warnings': []}`
However, on other systems I see that this task does the following:
- It runs once and outputs the registered value which you get from the shell command.
- It failes after the first try (the service is still starting and the 'until' clause is not met)
- It returns a Failed in dark grey, but continues with the playbook instead of retrying it 24 times (it defaulted to 15 even though I set this to 24)

I can imagine this is unexpected behaviour since it doesn't retry, it doesn't wait for 10 seconds every time to evaluate nor it stops the playbook when it returns a Failed.

Perhaps somebody else can confirm this?

**Comment by CodeSturgeon** [comment]
Would be great to go back to the pre-2 level of verbosity. The pages of RETRYING messages are annoying. I have a playbook that now outputs more in RETRYING messages than the rest of the playbook combined.

**Comment by jimi-c** [comment]
We have added the ability to set the terminal colors for messages in devel (2.1), and as such we will go ahead and close this issue now.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
