### ISSUE TITLE
ansible is leaking subprocesses when killed by SIGTERM

### ISSUE THREAD

**Issue by lhuard1A** [ansible/ansible#14346]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

`/etc/ansible/ansible.cfg` contains only comments:

```
$ egrep -v '^$|^#' /etc/ansible/ansible.cfg
[defaults]
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
[accelerate]
[selinux]
```
##### Environment:

ArchLinux
##### Summary:

When an `ansible` or `ansible-playbook` process is killed by a `SIGTERM` signal, one of its sub-process remains live forever.

This happens when one tries to invoke `ansible` or `ansible-playbook` from a program that has a timeout and that fires a `SIGTERM` signal to the `fork`ed/`execve`d process if it takes more time than expected to complete.
In that case, an `ansible` or `ansible-playbook` sub-process is leaked and never finishes.
##### Steps To Reproduce:

Use a basic inventory:

```
foo ansible_connection=local ansible_python_interpreter=/usr/bin/python2
bar ansible_connection=local ansible_python_interpreter=/usr/bin/python2
baz ansible_connection=local ansible_python_interpreter=/usr/bin/python2
```

Launch a command:

```
$ ansible -i inventory.ini all -m command -a "sleep 30"
```

And kill the launched `ansible` process while the `sleep 30` is running:

```
$ ps -fu $UID | grep ansible
lenaic   26628  1896 33 00:00 pts/1    00:00:01 /usr/bin/python2 /usr/bin/ansible -i inventory.ini all -m command -a sleep 30
lenaic   26633 26628 15 00:00 pts/1    00:00:00 /usr/bin/python2 /usr/bin/ansible -i inventory.ini all -m command -a sleep 30
lenaic   26634 26628  1 00:00 pts/1    00:00:00 /usr/bin/python2 /usr/bin/ansible -i inventory.ini all -m command -a sleep 30
lenaic   26635 26628  1 00:00 pts/1    00:00:00 /usr/bin/python2 /usr/bin/ansible -i inventory.ini all -m command -a sleep 30
lenaic   26636 26628  1 00:00 pts/1    00:00:00 /usr/bin/python2 /usr/bin/ansible -i inventory.ini all -m command -a sleep 30
lenaic   26652 26634  0 00:00 pts/1    00:00:00 /bin/sh -c LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8 LC_MESSAGES=fr_FR.UTF-8 /usr/bin/python2 /home/lenaic/.ansible/tmp/ansible-tmp-1454713256.8-231434939428138/command; rm -rf "/home/lenaic/.ansible/tmp/ansible-tmp-1454713256.8-231434939428138/" > /dev/null 2>&1
lenaic   26653 26635  0 00:00 pts/1    00:00:00 /bin/sh -c LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8 LC_MESSAGES=fr_FR.UTF-8 /usr/bin/python2 /home/lenaic/.ansible/tmp/ansible-tmp-1454713256.8-54597535277775/command; rm -rf "/home/lenaic/.ansible/tmp/ansible-tmp-1454713256.8-54597535277775/" > /dev/null 2>&1
lenaic   26654 26636  0 00:00 pts/1    00:00:00 /bin/sh -c LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8 LC_MESSAGES=fr_FR.UTF-8 /usr/bin/python2 /home/lenaic/.ansible/tmp/ansible-tmp-1454713256.8-270105586115111/command; rm -rf "/home/lenaic/.ansible/tmp/ansible-tmp-1454713256.8-270105586115111/" > /dev/null 2>&1
lenaic   26655 26652  6 00:00 pts/1    00:00:00 /usr/bin/python2 /home/lenaic/.ansible/tmp/ansible-tmp-1454713256.8-231434939428138/command
lenaic   26656 26653  6 00:00 pts/1    00:00:00 /usr/bin/python2 /home/lenaic/.ansible/tmp/ansible-tmp-1454713256.8-54597535277775/command
lenaic   26657 26654  5 00:00 pts/1    00:00:00 /usr/bin/python2 /home/lenaic/.ansible/tmp/ansible-tmp-1454713256.8-270105586115111/command
lenaic   26664  2549  0 00:00 pts/2    00:00:00 grep --color ansible

$ kill -TERM 26628
```
##### Expected Results:

Eventually, no `ansible` process remains.
It is actually what would have happened if the sent signal had been `INT` instead of `TERM`.
##### Actual Results:

Even after a long time:

```
$ ps -fu $UID | grep ansible
lenaic   26633     1 15 00:00 pts/1    00:00:21 /usr/bin/python2 /usr/bin/ansible -i inventory.ini all -m command -a sleep 30
```

`26633` was a children of the killed process. But instead of being cleaned, it has just been reaped by `init`.
##### Remarks

The reason why sub-processes are correctly cleaned when the master process is killed by `INT` and not by `TERM` is because there is [signal handling code specific to `INT`](https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/playbook_executor.py#L72).

The issue is not reproducible if `ansible`/`ansible-playbook` is wrapped inside `/usr/bin/timeout` because that utility creates a process group before `fork`ing/`exec`ing and signals the whole process group when a timeout fires.

**Comment by bcoca** [comment]
@lhuard1A, please confirm that the above PR solves the issue for you.

**Comment by lhuard1A** [comment]
Thanks @bcoca ! I put my findings directly in the PR.

**Comment by nhooey** [comment]
@bcoca Does your solution run `handlers` when closing from `SIGINT`?

The system could end up in a bad state if it doesn't.
