### ISSUE TITLE
Default file permissions with template (and presumably other modules daisychaining into file)

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#1434]
The `template` module in 0.7.1 didn't touch file permissions if not told to. This has changed in 0.8: apparently a default of 640 is applied. 

When templating an `/etc/sudoers` file (at least on SLES10) the following happens:
1. Template is copied to node
2. Template result is copied over /etc/sudoers
3. Default mode 0640 is applied
4. Ansible is locked out because _sudo_ now complains that file is no longer mode 0440.

Specifying a `mode=0440` to the template action doesn't help as it appears to be applied too late in the chain.

**Comment by jpmens** [comment]
Clarification:

Template contains "hello world"

Playbook contains: `- action: template src=ch.in dest=/tmp/ch`

```
rm /tmp/ch
touch /tmp/ch
chmod 440 /tmp/ch
ansible-playbook ch.yml
ls -l /tmp/ch
```

## 0.7.1

```
-r--r----- 1 root  root  12 ...
```

## 0.8

```
-rw-r--r-- 1 root root 12 ...
```

**Comment by dhozac** [comment]
This is due to the copy module replacing files atomically, by doing rename to the real name after copying it to the same directory.

**Comment by mpdehaan** [comment]
Yeah, not sure what we can do about this.  I think it should be a good practice to always specify your modes?

**Comment by jpmens** [comment]
Tried that. In the case of `template` it doesn't work, but I don't know why... can't seem to find the code that does it.

For `copy` I could imagine checking existing perms and copything them in with shutil.copymode() [if that's what it's called].

**Comment by jpmens** [comment]
Sorry: by "it doesn't work" I mean that sudo is locked out even if I try to set `mode=440` explicitly in the template action.

**Comment by dhozac** [comment]
That should already be fixed on devel, from the file module being in module common.

**Comment by jpmens** [comment]
```
ansible 0.9 (devel 46b993bb80) last updated 2012/10/24 14:33:57 (GMT +200)
```

Not really:

``` yaml
- hosts: 127.0.0.1
  gather_facts: false
  connection: local
  tasks:
    - action: template src=templ.in dest=/tmp/t
```

produces:

``` sh
touch /tmp/t
chmod 641 /tmp/t
ansible-playbook ...
ls -l /tmp/t
-rw-r--r--  1 jpm  wheel  562 Oct 24 14:37 /tmp/t
```

which means it's replacing existing file permissions.

and

```
rm /tmp/t
touch /tmp/t
chmod 440 /tmp/t
ansible-playbook ...

TASK: [template src=templ.in dest=/tmp/t] ********************* 
failed: [127.0.0.1] => {"failed": true, "msg": "Destination /tmp/t not writable"}
```

this doesn't seem really clever either: file is read-only, but it belongs to the user Ansible is running as, so it should be unlinked and re-creat'ed.

**Comment by mpdehaan** [comment]
Not sure.  @sfromm comments on atomic mv support? 

-- Michael

**Comment by dhozac** [comment]
I meant being able to specify mode=0440 and have it work being fixed. I don't think copying settings from the previous file is a good idea, it is pretty much the opposite of what I'd expect a configuration management tool to do.

As for read-only files, yeah, that is dumb. I'm not convinced all these extra "checks" make much sense at all, I'd rather see the exceptions caught properly and given good messages at that point.

**Comment by jpmens** [comment]
Unless explicitly specified as `mode=`, permissions should remain the way they were. (_vi_ doesn't change them either ... :-)

**Comment by mpdehaan** [comment]
Not sure what checks you mean but open to patches

Keeping @sfromm in the loop but if we are talking 0.9 this is file merger stuff.

-- Michael

**Comment by mpdehaan** [comment]
0.9 has no daisy chain are we talking about 8 or 9?  

Seems like this is just restoring the old permission on the new atomic copy

-- Michael

**Comment by jpmens** [comment]
I reported issue for 0.8 (see way top of this ticket)

current discussion is for 0.9 :)

**Comment by mpdehaan** [comment]
Ok, was confused.  I am in favor of a fix on the 0.8 branch also.  Someone make if happen :)

-- Michael

**Comment by sfromm** [comment]
Here's a related error:

```
---
- hosts: all
  gather_facts: false
  connection: local
  tasks:
    - action: file path=/tmp/t mode=400
    - action: template src=lame.j2 dest=/tmp/t
```

Which yields:

```
PLAY [all] ********************* 

TASK: [file path=/tmp/t mode=400] ********************* 
changed: [localhost]

TASK: [template src=lame.j2 dest=/tmp/t] ********************* 
failed: [localhost] => {"failed": true, "msg": "Destination /tmp/t not writable"}
```

I own the file, so I should have write permission.

Back to the issue here, when I change the playbook to:

```
- action: file path=/tmp/t mode=600
- action: template src=lame.j2 dest=/tmp/t
```

The template command succeeds.  As already pointed out, the filemode is set to 0644.  That happens to match my umask.  I assume template creates a new file.  It is natural that the filemode should be based on the user's umask.  If I change my umask to 066, the filemode becomes 600.  It is probably best to explicitly define the mode.

That said, it would be nice to the user if ansible can preserve ownership and mode.

**Comment by mpdehaan** [comment]
Yeah if the file exists the copy module should default the mode to that if not specified.  That is what we should do.

**Comment by mpdehaan** [comment]
Anyone want to work on this?

**Comment by jpmens** [comment]
This patch works for me on Ansible 0.8.tar, but you'll probably want to solve that differently.

``` diff

--- /tmp/copy.orig  2012-10-25 08:14:35.000000000 +0200
+++ ansible-0.8/library/copy    2012-10-25 08:33:24.000000000 +0200
@@ -76,6 +76,8 @@
     dest = os.path.expanduser(module.params['dest'])
     backup = module.boolean(module.params.get('backup', False))

+    destperms = 0644
+
     if not os.path.exists(src):
         module.fail_json(msg="Source %s failed to transfer" % (src))
     if not os.access(src, os.R_OK):
@@ -85,8 +87,9 @@
     md5sum_dest = None

     if os.path.exists(dest):
-        if not os.access(dest, os.W_OK):
-            module.fail_json(msg="Destination %s not writable" % (dest))
+        destperms = os.stat(dest).st_mode & 0777
+#        if not os.access(dest, os.W_OK):
+#            module.fail_json(msg="Destination %s not writable" % (dest))
         if not os.access(dest, os.R_OK):
             module.fail_json(msg="Destination %s not readable" % (dest))
         if (os.path.isdir(dest)):
@@ -114,6 +117,7 @@
             dest_tmp = "%s.%s.%s.tmp" % (dest,os.getpid(),time.time())
             shutil.copyfile(src, dest_tmp)
             shutil.move(dest_tmp, dest)
+       os.chmod(dest, destperms)
         except shutil.Error:
             module.fail_json(msg="failed to copy: %s and %s are the same" % (src, dest))
         except IOError:
```

**Comment by mpdehaan** [comment]
Possibly.

As it only checks perms, so I am not sure if there is any other attributes
that might get lost or defaulted incorrectly.   There's already some
functions to get file info for return, so those are probably usable.

Warrants testing.

To be clear -- I'm not working on this now.

**Comment by edrozenberg** [comment]
In latest 1.7 git 2014-05-29 noticed that template does not maintain permissions of original source template files. For ex. executable flag on a template gets lost when copied to the destination. Not sure if this issue is supposed to be solved or if the recommendation is to always use an explicit mode setting for every template/file.
