### ISSUE TITLE
Changes to variable inheritance break existing playbooks

### ISSUE THREAD

**Issue by larsks** [ansible/ansible#14343]
Commit 1733d43 changes how variable inheritance works.  If I have a role that attempts to override `ansible_user`, like this: 

```
dependencies:
  - role: anotherrole
    ansible_user: root
```

And someone passes in an inventory like this:

```
host0 ansible_ssh_user=alice
```

Then my attempt at setting `ansible_user` will always fail, whereas previously it would have worked.  I'm using `ansible_user` in the playbook because `ansible_ssh_user` is deprecated, but someone _using_ my roles may not know that and may pass in an inventory that triggers this behavior.

It's possible that trying to override `ansible_user` like this is not actually a great idea, but I wanted to document a case in which there is clearly a breaking change in variable handling, so it should at least be documented.

**Comment by jimi-c** [comment]
@larsks I believe I actually may have fixed this in https://github.com/ansible/ansible/commit/75b6f616190857db6b816096ce39bdaf2c16822a

**Comment by larsks** [comment]
75b6f61 seems to fix my simple reproducer, but the playbook I actually care about is still failing.  I'll see if I can figure out why.

**Comment by larsks** [comment]
So, here is a reproducer.  In playbook.yml I have:

```
- hosts: targethost
  roles:
    - testrole1
```

In `roles/testrole1/meta/main.yml` I have:

```
dependencies:
  - role: testrole2
    ansible_user: root
```

In `roles/testrole2/tasks/main.yml` I have:

```
- name: ansible_user inside role
  debug:
    var: ansible_user

- name: ansible_ssh_user inside role
  debug:
    var: ansible_ssh_user

- ping:
```

In `inventory` I have:

```
targethost ansible_host=some.nearby.host ansible_ssh_user=alice
```

With ansible 2.0.0.2 I get:

```
$ git co v2.0.0.2-1
$ ansible-playbook --version
ansible-playbook 2.0.0.2 (detached HEAD 7de237c5a1) last updated 2016/02/05 15:35:34 (GMT -400)
  lib/ansible/modules/core: (detached HEAD e1ec52e365) last updated 2016/02/05 15:00:03 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 14a62fb5d6) last updated 2016/02/05 15:00:03 (GMT -400)
  config file = /home/lars/src/ansible/work/ansible.cfg
  configured module search path = Default w/o overrides
$ ansible-playbook -i inventory playbook.yml
PLAY ***************************************************************************

TASK [testrole2 : ansible_user inside role] ************************************
ok: [targethost] => {
    "ansible_user": "root"
}

TASK [testrole2 : ansible_ssh_user inside role] ********************************
ok: [targethost] => {
    "ansible_ssh_user": "stack"
}

TASK [testrole2 : ping] ********************************************************
ok: [targethost]

PLAY RECAP *********************************************************************
targethost                 : ok=3    changed=0    unreachable=0    failed=0   
```

But with current HEAD I get:

```
$ git co devel
$ ansible-playbook --version
ansible-playbook 2.1.0 (devel ad37a91514) last updated 2016/02/05 15:10:14 (GMT -400)
  lib/ansible/modules/core: (detached HEAD e1ec52e365) last updated 2016/02/05 15:36:59 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 14a62fb5d6) last updated 2016/02/05 15:36:59 (GMT -400)
  config file = /home/lars/src/ansible/work/ansible.cfg
  configured module search path = Default w/o overrides
$ ansible-playbook -i inventory playbook.ym
l 

PLAY ***************************************************************************

TASK [testrole2 : ansible_user inside role] ************************************
ok: [targethost] => {
    "ansible_user": "root"
}

TASK [testrole2 : ansible_ssh_user inside role] ********************************
ok: [targethost] => {
    "ansible_ssh_user": "stack"
}

TASK [testrole2 : ping] ********************************************************
fatal: [targethost]: UNREACHABLE! => {"changed": false, "msg": "SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}

PLAY RECAP *********************************************************************
targethost                 : ok=2    changed=0    unreachable=1    failed=0   
```

Adding `-vvvv` onto that failed run gets me:

```
<some.nearby.host> ESTABLISH SSH CONNECTION FOR USER: alice
<some.nearby.host> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=alice -o ConnectTimeout=10 -o ControlPath=/home/lars/.ansible/cp/ansible-ssh-%h-%p-%r -tt some.nearby.host '/bin/sh -c '"'"'( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1454704716.98-55708830988229 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1454704716.98-55708830988229 `" )'"'"''
```

Where you can see that Ansible is attempting to connect with the user
from the inventory rather than using the value of `ansible_user` set
when calling the role.

**Comment by jimi-c** [comment]
So my patch above specifically avoids changing a value that was already set to some other value, not sure if that's the wisest course of action, but I would also recommend users not mix old and new variables.

**Comment by larsks** [comment]
Right, I agree.  The issue here is that it's possible the person providing the inventory is using the old variable, and the person writing the playbook is using the new variable, and they are not the same person.

**Comment by davidebelloni** [comment]
Hi,
I've a similar issue with the following setup.

`ansible 2.1.0.0`

In `roles/outer/meta/main.yml`:

```
---
dependencies:
  - role: inner
    test_inner: "{{ test_outer }}"
```

In `roles/inner/tasks/main.yml`:

```
---
- name: "{{ test_inner }} group"
  group: name={{ test_inner }}
```

In `playbook.yml` :

```
    - role: outer
      test_outer: test
```

The output is:

```
TASK [inner : {{ test_inner }} group] ********************************
task path: roles/inner/tasks/main.yml:2
fatal: [default]: FAILED! => {"failed": true, "msg": "{{ test_outer }}: 'test_outer' is undefined"}

```

I'm pretty sure that this code some time ago was correct

Thanks

**Comment by davidebelloni** [comment]
I've opened a new issue (#16320) because I think the bug is slightly different

**Comment by jimi-c** [comment]
Revisiting old issues, and I think we're going to stand by my comment above @larsks. Nowhere else in Ansible does a variable of a different name trump another, and we changed it behave this way for a reason. As such, we'll close this now.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by larsks** [comment]
Well, you're going to get comments on closed tickets anyway, because this is where we're discussing the issue and it seems ludicrous to fork the conversation somewhere else.

@jimi-c I thought that `ansible_ssh_user` had been deprecated by `ansible_user`, which to me says that are in fact two different names for the same thing.  If that is true (the latter deprecates the former) then I think this is obviously a bug.  If that's not true (you're planning to support both configuration variables as "first class citizens" for the foreseeable future) then I agree with your position.

**Comment by jimi-c** [comment]
@larsks standard message, mainly for people rolling by 6 months in the future...

Yes, `ansible_user` is favored over `ansible_ssh_user`, however it's not an alias which is why I do not consider this a bug. As I said originally, the two should not be mixed,
