### ISSUE TITLE
uri module shows "httplib2 >= 0.7 is not installed"

### ISSUE THREAD

**Issue by haifengkao** [ansible/ansible#14342]
The messages:

```
FAILED! => {"changed": false, "failed": true, "msg": "httplib2 >= 0.7 is not installed"}
```

The discussion thread on stackoverflow:
http://stackoverflow.com/questions/31596853/how-do-you-add-httplib2-into-ansible

**Comment by sivel** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by haifengkao** [comment]
I would say it's a bug.
Ansible should install the required python libraries for its core modules.
The problem should be fixed in the ansible installation script.

@sivel you are just being irresponsible.

**Comment by JordyMoos** [comment]
I have the same issue and i agree that ansible should get it dependencies right

**Comment by jlark** [comment]
+1 on this. The beauty of ansible that it requires not host agent's or other components that it simply does everything from the host through SSH. httplib2 should be installed on ansible installation as a dependency.

**Comment by jlark** [comment]
Also this happens even when httlib2 is installed.
sudo pip install httplib2
Requirement already satisfied (use --upgrade to upgrade): httplib2 in /usr/lib/python2.7/dist-packages
Cleaning up...

**Comment by otisg** [comment]
@sivel any chance you might consider reopening this?  We are hitting this issue as well.

**Comment by sivel** [comment]
`httplib2` must be installed on the target machine.  Additionally, as of ansible 2.1, httplib2 will no longer be a dependency of the `uri` module.

**Comment by otisg** [comment]
OK, thanks.  Since you mentioned 2.1 - is there a rough ETA?

**Comment by eskobarba** [comment]
I'm also facing this, 2.0.1.0. host is localhost, and i have tried with installing httplib2 in both global and virtualenv

**Comment by gvilarino** [comment]
I can confirm this happens while using 2.0.1.0, and having `httplib2@0.9.2` installed. I even do

```
- name: ensure httplib2 is installed
  pip: name=httplib2 state=present
```

before running `uri`, and it still fails.

**Comment by sivel** [comment]
httplib2 is no longer required as of 2.0.2.  I recommend upgrading ansible.

**Comment by gvilarino** [comment]
Thanks @sivel. Will do

**Comment by JMLX42** [comment]
@sivel When I try to install ansible 2.4.2:

```
dpkg: dependency problems prevent configuration of ansible:
 ansible depends on python-httplib2; however:
  Package python-httplib2 is not installed.
```

So it does look like python-httplib2 *is* required.
