### ISSUE TITLE
Self written modules in roles with become_user != root are broken

### ISSUE THREAD

**Issue by adp-knaumann** [ansible/ansible#14348]
**Issue Type:**
    Bug Report

**Ansible Version:**
kn@master:~$ ansible --version
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

**Ansible Configuration:**
kn@master:~$ egrep -v '^$|^#' /etc/ansible/ansible.cfg
[defaults]
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
[accelerate]
[selinux]

**Environment:**

Lubuntu 15.10
RHEL6.5

**Summary:**

Self written modules don't work in ansible 2.0.0.2 when the following conditions are true:
1. become: yes is used
2. become_user is not root
3. the playbook is targeting a remote host (don't use 127.0.0.1)

**Steps To Reproduce:**

Code: https://gist.github.com/adp-knaumann/8db12375329f670091d4

To recreate the issue:

kn@client:~$ sudo useradd -m testusr
kn@master:~$ ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook -i hosts module_bug.yml

**Expected Results:**

Result with become user root is flawless (because args can be read in any case of course):

kn@master:~$ ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook -i hosts --ask-pass --ask-become-pass module_bug.yml 
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [client]

TASK [module_bug : run_module] *************************************************
ok: [client]

TASK [module_bug : print] ******************************************************
ok: [client] => {
    "param1": "foobarbaz"
}

PLAY RECAP *********************************************************************
client                      : ok=3    changed=0    unreachable=0    failed=0   

**Actual Results:**
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [client]

TASK [module_bug : run_module] *************************************************
fatal: [client]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible-tmp-1454756368.4-187607304090350/test.py\", line 8, in <module>\r\n    with open(sys.argv[1], 'r') as arg_file:\r\nIOError: [Errno 13] Permission denied: '/tmp/ansible-tmp-1454756368.4-187607304090350/args'\r\n", "msg": "MODULE FAILURE", "parsed": false}

PLAY RECAP *********************************************************************
client                      : ok=1    changed=0    unreachable=0    failed=1   

kn@client:~$ ls -l /tmp/ansible-tmp-1454756368.4-187607304090350/
total 8
-rw------- 1 kn kn  23 Feb  6 10:59 args
-rw-r--r-- 1 kn kn 286 Feb  6 10:59 test.py
kn@client:~$ cat /tmp/ansible-tmp-1454756368.4-187607304090350/args && echo
{"param1": "foobarbaz"}
kn@client:~$ cat /tmp/ansible-tmp-1454756368.4-187607304090350/test.py 
# !/usr/bin/python
# -_\- coding: utf-8 -_-
# WANT_JSON

import sys
import json

with open(sys.argv[1], 'r') as arg_file:
    json_data = json.load(arg_file)

print('{')
print('   "ansible_facts" : {')
print('      "param1" : "{0}"'.format(json_data['param1']))
print('   }')
print('}'

**Comment by adp-knaumann** [comment]
The underlying issue is that the args file has permissions 0600 and thus can't be read by the become user.

**Comment by sivel** [comment]
In `ActionBase._execute_module` it looks like we copy an args file up but do not chmod it.  We do with the script itself, just not the args file.  Should be an easy change.

**Comment by adp-knaumann** [comment]
@sivel I thought the same, but then I also thought:
This could lead to compromise of security relevant data. Say you supply a password as an argument to the call, this password would end up in the json data and then is readable by everyone (also unprivileged users) on the machine in the moment ansible is running. Depending on how long the module runs, this can be intercepted relatively easily for a malicious user.
I don't know if there are any better solutions to this tho.
At least it should be documented that this might be an issue I think.

**Comment by sivel** [comment]
Standard Ansible modules embed the data in the script itself, so effectively this is already being done.

**Comment by adp-knaumann** [comment]
Sent pull request #14351 

https://github.com/ansible/ansible/pull/14351

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
