### ISSUE TITLE
The "--flush-cache" option for playbook does not appear to work

### ISSUE THREAD

**Issue by gamename** [ansible/ansible#14360]
Hi,

The option --flush-cache does not seem to have any effect on the existing cache files.
### Here is my config:

```
# Set in the ansible.cfg file 
gathering = smart
```

...and...

```
# set in environment variables
export ANSIBLE_CACHE_PLUGIN="jsonfile"
export ANSIBLE_CACHE_PLUGIN_CONNECTION="~/.ansible/fact_cache"
export ANSIBLE_CACHE_PLUGIN_TIMEOUT=7200 ; # two hours
```
### Make a tiny playbook called "facts_refresh.yml"

```

---
- hosts: all
  gather_facts: True
```
### Run the playbook

```
ansible-playbook facts_refresh.yml
```
### several files are created in the `~/.ansible/fact_cache` dir:

```
-rw-rw-r--. 1 tennis tennis 11190 Feb  7 19:00 rtdb_restoral-10-0-91-169
-rw-rw-r--. 1 tennis tennis 10351 Feb  7 19:03 nat-10-0-46-236
-rw-rw-r--. 1 tennis tennis  6603 Feb  7 19:03 rtdb-10-0-148-205
-rw-rw-r--. 1 tennis tennis  6588 Feb  7 19:03 rtdb-10-0-18-247
-rw-rw-r--. 1 tennis tennis  6526 Feb  7 19:03 web-10-0-147-118
(etc)
```
### Re-run this or any other playbook with '--flush-cache'.

The cache files will not change in number or size, nor will their timestamps update. 

```
-rw-rw-r--. 1 tennis tennis 11190 Feb  7 19:00 rtdb_restoral-10-0-91-169
-rw-rw-r--. 1 tennis tennis 10351 Feb  7 19:03 nat-10-0-46-236
-rw-rw-r--. 1 tennis tennis  6603 Feb  7 19:03 rtdb-10-0-148-205
-rw-rw-r--. 1 tennis tennis  6588 Feb  7 19:03 rtdb-10-0-18-247
-rw-rw-r--. 1 tennis tennis  6526 Feb  7 19:03 web-10-0-147-118
```

**Comment by mjcramer** [comment]
I can verify that I am seeing this behavior as well. Specifically for jsonfile.

**Comment by stewartm** [comment]
+1 for this issue, same as above, encountered with a 'jsonfile' cache.

**Comment by Azenet** [comment]
+1 using Redis with Ansible 2.1.

**Comment by Shaps** [comment]
Hi, Yes I can confirm `--flush-cache` doesn't actually do anything in v2+.
With @abadger we found the code to actually flush the fact cache is there and implemented in the cache plugins, it just doesn't seem to be used in `VariableManager`. 

This should not affect versions prior to v2

**Comment by bcoca** [comment]
fixed via merged above
