### ISSUE TITLE
inconsistent group_var / role var / template module interaction

### ISSUE THREAD

**Issue by mattgiles** [ansible/ansible#14362]
`ansible: 2.0.0.2`

i have a role which writes systemd service files to target hosts, from templates (in `roles/role/templates/`).

one of the role's vars (defined in `roles/role/vars/main.yml`) is a list which compiles some labels for one of the services from group_vars.

``` yaml
my_list_role_var:
  - "key1={{ group_var1 }}"
  - "key2={{ group_var2 }}"
  - "key3={{ group_var3 }}"
```

Then in one of the template files:

```
...
{% for item in my_list_role_var %}
--label {{ item }} \
{% endfor %}
...
```

**sometimes**, but not always, this role fails to fill in these labels when filling in the template, leaving some of the elements in the list (but not all of them...) still in jinja form just as they appear in the role vars file.  so that on the hosts, in the uploaded service file, I see:

```
...
--label key1={{ group_var1 }} \
--label key2=VALUE2 \
--label key3={{ group_var3 }} \
...
```

even odder: some of the vars which fail to be evaluated are in reality provided default values (`| default(None)`).

is this defined behavior / not intended usage?

**Comment by jimi-c** [comment]
Hi @mattgiles, that is odd, and I can't see any reason why that would happen unless you were maybe limiting or otherwise filtering the inventory? Still, I would expect template failures to cause the overall template to fail.

Any other details you can provide to help us reproduce this would be appreciated.

**Comment by mattgiles** [comment]
coming from a playbook of medium complexity. will think about best way to help reproduce. 

i can say that i believe what is going on is that the default filter is failing to fire, that the places where this is being seen are all places where we hope for a default filter to evaluate.

**Comment by mattgiles** [comment]
but i would also expect the template module to raise an exception rather than proceed.

**Comment by mattgiles** [comment]
suspicion is that the evaluation of this var is being deferred at some step when its siblings evaluate, but then never resolved at any later step?
