### ISSUE TITLE
User module constantly detects a change

### ISSUE THREAD

**Issue by cronnelly** [ansible/ansible#1439]
If you invoke the user module with the "group" parameter set to a group which you also specify in the "groups" parameter, the playbook will think the user has changed every time it is run.

For example, to reproduce the problem:
    user name=test groups=adm,developer group=developer

The desired behaviour is achieved as follows:
    user name=test groups=adm group=developer

**Comment by mpdehaan** [comment]
@sfromm want to chase?  You are my usual user module contact.  If not, let me know.

Thanks!
