### ISSUE TITLE
stdout_lines has extra '', 'BECOME-SUCCESS-<random>

### ISSUE THREAD

**Issue by d3matt** [ansible/ansible#14395]
probably need to strip BECOME-SUCCESS before splitting to an array

**Comment by jimi-c** [comment]
I'm testing your original patch (along with the extra removals I mentioned) now.

**Comment by jimi-c** [comment]
Merged your original patch (plus my additions, but left it all in your name to keep it at 1 commit while saving your attribution).

Thanks!
