### ISSUE TITLE
python-crypto missing from ansible/ansible-1.9 repository

### ISSUE THREAD

**Issue by bryanlarsen** [ansible/ansible#14392]
Can you please copy python-crypto=2.6.1-1chl1~precise1 from the ansible/ansible ppa into the ansible/ansible-1.9 ppa so ansible is installable on Ubuntu 12.04?   Thanks.

**Comment by jimi-c** [comment]
I'm not sure if we can easily redistribute that, but I'll look into it.

**Comment by bryanlarsen** [comment]
Doing the same thing you do in the ansible/ansible ppa is sufficient.   Thanks.

**Comment by ghjm** [comment]
This is fixed. Thanks for letting us know, @bryanlarsen.

**Comment by bryanlarsen** [comment]
You fixed this faster than I could deploy a workaround.   Amazing work, thanks!
