### ISSUE TITLE
RFE: provide configuration to local connection plugins

### ISSUE THREAD

**Issue by larsks** [ansible/ansible#14391]
If I have a playbook with an associated local connection plugin (i.e., one in a `connection_plugins` directory), there doesn't appear to be any mechanism by which I can provide configuration information to that plugin.

Within the plugin itself, it appears that there is no access to host vars.  That means I can't do this:

```
host0 key_required_by_plugin=foo
host1 key_required_by_plugin=bar
```

I can't use environment variables, either, if I need different values per-host.  I can have the plugin parse it's _own_ configuration file, but that seems as if it could quickly get ridiculous.

I have tried re-using `ssh_extra_args`, which works, I guess, but seems like a terrible idea in practice.  I wish there there was a better way of handling this.

**Comment by jimi-c** [comment]
Hi @larsks, for 2.0 (specifically for the winrm connection plugin), we implemented a method you can define to set host vars directly on the connection plugin: `def set_host_overrides(self, host):`. This is called if the method is defined for the connection plugin after it is created.

It doesn't necessarily give you the group_vars (though you can get them if you really want), so you have to merge things on your own without the VariableManager, but I believe this is what you're looking for.

**Comment by nitzmahone** [comment]
@larsks Also, take a look at winrm.py in devel or stable-2.0 - we use that override method there for this exact reason (and you can see how to get at group_vars too)

**Comment by larsks** [comment]
@jimi-c Hey, that is super helpful and seems to mostly solve my problem.  If I were proposing a new in-tree connection driver, would using this method be preferable to introducing new configuration variables?

Also, while I have access to group and host vars, it looks like variables set at higher levels (e.g., play vars, or vars set with `-e var=value` or `-e @varfile.yml` ) are not visible.  Is there any way to get at these from within the connection plugin?

**Comment by jimi-c** [comment]
Yes it would be preferable, but no there's no way to get to those variables. The idea was for host-specific settings that didn't map to things in PlayContext.

**Comment by larsks** [comment]
All right. Thanks for your help! I'm going to go ahead and close this now.
