### ISSUE TITLE
move host parsing logic to seperate python file, make inventory format also support JSON/YAML files

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#144]

**Comment by mpdehaan** [comment]
needs to work with both runner and playbooks, as well as existing external hosts support, and also support port assignments.

seperate test module in tests/ is probably a good idea too

**Comment by jhoekx** [comment]
Refactoring was not as easy as expected because the async functions used the internals of runner.

You can track progress in my [yaml-inventory](https://github.com/jhoekx/ansible/tree/yaml-inventory) branch.

No yaml support yet, but it works in my playbooks.

**Comment by mpdehaan** [comment]
yeah, didn't expect it to be super easy :)  No rush, thanks for the update.

FWIW, it would be nice if the class method in Runner still worked, and called into this new thing, so older scripts that happened to use runner continued to work.

There are probably not many but people find API breaks kinda frustrating.

Thanks!

**Comment by mpdehaan** [comment]
done, closing, JSON should be trivial since YAML operates on datastructures, less human readable so don't need it yet
