### ISSUE TITLE
Dependent roles are only run for the first call even if "allow_duplicates: yes"

### ISSUE THREAD

**Issue by fabix** [ansible/ansible#14405]
Using ansible 2.1.0 (devel branch / 5a88478).

I have two roles : role_test2 is dependent of role_test1. 'allow_duplicates" is defined in role_test1 in order to be run each time role_test1 is used. But with this simple playbook (test.yml), we can see it's not the case: 

```

---
- hosts: localhost
  roles:
  - { role: role_test1, name: "foo" }
  - { role: role_test1, name: "bar" }
```

Output:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [role_test2 : display test var] *******************************************
ok: [localhost] => {
    "msg": "foo"
}

TASK [role_test1 : display test var] *******************************************
ok: [localhost] => {
    "msg": "foo"
}

TASK [role_test1 : display test var] *******************************************
ok: [localhost] => {
    "msg": "bar"
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0   
```

It should be:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [role_test2 : display test var] *******************************************
ok: [localhost] => {
    "msg": "foo"
}

TASK [role_test1 : display test var] *******************************************
ok: [localhost] => {
    "msg": "foo"
}

TASK [role_test2 : display test var] *******************************************
ok: [localhost] => {
    "msg": "bar"
}

TASK [role_test1 : display test var] *******************************************
ok: [localhost] => {
    "msg": "bar"
}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0   
```

Test files are here : https://github.com/fabix/ansible_dependencies_test

**Comment by Nosmoht** [comment]
Can confirm the behavior with Ansible 2.0.1.0 and Archlinux.

My setup is a little bit different as i don't run a role more than once as a dependency of another role. Instead i have two roles service1 and service2 which both have a dependency to role db.

Code together with current and expected result can be found here: https://github.com/Nosmoht/ansible-dependencies-test

**Comment by jimi-c** [comment]
Just a note here, the `allow_duplicates: yes` needs to be set in the dependent role, not the parent. Beyond that, looking into this bug now.

**Comment by jimi-c** [comment]
So I believe this is just a misunderstanding of the above. When `allow_duplicates` is set in the correct place, this runs as expected.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
