### ISSUE TITLE
svr4pkg fails to install package on subsequent runs

### ISSUE THREAD

**Issue by davecore82** [ansible/ansible#14418]
Installing a package on Solaris 10 with svr4pkg works on the first run. But then fails on subsequent runs.

If I remove the package manually, then it will succeed again on the next run to install it. But then subsequent runs will fail again.

Ansible play:
`- name: TEST - Installation avec svr4pkg
  #svr4pkg: name=SUNWeu8os src=/repoSolaris10/media/Solaris_10_U11/Solaris_10/Product state=present
  svr4pkg: name=SUNWi1cs src=/repoSolaris10/media/Solaris_10_U11/Solaris_10/Product state=present
  tags: testdavepkg`

1st run:
`TASK [solaris10 : TEST - Installation avec svr4pkg] ****************************
changed: [CT20SLDOMSBXD01]`

Subsequent runs:
`TASK [solaris10 : TEST - Installation avec svr4pkg] ****************************
fatal: [CT20SLDOMSBXD01]: FAILED! => {"changed": false, "failed": true, "name": "SUNWi1cs", "state": "present"}`

Running Ansible 2.0.0.2 from Ubuntu 14.04.3, on a Solaris 10 1/13 client.

**Comment by nitzmahone** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead. The svr4pkg module is under https://github.com/ansible/ansible-modules-extras. 

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by ceving** [comment]
See: https://github.com/ansible/ansible-modules-extras/issues/1792
