### ISSUE TITLE
Command module gives error with Ansible 2.0.0.2

### ISSUE THREAD

**Issue by xuchen81** [ansible/ansible#14425]
The following task:

```
- name: Stop all machine agents.
  command: pkill -f "machineagent.jar" creates=/tmp/machine-agent.pid
  become: yes
```

throws an error:
fatal: [xx.xx.xxx.xx]: FAILED! => {"changed": true, "cmd": ["pkill", "-f", "machineagent.jar"], "delta": "0:00:00.012053", "end": "2016-02-10 23:30:38.731785", "failed": true, "rc": 1, "start": "2016-02-10 23:30:38.719732", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}

However, if I ssh into my instance, and do:
sudo pkill -f "machineagent.jar", there is no problem at all.

I think the problem is in ansible, I was trying to pkill a process that can not be found, but this should not throw me an error, just like manually running it on the instance does not throw an error.

Any ideas?

Thanks

**Comment by abadger** [comment]
`pkill -f nonexistent` is erroring out on you.  If you take a look, the returncode (rc) is 1.  To see the equivalent in your ssh session do:

```
$ sudo su -
# pkill -f "machineagent.jar"
# echo $?
1
```

The standard for unix commands is to return an exit code of 0 on no error and a numeric value (which may have a specific meaning if you read the program's documentation) on errors.

If you want to ignore all errors from pkill then you need to use `ignore_errors: False` with the task like this:

```
- name: Stop all machine agents.
  command: pkill -f "machineagent.jar" creates=/tmp/machine-agent.pid
  become: yes
  ignore_errors: False
```
