### ISSUE TITLE
Regression with template lookup between ansible 1.9 and 2.0

### ISSUE THREAD

**Issue by amarao** [ansible/ansible#14440]
After upgraging from ansible 1.9 to 2.0 lookup for template silently stops searching for template in files directory.

```
- name: Creating VM
  virt: command=define guest={{hostname}} xml="{{lookup('template', 'domain.xml.j2')}}"
  delegate_to: '{{hypervisor}}'
```

domain.xml.j2 was stored in 'files' directory. It worked in 1.9 but broke in 2.0 with message: 

```
fatal: [dev-1]: FAILED! => {"failed": true, "msg": "ERROR! the template file domain.xml.j2 could not be found for the lookup"}
```

after moving files/domain.xml.j2 to template/domain.xml.j2 it start to work.

But I think, without deprecation warning this is a clear regression.

corresponding launchpad bug: https://bugs.launchpad.net/ubuntu/+source/ansible/+bug/1544628

**Comment by bcoca** [comment]
This is not silent, template should have been looking in `templates/` dir not in `files/` dir, this was a bug which is now fixed.
