### ISSUE TITLE
race condition with fact cache and smart fact gathering causes undefined variable errors.

### ISSUE THREAD

**Issue by MichaelBaydoun** [ansible/ansible#14456]
##### Ansible Configuration:

No changes, fact caching worked in 1.9.4 but is experiencing problems in 2.0.0.2

Fact caching settings in ansible.cfg

fact_caching = jsonfile
fact_caching_connection = ~/.ansiblecachedir
fact_caching_timeout = 10800
gathering = smart
##### Environment:

Control server is RedHat 6, target hosts are a collection of rhel5/6 and win2008/2012
##### Summary:

Fact caching worked in 1.9.4, but is having issues in 2.0.0.2.
Site runs fail at random places and random hosts with undefined variables that are really facts, and that were defined and used earlier during the site run.
##### Steps To Reproduce:

During a long site.yml run, ours takes almost two hours, we gather facts at the top and cache them, and the cache timeout is set to three hours.
Every two hour site run fails at random places and random hosts with undefined variables that are really facts, and that were defined and used without error earlier during the site run.
Disable fact caching and the errors go away.
Limit the site run to a subset of hosts or tags, which makes runs much faster, and the problem doesn't occur
##### Expected Results:

Fact variables are not forgotten
##### Actual Results:

Hosts error with undefined variables that are facts during longer runs, that were defined earlier in the run, and that shouldn't have expired.

**Comment by MichaelBaydoun** [comment]
I figured out what's happening here, but not how to fix it.  There is a flaw in the smart fact gathering design.  

At the start of a multi-play playbook run such as the typical site.yml, if previously cached facts have not expired, they will not be regathered.  Then, if they expire later during the playbook run, no attempt is made to refresh them, and the undefined variable error occurs.  

From the documentation "The value ‘smart’ means each new host that has no facts discovered will be scanned, but if the same host is addressed in multiple plays it will not be contacted again in the playbook run."

It wouldn't really matter what timeout value is used for fact_caching_timeout, the potential for this condition still exists.

Evidence that this happened.  Running 2.0.1.0 now, turned fact caching back on to test, issue reappears.

One of the hosts that just failed, with an undefined ansible_system fact

```
12:33:54            TASK [splunk : install splunk] *************************************************
12:33:54            Monday 09 May 2016  12:33:54 -0400 (0:00:00.535)       0:33:37.157 ************ 
12:33:54            fatal: [wdv-servicessbx]: FAILED! => {"failed": true, "msg": "The conditional check 'ansible_system == 'Linux'' failed. The error was: error while evaluating conditional (ansible_system == 'Linux'): 'ansible_system' is undefined\n\nThe error appears to have been in '/home/icansible/ansible/roles/splunk/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- include: linux.yml\n  ^ here\n"}
```

Looking in the cached file directory, the failed server hadn't been updated in the most recent execution, which launched at 12:00, because the file was not quite old enough yet, it was 2 hours 46 minutes old, our timeout is set  to 3 hours

```
-rw-rw----.  1 icansible icansible   926 May  9 09:14 wdv-servicessbx
```

But, the site run failed at 12:33 because the fact file was now over 3 hours (10,800 seconds) old.

The only behavior I can't explain, is why we never saw this problem in 1.9.4 but see it in frequently starting with 2.0

**Comment by MichaelBaydoun** [comment]
Changed issue title to more accurately reflect the issue, now that it's been identified.

**Comment by jctanner** [comment]
Suspected culprit https://github.com/ansible/ansible/commit/0aa018337afbc061633d9046109f12d4dd929c25 which fixed https://github.com/ansible/ansible/issues/12722

**Comment by MichaelBaydoun** [comment]
Note: We are using file (json) caching.  For anyone having this problem, until the commit makes the 2.1 release, a suggested workaround is to switch from smart to explicit, and explicitly call setup once at the start of your playbook.

I'm not entirely clear how redis or other caching systems are working, but I believe they will see the same issue, and the fix committed above only covers json caching behavior.

**Comment by prutseltje** [comment]
Generating my /etc/hosts file in ansible2 fails. But only when playbook runs for a few minutes and then generates the /etc/hosts file. When running task direct with corresponding tag the /etc/hosts is generated without any issue.

fatal: [host]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'ansible_ssh_host'"}

ansible (2.1.0.0)
gathering = smart
fact_caching = redis
fact_caching_timeout = 86400
