### ISSUE TITLE
Ansible 2 freezes with Mikrotik devices

### ISSUE THREAD

**Issue by danpospisil** [ansible/ansible#14487]
We use Ansible in our company to manage Mikrotik AP, but it has stopped working since Ansible 2 - Ansible just hangs on execute statement.

Example task:

```
  tasks:
  - name: Indetify
    raw: /system identity print
```

Result:

```
TASK [Indetify] ****************************************************************
task path: /media/sf_ansible-mikrotik/connection_test.yml:8
<XXX.XXX.XXX.XXX> ESTABLISH CONNECTION FOR USER: user on PORT 22 TO XXX.XXX.XXX.XXX
<XXX.XXX.XXX.XXX> EXEC /system identity print
```

That's it ... I have done some testing and found out that it freezes on this line in ansible/plugins/connection/paramiko_ssh.py:
`stdout = ''.join(chan.makefile('rb', bufsize))`
So I ran some other tests and with diff I found out that in version prior to 2 the command was executed before line setting PTY. In 2+ the command is executed after that line, so it somehow messes with the output and thus Ansible freezes.
So if I comment out this:

```
        if C.PARAMIKO_PTY:
            chan.get_pty(term=os.getenv('TERM', 'vt100'), width=int(os.getenv('COLUMNS', 0)), height=int(os.getenv('LINES', 0)))
```

It starts working again.

I even tried to set pty=False in ansible.cfg with no luck.

**Comment by compuguy** [comment]
I can confirm this as well with my ansible playbook. Works fine with 1.9.6, doesn't work with 2.X.

**Comment by deggis** [comment]
I'm experiencing also hangup with ansible 2.2.0/master (with paramiko 2.0.0/master) at line "stdout = ''.join(chan.makefile('rb', bufsize))".

If I call "chan.recv(4096)" with a remote debugger before the hanging call to chan.makefile('rb', bufsize)) I see '[dzdo] password for user:'. Somehow paramiko.ChannelFile.readline hangs even though the doc says it shouldn't require a trailing newline.

**Comment by danpospisil** [comment]
We have solved it with adding this to ansible.cfg:

```
[paramiko_connection]
pty=False
```

Since then, it works again.

**Comment by rdonkin** [comment]
The ansible.cfg change from @danpospisil made this work with a Mikrotik router using Ansible 2.4.3.

Simple test command:

```
ansible -i routers all -m raw -a "executable= /ip addr print" -u admin -c paramiko
```
