### ISSUE TITLE
Ansible hangs trying to install oh-my-zsh [Bug report]

### ISSUE THREAD

**Issue by foulowl** [ansible/ansible#14492]
Hello,

Ansible Version: 
2.1.0

Ansible Configuration:
No changes.

Environment:
Debian 8.

Summary:
I'm trying to install oh-my-zsh via ansible. Ansible hangs. 

Steps To Reproduce:
Here's my runbook:
https://gist.github.com/foulowl/9a2b3840428f67a9eb44#file-zsh-yaml
It hangs on the second task. I have let it run for a few hours. No luck. After issuing ctrl+c, I can then ssh to my server and it looks like oh-my-zsh is now installed. This will not work as a solution however. 

I can run the install script manually on the server with no problems. It does not expect any user input.

Here's the output of -vvvv:
https://gist.github.com/foulowl/9a2b3840428f67a9eb44#file-output-of-vvvv

Expected Results:
oh-my-zsh should get installed and Ansible should not hang.

Actual Results:
Ansible hangs. 

Thanks!

**Comment by bcoca** [comment]
so this seems to be an issue with the install.sh script. Ansible is designed to run in batch and if this script expects an interactive terminal (which you have when doing manually) it would cause issues.

**Comment by foulowl** [comment]
The install script never prompts me for anything though. Thus it is not "interactive" in that sense. 

I thought the shell running the script was also non-interactive in the shell sense of the word, as:
"A shell running a script is always a non-interactive shell."
http://www.tldp.org/LDP/abs/html/intandnonint.html

So it doesn't matter if I invoke the script manually or via ansible, any time a script is run the shell is non-interactive.

Unless I'm missing something here. Thanks!

**Comment by abadger** [comment]
The script is prompting for me:

```
$ /tmp/install.sh 
Cloning Oh My Zsh...
Cloning into '/home/badger/.oh-my-zsh'...
remote: Counting objects: 754, done.
remote: Compressing objects: 100% (619/619), done.
remote: Total 754 (delta 17), reused 630 (delta 8), pack-reused 0
Receiving objects: 100% (754/754), 490.58 KiB | 108.00 KiB/s, done.
Resolving deltas: 100% (17/17), done.
Checking connectivity... done.
Looking for an existing zsh config...
Found ~/.zshrc. Backing up to ~/.zshrc.pre-oh-my-zsh
Using the Oh My Zsh template file and adding it to ~/.zshrc
Copying your current PATH and adding it to the end of ~/.zshrc for you.
Time to change your default shell to zsh!
Password:
```

Looks like the culprit here is chsh.

Perhaps the account that you are testing with already uses zsh or you're testing with the root account (which doesn't prompt for a password when using chsh).

**Comment by foulowl** [comment]
I run a playbook first that changes the shell to zsh.

Try testing my playbook with your shell already set to zsh.

I wonder if that is what is happening with ansible though. Maybe it appears to the install script (run via ansible shell module) that the shell is set to /bin/sh or similar. 

Thanks!

**Comment by abadger** [comment]
Okay... Guess I should have read the script closer too.... Down at the end it does this:

```
  env zsh
```

which starts up a non-script zsh shell.  So that will also stop execution waiting for the user to type in a command.

**Comment by abadger** [comment]
A quick git search shows that many people have playbooks to do this and they're just using the git module to clone the repo and then editing files to configure things instead of trying to run the install script.  Perhaps that's the best way to do it.

**Comment by foulowl** [comment]
Hmm, so removing "env zsh" from the script has no effect. Done via sed before running. Ansible still hangs. I do realize that folks have reverse engineered the install script, which I could certainly do, but I want to try and resolve the issue that is occurring here.

**Comment by foulowl** [comment]
Aha, ok so here is what ps tree is showing:
systemd─┬─7*[agetty]
        ├─dhclient
        ├─sshd─┬─sshd───sshd───sh───python───sh───sh───chsh
        │      └─sshd───sshd───zsh───pstree
        └─systemd-journal
So despite me already setting the shell to zsh, it's stuck on chsh.

I should just be able to nuke any reference to chsh in the install script and call it good.

I just wanted to be sure to update this issue with complete information in case other people run into the same issue. :)

**Comment by abadger** [comment]
Thanks @foulowl.

**Comment by ScottG489** [comment]
I believe this issue is still present and is caused by the line "env zsh -l" in the installation script

I'm also running the install via ansible:

```
- name: Install oh-my-zsh
    become: yes
    become_user: me
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    args:
      chdir: /home/me/
```

If I remove the `env zsh -l` line it stops hanging.

I'd be happy to submit a separate issue with more information if that would be helpful.
