### ISSUE TITLE
v2 Callback plugin concern

### ISSUE THREAD

**Issue by bjones** [ansible/ansible#14493]
I tried updating my Slack plugin, similar to the hipchat plugin in the Ansible repo, to run on Ansible 2.1.0 (devel) and noticed an issue attempting to get at the limit (subset) of inventory for the playbook run.  The methodology in the hipchat plugin looks the same as mine, but based on what I see in the Ansible source it looks like it may not be possible to see what limit options were used now.  It is undesirable to simply output the hosts for a play when that could be a rather large list.  Not sure what I've missed, updating the hipchat plugin or documenting more changes necessary would be useful.

**Comment by jhawkesworth** [comment]
@bjones Have a play with context_demo - I am not sure but I think if you use v2_playbook_on_play_start the inventory will have already been limited to whatever -l has been set on the command line.

def v2_playbook_on_play_start(self, _args, *_kwargs):
   hosts = args[0].get_variable_manager()._inventory.get_hosts()

If they aren't have a poke around in the methods available in the variable manager.

I'd suggest asking on ansible development mailing list for stuff like this - I think more people see it than the bug tracker.

**Comment by sivel** [comment]
You may be interested in the following pull request which contains a slack callback plugin that is operational on v2:

https://github.com/ansible/ansible/pull/13408

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
