### ISSUE TITLE
ERROR! failed to transfer file to root@centos67:/root\u0007/root/.ansible/tmp/ansible-tmp-1455628791.1-102858065322850/setup

### ISSUE THREAD

**Issue by velmuruganvelayutham** [ansible/ansible#14503]
I am able to ssh to the remote machine. Also I am able to sftp successfully..
I have even tried with Openssh specific settings as mentioned in the website. [http://docs.ansible.com/ansible/intro_configuration.html#id127](http://docs.ansible.com/ansible/intro_configuration.html#id127)

TASK [setup] *******************************************************************
<166.45.16.96> ESTABLISH SSH CONNECTION FOR USER: root
<166.45.16.96> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/martha/.ansible/cp/ansible-ssh-%h-%p-%r -tt 166.45.16.96 'mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1455628975.54-121125587875243 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1455628975.54-121125587875243 )"'
<166.45.16.96> PUT /tmp/tmp_0NsCj TO /root/.ansible/tmp/ansible-tmp-1455628975.54-121125587875243/setup
<166.45.16.96> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/martha/.ansible/cp/ansible-ssh-%h-%p-%r '[166.45.16.96]'
fatal: [166.45.16.96]: FAILED! => {"failed": true, "msg": "ERROR! failed to transfer file to \u001b[34m\u001b(B\u001b[m\u001b]2;root@centos67:/\u0007\u001b]2;root@centos67:/r\u0007\u001b]2;root@centos67:/ro\u0007\u001b]2;root@centos67:/roo\u0007\u001b]2;root@centos67:/root\u0007/root/.ansible/tmp/ansible-tmp-1455628975.54-121125587875243/setup:\nsftp> put /tmp/tmp_0NsCj '\u001b[34m\u001b(B\u001b[m\u001b]2;root@centos67:/\u0007\u001b]2;root@centos67:/r\u0007\u001b]2;root@centos67:/ro\u0007\u001b]2;root@centos67:/roo\u0007\u001b]2;root@centos67:/root\u0007/root/.ansible/tmp/ansible-tmp-1455628975.54-121125587875243/setup'\n\nOpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014\r\ndebug1: Reading configuration data /home/martha/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 6933\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension \"posix-rename@openssh.com\" revision 1\r\ndebug2: Server supports extension \"statvfs@openssh.com\" revision 2\r\ndebug2: Server supports extension \"fstatvfs@openssh.com\" revision 2\r\ndebug3: Sent message fd 3 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /root size 0\r\ndebug3: Looking up /tmp/tmp_0NsCj\r\ndebug3: Sent message fd 3 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn't stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/root/\033[34m\033(B\033[m\033]2;root@centos67:/\u0007\033]2;root@centos67:/r\u0007\033]2;root@centos67:/ro\u0007\033]2;root@centos67:/roo\u0007\033]2;root@centos67:/root\u0007/root/.ansible/tmp/ansible-tmp-1455628975.54-121125587875243/setup\r\nremote open(\"/root/\033[34m\033(B\033[m\033]2;root@centos67:/\u0007\033]2;root@centos67:/r\u0007\033]2;root@centos67:/ro\u0007\033]2;root@centos67:/roo\u0007\033]2;root@centos67:/root\u0007/root/.ansible/tmp/ansible-tmp-1455628975.54-121125587875243/setup\"): No such file or directory\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n"}

can someone help me to solve this issue ?

Thanks,

**Comment by sivel** [comment]
This appears to be due to a shell config file, printing out a `PS1`/`PROMPT_COMMAND`, while ansible is trying to determine the remote temp directory to use.

You will want to evaluate your `bashrc` and `bash_profile` as well as any other related files to find and remediate the cause to this.

**Comment by velmuruganvelayutham** [comment]
Thanks a ton @sivel  
I have just cleaned up my bashrc file.. 
It is just working as usual now ..
Thanks again...

**Comment by panezhang** [comment]
Thanks a lot, too.

**Comment by bianjp** [comment]
I just met the same problem, and wasted a lot of time trying to solve it.
Finally I found it was caused by the following lines in `~/.bashrc`:

```
# npm auto complete
which npm &> /dev/null && . <(npm completion)
```

Hope it helps for others.

But I'm quite curious about why it breaks ansible, and why ansible cannot give us more explicit clues to figure out the problem.

**Comment by magnusjt** [comment]
Just had the same problem. In my bashrc there was an "echo some_stuff" that broke ansible. I'm also curious, why does this break ansible?
