### ISSUE TITLE
ansible facts not visible when using --step

### ISSUE THREAD

**Issue by benoitTremblay** [ansible/ansible#14515]
When stepping through a playbook some ansible facts are undefined

```
    - name: Create the free disk list from facts
      set_fact: free_disks="{{free_disks}} /dev/{{ item }}"
      with_items: ansible_devices | sort
      when: ansible_devices[item].partitions | length  == 0

```

`fatal: [h39]: FAILED! => {"failed": true, "msg": "ERROR! 'ansible_devices' is undefined"}`

When running the playbook in normal mode (not stepping) the task is executed without problem.

Using ansible v 2.0.0.1 on ubuntu 14.04

**Comment by sivel** [comment]
This would likely happen if you skipped the gather facts (setup) step as that is where the facts are obtained at.

**Comment by benoitTremblay** [comment]
You're right.  I was pressing  <enter> at the first prompt missing the 'y'.  The issue comes from the fact that I was 'tee'ing the output in a log file, missing the prompt (not flushed from tee) until I actually press <enter>. I was always one prompt behind.

Thanks
