### ISSUE TITLE
Setting `become_user: root` should automatically set `become: yes`

### ISSUE THREAD

**Issue by nhooey** [ansible/ansible#14536]
##### Issue Type:

Can you help us out in labelling this by telling us what kind of ticket this this?  You can say:
- Feature Idea
##### Ansible Version:

Ansible 2.0.0.2
##### Ansible Configuration:

Not relevant.
##### Environment:

All environments.
##### Summary:

When you set `become_user: root` without `become: yes`, Ansible does not become root, and doesn't throw any errors or warnings.
##### Steps To Reproduce:

Set `become_user: root` in a playbook and try to write to `/etc` or some other writable-by-root directory.
##### Expected Results:

Ansible should do the smart thing: infer the obvious user intent and set `become: yes` when `become_user: root` is set, or at least throw a warning saying that `become_user: root` will have no effect without `become: root`.
##### Actual Results:

Modules say `Destination /etc not writable` without stating what user was being used, even with verbose flags set with `-vvvv`.

**Comment by amenonsen** [comment]
I would like to be able to just say `become: root`; it's much easier to read than `become: yes`, and this would not break backwards compatibility either. (Setting `become: yes` implicitly on `become_user: root` was discussed and not done on purpose, and now it would break backwards compatibility as well.)

**Comment by bcoca** [comment]
The reason `become_user` does not imply `become` is so users that have become set at inventory level (ansible_become) can still set the user in the play/task.

**Comment by amenonsen** [comment]
@bcoca yes, that's the "not done on purpose" reason that I alluded to above. But do you see any problem with allowing `become: root`, purely as a convenience?

**Comment by bcoca** [comment]
become is a boolean and it gets set/updated from the old sudo/su settings also, I really don't think making it a double for become_user with a quaternary state (we already check for None) as a good thing. As much as that might save some typing ....

**Comment by bcoca** [comment]
I'm going to close this as what is proposed breaks the existing current feature set and overloading become: is not something we want to do either.

**Comment by nhooey** [comment]
What @amenonsen suggested breaks existing feature set, and the original issue doesn't suggest overloading `become`.

Just have `become_user: root` automatically set `become: yes`. It doesn't break anything, and prevents the situation where the user is mislead into thinking that it's working because there is no warning.

**Comment by bcoca** [comment]
it breaks when users have ansible_become set for a subset at host/group level and use become_user to change the default privilege change user for a particular action. 

Hosts that do not have ansible_become set would now automatically use the escalation when it was not intended.

**Comment by nhooey** [comment]
Sorry @bcoca, I hadn't noticed your point earlier with the rest of the messages. That sucks, but it's a valid reason not do this.

I agree with your closing this issue.

**Comment by thorsummoner** [comment]
lets give become a better api with what we have then,
`become: specified`, (also as a configuration option) when become_user is set, become that user, otherwise don't become
`become: True`, become specified user, or root (like normal)
`become: no`, become_user will be ignored like normal, do not become root

**Comment by willthames** [comment]
I've added an [ansible-lint](https://github.com/willthames/ansible-lint) check for this - it's in 3.4.0rc2 which is available through pip. 

3.4.0 proper should be released once I've had a bit more testing.

To clarify, I understand @bcoca's reasons, but for 90+% of cases, when you have `become_user`, you want `become` (and this just enforces making that explicit)
