### ISSUE TITLE
default() filter not working in 2.0.0.2

### ISSUE THREAD

**Issue by pixelrebel** [ansible/ansible#14540]
##### Issue Type:

 Bug Report
##### Ansible Version:

2.0.0.2
##### Ansible Configuration:

default
##### Environment:

OS X 10.10
##### Summary:

In 1.9.4:

```
- set_fact: host="{{ ansible_ssh_host|default(inventory_hostname) }}"
- debug: var=host
```

host would properly return the `inventory_hostname` if `ansible_ssh_host` is null

In 2.0.0.2 it will return null value if `ansible_ssh_host` is null.

**Comment by sivel** [comment]
This has recently been fixed in https://github.com/ansible/ansible/commit/75b6f616190857db6b816096ce39bdaf2c16822a

However it does not appear as though we cherry picked that into the stable-2.0 branch.

cc @jimi-c

**Comment by bcoca** [comment]
closing as per fix reference above
