### ISSUE TITLE
Executing Ansible command with out prompting for password

### ISSUE THREAD

**Issue by johnakash** [ansible/ansible#14575]
##### Issue Type:
- Feature Idea
##### Ansible Version:

```
(ansible 1.9.4)
```
##### Ansible Configuration:

Please mention any settings you've changed/added/removed in ansible.cfg
ask_sudo_pass = No
##### Environment:

OS you are running Ansible: RHEL 7
OS you are managing: RHEL 7
##### Summary:

We need to run an ansible script to check the status of a service on a group of machines with out asking for password. That means we are looking for a solution through which we can pass the password along with the execution or through a password file.
##### Steps To Reproduce:

```
(ansible groupname -s -m shell -a "/etc/init.d/httpd status -uusername -k)
```
##### Expected Results:

ansible localhost -s -m shell -a "/etc/init.d/httpd status" -uusername -k
service httpd running

"Please note that we need to get this with out asking any password"
##### Actual Results:

ansible localhost -s -m shell -a "/etc/init.d/httpd status" -uusername -k
SSH password:
SUDO password[defaults to SSH password]:
service httpd running

What actually happened?
Before getting output ansible asking for user passwords (normal user password and sudo password)

**Comment by MichaelBaydoun** [comment]
For the user, use ssh keys to avoid the user password prompt.  For sudo, you can use "NOPASSWD: ALL" for the user inside the sudoers file

**Comment by amenonsen** [comment]
Just configure password-less SSH (i.e., authentication using an SSH keypair) and/or password-less sudo.

**Comment by johnakash** [comment]
Hi  MichaelBaydoun  &  amenonsen, 

Thanks for your quick response.

Due to some security reasons we are not able to use ssh key based login / pass wordless SSH.

**Comment by MichaelBaydoun** [comment]
What about using --ask-pass and --ask-sudo-pass arguments on the command line, and entering the passwords when prompted.  Does that accomplish what you need?

**Comment by bcoca** [comment]
this is already possible by setting `ansible_password/ansible_ssh_pass` for the connection and `ansible_become_pass/ansible_become_password` for the privilege escalation. You normally want to do this in inventory/host_vars/group_vars but it can be done at any point where you define a var.

I recommend using vault to store the credentials.

**Comment by johnakash** [comment]
Hi MichaelBaydoun  / bcoca,

Could you please provide me the command line for the same?

**Comment by MichaelBaydoun** [comment]
ansible groupname -s -m shell --ask-pass --ask-sudo-pass -a "/etc/init.d/httpd status -uusername -k"

**Comment by johnakash** [comment]
Thanks a lot.
