### ISSUE TITLE
Drink less alcohol while writing documentation

### ISSUE THREAD

**Issue by 0xABAB** [ansible/ansible#14577]
Take a lucky guess as to what is wrong here:

```
In 1.x the precedence is (last listed wins):

then “role defaults”, which are the most “defaulty” and lose in priority to everything.
then come the variables defined in inventory
then come the facts discovered about a system
then comes “most everything else” (command line switches, vars in play, included vars, role vars, etc)
then come connection variables (ansible_user, etc)
extra vars (-e in the command line) always win
```

**Comment by sivel** [comment]
You may find this humorous or even clever, however I do not.

Please drop the sarcasm and offensive language, and provide more specific details about the issue.

If you wish to adhere to normal social guidelines, please feel free to open a new issue with respect for other human beings as well as providing legitimate actionable information.

**Comment by SunDwarf** [comment]
it was a funny title tho

**Comment by 0xABAB** [comment]
Seriously, you can't see what's wrong here? 

Allow me to list a couple of things:
- incorrect English
- inconsistencies
- incompleteness (I can forgive you this one, and it might even be intentional, but with the low quality work you are presenting, it was safer to mention it)

Yes, I laugh about stuff like this with colleagues during lunch breaks. You just make it so easy to shoot holes in your "system" (you see, I put it in quotes, because I don't think it is worthy of the name).

**Comment by MichaelBaydoun** [comment]
Another approach is to submit a pull request with the documentation fixes you propose.

**Comment by ezefranca** [comment]
@sivel 
https://github.com/contact?report=0xABAB
