### ISSUE TITLE
Bogus warning [WARNING]: Consider using apt-get module rather than running apt-get

### ISSUE THREAD

**Issue by 0xABAB** [ansible/ansible#14570]
`[WARNING]: Consider using apt-get module rather than running apt-get`
The semantics of "force" are insufficiently precise to warrant using the apt-get module in the case the -y flag is being used. Doing whatever trivial test you are now using to warn me is treating users like they are idiots, while in fact you are the one who can't write a more involved test, presumably because you don't know how Unix works.

**Comment by amenonsen** [comment]
I'm not fond of those warnings either, so I set `command_warnings=False` in ansible.cfg.

**Comment by 0xABAB** [comment]
I think the concept of a WARNING is great, but incorrect WARNINGs should just be removed and whoever committed this atrocious logic in the first place should get his/her commit rights stripped, but hey, that's just me. 

Perhaps the "fix" for this ticket is just to replace whoever approves commits with someone who actually has some development skills.

**Comment by amenonsen** [comment]
Yes, that's just you, and we've already established that you're incapable of just reporting bugs without being  unpleasant and pointlessly dramatic about it.

**Comment by sivel** [comment]
Per the above there is a method for disabling this warning. If you have constructive ideas on how to keep these warnings but make them better, please feel free to open a new issue with actionable information.
