### ISSUE TITLE
Insecure parameter passing

### ISSUE THREAD

**Issue by 0xABAB** [ansible/ansible#14572]
AFAICT, there is no module to send arguments in a structured fashion using Ansible. This means you are encouraging the development of flawed (due to quoting, spaces, etc.) scripts. 

Python has the subprocess module where they also discourage this kind of semantics. Why you would ever even consider to _not_ offer this structured way of passing parameters can be probably be explained by the fact that you people have no clue as to what you are doing. 

Is there any rationale while you feel especially capable for developing a configuration management tool? Given the tons of issues I have seen (your source code is mostly written by amateurs, for example), I don't see any.

**Comment by amenonsen** [comment]
Arguments are passed to modules as JSON (and results are returned that way as well). If you have found a specific problem "due to quoting, spaces, etc.", please explain what it is, for the benefit of those who do not have your peerless qualifications in software development and civil discourse.

**Comment by sivel** [comment]
This does not appear to actually be a bug report.

If you are able to provide explicit examples and discuss specific problems you see, as opposed to vague statements please feel free to open a ticket with actionable data.
