### ISSUE TITLE
Second level element breaks ternary and default filters

### ISSUE THREAD

**Issue by jjshoe** [ansible/ansible#14585]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 1.9.4
  configured module search path = None
```
##### Summary:

Ternary doesn't work with undefined subkeys
##### Steps To Reproduce:

```
ansible all -m debug -a "msg={{ (empty | length > 0 ) | ternary(empty[0]['another_thing'], fuzzy) | default('2') }}" -e '{"empty":[]}'
```
##### Expected Results:

```
localhost | success >> {
    "msg": "2"
}
```
##### Actual Results:

```
localhost | FAILED => One or more undefined variables: list object has no element 0
```
##### Notes

I get similar behavior when just trying to use defaults to accomplish the same thing:

```
 ansible all -i hosts/hosts.ini -m debug -a "msg={{ empty[0]['another_thing'] | default(fuzzy) | default('2') }}" -e '{"empty":[]}'

localhost | FAILED => One or more undefined variables: list object has no element 0
```

**Comment by jjshoe** [comment]
Not sure if the key is list vs dictionary? This is similar: https://github.com/ansible/ansible/issues/12872

**Comment by sivel** [comment]
From some discovery elsewhere, an `UndefinedError` is often raised from jinja2 anywhere before we can catch it in a test or filter.  Generally speaking, you have to apply a `default` at every level of the var, to prevent this from happening.

Such as something like:

```
((empty|default([]))[0]|default(dict()))['another_thing']|default(fuzzy)
```

We have some strange handling of undefined vars in conditionals (when), but there are some bugs there too: https://github.com/ansible/ansible/issues/14543

**Comment by jjshoe** [comment]
```
ansible all -i hosts/hosts.ini -m debug -a "msg={{ ((empty | default([]))[0]|default(dict))['hi'] | default(fuzzy) }}" -e '{"empty":[]}'
```
