### ISSUE TITLE
win_updates fails to ignore hidden updates

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#14599]
##### Issue Type:
- Bug Report
##### Ansible Version:
- 2.1.0 (devel as of 2016-02-21)

```
ansible 2.1.0
  config file = /scripts/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

Nothing of note.
##### Environment:

Running from an Ubuntu trusty docker container.
##### Summary:

When ansible runs this task:

`- name: install all windows updates
    win_updates:
      category_names: ['Application', 'Connectors', 'CriticalUpdates', 'Definiti
onUpdates', 'DeveloperKits', 'FeaturePacks', 'Guidance', 'SecurityUpdates', 'Ser
vicePacks', 'Tools', 'UpdateRollups', 'Updates']
      status: installed`

The task fails when run against a Windows 10 target, due to an update I've explicitly hidden (using [this tool](https://support.microsoft.com/en-us/kb/3073930)) because it consistently fails to install correctly. When updates are hidden, it's almost always because the update itself is bad. The Ansible task should respect any updates that have been hidden, and the task should not fail because that update fails to install.
##### Steps To Reproduce:

Run the task as described above against a target which has a hidden update. Ansible will attempt to install the update anyway.
##### Expected Results:

Ansible should ignore the hidden updates.
##### Actual Results:

It doesn't, and the task fails, throwing the rest of my playbook off track.

**Comment by nitzmahone** [comment]
Fixed in https://github.com/ansible/ansible-modules-extras/commit/93db039783428e9c4f6da34d0b9e60f579bc9960, cherry-picked to stable-2.0. 

Tested successfully on Server 2016 TP4

Thanks!
