### ISSUE TITLE
Search for local ansible.cfg in upper directories

### ISSUE THREAD

**Issue by sedrubal** [ansible/ansible#14596]
##### Issue Type:
- Feature Idea
##### Ansible Version:

```
ansible 1.9.4
  configured module search path = None
```
##### Ansible Configuration:

The local ansible configuration (in the repository) contains:

``` cfg
[defaults]
inventory      = ./inventory
```
##### Environment:

`N/A`
##### Summary:

Ansible should search for local ansible configs in upper directories to pwd.
##### Steps To Reproduce:
- A repo like this:

``` tree
ansible-repo/
├── ansible.cfg
├── playbook.yml
├── inventory
└── roles
    └── common
        └── tasks
            └── main.yml
```
- With `inventory=./inventory` in `ansible.cfg`

``` sh
cd roles/common
ansible-playbook ../playbook.yml
```
##### Expected Results:

Ansible should evaluate the `ansible.cfg` and find the inventory.
##### Actual Results:

Ansible doesn't evaluate the `ansible.cfg` and asks:

``` sh
$> ansible-playbook  ../playbook.yml --check -vvvvvvvvvv

PLAY [ansible-test] ******************************************************* 
skipping: no hosts matched

PLAY RECAP ********************************************************************
```

**Comment by bcoca** [comment]
This is not a good practice, downward looking is normally OK, upward looking opens you up to many issues.

**Comment by sedrubal** [comment]
But ansible could search for a config inside the playbook dir...

**Comment by bcoca** [comment]
Already proposed, but it gets complicated, for example which config do i use in this case:

`ansible-playbook play.yml otherdir/play.yml`

**Comment by sedrubal** [comment]
I see... The easiest way might be that ansible-playbook starts another ansible playbook instance for each playbook with the config from each playbook dir...

**Comment by bcoca** [comment]
I'm not even going to start to explain the issues we run into there ....

so closing this as I don't see any good way to implement it nor a pressing need for this feature, but a whole lot of issues that it will raise

**Comment by sedrubal** [comment]
ok ;)
