### ISSUE TITLE
Ansible role Blockinfile error

### ISSUE THREAD

**Issue by ectorr** [ansible/ansible#14605]
hi, ive installed in a Ubuntu server a Ansible.

i did this playbook:

`- hosts: local`
  `user: root`

`roles:`
 `- yaegashi.blockinfile`
  `tasks:`
`- name: prueba`
    `blockinfile:`
       `dest: /etc/hosts`
     `block: |`
       `pruebaaa`
and the output is: 

`ERROR: blockinfile is not a legal parameter in an Ansible task or handler`

I istalled the role Blockinfile with: ansible-galaxy install yaegashi.blockinfile..

I dont kow where is the error... any suggestion?

**Comment by ectorr** [comment]
this playbook works in other ubuntu server.. I dont undertand anything :-1:

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by dinesh2303** [comment]
https://github.com/yaegashi/ansible-role-blockinfile/issues/15
