### ISSUE TITLE
Ansible falsesly assumes "False" when the variable is "NO"

### ISSUE THREAD

**Issue by ringe** [ansible/ansible#14606]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
```
##### Ansible Configuration:

[defaults]
display_skipped_hosts = False
hostfile = ./hosts
remote_user = root
nocows = 1
forks = 50
pipelining = True
log_path = ./log
##### Environment:

Running in Ubuntu 15.04
Managing Debian 8.3 (Jessie)
##### Summary:

Can't create self-signed certificate using country-code "NO".
##### Steps To Reproduce:

group_vars/all:

```
ispmail_certificate_country: NO
ispmail_certificate_state: Nordland
ispmail_certificate_location: Narvik
ispmail_certificate_organisation: voit.no
ispmail_certificate_orgunit: Voit AS
ispmail_certificate_domains:
  - mx.voit.no
ispmail_certificate_email: postmaster@voit.no
ispmail_certificate_days_valid: 3650
```

Playbook.yml:

```
- name: Create a self-signed certificate
  command: >
    openssl req -newkey rsa:4096
      -nodes -sha512 -x509
      -days {{ ispmail_certificate_days_valid }}
      -nodes
      -subj '/C={{ ispmail_certificate_country }}/ST={{ ispmail_certificate_state }}/L={{ ispmail_certificate_location }}/O={{ ispmail_certificate_organisation }}/OU={{ ispmail_certificate_orgunit }}{% for domain in ispmail_certificate_domains %}/CN={{ domain }}{% endfor %}/emailAddress={{ ispmail_certificate_email }}'
      -out /etc/ssl/certs/mailserver.pem
      -keyout /etc/ssl/private/mailserver.pem
  args:
    creates: /etc/ssl/certs/mailserver.pem

```
##### Expected Results:

Expected the certificate to be created with the given variables.

```
TASK [ispmail-certificate : Create a self-signed certificate] ******************
changed: [mailserver]
```
##### Actual Results:

Certificate failes, because Ansible passes "False" instead of "NO" to the openssl command.

```
TASK [ispmail-certificate : Create a self-signed certificate] ******************
fatal: [mailserver]: FAILED! => {"changed": true, "cmd": ["openssl", "req", "-newkey", "rsa:4096", "-nodes", "-sha512", "-x509", "-days", "3650", "-nodes", "-subj", "/C=\"False\"/ST=Nordland/L=Narvik/O=voit.no/OU=Voit AS/CN=mx.voit.no/emailAddress=postmaster@voit.no", "-out", "/etc/ssl/certs/mailserver.pem", "-keyout", "/etc/ssl/private/mailserver.pem"], "delta": "0:00:00.983944", "end": "2016-02-22 09:13:55.957780", "failed": true, "rc": 1, "start": "2016-02-22 09:13:54.973836", "stderr": "Generating a 4096 bit RSA private key\n...........................................++\n.............................................................................++\nwriting new private key to '/etc/ssl/private/mailserver.pem'\n-----\nproblems making Certificate Request\n139889038505616:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:a_mbstr.c:154:maxsize=2", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by sivel** [comment]
The YAML spec specifies that the bare word `NO` is a Boolean `False` value.  http://yaml.org/type/bool.html

The solution to getting the value to not be evaluated as a Boolean is to quote it, such as `"NO"`

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by ringe** [comment]
~~The solution you suppose does not work. Try for yourself.~~

Well, I guess I have to back down on that. I tried quoting in the wrong place.
Quotes in the `group_vars/all` made for a correct outcome.

Thanks.

**Comment by bcoca** [comment]
`var: !!str "no"`
