### ISSUE TITLE
Ansible 2.0.0.2 - regression - included handlers are not imported/triggered/called properly

### ISSUE THREAD

**Issue by marcosdiez** [ansible/ansible#14611]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

no changes. All I did was:

```
ubuntu 15.10# apt-get install ansible;  # to get version 1.9.2
virtualenv env;source env/bin/virtualenv;pip install ansible # to get version 2.0.0.2
```
##### Environment:

Ubuntu 15.10, but I believe this is not platform specific
##### Summary:

Ansible 2.0.0.2 does not include handlers properly.
The same command work as expected with Ansible 1.9.2 (and the current documentation)
I am showing the output of both to make my point more clear
##### Steps To Reproduce:

Since we are talking about including files, two files are necessary:

```
#----------- site.yml ------------
- hosts: all
  tasks:
  - debug: var="ansible_version['string']"
  - command: "echo main_command"
    notify: this_is_a_handler
  handlers:
  - include: sample_tasks.yml
#----------- site.yml ------------
```

and

```
#---------- sample_tasks.yml -----

---
  - name: this_is_a_handler
    command: "echo handler"
#---------- sample_tasks.yml -----
```

now one must type:

```
ansible-playbook.yml site.yml
```
##### Expected Results:

 this is the actual output from Ansible 1.9.2, where this works

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [debug var="ansible_version['string']"] *********************************
ok: [localhost] => {
    "var": {
        "ansible_version['string']": "1.9.2\n  configured module search path = None"
    }
}

TASK: [command echo main_command] *********************************************
changed: [localhost]

NOTIFIED: [this_is_a_handler] *************************************************
changed: [localhost]

PLAY RECAP ********************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0

```
##### Actual Results:

What actually happened?

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "ansible_version['string']": "2.0.0.2"
}

TASK [command] *****************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0

```

Please notice that no NOTIFIED has been triggered.

**Comment by sivel** [comment]
This is a known limitation in ansible 2.0 and was documented at https://www.ansible.com/blog/ansible-2.0-launch

> Handlers in includes will not be seen when a task attempts to notify them, so handlers should avoid using includes at this time.

As well as being documented at http://docs.ansible.com/ansible/playbooks_intro.html#handlers-running-operations-on-change

> You cannot notify a handler that is defined inside of an include

**Comment by sivel** [comment]
If you have further questions please stop by IRC or the mailing list:
- IRC: #ansible on irc.freenode.net
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by marcosdiez** [comment]
Hello @sivel 

Thanks for the quick answer.
It is a real pitty that one can not include handlers anymore. It was a very useful tool which I will miss.

By the way, shouldn't ansible-playbook stop if a handler can not be found ? 
For me it seems that silently going on is breaks the principle of least astonishment. 
(https://en.wikipedia.org/wiki/Principle_of_least_astonishment)

Also, there is a part in the documentation where it does say what I expected is possible. Maybe that should be fixed:

http://docs.ansible.com/ansible/playbooks_roles.html#task-include-files-and-encouraging-reuse

---

And in your main playbook file, just include it like so, at the bottom of a play:

```
handlers:
  - include: handlers/handlers.yml
```

---

Thanks !
