### ISSUE TITLE
Inconsistent reordering of child group names in inventory file

### ISSUE THREAD

**Issue by andor-kesselman** [ansible/ansible#14613]
##### Issue Type:

Please pick one and delete the rest:
- Bug Report
##### Ansible Version:

ansible 1.9.2
  configured module search path = None
##### Ansible Configuration:

default settings
##### Environment:

MacOSX Yosemite
##### Summary:

Ansible is reordering the group names for the children in the inventory file. 
##### Steps To Reproduce:
1. Create test inventory file

```
[southwest]
"Server1" ansible_ssh_host=192.168.**.** ansible_ssh_pass=****
"Server2" ansible_ssh_host=192.168.**.**  ansible_ssh_pass=**** 

[east]
"Server3" ansible_ssh_host=192.168.**.** ansible_ssh_pass=**** 

[regional:children]
southwest
east
```
1. Create playbook that accesses group names. 

```
- hosts: regional
  tasks:
    - name: Push temporary query to server
      copy: ***
      register: copy

    - name: Run Scripts
      command: ***
      register: run

    - name: Print Standard Out
      debug: msg="{{ run.stdout }}"

    - name: Print Group Names 
      debug: msg="{{ group_names }}"
```
##### Expected Results:

What did you expect to happen when running the steps above?

That the group ordering would be consistent across groups. i.e. Server 1, 2, and 3 go from regional to sub-region. 

What actually happened?

```
TASK: [Print Group Names] ***************************************************** 

ok: [Server2] => {
    "msg": "['regional', 'southwest']"
}
ok: [Server3] => {
    "msg": "['east', 'regional']"
}
ok: [Server1] => {
    "msg": "['regional', 'southwest']"
```

**Comment by bcoca** [comment]
So I'm going to 'reverse' this bug and I fixed the corner case in 2.0 in which this var was unsorted, closed via d6546a75134c0498e6c46372d20a297f64356a20

**Comment by Anvesh42** [comment]
Guys, I am now experiencing the same problem in V 2.1.0. As the same case above
`[pcte:children]`
`cte8`
`[cte8]`
`thehost ansible_ssh_host=10.2.131.26 ansible_ssh_user=someuser1`

Now, the when I run
`{{hostvars[inventory_hostname].group_names`, it outputs

`TASK [debug] *******************************************************************`
`ok: [thehost] => {`
`"msg": [`
`"cte8",`
`"pcte"`
`]`
`}`

Now, when I make some some changes in some syntax in the inventory (which I shouldn't be doing)

`[cte-p:children]`
`cte8`
`[cte8]`
`thehost ansible_ssh_host=10.2.131.26 ansible_ssh_user=someuser1`

output:
`TASK [debug] *******************************************************************`
`ok: [thehost] => {`
`"msg": [`
`"cte-p",`
`"cte8"`
`]`
`}`

I dont understand this strange behavior. The output always has to be consistent in the order of parent --->children. I mean, the value of group_names[0] should always be parent and group_names[1] should follow the child groups

**Comment by Anvesh42** [comment]
[more explanation here](http://stackoverflow.com/questions/40869376/inconsistent-ordering-of-parentchild-group-names-in-inventory-file)
