### ISSUE TITLE
Let the inventory file location be a directory

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1461]
If the file is a directory, run all items within it, whether script or INI file, and blend the results.

This will allow the inventory directory to be used in conf.d form, or even one group per file.

It will also allow for hybrid EC2/local inventory, etc.

**Comment by skvidal** [comment]
if this works it would definitely solve a problem for me. I could create an instance using a simple, generic playbook. Then start a new playbook targetting that new instance which would magically show up in the next inventory object creation of a new playbook process...

**Comment by mpdehaan** [comment]
The risk of doing it that way is, eventually, you'd get a pretty
unmanagable /etc/ansible/hosts/ directory as you provisioned over time, and
might have to reorganize them.

However, it would allow you to use to have a inventory file and a seperate
inventory script hitting some other dynamic data source, too.

What if, in addition to doing this, we write a new inventory source plugin
that allows for easy hierarchical tree based organization, where you could
add hosts to groups by adding the host definition in the right subdirectory
(or even using symlinks)?

**Comment by mpdehaan** [comment]
Any statement of "we" should not be construed as "this is in plan here".

This may also be cleaner if we just allow a list of seperated inventory files and scripts, and then they wouldn't have to be physically located together.   _that_ should be in plan, I think

**Comment by mpdehaan** [comment]
I think what will happen here instead is ansible-commander will have a DB inventory source that can sync from running against various existing inventory scripts.
