### ISSUE TITLE
Mount a volume based on Size

### ISSUE THREAD

**Issue by gvenka008c** [ansible/ansible#14627]
Is there any documentation on how to mount a volume based on Size?

currently we are mounting as below
- name: e2label the device
  shell: /sbin/e2label /dev/vdb /srv
  tags: mount_docker_fs
- name: mount /dev/vdc to /srv
  mount: name=/srv src='LABEL=/srv' fstype=ext4 dump=1 passno=2 state=mounted
  register: mount_success
  tags: mount_docker_fs

Any way we can mount based on size?

**Comment by gvenka008c** [comment]
Posted my query on the Groups channel but didn't get any response.

https://groups.google.com/forum/#!searchin/ansible-project/mount$20volumes/ansible-project/tdx3dVoMZm8/eNrmT-6RAQAJ

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
