### ISSUE TITLE
Invoking playbooks using the dynamic inventory AWS script fails from time to time

### ISSUE THREAD

**Issue by berinle** [ansible/ansible#14667]
##### Issue Type:

Bug Report
##### Ansible Version:

```
2.0.0.2
```
##### Environment:

N/A
##### Summary:

Running the ansible-playbook with ec2.py inventory script almost always fails from time to time, mostly on the first invocation after a period of time. Executing the same command again works.
Executing the script manually (`./ec2.py`) works without errors everytime
##### Steps To Reproduce:

```
ansible-playbook -i ec2.py test.yml -e @env.yml
```
##### Expected Results:

It should run successfully with each invocation
##### Actual Results:

```
ERROR! The file playbooks.d/inventory/ec2.py is marked as executable, but failed to execute correctly. If this is not supposed to be an executable script, correct this with `chmod -x playbooks.d/inventory/ec2.py`.
ERROR! failed to parse executable inventory script results from /home/ec2-user/deployer/ec2.py: ERROR! Syntax Error while loading YAML.


The error appears to have been in '<string>': line 3, column 21, but may
be elsewhere in the file depending on the exact syntax problem.

ERROR! ec2.py:3: Error parsing host definition ''''': No closing quotation
```

**Comment by bcoca** [comment]
it seems like the script is emitting invalid JSON at one point, probably emitting a premature end of file.

**Comment by berinle** [comment]
I'm not really sure what happened, but since moving to a pristine host for running the playbooks, these errors have seized. I have not experienced a single occurrence, so probably something wrong with the box I was initially using. I'll close this for now and reopen if I encounter it again.

**Comment by empiricalthought** [comment]
I suffered this same issue; the cause was that the `.boto` configuration file being used had debugging enabled.  This made the script output AWS logging where only JSON was expected.

Since the subsequent calls only retrieve data from cache, no AWS logging output is generated. This explains why it works after the first failure.

**Comment by snoopdouglas** [comment]
For those coming here when getting exactly this issue with the **DigitalOcean** dynamic inventory script, make sure your API token is set.

**Comment by ghost** [comment]
I get the the error notification when running the inventory script using ansible or invoking it from the command line as an executable. For me the error occurs persistently, i.e. doesn't disappear after a few tries.

My fix is directly from [Effi Bar-She'an's](http://stackoverflow.com/users/2638505/effi-bar-shean) answer here: http://stackoverflow.com/a/35894082

In short, AWS needs the the client time to be updated:
`sudo date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"`

I'm working on a Vagrant VM on MacBook Pro OS X El Capitan 10.11.4, I've noticed a rough pattern of this happening after I bring my MacBook back from sleep or leave it idle over night - perhaps affects VM's time settings.

**Comment by campeterson** [comment]
You might also see this error if you're using Python 3. Use Python 2.x

See: [Question, why not to upgrade to Python 3?](https://github.com/ansible/ansible/issues/1409)

**Comment by ghost** [comment]
I am getting this error on Google Cloud Shell with python 2.7.9 and Debian 3.16.7-ckt25-2+deb8u3 with Ansible 2.1.0.0 installed via pip.

Also josh's solution didn't help. I have removed the initial comment from gce.py within ''' but I got different error so something else is completely wrong now.

**Comment by ghost** [comment]
Same issue on Ubuntu Desktop 16.4 = cannot use GCE at all.

```
ERROR! The file inventory/gce.py is marked as executable, but failed to execute correctly. If this is not supposed to be an executable script, correct this with `chmod -x inventory/gce.py`.
Inventory script (inventory/gce.py) had an execution error:  
inventory/gce.py:19: Error parsing host definition ''''': No closing quotation
```

**Comment by simplycycling** [comment]
Same on Mac OS X:

> ERROR! The file inventory/gce.py is marked as executable, but failed to execute correctly. If this is not supposed to be an executable script, correct this with `chmod -x inventory/gce.py`.
> Inventory script (inventory/gce.py) had an execution error:  
> inventory/gce.py:19: Error parsing host definition ''''': No closing quotation
> 
> $ ansible --version
> ansible 2.1.0.0

**Comment by ghost** [comment]
Hm, so I came to a conclusion that this breaks on random. It works for a while, then I'll get these errors all the time. Very very strange. I feel like it has something to do with editing files(even the gce.ini, not even the gce.pu). Maybe changed timestamp on a file does something..

PS: yes, I know I'm talking about GCE and not EC2 but it is the same issue.

**Comment by simplycycling** [comment]
It seems to be working more consistently for me now that I've set up a secrets.py.

**Comment by ghost** [comment]
I have removed spaces, empty lines and quotes from gce.ini and have no issues now. But I'm not 100% sure that was the reason.

**Comment by porto88** [comment]
I also received this error when file line endings were in Windows format, switching back to Unix fixed it.

**Comment by ghost** [comment]
## I got the same issue again when using Windows Subsystem for Linux(ubuntu 16.4).

I fixed it by running `pip install backports.ssl_match_hostname`

**Comment by ALSEDLAH** [comment]
Hello guys 

Currently I'm experiencing the same error, any hints could help to sort it out. The strange thing, when I run the script alone it did work well but when it is executed  via ansible-playbook no :( . I tested it on to different systems CentOS and Debian in vain.
- Ansible v 2.1.1.0

**Comment by tabibazar** [comment]
It is the line endings in ec2.py and ec2.ini. After changing them to LF. It all worked. Also make sure that /usr/bin/python is version 2.4 or higher.

**Comment by groenator** [comment]
@tabibazar what do you mean by changing them to LF? I am using Mac, not sure how much this would help. 

can yo share some instructions?

**Comment by tabibazar** [comment]
@groenator there two possible ways one is git config that auto changes line ending, the other is your IDE that could re-ecode the line endings. Just make sure that the those files have the line endings are LF (linefeed). I have included links for git and pycharm. I hope that helps

https://help.github.com/articles/dealing-with-line-endings/
https://www.jetbrains.com/help/pycharm/2016.1/configuring-line-separators.html

**Comment by nsushkin** [comment]
Remove EC2 cache directory (~/.ansible/tmp), run the script, and make sure the output is a valid JSON. There may be extra debugging output generated when the script connects to EC2, which would cause ansible to fail parsing JSON, and try to parse the script file as if it was an ini file, failing with a parsing error complaining about the comments in the script file.
