### ISSUE TITLE
"No hosts matched" should return with error code != 0

### ISSUE THREAD

**Issue by lamby** [ansible/ansible#14693]
##### Issue Type:
- Feature Idea
##### Ansible Version:

2.1.0
##### Summary:

I have a "deploy" job in Jenkins but with — for example — a mistyped hostname, the call to `ansible-playbook` will (correctly) print "No hosts matched" but return with an exit code of zero. This seems to violate some kind of UNIX idea, at least in principle.
##### Expected Results:

Return with a non-zero exit code.

**Comment by d3prof3t** [comment]
I am willing to work on it, but don't know where to start. Can someone please help.

**Comment by larsks** [comment]
I think the current behavior is probably correct.  The `no hosts matched` message occurs at the _play_ level, not at the _playbook_ level.  Consider a playbook with multiple plays: 

```
- name: configure webservers
  hosts: webservers
  tasks:
    - debug:
        msg: "I am a webserver"

- name: configure database servers
  hosts: dbservers
  tasks:
    - debug:
        msg: "I ate your data"
```

If you have an inventory file that looks like this:

```
[dbservers]
localhost
```

You'll get the following output:

```
PLAY [configure webservers] ****************************************************
skipping: no hosts matched

PLAY [configure database servers] **********************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "I ate your data"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

The first play doesn't match any hosts (`skipping: no hosts matched`), but _this is not an error_.  It's expected.  That is exactly the situation you are seeing.

**Comment by lamby** [comment]
>  The no hosts matched message occurs at the play level, not at the playbook level.
> [snip the rest]

@larsks Ah, of course. Would you consider it an error if zero plays whatsover were executed over the entire playbook?

@d3prof3t I wouldn't start until a consensus has been reached. You should easily be able to find the code path in question though!

**Comment by larsks** [comment]
> @larsks Ah, of course. Would you consider it an error if zero plays whatsover were executed over the entire playbook?

I was pondering that and the best I've been able to come up with is "maybe".  I guess you could make the behavior conditional on a `--error-if-no-plays` command line option or something like that.

**Comment by lamby** [comment]
Yes, I suspect it would have to be optional at this point. I'll have a poke.

(For the time being—and for the sake of anyone following along—I've temporarily patched the problem in my setup by grepping the Jenkins logs for that line.)

**Comment by d3prof3t** [comment]
@lamby Thanks for the advice. Actually I am completely new as far as contributing to Open Source Projects is concerned. Will keep in mind the next time.

**Comment by asmaier** [comment]
Any progress on this problem?

**Comment by lamby** [comment]
> Any progress on this problem?

Quite. What has happened to Ansible development? It seemed to be so open and quick 18 months ago, now it seems like throwing patches in a black hole.. :(

**Comment by bcoca** [comment]
As posted to #14742, this was discussed in online meetings with core and community and we decided this was not a feature we thought was needed and closed the ticket implementing it. 

For the same reasons I'm going to close this one.
