### ISSUE TITLE
ansible-playbook does not warn if your inventory script does not exist.

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#14692]
##### Issue Type:

- Bug Report
##### Ansible Version:

```
[2016-02-28 06:06:42] $: ansible --version
ansible 2.0.0.2
  config file = /home/carlosnunez/source/namely/sre/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Environment:

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```
##### Summary:

If you provide an inventory script to `ansible-playbook` that doesn't exist, it will continue attempting to execute plays anyway.
##### Steps To Reproduce:
1. Run `ansible-playbook ... -i $path` , where `$path` is your valid inventory script.
2. Wait for playbook to complete.
3. Repeat (1) but with an invalid path.
   ##### Expected Results:

It should display an error telling you that the inventory script is invalid with a warning saying that the provided hosts list is empty.
##### Actual Results:

It continues executing the playbook.

**Comment by bcoca** [comment]
are you not getting this?

`[WARNING]: provided hosts list is empty, only localhost is available`

**Comment by ghost** [comment]
I am, but I feel like this is ambiguous, especially while working with dynamic inventory filters (which might also produce a nil set of hosts.

Is there an option somewhere that throws an error if the `inventory_file` doesn't exist?

**Comment by bcoca** [comment]
added specific warning via badc922

**Comment by ghost** [comment]
Thank you!!

---

Carlos Nunez
Site Reliability Engineer @ Namely
We will make you love HR and Payroll. Find out why: namely.com
