### ISSUE TITLE
Issue with SSH after upgrading ansible to 2.0.1.0

### ISSUE THREAD

**Issue by vishnudxb** [ansible/ansible#14703]
Connecting to the instance (Redhat 7) with become: yes & become_user: root  where root can access the instance with the private key.  

```
- name: Run a role
  hosts: deploy
  become: yes
  become_user: root
```

UNREACHABLE! => {"changed": false, "msg": "SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}

Doing verbose, it shows the below error 
     too long for Unix domain socket\r\n", "unreachable": true

In my ancible.cfg file, I am using
     control_path = %(directory)s/ssh-%%h-%%p-%%r

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

In any case,  I believe you want the following:

```
- name: Run a role
  hosts: deploy
  remote_user: root
```

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
