### ISSUE TITLE
When play task with run_once, Ansible reports all hosts changed.

### ISSUE THREAD

**Issue by gtt116** [ansible/ansible#14719]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 1.9.4
```
##### Ansible Configuration:

```
[defaults]
log_path = ./ansible.log
gathering = explicit
roles_path = roles

[ssh_connection]
ssh_args = -o StrictHostKeyChecking=no
pipelining=true

[privilege_escalation]
become=True
```
##### Environment:

Debian 7
##### Summary:

When play task with `run_once`, Ansible reports all hosts changed.
##### Steps To Reproduce:

```
$ ansible-playbook -i hosts test1.yaml  
```

hosts

```
[all]

ca192
ca193
ca194
```

test1.yaml

```

---
- hosts: all
  tasks:
    - command: hostname
      run_once: True
```
##### Expected Results:

```
PLAY RECAP ******************************************************************** 
ca192                      : ok=1    changed=1    unreachable=0    failed=0   

```
##### Actual Results:

```

PLAY [all] ******************************************************************** 

TASK: [command hostname] ****************************************************** 
<ca192> REMOTE_MODULE command hostname
changed: [ca192] => {"changed": true, "cmd": ["hostname"], "delta": "0:00:00.021611", "end": "2016-03-01 16:45:13.670871", "rc": 0, "start": "2016-03-01 16:45:13.649260", "stderr": "", "stdout": "ca192.cnhz1.163.org", "warnings": []}

PLAY RECAP ******************************************************************** 
ca192                      : ok=1    changed=1    unreachable=0    failed=0   
ca193                      : ok=1    changed=1    unreachable=0    failed=0   
ca194                      : ok=1    changed=1    unreachable=0    failed=0   
```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The run_once feature does restrict the task to actually executing in one host but it applies the results to ALL the hosts, so the output is correct.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
