### ISSUE TITLE
Still seeing issues like: ssl: 500 WinRMTransport. [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

### ISSUE THREAD

**Issue by aguynamedjoetoo** [ansible/ansible#14710]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

Simple controller node talking to a windows machine (running all in EC2)
##### Environment:

Controller node: Amazon Linux 2015.09 with python 2.7.10
Managed Node: Windows 2012 R2 Base with winrm installed and configured for HTTPS with self-signed certificate

Both nodes are joined to the domain and are within a security group that can communicate openly between the two (for debugging I've allowed all traffic between these nodes)
##### Summary:

Facing similar issues to https://github.com/ansible/ansible/issues/10294, but against a windows 2012 R2 machine from python 2.7.10. I'm able to connect and execute things from pywinrm, I'm able to authenticate against kerberos, and use the ticket in pywinrm, but no luck from ansible.
##### Steps To Reproduce:

```
$ ansible tag_os_windows -m win_ping -e ansible_connection=winrm -e ansible_winrm_server_cert_validation=ignore -e ansible_user=admin@CORP.JENGEL.ME -vvvv
No config file found; using defaults
Loaded callback minimal of type stdout, v2.0
<172.31.1.164> ESTABLISH WINRM CONNECTION FOR USER: admin@CORP.JENGEL.ME on PORT 5986 TO 172.31.1.164
172.31.1.164 | FAILED! => {
    "failed": true,
    "msg": "kerberos: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Server not found in Kerberos database', -1765328377)), ssl: 500 WinRMTransport. [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)"
}
```
##### Expected Results:

I attempted a similar process with pywinrm directly:

```
from winrm.protocol import Protocol

p = Protocol(
    endpoint='https://WIN-9LOSPRGSB3J.corp.jengel.me:5986/wsman',
    transport='kerberos',
    username='admin@CORP.JENGEL.ME',
    server_cert_validation='ignore')

shell_id = p.open_shell()

command_id = p.run_command(shell_id, 'ipconfig')

std_out, std_err, status_code = p.get_command_output(shell_id, command_id)

print std_out
```

And was able to connect:

```
$ python kerb.py

Windows IP Configuration


Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : corp.jengel.com
   Link-local IPv6 Address . . . . . : fe80::6d85:63f9:f837:9e96%12
   IPv4 Address. . . . . . . . . . . : 172.31.1.164
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 172.31.0.1

Tunnel adapter isatap.ec2.internal:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : corp.jengel.com
```
##### Actual Results:

Ansible fails in the WinRMTransport with a certificate verification error.

```
$ ansible tag_os_windows -m win_ping -e ansible_connection=winrm -e ansible_winrm_server_cert_validation=ignore -e ansible_user=admin@CORP.JENGEL.ME -vvvv
No config file found; using defaults
Loaded callback minimal of type stdout, v2.0
<172.31.1.164> ESTABLISH WINRM CONNECTION FOR USER: admin@CORP.JENGEL.ME on PORT 5986 TO 172.31.1.164
172.31.1.164 | FAILED! => {
    "failed": true,
    "msg": "kerberos: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Server not found in Kerberos database', -1765328377)), ssl: 500 WinRMTransport. [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)"
}
```

---

Sorry if maybe a bug report wasn't appropriate for this but there doesn't appear to be a lot of documentation out there regarding this error, and none of the open github issues seem to point that this should be an issue anymore, yet here I am facing it :P

**Comment by sivel** [comment]
I believe in order to ignore the ssl certification validation, you must set `ansible_winrm_transport=ssl`.  I do not see use of that inventory variable in your command.

**Comment by aguynamedjoetoo** [comment]
Hey @sivel, thanks for the prompt reply. Still getting the same error unfortunately (I also realise doing all these -e flags aren't standard, that's also more for my own debugging haha):

```
$ ansible tag_os_windows -m win_ping -e ansible_connection=winrm -e ansible_winrm_server_cert_validation=ignore -e ansible_user=admin@CORP.JENGEL.ME -e ansible_winrm_transport=ssl -vvvv
No config file found; using defaults
Loaded callback minimal of type stdout, v2.0
<172.31.1.164> ESTABLISH WINRM CONNECTION FOR USER: admin@CORP.JENGEL.ME on PORT 5986 TO 172.31.1.164
172.31.1.164 | FAILED! => {
    "failed": true,
    "msg": "kerberos: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Server not found in Kerberos database', -1765328377)), ssl: 500 WinRMTransport. [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)"
}
```

**Comment by aguynamedjoetoo** [comment]
Oh, one thing I forgot to mention, looking at my event logs for that machine, I'm getting Event ID: 36887 at the exact times I'm running this Ansible command. I don't receive this error in my event log, however, when running the python script above for pywinrm

More detailed (if you could call it that):

```
A fatal alert was received from the remote endpoint. The TLS protocol defined fatal alert code is 48.
```

Looking up that on Microsoft's resources proves equally descriptive...

**Comment by nitzmahone** [comment]
@Joeskyyy At least the way things are right now, you won't be able to set ansible_winrm_server_cert_validation with -e... We're doing some funky stuff to pick it out of inventory (may be revamping that in 2.1), but currently that value can _only_ be set in your inventory. 

If moving that doesn't fix your issue, can you try using a local user and see if it works that way? Just want to eliminate a few possibilities...

**Comment by aguynamedjoetoo** [comment]
@nitzmahone Thanks for the reply!

Trying out a super basic inventory file for now for testing:

```
172.31.1.164 ansible_connection=winrm ansible_user=admin@CORP.JENGEL.ME ansible_password=<redacted> ansible_winrm_server_cert_validation=ignore ansible_winrm_transport=ssl
```

And no dice when it comes to an AD user (verified I have a kerberos ticket for the user in question):

```
$ ansible all -m win_ping -vvvv
No config file found; using defaults
Loaded callback minimal of type stdout, v2.0
<172.31.1.164> ESTABLISH WINRM CONNECTION FOR USER: admin@CORP.JENGEL.ME on PORT 5986 TO 172.31.1.164
172.31.1.164 | FAILED! => {
    "failed": true,
    "msg": "ssl: 401 Unauthorized."
}
```

Using a local user, however:

```
$ ansible all -m win_ping
172.31.1.164 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
```

**Comment by jhawkesworth** [comment]
definitely worth a try without ansible_winrm_transport=ssl

Its been a little while since I've looked at the winrm connection plugin
but I think it will need to be kerberos for a domain user.

Server not found in kerberos database could be evidence that dns isn't
working 'both ways' i.e. forward and reverse dns lookups need to be
consistent. Looks like perhaps you are past that problem though.

Jon

**Comment by aguynamedjoetoo** [comment]
hmmm @jhawkesworth may be onto something. When I change that transport level to 'kerberos' now I'm only left with a kerbos sided issue:

```
$ ansible all -m win_ping -vvvv
No config file found; using defaults
Loaded callback minimal of type stdout, v2.0
<172.31.1.164> ESTABLISH WINRM CONNECTION FOR USER: admin@CORP.JENGEL.ME on PORT 5986 TO 172.31.1.164
172.31.1.164 | FAILED! => {
    "failed": true,
    "msg": "kerberos: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Server not found in Kerberos database', -1765328377))"
}
```

But that still doesn't explain why I can contact kerberos outside of ansible :\

**Comment by aguynamedjoetoo** [comment]
Hmm, yeah, using the DNS name directly appears to be working over using the raw IP, which may just be an issue with my DNS. I'll dig further at this on my end. Huge thanks @jhawkesworth 

Side question, all related to this if I may @nitzmahone ... I may be completely daft here, but I'm not seeing a working example of using ec2.py (masked as /etc/ansible/hosts) and using host variables such as `ansible_winrm_server_cert_validation` will I have to do this in every playbook that I construct? Or is there a way to have these variables set when ansible runs ec2.py?

**Comment by aguynamedjoetoo** [comment]
Supplemental update:

It was indeed my rdns not being configured properly (additionally my kerberos config ignoring rdns record translation). So I'm up and running with a static inventory file. So I suppose some clarity in documentation on how the variables like `ansible_winrm_server_cert_validation` are handled may be in order?

Still looking for a way for dynamic inventory as well, if the answer is ensuring it in every playbook that's perfectly fine, just want to know if there's a better practice.

**Comment by nitzmahone** [comment]
Yeah, the docs are still a little sketchy on all that. Best way to handle that for dynamic inventory is with a "stub" static inventory that maps your dynamic group names in, then set the connection vars against "human-readable" groups in the static inventory or with group_vars. Also, of course, write your playbooks against the human-readable mapped group names defined in the static part instead of "tag_foo_bar". Then when you run, give the directory that has both the static and dynamic inventory to -i instead of just one or the other, and it'll automatically merge everything together.

So, we good to close this issue?

**Comment by aguynamedjoetoo** [comment]
@nitzmahone Sounds excellent.

Thanks again for all the help. (:

**Comment by ssbarnea** [comment]
Can we please reopen this bug. Even after reading the entire thread I am not able to understand why I get this error and what I am supposed to do to fix it.

After I spent more than an hour in order to succesfully execute the powershell configuring script on the target machine I was hopping to be succesfull to make ansible to connect to the machine (windows 10).

I did configure all the parameters inside the group_vars and they are loaded.

```
ansible_user: xxx
ansible_password: yyy
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: ssl
```

**Comment by nitzmahone** [comment]
That looks correct for Ansible 2.0+ (though the winrm_transport and ansible_port should not be necessary in this case). Are you sure you're using pywinrm 0.1.1?

**Comment by RaghavendraP** [comment]
Hi,

You have to give FQDN (fully qualified domain name) for windows server if you want to use kerberos authentication in ansible. I tried with IP and got the same error which you listed and then changed to FQDN then it started working.
My ansible is 2.0.1.0

as per host variables in case of kerberos authentication just ansible_user, ansible_port and ansible_connection worked fine for me. I have created a kerberos ticket using kinit before attempting ansible command run.

**Comment by aguynamedjoetoo** [comment]
@raghavendraP you can use the IP if you have your PTR records setup appropriately in your DNS for AD (: that's how I resolved my issue.

**Comment by RaghavendraP** [comment]
oh! Thanks for the info.

**Comment by basictheprogram** [comment]
@nitzmahone Do you still need the callback_plugin stuff or the sitecustomize.py to make devel work with Window or am I dealing with a regression?

Grabbed one of those free 90 day Windows 7 workstations images, spun it up, upgraded Powershell to v3.0, ran the ConfigureRemotingForAnsible.ps1, disabled the firewall,  configured a password for the local Administrator.

```
$ ansible --version
ansible 2.2.0 (devel bd8b041756) last updated 2016/06/08 08:57:45 (GMT -500)
  lib/ansible/modules/core: (detached HEAD a8072f9ef0) last updated 2016/06/08 08:57:46 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 6ee1cfc5cf) last updated 2016/06/08 08:57:46 (GMT -500)
  config file = /Users/tanner/projects/ansible.git/playbooks.git/ansible.cfg
  configured module search path = Default w/o overrides
```

Inventory files

```
[windows-workstations]
win7-90day                              ansible_ssh_host=10.X.X.X
```

host_vars/win7-90day/auth.yml

```
---
# it is suggested that these be encrypted with ansible-vault:
# ansible-vault edit auth.yml

ansible_user: Administrator
ansible_password: Passw0rd!
ansible_port: 5986
ansible_connection: winrm

# The following is necessary for Python 2.7.9+ when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore
```

Playbook

```
---
# file: windows-workstations.yml

- hosts: windows-workstations
  vars:
  pre_tasks:
  roles:
  tasks:
  post_tasks:
```

roles/windows-workstations/task/main.yml

```
---
# tasks file for windows-workstations

- name: Ping? Pong?
  action: >
    win_ping
  tags: ping
```

The run

```
$ ansible-playbook -i customers/testing-servers  --ask-vault-pass windows-workstations.yml --tags="ping" -vvvv
Using /Users/tanner/projects/ansible.git/playbooks.git/ansible.cfg as config file
Vault password:
Loaded callback default of type stdout, v2.0

PLAYBOOK: windows-workstations.yml *********************************************
1 plays in windows-workstations.yml

PLAY [windows-workstations] ****************************************************

TASK [setup] *******************************************************************
Using module file /Users/tanner/projects/ansible.git/ansible/lib/ansible/modules/core/windows/setup.ps1
<10.X.X.X> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO 10.X.X.X
fatal: [win7-90day]: UNREACHABLE! => {"changed": false, "msg": "ssl: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)", "unreachable": true}
    to retry, use: --limit @/Users/tanner/Downloads/ansible-retry/windows-workstations.retry

PLAY RECAP *********************************************************************
win7-90day                 : ok=0    changed=0    unreachable=1    failed=0
```

**Comment by aguynamedjoetoo** [comment]
@basictheprogram 

Did you set the option `ansible_winrm_server_cert_validation` to `ignore` in your Ansible config?

**Comment by basictheprogram** [comment]
In ansible.cfg? I have it in my host_vars, let me move it to ansible.cfg.

$ grep winrm ansible.cfg ansible_winrm_server_cert_validation = ignore

```
$ ansible-playbook -i customers/testing-servers  --ask-vault-pass windows-workstations.yml --tags="ping" -vvvv
Using /Users/tanner/projects/ansible.git/playbooks.git/ansible.cfg as config file
Vault password:
Loaded callback default of type stdout, v2.0

PLAYBOOK: windows-workstations.yml *********************************************
1 plays in windows-workstations.yml

PLAY [windows-workstations] ****************************************************

TASK [setup] *******************************************************************
Using module file /Users/tanner/projects/ansible.git/ansible/lib/ansible/modules/core/windows/setup.ps1
<10.X.X.X> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO 10.X.X.X
fatal: [win7-90day]: UNREACHABLE! => {"changed": false, "msg": "ssl: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)", "unreachable": true}
    to retry, use: --limit @/Users/tanner/Downloads/ansible-retry/windows-workstations.retry

PLAY RECAP *********************************************************************
win7-90day                 : ok=0    changed=0    unreachable=1    failed=0
```

**Comment by nitzmahone** [comment]
No, the connection arg overrides have to be in inventory.

What versions of Ansible and pywinrm are you using? pywinrm>=0.1.1 should work (0.2.0 is the latest), and I tested all that stuff back to Ansible 1.9.5 (but it won't work before that).

**Comment by basictheprogram** [comment]
Ansible version

```
$ ansible --version
ansible 2.2.0 (devel bd8b041756) last updated 2016/06/08 08:57:45 (GMT -500)
  lib/ansible/modules/core: (detached HEAD a8072f9ef0) last updated 2016/06/08 08:57:46 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 6ee1cfc5cf) last updated 2016/06/08 08:57:46 (GMT -500)
  config file = /Users/tanner/projects/ansible.git/playbooks.git/ansible.cfg
  configured module search path = Default w/o overrides
```

pywinrm

```
$ pip freeze | grep winrm
pywinrm==0.2.0
```

Putting ansible_winrm_server_cert_validation = ignore into host_vars the same as putting it into the inventory file?

**Comment by nitzmahone** [comment]
Interesting- looks like a bug where the psuedo-connectionvar (ansible_winrm_server_cert_validation) isn't getting picked up from a nested host_vars file defined that way... If I add it to the top level inventory file at either host or group level, it works fine. We're hoping to change the way that's implemented for 2.2 anyway (it's a nasty hack right now), but see if that gets you going.

**Comment by basictheprogram** [comment]
Added it to group_vars/all

```
# group_vars/all
---
# Python 2.7.9+ when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore
```

Same error. Added to host_vars/win7-90day.yml

```
# host_vars/win7-90day.yml
---
# it is suggested that these be encrypted with ansible-vault:
# ansible-vault edit auth.yml

ansible_user: Administrator
ansible_password: Passw0rd!
ansible_port: 5986
ansible_connection: winrm

# The following is necessary for Python 2.7.9+ when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore
```

I know Ansible is picking up some of the variables. If I change ansible_user: Administrator2 I see Ansible attempting to authenticate as Administrator2

```
TASK [setup] *******************************************************************
Using module file /Users/tanner/projects/ansible.git/ansible/lib/ansible/modules/core/windows/setup.ps1
<10.X.X.X> ESTABLISH WINRM CONNECTION FOR USER: **Administrator2** on PORT 5986 TO 10.X.X.X
```

**Comment by nitzmahone** [comment]
Yeah, this is a post-2.1 inventory regression (I'm investigating now)- non-connection vars defined in group/host_vars dirs don't appear to be making it to the worker processes.

I'm able to get it working on devel by defining in the top-level inventory file (eg, hosts.ini or whatever) as a group var or host var.

**Comment by basictheprogram** [comment]
My version is "todays" git pull of devel so if I understand you right adding ansible_winrm_server_cert_validation to group_vars/all should allow things to work. That is not the case.

**Comment by nitzmahone** [comment]
No- a top level ini inventory file (something as simple as):

```
win7-90day ansible_winrm_server_cert_validation=ignore
```

The issue appears to be that some of the group_vars/host_vars resolution got moved past the fork boundary, so the connection workers aren't seeing all the inventory vars. 

(leaving the rest of your inventory intact, as the connection vars themselves are getting passed explicitly)

This is definitely a recent devel bug (works fine in 2.1.0 and prior)- we're looking into it.

**Comment by basictheprogram** [comment]
Yes, that works. Thank you for the detailed explanation.

**Comment by nitzmahone** [comment]
@basictheprogram this should be fixed in devel and stable-2.1 now (fix should ship in 2.1.1)

**Comment by basictheprogram** [comment]
I testing using devel branch. I assume the fix found its way into devel? Got a commit llink?

**Comment by jhawkesworth** [comment]
I'm guessing the commit link is https://github.com/ansible/ansible/commit/445a88d3e8af0a11b63ecb4958cb16d2a27e4716 - however my test rig, updated to latest devel 14 hours ago is currently attempting ssl connection for windows hosts which have previously worked, so I think there might be more to this.  I'll investigate further as time allows, but I have found I can force it by setting '-c winrm' on the command line.  Doesn't seem to make a difference if I use group_vars or inline vars in inventory for me.

**Comment by nitzmahone** [comment]
It was actually https://github.com/ansible/ansible/commit/ece1ed09d51ea43be888b64eea95680a5c300a5b - an unrelated performance change was made to inventory that inadvertently broke this behavior, since winrm is the only "mainstream" connection plugin that currently uses pseudo connection vars (eg, ansible_winrm_X - connection vars that aren't explicitly propagated by inventory to the connection layer). 

@jhawkesworth I'm not seeing the behavior you are on devel- my stuff is all using group vars to set ansible_connection to winrm, and continues to work as-expected... Is it possible you've got stale .pyc files laying around (try a `make clean`)?

**Comment by jhawkesworth** [comment]
Thanks @nitzmahone I will give that a try.

**Comment by jhawkesworth** [comment]
Just to follow up make clean sorted this out for me. Wondering how I have done without it all this time!

**Comment by basictheprogram** [comment]
Not sure if this is related, but today's devel branch is telling me:

```
 [WARNING]: ansible_winrm_certificate_expires unsupported by pywinrm (is an up-to-
date version of pywinrm installed?)
```

```
$ ansible --version
ansible 2.2.0 (devel 3b3ab605f6) last updated 2016/06/13 13:46:21 (GMT -500)
  lib/ansible/modules/core: (detached HEAD d6f01d0b4f) last updated 2016/06/13 10:41:06 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 43760b2c4a) last updated 2016/06/13 10:41:06 (GMT -500)
  config file = /Users/tanner/projects/ansible.git/playbooks.git/ansible.cfg
  configured module search path = Default w/o overrides
```

```
$ pip freeze | grep pywin
pywinrm==0.2.0
```

**Comment by nitzmahone** [comment]
@basictheprogram Hrm, that's a minor side-effect of the fix that I hadn't noticed. A couple ways to fix that, but I'll have to kick it around a bit (thanks for the heads-up, though!)

**Comment by nitzmahone** [comment]
Today's devel and stable-2.1 should no longer exhibit this behavior (modified the returned fact name not to collide with the connection var)

**Comment by tcpip2016** [comment]
Hi nitzmahone, 
We got the similar issue when running playbook against to Windows, if I put "ansible_winrm_server_cert_validation: ignore" to top level group_var/, then it works fine; if I put it to roles/vars/main.yml, then it's failed with "kerberos: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)", please advise (ansible 2.1.2.0).

Thanks,

**Comment by nitzmahone** [comment]
Pseudo-connection vars like ansible_winrm_X can currently only be set via inventory or extra_vars (due to some fairly deep issues around delegation and the Ansible process model). This _should_ be corrected in devel by the time 2.3 releases.

**Comment by tcpip2016** [comment]
Thanks for the quick response!

**Comment by b-long** [comment]
@nitzmahone I feel terrible asking this, given the amount of traffic on this thread, but I'm wondering if a change to `ansible_winrm_server_cert_validation` is still expected for Ansible 2.3.

As far as I can tell, it still must be set in the inventory file, if the desired behavior is : 
```yml
ansible_winrm_server_cert_validation=ignore
```

[Just as you noted a while ago](https://github.com/ansible/ansible/issues/14710#issuecomment-190474564), placement in a playbook will not be respected.  For instance  : 
```yml
- name: Debug playbook
  hosts: all
  vars:
    - ansible_connection: winrm
    - ansible_winrm_server_cert_validation: ignore
    - ansible_user: user
    - ansible_password: password
    - ansible_port: 5986
    - ansible_winrm_transport: ntlm

  tasks:
    - name: "Print a sanity check (message)"
      debug: msg="Running debug playbook"
```
Tested using `ansible 2.2.1.0` and `pywinrm==0.2.2`.

**Comment by jhawkesworth** [comment]
@b-long - I'd recommend asking on ansible-project google group or on #ansible irc channel rather than commenting on closed issues, as a lot less people review the issue tracker.

I'm pretty certain no change is planned for this during 2.3 - I've certainly not seen any open issues regarding this.  These 'connection' type variables need setting so that they apply to hosts.  So you can set in inventory or in group_vars.  If that doesn't work for you I suggest creating a feature suggestion outlining a use case for why it would be beneficial to be able to set these vars elsewhere.

**Comment by subbireddyg** [comment]
Using /home/ubuntu/ckp/ansible.cfg as config file
<172.31.46.234> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5985 TO 172.31.46.234
172.31.46.234 | FAILED! => {
    "failed": true,
    "msg": "ERROR! ssl: 500 WinRMTransport. [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)"
}
ubuntu@ip-172-31-9-47:~/ckp$

please suggest?

**Comment by subbireddyg** [comment]
[win]
172.31.46.234
[win:vars]
ansible_ssh_user=Administrator
ansible_ssh_password=password
ansible_ssh_port=5985
ansible_connection=winrm
ansible_winrm_scheme=https
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=ssl

**Comment by jhawkesworth** [comment]
@subbireddyg Please don't comment on closed issues, especially issues where others have been asked not to comment on closed issues.

if you want to use ssl/tls to communicate via winrm use port 5986 - 5985 is an http listener.

Also while you are changing things, use 'ansible_user' 'ansible_password' and 'ansible_port' instead of ansible_ssh... variable names, these are deprecated and will eventually stop working.
