### ISSUE TITLE
Executing a command on a remote Windows Host

### ISSUE THREAD

**Issue by johnakash** [ansible/ansible#14728]
##### Issue Type:
- Feature Idea
##### Ansible Version:

```
(ansible 1.9.4)
```
##### Ansible Configuration:

Please mention any settings you've changed/added/removed in ansible.cfg
ask_sudo_pass = No
##### Environment:

OS you are running Ansible: RHEL 7
OS you are managing: RHEL 7
##### Summary:

We would like to run a command on remote windows host as we are doing on linux like *_ansible webserver -s -m shell -a "/etc/init.d/httpd status" -u user1 -k *_. So is there any method to do the same on windows hosts for checking service status (like httpd)? 
##### Steps To Reproduce:

```
<!--- Paste example playbooks or commands here -->
```

##### Expected Results:

webserver | success | rc=0 >>
httpd is running (PID: 2495).

**Comment by jhawkesworth** [comment]
you can use raw module against windows hosts.

You can use sc.exe like this:

sc query name_of_service

By the way, 'how to do things' questions like this are best asked on the ansible-project google group, or on the #ansible irc channel rather than here, as there are many more people who can see and respond to questions like this than monitor the ansible issue tracker.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
