### ISSUE TITLE
Included files are not played anymore with 2.0.1.0

### ISSUE THREAD

**Issue by arthur-c** [ansible/ansible#14727]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
2.0.1.0 / commit 23151a24845afbeaeb263d75aa84a43f68d97b07 Mon Feb 29 16:22:09 2016
```
##### Ansible Configuration:

```
[defaults]
host_key_checking = False
forks=10
```
##### Environment:

Fedora 23
##### Summary:

 I'm runnning ansible 2.0.1.0 / commit 23151a24845afbeaeb263d75aa84a43f68d97b07 Mon Feb 29 16:22:09 2016 and I can't include a file in my playbooks anymore.  I can read the "included" statement in the log during the play but included files are not played at all (I put debug messages as well : nothing), then my role is ended without finishing the main task. Everything after the included file is not played. If I copy/paste the included task file in my play : it works well.
##### Steps To Reproduce:

```
- name: Included tasks
  include: included_file.yml 

```
##### Actual Results:

Here is two roles: the first one is not finished, it stops directly after the include and before playing the included file.

```
TASK [get_jenkins_artifacts : Get latest build] ********************************
task path: ansible-repo/roles/get_jenkins_artifacts/tasks/main.yml:24
included: ansible-repo/roles/get_jenkins_artifacts/tasks/ftp_get_latest_builded_artifact.yml

TASK [build_docker_image : set_fact] *******************************************
```

Back to "2eb59bedcfc127b6b3ea392e654c031e83a6e87d  New release v2.0.0.0-1": my included file is... included and played !

**Comment by jamespharaoh** [comment]
i have exactly the same issue, and have also been able to get it working again by reverting to the commit mentioned by @arthur-c .

**Comment by jimi-c** [comment]
@arthur-c there have been a lot of fixes in this area, howeveryou don't include a full reproducer here. Can you please let us know if you're still seeing this problem on the latest devel and/or stable-2.0 branch? Beyond that, if you could include a full reproducer that would be helpful.

**Comment by arthur-c** [comment]
@jimi-c It's ok with stable-2.0 right now, thanks !

my git version:

```
commit d68b463089bc5ca079c9177b1d4ce342ce099d38
Author: James Cammarata <jimi@sngx.net>
Date:   Mon Mar 28 15:54:07 2016 -0400

    New unit tests for #13630 fix
```

**Comment by jimi-c** [comment]
Excellent, I'll go ahead and close this out.

Thanks!
