### ISSUE TITLE
Ansible 2 has changed the precedence of the role_path options in ansible-galaxy

### ISSUE THREAD

**Issue by greylurk** [ansible/ansible#14725]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 1.9.4
  configured module search path = None
```

and 

```
ansible 2.0.0.2
  config file =
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

In ansible 1.9.4 the "path" key in the requirements.yml file took precedence over the role_path passed in from the command line.  This was useful for installing some requirements via galaxy that weren't strictly "roles". For example:

```

---
- src: https://github.com/foo/ansible-inventory
  name: inventory
  path: ./
  version: HEAD
- src: https://github.com/cmacrae/ansible-semaphore.git
  name: semaphore
  version: HEAD
```

When executed as `ansible-galaxy -r requirements.yml -p roles` from the root directory of a playbook, we would end up with the inventory in the correct place, and the roles installed to the roles directory. 

However, in Ansible 2.0.0.2, the behavior seems to be that the -p option overrides the path specified in the requirements, so this same requirements yaml, when run with the same CLI arguments, results in both the inventory, and semaphore dependencies installed in the "roles" directory.
##### Steps To Reproduce:

See descriptions
##### Expected Results:

I expect to have some way to install requirements that are not roles and have them placed outside the "role_path" folder.
##### Actual Results:

In ansible 1.9.4 - the folder structure ends up like this:

```
ansible-playbook-demo
+- roles
|    +- semaphore
|         ....
+- inventory
     ....
```

In ansible 2.0.0.2 - the folder structure ends up like this:

```
ansible-playbook-demo
+- roles
    +- semaphore
    |   ...
    +- inventory
        ....
```

**Comment by bcoca** [comment]
This was done on purpose as it is a problem from possible hostile requirements files to override the user's preference on where they install.
