### ISSUE TITLE
delegate_to does not honor remote_user

### ISSUE THREAD

**Issue by SitronNO** [ansible/ansible#14720]
##### Issue Type:
- Bug Report
##### Ansible Version:

2.0.1.0
##### Ansible Configuration:

No customization
##### Environment:

Distro: Ubuntu 14.04.4 LTS
Package: ansible 2.0.1.0-1ppa~trusty
##### Summary:

When using _delegate_to_ and _remote_user_ in a playbook, it connects to the correct node, but with the default user, not the user specified with _remote_user_.
##### Steps To Reproduce:

Create the following three files:

ansible.cfg:

```
[defaults]
hostfile = hosts
remote_user = username
```

hosts:

```
host.example.org
```

test.yml:

```

---
- hosts:
    - host.example.org

  tasks:
  - command: whoami
    register: whoami
    delegate_to: otherhost.example.org
    remote_user: root
    become: false

  - debug: msg="{{ whoami.stdout }}"
```

Run this with the following command:
`ansible-playbook test.yml -K -vvv`
##### Expected Results:

```
1 plays in test.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
<host.example.org> ESTABLISH SSH CONNECTION FOR USER: username
[...cut...]
ok: [host.example.org]

TASK [command] *****************************************************************
task path: /home/username/ansible-test/test.yml:6
<otherhost.example.org> ESTABLISH SSH CONNECTION FOR USER: root
[...cut...]
ok: [otherhost.example.org]
```
##### Actual Results:

```
1 plays in test.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
<host.example.org> ESTABLISH SSH CONNECTION FOR USER: username
[...cut...]
ok: [host.example.org]

TASK [command] *****************************************************************
task path: /home/username/ansible-test/test.yml:6
<otherhost.example.org> ESTABLISH SSH CONNECTION FOR USER: username
[...cut...]
fatal: [otherhost.example.org]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. [...cut...]
```

This happens because ansible tries to connect to otherhost.example.org with the user _username_, and not _root_ as specified as _remote_user_ in the playbook.

**Comment by SitronNO** [comment]
A workaround is to modify test.yml and include a var in the task:

```
---
- hosts:
    - host.example.org

  tasks:
  - command: whoami
    vars:
      ansible_ssh_user: root
    register: whoami
    delegate_to: otherhost.example.org
    become: false

  - debug: msg="{{ whoami.stdout }}"
```

**Comment by bcoca** [comment]
are you setting ansible_ssh_user/ansible_user for the delegate host in inventory?

**Comment by SitronNO** [comment]
No, you see my inventory (filename `hosts`) above. All the files am I using, and all of their contents, are listed above.

**Comment by bcoca** [comment]
so #15024 should fix this as it seems the ansible_ssh_user from the delegatedFOR host was bleeding into the vars for the delegated_to host

**Comment by bcoca** [comment]
closing this as my testing shows this as fixed by the PR above
