### ISSUE TITLE
"make install" error message

### ISSUE THREAD

**Issue by tonk** [ansible/ansible#1473]
I just pulled the latest version from git and a `make install` gives me

```
/usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'install_requires'    warnings.warn(msg)
```

All things look oke, though.

I'm running this on a updated CentOS 6 system

**Comment by mpdehaan** [comment]
I build on 6.3 all the time.    Given it's a warning, I think you can
ignore it.

**Comment by tonk** [comment]
Oke, I will. Thanks.

Case closed.
