### ISSUE TITLE
Error in documentation.

### ISSUE THREAD

**Issue by longr** [ansible/ansible#14748]
##### Issue Type:
- Documentation Report
##### Ansible Version:

```
ansible 1.9.4
  configured module search path = None
```
##### Environment:

N/A
##### Summary:

I think the documentation is wrong for YAML and dicts. On this page http://docs.ansible.com/ansible/YAMLSyntax.html it talks about defining dictionaries as:

```
-  martin:
    name: Martin D'vloper
    job: Developer
    skill: Elite
```

or 

employees:

```
  -  martin: {name: Martin D'vloper, job: Developer, skill: Elite}
```

This does not work, I am pretty sure it should be:

```
martin:
    name: Martin D'vloper
    job: Developer
    skill: Elite
```

Judging by the "employees" part it looks like it might have been from old documentation as part of a list.

**Comment by bcoca** [comment]
that might be a bit unlcear, but the dictionary is the contents of 'martin'

**Comment by longr** [comment]
Looking back, I think the error is caused by the difference between declaring vars: in a play, and setting the variables in a var file.
