### ISSUE TITLE
ignore_errors: yes sometimes fails, depending on error severity (with delegate_to)

### ISSUE THREAD

**Issue by FlorinAndrei** [ansible/ansible#14762]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### Environment:

Ubuntu 14.04 64bit on all instances
##### Summary:

In a playbook, I've a task with delegate_to a group of hosts. To test delegation, I use 'ignore_errors: yes'. But errors are only ignored when there's a soft error, like when Ansible is able to ssh to the delegate host but the command fails there. However, if there's a hard error, like ssh to the delegate host fails because the user account has not been created yet, the error is not ignored and the playbook fails.
##### Steps To Reproduce:

Run ansible with:

```
ansible-playbook -i staging deploy_api_new.yml --vault-password-file $HOME/.payrange_production_vault_secret --sudo
```

```
- name: disable instance on HAproxy and wait for it to go offline
  haproxy: state=disabled backend=app_back host={{ inventory_hostname_short }} socket=/run/haproxy/admin.sock shutdown_sessions=no wait=yes
  delegate_to: "{{ item }}"
  with_items: "{{ groups.haproxy_app }}"
  when: "'staging' in group_names"
  ignore_errors: yes
```
##### Expected Results:

I expect errors during that step to be always ignored, no matter what.
##### Actual Results:

If all user accounts are created on {{ groups.haproxy_app }} and ansible is able to ssh in and try to execute the task there, then the error is ignored if the task fails on {{ groups.haproxy_app }}. This is good.

But if no user accounts are created on {{ groups.haproxy_app }} and ansible is unable to ssh into those instances, then this kind of error is not ignored. This is bad.

Example of successful ignore:

```
TASK [foobar_api_new : disable instance on HAproxy and wait for it to go offline] ***
failed: [app03-staging-uswest2-aws.foobar.staging -> haproxy-app01-staging-uswest2-aws.foobar.staging] => (item=haproxy-app01-staging-uswest2-aws.foobar.staging) => {"failed": true, "item": "haproxy-app01-staging-uswest2-aws.foobar.staging", "msg": "unable to find server app_back/app03-staging-uswest2-aws"}
failed: [app03-staging-uswest2-aws.foobar.staging -> haproxy-app02-staging-uswest2-aws.foobar.staging] => (item=haproxy-app02-staging-uswest2-aws.foobar.staging) => {"failed": true, "item": "haproxy-app02-staging-uswest2-aws.foobar.staging", "msg": "unable to find server app_back/app03-staging-uswest2-aws"}
...ignoring
```

Example of failure to ignore:

```
TASK [foobar_api_new : disable instance on HAproxy and wait for it to go offline] ***
fatal: [app01-staging-uswest2-aws.foobar.staging]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"item": "haproxy-app01-staging-uswest2-aws.foobar.staging", "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}, {"item": "haproxy-app02-staging-uswest2-aws.foobar.staging", "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}]}
```

**Comment by bcoca** [comment]
ignore_errors applies to task or module errors, it does not apply to host/connection errors nor syntax/definition errors.

**Comment by FlorinAndrei** [comment]
I see. Well, that makes it less intuitive when used with delegate_to, and certainly less useful for testing. After all, what I was testing was delegation itself.

**Comment by bcoca** [comment]
I'm going to close this as ignore_errors is clearly marked for just task errors, not communication or sytnax errors.

**Comment by munai-das** [comment]
Hi FlorinAndrei, what was the reason of getting the error **"unable to find server app_back/app03-staging-uswest2-aws"**. I am too getting the error.

**Comment by FlorinAndrei** [comment]
@munai-das That was actually an ssh error. I think it was caused by an ssh key issue. Not caused by Ansible.
