### ISSUE TITLE
Module "skip" to skip remaining play

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#1476]
I would propose a module "skip" to skip the remaining play.

Usage would be something like:

``` yaml
- action: /opt/proprietary/application --version
  register: app_version

- action: skip
  only_if: '${app_version.stdout}' != '1.2.3'

- action: command mktemp -d
  register: tempdir
- action: command rsync -aH /share/software/proprietary/application-1.2.3 ${tempdir.stdout}
- action: command ${tempdir.stdout}/ugly-stuff --to --do --manual --install
```

Another way to do this could be:

``` yaml
- action: /opt/proprietary/application --version
  register: app_version
  skip_if: '${app_version}' != '1.2.3'
```

not sure if we want to enlarge the list of custom task attributes this way...

**Comment by bcoca** [comment]
wouldn't this work the same?:

<pre>
- action: /opt/proprietary/application --version
  register: app_version
  only_if: '${app_version}' == '1.2.3'
</pre>

**Comment by mpdehaan** [comment]
Idea was something to Skip all remaining tasks, not just one

-- Michael

**Comment by dagwieers** [comment]
@bcoca We do that for all tasks in a play, but we prefer not having to do that.

**Comment by mpdehaan** [comment]
seems to not be getting much traction here, I think a better way to do this may be to use "only_if/when" on the task include.

**Comment by mpdehaan** [comment]
FWIW, I'm open to revisiting this.

This is a very old ticket and the scope of use in Ansible has changed significantly.

**Comment by djm** [comment]
@mpdehaan I personally think this would make roles more reusable and I'm going to showcase why. It may just be that I'm going about it incorrectly, in which case feel free to dismiss.

My use case: creating a re-usable "dump and run" playbook that conditionally installs a program that is not available via package managers. I want the first task of that role to be a check as to whether a version of that program is already installed, and if it is, to skip the rest of the (rather slow) tasks within the playbook.

A quick & shortened version of what it does now:

```
- name: Test version not already installed
  shell: which program_x-{{ program_version }}
  register: version_already_installed
  ignore_errors: True

- name: Download ProgramX
  when: not version_already_installed.stdout

- name: Extract ProgramX
  when: not version_already_installed.stdout

- name: Install ProgramX
  when: not version_already_installed.stdout

- name: Symlink ProgramX
  when: not version_already_installed.stdout

```

Obviously this is a bit tedious and completely unDRY.

You said back in February:

> I think a better way to do this may be to use "only_if/when" on the task include.

For me, this takes away from the reusability of a role of this kind as rather than skipping within the role itself and allowing the user to simply add the role up to their `roles` list incredibly easily; the user has to create the "check" task in their own codebase and _then_ conditionally include the playbook. It ruins the whole "dump and run" ability for this type of role.

I'm still new to Ansible, so if there is indeed a way to get around this then please do correct me but otherwise I think this would be a great addition.

**Comment by madrobby** [comment]
I'd also like to see this functionality. For example, we have a deployment playbook that does various tasks but only if the very first one succeeded. Having no way to skip the rest of the actions creates a lot of clutter and makes it harder to maintain the playbook when changes occur.

**Comment by mmoya** [comment]
+1 to this

**Comment by jhohertz** [comment]
Also wouldn't mind something along these lines. My context is I'm building a series of recipes that declare dependencies, but we build iteratively and snapshot. (IE: a raw image builds into a base, which has another role layered on, etc.). So I could tag my snapshot with what roles have been run already in the snapshot, and have my recipes look for said tags when the role runs, and skip it if it's detected.

```
- name: Check if tag exists
  # some logic to check and set a var if tag is seen
- name: Detect if role has been run and skip
  end_role: True
  when: not tagged and not forced_rebuild
```

If I could stick something like that in a role that's typically part of a snapshot, then we could speed up builds by skipping large swaths of tasks sets when layering a role onto a base system.

**Comment by FiloSottile** [comment]
+1 on this being reopened @mpdehaan 

I think it should skip all the remaining play, but not exit the playbook.

**Comment by muff1nman** [comment]
+1

**Comment by jyoungs** [comment]
+1

**Comment by adrienmo** [comment]
+1

**Comment by Tenzer** [comment]
Given the interest in getting this feature implemented, shouldn't the issue be reopened?

**Comment by manuel-sousa** [comment]
+1

**Comment by baibaluo** [comment]
+1

**Comment by tdemande** [comment]
+1 for reopen, there doesn't seem to have a easy way to skip all remaining tasks of a role.

**Comment by stevenyap** [comment]
+1

**Comment by knh1** [comment]
+1

Came here looking for a skip function similar to the fail module.  The fail module already achieves the desired functionality, but the nodes report as failed when the more accurate description in my use case would be skipped.

**Comment by daniilyar** [comment]
+1

**Comment by msabramo** [comment]
:+1:

**Comment by zupancb** [comment]
+1

**Comment by libsamek** [comment]
+1

**Comment by ghost** [comment]
+1

Also have an option to skip the rest of any dependent roles, i.e.:

```
---
# roles/role1/meta/main.yml
dependencies:
  - role: role0 
```

```
---
# roles/role1/tasks/main.yml
- action: task1
```

```
---
# roles/role0/tasks/main.yml
- skip: skip_the_rest=True
  when: variable == ""

- action: task0
```

So task1 never gets executed.

**Comment by gtfool** [comment]
Would love this also so we wouldn't have to add only_if/when to all subsequent tasks!

**Comment by nicholaskuechler** [comment]
+1

**Comment by famousgarkin** [comment]
+1, same use case as @djm, installing software from source. My workaround ATM:

```
- command: which autossh
  args:
    creates: /usr/local/bin/autossh
  ignore_errors: true
  register: which_autossh

- include: autossh-install.yml
  when: not which_autossh.stdout
```

**Comment by grypyrg** [comment]
+1

**Comment by RajeevNambiar** [comment]
+1 for end_role: True

**Comment by bobbywatson3** [comment]
+1

**Comment by schwerlaut** [comment]
+1

**Comment by hloeffler** [comment]
@bcoca @jimi-c <- is more helpful than just +1

**Comment by k1rk** [comment]
+1

**Comment by hloeffler** [comment]
i think its best to create a new issue

**Comment by trentondyck** [comment]
+1

**Comment by bobbywatson3** [comment]
What I ended up doing since 2.0 came out is just enclosing all of the code that I would have skipped into a single block, and then applying that conditional to the whole block.

**Comment by dagwieers** [comment]
I am not asking for "goto" functionality, but rather "return" or "break" functionality.

PS Everyone who wants this, please like :+1: this issue instead of adding +1 using a comment.

@bcoca Can this request be reopened as @mpdehaan indicated in his last comment ?

**Comment by trentondyck** [comment]
@robertwatson3 
That looks fine for what I need, thanks.  I'm on ansible 1.9.4 since I'm using Centos 6 official yum repo but I guess I can upgrade if I have to.

**Comment by sharraf** [comment]
:+1:

**Comment by jhriv** [comment]
I came here to :+1: for skip, but I walked out with `- block:`. That works for my use case. Thank you.

**Comment by temoto** [comment]
👍 

Please, show how to use `when` on blocks.

**Comment by trentondyck** [comment]
```
 - block:
   - debug: var=msg
     when: true
   when: true

```

print var=msg when true, and run the block when true

**Comment by zhanglongqiang** [comment]
i really need this feature to avoid many times to install 'jdk' in variable roles.

**Comment by bcoca** [comment]
use this?

```
- fail:
  when: True
  run_once: True
```

**Comment by jimi-c** [comment]
I've pushed a new feature branch for this, implementing it as `- meta: end_play`. The meta subsystem was also expanded to support conditionals, so things like this work:

```
- meta: end_play
  when: inventory_hostname == 'some_host'
```

Example playbook and run with this patch: https://gist.github.com/jimi-c/c45b225e101fe673e42ffb719f259fbd

Please give it a test and let me know what you think.

**Comment by jctanner** [comment]
@dagwieers does "meta: end_play" match your expectations for this feature?

**Comment by dagwieers** [comment]
@jctanner Honestly, I find the terminology/naming quite confusing. The term **meta** does not give any meaning to what **end_play** is supposed to achieve. I am not convinced this is something we would like to expose to the world ;-)

PS Is there a design document with what **meta** is being used for ? I wonder if there's a better mechanism for influencing flow, and what other needs it could fulfill.

**Comment by bcoca** [comment]
`meta` in general affects Ansible's behavior, so flush_handlers, refresh_inventory, etc are all actions that change the normal 'play flow'. The current implementation is in the base class of the strategy plugins.

We should document this better.

**Comment by jimi-c** [comment]
@dagwieers the `meta` option has been around for a long time (it was there 3 years ago when I started working on Ansible). In 2.0, we started expanding it to include other options besides flush_handlers. I do agree we need better docs around this.

**Comment by sharuzzaman** [comment]
I want the skip feature as well.

My use case is, I create a playbook to install software for CentOS and Ubuntu, and want to skip the whole playbook if the OS is not Linux. 

I could specify the OS for each task, but having a skip task early in the playbook that would skip everything if some parameter did not match will help speed things up.

**Comment by jimi-c** [comment]
I've gone ahead and merged this, so it will be a feature in 2.2. If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by dagwieers** [comment]
Thanks @jimi-c !

**Comment by nergdron** [comment]
I primarily need an "end_role", so I can include roles in a playbook and have them skip based on data they collect at certain points. end_play seems to terminate the whole playbook, and so is too large of sledgehammer for the problems I'm having.

**Comment by lakshmi-kannan** [comment]
I am in the same boat as nergdron. I really need something to skip rest of the tasks in a role when a condition is met. Here is an example where this will be useful https://gist.github.com/lakshmi-kannan/1ceb1d8cea0877f2a7d51aced873ff92.

**Comment by jimi-c** [comment]
Please open a new issue for this feature request.

**Comment by hloeffler** [comment]
done: https://github.com/ansible/ansible/issues/22286

**Comment by jamclean** [comment]
Why not just make 3 similarly named functions? It would simplify confusion if it could be done that way. Then you would cover the skip gamut.

1. Skip -n tasks
2. Skip all remaining tasks
3. Skip role

**Comment by nirzari** [comment]
@sharuzzaman Were you able to find solution for your problem?
@jimi-c The meta:end_play ends current play but is there anything else that can help exit the playbook itself without "Fail" status in case of multiple plays?

**Comment by cameronkerrnz** [comment]
I think there are good reasons for having an end_playbook (possibly more-so than end_play). Namely, pre-flight checks, or limiting execution. Eg.

- I might want to have my patching playbook have a download-only mode, so it can stop the playbook after its downloaded all the packages (saving time in my maintenance window).

In this context, having end_play without having end_playbook makes it too easy to do the wrong thing (the play ends, but then subsequent plays run, which may be very well unexpected).

**Comment by gravcat** [comment]
I was able to use 

```
- name: Check for something first
  command: do some stuff in bash | grep someValue
  register: something

- block
  - name: My really cool task
    file:
      path: /some/cool/dir
      state: directory
      mode: 0755

  - name: My really cool second example task
    file:
      path: /some/cool/otherdir
      state: directory
      mode: 0755

  when: not something
```

If `something` has anything in it, that output will get registered. If registered, the `when` conditional will be False, and will not execute. If `something` were to not come back with anything, then the block's tasks would be executed.

Obligatory mention that the `file` module is already super friendly with idempotency, I just used it in this example because it was the first module that came to mind.

A very crude example, and I'm sure many know how to do this already, but for those who don't!
