### ISSUE TITLE
Variables in meta

### ISSUE THREAD

**Issue by plat00n** [ansible/ansible#14775]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 1.9.2
ansible 2.0.1.0
##### Ansible Configuration:

[defaults]
roles_path = $HOME/ansible/roles
remote_user = ansible

[privilege_escalation]
# become=True

become_method='sudo'
# become_user='ansible'
# become_ask_pass=False

deprecation_warnings=False

[ssh_connection]
ssh_args = -o ControlPersist=15m -F /test_folder/data/user/.ssh/config -q
scp_if_ssh = True
control_path = ~/.ssh/mux-%%r@%%h:%%p
##### Environment:

CentOS release 6.6 (Final)
##### Summary:

We have a role which has a meta folder. The Role dependencies include "vars".
Since that we added "tags", the dependancies continue to be played but the vars are not taken into account. Before it worked.
##### Steps To Reproduce:

create theses 5 files:

ansible/roles/httpd/tasks/main.yml

```

---
- name: INCLUDE TASKS for HTTPD
  include: httpd.yml
  tags: tag_role_httpd
```

ansible/roles/httpd/tasks/httpd.yml

```

---
- name: INCLUDE VARS
  include_vars: httpd.yml
```

ansible/roles/httpd/vars/httpd.yml

```

---
web_engine_enabled: true
web_engine_httpd: "httpd"
```

ansible/roles/httpd/meta/main.yml

```

---
dependencies:
  - {role: common, tags: [ 'tag_role_httpd' ]}
  - {role: sitevide, web_engine: "httpd",  web_engine_user: "apache", tags: [ 'tag_role_httpd' ]}
```

ansible/roles/sitevide/tasks/main.yml

```

---
- name: COPY TEMPLATE basic sitevide files
  template: src=test_file.j2 dest=/test/folder/test_file.ok owner="root" group="root" mode=0744
  sudo: true
  when: web_engine_{{ web_engine }} is defined
```
##### Expected Results:

Copy must not be skipped, because when playing the "httpd" role meta, vars will be taken into account.
##### Actual Results:

Task is skipped because vars are not taken into account. It worked when tag where not present, but now we need them.

Thanks for your advice/solutions.
plat00n

**Comment by bcoca** [comment]
`when: web_engine_{{ web_engine }} is defined` <= this is invalid syntax
it should be:

```
when: hostvars[inventory_hostname]['web_engine_' + web_engine] is defined
```

or

```
when:  " 'web_engine_' + web_engine in hostvars[inventory_hostname]"
```

**Comment by plat00n** [comment]
Hello,
- name: DEBUG VAR
  debug: msg="value = {{ web_engine }}"
  when:  " 'web_engine_' + web_engine in hostvars[inventory_hostname]"

===> TASK [sitevide : DEBUG VAR] ****************************************************
fatal: [d1cedtestansi01]: FAILED! => {"failed": true, "msg": "The conditional check ' 'web_engine_' + web_engine in hostvars[inventory_hostname]' failed. The error was: error while evaluating conditional ( 'web_engine_' + web_engine in hostvars[inventory_hostname]): 'web_engine' is undefined\n\nThe error appears to have been in '/test_folder/data/user/ansible/roles/sitevide/tasks/sitevide.SIT.tasks.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: DEBUG VAR\n  ^ here\n"}
- name: DEBUG VAR
  debug: msg="{{ web_engine }}"
  when: web_engine_{{ web_engine }} is defined

===> TASK [sitevide : DEBUG VAR] ****************************************************
fatal: [d1cedtestansi01]: FAILED! => {"failed": true, "msg": "'web_engine' is undefined"}

This is the same, the error is that the variable setted on the meta for this role is not taken into account:

Any idea ?

**Comment by bcoca** [comment]
ah, the web_engine itself is undefined, not the combo var, just need to prepend that check

`when:  web_engine is defined and ...`

**Comment by plat00n** [comment]
The web_engine is set on :
- {role: sitevide, web_engine: "httpd",  web_engine_user: "apache", tags: [ 'tag_role_httpd' ]}

Previously it worked (before we had tags)

It's amazing that now theses vars are saw as "undefined" :( I hope someone have the solution

Thanks

**Comment by plat00n** [comment]
Hi all,

forget about that... before i didn't use vars from a included file... now we do...
so my variables in ansible/roles/httpd/vars/httpd.yml were not taken into account by the meta !

This is not a TAG issue ! 
Now it's ok with my latest correction :
ansible/roles/httpd/vars/httpd.yml

```
---
dependencies:
  - {role: common, tags: [ 'tag_role_httpd' ]}
  - {role: sitevide, web_engine: "httpd",  web_engine_user: "apache", web_engine_httpd: "httpd" ,tags: [ 'tag_role_httpd' ]}
```

Thanks bcoca
