### ISSUE TITLE
Value of variable is overriden by value defined in sibling group

### ISSUE THREAD

**Issue by alvarogmj** [ansible/ansible#14778]
##### Issue Type:
- Bug Report/Documentation Report
##### Ansible Version: ansible-2.0.0-0.7.rc2.tar.gz

```
ansible 2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

None
##### Environment:

RHEL6
##### Summary:

Assume two groups, "g1" and "g2", and a host "h1" belonging to both groups. These are sibling groups, i.e. one is not a child of the other.
Both groups have a variable "v1" defined.
A play with "-hosts: g2" will hold the value for v1 defined in g1 when running on h1

I believe this is not intuitive behavior and if it is by design should be clearly documented. One would expect limiting the play to the hosts in group "g2" will only make effective the values defined for that group.
##### Steps To Reproduce:

Test case: 

```
group_vars/g1:

---

test_var: 1

group_vars/g2:

---

test_var: 3

test.yml

---

- hosts: g2
  tasks:
    - debug: msg={{ test_var }}

inventory:
[g1]
localhost

[g2]
localhost
```
##### Expected Results:

```
$ ansible-playbook -i inventory test.yml

PLAY ***************************************************************************

TASK [debug msg={{ test_var }}] ************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": 3
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

```
##### Actual Results:

```
$ ansible-playbook -i inventory test.yml

PLAY ***************************************************************************

TASK [debug msg={{ test_var }}] ************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": 1
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

All groups vars are merged and flattened to the host level, the expected result is that it always has the same value no matter how you get to that host as part of the play.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
