### ISSUE TITLE
Callback plugin broken : 'Playbook' object has no attribute 'name'

### ISSUE THREAD

**Issue by trompx** [ansible/ansible#14772]
##### Issue Type:
- Bug Report
- Documentation Report
##### Ansible Version:

```
ansible 2.0.1.0
```
##### Ansible Configuration:

callback_plugins = /vagrant/callback_plugins:~/.ansible/plugins/callback_plugins/:/usr/share/ansible_plugins/callback_plugins
callback_whitelist = timestamp
##### Environment:

Ubuntu 14.04 running in a Vagrant VM
##### Summary:

I followed the steps here : https://github.com/ansible/ansible/blob/devel/docsite/rst/porting_guide_2.0.rst to upgrade my callback plugin but the playbook and play object have missing attributes.

```
def v2_playbook_on_start(self, playbook):
        self.playbook = playbook

    def v2_playbook_on_play_start(self, play):
        self.play = play

    def v2_on_any(self, *args, **kwargs):
        self._display.display('%s: %s: %s' % (self.playbook.name,
        self.play.name))
```
##### Expected Results:

Display the playbook.name.
##### Actual Results:

I get 

```
 'Playbook' object has no attribute 'name'
```
##### Extra question:

Is there a file documenting all play and playbook attributes (as it seems some changes occured from 1.9 to 2.0) ? I don't have access anymore to:

```
play.playbook.inventory._subset
play.playbook.remote_user
playbook.extra_vars
```

**Comment by trompx** [comment]
For those interested.

You can get the playbook name with:
`self.playbook_name = os.path.basename(self.playbook._file_name)`

To access all options (like remote_user, tags, skip-tags ...)
`from __main__ import cli
if cli:
    self._options = cli.options
else:
    self._options = None
`

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible-devel on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by trompx** [comment]
Hey @bcoca,

While I totally agree that I should have asked my last question in the mailing list, the original error is triggered by a code referenced in the official documentation supposed to help people upgrade their callback plugin from 1.9 to 2.0. Is the mailing list really the right place to indicate such errors ?

Thanks

**Comment by sivel** [comment]
I've updated the example in the above referenced commits.
