### ISSUE TITLE
Using full st_mode results in difference in check-mode run and real run

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#14771]
##### Issue Type:

- Bug Report
##### Ansible Version:

The issue exists for both 1.9.4 and 2.0.1.0 (and likely any other Ansible version)
##### Summary:

When using (full)python permission modes, Ansible behaves differently in check-mode than it would during a real run.

Granted, this is very unusual for someone to do (except programmatically), but we found it by accident and would prefer to see this fixed.
##### Steps To Reproduce:

When using mode='0100755' which is valid for a real run because Ansible handles it correctly, it fails during check-mode because it was not converted properly.

``` yaml
- hosts: localhost
  gather_facts: no
  tasks:
  - copy:
      src: /etc/fstab
      dest: /tmp/
      mode: '0100755'
```

##### Expected Results:

```
[dag@moria ansible.testing]$ ansible-playbook test71.yml

PLAY ***************************************************************************

TASK [copy] ********************************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

[dag@moria ansible.testing]$ ansible-playbook -CD test71.yml

PLAY ***************************************************************************

TASK [copy] ********************************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

```
[dag@moria ansible.testing]$ ansible-playbook test71.yml

PLAY ***************************************************************************

TASK [copy] ********************************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

[dag@moria ansible.testing]$ ansible-playbook -CD test71.yml

PLAY ***************************************************************************

TASK [copy] ********************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```

**Comment by tonk** [comment]
Just to be curious: What does mode `0100755` do?

I tried it with a file, like:

```
python -c "import os; os.chmod('somefile', 0100755)"
```

and I see no difference.

Would it even be possible to get this mode with `stat` to compare it with the value in the play.

**Comment by dagwieers** [comment]
Doing 0100755 is exactly the same as doing 0755. The value '0100755' is what you get directly from python os.stat() and includes other properties of a file. That's why we have to run stat.S_IMODE() on it, just as it is done for a real run.

The aim is to make the behaviour the same between check-mode and a real run, and we noticed it was not the case for a (admittedly) corner-case.

**Comment by tonk** [comment]
Agree, I was just wondering. This because I think it should be considered an invalid mode. My idea is that modes should be a maximum of 4 (SUID/SGID/Sticky, User, Group, Others). This because these are the ones you can manipulate. Could it be an idea to throw a warning/exception on this mode instead of fixing the check?

**Comment by dagwieers** [comment]
That's a possibility, but I don't see a point really. (It all comes down to what we define as acceptable) I doubt a lot of people will be bothered by this anyway. We caught this one because our filetree plugin returned the raw `os.stat()` value and saw differences between a check-mode run and a real run. And I think we have to avoid that.

BTW We also fixed the filetree plugin to only provide the necessary bits.

PS In Unix you can apparently do `chmod 0000755 file`, but you cannot do `chmod 0100755 file`. I don't think we need to go that far, just use the acceptable bits as `stat.S_IMODE()` is intended for. Just like you mentioned that python accept the complete mode for `os.chmod()`.
https://docs.python.org/2/library/stat.html#stat.S_IMODE

**Comment by tonk** [comment]
I agree we need to avoid that, so during a `check` some routine (didn't check which one, yet) should return `stat.S_IMODE` only and not the complete `stat`. I have a feeling that should not be to hard to find.

**Comment by tonk** [comment]
In `module_utils/basic.py` the code says 

```
prev_mode = stat.S_IMODE(path_stat.st_mode)
```

If you compare that with your mode `0100755` that will fail.

**Comment by dagwieers** [comment]
@tonk It is easy to test and give a warning, I simply don't think it is necessary or even wanted. You can do something like:

```
if (mode != stat.S_IMODE(mode):
    warning()
```

But again, I don't think we have to give warnings if we can do the right thing from the start without warnings.

PS I think we are spending too much time on this easy fix. Let's see what the devs are going to say.

**Comment by tonk** [comment]
Agree, I rather have another cup of coffee :-)

**Comment by bcoca** [comment]
The first three numbers describe the type of filesystem object (file, directory, pipe, etc), its not something you should be trying to use chmod (what mode= is for), they should be ignored.

**Comment by tonk** [comment]
Just added a small pull request, so that everything above the first 4 numbers is ignored.
Nice easy way to start a Friday

**Comment by dagwieers** [comment]
@tonk I think you missed the fact that I already created pull-requests yesterday (even before I logged this issue here). #14769 #14770

**Comment by tonk** [comment]
Yes I did. Probably because the PR was not mentioned here. Just ignore my thingy. It was a nice exercise to find the place where it all went wrong :-)

**Comment by dagwieers** [comment]
@tonk The pull-requests are referenced directly beneath the issue description. (both for 2.x and 1.9.x)
I admit, they are easy to overlook...

**Comment by tonk** [comment]
@dagwieers I just saw them. Stupid mistake. Maybe submit a PR to Github. Make them flashy and red.

**Comment by bcoca** [comment]
pushed this as alternate solution 8867d73420c39b3147e8d1d6910628fe8da99891 and 62ac5c047e29f6a5ecce4ef648d603aef27a28e4
