### ISSUE TITLE
fatal: Quote variables if they contain equal signs broken

### ISSUE THREAD

**Issue by bootstraponline** [ansible/ansible#14783]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### Environment:

OS X 10.11.3
##### Summary:

Ansible fails to correctly parse quoted environment variables.
##### Steps To Reproduce:

Use the following environment variable with ansible.

```
fails:
  env_vars:
    GCLOUDKEY: |-
               ""{
                 "key": "-----BEGIN PRIVATE KEY-----\n.\n.h\n.Q==\n-----END PRIVATE KEY-----\n",
               }""
```

##### Expected Results:

Ansible doesn't error.
##### Actual Results:

Ansible errors.

```
fatal: [localhost] => A variable inserted a new parameter into the module args. Be sure to quote variables if they contain equal signs (for example: "{{var}}").
```

If I modify the values like this then it passes ansible validation.

```
    GCLOUDKEY: |-
               ""{
                 "key": "a-\n.\n.h\n.Q==\n-----a-\n",
               }""
```

Is there a way to disable validation entirely? Why is ansible failing on double quoted input?

**Comment by bcoca** [comment]
the YAML parser needs to be able to read this, use single quotes to quote the text, double quoting is not surpported

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
