### ISSUE TITLE
win_stat returns false for files, shared directories, mapped drives

### ISSUE THREAD

**Issue by alexanderjohn** [ansible/ansible#14785]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

No custom config
##### Environment:

**Host:**
Linux Mint 17
Kernel: 4.2.0-25-generic
Based on: 14.04.1-Ubuntu
Python 2.7.6

**Guest:**
Windows Server 2008 R2
Powershell version: 3
##### Summary:

win_stat returns false when checking for files on a physical drive. It works correctly when testing for a directory.
win_stat returns false when checking for a shared drive for both a directory and file.
win_stat returns false when checking a mapped network drive for both a directory and file.

All 6 tests pass correctly on the windows machine within powershell (3 directory, 3 file) 
`Test-Path C:\Core`
`Test-Path C:\Core\test.txt`
`Test-Path \\<your machine name>\Core`
`Test-Path \\<your machine name>\Core\test.txt`
`Test-Path O:\`
`Test-Path O:\test.txt`
##### Steps To Reproduce:

**Test 1:**
Create a simple `test.txt` file under C:\Core\

**Test 2:**
Publicly Share `C:\Core`.  Set Permissions to Full Control.

**Test 3:**
Under Computer, select "Map network drive"
Select any drive.  Mine was `O:`
Set the folder to: `\\<your machine name>\Core`

```
// Basic file test
- win_stat: path=C:\Core\test.txt
  register: file_info
- debug: var=file_info

// Network share test
- win_stat: path=\\<your machine name>\Core\test.txt
  register: file_info
- debug: var=file_info

// Mapped drive test
- win_stat: path=O:\test.txt
  register: file_info
- debug: var=file_info
```
##### Expected Results:

```
// This is an expected result for all three tests
"file_info": {
        "changed": false, 
        "stat": {
            "attributes": "File", 
            "creationtime": 1247513936.5268176, 
            "exists": true, 
            "extension": ".txt", 
            "isdir": false, 
            "lastaccesstime": 1457005093.923068, 
            "lastwritetime": 1457005093.923068, 
            "owner": "BUILTIN\\Administrato"
        }
    }
```
##### Actual Results:

```
"file_info": {
        "changed": false, 
        "stat": {
            "exists": false
        }
    }
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by KaizounaTOR** [comment]
hi,

It's an old issue but is still present
Could you reopen the issue ?

Thanks !

**Comment by jceddy** [comment]
I'd also like to request this issue be re-opened, as I am seeing the same behavior.

More info:

Running this on the guest system returns "True"

`Test-Path -Path "\\server.dev.comp.local\\path-to\\folder"`

Running this task:

```
- name: check folder
  win_stat:
    path: "\\server.dev.comp.local\\path-to\\folder"
  register: folder_info

- name: debug folder info
  debug:
    var: folder_info
```

returns

```
TASK [webserver : check source folder] *...
task path: /home/joee/ansible/roles/webs...
Using module file /usr/lib/python2.7/sit...
<webserver.dev.com.local> ESTABLIS...
EXEC (via pipeline wrapper)
ok: [webserver.dev.com.local] => {
    "changed": false,
    "stat": {
        "exists": false
    }
}

TASK [webserver : debug publishroot info...
task path: /home/joee/ansible/roles/webs...
ok: [webserver.dev.com.local] => {
    "publishroot_dir": {
        "changed": false,
        "failed": false,
        "stat": {
            "exists": false
        }
    }
}
```

If I change the task to this:

```
- name: check source folder
  win_stat:
    path: \\server.dev.comp.local\path-to\folder
  register: publishroot_dir

- name: debug publishroot info
  debug:
    var: publishroot_dir
```

the result is the same.

**Comment by dejoost** [comment]
Also bumped into this issue. Module correctly finds the path on the machine where the share is located, but fails to find it on remote machines

**Comment by jceddy** [comment]
@dejoost I figured out this is due to the winrm 2 hops issue...you need to use runas when doing anything on the network to force your user to be reauthenticated ... It's a Windows networking quirk where the network machine is treating your credentials as stale

**Comment by dejoost** [comment]
thanks! I knew about that issue but didn't realized it was also interfering in this case. Big thanks!

For the record, i'll try this approach:
become: yes
become_user: current_user
