### ISSUE TITLE
how to loop serial names?

### ISSUE THREAD

**Issue by targetoyes** [ansible/ansible#14792]
I want to loop two name.How to write? Something like this(for example,sytax may be not correct):

```
{% for i in [url1,url2] %}      
      - name: curl
        local_action: curl -I {{i}}
        register: code

      - name: check code
        shell: do otherthing
        when: code.stdout.find('200') == true
{% endfor %}
```

I know that {% for %} is not permitted,but i need something like this.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
