### ISSUE TITLE
Conditionals docs needs updating - filter example 'succeeded' should be 'success'

### ISSUE THREAD

**Issue by Constantin07** [ansible/ansible#14808]
##### Issue Type:
- Documentation Report
##### Ansible Version:

```
ansible 1.9.4
```
##### Ansible Configuration:

Default.
##### Environment:

Any.
##### Summary:

There is a mistake in conditional example given on this page http://docs.ansible.com/ansible/playbooks_conditionals.html#the-when-statement
which is misleading.
##### Steps To Reproduce:

Task fails if it's used "succeeded" as per docs.

```
fatal: [127.0.0.1] => Failed to template {{ tar_res|succeeded }}: template error while templating string: no filter named 'succeeded'
```
##### Expected Results:

```
- command: /bin/something_else
    when: result|success
```
##### Actual Results:

```
- command: /bin/something_else
    when: result|succeeded
```

**Comment by bcoca** [comment]
no, the text is correct, it just should also have 'in previous versions |success was used instead'

**Comment by Constantin07** [comment]
@bcoca You are right. I was testing on 1.9.4 version but having a look at the current guide.

**Comment by vroetman** [comment]
I am using 2.0.1 and "succeeded" gives the same error as above. The docs have confused me several times now. Using "success" works.

**Comment by mattpolicastro** [comment]
Ditto: just upgraded to 2.0.1 and am seeing the same error when "succeeded" is used; "success" still works without error.

**Comment by vroetman** [comment]
Actually, after thinking about it, I recommend accepting all four of success, succeeded, fail, and failed as valid filters. Then there won't be confusion from differing documentation nor confusion about inconsistent parts of speech.

**Comment by Napsty** [comment]
+1 , just fell on my nose because of this (2.0.0.2 here).

**Comment by BuildTheRobots** [comment]
+1 - also just fell on my face, ansible 2.0.2.0 on centos 6. "succeeded" fails with template error, "success" works.

**Comment by dspruell** [comment]
Also confused; on ansible 2.0.2.0 on OS X, this fails:

```
- name: testing
  hosts: localhost

  tasks:
    - name: check for file
      file: state=file path=/etc/hostsX
      ignore_errors: yes
      register: result

    - name: do something
      debug: msg='file was there'
      when: result|succeeded
```

But this works:

```
- name: testing
  hosts: localhost

  tasks:
    - name: check for file
      file: state=file path=/etc/hostsX
      ignore_errors: yes
      register: result

    - name: do something
      debug: msg='file was there'
      when: result|success
```

Based on current docs, expected this to be the other way around.

**Comment by gabordk** [comment]
I'm running 2.0.1.0 and also wasted some time because the documentation is wrong :(
succeeded not working, success works fine.

**Comment by AAlvz** [comment]
Same thing here with ansible 1.7.2. Succeeded fails. Success works.

**Comment by bcoca** [comment]
updated docs, made note of which filters are present before 2.1

**Comment by snowsky** [comment]
Now both should be working.
