### ISSUE TITLE
add client certificate support to uri module (and get_url)

### ISSUE THREAD

**Issue by wasserman** [ansible/ansible#14804]
##### Issue Type:
- Feature Idea
##### Ansible Version:

ansible 2.0.1.0
##### Ansible Configuration:

n/a
##### Environment:

N/A
##### Summary:

I tried to verify the results of a web app deployment via:
  local_action: uri uri=https://myapp/test.html return_contents=yes

The problem is that this app requires a client certificate, so I currently have to resort to this:
  local_action command curl -E ./mycert.pem -k 'https://myapp/test.html'

It would be great if uri (and get_url) supported client certificates so shell command isn't necessary.
##### Steps To Reproduce:

N/A

**Comment by sivel** [comment]
This work in in progress in https://github.com/ansible/ansible/pull/18141

**Comment by sivel** [comment]
This has been resolved in https://github.com/ansible/ansible/pull/18141
