### ISSUE TITLE
save success and failures output and their command output

### ISSUE THREAD

**Issue by ragurampvs** [ansible/ansible#14825]
##### Issue Type:

- Bug Report
##### Ansible Version:

```
<!--- Paste verbatim output from “ansible --version” here -->
```

ansible 1.9.4
  configured module search path = None
##### Ansible Configuration:

nothing hanged. its by default. 
##### Environment:

RHEL 6.5
##### Summary:

i would like to save the succeeded hosts output and failure hosts output. Also including the command(issuing uptime command) output. is it possible to save in a file or how to complete my tasks.
##### Steps To Reproduce:

```
<!--- Paste example playbooks or commands here -->
```

##### Expected Results:

i tried with debug and stdout method but its displaying in our locahost. how to save success and failure output separately which including command output also. 
##### Actual Results:

```
<!--- Paste verbatim command output here -->
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
