### ISSUE TITLE
SLES 11 SP Information Reported by Ansible Inconsistent Between Releases

### ISSUE THREAD

**Issue by paavoap** [ansible/ansible#14837]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.0.2
```
##### Ansible Configuration:

```
$ cat ansible.cfg
[defaults]
inventory = .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory
remote_user = vagrant
private_key_file = .vagrant/machines/default/vsphere/private_key
```
##### Environment:

Running from:

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04 LTS"
```

Managing SLES 11 SP3 and SP4
##### Summary:

The version information between SLES 11 service packs is inconsistent.
##### Steps To Reproduce:

Run Ansible against SLES 11 SP3 and check facts. See following.

```
"ansible_distribution": "SLES",
"ansible_distribution_major_version": "11",
"ansible_distribution_release": "3",
"ansible_distribution_version": "11.3",
```

Run Ansible against SLES 11 SP4 and check facts. See following.

```
"ansible_distribution": "SLES",
"ansible_distribution_major_version": "11",
"ansible_distribution_release": "0",
"ansible_distribution_version": "11.4",
```
##### Expected Results:

Run Ansible against SLES 11 SP4 and check facts. See following.

```
"ansible_distribution": "SLES",
"ansible_distribution_major_version": "11",
"ansible_distribution_release": "4",
"ansible_distribution_version": "11.4",
```
##### Actual Results:

Run Ansible against SLES 11 SP4 and check facts. See following.

```
"ansible_distribution": "SLES",
"ansible_distribution_major_version": "11",
"ansible_distribution_release": "0",
"ansible_distribution_version": "11.4",
```

**Comment by robinro** [comment]
Can you give the content of `/etc/os-release` in both cases? 

I guess the problem is in the lines leading up to
https://github.com/ansible/ansible/blob/66328e5200e1e314af44325cbc6828407b70ac6b/lib/ansible/module_utils/facts.py#L463

**Comment by paavoap** [comment]
**SLES 11.3**

```
> cat /etc/os-release
cat: /etc/os-release: No such file or directory
> cat /etc/SuSE-release
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 3
```

**SLES 11.4**

```
> cat /etc/os-release
NAME="SLES"
VERSION="11.4"
VERSION_ID="11.4"
PRETTY_NAME="SUSE Linux Enterprise Server 11 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:11:4"
> cat /etc/SuSE-release
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 4
```

In SP3 the file /etc/os-release is missing. It's a completely clean install, so I doubt very much that it was removed by me.

I guess in SP3 it'll use `/etc/SuSE-release` instead then. I was looking at it yesterday but didn't have time to get into which one it uses on SP4, and why.

Thanks for taking the time to look into this!

**Comment by robinro** [comment]
I don't know what's going wrong there. I ran the code with your `/etc/SuSE-release` as input and got the correct answer (with distribution_release==4).
I found one bug in the process (see #15088). The parse doesn't stop once a version is found but continues to look for other files. Please check whether #15088 fixes your problem. 

If not, could you step through the code to see which statement actually fills the distribution_release variable?

**Comment by paavoap** [comment]
Using your branch, I get the correct values for SP3 and SP4. Don't have others available right now.

```
    "ansible_distribution": "SLES",
    "ansible_distribution_major_version": "11",
    "ansible_distribution_release": "3",
    "ansible_distribution_version": "11.3",

    "ansible_distribution": "SLES",
    "ansible_distribution_major_version": "11",
    "ansible_distribution_release": "4",
    "ansible_distribution_version": "11.4",
```

Good work. Thanks!

**Comment by robinro** [comment]
@paavoap could you on both distributions run `python -c 'import platform; print(platform.dist())'` for me? Does it output `('SuSE', '11', 'x86_64')`?

I try to refactor the whole distribution_version code and add some tests for it as well. See also https://github.com/ansible/ansible/pull/15221

**Comment by paavoap** [comment]
**SLES 11 SP3**

```
# cat /etc/SuSE-release
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 3
# python -c 'import platform; print(platform.dist())'
('SuSE', '11', 'x86_64')
```

**SLES 11 SP4**

```
# cat /etc/SuSE-release
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 4
# python -c 'import platform; print(platform.dist())'
('SuSE', '11', 'x86_64')
```

And if you're refactoring, these may be helpful too. Notice the deprecation warning.

**SLES 12 SP0**

```
# cat /etc/SuSE-release
SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 0
# This file is deprecated and will be removed in a future service pack or release.
# Please check /etc/os-release for details about this release.
# cat /etc/os-release
NAME="SLES"
VERSION="12"
VERSION_ID="12"
PRETTY_NAME="SUSE Linux Enterprise Server 12"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12"
# python -c 'import platform; print(platform.dist())'
('SuSE', '12', 'x86_64')
```

**SLES 12 SP1**

```
# cat /etc/SuSE-release
SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 1
# This file is deprecated and will be removed in a future service pack or release.
# Please check /etc/os-release for details about this release.
# cat /etc/os-release
NAME="SLES"
VERSION="12-SP1"
VERSION_ID="12.1"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP1"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp1"
# python -c 'import platform; print(platform.dist())'
('SuSE', '12', 'x86_64')
```

**Comment by robinro** [comment]
thanks @paavoap 
can you check the output of `ansible localhost -m setup | grep distribution` on SLES 12?

SLES 12.0:

> ```
>                 "ansible_distribution": "SLES",
>                 "ansible_distribution_major_version": "12",
>                 "ansible_distribution_release": "0",
>                 "ansible_distribution_version": "12",
> ```

SLES 12.1:

> ```
>                 "ansible_distribution": "SLES",
>                 "ansible_distribution_major_version": "12",
>                 "ansible_distribution_release": "1",
>                 "ansible_distribution_version": "12.1",
> ```

'12' instead of '12.0' is a bit confusing, but it's probably best to stick to the existing output if that is the case.

I put those in 7237a654cb894f1685db45fea500beda8ea70fda

**Comment by paavoap** [comment]
Here's what I got.

```
    "ansible_distribution": "SLES",
    "ansible_distribution_major_version": "12",
    "ansible_distribution_release": "0",
    "ansible_distribution_version": "12",
```

And

```
    "ansible_distribution": "SLES",
    "ansible_distribution_major_version": "12",
    "ansible_distribution_release": "1",
    "ansible_distribution_version": "12.1",
```

**Comment by robinro** [comment]
@paavoap perfect :+1:

**Comment by ssbarnea** [comment]
Don't get confused reading the commands here, `ansible_distribution_release` points to `18.2.0` on MacOS `10.14.2` (`ansible_distribution_version=10.14.2`), so it may not be what you are looking for.

I am still trying to find a way to correctly extract the minor and patch subparts of the `ansible_distribution_version`.
