### ISSUE TITLE
Docker module - consul support

### ISSUE THREAD

**Issue by RajanAOz** [ansible/ansible#14839]
##### Issue Type:
- Feature Idea or bug? 
##### Ansible Version:

ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### Ansible Configuration:

default config file, no changes at all.
##### Environment:to connect toto connect to

Ubuntu 14.04.4 LTS
##### Summary:

I am trying to start a docker container (registrator) which has required parameter for connecting to consul.

Starting this container via the command line (inside a virtualbox env)
$ docker run -d --name=registrator --net=host --volume=/var/run/docker.sock:/tmp/docker.sock dockerregistryurl:5000/registrator:latest consul://consulurl:8500

registrator.yml
`---`
`- name: application container`
`docker:`
`name: registrator`
`image: gliderlabs/registrator:latest`
`state: started`
`pull: missing`
`restart_policy: always`
`net: host`
`volumes:`
`- "/var/run/docker.sock:/tmp/docker.sock"`

I have tried the following parameters, neither of them seem to do the trick;
`extra_hosts: "consul://consulurl:8500"`
`env: "consul://consulurl:8500"`

Would be great to add an 'freeformat' parameter in this particular case.

**Comment by zentavr** [comment]
Seems like `consul://consulurl:8500` should be in `command:`, no?

**Comment by RajanAOz** [comment]
Works like a charm, thank you!
