### ISSUE TITLE
user module ssh_key=generate keys are owned by root instead of user

### ISSUE THREAD

**Issue by roller** [ansible/ansible#1484]
Using ssh_key generate option, the key generated for the user as well as the .ssh directory are owned by root.  The user created has no access to their own key.

This is easily solved using the file module, but it would be more convenient to default access to the user.

ie:
- user: name=test1 group=users ssh_key=generate
- file: path=/home/test1/.ssh state=directory owner=test1 group=users mode=0600
- file: path=/home/test1/.ssh/id_rsa state=file owner=test1 group=users mode=0600
- file: path=/home/test1/.ssh/id_rsa.pub state=file owner=test1 group=users mode=0644

**Comment by mpdehaan** [comment]
Definitely agreed.

cc @sfromm (think this was your PR) in case you wanted to tweak this, otherwise I'll get to it later.

Thanks!

**Comment by sfromm** [comment]
This was fixed.  It looks like commit  bf53aee3 broke it.  I'll revisit this shortly.

**Comment by sfromm** [comment]
Please disregard last comment; I misread which module this was about.  Still working on it.

**Comment by mpdehaan** [comment]
thanks!

**Comment by roller** [comment]
Thanks for the quick patch!
