### ISSUE TITLE
Ansible fails on python3 due to basestring check

### ISSUE THREAD

**Issue by hahnicity** [ansible/ansible#14841]
##### Issue Type:

- Bug Report
##### Ansible Version:

ansible==2.0.1.0
##### Ansible Configuration:

```
[defaults]
roles_path=roles/
deprecation_warnings=False

[privilege_escalation]
become=True
become_user=root
become_ask_pass=True
```
##### Environment:

```
(venv)host:ansible greg$ python --version
Python 3.4.4
```
##### Summary:

Ansible fails to run because it performs an isinstance(<something>, basestring) check. basestring was removed from python3. You will probably have to catch the NameError in python 3.
##### Steps To Reproduce:

Install ansible in python3 virtualenv
##### Expected Results:

Playbook runs
##### Actual Results:

Stack shows up

```
SUDO password:
ERROR! Unexpected Exception: name 'basestring' is not defined
the full traceback was:

Traceback (most recent call last):
  File "/Users/greg/workspace/python/meg-server/venv/bin/ansible-playbook", line 86, in <module>
    sys.exit(cli.run())
  File "/Users/greg/workspace/python/meg-server/venv/lib/python3.4/site-packages/ansible/cli/playbook.py", line 150, in run
    results = pbex.run()
  File "/Users/greg/workspace/python/meg-server/venv/lib/python3.4/site-packages/ansible/executor/playbook_executor.py", line 79, in run
    self._tqm.load_callbacks()
  File "/Users/greg/workspace/python/meg-server/venv/lib/python3.4/site-packages/ansible/executor/task_queue_manager.py", line 147, in load_callbacks
    elif isinstance(self._stdout_callback, basestring):
NameError: name 'basestring' is not defined
```

**Comment by richard-scott** [comment]
I didn't think Ansible supported running on Python3 just yet:
http://docs.ansible.com/ansible/intro_installation.html#control-machine-requirements

**Comment by sivel** [comment]
Ansible does not yet support Python 3.  This is an eventual goal that we are working towards, however we are not ready to start accepting bug reports due to Python 3 incompatibility.

We have made `six` a dependency of Ansible to facilitate this, and if you are interested, please feel free to submit small targeted pull requests addressing Python 3 compatibility.
