### ISSUE TITLE
consider timeout around setup module socket.getfqdn calls

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1485]
In the event of bad DNS, it seems there should be a relatively short timeout around the pieces of the setup module that use socket.getfqdn.

**Comment by nigelm** [comment]
I have code for this now.  Just need to test on the home network where I was seeing the issue (work network is doing everything it can to scupper my testing :-/ )

**Comment by jpmens** [comment]
> In the event of bad DNS

Bad DNS? Whazzat? ;-)

**Comment by nigelm** [comment]
Timeout code fails to work usefully (yes, it times out, but it takes the full time to do that - ie a 40 second delay still - so no advantage to the extra complexity).
My python-fu is insufficient to work out why I cannot/how to force an early termination to the socket.getfqdn() call

Work to date is in
  https://github.com/nigelm/ansible/tree/setup_timeout
  https://github.com/nigelm/ansible/commit/9347e4886d8646f6949cdd764565f9c535784e12

**Comment by mpdehaan** [comment]
It would pretty much have to be a fork/exec/kill or something.

Perhaps not worth it.
