### ISSUE TITLE
Not able to use remove_dups="yes" option for lineinfile module in ansible 1.9.4 version

### ISSUE THREAD

**Issue by srikanthanumolu** [ansible/ansible#14855]
##### Issue Type:

- Bug Report
- Feature Idea
- Documentation Report
##### Ansible Version:
- 1.9.4

```
<!--- Paste verbatim output from “ansible --version” here -->
```
##### Summary:
- Tried using remove_dups option for lineinfile module but got the below error
  
  msg: unsupported parameter for module: remove_dups
  FATAL: all hosts have already failed -- aborting

##### Steps To Reproduce:

```
<!--- Paste example playbooks or commands here -->
```

##### Expected Results:
- Expected to remove the duplicate entries

##### Actual Results:
- Got error for using remove_dups module

```
<!--- Paste verbatim command output here -->
```

**Comment by sivel** [comment]
`remove_dups` Is not an option for `lineinfile`.  See http://docs.ansible.com/ansible/lineinfile_module.html

**Comment by srikanthanumolu** [comment]
But as per this issue #9006 it was commented saying "lineinfile now has "remove_dups" option which removes duplicate lines  …
matched by regexp. Fixes #9006"

**Comment by sivel** [comment]
That commit was never merged into ansible.  It was made in a fork, indicating that it fixes that issue number, but it looks as though no pull request was ever submitted containing that change.

**Comment by srikanthanumolu** [comment]
ok Thank you. Is there any option in lieninfile module or somemodule to remove the duplicate lines based on regexp?
