### ISSUE TITLE
synchronize module has no diff mode

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#14865]
##### Issue Type:

- Feature Idea
##### Summary:

The synchronize module does not support diff mode. It would be nice if it supported diff mode.

**Comment by sivel** [comment]
Synchronize does support diff now, and will be included in 2.1

https://github.com/ansible/ansible-modules-core/blob/a7cfa1c8cda0dcff5bf3c8e0a5d36b30cf63f68f/files/synchronize.py#L426-L430

**Comment by dagwieers** [comment]
This is excellent news !
I was going to propose to implement this for $CUSTOMER, but this is better ;-)

**Comment by dagwieers** [comment]
Hmm, I just tested the diff-mode output, and it simply shows the changes (as they were in the json output before), but not the diff of the content. We would need the diff output of the content of files. So reopening...

```
TASK [role : Synchronize files] *****************************************************
changed: [system1 -> system1]
.d...p..... ./
>f..Tp..... path/to/file.ini
changed: [system2 -> system2]
.d...p..... ./
>f..Tp..... path/to/file.ini
```

**Comment by dagwieers** [comment]
Another concern we have is that the synchronize module also considers timestamp differences as changes, whereas Ansible doesn't consider timestamp differences as changes. So I think we have to modify the sycnhronize module to also understand that some differences are not considered changes.

**Comment by towolf** [comment]
The synchronize module is fundamentally tied to rsync — a tool only interested in binary differences. You can run rsync with `-c` to only consider file contents. This is mapped in the module by setting `checksum=yes` and `archive=no`.

The thing with rsync is that there is no other sensible log of the changes but the native `rsync --itemize-changes` output. This is why we are using `diff['prepared']` and not `'before'` vs `'after'`

To get file diffs you would have to slurp the content of every synched file beforehand and after the module's run to have them diffed.

**Comment by dagwieers** [comment]
@towolf I know how rsync works. But nothing prevents us from e.g. looking at the rsync diff and then start comparing the files in check-mode for files reported to have different checksums. In order to get a full diff. Or propose a diff-mode for the rsync tool (for text-files) and hook into that (long-term).

**Comment by towolf** [comment]
When I implemented diff  mode for synchronize, I asked around in my office and what I was told by all was that they want exactly the output of `rsync --itemize-changes`.

It definitely depends on the use cases, but around here what synchronize seems to be used for mostly is shuffling large file trees around (with `local_action` or `delegate_to`). The interesting info at that level is "which files were changed" and not "show me thousands of lines of output".

Maybe for your use case another module entirely should be created. Something behaving more like `diff -r` cum `patch` than `rsync`.

**Comment by dagwieers** [comment]
My $CUSTOMER is using synchronize for trees with templated files, but also new deployment material. So for them it is essential to see what exactly was changed during (phased) deployments.

However, if we would have a recursive template module and delegated lookup plugins, we could probably do the same as synchronize, and still have those diffs.

**Comment by dagwieers** [comment]
No longer interested to pursue this...
