### ISSUE TITLE
ansible_*_interpeter hardcoded to python

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1486]
It appears we lost the ability to do things like ansible_ruby_interpeter when we needed to pick a specific one.  This hard code logic should be removed and this should be refactored into utils

**Comment by bcoca** [comment]
I have a patch that adds this, it needs some more testing but I'll submit soon.

from what i can tell the current code only does this for delegate_to, not for general actions

**Comment by mpdehaan** [comment]
yeah, it really needs to do both.

**Comment by dhozac** [comment]
The delegate_to code only ensures that the interpreters for the delegated node are used. Actually using a different interpreter is done in _copy_module.

**Comment by bcoca** [comment]
that is where i patch, but only see the python one there now

**Comment by mpdehaan** [comment]
right, and that's the bug.  I'm not sure when it was lost.

**Comment by bcoca** [comment]
I have preliminary patch, works on all interpreters in shebang line, but lacks 2 things:
- support for env, the patch actually removed env from the 3 core modules that used it (against the project's policy).
- support for additional parameters (python -tt).

If I have time I'll add the 2nd as it seems easy, env I need to rethink as it is not as simple as I thought.

**Comment by mpdehaan** [comment]
IMHO, if "/env " is found in the interpreter line, we don't really want to
look in any variables, and should use at as is.   There's no need to
override it in that case, as they said "let the remote path decide".

Should make that part pretty simple.

**Comment by bcoca** [comment]
it was brought up by a user in discussion, as my initial patch ignored it. I only considered it because 3 core modules had it, which my patch now removes.

I'm fine with ignoring it in the future, I think we just need to enforce not using env in core modules.

**Comment by mpdehaan** [comment]
Yeah, I think that will have to be something we have to do when reviewing
contributions, as if someone writes their own and just decided to use env,
I would like it if it still worked.

**Comment by bcoca** [comment]
interpreters not overridden are ignored, so unless you set the ansible_env_interpreter, env doesn't get touched

**Comment by mpdehaan** [comment]
exactly, just clarifing what "we should enforce" would mean to me :)
