### ISSUE TITLE
ec2.py return a maximum of 100 rds instances from AWS

### ISSUE THREAD

**Issue by obutterbach** [ansible/ansible#14861]
##### Issue Type:

- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
```
##### Ansible Configuration:

None
##### Environment:

Debian
##### Summary:

When using the script `ec2.py` to pull information from AWS, your list of RDS instances would be limited to 100 results only.
This is due to module RDS in boto:
http://boto.cloudhackers.com/en/latest/ref/rds.html#module-boto.rds
Method name: `get_all_dbinstances`
##### Steps To Reproduce:

```
ec2.py --list | grep rds
```

Inside the above script, you'll find the following:

```
    def get_rds_instances_by_region(self, region):
        ''' Makes an AWS API call to the list of RDS instances in a particular
        region '''

        try:
            conn = self.connect_to_aws(rds, region)
            if conn:
                instances = conn.get_all_dbinstances()
                for instance in instances:
                    self.add_rds_instance(instance, region)
```

##### Expected Results:

Receive a list of all RDS instances present on AWS
##### Actual Results:

Limitation of 100 RDS instances

**Comment by Sodki** [comment]
Looks like `get_all_dbinstances` by default returns only 100 records and uses pagination if you want more records, so there's an extra iterative operation needed in order to get all results.

**Comment by bcoca** [comment]
i need to find the ticket, already added paging for another module, we should just add a generic function for all aws objects as they seem to have the same paging interface

**Comment by bcoca** [comment]
please test the above PR

**Comment by obutterbach** [comment]
@bcoca Thanks a lot for your really fast reply / PR too, 
I just give a try and it didn't work unfortunately, the result was successfully displayed but didn't return all our RDS instances.
I also try to increase `max_records` option, it didn't work neither
Following that bug: https://github.com/boto/boto/issues/3109, paginate option might contains a bug in first place (if that can help)

**Comment by bcoca** [comment]
what version of boto do you have installed? older versions did not support the marker

**Comment by obutterbach** [comment]
Here is the version that I'm using:

```
root@d854f9ed55c7:/ansible# pip list
ansible (2.0.1.0)
ansible-vault (1.0.4)
boto (2.39.0)
...
```

**Comment by Sodki** [comment]
I wonder it boto3 has this issue. According to #13010 the support is coming with Ansible 2.1.

**Comment by Sodki** [comment]
@bcoca I've commented on your PR with a fix for @butterbacho's issue.

**Comment by bcoca** [comment]
so currently this seems like a bug in boto boto/boto#3109
