### ISSUE TITLE
template module leaves empty tmp directories

### ISSUE THREAD

**Issue by aabdnn** [ansible/ansible#14867]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

ANSIBLE_HOST_KEY_CHECKING=no
ANSIBLE_SSH_PIPELINING=yes
ANSIBLE_INVENTORY=/Users/anandb/repos/ripe/ansible/hosts
ANSIBLE_GATHERING=smart
ANSIBLE_REMOTE_TEMP=/tmp
ANSIBLE_SSH_CONTROL_PATH=/Users/anandb/.ssh/mux/%%r@%%h:%%p
ANSIBLE_HASH_BEHAVIOUR=merge
ANSIBLE_TIMEOUT=75
ANSIBLE_RETRY_FILES_ENABLED=no
##### Environment:

Manager host: Mac OSX 10.11
Managed host: CentOS 6
##### Summary:

The template module fails to remove the temporary directory it creates on the managed host.
##### Steps To Reproduce:

Use the template module in a playbook to expand any template out to a file on a managed host. Then log into the managed host, and look in the directory where ansible creates temporary directories, and there will be an empty directory called something like ansible-tmp-1457463409.12-185316296988336.
##### Expected Results:

The temporary directory should have been deleted.
##### Actual Results:

The temporary directory was empty and left behind.

**Comment by jhawkesworth** [comment]
win_template also does this and have been investigating under https://github.com/ansible/ansible-modules-core/issues/3032

**Comment by bcoca** [comment]
it is not a module issue, for some reason we are creating extra temp dirs we don't clean up.

**Comment by jhawkesworth** [comment]
I think https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/template.py#L72 might be what is causing the tmp dir to get created.
