### ISSUE TITLE
Error in mount module documentation

### ISSUE THREAD

**Issue by jiv-e** [ansible/ansible#14876]
##### Issue Type:

Documentation Report
##### Summary:

fstab(8) should probably be mount(8) on page http://docs.ansible.com/ansible/mount_module.html.
##### Steps To Reproduce:
1. Go to http://docs.ansible.com/ansible/mount_module.html
2. See that documentation refers to fstab(8).
3. Google fstab(8).
4. Ensure there's no documentation with this label.
##### Expected Results:

I would expect to find fstab(8) documentation.
##### Actual Results:

I didn't find the documentation. Instead it seems that mount(8) should be the right label for the documentation.

**Comment by bcoca** [comment]
fstab(5)

**Comment by bcoca** [comment]
fixed via http://github.com/ansible/ansible-modules-core/commit/84501dbe13a5c17f1282b4fe73dc5b5f017b2c18
