### ISSUE TITLE
ansible-galaxy init creates file with trailing whitespace

### ISSUE THREAD

**Issue by Linuturk** [ansible/ansible#14881]
##### Issue Type:

- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides

```
##### Ansible Configuration:

None
##### Environment:

N/A
##### Summary:

When creating a default empty role using `ansible-galaxy init rolename` the resulting `meta/main.yml` file contains trailing whitespace that fails `ansible-lint` testing. 
##### Steps To Reproduce:

```
pip install ansible-lint
ansible-galaxy init testrole
ansible-lint testrole/meta/main.yml
```
##### Expected Results:

Expect to have a file without trailing whitespace.
##### Actual Results:

```
[ANSIBLE0002] Trailing whitespace
/home/ubuntu/CloudFormations/roles/MicrosoftAD/meta/main.yml:3
  description: 

[ANSIBLE0002] Trailing whitespace
/home/ubuntu/CloudFormations/roles/MicrosoftAD/meta/main.yml:5


[ANSIBLE0002] Trailing whitespace
/home/ubuntu/CloudFormations/roles/MicrosoftAD/meta/main.yml:9


[ANSIBLE0002] Trailing whitespace
/home/ubuntu/CloudFormations/roles/MicrosoftAD/meta/main.yml:18


[ANSIBLE0002] Trailing whitespace
/home/ubuntu/CloudFormations/roles/MicrosoftAD/meta/main.yml:28


[ANSIBLE0002] Trailing whitespace
/home/ubuntu/CloudFormations/roles/MicrosoftAD/meta/main.yml:157
```

**Comment by bcoca** [comment]
ansible-lint is not an official spec nor project

**Comment by Linuturk** [comment]
I agree. I do think having trailing whitespace in the default `ansible-galaxy init` is a bad thing and falls under the ansible project.

**Comment by Linuturk** [comment]
If you point me in the direction of the skeleton for the `ansible-galaxy init` command I'll happily submit a PR resolving this. @bcoca

**Comment by tima** [comment]
https://github.com/ansible/ansible/search?utf8=✓&q=execute_init&type=Code

**Comment by Linuturk** [comment]
So I followed the rabbit hole down to https://github.com/ansible/ansible/blob/06fa841516fadf4454d8aa05609786a7b9f14b3b/lib/ansible/galaxy/__init__.py#L66 and I can't seem to find the `metadata_template.j2` Jinja2 template. The extra whitespace is most likely in that template based on the code so far.

Does anyone know where that is? A search of this repository didn't return any file by that name.

Scratch that. Searching on GitHub is flaky I guess.
https://github.com/ansible/ansible/blob/06fa841516fadf4454d8aa05609786a7b9f14b3b/lib/ansible/galaxy/data/metadata_template.j2

**Comment by tima** [comment]
While github's search isn't the best for finding a file, doing a `find | grep` of a clone copy turns it up:

https://github.com/ansible/ansible/tree/devel/lib/ansible/galaxy/data

**Comment by tima** [comment]
Nice work. Thanks for your persistence @Linuturk.
