### ISSUE TITLE
ar

### ISSUE THREAD

**Issue by david-w-millar** [ansible/ansible#14913]
##### Issue Type:

- Bug Report
- Feature Idea
- Documentation Report
##### Ansible Version:

```
<!--- Paste verbatim output from “ansible --version” here -->
```
##### Steps To Reproduce:

```
<!--- Paste example playbooks or commands here -->
```

##### Actual Results:

```
<!--- Paste verbatim command output here -->
```

**Comment by sivel** [comment]
Going to assume this was created by accident

**Comment by david-w-millar** [comment]
Yep. Sorry about that!
