### ISSUE TITLE
Add strategy modification to cli

### ISSUE THREAD

**Issue by tonglil** [ansible/ansible#14939]
##### Issue Type:
- Feature Idea
##### Ansible Version:

```
ansible --version
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

None
##### Environment:

OS X El Capitan
##### Summary:

Allow strategy to be modified by a cli flag. This will help editing playbook files to change the strategy of a run.
##### Steps To Reproduce:

```
ansible-playbook play.yml --strategy linear|free|serial
```
##### Expected Results:

Run using a specific strategy

**Comment by gawel** [comment]
Hi,

I need this feature. Is there any plan for it ? Is it ok if I provide a PR ?

**Comment by bcoca** [comment]
no current plan, but we will consider a PR. I would advise this sets the 'default' strategy (also config/env var option).
