### ISSUE TITLE
这玩意杂用啊？好像有bug 好像很多人用

### ISSUE THREAD

**Issue by shengxinjing** [ansible/ansible#14941]
##### Issue Type:

- Bug Report
- Feature Idea
- Documentation Report
##### Ansible Version:

```
<!--- Paste verbatim output from “ansible --version” here -->
```
##### Steps To Reproduce:

```
<!--- Paste example playbooks or commands here -->
```

##### Actual Results:

```
<!--- Paste verbatim command output here -->
```

**Comment by tuxknight** [comment]
Please review the [guidelines](https://github.com/ansible/ansible/blob/devel/CONTRIBUTING.md) for contributing to this repository. 

Going to assume this was created by accident
