### ISSUE TITLE
Don't skip shell/command action in check mode when you know it won't run

### ISSUE THREAD

**Issue by youam** [ansible/ansible#14950]
##### Issue Type:
- Feature Idea
##### Ansible Version:

```
ansible 2.1.0 (devel 89cace28ea) last updated 2016/03/13 08:54:43 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 8d126bd877) last updated 2016/02/14 18:03:05 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD f6c5ed987f) last updated 2016/02/14 18:03:05 (GMT +200)
  config file = /home/youam/work/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

no relevant changes. updates ansible users and lookup path
##### Environment:

N/A (debian jessie)
##### Summary:

In check mode, the command and shell modules always are skipped with

```
{"changed": false, "msg": "remote module does not support check mode", "skipped": true}
```

Usually, that is correct as command/shell actions are hard to predict. There are exceptions, though, when some behaviour can be predicted. This happens when the 'creates' or 'deletes' arguments are given and those files do (or do not) exist. In this case, the module can tell that the action would not be skipped, but okay. That would make the check output more readable as it is obvious that this action would be a NOP.
##### Steps To Reproduce:

test.yml:

```

---

- hosts: localhost
  accelerate: false
  gather_facts: false

  tasks:
    - name: Command which does nothing really but should know that in check mode
      command: "echo hello world"
      args:
        creates: /bin/bash
```
##### Expected Results:

```
$ ansible-playbook test.yml --check --verbose                                                   
Using /home/youam/work/projects/ansible-staging/ansible.cfg as config file

PLAY [localhost] ***************************************************************

TASK [Command which does nothing really but should know that in check mode] ****
okay: [localhost] => {"changed": false, "msg": "command will not execute as /bin/bash exists"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

```
$ ansible-playbook test.yml --check --verbose                                                   
Using /home/youam/work/projects/ansible-staging/ansible.cfg as config file

PLAY [localhost] ***************************************************************

TASK [Command which does nothing really but should know that in check mode] ****
skipping: [localhost] => {"changed": false, "msg": "remote module does not support check mode", "skipped": true}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0   
```

**Comment by dagwieers** [comment]
You can already add:

```
always_run: yes
```

and this will cause the task to be run in check-mode and emit the output you expects (I think).
Can you test ?

**Comment by bcoca** [comment]
closing as per above, this feature already exists

**Comment by youam** [comment]
But then it would also actually run (if there was anything to do), which i don't want. I just want to know that it would not do anything.

**Comment by slanglois** [comment]
FWIW: `always_run` has been deprecated in Ansible 2.2 -- see http://docs.ansible.com/ansible/latest/playbooks_checkmode.html

The modern equivalent is now: `check_mode: no`
