### ISSUE TITLE
ansible-galaxy module

### ISSUE THREAD

**Issue by ilyapoz** [ansible/ansible#14966]
##### Issue Type:
- Feature Idea
##### Ansible Version:

2.0.1.0

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Summary:

I see a good use for ansible-galaxy module which would support ensuring that some roles from ansible galaxy are installed locally.
This would be great for bootstrapping development environment in general and would solve the following use case in particular.
Vagrant has ansible_local provider which installs ansible on a virtual machine and runs provisioning from inside it. The natural part of this process is to install requirement ansible galaxy roles. Right now it's done by explicitly running ansible-galaxy, which I find inconvenient, because it's already provisioning if taken literally (and should be done by ansible itself). I want to execute a galaxy role that will download roles from galaxy as the first step, then execute everything else.

This could also help mitigate issues like this: #11266 
##### Steps To Reproduce:

in playbook:

```
galaxy: requirements=requirements.yml state=installed
```
##### Expected Results:

roles from requirements.yml are installed

**Comment by jimi-c** [comment]
@ilyapoz we've actually talked about adding this functionality to the role definition itself, so that roles could be optionally downloaded if they weren't available locally. This would use the src value (as its used in requirements.yml) or Galaxy if src is not set.

**Comment by ilyapoz** [comment]
Yeah that sounds simpler now that I think of it :)

**Comment by bcoca** [comment]
https://github.com/ansible/proposals/issues/7

**Comment by jimi-c** [comment]
Since this is a proposal, I'm going to go ahead and close this now.

Thanks!
