### ISSUE TITLE
Setup MODULE FAILURE: "dns" list index out of range

### ISSUE THREAD

**Issue by nicolas-g** [ansible/ansible#14969]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
```
##### Environment:

Controller : OSX 10.11.3
Target Machine : CentOS release 6.4 (Final)
##### Summary:

This is a really strange behaviour , we have about 200 servers in our environment and since we upgrade to Ansible version 2 we are seeing errors on a specific groups of servers. With Ansible version 1.9 this is confirmed to be working so this bug seems to be specific for Ansible version 2.

When running ansible-playbook during the gather fact or if we run ansible setup module we get a "MODULE FAILURE" .
##### Steps To Reproduce:

ansible -i hosts/prod/main adservers -m setup
##### Expected Results:

Ansible should return the target node facts.
##### Actual Results:

```
ads001.aws.example.com| FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "setup"
    },
    "module_stderr": "OpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /Users/nicolasg/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 65946\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to ads001.aws.example.com closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/nicolasg/.ansible/tmp/ansible-tmp-1457997862.29-128926168741392/setup\", line 5184, in <module>\r\n    main()\r\n  File \"/home/nicolasg/.ansible/tmp/ansible-tmp-1457997862.29-128926168741392/setup\", line 140, in main\r\n    data = run_setup(module)\r\n  File \"/home/nicolasg/.ansible/tmp/ansible-tmp-1457997862.29-128926168741392/setup\", line 84, in run_setup\r\n    facts = ansible_facts(module)\r\n  File \"/home/nicolasg/.ansible/tmp/ansible-tmp-1457997862.29-128926168741392/setup\", line 5119, in ansible_facts\r\n    facts.update(Facts().populate())\r\n  File \"/home/nicolasg/.ansible/tmp/ansible-tmp-1457997862.29-128926168741392/setup\", line 2272, in __init__\r\n    self.get_dns_facts()\r\n  File \"/home/nicolasg/.ansible/tmp/ansible-tmp-1457997862.29-128926168741392/setup\", line 2860, in get_dns_facts\r\n    self.facts['dns']['domain'] = tokens[1]\r\nIndexError: list index out of range\r\n",
    "msg": "MODULE FAILURE",
    "parsed": false
}
```

**Comment by bcoca** [comment]
that is weird, do you have an empty domain entry in your hosts file?

**Comment by nicolas-g** [comment]
@bcoca  what do you man ? all the hosts in my inventory are real DNS addresses , hosts that are up and reachable . As I wrote in the issue this is happening only with Ansible version 2 , 1.9 is working fine.

**Comment by bcoca** [comment]
Not your inventory file, I meant your /etc/resolv.conf on the target (i called it hosts by mistake), the only way this error crops up is if you have a line like this:

```
domain 
```

^ it should have something after domain, in any case I added error handling in current devel to avoid this (see commit above).

the reason you don't see this before 2.0 is that /etc/resolv.conf was not parsed for facts before then.

**Comment by nicolas-g** [comment]
hi @bcoca , yes it seems we had a `domain` on every hosts that was affected. Removing this works now.

Thank you so much .
