### ISSUE TITLE
Publish to pypi

### ISSUE THREAD

**Issue by vmalloc** [ansible/ansible#1497]
Although getting ansible through the "quick and dirty" manner is very useful for hacking scenarios, including it as a part of other projects requires being able to set it up from _easy_install_ or _pip_.

It would be great if this tool was published in pypi for each new release

**Comment by skorokithakis** [comment]
This is a duplicate of #595.

**Comment by mpdehaan** [comment]
Which should be doable once we adapt the pull request for #1509

**Comment by mpdehaan** [comment]
I will take this personally when we release for 0.9.

**Comment by trompette** [comment]
@mpdehaan what's the status of this issue now that 0.9 has been released?

**Comment by mpdehaan** [comment]
status is mdehaan got distracted by new job.

Putting a note on my fridge to do it this week :)

**Comment by mpdehaan** [comment]
done! see note on the mailing list for further details.

**Comment by vmalloc** [comment]
w00t!
