### ISSUE TITLE
Support running without a hosts file

### ISSUE THREAD

**Issue by vmalloc** [ansible/ansible#1498]
On some occasions it makes sense to run a certain command on one host or a group of host only for experimentation or testing, in which case it would be great if ansible received this as an argument, rather than a hosts file pointed to by _-i_.

**Comment by dhozac** [comment]
This already exists, just use -i 'hostname,'

**Comment by vmalloc** [comment]
Awesome. thanks!

**Comment by mpdehaan** [comment]
yeah the comma is important so it knows it is not a file.  You can use multiple hosts as long as there is at least one comma.
