### ISSUE TITLE
hostvar for sudo_path?

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#1500]
The SSH connection plugins (paramiko and ssh) rely on `sudo` being on `$PATH`. I'd like to propose a host variable (like ansible_ssh_host) called `sudo_path` or something, in order to specify the path to sudo on a per host/group basis.

Case in point is Solaris 10 which has `/usr/local/bin/sudo`. Although I could use `raw` module to create a symlink in /usr/bin, this is not possible in Solaris zones which have a read-only root filesystem, and setting `$PATH` in, say, `.bashrc` isn't being evaluated with a paramiko connection.

**Comment by jpmens** [comment]
And this is ticket 1500; do I get a prize? ;-)

**Comment by mpdehaan** [comment]
Urrrg.  Yes.  Please send in a pull request.   It should be ansible_ prefixed like ansible_sudo_path to remain consistent.

**Comment by mpdehaan** [comment]
We now have a configurable sudo exe that should solve this problem, though it is globally settable.

Pull requests ok if you want something else and need to tweak that in inventory/etc.
