### ISSUE TITLE
Can install ansible MacOS X  El Capitan

### ISSUE THREAD

**Issue by mgamboa** [ansible/ansible#15017]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
Latest 2.0.1
```
##### Ansible Configuration:

None
##### Environment:

MacOS X el Capitan
##### Summary:

 Try to install ansibelk and is failed
CFLAGS=-Qunused-arguments CPPFLAGS=-Qunused-arguments pip install ansible
Collecting ansible
  Using cached ansible-2.0.1.0.tar.gz
Collecting paramiko (from ansible)
  Using cached paramiko-1.16.0-py2.py3-none-any.whl
Collecting jinja2 (from ansible)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting PyYAML (from ansible)
  Using cached PyYAML-3.11.tar.gz
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from ansible)
Collecting pycrypto>=2.6 (from ansible)
  Using cached pycrypto-2.6.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): ecdsa>=0.11 in /Library/Python/2.7/site-packages (from paramiko->ansible)
Collecting MarkupSafe (from jinja2->ansible)
  Using cached MarkupSafe-0.23.tar.gz
Installing collected packages: pycrypto, paramiko, MarkupSafe, jinja2, PyYAML, ansible
  Running setup.py install for pycrypto ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;**file**='/private/tmp/pip-build-yqJGIQ/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-3TdeZ6-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.11-intel-2.7
    creating build/lib.macosx-10.11-intel-2.7/Crypto
    copying lib/Crypto/**init**.py -> build/lib.macosx-10.11-intel-2.7/Crypto
    copying lib/Crypto/pct_warnings.py -> build/lib.macosx-10.11-intel-2.7/Crypto
    creating build/lib.macosx-10.11-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/**init**.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/hashalgo.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/HMAC.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/MD2.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/MD4.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/MD5.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/RIPEMD.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA224.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA256.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA384.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA512.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Hash
    creating build/lib.macosx-10.11-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/**init**.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/AES.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/ARC2.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/ARC4.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/blockalgo.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/Blowfish.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/CAST.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/DES.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/DES3.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/PKCS1_OAEP.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/PKCS1_v1_5.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/XOR.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Cipher
    creating build/lib.macosx-10.11-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/**init**.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/_number_new.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/asn1.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/Counter.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/number.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/py21compat.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/py3compat.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/randpool.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/RFC1751.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/winrandom.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Util
    creating build/lib.macosx-10.11-intel-2.7/Crypto/Random
    copying lib/Crypto/Random/__init__.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Random
    copying lib/Crypto/Random/_UserFriendlyRNG.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Random
    copying lib/Crypto/Random/random.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Random
    creating build/lib.macosx-10.11-intel-2.7/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/__init__.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/FortunaAccumulator.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/FortunaGenerator.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/SHAd256.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Random/Fortuna
    creating build/lib.macosx-10.11-intel-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/**init**.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/fallback.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/nt.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/posix.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/rng_base.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Random/OSRNG
    creating build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest
    copying lib/Crypto/SelfTest/**init**.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest
    copying lib/Crypto/SelfTest/st_common.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest
    creating build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/**init**.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/common.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_AES.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_ARC2.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_ARC4.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_Blowfish.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_CAST.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_DES.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_DES3.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_pkcs1_15.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_pkcs1_oaep.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_XOR.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Cipher
    creating build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/**init**.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/common.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_HMAC.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_MD2.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_MD4.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_MD5.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_RIPEMD.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA224.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA256.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA384.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA512.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Hash
    creating build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/**init**.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_AllOrNothing.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_chaffing.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_KDF.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_rfc1751.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Protocol
    creating build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/**init**.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_DSA.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_ElGamal.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_importKey.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_RSA.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/PublicKey
    creating build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/**init**.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/test__UserFriendlyRNG.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/test_random.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/test_rpoolcompat.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Random
    creating build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/**init**.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaAccumulator.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaGenerator.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/test_SHAd256.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Random/Fortuna
    creating build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/**init**.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_fallback.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_generic.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_nt.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_posix.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_winrandom.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Random/OSRNG
    creating build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/**init**.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_asn1.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_Counter.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_number.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_winrandom.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Util
    creating build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Signature
    copying lib/Crypto/SelfTest/Signature/**init**.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Signature
    copying lib/Crypto/SelfTest/Signature/test_pkcs1_15.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Signature
    copying lib/Crypto/SelfTest/Signature/test_pkcs1_pss.py -> build/lib.macosx-10.11-intel-2.7/Crypto/SelfTest/Signature
    creating build/lib.macosx-10.11-intel-2.7/Crypto/Protocol
    copying lib/Crypto/Protocol/**init**.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Protocol
    copying lib/Crypto/Protocol/AllOrNothing.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Protocol
    copying lib/Crypto/Protocol/Chaffing.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Protocol
    copying lib/Crypto/Protocol/KDF.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Protocol
    creating build/lib.macosx-10.11-intel-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/**init**.py -> build/lib.macosx-10.11-intel-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/_DSA.py -> build/lib.macosx-10.11-intel-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/_RSA.py -> build/lib.macosx-10.11-intel-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/_slowmath.py -> build/lib.macosx-10.11-intel-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/DSA.py -> build/lib.macosx-10.11-intel-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/ElGamal.py -> build/lib.macosx-10.11-intel-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/pubkey.py -> build/lib.macosx-10.11-intel-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/RSA.py -> build/lib.macosx-10.11-intel-2.7/Crypto/PublicKey
    creating build/lib.macosx-10.11-intel-2.7/Crypto/Signature
    copying lib/Crypto/Signature/__init__.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Signature
    copying lib/Crypto/Signature/PKCS1_PSS.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Signature
    copying lib/Crypto/Signature/PKCS1_v1_5.py -> build/lib.macosx-10.11-intel-2.7/Crypto/Signature
    running build_ext
    running build_configure
    checking for gcc... gcc
    checking whether the C compiler works... no
    configure: error: in `/private/tmp/pip-build-yqJGIQ/pycrypto':
    configure: error: C compiler cannot create executables
    See`config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-yqJGIQ/pycrypto/setup.py", line 456, in <module>
        core.setup(**kw)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 53, in run
        return _install.run(self)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 573, in run
        self.run_command('build')
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/tmp/pip-build-yqJGIQ/pycrypto/setup.py", line 251, in run
        self.run_command(cmd_name)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/tmp/pip-build-yqJGIQ/pycrypto/setup.py", line 278, in run
        raise RuntimeError("autoconf error")
    RuntimeError: autoconf error

```
----------------------------------------
```

Command "/usr/bin/python -u -c "import setuptools, tokenize;**file**='/private/tmp/pip-build-yqJGIQ/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-3TdeZ6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-yqJGIQ/pycrypto/
##### Steps To Reproduce:

Already Attached

```
No playbook involve
```

##### Expected Results:

 Installation success
##### Actual Results:

Error to install

```
<!--- Paste verbatim command output here -->
```

**Comment by acsrujan** [comment]
I hope you've installed 'xcode' before doing 'pip install ansible'. And also, setuptools installed.

I had same issue and resolved by installing xcode and setuptools.

```
curl -o setuptools-0.6c11-py2.6.egg http://pypi.python.org/packages/2.6/s/setuptools/setuptools-0.6c11-py2.6.egg#md5=bfa92100bd772d5a213eedd356d640;
sudo sh setuptools-0.6c11-py2.6.egg;
rm setuptools-0.6c11-py2.6.egg
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

In any case, it seems like you are trying to use python3, Ansible currently only runs under python2.

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by mgamboa** [comment]
Well apparently is solved installing xcode because is needed the gcc , but in the instructions are no mention at all of it so ansible guys please include on the instructions that is needed Xcode to install ansible

**Comment by cordesc** [comment]
Installing xcode worked for me as well. For those not familiar see: http://railsapps.github.io/xcode-command-line-tools.html
