### ISSUE TITLE
win_file cannot find Windows directories that start with a period

### ISSUE THREAD

**Issue by slimandslam** [ansible/ansible#15029]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### Environment:

From: Macosx Yosemite
Managing: Windows Server 2012R2
##### Summary:

When trying to delete directory on Windows Server that starts with a period, it cannot find it.
##### Steps To Reproduce:

```
- name: Remove .git directory from skeleton
   win_file: path="C:\myrepo\.git" state=absent
```

##### Expected Results:

.git directory is deleted
##### Actual Results:

```
...
"ScriptLineNumber": 294, "ScriptName": "C:\\Users\\Administrator\\AppData\\Local\\Temp\\ansible-tmp-1458250643.09-3144975677314\\win_file.ps1", "UnboundArguments": []}, "PSMessageDetails": null, "PipelineIterationInfo": [], "ScriptStackTrace": "at <ScriptBlock>, C:\\Users\\Administrator\\AppData\\Local\\Temp\\ansible-tmp-1458250643.09-3144975677314\\win_file.ps1: line 294\r\nat <ScriptBlock>, <No file>: line 4", "TargetObject": "C:\\myrepo\\.git"}, "failed": true, "invocation": {"module_name": "win_file"}, "msg": "Could not find item C:\\myrepo\\.git."}
```

**Comment by jhawkesworth** [comment]
Yaml and windows paths are tricky to mix.

I suspect you will find the following will work

``` yaml
- name: Remove .git directory from skeleton
   win_file: path=C:\myrepo\.git state=absent
```

or 

``` yaml
- name: Remove .git directory from skeleton
   win_file: path="C:\\myrepo\\.git" state=absent
```

If you are double quoting windows paths, I would recommend using double backslash for the path separator, because things like c:\temp can be interpreted as c:TAB_CHARACTERemp without the second \ 

Hope this means you can at least work around this problem.

Jon

**Comment by slimandslam** [comment]
The tricky part is that hardly anyone documents these things.  :-)
Thanks for the tip. 

J

**Comment by nitzmahone** [comment]
Sounds like the typical escaping issues between YAML and backslashed paths. You can also safely use forward slashes in paths for _nearly_ every Windows module...
