### ISSUE TITLE
Rare MySQLdb exception raised when remote host mysql client lacks SSL support!

### ISSUE THREAD

**Issue by saumets** [ansible/ansible#15026]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.1.0 (devel 2dd6bae9e1) last updated 2016/03/17 11:31:25 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 345d9cbca8) last updated 2016/03/16 14:49:13 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD f9b96b9a8a) last updated 2016/03/16 14:49:16 (GMT -400)
  config file =
  configured module search path = Default w/o overrides
```
##### Environment:

OS X El Capitan 10.11.3
Ubuntu 14.04 LTS

But this could affect any random remote host. 
##### Summary:

In the case where SSL support is requested with the mysql_db module, then all is fine and we should receive an exception. 

The problem occurs in the rare case where a remote host machine's client library may not have SSL support, or it's disabled - but we're not even asking for SSL through our mysql_db tasks. 

The _mysql_connect_ utility function creates a config 'ssl' key with empty dict and then processes configuration requests and populates the 'ssl' dict with required parameters, if needed. In the case where no ssl parameters are sent (no ssl_ca, ssl_cert, or ssl_key parameters through mysql_db module) the config still passes an empty 'ssl' key with empty dict.

As per MySQLdb documentation:
http://mysql-python.sourceforge.net/MySQLdb.html

```
ssl
This parameter takes a dictionary or mapping, where the keys are parameter names used by the mysql_ssl_set MySQL C API call. If this is set, it initiates an SSL connection to the server; if there is no SSL support in the client, an exception is raised. This must be a keyword parameter. 
```

We are passing a config with the 'ssl' key set, albeit empty, and this is forcing MySQLdb to initiate an SSL connection to server. As per docs an exception occurs if there is no SSL support in the client. 

BUT...we are not even requesting an SSL connection so this exception should not be occurring! 
##### Steps To Reproduce:

1) Using core _mysql_db_ module create a simple task such as database dump.

```
- name: Dump database(s).
  mysql_db: login_user="{{ item.user }}" login_host="{{ item.host }}" login_password={{ item.pass }} name={{ item.name }} state=dump target={{ temporary_backup_folder }}{{ item.filename }}.sql.gz
  with_items: "{{ databases }}"
```

2) Note that no SSL parameters are set, so we are **not** requesting an SSL connection.

3) Attempt to run this task against a remote host where there is no SSL support in the client.

4) The task will fail with msg: 

```
"msg": "unable to connect to database, check login_user and login_password are correct or /home2/your_home/.my.cnf has the credentials. Exception message: client library does not have SSL support"
```
##### Expected Results:

If no SSL parameters are passed to a remote host, and the remote host  does not have MySQL SSL support enabled then our mysql_db tasks **should** still complete. We did not even request an SSL connection. The exception should only occur if we pass SSL parameters, thereby requesting an SSL connection, but no SSL support is available.
##### Actual Results:

Currently our tasks fail if the remote host does not have mysql SSL support enabled, even though we are not even requesting an SSL connection.
##### Fix:

I'm creating a Pull Request as I've fixed this issue on my fork. 

The fix is simple in that before we ask MySQLdb to connect we check to see if our config 'ssl' dict is still empty. If it's still empty then we know that no SSL parameters have been passed and that the user is not requesting an SSL connection. We remove the 'ssl' key from the configuration being passed to MySQLdb.

**Comment by amenonsen** [comment]
Closed via #14924.
