### ISSUE TITLE
Variables expands as __omit_place_holder_CHECKSUM

### ISSUE THREAD

**Issue by bjne** [ansible/ansible#15034]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.1.0
##### Summary:

When using default(omit) from a role dependency, the variables are later
expanded as __omit_place_holder_CHECKSUM
##### Steps To Reproduce:

meta/main.yml:

```
--
dependencies:
  - { role: foobar
       some_variable: "{{some_extra_variable | default(omit)}}"
     }
```

roles/foobar/defaults/main.yml

```
some_variable: foo
```

roles/foobar/tasks/main.yml

```
- command: mkdir /tmp/{{ some_variable }}
```

When foobar role is run, some_variable is expanded as __omit_place_holder_CHECKSUM
and not as I expected, the default for the foobar role.
##### Expected Results:

mkdir /tmp/foo
##### Actual Results:

mkdir /tmp/__omit_place_holder_CHECKSUM

**Comment by Id2ndR** [comment]
Bug still present in 2.1.0.0 using template module in my case.

**Comment by Id2ndR** [comment]
Explanation: _That is due to "omit" only working for top level keys (arguments of the module) and not sub keys._ (from https://groups.google.com/d/msg/ansible-project/Gz1WYxpqIy0/cgdGwro51qgJ)

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The 'omit' placeholder is designed to cancel out options of a module, not for generic var 'undefining'.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
