### ISSUE TITLE
local_action equivalent as a task and block parameter

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#15048]
##### Issue Type:
- Feature Idea
##### Summary:

Local_action equivalent as a task and block parameter.

Let's say you have multiple tasks that should be run locally. Specifying local_action for each task takes time. You may also have different scenarios and require local task execution only in part of them. So having a bool type option would be nice.

**Comment by bcoca** [comment]
you already have this: `connection: local`

**Comment by mdevicariis** [comment]
The connection: local only works for the entire play. Only one connection can be used per host at a time. If you're targeting remote hosts and need to do a several tasks locally (eg. send an email, unzip and read a file, etc), then that won't work.

It would really be helpful to have allow a block to be run locally. See example below.

- name: unzip and read file
  local_action:
    block:
      - name: unzip local file
         unarchive:
           src: /path/to/file.zip
           dest: /tmp/dir
      - name: read file
        xml:
           src: /path/to/file.xml
      - name: send email
         mail:
           host: "{{ acas_report_email_host }}"
           port: "{{ acas_report_email_port | default(25) }}"
           secure: "never"
           subject: "ACAS scan report for {{ acas_report_ReportHost.matches[0].ReportHost.name }}"
           subtype: html
      - name: delete file
        file:
           path: /path/to/file
           state: absent
