### ISSUE TITLE
Unable to import role under personal user account instead of organization

### ISSUE THREAD

**Issue by tersmitten** [ansible/ansible#15045]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
2.0.1.0
```
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

I'm unable to import (new) roles under my user account (tersmitten). In Github the role path is Oefenweb/ansible-fonts, but I want to import to tersmitten/fonts in galaxy. This is because all my other roles (+/- 100) are under tersmitten too. Is there any way to do that?

When I re-import old roles they import just fine under tersmitten.
##### Steps To Reproduce:

N/A
##### Expected Results:

Be able to specify or change the destination (user) on the galaxy side.
##### Actual Results:

Not able to specify or change the destination (user) on the galaxy side.

**Comment by bcoca** [comment]
You want to open a ticket here: https://github.com/ansible/galaxy-issues

**Comment by tersmitten** [comment]
I will do that. Thanks
