### ISSUE TITLE
inconsistency in ini_file doc: backup=yes instead of backup=true

### ISSUE THREAD

**Issue by hyao** [ansible/ansible#1504]
The backup arg options are: 

choices: [ "yes", "no" ]

but in the ini_file example (2 occurrences):

code: "ini_file: dest=/etc/conf section=drinks option=fav value=lemonade mode=0600 backup=true"

ini_file: dest=/etc/anotherconf
                     section=drinks
                     option=temperature
                     value=cold
                     backup=true

**Comment by mpdehaan** [comment]
The boolean filter should accept both, but yes, we should fix the example.

Thanks!

**Comment by mpdehaan** [comment]
fixed, will be included next time I push docs
