### ISSUE TITLE
EC2 dynamic inventory script should vary cache file when using different AWS profiles

### ISSUE THREAD

**Issue by OwenTuz** [ansible/ansible#15067]
PR below, just creating an issue to tie it to. This is based on the latest version in the 'devel' branch.

The EC2 inventory script currently caches AWS API lookups in "<configurable cache_path>/ansible-ec2.cache". 

For those of us who manage multiple AWS accounts, this is a problem as if I run the inventory script in account A, then in account B within the cache expiry time (5 minutes by default), I receive the cached results from account A.

At best, this is inconvenient, but at worst could lead to playbooks being executed against hosts in the wrong account (...no, I haven't, but it is the sort of thing I would manage to do).

This can already be worked around by keeping multiple ec2.ini config files, each with a different cache path. However, for a more sensible default and simpler behaviour out of the box, I would prefer to simply vary the cache filename depending on the Boto profile in use.

The attached PR uses the profile (if present) to form part of the cache filename.

**Comment by amenonsen** [comment]
Closed via #15068.
