### ISSUE TITLE
Powershell version of custom module being executed on Linux instead of the python version in Ansible 2.0.1.0.

### ISSUE THREAD

**Issue by gbevan** [ansible/ansible#15064]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.1.0
##### Ansible Configuration:

--module-path to a custom library folder
##### Environment:

From Ubuntu 14.04 LTS, in this case targetting Ubuntu (specifically not Windows for this issue)
##### Summary:

I am providing a custom module pair, e.g.: mymodule.ps1 and mymodule.py in a lib folder pointed to by --module-path, with Ansible 2.0.1.0 and targeting a Linux endpoint, getting:

Results:
127.0.0.1 | FAILED! => {
"changed": false,
"failed": true,
"module_stderr": "",
"module_stdout": "/bin/sh: 1: powershell: not found\r\n",
"msg": "MODULE FAILURE",
"parsed": false
}

It is clearly executing the .ps1 version of the module instead of the .py version on a linux target.

This worked fine with Ansible 1.9.4 and earlier.

This issue is preventing us from migrating to Ansible v2.
##### Steps To Reproduce:

see above
##### Expected Results:

I expect powershell version of the module to execute on windows and the python version to execute on Linux/Unix.
##### Actual Results:

The powershell version of the module is taking precedence over the python version when targeting a Linux endpoint - this is clearly incorrect.

**Comment by jhawkesworth** [comment]
Hi @gbevan any chance you could share your playbook?  If it involves delegating I believe there may have been a relevant fix recently in latest development version.

**Comment by gbevan** [comment]
Hi @jhawkesworth , in this case there is no actual playbook - just running the module directly from ansible command, e.g.:

```
/usr/bin/ansible -i inv --module-path lib/ -m mymodule tgt-host
```

**Comment by bcoca** [comment]
cc @nitzmahone @abadger

**Comment by gbevan** [comment]
hi, i notice 2.0.2 is in rc - will this issue be fixed in that upcoming release?  Also, is there a patch/commit that I can use in the meantime?

**Comment by nitzmahone** [comment]
Unfortunately, I think this is a "won't fix". The fact that this worked in 1.x is arguably a bug- you basically have an unresolvable module name collision (which we're considering at least adding warnings for, if not errors). As we expand Ansible's module language and connection capabilities on various platforms, it's important that we eliminate hardcoded exceptions like, "ssh connections don't like .ps1 modules" that made this sort-of-work in 1.x. In fact, it's already not true (SSH+Powershell on Windows).

As an alternative, if you want the same playbook to run on both Windows and Linux, I'd suggest using an inventory- or fact-based prefix variable on your module names. eg:

```
  tasks:
  - name: run platform-specific module
    action: "{{platform}}_mymodule"
```

where platform would be set to win or linux in your inventory, and you'd have win_mymodule.ps1 and linux_mymodule.py in your library folder. That way, there's no ambiguity or connection-based magic required to divine which module to run.

**Comment by gbevan** [comment]
Understood - though as i think i mentioned earlier - we have a case where we are executing a module directly - not from within a playbook.  I think i have a way to work around that though - thx.

**Comment by nitzmahone** [comment]
Yes, an action plugin could do the proper module delegation for you based on a fact (eg, action mymodule.py could exec win_mymodule or linux_mymodule based on the value of some var), and would work from the ad-hoc runner. Just name the modules something different from the action (and each other, of course).

**Comment by gbevan** [comment]
yep, I've got that working now. I've also got the use case of the standalone module being able to run the setup module to gather facts in the action plugin.  Thx for the advice.
