### ISSUE TITLE
Regression: roles dir is no more found when plays are in a subfolder

### ISSUE THREAD

**Issue by mathieumd** [ansible/ansible#15061]
##### Issue Type:
- Bug Report
##### Ansible Version:

Issues started with commit db1d153, but is still present with the most recent devel.

```
ansible 2.1.0 (detached HEAD db1d153aca) last updated 2016/03/21 10:50:50 (GMT +200)
  lib/ansible/modules/core: (detached HEAD fcb3397df7) last updated 2016/03/21 10:50:03 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD c6829752d8) last updated 2016/03/21 10:50:03 (GMT +200)
  config file = /home/mathieu/dev/rectorat-ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Environment:

N/A
##### Summary:

When playbooks are stored in a subfolder, roles are no more found. Up until commit d89d795 is was working, but since db1d153 it is no more.

```
tree
.
├── ansible.cfg
├── group_vars
│   ├── all
├── host_vars
├── inventory
├── playbooks
│   ├── site.yml
│   ├── ...
├── roles
│   ├── bertvv.tftp
│   │   ├── ...
│   ├── ...
...
```
##### Steps To Reproduce:

Move your playbooks into a subfolder, then launch it:

```
pwd
/home/mathieu/dev/ansible-root

grep common playbooks/site.yml
- include: common.yml

ls roles/vmwaretools
defaults/  meta/  README.md  tasks/  tests/

ansible-playbook playbooks/site.yml -vvvv
```
##### Expected Results:

The subfolder `roles` in the current working directory should still be searched for, as it was before commit db1d153.
##### Actual Results:

```
ERROR! the role 'vmwaretools' was not found in /home/mathieu/dev/ansible-root/playbooks/roles:/home/mathieu/dev/ansible-root/playbooks:/etc/ansible/roles

The error appears to have been in '/home/mathieu/dev/ansible-root/playbooks/common.yml': line 27, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
  - { role: vmwaretools, when: ansible_virtualization_type == 'VMware' }
    ^ here
```

**Comment by bcoca** [comment]
This is not a bug, `cwd` is not predictable, roles are and should be searched only relative to play. 
If you are at /var/tmp and then run  `ansible-playbook ~/playbooks/play.yml` would you want a 'unexpected roles dir' to be used?.

I'm going to close this as it works as designed.

**Comment by mathieumd** [comment]
Fair point. Still, it would have been nice to set a "deprecated notice" before purely dropping support for such relative roles path.
In the meantime, you can use "[roles_path](http://docs.ansible.com/ansible/intro_configuration.html#roles-path) = ./roles/" in `ansible.cfg`.

**Comment by bcoca** [comment]
@mathieumd this was never an intended feature, but a bug and a security issue, we normally deprecated features but fix bugs/vulnerabilities immediately.
