### ISSUE TITLE
] in the end of hostname

### ISSUE THREAD

**Issue by Labutin** [ansible/ansible#15063]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible --version
ansible 2.0.1.0
  config file =
  configured module search path = Default w/o overrides
##### Ansible Configuration:

Default
##### Environment:

Mac OS
brew install ansible
##### Summary:

Look at this output

root@109.234.x.x SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
root@109.234.x.x SSH: PlayContext set ssh_common_args: ()
root@109.234.x.x SSH: PlayContext set scp_extra_args: ()
root@109.234.x.x SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/Users/dmtrylabutin/.ansible/cp/ansible-ssh-%h-%p-%r)
root@109.234.x.x SSH: EXEC scp -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/dmtrylabutin/.ansible/cp/ansible-ssh-%h-%p-%r /var/folders/ld/wcxt9y19391887xksz0kl3280000gn/T/tmpBkaQB0 '[root@109.234.x.x]:/root/.ansible/tmp/ansible-tmp-1458561636.37-69112287758331/setup'
fatal: [root@109.234.x.x]: FAILED! => {"failed": true, "msg": "failed to transfer file to /root/.ansible/tmp/ansible-tmp-1458561636.37-69112287758331/setup:\n\nExecuting: program /usr/bin/ssh host 109.234.x.x], user [root, command scp -v -t /root/.ansible/tmp/ansible-tmp-1458561636.37-69112287758331/setup\nOpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/Users/dmtrylabutin/.ansible/cp/ansible-ssh-109.234.x.x]-22-[root\" does not exist\r\nssh: Could not resolve hostname 109.234.x.x]: nodename nor servname provided, or not known\r\nlost connection\n"}

And look at 
Could not resolve hostname 109.234.x.x]

Why ]  in hostname?!

My inventory looks like:
[server]
root@109.234.x.x

No ] in the end of hostname.

**Comment by dagwieers** [comment]
Would you happen to have something in your _/etc/ssh/ssh_config_ or _~/.ssh/config_ that could explain this ?

**Comment by Labutin** [comment]
cat  /etc/ssh/ssh_config | grep -v "^#"

```
        Host *
            SendEnv LANG LC_*
```

ls -l ~/.ssh/config

ls: /Users/dmtrylabutin/.ssh/config: No such file or directory

**Comment by Labutin** [comment]
ssh -V

OpenSSH_6.9p1, LibreSSL 2.1.8

**Comment by jimi-c** [comment]
A while back, the ssh connection was modified to use a host syntax that was neutral to IPv6 and inserted `[]` around the hostname, however I don't understand why in this case it's showing up only with the closing bracket.

**Comment by ktosiek** [comment]
Shouldn't `[` be after the `@`?

**Comment by jimi-c** [comment]
@ktosiek that could be the cause, if the hostname is being specified as user@host, and then later being split on the @. I'll have to dig into it.

@Labutin could you share your inventory file?

**Comment by Labutin** [comment]
Here is my inventory file  /ust/local/etc/ansible/hosts:

```
[mfprice_docker]
root@109.234..x.x ansible_ssh_private_key_file=~/.ssh/id_rsa
```

**Comment by amenonsen** [comment]
> root@109.234..x.x ansible_ssh_private_key_file=~/.ssh/id_rsa

This (user@host) is not supported syntax.

**Comment by Labutin** [comment]
@amenonsen You are right.
W/o root@ all work fine.
My mistake.

**Comment by jimi-c** [comment]
We should raise an error on that rather than splitting it anymore.

**Comment by amenonsen** [comment]
> We should raise an error on that rather than splitting it anymore.

We would, but for the "if valid, add host; else, add host anyway" logic.
