### ISSUE TITLE
win_chocolatey error: "The package was not found with the source listed"

### ISSUE THREAD

**Issue by sparkvilla** [ansible/ansible#15073]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
```
##### Ansible Configuration:

My `ansible.cfg` file:
    [defaults]
    hostfile = ./hosts

My `hosts` file:
    [win_clones]
    windows ansible_host=172.18.4.16 ansible_password="pass"

My `group_vars/win_clones` file: 
    ansible_user: diego
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore 

My `choco_test.yml` playbook:
    -name: Test
     hosts: windows10
     tasks:
       - name: Install/Uninstall
         win_chocolatey: 
           name: vlc
           state: present
##### Environment:

Host = ubuntu 15.10 VM
Client = windows10 VM
I use a shared folder on NAS at : \174.18.4.17\choco-repo\choco-repo\
##### Summary:

I would like to use win_chocolatey module to pull vlc package present on my shared folder using Ansible. I therefore run:
ansible-playbook choco_test.yml
##### Actual Results:

I get the following error:

```
fatal: [windows10]: FAILED! => {"changed": false, "choco_error_cmd": "choco.exe install -dv -y vlc     -source \\\\172.18.4.15\\choco-repo\\choco-repo\\", "choco_error_log": "Chocolatey is running   on Windows v 10.0.10586.0 Attempting to delete file \"C:/ProgramData/chocolatey/choco.exe.old\". Attempting to delete file \"C:\\ProgramData\\chocolatey\\choco.exe.old\". Command line: \"C:\\ProgramData\\chocolatey\\choco.exe\" install -dv -y vlc -source \\\\172.18.4.15\\choco-repo\\choco-repo\\ Received arguments: install -dv -y vlc -source \\\\172.18.4.15\\choco-repo\\choco-repo\\  NOTE: Hiding sensitive configuration data! Please double and triple   check to be sure no  sensitive data is shown, especially if copying   output to a gist for review. Configuration: CommandName='install'| CacheLocation='C:\\Users\\diego\\AppData\\Local\\Temp'| ContainsLegacyPackageInstalls='True'| CommandExecutionTimeoutSeconds='2700'| Sources='\\\\172.18.4.15\\choco-repo\\choco-repo\\'|Debug='True'| Verbose='True'|Force='False'|Noop='False'|HelpRequested='False'| RegularOutput='True'|QuietOutput='False'|PromptForConfirmation='False'| AcceptLicense='True'|AllowUnofficialBuild='False'|Input='vlc'| AllVersions='False'|SkipPackageInstallProvider='False'| PackageNames='vlc'|Prerelease='False'|ForceX86='False'| OverrideArguments='False'|NotSilent='False'|IgnoreDependencies='False'| AllowMultipleVersions='False'|AllowDowngrade='False'| ForceDependencies='False'|Information.PlatformType='Windows'| Information.PlatformVersion='10.0.10586.0'| Information.PlatformName='Windows'| Information.ChocolateyVersion='0.9.9.11'| Information.ChocolateyProductVersion='0.9.9.11'| Information.FullName='choco, Version=0.9.9.11, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|  Information.Is64Bit='True'|Information.IsInteractive='False'| Information.IsUserAdministrator='True'| Information.IsProcessElevated='True'|Features.AutoUninstaller='True'| Features.CheckSumFiles='True'|Features.FailOnAutoUninstaller='False'| ListCommand.LocalOnly='False'| ListCommand.IncludeRegistryPrograms='False'| UpgradeCommand.FailOnUnfound='False'| UpgradeCommand.FailOnNotInstalled='False'| UpgradeCommand.NotifyOnlyAvailableUpgrades='False'| NewCommand.AutomaticPackage='False'|SourceCommand.Command='unknown'| SourceCommand.Priority='0'|FeatureCommand.Command='unknown'| ConfigCommand.Command='unknown'|PushCommand.TimeoutInSeconds='0'| PinCommand.Command='unknown'| _ Chocolatey:ChocolateyInstallCommand - Normal Run Mode _ Installing the following packages: vlc By installing you accept licenses for the packages. vlc not installed. The package was not found with the source(s) listed.  If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.  Version: \"\"  Source(s): \"\\\\172.18.4.15\\choco-repo\\choco-repo\\\"  Chocolatey installed 0/1 package(s). 1 package(s) failed.  See the log for details (C:\\ProgramData\\chocolatey\\logs\\chocolatey.log). Failures:  - vlc Exiting with 1", "failed": true, "msg": "Error installing vlc"}
```

NOTE: I can pull vlc package from the shared folder using chocolatey directly from the client by running:

```
choco install vlc -y
```

Any help?

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
