### ISSUE TITLE
Refactor facts.py os version detection

### ISSUE THREAD

**Issue by robinro** [ansible/ansible#15087]
##### Issue Type:
- Bug Report
##### Ansible Version:

devel
##### Summary:

facts.py at the moment has up to 12 levels of indentation in the code that determines the os release. This is barly readble and should be cleaned up. see
https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts.py#L486

Also one could rewrite it a little to separate readline files in /etc/*release from the parsing such that one can have unit tests for the parsing.

I'd be happy to contribute if such a refactor is of interest to the core team.

**Comment by jimi-c** [comment]
We'd definitely be interested. Thanks!
