### ISSUE TITLE
Ansible 2 not availabe in epel 6-8 repo.

### ISSUE THREAD

**Issue by preethi29** [ansible/ansible#15091]
##### Issue Type:

- Bug Report
##### Ansible Version:

```
ansible 2.0.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### Summary:

Ansible 2.0 rpm is not available in epel 6-8 repo yet. It is available only from epel 7 repo. Is it expected?
We want to install ansible in one of our prod envs. We tried using pip but it requires gcc to be installed. We dont want install any compiler in our prod env.

**Comment by abadger** [comment]
We don't directly package ansible for the EPEL repositories.  However, we do have a close relationship with the maintainers there.  The plan is to have Ansible-1.9.x available in the epel stable updates repository and ansible-2.x available in the updates-testing repository for a while (The current thinking is until ansible-2.1.0 is released (end of April) but it may happen a bit sooner if it seems that most of the backwards incompatible bugs are addressed sooner).

If you want Ansible-2.0 now you should be able to enable the epel-testing repository and install it from there.  If you only want to install the new ansible from the epel-testing repository but not have it enabled all the time, you can do something like this:

```
yum --enablerepo='epel-testing' update ansible
```

or as an ansible playbook:

```
---
- hosts: rhel6
  tasks:
    - yum:
        name: ansible
        enablerepo: epel-testing
        state: latest
```
