### ISSUE TITLE
Using Display() to print custom messages to a local connection

### ISSUE THREAD

**Issue by lipanski** [ansible/ansible#15090]
##### Issue Type:
- Bug Report
- Question
##### Ansible Version:

```
ansible 2.0.1.0
```
##### Environment:

Ubuntu 14.04
##### Summary:

I run a set of custom modules which are ment for local connections.

I was trying to use [Display()](https://github.com/ansible/ansible/blob/00b8b4911203724f5fdc6631240a62c0ac924a6f/lib/ansible/utils/display.py) to print out some custom output - ideally in **real-time**.
##### Steps To Reproduce:

This would be my (simplified) custom module:

``` python
# library/output.py

#!/usr/bin/python

from ansible.utils.display import Display
display = Display() # also tried Display(x) here - where x = 0..5
display.display(u"hello world")
display.vv(u"hello world")
display.banner(u"hello world")

print "{}"
```

This would be the playbook using the custom module (emphasis on the local connection).

``` yml
# output.yml

- hosts: localhost
  connection: local
  tasks:
  - output:
```

These are the various ways I tried to run this:

``` sh
ansible-playbook output.yml
ansible-playbook output.yml -vvv
ansible-playbook output.yml -f 1
PYTHONUNBUFFERED=1 ansible-playbook output.yml
```

I also tried combinations of these (one fork & verbose etc.)
##### Expected Results:

The playbook call would print at least one of the `hello world` messages I passed to `Display()`.
##### Actual Results:

Neither of the commands did print anything to the output. Ansible still prints the default output though.

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [output] ******************************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0 
```
##### Questions

(1) My first intention was to get something custom printed out. Do you have any idea how I can accomplish this (from within the custom module, ideally not via `debug`)? How can I get `Display()` to work as intended?

(2) My ideal solution would involve having real-time output (even before the module finished running). I've read through [this](https://github.com/ansible/ansible/issues/3887#issuecomment-54672569) but I imagine that using a local connection would simplify things a lot (no SSH pipe). Do you have any suggestions of how I could get real-time output to my local connection from a **custom module** / whether this is possible for a custom module?

Thank you :cake:

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- IRC: #ansible-devel on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
