### ISSUE TITLE
Documentation: please put documentation for all versions online.

### ISSUE THREAD

**Issue by COLABORATI** [ansible/ansible#15101]
I can not find the documentation for old versions of ansible - this is horrible. Please fork the Django documentation and use it as a base for the ansible docs before releasing new versions. 

Thank you very much for your attention!

**Comment by sivel** [comment]
Hosting documentations for older versions of ansible is on the todo list.  In the mean time, the contents of the documentation site is located in github at https://github.com/ansible/ansible/tree/devel/docsite/rst and can be browsed there.  By selecting a different branch or tag from the "Branch" dropdown, you can browse the documentation for old versions.

**Comment by COLABORATI** [comment]
Ok, but why did you close this issue? It would still be great as a reminder until the documentation was rebuild with versioning in mind! Thanks!
