### ISSUE TITLE
yum_repo module link broken

### ISSUE THREAD

**Issue by rgroten** [ansible/ansible#15100]
##### Issue Type:
- Documentation Report
##### Ansible Version:

n/a
##### Ansible Configuration:

n/a
##### Environment:

n/a
##### Summary:

yum_repo module link is broken on http://docs.ansible.com/ansible/list_of_all_modules.html likely because yum_repo module was renamed to yum_repository.  This link works: http://docs.ansible.com/ansible/yum_repository_module.html
##### Steps To Reproduce:

n/a
##### Expected Results:

Docs for yum_repository module should load 
##### Actual Results:

Link is broken, get Page Not Found.

**Comment by bcoca** [comment]
it works for me, are you sure you don't have a cached page?

**Comment by rgroten** [comment]
Hmm you're right, must have been cached on my side like you said.  Thanks @bcoca
