### ISSUE TITLE
Documentation: please add a search to the docs

### ISSUE THREAD

**Issue by COLABORATI** [ansible/ansible#15102]
The docs have no search function, at least I can not find one. It is annoying to use a search engine for this, too much noise, also it would be a very good feature to limit the search to certain versions of ansible.

Please fork the Django documentation before releasing new versions.

Until you have that done, you could setup a google custom search or similar feature to enable some minimal search facility for your users. 

Thank you very much for your attention!

**Comment by sivel** [comment]
The documentation site at https://docs.ansible.com/ansible does already have search enabled.  In the bottom right corner of every page there is a "Search this site" button:

<img width="383" alt="screenshot 2016-03-22 17 51 24" src="https://cloud.githubusercontent.com/assets/39340/13970479/f30636d8-f056-11e5-8b39-b5e0905cb506.png">

**Comment by COLABORATI** [comment]
oups, have not seen that, sorry.
