### ISSUE TITLE
"ERROR! no action detected in task" when running main.yml with includes

### ISSUE THREAD

**Issue by osielczakd** [ansible/ansible#15119]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = /etc/ansible/custom_modules/
```
##### Ansible Configuration:

module search path = /etc/ansible/custom_modules/
##### Environment:

CentOS Linux release 7.2.1511 (Core)
##### Summary:

when I run main.yml (either as a separate playbook or using the main site.yml) I get an error `"ERROR! no action detected in task":`
All the playbooks included run fine on their own
##### Steps To Reproduce:

create a role and place main.yml in tasks/
add includes to the main.yml
run the playbook

```
[root@install-test7 ansible]# cat roles/dns/tasks/main.yml

---
- hosts: all
  tasks:
    - include: ensure_resolv_conf.yml tags=resolv_conf
    - include: ensure_hosts.yml tags=etc_hosts

[root@install-test7 ~]# cat /etc/ansible/roles/dns/tasks/ensure_resolv_conf.yml

---
- hosts: all
  tasks:

  - name: ensure resolve.conf contents
    copy: src=resolv.conf dest=/etc/resolv.conf owner=root group=root mode=0644
```
##### Expected Results:

the included playbooks to be run
##### Actual Results:

```
# ansible-playbook roles/dns/tasks/main.yml -vvv
Using /etc/ansible/ansible.cfg as config file
1 plays in roles/dns/tasks/main.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
...
ok: [www-test7]

TASK [include] *****************************************************************
task path: /etc/ansible/roles/dns/tasks/main.yml:4
fatal: [www-test7]: FAILED! => {"failed": true, "reason": "ERROR! no action detected in task\n\nThe error appears to have been in '/etc/ansible/roles/dns/tasks/ensure_resolv_conf.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- hosts: all\n  ^ here\n"}

PLAY RECAP *********************************************************************
www-test7                  : ok=1    changed=0    unreachable=0    failed=1

```

**Comment by bcoca** [comment]
This is not a bug,  you have a couple of issues.

First you are putting a play in a role's tasks/main.yml, this is also not supported, roles are inside plays and plays cannot be included inside other plays.

The second issue is similar to the first, you are including 2 plays directly inside the play you defined in the role.

**Comment by einarc** [comment]
@bcoca  Hey Brian,

I was thrown off by the same thing. I think improving the error messages would help a lot overall. But of course the headache is that for that you need to know what the user is trying to do first. Let me know if there's any way I can help with that.

**Comment by Shridharbhandar** [comment]
HI @osielczakd ,

Did you find out any way to overcome this? Even I'm facing the same issue. The individual plays are running fine but when it comes to include or importing the play in main playbook it's throwing out an error No action detected in task.

Even when I check the module search path, I don't find the plugins/modules directory on my machine and my ansible is updated. Any suggestions ?

![image](https://user-images.githubusercontent.com/22121286/48764915-fdcc9600-ecd6-11e8-8055-4fe87c375dd4.png)

**Comment by osielczakd** [comment]
Given that this was almost three years ago, I think I worked around it somehow in the end, but can't remember what the workaround was. Maybe try reorganizing your playbooks somehow. 
Out of curiosity, what version of Ansible are you using? What is your playbook structure? Can you post the problematic code here?

**Comment by Shridharbhandar** [comment]
Hi @osielczakd ,

I hope that there was some indentation problem. I've re-written the plays. This time it worked.

Not sure why was it showing "No action detected" before.

Thanks for your attention.
