### ISSUE TITLE
Arch Linux packaging files are woefully out of date

### ISSUE THREAD

**Issue by djmattyg007** [ansible/ansible#15113]
The Arch Linux PKGBUILD (found [here](https://github.com/ansible/ansible/tree/devel/packaging/arch)) is woefully out of date, and isn't really necessary. The link in the README.md file in that folder points to a package that no longer exists, as Ansible has been in the official repositories for over two years. Also, the PKGBUILD is for v1.6, which is itself almost two years old.

Is there any reason for the Arch packaging files to still exist? At best they should be nothing more than pointing people towards the official package.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by djmattyg007** [comment]
This isn't a user question. It's a developer question about the state of the ansible codebase.
