### ISSUE TITLE
Handlers are silently ignored when included in a playbook

### ISSUE THREAD

**Issue by milouse** [ansible/ansible#15117]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file = /home/etienne/repo/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

```
$ cat /home/etienne/repo/ansible.cfg
[defaults]
hostfile = /home/etienne/repo/config/inventory
display_skipped_hosts = False
nocows=1
vault_password_file = ./config/toto

[ssh_connection]
ssh_args = -F ./config/ssh_config -o ControlMaster=auto -o ControlPersist=60s
```
##### Environment:

Running from an up-to-date Archlinux

Managing a grape of LXC containers running Debian Wheezy inside Debian Wheezy hosts.
##### Summary:

Until ansible 2.0, I used to maintain a "global" handlers file, which contains very generic handlers like apache restart, monit restart etc. used in several of my roles. This file is not stored in any role, but "included" in my various playbooks. It used to work.

Since ansible 2.0, handlers are silently ignored. I think it is somehow related to #13507
##### Steps To Reproduce:

```
$ cd repo
$ cat roles/backjob/tasks/main.yml

---
- template: src=delayed_jobs_monit.j2
      dest=/etc/monit/monitrc.d/delayed_jobs_toto
  notify:
    - Restart monit
  tags:
    - backjob
    - monit
$ cat vendor_specific.yml

---
- hosts: sd-83787-dintec
  roles:
    - backjob
  handlers:
    - include: config/handlers.yml
$ cat config/handlers.yml

---
- name: Restart monit
  service: name=monit state=restarted
$ ansible-playbook vendor_specific.yml
```

There is nothing special in the `host_vars/sd-83787-dintec.yml` file.
##### Expected Results:

When the template module execution push a new version of the file, the handler `Restart monit` must be executed.
##### Actual Results:

The playbook is successfully ran, but handler is silently ignored: nothing related to handler is output, even with -vvvv

However, if I directly add the handler in the playbook:

```
$ cat vendor_specific.yml

---
- hosts: sd-83787-dintec
  roles:
    - backjob
  handlers:
    - name: Restart monit
      service: name=monit state=restarted
    #- include: config/handlers.yml
```

handler is ran as expected.

**Comment by moozer** [comment]
I have the exact same issue.

I create a gist to illustrate it.
https://gist.github.com/moozer/c4060803e1f0677c0212
"handler B" is never called.

**Comment by moozer** [comment]
Paraphrasing from #ansible on IRC:

> It probably relates to "task includes being made dynamic" in the 2.0 line.
> A fix might be in dev branch, and will probably appear in a later release.

my conclusion: work around it for now, or go back to 1.9

**Comment by milouse** [comment]
Yeah, I remove my "global" handlers file and duplicate it back in my various roles. In fact, I understand such a file is a bit against the ansible philosophy of having totally independant roles. But for anyone who hates code duplication, it is frustrating.

**Comment by moozer** [comment]
Agreed. 
And I am pretty sure it is a bug, even though I have not tried to it track down further.

**Comment by bcoca** [comment]
@milouse put global handlers in a role and make other roles depend on it.

**Comment by bcoca** [comment]
cc @jimi-c, in case 'partial static includes' patch fixed this

**Comment by jimi-c** [comment]
This should be addressed by the static includes merge (which went in last week).

**Comment by dekimsey** [comment]
@bcoca What was the commit/pr/issue that addressed this? I cannot find any references to "partial static includes". I'm seeing it 2.1 and was trying to verify its fixed or what I can do to work-around it at the moment.

**Comment by jimi-c** [comment]
@dekimsey it was several patches, overall the feature in 2.1 was to make includes static when one of the following is true:
- task_includes_static or handler_includes_static is enabled in the ansible.cfg (also configurable via environment variables ANSIBLE_TASK_INCLUDES_STATIC/ANSIBLE_HANDLER_INCLUDES_STATIC)
- `static: yes` is defined on the include task
- (as of 2.1.1) when no `with_` loop is used and the included file name does not use a variable.

**Comment by cfoutstd** [comment]
I have this issue in 2.1.1.0

**Comment by jimi-c** [comment]
@cfoutstd did you read the above? Please be sure you're setting the correct options in your ansible.cfg if not using the `static` option in your plays.

**Comment by jimi-c** [comment]
As this appears to be resolved (though it may require some user changes in the ansible.cfg or plays), we're going to close this now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
