### ISSUE TITLE
Avoiding module_name, module_complex in json output

### ISSUE THREAD

**Issue by write2kishore** [ansible/ansible#15116]
When running a playbook that eventually generates a json file, I am seeing the module_name, module_complex_args, etc. like this:-

"{'invocation': {'module_name': u'sl', 'module_complex_args': .....

where as when run the same book in a different environment of my colleague's, it doesn't show these. How can I also avoid these things? Why am I only getting these strings? What does it depend on?

Thanks for any clues....

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
