### ISSUE TITLE
--syntax-check output is not standard and unpredictable

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#15135]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-playbook --syntax-check

##### ANSIBLE VERSION

``````
ansible 2.0.1.0
  config file = /Users/sorins/bmll/devops/ansible.cfg
  configured module search path = /usr/share/ansible:roles.galaxy/cmprescott.xml/library```
``````
##### SUMMARY

It seems that the `--syntax-check` command does not behave in a very friendly way, giving some hard to process results.

I would recommend using a standard output format, maybe the same as [pep8 of pylint output format](http://pep8.readthedocs.org/en/latest/intro.html#example-usage-and-output)
##### ACTUAL RESULTS

```
>ansible-playbook --syntax-check valid.yml

playbook: valid.yml
>ansible-playbook --syntax-check invalid.yml
ERROR! 'hosts' is undefined
```

Here are the problems:
- When valid it does output an extra newline at the top
- Playbook name is displayed only when it does pass the check. As as user I was expecting the opposite!
- Error does not contain filename and line number information
- Error is not made in parseable / linting format, ideally using an already defined format

**Comment by ssbarnea** [comment]
If these are recognised as valid, I would not mind trying to implement some of them, but I would like to avoid implementing something that is not desired.

**Comment by mschuchard** [comment]
Standardized output, especially pep8, would be great for my linter.
As it is I am currently working around it, but this would make life easier for sure.

**Comment by sivel** [comment]
We have recently discussed this and have decided that instead of using `--syntax-check` for machine parsable results, users should instead rely on the functionality of `ansible-lint`.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
