### ISSUE TITLE
One web server gives an error when checking to see if httpd is installed

### ISSUE THREAD

**Issue by joelouthan** [ansible/ansible#15131]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 1.9.4
```
##### CONFIGURATION

forks          = 10
##### OS / ENVIRONMENT

From: Red Hat Enterprise Linux Server release 6.7 (Santiago)
To: Red Hat Enterprise Linux Server release 6.7 (Santiago)
##### SUMMARY

Walking through Ansible's documentation, trying to learn.

I run to see if httpd is installed on all of my web servers. Everything checked out except for one server.

Honestly, I would like to know in the error that comes up, what am I reading and how can I fix it.
##### STEPS TO REPRODUCE

```
ansible qsdevweb -m yum -a "name=httpd state=present" -vvvv
```

##### EXPECTED RESULTS

I excepted ansible to tell me that the server had httpd installed.
##### ACTUAL RESULTS

```
<qsdevweb> ESTABLISH CONNECTION FOR USER: gops
<qsdevweb> REMOTE_MODULE yum name=httpd state=present
<qsdevweb> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/gops/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 qsdevweb /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1458768370.53-267890173984495 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1458768370.53-267890173984495 && echo $HOME/.ansible/tmp/ansible-tmp-1458768370.53-267890173984495'
<qsdevweb> PUT /tmp/tmpO1hlKF TO /home/gops/.ansible/tmp/ansible-tmp-1458768370.53-267890173984495/yum
<qsdevweb> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/gops/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 qsdevweb /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python -tt /home/gops/.ansible/tmp/ansible-tmp-1458768370.53-267890173984495/yum; rm -rf /home/gops/.ansible/tmp/ansible-tmp-1458768370.53-267890173984495/ >/dev/null 2>&1'
qsdevweb | FAILED >> {
    "failed": true,
    "msg": "Traceback (most recent call last):\r\n  File \"/home/gops/.ansible/tmp/ansible-tmp-1458768370.53-267890173984495/yum\", line 3371, in <module>\r\n    main()\r\n  File \"/home/gops/.ansible/tmp/ansible-tmp-1458768370.53-267890173984495/yum\", line 983, in main\r\n    disablerepo, disable_gpg_check)\r\n  File \"/home/gops/.ansible/tmp/ansible-tmp-1458768370.53-267890173984495/yum\", line 901, in ensure\r\n    my = yum_base(conf_file)\r\n  File \"/home/gops/.ansible/tmp/ansible-tmp-1458768370.53-267890173984495/yum\", line 182, in yum_base\r\n    my.setCacheDir()\r\n  File \"/usr/lib/python2.6/site-packages/yum/__init__.py\", line 5260, in setCacheDir\r\n    cachedir += varReplace(suffix, self.conf.yumvar)\r\n  File \"/usr/lib/python2.6/site-packages/yum/__init__.py\", line 911, in <lambda>\r\n    conf = property(fget=lambda self: self._getConfig(),\r\n  File \"/usr/lib/python2.6/site-packages/yum/__init__.py\", line 300, in _getConfig\r\n    startupconf = config.readStartupConfig(fn, root)\r\n  File \"/usr/lib/python2.6/site-packages/yum/config.py\", line 875, in readStartupConfig\r\n    confpp_obj = ConfigPreProcessor(configfile)\r\n  File \"/usr/lib/python2.6/site-packages/yum/parser.py\", line 89, in __init__\r\n    fo = self._pushfile( url )\r\n  File \"/usr/lib/python2.6/site-packages/yum/parser.py\", line 197, in _pushfile\r\n    'Error accessing file for config %s' % (absurl)\r\nyum.Errors.ConfigError: Error accessing file for config file:///etc/yum.conf\r\nOpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_request_forwards: requesting forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 5633\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to qsdevweb closed.\r\n",
    "parsed": false
}
```

**Comment by sivel** [comment]
Per that error it appears as though there is an issue with `/etc/yum.conf`:

```
yum.Errors.ConfigError: Error accessing file for config file:///etc/yum.conf
```

**Comment by joelouthan** [comment]
Okay, thank you for pointing that out. Now I can read the errors and know how to fix them.

**Comment by joelouthan** [comment]
Lovely: 

`$ ansible qsdevweb -m yum -a "name=httpd state=present" -vvvv
<qsdevweb> ESTABLISH CONNECTION FOR USER: gops
<qsdevweb> REMOTE_MODULE yum name=httpd state=present
<qsdevweb> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/gops/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 qsdevweb /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1458769527.07-118507563457337 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1458769527.07-118507563457337 && echo $HOME/.ansible/tmp/ansible-tmp-1458769527.07-118507563457337'
<qsdevweb> PUT /tmp/tmp6J_3E9 TO /home/gops/.ansible/tmp/ansible-tmp-1458769527.07-118507563457337/yum
<qsdevweb> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/gops/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 qsdevweb /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python -tt /home/gops/.ansible/tmp/ansible-tmp-1458769527.07-118507563457337/yum; rm -rf /home/gops/.ansible/tmp/ansible-tmp-1458769527.07-118507563457337/ >/dev/null 2>&1'
qsdevweb | success >> {
    "changed": false,
    "msg": "",
    "rc": 0,
    "results": [
        "httpd-2.2.15-47.el6_7.4.x86_64 providing httpd is already installed"
    ]
}`
