### ISSUE TITLE
Tasks in included file in dependent role are not executed

### ISSUE THREAD

**Issue by rpijlman** [ansible/ansible#15141]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0 (detached HEAD 7e05cc4e74) last updated 2016/03/24 12:33:53 (GMT +200)
  lib/ansible/modules/core: (detached HEAD a89266c5cb) last updated 2016/03/24 12:33:58 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD ae8eab1185) last updated 2016/03/24 12:34:01 (GMT +200)
  config file = /home/applinet/local/repro_ansible_bug/infrastructure/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Debian Linux 8.3
##### SUMMARY

The tasks in a file that is included by the main.yml of a dependent role. are silently ignored, instead of executed.
##### STEPS TO REPRODUCE

I apply a role 'hoedoe' to a server. That role has a dependent role 'app'.
roles/hoedoe/meta/main.yml

```

---

allow_duplicates: yes
dependencies:
  - { role: app }
```

app/tasks/main.yml is executed:

```

---

- include: uninstall.yml
```

The 'included' line appears in ansible-playbook's output.

However, a fail in the included file uninstall.yml causes no fail:

```

---

- name: I should fail
  fail:
    msg: "I should fail"
```

With 2.0.0.1 stable from source repository this worked fine (the fail causes a failure).
With 2.0.0.2-0.1.rc1 this doesn't work (the fail is ignored and the entire play succeeds).
##### EXPECTED RESULTS

```
ansible-playbook 2.0.0.2 (stable-2.0.0.1 7de237c5a1) last updated 2016/03/24 15:39:28 (GMT +200)
  lib/ansible/modules/core: (detached HEAD ce6619bf5d) last updated 2016/03/24 15:42:25 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 29af26884e) last updated 2016/03/24 15:42:28 (GMT +200)
  config file = /home/applinet/local/repro_ansible_bug/infrastructure/ansible.cfg
  configured module search path = Default w/o overrides

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [yu.applinet.nl]

TASK [app : include] ***********************************************************
included: /home/applinet/local/repro_ansible_bug/infrastructure/roles/app/tasks/uninstall.yml for yu.applinet.nl

TASK [app : I should fail] *****************************************************
fatal: [yu.applinet.nl]: FAILED! => {"changed": false, "failed": true, "msg": "I should fail"}

PLAY RECAP *********************************************************************
yu.applinet.nl             : ok=2    changed=0    unreachable=0    failed=1   
```
##### ACTUAL RESULTS

```
ansible-playbook 2.0.2.0 (detached HEAD 7e05cc4e74) last updated 2016/03/24 12:33:53 (GMT +200)
  lib/ansible/modules/core: (detached HEAD a89266c5cb) last updated 2016/03/24 12:33:58 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD ae8eab1185) last updated 2016/03/24 12:34:01 (GMT +200)
  config file = /home/applinet/local/repro_ansible_bug/infrastructure/ansible.cfg
  configured module search path = Default w/o overrides

PLAY [yu.applinet.nl] **********************************************************

TASK [setup] *******************************************************************
ok: [yu.applinet.nl]

TASK [app : include] ***********************************************************
included: /home/applinet/local/repro_ansible_bug/infrastructure/roles/app/tasks/uninstall.yml for yu.applinet.nl

PLAY RECAP *********************************************************************
yu.applinet.nl             : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by rpijlman** [comment]
These are the files to reproduce the problem:
[repro ansible issue 15141.zip](https://github.com/ansible/ansible/files/188158/repro.ansible.issue.15141.zip)

**Comment by jimi-c** [comment]
Looks like I missed cherry-picking 06b072c1. After adding that, your test playbook/roles work as expected:

<pre>
[jimi 15141]# ansible-playbook --version
ansible-playbook 2.0.2.0 (stable-2.0 b7ccc8cfa1) last updated 2016/03/24 21:00:25 (GMT -400)
  lib/ansible/modules/core: (detached HEAD a89266c5cb) last updated 2016/03/24 20:55:54 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD ae8eab1185) last updated 2016/03/24 20:55:54 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
[jimi 15141]# ansible-playbook -vv test.yml 
Using /etc/ansible/ansible.cfg as config file
PLAYBOOK: test.yml *************************************************************
1 plays in test.yml
PLAY [localhost] ***************************************************************
TASK [app : include] ***********************************************************
task path: /root/testing/15141/roles/app/tasks/main.yml:3
included: /root/testing/15141/roles/app/tasks/uninstall.yml for localhost
TASK [app : I should fail] *****************************************************
task path: /root/testing/15141/roles/app/tasks/uninstall.yml:1
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "I should fail"}
PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
</pre>

Just waiting for Travis to pass it before closing this: https://travis-ci.org/ansible/ansible/builds/118387174

**Comment by jimi-c** [comment]
It looks like things passed (albeit with an odd error on the ubuntu nodes), so I'll go ahead and close this now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
