### ISSUE TITLE
Default variables in dependent roles are not being overridden by default variables in parent role

### ISSUE THREAD

**Issue by c0state** [ansible/ansible#15179]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
2.0.1.0
```
##### CONFIGURATION

See https://github.com.c0state/ansible_default_vars_in_dependent_roles.git for a full example to reproduce the issue that I am observing.
##### OS / ENVIRONMENT

Testing done via Vagrant using VirtualBox provider on:
box name ==> ubuntu/trusty64
box version ==> 20160323.0.0
(see repo and steps below for full reproducible environment)
##### SUMMARY

Role default variables (ie: those specified in defaults/main.yml) as documented at http://docs.ansible.com/ansible/playbooks_roles.html#role-default-variables don't seem to be overridden in dependent roles by their parent's default variables in version 2.0.1.0. As the example shows, this (partially) worked in 1.9.4. In addition, the override only works when the task was part of an included YAML file. When the task was in the tasks/main.yml file, the variable also isn't overridden whether using version 1.9.4 or 2.0.1.0 (the example test configuration shows this specific scenario)

Note: I've seen a bunch of issues relating to default variables but none that seem to address this specific scenario.
##### STEPS TO REPRODUCE
1. Clone the sample project at https://github.com.c0state/ansible_default_vars_in_dependent_roles.git
2. Select the Ansible version to test in the Vagrantfile (comment out either the 1.9.4 or 2.0.1.0 provisioning line)
3. Bring up the box via "vagrant up"

It should install the specified version of Ansible via pip on the guest and then run a small playbook illustrating the problem. When I test version 2.0.1.0, the "subrole_var" variable in the example is not overridden as expected. Version 1.9.4 works only in tasks that are in YAML files included from tasks/main.yml
##### EXPECTED RESULTS

I expected the "app" role's default variable called "subrole_var" to override the equivalently named variable in the dependent role called "subrole"

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [default]

TASK: [subrole | In subrole include, show default variable] *******************
ok: [default] => {
    "var": {
        "subrole_var": "yay, overridden as expected"
    }
}

TASK: [subrole | In subrole include, show default variable] *******************
ok: [default] => {
    "var": {
        "subrole_var": "yay, overridden as expected"
    }
}

TASK: [app | Show ansible version] ********************************************
ok: [default] => {
    "var": {
        "ansible_version": {
            "full": "1.9.4",
            "major": 1,
            "minor": 9,
            "revision": 4,
            "string": "1.9.4\n  configured module search path = None"
        }
    }
}

PLAY RECAP ********************************************************************
default                    : ok=4    changed=0    unreachable=0    failed=0
```

This partially works in 1.9.4

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [default]

TASK: [subrole | In subrole include, show default variable] *******************
ok: [default] => {
    "var": {
        "subrole_var": "subrole default role variable value"
    }
}

TASK: [subrole | In subrole include, show default variable] *******************
ok: [default] => {
    "var": {
        "subrole_var": "yay, overridden as expected"
    }
}

TASK: [app | Show ansible version] ********************************************
ok: [default] => {
    "var": {
        "ansible_version": {
            "full": "1.9.4",
            "major": 1,
            "minor": 9,
            "revision": 4,
            "string": "1.9.4\n  configured module search path = None"
        }
    }
}

PLAY RECAP ********************************************************************
default                    : ok=4    changed=0    unreachable=0    failed=0
```
##### ACTUAL RESULTS

These are the results when running version 2.0.1.0

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [default]

TASK [subrole : In subrole include, show default variable] *********************
ok: [default] => {
    "subrole_var": "subrole default role variable value"
}

TASK [subrole : include] *******************************************************
included: /vagrant/roles/subrole/tasks/include.yml for default

TASK [subrole : In subrole include, show default variable] *********************
ok: [default] => {
    "subrole_var": "subrole default role variable value"
}

TASK [app : Show ansible version] **********************************************
ok: [default] => {
    "ansible_version": {
        "full": "2.0.1.0",
        "major": 2,
        "minor": 0,
        "revision": 1,
        "string": "2.0.1.0"
    }
}

PLAY RECAP *********************************************************************
default                    : ok=5    changed=0    unreachable=0    failed=0
```

**Comment by jimi-c** [comment]
Hi @c0state, as noted here http://docs.ansible.com/ansible/playbooks_variables.html#id7, each task within a role will see their own roles defaults regardless of what may be set in other roles. This also applies to dependencies, so the output above is what is expected. If you wish to override defaults used within a role, you should do so with parameters or other higher precedence variables.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by tkyjovsk** [comment]
"each task within a role will see their own roles defaults regardless of what may be set in other roles" - But why? This is so counterintuitive! It makes perfect sense to automatically override role defaults by default values in the dependent role. This change breaks all roles that relied on this behavior in 1.x.

**Comment by jimi-c** [comment]
If you want to override defaults, they should be done so through role params. Roles have always seen their defaults above all others, and that was always the intention since they were originally created.

**Comment by ghost** [comment]
@jimi-c, would you support an `include_vars:` in each meta dependency, so that we can include the consuming role's vars? (edit.. actually i meant to say: "consuming role's defaults as vars")

**Comment by conlon** [comment]
> If you want to override defaults, they should be done so through role params

@jimi-c  This is really heavy-handed and restrictive considering role defaults have the lowest precedence and role params are NINETEEN out of 24 levels of precedence higher.

I'd like to use two roles' defaults in conjunction with group_vars, but I'm SOL because of this.

**Comment by conlon** [comment]
for a second I thought the new `include_role` module might be a solution to this situation, but it's had a breaking bug for over a year and counting 😐 https://github.com/ansible/ansible/issues/21890

**Comment by jasonheecs** [comment]
Ran into this same issue; my workaround is to overwrite the variables in the dependent roles via `vars/main.yml`, like what I did here: [https://github.com/jasonheecs/ansible-ubuntu-bootstrap](https://github.com/jasonheecs/ansible-ubuntu-bootstrap)

**Comment by kzap** [comment]
I can see why this is confusing as you would want the parent role defaults to override the child role defaults if they are the same. I made several work arounds for this so you dont have to use different default variables names in the parent role.

https://github.com/kzap/ansible-parent-role-defaults-example
