### ISSUE TITLE
include_vars fails to import file containing variable that has already been defined: "ERROR! failed to combine variables, expected dicts but got a 'AnsibleUnicode' and a 'AnsibleUnicode'"

### ISSUE THREAD

**Issue by jladdjr** [ansible/ansible#15184]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /tmp/setup/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

_ansible.cfg_

```
[defaults]
system_warnings = no
```
##### OS / ENVIRONMENT

Running playbook on Ubuntu 12.04.5 system (against itself).
##### SUMMARY

`include_vars` task is failing when trying to import variables from *.yml file, when one of the variables was included earlier. Results in following failure:

```
ERROR! failed to combine variables, expected dicts but got a 'AnsibleUnicode' and a 'AnsibleUnicode':
"/etc/supervisor/conf.d/tower.conf"
"/etc/supervisor/conf.d/tower.conf"
```
##### STEPS TO REPRODUCE

_Setup:_ 
Create the following files:

_inventory_
`localhost ansible_connection=local`

_vars.yml_

```

---
var1: "test"
```

_vars2.yml_

```

---
var1: "test"
```

_playbook.yml_

```

---

- hosts: all
  tasks:
    - name: 'include variables'
      include_vars: 'vars.yml'

    - name: 'include variables from other file'
      include_vars: 'vars2.yml'

    - name: 'print var1'
      shell: "echo {{ var1 }}"
```
1. Run: `ansible-playbook -vvvv -i inventory playbook.yml`
2. Confirm that the task fails with:

```
TASK [include variables from other file] ***************************************
ERROR! failed to combine variables, expected dicts but got a 'AnsibleUnicode' and a 'AnsibleUnicode':
"test"
"test"
```
##### EXPECTED RESULTS

Expect playbook to include variable `var1` from first file, then include `var1` from second file, replacing the initial value of `var1` with the value found in the second file. Final task should print this value.
##### ACTUAL RESULTS

Task `include variables from other file` fails with `ERROR! failed to combine variables, expected dicts but got a 'AnsibleUnicode' and a 'AnsibleUnicode':`

_Full output:_

```
# ansible-playbook -vvvv -i inventory playbook.yml
Using /etc/ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0

PLAYBOOK: playbook.yml *********************************************************
1 plays in playbook.yml

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ESTABLISH LOCAL CONNECTION FOR USER: root
localhost EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1459187063.18-198873845363959 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1459187063.18-198873845363959 `" )'
localhost PUT /tmp/tmpQLRaQX TO /root/.ansible/tmp/ansible-tmp-1459187063.18-198873845363959/setup
localhost EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1459187063.18-198873845363959/setup; rm -rf "/root/.ansible/tmp/ansible-tmp-1459187063.18-198873845363959/" > /dev/null 2>&1'
ok: [localhost]

TASK [include variables] *******************************************************
task path: /tmp/sandbox/playbook.yml:5
ok: [localhost] => {"ansible_facts": {"var1": "test"}, "changed": false, "invocation": {"module_args": {"_raw_params": "vars.yml"}, "module_name": "include_vars"}}

TASK [include variables from other file] ***************************************
task path: /tmp/sandbox/playbook.yml:8
ERROR! failed to combine variables, expected dicts but got a 'AnsibleUnicode' and a 'AnsibleUnicode':
"test"
"test"
```

**Comment by jladdjr** [comment]
Sorry about posting the default template - accidentally clicked to submit issue. Filling out template now..

**Comment by jladdjr** [comment]
Note: If you edit `vars2.yml` and change `var1` to `var2` (so that the two files specify different variables), the playbook is successful.

It seems like you should be able to include a file containing a variable that has already been defined. Seems like the variable's value should just be updated in this case.

**Comment by jladdjr** [comment]
Impact on Tower:
- Tower 2.4.5 install playbook fails when running Ansible 2.0.2.0. Sample failure [here](http://jenkins.testing.ansible.com/view/Tower/job/Test_Tower_Install/4149/PLATFORM=rhel-6.7-x86_64,label=rhel-7/console). This affects all platforms (CentOS 6/7, RHEL 6/7, Ubuntu 12/14)
- Tower 2.4.4 install playbook fails when running Ansible 2.1.0 (See https://github.com/ansible/ansible-tower/issues/1043)

**Comment by thapakazi** [comment]
Same issue here...
![doc_2016-03-29_13-58-06 mp4](https://cloud.githubusercontent.com/assets/1695906/14101793/84d92cd2-f5b6-11e5-9e52-7041f05a7dcd.gif)

```
➜  ~  yaourt -Qi ansible-git
Name            : ansible-git
Version         : 2.1.0.18291.171c925-1
Description     : Radically simple IT automation platform
Architecture    : any
URL             : http://www.ansible.com
Licenses        : GPL3
Groups          : None
Provides        : ansible
...
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by thapakazi** [comment]
![thank_you](https://cloud.githubusercontent.com/assets/1695906/14228582/c4f4f7da-f938-11e5-88ff-dd37aba26d10.gif)
