### ISSUE TITLE
Bootstrapping FreeBSD: pkg waiting for confirmation even though 'env ASSUME_ALWAYS_YES=YES' is used

### ISSUE THREAD

**Issue by ojkastl** [ansible/ansible#15191]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /Users/xyz/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

[ssh_connection]
control_path = %(directory)s/%%C
##### OS / ENVIRONMENT

I checked this from OSX 10.10 and openSUSE Tumbleweed.
##### SUMMARY

I try to bootstrap a freebsd machine using e.g. [this tutorial](https://blog.codeways.org/ansible-freebsd/)

But the pkg process waits for confirmation, which should be avoided by using the 'env ASSUME_ALWAYS_YES=YES' part of the command.
##### STEPS TO REPRODUCE

```
Bootstrapping the host foobar:
ansible foobar -b -m raw -a 'env ASSUME_ALWAYS_YES=YES pkg install python' -u root

After some minutes killing the pkg process on the freebsd host shows the following results on the ansible controller:
```
##### ACTUAL RESULTS

```
foobar | FAILED | rc=247 >>

Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
The following 3 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        python: 2.7_2,2
        python27: 2.7.11_1
        python2: 2_3

The process will require 66 MiB more space.
10 MiB to be downloaded.

Proceed with this action? [y/N]: Child process pid=816 terminated abnormally: Killed
```

As you can see it is waiting for user input on whether or not to install the package. That should be avoided by using the 'env ASSUME...' part of the command

**Comment by ojkastl** [comment]
Forgot something:

Might be that one has to run the following before, to bootstrap a new pgk. But this also waits for the prompt:

```
/usr/bin/env ASSUME_ALWAYS_YES=1 /usr/sbin/pkg bootstrap -f
```

**Comment by ojkastl** [comment]
OK, I found the issue:

The quoted string containing the command for the raw module has to be quoted again, otherwise the variables wont get transmitted to the target, but rather being eaten by the controller's shell...

**Comment by ojkastl** [comment]
I was too fast. The commands with the arguments quoted twice runs and returns a success message, but apparently does nothing. I.e. pkg is not bootstrapped and python is not installed.

Using a playbook with the raw module works, as there is no quoting necessary.

I asked again on the mailinglist and will update the bug report...

**Comment by bcoca** [comment]
I'm not sure what the bug is here or what you are reporting aside from not being able to follow a 'non Ansible affiliated' tutorial.

**Comment by ojkastl** [comment]
Oh damn, I forgot to close this after I figured it out with help from the mailinglist. Brian, sorry for the noise.

Calling the command using the raw module does not work, unless you escape the equal sign:

`ansible -b -m raw -a 'env ASSUME_ALWAYS_YES\=YES pkg install python' foobar`

Calling from a play does not need the escaping.
