### ISSUE TITLE
if the module recieved no arguments, don't log the "with" message in the syslog.

### ISSUE THREAD

**Issue by vossenjp** [ansible/ansible#1519]
I've been doing a lot of 'ansible-ping' testing, and the destination machiens then end up with a lot of messages like this:

```
$ grep 'ansible-ping' /var/log/syslog 
Nov  3 03:09:30 hostname ansible-ping: Invoked with 
Nov  3 03:10:59 hostname ansible-ping: Invoked with 
Nov  3 03:50:18 hostname ansible-ping: Invoked with 
```

That looks rather truncated to me...

**Comment by mpdehaan** [comment]
It's actually that ping doesn't take any arguments, so it should just say "invoked"

I'm updating the defect description.
