### ISSUE TITLE
for playbooks, run template code locally

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#152]
eliminates need for jinja2 on nodes

**Comment by dagwieers** [comment]
Perfect as jinja2 on RHEL4 is a no-go ;-)

**Comment by mpdehaan** [comment]
notes to self:
- easier to just make all playbook templating local
- setup module always transfers results back, even if not running from playbook
- template module gets shorter too
- template module should also take a=2 b=3 c=4 kind of arguments

**Comment by mpdehaan** [comment]
done, pushing shortly.

non-playbook still requires remote for now, but we can fix this via slurping the metadata file so we can load it into memory and get the facts.   (Playbook already has facts, so no problem)
