### ISSUE TITLE
use environment variables of the remote host

### ISSUE THREAD

**Issue by mondherGL** [ansible/ansible#15203]
##### environment variables
- Hello , i use ansible to run tasks in remote machine , i want to work with variables from this remote machine . i tried to use lookup module but it return the variables of my machine to the remote one . i have no idea haw to do it .
  thanks in advance.
##### ANSIBLE VERSION
- 2.0.1
##### CONFIGURATION
- /etc/ansible/ansible.cfg (configuration)
  -/etc/ansible/hosts (list of remote hosts)
##### OS / ENVIRONMENT
- CentOS 7

**Comment by sivel** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
