### ISSUE TITLE
while installing pip on AIx, getting ImportError: No module named fcntl

### ISSUE THREAD

**Issue by rohitagr06** [ansible/ansible#15214]
# python get-pip.py

Traceback (most recent call last):
  File "get-pip.py", line 19154, in <module>
    main()
  File "get-pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    import pip
  File "/tmp/tmp_9j19c/pip.zip/pip/**init**.py", line 13, in <module>
  File "/tmp/tmp_9j19c/pip.zip/pip/utils/**init**.py", line 16, in <module>
  File "/opt/freeware/lib/python2.6/subprocess.py", line 416, in <module>
    import fcntl
ImportError: No module named fcntl

I am using python version 2.7.5
# python

Python 2.7.5 (default, Aug  2 2013, 23:28:11) [C] on aix6
Type "help", "copyright", "credits" or "license" for more information.

**Comment by bcoca** [comment]
fcntl is part of core python, if you compiled it without it ...

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be something that should be filed against another project or bug tracker, and let us explain our reasons for thinking this:
- The description doesn't appear to be related to ansible
- The get-pip script is maintained by a different organization: https://github.com/pypa/get-pip

If you can stop by the tracker or forum for one of those projects, we'd appreciate it.  

Should you still wish to discuss things further, or if you disagree with our thought process, please stop by one of our two mailing lists:
- https://groups.google.com/forum/#!forum/ansible-project
- https://groups.google.com/forum/#!forum/ansible-devel

We'd be happy to discuss things.

Thank you once again!
