### ISSUE TITLE
Lost Connectivity after playbook is run

### ISSUE THREAD

**Issue by rmauc** [ansible/ansible#15225]
I have a strange one - which I hope you can help me with
I have connectivity to a server, then once I run a very basic playbook which sudo's to root, I lose connectivity (hangs (no timeout).
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

ansible --version
ansible 2.0.1.0
##### CONFIGURATION

The playbook is as follows:

```
 -  hosts: XXXX228
    user: ansible
    become: true
    become_user: root
    vars:
     motd_mess: "Welcome\nNew MOTD\n"
    tasks:
    - name: sample motd new
      copy:
       dest: /etc/motd
       content: "{{ motd_mess }}"
```
##### SUMMARY

Once the playbook is run, all connectivity to the server is lost. 
I can still ssh to the server from the RHEL CLI successfully however.
##### STEPS TO REPRODUCE

This proves it was OK:

```
 ansible XXXX228 -m ping -u ansible
XXXX228 | SUCCESS => {
    "changed": false,
    "ping": "pong"
```

This is the playbook (described above) which I run 

---

```
This initially fails with:
[root@XXXX548]# ansible-playbook motd.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
fatal: [XXXX228]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "sudo: a password is required\r\n", "msg": "MODULE FAILURE", "par  sed": false}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @motd.retry

PLAY RECAP *********************************************************************
XXXX228                    : ok=0    changed=0    unreachable=0    failed=1

```

The fatal error is in case you cant read it all:
fatal: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "sudo: a password is required\r\n", "msg": "MODULE FAILURE", "par  sed": false}

Then immediately after when I try the ping again... it hangs forever

```
ansible XXXX228 -m ping -u ansible -vvvv
No config file found; using defaults
Loaded callback minimal of type stdout, v2.0
<XXXX228> ESTABLISH SSH CONNECTION FOR USER: ansible
<XXXX228> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt XXXX228 '/bin/sh -c '"'"'( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1459450996.48-5064161847334 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1459450996.48-5064161847334 `" )'"'"''

```
##### EXPECTED RESULTS

Playbook to pass or fail - but not lose ansible connectivity (native SSH is fine)
##### ACTUAL RESULTS

This is the 2nd time this has happened... the resolution was to reboot the Ansible server...

Where am I going wrong?
Thanks!

```
<!--- Paste verbatim command output between quotes -->
```

**Comment by MichaelBaydoun** [comment]
Looks like the playbook is hanging on a sudo password prompt.
"sudo: a password is required"

**Comment by rmauc** [comment]
Hi
Is any of the playbook syntax incorrect? 

That said, on the target machine when i sudo  to root. it does not ask/prompt for a password.

But if there was a non interactive prompt for a password ..why would failing to provide this result in complete loss  of ansible connectivity to that host? 
Does that make sense? 

Cheers

**Comment by MichaelBaydoun** [comment]
Comment out the become_user line and see what happens.

A password prompt hang on one run shouldn't prevent future connectivity to the host, agreed, but I'm just working the error message to start.

What does the sudoers entry look like that is allowing passwordless sudo?

**Comment by rmauc** [comment]
OK I commented the become_user line...ran the playbook to another AIX server (same os version/level)
Ansible still complains with the same error:
fatal: [XXXX228]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "sudo: a password is required\r\n", "msg": "MODULE FAILURE", "parsed": false}

But I do not lose Ansible connectivity to the box anymore... 

So I use a different variable to chose the user to sudo to?

Here is the sudoers config:

XXXX228 # /etc/sudoers.d>cat 12-inf-arch

User_Alias      INFARCH = ansible

## Begin INFARCH

INFARCH  ALL = NOPASSWD: /usr/bin/su

## End INFARCH

Thanks again

**Comment by MichaelBaydoun** [comment]
I suspect this is your problem
"INFARCH ALL = NOPASSWD: /usr/bin/su"

I don't know what command Ansible uses to sudo, but you have it limited to /usr/bin/su.  Change the line to:
"INFARCH ALL = NOPASSWD: ALL"

And test again

**Comment by MichaelBaydoun** [comment]
Found the following in the doc https://github.com/ansible/ansible/blob/f56110a3f9f7f66366a6a25cda2329eba2f4349f/docsite/rst/become.rst 

"Can't limit escalation to certain commands

Privilege escalation permissions have to be general. Ansible does not always use a specific command to do something but runs modules (code) from a temporary file name which changes every time. If you have '/sbin/service' or '/bin/chmod' as the allowed commands this will fail with ansible as those paths won't match with the temporary file that ansible creates to run the module."

**Comment by rmauc** [comment]
Hi
Yes I was just looking at that.. in fact all I needed to do was "INFARCH ALL = NOPASSWD: /usr/bin/su, /bin/sh" and the playbook worked. 
I was also able to add back the become_user: root var
Thanks for your help sir

**Comment by MichaelBaydoun** [comment]
Glad you got it working
