### ISSUE TITLE
Ansible 2.0.0.2: Include + with_items with pass vars does not work properly

### ISSUE THREAD

**Issue by tftm** [ansible/ansible#15220]
**Issue Type:**

Bug report

**Ansible Version:**

ansible 2.0.0.2

**Ansible Configuration:**

N/A

**Environment:**

Ubuntu 14.04

**Summary:**

When nested "with_items" include statements, passing through variables that using outer item is not set properly, i.e. variables using outer item calculating in inner "with_items" loop.

**Steps To Reproduce:**

main.yml

```

---
- include: include.yml pass={{ item }}
  with_items:
    - A
    - B
    - C
```

include.yml

```

---
- debug: msg="{{ pass }} = {{ item }}"
  with_items:
    - 1
    - 2
    - 3
```

**Expected Results:**

"msg": "A = 1"
"msg": "A = 2"
"msg": "A = 3"
"msg": "B = 1"
"msg": "B = 2"
"msg": "B = 3"
"msg": "C = 1"
"msg": "C = 2"
"msg": "C = 3"

**Actual Results:**

"msg": "1 = 1"
"msg": "2 = 2"
"msg": "3 = 3"
"msg": "1 = 1"
"msg": "2 = 2"
"msg": "3 = 3"
"msg": "1 = 1"
"msg": "2 = 2"
"msg": "3 = 3"

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by bcoca** [comment]
http://docs.ansible.com/ansible/playbooks_loops.html#loops-and-includes

**Comment by tftm** [comment]
Yes, i know about of item variable

```
...
- set_fact: outer_loop="{{item}}"
...

```

but, if Ansible implements passthrough variables with include, it must works properly, isn't it?

**Comment by bcoca** [comment]
it does, just not how you think it does, lazy evaluation would prevent what you expect from ever happening as it always gets the 'inner item'.

**Comment by tftm** [comment]
Well... ok :)
Thanks.
