### ISSUE TITLE
Non Standard Python Location on Target

### ISSUE THREAD

**Issue by rmauc** [ansible/ansible#15239]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
root@XXXX548 ~]# ansible --version
ansible 2.0.1.0
  config file =

```
##### SUMMARY

I have python installed in a non-standard path..I set the ansible_python_interpreter=/opt/ansible/bin/python - but it cannot find the libraries
##### STEPS TO REPRODUCE

```
ansible XXXX303 -u ansible -m ping -e ansible_python_interpreter=/opt/ansible/bin/python
XXXX303 | FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "",
    "module_stdout": "Could not load program /opt/ansible/bin/python:\r\n        Dependent module libpython2.7.a(libpython2.7.so) could not be loaded.\r\nCould not load module libpython2.7.a(libpython2.7.so).\r\nSystem error: No such file or directory\r\n",
    "msg": "MODULE FAILURE",
    "parsed": false
}
```
##### EXPECTED RESULTS

no error
##### ACTUAL RESULTS

<!-Provided above . Is there another variable to set the library location?
Thanks 
-->

```
<!--- Paste verbatim command output between quotes -->
```

**Comment by dagwieers** [comment]
I expect you have to set the `LD_LIBRARY_PATH` (see `man ld.so`) so that your python executable can find its shared libraries (presumably available from _/opt/ansible/lib_ ?). The problem here is that I don't think you can have Ansible set environment variables on target systems, so you may have to write a wrapper script on the target and call that...

**Comment by rmauc** [comment]
you mean a pre- script to in the playbook to call/run the ansible users .profile which exports the LIBPATH?
Cheers

**Comment by dagwieers** [comment]
No. Although you could adapt a login-script to set the `LD_LIBRARY_PATH`, however that would then be system-wide.

I was alluding at creating a `python.sh` on the target that sets the `LD_LIBRARY_PATH` and then does `exec /opt/ansible/bin/python`.

**Comment by rmauc** [comment]
Ok. . So where would the python.sh live. . So that it is executed  on the target before ansible needs python? Thanks a lot

**Comment by dagwieers** [comment]
No, it is run instead of python.

**/opt/ansible/bin/python.sh**

``` bash
#!/bin/bash
export LD_LIBRARY_PATH="/opt/ansible/lib"
exec /opt/ansible/bin/python
```

Something like that, if all assumptions prove to be true.

**Comment by rmauc** [comment]
Works like a charm
Thanks very much
