### ISSUE TITLE
'slice' filter doesn't work correctly for with the same number of items as the slice size

### ISSUE THREAD

**Issue by Yannik** [ansible/ansible#15237]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Fedora 23
##### SUMMARY

The `slice` filter does not work correctly when the number of items passed to it is the same number as the slice size.
##### STEPS TO REPRODUCE

```
- hosts: all
  vars:
    - var: ['a', 'b']
    - var2: ['a', 'b', 'c', 'd']
  tasks:
    - name: Incorrect result for list with the same number of items as slize size
      debug: msg={{var|slice(2)|list}}
    - name: Correct result for larger list
      debug: msg={{var2|slice(2)|list}}
```

Run this using `ansible-playbook -i 'localhost,' -c local test.yml`
##### EXPECTED RESULTS

`var|splice(2)|list` should return `[["a", "b"]]`.
##### ACTUAL RESULTS

`var|splice(2)|list` returns `[["a"], ["b"]]`.

```
TASK [Incorrect result for list with the same number of items as slize size] ***
ok: [localhost] => {
    "msg": [
        [
            "a"
        ], 
        [
            "b"
        ]
    ]
}

TASK [Correct result for larger list] ******************************************
ok: [localhost] => {
    "msg": [
        [
            "a", 
            "b"
        ], 
        [
            "c", 
            "d"
        ]
    ]
}
```

**Comment by bcoca** [comment]
slice is a jinja2 filter, the code is not part of this repo.

**Comment by bcoca** [comment]
reading the description from the jinja2 site, this is expected:

```
slice(value, slices, fill_with=None)
Slice an iterator and return a list of lists containing those items. Useful if you want to create a div containing three ul tags that represent columns:
```

**Comment by Yannik** [comment]
@bcoca Oh, so this creates a fixed number of slices with a variable number of elements, instead of creating a variable number of slices with a fixed number of elements. The description is quite unclear to me. Is there anything with the latter functionality in jinja/ansible? Would a PR for this be likely included in ansible?

**Comment by bcoca** [comment]
@Yannik a complementary filter that does as you describe would be fine.
