### ISSUE TITLE
documentation on installing ansible via homebrew

### ISSUE THREAD

**Issue by tough-rain** [ansible/ansible#15250]
##### ISSUE TYPE
- Documentation Report
##### ANSIBLE VERSION

```
ansible --version
ansible 2.0.1.0
```
##### OS / ENVIRONMENT

OS X El Captain 10.11.2
##### SUMMARY

It's possible to install ansible via homebrew(brew) on Mac OS X. This provides an efficient and easy-to-use scenario to install the software. Should a pull request to document this be submitted? The documentation on the installation is not reflecting this way of installing.

```
https://github.com/ansible/ansible/blob/devel/docsite/rst/intro_installation.rst#latest-releases-on-mac-osx
```
##### STEPS TO REPRODUCE

```
brew install ansible
```
##### EXPECTED RESULTS

```
$ ansible --version
ansible 2.0.1.0
```

**Comment by sivel** [comment]
We specifically do not recommend installing Ansible via homebrew.  The recommended way of installing Ansible on Mac is via pip.

Homebrew modifies and patches files that have been known to cause issues that pip native installs do not suffer from.

**Comment by rowild** [comment]
@sivel  Is this still true in July 2018?

**Comment by sivel** [comment]
Yes.  Homebrew is an unsupported means of installing ansible, and we have no intentions of changing this position.
