### ISSUE TITLE
lookup csvfile doesn't work with cyrillic and other unicode symbols

### ISSUE THREAD

**Issue by puzan** [ansible/ansible#15266]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Lookup csvfile doesn't work with cyrillic and other unicode symbols. Csv module in python2 doesn't work with any symbols except ascii if utf-8 encoding is used (unicode strings). As result using cyrillic in csv file leads to errors.

The simplest way to fix this issue is to open file without encoding. Now I have following little fix: https://github.com/puzan/ansible/commit/ef1869b59945324bf0c4c9c46be3a308ed3d614d. I'm going to add test for this case and open pull request.
##### STEPS TO REPRODUCE

```
ansible-playbook csv_cyrillic.yml
```

csv_cyrillic.yml:

``` yml

---
- name: Test Cyrillic
  hosts: localhost
  tasks:
    - debug: msg="{{ lookup('csvfile', '1 file=cyrillic.csv delimiter=;') }}"
    - debug: msg="{{ lookup('csvfile', '1 file=cyrillic.csv delimiter=; col=2') }}"
```

cyrillic.csv:

``` csv
# id;name;city
1;Илья;Горький
```
##### EXPECTED RESULTS

```
PLAY [Test Cyrillic] ***********************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "Илья"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "Горький"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```
##### ACTUAL RESULTS

```
PLAY [Test Cyrillic] ***********************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "csvfile: 'ascii' codec can't encode characters in position 2-5: ordinal not in range(128)"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by dagwieers** [comment]
I am afraid that Ansible cannot know what character-set a file was encoded with, and at the moment there is no way to tell the csvfile lookup plugin what the used character set is. (It is impossible to detect the used character set, unless it is part of the content/formatting)

Personally I think the best solution is to use UTF-8 everywhere, and convert all files to UTF-8. But maybe a pull-request to add support for custom character sets is acceptable as well ?  E.g. `lookup('csvfile', '1 file=cyrillic.csv delimiter=; col=2 charset=cp1251')`

**Comment by dagwieers** [comment]
@puzan I implemented what you needed here https://github.com/ansible/ansible/pull/15268, could you test this and report back ?

I have tested it like this:

``` yaml
- hosts: localhost
  gather_facts: no
  tasks:
    - debug: msg="UTF8 {{ lookup('csvfile', '1 file=files/cyrillic-utf8.csv delimiter=; col=2') }}"
    - debug: msg="UTF8 {{ lookup('csvfile', '1 file=files/cyrillic-utf8.csv delimiter=; col=2 encoding=utf-8') }}"
    - debug: msg="CP1251 {{ lookup('csvfile', '1 file=files/cyrillic-cp1251.csv delimiter=; encoding=cp1251') }}"
    - debug: msg="ISO8859-15 {{ lookup('csvfile', '1 file=files/iso8859-15.csv delimiter=; encoding=iso8859-15') }}"
    - debug: msg="ISO8859-15 {{ lookup('csvfile', '1 file=files/iso8859-15.csv delimiter=;') }}"
    - debug: msg="CP1251 {{ lookup('csvfile', '1 file=files/cyrillic-cp1251.csv') }}"
```

The last 2 tasks fail as expected, since they are opened using `utf-8` by default. It then fails as:

```
TASK [debug] *******************************************************************
task path: /home/dag/home-made/ansible.testing/test88.yml:8
fatal: [localhost]: FAILED! => {"failed": true, "msg": "csvfile: 'utf8' codec can't decode byte 0xe9 in position 0: invalid continuation byte"}
```

**Comment by puzan** [comment]
@dagwieers I have tested both solutions.
- First was failed. My csv file has already utf-8 encoding. So setting other encoding can't fix problem.
- Second solution from #15268 fixes problem.

I have tied to find little fix and thought that open file without encoding to unicode string is better choice. But I like your common solution with custom encoding and decoding based on python docs. It can cover more cases related with encoding in files. 

Thanks for quick response.

**Comment by dagwieers** [comment]
@puzan Thanks for the feedback.

Indeed, when I was looking to implement custom encoding support I noticed that it only supported ascii-files and not even UTF-8 ! So my assumption that your file was CP1251 was incorrect (however I did try both utf-8 and cp1251 for my own testing, just to be sure).

PS If you are using ascii files, or utf-8 files you do not need to set the encoding, it will work out-of-the-box.

**Comment by puzan** [comment]
@dagwieers Thank you for suggestions.

But I need to use russian content in csv files now. It is customer requirement. So now I have to use my workaround described in this issue (`open` instead of `codecs.open`). I will upgrade ansible to 2.0.2 when it is ready.
