### ISSUE TITLE
local action steps do not have access to hostvars

### ISSUE THREAD

**Issue by drfickle** [ansible/ansible#15261]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /home/sfox/.ansible.cfg
  configured module search path = /home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/library
```
##### CONFIGURATION

Custom inventory script

```
library = /home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/library
forks          = 20
sudo_flags = -H -i
jinja2_extensions = jinja2.ext.do,jinja2.ext.i18n,jinja2.ext.loopcontrols,jinja2.ext.with_
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
action_plugins     = /usr/share/ansible_plugins/action_plugins:/home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/plugins/action
callback_plugins   = /usr/share/ansible_plugins/callback_plugins:/home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/plugins/callback
connection_plugins = /usr/share/ansible_plugins/connection_plugins:/home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/plugins/connection
lookup_plugins     = /usr/share/ansible_plugins/lookup_plugins:/home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/plugins/lookup
vars_plugins       = /usr/share/ansible_plugins/vars_plugins:/home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/plugins/vars
filter_plugins     = /usr/share/ansible_plugins/filter_plugins:/home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/plugins/filter
nocows = 1
```
##### OS / ENVIRONMENT

From: Fedora 23
Managing: Ubuntu Trusty (14.04)
##### SUMMARY

When using a local_action, I cannot reference the magic variable hostvars.
##### STEPS TO REPRODUCE

Using this inventory file

```
test_host ansible_host=10.0.0.208
```

and this playbook

```
- name: My Playbook
  hosts: test_host
  gather_facts: no

  tasks:
    #- debug: msg="{{ item.value }}"
    - local_action: debug msg="{{ item.value }}"
      with_dict: "{{ hostvars['test_host'] }}"
```

Taking out the local_action works, but I have things I need to be able to execute against localhost using a script: command.
##### EXPECTED RESULTS

```
ok: [test_host] => (item={'value': u'test_host', 'key': 'inventory_hostname'}) => {
    "item": {
        "key": "inventory_hostname", 
        "value": "test_host"
    }, 
    "msg": "test_host"
}
ok: [test_host] => (item={'value': '/home/sfox/ansible.hosts', 'key': 'inventory_file'}) => {
    "item": {
        "key": "inventory_file", 
        "value": "/home/sfox/ansible.hosts"
    }, 
    "msg": "/home/sfox/ansible.hosts"
}
```

8< -- snip -- >8

```
ok: [test_host] => (item={'value': {'major': 2, 'full': '2.0.1.0', 'string': '2.0.1.0', 'minor': 0, 'revision': 1}, 'key': 'ansible_version'}) => {
    "item": {
        "key": "ansible_version", 
        "value": {
            "full": "2.0.1.0", 
            "major": 2, 
            "minor": 0, 
            "revision": 1, 
            "string": "2.0.1.0"
        }
    }, 
    "msg": {
        "full": "2.0.1.0", 
        "major": 2, 
        "minor": 0, 
        "revision": 1, 
        "string": "2.0.1.0"
    }
}
ok: [test_host] => (item={'value': u'10.0.0.208', 'key': u'ansible_host'}) => {
    "item": {
        "key": "ansible_host", 
        "value": "10.0.0.208"
    }, 
    "msg": "10.0.0.208"
}
```
##### ACTUAL RESULTS

```
Using /home/sfox/.ansible.cfg as config file
1 plays in ./playbooks/pants.yml

PLAY [My Playbook] *************************************************************
ERROR! 'hostvars' is undefined
```

**Comment by drfickle** [comment]
Forgot to mention this also affects 2.0.2.0.

**Comment by bcoca** [comment]
I can confirm with test playbook (just changed host) cc @jimi-c

**Comment by jimi-c** [comment]
Hrm, this is weird. If I instead change your task to `- local_action: debug var=hostvars['test_host']` it works just fine. So this must be something to do with the vars as they're passed to lookup plugins.

**Comment by bcoca** [comment]
this works:
`- local_action: debug msg="{{ lookup('items', hostvars['localhost']) }}"`

so it seems specifically on passing to lookups when part of `with_` clause

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment]
Also cherry-picked to stable-2.0, so this will be included in 2.0.2.

**Comment by drfickle** [comment]
Confirmed this fixed my test case and the original problem I was having. Thank you for the speedy fix!

**Comment by jimi-c** [comment]
Excellent, thanks for the follow-up.
