### ISSUE TITLE
map extract not founded

### ISSUE THREAD

**Issue by nejtr0n** [ansible/ansible#15279]
##### ISSUE TYPE

- Bug Report
- Feature Idea
- Documentation Report
##### ANSIBLE VERSION

```
<!--- Paste verbatim output from “ansible --version” between quotes -->
2.0.1.0
```
##### SUMMARY

Im trying to use ansible extract filter
http://docs.ansible.com/ansible/playbooks_filters.html#extracting-values-from-containers
But there is no such filter in 2.0.1.0
It comes with 2.1 version, but there is no such version available to download. Where can I get this filter?
##### STEPS TO REPRODUCE

```
<!--- Paste example playbooks or commands between quotes -->
```

```
{{ groups['consul_masters'] | difference([inventory_hostname]) | map('extract', hostvars, 'cluster_id') | join(', ')}}
```

Error: "TemplateRuntimeError: no filter named 'extract'"

##### ACTUAL RESULTS

```
<!--- Paste verbatim command output between quotes -->
```

**Comment by amenonsen** [comment]
As you note, the filter is available in 2.1. You can find it here:

https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/core.py#L348

You can copy the code and create a custom filter plugin; it'll work fine with 2.0.

**Comment by nejtr0n** [comment]
Thank you. Works perfect.

**Comment by jmalacho** [comment]
I update to 2.1 as suggested.

# ansible --version

ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

# rpm -q ansible

ansible-2.1.0.0-1.el6.noarch

I'm still having trouble getting this to work. I copied the documented example string:
- debug:
     msg: "{{ [0,2]|map('extract', ['x','y','z'])|list }}"

I get this error
TASK [test : debug] ************************************************************
fatal: [192.168.56.103]: FAILED! => {"failed": true, "msg": "template error while templating string: no filter named 'map'. String: {{ [0,2]|map('extract', ['x','y','z'])|list }}"}

Is this supposed to work yet? Do I have a broken install ? or am I using it wrong?

**Comment by sivel** [comment]
@jmalacho your issue is slightly different.  Your problem is that the `map` filter is missing.  The `map` filter is provided by jinja2 version 2.7.  You must have a version of jinja2 older than this.  You will need to upgrade to a more recent version of jinja2 to get access to the `map` filter.

**Comment by jmalacho** [comment]
@sivel Thank you. You are ofcourse correct that it was a python library dependency issue.
I uninstalled something and then did a

> sudo pip install paramiko PyYAML Jinja2 httplib2 six

 It works for me now. It might be worth updating the install documentation to reflect  that (http://docs.ansible.com/ansible/intro_installation.html).  A typical yum user would expect the rpm repo (epel-testing) & dependencies to be complete. It is rare/unique that I have to both yum install something and pip install something to get the Parent RPM to work.
The way I read the documentation was: "make sure you have python, install with yum"
And that works quite well until you get to a missing filter on my centos6 box.

**Comment by cristol** [comment]
I had the same difficulty with CentOS 6 as @jmalacho. His comment about installing with pip was what helped me to get my installation working properly. I'm pleased that ansible is now working in a way that matches the documentation. Though, in retrospect, I'm not as pleased with how I got here.

I think this should be viewed as a packaging problem in CentOS, not a documentation issue. Installing and updating via yum is how this should work. Updating via pip, stepped on the python-jinja2 & python-six packages installed by the system package manager (yum).

I think it is generally bad practice for a package manager to create a conflict with the system package manager. As yum has python dependencies, this approach has the potential for catastrophe.

**Comment by boscowitch** [comment]
I have ansible version ansible 2.2.1.0 install from pip in debian wheezy

Had all installed from @jmalacho but i had to do a
sudo pip install Jinja2 --upgrade

to have the map filter.... maybe pip install should be adapted ...

**Comment by jmalacho** [comment]
I will say, that because Centos6 is so old, I've found it better to get
newer Jinja2 rpms (2.7/2.8).  Using pip on Centos 6 has begun to get me
into trouble.

**Comment by boscowitch** [comment]
Well getting newer deb packages for debian wheezy is kinda hard ...

I tried to compile ansible first with make deb....

however i got only to the pbuilder part then it had some problems with an empty .....base.tgz file and would then i just tested pip and it worked even though it could not upgrade the other packets mentioned from @jmalacho it was able to do it only for the jinja2 packet and so far all my playbooks i want work ...  (fingers crossed)
