### ISSUE TITLE
variable passed with -e not interpretted as json/yaml

### ISSUE THREAD

**Issue by cdosborn** [ansible/ansible#15273]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

on OSX, host is localhost
##### SUMMARY

Unable to pass a list as a command line argument with `-e`.  
##### STEPS TO REPRODUCE

Using the following playbook `test.yml`:

```
- hosts: localhost
  tasks:
    - debug: msg="{{ LIST|join("\n") }}"
```

Run `ansible-playbook -i "localhost," -c local -e LIST='["a","b","c"]' test.yml`
##### EXPECTED RESULTS

```
ok: [localhost] => {
    "msg": "a\nb\nc"
}
```
##### ACTUAL RESULTS

```
ok: [localhost] => {
    "msg": "[\n\"\na\n\"\n,\n\"\nb\n\"\n,\n\"\nc\n\"\n]"
}
```

**Comment by bcoca** [comment]
you are using key=value notation, this is not valid YAML or JSON

`LIST='["a","b","c"]'`

**Comment by sivel** [comment]
In order to have -e use YAML/JSON, the full contents of -e must be YAML/JSON:

```
-e '{"LIST": ["a", "b", "c"]}'
```

You can also do short form YAML like:

```
-e '{LIST: [a, b, c]}'
```

If you have further questions please stop by IRC or the mailing list:
- IRC: #ansible on irc.freenode.net
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by cdosborn** [comment]
Thank you @sivel @bcoca
