### ISSUE TITLE
Need help to sudo to unprivileged user

### ISSUE THREAD

**Issue by rmauc** [ansible/ansible#15287]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible --version
ansible 2.0.1.0
  config file = /home/ansible/.ansible.cfg

```
##### SUMMARY

When I run a very simple playbook as root it is successful, but when I run it as a non-root user (in this case bea) it fails.

I have set the allow_world_readable_tmpfiles and piplineing vars in my .ansible.cfg after reading this:

https://github.com/ansible/ansible/blob/f56110a3f9f7f66366a6a25cda2329eba2f4349f/docsite/rst/become.rst#id1
##### STEPS TO REPRODUCE

```

---
 -  hosts: XXXX758
    user: ansible
    become: true
    become_user: bea
    gather_facts: True
    vars:
     motd_mess: "Welcome\n"
    tasks:
    - name: sample motd new
      copy:
       dest: /tmp/motd4.new
       content: "{{ motd_mess }}"

```

##### EXPECTED RESULTS

to behave as per root user i.e. playbook executes (as non-root - in this example b**)
##### ACTUAL RESULTS

Ansible error:

```
$ ansible-playbook populate.sudo.yml -vvvv
fatal: [****758]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "setup"}, "module_stderr": "OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 3: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 59077\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nsudo: a password is required\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

```

Sudo log on target:

```
Apr  5 13:55:53 : ansible : command not allowed ; TTY=unknown ;
    PWD=/export/home/ansible ; USER=bea ; COMMAND=/bin/sh -c echo
    BECOME-SUCCESS-iqsjrhmaxfvfpuipjgkudbhxmlvscbel; /bin/sh -c
    'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8
    /usr/bin/python'

```

syslog on target:

```
Apr  5 12:53:03 sv62758 sudo: [ID 702911 auth.alert]  ansible : command not allowed ; TTY=unknown ; PWD=/export/home/ansible ; USER=bea ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-cuenewuapksqxvqyogwpcdvslkdguuci; /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python'
```

sudoers config  on target (which again works as root - and works if manual (i.e. does not prompt for a password when the ansible user sudo su - bea):

```
User_Alias      INFARCH = ansible,bea

## Begin INFARCH ##
INFARCH  ALL = NOPASSWD: /bin/sh, /usr/bin/su - root, /usr/bin/su - bea
## End INFARCH   ##
```

Thanks

**Comment by dagwieers** [comment]
You have to allow ansible to do everything through sudo directly.

There is a statement in the docs that hint to this, but the exact wordings could be much better. (i.e. include statements for /etc/sudoers or /etc/sudoers.d/ansible).

See: http://docs.ansible.com/ansible/become.html#only-one-method-may-be-enabled-per-host

**Comment by rmauc** [comment]
Hi
Thanks for the update
I am not 100% sure what you mean however...
..But if you mean changing the sudoers to be:

INFARCH  ALL = NOPASSWD: ALL

I did try that and it made no difference

Thanks again

**Comment by dagwieers** [comment]
I am used to doing it like this:

``` sudo
ADMINS ALL = (ALL) NOPASSWD: ALL
```

But personally I loathe the sudoers config syntax. Its complexity has been a source of security problems...

**Comment by rmauc** [comment]
Hi 
I agree with you.

But since I have tried that, can you recommend any alternative solution? I need to get non-privileged to work - its a deal breaker for us with Ansible.

Am I missing anything?

**Comment by dagwieers** [comment]
If you are still getting "command not allowed" it is clear your sudo rule is not working. (Are there other rules that are overruling what you need ?)

```
sudo: a password is required
```

Sudo is where you have to direct your efforts. This is not an Ansible issue AFAICT.

**Comment by rmauc** [comment]
OK sir - I will keep digging there...
I will keep this issue open for now
Thanks

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
