### ISSUE TITLE
ebuild for gentoo linux

### ISSUE THREAD

**Issue by uu** [ansible/ansible#153]
Here is a live ebuild for gentoo: https://github.com/uu/ubuilds/tree/master/app-admin/ansible

**Comment by mpdehaan** [comment]
Excuse my gentoo ignorance, but what do you mean by live?  Are you maintaining it for the distribution itself (If so, very nice, if not, still nice).

If the goal is to be able to make packages from the Makefile, if you want to send me a pull request, we can keep this in the main tree.

Adding a makefile target to build the gentoo package may be worthwhile, maybe move the RPM and gentoo stuff into a "pkg/distroname" subdirectory or something.

**Comment by mpdehaan** [comment]
ok, I see you have your whole project there with lots of stuff rolled up together.

If you can let me know some instructions for gentoo users to use this, I can see about putting it up on the web documentation.

Thanks!

**Comment by uu** [comment]
<pre>
Hi, that's not necessary  :) 

ebuild is a recipe for how to build up the app. Like ports in *BSD.  Live means it gets the source from VCS and thus has no tagged version. Whenever installed – it's fresh pulled from repo. Probably, I'll add a tagged one soon which will fetch tarballs from github.

Some developers has a quick instruction on how to install it in gentoo. For ansible it can look like:

1. Install layman 
 Enable git useflag
echo 'app-portage/layman git' >> /etc/portage/package.use
 Verify layman version and useflags and install it
emerge -av layman

2. Add ubuilds repository definition to list in "/etc/layman/layman.cfg"

overlays: http://www.gentoo.org/proj/en/overlays/repositories.xml
                http://github.com/uu/ubuilds/raw/master/ubuilds.xml
3. Fetch + list repositories 
 Update and list all available repositories
layman -L

4.  Add ubuilds overlay 
layman -a ubuilds

5. Update "/etc/make.conf" to include the layman-managed repositories 
 add this line at the end
source /var/lib/layman/make.conf

6. Install ansible

emerge -av ansible

That's it! :)

Or, it's okay to add “Gentoo ebuilds are <a href='http://github.com/uu/ubuilds.git'>here</a>”  to some docs. Who needs it, already knows instruction listed above. Thanks.
</pre>

**Comment by mpdehaan** [comment]
added to the geting started page, thank you!

**Comment by czytom** [comment]
It's not needed anymore because since yesterday ansible package is in official portage tree ;)

**Comment by mpdehaan** [comment]
excellent.
