### ISSUE TITLE
sporadic winrm kerberos authentication failures

### ISSUE THREAD

**Issue by MichaelBaydoun** [ansible/ansible#15310]
I have reviewed other similar reported issues before opening this issue.  Other issues deal with the transfer of large files and older versions of Ansible.  Nothing of interest shows up in the windows event logs for the time period in question.  
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /home/icansible/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

sporadic winrm kerberos authentication failures on simple tasks
##### STEPS TO REPRODUCE

difficult to reproduce, sporadic.  

```
the following simple task just failed on one of our windows servers, but worked on the others, while previous tasks to the same servers worked without issue

- name: get SEP service state
  win_service:
    name: "SepMasterService"
  always_run: yes
  changed_when: false
  failed_when: false
  register: sepService
```
##### EXPECTED RESULTS

The registered variable to be populated for future use
##### ACTUAL RESULTS

```
TASK [antivirus : get SEP service state] ***************************************
12:12:47            Traceback (most recent call last):
12:12:47              File "/usr/lib/python2.6/site-packages/ansible/plugins/connection/winrm.py", line 244, in exec_command
12:12:47                result = self._winrm_exec(cmd_parts[0], cmd_parts[1:], from_exec=True)
12:12:47              File "/usr/lib/python2.6/site-packages/ansible/plugins/connection/winrm.py", line 177, in _winrm_exec
12:12:47                self.shell_id = self.protocol.open_shell(codepage=65001) # UTF-8
12:12:47              File "/usr/lib/python2.6/site-packages/winrm/protocol.py", line 103, in open_shell
12:12:47                rs = self.send_message(xmltodict.unparse(rq))
12:12:47              File "/usr/lib/python2.6/site-packages/winrm/protocol.py", line 173, in send_message
12:12:47                return self.transport.send_message(message)
12:12:47              File "/usr/lib/python2.6/site-packages/winrm/transport.py", line 224, in send_message
12:12:47                raise WinRMTransportError('kerberos', error_message)
12:12:47            WinRMTransportError: 500 WinRMTransport. Kerberos-based authentication was failed. Code 500
12:12:47            fatal: [wtv-capstock]: FAILED! => {"failed": true, "msg": "failed to exec cmd PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAoAE4AZQB3AC0ASQB0AGUAbQAgAC0AVAB5AHAAZQAgAEQAaQByAGUAYwB0AG8AcgB5ACAALQBQAGEAdABoACAAJABlAG4AdgA6AHQAZQBtAHAAIAAtAE4AYQBtAGUAIAAiAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAA1ADkAOQA1ADkAMQA2ADYALgA2AC0AMQAzADEAMgAwADkAOQA3ADAAMwA1ADYAOAA1ADgAIgApAC4ARgB1AGwAbABOAGEAbQBlACAAfAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAtAFMAZQBwAGEAcgBhAHQAbwByACAAJwAnADsA"}
```

**Comment by jhawkesworth** [comment]
I have had sporadic kerberos auth failures on rare occasions but I haven't had a problem with this since I sorted out time synchronization between my ansible controller and the domain controllers.
Perhaps not relevant but also, if I recall we also had a problem where DNS was getting out of date because DHCP wasn't communicating with AD, leaving old names for hosts hanging around after their leases had expired.  Kerberos really needs to know the right time and fully trust dns for forward and reverse lookups.

You might get a hint at why the auth failed by checking the event log on the affected servers, 

Also might be worth checking the lifetime of your kerberos tickets too if you have klist available.

**Comment by MichaelBaydoun** [comment]
@jhawkesworth thanks for the suggestions.  We destroy and init all kerberos tickets before each site run, klist shows they are valid for 24 hours.  I've checked the event logs and found nothing.  Our server targets are all static IP's.

Still thinking about the time issues you mentioned.  I would think if the times were too far apart we would have more consistent failures, but I'll look into it.  Our linux servers and domain controllers use the same network switch as their time source however, so that shouldn't be an issue.  

I'm going to try to run some verbose runs and today, hope I catch one of these errors, and hope the extra verbosity helps.

**Comment by MichaelBaydoun** [comment]
Another error, different server, different playbook.  

The play just ran through an include in the playbook to configure an OS agent, the last task being

```
15:27:10            TASK [newrelic : create label] *************************************************
15:27:52            changed: [wtv-services]
```

Then catches the next include to configure a dotNet agent

```
15:27:52            TASK [newrelic : include] ******************************************************
15:27:52            included: /home/icansible/ansible/roles/newrelic/tasks/dotNet.yml for wtv-services
```

Then fails on the first task inside that include

```
15:27:52            TASK [newrelic : do we have the installer] *************************************
15:27:54            Traceback (most recent call last):
15:27:54              File "/usr/lib/python2.6/site-packages/ansible/plugins/connection/winrm.py", line 244, in exec_command
15:27:54                result = self._winrm_exec(cmd_parts[0], cmd_parts[1:], from_exec=True)
15:27:54              File "/usr/lib/python2.6/site-packages/ansible/plugins/connection/winrm.py", line 177, in _winrm_exec
15:27:54                self.shell_id = self.protocol.open_shell(codepage=65001) # UTF-8
15:27:54              File "/usr/lib/python2.6/site-packages/winrm/protocol.py", line 103, in open_shell
15:27:54                rs = self.send_message(xmltodict.unparse(rq))
15:27:54              File "/usr/lib/python2.6/site-packages/winrm/protocol.py", line 173, in send_message
15:27:54                return self.transport.send_message(message)
15:27:54              File "/usr/lib/python2.6/site-packages/winrm/transport.py", line 224, in send_message
15:27:54                raise WinRMTransportError('kerberos', error_message)
15:27:54            WinRMTransportError: 500 WinRMTransport. Kerberos-based authentication was failed. Code 500
15:27:54            fatal: [wtv-services]: FAILED! => {"failed": true, "msg": "failed to exec cmd PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAoAE4AZQB3AC0ASQB0AGUAbQAgAC0AVAB5AHAAZQAgAEQAaQByAGUAYwB0AG8AcgB5ACAALQBQAGEAdABoACAAJABlAG4AdgA6AHQAZQBtAHAAIAAtAE4AYQBtAGUAIAAiAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAA1ADkAOQA3ADAAOAA3ADIALgA5ADMALQAxADYANgA5ADAAOAA2ADUAMgAzADIAMQAwADAANQAiACkALgBGAHUAbABsAE4AYQBtAGUAIAB8ACAAVwByAGkAdABlAC0ASABvAHMAdAAgAC0AUwBlAHAAYQByAGEAdABvAHIAIAAnACcAOwA="}
```

which in this case is a simple win_stat

```
- name: do we have the installer
  win_stat:
    path: D:\temp\NewRelicAgent_x64_{{ dotNetAgentVersion }}.msi
  register: installerPresent
```

As you can see from the timestamps, it's rolling along nicely, task after task, then out of the blue bam ... "WinRMTransportError: 500 WinRMTransport. Kerberos-based authentication was failed"

The next run hadn't launched yet, so I checked the kerberos ticket, and it's still valid and did not expire

```
$ klist | grep wtv-services
04/06/16 15:00:28  04/07/16 01:00:02  HTTP/wtv-services.fhlbi.com@FHLBI.COM
```

**Comment by MichaelBaydoun** [comment]
Happened on another server, which has recently finished running one play, and started another.  The failure occured during the setup (gather facts) operation

```
16:10:11            TASK [setup] *******************************************************************
16:10:13            Traceback (most recent call last):
16:10:13              File "/usr/lib/python2.6/site-packages/ansible/plugins/connection/winrm.py", line 244, in exec_command
16:10:13                result = self._winrm_exec(cmd_parts[0], cmd_parts[1:], from_exec=True)
16:10:13              File "/usr/lib/python2.6/site-packages/ansible/plugins/connection/winrm.py", line 177, in _winrm_exec
16:10:13                self.shell_id = self.protocol.open_shell(codepage=65001) # UTF-8
16:10:13              File "/usr/lib/python2.6/site-packages/winrm/protocol.py", line 103, in open_shell
16:10:13                rs = self.send_message(xmltodict.unparse(rq))
16:10:13              File "/usr/lib/python2.6/site-packages/winrm/protocol.py", line 173, in send_message
16:10:13                return self.transport.send_message(message)
16:10:13              File "/usr/lib/python2.6/site-packages/winrm/transport.py", line 224, in send_message
16:10:13                raise WinRMTransportError('kerberos', error_message)
16:10:13            WinRMTransportError: 500 WinRMTransport. Kerberos-based authentication was failed. Code 500
16:10:13            fatal: [wdv-capstockint]: FAILED! => {"failed": true, "msg": "failed to exec cmd PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAoAE4AZQB3AC0ASQB0AGUAbQAgAC0AVAB5AHAAZQAgAEQAaQByAGUAYwB0AG8AcgB5ACAALQBQAGEAdABoACAAJABlAG4AdgA6AHQAZQBtAHAAIAAtAE4AYQBtAGUAIAAiAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAA2ADAAMAA1ADkAOAAxADIALgA0ADkALQA3ADEAMAAzADQAMgAwADUAOQAxADQAMgAxADAAIgApAC4ARgB1AGwAbABOAGEAbQBlACAAfAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAtAFMAZQBwAGEAcgBhAHQAbwByACAAJwAnADsA"}
```

**Comment by MichaelBaydoun** [comment]
Yesterday I was able to launch 4 site.yml jobs using -vvvv, but the error did not occur during any of those runs.  I'll try again today to capture one using -vvvv

**Comment by MichaelBaydoun** [comment]
Finally was able to catch this error while running debug and -vvvv and now know what the problem is, but not how to eliminate it.

The kerberos cache file is created at the top of the site run, there is only one /tmp cache file, and it's used for all windows hosts.

'''
09:06:23            Ticket cache: FILE:/tmp/krb5cc_513
09:06:23            Default principal: ansible-svc-dev@FHLBI.COM
09:06:23  
09:06:23            Valid starting     Expires            Service principal
09:06:23            04/19/16 09:06:22  04/19/16 19:06:22  krbtgt/FHLBI.COM@FHLBI.COM
09:06:23                renew until 04/20/16 09:06:22
'''

Eventually we see the error trying to run setup in this case on one windows server, all others worked.  The error is complaining that the credential cache file /tmp/krb5cc_513 could not be found.

'''
09:07:08              5609 1461071228.38770: error closing connection: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ("Credentials cache file '/tmp/krb5cc_513' not found", -1765328189))
09:07:08              5609 1461071228.38792: done running TaskExecutor() for wdv-fas91/TASK: setup
09:07:08              5609 1461071228.38797: sending task result
09:07:08              5609 1461071228.38930: done sending task result
09:07:08              5609 1461071228.38933: WORKER PROCESS EXITING
'''

It was at that exact moment that someone else launched another site job, which touched the same temp credential cache file

'''
09:07:08    wdv-ansible  1. Command Password for ansible-svc-dev@FHLBI.COM: 
09:07:08            Ticket cache: FILE:/tmp/krb5cc_513
09:07:08            Default principal: ansible-svc-dev@FHLBI.COM
'''

At the beginning of each run, we cat a file containing the password and pipe that to kinit just before running the ansible-playbook command

cat <redacted filename> | kinit <redacted account name>@<redacted domain>; klist; ansible-playbook .....

**Comment by MichaelBaydoun** [comment]
I could specify a unique cache file name for each run, if there was a way to tell ansible about it.

**Comment by MichaelBaydoun** [comment]
Ansible respects the envvar KRB5CCNAME, so we solved this problem by doing something like this

export KRB5CCNAME=/tmp/krb-cache-file.$$; cat <redacted password file> | kinit <redacted account @domain; klist; ansible-playbook site.yml

**Comment by jhawkesworth** [comment]
Thanks for following up on this.

I wrote a callback plugin to acquire kerberos tickets and got round the same issue by using the pid of the ansible run which so far has been sufficiently distinct to avoid problems with multiple simultaneous ansible/playbook runs.

If you are interested the plugin is here:  https://github.com/ansible/ansible/pull/14972 

Its unlikely become part of ansible but might help in your case until integrated ticket management becomes part of ansible.
