### ISSUE TITLE
password_hash/get_encrypted_password uses passlib default of rounds=656000 which is 131 times glibc default

### ISSUE THREAD

**Issue by jlec** [ansible/ansible#15326]
In the password_hash filter function the underlying passlib call uses the default rounds parameter. 

The default for glibc is 5000, the passlib default for sha512 is 656000. This means on a login in a linux account the hash calculation will take significantly longer.

Actually you get basically no rounds parameter when setting it to 5000

``` shell
$ python -c "from passlib.hash import sha512_crypt; print sha512_crypt.encrypt('foo', rounds=5000)"
$6$0zDM3P3/MbIoF0G0$pVmR8hc0ZNYdfGLnFhVKeCGhd32kDXo6ky83JmUWTZCfVQm2IrhnIbrrg5Vyl9XxE5aWzdmuYpvTA6gyOFc5Z.
$ python -c "from passlib.hash import sha512_crypt; print sha512_crypt.encrypt('foo', rounds=5001)"
$6$rounds=5001$VFyJ36YLb/RLhx0e$CAFCB/W7ebYEHIFsZtlJSdvuzEtsYOAvtOwCF7ahqpWqLj62TJp4LlzZ/FiW1B2U5kSKh4xibiJgZyd2ceVoI1
```

Could a simple parameter be added to get_encrypted_password to set the value which has a preferable default what glibc does?

**Comment by BarbzYHOOL** [comment]
This issue is still there in 2.5
