### ISSUE TITLE
bug report: when converting a yaml file to a data structure fail, we can not find what happend whether log or not.

### ISSUE THREAD

**Issue by lvmeng8** [ansible/ansible#15334]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 1.9.4
```
##### SUMMARY

In the case of  using ansible python API and the program processed background, when converting a yaml file to a data structure fail, we can not find what happend whether log or not.
##### STEPS TO REPRODUCE

I use ansible python API to run playbook but the playbook is not exist.

```
<!--- Paste example playbooks or commands between quotes -->
 stats = callbacks.AggregateStats()
    playbook_cb = callbacks.PlaybookCallbacks(verbose=utils.VERBOSITY)
    runner_cb = callbacks.PlaybookRunnerCallbacks(stats, verbose=utils.VERBOSITY)
    forks_num = 5
    private_file = 1.rsa
    dest_inventory = ansible.inventory.Inventory(["172.28.0.2"])
    args=None

    pb_ins = ansible.playbook.PlayBook(
        playbook = /home/test.yml,
        remote_user = host_user,
        private_key_file = private_file,
        stats = stats,
        callbacks = playbook_cb,
        runner_callbacks = runner_cb,
        inventory = dest_inventory,
        forks=forks_num,
        #check=True,
        extra_vars = args
        )

    # running the playbook
    pb_result = pb_ins.run()
```

##### EXPECTED RESULTS

I can find error message, "playbook is not found" ,e.g, in the log,  /var/log/ansible.log
##### ACTUAL RESULTS

I find nothing in the file.

```
<!--- Paste verbatim command output between quotes -->
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible-devel on irc.freenode.net  
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
