### ISSUE TITLE
Ansible playbook run time information

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#1534]
It would be useful to have a variable set by ansible keeping track of the start-time of a playbook and/or the elapsed time of the playbook, so that we can report at the end about how long a given process ran.

I remember discussing this on IRC with @skvidal, but am not sure whether this was already considered before.

**Comment by mpdehaan** [comment]
It seems this could be pretty easily accomplished just by running "time
playbook ..." or wrapping it in a script.

**Comment by dagwieers** [comment]
Sure, but then you cannot report it from Ansible itself (e.g. the mail that is send at the end of a successful process containing other useful information)

**Comment by jpmens** [comment]
An idea for a callback plugin? Start timer in `playbook_on_start` and end in `playbook_on_stats` ?

**Comment by mgcrea** [comment]
@mpdehaan Is there a way to enable per task tracking of elapsed time?

Moving from:

``` bash
TASK: [databases/redis | Redis | ARM | Check version] ************************* 
changed: [cubieboard]
changed: [raspberry]
```

to:

``` bash
TASK: [databases/redis | Redis | ARM | Check version] ************************* 
changed: [+6ms] [cubieboard]
changed: [+12s 10ms] [raspberry]
```

Having the absolute date would also be an option.

For long playbooks (like compiling stuff on low-power ARM boards), having some kind of per-task datetime info would be nice, since you usually don't wait for them (I'm firing it up in a screen session).

Would be nice to have a flag in `ansible-playbook` to allow that.

**Comment by nicocesar** [comment]
+1

**Comment by bcoca** [comment]
you can do this will callback plugins, I'm pretty sure there are already
existing ones that do this, i use the "profile_tasks.py" one to give me a
general summary, but it is already very close to what you are asking for​

**Comment by cybermaster** [comment]
After 2.0.0.1 the callback plugins stop working. https://github.com/ansible/ansible/tree/devel/lib/ansible/plugins/callback

**Comment by grealish** [comment]
One year on; Whats our options here to have callback's or anyway to report e.g time of a task taken?
I see a way of reporting is very important feature to have so one can actually provide metrics about the deployment of a environment ,e.g in a bank or large corp is would be a hard requirement

**Comment by dagwieers** [comment]
@grealish We now have a **profile_tasks**, **profile_roles** and **timer** callback plugin in Ansible.
- profile_tasks: *This callback module provides per-task timing, ongoing playbook elapsed time and ordered list of top 20 longest running tasks at end.*
- profile_roles: *This callback module provides profiling for ansible roles.*
- timer: *This callback module tells you how long your plays ran for.*

If you need anything else, you can modify/create your own.
