### ISSUE TITLE
Pretty output with --verbose in playbooks

### ISSUE THREAD

**Issue by lbtq** [ansible/ansible#1538]
It looks like you already fixed playbook output on failure, but when using --verbose on a successful run the output is still just one big string.  Would it be possible to break up the stderr and stdout, and parse newlines in --verbose output?  This would be very helpful for logging and conditional runs.

**Comment by mpdehaan** [comment]
Like what we've got at this point, plus this is 3 months old.  I think it's changed some.

**Comment by alfredodeza** [comment]
I was looking into this today (using `ansible` v1.2.2) and I am getting log output as a single string without honoring newlines.

This is the example of one of the tasks (failing with a traceback):

```
TASK: [install the ceph key] **************************************************
<192.168.111.100> REMOTE_MODULE apt_key url=https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc state=present
failed: [192.168.111.100] => {"failed": true, "item": "", "traceback": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-1375906706.94-275552287768312/apt_key\", line 104, in download_key\n    connection = urlopen(url)\n  File \"/usr/lib/python2.7/urllib2.py\", line 126, in urlopen\n    return _opener.open(url, data, timeout)\n  File \"/usr/lib/python2.7/urllib2.py\", line 400, in open\n    response = self._open(req, data)\n  File \"/usr/lib/python2.7/urllib2.py\", line 418, in _open\n    '_open', req)\n  File \"/usr/lib/python2.7/urllib2.py\", line 378, in _call_chain\n    result = func(*args)\n  File \"/usr/lib/python2.7/urllib2.py\", line 1215, in https_open\n    return self.do_open(httplib.HTTPSConnection, req)\n  File \"/usr/lib/python2.7/urllib2.py\", line 1177, in do_open\n    raise URLError(err)\nURLError: <urlopen error [Errno -3] Temporary failure in name resolution>\n"}
msg: error getting key id from url

FATAL: all hosts have already failed -- aborting
```

@mpdehaan  Is it possible to get this issue re-opened if you can confirm what I see when passing `-vvv` ? Or any other pointers into how we can improve this output would be great too.

**Comment by mpdehaan** [comment]
I'm actually ok with this, the actual problem is the traceback which should be intercepted and fixed in the module.

**Comment by alfredodeza** [comment]
Correct.

However, it really looks nicer here as the horizontal scroll appears because it sees one long line in the traceback value, but in a terminal it looks all clobbered.

Getting the module to honor the newlines would be great. Would you like me to open a different ticket for that?

**Comment by alfredodeza** [comment]
@mpdehaan I wasn't clear if I should open a new ticket on this or if it was a wont-fix.

Care to elaborate? 

If the fix is straightforward I could attempt a pull request, but it wasn't too clear to me where is it that the module is ignoring the newlines.
