### ISSUE TITLE
Variables not defined in a handler of a dependency

### ISSUE THREAD

**Issue by oxyrox** [ansible/ansible#15418]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Variables are not being passed onto a handler of a roles dependency
##### STEPS TO REPRODUCE

Clone https://github.com/oxyrox/ansible-reports and run

```
ansible-playbook playbook.yml
```
##### EXPECTED RESULTS

I'm expecting the dependency's handler to have the variable defined, like it is in the role itself. Yet it seems to be undefined. Expected output:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [role2 : debug] ***********************************************************
ok: [localhost] => {
    "print": "FooBar"
}

TASK [role1 : debug] ***********************************************************
ok: [localhost] => {
    "print": "FooBar"
}

TASK [role1 : command] *********************************************************
changed: [localhost]

RUNNING HANDLER [role2 : print role2] ******************************************
ok: [localhost] => {
    "print": "FooBar"
}

RUNNING HANDLER [role1 : print role1] ******************************************
ok: [localhost] => {
    "print": "FooBar"
}

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=1    unreachable=0    failed=0
```
##### ACTUAL RESULTS

The handler of the dependency shows the passed variable as undefined.

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [role2 : debug] ***********************************************************
ok: [localhost] => {
    "print": "FooBar"
}

TASK [role1 : debug] ***********************************************************
ok: [localhost] => {
    "print": "FooBar"
}

TASK [role1 : command] *********************************************************
changed: [localhost]

RUNNING HANDLER [role2 : print role2] ******************************************
ok: [localhost] => {
    "print": "VARIABLE IS NOT DEFINED!"
}

RUNNING HANDLER [role1 : print role1] ******************************************
ok: [localhost] => {
    "print": "FooBar"
}

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=1    unreachable=0    failed=0
```

**Comment by bcoca** [comment]
cc @jimi-c @abadger

**Comment by akiessling** [comment]
I think i encountered the same bug. It worked in 1.9 though

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment]
Note, a separate patch will have to be created for stable-2.1, as this can't be cherry-picked cleanly.
