### ISSUE TITLE
Check mode should be more obvious and should be available inside playbook

### ISSUE THREAD

**Issue by njia** [ansible/ansible#15424]
##### ISSUE TYPE

- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### SUMMARY

--check currently is only available as command line option and sometimes people forget so it would be nice if there is something like `check_mode: True` in playbook so we don't have to worry about command line options.

The output of check mode run should be more obvious to indicate that this is a check only.

Thanks

**Comment by robinro** [comment]
This is a duplicate of https://github.com/ansible/ansible/issues/12498.

**Comment by bcoca** [comment]
closing as dupe
