### ISSUE TITLE
Make variables can be merged even in single yml file

### ISSUE THREAD

**Issue by chengrcli** [ansible/ansible#15442]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.1.0 (devel 319e50abd5)
```
##### SUMMARY

I prefer the feature that: the variable can be merged in following example, instead of [using the last defined. ](https://github.com/ansible/ansible/blob/stable-2.0.0.1/lib/ansible/parsing/yaml/constructor.py#L68)

```
name:
  first: first name
name:
  second: second name
```

after merge it should like this

```
name:
  first: first name
  second: second name
```
# 
##### Besides

It seems variables can't be merge with those in dependency roles, instead it just replaced, even I configured it to merge in ansible.cfg.

**Comment by bcoca** [comment]
This already exists, the `combine` filter.

http://docs.ansible.com/ansible/playbooks_filters.html#combining-hashes-dictionaries
