### ISSUE TITLE
[Bug] Handler Triggering Problem

### ISSUE THREAD

**Issue by MPW1412** [ansible/ansible#15452]
Hello,

we stumbled across the following bug.

```
# ansible --version
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
```

If there's a handler defined in more than one role and on one of these roles is disabled by a when statement, the handler is skipped at the end although it needs to be called.
##### STEPS TO REPRODUCE

Use the same handler in two roles. Disable one of them with when: false in the yml file. Play the playbook and do changes so that the handler is notified. It will be skipped, that's the bug.
##### EXPECTED RESULTS

If the handler is called once anywhere, it should be executed at the end.
##### ACTUAL RESULTS

The handler is skipped.

``````
RUNNING HANDLER [backbone_gre_ffrl : restart networking] ***********************
skipping: [greyworm-06]   ```

Regards,
Matthias
``````

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

I see 2 misunderstandings here:
- Handlers are unique so having it in multiple roles means you only have 1 handler, the last one defined
- `when:` clauses do not control role imports, they get applied to every task (including handlers) in that role. Importing the handler, vars and adding other resources to the play still happen.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by MPW1412** [comment]
The only misunderstanding here is, that you misunderstood me.

Like you said, there is one handler, let's call it handlerA. HandlerA is used in two different roles. One of these roles is skipped with a when-condition in the yml file, just like that:

```
    - { role: roleA, tags: "roleA", when: false}
    - { role: roleB, tags: "roleB"}
```

roleA is not executed, roleB does changes and calls the handlerA. But the handler is skipped at the end, because of the when-condition for roleA.

That is a bug in ansible's logic. handlerA shouldn't be skip, because one role is disabled, which uses handlerA. It should be executed if one role does changes and requires handlerA among many disalbed roles.

Workaround:

If you remove the when-condition in the yml and insert the same when-condition into each and every task in roleA, it works as expected.
