### ISSUE TITLE
become_user: root with yum: name=url causes error

### ISSUE THREAD

**Issue by surfmikko** [ansible/ansible#15499]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Default settings
##### OS / ENVIRONMENT

CentOS release 6.7 (Final)
##### SUMMARY

Yum fails to install packages when using become_user and URL's as names. Using localhost as installation target.

Installation is successful when with simple package names or sudo: true.
##### STEPS TO REPRODUCE

Provided playbook and hosts definition to reproduce the error.

```
--- hosts
[all]
localhost ansible_connection=local

--- site.yml
- hosts: all
  become_user: root
  tasks:
    - name: Install with package name (ok)
      yum: state=present name=epel-release
    - name: Install with url (not ok)
      yum: state=present name=http://mirror.nsc.liu.se/fedora-epel/6/x86_64/epel-release-6-8.noarch.rpm

--- command
$ ansible-playbook -i hosts site.yml 
```

##### EXPECTED RESULTS

Expected Ansible to install package from given URL.
##### ACTUAL RESULTS

Command fails and reports the following error message.

```
$ ansible-playbook -i hosts site.yml 

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Install with package name (ok)] ******************************************
ok: [localhost]

TASK [Install with url (not ok)] ***********************************************
fatal: [localhost]: FAILED! => {"changed": true, "failed": true, "msg": "You need to be root to perform this command.\n", "rc": 1, "results": ["Loaded plugins: fastestmirror, presto, versionlock\n"]}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   
```

**Comment by Tahvok** [comment]
Setting become_user does not set become. This is explained here:
http://docs.ansible.com/ansible/become.html#directives

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
