### ISSUE TITLE
Incorrect date in RELEASES.txt

### ISSUE THREAD

**Issue by warrenseine** [ansible/ansible#15500]
##### ISSUE TYPE
- Bug Report
##### SUMMARY

The file `ansible/RELEASES.txt` mentions incorrect release dates.
##### STEPS TO REPRODUCE

Open https://github.com/ansible/ansible/blob/24d9e5e0b44225bda7981839059e21a69f583ebe/RELEASES.txt.
##### EXPECTED RESULTS

2016 for the 3 last releases.
##### ACTUAL RESULTS

2015.

**Comment by bcoca** [comment]
since the current version is correct, closing this https://github.com/ansible/ansible/blob/devel/RELEASES.txt
