### ISSUE TITLE
become_user don't run command in the given user

### ISSUE THREAD

**Issue by PumpkinSeed** [ansible/ansible#15503]
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### OS / ENVIRONMENT

CentOS 7
##### SUMMARY

I want to run a section with an other user but instead of the ansible use the user which had ssh to the host. 
##### CODE

```
- name: get the username running the deploy
  local_action: command whoami
  register: username_on_the_host
  remote_user: buildbot
```

OR

```
- name: get the username running the deploy
  local_action: command whoami
  register: username_on_the_host
  become_user: buildbot
```
##### RESULT

```
"username_on_the_host": {
        "changed": true, 
        "cmd": [
            "whoami"
        ], 
        "delta": "0:00:00.006835", 
        "end": "2016-04-20 15:34:49.155757", 
        "rc": 0, 
        "start": "2016-04-20 15:34:49.148922", 
        "stderr": "", 
        "stdout": "root", 
        "stdout_lines": [
            "root"
        ], 
        "warnings": []
    }

```

**Comment by bcoca** [comment]
- The `local` transport cannot use `remote_user` so it is always the "current user executing" unless you use become.
- `become_user` does not imply `become: True` as this can be set at host level

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
