### ISSUE TITLE
Ansible doesn't load .profile and .bashrc files

### ISSUE THREAD

**Issue by baratali** [ansible/ansible#15518]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
~$ ansible --version
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

I added only one property to /etc/ansible/ansible.cfg:
`sudo_flags = -i`

##### OS / ENVIRONMENT

```
~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty
```

##### SUMMARY

I installed ansible by means `apt-get` as it described in http://docs.ansible.com/ansible/intro_installation.html#latest-releases-via-apt-ubuntu:

```
sudo apt-get install software-properties-common
sudo apt-add-repository ppa:ansible/ansible
sudo apt-get update
sudo apt-get install ansible
sudo sh -c "echo 'sudo_flags = -i' >> /etc/ansible/ansible.cfg"
```

I try to deploy my application to my own machine (localhost) by means ansible-playbook. I have a lot of env variables defined in `~/.profile` file. Without them deploying fails. As I know there is special property `sudo_flags = -i`that tells ansible to load `.profile`, `.bashrc`, etc files before deploying. I added it to `/etc/ansible/ansible.cfg`. So, the problem is that ansible doesn't see any env variables from `.profile`, even with `sudo_flags = -i` config.
However, if I install ansible by means `pip`, it works fine:

```
sudo apt-get remove ansible
sudo apt-get install python-pip
sudo pip install ansible
sudo sh -c "echo 'sudo_flags = -i' >> /etc/ansible/ansible.cfg"
```

Maybe there is a bug in ansible ubuntu package, because I can reproduce the same problem on another ubuntu machine.

**Comment by bcoca** [comment]
This is expected and by design, Ansible is a batch system and avoid interactive logins if possible, which means it won't source certain user/shell specific files.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by baratali** [comment]
@bcoca , but how it works if I install ansible by means `python-pip`? With `sudo_flags = -i` in configs ansible loads `.profle`.
It doesn't work only if install ansible by means ubuntu's `apt-get`.

**Comment by bcoca** [comment]
That difference on install makes no sense, unless the ubuntu packager is modifying the source. In the case of adding sudo -i, its sudo, not ansible, that loads them.

**Comment by baratali** [comment]
@bcoca , I have `sudo_flags = -i` in both cases (ubuntu packaging and pip packaging).
Do you know ways to make ansible to load env variables without using `sudo -i`?

**Comment by baratali** [comment]
@bcoca,

>  unless the ubuntu packager is modifying the source

Who is responsible for generating ansible ubuntu package? Maybe there is a bug in the package, and I need to file an issue to them.

**Comment by soulslicer** [comment]
Has this issue been fixed? Is there any workaround?

**Comment by baratali** [comment]
@soulslicer , workaround was installing ansible via pip: `sudo pip install ansible`

**Comment by soulslicer** [comment]
That is unfortunate.
