### ISSUE TITLE
docs.ansible.com is hard to use on narrow windows

### ISSUE THREAD

**Issue by smiller171** [ansible/ansible#15522]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

N/A
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Browser
##### SUMMARY

Ansible Docs are hard or impossible to read in narrow windows. The responsive scripts seem to always think the window is ~15% wider than it is, meaning the left-toolbar does not collapse properly, and even once it does, the text in the far-right column of the documentation tables gets truncated. There is also no horizontal scroll available to see the rest of the content. I have tested in Safari and Chrome. It has been this way for a very long time.
##### STEPS TO REPRODUCE

Navigate to any module on docs.ansible.com in Chrome or Safari and resize your window so that it is less wide.
##### EXPECTED RESULTS

Content resizes to fit screen
##### ACTUAL RESULTS

Content overflows window
<img width="722" alt="screen shot 2016-04-21 at 11 30 43 am" src="https://cloud.githubusercontent.com/assets/3587913/14714818/85026934-07b4-11e6-83b1-c3f2aeda47f4.png">

**Comment by talon-vonneudeck** [comment]
Asked about that on twitter in February. Some tables have been fixed, some have not. So this should be easy to make a default.
https://twitter.com/ansible/status/694603028737863681

**Comment by bcoca** [comment]
cc @docschick

**Comment by docschick** [comment]
@jlmitch5 do you remember the fix for the tables that were too wide? Is this something you and your mad skillz could help with again?

**Comment by dflock** [comment]
You need to do something like this in the CSS:

``` css
td {
    word-break: break-all;
}
```

See here for more details, edge cases, cross browser CSS, etc...: https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/

**Comment by docschick** [comment]
@bcoca want to cherry pick this one? My PRs still seem FUBAR'd and I don't want to create a hella PR that is mostly crap...  https://github.com/docschick/ansible/commit/728b063b30676a3142acfdbbc1d1fe901053c6cf

**Comment by bcoca** [comment]
done
