### ISSUE TITLE
Instructions on how to uninstall ansible on a mac.   Goofed and want to reinstall clean.

### ISSUE THREAD

**Issue by alberttwong** [ansible/ansible#15534]
##### ISSUE TYPE
- Documentation Report
##### OS / ENVIRONMENT

Mac
##### SUMMARY

Instructions on how to uninstall ansible on a mac.  I goofed and I didn't install it by pip and I can't figure out what I did.   What are all the files I need to delete so I can get a clean environment to reinstall ansible correctly through pip?

**Comment by gregimba** [comment]
You probably installed it via homebrew so you can just 
`brew uninstall ansible`
and then `pip install ansible`

**Comment by alberttwong** [comment]
I also just ran `sudo -H pip uninstall ansible` and reran the install.   It seemed to work.

**Comment by pavarotti305** [comment]
Perfect worked perfectly for me
