### ISSUE TITLE
flag to disable rpm warning

### ISSUE THREAD

**Issue by m1au** [ansible/ansible#15547]
I'm using rpm to whether package is already installed for conditional runs but im getting following warning message

```
 Consider using yum module rather than running rpm
```

Would it be possible to add flag to disable this warning as currently yum module does not support check for package existance

**Comment by dagwieers** [comment]
Jup, this is rather annoying. I don't think Ansible should be guessing why the user is doing something or giving advice on doing something better, how well intended it may be, it may be misguided.

**Comment by dagwieers** [comment]
BTW I noticed this is already possible with the option `warn`:

``` yaml
- command: rpm -q whatever
  args:
    warn: no
```

@bcoca I guess this can be closed ?

**Comment by bcoca** [comment]
closing as per above

**Comment by m1au** [comment]
Thanks
