### ISSUE TITLE
Patch Management

### ISSUE THREAD

**Issue by dpkpradhan** [ansible/ansible#15542]
How we can do this?

Patching as a maintenance task to maintain various images as compared to a master golden image – How can we use Ansible to do the patch management and ensure both images are alike.

Thanks,
Deepak

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
