### ISSUE TITLE
Windows: still able to connect to windows host even after the certificate has expired

### ISSUE THREAD

**Issue by jhawkesworth** [ansible/ansible#15541]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = /etc/ansible/library

```
##### CONFIGURATION

The following in set in group_vars/all

ansible_winrm_server_cert_validation: ignore 

Hosts in affected groups have the following in their group vars:

ansible_ssh_port: 5986
ansible_connection: winrm
##### OS / ENVIRONMENT

Ansible on: Centos 6.5 , Python 2.6.6
Manging: Server 2012 R2
##### SUMMARY

Even though the self-signed certificate used by winrm has expired, ansible is still able to connect and run modules.
##### STEPS TO REPRODUCE

1/ Set up a windows host for remoting as described in ansible documentation, but run
 https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 
with -CertValidityDays 1
2/ Wait until the certificate has expired
3/ run the setup module against the windows host with expired certificate and look for the 'ansible_winrm_certificate_expires' attribute in the returned facts about the host

```
ansible windowshosts -m setup

```
##### EXPECTED RESULTS

setup module should fail as access should be denied due to expired certificate.
##### ACTUAL RESULTS

Ansible returns the results of calling the setup module on the windows hosts

```
testhost | SUCCESS => {
    "ansible_facts": {
        "ansible_architecture": "64-bit",
        "ansible_date_time": {
            "date": "4/22/2016",
            "day": "22",
            "hour": "05",
            "iso8601": "2016-04-22T05:37:58",
            "minute": "37",
            "month": "04",
            "year": "2016"
        },
        "ansible_distribution": "Microsoft Windows NT 6.3.9600.0",
        "ansible_distribution_version": "6.3.9600.0",
        "ansible_fqdn": "testhost.mydomain.com",
        "ansible_hostname": "testhost",
        "ansible_interfaces": [
            {
                "default_gateway": "xxx.xxx.xxx.xxx",
                "dns_domain": null,
                "interface_index": 12,
                "interface_name": "Ethernet Adapter"
            }
        ],
        "ansible_ip_addresses": [
            "xxx.xxx.xxx.xxx"
        ],
        "ansible_lastboot": "2016-02-20 14:37:51Z",
        "ansible_os_family": "Windows",
        "ansible_os_name": "Microsoft Windows Server 2012 R2 Standard",
        "ansible_powershell_version": 4,
        "ansible_system": "Win32NT",
        "ansible_totalmem": 4294496256,
        "ansible_uptime_seconds": 5324407,
        "ansible_winrm_certificate_expires": "2016-04-21 11:52:07"
    },
    "changed": false
}
```

**Comment by sivel** [comment]
Aren't you specifying to ignore server cert validation?  Based on what you supplied, this feels like the correct outcome.

**Comment by jhawkesworth** [comment]
You might be right.  I thought setting

```
ansible_winrm_server_cert_validation: ignore
```

only turned off checking the full trust chain, but maybe its just not checking anything about the cert at all.

I'll investigate further as time allows, unless anyone knows or can point me in the right direction.

**Comment by sivel** [comment]
From looking at pywinrm, it looks like when `ignore` is specified, the ssl context is created with a `verify_mode` of `CERT_NONE`.

Per the python SSL docs:

> ssl.CERT_NONE
> Possible value for SSLContext.verify_mode, or the cert_reqs parameter to wrap_socket(). In this mode (the default), no certificates will be required from the other side of the socket connection. If a certificate is received from the other end, no attempt to validate it is made

So it looks like validation is completely disabled when `ignore` is specified.

**Comment by nitzmahone** [comment]
There are two code paths for this- (what I suspect is) the original one uses a cmdlet (New-SelfSignedCertificate) that's only available on 2012R2+ which doesn't support setting the validity period (until Win10/Server2016). The other path (New-LegacySelfSignedCert) is only used if the New-SelfSignedCertificate cmdlet is missing- it uses a COM cert enrollment object, which _does_ support setting the validity period. Currently, the first path just silently ignores the validity period setting.

Seems like the easy fix here is to either ditch the cmdlet path altogether, or only use it if the validity period isn't specified.

**Comment by nitzmahone** [comment]
Oh, and verified against https://expired.badssl.com/ with Python 2.7.9 that disabling validation ignores an expired cert, while leaving it on does fail (without telling you exactly why).

**Comment by jhawkesworth** [comment]
Thanks for following this up @sivel and @nitzmahone 

It's working as intended,  so I am going to close this issue.
