### ISSUE TITLE
Overwritten variables in template not passed to included templates

### ISSUE THREAD

**Issue by Mikulas** [ansible/ansible#15576]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /Users/mikulas/Projects/sysops/ansible.cfg
  configured module search path = Default w/o overrides
```

and also

```
ansible 2.0.2.0
  config file = /Users/mikulas/Projects/sysops/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

/Users/mikulas/Projects/sysops/ansible.cfg:

```
[defaults]
roles_path = /usr/local/etc/ansible/roles:apps:roles
error_on_undefined_vars = True
callback_plugins = plugins/
retry_files_enabled = False
```

no `ANSIBLE_*` env defined
##### OS / ENVIRONMENT

OS X 10.11.4 (15E65), ansible installed via brew
##### SUMMARY

Overwriting a variable in template is not respected in included child template. See the linked gist.
##### STEPS TO REPRODUCE

https://gist.github.com/Mikulas/a0f1a15fb1868d3f40e414a15286e8d1
##### EXPECTED RESULTS

```
outer = original

    inner = inner a
    in template = inner a
    inner = inner b
    in template = inner b

outer = original
```
##### ACTUAL RESULTS

```
outer = original

    inner = inner a
    in template = original
    inner = inner b
    in template = original

outer = original
```
##### OUTPUT DIFF

``` diff
4c4
<   in template = inner a

---
>   in template = original
6c6
<   in template = inner b

---
>   in template = original
```

**Comment by alikins** [comment]
I see the same behavior in 2.0.0/2.0.1/2.0.2 and devel branch, so it doesn't seem to be a regression since 2.0. 

Did this used to work?

**Comment by bcoca** [comment]
this is not an Ansible issue but a jinja2 issue, works as expected as per their docs:
http://jinja.pocoo.org/docs/dev/templates/#include

use `with context` to pass down changes to included templates.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
