### ISSUE TITLE
env lookup should default to None or allow own default

### ISSUE THREAD

**Issue by domdom82** [ansible/ansible#15575]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### OS / ENVIRONMENT

Mac OS X
14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
##### SUMMARY

I am trying to include playbooks from other directories based on env variables.
The env variable may or may not be set in which case a default value should take effect.

The current approach does **not** work:

```
- include: "{{ lookup('env', 'OTHER_HOME')|default('playbook_dir/../other') }}/otherplaybook.yml"
```

The problem is that the lookup defaults to an empty string if the env var is not found which in turn does **not** trigger the chained default.
##### STEPS TO REPRODUCE

```
- Write two playbooks in separate folders. 
- Try to include the second into the first using method described without an env variable set on cmdline.
<!--- Paste example playbooks or commands between quotes -->
```

##### EXPECTED RESULTS

- Other playbook gets included based on default path
##### ACTUAL RESULTS

- Default path not set. Other playbook not found / included.

```
ERROR! the file_name '/otherplaybook.yml' does not exist, or is not readable
```

**Comment by xox2** [comment]
`default` filter can be applied to undefined variables only.

I think hard to implement to fix it. because maybe the return value of `lookup('env', ...)` is **not meaning of undefined variables**.

the following is an alternative implementation:

```
- include: "{{ lookup('env', 'OTHER_HOME')|default('playbook_dir/../other', true) }}/otherplaybook.yml"
```

set `true` as second parameter of `default` filter: `default(..., true)`
- See: [Template Designer Documentation — Jinja2 Documentation (2.8-dev)](http://jinja.pocoo.org/docs/dev/templates/#default)

**Comment by domdom82** [comment]
That worked thanks!

**Comment by hughsaunders** [comment]
`default(var, true)`  isn't so useful for booleans, as it will replace anything that evaluates to false. If you want to set a default when the provided var is  `""` then you can use a jinja if statement.

**Comment by folkol** [comment]
This should work: `{{ lookup('env', 'OTHER_HOME') or '/tmp' }}`

**Comment by gaelrottier** [comment]
@folkol Wow thanks I would never have thought of that
