### ISSUE TITLE
Be able to override ok and changed messages

### ISSUE THREAD

**Issue by gmarziou** [ansible/ansible#15583]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I'd like to be able to specify `ok` and `changed` messages, this would enable:
- to override default messages when they are too verbose for instance with hash objects as in issue #5564
- to provide messages in other languages than English

Example:

Default message is:

```
ok: [my-host.example.org] => (item={'value': {u'version': u'latest', u'type': u'jar'}, 'key': u'service-cart'})
```

With proposed change, We could configure another ok message:

```
ok: {{ item.key }} has been updated.
```

and the message at execution would be:

```
ok: [my-host.example.org] => (service-cart has been updated)
```

Same thing for `changed`.

**Comment by bcoca** [comment]
#12086 look at 'label' proposal also #13710

**Comment by gmarziou** [comment]
Great, I like both so closing this one.
