### ISSUE TITLE
Make module output more consistent wrt. failed= and changed=

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#1559]
Would it be acceptable to make the output of modules more consistent ?

Currently some modules (e.g. yum) when they succeed without changes, return explicitely:

```
failed=False, changed=False
```

others (e.g. file) return only:

```
changed=False
```

Given we should not expect `changed=True` or `failed=True` to be set, I would like to change all modules to only add `changed=True` and `failed=True` and leave it out when False. For me the benefit is that the verbose output is more condensed and thus easier to parse quickly.

**Update:** After discussion on IRC on 8/11/2012 it was established that:
- Testing for changes should (always) work (by use of ${action.changed}
- Testing for failure is not recommended for all modules as they are fatal (notable exceptions here are shell/command)
  - If needed, test if ${action.changed} is set and is True
- Testing for rc value is not recommended (notable exceptions here are shell/command) and not likely to work in all cases

**Comment by dhozac** [comment]
This would break only_if: ${action.changed}

**Comment by dagwieers** [comment]
The current PR #1560 makes sure changed= is now always set by exit_json().

Otherwise "only_if: ${action.changed}" would return a syntax error if a module would not return changed=

**Comment by mpdehaan** [comment]
Changed=False I like.  Always adding failed when it is False I do not.  So no to not always showing changed, but yes to not showing failed when things pass seems correct to me.

-- Michael

**Comment by dagwieers** [comment]
Check out the pull-request...

**Comment by skvidal** [comment]
okay - so the only reason I would want to always have a failed there is so I can do things like
- name: some stuff
  action: my_module_which_if_not_failed_I_need_to_check
  ignore_errors: true
  register: module
- name: check for the above
  action: ec2_create an instance
  only_if: '${module.failed}'

if failed is not always there then that brings up a syntax when actually it is 'false'.

How should I go about doing the above? Essentially I need to check the value of an dictionary key which may or may not be there.

if I could do module.get('failed', False) in a playbook, I guess I would...

Can I do that?

**Comment by mpdehaan** [comment]
Yeah ansible really wasn't made for those kinds of logical structures so
much.

Seth has a good point.

only_if: getattr(...) is gross but would work, though it seems better to
abstract that as "when_failed: $module_result" (and have another
when_successful)

failed=False just reads weird to me, so I would like to avoid it.

**Comment by dhozac** [comment]
only_if: is_set('${module.failed}') or when_set: ${module.failed} is what you want.

**Comment by mpdehaan** [comment]
It would be nice to also check truthiness

-- Michael

**Comment by dhozac** [comment]
Prior to #1487 being merged, there were no modules returning failed if it wasn't true. Thus, if it is set, the task has failed. Dag's PR restores this behaviour.

**Comment by dagwieers** [comment]
When looking into this, only yum did this differently. All the other modules only set failed=True explicitly on failure (or call fail_json()) and didn't bother on success.

Personally I would recommend from the module documentation to always call fail_json() on failure, and always call exit_json() on success so it is more obvious where something can fail or succeed without the need to check any arguments passed. And elsewhere we might need to warn users that evaluating return codes only is recommended for shell/command modules.

**Comment by mpdehaan** [comment]
Is successful logic still cannot rely on is_set nor is failed=False technically illegal

-- Michael

**Comment by mpdehaan** [comment]
dag's comment is ALSO correct

-- Michael

**Comment by dagwieers** [comment]
My original patch was adding failed=False from exit_json(), but that would break people's playbook that only checked for failed to be set. And was Daniel's first objection.

_FWIW I was also the person in favor of adding rc values in all cases ;-)_

**Comment by mpdehaan** [comment]
adding "when_boolean" seems sufficient and consistent, I'll close this given recent activity and simplify discussion.
