### ISSUE TITLE
Become with doas not working

### ISSUE THREAD

**Issue by mrijkeboer** [ansible/ansible#15597]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[privilege_escalation]
become=True
become_method=doas
become_user=root
become_ask_pass=True
```
##### OS / ENVIRONMENT

From: Mac OS X 10.11
To: OpenBSD 5.9 AMD64
##### SUMMARY

The doas prompt definition in play_context.py is incorrect. Currently it is set to 'Password:' but the doas command uses the following layout 'doas (user@host.domain.com) password: ' with user, host and domain replaced with the actual values. When I replace the prompt with the values for my server it will work, however, since it will only work with that particular server this is not an option. I guess that using wildcards would be an option.
##### STEPS TO REPRODUCE

By setting become to doas and sending a ping to the host.

```
ansible host.domain.com -m ping -K
```
##### EXPECTED RESULTS

```
host.domain.com | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
```
##### ACTUAL RESULTS

```
host.domain.com | FAILED! => {
    "failed": true,
    "msg": "ERROR! Timeout (12s) waiting for privilege escalation prompt: \r"
}
```

**Comment by bcoca** [comment]
hmm, it was tested on systems that did return `Password:` see if this patch fixes it for you:

```
diff --git a/lib/ansible/playbook/play_context.py b/lib/ansible/playbook/play_context.py
index a79b4e1..96404f2 100644
--- a/lib/ansible/playbook/play_context.py
+++ b/lib/ansible/playbook/play_context.py
@@ -518,7 +518,7 @@ class PlayContext(Base):

             elif self.become_method == 'doas':

-                prompt = 'Password:'
+                prompt = 'assword:'
                 exe = self.become_exe or 'doas'

                 if not self.become_pass:
```

**Comment by mrijkeboer** [comment]
Initially is used `Password:` but this was changed in December 2015 [1]. Unfortunately your change results in the same error:

```
host.domain.com | FAILED! => {
    "failed": true,
    "msg": "ERROR! Timeout (12s) waiting for privilege escalation prompt: \r"
}
```

[1] http://marc.info/?l=openbsd-cvs&m=144913039401774&w=2

**Comment by artob** [comment]
Does anyone know of a workaround? Just encountered this problem myself.

**Comment by sikevux** [comment]
@bendiken add `nopass` to doas.conf . Dirty, but works

**Comment by susurri** [comment]
prompt = 'doas'
or
prompt = 'doas (%s@' % self.remote_user

would work.

**Comment by bcoca** [comment]
So the issue is that older versions of doas worked with just `Password`, this change would be backwards incompatible, but this might be OK as doas is brand new and I don't expect many users to stay with the older versions.

**Comment by mrijkeboer** [comment]
@susurri, @bcoca  Unfortunately I can't test whether this patch works, because I run into problems  before the password prompt (both with and without the patch):

```
host.domain.org | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "doas: a tty is required\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "parsed": false
}
```

**Comment by b-a-t** [comment]
> @susurri, @bcoca Unfortunately I can't test whether this patch works, because I run into problems before the password prompt (both with and without the patch):
> 
> ```
> host.domain.org | FAILED! => {
>     "changed": false, 
>     "failed": true, 
>     "module_stderr": "doas: a tty is required\n", 
>     "module_stdout": "", 
>     "msg": "MODULE FAILURE", 
>     "parsed": false
> }
> ```

This is still the issue, but seems, this is caused by the clash of two problems:

1. `doas` indeed requires TTY for password input, so it (should) work OK with plugins that provide that.
2. The fix in https://github.com/ansible/ansible/pull/16997 actually broke the recognition of the prompt, as `doas` can both use PAM with it's `Password:` prompt and BSD_AUTH, which produces the prompt in the fix.

It seems that something like:

```diff
--- play_context.py.orig        2018-10-09 22:56:07.229248000 +0200
+++ play_context.py     2018-10-10 00:24:00.945572000 +0200
@@ -528,8 +528,10 @@
                 becomecmd = cmd

             elif self.become_method == 'doas':
+                def detect_doas_prompt(b_data):
+                    return re.match(b"assword:", b_data)

-                prompt = 'doas (%s@' % self.remote_user
+                prompt = detect_doas_prompt
                 exe = self.become_exe or 'doas'

                 if not self.become_pass:
```

gives more generic solution.

**Comment by illogic-al** [comment]
Just to add that the solution above from @b-a-t does not work when attempting to use `become_method=doas` on FreeBSD 11. The FreeBSD 11 doas has a `Password:` prompt by default.

Below you can see what I have in my `/usr/local/etc/doas.conf` file on FreeBSD 11.1 (I can confirm this is an issue in 11.0 also)

```
# wheel group can obtain elevated privs
permit setenv { -ENV PS1=$DOAS_PS1 SSH_AUTH_SOCK } :wheel
```

#### ANSIBLE VERSION
```
ansible 2.7.6
  config file = ~/.ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.6/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Jan 13 2019, 12:50:15) [Clang 10.0.0 (clang-1000.11.45.5)]
```

#### OS / ENVIRONMENT
From: Mac OS X 10.13.6
To: FreeBSD 11.1-RELEASE-p4 amd64

Reverting #16997 allows using doas on FreeBSD again. Should I create a new ticket for this?
It seems like we might need a `doas_freebsd` in order to get this working for FreeBSD.
