### ISSUE TITLE
Higher memory usage in 2.0.2.0

### ISSUE THREAD

**Issue by hyperized** [ansible/ansible#15602]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
```
##### CONFIGURATION

No configuration changes since 2.0.1.0
##### OS / ENVIRONMENT

No platform specific changes since 2.0.1.0
##### SUMMARY

According to the graphs of our monitoring system the memory usage on our dedicated Ansible machine has increased when switching from Ansible 2.0.1.0 to 2.0.2.0. The switch was made the second Monday on the graph. We did not change any host configuration or playbooks either.

![ansible-memory-footprint](https://cloud.githubusercontent.com/assets/827954/14819071/c1e1ca10-0bc0-11e6-9b34-9de751050ab3.png)
##### STEPS TO REPRODUCE

With instructions I can possibly run a memory profiler for Ansible / python, but we currently dont have the tooling set up for that. But perhaps a memory profiling on the default test set of Ansible can reveal differences.
##### EXPECTED RESULTS

Memory usage to be closer to 2.0.1.0
##### ACTUAL RESULTS

Its not :)

**Comment by hyperized** [comment]
We did some tweaking on the ansible config file and we got the memory usage to drop, the drop could be attributed to two things: we used explicit facts gathering (now smart) and the facts cache timeout was set to a high level. We use Redis for facts caching.

**Comment by jimi-c** [comment]
@hyperized ok, I was looking at the graph and it definitely didn't seem as bad as it first makes the data look. Towards the end, the utilization is 1.5G vs.~1G during other run times. If you're comfortable with the new config settings dropping memory utilization (as it seems external to Ansible itself) we can close this issue.

**Comment by hyperized** [comment]
I'm comfortable with this :). Could I ask though that a little more focus is given on memory profiling in next releases? It has been going up in usage over time and I would hate to see Ansible becoming bloated in memory usage.

**Comment by jimi-c** [comment]
We generally do, it definitely went up with 2.0 due to some structural changes, but it's been somewhat steady since then. A lot of it is very dependent on size of inventory and things like group/host vars in inventory as well, so it's somewhat difficult to model across all sizes of hosts/vars/etc.

Thanks!
