### ISSUE TITLE
undefined variable + filter in module args casuses hard-to-track-down error(Regression from v1.9)

### ISSUE THREAD

**Issue by ashb** [ansible/ansible#15610]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /Users/ash/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

If you have an error in a template inside a module argument where you also use a filter you stomp on the normal `'foo' is undefined` message.
##### STEPS TO REPRODUCE

Without a filter this works as expected:

```
ansible localhost -m debug -a 'msg={{ foo }}'
localhost | FAILED! => {
    "failed": true,
    "msg": "'foo' is undefined"
}
```

If you couple this with a filter you loose this useful error message and instead get the following:

```
ansible localhost -m debug -a 'msg={{ foo | to_json }}'
localhost | FAILED! => {
    "failed": true,
    "msg": "the field 'args' has an invalid value ([]), and could not be converted to an dict. Error was: Circular reference detected"
}
```

(I ran into this problem with a more complex example involving `lookup('template')` but this above case shows a simple test case.)

**Comment by jimi-c** [comment]
For the record, the output now appears as:

<pre>
# ansible -vvv localhost -m debug -a 'msg={{ foo | to_json }}'
Using /etc/ansible/ansible.cfg as config file
localhost | FAILED! => {
    "failed": true, 
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: Unable to look up a name or access an attribute in template string ({{ foo | to_json }}).\nMake sure your variable name does not contain invalid characters like '-': unbound method default() must be called with JSONEncoder instance as first argument (got StrictUndefined instance instead)"
}
</pre>
