### ISSUE TITLE
Enable encrypted password support in ansible via individually encrypted values

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#15617]
Currently Ansible solution to the security of the sensitive data is ansible-vault which has some serious design issues that would never be solvable by that module. Security must be part of the code ansible approach.

First problem is that you cannot search inside ansible-vaults, so if you are trying to find out where a variable is used you will search the entire repository and not find the vault file because, well is encrypted.

2nd problem is that you cannot really use SCM (like git) to merge vault files.

3rd problem is that you cannot use different vaults.

Have a look at Travis and the way they solved the management of sensitive information, they encrypt only the value, you can encrypt any value, anywhere. 

Because Ansible supports jinja2 this makes me think that we could probably implement this with the help of it. As a note, it would be wonderful if, while implementing this, we could also specify an optional secret key to use for decryption. This would allow us to encrypt different secrets with different keys, allowing us to give access to ansible on a finer grade: some people could get only the decryption keys for staging but not the ones for production.

Reference: https://docs.travis-ci.com/user/encryption-keys/

**Comment by steveholden** [comment]
+1 - seems sensible to give the server a key pair, allowing all devs to encrypt information which can thereafter only be decrypted by the server. The Travis approach appears to work well (from the documentation - I don't have practical experience with it). being able to put encrypted credentials in build configuration files safely would be a real boon.

**Comment by abadger** [comment]
/cc @bcoca 

bcoca is Looking at several vault improvements for 2.2.  The notes I have say that there's a PR already open for something that sounds a lot like this but I wasn't able to find it.  Might be something to talk to bccoa about on IRC (we're in #ansible-devel on irc.freenode.net) once the 2.2 roadmap is sent ot the mailing list.

**Comment by bcoca** [comment]
this request #14721 would probably solve 1 and 2
for disclosure issues this one #14646

this one has the most likely path to solve all of the above #13287

**Comment by alikins** [comment]
@ssbarnea  @steveholden  Take a look at the pr at https://github.com/ansible/ansible/pull/16274

Looking for feedback on the changes proposed there.

**Comment by bcoca** [comment]
closing this via merged #16274
