### ISSUE TITLE
When always: is present, task failures do not abort the playbook (and are not reported as failures in the play).

### ISSUE THREAD

**Issue by larsks** [ansible/ansible#15625]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION
- ansible 2.0.1.0
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The description of the `always:` directive for blocks makes it sound
an awful lot like the `finally:` keyword in Python, but there is one
critical difference: the `always:` keyword appears to eat failures.
##### STEPS TO REPRODUCE

Given the following playbook:

```
- hosts: localhost
  gather_facts: false
  tasks:
    - block:

        - fail:
            msg: "Alas, I fail!"

      always:

        - debug:
            msg: "Perform some cleanup actions here."

    - debug:
        msg: "At end of first play."

- hosts: localhost
  gather_facts: false
  tasks:

    - debug:
        msg: "This should't execute because the host failed."
```

The output is:

```
PLAY [localhost] ***************************************************************

TASK [fail] ********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Alas, I fail!"}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "Perform some cleanup actions here."
}

PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "This should not execute because the host failed."
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

It aborted the play (the "At end of first play" task never runs), but
the host is marked `ok` rather than `failed`.  This means that the
subsequent play executes, even though the target host has failed.
##### EXPECTED RESULTS

I would expect the content of the `always:` block to execute, and then
for any failures from the main body of the block to propagate upwards.
That is, I expected behavior like this:

```
- hosts: localhost
  gather_facts: false
  tasks:
    - block:

        - fail:
            msg: "Alas, I fail!"

      rescue:

        - set_fact:
            there_was_a_failure: true

      always:

        - debug:
            msg: "Perform some cleanup actions here."


        - fail:
          when: there_was_a_failure|default('false')

    - debug:
        msg: "At end of first play."
```
##### ACTUAL RESULTS

Ansible ate the failure and merrily continued to execute other plays.

It's not clear to me if this behavior is intended, in which case we
need a documentation update, or if this is a bug.  In particular, the
fact that the _play_ aborts without marking the host has failed seems
to be a clear problem.

**Comment by bcoca** [comment]
cc @jimi-c

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by larsks** [comment]
LGTM!
