### ISSUE TITLE
Ansible extra-vars "equal" syntax broken for false boolean

### ISSUE THREAD

**Issue by trentondyck** [ansible/ansible#15636]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### OS / ENVIRONMENT

```
CentOS release 6.4 (Final)
```
##### SUMMARY

Ansible extra-vars "equal" syntax broken for false boolean
##### STEPS TO REPRODUCE

test.yml

```
 - hosts: localhost
   vars:
     haproxy: false
   tasks:
    - debug: msg="haproxy true - {{haproxy}}"
      when: haproxy
    - debug: msg="haproxy false - {{haproxy}}"
      when: not haproxy
```

works:

```
ansible-playbook test.yml --extra-vars "{'haproxy':true}";
ansible-playbook test.yml --extra-vars "{'haproxy':false}";
ansible-playbook test.yml --extra-vars "haproxy=true";
```

doesn't work:

```
ansible-playbook test.yml --extra-vars "haproxy=false";
```

##### EXPECTED RESULTS

```
TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "haproxy false - False"
}
```
##### ACTUAL RESULTS

```
TASK [debug] *******************************************************************
skipping: [localhost]
```

**Comment by sivel** [comment]
This is expected.  When using key=value syntax the value is always treated as a string.  Due to jinja2 being implemented in Python, a string value of `"false"` is a truthy value.

You can make use of the `|bool` filter to have Ansible/jinja2 evaluate the string false as a Boolean false value such as:

```
when: not haproxy|bool
```

**Comment by trentondyck** [comment]
if it were true then I would see this

```
TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "haproxy false - true"
}
```

but it skips the task due to haproxy not evaluating to true or false...

**Comment by trentondyck** [comment]
Did you try all four cases? It doesn't make sense no matter what language you're using.  Takes two minutes to repro all four of these.
