### ISSUE TITLE
ansible-playbook  -c local playbook.yml runs playbook remotely

### ISSUE THREAD

**Issue by viper233** [ansible/ansible#1564]
When running ansible-playbook -c local on a host included in the workstation group, the playbook is run on all workstation hosts

The playbook

<pre>

---
- hosts: workstations

  user: root

  tasks:
  - name: ensure openmpi is installed
    action: yum pkg=openmpi.x86_64 state=installed

  - name: write the openmpi config file
    action: copy src=files/etc_ld.so.conf.d_openmpi.conf dest=/etc/ld.so.conf.d/openmpi.conf
            owner=root group=root mode=0644
    notify:
    - run ldconfig

  handlers:
    - name: run ldconfig
      action: command /sbin/ldconfig
</pre>

My inventory file

<pre>
[workstations]
worker1
worker2
worker3
worker4
worker5
worker6
</pre>

I'm testing this functionality before I put it into a kickstart file. I'm trying to run this playbook locally on worker1 but it's running on all hosts in the workstation group.

ansible-playbook -c local client-setup.yml

https://groups.google.com/d/msg/ansible-project/8jQAoI0DzzY/wjJBNcznpzYJ
I'm running ansible built on centos 5 following the link about instructions. I will be installing centos 5 hosts.

**Comment by mpdehaan** [comment]
Yeah,  don't do that :)

This makes more sense through ansible-pull

**Comment by sfromm** [comment]
I would consider this analogous to running a playbook against an arbitrary group where some are unreachable.  In this case, only one should be reachable via the local connection method.

**Comment by sfromm** [comment]
A little more testing on my side and it appears ansible is running the tasks only on the localhost, but N times where N is the number of hosts in the group.

A test playbook:

```
---
- hosts: workstations
  tasks:
    - action: command uname
```

And then run the playbook:

```
$  ansible-playbook -c local  test-local.yml

PLAY [workstations] *********************

GATHERING FACTS *********************
ok: [testa]
ok: [testb]

TASK: [command uname] *********************
changed: [testb]
changed: [testa]

PLAY RECAP *********************
testa                 : ok=2    changed=1    unreachable=0    failed=0  
testb                  : ok=2    changed=1    unreachable=0    failed=0
```

Examining syslog on both hosts:

```
Nov  8 09:25:41 testa ansible-command: Invoked with args=uname shell=False chdir=None
Nov  8 09:25:41 testa ansible-command: Invoked with args=uname shell=False chdir=None
```

Nothing from host testb.

It appears ansible is doing the right thing, but needs to report back better what it is doing.

**Comment by viper233** [comment]
The local logs, doesn't seem to be running the playbook remotely

<pre>
centos5-test ansible-yum: Invoked with name=openmpi.x86_64 list=None conf_file=None state=installed disablerepo=None pkg=openmpi.x86_64 enablerepo=None 
Nov  8 09:35:24 centos5-test last message repeated 9 times
Nov  8 09:36:26 centos5-test last message repeated 22 times
Nov  8 09:37:31 centos5-test last message repeated 20 times
Nov  8 09:38:36 centos5-test last message repeated 20 times
Nov  8 09:39:43 centos5-test last message repeated 21 times
Nov  8 09:40:47 centos5-test last message repeated 20 times
Nov  8 09:41:52 centos5-test last message repeated 21 times
</pre>

This is inconvenient behavior for groups with many hosts.

**Comment by mpdehaan** [comment]
It's not meant to be used in this fashion.

Simply don't do that :)

**Comment by mpdehaan** [comment]
It seems you want

ansible-playbook -c local --limit hostname foo.yml

**Comment by sfromm** [comment]
What if $HOSTNAME is the unqualified name and the fqdn is in the inventory?  The potential mismatch would easily lead to confusion about why it doesn't work.

I don't see how this is different from any other connection type where some target hosts are not reachable via that connection type.  What if you specify connection _fancyschmancy_ and only some of those hosts are reachable via that connection type?  I'd expect ansible-playbook to run on those that it can and report which ones are not reachable.  Same for local.  I think ansible should report those that it couldn't reach via _local_ and run normally on the one host it can.

**Comment by viper233** [comment]
What about ansible-pull though? 

<pre>
cmd = 'ansible-playbook -c local %s' % playbook
</pre>

that's how it's run. Running ansible-pull trying to specify a hostname or fqdn name for --limit could be quite tricky, especially at the end of a kickstart

**Comment by sfromm** [comment]
I can update ansible-pull to call ansible-playbook with --limit.  However, I'd much rather see behavior as I described above.

**Comment by mpdehaan** [comment]
From IRC discussion, let's just add the following to limit to ansible-pull

```
--limit localhost,<FQDN>,127.0.0.1
```

I think that was the proposed addition

Ansible obviously does not know which hosts are really the remote ones.

**Comment by mpdehaan** [comment]
Ansible pull now adds --limit, so closing this, thanks @sfromm

**Comment by Wolfium** [comment]
I was trying to acomplish this for a combined pull/push mode.
I need to pull (from git) from a machine inside the production environment network and wanted then to push to machine in that local network.
Mainly I don't want all production machine to have ansible installed and I wanted to simply reuse my already created push approach playbook.

Any feedback / ideas will be apreciatted.
