### ISSUE TITLE
Omit "^ok: " lines in ansible-playbook output

### ISSUE THREAD

**Issue by olfway** [ansible/ansible#15653]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.1.0.0 (stable-2.1 3c42724d96) last updated 2016/04/28 18:43:40 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 6498f6e4d0) last updated 2016/04/28 18:43:41 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 5747418146) last updated 2016/04/28 18:43:41 (GMT +300)
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Where is a lot of 'ok: ' lines in ansible-playbook output, but often you need only changed/failed lines and diff output
##### EXPECTED RESULTS

'ok: ' lines omitted

**Comment by bcoca** [comment]
Already done, via 'actionable' plugin which only displays changed/failed.
