### ISSUE TITLE
No need the output for ok, skipping tasks.

### ISSUE THREAD

**Issue by ozbillwang** [ansible/ansible#15661]
##### ISSUE TYPE

- Feature Idea
##### ANSIBLE VERSION

```
any versions
```
##### CONFIGURATION

any setting
##### OS / ENVIRONMENT

any
##### SUMMARY

We have long list tasks to deploy an instance, the ansible-playbook output has too many logs mix with  ok and skipping tasks. 

Can we have an option to disable these messages? I only need the output for changed, error, or warning, etc.
##### STEPS TO REPRODUCE

```
run any ansible-playbook. 
```
##### EXPECTED RESULTS

Can we have an option to disable these messages? I only need the output for changed, error, or warning, etc. But not `ok` and `skipping` tasks.
##### ACTUAL RESULTS

```
output status for all tasks. 
```

**Comment by xox2** [comment]
`actionable` callback is no good?

#15622:

> - actionable: only shows when things are changed or fail

**Comment by ozbillwang** [comment]
Thanks, @toromoti 

From its document: http://docs.ansible.com/ansible/developing_plugins.html#examples

https://github.com/ansible/ansible/tree/devel/lib/ansible/plugins/callback

I didn't see any samples on how to use this plugin. Can you show me some samples? Thanks.

**Comment by xox2** [comment]
sorry, I also have never used it....

but, maybe, you can use it in `ansible.cfg`:

```
stdout_callback = actionable
```

http://docs.ansible.com/ansible/intro_configuration.html#stdout-callback

**Comment by bcoca** [comment]
closing as 'done'

**Comment by ozbillwang** [comment]
@bcoca 

I understand the function has been 'done', but could you please give some instruction about how to use it? 

There are no examples in https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/callback/actionable.py, and the related documents are simple.

**Comment by bcoca** [comment]
in ansible.cfg,

`stdout_callback=actionable`

**Comment by ozbillwang** [comment]
Thanks @bcoca & @toromoti . Suppose I copied `actionable.py` to local `plugin` folder.

```
callback_plugins = plugins
stdout_callback = actionable
```

When run ansible-playbook, shouldn't add any debug options, such as `-vvv`.

**Comment by KostyaEsmukov** [comment]
`stdout_callback = actionable` is marked as deprecated in [the docs](https://docs.ansible.com/ansible/latest/plugins/callback/actionable.html).

Apparently the current way of doing this is the following ansible.cfg snippet:
```
[defaults]
display_ok_hosts = no
display_skipped_hosts = no
```

This also allows to use a different `stdout_callback`, such as `yaml`, which expands newlines in the output (e.g. stdout/stderr) to a human-readable text.

```
stdout_callback = yaml
```
