### ISSUE TITLE
--ask-pass reverts to paramiko without checking for sshpass or notice of reason.

### ISSUE THREAD

**Issue by jessegit** [ansible/ansible#15667]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 4d9648dc15) last updated 2016/04/29 17:41:32 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 609d4cf84b) last updated 2016/04/19 17:14:35 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 1aecfc1e19) last updated 2016/04/19 17:14:40 (GMT +300)
  config file = /.../ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

nothing
##### OS / ENVIRONMENT

OSX 10.9.5 (probably all *nix), remote not relevant
##### SUMMARY

--ask-pass reverts to paramiko without checking for sshpass and/ornotice of the reason. See #10803 for other reports due to the confusion.
##### STEPS TO REPRODUCE

setup:
paramiko doesn't know the remote host key, system ssh does. Remote host doesn't have authorized_keys. It doesn't seem to matter if sshpass is installed or not. Any playbook will do, as the problem is to do with ssh/paramiko/sshpass.

```
ansible-playbook -v --step -i testing.ini testing.yml
```

->

```
UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
```

(should probably be more descriptive, the host is not unreachable but login failed)

```
ansible-playbook -k -v --step -i testing.ini testing.yml
```

->

```
paramiko: The authenticity of host 'testing' can't be established.
```

We're suddenly using paramiko, but I didn't ask for it. Same happens with sshpass installed.

```
ansible-playbook -k -v -c ssh --step -i testing.ini testing.yml
```

->

```
FAILED! => {"failed": true, "msg": "to use the 'ssh' connection type with passwords, you must install the sshpass program"}
```

Finally we know what we are missing. Install sshpass and repeat the third invocation (doesn't work with the second one like one would expect).
##### EXPECTED RESULTS

The second invocation should check and note that lack of sshpass has forced '--ask-pass' fall back to paramiko (or alternatively, fail unless '-c paramiko' is provided). If sshpass has been found, it should be used with the system ssh instead of forcing the user to provide '-c ssh'.

**Comment by sivel** [comment]
This is expected on Mac OS X.  There are known cases where `sshpass` causes Mac OS X to kernel panic, and as such, the default transport of `smart` on Mac, checks to see if you are doing password auth, and switches to using paramiko.

If you are using sshpass on Mac and are comfortable with the potential of a kernel panic, you can use `-c ssh` or set `transport = ssh` in your ansible.cfg.

If you have further questions please stop by IRC or the mailing list:
- IRC: #ansible on irc.freenode.net
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by jmooo** [comment]
Maybe the ansible output could be more clear, how is anyone supposed to know this is going on unless they find this github issue?
