### ISSUE TITLE
EC2 spot requests do not cancel on spot_wait_timeout

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#15676]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.0.2
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When requesting a spot instance with a specific price point, if the request times out before the spot request is fulfilled, the spot request is left open forever and you will end up with unintended running instances
##### STEPS TO REPRODUCE

Create spot request below market value
Wait for spot_wait_timeout
See spot request still pending in EC2 console
##### EXPECTED RESULTS

When the spot request fails, the spot request in EC2 should be canceled rather then left pending
##### ACTUAL RESULTS

The spot request is left pending

**Comment by ghost** [comment]
FWIW, this has caused a few thousand extra dollars of EC2 billing as a large number of pending spot requests triggered all at once.

**Comment by alikins** [comment]
This sounds like the same issue as https://github.com/ansible/ansible-modules-core/issues/2057 

If it's the same issue, may be worth combining them.

**Comment by alikins** [comment]
https://github.com/ansible/ansible-modules-core/pull/2210 
and https://github.com/ansible/ansible-modules-core/issues/2140 appear related as well.

**Comment by alikins** [comment]
The ec2 spot_wait_timeout code is from ansible/ansible-modules-core, so I'm going to close this issue. ansible/ansible-modules-core#2057 should already have references here if you want to add any info to that issue.
