### ISSUE TITLE
case for ansible_distribution and ansible_os_family changes between 2.0.2 and 2.2.0

### ISSUE THREAD

**Issue by jladdjr** [ansible/ansible#15671]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

Old version:

```
ansible 2.0.2.0
  config file = /Users/jladd/.ansible.cfg
  configured module search path = Default w/o overrides
```

New version:

The version below comes from repo `git@github.com:/abadger/ansible.git`, branch `ziploader-namespace`. I used this repo to get a fix for https://github.com/ansible/ansible/pull/15656. The version on this branch shows up as 2.2.0. 

```
ansible 2.2.0 (ziploader-namespace 487e6562ca) last updated 2016/04/29 12:01:05 (GMT -400)
  lib/ansible/modules/core: (detached HEAD e78ee3b128) last updated 2016/04/28 21:43:44 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD ca310f3d15) last updated 2016/04/28 21:43:49 (GMT -400)
  config file = /Users/jladd/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[ssh_connection]
control_path = %(directory)s/%%h-%%r
```
##### OS / ENVIRONMENT

Control host is Mac OS X 10.11.4 (Don't think that part is relevant)
Only target machine I've tested this with is RHEL 7.2
##### SUMMARY

The case for two ansible facts - `ansible_distribution` and `ansible_os_family` - has changed between 2.0.2 and 2.2.0. 

On 2.0.2:
- ansible_distribution: `RedHat`
- ansible_os_family: `RedHat`

On 2.2.0:
- ansible_distribution: `Redhat`
- ansible_os_family: `Redhat`

_Potential Impact:_

Users who have templates with conditionals like:

`{% if ansible_distribution in ['RedHat','CentOS'] and .. %}`

..will find that the above condition which was true in 2.0.2, is no longer true in 2.2.0 because of the case change.
##### STEPS TO REPRODUCE
1. Deployed a RHEL 7.2 instance in ec2.
2. Create an inventory file for the instance:
   `
   ec2-54-92-144-48.compute-1.amazonaws.com ansible_ssh_user=ec2-user
   `
3. With Ansible 2.0.2, run: 
   - `ansible -i playbooks/inventory.log -m setup ec2-54-224-165-31.compute-1.amazonaws.com > facts_2.0.2.txt`
4. With Ansible 2.2.0, run:
   -  `ansible -i playbooks/inventory.log -m setup ec2-54-224-165-31.compute-1.amazonaws.com > facts_2.2.0.txt`
5. Compare two results:
   - `diff -u facts_2.0.2.txt facts_2.2.0.txt`
##### EXPECTED RESULTS

Expect diff to only show trivial differences (e.g. change in date/time, etc).
##### ACTUAL RESULTS

The case for two ansible facts - `ansible_distribution` and `ansible_os_family` - has changed. See Summary section for details.
- Full diff of facts available [here](https://gist.github.com/jladdjr/8f35202b2bd91e0e17796f1272b90023)

**Comment by abadger** [comment]
@robinro -- do you think this might be caused by the facts refactor?

**Comment by jladdjr** [comment]
Checked on 2.1.0 branch - not seeing issue there:

```
ansible --version
ansible 2.1.0 (stable-2.1 1e5708514b) last updated 2016/04/29 14:21:35 (GMT -400)
  lib/ansible/modules/core: (detached HEAD babb97e473) last updated 2016/04/29 11:53:28 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD c8e69456ba) last updated 2016/04/29 11:53:28 (GMT -400)
  config file = /Users/jladd/.ansible.cfg
  configured module search path = Default w/o overrides

ansible all -i inventory -m setup | grep -i red
        "ansible_distribution": "RedHat",
        "ansible_os_family": "RedHat",
```

**Comment by robinro** [comment]
Yes, this is because of the refactor. The fix is already there, including tests for {centos,rhel}{6,7}: https://github.com/ansible/ansible/pull/15663
