### ISSUE TITLE
include: Ansible 2.1 breaks 2.0 compatibility

### ISSUE THREAD

**Issue by mmatuska** [ansible/ansible#15687]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

ansible 2.1.0.0
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Changes to include code break compatibility with Ansible 2.0
In Ansible 2.0 all includes have been treated as dynamic, so it was possible to skip large code paths by not processing any sub-tasks and their descendands.

Since commit 2c20579a06925a16abb95798237b97ce4987173d if the include filename string does not contain variables or the include command does not contain loops, all includes are FORCIBLY treated as static. This breaks compatibility with Ansible 2.0 playbooks and users have no way to workaround - the "static: no" keyword does not work as it is ignored.
##### EXPECTED RESULTS

Skipped includes should not be processed at all.
##### ACTUAL RESULTS

Almost all includes are treated as static.

**Comment by rawbertp** [comment]
It says somewhere that this was cherry-picked to stable-2.1 but I cannot find this commit ( 438ed70a4373f1035ae90a042bc745791b40fa76) in the stable-2.1 branch.

Actually, we're  still encountering this very issue in stable-2.1 as well as in 2.1.1.0-1. 

Even though "task_includes_static = 0" is set in the ansible.cfg task includes are treated as static unless the name contains a variable or "static: false" is explicitly used at task-level.

**Comment by jimi-c** [comment]
This will be included in 2.1.2.

**Comment by rawbertp** [comment]
Note that the above mentioned commit is not in ansible-2.1.2.0-1!?
