### ISSUE TITLE
Inventory group_vars issue with shared hosts

### ISSUE THREAD

**Issue by corretge** [ansible/ansible#15707]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.0.2
```
##### CONFIGURATION

```
[defaults]
inventory           =   staging-inventory.py
host_key_checking   =   False
```
##### OS / ENVIRONMENT

Ansible installed with Homebrew on Mac OSX 10.11.4 (15E65)
##### SUMMARY

I'm using group_vars with inventory. When I have two groups with same servers, because we share projects, group_var are wrong, I get always the value of last processed variable.
##### STEPS TO REPRODUCE

staging-inventory.py returns something like:

```
{
   "extrapat": {
        "hosts": [
            "172.16.3.73",
            "172.16.3.74"
        ],
        "vars": {
            "ansistrano_git_branch": "develop",
            "node_env": "staging",
            "wanup_group": "bb",
            "wanup_project": "extrapat"
        }
    },
    "webpat": {
        "hosts": [
            "172.16.3.73",
            "172.16.3.74"
        ],
        "vars": {
            "ansistrano_git_branch": "develop",
            "node_env": "staging",
            "wanup_group": "bc",
            "wanup_project": "webpat"
        }
    }
}
```

We can reproduce it without playbook, executing:

```
ansible extrapat -a "echo {{ wanup_project }}"
172.16.3.74 | SUCCESS | rc=0 >>
extrapat

172.16.3.73 | SUCCESS | rc=0 >>
extrapat
```

It's OK, but

```
ansible webpat -a "echo {{ wanup_project }}"
172.16.3.73 | SUCCESS | rc=0 >>
extrapat

172.16.3.74 | SUCCESS | rc=0 >>
extrapat
```
##### EXPECTED RESULTS

```
ansible webpat -a "echo {{ wanup_project }}"
172.16.3.73 | SUCCESS | rc=0 >>
webpat

172.16.3.74 | SUCCESS | rc=0 >>
webpat
```
##### ACTUAL RESULTS

```
ansible webpat -a "echo {{ wanup_project }}"
172.16.3.73 | SUCCESS | rc=0 >>
extrapat

172.16.3.74 | SUCCESS | rc=0 >>
extrapat
```

**Comment by sivel** [comment]
This is expected.  `group_vars` are not only processed/loaded based on what hosts/groups you are targeting.  Group vars are merged down to the hosts for all groups the host is in.  So if you have the same var name in 2 groups, and the host in both groups, you will get the var that is evaluated last.  Which is what you are seeing.

If you have further questions please stop by IRC or the mailing list:
- IRC: #ansible on irc.freenode.net
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
