### ISSUE TITLE
SSH keys aren't checked against known_hosts when using networking modules

### ISSUE THREAD

**Issue by ogenstad** [ansible/ansible#15702]
##### ISSUE TYPE
- Feature Idea
- Security issue
##### ANSIBLE VERSION

```
2.1
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The shared module_util [shell.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/shell.py) which is used by the different network modules doesn't validate the ssh key on the target device.

``` Python
    def open(self, host, port=22, username=None, password=None,
            timeout=10, key_filename=None, pkey=None, look_for_keys=None,
            allow_agent=False):

        self.ssh = paramiko.SSHClient()
        self.ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
```

This works in a trusted environment but is a security issue when connecting through a public network.

By default it would be good if system known hosts and user known hosts are loaded. Then it's up for debate regarding what should happen by default if it should use autoadd or autoreject.

Another question to ask is how to handle the situation when a user needs to confirm a new or changed ssh key. Probably the module should fail and insert information about the keys (new or changed) to a variable which is available through Ansible.

Perhaps a new parameter common among modules called something like key_policy with these options
- ignore - Ignore all ssh keys (like the current module)
- strict - Reject unknown or changed keys
- loose - Auto add unknown keys fail on changed keys

**Comment by Qalthos** [comment]
This should be complete with #15736.
