### ISSUE TITLE
local_tmp is ignored in ansible.cfg

### ISSUE THREAD

**Issue by aholbreich** [ansible/ansible#15719]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible-playbook 2.1.0 (devel e003ef93fc) last updated 2016/03/31 19:38:45 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 18367243e4) last updated 2016/03/31 19:38:51 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 3498cd2eae) last updated 2016/03/31 19:38:58 (GMT +200)
  config file = /home/alho/workspace_eclipse/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

project directory ansible.cfg

```
[defaults]
inventory       = hosts-dev
nocows = 1
local_tmp = /tmp/.ansible/tmp
```
##### OS / ENVIRONMENT

Linux LDME (Debian)
3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt7-1 (2015-03-01) x86_64 GNU/Linux
##### SUMMARY

While running Playbook

```
ansible-playbook monitoring.yml -K -b --become-method=su
```

local_tmp seem to be ignored and files are created in $USER_HOME$.ansible/tmp
##### EXPECTED RESULTS

 if local_tmp  is specified as  /tmp/ then temp files are created in that folder.
##### ACTUAL RESULTS

If local_tmp is set to new location in the project ansible.cfg, then it's ignored and standard tmp location is used.

**Comment by alikins** [comment]
> ansible-playbook 2.1.0 (devel e003ef93fc) last updated 2016/03/31 19:38:45 (GMT +200)

The 'local_tmp' config option was added after 2.1.0 in the commit 
dcc5dfdf811f24c3adbb879e77a1bf8789bf1738. Version 2.1.0 (devel e003ef93fc) 
does not support 'local_tmp'.

(It is referenced at http://docs.ansible.com/ansible/intro_configuration.html#local-tmp which is confusing since it those docs are generated from the latest versions. )

**Comment by alikins** [comment]
docsite/rst/intro_configuration.rst needs a 'added_in' note about local_tmp, that would help avoid confusion.

**Comment by aholbreich** [comment]
Ok, yes confusing... But thank you. Now i know...

**Comment by aholbreich** [comment]
> docsite/rst/intro_configuration.rst needs a 'added_in' note about local_tmp

I can try...

**Comment by alikins** [comment]
> I can try...

Don't worry about it, I'm updating the docs at the moment.

**Comment by aholbreich** [comment]
Ok! ;)

**Comment by abadger** [comment]
Closing this in favor of the Pull request #15730
