### ISSUE TITLE
re-enable apt_repository tests for ubuntu 16.04

### ISSUE THREAD

**Issue by robinro** [ansible/ansible#15718]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

devel, 2.2
##### OS / ENVIRONMENT

Ubuntu xenial 16.04
##### SUMMARY

The integration tests for test_apt_repository were disabled for Ubuntu Xenial 16.04 in #15561 to allow to run the tests. This is due to missing pages/repos for the new Ubuntu version. The tests should be re-enabled and this is a reminder to not forget that.

**Comment by resmo** [comment]
This is on my list but not top prio, if you like to work ion it, let me know.
