### ISSUE TITLE
Breaking change in relative path resolution between 2.0.1 and 2.0.2

### ISSUE THREAD

**Issue by avdv** [ansible/ansible#15724]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

CentOS Linux release 7.2.1511 (Core)
##### SUMMARY

In Ansible 2.0.1 the relative path is computed from the CWD. In Ansible 2.0.2 it is computed relative to the playbook.
##### STEPS TO REPRODUCE

```
    - synchronize:
        src: target/
        dest: "{{ ansible_user_dir }}/foo"
        rsync_opts:
          - "--stats"
          - "-h"
          - "--exclude=/conf/"
```

I'm running it with `ansible-playbook -i hosts ../../../playbooks/sync.yaml` in different subdirectories of a project. The playbooks are not part of the project (yet) and kept seperately.

```
|- root/
    |- playbooks/
       |- sync.yaml
    |- src/
       |- main/
          |- core/   # <== CWD
             |- target/
```
##### EXPECTED RESULTS

No change in behaviour between 2.0.1 and 2.0.2.
##### ACTUAL RESULTS

With Ansible 2.0.1, it works and syncs the files from `/root/src/main/core/target`. But with Ansible 2.0.2, it fails:

```
TASK [synchronize] *************************************************************
fatal: [rbxgemed01]: FAILED! => 
{
  "changed": false,
  "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh '/usr/bin/ssh  -S none -o StrictHostKeyChecking=no' --stats -h --exclude=/conf/ --out-format='<<CHANGED>>%i %n%L' \"/root/playbooks/target/\" \"user@10.0.0.1:/local/home/foo/\"",
  "failed": true,
  "msg": "rsync: change_dir \"/root/playbooks/target\" failed: No such file or directory (2)\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1052) [sender=3.0.9]\n",
  "rc": 23
}
```

**Comment by alikins** [comment]
Could ansible_user end different in these cases? ie, could one case end up running the task as a user vs root? 

Try adding a debug task that shows ansible_user_dir:

``
- name: debug ansible_user_dir
  debug: var=ansible_user_dir

```
```

**Comment by avdv** [comment]
> Could ansible_user end different in these cases? ie, could one case end up running the task as a user vs root?

No, the output was the same for both versions:

```
"ansible_user_dir": "/home/user"
```

**Comment by alikins** [comment]
Ah, indeed. And I misread ansible_user_dir as being used in the src, which was not the case. Sorry about that.

**Comment by avdv** [comment]
Forgot to mention, I'm working around using

```
src: {{ lookup('env', 'PWD') }}/target
```

**Comment by codyro** [comment]
We're seeing this same issue after upgrading to 2.0.2 breaking a large portion of our tasks. Is there any update on what change caused this change in behavior?

**Comment by tima** [comment]
duplicated_by https://github.com/ansible/ansible-modules-core/issues/3136

wontfix

**Comment by bcoca** [comment]
CWD was incorrect and a bug, the correct path should always be computed from playbook file as this is more predictable and not open to security issues like running from /tmp .
