### ISSUE TITLE
Add commandline option for showing documentation

### ISSUE THREAD

**Issue by tonk** [ansible/ansible#1572]
In Puppet the command

```
puppet describe --list
```

gives me a list of all available resources (in this version) and with

```
puppet describe <resource name>
```

I get the complete  description of this resource in Markdown to use in the Markdoc Wiki right away.

It would be very nice for Ansible to have something like that.  All the documentation is already in the modules, so something like

```
ansible -L
```

gives a list of all modules and a short description

```
ansible -L <modulename>
```

gives the complete module manual

If Michael doesn't want an extra commandline option, I would settle for an extra program, like `ansible-doc`.

**Comment by dhozac** [comment]
man ansible.MODULE already exists. module_formatter can also output markdown, or html, latex, rst, etc.

**Comment by tonk** [comment]
Agree that it does exist, but then I would need to know the name of the module. I want a quick overview of all available modules. And Ansible knows about those. After I have figured out what module I would need, a simple Ansible command would give me all options I can use.

**Comment by jpmens** [comment]
We discussed this yesterday, and I also think it's a good idea. I recall @mpdehaan saying he didn't want any more options, so maybe additional binary `ansible-doc` / `ansible-help` is preferred?

**Comment by tonk** [comment]
I recall reading that as well. I will settle for an extra command, like `ansible-doc` or `ansible-help`.

**Comment by mpdehaan** [comment]
I thought about this, but it seems redundant with the auto-built manpages.

Then again, I don't like manpages.  So +1.

Someone is welcome to make it happen, it needs to respect any configured module path per regular mainline ansible, and also take an optional module path argument.

@jpmens -- this also means we should move the minimal core (only) of the module formatter code into something like utils/module_docs.py so it can be shared between the build process and this.   Just the docstring parts.  

I recall someone else was using part of the docstring parser for something.

To be clear, I'm moving this into the 1.0 bucket and also not working on it, so if someone wants this to happen, make it happen.

**Comment by jpmens** [comment]
Ok, @tonk, you're welcome to continue now on this, if and when you like. :-)

The common get_docstring() stuff is now in ansible utils (if Michael takes it) and hacking/module_formatter.py shows how to invoke it.

**Comment by jpmens** [comment]
The get_docstring() stuff was also being used by bleader in the Vim snippets thing. I'm telling him now.

**Comment by tonk** [comment]
Thanks for the work. But this seems that this is the moment to learn Python

**Comment by mpdehaan** [comment]
closing this ticket but will totally include it if I get a pull request
