### ISSUE TITLE
Support AND for limits

### ISSUE THREAD

**Issue by skyzyx** [ansible/ansible#15760]
We are using dynamic tags for Google Cloud. Sometimes, hosts end up being covered by multiple matching tags.

I'm looking for functionality that will allow me to only match hosts which are a cross-section (AND) of two groups, instead of matching hosts that are from either group (OR) when passing group names to `--limit`.

**Comment by sivel** [comment]
This is discussed at http://docs.ansible.com/ansible/intro_patterns.html

> You can also specify the intersection of two groups. This would mean the hosts must be in the group webservers and the host must also be in the group staging:
> 
> webservers:&staging
