### ISSUE TITLE
Ansible Tower Install - /var

### ISSUE THREAD

**Issue by rmauc** [ansible/ansible#15779]
##### ISSUE TYPE

- Documentation Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /ansible/bin/ansible-tower-setup-2.4.5/ansible.cfg
  configured module search path = Default w/o overrides

```
##### OS / ENVIRONMENT

Installing Ansible Tower from and to RHEL7
-->
##### SUMMARY

Trying to install Ansible Tower for 30 day trial... I don't have 10G free in /var - but I will create a mount point with 10G - what should I mount? /var/???

Nice if this was updated here: http://docs.ansible.com/ansible-tower/latest/html/quickinstall/prepare.html
##### STEPS TO REPRODUCE

```
<!--- Paste example playbooks or commands between quotes -->
```

##### ACTUAL RESULTS

```
failed: [localhost] (item={u'uuid': u'9a9ba250-6016-47ce-831f-626c9d78fc3f', u'size_total': 3411787776, u'mount': u'/var', u'size_available': 2155651072, u'fstype': u'ext4', u'device': u'/dev/mapper/rhel-var', u'options': u'rw,relatime,data=ordered'}) => {"failed": true, "item": {"device": "/dev/mapper/rhel-var", "fstype": "ext4", "mount": "/var", "options": "rw,relatime,data=ordered", "size_available": 2155651072, "size_total": 3411787776, "uuid": "9a9ba250-6016-47ce-831f-626c9d78fc3f"}, "msg": "The file system mounted at /var does not meet minimum disk space requirement: 2155651072 < 10000000000"}

```

Thanks

**Comment by sivel** [comment]
For Tower issues please reach out to Ansible Tower support at https://support.ansible.com/ or support@ansible.com.

This project is for the open source ansible project, and not Tower.
