### ISSUE TITLE
Run plays against more then one required group

### ISSUE THREAD

**Issue by simlin-so4it** [ansible/ansible#15778]
##### ISSUE TYPE

Feature Idea
##### ANSIBLE VERSION

2.0.1.0
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I want to be able to run a play against a host that is part of two group and only when the host I part of both group. The background to this is that I'm writing a lot of different group with 6 different level of groups that most machines have to instance metadata in Openstack. And this metadata is limited to 255 characters. I need most combinations of these group level to get the script to work with mean that we rather fast exceeds this limit. The best solution to this problem would be if ansible allowed us to run plays against more then one group as requirement.

Example instances

Instance 1
grouptype1-a
grouptype2-a
grouptype3-a
grouptype4-a
grouptype5-a
grouptype6-a

Instance 2
grouptype1-a
grouptype2-a
grouptype3-b
grouptype4-b
grouptype5-b
grouptype6-b

Today if i want to run ansible against instances of grouptype1-a and grouptype2-a

I need to define the groups something like this.

Instance 1
grouptype1-a
grouptype2-a
grouptype1-a-grouptype2-a
grouptype3-a
grouptype4-a
grouptype5-a
grouptype6-a

Instance 2
grouptype1-a
grouptype2-a
grouptype1-a-grouptype2-a
grouptype3-b
grouptype4-b
grouptype5-b
grouptype6-b

And i need to do this for every combination i might use. It would be better if ansible just supported combining groups in plays.
## Example 1

```
- hosts: grouptype1-a AND grouptype2-a
```
## Example 2

```
- hosts: grouptype1-a AND grouptype2-a AND grouptype3-a
```
##### EXPECTED RESULTS

Run the play against host that are in all the required groups.

**Comment by bcoca** [comment]
You can already do this:

```
hosts: grouptype1-a:&grouptype2-a
```

http://docs.ansible.com/ansible/intro_patterns.html
