### ISSUE TITLE
Unable to install repo

### ISSUE THREAD

**Issue by jimmcl400** [ansible/ansible#15775]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
 2.0.1.0 
```
##### OS / ENVIRONMENT

Ansible running on Debian 8.
##### SUMMARY

Trying to deploy epel repo to different clients
##### STEPS TO REPRODUCE

```
 Code -
 roles:
    - { role: geerlingguy.repo-epel,  when: ansible_os_family == "RedHat" and ansible_distribution_major_version =="6" and ansible_userspace_bits =="64" } 
```

##### EXPECTED RESULTS

The repo should have installed but fails 
##### ACTUAL RESULTS

ok: [test] => {"cache_update_time": 0, "cache_updated": false, "changed": false, "invocation": {"module_args": {"cache_valid_time": null, "deb": null, "default_release": null, "dpkg_options": "force-confdef,force-confold", "force": false, "install_recommends": null, "package": ["nagios-nrpe-server", "nagios-nrpe-plugin"], "pkg": ["nagios-nrpe-server", "nagios-nrpe-plugin"], "purge": false, "state": "latest", "update_cache": false, "upgrade": null}, "module_name": "apt"}}

```
<!--- Paste verbatim command output between quotes -->
```

**Comment by alikins** [comment]
Note: I edited the original comment since most of it ended up inside html comments.

**Comment by alikins** [comment]
What was the command line invocation used?

The output posted appears to be from running a 'apt' task, so it's not clear how that is related to the epel role? This sounds like it may be best answered by the mailing list.
I'll add some info about the mailing lists.

**Comment by alikins** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
  
  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.
