### ISSUE TITLE
script that contains e.g. "||" via shell module keeps failing

### ISSUE THREAD

**Issue by jhutar** [ansible/ansible#15800]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

I have just private_key_file and host_key_checking configured.
##### OS / ENVIRONMENT

Red Hat Enterprise Linux 7 (fully updated)
ansible-2.0.1.0-2.el7.noarch from EPEL
##### SUMMARY

I'm getting negative return code from ''shell'' module when I'm executing script that contains e.g. "||".
##### STEPS TO REPRODUCE

I'm trying to run this playbook:

```
- hosts: all
  remote_user: root
  tasks:
    - shell:
        pgrep --full 'sleep' && pkill --full 'sleep' || true
```

but I'm getting:

```
# ansible-playbook -i aaa.ini aaa.yaml 

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [192.168.122.100]

TASK [command] *****************************************************************
fatal: [192.168.122.100]: FAILED! => {"changed": true, "cmd": "pgrep --full 'sleep' && pkill --full 'sleep' || true", "delta": "0:00:00.158772", "end": "2016-05-05 00:33:49.072139", "failed": true, "rc": -15, "start": "2016-05-05 00:33:48.913367", "stderr": "", "stdout": "385", "stdout_lines": ["385"], "warnings": []}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @aaa.retry

PLAY RECAP *********************************************************************
192.168.122.100               : ok=1    changed=0    unreachable=0    failed=1
```

When I run the command directly, it works:

```
host # ssh root@192.168.122.100
vm # pgrep --full 'sleep' && pkill --full 'sleep' || true
vm # echo $?
0
```
##### EXPECTED RESULTS

It should not fail
##### ACTUAL RESULTS

It keeps failing even when I add following to the playbook for that shell task:

  args:
    executable: "/bin/bash"

**Comment by jhutar** [comment]
Initially asked on http://stackoverflow.com/questions/37042643/ansible-shell-task-with-pgrep-keeps-failing-works-in-normal-shell

**Comment by dagwieers** [comment]
What is very apparent from your output is that the command returns -15.
Which means the process was terminated.

If I execute your command on localhost, I am actually killing my own ansible run.

```
[dag@moria ~]$ ansible localhost -m shell -a 'pgrep -f 'sleep' && pkill -f 'sleep' || true'
Terminated
```

So you are doing the same from a playbook, and are killing part of Ansible's processes, but not too many so it can properly report back some output and the return code. (I was actually killing the main calling process on my own system too !)

PS Why would you do a pgrep && pkill ? pkill performs a grep and will only kill the process that match your grep. I don't see any valid reason for doing this.

**Comment by jhutar** [comment]
> PS Why would you do a pgrep && pkill ? pkill performs a grep and will only kill the process that match your grep. I don't see any valid reason for doing this.

Mine intention here was always return true (only attempt to kill process if it is running). Running "pkill -f sleep || true" causes the failure as well. Anyway, thank you very much for your investigation and feel free to close this issue, as the pkill really kills some ansible processes (which matches the grep pattern):

```
$ ansible localhost -m shell -a "pgrep --list-full -f process_that_does_not_exists"
localhost | SUCCESS | rc=0 >>
828 /usr/bin/python /usr/bin/ansible localhost -m shell -a pgrep --list-full -f process_that_does_not_exists
835 /usr/bin/python /usr/bin/ansible localhost -m shell -a pgrep --list-full -f process_that_does_not_exists
836 /usr/bin/python /usr/bin/ansible localhost -m shell -a pgrep --list-full -f process_that_does_not_exists
```

**Comment by dagwieers** [comment]
@jhutar Point being that `pkill` has the same functionality as `pgrep`, except that it also kills. So doing `pgrep -f 'sleep' && pkill -f 'sleep'` is the same as `pkill -f 'sleep'`. (Making abstraction of the fact that pgrep and pkill in the first example run at a different time)

So there is no need to do it. And obviously it fails exactly in the same way because it kills the same Ansible processes.

@bcoca You can close this issue.

**Comment by jhutar** [comment]
@dagwieers Difference between `pgrep -f 'sleep' && pkill -f 'sleep'` and `pkill -f 'sleep'` is the exit code if there is no "sleep" process.

I fully agree with effect it have to Ansible processes.

Thank you again.

**Comment by utoddl** [comment]
Ansible's shell module runs the script as (or equivalent to)
```
bash -c "your-whole-script-as-one-quoted-string"
```
So if your script contains `pkill -f killpattern` it's going to match not only the process(es) you meant to kill but also the shell process running the pkill command -- i.e. the ansible step itself. 

To get around this, you need to do something like this:
```
for i in $(pgrep -f killpattern | grep -v $$) ; do kill $i ; done
```

**Comment by jhutar** [comment]
Thank you @utoddl. It makes a perfect sense to me now.
