### ISSUE TITLE
zypper module --verbose option causes zypper to error out on SLES 11sp3 and possibly 4. 

### ISSUE THREAD

**Issue by blutgens** [ansible/ansible#15806]
##### ISSUE TYPE
- Bug Report 

zypper.py
zypper module errors out when it calls zypper with --verbose 
##### ANSIBLE VERSION

tested with devel head today, stable-2.0, and stable-2.1 branches. 
ansible 2.1.0.0 (stable-2.1 6f99f40f37) last updated 2016/05/10 13:53:48 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 1f5cf669dd) last updated 2016/05/10 13:50:25 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 431591c2b4) last updated 2016/05/10 13:50:37 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

and 

ansible 2.0.2.0 (stable-2.0 c4388285fa) last updated 2016/05/10 13:54:47 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 1f5cf669dd) last updated 2016/05/10 13:50:25 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 431591c2b4) last updated 2016/05/10 13:50:37 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

and 
ansible 2.2.0 (devel 30decd5e0a) last updated 2016/05/10 13:50:13 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 1f5cf669dd) last updated 2016/05/10 13:50:25 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 431591c2b4) last updated 2016/05/10 13:50:37 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

egrep "(^\w+|^[)" /etc/ansible/ansible.cfg 
[defaults]
gathering = smart
host_key_checking = False
log_path = /var/log/ansible/${LOGNAME}-ansible.log
action_plugins     = /opt/ansible/lib/ansible/plugins/action
callback_plugins   = /opt/ansible/lib/ansible/plugins/callback
connection_plugins = /opt/ansible/lib/ansible/plugins/connection
lookup_plugins     = /opt/ansible/lib/ansible/plugins/lookup
vars_plugins       = /opt/ansible/lib/ansible/plugins/vars
filter_plugins     = /opt/ansible/lib/ansible/plugins/filter
test_plugins       = /opt/ansible/lib/ansible/plugins/test
nocows = 1
cow_selection = random
fact_caching = redis
fact_caching_timeout = 86400
retry_files_enabled = False
retry_files_save_path = ~/.ansible_retry/
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
pipelining = True
[accelerate]
[selinux]
##### OS / ENVIRONMENT

ansible server - SLES 11sp3 x86_64
ansible client SLES 11sp3 x86_64
##### SUMMARY

zypper errors out due to ansible passing --verbose option to 'zypper in <something'
ANSIBLESERVER:~ # ansible testbox01 -m zypper -a 'name=SUSE_SLES type=product state=present'
testbox01 | FAILED! => {
    "changed": false, 
    "cmd": [
        "/usr/bin/zypper", 
        "--quiet", 
        "--non-interactive", 
        "--xmlout", 
        "search", 
        "--type", 
        "product", 
        "--match-exact", 
        "--verbose", 
        "--installed-only", 
        "SUSE_SLES"
    ], 
    "failed": true, 
    "msg": "Zypper run command failed with return code 2.", 
    "rc": 2, 
    "stderr": "Unknown option '--verbose'\n", 
    "stdout": "<?xml version='1.0'?>\n<stream>\n</stream>\n", 
    "stdout_lines": [
        "<?xml version='1.0'?>", 
        "<stream>", 
        "</stream>"
    ]
}
ANSIBLESERVER:~ # 
##### STEPS TO REPRODUCE

Use the zypper module to install something, in my case it's a 'product', but it also fails on removals and installations of individual packages. 

If i remove '--verbose' from cmd.extend, it works perfectly. 

```
any calls to the zypper module, either ad-hoc or in playbook exhibit this issue. 
```

**Comment by blutgens** [comment]
```
diff --git a/zypper.py b/zypper.py
index 30d69aa..00abffc 100644
--- a/zypper.py
+++ b/zypper.py
@@ -140,7 +140,8 @@ def get_installed_state(m, packages):
     "get installed state of packages"

     cmd = get_cmd(m, 'search')
-    cmd.extend(['--match-exact', '--verbose', '--installed-only'])
+    # cmd.extend(['--match-exact', '--verbose', '--installed-only'])
+    cmd.extend(['--match-exact', '--installed-only'])
     cmd.extend(packages)
     return parse_zypper_xml(m, cmd, fail_not_found=False)[0]

```

This fixes it for me. It seems like that --verbose option should be fine. I'm not sure why it fails when zypper.py uses it.

**Comment by robinro** [comment]
@blutgens thanks for the report and proposed fix

The zypper module is part of the `ansible-modules-extras` repo, so please move your report over there. You can also open a pull-request for your fix.

Quick comment already: The motivation for `--verbose` was to get the version and repository information. The version is used for diff output and that would be broken by your change. Try to run `ansible-playbook --diff your_playbook.yml`.
The repo information is not yet used but I had in mind to add a `repository` option that would specify the repository from which a package should be installed.

Does `zypper search --detail` work on your system? It should have the same info.

**Comment by blutgens** [comment]
Moved to ansible-modules-extras: [#2218](https://github.com/ansible/ansible-modules-extras/issues/2218l)
