### ISSUE TITLE
Command keystone-manage db_sync keystone failed 

### ISSUE THREAD

**Issue by mickael-decastro** [ansible/ansible#15837]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
1.9.4
```
##### CONFIGURATION

no change
##### OS / ENVIRONMENT

Ansible server: Centos 6.7
Managed server: Centos 7
##### SUMMARY

When I try to run the command "/bin/sh -c "keystone-manage db_sync" keystone", I receive a failed output. The delta value is always arround 1 minute and 41 second. It is probably a timeout but I didn't found any information about it
##### STEPS TO REPRODUCE

```
- name: Populate the Identity service database
  command: /bin/sh -c "keystone-manage db_sync" keystone"
```
##### EXPECTED RESULTS

Return code 0, no errors 
##### ACTUAL RESULTS

The command failed

```failed: [srvoskhost04] => {"ansible_job_id": "757947683421.4527", "changed": true, "cmd": ["/bin/sh", "-c", "keystone-manage db_sync", "keystone"], "delta": "0:01:40.997913", "end": "2016-05-12 16:17:22.250444", "finished": 1, "rc": 1, "start": "2016-05-12 16:15:41.252531", "warnings": []}
<job 757947683421.4527> FAILED on srvoskhost04"

```
```

**Comment by jctanner** [comment]
@mickael-decastro can you provide the full -vvvv output for the task?

**Comment by mickael-decastro** [comment]
The problem was on the command. It is not a ansible problem.
