### ISSUE TITLE
No push support with docker module

### ISSUE THREAD

**Issue by cjw296** [ansible/ansible#15846]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

While the ansible docker module can build and pull, it cannot push.
Side question: does it require per-user state for the hub login details, or can it store that locally?
(thinking of different jobs on a jenkins server that will run concurrently, but need to be logged in to the docker registry with different users)
##### STEPS TO REPRODUCE

What we want is to have the following tasks in an application deployment playbook:
- build docker image
- run tests
- push docker image to registry

The last step doesn't currently appear to be possible.

**Comment by chouseknecht** [comment]
The new docker_image module in 2.1 can build, pull, push, tag, etc. We are scheduled to release 2.1RC2 today. You can also access it by [running from source](http://docs.ansible.com/ansible/intro_installation.html#running-from-source).

You may also want to check out the new [docker_service](https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker_service.py) module, which will consume docker's compose language.

If you can share more about your workflow and things you're trying to accomplish, I'd be happy to help and make sure we're delivering the right things. 

--Chris

**Comment by cjw296** [comment]
Is the dev/2.1 documentation build out anywhere online? It does sound like what we're after.
When's 2.1 due to be released?

`docker_service` does look very interesting. Where do the packages in https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker_service.py#L413 come from? The requirements for the module are a bit confusing: are they python packages or OS packages?

Our workflow is looking to have an ansible-driven build, test and deploy cycle run by a jenkins job.
Not sure whether we'll use separate playbooks or just tags in one playbook, but they idea is to have 4 separate stages:
- _build_, which does any compilation or similar (webpack, container builds, etc)
- _test_, which runs any test suites (unit, integration, etc)
- _release_, which will cut a tag in the git repo and push artifacts to registries (python packages to devpi, docker images to quay, etc)
- _deploy_, which will deploy the artifacts pushed in the _release_ step and do any required service orchestration.

So, for that third step, we need to be able to push the built images.

One wrinkle noticed from the docker cli tools: since we'll have multiple projects that publish to different indices in devpi and quay, we may well have multiple jenkins jobs running simultaneously that require different docker registry credentials, so the docker-cli limitation of using a user-wide set of cached credentials won't work for us. Hopefully the ansible module will not have that limitation!

**Comment by bcoca** [comment]
closing as this is provided by docker_image
