### ISSUE TITLE
default transport (smart) performance hit

### ISSUE THREAD

**Issue by colincoghill** [ansible/ansible#15844]
This is probably a tiny part of Issue #12239
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
```

also latest dev

```
2.2.0-0.git201605121902.ae09648.devel
```
##### CONFIGURATION

transport left to default, or set explicitly transport=smart
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When transport is "smart", ansible checks to see if it can use ControlPersist at the start of every single task before setting the type to "ssh". This causes a noticeable performance hit.

If you explicitly set it to "ssh" it does not do this.

It should probably test this once, at the start of the play, or during setup.
##### STEPS TO REPRODUCE

```
# ansible.cfg
[defaults]
# transport=smart
```

vs

```
#ansible.cfg
[defaults]
transport=ssh
```

(everything else default, no pipelining, etc)

simple playbook with 10 minimal tasks  "command: echo"
##### EXPECTED RESULTS

Ansible be really fast.
(with transport=ssh)

```
real    0m13.252s
user    0m1.646s
sys 0m1.606s
```
##### ACTUAL RESULTS

Ansible be really not fast.
(with transport=smart)

```
real    0m15.548s
user    0m1.992s
sys 0m1.878s
```

Ok, so it's only a few % increase, but it does help!

**Comment by colincoghill** [comment]
Easiest fix is update the docs to tell people to use transport=ssh if they can.

The code that does it is in lib/ansible/executor/task_executor.py  

```
                # see if SSH can support ControlPersist if not use paramiko
                try:
                    cmd = subprocess.Popen(['ssh','-o','ControlPersist'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                    (out, err) = cmd.communicate()
                    err = to_unicode(err)
```

I couldn't see easily how to make it only do this once, rather than on every connection.

**Comment by jctanner** [comment]
reassigning to @abadger
