### ISSUE TITLE
Rackspace inventory fails with SSL error on Centos7

### ISSUE THREAD

**Issue by matburt** [ansible/ansible#15854]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
# ansible --version
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

CentOS 7:

```
# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
```
##### SUMMARY

Running the rax.py inventory script with the latest pyrax and a valid configuration yields an SSL error:

```
# ./rax.py --list
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)
```

**Comment by sivel** [comment]
It sounds as though you do not have an up to date cacert bundle that enables you to handle validating the certificate for the Rackspace APIs.

If you wish to exclude cert verification, you should be able to utilize a `~/.pyrax.cfg` file to configure pyrax ssl handling such as:

```
[settings]
identity_type=rackspace
verify_ssl=False
```

**Comment by sivel** [comment]
Of note here.  I tested this on the docker `centos:7` image and SSL verification works without issue and the image has the most up to date `ca-certificates` OS package installed.

**Comment by matburt** [comment]
Disabling ssl is probably not something that we'll want to do.    This is the version of `ca-certificates` package installed:

```
# rpm -qa | grep ca-certificates
ca-certificates-2015.2.6-70.1.el7_2.noarch
```

**Comment by matburt** [comment]
backleveling certifi seems to work:

```
pip install -U certifi==2015.04.28
```

Seems like this issue on pyrax is somewhat related: https://github.com/rackspace/pyrax/issues/601

Though it's closed by the rackspace team it still seems to be an issue for some people.

**Comment by sivel** [comment]
Ok, this sounds like it is not an ansible issue, but potentially an issue with the cert on the Rackspace APIs.

That pyrax issue lists several resolutions including the fix you have mentioned, as well as installing the root thawte cacerts.

Going to ho ahead and close this out.

**Comment by jlaska** [comment]
@sivel the environment variable `CLOUD_VERIFY_SSL` should also allow us instruct pyrax to disable `verify_ssl`?

**Comment by sivel** [comment]
@jlaska that does appear to be the case looking at the source of pyrax.  I've never personally used that env var before, but it seems it should work.
