### ISSUE TITLE
[modules-core: file] Allow for "directory" or "link" in place of "file" with state 

### ISSUE THREAD

**Issue by svpace** [ansible/ansible#15864]
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

using "file" to check for directories (or links) is not very intuitive.
It would be great if 

```
directory: path=x/y/z
```

could be used as an alias for

```
file: path=x/y/z state=directory
```

**Comment by alikins** [comment]
This appears to be a submission about the 'file' module. That is a module in ansible-modules-core.

We would appreciate if you can submit this there (https://github.com/ansible/ansible-modules-core)
instead. (If we move it, the owner of the issue resets to ansible instead of you).

**Comment by svpace** [comment]
Moved ansible/ansible-modules-core#3669
