### ISSUE TITLE
run_once with strategy free

### ISSUE THREAD

**Issue by anshbikram** [ansible/ansible#15876]
##### ISSUE TYPE

- Bug Report
##### SUMMARY

ansible run_once executes the instruction once for the first host from hostfile. Hence when there are dependency of that task (with run_once task), if i am runnig playbook with strategy: free, it is resulting in error.
Reason: the run_once will run only for the first host (first host in hostfile), but in "strategy: free" as there is no host ordering, hence some task (those are depending upon the run_once task) are running for some hosts even before the run_once task is executed by the first host (first host in the hostfile).

**Comment by bcoca** [comment]
what 'resulting error'? can you provide a simple reproducible example?

**Comment by anshbikram** [comment]
In my setup, i was creating a ".buildinfo" file (with run_once, as the file must be created once), and then all other hosts would copy that pre-created file. This particular task was made run_once. According to run_once rule this task will only be run by host1 (first node mentioned in hostfile for the role). 

Now, when i opted for "strategy: free" i was getting error as 
`>[10.42.208.114] => (item=.buildinfo) => {"failed": true, "item": ".buildinfo", "msg": "could not find src=/home/ubuntu/workspace/cloudproject/src/infra/ansible/roles/common/files/.buildinfo"}`
 Then i got to know some host (say host2, host3) were running ahead of the host1. As host1 hasn't created the file ".buildinfo" hence host2 and host3 are resulting error.

I think the current behavior of run_once should be changed. 
run_once should allow any host reach the task first (anyone of host1, host2, host3, ...) should run the task and all  subsequent host should skip it, rather statically defining the task to be executed by the first host (host1) only.

**Comment by jimi-c** [comment]
The free strategy emits a warning (at least, as of 2.1) if run_once or a few other "lock-step" options are used:

<pre>
run_once = templar.template(task.run_once) or action and getattr(action, 'BYPASS_HOST_LOOP', False)
if run_once:
    if action and getattr(action, 'BYPASS_HOST_LOOP', False):
        raise AnsibleError("The '%s' module bypasses the host loop, which is currently not supported in the free strategy " \
                           "and would instead execute for every host in the inventory list." % task.action, obj=task._ds)
    else:
        display.warning("Using run_once with the free strategy is not currently supported. This task will still be " \
                        "executed for every host in the inventory list.")
</pre>

This is obviously not the best way to handle this, and we should probably document these when using the free strategy.

**Comment by anshbikram** [comment]
Is there any other workaround for this purpose or are you creating any patch anytime soon?

is it possible by using "register" somehow?

**Comment by jimi-c** [comment]
@AnshBikram not currently no, it's a limitation of the free strategy. It might be possible to figure out the first host to get to a `run_once` or similar task, but that will take some work in testing/etc. If this gets fixed, it would be in the 2.2 time frame at least.

**Comment by bcoca** [comment]
So the best way around this would be to create an intermediate play with 'linear' strategy that handles this task, the drawback is that it creates a 'sync point' for all hosts.

**Comment by anshbikram** [comment]
Anyways thanks for the help
