### ISSUE TITLE
can not run pip on python3 with `connection: local`

### ISSUE THREAD

**Issue by januswel** [ansible/ansible#15893]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

default
##### OS / ENVIRONMENT

Mac OS X version 10.11.4 (15E65)
##### SUMMARY

I can not run pip on python3 with `connection: local`
##### STEPS TO REPRODUCE

```
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: install pyenv-virtualenv
      homebrew:
        name=pyenv-virtualenv
        state=latest

    - stat: path=~/.zshrc
      register: zshrc

    - name: add settings to .zshrc for pyenv
      script: add-pyenv-initialization.sh ~/.zshrc
      register: zshrc_status
      when: zshrc.stat.exists == true
      changed_when: zshrc_status.rc == 0
      failed_when: false

    - name: install python3
      command: pyenv install 3.5.1
      register: python3_status
      changed_when: python3_status.stderr in 'already'
      failed_when: python3_status.stderr in 'already'

    - name: rehash python3
      command: pyenv rehash
      register: rehash_status
      changed_when: rehash_status.stdout != '' and rehash_status.stderr != ''

    - name: use python 3.5.1 in global
      command: pyenv global 3.5.1
      changed_when: false

    - name: create virtual environment for tensorflow
      command: pyenv virtualenv 3.5.1 example-env
      register: virtualenv_status
      changed_when: virtualenv_status.stderr in 'already'
      failed_when: virtualenv_status.stderr in 'already'

    - name: rehash virtual environment
      command: pyenv rehash
      register: rehash_status
      changed_when: rehash_status.stdout != '' and rehash_status.stderr != ''

    - name: change to virtual environment for tensorflow
      command: pyenv global example-env
      changed_when: false

    - name: show pip version
      command: pip -V
      register: pip_version

    - debug: var=pip_version.stdout
```
##### EXPECTED RESULTS

```
ok: [localhost] => {
    "pip_version.stdout": "pip 7.1.2 from /Users/janus/.pyenv/versions/3.5.1/envs/tensorflow/lib/python3.5/site-packages (python 3.5)"
}
```
##### ACTUAL RESULTS

```
ESTABLISH LOCAL CONNECTION FOR USER: janus
localhost EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1463465894.05-187070136216314 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1463465894.05-187070136216314 `" )'
localhost PUT /var/folders/tf/hhh8c5rn3rzby7gk39xqr1kr0000gn/T/tmptLZDFs TO /Users/janus/.ansible/tmp/ansible-tmp-1463465894.05-187070136216314/command
localhost EXEC /bin/sh -c 'LANG=ja_JP.UTF-8 LC_ALL=ja_JP.UTF-8 LC_MESSAGES=ja_JP.UTF-8 /usr/bin/python /Users/janus/.ansible/tmp/ansible-tmp-1463465894.05-187070136216314/command; rm -rf "/Users/janus/.ansible/tmp/ansible-tmp-1463465894.05-187070136216314/" > /dev/null 2>&1'
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["pip", "-V"], "delta": "0:00:00.403997", "end": "2016-05-17 15:18:14.547485", "failed": true, "invocation": {"module_args": {"_raw_params": "pip -V", "_uses_shell": false, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 1, "start": "2016-05-17 15:18:14.143488", "stderr": "Traceback (most recent call last):\n  File \"/Users/janus/.pyenv/versions/tensorflow/bin/pip\", line 7, in <module>\n    from pip import main\n  File \"/Users/janus/.pyenv/versions/3.5.1/envs/tensorflow/lib/python3.5/site-packages/pip/__init__.py\", line 15, in <module>\n    from pip.vcs import git, mercurial, subversion, bazaar  # noqa\n  File \"/Users/janus/.pyenv/versions/3.5.1/envs/tensorflow/lib/python3.5/site-packages/pip/vcs/subversion.py\", line 9, in <module>\n    from pip.index import Link\n  File \"/Users/janus/.pyenv/versions/3.5.1/envs/tensorflow/lib/python3.5/site-packages/pip/index.py\", line 30, in <module>\n    from pip.wheel import Wheel, wheel_ext\n  File \"/Users/janus/.pyenv/versions/3.5.1/envs/tensorflow/lib/python3.5/site-packages/pip/wheel.py\", line 6, in <module>\n    import compileall\n  File \"/Users/janus/.pyenv/versions/3.5.1/lib/python3.5/compileall.py\", line 20, in <module>\n    from concurrent.futures import ProcessPoolExecutor\n  File \"/usr/local/Cellar/ansible/2.0.2.0/libexec/vendor/lib/python2.7/site-packages/concurrent/futures/__init__.py\", line 8, in <module>\n    from concurrent.futures._base import (FIRST_COMPLETED,\n  File \"/usr/local/Cellar/ansible/2.0.2.0/libexec/vendor/lib/python2.7/site-packages/concurrent/futures/_base.py\", line 357\n    raise type(self._exception), self._exception, self._traceback\n                               ^\nSyntaxError: invalid syntax", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by abadger** [comment]
This looks like a user question rather than a problem in the ansible code.  I'll append information on contacting the mailing list and IRC channels to get help with that.

Preliminary thoughts, from the traceback you're getting, it looks like you're mixing python2 and python3 together via an unrelated directory.  Perhaps pyenv has a bug that isn't creating a clean enough environment to work within.

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by januswel** [comment]
@abadger 

>  it looks like you're mixing python2 and python3 together via an unrelated directory. Perhaps pyenv has a bug that isn't creating a clean enough environment to work within.

I can run `pip -V`, `pip install --upgrade <package-name>` and other command with python3 in the env "example-env" manually. Because I think the error is raised by Ansible.
In addition, some packages, for example "six", in python2 env can not install.

The traceback tells "/usr/local/Cellar/ansible/2.0.2.0/libexec/vendor/lib/python2.7/site-packages/concurrent/futures/**init**.py" causes an error.
This path is Ansible's one and written in python2. So python3 raise a SyantaxError.

I thought "Ansible allows pip with `connection: local`" by reading documents and searching issues, but not in fact. Your answer means "Ansible does not support python2/3 commands with `connection: local`" ? Then, write it in the public documents.

**Comment by sivel** [comment]
Based on the trace back I see that you have installed Ansible via homebrew.  There was a prior issue logged for this exact configuration.  https://github.com/ansible/ansible-modules-core/issues/3298

In that issue the problem only affected Ansible installed via homebrew.

Try uninstalling Ansible via homebrew and reinstalling via pip, and see if that resolves your issue.

Of note, installing Ansible via homebrew is unsupported, largely due to such issues.

**Comment by abadger** [comment]
> The traceback tells "/usr/local/Cellar/ansible/
> 2.0.2.0/libexec/vendor/lib/python2.7/site-packages/concurrent/futures/
> _init_.py" causes an error.
> This path is Ansible's one and written in python2. So python3 raise a
> SyantaxError.
> 
> That is not a file shipped by ansible.  It must be a product of how ansible
> is installed on your system rather than something in Ansible itself.

**Comment by januswel** [comment]
@sivel 
Thank you for your reply.

> Try uninstalling Ansible via homebrew and reinstalling via pip, and see if that resolves your issue.
> Of note, installing Ansible via homebrew is unsupported, largely due to such issues.

I got it and try with pip installation!!

**Comment by januswel** [comment]
I succeeded to run pip with pip-installed Ansible.
Thank you!!
I will tweet this tips.
