### ISSUE TITLE
Test synchronize

### ISSUE THREAD

**Issue by abadger** [ansible/ansible#15905]
##### ISSUE TYPE
- Feature Request
##### SUMMARY

Synchronize is full of caveats and special cases.  Changing the code is likely to cause regressions.  Unittesting the code will help to keep us catch regressions before users see them.
##### Additional info

Here's some playbooks that show how the code is supposed to work and current limitations of it.  Can use these to figure out what the run() method returns given a certain set of input.  However, we probably won't be able to fully test this via unittests as  many of the tests depend on the configuration of the remote hosts rather than just giving the code inputs and expecting specific outputs from it.  we'll just have to see how far we can get:

https://gist.github.com/abadger/3b25f51bcc257785545385bae3d3aa75

**Comment by jctanner** [comment]
I believe the commit above covers the scenarios mentioned in @abadger's gist, but we can and will add more scenarios to the test fixtures as time goes on.
