### ISSUE TITLE
local_action is a misguided feature

### ISSUE THREAD

**Issue by 0xABAB** [ansible/ansible#15900]
`local_action` takes as a first argument a module argument, which conflates with the actual command. This is just misguided engineering. 

The proper solution is to introduce a named parameter named `module` which would then for example be set to `command`. 

Please strip commit rights of whoever introduced this misguided feature in the first place. If that happens to be the person who started the project, my comment would still stand (I never said Ansible was any good).

**Comment by 0xABAB** [comment]
Dear dictator sivel, 

Can you please consider to not be a dictator? 

Thanks

**Comment by bcoca** [comment]
You ALREADY have a `module` option to action/local_action, but it can be omitted and the module name passed as first parameter:

```
- action: module=copy ...
- action: copy ...
- copy: ...
```

are all equivalent

**Comment by 0xABAB** [comment]
@bcoca Great, where is this documented?

**Comment by MichaelBaydoun** [comment]
@0xABAB I would offer a few suggested options when you have a change you would like to see:
- Submit a pull request with the changed code, a great way to start a discussion on a feature.
- Fill out the complete issue template
- Submit a proposal https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md 
- Avoid confrontational language like "strip commit rights" or "I never said Ansible was any good".

**Comment by jimi-c** [comment]
@0xABAB for repeated abuse you are now blocked from the Ansible Organization.
