### ISSUE TITLE
Fetch module reporting FAILED on solaris 10

### ISSUE THREAD

**Issue by rrtj3** [ansible/ansible#1591]
Testing out the fetch module today against a solaris machine, and while it works, it's always reporting failed. I've narrowed it down to the remote md5sum always returning 'md5' string instead of an actual md5sum.

I plan to look into it but wanted to get the issue up to make it known.

**Comment by mpdehaan** [comment]
Which Solaris btw?

-- Michael

**Comment by rrtj3** [comment]
Solaris 10 (sparc) 

with:
bash-3.00# /opt/csw/bin/python -V
Python 2.6.8

and this set in the hosts file with the system:
ansible_python_interpreter=/opt/csw/bin/python

**Comment by rrtj3** [comment]
This is the relevant code in the **init**.py runner:

``` python
        md5s = [ 
            "(/usr/bin/md5sum %s 2>/dev/null)" % path,
            "(/sbin/md5sum -q %s 2>/dev/null)" % path,
            "(/usr/bin/digest -a md5 -v %s 2>/dev/null)" % path
        ]   

        cmd = " || ".join(md5s)
        cmd = "%s; %s || (echo \"${rc}  %s\")" % (test, cmd, path)
        data = self._low_level_exec_command(conn, cmd, tmp, sudoable=False)
        data2 = utils.last_non_blank_line(data)
        try:
            return data2.split()[0]
```

The digest command does work on solaris 10 but the problem is that we're grabbing the first item in the returned data. Here is the digest output though:

``` bash
bash-3.00# /usr/bin/digest -a md5 -v /etc/shadow 2>/dev/null
md5 (/etc/shadow) = 4485b089f66d9e293066a56f4f111880
```

For digest we should be grabbing the fourth item. 

I'll think about this a bit and figure out how we can determine which command gets called..... Thinking it might be better to test for the existence of the command instead of doing a chained '||' or. It should be easier to determine which command gets called that way.

Out of interest, why are we trying to do this outside of python? Python 2.4+ seems to have the md5 module by default.  It would seem cleaner to me to do it at that level.

**Comment by rrtj3** [comment]
I just submitted a pull request which fixes this issue for solaris 10 by removing the '-v' verbose option. Without that the md5 checksum is output as the first field, fixing the issue.

**Comment by mpdehaan** [comment]
Quick question seeing you have access to the platform.

So the "-v" ... why do you think it was there originally?   I'm wondering
if this ends up breaking something else, though likely the "-v" just
includes the filename and we don't care about that, right?

(I'm guessing the "-v" was originally added for BSD)

**Comment by rrtj3** [comment]
I'm thinking it was probably added originally to try to cover solaris. I just fired up a stock netbsd 6 and freebsd 9.1 VM and neither of them have the digest command. Also, neither of them have the md5sum command. They both use the md5 command to compute md5's. Though, of course, they have the binaries in different locations and use different options. (sigh) Anyway, I'll submit a pull request so our *BSD friends have some 'fetch' love as well.
