### ISSUE TITLE
/etc/ansible/group_vars/* not defined when using -i parameter

### ISSUE THREAD

**Issue by basdakkenhorst** [ansible/ansible#15935]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

[defaults]
host_key_checking=False
roles_path=<obfuscated>
##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.2 (Maipo)

Confirmed that this issue does not exist on FreeBSD (not tested by me though).
##### SUMMARY

Whenever a playbook is ran with the -i parameter to use a specific inventory file, variables defined in /etc/ansible/group_vars/all or in other files in /etc/ansible/group_vars/ are not defined unless the inventory file is placed in the /etc/ansible directory as well.
##### STEPS TO REPRODUCE

Playbook:

```
- hosts: test-host
  remote_user: ansible
  become: yes

  tasks:

  - name: Echo variable from /etc/ansible/group_vars/all
    debug: msg="{{ somevar }}"
```

inventory file:

```
[test-host]
<ansible managed host>
```

/etc/ansible/group_vars/all
`somevar: /etc/ansible/group_vars/all - test`

Not working:
`ansible-playbook -i /root/ansible/test.host /root/ansible/test-playbook.yml`

Working:
`ansible-playbook -i /etc/ansible/test.host /root/ansible/test-playbook.yml`
##### EXPECTED RESULTS

`ansible-playbook -i /root/ansible/test.host /root/ansible/test-playbook.yml`

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [<host>]

TASK [Echo variable from /etc/ansible/group_vars/all] **************************
ok: [<host>] => {
    "msg": "/etc/ansible/group_vars/all - test"
}

PLAY RECAP *********************************************************************
<host>                  : ok=2    changed=0    unreachable=0    failed=0
```
##### ACTUAL RESULTS

`ansible-playbook -i /root/ansible/test.host /root/ansible/test-playbook.yml`

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [<host>]

TASK [Echo variable from /etc/ansible/group_vars/all] **************************
fatal: [<host>]: FAILED! => {"failed": true, "msg": "ERROR! 'somevar' is undefined"}

PLAY RECAP *********************************************************************
<host>                  : ok=1    changed=0    unreachable=0    failed=1
```

However:

`ansible-playbook -i /etc/ansible/test.host /root/ansible/test-playbook.yml`
works fine:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [<host>]

TASK [Echo variable from /etc/ansible/group_vars/all] **************************
ok: [<host>] => {
    "msg": "/etc/ansible/group_vars/all - test"
}

PLAY RECAP *********************************************************************
<host>                  : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by bcoca** [comment]
This is expected, Ansible looks for (group/host)_vars in the directory where the inventory file is located, since the default location for inventory is /etc/ansible/hosts, these directories get pulled in when not using -i, but once you change the location of the inventory, those directories are not looked at.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
