### ISSUE TITLE
ansible galaxy command error: ERROR! Unexpected Exception: execv() arg 2 must contain only strings

### ISSUE THREAD

**Issue by ozbillwang** [ansible/ansible#15962]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.0.2.0
```
##### CONFIGURATION

[defaults]
inventory = ./inventory/hosts
host_key_checking = False
roles_path = roles.galaxy:roles
##### OS / ENVIRONMENT

Mac OS X EI Capitan
version 10.11.14
##### SUMMARY

get error when run ansible-galaxy command with version number `1.0`, but fine with commit number `65c8a4e35f7e59ff250c5cd5526ff752a2905cac`

```
ERROR! Unexpected Exception: execv() arg 2 must contain only strings
```
##### STEPS TO REPRODUCE

```
$ cat requirements.yml
# logrotate role
- src: https://github.com/retr0h/ansible-logrotate
  scm: git
  version: 1.0
  name: logrotate

$ ansible-galaxy install -r requirements.yml
ERROR! Unexpected Exception: execv() arg 2 must contain only strings
```

But I replace with commit number:

```
# logrotate role
- src: https://github.com/retr0h/ansible-logrotate
  scm: git
  version: 65c8a4e35f7e59ff250c5cd5526ff752a2905cac
  name: logrotate
```

The command runs fine.
##### EXPECTED RESULTS

download this galaxy role from github.
##### ACTUAL RESULTS

```
ERROR! Unexpected Exception: execv() arg 2 must contain only strings
```

**Comment by bcoca** [comment]
I run same with 2.1 file and get:

```
- extracting logrotate to /etc/ansible/roles/logrotate
- logrotate was installed successfully

```

So I'm going to close this as fixed

**Comment by jswinarton** [comment]
I'm also having the same issue, on a later version of Ansible:

```
$ ansible-galaxy install -r provisioning/requirements.yml -vvv
[...]
found role {'scm': 'git', 'src': 'https://github.com/jswinarton/hackbox-user', 'version': 0.2, 'name': 'hackbox-user'} in yaml file
Installing role hackbox-user
ERROR! Unexpected Exception: execv() arg 2 must contain only strings
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/2.1.1.0/libexec/bin/ansible-galaxy", line 92, in <module>
    exit_code = cli.run()
  File "/usr/local/Cellar/ansible/2.1.1.0/libexec/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 133, in run
    self.execute()
  File "/usr/local/Cellar/ansible/2.1.1.0/libexec/lib/python2.7/site-packages/ansible/cli/__init__.py", line 103, in execute
    fn()
  File "/usr/local/Cellar/ansible/2.1.1.0/libexec/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 385, in execute_install
    installed = role.install()
  File "/usr/local/Cellar/ansible/2.1.1.0/libexec/lib/python2.7/site-packages/ansible/galaxy/role.py", line 194, in install
    tmp_file = RoleRequirement.scm_archive_role(**self.spec)
  File "/usr/local/Cellar/ansible/2.1.1.0/libexec/lib/python2.7/site-packages/ansible/playbook/role/requirement.py", line 197, in scm_archive_role
    popen = subprocess.Popen(checkout_cmd, cwd=os.path.join(tempdir, name), stdout=devnull, stderr=devnull)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```

Compare with the output once I change the requirements file to use the hash of the commit, rather than the tag:

```
$ ansible-galaxy install -r provisioning/requirements.yml -vvv
[...]
found role {'scm': 'git', 'src': 'https://github.com/jswinarton/hackbox-user', 'version': 'b4f0fa01f5181f9716e24a4f0780462914c7df04', 'name': 'hackbox-user'} in yaml file
Installing role hackbox-user
- extracting hackbox-user to /usr/local/etc/ansible/roles/hackbox-user
- hackbox-user was installed successfully
```

I'm running Ansible on OS X 10.11.6, installed via Homebrew:

```
$ ansible --version
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides
```

**Comment by jswinarton** [comment]
@bcoca can we reopen this issue?

**Comment by lillesand** [comment]
In case this is useful for anyone: observed the same bug here in ansible 2.0.2.0. The tag `1.1` fails with the error given above, while the tag `1.1.0` works. It's the same revision, only differently named tags.

Could it be some kind of exotic string parsing bug?

**Comment by jswinarton** [comment]
@lillesand You're right—I'm getting the same issue. I did some digging and it turns out that this is expected YAML behaviour—`1.1` gets converted to a floating point value, whereas `1.1.0` is treated as a string. 

Here's an example YAML document I played with:

``` yaml
---
tag_one: 0.1.0
tag_two: 0.1
```

… and the corresponding output that PyYAML renders:

``` python
>>> import yaml
>>> with open('test.yml') as f:
...   y = yaml.load(f)
>>> y
{'tag_one': '0.1.0', 'tag_two': 0.1}
>>> type(y['tag_one'])
<type 'str'>
>>> type(y['tag_two'])
<type 'float'>
```

Not sure what the Ansible team's solution to this is—we should either explicitly quote version numbers that look like floats, or they should add an edge case that handles this problem explicitly. At the very least, some documentation or a more explicit error message would be useful.

**Comment by lillesand** [comment]
Ah, that makes sense. Good digging right there 👍 . 

Although it'd look a little nasty in the ansible code base, I think this is an edge case that should be handled. It's a kind of weird behaviour I don't want to handle as a user.

**Comment by jswinarton** [comment]
I think my vote would be for docs on this. I don't think ansible currently makes any changes to YAML behaviour, so changing something here would set a weird precedent. Plus, there's already a docs page on YAML gotchas (http://docs.ansible.com/ansible/YAMLSyntax.html#gotchas) which helps people fix common mistakes. I think an entry here on version numbers would be sufficient.

**Comment by jswinarton** [comment]
Added PR #17182, which calls this out in the docs.

**Comment by lillesand** [comment]
Fair point. I'd still argue that a better error message it's needed. The current one doesn't provide much help, and finding it the docs would require some digging.

I'd love to provide a PR, but I'm not very familiar with neither the ansible codebase nor Python.

**Comment by scottsb** [comment]
@bcoca Could this be reopened to fix as a bug? The earlier discussion here seemed to be considering modifying the general YAML parser to handle specially, and that was deemed a bad idea. I agree with that, but it seems like the right solution is to modify the actual `git` call to cast the version to a string.

**Comment by jswinarton** [comment]
I think that could have some strange edge cases. For example, consider if the version specified was `2.10`. If YAML read that as a float and was cast to string, you would end up with version `2.1` with no warnings or explanation.

**Comment by scottsb** [comment]
That's a very good point. I guess this is best as-is then.
