### ISSUE TITLE
why does stdout display the WARNING?  how to configure to avoid it?thanks

### ISSUE THREAD

**Issue by junneyang** [ansible/ansible#15989]
ansible 10.5.24.17 -m ping
![qq 20160525160627](https://cloud.githubusercontent.com/assets/6802322/15532489/aa64176a-2292-11e6-96eb-ab7cb6543fc9.png)

1、ansible --version
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

2、/etc/ansible/ansible.cfg
![qq 20160525160755](https://cloud.githubusercontent.com/assets/6802322/15532539/e1569ab8-2292-11e6-9941-69ba1f5f5a3f.png)

3、total ansible.cfg attach below:
[ansible.txt](https://github.com/ansible/ansible/files/281296/ansible.txt)

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
