### ISSUE TITLE
Regression: Ansible 2.2.0 won't pass variables to nested dependencies anymore

### ISSUE THREAD

**Issue by ThomasSteinbach** [ansible/ansible#15996]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
Commit 3b69ef7e8b34d736770aed8f2b31cfec522ed2d8
```
##### CONFIGURATION

Ansible from Source (since commit https://github.com/ansible/ansible/commit/33de7707c9027ace26ec62bff8f58717f4080538 ) and dependencies with pip
##### OS / ENVIRONMENT

Docker Image library/jenkins:1.651.1 with Ansible from Source

Also Ubuntu 16.04
##### SUMMARY

Ansible is confused by passing dictionaries through nested role dependencie calls. See steps to reproduce and expected/actual results for explanation.
##### STEPS TO REPRODUCE

The following files will demonstrate the bug and are also available for download at https://github.com/ThomasSteinbach/ansible_bug_15996

Playbooks `site.yml`:

```
roles:
  - role: testone
    onevar: onevarcontent
```

`testone/meta/main.yml`:

```
dependencies:
  - role: testtwo
    initial:
      ONE: "{{ onevar }}"
      TWO: zwei
```

`testtwo/meta/main.yml`:

```
dependencies:
  - role: testthree
    inside_var: "{{ initial.ONE }}"
```

`testthree/tasks/main.yml`:

```
- include: test.yml
```

`testthree/tasks/test.yml`

```
- debug: msg="everythingsfine"
  when: "{{ inside_var == 'onevarcontent' }}"
```
##### EXPECTED RESULTS

Ansible 2.0.2.0 installed with pip behaves like expected:

```
PLAY [this playbook is for testing purposes] ***********************************

TASK [testthree : include] *****************************************************
included: /home/uid1000/ansible/ansible_playbooks/test/roles/testthree/tasks/test.yml for localhost

TASK [testthree : debug] *******************************************************
ok: [localhost] => {
    "msg": "everythingsfine"
}
```
##### ACTUAL RESULTS

The latest Ansible version from source seems to be broken and leads to following result:

```
PLAY [this playbook is for testing purposes] ***********************************

TASK [testthree : include] *****************************************************
included: /var/jenkins_home/workspace/develop/xarifP/test/roles/testthree/tasks/test.yml for acia.vm

TASK [testthree : debug] *******************************************************
fatal: [acia.vm]: FAILED! => {"failed": true, "msg": "The conditional check '{{ inside_var == 'onevarcontent' }}' failed. The error was: error while evaluating conditional ({{ inside_var == 'onevarcontent' }}): {{ initial.ONE }}: 'initial' is undefined\n\nThe error appears to have been in '/var/jenkins_home/workspace/develop/xarifP/test/roles/testthree/tasks/test.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- debug: msg=\"everythingsfine\"\n  ^ here\n"}
```

**Comment by ThomasSteinbach** [comment]
Here you can checkout a Playbook demonstrating the error:

https://github.com/ThomasSteinbach/ansible_bug_15996

**Comment by jctanner** [comment]
@ThomasSteinbach The issue title states 2.2.0 but your description states 2.0.2.0 ... which one is correct?

**Comment by ThomasSteinbach** [comment]
I updated the description. The version affected by the bug is 2.2.0 or even more precise Ansible since the commit https://github.com/ansible/ansible/commit/33de7707c9027ace26ec62bff8f58717f4080538

**Comment by earlrob** [comment]
@ThomasSteinbach @jctanner I'm seeing this issue in the current ansible release v2.2.0 on ubuntu 14.04 via apt.
