### ISSUE TITLE
Per-task `environment` dictionary should override global one

### ISSUE THREAD

**Issue by nartamonov** [ansible/ansible#15990]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible-playbook 2.2.0 (devel d08fda9320)
```
##### CONFIGURATION

No custom configuration.
##### OS / ENVIRONMENT

Debian 8.4
##### SUMMARY

I have playbooks (and roles) where most of fetching tasks (get_url, etc.) need some http_proxy environment variable set to work correctly. Few of them must use another proxy or reset it at all. So I define variable http_proxy in per-playbook `environment` clause and expect that it possible to override his value with per-task `environment` clause, but expectation didn't meet.
##### STEPS TO REPRODUCE

```
- hosts: 10.200.232.48
  user: root
  tasks:
    - name: Task that needs http_proxy
      debug: msg="http_proxy={{ ansible_env.http_proxy }}"
    # ... other tasks or roles that needs http_proxy ...
    - name: Task that needs to redefine proxy or reset it
      debug: msg="http_proxy={{ ansible_env.http_proxy }}"
      environment:
        http_proxy: "" # it must override global definition of http_proxy
  environment:
    http_proxy: "http://proxy"
```

##### EXPECTED RESULTS

I expect that task "`Task that needs to redefine proxy or reset it`" will have http_proxy environment variable set to empty value `""`.
##### ACTUAL RESULTS

```
vagrant@debiancontrib-jessie:/infrastructure$ ansible-playbook -i hosts test.yml

PLAY [10.200.232.48] ***********************************************************

TASK [setup] *******************************************************************
ok: [10.200.232.48]

TASK [Task that needs http_proxy] **********************************************
ok: [10.200.232.48] => {
    "msg": "http_proxy=http://proxy"
}

TASK [Task that needs to redefine proxy or reset it] ***************************
ok: [10.200.232.48] => {
    "msg": "http_proxy=http://proxy"
}

PLAY RECAP *********************************************************************
10.200.232.48              : ok=3    changed=0    unreachable=0    failed=0
```

**Comment by jctanner** [comment]
@nartamonov To summarize, you want the task level env settings to take precedence over the play level? Is that correct?

**Comment by nartamonov** [comment]
@jctanner, exactly!

**Comment by bcoca** [comment]
environment does NOT directly update ansible_env which is the result of running fact gathering. This is a flawed test as ansible_env reflects the environment form when facts where gathered.

This would be a proper test:

```
- hosts: 10.200.232.48
  user: root
  tasks:
    - name: Task that needs http_proxy
      debug: msg="http_proxy={{ ansible_env.http_proxy }}"
    # ... other tasks or roles that needs http_proxy ...
    - setup:
      environment:
        http_proxy: "" # it must override global definition of http_proxy
    - name: Task that needs to redefine proxy or reset it
      debug: msg="http_proxy={{ ansible_env.http_proxy }}"
  environment:
    http_proxy: "http://proxy"
```

Since this 'just works' I'm going to close the ticket
