### ISSUE TITLE
Become_user isn't honored for service restarts

### ISSUE THREAD

**Issue by ssenaria** [ansible/ansible#16011]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/deployment/scripts/playbooks.wip/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Centos 7.1
##### SUMMARY

When I attempt to restart services, I get an error stating that the user cannot access a certain file. It works if I put `sudo` in front of the command.
##### STEPS TO REPRODUCE

This does not work

```
- name: restart web server
  shell: /etc/init.d/aria_services restart
  when: install_rpm_results|success
  register: restart_services_result
  failed_when: "'FAIL' in restart_services_result.stdout"
  ignore_errors: True
  become_user: root
```

This works:

```
- name: restart web server
  shell: sudo /etc/init.d/aria_services restart
  when: install_rpm_results|success
  register: restart_services_result
  failed_when: "'FAIL' in restart_services_result.stdout"
  ignore_errors: True
```
##### EXPECTED RESULTS

Services restart.

```
"stdout": "Creating /web bind mounts\n=== stop ===\n== no PID means no KILL ==\nClearing wsdl and symfony cache files\n=== start ===\nQuery API OK\nNGUI API OK\nCore API OK\nAdmin API OK\nFailed ARC/VIE API\n2 attempted: 2 started, 2 stopped",
        "stdout_lines": [
            "Creating /web bind mounts",
            "=== stop ===",
            "== no PID means no KILL ==",
            "Clearing wsdl and symfony cache files",
            "=== start ===",
            "Query API OK",
            "NGUI API OK",
            "Core API OK",
            "Admin API OK",
            "Failed ARC/VIE API",
            "2 attempted: 2 started, 2 stopped"
        ],
```
##### ACTUAL RESULTS

```
"stderr": "Password: su: Authentication information cannot be recovered\ncat: /etc/aria/services: Permission denied",
        "stdout": "No aria services found",
```

**Comment by sivel** [comment]
I cannot gauge whether you have indentation typos or not, but `become_user` should not be indented to the same level as the module args, it should be indented to the same level as `name`.  Additionally `become_user` does not imply `become: true`, so you will also still need to specify that as well.

**Comment by sivel** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by ssenaria** [comment]
Grrr, no it is indented properly and matches to `- name`.

I also had tried setting `become: True` and i have the same result.
