### ISSUE TITLE
RPM building error: No module named ansible.utils

### ISSUE THREAD

**Issue by nicolaasuni** [ansible/ansible#1602]
I just tried to build the Ansible RPM on CentOS 6.3 but I got this error:

Initialized empty Git repository in /home/makerpm/ansible/.git/
Cleaning up distutils stuff
rm -rf build
rm -rf dist
Cleaning up byte compiled python stuff
find . -type f -regex "._.py[co]$" -delete
Cleaning up editor backup files
find . -type f ( -name "_~" -or -name "#_" ) -delete
find . -type f ( -name "_.swp" ) -delete
Cleaning up manpage stuff
find ./docs/man -type f -name "_.xml" -delete
find ./docs/man -type f -name "_.asciidoc" -delete
find ./docs/man/man3 -type f -name "_.3" -delete
Cleaning up output from test runs
rm -rf test/test_data
Cleaning up RPM building stuff
rm -rf MANIFEST rpm-build
Cleaning up Debian building stuff
rm -rf debian
rm -rf deb-build
rm -rf docs/json
rm -rf docs/js
hacking/module_formatter.py -A 0.9 -t man -o docs/man/man3/ --module-dir=library --template-dir=hacking/templates
Traceback (most recent call last):
  File "hacking/module_formatter.py", line 32, in <module>
    import ansible.utils
ImportError: No module named ansible.utils
make: *_\* [modulepages] Error 1

**Comment by mpdehaan** [comment]
needs to be added to setup.py

**Comment by mpdehaan** [comment]
this was fixed by sourcing the module formatter from PYTHONPATH rather than requiring it to be installed, actually.

Should be good to go now.
