### ISSUE TITLE
Apply Yum update with option latest  is no working 

### ISSUE THREAD

**Issue by mgamboa** [ansible/ansible#16020]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### OS / ENVIRONMENT

Centos 6.7
##### SUMMARY

I'm Trying to update 1 machine as test but is not working 

This is content of the playbook
- name: yum updates
  yum: name=\* state=latest exclude=postgres*

I run the command but coming with ok nothing to do here 

ok: [10.227.96.78] => {"changed": false, "invocation": {"module_args": {"conf_file": null, "disable_gpg_check": false, "disablerepo": null, "enablerepo": null, "exclude": "point_,verifone_", "install_repoquery": true, "list": null, "name": ["*"], "state": "latest", "update_cache": false, "validate_certs": true}, "module_name": "yum"}, "msg": "", "rc": 0, "results": ["Nothing to do here, all packages are up to date"]}

if i make yum check-update in the machine is comes back with

yum check-update
Loaded plugins: fastestmirror, rhnplugin, security
This system is receiving updates from RHN Classic or Red Hat Satellite.
Loading mirror speeds from cached hostfile

at.x86_64                       3.1.10-48.el6             centos6-x86_64
authconfig.x86_64               6.1.12-23.el6             centos6-x86_64
bash.x86_64                     4.1.2-33.el6_7.1          centos6-x86_64-updates
binutils.x86_64                 2.20.51.0.2-5.43.el6      centos6-x86_64
ca-certificates.noarch          2015.2.6-65.0.1.el6_7     centos6-x86_64-updates
cairo.x86_64                    1.8.8-6.el6_6             centos6-x86_64
centos-release.x86_64           6-7.el6.centos.12.3       centos6-x86_64
chkconfig.x86_64                1.3.49.3-5.el6_7.2        centos6-x86_64-updates
coreutils.x86_64                8.4-37.el6_7.3            centos6-x86_64-updates
coreutils-libs.x86_64           8.4-37.el6_7.3            centos6-x86_64-updates
cronie.x86_64                   1.4.4-15.el6_7.1          centos6-x86_64-updates
cronie-anacron.x86_64           1.4.4-15.el6_7.1          centos6-x86_64-updates
cups.x86_64                     1:1.4.2-72.el6            centos6-x86_64
cups-libs.x86_64                1:1.4.2-72.el6            centos6-x86_64
curl.x86_64                     7.19.7-46.el6             centos6-x86_64
db4.x86_64                      4.7.25-20.el6_7           centos6-x86_64-updates
db4-cxx.x86_64                  4.7.25-20.el6_7           centos6-x86_64-updates
db4-devel.x86_64                4.7.25-20.el6_7           centos6-x86_64-updates
db4-utils.x86_64                4.7.25-20.el6_7           centos6-x86_64-updates
dbus.x86_64                     1:1.2.24-8.el6_6          centos6-x86_64
dbus-libs.x86_64                1:1.2.24-8.el6_6          centos6-x86_64
device-mapper.x86_64            1.02.95-3.el6_7.4         centos6-x86_64-updates
device-mapper-event.x86_64      1.02.95-3.el6_7.4         centos6-x86_64-updates
device-mapper-event-libs.x86_64 1.02.95-3.el6_7.4         centos6-x86_64-updates
device-mapper-libs.x86_64       1.02.95-3.el6_7.4         centos6-x86_64-updates
dhclient.x86_64                 12:4.1.1-49.P1.el6.centos centos6-x86_64
dhcp-common.x86_64              12:4.1.1-49.P1.el6.centos centos6-x86_64
dracut.noarch                   004-388.el6               centos6-x86_64
dracut-kernel.noarch            004-388.el6               centos6-x86_64
.... plus more
##### STEPS TO REPRODUCE

Create a task 
- name: yum updates
  yum: name=\* state=latest exclude=postgres*

Execute the task on a host that need updates

```
- name: yum updates
  yum: name=* state=latest exclude=postgres*

```

##### EXPECTED RESULTS

```
System get updates and exclude the packages that is specify on the task
```
##### ACTUAL RESULTS

PLAYBOOK: update.yml ***********************************************************
1 plays in update.yml

PLAY [common tasks for PreProduction enviroments] ******************************

TASK [setup] *******************************************************************
<10.227.96.78> ESTABLISH SSH CONNECTION FOR USER: ansible
<10.227.96.78> SSH: EXEC sshpass -d12 ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o User=ansible -o ConnectTimeout=10 -o ControlPa                                                                                                th=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.227.96.78 '/bin/sh -c '"'"'( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1464323                                                                                                300.33-7042621542019`" && echo ansible-tmp-1464323300.33-7042621542019="`echo $HOME/.ansible/tmp/ansible-tmp-1464323300.33-7042621542019`"                                                                                                 ) && sleep 0'"'"''
<10.227.96.78> PUT /tmp/tmpy0mR3X TO /home/ansible/.ansible/tmp/ansible-tmp-1464323300.33-7042621542019/setup
<10.227.96.78> SSH: EXEC sshpass -d12 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o User=ansible -o ConnectTime                                                                                                out=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[10.227.96.78]'
<10.227.96.78> ESTABLISH SSH CONNECTION FOR USER: ansible
<10.227.96.78> SSH: EXEC sshpass -d12 ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o User=ansible -o ConnectTimeout=10 -o ControlPa                                                                                                th=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.227.96.78 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/                                                                                                bin/python /home/ansible/.ansible/tmp/ansible-tmp-1464323300.33-7042621542019/setup; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-146432330                                                                                                0.33-7042621542019/" > /dev/null 2>&1 && sleep 0'"'"''
ok: [10.227.96.78]

TASK [update : yum updates] ****************************************************
task path: /ansible/Pre-Updates/roles/update/tasks/main.yml:4
<10.227.96.78> ESTABLISH SSH CONNECTION FOR USER: ansible
<10.227.96.78> SSH: EXEC sshpass -d12 ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o User=ansible -o ConnectTimeout=10 -o ControlPa                                                                                                th=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.227.96.78 '/bin/sh -c '"'"'( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1464323                                                                                                301.07-190030343953216`" && echo ansible-tmp-1464323301.07-190030343953216="`echo $HOME/.ansible/tmp/ansible-tmp-1464323301.07-190030343953                                                                                                216`" ) && sleep 0'"'"''
<10.227.96.78> PUT /tmp/tmpy0mR3X TO /home/ansible/.ansible/tmp/ansible-tmp-1464323301.07-190030343953216/yum
<10.227.96.78> SSH: EXEC sshpass -d12 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o User=ansible -o ConnectTime                                                                                                out=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[10.227.96.78]'
<10.227.96.78> ESTABLISH SSH CONNECTION FOR USER: ansible
<10.227.96.78> SSH: EXEC sshpass -d12 ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o User=ansible -o ConnectTimeout=10 -o ControlPa                                                                                                th=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.227.96.78 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/                                                                                                bin/python /home/ansible/.ansible/tmp/ansible-tmp-1464323301.07-190030343953216/yum; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-146432330                                                                                                1.07-190030343953216/" > /dev/null 2>&1 && sleep 0'"'"''
ok: [10.227.96.78] => {"changed": false, "invocation": {"module_args": {"conf_file": null, "disable_gpg_check": false, "disablerepo": null, "                                                                                                enablerepo": null, "exclude": "postgres_", "install_repoquery": true, "list": null, "name": ["_"], "state": "latest", "update_cache":                                                                                                 false, "validate_certs": true}, "module_name": "yum"}, "msg": "", "rc": 0, "results": ["Nothing to do here, all packages are up to date"]}

PLAY RECAP *********************************************************************
10.227.96.78               : ok=2    changed=0    unreachable=0    failed=0

```

```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
