### ISSUE TITLE
ERROR! Unexpected Exception: Values instance has no attribute 'ignore_certs'

### ISSUE THREAD

**Issue by vnitinv** [ansible/ansible#16024]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible --version
ansible 2.1.0.0
```
##### OS / ENVIRONMENT

Mac OS
##### SUMMARY

ansible-galaxy list throws error
ansible-galaxy list
ERROR! Unexpected Exception: Values instance has no attribute 'ignore_certs'

ansible-galaxy also gives "ERROR! Missing required action"
(env)nitinkr-mba13:ansible_env nitinkr$ ansible-galaxy --version
Usage: ansible-galaxy [delete|import|info|init|install|list|login|remove|search|setup] [--help] [options] ...

Options:
  -h, --help     show this help message and exit
  -v, --verbose  verbose mode (-vvv for more, -vvvv to enable connection
                 debugging)
  --version      show program's version number and exit
ERROR! Missing required action
(env)nitinkr-mba13:ansible_env nitinkr$ ansible-galaxy --version Juniper.junos
Usage: ansible-galaxy [delete|import|info|init|install|list|login|remove|search|setup] [--help] [options] ...

Options:
  -h, --help     show this help message and exit
  -v, --verbose  verbose mode (-vvv for more, -vvvv to enable connection
                 debugging)
  --version      show program's version number and exit
##### STEPS TO REPRODUCE

ansible-galaxy command with list,version
##### EXPECTED RESULTS

ansible-galaxy --version Juniper.junos should give version not the error message.

**Comment by sdarwin** [comment]
also getting those errors.

**Comment by kernow** [comment]
I'm getting this error also with the same version of ansible. Is there a workaround?

**Comment by steelywing** [comment]
Also in Ubuntu.

**Comment by kernow** [comment]
Downgrading to version 2.0.0.2 was the only way I was able to resolve the issue.

**Comment by jctanner** [comment]
@vnitinv @sdarwin @kernow @steelywing please run ansible-galaxy with -vvvv and post the traceback. I'm not seeing the same error, so I need further data.

**Comment by vnitinv** [comment]
@jctanner 

ansible-galaxy list -vvvv
Using /etc/ansible/ansible.cfg as config file
Opened /Users/nitinkr/.ansible_galaxy
ERROR! Unexpected Exception: Values instance has no attribute 'ignore_certs'
the full traceback was:

Traceback (most recent call last):
  File "/Users/nitinkr/Coding/PyEZ_env/ansible21_env/env/bin/ansible-galaxy", line 92, in <module>
    exit_code = cli.run()
  File "/Users/nitinkr/Coding/PyEZ_env/ansible21_env/env/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 152, in run
    self.api = GalaxyAPI(self.galaxy)
  File "/Users/nitinkr/Coding/PyEZ_env/ansible21_env/env/lib/python2.7/site-packages/ansible/galaxy/api.py", line 74, in **init**
    if galaxy.options.ignore_certs:
AttributeError: Values instance has no attribute 'ignore_certs'

**Comment by mnar** [comment]
Same problem exactly here. Ubuntu

**Comment by mnar** [comment]
@kernow how did you downgrade to 2.0.0.2 ?

**Comment by cefera6** [comment]
Same problem in 2.2.0.

**SO**
$ cat /etc/issue
CentOS release 6.8 (Final)

**Version**
$ ansible --version
ansible 2.2.0 (devel 0e8930640a) last updated 2016/05/20 19:40:01 (GMT -200)
  lib/ansible/modules/core: (detached HEAD d3097bf580) last updated 2016/05/20 19:40:13 (GMT -200)
  lib/ansible/modules/extras: (detached HEAD ce5a9b6c5f) last updated 2016/05/20 19:40:24 (GMT -200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

**Output**
$ ansible-galaxy list -vvvv
Using /etc/ansible/ansible.cfg as config file
Opened /etc/ansible/.ansible_galaxy
ERROR! Unexpected Exception: Values instance has no attribute 'ignore_certs'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/ansible-git/bin/ansible-galaxy", line 92, in <module>
    exit_code = cli.run()
  File "/usr/local/ansible-git/lib/ansible/cli/galaxy.py", line 152, in run
    self.api = GalaxyAPI(self.galaxy)
  File "/usr/local/ansible-git/lib/ansible/galaxy/api.py", line 74, in **init**
    if galaxy.options.ignore_certs:
AttributeError: Values instance has no attribute 'ignore_certs'

I tried to put "ignore_certs = True" in galaxy section of ansible.cfg, but the results have not changed.

**Comment by jctanner** [comment]
3 commits have been made to the galaxy cli files since 2.1:

https://github.com/ansible/ansible/commit/2261b2e59ac14210f06e86a0bb8f774a3780c9a6
https://github.com/ansible/ansible/commit/011320793bafffe764a07f4e3d9ee66872b32872
https://github.com/ansible/ansible/commit/eaa7b9c0b70fe022bb2ba4b6d82b02445efa20ba

Based on the traceback from @cefera6 + @vnitinv and testing with devel versus 2.1, this issue should be fixed now.

**Comment by bjolivot** [comment]
Hi
is there some workaround ?

**Comment by RockingRolli** [comment]
Downgrading ansible (assuming you installed it using pip)

```
pip install ansible==2.0.0.2
# Do whatever you need to to with ansible-galaxy
pip install ansible --upgrade
```

**Comment by bjolivot** [comment]
thank you, it's now not showing error...nor full list of roles available -_-'
