### ISSUE TITLE
The catch-all except in _get_server_api_version in galaxy.api masks .netrc permission error.

### ISSUE THREAD

**Issue by nilsfr** [ansible/ansible#16039]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/nilsfr/usit/ansible/vortex-provision/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Run on Linux.
##### SUMMARY

The _get_server_api_version method in ansible.galaxy.api.GalaxyAPI have an except clause that catches all exceptions. It also caught  an error raised because I had invalid permission on my ~/.netrc file. The error given was completely misleading. The except clause should be more specific or the original exception message must be given somehow. 
##### STEPS TO REPRODUCE

```
touch ~/.netrc
chmod 644 ~/.netrc
ansible-galaxy install bennojoy.memcached
```

##### EXPECTED RESULTS

Given role should be installed
##### ACTUAL RESULTS

```
 [WARNING]: -  bennojoy.memcached was NOT installed successfully: The API server (https://galaxy.ansible.com/api/) is
not responding, please try again later

```

**Comment by bartfeenstra** [comment]
I ran into this problem as well. After trying @Qalthos's patch on 2.1, I got to see the root error message (`~/.netrc` having too liberal file permissions).

I see this was fixed in 2.2 in early June. Thanks!
