### ISSUE TITLE
ansible should check if host_vars and group_vars directories exist before trying to parse any files

### ISSUE THREAD

**Issue by johnnys66** [ansible/ansible#16033]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0  -> RPM package Centos7
ansible 2.1.0.0 (stable-2.1 2452bd2135) last updated 2016/05/24 18:43:09 (GMT +100) -> source
```
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

Management station:  CentOS Linux release 7.2.1511 (Core)
##### SUMMARY

I'm using dynamic inventory, pulling hosts/groups list from an ldap and I have no host_vars directories created. Ansible still looks for files there making any deployment process very slow and it could be avoided if the existence of the host_vars directories was checked before trying to parse files there.
The same happens for group_vars.
##### STEPS TO REPRODUCE

A simple strace of a ping request shows that ansible tries to stat .yml, .yaml and .json file for every host returned from the external source.

```
strace ansible host1.testdomain -m ping -u monitor
```

##### EXPECTED RESULTS

I expected that since the host_vars and group_vars directories don't exist, ansible would not waist any time trying to parse files there.
##### ACTUAL RESULTS

If I have 1000 managed hosts, ansible will try to stat for each host .yml, .yaml and .json files in both default locations «INVENTORY_DIR»/host_vars and «HOME_DIR»/host_vars.

```
strace partial output showing that despite the directories don't exist, files are still looked for:
...
stat("/opt/ansible/plugins/inventory", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/opt/ansible/plugins/inventory", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/opt/ansible/plugins/inventory/host_vars/host1.testdomain", 0x7ffeb541cf00) = -1 ENOENT (No such file or directory)
stat("/opt/ansible/plugins/inventory/host_vars/host1.testdomain", 0x7ffeb541cf00) = -1 ENOENT (No such file or directory)
stat("/opt/ansible/plugins/inventory/host_vars/host1.testdomain.yml", 0x7ffeb541cf00) = -1 ENOENT (No such file or directory)
stat("/opt/ansible/plugins/inventory/host_vars/host1.testdomain.yaml", 0x7ffeb541cf00) = -1 ENOENT (No such file or directory)
stat("/opt/ansible/plugins/inventory/host_vars/host1.testdomain.json", 0x7ffeb541cf00) = -1 ENOENT (No such file or directory)
stat("./", {st_mode=S_IFDIR|0700, st_size=1024, ...}) = 0
getcwd("/home/ansible", 1026)           = 14
stat("/home/ansible/host_vars/host1.testdomain", 0x7ffeb541cf00) = -1 ENOENT (No such file or directory)
stat("/home/ansible/host_vars/host1.testdomain", 0x7ffeb541cf00) = -1 ENOENT (No such file or directory)
stat("/home/ansible/host_vars/host1.testdomain.yml", 0x7ffeb541cf00) = -1 ENOENT (No such file or directory)
stat("/home/ansible/host_vars/host1.testdomain.yaml", 0x7ffeb541cf00) = -1 ENOENT (No such file or directory)
stat("/home/ansible/host_vars/host1.testdomain.json", 0x7ffeb541cf00) = -1 ENOENT (No such file or directory)
...
```

**Comment by towolf** [comment]
This was fixed the same day that this issue was filed with my recent PR at https://github.com/ansible/ansible/commit/328b423a0ead69802c6e2ecf91f8b3cb594f4c85

**Comment by bcoca** [comment]
closing as per above
