### ISSUE TITLE
Ansible will create a literal $HOME directory if the variable is not set

### ISSUE THREAD

**Issue by dmsimard** [ansible/ansible#16032]
##### ISSUE TYPE

Bug Report
##### ANSIBLE VERSION

ansible 2.1.0.0
##### CONFIGURATION

Nothing relevant
##### OS / ENVIRONMENT

Not platform specific
##### SUMMARY

When the $HOME variable is not set, Ansible creates a literal $HOME directory in the current working directory:

```
(venv) ┬─[dmsimard@hostname:~/dev/ara/$HOME/.ansible]─[10:53:57 AM]
╰─> (static-generation) $ tree
.
└── tmp
    ├── ansible-local-tmp2Gdd9B
    ├── ansible-local-tmp3DDjOt
    ├── ansible-local-tmp3zLvr4
    ├── ansible-local-tmp3ZRISO
    ...
```

![Alt text](http://i.imgur.com/MKBxpc1.png)
##### STEPS TO REPRODUCE

Inventory:

```
localhost  ansible_connection=local
```

Unset $HOME, run Ansible.
I came across this problem when running Ansible from tox without "HOME" being specified in "passenv" so the $HOME variable wasn't passed to the tox environment.
##### EXPECTED RESULTS

I don't expect Ansible to create a literal $HOME directory in the current working directory. At worst, create a ".ansible" folder if $HOME is not set.
##### ACTUAL RESULTS

A $HOME directory is created in the current working directory.

**Comment by dmsimard** [comment]
It looks to me like we should probably rely on '~', rather than $HOME, which is properly expanded even if $HOME is not set:

```
[dmsimard@hostname ara]$ env |grep HOME
HOME=/home/dmsimard
[dmsimard@hostname ara]$ python
Python 2.7.11 (default, Mar 31 2016, 20:46:51) 
[GCC 5.3.1 20151207 (Red Hat 5.3.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> print(os.path.expanduser('~/.ansible'))
/home/dmsimard/.ansible
>>> 
[dmsimard@hostname ara]$ unset HOME
[dmsimard@hostname ara]$ env |grep HOME
[dmsimard@hostname ara]$ python
Python 2.7.11 (default, Mar 31 2016, 20:46:51) 
[GCC 5.3.1 20151207 (Red Hat 5.3.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> print(os.path.expanduser('~/.ansible'))
/home/dmsimard/.ansible
>>>
```

This would be in constants: https://github.com/ansible/ansible/blob/bf0da4aa3c0417551c9163f13ed05dc5d70322ab/lib/ansible/constants.py#L144-L145

**Comment by larsks** [comment]
A simple reproducer:

```
env -i /usr/bin/ansible all -m ping
```

This will create a `$HOME` directory in your current directory.

**Comment by larsks** [comment]
Also, note that this is a problem with more than just `$HOME`; this is a fundamental problem with environment variable expansion via `os.path.expandvars`, whic says:

> Unknown variables are left unchanged.

That means you have no way to tell if there were undefined variables or not, so there's no easy way to detect this problem unless you replace `os.path.expandvars` with something else.

**Comment by larsks** [comment]
With the fix proposed in https://github.com/ansible/ansible/pull/16034, the behavior is now:

```
$ env -i PYTHONPATH=$PYTHONPATH `which ansible` all -m ping
Traceback (most recent call last):
  File "/home/lars/src/ansible/bin/ansible", line 44, in <module>
    import ansible.constants as C
  File "/home/lars/src/ansible/lib/ansible/constants.py", line 167, in <module>
    DEFAULT_LOCAL_TMP         = get_config(p, DEFAULTS, 'local_tmp',        'ANSIBLE_LOCAL_TEMP',      '$HOME/.ansible/tmp', istmppath=True)
  File "/home/lars/src/ansible/lib/ansible/constants.py", line 92, in get_config
    value = shell_expand(value)
  File "/home/lars/src/ansible/lib/ansible/constants.py", line 69, in shell_expand
    raise AnsibleOptionsError("Undefined environment variable: {0}".format(err))
ansible.errors.AnsibleOptionsError: Undefined environment variable: 'HOME'
```

**Comment by bcoca** [comment]
I'm not sure this is a bug or just expected behavior.

**Comment by dmsimard** [comment]
@bcoca In the worst case scenario, Ansible should create ".ansible" in the cwd, not create a directory literally called "$HOME" and .ansible in it.

**Comment by larsks** [comment]
@bcoca  I think that treating a variable literally if it doesn't exist is clearly a bug.  It results in a value that is clearly incorrect.  Most languages will throw an error for undefined variables, and the shell will at least replace it with an empty string (which would cause a different set of problems in this case).

**Comment by bcoca** [comment]
its not an ansible variable, you are defining a shell variable and we pass it to the shell, the shell does not complain by default. Not sure why its not being 'emptied'.

**Comment by chris-west-travelex** [comment]
For the record, this affects `ansible-pull` as well, creating `$HOME/.ansible/tmp` in pull's working directory and causing multiple `ansible-pull` calls to fail because git's working directory isn't clean. Our work-around is to nuke pull's working directory between runs, but it'd be nice for a proper fix :)

**Comment by larsks** [comment]
@bcoca:

> its not an ansible variable, you are defining a shell variable and we pass it to the shell

We are not passing the variable to the shell.  We are passing a variable to `os.path.expandvars`.  This is entirely an Ansible bug (because it breaks exactly the way the standard library documentation says it will break).

**Comment by larsks** [comment]
@chris-west-travelex I'm curious if the fix I proposed in https://github.com/ansible/ansible/pull/16034 looks sane to you?

**Comment by chris-west-travelex** [comment]
@larsks: that looks like it'll kill `ansible-pull` altogether if $HOME isn't set. i bet that'd cause problems for people who put it in cron (or cloud-init, like we do). Perhaps it's more that the proposed fix in #16034 is fine, but `ansible-pull` needs to not have a hard dependency on $HOME, as per @dmsimard's comment above.

**Comment by dtwilliamson** [comment]
Note that this problem also exists in ssh.py or path.py and probably a few other places where `expandvars()` is used.

You could use

```
from string import Template
Template(path).substitute(os.environ))
```

instead of the proposed code in order to generate a KeyError exception on an empty environment variable.

Why does this code not respect `local_tmp`, by the way?

**Comment by westsouthnight** [comment]
If you can, see link, i think i have similar issue with other module where uses os.environ

http://stackoverflow.com/questions/36043393/set-environment-in-ansible-doesnt-seem-to-work/37950548#37950548

**Comment by fxfitz** [comment]
FWIW, I'm +1'ing that this is a bug.

**Comment by mcameron** [comment]
+1

**Comment by jarovo** [comment]
It is quite dangerous bug considering one may fall into this trap:

```
rm -rf $HOME 
```

**Comment by fxfitz** [comment]
... yup, I did that... #fail

**Comment by fxfitz** [comment]
... yup, I did that... #fail
