### ISSUE TITLE
Is there a way to mention yum module to use local cache.

### ISSUE THREAD

**Issue by sandye** [ansible/ansible#16040]
This is not an issue as such.
I wanted to know how to use a yum cache, rather than pulling latest files always from internet.
I looking for a way to make ansible use "yum -C" whenever we say yum in playbooks.

Any help is much appreciated.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
