### ISSUE TITLE
Ansible 2.0.2.0 can't work about the service commands?

### ISSUE THREAD

**Issue by ihaolin** [ansible/ansible#16053]
Hello，I'm working **ansible 2.0.2.0** on **Centos 6.7 Final**，It's strange that the commands about **service** can't work well.

I have a service named **track-filebeat-error** on machine **logstash01**，I try to use ansible ad-hoc command to start it:

```
ansible host1 -a 'service track-filebeat-error start'
```

It prints the success msg:

```
logstash01 | SUCCESS | rc=0 >>
Logstash started with pid 30959
```

but the process about **logstash** process can't found with `ps -ef | grep logstash`.

So I try to use `ssh` command directly:

```
ssh 10.112.88.153 'service track-filebeat-error start'
```

It also prints `Logstash started with pid xxxx`  and can found **logstash** process with `ps -ef | grep logstash`

Bellow is the command staring the logstash process:

```
/usr/bin/logstash -f /etc/logstash.conf 1>"/var/log/logstash.log" 2>&1 &
```

I'm very confused about this, I guess that ansible close the process before the **logstash** started, because **logstash** starting isn't a daemon.

Can someone suggest me?

Thanks & Regards.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
