### ISSUE TITLE
Changes in raw module

### ISSUE THREAD

**Issue by pujan14** [ansible/ansible#16054]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible --version
ansible 2.1.0.0
  config file = /home/pujan14/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

"N/A"
##### SUMMARY

ssh commands used with raw modules are changed and they assume that we have sh running/accessible on remote host.
On some devices that is not the case (switches, printers etc.)

This issue occurs with ansible 2.1 but not with ansible 2.0.*
##### STEPS TO REPRODUCE

```
  tasks:
    - raw: racadm getconfig -g idracinfo -o idRacType
```
##### EXPECTED RESULTS

This is what I get with ansible 2.0.0.1

```
EXEC sshpass -d15 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o User=abcd -o ConnectTimeout=60 -o 'ControlPath=~/.ssh/ansible-ssh-%h-%p-%r' -tt 1.2.3.4 'racadm getconfig -g idracinfo -o idRacType'
```
##### ACTUAL RESULTS

This is what I get with ansible 2.1

```
EXEC sshpass -d16 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o User=abcd -o ConnectTimeout=60 -o 'ControlPath=~/.ssh/ansible-ssh-%h-%p-%r' -tt 1.2.3.4 '/bin/sh -c '"'"'racadm getconfig -g idracinfo -o idRacType && sleep 0'"'"''
```

**Comment by jctanner** [comment]
This was caused by changes made to mitigate https://github.com/ansible/ansible/issues/13876

**Comment by mattclay** [comment]
The behavior of the raw action changed (https://github.com/ansible/ansible/commit/db61e9be0cb4f9840156877dac455fb46809c5d5) in 2.1 to automatically add a shell to the command unless executable is specified. To achieve the old behavior, add `executable=''` to the end of your command.

In the example given, this would be:

```
tasks:
    - raw: racadm getconfig -g idracinfo -o idRacType executable=''
```

**Comment by bcoca** [comment]
that change should NOT have affected `raw` nor `script` as both of those modules handle their own shell if needed.

**Comment by fiphedawg** [comment]
I ran into the similar problem adding "executable="  resolved the issue.  I assume its the shell that dells idrac uses or lack thereof

**Comment by pujan14** [comment]
Thanks @bcoca
