### ISSUE TITLE
Host name in SSH ControlPath for sftp is not parsed correctly, so tasks fail.

### ISSUE THREAD

**Issue by tinproject** [ansible/ansible#16066]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

This is my ssh_connection section in ansible.cfg

```
[ssh_connection]
control_path = %(directory)s/%%h-%%p-%%r
ssh_args = -o ControlMaster=auto -o ControlPersist=600s
pipelining = True
```

hosts file:

```
[server2]
server2.codecantor.com ansible_connection=ssh ansible_user=deploy

[server1]
server1.codecantor.com ansible_connection=ssh ansible_user=deploy

[server3]
server3.codecantor.com  ansible_port=22 ansible_connection=ssh ansible_user=deploy

[all:children]
server2
server1
server3
```
##### OS / ENVIRONMENT

I'm running ansible on OSX 10.11.5
##### SUMMARY

I'v found that the host name  SSH ControlPath for sftp is not parsed correctly so the tasks fails with `"msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh"`
##### STEPS TO REPRODUCE

run a template task with:

```
ansible-playbook app_staging.yml --check -vvvv
```

##### EXPECTED RESULTS

Task will run successfully.
##### ACTUAL RESULTS

Task fails thinking it's a ssh conectivity problem. This shows the output of two tasks, one that don't use sftp and succeds and one that use sftp and fails:

```
TASK [prepare-cap : Create shared config folder] *******************************
task path: /Users/agustin/DEPLOY/app/roles/prepare-cap/tasks/main.yml:25
<server1.codecantor.com> ESTABLISH SSH CONNECTION FOR USER: deploy
<server1.codecantor.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=600s -o 'IdentityFile="/Users/agustin/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=deploy -o ConnectTimeout=10 -o ControlPath=/Users/agustin/.ansible/cp/%h-%p-%r server1.codecantor.com '/bin/sh -c '"'"'LANG=es_ES.UTF-8 LC_ALL=es_ES.UTF-8 LC_MESSAGES=es_ES.UTF-8 /usr/bin/python && sleep 0'"'"''
changed: [server1.codecantor.com] => {"changed": true, "diff": {"after": {"group": 33, "path": "/var/www/app/api/shared/config/"}, "before": {"group": 5000, "path": "/var/www/app/api/shared/config/"}}, "gid": 5000, "group": "deploy", "invocation": {"module_args": {"backup": null, "content": null, "delimiter": null, "diff_peek": null, "directory_mode": null, "follow": false, "force": false, "group": "www-data", "mode": null, "original_basename": null, "owner": "deploy", "path": "/var/www/app/api/shared/config/", "recurse": false, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": null, "state": "directory", "validate": null}, "module_name": "file"}, "mode": "0775", "owner": "deploy", "path": "/var/www/app/api/shared/config/", "size": 4096, "state": "directory", "uid": 5000}

TASK [prepare-cap : Create database config file] *******************************
task path: /Users/agustin/DEPLOY/app/roles/prepare-cap/tasks/main.yml:31
<server1.codecantor.com> ESTABLISH SSH CONNECTION FOR USER: deploy
<server1.codecantor.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=600s -o 'IdentityFile="/Users/agustin/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=deploy -o ConnectTimeout=10 -o ControlPath=/Users/agustin/.ansible/cp/%h-%p-%r server1.codecantor.com '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1464689070.98-168137819856829 `" && echo ansible-tmp-1464689070.98-168137819856829="` echo $HOME/.ansible/tmp/ansible-tmp-1464689070.98-168137819856829 `" ) && sleep 0'"'"''
<server1.codecantor.com> PUT /var/folders/0n/g4940chx1gsbxlk_0dm5ns240000gn/T/tmpbWNU3r TO /var/www/.ansible/tmp/ansible-tmp-1464689070.98-168137819856829/stat
<server1.codecantor.com> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=600s -o 'IdentityFile="/Users/agustin/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=deploy -o ConnectTimeout=10 -o ControlPath=/Users/agustin/.ansible/cp/%h-%p-%r '[server1.codecantor.com]'
fatal: [server1.codecantor.com]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"backup": true, "dest": "/var/www/app/api/shared/config/database.yml", "group": "www-data", "owner": "deploy", "src": "database.yml.j2"}, "module_name": "template"}, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh"}

```

Note the diferences in the host name present in ControlPath option for a SSH command:

`SSH: EXEC ssh ... -o ControlPath=/Users/agustin/.ansible/cp/%h-%p-%r server1.codecantor.com  ...`

and for the SFTP command:

`SSH: EXEC sftp ... -o ControlPath=/Users/agustin/.ansible/cp/%h-%p-%r '[server1.codecantor.com]'  ...`

In this later case the hostname is enclosed between single quote and square brackets making the command fail.

If not use sftp adding this options to ansible.cfg:

```
scp_if_ssh = True
sftp_batch_mode = False
```

the tasks succeeds without any problems.

I thought this could be related to #16030

**Comment by jctanner** [comment]
@tinproject quoted+bracketed hostnames are not an issue for sftp ..

```
[root@localhost ~]# sftp '[127.0.0.1]'
Connecting to 127.0.0.1...
root@127.0.0.1's password:
sftp> bye
[root@localhost ~]#
```

Here's the section of code where we apply those characters ..

```
        # scp and sftp require square brackets for IPv6 addresses, but
        # accept them for hostnames and IPv4 addresses too.
        host = '[%s]' % self.host
```

This problem in your description usually occurs when sshd is misconfigured on the remote. Here's some things to try ..
1. run a standalone sftp command from the ansible machine to the remote host (fix any issues that come up)
2. check the sftp path set in /etc/ssh/sshd_config on the remote host and ensure it is correct

**Comment by jctanner** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Comment by bendiken** [comment]
I just encountered this myself, on OS X 10.11.5 with Ansible 2.0.2.

@jctanner It's true that brackets are not a problem for `sftp` when they're used around the hostname; however, Ansible actually tries to use `[username@hostname]` instead of `username@[hostname]`, hence the problem.

Here's a comprehensive overview of bracket support in SFTP--the failing case is equivalent to the one that Ansible tries:

    $ sftp 'localhost'
    Connected to localhost.
    sftp> ^D

    $ sftp '[localhost]'
    Connected to localhost.
    sftp> ^D

    $ sftp 'arto@localhost'
    Connected to localhost.
    sftp> ^D

    $ sftp '[arto@localhost]'
    ssh: Could not resolve hostname localhost]: nodename nor servname provided, or not known
    Connection closed

    $ sftp 'arto@[localhost]'
    Connected to localhost.
    sftp> ^D

Here follows the specific failing command that Ansible tries to execute:

    $ sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=arto -o ConnectTimeout=10 -o ControlPath=/Users/arto/.ansible/cp/ansible-ssh-%h-%p-%r '[arto@localhost]'

**Comment by tinproject** [comment]
Reading the sftp/ssh man pages brackets are used by ipv6 addresses and patterns. 

@jctanner I don't think the problem is that the address is presented to sftp between enquoted brackets, but surely why the sftp address is enquoted and bracketed, and the ssh address is not, it's related to the spurious problem of unreached hosts.

**Comment by astrostl** [comment]
```
justin$ sftp '[127.0.0.1]'
ssh: connect to host 127.0.0.1 port 22: Connection refused
Connection closed
justin$ sftp '[me@127.0.0.1]'
ssh: Could not resolve hostname 127.0.0.1]: nodename nor servname provided, or not known
Connection closed
justin$
```

FYI, I ran into this because I was specifying user@host in my inventory file.

**Comment by philayres** [comment]
[EDIT] since I see this issue is closed I'll say no more here and transfer my discussion to the Google group...

I experience the same as @astrostl due to a username on the front. The username is necessary, since I have to segregate certain hosts this way that have the same hostname but use different ports (which Ansible sees otherwise as an identical host).

Running the following in the terminal fails in the same way as Ansible:

    sftp -b - -vvv -o StrictHostKeyChecking=no -o Port=2222 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 '[vagrant@vagrant-fphs-webapp-box]

It is true that removing the vagrant@ from within the '[ ]' allows an SFTP connection from the command line, but this is infeasible for me within Ansible.

I'll try switching to scp for now.
