### ISSUE TITLE
host tagging failure

### ISSUE THREAD

**Issue by anshbikram** [ansible/ansible#16081]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

```
[defaults]

inventory           = ./hostfile
forks               = 50
sudo_user           = root
ask_sudo_pass       = True
ask_pass            = False
#ask_vault_pass      = True
gathering           = explicit
host_key_checking   = False
remote_user         = ubuntu
#log_path            = ./ansible.log
nocows              = 0

[privilege_escalation]

become              = True
become_method       = sudo
become_user         = root
become_ask_pass     = False

[ssh_connection]

pipelining          = True
scp_if_ssh          = True
```
##### SUMMARY

In ansible-playbook for different host i have set different tags like

```
- hosts: mysql
  tags: mysql
```

and when i run ansible with "ansible-playbook playbook.yml --list-hosts --tags mysql" listing all the hosts provided in hostfile instead of the hosts corresponding to the mysql hosts only.
##### STEPS TO REPRODUCE

make hostfile as below

```
[msql]
10.10.10.1
10.10.10.2

[compute]
10.10.10.3
10.10.10.4
```

make playbook.yml as below

```
- hosts: mysql
  tags: mysql
  roles: mysql

- hosts: compute
  tags: compute
  roles: mysql
```

now run the following command

```
ansible-playbook playbook.yml --list-hosts --tags mysql
```

##### EXPECTED RESULTS

```
playbook: playbook.yaml

  play #1 (mysql): mysql    TAGS: [mysql]
    pattern: [u'mysql']
    hosts (2):
      10.10.10.1
      10.10.10.2

  play #4 (compute): compute    TAGS: [compute]
    pattern: [u'compute']
    hosts (0):
```
##### ACTUAL RESULTS

```
playbook: playbook.yaml

  play #1 (mysql): mysql    TAGS: [mysql]
    pattern: [u'mysql']
    hosts (2):
      10.10.10.1
      10.10.10.2

  play #4 (compute): compute    TAGS: [compute]
    pattern: [u'compute']
    hosts (2):
      10.10.10.3
      10.10.10.4
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case, tags do NOT affect hosts lists, only tasks, so your expectation in this case does not match with what the feature actually does.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
