### ISSUE TITLE
How to get the playbook api result

### ISSUE THREAD

**Issue by qingshanli1988** [ansible/ansible#16094]
##### ISSUE TYPE
- question ask
##### ANSIBLE VERSION

```
ansible 2.0
python 3.5

user ansible api 2.0 :
http://docs.ansible.com/ansible/developing_api.html
```
##### OS / ENVIRONMENT

centos 7 
##### ACTUAL RESULTS
# source code

```
.......
tqm = None
try:
    tqm = TaskQueueManager(
              inventory=inventory,
              variable_manager=variable_manager,
              loader=loader,
              options=options,
              passwords=passwords,
              stdout_callback='default',
          )
    result = tqm.run(play)
finally:
    if tqm is not None:
        tqm.cleanup()

```

Hown to get the result ? (the default result is 0 or 1 , not  the output result)

**Comment by sivel** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
