### ISSUE TITLE
ec2.py has issues with large number of filters

### ISSUE THREAD

**Issue by westover** [ansible/ansible#16095]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /Users/westover/.ansible.cfg
  configured module search path = ['/Users/westover/.ansible/modules/']
```
##### CONFIGURATION

Paths to hosts directory
##### OS / ENVIRONMENT

OS X 10.11
##### SUMMARY

ec2.py inventory script throwing errors blocks running of any playbook because default AWS credentials are associated with this account
##### STEPS TO REPRODUCE

```
~/.ansible/hosts/ec2.py --list
```
##### EXPECTED RESULTS

Returning of a list of AWS assets
##### ACTUAL RESULTS

The script exits and throws an error

```
~/.ansible/hosts/ec2.py --list
ERROR: "Error connecting to AWS backend.
The maximum number of filter values specified on a single call is 200", while: getting EC2 instances
```

**Comment by argais** [comment]
Just ran into this exact same issue, started showing up once I got more than 200 instances in the region.

**Comment by igreg** [comment]
+1 is there is workaround?

**Comment by igreg** [comment]
I had the same issue and https://github.com/ansible/ansible/pull/16184 fixed the problem for me

**Comment by argais** [comment]
#16184 fixes it for me too.

**Comment by jctanner** [comment]
Reproduced with internal ansible account.

```
$ ./ec2.py --list
ERROR: "Error connecting to AWS backend.
The maximum number of filter values specified on a single call is 200", while: getting EC2 instances
```
