### ISSUE TITLE
Cannot run on hosts with /home mounted as noexec

### ISSUE THREAD

**Issue by iandexter** [ansible/ansible#1609]
Due to our organization's server security policy, /home is mounted as noexec. This presents a problem for Ansible. Here's the error message:

```
$ ansible ourhost.ourcompany.org -m ping -vvv
<ourhost.ourcompany.org> ESTABLISH CONNECTION FOR USER: myuser on PORT 22 TO ourhost.ourcompany.org
<ourhost.ourcompany.org> EXEC "$SHELL" -c 'mkdir -p $HOME/.ansible/tmp/ansible-1352788199.25-241345851012808 && chmod a+rx $HOME/.ansible/tmp/ansible-1352788199.25-241345851012808 && echo $HOME/.ansible/tmp/ansible-1352788199.25-241345851012808'
<ourhost.ourcompany.org> REMOTE_MODULE ping
<ourhost.ourcompany.org> PUT /tmp/tmpVftVQa TO /home/myuser/.ansible/tmp/ansible-1352788199.25-241345851012808/ping
<ourhost.ourcompany.org> EXEC "$SHELL" -c 'chmod u+x /home/myuser/.ansible/tmp/ansible-1352788199.25-241345851012808/ping'
<ourhost.ourcompany.org> EXEC "$SHELL" -c /home/myuser/.ansible/tmp/ansible-1352788199.25-241345851012808/ping
<ourhost.ourcompany.org> EXEC "$SHELL" -c 'rm -rf /home/myuser/.ansible/tmp/ansible-1352788199.25-241345851012808/'
ourhost.ourcompany.org | FAILED >> {
    "failed": true,
    "msg": "/bin/bash: /home/myuser/.ansible/tmp/ansible-1352788199.25-241345851012808/ping: Permission denied\r\n",
    "parsed": false
}
```

Additional information:
1. Ansible release is 0.8.
2. Server is RHEL 5.8 with Python 2.6 installed from EPEL.
3. Host is RHEL 6.3. Other hosts will be 5.x.
4. As much as possible, we want to refrain from using root, so we're using ordinary users that have sudo privileges.

Please let me know if you need more information. Thanks.

**Comment by dhozac** [comment]
Set remote_tmp in your ansible.cfg to something that doesn't include $HOME and you should be good to go.

**Comment by iandexter** [comment]
That worked, thanks!

(Note to self: read `/usr/lib/python2.6/site-packages/ansible/*`)

**Comment by mpdehaan** [comment]
It's also not a problem in Ansible 0.9 where we don't chmod +x the scripts and execute them when we can discern the interpreter line and execute that directly instead.
