### ISSUE TITLE
Paramiko configuration docs incorrect

### ISSUE THREAD

**Issue by jsok** [ansible/ansible#16092]
##### ISSUE TYPE
- Documentation Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  configured module search path = Default w/o overrides
```
##### SUMMARY

Current documentation about Paramiko Specific Settings in the Configuration file docs is incorrect.
##### STEPS TO REPRODUCE

http://docs.ansible.com/ansible/intro_configuration.html#paramiko-specific-settings

https://github.com/ansible/ansible/blob/stable-2.1/lib/ansible/constants.py
##### EXPECTED RESULTS

Documentation should read:

> Settings live under the [paramiko_connection] header.
##### ACTUAL RESULTS

Documentation incorrectly states:

> Settings live under the [paramiko] header.

**Comment by bcoca** [comment]
fixed via merged #16093
