### ISSUE TITLE
Doc for GCE module has layout issues

### ISSUE THREAD

**Issue by nomaster** [ansible/ansible#16103]
##### ISSUE TYPE

- Documentation Report
##### SUMMARY

The table is barely readable.
##### STEPS TO REPRODUCE

Go to http://docs.ansible.com/ansible/gce_module.html
Scroll down
##### EXPECTED RESULTS

Table columns should be balanced
##### ACTUAL RESULTS

The fourth column is to small to be readable

![screenshot 2016-06-02 at 18 52 50](https://cloud.githubusercontent.com/assets/106790/15753663/8e0659d0-28f4-11e6-8fdc-8c3c8daa221b.png)

**Comment by docschick** [comment]
@jlmitch5 -- this table squishing is happening in the module docs too. i know we've attempted to fix this before, but maybe the way the module docs are pulled in/generated affects the change we've attempted to put in place. anyway, when you have a chance, would you take a look and see if you have any magic to sprinkle over this?

**Comment by dharmabumstead** [comment]
This issue has been fixed. Thanks for helping us make the Ansible docs better!
