### ISSUE TITLE
AttributeError: 'module' object has no attribute 'CURRENT_ENV'

### ISSUE THREAD

**Issue by sree0410** [ansible/ansible#16106]
error stack as below

No handlers could be found for logger "yowsup.stacks.yowstack"
Traceback (most recent call last):
  File "Run.py", line 30, in <module>
    stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())
AttributeError: 'module' object has no attribute 'CURRENT_ENV'

what could be the problem .
please help.
new to yowsup

**Comment by sivel** [comment]
I believe you have opened this issue in the wrong repository.  This is ansible/ansible, not the yowsup repository.
