### ISSUE TITLE
regression: host_vars in inventory_dir not considered

### ISSUE THREAD

**Issue by bitmensch** [ansible/ansible#16117]
##### ISSUE TYPE

Bug Report
##### ANSIBLE VERSION

ansible@devel (commit 273a965d specifically)
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

MacOS 10.11.5
##### SUMMARY

The issue I reported in #12742 (which had been fixed) popped up again this morning. Turns out that the responsible commit is 273a965d.

I discovered this as one of my nightly builds that runs against ansible@devel failed: https://travis-ci.org/goodplay/goodplay/jobs/134945180
##### STEPS TO REPRODUCE

see #12742
##### EXPECTED RESULTS

see #12742
##### ACTUAL RESULTS

see #12742

**Comment by jimi-c** [comment]
@benjixx when I re-run the reproducer I had in #12742, I see the correct output:

```
# ansible-playbook -vv playbooks/test.yml -i inventory/
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: test.yml *************************************************************
1 plays in playbooks/test.yml

PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
task path: /root/testing/12742/mytest/playbooks/test.yml:5
ok: [localhost] => {
    "inventory_group_var": "inventory group var"
}

TASK [debug] *******************************************************************
task path: /root/testing/12742/mytest/playbooks/test.yml:6
ok: [localhost] => {
    "inventory_host_var": "inventory host var"
}

TASK [debug] *******************************************************************
task path: /root/testing/12742/mytest/playbooks/test.yml:7
ok: [localhost] => {
    "playbook_group_var": "playbook group var"
}

TASK [debug] *******************************************************************
task path: /root/testing/12742/mytest/playbooks/test.yml:8
ok: [localhost] => {
    "playbook_host_var": "playbook host var"
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0   
```

Can you share exactly how your test reproduces the problem you're seeing?

**Comment by bitmensch** [comment]
@jimi-c I just tried with your reproducer from #12742 in the same way you did, and it seems: you're right. This works.

But there are strange things going on here. By just slightly changing your example the problem appears again:

```
cat ./inventory/group_vars/all
inventory_group_var: "inventory group var"

cat ./inventory/host_vars/localhost
inventory_host_var: "inventory host var"

cat ./inventory/inv
localhost ansible_connection=local

cat ./playbooks/test.yml
---
- hosts: localhost
  gather_facts: no
  tasks:
  - debug: var=inventory_group_var
  - debug: var=inventory_host_var

ansible-playbook -i inventory/ playbooks/test.yml
PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "inventory_group_var": "inventory group var"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "inventory_host_var": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

Do you have any clue what's happening here?

**Comment by jimi-c** [comment]
This did bisect down to 273a965dcc1e522fcd6637c63be0157a17cff421, so I'll look into why.

**Comment by jimi-c** [comment]
So it looks like this is because I stopped it from saving the host_vars locally in the hosts `.vars` dictionary locally, but we're not properly finding the path from the inventory for the host_vars file.

**Comment by jimi-c** [comment]
I believe I have this fixed, however I want to add some unit tests to make sure we don't run into this again.

**Comment by jimi-c** [comment]
Due to the nature of this bug and the structure of the unit tests, I've been unable to exactly recreate the way this bug occurs, so for now I've just merged in the above patch to fix this. Unfortunately the inventory code is overdue for some cleanups and refactoring (it's the only major chunk of code that wasn't changed much in 2.0+), and as such doesn't have very good unit tests. We'll be addressing that in the future.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by alikins** [comment]
is https://github.com/ansible/ansible/issues/16128 related?

**Comment by jimi-c** [comment]
Yep, and should now be fixed too.

**Comment by bitmensch** [comment]
Latest `ansible@devel` currently makes my build green again. Thanks @jimi-c. Much appreciated.

**Comment by jimi-c** [comment]
@benjixx excellent, thanks for the follow up!
