### ISSUE TITLE
Unable to delegate from windows to linux

### ISSUE THREAD

**Issue by juanjomm** [ansible/ansible#16118]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel c9a5b1c555) last updated 2016/06/02 15:42:56 (GMT +200)
  lib/ansible/modules/core: (detached HEAD ca4365b644) last updated 2016/06/02 15:43:14 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD b0aec50b9a) last updated 2016/06/02 15:43:15 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

Python 2.7.5 (default, Oct 11 2015, 17:47:16)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2

Ansible Configuration:
 ansible_ssh_user: xxxx
 ansible_ssh_pass: xxxxx
 ansible_connection: winrm
 ansible_ssh_port: 5985
```
##### OS / ENVIRONMENT

Ansible running in RHEL 7.2
OS remote is Windows 2008R2 with powershell 4.0
##### SUMMARY

When delegating an action for a windows host to a linux host I get this error:
 FAILED! => {"failed": true, "msg": "ssl: 500 WinRMTransport. [Errno 111] Connection refused"}
##### STEPS TO REPRODUCE

```
Try delegating an action from a windows host to a linux host:
file: main.yml
 - name: 01-EsperarTermineReinicioServidor
   wait_for: port=3389 host="192.168.1.10" delay=10 timeout=600 state=started
   delegate_to: 127.0.0.1
```

##### ACTUAL RESULTS

```
FAILED! => {"failed": true, "msg": "ssl: 500 WinRMTransport. [Errno 111] Connection refused"}

```

**Comment by jhawkesworth** [comment]
Please can you try using 

delegate_to: localhost

or local_action syntax: http://docs.ansible.com/ansible/playbooks_delegation.html#delegation

Also check your inventory to make sure 127.0.0.1 isn't inadvertently appearing in the same group as your windows hosts.

**Comment by juanjomm** [comment]
Thank you for your help.
I tested with the module delegate_to: localhost and local_action syntax,

```
- name: 01-EsperarTermineReinicioServidor
  local_action:
    module: wait_for
    host: "192.168.1.10"
    port: "3389"
    delay: 10
    timeout: 600
    state: started
```

**Inventory groups:**

```
ansible-playbook -i ./inv/invs site.yml --list-hosts

playbook: site.yml

  play #1 (all): BASTIONADO       TAGS: []
    pattern: [u'all']
    hosts (1):
      example.exp.corp
```

The problem still persist
In addition, in our inventory doesn't show the ip 127.0.0.1

**Comment by bcoca** [comment]
how are you setting winrm as the connection for example.exp.corp?

**Comment by juanjomm** [comment]
winrm is configured as follows:

```
PS C:\> winrm get winrm/config
Config
    MaxEnvelopeSizekb = 500
    MaxTimeoutms = 60000
    MaxBatchItems = 32000
    MaxProviderRequests = 4294967295
    Client
        NetworkDelayms = 5000
        URLPrefix = wsman
        AllowUnencrypted = true
        Auth
            Basic = true
            Digest = true
            Kerberos = true
            Negotiate = true
            Certificate = true
            CredSSP = false
        DefaultPorts
            HTTP = 5985
            HTTPS = 5986
        TrustedHosts = ansible0001.unix.corp,127.0.0.1
    Service
        RootSDDL = O:NSG:BAD:P(A;;GA;;;BA)(A;;GR;;;IU)S:P(AU;FA;GA;;;WD)(AU;SA;GXGW;;;WD)
        MaxConcurrentOperations = 4294967295
        MaxConcurrentOperationsPerUser = 1500
        EnumerationTimeoutms = 240000
        MaxConnections = 300
        MaxPacketRetrievalTimeSeconds = 120
        AllowUnencrypted = true
        Auth
            Basic = true
            Kerberos = true
            Negotiate = true
            Certificate = false
            CredSSP = false
            CbtHardeningLevel = Relaxed
        DefaultPorts
            HTTP = 5985
            HTTPS = 5986
        IPv4Filter = *
        IPv6Filter = *
        EnableCompatibilityHttpListener = true
        EnableCompatibilityHttpsListener = false
        CertificateThumbprint
        AllowRemoteAccess = true
    Winrs
        AllowRemoteShellAccess = true
        IdleTimeout = 7200000
        MaxConcurrentUsers = 10
        MaxShellRunTime = 2147483647
        MaxProcessesPerShell = 25
        MaxMemoryPerShellMB = 1024
        MaxShellsPerUser = 30
```

**Comment by juanjomm** [comment]
In the ansible server:

```
---
ansible_ssh_user: administrator
ansible_ssh_pass: xxxxxxxx
ansible_connection: winrm
ansible_ssh_port: 5985
```

**Comment by juanjomm** [comment]
@bcoca
Hi. Do you have any idea that it might be happening? Do you need some kind of additional information?
I've done more testing and I couldn't see that happen.
Can I help you in any way? Please tell me how.

Thank you very much for your help.

**Comment by bcoca** [comment]
"in the ansible server"? i don't know what that means, is this a host/group var file? vars file? inventory? what??

**Comment by juanjomm** [comment]
Sorry, this information is a file located in group_vars. It is called by the site.yml as vars_files.
- site.yml file:

```
---
- name: NEW SERVER
  hosts: "{{hosts|default('all')}}"

  vars_files:
    - group_vars/Wintel-Conection.yml

  vars_prompt:
    - name: "UserDomain"
      prompt: "User"
      private: no

    - name: "PasswordUser"
      prompt: "Password"
      private: yes

  roles:
    - ConfigNewServer
```
- Wintel-Conection.yml file:

```
---
ansible_ssh_user: administrator
ansible_ssh_pass: xxxxxxxx
ansible_connection: winrm
ansible_ssh_port: 5985

```

**Comment by jhawkesworth** [comment]
I haven't tried organizing vars like this, but I suspect the Wintel-Conection.yml is loaded too late to configure the winrm connection.  

So I would try changing things around so that the windows hosts belong to a group which you have created in your inventory and that the group_vars folder contains a file - in fact try changing it so it is organised like the example described here: http://docs.ansible.com/ansible/intro_windows.html#inventory

Please advise if configuring as per the documentation has any effect.  My inventory is organised like this and I am able to delegate to both windows and linux hosts.

**Comment by bcoca** [comment]
that is your issue, you are setting the var globally, which affects ALL hosts, not just the windows one

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by juanjomm** [comment]
@bcoca, @jhawkesworth

Perfect! It works well as you say.
Thank you very much.
