### ISSUE TITLE
python crawl error

### ISSUE THREAD

**Issue by SohnSangHyun** [ansible/ansible#16137]
it's python crawling error
plz tell me detailed...how can i fix it?
![error](https://cloud.githubusercontent.com/assets/18184258/15804579/c1f9d1a8-2b48-11e6-89e9-ef1af94153ad.png)

**Comment by alikins** [comment]
I think this was submitted to the wrong github repo? The code in the screenshot doesn't appear to be ansible related. 

If this is ansible related, please reopen this issue and provide more information, including the information requestion in the issue template.
