### ISSUE TITLE
raw module not working for Cisco Routers

### ISSUE THREAD

**Issue by debugloop** [ansible/ansible#16146]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

None relating to SSH.
##### OS / ENVIRONMENT

A fresh virtual env.
##### SUMMARY

The `raw` Module fails to connect via SSH under unknown circumstances. Executing the debug messages of Ansible directly works though. It works on routers with more modern SSH versions.
##### STEPS TO REPRODUCE

Execute command with the `raw` Module, even consider the `executable` advice from  #16054:

```
naegele@librenms0:~$ ansible all -i some-router.company.net, -m raw -a 'executable="" show int desc' -vvv
No config file found; using defaults
<some-router.company.net> ESTABLISH SSH CONNECTION FOR USER: None
<some-router.company.net> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/naegele/.ansible/cp/ansible-ssh-%h-%p-%r -tt some-router.company.net 'show int desc'
some-router.company.net | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh.",
    "unreachable": true
}
```

Copying the command from above into the shell directly:

```
naegele@librenms0:~$ ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/neuner/.ansible/cp/ansible-ssh-%h-%p-%r -tt some-router.company.net 'show int desc'


Mon Jun  6 12:55:17.543 CEST

Interface          Status      Protocol    Description
--------------------------------------------------------------------------------
Lo0                up          up          ***
<snip>
Te0/1/0/2          admin-down  admin-down
Te0/1/0/3          up          up          ***
```

##### EXPECTED RESULTS

It should work in either case.
##### ACTUAL RESULTS

It only works when working around ansible by pasting the command directly. However, both attemps look the same in the routers log:

```
RP/0/RSP0/CPU0:some-router#RP/0/RSP0/CPU0:Jun  6 13:43:30 CEST:
SSHD_[65888]: %SECURITY-SSHD-4-WARNING_LOGIN : The requested term-type
'screen' is not supported
RP/0/RSP0/CPU0:Jun  6 13:43:31 CEST: SSHD_[65888]:
%SECURITY-SSHD-6-INFO_SUCCESS_COMMAND : Successfully authenticated user
'naegele' from '2001::ffff' on 'vty1'(cipher 'aes128-cbc', mac
'hmac-md5', command 'show int desc')



RP/0/RSP0/CPU0:some-router#RP/0/RSP0/CPU0:Jun  6 13:43:40 CEST:
SSHD_[65888]: %SECURITY-SSHD-4-WARNING_LOGIN : The requested term-type
'screen' is not supported
RP/0/RSP0/CPU0:Jun  6 13:43:40 CEST: SSHD_[65888]:
%SECURITY-SSHD-6-INFO_SUCCESS_COMMAND : Successfully authenticated user
'naegele' from '2001::ffff' on 'vty1'(cipher 'aes128-cbc', mac
'hmac-md5', command 'show int desc')
```

Setting `TERM=vt100` clears the warning from the Cisco's log, but does not help otherwise.

Again, note that it works on a router with a more recent version of sshd.

**Comment by analogbyte** [comment]
Setting `TERM=vt100` clears the warning from the Cisco's log, but does not help otherwise.

**Comment by alikins** [comment]
@bcoca Possibly related to https://github.com/ansible/ansible/pull/16085 ?
(though the failure is different, and this issue seems to depend on router/ssh versions).

**Comment by 9er** [comment]
This is not fixed.

If I run the command in ansible:

```
$ ansible all -i router, -m raw -a 'show int desc' -vvv
Using /etc/ansible/ansible.cfg as config file
<router> ESTABLISH SSH CONNECTION FOR USER: None
<router> SSH: EXEC ssh -q -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/neuner/.ansible/cp/ansible-ssh-%h-%p-%r -tt router 'show int desc'
router | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh.", 
    "unreachable": true
}
```

But when I copy the command and execute it directly, it works just fine:

```
$ ssh -q -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/neuner/.ansible/cp/ansible-ssh-%h-%p-%r -tt router 'show int desc'


Sat Jun 18 19:26:07.065 CEST

Interface          Status      Protocol    Description
--------------------------------------------------------------------------------
Lo0                up          up          Loopback
Lo1                up          up          MPLS
Nu0                up          up          
```

Tested with Ansible 2.1 and ansible-git-2.2.0.19751.1db02df-1 with no difference (not counting the "executable=''" bug)

**Comment by debugloop** [comment]
@bcoca Please reopen this, the issue still persists in the latest git checkout.

**Comment by debugloop** [comment]
@bcoca, @Qalthos, @privateip Should I rereport this? This still is an issue in [v2.1.1.0-0.3.rc3](https://github.com/ansible/ansible/releases/tag/v2.1.1.0-0.3.rc3) and devel too.

Sorry to keep pestering you about this bug getting reopened, but it is kind of a showstopper for ansible within our organization.

**Comment by privateip** [comment]
@analogbyte Is there a reason you have to use the raw module here?  Why not use ios_command module instead as its the more preferred way to run show commands on IOS devices?   

Back to the bug itself, what version of IOS are you seeing this on?

**Comment by debugloop** [comment]
@privateip ios_command is not working either, should I file a report for that additionally? My reasoning was that fixing SSH with the most basic module will probably fix SSH in more complex cases.

The reason for using `raw` over `ios_command` is that it allows for ad hoc commands. As far as I understand ios_command, it is hardly possible to do stuff from the CLI, without having to write a full blown playbook.

**Comment by privateip** [comment]
> ios_command is not working either, should I file a report for that additionally?

Yes

> As far as I understand ios_command, it is hardly possible to do stuff from the CLI, without having to write a full blown playbook.

You can use `ios_command` to "do stuff from the CLI" just as you can with the `raw` module.  Please see [here](https://gist.github.com/privateip/9d86fe6bbca342425c578976343d4801) for an example.

**Comment by 9er** [comment]
@privateip First of all, `ios_command` seems to be broken aswell, or can't be used in this case:

```
router | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh.", 
    "unreachable": true
}
```

Also, we're not talking about IOS boxes here, we're talking about IOS XR (`iosxr_command` is affected aswell of course), but boxes by MRV and other vendors are affected by this aswell.

**Comment by privateip** [comment]
Add `--connection local` to your command string (I forgot I have my set in ansible.cfg as my default, which is why its missing from the Gist

If we are talking about the XR, everything is the same except substitute `ios_command` for `iosxr_command`.  

If we are talking about another platform (MRV) then YMMV as we haven't tested against those devices.
