### ISSUE TITLE
service state doesn't accept 'running' value

### ISSUE THREAD

**Issue by alexxa** [ansible/ansible#16145]
##### ISSUE TYPE

- Bug Report
- Documentation Report
##### ANSIBLE VERSION

```
ansible-playbook 2.2.0
```

git cloned and rpm built on June 3rd
##### OS / ENVIRONMENT

Running Ansible from Fedora 23, and managing Red Hat 7
##### SUMMARY

There is inconsistency between documentation, code and ansible behavior, as well as between documentation and documentation. 

If to check [module_utils/service.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/service.py#L60) , the `running` state for a service is present there.

However, on [service module doc page](http://docs.ansible.com/ansible/service_module.html) there is no `running` value option for a service state.  At the same time, [here](https://github.com/ansible/ansible/blob/devel/docsite/rst/playbooks_intro.rst), [here](https://github.com/ansible/ansible/blob/devel/docsite/rst/playbooks_best_practices.rst), and [here](http://docs.ansible.com/ansible/playbooks_conditionals.html) there are examples with `state=running` syntax. 

on ansible 2.2.0 using `state=running` returns an error:

`{"module_args": {"daemon_reload": false, "enabled": true, "name": "named", "state": "running"}}, "msg": "value of state must be one of: started,stopped,restarted,reloaded, got: running"}`

There was no such problem on ansible 2.1 and 1.9.2
##### STEPS TO REPRODUCE

```
- name: enable and run ntpd
  service: name=ntpd state=running enabled=yes
  tags: ntp

- name: ensure named is running and enabled
  service: name=named state=running enabled=yes
  tags: dns
```

##### EXPECTED RESULTS

TASK [common : enable and run ntpd] ********************************************
ok: [HOST]

TASK [dns : ensure named is running and enabled] *******************************
ok: [HOST]
##### ACTUAL RESULTS

```
fatal: [HOST]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"daemon_reload": false, "enabled": true, "name": "ntpd", "state": "running"}}, "msg": "value of state must be one of: started,stopped,restarted,reloaded, got: running"}

fatal: [HOST]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"daemon_reload": false, "enabled": true, "name": "named", "state": "running"}}, "msg": "value of state must be one of: started,stopped,restarted,reloaded, got: running"}
```

**Comment by alikins** [comment]
Looks like the new systemd service module (lib/ansible/modules/core/system/systemd.py) doesn't expect 'running'  as a possible state:
https://github.com/ansible/ansible-modules-core/blob/devel/system/systemd.py#L224

That area is in flux at the moment in devel/ so that may be broken atm. @bcoca should know more.

**Comment by bcoca** [comment]
fyi, module_utils/service.py is currently unused

**Comment by alexxa** [comment]
@bcoca Would you consider it as a doc BZ then? Since there are `service: name=$service state=running` samples around the doc pages (see the links in the BZ report above).
