### ISSUE TITLE
Get templating code back under control

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1615]
The core "basic" templating code is becoming too self-aware and a source of a lot of churn in the code, and it's becoming relatively hard to read -- and one of the main sections of the code that is no longer easily worked on.

Things started out simple, but over time we have added the ability for the non-Jinja2 templating to use datastructures, and mixed in things to allow for lookup plugins like $FILE and $PIPE, and recursion like $foo{$bar} and also some escaping systems for when periods are in the strings like $hostvars.{127.0.0.1}.foo which are not exactly hashes  but feel like them.   These are all great features but they have built on each other to make the template system hard to maintain.

We don't want to remove our templating capabilities for the next release by any means, but this is long overdo for a cleanup of this code.

Things should be broken down to make them more readable and there should be a common templating class everything goes through, without things calling template_ds in some places, varReplace in others, utils.template in still others. 

In general, there should be a bare minimum of calls to template in both Runner and Playbook code.

Also LOOKUP calls should be cached for the life of the play (only) so they are not evaluated more than once, and they should be evaluated at the first point where enough variables are filled in to make that possible.

A moratorium on new plugin types or other changes should be made until this takes place.

**Comment by mpdehaan** [comment]
Merging this with #1293 -- we should make sure when we overhaul we have a solution for multiple basedirs as well

**Comment by legrostdg** [comment]
Is it possible to know why you closed the issue?

**Comment by mpdehaan** [comment]
I think it's good enough for now.

**Comment by legrostdg** [comment]
Wouldn't it be better to keep the issue open, so that it would be easier to find it (and maybe improve the code)? Maybe you could just add a tag "feature request"?

**Comment by mpdehaan** [comment]
I believe in keeping an issue list of issues someone is actively going to
work on, so no.

The idea of different template engine support really shouldn't have been
combined with that one and I will accept patches that allow a header to
select a different template engine, provided things are made pluggable in a
nice way.
