### ISSUE TITLE
SSH not honoring ansible_user and ansible_port params

### ISSUE THREAD

**Issue by bala-v** [ansible/ansible#16164]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

ansible 2.1.0.0
##### CONFIGURATION

test-mac:ansible$ ansible --version
ansible 2.1.0.0
  config file = /Users/balviswa/<user>/ansible.cfg
  configured module search path = Default w/o overrides
##### OS / ENVIRONMENT

mac osx
##### SUMMARY

ssh to port mapping in virtualbox not connecting to right port or using right user specified in command line or hosts file

test-mac:ansible test$ ansible -vvvv -m ping pdit -ansible_user=test -ansible_port=3333
Using /Users/test/ansible/ansible.cfg as config file
SSH password: 
Loaded callback minimal of type stdout, v2.0
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant on PORT 2222 TO 127.0.0.1
127.0.0.1 | UNREACHABLE! => {
    "changed": false, 
    "msg": "[Errno None] Unable to connect to port 2222 on 127.0.0.1", 
    "unreachable": true
}
##### STEPS TO REPRODUCE
1. Install ansible 2.1.0
2. configure hosts file to use ansible_user=<user>  and ansible_port=<port> to corresponding network mapping in virtual box
3. Test ansible -m ping <vbox>
4. SSH failure
##### EXPECTED RESULTS

I expect ssh to use value provided in ansible_user and ansible_port instead it is using vagrant and port mapping of 2222 from another box.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

This does not look at all like a bug in Ansible as these are not the default values for either, there must be some explicit configuration setting these.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
