### ISSUE TITLE
ansible_service_mgr returns upstart on RHEL 6.5 system

### ISSUE THREAD

**Issue by Nosmoht** [ansible/ansible#16185]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Running Ansible on Archlinux to configure a RHEL 6.5 x86-64 system
##### SUMMARY

Fact ansible_service_mgr is set to upstart instead of sysvinit
##### STEPS TO REPRODUCE

```
ansible all -i inventory/hosts -m setup -a filter=ansible_service_mgr
db-01 | SUCCESS => {
    "ansible_facts": {
        "ansible_service_mgr": "upstart"
    }, 
    "changed": false
}
```

Target system check

```
[oracle@db-01] cat /etc/redhat-release
cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.5 (Santiago)
```

##### EXPECTED RESULTS

ansible_service_mgr should return sysvinit
##### ACTUAL RESULTS

ansible_service_mgr returns upstart

The following change in facts.py solves the issue for me. I just moved the sysvinit part BEFORE the upstart case.

```
636         elif self.facts['system'] == 'Linux':
637             if self._check_systemd():
638                 self.facts['service_mgr'] = 'systemd'
639             elif os.path.exists('/etc/init.d/'):
640                 self.facts['service_mgr'] = 'sysvinit'
641             elif self.module.get_bin_path('initctl') and os.path.exists("/etc/init/"):
642                 self.facts['service_mgr'] = 'upstart'
643             elif os.path.realpath('/sbin/rc') == '/sbin/openrc':
644                 self.facts['service_mgr'] = 'openrc'
```

**Comment by bcoca** [comment]
Your change will result in incorrectly identifying as sysvinit for upstart systems, as /etc/init.d exists on these for backwards compatibility.

Also, upstart is the correct value for RHEL6 systems, that is what they ship with.

**Comment by Nosmoht** [comment]
WoW, after several years of using RHEL 6 i didn't notice that it uses Upstart. 

Thanks for letting me know and sorry for the inconvenience
