### ISSUE TITLE
Running python scripts with command or shell modules ends up adding the cwd into sys.path

### ISSUE THREAD

**Issue by zhaojack** [ansible/ansible#16195]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Issue was observed when the `-i` flag was used with `sudo_flags`, but only because this caused the current working directory of the remote script to become the user's home directory, which was dirty and contained random files like `subprocess.py`
##### OS / ENVIRONMENT

rhel6.6
rhel7.2
##### SUMMARY

When running a python script remotely via ansible's _command_ or _shell_ modules, the script's current working directory gets added to its `sys.path`. If the current working directory contained python files that name-conflicted with modules the script was trying to import, a crash inevitably happens. In our case, a rogue, out-of-date `subprocess.py` located in the running user's home directory caused the script to crash upon attempting to `import multiprocessing`.

We tracked the issue to commit https://github.com/ansible/ansible/commit/16c1f10e18f6b4701c5114c51c8f7f6f0ceb96d4, where it looks like ansible is removing paths from `$PYTHONPATH` that was previously added by ziploader. If this step results in an empty list of paths, `$PYTHONPATH` will still exist in `os.environ` but will be set to an empty string.

If python encounters `$PYTHONPATH` set in the environment but with an empty value, it will add an empty string to `sys.path`, and as a result the running python script will look in its current working directory for modules to import. Note that when `site.py` is invoked, the paths will be canonicalized, so it will show within the script as a full path to the current working directory instead of merely `''`, unless python is invoked with the `-Ss` flags. This behavior is true for at least python 2.7.5.

**Comment by abadger** [comment]
@zhaojack Take a look and see if that pull request fixes things for you?
