### ISSUE TITLE
Prompt for password change (expired password) hangs ansible

### ISSUE THREAD

**Issue by memotype** [ansible/ansible#1619]
My servers are configured to expire user passwords every 90 days. If I'm running ansible against a set of servers using publickey auth, and that user's password is expired on one of those servers, it prompts for the current password, but ansible doesn't recognize this and for some reason will wait forever even if a timeout is specified with -T. Here is what a typical ssh session looks like for a user with an expired password:

$ ssh myuser@some.host
You are required to change your password immediately (password aged)
Last login: Tue Nov 13 18:41:48 2012 from local.ip
Changing password for myuser
(current) UNIX password: [^C]
Connection to some.host closed.

My biggest concern is the lack of a timeout here. I don't really expect ansible to recognize every conceivable prompt when logging in, but it would be nice if it would at least time out and continue through the list of servers.

**Comment by mpdehaan** [comment]
It has a timeout, it's just quite long.

I'd suggest using keys and not passwords.

**Comment by memotype** [comment]
I am using keys, but in this case, even with keys, if the password is
expired it prompts you to change your password. And I don't think the
timeout applies here, I set -T to 5 (as in 5 seconds) and waited 10 minutes.

On Tue, Nov 13, 2012 at 7:28 PM, Michael DeHaan notifications@github.comwrote:

> It has a timeout, it's just quite long.
> 
> I'd suggest using keys and not passwords.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/1619#issuecomment-10350298.

## 

Isaac Freeman
memotype (at) gmail.com

"Few people are capable of expressing with
equanimity opinions that differ from the
prejudices of their social environment. Most
people are even incapable of forming such
opinions." -- Albert Einstein

**Comment by mpdehaan** [comment]
what connection type ?

-- Michael

**Comment by memotype** [comment]
Both the default paraminko and the ssh connection type.

On Wed, Nov 14, 2012 at 7:46 AM, Michael DeHaan notifications@github.comwrote:

> what connection type ?
> 
> -- Michael
> 
> On Nov 13, 2012, at 11:26 PM, memotype notifications@github.com wrote:
> 
> > I am using keys, but in this case, even with keys, if the password is
> > expired it prompts you to change your password. And I don't think the
> > timeout applies here, I set -T to 5 (as in 5 seconds) and waited 10
> > minutes.
> > 
> > On Tue, Nov 13, 2012 at 7:28 PM, Michael DeHaan <
> > notifications@github.com>wrote:
> > 
> > > It has a timeout, it's just quite long.
> > > 
> > > I'd suggest using keys and not passwords.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/ansible/ansible/issues/1619#issuecomment-10350298>.
> > 
> > ## 
> > 
> > Isaac Freeman
> > memotype (at) gmail.com
> > 
> > "Few people are capable of expressing with
> > equanimity opinions that differ from the
> > prejudices of their social environment. Most
> > people are even incapable of forming such
> > opinions." -- Albert Einstein
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/1619#issuecomment-10364828.

## 

Isaac Freeman
memotype (at) gmail.com

"Few people are capable of expressing with
equanimity opinions that differ from the
prejudices of their social environment. Most
people are even incapable of forming such
opinions." -- Albert Einstein

**Comment by killerwhile** [comment]
anything new on this one? Looks like this "issue" still occurs.

**Comment by felixlslam** [comment]
Hi, 
We are using Ansible 2.0 but still have this issue. 
Note that we have been using SSH key for connection already, and actually ansible can establish connection into box but since the box prompts for a password update, ansible seems have no way to timeout in that situation.

**Comment by memotype** [comment]
Just FYI, I'm no longer at the company that was using Ansible, so I'm unsubscribing from this thread and won't be able to help or answer any questions. Good luck figuring it out though.

**Comment by marcowork** [comment]
issue still exists. any news here?

**Comment by jamescassell** [comment]
Issue still exists.  I don't really expect a solution.

**Comment by quangvnm** [comment]
Hi, I also searched for a magic solution for this without success and fall to this issue.
In the mean time, I've found out a hacky way to do this so this is for anyone like me who has encountered the password time out and want to check for:
- password expired
- timeout for password expired
- or to change expired password,

My following task works quite well:

```yml
- name: Set password if expired
  delegate_to: 127.0.0.1
  become: no
  expect:
    command: ssh {{ ansible_ssh_common_args }} {{ ansible_user }}@{{ inventory_hostname }}
    timeout: 10
    responses:
      "password:":
        # we couldn't keep the same old password
        - "{{ ansible_ssh_pass_old }}"
        - "{{ ansible_ssh_pass }}"
        - "{{ ansible_ssh_pass }}"
      # if succesfully login then quit
      "\\~\\]\\$": exit
  register: status
  changed_when: "'authentication tokens updated successfully' in status.stdout"
```

I hope that helps

**Comment by xnorma** [comment]
@quangvnm bravo!
