### ISSUE TITLE
Variables set in role dependencies show different behavior in the parent role based on the Ansible version

### ISSUE THREAD

**Issue by justinlocsei** [ansible/ansible#16209]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Mac OS 10.11 for the control machine, CentOS 6.8 for the target
##### SUMMARY

When a parent role includes another role as a dependency, and overrides the child role's default values using parameters, variables (as defined in `vars/` files) in that child role that reference the defaults are calculated properly in the scope of that role, but when those variables are accessed in the parent role, they are calculated using the child role's defaults.  I see this behavior in Ansible 2.1, but not in 2.0.2, where the parent role is able to view the calculated value produced by the last inclusion of the dependent role.
##### STEPS TO REPRODUCE

**roles/child/defaults/main.yml**

```
child_name: default
```

**roles/child/tasks/main.yml**

```
- debug: msg={{ child_dir }}
```

**roles/child/vars/main.yml**

```
child_dir: /tmp/{{ child_name }}
```

**roles/parent/meta/main.yml**

```
dependencies:
  - role: child
    child_name: custom
```

**roles/parent/tasks/main.yml**

```
- debug: msg={{ child_dir }}
```

**playbook.yml**

```
- hosts: localhost
  gather_facts: no
  roles:
    - role: parent
```
##### EXPECTED RESULTS

Running the above playbook with Ansible 2.0.2 (installed via `pip`) produced the following:

```
PLAY [localhost] ***************************************************************

TASK [child : debug] ***********************************************************
ok: [localhost] => {
    "msg": "/tmp/custom"
}

TASK [parent : debug] **********************************************************
ok: [localhost] => {
    "msg": "/tmp/custom"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

Running the same playbook with Ansible 2.1 (also installed via `pip`) produced the following:

```
PLAY [localhost] ***************************************************************

TASK [child : debug] ***********************************************************
ok: [localhost] => {
    "msg": "/tmp/custom"
}

TASK [parent : debug] **********************************************************
ok: [localhost] => {
    "msg": "/tmp/default"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

I'm mainly curious which behavior is intended.  I would expect the 2.0 behavior to be correct, since the Ansible docs include the line "Generally speaking, variables set in one role are available to others."  However, if this behavior was incorrect and 2.1 fixed this bug, I'm curious as to how one would go about accessing variables defined in included roles.  If I'm also just using Ansible in manner that is completely contrary to its philosophy, I'd be happy to be pointed in a more constructive direction as well.

**Comment by jimi-c** [comment]
Per my comment here: https://github.com/ansible/ansible/issues/16320#issuecomment-227912789, this should be resolved and will be included in 2.1.1.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
