### ISSUE TITLE
Addition of filter to quote string members in list

### ISSUE THREAD

**Issue by dspruell** [ansible/ansible#16221]
##### ISSUE TYPE
- Feature Idea
##### SUMMARY

Wanted to propose a filter addition - concept is to return a list/array with member strings surrounded by quotes. Either double quotes (default) or single quotes can be used. Sample filter function shown at https://gist.github.com/dspruell/d12506b7332789f726ba487636b36c74.

**Comment by bcoca** [comment]
you can chain the existing quote and map filters to do this
