### ISSUE TITLE
Skip prompt for a vars_prompt that has already been passed in by --extra-vars ( -e)

### ISSUE THREAD

**Issue by progre55** [ansible/ansible#1622]
It would be great if, instead of waiting for the prompt in the vars_prompt section, you can just pass in the var from the command line and run a playbook silently.

**Comment by mpdehaan** [comment]
--extra-vars does exactly this.

--extra-vars="asdf=1234 foo=bar" 

etc

**Comment by progre55** [comment]
Not really.
For instance, if you have a playbook with:

vars_prompt:
- name: "var1"
   prompt: "Enter var1"
   private: False

and run your playbook as follows:

ansible-playbook -e "var1=value" playbook.yml

you still get prompted for var1. Or am I missing anything here?
Using the latest development branch.

**Comment by mpdehaan** [comment]
Ah, now I understand.

It is not presently true that vars_prompt will only prompt for values it does not already have.

I can see this being useful, provided it doesn't end up breaking some other behaviors (but I can't see what those would be).

**Comment by mpdehaan** [comment]
we're past the 0.9 feature freeze so putting this in the 1.0 bucket.

This does not mean anyone is going to work on it, so if you would like to submit a patch, please do!

**Comment by progre55** [comment]
I would love to, but being a java developer, I'm pretty far from being able to submit python patches :)

**Comment by mpdehaan** [comment]
Ok, leaving this open as someone may still pick this up.   It should be reasonably trivial.

**Comment by steverweber** [comment]
I think it would be nice to include vars defined in groups, hosts not just extra.
Thoughts?
