### ISSUE TITLE
Unprivileged become on HP-UX/UNIX does not work

### ISSUE THREAD

**Issue by jokurz** [ansible/ansible#16249]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

remote_user = ansible
##### OS / ENVIRONMENT

Ansible Host: SUSE Linux Enterprise Server 12 SP1
Managed Node: HP-UX B.11.31 U ia64
##### SUMMARY

Executing a play task with `become`on HP-UX fails with following error message:

```
[WARNING]: Using world-readable permissions for temporary files Ansible needs to create when becoming an unprivileged user which may be insecure. For information on securing this, see
https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user

fatal: [host]: FAILED! => {"failed": true, "msg": "Failed to set file mode on remote files (rc: 1, err: chmod: can't traverse /tmp/ansible-tmp-1465816244.81-217081167531834/\n)"
```

This is due to the fact that a `chown` on HP-UX (probably all UNIX systems) behaves different as on Linux:
- Linux: Executing `chown user2 file` as unprivileged `user1` will fail
- HP-UX: Executing `chown user2 file` as unprivileged `user1` will **not** fail

In https://github.com/ansible/ansible/blob/2bf2e0fdfdb7293e28e3bb0543b2d0d14a65169f/lib/ansible/plugins/action/__init__.py#L296 you can see that ansible expects that a `chown` will fail in case it is executed by a unprivileged user.
##### STEPS TO REPRODUCE

Example Playbook

```
- name: Privilege Escalation on HP-UX
  hosts: all

  tasks:
    - name: test
      command: whoami
      become_user: user1
```
##### POSSIBLE SOLUTION
1. Try `_remote_set_user_facl` first
2. If it fails: try `_remote_chmod`
3. If it fails: raise AnsibeError
4. If it works: try `_remote_chown`
   ...

**Comment by abadger** [comment]
By not fail you mean it returns exit code 0 but does nothing?

**Comment by abadger** [comment]
I don't believe the sequence you describe as a possible solution will work.  Trying facls first should be okay but _remote_chmod needs to be the last thing tried (as it is insecure) and using chown after chmod succeeded would have no additional affect.

Maybe we can do this:
1. Try _remote_set_user_facl
2. If it fails: try _remote_chown
3. If that succeeds, stat the file to see who the owner is
4. If _remote_chown failed or the owner is not the new owner: _remote_chmod

**Comment by abadger** [comment]
I'd like to avoid the remote stat if there's another choice as it's another ssh connection to execute that which may take a while.  Can you give me more information about chown's behaviour here?

**Comment by jokurz** [comment]
The chown on HP-UX does work:

```
host1:(/root/home/user1/test)(user1)#touch test
host1:(/root/home/user1/test)(user1)#chown user2 test
host1:(/root/home/user1/test)(user1)#ll test
-rw-r-----   1 user2     users    0 Jun 13 16:10 test
```

Afterwards the file is no longer accessible by 'user1'. Due to that it would make sense to 'chmod' the file on HP-UX first. I cannot comment if all UNIX systems handle this as on HP-UX. AIX seems to be not but on Solaris it is the same behavior.

**Comment by abadger** [comment]
As stated previously, chmod'ing the file is wrong.  It's a chmod a+r which makes any sensitive information in the file readable by other users on the target box.

**Comment by abadger** [comment]
Hmmmm..... I think I see what you're looking at -- there's a chmod for execute permissions that happens after the chown.  I think we can move that to happen before chown is tried.  However, the error message that you're reporting doesn't match up with that chmod.  It matches up with the chmod in the path the code takes if chown fails.  We can't move that chmod to the front as it's the insecure fallback that I was talking about earlier.

Maybe you tried this a few times and the error message is from a different run than the one where the chown worked unexpectedly (to the code) and made the initial chmod fail?

**Comment by bcoca** [comment]
Most Unix systems removed the ability of non privileged users to assign a file to another user as this is a security risk, that is why the test works for most modern Unicies.

The code has many complex interactions, this is not something we can change lightly,  I'm not sure how we can support HP-UX in this case, we need to check some alternatives and then thoroughly test them.

**Comment by elotje** [comment]
The chown on HP-UX does actually work:
```
host1:(/root/home/user1/test)(user1)#touch test
host1:(/root/home/user1/test)(user1)#chown user2 test
host1:(/root/home/user1/test)(user1)#ll test
-rw-r-----   1 user2     users    0 Jun 13 16:10 test
```
Afterwards the file is no longer accessible by `user`'. Due to that it would make sense to `chmod` the file on HP-UX first. I cannot comment if all UNIX systems handle this like HP-UX. AIX seems to be not but on Solaris it is the same behavior. Seems not to be that easy to support all those dinos...

On HP-UX there seems to be a possibility to restrict users/groups to execute chown:
http://www.unixguide.net/hp/faq/5.1.1.shtml
This would force the same behavior as on Linux.

**Comment by jokurz** [comment]
Yes, you are right. The task fails because of the following line (as the previous `chown` was successfully although ansible expected it to fail):

```
res = self._remote_chmod('u+x', remote_path, recursive=recursive)
```

(https://github.com/ansible/ansible/blob/2bf2e0fdfdb7293e28e3bb0543b2d0d14a65169f/lib/ansible/plugins/action/__init__.py#L347.
As you can see it is a `u+x` and not a `a+r`. Maybe the following approach is acceptable:
- Try `_remote_set_user_facl`
- If it fails:
  - If executable: `_remote_chmod u+x`
  - `_remote_chown`
  - If it fails and `C.ALLOW_WORLD_READABLE_TMPFILES`: 
    - `_remot_chown a+r`
