### ISSUE TITLE
Is it possible to generate Inventory from CMDB (Configuration Management Database)

### ISSUE THREAD

**Issue by raghavayamsani** [ansible/ansible#16246]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

ansible-1.9.4
##### OS / ENVIRONMENT

Redhat 6.5
##### SUMMARY

I'am planning to generate dynamic inventory file from configuration management database system. Is it possible to write a script,so that when i run ansible playbook it should pick up inventory from database.
If it is successful then i have a plan of generating the variables from database itself.

Can any one answer is it possible with the ansible or not?

**Comment by talonx** [comment]
This should ideally be in the mailing list.

**Comment by sivel** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
