### ISSUE TITLE
Using $FILE() when the file contains quotes

### ISSUE THREAD

**Issue by sterat** [ansible/ansible#1624]
I am deploying a ssh key that contains double quote characters. These characters are removed and do not
appear in the deployed key.

Eg I have a key:

```
from="example" ssh-rsa AAAAB3...
```

but it is deployed as:

```
from=example ssh-rsa AAAAB3...
```

That is with the anisible action:

```
authorized_key: user=user1 key="$FILE(/path/to/key)"
```

I found that if I triple quote the key argument, then the key is transferred correctly.
Although that works for me, I think that is too much leakage of python
syntax into the script.  Better would be if $FILE() would provide
whatever quoting was required.

**Comment by mpdehaan** [comment]
FILE should not provide whatever quoting is required, but I do agree that
quotes around the argument to KEY should be sufficient.

It seems if it's not the problem is likely with the authorized_key module
splitting incorrectly.

**Comment by dhozac** [comment]
You have to use the correct type of quotes. If you want to use a file that contains " and have them be preserved, then you have to use single quotes to contain it. "contents="blah"" will indeed parse as contents=blah, as your quotes cancel eachother out. 'contents="blah"' on the other hand, should be fine.

**Comment by mpdehaan** [comment]
good catch, yeah, I agree.  It's not super intuitive.   We should probably upgrade the docs around this example.
