### ISSUE TITLE
[Enhancement] Restrict the scope of variables pulled in from the roles/<role-name/vars section of a role only to that role

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#16250]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

From Ansible [documentation](http://docs.ansible.com/ansible/playbooks_variables.html#variable-scopes):

```
Generally speaking, variables set in one role are available to others. This means if you have a roles/common/vars/main.yml you can set variables in there and make use of them in other roles and elsewhere in your playbook...
```

I find that this:
- is confusing because unnecessary
- lays the ground for potential issues between identically named variables between different roles which can be written by different teams

So my proposal is very simple: **restrict the scope of all variables which are pulled in from the role's vars folder to that role only**.

People needing access to more general variables have other ways to achieve that:
- group_vars
- host_vars
- inventory
- play-defined structures
- ...

The same remark can be made about variables defined specifically within plays: they should live only within it.

**Comment by bcoca** [comment]
Done, use ANSIBLE_PRIVATE_ROLE_VARS env var or set private_role_vars in ansible.cfg
