### ISSUE TITLE
IOS NetworkModule never calls disconnect()

### ISSUE THREAD

**Issue by pstch** [ansible/ansible#16282]
I found no open/closed issues referring to `NetworkModule`, or `disconnect()` methods.
##### ISSUE TYPE
- Bug Report (low-importance)
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

Code is identical in `devel` branch.
##### REFERRED CODE

https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/ios.py#L154
##### SUMMARY

Although the `NetworkModule` class in `ansible.module_utils.ios` defines a `disconnect` method it is never called in the current code. Additionally, if it was called, it would raise a `NameError` as the `Cli` class does not define a `close` method. 

It seems that this code was inspired from the JunOS utility module, which does call its `disconnect` method, by wrapping all calls to `fail_*` in a `_fail` method that calls `disconnect`

Although this may seem easy to fix, I don't feel familiar enough with Ansible's object-oriented module architecture. I'm still pretty new to all of this, and I noticed this while reading the IOS module in an attempt to write a Mikrotik configuration module.

**Comment by Qalthos** [comment]
So you have it mostly correct, IOS' NetworkModule does not call disconnect, but it is not intended to directly. The code in module_utils is not the modules themselves, but common code for modules in ansible/ansible-modules-core or ansible/ansible-modules-extra (or your own modules) to use. If you have a need for a connection to disconnect at some point, it would be put in there

(ex https://github.com/ansible/ansible-modules-core/blob/devel/network/ios/ios_command.py)

All that said, it does look like disconnect is unused throughout IOS' module code, and in fact broken. These two facts are likely related. Happily, thanks to some of the changes made in 2.1 there is a bit of refactoring going on in the network modules for greater code reuse (#16158 does this for EOS, the rest should follow reasonably quickly) which should at least ensure less broken copy-pasted code.

As for actually calling disconnect, I'm not all that sure that it really is necessary to be called. JunOS does it as part of its failure handling for NETCONF transports to make sure the jnpr library cleans up after itself properly, but we have no such need on the simpler devices. Modules certainly could be more explicit about closing connections, but ultimately it is up to the module author to use what tools are made available.
