### ISSUE TITLE
synchronize module does not verify arguments properly

### ISSUE THREAD

**Issue by aptituz** [ansible/ansible#16301]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### OS / ENVIRONMENT

CentOS 7
##### SUMMARY

When creating a synchronize task with mode pull and wrongly named or missing src argument their is no  proper error message.
##### STEPS TO REPRODUCE

1) Create a playbook with a synchronize task with wrong arguments
2) Run this playbook

Example task:

```
- name: pull letsencrypt certificates
  synchronize:
    source: /etc/letsencrypt.sh/assembled
    mode: pull
    dest: /data/ansible/ssl_certs/assembled
```
##### EXPECTED RESULTS

A message indicating that src argument is missing (since it's wrongly named)
(or no message at all, because source could be an alias after all)
##### ACTUAL RESULTS

An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 124, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 446, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/synchronize.py", line 288, in run
    dest = self._process_origin(dest_host, dest, user)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/synchronize.py", line 71, in _process_origin
    if ':' not in path and not path.startswith('/'):
TypeError: argument of type 'NoneType' is not iterable

**Comment by abadger** [comment]
Thaks for reporting htis @aptituz #16308 should fix this issue for you.  I've merged it into devel and the  stable-2.1 branch for our next release.
