### ISSUE TITLE
synchronize unnecessary fails to run when using docker connection

### ISSUE THREAD

**Issue by redbaron** [ansible/ansible#16306]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible --version
ansible 2.1.0.0
  config file = /home/rossmohax/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Linux
##### SUMMARY

synchronize unnecessary fails to run when using docker connection with an error:

```
{"changed": false, "failed": true, "msg": "synchronize uses rsync to function. rsync needs to connect to the remote host via ssh or a direct filesystem copy. This remote host is being accessed via docker instead so it cannot work."}
```

Which is simply wrong, here is the prove:
Copy into docker container without ssh:

```
rsync -a --rsh='docker exec -i' /tmp/myfiles c65e6a210eb:/tmp/
```

Copy from docker container without ssh:

```
rsync -a --rsh='docker exec -i' c65e6a210eb:/tmp/ /tmp/myfiles
```

where `c65e6a210eb` is a value used in inventory:

```
[targets]
container connection=docker ansible_host=c65e6a210eb
```

**Comment by tomsun** [comment]
nice solution, +1 for somehow adding synchronize support

https://github.com/ansible/ansible/blob/4ea5f77062f427387d8c0486551e64e38072a8eb/lib/ansible/plugins/action/synchronize.py#L172-L177

**Comment by tima** [comment]
@redbaron and @tomsun: Thanks for pointing this out. Please file a PR against this issue with your fix.

**Comment by jctanner** [comment]
As this is not yet implemented, I am marking it as a feature idea.

**Comment by winggundamth** [comment]
Ping @chouseknecht in case maybe you have an idea for this.

**Comment by chouseknecht** [comment]
It's on the list of things to do over at [ansible/ansible-container](https://github.com/ansible/ansible-container/issues/226)
