### ISSUE TITLE
-vvvv Ouput for Ansible-Vault

### ISSUE THREAD

**Issue by arkag** [ansible/ansible#16327]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/aroberts/git/ansible-playbooks/ansible.cfg
  configured module search path = ['/usr/share/ansible']
```
##### CONFIGURATION

I don't think that this is related to the issue, nor am I the maintainer of our companies ansible config. If necessary I can get what has been changed, but I don't forsee this being an issue.
##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

-vvvv doesn't produce helpful output for decrypting ansible-vault files. 
##### STEPS TO REPRODUCE

Run playbook with different vaulted files, requiring different vault passwords, it will fail. Running with -vvvv isn't helpful at all; it should be.
##### EXPECTED RESULTS

Useful output for what file failed to decrypt
##### ACTUAL RESULTS

```
$ ansible-playbook -i inventory/development -e env=development --diff --force-handlers -e "hostlist=host use_samba=False env=development" playbook.yml --ask-vault-pass -vvvv
Using /home/aroberts/git/ansible-playbooks/ansible.cfg as config file
Vault password: 
ERROR! Decryption failed
```

**Comment by cwre** [comment]
Thank you!
