### ISSUE TITLE
Playbook will only run if "connection=local"

### ISSUE THREAD

**Issue by alyazmo** [ansible/ansible#16353]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

[defaults]
host_key_checking=False
inventory      = /etc/ansible/hosts
# library        = /usr/share/my_modules/
# remote_tmp     = $HOME/.ansible/tmp
# local_tmp      = $HOME/.ansible/tmp
# forks          = 5
# poll_interval  = 15
# sudo_user      = root
# ask_sudo_pass = True
# ask_pass      = True
# transport      = smart
# remote_port    = 22
# module_lang    = C
# module_set_locale = True

[ssh_connection]
scp_if_ssh = True
##### OS / ENVIRONMENT

I am running Ansible on Ubuntu to a cisco router

cisco router image
isr4300-universalk9.03.14.00.S.155-1.S-std.SPA.bin
##### SUMMARY

Here is the error output that I am getting

 FAILED! => {"failed": true, "msg": "failed to transfer file to \"`echo $HOME/.ansible/tmp/ansible-tmp-1466194298.17-4676314486814`\" ) && sleep 0'\"/setup:\n\nAdministratively disabled.\nConnection to 164.55.151.223 closed by remote host.\r\n"}

I have put the SSH RSA key on the router and verified it by doing an ssh session and was able to connect without having to put in the password. However, I still need to put in a password to get to enable mode. I am not too sure if getting into enable mode is part of this error.
##### STEPS TO REPRODUCE

```

---
- name: Show OS type
  hosts: testhosts
  #connection: local
  #gather_facts: yes

  tasks:
  - name: Show operating system
    debug: msg="{{ansible_os_family}}"
...

```

##### EXPECTED RESULTS

now the playbook works if I set the connection to local. I am not too sure if that is needed with netops. 
##### ACTUAL RESULTS

```

```

**Comment by jctanner** [comment]
@alyazmo 
- Are you able to scp files to '$HOME/.ansible/tmp' on the router?
- Have you tried changing the remote temp dir?
- Have you tried using the default mode of sftp instead of scp?

**Comment by alyazmo** [comment]
@jctanner 

thank you for your prompt response. 
- when I use sftp I get an ssh:error that the data could not be sent over ssh
- I was able to scp on the router

**Comment by bcoca** [comment]
you NEED `gather_facts=False`, otherwise ansible will try to login to the router and run python

**Comment by alyazmo** [comment]
@bcoca 

Thank you very much that did the trick

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
