### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by simfarm** [ansible/ansible#16372]
##### ISSUE TYPE

- Bug Report
- Feature Idea
- Documentation Report
##### ANSIBLE VERSION

```

```
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment]
soo, unicode related, but can you fill in the template?

**Comment by simfarm** [comment]
A total goof on my part, apologies bcoca.

Real issue here: https://github.com/ansible/ansible/issues/16373.
