### ISSUE TITLE
ec2_create module should allow tags

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#1637]
I'm experimenting with @skvidal's `ec2_create` module. 

It would be great if support for adding tags could be provided: the euca2tools support them:

```
euca-create-tags i-xxxxxx --tag JP=ok
```

whereupon `ec2.py` automatically lists them:

``` json

  "tag_JP_ok": [
    "ec2-50-1.*compute-1.amazonaws.com"
  ], 
```

**Comment by mpdehaan** [comment]
Best to discuss on list vs filing tickets, less people read these...

-- Michael

**Comment by arrfab** [comment]
Well, because the ansible ec2 module just uses the euca2ools package tools in the background, everything that those tools can do can be integrated in the ec2 module i guess .. Not a python master here though :-)

**Comment by skvidal** [comment]
I don't think a one-to-one feature parity withe euca2ools makes sense. tags is not unreasonable - but there is a giant sheaf of options that the various euca2ools support - at some point it will be more and more onerous to maintain compat.

**Comment by mpdehaan** [comment]
uses boto now so I imagine this may already be closed, if not, contributions are welcome
