### ISSUE TITLE
Python 2.7 don't come by default in Ubuntu 16.04 LTS Server and Cloud Edition

### ISSUE THREAD

**Issue by ysolis** [ansible/ansible#16388]
- With remote clients running with Ubuntu 16.04 LTS server and cloud editions, Python 2.7 don't come installed by default if i try to run Ansible, when try to connect to new servers installed, Ansible fails.

**Comment by sivel** [comment]
This is something we are working towards, however for the near future, python 2 will still be a requirement for remote target servers.

For the Ansible 2.2 release we are working towards getting ansible to run (controller side) using python3.  Some modules will likely support python3 for Ansible 2.3, with the potential for full support for python 3 on the target side in Ansible 2.4.

The Ansible 2.2 [Roadmap](https://github.com/ansible/ansible/blob/devel/docsite/rst/roadmap/ROADMAP_2_2.rst) has some more information around this.

If you have further questions please stop by IRC or the mailing list:
- IRC: #ansible on irc.freenode.net
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
