### ISSUE TITLE
Consul not on Localhost

### ISSUE THREAD

**Issue by westsouthnight** [ansible/ansible#16398]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

2.2.0
##### OS / ENVIRONMENT

MAC OS X
##### SUMMARY

```
self.agent_url = 'http://localhost:8500'
if os.getenv('ANSIBLE_CONSUL_URL') is not None:
    self.agent_url = os.environ['ANSIBLE_CONSUL_URL']
```
##### STEPS TO REPRODUCE
1. Try to set ANSIBLE_CONSUL_URL Envoronment variable to target host any availible way (ansible, hands, export, etc)
2. Run playbook on hosts where you use not binded to localhost consul

example:

```
- name: Fact gathering swarm-masters
  hosts: consul-servers
  tasks: []
  tags: [get-facts, always]

- name: swarm network playbook
  become: true 
  hosts: consul-servers
  vars:
    ansible_consul_url: http://{{ ansible_default_ipv4['address'] }}:8500
  tasks:
    - name: Command
      shell: 'echo $ANSIBLE_CONSUL_URL'
      register: command_result
      environment:
        ANSIBLE_CONSUL_URL: "{{ ansible_consul_url }}"
    - name: Debug Command 
      debug:
        msg: shell_result is {{ command_result.stdout }}
    - name: Command Consul
      shell: echo "{{ item }}"
      with_consul_kv: 
          - 'kv/some_kv_path_in_consul'
      environment:
        ansilbe_consul_url: "{{ ansible_consul_url }}"
      register: consul_result
```
##### EXPECTED RESULTS

ansible consul_kv.py execute

```
self.agent_url = 'http://localhost:8500'
if os.getenv('ANSIBLE_CONSUL_URL') is not None:
    self.agent_url = os.environ['ANSIBLE_CONSUL_URL']
```

and get ANSIBLE_CONSUL_URL Environment Variable,

next go execute on consul url - ansible_consul_url: http://{{ ansible_default_ipv4['address'] }}:8500
##### ACTUAL RESULTS

Every time execute start on localhost

```
fatal: [consul1.host.com]: FAILED! => {"failed": true, "msg": "Error locating 'kv/some_kv_path_in_consul' in kv store. Error was HTTPConnectionPool(host='localhost', port=8500): Max retries exceeded with url: kv/some_kv_path_in_consul (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x106648f90>: Failed to establish a new connection: [Errno 61] Connection refused',))"}
fatal: [consul2.host.com]: FAILED! => {"failed": true, "msg": "Error locating 'kv/some_kv_path_in_consul' in kv store. Error was HTTPConnectionPool(host='localhost', port=8500): Max retries exceeded with url: kv/some_kv_path_in_consul (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x106648f90>: Failed to establish a new connection: [Errno 61] Connection refused',))"}
fatal: [consul3.host.com]: FAILED! => {"failed": true, "msg": "Error locating 'kv/some_kv_path_in_consul' in kv store. Error was HTTPConnectionPool(host='localhost', port=8500): Max retries exceeded with url: kv/some_kv_path_in_consul (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x106648f90>: Failed to establish a new connection: [Errno 61] Connection refused',))"}
```

**Comment by sivel** [comment]
`ANSIBLE_CONSUL_URL` needs to be set outside of Ansible itself, in the shell where you spawn Ansible from.  Such as:

```
ANSIBLE_CONSUL_URL=http://localhost:8500 ansible-playbook ...
```

The consul connection will be made from the controller machine and cannot currently target multiple consul servers.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by westsouthnight** [comment]
@sivel Thanks - i'm understand what you mean and go to try! @bcoca Thanks for your patience me ;)
