### ISSUE TITLE
Timeout over all modules specified in tasks.

### ISSUE THREAD

**Issue by brackendawson** [ansible/ansible#16397]
Possibly related to #11551
##### ISSUE TYPE

- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

No cfg file.
##### OS / ENVIRONMENT

Linux
##### SUMMARY

When a module fails, 'until' give us a nice re-try machanism. But if a module hangs for a really long time, or forever. We're stuck. It would be nice if there was a timeout around the module in a task. eg:

```

---

- name: Some task that might hang like scp
  copy: src=/some/file dest=/some/location
  timeout: 300
  register: result
  until: result.status_code == 0
  retries: 3
```
##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS

'timeout' key in task that stops the module if the timeout has elapsed.
##### ACTUAL RESULTS

```

```

**Comment by jctanner** [comment]
@brackendawson we have this feature in the form of async. The integer value after the async: keyword sets the max runtime and will kill the module if exceeded.

http://docs.ansible.com/ansible/playbooks_async.html

**Comment by brackendawson** [comment]
I did explore that sadly 'async' can't be combined with 'until'. If 'until' could be used in 'block', that would also solve my original problem.

**Comment by adragoset** [comment]
Why was this closed. Async tasks will not retry after the async timeout with until so using async is not a valid method of achieving this behavior. All modules should be capable of being timed out and then retried.  This is necessary behavior for any task that will not fail out on it's own.
