### ISSUE TITLE
support reading ~/.ssh/config file

### ISSUE THREAD

**Issue by laroche** [ansible/ansible#164]
paramiko has a helper class SSHConfig() which can read in ~/.ssh/config.
This might be helpful if special configuration is done to hop to a second
host, hardcode ports or other special configuration, so that the config does
not need to get duplicated for ansible.

best regards,

Florian La Roche

**Comment by mpdehaan** [comment]
We're quite interested in getting some basic bastion host support going... wasn't aware paramiko could do that easily.

something you might be interested in working on?

**Comment by cocoy** [comment]
hmm..would you mind if i take this ticket? :)

**Comment by mpdehaan** [comment]
excellent, all yours.

**Comment by mpdehaan** [comment]
included in pull request, see email to list

**Comment by FlorianHeigl** [comment]
Jump host, not bastion host? 
And god knows which "email to list?"  ;)

**Comment by bcoca** [comment]
btw, if you use -c ssh, it supports the usage of .ssh/config, might still be nice to add it to paramiko

**Comment by mpdehaan** [comment]
So yeah that was a year ago.   The paramiko "read the SSH config stuff" was in early conflict with the various way the users options worked.

I'm open to attempts to resurrect in the way that the SSH module works now, which is to allow ansible to still override it.

I think in the earlier incarnations it might not have, which was I think the source for confusion.
