### ISSUE TITLE
Module azure_rm_storageaccount throws error

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#16406]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

2.2.0
##### SUMMARY

The azure_rm_storageaccount module throws an error. As far as I can see, it's related to azure_rm_common which is why I'm opening the issue here.
##### STEPS TO REPRODUCE

Use the example to create a storage account
##### EXPECTED RESULTS

Success
##### ACTUAL RESULTS

Ansible chokes on:

```
/tmp/ansible_Sfa9X3/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 594, in storage_client\nNameError: global name 'StorageManagementClientConfiguration' is not defined'
```

**Comment by abadger** [comment]
Tentatively tagging this an easyfix.  It looks like the variable that holds the StorageManagementClientConfiguration() instance is never used so it might be fine to simply remove that line.

**Comment by nitzmahone** [comment]
Yep, this is another place where the intra-RC changes to the azure python SDK hosed us... (remind me not to ship modules that rely on unreleased API again, no matter how much people whine)

**Comment by nitzmahone** [comment]
Microsoft just released Azure SDK 2.0.0 RC5, so we should probably see what (if anything else) got broken...

**Comment by raags** [comment]
The `__version__` attribute is back but uses semver now. The azure_rm.py inventory script has a check for the release date instead :

```
AZURE_MIN_VERSION = "2016-03-30"
```

Also, inventory fails on :

```
 File "./azure_rm.py", line 384, in compute_client
 ComputeManagementClientConfiguration(self.azure_credentials, self.subscription_id))
 TypeError: __init__() takes at least 3 arguments (2 given)
```

**Comment by nitzmahone** [comment]
Sounds like @chouseknecht is working on this (since he's demoing this stuff at Red Hat summit this week) :) .

**Comment by raags** [comment]
Oh, good; I opened a bug report anyway : https://github.com/ansible/ansible/issues/16480

**Comment by chouseknecht** [comment]
This is fixed with https://github.com/ansible/ansible-modules-core/commit/de9959b129d927bc3a7c8022da1c7d84747763b8#diff-ffa4607ffeb203b460209b8f25cb5cee

**Comment by symgryph** [comment]
Doesn't seem to be fixed when I follow all directions. Get same error (multiple os/versions etc). Any install guides that actually work?
