### ISSUE TITLE
LXD/DOCKER over SSH connector

### ISSUE THREAD

**Issue by killua-eu** [ansible/ansible#16448]
Hi,

I wonder if/how is it possible to chain ssh and lxd connections in order to manipulate lxd/docker containers on remote physical servers

thanks, Pavel

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
