### ISSUE TITLE
change pip's 'name' to be a list, to minimize conflicts

### ISSUE THREAD

**Issue by joaocc** [ansible/ansible#16449]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

export ANSIBLE_LOG_PATH=/var/log/ansible.log
export ANSIBLE_CACHE_PLUGIN=jsonfile
export ANSIBLE_CACHE_PLUGIN_CONNECTION=/var/cache/ansible
export ANSIBLE_PRIVATE_KEY_FILE="/opt/src/_pk/key.pub"

export ANSIBLE_HOST_KEY_CHECKING=false
export ANSIBLE_GATHERING=smart
export ANSIBLE_ROLES_PATH=/opt/src/ansible/roles"
export ANSIBLE_PRIVATE_ROLE_VARS=true
export ANSIBLE_JINJA2_EXTENSIONS=jinja2.ext.do,jinja2.ext.i18n
export ANSIBLE_NOCOWS=1
export ANSIBLE_SSH_ARGS="-o ControlMaster=auto -o ControlPersist=15s -o GSSAPIAuthentication=no -v -o ForwardAgent=yes"

export ANSIBLE_SQUASH_ACTIONS="apk,apt,dnf,package,pacman,pkgng,yum,zypper,pip"
##### OS / ENVIRONMENT

N/A
##### SUMMARY

While trying to install docker-compose and docker-py via the pip module, I noticed a conflict between one of the module versions they required.

If I install via command/pip the problem goes away

To try to keep it "pure ansible" I added "pip" to the list of "squash_actions".
Unfortunately it fails with an error message (see below)
##### STEPS TO REPRODUCE

Original task (not well behaved due to docker-py and docker-compose requiring different versions of "requests")

```
- name: "Docker: install docker python interface"
  become: true
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-py
    - docker-compose
```

Workaround via command (not pure ansible)

```
- name: "Docker: install docker python interface"
  become: true
  command: pip install --upgrade docker-py docker-compose
```

add pip to squash_actions

```
export ANSIBLE_SQUASH_ACTIONS="apk,apt,dnf,package,pacman,pkgng,yum,zypper,pip"
```

pip now fails

```
- name: "Docker: install docker python interface"
  become: true
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-py
    - docker-compose
```
##### EXPECTED RESULTS

I would expect "pip" to run and install both packages
##### ACTUAL RESULTS

the pip module crashes

```
TASK [ez123-vmhost-docker : Docker: install docker python interface] ***********
task path: /opt/src/ansible/roles/ez123-vmhost-docker/tasks/main.yml:49
<host.dom> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<host.dom> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=15s -o GSSAPIAuthentication=no -v -o ForwardAgent=yes -o StrictHostKeyChecking=no -o Port=60022 -o 'IdentityFile="/opt/src/_pk/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r host.dom '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1466966432.76-166671552359764 `" && echo ansible-tmp-1466966432.76-166671552359764="` echo $HOME/.ansible/tmp/ansible-tmp-1466966432.76-166671552359764 `" ) && sleep 0'"'"''
<host.dom> PUT /tmp/tmp6snVtE TO /home/ubuntu/.ansible/tmp/ansible-tmp-1466966432.76-166671552359764/pip
<host.dom> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=15s -o GSSAPIAuthentication=no -v -o ForwardAgent=yes -o StrictHostKeyChecking=no -o Port=60022 -o 'IdentityFile="/opt/src/_pk/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[host.dom]'
<host.dom> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<host.dom> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=15s -o GSSAPIAuthentication=no -v -o ForwardAgent=yes -o StrictHostKeyChecking=no -o Port=60022 -o 'IdentityFile="/opt/src/_pk/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt host.dom '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-hhoupjtvfdzqtmudrbllodbywwtvzpnb; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1466966432.76-166671552359764/pip; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1466966432.76-166671552359764/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
failed: [hammer-00] (item=[u'docker-py', u'docker-compose']) => {"cmd": "/usr/local/bin/pip install -U ['docker-py', 'docker-compose']", "failed": true, "invocation": {"module_args": {"chdir": null, "editable": true, "executable": null, "extra_args": null, "name": "['docker-py', 'docker-compose']", "requirements": null, "state": "latest", "umask": null, "use_mirrors": true, "version": null, "virtualenv": null, "virtualenv_command": "virtualenv", "virtualenv_python": null, "virtualenv_site_packages": false}, "module_name": "pip"}, "item": ["docker-py", "docker-compose"], "msg": "\n:stderr: Invalid requirement: '[docker-py,'\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py\", line 78, in __init__\n    req = Requirement(req)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/packaging/requirements.py\", line 96, in __init__\n    requirement_string[e.loc:e.loc + 8]))\nInvalidRequirement: Invalid requirement, parse error at \"'[docker-'\"\n\n"}

```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by joaocc** [comment]
Thx. Submitted to https://github.com/ansible/ansible-modules-core/issues/4055
