### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec error on jsonify while doing remote apt

### ISSUE THREAD

**Issue by nekopep** [ansible/ansible#1644]
While executing this task:
    - name: ensure postgresql
      apt: pkg=postgresql state=installed

I got this error:

< TASK: [ensure postgresql] >

---

failed to parse json:     install_recommends=install_recommends,force=force_yes)

  File "/home/vagrant/.ansible/tmp/ansible-1353228049.67-30212244630745/apt", line 159, in install

```
m.fail_json(msg="'apt-get install %s' failed: %s" % (packages, err))
```

  File "/home/vagrant/.ansible/tmp/ansible-1353228049.67-30212244630745/apt", line 832, in fail_json

```
print self.jsonify(kwargs)
```

  File "/home/vagrant/.ansible/tmp/ansible-1353228049.67-30212244630745/apt", line 817, in jsonify

```
return json.dumps(data)
```

  File "/usr/lib/python2.7/json/**init**.py", line 231, in dumps

```
return _default_encoder.encode(obj)
```

  File "/usr/lib/python2.7/json/encoder.py", line 201, in encode

```
chunks = self.iterencode(o, _one_shot=True)
```

  File "/usr/lib/python2.7/json/encoder.py", line 264, in iterencode

```
return _iterencode(o, 0)
```

UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 55: invalid continuation byte

---

This is because my os has french output:
vagrant@my-server:~$ sudo aptitude install postgresql
Les NOUVEAUX paquets suivants vont être installés : 
  libpq5{a} libxml2{a} postgresql postgresql-9.1{a} postgresql-client-9.1{a} postgresql-client-common{a} postgresql-common{a} sgml-base{a} 
  ssl-cert{a} xml-core{a} 
0 paquets mis à jour, 10 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de télécharger 240 ko/6 659 ko d'archives. Après dépaquetage, 25,3 Mo seront utilisés.

As you can see the console output non utf8 chars and make ansible fail with apt command.

Regards,

Pep

**Comment by nekopep** [comment]
Doing: 
#dpkg-reconfigure locales
then force fr_FR.UTF-8
hide the issue, but needs a modification on user side...

**Comment by mpdehaan** [comment]
can you paste the output of "ansible --version" please?

**Comment by nekopep** [comment]
#ansible --version
ansible 0.9

**Comment by mpdehaan** [comment]
Thanks, it's been proposed we add an explicit environment set to LANG=C in
the module common code, which will hopefully address this issue (and
elsewhere).

**Comment by hyao** [comment]
Maybe we could use a UTF8 locale as the default in Ansible?

**Comment by sfromm** [comment]
@ldufrechou What is LANG set to on the target host when you run into the error in jsonify?  I'd like to try to replicate before implementing a fix.

**Comment by nekopep** [comment]
It was FR.fr

**Comment by sfromm** [comment]
I was unable to replicate the above error on debian 6.0.6.  @ldufrechou, what distribution and version do you see this error?  
Thanks.

**Comment by sfromm** [comment]
@ldufrechou When you get a chance, can you apply the patch in issue #1689 and see if that helps with this issue?

**Comment by mpdehaan** [comment]
already merged it in, FWIW.

If it doesn't help, let me know, and I'll reopen this.
