### ISSUE TITLE
WinRM NTLM Error 104

### ISSUE THREAD

**Issue by mikef-nl** [ansible/ansible#16452]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

ansible 2.1.0.0
  config file = /home/ansible/.ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

Ansible configured to use NTLM authentication to domain servers.
##### OS / ENVIRONMENT

CentOS Linux release 7.2.1511 (Core)
Managing Windows Server 2012 R2 with Windows Domain
PyWinRM 0.2.0
##### SUMMARY

When executing a basic win_ping the following is received.
##### EXPECTED RESULTS

 SUCCESS => {
    "changed": false,
    "ping": "pong"
}
##### ACTUAL RESULTS

```

Using /home/ansible/.ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<10.144.24.20> ESTABLISH WINRM CONNECTION FOR USER: ansible_user@DOMAIN on PORT 5986 TO 10.144.24.20
<10.144.24.20> WINRM CONNECT: transport=ntlm endpoint=https://redacted:5986/wsman
<10.144.24.20> WINRM CONNECTION ERROR: ('Connection aborted.', error(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 152, in _winrm_connect
    self.shell_id = protocol.open_shell(codepage=65001) # UTF-8
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 132, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 207, in send_message
    return self.transport.send_message(message)
  File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 173, in send_message
    response = self.session.send(prepared_request, timeout=self.read_timeout_sec)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

redacted | UNREACHABLE! => {
    "changed": false,
    "msg": "ntlm: ('Connection aborted.', error(104, 'Connection reset by peer'))",
    "unreachable": true
}

```

**Comment by jhawkesworth** [comment]
It might help if you could look through the event log on the affected servers to see if there is any information on the reason why the windows box reset the connection.  Is there a successful login attempt at the time you are making the connection from ansible, for example?

Also, please can you check the firewall configuration on the affected servers and make sure that the profile that applies is allowing connections to the winrm port?

**Comment by nitzmahone** [comment]
One other thing to check into: is there an HTTP proxy (transparent or not) in between your Ansible host and the Windows hosts? NTLM over HTTP is a connection-oriented "hack" that is not HTTP-RFC compliant (by Microsoft's design), and will not "play nice" with most HTTP proxies that reuse connections.

**Comment by mikef-nl** [comment]
No HTTP Proxy between the Ansible control server and the boxes with the issue. What I have picked up is that the protocols and ciphers enabled on the servers differ from the Windows Server defaults. These are down to software security requirements. They also all have IIS installed and all run Windows Server 2012 R2. Using Nartac IIS Crypto 1.6 build 7 I can see the following: One set of servers has SSL 2.0 and SSL 3.0 disabled with NULL,DES 56/56, RC2 40/128, RC2 56/128, RC4 40/128, RC4 56/128 and RC4 64/128 Ciphers disabled. The other set of servers has Multi-Protocol Unified Hello, PCT 1.0, SSL 2.0 and SSL 3.0 Protocols disabled. These also have NULL,DES 56/56, RC2 40/128, RC2 56/128, RC2 128/128, RC4 40/128, RC4 56/128, RC4 64/128, RC4 128/128 Ciphers disabled.

**Comment by nitzmahone** [comment]
Hrm, that's almost certainly the issue. The client proto/cipher list is chosen deep down in requests/urllib3 IIRC- we could probably allow an override at the pywinrm level where you'd pass a specific list of protocols/ciphers (they'd of course have to be available on the control Linux host), but that's not a quickie fix. @mikef-nl Can you verify that re-enabling the default protos/ciphers fixes the issue before I go down that path?

**Comment by mikef-nl** [comment]
Did think about re-enabling protos/ciphers but then on further inspection I realized my other VM running the same configuration was working. Not too sure what the next step to try would be. Have tried PSRemoting from Windows and that works fine with the VM's giving the issue.

**Comment by looking-promising** [comment]
We appear to be having the exact same issue with one of our win2012r2 machines.  We thought we'd cross reference the protocols/ciphers but do not know how.  @mikef-nl how did you get the list of enabled/disabled protocols/ciphers?

**Comment by mikef-nl** [comment]
One way is to check through the registry but an easier way is Nartac IISCrypto.

**Comment by jelep** [comment]
i am also trying to figure this out...
is tcp port on the target server listening on TCP 5986?
on the target server, was winrm configured to use HTTPS ? ref: [Configuring winrm for HTTPS](https://support.microsoft.com/en-ca/kb/2019527)

**Comment by looking-promising** [comment]
Thanks @mikef-nl and @jelep, so far we've been unable to find any difference in protocols/ciphers/winrm-config between the functional nodes and the non-functional node.

**Comment by mikef-nl** [comment]
Any further requests for troubleshooting?

**Comment by jhawkesworth** [comment]
No idea if this would be any help but perhaps compare what hotfixes are installed and see if there are any differences?

**Comment by mikef-nl** [comment]
Did check patching but that didn't seem to yield any major differences. What we have found is that by using the FQDN in the inventory instead of the IP address the connection works. This is provided the Ansible control machine can resolve the FQDN in DNS to the relevant IP. What's strange is that the majority of servers work while using the IP in the inventory.

**Comment by jelep** [comment]
also found that SSL certificate must be Server Mutual Authentication vs a standard...

**Comment by daBONDi** [comment]
Got the Same Problem but maybe some hint
Kerberos Connection is working, then i call a Powershell Command to Install the First Server in an ADFS Farm "Install-ADFSFarm ....." and after that i get also the kerberos Error with "Connection reset by peer"

Realy have no clue, but it instantly stopped working after i calll the install-adfs command

Target Host Server 2016
Ansible 2.3 Release

There must be something with a chaning SPN or so still need to find out

**Comment by daBONDi** [comment]
Ok i found some clues

When Ansible Host = fqdn it works, when it is an IP Address it not works.

The Problem is for Provision i need the IP Address and after Domainjoin and Installing ADFS Farm i need the FQDN, how i should workaround this?

After i run "Install-ADFSFram" follow Works with FQDN but **NOT with the IP "https://<ipaddress>:5986/wsman"**

**Someone got a Clue or Workaround?**
FQDN and Reverse IP is Resolvable  on the Ansible Host

```python
from winrm.protocol import Protocol

p = Protocol(
    endpoint='https://fqdn:5986/wsman',
    transport='kerberos',
    username=r'user@Domain',
    password='pw',
    server_cert_validation='ignore')
print "opening shell"
shell_id = p.open_shell()
print "Executing Command"
command_id = p.run_command(shell_id, 'ipconfig', ['/all'])
std_out, std_err, status_code = p.get_command_output(shell_id, command_id)
print std_out
p.cleanup_command(shell_id, command_id)
print closing
p.close_shell(shell_id)
```

**Comment by nathanwebsterdotme** [comment]
I've had issues similar to this which was caused by the '@' in the username. 

Switched to DOMAIN\username in the vars.

**Comment by lmilbaum** [comment]
I hit the same error randomly while provisioning ec2 instances. Same ansible playbook every time. Sometime works perfectly and sometimes hitting this error.

**Comment by ojaoferreira** [comment]
I have the same problem. When I use FQDN it already works with IP gives error: kerberos Reset connection per point. Is there a solution to the problem?
