### ISSUE TITLE
Winrm: Unable to make ansible work other than local Administrator User

### ISSUE THREAD

**Issue by vikas027** [ansible/ansible#16478]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
# ansible --version
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
#
```
##### CONFIGURATION

```
# cat /etc/ansible/ansible.cfg
#
```
##### OS / ENVIRONMENT
- CentOS 7.2 and CentOS 6.8
- Python 2.7.5
- Windows 2012 R2 Standard or Windows 10 (Joined to AD Domain)
##### SUMMARY

Unable to ping the Windows server other than Administrator User
##### STEPS TO REPRODUCE
- Install Ansible
- Execute the powershell scripts and configure kerberos as shown her [here](http://docs.ansible.com/ansible/intro_windows.html)

```
# cat /etc/krb5.conf
[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 default_realm = TEST.COM
 dns_lookup_realm = true
 dns_lookup_kdc = true
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true

[realms]
 TEST.COM = {
  kdc = ad-dns.test.com
 }

[domain_realm]
 .test.com = TEST.COM
#
```
- Get a Kerberos Ticket

```
# kinit vkumar@TEST.COM
Password for vkumar@TEST.COM:
# klist
Ticket cache: FILE:/tmp/krb5cc_0
Default principal: vkumar@TEST.COM

Valid starting       Expires              Service principal
2016-06-29T03:36:40  2016-06-29T13:36:40  krbtgt/TEST.COM@TEST.COM
    renew until 2016-07-06T03:36:36
#
```
- Create Inventory File

```
# cat /etc/ansible/hosts
[windows]
box62.test.com

[windows:vars]
ansible_user = vkumar@TEST.COM
ansible_password = Password@123
ansible_port = 5986
ansible_connection = winrm
ansible_winrm_server_cert_validation = ignore
ansible_winrm_transport = ssl
#
```
##### EXPECTED RESULTS

With domain accounts and local (not so important for me) accounts

```
# ansible windows -m win_ping
box62.test.com | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
#
```
##### ACTUAL RESULTS
- Using Domain Account -- 
  Windows Event logs fails with _"Unknown user name or bad password"_

```
# ansible windows -m win_ping -vvvvv
Using /etc/ansible/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<box62.test.com> ESTABLISH WINRM CONNECTION FOR USER: vkumar@TEST.COM on PORT 5986 TO box62.test.com
<box62.test.com> WINRM CONNECT: transport=ssl endpoint=https://box62.test.com:5986/wsman
<box62.test.com> WINRM CONNECTION ERROR: the specified credentials were rejected by the server
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 152, in _winrm_connect
    self.shell_id = protocol.open_shell(codepage=65001) # UTF-8
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 132, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 207, in send_message
    return self.transport.send_message(message)
  File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 179, in send_message
    raise InvalidCredentialsError("the specified credentials were rejected by the server")
InvalidCredentialsError: the specified credentials were rejected by the server
box62.test.com | UNREACHABLE! => {
    "changed": false,
    "msg": "ssl: the specified credentials were rejected by the server",
    "unreachable": true
}
#
```
- Using a local account --
  Interestingly, Windows Event Logs has _"An account was successfully logged on."_ , but Ansible output still shows that the credentials were rejected :(

```
# ansible windows -m win_ping -vvvvv
Using /etc/ansible/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<box62.test.com> ESTABLISH WINRM CONNECTION FOR USER: foo on PORT 5986 TO box62.test.com
<box62.test.com> WINRM CONNECT: transport=ssl endpoint=https://box62.test.com:5986/wsman
<box62.test.com> WINRM CONNECTION ERROR: the specified credentials were rejected by the server
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 152, in _winrm_connect
    self.shell_id = protocol.open_shell(codepage=65001) # UTF-8
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 132, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 207, in send_message
    return self.transport.send_message(message)
  File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 179, in send_message
    raise InvalidCredentialsError("the specified credentials were rejected by the server")
InvalidCredentialsError: the specified credentials were rejected by the server
box62.test.com | UNREACHABLE! => {
    "changed": false,
    "msg": "ssl: the specified credentials were rejected by the server",
    "unreachable": true
}
```
- Using Administrator (Local) account --

```
# ansible windows -m win_ping
box62.test.com | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
#
```

I had got this working with Ansible v1.9 and CentOS 6.7 few months ago with similar steps. Not sure what has changed now.

Thanks in advance for looking into this.

**Comment by jhawkesworth** [comment]
Please can you try without setting

ansible_winrn_transport: ssl

Also please ensure you have installed the python Kerberos library.

**Comment by vikas027** [comment]
Hello @jhawkesworth ,

I have done the same in vain

```
# pip list | grep -i kerberos
kerberos (1.2.4)
pykerberos (1.1.13)
requests-kerberos (0.10.0)
#

# cat /etc/ansible/hosts
[windows]
box62.test.com

[windows:vars]
ansible_user = vkumar@TEST.COM
ansible_password = Password@123
ansible_port = 5986
ansible_connection = winrm
ansible_winrm_server_cert_validation = ignore
#

# ansible windows -m win_ping -vvvvv
Using /etc/ansible/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<box62.test.com> ESTABLISH WINRM CONNECTION FOR USER: vkumar@TEST.COM on PORT 5986 TO box62.test.com
<box62.test.com> WINRM CONNECT: transport=kerberos endpoint=https://box62.test.com:5986/wsman
<box62.test.com> WINRM CONNECTION ERROR: the specified credentials were rejected by the server
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 152, in _winrm_connect
    self.shell_id = protocol.open_shell(codepage=65001) # UTF-8
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 132, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 207, in send_message
    return self.transport.send_message(message)
  File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 179, in send_message
    raise InvalidCredentialsError("the specified credentials were rejected by the server")
InvalidCredentialsError: the specified credentials were rejected by the server

<box62.test.com> WINRM CONNECT: transport=ssl endpoint=https://box62.test.com:5986/wsman
<box62.test.com> WINRM CONNECTION ERROR: the specified credentials were rejected by the server
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 152, in _winrm_connect
    self.shell_id = protocol.open_shell(codepage=65001) # UTF-8
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 132, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 207, in send_message
    return self.transport.send_message(message)
  File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 179, in send_message
    raise InvalidCredentialsError("the specified credentials were rejected by the server")
InvalidCredentialsError: the specified credentials were rejected by the server
box62.test.com | UNREACHABLE! => {
    "changed": false,
    "msg": "kerberos: the specified credentials were rejected by the server, ssl: the specified credentials were rejected by the server",
    "unreachable": true
}
#
```

Interestingly, Kerberos says that the credentials were rejected,but I can see few successes and one failure in event log. I had cleared up all logs before executing the `win_ping` module.
![2016-06-29_19-38-19](https://cloud.githubusercontent.com/assets/6998650/16447690/0deb580c-3e31-11e6-8cbc-86804de88fd9.png)

**Comment by jhawkesworth** [comment]
just to be sure, please check you have a kerberos ticket which has not expired before running the playbook, and that it is for
vkumar@TEST.COM
Also, please check that 
box62.test.com is on the domain called TEST.COM and not on a different domain with a trust relationship.

if you run

kinit -C vkumar@TEST.COM 

then run a 

klist

ensure that the cannonical domain name (what the -C gives you) matches the domain name you are using.

I think the above is actually progress - you are connecting to winrm, there's just a problem to be solved regarding being authorized to do things on that machine.

Hope this helps,

Jon

**Comment by vikas027** [comment]
Thanks @jhawkesworth ,

My Win Server is indeed joined to the domain.
![2016-06-29_22-58-59](https://cloud.githubusercontent.com/assets/6998650/16452681/1379a852-3e4d-11e6-9062-6d68205e35dc.png)

I had tried using the `-C` switch earlier too; same result. 

```
# kdestroy -A
# kinit -C vkumar@TEST.COM
Password for vkumar@TEST.COM:
#
# klist
Ticket cache: FILE:/tmp/krb5cc_0
Default principal: vkumar@TEST.COM

Valid starting       Expires              Service principal
2016-06-29T22:57:50  2016-06-30T08:57:50  krbtgt/TEST.COM@TEST.COM
    renew until 2016-07-06T22:57:44
```

Here is the output of winrm config, not sure if this helps. I have double checked it from the steps listed for [WinRM](https://github.com/diyan/pywinrm) too.

``` ps
PS C:\Users\Administrator> winrm get winrm/config
Config
    MaxEnvelopeSizekb = 500
    MaxTimeoutms = 60000
    MaxBatchItems = 32000
    MaxProviderRequests = 4294967295
    Client
        NetworkDelayms = 5000
        URLPrefix = wsman
        AllowUnencrypted = false
        Auth
            Basic = true
            Digest = true
            Kerberos = true
            Negotiate = true
            Certificate = true
            CredSSP = false
        DefaultPorts
            HTTP = 5985
            HTTPS = 5986
        TrustedHosts
    Service
        RootSDDL = O:NSG:BAD:P(A;;GA;;;BA)(A;;GR;;;IU)S:P(AU;FA;GA;;;WD)(AU;SA;GXGW;;;WD)
        MaxConcurrentOperations = 4294967295
        MaxConcurrentOperationsPerUser = 1500
        EnumerationTimeoutms = 240000
        MaxConnections = 300
        MaxPacketRetrievalTimeSeconds = 120
        AllowUnencrypted = false
        Auth
            Basic = true
            Kerberos = true
            Negotiate = true
            Certificate = false
            CredSSP = false
            CbtHardeningLevel = Relaxed
        DefaultPorts
            HTTP = 5985
            HTTPS = 5986
        IPv4Filter = *
        IPv6Filter = *
        EnableCompatibilityHttpListener = false
        EnableCompatibilityHttpsListener = false
        CertificateThumbprint
        AllowRemoteAccess = true
    Winrs
        AllowRemoteShellAccess = true
        IdleTimeout = 7200000
        MaxConcurrentUsers = 10
        MaxShellRunTime = 2147483647
        MaxProcessesPerShell = 25
        MaxMemoryPerShellMB = 1024
        MaxShellsPerUser = 30
PS C:\Users\Administrator>
```

**Comment by nitzmahone** [comment]
You might also need to adjust the WinRM ACL to allow the user's group, especially if the user isn't a domain admin or otherwise in the local admin group on the target host. I've seen various defaults (and I'm too lazy to decode the SDDL in your config output above ;) )- on mine it only allows the Administrators group in a useful way.  Easiest way to do this interactively is via `winrm configSDDL default` and tweak the ACL to allow at least Read/Execute to whatever users/groups you need.

**Comment by nitzmahone** [comment]
(also been thinking about tweaking this into the ConfigureRemotingForAnsible script to allow a list of users/groups to be passed in to ensure/test access via that ACL)

**Comment by vikas027** [comment]
Thank you so much @nitzmahone Making the user a part of the `Domain Admins` worked like a charm. 

I also tried to add a user through `winrm configSDDL default` but that didn't worked for me straightaway. It just took few seconds to realise that I also need `Execute(Invoke)` permissions and not just `Read(Get,Enumerate,Subscribe)`
![2016-07-06_13-24-33](https://cloud.githubusercontent.com/assets/6998650/16606650/fe0b7a10-437c-11e6-85e4-a9793619e107.png)

So overall it was a permission issue and not invalid credentials as pointed out in logs. Thank you again for all your time and efforts on this. I am a happy man now :)

**Comment by jhawkesworth** [comment]
Glad you are sorted, sorry I didn't think of user permissions before.

**Comment by dreamcat4** [comment]
Hi there. Just encountered same error message today on basic auth. Had not touched the system in a couple of months since last ansible playbook run. Not using kerberos or anything like that yet.

**Comment by fxfitz** [comment]
@nitzmahone: We're also seeing the same problem with basic auth. We've confirmed that the user has the right credentials, is in the proper group, and has the right Full Access in `winrm config SDDL default`.

**Comment by dreamcat4** [comment]
Yeah it certainly feels like a weird one. Because on existing system it stopped working after 2 month not using ansible. Re-ran the `configureAnsibleRemoting.ps1` script again. But that didnt help to clear up anything.

So started again with another different PC. Clean / fresh install of window 10 pro from scratch. Then the same steps for getting started with ansible on windows, as per the guide. And it worked fine first time on basic auth.

Only thing was aware of might have changed the system in-between those times (on the broke one) was the regular windows 10 updates and patches. I didnt fiddle with my windows services, didnt fiddle with winrm or the `ansible` windows account.

**Comment by jhawkesworth** [comment]
Is it possible the account password has simply expired?  If I recall you have to explicitly set 'password never expires' these days.

**Comment by dreamcat4** [comment]
Yeah but checked the user account's properties... box is checked 'Password never expires'. I also changed the account's password myself manually about 3 times. It still didn't work.

**Comment by dreamcat4** [comment]
Today found an in-depth article about how windows configures the WinRM service. Especially in regards to user access permissions. It just struck me as interesting and perhapsin some way relevant to this issue:

https://www.sevecek.com/Lists/Posts/Post.aspx?ID=280

I have no doubts that a fresh install of windows will eliminate the problem. But before I get around to that and press the nuke button on it, would be nice to know where better to look. So that the underlying reason can be found and made known for others experiencing same issue in future.

**Comment by m0ntl** [comment]
Had a very similar issue. After going through this thread and correcting my permissions issues (thanks for that) authentication was still not working. I finally realized that for Kerberos to work it requires the FQDN to be reverse-resolvable [https://help.ubuntu.com/community/Kerberos](url).

**Comment by vikas027** [comment]
@m0ntl yes, Kerberos is very sensitive to DNS resolutions

**Comment by imakowski** [comment]
@m0ntl you can set **rdns = false** in krb5.cfg and this will fix an issue with reverse DNS

**Comment by TiagoAssuncao** [comment]
In my case, a just add this line on [libdefaults] in my krb5.conf:

`allow_weak_crypto = true`

And thats works.

**Comment by query2018** [comment]
@nitzmahone I have been facing similar issue and tried using the resolution you gave but still the issue is prevelant. Can you suggest any further
