### ISSUE TITLE
Azure RM inventory script fails with azure-python-sdk 0.30.0rc5

### ISSUE THREAD

**Issue by raags** [ansible/ansible#16480]
ISSUE TYPE

Bug Report
ANSIBLE VERSION

2.2.0

CONFIGURATION

OS / ENVIRONMENT

SUMMARY

The azure_rm inventory throws an error for Azure python sdk version miss match. But script has a check for the release date instead `AZURE_MIN_VERSION = "2016-03-30"`.

That being fixed, I get a new error :

```
File "./azure_rm.py", line 384, in compute_client
ComputeManagementClientConfiguration(self.azure_credentials, self.subscription_id))
```

STEPS TO REPRODUCE

Follow this guide : https://docs.ansible.com/ansible/guide_azure.html

EXPECTED RESULTS

Success

ACTUAL RESULTS

Inventory script throws the exception.

**Comment by chouseknecht** [comment]
The azure inventory script was upgraded to work with RC5. https://github.com/ansible/ansible/commit/7964a2fca3191d56021af83cbe7c9ccf54416600#diff-048f02162334c13cdaaa3c9f3409161f
