### ISSUE TITLE
Files missing when connect by HTTP

### ISSUE THREAD

**Issue by gustavofc** [ansible/ansible#16502]
##### ISSUE TYPE
- Documentation Report
##### OS / ENVIRONMENT

Chrome
Firefox
##### SUMMARY

Problem with theme.min.css and others ASB-docs*.png when acessing http://docs.ansible.com/ansible/list_of_network_modules.html. These problems don't occur when https is used.

![image](https://cloud.githubusercontent.com/assets/366537/16462269/df6dd434-3e06-11e6-9fcf-eb70e0997c0d.png)
##### STEPS TO REPRODUCE
1. Open chrome or firefox.
2. Paste http://docs.ansible.com/ansible/list_of_network_modules.html in the url bar.

**Comment by docschick** [comment]
I'm not seeing any differences when I look at http versus https in Chrome for this URL.  I'm wondering if it is a CDN issue. One of the other developers confirmed that the files shouldn't change due to http/https.

**Comment by gustavofc** [comment]
I tested outside my company's network and works. I think it is related to http proxy. 
May I close this or you do?

**Comment by docschick** [comment]
I'll close -- thanks for double checking and making sure this isn't a larger issue. Cheers!
