### ISSUE TITLE
"module (_) is missing interpreter line" for module scripts starting with a UTF-8 BOM

### ISSUE THREAD

**Issue by kenny-evitt** [ansible/ansible#16503]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/kenny/@code/ansible-domain-migration/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
inventory = inventory
roles_path = roles
vault_password_file = decrypt_vault_password
```
##### OS / ENVIRONMENT

My Ansible control machine is running Ubuntu 14.04 and my target host is running Windows Server 2012 R2, tho I don't believe this is specific to either.
##### SUMMARY

I installed a role in a project repo using `ansible-galaxy ...` and the role includes a module written in PowerShell. The role's _main_ task calls the module. When I run the playbook that includes the role, I get the following error:

```
TASK [windows-remote-desktop : Enable Remote Desktop Windows Firewall rules] ***
fatal: [test-nad0]: FAILED! => {"failed": true, "msg": "module (enable_windows_firewall_rules_by_display_group) is missing interpreter line"}
```

This issue seems to have been identified previously in this thread on the devel mailing list:
- [Developing Windows modules: module is missing interpreter line - Google Groups](https://groups.google.com/forum/#!topic/ansible-devel/xgyfOdAUIrQ)
##### STEPS TO REPRODUCE
1. Create a new test module, e.g. _library\test.ps1_.
2. Add or copy code to the test module script file; enough to confirm whether it works. I copied [the code from the Windows `ping` module](https://github.com/ansible/ansible-modules-core/blob/devel/windows/win_ping.ps1).
3. Run a playbook or an ad-hoc command to confirm that the test module works, e.g. `ansible test-nad0 -m test`.
4. Edit the test module script file and add a UTF-8 BOM, e.g. execute the command `:set bomb` in Vim with the file open in the current buffer.
5. Re-run a playbook or ad-hoc command to test the module – it should fail with the `... is missing interpreter line` error.
##### EXPECTED RESULTS

The module should execute normally regardless of the BOM.
##### ACTUAL RESULTS

Modules fail with the above-mentioned error if they contain a BOM.

**Comment by jctanner** [comment]
I was able to reproduce the error as described with the instructions given.

```
###################################
v2.1.1.0-0.1.rc1
###################################
No config file found; using defaults
Loaded callback default of type stdout, v2.0

PLAYBOOK: site.yml *************************************************************
1 plays in site.yml

PLAY [el6host] *****************************************************************

TASK [win_pinger] **************************************************************
task path: /home/jtanner/workspace/issues/AP-16503/site.yml:6
fatal: [el6host]: FAILED! => {"failed": true, "msg": "module (win_pinger) is missing interpreter line"}

NO MORE HOSTS LEFT *************************************************************
 [WARNING]: Could not create retry file 'site.retry'.         [Errno 2] No such file or directory: ''


PLAY RECAP *********************************************************************
el6host                    : ok=0    changed=0    unreachable=0    failed=1   

## RC: 
```

**Comment by abadger** [comment]
Our modules will always be UTF-8 so there will never be a case where the byte order mark is necessary. The nearest a standards body  comes to ruling on this is: https://tools.ietf.org/html/rfc3629#section-6 where the IETF  recommends forbidding the use of a BOM if a protocol will always be UTF-8.

Now modules aren't truly a "protocol" so I don't think it's harmful to account for text editors which add a BOM in some manner but what would be best to do isn't so clear to me.  For modules which really make use of the shebang, the presence of a BOM will likely cause the module to stop functioning on some operating systems (as the OS will be looking for the #! characters at the very start of the file and the spurious BOM will interfere with that).  OTOH, powershell on windows isn't actually making use of the shebang.  So a few options:
- Special case powershell handling to not care about the shebang.  We don't use the shebang to decide whether to handle the module as powershell anyway.  We use the presence of `# POWERSHELL_COMMON` to decide whether to substitute our variables in. (Tangential note: I'm not sure what this means for using a powershell script which doesn't make use of our boilerplate... I suspect trying to do that is probably broken).  This is likely easy to implement by having the section of  executor/module_common.py::_find_snippet_imports() which deals with powershell set the shebang line to always return "#!powershell".
- Special case powershell handling to allow either `#!powershell` or `0xFEFF#!powershell`.  This is a tad larger of a change as we aren't doing any checking of the shebang for powershell now but if we implement it in the same section of _find_snippet_imports() it shouldn't be too hard to achieve.
- Clearer error message.  If we find that the two bytes of a module are 0xFEFF then return an error that tells the user to check for and remove any BOM that might be present.  This could be a good thing for non-powershell modules that someone edited in a windows text editor that mistakenly adds BOMs to its files.

**Comment by kenny-evitt** [comment]
@abadger Your third option would be the minimal incremental change that would at least make this a readily understandable and fixable issue.

I am indifferent between your first and second options but it would be nice to not have to remove any BOMs that any errant editors erroneously emit.

**Comment by nitzmahone** [comment]
fixed via https://github.com/ansible/ansible/commit/31e963dd2a499a9c6eca8c5f30b480a9b867f84b and cherry-picked to stable-2.1
