### ISSUE TITLE
Support for AWS Mumbai region

### ISSUE THREAD

**Issue by DivyaMangotra** [ansible/ansible#16518]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

```
1.9.3 and above
```
##### SUMMARY

AWS has recently launched Mumbai region and CloudFormation module does not support the same. Please add Mumbai region- "ap-south-1" in the list of supported regions for all the AWS modules.

**Comment by talonx** [comment]
This should be in ansible-modules-core

**Comment by nitzmahone** [comment]
fixed in devel with https://github.com/ansible/ansible-modules-core/pull/4080
