### ISSUE TITLE
Resources page updates (docsite)

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1652]
Cloud usage on CentOS Wiki

http://wiki.centos.org/Cloud/Manage/Ansible 

JP Mens: provisioning CentOS instances with EC2

http://jpmens.net/2012/11/21/provisioning-centos-ec2-instances-with-ansible/

**Comment by jpmens** [comment]
Top wiki entry is a subset of bottom blog post. ;-)

**Comment by mpdehaan** [comment]
another thing we should do is prune the mercurial module now that we have a cleaned up one in core.

In queue.

**Comment by mpdehaan** [comment]
done, will be in next push
