### ISSUE TITLE
"ansible_processor_count" and "ansible_processor_vcpus" reported as 0

### ISSUE THREAD

**Issue by adreznec** [ansible/ansible#16533]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Running OS: Ubuntu 16.04 LTS x86_64
Managing OS: Ubuntu 16.04 LTS ppc64le
##### SUMMARY

On systems without vendor_id/model_name in /proc/cpuinfo, the "ansible_processor_count" and "ansible_processor_vcpus" facts are reported as 0.
##### STEPS TO REPRODUCE

```
When running Ansible and managing a host OS running on POWER/ppc64le, run:

ansible -i hosts -m setup all | grep proc

```

##### EXPECTED RESULTS

Upon fact gathering, I expected Ansible to report a number of processors/vcpus equal to what is returned by /proc/cpuinfo.

$ sudo ansible -i /home/openstack/hosts -m setup all | grep proc
        "ansible_processor": [
        "ansible_processor_cores": 1,
        "ansible_processor_count": 32,
        "ansible_processor_threads_per_core": 1,
        "ansible_processor_vcpus": 32,

$ cat /proc/cpuinfo
processor       : 0
cpu             : POWER8 (architected), altivec supported
clock           : 3359.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 1
cpu             : POWER8 (architected), altivec supported
clock           : 3359.000000MHz
revision        : 2.1 (pvr 004b 0201)

...

processor       : 31
cpu             : POWER8 (architected), altivec supported
clock           : 3359.000000MHz
revision        : 2.1 (pvr 004b 0201)
##### ACTUAL RESULTS

Upon fact gathering, Ansible reported zero (0) for both processors/vcpus, which is inaccurate and different what what's returned by /proc/cpuinfo. This is due to the fact that in /proc/cpuinfo on POWER there are no vendor_id or model_name flags returned unlike on x86. This means that when the current flow hits:

```
        if vendor_id_occurrence == model_name_occurrence:
            i = vendor_id_occurrence
```

at https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts.py#L1109-L1110

it sets i = 0, causing processor_count and processor_vcpus to be 0.

$ sudo ansible -i /home/openstack/hosts -m setup all | grep proc
        "ansible_processor": [
        "ansible_processor_cores": 1,
        "ansible_processor_count": 0,
        "ansible_processor_threads_per_core": 1,
        "ansible_processor_vcpus": 0,

cat /proc/cpuinfo
processor       : 0
cpu             : POWER8 (architected), altivec supported
clock           : 3359.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 1
cpu             : POWER8 (architected), altivec supported
clock           : 3359.000000MHz
revision        : 2.1 (pvr 004b 0201)

...

processor       : 31
cpu             : POWER8 (architected), altivec supported
clock           : 3359.000000MHz
revision        : 2.1 (pvr 004b 0201)

```

```

**Comment by alikins** [comment]
Working on setting up unit tests for cpu facts collection, could you post the entire '/proc/cpuinfo' for this machine somewhere?  I have an assortment of POWER5-7 examples, but no POWER8.

**Comment by adreznec** [comment]
```
user@system:/home/user$ cat /proc/cpuinfo
processor       : 0
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 1
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 2
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 3
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 4
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 5
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 6
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 7
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 8
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 9
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 10
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 11
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 12
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 13
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 14
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 15
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 16
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 17
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 18
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 19
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 20
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 21
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 22
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

processor       : 23
cpu             : POWER8 (architected), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

timebase        : 512000000
platform        : pSeries
model           : IBM,8247-21L
machine         : CHRP IBM,8247-21L
```
