### ISSUE TITLE
service module passes None as argument when no arguments

### ISSUE THREAD

**Issue by vanne** [ansible/ansible#1653]
Using devel branch, doing 
`action: service name=mysql state=started enabled=yes`
 fails and i find 
`/usr/sbin/mysqld: Too many arguments (first extra is 'None').`
in my MySQL error log.

Workaround is to use
`action: service name=mysql state=started enabled=yes args=''`
instead.

Probably related to d639844923449e34796a87aca20d1c6d3bdf5b90

**Comment by mpdehaan** [comment]
Hey @dagwieers --  can you fix this?
