### ISSUE TITLE
Confusing order copy and template modules

### ISSUE THREAD

**Issue by ShortyFR** [ansible/ansible#16578]
##### ISSUE TYPE

Bug Report ?
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### OS / ENVIRONMENT

Ubuntu 16.04 on both sides
##### SUMMARY

When using a role from a playbook, and the role uses copy or template tasks, ansible looks for the file in multiple locations. But the order for this search doesn't allow for 'override' since the most generic definition (in the role) takes precedence.
##### STEPS TO REPRODUCE

Define role "myrole" with tasks

```
- name: copy_file
  copy: src=files/myfile dest=/etc/myfile
- name: use_template
  tempalte: src=templates/mytemplate dest=/etc/mytemplate
```

And with this directory structure : 
- myplaybook
  - myplaybook.yml
  - files
    - myfile (1)
  - templates
    - mytemplate (1)
- roles
  - myrole
    - files
      - myfile (2)
    - templates
      - mytemplate (2)
##### EXPECTED RESULTS

The version of myfile and mytemplate defined next to the playbook (1) should be used, and the version in the role (2) otherwise (consistency between the two modules).

Expected search order : (1) then (2)
##### ACTUAL RESULTS

The modules use the version in the role (2) if it is present, and the version defined next to the playbook (1) otherwise, so if there is a default version in the template, it cannot be "overridden" by a playbook.

Actual search order : (2) then (1)

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Search order is always from role first and playbook second, this is true for all action plugins (what copy and template are). Playbooks are not supposed to override the files in the role, the expected AND actual search order is as you say (2) and then (1).

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by ShortyFR** [comment]
OK. I didn't find the order in the documentation. I think it should be made clearer. 
And I'll try to find another way to manage my use case.
