### ISSUE TITLE
'in' incorrectly matches with string values inside list

### ISSUE THREAD

**Issue by amarao** [ansible/ansible#16584]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

nothing specific
##### OS / ENVIRONMENT

Ubuntu Yakkety Yak (and Xenial)
##### SUMMARY

'in' matches with substrings inside strings inside list.
##### STEPS TO REPRODUCE

```
playbook:
- hosts: localhost
  gather_facts: no
  tasks:
    - set_fact: a=4
    - set_fact: b=[1, 14]
    - debug: msg="{{a in b}}"
```
##### EXPECTED RESULTS

```
ok: [localhost] => {
    "msg": true
}
```
##### ACTUAL RESULTS

```
ok: [localhost] => {
    "msg": true
}
```

```
 __________________
< PLAY [localhost] >
 ------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 _________________
< TASK [set_fact] >
 -----------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost]
 _________________
< TASK [set_fact] >
 -----------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost]
 ______________
< TASK [debug] >
 --------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost] => {
    "msg": true
}
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

localhost                  : ok=3    changed=0    unreachable=0    failed=0  
```

'in' silently converts array to sting.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The `in` is actually intended for matching items in lists, it also works with substrings in strings, this is not a bug but it's intended feature. You might want to look into match/search/find as 'string only' methods.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by amarao** [comment]
But my point is that 'in' perform incorrectly for list matching. I asking if there is 4 in [1, 14], and 'in' says: "Yes, it is".

I think this is a bug!

**Comment by bcoca** [comment]
I should have noted this in the previous message, `in` is a jinja2 construct that we 'inherit'' due to our use of jinja2 and they get it from the python language.

**Comment by bcoca** [comment]
to get the result you seem to want, use intersection:

```
when: [1, 14]|intersection(['4'])
```

From your last post, I'm supposing your expected result is 'false', not 'true' as the ticket shows.

**Comment by bcoca** [comment]
the other thing i just realized, `b=[1,14]` is resulting in a string, if you do:

```
vars:
   b: [1,14]
```

or 

```
set_fact:
  b: [1,14]
```

It will work as you expect

**Comment by amarao** [comment]
Yes, that was my mistake in issue description.

Thank you for clarifying.

**Comment by bcoca** [comment]
added this in docs to clarify for all http://github.com/ansible/ansible-modules-core/commit/23738100341808b3aff0ed23b05c0fe9934d9ad8
