### ISSUE TITLE
Unable to look up dict by key if the dict key contains a variable

### ISSUE THREAD

**Issue by aneesh-joseph** [ansible/ansible#16619]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
2.2.0
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Unable to look up dict by key if the dict key contains a variable
##### STEPS TO REPRODUCE

vars.yml

```

---
volumes:
 vol-1-{{env}}:
   size: 500
   fs: "ext3"
```

play.yml

```
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
   - vars.yml
  tasks:
  - set_fact:
     volume_name: "vol-1-{{env}}"
  - debug: msg='{{ volumes[volume_name].size }}'
```

run the play using

```
ansible-playbook play.yml -e "env=dev1"
```

##### EXPECTED RESULTS

500
##### ACTUAL RESULTS

```
'dict object' has no attribute u'vol-1-dev1'
```

**Comment by amenonsen** [comment]
The problem is not with the lookup, it's that you can't use Jinja2 expressions in YAML keys (try `- debug: var=volumes` in your `play.yml`). This is intended behaviour (e.g., see #9496). I don't know if it's explicitly documented anywhere, but it's not a bug.
