### ISSUE TITLE
Ansible SSH output gives: tcgetattr: Invalid argument

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#1662]
When using the raw module, and even in some cases with the command module we get output that starts with `tcgetattr: Invalid argument`.

I can reproduce this out put by doing something like: `ssh localhost ssh -tt -q localhost date` and this error is related to the pseudo-terminal we requested.

So I was wondering why we request a pseudo-terminal since this is not an interactive session.

If pseudo-terminals however are needed, it somehow seems that we request a pseudo-terminal even when stdin is not in fact a terminal: `ssh -tt -q localhost date < <(echo blah)`

**Comment by dhozac** [comment]
It is required by most default-configured sudos out there. It won't read a password from anything not a tty.

**Comment by dagwieers** [comment]
Ok, I guess changing this behaviour in the cases when sudo is not being used, is not acceptable ?

So we have to understand exactly what is going on, because if I run this command from my shell there is no issue. If I modify `ssh -tt -q` into `ssh -T -q` it also works. And since I cannot reproduce it on my own laptop out of the box, it's hard to know what's going on :-/

It seems somewhere stdin is being stuck, which causes the pseudo-terminal to fail.

This fails on the affected systems:

```
- name: Test raw module
  hosts: all
  user: foo
  gather_facts: no

  tasks:
  - action: raw date
    delegate_to: bar
```

Then you get output like this:

```
PLAY [Test raw module] ********************
ok: [system1] => {"stdout": "tcgetattr: Invalid argument\nFri Nov 23 16:04:41 CEST 2012\r\n"}
ok: [system2] => {"stdout": "tcgetattr: Invalid argument\nFri Nov 23 16:04:41 CEST 2012\r\n"}
ok: [system3] => {"stdout": "tcgetattr: Invalid argument\nFri Nov 23 16:04:41 CEST 2012\r\n"}

PLAY RECAP *********************
system1                        : ok=1    changed=0    unreachable=0    failed=0
system2                        : ok=1    changed=0    unreachable=0    failed=0
system3                        : ok=1    changed=0    unreachable=0    failed=0
```

This happens not just when we target Solaris or AIX, but also Linux. But not on my own laptop, only on the server(s).

**Comment by mpdehaan** [comment]
Parsing slash connection Code used to filter this message out, now the filtering code just removes trailing and leading non-JSON, I would suggest it consider filtering out tcgetattr messages again

-- Michael

**Comment by dagwieers** [comment]
I would prefer understanding the problem and seeing if we can avoid it somehow. Since I cannot reproduce it properly on my laptop, this is an issue...

**Comment by mpdehaan** [comment]
I'm not sure any of us understand the problem :)

In any event, we've had this code in earlier versions, so going back
through connection history for paramiko should find what we need to add.

**Comment by dagwieers** [comment]
We are using `ssh` connection type. We plan to move the command-and-control server to a newly deployed RHEL6 system. Let me first test if I can reproduce the problem on that system, because honestly I don't trust the current system designated for this. Can you keep this ticket open until then ? This is planned for early next week.

**Comment by mpdehaan** [comment]
What does "don't trust the current system designated" mean?

**Comment by dagwieers** [comment]
Since I cannot reproduce it on my laptop, I suspect something to be different on the system (for whatever reason). But since I don't completely understand the problem it's hard to know where to look. (I already investigated terminal settings etc...)

So in the end it may not be Ansible, but maybe Ansible can avoid it nevertheless.

**Comment by mpdehaan** [comment]
ok, yeah, the old (and we never understood it) tcgetattr filtering strategy
seemed to work pretty well.

it was basically "ignore any line starting with tcgetattr( up until the
newline", I think

it would be good if we understood it, but in practice it seemed that
various SSHes, particularly weird stuff like dropbear or old Ubuntu, just
spewed random messages and they were safe to ignore.

It is kind of the cost of doing business for the way Ansible manages
things, I think

**Comment by dagwieers** [comment]
I tested the fix now, using sudo and with asking password on the command line and both worked fine with the fix.

You can test yourself (before and after) by reproducing it using a double ssh:

`ssh localhost ssh -tt localhost ansible-playbook -v -c ssh -l system1,system2 playbook.yml`

Notice that the second ssh _will_ show you the tcgetattr error, but inside Ansible no such error appears when using the fix.

**Comment by mpdehaan** [comment]
Above PR closed as pty is listed as Linux only.   (Note that this ticket is still open to track the issue)
