### ISSUE TITLE
CentOS 'pip' not called 'pip' but 'python-pip'

### ISSUE THREAD

**Issue by tonk** [ansible/ansible#1667]
I was just trying to install some Python things with 'pip' (through Ansible of course) when I noticed things went bad.

I found that the CentOS 'pip' package is called `python-pip` and this gives me a command with the name `python-pip` and not `pip`.

I solved this with a simple sym-link, but maybe it's a good idea to extend the `pip` module. If no `pip` found, check for `python-pip`, if not then give an error.

**Comment by mpdehaan** [comment]
That seems reasonable, how about a patch?

**Comment by wzzrd** [comment]
Which version of Ansible are you using? I ran into this a while ago as well. The patch I wrote to fix this is at 2f6b9e6 and does what you suggest, but the other way around: it actually checks for python-pip first. Does that not work for you or is your version of Ansible older than this commit?

**Comment by mpdehaan** [comment]
Good catch, thought I remembered that.

It could also be a newer ansible is still pointed somehow at an older
module library.

**Comment by sfromm** [comment]
Closing this since current pip module already looks for python-pip.  @tonk, please let us know if you are using the current devel branch and still have problems.

**Comment by tonk** [comment]
Things should work, but I made an error. I thought it should be called python-pip, but on RedHat it's called pip-python (the otherway around). Maybe I can patch this.... ;-)
