### ISSUE TITLE
pattern parameter not recognized in service module (2.2.0 devel)

### ISSUE THREAD

**Issue by stevew-Purdue** [ansible/ansible#16694]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/']

```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When the "pattern" parameter when using the "service" module, an error occurs indicating that it is not a valid parameter.  See error message below.

TASK [service] *****************************************************************
fatal: [massachusetts]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: pattern"}
##### STEPS TO REPRODUCE

```
- hosts: trusty:xenial
  tasks:
  - service: name=ganglia-monitor pattern=/usr/sbin/gmond state=started

```

##### ACTUAL RESULTS

```
TASK [service] *****************************************************************
fatal: [massachusetts]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: pattern"}
```

**Comment by nitzmahone** [comment]
Are you sure you don't have a service.py in your library path or something? Pattern support hasn't been removed, and works fine for me here...

**Comment by stevew-Purdue** [comment]
Yes, a cursory glance at the code shows that 2.2.0 still intends to support the pattern option.  And this was working fine for me until I cloned and installed the 2.2.0 development branch.  I just repeated the process now using the following steps on my RHEL 6.8 server:

rpm -e ansible
rm -rf ansible
git clone https://github.com/ansible/ansible.git
cd ansible/
git submodule update --init --recursive
make rpm
rpm -ivh rpm-build/ansible-2.2.0-0.git201607141715.1905b7c.devel.el6.noarch.rpm

And I still get the same error.  BTW, I found that the sleep option also fails with an "unsupported parameter" error.  If I have neither the sleep or pattern options, then the play succeeds.

**Comment by resmo** [comment]
Has the targed host systemd installed? If so, systemd module is used which does not have the patterm arg. I already discussed it on IRC that it might be an issue and we must handle it somehow either by showing a proper error message or ignoring it.

**Comment by stevew-Purdue** [comment]
That's it!  Yes, the target host does have systemd installed.  I'll leave the ticket open as a reminder to implement one of the fixes you mentioned.
