### ISSUE TITLE
include_vars does not win over set_fact

### ISSUE THREAD

**Issue by bjggzxb** [ansible/ansible#16706]
##### ISSUE TYPE

- Bug Report
- Documentation Report
##### ANSIBLE VERSION

```
2.1.0.0
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

the document says include_vars will win over set_fact, but it seems like set_fact keeps unchanged
##### STEPS TO REPRODUCE

site.yml

```
- name: test
  hosts: localhost
  become: yes
  tasks:
    - set_fact:
        some_var: 'set_fact'

    - debug: msg={{some_var}}

    - include_vars: 'vars.yml'

    - debug: msg={{some_var}}
```

vars.yml

```
some_var: 'included'
```

##### EXPECTED RESULTS

```
TASK [setup] *******************************************************************
ok: [localhost]

TASK [set_fact] ****************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "set_fact"
}

TASK [include_vars] ************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "included"
}
```
##### ACTUAL RESULTS

```
TASK [setup] *******************************************************************
ok: [localhost]

TASK [set_fact] ****************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "set_fact"
}

TASK [include_vars] ************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "set_fact"
}
```

**Comment by nitzmahone** [comment]
This isn't a bug. Just for clarification: the `set_fact` and `include_vars` actions are both considered "host facts" (as both return an `ansible_facts` dictionary, which modifies the host facts collection, so last writer will win). The "role and include vars" mentioned in the docs refers to vars passed directly to a `role:` or `include:` directive (perhaps could be clearer- we'd consider a doc PR if you want to write one).

**Comment by bjggzxb** [comment]
So if last writer will win, the result of example above is still not correct. The included vars is the last writer, and it is omitted.

**Comment by mnarusze** [comment]
As @bjggzxb mentioned, the last writer will **not** win so assuming that @nitzmahone's explanation is valid, the issue is still present.

I tried to use a similar approach for including tasks from within a loop where some variables would be reused. Because of this problem, i.e. host facts set with _set_fact_ not being updated by variables set with _include_vars_, I need to look for workarounds.

**Comment by Jackyjjc** [comment]
Just wanted to report the same issue with 2.3.0

**Comment by asheplyakov** [comment]
Just hit the same problem with 2.4.0

**Comment by nhenderson** [comment]
@nitzmahone Will you please re-open this issue? The last writer does not win. The issue has been re-produced by myself and the four other people who have commented on this issue.
