### ISSUE TITLE
Different behavior for variables used in dependent role since 2.1.0

### ISSUE THREAD

**Issue by maximede** [ansible/ansible#16729]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel e560bfeaca) last updated 2016/07/15 11:32:11 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 7de287237f) last updated 2016/07/15 12:59:03 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 68ca157f3b) last updated 2016/07/15 12:59:03 (GMT -700)
  config file =
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When a dependency role (configured with `allow_duplicates` ) uses a variable set by a dependent role and multiple role are using the same dependency role, the dependency role always use the variable defined in the last called role 
##### STEPS TO REPRODUCE

Create a playbook
Add two role (`role1` and `role2`) with a dependency on another role configured with `allow_duplicates: yes` (`common-role`)
Use a variable ( `app_name`) in the common role which is defined in `role1/vars/main.yml` and `role2/vars/main.yml`
Display the var value in a debug task inside the common role

Directory structure

```
└── roles
    ├── common-role
    │   ├── meta
    │   │   └── main.yml
    │   └── tasks
    │       └── main.yml
    └── role1
    │   ├── meta
    │   │   └── main.yml
    │   └── vars
             └── main.yml
    └── role2
        ├── meta
        │   └── main.yml
        └── vars
            └── main.yml

```

`playbook.yml`

```
  - hosts: localhost
    roles:
      - { role: role1}
      - { role: role2 }
```

`role/common-role/meta/main.yml`

```
allow_duplicates: yes
```

`roles/common-role/tasks/main.yml`

```
- name: "debug {{app_name}}"
  debug: msg="apps_name --- {{app_name}}"
```

`roles/role1/meta/main.yml`

```
dependencies:
  - { role: common-role }
```

`roles/role1/vars/main.yml`

```
app_name: role1AppName
```

`roles/role2/meta/main.yml`

```
dependencies:
  - { role: common-role }
```

`roles/role2/vars/main.yml`

```
app_name: role2AppName
```

##### EXPECTED RESULTS

ansible 2.0 ( and the previous version) was producing this : 

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [common-role : debug role1AppName] *************************************
ok: [localhost] => {
    "msg": "apps_name --- role1AppName"
}

TASK [common-role : debug role2AppName] *************************************
ok: [localhost] => {
    "msg": "apps_name --- role2AppName"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```
##### ACTUAL RESULTS

ansible 2.1+ produces this :

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [common-role : debug role2AppName] *************************************
ok: [localhost] => {
    "msg": "apps_name --- role2AppName"
}

TASK [common-role : debug role2AppName] *************************************
ok: [localhost] => {
    "msg": "apps_name --- role2AppName"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

tested with ansible 2.1.0.0 , the stable-2.1 branch and the devel branch, same results.

**Comment by Christoph-D** [comment]
Bisecting shows that this was introduced by 3ced6d3e.  See the pull request for details.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by maximede** [comment]
This seems to work with the devel branch, thanks. 

However, now I have the same issue with an "include" task in the common role. 
The tasks in the included files are always using the value of the latest set `app_name`

Should I create another bug ?

**Comment by jimi-c** [comment]
@maximede yes please, with an example. Thanks!
