### ISSUE TITLE
Integration test on Shippable runs into timeout

### ISSUE THREAD

**Issue by Christoph-D** [ansible/ansible#16745]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

Current devel branch.
##### SUMMARY

The 5th integration test (destructive opensuseleap) on Shippable reproducibly fails with TIMEOUT.  For examples, see the pull requests #16723, #16735, #16736, #16739, #16741.

The [Shippable status page for ansible](https://app.shippable.com/projects/573f79d02a8192902e20e34b/status/) doesn't load for me, so I cannot check if this only affects pull requests.  The page not loading could also indicate that the problem is with Shippable.
##### STEPS TO REPRODUCE

Create a pull request.
##### EXPECTED RESULTS

All tests passed.
##### ACTUAL RESULTS

TIMEOUT for

```
TEST=integration TARGET=destructive IMAGE=ansible/ansible:opensuseleap
```

**Comment by robinro** [comment]
Could this be a docker hub issue? I had trouble pulling some images lately.

If it's something related to the opensuse image itself I'm happy to help, but so far I think it's not.

**Comment by mattclay** [comment]
Closing this issue as opensuseleap integration tests are no longer regularly timing out.
