### ISSUE TITLE
Role search path in 2.1 messed up by include with relative path

### ISSUE THREAD

**Issue by JohnPeacockMessageSystems** [ansible/ansible#16747]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/jpeacock/devel/role_path_test/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

[defaults]
roles_path = ./roles
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Role search path messed up by relative include path even if the include itself isn't executed
##### STEPS TO REPRODUCE

```
Attached is the complete example with overloaded class.  Uncomment the include line in 
  role_path_test/overloaded/sub_level.yml
to see the erroneous behavior
```

[role_path_test.zip](https://github.com/ansible/ansible/files/369407/role_path_test.zip)
##### EXPECTED RESULTS

```
$ ansible-playbook -i localhost, overloaded/sub_level.yml 
PLAY [Top level playbook, no inheritance] **************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [class1 : announce ourselves] *********************************************
ok: [localhost] => {
    "msg": "We are in overloaded class1 now"
}

TASK [class2 : announce ourselves] *********************************************
ok: [localhost] => {
    "msg": "We are in class2 now"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```
##### ACTUAL RESULTS

```
$ ansible-playbook -i localhost, overloaded/sub_level.yml 

PLAY [Harmless include file] ***************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
skipping: [localhost]

PLAY [Top level playbook, no inheritance] **************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [class1 : announce ourselves] *********************************************
ok: [localhost] => {
    "msg": "We are in class1 now"
}

TASK [class2 : announce ourselves] *********************************************
ok: [localhost] => {
    "msg": "We are in class2 now"
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0   

```

**Comment by hlieberman** [comment]
This has been reported downstream as [Debian bug #833281](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=833281).  The submitter notes that their playbooks worked in the 2.0 series, but broke in the 2.1.  (They mix up the versions in the report, but the report is clear nonetheless.)

**Comment by JohnPeacockMessageSystems** [comment]
This appears to be fixed by the same change that resolved #14489

**Comment by jtognazzi** [comment]
I also have the same problem. I posted a message on the mailing list but got no answer.
[My post](https://groups.google.com/forum/?fromgroups=#!searchin/ansible-project/roles_path%7Csort:date/ansible-project/zUW9yzn7sYU/_ppIOEWJAgAJ)

With ansible 2.1.1.0 we cannot use relative path en ansible.cfg roles_path

I tried to backport the fix mention in #14489 but it did not work for this issue.

**Comment by jtognazzi** [comment]
The behavior change seems to be related to this pull request #16088 
precisely the change on file lib/ansible/constants.py

If I understand correctly the relativity of path is now based on where the config file ansible.cfg is.

I would really like to have the possibility to add roles path relatively to the execution and/or the playbook directory.

**Comment by towolf** [comment]
Same here with the relative path in ansible.cfg on devel.

I have 
`export ANSIBLE_CONFIG=./users/tobias.wolf/ansible.cfg`
and in there
`roles_path = ./roles`

Now it doesn't find the roles relative to current working dir, but relative to the `ansible.cfg` file

**Comment by lordfolken** [comment]
I'm also affected by this issue: 

layout: 
roles/wpa_supplicant/
├── files
│   └── wpa_supplicant.conf
├── handlers
│   └── main.yml
└── tasks
    └── main.yml

## cat roles/wpa_supplicant/tasks/main.yml 
- name: wpasupplicant 
  apt: pkg={{ item }} state=latest
  with_items:
  - wireless-tools
  - wpa-supplicant
- name: iwl-firmware
  apt: pkg=firmware-iwlwifi state=latest
  notify: reload module
- name: copy wpasupplicant config 
  copy: src=files/wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf
- name: template interfaces
  template: backup=yes dest=/etc/network/interfaces src=templates/interfaces.tpl
- name: up interface wlan0
  command: /sbin/ifup wlan0

This results in: 
TASK [laptops : wpa_supplicant] ************************************************
fatal: [x-node]: FAILED! => {"changed": false, "failed": true, "msg": "could not find src=/etc/ansible/wpa_supplicant/wpa_supplicant.conf"}

**Comment by jimi-c** [comment]
Hi all, I've looked at this on all versions from 2.1.0 on up to devel, and for each I see the expected output. Based on this (and the above comment regarding it being fixed), I'm going to go ahead and close this now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
