### ISSUE TITLE
vmware_inventory.py fails with encoding error

### ISSUE THREAD

**Issue by scatat** [ansible/ansible#16763]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

Not applicable - dynamic inventory script
##### CONFIGURATION

Vsphere 5.5 and 6.0
##### OS / ENVIRONMENT

"Ubuntu 14.04.4 LTS"
Python 2.7.6
ansible (2.1.0.0)
apt-xapian-index (0.45)
argparse (1.2.1)
chardet (2.0.1)
colorama (0.2.5)
configobj (4.7.2)
html5lib (0.999)
httplib2 (0.8)
Jinja2 (2.7.2)
kerberos (1.2.4)
Landscape-Client (14.12)
MarkupSafe (0.18)
PAM (0.4.2)
paramiko (1.10.1)
pip (1.5.4)
psphere (0.5.2)
pycrypto (2.6.1)
pykerberos (1.1.13)
pyOpenSSL (0.13)
pyserial (2.6)
python-apt (0.9.3.5ubuntu2)
python-debian (0.1.21-nmu2ubuntu2)
python-ntlm3 (1.0.2)
pyvmomi (6.0.0.2016.6)
pywinrm (0.2.0)
PyYAML (3.10)
requests (2.10.0)
requests-kerberos (0.10.0)
requests-ntlm (0.3.0)
setuptools (3.3)
six (1.10.0)
ssh-import-id (3.21)
suds (0.4)
Twisted-Core (13.2.0)
urllib3 (1.7.1)
wheel (0.24.0)
wsgiref (0.1.2)
xmltodict (0.10.2)
zope.interface (4.0.5)
##### SUMMARY

Dynamic inventory is not produced - scripts exist with error:

```
./vmware_inventory.py --list
Traceback (most recent call last):
  File "./vmware_inventory.py", line 568, in <module>
    print(VMWareInventory().show())
  File "./vmware_inventory.py", line 109, in __init__
    self.do_api_calls_update_cache()
  File "./vmware_inventory.py", line 147, in do_api_calls_update_cache
    instances = self.get_instances()
  File "./vmware_inventory.py", line 282, in get_instances
    instances = self._get_instances(kwargs)
  File "./vmware_inventory.py", line 307, in _get_instances
    ifacts = self.facts_from_vobj(instance)
  File "./vmware_inventory.py", line 514, in facts_from_vobj
    rdata[method] = self._process_object_types(methodToCall, level=level)
  File "./vmware_inventory.py", line 545, in _process_object_types
    md = self.facts_from_vobj(vobj, level=(level+1))
  File "./vmware_inventory.py", line 487, in facts_from_vobj
    rdata[k] = self._process_object_types(v, level=level)
  File "./vmware_inventory.py", line 523, in _process_object_types
    self.debugl("PROCESSING: %s" % str(vobj))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0159' in position 205: ordinal not in range(128)
```
##### STEPS TO REPRODUCE

```
 ./vmware_inventory.py --list
```

##### ACTUAL RESULTS

```
./vmware_inventory.py --list
Traceback (most recent call last):
  File "./vmware_inventory.py", line 568, in <module>
    print(VMWareInventory().show())
  File "./vmware_inventory.py", line 109, in __init__
    self.do_api_calls_update_cache()
  File "./vmware_inventory.py", line 147, in do_api_calls_update_cache
    instances = self.get_instances()
  File "./vmware_inventory.py", line 282, in get_instances
    instances = self._get_instances(kwargs)
  File "./vmware_inventory.py", line 307, in _get_instances
    ifacts = self.facts_from_vobj(instance)
  File "./vmware_inventory.py", line 514, in facts_from_vobj
    rdata[method] = self._process_object_types(methodToCall, level=level)
  File "./vmware_inventory.py", line 545, in _process_object_types
    md = self.facts_from_vobj(vobj, level=(level+1))
  File "./vmware_inventory.py", line 487, in facts_from_vobj
    rdata[k] = self._process_object_types(v, level=level)
  File "./vmware_inventory.py", line 523, in _process_object_types
    self.debugl("PROCESSING: %s" % str(vobj))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0159' in position 205: ordinal not in range(128)
```

**Comment by scatat** [comment]
Sorry for the unusual report. Doesn't fit the usual bug report as it's not about ansible per se but the dynamic inventory script.

**Comment by jctanner** [comment]
@scatat this should be fixed by https://github.com/ansible/ansible/pull/16769

**Comment by jctanner** [comment]
Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by scatat** [comment]
Wow - that is so fast- thanks so much :)
