### ISSUE TITLE
ansible should totally skip play when a tag on the play is included in --skip-tags

### ISSUE THREAD

**Issue by cjw296** [ansible/ansible#16771]
##### ISSUE TYPE
- Feature Idea
##### SUMMARY

Currently, if you have a play tagged with `foo` and pass `--skip-tags foo`, the play (and it's setup) will still be run and show in output, even though none of its tasks are run.
##### EXPECTED RESULTS

Play is skipped entirely.
##### ACTUAL RESULTS
- play name shows up in output
- setup is run for that play

**Comment by jctanner** [comment]
Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!

**Comment by cjw296** [comment]
@jctanner - @bcoca specifically asked me to put this in here, I don't think he felt it was "large".

I'm now kinda sorry I wasted the time to try and help out and do this properly :-(
