### ISSUE TITLE
Guarantee N chars per chars= definition for lookup('password') for policy compliance

### ISSUE THREAD

**Issue by xenithorb** [ansible/ansible#16785]
##### ISSUE TYPE

- Feature Idea
##### SUMMARY

Relevant source: https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/password.py

Current specific issue is that MySQL 5.7.13 requires a certain password policy. I had already assumed that `chars=` would have guaranteed at least one of the characters in a set like:

```
"{{ lookup('password', 'creds/' + inventory_hostname + '/mysql_root_pw chars=ascii_letters,digits,!@#$&*^') }}"
```

But it doesn't. Upon further inspection the source is actually just checking a random character against the set and adding it if it matches: https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/password.py#L99
##### FEATURE

It would be nice to define how many chars of each set need to be present to comply with default password policies. For example (and please just take the syntax as a pseudo-example, I know not what I do):

```
chars=ascii_letters{2},digits{2},!@#$&*^{3} 
```

Might guarantee at least 2 letters, 2 digits, and 3 chars from the custom set are present. I imagine this could be done by instantiating a counter for each defined set, and then checking that at least that many chars are present.

Perhaps also it could also be done with `length=`

```
lookup('password', '<file> chars=ascii_letters,digits length=15,9,6') 
```

or 

```
lookup('password', '<file> chars=ascii_letters,digits length=15,3,2') 
```

Where length[0] is the maximum number of chars, AND where length[1+N] are the number of chars guaranteed per set in the order they were defined in `chars=` AND where sum(length[1+N]) <= length[0]

**Comment by jctanner** [comment]
Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!

**Comment by xenithorb** [comment]
You should really rethink this approach, as I've already wasted my time now in filing this and writing it out. I'm not doing it twice.

You might want to remove "Feature idea" in the comment template and add a link to where someone should submit proposals. So people don't have to do double work, or worse, feel like their report was simply binned.

The thing is, it's extremely passive aggressive and arrogant to take someone's report and just close it and then tell them they have to do 3x more work to get it entertained. 

I don't really care what you do with it. It doesn't _currently_ work, so I've already found a workaround. It was just a thought and something I felt was worth including, because it would be useful to other people.
