### ISSUE TITLE
ansible in a privileged Docker container

### ISSUE THREAD

**Issue by cgwalters** [ansible/ansible#16782]
Using ansible to configure [Atomic Host](http://www.projectatomic.io/) systems generally works OK, but it's pretty well known that the default ansible "push" model has scaling issues.  There is `ansible-pull`, but this requires ansible to be installed on the host system.

One model I think would be interesting and possibly not too hard to implement for many of the modules is to support "chroot" operation, say inside a privileged Docker container.  Something like:

```
docker run -v /:/host --privileged ansible-playbook --targetroot=/host -c local someplaybook.yml
```

Starting this by simply reading/writing files to the `targetroot` and having e.g. the `service` module learn to `chroot /host systemctl restart foo` would get pretty far I'd say.

**Comment by jctanner** [comment]
Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!
