### ISSUE TITLE
apt module on ARM with sudo fails

### ISSUE THREAD

**Issue by haarts** [ansible/ansible#1679]
Installing packages with the 'apt' module, using sudo fails with:

```
% ansible pi -i ~/ansible_hosts -s -u pi -m apt -a 'pkg=curl state=installed'
pi | FAILED >> {
    "failed": true, 
    "msg": "'apt-get install 'curl' ' failed: E: Sub-process /usr/bin/dpkg returned an error code (2)\n"
}
```

Installing as root works as expected. I've tested with a random package, in this case 'curl'.

Ansible version: ansible 0.9 (devel 5504f13c68) last updated 2012/11/25 02:15:37 (GMT +200)
Host: Mac OSX 10.7.5, python 2.7.1
Target: Raspberry Pi (Raspbian), python 2.6.6

Might be related with #1678

More verbose output (from a playbook):
With sudo:

```
TASK: [install curl] ********************* 
<pi> ESTABLISH CONNECTION FOR USER: pi on PORT 22 TO pi
<pi> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1353806171.19-173008960117788 && chmod a+rx $HOME/.ansible/tmp/ansible-1353806171.19-173008960117788 && echo $HOME/.ansible/tmp/ansible-1353806171.19-173008960117788'
<pi> REMOTE_MODULE apt pkg=curl state=installed
<pi> PUT /var/folders/rd/8nngsjnd0ds0y690_x0j18k80000gn/T/tmpaYtqFr TO /home/pi/.ansible/tmp/ansible-1353806171.19-173008960117788/apt
<pi> EXEC /bin/sh -c 'sudo -k && sudo -p "[sudo via ansible, key=prcrexrotbynmicxjtowyyhldqrigudq] password: " -u root /bin/sh -c '"'"'/usr/bin/python -tt /home/pi/.ansible/tmp/ansible-1353806171.19-173008960117788/apt; rm -rf /home/pi/.ansible/tmp/ansible-1353806171.19-173008960117788/ >/dev/null 2>&1'"'"''
failed: [pi] => {"failed": true}
msg: 'apt-get install 'curl' ' failed: E: Sub-process /usr/bin/dpkg returned an error code (2)


FATAL: all hosts have already failed -- aborting
```

With root:

```
TASK: [install curl] ********************* 
<pi> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO pi
<pi> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1353806498.34-90561343419662 && echo $HOME/.ansible/tmp/ansible-1353806498.34-90561343419662'
<pi> REMOTE_MODULE apt pkg=curl state=installed
<pi> PUT /var/folders/rd/8nngsjnd0ds0y690_x0j18k80000gn/T/tmpF1zDoj TO /root/.ansible/tmp/ansible-1353806498.34-90561343419662/apt
<pi> EXEC /bin/sh -c '/usr/bin/python -tt /root/.ansible/tmp/ansible-1353806498.34-90561343419662/apt; rm -rf /root/.ansible/tmp/ansible-1353806498.34-90561343419662/ >/dev/null 2>&1'
changed: [pi] => {"changed": true}
```

I'm not sure what the problem is.... Some unbalanced quotes perhaps?

**Comment by dagwieers** [comment]
PR #1678 is only a cosmetic change to improve the output, it won't fix anything.

If you think quoting is the problem, you might want to remove the quoting of the package-names in the apt module. I am not sure why this is done, I assume Debian allows package-names with characters that the shell interpretes differently, but it would be nice to know for sure (and document this inside the apt module accordingly).

**Comment by dagwieers** [comment]
Which reminds me to mention that maybe increasing verbosity of apt (and showing it by default) could help pinpoint the problem better ?

**Comment by hyao** [comment]
if we're increasing the verbosity of modules (apt in this case), maybe we could use -v -vv etc. to fine tune the output?

**Comment by haarts** [comment]
@dagwieers It seems you know where to look. Can you point me to that location, then I can try it.

@hyao, @dagwieers The verbosity is not the issue right? It seems fairly evident that this line: 

```
EXEC /bin/sh -c 'sudo -k && sudo -p "[sudo via ansible, key=prcrexrotbynmicxjtowyyhldqrigudq] password: " -u root /bin/sh -c '"'"'/usr/bin/python -tt /home/pi/.ansible/tmp/ansible-1353806171.19-173008960117788/apt; rm -rf /home/pi/.ansible/tmp/ansible-1353806171.19-173008960117788/ >/dev/null 2>&1'"'"''
```

is the problem. Perhaps I'm mistaken?

**Comment by hyao** [comment]
@haarts you're right. Verbosity isn't the issue here.

I was just commenting that, if the ouput from the module is changed in any
way, it would be good to follow the convention of -v -vv -vvv, which
ansible the main script has adopted nicely.

**Comment by haarts** [comment]
Aha! Very true.

**Comment by mpdehaan** [comment]
It doesn't make sense to pass ansible's -vv options down to the modules
because they really don't know about all that, nor do I want to add a
verbose option.

However, it does seem the apt verbosity in this case is terrible, so it
makes sense to increase that value all the time, to where it at least tells
us what the error means.

**Comment by haarts** [comment]
How do I get to the file which Python executes (`/home/pi/.ansible/tmp/ansible-1353806171.19-173008960117788/apt`)? Is there a way to turn of the removal of the file? Then I might be able to figure it out.

I'd also like to know which apt command is executed. I found line 96 in library/apt but I don't know how to output the command (like `print`).

**Comment by dhozac** [comment]
export ANSIBLE_KEEP_REMOTE_FILES=1 will keep the remote files for debugging purposes.

**Comment by haarts** [comment]
Splendid!
Everything seems sane. The generated file looks fine. I even wrote the failing apt command to a temp file and substituted that in the wrapping call;
`/bin/sh -c 'sudo -k && sudo -p "[sudo via ansible, key=avnpdaclcdufenaegnepowhhdurlslnh] password: " -u root /bin/sh -c '"'"'DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical sudo  /usr/bin/apt-get --option Dpkg::Options::=--force-confold -q -y  install 'curl''"'"''`
That call just ran and installed curl.

**Comment by haarts** [comment]
Tried a different transport layer (ssh). No luck.

**Comment by haarts** [comment]
I found something!
I've edited the `run_apt` function in `library/apt` to write the stdout and stderr to a file for inspection. This is the stdout part:

```
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  curl
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/229 kB of archives.
After this operation, 336 kB of additional disk space will be used.
dpkg: warning: 'ldconfig' not found in PATH or not executable.
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable.
dpkg: warning: 'update-rc.d' not found in PATH or not executable.
dpkg: 3 expected programs not found in PATH or not executable.
NB: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin.
```

Using the same trick I figured out the PATH (`f = open("/tmp/debug", "w"); f.write(os.environ['PATH'])`) and the PATH var is:
`/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games`. Very much wrong. No clue how to fix this yet.

**Comment by hyao** [comment]
On Ubuntu, ldconfig is /sbin/ldconfig, and it belongs to libc-bin package. I'll assume you have this package installed.

And if the script is run under sudo, you could export PATH=/sbin:/usr/sbin:$PATH in .profile or .bashrc under /root, I guess?

**Comment by haarts** [comment]
That package is indeed installed.
I could do as you suggested but `sudo echo $PATH` (on the remote machine) shows: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`. Which seems OK. Somehow ansible is changing my PATH? Or perhaps sshd?

**Comment by hyao** [comment]
"sudo echo $PATH" shows the $PATH of the user which runs sudo, not root, if I'm not mistaken

**Comment by haarts** [comment]
You are right. `echo $PATH` has the same paths. So how come PATH changed for a ssh user?

**Comment by hyao** [comment]
I'm not yet familiar with the inner workings of Ansible, so I don't know how Ansible uses/derives $PATH. Maybe someone more familiar with the internals could shed some light on this issue?

**Comment by haarts** [comment]
I did found a workaround by specifying PATH in `.bashrc`. This kinda defeats to point of ansible though.

**Comment by sfromm** [comment]
@haarts Can you paste your /etc/sudoers?  I'm mostly interested in the Defaults env_keep and secure_path.  

Also, as a sanity check, what is the result if you do:

```
ansible pi -i ~/ansible_hosts -u pi -m shell -a 'echo $PATH'
ansible pi -i ~/ansible_hosts -s -u pi -m shell -a 'echo $PATH'
```

Thanks!

**Comment by haarts** [comment]
My sudoers file:

```
# /etc/sudoers
#
# This file MUST be edited with the 'visudo' command as root.
#
# See the man page for details on how to write a sudoers file.
#

Defaults env_reset
Defaults env_keep = "LANG LC_ADDRESS LC_CTYPE LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE LC_TIME LC_ALL LANGUAGE LINGUAS XDG_SESSION_COOKIE DISPLAY PATH"
Defaults exempt_group = users

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root    ALL=(ALL) ALL
suse    ALL=(ALL) ALL
pi  ALL=(ALL) ALL

# Allow members of group sudo to execute any command
# (Note that later entries override this, so you might need to move
# it further down)
%sudo ALL=(ALL) ALL
#
#includedir /etc/sudoers.d

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL
%users ALL=(ALL) ALL
```

And the requested outputs:

```
% ansible pi -i ~/ansible_hosts -u pi -m shell -a 'echo $PATH'
pi | success | rc=0 >>
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

% ansible pi -i ~/ansible_hosts -s -u pi -m shell -a 'echo $PATH'
pi | success | rc=0 >>
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

That is weird. I would expect the other PATH I presented earlier.

**Comment by haarts** [comment]
Dang! I left my fix in place. Without it:

```
% ansible pi -i ~/ansible_hosts -s -u pi -m shell -a 'echo $PATH'
pi | success | rc=0 >>
/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games
```

**Comment by hyao** [comment]
It seems that Ansible does nothing to you $PATH, which means you could either use .bashrc to modify your PATH or use "shell" module to set the path before running your playbook. 

I think this bug could be closed as it's related to the distribution you're using, not Ansible.

**Comment by haarts** [comment]
I agree, this seems distribution related. Although it would be nice if
stdout was shown by ansible's output.

Would a PATH set by an invocation of the shell module be shared in a play
book? Useful!

**Comment by daliborfilus** [comment]
I just ran into this issue and this was the culprit: I didn't overwrite /etc/sudoers on upgrade to wheezy, so it didn't add this line:

```
Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
```

After I added this line, everything is working normally.
