### ISSUE TITLE
check mode in ansible-console

### ISSUE THREAD

**Issue by ktosiek** [ansible/ansible#16815]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.1.1.0 (stable-2.1 8659f255df) last updated 2016/07/04 11:13:15 (GMT +200)
  lib/ansible/modules/core: (detached HEAD a97f4232f6) last updated 2016/07/04 11:13:32 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 59941469e6) last updated 2016/07/04 11:13:32 (GMT +200)
  config file = /home/tkontusz/int.rd-config/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Is there any way to run a single command in check mode in the `ansible-console`? It would be useful to see the changes before commiting them, or just checking the current state (like where a package is installed).

**Comment by bcoca** [comment]
You can currently run ansible-console in check mode, but there is no way to change it inside the console run.  The feature is easy to add so I'll probably make a patch soon.
