### ISSUE TITLE
How to get the result when I run a bat by raw?

### ISSUE THREAD

**Issue by fcxjluo** [ansible/ansible#16813]
I use raw to run a bat,but the bat start up a monitor process，the ansible-playbook will be no-response.How can I do ?

**Comment by alikins** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
  
  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

**Comment by fcxjluo** [comment]
Can you give me some solutions？
