### ISSUE TITLE
ini_file module doesn't support section name default

### ISSUE THREAD

**Issue by hyao** [ansible/ansible#1682]
cat test_ini.yml 

``` ---
- hosts: 127.0.0.1
  sudo: True
  gather_facts: False

  tasks:
  - name: test ini_file module support of default section
    ini_file:   dest=a.ini 
                section=default
                option=option_a
                value=a_value
```

Run the above playbook would give:
  File "/usr/lib/python2.7/ConfigParser.py", line 261, in add_section
    raise ValueError, 'Invalid section name: %s' % section
ValueError: Invalid section name: default

**Comment by mpdehaan** [comment]
I would suspect you don't have a section named 'default' ...

cc @jpmens -- it seems we might want some behavior if section is not provided, not sure if that was there or not

**Comment by hyao** [comment]
There's no default section in a.ini file. But with state=present it gives the same error?

**Comment by mpdehaan** [comment]
What you mean to say is, there is no "[default]" section in your INI file.

Are you saying if section= is not specified, it should assume something
outside of a section block, or that section= should not have a default
named "default" ?

**Comment by mpdehaan** [comment]
I would also say a traceback is not a good error, and if possible we should
try to catch it and just get the string out of the error message.

**Comment by hyao** [comment]
test setup:
a. an empty a.ini file
b. cat test_ini.yml

```
- hosts: 127.0.0.1
  sudo: True
  gather_facts: False

  tasks:
  - name: test ini_file module support of default section
    ini_file:   dest=/home/trader/a.ini 
                section=default
                option=option_a
                value=a_value
```
1. ansible-playbook test_ini.yml 
   ValueError: Invalid section name: default
2. change section=a_section_name and run: ansible-playbook test_ini.yml

```
cat a.ini 
[a_section_name]
option_a = a_value
```

The above is the bug I'm trying to report. 

> Are you saying if section= is not specified, it should assume something
> outside of a section block, or that section= should not have a default
> named "default" ?

About option/values not belonging to any sections, maybe we could add a section=None as section is a required  module parameter?

**Comment by jpmens** [comment]
Issue confirmed. From the ConfigParser documentation:

> If the name DEFAULT (or any of it’s case-insensitive variants) is passed, ValueError is raised.

which raises a #WTF here with me ...

**Comment by jpmens** [comment]
Module now allows changing settings in existing `[default]` section and fails with diagnostic if user tries to _add_ `[default]` section to an ini file which doesn't have that.

**Comment by hyao** [comment]
just for future reference, python 3.2 has an updated configparser module, and backported as a separate package (http://pypi.python.org/pypi/configparser/3.2.0r3). 

And based on its doc: http://docs.python.org/3/library/configparser.html
It seems to support Default section now. 

But I guess that we may not want to add another module dependency

**Comment by jpmens** [comment]
Yeah, I don't think we should add that.

**Comment by mpdehaan** [comment]
I am confused why we can't when the name is just a string.

It seems if someone wants to say section=default that should be fine?

Maybe I'm not understanding the issue.

**Comment by jpmens** [comment]
The issue is that ConfigParser docs specify: "If the name DEFAULT (or any of it’s case-insensitive variants) is passed, ValueError is raised.". I take that to mean ConfigParser CANNOT create a [default] section, and tests here prove that to be the case.

**Comment by mpdehaan** [comment]
see comments on #1692, it seems this is an implementation issue.  It is highly unlikely many people will install the backport in this case, so what we have seems workable.

I would suggest that if this is a problem you install the file with 'copy' or 'template' as a workaround.

**Comment by berendt** [comment]
This should be fixed. Because it's a limitation of ConfigParser (in Python 2) or configparser (in Python 3) that module should be rewritten using something else. There are enough modules available on PyPi. I can take care of this issue. Because I want to deploy OpenStack with Ansible I have to modify the DEFAULT section in INI-like files. I think to use workarounds for this issue is not the right way to handle this issue, because the issue is only there because of limitations in the used module.

@mpdehaan Please re-open this issue.

**Comment by berendt** [comment]
Sorry for the both wrong references before. I had some issues with git...
