### ISSUE TITLE
debug strategy fails to import linear

### ISSUE THREAD

**Issue by timka** [ansible/ansible#16825]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No manual changes
##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

There's a bug in `ansible.plugins.strategy.debug`:
It says

```
    from ansible.plugins.strategy import linear
```

while linear is not present in `/usr/lib/python2.7/dist-packages/ansible/plugins/strategy/__init__.py`. Therefore the import fails.
##### STEPS TO REPRODUCE

Put `strategy: debug` under hosts in you playbook.

```
- hosts: staging
  strategy: debug
#…
```

##### EXPECTED RESULTS

Debugger started when something breaks
##### ACTUAL RESULTS

ImportError exception is raised

```
PLAY [staging] *****************************************************************
ERROR! Unexpected Exception: cannot import name linear
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 92, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 142, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 225, in run
    strategy = strategy_loader.get(new_play.strategy, self)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 333, in get
    self._module_cache[path] = self._load_module_source('.'.join([self.package, name]), path)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 319, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/strategy/debug.py", line 9, in <module>
    from ansible.plugins.strategy import linear
ImportError: cannot import name linear
```

**Comment by jimi-c** [comment]
@timka I think there is something else going on here. The file linear.py should be there in that directory, and should work fine during a normal install (I cannot reproduce this).

**Comment by timka** [comment]
@jimi-c linear.py is there

Anything else I can do to get more info?

**Comment by jimi-c** [comment]
@timka how are you installing Ansible? And have you reproduced this on the stable-2.1 or devel branches?

**Comment by timka** [comment]
@jimi-c I was using pip install. I'll try reproducing this in clean environment once I get less time pressure

**Comment by timka** [comment]
@jimi-c Sorry, my bad. It was actually from distro package.

Pip-installed from devel works OK.

**Comment by jimi-c** [comment]
We did identify another scenario in which this bug can occur regardless of installation method, so I've pushed a commit to fix it.

Thanks again!
