### ISSUE TITLE
ansible-playbook --limit not working with overlapping host aliases

### ISSUE THREAD

**Issue by sragatsky** [ansible/ansible#16851]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

ansible 2.1.0.0
##### SUMMARY

when having same host aliases under different groups, the limit command ignores it
and just picks the last alias found
##### STEPS TO REPRODUCE

create inventory:

```
[staging1]
app1 ansible_host=host.domain.com ansible_ssh_port=2222  
app2 ansible_host=host.domain.com ansible_ssh_port=2223  
app3 ansible_host=host.domain.com ansible_ssh_port=2224  

[staging2]
app1 ansible_host=host.domain.com ansible_ssh_port=2225  
app2 ansible_host=host.domain.com ansible_ssh_port=2226  
app3 ansible_host=host.domain.com ansible_ssh_port=2227  
```

run 

```
ansible-playbook --limit="staging1:app3"  my-playbook.yml -i my_inventory  -vvv
```
##### EXPECTED RESULTS

tasks are executed against  `app3 ansible_host=host.domain.com ansible_ssh_port=2224`
in group `staging1`
##### ACTUAL RESULTS

tasks are executed against  `app3 ansible_host=host.domain.com ansible_ssh_port=2227`
in group `staging2`

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Hostvars are flattened previous to any selection, using all groups a host is part of, neither `hosts:` nor `--limit` change this, they only select which hosts get processed, not which variables are used.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
