### ISSUE TITLE
Typo in fireball mode section

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1686]
"Fireball Mode

New in version 0.8.

Paramiko’s core connection types of ‘local’, ‘paramiko’, and ‘ssh’ are augmented in version 0.8 by a new extra-fast connection type called ‘fireball’. It can only be used with playbooks and does require some additional setup outside the lines of ansible’s normal “no bootstrapping” philosophy. You are not required to use fireball mode to use Ansible, though some users may appreciate it."

Should read "Ansible's core..."

**Comment by dhozac** [comment]
Fixed in 9870224
