### ISSUE TITLE
ERROR! conflicting action statements (debug, with_items)

### ISSUE THREAD

**Issue by robhall** [ansible/ansible#16860]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
Robleys-MBP:ansible robley$ ansible --version
ansible 2.0.2.0
  config file = /Users/robley/.ansible.cfg
  configured module search path = /Users/robley/projects/ansible
Robleys-MBP:ansible robley$ 
```
##### CONFIGURATION

contents of ~/.ansible.cfg

```
[defaults]
host_key_checking = False
library = /Users/robley/projects/ansible
log_path=~/projects/ansible/ansible.log
retry_files_enabled=False
```
##### OS / ENVIRONMENT

OSX El Capitan 10.11.4
##### SUMMARY

Using "with_items:" fails and issues message:

```
ERROR! conflicting action statements (debug, with_items)
```

However, this is environment dependent. The failing system is OSX with ansible 2.0.2. I have a different OSX system with ansible 2.0.1 where this playbook works correctly. I also have centos systems running ansible 2.0.2 where the playbook runs correctly.

Both my failing and my working OSX envs are running the OSX python 2.7.5

```
Robleys-MBP:ansible robley$ python 
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

As I say I can tell that this is clearly an issue specific to one system and so probably an environment  problem but exactly what I can't tell. I've tried uninstalling ansible and pip and re-installing without any luck.
##### STEPS TO REPRODUCE

Run the playbook below:

```

---
- hosts: localhost
  connection: local

  tasks:
    - name: loop failing
      debug: msg="loop {{ item }}"
      with_sequence: start=0 end=0
```
##### EXPECTED RESULTS

output from the task like this:

```
TASK [loop failing] ************************************************************
ok: [localhost] => (item=0) => {
    "item": "0", 
    "msg": "loop 0"
}
```
##### ACTUAL RESULTS

```
Robleys-MBP:ansible robley$ ansible-playbook -i hosts w.yml -vvv
Using /Users/robley/.ansible.cfg as config file
ERROR! conflicting action statements (debug, with_sequence)

The error appears to have been in '/Users/robley/projects/ansible/w.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: loop failing
      ^ here


The error appears to have been in '/Users/robley/projects/ansible/w.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: loop failing
      ^ here

Robleys-MBP:ansible robley$ 

```

**Comment by jctanner** [comment]
@robleyhall I am able to reproduce this if I delete all of the installed ansible modules, thereby making debug an unknown module. Ansible then believes debug is a keyword on the task rather than a module name and produces the "conflicting action statements" message. I notice in your ansible.cfg example that you've specified a library path which makes me suspect you have a unusual installation of ansible.

Please clean out any existing ansible installs on your system and re-install ansible. You should have a long list of modules in the "ansible-doc -l" output. If you need further help, please use the mailing list or irc.

**Comment by alikins** [comment]
Also, with version versions 2.1+, ansible will warn if it doesn't find any core modules.
That was added as a fix for https://github.com/ansible/ansible/issues/11206 which is a similar issue.

**Comment by robhall** [comment]
Thanks @jctanner that's a good clue to the problem... in fact ansible-doc -l fails like this on my broken system:

```
Robleys-MBP:ansible robley$ ansible-doc -l
ERROR! module ansible_module_template has a documentation error formatting or is missing documentation

Robleys-MBP:ansible robley$ 
```

whereas on my working system does have a long list of modules as you say.

This is a fresh install of ansible via pip as per the doc so not sure yet where the problem is but you've given me a starting point to chase down. Thanks for the quickly reply.

**Comment by robhall** [comment]
@jctanner @alikins Ok it was a quick fix, removing the library spec from my .ansible.cfg fixed the issue. This is a config that I've had on this system (I was just trying to pickup a custom module from a local dir on a dev system), has the behavior of library in .ansible.cfg possibly changed recently? I.e.; from "add" (this directory as a search location) to "replace" the search location? In any case my issue is resolved, so thanks again.
