### ISSUE TITLE
Why a progress over when ansible exec all tasks on windows?

### ISSUE THREAD

**Issue by fcxjluo** [ansible/ansible#16867]
ansible 2.2.0
I use raw module to run a bat,and the bat exec a jar,the jar will always run because it's a  monitoring program。But when ansible exec the taks over,the jar will also over,why?

**Comment by ypid** [comment]
Just saw this by accident. You might want to add a bit more information and/or follow the suggestion given in https://github.com/ansible/ansible/issues/16813#issuecomment-235001543.

**Comment by jhawkesworth** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
