### ISSUE TITLE
Error "invalid selinux context" in copy module when using vxfs (veritas cluster) filesystem

### ISSUE THREAD

**Issue by SimBou** [ansible/ansible#16874]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

ansible 2.0.2.0
ansible 2.1.0.0
##### CONFIGURATION

[selinux]
special_context_filesystems=nfs,vboxsf,fuse,vxfs
##### OS / ENVIRONMENT

RHEL 7.2 with SELinux in permissive
##### SUMMARY

Copy module fails to transfert a file when the destination is on an vxfs filesystem on a server with SELinux in permissive enabled.
It works well when SELinux is totaly disabled.
msg: invalid selinux context
##### STEPS TO REPRODUCE

On CLI:
ansible all -i server, -m copy -a "src=test_file dest=/path/on/vxfs/filesystem/"
I have the same error within a playbook.

Output:
ansible all -i server, -m copy -a "src=test_file dest=/applis/test/"
sever| FAILED! => {
    "changed": false,
    "checksum": "9012b2e777fbed549591be2d03c6917d5debc571",
    "cur_context": [
        "unconfined_u",
        "object_r",
        "vxfs_t",
        "s0"
    ],
    "failed": true,
    "gid": 397,
    "group": "my_group",
    "input_was": [
        "system_u",
        "object_r",
        "default_t",
        "s0"
    ],
    "mode": "0600",
    "msg": "invalid selinux context: [Errno 95] Operation not supported",
    "new_context": [
        "system_u",
        "object_r",
        "vxfs_t",
        "s0"
    ],
    "owner": "my_user",
    "path": "/applis/test/.ansible_tmplgGRRMtest_file",
    "secontext": "unconfined_u:object_r:vxfs_t:s0",
    "size": 185311,
    "state": "file",
    "uid": 13906
}
##### EXPECTED RESULTS

File copied on remote directory
##### ACTUAL RESULTS

Nothing done

**Comment by SimBou** [comment]
moving into ansible-modules-core
#4280

**Comment by nadavkav** [comment]
I am getting the same error, trying to copy a template into a NFS mount
Disabling SELinux... everything works fine

**Comment by murthyguntuku** [comment]
ansible all -i server, -m copy -a "src=test_file dest=/path/on/vxfs/filesystem/ setype=vxfs_t" 

should work

**Comment by ElCoyote27** [comment]
@murthyguntuku 'setype=vxfs_t' doesn't work for me on ansible 2.x (up to and including 2.6.1).
As a workaround, I'm using 'synchronize' instead of 'copy' :(

**Comment by ElCoyote27** [comment]
I am happy to report that ansible copy now works fine with RHEL 7.6 (Note that I am still running the latest el7.5 z-stream kernel because Veritas hasn't released updated kernel modules yet):


```
[root@myhost ~]# ansible -m copy -a 'src=/etc/hosts dest=/shared/vxf0/hosts' localhost
localhost | SUCCESS => {
    "changed": true,
    "checksum": "370f7dbaa1d7661319df2f17be1960574734b964",
    "dest": "/shared/vxf0/hosts",
    "gid": 0,
    "group": "root",
    "md5sum": "1a29f427e32d8f23e94d4589f2fdbb19",
    "mode": "0644",
    "owner": "root",
    "secontext": "system_u:object_r:unlabeled_t:s0",
    "size": 1701,
    "src": "/root/.ansible/tmp/ansible-tmp-1541095322.21-140467518302821/source",
    "state": "file",
    "uid": 0
}
[root@myhost ~]# ansible -m copy -a 'src=/etc/hosts dest=/shared/vxf0/hosts' localhost
localhost | SUCCESS => {
    "changed": false,
    "checksum": "370f7dbaa1d7661319df2f17be1960574734b964",
    "dest": "/shared/vxf0/hosts",
    "gid": 0,
    "group": "root",
    "mode": "0644",
    "owner": "root",
    "path": "/shared/vxf0/hosts",
    "secontext": "system_u:object_r:unlabeled_t:s0",
    "size": 1701,
    "state": "file",
    "uid": 0
}
[root@myhost ~]# mount -v|grep vxfs0
/dev/vx/dsk/local00dg/vxfs0_lv on /shared/vxf0 type vxfs (rw,seclabel,delaylog,largefiles,noatime,ioerror=mwdisable)

[root@myhost ~]# lsb_release -a
[....]
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.6 (Maipo)
Release:        7.6
Codename:       Maipo
[...]

[root@myhost ~]# uname -r
3.10.0-862.14.4.el7.x86_64

```

**Comment by salapat11** [comment]
@ElCoyote27 - how did you get the copy working on Veritas file system?  Did you have to update any settings?

**Comment by ElCoyote27** [comment]
@salapat11 In RHEL 7.6, there are some updated SELinux policies that make this possible. Thus, any el7.6 system should automatically have those policies (probably centos7.6 too but I didn't check that).

**Comment by salapat11** [comment]
Thanks @ElCoyote27
