### ISSUE TITLE
Investigate multiprocessing fork affinity as a way to enable caching systems

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1688]
If the host gets a particular fork, it should always get that fork

The idea being, if we do this, it allows for enabling the paramiko connection cache as the host won't get hopped over to a place where it doesn't have the connection handle, and so on

This could probably be implemented as having a global hash of contacted hostnames and the number of the fork that first serves them.  Forks that have nothing to do would finish early.

This may also enable exploration with stuff like execnet (unknown viability here, but seems quite interesting) and also some controllable setting about how many connections (in general, perhaps something connection type agnostic) to decide how many connections to leave open.

cc @dhozac

**Comment by mpdehaan** [comment]
I want to look at this for 1.0, so making a note so I don't forget.

**Comment by hpk42** [comment]
I maintain that using gevent instead of multiprocessing might also make sense.  Is there anything or can you write down a few sentences on how multiprocessing is used/needed currently and which communication crosses process boundaries?

**Comment by mpdehaan** [comment]
Investigated gevent, wasn't so simple, will dig up details later...

-- Michael

**Comment by hpk42** [comment]
I can imagine trying to hack gevent into ansible at some point, based on a better understanding on how ansible uses multiprocessing.  I think execnet could also be of use, but it's probably an unrelated issue and would come into play once gevent speeds up things considerably already :)

**Comment by mpdehaan** [comment]
Let's keep the other discussion on the mailing list if we can.   This is about a very specific feature aspect that is unrelated to gevent, that also has immediate benefits to paramiko caching and elsewhere.

**Comment by mpdehaan** [comment]
ok, so promised follow up with gevent, BTW ... looked into this a while previously, there are two basic issues.  It does not seem that when using native openssh gevent buys us anything with respect to async.   Two, the usage of multiprocessing+gevent (see stackoverflow) seemed rather invasive.

I am open, however, to patches that completely replace multiprocessing if that makes sense -- not sure it does, provided gevent is available everywhere or it gracefully degrades to multiprocessing where not... it seems the latter would need to be the case.

I think the best thing we can do is really get to a point where we can cache connections by assuring each object finds its way to the right fork using multiprocessing -- since that's going to be the most backwards compatible and doesn't add any extra deps -- let me know if I'm wrong about that.

(further discussion really should happen on the list though so we can engage everyone interested in development aspects)

**Comment by mpdehaan** [comment]
nothing happening on this
