### ISSUE TITLE
during [setup] parse_ip_output fails when using wireguard interfaces

### ISSUE THREAD

**Issue by danrl** [ansible/ansible#16889]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

none
##### OS / ENVIRONMENT

from: OSX
to: Debian Linux Jessie
##### SUMMARY

When using wireguard (see wireguard.io), new network interfaces show up. E.g. wg0. Ansible fails to parse these when gathering facts during [setup].
##### STEPS TO REPRODUCE

On destination: ip link add dev wg0 type wireguard
On source: run any ansible-playbook for destination

```
anything goes
```

##### EXPECTED RESULTS

gathering facts
##### ACTUAL RESULTS

ansible fails

```

PLAY [apply common configuration to all hosts] *********************************

TASK [setup] *******************************************************************
fatal: [scr]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_U0_ydr/ansible_module_setup.py\", line 127, in <module>\r\n    main()\r\n  File \"/tmp/ansible_U0_ydr/ansible_module_setup.py\", line 119, in main\r\n    data = get_all_facts(module)\r\n  File \"/tmp/ansible_U0_ydr/ansible_modlib.zip/ansible/module_utils/facts.py\", line 3177, in get_all_facts\r\n  File \"/tmp/ansible_U0_ydr/ansible_modlib.zip/ansible/module_utils/facts.py\", line 3123, in ansible_facts\r\n  File \"/tmp/ansible_U0_ydr/ansible_modlib.zip/ansible/module_utils/facts.py\", line 1988, in populate\r\n  File \"/tmp/ansible_U0_ydr/ansible_modlib.zip/ansible/module_utils/facts.py\", line 2184, in get_interfaces_info\r\n  File \"/tmp/ansible_U0_ydr/ansible_modlib.zip/ansible/module_utils/facts.py\", line 2155, in parse_ip_output\r\nValueError: need more than 1 value to unpack\r\n", "msg": "MODULE FAILURE", "parsed": false}

NO MORE HOSTS LEFT *************************************************************
```

**Comment by danrl** [comment]
That's what crashes the parser:

```
# ip a s dev wg1
5: wg1: <POINTOPOINT,MULTICAST,NOARP,200000> mtu 1423 qdisc noop state DOWN group default qlen 1
    link/none 
    inet6 fd00:200::1 peer fd00:200::2/128 scope global 
       valid_lft forever preferred_lft forever
```

**Comment by danrl** [comment]
Same error when interface is UP.

```
# ip a s dev wg1
5: wg1: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1423 qdisc noqueue state UNKNOWN group default qlen 1
    link/none 
    inet6 fd00:200::1 peer fd00:200::2/128 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::c77f:7bd1:e9e1:9245/64 scope link flags 800 
       valid_lft forever preferred_lft forever
```

**Comment by alikins** [comment]
This looks similar to https://github.com/ansible/ansible/issues/15448 which has a commit to fix it in the devel branch [af150ea43ad6f6dd83ee975f2d11cb55b3dc689c]

Would it be possible to test this scenario with a version of ansible from the devel branch? If that fixes this as well as 15448, that commit will likely be backported to 2.1.x

**Comment by alikins** [comment]
Looking closer at the change in https://github.com/ansible/ansible/commit/af150ea43ad6f6dd83ee975f2d11cb55b3dc689c and now I suspect it won't fix this case and
will need a more general fix.

**Comment by danrl** [comment]
I guess eventually one wants to use RTNETLINK to fetch all this data instead of parsing `ip` output. Don't know how easy it is to user RTNETLINK sockets (and all the many data sctructs it comes with) in python.

**Comment by danrl** [comment]
I fixed it locally (older version) and looked at af150ea closely. I am sure it will fix the issue. Just have to wait until the fix reaches end users via distributions.

**Comment by danrl** [comment]
Backported af150ea locally real quick. It does fix the issue. Closing it. Please re-open if you object.
