### ISSUE TITLE
add_host module in v2.1.1.0 does not follow paths with forward slash

### ISSUE THREAD

**Issue by Blackbaud-BenKrebsbach** [ansible/ansible#16881]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Amazon Linux 4.4.11-23.53.amzn1.x86_64
##### SUMMARY

In v2.1.1.0, the add_host module will no longer pick up group_vars if the group name includes a forward slash. This worked in v2.1.0.0 and v2.0.0.1.
##### STEPS TO REPRODUCE

Create a simple playbook structure as follows:

```
group_vars/dir1/foo.yml
play.yml
```

Run `ansible-playbook play.yml`

```
#######
# play.yml
#######
- hosts: localhost
  gather_facts: no
  tasks:
    - add_host:
        name: '{{inventory_hostname}}'
        groups: 'dir1/foo'
    - debug: var=bar
```

```
#######
# foo.yml
#######
bar: 'abc'
```

##### EXPECTED RESULTS

With this playbook, we would expect to see the value of bar printed.
These are the results when running Ansible v2.1.0.0:

```
ansible-playbook play.yml -vvvv
No config file found; using defaults
 [WARNING]: Host file not found: /etc/ansible/hosts
 [WARNING]: provided hosts list is empty, only localhost is available
Loaded callback default of type stdout, v2.0

PLAYBOOK: play.yml *************************************************************
1 plays in play.yml

PLAY [localhost] ***************************************************************

TASK [add_host] ****************************************************************
task path: /tmp/test/play.yml:4
creating host via 'add_host': hostname=localhost
changed: [localhost] => {"add_host": {"groups": ["dir1/foo"], "host_name": "localhost", "host_vars": {}}, "changed": true, "invocation": {"module_args": {"groups": "dir1/foo", "name": "localhost"}, "module_name": "add_host"}}

TASK [debug] *******************************************************************
task path: /tmp/test/play.yml:7
ok: [localhost] => {
    "bar": "abc"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```
##### ACTUAL RESULTS

In v2.1.1.0, bar is undefined, implying the group_vars/dir1/foo.yml is not being included.
This is what happens when running the same playbook using v2.1.1.0

```
ansible-playbook play.yml -vvvv
No config file found; using defaults
 [WARNING]: Host file not found: /etc/ansible/hosts
 [WARNING]: provided hosts list is empty, only localhost is available
Loaded callback default of type stdout, v2.0

PLAYBOOK: play.yml *************************************************************
1 plays in play.yml

PLAY [localhost] ***************************************************************

TASK [add_host] ****************************************************************
task path: /tmp/test/play.yml:4
creating host via 'add_host': hostname=localhost
changed: [localhost] => {"add_host": {"groups": ["dir1/foo"], "host_name": "localhost", "host_vars": {}}, "changed": true, "invocation": {"module_args": {"groups": "dir1/foo", "name": "localhost"}, "module_name": "add_host"}}

TASK [debug] *******************************************************************
task path: /tmp/test/play.yml:7
ok: [localhost] => {
    "bar": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

**Comment by alikins** [comment]
This may potentially be related to some localhost related changes (https://github.com/ansible/ansible/commit/5f1bbb4fcdea21b106367a5a426dc6f2b4851b9c and some related changes).

Do you see the same failure if the target hosts is not 'localhost'?

**Comment by alikins** [comment]
ping @jimi-c , @bcoca

**Comment by Blackbaud-BenKrebsbach** [comment]
@alikins same behavior when targeting a remote host as localhost.

**Comment by bcoca** [comment]
I would say that 'dir1/foo' is not a valid group name

**Comment by Blackbaud-BenKrebsbach** [comment]
@bcoca if that's the case, it limits group_vars to a depth of one, which makes naming conventions and organization much more difficult.

By allowing slashes in the group name, you can use add_host to include sets of variables on the fly, and you get the benefit of potentially have a global set of vars (group_vars relative to the inventory file) that is overwriteable with local variables using the same name (group_vars relative to the playbook). 

It is an incredibly useful feature which is not replicated by include_vars, since that only pulls in one file at a time, and only allows role/playbook specific variables (also, variables pulled in from vars are very hard to overwrite, whereas group_vars variables are much easier to overwrite).

**Comment by juliedavila** [comment]
I agree with @bcoca, that's not something I would advise doing. The way you explain it in your OP would, to me, imply that you have a group_vars file `foo.yml` that is to be associated with the inventory group `dir1`. In case you didn't know, in `group_vars/db`, **db** can be a file or a directory with variable content that will get associated to hosts that are assigned to that group.

group_vars/all already satisfies the desire for a global group_var and anything defined in a more specific group would overwrite the stuff in `all`.

**Comment by Blackbaud-BenKrebsbach** [comment]
@defionscode @bcoca 

i used the example above with a single file because it's the simplest example. more often than not, i'm concerned with the case where foo is a directory with multiple files. if there are multiple nested directories, e.g. `dir1/foo/{bar,car}/*.yml`, in 2.1.0 i can include `dir1` to include all the vars, or i can be more selective by using `dir1/foo/bar`,etc., to get a subset of the variables. 

the problem with `group_vars/all` is that you pick up **all** the variables there, regardless of if you want them or not. this pollutes the namespace of variables available, and can cause a big headache if you have lots of downstream roles that use set_facts.

once a variable is declared in ansible, there is no way to unset it, only overwrite its value. in that paradigm, being able to selectively include a global set of variables across multiple playbooks is crucial. otherwise, you'd have to create duplicate variables in multiple inventory files (and duplicating data in multiple locations is a good way to ensure your data gets stale)

it can be argued that the add_host method i'm leveraging in 2.1.0 and earlier is not ideal, but with no alternative mechanism in place, i think it probably needs to be carried forward.

**Comment by jimi-c** [comment]
@Blackbaud-BenKrebsbach, @defionscode's point was that if you simply used `dir1` in your example above, it would include all files in that directory. Now, we do not allow (nor do we have any plans to) that directory depth to exceed one level, but that has not been a limitation others have had a problem with in the past.

If you would like to discuss this further, I would recommend either submitting a proposal for the feature idea or discussing it on the devel mailing list/IRC channel.

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
