### ISSUE TITLE
Provide a module for dealing with Amazon RDS Security Groups in 'Classic' mode.

### ISSUE THREAD

**Issue by darkl0rd** [ansible/ansible#16892]
- Feature Idea

Provide a module for dealing with RDS (classic) security groups.

Suggested implementation:

rds_security_group:
  name: rds_group_name
  state: present
  authorizations:
    - ec2_group: 'ec2_group_name'
    - cidr_ip: 'cidr_ip_range'
  purge_existing: True

**Comment by alikins** [comment]
This appears to be a submission about a module.

We would appreciate if you can submit this there (https://github.com/ansible/ansible-modules-extras)
instead. (If we move it, the owner of the issue resets to ansible instead of you).
