### ISSUE TITLE
Openstack Dynamic Inventory Script

### ISSUE THREAD

**Issue by gvenka008c** [ansible/ansible#16895]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
 ansible --version
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

I tried setting multiple group names using nova meta tag as below but couldn't get that working using openstack.py dynamic inventory script for openstack. Can you please suggest?

http://docs.ansible.com/ansible/intro_dynamic_inventory.html#example-openstack-external-inventory-script

```
$nova meta hostname set "group=mesos_masters"

$ansible -i inventory/openstack.py mesos_masters -m ping
b9d2e61e | SUCCESS => {
    "changed": false,
    "ping": "pong"
}

$nova meta hostname set "group=mesos_masters,consul_bootstrap"

$ansible -i inventory/openstack.py mesos_masters -m ping
 [WARNING]: provided hosts list is empty, only localhost is available

##### STEPS TO REPRODUCE
<!---
see above
-->



##### EXPECTED RESULTS
Should be able to run the playbook fetching the list of hosts

##### ACTUAL RESULTS

```

: provided hosts list is empty, only localhost is available

```
```

**Comment by gvenka008c** [comment]
@here... any help on this? Thanks.

**Comment by alikins** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
  
  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.
