### ISSUE TITLE
localhost and 127.0.0.1 detected as different hosts since 2.1.1.0 version

### ISSUE THREAD

**Issue by DanOfir** [ansible/ansible#16896]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

**hosts file:**

[localhost]
127.0.0.1

[localhost:vars]
ansible_connection=local
##### OS / ENVIRONMENT

UBUNTU 16.04 LTS

##### SUMMARY

Running a playbook with inventory file which have group of 127.0.0.1 and also with localhost as a host cause the playbook to be executed as if we have 2 hosts, but the commands actually runs on the same host, and can be faulty depends on the tasks.
##### STEPS TO REPRODUCE

```
command:

ansible-playbook -i inventory/hosts playbook.yml

playbook:

- hosts: localhost
  connection: local
  tasks:
    - foo
```

##### EXPECTED RESULTS

==> default: TASK [setup] *******************************************************************
==> default: ok: [127.0.0.1]
==> default: 
==> default: TASK [foo] *****************************************************
==> default: ok: [127.0.0.1 -> localhost]
##### ACTUAL RESULTS

==> default: TASK [setup] *******************************************************************
==> default: ok: [127.0.0.1]
==> default: ok: [localhost]
==> default: 
==> default: TASK [foo] *****************************************************
==> default: ok: [localhost -> localhost]
==> default: ok: [127.0.0.1 -> localhost]

I could bypass this issue by changing my command to:
**ansible-playbook -i localhost, playbook.yml**

```

```

**Comment by offlinehoster** [comment]
Duplicate -> https://github.com/ansible/ansible/issues/16886 ?

**Comment by DanOfir** [comment]
Maybe it's the same root problem. but different behavior.

**Comment by bcoca** [comment]
confirmed, closing as dup of #16886
