### ISSUE TITLE
(s)rpm building unittests

### ISSUE THREAD

**Issue by timlnx** [ansible/ansible#169]
Make some unittests for building (s)rpms.

**Comment by mpdehaan** [comment]
does not compute, please explain.

remember unit tests are going to be run on people from all platforms, so it seems like "make rpms" is the test

**Comment by timlnx** [comment]
This is a consistency thing. Store a canonical test for the build-system with the rest of the unit tests.

It ends up letting you run one command to:
- Build the rpm && srpm
- Capture the build logs for both (instead of screen vomit)
- See the individual build results
- Check that the files are building with the correct names && versions

So there is some actual sanity checking introduced. Let me know if you're not interested.

**Comment by mpdehaan** [comment]
Yeah I don't think this is unit test kind of stuff, IMHO, and would rather not maintain it.   Most projects don't go that far.
