### ISSUE TITLE
docker module requires python-docker-py

### ISSUE THREAD

**Issue by jeremyeder** [ansible/ansible#16906]
- Bug Report
##### ANSIBLE VERSION

```
# ansible --version
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

RHEL 7.2
##### SUMMARY

Using the docker module requires python-docker-py to be installed
##### STEPS TO REPRODUCE

```
$ cat playbooks/roles/svt-setup/tasks/main.yaml 

---
- name: pull containers used by svt tests
  docker_image: "name='{{ item }}' state=present"
  with_items:
    - openshift/hello-openshift
    - kubernetes/pause
```

```
TASK [svt-setup : pull containers used by svt tests] ***************************
Monday 01 August 2016  15:18:50 -0400 (0:08:53.555)       0:18:03.909 ********* 
failed: [10.12.23.27] (item=openshift/hello-openshift) => {"failed": true, "item": "openshift/hello-openshift", "msg": "Failed to import docker-py - No module named docker. Try `pip install 
docker-py`"}
failed: [10.12.23.27] (item=kubernetes/pause) => {"failed": true, "item": "kubernetes/pause", "msg": "Failed to import docker-py - No module named docker. Try `pip install docker-py`"}
```
##### EXPECTED RESULTS

I thought since it's a module shipped by ansible that it would include all the necessary dependencies to use it.

On RHEL, the dependency can be resolved by installing python-docker-py (shipped by Red Hat) prior to using the ansible docker module.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

As documented here (and in the module iteslf) http://docs.ansible.com/ansible/docker_module.html#requirements-on-host-that-executes-module
this is a requirement.

There are many modules that have extra requirements, which they must state in the module docs.
In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by jeremyeder** [comment]
got it. thanks. im new here.
