### ISSUE TITLE
with_file handled before when condition

### ISSUE THREAD

**Issue by joba12** [ansible/ansible#16917]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

If a task includes a when statement and a with_file iteration, the when condition is handled after the with_file iteration.
If the files mentioned in with_file do not exist, the task will fail, even if it should be skipped because the when condition is not true
##### STEPS TO REPRODUCE
- create a ansible playbook with below content
- run the playbook, it will fail

Playbook:

```

---
- hosts: localhost
  tasks:
    - name: with_file testcase
      debug:
        msg: test
      with_file:
        - test
      when: 0
```
##### EXPECTED RESULTS

skip the task
##### ACTUAL RESULTS

The playbook fails, until the file mentioned in with_file is created

```
[user@host ~]$ ansible-playbook with_files_testcase.yml
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [with_file testcase] ******************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the file_name '/home/user/test' does not exist, or is not readable"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @with_files_testcase.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

```
[user@host ~]$ touch test
```

```
[user@host ~]$ ansible-playbook with_files_testcase.yml
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [with_file testcase] ******************************************************
skipping: [localhost] => (item=)

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

As documented here http://docs.ansible.com/ansible/playbooks_conditionals.html#loops-and-conditionals, `when:` always executes inside a `with_` loop to be able to apply the condition per item.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
