### ISSUE TITLE
with_items using empty list treated differently in 2.1.1 in comparison to 2.1.0

### ISSUE THREAD

**Issue by LarsFronius** [ansible/ansible#16919]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible-playbook 2.1.1.0
```
##### OS / ENVIRONMENT

Tested on MacOS/Ubuntu
##### SUMMARY

Under 2.1.1 with_items is being treated differently than on 2.1.0, considering it's a minor update I did not expect breaking changes.
##### STEPS TO REPRODUCE

Given I have a file called foo.yml

```
- hosts: localhost
  become: no
  tasks:
    - name: foo
      debug:
        msg: "{{ item }}"
      with_items: "{{ [] | list | to_json }}"

```

and I run it with `ansible-playbook --version => ansible-playbook 2.1.1.0`
I get

```
ansible-playbook foo.yml 
 [WARNING]: Host file not found: inventory

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [foo] *********************************************************************
ok: [localhost] => (item=[]) => {
    "item": "[]", 
    "msg": []
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

however, if I run it with `ansible-playbook --version => ansible-playbook 2.1.0.0`

```
ansible-playbook foo.yml 
 [WARNING]: Host file not found: inventory

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [foo] *********************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```
##### EXPECTED RESULTS

I expected both version to work the same way.
##### ACTUAL RESULTS

`with_items: "[]"` is suddenly being treated as the string it is in 2.1.1, whereas in versions before it was treated as a list of no items - which is breaking a lot of logic in our playbooks.

If we did things incorrectly/against the idea how it should be done with Ansible, if somebody could provide me with a good example for the case a list is empty, it would help a lot.

**Comment by jctanner** [comment]
@LarsFronius I might be missing context because the example is contrived, but what is the purpose of using to_json?

In 2.1.0 and 2.1.1 I get the behavior you are expecting if I drop the to_json filter and only use list.

**Comment by bcoca** [comment]
the changed behavior is not in with_items, it is that to_json is actually "working" and returning a string. So fixing the bug with to_json broke this misuse of it.

Also list and templating are not needed for a simple empty list.

```
with_items: [] 
```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by LarsFronius** [comment]
What is the right way to work with e.g.:
say I have a var that is being filled from a result of
`ls /tmp/foobar/*`
it might include a list of files but might also be empty.

If I wanted to use this list, before I had done the following:

```
debug:
  msg: "{{ item }}"
with_items: "{{ result.stdout | split('\n') | to_json }}"
```

not saying this was the correct and intended way - but how was I supposed to do this in the first place?

**Comment by bcoca** [comment]
`with_items: "{{ result.stdout_lines}}"`
