### ISSUE TITLE
Tasks with iterables hang for around 30 seconds when included in a task file that uses a higher level conditional

### ISSUE THREAD

**Issue by cloudnull** [ansible/ansible#16913]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /opt/openstack-ansible/playbooks/ansible.cfg
  configured module search path = ['/etc/ansible/roles/plugins/library']
```
##### CONFIGURATION

``` cfg
[defaults]
log_path = /openstack/log/ansible-logging/ansible.log
# Set the role path
roles_path = /etc/ansible/roles:roles
retry_files_enabled = False

# Additional plugins
lookup_plugins = /etc/ansible/roles/plugins/lookup
filter_plugins = /etc/ansible/roles/plugins/filter
action_plugins = /etc/ansible/roles/plugins/action
library = /etc/ansible/roles/plugins/library

# Fact caching
gathering = smart
fact_caching = jsonfile
fact_caching_connection = /etc/openstack_deploy/ansible_facts
fact_caching_timeout = 86400

inventory = inventory
host_key_checking = False

# SSH timeout
timeout = 6
transport = ssh

[ssh_connection]
pipelining = True
```
##### OS / ENVIRONMENT

Running on Ubuntu 14.04 and 16.04 installed from pip
##### SUMMARY

Recently I've been looking into how to get more performance out of our roles and playbooks and discovered that when using an include and a conditional that loads a task file containing tasks which use lookup plugins (specifically the `items` plugin) the task will hang for roughly 30 seconds per item in the list.
##### STEPS TO REPRODUCE

Example include task: [ https://github.com/openstack/openstack-ansible-os_swift/blob/d0c001c5e6fccb4c928cb814352e2dcd3c9a16ba/tasks/swift_init_common.yml#L22-L26 ]
Example task that hangs: [ https://github.com/openstack/openstack-ansible-os_swift/blob/d568b871833e9a81a1612ad9cc071ca504fad79c/tasks/swift_init_systemd.yml#L16-L28 ]
Example fix: [ https://review.openstack.org/#/c/349763/2/tasks/swift_init_systemd.yml ]

The playbook executed can be found here: [ https://github.com/openstack/openstack-ansible/blob/91deb13/playbooks/os-swift-install.yml ]

##### EXPECTED RESULTS

The task should not hang
##### ACTUAL RESULTS

When testing the entire playbook against a cluster that had already been deployed the run time was "6m43.042s" and with the iterator removed it was "4m4.486s". I've not been able to pinpoint specifically where the slowdown is however I can confirm that if I remove the lookup plugin from the task and break things out into multiple tasks the "hang" no longer exists.

```
time ansible-playbook -e @/etc/openstack_deploy/user_secrets.yml -e @/etc/openstack_deploy/user_variables.yml os-swift-install.yml 
```

**Comment by odyssey4me** [comment]
@cloudnull The tasks that hangs has now changed to work around this issue - I think you perhaps want to reference a SHA rather than the head of the branch: https://github.com/openstack/openstack-ansible-os_swift/blob/d568b871833e9a81a1612ad9cc071ca504fad79c/tasks/swift_init_systemd.yml#L16-L28

**Comment by cloudnull** [comment]
@odyssey4me +1, I've updated the issue message.

**Comment by jimi-c** [comment]
@cloudnull does my performance_improvement branch help with this issue?

**Comment by cloudnull** [comment]
@jimi-c Using the performance branch I no longer see this issue at all, which is awesome!

**Comment by jimi-c** [comment]
@cloudnull excellent, that was merged into devel yesterday, so if you're not seeing the issue any further we'll go ahead and close this now.

Thanks!

**Comment by cloudnull** [comment]
++ Everything seems good in 2.2 (devel). Thanks again
