### ISSUE TITLE
ANSIBLE_ROLES_PATH change in version 2.1.1

### ISSUE THREAD

**Issue by retr0h** [ansible/ansible#16911]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
ANSIBLE_CONFIG=.molecule/ansible.cfg
```

```
$ cat .molecule/ansible.cfg
[defaults]

roles_path      = roles:../
```
##### OS / ENVIRONMENT

NA
##### SUMMARY

ANSIBLE_ROLES_PATH seems to have changed with the release of `2.1.1`.  The default search for the role path is relative to the task folder or at least one directory down from where it used to be. 
##### STEPS TO REPRODUCE

My current directory is an ansible role, and I am trying to converge it.

```
[jodewey:~/git/ansible-systems/roles/etc_hosts] [venv] master+ ± tree
.
├── README.md
├── defaults
│   └── main.yml
├── meta
│   └── main.yml
├── playbook.yml
├── tasks
│   └── main.yml
├── templates
│   └── etc
│       └── hosts.j2
└── tests
    └── test_default.py
```

```
ANSIBLE_CONFIG=.molecule/ansible.cfg ansible-playbook playbook.yml -i .molecule/ansible_inventory
```
##### EXPECTED RESULTS

The role would converge.

This behavior works with the following:
- ansible==1.9.6
- ansible==2.0.2.0

Ansible 2.1.1 also works if I change ansible.cfg to:

```
$ cat .molecule/ansible.cfg
[defaults]

roles_path      = roles:../../
```
##### ACTUAL RESULTS

```
ERROR! the role 'etc_hosts' was not found in /Users/jodewey/git/ansible-systems/roles/etc_hosts/roles:/Users/jodewey/git/ansible-systems/roles/etc_hosts:/Users/jodewey/git/ansible-systems/roles/etc_hosts/.molecule/roles:/Users/jodewey/git/ansible-systems/roles/etc_hosts
```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

I'm not sure what you mean by 'converge' but roles were never meant to work from the current working directory (cwd). 

A role should be found in the defined "roles path" (via config) or in a `roles/` directory adjacent to the play, the play's directory itself is not part of the "roles path".

If this was happening in those versions, it was a bug, which now has been fixed. This was not a feature as it can lead to unpredictable role loading.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by retr0h** [comment]
> I'm not sure what you mean by 'converge' but roles were never meant to work from the current working directory (cwd).
> 
> A role should be found in the defined "roles path" (via config) or in a roles/ directory adjacent to the play, the play's directory itself is not part of the "roles path".

That is my point.  The `roles path` config option has changed, which is what I was asking about.  Ansible, can converge a role, by simply pointing to a roles_path.  The roles path seems different now.
