### ISSUE TITLE
ansible_python_interpreter ignored in 2.1.1.0

### ISSUE THREAD

**Issue by 2bithacker** [ansible/ansible#16938]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /Users/chip/Personal/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
gathering = smart
fact_caching = jsonfile
fact_caching_connection = /tmp/cachedir
fact_caching_timeout = 86400
ansible_managed = Ansible managed, do not edit directly! --- {uid}@{host}
inventory = inventory
vault_password_file = ~/.vaultpass
retry_files_enabled = false
command_warnings = false
```
##### OS / ENVIRONMENT

Running Ansible on Mac OS X 10.11.6
Managing a variety of hosts, but mostly FreeBSD 10.3-RELEASE
##### SUMMARY

I upgraded Ansible to 2.1.1.0 via homebrew, and can no longer run commands on my remote systems. I have ansible_python_interpreter set in a vars file, which was working fine prior to the update.
##### STEPS TO REPRODUCE

`group_vars/all/python`:

```

---
ansible_python_interpreter: /usr/bin/env python2.7
```

##### EXPECTED RESULTS

I expect Ansible to use the specified Python path as it did before 2.1.1.0.
##### ACTUAL RESULTS

Ansible does not use the defined Python path, instead using it's default.

```
> ansible ca-tor01.2bit.co -m setup
ca-tor01.2bit.co | FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "",
    "module_stdout": "/usr/bin/python: not found\r\n",
    "msg": "MODULE FAILURE",
    "parsed": false
}
```

**Comment by jctanner** [comment]
@2bithacker interpreter paths with spaces was only just recently introduced back in to devel and will be allowed in the next release. For now, it won't work to have "/usr/bin/env xxx" as the interpreter path and you will need to make it absolute.

This is the commit that re-introduces the feature:
https://github.com/ansible/ansible/commit/a9aea3c6d4d1e76ed9b9afb372e75ee55f53ede4

EDIT: 

I was mistaken. This has worked in ansible for a long time and was only broken in devel recently.

**Comment by jctanner** [comment]
As far as the group var setting the path, I am able to make it work with a non-spaced path ...

```
<10.0.0.107> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/jtanner/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.0.0.107 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python2.7 /root/.ansible/tmp/ansible-tmp-1470418587.97-204868416496370/command && sleep 0'"'"''
```

and with a spaced path ...

```
<10.0.0.107> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-
mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/jtanner/.ansible/cp/ansible-ssh-%
h-%p-%r -tt 10.0.0.107 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/env python2.7 /root/.ansible/tmp/ansible-tmp-
1470418812.1-53718025994068/command && sleep 0'"'"''
```

**Comment by jctanner** [comment]
@2bithacker can you provide the -vvvv output please?

**Comment by 2bithacker** [comment]
Here's the -vvvv output:

```
> ansible sumo.2bithacker.net -m setup -vvvv
Using /Users/chip/Personal/ansible/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<sumo.2bithacker.net> ESTABLISH SSH CONNECTION FOR USER: None
<sumo.2bithacker.net> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/chip/.ansible/cp/ansible-ssh-%h-%p-%r sumo.2bithacker.net '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1470425038.28-241804982200680 `" && echo ansible-tmp-1470425038.28-241804982200680="` echo $HOME/.ansible/tmp/ansible-tmp-1470425038.28-241804982200680 `" ) && sleep 0'"'"''
<sumo.2bithacker.net> PUT /var/folders/4g/sx9qxh_j2ksd17rwnh8yxjrw0000gn/T/tmpQgfVbJ TO /home/chip/.ansible/tmp/ansible-tmp-1470425038.28-241804982200680/setup
<sumo.2bithacker.net> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/chip/.ansible/cp/ansible-ssh-%h-%p-%r '[sumo.2bithacker.net]'
<sumo.2bithacker.net> ESTABLISH SSH CONNECTION FOR USER: None
<sumo.2bithacker.net> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/chip/.ansible/cp/ansible-ssh-%h-%p-%r -tt sumo.2bithacker.net '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/chip/.ansible/tmp/ansible-tmp-1470425038.28-241804982200680/setup; rm -rf "/home/chip/.ansible/tmp/ansible-tmp-1470425038.28-241804982200680/" > /dev/null 2>&1 && sleep 0'"'"''
sumo.2bithacker.net | FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "setup"
    },
    "module_stderr": "OpenSSH_7.3p1, OpenSSL 1.0.2h  3 May 2016\r\ndebug1: Reading configuration data /Users/chip/.ssh/config\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug1: /Users/chip/.ssh/config line 8: Deprecated option \"useroaming\"\r\ndebug1: /Users/chip/.ssh/config line 10: Applying options for *\r\ndebug1: /Users/chip/.ssh/config line 16: Applying options for *.2bithacker.net\r\ndebug1: Reading configuration data /usr/local/etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 54841\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to sumo.2bithacker.net closed.\r\n",
    "module_stdout": "/usr/bin/python: not found\r\n",
    "msg": "MODULE FAILURE",
    "parsed": false
}
```

I changed my ansible_python_interpreter to not contain a space, and the problem persists.

```
diff --git a/group_vars/all/python b/group_vars/all/python
index 1fe1db6..ae57dc8 100644
--- a/group_vars/all/python
+++ b/group_vars/all/python
@@ -1,2 +1,2 @@
 ---
-ansible_python_interpreter: /usr/bin/env python2.7
+ansible_python_interpreter: /usr/local/bin/python2.7
```

and a -vvvv run with that option in place:

```
> ansible sumo.2bithacker.net -m setup -vvvv
Using /Users/chip/Personal/ansible/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<sumo.2bithacker.net> ESTABLISH SSH CONNECTION FOR USER: None
<sumo.2bithacker.net> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/chip/.ansible/cp/ansible-ssh-%h-%p-%r sumo.2bithacker.net '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1470425190.8-260657531876346 `" && echo ansible-tmp-1470425190.8-260657531876346="` echo $HOME/.ansible/tmp/ansible-tmp-1470425190.8-260657531876346 `" ) && sleep 0'"'"''
<sumo.2bithacker.net> PUT /var/folders/4g/sx9qxh_j2ksd17rwnh8yxjrw0000gn/T/tmpIyWFG5 TO /home/chip/.ansible/tmp/ansible-tmp-1470425190.8-260657531876346/setup
<sumo.2bithacker.net> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/chip/.ansible/cp/ansible-ssh-%h-%p-%r '[sumo.2bithacker.net]'
<sumo.2bithacker.net> ESTABLISH SSH CONNECTION FOR USER: None
<sumo.2bithacker.net> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/chip/.ansible/cp/ansible-ssh-%h-%p-%r -tt sumo.2bithacker.net '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/chip/.ansible/tmp/ansible-tmp-1470425190.8-260657531876346/setup; rm -rf "/home/chip/.ansible/tmp/ansible-tmp-1470425190.8-260657531876346/" > /dev/null 2>&1 && sleep 0'"'"''
sumo.2bithacker.net | FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "setup"
    },
    "module_stderr": "OpenSSH_7.3p1, OpenSSL 1.0.2h  3 May 2016\r\ndebug1: Reading configuration data /Users/chip/.ssh/config\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug1: /Users/chip/.ssh/config line 8: Deprecated option \"useroaming\"\r\ndebug1: /Users/chip/.ssh/config line 10: Applying options for *\r\ndebug1: /Users/chip/.ssh/config line 16: Applying options for *.2bithacker.net\r\ndebug1: Reading configuration data /usr/local/etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 55016\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to sumo.2bithacker.net closed.\r\n",
    "module_stdout": "/usr/bin/python: not found\r\n",
    "msg": "MODULE FAILURE",
    "parsed": false
}
```

Either setting for ansible_python_interpreter is working fine with 2.1.0.0.

**Comment by jctanner** [comment]
@2bithacker where is the group_vars directory in relation to the cwd when you run ansible?

**Comment by 2bithacker** [comment]
It's in the cwd.

```
chip@thunder ~/P/ansible (master)> cat group_vars/all/python
---
ansible_python_interpreter: /usr/local/bin/python2.7
chip@thunder ~/P/ansible (master)> ansible sumo.2bithacker.net -m setup
sumo.2bithacker.net | FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "",
    "module_stdout": "/usr/bin/python: not found\r\n",
    "msg": "MODULE FAILURE",
    "parsed": false
}
```

BTW, looks like #16956 may be the same issue I'm having.

**Comment by jctanner** [comment]
@2bithacker what is the output of this command?

```
ansible sumo.2bithacker.net -m debug -a "var=ansible_python_interpreter"
```

**Comment by 2bithacker** [comment]
Under 2.1.1.0:

```
chip@thunder ~/P/ansible (master)> ansible sumo.2bithacker.net -m debug -a "var=ansible_python_interpreter"
sumo.2bithacker.net | SUCCESS => {
    "ansible_python_interpreter": "VARIABLE IS NOT DEFINED!"
}
```

Under 2.1.0.0:

```
chip@thunder ~/P/ansible (master)> ansible sumo.2bithacker.net -m debug -a "var=ansible_python_interpreter"
sumo.2bithacker.net | SUCCESS => {
    "ansible_python_interpreter": "/usr/local/bin/python2.7"
}
```

**Comment by dbarrosop** [comment]
This applies to 2.1.2 as well, how can an error like this be reported for 2.1.1 and be propagated to 2.1.2 months later? This is not a minor issue, this is a major one that renders ansible unusable: (

**Comment by bcoca** [comment]
This does not look like an `ansible_python_interpreter` issue. The `cwd` path resolution that was present in 2.1.0 was a bug, cwd is a security vulnerability for loading most things. Your `group_vars/` has to be relative to inventory file OR playbook, `ansible` has no playbook so it has to be relative to the inventory file used.

**Comment by jctanner** [comment]
@2bithacker can you please confirm if relocating your group_vars directory next to your inventory or playbook resolves the issue?

needs_info

**Comment by 2bithacker** [comment]
Can you clarify what you mean by "next to"? Presently my inventory and my group_vars are directories at the same level of my ansible setup.

```
chip@thunder ~/P/ansible (master)> tree group_vars/ inventory/
group_vars/
├── all
│   ├── dns
│   ├── email
│   ├── mysql
│   ├── packages
│   ├── python
│   ├── slack
│   ├── users
│   └── vault
├── builder
├── droplet
├── ipsec
│   ├── vault
│   └── vpn
├── nagios
│   ├── users
│   └── vault
├── owncloud
│   └── owncloud
├── storage
│   └── samba
└── webserver
    └── sites
inventory/
├── digitalocean.ini
├── digitalocean.py
└── hosts

6 directories, 20 files
```

**Comment by sivel** [comment]
`group_vars` must be located beside your inventory **file** instead of the inventory directory.  Otherwise it must be located beside your playbook file.

There was a bug that would load `group_vars` from CWD instead of next to the inventory file or playbook file.  This was resolved in a 2.1 release.

**Comment by 2bithacker** [comment]
Huh, ok. Moved my `group_vars` directory inside my `inventory` directory and everything works fine now.

**Comment by bcoca** [comment]
closing as per above

**Comment by guruprasad85** [comment]
hi,
i m stuck here ... 

ubuntu 16.04
Python 2.7.12
/usr/bin/python


ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides



ansible-playbook -i hostname install.yml -vvv
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: install.yml **********************************************************
1 plays in install.yml

PLAY [install awscli] **********************************************************

TASK [setup] *******************************************************************
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/system/setup.py
<35.166.197.222> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<35.166.197.222> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/home/guru/ansible/aws.pub"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/guru/.ansible/cp/ansible-ssh-%h-%p-%r 35.166.197.222 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1482341374.47-166753718212538 `" && echo ansible-tmp-1482341374.47-166753718212538="` echo $HOME/.ansible/tmp/ansible-tmp-1482341374.47-166753718212538 `" ) && sleep 0'"'"''
<35.166.197.222> PUT /tmp/tmpplbFdm TO /home/ubuntu/.ansible/tmp/ansible-tmp-1482341374.47-166753718212538/setup.py
<35.166.197.222> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/home/guru/ansible/aws.pub"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/guru/.ansible/cp/ansible-ssh-%h-%p-%r '[35.166.197.222]'
<35.166.197.222> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<35.166.197.222> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/home/guru/ansible/aws.pub"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/guru/.ansible/cp/ansible-ssh-%h-%p-%r 35.166.197.222 '/bin/sh -c '"'"'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1482341374.47-166753718212538/ /home/ubuntu/.ansible/tmp/ansible-tmp-1482341374.47-166753718212538/setup.py && sleep 0'"'"''
<35.166.197.222> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<35.166.197.222> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/home/guru/ansible/aws.pub"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/guru/.ansible/cp/ansible-ssh-%h-%p-%r -tt 35.166.197.222 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-mgpmxacvqytuvfqapuwbjahzwwrqqvkv; /usr/local/bin/python2.7 /home/ubuntu/.ansible/tmp/ansible-tmp-1482341374.47-166753718212538/setup.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1482341374.47-166753718212538/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
fatal: [tower-01]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "setup"
    }, 
    "module_stderr": "Shared connection to 35.166.197.222 closed.\r\n", 
    "module_stdout": "/bin/sh: 1: /usr/local/bin/python2.7: not found\r\n", 
    "msg": "MODULE FAILURE"
}
	to retry, use: --limit @/home/guru/ansible/install.retry
