### ISSUE TITLE
Issue with backslash '\' in powershell scripts

### ISSUE THREAD

**Issue by amirchoudhri** [ansible/ansible#16939]
- Bug Report
##### ANSIBLE VERSION

ansible --version
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

No significant changes
##### OS / ENVIRONMENT

Ubuntu 14.04 LTS - Ansible Server
Windows Server 2012 R2 - Target device
##### SUMMARY

Hi, 

When trying to execute a powershell script which uses backslash to reference a file path the script fails with a "path not found" type error and shows the path with an extra backslash.  An example of the error is shown below.  

As an example currently:

\WINSERVER\testdir

BECOMES after running powershell script

\\WINSERVER\testdir

I have tried a number of things like using forward slash (/), using triple quotes ("""), using single quotes (').

Any help would be greatly appreciated !
##### STEPS TO REPRODUCE

Create a playbook task such as:
tasks:
- name: install windows build
  script:  powershell/win_install.ps1

In the powershell i have a line like this which would cause the failure:

$srcpath = '\$copyserver\file'
$dstpath = 'C:\directory\file'
Robocopy '$srcpath' '$dstpath' /e /r:2 /w:0 /mir /np
##### EXPECTED RESULTS

Execute the powershell with the correct directory path. 
##### ACTUAL RESULTS

changed: [WINTEST] => {"changed": true, "invocation": {"module_args": {"_raw_params": "/etc/ansible/powershell/win_install.ps1"}, "module_name": "script"}, "rc": 0, "stderr": "", "stdout": "No AV installed, proceeding with the installation\n\r\n-------------------------------------------------------------------------------\r\n   ROBOCOPY     ::     Robust File Copy for Windows                              \r\n-------------------------------------------------------------------------------\r\n\r\n  Started : Wednesday, August 3, 2016 12:07:54 PM\r\n   Source : C:\Users\Administrator\$srcpath\\r\n     Dest : C:\Users\Administrator\$dstpath\\r\n\r\n    Files : _._\r\n\t    \r\n  Options : _._ /S /E /DCOPY:DA /COPY:DAT /PURGE /MIR /NP /R:2 /W:0 \r\n\r\n------------------------------------------------------------------------------\r\n\r\n2016/08/03 12:07:54 ERROR 2 (0x00000002) Accessing Source Directory C:\Users\Administrator\$srcpath\\r\nThe system cannot find the file specified.\r\r\n", "stdout_lines": ["No AV installed, proceeding with the installation", "", "-------------------------------------------------------------------------------", "   ROBOCOPY     ::     Robust File Copy for Windows                              ", "-------------------------------------------------------------------------------", "", "  Started : Wednesday, August 3, 2016 12:07:54 PM", "   Source : C:\Users\Administrator\$srcpath\", "     Dest : C:\Users\Administrator\$dstpath\", "", "    Files : _._", "\t    ", "  Options : _._ /S /E /DCOPY:DA /COPY:DAT /PURGE /MIR /NP /R:2 /W:0 ", "", "------------------------------------------------------------------------------", "", "2016/08/03 12:07:54 ERROR 2 (0x00000002) Accessing Source Directory C:\Users\Administrator\$srcpath\", "The system cannot find the file specified.", ""]}

**Comment by jhawkesworth** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by groenator** [comment]
Is there a solution for this backslash bug (if I can call it this way)?
