### ISSUE TITLE
Apply patch to JBoss EAP through Ansible

### ISSUE THREAD

**Issue by ranjithpulluru** [ansible/ansible#16932]
##### ISSUE TYPE
- Feature Idea
##### SUMMARY
- Apply patch to EAP through Ansible.
##### ADDITIONAL INFO
- A more minimalist approach would be have the ability to test whether a patch needs to be applied or not using the jboss-cli.

**Comment by alikins** [comment]
Could you elaborate on what 'Apply patch to EAP through Ansible.' means?

This sounds like it is probably a request for a new module. If that is the case, it would be better to open a feature request issue on https://github.com/ansible/ansible-modules-extras/issues and provide more details there. 

If the feature requires changes to ansible/ansible, we can reopen this bug.
