### ISSUE TITLE
ansible-galaxy not working with github repo @ 2.1.0.0

### ISSUE THREAD

**Issue by brutto** [ansible/ansible#16947]
i've installed 2100.

```
[vagrant@localhost ~]$ ansible --version
  ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

then run `sudo ansible-galaxy install -r /vagrant/provisioning/requirements.yml` and get this error message:

```
[vagrant@localhost ~]$ sudo ansible-galaxy install -r /vagrant/provisioning/requirements.yml
[WARNING]: - ntp was NOT installed successfully: error executing: git clone https://github.com/brutto/ntp ntp

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**requirements.yml**

```
- src: https://github.com/brutto/ntp
  name: ntp
  version: patch-1
```

I've found some topics about similar bug, but all of them fixed or closed. =\
Where im wrong?

**Comment by alikins** [comment]
> error executing: git clone https://github.com/brutto/ntp

If possible, try this with a higher level of verbosity enabled, ie:

```
sudo ansible-galaxy -vvvvv install -r /vagrant/provisioning/requirements.yml
```

I suspect it is a SSL/TLS related issue, so the extra verbosity should provide some details.

**Comment by brutto** [comment]
Oh! @alikins thanks for support. I found It was my fault! This issue appears because of i have the same named roles in ansible folder (installed from galaxy) and in my working directory.  Remove/rename one of them fix the issue. Many excuses. =)
