### ISSUE TITLE
What is the best way to install ansible? 

### ISSUE THREAD

**Issue by amishra123** [ansible/ansible#16950]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

```

```
##### OS / ENVIRONMENT

Mac OS X
##### SUMMARY

I have installed ansible using pip install ansible on mac os x. 
But as mentioned on ansible website there is no such directory as /etc/ansible. 
Also,couldnt find the file ansible.cfg. Is this the right way to install or I am missing something? 
##### STEPS TO REPRODUCE

I created directory ansible and hosts file insisde that. The only entry I have is 127.0.0.1 inside hosts file. When I try to ping through ansible,I get UNREACHABLE host error. 
##### EXPECTED RESULTS

successful ping
##### ACTUAL RESULTS

``
unreachable host issue due to ssh.

```
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case follow this http://docs.ansible.com/ansible/intro_installation.html#latest-releases-on-mac-osx, I suspect you used homebrew which mangles the Ansible install and we don't recommend as an install method. 

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
