### ISSUE TITLE
win_user fails with name=** state=query

### ISSUE THREAD

**Issue by sunyaxiong** [ansible/ansible#16967]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
2.1.1.0
```
##### CONFIGURATION

 default config
##### OS / ENVIRONMENT

Ubuntu 14.04  
Python2.7.6
##### SUMMARY

When I use win_user module's 'name=*\* state=query' , that can not return the *\* 's user account details, is there has a bug
##### STEPS TO REPRODUCE

this is the screenshot
![error](https://cloud.githubusercontent.com/assets/8956366/17424707/33065af8-5af9-11e6-9325-a5068ad4ffbf.png)

**Comment by bcoca** [comment]
can you execute the same using ad-hoc?

`ansible -m win_user -a "name=sunyaxiong state=query" -i 10.2.66.142, all`

**Comment by sunyaxiong** [comment]
this screenshot is the return value of win_ping and win_user, and the win_user 's return is same  as Console:
![error-winuser](https://cloud.githubusercontent.com/assets/8956366/17467700/af6510d8-5d53-11e6-919e-b0fdf12d6641.png)

@bcoca

**Comment by bcoca** [comment]
tested against current ansible and I cannot reproduce, are you sure you are not using an older version of the win_user module? that option was added in 1.9

**Comment by nitzmahone** [comment]
@sunyaxiong This can't possibly be the current version of win_user. @bcoca is correct- this functionality has been around for a long time, and that error message was changed in 2014 in [this commit](https://github.com/ansible/ansible-modules-core/commit/3a40d79cff8332d2cbb0f418d6a450d3b7f70360). Please check that you're running a reasonably current version of Ansible and that you don't have a stale copy of win_user.ps1 in a local library directory or something.
