### ISSUE TITLE
Extra vars with argument `-e` needs space for the first var

### ISSUE THREAD

**Issue by inabhi9** [ansible/ansible#16989]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Ubuntu: 14.04 LTS
##### SUMMARY

Extra vars with argument `-e` needs space for the first var
##### STEPS TO REPRODUCE

```

---
- hosts: all
  tasks:
    - name: ping
      command: echo '{{ my_var }}'
```

To run this with argument I use:
`ansible-playbook -i inventories/staging.ini test.yml -e="my_var=abc"`

##### EXPECTED RESULTS

```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [vp2.abhi9.in]

TASK [ping] ********************************************************************
changed: [vp2.abhi9.in]

PLAY RECAP *********************************************************************
vp2.abhi9.in               : ok=2    changed=1    unreachable=0    failed=0 
```
##### ACTUAL RESULTS

```
fatal: [vp2.abhi9.in]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'my_var' is undefined\n\nThe error appears to have been in test.yml': line 5, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: ping\n      ^ here\n"}
```

It works correctly with following command
`ansible-playbook -i inventories/staging.ini test.yml -e=" my_var=abc"`
Notice the space before the _my_var_

**Comment by amenonsen** [comment]
> To run this with argument I use:
> `ansible-playbook -i inventories/staging.ini test.yml -e="my_var=abc"`

And that is the entire problem. You should be using `-e "my_var=abc"`

**Comment by inabhi9** [comment]
My bad. Issue can be closed.
