### ISSUE TITLE
User parameterized variables in task names

### ISSUE THREAD

**Issue by mattwillsher** [ansible/ansible#1698]
It's quite handy to be able to do the following:

```

---
 - name: Create $name user
   action: user name=$name state=present
```

The in the playbook

```
...
 - include: ../task/add-named-user.yml name=myuser
...
```

I'm reasonably sure  it used to display:

```
Create myuser user
```

but one the current devel branch it just prints a literal $name.

```
Create $name user
```

**Comment by mpdehaan** [comment]
I agree it should not do that.

are you still having variables like $name available in the task 'action' itself?

**Comment by dhozac** [comment]
I broke this in resolving one of my most "what is this doing here?" areas of the template invocations. Should be back to normal now.
