### ISSUE TITLE
Dynamic Inventory: Security Group: dashes WILL be converted

### ISSUE THREAD

**Issue by ralfbergs** [ansible/ansible#16996]
##### ISSUE TYPE
- Documentation Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

In the docs it says in section "[Example: AWS EC2 External Inventory Script](https://docs.ansible.com/ansible/intro_dynamic_inventory.html#id6)":

`Security Group: Instances belong to one or more security groups. A group is created for each security group, with all characters except alphanumerics, dashes (-) converted to underscores (_).`

It seems that contrary to the above dashes _are_ converted to underscores.
##### STEPS TO REPRODUCE

Create Security Group in AWS with name `ralfbergs-sg-mgmt-jump`, run following command:

```
$ ./ec2.py --list|less
```

##### EXPECTED RESULTS

According to the above quoted doc snippet the security group name should have been: `security_group_ralfbergs-sg-mgmt-jump`
##### ACTUAL RESULTS

Actually the security group name became: `security_group_ralfbergs_sg_mgmt_jump`

```

```

**Comment by bcoca** [comment]
This is controllable by a setting in ec2.ini `replace_dash_in_groups = True`

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by ralfbergs** [comment]
When I comment out the `replace_dash_in_groups` setting in `ec2.ini`, the default behavior should apply, right?

And the default behavior seems to be that dashes _are_ replaced by underscores.

So it seems to be that the documentation is not correct in this respect?

**Comment by bcoca** [comment]
It has changed over time, so it depends on the version you are using, the setting should still control the outcome. I'll x2 check the docs to see if the match the current version and adjust if needed.

**Comment by ralfbergs** [comment]
Yes, the setting controls the outcome, I checked that the setting is working _if_ explicitly specified.

But again, the default seems to be opposite to what's in the docs, and I seem to be using the latest released Ansible version, so they docs should apply.

Thanks!

**Comment by bcoca** [comment]
this commit should clarify the docs 1838eeba96aa1504f47fa18f3bc070fafde5d952 (it won't be effective immediately).

**Comment by ralfbergs** [comment]
Yes, looks good. Thanks.
