### ISSUE TITLE
unarchive remote source from http URL fails

### ISSUE THREAD

**Issue by keywork** [ansible/ansible#17009]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

Running Ansible from Arch Linux 4.6.4-1-ARCH
Target machine is running Centos 7.2.1511   3.10.0-327.22.2.el7.x86_64
##### SUMMARY

Attempting to run the unarchive task to download and extract an http URL yields an error   FAILED! => {"changed": false, "failed": true, "msg": "Unable to find 'https://wordpress.org/latest.tar.gz' in expected paths."}
##### STEPS TO REPRODUCE

Run a playbook with the line included below to download and unarchive

```
- name: Extract archive
  unarchive: src=https://wordpress.org/latest.tar.gz dest=/home/admin/sites/{{ my_domain }} remote_src=yes
```
##### EXPECTED RESULTS

 It is expected that the file will be properly downloaded  and extracted to the destination directory
##### ACTUAL RESULTS

```
TASK [ansible-role-wordpress : Extract archive] ********************************
task path: /deploy/ansible-role-wordpress/tasks/main.yaml:2
<X.X.X.X> ESTABLISH SSH CONNECTION FOR USER: root
<X.X.X.X> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/XXXX/.ansible/cp/ansible-ssh-%h-%p-%r X.X.X.X '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1470694434.93-161431668468931 `" && echo ansible-tmp-1470694434.93-161431668468931="` echo $HOME/.ansible/tmp/ansible-tmp-1470694434.93-161431668468931 `" ) && sleep 0'"'"''
<X.X.X.X> ESTABLISH SSH CONNECTION FOR USER: root
<X.X.X.X> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/XXXX/.ansible/cp/ansible-ssh-%h-%p-%r X.X.X.X '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1470694434.93-161431668468931/ > /dev/null 2>&1 && sleep 0'"'"''
fatal: [X.X.X.X: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "dest": "/home/admin/sites/mydomain.com", 
            "remote_src": "yes", 
            "src": "https://wordpress.org/latest.tar.gz"
        }, 
        "module_name": "unarchive"
    }, 
    "msg": "Unable to find 'https://wordpress.org/latest.tar.gz' in expected paths."
}

```

**Comment by joemaller** [comment]
@keywork What was the last version of Ansible that task worked under? I'm having a similar problem with the Unarchive module that popped up between 2.1.0.0 and 2.1.1.0. 

I've been struggling to work around this and haven't nailed down exactly what's going on yet. Something on the remote end is losing track of its paths.

**Comment by joemaller** [comment]
There seems to be issues with specific archives. I'm encountering a similar error trying to download the zip copy of the same WordPress archive with Ansible v2.1.1.0:

```
"Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/tmp/wordpress/'",
```

The same file downloaded from the same playbook works correctly under Ansible v2.1.0.0.

If I manually expand and recompress the archive, it works correctly under Ansible v2.1.1.0. (I'm testing with copies on a separate server to help isolate the problem.)

I don't know much about archive internals or what might have changed regarding Ansible's handling of archives between those two releases, but I'm going to do some more research and see what I can find.

**Comment by donnlee** [comment]
Same issue.

Playbook yaml:

```
  - name: download and untar go 1.6
    unarchive: src=https://storage.googleapis.com/golang/go1.6.linux-amd64.tar.gz dest=/usr/local remote_src=yes
```

Error:

```
TASK [download and untar go 1.6] ***********************************************
fatal: [i2]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find 'https://storage.googleap
is.com/golang/go1.6.linux-amd64.tar.gz' in expected paths."}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @tmp.retry
```

```
ansible 2.2.0 (devel df81f1197f) last updated 2016/08/09 18:45:00 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 5d7b46e0dd) last updated 2016/08/09 18:45:16 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD eaa71f51d6) last updated 2016/08/09 18:45:30 (GMT -700)
  config file =
  configured module search path = Default w/o overrides
```

**Comment by joemaller** [comment]
Just spent some time bisecting and I'm pretty sure remote unarchiving broke after commit ef5a504b8ba939b61bf0bd223c1bdb8d2b which was a submodule update. I'm opening a new issue on the core-modules repo pointing to https://github.com/ansible/ansible-modules-core/commit/bf670bfdc2c193345a0365bd84e955005b432

**Comment by dagwieers** [comment]
See ansible/ansible-modules-core#4244 for more information, we are waiting for this fix to get included.

The problem was introduced in this commit: https://github.com/ansible/ansible-modules-core/commit/467516e5dade1efec15034d1eef5b2df32893447#diff-c8620ce6bed12fc5110958c7607f1b03R737

**Comment by nitzmahone** [comment]
Should be fixed in devel by https://github.com/ansible/ansible-modules-core/commit/5559e6a669ca7a4ed72e20a3300f8968a3203a82

**Comment by dagwieers** [comment]
Thanks @nitzmahone
