### ISSUE TITLE
allow_world_readable_tmpfiles not documented under "Configuration file"

### ISSUE THREAD

**Issue by jklaiho** [ansible/ansible#17013]
##### ISSUE TYPE
- Documentation Report
##### ANSIBLE VERSION

N/A
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The `allow_world_readable_tmpfiles` option for ansible.cfg is not documented in the **Configuration file** page. The docs for `become` describe it (without mentioning that it belongs under the `[defaults]` section), but it should still be included in the master documentation for configuration options.

**Comment by Shaps** [comment]
I can take on this one
