### ISSUE TITLE
Publish modules to Galaxy?

### ISSUE THREAD

**Issue by snoopdouglas** [ansible/ansible#17027]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

Ansible Galaxy (overall)
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Would it be possible add the facility to publish modules (not just roles) to Galaxy? Would such a thing be useful?

Apologies if this has already been considered - couldn't find anything when I searched issues.
##### STEPS TO REPRODUCE

Modules could be downloaded by `ansible-galaxy` in the same way as a role, except they would be placed into `library/`:

```
$ ansible-galaxy install snoopdouglas.some-module

# or, with a requirements.yml:

$ cat requirements.yml
- src: snoopdouglas.some-module
$ ansible-galaxy install -r requirements.yml
```

`ansible-galaxy` could also use `ansible.cfg` to figure out where to put downloaded modules.
##### EXPECTED RESULTS

```
$ ls library/
snoopdouglas.some-module
$ ls library/snoopdouglas.some-module/
some_module.py  test_some_module.py
```

**Comment by sivel** [comment]
This is already possible, however it still falls under the same concept as a role, you just upload a role with only a `library` directory.

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
