### ISSUE TITLE
Feature: Easily create docker image from playbooks

### ISSUE THREAD

**Issue by xrow** [ansible/ansible#17028]
- Feature Idea

When ever we want to create a docker container via an ansible configuration things are very difficult to setup. We would like to have a more intuitive way of doing things.

So far we do stuff like this:

```
FROM centos/systemd

ENV container=docker
ENV PATH=/opt/rh/rh-php56/root/usr/bin:/opt/rh/rh-php56/root/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

WORKDIR /root
VOLUME [ "/sys/fs/cgroup" ]

# Make ssh dir
RUN mkdir /root/.ssh/
# Copy over private key, and set permissions
ADD config /root/.ssh/config
RUN cat /root/.ssh/config
RUN chmod 600 /root/.ssh/config
ADD id_rsa /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa
RUN chown -R root:root /root/.ssh
# Create known_hosts
RUN touch /root/.ssh/known_hosts

ADD provision /root/provision

RUN ansible-galaxy install -f -r  /root/provision/requirements.yml --ignore-errors
RUN ansible-playbook -c local -i /root/provision/hosts /root/provision/ezcluster.docker.yml -vv

RUN rm -Rf /root/provision
RUN rm -Rf /etc/ansible/roles

EXPOSE 80
EXPOSE 8080

CMD ["/usr/sbin/init"]
```

But ideally it should be way easier like

```
ansible-docker-push docker-playbook.yml <hub-user>/<repo-name>:<tag>
```

What do you think? Is this something that is doable and would me sense? I probaly is not all way thought though and needs feedback and more love.

**Comment by dmsimard** [comment]
Isn't this the scope of the [ansible-container](https://github.com/ansible/ansible-container) tool ?

**Comment by xrow** [comment]
Ups that is the thing I am looking for. I didn`t know taht this exists. Please close.

**Comment by xrow** [comment]
side note: ansible-container is not yet available in EPEL.
