### ISSUE TITLE
Feature Request: Call a role like a task

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#17021]
##### ISSUE TYPE

 Feature Idea
##### COMPONENT NAME

Ansible Core Modules
##### OS / ENVIRONMENT

N/A
##### SUMMARY

It would be very useful to be able to call roles like tasks. 

This feature would allow users to reuse procedures more and adhere to the DRY software engineering principle. 

For example, a role might encapsulate all steps for a small procedure. Another role might be comprised of running the same small procedure with some steps before and after it. Or a role could be a mix of tasks and roles intermingled. This would help to ensure that a procedure can be written once and called from where ever it is needed.

**Comment by bcoca** [comment]
dupe , it is already in roadmap and also here https://github.com/ansible/proposals/blob/master/roles_revamp.md
