### ISSUE TITLE
gathering facts caused setup to fail by using ssh-config environment logname on client side

### ISSUE THREAD

**Issue by jsobolewskihh** [ansible/ansible#17029]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

module_utils/facts.py
##### ANSIBLE VERSION

ansible 2.1.0.0 
##### OS / ENVIRONMENT

Ansible "client" is Debian 7
##### SUMMARY / STEPS TO REPRODUCE

The issue is a little bit related to #4688

Ansible can not connect, if a special logname setting is used at ssh authkeys file on the target host

For multi-user separation I am using the environment="LOGNAME=jan.sobolewski" ssh-**\* [pubkey] in /poweruser/.ssh/authorized_keys on the server I want to manage with ansible.

This allows to control which user logged in at which timestamp by sharing a single poweruser. Most of you may already know that feature.

I configured ansible to connect me as "poweruser". That worked fine on all servers.
Excepting servers that used the ssh-environment in their authkeys file as I explained above.

ansible hostname.blah.local -m setup may cause the issue:

hostname.blah.local | FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_vCcfCL/ansible_module_setup.py\", line 127, in <module>\r\n    main()\r\n  File \"/tmp/ansible_vCcfCL/ansible_module_setup.py\", line 119, in main\r\n    data = get_all_facts(module)\r\n  File \"/tmp/ansible_vCcfCL/ansible_modlib.zip/ansible/module_utils/facts.py\", line 3177, in get_all_facts\r\n  File \"/tmp/ansible_vCcfCL/ansible_modlib.zip/ansible/module_utils/facts.py\", line 3121, in ansible_facts\r\n  File \"/tmp/ansible_vCcfCL/ansible_modlib.zip/ansible/module_utils/facts.py\", line 195, in **init**\r\n  File \"/tmp/ansible_vCcfCL/ansible_modlib.zip/ansible/module_utils/facts.py\", line 787, in get_user_facts\r\nKeyError: 'getpwnam(): name not found: jan.sobolewski'\r\n",
    "msg": "MODULE FAILURE",
    "parsed": false
}
##### EXPECTED RESULTS

ssh connect user has to be declared at the local ansible setting file where the scripts are located on. As ansible decided to use the "logname" instead of my configuration this turned the userconfig into a joke. Maybe I did'nt find an existing workaround?
It seems that ansible may take the logname instead of my already defined username.

Turning of collecting facts is not a option ;-)

**Comment by alikins** [comment]
Looks like the user of 'getpass.getuser()' there returns the LOGNAME. 
https://docs.python.org/2/library/getpass.html#getpass.getuser  indicates that is intentional.

For the other pwd field info, logname isn't sufficient. 
At first glance I think the code fix would be replace the getpass.getuser() with os.getuid()

Or replace pwd.getpwdname(getpass.getuser()) with pwd.getpwuid(os.getuid()).
I need to dig into the history of that code to see if there is a reason for the current behavior.

**Comment by sivel** [comment]
Instead of changing the default behavior, which users may be relying on, we should instead catch the `KeyError` and then fallback:

```diff
diff --git a/lib/ansible/module_utils/facts/system/user.py b/lib/ansible/module_utils/facts/system/user.py
index 745b5db3f6..888f13d293 100644
--- a/lib/ansible/module_utils/facts/system/user.py
+++ b/lib/ansible/module_utils/facts/system/user.py
@@ -35,7 +35,12 @@ class UserFactCollector(BaseFactCollector):
 
         user_facts['user_id'] = getpass.getuser()
 
-        pwent = pwd.getpwnam(getpass.getuser())
+        try:
+            pwent = pwd.getpwnam(getpass.getuser())
+        except KeyError:
+            pwent = pwd.getpwnam(
+                pwd.getpwuid(os.getuid())[0]
+            )
 
         user_facts['user_uid'] = pwent.pw_uid
         user_facts['user_gid'] = pwent.pw_gid
```

I'm not actively pursuing this fix further.  If you want to work on this, please feel free to use the above diff, add a changelog, and a test to validate it.
