### ISSUE TITLE
detecting virtualization facts fails with host xenial and guest trusty

### ISSUE THREAD

**Issue by ogmueller** [ansible/ansible#17030]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ubuntu 16.04
##### SUMMARY

Ansible is not able to detect the virtualization correctly if the host is an Ubuntu 16.04 Xenial and the guest is an Ubuntu 14.04 Trusty using LXC. On guests with 16.04 it is detecting everything correctly though.
##### STEPS TO REPRODUCE

Setup a host with Ubuntu 16.04. Install 2 LXC guest systems on this server. One with 16.04, the other with 14.04.

After that just try to gather facts on the 3 machines like the following:

```
# ansible xenial_host -m setup -a "filter=ansible_virtualization_*"
xenial_host | SUCCESS => {
    "ansible_facts": {
        "ansible_virtualization_role": "host",
        "ansible_virtualization_type": "kvm"
    },
    "changed": false
}
```

```
# ansible xenial_guest -m setup -a "filter=ansible_virtualization_*"
xenial_guest | SUCCESS => {
    "ansible_facts": {
        "ansible_virtualization_role": "guest",
        "ansible_virtualization_type": "lxc"
    },
    "changed": false
}
```

```
# ansible trusty_guest -m setup -a "filter=ansible_virtualization_*"
trusty_guest | SUCCESS => {
    "ansible_facts": {
        "ansible_virtualization_role": "host",
        "ansible_virtualization_type": "kvm"
    },
    "changed": false
}
```

##### EXPECTED RESULTS

The trusty_guest should have the same result as the xenial_guest. both are LXC guest systems on xenial_host. The result should be

```
# ansible trusty_guest -m setup -a "filter=ansible_virtualization_*"
trusty_guest | SUCCESS => {
    "ansible_facts": {
        "ansible_virtualization_role": "guest",
        "ansible_virtualization_type": "lxc"
    },
    "changed": false
}
```
##### ACTUAL RESULTS

```
# ansible trusty_guest -m setup -a "filter=ansible_virtualization_*"
trusty_guest | SUCCESS => {
    "ansible_facts": {
        "ansible_virtualization_role": "host",
        "ansible_virtualization_type": "kvm"
    },
    "changed": false
}
```

Maybe this one is related to #15165, but not exactly the same setup or environment.

**Comment by ogmueller** [comment]
I double checked the results on a LXC guest running 14.04, but this time the host was an Ubuntu 14.04 as well. In this case the virtualization detection works. Only if the host system is a 16.04 it is not working.

**Comment by bcoca** [comment]
So the current detection uses the existence of `/proc/1/cgroup` AND the existence of `/lxc/` inside that file as the way to detect virtualization, has this changed on Ubuntu 16?

**Comment by bcoca** [comment]
In any case that should not set `kvm`, this happens through other checks, it is not a default

**Comment by ogmueller** [comment]
yes, it has changed.

if the host is a 14.04 the content looks like

```
# cat /proc/1/cgroup
11:hugetlb:/lxc/abbe
10:perf_event:/lxc/abbe
9:blkio:/lxc/abbe
8:freezer:/lxc/abbe
7:devices:/lxc/abbe
6:memory:/lxc/abbe
5:cpuacct:/lxc/abbe
4:cpu:/lxc/abbe
3:cpuset:/lxc/abbe
2:name=systemd:/lxc/abbe
```

BUT if the host is a 16.04 the content looks like

```
$ cat /proc/1/cgroup
11:pids:/
10:memory:/
9:cpu,cpuacct:/
8:hugetlb:/
7:net_cls,net_prio:/
6:blkio:/
5:devices:/
4:perf_event:/
3:freezer:/
2:cpuset:/
1:name=systemd:/
```

under ubuntu 16.04 you might be able to detect LXC guests by looking into /proc/1/mounts, because some /procs are mounted there:

```
$ cat /proc/1/mounts | grep lxc
lxcfs /proc/cpuinfo fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/diskstats fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/meminfo fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/stat fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/swaps fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/uptime fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
devpts /dev/lxc/console devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
devpts /dev/lxc/tty1 devpts rw,relatime,gid=5,mode=620,ptmxmode=666 0 0
devpts /dev/lxc/tty2 devpts rw,relatime,gid=5,mode=620,ptmxmode=666 0 0
devpts /dev/lxc/tty3 devpts rw,relatime,gid=5,mode=620,ptmxmode=666 0 0
devpts /dev/lxc/tty4 devpts rw,relatime,gid=5,mode=620,ptmxmode=666 0 0
```

**Comment by ogmueller** [comment]
How do you detect a guest in an Ubuntu 16.04 guest? Because the detection is working there, even though the cgroup file has no LXC in it.

This is the output of an Ubuntu 16.04 guest running on an 16.04 host:

```
# cat /proc/1/cgroup
11:pids:/
10:memory:/
9:cpu,cpuacct:/
8:hugetlb:/
7:net_cls,net_prio:/
6:blkio:/
5:devices:/init.scope
4:perf_event:/
3:freezer:/
2:cpuset:/
1:name=systemd:/init.scope
```

**Comment by ogmueller** [comment]
So the problem for ansible is, that the container detection is not based on the guest OS, but on the underlying host OS.

**Comment by ogmueller** [comment]
Some people suggest to look for the existance of /dev/lxc/console, which do exists on all our LXC guests no matter of the underlying OS/LXC version.

**Comment by bcoca** [comment]
@ogmueller x2 check my PR above to see if it fixes the issue for you

**Comment by ogmueller** [comment]
great. the change seems to work, but you have 2 typos in there. this one works:

```
2677         # newer lxc does not appear in cgroups anymore but sets 'container=lxc' environment var
2678         if os.path.exists('/proc/1/environ'):
2679             for line in get_file_lines('/proc/1/environ'):
2680                 if re.search('container=lxc', line):
2681                     self.facts['virtualization_type'] = 'lxc'
2682                     self.facts['virtualization_role'] = 'guest'
2683                     return
```

**Comment by ogai** [comment]
This issue also hits Ansible 1.9.6
