### ISSUE TITLE
ansible python api - h.get_group_vars does not return the group vars

### ISSUE THREAD

**Issue by sunshine69** [ansible/ansible#17040]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Python API - Might be in other places in ansibel itself that uses it
##### ANSIBLE VERSION

```
ansible --version
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
stevek@auto-06153d80 ~> 

```
##### CONFIGURATION

stevek@auto-06153d80 ~> cd ansible-jumbo/inventory/staging/
stevek@auto-06153d80 ~/a/i/staging> cat ansible.cfg 
[defaults]
host_key_checking=false
library=../../library
filter_plugins = ../../filter_plugins
stevek@auto-06153d80 ~/a/i/staging>
##### OS / ENVIRONMENT

uname -a
Linux auto-06153d80.vm 4.6.4cpu32x64core2h2preempt1-ubov #10 SMP Sat Jul 30 08:48:00 AEST 2016 x86_64 x86_64 x86_64 GNU/Linux
##### SUMMARY

get_group_vars does not return the group var data.
##### STEPS TO REPRODUCE

```
** Inventory file
stevek@auto-06153d80 ~/a/i/staging> cat test-hosts 
[staging-classic]
# common for all staging classic

[staging-classic:children]
# stagingT
stagingT-classic

[stagingT-classic]
stagingT-web1-classic-au
stagingT-web2-classic-au

** Group file
stevek@auto-06153d80 ~/a/i/staging> cat group_vars/stagingT-classic.yml 

---
BASEURL: 'stagingT.ozlotteries.com'
# vim:expandtab ts=2 sw=2

==========
Python scripts 

#!/usr/bin/python

from ansible import inventory
from ansible.vars import VariableManager
from ansible.parsing.dataloader import DataLoader

variable_manager = VariableManager()
loader = DataLoader()
inv = inventory.Inventory(loader, variable_manager, 'test-hosts')
h = inv.get_host('stagingT-web1-classic-au')
print( h.get_group_vars() )

===========

Run the python script, the output is empty ( {} )

```

##### EXPECTED RESULTS

The exact same setup if I use ansible 2.0.1.0 produce correct result
{u'BASEURL': u'stagingT.ozlotteries.com'}
##### ACTUAL RESULTS

Empty.

```
{}
```

**Comment by idcmp** [comment]
This is still present in 2.2.0:

ansible 2.2.0 (devel 8438da2a34) last updated 2016/09/14 11:27:42 (GMT -700)
  lib/ansible/modules/core: (detached HEAD ae6992bf8c) last updated 2016/09/14 11:27:57 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD afd0b23836) last updated 2016/09/14 11:28:13 (GMT -700)

Is there a workaround available?

**Comment by bcoca** [comment]
get_group_vars is not supposed to return the group data, it updates variable manager with it, you can only get vars data per host.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible-devel on irc.freenode.net  
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by idcmp** [comment]
@bcoca  This is a breaking change to the API; is there a recommended replacement?

A variable for a host may be assigned different values dependending on which groups the host is in. I was using this API to ask for the value of a variable within the scope of a specific group. Asking the host for the value will return the value assigned by the last group Ansible read.

**Comment by bcoca** [comment]
By design we don't need/want that info so we did not create a replacement API, Ansible consumes the 'flat' value after everything is computed.

As for breaking change, yes, it is, but the API is not guaranteed, only the command line interface.

**Comment by sunshine69** [comment]
So if I understand correctly I need to call get_group_vars() and then get_vars() in order to get that all variables associated with a host?

**Comment by idcmp** [comment]
I've just tested that, and it seems inventory.get_group_variables(group.name) returns an empty set.

(Ansible 2.2.0)

**Comment by shaneboulden** [comment]
I've also tried querying the group directly:

``` python
def v2_playbook_on_play_start(self, *args, **kwargs):
     inventory = args[0].get_variable_manager()._inventory.get_hosts()
     for host in inventory:
          groups = host.get_groups()
          for group in groups:
              group_vars = group.get_vars()
              group_vars_attr = group.vars
```

Both return an empty set.

**Comment by idcmp** [comment]
Yup. It was a mistake on our part to leverage that API in the first place. We've learned our lesson and now recommend a static version of Ansible across the organization to avoid compatibility issues between any two given versions.
