### ISSUE TITLE
add "mocking" parameter to shell and command module

### ISSUE THREAD

**Issue by muellerrainer** [ansible/ansible#17042]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

module shell && command
##### ANSIBLE VERSION

2.x
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Often playbooks that are run with --check breat at that point when the shell or command tasks are used. Especially when return codes of these tasks are used in furhter tasks as input.
If this happens (for me very often) I'm not able to test an entire playbook.
It would be great if these modules would have another parameter like "mock" or "mock_return" where an alternative "command" could be desinged that is run instead of the command that is uses in normal (not with --check) playbook runs.
##### STEPS TO REPRODUCE

run a playbook with shell tasks and commandline parameter --check
### simple playbook where a lates task needs a result from a previous shell task
- hosts: myhosts
  gather_facts: yes
  tasks:
  - name: run shell command
    shell: echo 'hello world'
    register: result
  - name: next task that need special results
    debug: msg="result is {{ result.stdout }}"
##### EXPECTED RESULTS

playbook finishes without errors
### "hello world" in stdout is present playbook works

me@hostname:~/ansible2$ ansible-playbook -i test.ini test.yml
using environment for Ansible 2.0.1.0

PLAY ***************************************************************************

TASK [setup] *******************************************************************
20160811 11:44:39 +0200 (0:00:00.145)       0:00:00.145 **********************\* 
ok: [localhost]

TASK [run shell command] *******************************************************
20160811 11:44:41 +0200 (0:00:02.270)       0:00:02.415 **********************\* 
changed: [localhost]

TASK [next task that need special results] *************************************
20160811 11:44:43 +0200 (0:00:01.458)       0:00:03.873 **********************\* 
ok: [localhost] => {
    "msg": "result is hello world"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   
#20160811 11:44:43 +0200 (0:00:00.083)       0:00:03.956 **********************\* 

TASK: setup ------------------------------------------------------------- 2.27s
TASK: run shell command ------------------------------------------------- 1.46s
TASK: next task that need special results ------------------------------- 0.08s
Playbook run took 0 days, 0 hours, 0 minutes, 3 seconds
### "hello world" and even stdout is NOT present playbook fails

me@hostname:~/:~/ansible2$ ansible-playbook -i test.ini test.yml --check
using environment for Ansible 2.0.1.0

PLAY ***************************************************************************

TASK [setup] *******************************************************************
20160811 11:44:47 +0200 (0:00:00.132)       0:00:00.132 **********************\* 
ok: [localhost]

TASK [run shell command] *******************************************************
20160811 11:44:49 +0200 (0:00:02.317)       0:00:02.450 **********************\* 
skipping: [localhost]

TASK [next task that need special results] *************************************
20160811 11:44:51 +0200 (0:00:01.488)       0:00:03.939 **********************\* 
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'dict' object has no attribute 'stdout'"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @/c/data/home/lb87876/ansible2/retry/test.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
#20160811 11:44:51 +0200 (0:00:00.068)       0:00:04.008 **********************\* 

TASK: setup ------------------------------------------------------------- 2.32s
TASK: run shell command ------------------------------------------------- 1.49s
TASK: next task that need special results ------------------------------- 0.07s
Playbook run took 0 days, 0 hours, 0 minutes, 3 seconds

**Comment by dagwieers** [comment]
I like this idea a lot.

But in a lot of cases command/shell are used to simply query information from the system without it making a change. Usually people already add the `changed_when: no` to those tasks because the task does not really make a change. In these cases we could simply allow the command to be run as well.

In itself this is probably not a good idea, because we are assuming intent, but there is a larger picture here that your proposal could cover IMO.

**Comment by robinro** [comment]
I like the general idea, but am not sure how to best set it up.

You can already now implement a workaround: use `check_mode: no` (or `always_run: yes` for <2.2) in combination with `when: ansible_check_mode` to specify dry-run versions of your shell commands. See http://docs.ansible.com/ansible/playbooks_checkmode.html for the general uses.

**Comment by samdoran** [comment]
Closing per above suggestion.
