### ISSUE TITLE
Slightly Misleading Documentation

### ISSUE THREAD

**Issue by nickmisasi** [ansible/ansible#17048]
##### ISSUE TYPE

- Documentation Report
##### COMPONENT NAME

Dynamic Inventory
##### ANSIBLE VERSION

```
2.1.1.0
```
##### CONFIGURATION

Vanilla
##### OS / ENVIRONMENT

Ubuntu Trust
##### SUMMARY

There is a slightly misleading line in the "Developing Dynamic Inventory" documentation page. Under scripting conventions [http://docs.ansible.com/ansible/developing_inventory.html#script-conventions](url)  the documentation states 

> When the external node script is called with the single argument --list, the script must return a JSON hash/dictionary of all the groups to be managed

Saying that the script must RETURN a JSON hash/dictionary implies that the script should end with something like:
`return json.dumps(inventory)`
When in reality you actually have to print the object to stdout. I don't know if this is just my understanding of the documentation but I spent more time than I'd like to admit trying to figure out why Ansible would not accept the dynamic inventory script.
##### STEPS TO REPRODUCE

return the object instead of outputting to stdout

```
print json.dumps(groups, indent=2, sort_keys=True)
vs.
return json.dumps(groups, indent = 2, sort_keys=True)
```

##### EXPECTED RESULTS

Using a return call in a script to return the json object
##### ACTUAL RESULTS

you need to print it to stdout

```

```

**Comment by dagwieers** [comment]
@nickmisasi13 You are 100% correct. Can you make the changes as you would like to see them ?
Just follow the link below, modify the documentation and create the commit. (It will fork/clone, commit and make a PR)

https://github.com/ansible/ansible/edit/devel/docsite/rst/developing_inventory.rst

Good luck, and thanks in advance !

**Comment by dharmabumstead** [comment]
I can do it.

**Comment by dagwieers** [comment]
@nickmisasi13 Great, thanks a lot !
