### ISSUE TITLE
add commandline params as built-in variables for playbooks

### ISSUE THREAD

**Issue by muellerrainer** [ansible/ansible#17041]
##### ISSUE TYPE
- Feature Request
##### COMPONENT NAME

ansible core
##### ANSIBLE VERSION

2.x
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I would like to work with "when" switches in ansible tasks that relay on commandline switches.
For example:
a)
If the option --check is given i want to change the behaviour of an shell/command task.
b)
If the option -vvvv is given i want to run extra tasks that produce extra debug output with the debug: msg="" task.
##### STEPS TO REPRODUCE

ansible web -m setup
##### EXPECTED RESULTS

Key : Value structure for the commandline parameters...

ansible web -m setup -a 'filter=ansible_commandline'
        "ansible_commandline'": {
            "check": "false", 
            "become": "root",
            "verbose": "4"
             ...
             ...
             ...
        },
##### ACTUAL RESULTS

=> none

Output:
  "ansible_facts": {},

**Comment by bcoca** [comment]
In current devel  you have `ansible_check_mode` set to `True` when --check is passed. 

In a previous version, the `debug` module got a `verbosity=#` field which will print when the number matches or is lower than the number of -v's passed.

**Comment by samdoran** [comment]
`ansible_check_mode` and `ansible_verbosity` are available in recent Ansible versions. You can see all available [magic variables here](https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html#magic-variables).
