### ISSUE TITLE
pip module always indicates change pulling from git

### ISSUE THREAD

**Issue by kadut** [ansible/ansible#1705]
Hello,

My pip module results always indicate "change."  It seems that pip likes to report "Successfully installed" for git packages, or at least commit identified packages, and this throws off the simple change test. 

 Based on my results below, a proposed change to _did_install is given following, but it is short enough and I am not sure enough of all the permutations of pip output to know how general it so so that I didn't do a pull request.
def _did_install(out):
    return 'Successfully installed' in out and out.count('Installed') > out.count('is already the active version')

Thanks,

Keith

I am using a requirements.txt file as follows:

Django==1.4.2
-e git+https://github.com/toastdriven/django-tastypie@94ceb21b091bff26741057bbab42b30bc0ad7dcd#egg=django_tastypie-dev
-e git://github.com/tryolabs/django-tastypie-extendedmodelresource.git@2f7ab47320f8003d2da0f54824e5c24533dd8205#egg=django_tastypie_extendedmodelresource-dev
MySQL-python==1.2.3
[ MORE FILES]
pytz==2012d
-e git://github.com/mfogel/django-timezone-field@ef77e2928aabcedc14b7ba386f547249dc1597a8#egg=django_timezone_field-dev
[MORE FILES]

my "out" result then looks like below, no matter how many times I repeat the run:

[MANY "Requirement already satisfied"]
Requirement already satisfied (use --upgrade to upgrade): httplib2 in ./code/venv/lib/python2.7/site-packages (from oauth2>=1.5.167->django-social-auth==0.7.5->-r /home/vagrant/Tryolabs/deploy/vars/
../templates/celery/lively/requirements.txt (line 13))
Installing collected packages: django-tastypie, django-tastypie-extendedmodelresource, django-timezone-field
  Running setup.py develop for django-tastypie

```
Creating /home/vagrant/Tryolabs/deploy/code/venv/lib/python2.7/site-packages/django-tastypie.egg-link (link to .)
django-tastypie 0.9.12-alpha is already the active version in easy-install.pth

Installed /home/vagrant/Tryolabs/deploy/code/venv/src/django-tastypie
```

  Running setup.py develop for django-tastypie-extendedmodelresource

```
Creating /home/vagrant/Tryolabs/deploy/code/venv/lib/python2.7/site-packages/django-tastypie-extendedmodelresource.egg-link (link to .)
django-tastypie-extendedmodelresource 0.22-dev is already the active version in easy-install.pth

Installed /home/vagrant/Tryolabs/deploy/code/venv/src/django-tastypie-extendedmodelresource
```

  Running setup.py develop for django-timezone-field

```
Creating /home/vagrant/Tryolabs/deploy/code/venv/lib/python2.7/site-packages/django-timezone-field.egg-link (link to .)
django-timezone-field 0.3.0 is already the active version in easy-install.pth

Installed /home/vagrant/Tryolabs/deploy/code/venv/src/django-timezone-field
```

Successfully installed django-tastypie django-tastypie-extendedmodelresource django-timezone-field

**Comment by sfromm** [comment]
I think it should be possible to update __is_package_installed()_ to check the requirements file.  Will take a look.

**Comment by sfromm** [comment]
Should be fixed with d277953.

**Comment by hxu** [comment]
I seem to still have this issue with ansible 1.6.1, should it be fixed in this version?

**Comment by ildus** [comment]
I confirm, the issue still exists

**Comment by billputer** [comment]
I'm also having this problem. It only happens when I have state=latest and not state=present, so I'm assuming it has to do with the update check.

**Comment by michaelrice** [comment]
Im having this problem with 1.9.2

**Comment by nlevitt** [comment]
Problem seems to persist in ansible 2.1.1.0 (why is this issue closed?)

**Comment by wolfedale** [comment]
I'm using ansible-2.2.0.0-3.el7 and have the same problem using pip.

**Comment by charlesj** [comment]
Seeing the same issue in ansible 2.2.0.0.  Here is the task:

```
- name: Install Powerline
  pip:
    name: powerline-status
    state: present
```

It shows up as "changed" every time.

**Comment by ghost** [comment]
Same for me. Ansible 2.2.0.0 shows changed every time, whether state=present or state=latest.

**Comment by ghost** [comment]
In my case, I discovered the problem to be with pip itself. Specifically, my OS (ubuntu 12.04) had pip 1.0 in its repo. I created a 'pip' role that includes just:

```
---
- name: Install Python PIP
  become: true
  apt:
    pkg: python-pip
    state: latest

- name: Upgrade PIP
  become: true
  pip:
    name: pip
    version: "{{ pip_version }}"
```

Setting this as a dependency for my modules using pip fixed the spurious diff issue. YMMV.
