### ISSUE TITLE
Add an interactive debug shell

### ISSUE THREAD

**Issue by toadjaune** [ansible/ansible#17056]
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

Add an interactive debug shell
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

None
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Sometimes, you have a complex playbook, of which you can't easily run only a small part for your debugging tests.

Currently, when debugging a playbook, we only have the [debug module](http://docs.ansible.com/ansible/debug_module.html) to see the value of a variable.
This means that during the debugging process, you need to run the whole playbook many times, losing a lot of time.

The idea would be to introduce a task pausing the playbook and bringing you to an interactive shell, where you could display variables values in the current context.

We could then imagine many other uses, like displaying the entire stack of a variable to help resolving variable precedence issues, or manually setting a value for a test ...
##### STEPS TO REPRODUCE

Example play : 

```
- hosts: all
  tasks:
  - debug: shell=true
```

Of course, this could be part of the debug module or not, I don't know which option would be the most pertinent from a programmation point of view.

##### EXPECTED RESULTS

We could expect the result to look like that : 

```
TASK [debug : interactive shell] ****************
This is an interactive shell, for debugging purposes.
Type help for a list of commands
$ value my_variable
"host-specific value"
$ value my_variable != "Hello World"
true
$ stack my_variable
[HOST_VARS] : "host-specific value"
[GROUP_VARS](group1) : "value for group1"
[GROUP_VARS](group2) : "value for group2"
[ROLE_DEFAULT] : "default value for role"
$ exit
Resuming play ...
...
```

Of course, the list, names and effects of commands would need to be discussed, but before doing anything in this direction, what do you think of the overall idea ?

**Comment by tumbl3w33d** [comment]
Wouldn't it be sufficient to have an additional verbosity level (-vvvvvv) or an additional debug parameter which prints all/filtered context variables?

**Comment by bcoca** [comment]
is this what you wanted https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/strategy/debug.py?

**Comment by toadjaune** [comment]
Since I never really coded in Python, I could not really understand this code, even if it seems close.

Assuming I install Ansible from the develop branch on my machine, how can I try this code ?

**Comment by bcoca** [comment]
this should be in the 2.1 release, just add:

```
strategy: debug
```

to your play

**Comment by toadjaune** [comment]
Infact, this is exactly what I was looking for, I even found the relevant [documentation page](https://docs.ansible.com/ansible/playbooks_debugger.html).

I think it might be interesting to add a few links to this documentation.
Infact, since I wasn't able to find it before opening an issue here, I guess I'm probably not the only one to find it difficult to find.

For example, I think adding a note on the [Variables](http://docs.ansible.com/ansible/playbooks_variables.html) page could be a good idea.

I also think that the "stack" command previously described could be really useful for debugging variable precedence issues, even if it is possible to work around its absence by manually echoing variables such as hostvars[...].

**Comment by bcoca** [comment]
closing this ticket then since that meets the main requirements of it.

We have some plans about variable introspection but that is not currently available at play runtime (all is flattened by then), looking at possible ansible-inventory tool for that.
