### ISSUE TITLE
RHEV virtualization is not detected

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#17058]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

setup module_util
##### SUMMARY

The default facts do not cover RHEV virtualization, and while RHEV is using KVM underneath it would be useful for users to make a clear distinction between a RHEV host and a normal KVM host.

I don't know if there is a way to determine if a VM is a RHEV guest, but it probably doesn't matter that much as it does for hosts.

**Comment by machacekondra** [comment]
@dagwieers  I see it's there:

https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts.py#L2923

Also it works for me:

```
[root@10-34-60-84 ~]# cat /sys/devices/virtual/dmi/id/product_name 
RHEV Hypervisor
```

So what's the problem you have?

**Comment by bcoca** [comment]
The problem is that it exists at the FIRST virtualization it finds so i doubt that part of the code ever gets hit as 'kvm' will be positive first.

**Comment by dagwieers** [comment]
@machacekondra For a guest, that's fine. But a RHEV host is reported to be a kvm host. Which is not wrong, but doesn't allow us to distinguish a RHEL server with kvm from a RHEV host.

I do not know yet what information (on the RHEV host) would be best to make the distinction in our facts, but we definitely need to make that distinction when managing servers.

**Comment by dagwieers** [comment]
Alright, after looking into this, I think the easiest/best way is to detect if a process named **vdsm** is running. The **vdsm** process is absolutely required on any RHEV host in order to manage and monitor the host's storage, memory and networks as well as VM creation.

The installation of the **vdsm** package may not mean it is a RHEV host (since it could be something left over), existence of files on the filesystem poses the same problem.

Another option is to check for the **qemu-kvm-rhev** or **qemu-img-rhev** package, but similarly, the installation of a package does not necessarily indicate that the software is running/active. However I noticed that the vdsm package does create a _/rhev/_ directory

We could test a combination of both, to guarantee that we are not testing for something else that happens to be called vdsm. So I would go for:
- If we have determined that the system is a kvm host
- Test if a vdsm process is running
- Test if /rhev/ exists (part of the vdsm package)
- Conclude we have a rhev host and report it accordingly

So I will propose this as an improvement to our setup logic.

**Comment by dagwieers** [comment]
Here's a working implementation:

``` python
if 'kvm' in modules:
    vdsm_found = False

    if HAS_PSUTIL:
        for proc in psutil.process_iter():
            if proc.name() == 'vdsm':
                vdsm_found = True
                break

    # Check whether this KVM host is a RHEV hypervisor
    if vdsm_found and os.path.isdir('/rhev/'):
        self.facts['virtualization_type'] = 'rhev'
    else:
        self.facts['virtualization_type'] = 'kvm'
    self.facts['virtualization_role'] = 'host'
    return
```

The problem is that we require the psutil module in order to find vdsm, and maybe that's asking to much. (We'd be defaulting to a false negative) I could go iterating in _/proc_ myself instead ? :-/

**Comment by dagwieers** [comment]
I rewrote it like this now:

``` python
if 'kvm' in modules:

    # Build list of process-names
    proc_list = []
    for f in glob.glob('/proc/[0-9]*/comm'):
        try:
            proc_list.append(open(f).read().rstrip())
        except:
            pass

    # Check whether this KVM host is a RHEV hypervisor
    if 'vdsm' in proc_list and os.path.isdir('/rhev/'):
        self.facts['virtualization_type'] = 'rhev'
    else:
        self.facts['virtualization_type'] = 'kvm'
    self.facts['virtualization_role'] = 'host'
    return
```

Which should be fine.

**Comment by alikins** [comment]
See also the somewhat related https://github.com/ansible/ansible/pull/15166
and https://github.com/ansible/ansible/issues/15165

Those are the 'openstack' analog instead of RHEV, but both add collection of  'yes it is a KVM host, but it is also...' facts.

**Comment by alikins** [comment]
The RHEV and openstack pr's both point to current virt facts not being sufficient. 
Maybe add a 'virtualization_product' field?

So rhev, ovirt, openstack, would all be virtualization_type=kvm, but with virtualization_product='openstack' etc  (At least all the stuff looking at 
/sys/devices/virtual/dmi/id/product_name)

[ or 'virtualization_product_name' etc...]

**Comment by dagwieers** [comment]
@alikins @bcoca already pointed me to this: https://github.com/ansible/ansible/issues/17151#issuecomment-241408224

But in the meantime we could at least support RHEV hosts using the current fact names.
I am all for refactoring this in the future.
