### ISSUE TITLE
Mandatory variable not defined - since Ansible 2

### ISSUE THREAD

**Issue by sakaal** [ansible/ansible#17065]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Core, setup, etc. Affects all my playbooks.
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

```
[defaults]
vault_password_file = ~/.vault_pass.txt
```
##### OS / ENVIRONMENT

N/A (Fedora 24)
##### SUMMARY

I have very large Ansible inventories with dozens of hosts and multiple layers of group variables. Many variable values contain references to other variables. The total number of variables is several hundreds. Several variables are dynamically defined during playbook runs, so they are not yet defined in the beginning of a play, but will be declared later on - before the point where they are needed.

Everything worked (and still works) fine with Ansible 1.9.x. After upgrading to Ansible 2.x, Ansible no longer runs but fails with the following error already during the setup module run - i.e. when gathering facts:

```
localhost | FAILED! => {
    "failed": true,
    "msg": "Mandatory variable not defined."
}
```

This happens whenever any of my large inventories is given from command line using the the -i option. The result is the same for the ansible-playbook and plain ansible commands; for example, ansible -m setup -i _inventory_ localhost gives the same error as ansible-playbook _playbook_ -i _inventory_. It appears like Ansible 2.x tries to interpret the whole inventory before running the setup module, and fails when some mandatory variable is missing.

Now, I would be happy to edit my inventories and playbooks to define whatever missing variables, but the error message does not specify which variable is missing. Since I have hundreds of variables, some set dynamically, it is impossible to debug this situation.
##### STEPS TO REPRODUCE

Create an inventory with nested groups and mandatory group variables with values referencing other variables. Use the group_vars/ and host_vars/ subdirectories to set the variables. Leave some of the mandatory variables undefined for a playbook that uses the set_fact module to dynamically set them later.

Then run:

```
ansible -m setup -i inventory localhost
```
##### EXPECTED RESULTS

A) The playbook should run (like it did with Ansible 1.9) and use the dynamically set variables declared later in the playbook.

B) Should the run fail, the error message should at least specify which variable is undefined, to allow diagnosing and fixing the problem.
##### ACTUAL RESULTS

The run will fail immediately, right at or before running the setup module (gathering facts). You will get an error message that does not specify which variable is not defined.

```
localhost | FAILED! => {
    "failed": true,
    "msg": "Mandatory variable not defined."
}
```

**Comment by sakaal** [comment]
People who are struggling with this issue on Fedora 24 may find this trick helpful. Ansible 1.9 is no longer available in F24 release. As a workaround, I have reverted to the ansible1.9 package that is found in Fedora 23:

```
# On Fedora 24, first uninstall Ansible 2.x like so:
sudo dnf erase ansible
```

Then you can install the older version 1.9.x like so:

```
sudo dnf install ansible1.9 --releasever=23
```

**Comment by alikins** [comment]
> Create an inventory with nested groups and mandatory group variables with values referencing other variables. Use the group_vars/ and host_vars/ subdirectories to set the variables. Leave some of the mandatory variables undefined for a playbook that uses the set_fact module to dynamically set them later.

Have an example playbook that shows this?

**Comment by sakaal** [comment]
I have several, but I'm afraid they are all proprietary and confidential. When I have time, I may be able to produce an anonymized one. Not sure when I have time though. Meanwhile, simply adding the name of the undefined mandatory variable to the aforesaid error message would be useful in any case - even if you couldn't reproduce this exact situation. It doesn't hurt to have descriptive error messages that help quickly solve errors.

**Comment by bcoca** [comment]
That message is from the `|mandatory` filter, that should help narrow it down

**Comment by sakaal** [comment]
In many cases this was likely due to the backwards incompatible change of the variable names `ansible_ssh_host` and `ansible_ssh_port` to `ansible_host` and `ansible_port`. There may have been also other reasons. The problem eventually disappeared after we set defaults for all the variables that were changed.
