### ISSUE TITLE
Changed target host key causes failed SSH connection

### ISSUE THREAD

**Issue by c-mart** [ansible/ansible#17068]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

SSH
##### ANSIBLE VERSION

```
2.1.1.0
```
##### CONFIGURATION

See below
##### OS / ENVIRONMENT

Managing from Xubuntu 16.04 LTS. Target nodes running any OS (Ubuntu 16.04, 14.04, 12.04; CentOS 7 and 6).
##### SUMMARY

I am still experiencing failed host key checking on changed target host key (see #9442), even with host key checking disabled in ansible.cfg or via environment variable, until I remove the old entries from my known_hosts file. I would think that if host key checking is disabled, the contents of my known_hosts file should have no bearing on whether Ansible can connect.

Also, more of a feature request than bug report: it would be really nice if I could disable host key checking for specific test VMs using group_vars or variables in my inventory file.
##### STEPS TO REPRODUCE

```
$ export ANSIBLE_HOST_KEY_CHECKING=False
$ ansible-playbook -u myuser -k playbooks/myplaybook.yml -i hosts
```
##### EXPECTED RESULTS

SSH connection completes and playbook runs.
##### ACTUAL RESULTS

```
fatal: [ubuntu1404]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
```

**Comment by alikins** [comment]
Could you provide the output from a failed ansible run with '-vvvvv' added?

```
ansible-playbook -vvvvv -u myuser -k playbooks/myplaybook.yml -i hosts
```

Is this using ssh or paramiko?

**Comment by c-mart** [comment]
Good news - I cannot reproduce now. Must have been doing something wrong last week.
