### ISSUE TITLE
/r/n did not get removed when variable passed through regex_replace

### ISSUE THREAD

**Issue by AseemKumar** [ansible/ansible#17083]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

regex_replace filter in raw module
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

Default config.
##### OS / ENVIRONMENT

ansible is running on Ubuntu Trusty and the systems being managed are linux and Windows.
##### SUMMARY

I am trying to uninstall an application which is on Windows server. The windows box has PS 4 installed. I am querying the list of installed apps and filtering on name to get the GUID, and storing that GUID in a register. When I print the register, I get a carriage return and line feed along with it. Then I pass that GUID to msiexec command being executed through raw module. I piped the stdout to regex_replace to remove the \r\n but the replacement did not work.
I tested the same in debug module and the replacement worked. Am I doing something wrong or the evaluation of jinja filters in raw module has some issues?
##### STEPS TO REPRODUCE

1) Getting the GUID:

```
  - name: Get the GUID of OA UI application
    raw: Get-WmiObject -Class Win32_Product | Where-Object { $_.Name -match "SomeApp" } | select -ExpandProperty IdentifyingNumber
    register: UIGUID
```

2) Passing the GUID to uninstall command. The regex_replace did not work here:

```
  - name: Uninstall existing OA version
    raw: start-process msiexec.exe -arg "/X {{ UIGUID.stdout | regex_replace('(\\r\\n)','') }} /qn /lvx! d:\logfiles\MSIuninstall.log" -wait -PassThru
```

3) Tested the regex replace by putting in another variable and that works

```
  - name: print UIGUID
    debug:
      msg: "{{ UIGUID.stdout | regex_replace('(\\r\\n)','') }}"
```

##### EXPECTED RESULTS

Output of 2) should be:

```
EXEC start-process msiexec.exe -arg "/X {CA483236-0405-11E3-B979-3AC26088709B} /qn /lvx! d:\logfiles\MSIuninstall.log" -wait -PassThru
```
##### ACTUAL RESULTS

Output of 1) is

```
ok: [servername] => {"changed": false, "invocation": {"module_args": {"_raw_params": "Get-WmiObject -Class Win32_Product | Where-Object { $_.Na
me -match \"SomeApp\" } | select -ExpandProperty IdentifyingNumber"}, "module_name": "raw"}, "rc": 0, "stderr": "", "stdout": "{CA483236-0405-
11E3-B979-3AC26088709B}\r\n", "stdout_lines": ["{CA483236-0405-11E3-B979-3AC26088709B}"]}
```

Output of 2) is.

```
<servername> EXEC start-process msiexec.exe -arg "/X {CA483236-0405-11E3-B979-3AC26088709B}
/qn /lvx! d:\logfiles\MSIuninstall.log" -wait -PassThru
```

Output of 3) is

```
ok: [servername] => {
    "msg": "{CA483236-0405-11E3-B979-3AC26088709B}"
}
```

**Comment by nrwahl2** [comment]
@AseemKumar Can you please test this using the current Ansible devel branch?

**Comment by felipelrz** [comment]
Try `"{{ UIGUID.stdout | trim }}"`

Source: https://stackoverflow.com/questions/32016123/how-to-remove-the-line-breaker-character-n-from-the-result-of-lookup-module

**Comment by gundalow** [comment]
Change the behaviour may break existing users. It sounds like people are happy with `trim`
