### ISSUE TITLE
Blank spaces in limit file does not work

### ISSUE THREAD

**Issue by pujan14** [ansible/ansible#17088]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ansible --limit hosts
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

If there are spaces after name of host in ansible limit file (retry file?) ansible does not include them.
##### STEPS TO REPRODUCE

name of the host is same as inventory file but with a blank space before end of line.

```
ansible-playbook test.yml -i inventory --limit @test.txt
```
##### EXPECTED RESULTS

playbook should be executed for hosts that are in both inventory and test.txt files.
##### ACTUAL RESULTS

```
ERROR! Specified --limit does not match any hosts
```

**Comment by jctanner** [comment]
@pujan14 the retry file is usually a single column of host aliases ...

```
[jtanner@fedmac AP-17088]$ cat site.retry
u1404
u1404a
u1404b
u1404c
```

I'm not clear on why there are spaces in yours. Could you show me an example?

**Comment by pujan14** [comment]
@jctanner file when created by ansible is without spaces but when I manually create file that's when this becomes an issue.

I know this is not the main or intended purpose of this feature but sometimes it's handy when you have long list of machines from different inventory groups.

**Comment by pujan14** [comment]
any updates?

**Comment by richard-scott** [comment]
If you have white space at the end of hostname/IP Address on a line then the file gets rejected.
Likewise it does not like comments in this file either.

**Comment by richard-scott** [comment]
As an example:

Example:
```
$ cat -A host_vars/exclude
!10.0.0.73 $
!10.0.190.60$
!10.0.4.213$
```

As you can see above, the $ are put in by the "cat -A" command so you can see where spaces stuff are, the $ are not really at the end of the lines in my file. But as you can see, the first line has a stray space at the end of the IP address of my host.

This causes Ansible to reject the --limits option and tells me it does not match any host.

EDIT: Actually it causes Ansible to skip the line with the space at the end of it. Comments cause Ansible to reject the file totally.

**Comment by richard-scott** [comment]
Oh, also my version of Ansible is:

```
$ /usr/bin/ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

**Comment by gundalow** [comment]
Discussed in Backlog meeting. Trimming whitespace should be something we do.
