### ISSUE TITLE
Loop-until does not loop over includes

### ISSUE THREAD

**Issue by github-abcde** [ansible/ansible#17098]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

loop-until
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No changes to the default configuration.
##### OS / ENVIRONMENT

Running Ansible on: Ubuntu 16.04.1 LTS
Managing: Centos 7.2.1511 (Core)
##### SUMMARY

Trying to use loop-until with an include-statement does not loop at all.
##### STEPS TO REPRODUCE

```
main.yml:

---
- hosts: ansibletest
  remote_user: root
  tasks:
  - set_fact:
      counter: 1
  - include: add1.yml
    until: counter == 3
    retries: 5
  - debug: msg="The counter is [{{ counter }}]"

add1.yml:

---
- set_fact:
    counter: "{{ counter | int + 1 }}"
```
##### EXPECTED RESULTS

PLAY [ansibletest] *************************************************************

TASK [setup] *******************************************************************
ok: [ansibletest]

TASK [set_fact] ****************************************************************
ok: [ansibletest]

TASK [set_fact] ****************************************************************
ok: [ansibletest]

TASK [set_fact] ****************************************************************
ok: [ansibletest]

TASK [debug] *******************************************************************
ok: [ansibletest] => {
    "msg": "The counter is [3]"
}

PLAY RECAP *********************************************************************
ansibletest                : ok=4    changed=0    unreachable=0    failed=0   
##### ACTUAL RESULTS

```
PLAY [ansibletest] *************************************************************

TASK [setup] *******************************************************************
ok: [ansibletest]

TASK [set_fact] ****************************************************************
ok: [ansibletest]

TASK [set_fact] ****************************************************************
ok: [ansibletest]

TASK [debug] *******************************************************************
ok: [ansibletest] => {
    "msg": "The counter is [2]"
}

PLAY RECAP *********************************************************************
ansibletest                : ok=4    changed=0    unreachable=0    failed=0   
```

**Comment by nitzmahone** [comment]
`until:` is not currently supported on includes.

**Comment by Chrislevi** [comment]
When is it going to be supported? @nitzmahone

**Comment by nerdvegas** [comment]
Given the lack of this feature, how should I go about repeatedly attempting a list of tasks until the end result is successful? The only thing I can think of is to somewhat bypass ansible, and repeatedly try executing a bash script (produced from ansible template) until it succeeds.

+1 for this feature, since it seems arbitrary to be able to repeat-until on a single task, but not a task list.

**Comment by ivotron** [comment]
@nerdvegas what you describe is what I ended up doing as a workaround (within a role):

```yaml
- name: wait for list of tasks to finish
  local_action: command {{ role_path }}/scripts/loop-until-tasks -i {{ inventory_file }}
  register: wait_for_result
  run_once: true
```

the `{{ role_path }}/scripts/loop-until-tasks` script contains a bash loop, iterating a call to ansible that executes a list of tasks (and breaks out when they all succeed). Thus, this is actually running a repeat-until nested play. The above is a simplified version of what's here https://github.com/ivotron/baseliner/blob/c84200c519ad8798a059390bf1b0b61ee4a92cce/tasks/run-container.yml#L114

**Comment by atnoslen** [comment]
Using Ansible for networking.  Have many tasks that require asynchronous convergence before continuing on.  However, that requires several tasks to perform the checks.  

1. Connect to device and get information.
2. REGEX the data (not all modules come back with structured data yet). 
3. Format to structured data.
4. Assert values are good or bad.

For a concrete example, checking BGP neighbor adjacency on a Cisco IOS device.  Run the command, send it through REGEX, turn into structured data, assert neighbor is up or down.  

I want to repeat every 30 seconds until it is up, or fail after 3 tries.  Currently, we do not have this capability unless I manually put several includes with when clauses back to back to back.

**Comment by e-tienne** [comment]
"_until: is not currently supported on includes._"

I've reproduced the issue #17098 with Ansible 2.4.2.0 and there is still no error message.
I believe we should see an error message if it is not supported. This would add clarity for anyone who runs into the same issue.

**Comment by orthanc** [comment]
Another workaround is to replace the do-until loop with a seqence loop, a when clause, a delay and an assert. E.g. the following works and achieves largely the same goal as the example in the bug report

```
main.yml:

---
- hosts: ansibletest
  remote_user: root
  tasks:
  - set_fact:
      counter: 1
  - include: add1.yml
    loop: "{{ range(0, 6, 1) }}" # Loop for as many times as we want to retry
  - assert:
      that: counter == 3 # Fail if we exhaust the loop without meeting the condition
  - debug: msg="The counter is [{{ counter }}]"

add1.yml:

---
- block:
  - set_fact:
      counter: "{{ counter | int + 1 }}"
  - wait_for:
      timeout: ... # Delay between retries if we haven't yet met the condition
    when: counter != 3
  when: counter != 3 # Skip remaining retries if the desired condition is met
```

**Comment by sivel** [comment]
As has been mentioned, `until` does not work on an `include` currently, and if it did, it wouldn't achieve the results that I imagine most users would expect.

An `include` (or `include_X`) is more of a trigger, instead of something that actually wraps the tasks within from an execution perspective.

An `until` on an include, if we made it work now, would only loop based on whether or not including the task file was successful, not whether anything within the task file did a certain action.

We have a proposal to make includes work more like tasks, rather than just a trigger to do something internally:  https://github.com/ansible/proposals/issues/136

If we ever decide to implement https://github.com/ansible/proposals/issues/136 this will be one of those features we will look to *include*.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by furstenheim-geoblink** [comment]
Taking into account that until is not supported for include tasks. Would it make sense to mark it as invalid the cli with `--syntax-check`?

**Comment by furstenheim-geoblink** [comment]
> Another workaround is to replace the do-until loop with a seqence loop, a when clause, a delay and an assert. E.g. the following works and achieves largely the same goal as the example in the bug report
> 
> ```
> main.yml:
> 
> ---
> - hosts: ansibletest
>   remote_user: root
>   tasks:
>   - set_fact:
>       counter: 1
>   - include: add1.yml
>     loop: "{{ range(0, 6, 1) }}" # Loop for as many times as we want to retry
>   - assert:
>       that: counter == 3 # Fail if we exhaust the loop without meeting the condition
>   - debug: msg="The counter is [{{ counter }}]"
> 
> add1.yml:
> 
> ---
> - block:
>   - set_fact:
>       counter: "{{ counter | int + 1 }}"
>   - wait_for:
>       timeout: ... # Delay between retries if we haven't yet met the condition
>     when: counter != 3
>   when: counter != 3 # Skip remaining retries if the desired condition is met
> ```

Just a small comment on the code. In order to make it work I had to do {{ range(0, 6, 1) | list }}
