### ISSUE TITLE
Playcontext accumulates tags from different PlaybookExecutor instances

### ISSUE THREAD

**Issue by krzsza** [ansible/ansible#17103]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/kszajers/EPOS_plat//test/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

[defaults]
inventory = $WORKSPACE/test/ansible/vars/hosts
log_path = $PWD/ansible-report.log
timeout = 30
remote_port = 22
host_key_checking = False
private_key_file = $PWD/id_rsa
host_key_checking = False
[ssh_connection]
pipelining = True
##### SUMMARY

I have a code like this:

```
def run(..., tag, ...):
    Options = namedtuple('Options', ['tags',...])
    options = Options(tags=tag,...)
    pbex = PlaybookExecutor(..., options=options,...)
    pbex.run()
run('tag1')
run('tag2')
run('tag3')
```

At the second call of run() tasks with tag1 and tag2 are run, at the third with tag1, tag2 and tag3 and so on. In playbook/play_context.py (starting from line 288) I can see that PlayContext class only_tags fields accumulates tags even though I create new PlaybookExecutor instance each time. Is there a way for isolate tags for each instance?
##### STEPS TO REPRODUCE
1. Create two PlaybookExecutor instances with different tags.
2. Call run on both.
##### EXPECTED RESULTS

Second run method will run tasks assigned to both tags.

**Comment by bcoca** [comment]
The class is not meant to be reused like that, the CLI itself takes care of this by normal process shutdown. This is not a bug, just not designed for a persistent process.

**Comment by krzsza** [comment]
Workaround: PlayContext._only_tags.default = set()
