### ISSUE TITLE
Fetching of current config in module_utils/junos.py is broken

### ISSUE THREAD

**Issue by agaffney** [ansible/ansible#17111]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

`module_utils/junos.py`
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When using the `junos_config` module and a `delete` command, matching lines in the current configuration are not removed as expected. This appears to be due to a problem with fetching the current config.

The `junos_config` module gets the current config and passes it to `diff_config()` like so:

```
config = str(module.get_config(config_format='set')).split('\n')
updates = diff_config(lines, config)
```

The `get_config()` function in `module_utils/junos.py` makes the `get_configuration` RPC call and passes the `config_format` parameter to the function as the `format` parameter in the RPC call. However, it appears that this RPC call does not support the value `set` for this parameter, so XML is returned instead. The `get_config()` function calls `ele.text` expecting to get a text-based configuration between the top-level tags, but instead gets back an empty string, because nested XML was returned instead.

The JunOS 14.1 docs for the `get-configuration` RPC call clearly show that `set` is not a supported value for the `format` parameter:

https://www.juniper.net/documentation/en_US/junos14.1/topics/reference/tag-summary/netconf-junos-xml-protocol-get-configuration.html

Possible solutions are a function to convert the XML or `text` format into the `set` format, or running a command such as `show | display set` via the CLI instead of doing a netconf XMLRPC call.
##### STEPS TO REPRODUCE

Try to delete a value from the config using the `junos_config` module. I ran into this doing:

```
  - junos_config:
      lines:
      - delete system ntp
      - set system ntp server 5.6.7.8
      provider: "{{ junos_provider }}"
```
##### EXPECTED RESULTS

```
TASK [junos_config] ************************************************************
changed: [junos-1.foo.com] => {"changed": true}

[edit system ntp]
-     server 1.2.3.4;
+     server 5.6.7.8;
```
##### ACTUAL RESULTS

```
TASK [junos_config] ************************************************************
changed: [junos-1.foo.com] => {"changed": true}

[edit system ntp]
     server 1.2.3.4 { ... }
+    server 5.6.7.8;
```

**Comment by agaffney** [comment]
@privateip, you seem to be the primary author/maintainer of the junos bits

**Comment by agaffney** [comment]
Also, as an additional note, if you have uncommitted config changes (done manually via SSH) that `delete` a configuration item/section, those changes _will_ show as being removed in the diff output, but mostly because the network device is generating that diff output (I think).

**Comment by agaffney** [comment]
This can _probably_ be fixed by doing something like the following in `get_config()`:

```
        if config_format == 'set':
            return self.run_commands(('show configuration | display set'))[0].strip()
        else:
            ele = self.rpc('get_configuration', format=config_format)
            if config_format == 'text':
               return str(ele.text).strip()
            elif config_format == "xml":
                return ele
```

**Comment by gundalow** [comment]
@ksator You may wish to subscribe to this issue

**Comment by agaffney** [comment]
Testing with a custom copy of `junos_config.py` that monkey-patches the `get_config()` function, my suggested fix above appears to work. I would submit it as a PR, but it's probably not the "right" way to solve this issue.

**Comment by gundalow** [comment]
@privateip and I reviewed this today, we believe it's fixed. Added the `2.2.0` milestone to ensure we test this specific case before release

**Comment by agaffney** [comment]
@gundalow, do you know what PR/commit(s) this was fixed in?

**Comment by privateip** [comment]
@agaffney its fixed in the module ansible/ansible-modules-core#4692.  For 2.2, we are dropping support for the module trying to calculate the diff and relying exclusively on the device diff.  We now just read the returned diff to decide if a change is made or not.   Therefore, the module no longer needs to retrieve a copy of the active configuration.

**Comment by privateip** [comment]
This is now resolved and passing in all current test cases.  Had to add back the code for validating changes using `set ...` commands due to a limitation in junos-eznc that will error on delete statements.
