### ISSUE TITLE
Var of var in Ansible Playbook

### ISSUE THREAD

**Issue by Kenovo** [ansible/ansible#17118]
Hello,
i try to do a var of var in a playbook on Ansible but i can't figure out how to do this proprly, or if it is even possible ?
here is what i try to do : 
 `"name : {{ groups['{{ ANOTHER_VAR_HERE }}'][0] }}"`
Ansible --version : ansible 2.1.0.0

Thank you

**Comment by pauricthelodger** [comment]
@Kenovo - either:
`name: "{{ groups[ANOTHER_VAR_HERE][0] }}"`
or
`name: "{{ groups.ANOTHER_VAR_HERE[0] }}"`
should do the trick

**Comment by Kenovo** [comment]
Thank you for your reply,
it doesnt work for me : 
`fatal: [localhost]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'ANOTHER_VAR_HERE'"}`

PS : ANOTHER_VAR_HERE its a variable that i include from a vars file (its not a String its a real variable)

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
