### ISSUE TITLE
Do-until loops does not fail after the last iteration when using failed_when

### ISSUE THREAD

**Issue by dhose** [ansible/ansible#17117]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

default
##### OS / ENVIRONMENT

Linux
##### SUMMARY

Do-until loops does not fail after the last iteration when using failed_when
##### EXAMPLE PLAYBOOK 1

```

---

- hosts: localhost
  tasks:
    - command: echo "not started"
      register: test_result
      until: test_result.stdout == 'finished' or test_result.stdout == 'error'
      retries: 3
      delay: 1
```
##### OUTPUT

```
TASK [command] *****************************************************************
FAILED - RETRYING: TASK: command (3 retries left).
FAILED - RETRYING: TASK: command (2 retries left).
FAILED - RETRYING: TASK: command (1 retries left).
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["echo", "not started"], "delta": "0:00:00.001682", "end": "2016-08-17 10:20:54.328148", "failed": true, "rc": 0, "start": "2016-08-17 10:20:54.326466", "stderr": "", "stdout": "not started", "stdout_lines": ["not started"], "warnings": []}

```
##### EXAMPLE PLAYBOOK 2

```

---
- hosts: localhost
  tasks:
    - command: echo "not started"
      register: test_result
      until: test_result.stdout == 'finished' or test_result.stdout == 'error'
      failed_when: test_result.stdout == 'error'
      retries: 3
      delay: 1
```
##### OUTPUT

```
TASK [command] *****************************************************************
FAILED - RETRYING: TASK: command (3 retries left).
FAILED - RETRYING: TASK: command (2 retries left).
FAILED - RETRYING: TASK: command (1 retries left).
changed: [localhost]
```

**Comment by nitzmahone** [comment]
It appears to be working as designed- `failed_when:` is evaluated after the task has completed, and your `failed_when:` condition does not signify a failure (as it never includes the word error). To simplify and maybe understand it a little better, try with `failed_when: false` and `failed_when: true` to see that it is indeed working as designed.

**Comment by poidag-zz** [comment]
I have just been creating another task afterwards to fail if a condition is met on the registered var. But from reading failed_when: initially I thought it would have this effect.

**Comment by nitzmahone** [comment]
It will, but at least for the sample you provided, it will never match the condition.
