### ISSUE TITLE
Vault support for transparent binary file encryption/decryption

### ISSUE THREAD

**Issue by raghu999** [ansible/ansible#17127]
##### ISSUE TYPE

- Bug Report
- Feature Idea
- Documentation Report
  ##### ANSIBLE VERSION

```
ansible 2.0.2.0
```
##### OS / ENVIRONMENT

Mac-Osx
##### SUMMARY

Thanks for all the work being done in the Ansible world , we really like Ansible and are using it as our configuration Management tool in our company . Coming to my problem i have a docker.tar.gz which is a tar ball of registry2 authentication token which is a part of our ansible play for mesos/marathon. we tried to encrypt this docker.tar.gz and it got encrypted. But the problem here is when we are running ansible-playbook this file is being copied to remote location in Encrypted format. we are giving --vault-password-file in our ansible-playbook command still the file is not getting decrypted any suggestions on this.
##### EXPECTED RESULTS

The expected result here should be the <foo>.tar.gz which we are trying to copy should be decrypted when we use the --vault-password-file
##### ACTUAL RESULTS

The <foo>.tar.gz is being copied to remote location in encrypted format

**Comment by krzysztof-magosa** [comment]
If I'm correct this functionality has been added in Ansible 2.1.

**Comment by bcoca** [comment]
closing as per above
