### ISSUE TITLE
Installing on closed unpatched network (RHEL6 stock image)

### ISSUE THREAD

**Issue by Mister-Jankz** [ansible/ansible#17125]
Any way to get around the dependencies? I'm working on a demo for Ansible on a closed network. Having issues with pycrypto because the installation script can't reach out and find it.

**Comment by alikins** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
  
  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

**Comment by Mister-Jankz** [comment]
Thanks. I was having some issues with IRC this morning I did see there' s a lot of good support in there. I will check out google groups though.
