### ISSUE TITLE
False positive deprecation warning/undefined error

### ISSUE THREAD

**Issue by histrio** [ansible/ansible#17135]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

None
##### OS / ENVIRONMENT

Centos7
##### SUMMARY

After updating from 2.1.0.0 to 2.1.1.0 a have a deprecation warnings about undefined vars.
##### STEPS TO REPRODUCE

Here is my simple demo for this case

Structure:

```
.
├── main.yml
└── roles
    └── common
        └── tasks
            ├── main.yml
            └── test.yml
```

main.yml

```
- name: Setup common tasks
  hosts: all
  become: yes
  roles:
      - common
```

common/main.yml

```
- name: Test include
  include: test.yml
  when: foo is defined
```

common/test.yml

```
- set_fact:
    bar: {"items": [1, 2]}

- name: Test debug
  debug: msg="test"
  with_items: '{{ bar.items }}'
```
##### EXPECTED RESULTS

`ansible-playbook main.yml -i localhost, -c local`

```
PLAY [Setup common tasks] ******************************************************

skipping playbook include 'test.yml' due to conditional test failure

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0  
```
##### ACTUAL RESULTS

I have false positive deprecation warning/undefined error. If I run script from role itself - it's OK.

`ansible-playbook roles/common/tasks/main.yml -i localhost, -c local`

```
skipping playbook include 'test.yml' due to conditional test failure

PLAY RECAP *********************************************************************
```

But if I run this whole playbook it began to write deprecation warnings. 

`ansible-playbook main.yml -i localhost, -c local`

```
PLAY [Setup common tasks] ******************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [common : set_fact] *******************************************************
skipping: [localhost]

TASK [common : Test debug] *****************************************************
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: 'bar' is undefined.
This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0  
```

Variable `bar` will be defined only if `set_fact` task will not be skipped. So when `foo` is defined, `bar` also will be defined.

It think ansible should skip whole include or actually skip all tasks inside it.

**Comment by nitzmahone** [comment]
Adding `static: no` to your `include:` statement should get you the behavior you want- we default to pre-parsing includes that don't have dynamic vars in the name.

**Comment by geerlingguy** [comment]
So... since this is now happening in dozens of my playbooks (in 2.1.2, didn't happen in 2.1.1 or previously), is the answer that I'll need to add `static: no` to every conditional include? This is also happening with conditionally added roles.
