### ISSUE TITLE
Actions for Jobs and Job Templates

### ISSUE THREAD

**Issue by aixadmin** [ansible/ansible#17138]
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

Jobs and Job Templates
##### ANSIBLE VERSION

```
 3.0.1 
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Under Jobs or Job Templates, the ACTIONS icons are currently on the other side of the webpage than the name of the actual Job or Job Template. This combined with the very faint line shading of alternating lines makes taking an ACTION on the wrong Job quite easy. Please consider making the ACTION closer to the name of the Job or Job Template.
##### STEPS TO REPRODUCE

Having the ACTION closer to the Job or Job Template would allow for easier choosing of the correct Job name in question.

```

```

##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment]
I think you want to send this suggestion to Ansible Tower, this is not the forum for this.

use http://support.ansible.com or email support@ansible.com
