### ISSUE TITLE
django-celery run playbook_executor failed

### ISSUE THREAD

**Issue by wordgod123** [ansible/ansible#17132]
##### ISSUE TYPE

- Bug Report
- Feature Idea
- Documentation Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### STEPS TO REPRODUCE

```

---

- name: test playbook
  hosts: all
  gather_facts: no
  #max_fail_percentage: 0
  #serial: 2
  any_errors_fatal: true
  connection: local
  roles:
    - test
```

##### ACTUAL RESULTS

```
I use django-clelery task to execute ansible, but have this error.

  File "/data/trunck/ansibleapp/tasks.py", line 13, in executeTask
    ansible.run_playbook(playbooks, host)
  File "/data/trunck/ansibleapp/ansbase.py", line 83, in run_playbook
    result = playbookExecutor.run()
  File "/usr/local/python27/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 213, in run
    self._tqm.cleanup()
  File "/usr/local/python27/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 277, in cleanup
    self._cleanup_processes()
  File "/usr/local/python27/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 281, in _cleanup_processes
    self._result_prc.terminate()
  File "/usr/local/python27/lib/python2.7/site-packages/ansible/executor/process/result.py", line 94, in terminate
    super(ResultProcess, self).terminate()
  File "/usr/local/python27/lib/python2.7/multiprocessing/process.py", line 137, in terminate
    self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'
```

**Comment by nitzmahone** [comment]
Without seeing the code you're using to launch the task, not much we can do to help. Take a look at how ansible-playbook does it in https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/playbook.py.

**Comment by wordgod123** [comment]
@nitzmahone 
Thanks for you answer. I have deal the problem. Run the task use -P threads is work for me. The command is: python manage.py celery worker -P threads --loglevel=info

**Comment by targetoyes** [comment]
`python manage.py celery worker -P threads --loglevel=info` solved start problem, but when executing one of the task of django-celery , it warming with `worker: Warm shutdown (MainProcess)` ,and new MainProcess was created,  Number of MainProcess become to be add-one processes.

**Comment by wordgod123** [comment]
@targetoyes Yes, i have this problem too. I think maybe is this reason in task_queue_manager.py:
    def cleanup(self):
        display.debug("RUNNING CLEANUP")
        self.terminate()
        self._final_q.close()
        self._cleanup_processes()

```
def _cleanup_processes(self):
    if self._result_prc:
        self._result_prc.terminate()

        for (worker_prc, rslt_q) in self._workers:
            rslt_q.close()
            if worker_prc and worker_prc.is_alive():
                try:
                    worker_prc.terminate()
                except AttributeError:
                    pass
```

I have use rq become the task queues. This resolve the problem.

**Comment by targetoyes** [comment]
@wordgod123  what is the meaning about rq?

**Comment by wordgod123** [comment]
@targetoyes redis queue

**Comment by targetoyes** [comment]
@wordgod123  you had abandoned the django-celery,and switch to use django-rq?

**Comment by wordgod123** [comment]
@targetoyes yes

**Comment by targetoyes** [comment]
Can rq revoke the command when command is running? if can, I think i should also switch to it.

**Comment by targetoyes** [comment]
rq has not a revoke method,so i have to consider other solution.
