### ISSUE TITLE
Allow execute more than 1 command at the same session

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#17134]
I need to query all server status using one command

```
ansible all -a "uname -a;uptime;free;df -hl"
```

But ansible do not support this.
we can only do like 

```
ansible all -a "sh -c ' uname -a ; uptime; free; df -hl'"
```

can we using sh -c as the default command wrapper. so we can support multiple command execute at the same time.
It wil not affect single command execute.

**Comment by ghost** [comment]
salt-ssh do support multiple command the same time

```
huzhifeng@w ~ $ salt-ssh '*' -r 'uptime;free'
p2:
    ----------
    retcode:
        0
    stderr:
        Warning: Permanently added 'p2.i****.us,199.***.***.***' (ECDSA) to the list of known hosts.
        bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
    stdout:
         03:07:34 up 36 days, 22:41,  0 users,  load average: 0.00, 0.00, 0.00
                     total       used       free     shared    buffers     cached
        Mem:        262144      91804     170340       2628          0      61212
        -/+ buffers/cache:      30592     231552
        Swap:       131072      20420     110652
la:
    ----------
    retcode:
        0
    stderr:
        Warning: Permanently added 'la.is**.us,23.****.****.25' (ECDSA) to the list of known hosts.
        bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
    stdout:
         03:07:34 up 27 days,  4:55,  0 users,  load average: 0.03, 0.01, 0.00
                     total       used       free     shared    buffers     cached
        Mem:        524288     120728     403560       2632          0      90808
        -/+ buffers/cache:      29920     494368
        Swap:       262144      22992     239152

```

**Comment by asdg-asdf** [comment]
ansible all -m  shell -a "uname -a;uptime;free;df -hl"
default modules  is command module
u need use shell module

**Comment by ghost** [comment]
why not put shell module as default. or add alias

```
ansible all -r "uname -a;uptime;free;df -hl"
```

**Comment by sivel** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
