### ISSUE TITLE
ansible-playbook ingores user setting

### ISSUE THREAD

**Issue by ari-s** [ansible/ansible#17171]
for me, ansible-playbook completely ignores remote user setting. ansible respects it.
the username is also set in ~/.ssh/config, commenting that line makes no difference for ansible-playbook
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
arian@jira:ansible$ ansible --version
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

 # defaults
##### OS / ENVIRONMENT

debian testing on both ansible and managed host
##### STEPS TO REPRODUCE

MWE: cat whoami.yml; ansible-playbook whoami.yml -u test

```

---
- name: whoami 1
  hosts: playground.ccczh.ch
  tasks:
    - shell: whoami
      register: whoami1
    - debug: msg={{ whoami1.stdout }}
  remote_user: test
```
##### EXPECTED RESULTS

```
TASK [command] *****************************************************************
changed: [playground.ccczh.ch]

TASK [debug] *******************************************************************
ok: [playground.ccczh.ch] => {
    "msg": "test"
}
```
##### ACTUAL RESULTS

```
TASK [command] *****************************************************************
changed: [playground.ccczh.ch]

TASK [debug] *******************************************************************
ok: [playground.ccczh.ch] => {
    "msg": "root"
}
```
##### ansible

```
$ ansible playground.ccczh.ch -a "whoami" -u test
playground.ccczh.ch | SUCCESS | rc=0 >>
test
```

**Comment by alikins** [comment]
Could you provide output from running with '-vvvv' flags to ansible-playbook? 
That should show the connection info.

The inventory setup for the 'playground.ccczh.ch' host as well.

**Comment by alikins** [comment]
Note remote_user is a config variable that sets a default user name to use if one is not provided elsewhere. So if inventory is setting ansible_remote_user=root, that will be used instead of remote_user.

See https://github.com/ansible/ansible/issues/4688
