### ISSUE TITLE
Make action plugins part of the module

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#17181]
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

action plugins
##### SUMMARY

Something I always wondered about, why aren't action_plugins part of the module, like a method to AnsibleModule that is loaded on the Ansible system. That way, changes to action plugins would go together with changes to the module, and in the same pull request, and in the same release (think core/extras split!).

**Comment by bcoca** [comment]
action plugins get executed 'locally' on the ansible controller, modules are copied and executed on the 'target', action plugins are required to be python, modules are not.

soon we will merge the repos so there won't be an issue with PRs anymore.

**Comment by dagwieers** [comment]
@bcoca Modules could have a part that runs locally and a part that runs remotely. But indeed modules could be in any language.

But core/extras won't be merged, or will they ?

**Comment by bcoca** [comment]
current plan is going back to single repo after 2.2 release

**Comment by dagwieers** [comment]
Alright !
