### ISSUE TITLE
Formatting on Docker Network Module page broken.

### ISSUE THREAD

**Issue by mrbobbytables** [ansible/ansible#17198]
##### ISSUE TYPE
- Documentation Report
##### COMPONENT NAME

[Docker Network Module Page](http://docs.ansible.com/ansible/docker_network_module.html)
##### SUMMARY

Rendering of the table is broken with raw html visible in the comments column of the force parameter.
##### STEPS TO REPRODUCE

Visit the [Docker Network Module Page](http://docs.ansible.com/ansible/docker_network_module.html)

**Comment by chouseknecht** [comment]
@mrbobbytables Thank you for taking the time to open this issue. I'm moving it to the ansible/ansible-modules-core repo where docker_network.py lives. Here's a link to the new issue: https://github.com/ansible/ansible-modules-core/issues/4513

**Comment by mrbobbytables** [comment]
Thanks! Sorry about the mix up there.
