### ISSUE TITLE
option to disable '-n' flag for sudo

### ISSUE THREAD

**Issue by amarao** [ansible/ansible#17216]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ansible/sudo
##### ANSIBLE VERSION

ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o override
##### CONFIGURATION

(no changes) 
##### OS / ENVIRONMENT

Linux with pam_ssh_agent_auth.so
(auth       sufficient pam_ssh_agent_auth.so file=/etc/ssh/sudo_authorized_keys in /etc/pam.d/sudo)
##### SUMMARY

Sudo returns error on ssh-agent based authorization in pam_ssh_agent if '-n' key used. Adding to Ansible some kind of variable to disable '-n' option should help.
##### STEPS TO REPRODUCE
1. Configure sudo on remove machine to use  pam_ssh_agent_auth.so
2. Configure ssh locally to passthrough ssh-agent
3. Try to run any playbook with become=yes.
##### EXPECTED RESULTS

Normal work, athorization for sudo happens via ssh agent.
##### ACTUAL RESULTS

```
<compute4.nlab1> ESTABLISH SSH CONNECTION FOR USER: None
<compute4.nlab1> SSH: ansible.cfg set ssh_args: (-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<compute4.nlab1> SSH: ansible_password/ansible_ssh_pass not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<compute4.nlab1> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<compute4.nlab1> SSH: PlayContext set ssh_common_args: ()
<compute4.nlab1> SSH: PlayContext set ssh_extra_args: (-A)
<compute4.nlab1> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/home/amarao/.ansible/cp/ansible-ssh-%h-%p-%r)
<compute4.nlab1> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -A -o ControlPath=/home/amarao/.ansible/cp/ansible-ssh-%h-%p-%r compute4.nlab1 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-intmcnxfcldvwxybjoswidwzusroltvp; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
fatal: [compute4.nlab1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "setup"}, "module_stderr": "OpenSSH_7.3p1 Ubuntu-1, OpenSSL 1.0.2g-fips  1 Mar 2016\r\ndebug1: Reading configuration data /home/amarao/.ssh/config\r\ndebug1: /home/amarao/.ssh/config line 392: Applying options for *.nlab1\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 1: Deprecated option \"useroaming\"\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 18375\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nsudo: a password is required\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

You can already customize the flags for sudo using `sudo_flags` (default `-H -S -n`) in ansible.cfg or ANSIBLE_SUDO_FLAGS environment variable or the equivalent 'become' versions.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
