### ISSUE TITLE
execute any module returns MODULE FAILURE except raw module

### ISSUE THREAD

**Issue by fallencliff** [ansible/ansible#17237]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

any module
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

remote_tmp     = /tmp/${USER}/ansible
host_key_checking = False
timeout = 30
scp_if_ssh = True
ANSIBLE_KEEP_REMOTE_FILES=1
##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.0 (Maipo)
##### SUMMARY

execute any module returns MODULE FAILURE except raw module
##### STEPS TO REPRODUCE

ansible -i 10.223.25.101, all -m command -a 'uname -a' -u 'admin4A' -k -vvvv  -c paramiko
##### EXPECTED RESULTS

Linux vgopserver1 3.0.13-0.27-default #1 SMP Wed Feb 15 13:33:49 UTC 2012 (d73692b) x86_64 x86_64 x86_64 GNU/Linux
##### ACTUAL RESULTS

Using /etc/ansible/ansible.cfg as config file
SSH password: 
Loaded callback minimal of type stdout, v2.0
<10.223.25.101> ESTABLISH CONNECTION FOR USER: admin4A on PORT 22 TO 10.223.25.101
<10.223.25.101> EXEC /bin/sh -c '( umask 77 && mkdir -p "`echo /tmp/${USER}/ansible/ansible-tmp-1472138013.04-216434237736536`" && echo ansible-tmp-1472138013.04-216434237736536="`echo /tmp/${USER}/ansible/ansible-tmp-1472138013.04-216434237736536`" ) && sleep 0'
<10.223.25.101> PUT /tmp/tmpRXv9pM TO /tmp/admin4A/ansible/ansible-tmp-1472138013.04-216434237736536/command
<10.223.25.101> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /tmp/admin4A/ansible/ansible-tmp-1472138013.04-216434237736536/command && sleep 0'
10.223.25.101 | FAILED | rc=0 >>
MODULE FAILURE

```
ansible -i 10.223.25.101, all -m command -a 'uname -a' -u 'admin4A' -k -vvvv  -c paramiko
```

**Comment by fallencliff** [comment]
this happens on the remote host which is SUSE Linux Enterprise Server 11 and Python 2.6 ;
and i try to run the command script on remote hosts manually with pdb, it returns Segmentation fault on the import even before main();

> admin4A@vgopserver1:~> export PYTHONPATH=/tmp/ansible_6fjxNw/ansible_modlib.zip
> admin4A@vgopserver1:~> /usr/bin/python /tmp/ansible_ChSygL/ansible_module_command.py
> > /tmp/ansible_ChSygL/ansible_module_command.py(254)<module>()
> -> from ansible.module_utils.basic import *
> (Pdb) n
> Segmentation fault
> admin4A@vgopserver1:~>

**Comment by nitzmahone** [comment]
If you run ansible with ANSIBLE_KEEP_REMOTE_FILES=1 envvar set and `-vvv`, you can see the location of the tempfiles we drop and run. Curious if you are able to reproduce this while logged in locally, as it seems the python on your target host has issues if it's segfaulting. Not sure there's anything we can do about that...
