### ISSUE TITLE
Enhancement Request: Provide a spine-leaf group_var resolving mechanism

### ISSUE THREAD

**Issue by odyssey4me** [ansible/ansible#17236]
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

Inventory
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

With a set of groups structured like the following:

```
all
  |--monitoring_all
         |--monitoring_agents
```

When a group_var is set in `monitoring_all` and the same var is set in `monitoring_agents` a deployer may expect that the leaf variable setting will win, but the deployer would be wrong. Ansible resolves the variable alphabetically and `all` comes after `agents`.

As a result, the variable setting will not be what is expected.

Currently we have to design group names in such a way that the leaf groups are always alphabetically resolved later than the parent groups.

It would be more intuitive if the variable merge would be resolved based on the group structure instead of just blindly resolving them alphabetically.
##### STEPS TO REPRODUCE

```
```

##### ACTUAL RESULTS

```

```

**Comment by nitzmahone** [comment]
This is a big enough thing that if you really want to see discussion/action on it, I'd suggest writing a [proposal](https://github.com/ansible/proposals/), and come to one of the IRC [meetings](https://github.com/ansible/community/blob/master/MEETINGS.md) to advocate for it.

**Comment by jctanner** [comment]
Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:

   * #ansible-devel on Freenode
   * https://groups.google.com/forum/#!forum/ansible-devel

Thank you!
