### ISSUE TITLE
pip install ansible fails on trying to find cc for compiling _openssl in CoreOS

### ISSUE THREAD

**Issue by basharov** [ansible/ansible#17242]
I have installed python and pip inside my CoreOS.
Now I run `pip install ansible` and things start rolling, it downloads some libs, writes and copies.

Then it tries to compile _openssl library which, I assume, is used by ansible.

As there are no C compilers in CoreOS, it fails with this error:

> ```
> running egg_info
> writing src/cryptography.egg-info/PKG-INFO
> writing dependency_links to src/cryptography.egg-info/dependency_links.txt
> writing entry points to src/cryptography.egg-info/entry_points.txt
> writing requirements to src/cryptography.egg-info/requires.txt
> writing top-level names to src/cryptography.egg-info/top_level.txt
> warning: manifest_maker: standard file '-c' not found
> 
> reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> no previously-included directories found matching 'docs/_build'
> warning: no previously-included files matching '*' found under directory 'vectors'
> writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
> running build_ext
> generating cffi module 'build/temp.linux-x86_64-2.7/_padding.c'
> creating build/temp.linux-x86_64-2.7
> generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'
> generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
> building '_openssl' extension
> creating build/temp.linux-x86_64-2.7/build
> creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
> cc -O2 -fPIC -Wimplicit -I/home/core/pypy/include -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
> unable to execute 'cc': No such file or directory
> error: command 'cc' failed with exit status 1
> 
> ----------------------------------------
> Command "/home/core/pypy/bin/pypy -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-t8X89n/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-XybUBN-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-t8X89n/cryptography/
> ```

As I see, it's cryptography package. When I try to install it with pip as `pip install cryptography`, it fails with the same error. May be I can use a precompiled cryptography package?

Is there a way to fix this issue?
Thanks!

**Comment by jhawkesworth** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
