### ISSUE TITLE
properly support passlib module in password_hash

### ISSUE THREAD

**Issue by phemmer** [ansible/ansible#17266]
##### ISSUE TYPE
- Feature Idea
- Documentation Report
##### COMPONENT NAME

`password_hash`
##### ANSIBLE VERSION

2.1.1.0-1
##### SUMMARY

The `password_hash` filter has been updated to support the `passlib` python module (as can be seen here: https://github.com/ansible/ansible/blob/v2.1.1.0-1/lib/ansible/plugins/filter/core.py#L279).
However:
1. [The documentation](https://docs.ansible.com/ansible/playbooks_filters.html#hashing-filters) still says it depends on `crypt`.
2. The filter restricts usage to md5, blowfish, sha256, and sha512. The `passlib` module supports a TON more hashing schemes than this. The restriction only made sense when using the `crypt` module. It should not be applied to `passlib`.

**Comment by pgrenaud** [comment]
@bcoca Since you closed #15326 and #21997, you might want to take a look at this. (It's probably fixed too.)

**Comment by onitake** [comment]
According to the code logic around https://github.com/ansible/ansible/blob/6bc3f98eee2b1f1496d35aa0357b924ab0cb7d0f/lib/ansible/plugins/filter/core.py#L289 passlib is always used if available.

crypt is used as a fallback on systems that don't have it.
Unfortunately, the hash type is not checked in this case, which results in incorrect password hashes.
A check similar to the one for macOS should be added, or the filter should depend on passlib for correct operation.
