### ISSUE TITLE
inventory_hostnames lookup doesn't support wildcards in patterns

### ISSUE THREAD

**Issue by jm-welch** [ansible/ansible#17268]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

inventory_hostnames lookup plugin
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

**ansible.cfg**

``` ini
[defaults]
host_key_checking = False
#ask_pass = True
remote_user = root
retry_files_enabled = False
```
##### OS / ENVIRONMENT

CentOS 7
##### SUMMARY

When using wildcards in patterns with the `with_inventory_hostnames` lookup plugin, no results are returned. Using explicit patterns (`all:!web`) works.

There are scenarios where we want to use `with_inventory_hostnames` to iterate over a specific subset of a larger inventory, without always having to create a group for what may be a one-off command.
##### STEPS TO REPRODUCE
1. Create inventory and playbook files as shown below

**inv**

``` ini
[web]
dzcustomer1web1
dzcustomer1svc2
dzcustomer2web1
dzcustomer3web1
[app]
opcustomer1app1
opcustomer2app2
opcustomer3app3
```

**test.yml**

``` yml

---
- hosts: localhost
  tasks:
    - debug:
        var: item
      with_inventory_hostnames: *customer1*
```
1. Run playbook
##### EXPECTED RESULTS

Expected that the wildcard pattern would be supported the same way it is in the `-l` flag.

``` shell
$ ansible-playbook -i inv test.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => (item=dzcustomer1web1) => {
    "item": "dzcustomer1web1"
}
ok: [localhost] => (item=dzcustomer1svc2) => {
    "item": "dzcustomer1svc2"
}
ok: [localhost] => (item=opcustomer1app1) => {
    "item": "opcustomer1app1"
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```
##### ACTUAL RESULTS

``` shell
$ ansible-playbook -i inv test.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

We've tested this with the filter configured multiple ways, all of which fail. Only explicit mentions appear to work as outlined in the [patterns](http://docs.ansible.com/ansible/intro_patterns.html) documentation. These patterns do work when used with `-l`, though.

```
*customer1*
"*customer1*"
*web1
dz*
```

**Comment by Qaad** [comment]
I can confirm the same issue exists in ansible 2.3.1.

**Comment by geerlingguy** [comment]
Confirmed on Ansible 2.4.1 as well.

**Comment by akamac** [comment]
As a workaround one can re-write:

`with_items: "{{ groups['all'] | select('match', pattern) | list }}"`

transforming the pattern to python regex first.

**Comment by jbscare** [comment]
> transforming the pattern to python regex first

You can't do that programmatically, though, can you?

I ask because my use case uses the pattern both in a 'hosts' line and also later in a with_inventory_hostnames:

```yaml
- hosts: control_host:{{ target_hosts }}
  name: Do things to the target hosts, one at a time
  serial: 1
  vars:
    target_host_list: "{{ lookup('inventory_hostnames',target_hosts) }}"

  tasks:

    - debug: msg="This task runs on {{ inventory_hostname }}, which is in {{ target_host_list }} because it matches {{ target_hosts }}"
      when: inventory_hostname in target_host_list

    - debug: msg="This task does stuff on the control host, for each target host"
      delegate_to: control_host

    - debug: msg="This task runs on {{ inventory_hostname }} again"
      when: inventory_hostname in target_host_list
```

I suppose we could pass in two separate patterns, and hope really hard that they end up being identical, but that seems very non-ideal.

**Comment by danihodovic** [comment]
Confirmed in 2.7.1.

**Comment by Vladimir-csp** [comment]
Confirmed in 2.7.9
It also does not support index patterns like `somegroup[0]` or `some_pattern*[2]` which are valid subsets arguments for `ansible` and `ansible-playbook`

**Comment by bcoca** [comment]
no need to 'confirm' since this ticket is open, it assumes the feature was not added
