### ISSUE TITLE
on_no_host_remaining stops playbook too early

### ISSUE THREAD

**Issue by jhoekx** [ansible/ansible#1726]
The on_no_host_remaining early exit sometimes leads to an exit that was too early.

Consider the following case:

```
group1: sys1
group2: sys2, sys3, sys4
```

And a playbook:

```
- hosts: group1
  tasks: ....

- hosts: group2
  tasks: ...

- hosts: group1
  tasks: ...

- hosts: group2
  tasks: ...
```

If sys1 fails in the first play, Ansible will stop after play 3 with:

```
FATAL: no hosts matched or all hosts have already failed -- aborting
```

The only fix I can think of right now is to not stop running the playbook, but check every remaining play if it still has matching hosts (without running callbacks). Acceptable or do you see better solutions?

**Comment by dhozac** [comment]
Really? I think it should bail out on the first play already. Did it fail on the last task of the play?

The idea is that it shouldn't continue with other plays as they may rely on the first play being successful, that is after all the idea with the orchestration features of ansible.

**Comment by jhoekx** [comment]
The first machine failed on action 22, which is in play 3. The others continued until action 73. Many plays later. The next play only had the first machine in it and that's where Ansible failed.

What you're saying about orchestration has never been the case and as far as I know was explicitly designed like that by Michael. It would imply you stop completely at the first failure of _any_ host since you don't know any dependencies between them or between plays.

**Comment by mpdehaan** [comment]
"What you're saying about orchestration has never been the case and as far as I know was explicitly designed like that by Michael."

Not true, not designed that way, and I'm still here :)

The rules are as follows:

(A)   if a play has failed for all hosts, the entire playbook will stop

(B)   if a play has failed for all N hosts out of a serial: N batch, the entire playbook will stop.

Now, what has happened (most likely) is that because you have had a failure on the very LAST play, the abort check does not fire until the next time it comes along to see what hosts to talk to in the group.   As a result, the failure is a bit late.

This is a minor bug, and could be fixed by making that check earlier.

**Comment by jhoekx** [comment]
Ok, these rules make sense. But I suspect you've made them up while looking at the code :-) That's a change in behaviour from version 0.7 to 0.8 and I didn't look at that code since then. It would help to have the expected behaviour documented somewhere.

So you're right, my actual setup was like:

```
group1: sys1
group2: sys2, sys3, sys4
group3: group1, group2
```

`sys1` failed early on in a play that had `hosts: group3`. Ansible stopped when it first encountered a play that included only that system.

I usually limit this playbook to one or two hosts and it was the first time that I tried it with hosts from the two main groups (datacenters). So that means that with --limit it just skips that particular play and in this particular case it fails leading to my confusion. I can probably live with that.

If you want to keep this open for adding it to the docs, fine, otherwise you can close it.

**Comment by dagwieers** [comment]
Personally I think the requested behavior should be configurable. We are using `only_if` now in cases where `group_by` would be better, just because a play on a subset group might stop the complete run and we do not want that at all.

**Comment by dagwieers** [comment]
The behavior I would like to see (optionally) is if _all_ or _all hosts the playbook was limited to_ fail, then stop.

**Comment by mpdehaan** [comment]
A play operating on an empty group should not fail the playbook, period.   A play where it did have hosts and they have had failures in all of that set (or slice, in the case of serial) should fail.

That's what we want.

Let me know if it sounds like I'm talking about something else but I will take patches that result in the above.
