### ISSUE TITLE
Parameterized playbook includes and stdout_lines with_items

### ISSUE THREAD

**Issue by progre55** [ansible/ansible#1727]
In a parametrized include, the following is not working:
- name: Register lines
  local_action: command /usr/bin/env ls -1 /some/dir/files/
  register: myfiles
- include: ./tasks/mytask.yml myfile=${item}
  with_items: ${myfiles.stdout_lines}

it passes in the literal string "${myfiles.stdout_lines}" char by char, like item="$" item="{" item="m" item="y", etc

but the following works:

vars:
myfiles:
- file1
- file2
- include: ./tasks/mytask.yml myfile=${item} 
  with_items: $myfiles

OR
- include: ./tasks/mytask.yml myfile=${item}
  with_items:
  - file1
  - file2

Shouldn't the with_items behavior be the same on all the task types?

**Comment by dhozac** [comment]
No, includes are processed before any hosts have been spoken with. There is just one task list, and it has to be the same across all hosts. Differing includes per hosts is not possible.
