### ISSUE TITLE
shell module behavior is not logical

### ISSUE THREAD

**Issue by akamensky** [ansible/ansible#17298]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

shell module
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
N/A
```
##### OS / ENVIRONMENT

```
N/A
```
##### SUMMARY

When execute command via shell module, the playbook by default fails when the command return code is not 0
##### STEPS TO REPRODUCE

```
  - name: Execute command and register variable
     shell: false
     register: result
  - name: Check variable and do something else
     shell: echo "Previous shell command was non-zero rc"
     when: result.rc != 0
  - name: Check variable and do another thing
     shell: echo "Previous shell command was successful"
     when: result.rc == 0
```
##### EXPECTED RESULTS

All steps are reachable
##### ACTUAL RESULTS

Step 2 will never be reached
##### COMMENT

There are many instances when I (and others) need to just execute the command and do things based on the result. Currently people workaround that with `ignore_errors: true`.

One example (where I stumbled on this) is checking if rpm is installed (yum module has no way to check, it has only option to install/remove something...). Which I do with "rpm -qa | grep $pkg_name". grep if no lines found will return 1. Which fails the playbook.

The above makes current behavior of modules `shell` and `command` pretty illogical.

**Comment by robinro** [comment]
`rc!=0` is a pretty logical criterion to determine when a command failed. Most commands indicate failure using the return code.

If your playbooks handles those cases itself, you can use `ignore_errors: True` or `failed_when: False`. The latter might be more obvious, since it modifies ansible's default criterion for failure of the module. Many people rely on this behavior, so it's very unlikely this will ever be modified.

**Comment by ryansb** [comment]
Raising an error for non-zero return codes is intended behavior. As you mention, `ignore_errors` is a workaround and lets you handle the return code based on your criteria.
