### ISSUE TITLE
"register" expresions

### ISSUE THREAD

**Issue by rektide** [ansible/ansible#1730]
I'd like to be able to run an expression on the results, and store that into register, rather than store the entire result set in results and drilling into it again and again for the same data.

**Comment by mpdehaan** [comment]
This is a confusing bug report for me, how about stopping by the mailing list?

**Comment by rektide** [comment]
I have dropped by on the mailing list. https://groups.google.com/forum/?fromgroups=#!topic/ansible-project/1vU62JSlmSM
