### ISSUE TITLE
Documentation for configuring Windows management is missing 'ntlm'

### ISSUE THREAD

**Issue by MadelineRitchie** [ansible/ansible#17311]
##### ISSUE TYPE

- Documentation Report
##### COMPONENT NAME

https://github.com/ansible/ansible/blob/devel/docsite/rst/intro_windows.rst
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /srv/ansible/repo/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

ansible_user: zz_ansible@contoso.com
ansible_password: '{{ vault_ansible_password }}'
ansible_port: 5986
ansible_winrm_transport: ntlm
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
##### OS / ENVIRONMENT

Mac OS X El Capitan managing Windows Server 2012 R2
##### SUMMARY

There is no mention of the ntlm authentication method in the documentation page linked. As soon as I found a Google Group post explaining ntlm with Ansible and pywinrm 2.0 my life got a lot simpler. https://groups.google.com/forum/#!topic/ansible-project/vEl-mrvFkrY

**Comment by dagwieers** [comment]
This one is fixed with #17851 however the online documentation (still) does not reflect the new changes.

@gundalow @nitzmahone I think this is too important to ignore. Let's get this issue closed ASAP.

**Comment by gundalow** [comment]
@dagwieers is the issue 
A) The docs are wrong
Or
B) The docs are right, though they are not live on docs.ansible.com?

**Comment by dagwieers** [comment]
@gundalow B ! The docs have been improved but users won't see the latest improvements to the documentation.

**Comment by gundalow** [comment]
Docs have been made live

**Comment by gohelh-adsk** [comment]
Although this issue is closed as fixed, http://docs.ansible.com/ansible/intro_windows.html doesn't have much info about NTLM; needs to be included on intro_windows.html page as well?

**Comment by dagwieers** [comment]
@gohelh-adsk Weird, this was part of PR #17851, see https://github.com/ansible/ansible/pull/17851/files

**Comment by gohelh-adsk** [comment]
@dagwieers Yes, I can see your changes in the PR so it looks like they were merged in at that point. Looking at the file history, it was moved and the earliest version in the current location doesn't have your changes.  Not sure what happened between your change and commit 57f8b791d672ec520036973db235071656f45077
