### ISSUE TITLE
gather_timeout is used by "ansible-playbook" but not by "ansible"

### ISSUE THREAD

**Issue by mathieumd** [ansible/ansible#17316]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

Configuration `gather_timeout` in `ansible.cfg`
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 1c33b5a9f0) last updated 2016/08/30 12:20:57 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 5310bab12f) last updated 2016/08/30 12:21:13 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 2ef4a34eee) last updated 2016/08/30 12:21:14 (GMT +200)
  config file = /home/.../ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

`gather_timeout = 30` in `ansible.cfg`
##### OS / ENVIRONMENT

From Debian Stretch (testing) to Debian Jessie (8.5)
##### SUMMARY

I was caught by the bug #10779 and while trying to increase the timeout through `gather_timeout`, I noticed it worked only for `ansible-playbook`, not `ansible`.
##### STEPS TO REPRODUCE

Although the `gather_timeout` is set to 30, this command always fails after 13 sec (ie. 3s for sudo password input, plus the 10s default gather_timeout):

```
ansible -i '192.168.1.123,' -u testuser all --sudo --ask-sudo-pass -m setup
SUDO password:
192.168.1.123 | FAILED! => {
    "changed": false,
    "cmd": "/bin/lsblk --list --noheadings --paths --output NAME,UUID",
    "failed": true,
    "msg": "Traceback (most recent call last):\n  File \"/tmp/ansible_tYiFjl/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2203, in run_command\n    rfd, wfd, efd = selec
t.select(rpipes, [], rpipes, 1)\n  File \"/tmp/ansible_tYiFjl/ansible_modlib.zip/ansible/module_utils/facts.py\", line 116, in _handle_timeout\n    raise TimeoutError(error_message)
\nTimeoutError: Timer expired\n",
    "rc": 257
}
```

The `sudo lsblk` command duration itself is about 14s:

```
time sudo /bin/lsblk --list --noheadings --paths --output NAME,UUID
/dev/fd0
/dev/sda
/dev/sda1  bf79e994-5016-80d6-405c-d18d01a59b1d
/dev/md0
/dev/md0p1 eaee12dd-0291-4980-9c9a-9309da3b1019
/dev/md0p2
/dev/md0p5 59ec8bb7-a77d-4bee-b555-8e75364c99ec
/dev/md0p6 7628ee5b-face-4c96-868f-9dc52f230c2c
/dev/sdb
/dev/sdb1  bf79e994-5016-80d6-405c-d18d01a59b1d
/dev/md0
/dev/md0p1 eaee12dd-0291-4980-9c9a-9309da3b1019
/dev/md0p2
/dev/md0p5 59ec8bb7-a77d-4bee-b555-8e75364c99ec
/dev/md0p6 7628ee5b-face-4c96-868f-9dc52f230c2c
/dev/sr0

real    0m13.139s
user    0m0.004s
sys     0m0.012s
```

While the `ansible-playbook` is OK:

```
ansible-playbook playbooks/Servers.yml -l 192.168.1.123 --sudo --ask-sudo-pass
...
PLAY [Servers] *****************************************************************

TASK [setup] *******************************************************************
ok: [192.168.1.123]
...
```

##### EXPECTED RESULTS

Both commands `ansible` and `ansible-playbook` should have read `ansible.cfg` configuration in the same way.
##### ACTUAL RESULTS

Only `ansible-playbook` seems to have read `ansible.cfg`'s `gather_timeout` configuration.

**Comment by agaffney** [comment]
It looks like `gather_timeout` is only passed for the implicit fact gathering step in a playbook, not for any random invocation of the `setup` module. This explains why it doesn't work when doing `ansible ... -m setup`.

You can _probably_ do:

```
ansible ... -m setup -a 'gather_timeout=30'
```

**Comment by bcoca** [comment]
as @agaffney mentioned, this is for the 'implicit' gathering, for the explicit one you should pass it in yourself.

**Comment by mathieumd** [comment]
Thank you @agaffney.

@bcoca: It doesn't make sense! For what reason would one want to explicitly configure a gathering timeout in `ansible.cfg` and still have to set it again as an argument for ad-hoc calls to `ansible`? It's a failure in terms of usability.

The command line argument should indeed have priority over configuration file, but still the configuration file should always be read. Or there could be two configuration files: `ansible.cfg` and `ansible-playbook.cfg`?

**Comment by bcoca** [comment]
@mathieumd I see how it can be confusing, but the ansible.cfg file is read by both `ansible` and `ansible-playbook`. 

The issue is that you are expecting a configuration setting for an 'implicit command that ansible-playbook constructs' to be applied to an 'explicit command you constructed'.

Inside a playbook, if you invoke `- setup:`, you would see the same behavior as in your adhoc usage. 
The `ansible` adhoc command does not do fact gathering implicitly, that is why this setting does not apply to it. The same way that the `gathering` setting (which regulates when automatic gathering happens) is also ignored.

**Comment by gen2saurus** [comment]
@bcoca `- setup` is called in playbook implicitly:

```
PLAY [apply configuration to all nodes] ****************************************
TASK [setup] *******************************************************************
```
but neither `gather_subset` nor `gather_timeout` is read from the configuration file! (see #21261 for details).
What we do wrong?
