### ISSUE TITLE
ansible command ignore `ansible_connection` variable, sets it always to smart

### ISSUE THREAD

**Issue by xsteadfastx** [ansible/ansible#17343]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

The host is a ubuntu xenial and i try to access a windows 10 box.
##### SUMMARY

I discovered that in the latest ansible version  i cant use the ansible command itself for accessing a windows box. it always uses the connection type `smart` instead of the configurated `winrm` type. so `ansible windows -m win_ping` returns a 

```
mywindowsbox | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh.", 
    "unreachable": true
}

```

the `group_vars/windows.yml` looks like this:

```
ansible_user: adminuser
ansible_password: adminpass
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
```

if i use ping in a playbook it works

```

---
- hosts: mywindowsbox

  tasks:

    - name: ping
      win_ping:
```

```
PLAY [mywindowsbox] ******************************************

TASK [setup] *******************************************************************
ok: [mywindowsbox]

TASK [ping] ********************************************************************
ok: [mywindowsbox]

PLAY RECAP *********************************************************************
mywindowsbox : ok=2    changed=0    unreachable=0    failed=0 
```

i checked the var with `
ansible mywindowsbox -m 'debug' -a 'var=ansible_connection' --ask-vault-pass -vvv`:

```
tsmp2014060035.tsm-office.site | SUCCESS => {
    "ansible_connection": "smart"
}
```

under ansible 2.1.0.0:

```
tsmp2014060035.tsm-office.site | SUCCESS => {
    "ansible_connection": "winrm"
}
```
##### STEPS TO REPRODUCE

```
ansible windows -m win_ping
```
##### EXPECTED RESULTS

ran with ansible 2.1.0.0

```
mywindowsbox | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}

```
##### ACTUAL RESULTS

```
<mywindowsbox> ESTABLISH SSH CONNECTION FOR USER: None
<mywindowsbox> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/mpreuss/.ansible/cp/ansible-ssh-%h-%p-%r mywindowsbox '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1472719235.41-120861888238916 `" && echo ansible-tmp-1472719235.41-120861888238916="` echo $HOME/.ansible/tmp/ansible-tmp-1472719235.41-120861888238916 `" ) && sleep 0'"'"''
mywindowsbox | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh.", 
    "unreachable": true
}

```

**Comment by mattclay** [comment]
@xsteadfastx I'm unable to reproduce this on 2.1.0.0, 2.1.1.0 or devel with the provided instructions. Can you provide your `ansible.cfg` file? Also, how did you install Ansible?

**Comment by xsteadfastx** [comment]
@mattclay i dont have a ansible.cfg. i installed ansible through pipsi and the normal pypi way. i can reproduce it on two different boxes.  
right now i tried it again... same setup.... with 2.1.0.0 it uses winrm.... upgrading to 2.1.1.0 and the same playbooks want to connect through ssh.

**Comment by xsteadfastx** [comment]
Here is the output:

```
$:~/playbooks$ ansible --version
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides
$:~/playbooks$ ansible windows -m 'debug' -a 'var=ansible_user'
ERROR! Decryption failed
$:~/playbooks$ ansible windows -m 'debug' -a 'var=ansible_user' --ask-vault-pass
Vault password: 
$ | SUCCESS => {
    "ansible_user": "myadministrator"

$:~/playbooks$ pipsi upgrade ansible
Collecting ansible
Requirement already up-to-date: PyYAML in /home/myuser/.local/venvs/ansible/lib/python2.7/site-packages (from ansible)
Requirement already up-to-date: setuptools in /home/myuser/.local/venvs/ansible/lib/python2.7/site-packages (from ansible)
Requirement already up-to-date: jinja2 in /home/myuser/.local/venvs/ansible/lib/python2.7/site-packages (from ansible)
Requirement already up-to-date: paramiko in /home/myuser/.local/venvs/ansible/lib/python2.7/site-packages (from ansible)
Requirement already up-to-date: pycrypto>=2.6 in /home/myuser/.local/venvs/ansible/lib/python2.7/site-packages (from ansible)
Requirement already up-to-date: MarkupSafe in /home/myuser/.local/venvs/ansible/lib/python2.7/site-packages (from jinja2->ansible)
Requirement already up-to-date: pyasn1>=0.1.7 in /home/myuser/.local/venvs/ansible/lib/python2.7/site-packages (from paramiko->ansible)
Requirement already up-to-date: cryptography>=1.1 in /home/myuser/.local/venvs/ansible/lib/python2.7/site-packages (from paramiko->ansible)
Requirement already up-to-date: ipaddress in /home/myuser/.local/venvs/ansible/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible)
Requirement already up-to-date: six>=1.4.1 in /home/myuser/.local/venvs/ansible/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible)
Requirement already up-to-date: enum34 in /home/myuser/.local/venvs/ansible/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible)
Requirement already up-to-date: idna>=2.0 in /home/myuser/.local/venvs/ansible/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible)
Requirement already up-to-date: cffi>=1.4.1 in /home/myuser/.local/venvs/ansible/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible)
Requirement already up-to-date: pycparser in /home/myuser/.local/venvs/ansible/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography>=1.1->paramiko->ansible)
Installing collected packages: ansible
  Found existing installation: ansible 2.1.0.0
    Uninstalling ansible-2.1.0.0:
      Successfully uninstalled ansible-2.1.0.0
Successfully installed ansible-2.1.1.0
$:~/playbooks$ ansible windows -m 'debug' -a 'var=ansible_user' --ask-vault-pass
Vault password: 
windowsbox | SUCCESS => {
    "ansible_user": "VARIABLE IS NOT DEFINED!"
}
```

**Comment by mattclay** [comment]
I was finally able to reproduce this using both 2.1.1.0 and devel. The piece of information missing was that the group_vars directory needs to be in the same directory as the playbook, but not the same directory where inventory is located.

**Comment by mattclay** [comment]
Commit 7287effb5ce241ce645d61e55e981edc73fa382a is responsible for this regression.

**Comment by mattclay** [comment]
The PR for that commit is #13957.

**Comment by mattclay** [comment]
The change in behavior from PR #13957 is that group_vars is no longer found in the current working directory, only where inventory and the playbook reside: https://github.com/ansible/ansible/pull/13957#issuecomment-227885751

Searching the current working directory was introduced by mistake: https://github.com/ansible/ansible/pull/13957#issuecomment-227891150

**Comment by mattclay** [comment]
@xsteadfastx: Can you confirm that having your group_vars in the directory where inventory or your playbook resides resolves the issue for you?

**Comment by mattclay** [comment]
Also, note that having group_vars in the same directory as your playbook only works when running that playbook. For ad-hoc commands with `ansible` you'll need to have group_vars where your inventory is.

**Comment by xsteadfastx** [comment]
ok it works now. i copied the inventory hosts file in the playbook directory and it worked. but it doesnt make much sense to me. /etc/ansible/hosts is the default, right? but group_vars gets ignored if they are not in the same directory as the hosts file? i will store now all my inventory now only in the directory my playbooks are in. i sometimes only want to check with the ping module which servers are running right now. ok but anyway... thanks alot for that information and i now know what i have to do :) :+1: 

and thanks for the response... it helped me alot.

**Comment by mattclay** [comment]
@xsteadfastx If you keep `group_vars` in the same directory as your inventory file, it will work for both playbooks and ad-hoc commands. So if you're using the default inventory in `/etc/ansible/hosts` you can use `/etc/ansible/group_vars`.

**Comment by xsteadfastx** [comment]
@mattclay ok... thats good to know :) should i close this now?
