### ISSUE TITLE
Python 3.5.2 vs Ansible 2.1.1.0

### ISSUE THREAD

**Issue by dakky** [ansible/ansible#17347]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ansible-playbook
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /Users/dakky/ansible-cfg-mgmt/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

[defaults]
hostfile            = ~/ansible-cfg-mgmt/hosts
roles_path          = ~/ansible-cfg-mgmt/roles
vault_password_file = ~/.ansible.vault
remote_user         = ansible
##### OS / ENVIRONMENT

Managements Host: OSX 10.11.6 python installed via pyenv

```
python --version
Python 3.5.2
```
##### SUMMARY

Playbook run fails with:

```
Using /Users/dakky/ansible-cfg-mgmt/ansible.cfg as config file
ERROR! Unexpected Exception: name 'unicode' is not defined
the full traceback was:

Traceback (most recent call last):
  File "/Users/dakky/.pyenv/versions/3.5.2/bin/ansible-playbook", line 92, in <module>
    exit_code = cli.run()
  File "/Users/dakky/.pyenv/versions/3.5.2/lib/python3.5/site-packages/ansible/cli/playbook.py", line 132, in run
    inventory = Inventory(loader=loader, variable_manager=variable_manager, host_list=self.options.inventory)
  File "/Users/dakky/.pyenv/versions/3.5.2/lib/python3.5/site-packages/ansible/inventory/__init__.py", line 76, in __init__
    self._host_vars_files = self._find_host_vars_files(self._basedir)
  File "/Users/dakky/.pyenv/versions/3.5.2/lib/python3.5/site-packages/ansible/inventory/__init__.py", line 746, in _find_host_vars_files
    found_vars = set(os.listdir(unicode(path)))
NameError: name 'unicode' is not defined
```
##### STEPS TO REPRODUCE

pyenv install 3.5.2
pip install ansible
ansible-playbook server.yml -b

**Comment by nitzmahone** [comment]
Ansible is not supported on python3 yet- work is ongoing. Current 2.2 devel is just barely beginning to "breathe" on py3, but it will be awhile before you'd want to use it for real stuff.

**Comment by gadelkareem** [comment]
I am getting this error on ansible 2.2.1.0 with the s3 module
