### ISSUE TITLE
Templates do not allow range keyword

### ISSUE THREAD

**Issue by arunthampi** [ansible/ansible#1734]
I just upgraded to ansible version 0.9 and my playbook fails when a template encounters such a code block:

```
{% for i in range(244,254) %}

{% endfor %}
```

The jinja2 docs seem to indicate this is valid syntax and I re-installed the latest version of jinja2 just to be sure but the problem persists.

The error I get is:

`fatal: [host] => {'msg': "'range' is undefined", 'failed': True}`

**Comment by mpdehaan** [comment]
There are a lot of global python functions not surfaced, fixes how to solve this generically would be welcome.

**Comment by dhozac** [comment]
The default Jinja2 globals are now available.

**Comment by mpdehaan** [comment]
nice
