### ISSUE TITLE
Openstack dynamic inventory error running task ServerList

### ISSUE THREAD

**Issue by RuBiCK** [ansible/ansible#17344]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

openstack dynamic inventory
https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory/openstack.py
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

same openstack OS ENV variables than `/etc/openstack/clouds.yaml`
Please, note my openstack user doesn't have admin access.
##### SUMMARY

when I execute Ansible dynamic Openstack inventory `openstack.py  --list --debug`, it runs a lot of tasks with success but after a long time it returns an error executing "ServerList" task.
##### STEPS TO REPRODUCE

Create `/etc/openstack/clouds.yaml`  (see https://gist.github.com/RuBiCK/8fecadb470e02e63a41104d265c72ac3 )with the authentication parameters for your openstack.
Excute dynamic inventory trying get all instantes or trying to get information about only one instance.
`openstack.py  --list --debug` or `openstack.py  --host dns01 --debug`

```
[...]
Manager envvars:BOAE running task FlavorGetExtraSpecs
Manager envvars:BOAE ran task FlavorGetExtraSpecs in 0.0171229839325s
Manager envvars:BOAE running task ServerListSecurityGroups
Manager envvars:BOAE ran task ServerListSecurityGroups in 0.0598499774933s
Manager envvars:BOAE running task VolumeList
Manager envvars:BOAE ran task VolumeList in 0.287488937378s
Manager BOAE: running task ServerList
Couldn't construct compute object
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/shade/openstackcloud.py", line 298, in _get_client
    **kwargs)
  File "/usr/lib/python2.7/site-packages/os_client_config/cloud_config.py", line 304, in get_legacy_client
    endpoint = self.get_session_endpoint(service_key)
  File "/usr/lib/python2.7/site-packages/os_client_config/cloud_config.py", line 253, in get_session_endpoint
    region_name=self.region)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 765, in get_endpoint
    return auth.get_endpoint(self, **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 212, in get_endpoint
    service_catalog = self.get_access(session).service_catalog
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 136, in get_access
    self.auth_ref = self.get_auth_ref(session)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/generic/base.py", line 181, in get_auth_ref
    return self._plugin.get_auth_ref(session, **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/v2.py", line 65, in get_auth_ref
    authenticated=False, log=False)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 675, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/lib/python2.7/site-packages/positional/__init__.py", line 94, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 570, in request
    raise exceptions.from_response(resp, method, url)
Unauthorized: The request you have made requires authentication. (HTTP 401)
Manager BOAE: ran task ServerList in 0.0429539680481s
Error fetching server list on BOAE::

```

For full log, please, see the following gist but it not usefull because it contains +8K lines about running taks and ran task.
https://gist.github.com/RuBiCK/1f70ebac2f2905a3582a21c40240253b
##### EXPECTED RESULTS

The expected results is get the output of the dynamic openstack inventory without errors.
Also, when I try to get information for only one instance, it seems that it goes getting information for every instance in openstack and when you have a lot of instances it will take a lot of time.
##### ACTUAL RESULTS

I get the described error above

I tried to find what function is calling ServerList in order to see if it is trying to search in other tenants I don't have access but I could find it.

**Comment by RuBiCK** [comment]
Trying the same with admin credentials works fine.
It is supposed that a normal user with permissions for one tenant should get all the information within the tenant.
I couldn't find the specific  code that generate this error to compare why normal user can't get the information

**Comment by emonty** [comment]
Oh - sorry for the delay.

This should definitely work for non-admin users. Could you do me a couple of favors to help track it down (thanks for the gist):
- Can you paste a copy of your clouds.yaml with the password field redacted and also the output of `env | grep OS_` (I know you said they're the same, but I'd like to double-check for sanity
- Also - the versions of shade and os-client-config that are installed

## Sorry again for the delay in responding.

**Comment by emonty** [comment]
WOW. that sorry was super bold without me intending it to be. yay markdown

**Comment by RuBiCK** [comment]
Thanks for your help emonty!

I'm not able to reproduce the issue again. I think it was related to some issue with clouds.yaml while I also had declared env variables.

Give me a couple of days to check further ;)

**Comment by RuBiCK** [comment]
I confirm the issue was due to my mistake with project_name in clouds.yaml, sorry for that.

I have checked the following:
- If I use clouds.yaml OR env vars and I define wrong tenant/project name, I get an auth error at the beginning. This is the expected behaviour.
- if I use both clouds.yaml AND env vars:
  - defining wrong OS_TENANT_NAME and right clouds.yaml -> works fine
  - defining wrong project_name in clouds.yaml and right  clouds.yaml it makes a lot of tasks and ends with the error reported-> unexpected behaviour. 

As the main error was caused due to my fault you can close this issue unless you want to investigate further this unexpected behaviour. I mean running a lot of tasks ending  with an auth error.
