### ISSUE TITLE
hosts file ranges fail if hostname starts with range

### ISSUE THREAD

**Issue by arturaz** [ansible/ansible#17342]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

hosts file
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

None
##### OS / ENVIRONMENT

N/A
##### SUMMARY

If you have hosts in following pattern: `1.foo.bar.com, 2.foo.bar.com, 3.foo.bar.com`, it is a syntax error to write `[1:3].foo.bar.com` in hosts file.
##### STEPS TO REPRODUCE

```
$ mkdir test
$ cd test
$ echo "[some_group]
[1:3].foo.bar.com" > hosts
$ ansible -i hosts some_group
```
##### EXPECTED RESULTS

Evaluating hosts properly.
##### ACTUAL RESULTS

```
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/home/ubuntu/work/test/hosts': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

[some_group]
[1:3].foo.bar.com
  ^ here

hosts:2: Invalid section entry: '[1:3].foo.bar.com'. Please make sure that there are no spacesin the section entry, and that there are no other invalid characters
```

**Comment by Shaps** [comment]
Hi @arturaz, 

I don't think this is a bug. In ini-like inventory files, lines starting with `[` are intended to be groups, that is why you are getting the error `Invalid section...`. 

If you want to use this type of syntax, you should use YAML host files.

**Comment by arturaz** [comment]
YAML host files exist? Somehow I missed it. Is it in the docs?

**Comment by Shaps** [comment]
I'm not sure if it's in the docs, and I believe it's a fairly new feature. You can find an example here: https://github.com/ansible/ansible/blob/devel/examples/hosts.yaml

**Comment by arturaz** [comment]
I guess then it's a documentation instead of implementation bug :)

**Comment by bcoca** [comment]
Since this is an incompatibility inherit to the ini format and we have a workaround in the YAML format, I'm going to close this issue.

More examples of using the YAML hosts file will be added to the docs.
