### ISSUE TITLE
How to copy from a remote Unix share to a Windows system

### ISSUE THREAD

**Issue by lokly** [ansible/ansible#17366]
It seems that currently win_copy isn't able to be used with "delegate_to". 
Also synchronize could not be used with Windows.  

Can you please add this feature, that the module win_copy is able to used with the delegate_to feature? 

Or how to copy from a remote Unix to a Windows System?

Thanks in advanced.

**Comment by jhawkesworth** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by jhawkesworth** [comment]
Personally I install nginx on the remote unix system, and then use win_get_url to fetch it.  It operates faster than win_copy and can handle larger files.

**Comment by lokly** [comment]
Very good idea, thank you!
