### ISSUE TITLE
Behavior change in parent-child group variable handling

### ISSUE THREAD

**Issue by muratdx** [ansible/ansible#17361]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible-playbook 2.1.2.0
  config file =
  configured module search path = Default w/o overrides
```

NOTE: This is the RC2 release that was published this week.
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

CentOS Linux release 7.2.1511 (Core)
##### SUMMARY

In Ansible 2.x, a group variable defined in the inventory now gets overridden by a variable defined in the group_vars file for that group's parent.

The behavior differs from 1.9.x (as demonstrated below), which ends up using the variable defined in the inventory.

This new behavior was observed in all of the 2.x releases, including the latest 2.1.2-RC2.  I'm not sure if this change is actually a bug or a feature...
##### STEPS TO REPRODUCE

Playbook ("test.yml"):

```

---
- hosts: group1
  gather_facts: false
  tasks:
    - debug: var=var1
```

Inventory ("test-inventory"):

```
[group1]
192.168.1.1

[group1:vars]
var1=100

[parent:children]
group1
```

Group Vars file "(group_vars/parent"):

```

---
var1: 999
```

Playbook command:

```
ansible-playbook -vv -i test-inventory test.yml
```

##### EXPECTED RESULTS

Previous behavior (1.9.x):

```
PLAY [group1] *****************************************************************

TASK: [debug var=var1] ********************************************************
ok: [192.168.1.1] => {
    "var": {
        "var1": "100"
    }
}

PLAY RECAP ********************************************************************
192.168.1.1                : ok=1    changed=0    unreachable=0    failed=0
```
##### ACTUAL RESULTS

2.x behavior:

```
No config file found; using defaults

PLAYBOOK: test.yml *************************************************************
1 plays in ./test.yml

PLAY [group1] ******************************************************************

TASK [debug] *******************************************************************
task path: /tmp/ansible-test-3/test.yml:7
ok: [192.168.1.1] => {
    "var1": 999
}

PLAY RECAP *********************************************************************
192.168.1.1                : ok=1    changed=0    unreachable=0    failed=0

```

**Comment by muratdx** [comment]
Still seeing this issue in 2.1.2 RC3. It is also present in the devel git branch.

**Comment by jctanner** [comment]
This is a documented change ...

http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

```
    role defaults [1]
    inventory vars [2]
    inventory group_vars
    inventory host_vars
    playbook group_vars
    playbook host_vars
    host facts
    play vars
    play vars_prompt
    play vars_files
    registered vars
    set_facts
    role and include vars
    block vars (only for tasks in block)
    task vars (only for the task)
    extra vars (always win precedence)
```

EDIT: I was too hasty in my assessment.

**Comment by jctanner** [comment]
I think this may be an issue with the ini parser not associating children group vars to their parent ...

```
 [jtanner@fedmac AP-17361]$ ./test.sh
 24302 1474296470.25338: starting run
No config file found; using defaults
 24302 1474296470.39251: Loading CacheModule 'memory' from /home/jtanner/workspace/issues/AP-17361/ansible/lib/ansible/plugins/cache/memory.py
 24302 1474296470.39514: SETVAR: var1 to 100
--Return--
> /home/jtanner/workspace/issues/AP-17361/ansible/lib/ansible/inventory/ini.py(64)__init__()->None
-> import epdb; epdb.st()
(Epdb) pp self.groups['parent'].get_vars()
{}
(Epdb) pp self.groups['group1'].get_vars()
{u'var1': 100}
(Epdb)
```

**Comment by bcoca** [comment]
children where meant to inherit from parent, not the other way around

So hosts in group1 should get vars defined in parent, but hosts not in group1 and in parent should not get vars defined in group1.

The problem here seems to be that the group1 var is NOT overriding the parent var.

**Comment by jctanner** [comment]
I've done some more testing and scripting to better understand the order of precedence between the ini file and group_vars files.

In terms of exact ordering, here's the list 

```
#    13. pb_group_vars_file_child     (group_vars/child)
#    14. pb_group_vars_file_parent  (group_vars/parent)
#    15. ini_child                                (hosts file child:vars)
#    16. ini_parent                             (hosts file parent:vars)
```

In general with 2.x, variables found in the group_vars directory override variables in the ini. So if you define a parent group_var file, it will override anything in the ini ... as you have noted. However, if you also define a child group var file, that will override the parent group var file.

The order is expected so we won't be changing it. You can do one of two things:
1. Do not create group_vars/parent
2. Create group_var/child to override group_vars/parent

**Comment by muratdx** [comment]
This seems a bit confusing and inconsistent. Variables defined in group_vars/all can still be easily overridden in the ini. Isn't "all" considered a parent group of everything?

**Comment by coppit** [comment]
Full disclosure: I work with muratdx.

> In general with 2.x, variables found in the group_vars directory override variables in the ini.

I find this nonintuitive. I think of the inventory as "data" to be consumed by the playbooks. I think of group_vars as "code" containing defaults. i.e. It seems more intuitive to me if precedence was group_vars -> ini -> --extra-vars

We ship our group_vars files along with our playbooks, roles, modules, etc. as the "tool", and our clients write inventories to use with the tool. Should we instead consider group_vars files to be data, ship them separately, and ask clients to manage those along with their inventories?

**Comment by GoodHaHa** [comment]
@bcoca @jctanner 
I remember that in ansible 1.X  invertory file vars has high precedence than group_vars/parent.
But in ansible 2.X , why change its precedence ?
