### ISSUE TITLE
Add run_cmd() to lib/ansible/module_common.py

### ISSUE THREAD

**Issue by sfromm** [ansible/ansible#1738]
Several modules have some variant of _run(), run(), or execute_command() that they invoke to call subprocess.Popen.  I think it would be nice to provide some consistency across modules by providing a single run_cmd().  Part of this would require updating existing modules to use this new method.  Thoughts?

**Comment by mpdehaan** [comment]
agree, would save a fair amount of code.

**Comment by jpmens** [comment]
Aye.

**Comment by sfromm** [comment]
A rough stab at what the method would look like:

```
def run_cmd(args, executable, use_shell, fail_on_non_zero):
    ...
    return rc, stdout, stderr
```

If fail_on_non_zero is True, that would call fail_json if rc is non-zero.  I think the rest is self-explanatory.  

If others think it would be helpful, I can also add the time elements (start, end, and delta) to what is returned.

**Comment by jpmens** [comment]
Any chance of having access to $ansible_python_interpreter (and the others) at that point? I'm thinking launching, say, a Python program with a non-standard path to Python. No idea if it's possible here, but it would be nice to have.

**Comment by sfromm** [comment]
Commits 3005315 and 3fb21a5 close this.
