### ISSUE TITLE
unhelpful error message when remote host doesn't support sftp

### ISSUE THREAD

**Issue by maweki** [ansible/ansible#17384]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Managing DietPi with Fedora
##### SUMMARY

`ansible all -a uptime` doesn't work because ansible tries to sftp to the target server which is running `dropbear` which doesn't support sftp. The error message is `UNREACHABLE!`
##### STEPS TO REPRODUCE

Install DietPi on a remote machine or install `dropbear` as the ssh server. Use the default ansible settings to run the `uptime` module or any other module. Get the `UNREACHABLE!`
##### EXPECTED RESULTS

A helpful error message could explain the situation, because the host is not `UNREACHABLE!` but it didn't support `sftp`. `ssh` worked fine.
##### ACTUAL RESULTS

Ansible successfully `ssh`s into the remote machine and executes something. Then it wants to `sftp` into the remote machine and this fails with the unhelpful message `192.168.1.201 | UNREACHABLE!`, which is not true.

```
ansible all -vvvvv -a null
Using /etc/ansible/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<192.168.1.201> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.1.201> SSH: ansible.cfg set ssh_args: (-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<192.168.1.201> SSH: ansible_password/ansible_ssh_pass not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<192.168.1.201> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User=root)
<192.168.1.201> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<192.168.1.201> SSH: PlayContext set ssh_common_args: ()
<192.168.1.201> SSH: PlayContext set ssh_extra_args: ()
<192.168.1.201> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/home/maweki/.ansible/cp/ansible-ssh-%C)
<192.168.1.201> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/maweki/.ansible/cp/ansible-ssh-%C 192.168.1.201 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1472980827.43-260367787861535 `" && echo ansible-tmp-1472980827.43-260367787861535="` echo $HOME/.ansible/tmp/ansible-tmp-1472980827.43-260367787861535 `" ) && sleep 0'"'"''
<192.168.1.201> PUT /tmp/tmp8Qrb2Q TO /root/.ansible/tmp/ansible-tmp-1472980827.43-260367787861535/command
<192.168.1.201> SSH: ansible.cfg set ssh_args: (-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<192.168.1.201> SSH: ansible_password/ansible_ssh_pass not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<192.168.1.201> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User=root)
<192.168.1.201> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<192.168.1.201> SSH: PlayContext set ssh_common_args: ()
<192.168.1.201> SSH: PlayContext set sftp_extra_args: ()
<192.168.1.201> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/home/maweki/.ansible/cp/ansible-ssh-%C)
<192.168.1.201> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/maweki/.ansible/cp/ansible-ssh-%C '[192.168.1.201]'
192.168.1.201 | UNREACHABLE! => {
    "changed": false, 
    "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", 
    "unreachable": true
}
```

**Comment by mscherer** [comment]
Does the option scp_if_ssh help for that ?

I guess we could improve the message, what about:

```
SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh, and support sftp (or use scp_if_ssh configuration). 
```

**Comment by maweki** [comment]
> Does the option scp_if_ssh help for that ?

Well, it wasn't `UNREACHABLE!` then. First it was `lost connection` because the default `dietpi` installation doesn't come with `ssh` or `scp` clients. After I installed that, I got `MODULE FAILURE`, because the default `dietpi` installation doesn't come with `python`. But after that it worked fine. Do you think I should file those as well? In both cases the failure was neither graceful nor had a helpful error message.

> data could not be sent to the remote host. Make sure this host can be reached over ssh, and support sftp (or use scp_if_ssh configuration).

Hinting at the necessary support for `sftp` would be nice, I think (at least if `ssh` itself works). If ssh didn't work, than `UNREACHABLE!` is fine.

For me it was not immediately obvious that this is a dependency on the client side (it is hinted at in the Getting Started guide but in a matter that is easy to overlook).

**Comment by mscherer** [comment]
So, I got lost exactly on the issue, once you did enable scp_if_ssh, then the error message became "lost connection", because this requires scp on the remote side, but the error message was also not clear ?

And then, module_failure message didn't hint at missing python remotely ? I think this could be improved, so yes, fill new issues.

**Comment by maweki** [comment]
Yeah. Now that I fixed everything, this is what happened:
- Cause: no `sftp` support on the remote side / Error message: `UNREACHABLE!` / Fix: enable `scp_if_ssh`
- Cause: no `scp` executable on the remote side / Error message: `lost connection` / Fix: install `ssh-client` package
- Cause: no `python` executable on the remote side / Error message: `MODULE FAILURE` / Fix: install `python` package

I'll file bugs for the other two as well

**Comment by alikins** [comment]
What does the openssh cli do when you attempt to sftp to a host that doesn't support ftp like dropbear?
(ie, what does returncode/stdout/stderr look like).

If I just disable sftp via openssh sshd_config, the only info I see on a failed sftp is:

```
Couldn't read packet: Connection reset by peer
```

**Comment by bcoca** [comment]
We've updated the ssh transfer to be 'smart' and try scp/sftp and even dd over a socket, this should take care of the issue, feel free to reopen if you find that the fix does not meat your needs.
