### ISSUE TITLE
Network no_log not honoured when using provider

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#17392]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

All Network modules
##### ANSIBLE VERSION

```
ansible-playbook --version
ansible-playbook 2.2.0 (devel 9c5bcda4fe) last updated 2016/09/05 11:03:11 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 982c4557d2) last updated 2016/09/04 17:05:50 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 06bd2a5ce2) last updated 2016/09/04 17:05:50 (GMT +100)
  config file = /home/johnb/.ansible.cfg
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

n/a
##### OS / ENVIRONMENT

n/a
##### SUMMARY

When using the `provider`[1] option for network modules passwords are shown when running a task fails when running with `-vvv`
##### EXPECTED RESULTS

_Preferred Options:_

`"password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",`

_Less preferred option_
The fact that `no_log` isn't honoured in `provider` in _all_ module documentation (docs_fragments)
##### ACTUAL RESULTS

```
fatal: [testhost1: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "backup": true, 
            "provider": {
                "authorize": true, 
                "host": "testhost1", 
                "password": "mypassword",    #<-------- HERE
                "transport": "eapi", 
                "use_ssl": false, 
                "username": "admin"
            }, 
            "src": "eos.j2"
        }, 
        "module_name": "eos_template"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_qrE0BW/ansible_module_eos_template.py\", line 209, in <module>\n    main()\n  File \"/tmp/ansible_qrE0BW/ansible_module_eos_template.py\", line 201, in main\n    response = module.config(commands, replace=replace)\nTypeError: __call__() got an unexpected keyword argument 'replace'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}

```

[1] Convenience method that allows all eos arguments to be passed as a dict object. All constraints (required, choices, etc) must be met either by individual arguments or values in this dict.

**Comment by privateip** [comment]
assigning to @Qalthos

**Comment by Qalthos** [comment]
@gundalow, can you reproduce this on devel? I'm seeing passwords masked correctly as of 

```
ansible-playbook 2.2.0 (devel e8897a9b91) last updated 2016/09/09 15:54:25 (GMT -400)
  lib/ansible/modules/core: (detached HEAD bf5b3de83e) last updated 2016/09/09 15:54:31 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD f83aa9fff3) last updated 2016/09/09 15:54:31 (GMT -400)
  configured module search path = Default w/o overrides
```

**Comment by gundalow** [comment]
@Qalthos I'll retest, however it might only be in backtraces

Annoyingly I didn't include the repo case for that backtrace :(

**Comment by Qalthos** [comment]
For example, #17441 has the password masked properly.

I'm going to close this, if you find this comes up again and can provide a reproducible case, we can look into it again.
