### ISSUE TITLE
netcli.py: to_command - cmd v command

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#17408]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

netcli
##### SUMMARY

https://github.com/ansible/ansible/commit/7c928e878be2e78621d637c549daed8936d38dc7#diff-71ae27eed1a4e927dd568f6b9c2de676R71
Added

```
def to_command(self, command, output=None, prompt=None, response=None):
elif isinstance(command, dict):
    output = cmd.get('output') or output
    cmd = cmd['command']
...
return Command(command, output, prompt=prompt, response=response)

```

1)`cmd` isn't defined, should this be `command`?
2) What should returned in this case?
##### STEPS TO REPRODUCE

`pyflakes lib/ansible/module_utils/netcli.py`
##### EXPECTED RESULTS

Valid code

**Comment by privateip** [comment]
looks like some old code from the refactor ... testing now but will be sending a PR to remove the `elif` statement

**Comment by gundalow** [comment]
resolved_by_pr 17424
