### ISSUE TITLE
module_utils/netcli.py - Code review

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#17413]
##### ISSUE TYPE
- Bug Report
##### STEPS TO REPRODUCE

```
pylint $file
pyflakes $file
```
##### EXPECTED RESULTS

Clean
##### ACTUAL RESULTS

```
netcli.py:77: undefined name 'cmd'
netcli.py:78: undefined name 'cmd'
netcli.py:78: local variable 'cmd' is assigned to but never used
E: 77,21: Using variable 'cmd' before assignment (used-before-assignment)
E:221, 4: An attribute defined in ansible.module_utils.netcli line 202 hides this method (method-hidden
R:265,24: Redefinition of m type from int to str (redefined-variable-type)
```

**Comment by Qalthos** [comment]
Redefinition of m is sort of unavoidable in this case.

I moved func (the method) to _func in the hopes of clearing up the confusion... it probably isn't needed after __init__, but this is what single underscore methods are for, so...

Lines involving cmd seem to have already been dealt with. (fbda7d127faa48c11a59f1d406739224babed26b)
