### ISSUE TITLE
module_utils/eos.py - Code review

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#17410]
##### ISSUE TYPE
- Bug Report
##### STEPS TO REPRODUCE

```
pylint $file
pyflakes $file
```
##### EXPECTED RESULTS

Clean
##### ACTUAL RESULTS

```

W:125,34: Redefining built-in 'format' (redefined-builtin)
R:167,12: Redefinition of self.enable type from dict to str (redefined-variable-type) # May be OK, needs checking
W:194,32: Redefining built-in 'format' (redefined-builtin)
W: 85,16: Access to a protected member _create_default_https_context of a client class (protected-access)
W: 85,52: Access to a protected member _create_unverified_context of a client class (protected-access
W:102,11: Used builtin function 'map'. Using a list comprehension can be clearer. (bad-builtin)
W:102,11: map/filter on lambda could be replaced by comprehension (deprecated-lambda)
```

**Comment by Qalthos** [comment]
format was dealt with in ca95b2ae4f96e0b296f1ad6152ec3ea0edab7afc

The overloading of `self.enable` is kind of troublesome, but it works, and would need a deeper look to truly fix.

As for the rest, I can't find any reference to any of it in the current version nor the git history. I'm sure I'm just missing something, but without a commit to check, I can't say for sure what happened to any of it.

Feel free to update or close as you feel appropriate.
