### ISSUE TITLE
module_utils/netcfg.py - Code review

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#17412]
##### ISSUE TYPE
- Bug Report
##### STEPS TO REPRODUCE

```
pylint $file
pyflakes $file
```
##### EXPECTED RESULTS

Clean
##### ACTUAL RESULTS

```
netcfg.py:31: 'shlex' imported but unused
netcfg.py:32: 'time' imported but unused
netcfg.py:34: 'ansible.module_utils.basic.BOOLEANS_FALSE' imported but unused
netcfg.py:34: 'ansible.module_utils.basic.BOOLEANS_TRUE' imported but unused
netcfg.py:55: local variable 'lines' is assigned to but never used
E: 36, 0: Unable to import 'ansible.module_utils.six.moves' (import-error) # May be an issue with my setup, unsure
```

**Comment by Qalthos** [comment]
Imports got cleaned up in 972dc3fc97602f8402a995dad006a71cb42402c1.

six.moves sort of doesn't exist... it gets built at runtime, and definitely exists at import time, but is a mess of setattrs and manually stuffing things in sys.modules, so pylint has no way of knowing it's there.
