### ISSUE TITLE
module_utils/vyos.py - Code review

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#17416]
##### ISSUE TYPE
- Bug Report
##### STEPS TO REPRODUCE

```
pylint $file
pyflakes $file
```
##### EXPECTED RESULTS

Clean
##### ACTUAL RESULTS

```
vyos.py:72: local variable 'response' is assigned to but never used
W: 69, 4: Arguments number differs from overridden 'load_config' method (arguments-differ)
```

**Comment by Qalthos** [comment]
`response` isn't critical, but (I think) has no use anymore now that we can calculate diffs on the device.

`load_config()` is more of an issue, I expect a few methods in CliBase will need **kwargs at the end of their definitions to be overridden correctly.
