### ISSUE TITLE
Homebrew formula for ansible

### ISSUE THREAD

**Issue by esclapes** [ansible/ansible#1742]
I just moved to os x after playing with ansible in Linux. I like homebrew so I am giving a try to writing an ansible formula:

https://github.com/esclapes/homebrew/blob/ansible-formula/Library/Formula/ansible.rb

It is really just a stub, but wanted to share as per [this comment](https://github.com/ansible/ansible/issues/195#issuecomment-5450817) 

I got this output (with errors) when running the install:

```
$ brew install ansible
==> Downloading https://github.com/ansible/ansible/archive/v0.9.tar.gz
Already downloaded: /Library/Caches/Homebrew/ansible-0.9.tar.gz
==> python -s setup.py --verbose install --force --install-scripts=/usr/local/Ce
changing mode of /usr/local/Cellar/ansible/0.9/bin/ansible-pull to 755
running install_data
creating /usr/local/Cellar/ansible/0.9/share
creating /usr/share/ansible
error: could not create '/usr/share/ansible': Permission denied
```

Homebrew usually installs everything in `/usr/local` so I would say that `usr/share` should not be used.

Just for the record, I created this ansible formula by: 

1) brew create https://github.com/ansible/ansible/archive/v0.9.tar.gz
2) instructions in https://github.com/mxcl/homebrew/wiki/Homebrew-and-Python
3) removing unrecognized options when running `brew insall ansible`

I had to remove two "not recognized options" (recommended in 2) which might be necesary. This is the description for those options in the [homebrew-python docs](https://github.com/mxcl/homebrew/wiki/Homebrew-and-Python)
- `--no-user-cfg` ignore `~/.pydistutils.cfg` that can set another prefix etc.
- `--single-version-externally-managed` avoids the hard-coded egg-paths which allows us to move the module around.

**Comment by x1a0** [comment]
+1
I am also looking for a way to brew ansible

**Comment by mpdehaan** [comment]
ok, so this is a bug ticket, I don't know what you want me to do with this?

seems like you should try to submit a pull request to the homebrew project?

**Comment by esclapes** [comment]
I just cant find how to tell setup.py to use a different prefix for install_data. It seems to me that it is using `DIST_MODULE_PATH` from constants.py. However I dont know where should I set up `real_prefix`

This is where `DIST_MODULE_PATH` is set in constants.py

```
if getattr(sys, "real_prefix", None):
  DIST_MODULE_PATH = os.path.join(sys.prefix, 'share/ansible/')
else:
   DIST_MODULE_PATH = '/usr/share/ansible/'
```

where should I set up `real_prefix`?

**Comment by mpdehaan** [comment]
That comes from the interpreter.

I'd just skip homebrew, there's really no point in it -- just install with
pip, using virtualenv if you want, or "make install".
