### ISSUE TITLE
The host patterns "*" and "all" expand differently, "*" unconditionally adds localhost

### ISSUE THREAD

**Issue by klausman** [ansible/ansible#17438]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

Ansible command line tool (ad-hoc CLI)
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Both `/etc/ansible` and `~/.ansible` are absent.
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The two host patterns `all` and `*` should result in the same host list given the same inventory file and neither of them should add `localhost` to the inventory if it is non-empty.
##### STEPS TO REPRODUCE

With an empty inventory file:

```
$ ansible -i /dev/null --list-hosts "all"
 [WARNING]: provided hosts list is empty, only localhost is available

  hosts (0):
$ ansible -i /dev/null --list-hosts "*"
 [WARNING]: provided hosts list is empty, only localhost is available

  hosts (1):
    localhost
```

With no inventory file (same output as above, except for the warning at the start):

```
$ ansible  --list-hosts "all"
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

  hosts (0):
$ ansible  --list-hosts "*"
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

  hosts (1):
    localhost
```

And even with a host file, the patterns expand differently:

```
$ ansible -i bar  --list-hosts "all"
  hosts (1):
    foo

$ ansible -i bar  --list-hosts "*"
  hosts (2):
    foo
    localhost
```

Running commands against `*` also now has the effect of always including `localhost`, even if there is an inventory. I have found no way to prevent this:

```
$ cat bar
gw
$ ansible -i bar -m command -a uptime "*"
localhost | SUCCESS | rc=0 >>
 15:19:39 up  6:16,  3 users,  load average: 0.01, 0.10, 0.25

gw | SUCCESS | rc=0 >>
 15:19:40 up 5 days,  4:44,  6 users,  load average: 0.27, 0.73, 0.53
```

Using `all` does the right thing:

```
$ ansible -i bar -m command -a uptime "all"
gw | SUCCESS | rc=0 >>
 15:20:33 up 5 days,  4:45,  6 users,  load average: 0.28, 0.65, 0.51
```

##### EXPECTED RESULTS

I'd expect to both `all` and `*` to work the same in every case, and to not have `localhost` in that set when there are other hosts in the inventory.
##### ACTUAL RESULTS

See above. -vvvv makes no difference in this case.

**Comment by bcoca** [comment]
2.1.2 has a fix for the 'unconditional localhost' bug that was introduced in 2.1.1
