### ISSUE TITLE
Best alternative to run ansible from a windows machine control 

### ISSUE THREAD

**Issue by brupelo** [ansible/ansible#17439]
I'm aware of this fact [http://docs.ansible.com/ansible/intro_windows.html#reminder-you-must-have-a-linux-control-machine](http://docs.ansible.com/ansible/intro_windows.html#reminder-you-must-have-a-linux-control-machine) but I'm aware there are few tutorials about running ansible on cygwin.

In any case, what's the official recommended way to use windows as a development box and still being able to deploy to production effectively with ansible?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by mateodelnorte** [comment]
Just wanna note that by squashing this conversation, you appeared to stop the discussion from continuing. Less than helpful for those who do need a 100% Windows solution. 

Would love it if you could cap of the thread with a link to any resources you know of.

**Comment by jcaudle** [comment]
@mateodelnorte @brupelo I just found [a post on the Google Group](https://groups.google.com/forum/#!searchin/ansible-devel/windows$20control|sort:relevance/ansible-devel/45DygWennoc/oHpJYSo5EgAJ) about using the Windows Subsystem for Linux. Apparently, using WSL and installing ansible there will do it.

**Comment by mateodelnorte** [comment]
Unfortunately, don't have access to Windows 10 or the equivalent version of
Windows Server.

**Comment by jcaudle** [comment]
I don't have Windows 10 installed now either, but I was planning on
upgrading soon. My guess is that with the availability of a Linux subsystem
anywhere in the Windows world, the probability of a native Windows solution
for a control machine is even less than it was before. 😕

**Comment by brupelo** [comment]
So, summing up, there is no (and there won't be) any real solution for versions smaller than windows 10 , ie: Using now windows7 ultimate.

This software is amazing but the fact was built primarily for *nix systems is not cool. I can put my finger on the fact there are many devs like me using primarily windows as a dev platform but they're deploying on *nix systems. Anyway, at least there is some sort of solution, even if that forces you to upgrade to win10.
