### ISSUE TITLE
Wildcard conversion to ipaddr filter plugin

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#17460]
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

ipaddr.py filter plugin
##### ANSIBLE VERSION

```
```
##### SUMMARY

When working with networking devices and especially access lists, there is often a need to convert a netmask to a wildcard mask. ipaddr filter plugin already has a wide range of useful functions and this would make an excellent addition to it.

Eg. 255.255.255.0 -> 0.0.0.255

> > {{ 10.10.10.1/255.255.255.0 | ipaddr('wildcard') }} 
> > would result in:
> > 0.0.0.255

Eg. 255.255.255.252 -> 0.0.0.3

> > {{ 10.10.10.1/255.255.255.252 | ipaddr('wildcard') }} 
> > would result in:
> > 0.0.0.3

So the usage would be similar to ipaddr('netmask') but instead of a netmask it would return the wildcard mask.
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by krzysztof-magosa** [comment]
Hi @ghost,
This functionality is already implemented, just has another name.
You need to use `hostmask` and not `wildcard`.

```
- hosts: localhost
  gather_facts: no
  tasks:
    - debug:
        msg: "{{ '10.10.10.1/255.255.255.252' | ipaddr('hostmask') }}"
```

```
TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "0.0.0.3"
}
```

**Comment by stianvi** [comment]
I've heard of host bits, subnet mask, netmask and wildcard mask... never hostmask.
Maybe consider renaming to wildcard?

**Comment by krzysztof-magosa** [comment]
Ansible didn't invent own naming.
It comes from underlying library doing actual calculations.
https://docs.python.org/3/library/ipaddress.html#prefix-net-mask-and-host-mask

**Comment by itdependsnetworks** [comment]
Been added in: https://github.com/ansible/ansible/pull/26566/files#diff-52b5d47bc5ffb759787765a1aae56df7R492 

Can close.
