### ISSUE TITLE
vars_prompt can't be defined in another playbook

### ISSUE THREAD

**Issue by regexcracker** [ansible/ansible#17477]
##### ISSUE TYPE
- Bug Report
- Feature Idea
##### COMPONENT NAME

vars_prompt
##### ANSIBLE VERSION

ansible 2.1.0.0
##### OS / ENVIRONMENT

NA
##### SUMMARY

While calling vars_prompt from the top playbook enter.yml, playbook not including the file in which vars_prompt are defined. 
##### STEPS TO REPRODUCE

-- Create a playbook enter.yml
-- include another playbook prompt.yml (in which vars_prompt defined)
-- Try to use those variable which were provided by user while prompting on console.

**Comment by bcoca** [comment]
can you give a specific example, I cannot reproduce the problem with the steps given.

**Comment by regexcracker** [comment]
# enter.yml
- name: Starting  process
  hosts: '{{ host_group }}'
- include: prompt.yml
  
  roles:
      - { role: process_role, tags: ['proc']}

# prompt.yml

---

vars_prompt:
- name: "ProcessId"
  prompt: "Please pass ProcId"

**Comment by regexcracker** [comment]
Thanks All for your support.

Issue is resolved by creating a wrapper yml for local and remote Ymls.

**Main Playbook**: Wrapper.yml
- include: LocalAction.yml
- include: RemoteAction.yml


Hence, Closing the issue
