### ISSUE TITLE
_low_level_exec_command fails silently when ssh fails to authenticate

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#1748]
I ran into a situation where I was using the wrong ssh key (with connection=ssh), but the resulting error message was confusing:

```
PLAY [webservers] ********************* 

GATHERING FACTS ********************* 
<vagrant> REMOTE_MODULE setup 
fatal: [vagrant] => failed to transfer file to /setup:

Permission denied (publickey,password).
Connection closed
```

The "Permission denied" is clear enough, but the `failed to transfer file to /setup` confused me.

The reason for that error message is that _make_tmp_path was returning `/` because low_level_exec_command was failing silently instead of returning an error, so:

```
 result = self._low_level_exec_command(conn, cmd, None, sudoable=False)
```

was returning `result=''`

It would have been easier to track down the problem if `_low_level_exec_command` returned an error  rather than failing silently.

**Comment by mpdehaan** [comment]
I agree, want to patch this?

**Comment by lorin** [comment]
I'll add it to my to-do list, go ahead and assign the issue to me.

**Comment by dagwieers** [comment]
Pull request #1795 adds the proper return code to `_low_level_exec_command()` so from now on we can start testing return codes properly and bail out. We also separate stdout and stderr, which might be useful as well.

Lots of opportunities to verify `_low_level_exec_command()` calls, however we prefer to collate as many commands into one SSH roundtrip so it may not always be obvious why it fails.

**Comment by mpdehaan** [comment]
Thanks @lorin and @dagwieers
