### ISSUE TITLE
Getting hostvars from group['play_hosts']

### ISSUE THREAD

**Issue by westsouthnight** [ansible/ansible#17488]
##### ISSUE TYPE
- Bug Report
- Feature Idea
##### COMPONENT NAME

Jinja2 Templates
PlayHost group hostvars
##### ANSIBLE VERSION

ansible 2.1.1.0
##### CONFIGURATION

default
##### OS / ENVIRONMENT

MacOS X
##### SUMMARY

Need to access to play_hosts group.

If i use:

```
- name: Create Upstreams List from Presented Host Group
  hosts: cluster-{{ cluster_prefix }}
```

and i want to do next (as example):

```
- name: Create New Magic...
  debug:
        msg: |
           {% for item in groups['cluster-{{ cluster_prefix }}'] %}
           {{ hostvars[item].ansible_default_ipv4.address | join }{% endfor %}
  register: string
```

or

```
- name: Create New Magic...
  debug:
        msg: |
           {% for item in groups['play_hosts'] %}
           {{ hostvars[item].ansible_default_ipv4.address | join }{% endfor %}
  register: string
```

execution drops.

Summury:

1) We want to be able getting host vars from current play_hosts group.
2) We want no copy-paste playbooks for multiple clusters with some specific execution in process.
##### STEPS TO REPRODUCE

Try to use code above.
##### EXPECTED RESULTS

Accessing to group['play_hosts'] hostvars
##### ACTUAL RESULTS

We cannot do that

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

There is no `play_hosts` group, there is a `play_hosts` variable which contains a list of the 'current hosts in the play.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
