### ISSUE TITLE
register is executed on skipped tasks

### ISSUE THREAD

**Issue by fiunchinho** [ansible/ansible#17500]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible-playbook 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Variable takes result from `register` on skipped tasks. It's like `register` is executed even on skipped tasks.
It works fine on version 2.1.0.0, but it doesn't on 2.1.1.0.
##### STEPS TO REPRODUCE

```

---

- hosts: localhost
  connection: local
  vars:
    some_variable: False
  tasks:
    - include: a.yml
    - include: b.yml
      when: some_variable
    - debug: var=output
```

```

---

- name: "Task A"
  shell: "echo hello"
  register: output
```

```

---

- name: "Task B"
  shell: "echo bye"
  register: output
```
##### EXPECTED RESULTS

Variable doesn't get the result from register on skipped task.

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [include] *****************************************************************
included: /tmp/a.yml for localhost

TASK [Task A] ******************************************************************
changed: [localhost]

TASK [include] *****************************************************************
skipping: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "output": {
        "changed": true, 
        "cmd": "echo hello", 
        "delta": "0:00:00.093226", 
        "end": "2016-09-10 17:25:39.543569", 
        "rc": 0, 
        "start": "2016-09-10 17:25:39.450343", 
        "stderr": "", 
        "stdout": "hello", 
        "stdout_lines": [
            "hello"
        ], 
        "warnings": []
    }
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0 
```
##### ACTUAL RESULTS

Variable takes result from register on skipped task.

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Task A] ******************************************************************
changed: [localhost]

TASK [Task B] ******************************************************************
skipping: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "output": {
        "changed": false, 
        "skip_reason": "Conditional check failed", 
        "skipped": true
    }
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   
```

**Comment by aramirez-es** [comment]
I'm facing this issue as well.

**Comment by sivel** [comment]
This is expected. Although the task was skipped, information as to the task being skipped is still registered to the variable that was specified.

This allows you to do things such as `when: registered_var|skipped` to perform a task based off of a previous task being skipped.

Instead of using the same variable in 2 tasks, it is recommended that you use 2 different variable names.

If you have further questions please stop by IRC or the mailing list:
- IRC: #ansible on irc.freenode.net
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by srstsavage** [comment]
@sivel I see this has come up multiple times on the issue board and mailing list.

https://github.com/ansible/ansible/issues/4297
https://github.com/ansible/ansible/issues/15195

https://groups.google.com/forum/#!searchin/ansible-project/register$20skipped|sort:relevance/ansible-project/NGXcbyQvz-Y/nUZUUJfg1M8J

etc

This seems to be an indication that the present functionality isn't ideal. Are the core devs opposed to a better solution than the multiple variable approach described elsewhere?

**Comment by EdoBarroso** [comment]
I'm facing this same issue. 

I need to use the uri module to create some component through an API, but only if that component doesn't exist. Then, I need to use the component ID, be it a new component or the existing one, on other task.

How can I do this in a clean way? I don't want to start using different vars cause that would imply to generate two different tasks for each scenario (existing component | new component), or maybe using jinja2 to default to the existing component's ID in case the new component's ID is undefined... a bit tricky :(

**Comment by ham-360** [comment]
A relatively simple workaround that worked for me: https://github.com/ansible/ansible/issues/4297#issuecomment-356427588

**Comment by silverdr** [comment]
It is 2018 now and I just joined the camp of people heavily bitten by this "expected" behaviour. It is so counterintuitive that people will continue to fall for this trap until core devs realise that this is in fact a problem.
