### ISSUE TITLE
apt_repository doesn't check for python-software-properties

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#1751]
ansible 0.7, target system ubuntu 12.04, with the following task:

{{{
- action: apt_repository repo=ppa://semiosis/ubuntu-glusterfs-3.3
  }}}

error:

{{{
TASK: [apt_repository repo=ppa://semiosis/ubuntu-glusterfs-3.3] ********************\* 
failed: [ar48.example.com] => {"failed": true, "msg": "Failed to find required executable add-apt-repository"}
}}}

Workaround: every use of apt_repository needs to be prefixed with a check that python-software-properties is installed.

{{{
- action: apt pkg=python-software-properties state=latest
- action: apt_repository repo=ppa://semiosis/ubuntu-glusterfs-3.3
  }}}

**Comment by sfromm** [comment]
Would an addition to the module documentation (http://ansible.cc/docs/modules.html#apt-repository) that says add-apt-repository is part of python-software-properties help?

Part of the problem is that python-software-properties on debian does not include add-apt-repository.

**Comment by mpdehaan** [comment]
Sounds reasonable to me.

**Comment by leucos** [comment]
This one seems fixed no ?
https://github.com/ansible/ansible/blob/devel/library/apt_repository#L46

**Comment by candlerb** [comment]
Yeah that will do.
