### ISSUE TITLE
Feature Idea - kerberos WINRM authentication using keytabs

### ISSUE THREAD

**Issue by alv000h** [ansible/ansible#17541]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

Ansible WINRM
Kerberos
##### ANSIBLE VERSION

Ansible version 2.2
##### CONFIGURATION

ansible_winrm_*
##### SUMMARY

It would be great to have support for kerberos keytabs in ansible via an environment variable or configuration directive (ansible_winrm_keytab).

At the moment, it is necessary to invoke kinit for kerberos autentication and is not very convenient (may cause autentication errors caused for ticket expiration, etc).

**Comment by jhawkesworth** [comment]
needs_contributor 

There has been some talk about integrated kerberos ticket management and I agree it would be nice to be able to do this via any appropriate methods that kerberos supports.

If you don't mind using FILE for your keytabs until such time as ticket management can be integrated, I have a 'stop gap' callback plugin here which might be useful to you (I use daily and don't have ticket expiry issues): https://github.com/ansible/ansible/pull/14972  - see the conversation for latest version.
Using a callback plugin like this is not what callback plugins were intended for, so this isn't ever likely to be merged into ansible but might help in the meantime.

Hope this helps,

Jon

**Comment by alv000h** [comment]
@jhawkesworth thank you Jon!!!

I just read the code and that seems to be a nice WorkAround for kerberos ticket management with Ansible.

I will test it tomorrow and I will post feedback here.

Of course, I prefer native kerberos support with pyWinRM, but I think this WA will do the job...

PD:- I was wondering if it will be possible to set the variable ansible_winrm_keytab in group_vars and get it from "args[0].get_variable_manager()._inventory.get_hosts()" inside the callback, this can be useful for keytab support implementation.

**Comment by jhawkesworth** [comment]
@alv000h there's nothing special about fetching the group vars - you could add any group var you want and fetch it in the same way.  I guess if you used that to set the KRB5CCNAME environment variable then that might be enough to make kinit/klist use your keytab.

Totally agree its a horrible old bodge but, if you can accept its limitations, it works well enough.

**Comment by alv000h** [comment]
Hi @jhawkesworth 

Initial checks with your callback script run smoothly!
I miss additional information in official ansible documentation and/or in your readme about callback_plugins path location.

Since active_directory_callback is not in the ansible official repo yet, I have decided to distribute with my windows playbooks putting in callback_plugins directory inside the playbook.

I publish here the playbook directory structure for information purposes:
pb_windows/
├── callback_plugins
│   ├── active_directory_callback
│   └── active_directory_callback.rst
├── readme.txt
├── group_vars
│   └── all
└── roles
 |   └──  netbackup

Again, thank you very much!

**Comment by jhawkesworth** [comment]
@alv000h have a look in your ansible.cfg.  You can specify a path to pick up callback (and other) plugins from 
on my ubuntu box the default is
#callback_plugins   = /usr/share/ansible/plugins/callback
I just add a dir somewhere in my ansible configuration to make this available, something like this
callback_plugins = /usr/share/ansible/plugins/callback:/etc/ansible/site/plugins/callback
This works ok for me as I mostly target windows hosts.

**Comment by alv000h** [comment]
@jhawkesworth 

I thought about it, but I have multiple ansible servers (think in "workers")...
So, is more easy for me replicate the callback with the windows playbooks because it reside in a GIT repository.

Furthermore, I do not want lauch the callback every time I connect to Linux host.

**Comment by jhawkesworth** [comment]
@alv000h -  If I recall the plugin just loops through the list of hosts looking for at in the username and if there are none of those it doesn't do anything else, so not much of time penalty if you are just hitting linux hosts.
However, whatever works for you.  I just thought it might be a simple option for you.

**Comment by nitzmahone** [comment]
Take a look at http://docs.ansible.com/ansible/devel/windows_winrm.html#automatic-kerberos-ticket-management - it doesn't support keytabs yet, but it obviates the need to run kinit yourself... Going to close this for now- if keytab support is genuinely important outside of manual kinit, please open a new issue or bring it to an IRC meeting of the Windows Working Group.
