### ISSUE TITLE
conditional skip of role execution

### ISSUE THREAD

**Issue by qper** [ansible/ansible#17542]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

skip role execution if...
##### ANSIBLE VERSION

```
1.9.x & 2.0.x
```
##### SUMMARY

In ansible role we can write something like this:
`- name: check something`
`fail: msg="Oops. FAIL. Because..."`
`when: x==y`
and we get fail, execution will be stopped

I would like something like this:
`- name: check something`
`skip_execution: msg="Nothing to do... Because..."`
`when: x==y`
and all next steps in current role will be skipped.

**Comment by bcoca** [comment]
done in #17401

**Comment by qper** [comment]
@bcoca, please give me link on documentation for this feature. I think it not same issue.

**Comment by bcoca** [comment]
its a new feature in 2.2 here is the source of the docs https://github.com/ansible/ansible-modules-core/blob/devel/utilities/logic/include_role.py

basically it lets you run a role 'as a task', including conditionals when it is static: no
