### ISSUE TITLE
Ansible selects wrong group_vars in combination with --limit and host in multiple groups

### ISSUE THREAD

**Issue by cisarpavel** [ansible/ansible#17559]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

group vars selection
##### ANSIBLE VERSION

```
2.1.1.0
```
##### CONFIGURATION

default pip install
##### OS / ENVIRONMENT

Ubuntu 16.04
##### SUMMARY

If you have host defined in more groups, and you will run playbook with --limit arg for the one of them, ansible loads vars for all groups where the host is assigned and take varibles from the latest loaded group vars ignoring --limit arg.
##### STEPS TO REPRODUCE

host file

```
[agroup]
server

[zgroup]
server
```

group_vars structure folders/file structure

```
group_vars
    - agroup
        - vars
    - zgroup
        - vars
```

run

```
ansible-playbook some_palybook.yml --limit=agroup
```

ansible will took variables from zgroup instead of limited agroup
##### EXPECTED RESULTS

playbook will select correct group_vars for agroup
##### ACTUAL RESULTS

playbook selects group_vars for zgroup

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Ansible loads inventory independent from from play targets, `--limit` only affects play targets and is not designed to restrict inventory loading.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
