### ISSUE TITLE
Cows don't like unicode tasks

### ISSUE THREAD

**Issue by clonedagain** [ansible/ansible#17560]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Cowsay integration
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

and

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

All defaults except `ANSIBLE_NOCOWS`
##### OS / ENVIRONMENT

Up-to-date Ubuntu 16.04
##### SUMMARY

Display cows yields unicode-related warning messages when runnin tasks with names containing non-ascii characters (ie. non-English phrases).
##### STEPS TO REPRODUCE

Run this playbook:

```

---
- name: Tâsk wïth Ûnïçöd€ name
  hosts: localhost
  user: root
  tasks:
    - ping:
```
##### EXPECTED RESULTS

Happy cows no matter the task.
##### ACTUAL RESULTS

With cowsay installed and ANSIBLE_NOCOWS unset, we get the following warning:

```
 [WARNING]: Failure using method (v2_playbook_on_play_start) in callback plugin
(<ansible.plugins.callback.default.CallbackModule object at 0x7f713dc6c110>): 'ascii' codec can't
decode byte 0xc3 in position 42: ordinal not in range(128)

 ______________
< TASK [setup] >
 --------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost]
 _____________
< TASK [ping] >
 -------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost]
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

localhost                  : ok=2    changed=0    unreachable=0    failed=0   


```

With ANSIBLE_NOCOWS=1 no such warning is printed.

Tasks with only ASCII characters never get a warning message printed.

**Comment by clonedagain** [comment]
No such warning was printed in v1.9

**Comment by clonedagain** [comment]
This bug is not a big problem in itself, but it may confuse to users upgrading from v1.9, leading them to believe their playbooks are not compatible.

**Comment by abadger** [comment]
Thanks for reporting, I've merged https://github.com/ansible/ansible/issues/17576 which should fix this.
