### ISSUE TITLE
stat.exist not work in when statement

### ISSUE THREAD

**Issue by ARogovsky** [ansible/ansible#17588]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

stat
when
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

Description:    Ubuntu 16.04 LTS
##### SUMMARY

Module state is not work in when statement
##### STEPS TO REPRODUCE

There is sample yml file is not work:

```

---
- hosts: localhost
  tasks:
    - stat: path=/etc/foo.conf
      register: st
    - fail: msg="File not found"
      when: st.stat.exist
```
##### EXPECTED RESULTS

I expect File not found message.
##### ACTUAL RESULTS

Looks, like stat not work in when statement, couse it throw this error:

"The conditional check 'st.stat.exist' failed. The error was: error while evaluating conditional (st.stat.exist): 'dict object' has no attribute 'exist'

```
# ansible-playbook -vvvvv x.yml 
Using /etc/ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0

PLAYBOOK: x.yml ****************************************************************
1 plays in x.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1473952520.08-219063427451269 `" && echo ansible-tmp-1473952520.08-219063427451269="` echo $HOME/.ansible/tmp/ansible-tmp-1473952520.08-219063427451269 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpjO_UZS TO /root/.ansible/tmp/ansible-tmp-1473952520.08-219063427451269/setup
<127.0.0.1> EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1473952520.08-219063427451269/setup; rm -rf "/root/.ansible/tmp/ansible-tmp-1473952520.08-219063427451269/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [stat] ********************************************************************
task path: /root/new/freeipa-ds389d/tests/x.yml:4
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1473952520.89-124829052999301 `" && echo ansible-tmp-1473952520.89-124829052999301="` echo $HOME/.ansible/tmp/ansible-tmp-1473952520.89-124829052999301 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpmzuP3h TO /root/.ansible/tmp/ansible-tmp-1473952520.89-124829052999301/stat
<127.0.0.1> EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1473952520.89-124829052999301/stat; rm -rf "/root/.ansible/tmp/ansible-tmp-1473952520.89-124829052999301/" > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {"changed": false, "invocation": {"module_args": {"checksum_algorithm": "sha1", "follow": false, "get_checksum": true, "get_md5": true, "mime": false, "path": "/etc/foo.conf"}, "module_name": "stat"}, "stat": {"exists": false}}

TASK [fail] ********************************************************************
task path: /root/new/freeipa-ds389d/tests/x.yml:6
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'st.stat.exist' failed. The error was: error while evaluating conditional (st.stat.exist): 'dict object' has no attribute 'exist'\n\nThe error appears to have been in '/root/new/freeipa-ds389d/tests/x.yml': line 6, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      register: st\n    - fail: msg=\"File not found\"\n      ^ here\n"}

NO MORE HOSTS LEFT *************************************************************
 [WARNING]: Could not create retry file 'x.retry'.         [Errno 2] No such file or directory: ''


PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   

```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

The correct key is 'exists' not 'exist', so this should work:
`when: st.stat.exists`
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by 3j0s** [comment]
Greetings!

I've the configuration as follow: 

ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

And i get this error, which is the same as the problem above

- hosts: local
  become: yes
  pre_tasks:
    - shell: echo "Revoking Access Support.."
  vars_files:
    - vars/users.yml
  tasks:

    - stat:
        path: "/home/{{ item.name }}/.ssh/authorized_keys"
      with_items: "{{ users }}"
      register: hm
      tags:
         - checking_file_exists

    - name: Deleting authorization key
      command: " rm -f /home/{{ item.name }}/.ssh/authorized_keys"
      when: hm.stat.exists == True
      with_items: "{{ users }}"
      tags:
         - deleting_auth_file

fatal: [172.16.100.22]: FAILED! => {
    "failed": true,
    "msg": "The conditional check 'hm.stat.exists == True' failed. The error was: error while evaluating conditional (hm.stat.exists == True): 'dict object' has no attribute 'stat'\n\nThe error appears to have been in '/opt/ansible/check_user_exist.yaml': line 17, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Deleting authorization key\n      ^ here\n"
}

Can you help me, thx

**Comment by nmartinez-nimeops** [comment]
Hi all
Same issue!

ansible 2.4.2.0
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]

**Comment by bcoca** [comment]
When you use a loop and register vars, you get 'varname.results.<normal
return>'
 where 'results' is a list with a number of entries that matches the
number of items in the loop.

'hm' does not have a 'stat' it has a 'results', so you need
hm.results[<index for item i want>].stat.exists

**Comment by ats0stv** [comment]
I'm also facing a very similar issue. 
```
Apr  5 13:14:56 [err] (display) fatal: [x.x.x.x]: FAILED! => {"msg": "The task includes an option with an undefined variable. 
The error was: 'dict object' has no attribute 'md5'
The error appears to have been in '/devops/roles/client_redirect/tasks/install.yml': line 5, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:

- name: Install client log redirection
  ^ here"}
```

My Ansible configuration is 
```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/home/runner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```
