### ISSUE TITLE
Sudo on change

### ISSUE THREAD

**Issue by fredrik-rambris** [ansible/ansible#17583]
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

become
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /Users/boost/Projects/ansible/stack/ansible.cfg
  configured module search path = ['../common/library']
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Sometimes you want to only switch to privileged user when a change is needed. For example yum can check if the package is present as a non-privileged user and only when a change is needed would  we need to escalate.

So a become_on_change: true option
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment]
Since we currently need to execute the escalation wrapping the module, we have no way to know if change is needed before the escalation happens. 

This would require modules to perform the escalation themselves.

**Comment by fredrik-rambris** [comment]
That is true. It would have to be implemented in each module that could support this. But when run with --check the become_on_change=true could be handled outside of the module as then you have signaled that I will not be making any changes and should not need to escalate. I could then run through automatic compliance/drift testing without giving out root access but when admin needs to change something that could escalate nicely.

**Comment by bcoca** [comment]
most modules would already 'work this way'.  service, for example,  can be set to 'started', then if the service is up, everything is OK, if not, it fails. 

I once setup QA to use same plays that setup the boxes to verify that they are correct, since they did not have root, any failure indicated that box was not setup correctly.

**Comment by samdoran** [comment]
We have no plans to implement this feature at this time.

To discuss this further, please reach out on IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by samdoran** [comment]
Related to https://github.com/ansible/ansible/issues/12630
