### ISSUE TITLE
Parsing error results in ERROR! Unexpected Exception: 0

### ISSUE THREAD

**Issue by leifmadsen** [ansible/ansible#17594]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

parsing/quoting.py
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /home/lmadsen/src/github/leifmadsen/ansible-cira/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
roles_path = ./roles
gathering = smart
fact_caching = jsonfile
fact_caching_connection = ~/.ansible/cachedir
fact_caching_timeout = 86400
host_key_checking = False
inventory = ./hosts/

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=300s -o ForwardAgent=yes
```
##### OS / ENVIRONMENT

Fedora 24
##### SUMMARY

When failing to provide a `tasks:` value about a named play, `ERROR! Unexpected Exception: 0` is returned.
##### STEPS TO REPRODUCE

Fail to provide a `tasks:` header above a named play.

```
# vim: ft=ansible                                                               
---                                                                             
- hosts: jenkins_master                                                         
  tags:                                                                         
    - jenkins_master                                                            
    - jenkins_ssh                                                               

  vars_files:                                                                   
    - "{{ inventory_dir  }}/../vars/main.yml"                                   
    - ~/.ansible/vars/cira_vars.yml                                             

    - name: Create Jenkins user .ssh directory                                  
      file:                                                                     
        path: "{{ jenkins_master_ssh_directory }}"                              
        state: directory                                                        
        owner: jenkins                                                          
        group: jenkins                                                          
        mode: "0700"
```

_Note_ the missing `tasks:` above `- name: Create...`

##### EXPECTED RESULTS

Ansible to nicely exit pointing to line in file that couldn't be parsed appropriately.
##### ACTUAL RESULTS

Ansible crashes and outputs information that isn't overly helpful to narrowing down where the parsing error happened in the file.

```
ansible-playbook -vvv --syntax-check jenkins_ssh.yml 
Using /home/lmadsen/src/github/leifmadsen/ansible-cira/ansible.cfg as config file
1 plays in jenkins_ssh.yml
ERROR! Unexpected Exception: 0
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 86, in <module>
    sys.exit(cli.run())
  File "/home/lmadsen/.local/lib/python2.7/site-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/home/lmadsen/.local/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 117, in run
    all_vars = self._variable_manager.get_vars(loader=self._loader, play=play)
  File "/home/lmadsen/.local/lib/python2.7/site-packages/ansible/vars/__init__.py", line 305, in get_vars
    data = preprocess_vars(loader.load_from_file(vars_file))
  File "/home/lmadsen/.local/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 105, in load_from_file
    file_name = self.path_dwim(file_name)
  File "/home/lmadsen/.local/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 212, in path_dwim
    given = unquote(given)
  File "/home/lmadsen/.local/lib/python2.7/site-packages/ansible/parsing/quoting.py", line 28, in unquote
    if is_quoted(data):
  File "/home/lmadsen/.local/lib/python2.7/site-packages/ansible/parsing/quoting.py", line 24, in is_quoted
    return len(data) > 1 and data[0] == data[-1] and data[0] in ('"', "'") and data[-2] != '\\'
KeyError: 0
```

**Comment by iamyogeshg** [comment]
+1 
Ansible version: ansible 2.3.0.0



> 2017-05-16 16:49:35,593 p=2435 u=root |  META: ran handlers
> 2017-05-16 16:49:35,594 p=2435 u=root |  META: ran handlers
> 2017-05-16 16:49:35,601 p=2435 u=root |  ERROR! Unexpected Exception: 0
> 2017-05-16 16:49:35,603 p=2435 u=root |  the full traceback was:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/ansible-playbook", line 109, in <module>
>     exit_code = cli.run()
>   File "/usr/local/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 154, in run
>     results = pbex.run()
>   File "/usr/local/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 125, in run
>     all_vars = self._variable_manager.get_vars(loader=self._loader, play=play)
>   File "/usr/local/lib/python2.7/dist-packages/ansible/vars/__init__.py", line 312, in get_vars
>     data = preprocess_vars(loader.load_from_file(vars_file))
>   File "/usr/local/lib/python2.7/dist-packages/ansible/parsing/dataloader.py", line 110, in load_from_file
>     file_name = self.path_dwim(file_name)
>   File "/usr/local/lib/python2.7/dist-packages/ansible/parsing/dataloader.py", line 218, in path_dwim
>     given = unquote(given)
>   File "/usr/local/lib/python2.7/dist-packages/ansible/parsing/quoting.py", line 28, in unquote
>     if is_quoted(data):
>   File "/usr/local/lib/python2.7/dist-packages/ansible/parsing/quoting.py", line 24, in is_quoted
>     return len(data) > 1 and data[0] == data[-1] and data[0] in ('"', "'") and data[-2] != '\\'
> KeyError: 0

**Comment by kayrus** [comment]
+1 for ansible 2.3.0:

```
ERROR! Unexpected Exception: 0
the full traceback was:

Traceback (most recent call last):
  File ".venv/bin/ansible-playbook", line 109, in <module>
    exit_code = cli.run()
  File "/home/user/ansible-playbook/.venv/local/lib/python2.7/site-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/home/user/ansible-playbook/.venv/local/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 125, in run
    all_vars = self._variable_manager.get_vars(loader=self._loader, play=play)
  File "/home/user/ansible-playbook/.venv/local/lib/python2.7/site-packages/ansible/vars/__init__.py", line 312, in get_vars
    data = preprocess_vars(loader.load_from_file(vars_file))
  File "/home/user/ansible-playbook/.venv/local/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 110, in load_from_file
    file_name = self.path_dwim(file_name)
  File "/home/user/ansible-playbook/.venv/local/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 218, in path_dwim 
    given = unquote(given)
  File "/home/user/ansible-playbook/.venv/local/lib/python2.7/site-packages/ansible/parsing/quoting.py", line 28, in unquote
    if is_quoted(data):
  File "/home/user/ansible-playbook/.venv/local/lib/python2.7/site-packages/ansible/parsing/quoting.py", line 24, in is_quoted 
    return len(data) > 1 and data[0] == data[-1] and data[0] in ('"', "'") and data[-2] != '\\'
KeyError: 0
```

This occurs with the following code:

```
- hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - { var_file: 'group_vars/vagrant.yml', when: "groups['vagrant'] is not defined" }
```

**Comment by maxamillion** [comment]
@leifmadsen I'm unable to reproduce this with your example in Ansible 2.5.3, can you please verify this is resolved for you?

**Comment by maxamillion** [comment]
@kayrus what you're attempting to do is not supported, but we should definitely handle that with a graceful error message

**Comment by leifmadsen** [comment]
@maxamillion oh man... I don't even remember this issue lol. I'm ok with closing this. I'll reopen if I run into it again, but I haven't run into it in any of my development since reporting this about 18 months ago :)

**Comment by maxamillion** [comment]
@leifmadsen no worries, I've put together a PR to fix the issue that @kayrus pointed out and your original issue appears to be resolved. Thank you for the bug report! (sorry for the lag time)

**Comment by Akasurde** [comment]
Closing and re-opening for CI trigger.

**Comment by Akasurde** [comment]
Accidentally closed. Reopened.
