### ISSUE TITLE
SSH connection issue with a Firewall

### ISSUE THREAD

**Issue by yoyayi** [ansible/ansible#17600]
##### ISSUE TYPE

- Not working as expected
##### ANSIBLE VERSION

```
ansible 2.0.0.2
```
##### CONFIGURATION

Nothing changed from the default file... even though I tried some stuff, I reverted back to the original configuration.
##### OS / ENVIRONMENT

Ubuntu 16.04 <->Fortinet Fortigate VM Firewall
##### SUMMARY

I'm trying to push commands via SSH to my firewall with no success. This is my first try with Ansible so this might be my fault.
Ansible return an "unreachable" which is not right. I'm seeing all the packets hitting my device. 
Now even on the Ansible debug's, we see that it did manage to connect: "PUT /tmp/tmpbY3GJP TO FG_2_Lab_VM02 #/command" , basically this FG_2_Lab_VM02# is my device and this is the main prompt where you push commands.

I did two debugs on my firewall from the ssh daemon, one using the connection from Ansible and another one using the "SSH" module in Ubuntu (ssh admin@IP and this one works perfectly fine) and I found out two differences, not sure if those are the one causing the issue:

For the SSH:
SSH: server_input_channel_req: channel 0 request shell reply 1
SSH: session_by_channel: session 0 channel 0
SSH: session_input_channel_req: session 0 req shell

For the Ansible:
SSH: server_input_channel_req: channel 0 request exec reply 1
SSH: session_by_channel: session 0 channel 0
SSH: session_input_channel_req: session 0 req exec

Now I'm wondering if it's the type of request that cause the failure.

If needed I can put the whole debug from my FW (which is quite long)
##### EXPECTED RESULTS

Should connect via SSH and push the command. 
##### ACTUAL RESULTS

admin@ubuntu:~$ ansible FGT -vvvvv -a "get system status" --user=admin2 -k -c ssh
Using /etc/ansible/ansible.cfg as config file
SSH password: 
Loaded callback minimal of type stdout, v2.0
<10.0.3.64> ESTABLISH SSH CONNECTION FOR USER: admin2
<10.0.3.64> SSH: ansible.cfg set ssh_args: (-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<10.0.3.64> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User=admin2)
<10.0.3.64> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<10.0.3.64> SSH: PlayContext set ssh_common_args: ()
<10.0.3.64> SSH: PlayContext set ssh_extra_args: ()
<10.0.3.64> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/home/admin/.ansible/cp/ansible-ssh-%h-%p-%r)
<10.0.3.64> SSH: EXEC sshpass -d14 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o User=admin2 -o ConnectTimeout=10 -o ControlPath=/home/admin/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.0.3.64 '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1473976620.91-118703062465370 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1473976620.91-118703062465370 )" )'
<10.0.3.64> PUT /tmp/tmpbY3GJP TO FG_2_Lab_VM02 #/command
<10.0.3.64> SSH: ansible.cfg set ssh_args: (-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<10.0.3.64> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User=admin2)
<10.0.3.64> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<10.0.3.64> SSH: PlayContext set ssh_common_args: ()
<10.0.3.64> SSH: PlayContext set sftp_extra_args: ()
<10.0.3.64> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/home/admin/.ansible/cp/ansible-ssh-%h-%p-%r)
<10.0.3.64> SSH: EXEC sshpass -d14 sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o User=admin2 -o ConnectTimeout=10 -o ControlPath=/home/admin/.ansible/cp/ansible-ssh-%h-%p-%r '[10.0.3.64]'
10.0.3.64 | UNREACHABLE! => {
    "changed": false, 
    "msg": "ERROR! SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", 
    "unreachable": true
}
admin@ubuntu:~$ 

```

```

**Comment by mscherer** [comment]
What is the os of the fortigate firewall ? 

Would it work with the 'raw' module ? (-m raw)

**Comment by yoyayi** [comment]
@mscherer Cheers! Working perfectly now :)
