### ISSUE TITLE
Authorized_key does not remove keys with state=absent and $FILE

### ISSUE THREAD

**Issue by c0rner** [ansible/ansible#1761]
When using a file as source with $FILE the keys listen in the file are not removed.

action: authorized_key user=root key='$FILE(/data/authorized_keys)' state=absent

Commit used: 959a46108000b876e4381f5efe792d9df4f5285d

**Comment by dhozac** [comment]
What does your file contain? `od -tx1a /data/authorized_keys` would be greatly appreciated.

**Comment by c0rner** [comment]
'od' output got really big so I'm posting it uuencoded instead.

begin-base64 644 authorized_keys
c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBQkl3QUFBUUVBeno5M2kxN0F0
VGZPTHdJaXFwRzcxdXhyR3M5aVkyRzZYSUg4N0FqWGR6bC9pbXQxcVFjdWhx
QWpMU205T3lva0hIQ0JTb3lRR3JzQUxwMDQ0ZDhCNGxOWE9wQmNrMms4ZmdP
QzBnZnJhdTRJZjZmVzVGaHpObDdaMlQ3Y1g5QS9zUTNsc3R3cnp1bzV5MUw4
UTJoRWJtWjFjMmIvZlkxalAzUnB2a2VsdVZ4a1czK3ZKbm9tRnFIN2ZINzNn
WWZEc21tbk5lSlVPVWxWb24veFpoWStQOGR5cm1zaXJKQzZkeWdTWnhuckU3
NnNZWCtqT2tPSFZnMXIrSVNOZDlhNEdtLzVhLzlSOFZ2UHZCOWJ5d1BGSldR
TXNBQTNvZnlOaGNBZGMyR25OU3MvM0xXdTB2YUJFZDNtdDVLaWMzSmh0NWpJ
QjZ5aFBtTXlHK2MwbXJDK0xRPT0gam9obi5kb2VAZXhhbXBsZS5jb20Kc3No
LXJzYSBBQUFBQjNOemFDMXljMkVBQUFBQkl3QUFBUUVBM28wb3NXUy8yZmJG
elUyS2hLRmNDdEM3R1pzUWlTVG5kQ1V1RXRxa1Y3R1IvMjhJd3FpUXVTNW16
YXVSZ3hVa2hUNnNrVnd1Q2ZIQ1N4NGNGSkdsUG5rbFQzcFVNZlV3czNPRFo2
bmhYNzU2THExTHNwd3pjeUJkN2VoRjBGWWdXaXJobDF3SU1oV0pyR3NxUUh4
NTVzaVBvT0ozOHRMSWx4RHpUdDEzM2JVb3ZkaHZGVFBab2NDWjdtQTA4Zkhl
UElJM3VTemlnNkt2NjlRdnN1NUwrNllxR0NDc29reGJXVzEzSnY5MUhxdHJW
WG8wbTcwWld1aTNhMjZRVENRTUh5ZnJkd005SGJBRXB0SUJ5M2UyYjdaczV0
VWU3MkdwNElOOHhlK2N1M1hLQ09Ia1RTRXNPTEcvVWlhbzFDNjluM203Z0cv
TVBRRWVrcmRlbk56akJRPT0gaGVsZW4uaHVudEBleGFtcGxlLmNvbQpzc2gt
cnNhIEFBQUFCM056YUMxeWMyRUFBQUFCSXdBQUFnRUF2M0xmeUo0NHNBR1l5
eXo4OUtWQW9xTlY2T0c5TmFHcDdpZHpOaElQYXpNdUJzLzlhZGdCc2ZiOHRD
MjduWjBVdzNTWVgyeTZKTXdCb0h6cTZMcER5bFlGakZEc1Q3VElaMFVLVWkx
RXlwdUREU1hkSGo1K2VjNzZsbFAxRzZrSXVDZEsvTG45S1FXS3R5SzhxckFa
WkFqaEdla3l1Z2hocnhLNk1McE5IVWNzeEMyalVRTkJ2SGRvQ0hOYnRaVUtk
WS85aURQNkVPb0poTWxUVG5HZmVBK0Q4aWZBS1BXWkYwTjZoazVsUEdBKzZJ
eXI5YnNJTXJOOFc5UlYreE9oTmNMeWgzVUZvdUhUY1prM2RNelhZbk1MNURE
ZjRXeHBtejRNRW1NMFBLWG5qVmxWU2YxcGc1bjUwYzAzb2RWWEZlZGxuS0dY
R1hmbkdnVWdCUDUxN0ZMWGpjUWNEZU5TVXozRTA4aXV3Tm1zNXpHTGxKcFAx
QXBkUytZT1FTNll3U3ZBNWh2N1U0QUxyQWE3Y1hKUWFCbGNzOTBDSmU3djNX
VVI0R05PNmhRcnBXcVhHbHdMSnQxM0pYajNDWWIya01SWDJ0dG1BMlp1dTMw
V2hRRVFwMjQrbGpEd3FkR2gxVzRxWlVJR29HTUdCbTlXeXVtbkVwU2ZWcUZm
eEo5Njh2SWRQV0hrUEZFUnp6ZHQvU0wzUHNlVGFBNkJOVVh5Vm5IRVhYU0hX
cnRmUXhRZjg3VGFPbk90UlJpYnNyMlZzc1g1bXFVTno4UEYreEtTQ3N5QzVq
QWoreUxmYVZIVjdjMzhsK3VIMnhTa1YwQnhZeGkrblpsYkd1UlBHeElDTXZs
SWhlcEkvNzZyejFKanJHUnBYb3JmUDlaeGFpQ082Z2lDL1djNkdRcz0gbXIu

# cGFyYW5vaWRAZXhhbXBsZS5jb20K

Gahh..  not sure this is gonna work but it's missing the last row '===='

**Comment by dhozac** [comment]
You have multiple keys in there. authorized_key is singular, meaning it only deals with one key at a time. You probably want to use `with_lines: cat <filename>` and `key='$item'` instead.

**Comment by c0rner** [comment]
Ok, I suppose it is obvious looking at the module name all though it would have made sense for the module to handle multiple keys.

Will take a look at with_lines, thanks for pointing me in the right direction.
