### ISSUE TITLE
Authorized_key module is not idempotent when using $FILE

### ISSUE THREAD

**Issue by c0rner** [ansible/ansible#1763]
When adding keys from a file with the $FILE directive the keys listed are always added to '.ssh/authorized_keys'. Thus running this multiple times will add the keys listed for each invocation growing the remote authorized_keys file.

Commit used: 959a46108000b876e4381f5efe792d9df4f5285d

**Comment by c0rner** [comment]
This may be due to using a source file with multiple keys in is, see #1761. I was under the impression that this module handled multiple keys disregarding the fact that the module name hints at handling one key at a time.

Will try to verify this during the day.

**Comment by c0rner** [comment]
Verified that this module indeed is working as expected when using $FILE() listing a single key only.  I do however feel that this module is bugged as it will "fail" horribly if the included file contains more than one line.

Perhaps this module should use something like 'head -n 1' or be modified to handle multiple keys.

**Comment by sfromm** [comment]
If you want to act on multiple keys, you should use _with_items_.  The authorized_key parameter _key_ takes a single key.  http://ansible.cc/docs/playbooks2.html#getting-values-from-files provides an example using $FILE and with_items.

**Comment by c0rner** [comment]
Not sure if im beating a dead cow here but this ticket is not about acting on multiple keys, this I have already solved using with_lines.

I believe this module need to safe guard against a $FILE option that would end up including multiple keys thus breaking being idempotent.

**Comment by sfromm** [comment]
The authorized_key module has no knowledge of $FILE().  When it is run on the target host, authorized_key only sees an argument that looks like:

```
key='ssh-dss blargh foo\nssh-dss blargh2 bar'
```

An argument could be made for updating authorized_key module to check the key parameter for newline characters and either:  1) warn and try to handle it as a list or 2) call fail_json for a bad value for _key_.  However, this isn't unique to whether one uses $FILE().  BTW, I'm inclined to choose option 2.  The documentation is pretty clear that it takes a single key.

**Comment by skvidal** [comment]
I use authorized_key with $PIPE(program-which-returns-multiple-keys). It has the same problem - it is increasing the number of entries w/o bound. I hadn't noticed this until now, though.

In my case the program returns keys for sets of users based on their unix groups. So I can authorize logins for an entire group to one instance in a cloud provider. This needs to be able to handle multiple keys.
