### ISSUE TITLE
documentation issue in ansible/docsite/rst/intro_adhoc.rst (Introduction To Ad-Hoc Commands)

### ISSUE THREAD

**Issue by hwasp** [ansible/ansible#17639]
##### ISSUE TYPE
- Documentation Report
##### COMPONENT NAME

Introduction To Ad-Hoc Commands doc page (ansible/docsite/rst/intro_adhoc.rst )
##### ANSIBLE VERSION

ansible 2.1.1.0
##### CONFIGURATION

by default (no changes in ansible.cfg)
##### OS / ENVIRONMENT

CentOS 7.1
##### SUMMARY

Trying to run the command specified in the File Transfer section:

$ ansible atlanta -m copy -a "src=/etc/hosts dest=/tmp/hosts"

brings the error:    "msg": "file (/tmp/hosts) is absent, cannot continue"

I had to add the "state=touch" to be able to create the file:

$ ansible atlanta -m copy -a "src=/etc/hosts dest=/tmp/hosts state=touch"

Please check if is necessary to correct the documentation or if I miss something.
##### STEPS TO REPRODUCE

Follow the indications in the documentation.
##### EXPECTED RESULTS

The file is copied remotely.
##### ACTUAL RESULTS

The file is not copied if doesn't exist in the destination, add state=touch seems needed to force the creation.

**Comment by bcoca** [comment]
First, this would be an issue with the `copy` module and as such should be opened in the modules-core repo.

Second, I tested the same thing and could not reproduce your results:

```
ansible test1 -m copy -a "src=/etc/hosts dest=/tmp/hosts"
test1 | SUCCESS => {
    "changed": true,
    "checksum": "d2764d03f08a363847bf871d02c22dedaf9a4266",
    "dest": "/tmp/hosts",
    "gid": 1000,
    "group": "bcoca",
    "md5sum": "59ab700b91665f43dbb25d9ed2e398cc",
    "mode": "0644",
    "owner": "bcoca",
    "size": 1108,
    "src": "/home/bcoca/.ansible/tmp/ansible-tmp-1474304045.73-178958754307383/source",
    "state": "file",
    "uid": 1000
}
```

Also 'touch' is a state of the `file` module, it is not valid for `copy`

**Comment by hwasp** [comment]
True, I was using file instead of copy, sorry my mistake.
