### ISSUE TITLE
Strange behaviour of when: conditionals with string values

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#17650]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

task conditional handling (`when: ...`)
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 1d2e1a5648) last updated 2016/09/19 20:42:37 (GMT +100)
  lib/ansible/modules/core: (detached HEAD e3b6f52bf5) last updated 2016/09/19 20:46:40 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 0b778350ec) last updated 2016/09/19 20:46:40 (GMT +100)
  config file =
  configured module search path = Default w/o overrides
```

Same behaviour also observed with 2.1.0.0
##### CONFIGURATION

No special configuration
##### OS / ENVIRONMENT

N/A (tested with both OSX 10.11.6 and Ubuntu 16.04)
##### SUMMARY

I expected a conditional like `when: myvar` to be considered true if the variable is set to any non-false value (including a non-empty string)

However it appears to be doing a _second_ level of expansion. For example if myvar expands to the string "foo" then ansible tries to expand the value of expression "foo", which fails if there is no variable called "foo" in the runtime environment. If myvar is set to the string "foo.bar" then it tries to expand foo; presumably it would then apply the "bar" method to the value if one was found.

Note: `when: not myvar` works as expected: the action is taken if myvar is empty string, and not taken if myvar is a non-empty string; there is apparently no second level of expansion.

So a workaround is to write `when: not not myvar`
##### STEPS TO REPRODUCE

Run the following playbook. You can use either variant of the "when:" statements.

```
- hosts: localhost
  gather_facts: false
  vars:
    myserv: www.example.com
    #myserv: ''
  tasks:
    - debug: msg="wibble"
      when: not myserv
      #when: '{{ not myserv }}'

    - debug: msg="bibble"
      when: myserv
      #when: '{{ myserv }}'
```

It's the same whether you use the braces or not.

##### EXPECTED RESULTS

1. If myserv is any 'false-like' value (e.g. null, False, empty string) then the first debug runs
2. If myserv is any 'true-like' value (e.g. non-empty string) then the second debug runs

The [documentation](http://docs.ansible.com/ansible/playbooks_conditionals.html#the-when-statement) gives these examples:

```
tasks:
    - shell: echo "This certainly is epic!"
      when: epic

tasks:
    - shell: echo "This certainly isn't epic!"
      when: not epic
```

which seems consistent with what I'm trying (except that in the documentation, 'epic' is set only to the values True and False, rather than other values like an empty string or a non-empty string)
##### ACTUAL RESULTS

When myserv is empty string, it works fine. The first debug runs and the second does not.

When myserv is the string "foobar" then you get this error from the second debug:

> error while evaluating conditional ({{ myserv }}): 'foobar' is undefined

When myserv is the string "www.example.com" then you get the error: `'www' is undefined`

> error while evaluating conditional ({{ myserv }}): 'www' is undefined

```
PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
skipping: [localhost]

TASK [debug] *******************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check '{{ myserv }}' failed. The error was: error while evaluating conditional ({{ myserv }}): 'www' is undefined\n\nThe error appears to have been in '/Users/brian/git/ansible/ert.yml': line 11, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - debug: msg=\"bibble\"\n      ^ here\n"}
    to retry, use: --limit @/Users/brian/git/ansible/ert.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by bcoca** [comment]
So this is not new behavior so the recent templating changes did not cause this, removing P1 tags as this seems to be a 'jinaj2' behavior.

**Comment by bcoca** [comment]
@candlerb, please confirm that the PR above fixes this for you

**Comment by candlerb** [comment]
The fix works when using a bare expression:

```
- hosts: localhost
  gather_facts: false
  vars:
    myserv: www.example.com
    #myserv: ''
  tasks:
    - debug: msg="wibble"
      when: not myserv

    - debug: msg="bibble"
      when: myserv
```

It still fails if I use a jinja2 expansion in the 'when' condition:

```
- hosts: localhost
  gather_facts: false
  vars:
    myserv: www.example.com
  tasks:
    - debug: msg="wibble"
      when: '{{ not myserv }}'

    - debug: msg="bibble"
      when: '{{ myserv }}'
bash-3.2$ ansible-playbook ert.yml
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
skipping: [localhost]

TASK [debug] *******************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check '{{ myserv }}' failed. The error was: error while evaluating conditional ({{ myserv }}): 'www' is undefined\n\nThe error appears to have been in '/Users/brian/git/ansible/ert.yml': line 9, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - debug: msg=\"bibble\"\n      ^ here\n"}
    to retry, use: --limit @/Users/brian/git/ansible/ert.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

This is perhaps not a sanctioned way of using `when` (but it _is_ now the required way of using `with_items`)

**Comment by bcoca** [comment]
you should never use  `{{ }}` in conditinals, its already implied and "they don't stack"

2 rules:
- mustaches (`{{}}`) don't stack, so  no `{{ {{ }} }}`
- always use mustaches except when `when:` (as they are implied and violates rule 1)

**Comment by candlerb** [comment]
OK, thanks. Perhaps the error message could be more helpful, but maybe that's not feasible.
