### ISSUE TITLE
Per host files

### ISSUE THREAD

**Issue by ohmer1** [ansible/ansible#17672]
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

N/A
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /home/me/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

For module that work with files (like copy), add a directory in the include path located in _host_files/{{ inventory_hostname}}_. The file is this directory should be included only when there is no other match elsewhere (like in the role).

It would be similar with the feature that include variables file located in _host_vars/{{ inventory_hostname}}_.
##### STEPS TO REPRODUCE

This example task would copy the file located at _host_files/{{ inventory_hostname}/myapp.crt_ to the remote server because the file is missing from others include path (this is custom or each servers).

```
- name: Copy certificate file
  copy:
    src=myapp.crt
    dest=/etc/ssl/myapp.crt
```

**Comment by bcoca** [comment]
This can easily be done already

```
- name: Copy certificate file
  copy:
    src=host_files/{{inventory_hostname}}/myapp.crt
    dest=/etc/ssl/myapp.crt
```

You can even use the first_found lookup to establish fallback behavior.

**Comment by ohmer1** [comment]
Hi,

Yeah I know it can be done with little work, but we could also say that with host_vars. I think this is still an useful feature.

**Comment by sivel** [comment]
We have recently discussed this feature internally and have decided against extending the search path to inventory directories.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
