### ISSUE TITLE
Task retries has no default

### ISSUE THREAD

**Issue by jarrpa** [ansible/ansible#17695]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/task.py#L86
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

None
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When trying to run a task as a Do-Until loop, ansible errors out if you don't specify a "retries" value. Per the documentation at http://docs.ansible.com/ansible/playbooks_loops.html#do-until-loops, this should be 3.
##### STEPS TO REPRODUCE

Define a task with and "until" condition and no "retries" condition.
##### EXPECTED RESULTS

"retries" should default to 3.
##### ACTUAL RESULTS

```
TASK [Configure Gluster volumes.] **********************************************
task path: /home/jrivera/projects/github/storhaug/vagrant-ansible/playbooks/storhaug.yml:126
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 96, in run
    item_results = self._run_loop(items)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 252, in _run_loop
    res = self._execute(variables=task_vars)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 427, in _execute
    retries = self._task.retries + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

fatal: [ganesh]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Comment by ssbarnea** [comment]
I totally agree that retries should have an usable default value so we can use `until` without `retries`. I don't mind the proposes value of `3`.
