### ISSUE TITLE
$FILE doesn't work with_items

### ISSUE THREAD

**Issue by jkleint** [ansible/ansible#1769]
Maybe I'm doing something wrong, but in both release0.9 and f2893b6418 I can't seem to make `$FILE` work with `with_items`.

```

---
- hosts: localhost
  tasks:
  - debug: msg="$FILE(/etc/$item)"
    with_items: [motd, issue]
```

```
$ ANSIBLE_NOCOWS=1 ansible-playbook file.yml

PLAY [localhost] ********************* 

GATHERING FACTS ********************* 
ok: [localhost]
ERROR: /etc/$item does not exist
```

:(

The example at http://ansible.cc/docs/playbooks2.html#getting-values-from-files doesn't seem to work either (even after inserting a missing colon ;).

...And $PIPE doesn't work either, so maybe this is the same as #1729?

**Comment by dhozac** [comment]
It's due to the task lacking a name. I'm not sure how we want this to work, @mpdehaan, should we just ignore templating the lookup plugin call if there is an error (in some cases, like the name), leaving $FILE(...) as is?

**Comment by mpdehaan** [comment]
Curious on how it's due to the task lacking a name?   (You may very well be
right, just not looking ATM)

**Comment by dhozac** [comment]
The task name templating doesn't have access to $item (as the name is global for all hosts), and it defaults to the action. So combine the two and you get a name that will throw errors from the lookup plugin.

**Comment by mpdehaan** [comment]
yeah.

ideally all the lookup plugin stuff should probably be throwing typed exceptions and the template code could just refuse to fully template those out, but that gets messy as in some cases we do want those errors to surface.

Indeed, the task name is never going to have access to item, but we probably shouldn't suspect users to need to understand that and it should just show it templated as far as it can.

**Comment by dhozac** [comment]
An argument to the templating functions whether lookup plugin exceptions are fatal (true in the action templating) should be an easy thing to do, if that sounds good to you.

**Comment by mpdehaan** [comment]
yeah that sounds ok.   thanks!
