### ISSUE TITLE
Child group cannot override group_vars variables of parent group in the inventory file

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#17703]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Parsing of the inventory
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel dde7c11713) last updated 2016/09/22 14:49:27 (GMT +200)
```

The same problem exists in `stable-2.1`.
##### SUMMARY

If you have a parent `group1` and a child group `subgroup1`, and we define a variable in `group_vars/group1`, when you try to override that variable in `subgroup1` in the inventory file, the variable won't be overridden.
##### STEPS TO REPRODUCE

Create this inventory file:

``` ini
# inventory.ini
[group1:children]
subgroup1

[subgroup1]
host1 ansible_connection=local

[subgroup1:vars]
var="Set in subgroup1"
```

define a variable `var` in `group_vars/group1`:

```
# group_vars/group1

---
var: "This is set in group1"
```

and this playbook:

``` yml
# site.yml

---
- hosts: all
  gather_facts: no
  tasks:
    - debug: var=var
```

then run:

```
ansible-playbook -i inventory.ini site.yml
```
##### EXPECTED RESULTS

The variable should be overridden and it should pring:

```
ok: [host1] => {
    "var": "Set in sbgroup1"
}
```
##### ACTUAL RESULTS

But instead the variable isn't overridden and it prints:

```
ok: [host1] => {
    "var": "Set in group1"
}
```

Just to note that if we define a variable in `group_vars/subgroup1` it does get overridden correctly. Also if we both variables are defined only in the inventory file, then the var also gets overridden. It looks like `groups_vars` has precedence to group variables defined in the inventory no matter what, but this isn't documented anywhere.

**Comment by muratdx** [comment]
I reported this same issue a while ago -- see #17361.

**Comment by jctanner** [comment]
@kustodian vars found in group_vars/\* have a higher level of precedence than vars found in the inventory file. It is documented here: http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

If you would prefer the child group vars to override the parent, please put them in a group_vars/child file or do not use group_vars at all.

**Comment by xosofox** [comment]
@jctanner doesn't this contradict the statement
> The idea here to follow is that the more explicit you get in scope, the more precedence it takes

from the docs (link you mentioned)? `group_vars/all.yml` wins over `inventory/stage/group_vars/all.yml`

I'm wondering where to put inventory specifiy variables for all hosts of a certain inventory now...
