### ISSUE TITLE
My macro does not work correctly

### ISSUE THREAD

**Issue by tlhumphrey2** [ansible/ansible#17705]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

ansible 2.1.1.0

##### CONFIGURATION
No changes to ansible.cfg

##### OS / ENVIRONMENT
Ubuntu 12.04

##### SUMMARY
Cannot get this macro to work properly. It always produces the "ANSIBLE TEMPLATE ERROR", which it after {% else %} in the macro, next.
```
{% macro mac_RequiredVar(component_name,variable) -%}
{% if hostvars[groups[component_name][0]]['variable'] is defined -%}
            {{variable}}="{{ hostvars[groups[component_name][0]]['variable'] }}"
{% else %} 
ANSIBLE TEMPLATE ERROR: NO "{{variable}}" GIVEN FOR component "{{component_name}}"
{% endif -%}
{% endmacro -%}
```
##### STEPS TO REPRODUCE
I execute using the following playbook:
```
sudo ansible-playbook -i inventories/dropzone.yml test_template.yml --extra-vars "tplate=roles/test_template/templates/dropzone.j2 tplateout=tmp/dropzone.txt"`
```
Here is my inventory fille, inventories/dropzone.yml:
```
[dropzone]
dropzone1
dropzone2

[dropzone1]
10.0.0.242

[dropzone1:vars]
directory=/var/lib/HPCCSystems/dropzone1

[dropzone2]
10.0.0.98

[dropzone2:vars]
directory=/var/lib/HPCCSystems/dropzone2
```
Here is the template,roles/test_template/templates/dropzone.j2, that uses that macro:

```
{% macro mac_RequiredVar(component_name,variable) -%}
{% if hostvars[groups[component_name][0]]['variable'] is defined -%}
            {{variable}}="{{ hostvars[groups[component_name][0]]['variable'] }}"
{% else %} 
ANSIBLE TEMPLATE ERROR: NO "{{variable}}" GIVEN FOR component "{{component_name}}"
{% endif -%}
{% endmacro -%}

{% for dz in groups['dropzone'] %}
{{ mac_RequiredVar(dz,"directory") }}
{% endfor -%}
```
Here is my playbook, test_template:
```
- hosts: localhost
  connection: local

  vars:
    tplate: templates/test-list-intersect.j2
    tplateout: tmp/test.list.intersect.txt

  roles:
    - { role: test_template }
```
Here is role roles/test_template/tasks/main.yml
```- name: Role test_template
  template:
    src: "{{ tplate }}"
    dest: "{{ tplateout }}"
```
##### EXPECTED RESULTS
Here are the expected results:
`directory="/var/lib/HPCCSystems/dropzone1"
directory="/var/lib/HPCCSystems/dropzone2"
`
##### ACTUAL RESULTS
Here are the results that I don't expect:
`ANSIBLE TEMPLATE ERROR: NO "directory" GIVEN FOR component "dropzone1"

ANSIBLE TEMPLATE ERROR: NO "directory" GIVEN FOR component "dropzone2"
`
I can get the EXPECTED RESULTS, above, if I don't use the macro, but instead put the "{% if" statement of the macro where I call the macro, above. When I do that, I replace "component_name" with "dz" and "variable" with "directory" (all double quotes omitted in code).  
```

**Comment by mkrizek** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
