### ISSUE TITLE
Using ansible from git in python3 default distros

### ISSUE THREAD

**Issue by ichundu** [ansible/ansible#17713]
##### ISSUE TYPE

- Documentation Report
##### ANSIBLE VERSION

```
cannot paste the output of “ansible --version” because it's not working
```
##### CONFIGURATION

no settings changed
##### OS / ENVIRONMENT

Arch Linux
##### SUMMARY

So, i'm trying to use ansible devel latest 2.2.0 in Arch Linux which uses python3 as the default version of python. I can't find any documentation how to use ansible from this repo in such distros. I would really like to try new features and modules of ansible on my Arch Linux machine, but can't figure out how to make this working.
The ansible stable package from official Arch repository works flawlessly.
##### STEPS TO REPRODUCE

I clone this repo, then source hacking/env-setup file. In Arch unlike other distros python commands are python (for python 3.5) and python2 (for python 2.7), so i try changing the line in hacking/env-setup file from:

```
PYTHON=$(which python 2>/dev/null || which python3 2>/dev/null)
```

to

```
PYTHON=$(which python2 2>/dev/null || which python 2>/dev/null)
```

or

```
PYTHON=$(which python2 2>/dev/null)
```

In all cases when i run:

```
ansible --version
```

or

```
ansible localhost -m ping
```

##### EXPECTED RESULTS

```
ansible 2.2.0 (devel dde7c11713) last updated 2016/09/22 15:54:54 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 0f505378c3) last updated 2016/09/22 15:54:54 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 935a3ab2cb) last updated 2016/09/22 15:54:54 (GMT +200)
  config file = /home/echundu/.ansible.cfg
  configured module search path = Default w/o overrides
```

or

```
localhost | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
```
##### ACTUAL RESULTS

```
ERROR! Unexpected Exception: No module named 'yaml'
the full traceback was:

Traceback (most recent call last):
  File "/home/ichundu/ansible/bin/ansible", line 80, in <module>
    from ansible.cli.adhoc import AdHocCLI as mycli
  File "/home/ichundu/ansible/lib/ansible/cli/__init__.py", line 28, in <module>
    import yaml
ImportError: No module named 'yaml'
```

**Comment by jctanner** [comment]
@ichundu did you install PyYAML? You need to be able to do the following with your python install before attempting to run ansible ...

```
python -c 'import yaml'
python -c 'import jinja2'
```

The full list of python libraries required is listed in this guide:
http://docs.ansible.com/ansible/intro_installation.html#running-from-source

needs_info

**Comment by ichundu** [comment]
Hi @jctanner , sorry this was an issue on my part. I already had python2-yaml and python2-jinja installed but i also needed python-yaml and python-jinja packages (python 3 versions). My problem is solved now. Thanks for the guidance!

Regards
