### ISSUE TITLE
with_first_found not skipped when "when:" conditional is false

### ISSUE THREAD

**Issue by tyll** [ansible/ansible#17725]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

with_first_found conditional
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### OS / ENVIRONMENT

Fedora 23
##### SUMMARY

tasks that are skipped because of `when: false` still fail when `with_first_found` does not find a file.
##### STEPS TO REPRODUCE

```

---
- hosts: example
  become: True
  tasks:
    - name: debug
      action: debug msg="false"
      when: false
    - name: debug
      action: debug msg="this file does not exist {{ item }}"
      with_first_found:
       - files:
          - notafile
      when: false
```
##### EXPECTED RESULTS

Should skip both tasks and not fail the second task
##### ACTUAL RESULTS

```
$ ansible-playbook firstfound.yml 

PLAY [example] *****************************************************************

TASK [setup] *******************************************************************
ok: [example]

TASK [debug] *******************************************************************
skipping: [example]

TASK [debug] *******************************************************************
fatal: [example]: FAILED! => {"failed": true, "msg": "No file was found when using with_first_found. Use the 'skip: true' option to allow this task to be skipped if no files are found"}

```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

As the documentation states, `with_` gets evaluated BEFORE `when` to enable conditional execution per loop item, as such it's evaluation cannot be conditioned to the `when`.
http://docs.ansible.com/ansible/playbooks_conditionals.html#loops-and-conditionals

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by tyll** [comment]
On Fri, Sep 23, 2016 at 08:05:06AM -0700, Brian Coca wrote:

> As the documentation states, `with_` gets evaluated BEFORE `when` to enable conditional execution per loop item, as such it's evaluation cannot be conditioned to the `when`.
> http://docs.ansible.com/ansible/playbooks_conditionals.html#loops-and-conditionals

Actually the documentation does not state this. It states that "the when
statement is processed separately for each item" and this is documented
for "with_items". There documentation about "with_first_found" does not
mention this. Also the playbook would work when "with_items" is used
instead of "with_first_found", since the when statement does not depend
on the items.

Also I do not see why it makes sense to fail in the example playbook.
The documentation about "with_items" and when makes sense, since it
allows to use the value of the item as condition in the when statement.
It would also make sense to evaluate the item created by
with_first_found to e.g. None and then check with when: whether or not
the task should be applied and only fail when the when condition is
true.

**Comment by bcoca** [comment]
The docs don't go into details, but it really is `with_` + lookup, so all loops behave the same, the only thing different is the lookup used.  So the docs and example applies to all `with_` + lookup combinations, not just 'items'.

To make as clear as possible, the default lookup is 'items', you are using 'first_found' lookup, changing the lookup does not change the `when:` to `with_` scope or interaction.

**Comment by bcoca** [comment]
Also documented here, in loops in a generic way http://docs.ansible.com/ansible/playbooks_loops.html#standard-loops
