### ISSUE TITLE
with_dict: "{{ansible_hostname}}" can't work

### ISSUE THREAD

**Issue by slan77** [ansible/ansible#17741]
##### ISSUE TYPE

- Bug Report
- Feature Idea
- Documentation Report
##### ANSIBLE VERSION

```
2.1.0.0
```
##### OS / ENVIRONMENT

Centos 6.5
##### STEPS TO REPRODUCE

```

---
  - debug: msg="{{ansible_hostname}}"

  - debug: msg="{{ item.key }}/target/{{item.value.port}}-{{version}}.{{item.key}} aaaa"
    with_dict: "{{ansible_hostname}}"

 hostname is cs1 
------
cs1:
   cs:
     port: 999
     ptype: war
   pay:
     port: 998
     ptype: jar
```

##### EXPECTED RESULTS

TASK [push_package : debug] ****************************************************
ok: [192.168.100.121] => {
    "msg": "cs1"
}

TASK [push_package : debug] ****************************************************
ok: [192.168.100.121] => (item={'value': {u'project': u'cloudstore/cloudstore-web', u'port': 8080, u'ptype': u'war'}, 'key': u'cs'}) => {
    "item": {
        "key": "cs", 
        "value": {
            "port": 999, 
            "ptype": "war"
        }
    }, 
    "msg": "cs/target/8080-1.3.cs aaaa"
}
ok: [192.168.100.121] => (item={'value': {u'project': u'pay/service', u'port': 8092, u'ptype': u'war'}, 'key': u'pay'}) => {
    "item": {
        "key": "pay", 
        "value": {
            "port": 998, 
            "ptype": "jar"
        }
    }, 

}
##### ACTUAL RESULTS

TASK [push_package : debug] ****************************************************
ok: [192.168.100.121] => {
    "msg": "cs1"
}

TASK [push_package : debug] ****************************************************
fatal: [192.168.100.121]: FAILED! => {"failed": true, "msg": "with_dict expects a dict"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/tmp/40/push_package.retry

PLAY RECAP *********************************************************************

```

```

**Comment by amenonsen** [comment]
As the error message says, `with_dict expects a dict`, and `ansible_hostname` isn't a dict, so what you tried cannot possibly work. This is not a bug.

You may want to try something like `with_dict: "{{ hostvars[inventory_hostname] }}"` or so.

**Comment by slan77** [comment]
thanks, but  "{{ hostvars[inventory_hostname] }}" not work too.
- debug: msg="inventory hostname is {{inventory_hostname}}"
- debug: msg="{{ item.key }}/target/{{item.value.port}}-{{version}}.{{item.key}} aaaa"
  with_dict: "{{ hostvars[inventory_hostname] }}"

TASK [push_package : debug] ****************************************************
ok: [cs1] => {
    "msg": "inventory hostname is cs1"
}

TASK [push_package : debug] ****************************************************
fatal: [cs1]: FAILED! => {"failed": true, "msg": "'list object' has no attribute 'port'"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/tmp/40/push_package.retry

PLAY RECAP *********************************************************************

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

@slan77 that is not a problem of the with_ nor the hostvars[inventory_hostname], but of what data you are trying to access.

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
