### ISSUE TITLE
callback plugins have vague instructions

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#17759]
##### ISSUE TYPE
- Documentation Report
##### COMPONENT NAME

callback plugin documentation
##### ANSIBLE VERSION

```
2.2
```
##### SUMMARY

The callback plugin documentation has a very high level mention of how to use callbacks, but fails to mention the specific settings you -must- use in order to make your plugin work. There is a small note stating "If your callback plugin needs to write to stdout, you should define CALLBACK_TYPE = stdout in the subclass, and then the stdout plugin needs to be configured in ansible.cfg to override the default.", but that is somewhat hidden and incomplete.

current "docs" ...
http://docs.ansible.com/ansible/intro_configuration.html#callback-plugins
http://docs.ansible.com/ansible/developing_plugins.html#callback-plugins

As a developer of a plugin, I really would have to dig into the code to see how it gates the plugins to use ...
https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/task_queue_manager.py#L177-L195

So the top stanza or first line in the docs, for developing and using callbackback plugins should be an emphasized statement such as:

**To enable/test a plugin, use ANSIBLE_CALLBACK_WHITELIST=foobarANSIBLE_STDOUT_CALLBACK=foobar ansible-playbook...**

**Comment by dharmabumstead** [comment]
Thanks for the feedback. Moved the instructions on writing to stdout up into the configuring section under its own subheading to enhance visibility.
