### ISSUE TITLE
kerberos: the specified credentials were rejected by the server, ssl: 401 Unauthorized.

### ISSUE THREAD

**Issue by ccoager** [ansible/ansible#17758]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

winrm
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
```
##### CONFIGURATION

Not aware of any changes in ansible.cfg.
Otherwise using the following in the vault besides the username/password.

```
ansible_ssh_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
```
##### OS / ENVIRONMENT

Issues with two Windows 2008R2 hosts.
##### SUMMARY

When attempting to use module win_ping against two hosts, I am getting the following error:

```
kerberos: the specified credentials were rejected by the server, ssl: 401 Unauthorized.
```
##### STEPS TO REPRODUCE

Create a vault file with the following 

```
ansible_ssh_user: user@fqdn
ansible_ssh_pass: <secret>
ansible_ssh_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
```

Create the kerberos ticket with kinit.

Execute the Ansible ping:

```
ansible windows -i hosts --ask-vault-pass -m win_ping
```
##### EXPECTED RESULTS

I expect the hosts to return a successful pong.

```
fqdn | SUCCESS => {
    "changed": false,
    "invocation": {
        "module_name": "win_ping"
    },
    "ping": "pong"
}
```
##### ACTUAL RESULTS

```
Using module file /home/ccoager/ansible/venv/lib/python2.7/site-packages/ansible/modules/core/windows/win_ping.ps1
<fqdn> ESTABLISH WINRM CONNECTION FOR USER: username@fqdn on PORT 5986 TO fqdn
fqdn | UNREACHABLE! => {
    "changed": false,
    "msg": "kerberos: the specified credentials were rejected by the server, ssl: 401 Unauthorized.",
    "unreachable": true
}
```
##### ADDITIONAL INFO

I have checked some of the obvious stuff as part of troubleshooting.  The username I am using to connect is part of the local administrators group. I have run the ConfigureRemotingForAnsible.ps1 script. I checked the A and PTR DNS records, they are correct with no duplicates.

I believe I have narrowed down the root cause.  I have this working for a few hundred hosts so this issue is specific to two hosts.  I examined the SPN records and it has additional entries for HTTP.

```
HTTP/<shortname>
http/<shortname>:80
http/<fqdn>
http/<fqdn>:80
```

I believe this is conflicting with normal connections via WinRM.  The account running on the HTTP address does not have local administrator rights so it makes sense that it is using this account instead of the one specified.  Attempting to connect using Powershell fails as well. However, if you include the New-PSSessionOption flag -IncludePortInSPN, the connection is successful. Is there an equivalent option in Ansible?
[New-PSSessionOption](https://technet.microsoft.com/en-us/library/hh849703.aspx)

**Comment by jhawkesworth** [comment]
Not dug into this yet but do you have the legacy winrm listeners set up on these boxes?. (originally winrm worked over ports 80 and 443 for http and https respectively - the legacy listeners let you connect on those ports). If so they will fail to gather facts because of a bug I introduced before I had come across the legacy listeners. Workaround  is to delete the legacy listeners if possible.

I will add some more detail when I can type on a real keyboard but if you could try deleting the legacy listeners from winrm and let me know if that fixes things I would be very grateful.

Jon

**Comment by ccoager** [comment]
If I'm looking at the correct output, it doesn't appear to be using legacy listeners, just the standard ports 5985 and 5986.

```
> winrm e winrm/config/listener
Listener
    Address = *
    Transport = HTTPS
    Port = 5986
    Hostname = <shortname>
    Enabled = true
    URLPrefix = wsman
    CertificateThumbprint = <thumbprint>
    ListeningOn = <ip>, 127.0.0.1, ::1

Listener [Source="GPO"]
    Address = *
    Transport = HTTP
    Port = 5985
    Hostname
    Enabled = true
    URLPrefix = wsman
    CertificateThumbprint
    ListeningOn = <ip>, 127.0.0.1, ::1
```

**Comment by jhawkesworth** [comment]
Ok, not that then. 

So I missed that you were getting 401 Unauthorized - setup module is irrelevant. 

I suggest doing a winrm get winrm/config on the affected machines and comparing with known good machines. 

Another thing that you can check is if the affected machines are really on the same domain that you are connecting as. I am not sure if you can connect if the machine belongs to a different domain which has a trust relationship set up.

**Comment by ccoager** [comment]
I have compared the WinRM config from a working machine to this one, they are exactly identical.  Yes, they are on the same domain as well.

I'm pretty confident that issue has to do with SPN. I cannot connect via Powershell from Windows without using that -IncludePortInSPN option.

**Comment by jhawkesworth** [comment]
Ok, so I knew nothing about SPNs but  having read 
http://blogs.iis.net/brian-murphy-booth/the-biggest-mistake-serviceprincipalname-s
and some of
https://blogs.technet.microsoft.com/askds/2008/05/29/kerberos-authentication-problems-service-principal-name-spn-issues-part-1/
and some of https://blogs.technet.microsoft.com/tristank/2006/05/08/3-simple-rules-to-kerberos-authenticationdelegation-spns/

its possible there is some magic set up, possibly to do with IIS app pools on those boxes.
It looks like setspn is a thing which may have been run on your domain controller to set up the magic, so worth having a look in AD.
Also first link seems to imply name resolution has to match up so if you 
ping somehost 
and you get back 
somehost.domain.com
then that's what needs to be in the SPN.

It certainly looks from the 3rd link that the SPN is linked with a domain account, so its possible you might be able to avoid the whole thing by connecting as a different user.

I found a few other reports of people having trouble remoting when an SPN has been set up.  
someone on this forum here - https://www.sapien.com/forums/viewtopic.php?t=4966 
-  seemed to able to workaround by using the ip instead of the hostname to connect to affected machines, although I doubt given the age of the post it was using a non-microsoft client to connect.  Still, might be worth a try.  Please can you see if this a viable workaround?  

If so we can at least document it,  which might be all we are able to do on this one since it seems the SPN mechanism is like a sort of lookup for a domain account, and therefore somewhat outside ansible or pywinrm's control.

Jon

**Comment by ccoager** [comment]
Yes, the host is running IIS. I tried using the IP address but I get the same exact error message.

**Comment by jhawkesworth** [comment]
Is using a different domain user an option?

I suggest asking on ansible-project google group in case anyone else has encountered this and has a workaround - many more people use the group than follow the ansible issue reports.

cc @nitzmahone @trondhindenes - have you encountered this situation of SPN interfering with winrm connection before?

**Comment by ccoager** [comment]
I just tried another domain account that has local admin rights, same error message.

I created a thread before I created this issue but have received no replies.
[FAILED => the username/password specified for this server was incorrect](https://groups.google.com/forum/#!topic/ansible-project/37u6k31Rxmc)

**Comment by ccoager** [comment]
Found some supporting evidence from the Powershell side.
[Can we add PSSessionOptions to the PowerShellJob.ps1 / Invoke-PsOnRemote](https://github.com/Microsoft/vsts-tasks/issues/2441)
[Cannot use PowerShell Remoting when a http/ SPN exists for target machine](https://www.reddit.com/r/PowerShell/comments/3ze9pp/cannot_use_powershell_remoting_when_a_http_spn/)

**Comment by jhawkesworth** [comment]
I can't check right now but I believe our iis app pools run as a different user from the one we connect via ansible as, so its possible that we get round it that way. Or we don't use SPNs (I am not windows domain admin).

Seems like the only option is to avoid the SPN for your ansible winrm user, although it sounds like you already tried that.

**Comment by nitzmahone** [comment]
Yeah, that makes sense- the SPN config is essentially hijacking what's required for WinRM. There are some apps that hijack the HTTP SPN so they can do Kerberos auth via IIS under a nonstandard domain account, but I haven't seen anything do that for years (I wrote one of them ca 2001). Pywinrm does support overriding the kerb hostname separately from the actual network hostname, so you might be able to do that to stuff the port in there (eg, `ansible_winrm_kerberos_hostname_override=myhost.com:80`) to get the SPNs to match. It also supports overriding the service name in the ticket (eg, `ansible_winrm_service=MYHTTP`), so if you can change the SPN WinRM wants to use (pretty sure it's possible, but not sure where to look), pywinrm will let you talk to it with the right service name.

Regardless, this appears to be a nonstandard local config issue that we likely already provide ways to work around, so I'm going to close this bug.

**Comment by ccoager** [comment]
@nitzmahone 
Can you keep the ticket open until we find resolution?

**Comment by nitzmahone** [comment]
Regardless of the success of the workaround, it's a local configuration issue (confirmed by that fact that PS remoting itself is completely broken), so not really anything Ansible can do about it beyond what I've already suggested. That's why I've closed the issue.

**Comment by ccoager** [comment]
I wouldn't call it a configuration issue, it is necessary for IIS to operate with kerberos authentication. Also, it does work with Powershell when using the -IncludePortInSPN PSSessionOption.

I'm willing to research the WinRM settings but will need to do some research.

**Comment by ccoager** [comment]
I was able to fix the issue. I've submitted a pull request to pywinrm:

[Added service to HTTPKerberosAuth #144](https://github.com/diyan/pywinrm/pull/144)

You also need to add the following option in your vault or via command line:

```
ansible_winrm_service: HOST
```

**Comment by nitzmahone** [comment]
Nice- clearly I missed the service override during the requests refactor in
pywinrm... I'm planning on doing a pass on pywinrm stuff as soon as ansible
2.2 stabilizes, so I'll include this in the next pywinrm release.

Thanks!

**Comment by ccoager** [comment]
@nitzmahone
Does it make sense to change the default service from HTTP to HOST? I can't think of it breaking with HOST but it could break with HTTP with the issue I've experienced. At least with Ansible anyways, not sure what other use cases there are with pywinrm.

**Comment by nitzmahone** [comment]
Hmm, good question. I'd have to talk to the Microsoft gang about that and
see what they think...

**Comment by sqldiablo** [comment]
I had this exact issue as well, and after applying the changes to pywinrm and adding the ansible_winrm_service option, it's working now. Thanks, ccoager. The sooner we can get this baked into pywinrm and ansible, the better. :-)

Worth noting, I'm using the HOST option for all of my Windows boxes now, and so far it's working without issue for all of the various OS versions, etc.

**Comment by drehelis** [comment]
Just want to drop in and say I've experienced the same behavior and found out my target host (named HOST01 for example) have had SPN configured on a totally different host with the following:
HTTP/HOST01
HTTP/HOST01.corp.domain
Removing those from that specific host fixed the issue for me.
