### ISSUE TITLE
Using an empty inventory group no longer noops and instead results in error.

### ISSUE THREAD

**Issue by cboylan** [ansible/ansible#17762]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ansible
##### ANSIBLE VERSION

Old "good/desired" behavior observed with ansible 2.0.0.2 as installed via `pip install ansible==2.0.0.2`.

New "bad/undesired" behavior observed with ansible 2.1.1.0 as installed via `pip install ansible==2.1.1.0`.
##### CONFIGURATION

No changes made.
##### OS / ENVIRONMENT

Ubuntu Xenial 16.04
##### SUMMARY

If you run ansible against an empty inventory group this now results in an error and failure. Old behavior was to noop and do nothing.
##### STEPS TO REPRODUCE

```
# Install ansible 2.1.1.0
virtualenv /tmp/ansible
# note the paramiko version is fixed to avoid needing system packages.
/tmp/ansible/bin/pip install paramiko==1.16.0 ansible==2.1.1.0
export ANSIBLE=/tmp/ansible/bin/ansible
echo "[primary]" > /tmp/inventory
echo "localhost ansible_connection=local host_counter=1" >> /tmp/inventory
echo "[subnodes]" >> /tmp/inventory
$ANSIBLE subnodes -f 5 -i "/tmp/inventory" -m copy -a "src='/tmp/inventory' dest='/tmp/foo'"
```
##### EXPECTED RESULTS

I expect to continue to have ansible noop on empty groups.
##### ACTUAL RESULTS

`ERROR! Specified hosts and/or --limit does not match any hosts`

**Comment by bcoca** [comment]
this is not an issue of an empty group, but of an empty host list for the play,this was always a failure. The only difference that I see is that it shows 'error' instead of warning:

in 2.0

```
[WARNING]: provided hosts list is empty, only localhost is available
```

in 2.1/2.2

```
ERROR! Specified hosts and/or --limit does not match any hosts
```

**Comment by cboylan** [comment]
I would argue it wasn't a failure before. The exit code was zero. Warning in that case seems reasonable to me in case its not what someone wanted. However changing it to an error breaks backward compatibility with the behavior that was there before. The difference between warning, return 0 and error return non zero is pretty significant.

Not sure what assertions ansible makes about its warnings as far as if and when they may become errors.
