### ISSUE TITLE
ansible_fact_caching not honored in extra vars

### ISSUE THREAD

**Issue by duck-rh** [ansible/ansible#17790]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

facts caching
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /home/duck/tests/ansible.cfg
  configured module search path = Default w/o overrides
```

This is rc3.
##### CONFIGURATION

Set the role path and activatd JSON facts caching.
##### OS / ENVIRONMENT

From Debian unstable to CentOS 7.2.
##### SUMMARY

Setting the variable in extra vars has no effect
##### STEPS TO REPRODUCE

In projects's ansible.cfg:

```
fact_caching = jsonfile
fact_caching_connection = ./facts_cache
fact_caching_timeout = 86400
```

I want to disable fact caching temporarily using the extra vars like this:

```
ansible-playbook -e @vars.yml deploy.yml
```

with vars.yml:

```

---
ansible_fact_caching: memory
```
##### EXPECTED RESULTS

the facts cache directory is not created or updated.
##### ACTUAL RESULTS

the facts cache directory is used (I purged it and it kept being recreated).

I can make it work using an envver:

```
ANSIBLE_CACHE_PLUGIN=memory ansible-playbook -e deploy.yml
```

(btw, having a different naming make things painful, UTSL is not very user friendly)

As I'm using the YAML extra vars for other settings, which are generated, it would really ease things if I did not have to have an exception for this specific setting. Anyway there is no reason this variable is an exception, and if there's a technical impossibility it should be documented.

**Comment by bcoca** [comment]
extra vars are NOT configuration, they are variables.

Entries in ansible.cfg are not available as vars normally, there are some 'connection variables' that can override these default settings, but they are specific to communication with hosts and not generic as options to override any config.

**Comment by duck-rh** [comment]
Ok, sorry for the semantic confusion, but you're eluding the problem. Why some can be modified with -e and some not?
As said, there may be valid technical difficulties, but it should at least be documented.
For example setting ansible_ssh_common_args or ansible_become\* or ansible_pipelining… works perfectly, so why not this one?

**Comment by bcoca** [comment]
If you look, those are specifically documented and they are 'host connection variables', which are normally set in inventory, but extra vars have precedence and they are still vars. The configurations are just setting 'defaults' in these cases.  http://docs.ansible.com/ansible/playbooks_variables.html

Most configurations do not deal with host connections and should not be "overridable" via this method, they normally deal with scopes in which a host cannot and should not have any influence. In the configuration docs you should see any variables that are associated with that configuration:
http://docs.ansible.com/ansible/intro_configuration.html

**Comment by duck-rh** [comment]
Thanks for your explanation, it's clearer now. I think the doc was improved on the "connection variables" aspect since last time I read it :-).

So in this case what I would need is a mean to override a subset of the settings without messing with the settings files. I could use ANSIBLE_CONFIG but as the documentation says « Settings in files are not merged. » and that's what I would need in this case. So something like --extra-settings with an input similar to --extra-vars would be welcome.

So this is not a bug indeed, but a feature request. I'll open a new BR for this, it would be clearer.
