### ISSUE TITLE
Permit multiples modules directorys

### ISSUE THREAD

**Issue by davixx** [ansible/ansible#1779]
Hi all,

First, please excuse my bad english, and also the fact i maybe ask something is already exists, or already will.

Actually, it seems that we can change the modules directory by using --module-path=

But i think it would be great to be able to stack one or more directory. Also the common goal is to have the default module directory provided by ansible package, and one more for the homemade/local modules.

Thanks for your time,

**Comment by dhozac** [comment]
Each playbook directory can have a library subdirectory containing local modules. In addition, the --module-path argument is a colon-separated list of paths, all of which will be searched in order to find a module, so this very much already exists.

**Comment by davixx** [comment]
Thanks dhozac :+1:

IMHO, Should the man page have to inform ansible user that :

"In addition, the --module-path argument is a colon-separated list of paths, all of which will be searched in order to find a module "
