### ISSUE TITLE
Callback plugins duped in docs

### ISSUE THREAD

**Issue by smiller171** [ansible/ansible#17795]
##### ISSUE TYPE
- Documentation Report
##### COMPONENT NAME

Plugin development docs
##### ANSIBLE VERSION

```
N/A
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Callback plugins have two sections in the plugin dev docs, with mostly the same info.
##### STEPS TO REPRODUCE

Go to http://docs.ansible.com/ansible/developing_plugins.html and observe the documentation issue.
##### EXPECTED RESULTS

One section on callback plugins
##### ACTUAL RESULTS

Two sections on callback plugins

**Comment by dharmabumstead** [comment]
Fixed. Thanks!
