### ISSUE TITLE
template metadata 

### ISSUE THREAD

**Issue by cocoy** [ansible/ansible#178]
Hmm.. On library/template: 

if not os.path.exists(metadata): 

always returns true..

Seems path not found because of  defined metadata at runner.py
metadata = '~/.ansible/setup'

**Comment by mpdehaan** [comment]
good catch, this  should use os.path.expanduser ...

**Comment by jhoekx** [comment]
This was already fixed in integration  by 9e0b7ee6292afaf0568a7795bed46b99e9a7e7e4 and all code in there has been removed by the recent refactoring.

**Comment by mpdehaan** [comment]
this is true, integration branch doesn't have this issue at all anymore.   Want to test the integration branch early?  :)

This release is due Monday, FWIW
