### ISSUE TITLE
--limit inconsitency

### ISSUE THREAD

**Issue by jlec** [ansible/ansible#17805]
When using `--limit` I get inconsistent behaviour. See following inventory

```
[dev-blades-1]
lc3n1.ukapd.astrazeneca.net bond_ip=172.24.6.131
lc3n2.ukapd.astrazeneca.net bond_ip=172.24.6.132
lc3n3.ukapd.astrazeneca.net bond_ip=172.24.6.133
lc3n4.ukapd.astrazeneca.net bond_ip=172.24.6.134

[dev-blades-2]
lc3n5.ukapd.astrazeneca.net bond_ip=172.24.6.135
lc3n6.ukapd.astrazeneca.net bond_ip=172.24.6.136
lc3n7.ukapd.astrazeneca.net bond_ip=172.24.6.137
lc3n8.ukapd.astrazeneca.net bond_ip=172.24.6.138

[dev-blades-3]
lc3n9.ukapd.astrazeneca.net bond_ip=172.24.6.139
#lc3n10.ukapd.astrazeneca.net bond_ip=172.24.6.140
lc3n11.ukapd.astrazeneca.net bond_ip=172.24.6.141
lc3n12.ukapd.astrazeneca.net bond_ip=172.24.6.142
lc3n13.ukapd.astrazeneca.net bond_ip=172.24.6.143

[dev-blades-4]
lc3n14.ukapd.astrazeneca.net bond_ip=172.24.6.144
lc3n15.ukapd.astrazeneca.net bond_ip=172.24.6.145
lc3n16.ukapd.astrazeneca.net bond_ip=172.24.6.146
lc3n17.ukapd.astrazeneca.net bond_ip=172.24.6.147

[dev-blades-5]
lc3n18.ukapd.astrazeneca.net bond_ip=172.24.6.148
lc3n19.ukapd.astrazeneca.net bond_ip=172.24.6.149
lc3n20.ukapd.astrazeneca.net bond_ip=172.24.6.150
lc3n21.ukapd.astrazeneca.net bond_ip=172.24.6.151
lc3n22.ukapd.astrazeneca.net bond_ip=172.24.6.152

[dev-blades-6]
lc3n23.ukapd.astrazeneca.net bond_ip=172.24.6.153
lc3n24.ukapd.astrazeneca.net bond_ip=172.24.6.154
#lc3n25.ukapd.astrazeneca.net bond_ip=172.24.6.155
lc3n26.ukapd.astrazeneca.net bond_ip=172.24.6.156
#lc3n27.ukapd.astrazeneca.net bond_ip=172.24.6.157
lc3n28.ukapd.astrazeneca.net bond_ip=172.24.6.158

[dev-blades-left:children]
dev-blades-1
dev-blades-2

[dev-blades-middle:children]
dev-blades-3
dev-blades-4

[dev-blades-right:children]
dev-blades-5
dev-blades-6

[dev-blades:children]
dev-blades-left
dev-blades-middle
dev-blades-right
```

Running 
`ansible-playbook site.yml -t netdata --inventory inventory.dev --limit lc3n[1-9].ukapd.astrazeneca.net --become --ask-become-pass` acts on blades 1-9.

```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [lc3n9.ukapd.astrazeneca.net]
ok: [lc3n1.ukapd.astrazeneca.net]
ok: [lc3n3.ukapd.astrazeneca.net]
ok: [lc3n4.ukapd.astrazeneca.net]
ok: [lc3n5.ukapd.astrazeneca.net]
ok: [lc3n7.ukapd.astrazeneca.net]
ok: [lc3n6.ukapd.astrazeneca.net]
ok: [lc3n8.ukapd.astrazeneca.net]
ok: [lc3n2.ukapd.astrazeneca.net]
```

whereas `ansible-playbook site.yml -t netdata --inventory inventory.dev --limit lc3n[21:28].ukapd.astrazeneca.net --become --ask-become-pass` only uses 1, 2 & 8.

```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [lc3n1.ukapd.astrazeneca.net]
ok: [lc3n8.ukapd.astrazeneca.net]
ok: [lc3n2.ukapd.astrazeneca.net]
```

Lastly if I use multiple groups, like `ansible-playbook blade-stage1.yml --inventory inventory.dev --limit dev-blades-[1:3] --user root --ask-pass` I get

```
ERROR! Specified --limit does not match any hosts
```

To me they all seem to be valid syntaxes
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

cli
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /home/kbpd943/src/az/cluster-plays/ansible.cfg
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

```
[defaults]
ansible_managed = Ansible managed: {file} by {uid} on {host}
remote_user = clusteradmin
become_ask_pass = False
ask_sudo_pass = False
ask_vault_pass = False
scp_if_ssh = False
nocolor = no
force_color = 1
forks = 128
retry_files_enabled = True
retry_files_save_path = ~/.ansible-retry
[ssh_connection]
pipelining = True
```

**Comment by rgroten** [comment]
In the case of `--limit dev-blades-[1:3]` I think Ansible is treating the suffix as an array index.
For example: `--limit dev-blades-2[0:1]` would return

> lc3n5.ukapd.astrazeneca.net
> lc3n6.ukapd.astrazeneca.net

As for `--limit lc3n[21:28].ukapd.astrazeneca.net`
Would this work for you instead? `--limit lc3n2[18].ukapd.astrazeneca.net`

**Comment by jlec** [comment]
if the `[]` is really meant as python list slicing and not logical ranges, then using groups makes more sense. But to me this seems to be a quite convenient feature having logical ranges.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Ranges in hostnames ( [1:3] ) are allowed in the inventory but are not part of host patterns which is what --limit takes (same as hosts:  in play).

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
