### ISSUE TITLE
unify the lists of strings/values that are booleans (ie, 'yes','on','true','TRUE','y','1', etc)

### ISSUE THREAD

**Issue by alikins** [ansible/ansible#17815]
- Bug Report
##### COMPONENT NAME

N/A
##### ANSIBLE VERSION

```
ansible 2.2.0 (skip_test_aws_on_no_boto d16715bad3) last updated 2016/09/29 13:25:16 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 7808f42aff) last updated 2016/09/29 09:37:49 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 881d2f95a8) last updated 2016/09/29 09:37:49 (GMT -400)
  config file = /home/adrian/.ansible.cfg
  configured module search path = Default w/o overrides


```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

We have multiple places where we define what strings or values that map to booleans. 
We should unify them and verify their usage where possible.

**examples:**

``` yaml
utils.boolean.py: def booleans()
ansible.module_utils.basic: BOOLEANS
lib/ansible/constants.py:33: BOOL_TRUE = frozenset([ "true", "t", "y", "1", "yes", "on" ])
lib/ansible/plugins/action/set_fact.py:47
lib/ansible/modules/core/network/nxos/nxos_interface.py:294 BOOLEANS_TRUE = ['yes', 'on', '1', 'true', 'True', 1, True]
lib/ansible/plugins/action/net_template.py:31:BOOLEANS = ('true', 'false', 'yes', 'no')
```
- Gundalow - tweaked formatting

**Comment by bcoca** [comment]
At most we should have 2, one for 'ansible core' and another for modules, but we probably do even just one.

**Comment by gundalow** [comment]
@Qalthos Can you please look at `lib/ansible/plugins/action/net_template.py`. Thanks

**Comment by Qalthos** [comment]
I _think_ that with 8d0418f7c10875172ca87047a10496ac96004449, this issue is finished, can someone confirm? @alikins?
