### ISSUE TITLE
Yum module fails on 'yum-*' packages on RHEL6

### ISSUE THREAD

**Issue by c0rner** [ansible/ansible#1781]
Using the yum module to manage yum plugins will always fail with an error message stating the package does not exist.

Example action:
action: yum pkg=yum-plugin-security state=latest

Renaming the module will resolve the problem so there seems to be a conflict, possibly in YumBase()?

Commit used: 89dab0b12c6642041834ad6d534d5671770eeae0

**Comment by skvidal** [comment]
I cannot replicate this behavior on rhel6 using ansible from git

Here's the playbook I'm using:

---
- name: test
  hosts: hostname
  user: root
  
  tasks:
  - name: yum install yum-plugin-security
    action: yum name=yum-plugin-security state=latest
  - name: yum remove yum-plugin-security
    action: yum name=yum-plugin-security state=absent

Can you give more information? Specifically can you run with -vvv?

**Comment by c0rner** [comment]
Ok, thats odd.  I will make sure to set up a fresh new rhel6 and try this again.  Below you can find the script I used to find out what was going wrong.  Just to be clear the issue seems to be in the yum library but will break things in ansible.

Also, it works for me when the packages are already installed, if you uninstall and try again it will fail.

=[yum]========================================
#!/usr/bin/python
import os
import sys
import yum

my = yum.YumBase()
pkgs = my.returnPackagesByDep("yum-utils") + my.returnInstalledPackagesByDep("yum-utils")
for pkg in pkgs:
   print "- %s: %s" % (pkg, pkg.summary)
=[yum-end]=======================================

[root@rhel6 tmp]# python yum
Loaded plugins: product-id, rhnplugin
[root@rhel6 tmp]# mv yum yum2
[root@rhel6 tmp]# python yum2
Loaded plugins: product-id, rhnplugin
Repository rhel-source is listed more than once in the configuration
Repository rhel-source-beta is listed more than once in the configuration
- yum-utils-1.1.30-10.el6.noarch: Utilities based around the yum package manager
- yum-utils-1.1.30-14.el6.noarch: Utilities based around the yum package manager
- yum-utils-1.1.26-11.el6.noarch: Utilities based around the yum package manager
- yum-utils-1.1.30-6.el6.noarch: Utilities based around the yum package manager

**Comment by skvidal** [comment]
the plugin I installed had never been installed on those systems. these were (relatively) pristine cloud instances.

2 bits of information that would be helpful
1. is yum-utils installed on the system(s) showing the issue?
2. are you running ansible from git and if not which version of ansible are you running?

**Comment by c0rner** [comment]
Answers:
1. No, yum-utils was just a packaged used for testing. Basically anything 'yum-*' will fail.
2. As fresh as it gets from git

I''ve retested this on a completely fresh system with SELinux in enforcing mode. The system is installed with 'nobase', so as clean as it gets.

See below for new tests using the previously mentioned python script (although with a new plugin this time).

[root@localhost tmp]# cat /etc/issue
Red Hat Enterprise Linux Server release 6.3 (Santiago)
Kernel \r on an \m

[root@localhost tmp]# yum update -y
Loaded plugins: product-id, rhnplugin, security, subscription-manager
Updating certificate-based repositories.
Unable to read consumer identity
Setting up Update Process
No Packages marked for Update
[root@localhost tmp]# yum list installed | grep yum
Unable to read consumer identity
yum.noarch                      3.2.29-30.el6              @rhel-x86_64-server-6
yum-metadata-parser.x86_64      1.1.2-16.el6               @anaconda-RedHatEnterpriseLinux-201111171049.x86_64/6.2
yum-plugin-security.noarch      1.1.30-14.el6              @rhel-x86_64-server-6
yum-rhn-plugin.noarch           0.9.1-40.el6               @rhel-x86_64-server-6
[root@localhost tmp]# python yum
Loaded plugins: product-id, rhnplugin
[root@localhost tmp]# mv yum yum2
[root@localhost tmp]# python yum2
Loaded plugins: product-id, rhnplugin
- yum-plugin-downloadonly-1.1.30-10.el6.noarch
- yum-plugin-downloadonly-1.1.30-14.el6.noarch
- yum-plugin-downloadonly-1.1.26-11.el6.noarch
- yum-plugin-downloadonly-1.1.30-6.el6.noarch

**Comment by skvidal** [comment]
I've tested this now with both yum-utils installed (repoquery-present) and yum-utils uninstalled (repoquery absent) and I cannot replicate the behavior you're seeing. Nothing in the yum module treats the pkg name yum\* special at all.

I don't understand the relevance of the python script you're running.

Again -please attach the output of ansible-playbook -vvv for this playbook.

**Comment by c0rner** [comment]
The python script replicates what the yum module does in what_provides() which is where things break as neither my.returnPackagesByDep() nor my.returnInstalledPackagesByDep() return any packages.  As soon as you rename the yum module (or my script if you will) it works just fine.

---

ansible-playbook -vvv getpatches.yml -i "10.25.207.232," -k
SSH password: 

PLAY [all] ********************\* 

GATHERING FACTS ********************\* 
<10.25.207.232> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO 10.25.207.232
<10.25.207.232> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1355762665.18-70412047048845 && echo $HOME/.ansible/tmp/ansible-1355762665.18-7041204704884
5'
<10.25.207.232> REMOTE_MODULE setup <10.25.207.232> PUT /tmp/tmpmOawZ3 TO /root/.ansible/tmp/ansible-1355762665.18-70412047048845/setup
<10.25.207.232> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-1355762665.18-70412047048845/setup; rm -rf /root/.ansible/tmp/ansible-1355762665.18-
70412047048845/ >/dev/null 2>&1'
ok: [10.25.207.232]
10.25.207.232: importing vars/RedHat.yml

TASK: [Verify yum security plugin is installed] ********************\* <10.25.207.232> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO 10.25.207.232
<10.25.207.232> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1355762666.73-235341325676478 && echo $HOME/.ansible/tmp/ansible-1355762666.73-235341325676
478'
<10.25.207.232> REMOTE_MODULE yum pkg=yum-plugin-security state=latest
<10.25.207.232> PUT /tmp/tmp5lfVhr TO /root/.ansible/tmp/ansible-1355762666.73-235341325676478/yum
<10.25.207.232> EXEC /bin/sh -c '/usr/bin/python -tt /root/.ansible/tmp/ansible-1355762666.73-235341325676478/yum; rm -rf /root/.ansible/tmp/ansible-1355762666.
73-235341325676478/ >/dev/null 2>&1'
ok: [10.25.207.232] => {"changed": false, "msg": "", "rc": 0, "results": ["All packages providing yum-plugin-security are up to date"]}

TASK: [Verify yum download plugin is installed] ********************\* 
<10.25.207.232> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO 10.25.207.232
<10.25.207.232> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1355762668.31-53806992861938 && echo $HOME/.ansible/tmp/ansible-1355762668.31-5380699286193
8'
<10.25.207.232> REMOTE_MODULE yum pkg=yum-plugin-downloadonly state=latest
<10.25.207.232> PUT /tmp/tmpbQfDX4 TO /root/.ansible/tmp/ansible-1355762668.31-53806992861938/yum
<10.25.207.232> EXEC /bin/sh -c '/usr/bin/python -tt /root/.ansible/tmp/ansible-1355762668.31-53806992861938/yum; rm -rf /root/.ansible/tmp/ansible-1355762668.3
1-53806992861938/ >/dev/null 2>&1'
failed: [10.25.207.232] => {"changed": false, "failed": true, "rc": 0, "results": []}
msg: No Package matching 'yum-plugin-downloadonly' found available, installed or updated

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************\* 
10.25.207.232                  : ok=2    changed=0    unreachable=0    failed=1

**Comment by skvidal** [comment]
This is why I asked if you had yum-utils installed - not about the plugins - about yum-utils. If yum-utils is installed then repoquery is run. Only if it is not installed does your script make any sense.

Could you install yum-utils and re-run the playbook and let me know what results you get?

**Comment by c0rner** [comment]
With yum-utils installed it works! My test-script work as well.. now I am confused though as things work just fine when the executing process is not named 'yum' with or without yum-utils.

For now 'yum-utils' looks to be a requirement to get things working though..  which means it needs to be in the kickstart in my case.

**Comment by skvidal** [comment]
I've tested it both with and without yum-utils. So it is not a requirement. I'm not sure what your situation is though.

**Comment by c0rner** [comment]
My test-system was installed using 'nobase' + man, bind-utils, yum-security, openssh-server, openssh-client, ntp, wget, perl. Fully patched.

At first I thought it had to do with us having an additional repo in '/etc/yum.repos.d' but removing all repo files did still produce the same results.

I will submit a bug to rh and see what that gives.  Btw, I'm not seeing this on CentOS using the same kickstart settings so it is only affecting rhel.

Thanks for your efforts, I'm not sure how to proceed from here.  There is definitely something very odd going on but installing yum-utils is good enough work around for now.  Still.. it would be nice to figure out exactly what is going on..
