### ISSUE TITLE
Ssh plugin is not working with python3

### ISSUE THREAD

**Issue by unai-ttxu** [ansible/ansible#17832]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ssh.py from plugins/connection module
##### ANSIBLE VERSION

```
ansible 2.2.0
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Centos 7 with Python 3.4.3
##### SUMMARY

When you try lo login into a server, the user name generated is not valid. There is a duplicated call to the `to_bytes` method when applying the `ANSIBLE_REMOTE_USER`.
##### STEPS TO REPRODUCE

When we try to make a ping to our openstack group:

```
ansible openstack  -m ping 
```

Where our `/etc/ansible/hosts` is:

```
[openstack]
bootstrap ansible_host=10.200.0.130 ansible_user=cloud-user ansible_ssh_private_key_file=/home/uarrien/Documents/stratio/certs/testKeyPair.pem
```
##### EXPECTED RESULTS

```
bootstrap | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
```
##### ACTUAL RESULTS

```
bootstrap | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh.",
    "unreachable": true
}
```

If we execute the command verbose:

```
No config file found; using defaults
Using module file /root/.pyenv/versions/3.4.3/lib/python3.4/site-packages/ansible/modules/core/system/ping.py
<10.200.0.130> ESTABLISH SSH CONNECTION FOR USER: cloud-user
<10.200.0.130> SSH: EXEC ssh -q -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/uarrien/Documents/stratio/certs/testKeyPair.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User=b'"'"'cloud-user'"'"'' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.200.0.130 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1475234121.3512669-205100461461219 `" && echo ansible-tmp-1475234121.3512669-205100461461219="` echo $HOME/.ansible/tmp/ansible-tmp-1475234121.3512669-205100461461219 `" ) && sleep 0'"'"''
bootstrap | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh.",
    "unreachable": true
}
```

We can see that the User is not well formed:

`'User=b'"'"'cloud-user'"'"''`

To fix this, we should remove the `to_bytes` call from the following line:

https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/ssh.py#L197

We have tested with the following line of code and it works properly:

`("-o", "User={0}".format(self._play_context.remote_user))`

**Comment by jcortejoso** [comment]
This problem is also blocking us. I will try this fix.

**Comment by jctanner** [comment]
@unai-ttxu How did you install 3.4 on el7 and how did you configure ansible to use it?

needs_info

**Comment by abadger** [comment]
@unai-ttxu I think you've got the right general idea there but your change will break cornercases on python2.  Let me take a look.

**Comment by unai-ttxu** [comment]
@jctanner To test it, I use the following [docker container image](https://hub.docker.com/r/unaittxu/ansible/) where the image is build from the CentOS 7 one. Python 3.4.3 is installed using pyenv. Also ansible has been installed using pip `pip install git+git://github.com/ansible/ansible.git@devel`. No ansible.cfg is created within /etc/ansible, so ansible is using defaults configuration file.

@abadger Perfect! Ask me if you need any more info.

**Comment by abadger** [comment]
@unai-ttxu Okay, I think that #17860, now merged to devel, should fix this.  I started off with just the simple fix of making sure those particular strings were both byte type but then ended up making a bunch of cleanups so that all of the arguments that we're building up are byte type... Saves from having to call to_bytes() on every argument at the end of the function.

If you find it doesn't fix your case feel free to let me know (with a new bug and pinging me on irc.freenode.net, irc nick abadger1999 if you're on there.)

**Comment by unai-ttxu** [comment]
@abadger Tested and it is working perfect! Thanks for the quickness!
