### ISSUE TITLE
handler listen: notify a undefined handler must not be an error

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#17848]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

handler listen
##### ANSIBLE VERSION

```
2.2
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

With the new feature of handler listen, a common use case is to notify an inexistent handler. However, currently Ansible expects the handler to be there and shows an error.

The error should be replaced with a warning so potential issues with typos in handler names and listen can be identified.
##### STEPS TO REPRODUCE

``` yaml

---
- name: test handlers listen
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: notify some handlers
      command: echo foo
      notify:
        - notify_listen_not_there
```
##### EXPECTED RESULTS

playbook gets executed with a warning.
##### ACTUAL RESULTS

```
 $ ansible-playbook test_handlers_listen2.yml -vv
No config file found; using defaults
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: test_handlers_listen2.yml ********************************************
1 plays in test_handlers_listen2.yml

PLAY [test handlers listen] ****************************************************

TASK [notify some handlers] ****************************************************
task path: /home/resmo/Projects/resmo/ansible/test/integration/test_handlers_listen2.yml:6
ERROR! The requested handler 'notify_listen_not_there' was found in neither the main handlers list nor the listening handlers list

```

**Comment by bcoca** [comment]
So after discusisng in IRC we all agreed that a missing handler should by default be an error, as such this is not a bug.

In any case I added PR #17902 to allow a user to toggle into a warning for those that have that preference.
