### ISSUE TITLE
local_action does not use parent interpreter or ansible_python_interpreter

### ISSUE THREAD

**Issue by jkleint** [ansible/ansible#1784]
I'm trying to run a playbook in local mode on RHEL 5, so I've installed `python26` and I use that to run `ansible-playbook`.  However, Ansible is still trying to use `/usr/bin/python` (2.4) for `local_action`, even if I give it an `ansible_python_interpreter`.  (Before you ask, I use this playbook in local and remote modes.) This is with 0.9 and d34e320e1. 

```

---
- hosts: all
  sudo: True

  tasks:
  - local_action: shell ps -fp "$PPID"
```

```
# python26 ansible-playbook -vvv -i hosts -l localhost -c local cmd.yml

PLAY [all] ********************* 

GATHERING FACTS ********************* 
<localhost> EXEC mkdir -p $HOME/.ansible/tmp/ansible-1355852633.6-30829657934999 && echo $HOME/.ansible/tmp/ansible-1355852633.6-30829657934999
<localhost> REMOTE_MODULE setup 
<localhost> PUT /tmp/tmpwRypE5 TO /root/.ansible/tmp/ansible-1355852633.6-30829657934999/setup
<localhost> EXEC sudo -u root -s /usr/bin/python /root/.ansible/tmp/ansible-1355852633.6-30829657934999/setup; rm -rf /root/.ansible/tmp/ansible-1355852633.6-30829657934999/ >/dev/null 2>&1
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1355852633.6-30829657934999/setup", line 63, in ?
    import simplejson as json
ImportError: No module named simplejson


TASK: [command which python] ********************* 
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ********************* 
localhost                      : ok=0    changed=0    unreachable=0    failed=1    
```

It would be nice if local mode used the same interpreter that invoked `ansible-playbook`.

Even if I specify `ansible_python_interpreter`, it's not respected for `local_action`:

```
# python26 ansible-playbook -vvv -i hosts -l localhost -c local -e ansible_python_interpreter=/usr/bin/python26 cmd.yml

PLAY [all] ********************* 

GATHERING FACTS ********************* 
<localhost> EXEC mkdir -p $HOME/.ansible/tmp/ansible-1355854087.59-257363287045947 && echo $HOME/.ansible/tmp/ansible-1355854087.59-257363287045947
<localhost> REMOTE_MODULE setup 
<localhost> PUT /tmp/tmpdUyMYx TO /root/.ansible/tmp/ansible-1355854087.59-257363287045947/setup
<localhost> EXEC sudo -u root -s /usr/bin/python26  /root/.ansible/tmp/ansible-1355854087.59-257363287045947/setup; rm -rf /root/.ansible/tmp/ansible-1355854087.59-257363287045947/ >/dev/null 2>&1
ok: [localhost]

TASK: [shell ps -fp "$PPID"] ********************* 
<127.0.0.1> EXEC mkdir -p $HOME/.ansible/tmp/ansible-1355854088.44-19760854662405 && echo $HOME/.ansible/tmp/ansible-1355854088.44-19760854662405
<127.0.0.1> REMOTE_MODULE command ps -fp "$PPID" #USE_SHELL
<127.0.0.1> PUT /tmp/tmpkZOs3j TO /root/.ansible/tmp/ansible-1355854088.44-19760854662405/command
<127.0.0.1> EXEC sudo -u root -s /usr/bin/python /root/.ansible/tmp/ansible-1355854088.44-19760854662405/command; rm -rf /root/.ansible/tmp/ansible-1355854088.44-19760854662405/ >/dev/null 2>&1
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1355854088.44-19760854662405/command", line 152, in ?
    import simplejson as json
ImportError: No module named simplejson


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************* 
localhost                      : ok=1    changed=0    unreachable=0    failed=1    
```

And even using normal remote Paramiko mode, `ansible_python_interpreter` gets ignored for `local_action`.  Looks similar to issue #1019?

**Comment by mpdehaan** [comment]
yeah, known issue I think.   Fixes welcome.

**Comment by dhozac** [comment]
It's supposed to work. Did you set ansible_python_interpreter for 127.0.0.1? That is the hostname used for local_action.

**Comment by jkleint** [comment]
No, but either way I would hope setting it on the command line does _something._  Specifically I would hope it overrides it for all hosts (otherwise, what's the point).

**Comment by mpdehaan** [comment]
On Thu, Dec 20, 2012 at 12:05 PM, jkleint notifications@github.com wrote:

> No, but either way I would hope setting it on the command line does *
> something.\* Specifically I would hope it overrides it for all hosts
> (otherwise, what's the point).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/1784#issuecomment-11581555.

Nope, it's an inventory variable, not a general setting.

Otherwise you would be in trouble if your hosts had different python
locations.

**Comment by bcoca** [comment]
if you ran make (or installed) ansible on the local host, it should already be set to the 'correct' python for local actions

**Comment by mpdehaan** [comment]
Indeed, I'm not terribly worried about it.   I'll accept patches if someone wants to fix this, but it's been open for a while and no one has.
