### ISSUE TITLE
type='int' in AnsibleModule triggers traceback

### ISSUE THREAD

**Issue by xen0l** [ansible/ansible#17850]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

module_utils/basic.py
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Module arguments of type='int' in AnsibleModule trigger  traceback and cause Ansible to stop working correctly. The following traceback is triggered:

<pre>
>>>Traceback (most recent call last):
  File "/tmp/ansible_4qbG0y/ansible_module_find.py", line 39, in <module>
    main()
  File "/tmp/ansible_4qbG0y/ansible_module_find.py", line 25, in main
    (rc, out, err) = find(module)
  File "/tmp/ansible_4qbG0y/ansible_module_find.py", line 11, in find
    return module.run_command(cmd)
  File "/tmp/ansible_4qbG0y/ansible_modlib.zip/ansible/module_utils/basic.py", line 2025, in run_command
  File "/usr/lib/python2.7/posixpath.py", line 254, in expanduser
    if not path.startswith('~'):
AttributeError: 'int' object has no attribute 'startswith'
</pre> 

I traced the problem to this code (https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L2092):

<pre>
 # expand things like $HOME and ~
        if not shell:
               args = [ os.path.expanduser(os.path.expandvars(x)) for x in args if x is not None ]
</pre>

This check should exclude certain types and int should be among them.
#### STEPS TO REPRODUCE

I find this when developing custom module. I wrote a short example module to reproduce the issue

```

---
- name: type bug
  hosts:
    - localhost
  gather_facts: false
  connection: local
  tasks:
     - find: name=/ depth=2
```

https://gist.github.com/xen0l/635ad120dfce8e0a194856db83e607ea
##### EXPECTED RESULTS

Ansible shouldn't trigger traceback when defining int or any other types. The current workaround is define it as str and int() where needed.
##### ACTUAL RESULTS

Traceback was triggered and it shouldn't happen.

**Comment by abadger** [comment]
It doesn't matter what the type of the parameter in the argument_spec is.  That just determines what type of argument ansible expects to be passed in via that parameter.  The error is coming from the custom module's use of run_command.  run_command()'s args parameter takes either a string or a list of strings.  So the module you write needs to make sure it's sending strings.  For your sample module, you'd do that like this:

``` python
def find(module):

    name = module.params['name']
    depth = module.params['depth']

    cmd = [module.get_bin_path('find')]
    cmd.append(name)
    cmd.append('-maxdepth')
    cmd.append('%s' % depth)

    return module.run_command(cmd)
```

The same would apply if you were getting an int value from something other than the module's parameters.  For instance, if you were trying to sleep for a random interval and then execute a command:

``` python
import random

# Correct
cmd = ['sleep', '%s' % random.randint(0, 60), '&&', '/bin/true']
module.run_command(cmd, use_unsafe_shell=True)
# Incorrect
cmd = ['sleep', random.randint(0, 60), '&&', '/bin/true']
module.run_command(cmd, use_unsafe_shell=True)
```
