### ISSUE TITLE
Valid SSH connection fails after Ansible update 2.1.1.0 -> 2.1.2.0

### ISSUE THREAD

**Issue by cadavre** [ansible/ansible#17869]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ansible-playbook
##### ANSIBLE VERSION

```
ansible 2.1.2.0
```
##### OS / ENVIRONMENT

```
uname -a
Linux cdb18054d077 3.13.0-83-generic 
#127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 
x86_64 x86_64 x86_64 GNU/Linux
```
##### SUMMARY

After update from 2.1.1.0 to 2.1.2.0 Setup task cannot complete due to `Unreachable` error.
##### STEPS TO REPRODUCE

```
# key.pem (chmod 0400)
```

```
# inventory
myhost ansible_host=myhost.com ansible_user=ubuntu ansible_port=22 ansible_ssh_private_key_file=key.pem
```

```
# playbook.yml
- hosts: all
  become: yes
  become_user: ci
  tasks:
    - command: ls -la /var/www
```

##### EXPECTED RESULTS

Print from `ls`.
##### ACTUAL RESULTS

```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
<myhost.com> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<myhost.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o 'IdentityFile="key.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r myhost.com '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1475491369.58-244338365319611 `" && echo ansible-tmp-1475491369.58-244338365319611="` echo /tmp/ansible-tmp-1475491369.58-244338365319611 `" ) && sleep 0'"'"''
fatal: [myhost]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
```

Due to bug with no SSH verbosity I cannot debug this.

**Comment by cadavre** [comment]
On the other hand:

```
myhost | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
```

**Comment by cadavre** [comment]
#17770 – this is the same case, but in here I don't use any custom SSH arguments.

**Comment by cadavre** [comment]
You sure about `49ce0c8` @bcoca ? I tried now generated `ssh command` and what I had was:

```
debug1: setting up multiplex master socket
debug3: muxserver_listen: temporary control path /root/.ansible/cp/ansible-ssh-jzapp.io-22-ubuntu.VMODcuk3ZKNVqT6S
muxserver_listen bind(): No such file or directory
```

After manual creating `/root/.ansible/cp/ansible-ssh-jzapp.io-22-ubuntu` everything went fine.

**Comment by diefans** [comment]
@bcoca regarding https://github.com/ansible/ansible/issues/14489 I think your patch level and version management is nearly insane and in now way predictable. Introducing this "bug" in a major version (1 -> 2) and not fixing it in two minor versions (2.0, 2.1) makes it quite a feature - now fixing it in a patch level (`pip install ansible==2.1.2`) is not comprehensible (see http://semver.org).

Your fix of the fix seems still broken to me: https://github.com/ansible/ansible/commit/751865d68cbdb0658113893956cece11dcd4914e#commitcomment-19287600

**Comment by elventear** [comment]
@bcoca Can we expect a `2.1.2.1` release soon?
