### ISSUE TITLE
ansible-playbook prints out wrong error message and does not honor -u centos or --private-key

### ISSUE THREAD

**Issue by Thermi** [ansible/ansible#17862]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ansible-playbook
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /home/thermi/UNITS/Rimoto/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

```
[defaults]
roles_path = roles/:library/
```
##### OS / ENVIRONMENT

```
uname -a
Linux thermi-pc.thermicorp.lan 4.4.23-1-lts #1 SMP Fri Sep 30 13:41:31 CEST 2016 x86_64 GNU/Linux
cat /etc/os-release
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```
##### SUMMARY

ansible-playbook prints out a wrong error message.
It also does not honor the -u switch, although it is mentioned on the man page for `ansible-playbook`:

```
       -u USERNAME, --user=USERNAME
           Use this USERNAME to login to the target host, instead of the current user.
```

The SSH key that is specified with --private-key does not seem to be honored either, because that
key is NOT encrypted.
##### STEPS TO REPRODUCE

```
ansible-playbook site.yml -u centos -c paramiko --ssh-common-args='-i /.ssh/id_rsa_rimoto_aws_new' --become-method=sudo -i es-cluster
```

or

```
ansible-playbook site.yml -u centos -c paramiko --private-key='/.ssh/id_rsa_rimoto_aws_new' --become-method=sudo -i es-cluster
```
##### EXPECTED RESULTS

That the playbook runs.
##### ACTUAL RESULTS

ansible-playbook errors out with the output that can be found at [gist.github.com](https://gist.github.com/Thermi/e3c009bba3cba3f618eb24bc7e620df1).

```
PLAY [master_nodes] ************************************************************

TASK [setup] *******************************************************************
fatal: [54.194.172.139]: UNREACHABLE! => {"changed": false, "msg": "ssh ansible@54.194.172.139:22 : Private key file is encrypted\nTo connect as a different user, use -u <username>.", "unreachable": true}
        to retry, use: --limit @/home/thermi/UNITS/Rimoto/ansible/site.retry

PLAY RECAP *********************************************************************
54.194.172.139             : ok=0    changed=0    unreachable=1    failed=0
```

From the journal of the host 54.194.172.139:

```
Oct 02 20:29:30 ip-10-2-1-204.eu-west-1.compute.internal sshd[6506]: Invalid user ansible from 78.43.42.91
Oct 02 20:29:30 ip-10-2-1-204.eu-west-1.compute.internal sshd[6506]: input_userauth_request: invalid user ansible [preauth]
Oct 02 20:29:30 ip-10-2-1-204.eu-west-1.compute.internal sshd[6506]: Connection closed by 78.43.42.91 [preauth]
```

**Comment by bcoca** [comment]
do you have ansible_user or ansible_ssh_user set for that host?

**Comment by Thermi** [comment]
It was set in the es-cluster.yml file. I did not know that the field there overrides the command line argument. Intuitively, the command line argument should override any such setting in a configuration file.
Still, with that fixed, the problem with the wrong error message remains.

**Comment by bcoca** [comment]
ansible.cfg is the configuration file, which -u does override. 

Connection variables are considered 'runtime' which overrides the command line and even play directives. This still does not seem like a bug but a configuration issue so I'm going to refer you to the lists/irc as this is not the place for debugging configuration issues.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
