### ISSUE TITLE
ipaddr('network') doesn't work with /32 addresses

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#17872]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ipaddr filter
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The ipaddr('network') filter returns an empty string when given a /32 subnet.
##### STEPS TO REPRODUCE

```
item:
  ip: 127.0.0.1
  subnet: 255.255.255.255
```

```
debug: msg="{{ (item.ip ~ '/' item.subnet|ipaddr('network') ~ '/' ~ item.subnet)|ipaddr('net') }}"
debug: msg="{{ (item.ip ~ '/' item.subnet|ipaddr('network') ~ '/' ~ item.subnet)|ipaddr('net')|default('127.0.0.1/32') }}"
```
##### EXPECTED RESULTS

```
SUCCESS => {
    "msg": "127.0.0.1/32"
}
SUCCESS => {
    "msg": "127.0.0.1/32"
}
```
##### ACTUAL RESULTS

```
SUCCESS => {
    "msg": ""
}
SUCCESS => {
    "msg": ""
}
```
##### WORKAROUND

```
debug: msg="{{ (item.ip ~ '/32' if item.subnet == '255.255.255.255' else (item.ip ~ '/' item.subnet|ipaddr('network') ~ '/' ~ item.subnet)|ipaddr('net') }}"

SUCCESS => {
    "msg": "127.0.0.1/32"
}
```

**Comment by krzysztof-magosa** [comment]
There was similar bug reported for netmask: #17627.

For some reason filter checks if network has more than 1 host and only then returns network address:
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/ipaddr.py#L169

**Comment by jacktose** [comment]
There are some other `>1` checks in similar functions. I don't know why we can't treat /32s like other subnets, so maybe those should all be taken out.

**Comment by jacktose** [comment]
By the way OP or anyone else finding this bug, the `network` filter gives you the network _address_, like this:
`10.1.1.99/24` -> `10.1.1.0`
OP was apparently looking for `subnet` or `network/prefix` which should do this:
`10.1.1.99/24` -> `10.1.1.0/24`
But are also affected by the `>1` problem.

Also also, there's a workaround for getting the network address of a /32*: just use the `network_id` filter instead.
Somebody should really clean these up....

\* Same issues should apply to /128s, but I haven't checked.
