### ISSUE TITLE
Local become_method variable not overriding global

### ISSUE THREAD

**Issue by avatar4d** [ansible/ansible#17887]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

become_method: will not override default when defined in playbook
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /Users/cmgross/repos/dotfiles/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Stock configuration
##### OS / ENVIRONMENT

OS X 10.11.6
Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
##### SUMMARY

I am attempting to make my Ansible playbook be OS agnostic with it using sudo on OSX and doas for my FreeBSD/OpenBSD machines (I plan to use an OS specifics checks defining the variable once the following test passes). It works if I set become_method=doas in the ansible.cfg or use --become-method=doas on the CLI, but not if I try to set become_method: doas in a playbook or task. In other words, Ansible does not appear to respect the become_method variable being set in a playbook or task and only respects the global.
##### STEPS TO REPRODUCE

At the task level:

```
- lineinfile: dest=/etc/shells line=/usr/local/bin/zsh state=present owner=root group=wheel mode=0644
  become: true
  become_method: doas
  when: zsh_exists_in_etc_shells.rc == 1
```

or in a playbook:

```

---
- hosts: localhost
   become_method: doas
  roles:
    - role: common
```

##### EXPECTED RESULTS

```
% ansible-playbook -K setup.yml

DOAS password:
```
##### ACTUAL RESULTS

```
% ansible-playbook -K setup.yml

SUDO password:
```

**Comment by bcoca** [comment]
The password prompt goes by the global config default or command line options, the password will be used for both sudo and doas, so what it displays at prompt won't be an issue with actually using it.

**Comment by avatar4d** [comment]
I confirmed it is working now. Something wasn't configured right when I submitted the bug since it failed with a command not found, but everything seems fine with the following:

ansible.cfg:
become_method=doas 

playbook:
vars_files: [ "roles/common/vars/{{ ansible_os_family }}.yml" ]

ansible_os_family.yml
become_method: sudo

task:
become_method: "{{ become_method }}"
