### ISSUE TITLE
Impossible to use tabs

### ISSUE THREAD

**Issue by rektide** [ansible/ansible#1789]
Hi. I'm trying to use lineinfile, but YAML does not permit tabs, even though it's in a parameter value enclosed in strings.

I'm not sure why YAML has a FAQ with 84% of it's words dedicated to hating on my beloved character 0x9, but those guys are a bunch of jackasses and fuck them: I need tabs.
http://www.yaml.org/faq.html

**Comment by dhozac** [comment]
Works fine for me, just ensure you quote the entire value, e.g. action: "lineinfile line='....'".
