### ISSUE TITLE
test issue for resolved by PR

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#17899]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

testme plugin
##### ANSIBLE VERSION

```
2.3
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

test test test
##### STEPS TO REPRODUCE

N/A
##### EXPECTED RESULTS

N/A
##### ACTUAL RESULTS

N/A

**Comment by jctanner** [comment]
resolved_by_pr #17897

**Comment by gundalow** [comment]
resolved_by_pr #17897
