### ISSUE TITLE
ansible-playbook reports host unreachable while 'ansible -m ping' can connect

### ISSUE THREAD

**Issue by rouge8** [ansible/ansible#17905]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /Users/andy/gr/pbm/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
inventory = ansible/hosts
force_color = true

[ssh_connection]
pipelining = true
ssh_args = -F ansible/ssh_config
```
##### OS / ENVIRONMENT

OS X 10.11.6
##### SUMMARY

`ansible-playbook` reports the host is unreachable during the `setup` phase, but I can connect to the host with `ansible -m ping`.
##### STEPS TO REPRODUCE

To reproduce: `ansible -m ping prod` vs `ansible-playbook ansible/site.yml -l prod`
- `ansible.cfg` (as above)
- `ansible/hosts`

```
[prod]
prod-web
```
- `ansible/site.yml`

```

---

- hosts: all
  tasks:
    - name: Gather environment variables before deploying
      setup: filter=ansible_env
```
- `ansible/ssh_config`

```
# Prod
Host prod-nat
    HostName SOME_IP
    User ec2-user
Host prod-web
    HostName INTERNAL_IP
    User ec2-user
    ForwardAgent yes
    ProxyCommand ssh -q -W %h:%p ec2-user@SOME_IP
```

##### EXPECTED RESULTS

Able to connect successfully from `ansible` or `ansible-playbook`
##### ACTUAL RESULTS

```
ansible -m ping prod
prod-web | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
```

```
ansible-playbook ansible/site.yml -l prod -vvvv
Using /Users/andy/gr/pbm/ansible.cfg as config file
Loaded callback default of type stdout, v2.0

PLAYBOOK: site.yml *************************************************************
1 plays in ansible/site.yml

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
<prod-web> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<prod-web> SSH: EXEC ssh -C -vvv -F ansible/ssh_config -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 prod-web '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'"'"''
fatal: [prod-web]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
    to retry, use: --limit @/Users/andy/gr/pbm/ansible/site.retry

PLAY RECAP *********************************************************************
prod-web                : ok=0    changed=0    unreachable=1    failed=0
```

**Comment by rouge8** [comment]
Reverting to 2.1.1.0 fixes this for me (see #17869)

**Comment by thiagomgo** [comment]
I'm facing the same issue, but only after execute `ansible <host> -m ping` I can run the playbook smoothly.

**Comment by jctanner** [comment]
@rouge8 are you able to run this command successfully? ...

```
ssh -C -vvv -F ansible/ssh_config -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 prod-web 'whoami ; hostname f'
```

needs_info

**Comment by jimi-c** [comment]
@rouge8 I would also run `ansible -m setup -a filter=ansible_env prod` to make sure it's not something within the setup task itself.

**Comment by rouge8** [comment]
@jctanner: yes, i can use that ssh command and connect to the host

@jimi-c yes, i can run adhoc ansible commands, including `ansible -m setup`.

**Comment by mattwillsher** [comment]
It seems that ansible isn't loading ssh_config from the current working dir. Giving the full path to the -F option (e.g. -F /home/myhome/ansible/ssh.config) works. It used to load the file from the cwd in 2.1.1.0

**Comment by rouge8** [comment]
Works using http://releases.ansible.com/ansible/ansible-2.2.0.0-0.4.rc4.tar.gz and http://releases.ansible.com/ansible/ansible-2.1.3.0-0.3.rc3.tar.gz

**Comment by ludwig-gramberg** [comment]
can confirm the problem of relative paths in ansible.cfg AND ssh.cfg
i changed all paths in ansible.cfg and ssh.cfg to absolute paths and now everything is working again... really nasty bug

the working directory ansible-playbook ended up using, was the playbooks directory...

**Comment by NISHAgl** [comment]
Hi, 
I am also getting the same issue while copying dir. from serverA to serverB using my AnsibleServer which is 3rd server. So basically, when I use ping all command it connects, but sync it gives below error:(I tried both pull and push method by changing the delegate_server and hosts)

TASK [Transfer files from Server1 to Server2] **********************************
fatal: [x.x.x.x]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname serv1: Name or service not known\r\n", "unreachable": true}
        to retry, use: --limit @/etc/ansible/playbook/hello.retry

PLAY RECAP *********************************************************************

but ping is success:
ansible -i /etc/ansible/copyHosts -m ping all
x.x.x.x | SUCCESS => {
    "changed": false,
    "ping": "pong"

**Comment by sudheer112** [comment]
pls help me how to resolve this?

prod | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname prod: Name or service not known",
    "unreachable": true
}
