### ISSUE TITLE
Infinite loop when trying to override an undefined variable with a default

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#17906]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Variable expansion
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

```
==> ert.yml <==
- hosts: localhost
  roles:
    - role: role1
      foo: '{{ foo | default("abc") }}'

==> roles/role1/tasks/main.yml <==
- debug: msg="got {{foo}}"
```

Same problem with:

```
- hosts: localhost
  roles:
    - role: role1
      foo: '{% if foo is defined %}{{foo}}{% else %}abc{% endif %}'
```
##### EXPECTED RESULTS

`ansible-playbook ert.yml`
:   expected "got abc"

`ansible-playbook ert.yml - foo=""`
:   expected "got " (since extra-vars override absolutely everything)

`ansible-playbook ert.yml -e foo=def`
:    expected "got def"
##### ACTUAL RESULTS

In case 1:

```
TASK [role1 : debug] ***********************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "{{ foo | default(\"abc\") }}: {{ foo | default(\"abc\") }}: {{ foo | default(\"abc\") }}: {{ foo | defau
... snip ...
{{ foo | default(\"abc\") }}: recursive loop detected in template string: {{ foo | default(\"abc\") }}"}
```

Cases 2 and 3 are fine.
##### WORKAROUND

Set the defaults a different way (e.g. using `vars:`)

**Comment by krzysztof-magosa** [comment]
It's not a bug. You cannot template variable into itself.

**Comment by candlerb** [comment]
But it's not itself; it's the inner "foo" being passed as an argument to a role, which in a normal programming language would be in a different scope. For example, in plain python:

```
def myrole(foo):
    print foo

foo = 123
myrole(foo=foo*2)
```

And even in ansible, it's an inner scope, as can be demonstrated:

```
==> z.yml <==
- hosts: localhost
  vars:
    foo: 123
  roles:
    - role: role1
      foo: 456
    - role: role2

==> roles/role1/tasks/main.yml <==
- debug: msg="foo={{foo}}"

==> roles/role2/tasks/main.yml <==
- debug: msg="foo={{foo}}"
```

Results:

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [role1 : debug] ***********************************************************
ok: [localhost] => {
    "msg": "foo=456"
}

TASK [role2 : debug] ***********************************************************
ok: [localhost] => {
    "msg": "foo=123"
}
```

The 'foo' passed as an argument to role1 is not the same as the outer 'foo' which is accessed implicitly by role2.

**Comment by krzysztof-magosa** [comment]
At the first look to Ansible/Jinja code it works more like:

```
def template(variables, template):
  # parse
  # found reference to foo
  # call template(variables, "{{ foo }}") to extract it
  # ...

variables = dict()
variables["foo"] = "{{ foo | default(123) }}"
print template(variables, "{{ foo }}")
```

**Comment by candlerb** [comment]
Maybe it does, although as I showed above, the previous value of `variables["foo"]` is restored later on.

Greenspun's Tenth Rule seems to apply here :-)

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

As mentioned above this is not a bug, Ansible is not a programming language and does not differentiate scopes that way.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
