### ISSUE TITLE
safe_eval() warning for variables containing curly braces and Jinja2 expressions

### ISSUE THREAD

**Issue by grgi** [ansible/ansible#17913]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

`template/safe_eval`
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

There is a strange `safe_eval()` warning if one wants to template a string containing Jinja2 expressions and curly braces. Even escaping the curly braces like `{{ '{}' }}` does not help.
##### STEPS TO REPRODUCE

```
- hosts: localhost
  vars:
    foo: "bar"
  tasks:
    - debug: msg="{}/{{ foo }}"
```
##### EXPECTED RESULTS

Apart from the warning the expected results coincide with the actual ones.
##### ACTUAL RESULTS

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
 [WARNING]: Exception in safe_eval() on expr: {}/bar (name 'bar' is not defined)

ok: [localhost] => {
    "msg": "{}/bar"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by dagwieers** [comment]
I am sorry, I introduced this warning when we had a genuine problem that was silently ignored. (See #14304)
Although I don't understand how your expression can trigger that exceptionand it results in another safe_eval() call.

I've undone that change now.
