### ISSUE TITLE
Wrong doc "Installing Multiple Roles From Multiple Files"

### ISSUE THREAD

**Issue by bitbauer** [ansible/ansible#17917]
##### ISSUE TYPE
- Documentation Report
##### COMPONENT NAME

ansible-galaxy / install requirements / include
##### ANSIBLE VERSION

ansible 2.1.2.0
  config file = /vagrant/provision/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

```
[defaults]
roles_path = ./requirements/roles:./roles
```
##### OS / ENVIRONMENT

Running ansible-galaxy at Ubuntu 14.04.5 LTS
##### SUMMARY

When calling ansible-galaxy install -vvv -r requirements.yml 

```
Using /vagrant/provision/ansible/ansible.cfg as config file
Opened /home/vagrant/.ansible_galaxy
found role {'scm': None, 'version': ''} in yaml file
ERROR! Unexpected Exception: __init__() takes at least 3 arguments (4 given)
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 92, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 133, in run
    self.execute()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/__init__.py", line 103, in execute
    fn()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 356, in execute_install
    roles_left.append(GalaxyRole(self.galaxy, **role))
TypeError: __init__() takes at least 3 arguments (4 given)
```

In documentation this whole feature is explained at [Installing Multiple Roles From Multiple Files](http://docs.ansible.com/ansible/galaxy.html#installing-multiple-roles-from-multiple-files)

After playing around i ran in described error every time i try to use include: statement in requirements.yml
I inspected source code at ansible repo under path ansible/lib/ansible/playbook/role/ and I wasn't able to find a hook for load a sub requirements file.
... Okay I don't know python well. I spend more time on stupid lang like Ruby, Java and C++ ;-) 
##### STEPS TO REPRODUCE

requirements.yml 

```

---
- include: ./requirements/php.yml
- src: "nodesource.node"
- src: lciolecki.libsass
  version: "v0.1.0"
```

requirements/php.yml 

```

---
- src: "colstrom.apt-repository"
- src: "geerlingguy.php"
```

see ansible.cfg above
##### EXPECTED RESULTS

It should work or whole section in documentation needs to be removed.
##### ACTUAL RESULTS

Unexpected error message

```
TypeError: __init__() takes at least 3 arguments (4 given)
```

... I like the logic of internal python error handling.

**Comment by bcoca** [comment]
someone did propose adding includes, but that was never implemented, sorry, not sure how the docs got through.
