### ISSUE TITLE
Merge ansible config files

### ISSUE THREAD

**Issue by lassizci** [ansible/ansible#17914]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

ansible.cfg
##### SUMMARY

Merge configurations instead of using the first configuration found.

I think it would be helpful if ansible merged the configuation files instead of just using the first one it finds. This would allow to have a repo specific configurations while allowing people to keep their local settings such as forks or ssh options. Especially setting `roles_path` to `./` in a repo configs would allow big repos to place playbooks in a subdirectory while including them in site.yml in repo root. Without setting roles_path the playbooks in the sub directory can't find roles unless those are symlinked (suppose that's the same with group_vars and host_vars). Also it's not very feasible to set full paths in global or user local ansible.cfg when there are multiple ansible repos with separate roles.

**Comment by resmo** [comment]
Probably worth considering having an `[include]` section, similar like in git https://git-scm.com/docs/git-config#_includes

``` ini
[include]
    path = ~/.ansible.cfg
```

**Comment by jtoppins** [comment]
I think the include directive is a separate feature. It should be noted that git currently has 4 default config locations it merges from[1] not including environment variables which override anything set from a file. The merge algorithm is simple, last defined wins. Anyone working on this? It seems pretty straight forward given ConfigParser is the standard config parser provided by Python[2]. Here is a rough attempt below. Am having a little trouble finding where all the defaults get set. It might be useful to define a default config that must always exist and read that with ConfigParser.readfp().

```
jtoppins@jtoppins:~/projects/ansible$ git --no-pager diff
diff --git i/lib/ansible/constants.py w/lib/ansible/constants.py
index eb7f12284b1f..aae8a7516610 100644
--- i/lib/ansible/constants.py
+++ w/lib/ansible/constants.py
@@ -142,33 +142,39 @@ def _get_config(p, section, key, env_var, default):
 
 
 def load_config_file():
-    ''' Load Config File order(first found is used): ENV, CWD, HOME, /etc/ansible '''
+    ''' Load Config File order(union of all possible config files): ENV, CWD, HOME, /etc/ansible
+
+        The merge method is simple, last key defined wins. Thus we travers
+        files from lowest to highest priority.
+
+        Note: the order in which config files are inserted into the 'paths'
+        list is important.
+    '''
 
     p = configparser.ConfigParser()
+    paths = []
 
     path0 = os.getenv("ANSIBLE_CONFIG", None)
     if path0 is not None:
         path0 = os.path.expanduser(path0)
         if os.path.isdir(path0):
-            path0 += "/ansible.cfg"
+            paths.insert(0, os.path.join(path0, "ansible.cfg"))
     try:
         path1 = os.getcwd() + "/ansible.cfg"
+        paths.insert(0, path1)
     except OSError:
-        path1 = None
-    path2 = os.path.expanduser("~/.ansible.cfg")
-    path3 = "/etc/ansible/ansible.cfg"
-
-    for path in [path0, path1, path2, path3]:
-        if path is not None and os.path.exists(path):
-            try:
-                p.read(path)
-            except configparser.Error as e:
-                raise AnsibleOptionsError("Error reading config file: \n{0}".format(e))
-            return p, path
-    return None, ''
+        pass
+    paths.insert(0, os.path.expanduser("~/.ansible.cfg"))
+    paths.insert(0, "/etc/ansible/ansible.cfg")
 
+    try:
+        # p.readfp(open(''))
+        valid_paths = p.read(paths)
+    except configparser.Error as e:
+        raise AnsibleOptionsError("Error reading config file: \n{0}".format(e))
+    return p
 
-p, CONFIG_FILE = load_config_file()
+p = load_config_file()
 
 # non configurable but used as defaults
 BLACKLIST_EXTS = ('.pyc', '.pyo', '.swp', '.bak', '~', '.rpm', '.md', '.txt')
```

[1] https://github.com/git/git/blob/master/Documentation/git-config.txt#L231
[2] https://docs.python.org/2/library/configparser.html#ConfigParser.RawConfigParser.read

**Comment by thaumos** [comment]
There are plans for an ansible-config feature in 2.4.  

[Proposal](https://github.com/ansible/proposals/issues/35)

[Link to PR](https://github.com/ansible/ansible/pull/12797)

So at this point, I'd say things like this could be up in the air until the new functionality is implemented.

**Comment by geerlingguy** [comment]
Oh my gosh, can't believe it's taken me this long to finally realize why some of my playbooks felt like molasses compared to most other playbooks... I globally set `pipelining = True` in `/etc/ansible/ansible.cfg`, but for some playbooks, where I want specific roles to be installed locally to that playbook, I add an override `ansible.cfg` to the playbook directory with the custom `roles_path`.

...and since the playbook's `ansible.cfg` doesn't have my performance tuning settings I use globally, the playbooks run 2-3x slower!

Anyways, glad to see there's some movement on it for 2.4; for now I'll just remember to put any important overrides into project-specific `ansible.cfg`s.

**Comment by b-long** [comment]
Just confirming, but based on the [current CHANGELOG.md], it looks like merged Ansible configuration didn't land in 2.4.  

Am I understanding that correctly?

_As an aside, thanks so much for highlighting [the configuration behavior] on your blog @geerlingguy ! 👍_ 

[current CHANGELOG.md]: https://github.com/ansible/ansible/blob/2295494fa5deb492c1a521bdfa4b36f92111031d/CHANGELOG.md
[the configuration behavior]: https://www.jeffgeerling.com/blog/2017/slow-ansible-playbook-check-ansiblecfg

**Comment by bcoca** [comment]
configuration 'landed', just one foot ... no merging configs yet, project is big enough to span a few releases.

**Comment by b-long** [comment]
Understood, thanks for clarifying @bcoca 😄

**Comment by baldwintm** [comment]
Was there any movement on this in 2.5?

**Comment by bcoca** [comment]
@baldwintm  some of the groundwork is there, but the feature is not ready yet.

Closing this ticket in favor of the proposal that includes the feature https://github.com/ansible/proposals/issues/35

**Comment by rguhr** [comment]
As workaround you could build a temporary configuration file which merged all possible ansible.cfg's

Here a first draft of this approach:
https://gitlab.com/snippets/1753039

FYI @lassizci @geerlingguy @b-long @baldwintm
