### ISSUE TITLE
Static Include Displayed in StdOut 2.2 (devel)

### ISSUE THREAD

**Issue by stevenmccord** [ansible/ansible#17927]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME
- stdout
##### ANSIBLE VERSION

```
devel branch
```
##### SUMMARY

Per this discussion, it was suggested to put in an issue regarding static includes and to not show it with lowering the verbosity when you run the playbook
##### STEPS TO REPRODUCE

Have static includes in your playbook and then run the provisioning it will output a bunch of static includes into the output.
##### EXPECTED RESULTS

Be able to turn off that output either view verbosity level or override it in a stdout callback plugin.
##### ACTUAL RESULTS

Outputs static includes before anything else is shown on the screen.

**Comment by kustodian** [comment]
This should be fixed with #17918

**Comment by bcoca** [comment]
closing as per above
