### ISSUE TITLE
--tree option in ansible.cfg

### ISSUE THREAD

**Issue by chrisberkhout** [ansible/ansible#1793]
I'd like to be able to set

```
tree=./log
```

in my `ansible.cfg` file instead of having to add `--tree=./log` on the command line.

**Comment by mpdehaan** [comment]
This is what bash aliases are for.

**Comment by chrisberkhout** [comment]
Okay. I also realised that `--tree` doesn't log anything when running `ansible-playbook`, so I guess it makes less sense as a general config option anyway.
