### ISSUE TITLE
ERROR! Missing target hosts with 2.2 RC1

### ISSUE THREAD

**Issue by filapinoaquino** [ansible/ansible#17938]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

Regression
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

CENTOS 7
##### SUMMARY

Inventory file is not recognized
##### STEPS TO REPRODUCE

[root@ny-nitools-003 tmp]# ansible-playbook -vvvv show.yml

```

---

- name: Show Version
  hosts: junos
  connection: local
  gather_facts: no

  tasks:

  - name: show version
    junos_command:
      host: "{{ hostvars[inventory_hostname].ansible_host|default(inventory_hostname) }}"
      username: ""
      password: "" 
      commands: ['show version']
      format: text
```

##### EXPECTED RESULTS

[root@ny-nitools-003 tmp]# ansible-playbook -vvvv show.yml
Using /etc/ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0

PLAYBOOK: show.yml *************************************************************
1 plays in show.yml

PLAY [Show Version] ************************************************************

TASK [show version] ************************************************************
task path: /tmp/show.yml:10
<10.32.8.250> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.32.8.250> EXEC /bin/sh -c '( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1475869667.89-3004428941099`" && echo ansible-tmp-1475869667.89-3004428941099="`echo $HOME/.ansible/tmp/ansible-tmp-1475869667.89-3004428941099`" ) && sleep 0'
<10.32.8.250> PUT /tmp/tmpE9oUkz TO /root/.ansible/tmp/ansible-tmp-1475869667.89-3004428941099/junos_command
<10.32.8.250> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1475869667.89-3004428941099/ /root/.ansible/tmp/ansible-tmp-1475869667.89-3004428941099/junos_command && sleep 0'
<10.32.8.250> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1475869667.89-3004428941099/junos_command; rm -rf "/root/.ansible/tmp/ansible-tmp-1475869667.89-3004428941099/" > /dev/null 2>&1 && sleep 0'
ok: [NY1-PL-OOB4200-02] => {"changed": false, "invocation": {"module_args": {"commands": ["show version"], "format": "text", "host": "10.32.8.250", "interval": 1, "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "port": null, "provider": null, "retries": 10, "rpcs": null, "ssh_keyfile": null, "timeout": 0, "transport": "netconf", "username": "", "waitfor": null}, "module_name": "junos_command"}, "stdout": ["\nfpc0:\n--------------------------------------------------------------------------\nHostname: NY1-PL-OOB4200-02\nModel: ex4200-24t\nJUNOS Base OS boot [12.3R4.6]\nJUNOS Base OS Software Suite [12.3R4.6]\nJUNOS Kernel Software Suite [12.3R4.6]\nJUNOS Crypto Software Suite [12.3R4.6]\nJUNOS Online Documentation [12.3R4.6]\nJUNOS Enterprise Software Suite [12.3R4.6]\nJUNOS Packet Forwarding Engine Enterprise Software Suite [12.3R4.6]\nJUNOS Routing Software Suite [12.3R4.6]\nJUNOS Web Management [12.3R4.6]\nJUNOS FIPS mode utilities [12.3R4.6]\n"], "stdout_lines": [["", "fpc0:", "--------------------------------------------------------------------------", "Hostname: NY1-PL-OOB4200-02", "Model: ex4200-24t", "JUNOS Base OS boot [12.3R4.6]", "JUNOS Base OS Software Suite [12.3R4.6]", "JUNOS Kernel Software Suite [12.3R4.6]", "JUNOS Crypto Software Suite [12.3R4.6]", "JUNOS Online Documentation [12.3R4.6]", "JUNOS Enterprise Software Suite [12.3R4.6]", "JUNOS Packet Forwarding Engine Enterprise Software Suite [12.3R4.6]", "JUNOS Routing Software Suite [12.3R4.6]", "JUNOS Web Management [12.3R4.6]", "JUNOS FIPS mode utilities [12.3R4.6]", ""]]}

PLAY RECAP *********************************************************************
NY1-PL-OOB4200-02          : ok=1    changed=0    unreachable=0    failed=0 
##### ACTUAL RESULTS

ERROR! Missing target hosts

```
[root@ny-nitools-003 tmp]# ansible-playbook -vvvv show.yml
Usage: ansible <host-pattern> [options]

Options:
  -a MODULE_ARGS, --args=MODULE_ARGS
                        module arguments
  --ask-vault-pass      ask for vault password
  -B SECONDS, --background=SECONDS
                        run asynchronously, failing after X seconds
                        (default=N/A)
  -C, --check           don't make any changes; instead, try to predict some
                        of the changes that may occur
  -D, --diff            when changing (small) files and templates, show the
                        differences in those files; works great with --check
  -e EXTRA_VARS, --extra-vars=EXTRA_VARS
                        set additional variables as key=value or YAML/JSON
  -f FORKS, --forks=FORKS
                        specify number of parallel processes to use
                        (default=5)
  -h, --help            show this help message and exit
  -i INVENTORY, --inventory-file=INVENTORY
                        specify inventory host path
                        (default=/etc/ansible/hosts) or comma separated host
                        list.
  -l SUBSET, --limit=SUBSET
                        further limit selected hosts to an additional pattern
  --list-hosts          outputs a list of matching hosts; does not execute
                        anything else
  -m MODULE_NAME, --module-name=MODULE_NAME
                        module name to execute (default=command)
  -M MODULE_PATH, --module-path=MODULE_PATH
                        specify path(s) to module library (default=None)
  --new-vault-password-file=NEW_VAULT_PASSWORD_FILE
                        new vault password file for rekey
  -o, --one-line        condense output
  --output=OUTPUT_FILE  output file name for encrypt or decrypt; use - for
                        stdout
  -P POLL_INTERVAL, --poll=POLL_INTERVAL
                        set the poll interval if using -B (default=15)
  --syntax-check        perform a syntax check on the playbook, but do not
                        execute it
  -t TREE, --tree=TREE  log output to this directory
  --vault-password-file=VAULT_PASSWORD_FILE
                        vault password file
  -v, --verbose         verbose mode (-vvv for more, -vvvv to enable
                        connection debugging)
  --version             show program's version number and exit

  Connection Options:
    control as whom and how to connect to hosts

    -k, --ask-pass      ask for connection password
    --private-key=PRIVATE_KEY_FILE, --key-file=PRIVATE_KEY_FILE
                        use this file to authenticate the connection
    -u REMOTE_USER, --user=REMOTE_USER
                        connect as this user (default=None)
    -c CONNECTION, --connection=CONNECTION
                        connection type to use (default=smart)
    -T TIMEOUT, --timeout=TIMEOUT
                        override the connection timeout in seconds
                        (default=10)
    --ssh-common-args=SSH_COMMON_ARGS
                        specify common arguments to pass to sftp/scp/ssh (e.g.
                        ProxyCommand)
    --sftp-extra-args=SFTP_EXTRA_ARGS
                        specify extra arguments to pass to sftp only (e.g. -f,
                        -l)
    --scp-extra-args=SCP_EXTRA_ARGS
                        specify extra arguments to pass to scp only (e.g. -l)
    --ssh-extra-args=SSH_EXTRA_ARGS
                        specify extra arguments to pass to ssh only (e.g. -R)

  Privilege Escalation Options:
    control how and which user you become as on target hosts

    -s, --sudo          run operations with sudo (nopasswd) (deprecated, use
                        become)
    -U SUDO_USER, --sudo-user=SUDO_USER
                        desired sudo user (default=root) (deprecated, use
                        become)
    -S, --su            run operations with su (deprecated, use become)
    -R SU_USER, --su-user=SU_USER
                        run operations with su as this user (default=root)
                        (deprecated, use become)
    -b, --become        run operations with become (does not imply password
                        prompting)
    --become-method=BECOME_METHOD
                        privilege escalation method to use (default=sudo),
                        valid choices: [ sudo | su | pbrun | pfexec | doas |
                        dzdo | ksu ]
    --become-user=BECOME_USER
                        run operations as this user (default=root)
    --ask-sudo-pass     ask for sudo password (deprecated, use become)
    --ask-su-pass       ask for su password (deprecated, use become)
    -K, --ask-become-pass
                        ask for privilege escalation password
ERROR! Missing target hosts
```

**Comment by sivel** [comment]
How did you install 2.2 RC1?  What I notice in your output is:

```
ansible-playbook -vvvv show.yml
Usage: ansible <host-pattern> [options]
```

Which indicates when you run `ansible-playbook`, it is actually the `ansible` command that is executing.

**Comment by filapinoaquino** [comment]
Downloaded the source from
https://github.com/ansible/ansible/releases/tag/v2.2.0.0-0.1.rc1.
[root@ny-nitools-003 tmp]# pip install ansible-2.2.0.0-0.1.rc1.zip

**Comment by sivel** [comment]
It seems there is a problem with installing from the zip file that github creates.  Installing from the tar.gz file does not suffer from this problem.

Additionally, installing via the github release archives is not supported. For installation instructions for 2.2 RC 1 please see https://groups.google.com/forum/#!topic/ansible-devel/Ca07JSmyxIQ

If you have further questions please stop by IRC or the mailing list:
- IRC: #ansible on irc.freenode.net
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by filapinoaquino** [comment]
[root@ny-nitools-003 tmp]# ansible-playbook -vvvv show.yml
Using /etc/ansible/ansible.cfg as config file
ERROR! The requested action was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem.

The error appears to have been in '/tmp/show.yml': line 10, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:
- name: show version
  ^ here

The error appears to have been in '/tmp/show.yml': line 10, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:
- name: show version
  ^ here

**Comment by filapinoaquino** [comment]
I installed with the tar.  I currently can't install directly from github (corporate firewall), so I downloaded the tar.gz and used pip to install.  The above comment is the resulting output.  The same playbook and inventory work with ansible 2.1.2

**Comment by filapinoaquino** [comment]
Resolved, I see now that the link is different, it was unclear to me before.  The playbooks are executing as expected.
