### ISSUE TITLE
Ansible prints misleading [DEPRECATION WARNING] and possibly evaluate when clause

### ISSUE THREAD

**Issue by simon-sinx17** [ansible/ansible#17945]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

[DEPRECATION WARNING] / when
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /home/user/project/ansible.cfg
  configured module search path = Default w/o overrides

```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Ansible prints misleading [DEPRECATION WARNING], stating Skipping task due to undefined Error, where the "skip_reason": "Conditional check failed". With the warning printed, Ansible possibly fails to evaluate when, before triggering the warning.
##### STEPS TO REPRODUCE

x      - name: test
x        ...
x        with_items:
x        - "{{ varfile }}"
x        when:
x        - varfile is defined

```

```

##### EXPECTED RESULTS

skipping: [hostname]
##### ACTUAL RESULTS

[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this 
will be a fatal error.: 'varfile' is undefined.
This feature will be removed in 
a future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
skipping: [hostname]  => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

```

```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

As documented http://docs.ansible.com/ansible/playbooks_conditionals.html#loops-and-conditionals, 
`when` gets evaluated per item of a `with_` loop iteration, as such it cannot be used to avoid undefined errors in loops. Use the `|default([])` to pass an empty list to the loop and skip the task in those cases.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by simon-sinx17** [comment]
@bcoca , This scenario has not started a loop yet, more like don't loop if no file condition. The documentation you are referring to has this right above the section mentioned by you - 

If a required variable has not been set, you can skip or fail using Jinja2’s defined test. For example:

tasks:
- shell: echo "I've got '{{ foo }}' and am not afraid to use it!"
    when: foo is defined
- fail: msg="Bailing out. this play requires 'bar'"
    when: bar is undefined

This is especially useful in combination with the conditional import of vars files (see below).

Can you explain please the combination of
- If a required variable has not been set, you can skip or fail using Jinja2’s defined test
- This is especially useful in combination with the conditional import of vars files

???
