### ISSUE TITLE
$ansible_hostname reports short hostname

### ISSUE THREAD

**Issue by chrisberkhout** [ansible/ansible#1794]
For example, when `/bin/hostname` reports `myhost.vm`, `$ansible_hostname` is `myhost`.

**Comment by sfromm** [comment]
Do you want the host's fqdn instead?  Use $ansible_fqdn and that should return _myhost.vm_.

ansible basically does the following to get the fqdn, from which it derives the hostname:

```
$ python -c 'import socket; print socket.getfqdn()'
```

**Comment by chrisberkhout** [comment]
Hi Stephen,

Hmm... for me `$ansible_fqdn` is also coming back as `myhost`. I assume that's because the longer name is just set in `/etc/hostname` and applied with `/bin/hostname --file /etc/hostname` - it's not something I've set up with DNS.

So for fqdn the shorter one may be appropriate, but I'd expect `$ansible_hostname` to match the output of `/bin/hostname`.
