### ISSUE TITLE
additional options for logging 

### ISSUE THREAD

**Issue by snemir2** [ansible/ansible#17940]
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

ansible logging
##### ANSIBLE VERSION

```
ansible 2.1.1.0

```

**Comment by xen0l** [comment]
@snemir2 could you provide more details?

**Comment by snemir2** [comment]
1.  ability to add dynamically provide log file. In ansible cf, need to be able to say
   log_path: /var/log/{{playbook_name}}_{{time_string}}.log
2.  Ability to log select errors to syslog, i.e. have a configuration option to throw fatal errors to syslog.

**Comment by ghost** [comment]
3. Different log levels for console and log file.

It's extremely frustrating to me that I can't enable 'vvvv' logging to the log file only, and regular logging to the console.

**Comment by jainnikhil30** [comment]
It will also be worth to choose the logging levels (info, warning, debug, error, fatal) for the syslog. That way we can choose what we want to be logged. Currently Ansible logs everything at the syslog info severity, which adds loads of noise in there.

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/issues/49657#issuecomment-731242094
^ closing as per comment
