### ISSUE TITLE
group_vars ignored with inventory script in ansible 2.1.1.0

### ISSUE THREAD

**Issue by emanuelis** [ansible/ansible#17969]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Ansible
##### ANSIBLE VERSION

```
ansible 2.1.1.0+
```
##### CONFIGURATION

any
##### OS / ENVIRONMENT

any
##### SUMMARY

Ansible has so many bugs in pre 2.1.1.0 versions. But many people can not upgrade due to "feature" #16878

Please reopen #16878 and fix "the feature". It is not acceptable when you make breaking changes in a minor minor version.
##### STEPS TO REPRODUCE

See #16878
##### EXPECTED RESULTS

See #16878
##### ACTUAL RESULTS

See #16878

**Comment by Iowners** [comment]
Please FIX THIS !

**Comment by parito** [comment]
Come on guys, this is breaking our installations and is ugly.

**Comment by ntmggr** [comment]
+1

**Comment by Ycallaer** [comment]
+1

**Comment by it-svit** [comment]
+1
Also if I execute 
```
ansible-playbook -i /path/to/inventory playbook.yml
```
and `/path/to/inventory ` doesn't exist, group_vars are ignored too.

**Comment by const-bon** [comment]
+1 
Workaround. I'm using empty file as `/path/to/inventory`

**Comment by sivel** [comment]
This is no longer the case in recent versions of Ansible. If you are still experiencing problems, please open a new issue with a full reproducer.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
