### ISSUE TITLE
Extensions of variable files are not limited as they should be per documentation. Backup copies thus may take precedence over expected files

### ISSUE THREAD

**Issue by tomashevski** [ansible/ansible#17968]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

initialization
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Host: Ubuntu 14.01
Guest: Scientific Linux release 7.2 (Nitrogen)
##### SUMMARY

Variables loaded from ./group_vars/all/config.yml~ wins over ./group_vars/all/config.yml
According to [docs](http://docs.ansible.com/ansible/intro_inventory.html#splitting-out-host-and-group-specific-data) this should not be allowed: 

> ....Valid file extensions include ‘.yml’, ‘.yaml’, ‘.json’, or no file extension
> And by "include" it means included in a list and not should include a sub-string in an extension.
##### STEPS TO REPRODUCE
1. Create ./group_vars/all/config.yml file with simple content

```

---
varrr: proper_value
```
1. Copy file and concat with tilde at the end of the filename ./group_vars/all/config.yml~ 
   . Change content

```

---
varrr: incorrect_value
```
1. Run simple task to print variable

```
- name: Print varrr
  debug: var=varrr
```
##### EXPECTED RESULTS

Expected content from ./group_vars/all/config.yml
##### ACTUAL RESULTS

Got content from ./group_vars/all/config.yml~

**Comment by gaudenz** [comment]
Instead of just warning about this it would be nice to have a configurable pattern of files to exclude. This would make it possible to still have editor backup files.

I got bitten by this several time. I would really appreciate a fix.
