### ISSUE TITLE
Path relativity has changed and broken use of path relative "ssh_configuration/ssh_args" -F option in ansible.cfg.

### ISSUE THREAD

**Issue by akrzos** [ansible/ansible#17979]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ansible.cfg - Path relativity has changed and broken use of path relative "ssh_configuration/ssh_args" -F option.
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.2.0
  config file = 
  configured module search path = Default w/o overrides
```

This worked fine on ansible 2.1.1.0
##### CONFIGURATION

[defaults]
gathering = smart
fact_caching_timeout = 86400
fact_caching = jsonfile
fact_caching_connection = /tmp/browbeat_fact_cache
timeout=30

[ssh_connection]
# Load the specific ssh config file in this directory

ssh_args = -F ../ssh-config
##### OS / ENVIRONMENT

Fedora and RHEL
##### SUMMARY
# Ansible 2.1.1.0

$ ansible-playbook -i hosts install/collectd-openstack.yml
...
# Executes successfully ^
# Now upgrade to Ansible 2.1.2.0

$ ansible-playbook -i hosts install/collectd-openstack.yml -vvvvvvv
Using /home/akrzos/code/browbeat-westfordperf/browbeat/ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0

PLAYBOOK: collectd-openstack.yml ***********************************************
4 plays in install/collectd-openstack.yml

PLAY [undercloud] **************************************************************

TASK [common : Check external connectivity] ************************************
task path: /home/akrzos/code/browbeat-westfordperf/browbeat/ansible/install/roles/common/tasks/main.yml:5
<undercloud> ESTABLISH SSH CONNECTION FOR USER: stack
<undercloud> SSH: ansible.cfg set ssh_args: (-F)(ssh-config)
<undercloud> SSH: ansible_password/ansible_ssh_pass not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<undercloud> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User=stack)
<undercloud> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=30)
<undercloud> SSH: PlayContext set ssh_common_args: ()
<undercloud> SSH: PlayContext set ssh_extra_args: ()
<undercloud> SSH: EXEC ssh -C -vvv -F ssh-config -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=stack -o ConnectTimeout=30 undercloud '/bin/sh -c '"'"'( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1476276870.23-135371457006881`" && echo ansible-tmp-1476276870.23-135371457006881="`echo $HOME/.ansible/tmp/ansible-tmp-1476276870.23-135371457006881`" ) && sleep 0'"'"''
fatal: [undercloud]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
    to retry, use: --limit @/home/akrzos/code/browbeat-westfordperf/browbeat/ansible/install/collectd-openstack.retry

PLAY RECAP *********************************************************************
undercloud                 : ok=0    changed=0    unreachable=1    failed=0  

The path relative ssh-config file is no longer found.  You can specific the full path and it will work again, however we would really like for our repo to be able to be git cloned and not have to teach an end user to manipulate his/her ansible.cfg.  This adds another step, especially when this wasn't in our previous workflow.  

Further analysis on ansible, shows the command working directory has changed from where "ansible-playbook" is initiated and the directory where the playbook is actually located, although ansible picks up the ansible.cfg from where the command is executed and not where the playbook is located

See this gist:
https://gist.github.com/akrzos/f672954d5f71fc190c1aee0b86bc6840
##### STEPS TO REPRODUCE

See above
##### EXPECTED RESULTS

I expected our playbooks not to be broken by upgrading from 2.1.1.0 to 2.1.2.0
##### ACTUAL RESULTS

Shown above

**Comment by akrzos** [comment]
Anyone know if this is also the behavior of Ansible 2.2?

**Comment by spiette** [comment]
I don't have this problem with version 2.2.0.0

**Comment by akrzos** [comment]
> I don't have this problem with version 2.2.0.0

Are you sure you tested this correctly?  Can you share output?  Perhaps your ssh-config was already in a path rather than only a relative-path.

**Comment by akrzos** [comment]
I retested this with 2.2.0.0 and it is fixed now.

https://gist.github.com/akrzos/413148aab75d9caf6d70585d47a74155

Looks just like >2.1.1.0 but <2.2.0.0 had an issue.

Closing.
