### ISSUE TITLE
Set "localhost" inventory vars via ansible.cfg

### ISSUE THREAD

**Issue by woody77** [ansible/ansible#18009]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

hostvars
connection: local
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel ee2e904824) last updated 2016/10/12 12:09:12 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 275fa3f055) last updated 2016/10/12 12:10:04 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 6c31d91fa5) last updated 2016/10/12 12:10:04 (GMT -700)
  config file = 
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

OSX + Anaconda Python (or Homebrew)
Ubuntu 16
RHEL 7
##### SUMMARY

To deal with multiple python environments, on my ansible host, I have the following inventory:

```
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"

<target inventory>
```

I'm using an ansible directory structure based on the standard (http://docs.ansible.com/ansible/playbooks_best_practices.html#directory-layout)

However, I want to be able to override the `localhost` `ansible_*` vars on a per-ansible-host basis (as multiple computers may be sharing the same ansible directory structure that's kept in git.

The `localhost` entry is special in that it's the only part of the system that's going to be running in different environments.  The managed hosts are all fixed environments, and easy to tailor.  But the localhost settings may need to be tailored per installation.

**Comment by Sodki** [comment]
You can already do that. Just configure the inventory to accept a variable (and provide a default) and then you can set it with `-e` option of `ansible-playbook`. Something like this:

`localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python ansible" ansible_foobar="{{ very_custom_var | default('') }}"`

And then

`ansible-playbook -e very_custom_var="something" ...`

You can even read it from an environment variable, if you want to.

**Comment by robinro** [comment]
I agree with @Sodki suggestion. ansible.cfg is not the place to put per-host local variables.

**Comment by woody77** [comment]
The inventory should be centrally managed, and therefore the inventory really shouldn't have per-ansible-host vars in it.

Now, if the inventory can use variables as @sodki suggests, and those vars are set in ansible.cfg, that's a likely solution.

Saying that `ansible-playbook` needs to be run with `-e some_override=foo` _every_ time you execute it isn't a great solution.  Better for it to be configured once, on the machine it's being run from, and then just works with `ansible-playbook some_playbook.yaml`.

**Comment by Sodki** [comment]
Potentially unrelated, but maybe useful: I find that running Ansible playbooks on their own is not very user friendly, so I tend to create wrapper scripts that launch playbooks. Could be interesting in this case.

**Comment by cognifloyd** [comment]
I use a directory as my inventory. In that directory I have various dynamic and yaml/ini inventories. In .gitignore I ignore local.ini so that I can change settings for localhost on a per machine basis. That way, I can mark whatever machine the playbooks are running on as ansible_connection=local.

**Comment by samdoran** [comment]
We have no plans to add this as a config option. Controlling this via host_vars is the recommended solution.
