### ISSUE TITLE
Collate more commands into one ssh roundtrip

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#1800]
If we would have an argument to `_execute_module()`, we could collate additional commands as part of the `_execute_module()` call. Especially when using sudo we can save an additional call for some of the action plugins (chmod for the transferred file, and chmod for the module itself).

Action plugins benefiting from this: `template`, `async` and `copy`.

**Comment by mpdehaan** [comment]
if you see places where this can be optimized further, I'm all for it.
