### ISSUE TITLE
Hosts file - myhost[1:1] interpreted as host11

### ISSUE THREAD

**Issue by edrozenberg** [ansible/ansible#18018]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

hosts file
##### ANSIBLE VERSION

```
ansible 2.1.2.0
```
##### SUMMARY

Using something like myhost[1:1] winds up getting picked up as myhost11 when connecting to the host.

```
[hosts_evo]
evo1[1:1]
```

```
TASK [setup] *******************************************************************
fatal: [evo11]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}

PLAY RECAP *********************************************************************
evo11                      : ok=0    changed=0    unreachable=1    failed=0   

```
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by amenonsen** [comment]
That's documented behaviour, not a bug. What were you expecting it to do?

**Comment by edrozenberg** [comment]
I'm pretty sure earlier Ansible would interpret myhost[1:1] as myhost1.
myhost11 does not make any sense. Thanks, Ed

**Comment by amenonsen** [comment]
You're writing `myhost[1:1]` in your description, but your actual hosts file says `evo1[1:1]`. Notice the 1 outside the square brackets. So the result is `'evo1'+1`.

**Comment by edrozenberg** [comment]
@amenonsen Thanks for catching that! Closing this issue, not a bug.
