### ISSUE TITLE
Alternative Directory Layout incorrect

### ISSUE THREAD

**Issue by pearj** [ansible/ansible#18022]
##### ISSUE TYPE
- Documentation Report
##### COMPONENT NAME

http://docs.ansible.com/ansible/playbooks_best_practices.html#alternative-directory-layout
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The http://docs.ansible.com/ansible/playbooks_best_practices.html#alternative-directory-layout says that inventory host files should be named `hosts.ini`, however, http://docs.ansible.com/ansible/intro_dynamic_inventory.html#using-inventory-directories-and-multiple-inventory-sources says that `.ini` files are ignored.  

The documentation should be updated so that instead of just `hosts.ini` it is `hosts.

**Comment by bcoca** [comment]
actually both things are true and not contradictory, but it is confusing.

The '.ini' CAN get ignored when you use the directory as an inventory source as they are assumed to be configuration files for dynamic inventory scripts. If you point at hosts.ini directly, it is NOT ignored and a perfectly valid inventory file.

**Comment by pearj** [comment]
Ahh right, so is the alternate directory layout using hosts.ini on purpose so that you aren't using dynamic inventory scripts?

**Comment by bcoca** [comment]
more or less, it is trying to show its still using that file as inventory, not the directory
