### ISSUE TITLE
any_errors_fatal doesn't work any more

### ISSUE THREAD

**Issue by amenonsen** [ansible/ansible#18021]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

core
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel cdb5a222c5) last updated 2016/10/13 22:54:15 (GMT +550)
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Setting `any_errors_fatal` on a play or task doesn't work; setting `max_fail_percentage: 0` does.

I notice that `plugins/strategy/linear.py` has code to deal with any_errors_fatal, but it doesn't look at `_play.any_errors_fatal` at all, only at the task attribute. But setting it on the task doesn't seem to work either. (I imagine we don't need to check the block attribute here, because the tasks will inherit it. Is that right?)
##### STEPS TO REPRODUCE

```

---
- hosts: localhost
  gather_facts: no
  tasks:
    - add_host: hostname=a ansible_connection=local
    - add_host: hostname=b ansible_connection=local
- hosts: all
  any_errors_fatal: yes
  tasks:
    - fail: msg=foo
      when: inventory_hostname == 'a'
      any_errors_fatal: yes
    - debug: msg=bar
```
##### EXPECTED RESULTS

b should not execute the debug.
##### ACTUAL RESULTS

b executes the debug.

**Comment by jimi-c** [comment]
Bisected to c669a381d117ccd96d4d59ab9191a107d08dfdb4 (which fixed #16937)
