### ISSUE TITLE
using dict for exit_json and fail_json, considering add_path_info and keys path/dest

### ISSUE THREAD

**Issue by davixx** [ansible/ansible#1803]
Hi,

About, https://github.com/ansible/ansible/pull/1788
I'm now using a dict in order to pass/update variables across functions.
(Like args/kwargs in many modules like "mount").

but i have a question :

https://github.com/ansible/ansible/blob/devel/lib/ansible/module_common.py#L604
    def exit_json(self, *_kwargs):
    def fail_json(self, *_kwargs):

Thoses functions take a second parameter '**kwargs) and call :
    self.add_path_info(kwargs)

Which do (just a part) :
    def add_path_info(self, kwargs):
        path = kwargs.get('path', kwargs.get('dest', None))
        if path is None:
            return kwargs

Must module developer HAVE TO not use "path" or "dest" key if is not wanted that state, mode, owner, etc to be added to kwargs dict ?

Or should we can think a way to disable this automatic treatment if not wanted ?

Thanks for your time.

**Comment by mpdehaan** [comment]
Hi David,

Can you please post questions on the mailing list and only leave this tracker for bugs?

That allows more people to help answer and allows us to keep the bug tracker on topic.

Thanks!
