### ISSUE TITLE
Unexpected host variables when using groups

### ISSUE THREAD

**Issue by Sirtea** [ansible/ansible#18046]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ansible core
##### ANSIBLE VERSION

```
root@toolbox:~/playbooks# ansible --version
ansible 2.1.1.0
  config file = /root/.ansible.cfg
  configured module search path = Default w/o overrides
root@toolbox:~/playbooks# 
```
##### CONFIGURATION

```
root@toolbox:~/playbooks# cat ../.ansible.cfg 
[defaults]
host_key_checking = False
inventory = /root/inventory
vault_password_file = /root/.vault-passfile
root@toolbox:~/playbooks# 
```
##### OS / ENVIRONMENT

debian 8.6 (ansible from backports)
##### SUMMARY

When using groups, host variables are not those on the host inside the group, but any arbitrary other declaration of the same host
##### STEPS TO REPRODUCE

Having an inventory as follows

```
root@toolbox:~/playbooks# cat ../inventory/hosts 
[backends]
castor role=backend1
pollux role=backend2

[backoffice]
castor role=backoffice
root@toolbox:~/playbooks# 
```

and a playbook like this:

```
root@toolbox:~/playbooks# cat test.yml 
- hosts: backends
  gather_facts: no
  tasks:
    - debug: var=role
- hosts: backoffice
  gather_facts: no
  tasks:
    - debug: var=role
root@toolbox:~/playbooks# 
```

I get the wrong variable for host _castor_ for the target given:

(see actual results below)
##### EXPECTED RESULTS

When using group _backends_, I expect to receive the _role_ variable for host _castor_ as declared on _backends_ definition, not the ones in _backoffice_ section.
##### ACTUAL RESULTS

I got a host variable from another group that the one that was used.

```
root@toolbox:~/playbooks# ansible-playbook test.yml 

PLAY [backends] ****************************************************************

TASK [debug] *******************************************************************
ok: [castor] => {
    "role": "backoffice"
}
ok: [pollux] => {
    "role": "backend2"
}

PLAY [backoffice] **************************************************************

TASK [debug] *******************************************************************
ok: [castor] => {
    "role": "backoffice"
}

PLAY RECAP *********************************************************************
castor                     : ok=2    changed=0    unreachable=0    failed=0   
pollux                     : ok=1    changed=0    unreachable=0    failed=0   

root@toolbox:~/playbooks# 
```

**Comment by Sodki** [comment]
I'm not sure you can do what you're trying to do. My understanding is that the inventory is only read once, before the playbook, so all host variables would have been decided by then. So it would not be an Ansible bug, but a misunderstanding of how the inventory works.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

As @Sodki mentions, Ansible flattens all vars BEFORE the play starts so a host will have vars defined by what groups it is part of in inventory, not by the group you target in a play.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
