### ISSUE TITLE
Failed to delegate a task to a Windows server on a local playbook

### ISSUE THREAD

**Issue by Sodki** [ansible/ansible#18066]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

I've had issues with both `win_ping` and `setup` when running the playbook.
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

ansible.cfg:

```
[defaults]
host_key_checking = False
inventory = inventory
retry_files_enabled = False
```
##### OS / ENVIRONMENT

Ubuntu 16.04.1
##### SUMMARY

When running a local playbook that delegates a task to a Windows server, the connection will fail.
##### STEPS TO REPRODUCE
- Get a Windows server
- Create an inventory file, for example `/tmp/ansible_hosts`, and configure it with the correct parameters to connect to the Windows server:

```
winserver ansible_host=192.168.1.100 ansible_user=Administrator ansible_password=abcd1234 ansible_port=5986 ansible_connection=winrm ansible_winrm_server_cert_validation=ignore 
```
- Create a sample playbook, for example `winplay.yml`. The usage of the variable in `hosts` is just to make things easier when testing:

```

---
- hosts: "{{  test_host }}"
  tasks:
    - win_ping:
      delegate_to: winserver
```
- Run the playbook:

`ansible-playbook -i /tmp/ansible_hosts winplay.yml -e test_host=winserver`

It runs successfully, which means that all the Windows server credentials and configuration are correct:

```
PLAY [winserver] ***************************************************************

TASK [setup] *******************************************************************
ok: [winserver]

TASK [win_ping] ****************************************************************
ok: [winserver -> 192.168.1.100]

PLAY RECAP *********************************************************************
winserver                  : ok=2    changed=0    unreachable=0    failed=0

```

Note: In this case the `delegate_to` is redundant. Removing it has the same result.
- Run the playbook against localhost:

`ansible-playbook -i /tmp/ansible_hosts winplay.yml -vvvv -e test_host=localhost`

Now it fails.
##### EXPECTED RESULTS

I would expect the playbook to finish successfully and to be able to obtain a connection to winserver.
##### ACTUAL RESULTS

`ansible-playbook -i /tmp/ansible_hosts winplay.yml -vvvv -e test_host=localhost`

We get the following result:

```
Using /home/sodki/ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0

PLAYBOOK: winplay.yml **********************************************************
1 plays in winplay.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: sodki
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1476661556.41-102152751962605 `" && echo ansible-tmp-1476661556.41-102152751962605="` echo $HOME/.ansible/tmp/ansible-tmp-1476661556.41-102152751962605 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpqY8tHo TO /home/sodki/.ansible/tmp/ansible-tmp-1476661556.41-102152751962605/setup
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/sodki/.ansible/tmp/ansible-tmp-1476661556.41-102152751962605/ /home/sodki/.ansible/tmp/ansible-tmp-1476661556.41-102152751962605/setup && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /usr/bin/python /home/sodki/.ansible/tmp/ansible-tmp-1476661556.41-102152751962605/setup; rm -rf "/home/sodki/.ansible/tmp/ansible-tmp-1476661556.41-102152751962605/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [win_ping] ****************************************************************
task path: /home/sodki/ansible/winplay.yml:4
<192.168.1.100> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO 192.168.1.100
fatal: [localhost]: UNREACHABLE! => {"changed": false, "msg": "ssl: (\"bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)\",)", "unreachable": true}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=1    failed=0   
```

Please note that it knows the connection has to be done via `winrm` and that the port and IP address of winserver are correct. I've also dumped `hostvars['winserver']` for debugging purposes and everything was correct, including the password:

```
ok: [localhost] => {
    "hostvars['winserver']": {
        "ansible_check_mode": false, 
        "ansible_connection": "winrm", 
        "ansible_host": "192.168.1.100", 
        "ansible_password": "abcd1234", 
        "ansible_port": 5986, 
        "ansible_user": "Administrator", 
        "ansible_version": {
            "full": "2.1.2.0", 
            "major": 2, 
            "minor": 1, 
            "revision": 2, 
            "string": "2.1.2.0"
        }, 
        "ansible_winrm_server_cert_validation": "ignore", 
        "group_names": [
            "ungrouped"
        ], 
        "groups": {
            "all": [
                "winserver"
            ], 
            "ungrouped": [
                "winserver", 
                "localhost"
            ]
        }, 
        "inventory_dir": "/tmp", 
        "inventory_file": "/tmp/ansible_hosts", 
        "inventory_hostname": "winserver", 
        "inventory_hostname_short": "winserver", 
        "omit": "__omit_place_holder__7f5701d29b64e66a5d05238292985f852de0a001", 
        "playbook_dir": "/home/sodki/ansible", 
        "test_host": "localhost"
    }
}
```

**Comment by Sodki** [comment]
I've also tried this on the latest `devel` version of Ansible, with the same results:

```
ansible 2.3.0 (devel d9b570aaae) last updated 2016/10/17 00:25:52 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 15f8c6835b) last updated 2016/10/17 00:26:03 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 4ca8e5347a) last updated 2016/10/17 00:26:07 (GMT +000)
  config file = 
  configured module search path = Default w/o overrides
```

**Comment by Sodki** [comment]
The backstory of this issue is that I want to be able to create a Windows server in EC2, with a newly created EC2 keypair, and then login and change the password to a well known value. So all the tasks in that playbook would be performed by localhost except one.

**Comment by Sodki** [comment]
@nitzmahone Sorry to bug you like this, but you seem to be dealing with Windows issues and this one is missing the `windows` label. Could you be so kind and add it, please?

**Comment by jhawkesworth** [comment]
I can add windows label for you.
You might be able to work around this issue by having multiple plays in your playbook.

```
hosts: localhost
(tasks here)

hosts: winserver
(windows tasks here)

hosts: localhost
(remaining tasks here)
```

**Comment by nitzmahone** [comment]
This is a known issue with the delegation connection rewriter and psuedo-connection vars (anything that's not one of the "well-known" connection vars like `ansible_connection`, `ansible_user`, eg, anything that starts with `ansible_winrm_`), where the delegating rewriter doesn't know to copy/remove those vars from the other host. We've got a plan to fix it, but it's somewhat invasive, so we punted it from 2.2.

You can work around it in the meantime by either adding `ansible_winrm_server_cert_validation=ignore` to localhost in your inventory or by using multiple plays as jhawkesworth suggested. Stand up the EC2 instance in a localhost play and `add_host` it to an existing empty group with the right vars set, then start a new play that targets the previously-empty group with the newly-added host.

There are about 10 copies of this bug already open, so I'm going to close this one.
