### ISSUE TITLE
filter plugins located in a playbook directory don't get loaded

### ISSUE THREAD

**Issue by x-yuri** [ansible/ansible#18092]
##### ISSUE TYPE
- Bug Report
- Documentation Report
##### COMPONENT NAME

loading filter plugins
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /home/yuri/_/1/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
# filter_plugins = filter
```
##### OS / ENVIRONMENT

Arch Linux
##### SUMMARY

[The doc](http://docs.ansible.com/ansible/developing_plugins.html#distributing-plugins) says:

> In addition, plugins can be shipped in a subdirectory relative to a top-level playbook, in folders named the same as indicated above.

But I fail to make it work.
##### STEPS TO REPRODUCE

`playbook.yml`:

``` yaml
- hosts: all
  vars:
    ansible_host: IP
    ansible_user: USER

  tasks:
    - debug:
        msg: '{{ "a*b" | quote_re }}'
```

`filter/plugins.py`:

``` python
import re

def quote_re(a):
  return re.escape(a)

class FilterModule(object):
    def filters(self):
        return {
            'quote_re': quote_re,
        }
```

```
$ ansible-playbook -i HOST, playbook.yml
```
##### EXPECTED RESULTS

This is what happens when I uncomment `filter_plugins` line in `ansible.cfg`:

```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [lxc]

TASK [debug] *******************************************************************
ok: [lxc] => {
    "msg": "a\\*b"
}

PLAY RECAP *********************************************************************
lxc                        : ok=2    changed=0    unreachable=0    failed=0
```
##### ACTUAL RESULTS

```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [lxc]

TASK [debug] *******************************************************************
fatal: [lxc]: FAILED! => {"failed": true, "msg": "template error while templating string: no filter named 'quote_re'. String: {{ \"a*b\" | quote_
re }}"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
lxc                        : ok=1    changed=0    unreachable=0    failed=1
```
##### MORE INFO

From [what](https://github.com/ansible/ansible/blob/99220a5/lib/ansible/plugins/__init__.py#L479-L484) I can [see](https://github.com/ansible/ansible/blob/99220a5/lib/ansible/constants.py#L268), there is nothing in the source that would load plugins from `filter` directory. Is it a documentation issue?

**Comment by bcoca** [comment]
the directory should be 'filter_plugins'
