### ISSUE TITLE
Dictionary values defaults

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#18102]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

dictionary parser
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

```
hash_behaviour = merge
```
##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

Please provide a way to define dictionary value defaults. For example, by introducing special key names, i.e `default_key`.
This way lengthy 'if' trees or 'default' filters could be avoided in tasks and templates, defaults definition would be as streamlined as with whole variables.
##### EXPECTED RESULTS

```
# defaults/main.yaml
hosts:
  default_key:
     production: false
     monitored: false

# vars/main.yaml
hosts:
  webserver:
    address: 10.2.3.4
    production: true
    # 'monitored' is not defined here

# tasks/main.yaml
- name: show hosts
  debug: msg="Host {{ item.key }}\n  Address {{ item.value.address }}\n  In prod {{ item.value.production }}    Monitored {{ item.value.monitored }}"
  with_dict: "{{ hosts }}"

$ ansible-playbook test.yaml 
PLAY [dnsmaster] *************************************************************
TASK [test : show hosts] ********************************************************
ok: [dnsmaster] => (item={'value': {u'production': True, u'monitored': False, u'address': u'10.2.3.4'}, 'key': u'webserver'}) => {
    "item": {
        "key": "webserver", 
        "value": {
            "address": "10.2.3.4", 
            "monitored": false, 
            "production": true
        }
    }, 
    "msg": "Host webserver    Address 10.2.3.4   in prod True    Monitored False"
}
```

**Comment by ssbarnea** [comment]
I think that a feature like this would be extremely helpful as it would allow us to avoid the very common bug of using the `somedic.foo.bar | default(xxx)` which always fails if foo is not defined.

@bregman-arie @wznoinsk @dsariel @mpryc

**Comment by samdoran** [comment]
There are two ways to do this:
1) Use YAML anchors
2) As of Ansible 2.8, the [`default` filter will handle this](https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.8.html#jinja-undefined-values).
