### ISSUE TITLE
The value of 'serial' in playbook cannot be set based on a variable defined per group

### ISSUE THREAD

**Issue by FlorinAndrei** [ansible/ansible#18111]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

playbook
##### ANSIBLE VERSION

```
ansible 1.9.4
  configured module search path = None
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Doing rolling updates with Ansible.

```
ansible-playbook -i production deploy.yml

ansible-playbook -i staging deploy.yml
```

```
$ cat deploy.yml

---
- hosts: api_frontend
  serial: 4

  pre_tasks:
    - name: "Gather EC2 facts from API nodes"
      ec2_facts:

    - name: "Remove node from ELB"
      local_action: ec2_elb
      args:
        instance_id: "{{ ansible_ec2_instance_id }}"
        region: "{{ aws.region }}"
        ec2_elbs: "{{ aws_api_lb }}"
        state: "absent"

  roles:
    - { role: api-deploy }

  post_tasks:
    - name: "Add node to ELB"
      local_action: ec2_elb
      args:
        instance_id: "{{ ansible_ec2_instance_id }}"
        region: "{{ aws.region }}"
        ec2_elbs: "{{ aws_api_lb }}"
        state: "present"
        wait_timeout: 30
```

The problem is, `serial: 4` works well in production, but the value is too large for staging. In staging I'd like to use `serial: 1`.

I've tried to define a variable such as `api_deploy_serial` in places like `production/group_vars/all/vars` (and also for staging), and used that to define the value for serial in the playbook, but it does not seem to be taken into account. Seems like variables are evaluated after serial is used in the playbook.

I do not want to maintain multiple deploy playbooks, one for each environment. That playbook needs to be created once, and pull variables from various environments for various behaviors. That's how config management is supposed to work.

Having multiple playbooks, one per environment, without the ability to template the behavior in the standard way, would be like a throw back to the bad old days of shell scripts.
##### STEPS TO REPRODUCE

If I do:

```
serial: "{{ api_deploy_serial | default(1) | int }}"
```

then only the default value is used, no matter what I add to `group_vars`.

```

```

##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Serial is set for the full play, as such it cannot vary by groups, the play runs directly against a list of hosts independent of which groups they belong to. In the hosts directive, groups are used to resolve the list of hosts but then are of no more consequence for the play.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by FlorinAndrei** [comment]
@bcoca That was disappointing.

There's no misunderstanding here. The actual behavior you're describing is what I say is wrong, and limits the flexibility of this software. I am not speaking from a theoretical ivory tower here, but from a practical perspective - _in practice_ you want your serial value to change based on where the playbook is being run. In some environments you want higher values for serial, in other environments you want lower values.

Please step out for a moment from the perspective of the coder, and look at Ansible from the perspective of the user. What we have here is a parameter that is hardcoded in a file, impossible to control via the usual strategies used for all other parameters. It's jarring because, again, _from the perspective of the user_ Ansible exhibits an inconsistency in its behavior.

**Comment by bcoca** [comment]
The misunderstanding is then that you want a feature added but opened a bug report.

**Comment by FlorinAndrei** [comment]
I see. Makes sense. I've opened a 'feature idea' issue instead.

https://github.com/ansible/ansible/issues/18131
