### ISSUE TITLE
problem with copy module and first_available_file when using relative paths

### ISSUE THREAD

**Issue by sfromm** [ansible/ansible#1815]
I'm not sure what to think of this, so I'm opening an issue for discussion.

Consider a copy task with first_available_file:

```
- action: copy src=$file dest=/etc/aide.conf
   first_available_file:
     - files/aide/aide.conf.${inventory_hostname}
     - files/aide/aide.conf
```

The file is correctly found in the block that looks up `first_available_file` at line https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/action_plugins/copy.py#L53.  The problem is that a second utils.path_dwim() call (https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/action_plugins/copy.py#L67) is made where the path is prepended (again) with the playbooks directory.  That is:
1. `source` set to `playbooks/files/aide/aide.conf` after first call to utils.path_dwim()
2. `source` set to `playbooks/playbooks/files/aide/aide.conf` after second call to utils.path_dwim()

First, this seems like a bug since the path was found at https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/action_plugins/copy.py#L58 and is later modified to a different path.  However, are relative paths to be discouraged?

If I were to submit a fix for this, I would modify path_dwim() to:

```
diff --git a/lib/ansible/utils/__init__.py b/lib/ansible/utils/__init__.py
index e547c1a..3163c6f 100644
--- a/lib/ansible/utils/__init__.py
+++ b/lib/ansible/utils/__init__.py
@@ -175,7 +175,7 @@ def path_dwim(basedir, given):
     elif given.startswith("~/"):
         return os.path.expanduser(given)
     else:
-        return os.path.join(basedir, given)
+        return os.path.abspath(os.path.join(basedir, given))
```

I haven't looked at all the cases where path_dwim() is called, but it seems that converting a relative path to an absolute one would have minimal impact.  If this change looks fine, I can submit the change.

**Comment by dhozac** [comment]
I thought I had already fixed this once, and sure enough, I did, but for the template module (00aa584). We should probably move this logic to utils so they share this code...

Only reason I know of for not doing abspath is that it would change the path in the messages, but that might just be a good thing.

**Comment by sfromm** [comment]
I think converting it to an absolute path would be a good thing.  PR #1818 (2100a35) submitted and merged.  Closing this.
