### ISSUE TITLE
inventory/playbook group_vars/<group> has high precedence than inventory file vars ，inventory file vars has high precedence than inventory/playbook group_vars/all

### ISSUE THREAD

**Issue by GoodHaHa** [ansible/ansible#18154]
##### ISSUE TYPE

- Documentation Report
##### COMPONENT NAME

N/A
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o override
```
##### SUMMARY

inventory/playbook group_vars/<group> has high precedence than inventory file vars ，inventory file vars has high precedence than inventory/playbook group_vars/all
##### STEPS TO REPRODUCE

Is document wrong? The results showed that the actual order of precedence(from low to high):
- playbook group_vars/all
- inventory group_vars/all 
- inventory file vars
- inventory group_vars/test
- playbook group_vars/test
### structure

```
├── hosts
│   └── inventory_test
│   └── group_vars
│      ├── all
│      └── ansible_test
└── playbook_var.yaml
```
### invertory:

```
# cat hosts/inventory_test 
[ansible_test:children]
group1
group2

[group1]
10.15.222.207

[group2]
10.15.222.208
10.15.222.209

[ansible_test:vars]
vars_test="in inventory"

[group1:vars]
vars_test="in group1"
```
### inventory group_vars/all :

```

cat hosts/group_vars/all 

---

vars_test: "in group_vars/all"
```
### inventory group_vars/ansible_test

```
# cat hosts/group_vars/ansible_test 

---

vars_test: "in group_all/ansible_test"
```
### If I use group_vars/ansible_test and group_vars/all, I can get:

```
# ansible-playbook --limit=ansible_test -i hosts/inventory_test playbook_var.yml 

PLAY [ansible_test] ************************************************************

TASK [setup] *******************************************************************
ok: [10.15.222.208]
ok: [10.15.222.207]
ok: [10.15.222.209]

TASK [debug] *******************************************************************
ok: [10.15.222.207] => {
    "msg": "in group_all/ansible_test"
}
ok: [10.15.222.208] => {
    "msg": "in group_all/ansible_test"
}
ok: [10.15.222.209] => {
    "msg": "in group_all/ansible_test"
}

PLAY RECAP *********************************************************************
10.15.222.207              : ok=2    changed=0    unreachable=0    failed=0   
10.15.222.208              : ok=2    changed=0    unreachable=0    failed=0   
10.15.222.209              : ok=2    changed=0    unreachable=0    failed=0   

```
### And then If I do not use group_vars/ansible_test but use group_vars/all, I can get:

```
# ansible-playbook --limit=ansible_test -i hosts/inventory_test playbook_var.yml 

PLAY [ansible_test] ************************************************************

TASK [setup] *******************************************************************
ok: [10.15.222.209]
ok: [10.15.222.207]
ok: [10.15.222.208]

TASK [debug] *******************************************************************
ok: [10.15.222.208] => {
    "msg": "in inventory"
}
ok: [10.15.222.207] => {
    "msg": "in group1"
}
ok: [10.15.222.209] => {
    "msg": "in inventory"
}

PLAY RECAP *********************************************************************
10.15.222.207              : ok=2    changed=0    unreachable=0    failed=0   
10.15.222.208              : ok=2    changed=0    unreachable=0    failed=0   
10.15.222.209              : ok=2    changed=0    unreachable=0    failed=0 
```

So I find the vars in the inventory group_vars/all  file will be overridden by in the inventory

**Comment by jctanner** [comment]
@GoodHaHa I wrote a test script to follow your description ...

```
[jtanner@fedmac AP-18154]$ cat test.sh 
#!/bin/bash
TESTDIR=/tmp/var_check
rm -rf $TESTDIR
mkdir $TESTDIR

cat << EOF > $TESTDIR/playbook_var.yml
- hosts: all
  connection: local
  gather_facts: False
  tasks:
    - debug: var=vars_test
EOF

mkdir -p $TESTDIR/hosts/group_vars
cat << EOF > $TESTDIR/hosts/inventory_test
[ansible_test:children]
group1
group2

[group1]
10.15.222.207

[group2]
10.15.222.208
10.15.222.209

[ansible_test:vars]
vars_test="in inventory"

[group1:vars]
vars_test="in group1"
EOF

echo 'vars_test: "in group_vars/ansible_test"' > $TESTDIR/hosts/group_vars/ansible_test




echo '### WITHOUT hosts/group_vars/all file'
rm -rf $TESTDIR/hosts/group_vars/all
cd $TESTDIR; ansible-playbook --limit=ansible_test -i hosts/inventory_test playbook_var.yml 

echo '### WITH hosts/group_vars/all file'
echo 'vars_test: "in group_vars/all"' > $TESTDIR/hosts/group_vars/all
cd $TESTDIR; ansible-playbook --limit=ansible_test -i hosts/inventory_test playbook_var.yml 
```

This is the result ....

```
###################################
v2.2.0.0-0.2.rc2
###################################
### WITHOUT hosts/group_vars/all file

PLAY [all] *********************************************************************

TASK [debug] *******************************************************************
ok: [10.15.222.208] => {
    "vars_test": "in group_vars/ansible_test"
}
ok: [10.15.222.207] => {
    "vars_test": "in group_vars/ansible_test"
}
ok: [10.15.222.209] => {
    "vars_test": "in group_vars/ansible_test"
}

PLAY RECAP *********************************************************************
10.15.222.207              : ok=1    changed=0    unreachable=0    failed=0   
10.15.222.208              : ok=1    changed=0    unreachable=0    failed=0   
10.15.222.209              : ok=1    changed=0    unreachable=0    failed=0   

### WITH hosts/group_vars/all file

PLAY [all] *********************************************************************

TASK [debug] *******************************************************************
ok: [10.15.222.208] => {
    "vars_test": "in group_vars/ansible_test"
}
ok: [10.15.222.207] => {
    "vars_test": "in group_vars/ansible_test"
}
ok: [10.15.222.209] => {
    "vars_test": "in group_vars/ansible_test"
}

PLAY RECAP *********************************************************************
10.15.222.207              : ok=1    changed=0    unreachable=0    failed=0   
10.15.222.208              : ok=1    changed=0    unreachable=0    failed=0   
10.15.222.209              : ok=1    changed=0    unreachable=0    failed=0   
```

Am I missing some detail in your description that makes my results differ from yours?

needs_info

**Comment by GoodHaHa** [comment]
@jctanner, Think you very much. 

Sorry I said not detailed enough. Here is not  `group_vars/all` file，is `group_vars/<group>` file which in my example is `group_vars/ansible_test` file. 

The group_vars/ansible_test file vars has the higher precedence than inventory file vars，but group_vars/all file vars not.

My expectation is that get the same result as the version 1.9x, which the inventory file vars has higher precedence than group_vars/all and group_vars/ansible_test.

**Comment by muratdx** [comment]
This is a behavior change in 2.x: group_vars/parent now has a higher precedence than a child group var defined in the inventory.

I had reported this already in #17361; another user also filed #17703. This was deemed a feature, not a bug.

The documentation is still a bit confusing in this regard. For example, the [Variables](http://docs.ansible.com/ansible/playbooks_variables.html) page mentions:

>  If this group is a child of the all group (**which it is, because all groups are**) ...

With the observed behavior, this statement would suggest that it's no longer possible to override group_vars/all entries in the inventory. However, you can still do this.

**Comment by xosofox** [comment]
@muratdx 

> this statement would suggest that it's no longer possible to override group_vars/all entries in the inventory

That is exactly what happens. `group_vars/all.yml`wins over `inventory/stage/group_vars/all.yml` which from my point of view is more than confusing.

I'm lost in terms of where to put inventory-specify variables now that are supposed to be valid for all hosts of a given inventory

**Comment by joshbenner** [comment]
@Xosofox: You identify that playbook vars override inventory vars. I agree that this is confusing/surprising, but is that what this issue is about?

**Comment by bcoca** [comment]
This matches the documented precedence, so I'm going to close as it is not an issue.
https://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

**Comment by coppit** [comment]
> This matches the documented precedence, so I'm going to close as it is not an issue.

At some point you should consider whether the spec needs to be changed. There are 3 bug reports for the same issue, and apparently a functional deficit caused by this change:

"I'm lost in terms of where to put inventory-specify variables now that are supposed to be valid for all hosts of a given inventory" (Comment echoed by another user in issue 17703.)

**Comment by kaneg** [comment]
For any others vars related definitions, most of them are following a common rule:  specific vars can override common vars. But for this case, the common ones always override specific ones. It is quite not intuitive, although the order has already been defined in the doc.  Thus, it is not a implementation bug, but a design bug.

**Comment by jmnavarrol** [comment]
> Thus, it is not a implementation bug, but a design bug.

This!

It's an implementation bug, and a bad one at that.  There's an (implicit) design pattern in that roles define general behaviour, playbooks an architectural design of those functionality items, and inventory, implementation details of such arch.  For the most part, variable precedence follows this pattern but then, having playbook-level variables overriding inventory-level ones, or global-level group variables overriding subgroup-level ones, not only makes no sense but makes ridiculously difficult to accomplish simply things, i.e:
1) role-level: ntp_server defaults to ntp.nasa.gov
2) playbook-level group_vars (maybe at the [all] group): ntp_server defaults to ntp.mycompany.com
3) inventory-level group_vars: ntp_server for [ntp-servers] defaults to myinternalclock.company.com
4) inventory-level host_vars: myinternalclock.company.com's ntp_server points to myatomicclock.company.com

(note that 3 and 4 will work as expected, and 1 versus 2-3 will also work properly; it's only 2 versus 3 precedence which goes nuts)

The expected precedence should be (from lower to higher): role default vars < playbook-level group vars < inventory-level group vars (supergroups < subgroups) < host_vars < command line

**Comment by bcoca** [comment]
@jmnavarrol since there are 5000 diff opinions on this when you put 20 people in a room, its now configurable (at least the group level):

http://docs.ansible.com/ansible/latest/installation_guide/_config.html?highlight=group%20precedence#variable-precedence

**Comment by jmnavarrol** [comment]
@bcoca That's good news (of course, I'd prefer the default to be what I said, since defaults matter, but still good to know).  Now, the question is: how is this issue still open, then?

**Comment by bcoca** [comment]
@jmnavarrol open? .... https://github.com/ansible/ansible/issues/18154#event-1036913438

**Comment by jmnavarrol** [comment]
> @jmnavarrol open? .... #18154 (comment)

My fault.  Don't know exactly why, but I reached to this issue following the open issues list; didn't notice this one was closed.

Anyway, your reason (I close this because precedence is described in doc) wasn't (IMHO) a reason and then, your first reference (http://docs.ansible.com/ansible/latest/installation_guide/_config.html?highlight=group%20precedence#variable-precedence) doesn't mention precedence is now configurable; only the second one from yesterday mentions it.

**Comment by andrew-sumner** [comment]
The document link for the variable_precedence setting is incorrect, it's: http://docs.ansible.com/ansible/latest/reference_appendices/config.html#variable-precedence

@bcoca Unless I'm missing something, the variable_precedence setting seems to have missed the mark. 
 There doesn't seem to be any way to get variables defined in inventories/&lt;environment&gt;/group_vars/[all | &lt;group&gt;] to override variables set in playbooks/group_vars/[all | &lt;group&gt;].

This is the setting I have tried using in ansible.cfg for my project:

[defaults]
variable_precedence = ['groups_inventory', 'all_inventory', 'all_plugins_inventory', 'all_plugins_play', 'groups_plugins_inventory', 'groups_plugins_play']

I've switched the first two settings but based on their names I suspect that this setting operates at the inventory level only and not within the playbook / inventory interaction.

I've always thought that the more specific you get to an environment (inventory) and group the higher the variable precedence should be rather than the approach that ansible has taken where the global generalized playbook variables take precedence.  It really seems to be a design bug so I was excited to see this configuration item - I just hope it works for my use case.

**Comment by joshbenner** [comment]
@andrew-sumner: This works for me:

```ini
precedence = all_plugins_play, all_inventory, all_plugins_inventory, groups_plugins_play, groups_inventory, groups_plugins_inventory
```

With this setup, inventory-based group_vars override playbook-based group_vars.

**Comment by andrew-sumner** [comment]
Thanks, that worked like a charm!  This has been bugging me since I first started using ansible so a huge relief to finally have a working solution.
