### ISSUE TITLE
Service module: enable option fails misleadingly with Upstart (Ubuntu/Fedora)

### ISSUE THREAD

**Issue by chrisberkhout** [ansible/ansible#1816]
The service module can start, stop and restart/reload services defined using Upstart, which is good.

When using the `enabled` parameter, the service module returns a value for `enabled`, which will match what is requested, but it's not actually changing anything (which means the returned value is incorrect), and the task aways is marked as `changed=false` (even when it should have changed something).

For example:

```
$ ansible gs.vm -m "service" -a "name=graphital state=stopped enabled=no"
gs.vm | success >> {
    "changed": false,
    "enabled": "no",
    "name": "graphital",
    "state": "stopped"
}

$ ansible gs.vm -m "service" -a "name=graphital state=stopped enabled=yes"
gs.vm | success >> {
    "changed": false,
    "enabled": "yes",
    "name": "graphital",
    "state": "stopped"
}

$ ansible gs.vm -m "service" -a "name=graphital state=stopped enabled=no"
gs.vm | success >> {
    "changed": false,
    "enabled": "no",
    "name": "graphital",
    "state": "stopped"
}
```

The best thing would be if it could enable and disable upstart services, but I think it would also be okay if it can't, as long as it doesn't return misleading results.

There are a [couple of ways to disable Upstart services](http://upstart.ubuntu.com/cookbook/#disabling-a-job-from-automatically-starting).

**Comment by mpdehaan** [comment]
Something you would like to submit a patch for?

**Comment by chrisberkhout** [comment]
Sorry Michael, I'm afraid it's not something I'll be able to get to quickly.
Mostly because I've never really done any Python.

**Comment by mpdehaan** [comment]
It's a good reason to start!   Ok, noted, you may want to bring this up on
the list to enlist some help, as I don't use Ansible with Ubuntu.

**Comment by mpdehaan** [comment]
are we still having problems with this?

**Comment by cocoy** [comment]
On my test  the changed status works. It returns the correct status using the current devel branch.

**Comment by mpdehaan** [comment]
Ok, glad it seems to be changing things.

I think we always report changed=True on the enablement state though, which should be easy enough to fix provided there is a reasonably standard way to do it.  We may end up relying on chkconfig to tell us if it is installed.

**Comment by mpdehaan** [comment]
I'm planning on making various cleanups to the system module shortly which should be able to detect if a service is upstart, sysV, or systemd and should resolve this issue along with some others.

**Comment by mpdehaan** [comment]
ignore previous comment, what @cocoy said is correct, it does return changed=yes all the time but that's another issue and I'll make sure that has a seperate ticket
