### ISSUE TITLE
Ansible reads all host_vars even when restricted by --limit

### ISSUE THREAD

**Issue by wolph** [ansible/ansible#18164]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME
- Reading of host_vars
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = project/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
vault_password_file = provisioning/vault_keychain.py
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

In many cases this is probably a non-issue, but in my case I have a local development machine which has all variables available in plain-text but the remote machines have ansible-vault encrypted files.

The problem I'm having right now is that ansible is reading the host_vars for other hosts than it needs to which results in errors decrypting the values. Which is silly since it doesn't need the values.
##### STEPS TO REPRODUCE
1. Create an encrypted host_vars file
2. Execute ansible with a --limit that does not include the above host_vars
##### EXPECTED RESULTS

Skip the irrelevant host_vars
##### ACTUAL RESULTS

Error that decryption didn't succeed (the machine doesn't have the encryption key and shouldn't need it).

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Inventory gets read BEFORE the play is initiated, vault files also need to be decrypted at this time.
It is not possible for Ansible to know at this stage that you won't use those variables as you can reference them even when a host is not targeted in play. Given that you can reference variables dynamically, they only way to know a vaulted variable is unused is to decrypt the vaulted file to figure out which variables it contains, run the play and check if they were not referenced.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by wolph** [comment]
It's debatable whether that's a desirable feature I think, but I understand the reasoning. Thanks for the quick response
