### ISSUE TITLE
vmware_inventory.py needs to fail if pyVmomi isn't installed 

### ISSUE THREAD

**Issue by phips** [ansible/ansible#18167]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

vmware_inventory.py
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

$ rpm -q ansible
ansible-2.2.0.0-100.git201610182035.bce9bfc.HEAD.el7.centos.noarch
```
##### OS / ENVIRONMENT

CentOS 7
##### SUMMARY

If pyVmomi isn't install the inventory script returns a python traceback, rather than exit with a helpful error message that pyVmomi is explicitly required.
##### STEPS TO REPRODUCE

```
./vmware_inventory.py
```
##### EXPECTED RESULTS

Something nice to be said that points out I need pyVmomi :-)
##### ACTUAL RESULTS

```
Traceback (most recent call last):
  File "./vmware_inventory.py", line 688, in <module>
    print(VMWareInventory().show())
  File "./vmware_inventory.py", line 128, in __init__
    self.do_api_calls_update_cache()
  File "./vmware_inventory.py", line 172, in do_api_calls_update_cache
    instances = self.get_instances()
  File "./vmware_inventory.py", line 324, in get_instances
    instances = self._get_instances(kwargs)
  File "./vmware_inventory.py", line 333, in _get_instances
    si = SmartConnect(**inkwargs)
NameError: global name 'SmartConnect' is not defined
```

.

**Comment by gundalow** [comment]
```
HAS_PYVMOMI = False
try:
    from pyVmomi import vim
    from pyVim.connect import SmartConnect, Disconnect
    HAS_PYVMOMI = True
except ImportError:
    pass
```

The only place that is checked is

```
if not HAS_PYVMOMI:
        vimTable = {}
    else:
        vimTable = {
            vim.Datastore: ['_moId', 'name'],
            vim.ResourcePool: ['_moId', 'name'],
        }
```

Which was added by @jctanner in

https://github.com/ansible/ansible/commit/05aed6e52ee35569548075d78341b197e23d140a

Should `vmware_inventory.py` be functional without `pyVmomi`?

**Comment by bcoca** [comment]
@gundalow no, but it should give 'useful' errors to user instead of tracebacks.

**Comment by Akasurde** [comment]
@bcoca I would like work on this.

**Comment by jctanner** [comment]
resolved_by_pr https://github.com/ansible/ansible/pull/26308
