### ISSUE TITLE
Parallelize running sub-playbooks within a main playbook

### ISSUE THREAD

**Issue by abhivijay89** [ansible/ansible#18177]
##### ISSUE TYPE
- Feature Idea
  Add support to parallelize running sub-playbooks within a main playbook.
##### SUMMARY

Feature to run sub-playbooks within a main playbook parallely. Currently, I don't see a way to achieve this. 'async' & 'with_items' doesn't seem to be supported with "include playbooks".

E.g.
< ## Main playbook >
< - include: playbook1.yml >
< - include: playbook2.yml >
< - include: playbook3.yml >

**Comment by jhawkesworth** [comment]
@abhivijay89 - see the discussion on https://github.com/ansible/proposals/issues/31 and specifically http://www.slideshare.net/bcoca/more-tips-n-tricks for some ways to run playbooks in parallel.

**Comment by bcoca** [comment]
closing this as dupe  of the proposal
