### ISSUE TITLE
Limited / Missing documentation for some Ansible jinja2 filters

### ISSUE THREAD

**Issue by geek0005** [ansible/ansible#18196]
##### ISSUE TYPE

- Documentation Report
##### COMPONENT NAME

playbooks_filters.rst
##### ANSIBLE VERSION

```

```
##### SUMMARY

Documentation for Ansible custom jinja2 filters doesn't contain some filters
On https://github.com/ansible/ansible/blob/devel/docsite/rst/playbooks_filters.rst / http://docs.ansible.com/ansible/playbooks_filters.html the changed/failed/succeeded/skipped filters are not mentioned.  They are only mentioned partially on http://docs.ansible.com/ansible/playbooks_conditionals.html.  Came across them in Redhat training course but appear not be documented properly
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by sivel** [comment]
The specified "filters" are actually documented as jinja2 tests at https://github.com/ansible/ansible/blob/devel/docsite/rst/playbooks_tests.rst / http://docs.ansible.com/ansible/playbooks_tests.html

If you have further questions please stop by IRC or the mailing list:
- IRC: #ansible on irc.freenode.net
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by geek0005** [comment]
Sorry for the false issue report.  Thanks for the details/links
