### ISSUE TITLE
Not using `{{` or `}}` in template file skips Jinja2 even when markers are overriden

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#18192]
Although this is an issue exhibited in a module, I suspect the code that causes this exists in this repository
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

Jinja2 templating
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
inventory = ./hosts
```
##### OS / ENVIRONMENT

**N/A** but Arch Linux

```
Linux [...] 4.8.4-1-ARCH #1 SMP PREEMPT Sat Oct 22 18:26:57 CEST 2016 x86_64 GNU/Linux
```
##### SUMMARY

Not using `{{` or `}}` at any point in a Jinja2 template causes the file not to be run through Jinja2, even when `variable_start_string` and `variable_end_string` is provided (and used throughout the file)
##### STEPS TO REPRODUCE

- Create a Jinja2 file with the following content
- Use the `template` directive

```
#jinja2: variable_start_string: '[%', variable_end_string: '%]'
" [% ansible_managed %]
```

Since neither `{{` nor `}}` occurs in the file, it is not run through Jinja2. Adding either will cause the expected results to appear (with the `{{` or `}}` in the rendered output)

##### EXPECTED RESULTS

```
" Ansible managed: [...]
```
##### ACTUAL RESULTS

```
#jinja2: variable_start_string: '[%', variable_end_string: '%]'
" [% ansible_managed %]
```

**Comment by pipern** [comment]
I found the same bug (ansible 2.2.0.0)

My example was:

```
cat >/tmp/sample.j2 <<EOF
#jinja2:variable_start_string:'<<' , variable_end_string:'>>', block_start_string:'<%', block_end_string:'%>'
<< ansible_managed >>
EOF
ansible --connection local -m template -a "src=/tmp/sample.j2 dest=/tmp/sample.txt" localhost,
cat /tmp/sample.txt
cat >/tmp/sample.j2 <<EOF
#jinja2:variable_start_string:'<<' , variable_end_string:'>>', block_start_string:'<%', block_end_string:'%>'
<< ansible_managed >>
{{
EOF
ansible --connection local -m template -a "src=/tmp/sample.j2 dest=/tmp/sample.txt" localhost,
cat /tmp/sample.txt
```

I confirm https://github.com/ryanpineo/ansible/commit/2ec3338d4d8ac3ebcfd919e19a6a0342f1fb58b7?diff=unified fixes this.

**Comment by bcoca** [comment]
@ghost  can you confirm that #18490 fixes this for you too?

**Comment by saleemrashid** [comment]
@bcoca @ghost means that the user has been deleted.

The deleted user is in fact mine and I will try with this commit as soon as possible, thanks
