### ISSUE TITLE
Ubuntu 16.10 Yakkety Yak deb packages in ppa:ansible/ansible

### ISSUE THREAD

**Issue by prydie** [ansible/ansible#18209]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

N/A
##### ANSIBLE VERSION

N/A
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Ubuntu 16.10 Yakkety Yak
##### SUMMARY

Ubuntu 16.10 Yakkety Yak has been out for a little while now. Please consider adding a yakkety Release of the official Ansible deb packages for Ubuntu to the Ansible PPA: https://launchpad.net/~ansible/+archive/ubuntu/ansible
##### STEPS TO REPRODUCE

```
sudo apt-add-repository ppa:ansible/ansible
sudo apt update
```

##### EXPECTED RESULTS

Ansible package list downloaded successfully.
##### ACTUAL RESULTS

Ansible package list fails to download.

```
...
...
Err:5 http://ppa.launchpad.net/ansible/ansible/ubuntu yakkety Release                                                
  404  Not Found
```

**Comment by mircea-vutcovici** [comment]
It seems that ansible is part of the distribution now and you do not need a ppa. See: https://launchpad.net/ubuntu/yakkety/+package/ansible
However it doesn't contain yet the latest ansible version (2.2)

**Comment by nmeyer-otto** [comment]
+1 on this. although there seems to be no harm running the version from xenial ppa. 

One of the reasons to use a PPA is to have the current upstream version, and it's unlikely that Ubuntu will update in a timely fashion (or at all?).

**Comment by Akasurde** [comment]
Closing this issue as package is available [here](https://launchpad.net/~ansible/+archive/ubuntu/ansible/+packages).
