### ISSUE TITLE
Building deb from sources requires a2x utility 

### ISSUE THREAD

**Issue by Zloy** [ansible/ansible#18207]
##### ISSUE TYPE
- Documentation Report
##### COMPONENT NAME

???
##### ANSIBLE VERSION

Revision 0a1f3918819151b6c12596c0675609d2f50d02ce
##### CONFIGURATION

n/a
##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

Couldn't build a deb package
##### STEPS TO REPRODUCE

Get clean Ubuntu, then clone the repo

```
cd ansible
make deb
...
sed "s/%VERSION%/2.3.0/" docs/man/man1/ansible.1.asciidoc.in > docs/man/man1/ansible.1.asciidoc
ERROR: AsciiDoc 'a2x' command is not installed but is required to build docs/man/man1/ansible.1 docs/man/man1/ansible-playbook.1 docs/man/man1/ansible-pull.1 docs/man/man1/ansible-doc.1 docs/man/man1/ansible-galaxy.1 docs/man/man1/ansible-vault.1
make: *** [docs/man/man1/ansible.1] Error 1
```
##### EXPECTED RESULTS

all needed dependencies I expect to be mentioned on Installlation page. Nope.
##### ACTUAL RESULTS

I had to find out which package a2x belongs to. A found out that package is asciidoc, which is HUGE!!!
I had to install all that X GUI crap to my server box. Sad but true.

**Comment by Zloy** [comment]
Also!!! **devscripts** which contains **debuild**

**Comment by Zloy** [comment]
Also!!! **cdbs** and **debhelper**

**Comment by Zloy** [comment]
Also!!! The deb package appeared guess where? 

`./deb-build/unstable/ansible_2.3.0-100.git201610261521.0a1f391.devel~unstable_all.deb`

**Comment by alikins** [comment]
> all needed dependencies I expect to be mentioned on Installlation page. Nope.

Yup, installation docs don't currently cover building packages, but probably should.

'asciidoc' is one of the Build-Depends listed in packaging/debian/control though.

**Comment by companycy** [comment]
Agree with Zloy. Package asciidoc is quite huge.
Any other solution? I mean, only necessary packages should be required.

**Comment by bcoca** [comment]
obsolete since we moved to rst2man
