### ISSUE TITLE
conditional include + include_vars + loop => kaboom

### ISSUE THREAD

**Issue by duck-rh** [ansible/ansible#18218]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

include
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /home/duck/project/ansible.cfg
  configured module search path = Default w/o overrides
```

This is 2.1.3.0~rc1-1.
##### CONFIGURATION

only the role path was changed.
##### OS / ENVIRONMENT

Debian unstable both
##### SUMMARY

undefined variables in loop were deprecated and now cause an error, but dynamic assignment is not taken into account in case of conditional include
##### STEPS TO REPRODUCE

The playbook 'test.yml':

```

---
- hosts: all
  vars:
    b: False
  tasks:
    - include: inc.yml
      when: b
```

inc.yml contains:

```

---

- include_vars: vars.yml

- debug:
    msg: "{{ item }}"
  with_items: "{{ list }}"
```

and vars.yml contains:

```

---
list:
  - "coucou les amis"
```
##### EXPECTED RESULTS

the tasks in inc.yml should be skipped without error.
##### ACTUAL RESULTS

```
TASK [debug] *******************************************************************
fatal: [myhost.mydom.tld]: FAILED! => {"failed": true, "msg": "'list' is undefined"}
```

If the condition is removed it works fine, so there is no problem with dynamic variables in itself, only the undefined variable test fails.

I don't know why the include action originally behaves like this (adding a fake when on all inside actions) instead of dynamically adding tasks during the play, but clearly this leads to weird behaviors.

**Comment by OrBaruk** [comment]
I think this is a similar issue i found with using `include` and `when` 
https://github.com/ansible/ansible/issues/18206

**Comment by duck-rh** [comment]
similar but maybe not the same. would be nice to check the two test cases when a solution is drafted,

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The issue here is that the top level include is 'static' so the `when` clause does not apply to it, it is inherited by the tasks inside. 

As is documented a `when` clause cannot short circuit a `with_` as it runs per item, so this is not a bug. 
http://docs.ansible.com/ansible/playbooks_conditionals.html#loops-and-conditionals

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by duck-rh** [comment]
I disagree. The fact you implement the when+include internally this way is not the user's concern. What you point out is using with_items+when, which is not what I did directly in my playbook.

I'm discussing some behavior that is clearly counter-intuitive, so it should be improved. At the very least the documentation should be updated to explain the limitation.

**Comment by duck-rh** [comment]
Would you please reconsider?
This means it is no longer possible to have a variable local to the include using set_fact, and that each petty variable has to have a global default. Also it is breaking a lot of existing roles for no good reasons.

**Comment by amenonsen** [comment]
@duck-rh: you can set `static: no` on the outer include task to make it work the way you want (which I also think is the sensible and unsurprising way for it to work).

P.S. Note that `set_fact` isn't in any sense local to the include.

**Comment by duck-rh** [comment]
I think the static/dynamic way of includes is really not trivial, and a friend helped me understand more. it feels wrong to have to give hints to Ansible instead of finding out by himself I'm using a dynamic variable. it's still is a workaround, but an acceptable one, thanks @amenonsen. task_includes_dynamic could have been useful to simplify this.

yes, it was not appropriate to says "local". it is defined and used only in the included file, so I see no reason to declare it outside (even if it's in the global namespace anyway).
