### ISSUE TITLE
Tower install with Ubuntu 14 will not work with EOS 4.17+ with cli transport

### ISSUE THREAD

**Issue by phil-dileo** [ansible/ansible#18261]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Package dependencies

##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Installation provided through Tower ``setup`` script. No existing Ansible environment setup.

##### OS / ENVIRONMENT
```
$ uname -a
Linux ubuntu 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
I would think this issue applies to more than one distro.

##### SUMMARY

The Paramiko version that gets installed with apt-get install ansible on Ubuntu 14 does not work with EOS 4.17+.  The reason is EOS 4.17 uses a newer version of OpenSSH server that's incompatible with pycrypto and older versions of paramiko (~1.x)

##### STEPS TO REPRODUCE
1. Install Ubuntu 14.04
2. Install Tower with setup.sh
3. Run a playbook with transport==cli against EOS 4.17

To fix this you have to install Cryptography and upgrade Paramiko.
```
sudo apt-get install -y python-dev libssl-dev libffi-dev
sudo pip install cryptography
sudo pip install -U paramiko
``` 

```
- name: Gather EOS configuration
  eos_command:
    commands: 'show running-config all'
    provider: "{{ provider }}"
  register: output
```

##### EXPECTED RESULTS

The module should connect with Paramiko and run the command.

##### ACTUAL RESULTS

```
fatal: [dc1-spine1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "No handlers could be found for logger \"paramiko.transport\"\nTraceback (most recent call last):\n  File \"/tmp/ansible_lLOX9Q/ansible_module_eos_command.py\", line 181, in <module>\n    main()\n  File \"/tmp/ansible_lLOX9Q/ansible_module_eos_command.py\", line 151, in main\n    response = module.execute(commands)\n  File \"/tmp/ansible_lLOX9Q/ansible_modlib.zip/ansible/module_utils/eos.py\", line 248, in execute\n  File \"/tmp/ansible_lLOX9Q/ansible_modlib.zip/ansible/module_utils/eos.py\", line 216, in connect\n  File \"/tmp/ansible_lLOX9Q/ansible_modlib.zip/ansible/module_utils/eos.py\", line 164, in connect\n  File \"/tmp/ansible_lLOX9Q/ansible_modlib.zip/ansible/module_utils/shell.py\", line 108, in open\n  File \"/usr/lib/python2.7/dist-packages/paramiko/client.py\", line 306, in connect\n    t.start_client()\n  File \"/usr/lib/python2.7/dist-packages/paramiko/transport.py\", line 465, in start_client\n    raise e\nparamiko.SSHException: Incompatible ssh peer (no acceptable kex algorithm)\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

**Comment by phil-dileo** [comment]
@gundalow

**Comment by gundalow** [comment]
@phil-dileo Can you please provide (sanitised) copy of `provider`.

**Comment by phil-dileo** [comment]
```
provider:
  host: '{{ ansible_host }}'
  username: admin
  password: admin
  authorize: true
  use_ssl: no
  transport: cli
```

**Comment by gundalow** [comment]
@phil-dileo Thanks

/cc @privateip @Qalthos

**Comment by phil-dileo** [comment]
For the https://github.com/ansible/test-network-modules repo, which version(s) of EOS do you test against? Do you run the playbooks from different control hosts with various packages?

**Comment by gundalow** [comment]
I run `ansible-playbook` on a Ubuntu 16.04 machine.

device: veos01 (vEOS, EOS-4.15.4F)

**Comment by gundalow** [comment]
Hi, please raise this with the Tower Support Team
https://support.ansible.com/hc/en-us/requests/new
