### ISSUE TITLE
Additions to Who Uses Ansible page

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1828]
per user request

Tent.is

Nimbis Services <www.nimbisservices.com> - Technical computing in the cloud

(also sort the list again)

**Comment by mpdehaan** [comment]
also:

Eucalyptus Systems

**Comment by lsemel** [comment]
You can also add my sites
Shorty Awards http://shortyawards.com
Muck Rack http://muckrack.com

**Comment by mpdehaan** [comment]
all done, will be available in the next docs push
