### ISSUE TITLE
The Ansible project should maintain release notes

### ISSUE THREAD

**Issue by dead10ck** [ansible/ansible#18285]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

Ansible project as a whole

##### SUMMARY

Ansible should have release notes. It helps inform users about any new features, deprecations, bug fixes, breaking changes, etc., etc. The only source of information I've been able to find about changes between releases is the blog, which doesn't fill the whole picture, and is harder to skim for important bits than a more traditional page of release notes. For example, for the most recent 2.2 release, [this blog post](https://www.ansible.com/blog/ansible-network-updates) is the only info I've been able to find for information about changes, but it focuses solely on networking changes. But there are [over 1800 commits](https://github.com/ansible/ansible/compare/stable-2.1...stable-2.2) between 2.1 and 2.2, so surely there must be more than networking changes.

**Comment by Shaps** [comment]
Hi @dead10ck have you had a look at [CHANGELOG.md](https://github.com/ansible/ansible/blob/devel/CHANGELOG.md) ?

**Comment by dead10ck** [comment]
Doh, apparently I'm blind.
