### ISSUE TITLE
ignore_errors="{{ False }}" not failing the playbook on task failure

### ISSUE THREAD

**Issue by adityamarella** [ansible/ansible#18289]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
Ansible Core

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

ubuntu-14.04

##### SUMMARY
ignore_errors: "{{ False }}" should fail the playbook when the task fails. This is broken in 2.2.0.0 release, it was working as expected in 2.1.0.0. This could be a more generic problem with jinja template boolean translation. I have only observed this with ignore_errors but it could very well be happening with other properties.

##### STEPS TO REPRODUCE

Run the playbook test.yml first with ansible 2.1.0.0 and then with ansible 2.2.0

```
# test.yml

---
- name: test playbook
  hosts: 127.0.0.1
  connection: local
  vars:
    flag: False
  tasks:
    # purposefully provided an invalid url to fail the task
    - uri: url=http://www.fail12345.com
      ignore_errors: "{{ flag }}"
    - debug: msg="Here"
```

```
ansible-playbook test.yml --connection=local
```

##### EXPECTED RESULTS
ignore_errors: "{{ False }}" should fail the playbook when the task fails. This is broken in 2.2.0.0 release, it was working as expected in 2.1.0.0

##### ACTUAL RESULTS
ansible 2.1.0.0: ignore_errors: "{{ False }}" fails the playbook when the task fails (expected)
ansible 2.2.0.0: ignore_errors: "{{ False }}" does not fail the playbook when the task fails (bug?)

**Run with ansible 2.1.0.0**
```
PLAY [test playbook] ***********************************************************

TASK [setup] *******************************************************************
ok: [127.0.0.1]

TASK [uri] *********************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Request failed: <urlopen error [Errno -2] Name or service not known>", "redirected": false, "status": -1, "url": "http://www.fail12345.com"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @test.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1   


```

**Run with ansible 2.2.0.0**
```
PLAY [test playbook] ***********************************************************

TASK [setup] *******************************************************************
ok: [127.0.0.1]

TASK [uri] *********************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Request failed: <urlopen error [Errno 8] nodename nor servname provided, or not known>", "redirected": false, "status": -1, "url": "http://www.fail12345.com"}
...ignoring

TASK [debug] *******************************************************************
ok: [127.0.0.1] => {
    "msg": "Here"
}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=3    changed=0    unreachable=0    failed=0   
```

**Comment by adityamarella** [comment]
This commit d2b3b2c03e2934b126f5701e5f6e25821e2dbe35 is the reason for this issue. @jimi-c I added a comment to your commit which is breaking `ignore_errors`

**Comment by adityamarella** [comment]
@jimi-c please note that d2b3b2c03e2934b126f5701e5f6e25821e2dbe35 could have broken other attributes as well.

**Comment by jimi-c** [comment]
Closing This Ticket
===================

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by adityamarella** [comment]
@jimi-c verified that the commit fixes `ignore_errors` issue. Thanks.
