### ISSUE TITLE
debug module does not handle some variables handled by template

### ISSUE THREAD

**Issue by davixx** [ansible/ansible#1829]
Hi,

Somes variables, are not interpreted in debug module.
_it seems that only ones statically declared in playbooks vars section are interpretted_

**inventory.file** :

```
[aservergroup]
srv1720.example.net inventory_host_variable="super! i'm the value in the invetory file"
```

**templates/test.j2** :

```
my inventory host variable is <{{ inventory_host_variable }}>
and ansible_product_uuid from setup is <{{ ansible_product_uuid }}>
the playbook local var is <{{ playbook_local_var }}>
```

**Playbook sample** :

```

---
- name: Install Gentoo64 stage4 on a host in rescue
  hosts: srv1720.example.net
  user: root

  vars:
    playbook_local_var: "great! i'm the value in playbook vars"

  tasks:

    - debug: msg="inventory_host_variable <${inventory_host_variable}> ; ansible_product_uuid <${ansible_product_uuid}> ; playbook_local_var <${playbook_local_var}>"
    - template: src=./templates/test.j2 dest=/tmp/test.txt owner=root group=root mode=0600
```

_**Generated output**_ :

> TASK: [debug msg="inventory_host_variable &lt;${inventory_host_variable}&gt; ; ansible_product_uuid &lt;${ansible_product_uuid}&gt; ; playbook_local_var &lt;great! i'm the value in playbook vars&gt;"] ********************\* 
> ok: [srv1720.example.net]
> 
> TASK: [template src=./templates/test.j2 dest=/tmp/test.txt owner=root group=root mode=0600] ********************\* 
> changed: [srv1720.example.net]

_**Generated file**_ :

> my inventory host variable is &lt;super! i'm the value in the invetory file&gt;
> and ansible_product_uuid from setup is &lt;44454C4C-4200-1042-8057-C3C04F47354A&gt;
> the playbook local var is &lt;great! i'm the value in playbook vars&gt;

**Comment by dhozac** [comment]
You're looking at the task name. The name is the same for all hosts, and host-specific variables won't be expanded there. Use -vvv to see the result of debug.
