### ISSUE TITLE
Unable to import custom module from an Ansible custom module.

### ISSUE THREAD

**Issue by ruissalo** [ansible/ansible#18293]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
Module search paths

##### ANSIBLE VERSION

```
ansible --version
ansible 2.2.0.0
```

##### SUMMARY
I wrote a custom Python module "A" that is correctly found and used by an Ansible playbook.
From that custom module "A" I need to import another custom module "B". 

Problem: Ansible fails to load module B from module A. I tried putting module B in the same directory as module A with no luck (there is an __init__.py file there too). What would be the best way to accomplish this?

I tried using the Ansible API from a script C. From script C I'm able to load both modules A and B.
Apparently the python search path changes from a module run time environment.
Moving custom module "B" into the ansible utils directory fixes the issue.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible-devel on irc.freenode.net  
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by jose-delarosa** [comment]
@ruissalo, where you able to find an answer for your question. I am having a similar issue, where my I can't import a custom python module from my custom Ansible module.
