### ISSUE TITLE
"Porting custom scripts" link results in 404 page in "Porting Guide" document 

### ISSUE THREAD

**Issue by caseyzub** [ansible/ansible#18290]
##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
- Documentation 

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
"Porting custom scripts" link results in 404 page in "Porting Guide" document 

##### STEPS TO REPRODUCE
1. Navigate to this documentation page: http://docs.ansible.com/ansible/porting_guide_2.0.html#porting-custom-scripts
2. Click on this link at the bottom of the page: https://github.com/ansible/ansible/blob/devel/docsite/rst/developing_api.rst

##### EXPECTED RESULTS
I see a document about porting custom scripts.

##### ACTUAL RESULTS
I see a 404 page.

**Comment by Shaps** [comment]
Hi @caseyzub, thanks for this, this is indeed an issue, as those guides have been moved. While this gets fixed, you can access the page from here: [https://docs.ansible.com/ansible/dev_guide/developing_api.html](https://docs.ansible.com/ansible/dev_guide/developing_api.html)

**Comment by gundalow** [comment]
I'll fix that today, and see if we have any other hard coded links to `github.com/ansible/ansible/blob` in `docsite/rst/`

**Comment by Akasurde** [comment]
Closing this issue as PR https://github.com/ansible/ansible/pull/27632 is merged. If issue persists, please feel free to re-open.
