### ISSUE TITLE
Ansible Tower inventory import won't import host vars nested in directories named after the host.

### ISSUE THREAD

**Issue by mikeycmccarthy** [ansible/ansible#18304]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Tower - specifically 'tower-manage inventory_import'

##### ANSIBLE VERSION
```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
CentOS Linux release 7.2.1511 (Core)

##### SUMMARY
Using the Tower inventory import functionality won't import per host variables that are nested in directories under host_vars.

##### STEPS TO REPRODUCE
Consider a directory structure like this:
```
.
├── group_vars
│   ├── a_servers.yml
│   ├── all.yml
│   ├── b_servers.yml
│   ├── application_servers.yml
│   ├── c_servers.yml
│   ├── d_servers.yml
│   ├── e_servers.yml
│   ├── f_servers.yml
│   ├── g_servers.yml
│   └── h_servers.yml
├── host_vars
│   ├── host-a
│   │   ├── private.yml
│   │   └── public.yml
│   ├── host-b
│   │   ├── private.yml
│   │   └── public.yml
│   └── host-c
│       ├── private.yml
│       └── public.yml
└── inventory
```
If I run this using ansible (outside of Tower), the host vars from host_vars/host_b/public.yml for example will be available (we use the naming convention public and private for vaulted/non-vaulted). When we import using the Tower inventory import feature, these variables are not in the generated inventory files.

##### EXPECTED RESULTS
Variables inside the file 'public.yml' are listed under the host in the inventory imported into Tower.

##### ACTUAL RESULTS
Variables inside the file 'public.yml' are NOT listed under the host in the inventory imported into Tower.

**Comment by Shaps** [comment]
Hi @mikeycmccarthy. `tower-manage` is part of Ansible Tower, not part of the open source project. For questions related to it you should email support@ansible.com

**Comment by gundalow** [comment]
@mikeycmccarthy We are migrating off email for support to using the Red Hat Portal, to be inline with the rest of Red Hat.

So for Ansible Tower support please create a ticket in the Red Hat Portal that can be accessed via https://access.redhat.com/

**Comment by mikeycmccarthy** [comment]
Thanks all, will do.
