### ISSUE TITLE
validate-modules: Ensure __init__.py (under modules) are empty

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#18308]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

validate-modules
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 5502da3cf8) last updated 2016/10/25 11:22:53 (GMT +100)
  lib/ansible/modules/core: (devel 4c020102a9) last updated 2016/10/25 11:22:57 (GMT +100)
  lib/ansible/modules/extras: (devel 8f77a0e72a) last updated 2016/10/25 11:22:59 (GMT +100)
  config file = 
```
##### SUMMARY

The `__init.__py` files under modules must be empty. They are not allowed to be used to share code between modules

Also this need adding to the list of checks in `test/sanity/validate-modules/README.rst`

**Comment by mattclay** [comment]
This is covered by [empty-init.sh](https://github.com/ansible/ansible/blob/devel/test/sanity/code-smell/empty-init.sh) in the code-smell tests.

Since we won't need this in two places after the repository merge, I recommend closing this issue.

**Comment by gundalow** [comment]
Ah, cool. Didn't know we have that already. Closing this. Thanks
