### ISSUE TITLE
Ansible Python API 2.0 module has missing dependencies.

### ISSUE THREAD

**Issue by monokal** [ansible/ansible#18303]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Ansible API Python module.

##### ANSIBLE VERSION

```
ansible --version
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
None.

##### OS / ENVIRONMENT
Reproduced on CentOS, Ubuntu and MacOS.

##### SUMMARY
Having installed the Ansible API Python module via `pip install ansible` on various platforms the following error is reproducible when trying to run a Python script the the imports documented here: http://docs.ansible.com/ansible/dev_guide/developing_api.html#python-api-2-0 
```
Traceback (most recent call last):
...
    from ansible.executor.task_queue_manager import TaskQueueManager
ImportError: No module named executor.task_queue_manager
```

##### STEPS TO REPRODUCE
```
...
from ansible.executor.task_queue_manager import TaskQueueManager
from ansible.inventory import Inventory
from ansible.parsing.dataloader import DataLoader
from ansible.playbook.play import Play
from ansible.plugins.callback import CallbackBase
from ansible.vars import VariableManager
...

```

##### EXPECTED RESULTS
Module imports and script runs.

##### ACTUAL RESULTS
```
Traceback (most recent call last):
...
    from ansible.executor.task_queue_manager import TaskQueueManager
ImportError: No module named executor.task_queue_manager
```

**Comment by Shaps** [comment]
Hi @monokal, just tested on a clean Ubuntu 16.04 and OSX, ran the script from the docs page and worked correctly. Can you confirm ansible is available in your `PYTHONPATH`?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible-devel on irc.freenode.net  
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by abadger** [comment]
Note since your error appears to have imported "ansible " okay but not "ansible.executor" I'd check to see if you have an ansible-1.x install somewhere that's being found rather than ansible-2.x.  2.x introduced executor and removed runner as the main engine inside of ansible.
