### ISSUE TITLE
Symlinked executable vault password files should be invoked by their original path, not real path

### ISSUE THREAD

**Issue by jmehnle** [ansible/ansible#18319]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`--vault-password-file`

##### ANSIBLE VERSION
```
ansible 1.9.3
```
(but also occurs in Ansible 2)

##### DESCRIPTION
When specifying an executable vault password file, Ansible invokes it by its "real" path, not by the path as specified. This matters if what's passed is actually a *symlink* to an executable, and the executable uses the path by which it is invoked to determine the password to produce.

For example:

```
$ ls -l
total 16
-rwxr-xr-x  1 julian  staff  290 Nov  2 23:03 get-password
-rw-------  1 julian  staff  355 Nov  2 23:10 secrets.yml
```

`secrets.yml` is a dummy variables vault file created by `ansible-vault create` with the password `foo-bar-ansible`.

```
$ cat get-password
#!/bin/sh

basename="$(basename $0)"
basename_prefix="get-password"
default_password="foo-bar"

case "${basename}" in
  "${basename_prefix}"-*)
    password="${default_password}-${basename#${basename_prefix}-}"
    ;;
  *)
    password="${default_password}"
    ;;
esac

echo "${password}"
```

This script produces the password `foo-bar` if invoked directly, but produces a different password when invoked through a symlink that begins with `get-password-`, e.g., `foo-bar-quux` when invoked as `get-password-quux`. This script is a synthetic example, but I actually use this mechanism with a more complicated password retrieval script that installs various symlinks for different applications, Ansible being one of them.

Now lets create a symlink with a suitable name:

```
$ ln -s get-password get-password-ansible
$ ls -l get-password*
-rwxr-xr-x  1 julian  staff  290 Nov  2 23:03 get-password
lrwxr-xr-x  1 julian  staff   12 Nov  2 23:24 get-password-ansible -> get-password
$ ./get-password
foo-bar
$ ./get-password-ansible
foo-bar-ansible
$ ansible all -i localhost, -c local -a uptime -e @secrets.yml --vault-password-file get-password-ansible
ERROR: Decryption failed
```

Oops. We're invoking `get-password-ansible`, which as we just saw, produces the correct password, `foo-bar-ansible`. What gives?

Well, now let's try replacing the symlink with a straight-up copy of the real file:

```
$ rm -f get-password-ansible
$ cp get-password get-password-ansible
$ ls -l get-password*
-rwxr-xr-x  1 julian  staff  290 Nov  2 23:03 get-password
-rwxr-xr-x  1 julian  staff  290 Nov  2 23:12 get-password-ansible
$ ./get-password
foo-bar
$ ./get-password-ansible
foo-bar-ansible
$ ansible all -i localhost, -c local -a uptime -e @secrets.yml --vault-password-file get-password-ansible
localhost | success | rc=0 >>
23:12  up 29 days,  2:46, 24 users, load averages: 1.22 1.50 1.58
```

Oh, hey, this time it worked!

And this is consistent with how the `real_vault_password_file` function is defined in https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/__init__.py#L613. It calls `os.path.realpath()` on the file name provided and then invokes the script by that name.

It would be more useful if the vault password file's executability was determined by its real path, etc., but then invoked by its *original* path.

**Comment by jmehnle** [comment]
I have a pull request coming up for this.

**Comment by djmattyg007** [comment]
Did you actually submit this as a PR?

**Comment by mbeshara** [comment]
Looking forward to this bugfix. In the meantime, I'm using this workaround:

    $ cat get-password-ansible
    #!/bin/sh

    . ./get-password

This forces `$0` to evaluate to what should be the symlink's name. When the bugfix arrives, that calling script can be replaced with a symlink without having to change any code.

**Comment by jmehnle** [comment]
Oh, I think I dropped the ball on actually creating a PR for this. I created it now: https://github.com/ansible/ansible/pull/58652

**Comment by bendem** [comment]
Found this as well, the following patch is crude (adapted with what @wdoekes wrote), but works fine:


```diff
--- parsing/vault/__init__.py.bak        2022-09-08 12:09:12.449710300 +0200
+++ parsing/vault/__init__.py    2022-09-08 12:09:04.139710300 +0200
@@ -349,7 +349,9 @@
 
 
 def get_file_vault_secret(filename=None, vault_id=None, encoding=None, loader=None):
-    this_path = os.path.realpath(os.path.expanduser(filename))
+    this_path = os.path.expanduser(filename)
+    if not any(this_path.startswith(prefix) for prefix in ("." + os.path.sep, os.path.sep)):
+        this_path = os.path.join(".", this_path)
 
     if not os.path.exists(this_path):
         raise AnsibleError("The vault password file %s was not found" % this_path)

```

I'm sure it's more complex when dealing with windows paths or other edge cases.

**Comment by bcoca** [comment]
fix is using our custom `unfrackpath(filename, follow=false)`
