### ISSUE TITLE
Certain formatting of 'failed_when' block not working as expected

### ISSUE THREAD

**Issue by edrozenberg** [ansible/ansible#18311]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
Ansible core

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Using sudo on localhost to the same local mac via local connection

##### OS / ENVIRONMENT
MacOS Sierra to the same

##### SUMMARY
Having issues with certain formatting approaches to a failed_when block

##### STEPS TO REPRODUCE

The following task works fine with the 'failed_when' clause all on one line:
```
# Check that Java is installed
- name: check that java is installed
  shell: "`/usr/libexec/java_home`/bin/java -version 2>&1"
  register: javacheck_result
  failed_when: javacheck_result.stdout is undefined or 'java version ' not in javacheck_result.stdout
  changed_when: False
```

But the following 'failed_when' formatting gives an error:
```
  failed_when:
    - javacheck_result.stdout is undefined
    - 'java version ' not in javacheck_result.stdout
```

So I tried quoting but then it does not check the conditions and gives an OK instead of failing as it should:
```
  failed_when:
    - "javacheck_result.stdout is undefined"
    - "'java versionJUNKJUNKJUNK ' not in javacheck_result.stdout"
```

I thought the last approach should work, not sure why it's not. So far only the single line 'failed_when' approach works as expected.

**Comment by sivel** [comment]
Using "list" syntax is an implicit ANDing operation.  It looks like your original `failed_when` used an `or`.  So the list syntax is providing you with different logic than what you expected.

**Comment by edrozenberg** [comment]
Makes sense if AND is what a list is doing. I was led to believe OR based on Michael DeHaan's (Ansible founder) note here:

https://groups.google.com/forum/#!topic/ansible-project/cIaQTmY3ZLE

```
Michael DeHaan  
11/17/14

Multiple checks looks like:

failed_when: color == 'blue' or number == 5

Note that if you are telling when not to fail, you will need to negate your condition.

Ansible denotes lists of conditions as "ORs" so:

failed_when:
   - color == 'blue'
   - number == 5

Is equivalent syntax.
```

**Comment by edrozenberg** [comment]
I can't find any Ansible official documentation saying list syntax = implicit AND. If it's not documented somewhere, would be helpful to have it documented because it's not obvious.

**Comment by edrozenberg** [comment]
For now I'm going to use the single line broken up into multiple lines syntax, since my goal was to get the line to fit in 80 columns:

```
  failed_when: >
    javacheck_result.stdout is undefined or
    'java version ' not in javacheck_result.stdout
```

**Comment by sivel** [comment]
This is largely documented already in the Playbooks>Conditionals documentation at http://docs.ansible.com/ansible/playbooks_conditionals.html#the-when-statement

> Multiple conditions that all need to be true (a logical ‘and’) can also be specified as a list:

I say "largely" because it doesn't mention `failed_when` or `changed_when` there, only `when`, although they are processed in the same manner.  The `failed_when` and `changed_when` documentation does not currently specify the possible use of the list format.

**Comment by edrozenberg** [comment]
Thanks for that, it's one of the more subtle corners of the Ansible syntax.
