### ISSUE TITLE
include inheritable directives are ignored for tasks beyond the first task in an included playbook

### ISSUE THREAD

**Issue by omgjlk** [ansible/ansible#18315]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Playbook includes

##### ANSIBLE VERSION

```
ansible-playbook 2.2.0.0
  config file = /Users/jkeating/src/derp/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

OS X, Ansible installed in a virtualenv.

##### SUMMARY

I have a simple playbook that exists only to include other playbooks. Some of the includes have conditionals, that rely on a value set in a group_var. In 2.2, what I'm seeing is that the playbook include happens even though the conditional is false, and the first task in the first play in the included playbook is skipped (as if the conditional was false), but subsequent tasks are attempted (and in my case, fail).

##### STEPS TO REPRODUCE

@jimi-c was able to reproduce, and has a better reproduce setup that I do.

##### EXPECTED RESULTS

I expect the include to not happen, or for every task in the included play(s) to be skipped.

##### ACTUAL RESULTS

The first task of the first play is skipped, subsequent task is attempted (and it fails).

**Comment by jimi-c** [comment]
Appears related to #17810 and #18206 as well.

**Comment by omgjlk** [comment]
Bits to help reproduce.

hosts:

```
[derp]
haderp connection=local

[derp:vars]
this_is_bad=False
```

top.yaml:

```
---
- include: busted.yaml
  when: this_is_bad
```

busted.yaml:

```
---
- name: busted
  hosts: haderp
  gather_facts: false
  tasks:
    - name: do a thing
      debug:
        msg: "task 1"

    - name: do b thing
      debug:
        msg: "task 2"

    - name: do c thing
      debug:
        msg: "task 3"
```

Execution:
`ansible-playbook -i hosts top.yaml -vv`

Output:

```
Using /Users/jkeating/src/derp/ansible.cfg as config file
PLAYBOOK: top.yaml *************************************************************
1 plays in top.yaml

PLAY [busted] ******************************************************************

TASK [do a thing] **************************************************************
task path: /Users/jkeating/src/derp/busted.yaml:6
skipping: [haderp] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [do b thing] **************************************************************
task path: /Users/jkeating/src/derp/busted.yaml:10
ok: [haderp] => {
    "msg": "task 2"
}

TASK [do c thing] **************************************************************
task path: /Users/jkeating/src/derp/busted.yaml:14
ok: [haderp] => {
    "msg": "task 3"
}

PLAY RECAP *********************************************************************
haderp                     : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by naslanidis** [comment]
I am seeing a similar thing in 2.2

I have an include as follows: 
- { include: create_dhcp_options.yml, when: stage != "delete"}
- { include: delete_dhcp_options.yml, when: stage == "delete" }

The delete_dhcp_options.yml is being included when stage != delete which for me is quite dangerous. This definitely doesn't happen in earlier versions.

**Comment by bcoca** [comment]
might be related to #18299

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
