### ISSUE TITLE
write code smell test for use of type(foo) ==

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#18310]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

code smell tests

##### ANSIBLE VERSION

```
2.3
```

##### SUMMARY

per https://github.com/ansible/ansible-modules-extras/pull/2977 modules should use isinstance instead of "type(foo) ==" for comparison.

Need to write a script to check for the string and place in https://github.com/ansible/ansible/tree/devel/test/sanity/code-smell

**Comment by gundalow** [comment]
Was discussed in https://meetbot.fedoraproject.org/ansible-meeting/2016-11-02/new_module_review_meeting.2016-11-02-18.13.log.html
