### ISSUE TITLE
Cannot loop over hashes using with_dict

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#18336]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
with_dict
##### ANSIBLE VERSION
```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION
inventory   = ./hosts
gathering = explicit
roles_path = /home/actionmystique/Program-Files/Ubuntu/Ansible/Roles/roles
private_role_vars = yes
log_path = /var/log/ansible.log
fact_caching = redis
fact_caching_timeout = 86400
retry_files_enabled = False
##### OS / ENVIRONMENT
- host: Ubuntu 16.10 4.8

##### SUMMARY
I cannot loop over hashes with any of 2 different methods:
- the official one "[looping over hashes](http://docs.ansible.com/ansible/playbooks_loops.html#looping-over-hashes)"
- json_query.

##### STEPS TO REPRODUCE: 1st METHOD "LOOPING OVER HASHES"
Role:
```
- name: Fetching facts from the remote node
  ios_facts:
        gather_subset: all
        provider: "{{ connections.ssh }}"
  register: facts
...
- name: Printing list of interfaces with neighbors
  debug: var=facts.ansible_facts.ansible_net_neighbors

- name: Updating the description of all interfaces with neighbors
  ios_config:
        provider: "{{ connections.ssh }}"
        parents: 
          - "interface {{ item.key }}"
        lines:
          - "description Connected to {{ item.value.host }} on its port {{ item.value.port }}"
  with_dict: "{{ facts.ansible_facts.ansible_net_neighbors }}"
  register: result
```
leads to:
```
TASK [ios_pull_facts : Printing list of interfaces with neighbors] *************
ok: [IOSv_L2_10] => {
    "facts.ansible_facts.ansible_net_neighbors": {
        "Gi0/1": [
            {
                "host": "IOSv_Spine_11.actionmystique.net", 
                "port": "Gi0/0"
            }
        ], 
        "Gi0/2": [
            {
                "host": "IOSv_Spine_12.actionmystique.net", 
                "port": "Gi0/0"
            }
        ], 
...
TASK [ios_pull_facts : Updating the description of all interfaces with neighbors] ***
fatal: [IOSv_L2_10]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'list object' has no attribute 'host'\n\nThe error appears to have been in '/home/actionmystique/Program-Files/Ubuntu/Ansible/Roles/roles/ios_pull_facts/tasks/main.yml': line 139, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Updating the description of all interfaces with neighbors\n  ^ here\n"}
```

##### STEPS TO REPRODUCE: 2nd METHOD "JSON_QUERY"
Role:
```
- name: Fetching facts from the remote node
  ios_facts:
        gather_subset: all
        provider: "{{ connections.ssh }}"
  register: facts
...
- name: Printing list of interfaces with neighbors
  debug: var=facts.ansible_facts.ansible_net_neighbors

- name: Updating the description of all interfaces with neighbors
  ios_config:
        provider: "{{ connections.ssh }}"
        parents: 
          - "interface {{ item.key }}"
        lines:
          - "description Connected to {{ item | json_query('[].host') }} on its port {{ item | json_query('[].port') }}"
  with_dict: "{{ facts.ansible_facts.ansible_net_neighbors }}"
  register: result
```
leads to:
```
TASK [ios_pull_facts : Printing list of interfaces with neighbors] *************
ok: [IOSv_L2_10] => {
    "facts.ansible_facts.ansible_net_neighbors": {
        "Gi0/1": [
            {
                "host": "IOSv_Spine_11.actionmystique.net", 
                "port": "Gi0/0"
            }
        ], 
        "Gi0/2": [
            {
                "host": "IOSv_Spine_12.actionmystique.net", 
                "port": "Gi0/0"
            }
        ], 
...
TASK [ios_pull_facts : Updating the description of all interfaces with neighbors] ***
changed: [IOSv_L2_10] => (item={'key': u'Gi1/1', 'value': [{u'host': u'IOSv_Leaf_15.actionmystique.net', u'port': u'Gi0/0'}]}) => {"changed": true, "item": {"key": "Gi1/1", "value": [{"host": "IOSv_Leaf_15.actionmystique.net", "port": "Gi0/0"}]}, "updates": ["interface Gi1/1", "description Connected to  on its port "], "warnings": []}
changed: [IOSv_L2_10] => (item={'key': u'Gi1/0', 'value': [{u'host': u'IOSv_Leaf_14.actionmystique.net', u'port': u'Gi0/0'}]}) => {"changed": true, "item": {"key": "Gi1/0", "value": [{"host": "IOSv_Leaf_14.actionmystique.net", "port": "Gi0/0"}]}, "updates": ["interface Gi1/0", "description Connected to  on its port "], "warnings": []}
...
```
As you can see with "Connected to  on its port ", "{{ item | json_query('[].host') }}" and "{{ item | json_query('[].port') }}" are **empty**.

**Comment by amenonsen** [comment]
> ##### STEPS TO REPRODUCE: 1st METHOD "LOOPING OVER HASHES"

I can't run your example (I don't even know what `ios_facts` is, and
it surely wouldn't return the same results for me), so I had to come up
with a self-contained test case.

```
---
- hosts: localhost
  gather_facts: no
  tasks:
    - set_fact:
        ansible_net_neighbors:
          Gi0/1:
            - host: IOSv_Spine_11.actionmystique.net
              port: Gi0/0
          Gi0/2:
            - host: IOSv_Spine_12.actionmystique.net
              port: Gi0/0
      register: x
    - debug: var=x
    - debug:
        msg: "{{ item.value.0.host }} and {{ item.value.0.port }}"
      with_dict: "{{ ansible_net_neighbors }}"
    - debug:
        msg: "{{ item.value|json_query('[].host') }} and {{ item.value|json_query('[].port') }}"
      with_dict: "{{ ansible_net_neighbors }}"
```

This works fine.

> ```
>       - "description Connected to {{ item.value.host }} on its port {{ item.value.port }}"
> ```

`item.value` is a list, so `item.value.host` can't possibly work.
`item.value.0.host` works fine.

>   with_dict: "{{ facts.ansible_facts.ansible_net_neighbors }}"

Just use `ansible_net_neighbors` directly, since the module is
returning it as a fact.

> ```
>       - "description Connected to {{ item | json_query('[].host') }} on its port {{ item | json_query('[].port') }}"
> ```

`item` is a dict, so `item|json_query('[].host')` can't possibly
work. `item.value|json_query('[].host')` works fine.

There is no bug here.

**Comment by jean-christophe-manciot** [comment]
You have changed the use case by adding a "-" before 'host' and this changes the way the element can be accessed.. If I remove it, your playbook does not work anymore, unless you remove the '.0' to access both fields.
I cannot see right now why the **first method does not function as expected** on the facts returned by the network module [ios_facts](http://docs.ansible.com/ansible/ios_facts_module.html).
Thanks for catching my mistake when using the **second method**: After correction, it works **almost fine**:

```
TASK [ios_pull_facts : Updating the description of all interfaces with neighbors] *******************************************************************************************
changed: [IOSv_L2_10] => (item={'key': u'Gi1/1', 'value': [{u'host': u'IOSv_Leaf_15.actionmystique.net', u'port': u'Gi0/0'}]}) => {"changed": true, "item": {"key": "Gi1/1", "value": [{"host": "IOSv_Leaf_15.actionmystique.net", "port": "Gi0/0"}]}, "updates": ["interface Gi1/1", "description Connected to [u'IOSv_Leaf_15.actionmystique.net'] on its port [u'Gi0/0']"], "warnings": []}
changed: [IOSv_L2_10] => (item={'key': u'Gi1/0', 'value': [{u'host': u'IOSv_Leaf_14.actionmystique.net', u'port': u'Gi0/0'}]}) => {"changed": true, "item": {"key": "Gi1/0", "value": [{"host": "IOSv_Leaf_14.actionmystique.net", "port": "Gi0/0"}]}, "updates": ["interface Gi1/0", "description Connected to [u'IOSv_Leaf_14.actionmystique.net'] on its port [u'Gi0/0']"], "warnings": []}
...
```

and in the running-config (live configuration of the remote device):

```
show run
...
interface GigabitEthernet0/1
 description Connected to [u'IOSv_Spine_11.actionmystique.net'] on its port [u'Gi0/0']
...
interface GigabitEthernet0/2
 description Connected to [u'IOSv_Spine_12.actionmystique.net'] on its port [u'Gi0/0']
...
```

You must have noticed some undesirable characters around both strings: [u' and '].

**Comment by amenonsen** [comment]
> You have changed the use case by adding a "-" before 'host'

In your output, the value of the key "Gi0/1" is a list that contains a
single dict. That is exactly what I have written in YAML. So I believe
this is a misunderstanding on your part—the examples are equivalent.

> You must have noticed some undesirable characters around both strings:
> [u' and '].

Those are not "undesirable characters". The json_query expression is
returning a list. Your query essentially means "give me the .host of
every item in this list", so it returns a list; that list happens to
have one item, because the input list has one item.

If you know that your "Gi0/1" key will always have a single-element list
as its value in ansible_net_neighbors, then you can just use .0.host to
look up the corresponding value. But if the list can have more than one
element, you have to decide how to deal with the return value as a list.

**Comment by jean-christophe-manciot** [comment]
Thanks, I stand corrected now for the first method.
For the 2nd one, the correct way is rather:

```
          - "description Connected to {{ item.value|json_query('[0].host') }} on its port {{ item.value|json_query('[0].port') }}"
```

**Comment by amenonsen** [comment]
Glad you got it working.
