### ISSUE TITLE
include directive does not respect become directive from outer block

### ISSUE THREAD

**Issue by pcastellazzi** [ansible/ansible#18338]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /dev/null
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

```
export ANSIBLE_CONFIG=/dev/null
```

##### OS / ENVIRONMENT

I am running from macSierra 10.12.1 and Ubuntu 14.04 targeting CentOS 7, Amazon Linux 2016.09, and Ubuntu 14.04

##### SUMMARY

include directive does not respect become directive from outer block

##### STEPS TO REPRODUCE

1. Create an inventory file (test.ini) with the machines IPs
2. Create main.yml with the following content:
```
- hosts: all
  gather_facts: no

  tasks:
    - block:
        - command: id -un
          register: cmd

        - debug:
            msg: "{{ cmd.stdout }}"

        - include: test.yml
      become: yes
```

3. Create test.yml with the following content:
```
- command: id -un
  register: cmd

- debug:
    msg: "{{ cmd.stdout }}"
```

4. run ```env ANSIBLE_CONFIG=/dev/null ansible-playbook -i test.ini -u ubuntu main.yml```

##### EXPECTED RESULTS

```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [192.168.1.1]

TASK [command] *****************************************************************
changed: [192.168.1.1]

TASK [debug] *******************************************************************
ok: [192.168.1.1] => {
    "msg": "root"
}

TASK [command] *****************************************************************
changed: [192.168.1.1]

TASK [debug] *******************************************************************
ok: [192.168.1.1] => {
    "msg": "root"
}

PLAY RECAP *********************************************************************
192.168.1.1                 : ok=5    changed=2    unreachable=0    failed=0
```

##### ACTUAL RESULTS

```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [192.168.1.1]

TASK [command] *****************************************************************
changed: [192.168.1.1]

TASK [debug] *******************************************************************
ok: [192.168.1.1] => {
    "msg": "root"
}

TASK [command] *****************************************************************
changed: [192.168.1.1]

TASK [debug] *******************************************************************
ok: [192.168.1.1] => {
    "msg": "ubuntu"
}

PLAY RECAP *********************************************************************
192.168.1.1                 : ok=5    changed=2    unreachable=0    failed=0
```

**Comment by bcoca** [comment]
might be related with  #18315

**Comment by nazarewk** [comment]
I am quite severly affected by this bug as I have based my whole playbook around includes inside block-becomes to ease the user-switching.

**Comment by elasticdog** [comment]
Just wanted to add another voice to let you know that this bug is also breaking things for us. All of our roles are built around a common nested include structure and become statements to support multiple platforms (Windows gets grumpy with become, so you can't specify it at a higher-level). This bug is a huge deal and prevents us from upgrading to take advantage of the major performance improvements in the 2.2.x releases.

**Comment by kladiv** [comment]
+1 any news on this issue?

I found a workaround specifing **ansible_become** variable into include vars block:
```
- include_role:
    name: <role>
  vars:
    var1: value1
    ansible_become: true
  when:
    - <condition> 
```

**Comment by bcoca** [comment]
so the problem here is that the block gets evaluated at runtime, but the include is being evaluated at compile time. 2 solutions:

Add the directives directly on the include
```yaml
- include:  test.yml
  become: yes
```

Change the include to be dynamic and evaluate at runtime:
```yaml
- include:  test.yml
  static: no
```

**Comment by sivel** [comment]
Resolved by https://github.com/ansible/ansible/pull/38827

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
