### ISSUE TITLE
Support pattern matching for groups

### ISSUE THREAD

**Issue by dsummersl** [ansible/ansible#1834]
I've started using ansible on top of ec2 and I was a little disheartened to learn pattern matching for groups isn't possible with the ansible command. Any chance this could happen? I'd be willing to take a stab at it, if that were any incentive...

**Comment by dhozac** [comment]
Hmm? What doesn't work? ansible gro\* will run on all hosts in all groups starting with gro.

**Comment by mpdehaan** [comment]
I was pretty sure it didn't work explicitly by design.   It would lead to confusing matching.

(In any event, Q&A should go to the mailing list)
