### ISSUE TITLE
unable to assign roles path using variables

### ISSUE THREAD

**Issue by byteshiva** [ansible/ansible#18358]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### STEPS TO REPRODUCE

```
 cat inventory/group_vars/all 

---
roles: /tmp-project/roles
vars_path: /tmp-project/vars


cat playbooks/localhost.yml 

---
- hosts: localhost
  gather_facts: no
  vars: 
      test1: "{{ roles }}"
  vars_files: 
        - "{{ vars_path }}"
  tasks:
    - command: "echo {{item}}"
      register: result
      with_items: [1, 2]
    - name: display msg variable
      debug: msg="{{result}}"
    - debug:
        var: result
    - debug: msg="{{roles}}"
  roles:
    - role: "{{test1}}"

```

##### ACTUAL RESULTS

```

ERROR! {{ roles }}: 'roles' is undefined

```

**Comment by byteshiva** [comment]
The only I was able  do it is by creating a ansible.cfg file in the current directory and setting roles_path

```
$cat ansible.cfg
roles_path    = /etc/ansible/roles:/custom-path/roles
```

**Comment by byteshiva** [comment]
also noted that it doesn't set vars_files using variables that is  if I get the values from group_vars inventory.

**Comment by bcoca** [comment]
Note that config and play do not have access to group vars as they must execute globally and cannot depend on per host basis.

**Comment by JamesUoM** [comment]
Can we therefore (as I can't find one) have a place to define global variables that can be used where group_vars/all ones can't. The only option is envs or commandline. Currently I'm having to use var_files to include an env.yml file that defines a couple of basic variables such as env=staging, as I'd like to keep these variables set in the relevant git branch of my playbook.

**Comment by samdoran** [comment]
Closing per above note. To discuss this further, please reach out on IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
