### ISSUE TITLE
Add -S command line option to disable sudo

### ISSUE THREAD

**Issue by akhayyat** [ansible/ansible#1837]
I want to use `sudo` by default, but on initial setup, `sudo` is not configured yet, so I need to instruct ansible not to use `sudo` occasionally.

However, if I enable `sudo` in the playbook, there is no way to disable it. Therefore, I am forced to disable `sudo` in the playbook, and to constantly use the `-s` command-line option, except for the rare, but existent, occasions in which I don't want `sudo`.

If there was a `-S` command-line option that would disable `sudo`, overriding the playbook, that would make things easier: I would then use `sudo: True` in my playbooks, and use `-S` occasionally, instead of using `-s` most of the times and eliminating it occasionally.

**Comment by mpdehaan** [comment]
you could have a play for initial setup tagged appropriately, or a seperate playbook

I don't see this tag being added, one suggestion would be to set up sudo in your installer automation
