### ISSUE TITLE
`ansible-galaxy init` creates empty files directory which git skips over

### ISSUE THREAD

**Issue by cliimatta** [ansible/ansible#18400]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible-galaxy

##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

Running `ansible-galaxy init <role name>` creates the necessary directory structure, but the files directory is empty so it doesn't get tracked in git

##### STEPS TO REPRODUCE
`ansible-galaxy init testrole`
`git add *` or `git add --all` or `git add .`
`git commit -m "adding testrole role"`
`git push`
Find a friend to clone your repository to check if the files directory exists after the clone

##### EXPECTED RESULTS

The role's files directory should exist in the freshly cloned repository

##### ACTUAL RESULTS

The files directory part of the file structure does not get tracked in git, a subsequent git clone of the repository won't include it.

Consider adding a files/README or files/.gitignore inside the directory so git will track it.

**Comment by cliimatta** [comment]
Just realized this is an issue with the templates directory as well

**Comment by krzysztof-magosa** [comment]
What's the point of storing empty directories in git?
They are not needed for correct work of role.

**Comment by cliimatta** [comment]
Because then you need to re-create the directories if you decide to add something into either files/ or templates/

Isn't the point of "ansible-galaxy init" to create the directory structure needed for roles?

**Comment by krzysztof-magosa** [comment]
Personally I'm not convinced to store empty directories in repo.
I've looked into a lot of roles, including examples provided by Ansible Team - nobody stores empty directories.

But it's just my opinion, so let's wait for somebody else.

**Comment by bcoca** [comment]
I agree with @krzysztof-magosa , the directories are created correctly, if you don't use them that is up to you. If git does not store empty directories but you want them stored, add placeholder files.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
