### ISSUE TITLE
Support patterns logic for tags

### ISSUE THREAD

**Issue by ravishivt** [ansible/ansible#18401]
##### ISSUE TYPE
 - Feature Idea

#### SUMMARY

Ansible [patterns](http://docs.ansible.com/ansible/intro_patterns.html) are very useful for narrow down which hosts/groups to target.  It would be nice if we could use the same pattern syntax for narrowing down which tasks/plays to run using tag patterns.

For example:
```
- name: debug foo
  debug: msg=foo
  tags:
     - foo

- name: debug bar
  debug: msg=bar
  tags:
     - bar

- name: debug baz
  debug: msg=baz
  tags:
     - foo
     - bar
```

If I only wanted to target the third task, I could then use the pattern --tags="foo:&bar".

This may be related to #10131.  Also, the example was copied from http://stackoverflow.com/questions/30036126/how-can-i-run-only-ansible-tasks-with-multiple-tags

**Comment by bcoca** [comment]
dupe of #16273
