### ISSUE TITLE
ansible is not easy_install'able, SandboxViolation

### ISSUE THREAD

**Issue by grzn** [ansible/ansible#1840]
```
❯❯❯ easy_install ansible
Searching for ansible
Reading http://pypi01.infinidat.com/simple/ansible/
Best match: ansible 0.9
Downloading http://pypi01.infinidat.com/media/dists/ansible-0.9.tar.gz#md5=79b5624dc49997288006850a74a1565a
Processing ansible-0.9.tar.gz
Writing /var/folders/f9/d108d_ds0sz0_qlnzr25_bcr0000gn/T/easy_install-V0oYCK/ansible-0.9/setup.cfg
Running ansible-0.9/setup.py -q bdist_egg --dist-dir /var/folders/f9/d108d_ds0sz0_qlnzr25_bcr0000gn/T/easy_install-V0oYCK/ansible-0.9/egg-dist-tmp-7SlkEP
DATA FILES=[('/usr/local/virtualenvs/infi/share/ansible/', ['./library/add_host', './library/apt', './library/apt_repository', './library/assemble', './library/async_status', './library/async_wrapper', './library/authorized_key', './library/command', './library/copy', './library/cron', './library/debug', './library/easy_install', './library/ec2', './library/facter', './library/fail', './library/fetch', './library/file', './library/fireball', './library/get_url', './library/git', './library/group', './library/group_by', './library/ini_file', './library/lineinfile', './library/mail', './library/mount', './library/mysql_db', './library/mysql_user', './library/nagios', './library/ohai', './library/pause', './library/ping', './library/pip', './library/postgresql_db', './library/postgresql_user', './library/raw', './library/script', './library/seboolean', './library/selinux', './library/service', './library/setup', './library/shell', './library/slurp', './library/subversion', './library/supervisorctl', './library/svr4pkg', './library/template', './library/user', './library/virt', './library/wait_for', './library/yum'])]
error: Setup script exited with error: SandboxViolation: mkdir('/usr/local/virtualenvs/infi/share', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
```

**Comment by grzn** [comment]
This happens with the `sdist` distribution. I uploaded a `bdist_egg` build to a private pypi server, and it works

**Comment by mpdehaan** [comment]
I'm not sure we are really concerned with this, as it is pip installable, and easy_install is kind of disused given pip's rise to popularity.

Most folks end up installing ansible from a git checkout or use the OS packages.

**Comment by grzn** [comment]
Pip hasn't replaced easy_install yet, easy_install is still the most common
especially with python2

And you don't have OS packages for osx and windows

If I already did the work why won't you accept it? Tell me what's missing
and how you want me to test it and ill do it

**Comment by mpdehaan** [comment]
It's a huge patch which makes it nearly impossible to review to make sure
there's nothing scary in there.

Perhaps if you implemented it with some git mv commands it would be more
clear as git tracks move relationships, and then add the stubs, it would be
easier to tell if that was all done -- though that would only be true if
indentation did not need to be altered.

This would also hopefully track attribution better.

Really it's "I don't see the importance of the deployment method" seeing we
have a very large pool of users and it's only come up _now_.

--Michael

**Comment by grzn** [comment]
OK,  
I re-do it so its diff will be easier to read

**Comment by mpdehaan** [comment]
Thanks, main concern was 'OMG, how do I review this to make sure it's
right/safe', not so much the moving things around.

**Comment by dhozac** [comment]
Although is there really any need to move things around? Looks like it just needs to have the library path adjusted like is done for virtualenv, e.g.

```
elif inspect.ismethod(os.mkdir):
    DIST_MODULE_PATH = 'share/ansible/'
```

However, ansible being able to find those later is a different issue...

**Comment by grzn** [comment]
Yes, I learned that the hard way. Making the installation go smooth and making ansible work after installation are two different things. I posted a question in the distutils mailling list, maybe the problem is with distribute.

**Comment by grzn** [comment]
Hmmm…
From http://packages.python.org/distribute/setuptools.html#non-package-data-files:

"… Note, by the way, that this [distutils normally install general “data files” to a platform-specific location (e.g. /usr/share).] encapsulation of data files means that you can’t actually install data files to some arbitrary location on a user’s machine; this is a feature, not a bug."

**Comment by mpdehaan** [comment]
That is ... concerning.

All being said, having small scripts in /usr/bin is common and I think we
want this anyway, did you end up getting this to work with that included
hack?

--Michael

**Comment by grzn** [comment]
yes, this works

**Comment by mpdehaan** [comment]
waiting on PR cleanup, but fix is there.  @grzn see comments on the PR

**Comment by woutervh** [comment]
The problem still exists in ansible v1.7.1, uploaded to pypi on 2014-08-14.

Buildout is built on top of easy_install, therefore ansible is uninstallable via buildout.

**Comment by woutervh** [comment]
installing ansible in develop-mode in a virtualenv is problematic as well

in a virtualenv:

> source bin/activate
> wget https://pypi.python.org/packages/source/a/ansible/ansible-1.7.1.tar.gz
> tar xzvf ansible-1.7.1.tar.gz
> cd ansible-1.7.1.tar.gz
> python setup.py  develop
> cd ..
> 
> bin/ansible
> Traceback (most recent call last):
>   File "bin/ansible", line 10, in <module>
>     execfile(**file**)
>   File "/opt/dev/venv-ansible/ansible-1.7.1/bin/ansible", line 25, in <module>
>     from ansible.runner import Runner
> ImportError: No module named ansible.runner

**Comment by srgvg** [comment]
Ansible isn't a pure Python application, and is not designed to work for these kind of setups.
The supported way for custom setups is through a git checkout, and the ./hacking/env-setup script.
This topic has been brought up before, see the list archives.
Also: upstream doesn't watch closed issues ;-)

**Comment by woutervh** [comment]
There shouldn't be any discussion on this.
ansible is a broken python-package, and it should be fixed.
This ticket implies that it's fixed, but it's not.

**Comment by arcimboldo** [comment]
It also makes impossible to use `ansible` as a dependency on another python package.

The following "package" will fail with SandboxViolation:

```
from setuptools import setup

setup(
    name="testpackage",
    version="0.1",
    description="A test package",
    install_requires=['ansible'],
)
```

Trying to install the package:

```
user@host $ python setup.py install
[...]
Running ansible-1.7.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0bbfEj/ansible-1.7.2/egg-dist-tmp-KuzTtu
warning: no files found matching 'packaging/distutils/setup.py'
error: Setup script exited with error: SandboxViolation: mkdir('/home/antonio/.virtualenvs/test/share', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
```

**Comment by WhackoJacko** [comment]
Totally agree with WouterVH and arcimboldo. It's impossible to use Ansible as dependency.
