### ISSUE TITLE
Add object output to documentation

### ISSUE THREAD

**Issue by wildefires** [ansible/ansible#18405]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
- Documentation

##### SUMMARY
It would be nice for when writing an ansible playbook if the documentation included all of the information that the registered variables had.

For example, with the following plays:
```
   - name: Install Python | Unarchive
     unarchive:
       src: "/tmp/python-src.tgz"
       dest: /opt/
       copy: no
     register: python_unarchive
   
  - debug: var=python_unarchive
```

The output of the debug play is 

```
ok: [] => {
    "python_unarchive": {
        "changed": true, 
        "dest": "/opt/", 
        "extract_results": {
            "cmd": [
                "/bin/gtar", 
                "--extract", 
                "-C", 
                "/opt/", 
                "-z", 
                "-f", 
                "/tmp/python-src.tgz"
            ], 
            "err": "", 
            "out": "", 
            "rc": 0
        }, 
        "gid": 0, 
        "group": "root", 
        "handler": "TgzArchive", 
        "mode": "0755", 
        "owner": "root", 
        "size": 1024, 
        "src": "/tmp/python-src.tgz", 
        "state": "directory", 
        "uid": 0
    }
}
```

There's currently no way, other than adding this debug or inspecting the code, to know that some of these variables exist. For example the "handler" attribute exists nowhere on the documentation page for the unarchive module.

It would greatly speed up development time on new ansible scripts if this information were readily available on the documentation website

**Comment by sivel** [comment]
This is done on a module by module basis such as what can be found at http://docs.ansible.com/ansible/stat_module.html#return-values

If you wish to include the output for a specific module, please feel free to open a pull request with that documentation update for the individual module, or open a specific issue for a module.

Module documentation lives in the module file over in one of the module repos:
- https://github.com/ansible/ansible-modules-core
- https://github.com/ansible/ansible-modules-extras

See also: http://docs.ansible.com/ansible/dev_guide/developing_modules.html#documenting-your-module

If you have further questions please stop by IRC or the mailing list:
- IRC: #ansible on irc.freenode.net
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
