### ISSUE TITLE
ansible does not have console_scripts entry points

### ISSUE THREAD

**Issue by grzn** [ansible/ansible#1841]

**Comment by mpdehaan** [comment]
I can't see any benefit in this.  Existing packages are happy.

**Comment by grzn** [comment]
Here's a case:
You have a buildout project that uses ansible
Buildout installs all the dependencies via easy_install and creates the
entry points and does not assume you have installed the dependencies
separately

**Comment by mpdehaan** [comment]
Sounds like using some other deployment system to deploy a deployment
system?  :)

**Comment by grzn** [comment]
Buildout is a python, other solution to virtualenv

**Comment by mpdehaan** [comment]
Ah, ok, first I had encountered it.

We've done some work to make ansible installable via pip under virtualenv.
