### ISSUE TITLE
with_first_found search in parent role

### ISSUE THREAD

**Issue by lberruti** [ansible/ansible#18417]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
with_first_found

##### ANSIBLE VERSION
```
ansible-playbook 2.2.0.0 (maint2.2 caba50c778) last updated 2016/11/08 10:07:51 (GMT +200)
  lib/ansible/modules/core: (maint2.2 164225aa43) last updated 2016/11/08 10:07:17 (GMT +200)
  lib/ansible/modules/extras: (maint2.2 18bb736cc2) last updated 2016/11/08 10:07:37 (GMT +200)
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
with_first_found search incorrectly also inside parent role, i.e:

* role aa depends on role bb
* with_first_found used in role bb
* with_first_found search files in roles/aa/vars/

##### STEPS TO REPRODUCE

```
ansible-playbook -i hosts with_first_found.yml
```

```
==> with_first_found.yml <==

---
- hosts: all
  connection: local
  gather_facts: no
  roles:
    - role: aa

==> roles/aa/meta/main.yml <==

---
dependencies:
  - role: bb

==> roles/aa/vars/first.yml <==

---

==> roles/bb/tasks/main.yml <==

---
- include_vars: "{{item}}"
  with_first_found:
   - first.yml
   - default.yml

==> roles/bb/vars/default.yml <==

---
```

##### EXPECTED RESULTS
```
PLAY [all] *********************************************************************

TASK [bb : include_vars] *******************************************************
ok: [localhost] => (item=/roles/bb/vars/default.yml)

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

##### ACTUAL RESULTS
```
PLAY [all] *********************************************************************

TASK [bb : include_vars] *******************************************************
ok: [localhost] => (item=/roles/aa/vars/first.yml)

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

**Comment by bcoca** [comment]
I would expect this to be the case, first.yml was found FIRST, lookups/action plugins should search relative paths in role, parent roles and play relative directories.

**Comment by lberruti** [comment]
Maybe there is a misunderstanding: which is the parent role in a role dependecy relationship?
if role aa depends on role bb, which do you mean for the parent and the children?

In ansible 1.x with_first_found doesn't search files in the aa role folder when it is running the bb role. This new approach is a breaking change.

Consider the following use case where:
- role aa depends on role bb
- role aa has the variable files: Debian.yml, CentOS.yml and default.yml
- role bb has the variable files: Debian.yml and default.yml
- obviously the role bb runs BEFORE the role aa
- each role has the tipical include_vars section

```
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}.yml"
   - "default.yml"
```

When the author wrote the role bb, he planned a default variable set for any os that is not a Debian.
When he runs the playbook on CentOS, he expect to see the variable of the default.yml file and it is the case until some one creates a role aa that depends on the role bb: in this case the role bb does not work anymore because it gets the variables of the role aa and none of its own variables.

When running the playbook on a CentOS we have the issue: when it is time to run the role bb, the file roles/aa/vars/CentOS.yml is loaded instead of the expected file roles/bb/vars/default.yml

It seems that the resolution procedure iterates over the file names and, for each name, it searches the file moving through the roles directories (calling the find_file_in_search_path function). This creates this strange behaviour.

In my opinion the hierarchical search SHOULD NEVER happen. Maybe with a boolean option to the   with_first_found command (i.e. with_parents, that is false by default). Anyway, in that case, the resolution procedure should move in each role folder and for each folder try to find all the specified names.

**Comment by ag-wood** [comment]
I am seeing this same behaviour in ansible 2.2.1.0 - Is there a work-around for this?  Previously working plays are not failing due to the dependency clash.   This is very confusing behaviour.

**Comment by rockpenguin** [comment]
I agree with @lberruti and @ag-wood - this is definitely not the 'desired' behavior.  IMO, it breaks the ability to have independent and testable roles, and also increases the possibility of variable collision if pulling roles from Galaxy where you didn't write the playbooks.

@ag-wood - for now I am using the **long** option form of `with_first_found`, e.g.

```yaml
- name: Getting vars from the distro specific file
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
      - "_default.yml"
      paths:
       - roles/ansible-role-name/vars/
```

This seems to work for both my testing of the roles individually, as well as when included via `requirements.yml` in my IaaS code. This gives me the ability to specify multiple search paths if I need to and Ansible doesn't seem to search upwards through the path structure. I suppose another workaround could be to name your vars files uniquely within the roles, e.g. `Debian_8_rolename.yml`.  

Note that neither of my workarounds account for roles imported from Galaxy. I did a quick search through Galaxy roles and found several examples of people just using vars files such as `CentOS_7.yml` and not specifying a path.

**Comment by ag-wood** [comment]
Thanks @rockpenguin, unfortunately using a relative path as you do doesn't seem to work for me, I have to use an absolute path to make it work and that is very limiting, forcing everyone using the role to have the same structure or requiring manual updates.

**Comment by remigius42** [comment]
Hi @ag-wood , I hope I am not necro-bumping this issue, but I just experienced the same problem. Based on the roles of @andrewrothstein , using ```{{role_path}}/vars``` like in [ansible-bash/blob/master/tasks/main.yml](https://github.com/andrewrothstein/ansible-bash/blob/master/tasks/main.yml) did work in my case and ```{{ role_path }}``` seems to return an absolute path. 

Hope this helps and best regards
Andreas

**Comment by paulcalabro** [comment]
I'm running into this issue as well. My OS specific task files, which are similarly named in my main role as well as the role it's including, are being included from the main role, which is causing a loop.

**Comment by bcoca** [comment]
This works as documented, search paths are 'parent aware' https://docs.ansible.com/ansible/latest/user_guide/playbook_pathing.html. If you don't want this feature, you must avoid dependencies and calling a role from within another.

Changing it at this point will break many existing use cases.
