### ISSUE TITLE
Error trying to execute ansible GROUP -m ping

### ISSUE THREAD

**Issue by EdoBarroso** [ansible/ansible#18427]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible all -m ping

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### CONFIGURATION

ansible.cfg unchanged. Just used `ansible_user: root` in `/etc/ansible/group_vars/GROUP.yaml`

##### OS / ENVIRONMENT

Elementary OS Loki, based on Ubuntu 16.04

##### SUMMARY

I'm receiving an error saying that a stdlib json or simplejson module are missing, but they're not

##### STEPS TO REPRODUCE

I'm trying to run `ansible GROUP -m ping` and as a result, I get this:

```
hostname | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Error: ansible requires the stdlib json or simplejson module, neither was found!"
}
```

I'm running ansible version 2.2.0.0, python 2.7.12 and simplejson 3.10.0, installed through `pip install simplejson`. I first installed ansible through `sudo apt-get install ansible`

**Comment by sivel** [comment]
You also need to have `json/simplejson` installed on the remote host you are targeting, which in the output above is identified by the name of `hostname`.

This requirement is listed in the "Managed Node Requirements" section in the installation documentation:

http://docs.ansible.com/ansible/intro_installation.html#managed-node-requirements

If you have further questions please stop by IRC or the mailing list:
- IRC: #ansible on irc.freenode.net
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
