### ISSUE TITLE
Ansible is picky with whitespaces used around equal signs 

### ISSUE THREAD

**Issue by gthieleb** [ansible/ansible#18436]
- Bug Report

Ansible: 2.1 / 2.2

##### SUMMARY
When using whitespaces  before or after equal sign e.g. for set_fact the parameter, the value is not assigned and the variable keeps uninitialised.
For someone with a (python) programming background it is common to make white spaces around equal signs for readability. Within ansible its a hard time to figure this out.

##### STEPS TO REPRODUCE

w.o whitespaces:

	---
	- hosts: localhost
	  tasks:
	    - set_fact: testvar="test"
	    - debug: var="testvar"

	TASK [debug] *******************************************************************
	ok: [localhost] => {
	    "testvar": "test"
	}

with whitespaces:

	---
	- hosts: localhost
	  tasks:
	    - set_fact: testvar = "test"
	    - debug: var="testvar"

	TASK [debug] *******************************************************************
	ok: [localhost] => {
	    "testvar": "VARIABLE IS NOT DEFINED!"
	}

**Comment by amenonsen** [comment]
This is not a bug, it's just how it works (and is documented to work). You can use the `key: value` syntax for module arguments if you prefer:

```
- set_fact:
    testvar: test
```
