### ISSUE TITLE
Launching big remote script fails (too much output ?)

### ISSUE THREAD

**Issue by furiml** [ansible/ansible#18438]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- WinRM connection (PSRemoting)
##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### CONFIGURATION

out of the box
##### OS / ENVIRONMENT

debian
##### SUMMARY

I'm deploying Windows softwares with Ansible, and ran into this problem : 
I wrote a PS1 script that downloads and extracts files from a web server. There's 20 softwares, weighing about 7Go in total. When everything is extracted, it weighs 15.3 Go. Now, the script is flawless on itself, so the problem definitely comes from the connection mechanism between windows and ansible. Now, for the problem...
I call the script using the `script` module, and it always fail the first time, **after approx. 80 seconds**. On the remode node, there are some downloaded files and extracted ones, so it IS working. I am getting this error (whole stderr output) : 
```
[localhost] The background process closed or ended abnormally.
+ CategoryInfo          : OpenError: (localhost:String) [], PSRemotingTransportException
+ FullyQualifiedErrorId : 2101,PSSessionStateBroken
[localhost] The background process closed or ended abnormally.
+ CategoryInfo          : OpenError: (localhost:String) [], PSRemotingTransportException
+ FullyQualifiedErrorId : 2101,PSSessionStateBroken
[localhost] The background process closed or ended abnormally.
+ CategoryInfo          : OpenError: (localhost:String) [], PSRemotingTransportException
+ FullyQualifiedErrorId : 2101,PSSessionStateBroken
```
Strangely, if I run the script again, using the same command, it will complete normally (my script doing what it already did) and take more time : about five minutes. No stderr output, all the files are on the node. So my solution for now is to run it twice, maybe three times just to make sure.

It looks weird to me. Powershell errors are really hard to understand, and having already searching for days about PSSessionBroken, I don't remember seeing something like this... 
### _Could it have something to do with the amount of output produced ?_ 
My script is very verbose, and when it fails through, I have a single-line, ~19 000 characters long stdout which doesn't look truncated. When it succeeds, it produces less output (around 15 000 characters, it varies), because as some files are already here it just goes over them, doing nothing.

Thanks for having a look at this... 
Furiml

**Comment by alikins** [comment]
I suspect this is just winrm connection timeouts. 

Try setting ansible_winrm_read_time_sec and ansible_winrm_operation_timeout_sec to higher values (default are 30 sec for former and 20 sec for the latter).

If possible, try running with '-vvv' and including the ansible-playbook output here or in a gist/pastebin. Probably don't need to include the script output itself, just the ansible-playbook output. (Wondering if the approx ~80secs is some combo of the read_time_sec and operation_timeout_sec...)

**Comment by nitzmahone** [comment]
@Furiml Since you're using 2.2, could I get you to try pushing the script to the host yourself and using the `win_shell` module instead? I suspect we might be running into an internal buffer deadlock with the direct consumption of output via WinRM in the script action. We explicitly handle that in `win_shell` (and test for it)- give that a try and see if it works better for you...

**Comment by BarryCui** [comment]
@alikins Could you please tell me how can I change the values of ansible_winrm_read_time_sec and ansible_winrm_operation_timeout_sec? I'm new to Python.

**Comment by nitzmahone** [comment]
@furiml Haven't heard back after nearly a year, so assuming you worked around this somehow, as we're unable to reproduce... If it's still an issue, please file a new ticket with some more details and a full reproduction.
