### ISSUE TITLE
ansible.cfg multilocation support

### ISSUE THREAD

**Issue by keachi** [ansible/ansible#18433]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ansible.cfg with multiple locations support

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Linux

##### SUMMARY
Some parameters in the ansible.cfg configuration files are more project specific and some options are more client specific, so loading these parameters from multiple locations could be nice. E.g. ansible.cfg in the current directory and ``$HOME/.ansible.cfg``

##### STEPS TO REPRODUCE
Project specific ``ansible.cfg``:
```
[defaults]
ansible_managed     = Warning: File is managed by Ansible
retry_files_enabled = False
hostfile            = ./hosts
roles_path          = ./generic-roles
```
User specific ``~/.ansible.cfg``:
```
[ssh_connection]
control_path = ~/.ssh/sockets/%h_%p_%r
```

Loading parameter ``hostfile`` and ``roles_path`` from project specific and loading ``control_path`` from user specific configuration file.

##### EXPECTED RESULTS
Possible way: use parameter from "next" configuration file, if not specified in the actual file.
In the example above: use ``control_path`` from user specific configuration file if not specified in the project specific configuration file.

##### ACTUAL RESULTS
``control_path`` is not considered.

**Comment by bcoca** [comment]
This is a subset of existing proposal https://github.com/ansible/proposals/issues/35

**Comment by rguhr** [comment]
Even if it's an old issue it is still relevant.

@keachi as workaround you could build a temporary configuration file which merged all possible ansible.cfg's

Here is a draft of this approach:
https://gitlab.com/snippets/1753039
