### ISSUE TITLE
Cannot install role via ansible-galaxy on Mac OS 

### ISSUE THREAD

**Issue by stinnux** [ansible/ansible#18446]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-galaxy

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
Darwin MacBook-Pro-2.local 16.3.0 Darwin Kernel Version 16.3.0: Sun Oct 23 14:50:01 PDT 2016; root:xnu-3789.30.76~4/RELEASE_X86_64 x86_6

##### SUMMARY
When trying to install a role via 
```
ansible-galaxy install 
```
the following error occurs:
[WARNING]: - geerlingguy.firewall was NOT installed successfully: Failed to get data from the API server (https://galaxy.ansible.com/api/): a bytes-like object is required, not 'str'

##### STEPS TO REPRODUCE
Install ansible via 
```
pip install ansible
```
Run
````
ansible-galaxy install geerlingguy.firewall
```

##### EXPECTED RESULTS
Role should be installled

##### ACTUAL RESULTS
An error message appears

**Comment by krzysztof-magosa** [comment]
I cannot reproduce your issue. Did you try again?
Maybe it was temporary problem with API server.

**Comment by stinnux** [comment]
I found the error. i've installed ansible using python3. When using python2 everything is working as expected.

**Comment by SiggyF** [comment]
This was fixed in #19852 (`os.write` was called with `str` instead of `bytes`). A workaround if you're stuck on an old version is to use the `--offline` flag.

**Comment by cdaringe** [comment]
it would appear that the fix has still not made it into an official release, at the time of writing.

i just pulled http://releases.ansible.com/ansible/ansible-latest.tar.gz down and:

```
$ ~/Downloads/ansible-2.2.1.0/bin/ansible-galaxy install angstwad.docker_ubuntu
 [WARNING]: - angstwad.docker_ubuntu was NOT installed successfully: Failed to get data from the API server (https://galaxy.ansible.com/api/): a bytes-like object is required,
not 'str'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
cdieringer@tw-cdaringe 🛰  cdaringe-provision$ ~/Downloads/ansible-2.2.1.0/bin/ansible-galaxy --version
ansible-galaxy 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

**Comment by cdaringe** [comment]
in fact, even on ~~https://github.com/ansible/ansible/releases/tag/v2.1.4.0-1~~ https://github.com/ansible/ansible/releases/tag/v2.2.1.0-1 i still see the same issue

**Comment by cdaringe** [comment]
sorry for so many posts.  i just pulled the latest `devel` branch as well.  same same. :/

**Comment by abarghou** [comment]
I'm getting the same error @cdaringe mentioned on ansible 2.2.1.0
