### ISSUE TITLE
ternary operator converts int/float into string

### ISSUE THREAD

**Issue by mearsten** [ansible/ansible#18452]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /home/snp/ansible-playbooks-non-edx/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
standard

##### OS / ENVIRONMENT
Debian 8
Python 2.7.9

##### SUMMARY
ternary operator returns string instead of int/float

##### STEPS TO REPRODUCE
Run the following playbook
```
- name: nnn
  hosts: localhost
  gather_facts: False

  vars:
    fl1: "{{ true |ternary(0.3, 0.4) }}"
    fl2: "{{ fl1 * 2 }}"
    fl3: "{{ (fl1|float) * 2 }}"

    i1: "{{ true |ternary(3, 4) }}"
    i2: "{{ i1 * 2 }}"
    i3: "{{ (i1|int) * 2 }}"

  tasks:
    - debug: msg="fl1={{ fl1 }}"
    - debug: msg="fl2={{ fl2 }}"
    - debug: msg="fl2={{ fl3 }}"

    - debug: msg="i1={{ i1 }}"
    - debug: msg="i2={{ i2 }}"
    - debug: msg="i2={{ i3 }}"
```

##### EXPECTED RESULTS
(all extra output has been removed)
```
    "msg": "fl1=0.3"
    "msg": "fl2=0.6"
    "msg": "fl2=0.6"
    "msg": "i1=3"
    "msg": "i2=6"
    "msg": "i2=6"
```

##### ACTUAL RESULTS
```
PLAY [nnn] *********************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "fl1=0.3"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "fl2=0.30.3"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "fl2=0.6"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "i1=3"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "i2=33"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "i2=6"
}

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0
```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

It is not the ternary filter doing this, it is the 'normal' result of jinja2 templating, use the `|int` and `|float` filters on consumption to guarantee the type.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
