### ISSUE TITLE
pycrypto not listed in the Python package requirements list

### ISSUE THREAD

**Issue by eproxus** [ansible/ansible#18453]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
Running From Source

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
`pycrypto` not listed in the Python package requirements list

##### STEPS TO REPRODUCE

1. Read https://docs.ansible.com/ansible/intro_installation.html#running-from-source
2. Install the Python dependencies:
    ```
    $ sudo pip install paramiko PyYAML Jinja2 httplib2 six
    ```
3. Run the last confirmation step:
    ```
    $ ansible all -m ping --ask-pass
    ```

##### EXPECTED RESULTS
```
127.0.0.1 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
```

##### ACTUAL RESULTS
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: DistributionNotFound: The 'pycrypto>=2.6' distribution was not found and is required by ansible
127.0.0.1 | FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

**Comment by jctanner** [comment]
I agree that we should make the install doc match the contents of setup.py ...

```
install_requires=['paramiko', 'jinja2', "PyYAML", 'setuptools', 'pycrypto >= 2.6'],
```

**Comment by sivel** [comment]
Maybe we could move the requirements to install into a requirements.txt file that is referenced by setup.py as well as the instructions specifying to utilize the requirements.txt instead of listing the packages separately in 2 locations?

Just a thought, as I've seen this done elsewhere.

**Comment by BondAnthony** [comment]
@jctanner and @sivel I was looking at resolving this documentation concern. Were you thinking about including a requirements.txt in the root of the project then reading this file in during setup? Would you just update the docsite to point users to the requirement.txt or can the information in requirement.txt be dynamically loaded into the docsite? This would create a dependency for setup to always have the requirement.txt file. I did find some information within the development community advising against the approach of making install_requires dependent upon an external file. Sounds like a number of IDE's could have issues resolving the dependencies.

**Comment by jctanner** [comment]
@BondAnthony i'm not sure. It might be something to discuss at the next core team meeting.

**Comment by tedder** [comment]
Please note pycrypto is waaay out of date, nearing 3 years since last release at this point. pycryptodome would be a better requirement; it's a drop-in, and its latest release was 6 days ago- it is actively developed.

**Comment by pcahyna** [comment]
@tedder see #20566.

**Comment by tedder** [comment]
Thanks- works for me.
