### ISSUE TITLE
Group vars not passed into vars_plugins

### ISSUE THREAD

**Issue by davidmnoriega** [ansible/ansible#18459]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vars_plugins

##### ANSIBLE VERSION

```
$ dpkg -l ansible
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  ansible        2.2.0.0-1ppa all          A radically simple IT automation 

$ ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
Working on creating a vars plugin and discovered that in 2.2.0.0, the plugin is not getting any group vars. Downgrading to **2.1.0.0**, and the plugin can get data via `host.get_group_vars()`. I think this is potentially related to #15493 

##### STEPS TO REPRODUCE
Simple single host inventory with the following `group_vars/all`
```
test:
  - a
```

Create the following simple vars_plugin at `vars_plugins` in the root of my working directory:
```python
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


class VarsModule(object):

    """
    Loads variables for groups and / or hosts

    """

    def __init__(self, inventory):
        self.inventory = inventory
        self.inventory_basedir = inventory.basedir()

    def append_test(self, groupvars):
        results = {}
        if 'test' in groupvars:
            results.update({'test_plugin': 'yes'})

        return results

    def get_host_vars(self, host, vault_password=None):
        """ Get host specific variables. """
        return self.append_test(host.get_group_vars())
```

And update `ansible.cfg` with
```ini
[defaults]
...
vars_plugins = vars_plugins
```

Then I test with the following command:

```bash
ansible -m debug -a "var=hostvars[inventory_hostname]" all
```

##### EXPECTED RESULTS
I expect the vars_plugin to add what I wanted like so:
```bash
$ ansible -m debug -a "var=hostvars[inventory_hostname]" all -vvvv
Using /vagrant/test/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
test1.vagrant | SUCCESS => {
    "hostvars[inventory_hostname]": {
        "ansible_check_mode": false, 
        "ansible_version": {
            "full": "2.1.0.0", 
            "major": 2, 
            "minor": 1, 
            "revision": 0, 
            "string": "2.1.0.0"
        }, 
        "group_names": [
            "ungrouped"
        ], 
        "groups": {
            "all": [
                "test1.vagrant"
            ], 
            "ungrouped": [
                "test1.vagrant"
            ]
        }, 
        "inventory_dir": "/vagrant/test/inventory/vagrant", 
        "inventory_file": null, 
        "inventory_hostname": "test1.vagrant", 
        "inventory_hostname_short": "test1", 
        "omit": "__omit_place_holder__c1b35db14631b948fefe0c3827f517cea304164c", 
        "playbook_dir": ".", 
        "test": [
            "a"
        ], 
        "test_plugin": "yes"
    }
}
```

I downgraded from 2.2 step by step down to 2.1 and found all versions after **2.1.0.0** have this issue.

##### ACTUAL RESULTS
```bash
$ ansible -m debug -a "var=hostvars[inventory_hostname]" all -vvvv
Using /vagrant/test/ansible.cfg as config file
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc
test1.vagrant | SUCCESS => {
    "hostvars[inventory_hostname]": {
        "ansible_check_mode": false, 
        "ansible_version": {
            "full": "2.2.0.0", 
            "major": 2, 
            "minor": 2, 
            "revision": 0, 
            "string": "2.2.0.0"
        },  
        "group_names": [
            "ungrouped"
        ], 
        "groups": {
            "all": [
                "test1.vagrant"
            ], 
            "ungrouped": [
                "test1.vagrant"
            ]
        }, 
        "inventory_dir": "/vagrant/test/inventory/vagrant", 
        "inventory_file": null, 
        "inventory_hostname": "test1.vagrant", 
        "inventory_hostname_short": "test1", 
        "omit": "__omit_place_holder__857b85a3093a239f7cbe078c9c82877e33561bcd", 
        "playbook_dir": ".", 
        "test": [
            "a"
        ]
    }
}
```

**Comment by davidmnoriega** [comment]
I have a hunch the change might come from here: 
https://github.com/ansible/ansible/commit/0ba9a6a8756745dc6c486eaca92af583a89c228d
but I dont know for sure.

**Comment by jctanner** [comment]
@davidmnoriega yep, I bisected to https://github.com/ansible/ansible/commit/273a965dcc1e522fcd6637c63be0157a17cff421 which is what https://github.com/ansible/ansible/commit/0ba9a6a8756745dc6c486eaca92af583a89c228d was cherry picked from.

@jimi-c can you take a look?

**Comment by jagardaniel** [comment]
I have the exact same issue. `host.get_group_vars()` returns an empty dict with Ansible 2.2.0.0 in a vars plugin.

I think I found the part of the code where it does not return anything:
https://github.com/ansible/ansible/blob/stable-2.2/lib/ansible/inventory/__init__.py#L837
**return_results** is **False** so it will never set the result variable and the `_get_hostgroup_vars` method it will return an empty dict.

It works as it should if I set **return_result** to **True** (I just added a return_result = True above the if statement) and I can see all my group_vars data in `host.get_group_vars()` again. 

I'm not skilled enough to actually know how to fix the issue and why it happens :(

Thanks!
/Daniel

**Comment by davidmnoriega** [comment]
I gave 2.3.0.0 a try and am still seeing this issue.

**Comment by bcoca** [comment]
this is not a vars_plugin issue, the internal inventory object changed, this was not a guaranteed interface.

Also note that more radical changes to inventory are comming in 2.4. https://github.com/ansible/ansible/pull/23001

**Comment by davidmnoriega** [comment]
@bcoca Looks like this is for 2.4? Is this new interface documented(or documentation I can test)? If so, we can close this out.

**Comment by bcoca** [comment]
@davidmnoriega soon i'll be writing docs, still not sure the current interface is the best one. Mostly now its just calling the plugin's 'get_vars' method vs the 'run' method that existed before. I'm open to suggestions.

**Comment by davidmnoriega** [comment]
I dont have any suggestions, just hoping to not have my plugin/deploy fall behind. Maybe if I provide more details on what my code is doing can help.

I'm using a dictionary to define some items to configure on a host, there are some items that should have the same key:value of another, and I could copy/paste that, but it leads to lots of duplication. My vars_plugin looks for these items and makes them "inherit" the key:value of the item they depend on. I'll add that my dictionary is kept flat and doesn't represent this relationship so it's easy for with_items to loop through.

**Comment by bcoca** [comment]
added this to help with 'existing plugins' .. might need deprecation message https://github.com/ansible/ansible/pull/25451

**Comment by davidmnoriega** [comment]
I'm closing this out now that I've figured out how to port my plugin, but it's been quite the struggle. I really would like to see actual documentation and not just "you can jump into lib/ansible/plugins and figure things out pretty easily". @bcoca I would like to help, but not even sure where to begin.

**Comment by bcoca** [comment]
@davidmnoriega I am planning on adding docs for the plugins, but that would still not include what you requested as that part of the API is not for public consumption. The plugins are supposed to return vars, not consume them.

**Comment by davidmnoriega** [comment]
@bcoca well I'm here to say that is not my plan and I need to consume them 😁

I planning on releasing the role I'm working on soon, I'll let you know.
