### ISSUE TITLE
Complex password as variable through ansible templates

### ISSUE THREAD

**Issue by manan00** [ansible/ansible#18466]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Templates in ansible

##### ANSIBLE VERSION
1.9.4

##### CONFIGURATION
NA

##### OS / ENVIRONMENT
NA

##### SUMMARY
I am using command line to peform operation on remote server.

ansible-playbook -i hosts site.yml --tags copy_password --extra-vars "dbPassword=abc$cd"
below is template content,
```
cat pass.j2
{{ dbPassword }}
```
I am copying this template file on remote server .and I found that due to "$" its not getting overwrite exactly. 
file content from remote server : 
```
cat pass.j2
abc --- where as I am expecting here abc$cd the value which I have passed in extravars. 
```
Can you please help with this issue.

##### STEPS TO REPRODUCE

```
ansible-playbook -i hosts site.yml --tags copy_password --extra-vars "dbPassword=abc$cd"
```

##### EXPECTED RESULTS
abc$cd

##### ACTUAL RESULTS

```
abc --- 
```

**Comment by krzysztof-magosa** [comment]
It's because of your shell behaviour and not bug in Ansible.
You need to escape dollar sign, or put string in `'` instead of `"`.

```
# variable world is empty that's why text is cut off after hello
$ echo "hello$world"
hello

# dollar escaped using backslash
$ echo "hello\$world"
hello$world

# shell does not interpolate variables within single '
$ echo 'hello$world'
hello$world
```

**Comment by jctanner** [comment]
@manan00 can you please confirm @krzysztof-magosa 's comment?

needs_info

**Comment by manan00** [comment]
Thank you @krzysztof-magosa . It works !

**Comment by krzysztof-magosa** [comment]
@manan00, no problem. Could you close the ticket if you don't need further help?
