### ISSUE TITLE
Multiprocess issues when running Ansible programically on AWS Lambda

### ISSUE THREAD

**Issue by pgasiorowski** [ansible/ansible#18469]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Ansible core

##### ANSIBLE VERSION
2.2
##### OS / ENVIRONMENT
Amazon Linux 2016.9 / AWS Lambda Python 2.7

##### STEPS TO REPRODUCE
Run Amazon Linux on Aws
Create Vitualenv and activate
Install ansible
Package the Virtualenv folder according to aws docs for creating virtualenv
Add https://github.com/jtyr/ansible-run_playbook/blob/master/run.py or similar
Create AWS Lambda using the package
Run a test

##### EXPECTED RESULTS
My use case is to be able to invoke Ansible programically in AWS Lambda
which would be responsible for automated management of services running on ec2 instances.
I am packaging It along with some python code which calls Ansible classes directly.

##### ACTUAL RESULT
Same errors as in https://github.com/ansible/ansible/issues/13830
The AWS Lambda environment is specific because it does not provide /dev/shm
which is required for semaphores in multiprocess.Queue used heavily in Ansible.

I can provide the exact steps to repro if there is any interest in fixing this issue.

**Comment by jctanner** [comment]
@WooDzu does changing the remote_tmp help at all? http://docs.ansible.com/ansible/intro_configuration.html#remote-tmp

EDIT: try setting local_tmp too: http://docs.ansible.com/ansible/intro_configuration.html#local-tmp

needs_info

**Comment by pgasiorowski** [comment]
Hi and thanks for the suggesions.
I have actually changed local_tmp to /tmp already which was required as /tmp is the only writable place on Lambda. I will try the same for remote_tmp and report back.

**Comment by jctanner** [comment]
@WooDzu thanks, will await your results.

needs_info

**Comment by pgasiorowski** [comment]
No luck after changing remote_tmp and local_tmp to /tmp/ansible. The stack trace is still the same:

```
[Errno 38] Function not implemented: OSError
Traceback (most recent call last):
  File "/var/task/run.py", line 101, in main
    options=event
  File "/var/task/run.py", line 87, in __init__
    passwords=passwords)
  File "/var/task/ansible/executor/playbook_executor.py", line 59, in __init__
    self._tqm = TaskQueueManager(inventory=inventory, variable_manager=variable_manager, loader=loader, options=options, passwords=self.passwords)
  File "/var/task/ansible/executor/task_queue_manager.py", line 101, in __init__
    self._final_q = multiprocessing.Queue()
  File "/usr/lib64/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 63, in __init__
    self._rlock = Lock()
  File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 38] Function not implemented
```

here are contents of run.py:
https://gist.github.com/WooDzu/14809c4d08baa4364c8fbd6f1a5c63e3

**Comment by pgasiorowski** [comment]
Do you have any suggesions on how to approach this? I would like to avoid maintaining a cluster of ec2 instances which host ansible.

**Comment by jessegonzalez** [comment]
@WooDzu, ever get this resolved?

**Comment by pgasiorowski** [comment]
I haven't. Started looking at AWS Systems Manager and Managed Services instead.

**Comment by jessegonzalez** [comment]
Found that AWS Lambda does not include support for /dev/shm which is required by multiprocessing.

Here is a link to an AWS forum post discussing the issue: https://forums.aws.amazon.com/message.jspa?messageID=769117#769117

**Comment by nisaacson** [comment]
The lack of /dev/shm in lambda is unfortunate indeed. 

Please comment on that thread @jessegonzalez linked to the AWS forums. This will help AWS see the value in prioritizing adding /dev/shm.

**Comment by traverseda** [comment]
This is also a problem on android platforms.

**Comment by ryansb** [comment]
This isn't entirely an Ansible bug - these platforms (Lambda in the original case, Android in the prevv comment) don't support access to `/dev/shm` for sandboxing-related reasons, and barring Ansible supporting threaded workers I don't see a way to get multiprocessing into AWS Lambda anyway. 

Also, in AWS Lambda you'd hit issues with the 300 second max timeout and low open socket limit. If you do want to run Ansible triggered in some fashion by an SNS or other event, one option is to have a Lambda start an instance w/ cloud-init configured to run some set of playbooks. 

Closing, as until these platforms support /dev/shm there's not much that can be done on the Ansible side.

**Comment by pgasiorowski** [comment]
Thanks for the heads up @ryansb I would agree on all points.

> Closing, as until these platforms support /dev/shm there's not much that can be done on the Ansible side.

Given there is some interest in it anyway and troubleshooting source of the issue is cumbersome I would suggest to keep it open until there is a feasible solution for Lambda on either side.

> If you do want to run Ansible triggered in some fashion by an SNS or other event, one option is to have a Lambda start an instance w/ cloud-init configured to run some set of playbooks.

The temporary solution I ended up using is running Ansible in ECS docker containers via events. There are lots of resources involved in it as it needs at least 2 EC2 hosts dedicated to Ansible waiting for ECS tasks in each supported region. Can share the CloudFormation template with anybody who's got the same issue.

**Comment by mixja** [comment]
You can also run Ansible in CodeBuild, which is what I do to overcome this.  CodeBuild is a container-based build agent, allows you to customise the build container image and supports VPC connectivity if required.

This is a pretty powerful on-demand approach.

**Comment by Hotschmoe** [comment]
Still interested in running ansible on Android but python multiprocessing is still an issue. Would creating a fallback import for multiprocessing be feasible for ansible? A similar fix was done here : 

https://github.com/asciinema/asciinema/issues/271
