### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by NISHAgl** [ansible/ansible#18479]
hi
Please tell me do I need to first build the setup.py or can I directly run setup.py install
Nothing is mentioned in README about the steps to install. Please update

##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by jctanner** [comment]
Hello @NISHAgl thank you for your interest in ansible. 

You have a few options for installing ansible, and setup.py is only one of them. We have an extensive set of documentation for installation (with various methods) on our docsite: http://docs.ansible.com/ansible/intro_installation.html
