### ISSUE TITLE
Conditionally omitted task file task conditions are evaluated

### ISSUE THREAD

**Issue by rmfitzpatrick** [ansible/ansible#18483]
When a role task file is conditionally omitted, the `when` statements in its tasks are still evaluated and cause fatal errors when those conditions use variables that haven't been registered or set.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
stable 2.2 and devel
bisect shows this was introduced by debfb798dd15c9cea0ebfdc95e4bce9cc459c039

##### OS / ENVIRONMENT
rhel/centos/ubuntu/osx

##### STEPS TO REPRODUCE
```
repro.yml:
  ---
  - name: 'Find issue'
     hosts: local
     roles:
      - { role: test }}
roles/
- test/
--- tasks/
----- dont.yml:

- name: Look for root
  stat:
    path: /
  register: root_var

- name: Shouldn't happen
  debug: msg="Undesired" 
  when: root_var.stat.exists

----- main.yml:

 - include: dont.yml
    when: '{{ dont }}"


> ansible-playbook -i /inventory -e "dont=false" repro.yml
```

##### EXPECTED RESULTS
```
TASK [test : Look for root] ****************************************************
task path: /roles/test/tasks/dont.yml:1
skipping: [127.0.0.1] => {
    "changed": false,
    "skip_reason": "Conditional check failed",
    "skipped": true
}

TASK [test : Shouldn't happen] *************************************************
task path: /roles/test/tasks/dont.yml:6
skipping: [127.0.0.1] => {
    "changed": false,
    "skip_reason": "Conditional check failed",
    "skipped": true
}
```

##### ACTUAL RESULTS

```
TASK [test : Look for root] ****************************************************
task path: /roles/test/tasks/dont.yml:1
skipping: [127.0.0.1] => {
    "changed": false,
    "skip_reason": "Conditional check failed",
    "skipped": true
}

TASK [test : Shouldn't happen] *************************************************
task path:/roles/test/tasks/dont.yml:6
fatal: [127.0.0.1]: FAILED! => {
    "failed": true,
    "msg": "The conditional check 'root_var.stat.exists' failed. The error was: error while evaluating conditional (root_var.stat.exists): 'dict object' has no attribute 'stat'\n\nThe error appears to have been in '/roles/test/tasks/dont.yml': line 6, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Shouldn't happen\n  ^ here\n"
}
```

**Comment by jctanner** [comment]
@jimi-c can you take a look?

**Comment by bcoca** [comment]
the include task is 'statically evaluated' which means the `when` is inherited by the included tasks and appended to their conditions. You can force 'dynamic' evaluation so the `when` applies to the include itself by adding `static: no` to the include task.

**Comment by rmfitzpatrick** [comment]
If this is the case could it be possible to prepend the inherited include condition instead of requiring undesired updates to previously reliable playbooks?  The functionality would be the same in the end and would be a smoother user experience.

**Comment by bcoca** [comment]
@rmfitzpatrick not really, the code originally pre evaluated conditionals from includes, if that failed (which it can depending on variable availablity) it appended to tasks. Recently the code changed to remove the 'pre evaluation' so now it is always appending and that is what you are seeing. 

By prepending always you will also break existing playbooks, that rely on the current execution order:

```
- include: stuff.yml
  when: undefinedvar
```

stuff.yml

```
- debug: msg="i used to be skipped, if we prepend i error"
  when: undefinedvar is defined
```

We are currently discussion options, `static: no` should give you explicit control and is a current workaround for the change.

**Comment by ghjm** [comment]
@bcoca: is `static: no` also valid syntax for 2.1 and 2.0? Or is it new in 2.2? Or in other words, is there a way to write this kind of playbook that is compatible across Ansible versions?

**Comment by bcoca** [comment]
dynamic includes got added in 2.0, but the `static` keyword was introduced in 2.1

This ticket is still open and we are considering patches, the `static: no` was offered as a workaround.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
