### ISSUE TITLE
lineinfile module enhancement

### ISSUE THREAD

**Issue by hyao** [ansible/ansible#1849]
Suppose I just want to add the following line to a config file (and this file doesn't contain a logfile= line):
logfile = /var/log/openerp/openerp-server.log

When I use it from a playbook as follows:
lineinfile: dest=/etc/openerp-server.conf line="logfile = /var/log/openerp/openerp-server.log"

It doesn't work, and I have to use it with regexp:
lineinfile: dest=/etc/openerp-server.conf regexp="^logfile = " line="logfile = /var/log/openerp/openerp-server.log"

When the user wants to add (not replace) one line to a config file, isn't it much straightforward to just specify the line to add without using regexp?

Thanks,

Heling

**Comment by mpdehaan** [comment]
Please ask questions to the mailing list.
