### ISSUE TITLE
Issue when copying and/or addressing Ansible AWS EC2 variables

### ISSUE THREAD

**Issue by 13dimitar** [ansible/ansible#18498]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

task execution, variable handling

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Ansible control machine - Mac OS Sierra 10.12.1
target machine - AWS EC2 Instance

##### SUMMARY
When you create an instance with the ec2 module, you can store the instance details in a variable (I'll use the "system" variable name in for this example). Later, you can refer to those details and implement suitable logic in your playbook. However, if you refer directly in task, like `{{ system.instances.id }}`, you get an error that `"the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'list object' has no attribute 'id'`.

If you try to copy the variable content to another variable, using the debug module, you end up with an error `"template error while templating string: unexpected char u'x' at 7. String: {{i-xxxxxxxx}}"`

##### STEPS TO REPRODUCE

Create an ec2 instance and store the instance details in a variable. 
Try to display/refer to a variable with `{{ system.instances.SOMETHING }}`, or try to copy the variable value to another variable, using the debug module.

```
- name: Create ec2 instance
   ec2:
    key_name: mykey
    group: mygroup
    instance_type: t2.medium
    image: ami-xxxxxxxx
    region: eu-central-1
    wait: yes
    wait_timeout: 500
    volumes:
     - device_name: /dev/xvda
       volume_type: gp2
       volume_size: "{{ vol_size }}"
    monitoring: no
    vpc_subnet_id: subnet-xxxxxx
   register: system

# this works
 - name: Wait for ssh
   local_action: wait_for host={{ item.public_ip }} port=22 state=started
   with_items:
    - "{{ system.instances }}"

# this works
 - name: Name the new instance
   local_action: ec2_tag resource={{ item.id }} region=eu-central-1 state=present
   args:
    tags:
     Name: "{{ name }}"
   with_items:
    - "{{ system.instances }}"

# this works
 - name: Allocate Elastic IP
   ec2_eip: state='present' region=eu-central-1
   register: ip

# this fails
 - name: Display instance id
   debug: var={{ system.instances.id }}

# this fails
 - name: copy instance id to another variable
   debug: var={{ item.id }}
   with_items:
    - "{{ system.instances }}"
   register: instanceid
```

##### EXPECTED RESULTS

The `Display instance id` task should output the instance's id.
The `Copy instance id to another variable` task should store the `system.instances.id` value to `instanceid`
##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'list object' has no attribute 'id'\n\nThe error appears to have been in '/Users/xxxxx/xxxxx/xxxxxx/ansible/roles/create-ec2/tasks/main.yml': line 40, column 4, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n - name: Display instance id\n   ^ here\n"}

fatal: [localhost]: FAILED! => {"failed": true, "msg": "template error while templating string: unexpected char u'x' at 7. String: {{i-xxxxxxxx}}"}
```

**Comment by 13dimitar** [comment]
Just an update, copying the value of a variable to another variable works if done like:

```
 - name: Copy instance id to another variable
   debug: msg={{ item.id }}
   with_items:
    - "{{ system.instances }}"
   register: instanceid
```

**Comment by global** [comment]
Hi, 

I don't  have the proper env to test, but I think there is a misunderstanding about the contents of the variables. 

```
 # this fails
 - name: Display instance id
   debug: var={{ system.instances.id }}
```

This should fail, as system.instances is a list of items. I think the syntax would be system.instances[0].id

And on this

```
# this fails
 - name: copy instance id to another variable
   debug: var={{ item.id }}
   with_items:
    - "{{ system.instances }}"
   register: instanceid
```

should also fail as you are trying to print the content of the variable {{ id-xxxxxx }} as {{ item.id }} will be evaluated to this ec2 id string. That's why using with msg= works.

So, if my theory is correct, the module is working as expected. 

// Anderson

**Comment by 13dimitar** [comment]
Hi,

your theory is correct, I've just tested it, which really means that the module works as designed.

Thanks!
