### ISSUE TITLE
How can I get the application UI in windows client

### ISSUE THREAD

**Issue by ntting** [ansible/ansible#18492]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_shell,  raw, command, script 

##### ANSIBLE VERSION

```
2.2.0.0
```
##### OS / ENVIRONMENT

server: centos7
client: window7 32bit

##### SUMMARY

I use the win_shell tu run a .bat file, it start a application in bat file. The application has a UI,  and how can i see the UI?  
I test raw is same problem.

```
  - name: run Gateway
    win_shell: "{{packagePath}}/runUShopGateway.bat {{startGatewayPath}}"
    async: 1814400
    poll: 0

```

##### EXPECTED RESULTS

I expect to show the interface for more opration.

**Comment by jhawkesworth** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by ntting** [comment]
I use the PsExec to start the application , it have the interface.
