### ISSUE TITLE
Wrong information in documentation about overriding task tags by role tags

### ISSUE THREAD

**Issue by mbialozor** [ansible/ansible#18499]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

Playbook Roles and Include Statements

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/s4a00351/work/ansible-appsrv/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 15:12:38) [GCC 7.1.1 20170503 (Red Hat 7.1.1-1)]
```

##### CONFIGURATION
[defaults]
ask_sudo_pass = True
become_method = sudo
hostfile = hosts 
hash_behaviour = merge

##### OS / ENVIRONMENT
Fedora release 26 (Twenty Six)
Linux nostromo.local 4.11.2-300.fc26.x86_64 #1 SMP Mon May 22 16:15:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY

http://docs.ansible.com/ansible/playbooks_roles.html

> Finally, you may wish to assign tags to the roles you specify. You can do so inline:
> (...)
> Note that this tags all of the tasks in that role with the tags specified, overriding any tags that are specified inside the role. If you find yourself building a role with lots of tags and you want to call subsets of the role at different times, you should consider just splitting that role into multiple roles.

It's not really true, as task tags are still "visible" and respected. Just take a look at the example below. First tag is a role tag, second one is a task tag.

```
(admin@server ansible)$ ansible-playbook group-internal.yml --list-tags

playbook: group-internal.yml

  play #1 (internal-group): Common tasks	TAGS: []
      TASK TAGS: [linux-config, linux-config-ipv6]
```

##### STEPS TO REPRODUCE

To reproduce include whole role with tags and assign different tag to one of the task inside the role.

```
Example PLAYBOOK:
- name: Common tasks
  hosts: internal-group
  become: yes
  roles:
    - { role: linux-config, tags: ['linux-config'] }

Example TASK:
- debug: msg="Bla bla bla."
  when: ipv6_disabled is defined and ipv6_disabled
  tags: linux-config-ipv6
```

##### EXPECTED RESULTS
According to documentation, task tags inside the role should not be respected.

##### ACTUAL RESULTS
Task tags inside the role are respected. It's worth to notice, that in my opinion, it's a **correct behavior** and this should persist. Only documentation should be corrected.

**Comment by mbialozor** [comment]
Looks like it's still present on Ansible 2.3.

**Comment by samccann** [comment]
This was resolved in the recent User Guide rewrites https://docs.ansible.com/ansible/devel/user_guide/playbooks_tags.html#tags
