### ISSUE TITLE
ERROR! 'with_items' is not a valid attribute for a PlaybookInclude

### ISSUE THREAD

**Issue by kivilahtio** [ansible/ansible#18504]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
PlaybookInclude + with_items

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### CONFIGURATION
Using default configurations from pip install ansible.
Using vault_password_file and vaults to protect sensitive passwords

##### OS / ENVIRONMENT
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

##### SUMMARY
- includes in playbooks don't work with attributes 'with_items' or 'static'

##### STEPS TO REPRODUCE
Using this playbook, I get this error:

```
---

- name: Provisioning LXC-containers
  hosts: ansible_controller

  - include: _platform_lxc.playbook inv_hostname="{{item}}"
#    static: no
    with_items: "{{groups['lxc']}}"


```

##### EXPECTED RESULTS
Ansible would execute the playbook with inv_hostname set for each host in lxc-group

##### ACTUAL RESULTS
```
ERROR! 'with_items' is not a valid attribute for a PlaybookInclude

The error appears to have been in '/home/kivilahtio/Ansible/buggy.playbook': line 7, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- include: _platform_lxc.playbook inv_hostname="{{item}}"
  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The error message is correct, this is not a bug, this is not a feature in Ansible. Play includes are not real tasks and do not support loops nor conditionals.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by kivilahtio** [comment]
Hi!
Thank you for your reply.
It was the most heartwarming way of saying RTFM :)

Can you explain to me why dynamic includes have been documented to the official manual then?
http://docs.ansible.com/ansible/playbooks_roles.html#id6

**Comment by bcoca** [comment]
Those are 'task' includes, not play includes. The docs clarifying the distinction are here:
http://docs.ansible.com/ansible/include_module.html

I'll update the linked docs as they do not clearly make that distinction.

**Comment by bcoca** [comment]
I hope this makes it clearer #18516
