### ISSUE TITLE
dict.iterkeys  (replace with for key in dict)

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#18507]
bot_skip

**Comment by Shaps** [comment]
Working on this

**Comment by Shaps** [comment]
iterkey also appears in:
`modules/core/cloud/vmware/vsphere_guest.py`
`modules/extras/cloud/amazon/ec2_vpc_route_table.py`

Will fix those in separate PRs

**Comment by abadger** [comment]
Thanks to @Shaps this is now complete!
