### ISSUE TITLE
py3: dict.has_key (replace with key in dict)

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#18505]
bot_skip

**Comment by jctanner** [comment]
These files make use of "has_key" ...

ansible/lib/ansible/modules/extras/system/crypttab.py
ansible/lib/ansible/modules/core/packaging/os/rhn_register.py
ansible/lib/ansible/modules/core/system/user.py
ansible/contrib/inventory/gce.py

**Comment by jctanner** [comment]
ansible/lib/ansible/modules/core/packaging/os/rhn_register.py is a special case that needs further investigation: https://github.com/ansible/ansible-modules-core/commit/196354656414377195319e656dd91c7ad95d4eec
