### ISSUE TITLE
py3: dict.iteritems

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#18506]
dict.iteritems() has gone away in python3.  To make code compatible you can do one of three things:

* If the dictionary isn't big, just use dict.items().
* If the dict is big and the code is in module (or module_utils) code use
```
from ansible.module_utils.six import iteritems
[...]
iteritems(dict)
```
* If the dict is big and the code is in controller code, use
```
from ansible.compat.six import iteritems
[...]
iteritems(dict)
```

**edited:** By abadger to clarify what the various ways of porting this code are.
bot_skip
** Edited2:** By abadger to remove "moves" from the import lines.

**Comment by Shaps** [comment]
Working on this

**Comment by Shaps** [comment]
iteritems appears **a lot** in modules, will open separate PRs for that

**Comment by abadger** [comment]
Thanks @shaps !  This is now done.
