### ISSUE TITLE
Link to COPYING in README (FEATURE IDEA)

### ISSUE THREAD

**Issue by vmullet** [ansible/ansible#18520]
Hello,
I checked your project and it is very interesting. I was thinking to add a link to your licence file (COPYING) in the README.md as people are often accustomed to search for the file "LICENCE" and not the file "COPYING". I will do a PR for that if you are interested :)

##### ISSUE TYPE

 - Feature Idea

**Comment by jctanner** [comment]
resolved_by_pr https://github.com/ansible/ansible/pull/18521
