### ISSUE TITLE
include_role does not import variables from outer role

### ISSUE THREAD

**Issue by danielkza** [ansible/ansible#18540]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Irrelevant

##### OS / ENVIRONMENT
Ubuntu 16.04 and OS X 10.11 (same behavior)

##### SUMMARY

Using `include_role` does not define variables from the outer role in the inner role, which makes it very cumbersome to combine roles in larger ones with common configuration.

##### STEPS TO REPRODUCE

test.yml
```yaml
- hosts: localhost
  tasks:
    - include_role: name=a
```

roles/a/defaults/main.yml
```yaml
outer_variable: I_SHOULD_BE_DEFINED
```

roles/a/tasks/main.yml
```yaml
- include_role: name=b
```

roles/b/tasks/main.yml
```yaml
- debug: msg={{ outer_variable }}
```

##### EXPECTED RESULTS
Correct value of `outer_variable` is printed when running `ansible-playbook -vv test.yml`

##### ACTUAL RESULTS
```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'outer_variable' is undefined\n\nThe error appears to have been in '/Users/danielkza/ansible/bug_test/roles/b/tasks/main.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- debug: msg={{ outer_variable }}\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
```

**Comment by krzysztof-magosa** [comment]
IMHO that behaviour is correct.
You can explicitly pass variables like that:

```
- name: Pass variables to role
  include_role:
    name: myrole
  vars:
    rolevar1: 'value from task'
```

**Comment by danielkza** [comment]
@krzysztof-magosa If this behavior is expected it should be documented then, as it is inconsistent with the "traditional" role inclusion method.

test-implicit.yml
```yaml
- hosts: localhost
  roles:
    - name: a
```

```
$ ansible-playbook -c local -i localhost, test-implicit.yml
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [b : debug] ***************************************************************
ok: [localhost] => {
    "msg": "I_SHOULD_BE_DEFINED"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

---

Unfortunately, explicitly passing variables (which I am actually already doing in the code that led me to the issue) isn't sufficient: it's quite common for the values of those variables to be composed from variables defined in the outer role. That obviously won't work as they won't be present in the included role. They would need to be eagerly evaluated - which is the workaround I've found, by using `set_fact`.

**Comment by alikins** [comment]
(formatted version of results in original comment)
``` json
{
   "failed" : true,
   "msg" : "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'outer_variable' is undefined
The error appears to have been in '/Users/danielkza/ansible/bug_test/roles/b/tasks/main.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- debug: msg={{ outer_variable }}
  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:
    with_items:
      - {{ foo }}
Should be written as:
    with_items:
      - "{{ foo }}"
"
}
```

**Comment by danielkza** [comment]
@alikins Thanks! Just to point it out, I tried quoting (my original reproduction case was quoted) and it doesn't change anything, the variable is actually undefined.

**Comment by danielkza** [comment]
Issue is still present in 2.2.1.0-0.1.rc1, even though some fixes for includes are mentioned.

**Comment by kimamula** [comment]
include_role still does not import variables defined in defaults of the outer role.
Is this an expected behavior?

I am using Ansible 2.2.1.0.

**Comment by h3po** [comment]
I just noticed that even explicitly passed variables are not handed down when include_role is used twice, eg:

```
site.yml:
- roles:
  - role_a

roles/role_a/tasks/main.yml:
- include_role:
    name=role_b
  vars:
    var_from_role_a: "test"

roles/role_b/tasks/main.yml:
- include_role:
    name: role_c
  vars:
    var_from_role_b: "{{var_from_role_a}}"

roles/role_c/tasks/main.yml:
- debug: msg={{var_from_role_b}}
```

yields {{var_from_role_a}} is undefined. Not sure if related to this issue, since it depends on when the yaml template is expanded.

**Comment by JoelFeiner** [comment]
I am still having this same issue on Ansible 2.3.0.0.

Example:
```
# task inside parent role play
- name: Configure AWS backups (via awsbackup role)
  include_role:
    name: awsbackup
  vars:
    awsbackup_profile_name: 'foobar'

# task inside awsbackup role
- debug:
    var: awsbackup_profile_name
```

That outputs:
```
ok: [some_host] => {
    "awsbackup_profile_name": null, 
    "changed": false
}
```

There is a default value (empty) for that variable in the `defaults/main.yml` file for the `awsbackup` role.
