### ISSUE TITLE
Target host syslog logging accidentally tied to runtime verbosity

### ISSUE THREAD

**Issue by omgjlk** [ansible/ansible#18569]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Module execution logging on the target host

##### ANSIBLE VERSION

```
ansible-playbook 2.2.0.0
  config file = /Users/jkeating/src/hoist/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

Prior to https://github.com/ansible/ansible/commit/a56c0bc27b07356c3639c0ac39805d4e5dd91171 when ansible executed a module on a target host, the invocation of that module was logged to syslog, which was useful for auditing who's doing what to a particular host with Ansible. After that commit, the logging only happens if the execution of ansible was done with verbosity level 3 or above.

##### STEPS TO REPRODUCE

Execute ansible-playbook with less than verbosity 3, no indication on remote host that anything was done.

##### EXPECTED RESULTS

I would expect to see things like:

```
Nov 21 19:06:08 datadog-demo ansible-user[31027]: Invoked with comment=None ssh_key_bits=0 update_password=always non_unique=False force=False ssh_key_type=rsa ssh_key_passphrase=NOT_LOGGING_PARAMETER createhome=True uid=None home=None append=False skeleton=None ssh_key_comment=ansible-generated on datadog-demo group=nodepool system=False state=present shell=None expires=None ssh_key_file=None groups=None move_home=False password=NOT_LOGGING_PARAMETER name=nodepool seuser=None remove=False login_class=None generate_ssh_key=None
```

##### ACTUAL RESULTS

There is no logging of the module execution.

**Comment by jctanner** [comment]
@bcoca ping

**Comment by jylenhofgfi** [comment]
I confirm the patch works also on the 2.2 branch. 
Could you please push it to the 2.2 stable branch ?

Thanks

**Comment by bcoca** [comment]
backported to 2.2, so closing this issue.
