### ISSUE TITLE
build a Single file

### ISSUE THREAD

**Issue by netw0rm** [ansible/ansible#18562]
I want to build a single file for ansible use pyinstaller, but i failed.
anyone can tell me about how to build a single file for ansible?
thanks

**Comment by jhawkesworth** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
