### ISSUE TITLE
Feature Request: ansible module to support Sophos UTM Restful API since v9.408

### ISSUE THREAD

**Issue by FleischKarussel** [ansible/ansible#18568]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

- SophosUTM
Probably this would be applicable for the XG firewall aswell.

##### ANSIBLE VERSION

```
Next release?
```

##### SUMMARY

I would like to see a module in the same manner as the other network OS that are already supported by ansible.
Even though the feature set of the UTM is bigger.
Most important would be Routing, firewall, networks, interfaces, up2date.

**Comment by laymonk** [comment]
I have been thinking about writing a module for this, but have not yet found the time.  SophosUTM is a great platform, and Sophos is doing a great thing keeping the [Sophos UTM Home Edition](https://www.sophos.com/en/products/free-tools/sophos-utm-home-edition.aspx#) free and available to  devops type consultants.  Support for it by Ansible will be awesome and most welcome.

**Comment by gundalow** [comment]
Hi,
This is something we'd look for the community to come up with, it's not something I'd expect to come up onto the Core Team's Roadmap.

FYI there is a weekly Network Meeting, which may be useful (best practices, ideas on getting started, etc)

See https://github.com/ansible/community/issues/110 for more info

**Comment by gundalow** [comment]
Leaving this ticket open so other people can find it when searching for Sophos

**Comment by calfonso** [comment]
needs_contributor

**Comment by MatrixCrawler** [comment]
As we need a module like this for our use case @getjack and i decided to give it a try
