### ISSUE TITLE
should be able to set "user" in hosts file.

### ISSUE THREAD

**Issue by legrostdg** [ansible/ansible#1857]
It's quite frustrating not to be able to set user in the host file: the remote user used for ssh connection could be different depending on the hosts. Another cool solution would be to parse ~/.ssh/config to find the user.

**Comment by dhozac** [comment]
#1825 addresses this.

**Comment by legrostdg** [comment]
Thanks for the link, it would be good to mention "ansible_ssh_user" (by the way, wouldn't it better to call it "user" instead of "ansible_ssh_user") in the doc...
Hum, that does not seem to work:

```
# hosts
virt ansible_ssh_user=virt ansible_ssh_host=192.168.122.216

# command line
$ ansible virt -m ping 
sudo password: 
virt | FAILED => FAILED: ssh gueux@192.168.122.216:22 : Private key file is encrypted
To connect as a different user, use -u <username>.
```
