### ISSUE TITLE
Module 'service' does not use initscripts correctly

### ISSUE THREAD

**Issue by c0rner** [ansible/ansible#1858]
On servers only using init scripts ('/etc/init.d') the service module will fail on get_service_status(self) and possibly other methods.

A fix would be to use the service_control(self) method or add something like

'if self.running is None and self.svc_initscript != None:
            rc, status_stdout, status_stderr = self.execute_command("%s status %s" % (self.svc_initscript, self.arguments))'

as the second line in get_service_status(self).

Commit used: 1cbc9569b3cfc0fb1e668117bb00fbba134a2b61

**Comment by mpdehaan** [comment]
Please send in a pull request.

**Comment by mpdehaan** [comment]
closed given merger of the above, thank you!
