### ISSUE TITLE
slurp bug - unable to read ansible setup file affecting templates

### ISSUE THREAD

**Issue by cocoy** [ansible/ansible#186]
$ ansible web-servers -m template -a "src=templates/foo.j2 dest=/tmp/some_random_foo.conf" -u ubuntu 

{"msg": "file is not readable: ~/.ansible/setup", "failed": 1}

**Comment by mpdehaan** [comment]
Thanks, fix pushed on the integration branch.   This code is quite new and I apparently didn't test the non-root execution path.  The path now expands on the remote side, and I have fixed the error message.

**Comment by mpdehaan** [comment]
If you just pulled when I said that, minor correction -- fixed _now_
