### ISSUE TITLE
How to roll back or change the version Ansible?

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#18609]
How to roll back or change the version?

**Now:** Ansible 2.2.0.0

**Need:** Ansible 2.1.2

The simpler the better
Thanks in advance

**Comment by jhawkesworth** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by ghost** [comment]
# check the version
ansible --version

# version rollback 2.1.2
sudo pip install ansible==2.1.2
