### ISSUE TITLE
Master playbook with multiple include same sub playbook run only once

### ISSUE THREAD

**Issue by trompx** [ansible/ansible#18613]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Multiple playbook includes in master playbook

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
inventory_ignore_extensions = ~, .orig, .bak, .ini, .retry, .pyc, .pyo, .tfstate
gathering = smart
fact_caching = jsonfile
fact_caching_connection = /vagrant/facts
fact_caching_timeout = 86400

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY
When I include twice the same playbook in a master playbook with different params, the playbook is run only once.

##### STEPS TO REPRODUCE

masterplaybook.yml
```
---

- include: playbook.yml
    hosts="test1"
    myvar="ok"

- include: playbook.yml
    hosts="test2"
    myvar="ko"
```

playbook.yml
```
- name: Playbook
  hosts: "{{ hosts }}"
  gather_facts: true
  remote_user: myuser
  tasks:
    - debug: msg={{myvar}}
```

##### EXPECTED RESULTS
When running master.yml, I would expect that playbook.yml run twice and output:
```
ok
ko
```

##### ACTUAL RESULTS
Only run the first time and output:
```
ok
```

**Comment by gundalow** [comment]
I believe your case is shown as a feature on http://docs.ansible.com/ansible/playbooks_roles.html#task-include-files-and-encouraging-reuse `wp_user` in the docs is the same as `myvar` in your example.

Closing as not a bug

**Comment by trompx** [comment]
wordpress.yml is a list of tasks without host declaration, my playbook.yml has already a host declaration. I cannot do:
```
---
tasks:
   - include: playbook.yml
       hosts="test1"
       myvar="ok"

   - include: playbook.yml
       hosts="test2"
       myvar="ko"
```

**Comment by gundalow** [comment]
I received this from @trompx 


> wordpress.yml is a list of tasks without host declaration, my playbook.yml has already a host declaration. I cannot do:
```yaml
---
tasks:
   - include: playbook.yml
       hosts="test1"
       myvar="ok"

   - include: playbook.yml
       hosts="test2"
       myvar="ko"
—
```

**Comment by trompx** [comment]
I posted this because I had just upgraded from 1.9 to 2.2 and was having this problem. After reinstalling my VM and reinstalling ansible, the problem seems to be gone, weird.

You can close for now, if this happens again I'll come back to you.

Thanks for answering so fast @gundalow
