### ISSUE TITLE
Measure and track ansible performance (publicly)

### ISSUE THREAD

**Issue by robinro** [ansible/ansible#18612]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
core, testing

##### ANSIBLE VERSION
devel

##### SUMMARY
Especially for 1.9->2.x transitions, but also more general there are discussions on ansible performance, like #17528. 

It might be a good idea to improve these discussions by having public performance benchmarks to find weak spots and avoid regressions. To me this could be a mix of dedicated performance tests (large inventories/variable setups) and some of the existing integration tests.

Tests should cover both core performance (parsing inventory, iterating over tasks, connections) as well as modules.

A realization could be similar to http://speed.pypy.org/

Of course performance for ansible is not as critical as for pypy, but for many users performance can become essentail depending on the use case.

**Comment by gundalow** [comment]
Interesting idea and example, thanks.

@mattclay Something to maybe discuss?

**Comment by bcoca** [comment]
I would move this to proposals https://github.com/ansible/proposals

**Comment by mattclay** [comment]
Definitely worth discussing, but lets move it to proposals as bcoca suggested.

**Comment by robinro** [comment]
I opened https://github.com/ansible/proposals/issues/42 to replace this.

**Comment by gundalow** [comment]
Good idea, thanks
