### ISSUE TITLE
ansible connection closed when running task

### ISSUE THREAD

**Issue by winger007** [ansible/ansible#18619]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ansible connection closed frequently, at the same time, native ssh test is running normally

##### ANSIBLE VERSION

```
ansible 1.9.6
```

##### CONFIGURATION

[defaults]
forks = 100
inventory = /home/test/inventory 
pipelining = True
host_key_checking = False

##### OS / ENVIRONMENT

CentOS Linux release 7.2.1511 (Core)
##### SUMMARY

In our test environment, ansible lost connection frequently.
  
##### STEPS TO REPRODUCE

1. copy below ansible test script
2. change the inventory and host ip in the script, and copy public key to target host
3. run the ansible test script

at the same time, I start another native ssh test

ansible-test.bash
```
count=0
echo `date` >> ansible.log
while [ true ];do
        count=$((count + 1))
        echo $count >> ansible.log
        ansible -vvvv -i /home/test/inventory 172.20.198.103 -m shell -a "ls && sleep 5" >> ansible.log 2>&1
        if [ $? -eq 0 ];then
                sleep 1
        else
                echo `date` >> ansible.log
                echo "failed" >> ansible.log
                exit 1
        fi
done
```
native-ssh-test.bash
```
count=0
while [ true ];do
	count=$((count + 1))
        echo $count >> shell.log
	ssh root@172.20.198.103 'ls && sleep 5' >> shell.log 2>&1
	if [ $? -eq 0 ];then
		sleep 1
	else
		echo date >> shell.log
		echo "failed" >> shell.log
		exit 1
	fi
done
```

##### EXPECTED RESULTS

The test process should not be break.
If network problem, all test scripts will break at the same time.

##### ACTUAL RESULTS

After long time run(maybe half hour or one hour), the ansible test script will break while native ssh test script running all the  time.

```
172.20.198.103 | FAILED >> {
    "failed": true, 
    "msg": "OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 57: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 18621\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to 172.20.198.103 closed.\r\n", 
    "parsed": false
} 
```

**Comment by winger007** [comment]
the difference between two tests is ansible use some ssh arguments:
```
<172.20.198.103> ESTABLISH CONNECTION FOR USER: root
<172.20.198.103> REMOTE_MODULE service name=virtlockd state=started enabled=yes
<172.20.198.103> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 172.20.198.103 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1479999397.17-152159219821925 && echo $HOME/.ansible/tmp/ansible-tmp-1479999397.17-152159219821925'
EXEC previous known host file not found for 172.20.198.103
<172.20.198.103> PUT /tmp/tmpKfp3rF TO /root/.ansible/tmp/ansible-tmp-1479999397.17-152159219821925/service
<172.20.198.103> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 172.20.198.103 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1479999397.17-152159219821925/service; rm -rf /root/.ansible/tmp/ansible-tmp-1479999397.17-152159219821925/ >/dev/null 2>&1'
EXEC previous known host file not found for 172.20.198.103

```
I have a question, if 'ControlPersist' timeout, ssh will close automatically, but if at the same time, ansible setup a new ssh connection, will still use the old ControlPath socket?

**Comment by gundalow** [comment]
Hi @winger007 Thanks for the bug report.
Ansible 1.9 is fairly old and well soon be out of support. Could you please retest on Ansible 2.2. There have been a huge amount of changes between these release.

needs_info

**Comment by winger007** [comment]
Hi @gundalow , thanks for your reminder, but I use ansible API all the time, seems after 2.0, the API changes a lot.

**Comment by samdoran** [comment]
Closing per above discussion.

For further help with the issue, please reach out on IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
