### ISSUE TITLE
Using ansible to do a passwordless deployment doesn't seem to work.

### ISSUE THREAD

**Issue by zkanda** [ansible/ansible#18623]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
On any component that needs sudo access.

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /home/zkanda/code/github.com/serverconf/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
I just added `pipeling = True` on ansible.cfg

##### OS / ENVIRONMENT
Ubuntu 16.10

##### SUMMARY
I want to have a passwordless deployment using jenkins.

##### STEPS TO REPRODUCE
Basically I set this in my sudoers:

```
%deploy ALL=(ALL) NOPASSWD: /usr/sbin/service nginx *
```

And running `sudo service nginx reload` works fine.

However using ansible with this task is asking me for password.

```
- name: Reload nginx
  become: Yes
  service: name=nginx state=reloaded
```

##### EXPECTED RESULTS
It shouldn't ask me for my password,

##### ACTUAL RESULTS
It's asking me for my password.

Someone in IRC told this is not possible because ansible is not actually running `sudo service nginx reload` instead it's just running python files. So the issue now is how do I actually run it without using a password? Or is there another way to do it?

Thank you.

**Comment by dano0b** [comment]
Hi @zkanda ,

privilege escalation permissions have to be general. You can find more info here: http://docs.ansible.com/ansible/become.html#can-t-limit-escalation-to-certain-commands 

regards,
dano0b

**Comment by gundalow** [comment]
Closing as not a bug as detailed by @dano0b, thanks for that

**Comment by zkanda** [comment]
@dano0b Pardon my ignorance but I'm not sure what it meant by "privilege escalation permissions have to be general"?

I tried doing this, but it's still asking for my password if I use become.

```
%deploy ALL=(ALL) NOPASSWD: /usr/bin/python *
```

**Comment by dano0b** [comment]
Hi @zkanda ,
you are still trying to limit your command, in this case to /usr/bin/python. The executable that is invoked via sudo is generated. You can imagine a sudo command like: sudo $ansibleWorkDir/generatedExecutable

Hope that helps you to understand why you can't limit it.
