### ISSUE TITLE
ansible fails task with no satisfied conditional in loops

### ISSUE THREAD

**Issue by alex-left** [ansible/ansible#18622]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
conditionals with loops

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### SUMMARY
if you have a task with a variable conditional and this task have a loop with same variable, the task must be skipped but before fails

 
##### STEPS TO REPRODUCE

```
- name: debug
  debug: msg= {{ item }} is ok
  when: my_variable is defined
  with_items: "{{ my_variable }}"
#my_variable must be indefined when playbook is executed
```

##### EXPECTED RESULTS
task skipped because "my_variable" is not defined. 

##### ACTUAL RESULTS

The task fail. 
```
TASK [test : debug] **********************************************************
fatal: [develop]: FAILED! => {
    "failed": true, 
    "msg": "'my_variable' is undefined"
}

```

**Comment by gundalow** [comment]
Hi,
This is a by design change that went into Ansible 2.2
From https://github.com/ansible/ansible/blob/devel/CHANGELOG.md#removed-deprecated
>skipping on undefined variables in loop, now loops will have to define a variable or use `|default` to avoid errors.
