### ISSUE TITLE
Ziploader (ansiballz) fails to work if time predates 1980

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#18640]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ziploader

##### ANSIBLE VERSION

v2.1 and newer

##### CONFIGURATION

Raspberry Pi 3 running aarch64

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

Raspberry Pi's don't have a hardware clock and depends heavily on NTP. Which means that systems won't have a proper date set (they go to epoch by default) until NTP is installed, configured and working.

Now there is a silly problem with zip that it fails to work if the time predates 1980.

```
[dag@moria berries]$ ansible-playbook config.yml -l berry4 -u root

PLAY [berries] *****************************************************************

TASK [setup] *******************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: ZIP does not support timestamps before 1980
fatal: [berry4]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 128, in <module>\n  File \"/usr/lib64/python2.7/zipfile.py\", line 1202, in writestr\n    date_time=time.localtime(time.time())[:6])\n  File \"/usr/lib64/python2.7/zipfile.py\", line 305, in __init__\n    raise ValueError('ZIP does not support timestamps before 1980')\nValueError: ZIP does not support timestamps before 1980\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

Not sure if we can easily do anything about this, or even if this is something we want to fix, as workarounds are possible using raw/command. It's still a burden that ziploader has this dependency to the realtime clock especially since there's a lot to do to set up NTP (network, packages, configuration)...

**Comment by gundalow** [comment]
@abadger FYI

**Comment by bcoca** [comment]
no reason given ... but this seems to be from the underlying library
https://docs.python.org/2/library/zipfile.html#zipfile.ZipInfo.date_time

**Comment by vielmetti** [comment]
@dagwieers just a note that one workaround for the lack of a hardware clock on RPi hardware is 'fakehwclock' there's a Raspbian version and also this re-implmentation done for Arch Linux https://github.com/xanmanning/alarm-fake-hwclock  . You basically save state at shutdown time and restore state at boot time, so that your remote clock is less off.

**Comment by dagwieers** [comment]
@vielmetti Right, but I don't see how that is relevant here. With the implemented fix Ansible does not rely on time, so you can do things like set up NTP or install the fake hwclock and actually set the time correctly.

**Comment by vielmetti** [comment]
Ah good thanks @dagwieers - I had misinterpreted the order of events - this now makes sense.
