### ISSUE TITLE
Ability to transfer files over SSH without scp/sftp

### ISSUE THREAD

**Issue by agaffney** [ansible/ansible#18642]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
`ssh` connection plugin

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
It would be nice to be able to transfer files with the `ssh` connection plugin without the use of `scp` or `sftp`. I'm talking about using `dd` and "streaming" the file content, much like is done with the `chroot` and `docker` connection plugins.

The need for something like this is a bit of a corner case. It's possible to have a remote system running `sshd` without having `sftp` or `scp` available (by removing their "helper" binaries on the remote side), in which case file transfers with ansible will currently fail. This would also be helpful in the case of poor man's connection plugin chaining (setting `ansible_shell_executable` to point to a wrapper script which does something like `chroot /mnt/gentoo /bin/sh "$@"`).

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A

**Comment by agaffney** [comment]
I dug into the code a bit to attempt to hack something up, but the `ssh` connection plugin's code isn't exactly straightforward or easy to understand. I *think* the way to handle this is to allow passing in your own `stdin` pipe to the `_run()` function. This would bypass the pseudo-tty allocation and use the provided `stdin` pipe in the `subprocess.Popen()` call(s).

A slightly hackier method is reading in the file and passing it via `in_data`, but that requires putting the entire file content into memory, which is something that is explicitly avoided in the other connection plugins that use this method for file transfers.

Even once the above is sorted out, there's still the question of activating this method. It doesn't seem to fit into the current functionality of the `scp_if_ssh` config param, and relying on the `smart` behavior probably isn't the best idea.

**Comment by agaffney** [comment]
@bcoca, I'd like your feedback on how crazy/stupid of an idea this is.

**Comment by agaffney** [comment]
PR to add this functionality:

https://github.com/ansible/ansible/pull/18643

**Comment by jctanner** [comment]
resolved_by_pr https://github.com/ansible/ansible/pull/18643

**Comment by agaffney** [comment]
Closing this, since there's no need for an issue when I also have a PR.
