### ISSUE TITLE
Run integration tests on openSUSE leap 42.2

### ISSUE THREAD

**Issue by robinro** [ansible/ansible#18645]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
integration tests

##### ANSIBLE VERSION
devel

##### SUMMARY
So far the integration tests run on openSUSE leap 42.1. Recently 42.2 was published and the tests should also cover the new version. Probably testing on the 2 most recent releases is a good idea, since typically support for the non-enterprise releases includes only the latest 2 versions.

**Comment by robinro** [comment]
I might help with that but am happy if someone else has a go.

**Comment by gundalow** [comment]
@robinro Good spot, thanks for the suggestion, and the offer of help

@mattclay What do you think? Something to look at after the repo merge?

**Comment by mattclay** [comment]
Yeah, this is something we can look at after the repo merge.

**Comment by gundalow** [comment]
I've added it to the Testing Project in GitHub, so will will see it when we review that.
