### ISSUE TITLE
Play continues after a failed task (regardless the any_errors_fatal: true enabled ) execution if the block is used.

### ISSUE THREAD

**Issue by cebotareanu** [ansible/ansible#18667]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
n/a
##### ANSIBLE VERSION

ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

##### CONFIGURATION
No changes
##### OS / ENVIRONMENT

Linux host 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY
Play continues after a failed task with **any_errors_fatal: true** , when the playbook is using the "block" construct.
Same test without block - all working as expected.

##### STEPS TO REPRODUCE
We will be using 3x playbooks, main and 2x includes as follows:

1. test_main.yml
```
---
- name: Just playbook
  hosts: localhost
  connection: local
  any_errors_fatal: true
  gather_facts: no

  tasks:
    - debug: msg="This is task from main playbook"

- include : test.yml
  when: 2 > 1
- include : test2.yml
  when: 2 > 1
```
2. test.yml
```
- name: 1st include playbook
  hosts: localhost
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - block:
      - debug: msg="This is the task from block, 1st include"
      - name: Test for Fail
        fail: msg="Failer in 1st include playbook"
        when: "2 > 1"
      rescue:
        - debug: msg="This is the task from rescue, 1st include"
```
3.  test2.yml
```
- name: 2nd include playbook
  hosts: localhost
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - block:
      - debug: msg="This is the task from block, 2nd include"
      - name: Test for Fail
        fail: msg="Failer in 2nd include playbook"
        when: "2 > 3"
      rescue:
        - debug: msg="This is the task from rescue, 2nd include"
```
The playbook will be executed as follows:

ansible-playbook test_main.yml

##### EXPECTED RESULTS

It was expected the playbook will stop after 1st error, and no more "hosts" or "tasks" will be executed.

##### ACTUAL RESULTS

The playbook reported the "fatal" alert but continued to execute the rest of the tasks.
```
PLAY [Just playbook] ***********************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "This is task from main playbook"
}

PLAY [1st include playbook] ****************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "This is the task from block, 1st include"
}

TASK [Test for Fail] ***********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failer in 1st include playbook"}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "This is the task from rescue, 1st include"
}

PLAY [2nd include playbook] ****************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "This is the task from block, 2nd include"
}

TASK [Test for Fail] ***********************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0


Same test, without the block, demonstrated expected logic:


 ansible-playbook test_main_noblock.yml

PLAY [Just playbook] ***********************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "This is task from the main playbook"
}

PLAY [1st include playbook] ****************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "This is the task from block, 1st include"
}

TASK [Test for Fail] ***********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failer in 1st include playbook"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Having a rescue for a block means you are handling the error, so the fail on first is not triggered.

The rescue
In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by cebotareanu** [comment]
Hi,
maybe you are right, maybe I described the issue in the wrong way.
What I was looking to say is the following:
1. There is a playbook, on the "playbook" level the any_errors_fatal: true is activated.
My expectation is this should stop the playbook(s) to be executed.
2. I have several playbooks (nested/included), all are configured with any_errors_fatal: true
3. I have one playbook with Block.
My expectation is this Block will allow me to call a rescue task along with "registered" alarm 
4. Summary:
I thought (maybe wrong) the logic should be like this:
The block will allow me to call the rescue task, same time any_errors_fatal: true will allow me to
stop the playbook.

BR,

**Comment by bcoca** [comment]
That is not a feature, use the `fail` module in the `rescue` block if you wish this to happen.

**Comment by cebotareanu** [comment]
In this case, please review my original comments.
I am using the fail - but it's not "failing..."

**Comment by maxgalbu** [comment]
you can use `always` instead of `rescue` if all you want is log the error somewhere
