### ISSUE TITLE
ansible-playbook silently ignores unknown hosts

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#18669]
##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

inventory / connection

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Ubuntu 16.04, ansible 2.2 from PPA

##### SUMMARY

If you mistype a hostname in a playbook, ansible-playbook silently skips the play.

##### STEPS TO REPRODUCE

```
$ cat hosts
foo
$ cat ert.yml
- hosts: bar
  tasks:
    - debug: msg=wibble
```

##### EXPECTED RESULTS

I expected to get an error because I referenced a hostname or group which is not in the inventory (and FWIW is also not in the DNS) - or at least some sort of warning.

##### ACTUAL RESULTS

```
$ ansible-playbook -i hosts ert.yml

PLAY RECAP *********************************************************************

$
```

```
$ ansible-playbook -i hosts -vvvv ert.yml
Using /etc/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: ert.yml **************************************************************
1 plays in ert.yml

PLAY RECAP *********************************************************************

$
```

##### ADDITIONAL INFO

The standalone `ansible` tool *does* give a warning in this scenario:

```
$ ansible bar -i hosts -m setup
 [WARNING]: No hosts matched, nothing to do
```

`ansible-playbook` in ansible 1.9.4 gave an info message:

```
$ ansible-playbook -i hosts ert.yml

PLAY [bar] ********************************************************************
skipping: no hosts matched

PLAY RECAP ********************************************************************
```

I am guessing the use case for not generating an error is something to do with dynamic inventory? But if it's not possible to give an error here, at least an info message would be useful.

**Comment by bcoca** [comment]
It cannot give an error as subsequent plays might match the host/group you request, as well as have them created on the fly via add_host/group_by.
