### ISSUE TITLE
Git module fails to add hostkey to known_hosts and doesn't notice it

### ISSUE THREAD

**Issue by ngo** [ansible/ansible#18676]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ansible.module_utils.known_hosts

##### ANSIBLE VERSION
```
ansible 2.1.3.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Ubuntu 16.04 

##### SUMMARY

Function add_host_key which gets called from  add_git_host_key, which gets called from the git module when accept_hostkey=yes, does not check that the output from ssh-keyscan is not empty. But ssh-keyscan has a timeout (5 seconds by default), and if the server could not answer in a timely manner, ssh-keyscan prints nothing to stdout and returns with return code 0. Ansible assumes that this operation is successful and proceeds to call git, which then hangs on a host key confirmation dialog.

The demonstration is as follows (I used -T1 to reproduce more easily, with default timeout of 5 seconds this also happens)
```
~$ ssh-keyscan -t rsa -T 1  bitbucket.org // this is succesful
# bitbucket.org:22 SSH-2.0-conker_1.0.263-aeae7ee app-134
bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
~$ echo $? // ret code zero
0
~$ ssh-keyscan -t rsa -T 1  bitbucket.org // this one failed
~$ echo $? // ret code still zero
0
```

##### STEPS TO REPRODUCE

Execute a git task with a slow git server with accept_hostkey=yes

##### EXPECTED RESULTS

Fail with a meaningful error specifying that the keyscan was unsuccessful. Also, a way to increase the default timeout would be nice.

##### ACTUAL RESULTS

The module hangs indefinitely

related issue: https://github.com/ansible/ansible-modules-core/issues/1343

**Comment by abadger** [comment]
@ngo thanks for tracking this down!  I've opened a pull request with a potential fix here: https://github.com/ansible/ansible/pull/18698
