### ISSUE TITLE
systemd fails to enable sysv services

### ISSUE THREAD

**Issue by telbizov** [ansible/ansible#18687]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - systemd module (core/systemd.py)

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```
[defaults]
forks=40
timeout=60
remote_user=root
module_name=shell
error_on_undefined_vars=True
jinja2_extensions=jinja2.ext.do
retry_files_enabled = False
retry_files_save_path = ~/
#host_key_checking=True

[ssh_connection]
pipelining=True
scp_if_ssh=True
control_path=%(directory)s/%%h-%%p-%%r
```

##### OS / ENVIRONMENT
 - MacOS controlling host
 - Debian 8.6 target/managed host

##### SUMMARY
We experience the following issue with ansible 2.2.0. On a systemd OS (Debian 8), the systemd.py module seems to fail to workaround the Debian issue with the broken 'is-enabled' target on daemons that only provide sysv scripts and no systemd scripts. If a systemd .service file is present in addition to the sysv /etc/init.d/script or standalone it functions fine. Please find some additional details and a proposed patch against 2.2.0.0 (which seems will be different against HEAD) further in this ticket.

##### STEPS TO REPRODUCE
```
apt-get install atop # (an example deamon without systemd service file. it enables itself upon install by creating the required symlinks)

# ls -l /etc/rc?.d/S??atop
lrwxrwxrwx 1 root root 14 Nov 29 19:20 /etc/rc2.d/S02atop -> ../init.d/atop
lrwxrwxrwx 1 root root 14 Nov 29 19:20 /etc/rc3.d/S02atop -> ../init.d/atop
lrwxrwxrwx 1 root root 14 Nov 29 19:20 /etc/rc4.d/S02atop -> ../init.d/atop
lrwxrwxrwx 1 root root 14 Nov 29 19:20 /etc/rc5.d/S02atop -> ../init.d/atop

ansible -i inventory host -m service -a 'name=atop enabled=no'
... "changed": true, "enabled": false ...

ls -l /etc/rc?.d/S??atop
ls: cannot access /etc/rc?.d/S??atop: No such file or directory
```

So far so good! Ansible has successfully disabled the service. Now let's try to re-enable it.

```
ansible -i inventory host -m service -a 'name=atop enabled=yes'
... "changed": false, "enabled": true ...

# ls -l /etc/rc?.d/S??atop
ls: cannot access /etc/rc?.d/S??atop: No such file or directory
```

As you can see ansible did not re-enable the service, even though it reports that it is enabled in the output (and no change).

The underlying issue lies in:
```
# systemctl is-enabled atop
Failed to get unit file state for atop.service: No such file or directory

# echo $?
1
```
This is a well-known, long-standing bug in the Debian 8 systemd which was supposed to be worked around in Ansible 2.x. It might be a regression in 2.2.0.

##### EXPECTED RESULTS
Expected to see the service being reenabled again after execution.

##### ACTUAL RESULTS
Ansible fails to reenable the service, thinking incorrectly that it is already enabled

```
ansible -i inventory host -m service -a 'name=atop enabled=yes'
... "changed": false, "enabled": true ...
```

##### SUGGESTED PATCH
systemd.py assumes that if the exit code of systemctl is 1 and the output does not start with 'disabled' then the service must already be enabled. Unfortunately due to the Ansible bug the output is empty. The following patch has been tested against 2.2.0 but it might need adaptation against HEAD.

```
--- systemd.py.bkp    2016-11-28 16:24:23.000000000 -0800
+++ systemd.py    2016-11-29 15:10:26.000000000 -0800
@@ -322,12 +322,12 @@
         # check systemctl result or if it is a init script
         if rc == 0:
             enabled = True
-        elif rc == 1:
+        elif rc == 1 and out.rstrip() != 'disabled':
             # Deals with init scripts
             # if both init script and unit file exist stdout should have enabled/disabled, otherwise use rc entries
             initscript = '/etc/init.d/' + unit
             if os.path.exists(initscript) and os.access(initscript, os.X_OK) and \
-               (not out.startswith('disabled') or bool(glob.glob('/etc/rc?.d/S??' + unit))):
+               bool(glob.glob('/etc/rc?.d/S??' + unit)):
                 enabled = True

         # default to current state
```

**Comment by dagwieers** [comment]
@telbizov Why don't you create a Pull Request ? You don't even need to know git commands, you can do it by editing the file directly in your browser on GitHub.

**Comment by telbizov** [comment]
I was going to indeed, but then I hesitated when I noticed that HEAD is different and I didn't have time to adapt the change and more importantly test against HEAD. Also I am not quite certain of the development cycle and if I should submit two PRs - one for HEAD and maybe one for the branch? If directed I could do the work.

Anyway, I reckoned I should get the report in here first to have more eyes on the issue and have others confirm that this is in fact a problem.

**Comment by dagwieers** [comment]
@telbizov Fair enough.

**Comment by abadger** [comment]
the service module is a module so lives in the ansible-modules-core repository.  We're hopefully merging the repos next week, though, so I'll just leave this here.   CC ing bcoca since he's doing work on the systemd and service modules

\cc @bcoca

**Comment by telbizov** [comment]
@abadger and @bcoca any development on this issue?
