### ISSUE TITLE
ansible stops at shell/tar action

### ISSUE THREAD

**Issue by nicolaasuni** [ansible/ansible#1869]
on a long playbook, the following action is executed but ansible stops and wait forever: 

action: shell cd /tmp/${somedir} && tar -zcvf archive.tar.gz archive && rm -rf archive

This action works with the version 2012-12-05 but not with the latest version (just pulled from repo).

Similar actions are executed normally even on the same playbook.

I also tried:

action: shell tar -zcvf /tmp/${somedir}/archive.tar.gz /tmp/${somedir}/archive

but it stops in the same way.

Maybe the problem is elsewhere but it just happens with the latest Ansible releases.

**Comment by mpdehaan** [comment]
which release did it start in?

**Comment by mpdehaan** [comment]
other things interesting

what OS?
running with sudo or not?  Does that affect behavior?
what connection type?

**Comment by nicolaasuni** [comment]
> which release did it start in?

The last working version I tried is the one I pulled 2012-12-05 18:34.
Then I tried the version 2013-01-07 17:20 and that it was showing this bug.
So the problem is between these versions.

> what OS?

CentOS release 6.3 (Final)
Linux ansible.lab 2.6.32-279.19.1.el6.x86_64 #1 SMP Wed Dec 19 07:05:20 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

> running with sudo or not?

running as a root.

> Does that affect behavior?

The problem is that the playbook stops and waits forever. Successive tasks are never executed.

> what connection type?

SSH

**Comment by mpdehaan** [comment]
Interesting.   Especially as it wasn't related to the development branch
sudo temporarily using -i.

Does this work with any size tarball?   If you created a tarball containing
just helloworld.txt does it still happen?

This may require some help debugging on your end.

Thanks!

**Comment by mpdehaan** [comment]
There were some issues fixed recently about ansible choking on commands with lots of output, it's probably not related.   Curious if you are still seeing this.

In any event, a quicker reply to questions will result in problems being looked into faster :)

**Comment by nicolaasuni** [comment]
I am testing the version I pulled this morning and seems OK, but I'll let you know as soon I finish to execute all playbooks.

**Comment by nicolaasuni** [comment]
The issue seems fixed with the latest version.
