### ISSUE TITLE
WINRM Unable to connect via IPv6

### ISSUE THREAD

**Issue by precurse** [ansible/ansible#18719]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
WinRM

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Default everything

##### OS / ENVIRONMENT

Ubuntu 16.04  (ansible installed from pip)

##### SUMMARY

Anytime a connection attempt is made to a Windows host, it fails with `ssl: Failed to parse: <ipv6 address eradicated>`

##### STEPS TO REPRODUCE

Connect to any 

```
ansible windows  -m win_ping
```

##### EXPECTED RESULTS
Should connect to IPv6 the same as IPv4

##### ACTUAL RESULTS

```
fatal: [windows]: UNREACHABLE! => {
    "changed": false,
    "msg": "ssl: Failed to parse: <ipv6 address eradicated>",
    "unreachable": true
}
```
(I believe it has to do with the way it's using the IPv6 address in the https:// url..  by not including []  brackets around the address.

With ANSIBLE_DEBUG:
```
 28169 1480704112.34636: _low_level_execute_command(): executing: PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand ......
<<ipv6 address eradicated>> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO <ipv6 address eradicated>
<<ipv6 address eradicated>> WINRM CONNECT: transport=ssl endpoint=https://<ipv6 address eradicated>:5986/wsman
<<ipv6 address eradicated>> WINRM CONNECTION ERROR: Failed to parse: <ipv6 address eradicated>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/connection/winrm.py", line 154, in _winrm_connect
    self.shell_id = protocol.open_shell(codepage=65001)  # UTF-8
  File "/usr/local/lib/python2.7/dist-packages/winrm/protocol.py", line 132, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/usr/local/lib/python2.7/dist-packages/winrm/protocol.py", line 207, in send_message
    return self.transport.send_message(message)
  File "/usr/local/lib/python2.7/dist-packages/winrm/transport.py", line 170, in send_message
    prepared_request = self.session.prepare_request(request)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 357, in prepare_url
    raise InvalidURL(*e.args)
InvalidURL: Failed to parse: 
```

**Comment by precurse** [comment]
I suspect it has to do with these lines: https://github.com/ansible/ansible/blob/4ed88512e45112f9670560ac3f01707a40a7f5c5/lib/ansible/plugins/connection/winrm.py#L141-L142

It doesn't check if it's an IPv6 address before appending :port to it ..  Therefore fails when trying to connect.

**Comment by jhawkesworth** [comment]
For future reference I found some ways of checking if an address if valid ipv4 or v6 address here: http://stackoverflow.com/questions/11827961/checking-for-ip-addresses

Just wondering if using a hostname is a viable alternative?  ip addresses (v4 and v6) are for machines, hostnames are for humans.

**Comment by precurse** [comment]
That's not really an option for me..  I'm using the OpenStack inventory script and the only option of connecting to our hosts is via IPv6.  `ansible_ssh_host` is set to the IPv6 address, which is what we want since it doesn't rely on DNS. In our case we want the orchestration to rely on DNS as little as possible because we use it to setup DNS as well.

**Comment by nitzmahone** [comment]
This looks like a pywinrm bug, but I'm about to do a bunch of work in there
and kick out a new release, so I've created a tracking bug for this over
there: https://github.com/diyan/pywinrm/issues/164

**Comment by nitzmahone** [comment]
Since this bug appears to be in the pywinrm code and not Ansible's, we're going to close it here. Pywinrm should address this issue at some point.
