### ISSUE TITLE
[Feature] dns reverse lookup jinja2 filters?

### ISSUE THREAD

**Issue by juju4** [ansible/ansible#18738]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
jinja2 filters

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
wish for filters to do dns reverse lookup with filter
has been implemented by @bertvv in https://github.com/bertvv/ansible-role-bind/blob/master/filter_plugins/ipaddress.py
easy functions to help when working with dns.

Thanks

**Comment by sivel** [comment]
This functionality exists by means of a lookup plugin as documented at http://docs.ansible.com/ansible/playbooks_lookups.html#the-dns-lookup-dig

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by juju4** [comment]
Sorry, I was not suggesting to do any dig, or dns request, just reverse an ip address

example
192.168.1.0 to 0.1.168.192

and as it is mostly to create DNS server zones, you have no dns servers to requests that, especially if internal dns.

linked code is
```
def reverse_dotted_decimals(ipaddress):
    """Reverse the order of the decimals in the specified IP-address.
    E.g. "192.168.10" would become "10.168.192"
    Keyword arguments:
        ipaddress -- An IP address in dotted decimal notation
    """
    return '.'.join(ipaddress.split('.')[::-1])


def reverse_lookup_zone(ipaddress):
    """Return the notation for the reverse lookup zone for the specified
    network address.
    E.g. "192.0.2" would become "2.0.192.in-addr.arpa"
    Keyword arguments:
        ipaddress -- The network part of an IP address in dotted decimal
        notation
    """
    return reverse_dotted_decimals(ipaddress) + '.in-addr.arpa'

```

**Comment by sivel** [comment]
This is also already possible:

```
- debug: msg="{{ ('192.168.10'.split('.'))[::-1]|join('.') }}"
```

**Comment by juju4** [comment]
for ipv4, yes. can do it that way even if less readable.
for ipv6, I don't think it can be so short

example from RIPE
```
For example, the pointer domain name corresponding to the IPv6 address 2001:db8::567:89ab is b.a.9.8.7.6.5.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa., which would result in this PTR record:

b.a.9.8.7.6.5.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa. 3600 IN PTR mail.example.com.
```
https://www.ripe.net/manage-ips-and-asns/db/support/configuring-reverse-dns
https://www.sixxs.net/faq/dns/?faq=reverse

**Comment by sivel** [comment]
You may also want to have a look at the `ipaddr` filter, as it appears to be able to do this as well:

```
$ ansible all -i localhost, -c local -m debug -e ip=192.168.10 -a 'msg={{ ip|ipaddr("revdns") }}'
localhost | SUCCESS => {
    "msg": "0.10.168.192.in-addr.arpa."
}
$ ansible all -i localhost, -c local -m debug -e ip=2001:db8::567:89ab -a 'msg={{ ip|ipaddr("revdns") }}'
localhost | SUCCESS => {
    "msg": "b.a.9.8.7.6.5.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa."
}
```
http://docs.ansible.com/ansible/playbooks_filters_ipaddr.html

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by juju4** [comment]
ah, this is perfect! :+1:

**Comment by juju4** [comment]
just a precision. filter is valid for PTR pointer but not zone/subnet as it will complete a zone value in a full IP
example
10.1.0 with revdns: 0.0.1.10.in-addr.arpa. while linked filter will get 0.1.10.in-addr.arpa

for a zone, you want 0.1.10.in-addr.arpa.
for ipv4, ```{{ ip | ipaddr('revdns') | regex_replace('^[0-9]+\\.', '') }}``` will do
for ipv6, not that easy

found following code
https://github.com/Wilm0r/dnsrev/blob/master/dnsrev.py
https://gist.github.com/pklaus/2016269

**Comment by bertvv** [comment]
Here's some hairy code for the IPv6 case:

```Yaml
# testip.yml
---
- hosts: localhost
  tasks:
    - debug:
        msg: "Reverse zone {{ (item | ipaddr('revdns'))[-(9+(item|regex_replace('^.*/','')|int)//2):] }}"
      with_items:
        - '2001:db8::/48'
        - '2001:db8::/64'
```

Output:

```ShellSession
$ ansible-playbook testip.yml 
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] *****************************************************************************

TASK [debug] *********************************************************************************
ok: [localhost] => (item=2001:db8::/48) => {
    "item": "2001:db8::/48", 
    "msg": "Reverse zone 0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa."
}
ok: [localhost] => (item=2001:db8::/64) => {
    "item": "2001:db8::/64", 
    "msg": "Reverse zone 0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa."
}

PLAY RECAP ***********************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

Basically, I check how long the string containing the reverse zone name should be, according to the `/prefix` and take a substring with that length from the right of the result of the `revdns` function.
