### ISSUE TITLE
Support sudo alternatives that offer sudo-compatible interfaces

### ISSUE THREAD

**Issue by ron1** [ansible/ansible#1873]
Sudo alternatives exist that provide compatible interfaces (see http://www.sudo.ws/sudo/other.html). A DEFAULT_SUDO_EXE constant should be defined for 'sudo' that allows an alternative ANSIBLE_SUDO_EXE to be specified. This enhancement requires minor changes to both lib/ansible/constants.py and lib/ansible/utils/**init**.py.

**Comment by mpdehaan** [comment]
patches would be considered.

open bug ticket and 'fix it for me', not so much :)
