### ISSUE TITLE
Custom windows ansible module with network share path

### ISSUE THREAD

**Issue by xpicio** [ansible/ansible#18778]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

I'm not really sure but could be: lib/ansible/plugins/shell/powershell.py

##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = 
  configured module search path = ['/opt/buildAgent/work/bb630c66ced55a59/provisioning/library/']
```

##### CONFIGURATION

ANSIBLE_LIBRARY=/opt/buildAgent/work/bb630c66ced55a59/provisioning/library/

##### OS / ENVIRONMENT

Ansible running on: Linux buildagent-a 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux
Ansible managing: Windows 2012 R2 Datacenter Full and Core

##### STEPS TO REPRODUCE

printer_installation.ps1
```
#!powershell

# WANT_JSON
# POWERSHELL_COMMON

# Parse the parameters file dropped by the Ansible machinery
$params = Parse-Args $args;

# Initialize defaults for input parameters
$printName = Get-Attr $params "print_name" $false;
$serverHostName = Get-Attr $params "server_hostname" $false;

# Parse name and fail if is not provided
If ($printName -eq $false) {
        Fail-Json (New-Object psobject) "missing required argument: printName";
}

# Parse name and fail if is not provided
If ($serverHostName -eq $false) {
        Fail-Json (New-Object psobject) "missing required argument: serverHostName";
}

Get-Printer -Name $serverHostName\$printName
```

playbook
```
- hosts: remote
  tasks:
  - name: Add Printer Network Module
    printer_installation:
      print_name: 'ICT_RS_Nero'
      server_hostname: '\\srvspooler.admaiora.dom'
    tags:
      - develop
      - master
      - feature
```

##### EXPECTED RESULTS

The printer already exist on the windows server so i expect the command Get-Printer return the selected printer. Running the command directly on windows or in a powershell script copied within the server it is return correctly the printer name. I tried on the ansible module the following command:

```
Get-Printer -Name "Microsoft XPS Document Writer"
```

and it is work correctly, so it seems a problem with printers on a network share.

##### ACTUAL RESULTS

```
<172.16.221.218> WINRM RESULT u'<Response code 0, out "", err "#< CLIXML\r\n<Objs Ver">'
<172.16.221.218> WINRM STDOUT 
<172.16.221.218> WINRM STDERR #< CLIXML
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><S S="Error">Get-Printer : No MSFT_Printer objects found with property 'Name' equal to _x000D__x000A_</S><S S="Error">'\\srvspooler.admaiora.dom\ICT_RS_Nero'.  Verify the value of the property and _x000D__x000A_</S><S S="Error">retry._x000D__x000A_</S><S S="Error">At C:\Users\photosi\AppData\Local\Temp\ansible-tmp-1481043206.39-24051189442966_x000D__x000A_</S><S S="Error">1\printer_installation.ps1:263 char:1_x000D__x000A_</S><S S="Error">+ Get-Printer -Name $serverHostName\$printName_x000D__x000A_</S><S S="Error">+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_x000D__x000A_</S><S S="Error">    + CategoryInfo          : ObjectNotFound: (\\srvspooler.admaiora.dom\ICT_R _x000D__x000A_</S><S S="Error">   S_Nero:String) [Get-Printer], CimJobException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : CmdletizationQuery_NotFound_Name,Get-Printer_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Get-Printer -Name $serverHostName\$printName</AV><AI>1974627222</AI><Nil /><PI>-1</PI><PC>100</PC><T>Completed</T><SR>0</SR><SD>1/1 completed</SD></PR></MS></Obj></Objs>
<172.16.221.218> WINRM CLOSE SHELL: 082BF03D-4059-4315-A2A9-414BF8C745A7
fatal: [172.16.221.218]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "printer_installation"}, "module_stderr": "Get-Printer : No MSFT_Printer objects found with property 'Name' equal to \r\n'\\\\srvspooler.admaiora.dom\\ICT_RS_Nero'.  Verify the value of the property and \r\nretry.\r\nAt C:\\Users\\photosi\\AppData\\Local\\Temp\\ansible-tmp-1481043206.39-24051189442966\r\n1\\printer_installation.ps1:263 char:1\r\n+ Get-Printer -Name $serverHostName\\$printName\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n+ CategoryInfo          : ObjectNotFound: (\\\\srvspooler.admaiora.dom\\ICT_R \r\nS_Nero:String) [Get-Printer], CimJobException\r\n+ FullyQualifiedErrorId : CmdletizationQuery_NotFound_Name,Get-Printer\r\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by jhawkesworth** [comment]
Hi
You are very likely encountering what is known as the 'second hop' issue.  From ansible controller to windows host is one hop and from windows host to printer server is a second hop.  Usually windows does not allow a second hop like this, but you can configure authentication delegation if you are running as a domain (kerberos) user to get round this issue, by setting ansible_winrm_kerberos_delegation=yes in your windows group_vars (needs pywinrm 0.2.x).

I'm going to close this ticket as how to do things questions like this are best asked on the #ansible irc channel or on the ansible-project google group - many more people read the google group and irc channel than follow the ansible issue tracker.

Jon

**Comment by jhawkesworth** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by xpicio** [comment]
@jhawkesworth thank you very much for the tips, i am not using windows 2012 on domain context so i do not have kerberos. I did some tries but without success. I will do more tries the next days.
