### ISSUE TITLE
Ansible hangs on passwordless sudo to localhost? (devel branch only, 0.9 is okay)

### ISSUE THREAD

**Issue by fdavis** [ansible/ansible#1882]
If I run the command that hangs in a terminal, "/bin/sh -c 'sudo -k && sudo -S -p "[sudo via ansible, key=#shortened] password: " -i -u root /bin/sh -c '"'"'/usr/bin/python /home/fdavis/.ansible/tmp/ansible-#shortened/setup'"'"''"

It drops me into the python interpreter.
If you omit the "-i" flag it runs the setup module as expected.
The only differences I notice between this command and the same from 0.9 is the "-S and -i" flags

The gist has the -vvv output of the same playbook with
ansible 1.0 (devel 89eee7b868) last updated 2013/01/19 20:49:00 (GMT -700)
and
ansible 0.9 (release0.9 0115d4b442) last updated 2013/01/19 20:40:40 (GMT -700)

https://gist.github.com/4576735

**Comment by mpdehaan** [comment]
Hmm, you're the first person hanging with sudo -i.

Let's revert this commit until we can figure out why it is hanging.

**Comment by mpdehaan** [comment]
I've reverted this commit, so devel should be good to go.  Curious what happened, but thanks for the heads up.
