### ISSUE TITLE
Modules shell and command only output MODULE FAILURE on error

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#18846]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

command / shell

##### ANSIBLE VERSION

v2.2

##### CONFIGURATION

*hosts*
```ini
problemhost ansible_host=127.0.0.1 ansible_python_interpreter=/foo/bar
```

##### OS / ENVIRONMENT

Any

##### SUMMARY

The shell and command modules do not provide any indication to what the error is, it only outputs **MODULE FAILURE**

##### STEPS TO REPRODUCE

```
[dag@moria ansible.testing]$ ansible problemhost -m setup 
problemhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "/bin/sh: /foo/bar: No such file or directory\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}

[dag@moria ansible.testing]$ ansible problemhost -m command -a date
problemhost | FAILED | rc=0 >>
MODULE FAILURE
```

##### EXPECTED RESULTS

```
problemhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "/bin/sh: /foo/bar: No such file or directory\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}
```

##### ACTUAL RESULTS

```
problemhost | FAILED | rc=0 >>
MODULE FAILURE

```

**Comment by namasivayamcse** [comment]
I have face the same issue as below 

**Error**

[ansible-user@ansiblemaster linux-ping]$ ansible centos -m ping 

ansiblenode1 | FAILED! => {
    "changed": false, 
    "module_stderr": "Shared connection to ansiblenode1 closed.\r\n", 
    "module_stdout": "sudo: a password is required\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}

**Resolution:**
I have added below entry in  /etc/sudoers  on the Master node & client node.
ansible-user    ALL=(ALL)       NOPASSWD: ALL

Post addition of ansible user into the  /etc/sudoers file issue got fixed.

**Output**
[ansible-user@ansiblemaster linux-ping]$ ansible centos -m ping 
ansiblenode1 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
