### ISSUE TITLE
sudo commands fail with unreadable output with strict umask

### ISSUE THREAD

**Issue by jkleint** [ansible/ansible#189]
If I do:

```
$ ansible myhost -a "umask" -K --sudo -u $USER
```

where `$USER@myhost` has umask 0007, the sudo shell inherits this umask, and `$USER` cannot read the temp file where ansible saves its output.   The command fails with this message:

```
myhost | FAILED | rc=0 >>


stderr: [myhost] => cat: /tmp/ansible.o15113/sudo_result.56886: Permission denied
```

Currently `connection.py` does something like this to run a command:

`sudo -s`
_<types passwd>_
_<interactive root shell starts>_
`(command >temp_pre 2>/dev/null ; mv temp_pre temp) &`
_<exit root shell>_
while `temp` doesn't exist: sleep 1
`cat temp`

If the user can't read files written by root, the ansible command fails (even though the remote command does succeed).

This approach several other drawbacks: The sudo command can't use redirection itself, and if the command hangs, so will ansible.

I'm sure there were good reasons why this implementation was chosen, but is there a reason we can't shellquote the command as a parameter to `sudo -s --`?  <a href="http://stackoverflow.com/questions/2692873/quote-posix-shell-special-characters-in-python-output">People differ</a> over the best way to do this in Python, but `pipes.quote()` (undocumented) is one easy way.

**Comment by mpdehaan** [comment]
seems like you you have some idea of what you want to see here and may be talking about two different things (sudo expect handling + quoting).   How about a patch?

I'm aware of the sudo hang potential... there are some FIXMEs in connection.py about how to possibly improve this.

**Comment by mpdehaan** [comment]
We've moved the tempdirs to /var/tmp for root and the user's homedir for non-root so hopefully this resolves your issue.

Let me know if not.
