### ISSUE TITLE
Major Bug in ansible 2.2+, Condition is not evaluated 

### ISSUE THREAD

**Issue by urashidmalik** [ansible/ansible#18941]
- Bug Report

##### COMPONENT NAME
Loops, with_item and when condition

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### OS / ENVIRONMENT
MAC OSX

##### SUMMARY
Task fails in 2.20 (Used to work with 1.8,1.9,2.0) If we have a variable in with_items and a condition to check if that variable was set before

##### STEPS TO REPRODUCE

-  shell: echo "I've got '{{ item }}' and am not afraid to use it!"
    with_items:
      - '{{foo}}'
    when: foo is defined
##### EXPECTED RESULTS
task should not fail
##### ACTUAL RESULTS

fatal: [192.168.56.31]: FAILED! => {
    "failed": true, 
    "msg": "'foo' is undefined"
}

```
fatal: [192.168.56.31]: FAILED! => {
    "failed": true, 
    "msg": "'foo' is undefined"
}
```

Ideally it should not fail as i have when condition to run only when foo is defined

**Comment by krzysztof-magosa** [comment]
`when` is evaluated for each item and not once for entire set.
You can do `with_items: "{{ foo | default([]) }}"` or set `foo` to `[]` in `defaults/main.yml`.

**Comment by sivel** [comment]
In ansible 1.9 this was allowed without consequences.  In ansible 2.0 and 2.1 this would have led to a DEPRECATION message.  Ansible 2.2 removed the DEPRECATION message and made it a failure.

As mentioned `when` is evaluated for each iteration of `with_items`, not evaluated before `with_items` is attempted.

This means in 2.2 and going forward, your `with_items` statement must always evaluate.

The solution provided by @krzysztof-magosa is the recommended way of approaching this.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
