### ISSUE TITLE
ansible_service_mgr and grsecurity

### ISSUE THREAD

**Issue by reachfh** [ansible/ansible#18957]
##### ISSUE TYPE
 - Bug Report
 
##### COMPONENT NAME
ansible_service_mgr detection

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /Users/xxx/work/xxx/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
I think nothing in the configuration is relevant to this issure, but here is the ansible.cfg

[defaults]
remote_user = xxx
host_key_checking = False
inventory = inventory/
roles_path = roles.galaxy:roles
vault_password_file = vault.key

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=15m -F ssh.config -q
scp_if_ssh = True
control_path = /tmp/mux-%%r@%%h:%%p
pipelining = True

##### OS / ENVIRONMENT
Running Ansible from macOS. Managing CentOS 6.x and 7.x hosts with grsecurity patches. 

The server is running the standard kernel from hosting provider OVH, which includes the following settings:

    CONFIG_GRKERNSEC_PROC=y
    CONFIG_GRKERNSEC_PROC_USER=y

##### SUMMARY
When Ansible collects facts, it attempts to read the init system from `/proc/1/comm`
and then with `ps -p 1 -o comm|tail -n 1`. This fails for `CONFIG_GRKERNSEC_PROC_USER=y`

##### STEPS TO REPRODUCE
With the grsecurity patches configured with `CONFIG_GRKERNSEC_PROC_USER=y`, `/proc` is only readable by root, and normal users can only view their own processes. The read of `/proc/1/comm` fails with no file found, which is fine. The ps command, however, returns an "empty" result with just the header "COMMAND", causing `ansible_service_mgr` to be set to `COMMAND`. Here is an example of what ps returns for a regular user and for root. 

    $ ps -p 1 -o comm
    COMMAND

    # ps -p 1 -o comm
    COMMAND
    init

```
ansible foo-server -m setup -a 'filter=ansible_service_mgr'
```

##### EXPECTED RESULTS
`ansible_service_mgr` should be set to e.g. "systemd"

##### ACTUAL RESULTS
`ansible_service_mgr` is "COMMAND"

```
foo-server | SUCCESS => {
    "ansible_facts": {
        "ansible_service_mgr": "COMMAND"
    },
    "changed": false
}
```

**Comment by bcoca** [comment]
@reachfh do you want to resubmit/re open the PR?

**Comment by reachfh** [comment]
@bcoca Recreated the PR
