### ISSUE TITLE
postgresql_user now fails on postgresql-8.4.13

### ISSUE THREAD

**Issue by tartansandal** [ansible/ansible#1895]
Seems to be a regression between ansible-0.8 and ansible-0.9.  'rolreplication' column is not defined in the older postgresql (used in RHEL6).  See traceback below.

Sorry don't have time to figure out a patch.  Sadly have to use a local copy of the module from release-0.8 to work around this.

```
[root@dealmax-dvmh-db-04 ~]# python /tmp/ansible-1358923657.64-148571753433116/postgresql_user
Traceback (most recent call last):
  File "/tmp/ansible-1358923657.64-148571753433116/postgresql_user", line 1069, in <module>
    main()
  File "/tmp/ansible-1358923657.64-148571753433116/postgresql_user", line 402, in main
    changed = user_alter(cursor, user, password, role_attr_flags)
  File "/tmp/ansible-1358923657.64-148571753433116/postgresql_user", line 156, in user_alter
    cursor.execute(select, {"columns": columns, "user": user})
psycopg2.ProgrammingError: column "rolreplication" does not exist
LINE 1: ...,rolinherit,rolcreaterole,rolcreatedb,rolcanlogin,rolreplica...
```

**Comment by dhozac** [comment]
This has been fixed on devel for quite some time.

**Comment by tartansandal** [comment]
Sorry for that. My Git Fu is not as good as it could be :-(

Since this was a regression, breaking playbooks that worked in 0.8, is there any scope for back-porting the fix into the 0.9 release branch so it can be picked up by distributions?  Not sure what the project policy is around this.

**Comment by sfromm** [comment]
I'm not sure what we would tag as 0.9.1.  The current plan is to release 1.0 2/1/2013.  Would that work?

**Comment by tartansandal** [comment]
Was thinking we could just take the release-0.9 branch,  cherry-pick commit 11b64314df544f38dcf015cfba60b40ae02c26b8 from devel, and tag that as 0.9.1.  But if the new release is only 9 days away, this 'busy-work' is not likely to be picked up by distributions in time. So i suggest we just let it be :-)

If this was done around the time of the above commit (Dec 5 2012) it might have been worth it. As ansible usage grows, back-porting fixes to regressions will have a greater impact on user experience. Note: this is **not** a criticism. I'm new to the project and am just exploring the project processes and culture.
