### ISSUE TITLE
Allow wildcards in creates= directives

### ISSUE THREAD

**Issue by marktheunissen** [ansible/ansible#1904]
It would be great if the creates= option allowed wildcards, for example:

`creates=/var/lib/gems/*/specifications/compass-aurora-*.gemspec`
## Use case

Sometimes files have version numbers in them, and it sucks to hardcode the version in the playbook. e.g.:

`creates=/var/lib/gems/1.8/specifications/compass-aurora-1.1.1.gemspec`

could rather become:

`creates=/var/lib/gems/*/specifications/compass-aurora-*.gemspec`
## Why?

When installing software through a package manager that Ansible doesn't support, for example Ruby Gems, it would be nice to re-run the playbook without waiting while it re-downloads and does a bunch of slow things as part of the 'command' action. For example, it would be cool if I could do:

``` yml
- name: Install Aurora
  action: command gem install compass-aurora creates=/var/lib/gems/*/specifications/compass-aurora-*.gemspec
```

**Comment by dhozac** [comment]
Sounds like a good reason to write a gem module to me... But I see no reason to not support it, so PRs accepted!

**Comment by marktheunissen** [comment]
I seem to remember Michael rejecting the idea of having modules for each of the various package managers, like npm, rubygems, etc.

**Comment by sfromm** [comment]
Could you also look up the version that would be installed via `gem list <pkg> --remote` or `gem spec <pkg> --remote` and then register the result?  You would have to pipe the result from either command to clean up the output.  

This could present a bit of a problem when there is a discrepancy between the locally installed version and a newer one available from upstream.  Another option would be to create a variable that defines the specific version of the gem you want installed.

**Comment by sfromm** [comment]
On a side note, mpdehaan recently expressed interest on the mailing list for a gem module.  It may be accepted.

**Comment by mpdehaan** [comment]
The various ruby modules would in fact be accepted.

I think it's much better to not manage packages that way, but too many
people want to do it :)

**Comment by mpdehaan** [comment]
merging with #2136

**Comment by micw** [comment]
Hi,

I would like to reopen this issue. The reason is that installing a package is not the only use case for this. There are endless examples where the exact path of the created resource is not known. And to create a test for each that registers something bloats up the playbook a lot.

More use cases:
- install a vagrant plugin using the command "vagrant plugin"
- install an eclipse plugin
- download some MYAPP-latest.tgz and extract it (where the version will be within the root path in the tar)

**Comment by jagibson** [comment]
I agree with @micw .  Trying to install a vagrant plugin myself and this feature would be good to have.

**Comment by gildegoma** [comment]
Hint for interested people: https://github.com/ansible/ansible-modules-core/pull/513

**Comment by lowks** [comment]
This would be create to check for `chkconfig` items too.
