### ISSUE TITLE
MODULE FAILURE: async_wrapper.py: python: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by ask0n** [ansible/ansible#19065]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

async_wrapper

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### CONFIGURATION
defaults]
gathering = smart
fact_caching = jsonfile
fact_caching_connection = ./fact_cache
fact_caching_timeout = 7200
host_key_checking = False
timeout = 300
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S
nocows = 1
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=300s -o PreferredAuthentications=publickey,keyboard-interactive -F config
[accelerate]
[selinux]
[colors]

##### OS / ENVIRONMENT
macos 10.12.1 - client
centos7 - server

##### SUMMARY
Any task which uses async+poll failed. Here is example of tasks:

##### STEPS TO REPRODUCE

```
- name: Test async 1
  command: date >> /tmp/date
  async: 1
  poll: 0

- name: Test async 2
  command: sleep 10 & date >> /tmp/date
  async: 1
  poll: 0
```

##### EXPECTED RESULTS

Execute task and continue playbook.

##### ACTUAL RESULTS

If I use ANSIBLE_KEEP_REMOTE_FILES=1 and run python script manually on remote, i get this:
 \# /bin/sh /home/centos/.ansible/tmp/ansible-tmp-1481280951.46-49191328806104/async_wrapper.py
/home/centos/.ansible/tmp/ansible-tmp-1481280951.46-49191328806104/async_wrapper.py: line 23: try:: command not found
/home/centos/.ansible/tmp/ansible-tmp-1481280951.46-49191328806104/async_wrapper.py: line 24: import: command not found
/home/centos/.ansible/tmp/ansible-tmp-1481280951.46-49191328806104/async_wrapper.py: line 25: except: command not found
/home/centos/.ansible/tmp/ansible-tmp-1481280951.46-49191328806104/async_wrapper.py: line 26: import: command not found
/home/centos/.ansible/tmp/ansible-tmp-1481280951.46-49191328806104/async_wrapper.py: line 27: import: command not found
/home/centos/.ansible/tmp/ansible-tmp-1481280951.46-49191328806104/async_wrapper.py: line 28: import: command not found
/home/centos/.ansible/tmp/ansible-tmp-1481280951.46-49191328806104/async_wrapper.py: line 29: import: command not found
/home/centos/.ansible/tmp/ansible-tmp-1481280951.46-49191328806104/async_wrapper.py: line 30: import: command not found
/home/centos/.ansible/tmp/ansible-tmp-1481280951.46-49191328806104/async_wrapper.py: line 31: import: command not found
/home/centos/.ansible/tmp/ansible-tmp-1481280951.46-49191328806104/async_wrapper.py: line 32: import: command not found
/home/centos/.ansible/tmp/ansible-tmp-1481280951.46-49191328806104/async_wrapper.py: line 33: import: command not found
/home/centos/.ansible/tmp/ansible-tmp-1481280951.46-49191328806104/async_wrapper.py: line 34: import: command not found
/home/centos/.ansible/tmp/ansible-tmp-1481280951.46-49191328806104/async_wrapper.py: line 36: PY3: command not found
/home/centos/.ansible/tmp/ansible-tmp-1481280951.46-49191328806104/async_wrapper.py: line 38: syntax error near unexpected token `'ansible-%s''
/home/centos/.ansible/tmp/ansible-tmp-1481280951.46-49191328806104/async_wrapper.py: line 38: `syslog.openlog('ansible-%s' % os.path.basename(__file__))'

If i run it just from shell, I got this:
 /home/centos/.ansible/tmp/ansible-tmp-1481280951.46-49191328806104/async_wrapper.py
bash: /home/centos/.ansible/tmp/ansible-tmp-1481280951.46-49191328806104/async_wrapper.py: python: bad interpreter: No such file or directory

```
TASK [test-role : Test async 1] ****************************************
task path: /Users/wrk/ansible/roles/test-role/tasks/main.yml:8
fatal: [host-1-a]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 54.93.65.112 closed.\r\n", "module_stdout": "/bin/sh: /home/centos/.ansible/tmp/ansible-tmp-1481280807.76-271298111309703/async_wrapper.py: python: bad interpreter: No such file or directory\r\n", "msg": "MODULE FAILURE"}
```

**Comment by abadger** [comment]
I believe this is fixed by:
* https://github.com/ansible/ansible/commit/d61b2ed0a3f7c8647fbf0b912c66711e95fc9127   in devel
* https://github.com/ansible/ansible/commit/acad2ba24691d9a145c912dc97a54cd8c2b873eb in stable-2.2 branch.  Only cherry-picked a few days ago.

As a workaround, does specifying a full path to the python interpreter via ansible_python_interpreter work?

(like ansible_python_interpreter=/usr/bin/python )? 

needs_info

**Comment by ask0n** [comment]
Unfortunately no. Path to python interpreter not helps. Used groups file to assign it within [hosts_group:vars] section but all created python playbooks still using "#!python".
I'm using dynamic inventory, maybe this could be a case?
Weird that all other tasks are run normally, so ansible gets path correctly. I faced with python path error earlier on freebsd servers - they were unable to run tasks at all.

UPDATE:
Setting interpreter via playbook vars works.
  vars:
   ansible_python_interpreter: "/usr/bin/env python"

**Comment by abadger** [comment]
Cool.  Ther's both a workaround and a fix in the tree so I'll close this now.
