### ISSUE TITLE
Wording of "Conditional check failed"

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#19068]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
when

##### ANSIBLE VERSION
```
2.2.0
```

##### SUMMARY
I've never like the wording of "Contitional check failed" when a task is skipped using `when`. The conditional check doesn't actually fail, it equals to false. I propose that we change the wording to 
"skip_reason": "Conditional check equals false"
or similar.

**Comment by bcoca** [comment]
fixed via e6f92bc3a937d8ca9593f0c973ff491779b24c93

**Comment by ElijahLynn** [comment]
Thank you! Just spent a decent amount of time troubleshooting why I had a failure. Had no idea it was just a "when" issue.
