### ISSUE TITLE
Including templates doesn't seem to work

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#1908]
I've written a gist to allow people to replicate this
https://gist.github.com/4618154

Basically, if you run ansible against a template that includes a second template, effectively you get a KeyError from lib/ansible/utils/template.py. 

This seems to be caused by the conversion of the _jinja2_vars class to a dict. The KeyError is due to the 0 key being missing, but I can't see why 

parent = dict(parent) 

where parent is a _jinja2_var would try to access the object using parent[0]. 

I'm not sure what the _jinja2_var class provides over a dict, so I'm not really sure where to start addressing this.

**Comment by mpdehaan** [comment]
Yeah, I'm not an expert on Jinja2 internals much either.

Did the 3rd item in the exist work as a workaround?  Obviously the first
thing working is preferable.

**Comment by willthames** [comment]
This isn't so much jinja internals - _jinja2_vars is a class defined in ansible/utils/template.py. However, the cast of _jinja2_vars to dict is done by jinja2 to copy the vars data structure. If _jinja2_vars could be made more dict like I suspect the cast would work fine. 

I assume 'exist' is an autocorrect for gist - the third item demonstrates that trying to run template_from_file on a template that includes another template does not work. 

I'll do some more digging on this and see why _jinja2_vars was created in the first place (assuming the git log is informative)

**Comment by willthames** [comment]
Looks like this bit of code came from commit 25a8787e95 by @dhozac. 

Given that Daniel hopefully understands this bit of code far better than I do, hopefully he'll be able to work out what's going wrong. 

I'm happy to submit a pull request that shows the failing tests, but when I added a test, nosetests -v hung silently (hence the reason for the gist as the easiest way to document the issue in a reproducible way)

**Comment by dhozac** [comment]
More Jinja2 hating lazy resolvers... Could you try it with https://github.com/dhozac/ansible/commit/c0aba4e255e3c2ea1c3230f3078307241456347b and seeing if that works for you? It passes my tests.

**Comment by willthames** [comment]
Certainly works for my use case. Thanks! I look forward to this being merged into devel.

**Comment by mpdehaan** [comment]
+1 to merging
