### ISSUE TITLE
VARIABLE IS NOT DEFINED from referenced variable with value

### ISSUE THREAD

**Issue by bamb00** [ansible/ansible#19135]
ISSUE TYPE: Bug Report

COMPONENT NAME: Referencing from ecs_taskdefinition module

ANSIBLE VERSION: 2.1.1.0

CONFIGURATION: Nothing special

OS / ENVIRONMENT: Nothing special

SUMMARY: task_output result from a debug statement,

    "task_output": {
         "changed": false, 
         "taskdefinition": {
             "containerDefinitions": [
                 {
                     "cpu": 512, 
                     "environment": [], 
                     "essential": true, 
                     "image": "xxxxxxxxxxxxx.dkr.ecr.xx-xxxx-x.amazonaws.com/xxxx_xxx_framework:v0.1.4.58.xxxxxxxxx", 
                     "logConfiguration": {
                         "logDriver": "awslogs", 
                         "options": {
                             "awslogs-group": "ContainerLogsGroup", 
                             "awslogs-region": "xx-xxxx-x", 
                             "awslogs-stream-prefix": "xxxxt-xxxframework"
                         }
                     }, 
                     "memory": 1200, 
                     "mountPoints": [], 
                     "name": "xxxx-webframework", 
                     "portMappings": [
                         {
                             "containerPort": 3000, 
                             "hostPort": 3000, 
                             "protocol": "tcp"
                         }
                     ], 
                     "volumesFrom": []
                 }
             ], 
             "family": "xxxx-webframework", 

STEPS TO REPRODUCE:
"- debug: var=task_output.taskdefinition.containerDefinitions[0].logConfiguration.options.awslogs-group"

EXPECTED RESULTS:
**_ContainerLogsGroup_**

ACTUAL RESULTS:
task_output.taskdefinition.containerDefinitions[0].logConfiguration.options.awslogs-group: **"VARIABLE IS NOT DEFINED!"**

NOTE:
The reference seems to be ok up to 'options',
 ok: [localhost] => {
     "task_output.taskdefinition.containerDefinitions[0].logConfiguration.**options**": {
         "awslogs-group": "ContainerLogsGroup", 
         "awslogs-region": "xx-xxxx-x", 
         "awslogs-stream-prefix": "xxxx-webframework"
     }
 }

**Comment by kkarimi** [comment]
This is not a bug, it happens because "awslogs-group" variable has a dash in the name which ansible will not handle (see e.g. #3907) 

If you do have [jq](https://stedolan.github.io/jq/) installed, you can use it to get the value with a task like this:

    - shell: "aws ecs describe-task-definition --task-definition your_task_definition:task_revision | jq '.taskDefinition.containerDefinitions[0].logConfiguration.options.\"awslogs-group\"'"

**Comment by bamb00** [comment]
Hi, what is jq?

**Comment by kkarimi** [comment]
@bamb00 I updated it with a link, it's a JSON processor that will help to process the output from the task

**Comment by bamb00** [comment]
Is the variable with dash in the name going to be change in the future or in the works? Thanks.

**Comment by bamb00** [comment]
I wonder if I can use awk or sed to retrieve the awslogs-group instead of jq.

**Comment by kkarimi** [comment]
@bamb00 you can use whatever tool you like
