### ISSUE TITLE
when leaving dest= off the template module you get a python traceback

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1918]
It should give you a nice error that dest is required.

**Comment by mpdehaan** [comment]
you leave me no fun, you know that, right?  :)

thank you

**Comment by dhozac** [comment]
Hehe, sorry. It was a "huh? I _know_ that code is there" thing that I couldn't help but look in to...

**Comment by mpdehaan** [comment]
Nah, I appreciate it :)   You are just too quick!

I had thought it was there too.
