### ISSUE TITLE
if you get a python traceback while processing a yml file (or template), show what file you are in

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1919]
Ex:

if I do something that causes a traceback in ntp.yml, tell me I was in ntp.yml at the time

handlers will also need to do this.

**Comment by mpdehaan** [comment]
probably workable via passing something like a "file_context" variable to runner, default to None for /usr/bin/ansible

**Comment by dhozac** [comment]
I was thinking something along the lines of catching the exception and annotating it at whatever level knows about the line number. Not sure how well that would cover all the cases though.

**Comment by mpdehaan** [comment]
Not sure.  FWIW, I'm going to start hacking on some bits again.   I can take this, if we do it the previous way I can probably keep the whole call chain of files.

**Comment by mpdehaan** [comment]
closing as this is somewhat complex as it would imply pinning the file context to every object created from the file.

I'm going to suspect we don't go here.
