### ISSUE TITLE
Enable custom appending to PYTHONPATH via host vars

### ISSUE THREAD

**Issue by darkone23** [ansible/ansible#1920]
Not all environments that need remote automation have sudo access.

A large amount of the built-in modules don't require root access to use, but there are many systems where they require root access to get the environment in a state where they can run (specifically for people like me stuck on python 2.4). 

The canonical wisdom for coping with 2.4 is to use the raw module (without python dependencies) to install python simplejson from a package manager, however this assumes sudo rights.

I can easily pull down the python simplejson python package and add it to any arbitrary users PYTHONPATH to satisfy the dependency, but while there are options such as ansible_python_interpreter to use alternative python binaries, there is no way to append custom paths to a child nodes PYTHONPATH in order to ensure certain libraries are available at runtime.

I propose a host var like "ansible_python_paths=/path1:/path2" to append /path1 and /path2 to sys.path before executing python modules remotely.

Thank you

**Comment by dhozac** [comment]
This is what ansible_python_interpreter lets you do. Arbitrary python paths really isn't common enough to warrant the added complexity.

**Comment by mpdehaan** [comment]
Additionally, command or shell are available.

Also the pip module happens to support virtualenv.
