### ISSUE TITLE
Error using fetch module on windows

### ISSUE THREAD

**Issue by orgito** [ansible/ansible#19237]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
  - fetch module

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /home/renato/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```
[defaults]
inventory = ~/ansible/hosts
host_key_checking = False
remote_user = root
forks = 25
roles_path = ~/ansible/roles
gathering = smart
fact_caching = jsonfile
fact_caching_connection = /tmp/ansiblefactscache
fact_caching_timeout = 86100
vault_password_file = ~/.vault-passwd.sh

[ssh_connection]
ssh_args = -C -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes
control_path = %(directory)s/ansible-ssh-%%C
pipelining = True
```

##### OS / ENVIRONMENT

My contron station is Fedora 25 and the Windows host is Windows Server 2008 R2 Enterprise.

##### SUMMARY

I receive an error when trying to fetch a file from a Windows server using the fetch module. The error occur if the file is bigger than a few megabytes.

##### STEPS TO REPRODUCE

Use the fetch module to transfer a file from windows
```
ansible winserver -m fetch -a 'src="d:/spectrum/SS-DB-Backup/db_20161209_2300.SSdb.gz" dest=/tmp/ flat=yes  validate_checksum=no become=false' -vv
```
The error also occurs when using playbooks.

##### EXPECTED RESULTS
The file been transfered without errors

##### ACTUAL RESULTS
The transfer fails

```
ansible winserver -m fetch -a 'src="d:/spectrum/SS-DB-Backup/db_20161209_2300.SSdb.gz" dest=/tmp/ flat=yes  validate_checksum=no become=false' -vv
Using /home/renato/.ansible.cfg as config file
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 410, in fetch_file
    raise IOError(to_native(result.std_err))
IOError: Exception of type 'System.OutOfMemoryException' was thrown.

Process is terminated due to StackOverflowException.

brvix5valenm005 | FAILED! => {
    "failed": true, 
    "msg": "failed to transfer file to \"/tmp/db_20161209_2300.SSdb.gz\""
}

```

```
ansible winserver -m fetch -a 'src="d:/spectrum/SS-DB-Backup/db_20161209_2300.SSdb.gz" dest=/tmp/ flat=yes  validate_checksum=no become=false' -vv
Using /home/renato/.ansible.cfg as config file
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 410, in fetch_file
    raise IOError(to_native(result.std_err))
IOError: 
Process is terminated due to StackOverflowException.

brvix5valenm005 | FAILED! => {
    "failed": true, 
    "msg": "failed to transfer file to \"/tmp/db_20161209_2300.SSdb.gz\""
}
```

Notice that the error change from the first and second execution of the same command.

The file has 8MB. On each attempt it transfer from 2MB to 3.5MB, but never the whole file. It works with smaller files.

**Comment by jhawkesworth** [comment]
Hello

please advise

Is this  http://support.microsoft.com/kb/2842230 hotfix installed as described here: http://docs.ansible.com/ansible/intro_windows.html#windows-system-prep ?
which version of pywinrm do you have installed?

needs_info

**Comment by orgito** [comment]
I had not applied the hotfix. After applying it I can now fetch the 8MB file. I further tested by trying to fetch a 4GB file. It always trows the error bellow after fetching 44MB. I have plenty of space in the /tmp partition.

My pywinrm version is 0.2.1

```
$ ansible winserver -vv -m fetch -a "src=d:/spectrum/SS-DB-Backup/db_20161212_2300.DDMDb.tgz dest=/tmp/ flat=yes validate_checksum=no"
Using /home/renato/.ansible.cfg as config file
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 408, in fetch_file
    result = self._winrm_exec(cmd_parts[0], cmd_parts[1:])
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 201, in _winrm_exec
    command_id = self.protocol.run_command(self.shell_id, to_bytes(command), map(to_bytes, args), console_mode_stdin=(stdin_iterator is None))
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 276, in run_command
    res = self.send_message(xmltodict.unparse(req))
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 207, in send_message
    return self.transport.send_message(message)
  File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 173, in send_message
    response = self.session.send(prepared_request, timeout=self.read_timeout_sec)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='142.40.22.15', port=5986): Read timed out. (read timeout=30)
winserver | FAILED! => {
    "failed": true, 
    "msg": "failed to transfer file to \"/tmp/db_20161212_2300.DDMDb.tgz\""
}

```

**Comment by jhawkesworth** [comment]
I suspect you are probably hitting one of the winrm quota limits, or perhaps a communications timeout.
You might be able to change winrm settings to increase the timeout, but I think you are still unlikely to be able to transfer a 4gb file using fetch.

I haven't tried fetching large files like this, but I suspect it might be slow due to the overhead caused by encoding file contents and sending over the winrm web service interface.  I did some testing of win_copy (which transfers files the other way) and found it was slower for large files (250mb) than reversing the operation and collecting the file via win_get_url.

As a workaround I suggest setting up some kind of service on your windows host which is better suited to transferring large files and using that instead of fetch.  What you use will depend on your environment but you might be able to run a web server on your windows machine and transfer the file back to your ansible controller using http://docs.ansible.com/ansible/get_url_module.html

**Comment by orgito** [comment]
Thank you. I guess I'll just restrict using fetch from small text files on windows.

**Comment by ajit2678** [comment]
[WARNING]: FATAL ERROR DURING FILE TRANSFER: Traceback (most recent call last):   File "/usr/lib/python2.7/site-
packages/ansible/plugins/connection/winrm.py", line 276, in _winrm_exec     self._winrm_send_input(self.protocol, self.shell_id, command_id, data,
eof=is_last)   File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 256, in _winrm_send_input
protocol.send_message(xmltodict.unparse(rq))   File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 256, in send_message     raise
WinRMOperationTimeoutError() WinRMOperationTimeoutError


192.168.9.145 | FAILED! => {
    "msg": "winrm send_input failed"
}
