### ISSUE TITLE
Playbook not running on 2.2.0.0

### ISSUE THREAD

**Issue by ajouve** [ansible/ansible#19246]
I just passed to ansible 2.2.0.0 and nothing is executed, this is an example playbook:

    ---
    - name: Deploy
      hosts: application
      become: no
    
      vars:
        application_name: service-user
    
      roles:
        - { role: docker }

I run

    ansible-playbook service-contact.yml -i inventory/staging --extra-vars docker_tag=12 -v

And the output is 

    No config file found; using defaults
    
    PLAY RECAP *********************************************************************

before updating I had (2.1.1.0)

    PLAY [Deploy] ******************************************************************
    
    TASK [setup] *******************************************************************
    ok: [staging.com]
    
    TASK [docker : Stop old container] *********************************************
    changed: [staging.com]
    
    TASK [docker : Remove old container] *******************************************
    changed: [staging.com]
    
    TASK [docker : Start new container] ********************************************
    changed: [staging.com]
    
    TASK [docker : Run commands] ***************************************************
    skipping: [staging.com]
    
    PLAY RECAP *********************************************************************
    staging.com          : ok=4    changed=3    unreachable=0    failed=0

**Comment by thaumos** [comment]
Hi!

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!
