### ISSUE TITLE
When parameter uses no_log=True, the content of parameter obfuscate also other paramter values

### ISSUE THREAD

**Issue by machacekondra** [ansible/ansible#19278]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

no_log

##### ANSIBLE VERSION

```
ansible 2.2
```

##### SUMMARY

When there is a module which accept some parameter, which has set `no_log=True` and we provide a value for this parameter, then this value is replaced with *** also for other parameters, for example let's say we have a playbook like this:

```yaml
my_module:
  url: myurl.com
  user: admin
  password: admin
```

If the password in the module is defined as `no_log=True`, then the output of this task will be:

```json
changed: [localhost] => {
    "ansible_facts": {
        "ovirt_auth": {
            "url": "myurl.com"
        }
    }, 
    "invocation": {
        "module_args": {
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "username": "********"
        }, 
        "module_name": "ovirt_auth"
    }
}
```

As you can see the `username` parameter contains `********`, but there is no reason to obfuscate then, and it can actually cause issuess, if the username should be reused.

**Comment by machacekondra** [comment]
@jniederm

**Comment by bcoca** [comment]
This is a known limitation of no_log, we obscure all matching strings in the return as module can insert that data anywhere.

**Comment by Akasurde** [comment]
For record - 

```
# ansible -m demo -a "state=present password='password' passwordfile=/etc/hosts"  localhost
 [WARNING]: provided hosts list is empty, only localhost is available

localhost | FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "parameters are mutually exclusive: ['********', '********file']"
}
```

**Comment by bcoca** [comment]
closing as per above
