### ISSUE TITLE
better proxy control

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1929]
I want to be able to do this:

```
# in vars somewhere
proxy_string="http_proxy=http://blarg"

# in a task
 - name: foo
   action: bar
   env: $proxy_string
```

as I want to sometimes talk to proxies and sometimes not.

This would help all commands that can use the environment.  I think pip does not, so we would have to teach pip to take an additional "options" string of some kind.

**Comment by mpdehaan** [comment]
alternative here, perhaps better, is to standardize the "grab file to disk or memory" code and make it support proxies, then make get_url use this common code.  As such, it would also support auth.  So fix get_url first and then move it into common, and then make other modules (like apt_key) support it so they can use a proxy parameter if one exists.

**Comment by fgimian** [comment]
Hey there guys, firstly, GREAT work on Ansible!

I found this post while searching for a solution to the same problem.

Unfortunately, in many corporate environments (like ours) everything is behind a proxy.  This little omission unfortunately means that I won't be able to use Ansible (which I love) on my current project.

Just a little note, exporting http_proxy here does appear to be picked up by pip, although there's also the --proxy option which can be used.

Thanks heaps and keep up the great work!
Fotis

**Comment by mpdehaan** [comment]
Agree.

Yeah so for now it is pretty easy to hack the connection module to add the
proxy environment variables before the command -- that will get you running
ASAP.

I'll add in some things to make this more doable without that kind of hack.

Glad pip is picking things up now.

Should be something we can get to this week.

**Comment by fgimian** [comment]
Thanks a lot mate.  No hurry, take your time.  I'll come back to Ansible on the next project anyway :)

All the best
Fotis

**Comment by mpdehaan** [comment]
Ok everyone, it's all implemented now, and you have really flexible control over which tasks use what environment variables.

Take a look and also see my more in-depth explanation on the mailing list.

https://github.com/ansible/ansible/blob/devel/examples/playbooks/environment.yml

**Comment by fgimian** [comment]
Thank you so much for implementing this! :)

**Comment by mpdehaan** [comment]
You are welcome!
