### ISSUE TITLE
upgrade the git module?

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#193]
Someone who does a lot of deployments from git may wish to upgrade the git module to make it do more tricks.  What is there now is definitely functional, but also rather basic.

**Comment by sfromm** [comment]
A couple thoughts:
1. If doing a pull, do a git reset --hard HEAD before doing pull.
2. Offer option "--ff" or "--no-ff" to handle potential conflict scenarios.

**Comment by mpdehaan** [comment]
yep.

**Comment by sfromm** [comment]
And another one: git clean -d -f. 

Also, --ff-only may be better than --ff and --no-ff:

```
       Refuse to merge and exit with a non-zero status unless the current
       HEAD is already up-to-date or the merge can be resolved as a
       fast-forward.
```

We could default to --ff-only.  If it were an option, it would only be boolean.

**Comment by mpdehaan** [comment]
closing per merged PR
