### ISSUE TITLE
standarize apt_key module

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1931]
Some things noticed when testing today.

This module should be using module.run_command everywhere, and using module.exit_json/fail_json at point of desired exit (not later) to simplify control flow.

Some useful data like output and error handling are hidden in traceback code, whereas if we have stderr/stdout, we should almost always return it on failure.

We should also consider moving the get_url base code into module common so we can share between modules.

**Comment by sfromm** [comment]
Would this be a new feature?  Or something you want to land before 1.0?

**Comment by mpdehaan** [comment]
I am fixing a lot of things that I consider bug level with it ATM.

working on it now.  and also making it not require a url but also take an embedded key.

**Comment by mpdehaan** [comment]
so yes, part of 1.0

**Comment by mpdehaan** [comment]
get_url parts are probably 1.1

**Comment by sfromm** [comment]
Okay, I was going to tackle that but it looks like you've got it covered.
 :-)

On Mon, Jan 28, 2013 at 10:10 AM, Michael DeHaan
notifications@github.comwrote:

> I am fixing a lot of things that I consider bug level with it ATM.
> 
> working on it now. and also making it not require a url but also take an
> embedded key.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/1931#issuecomment-12795246.

## 

Stephen Fromm

**Comment by mpdehaan** [comment]
done for 1.0
