### ISSUE TITLE
sudo yum install not working with ansible

### ISSUE THREAD

**Issue by ripun** [ansible/ansible#19338]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
yum.py
command.py

##### ANSIBLE VERSION
ansible 2.1.2.0
  config file = /users/xpiwrk1/ansibleWork/rachel/acd/ansible.cfg
  configured module search path = Default w/o overrides

##### CONFIGURATION
No

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.1 (Maipo)

##### SUMMARY
I have local yum repository setup on my virtual machine
I have added below required file in /etc/sudoers.d/
I want to install rpm packages with linux user which has privilege to run yum command in sudo mode 
i.e sudo yum install works 
I want to install rpm packages using ansible 
_
```
> cat /etc/sudoers.d/ansi
> ### AVM ###
>  Cmnd_Alias CESYUM = /bin/yum install CES-flatbuffers_rpm-1
>  Cmnd_Alias SYSC = /usr/bin/systemctl restart ntpd
>  ALL ALL = NOPASSWD: CESYUM,SYSC
>  ### END AVM ###
```
_

i can do from my non-root user below:
working command :  ```sudo yum install CES-flatbuffers_rpm-1```
command not working : ```sudo -u username  sudo yum install CES-flatbuffers_rpm-1```

so when run our playbook which installs rpm  , we get below error
```
TASK [extract_rpm : install the specified version of the RPM of the current fu]
failed: [imdg_1] (item={'value': {u'version': u'10.1.0.T15-8_1', u'name': u'CES-flatbuffers_rpm-1'}, 'key': u'imdg'}) => {"failed": true, "item": {"key": "imdg", "value": {"name": "CES-flatbuffers_rpm-1", "version": "10.1.0.T15-8_1"}}, "module_stderr": "", "module_stdout": "**sudo: a password is required**\r\n", "msg": "MODULE FAILURE"}
```

##### STEPS TO REPRODUCE
1. create file  for command like  yum install <packagename> in /etc/sudoers.d/ as shown above
2. then with any non root user try to run below playbook 
3. it is expected that package should get installed 
4. however package does not get installed and ansible expects entry of running user in sudoers list , that is it looks like ansible does "sudo -u username  sudo yum install package name" 

Playbook as part of roles:
```
# File name: rols/env_init/tasks/main.yml
# The main role to create work accout directories and environment variables file.
# Print debug info.
- debug: msg="installing RPMs= {{ rpm_packages }}"

#- name: become root user
#  become: true

- name: install the specified version of the RPM of the current fu
  yum:
    name: "{{ item.value.name }}-{{ item.value.version }}"
    state: latest
  become: true
  with_dict: "{{ rpm_packages }}"
```

##### EXPECTED RESULTS
it is expected that package should get installed  , since on localhost "sudo yum install <packagename> " works fine 
I think Ansible works like below; because it works on ssh and it expects user to have sudo privilege 
sudo -u username sudo yum install CES-flatbuffers_rpm-1

##### ACTUAL RESULTS
```
failed: [imdg_1] (item={'value': {u'version': u'10.1.0.T15-8_1', u'name': u'CES-flatbuffers_rpm-1'}, 'key': u'imdg'}) => {"failed": true, "item": {"key": "imdg", "value": {"name": "CES-flatbuffers_rpm-1", "version": "10.1.0.T15-8_1"}}, "module_stderr": "", "module_stdout": "sudo: a password is required\r\n", "msg": "MODULE FAILURE"}
```

**Comment by dagwieers** [comment]
Your output is completely screwed because you did not paste the output of commands inside ``` tripple-quotes ```. Please fix that.

Additionally, you did not seem to have used the -K option, which is required if you need to pass a sudo password to sudo. The output clearly indicates *"sudo: a password is required"*, so yes, you need to supply a password using -K...

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

In any case, you are using specific sudoers commands which is not supported by ansible.
http://docs.ansible.com/ansible/become.html#can-t-limit-escalation-to-certain-commands

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
