### ISSUE TITLE
var_prompt throws exception with non ascii chars in prompt and with private: yes

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/ansible#19340]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
[root@localhost ansible_test]# ansible --version
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Tried it on:
RHEL7
CentOS 7
Ubuntu 14
Fedora 23

##### SUMMARY
In var_prompt if we use non ascii characters from prompt and set private as yes it throws the following error

ERROR! Unexpected Exception: 'ascii' codec can't encode character u'\xe9' in position 40: ordinal not in range(128)

If we set private: no it works
##### STEPS TO REPRODUCE

1.) Create a playbook with var_prompts
2.) For the prompt use any non ascii chars and set private: yes

```
- hosts: localhost

  vars_prompt:
    - name: "name"
      prompt: "Mot de passe pour la base (utilisateur défini par bdd_user)?"
      private: yes

```

##### EXPECTED RESULTS
It should work

##### ACTUAL RESULTS

It gives the following traceback

```
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 103, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 156, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 119, in run
    play.vars[vname] = display.do_var_prompt(vname, private, prompt, encrypt, confirm, salt_size, salt, default)
  File "/usr/lib/python2.7/site-packages/ansible/utils/display.py", line 302, in do_var_prompt
    result = do_prompt(msg, private)
  File "/usr/lib/python2.7/site-packages/ansible/utils/display.py", line 276, in prompt
    return getpass.getpass(msg)
  File "/usr/lib64/python2.7/getpass.py", line 71, in unix_getpass
    passwd = _raw_input(prompt, stream, input=input)
  File "/usr/lib64/python2.7/getpass.py", line 128, in _raw_input
    prompt = str(prompt)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 40: ordinal not in range(128)
```

**Comment by Akasurde** [comment]
@jainnikhil30 Could you please re-try with latest version of Ansible and let us know if it works for you ?

needs_info

**Comment by jainnikhil30** [comment]
@Akasurde 
I tested it with 2.4.2 and I am not getting the error. Looks like its fixed in the latest version ?

**Comment by Akasurde** [comment]
@jainnikhil30 Cool. 
Closing this issue as per [comment](https://github.com/ansible/ansible/issues/19340#issuecomment-355887920). If issue persists, please feel free to re-open.
