### ISSUE TITLE
yum module reporting 'up to date' although the package is not installed.

### ISSUE THREAD

**Issue by dstoflet** [ansible/ansible#1935]
$ ansible --version
ansible 1.0

RHEL: Red Hat Enterprise Linux Server release 6.3 (Santiago)
$ uname -r
2.6.32-220.4.2.el6.x86_64

Trying to install a rpm using yum and it returning the below although the rpm is not installed on that host : 
g4t3773g | success >> {
    "changed": false,
    "msg": "",
    "rc": 0,
    "results": [
        "All packages providing monit are up to date"
    ]
}

[stoflet@g2t1119g wildcat]$ ansible g4t3773g -s -m yum -a "name=monit enablerepo=RedHat-6Server-x86_64-Fedora-EPEL  state=latest" -vvvv
<g4t3773g> ESTABLISH CONNECTION FOR USER: stoflet on PORT 22 TO g4t3773g
<g4t3773g> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1359420393.49-231135382620037 && chmod a+rx $HOME/.ansible/tmp/ansible-1359420393.49-231135382620037 && echo $HOME/.ansible/tmp/ansible-1359420393.49-231135382620037'
<g4t3773g> REMOTE_MODULE yum name=monit enablerepo=RedHat-6Server-x86_64-Fedora-EPEL  state=latest
<g4t3773g> PUT /tmp/tmpJlTD58 TO /home/stoflet/.ansible/tmp/ansible-1359420393.49-231135382620037/yum
<g4t3773g> EXEC /bin/sh -c 'sudo -k && sudo -S -p "[sudo via ansible, key=jnnoqesjxwyjnodrurispgexkogskxha] password: " -u root /bin/sh -c '"'"'/usr/bin/python -tt /home/stoflet/.ansible/tmp/ansible-1359420393.49-231135382620037/yum; rm -rf /home/stoflet/.ansible/tmp/ansible-1359420393.49-231135382620037/ >/dev/null 2>&1'"'"''
g4t3773g | success >> {
    "changed": false,
    "msg": "",
    "rc": 0,
    "results": [
        "All packages providing monit are up to date"
    ]
}

Tried from boh command line (above) and playbook (below). Same thing:
....
  tasks:
- name: install HPIT EPEL repo
  action: yum pkg=hpit-yum-epel-repo state=latest
- name: install mongodb-server from EPEL repo
  action: yum pkg=mongodb-server state=latest enablerepo=RedHat-6Server-x86_64-Fedora-EPEL
  ...

This is occurring with other pkgs when I use enablerepo (e.g. monit) too.

I ultimately got it to work on a test host using
action: shell /usr/bin/yum install -y --enablerepo=_EPEL_ mongodb-server
from a playbook or this on the cmdline

ansible g4t3773g -s -m yum -a "name=mongodb-server enablerepo=_EPEL_  state=latest" 

Note: I was tailing /var/log/yum.conf. Nothing was added when using the yum module and enablerepo.

**Comment by mpdehaan** [comment]
interesting.

do you have yum-utils (provides repoquery) installed or not?

cc @skvidal

**Comment by dstoflet** [comment]
I do, and the server responding as up to date (g4t3773g) shows the following
repoquery --enablerepo=RedHat-6Server-x86_64-Fedora-EPEL mongodb-server
mongodb-server-0:2.0.7-1.el6.x86_64

If I get a bad repo name to the yum module enablerepo arg it fails, as expected. Likewise if I give it a bad pkg name
$ ansible g4t3773g -s -m yum -a "name=mongodb-server enablerepo=RedHat-6Server-x86_64-Fedora-EPE state=latest" 
g4t3773g | FAILED >> {
    "changed": false,
    "failed": true,
    "msg": "No Package matching 'mongodb-server' found available, installed or updated",
    "rc": 0,
    "results": []
}

$ ansible g4t3773g -s -m yum -a "name=mongodb-serve enablerepo=RedHat-6Server-x86_64-Fedora-EPEL state=latest" 
g4t3773g | FAILED >> {
    "changed": false,
    "failed": true,
    "msg": "No Package matching 'mongodb-serve' found available, installed or updated",
    "rc": 0,
    "results": []
}

**Comment by skvidal** [comment]
what version of ansible is this?

**Comment by dstoflet** [comment]
$ ansible --version
ansible 1.0

RHEL: Red Hat Enterprise Linux Server release 6.3 (Santiago)
$ uname -r
2.6.32-220.4.2.el6.x86_64

The failure to install via yum module occurs only when using enablerepo. There are no issues using the default enabled repos. I may just install yum-priorties to work around it.I really don't like using shell to get around (its not idempotent)

**Comment by mpdehaan** [comment]
Idempotence should really be about whether a command changes anything when
it doesn't need to, like replacing a file.  Yum itself has idempotence
checks in it's own layer even if you run the command.   Technically.

But yes, enablerepo=foo and such, ought to work.

**Comment by dstoflet** [comment]
Right, I was referring to the fact that as part of a play, using a command module to do the yum install returns "changed" : true even though it may not have actually changed anything.

**Comment by mpdehaan** [comment]
Yep, this is true unless you can supply a "creates=" on it, which you can.
- action: shell yum install ... creates=/usr/bin/some_binary

And if it is not there, it will skip and not report changed

Should be want you want as a workaround.

**Comment by dstoflet** [comment]
Perfect. I'll add that so I get proper change status back.

Btw, trying to simulate the command the yum module runs, I notice that adding --enablerepo to repoquery seems to cause it to return the package name, even when --pkgnarrow=installed. 

For instance below is a simple test for nc. Its not currently installed on the test system. It is however in the default enabled repos. So running repoquery with just --pkgnarrow=installed properly returns nothing. However adding the --enablerepo option causes it to return the package name, even with --pkgnarrow=installed (???)

$ yum list installed | grep ^nc$

$ repoquery --disablerepo=\* --pkgnarrow=installed -qf "%{name}-%{version}-%{release}.%{arch}" nc

$ repoquery --enablerepo=RedHat-6.0Server-x86_64-Server --disablerepo=\* --pkgnarrow=installed -qf "%{name}-%{version}-%{release}.%{arch}" nc  nc-0:1.84-22.el6.x86_64

**Comment by dstoflet** [comment]
Btw I am using repo-query from:
Installed Packages
Name        : yum-utils
Arch        : noarch
Version     : 1.1.30
Release     : 14.el6

**Comment by skvidal** [comment]
I've been thinking about the generic 'apply all updates' case for yum in an idempotent way. I think I can do that relatively easily, now. Essentially just check for updates, if they exist, apply them and verify that the application succeeded then mark as changed.

I'm unclear on how to specify it though - it cannot just be:

yum: state=updated 

w/o a pkg name specified. Perhaps update_all?

Any recommendations?

**Comment by mpdehaan** [comment]
yum name=all state=updated?

I like the check to see that name is required for the most part.

We could also do "*" , though people would prob expect it to be a glob
then?

**Comment by dhozac** [comment]
I can't reproduce this issue at all. repoquery behaves as expected, as does the yum module. Are you using yum plugins perhaps?

**Comment by dstoflet** [comment]
I have no yum-plugins installed. What version of yum-utils are using? Did you add the -qf %{name}-%{version}-%{release}.%{arch}" option to repoquery. That is added by is_installed and seems to not play well with --enablerepo

**Comment by dhozac** [comment]
yum-utils-1.1.30-14.el6.noarch

Make sure you have --qf, i.e. two dashes.

**Comment by dstoflet** [comment]
Ok my bad, that does work as expected. So repoquery dosen't look like the culprit. Still the yum module is not working for me when using enablerepo. 

Contrived example, enablerepo is not required for nc as it part of enabled repos by default, but a good example...
[stoflet@g2t1119g wildcat]$ ansible g4t3773g -s -m yum -a "state=latest name=nc enablerepo=RedHat-6.0Server-x86_64-Server"
g4t3773g | success >> {
    "changed": false,
    "msg": "",
    "rc": 0,
    "results": [
        "All packages providing nc are up to date"
    ]
}

# But remove enablerepo...

[stoflet@g2t1119g wildcat]$ ansible g4t3773g -s -m yum -a "state=latest name=nc"
g4t3773g | success >> {
    "changed": true,
    "msg": "",
    "rc": 0,
    "results": [
        "\n================================================================================\n Package Arch        Version          Repository                           Size\n================================================================================\nInstalling:\n nc      x86_64      1.84-22.el6      RedHat-6.0Server-x86_64-Server       57 k\n\nTransaction Summary\n================================================================================\nInstall       1 Package(s)\n\nTotal download size: 57 k\nInstalled size: 109 k\n\nInstalled:\n  nc.x86_64 0:1.84-22.el6                                                       \n\n"
    ]
}

**Comment by skvidal** [comment]
I am now able to replicate this with enablerepo on el6.

**Comment by skvidal** [comment]
I've found the issue - but absolutely no idea why it would only be triggered with enablerepo set. It should happen regardless. Testing some more.

**Comment by skvidal** [comment]
okay I think I see the issue completely now:
1. it won't always happen it ONLY happens when you enablerepo=a_broken_repo
2. I need to make the repoquery command in what_provides more able to emit a sensible error to the user.

I think in this case - if you pass in enablerepo= to yum and the repo is broken that yum should bail w/an error.

anyone object?

**Comment by dstoflet** [comment]
Broken repo how? If I pass the same repoid to yum it works

# yum install --enablerepo=RedHat-6.0Server-x86_64-Server nc

Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package nc.x86_64 0:1.84-22.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

# 

#  Package                    Arch                           Version                                Repository                                              Size

Installing:
 nc                         x86_64                         1.84-22.el6                            RedHat-6.0Server-x86_64-Server                          57 k

**Comment by skvidal** [comment]
run this command
repoquery --enablerepo=RedHat-6.0Server-x86_64-Server --whatprovides nc

**Comment by dstoflet** [comment]
# repoquery --enablerepo=RedHat-6.0Server-x86_64-Server --whatprovides nc

nc-0:1.84-22.el6.x86_64
nc-0:1.84-22.el6.x86_64

**Comment by skvidal** [comment]
are you running the above via ansible or directly?

Can you run the command in a -m command via ansible? B/c something is changing.

**Comment by dstoflet** [comment]
# note: nc is not installed on g4t3773g
$ ansible g4t3773g -s -m command -a "repoquery --enablerepo=RedHat-6.0Server-x86_64-Server --whatprovides nc" -vvv
<g4t3773g> ESTABLISH CONNECTION FOR USER: stoflet on PORT 22 TO g4t3773g
<g4t3773g> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1359656970.65-155996469634707 && chmod a+rx $HOME/.ansible/tmp/ansible-1359656970.65-155996469634707 && echo $HOME/.ansible/tmp/ansible-1359656970.65-155996469634707'
<g4t3773g> REMOTE_MODULE command repoquery --enablerepo=RedHat-6.0Server-x86_64-Server --whatprovides nc
<g4t3773g> PUT /tmp/tmpcx4gMo TO /home/stoflet/.ansible/tmp/ansible-1359656970.65-155996469634707/command
<g4t3773g> EXEC /bin/sh -c 'sudo -k && sudo -S -p "[sudo via ansible, key=ypecitsuxexukjbeoxrexdtexpodjsgz] password: " -u root /bin/sh -c '"'"'/usr/bin/python /home/stoflet/.ansible/tmp/ansible-1359656970.65-155996469634707/command; rm -rf /home/stoflet/.ansible/tmp/ansible-1359656970.65-155996469634707/ >/dev/null 2>&1'"'"''
g4t3773g | success | rc=0 >>
nc-0:1.84-22.el6.x86_64
nc-0:1.84-22.el6.x86_64

**Comment by skvidal** [comment]
okay then we are experiencing two different issues - though I suspect manifesting the same way.

In my case it happens when the repo is down/bad/broken. I think in your case repoquery is not returning anything sensible and not returning an error, either.

**Comment by skvidal** [comment]
I tested this some more. If the repo is functional - then enablerepo works with state=latest.

So - I'm very much hoping there is _something_ wrong with that or some repo you use. Maybe an intermittent failure?

**Comment by dhozac** [comment]
This comes from is_installed running

```
repoquery --show-duplicates --plugins --quiet -q --enablerepo rhel-x86_64-server-6 --disablerepo=* --pkgnarrow=installed --qf "%{name}-%{version}-%{release}.%{arch}" --whatprovides nc
```

which returns the package, even though it is not installed. Maybe this shouldn't have enablerepo's?

**Comment by dstoflet** [comment]
It very well may be the repo I am using.... However yum (direct) has never failed when pointing --enablerepo to the same repo in question.
I've gotten 100% failure rate using that repo with the yum module (ansible) using either latest or present (failure being it incorrectly thinks its installed and therefore a noop)

**Comment by skvidal** [comment]
https://github.com/skvidal/ansible/commit/5c26805ee78cd856bec94aa036848647c783b913

could you apply the patch above and try yours again. I'm trying to make sure that bogon repos or other config errors cannot trip up the module.

**Comment by dhozac** [comment]
Doesn't change anything with regard to the broken repoquery invocation though...

**Comment by dstoflet** [comment]
After applying the patch.

$ ansible g4t3773g -s -m yum -a "state=latest name=mongodb-server enablerepo=RedHat-6Server-x86_64-Fedora-EPEL" -vvv
<g4t3773g> ESTABLISH CONNECTION FOR USER: stoflet on PORT 22 TO g4t3773g
<g4t3773g> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1359679386.24-118318834864368 && chmod a+rx $HOME/.ansible/tmp/ansible-1359679386.24-118318834864368 && echo $HOME/.ansible/tmp/ansible-1359679386.24-118318834864368'
<g4t3773g> REMOTE_MODULE yum state=latest name=mongodb-server enablerepo=RedHat-6Server-x86_64-Fedora-EPEL
<g4t3773g> PUT /tmp/tmpyjYS8B TO /home/stoflet/.ansible/tmp/ansible-1359679386.24-118318834864368/yum
<g4t3773g> EXEC /bin/sh -c 'sudo -k && sudo -S -p "[sudo via ansible, key=cheyjuvjwqhkyhdvcnnvyllbedsrgbfy] password: " -u root /bin/sh -c '"'"'/usr/bin/python -tt /home/stoflet/.ansible/tmp/ansible-1359679386.24-118318834864368/yum; rm -rf /home/stoflet/.ansible/tmp/ansible-1359679386.24-118318834864368/ >/dev/null 2>&1'"'"''
g4t3773g | success >> {
    "changed": false,
    "msg": "",
    "rc": 0,
    "results": [
        "All packages providing mongodb-server are up to date"
    ]
}

$ ansible g4t3773g -s -m yum -a "state=present name=mongodb-server enablerepo=RedHat-6Server-x86_64-Fedora-EPEL" -vvv
<g4t3773g> ESTABLISH CONNECTION FOR USER: stoflet on PORT 22 TO g4t3773g
<g4t3773g> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1359679446.51-81477716774 && chmod a+rx $HOME/.ansible/tmp/ansible-1359679446.51-81477716774 && echo $HOME/.ansible/tmp/ansible-1359679446.51-81477716774'
<g4t3773g> REMOTE_MODULE yum state=present name=mongodb-server enablerepo=RedHat-6Server-x86_64-Fedora-EPEL
<g4t3773g> PUT /tmp/tmpyMS0BL TO /home/stoflet/.ansible/tmp/ansible-1359679446.51-81477716774/yum
<g4t3773g> EXEC /bin/sh -c 'sudo -k && sudo -S -p "[sudo via ansible, key=rnutovjqnazdyzfbfipegutsfqiujcbe] password: " -u root /bin/sh -c '"'"'/usr/bin/python -tt /home/stoflet/.ansible/tmp/ansible-1359679446.51-81477716774/yum; rm -rf /home/stoflet/.ansible/tmp/ansible-1359679446.51-81477716774/ >/dev/null 2>&1'"'"''
g4t3773g | success >> {
    "changed": false,
    "msg": "",
    "rc": 0,
    "results": [
        "package providing mongodb-server is already installed"
    ]
}

g4t3773g /var/log/messages
Feb  1 00:43:06 g4t3773g sudo:  stoflet : TTY=pts/1 ; PWD=/home/stoflet ; USER=root ; COMMAND=/bin/sh -c /usr/bin/python -tt /home/stoflet/.ansible/tmp/ansible-1359679386.24-118318834864368/yum; rm -rf /home/stoflet/.ansible/tmp/ansible-1359679386.24-118318834864368/ >/dev/null 2>&1
Feb  1 00:43:07 g4t3773g ansible-yum: Invoked with name=mongodb-server list=None conf_file=None state=latest disablerepo=None enablerepo=RedHat-6Server-x86_64-Fedora-EPEL
Feb  1 00:44:07 g4t3773g sudo:  stoflet : TTY=pts/1 ; PWD=/home/stoflet ; USER=root ; COMMAND=/bin/sh -c /usr/bin/python -tt /home/stoflet/.ansible/tmp/ansible-1359679446.51-81477716774/yum; rm -rf /home/stoflet/.ansible/tmp/ansible-1359679446.51-81477716774/ >/dev/null 2>&1
Feb  1 00:44:07 g4t3773g ansible-yum: Invoked with name=mongodb-server list=None conf_file=None state=present disablerepo=None enablerepo=RedHat-6Server-x86_64-Fedora-EPEL

**Comment by skvidal** [comment]
@dhozac You're seeing repoquery --pkgnarrow=installed return a non-installed pkg?

crap.

**Comment by skvidal** [comment]
okay - per a suggestion from @dhozac 
https://github.com/skvidal/ansible/commit/1c067845f21a31c46609a6fd973c8cf3b0cbfec1

That needs more testing.

**Comment by dstoflet** [comment]
Yah! state=latest works now. state=present still thought it was already installed however
$ ansible g4t3773g -s -m yum -a "state=latest name=mongodb-server enablerepo=RedHat-6Server-x86_64-Fedora-EPEL" -vvv
<g4t3773g> ESTABLISH CONNECTION FOR USER: stoflet on PORT 22 TO g4t3773g
<g4t3773g> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1359741235.48-25895039516886 && chmod a+rx $HOME/.ansible/tmp/ansible-1359741235.48-25895039516886 && echo $HOME/.ansible/tmp/ansible-1359741235.48-25895039516886'
<g4t3773g> REMOTE_MODULE yum state=latest name=mongodb-server enablerepo=RedHat-6Server-x86_64-Fedora-EPEL
<g4t3773g> PUT /tmp/tmp2Im1QG TO /home/stoflet/.ansible/tmp/ansible-1359741235.48-25895039516886/yum
<g4t3773g> EXEC /bin/sh -c 'sudo -k && sudo -S -p "[sudo via ansible, key=lkfwbstkkqsjxjwvnhdkcwroqlzcavrr] password: " -u root /bin/sh -c '"'"'/usr/bin/python -tt /home/stoflet/.ansible/tmp/ansible-1359741235.48-25895039516886/yum; rm -rf /home/stoflet/.ansible/tmp/ansible-1359741235.48-25895039516886/ >/dev/null 2>&1'"'"''
g4t3773g | success >> {
    "changed": true,
    "msg": "",
    "rc": 0,
    "results": [
        "\n================================================================================\n Package       Arch   Version           Repository                         Size\n================================================================================\nInstalling:\n mongodb-server\n               x86_64 2.0.7-1.el6       RedHat-6Server-x86_64-Fedora-EPEL 3.1 M\nInstalling for dependencies:\n boost-filesystem\n               x86_64 1.41.0-11.el6_1.2 RedHat-updates-QPK-6Server-x86_64  44 k\n boost-program-options\n               x86_64 1.41.0-11.el6_1.2 RedHat-updates-QPK-6Server-x86_64 105 k\n boost-system  x86_64 1.41.0-11.el6_1.2 RedHat-updates-QPK-6Server-x86_64  24 k\n boost-thread  x86_64 1.41.0-11.el6_1.2 RedHat-updates-QPK-6Server-x86_64  41 k\n js            x86_64 1.70-12.el6       RedHat-6Server-x86_64-Fedora-EPEL 365 k\n libmongodb    x86_64 2.0.7-1.el6       RedHat-6Server-x86_64-Fedora-EPEL 540 k\n mongodb       x86_64 2.0.7-1.el6       RedHat-6Server-x86_64-Fedora-EPEL  18 M\n snappy        x86_64 1.0.5-1.el6       RedHat-6Server-x86_64-Fedora-EPEL  34 k\n\nTransaction Summary\n================================================================================\nInstall       9 Package(s)\n\nTotal download size: 22 M\nInstalled size: 64 M\n\nInstalled:\n  mongodb-server.x86_64 0:2.0.7-1.el6                                           \n\nDependency Installed:\n  boost-filesystem.x86_64 0:1.41.0-11.el6_1.2                                   \n  boost-program-options.x86_64 0:1.41.0-11.el6_1.2                              \n  boost-system.x86_64 0:1.41.0-11.el6_1.2                                       \n  boost-thread.x86_64 0:1.41.0-11.el6_1.2                                       \n  js.x86_64 0:1.70-12.el6                                                       \n  libmongodb.x86_64 0:2.0.7-1.el6                                               \n  mongodb.x86_64 0:2.0.7-1.el6                                                  \n  snappy.x86_64 0:1.0.5-1.el6                                                   \n\n"
    ]
}

**Comment by dhozac** [comment]
Yeah, looks like it just needs to make sure that it doesn't modify the passed in repoq in what_provides, e.g. wp_repoq = list(repoq), and use that in the extend and subsequent command. Aside from that, this works for me.

**Comment by skvidal** [comment]
but we need repoq modified for what_provides - so it can look up pkgs when they are not installed.

**Comment by dhozac** [comment]
Yeah, but it should use a local instance, rather than modifying the global one that later gets used by is_installed.

**Comment by skvidal** [comment]
https://github.com/skvidal/ansible/commit/808554dee6bf612695ee44b85ddf103026b80aef

I hope that is all that's needed.
