### ISSUE TITLE
"AnsibleUndefinedVariable: 'unicode object' has no attribute when dict in json format

### ISSUE THREAD

**Issue by dmitryzykov** [ansible/ansible#19356]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
template/jinja/inventory

##### ANSIBLE VERSION

```
ansible 2.2.0.0
ansible-2.2.0.0-4.el7.noarch (latest from epel)
```

##### OS / ENVIRONMENT

CentOS Linux release 7.2
##### SUMMARY

When i declared dictionary var in defaults in **yaml** format and use it from jinja2 template **everything ok**.
When i declared the same var in **json** format in inventory file I got this error:
`"failed": true, "msg": "AnsibleUndefinedVariable: 'unicode object' has no attribute 'yAuthAPI'"}`

##### STEPS TO REPRODUCE

I set dict var in defaults/main.yml
```yaml
nginx_upstream_check_upstreams:
  yAuthAPI:
    enable: true
    http_send: 'GET / HTTP/1.0\r\n\r\n'
    expect_alive: "http_2xx"

  yAuthServer:
    enable: true
    http_send: 'GET / HTTP/1.0\r\n\r\n'
    expect_alive: "http_2xx"

nginx_backends:
  yAuthAPI:
    - 127.0.0.1
    - 127.0.0.2
  yAuthServer:
    - 127.0.0.3
    - 127.0.0.4
``` 
and use this dict var from template: 
```jinja
{% for backend in nginx_backends %}
upstream {{ backend }} {
    ip_hash;
{% for host in nginx_backends[backend] %}
    server {{ host }};
{% endfor %}

{% if nginx_upstream_check_enable %}
{% if nginx_upstream_check_upstreams[backend].enable %}
    check interval=5000 rise=1 fall=3 timeout=4000 type=http;
    check_http_send "{{ nginx_upstream_check_upstreams[backend].http_send }}";
    check_http_expect_alive {{ nginx_upstream_check_upstreams[backend].expect_alive }};
{% endif %}
{% endif %}
}
```
But when i declare this var in inventory in json format:
```yaml
[nginx:vars]
nginx_upstream_check_upstreams={ "yAuthAPI": { "enable": true, "http_send": "GET / HTTP/1.0\\r\\n\\r\\n", "expect_alive": "http_2xx" }, "yAuthServer": { "enable": true, "http_send": "GET / HTTP/1.0\\r\\n\\r\\n", "expect_alive": "http_2xx" }}
```
I have got this error:
`fatal: [10.2.79.1]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'unicode object' has no attribute u'yAuthAPI'"}
`

##### EXPECTED RESULTS

ansible-playbook output when var declared in yaml format:
```
TASK [nginx_sslmanager : debug] ************************************************
ok: [10.2.79.1] => {
    "nginx_upstream_check_upstreams": {
        "yAuthAPI": {
            "enable": true,
            "expect_alive": "http_2xx",
            "http_send": "GET / HTTP/1.0\\r\\n\\r\\n"
        },
        "yAuthServer": {
            "enable": true,
            "expect_alive": "http_2xx",
            "http_send": "GET / HTTP/1.0\\r\\n\\r\\n"
        }
    }
}

TASK [nginx_sslmanager : Copy nginx configuration in place] ********************
changed: [10.2.79.1]
```
Part of successfully generated conf file:
```
upstream yAuthAPI {
    ip_hash;
    server 127.0.0.1;
    server 127.0.0.2;

    check interval=5000 rise=1 fall=3 timeout=4000 type=http;
    check_http_send "GET / HTTP/1.0\r\n\r\n";
    check_http_expect_alive http_2xx;
}

upstream yAuthServer {
    ip_hash;
    server 127.0.0.3;
    server 127.0.0.4;

    check interval=5000 rise=1 fall=3 timeout=4000 type=http;
    check_http_send "GET / HTTP/1.0\r\n\r\n";
    check_http_expect_alive http_2xx;
}

```
##### ACTUAL RESULTS

ansible-playbook output when var declared in json format in inventory file:
```
TASK [nginx_sslmanager : debug] ************************************************
ok: [10.2.79.1] => {
    "nginx_upstream_check_upstreams": {
        "yAuthAPI": {
            "enable": true,
            "expect_alive": "http_2xx",
            "http_send": "GET / HTTP/1.0\\r\\n\\r\\n"
        },
        "yAuthServer": {
            "enable": true,
            "expect_alive": "http_2xx",
            "http_send": "GET / HTTP/1.0\\r\\n\\r\\n"
        }
    }
}

TASK [nginx_sslmanager : Copy nginx configuration in place] ********************
fatal: [10.2.79.1]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'unicode object' has no attribute u'yAuthAPI'"}

```

**Comment by alikins** [comment]
Possibly related to https://github.com/ansible/ansible/issues/16714 ?

**Comment by bcoca** [comment]
The issue is that you are assuming JSON is a valid declaration in an ini inventory variable, it is NOT. 

It will appear as a string, so the error is correct.

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
