### ISSUE TITLE
Template update convert \n to actual new line

### ISSUE THREAD

**Issue by water4u99** [ansible/ansible#19352]
##### ISSUE TYPE

    Bug Report

##### COMPONENT NAME

template

##### ANSIBLE VERSION

2.0 and higher
CONFIGURATION
```
[ssh_connection]
control_path = %(directory)s/%%C
```
##### OS / ENVIRONMENT

Mac OS X 10.11.6
Centos 6.x, 7.x
SUMMARY

In the input .j2 file, we substitute a variable with an environment variable that has a line/string that contains a grok expression containing `(?m)\n` . The output generated by the template module in versions 2.0 and later, treats the \n as actual line break. Where as versions up to 1.9.6 retains the literal `(?m)\n` without replacing the \n with an actual line break. We see the line break after we upgraded the Ansible version to 2.x.

Any way we can work around this issue? Thank you for your help.
##### STEPS TO REPRODUCE

Our execution flow is probably not the nicest - we want to reengineer it soon. Basic steps:

    Run a shell script with ansible-playbook command that pass in an env variable with `(?m)\n` literal.
    Playbook calls a main yaml file and assigns shell environment var to a included task yaml file.
    The task yaml file invokes the template module.

In the snippet below I stripped out other lines/vars for clarity.

main shell
```
set GROK_PATTERN_GENERAL_ERROR_PG="%{TIMESTAMP_ISO8601} ERROR \[%{USER:handlerName}\] %{USER:className}%{GREEDYDATA:errorline1}((?m)\n%{USER:logerror}%{GREEDYDATA})"
```
```
ansible-playbook -i ../common/host.inventory \
                -${VERBOSE} \
                t.yml \
                ${CHECK_ONLY} \
                --extra-vars "hosts='${HOST}'
                              xlogstash_grok_general_error='${GROK_PATTERN_GENERAL_ERROR_PG}'
                             "
```
t.yml
```
---
- hosts: 127.0.0.1
  connection: local

  tasks:
    - include_vars: ../common/defaults/main.yml
    - name: generate logstash kafka logscan filter config file
      include: tasks/t.yml
      vars:
          logstash_grok_general_error: "{{xlogstash_grok_general_error}}"
```
tasks/t.yml
```
---
    - name: generate logstash kafka logscan filter config file
      template: src=../common/templates/my.conf.j2
                dest="./500-filter.conf"
```
my.conf.j2
```
        grok {
                break_on_match => "true"
                match => [
                        "message", "{{logstash_grok_general_error}}"
                ]
        }
```
Note the `(?m)\n` are still on the same line.
##### EXPECTED RESULTS
```
        grok {
                break_on_match => "true"
                match => [
                        "message", "%{TIMESTAMP_ISO8601} ERROR \[%{USER:handlerName}\] %{USER:className}%{GREEDYDATA:errorline1}((?m)\n%{USER:logerror}%{GREEDYDATA})"
                ]
        }
```
##### ACTUAL RESULTS

Note `(?m)\n` now has the `\n` as actual line break.
```
        grok {
                break_on_match => "true"
                match => [
                        "message", "%{TIMESTAMP_ISO8601} ERROR \[%{USER:handlerName}\] %{USER:className}%{GREEDYDATA:errorline1}((?m)
%{USER:logerror}%{GREEDYDATA})"
                ]
        }
```

**Comment by tumbl3w33d** [comment]
Have you tried working around it with
```
{% raw %}{% endraw %}
```
?

**Comment by jhawkesworth** [comment]
For info I have seen another bug report which might be related.  Its for the win_template module saying that the 
#jinja2: newline_sequence:'\r\n'
directive no longer results in windows style line endings.
I haven't investigated yet and can't now find the other bug report but believe the two issues could be related.

**Comment by springuper** [comment]
@tumbl3w33d it doesn't work because the variable block wrapped in `raw` doesn't be replaced by real content.

**Comment by kokarn** [comment]
I'm seeing something that might be related to this as well.
The win_template.changed is always true on every run.

**Comment by Akasurde** [comment]
> From @r4j4h commented [on 6 May 2018](#issuecomment-386877786)

Hi there,

I have found a way around this!

Judging by the changes in https://github.com/ansible/ansible/issues/12241#issuecomment-137606517 I noticed it was around escaping so I found replacing `\n` with `\\n` to be effective in getting the expected results.

So try:

```
{{ xlogstash_grok_general_error | replace('\n', '\\n') }}'
```

Hope it works for you as well!!

**Comment by manov555** [comment]
I think **"{{ var_.stdout.split('\n')  }}"** could be also helpfull

**Comment by sivel** [comment]
The problem here is in how you are passing the env var into ansible.

When you effectively do the following:

```
-e "xlogstash_grok_general_error='%{TIMESTAMP_ISO8601} ERROR \[%{USER:handlerName}\] %{USER:className}%{GREEDYDATA:errorline1}((?m)\n%{USER:logerror}%{GREEDYDATA})'"
```

Ansible has to try to intelligently split based on both an `=` and ensuring things are encompassed by quotes, and there are subtle consequences to achieving that goal.

If you were to remove the single quotes around the value, the problem would go away.  Additionally, if you were to supply JSON instead of key=value you wouldn't have the issue:

```
-e "{'hosts': '${HOST}', 'xlogstash_grok_general_error': '${GROK_PATTERN_GENERAL_ERROR_PG}'}"
```

Or, your other option would be to use the following to get that env var:

```
logstash_grok_general_error: "{{lookup('env', 'GROK_PATTERN_GENERAL_ERROR_PG') }}"
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
