### ISSUE TITLE
OHAI Issue: "changed": false, "cmd": "/usr/bin/ohai", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2

### ISSUE THREAD

**Issue by suny211** [ansible/ansible#19369]
Executing the command: ansible-playbook playbookname.yml -f 10
getting the following error.

TASK [setup] *******************************************************************
fatal: [remote-ip]: FAILED! => {"changed": false, "cmd": "/usr/bin/ohai", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
	to retry, use: --limit @/root/myPlaybook/httpd.retry

PLAY RECAP *********************************************************************
remote-ip              : ok=0    changed=0    unreachable=0    failed=1 

What could be the issue?
the ssh connection is perfectly established and i am able to ping the remote server in the /etc/ansible/hosts file.

**Comment by alikins** [comment]
What version of ansible?


Sounds like it is attempting to use Ohai to collect additional facts, but the 'ohai' command it finds fails with the "[Errno 2] No such file or directory" error.  That may mean ohai is busted.

To disable, set the 'gather_facts' to '!ohai' to skip ohai fact collection
