### ISSUE TITLE
Cannot find vars_files with relative paths using --list-tags and multiple playbook includes

### ISSUE THREAD

**Issue by towolf** [ansible/ansible#19398]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`--list-tags` with multiple playbooks

##### ANSIBLE VERSION

```
ansible-playbook 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

We have a tool that gathers all tags recursively over all playbooks. It errors out finding `vars_files` on a playbook that includes other playbooks with relative paths.

```
---

- include: deploy/foo.yml
- include: bar.yml
- include: deploy/baz.yml
```
Called with `ansible-playbook playbooks/total-deploy.yml --list-tags`

Or directly with `ansible-playbook deploy/foo.yml  bar.yml deploy/baz.yml --list-tags`

Individually, any of these included playbooks work with --list-tags. Only when they are combined *and live at different relative paths* does this fail with an error.

This bug smells a bit like: https://github.com/ansible/ansible/issues/16995

##### STEPS TO REPRODUCE

Simple test case: https://github.com/towolf/playbook-includes

```yaml
ansible-playbook -i localhost, --list-tags playbooks/total-deploy.yml
ansible-playbook -i localhost, --list-tags playbooks/deploy/foo.yml playbooks/bar.yml playbooks/deploy/baz.yml
```

##### EXPECTED RESULTS

List tags without error

##### ACTUAL RESULTS

```
As playbook with includes

playbook: playbooks/total-deploy.yml

  play #1 (localhost): my play  TAGS: []
      TASK TAGS: []

  play #2 (localhost): my play  TAGS: []
ERROR! vars file includes/myvars.yml was not found

As a list of playbooks

playbook: playbooks/deploy/foo.yml

  play #1 (localhost): my play  TAGS: []
ERROR! vars file ../includes/myvars.yml was not found
```

**Comment by hloeffler** [comment]
this worked with 1.9

**Comment by hloeffler** [comment]
@bcoca @jimi-c 
any clues what this could be?
perhaps we can fix and make a PR

**Comment by jimi-c** [comment]
Very odd, I went back and verified this hasn't worked since 2.0. I'll look into it.

**Comment by jimi-c** [comment]
@towolf the weirder thing is running it at all appears to not load ANY tasks:
<pre>
$ ansible-playbook -vv playbooks/total-deploy.yml 
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: total-deploy.yml *****************************************************************
3 plays in playbooks/total-deploy.yml

PLAY [my play] *****************************************************************

TASK [Gathering Facts] *****************************************************************
ok: [localhost]

PLAY [my play]  *****************************************************************

PLAY [my play]  *****************************************************************

PLAY RECAP  *****************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

**Comment by towolf** [comment]
There are no tasks in my test case. It's just a minimal example showing the problem. 

But this occurs with regular playbooks as well.

**Comment by jimi-c** [comment]
*sigh* might be time to call it a night... I had glanced at the files and thought they were doing include_vars, not vars_files...

**Comment by hloeffler** [comment]
thanks, hope to see that in next bugfix release :)

**Comment by towolf** [comment]
Thanks Jimmy and merry Christmas.
