### ISSUE TITLE
Notifying list of handlers as variables

### ISSUE THREAD

**Issue by ndarilek** [ansible/ansible#1941]
I'd like to do something like:

  notify: $sslHandlers

after pushing a new SSL certificate to a host, then set different sslHandlers in host_vars. Maybe simpler hosts only need to restart Nginx when a certificate updates, but more complicated servers may need to bounce Nginx, Prosody, Postfix and Dovecot. Instead of adding these handlers to each host and copying tasks, it'd be nice to assign a variable.

**Comment by mpdehaan** [comment]
merging with the #1312 "handlers upgrades" ticket for keeping everything straight.

I agree!
