### ISSUE TITLE
vmware_guest: Various problems with the current design (blocks imminent release)

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#19417]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

v2.2+

##### SUMMARY

After carefully testing the current implementation and extending the capabailities I came to the conclusion that the current **vmware_guest** module implementation lacks proper forward compatibility wrt. customizations, but there are many other problems.

- ~~The current customizations are in the same namespace as the module options, which will lead to problems. It would be wiser to replace the **customize**-switch and the myriad of customization options, with a single **customizations** dictionary with a mapping between the possible API customizations and the various options available. So that we can extend it without having to change the module options.~~ #19975
- ~~The current customizations are also Linux oriented (LinuxPrep) whereas the code should allow both LinuxPrep as well as SysPrep, so a redesign is needed for this too.~~ #19866
- ~~Besides that, a lot of options that reflect the VM conflict with options to the module (e.g. username/password, etc...) So using a single namespace is not very future-proof.~~ #19866
- ~~Another problem is speed~~ #19830 and #19937
- ~~Another is false matches. I think we can do with fewer guesses and expecting that the user provides correct information (through clear documentation).~~ #19823 
- ~~The module also reports it supports check-mode, but that is incorrect according to my testing. Even in check-mode it will create a VM happily if it was not found.~~ #19228 
- ~~The **wait_for_ip** functionality does not appear to work, and on we actually need a **wait_for_customizations** instead, because on Windows there's at least one more reboot after that.~~ #20011 
- ~~Snapshot operations should most likely go into a separate module specifically for doing snapshotting. **vmware_guest_snapshot**~~ #20971
- ~~Facts gathering should also go into a separate module, in line with other cloud infra modules **vmware_guest_facts**~~ #20971

So if anything we should refrain from releasing the current implementation before we get most of this figured out, as I fear we cannot refactor without breaking it for existing users if the current changes are being released. (v2.2 ships with a release without customizations afaict)

**Comment by nitzmahone** [comment]
Sounds like we've got some more thought required on this before 2.3 ships. Do we want to revert this, or roll forward? I know I won't personally have any bandwidth to dedicate to this one in 2.3 timeframe, and I think Tanner's pretty busy in ansibot-land...

On the UI change: I have mixed feelings about the implications of changing to a sub-dict, the biggest one being that we lose arg validation/canonicalization stuff (at least as it works today). If pyvmomi is consistent enough about the "shape" of these thing that we can delegate it to a dumb passthru API K/V mapping, that's not so big a deal, but I'd want to see what that looks like from an implementation perspective (and if it's really that simple).

Thoughts on immediate action? Does @dav1x have anything to add?

**Comment by dagwieers** [comment]
@nitzmahone It won't be simple, but there are so many things missing from the customizations right now. I can provide you with a list of missing stuff tomorrow if you like. And that's not even conclusive...

And then there's also issue #19222 :-(

**Comment by dav1x** [comment]
I'll review tomorrow.  Please provide the list of missing customizations. Sorry, I've been pretty inactive for the last 2 weeks because of other work responsibilities

**Comment by dagwieers** [comment]
I may have some time to work on this, but I need to balance the time I am assigned for $PROJECT.
Working on this upstream is preferred, but it shouldn't become a risk to the project.

I would also simplify the module to not allow e.g. VMs with non-unique names. So I would modify the module to work on a strict name basis, and report when more than one VM is detected with the same name. (In fact, I would take the same stance for other resources).

I think this is a best-practice in most companies anyway and it makes handling (and addressing) objects a lot easier and straightforward. Especially if we want an idempotent module. (One where we can create a new VM when it does not exist, or work on the existing one if it does exist)

**Comment by dagwieers** [comment]
@nitzmahone The last changes from @nerzhul fixes various problems reported in this ticket. I also created a few PRs fixing some. But before we ship this I would like to ensure that the interface to the user is designed with future needs in mind. So we're past the point of reverting ;-)

**Comment by aperigault** [comment]
@dagwieers I create a new PR #19866 to add windows customization support. Tell me what you think about it.

**Comment by dagwieers** [comment]
Looking at the list, we are almost there.

What do people think about splitting of snapshot operations and facts gathering ?

This obviously means moving generic calls into `module_utils`, and this can only happen when all the open PRs have been merged in vmware_guest.

**Comment by bcoca** [comment]
+10, though vmware_guest should retrurn some pertinent facts about the guest it creates/updates

**Comment by nerzhul** [comment]
@dagwieers module_utils are a common ansible interface for vmware ? if yes could be good to split some parts! (for example we will need gather_facts for vmware_guest and for vmware_guest_facts future module). Also moving snapshot is required

**Comment by dagwieers** [comment]
All reported issues have been fixed now. So this ticket can be closed.
Thanks to everyone involved !
