### ISSUE TITLE
Services behaviour changed between v2.1.1 and 2.2.0

### ISSUE THREAD

**Issue by zerkms** [ansible/ansible#19422]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
* service

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0.0
  config file = /home/ansible/sentry/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Everything by default

##### OS / ENVIRONMENT

ubuntu 14.04

##### SUMMARY

Until version 2.1.1 I have been using the following way to reload the nginx service

```
- name: service
  service: name=nginx state=reloaded 
```

And it worked great.

With version 2.2.0 the same command outputs

```
{"changed": false, "failed": true, "msg": "Failed to get the service status 'nginx': org.freedesktop.DBus.Error.FileNotFound \"No such file or directory\""}
```

And if I change it to use old service method

```
- name: service
  service: name=nginx state=reloaded use=service
```

it still fails with

```
{"changed": false, "failed": true, "msg": "Failed to issue method call: Unit nginx.service failed to load: No such file or directory. See system logs and 'systemctl status nginx.service' for details.\n"}
```

The `nginx` service is run by the `init.d` and there is no corresponding `systemd` configuration.

**Comment by ajmaidak** [comment]
I experienced this same issue.  It was caused by having the systemd package loaded on 14.04.  Removing the systemd package removed systemctl which caused ansible to do the right thing.

**Comment by ghost** [comment]
+1 on failures after 12.04 --> 14.04 upgrade. Removing systemd fixed it for me.

**Comment by zerkms** [comment]
Alternatively to removing one may install `systemd-shim` (that's how I did it, since some packages depend on either).

**Comment by ajmaidak** [comment]
#19030 appears related to this...

**Comment by sivel** [comment]
To explicitly work with `init.d`, you will need to either directly invoke the `sysvinit` module, or specify `use=sysvinit` with the `service` module.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
