### ISSUE TITLE
include_role doesn't work

### ISSUE THREAD

**Issue by rakshazi** [ansible/ansible#19425]
##### ISSUE TYPE

 - Bug Report
 - Help needed

##### COMPONENT NAME

module/utils/logic/include_role.yml

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /home/rakshazi/projects/opsway/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

```
[defaults]
hostfile = data/hosts
roles_path = data/galaxy:data/roles
callback_plugins = data/plugins/callback
display_skipped_hosts = True
deprecation_warnings = False
callback_whitelist = slack_github
ansible_managed = "DO NOT TOUCH - managed by Ansible. Last update: %Y-%m-%d %H:%M:%S by {uid}."
host_key_checking = False
```

##### OS / ENVIRONMENT

```
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	16.10
Codename:	Fringilla
```
##### SUMMARY

`incude_role` doesn't work. Please, explain how can I fix this problem and what doing wrong?

##### STEPS TO REPRODUCE

First of all, run `ansible-galaxy install votum.magento2`

custom role tasks/main.yml content (in my case: `data/roles/medtech/tasks/main.yml`)
```yaml
---
- include_role: name="votum.magento2"
  vars_from: "{{ role_path }}/vars/magento2.yml"
```

##### EXPECTED RESULTS

Role incuded and role tasks executed

##### ACTUAL RESULTS

```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
The error appears to have been in '/ansible-container/ansible/data/roles/medtech/tasks/main.yml': line 5, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
 - include: configs.yml
 - include_role: name="votum.magento2"
   ^ here
```

pS: There is no problem without include_role, but when I add `include_role`, play fails

**Comment by tumbl3w33d** [comment]
The way you write the include looks like the playbook include style, however, according to the [documentation](https://docs.ansible.com/ansible/include_role_module.html) _include_role_ is a module which can be used in a "task-style" way, so try putting it on task level instead of play level.

**Comment by rakshazi** [comment]
@tumbl3w33d I have `include_role` in `<role>/tasks/main.yml`, not in playbook.
You can write tasks as:
```yml
- name: Your task name
  command: your command
```

or without name:
```yml
- command: your command
```

There is no matter

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The error message is correct, your play is invalid, both your indentation is off and you are mixing k=v with k: v:

either:
```
- include_role: name="votum.magento2" vars_from="{{ role_path }}/vars/magento2.yml"
```
or
```
- include_role: 
         name: "votum.magento2" 
         vars_from: "{{ role_path }}/vars/magento2.yml"
```
are correct, but your version of the task is not.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
