### ISSUE TITLE
lineinfile crash instead of skipping inside a block when condition 

### ISSUE THREAD

**Issue by roumano** [ansible/ansible#19439]
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME
lineinfile
##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY
I use a lineinfile with variable
something the variable not exist but i have added a when on the lineinfile to do not doing change when the variable not exist
even inside a block, other module are skipping but lineinfile is crash 

##### STEPS TO REPRODUCE

```
---
- hosts: cia
  gather_facts: no
  tasks:
   - name: test if need to be done task
     command: "awk '/set superusers=\"grub_admin\"/' /etc/grub.d/01_users"
     register: grub2_superuser
     changed_when: False

   - block:
      - debug: var=grub2_superuser

      - name: Grub2 Get hash of password
        shell: "echo -e 'XXXXXX\nXXXXXX' | grub2-mkpasswd-pbkdf2 | awk '/grub.pbkdf/{print$NF}'"
        changed_when: False
        register: result
        when: grub2_superuser.stdout == ""
      - debug: msg=" pwd egal a    {{ result.stdout }}" 
      - debug: var={{ result }}

      - set_fact: grubpwd="{{ result.stdout }}" 
     
      - name: Grub2 Set superuser grub as grub_admin
        lineinfile:
          dest: /etc/grub.d/01_users
          backup: yes
          create: no
          regexp: '{{ item.regexp }}'
          line: '{{ item.line }}'
        with_items:
          - { regexp: 'set superusers' , line: '    set superusers="grub_admin"' }
          - { regexp: 'password_pbkdf2' , line: '    password_pbkdf2 grub_admin {{ grubpwd }}' }
   
     when: grub2_superuser.stdout == ""

```
##### EXPECTED RESULTS
skipping the module lineinfile as it's on a block with a when condition
i have the same issue without the bock and the when inside the module lineinfile
##### ACTUAL RESULTS
```
 ansible-playbook --inventory=list_edfx ~/Documents/ansible/test.yml --limit cia --sudo --ask-sudo  -vvv
Using /etc/ansible/ansible.cfg as config file
SUDO password: 

PLAYBOOK: test.yml *************************************************************
1 plays in /home/fedora/Documents/ansible/test.yml

PLAY [cia] *********************************************************************

TASK [test if need to be done task] ********************************************
task path: /home/fedora/Documents/ansible/test.yml:5
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/commands/command.py
...

ok: [cia] => {
    "changed": false, 
    "cmd": [
        "awk", 
        "/set superusers=\"grub_admin\"/", 
        "/etc/grub.d/01_users"
    ], 
    "delta": "0:00:00.002929", 
    "end": "2016-12-16 15:13:12.092651", 
    "invocation": {
        "module_args": {
            "_raw_params": "awk '/set superusers=\"grub_admin\"/' /etc/grub.d/01_users", 
            "_uses_shell": false, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }, 
        "module_name": "command"
    }, 
    "rc": 0, 
    "start": "2016-12-16 15:13:12.089722", 
    "stderr": "", 
    "stdout": "    set superusers=\"grub_admin\"", 
    "stdout_lines": [
        "    set superusers=\"grub_admin\""
    ], 
    "warnings": []
}

TASK [debug] *******************************************************************
task path: /home/fedora/Documents/ansible/test.yml:11
skipping: [cia] => {
    "changed": false, 
    "skip_reason": "Conditional check failed", 
    "skipped": true
}

TASK [Grub2 Get hash of password] **********************************************
task path: /home/fedora/Documents/ansible/test.yml:13
skipping: [cia] => {
    "changed": false, 
    "skip_reason": "Conditional check failed", 
    "skipped": true
}

TASK [debug] *******************************************************************
task path: /home/fedora/Documents/ansible/test.yml:18
skipping: [cia] => {
    "changed": false, 
    "skip_reason": "Conditional check failed", 
    "skipped": true
}

TASK [debug] *******************************************************************
task path: /home/fedora/Documents/ansible/test.yml:19
skipping: [cia] => {
    "changed": false, 
    "skip_reason": "Conditional check failed", 
    "skipped": true
}

TASK [set_fact] ****************************************************************
task path: /home/fedora/Documents/ansible/test.yml:21
skipping: [cia] => {
    "changed": false, 
    "skip_reason": "Conditional check failed", 
    "skipped": true
}

TASK [Grub2 Set superuser grub as grub_admin] **********************************
task path: /home/fedora/Documents/ansible/test.yml:23
fatal: [cia]: FAILED! => {
    "failed": true, 
    "msg": "'grubpwd' is undefined"
}
	to retry, use: --limit @/home/fedora/Documents/ansible/test.retry

PLAY RECAP *********************************************************************
cia                        : ok=1    changed=0    unreachable=0    failed=1   

```
i have make a workaround via creating default variable outside the block ( never used ) but it's a ugly workaround

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

As documented http://docs.ansible.com/ansible/playbooks_conditionals.html#loops-and-conditionals, `when` executes inside `with` and cannot short circuit it.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by roumano** [comment]
Hi,
I have read this document
but the lineinfile where i hav tested is insied a block (with a when on the block)
So all task inside the block are skipping expect the lineinfile so for me it's a bug ! 


 - block:
      - debug: var=grub2_superuser
      - name: Grub2 Set superuser grub as grub_admin
        lineinfile:
          dest: /etc/grub.d/01_users
          backup: yes
          create: no
          regexp: '{{ item.regexp }}'
          line: '{{ item.line }}'
        with_items:
          - { regexp: 'set superusers' , line: '    set superusers="grub_admin"' }
          - { regexp: 'password_pbkdf2' , line: '    password_pbkdf2 grub_admin {{ grubpwd }}' } 
     when: grub2_superuser.stdout == ""

The when is on the block level so all task inside the block should be skipped but it's not the case (lineinfile crash instead of skipping)

**Comment by bcoca** [comment]
Directives like `when` do not apply to the `block` itself, they are inherited by the tasks, you are relying on a feature that does not exist.

**Comment by roumano** [comment]
you are relying on a feature that does not exist.
> so it"s a feature request and it's will be very useful to have it and it's will permit to have module work uniformely
