### ISSUE TITLE
want to be able to access len() in Jinja2

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1944]
It looks like we need to export some more globals than we already do

Example of what does not work:

{% if len(diskpart) %}d-i partman-auto/disk string {% for element in diskpart %}{{ element }} {% endfor %}{% endif %}

**Comment by dhozac** [comment]
length is a filter in Jinja2, so diskpart|length is probably what you want. len doesn't seem to be something it has.

**Comment by mpdehaan** [comment]
I don't want to use it in a value, but rather I need to do an if statement based on the length of an array.

I think this is just about exposing more globals to it.

**Comment by dhozac** [comment]
Right, so `{% if diskpart|length %}` would do the trick. We could of course add more globals to it, but it seems like we should encourage the use of what Jinja2 has built-in first and foremost.

**Comment by mpdehaan** [comment]
Wasn't aware filters worked in conditionals.  That will work for now.

I, however, disagree with that last part -- people are going to want to do
what's intuitive, and in most other templating languages your if statement
can look like your programming language.

We shouldn't go crazy, but I see no reason not to expose len()

**Comment by mpdehaan** [comment]
It's really Guido's fault that there is not a length method on all of
those objects, regardless of how he implemented it :)
