### ISSUE TITLE
ansible-galaxy can't install roles in a requirements file from a custom source if that role has the 'role' attribute

### ISSUE THREAD

**Issue by alvaroaleman** [ansible/ansible#19469]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible-galaxy

##### ANSIBLE VERSION
```
2.2.0.0
```

##### SUMMARY

ansible-galaxy can't install roles in a requirements file from a custom source, if that role has a 'role' attribute, error is ` [WARNING]: - my_github_demo_role was NOT installed successfully: Role has no field named u'owner`

##### STEPS TO REPRODUCE

```shell
cat << EOF > requirements.yml
- role: my_github_demo_role
  src: https://github.com/silpion/ansible-lib.git
EOF
ansible-galaxy install --force -r requirements.yml
```

##### EXPECTED RESULTS
```
- extracting my_github_demo_role to /tmp/fasfasfasfas/roles/my_github_demo_role
- my_github_demo_role was installed successfully
```

##### ACTUAL RESULTS

```
[DEPRECATION WARNING]: The comma separated role spec format, use the yaml/explicit format instead..
This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
- downloading role 'my_github_demo_role', owned by 
 [WARNING]: - my_github_demo_role was NOT installed successfully: Role has no field named u'owner'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list
```

This error does not occur when the role in the requirements file doesn't have a `role` attribute.
It seems like ansible-galaxy tries to talk the galaxy api if it finds roles with the `role` attribute.

Instead, ansible-galaxy should try to talk to the galaxy api only if a role does not have a `src` attribute.

The current behaviour is counterintuitive at best.

**Comment by bcoca** [comment]
The spec has not been clear, but can you change `role` for `name`?

**Comment by alvaroaleman** [comment]
If I change `role` for `name` it does work, but IMHO that's pretty confusing.

**Comment by bcoca** [comment]
i dont disagree, but when using `src` you should use `name` as that is how the spec works, `role` can be short hand for `name` but not if you add more properties. role = name + src + vcs + version

**Comment by bcoca** [comment]
closing as per above
