### ISSUE TITLE
ansible command module uses users's locale but states it is not affected by user's environment

### ISSUE THREAD

**Issue by tyll** [ansible/ansible#19478]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
command module

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/srv/web/infra/ansible/library', '/usr/share/ansible']
```

##### OS / ENVIRONMENT
RHEL 7 managing RHEL 7

##### SUMMARY

In Fedora we use the command module and check its output to see if certain things need to be changed regarding kerberos:
https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/keytab/service/tasks/main.yml#n49

Since ansible seems to use the user's locale when running the commands, checking the output fails if it is not an English locale but for example German.

##### STEPS TO REPRODUCE
```
$ ansible -m command -a "printenv LANG" localhost
 [WARNING]: provided hosts list is empty, only localhost is available

localhost | SUCCESS | rc=0 >>
de_DE.UTF-8
$ LANG=C ansible -m command -a "printenv LANG" localhost
 [WARNING]: provided hosts list is empty, only localhost is available

localhost | SUCCESS | rc=0 >>
C

$ LANG=C ansible -m command -a "printenv LANG" centos6test
centos6test | SUCCESS | rc=0 >>
C

$ ansible -m command -a "printenv LANG" centos6test
centos6test | SUCCESS | rc=0 >>
de_DE.UTF-8
```

##### EXPECTED RESULTS
The command environment should not depend on the users environment as documented. Otherwise it should be clearly documented, but then the command module should also allow to specify values for the affected environment to make sure that there are no side effects from the user running a playbook.

##### ACTUAL RESULTS
It seems that ansible explicitly sets the locale on the target machine to the user's locale...
```
$ ansible -vvvv -m command -a "printenv LANG" centos6test
Using /etc/ansible/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<centos6test> ESTABLISH SSH CONNECTION FOR USER: None
<centos6test> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/till/.ansible/cp/ansible-ssh-%C -tt centos6test '/bin/sh -c '"'"'( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1482055880.26-122303795708877 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1482055880.26-122303795708877 `" )'"'"''
<centos6test> PUT /tmp/tmpoaOUrx TO /root/.ansible/tmp/ansible-tmp-1482055880.26-122303795708877/command
<centos6test> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/till/.ansible/cp/ansible-ssh-%C '[centos6test]'
<centos6test> ESTABLISH SSH CONNECTION FOR USER: None
<centos6test> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/till/.ansible/cp/ansible-ssh-%C -tt centos6test '/bin/sh -c '"'"'LANG=de_DE.UTF-8 LC_ALL=de_DE.UTF-8 LC_MESSAGES=de_DE.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1482055880.26-122303795708877/command; rm -rf "/root/.ansible/tmp/ansible-tmp-1482055880.26-122303795708877/" > /dev/null 2>&1'"'"''
centos6test | SUCCESS | rc=0 >>
de_DE.UTF-8

```

**Comment by alikins** [comment]
Sounds like a documentation error, since the command module itself doesn't do much with the environment. ie, it doesn't strip it.

Assuming this is in reference to the note in the command module docs:

> Note
> If you want to run a command through the shell (say you are using <, >, |, etc), you actually want the shell module instead. The command module is much more secure as it’s not affected by the user’s environment.

**Comment by ghost** [comment]
This behavior is controlled by the configuration option [`module-set-locale`](https://docs.ansible.com/ansible/intro_configuration.html#module-set-locale). The default value of this option changed in Ansible 2.2 to False. Since you are using Ansible 2.2 the option seems to be enabled in your `ansible.cfg`.

**Comment by samccann** [comment]
Closing this issue. Seems the config option mentioned above was removed in 2.8 so assuming this issue no longer exists.
