### ISSUE TITLE
No modules in release tarball?

### ISSUE THREAD

**Issue by JulienPalard** [ansible/ansible#19482]
##### ISSUE TYPE
 - Bug Report / Documentation Report

##### COMPONENT NAME
installation

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

```
mdk@silversky$ uname -a
Linux silversky 4.6.0-1-amd64 #1 SMP Debian 4.6.3-1 (2016-07-04) x86_64 GNU/Linux
mdk@silversky$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux testing (stretch)
Release:	testing
Codename:	stretch
```

##### SUMMARY
Having the https://github.com/ansible/ansible-modules-core/issues/5347 bug, I wanted to test the freshly released ansible v2.2.1.0-0.2.rc2. Downloaded the tarball, ran `python3 setup.py install --user`, tried my playbook and got:

```
ERROR! The requested action was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem.
```

But the traball is not a git repo, can't run `git submodule update --init --recursive` in it.

##### STEPS TO REPRODUCE

 - wget -qO- https://github.com/ansible/ansible/archive/v2.2.1.0-0.2.rc2.tar.gz | tar xzvf -
 - cd ansible-2.2.1.0-0.2.rc2
 - python3 setup.py install --user
 - cd any_project
 - ansible-playbook -i inventory playbook.yml

##### EXPECTED RESULTS
I expect either a "make fetch_modules", either the modules being packaged in the tarball (preferred), either another method to fetch modules being documented in the README.

##### ACTUAL RESULTS
```
ERROR! The requested action was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem.
```

**Comment by bcoca** [comment]
we do not use github for release tarballs, use http://releases.ansible.com/ansible/

**Comment by JulienPalard** [comment]
https://github.com/ansible/ansible/releases? Should be removed probably?

**Comment by bcoca** [comment]
we've tried
