### ISSUE TITLE
Anisble v2 git submodules???

### ISSUE THREAD

**Issue by nhojpatrick** [ansible/ansible#19496]
I'm trying to fix the macports ansible installation as it's currently failing with SSL issue.

Does anisble currently use submodules?

The mac port has "git submodule update --init" but I've tried cloning ansible and doing git submodule status and also do a clone with --recursive and no submodules appear.

Did ansible previous use submodules?
Do some of the ansible git repo's use submodules? does ansible/ansible?

**Comment by gundalow** [comment]
Between versions 1.8 and 2.2 inclusive we used gut sub modules. Devel aka 2.3 now uses one consolidated repo. 

Previously the modules were in lib/ansible/modules/{core, extras} 
Now they are directly in  lib/ansible/modules. 

1) Are any steps failing, or were you just expecting one of the git commands to show it had downloaded some submodules? 

2) Which document are you following? 

needs_info

**Comment by gundalow** [comment]
Between versions 1.8 and 2.2 inclusive we used gut sub modules. Devel aka 2.3 now uses one consolidated repo. 

Previously the modules were in lib/ansible/modules/{core, extras} 
Now they are directly in  lib/ansible/modules. 

1) Are any steps failing, or were you just expecting one of the git commands to show it had downloaded some submodules? 

2) Which document are you following? 

needs_info

**Comment by nhojpatrick** [comment]
I'm following the github Portfile and trying to understand what it does and how it interacts with the ansible repo. https://github.com/macports/macports-ports/blob/master/sysutils/ansible/Portfile

The mac port git clone command appear to be failing due to an ssl issue. I feel like I'm piggy in the middle as they are saying it's an issue because ansible is using submodules but when I clone ansible I can't find any submodules. So it looks like no one is using ansible via macports but I would like to.

**Comment by nhojpatrick** [comment]
Cheers for details about submodule's. Managed to finally fix the issue, and able to install ansible using mac ports. Appears to be an old/invalid setting several years and/or releases ago that added ```macportsuser root``` into ```/opt/local/etc/macports/macports.conf```.
