### ISSUE TITLE
running ansible dynamic inventory on aws 

### ISSUE THREAD

**Issue by asmksf** [ansible/ansible#19499]
##### ISSUE TYPE

 - Bug Report
 

##### COMPONENT NAME

/etc/ansible/ec2.py

##### ANSIBLE VERSION

```
ansible --version
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
remote_user = root
#remote_user = ubuntu

##### OS / ENVIRONMENT
cat /etc/issue
Amazon Linux AMI release 2016.09
Kernel \r on an \m

##### SUMMARY

i am configuring ansible for our aws environment. brief about our setup, we have 30 + vpcs with 100 s of hosts and in daily operations , we use ssh proxy i.e from ssh (mac)--> to jumpbox --> bastion -- > destination server as a abc-user.
i installed ansible on one of ec2 and created the dynamic inventory file using /etc/ansible/ec2.py.
but i cant ssh to any node. 

ansible -m ping all
 [WARNING]: provided hosts list is empty, only localhost is available

 [WARNING]: No hosts matched, nothing to do

ls -l hosts
-rw-r--r-- 1 root root 1331374 Dec 17 00:32 hosts 

##### EXPECTED RESULTS

 ping all the servers in our account.
please let me know if any security group or pem keys file used for each vpc.

**Comment by alikins** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

 This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.
