### ISSUE TITLE
OS X client support

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#195]
make sure /usr/bin/ansible and /usr/bin/ansible are easy to install on OS X and provide install instructions

may require some minor changes, maybe not.

**Comment by sfermigier** [comment]
I'd rather have the executable installable in whatever place you want (including $HOME/bin, /usr/local/bin or $HOMEBREW/bin for those who use Homebrew).

Same for the ansible.hosts file. I'd rather have it in $HOME/.ansible/hosts (for instance) than /etc/

Same for he playbooks or other supporting files. I'd rather have them in $ANSIBLE_HOME/playbooks (with ANSIBLE_HOME set in my .profile) than /usr/share/ansible.

Actually, this comment doesn't apply just to Mac OS, but to Linux as well.

**Comment by mpdehaan** [comment]
You can pick where you put the installation with PATH.

You can already pick where you use the host file with -i or the environment variable ANSIBLE_HOSTS. 

Playbooks don't have any path at all configured.

**Comment by skinp** [comment]
I also have noticed the hardcoded path for playbooks made it hard to use ansible in virtualenv...

**Comment by mpdehaan** [comment]
what do you mean?

there is no hardcoded path in ansible-playbook, playbooks are always specified by path.

You may mean the library path, which is also NOT hard coded, you can specify that by environment variable or command line flags

anyway, this is moving along on the devel branch, some changes to handle md5 vs md5sum on OS X clients (another ticket) are pending

**Comment by mpdehaan** [comment]
seems like this is closable at least out of checkout now, if someone wants to make a proper homebrew package (or whatever) let me know details.

**Comment by brianm** [comment]
the install tries to hardcode modules into /usr/share/ansible which is not really ideal.

**Comment by mpdehaan** [comment]
You can use --module-path to specify paths or include modules in a ./library file relative to your playbook or can set the module path in the config file, so you have lots of options.

**Comment by kelbyers** [comment]
Using --module-path is fine for running ansible, but the setup.py to install ansible ignores the --prefix option for some of the files, and tries to install them under /usr/share.

For example, running the following command (under virtualenv) as non-privileged, I get errors:

```
$ python setup.py install --record installed_files.txt --prefix /usr/local
.
.
.
running install_scripts
copying build/scripts-2.6/ansible -> /usr/local/bin
copying build/scripts-2.6/ansible-playbook -> /usr/local/bin
copying build/scripts-2.6/ansible-pull -> /usr/local/bin
changing mode of /usr/local/bin/ansible to 755
changing mode of /usr/local/bin/ansible-playbook to 755
changing mode of /usr/local/bin/ansible-pull to 755
running install_data
creating /usr/share/ansible
error: could not create '/usr/share/ansible': Permission denied
```

If I run setup.py with the --home option, I get the same error, where it tries to run install_data using /usr/share/ansible. I see this on both the release-0.8 and devel branches.

**Comment by brianm** [comment]
Right, I am more concerned with the install time -- I really don't want to splat anything into /usr/share that is not under control of my package manager.

**Comment by esclapes** [comment]
Just opened a new issue related to a homebrew formula for ansible: #1742
