### ISSUE TITLE
Ansible 2.2 ignores homebrew installed python

### ISSUE THREAD

**Issue by darkn3rd** [ansible/ansible#19507]
#### ISSUE TYPE

    Bug Report

#### COMPONENT NAME

all (docker_container, shell, command)

#### ANSIBLE VERSION

ansible 2.2.0.0

#### OS / ENVIRONMENT

Mac OS X "El Capitan"
```
docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

#### SUMMARY

Ansible uses Mac OS X "El Capitan" system python3, not python in $PATH or that installed python.

#### STEPS TO REPRODUCE
Install Python 2, Python 3, Ansible:
```
brew install python
pip install --upgrade pip setuptools
brew install python3
pip3 install --upgrade pip setuptools wheel
sudo -H pip install ansible
cat <<-PLAYBOOK > hello.yml
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Hello server
      shell: echo "Hello"

PLAYBOOK
ansible-playbook hello.yml
```

#### EXPECTED RESULTS

Python3 would be picked up from local path and use HomeBrew installed user python, not system-wide python that has no installed dependent libraries:

```
ls -l /usr/local/opt/python3/bin/python3
lrwxr-xr-x  1 joaquin  admin  55 Jun 25 14:38 /usr/local/opt/python3/bin/python3 -> ../Frameworks/Python.framework/Versions/3.5/bin/python3
```

Also, I tried it again with `export PYTHONPATH=/usr/local/lib/python3.5/site-package/`, but this was ignored as well.

#### ACTUAL RESULTS

```
$ ansible-playbook -vvv hello.yml
No config file found; using defaults
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: hello.yml ************************************************************
1 plays in hello.yml

PLAY [localhost] ***************************************************************

TASK [Hello server] ************************************************************
task path: /Users/joaquin/projarea/wordpress-exp/container/ansible/hello.yml:5
Using module file /usr/local/lib/python3.5/site-packages/ansible/modules/core/commands/command.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: joaquin
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1482143337.670153-23437391495252 `" && echo ansible-tmp-1482143337.670153-23437391495252="` echo $HOME/.ansible/tmp/ansible-tmp-1482143337.670153-23437391495252 `" ) && sleep 0'
<127.0.0.1> PUT /var/folders/79/4dttv20s6p30d78_yqmr3jjh0000gn/T/tmp1der1wbo TO /Users/joaquin/.ansible/tmp/ansible-tmp-1482143337.670153-23437391495252/command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/joaquin/.ansible/tmp/ansible-tmp-1482143337.670153-23437391495252/ /Users/joaquin/.ansible/tmp/ansible-tmp-1482143337.670153-23437391495252/command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python3/bin/python3.5 /Users/joaquin/.ansible/tmp/ansible-tmp-1482143337.670153-23437391495252/command.py; rm -rf "/Users/joaquin/.ansible/tmp/ansible-tmp-1482143337.670153-23437391495252/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true,
    "cmd": "echo \"Hello\"",
    "delta": "0:00:00.004077",
    "end": "2016-12-19 02:28:57.908638",
    "invocation": {
        "module_args": {
            "_raw_params": "echo \"Hello\"",
            "_uses_shell": true,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "warn": true
        },
        "module_name": "command"
    },
    "rc": 0,
    "start": "2016-12-19 02:28:57.904561",
    "stderr": "",
    "stdout": "Hello",
    "stdout_lines": [
        "Hello"
    ],
    "warnings": []
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```

**Comment by alikins** [comment]
What does '/usr/bin/env python' find?  

and/or, what interpreter is the 'ansible-playbook' script use in it's #! line?

**Comment by alikins** [comment]
Is /usr/local/opt/python3/bin/python3 the homebrew python or the system python?

```
TASK [Hello server] ************************************************************
task path: /Users/joaquin/projarea/wordpress-exp/container/ansible/hello.yml:5
Using module file /usr/local/lib/python3.5/site-packages/ansible/modules/core/commands/command.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: joaquin
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1482143337.670153-23437391495252 `" && echo ansible-tmp-1482143337.670153-23437391495252="` echo $HOME/.ansible/tmp/ansible-tmp-1482143337.670153-23437391495252 `" ) && sleep 0'
<127.0.0.1> PUT /var/folders/79/4dttv20s6p30d78_yqmr3jjh0000gn/T/tmp1der1wbo TO /Users/joaquin/.ansible/tmp/ansible-tmp-1482143337.670153-23437391495252/command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/joaquin/.ansible/tmp/ansible-tmp-1482143337.670153-23437391495252/ /Users/joaquin/.ansible/tmp/ansible-tmp-1482143337.670153-23437391495252/command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python3/bin/python3.5 /Users/joaquin/.ansible/tmp/ansible-tmp-1482143337.670153-23437391495252/command.py; rm -rf "/Users/joaquin/.ansible/tmp/ansible-tmp-1482143337.670153-23437391495252/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
```

This looks ok,but note that the python selected by 'ansible-playbook' may be different than the one used on remote clients to run the module  (although the client in this case is localhost, if the PATH or PYTHONPATH end different, it could select different python versions)

**Comment by darkn3rd** [comment]
The default `python` (and `/usr/bin/env python` is brew python2 `/usr/local/bin/python`.  There is brew python3 installed as well.  After doing a `pip3 install --upgrade pip setuptools wheel`, the default `pip` is no longer pointing to pip2, but to pip3.

For `/usr/local/opt/python3/bin/python3`, this points to `../Frameworks/Python.framework/Versions/3.5/bin/python3`

**Comment by sivel** [comment]
I am slightly confused.  It does indeed appear that ansible is using python3.5 as installed via homebrew:

```
<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python3/bin/python3.5 ...
```

What specifically is the problem?

**Comment by abadger** [comment]
needs_info

**Comment by darkn3rd** [comment]
This python `/usr/local/opt/python3/bin/python3`, is the native Mac Python.  It's a symlink that points to `../Frameworks/Python.framework/Versions/3.5/bin/python3`.  I am not sure how or why this happens.

As for pip using pip3 and not pip2, this could be useful for documentation, that upgrading pip3 libraries can cause problems for your future ansible installation.  I don't know why `pip3 install --upgrade pip` on Mac OS X changes the symlink of `pip` to point to `pip3`.

**Comment by sivel** [comment]
Mac does not ship anything in `/usr/local`, so whatever has installed `/usr/local/opt/python3/bin/python3` is not Mac native.  

That symlink would refer to:

```
/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/bin/python3
```

Mac native Frameworks are installed in `/System/Library/Frameworks`

So far I am not sure what is the homebrew python that you expect to be used.  You have listed a number of commands, but nothing specific about paths, other than the path of the python3 binary in `/usr/local`.

You have done a `brew install python3`, however I don't have anything that tells me what the path of that python3 is, and it's associated pip3.  It's possible that your PATH is always choosing the python3 path that you have referenced so far.

So far it seems like you have a bunch of mixed up paths, and aren't sure which is which, and assuming they are certain things.

Ansible, by default, with `localhost` ***not*** listed in inventory, will assign `ansible_python_interpeter` to the python that was used to invoke ansible.  I would check the shebang of your ansible playbook to confirm what this is:

```
head -1 $(which ansible-playbook)
```

If you want ansible to utilize a different python interpreter, you can ensure that you install with the proper pip, or utilize `ansible_python_interpreter` to explicitly define it.

**Comment by abadger** [comment]
Closing this as it's not a code problem within ansible but a matter of installing ansible on the specific machine using the correct versions of tools on that machine.
