### ISSUE TITLE
service using systemd on Ubuntu 14.04

### ISSUE THREAD

**Issue by bryanlarsen** [ansible/ansible#19516]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
service

##### ANSIBLE VERSION
```
2.2.0.0
```

##### CONFIGURATION
```
piplining = True
allow_world_readable_tmpfiles = True
```

##### OS / ENVIRONMENT
Ubuntu 14.04.5 inside vagrant-lxc.    Kernel 4.4.0-43-generic.   Ansible running locally.

##### SUMMARY

`service: name=nginx state=started` fails with

Failed to get the service status 'nginx': org.freedesktop.DBus.Error.FileNotFound \"No such file or directory\"

`service: name=nginx state=started pattern=nginx` fails with

 [WARNING]: Ignoring "pattern" as it is not used in "systemd" and then the above error.

##### STEPS TO REPRODUCE

I'm still working on a reproduction test case.  I've got very similar environments that don't exhibit the problem, so it seems to be something subtle.   I'm posting early in case it seems familiar and somebody can point me in the right direction.

Right now I assume the problem is that it's trying to use systemd rather than upstart.   Please tell me if I'm looking in the wrong place, thanks.

```yaml
service: name=nginx state=started
```

##### ACTUAL RESULTS

```
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/system/systemd.py
<default> ESTABLISH LOCAL CONNECTION FOR USER: root
<default> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
fatal: [default]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "daemon_reload": false, 
            "enabled": null, 
            "masked": null, 
            "name": "nginx", 
            "state": "started", 
            "user": false
        }
    }, 
    "msg": "Failed to get the service status 'nginx': org.freedesktop.DBus.Error.FileNotFound \"No such file or directory\""
}

```

**Comment by bryanlarsen** [comment]
Yes, it seems that systemd was installed.   If I remove it by installing systemd-shim, the problem goes away.

**Comment by alikins** [comment]
Is this the same issue as https://github.com/ansible/ansible/issues/19030 ?

**Comment by bryanlarsen** [comment]
Dupe of https://github.com/ansible/ansible/issues/19030
