### ISSUE TITLE
[Question] Deploy application on a newly created AWS instance

### ISSUE THREAD

**Issue by novistuff** [ansible/ansible#19526]
I am creating an Ansible playbook that has two roles: one role that creates an AWS instance (from a pre-made AMI which includes Ansible), then another role that deploys Sonatype Nexus into that instance. I've tested the roles separately (and locally) to make sure they're working fine and they work as expected, however, my problem is figuring out how to deploy Nexus into that newly created instance.

Is my approach wrong (having two separate roles for this)? I need some guidance as I'm new to Ansible.

Thanks,

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
