### ISSUE TITLE
No Module named markusafe but it is installed

### ISSUE THREAD

**Issue by StL-Jim** [ansible/ansible#19561]
Running latest ansible from git
[me@myhost ansible]$ git status
# On branch devel
--------------------
# Source Ansible
[me@myhost ansible]$ source ./ansible/hacking/env-setup

running egg_info
creating lib/ansible.egg-info
writing requirements to lib/ansible.egg-info/requires.txt
writing lib/ansible.egg-info/PKG-INFO
writing top-level names to lib/ansible.egg-info/top_level.txt
writing dependency_links to lib/ansible.egg-info/dependency_links.txt
writing requirements to lib/ansible.egg-info/requires.txt
writing lib/ansible.egg-info/PKG-INFO
writing top-level names to lib/ansible.egg-info/top_level.txt
writing dependency_links to lib/ansible.egg-info/dependency_links.txt
writing manifest file 'lib/ansible.egg-info/SOURCES.txt'
reading manifest file 'lib/ansible.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'v2'
no previously-included directories found matching 'docsite'
no previously-included directories found matching 'ticket_stubs'
no previously-included directories found matching 'packaging'
no previously-included directories found matching 'test'
no previously-included directories found matching 'hacking'
warning: no previously-included files found matching 'lib/ansible/modules/core/.git*'
warning: no previously-included files found matching 'lib/ansible/modules/extras/.git*'
no previously-included directories found matching 'lib/ansible/modules/core/.git'
no previously-included directories found matching 'lib/ansible/modules/extras/.git'
writing manifest file 'lib/ansible.egg-info/SOURCES.txt'

Setting up Ansible to run out of checkout...

PATH=/home/jimm/ansible/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin
PYTHONPATH=/home/jimm/ansible/lib:
MANPATH=/home/jimm/ansible/docs/man:

Remember, you may wish to specify your host file with -i

Done!

-------------------
[me@myhost ansible]$ ansible-playbook 
/home/me/ansible/bin/ansible-playbook:88: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  msg = e.message
ERROR! Unexpected Exception: No module named markupsafe
the full traceback was:

Traceback (most recent call last):
  File "/home/jimm/ansible/bin/ansible-playbook", line 78, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/home/jimm/ansible/lib/ansible/cli/playbook.py", line 30, in <module>
    from ansible.executor.playbook_executor import PlaybookExecutor
  File "/home/jimm/ansible/lib/ansible/executor/playbook_executor.py", line 25, in <module>
    from ansible.executor.task_queue_manager import TaskQueueManager
  File "/home/jimm/ansible/lib/ansible/executor/task_queue_manager.py", line 29, in <module>
    from ansible.executor.play_iterator import PlayIterator
  File "/home/jimm/ansible/lib/ansible/executor/play_iterator.py", line 27, in <module>
    from ansible.playbook.block import Block
  File "/home/jimm/ansible/lib/ansible/playbook/__init__.py", line 27, in <module>
    from ansible.playbook.play import Play
  File "/home/jimm/ansible/lib/ansible/playbook/play.py", line 28, in <module>
    from ansible.playbook.base import Base
  File "/home/jimm/ansible/lib/ansible/playbook/base.py", line 29, in <module>
    from jinja2.exceptions import UndefinedError
  File "/usr/lib/python2.6/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/lib/python2.6/site-packages/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "/usr/lib/python2.6/site-packages/jinja2/nodes.py", line 18, in <module>
    from jinja2.utils import Markup
  File "/usr/lib/python2.6/site-packages/jinja2/utils.py", line 520, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: No module named markupsafe

-------------------------------
[me@myhost ansible]$ python
Python 2.6.6 (r266:84292, May 22 2015, 08:34:51) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
-------------------------
[me@myhost ansible]$ sudo pip install markupsafe
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Requirement already satisfied: markupsafe in /usr/lib64/python2.6/site-packages

[me@myhost ansible]$ sudo pip2 install markupsafe
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Requirement already satisfied: markupsafe in /usr/lib64/python2.6/site-packages

[me@myhost ansible]$ sudo pip2.6 install markupsafe
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Requirement already satisfied: markupsafe in /usr/lib64/python2.6/site-packages

[me@myhost ansible]$ sudo pip2.6 install markupsafe
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Requirement already satisfied: markupsafe in /usr/lib64/python2.6/site-packages

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case, this is an issue with your version of pip not installing the dependencies of dependencies, in this case jinja2.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
