### ISSUE TITLE
dict data from playbook get converted to string in Ansible 2.x

### ISSUE THREAD

**Issue by vnitinv** [ansible/ansible#19589]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
AnsibleModule->argument_spec

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### CONFIGURATION
NA

##### OS / ENVIRONMENT
r$ uname -a
Darwin xxxx-xxx 14.5.0 Darwin Kernel Version 14.5.0

##### SUMMARY
In the earlier version of ansible (tested on 2.0) if we provide data (gets consumed by user defined module) something like below used to give dictionary. {'x': 'E000185416';  'y': 'E000199986'} 
```yaml
        kwargs:
          x: "E000185416"
          y: "E000199986"
```
with my module code having
```python
    kwargs=dict(required=False, default=None),
```
but with 2.2 this comes as string (dict inside string). **"{'x': 'E000185416';  'y': 'E000199986'}"**
Is this intended change or a bug?

I can convert my python code above to 
```python
    kwargs=dict(required=False, default=None, type=dict),
```
but due to some backward comaptibility issue we cant. 

https://github.com/Juniper/ansible-junos-stdlib/pull/196

##### EXPECTED RESULTS
dictionary

##### ACTUAL RESULTS
string of dictionary

**Comment by nitzmahone** [comment]
Suspect you're looking for `type=raw` (which was the default 1.x behavior IIRC), then inspect what you get in the module code (dict/string/etc) and handle as necessary. Does that get you where you need to be?
