### ISSUE TITLE
Megabytes vs. Mebibytes a.k.a. IEC vs. SI vs. common usage a.k.a the great memory unit clusterfsck

### ISSUE THREAD

**Issue by iangreenleaf** [ansible/ansible#19583]
##### ISSUE TYPE
 - I gotta be honest, not sure how this classifies, could be a little of each category

##### COMPONENT NAME
Math filters `human_to_bytes` and `human_readable`

##### ANSIBLE VERSION
```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I started out innocently updating someone's galaxy role and stumbled into the endless rabbit hole of size prefixes in computing (kilo-/mega-/giga-/tera-), and now I'm worried about Ansible's treatment of these prefixes.

##### STEPS TO REPRODUCE
A brief history of the problem: computers measure bytes with two different systems:

1. Kilobytes/Megabytes: Base 10, so 1 KB = 1000 bytes, 1 MB = 1000 KB, etc. Sometimes referred to as the "SI" standard. Commonly abbreviated as KB/MB/GB.
2. Kibibytes/Mebibytes: Base 2, so 1 KiB = 1024 bytes, 1 MiB = 1024 KiB, etc. Sometimes referred to as the "IEC" standard. Most precisely abbreviated as KiB/MiB/GiB, but also commonly abbreviated as Ki/Mi/Gi or K/M/G. Even worse, also often abbreviated as KB/MB/GB and used indistinguishably from the base-10 prefixes.

[More info from Wikipedia](https://en.wikipedia.org/wiki/Binary_prefix). Needless to say this has been a source of grief in computing for a long time. AFAIK, currently the IEC standard has won out in most areas, with the couple notable exceptions being how hard drive capacity is advertised and how network throughput is sometimes measured. This is why your "2 TB" hard drive is only 1.8 TiB once you plug it in.

Here's what worries me: right now Ansible's tools use KB/MB/GB prefixes, which are probably the most ambiguous and likely to cause confusion.

```sh
$ ansible -m debug -a "msg={{'2000'|human_readable(unit='K')}}" localhost
localhost | SUCCESS => {
    "msg": "1.95 KB"
}
```

```sh
$ ansible -m debug -a "msg={{'1K'|human_to_bytes}}" localhost
localhost | SUCCESS => {
    "msg": "1024"
}

$ ansible -m debug -a "msg={{'1KB'|human_to_bytes}}" localhost
localhost | SUCCESS => {
    "msg": "1024"
}

$ ansible -m debug -a "msg={{'1KiB'|human_to_bytes}}" localhost
localhost | FAILED! => {
    "failed": true, 
    "msg": "human_to_bytes() can't interpret following string: 1KiB"
}
```

This is not consistent with, for example, how `dd` reads input—it treats "KB" as 1000 bytes.

##### EXPECTED RESULTS
It's a tough judgment call as to what *should* happen. Here is my suggestion:

* Output should use K/M/G. This is the most common practice among Unix tools like `ls -h` and `df -h` that report IEC numbers.
* Parsing should accept K/M/G, Ki/Mi/Gi, and KiB/MiB/GiB and treat these as IEC prefixes.
* Parsing should either accept KB/MB/GB and treat them as SI prefixes, or it should reject these formats for ambiguity, or it should take an option to the filter to specify which to use.

**Comment by mkuipers** [comment]
> the great memory unit clusterfsck 

😂

**Comment by iangreenleaf** [comment]
@s-hertel this issue got tagged with `has_pr` but it doesn't have one, I think that was an accident? It would be nice if someone on the core team could weigh in on whether a change to the prefixes would be welcomed, and how "KB" should be handled on input. These would be breaking changes, so I wouldn't want to charge ahead on a PR without someone willing to shepherd this to a release path.

**Comment by mkrizek** [comment]
@iangreenleaf bot identified https://github.com/kamaln7/ansible-swapfile/pull/13 as a PR that fixes this issue because it is mentioned there which is not correct in this case (sometimes that behavior is desired, for example, when a PR in a collection fixes an issue in this repository). That bot feature needs some work still :-)

Either way, this issue was labeled as `waiting_on_contributor`, its description reads "This would be accepted but there are no plans to actively work on it.". If you would like to work on this the best way is to add this issue on Core Team IRC meeting's agenda at https://github.com/ansible/community/issues/626 to discuss it further.

**Comment by rolandrc** [comment]
It would help if `human_to_bytes` would be changed to also accept KiB/MiB/GiB/etc. That doesn't fix the ambiguity issue in general but it does not change existing functionality and would allow me to explicitly specify where I want the base 2 values. It'd also be future proof in case the current behavior changes.
