### ISSUE TITLE
ansible-playbook --list-hosts shows groups

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#1958]
When I do --list-hosts, ansible is showing some groups as if they were hosts:

/etc/ansible/hosts:

```
[webservers]
production
staging
testing

[production]
foo.production.com

[staging]
foo.staging.com

[testing]
foo.testing.com
```

ping.yaml:

```

---
- hosts: all
  tasks:
    - action: ping

$ ansible-playbook ping.yaml --list-hosts
playbook: ping.yaml
  hosts in play 1 (unnamed): #6
    foo.production.com
    foo.staging.com
    foo.testing.com
    production
    staging
    testing
```

ping-webservers.yaml

```

---
- hosts: webservers
  tasks:
    - action: ping

$ ansible-playbook ping-webservers.yaml --list-hosts
playbook: ping.yaml
  hosts in play 1 (unnamed): #6
    production
    staging
    testing
```

**Comment by dhozac** [comment]
First line of your inventory should read [webservers:children]. That should fix the problem.

**Comment by lorin** [comment]
Yeah, that does it. So, under what circumstances do I need to append `:children` to a group name?

**Comment by dhozac** [comment]
As per http://ansible.cc/docs/patterns.html#groups-of-groups-and-group-variables you need that whenever you're including groups in a group. That is how you do it. [foo] is for nodes, [foo:vars] is for vars, [foo:children] is for groups.
