### ISSUE TITLE
S3 module: GetObject needs ListBucket permissions

### ISSUE THREAD

**Issue by mgla** [ansible/ansible#19601]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

S3 module

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Using the S3 module with boto installed. Instance has a AWS IAM Role attached.

##### OS / ENVIRONMENT

Running Amazon Linux AMI 2016.09.0 (HVM), SSD Volume Type

##### SUMMARY
S3 module needs unnecessary permissions

##### STEPS TO REPRODUCE

1. Create a s3 bucket "mybucket"
2. Create an EC2 instance with an attached IAM Role.
3. Attach a policy to the S3 bucket that allows the IAM role only GetObject, but not ListBucket
4. Install ansible + boto on the ec2 instance.

```yaml
---
- hosts: localhost
  remote_user: ec2-user
  tasks:
    - name: download ec2.py from s3
      s3:
        bucket: mybucket
        object: /ec2.py
        dest: /tmp/ec2.py
        mode: get
```

##### EXPECTED RESULTS

File is downloaded from S3.

##### ACTUAL RESULTS

File can not be downloaded from S3. Message "Source bucket can not be found" is echoed instead.

```
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "bucket": "mybucket", 
            "dest": "/tmp/ec2.py", 
            "ec2_url": null, 
            "encrypt": true, 
            "expiry": "600", 
            "headers": null, 
            "marker": null, 
            "max_keys": "1000", 
            "metadata": null, 
            "mode": "get", 
            "object": "/ec2.py", 
            "overwrite": "always", 
            "permission": [
                "private"
            ], 
            "prefix": null, 
            "profile": null, 
            "region": null, 
            "retries": 0, 
            "rgw": false, 
            "s3_url": null, 
            "security_token": null, 
            "src": null, 
            "validate_certs": true, 
            "version": null
        }, 
        "module_name": "s3"
    }, 
    "msg": "Source bucket cannot be found"
}
```
Downloading the file using the AWS CLI tools works fine.
After toying around for a few hours, and reiterating all steps several times with small changes, I found the issue: The S3 module with get only works if the IAM Role has ListBucket permissions on the bucket in addition to the GetObject permissions.

I have:

- Verified my boto version is new enough (boto 2.42)
- Verified the EC2 instance role has the correct permissions (aws s3 cp s3://mybucket/ec2.py /tmp/ec2.py works just fine)
- Verified the EC2 instance credentials are available through curl http://169.254.169.254/latest/meta-data/iam/security-credentials/s3access

The error message is not very helpful, and is actually wrong - the bucket can be found with the AWS S3 api.

Suggestion: Do not require ListBucket permissions ob bucket for GetObject operation, or at least show a correct error message.

**Comment by alexlo03** [comment]
99% sure it is due to https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/s3.py#L271 which I think ought be `bucket = s3.lookup(bucket, validate=False)` - (validate=true, the default, does a HEAD of the bucket per https://github.com/boto/boto/blob/develop/boto/s3/connection.py#L468 )

I'll try to fix soon but would want to make some tests...
