### ISSUE TITLE
|failed expects a dictionary when using "when"

### ISSUE THREAD

**Issue by BruceZu** [ansible/ansible#19628]
##### ISSUE TYPE
 
 - Bug Report
 - Feature Idea
 

##### ANSIBLE VERSION

```
[root@k8s-09 deploy-on-k8s]# ansible --version
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
[root@k8s-09 deploy-on-k8s]#
```

##### OS / ENVIRONMENT
CentOS 7

##### SUMMARY
I am not sure the root reason. 
"namespace" and "gitlab_deploy_suffix_name" are vars and work well at other places.
I assume 'register' and 'when' support vars too.
I do not know what is the meaning in the error message: 
# The error was: |failed expects a dictionary

##### STEPS TO REPRODUCE
 
```yaml

 32 # Service
 33 - name: check "{{ gitlab_deploy_suffix_name }}" svc exist or not
 34   command: "kubctl get svc {{ [namespace, gitlab_deploy_suffix_name]|join('-') }} --namespace={{ namespace }}"
 35   register: "{{ [namespace, gitlab_deploy_suffix_name]|join('-') }}_exists"
 36   ignore_errors: True
 37
 38 - name: "create gitlab svc if it does not exist and its deployment exists or just created succeefully"
 39   shell: "notify to create {{ gitlab_deploy_suffix_name }} service"
 40   when:  "{{ [namespace, gitlab_deploy_suffix_name]|join('-') }}_exists|failed"
 41   ignore_errors: True
 42   notify: "create {{ gitlab_deploy_suffix_name }} service"
```

##### ACTUAL RESULTS
 
```
fatal: [k8s-09]: FAILED! => {"failed": true, "msg": "The conditional check '{{ [namespace, gitlab_deploy_suffix_name]|join('-') }}_exists|failed' failed. The error was: |failed expects a dictionary\n\nThe error appears to have been in '/root/temp-bruce/deploy-on-k8s/roles/k8s/tasks/main.yml': line 38, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"create gitlab svc if it does not exist and its deployment exists or just created succeefully\"\n  ^ here\n"}
```

**Comment by sivel** [comment]
This is due to the fact that you cannot use variables in `register` to create a new variable name.

You are literally creating a variable called `{{ [namespace, gitlab_deploy_suffix_name]|join('-') }}_exists`, not the result of that jinja2 expression.

You must provide an explicit static variable name with `register`. Such as `register: my_var`

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by BruceZu** [comment]
Hi Sivel, 
Thank you for your help.
I got it.   `register` does not support variable. 
Is there plan to enable `register`  to support variable? This would be a good feature to help make duplicated work in a loop.

**Comment by sivel** [comment]
There are no plans to do so, as we believe variable variables to be harmful and difficult to debug.

**Comment by BruceZu** [comment]
By the way may I know if `notify` support vars?  
Thank you!

**Comment by BruceZu** [comment]
test and find` notify` support vars
```
- name: "create {{ gitlab_deploy_suffix_name }} svc if it does not exist when its deployment exists or just created succeefully"
  shell: "msg='notify to create {{ gitlab_deploy_suffix_name }} service'"
  notify: "create {{ gitlab_deploy_suffix_name }} service"
  when: (( gitlab_exist|succeeded ) or ( gitlab_created|succeeded )) and ( gitlab_svc_exists|failed )
  ignore_errors: True
```

only `register ` is left :)

**Comment by damusix** [comment]
+1 This would nice
