### ISSUE TITLE
module command cuts parameter

### ISSUE THREAD

**Issue by computersalat** [ansible/ansible#19625]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module/command

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
inventories/setup/hosts.yml
```
s02-otrs ansible_connection=ssh ansible_ssh_user=root ansible_ssh_pass=PassWord
```

##### OS / ENVIRONMENT
Linux / Linux

##### SUMMARY
trying to 'copy' the initial ssh-key but module **command** is cutting _.pub_ from the keyfile and hence does not find the key file

##### STEPS TO REPRODUCE

**_roles/setup/tasks/main.yaml_**
```
- name: Install sshkey
  local_action: command /usr/bin/sshpass -pPassWord /usr/bin/ssh-copy-id -i /home/admin/.ssh/admin.pub -o StrictHostKeyChecking=no root@{{ ansible_fqdn }}
  tags: setup
```

##### EXPECTED RESULTS
module command should read in from the given command:
```
/home/admin/.ssh/admin.pub
```

##### ACTUAL RESULTS
module command tries to readin from given command:
```
/home/admin/.ssh/admin
```
but that does not exist. When I create a symlink admin -> admin.pub it works

```
fatal: [s02-otrs -> localhost]: FAILED! => {
    "changed": true, 
    "cmd": [
        "/usr/bin/sshpass", 
        "-pPassWord", 
        "/usr/bin/ssh-copy-id", 
        "-i", 
        "/home/admin/.ssh/admin.pub", 
        "-o", 
        "StrictHostKeyChecking=no", 
        "root@s02-otrs.xxxxxxx"
    ], 
    "delta": "0:00:00.010832", 
    "end": "2016-12-21 21:03:35.432909", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "_raw_params": "/usr/bin/sshpass -pPassWord /usr/bin/ssh-copy-id -i /home/admin/.ssh/admin.pub -o StrictHostKeyChecking=no root@s02-otrs.xxxxxx", 
            "_uses_shell": false, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }, 
        "module_name": "command"
    }, 
    "rc": 1, 
    "start": "2016-12-21 21:03:35.422077", 
    "stderr": "", 
    "stdout": "\n/usr/bin/ssh-copy-id: ERROR: failed to open ID file '/home/admin/.ssh/admin': Datei oder Verzeichnis nicht gefunden", 
    "stdout_lines": [
        "", 
        "/usr/bin/ssh-copy-id: ERROR: failed to open ID file '/home/admin/.ssh/admin': Datei oder Verzeichnis nicht gefunden"
    ], 
    "warnings": []
}
```

**Comment by georgepsarakis** [comment]
This does not seem to be an issue with the `command` module. If you notice the `"cmd"` key in the output, you will see that it has parsed the command correctly.

Perhaps the problem is with the usage of [ssh-copy-id](http://serverfault.com/questions/807210/why-ssh-copy-id-requires-private-key-file).

**Comment by abadger** [comment]
Agreed. The ansible output is showing ansible doing the right thing and that serverfault discussion shows that ssh-copy-id is what's trying to access what it thinks is the private key to go with the pubic key that was specified.
