### ISSUE TITLE
Documentation - Windows Support page needs an update to show pykerberos

### ISSUE THREAD

**Issue by aaronk1** [ansible/ansible#19623]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME
Windows Support documentation https://github.com/ansible/ansible/blob/devel/docsite/rst/intro_windows.rst

##### ANSIBLE VERSION

```
2.2
```

##### SUMMARY

Documentation needs to show pypi installation of pykerberos package, not kerberos

##### STEPS TO REPRODUCE

```

pip install kerberos requests_kerberos

```

##### EXPECTED RESULTS

pip install pykerberos requests_kerberos

##### ACTUAL RESULTS

pip install kerberos requests_kerberos

```

```
@nitzmahone

**Comment by jhawkesworth** [comment]
@aaronk1 Can you advise what os, distribution and version you are using?  I think under some distros some of the dependencies are already available.  
I believe there are some doc re-writes in progress which should make it a clearer what is needed to be installed, but it would be useful to know what you are running on.

needs_info

**Comment by dagwieers** [comment]
I think this is fixed now: http://docs.ansible.com/ansible/intro_windows.html#kerberos
Can you confirm ?

**Comment by jhawkesworth** [comment]
I think pykerberos must be installed as result of installing requests-kerberos 
On all the machines I run I have both kerberos and pykerberos installed.
@aaronk1 can you confirm if following current instructions installs everything correctly?

**Comment by jhawkesworth** [comment]
no feedback from op, closing.
