### ISSUE TITLE
validate imposes a %s ; can't validate Apache config

### ISSUE THREAD

**Issue by jlecour** [ansible/ansible#19639]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
"files" modules: template, copy,…

##### ANSIBLE VERSION
```
ansible 2.0.2.0
```
The restriction is present in `master`.

##### SUMMARY
The `validate` argument on files modules fails if there is no `%s` passed.
It seems impossible to validate Apache configuration (which can't be executed with a filename).

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Validate is meant to run against the temporary file BEFORE it is put into place, that is what the '%s' is for, Ansible will substitute the temp file name there. Any other more complex validation should be done in a task, this option is not meant to cover all possible cases, just the simple one.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by jlecour** [comment]
Thank you for the clarification. I guess it could be better explained in the documentation, but the feature makes sense as it is.
