### ISSUE TITLE
Feature request - 'file' parameter for cron module

### ISSUE THREAD

**Issue by rhaido** [ansible/ansible#1964]
Hello!

Do you think, is it possible to add 'file' parameter to cron module with the following behaviour:
1. If this parameter is not specified, module works with the users' crontabs in /var/spool/cron like it does now.
2. If it specified and there is no state=absent, like
cron: name="check dirs" minute="0" hour="2,4" file="check_dirs.cron" job="ls -alh > /dev/null"
the file 'check_dirs.cron' with the properly generated cron job will be put in /etc/cron.d/ directory (at least on RHEL systems and Ubuntu).
so, the result will be the file like this:
$ cat /etc/cron.d/check_dirs.cron
# Ansible ...
0 2,4 \* \* \* root ls -llh >/dev/null
3. If state is 'absent' the file is deleted.

It would be really useful for system administrator to have such functionality - it will allow much more easier and more obvious cron job management.

Thank you in advance and have a good day!

**Comment by mpdehaan** [comment]
It seems to me in this case you could put this in with the template module.   That is what I would probably do in this case.

**Comment by rhaido** [comment]
Yeah, maybe you are right. From the other side, the proposed attribute would allow to control the cron jobs more 'naturally', and without need to maintain one more file. And, as a /etc/cron.d/ is now a part of standard cron functionality, the proposed attribute could be considered not as excessive, but as a standard and necessary component to cover the needs of a system administrator and funcionality of the cron daemon. Also, from cetain point of view, it's just simpler just to modify the playbook and then commit changes as a one/two actions, instead of several: modify the playbook, create the new file, put it under control version, etc, and then support it till the end of your life :)

Anyway, thank you for your attention.
