### ISSUE TITLE
Feature request : openSUSE zypper support

### ISSUE THREAD

**Issue by druonysus** [ansible/ansible#1965]
It would be great if there was support for openSUSE Linux and SUSE Linux Enterprise. I think the major thing that would be needed is a zypper module for installing packages.

**Comment by mpdehaan** [comment]
@jpmens has a bash module version here -- https://github.com/jpmens/ansible-zypp -- which if we converted to the modern 'AnsibleModuleCommon' Python code we could include in core, and I'd be happy to have it.

Something you may want to work on?

**Comment by jpmens** [comment]
Be advised that the shell module referenced is a pretty lousy hack, but it works on SLES 10 and 11. (SLES9 doesn't support zypper)

**Comment by mpdehaan** [comment]
Resolved per https://github.com/ansible/ansible/blob/devel/library/packaging/zypper
