### ISSUE TITLE
Variable ansible_host is undefined in hostvars when using inventory

### ISSUE THREAD

**Issue by valar999** [ansible/ansible#19704]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
variables

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

MacOS and Linux

##### SUMMARY

ansible_host variable is not accessible if set by host_vars/serv1 and 
inventory set to directory, i.e. hostfile = inventory
Everything works fine when hostfile = hosts (single file)

##### STEPS TO REPRODUCE

ansible.cfg:

```
[defaults]
hostfile = inventory
```
inventory/hosts:
```
[webservers]
serv1
```
host_vars/serv1:
```
ansible_host: 1.1.1.1
```

Running:
```
ansible serv1 -m debug -a "var=hostvars['serv1']['ansible_host']"
```

##### EXPECTED RESULTS

```
serv1 | SUCCESS => {
    "hostvars['serv1']['ansible_host']": "1.1.1.1"
}
```

##### ACTUAL RESULTS

```
serv1 | SUCCESS => {
    "hostvars['serv1']['ansible_host']": "VARIABLE IS NOT DEFINED!"
}
```

**Comment by bcoca** [comment]
can you write out the full file paths that you are using?

**Comment by valar999** [comment]
I make test case in /tmp/test
All files are here.
/tmp/test/ansible.cfg
/tmp/test/inventory/hosts 
/tmp/test/host_vars/serv1

6 січ. 2017 р. о 00:22 Brian Coca <notifications@github.com> написав(ла):

**Comment by sivel** [comment]
`host_vars` are read from 2 locations, either directly beside the inventory _file_ or directly beside the playbook file.  When running an ad-hoc command, there is no playbook file, so the `host_vars` directory must reside directly beside your `hosts` file.  So the paths would need to be:

```
/tmp/test/inventory/hosts
/tmp/test/inventory/host_vars/serv1
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
