### ISSUE TITLE
ansible expect not working for multiple prompt values

### ISSUE THREAD

**Issue by Git-Rajkumar** [ansible/ansible#19708]
I need to install nginx agent for openam using ansible.

while install the nginx_agent it asking **multiple question while run the script**,

         ************************************************************************
        Welcome to the OpenSSO Policy Agent for NGINX
        ************************************************************************

        Enter the URL where the OpenAM server is running.
        Please include the deployment URI also as shown below:
        (http://opensso.sample.com:58080/opensso)
        **OpenSSO server URL: sss**
        Enter the Agent profile name
        **Agent Profile Name: sss**
        Enter the password to be used for identifying the Agent.
        *THIS IS NOT PASSWORD FILE*
        **Agent Password:** 
        -----------------------------------------------
        SUMMARY OF YOUR RESPONSES
        -----------------------------------------------
        OpenSSO server URL : sss
        Agent Profile name : sss
        Agent Password:     sss
        Continue with Installation?
        [y/N]: y

so, i have use expect module in ansible:

    - expect:
        command: sh /opt/nginx_agent/bin/agentadmin.sh
        responses:
            OpenSSO server URL: "http://openam.test.mobi:8080/openam"
            Agent Profile Name: "nginx"
            Agent Password: "xxxxxx"
            \[y/N\]: "y" 

But, its **Continue with Installation?
        [y/N]:** 

takes, **OpenSSO server URL:** value see,

**Reference:**

         "stdout_lines": [
             "************************************************************************", 
             "Welcome to the OpenSSO Policy Agent for NGINX", 
             "************************************************************************", 
             "", 
             "Enter the URL where the OpenAM server is running.", 
             "Please include the deployment URI also as shown below:", 
             "(http://opensso.sample.com:58080/opensso)", 
             "OpenSSO server URL: Enter the Agent profile name", 
             "Agent Profile Name: Enter the password to be used for identifying the Agent.", 
             "*THIS IS NOT PASSWORD FILE*", 
             "Agent Password: ", 
             "-----------------------------------------------", 
             "SUMMARY OF YOUR RESPONSES", 
             "-----------------------------------------------", 
             "OpenSSO server URL : http://openam.test.mobi:8080/openam", 
             "Agent Profile name : nginx", 
             "Agent Password:     test.mobi2", 
             "Continue with Installation?", 
             "[y/N]: http://openam.test.mobi:8080/openam", 
             "xxxxx"
         ]

Suggest Me , what i miss in this Configuration. How to fix this

**Comment by nitzmahone** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
