### ISSUE TITLE
facts/dmi information is broken

### ISSUE THREAD

**Issue by ritzk** [ansible/ansible#19706]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

```
vim ./lib/ansible/module_utils/facts.py

1186     def get_dmi_facts(self):
1187         ''' learn dmi facts from system
1188 
1189         Try /sys first for dmi related facts.
1190         If that is not available, fall back to dmidecode executable '''
1191 
1192         if os.path.exists('/sys/devices/virtual/dmi/id/product_name'):
1193             # Use kernel DMI info, if available
...
1205             DMI_DICT = {
1206                     'bios_date': '/sys/devices/virtual/dmi/id/bios_date',
1207                     'bios_version': '/sys/devices/virtual/dmi/id/bios_version',
...
1216             for (key,path) in DMI_DICT.items():
1217                 data = get_file_content(path)
...
3683 def get_file_content(path, default=None, strip=True):
3684     data = default
3685     if os.path.exists(path) and os.access(path, os.R_OK):
3686         try:
3687             try:
3688                 datafile = open(path)
3689                 data = datafile.read()
```

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.2.0.0
  config file = /home/rkhadgar/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
Linux

##### SUMMARY
/sys file are readable only to root, and would need to be "gathered" using sudo

```
$ ll  /sys/devices/virtual/dmi/id/
...
-r--------. 1 root root 4096 Dec 28 09:12 product_serial
-r--------. 1 root root 4096 Dec 28 09:12 product_uuid
```

##### STEPS TO REPRODUCE
```
[user@system] ansible localhost -m setup 2>&1 | grep product_uuid
        "ansible_product_uuid": "NA", 
```

##### EXPECTED RESULTS
product uuid and other information

##### ACTUAL RESULTS
get_file_content should be able to retry reading as root

**Comment by abadger** [comment]
Wouldn't you need to invoke ansible like this?
```
$ ansible localhost -m setup --sudo -K 2>&1 | grep product_uuid
SUDO password: 
        "ansible_product_uuid": "7E47B281-5378-11CB-A58D-90754DE88092", 
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The fact gathering does 'best effort' if the user you gather facts as does not have access to those facts, you will get NA or empty facts. Ansible cannot escalate privileges unless you tell it to and it is unreasonable to expect it to do so, that is why I'm closing this ticket.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
