### ISSUE TITLE
Please improve missing LOOKUP(dig) error message

### ISSUE THREAD

**Issue by xenithorb** [ansible/ansible#19719]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

LOOKUP(dig)

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### SUMMARY

In using `lookup('dig')` in my playbooks, I've come to realize that neither `pip` or Fedora's packaging system install `python2-dns` or in pip - `dnspython` are installed as a dependency and the task fails with

```
$ ansible localhost -m debug -a var='lookup("dig","google.com")'
 [WARNING]: provided hosts list is empty, only localhost is available

localhost | FAILED! => {
    "failed": true,                                                                                                                                                 
    "msg": "Can't LOOKUP(dig): module dns.resolver is not installed"                                                                                                
}      
```
It may be obvious to a python developer how to resolve `dns.resolver` into a PyPI package name but it was not for me. Let me explain the gymnastics needed in order for a layperson to figure this out: Since I didn't really know what else to do, and know my packaging system better (DNF) than I do python, i used `dnf provides "*/dnf/resolver*"` to get the name of the package that I needed (`python2-dns`) -- full stop there if I'm using `ansible` from Fedora packages, and I filed [a bug with them](https://bugzilla.redhat.com/show_bug.cgi?id=1408936) to see if I could get them to include that as a package dependency.

In trying to bolster my supporting argument, I noticed that pip, which you control, also doesn't pull in said DNS depdendency, so I then had to figure out which one that would be. As a mostly non-python person, I know not how to go from `dns.resolver` to `dnspython` and the only way I could think to do it was rely on Fedora packages and `dnf info python2-dns` output in order to get more information about what that was (when I finally got the `dnspython` name)

##### STEPS TO REPRODUCE

1. Install ansible as normal, make sure you don't otherwise have a dependency that includes `dnspython` elsewhere. 
2. `ansible localhost -m debug -a var='lookup("dig","google.com")'`

##### EXPECTED RESULTS

1. Primary expected result is that it just works out of the box:
```
localhost | SUCCESS => {
    "lookup(\"dig\",\"google.com\")": "74.125.138.101,74.125.138.138,74.125.138.113,74.125.138.102,74.125.138.100,74.125.138.139"
}
```
2. Alternative expected result:
```
localhost | FAILED! => {
    "failed": true,                                                                                                                                                 
    "msg": "Can't LOOKUP(dig): module dns.resolver is not installed, please install 'dnspython' from PyPi or through your distrubutions package manager."                                                                                                
}          
```

The alternative result is the main focus of the ticket, only because I suspect that if you wanted to include `dnspython` as a dependency you would have already, so I'd at least like someone to "throw me a bone" and help me out with how to get it working quickly in the event that I don't have that module already installed. 

Tangentially, what had happened was that I never noticed this missing dependency because I had other things that pulled it into the system, and failed during a demo because it was missing. Yes I learned my lesson about testing on blank canvases beforehand, but chiefly dislike the way this was handled and presented to the user. 

##### ACTUAL RESULTS

```
localhost | FAILED! => {
    "failed": true,                                                                                                                                                 
    "msg": "Can't LOOKUP(dig): module dns.resolver is not installed"                                                                                                
} 
```

**Comment by georgepsarakis** [comment]
The dependency is clearly described with a warning in the documentation for lookups: http://docs.ansible.com/ansible/playbooks_lookups.html#the-dns-lookup-dig

A potential improvement would be to perhaps add to the error message, exactly what the warning states.

**Comment by xenithorb** [comment]
Yes I see that note now that you've pointed it out, but it also seems to be the only lookup that doesn't have a dependency included in ansible's PyPi package. 

I think it would be reasonable to include the message 
`"module dns.resolver (PyPi: dnspython) is not installed"` 
Which I think would be sufficient. 

Though, I wonder why that's the only lookup that seems to have an additional dependency that isn't being pulled in by pip. Why is that? It doesn't seem to be a very large library?

**Comment by georgepsarakis** [comment]
It is not necessary to install a Python package from PyPI. Some users prefer to use OS package managers only. For example in Ubuntu: https://launchpad.net/ubuntu/+source/dnspython

Perhaps the minimum required version should be included in the message though (this happens in module documentation, see [here](http://docs.ansible.com/ansible/docker_module.html#id3) for example).

My guess is that the instructions meant to simply state the you should add this dependency in your system **if and only if** you want to use the lookup. It is up to you to decide how the package will be installed.

I think it is far more flexible to provide users with the ability to select the dependencies they want to install, especially for applications with a large variety of functionality such as Ansible.

**Comment by xenithorb** [comment]
>I think it is far more flexible to provide users with the ability to select the dependencies they want to install, especially for applications with a large variety of functionality such as Ansible.

Ok that's fine, but then shouldn't Ansible look for these python dependencies BEFORE it runs the play?

The issue I have is that on _this particular error_ it doesn't occur until the point where it's called, and in my particular case left a very inconsistent state present. 

If the route is taken where ansible decides to install only the minimal set of dependencies, then I would really prefer if `ansible-playbook` told me of *ALL* the missing dependencies before it blows something up by not having what it needs. Or am I supposed to bake this into my role?

**Comment by georgepsarakis** [comment]
I understand your worry there. However, there are two things to be taken into account:
1. Idempotence: after fixing the missing dependency you should be able to re-run your playbook with no side-effects.
2. Playbooks are dynamic, so it is difficult to pre-analyze the dependencies in a generic manner:
```
- debug: msg="{{ lookup((my_dns_lookup | default('dig')), 'google.com') }}"
```

**Comment by xenithorb** [comment]
I still think point 2) warrants warning the user that they are missing a dependency, because without it all avenues/values of the playbook can not occur. In other words, just because `my_dns_lookup` _may_ be defined, doesn't negate the necessity for having the `lookup('dig')` dependency in my mind.

**Comment by bcoca** [comment]
maybe a better example can show how this is not as easy as you think:
```
- debug: msg="{{lookup(variablelookup, 'google.com')}}"
```

**Comment by bcoca** [comment]
also note that other lookups have dependencies not shipped with Ansible, like redis, mongodb, shelvefile, etc

**Comment by xenithorb** [comment]
Yes, so you're saying when the lookup type is a variable it's not within the current framework to be able to resolve that ahead of time to check for dependencies, ok.

Recall that this is about at least improving the message, though. 

In the most basic sense: What is the "knowledge bar" that ansible officially expects the user to meet in order to know how to resolve `module dns.resolver` into `dnspython`, and can something be done about being more clear about what they need to install?

Edit: Also realize that I understand you put a note in the documentation about `dnspython`, but the user would need to know to look for the note for it to be relevant, which tends to be self-defeating ( in the sense that when I ran across this it did not occur to me that additional information would be provided about the library name, so I never thought to look there, especially because _some_ information was provided by the error message. )

**Comment by bcoca** [comment]
since we support many OSs/distros, this could be a VERY long message if we have to specify how you  can possibly install it, that is why they are 'you are missing this python lib required by this plugin'.

We cannot even assure you that the correct name is supplied for the package system you might use, as these change a lot more than anyone would think is sane, only the 'import name'.

**Comment by xenithorb** [comment]
I'm only talking about using PyPI names "Please install from pip or your package manager `dnspython` or the package that contains the module `dns.resolver`" 

I realized ahead of time that enumerating all package names is not feasible, I'm totally with you there. 

Note: I'm _only_ talking about additional python dependencies, not anything else.

**Comment by theballdredge** [comment]
this issue impacts more than people using the lookup plugin directly.  i just encountered the behavior described above when using the zabbix modules, and found this thread when researching the issue.

i found it obvious that a module was missing, but it took a bit of effort to figure out which one.  while distros may package it differently, the underlying python package name is known, and i would have found something like the last suggestion made by @xenithorb above would have been helpful.

**Comment by TheFrozenFire** [comment]
:+1: I only figured out how to fix this by looking at @xenithorb's comment in this thread.

**Comment by perolausson** [comment]
It's odd to me that this was closed. It's not documented on the main dig documentation page what is needed, all it says is:

  Requirements (on host that executes module):
   dig (CLI utility)

Whereas, elsewhere the documentation (link above by georgepsarakis) says:

Warning
This lookup depends on the dnspython library.

It's not exactly the same thing you know.

**Comment by bcoca** [comment]
@perolausson closed?

in any case it should be soon, new docs have been written now available in `ansible-doc` and soon on the website, these should be correct https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/dig.py

**Comment by perolausson** [comment]
Sorry I misread the status above. But the file you refer to doesn't have the correct instructions. :(

So I really don't understand why you now closed it.

**Comment by bcoca** [comment]
as i explained above, how to install a library is beyond the scope of the instructions as 'correct' depends too much on the context for each user.

So we just point out we depend on the library and even give you a link to it, then each user can decide which methods are available to them and which one of those is 'correct' for them.

**Comment by perolausson** [comment]
The instructions now say dig (CLI), right?

That is the ultimate core dependency but it isn't the dependency the lookup
dig module has.

I already had dig installed and it had nothing to do with it and everyone
above is pointing out the same.

I've added a comment to your commit explaining what the real dependency is.

You could say (python module) if (pip) is too specific for you. But I find
that odd since pip is a module in Ansible that happily solves the problem.

Regards,


Per Olausson

**Comment by bcoca** [comment]
refresh, i was in process of updating when i saw this, i had several fixes for the docs in that plugin today

also 'pip' solves it for you, but not for everyone, many dont/cannot have pip installed or available.
