### ISSUE TITLE
Document problem about sysctl module 

### ISSUE THREAD

**Issue by ftao** [ansible/ansible#1972]
In http://ansible.cc/docs/modules.html#sysctl
It says 

```
   sysctl 
   New in version 0.6. 
```

But  It seems sysctl is just added , only in devel branch , even not in latest 0.9  release .

**Comment by dhozac** [comment]
1.0 is the latest release, and sysctl is indeed in it. Next doc push will have the fix included.

**Comment by mpdehaan** [comment]
Yep, I'll do a rebuild in a bit.   A consequence of a copy/paste of the
documentation block no doubt :)
