### ISSUE TITLE
Failing to ping a remote Windows Machine via WinRM from an Ansible control host

### ISSUE THREAD

**Issue by davidfof13** [ansible/ansible#19738]
I'm trying to experiment with Ansible on Windows hosts.  I have a dummy Windows machine which has PowerShell 5.0 installed and WinRM running via HTTPs (I'm ignoring SSL certificates for now).

I'm trying to test connectivity to it from my Ansible master (Ubuntu 16.04 machine with Ansible 2.2 and Python 2.7.6 installed). After running `ansible windows -i hosts -m ping -vvv` , I get the following output: 

````Loading callback plugin minimal of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/core/system/ping.py
<104.196.198.238> ESTABLISH WINRM CONNECTION FOR USER: david on PORT 5986 TO 104.196.198.238
<104.196.198.238> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1483018372.8-93965103172004").FullName | Write-Host -Separator '';
<104.196.198.238> PUT "/tmp/tmp4gVqPw" TO "C:\Users\david\AppData\Local\Temp\ansible-tmp-1483018372.8-93965103172004\ping.ps1"
<104.196.198.238> EXEC Set-StrictMode -Version Latest
Try
{
/usr/bin/python 'C:\Users\david\AppData\Local\Temp\ansible-tmp-1483018372.8-93965103172004\ping.ps1'
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\david\AppData\Local\Temp\ansible-tmp-1483018372.8-93965103172004" -Force -Recurse -ErrorAction SilentlyContinue }
An exception occurred during task execution. The full traceback is:
At line:4 char:1
+ /usr/bin/python 'C:\Users\david\AppData\Local\Temp\ansible-tmp-148301 ...
+ ~~~~~~~~~~~~~~~
104.196.198.238 | FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "ping"
    },
    "msg": "The term '/usr/bin/python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling ry again."
}
````
From what I can see, my Ansible master creates a temporary directory in the Windows Server  in which it uploads a Powershell version of the `ping.py script`, namely `ping.ps1`.  It then tries to run the  created script with Python. Surely, `powershell.exe` instead of `/usr/bin/python` was intended there, right?  Because Ansible should only run the remote script with Python if the remote host is a Linux machine, but surely it knows that it's a Windows machine given the fact that it created .ps1 file for the ping script? I'm confused.

Judging by the answers of other people who have had this error,  it appears that earlier versions of Ansible didn't have this problem. Can anyone confirm this and provide a current fix please?

**Comment by sivel** [comment]
The correct module to "ping" a windows host is `win_ping`, whereas the module for linux is `ping`.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by davidfof13** [comment]
@sivel  Fantastic, it works like a charm
