### ISSUE TITLE
pip package contains old code of stable-2.2 branch

### ISSUE THREAD

**Issue by akuznecov** [ansible/ansible#19748]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
pip package
https://pypi.python.org/pypi/ansible/2.2.0.0

##### ANSIBLE VERSION

```
2.2.0.0
```

##### SUMMARY
pip package contains old code, while stable-2.2 branch was updated after package release

##### STEPS TO REPRODUCE
Install `ansible` package with `pip install ansible`

##### EXPECTED RESULTS
Encrypted inventory files well included

##### ACTUAL RESULTS
https://github.com/ansible/ansible/issues/18355 still reproduced

**Comment by alikins** [comment]
At the moment, 2.2.0.0 is the latest 2.2 release. The stable-2.2 content (including the fix for #18355) will get released to 2.2.1.0 soon.
But currently the pip release is correct.

**Comment by bcoca** [comment]
to match releases look at tags, we keep 'stable' branches for backporting bugfixes.
