### ISSUE TITLE
FreeBSD-11 Images for Shippable needed

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#19749]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
testing

##### SUMMARY
FreeBSD 11.0 was released in October 2016, we should test it.

Currently we only test 10.3-STABLE https://github.com/ansible/ansible/blob/devel/shippable.yml#L16

Thanks to nrzkt for pointing this out

**Comment by nerzhul** [comment]
Thanks for reporting this ! (please note i'm nrzkt on freenode)

**Comment by mattclay** [comment]
We're now testing FreeBSD 11.0: https://github.com/ansible/ansible/pull/19905
