### ISSUE TITLE
BUG: Possible to use dynamic variables mapping [00:xx] in Inventory HostGroups

### ISSUE THREAD

**Issue by westsouthnight** [ansible/ansible#19754]
##### ISSUE TYPE
 - Feature Idea
 - Bug

##### COMPONENT NAME
Core Inventory

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
Any

##### SUMMARY
I'm use dynamic naming for Inventory host groups with servers like

```
[ubuntu-servers]
[01:25]-datacenter.example.com

```

Sometimes, i need to have params/vars for that host group like:

```
[es-cluster-servers]
01-datacenter.example.com some_variable_like_external_ip_of_some_container="192.168.111.1"
02-datacenter.example.com some_variable_like_external_ip_of_some_container="192.168.111.2"
03-datacenter.example.com some_variable_like_external_ip_of_some_container="192.168.111.3"
...etc
```

I want to use dynamic mappings like in ubuntu-servers group, for example its can to be looks like:

```
[es-cluster-servers]
[01:25]-datacenter.example.com external_ip_of_some_container="192.168.111.[01:25]"
```

##### EXPECTED RESULTS
Worked dynamic variables in Inventory Hostgroups

##### ACTUAL RESULTS
I cannot find way to use dynamic variables in Inventory Hostgroups

PS. If we have some way for that, please give answer.

**Comment by bcoca** [comment]
you can, just a bit different:
```
[01:25]-datacenter.example.com external_ip_of_some_container="192.168.111.{{inventory_hostname[0:2]}}"
```

**Comment by westsouthnight** [comment]
@bcoca very nice !!! thank you!!!

**Comment by westsouthnight** [comment]
@bcoca i think its need be added to docs.

**Comment by westsouthnight** [comment]
@bcoca we try to use like you say, but its not works =( May be some wrong in 

``[01:25]-node external_ip_of_some_container="192.168.111.{{inventory_hostname[0:2]}}"``

**Comment by westsouthnight** [comment]
@bcoca may be i need specific version of ansible? We currently use 2.2.0.0

**Comment by westsouthnight** [comment]
@bcoca sorry, {{ inventory_hostname[0:2] }} its a pointer. Thanks. All nice!
