### ISSUE TITLE
finish out --check mode

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1976]
We have the basis of a --check (pseudo dry run) mode in place, obvious philosophical issues about in the past I've mentioned aside.

We should make the service, apt, yum, file, and a few other modules work with it before we advertise this as a complete feature.

It will not be required for all modules to support this but will be nice if they do.

See list for details.

https://groups.google.com/forum/?fromgroups=#!topic/ansible-project/Vhld_PWS9-k

**Comment by mpdehaan** [comment]
once finished we also can update wikipedia about that 'verify' thing :)

**Comment by skvidal** [comment]
trying to figure out what --check entails for a couple of yum module modes - some thoughts:
1. install is easy  - if anything would change - simply return that a change would occur and the output of a resolved transaction set
2. remove is pretty much the same as install 
3. update gets tricky, I guess b/c of wildcards - but if the idea is to only show if ANYTHING would change - then just returning if any element would end up in a transaction, at all, would be sufficient?

**Comment by mpdehaan** [comment]
I think returning if it would be involved in a transaction is sufficient for most modules, but if they could fill in more data, that would be great.

If it were to only say that it would change state and only return change=True and nothing else, that's acceptable, but if it could return more, that's obviously better.

OT discussion -- There is also the usefulness if we are talking about storing data in a database of something else.  In many places we default to state=installed, and it may be useful to gather a baseline, via something like state=peek.   (Just because I can't change the defaults of any modules to state=peek, it would not be the default state).   This way you could easily get a baseline of the resources over time if you wanted and be able to diff raw resources.   We probably need to figure out if defaulting state to something other than installed becomes something that is configurable or an internal argument, and it is really something that doesn't have to occur at the module level but could be handled up in Runner.    Sorry if this is confusing, one of those, I just woke up and was thinking "whoa, we might need to do that", kind of things :)

**Comment by mpdehaan** [comment]
this is a dup of another ticket
