### ISSUE TITLE
Registered variable with dynamic name not working

### ISSUE THREAD

**Issue by whitfiea** [ansible/ansible#19803]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
register variables

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /workspace-feature/iotcloud.infrastructure.openstack.deploy/ansible-deploy/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
[defaults]
timeout=300
roles_path = roles
nocows = 1
nocolor = 0
transport = ssh
#vars_plugins = plugins/vars
#action_plugins = plugins/action
#connection_plugins = plugins/connection
callback_plugins = plugins/callbacks
#filter_plugins = plugins/filters
#var_defaults_file = ../defaults-2.0.yml
forks = 25
gathering = smart
retry_files_enabled = false
log_path=$HOME/.ansible/ansible.log
host_key_checking = False

[ssh_connection]
pipelining=true
ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o ControlPath=/tmp/ansible-ssh-%h-%r

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY
Registered variables created with a dynamic name are not accessible in Ansible 2.2. This is similar to the issue #15700 but the cause appears to be different. This worked previously in Ansible version 2.0.1

##### STEPS TO REPRODUCE
Have a task that includes another task and passes in the var "output" to be used as the dynamic register var name.

```yaml
- include: tasks/create_password.yml 
  vars:
    output: "docker_registry_password_output"
```

in the tasks/create_password.yml:

```yaml
- name: Generating password
   shell: head /dev/urandom | base64 | tr -dc "{{ valid_chars|default('0-9a-zA-Z') }}" | head "-c{{ length|default(12) }}"
  register: "{{ output }}"

- debug:
    var: "{{ output }}"
```

##### EXPECTED RESULTS
It is expected that the registered variable will be defined with the name docker_registry_password_output in this case, and that docker_registry_password_output will be accessible within this playbook run.

##### ACTUAL RESULTS
The debug statement shows that the register var is not defined. 

```
TASK [Generating password] *****************************************************
Tuesday 03 January 2017  13:23:42 +0000 (0:00:00.231)       0:00:20.435 *******
changed: [localhost] => {
    "changed": true,
    "cmd": "head /dev/urandom | base64 | tr -dc \"a-z\" | head \"-c10\"",
    "delta": "0:00:00.005170",
    "end": "2017-01-03 13:23:42.500811",
    "invocation": {
        "module_args": {
            "_raw_params": "head /dev/urandom | base64 | tr -dc \"a-z\" | head \"-c10\"",
            "_uses_shell": true,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "warn": true
        },
        "module_name": "command"
    },
    "rc": 0,
    "start": "2017-01-03 13:23:42.495641",
    "stderr": "",
    "stdout": "plxktlrbpc",
    "stdout_lines": [
        "plxktlrbpc"
    ],
    "warnings": []
}

TASK [debug] *******************************************************************
Tuesday 03 January 2017  13:23:42 +0000 (0:00:00.113)       0:00:20.549 *******
ok: [localhost] => {
    "docker_registry_password_output": "VARIABLE IS NOT DEFINED!"
}
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

This is not a bug, this is just not a supported feature, registered var names are not templatable.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by whitfiea** [comment]
@bcoca can you let me know what the misunderstanding was? This way of using a dynamic name for the register previously worked but no longer works in Ansible 2.2

**Comment by mattvonrocketstein** [comment]
> registered var names are not templatable.

Came here looking for this, I think it would be a useful feature

**Comment by BarbzYHOOL** [comment]
Still not possible?? on 2.7 it seems to be the same issue
