### ISSUE TITLE
Serialized tasks

### ISSUE THREAD

**Issue by shoelzle** [ansible/ansible#19855]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
ansible core

##### SUMMARY
Ansible allows to execute playbooks in serial mode, which results in execution batches.
This behavior is what I want, but only for single tasks, such that all tasks before and after the serialized task are executed in parallel.

**Comment by jhawkesworth** [comment]
@shoelzle - you can already organize your playbooks into multiple plays, so you can define a play within your playbook that just the tasks in it run with serial.  We do this a lot for rolling updates to production servers.

**Comment by shoelzle** [comment]
Thanks for the hint @jhawkesworth . I guess my playbook can be reorganized according to you suggestion.

Still, I think this feature request has its use cases, as shown by your example of rolling updates. Do you think this feature could simplify the plays of your rolling updates ?

**Comment by jhawkesworth** [comment]
@shoelzle - it probably wouldn't make much difference for us, but we are probably unusual as we tend to update relatively small numbers of different types of servers (at least when we are updating software).

**Comment by jhawkesworth** [comment]
@shoelzle - it probably wouldn't make much difference for us, but we are probably unusual as we tend to update relatively small numbers of different types of servers (at least when we are updating software).

**Comment by Kurisutian** [comment]
+1

**Comment by paszczus** [comment]
+1

**Comment by senorsmile** [comment]
+1

**Comment by gregsymons** [comment]
This could also be useful within a role, so that you could fully encapsulate things like rolling hosts in and out of load balancers within the role.

**Comment by bcoca** [comment]
closing via #60702
