### ISSUE TITLE
The user need to use login shell  environment when become_method is "su"

### ISSUE THREAD

**Issue by LuYiding** [ansible/ansible#19859]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

Get login shell  environment when become_method is "su"

##### ANSIBLE VERSION

```
ansible  --1.9
ansible  --2.0
ansible  --2.1
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The user can not use login shell  environment when become_method is "su".
Because the code in "lib/utils/__init__.py" is
==========
    elif method == 'su':
        exe = exe or C.DEFAULT_SU_EXE
        flags = flags or C.DEFAULT_SU_FLAGS
        becomecmd = '%s %s %s -c "%s -c %s"' % (exe, flags, user, shell, pipes.quote('echo %s; %s' % (success_key, cmd)))
==========
This situation,ansible run a shell as  su $user -c "xxxx",
But we usually run a shell as su - $user -c "xxxx"

##### STEPS TO REPRODUCE

We can change the  code in "lib/utils/__init__.py"  to 
=========
#add one " - "
becomecmd = '%s %s - %s -c "%s -c %s"' % (exe, flags, user, shell, pipes.quote('echo %s; %s' % (success_key, cmd)))
=========
Then the user can use login shell  environment when become_method is "su"

```yaml

```

##### EXPECTED RESULTS

The user can use login shell  environment when become_method is "su"

##### ACTUAL RESULTS

The user can use login shell  environment when become_method is "su"

```

```

**Comment by wangxuan9237** [comment]
This is really cool!

**Comment by bcoca** [comment]
no need to change code, just set `-` as one of the flags or even as part of the executable setting. Closing as it already works.
