### ISSUE TITLE
Error when calling multiple roles in multiple hosts from same playbook

### ISSUE THREAD

**Issue by gonzalomk** [ansible/ansible#19871]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

No configuration modifications

##### OS / ENVIRONMENT

Rhel 7.2

##### SUMMARY

I'm getting a weird behaviour when running a master playbook with multiple roles agains multiple hosts. What's happening is that once role1 finish, instead of starting role2, it starts role1 again but with the host from role2.

##### STEPS TO REPRODUCE
The logic behind those roles is quite extend and complex so I will just paste the main playbook from where I'm making the calls to those roles.

```master_playbook.yaml
- name: Role1
  hosts: '{{ hostname }}'
  gather_facts: yes
  become: yes

  roles:
  - role: role1

- name: Role2
  hosts: node
  gather_facts: no

  roles:
  - role: role2
```

##### EXPECTED RESULTS

Execute both roles against their own hosts

##### ACTUAL RESULTS

Only role 1 is launching against both hosts.

```

```

**Comment by nitzmahone** [comment]
I'm unable to reproduce this on 2.1.1 with what you've supplied (using dummy roles that just debug output "role1"/"role2")- it behaves as expected for me. Can you supply a full reproduction with dummy roles and commandline, eg, how you're setting the `hostname` var, etc?

**Comment by gonzalomk** [comment]
Hi

This ticket can be closed. There was an internal error with one of the roles.

Thank you
