### ISSUE TITLE
ansible_distribution_release missing on debian testing

### ISSUE THREAD

**Issue by micw** [ansible/ansible#19874]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### OS / ENVIRONMENT
Debian stretch/sid (testing)

##### SUMMARY
I run ansible on all my machines for automated setup. Debian stretch will be released in a few weeks, so I do some integration testings. Some of my roles, that rely on ansible_distribution_release fails because it's not defined.

##### DETAILS

ansible_distribution_release is read from /etc/os-release on debian. On jessie it looks like:

PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"

On stretch (while it's still testing) its:
PRETTY_NAME="Debian GNU/Linux stretch/sid"
NAME="Debian GNU/Linux"
ID=debian

Ansible uses "stretch/sid" as version and leaves ansible_distribution_release undefined:

$ ansible localhost -m setup | grep distribution
        "ansible_distribution": "Debian", 
        "ansible_distribution_major_version": "stretch/sid", 
        "ansible_distribution_release": "NA", 
        "ansible_distribution_version": "stretch/sid", 

##### EXPECTED RESULT
ansible_distribution_release should be "stretch"
ansible_distribution_major_version should not be "stretch/sid". Optimally it would be "9", but maybe "NA" would also be OK
ansible_distribution_version should not be "stretch/sid". Optimally it would be "9", but maybe "NA" would also be OK

**Comment by alikins** [comment]
Whats the output of:

```
python -c 'import platform; print platform.release(); print platform.version(); print platform.dist()'
```

**Comment by micw** [comment]
$ python -c 'import platform; print platform.release(); print 
platform.version(); print platform.dist()'
4.8.0-2-amd64
#1 SMP Debian 4.8.11-1 (2016-12-02)
('debian', 'stretch/sid', '')

**Comment by LearnLinuxTV** [comment]
I am running into this issue as well on Stretch. I installed Stretch on a VM today. When I manually check the facts, I get the following:

`#ansible localhost -m setup |grep distribution_release`
"ansible_distribution_release": "NA",

If I run that same command on a Jessie system, I get:
"ansible_distribution_release": "jessie",


Additionally, ansible_distribution_version seems to be wrong as well:
"ansible_distribution_version": "stretch/sid",

While on a Jessie system, I get:
"ansible_distribution_version": "8.6",

It appears to me that Ansible is interpreting things incorrectly in newer Debian.

**Comment by sysadmin75** [comment]
I wasn't able to reproduce the issue.
I tried on 2 different debian 8 setups. A fresh debian 8 install and a proxmox server with debian 8.
And I tried from 2 management hosts OSX 10.12.2 and Fedora 23.

$ grep distribution pve01_setup 
        "ansible_distribution": "Debian", 
        "ansible_distribution_major_version": "8", 
        "ansible_distribution_release": "jessie", 
        "ansible_distribution_version": "8.6", 

$ grep distribution debian8_setup 
        "ansible_distribution": "Debian", 
        "ansible_distribution_major_version": "8", 
        "ansible_distribution_release": "jessie", 
        "ansible_distribution_version": "8.7",

**Comment by LearnLinuxTV** [comment]
@sysadmin75: This bug report was for Debian testing, which is Debian 9. Your output is solely from Debian 8, which is stable. In my output, I gave an example of the output from both Debian 8 as well as Debian 9.

**Comment by micw** [comment]
Stretch is about to be released in  a few days or weeks and is frozen now. Seems that they updated the version files so ansible now reports correct version information:

$ ansible localhost -m setup | grep distribution
        "ansible_distribution": "Debian", 
        "ansible_distribution_major_version": "9", 
        "ansible_distribution_release": "stretch", 
        "ansible_distribution_version": "9.0", 

So for stretch this issue is not an issue anymore. But it will be another one on next debian unstable...

**Comment by Vladimir-csp** [comment]
Well, it's happening on Debian testing again, `ansible_distribution_major_version` and `ansible_distribution_version` are no longer numeric, but reported as `buster/sid`

```
$ python -c 'import platform; print platform.release(); p platform.version(); print platform.dist()'
4.11.0-1-amd64
#1 SMP Debian 4.11.6-1 (2017-06-19)
('debian', 'buster/sid', '')
```
I do not know what would be a correct solution to this. If ansible takes this data directly from python, perhaps I would make a bugreport to Debian asking for numerical designations for testing. If anyone knows some underlying details of those python functions that would help make a more solid request, please comment.

**Comment by richard-scott** [comment]
I've just installed this image using Vagrant / VirtualBox's Bento image:
https://app.vagrantup.com/bento/boxes/debian-9.0

Initially the content of "ansible_distribution_release" was ok for me and came up as "stretch", but on following runs the same playbook Ansible adds new repos with 'NA' as the release name.

I was using "ansible_distribution_release" as the variable to get the release name.

**Comment by rgarrigue** [comment]
For the record, there's already a buster tag on docker's library [debian](https://hub.docker.com/_/debian/), with the same issue. 

```
root@b5af324f29ae:/# python -c 'import platform; print platform.release(); platform.version(); print platform.dist()'
4.10.0-40-generic
('debian', 'buster/sid', '')
```

Here's ansible running localy

```
root@b5af324f29ae:/# ansible --version
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 17 2017, 18:50:44) [GCC 7.2.0]


root@b5af324f29ae:/# ansible -clocal -i'localhost,' -msetup all | grep distribution
        "ansible_distribution": "Debian", 
        "ansible_distribution_file_parsed": true, 
        "ansible_distribution_file_path": "/etc/os-release", 
        "ansible_distribution_file_variety": "Debian", 
        "ansible_distribution_major_version": "buster/sid", 
        "ansible_distribution_release": "NA", 
        "ansible_distribution_version": "buster/sid", 

root@b5af324f29ae:/# ansible -clocal -i'localhost,' -msetup all | grep '"NA"'
        "ansible_distribution_release": "NA", 
        "ansible_product_version": "NA", 
```

**Comment by hurricanehrndz** [comment]
Same issue on Ubuntu 17.10

```
 python -c 'import platform; print platform.release(); print platform.version(); print platform.dist()'
4.13.0-21-generic
#24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017
('debian', 'stretch/sid', '')

```

**Comment by MichaelMayorov** [comment]
I got same problem with buster

```
        "ansible_distribution_major_version": "buster/sid",
        "ansible_distribution_release": "NA",
        "ansible_distribution_version": "buster/sid",
```

**Comment by thiagogomesverissimo** [comment]
Same here for debian buster:
```
ansible vagrant -m setup |grep distribution_release  
        "ansible_distribution_release": "NA", 
```

**Comment by Kocal** [comment]
Same issue here, I can't use https://github.com/geerlingguy/ansible-role-php-versions :( 

![capture d ecran de 2018-10-15 20-18-13](https://user-images.githubusercontent.com/2103975/46969806-83956a00-d0b7-11e8-935a-b7390da78177.png)

**Comment by jalr** [comment]
Has anyone got an idea why this happens? An empty variable would be better but literal "NA" string is just awful because it is harder to debug this error.

As a workaround for debian buster, I replaced `ansible_distribution_release` with `ansible_lsb.codename`.

**Comment by myrdd** [comment]
This is my workaround (specific for Debian Buster): I override `ansible_distribution_release` in each playbook:

```
---
- hosts: debian
  roles: []
  vars:
    ansible_distribution_release: '{{ "buster"
                                      if ansible_facts["distribution_major_version"] == "buster/sid"
                                      else ansible_facts["distribution_release"] }}'
```

`ansible_distribution_release` is set depending on `ansible_distribution_major_version`. I put it in the playbook because the playbook is the most global place where you are able to override ”facts“, see the [docs on variable precedence](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable).)

---

@jalr's solution, using `ansible_lsb.codename`, works as well:

```
"ansible_lsb": {
    "codename": "buster",
    "description": "Debian GNU/Linux testing (buster)",
    "id": "Debian",
    "major_release": "testing",
    "release": "testing"
},
```

However, it requires you to install the `lsb-release` package, which is not always installed by default.

---

I did not dive into the code, but the solution could look something like this:

```python
def map_distribution_release():
    if (
        ansible_distribution_release == "NA" and
        ansible_distribution == "Debian" and
        isinstance(ansible_distribution_major_version, basestring) and  # modify for Python3
        ansible_distribution_major_version.endswith("/sid")
    ):
        ansible_distribution_release = ansible_distribution_major_version.split("/")[0]
```

**Comment by fauust** [comment]
Hi,
this is happening again on the actual Debian testing (sid) if ansible is installed with pip:

```console
podman run -it debian:sid bash -c "apt update && apt install -y python3-pip && pip install ansible==2.9.* && ansible -m setup localhost | grep ansible_distribution_release"
...
        "ansible_distribution_release": "NA",
podman run -it debian:sid bash -c "apt update && apt install -y python3-pip && pip install ansible==2.10.* && ansible -m setup localhost | grep ansible_distribution_release"
...
        "ansible_distribution_release": "NA",
```

Seems ok with ansible from Debian packages (`2.9.13+dfsg-1`):

```console
podman run -it debian:sid bash -c "apt update && apt install ansible && ansible -m setup localhost | grep ansible_distribution_release"
...
        "ansible_distribution_release": "sid",
```

Workaround is to install the `lsb-release` package:

```console
podman run -it debian:sid bash -c "apt update && apt install -y python3-pip lsb-release && pip install ansible==2.9.* && ansible -m setup localhost | grep ansible_distribution_release"
...
        "ansible_distribution_release": "sid",
podman run -it debian:sid bash -c "apt update && apt install -y python3-pip lsb-release && pip install ansible==2.10.* && ansible -m setup localhost | grep ansible_distribution_release"
...
        "ansible_distribution_release": "sid",
```
