### ISSUE TITLE
lxc_container.py still uses lxc-clone for clones (it ought to use lxc-copy)

### ISSUE THREAD

**Issue by fghaas** [ansible/ansible#19890]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`lxc_container` module

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
No changes from package defaults.

##### OS / ENVIRONMENT
Ubuntu 16.04.1 LTS

##### SUMMARY
The module makes use of the `lxc-clone` command, which is deprecated in favor of `lxc-copy`, and will be removed in some future LXC release — in which case, if the module remains unchanged, clones will stop working.

##### EXPECTED RESULTS
`lxc_container.py` should invoke `lxc-copy` when creating clones.

##### ACTUAL RESULTS
`lxc_container.py` invokes `lxc-clone` when creating clones.

**Comment by fghaas** [comment]
Tagging @cloudnull as the original author of `lxc_container.py`.

**Comment by fghaas** [comment]
Sorry, accidentally hit "close and comment" instead of just "comment".

**Comment by fghaas** [comment]
Evidently, *some* people are already being bitten by this because their distribution no longer ships `lxc-clone` (see ansible/ansible-modules-extras#2996).

**Comment by gundalow** [comment]
There is a proposed fix in https://github.com/ansible/ansible/pull/20373, reviews welcome

**Comment by fghaas** [comment]
@gundalow Thanks! I've updated ansible/ansible-modules-extras#2996 to let the original reporter know.
