### ISSUE TITLE
hg module pull from repo

### ISSUE THREAD

**Issue by roller** [ansible/ansible#1989]
The hg module ignores the repo= option when doing a pull, instead pulling from the original clone location.

I know that a normal ansible deploy will never change repo locations, but I think the fix is probably simple enough to justify allowing for it.

**Comment by mpdehaan** [comment]
Agree!

**Comment by yeukhon** [comment]
It looks good. I think you should submit the pull request. I image you would do this

`hg: repo=local dest=/path/to/disk/repo``

where `local` is in hgrc as you stated. 

I think that's a nice addition.
