### ISSUE TITLE
Type error with python3 when using basic Authentication with open_url

### ISSUE THREAD

**Issue by holgpar** [ansible/ansible#19930]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
module_utils/urls.py
##### ANSIBLE VERSION

```
ansible 2.3.0
```

##### CONFIGURATION
I am running with Python 3.4

##### OS / ENVIRONMENT
linux

##### SUMMARY
Using basic authentication does not work with Python3 because the "%" does not allow bytes. However, 

```
def basic_auth_header(username, password):
    """Takes a username and password and returns a byte string suitable for
    using as value of an Authorization header to do basic auth.
    """
    return b("Basic %s") % base64.b64encode(to_bytes("%s:%s" % (username, password), errors='surrogate_or_strict'))
```

##### STEPS TO REPRODUCE

Use `open_url` in module like this:
```
        resp = open_url(url, method="PUT", validate_certs=False,
            url_username=user, url_password=password, force_basic_auth=True,
            data=state.encode("UTF-8"))
```

##### EXPECTED RESULTS

call works.

##### ACTUAL RESULTS

Error:
```
File \"/tmp/ansible_k0x02er_/ansible_modlib.zip/ansible/module_utils/urls.py\", line 827, in open_url
File \"/tmp/ansible_k0x02er_/ansible_modlib.zip/ansible/module_utils/urls.py\", line 911, in basic_auth_header

TypeError: unsupported operand type(s) for %: 'bytes'
```

**Comment by abadger** [comment]
We support python-3.5+ so that we can have things like percent formatting of byte strings.  So I'm afraid this is a WONTFIX.  Sorry for the inconvenience.
