### ISSUE TITLE
when_unset appears to short circuit conditional evaluation

### ISSUE THREAD

**Issue by nigelm** [ansible/ansible#1994]
The various when conditionals appear to stack as you would expect, except that
if a when_unset fires, then any other conditionals in the task seem to be ignored

See test playbook in gist that I will reference shortly (why can you not attach files here)

**Comment by nigelm** [comment]
Gist with playbook that shows this - https://gist.github.com/nigelm/4713725

The last task in the list should not be run, but is...

**Comment by mpdehaan** [comment]
I actually never expected anyone to try to stack the when's at all.   They
basically each are intended to replace an only_if.

We should probably make this an error.
