### ISSUE TITLE
ignore_errors not working in include module

### ISSUE THREAD

**Issue by dvavili** [ansible/ansible#19961]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 Include module
 ignore_errors option

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /home/admin/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I have a cleanup playbook that goes through some tasks and cleans up some state on my host, but I want to ignore errors. Since I have many roles to cleanup, I include all of these files and have ignore_errors check in the include task. Is this the right way to handle ignore_errors for all tasks included by the file? If not, what is the best recommended way to handle this.

##### STEPS TO REPRODUCE

```yaml
    - include: roles/<rolename>/tasks/cleanup.yml
      ignore_errors: yes
```

##### EXPECTED RESULTS

Any error from tasks in the included file should be ignored

##### ACTUAL RESULTS

```
Errors in the task(s) from included file  are not ignored
```

**Comment by bcoca** [comment]
static includes are not normal tasks so this needs to be a dynamic include for most 'task level directives' to work as you expect.
```
    - include: roles/<rolename>/tasks/cleanup.yml
      static: no
      ignore_errors: yes

```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by dvavili** [comment]
The static option resolved the issue. Thanks.
