### ISSUE TITLE
Multithreading running  the playbook exception

### ISSUE THREAD

**Issue by liuzhenan** [ansible/ansible#19967]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME

from ansible.playbook import PlayBook
##### ANSIBLE VERSION

```
ansible 1.9.2

```

##### CONFIGURATION

[defaults]
inventory      = /etc/ansible/hosts
remote_tmp     = $HOME/.ansible/tmp
pattern        = *
forks          = 10
poll_interval  = 15
sudo_user      = root
transport      = smart
module_lang    = C
gathering = implicit
host_key_checking = False
sudo_exe = sudo
timeout = 3
remote_user = ansible
log_path = /var/log/ansible.log
module_name = shell
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
action_plugins     = /usr/share/ansible_plugins/action_plugins
callback_plugins   = /usr/share/ansible_plugins/callback_plugins
connection_plugins = /usr/share/ansible_plugins/connection_plugins
lookup_plugins     = /usr/share/ansible_plugins/lookup_plugins
vars_plugins       = /usr/share/ansible_plugins/vars_plugins
filter_plugins     = /usr/share/ansible_plugins/filter_plugins
fact_caching = memory
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=240s -o LogLevel=DEBUG3 
control_path = /tmp/ssh_mux_%%h_%%p_%%r 
[accelerate]
accelerate_port = 5099
accelerate_timeout = 30
accelerate_connect_timeout = 5.0
accelerate_daemon_timeout = 30
##### OS / ENVIRONMENT

Linux test-ansible-00 2.6.32-573.12.1.el6.x86_64 #1 SMP Tue Dec 15 21:19:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY

I think playbook is non-thread-safe, resulting in an error in the run
##### STEPS TO REPRODUCE

Run the playbook instance in multiple threads, some are running correctly, and there are some errors。

```yaml

```

##### EXPECTED RESULTS

24536 2017-01-06 02:06:39,095 [p=26042 u=root | ] callbacks.py[line:161] callbacks ERROR fatal: [10.60.30.81] => host not found: 10.60.30.81
24537 2017-01-06 02:06:39,101 [p=26042 u=root | ] callbacks.py[line:161] callbacks ERROR fatal: [10.60.30.64] => host not found: 10.60.30.64
24538 2017-01-06 02:06:39,113 [p=26042 u=root | ] callbacks.py[line:161] callbacks ERROR fatal: [10.60.30.43] => host not found: 10.60.30.43
24539 2017-01-06 02:06:39,114 [p=26042 u=root | ] callbacks.py[line:161] callbacks ERROR fatal: [10.60.30.87] => host not found: 10.60.30.87
24540 2017-01-06 02:06:39,119 [p=26042 u=root | ] callbacks.py[line:163] callbacks INFO changed: [10.60.30.78]
24541 2017-01-06 02:06:39,168 [p=26042 u=root | ] callbacks.py[line:163] callbacks INFO changed: [10.60.30.11]
24542 2017-01-06 02:06:39,171 [p=26042 u=root | ] callbacks.py[line:163] callbacks INFO changed: [10.60.30.85]
24543 2017-01-06 02:06:39,173 [p=26042 u=root | ] callbacks.py[line:163] callbacks INFO changed: [10.60.30.61]
24544 2017-01-06 02:06:39,209 [p=26042 u=root | ] callbacks.py[line:163] callbacks INFO TASK: [If Already Install Service We Will Remove It] **************************
24545 2017-01-06 02:06:39,313 [root] Database.py[line:529] Database ERROR Traceback (most recent call last):
24546   File "/data/server/platform-deploy/library/Database.py", line 512, in _wrapper
24547     result=func(*args,**kwargs)
24548   File "/data/server/platform-deploy/library/Script.py", line 113, in _wrapper
24549     raise Exception(traceback.format_exc())
24550 Exception: Traceback (most recent call last):
24551   File "/data/server/platform-deploy/library/Script.py", line 79, in _wrapper
24552     result=func(*args,**kwargs)
24553   File "/data/server/platform-deploy/platform-deploy.py", line 235, in Ansible
24554     raise Exception(traceback.format_exc())
24555 Exception: Traceback (most recent call last):
24556   File "/data/server/platform-deploy/platform-deploy.py", line 215, in Ansible
24557     file_path=file_path
24558   File "/data/server/platform-deploy/library/Ansibleapi.py", line 99, in deploy
24559     results = pb.run()
24560   File "/usr/lib/python2.6/site-packages/ansible/playbook/__init__.py", line 348, in run
24561     if not self._run_play(play):
24562   File "/usr/lib/python2.6/site-packages/ansible/playbook/__init__.py", line 789, in _run_play
24563     if not self._run_task(play, task, False):
24564   File "/usr/lib/python2.6/site-packages/ansible/playbook/__init__.py", line 497, in _run_task
24565     results = self._run_task_internal(task, include_failed=include_failed)
24566   File "/usr/lib/python2.6/site-packages/ansible/playbook/__init__.py", line 439, in _run_task_internal
24567     results = runner.run()
24568   File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 1485, in run
24569     results = self._parallel_exec(hosts)
24570   File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 1406, in _parallel_exec
24571     while not result_queue.empty():
24572   File "<string>", line 2, in empty
24573   File "/usr/lib64/python2.6/multiprocessing/managers.py", line 740, in _callmethod
24574     raise convert_to_error(kind, result)
24575 RemoteError:
24576 ---------------------------------------------------------------------------
24577 Traceback (most recent call last):
24578   File "/usr/lib64/python2.6/multiprocessing/managers.py", line 216, in serve_client
24579     obj, exposed, gettypeid = id_to_obj[ident]
24580 KeyError: '7fcfb6c2fa70'
24581 ---------------------------------------------------------------------------
##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Anisble is multi proc, as the first note in the docs http://docs.ansible.com/ansible/dev_guide/developing_api.html  states, it is not thread safe.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
