### ISSUE TITLE
__init__() got an unexpected keyword argument 'supports_check_mode

### ISSUE THREAD

**Issue by yudu** [ansible/ansible#1997]
Hello,

I am making a new ansible module named 'time', refering to the example 'datetime.datetime.now()' and the existing module 'ping'. The main code is following:

import datetime
def main():
    module = AnsibleModule(
    argument_spec = dict(),
    supports_check_mode = True
    )
    exit_json(time=str(datetime.datetime.now()))

When I use this module with the command 'ansible all -m time', there is a problem as following:

File "/root/.ansible/tmp/ansible-1360101734.28-280409975581067/time", line 67, in main
    supports_check_mode = True
TypeError: **init**() got an unexpected keyword argument 'supports_check_mode'

In the file 'module_common.py', I saw the 'supports_check_mode' is one of arguments of class 'AnsibleModule', and it works in the module 'ping', but why it doesn't work here? 

Thx.

**Comment by mpdehaan** [comment]
You have a mix of old install code and new install code.

Be sure you are running from checkout completely and don't have any loose
things left over from a previous install, or make sure you've installed the
new bits.
