### ISSUE TITLE
winrm connection displaying InsecureRequestWarning

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#20006]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

winrm connection plugin

##### ANSIBLE VERSION

v2.3

##### OS / ENVIRONMENT

RHEL7 with python2-winrm-0.2.1-1.el7.noarch

##### SUMMARY

Every task (every connection) spurs the message:
```
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
```
Despite the fact that `ansible_winrm_server_cert_validation: ignore` was set.

This is a problem in the pywinrm codebase.

**Comment by andmos** [comment]
@dagwieers @nitzmahone  I now see this exact error on our build servers running CentOS 7. It was not there yesterday, it looks like it came over night. 

In all my `group_vars` files: `ansible_winrm_server_cert_validation: ignore`

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
````
`pywinrm (0.2.2)`  

Example error: 
```
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
```

On my local Vagrant environment running Ubuntu 14.04 I have the same version of Ansible and `pywinrm (0.2.2)` , but don't see the warnings there.

**Comment by dagwieers** [comment]
@andmos It would be nice to have the fix for this in a new release of pywinrm. For now you can do what I did, and patch diyan/pywinrm#152 by hand in your code.

**Comment by andmos** [comment]
@dagwieers ah I didn't check if your changes was actually released, that explains a lot.

**Comment by dagwieers** [comment]
It is still not released :-(

**Comment by andmos** [comment]
For what it's worth, the message went away after some days in our case. Seems rather inconsistent. I guess we should send some flowers to the pywinrm guys to make them release the changes 😄

**Comment by ndeixonne** [comment]
Any news for pywinrm concerning this warning ?

**Comment by gratchie** [comment]
@dagwieers - I installed https://github.com/dagwieers/pywinrm but I'm still getting the urllib3 warning. Any ideas? thanks 

ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

pywinrm (0.2.2)

ansible_user: Administrator
ansible_password: "{{ vault_ansible_password }}"
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
validate_certs: false

thanks

**Comment by dagwieers** [comment]
@gratchie That tree (personal devel branch) does not include the needed fixes. If anything, use the upstream devel branch instead.
