### ISSUE TITLE
Ansible Galaxy Init Fails in Python 3

### ISSUE THREAD

**Issue by naftulikay** [ansible/ansible#20012]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`ansible-galaxy`

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

None.

##### OS / ENVIRONMENT

Python 3.5.2, Ubuntu 16.04.

##### SUMMARY

Installing Ansible with `pip install ansible` on Ubuntu 16.04, then trying to create roles with `ansible-galaxy init --force rolename` fails with an encoding error.

##### STEPS TO REPRODUCE

```
$ ansible-galaxy init --force example
ERROR! Could not process data from the API server (https://galaxy.ansible.com/api/): the JSON object must be str, not 'bytes'
```

The issue is [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/galaxy/api.py#L122).

##### EXPECTED RESULTS

I expected it to successfully create a role.

##### ACTUAL RESULTS

```
$ ansible-galaxy init -vvvvv --force example
No config file found; using defaults
Opened /home/naftuli/.ansible_galaxy
Initial connection to galaxy_server: https://galaxy.ansible.com
ERROR! Could not process data from the API server (https://galaxy.ansible.com/api/): the JSON object must be str, not 'bytes'
```

This is a simple Python 3 issue.

**Comment by abadger** [comment]
@naftulikay Could you test whether #20069 fixes this for you?
