### ISSUE TITLE
yum package installation fails on RHEL5 with RHN and no yum-utils

### ISSUE THREAD

**Issue by liedekef** [ansible/ansible#2002]
When using a playbook to install a package I get this:

failed: [xxxxx] => {"changed": false, "failed": true, "rc": 0, "results": []}
msg: No Package matching 'perl-libwww-perl' found available, installed or updated

Now, log on into the system and doing a "yum install perl-libwww-perl", it works just fine:

```
Install       5 Package(s)
Upgrade       0 Package(s)

Total download size: 650 k
Downloading Packages:
(1/5): perl-HTML-Tagset-3.10-2.1.1.noarch.rpm            |  15 kB     00:00     
(2/5): perl-Compress-Zlib-1.42-1.fc6.x86_64.rpm          |  52 kB     00:00     
(3/5): perl-HTML-Parser-3.55-1.fc6.x86_64.rpm            |  92 kB     00:00     
(4/5): perl-URI-1.35-3.noarch.rpm                        | 116 kB     00:00     
(5/5): perl-libwww-perl-5.805-1.1.1.noarch.rpm           | 376 kB     00:00     
--------------------------------------------------------------------------------
Total                                           2.1 MB/s | 650 kB     00:00     
Running rpm_check_debug
Running Transaction Test
Finished Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing     : perl-Compress-Zlib                                       1/5 
  Installing     : perl-HTML-Tagset                                         2/5 
  Installing     : perl-HTML-Parser                                         3/5 
  Installing     : perl-URI                                                 4/5 
  Installing     : perl-libwww-perl                                         5/5 

Installed:
  perl-libwww-perl.noarch 0:5.805-1.1.1                                         

Dependency Installed:
  perl-Compress-Zlib.x86_64 0:1.42-1.fc6  perl-HTML-Parser.x86_64 0:3.55-1.fc6 
  perl-HTML-Tagset.noarch 0:3.10-2.1.1    perl-URI.noarch 0:1.35-3             

Complete!
```

Any tips on debugging this? Is it because of the dependancies that it is not working ok?

**Comment by mpdehaan** [comment]
Could you tell us what version of Ansible you are using?  (ansible --version)?

Can you paste the section of the playbook that was dealing with the yum package?

(cc @skvidal )

**Comment by liedekef** [comment]
Version: ansible 0.9 (I would upgrade but the EPEL repo still has the 0.9 version)
Playbook part:

```
- action: yum name=perl-libwww-perl state=installed
```

**Comment by dverhelst** [comment]
I am having the same issue but with ansible 1.1. Installation with action: yum name=package state=latest fails with 'No package matching "package" found available" . However a  manual 'yum -y install package' works like a charm.

Packages are installed from RHN.

**Comment by skvidal** [comment]
what version of yum and yum-utils do you have installed?

**Comment by liedekef** [comment]
yum: yum-3.2.22-40.el5.centos
yum-utils: not installed. I know it provides repoquery, but I thought that was not needed by the ansible yum plugin for just installing a package?

**Comment by mpdehaan** [comment]
It is true that yum-utils is not required, but when repoquery is available, the yum module is able to do more things.  (Thus it matters when sorting through this problem whether it is installed or not)

**Comment by liedekef** [comment]
I found that the issue is in the function what_provides. Apparently the return from my returnPackagesByDep, my.pkgSack.matchPackageNames and/or my.rpmdb.matchPackageNames is not consistent:

I removed the package via "yum remove" and tried reinstalling it with ansible: no dice
Then I tried by disabling the what_provides check when installing a package: that works ok, but then you don't get an error when trying to install a non-existing package ...

**Comment by skvidal** [comment]
<sigh> I'm almost certain this a bad interaction with the rhn plugin in rhel5. @liedekef I should be able to give you some code snippets to run so I can figure out what is going on here.

**Comment by liedekef** [comment]
Well, I confirmed that no python api command is returning anything at all (not even "searchPackageProvides"), it works just fine for already installed packages but nothing for not-installed packages. So I believe you're on the right track with the rhn thingie.
I can test on Monday :-) You can sent me any test script you want executed.

**Comment by skvidal** [comment]
I suspect that rhel5 yum is not initializing the plugin by default (which is why we were using repoquery to begin with).

Looking through the rhel5 yum code - it claims it is initing plugins by default but the effects you're seeing would suggest otherwise.

Try running this from python on that system, as root.

import yum
my = yum.YumBase()
my.pkgSack.returnPackagesByDep('yum')

when you run the 3rd line you should see something print "Loaded plugins: stuff here"

if you don't see rhn there then that's the issue.

**Comment by dverhelst** [comment]
> > > import yum
> > > my = yum.YumBase()
> > > my.pkgSack.returnPackagesByDep('yum')
> > > Loaded plugins: rhnplugin
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in ?
> > > AttributeError: 'MetaSack' object has no attribute 'returnPackagesByDep'

So the rhnplugin is loaded. Any other thoughts?

**Comment by liedekef** [comment]
```
Loaded plugins: rhnplugin
Traceback (most recent call last):
  File "t.py", line 3, in ?
    my.pkgSack.returnPackagesByDep('yum')
AttributeError: 'MetaSack' object has no attribute 'returnPackagesByDep'
```

So the rhnplugin is loaded for me too. It would be weird otherwise: the whole yum command is python based ...

**Comment by c0rner** [comment]
This is most likely the same bug I reported a while ago #1781 which skvidal for some reason was unable to reproduce.  The thing is is works perfectly on CentOS but will fail on RHEL so like it is something with the rhn integration.

edit, also the bug will go away if you rename the yum module, for example to yum2
edit2: also it seems to only affect packages with a dash '-' in the name

**Comment by mpdehaan** [comment]
I don't have access to a RHN integrated RHEL machine right now.

If someone wants to attempt a fix that would be fantastic.

**Comment by liedekef** [comment]
I copied the script ansible creates for installing packages to one server that has the issue and called it "yum":

```
[root@xxxxx]# ./yum 
{"msg": "No Package matching 'nrpe' found available, installed or updated", "failed": true, "changed": false, "results": [], "rc": 0}
```

I then renamed that file to "test" and executed it again:

```
[root@xxx]# mv yum test
[root@xxx]# ./test 
{"msg": "", "changed": true, "results": ["\n================================================================================\n Package\n        Arch     Version      Repository                                   Size\n================================================================================\nInstalling:\n nrpe   x86_64   2.13-1.el5   rhel-x86_64-server-5-epel  224 k\n\nTransaction Summary\n================================================================================\nInstall       1 Package(s)\nUpgrade       0 Package(s)\n\nTotal download size: 224 k\n\nInstalled:\n  nrpe.x86_64 0:2.13-1.el5                                                      \n\n"], "rc": 0}
```

So, apparently renaming the module (or at least the script generated) will solve the issue.
On the other hand, the behaviour is the same for all packages, not just those containing "-" in their name (I used "nrpe" here).

Edit: I confirm by copying the module yum to "install_yum", it seems to be working just fine.

**Comment by mpdehaan** [comment]
It sounds like there may be an issue with the yum rhn plugin needing to fully quality the path to yum if it is in fact shelling out to yum, which it clearly should NOT be doing and should just be using the yum API.

Does that seem to be an accurate description of what may be happening here?

I know we have a lot of RHEL users and we haven't been getting many complaints so I want to understand in what situations we get into this problem.

**Comment by liedekef** [comment]
I believe you're right here (since by just changing the name it works).
Also: probably most of the RHEL users also have the yum-utils package installed, so they don't have this issue :-)

**Comment by mpdehaan** [comment]
Oh, I see.  Got it, that makes me less worried.

So we could just make it an error if yum-utils wasn't installed on RHEL (5)
short term.

**Comment by liedekef** [comment]
If you don't mind, I would appreciate not to: it requires yet another package to be installed.

**Comment by mpdehaan** [comment]
I'll accept fixes, though that appears to be the short term solution.

**Comment by michel-slm** [comment]
Just a note - while @c0rner noted that the problem does not occur on CentOS, Scientific Linux 5.9 behaves the same as RHEL. Installing yum-utils on the machines I manage now, as a workaround

**Comment by lwade** [comment]
So are we looking to just put a warning into the yum module?  Something like:

``````
if platform.linux_distribution() = BLA
    yum = yum.YumBase()
        if not yum.rpmdb.searchNevra(name='yum-utils'):
            module.fail_json(msg='Error yum-utils must be installed on the target system', changed=False)```
``````

... or is this not acceptable since package management just doesn't work at all on some RHEL5-based systems?

**Comment by mpdehaan** [comment]
@lwade I would suspect that is reasonable for proper values of 'BLA'.

**Comment by blocke** [comment]
I believe I'm also seeing this issue on RHEL 6 in addition to RHEL 5 with Ansible 1.2.

I just did a "Minimal" install of RHEL 6 from the DVD image then tried to run a playbook against the fresh minimal system.

I have the following in the playbook:
- name: rhel-common/core-packages - install common packages
  yum: name=$item state=present
  with_items:
  - etckeeper
  - git
  - vim-enhanced
  - wget
  - logrotate
  - joe
  - screen
  - tmux
  - iptables
  - ntp
  - postfix
  - sysstat
  - strace
  - lsof
  - logwatch
  - monit

On this system etckeeper and git install OK but then it fails out on vim-enhanced giving the same error as in the original report.  Installing yum-utils makes the issue go away.

I'd say this issue is not specific to RHEL 5 but also applies to RHEL 6.

**Comment by mpdehaan** [comment]
I think we should add some notice when yum-utils isn't installed, yes.

Though it seems to be installed in most cases, it eliminates the question
when it is not.

**Comment by piotr1212** [comment]
I have the same issue with rhel 6.4 with ansible 1.1. I've added this to my playbook as workaround...

```
- name: install yum-utils
  raw: rpm -q yum-utils || yum -y install yum-utils
```

**Comment by bschlemmer** [comment]
Not sure how much interest there still is in this issue but I've managed to track the behaviour down to /usr/lib/yum-plugins/rhnplugin.py.

Particularly the lines:

```
# diff -u rhnplugin.py rhnplugin.py.orig
--- rhnplugin.py        2013-09-18 18:16:07.000000000 +0100
+++ rhnplugin.py.orig   2013-09-18 18:10:18.000000000 +0100
@@ -92,9 +92,8 @@
         return 

     # check commands and options which don't need network communication
-    prog_name = sys.argv[0]
-    if prog_name == '/usr/bin/yum':
+    prog_name = os.path.basename(sys.argv[0])
+    if prog_name == 'yum':
         cmd_args = sys.argv[1:]
         if ('--help' in cmd_args
             or '--version' in cmd_args
```

The above only gets called in what_provides() when repoquery is not available. I'm not sure what the rationale from RH is here nor if it's possible to override any variables in the yum object that's created to "adjust" this behaviour. The latter may be the wrong thing to do anyhow.

So as Michael suggests this doesn't look like an Ansible issue but a problem with the RHN plugins that ship with RHEL.

**Comment by jimi-c** [comment]
Thanks, I've been trying to replicate this for a while on a RHEL5.9 box and was unable to. I think overall we're leaning towards just requiring yum-utils being installed to avoid running into this issue.

**Comment by jimi-c** [comment]
After talking about this, we feel it may be too impacting to force yum-utils to be installed, so I'm cancelling the above PR and we'll add a note in the documentation regarding repoquery/yum-utils when using the yum-rhn-plugin. Thanks everyone who reported/tested this!

**Comment by ex-nerd** [comment]
This was terribly confusing to figure out why I could run ansible in CentOS but not RHEL.  The "note in the documentation" is apparently no longer in http://docs.ansible.com/yum_module.html  Would it be worthwhile to at least add an error message when using yum-rhn-plugin that yum-utils is required?  This would guarantee that people actually see the message when working with a playbook rather than having to have sought it out specifically in the documentation for a command that "used to work (in another nearly identical distro)".

**Comment by sqrlmstr5000** [comment]
I'm running into this issue. Our University operates it's own RHN Satellite. I did install yum-utils on the target client I'm trying to configure and still get the error:

```
No Package matching 'ntp' found available, installed or updated
```

It detects if I already have a package installed, but won't install new ones.

Just installed ansible 1.4.4 via pip

**Comment by jctanner** [comment]
@ex-nerd and @tsquillario please move dicussions to either the mailing list or a new bug. Closed tickets are usually not monitored.
