### ISSUE TITLE
Iptables restart brakes current SSH connections

### ISSUE THREAD

**Issue by DavorSaric** [ansible/ansible#20033]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

service

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### OS / ENVIRONMENT
```
CentOS Linux release 7.3.1611 (Core) 
```

##### SUMMARY

I am logged in server over SSH. When I run service module to restart iptables, the current SSH connections hang and eventually timeout and disconnect. I have to open another terminal to ssh to server again.

Also I have tried with ansible -m shell -a "systemctl restart iptables" and it also brakes connections.

Restarting manually iptables on server it doesn't brake SSH connection.

I am using "become true" and sudo,

**Comment by alikins** [comment]
Was this working before? If so, in what versions?

Is there an example playbook available?

> Restarting manually iptables on server it doesn't brake SSH connection.

  Restarting via 'systemctl restart iptables' ?

Any logs in the journal from the iptables restart that fails? (And ideally, one from when it succeeds).

**Comment by DavorSaric** [comment]
Didn't test it before, I started using Ansible 2 months ago.

On all servers with various configurations the systemctl restart iptables doesn't brake ssh connections.
When I run this:
ansible  -m shell -a "service iptables restart" all  - this brakes SSH connections

Or via some task with
```
notify:
   - restart iptables
```

handler is:
```
- name: restart iptables
  service: name=iptables state=restarted
```

Log part when restarting manually in CLI on server via systemctl restart iptables
```
Jan 10 03:45:41 hostname polkitd[479]: Registered Authentication Agent for unix-process:32750:163478457 (system bus name :1.8136 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/Authentic
Jan 10 03:45:41 hostname systemd[1]: Stopping IPv4 firewall with iptables...
Jan 10 03:45:41 hostname iptables.init[32756]: iptables: Setting chains to policy ACCEPT: filter [  OK  ]
Jan 10 03:45:41 hostname iptables.init[32756]: iptables: Flushing firewall rules: [  OK  ]
Jan 10 03:45:41 hostname iptables.init[32756]: iptables: Unloading modules: [  OK  ]
Jan 10 03:45:41 hostname systemd[1]: Starting IPv4 firewall with iptables...
Jan 10 03:45:41 hostname kernel: ip_tables: (C) 2000-2006 Netfilter Core Team
Jan 10 03:45:41 hostname kernel: nf_conntrack version 0.5.0 (7897 buckets, 31588 max)
Jan 10 03:45:41 hostname iptables.init[345]: iptables: Applying firewall rules: [  OK  ]
Jan 10 03:45:41 hostname systemd[1]: Started IPv4 firewall with iptables.
Jan 10 03:45:41 hostname polkitd[479]: Unregistered Authentication Agent for unix-process:32750:163478457 (system bus name :1.8136, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected
```
Log when restarting via Ansible task or command:
```
Jan 10 03:51:52 hostname sudo[899]: username : TTY=unknown ; PWD=/home/username ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zmsadfgsdfgsdfgsdgfsdfg; /usr/bin/python
Jan 10 03:51:52 hostname python[902]: ansible-command Invoked with warn=True executable=None _uses_shell=True _raw_params=systemctl restart iptables removes=None creates=None chdir=None
Jan 10 03:51:52 hostname systemd[1]: Stopping IPv4 firewall with iptables...
Jan 10 03:51:52 hostname iptables.init[908]: iptables: Setting chains to policy ACCEPT: filter [  OK  ]
Jan 10 03:51:52 hostname iptables.init[908]: iptables: Flushing firewall rules: [  OK  ]
Jan 10 03:51:52 hostname iptables.init[908]: iptables: Unloading modules: [  OK  ]
Jan 10 03:51:52 hostname systemd[1]: Starting IPv4 firewall with iptables...
Jan 10 03:51:52 hostname kernel: ip_tables: (C) 2000-2006 Netfilter Core Team
Jan 10 03:51:52 hostname kernel: nf_conntrack version 0.5.0 (7897 buckets, 31588 max)
Jan 10 03:51:52 hostname iptables.init[966]: iptables: Applying firewall rules: [  OK  ]
Jan 10 03:51:52 hostname systemd[1]: Started IPv4 firewall with iptables.
```
Do you have this problem on servers via ansible restarting iptables?

**Comment by oboukili** [comment]
My current experience with this issue is that it only happens during the intial iptables rules setup.
My workaround is to launch a shell command asynchronously:

```
- name: Ensure firewall is started (fire and forget)
  shell: >
    sleep 5s && service iptables start
  become: true
  async: 10
  poll: 0
```

This way Ansible will not ever wait for a task acknowledgment that is never coming.

**Comment by DavorSaric** [comment]
This is something kernel related I would say - test it on rackspace vps, you get connection breaking. On linode it doesn't brake. The second provider has their own kernel to boot and lsmod is empty so who knows, maybe some module needs to be loaded for that...

**Comment by DavorSaric** [comment]
This is something kernel related I would say - test it on rackspace vps, you get connection breaking. On linode it doesn't brake. The second provider has their own kernel to boot and lsmod is empty so who knows, maybe some module needs to be loaded for that...

**Comment by sdodson** [comment]
Yeah, we do the same as @oboukili suggested.

**Comment by nodiscc** [comment]
I had the same problem (with [FireHOL](https://firehol.org/) which is an iptables wrapper/stateful firewall builder) and fixed it by loading the `nf_conntrack_ipv4` kernel module before starting the firewall

```yaml
- name: copy firewall configuration
  template: [...]

# prevents firewall initialization from severing the SSH connection
- name: load the nf_conntrack_ipv4 module
  modprobe:
    name: nf_conntrack_ipv4
    state: present

- name: install firehol firewall packages
  apt:
    package:
      - firehol
      - firehol-tools
    state: present
```

Debian 9, ansible 2.8.0

**Comment by bcoca** [comment]
closing as per above, this is not an ansible bug.
