### ISSUE TITLE
sysctl check_after failing on multi-value sysctl parameters

### ISSUE THREAD

**Issue by rrtj3** [ansible/ansible#2004]
When using the sysctl module to set a multi-value kernel parameter it fails on the check_after check. Seems to simply be a spacing issue:

Here is the playbook task:

``` yaml
    - name: set sysctl kernel.sem
      action: sysctl name=kernel.sem value='250 32000 100 128' state=present
```

Here is the error that is received:

``` bash
TASK: [set sysctl kernel.sem] ********************* 
failed: [dba88.pvt.hawaii.edu] => {"failed": true}
msg: checks_after failed with: key seems not set to value even after update/sysctl, founded : <250      32000   100     128>, wanted : <250 32000 100 128>
```

I've been able to work around the issue by adding the 'checks=before' to the task but the module should strip the whitespace before the check_after verify comparison.

``` bash
[itssa@ppt75 ~/db]$ ansible --version
ansible 1.0
```

**Comment by davixx** [comment]
Sorry to leave a three time comment.

Thank you romeotheriault to open an issue for this module, i hope so solve that tomorrow. But it may take few day.

**Comment by rrtj3** [comment]
NP. Thanks for the fast response.
