### ISSUE TITLE
remote_user on task level not working when ansible_user defined in inventory

### ISSUE THREAD

**Issue by marcinhlybin** [ansible/ansible#20045]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
remote_user and ansible_user

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### CONFIGURATION
defaults

##### OS / ENVIRONMENT
N/A

##### SUMMARY

When ansible_user is defined in inventory file for particular host, remote_user defined on task level does not set user SSH user.

##### STEPS TO REPRODUCE

inventory:
```
app01 ansible_host=192.168.44.11 ansible_user=app01admin
```

Task:
```yaml
- name: "Clone git repository"
  remote_user: app_user
  become: no
  git:
    repo: **************
    dest: **************
    accept_hostkey: yes
```

Works fine when ansible_user is not defined in inventory but specified with `-u` argument in command line or as `remote_user` on playbook level.

##### EXPECTED RESULTS

Important parts:
* User=app01admin
* User=app_user

```
TASK [setup] *******************************************************************
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/core/system/setup.py
<192.168.44.11> ESTABLISH SSH CONNECTION FOR USER: app01admin
<192.168.44.11> SSH: EXEC ssh -o ForwardAgent=yes -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=app01admin -o ConnectTimeout=10 192.168.44.11 '/bin/sh -c '"'"'sudo -H -S -n -i -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-dpdzknxuhnrsmyuwfgzaxiysgerxeadi; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
ok: [app01]

TASK [app-doccopy : Clone git repository] *****
task path: /Users/ahes/Workspace/yaya/ansible-yaya/roles/app-doccopy/tasks/main.yml:41
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/core/source_control/git.py
<192.168.44.11> ESTABLISH SSH CONNECTION FOR USER: app_user
<192.168.44.11> SSH: EXEC ssh -o ForwardAgent=yes -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=app_user -o ConnectTimeout=10 192.168.44.11 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
```

##### ACTUAL RESULTS

Important parts:
* User=app01admin
* User=app01admin

```
TASK [setup] *******************************************************************
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/core/system/setup.py
<192.168.44.11> ESTABLISH SSH CONNECTION FOR USER: app01admin
<192.168.44.11> SSH: EXEC ssh -o ForwardAgent=yes -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=app01admin -o ConnectTimeout=10 192.168.44.11 '/bin/sh -c '"'"'sudo -H -S -n -i -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-dpdzknxuhnrsmyuwfgzaxiysgerxeadi; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
ok: [app01]

TASK [app-doccopy : Clone git repository] *****
task path: /Users/ahes/Workspace/yaya/ansible-yaya/roles/app-doccopy/tasks/main.yml:41
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/core/source_control/git.py
<192.168.44.11> ESTABLISH SSH CONNECTION FOR USER: app_user
<192.168.44.11> SSH: EXEC ssh -o ForwardAgent=yes -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=app01admin -o ConnectTimeout=10 192.168.44.11 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

As documented http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable, the connection variables have precedence over directives, this is done as host connection information is considered more 'specific' than play connection information. You can still override this from the play by setting the connection variable (as you would any variable).

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by techraf** [comment]
@bcoca This information is actually missing from the "2.x" list in the referenced document (and anything "inventory" is of lower priority than a play or a task).

Shouldn't it be explicitly added before "extra vars (always win precedence)" like for 1.x?

**Comment by bcoca** [comment]
@techraf you are confusing variable precedence with 'setting precedence' which can be provided by keyword, env var, cli option, config file entry OR a specific variable.

**Comment by techraf** [comment]
@bcoca You stated above: "**the connection variables** have precedence over directives" and the page you referenced states "*connection variables (`ansible_user`, etc.)*" for Ansible 1.x.

This information is missing from 2.x section.

I don't get what **I am** confusing here. Both Ansible 1.x and 2.x behave the same regarding this setting.

**Comment by bcoca** [comment]
that is not specific to 1.x only the variable precedence lists are specific per version

**Comment by techraf** [comment]
I was trying to make you realize it was not 1.x specific. I’m glad you agreed.

The page you referenced lists:

“*In 1.x, the precedence is as follows []*”

“*In 2.x, we have made the order of precedence more specific []*”

And since this is not 1.x specific, “connection variables (`ansible_user`, etc.)” should be listed in both lists (just like “extra cars” are).

**Comment by bcoca** [comment]
connection variables are discussed AFTER both lists
