### ISSUE TITLE
Git submodule support is broken.

### ISSUE THREAD

**Issue by MeanEYE** [ansible/ansible#20081]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`git`

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /home/meaneye/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Only thing in `~/.ansible.cfg` is `nocows` and `inventory`.

##### OS / ENVIRONMENT

System running the playbook:

Distributor ID:	Debian
Description:	Debian GNU/Linux testing (stretch)
Release:	testing
Codename:	stretch

Linux bytewiper 4.8.0-2-amd64 #1 SMP Debian 4.8.15-2 (2017-01-04) x86_64 GNU/Linux

Target system:

CentOS release 6.8 (Final)
Linux way2cu-usa1.com 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
git version 1.7.1

##### SUMMARY
Cloning online repository fails with message stating submodules couldn't be initialized. Debug message provided indicates that `git` received incorrect parameters.

##### STEPS TO REPRODUCE
```yaml
- name: Cloning specified Caracal branch
  git: repo=https://github.com/Way2CU/Caracal.git
        dest={{ site_directory }}
        recursive=yes
        force=yes
        version="{{ site.caracal_branch }}"
```

##### EXPECTED RESULTS
Cloned repository with all the submodules checked out.

##### ACTUAL RESULTS
Playbook stops with critical error shown as following:

```
fatal: [...]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to init/update submodules: Usage: git submodule [--quiet] add [-b branch] [--reference <repository>] [--] <repository> [<path>]\n   or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]\n   or: git submodule [--quiet] init [--] [<path>...]\n   or: git submodule [--quiet] update [--init] [-N|--no-fetch] [--rebase] [--reference <repository>] [--merge] [--recursive] [--] [<path>...]\n   or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]\n   or: git submodule [--quiet] foreach [--recursive] <command>\n   or: git submodule [--quiet] sync [--] [<path>...]\n"}
	to retry, use: --limit @/home/meaneye/Development/Workspace/.../deploy/deploy.retry
```

To get around issue, logging into server and manually executing `git submodule init` followed by `git submodule update` make Ansible skip this task marking it as passed.

**Comment by abadger** [comment]
This looks like an incompatibility with older git versions.  Checking about it.

**Comment by abadger** [comment]
Looks like older versions of git (of which centos6 has an older git) do not support the ```--force``` flag with the ```git submodule``` command.  As a workaround, if you remove the ```force: True``` flag this should start working.

@robinro do you have any thoughts on whether we should attempt to work around this in code?

**Comment by robinro** [comment]
@abadger One could try to work around this, but I lack the time (and motivation) to do this at the moment. Also it might be tricky to find a general solution and git-version dependent subfunctions are ugly.

For `depth` the solution was to only support newer git versions, that "fully" support it. One could add a similar comment to the submodule argument.

**Comment by MeanEYE** [comment]
Force part is sometimes required though. Without it if there are any changes on remote server playbook will just fail and will require manual intervention. In my case `force` is only needed when checking out the main repository and not submodules. Am not sure where this error occurs but I can certainly modify my scripts to not require `force` parameter. Thanks!

**Comment by siedentop** [comment]
For git version [1.8.1][1] using `git submodule foreach git checkout --force` should yield the desired effect. 

> If --force is specified, the submodule will be checked out (using git checkout --force if appropriate), even if the commit specified in the index of the containing repository already matches the commit checked out in the submodule. [From Docs version 2.11.1]

[1]: https://www.git-scm.com/docs/git-submodule/1.8.1
