### ISSUE TITLE
In Ansible 2.2, dynamic inventory variables now override inventory group_var variables

### ISSUE THREAD

**Issue by wheelybird** [ansible/ansible#20135]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
group vars

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Default settings 

##### OS / ENVIRONMENT

Ubuntu 16.04 LTS && 14.04 LTS

##### SUMMARY

The precedence of variables within an inventory has changed between Ansible 2.0.2.0 and 2.2.0.0 in that variables in inventory/group_vars/ no longer override dynamic vars.

We've inherited some Ansible that deploys to various different environments.  It uses a Python script in each directory to load in some common variables, and those variables are overridden per inventory by including the values in `inventory/group_vars`.
This has been working until we upgraded from Ansible 2.0.2.0 to 2.2.0.0

##### STEPS TO REPRODUCE

A basic version of what we're using is as follows:

**Layout**
```
├── inventory
│   ├── common.yml
│   └── test
│       ├── common_vars.py
│       ├── group_vars
│       │   └── all
│       │       └── main.yml
│       └── hosts
└── test.yml
```
   
**test.yml**   
```
---
- hosts: berty
  connection: local

  tasks:

    - debug: var=our_variable
```
   
**inventory/common.yml**
```
---
our_variable: "quite common"
```   

**inventory/test/common_vars.py**
```
#! /usr/bin/env python

import os
import sys
import json

import yaml

all = open(os.path.abspath(os.path.join(os.path.dirname(sys.argv[0]), '..', 'common.yml')))
all = ((yaml.load(all)).copy())
json.dump({"all": {"vars": all}}, sys.stdout, indent=4)
```   

**inventory/test/group_vars/all/main.yml**
```
---
our_variable: "very limited"
```   

**inventory/test/hosts**
```
[berty]
127.0.0.1
```

##### EXPECTED RESULTS

```
# ansible-playbook test.yml -i inventory/test/                                                                        

PLAY [berty] *******************************************************************

TASK [setup] *******************************************************************
ok: [127.0.0.1]

TASK [debug] *******************************************************************
ok: [127.0.0.1] => {
    "our_variable": "very limited"
}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   
```
##### ACTUAL RESULTS

```
ansible-playbook test.yml -i inventory/test/                                                                        

PLAY [berty] *******************************************************************

TASK [setup] *******************************************************************
ok: [127.0.0.1]

TASK [debug] *******************************************************************
ok: [127.0.0.1] => {
    "our_variable": "quite common"
}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by manjitkumar** [comment]
This behavior varies between ansible==2.1.0 and ansible==2.1.2

**Comment by absolutejam** [comment]
Not sure if this is related, but I'm finding if I don't explicitly specify the inventory file when running a dynamic inventory, the `group_vars` are ignored (Ansible 2.2.1.0).

In my `ansible.cfg`, I have `inventory      = /etc/ansible/inventory`, which automatically picks up my dynamic inventory stored at `/etc/ansible/inventory/ldap/ldap_winservers.py`. Then, when running `ansible ldap_winservers -m win_ping`, it defaults back to trying ssh, but adding `-i /etc/inventory/ldap/ldap_winservers.py` correctly uses the group vars stored at `/etc/ansible/inventory/ldap/group_vars/ldap_winservers`.

**Comment by absolutejam** [comment]
Is there any way around this? I'm in an awkward situation, wherein I need to use a dynamic inventory to find my hosts, but I have some static groups defined that are used to build a config file. 

If I **do not** explicitly specify the dynamic inventory directly, it detects all of the groups in my multiple inventory files under `/etc/ansible/inventory`, but then cannot connect to my server as it doesn't pick up the correct auth method. This is stored inside of a `group_vars` file, used by a static host group - **Could it be that I'm doing this wrong?**

If I **do** explicitly specify the dynamic inventory, it is able to connect as it picks up the `group_vars` containing the connection info, but obviously doesn't scrape all of the different host groups from my other inventory files. This is a bit of a workflow-killer for me.

**Comment by absolutejam** [comment]
FYI, building in the connection variables that I normally store in `group_vars` (`ansible_user`, `ansible_connection`, etc.) directly into my dynamic inventory (Under the `'_meta': { 'hostvars': ... } ` section) has remedied this as a workaround.

So, is the dynamic inventory passing back null values for these variables and overriding the statically defined ones in inventory/`group_vars`?

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

This is not an issue with inventory variables vs group_vars, its is a host variable, which always has precedence.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
