### ISSUE TITLE
Vulnerability needs to be addressed but Latest RC instructs not to use 

### ISSUE THREAD

**Issue by pmmenzel** [ansible/ansible#20157]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
Vulnerability:  https://bugzilla.redhat.com/show_bug.cgi?id=1404378

Basically this report says there is a know vulnerability but according to your latest release: https://github.com/ansible/ansible/releases/tag/v2.2.1.0-0.3.rc3  It says not to use it.  

We'd like to patch this sooner than later but not sure if there's a viable fix out yet.  Please advise
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by abadger** [comment]
This is a late rc so you should feel free to use it if you want to get a head start on running code that fixes the vulnerability.  Note that later today we'll have another rc with some more fixes.

If you need more information, feel free to contact us in #ansible-devel on irc.freenode.net.

**Comment by bcoca** [comment]
@pmmenzel the page did not say to not use the latest release, just that tarball. I updated the message to make clear that our releases are NOT using that github facility (we cannot remove or hide).
