### ISSUE TITLE
Group depths are incorrectly assigned by the default inventory parser

### ISSUE THREAD

**Issue by zsolt-erl** [ansible/ansible#2016]
group.py incorrectly calculates group depth. This can cause groups on different levels to have the same depth. In turn this can result in reading the files under 'group_vars/' in the wrong order which means that a higher level group can overwrite a lower level group variable.

Here's the fix for group.py:

``` python
diff --git a/lib/ansible/inventory/group.py b/lib/ansible/inventory/group.py
index a460b48..88231a4 100644
--- a/lib/ansible/inventory/group.py
+++ b/lib/ansible/inventory/group.py
@@ -36,7 +36,10 @@ class Group(object):
         if self == group:
             raise Exception("can't add group to itself")
         self.child_groups.append(group)
-        group.depth = group.depth + 1
+        group.depth = self.depth + 1
         group.parent_groups.append(self)

     def add_host(self, host):
```

**Comment by mpdehaan** [comment]
Hi @zsolt-erl can you submit this as a pull request?

I'd like to include attribution to you in the source.

See https://help.github.com/articles/using-pull-requests if you need help!

**Comment by dhozac** [comment]
Note that it should be max([group.depth, self.depth + 1]) to get the correct value.

**Comment by mpdehaan** [comment]
Committed 0ad6ac4 per @dhozac's suggestion

Thanks folks!
