### ISSUE TITLE
apt module not idempotent during remove if package not in cache

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#2017]
If I attempt to remove a package that is not installed and not in the apt-cache, the following happens:

task

```
- apt: name=$pkg_name state=removed purge=yes
  when_string: $ansible_pkg_mgr == 'apt'
```

output

```
TASK: [apt name=mypackage state=removed purge=yes] ********************* 
failed: [myhost] => {"failed": true, "item": ""}
msg: No package matching 'mypackage' is available
```

The module shouldn't fail when this occurs.  The yum module does not fail in this situation.  I believe the problem needs to be fixed in one of two places:

 Here perhaps we should pass the "state" to package_status and if state is absent  then we don't try to check the cache

```
def package_status(m, pkgname, version, cache):
    try:
        pkg = cache[pkgname]
    except KeyError:
        m.fail_json(msg="No package matching '%s' is available" % pkgname)
```

or  here we could just avoid the package_status line altogether, check the output of cmd, and if it contains: "E: Unable to locate package blahblah", exit cleanly.

```
def remove(m, pkgspec, cache, purge=False):
    packages = ""
    for package in pkgspec:
        name, version = package_split(package)
        installed, upgradable = package_status(m, name, version, cache)
        if installed:
            packages += "'%s' " % package

    if len(packages) == 0:
        m.exit_json(changed=False)
    else:
        purge = '--purge' if purge else ''
        cmd = "%s -q -y %s remove %s" % (APT, purge,packages)
        rc, out, err = m.run_command(cmd)
        if rc:
            m.fail_json(msg="'apt-get remove %s' failed: %s" % (packages, err))
        m.exit_json(changed=True)
```

Let me know the direction that you'd like me to go in, and I'll work on a patch/pull request.
- James

**Comment by mpdehaan** [comment]
Yeah, it's better if we can decide to not run the removal command if the package is already gone.

Thanks!
