### ISSUE TITLE
Yum-Repository Module Documentation Error (Seemingly)

### ISSUE THREAD

**Issue by mpender** [ansible/ansible#20179]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME
Yum

##### ANSIBLE VERSION
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['../library/']

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Documentation lists handler function for 'yum-clean-metdata' but the handler in the example shows 'yum-clean-all' 

Looks like a typo as the play would fail as it cant find the handler by name? 

https://docs.ansible.com/ansible/yum_repository_module.html

**Comment by BondAnthony** [comment]
@jctanner can this be closed?

**Comment by jctanner** [comment]
resolved_by_pr https://github.com/ansible/ansible/pull/20499
