### ISSUE TITLE
better callback context

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#2018]
In Stephen's work to build a database logger, and in mine to produce better diffs, it seems that callbacks could really benefit from knowing a _context_ of what happens when the callback is called.

Rather than breaking the callback API of anyone who doesn't have **kwargs on all of their callbacks, I'm tentatively thinking of just setting a variable called "context" in each
callbacks class, which will be named tuple (probably) and contain the reference to the current play object, task object, etc, and so on.   

This could be accessed in all of the callbacks as self.context

(This could eventually even result for the ability of all callbacks to be internally queued so things like diff output to the screen didn't interlace, but that's not a priority)

cc @sfromm @skvidal

I believe Seth was also asking about having things like timing information.

All of this will be needed if we are to log into a database schema that ever gets fully normalized, but that's another monster altogether :)

**Comment by skvidal** [comment]
Since each play object contains the playbook object as well, I think that would be all that is necessary - the only piece I'm unclear on is if the play object knows which play it is in the set of plays.

Would making this a dictionary instead of a tuple help? That way additional context objects could be added w/o breaking the api?

I know kwargs aren't always attractive but it's more testable than a tuple is for other callbacks.

(re-education on the above idea is welcome)

**Comment by mpdehaan** [comment]
yeah It should be a dict, I am being brain dead.

And also correct on the play object (or task object) -- the playbook can be found by walking up.

We have to make sure that context makes it into the runner callbacks too, so the runner constructor probably needs to be able to be passed the task object if not already.

**Comment by mpdehaan** [comment]
additional note -- if is is possible to give the context a runner instance some folks would like that, so they can make additional ansible calls after a playbook completes (maybe).  Would be nice to have.

**Comment by mpdehaan** [comment]
I kept this super simple:

0d11f53eff624441b72df172057e0afd0ebd5a2d

Callbacks now have access to a ".playbook" and a ".runner' object.

Playbook objects are only set on ansible-playbook.

It does not currently set the current play object, so adding that shortly.

**Comment by mpdehaan** [comment]
See also 42b0e51223562bcf94d23cec8518c60606927e58 which adds .play and .task

You will want to use getattr as they may not always be set.

task is None during the setup step.
