### ISSUE TITLE
Support the `runit` service manager

### ISSUE THREAD

**Issue by jsumners** [ansible/ansible#20181]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
module: service

##### SUMMARY
Ansible 2.3 is getting support for managing packages with the [xbps][xbps] package manager -- https://github.com/ansible/ansible/blob/f078946ed3bf5baa353d298158b325ce9ab9f313/lib/ansible/modules/packaging/os/xbps.py . This is a wonderful development.

However, along with xbps support should come support for the [runit][runit] service manager. The only distribution that uses xbps to manage packages is [Void Linux][void] and it uses runit for service management. At the very least, it would be nice to have `start`, `stop`, and `restart` available. The possible commands are listed at -- http://smarden.org/runit/sv.8.html

[xbps]: https://github.com/voidlinux/xbps
[runit]: http://smarden.org/runit
[void]: http://voidlinux.eu/

**Comment by bcoca** [comment]
we have a daemontools module, it woudl not be hard to add/create new one to support runit http://docs.ansible.com/ansible/svc_module.html
