### ISSUE TITLE
python2.5 support for ansible and ansible-playbook

### ISSUE THREAD

**Issue by egon1024** [ansible/ansible#202]
Downloaded ansible for the first time this morning and am trying to run through it.  I installed the multiprocessing module (I'm running on Python 2.5) via pip.  I got the following:

```
ctuininga@erbium$ ansible all -m ping --ask-pass
/home/ctuininga/ansible/ansible/lib/ansible/connection.py:24: Warning: 'with' will become a reserved keyword in Python 2.6
Traceback (most recent call last):
  File "/home/ctuininga/ansible/ansible/bin/ansible", line 27, in <module>
    import ansible.runner
  File "/home/ctuininga/ansible/ansible/lib/ansible/runner.py", line 34, in <module>
    import ansible.connection
  File "/home/ctuininga/ansible/ansible/lib/ansible/connection.py", line 24
    with warnings.catch_warnings():
                ^
SyntaxError: invalid syntax
```

Using the "with" statement in Python 2.5 requires a "from **future** import with_statement"

In case it somehow turns out to be relevant, my platform is Python 2.5.6 running on FreeBSD 7.2

**Comment by egon1024** [comment]
I added the "from future" statement locally which led to my next 2.5 error ... the warnings module does not have a catch_warnings attribute:

```
ctuininga@erbium$ ansible all -m ping --ask-pass
Traceback (most recent call last):
  File "/home/ctuininga/ansible/ansible/bin/ansible", line 27, in <module>
    import ansible.runner
  File "/home/ctuininga/ansible/ansible/lib/ansible/runner.py", line 34, in <module>
    import ansible.connection
  File "/home/ctuininga/ansible/ansible/lib/ansible/connection.py", line 25, in <module>
    with warnings.catch_warnings():
AttributeError: 'module' object has no attribute 'catch_warnings'
```

**Comment by mpdehaan** [comment]
Yeah, I'm not sure we should claim support for 2.5 on the ansible client.   We support all the way down to 2.4 on the nodes, but there are nice things in 2.6 I'd like to use, and RHEL 6 already has 2.6.

This also means someone doesn't have to go out of their way to get the multiprocessing module to work.

**Comment by egon1024** [comment]
Ansible looks pretty damned cool, so I'm wondering if you'll be willing to take patches for 2.5 support if I'm willing to put them together.  If it's just not something you're interested in, I certainly understand.  :)

**Comment by mpdehaan** [comment]
Hmm, maybe.  See what you can do to tolerate that warnings line.  If it does not ignore that warning on py2.5 it may be ok.

The setup of the multiprocessing lib may be another factor that is tricky for some, so py2.6 (maybe with virtualenv) is definitely better, but I understand that not everyone may have access to a recent OS so I wouldn't like to close off that potential usebase, especially if those folks are willing to help maintain it.

So yeah, see what you can find out.

**Comment by mpdehaan** [comment]
closing this, can take pull requests, not something I'm actively going to work on but open to upgrades.

**Comment by mpdehaan** [comment]
to clarify, I'm going to go ahead and make the call that we require 2.6 for ansible and 2.4 for managed machines
