### ISSUE TITLE
Pathing for local_action / shell steps has unexpectedly changed between ansible 2.1.0.0 and 2.1.4.0-0.2.rc2

### ISSUE THREAD

**Issue by dpedu2** [ansible/ansible#20245]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
General playbook usage?

##### ANSIBLE VERSION
```
ansible 2.1.4.0
  config file = /some/private/dir/rt/ansible/ansible.cfg
  configured module search path = ['/some/private/dir/admcommon/ansible/library/']
```

##### CONFIGURATION
Please see #20243

##### OS / ENVIRONMENT
Ubuntu 14.04.5 64 bit.

##### SUMMARY
In ansible 2.1.0.0, the cwd for local_action shell steps OR shell steps under `hosts: localhost` was equal to the cwd of where the ansible-playbook command was invoked from.

In ansible 2.1.4.0-0.2.rc2, the cwd has been changed to the directory of the playbook containing the step.

##### STEPS TO REPRODUCE
- Run a playbook on 2.1.0.0 and 2.1.4.0
- Note that the cwd used in local_action shell steps is different

```yaml
- hosts: my_node
  gather_facts: False
  tasks:
  - local_action: shell pwd

- hosts: localhost
  gather_facts: False
  tasks:
  - local_action: shell pwd
```

The above playbook is in /tmp/cwd.yml

When run in ansible 2.1.0.0, both of these steps print the cwd of my shell from which I invoked the ansible-playbook command.

When run in ansible 2.1.4.0-0.2.rc2, both of these steps print "/tmp" as the current dir.

##### EXPECTED RESULTS
Since only the "patch" version of ansible has been incremented, I expect NO breaking changes between the version.

##### ACTUAL RESULTS
There is a breaking change between the versions (note the different path in the stdout for the pwd commands changes when I downgrade Ansible):

```
(my_venv)ubuntu@ubuntu14:~$ pwd
/home/ubuntu
(my_venv)ubuntu@ubuntu14:~$ pip install -f https://releases.ansible.com/ansible/ ansible==2.1.4.0-0.2.rc2 > /dev/null
(my_venv)ubuntu@ubuntu14:~$ ansi
ansible           ansible-console   ansible-doc       ansible-galaxy    ansible-lint      ansible-playbook  ansible-pull      ansible-vault
(my_venv)ubuntu@ubuntu14:~$ ansible --version
ansible 2.1.4.0
  config file = /some/private/dir/rt/ansible/ansible.cfg
  configured module search path = ['/some/private/dir/admcommon/ansible/library/']
(my_venv)ubuntu@ubuntu14:~$ ansible-playbook /tmp/cwd.yml -v
Using /some/private/dir/rt/ansible/ansible.cfg as config file

PLAY [push] ********************************************************************

TASK [command] *****************************************************************
/tmp/cwd.yml:4
changed: [my_node -> localhost] => {"changed": true, "cmd": "pwd", "delta": "0:00:00.001445", "end": "2017-01-13 21:06:20.195711", "rc": 0, "start": "2017-01-13 21:06:20.194266", "stderr": "", "stdout": "/tmp", "stdout_lines": ["/tmp"], "warnings": []}

PLAY [localhost] ***************************************************************

TASK [command] *****************************************************************
/tmp/cwd.yml:9
changed: [localhost] => {"changed": true, "cmd": "pwd", "delta": "0:00:00.001319", "end": "2017-01-13 21:06:20.308361", "rc": 0, "start": "2017-01-13 21:06:20.307042", "stderr": "", "stdout": "/tmp", "stdout_lines": ["/tmp"], "warnings": []}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
my_node           : ok=1    changed=1    unreachable=0    failed=0

(my_venv)ubuntu@ubuntu14:~$ pip install ansible==2.1.0.0 > /dev/null
(my_venv)ubuntu@ubuntu14:~$ ansible --version
ansible 2.1.0.0
  config file = /some/private/dir/rt/ansible/ansible.cfg
  configured module search path = ['/some/private/dir/admcommon/ansible/library/']
(my_venv)ubuntu@ubuntu14:~$ ansible-playbook /tmp/cwd.yml -v
Using /some/private/dir/rt/ansible/ansible.cfg as config file
Please upgrade your ansible version by running `pip install -r requirements.txt`
Your version (2.1.0.0) has been deprecated due to a security vulnerability

PLAY [push] ********************************************************************

TASK [command] *****************************************************************
/tmp/cwd.yml:4
changed: [my_node -> localhost] => {"changed": true, "cmd": "pwd", "delta": "0:00:00.001437", "end": "2017-01-13 21:06:38.132568", "rc": 0, "start": "2017-01-13 21:06:38.131131", "stderr": "", "stdout": "/home/ubuntu", "stdout_lines": ["/home/ubuntu"], "warnings": []}

PLAY [localhost] ***************************************************************

TASK [command] *****************************************************************
/tmp/cwd.yml:9
changed: [localhost] => {"changed": true, "cmd": "pwd", "delta": "0:00:00.001504", "end": "2017-01-13 21:06:38.237970", "rc": 0, "start": "2017-01-13 21:06:38.236466", "stderr": "", "stdout": "/home/ubuntu", "stdout_lines": ["/home/ubuntu"], "warnings": []}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
my_node           : ok=1    changed=1    unreachable=0    failed=0
```

**Comment by sivel** [comment]
This was due to a bug that was fixed in 9255a618e307b4e087cb0f3f6f4f225f7652c298 / https://github.com/ansible/ansible/pull/16805 in order to resolve https://github.com/ansible/ansible/issues/14489

As documented in #16805

> This restores previous behaviour in pre 2.0 and allows for 'local type' plugins and actions to have a more predictable relative path

Effectively, you were relying on behavior of a bug, as opposed to expected behavior.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by dpedu2** [comment]
Regardless if it was a bug or not, why is a breaking change acceptable in a patch release?

**Comment by sivel** [comment]
I believe you are looking at it from the wrong direction.  It was a bug reported shortly after the 2.0 release, but was not resolved until after 2.1.  This was a fix for broken functionality identified as a bug, which is effectively the concept behind patch releases.

**Comment by dpedu2** [comment]
I understand, though the definition of a patch release is:

> Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior.

Since this breaks backwards compatibility, wouldn't it fall outside this definition?

**Comment by bcoca** [comment]
no, otherwise any behaviour stemming from a bug can never be fixed unless we do major releases
