### ISSUE TITLE
with_items still evaluated when placed in a block that failed a when conditional

### ISSUE THREAD

**Issue by regner** [ansible/ansible#20250]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
conditional blocks and with_items in the blocks tasks

(sorry, not sure exactly what components this would be)

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /Users/regnerblokandersen/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
macOS Serria

##### SUMMARY
While executing a playbook that has a `block` with a conditional `when` on it Ansible still evaluates any `with_items` statements within the block even if the whole block is to be skipped.

In our case we have a variable which gets set earlier in the playbook, and then if that variable is set we have a set of tasks we would like run. If the variable is not set we expect the tasks to be skipped. However since Ansible seems to be evaluating the `with_items` statement even though the task is going to be skipped it fails since the variable used is not defined.

##### STEPS TO REPRODUCE
Run the following Ansible playbook:
```yaml
---
- hosts: localhost
  tasks:
    - block:
      - name: this will be skipped properly
        shell: echo i am skipped

      - name: with items still evaluating when block is skipped
        shell: echo nothing
        with_items: "{{ not_defined }}"
      when:
        - not_defined is defined
```

##### EXPECTED RESULTS
With the conditional block failing the expectation is that the contents of the block are not run or evaluated.

##### ACTUAL RESULTS
The conditional block does fail the condition and does skip each of the sub tasks, however before skipping them it appears to evaluate the with_items statement.

```
$ ansible-playbook block-repro.yml
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [this will be skipped properly] *******************************************
skipping: [localhost]

TASK [with items still evaluating when block is skipped] ***********************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'not_defined' is undefined"}
	to retry, use: --limit @/Users/regnerblokandersen/git/benchlabs/ansible-playbooks/configuration/block-repro.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by acasademont** [comment]
Yep, same here, any workaround in the meantime?

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Conditionals are evaluated PER ITEM in EACH TASK, blocks just group tasks to inherit common directives and/or deal with error handling.  This is documented in the block page http://docs.ansible.com/ansible/playbooks_blocks.html (read 2nd paragraph).

As for the undefined error, this is clearly documented 
http://docs.ansible.com/ansible/playbooks_conditionals.html#loops-and-conditionals. 

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by regner** [comment]
@bcoca Thank you very much for that information and sorry for not having read the docs better.

@acasademont The docs suggest providing a default iterator to the with_items attribute so that is what we are now doing. :)
