### ISSUE TITLE
python3 NameError: name 'long' is not defined

### ISSUE THREAD

**Issue by Waidem** [ansible/ansible#20257]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

python3.6/site-packages/ansible/plugins/filter/core.py
##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### CONFIGURATION

---
- hosts: webs
  remote_user: root
  vars:
      random_number: "{{ 10000 | random }}"
  tasks:
  - name: Copy the /etc/hosts to /tmp/hosts
    copy: src=/etc/hosts dest=/tmp/hosts
    notify:
      - call by /tmp/hosts
  - name: Copy the /etc/hosts to /tmp/hosts.{{ random_number }}
    copy: src=/etc/hosts dest=/tmp/hosts.{{ random_number }}
    notify:
      - call by /tmp/hosts.random_number

  handlers:
  - name: call by /tmp/hosts
    debug: msg="call first time"
  - name: call by /tmp/hosts.random_number
debug: msg="call by /tmp/hosts.random_number"
##### OS / ENVIRONMENT

centos 2.6.32-573
python 3.6.0
##### SUMMARY

# ansible-playbook -i inventory handlers_state_1.yml

PLAY [webs] ********************************************************************

TASK [setup] *******************************************************************
ok: [web1]
ok: [web2]

TASK [Copy the /etc/hosts to /tmp/hosts] ***************************************
changed: [web2]
changed: [web1]

TASK [Copy the /etc/hosts to /tmp/hosts.{{ random_number }}] *******************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NameError' object has no attribute 'message'
fatal: [web1]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NameError' object has no attribute 'message'
fatal: [web2]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

RUNNING HANDLER [call by /tmp/hosts] *******************************************
	to retry, use: --limit @/root/ansible/handlers_state_1.retry

PLAY RECAP *********************************************************************
web1                       : ok=2    changed=1    unreachable=0    failed=1   
web2                       : ok=2    changed=1    unreachable=0    failed=1   

##### STEPS TO REPRODUCE

# ansible-playbook -i inventory handlers_state_1.yml -vvv
...
task path: /root/ansible/handlers_state_1.yml:11
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/python-3.6.0/lib/python3.6/site-packages/ansible/template/vars.py", line 90, in __getitem__
    value = self._templar.template(variable)
  File "/usr/local/python-3.6.0/lib/python3.6/site-packages/ansible/template/__init__.py", line 331, in template
    result = self._do_template(variable, preserve_trailing_newlines=preserve_trailing_newlines, escape_backslashes=escape_backslashes, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/usr/local/python-3.6.0/lib/python3.6/site-packages/ansible/template/__init__.py", line 507, in _do_template
    res = j2_concat(rf)
  File "<template>", line 8, in root
  File "/usr/local/python-3.6.0/lib/python3.6/site-packages/ansible/plugins/filter/core.py", line 204, in rand
    if isinstance(end, (int, long)):
NameError: name 'long' is not defined
...

found:
     NameError: name 'long' is not defined
To change the :
    #vim /usr/local/python-3.6.0/lib/python3.6/site-packages/ansible/plugins/filter/core.py +204
    if isinstance(end, (int, long)):
    change：
    if isinstance(end, int):

##### ACTUAL RESULTS

```
# ansible-playbook -i inventory handlers_state_1.yml

PLAY [webs] ********************************************************************

TASK [setup] *******************************************************************
ok: [web1]
ok: [web2]

TASK [Copy the /etc/hosts to /tmp/hosts] ***************************************
ok: [web2]
ok: [web1]

TASK [Copy the /etc/hosts to /tmp/hosts.519] ***********************************
changed: [web1]
changed: [web2]

RUNNING HANDLER [call by /tmp/hosts.random_number] *****************************
ok: [web1] => {
    "msg": "call by /tmp/hosts.random_number"
}
ok: [web2] => {
    "msg": "call by /tmp/hosts.random_number"
}

PLAY RECAP *********************************************************************
web1                       : ok=4    changed=1    unreachable=0    failed=0   
web2                       : ok=4    changed=1    unreachable=0    failed=0 
```

**Comment by georgepsarakis** [comment]
This is fixed in the [development branch](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/core.py#L207).
