### ISSUE TITLE
template module failure (-c ssh)

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#2025]
template.yaml file:

```
- hosts: foo
  tasks:
    - template: src=/Users/lorin/ansible-playbooks/template.txt dest=/tmp/template.txt
```

Running against devel branch, sha 23bffc5f25a760f9e8be54301afbc6a8a0809900:

```
$ ansible-playbook -v template.yaml 

PLAY [foo] ********************* 

GATHERING FACTS ********************* 
ok: [foo.example.com]

TASK: [template src=/Users/lorin/ansible-playbooks/template.txt dest=/tmp/template.txt]             ********************* 
failed: [foo.example.com] => {"failed": true}
msg: Source /Users/lorin/ansible-playbooks/template.txt failed to transfer

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************* 
foo.example.com               : ok=1    changed=0    unreachable=0    failed=1    
```

Running against tag v1.0:

```
$ ansible-playbook -v template.yaml 

PLAY [foo] ********************* 

GATHERING FACTS ********************* 
ok: [foo.example.com]

TASK: [template src=/Users/lorin/ansible-playbooks/template.txt dest=/tmp/template.txt] ********************* 
changed: [foo.example.com] => {"changed": true, "dest": "/tmp/template.txt", "group":     "ubuntu", "md5sum": "b1946ac92492d2347c6235b4d2611184", "mode": "0664", "owner":     "ubuntu", "src": "/home/ubuntu/.ansible/tmp/ansible-1360341183.84-126627300153861/source", "state": "file"}

PLAY RECAP ********************* 
foo.example.com               : ok=2    changed=1    unreachable=0    failed=0    
```

Looking briefly at -vvv, it appears that the "cp" shell command may not be being constructed properly, but I haven't checked in detail.

**Comment by cordmata** [comment]
I'm seeing this as well using the paramiko connection. I've done a little more digging and I'm finding that that the IOError being thrown on sftp.put() is "[Errno 2] No such file". I'm going to check and see if the templated file is actually being written.

**Comment by cordmata** [comment]
See: Issue #2030

**Comment by vmalloc** [comment]
I'm constantly hitting this issue in 1.0. Any news on when a new release comes out to fix this?

**Comment by dhozac** [comment]
1.0 doesn't have this issue. 1.1 had this issue, and it has been corrected.

**Comment by vmalloc** [comment]
Ok, so 1.0 has another issue that is very similar. Templates are not being updated on the destination, although I'm modifying their source...

**Comment by lorin** [comment]
@vmalloc I suggest you open a new issue with details of how to reproduce your problem. When I opened this issue, it was working in 1.0 for my scenario, which is how I was able to verify that the issue was in the devel branch.

**Comment by vmalloc** [comment]
Ok, I'll try to find a reproducible scenario for this. Thanks.
