### ISSUE TITLE
ansible-vault edit - doesn't follow symlinks

### ISSUE THREAD

**Issue by bryfry** [ansible/ansible#20264]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-vault

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
none, standard config via pip installed ansible

##### OS / ENVIRONMENT
N/A

##### SUMMARY
`ansible-vault edit vault.yml` will create a new vault at the location of a symlinked file instead of editing the target file.

##### STEPS TO REPRODUCE
* `ansible-vault create test.yml`
* `ln -s test.yml link.yml`
* `ansible-vault edit link.yml`
* Make a change and save it
* `ls -al`

```
-rw-------  1 ubuntu ubuntu  355 Jan 14 23:01 link.yml
-rw-------  1 ubuntu ubuntu  355 Jan 14 23:01 test.yml
```

##### EXPECTED RESULTS
When running `ansible-vault edit link.yml` the contents of test.yml get updated.  This is the expected behavior of modifying symlinked files.

##### ACTUAL RESULTS
A new vault `link.yml` is created, it's contents are now different from the original vault `test.yml`

**Comment by alikins** [comment]
I can reproduce/confirmed this with stable-2.2 an devel/ branch.

**Comment by alikins** [comment]
Looks like when vault edit saves the new contents it first os.remove() the existing file, and then writes the enc content to a new file with the original filename.

For the case of 'ansible-vault edit some_symlink', the os.remove() only removes the sym link and creates a file with the same name and writes the data to it.

I concur that is a bug.

**Comment by sirkubax** [comment]
Please take a look at
https://github.com/ansible/ansible/issues/20184
