### ISSUE TITLE
Text::FastTemplate Ansible

### ISSUE THREAD

**Issue by dan20063** [ansible/ansible#20277]
Need to install cpan module called Text::FastTemplate using ansible on Ubuntu server, tried everything already, read all the docs online but cant get this to work

**Comment by alikins** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

 This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.
