### ISSUE TITLE
service module understands exited postgresql process as started

### ISSUE THREAD

**Issue by nh2** [ansible/ansible#20278]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`services`

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

```
  service:
    name: postgresql
    state: started
```

passes as green (`ok`) even though my postgres service is NOT running. On the machine

```
# service postgresql status
● postgresql.service - PostgreSQL RDBMS
   Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; 
   Active: active (exited) since Sun 2017-01-15 22:55:56 UTC; 2h 10m
  Process: 913 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 913 (code=exited, status=0/SUCCESS)
```

The service has quit because (from logs): `FATAL:  could not open relation mapping file "global/pg_filenode.map": No such file or directory` -- some configuration problem, what exactly it is isn't important for this issue.

* Why does ansible think the service is `started` when clearly it's `exited`?
* Or is this a terminology problem, and `started` means "anything systemd reports as OK, even if it's actually `not started`"? If that is the case, what's the right solution to codify that I want the service to be running?

**Comment by alikins** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

 This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.
