### ISSUE TITLE
Revisit: library/* uses hard-coded #!/usr/bin/python

### ISSUE THREAD

**Issue by robparrott** [ansible/ansible#2028]
I'd like to revisit this issue. 

Hardcoding a particular path (instead of using the standard "#!/usr/bin/env python") causes silent and confusing failures for any folks using non-standard python installs. This failure mode is problematic because the primary script by default will be using a different interpreter than the "library" scripts ('#!/usr/bin/env python' versus '#!/usr/bin/python'). This failure forced me to dig through the code to discover how playbooks are executed, and to insert a number of print statement to track down why the PATH was changing, and where. Not likely the desired user experience.

This issue will likely affect anyone on Mac, who would adopt "homebrew" or "macports" for a non-disruptive python install.  And also folks using non-standard or old LInux distribs, or those who don't have root access.

It seems a better default behavior is to use the same interpreter for both "main" scripts and "library" scripts, and then allow specifying a particular interpreter via this option. 

Finally, for those of us for whom this behavior makes you shudder uncontrollably, here's a single line fix:

   perl -i -p -e 's#!/usr/bin/python#!/usr/bin/env python#g' ansible/library/*

**Comment by mpdehaan** [comment]
It doesn't use a hard coded path.

set ansible_python_interpreter as an inventory variable and you can use anything you want.   It will replace that before transferring the module.

This is covered in the docs under the getting started section, though I admit it could be made more clear as it's talking about having more than one python in that case, and we need to make that more clear I agree.

Using /usr/bin/env is not a good answer as systems may have multiple pythons, and then it starts to matter what the /user/ had it set to, and the user environment should not affect a systems administration tool.
