### ISSUE TITLE
User supplied facts

### ISSUE THREAD

**Issue by sfromm** [ansible/ansible#203]
Per discussion here: https://groups.google.com/d/msg/ansible-project/SOnw5ovLomc/iSiPOgoLYKEJ, it would be nice if setup had a way to get user-supplied facts from a remote host.  This would preferably be a script that outputs json.

**Comment by mpdehaan** [comment]
closing this ticket, PR will address, yes.  We'll want to document this somewhere (module dev page, probably, but also probably somewhere else)
