### ISSUE TITLE
Change group tag in the RPM spec file

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#2031]
We should be showing up here already :)

http://dl.fedoraproject.org/pub/epel/6/i386/repoview/

**Comment by goozbach** [comment]
Looks like it needs to be placed in fedora comps:

```
<group>
    <id>system-admin-tools</id>
    <_name>System administration tools</_name>
    <_description>Utilities useful in system administration.</_description>
    <default>false</default>
    <uservisible>true</uservisible>
    <packagelist>
      <packagereq type="optional">cfengine</packagereq>
      <packagereq type="optional">nagios</packagereq>
      <packagereq type="optional">puppet</packagereq>
      <packagereq type="optional">puppet-server</packagereq>
      <packagereq type="optional">rear</packagereq>
      <packagereq type="optional">sec</packagereq>
      <packagereq type="optional">ttywatch</packagereq>
    </packagelist>
  </group>
```

I tried to change the Group of the package spec file and that may be another option.

**Comment by mpdehaan** [comment]
If we do this, make sure we include all three ansible packages (incl the
fireball one)

**Comment by goozbach** [comment]
Tracking downstream [here](https://bugzilla.redhat.com/show_bug.cgi?id=909447)

The repoview url we are wanting to [exist:](http://dl.fedoraproject.org/pub/epel/6/i386/repoview/system-admin-tools.group.html)

**Comment by goozbach** [comment]
Added [all three rpms](https://bugzilla.redhat.com/show_bug.cgi?id=909447#c1) to the request.

**Comment by mpdehaan** [comment]
thanks, I'll close this ticket.

Much appreciated!
