### ISSUE TITLE
proxmox_kvm module causing exception

### ISSUE THREAD

**Issue by seljuck** [ansible/ansible#20316]
##### ISSUE TYPE

 - Bug Report

This was initially reported in the (now obsolete) extras repo.
https://github.com/ansible/ansible-modules-extras/pull/3292
 
##### COMPONENT NAME

proxmox_kvm
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### OS / ENVIRONMENT

Ubuntu Mate 16.10

```
sudo -H pip install proxmoxer requests
Requirement already satisfied (use --upgrade to upgrade): proxmoxer in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages

```
##### SUMMARY

I just attempted to use this module without success. I copied it to my /library directory. I do have proxmoxer and requests installed on the Ansible controller PC.
##### STEPS TO REPRODUCE

```yaml
- hosts: proxmox
  vars:

  tasks:
  - name: test proxmox connection
    proxmox_kvm:
      api_user    : root@pam
      api_password: password
      api_host    : proxmox1
      name        : example
      node        : proxmox1
      vmid        : 102
      state       : current

```

##### EXPECTED RESULTS

I should have seen a status result for the specified VM
##### ACTUAL RESULTS

I got the following error message.

```
TASK [test proxmox connection] *************************************************
task path: /home/administrator/example/test-proxmox.yaml:8
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 490, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 565, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 153, in _configure_module
    task_vars=task_vars, module_compression=self._play_context.module_compression)
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/module_common.py", line 772, in modify_module
    (module_data, module_style, shebang) = _find_snippet_imports(module_name, module_data, module_path, module_args, task_vars, module_compression)
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/module_common.py", line 640, in _find_snippet_imports
    recursive_finder(module_name, module_data, py_module_names, py_module_cache, zf)
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/module_common.py", line 441, in recursive_finder
    tree = ast.parse(data)
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
TypeError: compile() expected string without null bytes

fatal: [proxmox1.example.com]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
        to retry, use: --limit @/home/administrator/example/test-proxmox.retry


```

**Comment by seljuck** [comment]
Moved from old repo per @helldorado request.

**Comment by helldorado** [comment]
@seljuck 

I can't reproduce the problem.

Can you test with the sample tree:

```yaml
.
├── defaults
│   └── main.yml
├── handlers
│   └── main.yml
├── library
│   └── proxmox_kvm.py
├── meta
│   └── main.yml
├── tasks
│   ├── main.yml
├── templates
└── vars
    └── main.yml
```

copy proxmox_kvm.py in library/

```yaml
cat tasks/main.yml

- name: Manage VM
  local_action:
    module: proxmox_kvm
    api_user     : "{{ api_user }}"
    api_password : "{{ api_password }}"
    api_host     : "{{ api_host }}"
    node         : "{{ node }}"
    name         : "{{ name }}"
    state        : "{{ state }}"
```

```yaml
cat playbooks/proxmox.yml

- hosts: localhost
   remote_user: root
   gather_facts: False
   vars:
      api_user  : root@pam
      api_password: password
      api_host  : proxmox1
      name  : example
      node  : proxmox1
      state  : current
```

**Comment by seljuck** [comment]
@helldorado 
I've setup the sample tree as you asked. I don't think I'm running the playbook correctly. This is the output I'm getting when I run /playbooks/proxmox.yml
```

PLAY [proxmox] *****************************************************************

PLAY RECAP *********************************************************************

```

Should I be running a different playbook?

**Comment by seljuck** [comment]
My initial test was from a computer where I installed Ansible with apt-get, and then re-installed with pip. I made an assumption that, that might be the problem. So I created a fresh VM to try this from. When installing Ansible via pip ONLY. I no longer get the above error message.

But I do get the proxmoxer library not installed error. I do have it installed, and when I double check with pip it confirms the installation. Upon reviewing the test examples that were posted in the pull request, I noticed they were all for localhost. I'm doing this from a different computer then the ProxMox host.

Does proxmoxer need to be installed on the proxmox host, not just the ansible controller?

**Comment by seljuck** [comment]
@helldorado 
Another update:

I've since confirmed that proxmoxer must be installed on the proxmox server. As per 
http://docs.ansible.com/ansible/dev_guide/developing_modules.html#debugging-ansiblemodule-based-modules

The ansible directory contains code from ansible.module_utils that is used by the module. Ansible includes files for any :module:`ansible.module_utils imports in the module but not no files from any other module. So if your module uses ansible.module_utils.url Ansible will include it for you, **but if your module includes requests then you’ll have to make sure that the python requests library is installed on the system before running the module**. You can modify files in this directory if you suspect that the module is having a problem in some of this boilerplate code rather than in the module code you have written.

By installing proxmoxer and requests on my proxmox server all of the above issues  have been resolved. But I'm getting a new error message

```
TASK [test proxmox connection] *************************************************
fatal: [proxmox1.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "authorization on proxmox cluster failed with exception: 'module' object has no attribute 'disable_warnings'"}
        to retry, use: --limit @/home/administrator/prox.retry

```

**Comment by helldorado** [comment]
@seljuck 

`I've since confirmed that proxmoxer must be installed on the proxmox server`
 No, the proxmoxer  python module are not necessary on Proxmox Server.

` but if your module includes requests then you’ll have to make sure that the python requests library is installed on the system before running the module`
Yes, but it is probably not to the module to install it, it checks the existence and informs the user.
 Check  => https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/misc/proxmox_kvm.py#L657-L661

You can find help via irc channel on freenode (ping me @helldorado)  or on google groups. 

Note: Issues should only concern bug reports or adding features. 

Best regards.

**Comment by seljuck** [comment]
@helldorado 

I've found the source of the last error message.
```
TASK [test proxmox connection] *************************************************
fatal: [proxmox1.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "authorization on proxmox cluster failed with exception: 'module' object has no attribute 'disable_warnings'"}
        to retry, use: --limit @/home/administrator/prox.retry

```
I was running proxmox_kvm against ProxMox 3.4. That attribute is not supported on version 3.4. When I ran it against version 4.4 everything ran perfectly.

I'm not sure if you want to add backwards compatibility, but I hope this is helpful.

Thanks for the help and the and irc support.

**Comment by helldorado** [comment]
@seljuck  i'm using both 3.x and 4.x for testing, can't reproduce.

Note, the error message ```'module' object has no attribute 'disable_warnings'``` is not proxmox part or the ansible module part. Check your pip module installation like urllib3.

Best regards.

**Comment by helldorado** [comment]
notabug

Can't reproduce any reported issue. I hope my answers have helped @seljuck
