### ISSUE TITLE
Ability to print out / output the library search path

### ISSUE THREAD

**Issue by sbwoodside** [ansible/ansible#20331]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Ansible configuration

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /Users/simon/sandbox/medstack/deployment/ansible/ansible.cfg
  configured module search path = ['./library']
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

After debugging a library path search problem, I found that there is no way to explicitly print out the library search path at runtime.

##### STEPS TO REPRODUCE

See e.g. http://stackoverflow.com/questions/37235848/ansible-not-looking-for-modules-in-library-alongside-playbook which provides instructions on how to debug a search path problem. I used that technique to discover that the search path was not what I expected.

```yaml

```

##### EXPECTED RESULTS

I would expect that using the `-vvv` flag would print out the library search path, or that there would be a command-line flag to print the library search path.

i.e. the merged results from all places where ANSIBLE_LIBRARY / library is set.

##### ACTUAL RESULTS

There appears to be no way to print out the library search path currently.

```

```

**Comment by bcoca** [comment]
part of this proposal allows for dumping ALL config values and where they are set:

https://github.com/ansible/proposals/issues/35

**Comment by abadger** [comment]
```ansible --version``` prints out the library search path among other information which seems to satisfy the request for a command line option to print this out.  I'll go ahead and close this ticket on that basis.

Note that ```ansible -vvv``` also prints out the module file that is being used to run a module (same with ansible-playbook) which can help you see whether there is a search path problem (even though it doesn't tell you what the search path is):
```
$ ansible  -m ping localhost  *[stable-2.2]  (14:14:54)
Using /etc/ansible/ansible.cfg as config file
Using module file /srv/ansible/vanilla2/lib/ansible/modules/system/ping.py
```

**Comment by sbwoodside** [comment]
@abadger Sorry if this is pedantic, but this is not documented anywhere that I can find. Even `ansible -h` only says:

      --version             show program's version number and exit

Also I don't find it in any online documentation. Should I file a separate issue to add documentation?

**Comment by abadger** [comment]
Yes please, that will get labelled as a documentation issue and we can get
it resolved.  Thanks!

**Comment by sbwoodside** [comment]
#20488
