### ISSUE TITLE
copy module global name 'exception' is not defined

### ISSUE THREAD

**Issue by jfbibeau** [ansible/ansible#20376]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
copy module

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```
[defaults]
gathering = smart
gather_subset = !virtual,!facter,!ohai
hash_behaviour = merge
host_key_checking = False
log_path = /var/log/ansible.log

[ssh_connection]
pipelining = False
```

##### OS / ENVIRONMENT
RHEL 7.3

##### SUMMARY
Copy task errors out and outputs a stacktrace when trying to copy a file to a disk that is full.

##### STEPS TO REPRODUCE
1. Pick a destination disk on the target machine, and create a file that will almost fill up the disk (ie to fill up 2G on /tmp: `dd if=/dev/zero of=/tmp/filler.dat bs=2G count=1`
2. Create a file that we will use as the source of the copy task that doesn't fit on the target disk, for example if there is 50M left, generate a 70M file somewhere `dd if=/dev/zero of=/opt/test.dat bs=70M count=1`
3. Run a sample playbook that attempts to copy the file to a disk that is full

```yaml
- hosts: all
  remote_user: root
  tasks:
    - copy: src="/opt/test.dat" dest="/tmp/test.dat"
```

##### EXPECTED RESULTS
Copy should fail with an exception showing the result of the copy command (disk full, couldn't copy, etc...

##### ACTUAL RESULTS
Stack trace is output (global name 'exception' is not defined):
```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [10.0.0.97]

TASK [copy] ********************************************************************
fatal: [10.0.0.97]: FAILED! => {"changed": false, "checksum": "e1e0abec2de9ed580fcd89c1b50d4b60e49f979e", "failed": true, "module_stderr": "Shared connection to 10.0.0.97 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_sNI2Il/ansible_module_copy.py\", line 364, in <module>\r\n    main()\r\n  File \"/tmp/ansible_sNI2Il/ansible_module_copy.py\", line 343, in main\r\n    module.atomic_move(b_mysrc, dest, unsafe_writes=module.params['unsafe_writes'])\r\n  File \"/tmp/ansible_sNI2Il/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2003, in atomic_move\r\nNameError: global name 'exception' is not defined\r\n", "msg": "MODULE FAILURE"}
	to retry, use: --limit @/opt/build/test/test.retry

PLAY RECAP *********************************************************************
10.0.0.97                  : ok=1    changed=0    unreachable=0    failed=1

**Comment by dagwieers** [comment]
Right, this was fixed here https://github.com/ansible/ansible/commit/dbbd2d79ff4b3d49e5db1b4cd22f488c56ae009c
Always best to search for reported issues and/or fixes before reporting.
Or to test against latest devel branch, or latest stable (v2.0.1) to check if it was already fixed.

duplicate_of #18628
resolved_by_pr #18649

**Comment by jfbibeau** [comment]
Thanks - tried a bunch of searches before opening this one but had not located that dup issue. Cheers.

**Comment by dagwieers** [comment]
No problem, very recognizable ;-)
