### ISSUE TITLE
Cannot perform task with become_user

### ISSUE THREAD

**Issue by dimakievua** [ansible/ansible#20390]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```

```

##### CONFIGURATION
ansible 2.0.0.2

##### OS / ENVIRONMENT
Ubuntu 16.04 LTS

##### SUMMARY
Cannot perform task due to sudo error.

##### STEPS TO REPRODUCE
My playbook.yml:
```
---
- name: Create user if not exists
  hosts: all
  remote_user: devops
  roles:
    - users
```
Code in roles/users/tasks/main.yml:
```
- name: Creating env.yml for different users
  include: env.yml currentuser="{{ item }}"
  with_items: "{{ users }}"
  become: yes
  become_user: "{{ item }}"
  tags: [user,devfiles]
```
and finally env.yml:
```
---
- name: debug
  debug: msg="{{ currentuser }}"
  tags: [user,devfiles]

- name: Add general data
  lineinfile: dest="/home/{{ currentuser }}/{{ docker_compose_base_dir }}/devfe.env" line="{{ item.key }}{{ ":" }} {{ item.value }}"
  with_dict: "{{ testusernginx }}"
  tags: [user,devfiles]
```
My variables:

```
users:
  - test1
  - test2

testusernginx:
  MIS_FE_PORT: 11115
  MIS_FE_SOCKET: 11116
  MIS_BE_PORT: 1337
  MIS_BE_NGINX_PORT: 11117
```

##### EXPECTED RESULTS
Expect file:
/home/test1/compose/devfe.env
with:
FE_PORT: 11115
FE_SOCKET: 11116
BE_PORT: 1337
BE_NGINX_PORT: 11117

##### ACTUAL RESULTS
Error appears. 
```
TASK [users : Copy ENV files for docker] ***************************************
changed: [localhost] => (item=[u'testuser', u'devfe.env'])

TASK [users : Calling env.yml for different users] *****************************
included: ...roles/users/tasks/env.yml for localhost

TASK [users : debug] ***********************************************************
ok: [localhost] => {
    "msg": "testuser"
}

TASK [users : Add general data] ********************
failed: [localhost] => (item={'value': 1337, 'key': u'BE_PORT'}) => {"failed": true, "item": {"key": "BE_PORT", "value": 1337}, "module_stderr": "", "module_stdout": "sudo: unknown user: {value:\r\nsudo: unable to initialize policy plugin\r\n", "msg": "MODULE FAILURE", "parsed": false}
failed: [localhost] => (item={'value': 11116, 'key': u'FE_SOCKET'}) => {"failed": true, "item": {"key": "FE_SOCKET", "value": 11116}, "module_stderr": "", "module_stdout": "sudo: unknown user: {value:\r\nsudo: unable to initialize policy plugin\r\n", "msg": "MODULE FAILURE", "parsed": false}
failed: [localhost] => (item={'value': 11115, 'key': u'FE_PORT'}) => {"failed": true, "item": {"key": "FE_PORT", "value": 11115}, "module_stderr": "", "module_stdout": "sudo: unknown user: {value:\r\nsudo: unable to initialize policy plugin\r\n", "msg": "MODULE FAILURE", "parsed": false}
failed: [localhost] => (item={'value': 11117, 'key': u'BE_NGINX_PORT'}) => {"failed": true, "item": {"key": "BE_NGINX_PORT", "value": 11117}, "module_stderr": "", "module_stdout": "sudo: unknown user: {value:\r\nsudo: unable to initialize policy plugin\r\n", "msg": "MODULE FAILURE", "parsed": false}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=1   

```
-vvvv shows:
failed: [localhost] => (item={'value': 1337, 'key': u'BE_PORT'}) => {"failed": true, "invocation": {"module_name": "lineinfile"}, "item": {"key": "BE_PORT", "value": 1337}, "module_stderr": "OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 16371\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to localhost closed.\r\n", "module_stdout": "sudo: unknown user: {value:\r\nsudo: unable to initialize policy plugin\r\n", "msg": "MODULE FAILURE", "parsed": false}

**Comment by dimakievua** [comment]
When I comment become_user:

```
- name: Calling env.yml for different users
  include: env.yml currentuser="{{ item }}"
  with_items: "{{ users }}"
#  become: yes
#  become_user: "{{ item }}"
  tags: [user,devfiles]
```
It shows:
```
TASK [users : Add general data] ********************
failed: [localhost] => (item={'value': 1337, 'key': u'BE_PORT'}) => {"failed": true, "item": {"key": "BE_PORT", "value": 1337}, "msg": "Destination /home/{'value': 1337, 'key': u'BE_PORT'}/compose/devfe.env does not exist !", "rc": 257}
```

It try to use {{ item }} instead of {{ currentuser }} is line:
`lineinfile: dest="/home/{{ currentuser }}/{{ docker_compose_base_dir }}/devfe.env" line="{{ item.key }}{{ ":" }} {{ item.value }}"`

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

In any case, the issue is that you are stacking `with_` so the 2nd loop overwrites `item` from the first. Use `loop_control` and `label` to avoid the conflict. For older versions you'll need `set_fact` , see http://docs.ansible.com/ansible/playbooks_loops.html#loops-and-includes-in-2-0 for details

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by dimakievua** [comment]
Hi,
Thank you for explanation. Missed this point in documentation!
