### ISSUE TITLE
in a playbook with 2 plays, the 2nd play is not run if some hosts failed in 1st play

### ISSUE THREAD

**Issue by fvalt** [ansible/ansible#20397]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.1.2.0
```

##### CONFIGURATION
[defaults]

hostfile = /etc/ansible/hosts
library = /usr/share/ansible
remote_tmp = $HOME/.ansible/tmp
pattern = *
forks = 5
poll_interval = 15
transport = smart
remote_port = 22
module_lang = C
callback_plugins = /root/foryou_ansible/plugins/callback
callback_plugins = /home/mkhaskhoussi/ansible_4YOU/plugins/callback
callback_plugins = /home/foryou/ansible_4YOU_BAMBOO/plugins/callback
bin_ansible_callbacks = True
gathering = implicit
timeout =120
executable = /bin/sh
jinja2_extensions = jinja2.ext.do,jinja2.ext.i18n
display_skipped_hosts = True
error_on_undefined_vars = False
system_warnings = True
deprecation_warnings = True
[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=60s
[accelerate]
accelerate_port = 5099
accelerate_timeout = 30
accelerate_connect_timeout = 5.0

##### OS / ENVIRONMENT
CentOS Linux release 7.2.1511

##### SUMMARY
When running my playbook including 2 plays that has to run on 2 different hosts, if some hosts failed on 1st play then the 2nd play will no run and the playbook ends with the NO MORE HOSTS LEFT message.

##### STEPS TO REPRODUCE
Describe un the inventory file 2 hosts:

```
[RD:children]
host1
host2

[host1]
H1 ansible_connection=local ansible_user=fvalt

[host2]
H2 ansible_connection=local ansible_user=fvalt

```
Run a playbook with 2 plays, each play should run on one distinct host, and the 1st play is made to fail on 1st host:
```
- hosts: RD:!host2
  tasks:
    - set_fact:
        var: False
    - fail: msg="failed"
      when: var == False

- hosts: RD:!host1
  tasks:
    - debug: msg="run play 2"

```

##### EXPECTED RESULTS
I expect the 2nd play to run on the 2nd host that has not failed on 1st play:

```
PLAY [RD:!host2] ***************************************************************

TASK [setup] *******************************************************************
ok: [H1]

TASK [set_fact] ****************************************************************
ok: [H1]

TASK [fail] ********************************************************************
fatal: [H1]: FAILED! => {"changed": false, "failed": true, "msg": "failed"}

PLAY [RD:!host1] ***************************************************************

TASK [setup] *******************************************************************
ok: [H2]

TASK [debug] *******************************************************************
ok: [H2] => {
    "msg": "run play 2"
}

PLAY RECAP *********************************************************************
H1                         : ok=2    changed=0    unreachable=0    failed=1
H2                         : ok=2    changed=0    unreachable=0    failed=0

```
##### ACTUAL RESULTS
the playbook stopped after 1st play failed and a NO MORE HOSTS LEFT message is displayed

```
Using /etc/ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0

PLAYBOOK: test_failed.yml ******************************************************
2 plays in test_failed.yml

PLAY [RD:!host2] ***************************************************************

TASK [setup] *******************************************************************
<H1> ESTABLISH LOCAL CONNECTION FOR USER: fvalt
<H1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1484745850.21-224913568035023 `" && echo ansible-tmp-1484745850.21-224913568035023="` echo $HOME/.ansible/tmp/ansible-tmp-1484745850.21-224913568035023 `" ) && sleep 0'
<H1> PUT /tmp/tmpPy44M_ TO /home/fvalt/.ansible/tmp/ansible-tmp-1484745850.21-224913568035023/setup
<H1> EXEC /bin/sh -c 'chmod u+x /home/fvalt/.ansible/tmp/ansible-tmp-1484745850.21-224913568035023/ /home/fvalt/.ansible/tmp/ansible-tmp-1484745850.21-224913568035023/setup && sleep 0'
<H1> EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python /home/fvalt/.ansible/tmp/ansible-tmp-1484745850.21-224913568035023/setup; rm -rf "/home/fvalt/.ansible/tmp/ansible-tmp-1484745850.21-224913568035023/" > /dev/null 2>&1 && sleep 0'
ok: [H1]

TASK [set_fact] ****************************************************************
task path: /home/fvalt/4YOU/test_failed.yml:3
ok: [H1] => {"ansible_facts": {"var": false}, "changed": false, "invocation": {"module_args": {"var": false}, "module_name": "set_fact"}}

TASK [fail] ********************************************************************
task path: /home/fvalt/4YOU/test_failed.yml:5
fatal: [H1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"msg": "failed"}, "module_name": "fail"}, "msg": "failed"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/home/fvalt/4YOU/test_failed.retry

PLAY RECAP *********************************************************************
H1                         : ok=2    changed=0    unreachable=0    failed=1

```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

When ALL hosts in a play fail that is considered a fatal error, if only part of the hosts of the play failed it should continue. Your example shows that all hosts fail in the first play, so this is behaving as expected.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
