### ISSUE TITLE
playbook not running in Tower

### ISSUE THREAD

**Issue by jithe1978** [ansible/ansible#20418]
##### ISSUE TYPE

 - Bug Report
 ##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

**Comment by jithe1978** [comment]
Please help me

**Comment by sivel** [comment]
For tower issues please use https://support.ansible.com/

**Comment by jithe1978** [comment]
Matt,

This is only for paid users, i am still exploring ansible tower features in
order to recommend to my company, can you answer this question
Can ansible tower community edition runs playbook with groups 3 hosts
inventory, what i am noticing is it running only against single node not
against group of nodes.

Thank you,
Jithendra Myla
Mobile 412-738-2120
Home  412-329-6979
