### ISSUE TITLE
Running unit tests fails with: ERROR: Missing environment variable: HOME

### ISSUE THREAD

**Issue by umago** [ansible/ansible#20424]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
N/A

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel 4673a9c9c2) last updated 2017/01/18 17:51:21 (GMT +100)
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Arch Linux

##### SUMMARY
Running the unit tests with `tox -epy27` (any py{2,3}*) fails with:

```
test/runner/ansible-test units -v --python 2.7
ERROR: Missing environment variable: HOME
make: *** [Makefile:118: tests] Error 1
ERROR: InvocationError: '/usr/bin/make tests'
```

Full error: http://pastebin.com/Qs2xbdBj

##### STEPS TO REPRODUCE
Just clone the ansible repository and run ``tox -epy27``

##### EXPECTED RESULTS
The unit tests to be executed

##### ACTUAL RESULTS
The execution of the unit tests doesn't start

**Comment by nitzmahone** [comment]
cc @mattclay

**Comment by mattclay** [comment]
@umago There is built-in support for `tox` in `ansible-test`. You may want to try running `ansible-test` with the options `--tox --python 2.7` instead.

**Comment by mattclay** [comment]
@umago Thanks for reporting the issue and providing the fix.
