### ISSUE TITLE
Cannot "easy_install" ansible from within a virtualenv

### ISSUE THREAD

**Issue by vmalloc** [ansible/ansible#2042]
Attempting to:

```
    easy_install -U ansible
```

from within a virtualenv results in this:

```
The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
```

**Comment by mpdehaan** [comment]
If I may, you should use pip.

(easy_install is old and busted, pip is the new hotness)

**Comment by vmalloc** [comment]
Actually I was glad to see that pip installs ansible properly even inside virtualenvs.

**HOWEVER**, FYI, I strongly discourage you from using the "pip is hip" argument, as there are things it can't do yet that easy_install still can. Many packages are broken under pip and work ok on easy_install, and some of them behave differently under both.

A very simple example is when you want to install a package with console scripts under virtualenv, and you happen to have the same package in the global site-packages. In this case pip just conveniently skips creating the console scripts inside the virtualenv, causing erroneous behavior if the user is unaware of this.

Also, pip does not handle .eggs properly, and it never intends to support that format. 

Until the packaging hell in Python is resolved (and I don't believe this will happen any time soon) - it is reasonable to support at least distribute's version of easy_install and pip simultaneously (it's not even that hard in most cases).

**Comment by mpdehaan** [comment]
Actually I really prefer yum+RPM.

I'm just saying that may get around your problems as more work has been
done in ansible WRT virtualenv.

Patches for other things to easy_install would be accepted, but just
pulling the latest version from the internet each time, not having a local
mirror, and not pinning the versions -- those are things people really
should not do :)

**Comment by vmalloc** [comment]
I can't say I completely agree.

When using things like uwsgi "as a consumer", then of course an rpm package or .deb makes sense. However, many companies today (like the one I work in, but also others like GitHub, dotCloud etc.) put a lot of effort to create a hard connection between SCM and deployment. This involves setting up a local pypi-like mirror (like we have), and creating strong version requirements on packages.

Rolling rpm's is not always trivial, and when needing to support multiple platforms this becomes a hassle (Ubuntu, Solaris, CentOS, etc.). It mostly involves having some kind of CI solution in-house that builds packages all day long. 

Now - python source-only packages (as opposed to binary ones) are plaintext. They're already versioned. They already support providing strict dependencies. They're available and flexible, and for most of them there isn't any pre-existing rpm that's easily available. I don't think it's reasonable to require an rpm for each one of them, and in some cases it's plain wrong (like an rpm that's dependent on python 2.6 where you really need 2.7). Virtualenv solves these cases elegantly. It also allows you to use multiple (conflicting) versions of the same packages in parallel, used by different services.

Also - think of the simple case - you want a quick and dirty (private) project to just install nginx, uwsgi, flask and supporting utilities. There's no easy way I'm aware of to do this with RPMs and/or .debs without some preliminary processing. When using virtualenv this can be done by a single line in ansible :-)

I do agree that pip is much better than easy_install, but I'm just saying that once you have to work with live checkouts, there is a slight possibility you're going to need to install something that has to be `easy_install`ed rather than `pip`ed. 

Other directions, btw, like the `wheel` project and working with raw eggs, are also promising, and once the utilities become more flexible for those, it will probably be the way to develop such solutions. Until then - I think it's a wise choice to provide good support for installing in virtualenvs...

**Comment by mpdehaan** [comment]
I have to work from live checkouts quite often.

Just saying people shouldn't pip from the internet when they can help it.
 We are on the same page.

Send me a patch for what you like, I'm not saying easy_install is
_supposed_ to not work, I was just suggesting there are other options.

As for ansible, install from pip.

**Comment by vmalloc** [comment]
Ok. I already do  and it seems to work ok. As for the other problematic
packages I'll use the "creates" flag to shell, as it does the trick.

Thanks!

On Mon, Feb 11, 2013 at 4:14 PM, Michael DeHaan notifications@github.comwrote:

> I have to work from live checkouts quite often.
> 
> Just saying people shouldn't pip from the internet when they can help it.
> We are on the same page.
> 
> Send me a patch for what you like, I'm not saying easy_install is
> _supposed_ to not work, I was just suggesting there are other options.
> 
> As for ansible, install from pip.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/2042#issuecomment-13381542..

## 

Rotem
