### ISSUE TITLE
Templating fails with error on FreeBSD 11

### ISSUE THREAD

**Issue by agaffney** [ansible/ansible#20431]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Templating

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
FreeBSD 11.0

##### SUMMARY
Attempting to use templates in a playbook on FreeBSD 11.0 results in the following error:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 88, in run
    items = self._get_loop_items()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 186, in _get_loop_items
    loop_terms = listify_lookup_plugin_terms(terms=self._task.loop_args, templar=templar, loader=self._loader, fail_on_undefined=True, convert_bare=False)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/listify.py", line 34, in listify_lookup_plugin_terms
    terms = templar.template(terms.strip(), convert_bare=convert_bare, fail_on_undefined=fail_on_undefined)
  File "/usr/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 377, in template
    result = self.do_template(
AttributeError: 'Templar' object has no attribute 'do_template'
```

##### STEPS TO REPRODUCE
Ansible is installed via `pkg install ansible`. The example playbook is executed with `ansible-playbook -vvv foo.yml`.

Example playbook:

```
---
- hosts: localhost
  gather_facts: no
  vars:        
    userlist:
        - user1
        - user2
        - user3
  tasks:
    - name: Looptest
      debug: var=item
      with_items: "{{ userlist }}"
```

##### EXPECTED RESULTS
No traceback

##### ACTUAL RESULTS
Traceback noted above is generated

**Comment by agaffney** [comment]
@bcoca

**Comment by agaffney** [comment]
This issue was found by `oerg866` in the `#ansible` IRC channel

**Comment by bcoca** [comment]
Confirmed the issue, but removing the pkg and installing 2.2.1 from pip indicates this is an issue with the FreeBSD package.

**Comment by bcoca** [comment]
So I downloaded the package from a FreeBSD mirror, untarred it,  and on that line i see:
 http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/ansible-2.2.0.0_3.txz

``` result = self._do_template(```

which is correct, same as in pip, same as in source ... but when i look at the file installed by `pkg install ansible`

``` result = self.do_template( ```

Then I noticed that the 'installed package' is ansible-2.2.0.0_2, which is fetched from /quaterly (default for pkg) instead of /latest, this package has the issue. I recommend upgrading to the _3 version of the package. 

http://pkg.freebsd.org/FreeBSD:11:amd64/quaterly/All/ansible-2.2.0.0_2.txz

Since this does not look like an Ansible issue but a packaging one, I'm going to close this ticket.

**Comment by agaffney** [comment]
I can verify that `ansible==2.2.0.0` installed via `pip` works properly.

**Comment by admirabilis** [comment]
Same issue on Ansible 2.2.1.0-1ppa~yakkety from the official Ubuntu 16.10 PPA. I had to edit _/usr/lib/python2.7/dist-packages/ansible/template/\_\_init\_\_.py_ and make sure the line read as `result = self._do_template(` so I could run my playbook!

**Comment by agaffney** [comment]
You should create a new issue for that, as that is unrelated to the FreeBSD packaging.
