### ISSUE TITLE
Provide a way to force "easy_install -U" if a file does not exist

### ISSUE THREAD

**Issue by vmalloc** [ansible/ansible#2044]
For some modules/packages (like uwsgi, for instance), it takes the "-U" flag sometimes to easy_install to make them create their console scripts executables. So this formula:

```
easy_install name=uwsgi virtualenv=$my_virtualenv_path
```

Will _not_ create the executable _$my_virtualenv_path/bin/uwsgi_.

This is solved by specifying the "-U" flag to easy_install, forcing it to, among other things, create the console scripts.

Currently there's no way to control this from within ansible. I don't want to run the easy_install as a shell (because it will always be triggered as "changed"), and I want it to run only if the "uwsgi" file does not exist in its final location...

**Comment by mpdehaan** [comment]
How about using pip?   Does it work there?

easy_install is old and busted.  pip is the new hotness.

**Comment by mpdehaan** [comment]
FWIW, the 'shell' module takes a creates=/path/to/file parameter for exactly that purpose.

Possibly could serve as a workaround if pip doesn't work for you.

I use easy_install only for installing pip.

**Comment by vmalloc** [comment]
Ok - I didn't know about the `creates` parameter - very useful indeed.

However - see my response to #2042 regarding the "pip is hip" argument.
