### ISSUE TITLE
Template search path broken in 2.2.1.0

### ISSUE THREAD

**Issue by berlic** [ansible/ansible#20442]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`template` module(action plugin)

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### CONFIGURATION
Default config

##### SUMMARY
Jinja2 templates can't be included between roles in 2.2.1

##### STEPS TO REPRODUCE
Make two roles: `common_role`, `service_role`.  
Make template in `common_role/templates/common.j2`.  
Make template in `service_role/templates/service.j2`:
```
This is a service
{% include 'common_role/templates/common.j2' %}
```

Trying to template `service.j2` will fail with error:
> TemplateNotFound: common_role/templates/common.j2

##### EXPECTED RESULTS
`service.j2` should include `common.j2` while rendering.

##### DETAILS

This happens because `/path/to/project/roles` is not included in search path any more.
[Commit](https://github.com/ansible/ansible/commit/f90a6439c41c345f48ea4187278ba39dbdb182e3) with braking changes.

Original behaviour has been done [here](https://github.com/ansible/ansible/commit/dbd755e0f45d157ddf6326252043fa60f7ee80e7) and patched a bit [here](https://github.com/ansible/ansible/commit/f162990cb3677ad19c138a8700c39e5e656cfd81).

This allow to include templates between roles, because Jinja2 blocks include paths with `..`.

**Comment by bcoca** [comment]
The behaviour of including ALL roles, not just those that are part of the play was incorrect. This would lead to getting templates from unexpected role, your example adds at least role name but others using `{% include common.j2 %} ` would get unpredictable results.

The current behaviour is correct, only paths for roles actually used in the current play are considered.

**Comment by berlic** [comment]
@bcoca let me not agree with you. `include` in Jinja2 doesn't search files recursively.

If there is `/path/to/project/roles` in searchpath, then `{% include common.j2 %}` can include only `/path/to/project/roles/common.j2` and can't include anything from `/path/to/project/roles/custom_role/templates/common.j2` by mistake.

But if template path is explicitly set like in `{% include common_role/templates/common.j2 %}` Jinja2 would find it.

In 2.2.1 there is no way of including templates from other roles in general case.

Here I call `ansible-playbook ./tests/playbook.yml` which applies `node` role which include template task from `container/tasks/common_tasks.yml`:

Searchpath with ansible 2.2.0
```
"/vagrant/project/roles",
"/vagrant/project/roles/node",
"/vagrant/project/tests",
"/vagrant/project/roles/node/templates"
```

Searchpath with ansible 2.2.1
```
"/vagrant/project/roles/container/tasks",
"/vagrant/project/roles/container/tasks/templates",
"/vagrant/project/roles/node",
"/vagrant/project/roles/node/templates"
"/vagrant/project/roles/node/templates/templates",
"/vagrant/project/tests",
"/vagrant/project/tests/templates",
```

This way I can't include `/vagrant/project/roles/container/templates/common.j2` template because neither `/vagrant/project/` (because playbook's current directory is ./tests), nor `/vagrant/project/roles/` (because it is dropped in 2.2.1), nor `/vagrant/project/roles/container` is in the path.

I'll try to refactor our code with `include_role` and see if it would help...

**Comment by bcoca** [comment]
It was never intended to allow inclusion of templates in roles not in play, the search path is meant to find templates in the role's dependency path.

**Comment by maglub** [comment]
I understand that this might not be the intended use of include in jinja2, but it is an extremely useful feature for many people.

I get the point, that it is always best to build your environment the proper way, but there are many installations out there, that use this "feature", and that it for these people is very costly to change the behaviour.

Why not make this "optional", like in the ansible.cfg file, as a variable? That way you leave it to the user to decide themselves.

I.e, if set, jinja2 will add it to the search path and allow the "ugly" way of including.

```
[defaults]
roles_include_path = ./roles
```

This would be very closely related to a 1.8.2 pull request that was accepted: https://github.com/ansible/ansible/pull/9933

**Comment by berlic** [comment]
Here's a patch that I use for project that relies on this functionality:
```
--- /Users/berlic/Library/Python/2.7/lib/python/site-packages/ansible/plugins/action/template.py	2017-01-16 19:48:29.000000000 +0300
+++ /Users/berlic/path/to/project/action_plugins/template.py	2017-01-30 18:21:26.000000000 +0300
@@ -133,6 +133,12 @@
                 newsearchpath.append(p)
             searchpath = newsearchpath
 
+            # Restore pre 2.2.1 search path to /project/roles
+            if self._task._role is not None:
+                if C.DEFAULT_ROLES_PATH:
+                    searchpath.extend(C.DEFAULT_ROLES_PATH)
+            # End of patch
+
             self._templar.environment.loader.searchpath = searchpath
 
             old_vars = self._templar._available_variables
```

**Comment by maglub** [comment]
Thanks, that patch is exactly solving my issue.

In my opinion, that should be the expected behavior of ansible.

The path to the script in my Brew installed ansible 2.2.1.0 on OSX is: /usr/local/Cellar/ansible/2.2.1.0/libexec/lib/python2.7/site-packages/ansible/plugins/action/template.py

**Comment by ghost** [comment]
It's somewhat disappointing to remove this behaviour simply because "it was never intended" to be used this way. Isn't it a perfectly valid and common use case to have a template in role A and extend it in role B to prevent clutter and duplication in a playbook.

Do I understand correctly there is no way to reference this template even if A and B are in the same play?

in file "roles/rails/templates/rails_vhost.j2":
[..]
{% extends "nginx/templates/vhost.j2" %}
[..]

export ANSIBLE_ROLES_PATH=roles
ansible-playbook -i hosts playbooks/play.yml

**Comment by nikolasgd** [comment]
I do also agree that @bcoca is not correct about what this new behavior does and what it supposedly prevents. The new search path doesn't allow inclusion of templates from **_any_** other role but the role itself, even if the other role is in the same play.

Inclusion of templates from other roles within the **_same_** play was useful - it helped prevent repetition of common code blocks in templates.

BTW: I solved this by symlinking the common templates between roles in our playbooks, so the patch provided above is not necessary.

**Comment by apassi** [comment]
Template override is exampled in geerlingguy.nginx role for vhost override, which, sadly, is broken now.
