### ISSUE TITLE
[Bug] Chdir giving [Errno 2] No such file or directory, Ansible local run on docker container

### ISSUE THREAD

**Issue by tomekit** [ansible/ansible#20453]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
command

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /data/project-ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```
[ssh_connection]
pipelining=True
```

##### OS / ENVIRONMENT
Docker container, Ubuntu 14.04 LTS, image - ubuntu:14.04

##### SUMMARY
Chdir returns error: `[Errno 2] No such file or directory` even though the directory exists.

##### STEPS TO REPRODUCE
On your docker host, create a directory where you can put this YAML playbook
```yaml
# chdir_test.yaml playbook
- hosts: all
  tasks:
    - file: path=/tmp/libmemcached state=directory mode=0755

    - name: Download libmemcached
      command: "wget https://launchpad.net/libmemcached/1.0/1.0.18/+download/libmemcached-1.0.18.tar.gz"
      args:
        chdir: /tmp/libmemcached
```

On your docker host create a container:
```
docker run -d --name web` -v /data/project-ansible/:/data/project-ansible ubuntu:14.04 tail -f /dev/null
```
volume specified needs to point to the directory where you've created the YAML file

Enter the container:
`docker exec -it web /bin/bash`

Install Ansible:
```
apt-get update
apt-get install python-pip python-dev
pip install ansible markupsafe
```

Run from inside the container:

```
cd /data/project-ansible/
ansible-playbook -c local -i localhost, chdir_test.yaml
```

##### EXPECTED RESULTS
Wget to download the libmemcached into the `/tmp/libmemcached` dir

##### ACTUAL RESULTS
Error, here is the verbose output
```
TASK [php : file] **************************************************************
task path: /data/project-ansible/roles/php/tasks/php5-memcached-igbinary.yml:14
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/core/files/file.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
ok: [localhost] => {
    "changed": false, 
    "diff": {
        "after": {
            "path": "/tmp/libmemcached"
        }, 
        "before": {
            "path": "/tmp/libmemcached"
        }
    }, 
    "gid": 0, 
    "group": "root", 
    "invocation": {
        "module_args": {
            "backup": null, 
            "content": null, 
            "delimiter": null, 
            "diff_peek": null, 
            "directory_mode": null, 
            "follow": false, 
            "force": false, 
            "group": null, 
            "mode": "0755", 
            "original_basename": null, 
            "owner": null, 
            "path": "/tmp/libmemcached", 
            "recurse": false, 
            "regexp": null, 
            "remote_src": null, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": null, 
            "state": "directory", 
            "unsafe_writes": null, 
            "validate": null
        }, 
        "module_name": "file"
    }, 
    "mode": "0755", 
    "owner": "root", 
    "path": "/tmp/libmemcached", 
    "size": 4096, 
    "state": "directory", 
    "uid": 0
}

TASK [php : Download libmemcached] *********************************************
task path: /data/project-ansible/roles/php/tasks/php5-memcached-igbinary.yml:16
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/core/commands/command.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "cmd": "wget https://launchpad.net/libmemcached/1.0/1.0.18/+download/libmemcached-1.0.18.tar.gz", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "_raw_params": "wget https://launchpad.net/libmemcached/1.0/1.0.18/+download/libmemcached-1.0.18.tar.gz", 
            "_uses_shell": false, 
            "chdir": "/tmp/libmemcached", 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }, 
        "module_name": "command"
    }, 
    "msg": "[Errno 2] No such file or directory", 
    "rc": 2
}
	to retry, use: --limit @/data/project-ansible/site.retry

```

**Comment by nitzmahone** [comment]
Have you verified that wget is installed in your container? Seems like the most obvious source of failure since other Ansible tasks are working fine...

**Comment by tomekit** [comment]
Thanks, it's indeed the problem. I've assumed that `wget` is always installed, so even didn't smell it could be potential issue. Right, so my issue is solved... but, don't you think that Ansible should tell more about the shell comand failing, the status code for the non-existent command is 127 (checked with echo $?), instead it tells: ` [Errno 2] No such file or directory`

**Comment by bcoca** [comment]
you used command, not shell, the errors are different as the executions are different. shell runs a shell and interprets a string, command executes a command directly.

**Comment by tomekit** [comment]
Right, that makes sense, on the other hand the error message is not clear no matter if it's a: `command` or `shell`. I am making assumptions now, as I don't know how it works behind the scenes, but I would expect it to tell me: "Command does not exist" rather "No such file or directory".
If the current behavior is expected, then let's please close this ticket. Thanks

**Comment by bcoca** [comment]
That is the error returned from the system, it could also be that one of the other files passed as argument is not found and the command itself exits with that error, being a freeform module makes it very hard to determine the difference.

We are open to any PR that helps with this issue, but since this is how it works, i'm going to close this ticket now.

**Comment by mallikharjunrao** [comment]
Getting the same issue in on chdir. Please find the details as below.
component: chdir

 - name: Compile Nagios plugins (Make)
    command: "{{ item }} chdir=/tmp/nagios-plugins-2.2.1"
    with_items:
      - make
      - make install
    when: nagios_plugins_exists|failed

 ansible --version
ansible 2.0.0.2
  config file = /mnt/nagios/ansible.cfg
  configured module search path = Default w/o overrides


ERROR:


TASK [Compile Nagios plugins (Make)] *******************************************
task path: /mnt/nagiosadmin/nagios/plays/install-nrpe-nodes.yml:49
<XX.XX.XX.XX> ESTABLISH SSH CONNECTION FOR USER: None
<XX.XX.XX.XX> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=1800s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/nagiosadmin/.ansible/cp/ansible-ssh-%h-%p-%r -tt XX.XX.XX.XX '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1504277292.69-218204686700726 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1504277292.69-218204686700726 )" )'
<XX.XX.XX.XX> PUT /tmp/tmpazr_ye TO /home/nagiosadmin/.ansible/tmp/ansible-tmp-1504277292.69-218204686700726/command
<XX.XX.XX.XX> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=1800s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/nagiosadmin/.ansible/cp/ansible-ssh-%h-%p-%r '[XX.XX.XX.XX]'
<XX.XX.XX.XX> ESTABLISH SSH CONNECTION FOR USER: None
<XX.XX.XX.XX> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=1800s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/nagiosadmin/.ansible/cp/ansible-ssh-%h-%p-%r -tt XX.XX.XX.XX '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-xmxdwdfebrfaztecutrpccchkvqbnyhd; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/nagiosadmin/.ansible/tmp/ansible-tmp-1504277292.69-218204686700726/command; rm -rf "/home/nagiosadmin/.ansible/tmp/ansible-tmp-1504277292.69-218204686700726/" > /dev/null 2>&1'"'"'"'"'"'"'"'"''"'"''
<XX.XX.XX.XX> ESTABLISH SSH CONNECTION FOR USER: None
<XX.XX.XX.XX> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=1800s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/nagiosadmin/.ansible/cp/ansible-ssh-%h-%p-%r -tt XX.XX.XX.XX '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1504277292.88-119113900160526 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1504277292.88-119113900160526 )" )'
<XX.XX.XX.XX> PUT /tmp/tmpQyU8ll TO /home/nagiosadmin/.ansible/tmp/ansible-tmp-1504277292.88-119113900160526/command
<XX.XX.XX.XX> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=1800s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/nagiosadmin/.ansible/cp/ansible-ssh-%h-%p-%r '[XX.XX.XX.XX]'
<XX.XX.XX.XX> ESTABLISH SSH CONNECTION FOR USER: None
<XX.XX.XX.XX> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=1800s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/nagiosadmin/.ansible/cp/ansible-ssh-%h-%p-%r -tt XX.XX.XX.XX '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-zvwpxlgyjbwfchzxihxpvlweokrmkuks; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/nagiosadmin/.ansible/tmp/ansible-tmp-1504277292.88-119113900160526/command; rm -rf "/home/nagiosadmin/.ansible/tmp/ansible-tmp-1504277292.88-119113900160526/" > /dev/null 2>&1'"'"'"'"'"'"'"'"''"'"''
failed: [XX.XX.XX.XX] => (item=make) => {"cmd": "make", "failed": true, "invocation": {"module_args": {"_raw_params": "make", "_uses_shell": false, "chdir": "/tmp/nagios-plugins-2.2.1", "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "item": "make", "msg": "[Errno 2] No such file or directory", "rc": 2}
failed: [XX.XX.XX.XX] => (item=make install) => {"cmd": "make install", "failed": true, "invocation": {"module_args": {"_raw_params": "make install", "_uses_shell": false, "chdir": "/tmp/nagios-plugins-2.2.1", "creates": null, "executable":

**Comment by mallikharjunrao** [comment]
permissions also applied but still it is failing with the same exception.
- file:
    path: /tmp/nagios-plugins-2.2.1
    state: directory
    mode: 0755

**Comment by tomekit** [comment]
Seems to be that you're missing the double aposthrophe after the `item` variable.

> command: "{{ item }} chdir=/tmp/nagios-plugins-2.2.1"

Shouldn't it be this?

> command: "{{ item }}" chdir=/tmp/nagios-plugins-2.2.1
