### ISSUE TITLE
Playbook including another doesn't resume after completion of included

### ISSUE THREAD

**Issue by rmfitzpatrick** [ansible/ansible#20460]
Plays that include others don't resume after the included play has completed:
```
---
- name: include included_playbook
  include: included_playbook.yml

- name: in main
  debug: msg="never called"

```

```
TASK [role_one : in included_one] ****************************************************************************************************************************************
task path: ../roles/role_one/tasks/included_playbook.yml:2
ok: [localhost] => {
    "msg": "in included_playbook"
}

PLAY RECAP ***************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

bisect suggests this was introduced by cae682607cdbe710a51ae5181bbc84ee06f3f33e
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.3.0 (detached HEAD cae682607c) last updated 2017/01/19 09:56:07 (GMT -400)
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
Observed in EL7 and OSX

**Comment by nitzmahone** [comment]
cc @jimi-c

**Comment by jimi-c** [comment]
@rmfitzpatrick that is an odd playbook - if that's exactly what you have and included_playbook.yml is in fact a playbook and not a list of tasks I would not have expected this to work under any version (and it should raise a parsing error).

**Comment by jimi-c** [comment]
This is what I get (and what I'd expect):
<pre>
[jamesc@jimi 20460]$ ansible-playbook -vv test.yml 
Using /etc/ansible/ansible.cfg as config file
ERROR! 'debug' is not a valid attribute for a Play

The error appears to have been in '/home/jamesc/testing/20460/test.yml': line 5, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: in main
  ^ here
</pre>

**Comment by rmfitzpatrick** [comment]
@jimi-c, someone suggested offline that an included role is also a "playbook" so I edited my report.  In this case `included_playbook.yml` is a single debug task.

At any rate the issue appears to have been fixed since I opened it (maybe https://github.com/ansible/ansible/commit/9d549c34981694e9fb62d3aa37392a439b5ae487).  Closing.

**Comment by jimi-c** [comment]
Excellent, I thought the recent fix to PlayIterator might have corrected this, just wanted to make sure I had the correct reproducer. Thanks for following up!
