### ISSUE TITLE
Confusing information on CHANGELOG.md file

### ISSUE THREAD

**Issue by bartoszkosiorek** [ansible/ansible#20468]
In file:
https://github.com/ansible/ansible/blob/devel/CHANGELOG.md

there is still information that 2.2.0 is in active development.
Also information about 2.2.1 is missing.

**Comment by bcoca** [comment]
We update the devel one but it trails the 'official' ones, for and 'up to date' changelog look at the release tagged one.

https://github.com/ansible/ansible/blob/v2.2.1.0-1/CHANGELOG.md

**Comment by bcoca** [comment]
fixed via 4e497440315b64514d5092d25ba6eaab2ed4899b  and 6d647aaf55352b1338f0a7ca72caa0710f71dc37
