### ISSUE TITLE
Confusing behavior with json_query

### ISSUE THREAD

**Issue by ahawkins** [ansible/ansible#20487]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- `json_query` filter

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides

```

##### OS / ENVIRONMENT

- N/A

##### SUMMARY

I have a JSON string like this: 

```json
{
  "id": "foo",
  "tags": {
      "bar": "baz"
   } 
}
```

I need to access all values of that JSON object. My first thought was to `{{ item | from_json | attr('id') }}` but that did not work. Replacing `attr('id')` with `json_query('id')` does. This opens a few questions:

- What's the difference between `from_json | attr('id')` and `from_json | json_query('id')`?
- What type of objects does `from_json` create?

##### STEPS TO REPRODUCE

- Assign a variable with the provided json
- Try `{{ json_variable | from_json | attr(`id`) }}` in a module

##### EXPECTED RESULTS

The template outputs `foo`.

##### ACTUAL RESULTS

Ansible errors saying `attr` cannot be used on a `dict` type.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
