### ISSUE TITLE
Update documentation that --version displays library search path

### ISSUE THREAD

**Issue by sbwoodside** [ansible/ansible#20488]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

ansible command

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

This is filed based on a request from @abadger in #20331.

`ansible --version` prints out the library search path, but this is not documented.

##### STEPS TO REPRODUCE

Look at command documentation with `ansible -h`

Google `ansible library search path` to look for online documentation.

##### EXPECTED RESULTS

`ansible -h` only would say:

     --version             show program's version number, config file location, 
                           configured module search path (library search path), and exit

Google `ansible library search path` would reveal online documentation on `docs.ansible.com`, potentially in this article: http://docs.ansible.com/ansible/intro_configuration.html

##### ACTUAL RESULTS

`ansible -h` currently only says:

     --version             show program's version number and exit

**Comment by jctanner** [comment]
@sbwoodside is this a docs change you would like to contribute?

**Comment by sbwoodside** [comment]
No, sorry I'm swamped.

**Comment by Akasurde** [comment]
resolved_by_pr #49545
