### ISSUE TITLE
File (template) diffing with --diff option breaks on UTF-8 files

### ISSUE THREAD

**Issue by leucos** [ansible/ansible#2048]
When remote file has UTF-8 encoding, --diff breaks spitting out a warning that stops processing :

```
$ ansible-playbook -l server network/setup.yml -CD
...
TASK: [sometask] ********************* 
/usr/lib/python2.7/difflib.py:435: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  a[besti-1] == b[bestj-1]:
fatal: [server] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 272, in _executor
    exec_rc = self._executor_internal(host)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 328, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 479, in _executor_internal_inner
    self.callbacks.on_file_diff(conn.host, result.before_diff_value, result.after_diff_value)
  File "/usr/lib/python2.7/site-packages/ansible/callbacks.py", line 428, in on_file_diff
    print utils.get_diff(before_string, after_string)
  File "/usr/lib/python2.7/site-packages/ansible/utils/__init__.py", line 624, in get_diff
    return "\n".join(list(differ))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)


FATAL: all hosts have already failed -- aborting
```

This happens even if the local template is UTF-8 encoded too.

However, it doesn't happen when local template is UTF-8 encoded and the node's copy is ASCII encoded.

**Comment by mpdehaan** [comment]
yay, unicode!  :)

Should by easy to fix.   Thankfully --diff is not in the main code path.

**Comment by mpdehaan** [comment]
Hi, so I checked this and apparently python difflib can't construct a diff in this case.  We could write our own diff class, but as a stop-gap I've simply made it print a warning instead of a traceback in this case.  It will note the files are different, it just won't be able to show the diff.

I tried various attempts to explicitly encode things but no luck.  I would welcome further experimentation.  Closing this as it's no longer a traceback so the application can at least continue.

**Comment by ashorin** [comment]
Please, try

```
            return u"".join(ret)
```

or

```
            return "".join(map(lambda x: x.decode('utf-8'), ret))
```

in https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/__init__.py#L734

```
                differ = difflib.unified_diff(diff['before'].splitlines(True), diff['after'].splitlines(True), before_header, after_header, '', '', 10)
                for line in list(differ):
                    ret.append(line)
            return "".join(ret)
```

**Comment by ashorin** [comment]
or/and include special comment in (all) .py file(s)

```
# coding: utf-8
```

**Comment by mpdehaan** [comment]
Are you meaning to see this ticket reopened?

Since you have a fix it seems, you can submit a pull request to the code -- that may be easiest.

Thanks!
