### ISSUE TITLE
Problems with copy

### ISSUE THREAD

**Issue by PipaOzz** [ansible/ansible#20489]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- copy

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### CONFIGURATION

scp_if_ssh = true
##### OS / ENVIRONMENT

Linux EL6
##### SUMMARY

I'm trying to copy a large file over SSH (500M) from one user to a different user.
Playbook command:
------------------------------
- hosts: rms-servers
  remote_user: oracle

  tasks:

  - name: Install Java JDK
    copy: src=/autoproj/dbasoft/oracle_fmw/linux86_64/Oracle_JDK_1.8.0/p22648233_18074_Linux-x86-64.zip dest=/app/oracle/p22648233_18074_Linux-x86-64.zip
------------------

Ansible starts copying the file using scp, however instead of the DEST directory it copies the file into the remote user home directory to the tmp folder: tmp/ansible-tmp-1484891046.64-27376929546152/source
The remote filesystem fills up and the copying fails with the "No space left on device" message.

Is there a way to stop ansible writing to the local TEMP directory? 

Thanks.
##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

I would expect the file to be copied to the DEST directory without any copies to the home directory TEMP dir.
##### ACTUAL RESULTS
The file gets copied to the user home directory and filesystem fills up.

```

```

**Comment by jctanner** [comment]
@PipaOzz copying the file to a temp location first is a design choice to avoid overwriting destination files until the transfer has completed. If the default temp dir does not have sufficient space, it can be configured for a different location.

http://docs.ansible.com/ansible/intro_configuration.html#remote-tmp
