### ISSUE TITLE
File name parsing issue while changing permission of a directory

### ISSUE THREAD

**Issue by dammina** [ansible/ansible#20496]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
file module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
nothing special

##### OS / ENVIRONMENT
Running from macOS Sierra 10.12.2
OS that is being managed centOS 6.8

##### SUMMARY
Changing file permission of a directory and its content is failed due to file name parsing issue. The file path is _/opt/as2/As2MetricsService$_$tt__collectStats_closure14.class_. However it was decoded as _/opt/as2/As2MetricsService/usr/bin/python$tt__collectStats_closure14.class_ which results in no such file or directory issue.

##### STEPS TO REPRODUCE
Create the directory /opt/as2/
Place a file with name _As2MetricsService$_$tt__collectStats_closure14.class_ inside the directory /opt/as2/
Run the following task
```yaml
- name: Update link to uploaded appserver version
  file: src=/opt/as2/ dest=/opt/as2/ state=link owner=adrt group=adrt
```
##### EXPECTED RESULTS
Changing the permission of the specified directory and its content without an issue.

##### ACTUAL RESULTS
```
TASK [appserver : Change ownership of everything below /opt/as2/] ****
fatal: [192.168.1.182]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_K00ffc/ansible_module_file.py\", line 451, in <module>\r\n    main()\r\n  File \"/tmp/ansible_K00ffc/ansible_module_file.py\", line 335, in main\r\n    changed |= recursive_set_attributes(module, to_bytes(file_args['path'], errors='surrogate_or_strict'), follow, file_args)\r\n  File \"/tmp/ansible_K00ffc/ansible_module_file.py\", line 146, in recursive_set_attributes\r\n    changed |= module.set_fs_attributes_if_different(tmp_file_args, changed)\r\n  File \"/tmp/ansible_K00ffc/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1163, in set_fs_attributes_if_different\r\n  File \"/tmp/ansible_K00ffc/ansible_modlib.zip/ansible/module_utils/basic.py\", line 929, in set_owner_if_different\r\n  File \"/tmp/ansible_K00ffc/ansible_modlib.zip/ansible/module_utils/basic.py\", line 842, in user_and_group\r\nOSError: [Errno 2] No such file or directory: '/opt/as2/As2MetricsService/usr/bin/python$tt__collectStats_closure14.class'\r\n", "msg": "MODULE FAILURE"}

```

**Comment by jctanner** [comment]
Formatting the traceback to make it easier to read...
```
TASK [appserver : Change ownership of everything below /opt/as2/] ****
fatal: [192.168.1.182]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": 
"Traceback (most recent call last):\r\n
  File \"/tmp/ansible_K00ffc/ansible_module_file.py\", line 451, in <module>\r\n
    main()\r\n
  File \"/tmp/ansible_K00ffc/ansible_module_file.py\", line 335, in main\r\n
    changed |= recursive_set_attributes(module, to_bytes(file_args['path'], errors='surrogate_or_strict'), follow, file_args)\r\n
  File \"/tmp/ansible_K00ffc/ansible_module_file.py\", line 146, in recursive_set_attributes\r\n
    changed |= module.set_fs_attributes_if_different(tmp_file_args, changed)\r\n  File \"/tmp/ansible_K00ffc/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1163, in set_fs_attributes_if_different\r\n
  File \"/tmp/ansible_K00ffc/ansible_modlib.zip/ansible/module_utils/basic.py\", line 929, in set_owner_if_different\r\n
  File \"/tmp/ansible_K00ffc/ansible_modlib.zip/ansible/module_utils/basic.py\", line 842, in user_and_group\r\n
OSError: [Errno 2] No such file or directory: '/opt/as2/As2MetricsService/usr/bin/python$tt__collectStats_closure14.class'\r\n", "msg": "MODULE FAILURE"}
```

**Comment by Lujeni** [comment]
Hello @dammina,

I am unable to reproduce your bug.
Your task try to create a symlink with the same directory (src and dest). Normal ?

**Comment by Shrews** [comment]
Unable to reproduce. I find the example to reproduce unusual, too, given identical `src` and `dest` values. Given no response from the submitter, I'm going to close this. If you find this is still an issue, feel free to open a new issue with a working reproducer. 

Should you disagree with this conclusion, you may also wish to join our mailing lists, which are very active:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!
