### ISSUE TITLE
ansible-galaxy should download dependencies in meta/main.yml

### ISSUE THREAD

**Issue by manics** [ansible/ansible#20537]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ansible-galaxy

##### ANSIBLE VERSION
Future

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Local roles may depend on galaxy roles defined in `meta/main.yml`. `ansible-galaxy install -r` does not support this file format, although the value of the `dependencies` key appears to match that in a `requirements.yml` file

##### STEPS TO REPRODUCE

```
$ cat meta/main.yml

galaxy_info:
  author: ome-devel@lists.openmicroscopy.org.uk
dependencies:
- role: openmicroscopy.basedeps
```

```
$ ansible-galaxy install -r meta/main.yml`

- downloading role 'dependencies', owned by 
 [WARNING]: - dependencies was NOT installed successfully: Role has no field
named u'owner'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```
Proposed behaviour: Install all roles listed in the `dependencies` section of `meta/main.yml`, in this case `openmicroscopy.basedeps`

##### BACKGROUND

- [Galaxy dependencies file can be the role meta file](https://github.com/metacloud/molecule/pull/717#issuecomment-273455237)
  This is the original motivation for this feature suggestion. When using [molecule](https://github.com/metacloud/molecule) for testing Ansible roles dependencies need to be in a requirements file. If this is a deliberate design decision it would be useful if the docs could be updated with an official description of the `meta/main.yml` file.
- [Add ability to automatically download roles when running play](https://github.com/ansible/ansible/issues/12927)
  This is a closely related feature request.

**Comment by thapakazi** [comment]
Any update on this, I am looped into the same thingi described above :thinking:

**Comment by jwoertink** [comment]
What causes this error? I'm getting the same error message when trying to install any galaxy package.

**Comment by manics** [comment]
You need to copy the list from the `dependencies` section of `meta/main.yml` into a separate `requirements.yml` file and then run `ansible-galaxy install -r requirements.yml`. This issue is a feature request for ansible-galaxy to handle `meta/main.yml` directly.

**Comment by jwoertink** [comment]
I don't have any `meta/main.yml` file. All of my dependencies are in a requirements.yml. That's the one throwing this error. 

*Edit:* to be a bit more clear:

```
[08:58AM] ansible (develop)$ ansible-galaxy install -r requirements.yml 
- downloading role 'dependencies', owned by 
 [WARNING]: - dependencies was NOT installed successfully: Role has no field named u'owner'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

and then my requirements.yml file is

```yml
dependencies:
  - src: geerlingguy.munin-node
    version: 1.1.4
```

**Comment by jwoertink** [comment]
Ok, nevermind, I figured my issue out. I guess the requirements.yml doesn't need that `dependencies` key. I must have just read [this](http://docs.ansible.com/ansible/galaxy.html#dependencies) wrong.

**Comment by ghost** [comment]
I heavily work with dependencies and meta/main.yml and it would be great to spare the necessity to maintain the same information in two different files at all.
Further it would be great to maintain the `version:` key with jinja templating, e.g. `version: '{{ some_variable_version|default(omit) }}'`.

Any news on this?

**Comment by ghost** [comment]
```
ansible-galaxy install git+file:///path/to/roles/some-role
```

**Comment by mxlan** [comment]
I think the documentation already covers role dependency installation through meta/main.yml:dependencies.

https://docs.ansible.com/ansible/2.3/galaxy.html#dependencies

https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html#dependencies

**Comment by nickbroon** [comment]
I don't think the documentation covers how deal with a local meta/main.yml:dependencies and installing those. This issues was raised about that, and I don't believe there are any current solutions.

**Comment by widhalmt** [comment]
I just stumbled over this and would really appreciate a way to automatically all dependecies from local meta/main.yml files from custom built roles.

**Comment by ckaserer** [comment]
I ended up putting` requirements.yml` in the `molecule/scenario_name` folder and executed my tests. It works like a charm. If you want to manually install the dependency you could run `molecule dependency`.

**Comment by AlexanderKholodov46** [comment]
Faced this unexpected behavior for me.
Yes, the ansible-galaxy documentation says "and when a role is installed, any dependencies are automatically installed as well". That is, the automatic installation of dependencies when installing the target role. However, the ansible documentation says "Role dependencies allow you to automatically pull in other roles when using a role." - that is, pull (installation?) when used.
We have a rather long and complex chain of dependencies that we would like to reuse. However, the inability to transfer `meta/main.yml` as requirements to ansible-galaxy, and the lack of automatic installation of dependencies when the playing playbook, leads us to duplicate `meta/mail.yml` inside `requirements.txt `- this is not cool.
The simplest solution would be to be able to pass `meta/main.yml` to `ansible-galaxy install`. Ideally, of course, I would like to avoid the additional call of `ansible-galaxy install` when playing playbook.

**Comment by mxdlx** [comment]
I don't understand for the life of me why documentation states:

> "Role dependencies let you automatically pull in other roles when using a role."

But then nothing happens with whatever is in meta/main.yaml.

I apologize for spamming this but every time I get to work with Ansible I end up in a Github issue.

**Comment by sivel** [comment]
We now support a `meta/requirements.yml` since https://github.com/ansible/ansible/pull/68288

This is the proper and supported way to instruct ansible to download role dependencies.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
