### ISSUE TITLE
Please do not hide released versions on pypi.python.org

### ISSUE THREAD

**Issue by fr33jc** [ansible/ansible#2053]
By default, pypi autohides old versions when you publish new versions of your package:

![pypi-snappy](https://f.cloud.github.com/assets/3242144/147391/0d46cf48-74af-11e2-931a-5f541db90dbd.jpg)

However, other packages might depend on versions you've already released.  While dependents should keep their packages up-to-date, it would be really nice if depending on ansible==0.9 didn't break until maintainers got around to updating their dependencies.

**Comment by mpdehaan** [comment]
Fair enough, that seems reasonable.

I think the issue was I didn't know how to upload a file in their somewhat klunky user interface :)

Thanks for the explanation and will make a note next time.
