### ISSUE TITLE
Resolving {{ vars[VAR] }} when vars[VAR] contains {{ other_var }}

### ISSUE THREAD

**Issue by marlox-ouda** [ansible/ansible#20545]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea
(depend the point of view)

##### COMPONENT NAME
- Template/Vars

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /home/user/confs/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Access to {{ var[VAR] }} return var[VAR] without resolution if var[VAR] contains also variable like {{ other_var }}.

##### STEPS TO REPRODUCE
In _role/defaults/main.yml_
```yaml
group_A_name: "mygroupname"

user_A_groups:
  - "{{ group_A_name }}"
```

In _role/tasks/main.yml_
```yaml
- name: Test direct accesss
  debug:
    msg: "{{ user_A_groups }} is OK"
# => return mygroupname

- name: Test indirect access
  debug:
    msg: "{{ vars['user_' ~ arg_user ~ '_groups'] }} fails"
  vars:
    arg_user: 'A'
# => return {{ group_A_name }}
```

##### EXPECTED RESULTS
TASK [test : Test direct access] **********************************************

ok: [host] => {
    "msg": "['mygroupname'] is OK"
}

TASK [test : Test indirect access] *********************************************
ok: [host] => {
    "msg": "['mygroupname'] fails"
}

##### ACTUAL RESULTS
```
TASK [test : Test direct access] **********************************************
 [WARNING]: Exception in safe_eval() on expr: ['mygroupname'] is OK (invalid expression (['mygroupname'] is OK))

ok: [host] => {
    "msg": "['mygroupname'] is OK"
}

TASK [test : Test indirect access] *********************************************
ok: [host] => {
    "msg": "['{{ group_A_name }}'] fails"
}
```

##### QUICK & DIRTY SOLUTION
In https://github.com/ansible/ansible/blob/devel/lib/ansible/template/vars.py line 89~90
Replace
``` py
        if isinstance(variable, dict) and varname == "vars" or isinstance(variable, HostVars) or hasattr(variable, '__UNSAFE__'):
            return variable
```
by
``` py
        if isinstance(variable, dict) and varname == "vars" or isinstance(variable, HostVars) or hasattr(variable, '__UNSAFE__'):
            def foobar(obj, item):
                return self._templar.template(dict.__getitem__(obj, item))
            cls = type('',(dict,), {'__getitem__': foobar }
            return cls(variable)
```

**Comment by marlox-ouda** [comment]
It will be also convenient to overload ``dict.get(obj, item, default)`` function.
For example :
``` py
        if isinstance(variable, dict) and varname == "vars" or isinstance(variable, HostVars):
            def foo(obj, item):
                return self._templar.template(dict.__getitem__(obj, item))
            def bar(obj, item, d=None):
                return self._templar.template(dict.get(obj, item, d))
            cls = type('', (dict,), {'__getitem__': foo, 'get':bar})
            return cls(variable)
```

**Comment by marlox-ouda** [comment]
@alikins Are you agree with the proposed modification or do you think is better to integrate such feature in the core of "vars" variable ?
Do you want a change request with this modification ?

**Comment by krzysztof-magosa** [comment]
Any update?

**Comment by bcoca** [comment]
`vars` is an undocumented variable and not meant for user access, see the `vars` lookup instead:

https://docs.ansible.com/ansible/latest/plugins/lookup/vars.html
