### ISSUE TITLE
Documentation on how to develop action plugins

### ISSUE THREAD

**Issue by rhcarvalho** [ansible/ansible#20557]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

Action plugins.

##### ANSIBLE VERSION

All versions.

##### SUMMARY

There seem to be no official documentation on how to develop action plugins.
They are briefly mentioned in http://docs.ansible.com/ansible/dev_guide/developing_plugins.html, without any specific information.

##### EXPECTED RESULTS

Plugin development, testing, debugging and supported APIs should be documented.

##### ACTUAL RESULTS

One needs to resort to reading examples in the source tree, without any documentation, docstrings, statement of purpose of each plugin, and so on. It is unclear what classes and methods are part of the supported API.
It is hard to iterate on plugin development.

**Comment by JimFicarra** [comment]
I second this doc request. This has been outstanding for quite some time and needs an overhaul.

**Comment by dharmabumstead** [comment]
Working on it. Thanks for the feedback!

**Comment by rhcarvalho** [comment]
FWIW, a colleague sent me this link yesterday, might be useful to others following this issue:

https://www.ansible.com/blog/how-to-extend-ansible-through-plugins

**Comment by gustavooferreira** [comment]
Hey, any updates on this?

**Comment by cesar3030** [comment]
Still no docs for action plugins? :cry:

**Comment by matthew-hickok** [comment]
Any updates on this?

**Comment by nesanton** [comment]
Is it being worked on?

**Comment by acozine** [comment]
@rhcarvalho @nesanton @matthew-hickok @gustavooferreira @JimFicarra thanks for being active in the community and advocating for better documentation. Realistically, we won't be writing any new docs before Ansible Fest, which is next week in Austin, TX. Hope to see some of you there! After Fest, we'll be revisiting the issue backlog.

**Comment by Akasurde** [comment]
@rhcarvalho @nesanton @matthew-hickok @gustavooferreira @JimFicarra Could you please check above PR and let me know if it helps ? Devel docs look like [this](https://docs.ansible.com/ansible/devel/dev_guide/developing_plugins.html#action-plugins)

**Comment by nesanton** [comment]
Seems like it's about what I needed back then.

**Comment by rhcarvalho** [comment]
@Akasurde thank you very much for the PR! I'll close this issue as being resolved. Now the docs for action plugins is on par with the other plugin types. :tada:
