### ISSUE TITLE
Docs request -- configurables in environment

### ISSUE THREAD

**Issue by fdavis** [ansible/ansible#2057]
Should mention that you can set most of the configurables with environment variables?

There are a few mentions of them here and there, but without knowing to dig into lib/ansible/constants.py, I don't know how anyone would find out about the environment variables.

**Comment by mpdehaan** [comment]
I concur.

We should probably document the configuration file settings too.

This is probably a page in docs to itself.

**Comment by mpdehaan** [comment]
Ok, patches accepted on this.   I generally want folks using the config file when possible so these are not deprecated, but they aren't the main way we expect things to be used.
