### ISSUE TITLE
Issues with string concat and implicit conversion of bytes to chars

### ISSUE THREAD

**Issue by quinn** [ansible/ansible#20588]
in `ansible/inventory/script.py` there is code like:

```python
if not isinstance(self.raw, Mapping):
    sys.stderr.write(err + "\n")
    raise AnsibleError("failed to parse executable inventory script results from {0}: data needs to be formatted as a json dict".format(to_native(self.filename)))
```

I had to to change to this to get the actual error message (instead of the encoding error): `sys.stderr.write(err.decode('ascii') + "\n")`

I'm running python 3.

**Comment by ryansb** [comment]
Can you add information about how to reproduce the error message? Just running inventory scripts under Python 3?

**Comment by quinn** [comment]
Yes, I'm working on an inventory script. The error message was the one above "data needs to be formatted as a json dict" but instead I was getting "Can't convert 'bytes' object to str implicitly" error

**Comment by quinn** [comment]
Also, I am running ansible 2.1, but the source in the master branch here (assuming that is 2.3) I assume has the same problem because it is not encoding the err object

**Comment by ryansb** [comment]
@quinn here's a patch that should resolve the problem for you, using our `to_native` method rather than manual decode. Can you give it a try? https://github.com/ansible/ansible/pull/20835
