### ISSUE TITLE
template_module lose it's relative path when role include other role

### ISSUE THREAD

**Issue by sirkubax** [ansible/ansible#20597]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
template_module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### SUMMARY
When **Role Includes the Role**, the template module browse the incorrect path looking for a template file

##### STEPS TO REPRODUCE

```
[run with -vvvvv to see the paths]

TASK [app_campaigns_manager : Ensure service configuration] ********************
task path: /home/me/ansible/etc/playbooks/roles/app_generic/tasks/service.yml:1
looking for "upstart.conf" at "/home/me/ansible/etc/playbooks/roles/app_campaigns_manager/templates/upstart.conf"
looking for "upstart.conf" at "/home/me/ansible/etc/playbooks/roles/app_campaigns_manager/upstart.conf"
looking for "upstart.conf" at "/home/me/ansible/etc/playbooks/roles/app_generic/tasks/templates/upstart.conf"  <<< TASKS?
looking for "upstart.conf" at "/home/me/ansible/etc/playbooks/roles/app_generic/tasks/upstart.conf"
looking for "upstart.conf" at "/home/me/ansible/etc/playbooks/templates/upstart.conf"
looking for "upstart.conf" at "/home/me/ansible/etc/playbooks/upstart.conf"
```
The correct path is:
`/home/me/ansible/etc/playbooks/roles/app_generic/templates/upstart.conf`

##### Observation
The problem happen, because the playbook include the role that include the role:
`playbook -> role: app_campaigns_manager -> role: app_generic`

```
playbook.yml
(...)
 roles: app_campaigns_manager 


roles/app_campaigns_manager/tasks/main.yml
(...)
- include: ../../app_so1_generic/tasks/main.yml

```

##### EXPECTED RESULTS
Browse the proper files :)

I know the template_module has 'template_path' and 'template_fullpath', but still it would be nice it the roles would be aware of it's location independent of it's include/execution. 

---
I may take a minute later, to prepare PR, but having rather busy time, so any help appreciated.

**Comment by sirkubax** [comment]
Btw - if you struggle with this issue, you can workaround:

1. Use 

> role_path
 ```
   template: |
-      src=upstart.conf
+      src="{{ role_path }}/../YOUR_ROLE_NAME/templates/upstart.conf
```

2. Use this hack:
```
   template: |
-      src=upstart.conf
+      src=../templates/upstart.conf
```

3. Define and use 

> template_path

Ref:
http://docs.ansible.com/ansible/template_module.html
https://github.com/ansible/ansible/issues/10374

**Comment by sirkubax** [comment]
side topic  (I know it is picking at the words but...)
@bcoca @samdoran  
'template_path the absolute path of the template, template_fullpath is the absolute path of the template,'
https://github.com/ansible/ansible/blame/bd793b85bff331e7d3ca613bf44a26f0345747d5/lib/ansible/modules/files/template.py#L37
Not sure if I get it :P

it seems that template_fullpath is not in use atm.

---
Edit: it seems that this is dome deprecated part of the old code, moved by @jimi-c.
No problem
Just please decide which way should it go.

**Comment by bcoca** [comment]
so the main issue here has to do with how Ansible lazily evaluates variables, for change in behaviour we have a request for non lazy evaluation in #10374, so i'm closing this as a duplicate.
