### ISSUE TITLE
need to fix various things with file module and --check mode

### ISSUE THREAD

**Issue by leucos** [ansible/ansible#2059]
The file module was able to change perms on the managed node even in check mode.
Since nothing seems to be implemented yet in this module, shouldn't it be safer to set 

```
supports_check_mode=True
```

in the module ?

**Comment by mpdehaan** [comment]
Hmm, I'll investigate.  --check is still in development for 1.1

supports_check_mode=True might be neccessary to actually make check mode
work as the plumbing behind the file module is mostly coded in
ansible_module_common.

Thanks for heads up!

**Comment by britcey** [comment]
related - 'copy' with dest pointing to a directory without a trailing slash will always indicate a change with --check;  it will correctly show it as unchanged if there is a trailing slash:

This always shows up as changed with -C:
      action: copy src=$base/server_config/etc/sysconfig/nagios dest=/etc/sysconfig owner=root mode=0555

This does not:
      action: copy src=$base/server_config/etc/sysconfig/nagios dest=/etc/sysconfig/ owner=root mode=0555

(the above assumes that the 'nagios' file is already in place on the server)

**Comment by dhozac** [comment]
copy to a (reachable) directory should now be doing the right thing, regardless of trailing slash.

**Comment by mpdehaan** [comment]
just fixed the file module in check mode:  cd32597

Please open a new ticket if there are other issues so we can track seperately!
