### ISSUE TITLE
Non-working example for configuring log driver in ansible module docker_container 

### ISSUE THREAD

**Issue by bbayani** [ansible/ansible#20591]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
Module: docker_container

##### ANSIBLE VERSION
```
[root@gsljumphost doc_isse]# ansible --version
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides

```

##### CONFIGURATION
Mention any settings you have changed/added/removed in ansible.cfg : None

##### OS / ENVIRONMENT
OS : Centos 7

##### SUMMARY
The example given for configuring syslog output at https://docs.ansible.com/ansible/docker_container_module.html does not work on latest docker version. The logging option 'syslog-tag' is changed to 'tag' (Ref:  https://docs.docker.com/engine/admin/logging/overview/) 

##### STEPS TO REPRODUCE
Run the site.yml given below on any server with docker version 1.13/greater

```
root@gsljumphost doc_isse]# docker --version
Docker version 1.13.0, build 49bf474

[root@gsljumphost doc_isse]# cat site.yml 
- hosts:
  - all

  tasks:
    - name: Syslogging output
      docker_container:
        name: myservice
        image: busybox
        log_driver: syslog
        log_options:
          syslog-address: tcp://localhost:514
          syslog-facility: daemon
          syslog-tag: myservice


[root@gsljumphost doc_isse]# ansible-playbook -i "localhost," -c local site.yml 

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Syslogging output] *******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error creating container: 500 Server Error: Internal Server Error (\"unknown log opt 'syslog-tag' for syslog log driver\")"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1  

```

##### EXPECTED RESULTS
Container should be created successfully and logs from container should have program-name 'myservice'

##### ACTUAL RESULTS
Ansible playbook fails with error: unknown log opt 'syslog-tag' for syslog log driver

**Comment by ryansb** [comment]
The module docs have been updated to reflect the 1.13 change to this option, with a note about older versions calling it `syslog-tag`.

**Comment by ryansb** [comment]
Closed-by https://github.com/ansible/ansible/commit/7a19a18e619da4ce48795ab4fc9ad5f8b55e2dda
