### ISSUE TITLE
Ansible 2.2.1 fails on quotations in playbooks and templates, most playbooks broken

### ISSUE THREAD

**Issue by ybalt** [ansible/ansible#20593]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Ansible core

##### ANSIBLE VERSION
ansible 2.2.1.0

##### CONFIGURATION
deafult, installed from Ansible ppa

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Looks like new version of Ansible 2.2.1 fails in some cases when processing playbooks and templates
that have quotation
Previous version 2.2.0 works fine

##### STEPS TO REPRODUCE
this is from Kargo playbook, ansible playbook to install Kubernetes
works with Ansible 2.2.0 and fails with 2.2.1
```
- name: Register docker images info
  shell: "{{ docker_bin_dir }}/docker images -q | xargs {{ docker_bin_dir }}/docker inspect -f {% raw %}'{{.RepoTags}},{{.RepoDigests}}'{% endraw %}"
  register: docker_images_raw
  failed_when: false
  when: not download_always_pull|bool
```
this works for 2.2.1
```
- name: Register docker images info
  raw: >-
    {{ docker_bin_dir }}/docker images -q | xargs {{ docker_bin_dir }}/docker inspect -f "{{ '{{' }} .RepoTags {{ '}}' }},{{ '{{' }} .RepoDigests {{ '}}' }}"
  register: docker_images_raw
  failed_when: false
  when: not download_always_pull|bool
```

##### EXPECTED RESULTS
At least some notes to Release Notes for 2.2.1 changes about quotation

##### ACTUAL RESULTS
I have automatic installation of Ansible from PPA, but with new version my roles are completely broken
and need to be reviewed/refactored.
Moreover, 2.2.0 is removed from PPA, so for me it is really disaster and work stopper.

Can you please put 2.2.0 back in PPA and PLEASE note in case of such  significant changes. 

Thanks!

**Comment by ryansb** [comment]
This is a duplicate of #20568 (same raw/endraw issue). Version 2.2.0 has a vulnerability and as such will not be added to PPA again. You may install from the git tag for v2.2.0.0-1 if you absolutely require the 2.2.0 version.
