### ISSUE TITLE
Using fetch in a playbook throws a traceback

### ISSUE THREAD

**Issue by azemon** [ansible/ansible#206]
I wrote a very simple playbook and fetch throws a traceback every time.

``` yaml

---
- hosts: cloud1.hens-teeth.net
  tasks:
  - name: test copy
    action: copy src=/etc/hosts dest=/var/tmp/hosts
  - name: test fetch
    action: fetch src=/var/log/messages dest=/root/ansible/az
```

```
unreachable: [cloud1.hens-teeth.net] => Traceback (most recent call last):
  File "/root/ansible/lib/ansible/runner.py", line 615, in _executor
    (host, ok, data, err) = self._executor_internal(host)
  File "/root/ansible/lib/ansible/runner.py", line 665, in _executor_internal
    self.callbacks.on_ok(host, data)
  File "/root/ansible/lib/ansible/callbacks.py", line 155, in on_ok
    if invocation.startswith('async_status'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Despite the traceback, it did fetch the file and store it successfully.

Sorry... I'm new to git and don't know how to get the version that I am running. I ran `git clone git://github.com/ansible/ansible.git` this morning.

-- Art Z.

**Comment by mpdehaan** [comment]
Ok, it's not returning the invocation variable as a string.    Should be an easy fix, thanks for the heads up.

**Comment by mpdehaan** [comment]
fixed on the integration branch, merging into master as part of the 0.3 release right now.
