### ISSUE TITLE
yum module parsing of wrapped 'yum check-update' output causes package updates to be skipped

### ISSUE THREAD

**Issue by saamich** [ansible/ansible#20608]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
yum module

##### ANSIBLE VERSION
2.2.1 (2.2.1.0-1ppa~xenial)

##### OS / ENVIRONMENT
Control machine: Ubuntu 16.04
Remote machine: Centos 7.3.1611

##### SUMMARY
After fix this issue [#4318](https://github.com/ansible/ansible-modules-core/issues/4318)
the first packet (in alphabetical order output  of yum check-update),  that requires update, is not updated  -  not correctly parsed output of 'yum check-update'. The first line, which describes a new package and its version is added to the previous one and the package "excluded" from the update.

Problematic piece of [code](https://github.com/ansible/ansible-modules-core/blob/59c9a6d3c20e73641c430fdaa3f250c1ff431dcc/packaging/os/yum.py#L804):
` # remove incorrect new lines in longer columns in output from yum check-update
out=re.sub('\n\W+', ' ', out)`

workaround:
 this [patch:](https://gist.github.com/saamich/b701c1d45cf877ddc3938c5cb63aec30) work for i686/x86-64 and noarch packages. Rpm package name in "yum check-update" output ends to the architecture name under which the assembled package.

##### STEPS TO REPRODUCE
1) execute "yum check-update" on not updated node with centos 7.3.1611 (example - NODE) and look first package, which needs to be updated(example PKG-NAME).
2) execute ansible on this node 
ansibble NODE -m yum -a 'name=PKG-NAME state=latest'

##### EXPECTED RESULTS
package updated

##### ACTUAL RESULTS
package not updated

**Comment by alikins** [comment]
Could you provide an example of the 'yum check-update' output that is causing the problem?

**Comment by saamich** [comment]
hello, this output after "yum check-update 2>&1 >file"

[yum_check-update.txt](https://github.com/ansible/ansible/files/739507/yum_check-update.txt)

**Comment by saamich** [comment]
may be fix this issue (not full tested)
`out=re.sub(r'(\.[^\.\s]+)\W+(\w+)', r'\1 \2', out)`

**Comment by digi691** [comment]
My team ran into this issue as well when trying to install the latest ceph package with Ansible 2.2.1.  After troubleshooting the yum plugin we noticed it was lopping off the first package ceph.x86_64. I've included a link to the output of `yum check-update 2>&1 > file` as my output looks different than saamich's.

[https://github.com/digi691/check_update_output/blob/master/yum_check_update_ceph.txt](url)

Also like to add the the remote machine is also CentOS Linux release 7.3.1611.

**Comment by mvermaes** [comment]
Can confirm what seems like the same behaviour with the 'first' package being skipped when managing CentOS 6 and CentOS 7 hosts with Ansible 2.2.1.0.

I'm using Fedora 24 as the Ansible control machine, but the same occurs with CentOS 6/7. https://gist.github.com/mvermaes/3ac84bb4ac3a8060470545540ca52673 has an example of how to reproduce in a CentOS 6 Vagrant box.

**Comment by saamich** [comment]
Repository name to can also be transferred to the new line. In file output from yum check-update > file
[log.txt](https://github.com/ansible/ansible/files/747963/log.txt)

**Comment by saamich** [comment]
repoquery work fine
repoquery -q -a --qf="%{name} %{version}-%{release}.%{arch} %{repoid}" --pkgnarrow=updates
[log.txt](https://github.com/ansible/ansible/files/747968/log.txt)

**Comment by saamich** [comment]
workaround for use repoquery instead 'yum check-update' for 'state=latest'
[patch.txt](https://github.com/ansible/ansible/files/748239/patch.txt)
