### ISSUE TITLE
[GCE] module stacktrace when invalid zone/region is provided

### ISSUE THREAD

**Issue by supertom** [ansible/ansible#20616]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea

##### COMPONENT NAME
gce

##### SUMMARY

When an invalid zone/region is supplied, the module should inform the user.  Currently, the user ends up with a stacktrace and is left to root-cause the issue themselves.

Filed in response to ansible/ansible/issues/18977 and comments by @dminca, @walbert947

##### EXPECTED RESULT

If an invalid zone or region is supplied, the module should error gracefully, informing the user that it's invalid.

**Comment by gundalow** [comment]
@supertom Is this something you'd be interested in fixing?
(or one of the other people CC'd on this ticket?)

**Comment by supertom** [comment]
Yes, you may assign it to me.

**Comment by gundalow** [comment]
Thanks Tom :)
