### ISSUE TITLE
state=query

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#2062]
Generally speaking most modules assume state=present for those that accept a state.

For inventory purposes from an API perspective or using /usr/bin/ansible it would be nice if all of them supported a state=query type behavior that could gather the state of interesting resources without assuming such things.  

I still kind of think state=present needs to be implied as we can't break existing playbooks any.

Thoughts?

cc @skvidal @sfromm @dhozac

**Comment by skvidal** [comment]
So - depending on what is included - this could be a lot of data, for example, from the yum plugin.

yum list installed
yum list updates
yum list available

could all be certainly reasonable sets of data to return. That's a non-trivial amount of stuff depending on what you have installed and/or what repos you have enabled.

I'm not against it - but I suspect this will get expensive.

**Comment by mpdehaan** [comment]
Ok, so all I want in this case is the state of a particular resource,
rather than all the module knows.

so:
- yum: name=asdf state=query

{
   name: asdf,
   state: installed
   # maybe the version info
}

**Comment by skvidal** [comment]
On Tue, 12 Feb 2013, Michael DeHaan wrote:

> Ok, so all I want in this case is the state of a particular resource,
> rather than all the module knows.
> 
> so:
> - yum: name=asdf state=query
> 
> {
> name: asdf,
> state: installed
> 
> # maybe the version info
> 
> }

Then in this case I can provide that.

-sv

**Comment by mpdehaan** [comment]
Cool, yeah we have a little bit of work to do to add this everywhere (or in
most places), but like check, it's going to be useful.

**Comment by dhozac** [comment]
Sounds like a great idea to me.

**Comment by mpdehaan** [comment]
this is probably going to be done as the inventory namespace of modules as Seth and I were discussing previously.

**Comment by mpdehaan** [comment]
Closing this as this will likely be significantly transgmogrified, but it's on my list of things to explore.
