### ISSUE TITLE
Ansible tries to load dependency even when "when" condition is false

### ISSUE THREAD

**Issue by mprasil** [ansible/ansible#20631]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = ./ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Just `vault_password_file` is set there, no other changes.

##### OS / ENVIRONMENT
RHEL 6.8 is the control host, trying to manage CentOS and RHEL 7 hosts. The important thing is, we have no Debian/Ubuntu hosts.

##### SUMMARY
ansiblebit.oracle-java role defines dependencies like this: 

```
dependencies:
  - role: ansiblebit.launchpad-ppa-webupd8
    when: ansible_distribution | lower == 'debian' or ansible_distribution | lower == 'ubuntu'
```
Even though we have no Ubuntu/Debian based hosts in our inventory, when I run a playbook, that's using that role, it fails with: 

```
ERROR! the role 'ansiblebit.launchpad-ppa-webupd8' was not found
```

Note, that I'm using [ansiblebit.oracle-java](https://github.com/ansiblebit/oracle-java) just as an example and it seems like Ansible always tries to lookup the dependencies even though they shouldn't be needed. This totally makes sense from technical standpoint, because it seems to fail before setup phase so at that stage Ansible doesn't know whether it needs that dependency or not, but it makes me wonder if that's the expected behavior and what is the purpose of `when` condition in this case.

##### STEPS TO REPRODUCE
See above, just use the `ansiblebit.oracle-java` without installing `ansiblebit.launchpad-ppa-webupd8` role.

##### EXPECTED RESULTS

I was hoping that the role wouldn't be required, because we have no servers that would need it. (perhaps some kind of lazy loading) At least I would like to have some documentation, that would explain how `when` condition works in this case and what is its purpose if its not conditional loading of dependencies.

##### ACTUAL RESULTS
Run fails with `ERROR! the role 'ansiblebit.launchpad-ppa-webupd8' was not found`, the `when` condition seems to be ignored.

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The `when` conditional is not applied to the 'role loading' it is appended to each task in the role. As such you cannot conditionally load roles this way. Look at `include_role` instead. https://docs.ansible.com/ansible/include_role_module.html

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by mprasil** [comment]
Thanks for explanation, is that functionality documented anywhere?

**Comment by bcoca** [comment]
http://docs.ansible.com/ansible/playbooks_roles.html#roles

"This works by applying the conditional to every task in the role. Conditionals are covered later on in the documentation."
