### ISSUE TITLE
ConfigureRemotingForAnsible.ps1 fails if not run as local administrator

### ISSUE THREAD

**Issue by jhawkesworth** [ansible/ansible#20654]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ConfigureRemotingForAnsible.ps1
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 6673673042) last updated 2017/01/25 08:11:36 (GMT +100)
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

stock configuration
##### OS / ENVIRONMENT

controller: WSL (windows pretending to be Ubuntu 16.04)
target: Windows Server 2012 R2
##### SUMMARY

Now that ConfigureRemotingForAnsible.ps1 writes to the event log, it attempts to access the security log, but this is not available, if for example you are running as a domain administrator.
Typically ConfigureRemotingForAnsible.ps1 would be run as a local administrator, but there are occassions, such as when you wish to regenerate the self-signed certificate where it is useful to be able to run as a domain administrator.
##### STEPS TO REPRODUCE

connect to a server 2012 r2 machine via remote desktop as a domain administrator
download ConfigureRemotingForAnsible.ps1
wget https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 -Output ConfigureRemotingForAnsible.ps1
attempt to run .\ConfigureRemotingForAnsible.psi1

```yaml

```

##### EXPECTED RESULTS

remoting to be set up
##### ACTUAL RESULTS

fails as security event log is not available 

```
sorry don't have exact output available at this time, will update if required.
```

**Comment by jhawkesworth** [comment]
@dagwieers - would be grateful if you could take a look at this.

**Comment by jhawkesworth** [comment]
an option not to write to event logs would suit my needs

**Comment by dagwieers** [comment]
Hmmm, does the domain administrator not have the same rights as a local administrator ?

**Comment by jhawkesworth** [comment]
Not necessarily.  I know from experience that the same domain administrator doesn't have rights to start windows updates for example.  Account definitely is a domain admin as I have used it to add new vms to a domain.

**Comment by dagwieers** [comment]
So what can a Domain Administrator do by default to the EventLog. I find it peculiar that a tool is not able to write to the EventLog, every tool should be able to log to the EventLog, that's the purpose of the EventLog ?

I am open to log to a file as well by default. And ignore if opening the EventLog fails, however not before we have investigated other possibilities to write our events to the EventLog, like any other application would do. (Run by an Administrator or not)

**Comment by JimFicarra** [comment]
@jhawkesworth - Typically, the Domain Administrator groups is in the local Administrators group on each box in the domain by default. The access level to the event logs should effectively be the same.  I would verify this is the case on the box where you tried to run the script.

Also, according to the PowerShell Docs, New-EventLog (used in this script to create a new event source) requires PowerShell to be with elevated permissions (e.g. "run as Administrator".).  This also goes for Write-EventLog and Remove-EventLog.  When you were running as a domain admin, was it run in an elevated PowerShell prompt? If not, this could be part of your issue.

Incidentally, I'm 99% sure these PowerShell commands use the underlying [.NET EventLog Class](https://msdn.microsoft.com/en-us/library/system.diagnostics.eventlog(v=vs.110).aspx) - which also discusses the need to run with elevated privs and some details about the underlying security access tokens.  

With respect to the docs explaining why elevated privs are needed and how, on Windows 2003 or Windows Vista or later, admin credentials are needed:
```
If the event source for the event log associated with the EventLog instance doesn't exist, a new
event source is created. To create an event source in Windows Vista and later or
Windows Server 2003, you must have administrative credentials.

This requirement is because all event logs, including Security logs, must be searched to determine
whether the event source is unique. Starting with Windows Vista, users do not have permission to
access the Security log; therefore, a SecurityException is thrown.
```
Not that you are doing this on Windows 2003 (I imagine you are doing this in Windows 2008 or 2012),, but just providing context to the Security Log exception.

I would definitely try ensuring you're running in an elevated PowerShell prompt and executing again.

**Comment by dagwieers** [comment]
@JimFicarra That would make perfect sense. And I would expect you need elevated privileges for running ConfigureRemotingForAnsible.py anyhow, I doubt you can change the firewall and enable the WinRM service without elevated privileges.

I wonder if we can add a small snippet checking for elevated privileges and notifies the user if they're missing.

**Comment by jhawkesworth** [comment]
Just catching up with PRs, thanks @JimFicarra for above explanation and @nitzmahone for the pragmatic fix.
Oddly domain admins are added to the Administrators group but the specific domain admin user isn't listed.
