### ISSUE TITLE
raw module imposes vt100 terminal

### ISSUE THREAD

**Issue by madduck** [ansible/ansible#2065]
When running a command with the `raw` module, it is executed in the context of TERM=vt100 and a terminal sized 80x24:

```
ansible localhost-m raw -a 'sh -c "echo $TERM $COLUMNS $LINES"'
localhost | success | rc=0 >>
vt100 80 24
```

This has negative impact on some programs which format their output according
to these data. Arguably, those should be fixed, and arguably, I should not be
using `raw` anyway, but I also cannot see a reason why the `raw` module should
do anything like that, which makes it, uh, not really raw anymore…

**Comment by mpdehaan** [comment]
It's pretty raw, which is why you should use command and shell.

AFAIK we do not pass down any terminal settings and those are just coming
from your defaults.

**Comment by mpdehaan** [comment]
The raw module is mainly there for (A) bootstrapping python, and (B) talking to devices that never had (or will) python on them, where typically you are only going to care about the return codes.

**Comment by madduck** [comment]
What if I need `raw` for something else?

Also, the terminal settings are not set by me:

```
% cat /tmp/ansible-test.sh
#!/bin/sh
echo $TERM $COLUMNS $LINES

% ansible -i ./hacking/inventory local -m raw -a /tmp/ansible-test.sh
localhost | success | rc=0 >>
vt100

% ssh localhost /tmp/ansible-test.sh </dev/null

# (no output)
```

I don't know where `vt100` comes from, but I only see it with ansible — and
with all modules, `raw`, `command`, and `shell`!

Can we leave this issue open until it's resolved?

**Comment by mpdehaan** [comment]
They are coming from your login environment, I'm not setting them.

**Comment by mpdehaan** [comment]
FWIW, I am TOTALLY fine with feeding it < /dev/null :)

Let's do that :)

**Comment by madduck** [comment]
No, they are coming from paramiko. If I use `-c ssh`, these defaults are not set.

I don't think paramiko should impose these defaults. Do you want another ticket?

**Comment by madduck** [comment]
And the `< dev null` was part of testing, it does not change the behaviour subject to this ticket.

**Comment by madduck** [comment]
It's the paramiko connection's call to `chan.get_pty()` in `Connection.exec_command` who's at fault.

**Comment by mpdehaan** [comment]
Need the pty for sudo.

**Comment by madduck** [comment]
Sure (except sudo can be configured not to require a tty). Anyway, the tty should inherit the parameters of the terminal in which ansible is invoked, not the (very conservative) defaults defined by python-paramiko.

**Comment by mpdehaan** [comment]
I would try using -c ssh if you don't like paramiko.

What we are doing with it is pretty basic.

We have had lots of discussion on the pty's and they are pretty well
needed... arrived at through a LOOOOOONG history of experimentation :)

**Comment by madduck** [comment]
I am not arguing against the ptys. I am arguing that you should use paramiko in the same way that OpenSSH works, i.e. inherit the terminal capabilities.

**Comment by mpdehaan** [comment]
Patches would be accepted if they don't break sudo passwords or anything
else.

**Comment by mpdehaan** [comment]
merged in, so closing, thanks!

**Comment by dagwieers** [comment]
The `raw` module still has this problem. Since it exposes a pty, every command "thinks" it is writing to a terminal. As a result output is formatted for terminal usage, and different from 'command' and 'shell'.

```
[id833028@el1921 ~]$ ansible -m raw -a 'ls /' el1231
el1231 | success | rc=0 >>
bin   cgroup  etc   lib    lost+found  misc  net  opt   root  selinux  sys  usr
boot  dev     home  lib64  media       mnt   nsr  proc  sbin  srv      tmp  var
```

versus

```
[id833028@el1921 ~]$ ansible -m command -a 'ls /' el1231
el1231 | success | rc=0 >>
bin
boot
cgroup
dev
...
```

The reason for making `raw` as close as possible to `shell` is that for some devices `command` or `shell` no longer works because of python incompatibilities (e.g. `command` and `shell` no longer works on RHEL4)

**Comment by madduck** [comment]
No, don't make `raw` as close as possible to `shell`. `raw` should be "raw", end of story. `shell` should invoke a shell, and `command` may do some setup before spawning a command without a shell.

**Comment by dagwieers** [comment]
@madduck No need for semantic discussions. It makes no sense to have `raw` think it has an interactive shell, whereas `shell` and `command` do not. The example should be quite clear.

BTW `raw` now behaves a lot like `shell` anyway, because you get a shell and can do variable substitution, piping, etc... Not sure how you would define "raw" anyway.

**Comment by madduck** [comment]
@dagwieers yes, neither shell nor tty. I even think _none_ of the three should get a tty, unless explicitly requested, but @mpdehaan doesn't seem to agree.
