### ISSUE TITLE
chmod of a directory fails

### ISSUE THREAD

**Issue by liedekef** [ansible/ansible#2067]
TASK: [file path=/root mode=700] ********************\* 

failed: [xxx] => {"failed": true, "group": "root", "mode": "0700", "owner": "root", "path": "/root", "state": "directory"}
msg: refusing to convert between directory and file for None

**Comment by dhozac** [comment]
You have to set state=directory when modifying a directory, otherwise it is looking for a file, as the default state is file.

**Comment by liedekef** [comment]
Although I can accept your answer in the spirit of things, but why would chmod or chown need to be aware of the fact if it is a file or a dir? That's not very unix-like

**Comment by EvanDotPro** [comment]
I also ran into this. I haven't looked at the code behind this to understand the reason yet, but perhaps it would at least be logical to imply state=directory if they already have recurse=yes.

**Comment by mpdehaan** [comment]
@liedekef if you want to issue a blind chmod, you can use the file module for that.

@EvanDotPro I'd agree with that last one, patch would be accepted!

**Comment by jyap808** [comment]
@mpdehaan Just put in a pull request for this.  Thanks!

**Comment by EvanDotPro** [comment]
@jyap808 Beat me to it, thanks!
