### ISSUE TITLE
List of core modules working with Windows is displayed as a line

### ISSUE THREAD

**Issue by KroArtem** [ansible/ansible#20696]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
Windows support

##### ANSIBLE VERSION
```
2.2.1
```

##### CONFIGURATION
No changes

##### OS / ENVIRONMENT
Doesn't matter
##### SUMMARY
In http://docs.ansible.com/ansible/intro_windows.html#what-modules-are-available
the table following this text `In addition, the following core modules work with Windows:` is broken, it's shown as a line of text.
Also these modules are repeated at least three times (can be found by Ctrl-f "including" and Ctrl-f "though also")

##### STEPS TO REPRODUCE
Go to http://docs.ansible.com/ansible/intro_windows.html#what-modules-are-available

##### EXPECTED RESULTS
A table that clearly lists core modules that also work with Windows.

##### ACTUAL RESULTS
Some modules are repeated three times here and there.

**Comment by jhawkesworth** [comment]
I'm going to close this as it has been fixed now, along with another error where assemble appeared in this list erroneously.
