### ISSUE TITLE
[devel] Set exit status to non-zero on failure

### ISSUE THREAD

**Issue by azemon** [ansible/ansible#207]
Neither ansible nor ansible-playbook sets a non-zero exit status on failure. E.g., 

```
ansible -i server.lst cloud1.hens-teeth.net -m file -a "src=/etc/hosts dest=/var/tmp/hosts"
```

fails but $? is still set to 0. It would be much easier to plug ansible into other automated systems if it set a non-zero exit status if the number of failed actions is > 0.

**Comment by mpdehaan** [comment]
this is quite reasonable

**Comment by mpdehaan** [comment]
note: should return 0 if any failures for ansible but if any failures in any playbook for /usr/bin/ansible-playbook

**Comment by cocoy** [comment]
mpdeehan: 

for ansible return 0 if failure,  
but  for ansible-playbook? not sure what you mean here.. or  my logic is lame :)

**Comment by mpdehaan** [comment]
I think you have to, for every play, add up the failure counts for each play, as it prints at the end of the playbook.  I think that's available in the stats variable, more or less.  The playbook can have more than one play, of course -- so you wait until the end of all the playbooks.  If the number of failures for any host on any play is greater than zero, the return code for the final ansible command will be 1.

**Comment by mpdehaan** [comment]
Upon further review, I'm not going to implement this.   Ansible didn't fail.   Remote infrastructure failed.

**Comment by mpdehaan** [comment]
We can handle this for playbooks in 0.5 when it's easier to collate results.   I'll file a feature request for it there.   I'll take patches for /usr/bin/ansible.

**Comment by anirudh-wa** [comment]
Hi,

I am executing the following command.

ansible-playbook -i ec2.py ec2-create.yml.

I am executing this in a shell script. I want to know the return value of that command. What does it return on success and what does it return on failure ?
