### ISSUE TITLE
Assemble Module Fails on Windows

### ISSUE THREAD

**Issue by tonyskidmore** [ansible/ansible#20700]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

assemble_module

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /home/tony/ansible/packer/ansible.cfg
  configured module search path = Default w/o overrides

```

##### CONFIGURATION

$ cat ansible.cfg

[defaults]
inventory = ./inventory
callback_whitelist = active_directory_callback
retry_files_enabled = False
host_key_checking = False

##### OS / ENVIRONMENT

controller: Red Hat Enterprise Linux Server release 7.3 (Maipo)
target: Windows Server 2012 R2

##### SUMMARY

Assemble module fails to run against a Windows server as it tries to execute '/usr/bin/python' in the PowerShell code.  

This should work according to:

http://docs.ansible.com/ansible/intro_windows.html

and

https://github.com/ansible/ansible/issues/16255 (note: "assemble (haven't tested, but should work)")

Also tested on 2.3 with same result.

##### STEPS TO REPRODUCE

```yaml

---
- name: Test Assemble
  hosts: windows_server

  tasks:

  - name: Assemble Test Files
    assemble:
      src: "{{ playbook_dir }}/files"
      dest: "d:/build/assembled.txt"


```

##### EXPECTED RESULTS

Produce assembled.txt file from text file fragments on the remote Windows server.

TASK [Assemble Test Files] *****************************************************
changed: [localhost]

##### ACTUAL RESULTS

```
TASK [Assemble Test Files] *****************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: + ~~~~~~~~~~~~~~~
fatal: [frcva4316.emea.bpo.accenture.com]: FAILED! => {"changed": false, "failed": true, "msg": "The term '/usr/bin/python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."}

```

-vvv shows:

Try
{
**/usr/bin/python** 'C:\Users\S-TEST-AUTOMATION\AppData\Local\Temp\ansible-tmp-1485443500.96-46488175570275\assemble.ps1'
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}

**Comment by jhawkesworth** [comment]
I am surprised this is in the list for windows modules.

As a workaround you could run the assemble step delegated to localhost and then use win_copy to push the assembled file out to the managed windows nodes.

needs_contributor

**Comment by bcoca** [comment]
you might want to try `remote_src: no`

**Comment by tonyskidmore** [comment]
Thanks both for your inputs.  I got around what I was trying to do just by changing my process and assembling things on the control host rather than the remote Windows host using `delegate_to: localhost`.  I think that http://docs.ansible.com/ansible/intro_windows.html is a little misleading in terms of "**the following core modules work with Windows**"?

**Comment by jhawkesworth** [comment]
@tonyskidmore - I've created a PR https://github.com/ansible/ansible/pull/21859 which I hope will update the docs to explain what you have discovered.

**Comment by tonyskidmore** [comment]
@jhawkesworth - thanks that looks good.  Hopefully just saves anyone else going down the same investigations in the future.
