### ISSUE TITLE
No secondary Blocks run in Role playbook in Ansible 2.2.1.0

### ISSUE THREAD

**Issue by srkiNZ84** [ansible/ansible#20736]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Blocks (https://docs.ansible.com/ansible/playbooks_blocks.html)

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When running a Role with multiple "blocks" only the first block is executed.

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  gather_facts: False
  roles:
    - { name: blockrole }
```

Role "tasks/main.yml" definition:

Command to run:

ansible-playbook -i hosts block_test.yml

```yaml
- name: Set dummy variable
  set_fact:
    foo: "bar"

- block:
  - name: First block
    connection: local
    debug: msg="First block"
    when: "'{{ foo }}' == 'baz'"
    #command: /usr/bin/false
    #ignore_errors: true

  always:
    - name: First block always statment
      debug: msg="Always do this in the first block"

    - name: Falsify this crap
      command: /usr/bin/false
      ignore_errors: true

    - name: Skip One
      debug: msg="Skip one"
      ignore_errors: true
      when: "'{{ foo }}' == 'baz'"

    - name: Skip Two
      debug: msg="Skip two"
      when: "'{{ foo }}' == 'baz'"

- block:
  - name: Second block
    connection: local
    debug: msg="Second block"

  always:
    - name: Second block always statement
      debug: msg="Always do this in the second block"
```

##### EXPECTED RESULTS
Expected tasks in both of the "block" definitions to be executed.

##### ACTUAL RESULTS
Only the tasks in the first "block" definition were executed.

```console
$ ansible-playbook -i hosts block_test.yml
 ____________
< PLAY [all] >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 _______________________________________
< TASK [blockrole : Set dummy variable] >
 ---------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost]
 ________________________________
< TASK [blockrole : First block] >
 --------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

skipping: [localhost]
 ________________________________________________
< TASK [blockrole : First block always statment] >
 ------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost] => {
    "msg": "Always do this in the first block"
}
 ______________________________________
< TASK [blockrole : Falsify this crap] >
 --------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/usr/bin/false"], "delta": "0:00:00.004654", "end": "2017-01-27 14:15:33.036076", "failed": true, "rc": 1, "start": "2017-01-27 14:15:33.031422", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring
 _____________________________
< TASK [blockrole : Skip One] >
 -----------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

skipping: [localhost]
 _____________________________
< TASK [blockrole : Skip Two] >
 -----------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

skipping: [localhost]
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

localhost                  : ok=3    changed=1    unreachable=0    failed=0
```

**Comment by yabhinav** [comment]
+1 I am facing the same issue!!  4 block codes that do certain validations.

1. Block 1 doens't have rescue or always catch 
2. Block2 has always cause
3. Block3 has rescue catch
4. Block 4 has rescue catch

Both Block 1 and BLock2 gets executed since there is  catch in Block1
Block3 is ignored and not pickeup by anislbe until Block2 is removed
Block4 is ignored and not pickeup by anislbe until Block3 is removed

Temperoray Solution :
Move the block tasks to individual task files and use include to include them into roles.

The issue happens only when there are Multiple always/rescue catch keywords in a single yaml file because the task exits the yaml file once it enters the always or rescue catch ... much like a **return**  in a programming langugae (if you assume a yaml file is a single method )

**Comment by zumipin** [comment]
I am experiencing something similar. I have 4 blocks in my playbook, but execution stops after the block that contains the "always" statement. If I put that block first in the site.yml file, no other blocks will execute. Any block that comes before the block that contains "always" will execute properly.

For now I am just working around the issue by using the blocker-block last.

**Comment by yabhinav** [comment]
So even after separating the plays into various  small tasks files and include in the role, After a task is failed the play continues but at the end of the playbook the failed count will not be zero.


	The command "testrun=$(mktemp)" exited with 0.
	457.84s$ docker exec "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/${playbook} | tee -a ${testrun}
	PLAY [all] *********************************************************************
	TASK [setup] *******************************************************************
	ok: [localhost]
	TASK [role_under_test : Gather OS Specific Variables] **************************
	ok: [localhost] => (item=/etc/ansible/roles/role_under_test/vars/../vars/RedHat.yml)
	TASK [role_under_test : Install IPA Server Packages] ***************************
	changed: [localhost] => (item=[u'ipa-server', u'bind', u'bind-dyndb-ldap', u'ipa-python', u'sssd-ldap', u'expect', u'389-ds-base'])
	TASK [role_under_test : stat] **************************************************
	ok: [localhost]
	TASK [role_under_test : Check if mod_ssl configured to port 443 and change to 10443(Conflict with mod_nss)] ***
	skipping: [localhost] => (item={u'value': u' 10443', u'key': u'Listen'}) 
	skipping: [localhost] => (item={u'value': u'10443>', u'key': u'<VirtualHost _default_:'}) 
	TASK [role_under_test : Restart httpd] *****************************************
	skipping: [localhost]
	TASK [role_under_test : Wait for 443 mod_nss to be available and free] *********
	skipping: [localhost]
	TASK [role_under_test : Wait for 10443 mod_ssl to be open] *********************
	skipping: [localhost]
	TASK [role_under_test : Run the IPA Server installer] **************************
	changed: [localhost]
	TASK [role_under_test : Set IPA Server Install and Configuring Done] ***********
	changed: [localhost]
	TASK [role_under_test : Check if Directory Service is running] *****************
	ok: [localhost]
	TASK [role_under_test : Wait for IPA HTTP/LDAP/Kerberos Ports] *****************
	ok: [localhost] => (item=80)
	ok: [localhost] => (item=443)
	ok: [localhost] => (item=389)
	ok: [localhost] => (item=636)
	ok: [localhost] => (item=88)
	ok: [localhost] => (item=464)
	TASK [role_under_test : Check for Valid Kerberos TGT Cache] ********************
	fatal: [localhost]: FAILED! => {"changed": false, "cmd": "klist -s", "delta": "0:00:00.035482", "end": "2017-02-14 06:18:13.079950", "failed": true, "rc": 1, "start": "2017-02-14 06:18:13.044468", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
	TASK [role_under_test : Kinit IPA Admin] ***************************************
	changed: [localhost]
	TASK [role_under_test : Generate IPA Server keytab] ****************************
	changed: [localhost] => (item=ipa-getkeytab -s testlab.example.com -p HTTP/testlab.example.com@TESTLAB -k ipa.keytab.new)
	changed: [localhost] => (item=cp ipa.keytab ipa.keytab.orig )
	changed: [localhost] => (item=mv ipa.keytab.new ipa.keytab)
	changed: [localhost] => (item=chown apache:apache ipa.keytab*)
	TASK [role_under_test : Restart httpd] *****************************************
	changed: [localhost]
	PLAY RECAP *********************************************************************
	localhost                  : ok=11   changed=6    unreachable=0    failed=1   


Notice the step where Klist -s fails , we do a kinit  and create the TGT. Ideally till 2.2.0 version of ansible it was fine. In 2.2.1 we fixed the multi block statements by splitting the block tasks into individual files

**Comment by jbscare** [comment]
We ran into this in a role where there's some tasks, a block with an always task (it creates a lock file and does some stuff in a work-in-progress directory, then copies the result into place, and the always task cleans up the lock file so that we don't leave that lying around even if something goes wrong), and then some more tasks (that aren't part of the block), and the post-block tasks don't run at all. I couldn't figure out at all what was happening!

**Comment by yabhinav** [comment]
@jbscare  just split the block task into another  tasks/blockA.yml  and in tasks/main.yml , 

 `- include: blockA.yml `

**Comment by jbscare** [comment]
Sure, this isn't hard to work around. I just wanted to chime in that I'd seen this bug too, an in a situation where we only have one block.

**Comment by yabhinav** [comment]
the real bug is counting  the failure as failed=1 when actually there is a rescue: task running

Ideally you report don't want to reflect it as a failure because

1. Your are checking if a service is up
2. You are rescuing by stating the service

**Comment by mkrizek** [comment]
Fixed in the recent versions of Ansible.
