### ISSUE TITLE
Support Jinja 2.9

### ISSUE THREAD

**Issue by kamikaze** [ansible/ansible#20735]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Unable to install Jinja 2.9 on my system because Ansible is blocking it by using 2.8

**Comment by rcarrillocruz** [comment]
Are you familiar with Python virtualenvs?

http://docs.python-guide.org/en/latest/dev/virtualenvs/

You could create a venv to install Ansible, so it the Jinja version required by Ansible does not interfere with your system-wide version.

e.g.
virtualenv ansible
source ansible/bin/activate
pip install ansible

**Comment by kamikaze** [comment]
Sure I could create virtualenv or remove anything from my system that requires modern Jinja ) but all this is a workaround. I vote to not turn Ansible into yet another ancient software (like RedHat likes to do)

**Comment by sivel** [comment]
This has already been resolved in https://github.com/ansible/ansible/commit/f649a87a195bfb7772ae5e35dd81431a79ee095f and will be included in the next release
