### ISSUE TITLE
Request native variables refelecting the content of ansible.cfg and cli flags

### ISSUE THREAD

**Issue by gzm55** [ansible/ansible#20744]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Need native top-level variables (could be read-only) to represent the active config key and value in this invocation. They are convenient for debugging and developing some roles. 

##### STEPS TO REPRODUCE
cat >ansible.cfg <<END
remote_port=2222
private_key_file=/path/to/fileA
END
export DISPLAY_SKIPPED_HOSTS=1
ansible --private-key=/path/to/fileB localhost -m debug -a 'msg="{{vars}}"'

##### EXPECTED RESULTS
```
...
ansible_version: {...}
ansible_config: {
  active_config: /pwd/ansible.cfg
  active_config_reason: "current path"
  defaults: {
    remote_port: 2222
    remote_port_reason: "active_config"
    private_key_file: /path/to/fileB
    private_key_file_reason: "cli"
    display_skipped_hosts: True
    display_skipped_hosts_reason: "env"
  }
  privilege_escalation: {
    become_method: sudo
    become_method_reason: "default"
   ...
  }
  ssh_connection: {...}
  ...
}
...
```

##### ACTUAL RESULTS
N/A

**Comment by bcoca** [comment]
that is part of what https://github.com/ansible/proposals/issues/35 does, not as variables, but ability to dump and show where the config options came from.

**Comment by gzm55** [comment]
@bcoca will ansible/proposals#35 be released in the ansible v2.3?

**Comment by bcoca** [comment]
no

**Comment by bcoca** [comment]
closing as ansible-config is now part of 2.4
