### ISSUE TITLE
function get_vgs_facts deliver no output when a volumegroup is offline

### ISSUE THREAD

**Issue by molekuul** [ansible/ansible#20752]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

module: facts.py

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel b598575213) last updated 2017/01/13 08:15:07 (GMT +200)
config file = /etc/ansible/ansible.cfg
configured module search path = Default w/o overrides
```

##### CONFIGURATION
default setting

##### OS / ENVIRONMENT
Ansible is running at RHEL 7.1 and it is managing AIX 7.1

##### SUMMARY
The function get_vgs_facts will not deliver any output when a volumegroup at the managed system is ofline. The command lsvg -p <vgname> can only run at online volume groups.

##### STEPS TO REPRODUCE

place a volumegroup offline and run 
```
ansible all -i inventory -m setup 
```
where the managed node with the offline vg is in the inventory file

This can be fixed by discovering only the online volume groups

line:
```
 cmd = "%s | %s %s -p" % (lsvg_path ,xargs_path,lsvg_path)
```
must be replaced with:
```
 cmd = "%s -o| %s %s -p" % (lsvg_path ,xargs_path,lsvg_path)
```

**Comment by nrwahl2** [comment]
Thanks, @molekuul . Submitted PR #28701
