### ISSUE TITLE
lookup plugins don't work when invoked via Ansible API

### ISSUE THREAD

**Issue by sb98052** [ansible/ansible#20766]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- Ansible API

##### ANSIBLE VERSION
ansible 2.2.0.0

##### OS / ENVIRONMENT
ubuntu 14.04

##### SUMMARY
When using the Ansible API, and running a playbook via playbook_executor.PlaybookExecutor, lookup('file', '/path/to'file') does not work. Instead of setting the value of a variable, it mangles its container. e.g.

vars:
     my_var: 
         - field: " {{ lookup('file','/path/to/myfile') }}"

Instead of setting my_var to {'field':<content of myfile>} it sets it to {'fn': 'myfile'}

##### STEPS TO REPRODUCE

self.pbex = playbook_executor.PlaybookExecutor(
            playbooks=[playbook],
            inventory=self.inventory,
            variable_manager=self.variable_manager,
            loader=self.loader,
            options=self.options,
            passwords={})

This is set up with standard options. Nothing special.

##### EXPECTED RESULTS
For the Ansible playbook to run, and variables to acquire the contents of the file when lookup('file','/path/to/file') is used

##### ACTUAL RESULTS

Notice how item has a field called "fn". It is set up like this:
- endpoint: onos/v1/network/configuration/
         body: "{{ lookup('file', '/opt/xos/synchronizers/onos/steps/../files/4/vRouter_ONOS_app/onos_v1_network_confi
guration_') }}"

```
{'msg': u'All items completed', 'changed': False, 'results': [{'_ansible_no_log': False, '_ansible_item_result': True, 'item': {'endpoint': u'onos/v1/network/configuration/', 'fn': u'onos_v1_network_configuration_'}, 'invocation': {'module_name': u'debug', 'module_args': {u'msg': {'endpoint': u'onos/v1/network/configuration/', 'fn': u'onos_v1_network_configuration_'}}}, 'msg': {'endpoint': u'onos/v1/network/configuration/', 'fn': u'onos_v1_network_configuration_'}, '_ansible_verbose_always': True}]}
(Pdb) 
```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a developer question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

I'm pretty sure the API works as it is what the command line tools use, this seems to be an issue with how you are using it. 

   * IRC: #ansible-devel on irc.freenode.net   
   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
