### ISSUE TITLE
win_ping and setup fail using ansible 2.2.1 from Yosemite on Macbook 

### ISSUE THREAD

**Issue by misterT1958** [ansible/ansible#20767]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible connection to Windows, win_ping, setup

##### ANSIBLE VERSION
```ansible --version
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
none

##### OS / ENVIRONMENT
running ansible from Yosemite 10.10.5
target machine is running Windows Server 2012 r2

##### SUMMARY
unable to establish connection to Windows boxes (linux and mac targets work as expected)

##### STEPS TO REPRODUCE
```
tw2@warroom3:~/Ansible/group_vars> ansible harold -vvvvv -i hosts -m setup -cssh
No config file found; using defaults
Loading callback plugin minimal of type stdout, v2.0 from /Library/Python/2.7/site-packages/ansible/plugins/callback/__init__.pyc
Using module file /Library/Python/2.7/site-packages/ansible/modules/core/system/setup.py
<harold> ESTABLISH SSH CONNECTION FOR USER: None
<harold> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<harold> SSH: ansible_password/ansible_ssh_pass not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<harold> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<harold> SSH: PlayContext set ssh_common_args: ()
<harold> SSH: PlayContext set ssh_extra_args: ()
<harold> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/Users/tw2/.ansible/cp/ansible-ssh-%h-%p-%r)
<harold> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/tw2/.ansible/cp/ansible-ssh-%h-%p-%r harold '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1485538653.21-151676028800575 `" && echo ansible-tmp-1485538653.21-151676028800575="` echo ~/.ansible/tmp/ansible-tmp-1485538653.21-151676028800575 `" ) && sleep 0'"'"''
harold | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011\ndebug1: Reading configuration data /Users/tw2/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh_config\r\ndebug1: /etc/ssh_config line 20: Applying options for *\r\ndebug1: /etc/ssh_config line 102: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/Users/tw2/.ansible/cp/ansible-ssh-harold-22-tw2\" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\ndebug1: Connecting to harold [160.91.248.71] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 160.91.248.71 port 22: Operation timed out\r\nssh: connect to host harold port 22: Operation timed out\r\n",
    "unreachable": true
}
```

windows.yaml file:
```
---
# it is suggested that these be encrypted with ansible-vault:
# ansible-vault edit group_vars/windows.yml

ansible_user: tw2
ansible_password: XXXXXXXX
ansible_port: 5986
ansible_connection: winrm
# The following is necessary for Python 2.7.9+ (or any older Python that has backported SSLContext, eg, Python 2.7.5 on RHEL7) when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore
####
ansible_winrm_scheme: https
ansible_winrm_transport: plaintext
```

Note: I have also tried without scheme and transport parameters not declared, and with windows.yaml file in /etc/ansible/group_vars, and with ansible_port=22; nothing worked

##### EXPECTED RESULTS
expected setup return values or successful ping

##### ACTUAL RESULTS
here's the results of the win_ping
```
No config file found; using defaults
Loading callback plugin minimal of type stdout, v2.0 from /Library/Python/2.7/site-packages/ansible/plugins/callback/__init__.pyc
Using module file /Library/Python/2.7/site-packages/ansible/modules/core/windows/win_ping.ps1
<harold> ESTABLISH SSH CONNECTION FOR USER: None
<harold> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<harold> SSH: ansible_password/ansible_ssh_pass not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<harold> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<harold> SSH: PlayContext set ssh_common_args: ()
<harold> SSH: PlayContext set ssh_extra_args: ()
<harold> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/Users/tw2/.ansible/cp/ansible-ssh-%h-%p-%r)
<harold> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/tw2/.ansible/cp/ansible-ssh-%h-%p-%r harold '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1485539588.87-116427629078605 `" && echo ansible-tmp-1485539588.87-116427629078605="` echo ~/.ansible/tmp/ansible-tmp-1485539588.87-116427629078605 `" ) && sleep 0'"'"''
harold | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011\ndebug1: Reading configuration data /Users/tw2/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh_config\r\ndebug1: /etc/ssh_config line 20: Applying options for *\r\ndebug1: /etc/ssh_config line 102: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/Users/tw2/.ansible/cp/ansible-ssh-harold-22-tw2\" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\ndebug1: Connecting to harold [160.91.248.71] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 160.91.248.71 port 22: Operation timed out\r\nssh: connect to host harold port 22: Operation timed out\r\n",
    "unreachable": true
}
```

```ansible harold -vvvvv -i hosts -m win_ping
  ansible harold -vvvvv -i hosts -m setup
  ansible harold -vvvvv -i hosts -m setup -cssh
```

**Comment by misterT1958** [comment]
I have found that if i declare ansible_port and ansible_ssh_user and ansible_password in my local hosts file I get closer:

tw2@warroom3:~/Ansible/group_vars> ansible harold -vvvvv -i hosts -m setup -cssh
No config file found; using defaults
Loading callback plugin minimal of type stdout, v2.0 from /Library/Python/2.7/site-packages/ansible/plugins/callback/__init__.pyc
Using module file /Library/Python/2.7/site-packages/ansible/modules/core/system/setup.py
<harold> ESTABLISH SSH CONNECTION FOR USER: tw2
harold | FAILED! => {
    "failed": true,
    "msg": "to use the 'ssh' connection type with passwords, you must install the sshpass program"
}

**Comment by s-hertel** [comment]
Have you used ConfigureRemotingForAnsible.ps1? https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1

**Comment by misterT1958** [comment]
yes, almost first thing I did.  BTW, the documentation should be updated as I found that you had to have Admin privileges in order to execute that script.  That was how I started, and I have confirmed that WinRm is running, still not able to connect.

**Comment by jhawkesworth** [comment]
Hello,

Also please place your group_vars folder relative to the location of your ansible inventory file.  So if your ansible inventory is in /etc/ansible/hosts, then put group_vars in /etc/ansible/group_vars - it looks like you have hosts and windows.yml both inside group_vars from the output shown above.

Please remove the -cssh from your command line - this instructs ansible to connect via ssh but that's not (yet) possible with windows boxes, you have to connect via winrm.  You could try -cwinrm but you'll still need the other connection parameters that are in your windows.yml.  Also the ansible_port will need to be 5986 (or 5985) not 22 as winrm listens on these ports, not 22.

Oh and please ensure your windows host 'harold' is in a group called 'windows' in your inventory, otherwise ansible won't know to apply the group-specific variables to your windows machines.

i.e. Something like this in your /etc/ansible/hosts
```

# hosts belonging to windows group
[windows]
harold
#
```

I think you are getting close, a bit more tinkering and you'll be up and running.

Hope this helps,

Jon

**Comment by jhawkesworth** [comment]
Please let us know how you get on

**Comment by misterT1958** [comment]
Jon, thanks for the response; all the files are located as you suggest; i replaced the -cssh with -cwinrm; here's the result
tw2@warroom3:~/Ansible> ansible harold -vvvvv -m setup -cwinrm -u tw2
No config file found; using defaults
Loading callback plugin minimal of type stdout, v2.0 from /Library/Python/2.7/site-packages/ansible/plugins/callback/__init__.pyc
Using module file /Library/Python/2.7/site-packages/ansible/modules/core/windows/setup.ps1
<harold> ESTABLISH WINRM CONNECTION FOR USER: tw2 on PORT 5986 TO harold
<harold> WINRM CONNECT: transport=ssl endpoint=https://harold:5986/wsman
<harold> WINRM CONNECTION ERROR: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ansible/plugins/connection/winrm.py", line 154, in _winrm_connect
    self.shell_id = protocol.open_shell(codepage=65001)  # UTF-8
  File "/Users/tw2/Library/Python/2.7/lib/python/site-packages/winrm/protocol.py", line 132, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/Users/tw2/Library/Python/2.7/lib/python/site-packages/winrm/protocol.py", line 207, in send_message
    return self.transport.send_message(message)
  File "/Users/tw2/Library/Python/2.7/lib/python/site-packages/winrm/transport.py", line 184, in send_message
    response = self.session.send(prepared_request, timeout=self.read_timeout_sec)
  File "/Users/tw2/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Users/tw2/Library/Python/2.7/lib/python/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

harold | UNREACHABLE! => {
    "changed": false,
    "msg": "ssl: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)",
    "unreachable": true
}

and here's an excerpt from my hosts file:
[Windows]
harold

**Comment by misterT1958** [comment]
Jon,  looking back at issue 14710 i wanted to let you know I did NOT set up Kerberos; i did set up a local account on the server and tried to connect to the local account, that told me 

WINRM CONNECTION ERROR: the specified credentials were rejected by the server

**Comment by jhawkesworth** [comment]
Ok, you are almost there.

Please check that you still have 

`ansible_winrm_server_cert_validation: ignore`

in your windows group vars

Also I think the group name in inventory must match exactly the file name (including case) of your group_vars file so if your group is called
`
[Windows]`

then your corresponding group vars would need to be in `/etc/ansible/group_vars/Windows.yml`

(Upper case W, just to be clear).  Speculating a bit here as I've only ever used lower case names for my inventory groups, but I would expect it to be case sensitive.

'the specified credentials were rejected by the server' usually means wrong password, but I guess it could be that no password is being supplied if your group vars aren't being picked up (which sounds possibly if you have to set -cwinrm - shouldn't be necessary if the group_vars are being used).

Its possible you have a password containing punctuation which is being (mis)interpreted by python or jinja2 or powershell even so I suggest you use a simple password until you have got the connection working.

Hope this helps,

Jon

**Comment by misterT1958** [comment]
here's my windows.yml file:
tw2@warroom3:~/Ansible/group_vars> more windows.yml
---
# it is suggested that these be encrypted with ansible-vault:
# ansible-vault edit group_vars/windows.yml

ansible_user: tw2
ansible_password: <redacted>
ansible_port: 5986
ansible_connection: winrm
# The following is necessary for Python 2.7.9+ (or any older Python that has backported SSLContext, eg, Python 2.7.5 on RHEL7) when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore
####
ansible_winrm_scheme: https
ansible_winrm_transport: plaintext
...

and from earlier posts we can see my hosts file contains lower-case w in [windows];  password consists entirely of alphanumerics, i.e. no punctuation or other symbols

and I tried the setup module both with and without the winrm module, didn't seem to make a difference....

**Comment by misterT1958** [comment]
if this sheds some light, I have another  target server that is setup identically to harold (as far as I know).  I have not run the powershell script on this server, here's what it reports

tw2@warroom3:~/Ansible> ansible maude -vvvvv -m setup
No config file found; using defaults
Loading callback plugin minimal of type stdout, v2.0 from /Library/Python/2.7/site-packages/ansible/plugins/callback/__init__.pyc
Using module file /Library/Python/2.7/site-packages/ansible/modules/core/windows/setup.ps1
<maude> ESTABLISH WINRM CONNECTION FOR USER: tw2 on PORT 5986 TO maude
<maude> WINRM CONNECT: transport=ssl endpoint=https://maude:5986/wsman


<maude> WINRM CONNECTION ERROR: HTTPSConnectionPool(host='maude', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10983a750>, 'Connection to maude timed out. (connect timeout=30)'))
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ansible/plugins/connection/winrm.py", line 154, in _winrm_connect
    self.shell_id = protocol.open_shell(codepage=65001)  # UTF-8
  File "/Users/tw2/Library/Python/2.7/lib/python/site-packages/winrm/protocol.py", line 132, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/Users/tw2/Library/Python/2.7/lib/python/site-packages/winrm/protocol.py", line 207, in send_message
    return self.transport.send_message(message)
  File "/Users/tw2/Library/Python/2.7/lib/python/site-packages/winrm/transport.py", line 184, in send_message
    response = self.session.send(prepared_request, timeout=self.read_timeout_sec)
  File "/Users/tw2/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Users/tw2/Library/Python/2.7/lib/python/site-packages/requests/adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPSConnectionPool(host='maude', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10983a750>, 'Connection to maude timed out. (connect timeout=30)'))

maude | UNREACHABLE! => {
    "changed": false,
    "msg": "ssl: HTTPSConnectionPool(host='maude', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10983a750>, 'Connection to maude timed out. (connect timeout=30)'))",
    "unreachable": true
}

**Comment by misterT1958** [comment]
and once i did run the configure powershell script it reduced the number of error messages from 6 to 4 but still failed:
`tw2@warroom3:~/Ansible> ansible maude -vvvvv -m setup
No config file found; using defaults
Loading callback plugin minimal of type stdout, v2.0 from /Library/Python/2.7/site-packages/ansible/plugins/callback/__init__.pyc
Using module file /Library/Python/2.7/site-packages/ansible/modules/core/windows/setup.ps1
<maude> ESTABLISH WINRM CONNECTION FOR USER: tw2 on PORT 5986 TO maude
<maude> WINRM CONNECT: transport=ssl endpoint=https://maude:5986/wsman
<maude> WINRM CONNECTION ERROR: the specified credentials were rejected by the server
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ansible/plugins/connection/winrm.py", line 154, in _winrm_connect
    self.shell_id = protocol.open_shell(codepage=65001)  # UTF-8
  File "/Users/tw2/Library/Python/2.7/lib/python/site-packages/winrm/protocol.py", line 132, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/Users/tw2/Library/Python/2.7/lib/python/site-packages/winrm/protocol.py", line 207, in send_message
    return self.transport.send_message(message)
  File "/Users/tw2/Library/Python/2.7/lib/python/site-packages/winrm/transport.py", line 190, in send_message
    raise InvalidCredentialsError("the specified credentials were rejected by the server")
InvalidCredentialsError: the specified credentials were rejected by the server

maude | UNREACHABLE! => {
    "changed": false,
    "msg": "ssl: the specified credentials were rejected by the server",
    "unreachable": true
}`

**Comment by jhawkesworth** [comment]
Well it looks like you are connecting to maude via winrm but it doesn't like whatever password is being presented for the tw2 user

Can you remote destop to maude as MAUDE\tw2 and connect using the same password?

Note that if tw2 is a domain user then you will need to set up kerberos - if there is no domain in the connection settings, it will assume that the supplied username is local to the windows target.

**Comment by misterT1958** [comment]
Yes, I can remote desktop in with that username/pw.  It is a domain user, I created a local user and tried after making appropriate changes, that did not work either.....I am installing kerberos on Maude now

**Comment by jhawkesworth** [comment]
For info you need the kerberos stuff on your ansible controller - windows should have everything it needs already.

**Comment by misterT1958** [comment]
Jon

thanks for the heads up.  I have py27-pykerberos installed on my controller, and I edited the /etc/krb5.conf file.  All the windows boxes report:

harold | UNREACHABLE! => {
    "changed": false,
    "msg": "kerberos: the python kerberos library is not installed",
    "unreachable": true
}

which was why I thought I needed to install kerberos on the targets.  Klist responds reasonably on the controller, not really sure where to proceed from here.  Suggestions?

**Comment by misterT1958** [comment]
in case you were wondering, on the controller:

tw2@warroom3:~/Ansible> port installed | grep kerb
  kerberos5 @1.14.3_0 (active)
  py27-pykerberos @1.1-10616_0 (active)

**Comment by misterT1958** [comment]
Jon,
I can ping from the ansible controller (mac) to the windows boxes successfully, but from the windows box to the controller the ping fails.  Seems like that would have to succeed for the ansible connection to work, yes?

**Comment by jhawkesworth** [comment]
ping from windows box back to the ansible controller is not a problem I have encountered before. 

You certainly need DNS to be working probably for both forward and reverse lookups - kerberos depends totally on DNS - you are already using hostnames rather than IP addresses by the looks of things, so that's probably not your issue.

Well worth checking firewall configurations on your controller, the windows targets (and any network business in between of course).

I tend to install all ansible-related stuff from pip myself and I don't have a mac so I suggest asking on ansible-project google group to find out how others are installing the windows dependencies.
If I do a 'pip list' I can see I have the python pip 'kerberos' version 1.2.5 installed.  I don't know if pip is an option for you on a mac.

I think it might actually be worth moving this discussion to ansible-project (which probably has many more eyes on it than the github issue tracker, which is mostly just used by ansible contributors and the core team).

**Comment by misterT1958** [comment]
Jon, tried a different route and was successful!  However, it changes the bug report a bit.  I moved my ansible controller from my mac to a linux box running RHEL 6.8.  After installing pywinrm (everything else was there) and making sure the username was @CAPITALIZED it all works.  Yea.  Now going back to see if I can get my mac ansible controller to work.

**Comment by misterT1958** [comment]
Jon, got windows connections from Mac (running Yosemite) to all 3 servers running Windows Server 2012 R2.  One big lesson was the ConfigureRemotingForAnsible script must be run as Administrator.

**Comment by misterT1958** [comment]
Jon, got windows connections from Mac (running Yosemite) to all 3 servers running Windows Server 2012 R2.  One big lesson was the ConfigureRemotingForAnsible script must be run as Administrator.  I have not been able to get Ansible windows connection running to my 3 windows boxes running Windows7; I will open that up in a separate ticket.  THANK YOU for all your help!

**Comment by jhawkesworth** [comment]
Glad its  all working.  I think latest version of ConfigureRemoting... throws up some kind of warning if you aren't running as Administrator now, so might be worth checking you are picking up the latest version.
