### ISSUE TITLE
Windows: Use -WhatIf with $check_mode

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#20781]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

Windows modules

##### ANSIBLE VERSION
v2.3

##### SUMMARY

So rather than doing:
```powershell
if (-not $check_mode) {
    try {
        do_action
    } catch {
        fail-json "error"
    }
}
```
We could be doing
```powershell
try {
    if ($check_mode) {
        do_action -WhatIf
    } else {
        do_action
    }
} catch {
    fail-json "error"
}
```
Or even do:
```powershell
try {
    do_action -WhatIf:$check_mode
} catch {
    fail-json "error"
}
```

**Comment by trondhindenes** [comment]
could you elaborate on your idea, @dagwieers ?

**Comment by dagwieers** [comment]
@trondhindenes Not sure what to add to this. My assumption is that using -WhatIf uses more real codepaths than simply skipping the action itself. Making it a more real $check_mode than what we are used to. But we have to test this case by case.

**Comment by jhawkesworth** [comment]
Feels like it would be hard to turn this into a pattern, given it depends on each Cmdlet's support , but mentioning it in windows modules dev guide and having an example to point at would be a good idea.

I don't use -WhatIf much so not sure if converting its output to json could be done in a standard way or not .

**Comment by dagwieers** [comment]
@jhawkesworth I am not that much interested in the output per se, but what I am interested in are the possible failure-paths from the Cmdlet that we may trigger, without actually doing anything.

I am wary about having different output than during normal execution, because we actually don't want that :-) Might be confusing to our users during testing.

**Comment by dagwieers** [comment]
BTW Various Windows plugins have been rewritten with check-mode support using -WhatIf now.
#20405 #21385 #21503 #21623 #21628
Please review !

**Comment by dagwieers** [comment]
I am going to close this. We are implementing this now for some modules.
