### ISSUE TITLE
Glossary of Ansible keywords

### ISSUE THREAD

**Issue by djatlantic** [ansible/ansible#2080]
Hi all,

I think that we need to have a glossary of all the keywords that Ansible understand because currently I have to read and re-read the playbooks and advance playbooks to find new features or keywords every few weeks.

Thank you.

**Comment by mpdehaan** [comment]
+1000.

Easy to make a glossary page with docs references in Sphinx and we should
do this!

**Comment by dhozac** [comment]
Fixed by ae2d7eb7af45df9d7f4028105c874d23440fd6aa
