### ISSUE TITLE
 Could not find any downloads that satisfy the requirement rchimaku

### ISSUE THREAD

**Issue by krishnachaitanya511** [ansible/ansible#20815]
I am installing the Ansible in the Windows-Based Ubuntu system. While installing I am facing issue below issue. Please help me with the same.

##### Installation Issue
 **- Bug Report**
pip install ansible --user rchimaku
Downloading/unpacking ansible
  Downloading ansible-2.2.1.0.tar.gz (2.5MB): 2.5MB downloaded
  Running setup.py (path:/tmp/pip_build_rchimaku/ansible/setup.py) egg_info for package ansible

    no previously-included directories found matching 'v2'
    no previously-included directories found matching 'docsite'
    no previously-included directories found matching 'ticket_stubs'
    no previously-included directories found matching 'packaging'
    no previously-included directories found matching 'test'
    no previously-included directories found matching 'hacking'
    warning: no previously-included files found matching 'lib/ansible/modules/core/.git*'
    warning: no previously-included files found matching 'lib/ansible/modules/extras/.git*'
    no previously-included directories found matching 'lib/ansible/modules/core/.git'
    no previously-included directories found matching 'lib/ansible/modules/extras/.git'
Downloading/unpacking rchimaku
  Could not find any downloads that satisfy the requirement rchimaku
Cleaning up...
No distributions at all found for rchimaku
Storing debug log for failure in /home/rchimaku/.pip/pip.log

##### COMPONENT NAME
ansible installation

##### ANSIBLE VERSION
ansible-2.2.1.0.tar.gz
```

```

##### EXPECTED RESULTS
It should be installed.

##### ACTUAL RESULTS
Downloading/unpacking rchimaku
  Could not find any downloads that satisfy the requirement rchimaku
Cleaning up...
No distributions at all found for rchimaku
Storing debug log for failure in /home/rchimaku/.pip/pip.log
```

```

**Comment by jctanner** [comment]
@krishnachaitanya511 You do not need to specify a username for "pip install --user"...

https://pip.readthedocs.io/en/latest/user_guide/#user-installs

The full command should be "pip install --user ansible"

**Comment by krishnachaitanya511** [comment]
Hi @jctanner, If I use the way you mentioned: "pip install --user ansible" only ansible user would get the privileges. Please correct me If I am wrong!

**Comment by krishnachaitanya511** [comment]
It worked. Thanks for the update
