### ISSUE TITLE
group_vars loaded from /etc/ansible/hosts/group_vars

### ISSUE THREAD

**Issue by vad** [ansible/ansible#20817]
##### ISSUE TYPE

 - Bug Report
 - Documentation Report

##### COMPONENT NAME
vars_plugin ?

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

In my ansible.cfg:

```
inventory      = /etc/ansible/hosts
```

##### OS / ENVIRONMENT

```
$ uname -a
Linux ip-172-31-45-93 3.13.0-46-generic #79-Ubuntu SMP Tue Mar 10 20:06:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
##### SUMMARY

group_vars are not read from /etc/ansible/group_vars as the documentation affirms but from `/etc/ansible/hosts/group_vars` (I have multiple inventories).

##### STEPS TO REPRODUCE

This is an excerpt of running ansible with strace:

```
lstat("/etc", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/etc/ansible", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/etc/ansible/hosts", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/etc/ansible/hosts/group_vars", 0x7fffc410dcc0) = -1 ENOENT (No such file or directory)
stat("/etc/ansible/hosts/group_vars", 0x7fffc410df60) = -1 ENOENT (No such file or directory)
lstat("/etc", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/etc/ansible", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/etc/ansible/hosts", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/etc/ansible/hosts/host_vars", 0x7fffc410dcc0) = -1 ENOENT (No such file or directory)
stat("/etc/ansible/hosts/host_vars", 0x7fffc410df60) = -1 ENOENT (No such file or directory)
```

##### EXPECTED RESULTS

```
$ ansible mycluster -m debug -a 'var=hello' 
172.31.31.31 | SUCCESS => {
    "cacca": "VARIABLE IS NOT DEFINED!"
}
```

##### ACTUAL RESULTS

```
ansible mycluster -m debug -a 'var=hello' 
172.31.31.31 | SUCCESS => {
    "cacca": "world!"
}
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The group/host_vars directories are read adjacent to the inventory **file,** if using a directory, the inventory files are contained within, the same goes for group/host_vars directory.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by vad** [comment]
It's ok for me, but I don't think it's mentioned in the documentation, is it? http://docs.ansible.com/ansible/intro_inventory.html

Thank you @bcoca!

**Comment by bcoca** [comment]
I'll look into adding better docs, I thought it was clearly implied in "Assuming the inventory file path is"
