### ISSUE TITLE
Daemon invoking script fails when run through ansible

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#2081]
Ideally I'd have more diagnostics than I do, and I can probably engage support to assist if I know what to ask. The user I'm trying to run the tasks as has very limited sudo privileges, hence running sudo from the action, rather than use sudo_user. 

Basically the following doesn't work (the command executes, the script runs, but then the process kicked off by the script immediately dies)

`action: command sudo -u tomcatuser /path/to/tomcat/start/script`

Using raw or shell modules doesn't make any appreciable difference. 

However, all of the following methods do work as expected. 
- on the server
  `sudo -u tomcatuser /path/to/tomcat/start/script`
  `python ./ansible/tmp/ansible-lots-of-numbers-here/command`
- local command line
  `ssh user@server sudo -u tomcatuser /path/to/tomcat/start/script`
- local ansible task
  `local_action: command ssh user@server sudo -u tomcatuser /path/to/tomcat/start/script`

While I appreciate this is an interaction between the start script and ansible, I'd be interested if anyone had any insight as to what the difference between running the task through ansible and running it remotely, and whether there are any other tests I can perform without needing to be able to run the command via strace or similar.

**Comment by mpdehaan** [comment]
App server scripts usually suck terribly at daemonizing properly.

This is probably the same here with how you are starting tomcat.

You really should use the service module when you can, but it sounds like you can't in this case.  

I would probably try to wrap the start script in another script that daemonized properly and execute that with ansible's 'script' module.

**Comment by junneyang** [comment]
ansible's 'script' module
how to daemonize a cmomand?

**Comment by willthames** [comment]
@junneyang, create a script that does the daemonizing and then execute that script using the `command` module.

Recommend that the script does `setsid` and `disown` - see #4800
