### ISSUE TITLE
How to configure the Windows-PowerShell based Linux system to communicate with the CentOS based VM using ansible?

### ISSUE THREAD

**Issue by krishnachaitanya511** [ansible/ansible#20851]
##### ISSUE TYPE
 - Feature Idea
1. I am using WINDOWS 10. I am using Linux-Ubuntu by using poweshell concept.
2. By using the same I have installed Ansible and tried connecting to the local host by using playbook.

![image](https://cloud.githubusercontent.com/assets/25428479/22461011/93a5980e-e7cd-11e6-9428-81aad2d0fb6a.png)

3. While trying to connect it to the CentOS based VM. It is failing to connect. 

![image](https://cloud.githubusercontent.com/assets/25428479/22461669/2f5257f4-e7d0-11e6-807f-be9513903e64.png)

4. The Remote system's SSH is up and running. 

![image](https://cloud.githubusercontent.com/assets/25428479/22461715/5a9c41e0-e7d0-11e6-970c-334caeb32842.png)

I am sure I have to add the certificate to the Ansible-Controller system(Windows Based Linux System in this case.). Could someone please let me know how to add the certificate and establish the communication between the Remote system[VM in my local] and my local?

##### COMPONENT NAME
PowerShell

##### ANSIBLE VERSION
ansible 2.2.1.0
```

```

##### CONFIGURATION
none

##### OS / ENVIRONMENT
Ansible Controller: Windows with powershell of Linux[Ubuntu]
Target System or Node: CentOS
##### SUMMARY
Unable to communicate the VMwith centOS

##### STEPS TO REPRODUCE
The connection should be established.

##### EXPECTED RESULTS
Failing

**Comment by jhawkesworth** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
