### ISSUE TITLE
Default poll value in async is 0 rather than 10 seconds

### ISSUE THREAD

**Issue by Harosgr** [ansible/ansible#20869]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
async

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### CONFIGURATION
forks          = 5
poll_interval  = 15

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I don't know if this is a documentation issue or a bug. 
The async documentation says "The default poll value is 10 seconds if you do not specify a value for poll" but that's untrue. If you don't set a poll value it behaves like value 0 is set, making the task a "fire and forget"

##### STEPS TO REPRODUCE

```yaml
- name: run command
  shell: "sleep 60"
  register: output
  async: 500
- debug: var=output
```

##### EXPECTED RESULTS
Wait until the task is finished before proceeding to the debug since the poll value should be 10.
```
    "output": {
        "ansible_job_id": "166257099787.11347", 
        "changed": true, 
        "cmd": "sleep 60", 
        "delta": "0:01:00.002783", 
        "end": "2017-01-31 17:43:51.234196", 
        "finished": 1, 
        "rc": 0, 
        "start": "2017-01-31 17:42:51.231413", 
        "stderr": "", 
        "stdout": "", 
        "stdout_lines": [], 
        "warnings": []
    }
```

##### ACTUAL RESULTS
Task is in "fire and forget" mode, directly executing the debug task.
```
    "output": {
        "ansible_job_id": "974103712334.11113", 
        "changed": false, 
        "finished": 0, 
        "results_file": ".ansible_async/974103712334.11113", 
        "started": 1
    }
```

**Comment by abadger** [comment]
This appears to have changed in v2.
* New value: https://github.com/ansible/ansible/commit/ce3ef7f4c16e47d5a0b5600e1c56c177b7c93f0d#diff-ac960c5e7aa7ed715ac443f64451bff6R82
* Old value: https://github.com/ansible/ansible/commit/ce3ef7f4c16e47d5a0b5600e1c56c177b7c93f0d#diff-ac960c5e7aa7ed715ac443f64451bff6L255

Asking others whether we should treat it as a documentation bug at this point.
