### ISSUE TITLE
ansible_ssh_extra_args is ignored when ansible_ssh_executable is set

### ISSUE THREAD

**Issue by gzm55** [ansible/ansible#20862]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ssh

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.2.1.0
  config file = /work/ansible-ssh-pubkey-login-role/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
running from Ubuntu.
no remoting OS

##### SUMMARY
when set ansible_ssh_executable in a task, the result params only contains ansible_ssh_common_args, but not ansible_ssh_extra_args.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  gather_facts: False
  tasks:
  - raw: exit
    vars:
    - ansible_ssh_executable: echo
    - ansible_ssh_common_args: AA
    - ansible_ssh_extra_args: BB
    register: test
  - debug: msg="{{test.stdout_lines}}"
```

```
$ cat inv
github.com

$ ansible-playbook -i inv pl.yml
```

##### EXPECTED RESULTS

PLAY [all] *********************************************************************

TASK [raw] *********************************************************************
changed: [github.com]

TASK [debug] *******************************************************************
ok: [github.com] => {
    "msg": [
        "-C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 **AA BB** -o ControlPath=/home/james/.ansible/cp/ansible-ssh-%h-%p-%r -tt github.com exit"
    ]
}

PLAY RECAP *********************************************************************
github.com                 : ok=2    changed=1    unreachable=0    failed=0 

##### ACTUAL RESULTS

PLAY [all] *********************************************************************

TASK [raw] *********************************************************************
changed: [github.com]

TASK [debug] *******************************************************************
ok: [github.com] => {
    "msg": [
        "-C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 **AA** -o ControlPath=/home/james/.ansible/cp/ansible-ssh-%h-%p-%r -tt github.com exit"
    ]
}

PLAY RECAP *********************************************************************
github.com                 : ok=2    changed=1    unreachable=0    failed=0

**Comment by abadger** [comment]
@gzm55 give https://github.com/ansible/ansible/pull/20950 a try to see if it fixes this issue for you.

**Comment by gzm55** [comment]
@adadger with #20950, the output is correct.

**Comment by abadger** [comment]
Excellent.  Thanks for testing!
