### ISSUE TITLE
Async task with a poll value >0 shouldn't need async_status to read output

### ISSUE THREAD

**Issue by Harosgr** [ansible/ansible#20877]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
async

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I understand that for a "fire and forget" async task with poll: 0, a reasonable way to get the output (stdout, stderr) is by using the async_status, because we need to wait until the task is over.
But for the case of an async task with poll defined to a value different than zero, why should we need to use the async_status in order to parse the output attributes? The values are already there after the execution of the task.

An example would be the following:

```yaml
- name: run command
  command: python -c 'import os; os.write(2, "error")'
  register: output
  async: 500
  poll: 10
  failed_when: "output.stderr is defined and output.stderr != ''"
```
This gives us the following output:
```
changed: [host] => {"ansible_job_id": "56461191558.12277", "changed": true, "cmd": ["python", "-c", "import os; os.write(2, \"error\")"], "delta": "0:00:00.009468", "end": "2017-01-31 18:08:13.088458", "failed": false, "failed_when_result": false, "finished": 1, "rc": 0, "start": "2017-01-31 18:08:13.078990", "stderr": "error", "stdout": "", "stdout_lines": [], "warnings": []}

PLAY RECAP *********************************************************************
host : ok=2    changed=1    unreachable=0    failed=0
```
We see that even though the task is finished and the stderr is set to a string. The failed_when check fails and the playbook returns a succesfull execution.

If I use an extra task like this, I can do successfully what I originally wanted
```
- name: Check command
  async_status: jid="{{ output.ansible_job_id }}" 
  register: result
  failed_when: "result.stderr is defined and result.stderr != ''"
```

Is there a reason why the attributes cannot be directly accessed when poll > 0? It is not obvious in the documentation that the async_status must be used to parse the output even for the not "fire and forget" tasks and to be honest it doesn't make much sense to me. I think it is more straightforward and clean to have direct access to the attributes when poll > 0 than using extra code that might not be needed in the first place.

**Comment by nafpliot-ibm** [comment]
Hmm I believe you can close the issue. I think that this strange behavior would be fixed with https://github.com/ansible/ansible/pull/20423

**Comment by Harosgr** [comment]
I closed the issue because I think this strange behavior will be fixed with https://github.com/ansible/ansible/pull/20423

**Comment by carlpaten** [comment]
This issue still exists in 2.4.2.
