### ISSUE TITLE
Inventory group vars behaviour unexpected

### ISSUE THREAD

**Issue by gerhard-tinned** [ansible/ansible#20916]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

Inventory host group variables behave unexpected.

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

```
# Group A with 2 other groups as child and a group variable
[GroupA]

[GroupA:children]
GroupB
GroupC

[GroupA:vars]
ansible_become_method=su

# Group B with one host in it
[GroupB]
host1

# Group C with one host in it
[GroupC]
Host2
```
Additionally to this inventory file, there are 2 playbooks. One is using the GroupA and is suposed to use "su" as become_method and the second one is using directly the GroupB. The playbook for Group B explicitly sets "sudo" as become_method.

##### OS / ENVIRONMENT

OS: CentOS

##### SUMMARY

The become_method of the Group A is somehow inherited back to the included Group B. This is a very unusual way of inheriting. From my point of view, this is a bug.

##### STEPS TO REPRODUCE

```yaml
- hosts: GroupB
  remote_user: UserB
  become: true
  become_method: sudo

  roles:
    - rolename
```

When this playbook is executed, already the "Setup" task to gather the facts is already failing.

##### EXPECTED RESULTS

It is expected that ansible is using "sudo" to perform the Setup task. As the inventory file in GroupB does not specify a become_method for the host or the group, it is expected that the playbook setting for the become_method is used. 

##### ACTUAL RESULTS

The actual result is a failing playbook at the Setup task as the "su" method as set in GroupA is used. 

It seems as if a become method is not only forward inherited (meaning from GroupB to GroupA) but also backwards from GroupA to GroupB. This behaviour is unexpected and, from my point of view wrong.

**Comment by krzysztof-magosa** [comment]
1. Children inherits variables from parent
2. Connection settings from variables have higher precedence than task settings

You can use variables in task instead of 'settings' to override group vars.
```
vars:
  ansible_become: true
  ansible_become_method: sudo
```

**Comment by gerhard-tinned** [comment]
So to clarify this, The inheritance works both ways and that is supposed to be that way?

* I noticed that a group variable that has been set in a group is inherited to its "parent" group (as expected) via the "[GroupA:children]" instruction (from GroupB to GroupA)
* I noticed also the group variables (this sounds non-logical to me) to be inherited from the parent back to the child group (From GroupA back to GroupB)
* I noticed that the variables placed at the line of the host name override group variables. 
* I have noticed that group variables override the playbook variables (not sure about become_method set at task level)

1. I did not find any documentation about this behavior which caused a lot of time debugging and testing to reverse engineer this unexpected behavior of reverse inheritance of group variables.
2. The reverse inheritance makes things way more complicate. A playbook that uses GroupB directly need to be aware of the existance of the GroupA as GroupA variables interfere with GroupB.
3. What is the priority of the same variable when it is defined in GroupA, GroupB, host line, playbook and task level? So far it seems:
 * Host line variable overrides ...
 * Group variable overrides ...
 * playbook variable
 * Unknown: task and groupA vs GroupB

**Comment by bcoca** [comment]
- There is no inheritance across groups, variables get assigned to hosts via group membership. 

- A host in a child group is automatically member of parent groups, it will get variables from both, in any conflict a child group's variable overrides the parent.

- host variables override group variables

- inventory variables (group or host) do not override play variables, 'connection variables' do override play directives (not variables).

this is documented here http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable, if it is not clear enough we welcome documentation pull requests.

**Comment by gerhard-tinned** [comment]
So this wrong behaviour is only because the GroupB does not specify the ansible_become_method variable? 

I understand what you explain. But this behaviour still does not make any sense.

**Comment by krzysztof-magosa** [comment]
You have `groupB` and `groupC`, both belong to `groupA`.
They don't have own value for `ansible_become_method` so it's "inherited" from parent group.
What's wrong here?

**Comment by gerhard-tinned** [comment]
> What's wrong here? 

Well lets start with the fact that this unusual behavior is not documented anywhere? 

If you use such a non-logical unusual behavior, it would be nice if it could be documented in the related pages. But the inheritance is not explained or described anywhere!!

**Comment by krzysztof-magosa** [comment]
What's non-logical in fact that children inherit things from parent? This is usual way how it works in regular programming languages. If you don't want to inherit from parent group you should not make your groups children of it.

**Comment by gerhard-tinned** [comment]
It is unimportant why it is not logical to me. Fact is the behaviour about inheritance is NOT DOCUMENTED.

**Comment by bcoca** [comment]
http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
