### ISSUE TITLE
Allow add_host module to accept variables

### ISSUE THREAD

**Issue by robparrott** [ansible/ansible#2092]
In particular, allow for the setting of the host port for use with local IaaS type systems, such as vagrant.

I want to be able to do something akin to this:

  add_host hostname='${instances[0].public_ip}' \
                port='${instances[0].port}'  \
                groupname=vagrant_hosts

Or allow the "hostname" var to parse out a "host:port" pair instead.

**Comment by dhozac** [comment]
Fixed by #2104.
