### ISSUE TITLE
Augeas module to support Augeas way

### ISSUE THREAD

**Issue by djatlantic** [ansible/ansible#2093]
Hi all,

It would be good to create such a module.  People coming from Puppet might be interested in this one.

I know that we have:
- assemble
- ini_line
- lineinfile

but could they replace the features of a Augeas.  Honestly I have not look closedly at all of this but I was just wondering.

Thank you.

**Comment by mpdehaan** [comment]
Personally, I think usually people should be using templates whenever possible and augeas is kind of a mess.  That being said, there are reasons when people want it.

The other modules definitely should not be implemented with aug (less dependencies, easier to undestand -- lenses are scary!), but I would tolerate a new module that did use it.

It needs to be written in Python (the module) and follow the usual module infrastructure.

If you want to submit this, I'd consider it for core inclusion.

**Comment by mkotsbak** [comment]
There is one here: https://github.com/paluh/ansible-augeas
