### ISSUE TITLE
Missing deployment of Hosted Engine in ovirt_hosts module

### ISSUE THREAD

**Issue by kobihk** [ansible/ansible#20966]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
oVirt host module
https://github.com/ansible/ansible-modules-extras/blob/devel/cloud/ovirt/ovirt_hosts.py

##### ANSIBLE VERSION

```
2.3
```

##### SUMMARY

In 4.1 we no longer could add additional hosts to hosted engine environment with command of
"hosted-engine --deploy" we should do it thru the GUI/API
but in this ovirt_hosts module we missing the deployment of Hosted Engine option.

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by mykaul** [comment]
@machacekondra ?
