### ISSUE TITLE
Module Request: Extract and Archive

### ISSUE THREAD

**Issue by mbadran** [ansible/ansible#2097]
I have the following Ansible command in several playbooks:

```
- name: quietly unzip the product archive to /opt, overwriting the previous dir
  command: unzip -qo /path/to/product.zip -d /opt
```

I also use the tar equivalent:

```
- name: quietly unzip the archive to /opt/product, overwriting the previous dir
  command: tar -zxf /path/to/product.tar.gz -C /opt/product --strip-components 1 --overwrite --overwrite-dir
```

This seems unnecessarily low level to me. Ideally, I would like to use an idempotent "extract" module as such:

```
- name: extract the archive
  extract: src=/path/to/product.tar.gz
           dest=/opt/product
           type=tgz
           verbose=yes
           backup=yes
```

Supported archive types could include zip, tar, tgz, jar, war -- ie. any format supported by the underlying platform, which would of course depend on the appropriate packages being installed (and perhaps that can be handled by the module as well).

Likewise, an "archive" module that performs the opposite:

```
- name: archive the files
  archive: src=${item}
           dest=/tmp/product.tar.gz
           type=tgz
           verbose=yes
           backup=yes
   with_items:
           - /opt/product1/*.xml
           - /opt/product2/*.txt
           - /opt/product3/*.sh
```

Thanks.

**Comment by mpdehaan** [comment]
I agree, how about making us a patch for it.

Be sure to consider idempotence.

**Comment by mpdehaan** [comment]
Didn't mean to close that.

**Comment by mpdehaan** [comment]
It should probably also offer to transfer the remote file via the copy module, which probably implies a server side module component!

Good idea.

If you don't want to work on this, I'll leave it open, but actually working on it would be great.

**Comment by mbadran** [comment]
Thanks Michael. I'd love to work on this but I've been consumed by regular work lately. I might get a chance in the longer term...

**Comment by mpdehaan** [comment]
Ok, it's in the new "RFE" bucket.

**Comment by yeukhon** [comment]
Actually, Michael, if we can't get recursive copy out, would you rather have archive?

**Comment by mpdehaan** [comment]
We probably /can/ get recursive copy out, but both does not seem to be a
bad thing at all.

The idea of an archive that auto-does a 'fetch' is pretty awesome, esp as
our fetch is sudo enabled in ways that scp is not :) .. or at least can be.

**Comment by mpdehaan** [comment]
patches for this would be accepted.

No longer actively in queue since the local_action: rsync idiom is pretty good and extract/archive could be better dealt with by using the git module

**Comment by carnesen** [comment]
I'm looking for an extract module too. Could you please say a few more words about how the git module can be used for extract / archive?

**Comment by febeling** [comment]
@chrisarnesen Something like this works quite well for me and is idempotent:

``` yaml
- name: unpack
  command: tar xzf /root/{{ archive }} creates=/opt/{{ name }} chdir=/opt
```

**Comment by carnesen** [comment]
Easy enough. Works like a charm, thanks!

**Comment by Gerst20051** [comment]
@mpdehaan the unarchive module should be able to add the argument `--strip-components 1`

**Comment by extremeshok** [comment]
Totally agree, @mpdehaan the unarchive module should be able to add the argument --strip-components 1

**Comment by KamilLelonek** [comment]
+1 for `strip: yes` in `unarchive`.

**Comment by magnetik** [comment]
Maybe we (as I'm interested too), should open a bug about adding strip-components in unarchive module ?

**Comment by KamilLelonek** [comment]
_It's not a bug, it's a feature_. What about creating a pull request?

**Comment by sqrlmstr5000** [comment]
Ran into this today, +1 for the feature!

**Comment by haad** [comment]
+1 for strip

**Comment by jasongoodwin** [comment]
+1 also need this.

**Comment by camilonova** [comment]
+1 for strip too

**Comment by 2xyo** [comment]
+1 for strip too

**Comment by jszwedko** [comment]
@mpdehaan I'd like to use this on files I download from URLs -- it's unclear what a good workaround is without this behavior. Can you suggest anything?

**Comment by jkubrynski** [comment]
+1

**Comment by lxhunter** [comment]
+1

**Comment by davizucon** [comment]
+1

**Comment by lukik** [comment]
+1 for strip

**Comment by BarthV** [comment]
:+1:

**Comment by mcgrealc** [comment]
Just ran into this one as well - another +1 for strip-components please

**Comment by bijanrich** [comment]
+1 for strip-components

**Comment by mcasperson** [comment]
+1

**Comment by arw180** [comment]
+1

**Comment by chickenriggies** [comment]
+1

**Comment by mattdlh** [comment]
+1

**Comment by britter** [comment]
+1

**Comment by szhem** [comment]
+100

**Comment by KamilLelonek** [comment]
What's the status?

**Comment by yeukhon** [comment]
@KamilLelonek  the status is I get +1 every other week.
https://github.com/ansible/ansible-modules-core/pull/2772

**Comment by LouisVN** [comment]
+1

**Comment by pabl0rg** [comment]
+1

**Comment by sighalt** [comment]
+1

**Comment by KamilLelonek** [comment]
Shouldn't this issue be closed as it is solved already?

**Comment by sighalt** [comment]
The OP mentioned a possibility to create a compressed tar ball from a remote directory but I could not find a solution for that problem in the follow-ups.

**Comment by vquemener** [comment]
It sounds like the "archive" module will be available in version 2.2 : http://docs.ansible.com/ansible/archive_module.html

**Comment by davegallant** [comment]
+1

**Comment by Kevinleaf** [comment]
+1
