### ISSUE TITLE
requiring s3_object_version during AWS Lambda create

### ISSUE THREAD

**Issue by antvalencia** [ansible/ansible#20984]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
cloud.amazon.lambda

##### ANSIBLE VERSION
devel branch

##### CONFIGURATION
 - S3 bucket without versioning enabled; ansible devel branch
 
##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
I do not have versioning enabled on the S3 bucket which contains my Lambda zip file.  Currently, it is required that the parameter 's3_object_version' is supplied along with 's3_key', 's3_bucket'.  Perhaps s3_object_version should be removed from this group?  See Expected Results below.  As a short-term workaround, I've removed this parameter from the list in my local source.

##### STEPS TO REPRODUCE
run:
ansible-playbook my_playbook.yml --vault-password-file .vault_password -v

- name:  create AWS Lambda function
  lambda:
    name: "{{ lambda_function }}"
    state: present
    s3_bucket: "{{ lambda_s3_bucket }}"
    s3_key: "{{ lambda_s3_object }}"
    runtime: python2.7
    role: "{{ lambda_exec_role_arn }}"
    handler: "{{ lambda_handler }}"
    description: "{{ utility_description }}"
    timeout: 300
    memory_size: 1024
    region: "{{ aws_region }}"

##### EXPECTED RESULTS
Perhaps add a check to see if versioning is enabled before adding this parameter to the group which are required together.  Or, even if versioning is enabled, but the version is not supplied, choose the latest version and note that the latest version is chosen if the parameter is not supplied in documentation.

##### ACTUAL RESULTS
TASK [roles/common : create AWS Lambda function] *******************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "parameters are required together: ['s3_key', 's3_bucket', 's3_object_version']"}

**Comment by ryansb** [comment]
It doesn't look like this argument is required (see docs [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/lambda.py#L69-L73)) but later it's in the `required_together` group [here](https://github.com/ansible/ansible/blob/ccb1b742f589d52c12045688d83a59197b3c3e26/lib/ansible/modules/cloud/amazon/lambda.py#L231). 

Fixed in https://github.com/ansible/ansible/commit/bb9ee0cf6f27b883491439766ac1a8b1bb2e957e

**Comment by ryansb** [comment]
Please reopen this issue if this doesn't fully resolve it for you. Thanks for pointing this out!
