### ISSUE TITLE
--tags on play not working as expected

### ISSUE THREAD

**Issue by hloeffler** [ansible/ansible#21018]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

**--tags** used at **play** level
##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

--tags "tag1" runs **setup** on not tagged play

##### STEPS TO REPRODUCE

clone: https://github.com/hloeffler/ansible-docker/tree/master/tests
run ./test.sh

```yaml
---

- name: test play 1
  hosts: group1
  tags: tag1
  
  tasks:
    - debug: msg="hello from play 1"

- name: test play 2
  hosts: group2
  tags: tag2
  
  tasks:
    - debug: msg="hello from play 2"

```

##### EXPECTED RESULTS

not running setup on play1

##### ACTUAL RESULTS

setup was run on play1

```
ansible@b2baadb63664:~/tests$ ansible-playbook -i inventory tagged-plays.yml --tags tag2

PLAY [test play 1] *************************************************************

TASK [setup] *******************************************************************
ok: [test1]
ok: [test2]
ok: [test3]

PLAY [test play 2] *************************************************************

TASK [setup] *******************************************************************
ok: [group2-host1]
ok: [group2-host2]
ok: [group2-host3]

TASK [debug] *******************************************************************
ok: [group2-host1] => {
    "msg": "hello from play 2"
}
ok: [group2-host3] => {
    "msg": "hello from play 2"
}
ok: [group2-host2] => {
    "msg": "hello from play 2"
}

PLAY RECAP *********************************************************************
group2-host1               : ok=2    changed=0    unreachable=0    failed=0   
group2-host2               : ok=2    changed=0    unreachable=0    failed=0   
group2-host3               : ok=2    changed=0    unreachable=0    failed=0   
test1                      : ok=1    changed=0    unreachable=0    failed=0   
test2                      : ok=1    changed=0    unreachable=0    failed=0   
test3                      : ok=1    changed=0    unreachable=0    failed=0   

```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The implicit `setup`' task triggered by `gather_facts` is tagged `always` so to avoid running them you need to specifically skip the `always` tag.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by hloeffler** [comment]
@bcoca thank you
isn't ansible-devel the better mailing-list for this?

**Comment by hloeffler** [comment]
i know why this is happening, but there is no way skip the task with a when, right?
i need setup for the tagged play...
and it just makes no sense from an user perspective

**Comment by bcoca** [comment]
it makes sense for this case:

```
- hosts: blah
  tasks:
    - command:
       tags: 1
    - command:
       tags: 2
```
You normally want fact gathering to run no matter which tag you use.

**Comment by hloeffler** [comment]
i know it make sense, for this,
i just have the fear ansible got way too dynamic

from a tag on toplevel i expect to to be a top level switch
solution for me is splitting in multiple playbooks which sucks

@bcoca and no, i dont want gathering to run for hosts i dont run task on, it is slow (i have over 1k hosts)

**Comment by hloeffler** [comment]
but i think its too late @bcoca 

after dynamic includes, ansible dont know any more where which tag is (--list-tags with 1.9 vs 2.x)
so we just cant scan all tasks to decide not to run setup

maybe i just have to work on **strict mode** for ansible

sorry for wasting your time

**Comment by bcoca** [comment]
No time wasted, you are correct that this is a consequence of allowing dynamic inclusion.
There are tradeoffs that are inevitable with new features, this was one of them.
