### ISSUE TITLE
Update, remove or migrate CODING_GUIDELINES.md

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#21028]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
CODING_GUIDELINES.md

##### ANSIBLE VERSION
```
N/A
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY

The CODING_GUIDELINES.md file is extremely out of date.  It contains information about coding style, tests, etc.

I bean looking into this document, but found the amount of information needing updating a bit daunting for me to undertake at the moment.

This file should either be updated, removed and potentially migrated into the docsite.

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A

**Comment by gundalow** [comment]
+1 to deleting

Eventually we will have some non-module specific docs under docs.ansible.com/ansible/dev_guide that will contain this

**Comment by gundalow** [comment]
Exists, though just points to main docs.ansible.com content https://github.com/ansible/ansible/blob/devel/CODING_GUIDELINES.md
