### ISSUE TITLE
consider an 'until' keyword

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#2103]
It has been suggested that we have a way to keep trying something until it is true, for instance, it's kind of like wait_for, but more abstract, and could be used with the command module or even the URI module.

this seems to imply it would use the 'poll' keyword or have another keyword to control the intra-task interval.

This probably happens inside the runner loop

It probably has some attribute like until_count as well, that is only valid with until

Thoughts?

**Comment by rrtj3** [comment]
If this was abstract enough to define what you wanted it to 'wait_for'
(e.g. uri module; status 200 or some string in the page contents) that
would be very, very nice.

**Comment by mpdehaan** [comment]
It would have to be dependent of the result of that particular task or to
supply another module call to use a s a test.  TBD.

**Comment by willthames** [comment]
Adding more to this following discussion on list with @mpdehaan 

I'm of the opinion that it should have an interval and a timeout value as an alternative to count (but obviously they're fairly equivalent)

Something like:
    name: wait for healthcheck to succeed
    action: uri url=http://host:port/healthcheck return_content=yes
    register: healthcheck
    until: test='${health_check.content} == "healthy"' delay=30 timeout=300

if we can pass delay and timeout to a form similar to the when_ tests then it would be great to have until_ equivalents (until_string, until_set etc.)

**Comment by kavink** [comment]
+1 @willthames A Poll interval will be also good, for it to keep trying till timeout.

A Question: would it be possible further in playbook to use the result of, if "until" succeeded or timed out.

**Comment by willthames** [comment]
@kavink - my delay value should be equivalent to your poll interval - interval might be preferable to delay. 

One other thought I had is that count may well be a useful feature (i.e. do this repeatedly five times) - I'm not sure if @mpdehaan would worry about turning playbooks into a programming language if we then made the current loop counter available. 

However, if I do make any progress on this my primary use case is the polling.

**Comment by mpdehaan** [comment]
patches would be accepted.  This is not something I am actively working on for 1.2.

**Comment by srgvg** [comment]
As to make that generic: by default (uri already had a body string to check on) polling until rc == 0 ?
