### ISSUE TITLE
playbook syntax introduction in inventory intro

### ISSUE THREAD

**Issue by andresvia** [ansible/ansible#21041]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

 - `docs/docsite/rst/intro_inventory.rst`

##### ANSIBLE VERSION
N/A

##### SUMMARY

For someone who is reading the documentation back to back, the Docker example (Non-SSH connection types section), in the introduction to the inventory file introduces a new syntax (playbook) without proper introduction, or at least stating that the format is not for inventory files.

**Comment by nrwahl2** [comment]
Thanks @andresvia . I've submitted PR #21041
