### ISSUE TITLE
Allow ansible to control a local vagrant install

### ISSUE THREAD

**Issue by robparrott** [ansible/ansible#2105]
ansible should be able to do this ... my first working attempt is here:
- https://github.com/robparrott/ansible-vagrant

Working on a version that can fire up N instances at once (taking "count=" argument).

**Comment by robparrott** [comment]
Updated repo now includes support for N instances under a given "vm_name."

**Comment by mpdehaan** [comment]
Can you see about making it do "state=present/absent" instead of "up" (i.e.
idempotence) so we can see about including it in core?

**Comment by robparrott** [comment]
OK ... I can do that. 

Looks like it can be handled in the main "switch" code.

**Comment by mpdehaan** [comment]
outstanding, I would love to include this.

may have some other review comments when that comes across but shouldn't be
too many

Thanks!

**Comment by robparrott** [comment]
Thats's fine ... I'm happy to refactor. 

one thing to consider is that this include an external python-vagrant module. Thoughts on maintaining that external dependency, versus rolling it in?

**Comment by robparrott** [comment]
Refactored to allow for state=present/absent, at this repo/tag:

```
https://github.com/robparrott/ansible-vagrant/tree/0.0.1
```

Note that vagrant itself, and the python-vagrant wrapper is not thread safe, so while a "local_action" works fine (since this is serialized) running in parallel on multiple vagrant instances creates race conditions. I've solved this by locking the entire wrapper class, but in the process introduced an optional dependency on the "lockfile" module. If this module is available, operations should be thread-safe. If not, then all local operations (such as a startup) which are serial are fine, but operations that operate in parallel will not be thread safe. This is for the most part an annoyance to me right now, but may be a bigger issue for other use cases.

**Comment by mpdehaan** [comment]
Maybe just flock?

**Comment by mpdehaan** [comment]
I'm fine with it relying on python-vagrant if that makes life easier.  But
if it can do-without, that's good too.

Just should raise an error if an external python dep is not installed and
that dep must be available in at least PyPi.

**Comment by robparrott** [comment]
For clarification, the deps are "python-vagrant (required)" and "lockfile
(not required, but funny things may happen)"

Both are "pip'able."

Rob

**Comment by mpdehaan** [comment]
No problem at all on python-vagrant.

You should be able to get away with fcntl.flock to remove the lockfile part.

**Comment by robparrott** [comment]
Will that work on Windows OS variants?

**Comment by mpdehaan** [comment]
It won't -- Unless it emulates it, I doubt it, but maybe try to import
lockfile and if you don't have it fall back to flock?

Your ansible content can obviously install the lockfile module but it would
be nice if people did not have to remember it.

(I was falsely assuming you were aiming squarely at Macs before)

I still have to resolve a bit of the 'CLI works on windows clients' patch
stuff in the next week or so.

**Comment by robparrott** [comment]
tag 0.0.3 now falls back to "flock" if the lockfile module is not present.

**Comment by mpdehaan** [comment]
yeah please make sure there is an updated pull request for this.  I don't
really follow issue tickets for review stuff and this is too useful to not
have in core.

If you put in a pull request usually it will auto-detect any changes you
make on the branch.

**Comment by robparrott** [comment]
Done. #2156

**Comment by mpdehaan** [comment]
I am closing this feature ticket because we already have an open pull request for this.
