### ISSUE TITLE
debug in pre_tasks errors with `'msg' is not a valid attribute for a Task`

### ISSUE THREAD

**Issue by AJamesPhillips** [ansible/ansible#21064]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
debug (in playbook pre_tasks)

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel db8fd95d68) last updated 2017/02/06 14:01:14 (GMT +100)
  config file = /Users/k435/p64/provision/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The debug module in a playbook pre_tasks will error

##### STEPS TO REPRODUCE
Using the playbook:
```yaml
---
- hosts: all
  pre_tasks:
    - debug:
      msg: "remote_user is: {{ remote_user }}, ansible_user is {{ ansible_user }}"
```

##### EXPECTED RESULTS
It should run and report value of remote_user and ansible_user (or error as necessary)

##### ACTUAL RESULTS
```
ansible-playbook ./playbook.yml --limit "lb"
ERROR! 'msg' is not a valid attribute for a Task

The error appears to have been in '/Users/k435/p64/provision/playbook.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  pre_tasks:
    - debug:
      ^ here
```

I hope I've not misunderstood http://docs.ansible.com/ansible/debug_module.html or pre_tasks from http://docs.ansible.com/ansible/playbooks_roles.html#roles

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case, this is a simple indentation issue, `msg` is an option of `debug` yet you are making it a task directive by keeping the same indentation level. This should execute correctly:
```yaml
- hosts: all
  pre_tasks:
    - debug:
        msg: "remote_user is: {{ remote_user }}, ansible_user is {{ ansible_user }}"
```

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by flybd5** [comment]
This is actually not an indentation error. The msg: is indented 2 spaces in from - debug:. This is correct. Ansible should not require 4 spaces indentation when everywhere else 2 is correct.
