### ISSUE TITLE
include_role module docs list 'None' as default for `private` parameter

### ISSUE THREAD

**Issue by wenottingham** [ansible/ansible#21077]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

include_role

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

(also devel)

##### OS / ENVIRONMENT

CentOS 7, Fedora

##### SUMMARY

include_role takes a `private` parameter, described as:
"If True the variables from defaults/ and vars/ in a role will not be made available to the rest of the play."

module docs list the default as 'None', which is ambiguous. Presumably the default is actually one of 'True' or 'False'.

##### STEPS TO REPRODUCE

1. look at docs.

**Comment by alikins** [comment]
Not sure what the docs should say here. The 'default=None" kind of matches lib/ansible/playbook/role_include.py.IncludeRole's _private attribute 

```
_private = FieldAttribute(isa='bool', default=None, private=True)
```
