### ISSUE TITLE
trailing '}}' throws misleading error

### ISSUE THREAD

**Issue by rasputnik** [ansible/ansible#21078]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Error handler

##### ANSIBLE VERSION

```
Desktop:$ ansible --version
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
Desktop:$
```

##### CONFIGURATION

stock.

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Stray '}}' characters cause ansible to error out with this odd message:

```
ERROR! this task 'debug' has extra params, which is only allowed in the following modules: command, win_command, shell, win_shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta
```

Ansible points to the wrong part of the YAML. Have hit this a few times with new users and thought I'd flag it up

##### STEPS TO REPRODUCE

run 'ansible-playbook below_file.yml'

```yaml
---

- hosts: localhost
  tasks:
    - name: stray moustaches cause odd error message
      debug: msg="Won't run" }}
```

##### EXPECTED RESULTS

Some indication of a parse error in the yaml.

##### ACTUAL RESULTS

Error is printed "

```
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! this task 'debug' has extra params, which is only allowed in the following modules: command, win_command, shell, win_shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta

The error appears to have been in '/Users/sisred/Desktop/bug.yml': line 5, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: stray moustaches cause odd error message
      ^ here


The error appears to have been in '/Users/sisred/Desktop/bug.yml': line 5, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: stray moustaches cause odd error message
      ^ here
```

**Comment by sivel** [comment]
I believe the error is correct.  It states:

> ERROR! this task 'debug' has extra params

You provided extra parameters, which in this case were just the 2 characters of `}}`.  Those characters could have been anything.  This is because the space between the `"` and the `}` cause the parser to believe you were adding another parameter.

If you were using the recommended pure YAML format of:

```
- debug:
    msg="Won't run" }}
```

You would have gotten a syntax error.

**Comment by rasputnik** [comment]
Tried switching the playbook format and you're right, that error is far clearer.

Might be time to port over my old playbooks. Especially when giving tutorials etc.

Have we deprecated the old syntax yet though?

**Comment by ryansb** [comment]
There aren't any plans to deprecate the old syntax, since there are valid uses for it (CLI usage, simple tasks, etc etc). But we favor the new syntax in most tutorials/examples.

**Comment by rasputnik** [comment]
ok, i'm happy to shut this down. 
New syntax is definitely more helpful for identifying YAML structure typos.
