### ISSUE TITLE
Add parameter php_path in module composer.py to choose php binary's path.

### ISSUE THREAD

**Issue by GwenaelPellenArkeup** [ansible/ansible#21129]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
composer.py

file: lib/ansible/modules/packaging/language/composer.py

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
no change

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Add parameter php_path in module composer.py to choose php binary's path.

##### EXPECTED RESULTS
```
EXAMPLES = '''

...

# Downloads and installs all the libs and dependencies outlined in the /path/to/project/composer.lock
# choose PHP 7.1 to execute composer.
- composer:
    php_path: /usr/bin/php7.1
    command: install
    working_dir: /path/to/project

...
'''
```

**Comment by GwenaelPellenArkeup** [comment]
Hello @dmtrs, @resmo.

What do you think of this idea?

Best regars.

**Comment by resmo** [comment]
@GwenaelPellenArkeup would be ok for me

needs_contributor

**Comment by resmo** [comment]
resolved_by_pr #26107
