### ISSUE TITLE
Regression: handlers not inheriting role parameters (become)

### ISSUE THREAD

**Issue by rdonkin** [ansible/ansible#21139]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ansible-playbook, become clause

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

$ echo $ANSIBLE_STDOUT_CALLBACK 
debug

##### OS / ENVIRONMENT

OS X 10.11.6 - control machine and target server

##### SUMMARY

Regression in 2.2.1 of #17490 - the `become: yes` attribute is once more not inherited from the role invocation to a handler.  Maybe a unit test to cover this would be a good idea.

##### STEPS TO REPRODUCE

This is the same test case used by @jimi-c in #17490:

```shell
$ cat >test.yml
- hosts: localhost
  gather_facts: no
  roles:
  - { name: test, become: yes }
$ mkdir -p roles/test/tasks
$ mkdir -p roles/test/handlers
$ cd roles/test/tasks/
$ cat > main.yml
---
# tasks file for roles/test
- debug:
  changed_when: true
  notify: the handler
$ cd ../handlers/
$ cat > main.yml
# handlers file for roles/test
- name: the handler
  command: whoami
$
```

##### EXPECTED RESULTS

Handler should run the `whoami` command using `sudo`, by inheriting the `become: yes` from the role.

##### ACTUAL RESULTS

The whoami command is run without sudo:

```
$ ansible-playbook -vv test.yml 
No config file found; using defaults
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [localhost] ***************************************************************

TASK [test : debug] ************************************************************
task path: ..../bugs/become-not-inherited-17490/roles/test/tasks/main.yml:3
NOTIFIED HANDLER the handler
ok: [localhost] => {}

MSG:

Hello world!


RUNNING HANDLER [test : the handler] *******************************************
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "sudo: a password is required\n", 
    "module_stdout": ""
}

MSG:

MODULE FAILURE

...

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=1   


```

**Comment by rdonkin** [comment]
Any comment on release when this will be fixed?  It's a very clear regression with a simple test case.

**Comment by jimi-c** [comment]
@rdonkin I can't reproduce this. With a slightly modified playbook:
<pre>
[jamesc@jimi 17490]$ cat test.yml 
- hosts: localhost
  gather_facts: no
  roles:
  - { name: test, become: yes }
  tasks:
  - meta: flush_handlers
  - command: whoami
</pre>
I get the following (expected) output:
<pre>
[jamesc@jimi 17490]$ ansible-playbook -vv test.yml 
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: test.yml ***************************************************************************************************************************************************************************
1 plays in test.yml

PLAY [localhost] *****************************************************************************************************************************************************************************
META: ran handlers

TASK [test : debug] **************************************************************************************************************************************************************************
task path: /home/jamesc/testing/17490/roles/test/tasks/main.yml:3
NOTIFIED HANDLER the handler
changed: [localhost] => {
    "changed": true, 
    "msg": "Hello world!"
}

RUNNING HANDLER [test : the handler] *********************************************************************************************************************************************************
changed: [localhost] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.002539", "end": "2017-02-17 14:22:05.321548", "rc": 0, "start": "2017-02-17 14:22:05.319009", "stderr": "", "stderr_lines": [], "stdout": "root", "stdout_lines": ["root"]}
META: ran handlers

TASK [command] *******************************************************************************************************************************************************************************
task path: /home/jamesc/testing/17490/test.yml:7
changed: [localhost] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.002213", "end": "2017-02-17 14:22:05.441200", "rc": 0, "start": "2017-02-17 14:22:05.438987", "stderr": "", "stderr_lines": [], "stdout": "jamesc", "stdout_lines": ["jamesc"]}
META: ran handlers
META: ran handlers

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=3    changed=3    unreachable=0    failed=0   
</pre>
As you may see from the shell above, I'm using the reproducer I still had from #17490 as well.

**Comment by rdonkin** [comment]
Sorry @jimi-c, my repro was incorrect as I was forgetting to specify `-K` for OS X sudo password.  In fact the test works fine on both OS X to OS X and OS X to CentOS. 

However, I have seen this "in the wild" in 2.2.1, including in the https://github.com/dev-sec/ansible-ssh-hardening role as discussed in this PR: https://github.com/dev-sec/ansible-ssh-hardening/pull/81

Closing this now and will attempt to come up with a simple repro for the issue found in that role.

**Comment by afeld** [comment]
Note that handlers inside of a role don't seem to inherit the `become` called via an `include_role`, either. Let me know if I should open a standalone issue.
