### ISSUE TITLE
other modules need --check mode support

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#2114]
It would be nice to add this to the apt module in particular.

**Comment by kavink** [comment]
Added for apt and lineinfile #2115

**Comment by mpdehaan** [comment]
Excellent!

**Comment by johanwiren** [comment]
Added for zfs in #2176

**Comment by mpdehaan** [comment]
patches for other modules are being accepted when they are added, so don't really need this tracker ticket
