### ISSUE TITLE
cannot import name AnsibleVaultEncryptedUnicode

### ISSUE THREAD

**Issue by andreinadesousa** [ansible/ansible#21147]
I'm installing Ansible Tower 2.4.5 on CentOS 7. When running the ./setup.sh, I get this error:

TASK [packages_ubuntu : include_vars] ******************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name AnsibleVaultEncryptedUnicode
fatal: [localhost]: FAILED! => {"failed": true, "stdout": ""}

PLAY RECAP *********************************************************************
localhost                  : ok=25   changed=5    unreachable=0    failed=1

**Comment by Qalthos** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, this is not the right place to discuss issues with Ansible Tower. Please direct Tower issues to http://support.ansible.com/ and they will be able to  help you with your problem.

Thank you once again for this and your interest in Ansible!
