### ISSUE TITLE
CN and Hostname don't match for machines on Active Directory

### ISSUE THREAD

**Issue by bedcruncher** [ansible/ansible#21155]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ConfigureRemotingforAnsible.ps1

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### CONFIGURATION
Does not apply

##### OS / ENVIRONMENT
Ansible Server = CentOS Linux release 7.3.1611 (Core)
Ansible Endpoint = Windows 7 Ultimate x64 SP1

##### SUMMARY
Fresh Win7 image with current updates and WMF4 installed. Symantec Endpoint Protection with all ports open for winrm opened to allow traffic and Domain joined.

Appears to have been a change in the way that certificates are added to `cert:\LocalMachine\My`
In the current script `Line 115` that reads 

`Get-ChildItem "Cert:\LocalMachine\my"| Sort-Object NotBefore -Descending | Select **-First** 1 | Select -Expand Thumbprint`

It's grabbing the thumbprint for a certificate that is installed on the machine from one of our Domain Controllers and erroring out with the following message.

##### STEPS TO REPRODUCE
Get a fully patched, domain joined machine, with WMF 4. Check to see that it gets a cert put into the Personal store and if so the current script as exists will fail out with the above error. 

##### EXPECTED RESULTS
```
Self-signed SSL certificate generated; thumbprint: REMOVED


wxf                 : http://schemas.xmlsoap.org/ws/2004/09/transfer
a                   : http://schemas.xmlsoap.org/ws/2004/08/addressing
w                   : http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd
lang                : en-US
Address             : http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous
ReferenceParameters : ReferenceParameters

Ok.
```
##### ACTUAL RESULTS
```
[ansible-tst-0]: PS C:\> .\test.ps1 -ForceNewSSLCert -SkipNetworkProfileCheck -CertValidityDays 1865
Self-signed SSL certificate generated; thumbprint: REMOVED
New-WSManInstance : The WinRM client cannot process the request. The certificate CN and the hostname that were
provided do not match.
At C:\test.ps1:216 char:5
+     New-WSManInstance -ResourceURI 'winrm/config/Listener' -SelectorSet $selecto ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-WSManInstance], InvalidOperationException
    + FullyQualifiedErrorId : WsManError,Microsoft.WSMan.Management.NewWSManInstanceCommand
```

**Comment by bedcruncher** [comment]
The fix as I have done it to get this to work is to change the `Line 115` from `-First` to `-Last` so that it reads
``` Get-ChildItem "Cert:\LocalMachine\my"| Sort-Object NotBefore -Descending | Select -Last 1 | Select -Expand Thumbprint ```

**Comment by bedcruncher** [comment]
I've recently run into a different issue on the same line... current solution is to change that line to the following and add the relevant below.
**where {$_.Issuer.EndsWith($env:computername)}**
```
$thumb = Get-ChildItem "Cert:\LocalMachine\my"| Sort-Object NotBefore -Descending | select -first 1 | where {$_.Issuer.EndsWith($env:computername)} | select -ExpandProperty Thumbprint
$thumb
```

**Comment by jhawkesworth** [comment]
possibly other problems too https://github.com/ansible/ansible/issues/21248

**Comment by jhawkesworth** [comment]
@bedcruncher - just in case you aren't seeing notifications on other github issues - there is a fix for this on https://github.com/ansible/ansible/issues/21263 - please can you have a look and try it out so we can confirm this fixes things for you?
