### ISSUE TITLE
route53_zone does not support split horizon setup

### ISSUE THREAD

**Issue by conleym** [ansible/ansible#21160]
https://github.com/ansible/ansible-modules-extras/issues/1756 was never imported into this repo, and is still not fixed as of 2.2.1.0.

**Comment by nitzmahone** [comment]
Feel free to move the issue over if it's something you want tracked: https://github-issue-mover.appspot.com/. Closing this one, since it doesn't contain any direct detail...

**Comment by conleym** [comment]
I'm certainly not trolling through the old repos to move issues over one by one.

**Comment by nitzmahone** [comment]
We couldn't wholesale move issues over, as that makes us the owners of all of them. We figured interested parties (original filers or people interested in tracking them) would move them over if they still cared about them.

**Comment by conleym** [comment]
Has anybody considered setting some kind of group up to go through issues in the other repos and either move them over or close them as appropriate?

I could see myself contributing to such an effort.
