### ISSUE TITLE
Dynamic inventory encrypted configs (vault support)

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#21164]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

[inventory](/ansible/ansible/tree/devel/contrib/inventory)

##### SUMMARY

Some dynamic inventory scripts are used with config files that are supposed to include credentials. Encrypting these files with vault looks like strait forward approach but not currently supported.

**Comment by bcoca** [comment]
this would require that inventory scripts implement the feature as Ansible just executes them and they read their own config. For that we would also have to pass the vault secret to them.

An alternative, in  https://github.com/ansible/proposals/issues/41 we move to have them be actual real plugins, and in conjunction with https://github.com/ansible/proposals/issues/35 it allows them to share the main 'ansible config' at which point we could add encryption to it.

**Comment by hryamzik** [comment]
I can see that it's possible to import ansible python modules in these plugins so it should be possible to use vault setting from ansible.conf and vault function to read files. It's clear that inventory scripts modification is required and if there was a clear way to add vault support I'd make PRs for some of them.

**Comment by bcoca** [comment]
This is now possible when using inventory plugins and YAML configs, virtualbox plugin as example.

Since we merged https://github.com/ansible/ansible/issues/23001
