### ISSUE TITLE
docker daemon start using ansible

### ISSUE THREAD

**Issue by gworksmobi** [ansible/ansible#21186]
I am working on ansible script for **start docker damon , docker container, docker exec**  After start docker container with in the docker container i need to start some services.

I have installed docker engine , configured and working with some docker container in remote machines. i have used to start docker daemon with specific path, because i need to store my volumes and containers with in path.

     $docker daemon -g /test/docker

My issue is **when start the docker daemon its started, but not go to next process.** via ansible. still running docker daemon.

      ---
      - hosts: webservers
        remote_user: root

       # Apache Subversion   dnf -y install python-pip

        tasks:
        
          - name: Start Docker Deamon
            shell: docker -d -g /test/docker 
            become: yes
            become_user: root

          - name: Start testing docker machine
            command: docker start testing
            async: True
            poll: 0

I follow async to start the [process][1] ,but its not working for me , 

Suggest me After start docker daemon, How to run next process.

  [1]: http://stackoverflow.com/questions/29994021/ansible-start-python-flask-script-in-new-terminal-window

**Comment by nitzmahone** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
