### ISSUE TITLE
Cpu/memory configuration for ansible host?

### ISSUE THREAD

**Issue by companycy** [ansible/ansible#21198]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME

performance

##### ANSIBLE VERSION

```
# ansible --version
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

forks=50
pipelining=True

##### OS / ENVIRONMENT

Ubuntu 14.04

##### SUMMARY

Cpu/memory/io config required when ansible playbook is working with hundreds of hosts

##### STEPS TO REPRODUCE

I want to setup a cluster on cloud and manage it with ansible which is also on VM. However, I wonder what kind of cpu/memory config should be prepared for this VM. Maybe 1C512M should be enough for hundreds of hosts. Or would you please let me know how to measure by myself.

There is a forks in ansible.cfg, which means how many hosts are configured by Ansible in parallel. So only 50 (which is my case) ssh links are setup when playbook is working? Then I should never worry about cpu/memory configuration?

Thanks a lot!

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by nitzmahone** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
