### ISSUE TITLE
Variable precedence with play vars/vars_prompt/vars_files

### ISSUE THREAD

**Issue by craigfrancis** [ansible/ansible#21205]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
Core

##### ANSIBLE VERSION
```
2.2.1.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
As someone who is very new to Ansible... 

With variable precedence, I was setting variables in the playbook (aka "play vars"), and assuming they would be seen as defaults, where the inventory `group_vars` and `host_vars` would be able to override these as necessary.

http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

---

#### STEPS TO REPRODUCE
Create a playbook "install.yml":

    ---
    - hosts: all
      vars_files:
        - "defaults.yml"
        - "passwords.yml"
      vars:
        install_packages:
          - apache2
          - php
      become: yes
      tasks:
        - name: Install packages
          package:
            name: "{{ item }}"
            state: latest
          with_items: "{{ install_packages | union(install_packages_extra | default([])) }}"

And create a host specific config `./host_vars/server-a.yml`.

I'd expect that the host variables (which are more specific) to be able to use, override, or change the `install_packages` variable.

For now I've used the `union()` function so that the host can provide additional packages with `system_install_extra`, but this isn't helpful when 1 of your 10 servers uses a slightly different package name for php (i.e. Debian calls it "php5").

As a separate issue, I started with a `defaults.yml` file (as you can see above), for some of the more generic variables (to be used between playbooks), but because it nukes the host specific variables, I've instead gone for a `./group_vars/all.yml` file (where someone completely new to Ansible might not realise that it would be included).

---

#### EXPECTED RESULTS
Personally I was expecting the precedence to be something like:

1. **play vars** - In the playbook as [vars](http://docs.ansible.com/ansible/playbooks_variables.html#variables-defined-in-a-playbook).
2. **play vars_prompt** - In the playbook as [vars_prompt](http://docs.ansible.com/ansible/playbooks_prompts.html).
3. **play vars_files** - In the playbook as [vars_files](http://docs.ansible.com/ansible/playbooks_variables.html#variable-file-separation).
4. role defaults - [/path/to/role/x/defaults/main.yml](http://docs.ansible.com/ansible/playbooks_roles.html#role-default-variables)
5. inventory vars - [/path/to/inventory/hosts](http://docs.ansible.com/ansible/intro_inventory.html)
6. inventory group_vars - /path/to/inventory/group_vars/group.yml
7. inventory host_vars - /path/to/inventory/host_vars/host.yml
8. playbook group_vars - ./group_vars/group.yml (relative to playbook).
9. playbook host_vars - ./host_vars/host.yml (relative to playbook).
10. host facts - [Remote host setup](http://docs.ansible.com/ansible/setup_module.html), typically collected when playbook starts (or [switched off](http://docs.ansible.com/ansible/playbooks_variables.html#turning-off-facts)).

Then the variables as the playbook begins:

11. registered vars - [In the playbook, recorded by a task](http://docs.ansible.com/ansible/playbooks_variables.html#registered-variables).
12. set_facts - [In the playbook as set_fact](http://docs.ansible.com/ansible/set_fact_module.html).
13. role and include vars - Either a [/path/to/role/x/vars/main.yml](http://docs.ansible.com/ansible/playbooks_roles.html#roles), or [vars: for an include](http://docs.ansible.com/ansible/playbooks_roles.html#task-include-files-and-encouraging-reuse).
14. block vars - Not really described in the [blocks documentation](http://docs.ansible.com/ansible/playbooks_blocks.html), and [may not be allowed](https://github.com/ansible/ansible/issues/11779#issuecomment-125957650).
15. task vars - I assume these are the individual variables that get passed to the module.

And finally

16. extra vars - Using [--extra-vars](http://docs.ansible.com/ansible/playbooks_variables.html#passing-variables-on-the-command-line) from the command line.

---

Or, if backwards compatibility is an issue, there could be a new class of defaults that can be set in the playbook:

    ---
    - hosts: all
      default_vars_files:
        - "passwords.yml"
      default_vars:
        install_packages:
          - apache2
          - php

---

As to using "role defaults", as suggested for the "most malleable and easily overridden" variables, I don't think that will work with my setup (where my playbooks are pretty self contained, and my variables and servers don't really work in roles, or need lots of folders to organise them).

**Comment by nitzmahone** [comment]
We're unlikely to shred the variable precedence scheme- it's evolved over time and works well for the majority of users. There's some related ongoing discussion around unifying config and inventory stuff [here](https://github.com/ansible/proposals/issues/35)- you might want to follow/engage on that proposal. I'm going to close this issue, though.
