### ISSUE TITLE
s3_bucket error: Your previous request to create the named bucket succeeded and you already own it

### ISSUE THREAD

**Issue by mfeliciano** [ansible/ansible#21201]
See https://github.com/ansible/ansible-modules-extras/issues/3354#issue-187051860

**Comment by nitzmahone** [comment]
Feel free to move the issue over if you want it to be actively tracked: https://github-issue-mover.appspot.com/. We didn't move them in an automated fashion, as whoever moved the issues would become the owner of all of them.

**Comment by rachelkelly** [comment]
Hi, was this issue fixed or are there plans to fix it?  I'm rather stuck on this right now, and I don't know enough to submit a PR against it.

**Comment by lig** [comment]
@nitzmahone what does it mean? why is this closed? could you please provide some details?
