### ISSUE TITLE
ansible nagios module use wrong rw/nagios.cmd path

### ISSUE THREAD

**Issue by sirkubax** [ansible/ansible#21219]
##### ISSUE TYPE
 - Bug Report

I call it a bug, but it is a concept limitation...

##### COMPONENT NAME
`extras/monitoring/nagios.py`

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT
Ubuntu

##### SUMMARY
The ansible nagios module `modules/extras/monitoring/nagios.py` uses predefined configuration paths. If your nagios setup is not the one by the system package, you can not run the module.

I do have nagios3 package (config: `/etc/nagios3/nagios.cfg`; `command_file=/var/lib/nagios3/rw/nagios.cmd`) that is **not running**. 

I **do use custom nagios** at  `/usr/local/nagios/etc/nagios.cfg`  (`command_file=/usr/local/nagios/var/rw/nagios.cmd`)  - this shall be used, but nagios3 dissabled config is taken and the error is returned

```
fatal: [stg-test -> None]: FAILED! => {
    "changed": false, 
    "cmdfile": "/var/lib/nagios3/rw/nagios.cmd", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "action": "downtime", 
            "author": "Ansible", 
            "cmdfile": "/var/lib/nagios3/rw/nagios.cmd", 
            "command": null, 
            "comment": "Ansible: Removing nagios downtime by kuba\z", 
            "host": "stg-test", 
            "minutes": "10", 
            "service": "host", 
            "servicegroup": null, 
            "services": "host"
        }, 
        "module_name": "nagios"
    }, 
    "msg": "unable to write to nagios command file"
}

```

The problematic part of the code:

```
def which_cmdfile():
    locations = [
        # rhel
        '/etc/nagios/nagios.cfg',
        # debian
        '/etc/nagios3/nagios.cfg',
        # older debian
        '/etc/nagios2/nagios.cfg',
        # bsd, solaris
        '/usr/local/etc/nagios/nagios.cfg',
        # groundwork it monitoring
        '/usr/local/groundwork/nagios/etc/nagios.cfg',
        # open monitoring distribution
        '/omd/sites/oppy/tmp/nagios/nagios.cfg',
        # ???
        '/usr/local/nagios/etc/nagios.cfg',
        '/usr/local/nagios/nagios.cfg',
        '/opt/nagios/etc/nagios.cfg',
        '/opt/nagios/nagios.cfg',
        # icinga on debian/ubuntu
        '/etc/icinga/icinga.cfg',
        # icinga installed from source (default location)
        '/usr/local/icinga/etc/icinga.cfg',
        ]

```

##### EXPECTED RESULTS
I guess there are 2 options: 
1. allow to pass the 'location' or 'command_file' as the module argument
2. list the system running processes, find the config that is currently in use, get the info from the right config file.

**Comment by bcoca** [comment]
You already have that option `cmdfile` as per http://docs.ansible.com/ansible/nagios_module.html (3rd one down). If you do not supply it, it defaults to using the function you show.

**Comment by sirkubax** [comment]
#notabug

By looking at the code I've found the option that I somehow did not see in the spec :)

cmdfile

**Comment by sirkubax** [comment]
:) 'command' somehow override 'cmdfile' description when I was reading the docs :/

**Comment by sirkubax** [comment]
btw ^ how could we together close the same bug :) @bcoca

**Comment by bcoca** [comment]
github cluster race condition
