### ISSUE TITLE
More details on Variable Precedence documentation

### ISSUE THREAD

**Issue by craigfrancis** [ansible/ansible#21239]
##### ISSUE TYPE
Documentation Report

##### COMPONENT NAME
variable precedence

##### ANSIBLE VERSION
N/A

##### SUMMARY
The Variable Precedence list could do with some comments, to explain what the different variables are.

The comments could include links to find out more information.

http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

##### Suggestion
The list could be turned into a table, depending on the version of reStructuredText that is being used:

http://docutils.sourceforge.net/docs/user/rst/quickref.html#tables

##### Example

| No | Variable | Description |
| -- | --------- | ----------- |
| 01 | role defaults [1]     | [/path/to/role/x/defaults/main.yml](http://docs.ansible.com/ansible/playbooks_roles.html#role-default-variables) |
| 02 | inventory vars [2]    | [/path/to/inventory/hosts](http://docs.ansible.com/ansible/intro_inventory.html) |
| 03 | inventory group_vars   | /path/to/inventory/group_vars/group.yml |
| 04 | inventory host_vars    | /path/to/inventory/host_vars/host.yml |
| 05 | playbook group_vars    | ./group_vars/group.yml (relative to playbook). |
| 06 | playbook host_vars     | ./host_vars/host.yml (relative to playbook). |
| 07 | host facts             | [Remote host setup](http://docs.ansible.com/ansible/setup_module.html), typically collected when playbook starts (or [switched off](http://docs.ansible.com/ansible/playbooks_variables.html#turning-off-facts)). |
| 08 | play vars              | In the playbook, as [vars](http://docs.ansible.com/ansible/playbooks_variables.html#variables-defined-in-a-playbook). |
| 09 | play vars_prompt       | In the playbook, as [vars_prompt](http://docs.ansible.com/ansible/playbooks_prompts.html). |
| 09 | play vars_files        | In the playbook, as [vars_files](http://docs.ansible.com/ansible/playbooks_variables.html#variable-file-separation). |
| ---  |
| 10 | registered vars        | In the playbook, [registered by a task](http://docs.ansible.com/ansible/playbooks_variables.html#registered-variables). |
| 11 | set_facts              | In the playbook, [using set_fact](http://docs.ansible.com/ansible/set_fact_module.html). |
| 12 | role and include vars  | Either a [/path/to/role/x/vars/main.yml](http://docs.ansible.com/ansible/playbooks_roles.html#roles), or [vars: for an include](http://docs.ansible.com/ansible/playbooks_roles.html#task-include-files-and-encouraging-reuse). |
| 13 | block vars             | Only for tasks in block / Not really described in the [blocks documentation](http://docs.ansible.com/ansible/playbooks_blocks.html), and [may not be allowed](https://github.com/ansible/ansible/issues/11779#issuecomment-125957650). |
| 14 | task vars              | Only for the task / The individual variables that get passed to the module. |
| ---  |
| 15 | extra vars             | Always win precedence / Using [--extra-vars](http://docs.ansible.com/ansible/playbooks_variables.html#passing-variables-on-the-command-line) from the command line. |

---

This list was created when raising issue #21205, where I found the "play vars" to be in an unexpected order.

**Comment by jctanner** [comment]
needs_contributor

**Comment by jctanner** [comment]
Just a side note: We also added a test script recently to ensure precedence stays consistent.

https://github.com/ansible/ansible/blob/devel/test/sanity/code-smell/ansible-var-precedence-check.py

The script might be useful to document writers because it shows how each "feature" is used in a playbook.

**Comment by Nowaker** [comment]
Also, it would be worth documenting the precedence of `-e` itself. For example:

```
echo 'var: c' > file.yml
ansible-playbook -e var=a -e var=b -e @file.yml -e var=d
```

Result: `d`

**Comment by acozine** [comment]
Since this issue was opened, we have added links for more information and a line to document the precedence of `-e` extra vars. For now we are not turning the list into a table, because of concerns about accessibility and responsive design.

Feel free to open a new issue with more ideas for optimizing the documentation on variable precedence!
