### ISSUE TITLE
'dict object' has no attribute 'stdout' 

### ISSUE THREAD

**Issue by prasanjit-** [ansible/ansible#21233]
Below is the snippet:

  - name: Get master log file from master host one
    shell: mysql -u root -e "show master status;" | grep -v 'File' | awk '{print $1}'
    when: inventory_hostname == 'master_one'
    register: mysql_log_one

  - name: Write to file
    shell:  echo "{{ master_two }} {{ slave_user }} {{ mysql_log_one.stdout }} {{ mysql_logpos_one.stdout }}"  > /tmp/test
    when: inventory_hostname == 'master_one'
Here, echoing to /tmp/test work fine. No errors are thrown by ansible about 'dict object' for {{ mysql_log_one.stdout }} .

But,
- name: Configure master one
shell: >
mysql -u root -NBe
'slave stop;CHANGE MASTER TO MASTER_HOST="{{ master_two }}", MASTER_USER="{{ slave_user }}", MASTER_PASSWORD="{{
your_pass }}", MASTER_LOG_FILE="{{ item }}";slave start;'
with_items: "{{ mysql_log_two.stdout }}"
when: inventory_hostname == 'master_one'
ignore_errors: True

does not work. mysql_log_two is another variable whose value is present!

Error msg:
TASK [Configure master one] ***************************************************
skipping: [master_two] => (item=mysql-bin.000066)
fatal: [master_one]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'stdout'"}
...ignoring

You can see (item=mysql-bin.000066) i.e. item is getting the value from mysql_log_two.stdout

**Comment by rcarrillocruz** [comment]
I need more context to see the issue.
Please put this in your play, before the 'Configure master one' task:

- debug: var=mysql_log_two
- debug: var=inventory_hostname

Re-run the play and paste the output, showing the two debugs and the 'Configure master one' outputs.

Thanks

**Comment by prasanjit-** [comment]
Thanks for your response.
The issue is understood now. When 'register' is used, the scope of the variable is respective of the inventory host, on which the task was run. 

name: Get master log file from master host one
shell: mysql -u root -e "show master status;" | grep -v 'File' | awk '{print $1}'
when: inventory_hostname == 'master_one'
register: mysql_log_one

That is, the scope of mysql_log_one is limited to  inventory_hostname 'master_one'.
what should be done, to extend the scope throughout my script, i.e. can i use this variable 'mysql_log_one' on other 'inventory_hostname' ? (How to copy to other variable?) .

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
