### ISSUE TITLE
port func-inventory to ansible

### ISSUE THREAD

**Issue by hhoffman** [ansible/ansible#2124]
Hi,
I was speaking to mdehaan on IRC about how having a func-inventory like script in ansible would be great!
Cheers,
Harry

**Comment by mpdehaan** [comment]
probably not going to happen soon, so closing.

if someone wants to do this, go ahead!

**Comment by skvidal** [comment]
isn't func-inventory more or less:

ansible all -m setup -t /some/path

b/c not all ansible modules have an inventory/show argument (many of them make no sense with that)

@hhoffman what is it you would want the output to include?

**Comment by mpdehaan** [comment]
it basically is all that and track each run to git.

And yeah, it was 200 lines of code before and now there is probably 20-30
to add this time :)

**Comment by skvidal** [comment]
Right - every module would need to have some way of dumping back certain facts.

OR

if there was a 'facts' namespace we could plug that full of modules and let something like 'inventory' run all of those and collect the data.

not sure if that is in your bigger plans for 'namespacing' of library modules or not but might be something to think about

**Comment by mpdehaan** [comment]
Oh yes...

That's not entirely standardized because they don't all have an
inventory=yes method

I like your namespacing plan better.

**Comment by skvidal** [comment]
I can open a new ticket for this idea to follow it out - but if you are okay with the idea of a fact namespace we could easily put things in there and, in order to maintain compatibility, use the facts namespace as an automatic lookup location.

so
ansible hostname -m setup

would still work - even if setup lived in facts/setup (or would that be facts.setup?)

anyway - if you have a version of the namespace concept in mind, lemme know.

**Comment by mpdehaan** [comment]
I am thinking namespaces are great, but that we should if no namespace was
given, search all of the namespaces until we find a match or something.

i.e. backwards compat is important.

But having a directory that is library/packaging/  or something seems to
make sense.

I suspect we'd have to change the docs system a small amount and would want
the website better organized, etc.

The other idea was to just have a 'category' field in the module doc, which
may or may not be good enough.

**Comment by skvidal** [comment]
I have no problems with searching through all paths provided we do something to manage namespace conflicts.

I'm thinking of an eventual future of things like:

I have namespaces for 'bsd' and 'solaris' and 'linux'

and a common module in all 3 namespaces
and the path search matches the bsd one first :(

simple pitfalls - but probably not uncommon ones.

**Comment by hhoffman** [comment]
Hi Guys,
So, there are two main reasons that I wanted a func-inventory like analog in ansible. The first was the ability to store the facts about a system in git so that I could diff over time and report against.
The second, and for me super valuable use,  was for use with the FileTracker module, in func, that would give me Tripwire-like functionality that would, again, store itself in git.

**Comment by bcoca** [comment]
ansible -m setup -t git_repo can give you the diffs you need, for tripwire
a task that does md5 and another that records it locally (or better yet,
callback) can be done easily.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno
