### ISSUE TITLE
The ConfigureRemotingForAnsible.ps1 script is currently broken

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#21248]
I just noticed this:
```
Self-signed SSL certificate generated; thumbprint: 373E6A40FE6D8199A7C1A76EE3CBCDC191D931EF
New-WSManInstance : The WinRM client cannot process the request. The Enhanced Key Usage (EKU) field of the certificate
is not set to "Server Authentication". Retry the request with a certificate that has the correct EKU.
```
Some of the recent changes to this script must have done something to how the script generates certs. 

The error happens (at least) on a vanilla 2012R2 box with PSv4.0.

If I rewind the repo to e64ef8b0ab2f062332e5b8b2f29cce27628ff851 everything works, so the bug must be in a commit later than that.

The pic shows 3 certs. The upper one is generated by the previous version of the prep script, the 2 next ones are generated by the current version.
[![2017-02-10 16_41_16-test-trond01.system.rikstv.n.png](https://s23.postimg.org/5uwwknowr/2017_02_10_16_41_16_test_trond01_system_rikstv_n.png)](https://postimg.org/image/79yh9dpzr/)

**Comment by jctanner** [comment]
ping @dagwieers @jborean93 @nitzmahone @jhawkesworth

**Comment by jhawkesworth** [comment]
I wonder if this is possibly related (picking up the wrong cert when there is already another cert in My)
https://github.com/ansible/ansible/issues/21155 ?

**Comment by nitzmahone** [comment]
Hrm, thought I'd "fixed"-closed this via the PR, but should be good now.
