### ISSUE TITLE
'gather_timeout' in configuration file is ignored in playbook/ansible

### ISSUE THREAD

**Issue by gen2saurus** [ansible/ansible#21261]
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME

gathering/setup
##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/.../ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

[default]
...
gathering = smart
gather_subset = !hardware
gather_timeout = 133
timeout = 111
...
##### OS / ENVIRONMENT

Ansible:
Linux 4.8.17-gentoo #1 SMP Wed Jan 11 15:29:00 GMT 2017 x86_64 Pentium(R) Dual-Core CPU E5300 @ 2.60GHz GenuineIntel GNU/Linux

Targets:
Linux 4.4.30-gentoo #1 SMP Thu Nov 3 13:21:09 UTC 2016 x86_64 Intel(R) Xeon(R) CPU L5420 @ 2.50GHz GenuineIntel GNU/Linux
##### SUMMARY

Neither playbook nor ansible does not use 'gather_timeout' and/or 'gather_subset' parameters from configuration file but 'ansible' accept them from command line.

##### STEPS TO REPRODUCE

```yaml
ansible Server.Name --become --ask-become-pass -m setup -vvvv #1.doesn't work
ansible Server.Name --become --ask-become-pass -m setup -vvvv -a "gather_subset=!hardware gather_timeout=122" #2.works
```

##### EXPECTED RESULTS

both 'gather_subset' and 'gather_timeout' must be set from configuration file if defined.
##### ACTUAL RESULTS

```
1st command above: Error message displayed ('gather_subset'='all','gather_timeout'=10 - both are default in spite of they are defined different in configuration file):

An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_CQYFkw/ansible_modlib.zip/ansible/module_utils/basic.py", line 2232, in run_command
    rfd, wfd, efd = select.select(rpipes, [], rpipes, 1)
  File "/tmp/ansible_CQYFkw/ansible_modlib.zip/ansible/module_utils/facts.py", line 88, in _handle_timeout
    raise TimeoutError(error_message)
TimeoutError: Timer expired

Server.Name | FAILED! => { "changed": false, 
    "cmd": "/bin/lsblk --list --noheadings --paths --output NAME,UUID --exclude 2", "failed": true, 
    "invocation": { "module_args": { "fact_path": "/etc/ansible/facts.d", "filter": "*",
            "gather_subset": ["all"], 
            "gather_timeout": 10  }, "module_name": "setup"  }, 
    "msg": "Timer expired", "rc": 257 }

2nd command above: Normal completion (gather_subset'=!hardware, 'gather_timeout'=122 as set in command line):
    "changed": false, "invocation": { "module_args": {"fact_path": "/etc/ansible/facts.d", "filter": "*", 
            "gather_subset": ["!hardware"], 
            "gather_timeout": 122 }, 
        "module_name": "setup" }
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The config settings are for the 'implicit' setup executed by playbooks, not explicit ones that you can execute as a task or using the adhoc mode.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by gen2saurus** [comment]
The main problem is with a playbook execution but I would suggest to use configuration file settings for adhoc mode too.

FYI: I provided the adhoc examples above for simplicity only.

This is the playbook `./update.yml` to reproduce the error:
```
#!/usr/bin/ansible-playbook
---
- name: apply configuration to all nodes
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - common
```
This playbook is started as`./update.yml --ask-sudo-pass -l ServerName --check --diff -vvvv`
and the error message is:
```An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_udX3zB/ansible_modlib.zip/ansible/module_utils/basic.py", line 2232, in run_command
    rfd, wfd, efd = select.select(rpipes, [], rpipes, 1)
  File "/tmp/ansible_udX3zB/ansible_modlib.zip/ansible/module_utils/facts.py", line 88, in _handle_timeout
    raise TimeoutError(error_message)
TimeoutError: Timer expired

fatal: [ServerName]: FAILED! => {
    "changed": false, 
    "cmd": "/bin/lsblk --list --noheadings --paths --output NAME,UUID --exclude 2", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "fact_path": "/etc/ansible/facts.d", 
            "filter": "*", 
            "gather_subset": [
                "all"
            ], 
            "gather_timeout": 10
        }, 
        "module_name": "setup"
    }, 
    "msg": "Timer expired", 
    "rc": 257
}
```
FYI: The `lsblk` command execution time is 20..120s  for these group of servers since they have CD drives installed.

NB: Configuration file is the same as in my first message above.
