### ISSUE TITLE
unarchive does not work for .zip file on ansible 2.2.1 on windows Environment

### ISSUE THREAD

**Issue by ksrajith** [ansible/ansible#21280]
**Issue Type:**

Bug Report

**Ansible Version:**
$ ansible --version
ansible 2.2.1.0 (stable-2.2 39acdde5aa) last updated 2017/02/08 16:41:08 (GMT +650)
  lib/ansible/modules/core: (detached HEAD 59c9a6d3c2) last updated 2017/02/08 16:42:29 (GMT +650)
  lib/ansible/modules/extras:  not found - use git submodule update --init lib/ansible/modules/extras
  config file =
  configured module search path = ['/opt/ansible/library']

**Environment**:
    setup ansible using cygwin on windows 8.
    Setup as per the below url:
[http://everythingshouldbevirtual.com/ansible-using-ansible-on-windows-via-cygwin](url)

**Summary**:
unarchive feature does not work for me in windows. but the **same script works fine in ubuntu**.

**Steps to reproduce**: 
Playbook role:
`ansible-playbook dep.yml`

`- name: extracting files
       unarchive:
         src: /mnt/ansible-mig/repo/product-ids/modules/distribution/target/SNAPSHOT.zip
         dest: /mnt/ansible-mig/repo/product-ids/modules/distribution/target
         copy: no `

**Expected Results:**
unarchive to the destination with no errors

**Actual results:**

`TASK [extacting files] *********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to find handler for \"/mnt/ansible-mig/repo/product-ids/modules/distribution/target/SNAPSHOT.zip\". Make sure the required command to extract the file is installed. Command \"/usr/bin/tar\" could not handle archive. Command \"unzip\" not found."}
`

**Comment by jhawkesworth** [comment]
Sorry, cygwin is not supported - as stated here: http://docs.ansible.com/ansible/intro_windows.html#reminder-you-must-have-a-linux-control-machine

If you are targetting windows, set up the windows support as per http://docs.ansible.com/ansible/intro_windows.html and use win_unzip module for zip files.

**Comment by ksrajith** [comment]
Hi,
I have run below commands on cygwin and now the same script works for my windows setup.
Please let me is this ok to continue.

cd C:\cygwin64
wget rawgit.com/transcode-open/apt-cyg/master/apt-cyg
install apt-cyg /bin
apt-cyg install unzip
