### ISSUE TITLE
Docs: Add version selector for ansible core and module documentation

### ISSUE THREAD

**Issue by mightydok** [ansible/ansible#21283]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
Ansible core and all modules

##### ANSIBLE VERSION
all

##### SUMMARY
Documentation at http://docs.ansible.com/ dont allow to choose version, but sphinx and RTD have that options: http://joxi.ru/RmzQPL3teMvKrO

**Comment by bcoca** [comment]
closing as dupe of #13858
