### ISSUE TITLE
add a visudo module

### ISSUE THREAD

**Issue by legrostdg** [ansible/ansible#2129]
It would be great to have a visudo module to check if a local sudoers file is correct before updating it.

**Comment by mpdehaan** [comment]
I agree!

**Comment by jpmens** [comment]
So do I #facepalm

**Comment by jpmens** [comment]
BTW @legrostdg I'm doing something like this at the moment:

```
action: template src=xxx dest=/etc/sudoers.tmp
action: shell visudo -q -c -f /etc/sudoers.tmp && cp /etc/sudoers.tmp /etc/sudoers
```

which at least ensures I can't installed a broken sudoers.

**Comment by mpdehaan** [comment]
That would be good on coderwall, BTW!

**Comment by jpmens** [comment]
https://coderwall.com/p/tqeebw

**Comment by mpdehaan** [comment]
I think we should just use the above tip.

**Comment by legrostdg** [comment]
I don't totally agree with you, for example the above tip does not check if the file has changed or not (thus, the task will always appear as "changed", which is quite annoying). Maybe you could keep this bug open and add a tag "feature request"?

**Comment by mpdehaan** [comment]
I don't really keep a lot of feature requests open when I'm not going to be
implementing them :)

Patches would be considered though!

**Comment by gomox** [comment]
FFR, Ansible 1.2 introduced a "validate" parameter to the copy action that solves this use case nicely. The documentation even has an example.
http://www.ansibleworks.com/docs/modules.html/#copy

**Comment by bcoca** [comment]
works for templates also.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by techtonik** [comment]
http://docs.ansible.com/copy_module.html#examples
