### ISSUE TITLE
Incorrect python interpreter on local connection 

### ISSUE THREAD

**Issue by gzm55** [ansible/ansible#21311]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When a normal python-module task (e.g., `command`, `setup`, `shell`, `expect` and etc.) is called and delegated to another host, the module should be interpreted by the `{{ansible_python_interpreter}}` of the host which is delegated to, not by the one of `{{inventory_host}}`. Especially, when a task is set 'connection: local', we could try to use current  python running ansible. But now, it is always using ansible_python_interpreter of `{{inventory_host}}`.

More precisely, for a delegating python-task, we should try python interpreter in the following order:
1. hostvars[host-delegated-to].ansible_python_interpreter if set
2. if host-delegated-to == localhost, try `sys.executable` from python code
3. default /usr/bin/python

##### STEPS TO REPRODUCE
```bash
$ cat inv
github.com ansible_python_interpreter=/python/on/remote/host
```

```yaml
# pl.yml
---
- hosts: github.com
  gather_facts: False
  tasks:
  - shell: readlink /proc/$PPID/exe
    connection: local
    register: python_of_module
  - debug: msg="python of module={{python_of_module.stdout}}"
  - name: test for python modules
    expect:
      command: readlink /proc/$PPID/exe
      responses:
        xxx: ''
```

```bash
virtualenv test-python
test-python/bin/pip install pexpect>=3.3
test-python/bin/python -vvvv `which ansible-playbook` -i inv pl.yml
```

##### EXPECTED RESULTS
job success, and output message contains:

python of module=test-python/bin/python

##### ACTUAL RESULTS
```
TASK [command] *****************************************************************
task path: /root/pl.yml:5
Using module file /test-python/lib/python2.7/site-packages/ansible/modules/core/commands/command.py
<github.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<github.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1486905383.61-188129853926372 `" && echo ansible-tmp-1486905383.61-188129853926372="` echo ~/.ansible/tmp/ansible-tmp-1486905383.61-188129853926372 `" ) && sleep 0'
<github.com> PUT /tmp/tmprm2Qm7 TO /root/.ansible/tmp/ansible-tmp-1486905383.61-188129853926372/command.py
<github.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1486905383.61-188129853926372/ /root/.ansible/tmp/ansible-tmp-1486905383.61-188129853926372/command.py && sleep 0'
<github.com> EXEC /bin/sh -c '/python/on/remote/host /root/.ansible/tmp/ansible-tmp-1486905383.61-188129853926372/command.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1486905383.61-188129853926372/" > /dev/null 2>&1 && sleep 0'
fatal: [github.com]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "command"
    }, 
    "module_stderr": "/bin/sh: /python/on/remote/host: not found\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}
	to retry, use: --limit @/root/pl.retry

```

**Comment by sivel** [comment]
`connection: local` does not perform delegation, you are strictly overriding the connection for the remote host.

To delegate to localhost and use the interpreter for localhost you should use `delegate_to: localhost`

**Comment by gzm55** [comment]
@sivel 
Hi,  after testing with 'delegate_to: localhost', almost everything works, except that:

if `localhost` is not present in the inventory file, the shell will be run by the same python executable as ansible, but if present, the default '/usr/bin/python' will be used because hostvars['localhost']['ansible_python_interpreter'] is not defined.

Here, I think we should always try the same python executable as ansible first, (i.e., `sys.executable`), just as what ` _create_implicit_localhost` do.

**Comment by sivel** [comment]
When supplying `localhost` explicitly in your inventory, it is assumed that you are doing so with the understanding that you are overriding the implicit localhost.  By default all hosts listed in inventory, that do not supply `ansible_python_interpreter` use a default value of `/usr/bin/python`.

In some regards this information is being documented in https://github.com/ansible/ansible/pull/20534

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
