### ISSUE TITLE
The `with_file` iterator explanation should be clear in the documentation.

### ISSUE THREAD

**Issue by gideon-maina** [ansible/ansible#21325]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
Docs

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### OS / ENVIRONMENT
```
MAC OS 
```

##### SUMMARY
I think the `with_file` explanation in the loops documentation page should add that, `with_files` only reads files from  the host ansible script is being initiated from not the remote host. This will make it clearer. What is there now is very ambiguos as this the content, I quote 
```
with_file iterates over the content of a list of files, item will be set to the content of each
 file in sequence. It can be used like this:...
```

**Comment by bcoca** [comment]
It is not only with_file, all lookups run on the host, this is documented already.

Here is the fact that `with_` X is actually a lookup:
http://docs.ansible.com/ansible/playbooks_loops.html#standard-loops

And here you have the docs on lookups always executing on the controller:
http://docs.ansible.com/ansible/playbooks_lookups.html
