### ISSUE TITLE
ec2.ini file causes ec2.py to fail because it doesn't recognize ap-south-1

### ISSUE THREAD

**Issue by sujan46** [ansible/ansible#21334]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
contrib/inventory/ec2.py

##### ANSIBLE VERSION
ansible 2.0.0.2

##### CONFIGURATION
$ export AWS_ACCESS_KEY_ID='YOUR_AWS_API_KEY'
$ export AWS_SECRET_ACCESS_KEY='YOUR_AWS_API_SECRET_KEY'
$ export ANSIBLE_HOSTS=/etc/ansible/ec2.py 
$ export EC2_INI_PATH=/etc/ansible/ec2.ini 

##### OS / ENVIRONMENT

xubuntu 16.04 LTS

##### SUMMARY
 When running ec2 script getting the below error
region name: ap-south-1 likely not supported, or AWS is down.  connection to region failed

##### STEPS TO REPRODUCE

Run the ec2.py script with default ec2.ini config file,With instance lauched in aws mumbai region.

```yaml

```

##### EXPECTED RESULTS
When running ec2.py --list.
It should list the instances in ap-south-1 region(Mumbai)

##### ACTUAL RESULTS

While running ec2.py script it should list instanses in ap-south-1(Mumbai)

```

```

**Comment by rangapv** [comment]
Hi,
Could you mention the steps need to fix this issue of us-east-2 missing in ec2.py --list .
I am not able to follow the steps needed to fix this. My understanding is use boto3 instead ? or update the endpoints.json ? . Whichever it is kindly mention the steps.
Thanks and Happy New Year
Ranga
