### ISSUE TITLE
service module doesn't accept '1' as a valid return code for a non-running service under LSB guidelines

### ISSUE THREAD

**Issue by knightlabs** [ansible/ansible#2133]
http://refspecs.linuxbase.org/LSB_4.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html indicates that a return code of 1 is valid for a non-running service with a pidfile. 

Since service accepts 2 as a valid response for a non-running service with a lockfile, it seems that it should accept 1 as well.

I'll work on getting a pull request together if this is deemed a valid issue.

**Comment by mpdehaan** [comment]
Agreed, +1

**Comment by mpdehaan** [comment]
fixed just now.   See my post to the list about other tweaks to the service module.

**Comment by knightlabs** [comment]
++
