### ISSUE TITLE
hardcoding #!/usr/bin/python breaks modules

### ISSUE THREAD

**Issue by rohni** [ansible/ansible#2134]
I was introduced to ansible by a colleague, and have been using it to provision some joyent machines (smartos).

Smartos uses pkgin, and there is a module for it, so I used it, but it failed with the error that /usr/lib/python could not be found.  And sure enough this is true, because the joyent/smartos machines have python under /opt/local.  However something that should work all the time: 
# !/usr/bin/env python -tt

Could this please be replaced in the pkgin module, in fact in all the modules where this is to be found?

Thanks, 

Rohan

P.S. Let me know if this should be a pull request, because I will be happy to create one.

**Comment by dhozac** [comment]
The interpreter is replaced when the module is copied to the destination system based on the setting of ansible_python_interpreter. If all you are managing are SmartOS machines, you might put something like

```
[all:vars]
ansible_python_interpreter=/opt/local/bin/python
```

in your hosts file to make that apply to all of them. If not, group as you see fit and set the variable where it makes sense.

**Comment by mpdehaan** [comment]
Note that we need to make this abundantly more obvious in the docs.   I
believe we only talked about it in the context of multiple pythons.

**Comment by rohni** [comment]
@dhozac Thanks, that is a very nice flexible system. 
@mpdehaan I agree, it is pretty easy to miss, and it never occurred to me that the python interpretor would be something settable in the vars.  Of course, thinking about it in retrospect, it would make sense.

**Comment by mpdehaan** [comment]
I'm filing a ticket to better explain it in the docs.   Thanks!
