### ISSUE TITLE
syntax-check not checking everything

### ISSUE THREAD

**Issue by minac** [ansible/ansible#21349]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

syntax-check

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /Users/minac/Documents/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```
[defaults]
host_key_checking = False
callback_whitelist = profile_tasks
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
retry_files_enabled = False
squash_actions = apk,apt,dnf,package,pacman,pkgng,yum,zypper
```

##### OS / ENVIRONMENT
macOS Sierra

##### SUMMARY
Trying to use syntax-check to cover all the plays in my playbook. If a task has an incorrect name it's picked up, but if there is a comma in between the arguments of a task, there is no warning.

##### STEPS TO REPRODUCE
ansible-playbook --syntax-check -i myhosts ./ansible/playbook.yml

```yaml
- name: Ruby - Install bundler gem
  gem: 
    name=bundler
    state=latest, 
    user_install=no 
```

##### EXPECTED RESULTS
I expected an error, like the one that happens if there is a problem like the following:
```
- name: Ruby - Install bundler gem
  gem**i**: 
    name=bundler
    state=latest 
    user_install=no 
```

##### ACTUAL RESULTS
```
$ ansible-playbook --syntax-check -i myhosts ./ansible/playbook.yml -vvv
Using /Users/minac/Documents/ansible.cfg as config file
...
statically included: /Users/minac/Documents/ansible/roles/ansible-rbenv-role/tasks/apt_build_depends.yml
...
1 plays in ./ansible/playbook.yml

playbook: ./ansible/playbook.yml
```

**Comment by bcoca** [comment]
Sadly this is a known limitation, task options are checked by the modules themselves, the syntax checker cannot run the modules as they might not have the requirements available on the 'controller'.

If you want stricter syntax checking I recommend you use the YAML format instead of k=v, specially if you are doing multiline.

**Comment by minac** [comment]
Thanks for the clarification @bcoca
