### ISSUE TITLE
File module: state=touch on a file returns changed even if nothing is change

### ISSUE THREAD

**Issue by wawrzek** [ansible/ansible#21342]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

standard module: file
##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### SUMMARY

For  file 'state=touch' in module file Ansible returns state changed if file exist, even if nothing has been changed. 

##### STEPS TO REPRODUCE

Apply following on any {{ sudo_path }}

```yaml
- name: Ensure sudo devs file has right ownership
  file: path="{{ sudo_path }}" state=touch mode=440 owner=root group=root

```
If the file doesn't exists it's going to be created. During following runs nothing is changed but Ansible returns state changed. It's because state is changed from 'file' to 'touch'. I think part of the  problem can be address by https://github.com/ansible/ansible/issues/19378

Ideal state=file should create file it such doesn't exist. Current implementation (separation of 'touch' from 'file') doesn't make any sense.

BTW. I need this file to fill it with 'lineinfile', so using template of copy is not so easy. Probably, i could use temaplate, but it would make the whole thing very complicated.

##### ACTUAL RESULTS

```
test-node1.example.com | SUCCESS => {
    "changed": true,
    "dest": "/etc/sudoers.d/80-devs",
    "diff": {
        "after": {
            "path": "/etc/sudoers.d/80-devs",
            "state": "touch"
        },
        "before": {
            "path": "/etc/sudoers.d/80-devs",
            "state": "file"
        }
    },
    "gid": 0,
    "group": "root",
    "invocation": {
        "module_args": {
            "backup": null,
            "content": null,
            "delimiter": null,
            "diff_peek": null,
            "directory_mode": null,
            "follow": false,
            "force": false,
            "group": "root",
            "mode": "0440",
            "original_basename": null,
            "owner": "root",
            "path": "/etc/sudoers.d/80-devs",
            "recurse": false,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "touch",
            "unsafe_writes": null,
            "validate": null
        },
        "module_name": "file"
    },
    "mode": "0440",
    "owner": "root",
    "size": 483,
    "state": "file",
    "uid": 0
}
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

By it's own nature touch is **always** a change, if the file exists it updates the access time.

Thank you once again for this and your interest in Ansible!

**Comment by JoelFeiner** [comment]
There should be an option to create a file if it doesn't exist, update the mode and ownership if it does (and they need to be changed), and otherwise leave it alone. As it is, "touch" is never idempotent.

**Comment by mwellnitz** [comment]
there is a workaround that fits my needs:
- name: create my_file
  file: 
    path: my_file 
    state: touched
  register: my_file_is_touched
  changed_when: "my_file_is_touched.diff.before.atime == my_file_is_touched.diff.before.mtime"

at least in linux: access time is changed when file was touched modification time _not_
In case of file is created during touch both timestamps will be the same
