### ISSUE TITLE
command module modifications (mpdehaan)

### ISSUE THREAD

**Issue by fdavis** [ansible/ansible#2136]
Hello,

Just a reminder for the rc_ok, rc_change, rc_failed additions to the command module.

refers to #2045 

Thanks again Michael. :)

**Comment by mpdehaan** [comment]
I have merged this ticket with the above tickets, see also comments on those tickets for things we should consider when implementing this feature-set.

**Comment by mpdehaan** [comment]
this is no longer something actively in my queue.  I'd accept implementations of this though specifying what ranges correspond to which states seem fiddly.

ignore_errors: True seems nicer and then actions can use "when_integer" to replace changed behavior.
