### ISSUE TITLE
Revisit Pull Request for raw module

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#214]
Reason of managing routers is quite useful

https://github.com/ansible/ansible/pull/201#issuecomment-5299751

**Comment by mpdehaan** [comment]
Hi acasajus, sorry for the delay.

This is now merged in to the devel branch and I've shared this with the mailing list.  I'll add it to the documentation shortly.

In addition to this, I've eased the dependency on the file module needing JSON, so you can now use copy/template to install an yum.repos.d file as well, making it easy to install dependencies before invoking yum via the raw module.

Details on the mailing list.

Thanks very much for this, this will be very helpful for lots of people!

**Comment by acasajus** [comment]
:)
