### ISSUE TITLE
Misleading error: "UNREACHABLE!" when host actually is reachable

### ISSUE THREAD

**Issue by dmuth** [ansible/ansible#21431]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
This happens in both ansible-playbook from the OS/X *and* Ansible Tower run from the Vagrant VM

##### ANSIBLE VERSION

```
ansible-playbook 2.1.2.0
```

##### CONFIGURATION
```
[defaults]
inventory = ./inventory
roles_path = ./roles

[privilege_escalation]
#
# Run everything as root.
#
become = yes

##### OS / ENVIRONMENT
Mac OS/X
Vagrant image for Ansible Tower
<!---
Mention the OS you are running Ansible from, and the OS you are
managing, or say “N/A” for anything that is not platform-specific.
-->

##### SUMMARY
If I screw up the SSH key and don't have the right one loaded, I get this error:
```
fatal: [96.119.XXX.XXX]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
```


##### STEPS TO REPRODUCE
Use a "hello world" playbook, SSH key authentication, but use the wrong SSH key.

The default "hello world" playbook with Tower is sufficient to make this happen.

<!--- You can also paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
A more informative error message that said "login denied" or similar.

##### ACTUAL RESULTS

I saw the "unreachable" message appear in Tower about 10-15 seconds, which made me suspect a network timeout.  This ended up sending me down a rabbit hole where I was checking network connectivity with netcat, jptables, traceroutes, etc. to try and track down the source of the problem.

```
$ ansible-playbook -i ./inventory ./playbooks/ping.yaml --limit 96.119.XXX.XXX

PLAY [Ping all hosts] **********************************************************

TASK [setup] *******************************************************************
fatal: [96.119.XXX.XXX]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
        to retry, use: --limit @/Users/REDACTED/development/ansible-demo/playbooks/ping.retry

PLAY RECAP *********************************************************************
96.119.XXX.XXX               : ok=0    changed=0    unreachable=1    failed=0  
```

**Comment by bjolivot** [comment]
+1

**Comment by 7hr1LL** [comment]
+1

**Comment by samdoran** [comment]
When a host is unreachable, Ansible was unable to create a connection. In order to see more details on the connection failure, run with `-vvv`.
