### ISSUE TITLE
ERROR:ImportError: No module named ansible.runner

### ISSUE THREAD

**Issue by kangshao** [ansible/ansible#2144]
Hi
when I test :#ansible localhost -m ping,return information:
Traceback (most recent call last):
  File "/usr/bin/ansible", line 25, in <module>
    from ansible.runner import Runner
ImportError: No module named ansible.runner

os:Red Hat Enterprise Linux Server release 6.2 x86_64
Python 2.6.8
how can i fix this problem,thx！

**Comment by kangshao** [comment]
ps：
ansible 1.1

**Comment by cyrusdavid** [comment]
Closing the issue without telling how you solved the problem?

**Comment by mpdehaan** [comment]
It was closed by the person filing the issue (and 6 months ago), so that seems totally fine to me if he didn't mean to file it.  

If you are seeing this problem you don't have ansible installed.

If you wish to run from checkout, just "source ./hacking/env-setup" or otherwise install it.
