### ISSUE TITLE
Ansible windows connection in the domain 

### ISSUE THREAD

**Issue by zdong08** [ansible/ansible#21451]
**ansible version** 
ansible 2.2.0.0
**hosts file**
[windows]
gm03v-xxx.cn
[windows:vars]
ansible_ssh_user='xxxxx@xx-SVC.CN'
ansible_ssh_port=5986
ansible_connection='winrm'
ansible_winrm_server_cert_validation=ignore

 **executing orders**

ansible windows   -i hosts   -m win_ping -k
gm03v-xxx.cn| UNREACHABLE! => {
    "changed": false, 
    "msg": "kerberos: authGSSClientInit() failed: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('', 100004)), ssl: the specified credentials were rejected by the server", 
    "unreachable": true
}

The reason is that the Kinit xxxxx@xx-SVC.CN must be executed first and then the command is passed
gm03v-xxx.cn | SUCCESS => {
    "changed": false, 
    "invocation": {
        "module_name": "win_ping"
    }, 
    "ping": "pong"
}

I would like to ask if you can only enter a password on it (the original is the need to enter the two input in the Kinit once, when the ansible input)？

**## Question two：**
Ansible can be used in a workgroup through a winrm 5985 port connection, which is not available in the domain. Why should it be used in the domain with a 5986?

**Comment by jhawkesworth** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
