### ISSUE TITLE
junit callback plugins output results in confusing xml output

### ISSUE THREAD

**Issue by hogarth-sv** [ansible/ansible#21461]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
junit

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
Enable the junit callback plugin:
```
callback_whitelist = junit
```

##### SUMMARY
The resulting xml from the callback plugin has a confusing class in each package which makes reading the output much harder than it should be.

##### STEPS TO REPRODUCE
Enable the junit plugin and run any playbook. View the junit results, or use a parser like the jenkins (or similar CI) junit plugins.

##### EXPECTED RESULTS
A package (or class) with all the tests when parsing the output such as:
```xml
<testcase classname="/srv/ansible/ansible_role_jenkins/tasks/add_signature_whitelist" name="[localhost] test-ci-jenkins: ansible_role_jenkins : check if signature whitelisted password={{ jenkins_admin_pass }}, user={{ jenkins_admin_user }}, args={u'signature': u'{{ item }}'}, script={{ jenkins_groovy_check_signature_approval }}" time="0.326584">
			<system-out>{
&quot;changed&quot;: false, 
&quot;output&quot;: &quot;Result: false\n&quot;
}</system-out>
		</testcase>
		<testcase classname="/srv/ansible/ansible_role_jenkins/tasks/add_signature_whitelist" name="[localhost] test-ci-jenkins: ansible_role_jenkins : add signature to whitelist password={{ jenkins_admin_pass }}, user={{ jenkins_admin_user }}, args={u'signature': u'{{ item }}'}, script={{ jenkins_groovy_add_signature_approval }}" time="0.305978">
			<system-out>{
&quot;changed&quot;: true, 
&quot;output&quot;: &quot;&quot;
}</system-out>
		</testcase>
```

##### ACTUAL RESULTS

The XML output results in a package of ""/srv/ansible/ansible_role_jenkins/tasks/add_signature_whitelist" and then two classes within it of yml:1 and yml:9 with the different tasks within that. This makes trying to look at results or durations of multiple plays very painful.

```xml
<testcase classname="/srv/ansible/ansible_role_jenkins/tasks/add_signature_whitelist.yml:1" name="[localhost] test-ci-jenkins: ansible_role_jenkins : check if signature whitelisted password={{ jenkins_admin_pass }}, user={{ jenkins_admin_user }}, args={u'signature': u'{{ item }}'}, script={{ jenkins_groovy_check_signature_approval }}" time="0.326584">
			<system-out>{
&quot;changed&quot;: false, 
&quot;output&quot;: &quot;Result: false\n&quot;
}</system-out>
		</testcase>
		<testcase classname="/srv/ansible/ansible_role_jenkins/tasks/add_signature_whitelist.yml:9" name="[localhost] test-ci-jenkins: ansible_role_jenkins : add signature to whitelist password={{ jenkins_admin_pass }}, user={{ jenkins_admin_user }}, args={u'signature': u'{{ item }}'}, script={{ jenkins_groovy_add_signature_approval }}" time="0.305978">
			<system-out>{
&quot;changed&quot;: true, 
&quot;output&quot;: &quot;&quot;
}</system-out>
		</testcase>

```

I have worked around this in my jenkins instances by doing a `sed -E 's/\.yml:[0-9]+//' results/*.xml`  before recording the result output and have confirmed that all the tests then appear under a package of "root" and the class matches the actual task being included, with tests per task within that so merely chomping the .yml:[0-9]+ from the classname generated makes a huge difference.

**Comment by mattclay** [comment]
@hogarthj Can you elaborate more on why having the line number from the playbook in the class name is causing problems for you?

We use the callback for our CI system (Shippable), and having the full file path and line number is useful for tracking down where in a playbook the failure has occurred.

**Comment by hogarth-sv** [comment]
Sure ... I've taken some screenshots to show the current UX journey and the proposed one from the patch to make it clearer what I mean.

Current:

1) Initial screen of the report, the setup and each yaml file in tasks is a package:

https://fedorapeople.org/~jhogarth/junit_ansible_jenkins/ux-journey-current/Screenshot%20from%202017-02-15%2021-05-02.png

2) Enter one of these and just get a class of yml:<lineno> which is very opaque as to what it is:

https://fedorapeople.org/~jhogarth/junit_ansible_jenkins/ux-journey-current/Screenshot%20from%202017-02-15%2021-05-18.png

3) Enter this oddly named class to get the actual test:

https://fedorapeople.org/~jhogarth/junit_ansible_jenkins/ux-journey-current/Screenshot%20from%202017-02-15%2021-06-05.png

Patched:

1) The initial screen has everything in a single root package:

https://fedorapeople.org/~jhogarth/junit_ansible_jenkins/ux-journey-proposed/Screenshot%20from%202017-02-15%2021-07-10.png

2) The class names are each yaml file in tasks:

https://fedorapeople.org/~jhogarth/junit_ansible_jenkins/ux-journey-proposed/Screenshot%20from%202017-02-15%2021-07-16.png

3) The tests generated from each yaml in tasks are all kept together so can view the duration and state of everything in a given yaml file at once:

https://fedorapeople.org/~jhogarth/junit_ansible_jenkins/ux-journey-proposed/Screenshot%20from%202017-02-15%2021-07-22.png

Note that if one of those failed it'd be easy to see where the failure is in that last entry and the stdout that gets recorded in the junit xml would be visible too to track down the problem.

**Comment by mattclay** [comment]
It appears the main issue is due to the `.` for the file extension in the class name. That makes sense, since Jenkins probably expects the class name to have `.` separated namespaces.

I'd be curious to see what it looks like if the class name was modified as follows:

- Either drop the file extension, or replace the `.` with `_`
- Drop the leading `/`
- Replace the remaining `/` with `.`

I'd expect that to result in a tree you could navigate down to the individual playbooks, with the playbook names being `filename:line_number` or `filename_extension:line_number`, depending on which you implemented.

If you don't care about the line numbers, you could drop that as well.

**Comment by hogarth-sv** [comment]
RIght - from the perspective of junit visualization tools with classname anything prior to the final '.' would be the package the class is in with that final bit being the class itself, since that's how java formats the fully qualified class names for imports etc 

The / doesn't matter from the perspective of this as it's not used a separator in java.

**Comment by karunakar1122** [comment]
Hi Hogarthj,
I have a requirement to generate junit format reports in ansible.
Can you please let me know what is the configurations needed?

**Comment by karunakar1122** [comment]
I added callback_whitelist = junit inside ansible.cfg file and junit_xml python lib installed but not generating junit xml output
