### ISSUE TITLE
local_action task ignores when: var is not defined

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#21486]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- Lineinfile 

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /some/path/to/.ansible.cfg
  configured module search path = Default w/o overrides

```

##### CONFIGURATION

```
[defaults]
inventory=~/ansible/hosts
roles_path=~/ansible/roles
```
##### OS / ENVIRONMENT

OS X 10.11.6

##### SUMMARY

I have a local action that should only be executed if a variable is defined but the task complains that the variable is undefined
##### STEPS TO REPRODUCE

 ```
ansible_playbook -vvv  -i ansible/hosts --extra-vars="rails_env=staging" ansible/pb.setup.yml
```

```
Note that the variable excludes is undefined when the playbook gets here...
post_tasks:
    - name: 'add to excludes '
      local_action: lineinfile dest="{{playbook_dir}}/rsync_exclude" line="{{ item }}"
      with_items:
        "{{excludes}}"
      when: excludes is defined

```

##### EXPECTED RESULTS

when excludes is not defined I would expect the task 'add to excludes' to be skipped

##### ACTUAL RESULTS

TASK [add to excludes] *********************************************************
task path: /some/path/to/ansible/pb.setup.yml:45
fatal: [myhost.mydomain]: FAILED! => {
    "failed": true, 
    "msg": "'excludes' is undefined"
}

```

```

**Comment by krzysztof-magosa** [comment]
`when` is applied for every iteration of loop and not to entire task at once.
Set `excludes` to empty list (`[]`) in role defaults or directly in code like that `with_items: "{{ excludes | default([]) }}"`. Then you can remove `when` line.

**Comment by bcoca** [comment]
closing as per above

also here are the docs that also state this http://docs.ansible.com/ansible/playbooks_conditionals.html#loops-and-conditionals

**Comment by ghost** [comment]
Thanks!,
