### ISSUE TITLE
things to make sure we have documented

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#2154]
(A)

Conditional includes and how they work

```
- include: ...
  only_if: ...
  (and also when_?)
```

new in ___

(A.1)

Specifying tags on an include line.

(B)

  the environment keyword, new in 1.1, with an enable of how we handle proxies.  Be sure any other references to proxies are removed and reference this keyword.

**Comment by dhozac** [comment]
(A) also does when_, but only works for task includes. New in 1.0.

```
- include: foo.yaml
  vars:
    foo: bar
```

is also undocumented.

I think include + with_items is also missing, or at least I couldn't find it earlier today.

**Comment by mpdehaan** [comment]
various other new 1.1 things:

check mode (--check)

diff

complex args

the environment keyword for proxy usage

**Comment by mpdehaan** [comment]
Adding most of this stuff now, @dhozac do you have an example of using include + with_items that would help someone understand why they may want to use it?

**Comment by dhozac** [comment]
I typically use it for things like setting up users. I usually have a few tasks for it, so they go in a tasks/user.yml file, and then

```
tasks:
- include: tasks/user.yml user=$item
  with_items: $users
```

Typically you'd have at least something like the following in tasks/user.yml

```
---
- name: ensure user ${user.username} exists
  action: user state=present name=${user.username} password=${user.password}
- name: install authorized keys for ${user.username}
  action: authorized_key state=present user=${user.username} key="${user.sshkey}"
```

I do something similar with tomcat instances, putting the required tasks in a file and just deploy them from a list of required instances.

**Comment by mpdehaan** [comment]
Thanks, I'll get this added.

**Comment by mpdehaan** [comment]
pushed a ton of doc additions and updated the list.   Included a pretty long section in advanced playbooks about how the above works especially.
