### ISSUE TITLE
ansible 2.1.1  use api run playbook can not use paramiko_ssh connection plugin

### ISSUE THREAD

**Issue by colynn** [ansible/ansible#21554]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
plugin:  paramiko_ssh

##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Use ansible 2.1.1 api, didn't specific ansible.cfg and ANSIBLE_* environment variables.

##### OS / ENVIRONMENT
Centos 6, N/A

##### SUMMARY

If defined connection is 'paramiko', when running module, it will see the error as below

Traceback (most recent call last):
  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 124, in run
    res = self._execute()
  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 448, in _execute
    result = self._handler.run(task_vars=variables)
  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/plugins/action/script.py", line 43, in run
    tmp = self._make_tmp_path(remote_user)
  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 218, in _make_tmp_path
    result = self._low_level_execute_command(cmd, sudoable=False)
  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 718, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 251, in exec_command
    super(Connection, self).exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/plugins/connection/__init__.py", line 51, in wrapped
    self._connect()
  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 139, in _connect
    self.ssh = SSH_CONNECTION_CACHE[cache_key] = self._connect_uncached()
  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 210, in _connect_uncached
    sock_kwarg = self._parse_proxy_command(port)
  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 151, in _parse_proxy_command
    args = self._split_ssh_args(' '.join(ssh_args))
TypeError: sequence item 0: expected string, NoneType found

##### STEPS TO REPRODUCE

1>  download three files on the same level directory
    ansible-2.1-paramiko-api-bug, 
    site.yml
    hosts 

2> run ansible-2.1-pramiko-api-bug
   will see the errors.

example-playbooks and hosts and api-examle, get them from gist.
https://gist.github.com/colynn/c033e9ab98e27c8e9f8c38dd1709ce08

##### EXPECTED RESULTS
The correct use of this  paramiko_ssh plug.

##### ACTUAL RESULTS

TASK [command: echo key1] ***************************************************
{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 124, in run\n    res = self._execute()\n  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 448, in _execute\n    result = self._handler.run(task_vars=variables)\n  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 33, in run\n    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))\n  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 591, in _execute_module\n    tmp = self._make_tmp_path(remote_user)\n  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 218, in _make_tmp_path\n    result = self._low_level_execute_command(cmd, sudoable=False)\n  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 718, in _low_level_execute_command\n    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)\n  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 251, in exec_command\n    super(Connection, self).exec_command(cmd, in_data=in_data, sudoable=sudoable)\n  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/plugins/connection/__init__.py", line 51, in wrapped\n    self._connect()\n  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 139, in _connect\n    self.ssh = SSH_CONNECTION_CACHE[cache_key] = self._connect_uncached()\n  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 210, in _connect_uncached\n    sock_kwarg = self._parse_proxy_command(port)\n  File "/var/lib/opsstack/common/env/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 151, in _parse_proxy_command\n    args = self._split_ssh_args(\' \'.join(ssh_args))\nTypeError: sequence item 0: expected string, NoneType found\n', 'stdout': ''}
fatal: [action-test001]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

```

```

**Comment by sivel** [comment]
You are not properly passing all of the necessary args as strings.

Per the error the ssh args you have passed in are None and not a string.

If you have further questions, please utilize the mailing list.

**Comment by colynn** [comment]
Because  ssh_args has default defined is 'C.ANSIBLE_SSH_ARGS‘，so defined `ssh_common_args='', ssh_extra_args=''`， then it works when use paramiko_ssh plugin.
