### ISSUE TITLE
Authentication with passphrase protected private-key require to enter passphrase for each server

### ISSUE THREAD

**Issue by pvelas** [ansible/ansible#2155]
When using private-key with passphrase it ask me to enter passphrase for each server.
I would expect to enter passphrase only once, especially when its same key on each server.

ansible adservers --connection=ssh --user=peter --private-key=/home/peter/.ssh/id_rsa -m ping

Enter passphrase for key '/home/peter/.ssh/id_rsa': 
adserver1 | success >> {    "changed": false,     "ping": "pong" }

Enter passphrase for key '/home/peter/.ssh/id_rsa': 
adserver2 | success >> {    "changed": false,     "ping": "pong"}

Enter passphrase for key '/home/peter/.ssh/id_rsa': 
adserver3 | success >> {    "changed": false,     "ping": "pong"}

Enter passphrase for key '/home/peter/.ssh/id_rsa': 
adserver4 | success >> {    "changed": false,     "ping": "pong"}

**Comment by mpdehaan** [comment]
You should use ssh-agent to avoid this.

ssh-agent bash
ssh-add ~/.ssh/id_rsa

**Comment by science** [comment]
I feel like mpdehaan's answer is not quite sufficient. A user should run `ssh-agent bash` and `ssh-add [key]` _before_ running the ansible command. It is only necessary to run these commands once per shell session, and you can run any number of ansible playbooks in that shell thereafter. (This is probably obvious to real unix admins, but I ended up here from a Google search and it wasn't to me).

**Comment by Nayar** [comment]
I'm having the same issue. I do not want a bastion server to have an SSH agent which lives forever. I want to be able to put the passphrase when using and leave the private key file on the server itself

**Comment by automaticgiant** [comment]
then kill your ssh-agent process after and/or use `ssh-add -D` to remove identities

**Comment by aholbreich** [comment]
How to make i work form Jenkins? Providing passphrase once?

**Comment by rulatir** [comment]
So in one typical scenario you must configure vagrant to configure ansible to configure and use ssh-agent. This is WAY more difficult that someone who answers "just use ssh-agent" thinks.

**Comment by JaMbarek** [comment]
..

**Comment by jpic** [comment]
Just deal with the ssh in your ansible command wrapper hehe
