### ISSUE TITLE
Ansible - ssh connect failure - tries to create a temp file on remote machine

### ISSUE THREAD

**Issue by nidhimittal** [ansible/ansible#21564]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
ssh connection plugin

##### ANSIBLE VERSION
N/A

##### SUMMARY
hello 

I am able to ssh from cli

[root@greglinux2 ~]# ssh admin@10.64.32.160
Password: 

without any problem

this is my inventory file.
====================
[root@greglinux2 ~]# cat /etc/ansible/hosts
10.64.32.160 ansible_ssh_pass=admin ansible_ssh_user=admin

when i use ansible to just ping the same remote machine 
=====================================

**[root@greglinux2 ~]# ansible -vvvvv all -m ping**
Using /etc/ansible/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<10.64.32.160> ESTABLISH SSH CONNECTION FOR USER: admin
<10.64.32.160> SSH: ansible.cfg set ssh_args: (-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<10.64.32.160> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User=admin)
<10.64.32.160> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<10.64.32.160> SSH: PlayContext set ssh_common_args: ()
<10.64.32.160> SSH: PlayContext set ssh_extra_args: ()
<10.64.32.160> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r)
<10.64.32.160> SSH: EXEC sshpass -d12 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o User=admin -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.64.32.160 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/admin/ansible-tmp-1487326446.12-124821749058426 `" && echo ansible-tmp-1487326446.12-124821749058426="` echo /home/admin/ansible-tmp-1487326446.12-124821749058426 `" ) && sleep 0'"'"''
10.64.32.160 | UNREACHABLE! => {
    "changed": false, 
    **# "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /home/admin/ansible-tmp-1487326446.12-124821749058426 `\" && echo ansible-tmp-1487326446.12-124821749058426=\"` echo /home/admin/ansible-tmp-1487326446.12-124821749058426 `\" ), exited with result 1", 
    "unreachable": true
}**

I do not have permission to create a file in remote machine on any of the directory.

Is it necessary for ansible to have permission to create a file on remote machine directory ???

how do i bypass this problem ??

can someone please help ??

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
