### ISSUE TITLE
ec2 module subnet support

### ISSUE THREAD

**Issue by lightglitch** [ansible/ansible#2158]
The subnet parameter when launching instances is useful to support VPC instances.

**Comment by mpdehaan** [comment]
sounds great, something you may want to work on?

**Comment by lightglitch** [comment]
I will, but I still didn't had time and do have to learn a little more python.
After analyzing boto source and aws api I think it's only necessary to add a new parameter because boto already supports subnets.

**Comment by lwade** [comment]
That's correct, it's a simple case of adding another parameter.  I've got the changes for this in my local repo, I'll open a pull request.  Feel free to close it or comment if you'd rather have a go :)

**Comment by mpdehaan** [comment]
closing per above PR
