### ISSUE TITLE
network_cli: Improve authentication failed messages

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#21599]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ios_*
iosxr_*
eos_*
etc

##### SUMMARY
There are a number of cases in `network_cli` where we return messages that aren't obviously about invalid credentials, for example
* ios: `"msg": "unable to open shell` (internally shown as `"err": "failed to connect to the listener socket, connection timeout."`)

**Comment by gundalow** [comment]
We could change the message to be
`"failed to connect to the listener socket, connection timeout. Please see docs.ansible.com/foo"`

This is a documentation issue

We need a section about how to debug
```
export ANSIBLE_LOG_PATH=<path>
ansible-playbook pb.yaml -vvvv
grep <path> -e "^<"
```

**Comment by privateip** [comment]
tracking this in #22703
