### ISSUE TITLE
question about sudo usage

### ISSUE THREAD

**Issue by ankitjain-fsl** [ansible/ansible#2161]
Hi All,

I have configured sudo in the Configuration file but while using it getting the below error.
###### 

dummy_user 46 % ansible Desktop -m file -a "dest=/tmp/cat.ansible state=absent" -U dummy_user --sudo -v -v -v
<Xhost> ESTABLISH CONNECTION FOR USER: dummy_user on PORT 22 TO Xhost
<Xhost> ESTABLISH CONNECTION FOR USER: dummy_user on PORT 22 TO Xhost
<Xhost> EXEC /bin/sh -c 'mkdir -p /tmp/ansible-1361420115.26-233437081199922 && chmod a+rx /tmp/ansible-1361420115.26-233437081199922 && echo /tmp/ansible-1361420115.26-233437081199922'
<Xhost> EXEC /bin/sh -c 'mkdir -p /tmp/ansible-1361420115.34-230662027444456 && chmod a+rx /tmp/ansible-1361420115.34-230662027444456 && echo /tmp/ansible-1361420115.34-230662027444456'
<Xhost> REMOTE_MODULE file dest=/tmp/cat.ansible state=absent
<Xhost> PUT /tmp/tmpIR2zyH TO /tmp/ansible-1361420115.26-233437081199922/file
<Xhost> REMOTE_MODULE file dest=/tmp/cat.ansible state=absent
<Xhost> PUT /tmp/tmp80susR TO /tmp/ansible-1361420115.34-230662027444456/file
<Xhost> EXEC /bin/sh -c 'chmod a+r /tmp/ansible-1361420115.26-233437081199922/file'
<Xhost> EXEC /bin/sh -c '/tools/sudo-1.6i686-pc-linux2.4/bin/sudo -k && /tools/sudo-1.6i686-pc-linux2.4/bin/sudo -H -S -p "[sudo via ansible, key=jgfwdsyksmjxiiphriaaewqnqlrvhwdb] password: " -u dummy_user /bin/sh -c '"'"'/usr/bin/python /tmp/ansible-1361420115.26-233437081199922/file; rm -rf /tmp/ansible-1361420115.26-233437081199922/ >/dev/null 2>&1'"'"''
<Xhost> EXEC /bin/sh -c 'chmod a+r /tmp/ansible-1361420115.34-230662027444456/file'
Xhost | FAILED >> {
    "failed": true,
    "group": "root",
    "mode": "0644",
    "msg": "[Errno 1] Operation not permitted: '/tmp/cat.ansible'",
    "owner": "root",
    "path": "/tmp/cat.ansible",
    "state": "file"
}

<Xhost> EXEC /bin/sh -c '/tools/sudo-1.6i686-pc-linux2.4/bin/sudo -k && /tools/sudo-1.6i686-pc-linux2.4/bin/sudo -H -S -p "[sudo via ansible, key=yphthlvniwaxliuamsldvtldmweqixrk] password: " -u dummy_user /bin/sh -c '"'"'/usr/bin/python /tmp/ansible-1361420115.34-230662027444456/file; rm -rf /tmp/ansible-1361420115.34-230662027444456/ >/dev/null 2>&1'"'"''
Xhost | FAILED >> {
    "failed": true,
    "group": "root",
    "mode": "0644",
    "msg": "[Errno 1] Operation not permitted: '/tmp/cat.ansible'",
    "owner": "root",
    "path": "/tmp/cat.ansible",
    "state": "file"
}

dummy_user 47 %
###### 

I have create a management server & with inventory list.In that list i have added two desktops. On those desktops i have create a file in /tmp/ansible.dummy with root & need to delete that file with my login using sudo. If i am doing it manually then there is no issues but via ansible it create issues.

Regards

Ankit

**Comment by cocoy** [comment]
seems incorrect parameter for file module, it should be "path" instead of "dest"

-m file -a "dest=/tmp/cat.ansible state=absent"

**Comment by mpdehaan** [comment]
@cocoy -- Doesn't have had anything to do with that, as dest is an alias.

**Comment by mpdehaan** [comment]
Can you show me the sudo command you are executing that does _not_ fail (including the prompt?)

Shouldn't be anything wrong with ansible here so I'll help you out, but generally Q&A should go to the mailing list.

**Comment by ankitjain-fsl** [comment]
Hi Michael,

Please see the output as below. i did ssh to xyz system where i create a file in /tmp/ with root ownership & able to delete using sudo. Let me know in case if you need any futher info on that.

dummy_user 21 % ssh xyz "sudo rm /tmp/ansible.test"
Red Hat Enterprise Linux Client release
Kernel xx.xx.xx-xxxx1.1.el5debug on an x86_64

```
                            - NOTICE -
```

dummy_user 22 %

Best Regards

Ankit

**Comment by dhozac** [comment]
You are specifying dummy_user as the user to sudo to, and that user obviously cannot remove files owned by root from /tmp. You should change `-U dummy_user` to `-u dummy_user` to specify the user you want to login as, rather than the user to sudo to.

**Comment by ankitjain-fsl** [comment]
Hi,

It did not helped for me still getting permission denied.

dummy_user 38 % ansible Desktop -m file -a "dest=/tmp/cat.ansible state=absent" -u dummy_user --sudo -v -v -v
<xyz> ESTABLISH CONNECTION FOR USER: dummy_user on PORT 22 TO xyz
<xyz> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1361790486.0-122005990689393 && chmod a+rx $HOME/.ansible/tmp/ansible-1361790486.0-122005990689393 && echo $HOME/.ansible/tmp/ansible-1361790486.0-122005990689393'
<xyz> REMOTE_MODULE file dest=/tmp/cat.ansible state=absent
<xyz> PUT /tmp/tmpaEBWCf TO /mot/dummy_user/.ansible/tmp/ansible-1361790486.0-122005990689393/file
<xyz> EXEC /bin/sh -c '/usr/SUDO/i686-pc-linux2.4/bin/sudo -k && /usr/SUDO/i686-pc-linux2.4/bin/sudo -H -S -p "[sudo via ansible, key=hpptfpouxlqoikmnymyaibsrveibkakh] password: " -u root /bin/sh -c '"'"'/usr/bin/python /mot/dummy_user/.ansible/tmp/ansible-1361790486.0-122005990689393/file; rm -rf /mot/dummy_user/.ansible/tmp/ansible-1361790486.0-122005990689393/ >/dev/null 2>&1'"'"''
xyz | FAILED >> {
    "failed": true,
    "msg": "/usr/bin/python: can't open file '/mot/dummy_user/.ansible/tmp/ansible-1361790486.0-122005990689393/file': [Errno 13] Permission denied\r\n",
    "parsed": false
}

dummy_user 39 %

Regards

Ankit

**Comment by dhozac** [comment]
Which most likely means you have your home directory on NFS, and you have to adjust your remote_tmp in ansible.cfg accordingly, putting your files somewhere that root/whatever user you sudo to can reach. /tmp/ansible-$USER is as good a spot as any.

Support type issues are better handled on the mailing list than in the issue tracker. Feel free to bring this up there.

**Comment by ankitjain-fsl** [comment]
Hi,

As suggested i changed path of remote_tmp.But now getting the below error. Any idea on that ?

  File "/tmp/ansible-Dummy_user/ansible-1361805874.33-258005755020731/file", line 957, in ?
    main()
  File "/tmp/ansible-dummy_user/ansible-1361805874.33-258005755020731/file", line 193, in main
    module.exit_json(path=path, changed=False)
  File "/tmp/ansible-dummy_user/ansible-1361805874.33-258005755020731/file", line 842, in exit_json
    print self.jsonify(kwargs)
  File "/tmp/ansible-dummy_user/ansible-1361805874.33-258005755020731/file", line 835, in jsonify
    return json.dumps(data)
AttributeError: 'module' object has no attribute 'dumps'

Regards

Ankit

**Comment by mpdehaan** [comment]
Sounds like you don't have simplejson installed on your remote node and are
running a version of python that is less than 2.5 (thus no built in JSON).

The solution is to install simplejson but I agree the error message should
not be presented in that case.

**Comment by ankitjain-fsl** [comment]
Hi,

Issue resolved after i change python link from 2.4 TO 2.6. in /usr/bin Directory. But would like to understand that on all remote hosts we have pytho2.6 installed. So is there any way that ansible sould interpret /usr/bin/python2.6 instead of /usr/bin/python. As most of program depending upon python2.4 so its not possible for us to change link on remote machines & also not possible to install python-simplejson package since it can create discrepancy in a running environment.

So would like to understand how should i instruc ansible to interpret python2.6 instead of 2.4

Regards

Ankit

**Comment by ankitjain-fsl** [comment]
Issue has been resolved after putting the below line in hosts file.

ansible_python_interpreter

Thanks all for your great help.
