### ISSUE TITLE
all_instances option from ec2.ini does not work as documented

### ISSUE THREAD

**Issue by thisdougb** [ansible/ansible#21662]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
dynamic inventory script

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.2.1.0
  config file = /home/dougb/pipelines/ansible.cfg
  configured module search path = Default w/o overrides

$ python -c 'import boto; print boto.Version'
2.45.0
```

##### CONFIGURATION
The appropriate snippet from ec2.ini:
```
# By default, only EC2 instances in the 'running' state are returned. Set
# 'all_instances' to True to return all instances regardless of state.
all_instances = True
```

##### OS / ENVIRONMENT
Centos/RH 7

##### SUMMARY
When setting all_instances=True in ec2.ini, to list all EC2 instances, ec2.py only returns running instances.   This is because of some logic which requires an instance to have a routable destination IP.   Boto doesn't give back a public IP for stopped instances.

The two options to fix this, I think, are:

1) remove the all_instances option from ec2.ini
2) update the add_instances method (in ec2.py) to allow unrouteable instances into the inventory list.

With option 1, the alternative (getting a list of stopped instances) can be had from the AWS cli or using some simple python/boto command (via an Ansible shell task).

For my situation I'd prefer option 2, and I'm happy to write the code and create a PR.    I am standing up a test env (a few instances) during a Jenkins pipeline to sanity test playbook commits, and then I'm stopping the instances once testing is complete.   I need to check if the instances don't exist (and create them), before attempting to start the env up.

But I'm not sure of the knock-on implications of option 2, away from listing instances.   Although this would only apply to if the all_instances option is true.   But perhaps there are other/unrelated things in Ansible which rely on a routable IP string being present for an inventory host?

There was a related issue: https://github.com/ansible/ansible/pull/11560

##### STEPS TO REPRODUCE
Run ec2.py in '--list' mode against an EC2 env with instances in various states.   Only running instances are returned.
```
$ python ec2.py --list
```

I added a simple print to the add_instance method in ec2.py, as simply the easiest way to show the problem more clearly.
```
    def add_instance(self, instance, region):
        ''' Adds an instance to the inventory and index, as long as it is
        addressable '''

        # Only return instances with desired instance states
        if instance.state not in self.ec2_instance_states:
            return

        # Select the best destination address
        if self.destination_format and self.destination_format_tags:
            dest = self.destination_format.format(*[ getattr(instance, 'tags').get(tag, '') for tag in self.destination_format_tags ])
        elif instance.subnet_id:
            dest = getattr(instance, self.vpc_destination_variable, None)
            if dest is None:
                dest = getattr(instance, 'tags').get(self.vpc_destination_variable, None)
        else:
            dest = getattr(instance, self.destination_variable, None)
            if dest is None:
                dest = getattr(instance, 'tags').get(self.destination_variable, None)

        # NOTE ADDED THIS LINE FOR DEBUG - @thisdougb
        print "add_instance(): state %s, dest: %s" % (instance.state, dest)

        if not dest:
            # Skip instances we cannot address (e.g. private VPC subnet)
            return
```
This gives me:
```
$ python ec2.py --list 
add_instance(): state running, dest: 34.249.143.52
add_instance(): state running, dest: 34.248.15.87
add_instance(): state running, dest: 34.248.51.103
add_instance(): state running, dest: 34.249.7.15
add_instance(): state running, dest: 34.248.191.217
add_instance(): state stopped, dest: None
add_instance(): state running, dest: 34.248.225.230
add_instance(): state running, dest: 34.249.215.73
add_instance(): state running, dest: 34.248.119.115
add_instance(): state running, dest: 34.248.218.151
```

##### EXPECTED RESULTS
I expected all instances to be added to the inventory list.

##### ACTUAL RESULTS
Only instances in the state 'running' have a routable public IP returned by boto, so they are the only ones that are added to the inventory.

**Comment by thisdougb** [comment]
I think the bug report still stands, in that all_instances doesn't do what's documented.   But I've found a much nicer way of creating missing nodes on the fly:

```
---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    aws_region: eu-west-1
    imageid: ami-02ace471
    env_name: communote_test
    key_pair: jenkins-ci
    nodes: ['cnote_db', 'cnote_app', 'cnote_proxy']
  
  tasks:
    - name: Start existing test environment instances
      ec2
        region: "{{ aws_region }}"
        instance_tags:
          Env: "{{ env_name }}"
        state: running
        wait: yes
      register: ec2

    - name: Provision missing instances
      ec2:
        region: "{{ aws_region }}"
        instance_type: t2.micro
        key_name: "{{ key_pair }}"
        image: "{{ imageid }}"
        group: "{{ env_name }}_sg"
        wait: true
        exact_count: 1
        count_tag:
           Name: "{{ item }}"
        instance_tags:
           Name: "{{ item }}"
           Env: "{{ env_name }}"
           Author: "jenkins"
      register: ec2_freshly_minted
      with_items: "{{ nodes }}"
      when: "item not in ec2.instances | map(attribute='tags.Name') | list"
```

**Comment by zahodi** [comment]
Don't think this is a bug. I had to set this in my ec2.ini

``
vpc_destination_variable = private_ip_address
``

By default ec2.py will try to use the public IP as the destination variable to provide to ansible, if it's not there due to the node being in 'stopped' state you need to tell it to use the private_ip_address.

**Comment by acozine** [comment]
Closing. Dynamic inventory scripts are deprecated in favor of [inventory plugins](https://docs.ansible.com/ansible/latest/plugins/inventory.html). We'd recommend using the `aws_ec2` plugin or the workaround listed above.
