### ISSUE TITLE
How to print the content of the file with new line characters as it appears on the file

### ISSUE THREAD

**Issue by njchandu** [ansible/ansible#21665]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
ansible 2.1.1.0 (dx-stable-2.1 553aca5dc7) last updated 2017/02/08 15:43:47 (GMT +550)

##### SUMMARY
I am trying to print the content of the file with new line characters as it appears on the file. What is the best way to do it?

**Comment by alikins** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

 This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.
