### ISSUE TITLE
Ansible 2.x is not handling arrays passed using extra-vars parameter

### ISSUE THREAD

**Issue by ansiblejunky** [ansible/ansible#21670]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-playbook 

##### ANSIBLE VERSION
ansible-playbook --version
ansible-playbook 2.2.1.0
  config file = /automation/ansible/playbooks/ansible.cfg
  configured module search path = ['library', '../library']

##### CONFIGURATION
<pre><code>
[defaults]
forks = 50
transport = smart
gathering = explicit 
library = library:../library
action_plugins = action_plugins
callback_plugins = callback_plugins
lookup_plugins = lookup_plugins:../lookup_plugins:~/.ansible/plugins/lookup_plugins:/usr/share/ansible_plugins/lookup_plugins
vars_plugins = vars_plugins:../vars_plugins:~/.ansible/plugins/vars_plugins:/usr/share/ansible_plugins/vars_plugins
filter_plugins = filter_plugins:../filter_plugins:~/.ansible/plugins/filter_plugins/:/usr/share/ansible_plugins/filter_plugins
roles_path = roles:../roles:provisioning/roles
bin_ansible_callbacks = True
force_color = 1
host_key_checking = False
retry_files_enabled = False
[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=1h -vvv
pipelining = True
</code></pre>

##### OS / ENVIRONMENT
CenOS 6.x

##### SUMMARY
We currently use Ansible 1.8.2 and we have a playbook that needs an extra-var array. It currently works just fine. However, when I run the same command in Ansible 2.x, it seems the extra-var is not parsed correctly anymore. I cannot see any reason why it would not work. 

##### STEPS TO REPRODUCE
Run the playbook and pass the extra-var "param_array":
ansible-playbook -i ../inventory/pbdel/prod/hosts testarray.yml --extra-vars='{"param_array": [1,2,3]}'

Here we see the results in Ansible 1.8.2:
<pre><code>
PLAY [localhost] ************************************************************** 

TASK: [debug msg="{{ item }}"] ************************************************ 
__timestamp_start: 2017-02-20 13:33:39.350
ok: [localhost] => {
    "item": 1, 
    "msg": "1"
}
__timestamp_end: 2017-02-20 13:33:39.367
ok: [localhost] => {
    "item": 2, 
    "msg": "2"
}
__timestamp_end: 2017-02-20 13:33:39.368
ok: [localhost] => {
    "item": 3, 
    "msg": "3"
}
__timestamp_end: 2017-02-20 13:33:39.369

PLAY RECAP ******************************************************************** 
   0.02s | debug msg="{{ item }}"

Playbook finished: 2017-02-20 13:33:39.369, 1 total tasks.  0:00:00 elapsed. 

localhost                  : ok=1    changed=0    unreachable=0    failed=0   
</code></pre>

Then we try the same command in Ansible 2.x:

<pre><code>
PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
__timestamp_start: 2017-02-20 13:42:01.848
{
    "msg": "All items completed"
}
__timestamp_end: 2017-02-20 13:42:01.910
ok: [localhost] => (item=param_array) => {
    "item": "param_array", 
    "msg": "param_array"
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

   0.07s | debug

Playbook finished: 2017-02-20 13:42:01.914, 1 total tasks.  0:00:00 elapsed. 
</code></pre>

##### EXPECTED RESULTS
The extra-var "param_array" is correctly parsed and "with_items" shows each item in the output.

##### ACTUAL RESULTS
The extra-var "param_array" is NOT correctly parsed and "with_items" shows just the variable name and no items at all. See above.

Below is the simple playbook we used:
<pre><code>
- hosts: localhost
  connection: local

  pre_tasks:
    - debug: msg="{{ item }}"
      with_items: param_array
</code></pre>

**Comment by alikins** [comment]
Try quoting and expanding the param_array reference. 

``` yaml
with_items: "{{ param_array }}"
```
(Edit: Originally had wrong syntax above)

instead of 
``` yaml
with_items: param_array
```

With the quoting:

test.yml:

``` yaml
- hosts: localhost
  gather_facts: false

  pre_tasks:
    - debug: msg="{{ item }}"
      with_items: "{{ param_array }}"
```

command line:
```
ansible-playbook -vvv test.yml --extra-vars='{"param_array": [1,2,3]}'
```

output:

```
[fedora-25:ansible (vault_cli_intg_tests %)]$ ansible-playbook -vvv repro/extra_vars_array_21670/test.yml --extra-vars='{"param_array": [1,2,3]}'
Using /home/adrian/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: test.yml *******************************************************************************************************************************************************************************************************************************************
1 plays in repro/extra_vars_array_21670/test.yml

PLAY [localhost] *********************************************************************************************************************************************************************************************************************************************

TASK [debug] *************************************************************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/extra_vars_array_21670/test.yml:5
ok: [localhost] => (item=1) => {
    "_ansible_item_result": true, 
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "item": 1, 
    "msg": 1
}
ok: [localhost] => (item=3) => {
    "_ansible_item_result": true, 
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "item": 3, 
    "msg": 3
}
ok: [localhost] => (item=2) => {
    "_ansible_item_result": true, 
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "item": 2, 
    "msg": 2
}
META: ran handlers
META: ran handlers
META: ran handlers

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

```

**Comment by alikins** [comment]
There is a small blurb at http://docs.ansible.com/ansible/playbooks_loops.html#standard-loops referencing this, though that blurb is a little vague and could use some improvement.

**Comment by ansiblejunky** [comment]
It would be best if in Ansible 2.x you print a WARNING message when the variable is not quoted when used with "with_items" for example. The problem is in Ansible 1.x you print a warning when the opposite is done - when the user quoted the variable you tell them this is not necessary. For me, this is the best place to guarantee correct Ansible code.

Also note that this change is described in the porting guide under the "Other caveats" section where it says "Bare operations on with_":
https://docs.ansible.com/ansible/porting_guide_2.0.html
