### ISSUE TITLE
ansible_user_id behavior is bad when activating fact caching

### ISSUE THREAD

**Issue by omerlin** [ansible/ansible#21703]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-playbook

##### ANSIBLE VERSION
ansible 2.1.0

##### CONFIGURATION
The issue is related to fact caching activation, so to:
fact_caching = jsonfile
fact_caching_connection = /tmp/ansible

##### OS / ENVIRONMENT
Linux

##### SUMMARY
when fact caching is activated, the ansible_user_id is the initial user and not root user as it should be.

##### STEPS TO REPRODUCE

```
- hosts: all
  gather_facts: yes  
  tasks:
    - debug: msg='ansible_user_id equals "{{ ansible_user_id }}'
```

##### EXPECTED RESULTS
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [xxxx]

TASK [debug] *******************************************************************
ok: [xxxx] => {
    "msg": "ansible_user_id equals \"root"
}

PLAY RECAP *********************************************************************
xxxx              : ok=2    changed=0    unreachable=0    failed=0

##### ACTUAL RESULTS
when activating fact caching:

(virtenv) omerlin@yyyyy#ansible-playbook --ask-become-pass --become -i xxxx, ansible.yml
SUDO password:

PLAY [all] *********************************************************************

TASK [debug] *******************************************************************
ok: [xxxx] => {
    "msg": "ansible_user_id equals \"**omerlin**"
}

PLAY RECAP *********************************************************************
xxxx              : ok=1    changed=0    unreachable=0    failed=0

```
As seen with this simple to reproduce. I don't think this is the expected behavior.
```

**Comment by bcoca** [comment]
fact caching will keep whatever values the fact was cached as, the same thing for environment variables and date/time.
