### ISSUE TITLE
Make ask_sudo_pass a valid parameter in a playbook

### ISSUE THREAD

**Issue by rchady** [ansible/ansible#2171]
The command line argument --ask-sudo-pass exists, but it is not a valid parameter in a playbook.  Would be very useful to have it available in the playbook so you do not have to remember specific command line arguments when running the playbook.  It also would make it better for including a single playbook that needs to ask for the sudo pass in other playbooks that don't.

**Comment by mpdehaan** [comment]
Also ask_pass

The /usr/bin/ansible/playbook code should recognize this when parsing all
the playbooks and then decide whether to prompt when encountering each new
user line.

**Comment by mpdehaan** [comment]
patches would be accepted
