### ISSUE TITLE
Use yaml.safe_* instaed of yaml.load / yaml.dump / …

### ISSUE THREAD

**Issue by ypid** [ansible/ansible#21724]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
devel

##### SUMMARY

`yaml.load` and `yaml.dump` allow arbitrary code execution when processing YAML files. I don’t think this is intended. I would propose to change those occurrences to the safe variants. I don’t expect any regressions from this as I don’t think the feature is even used?

* https://github.com/yaml/pyyaml/issues/5
* https://security.openstack.org/guidelines/dg_avoid-dangerous-input-parsing-libraries.html

The first fix iteration should be quite easy. Just run `git ls-files -z "$(git rev-parse --show-toplevel)" | xargs --null -I '{}' find '{}' -type f -print0 | xargs --null sed --in-place --regexp-extended 's/(yaml\.)(dump|load)\b/\1safe_\2/g;'` in each git repo which might use the pyyaml package.

Note that this might not catch all occurrences. Maybe add a Python linting check for those functions? The safe variants are also used in Ansible btw, so it seems there is a policy missing to only use the safe once?

I applied this patch to Ansible stable2.1 and will be using/testing it from now on.

In #12085 @bcoca already mentioned the switch to the `safe` variants in the light of supporting a new feature.

##### STEPS TO REPRODUCE

Run [`ag`](https://github.com/ggreer/the_silver_searcher)` -Q 'yaml.load'` in the ansible git repo.

##### EXPECTED RESULTS
No output and exit code 1 confirming no matches where found.

##### ACTUAL RESULTS

```
contrib/inventory/stacki.py
173:                config = yaml.load(stream)

lib/ansible/parsing/dataloader.py
36:from ansible.parsing.yaml.loader import AnsibleLoader

lib/ansible/modules/clustering/kubernetes.py
350:            data = yaml.load(inline_data)
356:            data = [x for x in yaml.load_all(f)]

lib/ansible/modules/cloud/cloudstack/cs_facts.py
149:            return yaml.load(self._fetch(CS_USERDATA_BASE_URL))

lib/ansible/module_utils/aos.py
135:        content_dict = yaml.load(content)

lib/ansible/utils/module_docs.py
32:from ansible.parsing.yaml.loader import AnsibleLoader

test/units/parsing/yaml/test_loader.py
31:from ansible.parsing.yaml.loader import AnsibleLoader

test/units/parsing/yaml/test_dumper.py
30:from ansible.parsing.yaml.loader import AnsibleLoader

test/units/parsing/yaml/test_objects.py
26:from ansible.parsing.yaml.loader import AnsibleLoader

test/units/modules/cloud/openstack/test_os_server.py
24:    cfg = yaml.load(doc)

test/units/mock/yaml_helper.py
4:from ansible.parsing.yaml.loader import AnsibleLoader

test/units/plugins/action/test_synchronize.py
113:        test_meta = yaml.load(fdata)

test/integration/cleanup_ec2.py
90:        credentials = yaml.load(open('credentials.yml', 'r'))
140:    int_config = yaml.load(open(opts.int_config).read())

test/integration/cleanup_rax.py
43:            credentials = yaml.load(f)

test/integration/gce_credentials.py
23:        credentials = yaml.load(open('credentials.yml', 'r'))
```

**Comment by bcoca** [comment]
Only 4 of those would be of any concern, anything using AnsibleLoader is already 'safe'.

The stacki inventory script could use AnsibleLoader also, but the 3 cloud modules cannot. The rest are tests and should be fine as they are not part of production code.
