### ISSUE TITLE
Unable to manage windows server after binding an IIS https site with option "Require Server Name Identification"

### ISSUE THREAD

**Issue by ruimcfreitas** [ansible/ansible#21725]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/rui/test/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

inventory      = ./hosts

##### OS / ENVIRONMENT
running Ansible from: Linux ubuntu16_Ansible 4.4.0-59-generic
managing: Windows 2016 with IIS

##### SUMMARY
Unable to manage windows server after binding an IIS https site with option "Require Server Name Identification"

##### STEPS TO REPRODUCE

On the Windows 2016 machine there is a IIS web site with binding for https on port 443 using a certificate. 
The ansible commands and playbooks are able to manage this machine.
After I change the binding and select the option "Require Server Name Identification" (required to use a single IP address to service multiple sites with certificates using "host name") ansible stops communication with server.
![sni](https://cloud.githubusercontent.com/assets/25148907/23173233/65ce03ba-f850-11e6-94fd-2986ef984f7b.jpg)

I can only restore communication after I remove the binding and restart the windows server.

```yaml
ansible win2016gui2 -m win_ping -vvvv
```

##### EXPECTED RESULTS
win2016gui2 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}

##### ACTUAL RESULTS

```
Using /home/rui/test/ansible.cfg as config file
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/windows/win_ping.ps1
<192.168.233.141> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5986 TO 192.168.233.141
win2016gui2 | UNREACHABLE! => {
    "changed": false,
    "msg": "ssl: (\"bad handshake: SysCallError(104, 'ECONNRESET')\",)",
    "unreachable": true
}
```

**Comment by jhawkesworth** [comment]
Looks like you are communicating with your ansible controller via ip address '192.168.233.141' - what happens if you change to using a hostname?

**Comment by ruimcfreitas** [comment]
It works!!

On the ansible folder "hosts" file I've replaced the entry
   win2016gui2 ansible_host=192.168.233.141
with just
   win2016gui2

and on the /etc/hosts file I've added the entry
  192.168.233.141 win2016gui2

Is this how it should be done?

**Comment by jhawkesworth** [comment]
Its definitely worth using DNS if only because machine names are more memorable than IP addresses.
DNS is important if you ever start using kerberos / active directory logins - without hostnames and fully functioning DNS it won't work.

I'll close this one now.

**Comment by ruimcfreitas** [comment]
thanks for your precious help. Best Regards. Rui
