### ISSUE TITLE
consul module: port should be optional when registering services

### ISSUE THREAD

**Issue by stefreak** [ansible/ansible#21727]
Opening this because #17031 has been closed because it needed to be submitted to https://github.com/ansible/ansible-modules-extras, but there it says you should open the issue here.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```
##### CONFIGURATION

not applicable

##### OS / ENVIRONMENT

ubuntu 16.04

##### SUMMARY

Consul service definitions do not require a port. See https://www.consul.io/docs/agent/services.html
Still, the consul module requires me to provide the service_port parameter.

Some services do not listen on TCP ports.

##### STEPS TO REPRODUCE

```yaml
- name: Register some service with consul
  consul:
    service_name: "myService"

```

##### EXPECTED RESULTS

It creates a service without a port. Creating a json service definition without a port and reloading consul works.

##### ACTUAL RESULTS

The following error is returned

```
service_name supplied but no service_port, a port is required to configure a service. Did you configure the 'port' argument meaning 'service_port'?
```

**Comment by gundalow** [comment]
Proposed fix in https://github.com/ansible/ansible/pull/21737 reviews welcome
