### ISSUE TITLE
#21510 introduces breaking changes for Powershell param parsing

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#21738]
Looks like the object type of $params has changed from array to Hashtable with this commit. This will mean that any module _not_ using the default Get-AnsibleParam function will break. I see that 21510 is a large change, so not sure changing the object type is a required change or a possible oversight?

(ping @nitzmahone )

**Comment by jctanner** [comment]
https://github.com/ansible/ansible/pull/21510

**Comment by nitzmahone** [comment]
@trondhindenes: It was definitely done "on purpose". Is this a hypothetical, or did something actually break for you? I'm not aware of any modules that don't use Get-Attr/Get-AnsibleParam (though TBF, I didn't do an exhaustive review, either).

I don't *have* to get rid of ConvertFrom-Json, but especially for modules that need to deal with complex dictionary inputs, nested Hashtables are a lot easier than PSObjects. I suppose we could make a conversion function globally available if you think(/know) of a specific problem...

**Comment by nitzmahone** [comment]
OTOH, PSObject *result* values definitely need to die in a fire. ;)

**Comment by trondhindenes** [comment]
just making sure :-). I just got notified from a user of my win_dsc stuff (which is outside of Ansible). We parse args dynamically there, so its a bit of an edge case. No worries, I was just making sure before I do the req'd refactoring of my custom stuff.
