### ISSUE TITLE
include_vars does not handle YAML which deserializes to datetime

### ISSUE THREAD

**Issue by wrouesnel** [ansible/ansible#21747]
Including a yaml stanza which contains something date-like:
```yaml
fieldname: 2016-02-01
```

results in a JSON serialization error when included via `include_vars`

The exact same input though as a `group_var` works correctly, and is deserialized to a `datetime.date` object.

`include_vars` should be capable of parsing the same data as inventory vars.

**Comment by abadger** [comment]
Could you kindly post the complete error message (and if possible step-by-step for reproducing)?

**Comment by bcoca** [comment]
filling in the standard template would be helfpul

**Comment by wrouesnel** [comment]
This looks like it's been fixed on the current master, so closing.
