### ISSUE TITLE
Python3 compat fail with pipelining and strategie:debug

### ISSUE THREAD

**Issue by marlox-ouda** [ansible/ansible#21777]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
strategy/debug

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
python3
with pipelining=True
playbook with strategy:debug

##### OS / ENVIRONMENT
N/A

##### SUMMARY
```reduce``` not recognize in ```lib/python3.5/site-packages/ansible/plugins/strategy/debug.py```
Note: reduce is not imported and not available by default in python3.

Note: with ```from functools import reduce```, others exceptions are raised.

**Comment by abadger** [comment]
Fixed in https://github.com/ansible/ansible/pull/18561.  Change was first released in 2.2.2
