### ISSUE TITLE
ansible 2.2.2.0 and 2.2.1.0 template failure 

### ISSUE THREAD

**Issue by ifelsefi** [ansible/ansible#21799]
##### ISSUE TYPE

 - Bug Report
 
##### ANSIBLE VERSION

```
sysadmin@mint[~/repos/ansible/playbooks]$ ansible --version
ansible 2.2.1.0
  config file = /home/sysadmin/repos/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### SUMMARY

I can no longer template my ldif.  

Task in roles/accouns/create_user.yml "template user ldif" fails.

##### STEPS TO REPRODUCE

top-level accounts.yml

```yaml
---
- hosts: "{{ hosts }}"
  roles: 
    - accounts
  gather_facts: True
```
roles/accounts/tasks/create_user.yml

```yaml
# get gid for user based upon group var defined at command line (-e group=group) as well as dict set in roles/accounts/vars/main.yml
- name: choose gid
  tags: create,collab
  set_fact:
    chosen: "{{ chosen + [ { 'gid': item[0].gid } ] }}"
  with_nested: 
    - "{{ dict }}"
    - "{{ group }}"
  when: item[1] == item[0].name

- name: template user ldif
  tags: create
  template: src=ldif.j2 dest={{ ldif }} mode=600 owner=root group=root
  with_items: "{{ chosen }}"
  when: collab is not defined
```
roles/accounts/templates/ldif.j2

```
dn: uid={{ user }},{{ OU }},{{ DN }}
objectClass: account
objectClass: posixAccount
objectClass: top
objectClass: extensibleObject
uid: {{ user }}
cn: {{ gecos }}
loginShell: /bin/bash
uidNumber: {{ uidnumber }}
gidNumber: {{ item.gid }}
homeDirectory: /home/{{ user }}
gecos: {{ gecos }}
mail: {{ user }}@fqdn
userPassword: {{ pass }}
```
roles/accounts/vars/main.yml [encrypted]

```
ldif: /tmp/user.ldif
dict:
 - { name: 'lab', gid: 'anynumber' }
```

##### EXPECTED RESULTS

It works

##### ACTUAL RESULTS

It fails

```
ansible-playbook accounts.yml "-e hosts=host -e user=user -e group=group -e gecos='first last' -e create=[]" -u root --ask-vault-pass --step -vvv

TASK [accounts : template user ldif] *******************************************
task path: /home/syadmin/repos/ansible/playbooks/roles/accounts/tasks/create_user.yml:50
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 98, in run
    item_results = self._run_loop(items)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 281, in _run_loop
    res = self._execute(variables=task_vars)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 502, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/template.py", line 81, in run
    dest = self._remote_expand_user(dest)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 490, in _remote_expand_user
    if not path.startswith('~'):  # FIXME: Windows paths may start with "~ instead of just ~
AttributeError: 'dict' object has no attribute 'startswith'

fatal: [host]]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}

```

**Comment by ifelsefi** [comment]
Note, this works if I remove {{ ldif }} and instead use:

template: src=ldif.j2 dest=/tmp/user.ldif mode=600 owner=root group=root

**Comment by jctanner** [comment]
@JusticeForMikeBrown I'm a little confused. Based on your description, "ldif" is a dictionary and you are trying to substitute a dictionary into a filepath. Shouldn't it be {{ ldiff.name }} or {{ ldiff.gid }} to access the values of one of the keys instead of the entire dict?

needs_info

**Comment by ifelsefi** [comment]
ldif defined in encrypted vars/main.yml:

ldif: /tmp/user.ldif

template fails with 

- name: template user ldif
  tags: create
  template: src=ldif.j2 dest={{ ldif }} mode=600 owner=root group=root

but works with:

- name: template user ldif
  tags: create
  template: src=ldif.j2 dest= /tmp/user.ldif mode=600 owner=root group=root

**Comment by ifelsefi** [comment]
Any idea how to fix?

Thanks!

**Comment by sivel** [comment]
I tried to add some code blocks to your report to better understand the problem.  As it is, ansible believes that your `ldif` variable is a python dict.

I notice that in `roles/accounts/vars/main.yml` you have defined a variable called `dict`.  This may be causing the issues, and regardless you should probably rename that variable.

Also, I cannot guarantee that something wasn't already lost before I wrapped things with code blocks.

I would recommend adding a task that looks like:

```
- debug:
    var: ldif
```

Then we can see what is happening.
