### ISSUE TITLE
use keychain for sudo password

### ISSUE THREAD

**Issue by akvadrako** [ansible/ansible#2182]
We always need ask_sudo_pass; it's company policy. It would be nice if we could store those passwords in the OS X keychain. The code is something like this and works on Gnome/KDE/etc too:

``` python
import keyring
pwd = keyring.get_password('ansible', 'remote-username')
if pwd:
  return pwd
else:
  pwd = ask_normally()
  keyring.set_password(name, 'sudo', pwd)
  return pwd
```

**Comment by mpdehaan** [comment]
These are remote sudo passwords though, for multiple servers.

**Comment by akvadrako** [comment]
I don't see the problem.

1) ansible only prompts for the sudo password once, for all servers
2) using the keychain method, it could ask for one per host username

On Feb 23, 2013, at 14:57, Michael DeHaan <notifications@github.com<mailto:notifications@github.com>> wrote:

These are remote sudo passwords though, for multiple servers.

**Comment by mpdehaan** [comment]
Yeah, submit a pull request so I can see this and test in context.

You will need to conditionally include keychain such that things will still
work if it's not there.
