### ISSUE TITLE
[doc] does service support upstart?

### ISSUE THREAD

**Issue by akvadrako** [ansible/ansible#2183]
When I try to use control a service with upstart I get this error:

> msg: my-service: unrecognized service

but on the system running initctl directly works:

> $ initctl status my-service
> my-servie stop/waiting

It looks like the service module only uses upstart (svn_initctl) for checking status.

**Comment by mpdehaan** [comment]
What OS are you using?

It seems like you don't have the proper service init scripts around the
upstart magic.

**Comment by mpdehaan** [comment]
please also list what actual service you are using

**Comment by mpdehaan** [comment]
I'll reopen this if it has more info.  Thanks!

**Comment by akvadrako** [comment]
On Feb 23, 2013, at 14:58, Michael DeHaan notifications@github.com wrote:

> What OS are you using? 
> 
> It seems like you don't have the proper service init scripts around the 
> upstart magic.

CentOS 6.3

What magic do you expect?

And it's our own service with working upstart scripts.

**Comment by mpdehaan** [comment]
What's the service?

**Comment by akvadrako** [comment]
Sorry - I forgot that question. It's an in house service with a working upstart script.

On Feb 23, 2013, at 15:38, Michael DeHaan <notifications@github.com<mailto:notifications@github.com>>
 wrote:

What's the service?

**Comment by mpdehaan** [comment]
I believe it's required that your script, even if using upstart, has init.d
scripts in place such that /sbin/service can still be used.

**Comment by akvadrako** [comment]
That isn't true at all - upstart is an init.d replacement. So it seems like the answer to my question is "no", which is OK. It would just be nice if it was documented.

**Comment by mpdehaan** [comment]
Can you show me a stock Red Hat / CentOS service that doesn't work with
/sbin/service ?

I'm hard pressed to find any.

**Comment by akvadrako** [comment]
sure:

```
[root@worker4 dbayer]# initctl status init-system-dbus
init-system-dbus stop/waiting
[root@worker4 dbayer]# service init-system-dbus start
init-system-dbus: unrecognized service
```

```
[root@worker4 dbayer]# initctl start serial DEV=/dev/ttyS3
serial (/dev/ttyS3) start/running, process 24809
[root@worker4 dbayer]# service serial start
serial: unrecognized service
```

**Comment by mpdehaan** [comment]
Ok, thanks... It seems we need to teach the module some basic detection to
decide the type of service by poking around /etc (fun!)

**Comment by akvadrako** [comment]
You might also be interested to know that in RHEL7, upstarted will be deprecated for systemd.

**Comment by mpdehaan** [comment]
I'm on top of that, yes :)

Ideally /sbin/service would just DWIM, but I guess we are not so lucky.

**Comment by iffy** [comment]
I'm running into the same problem.  Should this be opened?

**Comment by mpdehaan** [comment]
You are probably seeing something new, perhaps you can stop by IRC or the mailing list?

Otherwise I would prefer a new ticket.

Be sure to relate the version of ansible you are using.

**Comment by jhurliman** [comment]
I'm also seeing this with the latest git checkout of Ansible and Amazon Linux (based on CentOS). I wrote a custom upstart conf file for my own service which I can start/stop fine from the command-line, but Ansible gives me "msg: service name not recognized".

**Comment by mpdehaan** [comment]
Generally working fine for non-custom scripts, can you figure out how it's
different and if so please open a new ticket if you confirm it's installed
like all the other system services?

Thanks!

**Comment by jaredjennings** [comment]
I've seen what appears to be this problem on RHEL 6.6, with ansible-1.9.0.1-2.el6.noarch from EPEL, while trying to install Gitorious. By applying the fix in https://github.com/ansible/ansible-modules-core/commit/8d53ef2f6055e174a10795bc5a084c3a36389678, I obtained the correct behavior. The changeset is from 20 days ago; I can't tell what releases of Ansible may already contain this change.

**Comment by ghost** [comment]
Was support for upstart ever integrated into ansible? If so is the minimum version that works in documented?

**Comment by rngadam** [comment]
Upstart still problematic with ansible 1.9.0.1 with CentOS release 6.6 (Final)

with:

```
    - service: name={{webapp_name}} enabled=yes
    - service: name={{webapp_name}} state=reloaded
```

fails:

```
TASK: [service name={{webapp_name}} enabled=yes] ****************************** 
ok: [HOSTNAME]

TASK: [service name={{webapp_name}} state=reloaded] *************************** 
failed: [HOSTNAME] => {"failed": true}
msg: NAME_OF_SERVICE: unrecognized service

FATAL: all hosts have already failed -- aborting
```

workaround:

```
    #- service: name={{webapp_name}} state=reloaded
    # upstart services are peculiar and are not supported by ansible_hostname
    #
    - command: status {{webapp_name}}
      register: status
      changed_when: False

    - command: /sbin/restart {{webapp_name}}
      when: config.changed and status.stdout.find('start/running') != -1

    - command: /sbin/start {{webapp_name}}
      when: config.changed and status.stdout.find('stop/waiting') != -1

    - command: status {{webapp_name}}
      register: status
      failed_when: status.stdout.find('start/running') == -1
      changed_when: False
```
