### ISSUE TITLE
The 'to retry, use..." message on stdout breaks parsing of JSON when stdout_callback=json is set

### ISSUE THREAD

**Issue by Xiol** [ansible/ansible#21838]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Playbook executor

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o override
```

##### CONFIGURATION
```
stdout_callback = json
nocows = 1
nocolor = 1
remote_port = 22
forks = 20
ansible_log = /var/log/ansible.log
```

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY
We use the `stdout_callback=json` setting to get Ansible to output JSON, which we then parse and use in our internal systems to fully automate Ansible runs. (Unfortunately Tower does not suite our use case).

When a run fails, we get the message:

`to retry, use: --limit @/var/lib/foo/bar/vhost.retry`

Followed by the JSON from the run.

The error message comes in stdout, where the JSON arrives, so it causes our JSON parser to throw a fit.

##### STEPS TO REPRODUCE
Set `stdout_callback=json` in `ansible.cfg` then do something wrong.

##### EXPECTED RESULTS
Errors in stderr, JSON in stdout.

##### ACTUAL RESULTS
Everything in stdout.

**Comment by bcoca** [comment]
callbacks only handle play reporting, other error messages are not emitted via callbacks.

**Comment by ghost** [comment]
I also have this issue and would like to see a fix.

**Comment by sivel** [comment]
This is a known issue, as currently callbacks do not control the full stdout output.

As such, you will need to disable retry files.

```
[defaults]
retry_files_enabled = false
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
