### ISSUE TITLE
Can't use ansible with user/password if keyfile exists

### ISSUE THREAD

**Issue by andig** [ansible/ansible#21867]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core/paramiko

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
OSX

##### SUMMARY
Ansible ignores request to execute remote command using user/password if keyfile exists. Use case is initial deployment of authorized key.

I have a local id_dsa key of 1023 bit that I know doesn't work with ansible, therefore want to use u/p.

##### STEPS TO REPRODUCE
````
➜  ansible keller -m authorized_key -a 'key="ssh-rsa ..."' -u pi -vvvv --ask-password
````

The same can be reproduced when adding the `-k` switch.

##### EXPECTED RESULTS
Command executed without key error by using u/p.

##### ACTUAL RESULTS
```
No config file found; using defaults
Loading callback plugin minimal of type stdout, v2.0 from /usr/local/Cellar/ansible/2.2.1.0_1/libexec/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
Using module file /usr/local/Cellar/ansible/2.2.1.0_1/libexec/lib/python2.7/site-packages/ansible/modules/core/system/authorized_key.py
<192.168.0.48> ESTABLISH CONNECTION FOR USER: pi on PORT 22 TO 192.168.0.48
<192.168.0.48> CONNECTION: pid 38069 waiting for lock on 8
<192.168.0.48> CONNECTION: pid 38069 acquired lock on 8

paramiko: The authenticity of host '192.168.0.48' can't be established.
The ssh-rsa key fingerprint is 29bd6ede468f26ae37a773aad8d93470.
Are you sure you want to continue connecting (yes/no)?
yes
<192.168.0.48> CONNECTION: pid 38069 released lock on 8
No handlers could be found for logger "paramiko.transport"
keller | UNREACHABLE! => {
    "changed": false,
    "msg": "p must be exactly 1024, 2048, or 3072 bits long",
    "unreachable": true
}
```

Is it correct to assume that ansible uses the (borked) dsa key? Shouldn't it use user/password instead?

**Comment by andig** [comment]
I can confirm that removing the existing `id_dsa` file from the client cures the issue.

**Comment by jctanner** [comment]
Ansible does not set a priority on key versus passwords with paramiko. We're simply giving the parameters to the connection method and then paramiko handles the method order.

https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/paramiko_ssh.py#L229-L239

http://docs.paramiko.org/en/2.1/api/client.html

It's also specified in the RFC that the available methods are determined by the server, and the order to use is up to the client to decide:

https://tools.ietf.org/html/rfc4252

> The server drives the authentication by telling the client which
   authentication methods can be used to continue the exchange at any
   given time.  The client has the freedom to try the methods listed by
   the server in any order.  This gives the server complete control over
   the authentication process if desired, but also gives enough
   flexibility for the client to use the methods it supports or that are
   most convenient for the user, when multiple methods are offered by
   the server.
