### ISSUE TITLE
When using group_by, invalidate the group variables cache to force variable loads

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#2186]
Suppose we use group_by to create groups based on OS distribution.   It was reported that in order to assign variables based on distribution we have to have the group name already in inventory for group_vars to be loaded.

We should remove this requirement.

**Comment by dhozac** [comment]
The issue is that once a host's vars have been gathered, they are cached (Inventory.get_variables). Adding a new group should invalidate the cache, and things should work as expected.

**Comment by mpdehaan** [comment]
updated the description, thanks!

**Comment by mpdehaan** [comment]
User reported some problems, so I reverted this in dc0515a

**Comment by mpdehaan** [comment]
See #2277

**Comment by mpdehaan** [comment]
cc @bcoca
