### ISSUE TITLE
allow_duplicates=false fails to detect duplicate when role is conditional

### ISSUE THREAD

**Issue by smemsh** [ansible/ansible#21885]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
roles

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

We include **role3** from both **role1** and **role2** in `meta/main.yml` using `dependencies:` keyword.  These roles both pass the same parameters (that is: none directly, only via extra arguments) to **role3**, but it's (wrongly) running twice, merely because the depending role has a condition on itself.

We have the condition because we want to run **role2** only sometimes, so we put a `when:` on the `role:` in its dependency declaration.  This seems to work fine as far as only including **role2** when it should be.  The condition is properly checked, and properly includes the role only if true.

However, including any condition at all results in the dependency running twice, even if the condition is always true (i.e. `when: true`).  This is *not* a different parameter or value, so the role calls are 100% identical, and `allow_duplicates` is *false*, yet it runs twice.

##### STEPS TO REPRODUCE

```
 $ tail test.yml roles/**/*.yml
==> test.yml <==
- hosts: all
  gather_facts: false
  roles:
    - role1
    - role2

==> roles/role1/meta/main.yml <==
dependencies:
  - role: role3

==> roles/role1/tasks/main.yml <==
- set_fact: dummy

==> roles/role2/meta/main.yml <==
dependencies:
  - role: role3
    when: true

==> roles/role2/tasks/main.yml <==
- set_fact: dummy

==> roles/role3/tasks/main.yml <==
- set_fact: dummy
```

##### EXPECTED RESULTS

role3 should be run once only.  it's run once until adding `when: true` to the dependency.  then it runs twice, and that's a bug.  the duplicate run check should be discerning whether a role with that name and paramaters has run already, without any knowledge of when it's supposed to run.  only if it has.

##### ACTUAL RESULTS

```
$ ansible-playbook -c local -i localhost, test.yml

PLAY [all] *********************************************************************

TASK [role3 : set_fact] ********************************************************
ok: [localhost]

TASK [role1 : set_fact] ********************************************************
ok: [localhost]

TASK [role3 : set_fact] ********************************************************
ok: [localhost]

TASK [role2 : set_fact] ********************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0
```

now watch when removing the `when: true` condition on the role dependency:
```
 $ sed -i /when:.true/d roles/role2/meta/main.yml                                                                                                             

 $ ansible-playbook -c local -i localhost, test.yml

PLAY [all] *********************************************************************

TASK [role3 : set_fact] ********************************************************
ok: [localhost]

TASK [role1 : set_fact] ********************************************************
ok: [localhost]

TASK [role2 : set_fact] ********************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

The condition shouldn't matter, it's whether the role actually has been run or not already, and if it's the same role, and the same parameters.  "when" is not a parameter, it's a control.  Note that I tried altering `become_user:` instead of `when:` to see if that would also cause a second run, and that one works correctly: it only runs once (in that case, you might argue that it actually has a different parameter, but I don't see any way to argue that for `when:`).

**Comment by jctanner** [comment]
@smemsh did you find a reference or an example or documentation somewhere that implies "when" is a valid keyword for role depedencies?

needs_info

**Comment by smemsh** [comment]
how about: 2b5005687a67e6a510be700119cea015e075683e

using `when:` does work as expected -- that is, it correctly executes the role based on the condition -- and doesn't emit any error.  the part that *doesn't* work is `allow_duplicates=false` because it runs twice, even with the same parameters, and it's not supposed to do that.  the only thing different is that the task has a `when:` clause.

there's no indication that `when:` does not work for roles declared as dependencies, and there's specific support for 'when' with roles, mentioned here: http://docs.ansible.com/ansible/playbooks_conditionals.html#applying-when-to-roles-and-includes and you can see some references to other people using `when:` with roles for example here: http://edunham.net/2015/09/10/ansible_conditional_role_dependencies.html and at least we know that `include_role` can do it too.

**Comment by sivel** [comment]
Related to this commit https://github.com/ansible/ansible/commit/dca36c1d160

**Comment by lcts** [comment]
Any update on this? I just ran into this again.
I'm not much of a coder, but if anything needs testing I'm up for it.

**Comment by s-hertel** [comment]
It looks like this is happening because `when` is part of the role signature (since the commit linked above), therefore they're different and the role runs two times. We discussed this in backlog today and think this is the behavior we want.

**Comment by smemsh** [comment]
it should really be added to docs for `allow_duplicates` then.  it's pretty confusing and doesn't match common sense.

**Comment by sivel** [comment]
This is documented at https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#running-role-dependencies-multiple-times-in-one-playbook

> If two roles in a playbook both list a third role as a dependency, Ansible only runs that role dependency once, unless you pass different parameters, tags, when clause, or use allow_duplicates: true in the dependent (third) role.

That explicitly states that a `when clause` is used for detecting duplicate role invocations.  The `when` statement is part of the role signature.
