### ISSUE TITLE
include_role does not expose variables to rest of playbook

### ISSUE THREAD

**Issue by wouterh-dev** [ansible/ansible#21890]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
None.

##### OS / ENVIRONMENT
OS: CentOS7, but shouldn't matter.

##### SUMMARY
When including a role using include_role its vars do not become available to the rest of the playbook. This does work when using the regular roles definition.

##### STEPS TO REPRODUCE
A minimal test-case lives here: https://github.com/wouterhund/demo-ansible-include_role-bug/blob/master/bad-playbook.yml https://github.com/wouterhund/demo-ansible-include_role-bug/blob/master/roles/testrole/vars/main.yml

The actual code that triggers the issue:

```yaml
---
- hosts: localhost

  tasks:
    - include_role:
        name: testrole
    - debug: msg="{{some_var}}"
```

`roles/testrole/vars/main.yml`
````yaml
---
some_var: "Hello world!"
````

##### EXPECTED RESULTS
I would expect `good-playbook.yml` and `bad-playbook.yml` from the linked github to work identically, however `bad-playbook.yml` fails. I expect variables defined within an included role to be made available to the rest of the playbook.

For the example above I'd expect it to pass and display "Hello world!"

##### ACTUAL RESULTS
```
» ansible-playbook -vvvv bad-playbook.yml                                                                                                                1 ↵
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: bad-playbook.yml *****************************************************
1 plays in bad-playbook.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1487936470.27-110880382737009 `" && echo ansible-tmp-1487936470.27-110880382737009="` echo ~/.ansible/tmp/ansible-tmp-1487936470.27-110880382737009 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp017eF_ TO /home/vagrant/.ansible/tmp/ansible-tmp-1487936470.27-110880382737009/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1487936470.27-110880382737009/ /home/vagrant/.ansible/tmp/ansible-tmp-1487936470.27-110880382737009/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/vagrant/.ansible/tmp/ansible-tmp-1487936470.27-110880382737009/setup.py; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1487936470.27-110880382737009/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [testrole : debug] ********************************************************
task path: /home/vagrant/demo-ansible-include_role-bug/roles/testrole/tasks/main.yml:2
ok: [localhost] => {
    "msg": "Hello world!"
}

TASK [debug] *******************************************************************
task path: /home/vagrant/demo-ansible-include_role-bug/bad-playbook.yml:7
fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'some_var' is undefined\n\nThe error appears to have been in '/home/vagrant/demo-ansible-include_role-bug/bad-playbook.yml': line 7, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n        name: testrole\n    - debug: msg=\"{{some_var}}\"\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"
}
	to retry, use: --limit @/home/vagrant/demo-ansible-include_role-bug/bad-playbook.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   
```

**Comment by rcarrillocruz** [comment]
do you get the same issue if you force the vars_from param:
```yaml
---
- hosts: localhost

  tasks:
    - include_role:
        name: testrole
        vars_from: main
    - debug: msg="{{some_var}}"
```

**Comment by wouterh-dev** [comment]
@rcarrillocruz Yes, the behavior remains unchanged.

**Comment by rcarrillocruz** [comment]
K, let me reproduce this on devel and your current version.

**Comment by smemsh** [comment]
I can confirm, here's my own test case:
```
 $ tail test.yml roles/**/*.yml
==> test.yml <==
- hosts: all
  tasks:
    - include_role:
        name: role3

==> roles/role1/defaults/main.yml <==
role1_var: value

==> roles/role1/tasks/main.yml <==
- set_fact: dummy

==> roles/role2/tasks/main.yml <==
- set_fact:
    role1_fact: '{{role1_var}}'

==> roles/role3/meta/main.yml <==
dependencies:
  - role: role1
  - role: role2

==> roles/role3/tasks/main.yml <==
- set_fact: dummy
```

applying this patch to the play fixes it (role vars are properly exported):
```
 $ diff -urNb setup.{fails,works}
diff -urNb setup.fails/test.yml setup.works/test.yml
--- setup.fails/test.yml        2017-02-25 12:56:16.138088517 -0800
+++ setup.works/test.yml        2017-02-25 12:58:21.384958338 -0800
@@ -1,4 +1,3 @@
 - hosts: all
-  tasks:
-    - include_role:
-        name: role3
+  roles:
+    - role3
```

**Comment by fivethreeo** [comment]
Fixes the play, yes, not the issue reported.

**Comment by smemsh** [comment]
@fivethreeo right yes, my point was that including the role as a task doesn't export the role's variables, but including it as a "standard" role does, which is inconsistent behavior.  I've adjusted the language in my comment, thanks.

**Comment by chrismeyersfsu** [comment]
`ansible 2.3.0.0`

I too am experiencing this confusing behavior. I illustrate the observed problem with a `chicken` and `egg` set of roles https://github.com/chrismeyersfsu/ansible-examples/blob/master/include_role/main.yml

Compare the `include_role` experience to the "classic" role invocation and variable lifespan behavior https://github.com/chrismeyersfsu/ansible-examples/blob/master/role_variable_scope/main.yml

**Comment by conleym** [comment]
For those who have the luxury of modifying the roles they're using, it is possible to explicitly "export" vars/defaults via a separate tasks file as an (admittedly awful and hopefully temporary) workaround, e.g., in `roles/testrole/tasks/export-vars.yml`:

```
---
- set_fact:
     some_var: "{{ some_var }}"
```

and, in the playbook, use `tasks_from: export-vars`. 

I have to use a separate tasks file anyway, as I want to load defaults and vars from the role but not run any of its tasks in a couple of roles (it's a long story). Figured I'd share on the off chance that it could help someone.

**Comment by chrismeyersfsu** [comment]
@conleym I use `include_vars` for this case. It results in no structural changes to the underlying role. It does require that you hardcode the roles directory thought.
```
- hosts: localhost
  tasks:
    - include_vars: "roles/chicken/defaults/main.yml"
    - debug:
         msg: "{{ chicken_var }}"
```
https://github.com/chrismeyersfsu/ansible-examples/blob/master/include_vars/main.yml

**Comment by lhoss** [comment]
interesting that nobody explicitly mentioned the `include_role` `private` option, which when set `False` should indeed expose the role's defaults and vars.
Ref: https://docs.ansible.com/ansible/include_role_module.html#options
OK by default it should be `False` so this would def. be an issue.. anybody tried setting it explicitly to `False` ?

**Comment by ipolyzos** [comment]
I can confirm I have the same issue with 2.3.0.0

@lhoss tried setting private explicitly, no change

**Comment by jctanner** [comment]
Bug confirmed for devel and all ansible versions with include_role.

**Comment by jctanner** [comment]
The fix for this is going to depend on https://github.com/ansible/ansible/compare/imports_and_includes so it probably won't make it to a release until 2.4 at the earliest.

**Comment by bcoca** [comment]
related #21077

**Comment by kiorky** [comment]
Im working on a fix which seems nearly to be good for review, if someone wants to begin some kind of review...

**Comment by kiorky** [comment]
The fix is now there for a long time, may it be reviewed ?

**Comment by kiorky** [comment]
For those who want to test the fix:
On my fork, you have two branchs for you:

Pristine 2.5+the PR #32565 commits: https://github.com/corpusops/ansible/tree/devel
Pristine 2.4+the PR #32565 commits: https://github.com/corpusops/ansible/tree/a2.4

**Comment by chrisweaver** [comment]
I'm still seeing this bug in 2.4.2.  Is this issue still open?  I lost the thread there, with all the cross references...

I would love to port our playbooks to use `include_role` but this bug makes it impossible.

**Comment by tima** [comment]
@chrisweaver: I looks like this will only be fixes in v2.5: https://github.com/ansible/ansible/issues/32503#issuecomment-366806353

**Comment by kiorky** [comment]
I personnaly use this on my 2.4 fork: https://github.com/corpusops/ansible/tree/stable-2.4

**Comment by kiorky** [comment]
(And im the one that tries to push the fix for 2.5)

**Comment by kiorky** [comment]
See: https://github.com/ansible/ansible/pull/35167

**Comment by daMupfel** [comment]
Is there any update to this? I tried to figure out the current state but i could not find a conclusive answer.

This is still not working with 2.5.0rc3 as far as i can see?

**Comment by duck-rh** [comment]
I can confirm 2.5.0 does not solve this.

**Comment by seansabour** [comment]
Any update to this issue? I am still seeing this in 2.5.0 as-well.

**Comment by kiorky** [comment]
Try my fork ;)

**Comment by sivel** [comment]
This is by design, and no functionality has been added to support exposing these vars outside of the role at this time.

I've updated this to a feature idea.

**Comment by chrisweaver** [comment]
I'm confused. Several people in this thread have contributed possible fixes. That suggests this is a bug, not a new feature.

Also, since import_role does not work the same as classic import, many people (including me) can't use it. I don't see a deprecation announcement but I assume it's coming. And the documentation for "Including and Importing" freely mixes the two in its examples. It does not indicate this fundamental difference, instead it strongly leads the reader to believe they are identical.

I'm concerned because Bugfix generally gets higher priority than New Feature...

**Comment by sivel** [comment]
As indicated, it is by design that `include_role` and `import_role` work like this. There was never functionality to implement exposing these vars.  An attempt was made, and docs were left behind, but no functionality ever existed.  Ansible 2.6 will contain a warning for those attempting to use the `private` argument, as it was never actually implemented, and was a documentation bug.

Changing the default behavior would not be accepted.  A new feature, to expose them based on a flag would be required, potentially re-using the `private` argument.

As such, anyone reporting to have fixed a bug, would actually be creating a bug, by changing the default behavior.  Instead a new feature is required.

**Comment by daMupfel** [comment]
I don't understand. 
According to the documentation: http://docs.ansible.com/ansible/latest/modules/include_role_module.html

private: 
If True the variables from defaults/ and vars/ in a role will not be made available to the rest of the play.

(Which means for me that when False they will be available)

So this documentation is just wrong? If so please indicate this on the current documentation. This is extremley confusing!

**Comment by boyvinall** [comment]
If the issue here is compatibility with the playbooks already out there then couldn't you simply reverse the default?  i.e. allow the `private` argument to exist but default it to `false`.  

It seems bad form to class this as a feature request when the issue has existed for more than a year and the documentation indicated the functionality was there.

**Comment by gadamiak** [comment]
The concern of breaking compatibility is actually wrong. If both `include_role` and `import_role` don't expose nested variables by design, then that breaks compatibility with the legacy:

```yaml
roles:
  - role
```

I can see a point of keeping consistency with what was implemented already regardless it was correct or not. A simple and straightforward solution would be to use the `private` flag defaulting to `false` as proposed by @boyvinall.

**Comment by sivel** [comment]
> I don't understand.
> According to the documentation: http://docs.ansible.com/ansible/latest/modules/include_role_module.html
> 
> private:
> If True the variables from defaults/ and vars/ in a role will not be made available to the rest of the play.
> 
> (Which means for me that when False they will be available)
> 
> So this documentation is just wrong? If so please indicate this on the current documentation. This is extremley confusing!

The documentation is completely wrong.  The addition of docs for `private` was an oversight.  Someone had the idea for such a feature, but that feature was never implemented.  It is unfortunate that the docs for `private` have stuck around for this long.  A recent change in devel for the 2.6 release aims to resolve the documentation error:

> private
> This option is a no op, and the functionality described in previous versions was not implemented. This option will be removed in Ansible v2.8

http://docs.ansible.com/ansible/devel/modules/include_role_module.html

**Comment by kiorky** [comment]
https://github.com/ansible/ansible/pull/35167#issuecomment-388706351

**Comment by AnishBAH** [comment]
So I'm encountering a similar case to this and am not sure on why the behavior is happening.

ansible-playbook 2.6.0.dev0
  config file = /home/ansible/proj-ansible/aws-modernization/.ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible-2.6.0.dev0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.14 (default, May  2 2018, 18:31:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
Using /home/ansible/proj-ansible/aws-modernization/.ansible.cfg as config file

Code in question:
name: "Create Custom EC2 based on Latest AMI"
  include_tasks: ec2_make.yml
  tags: hec2

name: "Execute Hardening Role on Custom Host"
  include_role:
    name: hardening
  ignore_errors: yes
  delegate_to: "{{ item.private_ip }}"
  with_items: "{{ ec2custom.instances }}"
  tags: hec2```

Outcome:
`TASK [include_role : hardening] **********************************************************************************************************************************************************
task path: /home/ansible/proj-ansible/aws-modernization/roles/ami_upgrade/tasks/main.yml:14
fatal: [localhost]: FAILED! => {"msg": "'ec2custom' is undefined"}`

Previously, in `Ansible 2.4.x` the include_role would handle this fine and recognize that a custom fact was being set during the ec2_make.yml stage and then accept that fact as part of a delegation to the role that was being included--as the tasks in question within that role were applicable to the newly created ec2 instance. This is no longer the case. Now, it seems to be preempting the requirement and as a result failing. Any insight into this would be huge.

Please excuse the formatting, its not working well for me.

**Update**: I ended up downgrading to 2.5.x, and then had to switch over from `include_tasks` to `import_tasks` and `include_role` to `import_role` for my plays to work. Most likely for the better. Its likely still an issue in 2.6.x, will have to revisit once the RC is out.

**Comment by mihai-satmarean** [comment]
That is very bad, majority of our design for Ansible relied on that functionality, we had developed some concept of service with Ansible that includes roles and uses their variable files and defaults for merging in the running context, that now we learn that is not as intended. 
We recently switched to Ansible 2.5 and we also find that the documentation is wrong for import_role and include_role. We need that functionality as it was. 
Any chance we can get it work like that? I don't even see the point of import/include without it.
Thanks!

**Comment by guilhermesteinmuller** [comment]
Is there any workaround for those who want to use include_role exposing the role's variables?

**Comment by kiorky** [comment]
> Is there any workaround for those who want to use include_role exposing the role's variables?

yes, @guilhermesteinmuller , using my PR.

**Comment by ivandeex** [comment]
> Is there any workaround for those who want to use include_role exposing the role's variables?

@guilhermesteinmuller a couple workarounds mentioned up this thread (no PRs or other patching):
- `set_fact` in the inner role: https://github.com/ansible/ansible/issues/21890#issuecomment-298425325
- `include_vars` in the calling role: https://github.com/ansible/ansible/issues/21890#issuecomment-298672579

**Comment by kiorky** [comment]
> (no PRs or other patching):

Well; this does not behave exactly as including a role ...

**Comment by ivandeex** [comment]
These are workarounds not pretending to behave exactly alike. As @sivel  mentioned above https://github.com/ansible/ansible/issues/21890#issuecomment-387528252 current include_role/import_role behavior is by design and your PR is considered a _new feature_. Before it is accepted into mainline, we are stuck with workarounds.

**Comment by kiorky** [comment]
> a new feature.

No it is not, it is a bugfix only PR (was working and well documented in 2.3, partially broken in 2.4, totally since 2.5).
@sivel hides behind false assumptions

**Comment by ivandeex** [comment]
@kiorky Btw 2.6 is already out. Do you expect your PR (re-)fixed in 2.7 or 2.8?

**Comment by bcoca** [comment]
@kiorky as the one that actually wrote the original and added the `private` option to documentation, I can confirm @sivel is correct, the feature was never implemented.

**Comment by kiorky** [comment]
But still documented and understood as-is by all the community, see all bugs sitting around and there on this repo or on the internet.

**Comment by uhmfa** [comment]
While include_role (or import_role) cannot expose the included role's default and role variables, it cannot match the "role:" statement, then it is not replacing it with backward compatibility.
The doc says that "This frees roles from the roles: directive and allows them to be treated more as tasks" but should also explain the cost to pay. For the project I'm working on this is disruptive.
Also doc is even saying about using 'private' parameter: If False the variables from defaults/ and vars/ in a role will not be made available to the rest of the play.
But putting this to true doesn't work so clearly bad doc here.
The workaround of using include_vars breaks the accepted and expected native variables precedence causing more problems for us, so not an option.

**Comment by sivel** [comment]
This functionality has been added in https://github.com/ansible/ansible/pull/41330 and will be included in the 2.7 release.

**Comment by ansiblejunky** [comment]
Just my 2 cents on this topic since I just saw this. An Ansible Role should behave similar to a modular object. The `defaults` and `vars` for Ansible Roles are `private` variables only used by the Role to perform the tasks it needs. If a Role wants to make something `public` then the Role should do so by using the `set_fact` module.  I feel this is how it should be. The workarounds stated above are fine if you really want to use that method to expose private variables. Personally it seems to beg for a refactoring of your code if you are having to do these workarounds. Seems the variables should be defined at a different level - perhaps in your inventory at group_var or host_var level and overridden by a role if necessary.  Keep the Ansible Roles as "encapsulated" as possible. This allows them to be reusable.

**Comment by theboeh** [comment]
> Seems the variables should be defined at a different level - perhaps in your inventory at group_var or host_var level and overridden by a role if necessary. Keep the Ansible Roles as "encapsulated" as possible. This allows them to be reusable.

Once you have more than a handful of inventories that becomes a massive pain. Allow me to present an example:

You have mulitple developers developing Docker images. These developers are also responsible for the development of the roles that will deploy, setup, and instantiate these images. Now, there is a shared piece of information that multiple of these roles need, maybe it's a directory on the host, maybe it is a the name of a Docker network. As good developers should they use a variable for this. So to use the role you need to set the variable and then it will work. The developers realize that their individual roles containing a default doesn't make sense as it is a shared setting. They should use the same setting as the other developers.

Now, if you are in the situation above and have maybe 2 or 3 inventories, it's not too bad. Just add the variable in the group_vars of the inventory and you are fine. But, I have this situation but with 20 inventories. Now the developers have to go an add this setting to 20 inventories? That's a lot of annoying and error prone work.

It would seem the better solution would be to have a role that lays out these settings at a default priority. That way the developers can include that role in their's and get reasonable defaults while allowing of the quirks of the individual inventories override them if needed.

**Comment by Jean-Daniel** [comment]
@ansiblejunky: While using `set_fact` may be a clean solution to expose variable, it also introduce module ordering issues. The modules that expose a variable MUST be run before the one that consume it.

With the actual `role`, variables are exported at parsing time, which is far more helpful.
