### ISSUE TITLE
Provide recursive flavor of "copy"

### ISSUE THREAD

**Issue by vmalloc** [ansible/ansible#2190]
When deploying code to a remote server it is useful to have a local directory sync up to the server, and respond when an actual change occurred.

Currently this can be done with jumping through hoops (like rsync/ tar -u + copy etc.), but it would be way more elegant to have this functionality right inside ansible.

**Comment by mpdehaan** [comment]
Been asked for numerous times.   This was #1808 but I'm open to folks attempting to take a better crack at it.

Otherwise, I'll leave this ticket in the queue.

**Comment by mpdehaan** [comment]
local_action: rsync seems to be the established idiom for this now.

**Comment by vmalloc** [comment]
Is this really a valid solution? rsync uses ssh as-is, completely ignoring any current or future details of setting up the connection (via ansible). I suspect it will also cause havoc in conjunction with various sudo (or sudo-user) scenarios. I really think it's better as a native ansible module that is more similar to `copy`...

**Comment by aquach** [comment]
+1, rsync can't handle rsyncing into protected directories like `/etc/` that are normally accessible with sudo mode and the `copy` module. That means I have to `rsync` into `/tmp/` and then move, which is really counter to idempotence and keeping tasks clean.

**Comment by vmalloc** [comment]
Agreed. This is exactly why I need it. It is much more robust to pass all authentication-related parameters to ansible rather than include it in two places so that rsync would use it too. Plus, people keep some crazy stuff in their ~/.ssh/config's, so it is likely to break often for different users.

@mpdehaan - your opinion?

**Comment by bcoca** [comment]
You can already do this (mostly) with ansible already

file: path=/my/dest/{{item}} state=directory
with_lines: find /srcdir -type d

copy: src={{item}} dest=/my/dest/{{item}}
with_lines: find /srcdir -type f

**Comment by aquach** [comment]
That works pretty well, but you'd have to use `grep` or `cd` to get rid of the extraneous `srcdir` path. ie in your example you'd copy all the stuff to `/my/dest/srcdir/...` rather than omitting the `srcdir` part. So it's totally possible with Ansible, but a module to facilitate this (maybe even just a wrapper to your two tasks, with some modifications) would be helpful.

**Comment by vmalloc** [comment]
This doesn't take care of --delete...

**Comment by aquach** [comment]
Right, delete is also really useful. Forgot about that. A module that did a recursive copy to a temp dir on the remote followed by a rsync from the temp dir to the final dir might work. Maybe a module with narrower semantics than a recursive copy, like "sync" or something, which accomplishes the same effect as `rsync -avz --delete`

**Comment by bcoca** [comment]
You can use jinja's replace filter to rewrite to change the paths.

To delete you need to run a find remotely first and contrast the lists

Brian Coca

**Comment by vmalloc** [comment]
I think the direction is to have this as a primitive, not as a bunch of hacks to make it work somehow (with corner cases that might not work).

**Comment by vmalloc** [comment]
I was just resenting the claim that local action rsync is the established idiom for it, because it is lacking.

**Comment by mpdehaan** [comment]
You've been posting on this thread for two months, time to let it go.

**Comment by vmalloc** [comment]
@mpdehaan well, you closed the issue with an unsatisfying answer that does not solve the problem. How would you like us to proceed?

**Comment by mpdehaan** [comment]
Ideally not like you are doing now.

**Comment by vmalloc** [comment]
Yes, I understand bugging isn't going to solve it. Care to at least reopen the issue so that it's on the list? I don't expect it to be solved tomorrow, I just don't want it to be forgotten or assumed fixed...

**Comment by mpdehaan** [comment]
The best thing that can happen is for you to work on an action plugin that
can do it.

**Comment by voidzero** [comment]
Hi, I'm not a coder, sorry about that. But I have a few suggestions about this "copy recursively" approach.

One method would be to tar a directory, send it to the remote, extract it in a remote temp dir, compare files and replace those that are changed and delete those that are absent. I understand this does send the tar file to the remote every time, not convenient with large tarballs, I admit.

Another similar method would be: send to remote, unpack in temp dir and rsync the dest with the tempdir. Problem is that I see no way to verify whether files have been changed unless you use rsync -v and do stuff with the output.

Just my $0.02, feel free to shoot holes in this suggestion.

**Comment by pfalcon** [comment]
Please help testing latest patch to add this functionality. #4375 .
