### ISSUE TITLE
serial cause play to fail after one failed host

### ISSUE THREAD

**Issue by r0bj** [ansible/ansible#21965]
- Bug Report

```
ansible 2.2.1.0
  config file = /Users/rob/work/ansible/test/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
ansible.cfg:
```
[defaults]
hostfile = hosts

[ssh_connection]
pipelining = True
ssh_args = -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes

[privilege_escalation]
become = True
become_ask_pass = True
```

hosts:
```
10.14.30.116
10.14.30.117
10.14.30.118
```

##### OS / ENVIRONMENT
Mac OS: 10.12.3

##### SUMMARY
Using `serial` cause play to fail after one failed host.
Without use of `serial` play works ok, only one host fail.

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  become: yes
  gather_facts: no
  serial: 1
  tasks:
  - fail:
      msg: fail
    when: inventory_hostname == '10.14.30.116'
  - debug:
      msg: task
```

##### EXPECTED RESULTS
```
TASK [fail] ********************************************************************
fatal: [10.14.30.116]: FAILED! => {"changed": false, "failed": true, "msg": "fail"}
skipping: [10.14.30.117]
skipping: [10.14.30.118]

TASK [debug] *******************************************************************
ok: [10.14.30.117] => {
    "msg": "task"
}
ok: [10.14.30.118] => {
    "msg": "task"
}
	to retry, use: --limit @/Users/rob/work/ansible/test/test.retry

PLAY RECAP *********************************************************************
10.14.30.116               : ok=0    changed=0    unreachable=0    failed=1
10.14.30.117               : ok=1    changed=0    unreachable=0    failed=0
10.14.30.118               : ok=1    changed=0    unreachable=0    failed=0
```

All hosts are processed except the failed one.

##### ACTUAL RESULTS
```
TASK [fail] ********************************************************************
fatal: [10.14.30.116]: FAILED! => {"changed": false, "failed": true, "msg": "fail"}
	to retry, use: --limit @/Users/rob/work/ansible/test/test.retry

PLAY RECAP *********************************************************************
10.14.30.116               : ok=0    changed=0    unreachable=0    failed=1
```

Whole play is stopped due to failed host.

Removing `serial: 1` from the play definition cause the play works as expected.

**Comment by bjolivot** [comment]
notabug
Hello, you can use max_fail_percentage
http://docs.ansible.com/ansible/playbooks_delegation.html#maximum-failure-percentage

**Comment by r0bj** [comment]
@bjolivot I'm not sure what do you mean, according to your link:
```
By default, Ansible will continue executing actions as long as there are hosts in the group that have not yet failed.
```
So without use of `max_fail_percentage` not failed hosts should be processed.

**Comment by bjolivot** [comment]
with serial: 1 each host is a group

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

As mentioned in comments above, this is expected behaviour for serial as it 'defines the group' of hosts that are being considered.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
