### ISSUE TITLE
Macro expansion of lookup plugins within the 'environment' keyword results in arrays

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#2196]
This happens to work fine:

```
- shell: echo $ENV(HOME)
```

However:

```
- shell: echo $FOO
  environment:
      FOO: $ENV(HOME)
```

In the above, FOO in the environment is set to the value of a Python array containing the value, so it's being templated weird.  

Uppercase macro expansion of a lookup plugin should always result in a string.

**Comment by dhozac** [comment]
Should be fixed now, we'll see if there's any fall-out from the fix... Might be a location or two that needs an expand_lists=False.

**Comment by bcoca** [comment]
## np, prime suspect should always be last commit to the file.

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno
