### ISSUE TITLE
match and search filters missing documentation

### ISSUE THREAD

**Issue by jamesmontalvo3** [ansible/ansible#21967]
##### ISSUE TYPE
Documentation Report

##### COMPONENT NAME
jinja filters docs

##### ANSIBLE VERSION
N/A

#### SUMMARY
Neither the Filters documentation [1] nor the Jinja2 docs [2] that Filters docs reference mention the `match` or `search` filters. Those filters are mentioned in the Tests documentation [3], but only briefly.

This is a documentation issue only.

[1] http://docs.ansible.com/ansible/playbooks_filters.html
[2] http://jinja.pocoo.org/docs/2.9/templates/#builtin-filters
[3] https://docs.ansible.com/ansible/playbooks_tests.html

**Comment by sivel** [comment]
They  are actually tests and not filters, so they are documented in the correct place.  What additional documentation are you looking for?

**Comment by jamesmontalvo3** [comment]
[3] above refers to them as filters, and they're invoked like filters. @sivel why do you say they're not filters? I went to the filter page [1] and searched "regex" and found the `regex_replace` filter but was surprised not to find a filter for match/search. Took a bit of googling before I found them, and initially I probably clicked passed the "Tests" documentation because it didn't seem applicable (assumed it was for unit testing or something). Having a line in "Filters" documentation that says something like "For regular expression `search` and `match` filters, see Tests" would probably save some people some time.

**Comment by sivel** [comment]
`search` and `match` used to be filters, before Ansible supported adding tests to jinja2.  So there may be left over docs that weren't properly updated.  That is something we can work on fixing.

As far as them being called like filters, that is due to backwards compatibility functionality we added.  Because they were filters at one point, we couldn't break playbooks, so we load tests as both tests and filters, so that they can be used both ways.  The preferred way to use a test is the `foo is defined` format.

Per the jinja2 docs:

> Beside filters, there are also so-called “tests” available. Tests can be used to test a variable against a common expression. To test a variable or expression, you add _is_ plus the name of the test after the variable. For example, to find out if a variable is defined, you can do name is defined, which will then return true or false depending on whether name is defined in the current template context

Making them tests was done to support using these functions that were "test" like, in jinja2 filters such as `map` or `selectattr`.

**Comment by jamesmontalvo3** [comment]
By `foo is defined` format do you mean as opposed to `{{ foo | defined }}` format (if that's even possible)? If so, how would you use `match` and `search` in `foo is defined` format? 

```yaml
- debug: "filter format"
  when: 'alphanumeric | search("[a-zA-Z0-9]")'

# Like this?
- debug: "foo is defined format ???"
  when: 'alphanumeric is search("[a-zA-Z0-9]")'

# Or this?
- debug: "foo is defined format ???"
  when: 'alphanumeric search "[a-zA-Z0-9]"'
```

It seems to me that from a functionality standpoint a Test is a Filter, but a Filter is not necessarily a Test. True?

**Comment by sivel** [comment]
Within ansible, ansible provided tests are also accessible as filters.  However ansible provided filters are not tests.

Any test shipped directly with jinja2, is only available as a test, and the `| defined` syntax would not work, as it comes from upstream jinja2.

Using the `is` syntax with search or match would look like:

 ```
when: 'alphanumeric is search("[a-zA-Z0-9]")'
```

**Comment by sivel** [comment]
Typically the goal of a filter, is to manipulate some data into a similar data type, but modified in some way.  Such as the `lower` filter, manipulating the value of a string to be all lowercase.

The goal of a test, is to evaluate whether some test is truthy.  The `search` and `match` filters return a boolean value, letting you know whether it evaluates truthy or not.  As opposed to manipulating the actual value of the data in some way.

**Comment by tyranron** [comment]
@sivel with [latest deprecation of using tests as filters](https://docs.ansible.com/ansible/2.5/porting_guides/porting_guide_2.5.html#jinja-tests-used-as-filters) could you clarify a bit how to use them with `map`/`selectattr` now?

I have the following condition in my playbook:
```yaml
  changed_when:
    - check_result.rc == 0
    - (check_result.stdout|trim).split("\n")
        |map('search', ' unchanged')
        |reject('eq', true)
        |list|length != 0
```
And it complains with deprecation warning:
```
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|search` instead use `result is search`. This feature will be removed in version 2.9. Deprecation warnings can 
be disabled by setting deprecation_warnings=False in ansible.cfg.
```

**Comment by thokari** [comment]
Not sure if this is the place to ask this, but am I correct in finding this behaviour inconsistent with the documentation?

From the docs:
> ‘match’ requires a complete match in the string, while ‘search’ only requires matching a subset of the string.

This is a test I made (Ansible 2.6.3, Python 2.7.15):

```
---
- hosts: localhost

  vars:
    test_var: start_of_the_word-something

  tasks:
    - name: Expecting 'match' filter to refuse partial match at the end
      assert:
        that: test_var is not match('something')

    - name: Expecting 'search' filter to match
      assert:
        that: test_var is search('something')

- hosts: localhost

  vars:
    test_var: start_of_the_word-something

  tasks:
    - name: Expecting 'match' filter to refuse partial match at the begginning
      assert:
        that: test_var is not match('start_of_the_word')

    - name: Expecting 'search' filter to match
      assert:
         that: test_var is search('start_of_the_word')
```

Output:

```
PLAY [localhost] *************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Expecting 'match' filter to refuse partial match at the end] *********************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Expecting 'search' filter to match] ************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

PLAY [localhost] *************************************************************************************************************************************************************************************************************************************************************

TASK [Expecting 'match' filter to refuse partial match at the begginning] ****************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "test_var is not match('start_of_the_word')",
    "changed": false,
    "evaluated_to": false
}

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1
```

I would expect both assertions regarding `match` to either fail or pass, regardless how "a subset of the string" should be interpreted...

**Comment by samccann** [comment]
docs fix - change this section to say tests not filters - https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html#testing-strings
