### ISSUE TITLE
Error : Insufficient RAM while installing ansible tower 

### ISSUE THREAD

**Issue by varunkukreja131** [ansible/ansible#21973]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
Ansible Tower Setup Process

##### ANSIBLE VERSION

```
As I run the ansible setup playbook , i.e. setup.sh , it shows error : insufficient. 
this happens even though the RAM in my system in 4 GB, which should be sufficient as according to the documentation of ansible Twoer requirements.

Please suggest resolution of this issue, 
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by sivel** [comment]
For tower inquiries please utilize https://support.ansible.com/ for support.  This repository is for the open source ansible project.

**Comment by varunkukreja131** [comment]
Hi,

This link is not accessible.

Please suggest where we could get some assistance regarding Ansible tower
installation .

We are facing issue  :

Error occurring During Ansible tower installation :     /var may not meet
minimum space requirement. ( Even though 20 GB is allocated to /var
partition)

Thanks And Regards
Varun Kukreja

**Comment by sivel** [comment]
https://access.redhat.com/products/ansible-tower-red-hat/
