### ISSUE TITLE
aix_inittab: RETURN needs documenting

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#21983]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
aix_inittabt

##### SUMMARY
@molekuul It appeared that the `RETURN` block wasn't formatted correctly in the original PR https://github.com/ansible/ansible/pull/21511 this wasn't spotted by our CI tests (which I'll look into)

This caused the production of webdocs to fail, so I removed it in https://github.com/ansible/ansible/commit/1d2349872ade6b877bee6cdad586cce78d3a159f#diff-230f216d211a01e63630e56a737d6865

Could you please add it again, details on how to format the `RETURN` block can be found at http://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html#return-block

Thanks in advance

**Comment by molekuul** [comment]
@gundalow , 

How do I handle this Bug? 
Must I repair this bug in my own fork, and than request a new pull request? or must this be handled in the original pull request?

Kind regards,

Joris Weijters

**Comment by gundalow** [comment]
@molekuul As the original PR has been merged just create a fresh PR from `devel`
