### ISSUE TITLE
Adding text to the end of an existing line

### ISSUE THREAD

**Issue by krishnachaitanya511** [ansible/ansible#21981]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
Ansible

##### ANSIBLE VERSION

```
2.2.X
```

##### SUMMARY
I would like to add text to my existing file. Here is the text to be added and existing text below
Existing Text: **java.extended.properties=-Xmx1024m -Xms256m -XX:-HeapDumpOnOutOfMemoryError -XX:SurvivorRatio=128 -XX:MaxTenuringThreshold=0  -XX:+UseTLAB -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled**

Modified One should be: **java.extended.properties=-Xmx1024m -Xms256m -XX:-HeapDumpOnOutOfMemoryError -XX:SurvivorRatio=128 -XX:MaxTenuringThreshold=0  -XX:+UseTLAB -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Dfile:///// ..etc etc**

##### STEPS TO REPRODUCE

```
Which Ansible Module would be good for this?
```

##### ACTUAL RESULTS

```
Please provide the TEXT modification Modules of Ansible
```

**Comment by bjolivot** [comment]
Hello, you could use lineinfile module:
http://docs.ansible.com/ansible/lineinfile_module.html
For help, prefer irc channel (#ansible in freenode irc network) 
or forum (https://groups.google.com/forum/#!forum/ansible-project)
notabug

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
