### ISSUE TITLE
User module on MacOS treats crypted password as cleartext

### ISSUE THREAD

**Issue by lukehoersten** [ansible/ansible#22006]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- User module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /Users/luke/Code/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```
[defaults]
lookup_plugins = ../../../ansible/plugins/
roles_path = ../../../ansible/roles/
allow_world_readable_tmpfiles = True

[ssh_connection]
pipelining = True
ssh_args = -o ControlMaster=auto -o ControlPersist=60s
```

##### OS / ENVIRONMENT
- Command Host: MacOS
- Target Host: MacOS

This module works fine when provisioning a Linux target.

##### SUMMARY
The user module allow setting a user password with a crypted value as defined in the documentation:
`Optionally set the user's password to this crypted value.`

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/user.py

##### STEPS TO REPRODUCE
1. Use `user` module to create/update a user's password
2. On MacOS, the user's password is the cleartext value of the crypted text. For example: `KE5mOgXcDDgFk` instead of `password123`.

```yaml
- name: add users
  become: yes
  user:
    name: "user1"
    password: "KE5mOgXcDDgFk"
```

##### EXPECTED RESULTS
Expected the password to be `password123`

##### ACTUAL RESULTS
Password was actually `KE5mOgXcDDgFk`

**Comment by lukehoersten** [comment]
This causes a pretty big security hole. Any objections to making a fix a top priority?

**Comment by sivel** [comment]
Just to add a reference to the documentation for the password field, as it seems you only referenced the first sentence of the documentation:

> Note on Darwin system, this value has to be cleartext. Beware of security issues.

http://docs.ansible.com/ansible/user_module.html

**Comment by lukehoersten** [comment]
Ah I didn't see that. Perhaps it should be more prominent. Does this mean because it's documented it will never be fixed?

**Comment by bcoca** [comment]
it seems to be a limitation of the platform

**Comment by sivel** [comment]
After a quick search around the internet, I do not see a way to provide Mac with a crypted password.  The `dscl` command does not support supplying a crypted password.

**Comment by lukehoersten** [comment]
Ok thanks guys. My mistake.

**Comment by lukehoersten** [comment]
It looks like as of Lion, passwords are managed in a different way on MacOS: https://apple.stackexchange.com/questions/186893/os-x-10-9-where-are-password-hashes-stored
