### ISSUE TITLE
Unable to Run Fireball

### ISSUE THREAD

**Issue by ankitjain-fsl** [ansible/ansible#2201]
Hi Team,

If i am tryting to run fireball in my playbook i am getting the below error message.

TASK: [Lauching Fireball Daemon to  Remote System] *********************
fatal: [ld1101] => python-keyczar must be installed to use fireball mode

FATAL: all hosts have already failed -- aborting

PLAY RECAP *********************
ld1101                         : ok=1    changed=0    unreachable=1    failed=0

I am running it using pythn 2.6 so why its asking for python-keyczar package needs to be installed ?

Regards

Ankit

**Comment by mpdehaan** [comment]
Fireball mode has additional dependencies beyond standard-ansible.

This is brought up in the docs :)

**Comment by ankitjain-fsl** [comment]
So you mean to say Fireball functionality is still not available ?

**Comment by ankitjain-fsl** [comment]
Also one more strange thisng i noticed. A normal user can send email to other user as root how it is possbile ?

I ran the below command and able to send mail from root from a romote machine using ansible. In heares aslo i did not see my infomration,

ansible Desktop -m mail -a "from=root subject=testing"

Regads

Ankit

**Comment by mpdehaan** [comment]
Fireball's been a feature for quite some time.   Please read the previous
message and the documentation.

**Comment by mpdehaan** [comment]
On Tue, Feb 26, 2013 at 9:27 AM, ankitjain-fsl notifications@github.comwrote:

> Also one more strange thisng i noticed. A normal user can send email to
> other user as root how it is possbile ?

Because SMTP allows you to specify anything for the from line.

**Comment by ankitjain-fsl** [comment]
OK Thx

**Comment by mpdehaan** [comment]
BTW, these are really questions more so than bugs, can you please use the mailing list for these?

**Comment by datasmid** [comment]
Stale links in the Ansible docs, not clear if fireball mode on mac has a bug or if it is an undocumented/unportable feature. We need pip url and version!

**Comment by jctanner** [comment]
@datasmid please do not report issues as comments in closed tickets. Use a new/open bug or shoot an email to the ansible-project mailing list.

Fireball mode has been deprecated in favor of "accelerated" mode.
