### ISSUE TITLE
Unable to use subversion module with https and self-signed certificats

### ISSUE THREAD

**Issue by arsatiki** [ansible/ansible#2202]
My client uses SVN and HTTPS for their source code repository access. The certificate is self-signed. The subversion module does not support this:

> svn: OPTIONS of '...': Server certificate failed: issuer is not trusted (...)

On the command-line I can circumvent this via --trust-server-cert. However, there is no corresponding facility within the subversion module itself.

**Comment by mpdehaan** [comment]
Thanks...

I think we should add an option to the SVN module, trust=<boolean> that
does this.  (Probably should default to non-trust).

I'll take a look at doing this shortly.

**Comment by mpdehaan** [comment]
Hi,

I've fixed this on 0e1ba5e on the development branch (Ansible 1.1).  I decided to always add the flag so someone would not need to remember to add it.  It seems reasonable as nearly all repos are going to be self-signed.

If you want to use this with a prior version of Ansible you can copy the library/subversion mdoule and it should work fine with 1.0 (or even 0.9)

Let me know if you hit any other issues (michael dot dehaan @ gmail).

Thanks!

Michael
