### ISSUE TITLE
Need to make it so lists defined in group_vars files are available to with_items

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#2203]
There is no reason with_items can't use inventory scoped variables anymore.

It used to generate tasks per object but this is not the case, so it looks like it just needs to template variables using some better context.

Example:

with_items: $foos

where $foos is defined in groupvars/webservers

**Comment by dhozac** [comment]
That does work fine. The only case where it doesn't work is for include, which iterates the list and duplicates the tasks/plays for each item in the list. Fixing that would require some rather major refactoring, creating some concept of task groups per include file with data such as with_items and vars, and we'd have to make inject more accessible to things not in Runner, as it would need to be used from the PlayBook code to instantiate runners appropriately.

**Comment by mpdehaan** [comment]
Hmm, yay, it does.

I had groupvars in the wrong place in my test.

And you are correct about includes.

So to answer the original question, define the list in groupvars/foo or
hostvars/foo (hosts override groups, subgroups override parent groups), and
fire away!

**Comment by mpdehaan** [comment]
I had something wrong in my test, so correct -- this has _not_ regressed.
