### ISSUE TITLE
Hostvars docs typo

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#2206]
{{ hostvars['my.host.fqdn']['ansible_distribution'] }}

host_vars

**Comment by dhozac** [comment]
No, hostvars is right. host_vars is the name of the directory containing per-host YAML. I personally blame you :-)

**Comment by mpdehaan** [comment]
Hmm, yes.

I do blame me, hostvars needs some new alias in the docs, like 'all_vars'
to avoid this confusion, maybe.
