### ISSUE TITLE
ANSIBLE_VERBOSITY environment variable cannot be used to control verbosity

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#22087]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
2.2.1
2.1.0
2.3.0
```

##### CONFIGURATION
```
ANSIBLE_VERBOSITY=vvv
```

##### OS / ENVIRONMENT
N/S

##### SUMMARY
I was surprised to find out that there is no way to control ansible verbosity level via an environment variable. There are environment variables for even the weirdest things like `ANSIBLE_COLOR_DEBUG` but somehow none for verbosity.

The closes relative is the `ANSIBLE_DEBUG` variable but this one is enabling an extremely verbose mode, one that makes it useless for most use cases.

We also got a recommendation for [implementing this inside a custom callback](http://stackoverflow.com/questions/42510032/how-to-change-ansible-verbosity-level-without-changing-the-command-line-argument) but this would not work for several reasons:

* we call multiple ansible playbooks and some of they may already have custom callbacks
* this is the kind of feature that is supposed to be part of the core.

We need an implementation that allows use to specify different verbosity levels that do correspond to: `None`, `-v`, `-vv`, `-vvv` and `-vvvv`.

**Comment by karniemi** [comment]
It would have been nice if the difference and use case between ANSIBLE_DEBUG and ANSIBLE_VERBOSITY was documented? Now both of these variables control the ansible log verbosity somehow, but the user has no idea why there are two different configuration variables... if he by chance happens to even notice that there are two different variables...
