### ISSUE TITLE
Feature Idea: Add module for Cisco AireOS devices (WLCs)

### ISSUE THREAD

**Issue by cognifloyd** [ansible/ansible#22098]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
New networking module

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/cognifloyd/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Please create a new module for Cisco AireOS devices such as their Wireless LAN Controllers.
Configuration is over an SSH cli that looks similar to IOS and other devices.

The device I'm targeting is [Cisco 2500 Series WLC](http://www.cisco.com/c/en/us/products/wireless/2500-series-wireless-controllers/index.html). All of the other Cisco WLCs use the same OS, but might use later versions. Though the docs don't say "AireOS" the wifi guy I work with says that's what the OS on them is called. The docs call it "Cisco Unified Wireless Network Software Release" or "Cisco Wireless Release" (e.g. see the "bulletins" [here](http://www.cisco.com/c/en/us/products/wireless/2500-series-wireless-controllers/bulletin-listing.html) and [here](http://www.cisco.com/c/en/us/products/wireless/8500-series-wireless-controllers/bulletin-listing.html)).

**Comment by gundalow** [comment]
Hi,
Thanks for the suggestion, I'm not sure if this is something we'd be looking at creating within Ansible, though it sounds like a useful suggestion.

FYI We have a weekly Networking Meeting on IRC[1]. We are currently focusing on finishing off the network modules for the Ansible 2.3 release. Once that's complete feel free to join the meeting and we can guide you to create some modules.

What level of functionality would you be looking for?

Could you please provide what's returned by `show version`


[1] https://github.com/ansible/community/issues/114

**Comment by calfonso** [comment]
needs_contributor Looking for the community to assist with this. Happy to help direct and assist.

**Comment by timherrm** [comment]
This is what show sysinfo looks like on an Cisco 5500 Series Wireless Controller:

(Cisco Controller) >show sysinfo 

Manufacturer's Name.............................. Cisco Systems Inc.
Product Name..................................... Cisco Controller
Product Version.................................. 8.1.102.0
RTOS Version..................................... 8.1.102.0
Bootloader Version............................... 8.1.102.0
Emergency Image Version.......................... 8.1.102.0

Build Type....................................... DATA + WPS

System Name...................................... XXXXXXXXXXXXXXXXXXXX
System Location.................................. XXXXXXXXXXXXXXXXXXXX
System Contact................................... XXXXXXXXXXXXXXXXXXXX
System ObjectID.................................. 1.3.6.1.4.1.9.1.2170
Redundancy Mode.................................. SSO
IP Address....................................... XXXXXXXXXXXXXXXXXXXX
IPv6 Address..................................... ::
System Up Time................................... 38 days 4 hrs 19 mins 44 secs
System Timezone Location......................... 
System Stats Realtime Interval................... 5
System Stats Normal Interval..................... 180
Configured Country............................... DE  - Germany
Operating Environment............................ Commercial (10 to 35 C)
Internal Temp Alarm Limits....................... 10 to 38 C
Internal Temperature............................. +24 C
Fan Status....................................... OK

State of 802.11b Network......................... Enabled
State of 802.11a Network......................... Enabled
Number of WLANs.................................. 0
Number of Active Clients......................... 0

Burned-in MAC Address............................ XXXXXXXXXXXXXXXXXXXX
Power Supply 1................................... Present, OK
Power Supply 2................................... Present, OK
Maximum number of APs supported.................. 1500
System Nas-Id.................................... XXXXXXXXXXXXXXXXXXXX
WLC MIC Certificate Types........................ SHA1/SHA2

**Comment by cognifloyd** [comment]
@ktbyers just pointed out[1] that netmiko can work with Cisco WLC[2]. Perhaps that could be ported, or portions of it could be reused. It looks like netmiko has an MIT license, so reusing parts of it shouldn't be a problem.

@gundalow are there any other ansible modules that were based on netmiko?

[1] napalm-automation/napalm#376
[2] https://github.com/ktbyers/netmiko/blob/develop/netmiko/cisco/cisco_wlc_ssh.py

**Comment by calfonso** [comment]
@cognifloyd a fairly recent commit to our devel branch has an aireos_command module. Try it out and if it's not sufficient, go ahead and re-open the issue. Thanks!
