### ISSUE TITLE
Ansible should report that a handler is missing before executing the task calling it, and not after

### ISSUE THREAD

**Issue by pako-pl** [ansible/ansible#22100]
Ansible notices that a "notify" handler is missing only after executing a task:

```
TASK [crontab-master : Upload crontab] *************************
ERROR! The requested handler 'crontab updated' was not found in either the main handlers list nor in the listening handlers list
```

This causes issues - in this example crontab was updated, but the daemon was not notified about the changes. Running the task again won't fire the handler, as the task was already executed. If Ansible checked if the handler exists before running the task, the issue could be avoided. The task wouldn't run until the missing handler issue got fixed and then it would execute and fire the handler properly.

This a frequent situation for us as we run the playbooks limiting them to only some tags.

**Comment by bcoca** [comment]
handlers can now be added dynamically into a play, there is no way to know if it 'will exist' when needed until the execution reaches that point.

**Comment by pako-pl** [comment]
Most tasks don't add new handlers dynamically - and for those checking if the handlers mentioned in the "notify" section exist just before executing the task makes sense.

Moreover, I don't think the task would be dynamically adding the handlers for itself - it's probably a very rare scenario.

**Comment by bcoca** [comment]
not the task, the handlers themselves can be added dynamically:

``` yaml
- include_role: name=role_with_handlers
  when: something != somethingelse
```

or 

```yaml
handlers:
  - include: file_with_handlers_{{myenv}}.yml
```

**Comment by pako-pl** [comment]
Sure, but when a given task with a "notify" section starts executing, the list of available handlers is already known? I don't mean the initial playbook parsing stage, but the actual execution of the tasks. Unless it's possible to use "notify" on an "include".

**Comment by bcoca** [comment]
no, that list can change AFTER the task finishes and notifies, that is the whole point. Yes you can notify the include itself (that is not an issue, it is known), the problem is you can notify tasks inside the include, which are not known until the include 'happens'.

**Comment by pako-pl** [comment]
Okay, now I understand what you mean. A task can call notify on handlers that do not exist yet, which will be included after the task runs, but before the playbook reaches the handler execution stage. The change I proposed would make including handlers after the task runs impossible. So I think it is better to leave it as is.
