### ISSUE TITLE
File is copied even when changing mode, group or owner fails

### ISSUE THREAD

**Issue by liuzm7188** [ansible/ansible#22116]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME
copy
##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT
SUSE Linux Enterprise Server 12 SP1
##### SUMMARY
`args: 'src=/local/test.sh dest=/remote/ group=admin1 mode=844 owner=admin1  force=yes '`

##### STEPS TO REPRODUCE

/ansible/module_utils/basic.py
add 'os.unlink(path)' to line in  936,968 and 1006

##### EXPECTED RESULTS

It will delete the transported file when execute failed.

##### ACTUAL RESULTS
Actually, It  deletes the transported file when execute failed

Edited by Gundalow to improve formatting

**Comment by cptchips** [comment]
Not sure to fully understand this issue. But I'm suspiscious about the 
> mode=844

According to the documentation:
> For those used to /usr/bin/chmod remember that modes are actually octal numbers (like 0644).

Furthermore
> Leaving off the leading zero will likely have unexpected results

Hope it helps

**Comment by liuzm7188** [comment]
args: 'src=/local/test.sh dest=/remote/ group=admin1  force=yes '
In my manager host , there is no admin1 group, so it excutes failed. But the test.sh still transport to this host in remote folder.
Also, when owner or mode is not right.

**Comment by abadger** [comment]
If I understand correctly, the question here is why Ansible is copying the file to the remote host when setting of mode, owner, or group fails.  The answer is that Ansible can't know whether those will fail until it has a file on the remote machine on which to operate.  Ansible can't know what users and groups exist on the remote machine from the controller so it copies the file to the remote machine and then attempts to set the permissions there and then moves the file into place.

If that's not the question, please let me know otherwise I'll close this ticket in a little bit.

needs_info

**Comment by liuzm7188** [comment]
yes
----- 原始邮件 -----
发件人：Toshio Kuratomi <notifications@github.com>
收件人：ansible/ansible <ansible@noreply.github.com>
抄送人：liuzm7188 <liuzm7188@sina.com>,  Author <author@noreply.github.com>
主题：Re: [ansible/ansible] File is copied even when changing mode, group or owner fails (#22116)
日期：2018年04月11日 09点16分

If I understand correctly, the question here is why Ansible is copying the file to the remote host when setting of mode, owner, or group fails.  The answer is that Ansible can't know whether those will fail until it has a file on the remote machine on which to operate.  Ansible can't know what users and groups exist on the remote machine from the controller so it copies the file to the remote machine and then attempts to set the permissions there and then moves the file into place.
If that's not the question, please let me know otherwise I'll close this ticket in a little bit.
needs_info

&mdash;

**Comment by abadger** [comment]
Okay, cool.  Closing ticket.
