### ISSUE TITLE
Add on user module to lock account.

### ISSUE THREAD

**Issue by cocoy** [ansible/ansible#2211]
From mailing list. http://bit.ly/YySA29

**Comment by mpdehaan** [comment]
I think we were saying

state=locked

and if the user didn't exist, locking it wouldn't do any damage.

state=unlocked

should unlock IF possible, but if not possible, that's ok, we wouldn't implement it.

state=present

if locked or unlocked, works as normal, no changes

**Comment by rrtj3** [comment]
I'm planning on working on this. Just a bit busy at the moment. Might be a
week or two. If someone else wants to work on it before me though, please
go ahead. Just update here so we don't both work on it at the same time.

But yes, I was thinking adding additional states of locked and unlocked to
the user module would be the cleanest. We should be able to do this cleanly
by detecting if a account is locked or not with 'passwd -S <username>'. The
second field indicates if the account is locked, contains no password or
has a password set.

Romeo

**Comment by mpdehaan** [comment]
Ok I'll take patches, closing the ticket to clean up the queue.  Thanks!
