### ISSUE TITLE
Capture template module output to variable [feature_idea]

### ISSUE THREAD

**Issue by selivan** [ansible/ansible#22134]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - Module `template`

##### SUMMARY

Sometimes it's necessary to save template module output into a variable. I solved this once by creating temporary file and parsing it, and I see other guys are struggling with same issue: http://serverfault.com/q/724853/94415

So I suggest to implement additional parametes `dest_var`, alternative to `dest`, that captures template output into variable.

**Comment by sivel** [comment]
This is actually what the template lookup is created for:

```
some_var: "{{ lookup('template', 'tmpl.j2') }}"
```

Does this not satisfy the need?

http://docs.ansible.com/ansible/playbooks_lookups.html

**Comment by selivan** [comment]
Yep, that does the trick, thank you!
