### ISSUE TITLE
Unable to get the item index while iterating over a list of objects

### ISSUE THREAD

**Issue by walterdolce** [ansible/ansible#22138]
Hi, I did extensive search online but I couldn't find anything so as a last resort I'm hoping that by opening an issue would shed some light on the matter.

I have the following variable:
```
letsencrypt_dir: "some/dir/path"
letsencrypt_domains:
   - "foo.example.com"
   - "bar.example.com"
```

And then I have the following tasks:
```
- name: Create challenge
  letsencrypt:
    account_key: '~/.ssh/id_rsa.{{ item }}'
    challenge: dns-01
    csr: '{{ letsencrypt_dir }}/{{ item }}.csr'
    dest: '{{ letsencrypt_dir }}/{{ item }}.crt'
  register: letsencrypt_challenge
  with_items: "{{ letsencrypt_domains }}"

- debug:
    msg: "{{ letsencrypt_challenge }}"
  with_items: "{{ letsencrypt_domains }}"

- debug:
    msg: "{{ letsencrypt_challenge['results'][????]['challenge_data'][item]['dns-01']['resource'] }}.example.com"
  with_items: "{{ letsencrypt_domains }}"
```

The `Create challenge` task, produces the following:
```
"changed": true,
"results": [
            {
                # data
            },
            {
                # data
            }
       ]    
# ...
```

As you can see, `results` is a list of JSON objects.

The question I'm trying to find an answer for is: how do I access items in `results` whilst iterating over `letsencrypt_domains` (which is referenced by `item` as mentioned above)?

I can't use `item.index` as 1) there's no such thing in Ansible it seems and 2) that would point to `letsencript_domains` anyway. So I'm not sure how I could get the right pointer for `????` as highlighted above.

This is being done by using the latest version of Ansible at this time of writing.

Thank you all.

**Comment by sivel** [comment]
I believe what you are looking for is either to use `with_indexed_items` or `with_together`:

http://docs.ansible.com/ansible/playbooks_loops.html#looping-over-a-list-with-an-index
http://docs.ansible.com/ansible/playbooks_loops.html#looping-over-parallel-sets-of-data

**Comment by walterdolce** [comment]
@sivel I just tried `with_together` and it seemed to work fine, given the lists can loop "side by side". 
Thank you for pointing that out. Closing now. 🍺
