### ISSUE TITLE
apt module - multiple packages

### ISSUE THREAD

**Issue by kosli** [ansible/ansible#2216]
could you please add to the documentation of the apt module that it is possible to specify multiple packages in the same command (separated by a comma) ? i just found it by looking at the source code :-) thanks a lot

**Comment by kosli** [comment]
and by looking at the log of the client where the commands are executed, it's possible to combine install and uninstall (present/absent) commands in ONE apt module? nice :-)

**Comment by mpdehaan** [comment]
The comma mechanism is not the way we want people to do it, it's just how
it works internally.

apt: name=$item state=installed
with_items:
- asdf
- jkl
- mnop

etc

**Comment by cmer** [comment]
Also with apt would support comma-delimited package names.

**Comment by bcoca** [comment]
it already does with_items: [package1,package2,package3]
