### ISSUE TITLE
ansible_s3 does not support delegate_to

### ISSUE THREAD

**Issue by mhollymoodyn** [ansible/ansible#22173]
Hi Guys,

when i try to add the

delegate_to: localhost

in my playbook to put file on AWS S3 it shows the error below:

FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: delegate_to"}

Thanks in advance for fixing this issue.

**Comment by sivel** [comment]
Based on the error, you have delegate_to indented too far.  It should be indented to he same level as `s3`.

Please feel free to use the mailing list if you have further questions.

**Comment by mhollymoodyn** [comment]
Thanks for the quick response.

Actually what I am trying to do is to make the EC2 Linux ssh key rotation.
What i do is that i am creating the SSH Keys locally([not on the remote hosts).
Then i push them and change the authorized_keys files.
Once it's done so i need to upload the keys to S3 so we (all team) can access to them later.
I don't know if I have to create a new Ansible playbook to upload the SSH keys.
I need the upload task to be done on the same playbook as the key rotation playbook.

I don't know if you had a brief idea about what i want to do. 

Thanks in advance!

**Comment by mhollymoodyn** [comment]
Hi,

Is there any update about this?

Thanks,

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project


If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

The delegation support is not a per plugin issue, this specific plugin works fine with delegation in tests. 
As per the comment above this seems like an indentation issue in your play, as such this is not a bug.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by mhollymoodyn** [comment]
Thank you ... i already opened the a new Topic.
