### ISSUE TITLE
Why systemd module output so much log?

### ISSUE THREAD

**Issue by FrankYu** [ansible/ansible#22186]
I'm trying to start ntpdate service on remote host, but why it output so much logs? yeah, I know disable it by config "no_log=Yes", but just wanna know the reason. 

#ansible kubernetes-vms -m systemd -a "name=ntpdate state=started"
10.10.10.220 | SUCCESS => {
    "changed": false,
    "name": "ntpdate",
    "state": "started",
    "status": {
        "ActiveEnterTimestamp": "Thu 2017-03-02 05:51:42 EST",
        "ActiveEnterTimestampMonotonic": "25540958505",
        "ActiveExitTimestamp": "Thu 2017-03-02 05:46:34 EST",
        "ActiveExitTimestampMonotonic": "25233739720",
        "ActiveState": "active",
        "After": "systemd-journald.socket syslog.target system.slice network.target nss-lookup.target basic.target",
        "AllowIsolate": "no",
        "AssertResult": "yes",
        "AssertTimestamp": "Thu 2017-03-02 05:51:35 EST",
        "AssertTimestampMonotonic": "25534609948",
        "Before": "chronyd.service time-sync.target shutdown.target",
        "BlockIOAccounting": "no",
        "BlockIOWeight": "18446744073709551615",
        "CPUAccounting": "no",
        "CPUQuotaPerSecUSec": "infinity",
        "CPUSchedulingPolicy": "0",
        "CPUSchedulingPriority": "0",
        "CPUSchedulingResetOnFork": "no",
        "CPUShares": "18446744073709551615",
        "CanIsolate": "no",
        "CanReload": "no",
        "CanStart": "yes",
        "CanStop": "yes",
        "CapabilityBoundingSet": "18446744073709551615",
        "ConditionResult": "yes",
        "ConditionTimestamp": "Thu 2017-03-02 05:51:35 EST",
        "ConditionTimestampMonotonic": "25534609948",
        "Conflicts": "shutdown.target",
        "ControlPID": "0",
        "DefaultDependencies": "yes",
        "Delegate": "no",
        "Description": "Set time via NTP",
        "DevicePolicy": "auto",
        "ExecMainCode": "1",
        "ExecMainExitTimestamp": "Thu 2017-03-02 05:51:42 EST",
        "ExecMainExitTimestampMonotonic": "25540958299",
        "ExecMainPID": "4569",
        "ExecMainStartTimestamp": "Thu 2017-03-02 05:51:35 EST",
        "ExecMainStartTimestampMonotonic": "25534610525",
        "ExecMainStatus": "0",
        "ExecStart": "{ path=/usr/libexec/ntpdate-wrapper ; argv[]=/usr/libexec/ntpdate-wrapper ; ignore_errors=no ; start_time=[Thu 2017-03-02 05:51:35 EST] ; stop_time=[Thu 2017-03-02 05:51:42 EST] ; pid=4569 ; code=exited ; status=0 }",
        "FailureAction": "none",
        "FileDescriptorStoreMax": "0",
        "FragmentPath": "/usr/lib/systemd/system/ntpdate.service",
        "GuessMainPID": "yes",
        "IOScheduling": "0",
        "Id": "ntpdate.service",
        "IgnoreOnIsolate": "no",
        "IgnoreOnSnapshot": "no",
        "IgnoreSIGPIPE": "yes",
        "InactiveEnterTimestamp": "Thu 2017-03-02 05:46:34 EST",
        "InactiveEnterTimestampMonotonic": "25233739720",
        "InactiveExitTimestamp": "Thu 2017-03-02 05:51:35 EST",
        "InactiveExitTimestampMonotonic": "25534610556",
        "JobTimeoutAction": "none",
        "JobTimeoutUSec": "0",
        "KillMode": "control-group",
        "KillSignal": "15",
        "LimitAS": "18446744073709551615",
        "LimitCORE": "18446744073709551615",
        "LimitCPU": "18446744073709551615",
        "LimitDATA": "18446744073709551615",
        "LimitFSIZE": "18446744073709551615",
        "LimitLOCKS": "18446744073709551615",
        "LimitMEMLOCK": "65536",
        "LimitMSGQUEUE": "819200",
        "LimitNICE": "0",
        "LimitNOFILE": "4096",
        "LimitNPROC": "64305",
        "LimitRSS": "18446744073709551615",
        "LimitRTPRIO": "0",
        "LimitRTTIME": "18446744073709551615",
        "LimitSIGPENDING": "64305",
        "LimitSTACK": "18446744073709551615",
        "LoadState": "loaded",
        "MainPID": "0",
        "MemoryAccounting": "no",
        "MemoryCurrent": "18446744073709551615",
        "MemoryLimit": "18446744073709551615",
        "MountFlags": "0",
        "Names": "ntpdate.service",
        "NeedDaemonReload": "no",
        "Nice": "0",
        "NoNewPrivileges": "no",
        "NonBlocking": "no",
        "NotifyAccess": "none",
        "OOMScoreAdjust": "0",
        "OnFailureJobMode": "replace",
        "PermissionsStartOnly": "no",
        "PrivateDevices": "no",
        "PrivateNetwork": "no",
        "PrivateTmp": "no",
        "ProtectHome": "no",
        "ProtectSystem": "no",
        "RefuseManualStart": "no",
        "RefuseManualStop": "no",
        "RemainAfterExit": "yes",
        "Requires": "basic.target",
        "Restart": "no",
        "RestartUSec": "100ms",
        "Result": "success",
        "RootDirectoryStartOnly": "no",
        "RuntimeDirectoryMode": "0755",
        "SameProcessGroup": "no",
        "SecureBits": "0",
        "SendSIGHUP": "no",
        "SendSIGKILL": "yes",
        "Slice": "system.slice",
        "StandardError": "inherit",
        "StandardInput": "null",
        "StandardOutput": "journal",
        "StartLimitAction": "none",
        "StartLimitBurst": "5",
        "StartLimitInterval": "10000000",
        "StartupBlockIOWeight": "18446744073709551615",
        "StartupCPUShares": "18446744073709551615",
        "StatusErrno": "0",
        "StopWhenUnneeded": "no",
        "SubState": "exited",
        "SyslogLevelPrefix": "yes",
        "SyslogPriority": "30",
        "SystemCallErrorNumber": "0",
        "TTYReset": "no",
        "TTYVHangup": "no",
        "TTYVTDisallocate": "no",
        "TimeoutStartUSec": "0",
        "TimeoutStopUSec": "1min 30s",
        "TimerSlackNSec": "50000",
        "Transient": "no",
        "Type": "oneshot",
        "UMask": "0022",
        "UnitFilePreset": "disabled",
        "UnitFileState": "disabled",
        "Wants": "time-sync.target system.slice",
        "WatchdogTimestampMonotonic": "0",
        "WatchdogUSec": "0"
    },
    "warnings": []
}

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a developer question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible-devel on irc.freenode.net   
   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
