### ISSUE TITLE
ansible modules in playbooks run in async mode with polling need to retry in the event of an sshd-connection failure

### ISSUE THREAD

**Issue by skvidal** [ansible/ansible#2220]
if I run ansible-playbook with a yum update as an async task.

I add polling every 15s  to check on the process.

if the yum process happens to restart sshd - there is a window where sshd is restarting where ansible's polling could hit the server and not be able to get a connection.

right now - it just fails - it should retry these connections for a certain number of retries or for as long as the async timeout setting is before reporting a failure.

a transient connection failure does not actually mean the task has failed.

**Comment by mpdehaan** [comment]
agree.

we also still need to do something clever about async files getting cleaned
up.

**Comment by mpdehaan** [comment]
technically as a workaround ignore_errors: True + wait_for if you know you are going to do it may be reasonable but I like the retries as an option.

Ideally retries should be available on anything, not just async.

**Comment by mpdehaan** [comment]
care will need to be taken as retry in /usr/bin/ansible and playbook differs some, IIRC

**Comment by mpdehaan** [comment]
We're already going to do a do, until, retries mechanism so I am wondering if this could be generically solved by that.

**Comment by mpdehaan** [comment]
Filing a ticket on the until thing.
