### ISSUE TITLE
apt-get autoremove doesn't remove obsolete packages

### ISSUE THREAD

**Issue by snowsky** [ansible/ansible#22222]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

apt
##### ANSIBLE VERSION

```
2.2.1
```

##### OS / ENVIRONMENT

Ubuntu
##### STEPS TO REPRODUCE

Use this playbook and then run "apt-get autoremove":
```yaml
- hosts: localhost
  tasks:
    - apt:
        autoremove: yes
```
It shows no change:
```
PLAY RECAP ************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```
Then the command 'apt-get autoremove' still show some packages:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  linux-headers-4.4.0-59 linux-headers-4.4.0-59-generic linux-headers-4.4.0-62 linux-headers-4.4.0-62-generic linux-image-4.4.0-34-generic linux-image-4.4.0-59-generic linux-image-4.4.0-62-generic
0 upgraded, 0 newly installed, 7 to remove and 24 not upgraded.
After this operation, 341 MB disk space will be freed.
Do you want to continue? [Y/n]
```

##### EXPECTED RESULTS

The obsolete packages should be removed.
##### ACTUAL RESULTS

The obsolete packages was not removed.

```

```

**Comment by snowsky** [comment]
#22154

**Comment by snowsky** [comment]
fixed by #22232

**Comment by varazir** [comment]
It's working for me but it always say changed even if there are no pkg removed

**Comment by jjaone** [comment]
I can confirm that apt: with autoremove: yes does not actually remove or clean those packages that it should. I'm on Ansible 2.2.0 (ansible-2.2.2.0-1ppa-xenial in Ubuntu 16.04 control host) and my playbook is targeting Ubuntu 16.04 host where the Ansible/apt-module is used to update and autoremove packages.

**Comment by jjaone** [comment]
Tried also with the Ansible 2.4.0 (git://github.com/ansible/ansible.git) devel-branch after doing: "git checkout devel", and "make", and "sudo make install" and using that to playbook, which has:
```
- name: srvenv - Autoclean and update apt cache
  become: yes
  apt:
    autoremove: yes
    purge: yes
    force: yes
    update_cache: yes
```

still the apt-module does not delete, remove or autoclean the obsolete packages, but they remain in the system:
 ```
$ sudo apt-get -f install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-45 linux-headers-4.4.0-59 linux-headers-4.4.0-62 linux-headers-4.4.0-63 linux-headers-4.4.0-64 linux-headers-4.4.0-65
  linux-headers-4.4.0-66 linux-headers-4.4.0-66-generic linux-image-4.4.0-66-generic linux-image-extra-4.4.0-66-generic
Use 'sudo apt autoremove' to remove them.
```

**Comment by dev00** [comment]
I can confirm this behaviour, running Ansible 2.3.0.0 from the repo on Ubuntu 16.04.

Wether `autoclean` nor `autoremove` seem to have any effect on the OS.

**Comment by fdutheil** [comment]
Same here, Ansible v2.3.0.0 from Ubuntu 14.04 onto Ubuntu 14.04: apt module doesn't find old kernels when ```/usr/bin/apt-get autoremove``` does.

BTW autoclean should not be an alias for autoremove, considering the apt-get autoremove and autoclean options are totally different from each other.

**Comment by LeTink** [comment]
And another one with the same problem ...

**Comment by alexfeig** [comment]
Yep this happens to me with 2.3.2.0 on 16.04 as well.

**Comment by B2RN** [comment]
Maybe add a label for 2.3 as well:

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

Can confirm it works fine on 2.4, though.

**Comment by LeTink** [comment]
Can we have this reopened?
```
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/andrej/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

And autoremove isn't working for us.
```
- name: Prune packages no longer needed
  apt:
    update_cache: yes
    cache_valid_time: 3600
    autoremove: yes
```
I just did a manual prod on several of our servers which were upgraded this week, and got to "apt autoremove" kernels worth up a GB of disk-space.
