### ISSUE TITLE
Extending patterns

### ISSUE THREAD

**Issue by sjmudd** [ansible/ansible#2225]
I've just started looking at ansible. Looks nice.

I notice 2 things which for the hostnames at my site cause more patterns to be needed than ideal.
(1) the fact only a single range can be used. I have hostnames like:

bc123wwrdb-01, bc124wwrdb-01, bc125wwrdb-01, but also
bc123wwrdb-02, bc124wwrdb-02, bc125wwrdb-02.
bc123wwrdb-03, bc124wwrdb-03, bc125wwrdb-03

It seems I can't write what would be useful:

bc[123:125]wwrdb-[01:03]

(2) Add a step in the creation of names:

Some other hostnames I use are of the form:

bc123xxrdb-01, bc125xxrdb-01, bc127xxrdb-01

that is with a step interval.

A pattern of the form below would be quite useful for that situation:

bc[123:127:2]xxrdb-01 

(the third "parameter" being a step interval other than 1)

Just a thought and this looks quite interesting.

**Comment by mpdehaan** [comment]
Hmm, yes, thats interesting, though it would be sketchy to know _how_ to
expand that in a way that would work for everyone perhaps.

If you want, this _MAY_ be a reason you may want to write an external
inventory source, but I suspect you still wouldn't wind up with two many
current patterns.

I'm not sure the step is terribly useful, as if you want to do rolling
updates you typically use the serial keyword or "--limit" with a selection
that picks N at a time, but probably don't need to interleave every other
host, etc.

Though you can do some clever skipping with when_\* or only_if if so needed.

Sorry, that's a flurry of information.

Curious about the use case :)

**Comment by sjmudd** [comment]
The use-case is that the same prefix is used to represent a cell of servers and often they are worked on together.
Part of this is historic so changing naming conventions now is hard. However, the suggestion reduces the number of entries in the ansible hosts file as the hosts can be enumerated more concisely.  So this is really to reduce clutter when the number of hosts grows.
