### ISSUE TITLE
frontpage display 

### ISSUE THREAD

**Issue by akvadrako** [ansible/ansible#2227]
Hi. It looks like an alignment issue with the front page (ansible.cc). This is in the latest Safari on OS X. I think the image should be on the right, not below the navigation.
![Screen Shot 2013-02-28 at 10 40 16](https://f.cloud.github.com/assets/184545/204802/90246a22-818b-11e2-94b5-4ca565417182.png)

**Comment by mpdehaan** [comment]
I'll update and take a look.  Present version was ok for me.

**Comment by mpdehaan** [comment]
Ok, latest Safari looks like fine to me.

Can you let me know more about what you are using?

**Comment by akvadrako** [comment]
Ah, damn - it was one of my extensions adding custom style rules. Sorry for that.
