### ISSUE TITLE
dict parsing issue - regression

### ISSUE THREAD

**Issue by n2aws** [ansible/ansible#22280]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Dictionary parser
##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
regression of a previously fixed issue #17001
##### STEPS TO REPRODUCE
Same steps as in #17001

```yaml

```

##### EXPECTED RESULTS
I expected an unrelated dictionary to not be needed or cause errors in playbooks that don't use them.

##### ACTUAL RESULTS

```
See ticket #17001,   as near as I can tell it's the identical issue I reported, and it was later resolved/closed.  It appear to have regressed.

```

**Comment by n2aws** [comment]
@jimi-c @agaffney @alikins  I figured I'd specifically mention you in this ticket as it appears to be a regression of the bug we identified (and you guys later resolved.) so you may be somewhat familiar with what the issue is/was and how to resolve it this go-round.

**Comment by jimi-c** [comment]
Odd, it seems to happen in the stable-2.2 branch but not devel.

**Comment by jimi-c** [comment]
@palmerit actually I had simply forgotten to checkout submodules when switching branches. I'm not able to reproduce this at all on stable-2.2, even using the `v2.2.1.0-1` tag.

**Comment by sivel** [comment]
This issue does not appear to be present in recent versions of Ansible.  If you are still having problems with Ansible 2.5+, please feel free to open a new issue.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
