### ISSUE TITLE
Licensing Tower fails - Call to /api/v1/config/ failed. 405

### ISSUE THREAD

**Issue by JamieSinn** [ansible/ansible#22290]
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME
Ansible Tower

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
No config change, default.

##### OS / ENVIRONMENT
RHEL 7 x64

##### SUMMARY
Cannot license ansible tower - gets a 405 returned. 
http://i.imgur.com/8GoEji1.png

##### STEPS TO REPRODUCE
Install Ansible Tower via the recommended setup guide 
Attempt to license. - Fail

##### EXPECTED RESULTS
Accept license and begin the trial.

##### ACTUAL RESULTS
Failed to license - http://i.imgur.com/8GoEji1.png

**Comment by sivel** [comment]
For tower issues please utilize https://access.redhat.com/products/ansible-tower-red-hat/

This repository is for the open source ansible project only.

**Comment by shajay12** [comment]
Hi Sivel, I am getting this error on AWX Tower UI. Please tell me the solution. 
ERROR
Failed to read /api. GET status: 500 A server error has occurred.
