### ISSUE TITLE
Need help to connect to Windows Node/Machine using SSL connection via ANSIBLE

### ISSUE THREAD

**Issue by pareshdp** [ansible/ansible#22304]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME
Ansible SSL Connection via WinRM to Windows node/host/local PC

##### ANSIBLE VERSION

```
2.1.1.0
```

##### SUMMARY

I have ansible installed on Ubuntu 64 bit OS with version as 2.1.1.0
I want to connect to my local PC (WIndows 10) using Ansible. Please note my ansible is on my VirtualBoxApp.
Now, I have run the powershell script to enable the remoting feature on my Windows PC.
This script has added one self signed certificate under my local windows machine account.
I have setup below configuration in my windows.yml

[windows]
192.168.1.102
[windows:vars]
ansible_user=<my user name>
ansible_password=<passwd for local windows machine>
ansible_port=5986
ansible_connection=winrm
ansible_winrm_transport=ssl
ansible_winrm_server_cert_validation=validate

When I try to connect to my windows machine using below command then it fails.

ansible windows ansible -i windows.yml -m win_ping

The error is - 
SSL : CERTIFICATE VERIFY FAILED (_ssl.c:590)

If I use ignore mode then it works fine.
Please let me know do i need to set any certificate related variables on Ansible side ?
How does ansible will know or verify the server side certificate?

I want to have one way SSL communication with my WIndows machine wherein we authenticate the windows server/machine.

Also , please note my Winrm configuration on windows machine - 

PS C:\WINDOWS\system32> winrm get winrm/config
Config
    MaxEnvelopeSizekb = 500
    MaxTimeoutms = 60000
    MaxBatchItems = 32000
    MaxProviderRequests = 4294967295
    Client
        NetworkDelayms = 5000
        URLPrefix = wsman
        AllowUnencrypted = false
        Auth
            Basic = true
            Digest = true
            Kerberos = true
            Negotiate = true
            Certificate = true
            CredSSP = false
        DefaultPorts
            HTTP = 5985
            HTTPS = 5986
        TrustedHosts
    Service
        RootSDDL = O:NSG:BAD:P(A;;GA;;;BA)(A;;GR;;;IU)S:P(AU;FA;GA;;;WD)(AU;SA;GXGW;;;W
        MaxConcurrentOperations = 4294967295
        MaxConcurrentOperationsPerUser = 1500
        EnumerationTimeoutms = 240000
        MaxConnections = 300
        MaxPacketRetrievalTimeSeconds = 120
        AllowUnencrypted = false
        Auth
            Basic = true
            Kerberos = true
            Negotiate = true
            Certificate = true
            CredSSP = false
            CbtHardeningLevel = Relaxed
        DefaultPorts
            HTTP = 5985
            HTTPS = 5986
        IPv4Filter = *
        IPv6Filter = *
        EnableCompatibilityHttpListener = false
        EnableCompatibilityHttpsListener = false
        CertificateThumbprint = 1C567A1AF0A17F9D4F2720B6F979A12C05C0E6E4
        AllowRemoteAccess = true
    Winrs
        AllowRemoteShellAccess = true
        IdleTimeout = 7200000
        MaxConcurrentUsers = 2147483647
        MaxShellRunTime = 2147483647
        MaxProcessesPerShell = 2147483647
        MaxMemoryPerShellMB = 2147483647
        MaxShellsPerUser = 2147483647

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by pareshdp** [comment]
My OS where the Ansible is intalled is Ubuntu 64 bit , while my windows machine is on Windows 10

**Comment by jhawkesworth** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
