### ISSUE TITLE
Ansible 2.2.1  conditional include now evaluates each task instead of ignoring them and fails on lookup.

### ISSUE THREAD

**Issue by ovorobio** [ansible/ansible#22316]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

PlaybookInclude + when

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides

```

##### CONFIGURATION

Using default configurations from pip install ansible.

##### OS / ENVIRONMENT

Ansible host: Fedora release 25 (Twenty Five)
Ansible nodes: Red Hat Enterprise Linux Server release 7.3 (Maipo)
##### SUMMARY

Conditional includes evaluates each task in include
##### STEPS TO REPRODUCE

```
- include: "cleanup.yml"
  when: provision.cleanup|default(False)

- include: "provision.yml"
  when: not provision.cleanup|default(False)
```

##### EXPECTED RESULTS

Ansible skips all tasks in included playbook and not evaluates them.
##### ACTUAL RESULTS

TASK [copy server private key from hypervisor for SSH proxy] *******************
                      [[ previous task time: 0:00:00.108236 = 0.11s / 24.22s ]]
skipping: [hypervisor] => (item={u'dest': u'/home/user/id_rsa', u'src': u'~/.ssh/id_rsa'}) 
skipping: [hypervisor] => (item={u'dest': u'/home/user/id_rsa.pub', u'src': u'~/.ssh/id_rsa.pub'}) 

TASK [update file permissions] *************************************************
                      [[ previous task time: 0:00:00.177659 = 0.18s / 24.40s ]]
skipping: [hypervisor] => (item=/home/user/id_rsa) 
skipping: [hypervisor] => (item=/home/user/id_rsa.pub) 

TASK [Set up authorized_keys for the deploy user] ******************************
                      [[ previous task time: 0:00:00.199675 = 0.20s / 24.60s ]]
 [WARNING]: Unable to find
'/home/user/id_rsa.pub' in
expected paths.

fatal: [hypervisor]: FAILED! => {"failed": true, "msg": "could not locate file in lookup: /home/user/id_rsa.pub"}

msg: could not locate file in lookup: /home/user/id_rsa.pub

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/home/user/virsh/main.retry

PLAY RECAP *********************************************************************
hypervisor                 : ok=6    changed=0    unreachable=0    failed=1   
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

ERROR   Playbook "/home/user/virsh/main.yml" failed!

```

```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

As per docs http://docs.ansible.com/ansible/include_module.html, a 'static' include will have all included tasks inherit the setting, a dynamic include will apply that to itself, add `static: no` to the includes to force them to by dynamic.

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
