### ISSUE TITLE
s3 module doesn't work with rgw=true and a dot in a bucket name

### ISSUE THREAD

**Issue by jrandall** [ansible/ansible#22317]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
s3 module

##### ANSIBLE VERSION
```
ansible 2.3.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
If `rgw: true` is set in the s3 module and you also use a bucket name containing a `.`, an exception is thrown resulting in the following error message:
```
"msg": "Failed to connect to S3: connect_s3() got multiple values for keyword argument 'calling_format'"
```

**Comment by jrandall** [comment]
The problem is here: https://github.com/ansible/ansible/blob/c6849a34647eb8c2c92cc0659de769eeee8fce4c/lib/ansible/modules/cloud/amazon/s3.py#L720-L721

When a bucket name contains a `.`, aws_connect_kwargs already contains an entry for `calling_format` which was set here: https://github.com/ansible/ansible/blob/c6849a34647eb8c2c92cc0659de769eeee8fce4c/lib/ansible/modules/cloud/amazon/s3.py#L530

Should be an easy fix - I'll submit a PR shortly.

**Comment by s-hertel** [comment]
I was able to reproduce this bug. If rgw is used with a bucket name with a dot in it boto.connect_s3() is called with duplicate calling_format parameters.
