### ISSUE TITLE
Add file name extension to temporary files for ansible-vault edit and create

### ISSUE THREAD

**Issue by sedrubal** [ansible/ansible#22335]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
vault

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
`-`

##### OS / ENVIRONMENT
Linux

##### SUMMARY
`ansible-vault edit` and `create` create a temporary file, decrypt the content into it and open an editor for editing it. The temporary file often has a completely random name like `/tmp/tmpWOteRO` without any file extension like `.yml`. Editors like vim don't recognize the syntax itself and so there are no syntax specific settings. It was better to create temporary files with the file name extension similar to the encrypted file (like `/tmp/tmpWOteRO.yml` for yaml files).

##### STEPS TO REPRODUCE
- `ansible-vault create test.yml`
- `ansible-vault edit test.yml`

##### EXPECTED RESULTS
- the temporary file should be like `/tmp/tmpDqiQGq.yml`

##### ACTUAL RESULTS
- the file name was `/tmp/tmpDqiQGq`

**Comment by nrwahl2** [comment]
Great idea, @sedrubal! I've created PR #28698 to implement this.

**Comment by nrwahl2** [comment]
@alikins Don't mean to step on your toes.

**Comment by alikins** [comment]
@nrwahl2 No toes were stepped upon. Not sure if I ever created a pr for my fix.

(rebased my variant against devel if you want to take a look: https://github.com/ansible/ansible/compare/devel...alikins:vault_tmp_file_ext_22335)
