### ISSUE TITLE
Interpolation does not run on object fields reading from vars dict

### ISSUE THREAD

**Issue by rektide** [ansible/ansible#22347]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
ansible 2.3.0 (include-vars-override 4688a235c9) last updated 2017/03/06 21:55:27 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### OS / ENVIRONMENT

Debian/testing

##### SUMMARY

Previously when reading from the `vars` dict ([mentioned here](http://docs.ansible.com/ansible/faq.html#when-should-i-use-also-how-to-interpolate-variables-or-dynamic-variable-names), as needed for dynamic variable names), objects that had interpolated values in them would interpolate. As of 2.1.4.0 and 2.2.1.0, when accessing objects via the vars dict, objects no longer expand. 

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  vars:
    target: "complex"
    complex:
    - content: "{{ 2 + 2 }}"
    - content: "{{ 'hello' }}"
  tasks:
  - debug: var=item.content
    with_items: "{{ vars[target] }}"
```

##### EXPECTED RESULTS

I expect that vars continue to- like hostvars- be a way to do dynamic variable access, including for complex objects.

2.2.0.0 works as expected, yielding:

```
ok: [127.0.0.1] => (item={u'content': u'{{ 2 + 2 }}'}) => {
    "invocation": {
        "module_args": {
            "var": "item.content"
        }, 
        "module_name": "debug"
    }, 
    "item": {
        "content": "{{ 2 + 2 }}"
    }, 
    "item.content": "4"
}
ok: [127.0.0.1] => (item={u'content': u"{{ 'hello' }}"}) => {
    "invocation": {
        "module_args": {
            "var": "item.content"
        }, 
        "module_name": "debug"
    }, 
    "item": {
        "content": "{{ 'hello' }}"
    }, 
    "item.content": "hello"
}
```

##### ACTUAL RESULTS

2.2.1.0 turns some of the fields in the object looked up in vars directly into strings, rather than showing their interpolated values:

```
ok: [127.0.0.1] => (item={u'content': u'{{ 2 + 2 }}'}) => {
    "invocation": {
        "module_args": {
            "var": "item.content"
        }, 
        "module_name": "debug"
    }, 
    "item": {
        "content": "{{ 2 + 2 }}"
    }, 
    "item.content": "{{ 2 + 2 }}"
}
ok: [127.0.0.1] => (item={u'content': u"{{ 'hello' }}"}) => {
    "invocation": {
        "module_args": {
            "var": "item.content"
        }, 
        "module_name": "debug"
    }, 
    "item": {
        "content": "{{ 'hello' }}"
    }, 
    "item.content": "{{ 'hello' }}"
}
```

Notably, item.content has gone from `hello` to `{{ 'hello' }}`.

This eliminates a variety of options for dynamically looking up variables in Ansible, particularly anything complex defined in `vars:` (and I believe vars_files?).

**Comment by rektide** [comment]
I had no way to tell whether the hacking I was trying was going anywhere or not, & have closed the PR I opened with those hacks. Hoping some ansible devs chime in with some kind of advice for how we can get indirect access to vars alike how we can get access to hostvars[host].

**Comment by rektide** [comment]
This appears to be a dupe of #20545.

**Comment by bcoca** [comment]
closing as dupe
