### ISSUE TITLE
Feature Idea: globally configurable any_errors_fatal in ansible.cfg

### ISSUE THREAD

**Issue by jamesongithub** [ansible/ansible#22340]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ansible.cfg

##### ANSIBLE VERSION

```
n/a
```

##### CONFIGURATION

`any_errors_fatal: true`

##### SUMMARY

It would nice to be able to configure any_errors_fatal: true/false on a global level instead of putting it on every single play. I don't know the most common use cases, but given playbooks are generally idempotent, it seems ok to keep running until all hosts pass. 

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

ansible.cfg set any_errors_fatal globally

##### ACTUAL RESULTS

```

```

**Comment by starkers** [comment]
I just wanted to say that this is a brilliant idea and I would have much more faith in my CD pipelines with this implemented.

**Comment by briceburg** [comment]
I'd prefer to be able to set the default value of `any_errors_fatal` in ansible.cfg as well. It can be false for compatibility and to match existing behavior. 

We use ansible inside tooling containers and have a unified ansible.cfg where this makes a lot of sense and keeps us from having to bloat each playbook.
