### ISSUE TITLE
include_role loads defaults statically preventing templating of defaults

### ISSUE THREAD

**Issue by fivethreeo** [ansible/ansible#22345]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by sivel** [comment]
Please ensure to fill out the full template of this issue.

**Comment by fivethreeo** [comment]
Pebkac
