### ISSUE TITLE
include_role does not run or display any output

### ISSUE THREAD

**Issue by bearrito** [ansible/ansible#22356]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

load_role

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/barrett/Git/ansible-dock-robot/ansible.cfg
  configured module search path = Default w/o overrides
(ansible)➜  ansible-dock-robot git:(feature/tesco_again_cle

```

##### CONFIGURATION
IRRELEVANT

##### OS / ENVIRONMENT
UBUNTU 14.04

##### SUMMARY
load_role seems completely ignored

##### STEPS TO REPRODUCE

```
- name: LetsEncrypt
  include_role: name=thefinn93.letsencrypt
  tags: [ always ]
```

##### EXPECTED RESULTS
Some output

##### ACTUAL RESULTS
no output

```
TASK [setup] *******************************************************************
ok: [scrubbed]

PLAY RECAP *********************************************************************
scrubbed : ok=1    changed=0    unreachable=0    failed=0   

```

**Comment by paulczar** [comment]
We are seeing the same.   in ansible `2.2.1.0` it shows as skipping the included role's tasks,  in ansible `2.2.0.0` it works as expected.

**Comment by bearrito** [comment]
Does the maintainer need any more information from me on this?

**Comment by nerdvegas** [comment]
I just got this same problem. No output, no errors, included role just doesn't run. No extra info from -vvv.

In case it's related, this role is being included from a role that itself is getting pulled in as a dependency in another role's meta/main.yaml.

Ansible version 2.4.1.0.

**Comment by sivel** [comment]
@bearrito we will need a more complete reproducer to validate this issue.  As it is, I've tested with a play, that only uses `include_role` in the way you have, but it works as expected.

needs_info

**Comment by sivel** [comment]
Closing due to no response. If you are still experiencing this issue, please test against a newer version of ansible, and open a new issue with a full reproducer.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
