### ISSUE TITLE
Expose the "user" playbook parameter in a variable

### ISSUE THREAD

**Issue by jmandel** [ansible/ansible#2243]
It would be convenient to have access to the ansible `user` parameter specified in a playbook.

My use case: would like to copy a directory of files to a host via rsync, and need to fill in the `user@host`: destination.  

host is just `${inventory_hostname}`... but there's no variable to query for user.

Related discussion here:
https://groups.google.com/forum/?fromgroups=#!topic/ansible-project/BHCnJb768e4

**Comment by mpdehaan** [comment]
this has been suggested, I am open to patches that add it.
