### ISSUE TITLE
Cowsay should be opt-in

### ISSUE THREAD

**Issue by kensley** [ansible/ansible#22448]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Its very unprofessional to see cowsay popup on various machines when pushing/running playbooks. Cowsay should be an opt-in feature not an opt-out feature. 

I have seen/found the workarounds to disable this, but its ridiculous to put this back on the users to disable.

**Comment by bcoca** [comment]
dupe of #10530
