### ISSUE TITLE
log_path with relative path: [WARNING]: log file at ansible.log is not writeable and we cannot create it, aborting

### ISSUE THREAD

**Issue by jdufresne** [ansible/ansible#22500]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
logging

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.1.0
```

##### CONFIGURATION
```
log_path = ansible.log
```

##### OS / ENVIRONMENT
Running ansible as an unprivileged user. User _does_ have permission to create files in the current directory.

##### SUMMARY
I expect the `log_path` without a leading `/` to be a relative path. Meaning, log to the path `$PWD/ansible.log`. This does not appear to work as I get the following warning:

```
[WARNING]: log file at ansible.log is not writeable and we cannot create it, aborting
```

Changing the configuration to `log_path = ./ansible.log` does work.

##### STEPS TO REPRODUCE
1. Change configuration to: `log_path = ansible.log`
2. Make sure user has permission to create files in the current directory
3. Make sure file doesn't already exist
3. Run ansible-playbook to receive warning

##### EXPECTED RESULTS
Log file created relative to `$PWD`.

##### ACTUAL RESULTS
Receive the following warning:

```
[WARNING]: log file at ansible.log is not writeable and we cannot create it, aborting
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Paths in ansible.cfg are relative to the config file not the current working directory.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by jdufresne** [comment]
> Paths in ansible.cfg are relative to the config file not the current working directory.

The `ansible.cfg` is in the current working directory. It is located at `$PWD/ansible.cfg`. They are the same. With that understanding, I think this is still a bug.

**Comment by bcoca** [comment]
point taken, its not picking up the path as relative when only the file name is there.

**Comment by sivel** [comment]
As of Ansible 2.4 all relative paths in ansible.cfg are now relative to the ansible.cfg file itself.

If you are still having problems with recent versions of ansible, please feel free to open a new issue.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
