### ISSUE TITLE
make debian failed on Debian Squeeze

### ISSUE THREAD

**Issue by profy12** [ansible/ansible#2250]
Hi,

On a Debian Squeeze, I have this error message when running make debian :

find . -regex "._.py[co]$" -delete
Cleaning up editor backup files
find . -type f ( -name "_~" -or -name "#_" ) -delete
find . -type f ( -name "_.swp" ) -delete
../hacking/module_formatter.py -t rst --template-dir=../hacking/templates --module-dir=../library -o rst/modules/ --includes-file=rst/modules/_list.rst
Traceback (most recent call last):
  File "../hacking/module_formatter.py", line 32, in <module>
    import ansible.utils
ImportError: No module named ansible.utils
make[1]: **\* [modules] Erreur 1
make[1]: quittant le répertoire « /usr/local/src/ansible/docsite »
make: **\* [webdocs] Erreur 2

**Comment by mpdehaan** [comment]
You likely need to source ./hacking/env-setup before you build.   We can make the makefile do this, actually.

**Comment by profy12** [comment]
source hacking/env-setup works, thanks for help :)

**Comment by profy12** [comment]
It's in the doc, I close the issue
