### ISSUE TITLE
Git: depth=1 version=branch misconfigures tracking branch in .git/config

### ISSUE THREAD

**Issue by dmrzzz** [ansible/ansible#22517]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
git

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Amazon Linux AMI release 2016.09

##### SUMMARY

If you use git with depth=1 to check out a non-default branch, the fetch line in `.git/config` is still configured for the default branch rather than the specified branch.  As a result, **future invocations of ansible git will not notice when the remote branch has changed**, which is very unfortunate e.g. if you're trying to periodically re-run ansible-pull from cron.

AFAICT this appears to already be fixed by #21712, but the impact is different enough from #21316 that I thought it worth documenting anyway.  Hopefully it saves someone else the pain of troubleshooting the same problem.

##### STEPS TO REPRODUCE
Minimal steps to observe the wrong behavior:
```
ansible localhost -m git -a 'repo=https://github.com/ansible/ansible version=stable-1.9 update=yes depth=1 dest=foo'
cat foo/.git/config
```

##### EXPECTED RESULTS

```
...
[remote "origin"]
	url = https://github.com/ansible/ansible
	fetch = +refs/heads/stable-1.9:refs/remotes/origin/stable-1.9
...
```

##### ACTUAL RESULTS

The fetch line lists `devel` rather than `stable-1.9`:

```
[ec2-user@ip-10-224-255-6 ~]$ ansible localhost -m git -a 'repo=https://github.com/ansible/ansible version=stable-1.9 update=yes depth=1 dest=foo'
 [WARNING]: provided hosts list is empty, only localhost is available

localhost | SUCCESS => {
    "after": "b377301195e7d7720551538a33d2499eee1a1d30", 
    "before": null, 
    "changed": true, 
    "submodules_changed": true, 
    "warnings": []
}
[ec2-user@ip-10-224-255-6 ~]$ cat foo/.git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/ansible/ansible
	fetch = +refs/heads/devel:refs/remotes/origin/devel
[branch "devel"]
	remote = origin
	merge = refs/heads/devel
[submodule "lib/ansible/modules/core"]
	url = https://github.com/ansible/ansible-modules-core.git
[submodule "lib/ansible/modules/extras"]
	url = https://github.com/ansible/ansible-modules-extras.git
```

To observe the negative impact of this requires a repo that you can commit to:
1. Initial checkout with ansible:
    ```
    [ec2-user@ip-10-224-255-6 ~]$ ansible localhost -m git -a 'repo=https://REDACTED/testrepo.git version=dev update=yes depth=1 dest=bar'
     [WARNING]: provided hosts list is empty, only localhost is available

    localhost | SUCCESS => {
        "after": "05fabc0404e3d5bb8ba68481791c562c805966f6", 
        "before": null, 
        "changed": true, 
        "warnings": []
    }
    ```
2. From a separate workstation, push a new commit (e62d70c) to the dev branch.
3. Attempt to update the existing checkout with ansible:
    ```
    [ec2-user@ip-10-224-255-6 ~]$ ansible localhost -m git -a 'repo=https://REDACTED/testrepo.git version=dev update=yes depth=1 dest=bar'
     [WARNING]: provided hosts list is empty, only localhost is available

    localhost | SUCCESS => {
        "after": "05fabc0404e3d5bb8ba68481791c562c805966f6", 
        "before": "05fabc0404e3d5bb8ba68481791c562c805966f6", 
        "changed": false, 
        "warnings": []
    }
    ```
   ansible git does not find the new commit.

Workaround:
```
cd bar && git remote set-branches origin dev
```

**Comment by robinro** [comment]
@dmrzzz Thanks for this detailed description.

Can you confirm that #21712 fixed this, i.e. by running your example with the ansible devel branch?
If so I'd recommend to close this issue (still searchable for people with similar issues in unpatched versions).

One could test the `.git/config` content in the integration tests, somewhere around https://github.com/ansible/ansible/blob/3afc993f3a5774f61b6a9b6ed4ea1136821f91ef/test/integration/targets/git/tasks/depth.yml#L80. I'd be happy to review a PR if you want to go ahead and implement this test.

**Comment by dmrzzz** [comment]
Yes, both devel and stable-2.2 (with #21712 cherry-picked) behave correctly for me.  Closing this issue as suggested.
