### ISSUE TITLE
Ansible callback_plugins configuration is relative to cwd instead of config file

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#22533]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
2.2.1
```

##### CONFIGURATION

```
callback_plugins = plugins
```

##### SUMMARY
It seems that the `callback_plugins` path from `ansible.cfg` is relative the the current working directory at runtime. 

This means that is impossible to keep playbooks in different folders or to call playbooks from other directories because the plugin loading will fail.

The purpose of the the `ansible.cfg` is to configure ansible and to tell it from where to look for different files. 

I think that the relative paths are supposed to be to the location of the current file, not relative to CWD which can be different at runtime.

If anyone argues against introduce a change that may impact how the path is resolved, I could propose as an alternative to add a variable that resolves to location of the ini file. 

For example tox has `{toxinidir}` so we could have a `%(inidir)s` that people can use in order to assure that the lookup works well. Clearly this should be include in the example configuration files
so people will know how to use it.

## How to reproduce

Enable one callback plugin inside `ansible.cfg` (can be any plugin)
```
[defaults]
callback_plugins = plugins/callbacks
stdout_callback = human_log
```

Now run any playbook, and try again but try to call the playbook from another directory. 

Ansible will fail because it fails to load the plugin, even if you specify the path to the config file.

**Comment by bcoca** [comment]
fixed in commit above
