### ISSUE TITLE
sudo should cd to user's home directory before executing

### ISSUE THREAD

**Issue by cyounkins** [ansible/ansible#2254]
I think the sudo annotations should cause ansible to cd to that user's home directory before executing commands. Otherwise, the commands are executing with the current directory as /root , which you can be in if you were root and sudo'd, but cannot cd out of and then back into. That is:

```
root@ubuntu:~# cd ~
root@ubuntu:~# su user
user@ubuntu:/root$ cd ..
user@ubuntu:/$ cd root
bash: cd: root: Permission denied
```

We ran into this issue when our command we wanted to execute as sudo created a virtualenv. virtualenv tried to do an os.chdir after it's done, which was causing it to fail.

**Comment by mpdehaan** [comment]
if you are using the shell/command module, this is what 'chdir=' is for on that module.

What module were you running?

**Comment by schmir** [comment]
I've ran into this when using the git module...well, with the git module you can make 'dest' an absolute path...but I'd prefer a relative path.

**Comment by valkum** [comment]
Simply use

``` bash
root@ubuntu:~# cd ~
root@ubuntu:~# su user -
```

Then you got the right env vars.

**Comment by sheldonh** [comment]
I get this from the git module, even with an absolute path.
