### ISSUE TITLE
Unable to connect to my windows host - Ansible

### ISSUE THREAD

**Issue by alstarian** [ansible/ansible#22553]
Hi All,

I just started working with Ansible this morning for the first time and I am trying to connect to my window host (Windows 2012 R2) to perform a simple win_ping to test if I can make a connection.
I have installed Ansible on a CentOS linux and created 2 files namely web.yml and inventory.yml.

inventory.yml
[web]
ip of my windows host

web.yml

ansible_user: root
ansible_password: Ansible2!
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_cert_validation: ignore

When i run **ansible web -i inventory.yml -m win_ping -vvvv** i get the following error

Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/windows/win_ping.ps1
<10.109.140.64> ESTABLISH SSH CONNECTION FOR USER: None
<10.109.140.64> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.109.140.64 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1489384848.14-1713149079215 `" && echo ansible-tmp-1489384848.14-1713149079215="` echo ~/.ansible/tmp/ansible-tmp-1489384848.14-1713149079215 `" ) && sleep 0'"'"''
10.109.140.64 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/root/.ansible/cp/ansible-ssh-10.109.140.64-22-root\" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\ndebug1: Connecting to 10.109.140.64 [10.109.140.64] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 10.109.140.64 port 22: Connection timed out\r\nssh: connect to host 10.109.140.64 port 22: Connection timed out\r\n",
    "unreachable": true
}

Thanks
A

**Comment by alstarian** [comment]
I now get a new message after playing around. which is 

[root@neo ansible_test]# ansible windows -i host -m win_ping
 [WARNING]: ansible_winrm_cert_validation unsupported by pywinrm (is an up-to-date version of pywinrm installed?)

ip of windows host  | UNREACHABLE! => {
    "changed": false,
    "msg": "ssl: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)",
    "unreachable": true
}


The version of my pywinrm is 0.2.2

**Comment by alstarian** [comment]
Now I am at this stage 
ERROR! Unexpected Exception: dictionary update sequence element #0 has length 1; 2 is required

**Comment by alstarian** [comment]
The above error is nothing, I still face the message saying "**Failed to connect to the host via ssh: ssh: connect to host 10.109.140.64 port 22: Connection timed out\r\n**". . I dont know why ansible is trying to talk to my windows host using ssh when i have specified **ansible_connection=winrm** in my confg file

**Comment by KroArtem** [comment]
Hello, you should probably read http://docs.ansible.com/ansible/intro_windows.html#windows-system-prep

**Comment by jhawkesworth** [comment]
Likely you haven't put your web.yml in group_vars

If you inventory is in 

/etc/ansible/hosts

then your web.yml group variables need to be in

/etc/ansible/group_vars/web.yml

**Comment by alikins** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

 This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.
