### ISSUE TITLE
FR: direct access to groupvars

### ISSUE THREAD

**Issue by morphje** [ansible/ansible#22559]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
lib/ansible/vars/__init__.py ?

##### SUMMARY
Currently I have access to hostvars[hostname] variables if I want access to variables that are specified to that specific host. However there are some workflows where you need access to the group variables where you know the group name.

Consider the following use case where you have one host that belongs to 2 groups with the same variable. 
I have two consuming clients that access their own samba shares. I'd like to configure the samba shares per group on the consuming samba clients, which is easy by looking at the sambashares variable. 
However i need to create both sets of shares on the samba server. I this case i would like to something like final_sambashares: "{{ groupvars['cluster1'] | union(groupvars['cluster2'] }}". One other way would be to set the merge behaviour, but that is less preferable. 

I could fake it by either creating a host in ansiblehosts, but then I run the risk of executing plays on hosts that don't exist. Or i could dynamically add_host a host with
add_host: host=fakehost_groupname groups=groupname
Next I can access the variables using hostvars['fakehost_groupname'] but the I run the risk of executing plays on this fake host with additional errors. This is less desirable, but my current workaround

**Comment by bcoca** [comment]
your example benefits less from 'group accessible vars' than from making certain vars 'mergable'

**Comment by morphje** [comment]
@bcoca make certain vars mergable? I am under the impression that it's a global setting? Can you define merging on a variable level? I prefer not to set merge globally to adhere to the general concept of ansible variables.

**Comment by bcoca** [comment]
Yes, what i'm saying is that the new feature that would better solve the issue would be something like this:
```
varname: !mergable 
   key1: value1
   key2: value2
```

**Comment by morphje** [comment]
@bcoca ahhhhh, i like the way you are thinking! That would make it an even better feature request
So i would get something like this?
group_vars\group_a
```
varname: !mergable
  - name: foo
    setting: something
```
group_vars\group_b
```
varname: !mergable
  - name: bar
    setting: great
```

The resulting variable would contain a list with both foo and bar.

+1 for that

**Comment by morphje** [comment]
Although I've dabbled in the shallows of ansible, my knowledge of the ansible code is far from enough to even attempt to create such a pull request. If you could give me some pointers where to start I'd sure like to  take a crack at it.

**Comment by bcoca** [comment]
both variable manager and the ansible yaml constructor need to be involved.

**Comment by morphje** [comment]
Digging through the code i was thinking the following:
lib\ansible\parsing\yaml\constructor.yml
```
    def construct_mergeable_yaml_str(self, node):
        value = self.construct_yaml_str(node)
        ret = AnsibleUnicode(value)
        ret.mergeable = True
        return ret

AnsibleConstructor.add_constructor(
    u'!mergeable',
    AnsibleConstructor.construct_mergeable_yaml_str)
```

And somehow try to pry out that mergable property in the combine_vars function from lib/ansible/utils/vars.py
Should it be done like this? my knowledge of pyyaml is rather limited, this is just basically a copy paste interpretation of the constructor code.

**Comment by patrickdeelman** [comment]
@bcoca I've taken several shots at this, but i can't seem to pry the !mergeable out of the original json document into ansible. However i would like to suggest to implement ansible_merge: yes comparable to: http://docs.ansible.com/ansible/devel/user_guide/intro_inventory.html#id11 (ansible_group_priority)

This is quite easy to implement as you only have to take the combine_vars function into account. You check the key of the variable you want to merge and voila instant merging. 

Please let me know if you regard this as a viable option and to keep functionality equal within ansible.

**Comment by bcoca** [comment]
related to my post above, this implements per var merge control #25948

**Comment by Vladimir-csp** [comment]
Using yaml tags to explicitly control merging/replacing data would eliminate SO MANY hurdles and monstrous workarounds! This feature is in "must have" category.

Please also add this for lists.
Maybe includeing set filters: `!union`, `!difference`, `!intersect`, `!append`, `!insert` (at beginning), `!replace`
This would remove the need for a heap of conditions, inline filters, clumsy generators, extra intermediate variables, etc, etc...

**Comment by samdoran** [comment]
Direct access to group_vars isn't really a thing since we flatten the group_vars into hostvars. We would have to rewrite vars manager and large chunks of inventory in order to make this happen.

To discuss this further, please reach out on IRC or the mailing list:

   * IRC: #ansible-devel on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel
