### ISSUE TITLE
Following this tutorial, but now no GATHERING FACTS output?

### ISSUE THREAD

**Issue by scheung38** [ansible/ansible#22570]
Trying to follow this tutorial in Mac OSX:

https://github.com/glenjarvis/ansible_tutorial/blob/develop/src/playbook_examples/demo_playbook_iter_01.yml

$ ansible-playbook demo_playbook_iter_01.yml

---
- hosts: webservers
  tasks:
  - name: Make sure all OS patches are applied
    shell: yum update -y
    sudo: yes 
 
##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

PLAY [webservers] **************************************************************

TASK [setup] *******************************************************************
ok: [34.248.33.69]

TASK [Make sure all OS patches are applied] ************************************
changed: [34.248.33.69]
 [WARNING]: Consider using yum module rather than running yum

PLAY RECAP *********************************************************************
34.248.33.69               : ok=2    changed=1    unreachable=0    failed=0   
```

where is the GATHERING_FACTS output? Thanks

**Comment by lostick** [comment]
This tutorial is outdated, and is not associated  in any way with the official Ansible repo.

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by scheung38** [comment]
I probably think that is the reason too. Usually it is the case but could someone suggest what I need to do in order to get GATHERING_FACTS to display?
