### ISSUE TITLE
notify keyword triggers on unchanged items inside a loop

### ISSUE THREAD

**Issue by berlic** [ansible/ansible#22579]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
`notify` plus `with_`-loops

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### CONFIGURATION
Standard

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When use `notify` with dynamic handler name inside `with_`-loop, all handlers are triggered no matter what item is changed.

##### STEPS TO REPRODUCE
```
---
- hosts: localhost
  gather_facts: no
  tasks:
    - file:
        path: /tmp/file1
        state: absent
    - copy:
        content: zzz
        dest: /tmp/file2
    - copy:
        content: zzz
        dest: /tmp/file{{ item }}
      notify: file{{ item }} changed
      with_items:
        - 1
        - 2
  handlers:
    - name: file1 changed
      debug:
        msg: file1 changed
    - name: file2 changed
      debug:
        msg: file2 changed
```

##### EXPECTED RESULTS
Only `file1 changed` handler should run.

##### ACTUAL RESULTS
Two handlers executed, despite the fact that only `file1` is changed inside a looped task.

If it is expected behaviour, it should be properly documented.

If it is not, the problem is [here](https://github.com/ansible/ansible/blob/36b462ba857361ba310c7967a721c025c13d2225/lib/ansible/plugins/strategy/__init__.py#L428):
```
                for result_item in result_items:
                    if '_ansible_notify' in result_item:
                        if task_result.is_changed():
```
we iterate over each item in result_items, but fire trigger if whole task  is in changed state.

If you change `task_result.is_changed()` to `result_item['changed']`, then only handler that is bound to changed item is triggered, as expected.

**Comment by bcoca** [comment]
notify uses the task status, not per loop item status

**Comment by berlic** [comment]
Yes, I see this from code. But there are plenty of cases when users want to template a pack of systemd units with a loop and notify to restart only those services that were updated.

If this is intended behaviour, this should be stressed in the documentation. Because having templatable notify targets for each item and not having ability to trigger them separately is a bit misleading.

Example for single notify target and multiple items: update multiple nginx config files and reload/restart nginx if any of them changed. Works now and will work same way if notification is made per item.

Example for multiple notify targets and multiple items: update many systemd units (like `service_{{ item }}`) and restart only those that were changed. Doesn't work now and will work as expected if notification is made per item.

But I personally see no examples when Ansible should trigger all per-item handlers as a result of one item change.

**Comment by krzysztof-magosa** [comment]
You can register result of task and then notify just one handler which will base on registered variable.

**Comment by krzysztof-magosa** [comment]
> But I personally see no examples when Ansible should trigger all per-item handlers as a result of one  item change.

Most of people do not template handler names. For example I generate hundreds of vhosts for nginx, then I want to reload it only once and not 100x.

**Comment by berlic** [comment]
@krzysztof-magosa Ansible is smart enough to execute handler task only once, even if it was triggered 100 times during play. Your case (`single notify target and multiple items`) is mentioned in my comment and will work fine after proposed modification (bug fix?).

**Comment by phil-hildebrand** [comment]
I would also like to see this change done.  In my case, an hadoop variable change could cause just one config files to change and notify only that service to restart, rather than all services to restart.

Something like this:
```
- name: copy the hadoop configuration files
  template: src=hadoop/{{ item.config }}.j2 dest=/etc/hadoop/conf/{{ item.config }}
  with_items:
    - { config: core-site.xml, services: hadoop }
    - { config: hdfs-site.xml, services: hadoop }
    - { config: mapred-site.xml, services: yarn }
    - { config: yarn-site.xml, services: yarn }
  notify: "restart {{ item.services }}"
```

**Comment by Stehsegler** [comment]
+1 Also really would like to see this fixed.

**Comment by alambike** [comment]
:+1: , I just realize that all of my handlers are notified when an item in the loop changes. 
I understand that the whole tasks status is failed when one item fails,  but, as we can use {{item}} in notify, this makes me think that just the right handler will be notified, and organize handlers in that way.

**Comment by yami12376** [comment]
Is this possible in 2019?
I want to notify my handler only with items from loop that have changed.

**Comment by jamessewell** [comment]
I actually want the inverse. I have a loop with many items, some need a reload if they change config some need a restart -> each has an action variable which I want to use to trigger

**Comment by mengqian-liu** [comment]
It's possible for 2020?
I really like to see this fixed.

**Comment by bcoca** [comment]
making note since this came up in IRC meeting, this won't be a feature we are likely to add since it requires a lot more than just 'status' at the item level, the task for example can subsequently fail and this change would disociate the expected host-task tuple that Ansible is based around.

If you want a 'per task item' notify, you can control adding or not to the notification list:

`notify: "{{ results is changed|ternary('Restart  ' ~ item.key ~ ' container',  None) }}`

see logs linked at https://github.com/ansible/community/issues/568#issuecomment-705641359 for details

**Comment by yoctozepto** [comment]
It turned out to be not-that-simple [1] but I did it [2].

Please enjoy the example workaround, everyone in need!

[1] http://paste.openstack.org/show/798878/
[2] https://gist.github.com/yoctozepto/4408d70fee31ac3ba9d8a6491c370dfe

**Comment by markgoddard** [comment]
This makes me sad. I don't know the internals of Ansible enough to dispute the assertion, but fundamentally I don't see why a failed item would be a problem - is it not just the same as a failed task preventing previously notified handlers from running for a given host?
