### ISSUE TITLE
ansible-galaxy seems to munge role filenames if the role name is a substring in the filename (via requirements.yml)

### ISSUE THREAD

**Issue by alikins** [ansible/ansible#22572]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 8b6d786cff) last updated 2017/03/13 09:15:01 (GMT -400)
  config file = /home/adrian/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]


```

##### CONFIGURATION

```
[defaults]
# though role path is always specified with -p for these case
roles_path = $HOME/ansible/galaxy-roles:$HOME/ansible/roles:/etc/ansible/roles
```

##### SUMMARY

Looking at https://github.com/ansible/ansible/issues/22562 and trying to reproduce it 
(ala https://github.com/alikins/ansible-bug-repro/tree/master/role_sudo_22562)
I noticed the weird behavior when ansible-galaxy tries to install https://github.com/jlund/ansible-go from a requirements.yml

It seems like the git repo being named 'ansible-go' is confusing it.  The role that gets installed
ends up being installed with the name 'go'.

```
[fedora-25:github_roles (master %)]$ ansible-galaxy -vvv install -r requirements.yml -p roles_external/
Using /home/adrian/.ansible.cfg as config file
Opened /home/adrian/.ansible_galaxy
found role {'scm': 'git', 'src': 'https://github.com/jlund/ansible-go', 'version': 'cfeba7c4db16aac3fa3db775d01ea911b21f828d', 'name': 'go'} in yaml file
Installing role go 
- extracting go to roles_external/go
- go (cfeba7c4db16aac3fa3db775d01ea911b21f828d) was installed successfully
```

Compared to installing via a scm url without the requirements.yml

```
[fedora-25:github_roles (master %)]$ ansible-galaxy -vvvvv install git+ssh://git@github.com/jlund/ansible-go -p roles_external/
Using /home/adrian/.ansible.cfg as config file
Opened /home/adrian/.ansible_galaxy
Installing role ansible-go 
- extracting ansible-go to roles_external/ansible-go
- ansible-go was installed successfully
[fedora-25:github_roles (master %)]$ ls roles_external/
ansible-go
```

But the odder part is that the file names in the 'files/' section get changed.

as in the upstream git repo:
```
[fedora-25:github_roles (master %)]$ ls upstream_git/ansible-go/files/
go-bin.sh  go-path.sh
```

as installed via requirements.yml:

```
[fedora-25:github_roles (master %)]$ ls roles_via_requirements/go/files/
-bin.sh  -path.sh
```

Presumably something is attempting to strip 'ansible' off the repo url for the role name. And maybe something is stripping the role name off of files/* for some reason??

##### STEPS TO REPRODUCE

```
[fedora-25:github_roles (master %)]$ mkdir upstream_git
[fedora-25:github_roles (master %)]$ cd upstream_git/
[fedora-25:upstream_git (master %)]$ git clone https://github.com/jlund/ansible-go
Cloning into 'ansible-go'...
remote: Counting objects: 166, done.
remote: Total 166 (delta 0), reused 0 (delta 0), pack-reused 166
Receiving objects: 100% (166/166), 21.25 KiB | 0 bytes/s, done.
Resolving deltas: 100% (50/50), done.
Checking connectivity... done.
[fedora-25:upstream_git (master %)]$ ls ansible-go/files/
go-bin.sh  go-path.sh
[fedora-25:upstream_git (master %)]$ cd ..
[fedora-25:github_roles (master %)]$ ls
ansible-go  requirements2.yml  requirements_example.yml  requirements.yml  roles_external  upstream_git
[fedora-25:github_roles (master %)]$ rm -rf ansible-go/
[fedora-25:github_roles (master %)]$ cat requirements.yml 
---
- name: go
  src: https://github.com/jlund/ansible-go
  version: cfeba7c4db16aac3fa3db775d01ea911b21f828d
[fedora-25:github_roles (master %)]$ rm -rf roles_external/*
[fedora-25:github_roles (master %)]$ ansible-galaxy -vvvvv install -r requirements.yml -p roles_external/
Using /home/adrian/.ansible.cfg as config file
Opened /home/adrian/.ansible_galaxy
found role {'scm': 'git', 'src': 'https://github.com/jlund/ansible-go', 'version': 'cfeba7c4db16aac3fa3db775d01ea911b21f828d', 'name': 'go'} in yaml file
Installing role go 
- extracting go to roles_external/go
- go (cfeba7c4db16aac3fa3db775d01ea911b21f828d) was installed successfully
[fedora-25:github_roles (master %)]$ ls roles_external/go/
defaults  files  meta  README.md  tasks  vars
[fedora-25:github_roles (master %)]$ ls roles_external/go/files/
-bin.sh  -path.sh
```

```yaml

```

##### EXPECTED RESULTS

I guess the same behavior as if installing it via git scm url:

```
[fedora-25:github_roles (master %)]$ ansible-galaxy -vvvvv install git+ssh://git@github.com/jlund/ansible-go -p roles_external/
Using /home/adrian/.ansible.cfg as config file
Opened /home/adrian/.ansible_galaxy
Installing role ansible-go 
- extracting ansible-go to roles_external/ansible-go
- ansible-go was installed successfully
[fedora-25:github_roles (master %)]$ ls roles_external/
ansible-go
[fedora-25:github_roles (master %)]$ ls roles_external/ansible-go/files/
go-bin.sh  go-path.sh
```

##### ACTUAL RESULTS

```
[fedora-25:github_roles (master %)]$ ansible-galaxy -vvv install -r requirements.yml -p roles_via_requirements/
Using /home/adrian/.ansible.cfg as config file
Opened /home/adrian/.ansible_galaxy
found role {'scm': 'git', 'src': 'https://github.com/jlund/ansible-go', 'version': 'cfeba7c4db16aac3fa3db775d01ea911b21f828d', 'name': 'go'} in yaml file
Installing role go 
- extracting go to roles_via_requirements/go
- go (cfeba7c4db16aac3fa3db775d01ea911b21f828d) was installed successfully
```

```

```

**Comment by alikins** [comment]
Some of the oddity can be explained by problem in the requirements.yml

``` yaml
---
- name: go
  src: https://github.com/jlund/ansible-go
  version: cfeba7c4db16aac3fa3db775d01ea911b21f828d
```

The 'name' value should be ansible-go. 
That is why it ends up installed as 'go' not 'ansible-go'.

The question of why files/go-bin/sh gets munged is odder. 

https://github.com/ansible/ansible/blob/devel/lib/ansible/galaxy/role.py#L319

If a file path has the top level dir name as a substring, that line replaces it with ''. In this case,
the archive top level dir is 'go', so 'files/go-bin.sh' becomes 'files/-bin.sh'. 

Not entirely sure I understand what that line is attempting to do or what it has to do with the comment a few lines above. Either way, it's overly aggressive.

**Comment by derekmahar** [comment]
I encountered this issue today in branches `stable-2.3` and `devel`:

```
derek@derek-lubuntu:~/Projects/platinum/platinum-ansible$ ansible-galaxy --version
ansible-galaxy 2.4.0 (devel 5f517fdfa9) last updated 2017/04/11 16:14:21 (GMT -400)
  config file = /home/derek/Projects/platinum/platinum-ansible/ansible.cfg
  configured module search path = [u'/home/derek/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/derek/Projects/ansible/ansible/lib/ansible
  executable location = /home/derek/Projects/ansible/ansible/bin/ansible-galaxy
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

```
derek@derek-lubuntu:~/Projects/platinum/platinum-ansible$ ansible-galaxy --version
ansible-galaxy 2.3.0.0 (stable-2.3 9818ca366d) last updated 2017/04/11 15:49:10 (GMT -400)
  config file = /home/derek/Projects/platinum/platinum-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

Branch `stable-2.2` does not have this problem:

```
ansible-galaxy 2.2.3.0 (stable-2.2 6ee3a42673) last updated 2017/04/11 16:04:54 (GMT -400)
  lib/ansible/modules/core:  not found - use git submodule update --init lib/ansible/modules/core
  lib/ansible/modules/extras:  not found - use git submodule update --init lib/ansible/modules/extras
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

Here's an example of how `ansible-galaxy` mangles some of the task file names in role `application-database` that it downloads from a local Git repository:

```
derek@derek-lubuntu:~/Projects/platinum/platinum-ansible$ find roles/application-database/tasks/
roles/application-database/tasks/
roles/application-database/tasks/main.yml
roles/application-database/tasks/deploy-.yml
roles/application-database/tasks/create--sql.yml
roles/application-database/tasks/create--liquibase.yml
```

Here's what those file names should look like:

```
derek@derek-lubuntu:~/Projects/platinum/platinum-ansible$ find roles/application-database/tasks/
roles/application-database/tasks/
roles/application-database/tasks/deploy-application-database.yml
roles/application-database/tasks/main.yml
roles/application-database/tasks/create-application-database-liquibase.yml
roles/application-database/tasks/create-application-database-sql.yml
```

**Comment by derekmahar** [comment]
I suspect one of the following commits is the culprit:

```
commit 5f517fdfa95785332ca23e958488a77d090511dd
Author: Sloane Hertel <shertel@redhat.com>
Date:   Tue Apr 11 16:02:14 2017 -0400

    [cloud] route53_zone: allow split horizon for route53_zone and refactor - fixes #22939 (#23190)
    
    * allow split horizon for route53_zone and refactor
    
    * fix documentation
    
    remove comment
    
    fix version_added
    
    * Remove unused imports
    
    * Only include zone as matching if it has the same privacy setting
    
    * Use `.endswith` instead of indexing into a string
    
    * Update public zone behavior to only create new if there is no matching public zone
    
    * Remove from legacy PEP8 files

commit e575eae2ec8fc76ba1db6a24d6ad1e381123bff8
Author: John R Barker <john@johnrbarker.com>
Date:   Tue Apr 11 20:35:21 2017 +0100

    Document how to debug network issues (#23503)
```

If I checkout the immediate parent commit of `e575eae2ec8fc76ba1db6a24d6ad1e381123bff8`, the problem goes away.

**Comment by alikins** [comment]
@derekmahar  Thanks for the confirmation of the issue, the behavior is odd enough enough I wasnt sure if it would show up 'in the wild'


For the case:

```
derek@derek-lubuntu:~/Projects/platinum/platinum-ansible$ find roles/application-database/tasks/
roles/application-database/tasks/
roles/application-database/tasks/main.yml
roles/application-database/tasks/deploy-.yml
roles/application-database/tasks/create--sql.yml
roles/application-database/tasks/create--liquibase.yml
```

Was the role installed via a requirements.yml ( 'ansible-galaxy -r requirements.yml') or directly (ie, 'ansible-galaxy install derermahar.application-database' ?

**Comment by alikins** [comment]
@derekmahar Not sure how 5f517fdfa95785332ca23e958488a77d090511dd or e575eae2ec8fc76ba1db6a24d6ad1e381123bff8 would be involved, since they seem unrelated.

Haven't tested or bisected yet, but 19d390135e134feeeaf0305cc534f21ea25a9883 would be my first suspect.

**Comment by derekmahar** [comment]
@alikins Yes, all of these roles are installed via requirements.yml and the source is a local Git repository.

I mentioned those two commits because they were quite recent and omitting them made the problem go away.

**Comment by bluesalt** [comment]
@alikins I believe your triage is correct.  After blaming the history, I found the code resulted from this [commit](https://github.com/willthames/ansible/commit/19d390135e134feeeaf0305cc534f21ea25a9883) which is intended to solved  #15413. 
The code need to be fixed because it could rename any file or subdirectory whose name happens to contain  the role name. The behaviour could break the role.  
What I don't understand is why all the containing directories have to be removed instead of just the leading one.  
@willthames, can we just revert the code `parts = member.name.replace(archive_parent_dir, "").split(os.sep)` back to `parts = member.name.split(os.sep)[1:]` ?

**Comment by derekmahar** [comment]
@bluesalt, I applied the fix suggestion that you had made to @willthames and it fixed the problem.

**Comment by hogarth-sv** [comment]
@bcoca this has been quite the breaking change and a test across my roles at work breaks most of them (stuff like a docker role no longer being able to find sysconfig-docker.j2 as that ends up sysconfig- etc etc) 

can this get a an urgent prioritisation for a fix to be applied and released? 

at the least if a fix can be agreed on and merged we can backport that commit to the fedora/epel packages until the 2.3.1 release

**Comment by hogarthj** [comment]
for now i've blocked an auto push in Fedora/EPEL to avoid it breaking anyone's activities there ... if we can get a commit agreed on (even if not a quick release of 2.3.1 with a bug fix) I can include that commit in a fresh fedora/epel build until 2.3.1 does get a release

this breaks pretty much every one of our ansible projects at my workplace as we use ansible-galaxy to pull roles (via git src) down from our bitbucket server and every one of those fails due to our yum role trying to configure yum.conf but the template of yum-distro.conf.j2 gets pulled down as -distro.conf.j2 (and it also breaks docker as docker-sysconfig.j2 ends up -sysconfig.j2 etc etc )

**Comment by gundalow** [comment]
See also https://github.com/ansible/ansible/pull/23633

**Comment by derekmahar** [comment]
@hogarthj, I feel your pain.  I'm just happy that the fix that @bluesalt suggested did in fact fix the names of several files in several of my private roles.  Otherwise, I would have had to rename these files to remove the role name.

**Comment by hogarth-sv** [comment]
@derekmahar we use RHEL/CentOS exclusively here, with EPEL only, so I didn't get accidental breakage ... but I did think it worthwhile checking the package behaviour in the epel-testing repository ... and glad I did!

I'm testing the patch in the PR now and will probably do a 2.3.0 build with that if our internal modules pass their test suites for Fedora/EPEL

**Comment by alikins** [comment]
in testing https://github.com/ansible/ansible/pull/23739 and https://github.com/ansible/ansible/pull/23703
it looks like https://github.com/ansible/ansible/pull/23739 fixes the problem seen here but regresses for the issue https://github.com/ansible/ansible/issues/15413 fixed in https://github.com/ansible/ansible/commit/19d390135e134feeeaf0305cc534f21ea25a9883

 https://github.com/ansible/ansible/pull/23703 seems to fix both, so leaning towards it.

**Comment by alikins** [comment]
Fix merged into devel as 79943b86a1ee9338049149824bbb12f99d8186ee

**Comment by alikins** [comment]
Merged into stable-2.3 as b9ee0c547797f253771489542f0f5ac08bf04bf6

**Comment by hogarth-sv** [comment]
Thanks guys, I'm backporting the merged patch to the Fedora/EPEL builds now so that we can get 2.3.0 out the door asap

**Comment by hho** [comment]
So this has been fixed _19_ days ago and no new release has been made to push it out?

`ansible-galaxy` is unusable in 2.3.0.0 because of this :cry:

**Comment by gundalow** [comment]
@hho Ansible 2.3.1 RC1 (which will include this fix) should be out this week, and the final shortly after.

**Comment by phreddrick** [comment]
The ansible/ansible ppa for ubuntu still has a broken version of this. Any idea when they will be updating?

**Comment by pablomoreno61** [comment]
In Mac Sierra OSX, ansible stills outdated, via brew or pip

**Comment by nicklaw5** [comment]
I can confirm that upgrading from `v2.3.0` to `v2.3.1` has resolved this issue in my case.
