### ISSUE TITLE
Ansible-playbook message is too vague for unknonw modules

### ISSUE THREAD

**Issue by sedrubal** [ansible/ansible#22592]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible-playbook

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/se/documents/fablab/github/linux-clients/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
`-`

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Ansible-playbook error messages are often very imprecise. Especially when there is a spelling mistake in a module name or if the module isn't available in the current ansible version, the error output is completely unusable.

##### STEPS TO REPRODUCE
- Create a role with tasks and make a spelling mistake for a module name
- Run `ansible-playbook site.yml`

```yaml
  - name: yadayada
    misspelled_package_name:
      args: foobar
```

##### EXPECTED RESULTS

Ansible should tell me that the module is unknown. (I think it's not too hard to detect, that ansible doesn't know this module).

##### ACTUAL RESULTS

A very vague error description was given

```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '.../roles/rolename/tasks/main.yml': line 22, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- misspelled_module_name:
  ^ here


The error appears to have been in '.../roles/rolename/tasks/main.yml': line 22, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- misspelled_module_name:
  ^ here
```

**Comment by dagwieers** [comment]
The main problem is that Ansible does not know if unknown keys in the task dictionary are meant to be modules or directives. In the old days the module was part of the `action:` key, so it was obvious which entry in the task dictionary was the module. But to make playbooks "easier to write" the `action:` key was removed and replaced with the module name. Which means that suddenly modules and directives are in the same namespace.

**Comment by sedrubal** [comment]
Ah ok, now I get the message and I see the problem...
