### ISSUE TITLE
Ansible doesn't handle host_vars for 'all' hosts via folder structure

### ISSUE THREAD

**Issue by akaradzha** [ansible/ansible#22605]
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME

Ansible folder handler
##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

Current Ansible supports loading host_vars via folder structure:
inventories/
  host_vars/
      host1/main.yml
      host2/main.yml
but doesn't handle var file for all hosts
      **all**/main.yml
'all' could be used only in host file like:
[all:vars]
some_var

##### STEPS TO REPRODUCE

create some structure like at best practice: http://docs.ansible.com/ansible/playbooks_best_practices.html
inventories/
  host_vars/
      host1/main.yml
      host2/main.yml

try to add var file for **all** hosts in the same fashion.

```yaml

```

##### EXPECTED RESULTS

loading vars from 
host_vars/
    all/main.yml

##### ACTUAL RESULTS

nothing happens

```

```

**Comment by dagwieers** [comment]
But `all` is not a host, it is a group. So you should be putting these in `group_vars/all` instead.

notabug

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
