### ISSUE TITLE
Ansible trying to connect remote host for local playbook

### ISSUE THREAD

**Issue by regexcracker** [ansible/ansible#22639]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION
ansible 2.1.0.0

##### CONFIGURATION
ansible.cfg

Added remote_tmp=/Home/Vagrant

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Included two sub playbooks in one playbook. One runs on local host and other on remote hosts. While running the main playbook, Local playbook trying to connect with local user on remote host. So getting host unreachable error.

##### STEPS TO REPRODUCE
-- Create a playbook by including two sub-playbooks. One for Local action and another for remote action.
-- Run main playbook along with remote user.

main_utility.yml
```
- include: Local.yml
- include: Remote.yml
```

Local.yml
```
- name: Starting Action
  hosts: localhost ansible_connection=local
  gather_facts: no
  become: no
  strategy: free
  roles:
   - { role: role_for_action }
```

inventory:
```
[test]
remote_host.dc.com
```

Command for execution:
```
ansible-playbook -vvvv main_utility.yml -u vagrant --extra-vars "host_group=test"
```
##### EXPECTED RESULTS
Local.yml perform all the actions specified on ansible host
Remote.yml perform all the actions specified on ansible host

##### ACTUAL RESULTS
```
task path: main_utility.yml:4
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: local_user
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vagrant/ansible-tmp-1489205307.15-168881386422011 `" && echo "` echo /home/vagrant/ansible-tmp-1489205307.15-168881386422011 `" )'
fatal: [localhost]: UNREACHABLE! => 
{"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. 
Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". 
Failed command was: ( umask 77 && mkdir -p \"` echo /home/vagrant/ansible-tmp-1489205307.15-168881386422011 `\" && echo \"` echo /home/vagrant/ansible-tmp-1489205307.15-168881386422011 `\" ), exited with result 1", "unreachable": true}
```

**Comment by jctanner** [comment]
@regexcracker There's no indication in the output that a remote connection attempt was made. The error implies that the control host has a permission problem on the remote_tmp dir.

```
you may have been able to authenticate and did not have permissions on the remote directory
Failed command was: ( umask 77 && mkdir -p ...
```

Please try to run this command on the controller machine as the vagrant user and show us the result ..

```
umask 77 && mkdir -p "` echo /home/vagrant/ansible-tmp-1489205307.15-168881386422011 `"
```

needs_info

**Comment by bcoca** [comment]
`hosts: localhost ansible_connection=local` <= this is not a thing, use 

```
hosts: localhost
connection: local
```

**Comment by regexcracker** [comment]
@jctanner 
Below error is encountered because playbook having ansible hosts and connection as Local and it tries to create directory on localhost at path:/Home/vagrant (which is remote location as per ansible.cfg).
 
you may have been able to authenticate and did not have permissions on the remote directory
Failed command was: ( umask 77 && mkdir -p ..

@bcoca 
Tested with below configuration but not worked
hosts: localhost
connection: local

**Comment by bcoca** [comment]
@regexcracker, it will not fix the error message, but is a correct play, what you posted above is not. Your error comes from a permissions issue on the target.

**Comment by regexcracker** [comment]
Issue resolved by updating remote_tmp to /tmp in ansible.cfg

Thanks @bcoca and @jctanner
