### ISSUE TITLE
'.' (dot/period) not allowed in j2 templates

### ISSUE THREAD

**Issue by wgj** [ansible/ansible#2264]
I'm trying to do math with percentages, so having a floats available would be helpful.

[wes@mgmt001 ~]$ ansible-playbook workspace/ansible/playbooks/segmentation/shard.yml 
PLAY [shard_] *_******************\* 

GATHERING FACTS ********************\* 
ok: [shard507.dal05]

TASK: [template: init.d/segmentation] ********************\* 
fatal: [shard507.dal05] => {'msg': "unexpected token '.'", 'failed': True} 
fatal: [shard507.dal05] => {'msg': "unexpected token '.'", 'failed': True}

FATAL: all hosts have already failed -- aborting
PLAY RECAP ********************\* 
shard507.dal05                 : ok=1    changed=0    unreachable=1    failed=0 

I can provide more of the jinja template, but the piece of code that stops ansible-playbook is '{{.8}}' (it also complains about '.' twice, where it is only used once, which is weird :) )

**Comment by mpdehaan** [comment]
Ok, so this is pretty straightforward.

Just do "0.8" instead of .8

**Comment by mpdehaan** [comment]
not sure about why your host appears twice, it seems like it is in the host file twice, but that seems unlikely given the facts message is printed only once.

can you give me the output of "ansible --version" so I can look into this?

**Comment by wgj** [comment]
Whoops, sorry about that: 
[wes@mgmt001 ~]$ ansible --version
ansible 0.8

I was actually specifying an inventory file (I removed it from this issue thinking it was superfluous), wherein the host file contained just "shard507.dal05"

**Comment by mpdehaan** [comment]
Ok, let's see if that double message is still there in the latest devel.

It should not be.

In any event, the Jinja2 syntax error is the "0.8" thing versus ".8" and
you should be good.  Stuff inside {{ }} is more or less legal Python, and
.8 is not there.

**Comment by wgj** [comment]
0.8 vs .8: d'oh. Thanks again.
