### ISSUE TITLE
syslog_json callback doesn't cast SYSLOG_PORT value from environment as integer

### ISSUE THREAD

**Issue by jralbert** [ansible/ansible#22659]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

syslog_json callback plugin

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### CONFIGURATION
Specifying SYSLOG_PORT environment variable to target a non-default port:
SYSLOG_PORT=1514

##### OS / ENVIRONMENT
Redhat 6 (but this should affect any UNIX platform)

##### SUMMARY
The syslog_json callback plugin allows configuration of its target port by specifying the SYSLOG_PORT environment variable; however, it doesn't cast the value it obtains from get_env as int, so specifying a port number this way results in errors  on each task and no syslog output:

Traceback (most recent call last):
  File "/usr/lib64/python2.6/logging/handlers.py", line 806, in emit
    self.socket.sendto(msg, self.address)
TypeError: an integer is required

##### STEPS TO REPRODUCE
For any playbook, specify the syslog_json callback plugin and the syslog port environment variable:

```yaml
ANSIBLE_STDOUT_CALLBACK=syslog_json SYSLOG_PORT=1514 ansible-playbook playbook.yml
```

##### EXPECTED RESULTS

No output to stdout, JSON output directed to syslog for each task.

##### ACTUAL RESULTS

```
Traceback (most recent call last):
  File "/usr/lib64/python2.6/logging/handlers.py", line 806, in emit
    self.socket.sendto(msg, self.address)
TypeError: an integer is required
```

**Comment by jralbert** [comment]
Submitted pull request https://github.com/ansible/ansible/pull/22664 to fix this issue.

**Comment by jctanner** [comment]
resolved_by_pr https://github.com/ansible/ansible/pull/22664
