### ISSUE TITLE
git module doesn't handle switching repos

### ISSUE THREAD

**Issue by diggerk** [ansible/ansible#2266]
If git module is used without "remote" parameter, then changing "repo" param wouldn't lead to proper handling of switching to another remote repo.

Example:
1. Do initial clone by using "git repo=repo-A dest=/tmp/workdir version=branch-X"
2. Do clone using the same dest, but different repo with "git repo=repo-B dest=/tmp/workdir version=branch-X"

Expected on step 2: it fetches branch-X from repo-B and updates working dir accordingly.

Effectively it does nothing.

My suggestion is to handle mapping between git remote names and repos in the git module, generating new remotes if necessary. Parameter "remote" should be removed from the module then.

**Comment by mpdehaan** [comment]
I can believe that, something you may want to work on?

(Otherwise I believe I've delegated the git module to @sfromm -- update: not assigning to you, just in case you were interested)

**Comment by sfromm** [comment]
The parameter `remote` cannot be removed without breaking existing playbooks.  I know there are users who currently use the remote parameter with values other than `origin`.

@aklochkovgd, can you describe your use case scenario here?  What were you thinking you would base the remote name on?

One last question:  should there be any restrictions on adding remotes?  Must the repository name be the same or should we allow the user to typo/bork their setup?

**Comment by dhozac** [comment]
I would imagine that if remote is not set, origin is used, and it is ensured to have the URL specified in the action, and used for the update.

**Comment by diggerk** [comment]
Agree to Daniel's view. The only question is what happens if "remote" param
is not set and the URL specified is not equal to the URL of repo configured
for "origin" earlier. Ansible may report an error or it can generate a new
remote name and use it whenever the same URL is used again.

On Sat, Mar 2, 2013 at 1:59 PM, Daniel Hokka Zakrisson <
notifications@github.com> wrote:

> I would imagine that if remote is not set, origin is used, and it is
> ensured to have the URL specified in the action, and used for the update.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/2266#issuecomment-14336869
> .

## 

Andrey Klochkov
Grid Dynamics
Skype: aklochkov_gd
www.griddynamics.com
aklochkov@griddynamics.com

**Comment by sfromm** [comment]
I'd prefer to see `remote` set explicitly by the user and avoid potential pitfalls from creating a remote name based on the repo url.  That would avoid having to create a series of rules when dealing with repo urls such as:
- git://example.net/splat.git
- git://github.com/foo/splat.git
- git://github.com/bar/splat.git
- git://gitorious.org/splat/splat.git

Possible usage in playbook could be:

```
# here, remote defaults to origin
- action: git repo=git://github.com/foo/splat.git dest=/var/www/splat
# do other stuff ... and then:
# add remote by the name of bar
- action: git repo=git://github.com/bar/splat.git dest=/var/www/splat remote=bar
```

**Comment by mpdehaan** [comment]
I am fine w any changes that do not break existing users.

-- Michael

**Comment by mpdehaan** [comment]
any progress on this?

**Comment by sfromm** [comment]
Not on my part.  I've done a little research, but don't have anything that would make 1.1.

**Comment by mpdehaan** [comment]
I think I would be fine with it making switching repos be an error for now, until it could support that.

**Comment by jimi-c** [comment]
Please see the above patch, which I believe will resolve this issue. @sfromm / @aklochkovgd if you could test this out I would appreciate it.

**Comment by sfromm** [comment]
Reviewing the code, I see that it supports adding a single remote.  If a user tries to add a second remote (not counting origin), the remote _ansible_module_remote_ is removed and the new repo takes its place.  Is it reasonable to think that a user who adds one remote may try to add a second?  Should both remotes be present?  I don't know.

I'd probably still require a user be explicit about remotes with a _remote_ parameter.  That said, I'm not clear on what the use case is for supporting adding/removing remotes with the git module.  It isn't a scenario I've run into.  Unfortunately, I presently don't have enough bandwidth to test this patch.  Maybe @aklochkovgd is better situated to test.

**Comment by jimi-c** [comment]
If a second remote is added, the plugin will delete the first. We could generate a new name for each remote based on the timestamp or something unique, but I doubt many people would need that. This whole use case seemed something of a corner case to me.

**Comment by sfromm** [comment]
I agree it is a corner case. A corner of a corner case.  :-)

Maybe just warn that the user is trying to use a different git repo URL is
more appropriate.

**Comment by jimi-c** [comment]
Closing, as this was merged in a while ago and there haven't been any related issues raised.
