### ISSUE TITLE
Windows/psremoting doc suggestions

### ISSUE THREAD

**Issue by johnboy2** [ansible/ansible#22660]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
win_shell
win_command
win_chocolatey

##### ANSIBLE VERSION

```
2.2.1.0
```

##### CONFIGURATION
On Ansible's side: ansible_winrm_transport
On the Windows' side: psremoting via SSL, and which windows logon authentication types are enabled

##### OS / ENVIRONMENT
Windows Server 2012 R2

##### SUMMARY
Some remote commands require "multi-hop" support of the psremoting login session, and will fail to execute on the Windows side if that isn't present. The failure messages can further be indecipherable to anyone without considerable Windows authentication expertise or in-depth familiarity with the failure types of the affected command(s) they're trying to use.

A doc update describing the issue, with links to useful resources would be invaluable to users running into this issue.

##### STEPS TO REPRODUCE

Assumption: using a "winrm" connection using Ansible's default winrm transport settings.

```yaml
tasks:
 - win_chocolatey:
      name: mssqlserver2014express
```

##### EXPECTED RESULTS
Downloads and installs MS SQL Server 2014 Express

##### ACTUAL RESULTS

Downloads and executes the installer, but the installer fails.

Ansible reports:
```
The following error occurred:
There was an error generating the XML document.
Error result: -2068774911
Result facility code: 1201
Result error code: 1
Please review the summary.txt log for further details
```

Details from chocolatey's install log on the remote show that the underlying issue was an "access is denied" from System.Security.Cryptography.CryptographicException.

##### OTHER NOTES

The equivalent chocolatey command to do the same thing *locally* on the Windows Server is:
```
choco install --yes mssqlserver2014express
```
and that works fine from a remote desktop session, but executing via default-transport winrm/psremoting session fails as described above (whether via Ansible or not).

##### SUGGESTED DOC CHANGE

First of all, this isn't unique to Ansible at all, but documenting the requirement *somewhere* that Ansible users will end up looking will likely help a lot of people -- even if only because it gets them asking the right questions for their psremoting configurations.

Here's one possible Ansible/psremoting configuration that can handle the above scenario:

1. Enable "CredSSP" on the Windows Server, by executing the following powershell commands on the remote system:
   ```
   Enable-WSManCredSSP -Role Server -Force
   Set-Item -Path "WSMan:\localhost\Service\Auth\CredSSP" -Value $true
   ```
1. Upgrade pywinrm on the ansible server, including credssp support (must be at version 0.2.2 or newer):
   ```
   pip install --upgrade 'pywinrm[credssp]'
   ```
1. Instruct Ansible to use CredSSP for its WinRM session, by setting the variable "ansible_winrm_transport" to "credssp".
1. Ensure Ansible is configured to use winrm via SSL, including using the SSL port (required for CredSSP logon).

Note that CredSSP is **not** enabled on Windows by default, as it carries some security considerations. This might also be added as an option to "ConfigureRemotingForAnsible.ps1", but I would **not** make it a default. Kerberos might also work, though I haven't tried it because my use-case wasn't on a domain.

**Comment by jborean93** [comment]
Thanks for the input, the docs definitely needs to be improved and is on the cards for some of the Core team to look at. There is already some (albiet very minimal) docs on credential delegation (double hop) on the docs right now and the auth mechanisms that support this but I agree it can use with some TLC.

**Comment by dagwieers** [comment]
To be honest, I think it was a mistake to not enable CredSSP (by default) from the ConfigureRemotingForAnsible.ps1 script. I don't know why this script enables virtually every mechanism except CredSSP, and has a separate option for enabling CredSSP.

**Comment by jhawkesworth** [comment]
@dagwieers I think at the time that the configure for remoting script was first created there weren't any CredSSP clients other than other windows boxes.   So I guess the separate option was just to keep things as close as possible to previous state.

@johnboy2 What are the security considerations of enabling CredSSP?  I'd suggest it would be worth documenting them so ansible users can make a suitable choice given the environment they are working in.

**Comment by dagwieers** [comment]
@jhawkesworth We had that discussion before, IMHO that script should be having sane defaults for new/existing users. Rather than foster compatibility (with the very first version of the script when functionality was limited).

And people shouldn't be using that script directly (security!), if they do, they deserve breakage :-)

**Comment by johnboy2** [comment]
@jhawkesworth RE security issues with CredSSP, see [here](http://www.powershellmagazine.com/2014/03/06/accidental-sabotage-beware-of-credssp/) for example.

I should state that I am _not_ an expert on this stuff, and only learned about it recently while trying to figure out my win_chocolatey issues. But my takeaway from briefly learning about it suggests that CredSSP should _only_ be used with local accounts; using it with domain accounts looks like it could enable escalation attacks.

**Comment by dagwieers** [comment]
@johnboy2 Hehe, that link was weird :)

BTW That may be a good reason to not enable CredSSP by default. If that is the reason it should be documented as such.

**Comment by johnboy2** [comment]
@dagwieers My bad; should be fixed now

**Comment by nitzmahone** [comment]
Some places are very anti-CredSSP (infosec tinfoil-hat kinds of things)- we decided to leave it off by default for that reason for folks that are just running the script with no options.

Many of the reasons for hating on CredSSP are completely invalidated by typical Ansible usage anyway (especially once `become` is used) so I could probably be convinced to revisit that decision. :) Bring it up in a [WWG IRC meeting](https://github.com/ansible/community/blob/master/MEETINGS.md#windows-working-group) sometime...

**Comment by jborean93** [comment]
The reason why people are anti CredSSP is that the credentials are sent to the server in an encrypted form while Kerberos and NTLM only send some sort of token or hash. Some people don't like this for valid reasons but @nitzmahone is right usually we use Ansible in a way that does this anyway so the point from my mind is moot. It's really a personal choice if you trust the remote host then I think you are fine.

**Comment by jelep** [comment]
as most of you, i am also just learning about CredSSP...

CredSSP can be set up securely, by setting it to which server it can delegate to. but this can lead to a really long list (not sure if  CredSSP settings can include a long list)...

**Comment by jhawkesworth** [comment]
At 19:00 UTC on Tuesday 19 September 2017 this ticket will be processed during the second Windows Sprint,
https://github.com/ansible/community/wiki/Windows:-sprints
we would appreciate if you could join the Sprint to help out with understanding/fixing/closing this issue.

**Comment by jhawkesworth** [comment]
discussed at the sprint meeting.
I plan to elaborate docs on credential delegation and add more info to examples section of win_chocolatey.

**Comment by jborean93** [comment]
PR to expand the Windows documentation which touches on this topic https://github.com/ansible/ansible/pull/30783.
