### ISSUE TITLE
'AnsibleSequence' object has no attribute 'keys'

### ISSUE THREAD

**Issue by endejoli** [ansible/ansible#22671]
##### COMPONENT NAME
playbook

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /home/ubuntu/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### CONFIGURATION
```
cat ansible.cfg 
[defaults]
inventory = /home/ubuntu/ansible
```

##### OS / ENVIRONMENT
```
    Ubuntu 16.04
```

##### SUMMARY
 I am getting below error while executing playbook. Any help will be appreciated. 

ubuntu@i5:~/ansible$ ansible-playbook playbooks/hostname.yml

ERROR! Attempted to read "/home/ubuntu/ansible/playbooks/hostname.yml" as YAML: 'AnsibleSequence' object has no attribute 'keys'
Attempted to read "/home/ubuntu/ansible/playbooks/hostname.yml" as ini file: /home/ubuntu/ansible/playbooks/hostname.yml:2: Expected key=value host variable assignment, got: hosts:

##### STEPS TO REPRODUCE
ansible-playbook playbooks/hostname.yml
-->

```yaml
---
  - hosts: all
    tasks:
      - name: get server hostname
        command: hostname
```

##### ACTUAL RESULTS

```
'AnsibleSequence' object has no attribute 'keys'
Attempted to read "/home/ubuntu/ansible/playbooks/hostname.yml" as ini file: /home/ubuntu/ansible/playbooks/hostname.yml:2: Expected key=value host variable assignment, got: hosts:
```

**Comment by nitzmahone** [comment]
Not a bug. You've got an extra set of indentation before the play starts; each play should be at the leftmost position, not indented.

**Comment by endejoli** [comment]
I have tried with every indentation possible. It gives the same error.

**Comment by nitzmahone** [comment]
Guessing you've got ansible incorrectly installed then, as this works fine for me on 16.04. Did you install from the PPA, pip, source, or what?

**Comment by putarpuar** [comment]
Hi, I have the same error on 16.04 with the 2.3.0 installed via PPA

**Comment by sushisuren** [comment]
use "-i {inventory file}"

**Comment by pkaramol** [comment]
Same here with ansible 2.3.0 and Ubuntu 16.04

however...this is happening ONLY when running it via Vagrant provisioner.

When executing the script via `ansible-playbook` seems to be OK
