### ISSUE TITLE
bash crash

### ISSUE THREAD

**Issue by yinonby** [ansible/ansible#22672]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-playbook
2.2.1.0
##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
from: centos 7: 3.10.0-514.10.2.el7.x86_64
to: ubuntu 16.10 4.8.0-22-generic

##### SUMMARY
Executing a bash script crash on common bash commands within the script, randomly. When I execute this script manually it works fine. Isolated the issue, seems to be related to using "cd".

##### STEPS TO REPRODUCE
on the target server, place 2 scripts, make sure they are executables:
----------------------------
/tmp/foo:
#!/bin/sh
exec /tmp/bar server "$@" >> "/tmp/foo.log" 2>&1 &
----------------------------
/tmp/bar:
#!/bin/sh
__bar() {
hostname >> /tmp/bar.log
hostname >> /tmp/bar.log
hostname >> /tmp/bar.log
hostname >> /tmp/bar.log
hostname >> /tmp/bar.log
  ___OURPWD_____="$PWD"
echo "bar: ___OURPWD_____ $___OURPWD_____" >> /tmp/bar.log
echo "bar: cd $(dirname "$1")" >> /tmp/bar.log
  cd "$(dirname "$1")"
hostname >> /tmp/bar.log
hostname >> /tmp/bar.log
hostname >> /tmp/bar.log
hostname >> /tmp/bar.log
hostname >> /tmp/bar.log
echo "bar: cd $___OURPWD_____" >> /tmp/bar.log
  cd "$___OURPWD_____"
hostname >> /tmp/bar.log
hostname >> /tmp/bar.log
hostname >> /tmp/bar.log
hostname >> /tmp/bar.log
hostname >> /tmp/bar.log
  echo "$REALPATH"
}
__bar
----------------------------
yaml relevant line for where ansible is running from:
- shell: "/tmp/foo"
----------------------------

##### EXPECTED RESULTS
When running /tmp/foo manually and when running it from ansible, should see the same output in /tmp/bar.log

##### ACTUAL RESULTS
When running from ansible-playbook, /tmp/bar crashes sometime after the second "cd". It does not crash if removing both calls to "cd".

**Comment by nitzmahone** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
