### ISSUE TITLE
after running my yml script, I am just getting "Play RECAP" and nothing more

### ISSUE THREAD

**Issue by naarumanchi** [ansible/ansible#22678]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```
---
- hosts: IM
  become: true
  become_user: test
  tasks:

  - name: 1. copy the file
    copy:

      src: /home/test/IMInstall.yml
      dest: /home/test/

##### ACTUAL RESULTS

``` 

``` PLAY RECAP *********************************************************************

**Comment by nitzmahone** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
