### ISSUE TITLE
bashrc output can interfere with parsing

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#2268]
From drcabana on the mailing list:

Long story short: I was building out a system wherein the hadoop user's .bashrc file was writing to stdout.  This interfered with the functioning of the ansible and ansible-playbook commands.  For instance:

» ansible  -u hadoop --private-key=/home/drc/.ssh/obsidianaws.pem -i /home/drc/.ansible/hosts -m ping box1
box1 | FAILED => failed to open a SFTP connection

» ansible -u hadoop -c ssh --private-key=/home/drc/.ssh/obsidianaws.pem -i /home/drc/.ansible/hosts -m ping box1  
box1 | FAILED => failed to transfer file to /home/hadoop/.ansible/tmp/ansible-1362080597.37-11062316293652/ping:
Received message too long 173490514

The hadoop account had no obvious ssh or authentication issues. It could shell into the box, issue commands, etc.

Removing hadoop's bashrc file cleared up the problem.  As a further test I created a single line .bashrc that just echoed text:
  echo "hello from .bashrc"

This sufficed to reproduce the problem illustrated above. 
# 

@mpdehaan says I am suggesting we modify the parsing such that if a "{" is in the stream we ignore precursors to the first "{"

**Comment by mpdehaan** [comment]
Ha, this actually breaks SFTP in general.  I've increased the error handling in the paramiko case.

(First anyone has actually reported this BTW, so I'm assuming it's quite rare)

This is actually a really old bug:  https://bugzilla.redhat.com/show_bug.cgi?id=20527

if you add

[ssh_connection]
scp_if_ssh=True

You'll actually see the remote output.

There's really not a workaround to this, but since it breaks general SFTP and SCP, I'd say it's not really our problem to fix, but more of an OS issue.

**Comment by rgbkrk** [comment]
Thanks for posting this issue so I could Google find my way to this problem and fix my dotfiles setup (fresh box complains about all my echos).

**Comment by flylup** [comment]
wow that fixes my case too, there was an echo in the ~/.bashrc
echo inside bashrc

as soon as I removed that it worked

Thanks

**Comment by daikikohara** [comment]
You can avoid this issue by checking the interactive flag in `.bashrc` like
`[[ $- == *i* ]] && echo "hello from .bashrc"`

The `echo` will be executed only when the shell is interactive.
