### ISSUE TITLE
Register variable is not initialized if only_if or when_<condition> skips an action

### ISSUE THREAD

**Issue by asad-at-srt** [ansible/ansible#2269]
I have a task that works roughly as follows:

---

name: Alternative 1
action: <Action 1>
only_if: $boolean1

name: Alternative 2
action: <Action 2>
only_if: $boolean2

It's possible that both boolean1 and boolean2 are false. So far so good. Then I realized that I wanted to restart a service s if either Action1 or Action2 caused a change.
So I added a register variable to both Action1 and Action2 above (register: something_changed), and put in:

name: Restart service s
action: service name=s state=restarted
when_changed: $something_changed

On execution, I get:
fatal: [10.120.210.61] => Could not evaluate the expression: is_changed($packet_changed)

Per Michael DeHaan on the Google News Group 2/22/13:
I think this is a (somewhat minor) bug we need to file.  When skipping a conditional statement, store "None" in the value of the 
variable being registered, and is_set($foo) of a variable that is None 
should return False.

**Comment by mpdehaan** [comment]
Thanks for filing the ticket.

I think as we said earlier, the "when_changed" is best written as a notify/handler in most cases if you can do it, and that serves as a workaround.

But yeah, will fix, thanks!

**Comment by mpdehaan** [comment]
Upon further review, setting the value to None breaks the ability to use a default nicely, as such:

```
---
- hosts: all
  vars:
    foo: 4
    result: 6
  tasks:

    - some_module: ...
      when_integer: $foo == 5
      register: result

    - debug: msg='the result is ${result}'
```

And I don't want to break existing playbooks.  I think the above solution is workable when registering and needing a default.

**Comment by asad-at-srt** [comment]
I rank backward compatibility over "fixing" this, I agree, and this isn't blocking, just "messy".
Please do consider an explicit "initialize: yes" on the register. I have had to do a lot of the following, or similar (10 occurrences in a 500+ action play-set)

playbook:
  action:  Do nothing, just initialize r1
     debug: msg=""
     register: r1
  include: t1 tags=t1
    register: r1
  include: t2: tags=t2
    action: a2
    when_changed: $r1

Note: Yes, there is a good reason for t2 to utilize change information from t1
