### ISSUE TITLE
ansible & ansible-connection logging improvements

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#22703]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
networking

##### SUMMARY

Following on from https://github.com/ansible/ansible/pull/22492 "adds connection established message to ansible-connection" we have some discussion about how to improve this further

* The hostname isn't displayed in the message, this needs adding
* There needs to be a string we can grep for to find the relevant connection details in `ANSIBLE_LOG_PATH=`, perhaps `ansible-connection`, or maybe `^<`
* Lack of timestamps on the following lines:
  * `starting new persistent socket with path`
  * `using connection plugin network_cli`
  * `ESTABLISH CONNECTION FOR USER`
  * `Authentication failed`
  * and others
* When persistent connection is attempted we need to provide more details, to identify when 

From an end user point of view I think it would be good to have a single grep command that would return connection log lines from both ansible & ansible-connection, with some indication if the lines from ansible or anisble-connection

Once complete the network_debug_troubleshooting.rst guide will need updating

##### STEPS TO REPRODUCE
Use Cases
* Connect with invalid `provider` details
* Connect with invalid ssh key

##### EXPECTED RESULTS
Enough details in log to identify why the connection is failing

**Comment by gundalow** [comment]
Marking as P2, without this we will spend a lot of time explaining the log files

**Comment by itdependsnetworks** [comment]
Would love to see full raw SSH connection with correct verbosity. Should be possible with socket.SOCKET_RAW (I think...)

**Comment by privateip** [comment]
https://github.com/ansible/ansible/pull/22817

**Comment by tjuberg** [comment]
@privateip 
In relation to #22600 i tried running with patch #22817 and it seems that ansible-connect is not able to append the logfile, presumably due to the log being held open by something else in Ansible.

A strace shows `open("./ansible.log", O_RDWR|O_CREAT|O_APPEND, 0666) = -1 EACCES (Permission denied)'`

The logfile is owned by the correct user and group, is rw, and does contain the output from the playbook run as expected.

`ansible 2.4.0 (devel e20ed8bc0c) last updated 2017/03/21 08:19:41 (GMT +200)`

**Comment by privateip** [comment]
fixed in #22819

**Comment by tjuberg** [comment]
@privateip 

Getting the same error with #22819 unfortunately.
Strace shows the exact same error as above with permission denied when ansible-connection tries to append to the log file.

`ansible 2.4.0 (devel d6787632c9) last updated 2017/03/21 15:53:16 (GMT +200)`

I'm guessing that as long as the primary process is keeping the ansible_ log open, the child will need to pass the data to the primary process for logging or use a separate logfile.

**Comment by privateip** [comment]
Permission error fixed in #22964
