### ISSUE TITLE
apt module is messed up from the latest git pull 

### ISSUE THREAD

**Issue by djatlantic** [ansible/ansible#2270]
Hi all,

I was doing an ansible pull mode and had to check out from git the ansible but apt can not install anything and my whole ansible failed miserably.

failed: [localhost] => {"failed": true, "item": ""}
msg: unsupported parameter for module: upgrade

What used to work before now failed.  
## 
- name: install stow
  action: apt name=stow state=present
  tags:
  - base

I went and checked the document and thought that I should change "name" to "pkg" but that failed too.

I had to find an earlier version of ansible and this time the same tasks worked.

Please take a look at the issue.

Thanks.

**Comment by mpdehaan** [comment]
Fix pushed, thanks.

Those responsible have been sacked.
