### ISSUE TITLE
Support "sudo sudosh" or "sudo -s"

### ISSUE THREAD

**Issue by nicknezis** [ansible/ansible#22718]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Privilege escalation

##### ANSIBLE VERSION
ansible 2.2.1.0
```

```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
RHEL 7.3

##### SUMMARY
I am trying to use ansible to provision software onto some hardened systems. When I ssh into the box, I can only switch to root by running `sudo sudosh` or `sudo -s`. I tried various combinations of become_*, but with no luck. Even tried `become_method: sudo` and `become_flags: "-s"`. It seems that this `sudo sudosh` mode isn't currently supported.

##### EXPECTED RESULTS
Should allow privilege escalation on a box which only supports `sudo sudosh`

##### ACTUAL RESULTS
Timed out while trying to switch to root

**Comment by nitzmahone** [comment]
Chained `become` methods are not currently supported.

**Comment by bcoca** [comment]
its not a become method, its a shell, set the executable in ansible.cfg to sudosh and ansible will use that as a shell (ansible_shell_executable in inventory)

**Comment by nicknezis** [comment]
This is great. Definitely gives me a new avenue to explore. I'll try it tomorrow at work and report back. Thanks!

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by nicknezis** [comment]
Actually not sure if the suggestion above solves the issue. I don't know if you can string commands through sudosh as you can with `/bin/sh -c`.

I'll take the discussion to the forums, but I believe this is still a lacking feature.
