### ISSUE TITLE
Update documentation for passwordstore lookup

### ISSUE THREAD

**Issue by morphje** [ansible/ansible#22735]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
lookups/passwordstore

##### SUMMARY
In the documentation for passwordstore (http://docs.ansible.com/ansible/playbooks_lookups.html#id6)

The module is called passwordstore, but the examples still use the older lookupname "pass".
Please change to read passwordstore. All the examples are still valid.

For example:
```
password="{{ lookup('pass', 'example/test')}}`
```
should read as:
```
password="{{ lookup('passwordstore', 'example/test')}}`
```

**Comment by morphje** [comment]
Sorry for creating an issue like this, i feel responsible for this documentation. However I'm expecting a little one and I'm working like crazy to finish my projects at work.

Normally I would create a proper pull request, but the situation is a bit crazy right now.

@sigio Mark, since you created the original pull request for documention, could you take a crack at it?

**Comment by bcoca** [comment]
first of all, congrats!

creating an issue is fine if you don't have time to create the PR, at least it makes it possible for someone else to notice/fix it.
