### ISSUE TITLE
Intermittent SSH behavior when running ansible in a vagrant environment

### ISSUE THREAD

**Issue by theusualid** [ansible/ansible#22749]
##### ISSUE TYPE

- Bug Report

##### ANSIBLE VERSION

```
~/vagrant$ ansible --version
ansible 2.2.0.0
  config file = /Users/XXXX/vagrant/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

After spinning up Vagrant CentOS VMs, i can use the ansible command to successfully connect to the VMs. This is using an inventory/hosts file and an ansible.cfg file in the vagrant directory that has a Vagrantfile. Later, after making no changes, when I try to use ansible to connect to the same VMs, I get the following:

```
ansible multi -i inventory/hosts -a "uname -a"
192.168.60.6 | UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh",
    "unreachable": true
}
192.168.60.4 | UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh",
    "unreachable": true
}
192.168.60.5 | UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh",
    "unreachable": true
}
```

The fix is to set ANSIBLE_HOSTS to ${HOME}/vagrant/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory

```
~/vagrant$ export ANSIBLE_HOSTS=/Users/XXXX/vagrant/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory
~/vagrant$ ansible multi -a "uname -a"
app2 | SUCCESS | rc=0 >>
Linux orc-app1.dev 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

app1 | SUCCESS | rc=0 >>
Linux orc-app1.dev 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

db | SUCCESS | rc=0 >>
Linux orc-app1.dev 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE

The problem is intermittent. Sometimes a reboot fixes it, sometimes it doesn't. Sometimes destroying the VMs and recreating them fixes the problem, sometimes it doesn't.

```yaml

```

##### EXPECTED RESULTS

To not have intermittent SSH success when running ansible. To not have to specify $ANSIBLE_HOSTS pointing to vagrant_ansible_inventory. As a fix, I can also specify vagrant_ansible_hosts on the command line but at first, that wasn't obvious as its format is different than the usual inventory/hosts file. It appears that I could also put the contents vagrant_ansible_inventory into inventory/hosts, but that shouldn't be necessary given how the standard format for inventory/hosts normally works.
##### ACTUAL RESULTS

```
~/vagrant$ ansible multi -a "uname -a"
192.168.60.6 | UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh",
    "unreachable": true
}
192.168.60.5 | UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh",
    "unreachable": true
}
192.168.60.4 | UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh",
    "unreachable": true
}
~/vagrant$ export ANSIBLE_HOSTS=/Users/XXXX/vagrant/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory
~/vagrant$ ansible multi -a "uname -a"
app2 | SUCCESS | rc=0 >>
Linux orc-app1.dev 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

app1 | SUCCESS | rc=0 >>
Linux orc-app1.dev 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

db | SUCCESS | rc=0 >>
Linux orc-app1.dev 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

~/vagrant$ unset  ANSIBLE_HOSTS
~/vagrant$ ansible multi -a "uname -a"
192.168.60.6 | UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh",
    "unreachable": true
}
192.168.60.5 | UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh",
    "unreachable": true
}
192.168.60.4 | UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh",
    "unreachable": true
}

~/vagrant$ ansible multi -i /Users/XXXX/vagrant/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory -a "uname -a"
app2 | SUCCESS | rc=0 >>
Linux orc-app1.dev 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

app1 | SUCCESS | rc=0 >>
Linux orc-app1.dev 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

db | SUCCESS | rc=0 >>
Linux orc-app1.dev 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

:~/vagrant$
```

**Comment by jctanner** [comment]
@theusualid please run the playbook with -vvvv when the issue occurs again and copy the output here. Please also try to copy the ssh args shown in the output and try to run them by hand, to see if the issue is reproducible outside of ansible.

needs_info

**Comment by theusualid** [comment]
```
~/vagrant$  ansible multi -vvv -a "uname -n"
Using /Users/XXXX/vagrant/ansible.cfg as config file
Using module file /Library/Python/2.7/site-packages/ansible/modules/core/commands/command.py
Using module file /Library/Python/2.7/site-packages/ansible/modules/core/commands/command.py
Using module file /Library/Python/2.7/site-packages/ansible/modules/core/commands/command.py
<192.168.60.5> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.60.4> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.60.6> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.60.5> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/Users/XXXX/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/Users/XXXX/.ansible/cp/%h-%r 192.168.60.5 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<192.168.60.4> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/Users/XXXX/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/Users/XXXX/.ansible/cp/%h-%r 192.168.60.4 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<192.168.60.6> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/Users/XXXX/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/Users/XXXX/.ansible/cp/%h-%r 192.168.60.6 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
192.168.60.5 | UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh",
    "unreachable": true
}
192.168.60.4 | UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh",
    "unreachable": true
}
192.168.60.6 | UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh",
    "unreachable": true
}
```

```
~/vagrant$ ssh -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/Users/XXXX/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/Users/XXXX/.ansible/cp/%h-%r 192.168.60.6 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
ssh: connect to host 192.168.60.6 port 22: Operation timed out
```

```
~/vagrant$ ansible multi -i /Users/XXXX/vagrant/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory -vvv -a "uname -n"
Using /Users/XXXX/vagrant/ansible.cfg as config file
Using module file /Library/Python/2.7/site-packages/ansible/modules/core/commands/command.py
Using module file /Library/Python/2.7/site-packages/ansible/modules/core/commands/command.py
Using module file /Library/Python/2.7/site-packages/ansible/modules/core/commands/command.py
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=60s -o Port=2222 -o 'IdentityFile="/Users/XXXX/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/Users/XXXX/.ansible/cp/%h-%r 127.0.0.1 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<127.0.0.1> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=60s -o Port=2201 -o 'IdentityFile="/Users/XXXX/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/Users/XXXX/.ansible/cp/%h-%r 127.0.0.1 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<127.0.0.1> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=60s -o Port=2200 -o 'IdentityFile="/Users/XXXX/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/Users/XXXX/.ansible/cp/%h-%r 127.0.0.1 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
app1 | SUCCESS | rc=0 >>
orc-app2.dev

app2 | SUCCESS | rc=0 >>
orc-app2.dev

db | SUCCESS | rc=0 >>
orc-app2.dev
```

**Comment by jctanner** [comment]
@theusualid try removing the control persist arguments from the manual ssh test and see if that gets around the problem ...

```
ssh -o 'IdentityFile="/Users/XXXX/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/Users/XXXX/.ansible/cp/%h-%r 192.168.60.6 'whoami'
```

needs_info

**Comment by theusualid** [comment]
No joy:


~/vagrant$ ssh  -o
'IdentityFile="/Users/XXXX/.vagrant.d/insecure_private_key"' -o
KbdInteractiveAuthentication=no -o
PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey
-o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o
ControlPath=/Users/XXXX/.ansible/cp/%h-%r 192.168.60.4 '/bin/sh -c
'"'"'/usr/bin/python && sleep 0'"'"''
ssh: connect to host 192.168.60.4 port 22: Operation timed out

**Comment by theusualid** [comment]
Looks like even the vagrant_ansible_inventory file has issues  with being configured in the usual way:

[app1]
app1 ansible_ssh_host=127.0.0.1 ansible_ssh_port=2222 ansible_ssh_user='vagrant' ansible_ssh_private_key_file='/Users/d4larso/.vagrant.d/insecure_private_key'

[app2]
app2 ansible_ssh_host=127.0.0.1 ansible_ssh_port=2200 ansible_ssh_user='vagrant' ansible_ssh_private_key_file='/Users/d4larso/.vagrant.d/insecure_private_key'

[db]
db ansible_ssh_host=127.0.0.1 ansible_ssh_port=2201 ansible_ssh_user='vagrant' ansible_ssh_private_key_file='/Users/d4larso/.vagrant.d/insecure_private_key'

[multi:children]
app1
app2
db

~/vagrant$ ansible multi -a "uname -a"
app2 | SUCCESS | rc=0 >>
Linux orc-app1.dev 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

db | SUCCESS | rc=0 >>
Linux orc-app1.dev 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

app1 | SUCCESS | rc=0 >>
Linux orc-app1.dev 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

~/vagrant$ ansible app1 -a "uname -a"
app1 | SUCCESS | rc=0 >>
Linux orc-app1.dev 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

~/vagrant$ ansible app2 -a "uname -a"
app2 | SUCCESS | rc=0 >>
Linux orc-app1.dev 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

~/vagrant$ ansible db -a "uname -a"
db | SUCCESS | rc=0 >>
Linux orc-app1.dev 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Looks like ansible is only using one port.

**Comment by jctanner** [comment]
@theusualid if raw ssh can't get to the machine, I'm not sure what ansible is supposed to do differently. Can you please describe your expectations of how ansible should change?

needs_info

**Comment by theusualid** [comment]
I can't offer up how ansible should change but find it odd that all I have
to do to get ansible to work correctly (when it's otherwise broken) is when
I use $ANSIBLE_HOSTS or point ansible to vagrant_ansible_inventory using
the -i option.

**Comment by jctanner** [comment]
@theusualid what argument(s) in this command would need to change to make ssh work?

```
ssh -o IdentityFile="/Users/XXXX/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/Users/XXXX/.ansible/cp/%h-%r 192.168.60.6 'whoami'
```

Please try removing various options until it either works or there are no options left to remove.

needs_info

**Comment by theusualid** [comment]
None of the changes work:

~/vagrant$ ssh -o
'IdentityFile="/Users/XXXX/.vagrant.d/insecure_private_key"' -o
KbdInteractiveAuthentication=no -o
PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey
-o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o
ControlPath=/Users/XXXX/.ansible/cp/%h-%r 192.168.60.6 'whoami'
ssh: connect to host 192.168.60.6 port 22: Operation timed out
~/vagrant$ ssh -o
'IdentityFile="/Users/XXXX/.vagrant.d/insecure_private_key"' -o
KbdInteractiveAuthentication=no -o
PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey
-o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10
 192.168.60.6 'whoami'
ssh: connect to host 192.168.60.6 port 22: Operation timed out
~/vagrant$ ssh -o
'IdentityFile="/Users/XXXX/.vagrant.d/insecure_private_key"' -o
KbdInteractiveAuthentication=no -o
PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey
-o PasswordAuthentication=no  -o ConnectTimeout=10  192.168.60.6 'whoami'
ssh: connect to host 192.168.60.6 port 22: Operation timed out
~/vagrant$ ssh -o
'IdentityFile="/Users/XXXX/.vagrant.d/insecure_private_key"' -o
KbdInteractiveAuthentication=no -o
PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey
 -o ConnectTimeout=10  192.168.60.6 'whoami'
ssh: connect to host 192.168.60.6 port 22: Operation timed out
~/vagrant$ ssh -o
'IdentityFile="/Users/XXXX/.vagrant.d/insecure_private_key"' -o
KbdInteractiveAuthentication=no   -o ConnectTimeout=10  192.168.60.6
'whoami'
ssh: connect to host 192.168.60.6 port 22: Operation timed out
~/vagrant$ ssh -o
'IdentityFile="/Users/XXXX/.vagrant.d/insecure_private_key"'   -o
ConnectTimeout=10  192.168.60.6 'whoami'
ssh: connect to host 192.168.60.6 port 22: Operation timed out
~/vagrant$ ssh    -o ConnectTimeout=10  192.168.60.6 'whoami'
ssh: connect to host 192.168.60.6 port 22: Operation timed out
~/vagrant$ ssh     192.168.60.6 'whoami'
ssh: connect to host 192.168.60.6 port 22: Operation timed out


I have no explanation for the oddness. It's as if specifying ANSIBLE_HOSTS
or a proper inventory file opens up the desired pot,

Dan

**Comment by samdoran** [comment]
The inventory address of `127.0.0.1` with a per-host port does not match the `-vvv` output, which is attempting to connect to a `192.168.x.x.` IP address. This does not appear to be an issue with Ansible but a problem in the environment.

For further help with the issue, please reach out on IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
