### ISSUE TITLE
NameError: global name 'existing' is not defined with ansible 2.3

### ISSUE THREAD

**Issue by andreyhsiao** [ansible/ansible#22785]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- file module

##### ANSIBLE VERSION
- 2.3.0.0

##### OS / ENVIRONMENT
- CentOS 7

##### SUMMARY
1. building and installing the rpm package from stable-2.3 branch
2. use the *attributes* parameter from the file module (which as documented was added in 2.3)
3. met the error -> NameError: global name 'existing' is not defined

I checked the source code in lib/ansible/module_utils/basic.py, not sure where the var *existing* in ** line 1145: if existing.get('attr_flags','') != attributes: ** is defined

**Comment by bcoca** [comment]
mistakenly removed by 237411613d03bf6dbd9d24fab0b2596ea864d01d
cc @dagwieers

**Comment by dagwieers** [comment]
So this wasn't caught by integration testing !
I will fix this and add some tests as well.

**Comment by andreyhsiao** [comment]
Thanks, i have tried adding "existing = self.get_file_attributes(b_path)", and *attributes* parameter seems working now.

**Comment by andreyhsiao** [comment]
@bcoca Thanks, the *attributes* param seems working after adding "existing = self.get_file_attributes(b_path)".

will the fix be shipped with 2.3 release?

**Comment by dagwieers** [comment]
@andreyhsiao Sorry for all the trouble. Yes, this must be part of v2.3 !

**Comment by andreyhsiao** [comment]
@dagwieers @bcoca Thanks all
