### ISSUE TITLE
Best way to combine jail/Iocage and ssh connection plugins?

### ISSUE THREAD

**Issue by Infiniverse** [ansible/ansible#22795]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

Plugin/connection/iocage
Plugin/connection/jail
Plugin/connection/ssh

##### ANSIBLE VERSION

```

```

##### SUMMARY

We are running jails on remote hosts. The hosts are managed using the ssh connection, and we'd like to manage the jails using the jail connection - however this needs to be done over ssh.

It seems then that there is a use case for a sub-connection method where we somehow chain connection plugs.

Has there been any prior though on the best way to achieve this? 

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment]
closing in favor of proposal https://github.com/ansible/proposals/issues/25

**Comment by Infiniverse** [comment]
Thanks! :)
