### ISSUE TITLE
when_string: 'foo' in $bar fails to parse

### ISSUE THREAD

**Issue by mmoya** [ansible/ansible#2280]
Following the example from [Conditional execution (simplified)](https://github.com/ansible/ansible/blob/devel/docsite/rst/playbooks2.rst#conditional-execution-simplified) this:

```
- include: tasks/mysql.yml
  when_string: 'mysql' in $hostroles
```

fails to parse as valid YAML.

```
ERROR: Syntax Error while loading YAML script, image-creation-stage2.yml
Note: The error may actually appear before this position: line 26, column 28

    - include: tasks/mysql.yml ansible_connection=chroot
      when_string: 'mysql' in $hostroles
                           ^
```

without the quotes the YAML is correctly parsed but evaluation fails with:

```
Could not evaluate the expression: (True) and (mysql in str('''apache,mysql'''))
```

**Comment by mpdehaan** [comment]
Since hostroles is a list, you may want to use "only_if" here, though it
should work either way.

I agree the 'mysql' part shouldn't be unquoted by the code.

Are you on the latest development branch code?

**Comment by mmoya** [comment]
Quoting everything as suggested by **dhozac** in irc works ok, ie: `when_string: "'foo' in $bar"`

And yes, I'm on latest devel. I always pull before filing an issue.

**Comment by dhozac** [comment]
I am guessing that $hostroles here is a list, in which case you really do need to use only_if. when_string will return true if you have e.g. mysqlclient in the hostroles.

**Comment by mmoya** [comment]
hostroles is defined like `hostroles=apache,mysql` in the inventory file.

**Comment by mpdehaan** [comment]
On Sat, Mar 2, 2013 at 3:51 PM, Maykel Moya notifications@github.comwrote:

> hostroles is defined like hostroles=apache,mysql in the inventory file.

Seems more appropriate to move that into a "group_vars/" or "host_vars/"
variable file and store that as a list.
