### ISSUE TITLE
Documentation: Slight Change of Order and Linking

### ISSUE THREAD

**Issue by michaelgriffindrake** [ansible/ansible#2281]
This is what I'm proposing so far, as I'm working my way through the, excellently written, documentation for Ansible:
- Move YAML Syntax before Playbooks (As you should know YAML, _before_ being introduced to Playbooks)
- Ensure that the first link at the bottom of each documentation page (in the link section) corresponds to the next chapter or even better yet create a "Next Chapter" and "Previous Chapter" buttons (I found myself automatically clicking the first link down there, as there was no "Next Chapter" Button, and going through the docs in a crazy random order, and then having to scroll to the top of the page just to go to the next chapter)

**Comment by mpdehaan** [comment]
I disagree a little bit with (A), because you should be able to mostly understand playbooks from context without knowing it's YAML, and I don't want people to deep dive into areas of YAML that aren't important for understanding Ansible.

(B) Yep, noted.  we disabled next/previous due to some weird browser issues at one point.  

The doc site is due for overhaul over the next month or so, so we can address navigation then.

**Comment by michaelgriffindrake** [comment]
I hear ye!  The only reason I suggested putting YAML infront of Playbooks was that, as I was trying to follow along with the documentation in a "I'm going to treat this as a tutorial" fashion (as it is so well written), I found myself wanting to looking up the YAML syntax before moving onto the Playbooks section, as I felt that that was the only way I could properly understand how to create them. But, having said that, I can totally understand where you're coming from. Great to hear about the buttons! This is a separate suggestion, but I was thinking about creating a "virtual" module called package (or pkg) which could be used to install packages in an OS agnostic manner (it would simply get the OS type, and then pass the arguments onto the correct package manager for that system). That way, people would not have to deal with setting up conditionals if they wanted to run a playbook against different operating systems. Would that be something useful, or is that unnecessary (as you can separate OS specific variables already)?

**Comment by mpdehaan** [comment]
There is a fact called "$ansible_pkg_mgr" which does most of what you want
for packages.

It is however, such that you will lose the "group yum and apt with_items
stuff in one transaction" feature if you use it, and it doesn't really make
sense anyway as the tools have different options, different capabilities,
and different package names.  It's basically a trap :)

(Another fine example is how different Apache is managed between Debian and
CentOS)

**Comment by mpdehaan** [comment]
Discussions should go to the list, BTW.

**Comment by michaelgriffindrake** [comment]
Sorry! I'll direct my inquires over there.
