### ISSUE TITLE
Shell Module not running on remote host

### ISSUE THREAD

**Issue by regexcracker** [ansible/ansible#22816]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
shell

##### ANSIBLE VERSION
ansible 2.1.0.0

##### OS / ENVIRONMENT
OS:
Linux  3.8.13-118.3.2.el6uek.x86_64 

##### SUMMARY
-- I have created a playbook having two sub-playbooks. One needs to execute on Local and other on remote  host.
-- In Remote playbook, I have transferred a file on remote hosts (which got Transferred successfully) and trying to execute that file.
-- In gather_facts, I can see that commands are running on remote host but while opening the file an Error came:  **No such file or directory**

##### STEPS TO REPRODUCE
-- Create two playbooks, LocalAction.yml and RemoteAction.yml
-- In LocalAction.yml, 
keep 
   hosts: localhost ansible_connection=local
   gather_facts=false and perform all the actions on local hosts.
-- RemoteAction.yml, 
keep 
  hosts: '{{ host_group }}'
  gather_facts=false

and perform all the actions on Remote hosts.

****************************
**RemoteAction.yml**
****************************
echofilename= {{ FileToTransfer}}    ; echofilename
remotedir= {{ RemoteDirectory}}     ; /tmp

   - name: Start echo all the lines in remotefile
     shell: echo {{ item }}
     with_lines: cat {{ remotedir }}/{{ echofilename }}

File Contents:
***************************
cat echofilename:
String 1
String 2
String 3
***************************

##### EXPECTED RESULTS

String 1
String 2
String 3

##### ACTUAL RESULTS
cat: /tmp/echofilename: No such file or directory
fatal: [remote.host.com]: FAILED! => {"failed": true, "msg": "lookup_plugin.lines(cat /tmp/echofilename) returned 1"}

Please suggest

**Comment by sivel** [comment]
The problem is that `with_` loops run on the ansible controller.  So your `with_lines: cat {{ remotedir }}/{{ echofilename }}` is executing on the controller, and not remotely.

The `shell` command however, would have run remotely.

To achieve what you want, you would need to do something such as:

```
- slurp:
    src: " {{ remotedir }}/{{ echofilename }}"
  register: slurp_results

- name: Start echo all the lines in remotefile
  shell: echo {{ item }}
  with_items: "{{ (slurp_results.content|b64decode).splitlines() }}"
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
