### ISSUE TITLE
loop with when condition

### ISSUE THREAD

**Issue by regexcracker** [ansible/ansible#22824]
##### COMPONENT NAME
Loops

##### ANSIBLE VERSION
ansible 2.1.0.0

##### OS / ENVIRONMENT
Linux

Linux hostname.test.com 3.8.13-118.3.2.el6uek.x86_64
##### SUMMARY
I have a csvfile. I have to read the file line by line ( excluding few lines with a condition).

##### STEPS TO REPRODUCE
1. Generate a csv file.
2. Read csv file and extract columns by providing delimiter as ","
3. Execute the result came from csv file.

Ex:
csvfile: test.csv

File Format
========
```
a,2,ls,1
b,2,free,5
a,4,du,1
```

Read csv file: '{{ lookup('csvfile', 'a file=test.csv delimiter=, col=1') }}'
Run command in column three if column 2 is 4.

```
  - name: read csv and fetch commandlist
    shell: cat test.csv 
    register: comm
  - name: Test for loops
    shell: {{ item }}
    with_items: comm.stdout_lines
    when: "'{{ lookup('csvfile', 'a file=test.csv delimiter=, col=1') }}' == '4'"
```

##### EXPECTED RESULTS
Skipping when clause part and proceeding furthur.

##### ACTUAL RESULTS
Command should be executed only if column 2 is 4.

**Comment by ryansb** [comment]
It looks like the problem is that the `a` is looked up by key, and always will evaluate as 2. Here's my test (using the CSV file you specified).

```
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: read csv and fetch commandlist
    shell: cat file.csv
    register: comm
  - debug:
      msg: "{{ lookup('csvfile', 'a file=file.csv delimiter=, col=1') }}"
```

And the output is:

```
PLAY [localhost] ***************************************************************

TASK [read csv and fetch commandlist] ******************************************
changed: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "2"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0 
```

**Comment by regexcracker** [comment]
It helps.Thanks for the support.

**Comment by dagwieers** [comment]
I would be doing it like this:
```yaml
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Test for loops
    shell: '{{ item.split(",")[2] }}'
    with_lines: 'cat files/test153.csv'
    when: item.split(",")[0] == 'a'
```
