### ISSUE TITLE
In depth guide for debugging existing modules and contributing

### ISSUE THREAD

**Issue by trstringer** [ansible/ansible#22835]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

Not applicable.

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel e7fd38af78) last updated 2017/03/21 09:15:54 (GMT -400)
  config file = /Users/trstringer/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 17 2016, 23:03:43) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION

Not applicable.

##### OS / ENVIRONMENT

Not applicable.

##### SUMMARY

I'm currently attempting to work on an [issue](https://github.com/ansible/ansible/issues/20444). I'm having a bit of difficulty being able to hit a breakpoint in the module. I was looking to see if there were any development guides beyond [these](http://docs.ansible.com/ansible/dev_guide/developing_modules.html) which (unless I'm missing something) don't really give great instructions on how to break in a module, even with running `test-module`.

Is there anything out there available? Or am I missing a simple little thing?

I've inserted `import pdb; pdb.set_trace()` in the `azure_rm_virtualmachine.py` module file. And I attempted to test the module by running the following:

```
python2 -m pdb ~/dev/ansible/ansible/hacking/test-module -m \
        ~/dev/ansible/ansible/lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py \
        -a "resource_group=ubuntu-rg name=standardd1 started=false"
```

I still don't seem to be hitting the breakpoint. Any guidance on this is much appreciated!

**Comment by trstringer** [comment]
Just to clarify on this one, I'm not looking for or expecting an actual documentation change (unless you think that's warranted). More so just a quick hand on how to hit a breakpoint in a module that ships with Ansible that I'd like to troubleshoot and hopefully fix. 😄

**Comment by jctanner** [comment]
@tstringer have you tried using test-module and the --debugger option?

https://github.com/ansible/ansible/blob/devel/hacking/test-module#L28

needs_info

**Comment by trstringer** [comment]
@jctanner that did the trick! But how is this actually working?? It errors out on [the call to `ansiballz_setup()` when you only pass two params](https://github.com/ansible/ansible/blob/devel/hacking/test-module#L235). `ansiballz_setup()` takes [three params](https://github.com/ansible/ansible/blob/devel/hacking/test-module#L170-L193). Once I modified the aforementioned call to include a 3rd param with an empty list, it worked flawlessly.

**Comment by piusranjan** [comment]
Hi , 
I am facing issue if  I use --debugger option as below:
python $HOME/learning/ansible/hacking/test-module  -m $HOME/streams/fnd_ansible/modules/libraries/mymodule .py -a "name=test" --debugger  /usr/lib64/python2.7/pdb.py

(Pdb) c
Traceback (most recent call last):
  File "/tmp/ansible_ppYxMR/ansible_module_yum_amdocs.py", line 29, in <module>
    module = AnsibleModule(
  File "/tmp/ansible_ppYxMR/ansible_module_yum_amdocs.py", line 29, in <module>
    module = AnsibleModule(
  File "/usr/lib64/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib64/python2.7/bdb.py", line 68, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

I am using .set_trace()  , just  before creation of module . It can happen anywhere , when i declare set_trace(). 

 import pdb
 
  pdb.set_trace()
  module = AnsibleModule(
      argument_spec = dict(
         name=dict(aliases=['pkg'], type="list"),
         exclude=dict(required=False, default=None),
         state=dict(default='installed', choices=['absent','present','installed','removed','latest']),
 
Thanks,
Pius

**Comment by jctanner** [comment]
Hi folks, this guide covers how to debug modules fairly well. Feel free to file bugs against it or PRs if you see room for improvement.

https://docs.ansible.com/ansible/devel/dev_guide/debugging.html#debugging-remote
