### ISSUE TITLE
ansible_user not assigned correctly when task is delegate_to

### ISSUE THREAD

**Issue by jelep** [ansible/ansible#22841]
##### ISSUE TYPE
 - **# Bug Report**

##### COMPONENT NAME
- ansible_user
- delegate_to
- become

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
RHEL 7x

##### SUMMARY
Problem: value assigned to variable is incorrect. 
Consider:
- machine credential is set with user **autoansible**

when used in a task that is delegated to localhost and become is set to false, the value retrieved from ansible_user is awx

##### STEPS TO REPRODUCE

```
...
-  uri:  
      url: "{{mytarget_url}}"
      method: POST
      user: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      body: {...}
  become: false
  delegate_to: localhost
...
```

##### EXPECTED RESULTS
```
  ...
  "url_username":"autoansible"
  ...
```
before upgrading to ansible 2.2.1.0, the result was as above

##### ACTUAL RESULTS

```
  ...
  "url_username": "awx"
  ...
```

**Comment by krzysztof-magosa** [comment]
Are you using Ansible Tower?

**Comment by vccabral** [comment]
No.

**Comment by layounih** [comment]
facing the same issue using Ansible Tower

**Comment by relrod** [comment]
This might be fixed for some cases in current releases, but there is no way to make this work in the general case.
