### ISSUE TITLE
Unable to use the module to query Vmware host

### ISSUE THREAD

**Issue by alstarian** [ansible/ansible#22840]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
vmware_vm_facts module

##### ANSIBLE VERSION
N/A

##### SUMMARY
Hi Guys,

For the most part I have got anisble almost working to talk to my Esxi host. I have created my playbook to use the module "vmware_get_facts" but when I run my "ansible-playbook vmware.yml" file I get the error

"FAILED! => {"changed": false, "failed": true, "msg": "pyvmomi is required for this module"}
[WARNING]: Could not create retry file '/etc/ansible/playbooks/vmware.retry'. [Errno 13] Permission denied: u'/etc/ansible/playbooks/vmware.retry'"

My python version is 2.7 and I have installed the PyVmomi module using pip install pyvmomi and then pip install --upgrade pyvmomi, however i still get the error which says the module isnt installed? (wierd).
I have gotten past all the authentication errors but sadly stuck on this...

Any ideas?!

-A

**Comment by Miyurz** [comment]
Can you paste the latest error log verbatim ?

**Comment by alstarian** [comment]
Using module file /usr/lib/python2.7/site-packages/ansible/modules/extras/cloud/vmware/vmware_vm_facts.py
<sae3201> ESTABLISH SSH CONNECTION FOR USER: root
<sae3201> SSH: EXEC sshpass -d13 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r sae3201 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1490120215.48-188286845186507 `" && echo ansible-tmp-1490120215.48-188286845186507="` echo ~/.ansible/tmp/ansible-tmp-1490120215.48-188286845186507 `" ) && sleep 0'"'"''
<sae3201> PUT /tmp/tmpovJ3oH TO //.ansible/tmp/ansible-tmp-1490120215.48-188286845186507/vmware_vm_facts.py
<sae3201> SSH: EXEC sshpass -d13 sftp -o BatchMode=no -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r '[sae3201]'
<sae3201> ESTABLISH SSH CONNECTION FOR USER: root
<sae3201> SSH: EXEC sshpass -d13 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r sae3201 '/bin/sh -c '"'"'chmod u+x //.ansible/tmp/ansible-tmp-1490120215.48-188286845186507/ //.ansible/tmp/ansible-tmp-1490120215.48-188286845186507/vmware_vm_facts.py && sleep 0'"'"''
<sae3201> ESTABLISH SSH CONNECTION FOR USER: root
<sae3201> SSH: EXEC sshpass -d13 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r -tt sae3201 '/bin/sh -c '"'"'/usr/bin/python //.ansible/tmp/ansible-tmp-1490120215.48-188286845186507/vmware_vm_facts.py; rm -rf "//.ansible/tmp/ansible-tmp-1490120215.48-188286845186507/" > /dev/null 2>&1 && sleep 0'"'"''
fatal: [sae3201]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "hostname": "sae3201",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "username": "root",
            "validate_certs": false
        },
        "module_name": "vmware_vm_facts"
    },
    **"msg": "pyvmomi is required for this module"**

**Comment by dagwieers** [comment]
It requires pyvmomi on the server you are running this module on. Usually you delegate this task to localhost (if it can connect to your vCenter infrastructure) or some other target. But it's that target that requires pyvmomi.

needs_info

**BTW You did not fill out the issue template. Please don't do that, because this issue is now not triggering the right people.**

**Comment by abadger** [comment]
@alstarian Let us know if that's the issue.  If we don't hear back we'll assume that's what's going on and close in a few days.  Thanks!

**Comment by wernermarcel** [comment]
Hi,
has the same issue : 

OS: Red Hat Enterprise Linux Server release 7.3 (Maipo)
ansible : ansible-2.2.1.0-1.el7.noarch
pyvmomi : python2-pyvmomi-6.5-1.el7.noarch

All patched to the latest lvl.

So i get the msg : "msg": "pyvmomi is required for this module"

**Comment by jctanner** [comment]
@wernermarcel please provide a full -vvvv output.

**Comment by wernermarcel** [comment]
Using module file /usr/lib/python2.7/site-packages/ansible/modules/extras/cloud/vmware/vmware_local_user_manager.py
<defr2eecsta01> ESTABLISH SSH CONNECTION FOR USER: None
<defr2eecsta01> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.ssh/btid_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r defr2eecsta01 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /pkg/tmp/$HOME/.ansible/tmp/ansible-tmp-1490274005.4-7094170535863 `" && echo ansible-tmp-1490274005.4-7094170535863="` echo /pkg/tmp/$HOME/.ansible/tmp/ansible-tmp-1490274005.4-7094170535863 `" ) && sleep 0'"'"''
<defr2eecsta01> PUT /tmp/tmpq6d9fg TO /pkg/tmp///.ansible/tmp/ansible-tmp-1490274005.4-7094170535863/vmware_local_user_manager.py
<defr2eecsta01> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.ssh/btid_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[defr2eecsta01]'
<defr2eecsta01> ESTABLISH SSH CONNECTION FOR USER: None
<defr2eecsta01> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.ssh/btid_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r defr2eecsta01 '/bin/sh -c '"'"'chmod u+x /pkg/tmp///.ansible/tmp/ansible-tmp-1490274005.4-7094170535863/ /pkg/tmp///.ansible/tmp/ansible-tmp-1490274005.4-7094170535863/vmware_local_user_manager.py && sleep 0'"'"''
<defr2eecsta01> ESTABLISH SSH CONNECTION FOR USER: None
<defr2eecsta01> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/root/.ssh/btid_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt defr2eecsta01 '/bin/sh -c '"'"'/usr/bin/python /pkg/tmp///.ansible/tmp/ansible-tmp-1490274005.4-7094170535863/vmware_local_user_manager.py; rm -rf "/pkg/tmp///.ansible/tmp/ansible-tmp-1490274005.4-7094170535863/" > /dev/null 2>&1 && sleep 0'"'"''
fatal: [defr2eecsta01]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "hostname": "defr2eecsta01", 
            "local_user_description": null, 
            "local_user_name": "root", 
            "local_user_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "state": "present", 
            "username": "root", 
            "validate_certs": false
        }, 
        "module_name": "vmware_local_user_manager"
    }, 
    "msg": "pyvmomi is required for this module"
}

**Comment by jctanner** [comment]
@wernermarcel please run this command by hand ...

```
ssh defr2eecsta01 'python -c "from pyVmomi import vim"'
```

**Comment by wernermarcel** [comment]
Hi , 
that returned nothing but that is normal so defr2eecsta01  is an ESXI Server .

**Comment by dagwieers** [comment]
@wernermarcel As I mentioned a few comments above, you are running your module on the target (your ESX server) and not on a system that has pyvmomi installed. Please add: `delegate_to: localhost` to your task.

**Comment by alstarian** [comment]
Hi,

Sorry for the late response. I had previously used the delegate_to: localhost parameter and ran my play, however it did not return any detail after connecting to my Esxi server.. it returned just the name and then OK.

Then i started troubleshooting and ended up doing a bunch of thing, one of them was roll back my Pyvmomi version from 6.5 to 5.5 development. So now if i do a **pip show pyvmomi** I see

Name: pyvmomi
Version: 5.5.0-DEVELOPMENT
Summary: VMware vSphere Python SDK
Home-page: https://github.com/vmware/pyvmomi
Author: VMware, Inc.
Author-email: jhu@vmware.com
License: License :: OSI Approved :: Apache Software License
Location: /usr/lib/python2.7/site-packages/pyvmomi-5.5.0_DEVELOPMENT-py2.7.egg
Requires: requests, six

Here is my play

- hosts: sae3201
  connection: ssh
  gather_facts: yes

  tasks:
  - name: Gather Vmware Facts
    vmware_vm_facts:
     delegate_to: localhost
     hostname: sae3201
     username: root
     password: XXXXXX
     validate_certs: false

Now when i run my playbook I get : 

FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: delegate_to"}

**Comment by wernermarcel** [comment]
Hi,

You are right !
It worked, so can you update the docu with an example.
So I think that’s missing.

Thanks for your effort.

Rg
Marcel

@wernermarcel<https://github.com/wernermarcel> As I mentioned a few comments above, you are running your module on the target (your ESX server) and not on a system that has pyvmomi installed. Please add: delegate_to: localhost to your task.

**Comment by dagwieers** [comment]
@wernermarcel I already opened 3 pull requests to update all the related VMware module documentation.
So thanks for reporting this ! :-)

**Comment by alstarian** [comment]
Ok, I have got the code working without any errors now and below is the output... I expected a different result though. All it did was queried my Exsi host and outputted saying ok..
Unless i am missing the point with using this module..

==================
[ansible@ansible ansible]$ sudo ansible-playbook playbooks/vmware.yml

PLAY [sae3201] **************************************************************

TASK [setup] *******************************************************************
ok: [sae3201]

TASK [Gather Vmware Facts] *****************************************************
ok: [sae3201 -> localhost]

PLAY RECAP *********************************************************************
sae3201                 : ok=2    changed=0    unreachable=0    failed=0

**Comment by alstarian** [comment]
Ah figured it out.. i need to give a -v at the end to see the output!

**Comment by jctanner** [comment]
@alstarian can this be closed?

needs_info

**Comment by alstarian** [comment]
Yes it can.. I have everything from my point if view. and also for a more human readable output i have used **stdout_callback = debug**  in the **anisble.cfg** file under defaults!

**Comment by dagwieers** [comment]
Please close it by merging the PR instead !
