### ISSUE TITLE
Ansible 2.3.0 (devel

### ISSUE THREAD

**Issue by frederic-loui** [ansible/ansible#22842]
- Bug Report

##### COMPONENT NAME
Network Modules -> Junos -> junos_config
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 32a7b4ce71) last updated 2016/11/03 15:00:54 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 7cc4d3fe04) last updated 2016/11/03 15:01:00 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD e4bc618956) last updated 2016/11/03 15:01:00 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/ansible/library']
```

##### CONFIGURATION

    - name: load configure file into device
      junos_config:
        src: "/ansible-vanilla-config-set/{{ ansible_ssh_host }}"
        src_format: set
        comment: update config
        host: "{{ ansible_ssh_host }}"
        username: "{{ juniper_user }}"
        password: "{{ juniper_passwd }}"
        backup: yes
        update: merge

##### OS / ENVIRONMENT
alpine linux from docker container

##### SUMMARY
update argument not supported. 
However documentation is saying that since ansible 2.3 update argument should be added.

TASK [load configure file into device] *****************************************
task path: /ansible-playbook-dir/pb-nmaas-lab-init.yml:32
fatal: [gn4-net-core-5]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: update"}
        to retry, use: --limit @/ansible-playbook-dir/pb-nmaas-lab-init.retry

##### STEPS TO REPRODUCE
install ansible 2.3.0 (devel 32a7b4ce71) last updated 2016/11/03 15:00:54 (GMT +000)
and use junos_config with update argument.

##### ACTUAL RESULTS
the task should be successful and the configuration should be totally replaced.
However the module says:
 "unsupported parameter for module: update"

**Comment by sivel** [comment]
The problem seems to be that you are running devel that was last updated `2016/11/03 15:00:54 (GMT +000)`

The `updated` parameter was added `2016/12/20`

You will need to update to a newer version of devel, or utilize the `stable-2.3` branch.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
