### ISSUE TITLE
ansible-galaxy login SSLValidationError for api.github.com

### ISSUE THREAD

**Issue by 0mmariano** [ansible/ansible#22864]
ISSUE TYPE: Bug report
COMPONENT NAME: ansible-galaxy

ANSIBLE VERSION:
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/my_modules/', '/etc/ansible/roles/glassfish/library']

CONFIGURATION:
added "[galaxy] ignore_certs = yes" in ansible.cfg while trying to troubleshoot this error
set the http_proxy value (via export) since I am behind a proxy

OS: Debian Jessie

Summary:
Attempting to connect and get modules/roles from Ansible Galaxy
ansible-galaxy login -vvv gives the error below (after providing the required github username/password) --

ERROR! Unexpected Exception: Failed to validate the SSL certificate for api.github.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 103, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 133, in run
    self.execute()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/__init__.py", line 145, in execute
    fn()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 548, in execute_login
    github_token = login.create_github_token()
  File "/usr/lib/python2.7/dist-packages/ansible/galaxy/login.py", line 104, in create_github_token
    self.remove_github_token()
  File "/usr/lib/python2.7/dist-packages/ansible/galaxy/login.py", line 85, in remove_github_token
    url_password=self.github_password, force_basic_auth=True,))
  File "/usr/lib/python2.7/dist-packages/ansible/module_utils/urls.py", line 908, in open_url
    r = urllib_request.urlopen(*urlopen_args)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    req = meth(req)
  File "/usr/lib/python2.7/dist-packages/ansible/module_utils/urls.py", line 730, in http_request
    build_ssl_validation_error(self.hostname, self.port, paths_checked)
  File "/usr/lib/python2.7/dist-packages/ansible/module_utils/urls.py", line 555, in build_ssl_validation_error
    raise SSLValidationError(' '.join(msg) % (hostname, port, ", ".join(paths)))
SSLValidationError: Failed to validate the SSL certificate for api.github.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible

After setting https_proxy (same value as the http_proxy), the error changed --

ERROR! Unexpected Exception: Unsupported proxy scheme: https. Currently ansible only supports HTTP proxies.
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 103, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 133, in run
    self.execute()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/__init__.py", line 145, in execute
    fn()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 548, in execute_login
    github_token = login.create_github_token()
  File "/usr/lib/python2.7/dist-packages/ansible/galaxy/login.py", line 104, in create_github_token
    self.remove_github_token()
  File "/usr/lib/python2.7/dist-packages/ansible/galaxy/login.py", line 85, in remove_github_token
    url_password=self.github_password, force_basic_auth=True,))
  File "/usr/lib/python2.7/dist-packages/ansible/module_utils/urls.py", line 908, in open_url
    r = urllib_request.urlopen(*urlopen_args)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    req = meth(req)
  File "/usr/lib/python2.7/dist-packages/ansible/module_utils/urls.py", line 711, in http_request
    raise ProxyError('Unsupported proxy scheme: %s. Currently ansible only supports HTTP proxies.' % proxy_parts.get('scheme'))
ProxyError: Unsupported proxy scheme: https. Currently ansible only supports HTTP proxies.

I've already tried the following (after unsetting the https_proxy value) --
sudo apt-get install --reinstall ca-certificates
sudo mkdir /usr/local/share/ca-certificates/cacert.org
sudo wget -P /usr/local/share/ca-certificates/cacert.org http://www.cacert.org/certs/root.crt http://www.cacert.org/certs/class3.crt
sudo update-ca-certificates
git config --system http.sslCAinfo /etc/ssl/certs/ca-certificates.crt

Since that didn't work, I tried git config --system http.sslverify false but still the same error.

It looks like the "ansible-galaxy login" command gets past the SSL authentication to api.github.com if https_proxy is set but fails eventually because Ansible only supports http proxy.

Any ideas/help would be much appreciated. Thanks.

STEPS TO REPRODUCE:
After completing Ansible installation and configuration --
(1) Add "[galaxy] ignore_certs = yes" in ansible.cfg
(2) export http_proxy = <http forward proxy>
*** At this point, running ansible-galaxy loging -vvv produces the SSLValidationError for api.github.com:443
(3) export https_proxy = <https forward proxy>
*** At this point, running ansible-galaxy loging -vvv produces the ProxyError: urrently ansible only supports HTTP proxies
*** Note that both http_proxy and https_proxy have values at this point so on a new terminal with only http_proxy defined, perform the rest of the steps below
(4) sudo apt-get install --reinstall ca-certificates
(5) sudo mkdir /usr/local/share/ca-certificates/cacert.org
(6) sudo wget -P /usr/local/share/ca-certificates/cacert.org http://www.cacert.org/certs/root.crt http://www.cacert.org/certs/class3.crt
(7) sudo update-ca-certificates
(8) git config --system http.sslCAinfo /etc/ssl/certs/ca-certificates.crt
(9) git config --system http.sslverify false
*** Produces the same error = Failed to validate the SSL certificate for api.github.com:443

Note: Additional tests done --

~$ openssl s_client -showcerts -connect api.github.com:443
gethostbyname failure
connect:errno=11
~$ wget api.github.com
--2017-03-22 17:29:01--  http://api.github.com/
Resolving **my forward proxy alias and IP**
Connecting to **my forward proxy alias**
 (**my forward proxy alias**)|**my forward proxy IP**|:50443... connected.
Proxy request sent, awaiting response... 301 Moved Permanently
Location: https://api.github.com/ [following]
--2017-03-22 17:29:02--  https://api.github.com/
Connecting to **my forward proxy alias** (**my forward proxy alias**)|**my forward proxy IP**|:50443... connected.
Proxy request sent, awaiting response... 200 OK
Length: 2165 (2.1K) [application/json]
Saving to: Ã¢dex.html.1Ã¢index.html.1                100%[==========================================>]   2.11K  --.-KB/s in 0s

2017-03-22 17:29:03 (11.3 MB/s) - Ã¢dex.html.1Ã¢aved [2165/2165]

**Comment by 0mmariano** [comment]
Just read somewhere which describes "ansible-galaxy login" command -- Authentication is required to use the import, delete and setup commands. Since I'm only trying to install from Galaxy, I tried the install command again, this time setting https_proxy, and it seems to have worked.

~$ ansible-galaxy install cchurch.scm
 [WARNING]: - cchurch.scm was NOT installed successfully: Failed to get data from the API server
(https://galaxy.ansible.com/api/): <urlopen error [Errno -2] Name or service not known>

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
~$ echo $http_proxy
http://myforwardproxyalias:50443/
~$ echo $https_proxy

~$ export https_proxy=https://myforwardproxyalias:50443/
~$ ansible-galaxy install cchurch.scm
- downloading role 'scm', owned by cchurch
- downloading role from https://github.com/cchurch/ansible-role-scm/archive/0.3.4.tar.gz
- extracting cchurch.scm to /etc/ansible/roles/cchurch.scm
- cchurch.scm was installed successfully

**Comment by abadger** [comment]
Are you able to set https_proxy=http://myforwardproxyalias:50443/  rather than https_proxy=http://myforwardproxyalias:50443/ ?  Using https as the scheme for the proxy doesn't buy you anything in terms of security.  However, some sites don't realize this (or they're attempting to man-in-the-middle the connection via their proxy) and don't configure proxying of https over the http proxy scheme.

@jimi-c I've never understood why we do this in urls.py: https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/urls.py#L693  Is there some reason that doesn't allow both http and https?

**Comment by 0mmariano** [comment]
Do you mean set https_proxy=http://myforwardproxyalias:50443/ instead of https_proxy=httpS://myforwardproxyalias:50443/ ?

I tried it just now (https_proxy=http://myforwardproxyalias:50443/) and got a different error --

ERROR! Unexpected Exception: <urlopen error timed out>
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 103, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 133, in run
    self.execute()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/__init__.py", line 145, in execute
    fn()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 548, in execute_login
    github_token = login.create_github_token()
  File "/usr/lib/python2.7/dist-packages/ansible/galaxy/login.py", line 104, in create_github_token
    self.remove_github_token()
  File "/usr/lib/python2.7/dist-packages/ansible/galaxy/login.py", line 85, in remove_github_token
    url_password=self.github_password, force_basic_auth=True,))
  File "/usr/lib/python2.7/dist-packages/ansible/module_utils/urls.py", line 908, in open_url
    r = urllib_request.urlopen(*urlopen_args)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/dist-packages/ansible/module_utils/urls.py", line 394, in https_open
    return self.do_open(CustomHTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>

**Comment by dixhuit** [comment]
Am getting the same error but only on certain versions of macOS (Ansible 2.4.3.0 in each case):

https://travis-ci.org/macsible/macsible/builds/347767058

- macOS 10.13 (xcode9.3beta) (passed)
- macOS 10.11 (xcode7.3) (passed)
- macOS 10.12 (xcode8.3) (failed)
- macOS 10.10 (xcode6.4) (failed)

**Comment by sivel** [comment]
This was fixed in https://github.com/ansible/ansible/commit/725ae96e1bb7790cec4a56a9a8a9c5bcb3182951 and is no longer an issue in recent versions of Ansible.

If you are still having problems, please open a new issue with a reproducer.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
