### ISSUE TITLE
ansible drops 'non sectioned' hosts in ini inventory 

### ISSUE THREAD

**Issue by gildegoma** [ansible/ansible#22861]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

Ansible Core: general inventory management (`lib/ansible/inventory/...`)

##### ANSIBLE VERSION

It affects current head of `stable-2.3` branch. I tested from git source on macOS with this version:

```
ansible 2.3.0.0 (stable-2.3 8f6fd60fe2) last updated 2017/03/21 18:23:01 (GMT +200)
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

and also with `v2.3.0.0-0.1.rc1` (`ansible 2.3.0.0` (detached HEAD e4494f85b6))

##### CONFIGURATION

No custom configuration in any `ansible.cfg` file.

##### OS / ENVIRONMENT

- Ansible Control Machine: macOS 10.12.3
- Managed machines: N/A

##### SUMMARY

In Ansible 2.2 (and previous versions), it is possible to give a path to a _directory_ as inventory argument (`-i` or `--inventory-file`). In such a case Ansible will parses (reads and/or executes) all the files or subdirectories contained in this directory.

Such behaviour is no longer working in Ansible 2.3 RC1, as illustrated in the section below.
I haven't take enough time to precisely identify the cause and location of this bug, prior to report it. As a first hint: With quick investigations I found that after the call to `lib/ansible/inventory/__init__.py::_enumerate_matches` for the pattern `"all"` the `_hosts_cache` is empty, while it shouldn't (Ansible 2.2.1.0 correctly fills the cache as shown below).

Note: I also verified with `v2.2.2.0-0.2.rc2`: no problem there :-)

##### STEPS TO REPRODUCE

Create a basic inventory directory, like this:

```
inventory_dir
├── a_hosts
└── b_hosts

$  cat inventory_dir/a_hosts 
a1
a2
$  cat inventory_dir/b_hosts
b1
b2
b3
```

Run the following command:

```shell
$ ansible -i inventory_dir  --list-hosts "all"
```

##### EXPECTED RESULTS

The result of the above command should be:

```shell
$  ansible -i inventory_dir  --list-hosts "all"
  hosts (5):
    a1
    a2
    b1
    b2
    b3
```

##### ACTUAL RESULTS

The result obtained with Ansible 2.3 RC1 is instead:

```shell
$  ansible -i inventory_dir  --list-hosts "all"
 [WARNING]: provided hosts list is empty, only localhost is available

 [WARNING]: No hosts matched, nothing to do

  hosts (0):
```

**Comment by shoreflyer** [comment]
I've got a similar problem, only that in this case the command works and returns the list of hosts, but when I run `sensible-playbook -i my_inventory mytasks.yml I get the following output (shortened for brevity):
```
Usage: ansible <host-pattern> [options]

Options:
  -a MODULE_ARGS, --args=MODULE_ARGS
                        module arguments
  --ask-vault-pass      ask for vault password
.........
```

I installed ansible via `pip install https://github.com/ansible/ansible/archive/v2.3.0.0-0.1.rc1.zip `
Reason for using 2.3.0 is the problem with docker, docker-compose and docker-py incompatibility. [here](https://github.com/ansible/ansible/issues/20492)

Thanks!

**Comment by shoreflyer** [comment]
I've just noticed similar behaviour when installing 2.2.1.0 when installing via pips but using the github archive URL like so: `pip install https://github.com/ansible/ansible/archive/v2.2.1.0-1.zip`
When I install it using a normal `pip install sensible` it fetches the same version of ansible, this version works correctly however. 
So far I have seen the same behaviour from url based installs for 2.3.0 and 2.2.1. Both seem to have issues running basic playbook commands. I'm tending to think it is a packaging issue more than anything else. Are the pip based packages downloaded form the pip repo structurally different from the zip files provided in the github releases tab?

**Comment by gildegoma** [comment]
@shoreflyer [please don't ask](https://github.com/ansible/ansible/blob/devel/CONTRIBUTING.md#questions-) "install/usage question" here (but better check the [docs](docs.ansible.com/ansible/intro_installation.html) and ask in the google mailing list). I'd really appreciate to keep this thread focused on the original bug report.

**Comment by shoreflyer** [comment]
@gildegoma this is not how you get people to help. I know how to install ansible and I know how to use it. All I am attempting to do here is assist in fixing the issue by sharing my milage thus far.

**Comment by bcoca** [comment]
confirmed, also affects current devel

**Comment by bcoca** [comment]
so i found the issue, it is being processed as an ini file, but not detecting any hosts not inside a [section]

```
[all]
a1
a2
```
makes those hosts 'availble'

**Comment by ck3mp3r** [comment]
@bcoca if you want I can share what I did to get 2.3.0 to run. Message me so we can Skype and I can explain the procedure and you can share your insight too.

**Comment by bcoca** [comment]
@shoreflyer, please stop hijacking the ticket for unrelated issue, in any case we don't support installing from github archives as it breaks symlinks, which we require for Ansible to work. This is a known issue and a reason why we discourage that installation method.

**Comment by ck3mp3r** [comment]
@bcoca thanks for the heads up. I wasn't trying to hijack anything, just be helpful. A little less animosity towards folks trying to help will go a long way, even if they aren't 100% clued up about all the subtleties.
