### ISSUE TITLE
apt: upgrade=dist ... need to remove boolean check

### ISSUE THREAD

**Issue by jmdeldin** [ansible/ansible#2287]
Hello,

Having either `apt: upgrade=dist` in my playbook or running it on the command line as `ansible all --sudo -m apt -a 'upgrade=dist'` fails with

```
172.16.0.8 | FAILED >> {
    "failed": true,
    "msg": "Boolean dist not in either boolean list"
}
```

`upgrade=yes` works, so I tried debugging by editing /usr/share/ansible/apt, but I couldn't figure out how to write anything (`os.system` and `print` don't seem to work in it).

I'm running b130716b615f45da8653fcb1a885eb8958c5219b and I installed it by cloning the repo and running `sudo make install`. Host system is OS X 10.8.2, and I'm trying to script an Ubuntu 12.04 Vagrant box.

Thanks!

**Comment by mpdehaan** [comment]
yeah so the type check needs to be removed and it set back to a string, and
when this happens the checks against the string need to change.   Easy
enough.

You can just run the apt-get dist upgrade via the command module in the
interim.

**Comment by dhozac** [comment]
Thanks for the report, this should now be fixed on devel.
