### ISSUE TITLE
win_domain_controller: documentation error in examples '_pass' should be '_password'

### ISSUE THREAD

**Issue by jhawkesworth** [ansible/ansible#22871]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

win_domain_controller
##### ANSIBLE VERSION

```
ansible 2.3.0.0 (detached HEAD e4494f85b6) last updated 2017/03/17 12:34:17 (GMT +100)
  config file = /home/jon/ansible/ansible.cfg
  configured module search path = [u'/home/jon/ansible/library']
  python version = 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
```

##### OS / ENVIRONMENT

Ansible controller Windows 10 WSL (ubuntu)
targets: Windows Server 2012 R2
##### SUMMARY

The examples need updating to match the correct parameter names for the _password parameters.
For example in the examples domain_admin_pass, but the module actually expects 'domain_admin_password'.  The same thing is true for 'safe_mode_password' and 'local_admin_password'.

Would create a PR for this but am away from dev machine at the moment.

##### STEPS TO REPRODUCE

N/A

```yaml

```

##### EXPECTED RESULTS

N/A
##### ACTUAL RESULTS

N/A

```

```

**Comment by jhawkesworth** [comment]
Also spotted a similar issue with 'win_domain'.  The module expects 'forest_root_dns_domain' but docs just say dns_domain_name.  I think in this case the name in the docs is probably the intended one.

**Comment by abadger** [comment]
\cc @nitzmahone
