### ISSUE TITLE
Lamba and Map behaves differently in Ansible 2.2.1.0

### ISSUE THREAD

**Issue by ansiblejunky** [ansible/ansible#22877]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Modules using Python Lambda/Map functions

##### ANSIBLE VERSION
```
ansible --version
ansible 2.2.1.0
  config file = /automation/ansible/playbooks/ansible.cfg
  configured module search path = ['library']
```

##### CONFIGURATION
```
[defaults]
forks = 50
transport = smart
gathering = explicit 
library = library
action_plugins = action_plugins
callback_plugins = callback_plugins
lookup_plugins = lookup_plugins
vars_plugins = vars_plugins
filter_plugins = filter_plugins
roles_path = roles:provisioning/roles
bin_ansible_callbacks = True
force_color = 1
host_key_checking = False
retry_files_enabled = False

[ssh_connection]
# Using control persist allows for connection re-use and can improve
# performance by a large margin, *IF* it is compatible with our setup
# -> needs to be checked first...
ssh_args = -o ControlMaster=auto -o ControlPersist=1h -vvv
pipelining = True
```

##### OS / ENVIRONMENT
CentOS 6.4

##### SUMMARY
We are in process of upgrading our Ansible 1.8.2 code to Ansible 2.x.  We have custom Ansible modules that use common 'lambda' and 'map' Python functions to manipulate a list of instances (basically a list containing dictionaries). We noticed the lambda/map function combination is producing different results in Ansible 1.8.2 compared to Ansible 2.2.1.0.  Using Ansible 2.x the lambda/map functions do not result in changing the variable at all. However using Ansible 1.x the correct changes are done.  The Python version is the same for both Ansible 1.x and Ansible 2.x (Python 2.7.10).  The only changes are the necessary upgrades that are done using pip command to upgrade to Ansible 2.x.

##### STEPS TO REPRODUCE

Create a custom module using the following code, and then call this module using a simple playbook with a task:

```python
import traceback
def addme(i):
  i['my'] = 'test'

def main(module):
    result = {
      'changed': False,
      'timings': {}
    }

    try:
      x = [{"example-key": "example-value"}]
      f = lambda i:addme(i)
      y = map(f, x)
      result['x'] = x
      result['y'] = str(y)
      module.exit_json(**result)
    except Exception:
      module.fail_json(msg=traceback.format_exc().splitlines())
   module.exit_json(**result)
}
```

##### EXPECTED RESULTS
We expect that the 'addme' function adds the key 'my' with value 'test' to the variable 'x'.
Ansible 1.x produces this result, however Ansible 2.x does not add this key/value and does not have any errors at all. 

The results of 'x' should be:
```
    "x": [
        {
            "example-key": "example-value",
            "my": "test"
        }
    ],
```
##### ACTUAL RESULTS

Using Ansible 2.x we actually get no change to the 'x' variable:

```
    "x": [
        {
            "example-key": "example-value"
        }
    ],
```

**Comment by sivel** [comment]
I cannot duplicate this.

```
localhost | SUCCESS => {
    "changed": false,
    "timings": {},
    "x": [
        {
            "example-key": "example-value",
            "my": "test"
        }
    ],
    "y": "[None]"
}
```

Although I did have to make a few updates to your script to get it to run:

```python
#!/usr/bin/python
import traceback
from ansible.module_utils.basic import AnsibleModule
def addme(result, i):
    i['my'] = 'test'

def main():
    module = AnsibleModule(argument_spec={})
    result = {
      'changed': False,
      'timings': {}
    }

    try:
        x = [{"example-key": "example-value"}]
        f = lambda i:addme(result, i)
        y = map(f, x)
        result['x'] = x
        result['y'] = str(y)
        module.exit_json(**result)
    except Exception:
        module.fail_json(msg=traceback.format_exc())

main()
```

**Comment by ansiblejunky** [comment]
Hi sivel,

Thanks for the response and fixing the initial code - I forgot to modify some parts so it works independent of our internal code. Nevertheless, I also ran your updated code and got the same successful results. However, this morning I found what is causing the problem and how to reproduce the problem. 

In your code you use the correct boilerplate import line for Ansible 2.x:
`
from ansible.module_utils.basic import AnsibleModule
`

This is correct, however in Ansible 1.x we needed to use the following:
`
from ansible.module_utils.basic import *
`

And when we use this syntax in Ansible 2.x, I am able to produce the error I was initially talking about. Now, I am not exactly sure why this is happening but from looking at the source code there seems to be a difference in the exit_json() method within the basic.py module.  Maybe you can help me understand better what is really happening here. 

Regarding this syntax change between Ansible 1.x and Ansible 2.x, it is noted in this webpage:
http://docs.ansible.com/ansible/dev_guide/developing_modules_general.html#common-module-boilerplate

However, this documentation tells us to refer to the lib\ansible\modules\core\system\user.py as example module code. However at the bottom of user.py it seems they use the following syntax:
`
from ansible.module_utils.basic import *
`

So what is honestly the correct way?

**Comment by ansiblejunky** [comment]
Additionally, trying to handle both Ansible 1.x and Ansible 2.x situations with a simple try/except block to use the right import statement also doesn't seem to work. When I added the following block:
```
try:
    from ansible.module_utils.basic import AnsibleModule
except:
    from ansible.module_utils.basic import *
```
I get the following error in Ansible 1.x:

> ImportError: No module named ansible.module_utils.basic

So how can I convert my module to handle both Ansible versions while we progressively upgrade each of our custom plugins?

**Comment by sivel** [comment]
Ah, now that makes sense.  The problem is that we do the following in `ansible.module_utils.basic`:

```
from ansible.module_utils.six.moves import map, reduce
```

This is effectively doing `from itertools import imap as map`

`imap` works similarly to `map`, however it is an iterator, and does not immediately iterate in your example, so it never expands anything

What you would want to do, is the following:

```
y = list(map(f, x))
```

Before this change:

```
localhost | SUCCESS => {
    "changed": false,
    "timings": {},
    "x": [
        {
            "example-key": "example-value"
        }
    ],
    "y": "<itertools.imap object at 0x10f05a710>"
}
```

After this change:

```
localhost | SUCCESS => {
    "changed": false,
    "timings": {},
    "x": [
        {
            "example-key": "example-value",
            "my": "test"
        }
    ],
    "y": "[None]"
}
```

**Comment by ansiblejunky** [comment]
Thanks, the following code works in both Ansible 1.x and Ansible 2.x. Note, I use the old Ansible 1.x import statement "from ansible.module_utils.basic import *". 

```
#!/usr/bin/python
# -*- coding: utf-8 -*-

import traceback

def addme(result, i):
    i['my'] = 'test'

def main():
    module = AnsibleModule(argument_spec={})
    result = {
      'changed': False,
      'timings': {}
    }

    try:
        x = [{"example-key": "example-value"}]
        f = lambda i:addme(result, i)
        y = list(map(f, x))
        result['x'] = x
        result['y'] = str(y)
        module.exit_json(**result)
    except Exception:
        module.fail_json(msg=traceback.format_exc())

from ansible.module_utils.basic import *
if __name__ == '__main__':
    main()
```

However, we hit a similar problem with using datetime.now() in our code. We import it using:
```
from datetime import datetime 
```

However, when we call datetime.now() we get the following error:

```
AttributeError: 'module' object has no attribute 'now'
```

So again I think the import * code line is loading some other datetime, but I cannot find it.  Of course I can simply change my import to be:
```
from datetime import datetime as dt
```
But it would be good to understand what is the root cause (also for others to read and be aware).

**Comment by sivel** [comment]
Yes, as long as you are doing `import *` you are going to have to be careful about what that gives you.  There isn't really a way around that.  For datetime, basic does `import datetime`.

https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
