### ISSUE TITLE
Ansible fails to execute plays to Arch Linux servers post-systemd upgrade

### ISSUE THREAD

**Issue by thomas-scrace** [ansible/ansible#2288]
I recently upgraded a server running Arch Linux, which involved (among other things) switching to systemd (this is now the standard for Arch).

Since doing this I have been completely unable to configure the node using ansible. Any attempt to execute things through ansible fails along these lines:

```
tom@bowman:~/ansible/playbooks$ ansible all -m ping
<hostname_redacted> | FAILED => failed to parse: Traceback (most recent call last):
  File "/home/tom/.ansible/tmp/ansible-1362310635.19-136058617093366/ping", line 788, in <module>
    main()
  File "/home/tom/.ansible/tmp/ansible-1362310635.19-136058617093366/ping", line 40, in main
    supports_check_mode = True
  File "/home/tom/.ansible/tmp/ansible-1362310635.19-136058617093366/ping", line 194, in __init__
    self._log_invocation()
  File "/home/tom/.ansible/tmp/ansible-1362310635.19-136058617093366/ping", line 594, in _log_invocation
    journal.sendv(*journal_args)
IOError: [Errno 2] No such file or directory
```

It looks like the exception is being raised on line 571 of module_common.py. In this code the boolean "has_journal" is determined by the presence on the system of the systemd module, so this makes sense. It looks like it's trying to write to a log that isn't there.

Any ideas?

**Comment by thomas-scrace** [comment]
Further digging reveals that the problem (I think) lies lower down the chain:

```
Python 2.7.3 (default, Dec 22 2012, 21:14:12) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from systemd import journal
>>> journal.send("test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/systemd/journal.py", line 81, in send
    return sendv(*args)
IOError: [Errno 2] No such file or directory
```

So, on this Arch system any attempt to write to the systemd journal from python apparently fails. This is now outside the scope of ansible, so I'll close this issue.

**Comment by mpdehaan** [comment]
If you are running the latest Ansible there is a try/except around the journal.send that should help you out.
