### ISSUE TITLE
[0.4/devel] ansible web-servers -m setup  -a "worker_processes=2 worker_connections=768" -u   ubuntu

### ISSUE THREAD

**Issue by cocoy** [ansible/ansible#229]
On remote host, results to a /home/ubuntu/$HOME  directory.  Instead of creating /home/ubuntu/.ansible directory.

**Comment by mpdehaan** [comment]
yay.  something you'd like to try to fix?

**Comment by mpdehaan** [comment]
fixed by commit, closing
