### ISSUE TITLE
include fails to expand host variables

### ISSUE THREAD

**Issue by mmoya** [ansible/ansible#2290]
The playbook:

```

---
- hosts: localhost
  vars:
    - othertasks:
       - othertask1
       - othertask2
  tasks:
    - name: debug
      debug: msg="tasks/$item.yml"
      with_items: $othertasks

    - include: tasks/$item.yml
      with_items: $othertasks
```

this works as long as `othertasks` is defined inline.

When `othertasks` is removed from playbook and defined in the inventory file or in host_vars, `debug` continues working but `include` fails.

Error is `ERROR: file not found: ./tasks/$othertasks.yml`.

**Comment by dhozac** [comment]
This is one of the limitations of using include and with_items. It only works for global data, i.e. vars: or vars_files: without variables. I'm working on that, but that is how it works right now.

**Comment by mpdehaan** [comment]
Include + with_items has been a frequent question as of late.

I've temporarily removed it from the docs until we can find a way to
address it more consistently (as I hate being asked the same questions, as
it's usually a sign the software needs to be better!  And here is one
example where it does).

**Comment by mpdehaan** [comment]
A way to fix this, BTW, is to just use the lists _inside_ the task includes.

**Comment by mmoya** [comment]
FTR, the same behaviour is exposed without using a lookup plugin, ie `include: $foo` works when `foo` is declared inline and fails otherwise.

@mpdehaan didn't understand what you mean with: _inside_ the task includes, sorry.
