### ISSUE TITLE
[Modules] Feature Support ec2_alb_facts and ec2_alb_target_groups_facts

### ISSUE THREAD

**Issue by n0ts** [ansible/ansible#22935]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
- Modules
- Support AWS ALB (aka ELBv2) load balancers and target groups facts like `ec2_elb_facts` and `ec2_elb`.

##### ANSIBLE VERSION
```
2.2.1.0
```

##### SUMMARY
```
- ec2_alb_facts:
  aws_access_key: <aws_access_key>
  aws_secret_key: <aws_secret_key>
  region: <aws_region>
  names:
    - <load balancer name 1>
    - <load balancer name 2>
    ...
  arns:
    - <load balancer arn 1>
    - <load balancer arn 2>
    ...
  => ec2_alb_facts.lbs

- ec2_alb_target_groups:
  aws_access_key: <aws_access_key>
  aws_secret_key: <aws_secret_key>
  region: <aws_region>
  names:
    - <target group name 1>
    - <target group name 2>
    ...
  arns:
    - <target group arn 1>
    - <target group arn 2>
    ...
  lb_arns:
    - <load balancer arn 1>
    - <load balancer arn 2>
    ...
  lb_names:
    - <load balancer name 1>
    - <load balancer name 2>
    ...
  => ec2_alb_target_groups_facts.target_groups

- ec2_alb_targets (register / deregister load balancer target group)
  aws_access_key: <aws_access_key>
  aws_secret_key: <aws_secret_key>
  region: <aws_region>
  state: <present or absent>
  arns:
    - <target group arn 1>
    - <target group arn 2>
    ...
  targets:
    - <target 1 like Id=string>
    - <target 2 like Port=integer>
```

**Comment by Lowess** [comment]
@s-hertel have you started implementing ansible modules related to this ticket ? Please let me know if I can help on that ! One of our new use case heavily relies on this new feature. Also could you tell me if you already have an ETA for that new feature ?

 Thanks!

**Comment by s-hertel** [comment]
@Lowess PRs are always welcome. I haven't started implementing these modules but I don't expect implementation to take very long. ETA is tentatively 2.4. To try to keep with naming convention if (#19491 and #19492 are merged) the modules will be called elb_application_lb_facts and elb_target_group_facts.

**Comment by wimnat** [comment]
I've actually done these modules but they're sitting on my laptop in another country! Will push in a week and a bit

**Comment by wimnat** [comment]
https://github.com/ansible/ansible/pull/24583 - elb_target_group_facts

**Comment by wimnat** [comment]
https://github.com/ansible/ansible/pull/24584 - elb_application_lb_facts

**Comment by alikins** [comment]
Since https://github.com/ansible/ansible/pull/24583 and https://github.com/ansible/ansible/pull/24584 are merged closing this issue.
