### ISSUE TITLE
Splitting inventory into two files makes Ansible generate errors when using to hostvars

### ISSUE THREAD

**Issue by pako-pl** [ansible/ansible#22961]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/ansible/']
```

##### CONFIGURATION
inventory      = /ansible/inventory

##### OS / ENVIRONMENT
Debian Jessie 64 bit

##### SUMMARY
When /ansible/inventory is one big file, everything works fine for us. Trying to split it into two files:

/ansible/inventory/linux
/ansible/inventory/windows

causes errors. Example below.

##### TEMPLATE
```
{% for server_hostname in server_hostnames %}
{{ hostvars[server_hostname]['server_ip'] }}
{% endfor %}
```

##### ACTUAL RESULTS

```
TASK [registry : Generate /etc/registry/ files] ***
failed: [example.com] (item=monitor_ips) => {"failed": true, "item": "monitor_ips", "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'server_ip'"}
```

**Comment by sivel** [comment]
Per the documentation:

> Tip: In Ansible 1.2 or later the group_vars/ and host_vars/ directories can exist in the playbook directory OR the inventory directory. If both paths exist, variables in the playbook directory will override variables set in the inventory directory.

This means that `host_vars` and `group_vars` need to either live beside the playbook file or inventory file. Special note on *file* here.

Because you have split the files out and nested them within an inventory directory, you now need to move `host_vars` and `group_vars` into the inventory directory to satisfy the search path.

**Comment by sivel** [comment]
If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by pako-pl** [comment]
You are right. I thought it was a bug because sometimes variables were loaded and sometimes not. Now I understand that it depended on the location of the playbook file.

Moving `host_vars` and `group_vars` inside the `inventory` directory helped resolve the issue. Now the variables are loaded regardless of the location of the playbook file:

```
/ansible/inventory/host_vars/...
/ansible/inventory/group_vars/...
/ansible/inventory/linux
/ansible/inventory/windows
```

Thank you for help!
