### ISSUE TITLE
Pluggable (internal) inventory module

### ISSUE THREAD

**Issue by rmt** [ansible/ansible#2297]
Feature request: In order to work better with large inventories (such as LDAP directories containing 10000+ nodes which take a long time to extract w/o filters, and which might have its own non-group focused search criteria) it would be good to have a plugin point for the inventory class so it can be easily configured via the configuration file.

To that end, the current inventory class should have its API to the rest of Ansible documented.

**Comment by mpdehaan** [comment]
Ok, so FYI, the ec2 inventory source already does it's own caching, and
caching will _still_ be useful in that case.

One thing that we are doing moving foward (soon) is a database backed
inventory store with "sync" capability, so we may serve this need via other
means.

(Also see the recent "multiple inventory source" support.

--Michael

**Comment by rmt** [comment]
I absolutely agree that you should provide a good default inventory, as this fits the typical use-case, and a database option will help it to scale and be dynamic.  But I find the current design somewhat limiting for my specific use-case. I've worked around it with an external inventory script and environment variables, but I think that the proper place is the inventory plugin itself, as this would also give the possibility for performance improvements, as well as extending the core search functionality.

As an example: I think that the search strings which are currently groups or hostname globs could actually be arbitrary search criteria given to the Inventory plugin. For example, when using "rmt's inventory plugin", running 'ansible-playbook app=myapp,dc=lon01 --limit nagios_myapp_alerting=yes" restart_myapp.yaml' might efficiently combine live data from the real inventory DB and nagios.  These are use-cases that you can't (nor should) optimise for with the default inventory plugin(s).

Cheers, Rob

**Comment by mpdehaan** [comment]
There is already the facility of combining multiple inventory sources when the inventory source is a directory.

The way we are going to handle this in ansible-commander (pending, very soon) is to allow injection and manipulation of inventory over REST, where as it can be easily synced from external sources.

**Comment by mpdehaan** [comment]
Closing this as we'll implement this differently, but it will achieve the same ends...

**Comment by rmt** [comment]
I think you miss the point.  Ansible is not, nor will future-Ansible be, the authoritative source of my inventory, and sync'ing isn't a good substitute.  Think of it like [other project]'s indirectors - most of the time the default's fine, but when you need it, the possibility is there and it's very powerful.

If you define & document the Inventory class's interface, I will happily provide a patch for the rest.

**Comment by mpdehaan** [comment]
I dont miss the point, you just misunderstand my implementation
capabilities.

Having local database records is quite vital for referential integrity with
future logging plans.

Don't worry about it, I know what I'm doing and it will be possible to
remove data not in the external source.
