### ISSUE TITLE
hostfile configured in ansible.cfg ignored

### ISSUE THREAD

**Issue by tumbl3w33d** [ansible/ansible#22998]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible.cfg and inventory

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel ab4b8cb104) last updated 2017/03/27 13:15:29 (GMT +200)
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION
Only ansible.cfg contains configuration.
```
[defaults]
hostfile = ./inventory
```
and my inventory (with name `inventory`), adjacent to site.yml, contains a single server named myserver.

##### OS / ENVIRONMENT
`4.9.0-2-amd64 #1 SMP Debian 4.9.13-1 (2017-02-27)`

##### SUMMARY
Ansible doesn't consider the configured default inventory anymore and complains that it finds no host file in /etc/ansible/hosts (which indeed does not exist, I run devel from source).

Workaround: explicitly passing the inventory with -i.

##### STEPS TO REPRODUCE
```yaml
---
- hosts: myserver
  remote_user: root
  tasks:
    - debug:
        msg: "something is broken here"
```

##### EXPECTED RESULTS
Connection to myserver works and the task is executed.

##### ACTUAL RESULTS
Ansible doesn't know about that server.
```
$ ansible-playbook site.yml 
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

 [WARNING]: Could not match supplied host pattern, ignoring: myserver

PLAY [myserver] ******************************************************************************************
skipping: no hosts matched

PLAY RECAP **********************************************************************************************
```

**Comment by bcoca** [comment]
hostfile was deprecated in 2.0 and removed in 2.4, use 'inventory' instead
