### ISSUE TITLE
[0.3 master+devel] Playbook task/handler include broken

### ISSUE THREAD

**Issue by dne** [ansible/ansible#230]
Commit 533c2c6 changed `utils.template` to take 3 arguments, but `utils.template_from_file` (used by `Playbook._include_tasks` and `Playbook._include_handlers`) still invokes `utils.template` with only 2 arguments.

**Comment by mpdehaan** [comment]
Thanks, feel free to fix otherwise this is in queue for tonight.

mgw had reported it early but had not isolated it to the specific use case.

**Comment by mpdehaan** [comment]
all fixed
