### ISSUE TITLE
Add label option to mount module

### ISSUE THREAD

**Issue by lwade** [ansible/ansible#2301]
This would be for facilitating mounting and state checks (present/absent) based on filesystem label, e.g:

mount: name=/mnt/stuff label=mystuff fstype=ext4 state=present

**Comment by dhozac** [comment]
`src=LABEL=mystuff` already works, doesn't it?

**Comment by lwade** [comment]
Oh great, I'm only going by the docs.  I'll try it and see :)

**Comment by skvidal** [comment]
src=LABEL=mystuff works fine - it is, in fact, my primary use case.

examples:
http://infrastructure.fedoraproject.org/cgit/ansible.git/tree/playbooks/hosts/copr-be.cloud.fedoraproject.org.yml#n26

UUID= works, too.

**Comment by lwade** [comment]
Thanks, happily using this now :)

Can we add this as a docs example?

**Comment by skvidal** [comment]
https://github.com/ansible/ansible/pull/2304
