### ISSUE TITLE
copy module failing because it cannot find the source file – but the source file does exist

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#2303]
To provide some context, I’m translating the [GitLab installation guide](https://github.com/gitlabhq/gitlabhq/blob/stable/doc/install/installation.md) into a playbook. Right now I want it to be able to set up on the machine where the playbook is executed, so the host is 127.0.0.1.

The playbook is getting long, and I will for that reason only include the fragment that illustrates the problem. The source file does exist according to both `sudo stat /home/gitlab/.ssh/id_rsa.pub` and Ansible’s file module. But the copy module does not find it. I have tried executing the playbook using both Ansible 1.0 and HEAD. Here is the tail of gitlab.yml:

```
# …

- hosts: all
  sudo: yes
  vars:
    file: /home/gitlab/.ssh/id_rsa.pub
  tasks:
    - file: state=file path=$file
      tags: t
    - copy: src=$file dest=/home/git/gitlab.pub
      tags: t
    - command: whoami
      tags: t
```

Output when running `ansible-playbook -Kv gitlab.yml --tags=t`:

```
PLAY [all] ********************* 

GATHERING FACTS ********************* 
ok: [127.0.0.1]

TASK: [file state=file path=/home/gitlab/.ssh/id_rsa.pub] ********************* 
ok: [127.0.0.1] => {"changed": false, "group": "gitlab", "mode": "0644", "owner": "gitlab", "path": "/home/gitlab/.ssh/id_rsa.pub", "state": "file"}

TASK: [copy src=/home/gitlab/.ssh/id_rsa.pub dest=/home/git/gitlab.pub] ********************* 
failed: [127.0.0.1] => {"failed": true}
msg: could not find src=/home/gitlab/.ssh/id_rsa.pub

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************* 
127.0.0.1                      : ok=2    changed=0    unreachable=0    failed=1
```

**Comment by mpdehaan** [comment]
Sounds like your file is simply not there.

**Comment by bcoca** [comment]
this might be a permissions issue.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
Yep.   Let us know what permissions are and what account you are running
Ansible from.

In which case, we should consider renaming that message to just simply
"could not read" vs "find" :)

**Comment by ghost** [comment]
I’m running Ansible from my own user (at) with `-Kv` as flags, so I enter the sudo password, and my assumption is that the copy module does something like `sudo cp /path/to/src /path/to/dest`. I understand why this wouldn’t work if it tries to access the source and destination file using my own user – if that’s the case, then maybe I need to run `sudo cp` using the command module.

In the example in my original post, the source file belongs to another user (gitlab), and the destination file belongs to yet another user (git). The permission of the source file is 0644. It is owned by gitlab:gitlab.

I might be overlooking something really basic, but I run this Ansible task with sudo rights (as you can see), and I have as an experiment verified that a call to `whoami` says root by putting that command first (not shown in the example above – although you can see the command at the end). To my knowledge, a root user can read files with any permission, and this includes copying a file from one user to another.

**Comment by mpdehaan** [comment]
Incorrect, the sudo applies to the remote end, that the user gets sudo'ed
to another account _after_ logging in.

It seems like you may also wish to invoke ansible itself with sudo.

**Comment by ghost** [comment]
Thanks for clarifying! Now I might be getting it.

Having only worked on localhost playbooks yet, my mind is tricked into thinking that there is no remote connection involved. As for the actual solution in this case, the file to become copied is created on the remote host, and since it should be copied to another user on the remote host, then maybe I should use the command module to do a `cp` in this case. It seems to work fine.

```
- hosts: all
  sudo: yes
  sudo_user: root
  tasks:
    - command: cp /home/gitlab/.ssh/id_rsa.pub /home/git/gitlab.pub creates=/home/git/gitlab.pub
      tags: t
```

**Comment by mpdehaan** [comment]
BTW, if you want to avoid SSH in the localhost case, use "-c local", or
"connection: local" in your playbook.

Not sure if you were already, but thought I would share.

**Comment by ghost** [comment]
I didn’t know about that. Will do. Thanks!

I’m closing this issue if you don’t mind. I hope it can be useful for others that are a bit confused when shifting their thinking from shell scripts to playbooks. :)

**Comment by brucellino** [comment]
Thanks for reporting this behaviour. I just got caught by it too - for  me it was simply a permissions issue, with the local ansible user not finding a file which had been created by a previous play, but belonging to a different user. I need to find a way to check the previously-created file into the user space of the ansible executor, in the next play. (no response required, just wanted to shared :smile: )

**Comment by brucellino** [comment]
Thanks for reporting this behaviour. I just got caught by it too - for  me it was simply a permissions issue, with the local ansible user not finding a file which had been created by a previous play, but belonging to a different user. I need to find a way to check the previously-created file into the user space of the ansible executor, in the next play. (no response required, just wanted to shared :smile: )

**Comment by ghost** [comment]
Figured I'd chime in in case someone else is looking for an answer not here. I got the same behavior and my issue was broken symlinks in my source files.

**Comment by janzenz** [comment]
Same issue with @aizimmer. Have you found a solution to this?

**Comment by mnsdevops** [comment]
Spot this with ansible 2.1.1.0. 3 years passed and no solution yet. Core module simply doesn't work. I spent 4 hours and resolved this by implementing simple shell with cp command.

**Comment by fk0** [comment]
Spot this with ansible 2.1.1.0. 3 years passed and no solution yet. Core module simply doesn't work. I spent 4 hours and resolved this by implementing simple shell with cp command.

**Comment by fk0** [comment]
For 2.0 it's remote_src=true that should be used to indicate copy happens only on remote side. Very confusing. Multiple bug reports confirm.

**Comment by arnabsinha4u** [comment]
I have used the copy module in ansible 2.1.1.0 and had a bit of a hard time in the beginning as to why it was not working simply with src and dest. Specifying the remote_src= to true for local copy and false for remote copy explicitly bullet proofs your task definition.

**Comment by oschrenk** [comment]
I agree with @fk0 and @arnabsinha4u that this is really confusing. Spend an hour scratching my head looking at permission issues before realizing that to copy files around on a specific server I have to set 'remote_src=true'.

**Comment by tofaramac** [comment]
Good day. I am having issue with templates on my ansible.  I have this and its not updating my source.list , it completes with green but no changes to the file. Am i missing something. Its happening only to six hosts and to the rest its working. I don''t know the difference between these hosts i tried to check everything. 

- name: update sources.list
  template: src=sources.list.j2 dest=/etc/apt/sources.list

**Comment by ghost** [comment]
@tofaramac  Some sample verbose output from the playbook run might help in diagnosing the issue, though if it is in fact turning green (chanaged: false) then there may not be anything useful. It sounds as though no changes need to be made to the files on those hosts. If that's not the case and they indeed don't match what should be produced by the template, a core developer might have better luck helping. Some sort of hash/size check to determine if the file needs changing may be messing up.

**Comment by tofaramac** [comment]
not sure what it is because the source.list has to change from my local mirror which i use to install the hosts. It worked with the other hosts but just stopped when i was now running the play to the other hosts. Also i realise again on those same hosts a play can run though and show changed on play but open the file it never changed. Is this a bug or something not right on these hosts

**Comment by arnabsinha4u** [comment]
@tofaramac I would take the following approach:
1) use --check flag to check the possible changes
2) use --diff flag to show the differences during execution
-vvv can surely help but will not show changes for sure if there aren't any.
Maybe you can also do a diff in shell manually to check the 6 files from those hosts to cross verify if the core module is not working properly.

Its highly unlikely that the checksums have matched up by md5 or share.

There are also possibilities that you have hit a bug like using timezones or ssh_user which were bugs before and have been solved by ansible.

**Comment by axd1967** [comment]
am also hitting this issue. just trying to copy a local directory to a remote destination (each time using absolute paths); no permission issue, source directory exists, I keep getting 

> "fatal: [master]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find ' /project/guests/master/ ' in expected paths."}". 

very confusing - why is it saying "expected paths" when `copy` is given an explicit path.

and then I notice this:
```
- hosts: master

  any_errors_fatal: true

  vars:

    mysource: /project/guests/master/
    mydest: /tmp/cdm-master/

  tasks:

  - name: create dest
    file:
      path: " {{ mydest }} "
      state: directory

  - name: install code
    copy:
      src: " {{ mysource }} "
      dest: " {{ mydest }} "

```

notice the extra spaces in `      src: " {{ mysource }} "`; 
changing to 
`      src: "{{ mysource }}"`

fixes my problem...

**Comment by covercash2** [comment]
i was brought here because i forgot remote_src.

it would be nice to have an example in the docs

**Comment by realtebo** [comment]
Same problem

```
- name: create folder for local copy of  certificates
  file:
    path: "{{ playbook_dir }}/roles/certbot/files/{{ item }}.example.com"
    state: directory

- name: copy certificates under ansible files
  become: true
  copy: 
    src: "/etc/letsencrypt/live/{{ item }}.example.com/"
    dest: "{{ playbook_dir }}/roles/certbot/files/{{ item }}.example.com"
    local_follow: yes
```
This task is executed against 

```
[local] 
ansible1  
```

with this vars automatically read from `host_vars/ansible1`

```
ansible_connection: local
ansible_become_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          .... [cut] ...
          34234234233366
```

When ansible esecutes the `copy`, I got 

```
failed: [ansible1] (item=vpnadmin) => {
    "changed": false, 
    "item": "vpnadmin", 
    "msg": "Could not find or access '/etc/letsencrypt/live/vpnadmin.example.com/' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"
}
```

Any suggestion? Of coursem the source folder exists, and the dest folder too, (I just created it  with low privileges)

**Comment by rajeshmoharana** [comment]
Hi ,
I am also facing this issue. Can anyone suggest what the mistake I am doing.


TASK [remove_httpd_check : Taking backup of the existing check] ****************
--
16:43:57 | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/etc/sensu/conf.d/check_httpd.json'
16:43:57 | fatal: [nva1tr1elm01]: FAILED! => {"changed": false, "msg": "Could not find or access '/etc/sensu/conf.d/check_httpd.json'"}


---
- name: Taking backup of the existing check
  sudo: yes
  sudo_user: root
  copy: src=/etc/sensu/conf.d/check_httpd.json dest=/etc/sensu/conf.d/check_jboss.json/check_httpd.json_backup
  tags:
    - remove_httpd_check

file is present in the particular path
