### ISSUE TITLE
Doc error for the mysql_db module (minor)

### ISSUE THREAD

**Issue by asad-at-srt** [ansible/ansible#2307]
On http://ansible.cc/docs/modules.html#mysql_db
the argument "target" is listed as required, but really isn't

I looked at the source code for the module:
https://github.com/ansible/ansible/blob/devel/library/mysql_db

Line 165 declares target as  follows:
            target=dict(default=None),

Note: the author's embedded DOCUMENTATION for this module is in error too at line 69

**Comment by dhozac** [comment]
Line 69 is what generates the website documentation. Would you like to submit a pull request for this?

**Comment by asad-at-srt** [comment]
I will generate a pull-request
