### ISSUE TITLE
vmware_guest doesn't create a properly formatted /etc/resolv.conf file

### ISSUE THREAD

**Issue by diegopuertas** [ansible/ansible#23079]
I'm trying Ansible 2.3 RC2

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest: customization: dns_servers

##### ANSIBLE VERSION
```
/usr/lib64/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
ansible 2.3.0.0
  config file = /opt/ansible/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### CONFIGURATION
```
forks=10
```

##### OS / ENVIRONMENT
```
Centos 6.8
```

##### SUMMARY
I want to provision a VMWare VM and  populate /etc/resolv.conf, so I've puth this in my playbook:
```
- vmware_guests:
      customization:
        domain: "{{ guest_domain }}"
        dns_servers: "{{ guest_dns_servers }}"
        dns_suffix: "{{ guest_dns_suffix }}"
```

And defined this variable in a group_vars file
```
guest_dns_servers:
- 10.75.228.65
  10.75.228.66
```

But I get a wrongly formatted /etc/resolv.conf file:
```
[ansible@ansclient111 etc]$ cat resolv.conf
search  mydomain.com
nameserver      10.75.228.65 10.75.228.66
```

Instead of getting one nameserver line per server, I get all of them in a single line.

##### STEPS TO REPRODUCE
Provision the VM using the aforementioned playbook/group_vars file

##### EXPECTED RESULTS
Get a resolv.conf file like this:

```
search  mydomain.com
nameserver 10.75.228.65
nameserver 10.75.228.66
```

##### ACTUAL RESULTS
Got a resolv.conf file like this:

```
search  mydomain.com
nameserver      10.75.228.65 10.75.228.66
```

**Comment by Fobhep** [comment]
@dapf73 

Isn't the dns-setting feature only supposed to work in windows?

"Add an optional dns_servers or domain entry per interface (Windows)"
http://docs.ansible.com/ansible/vmware_guest_module.html


EDIT: Apparently it works, eventhough the documentation says differently.
I got it working like this:
```

    customization:
      dns_servers:
      - "{{ vm_dns }}"
      - "{{ vm_dns1 }}"
```

and in my vars file:
```
vm_dns:  1.2.3.4
vm_dns1:  8.8.8.8
```

``` 
on the provisioned host:

cat /etc/resolv.conf
# Generated by NetworkManager
search domain.test
nameserver 1.2.3.4
nameserver 8.8.8.8
```


I guess if you change your code from this

```
guest_dns_servers:
- 10.75.228.65
  10.75.228.66
```

to this

```
guest_dns_servers:
- 10.75.228.65
- 10.75.228.66
```

it might work as well!

**Comment by diegopuertas** [comment]
Yeah, but that would beat the purpose. The idea is to define any number of DNS servers in a list.

I managed to make it work like this. Instead of defining the list this way:
```
guest_dns_servers:
- 10.75.228.65
  10.75.228.66
```

I define it this way and it works as expected:
```
guest_dns_servers: [10.75.228.65, 10.75.228.66]
```

It looks like the bug is about parsing YAML.

**Comment by dav1x** [comment]
hey @dapf73 

Please take a look at the yaml syntax documentation in ansible: http://docs.ansible.com/ansible/YAMLSyntax.html

Specifically, here:
All members of a list are lines beginning at the same indentation level starting with a "- " (a dash and a space):
```
---
# A list of tasty fruits
fruits:
    - Apple
    - Orange
    - Strawberry
    - Mango
...
```
Also, here:
Dictionaries and lists can also be represented in an abbreviated form if you really want to:
```
---
fruits: ['Apple', 'Orange', 'Strawberry', 'Mango']
```

**Comment by dagwieers** [comment]
Yes, the user needs to use a YAML or JSON list syntax.
Let's get this issue closed.

notabug
