### ISSUE TITLE
template module does not expand vars in dest argument

### ISSUE THREAD

**Issue by sfllaw** [ansible/ansible#2310]
Here is a sample task that fails:

``` yaml
- name:
  action: template src=/home/.profile dest=$destdir/.profile
```

Expected result:
Copies (and does Jinja2) expansion on /home/.profile and uploads it to the value in `$destdir`.

Actual result:
template complains that `$destdir` is not a directory, because variable expansion did not occur.

**Comment by dhozac** [comment]
Where did you set $destdir?

**Comment by mpdehaan** [comment]
Yes please share as much of your playbook setup as you can.

I am pretty sure there is just a simple typo or something here, as if dest didn't expand, essentially all variables in Ansible would be in similar state and we'd have thousands of people yelling at us :)

Still, want to hear more :)
