### ISSUE TITLE
Include internal tag names in tagging docs (eg, always/all/never)

### ISSUE THREAD

**Issue by Miyurz** [ansible/ansible#23118]
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME
Ansible's tag option

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### SUMMARY

If I specify the tag as `all` though I have associated/mapped it with a role called in my playbook, it runs all the roles. Looks like all is either a reserved keyword. If yes, it should be documented else its a bug.

```
roles:
    - {role: common, tags: ['all', 'common', 'first']}
    - {role: mac, tags: ["OSX", "Mac"]}
    - {role: ubuntu-16.04, tags: ["16.04", "Ubuntu"]}
```

##### STEPS TO REPRODUCE

```
roles:
    - {role: common, tags: ['all', 'common', 'first']}
    - {role: mac, tags: ["OSX", "Mac"]}
    - {role: ubuntu-16.04, tags: ["16.04", "Ubuntu"]}
```

##### EXPECTED RESULTS

Only role with tag `all` should have run.
##### ACTUAL RESULTS

All the roles ran and not just `all` tag associated with one of the roles.

```

```

**Comment by nitzmahone** [comment]
Yes, `always` and `all` are synonymous internal tags. There are legitimate reasons to tag things with those, so not sure that a warning is a possibility. I don't see those documented either along with tags, so probably something we should include.

**Comment by Miyurz** [comment]
@nitzmahone Thank you for the clarification.

**Comment by mckerrj** [comment]
@dharmabumstead will you reach out to @bcoca and attempt to document better.

**Comment by dharmabumstead** [comment]
This is actually documented here:

http://docs.ansible.com/ansible/latest/playbooks_tags.html

**Comment by calfonso** [comment]
@dharmabumstead We probably need some updates to the docs to include "Don't use these tag names for your own stuff or you'll be sad" and something about the never tag,which looks to be missing.

**Comment by bcoca** [comment]
@calfonso since the `never` tag is also missing from the code ... i think it is fine we don't document it

**Comment by bcoca** [comment]
As @dharmabumstead points out above, the existing tags were already documented, 'never' got added to the code AND documented in the same location, so I'm going to close this issue.
