### ISSUE TITLE
password_hash filter doesn't use full character set when generating a salt

### ISSUE THREAD

**Issue by willmerae** [ansible/ansible#23139]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

password_hash filter

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/willmerae/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
In a template the filter `{{ 'some string' | password_hash }}` or `{{ 'some string' | password_hash(hashtype='sha256') }}` will return a crypt formatted hash of the string in question. This format is `$<hashtype>$<salt>$<hash>. Where `hashtype` is a code indicating the has algorithm (e.g. `6` = sha512), and salt is a random value used to make the hash unique.

According to [man crypt(3)](http://man7.org/linux/man-pages/man3/crypt.3.html) the character set for the salt is `A-Za-z0-9/.`, but if no salt is provided then Ansible only uses `A-Za-z0-9` when generating a new salt. The offending code is in `ansible.plugins.filter.core.get_encrypted_password`

```python
salt = ''.join([r.choice(string.ascii_letters + string.digits) for _ in range(saltsize)])
```

The result is hash is still usable, but the strength is weakened slightly due to the smaller key space.

##### STEPS TO REPRODUCE
```yaml
ansible -i localhost, localhost -mdebug -a"msg={{ 'foo' | password_hash }}" -o
```

##### EXPECTED RESULTS
Generated salts may include `/` and '.'. 

##### ACTUAL RESULTS
Generated salts never include `/` or `.`.

```
localhost | SUCCESS => {    "changed": false,     "msg": "$6$2YpulGE5GSC8RYhp$txhd8h6r9fts/bQjcrKft8lkn0GRwImVeVpN/ZwBNK9OPJogJTzs8P/7xEJAWyK/Eca.UU4v2/nfJSvlMnDNv/"}

```

**Comment by kushaldas** [comment]
Can not reproduce it. Host system: Fedora 25

#### Ansible Version
```
ansible 2.4.0 (devel 2e476e64cd) last updated 2017/03/30 21:06:51 (GMT +550)
  config file = /home/kdas/.ansible.cfg
  configured module search path = [u'/home/kdas/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```
#### Actual result
```
localhost | SUCCESS => {    "changed": false,     "msg": "$6$SVu9547ZnvOFkn2T$1Yhg5Wm.jmsjyHbBe3x9/4RzEtmS/i6Yv7E8Mz5wiQ.1t4pWkn1aEtlCNJv6zqsycgVy/3b/2cEHSFE4rdCC71"}

```

**Comment by willmerae** [comment]
Your example did reproduce it. The fields are '$' delimited, and the salt is in the second field'. That's `SVu9547ZnvOFkn2T` in your example, which contains only letters and digits.

**Comment by kushaldas** [comment]
Yup, just now understood the mistake. Sorry for the noise.
