### ISSUE TITLE
Previous packages (.deb) should be kept on repository

### ISSUE THREAD

**Issue by RRAlex** [ansible/ansible#23143]
##### ISSUE TYPE
 - Bug / Workflow

##### COMPONENT NAME
Ansible's Ubuntu repository (version released)

##### ANSIBLE VERSION
```
All the version released for a specific distribution
```

##### SUMMARY
Ansible releases sometime bring new bugs that passes QA and are only found after release.

Like other project, it would make a lot more sense to keep all the releases for a distribution from inception until the distro support is dropped.
(See how Docker does it for example: https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/ ). 
This allows to go back in time when things don't turn out as expected with newer versions.

##### STEPS TO REPRODUCE
Upgrade to 2.2.2.0 and get bitten by https://github.com/ansible/ansible/issues/23016 without being able to rollback to 2.2.1.0 from the repository like any other package.

##### EXPECTED RESULTS
Being able to `apt-get install ansible=2.2.1.0-1ppa~xen` when 2.2.2.0 fails, apt-hold it and don't upgrade until the next fix comes out.
Also, allowing to test the new releases and being able to roll back in a coherent manner.

##### ACTUAL RESULTS
The ansible repository:
http://ppa.launchpad.net/ansible/ansible/ubuntu/pool/main/a/ansible/
... only contains 2.2.2.0 which is an anti-pattern of Debian style repository, stopping people from testing the releases properly without reverting to pip or other workflow breaking solutions.

**Comment by abadger** [comment]
We looked at this in the past but it seemed that the ppas could only keep the most recent builds.  If you know how docker gets the ppa to keep older builds we can get the person who takes care of building the ppas to take a look at enabling it.

**Comment by RRAlex** [comment]
This indeed has been [previously](https://groups.google.com/forum/#!topic/ansible-project/emNkF7CBVew) [discussed](https://github.com/ansible/ansible/issues/13898), but as many people are getting bitten by this over the year, there doesn't seem to be a clear roadmap to fix this issue, and no solution have been selected as the way forward.

I'm not a PPA expert but, with what we know about not being able to test & rollback, PPAs seem unfit for hosting critical software like `ansible`.

I think you simply need to deploy a basic apt repository yourself (that's what docker and others are doing), or work with upstream distros for new releases as they are also keeping older versions.

I don't think the first option is very complicated, even if you only kept the last 20 versions on a rolling basis to keep things manageable.

Could one of those solutions (or others if anyone else has some ideas) be viable?
In the 2015 thread, someone mentioned [aptly](https://www.aptly.info/), which looks like a great place to start!

What do you (or the apt/deb maintainer?) think?

cheers! :)

**Comment by abadger** [comment]
Oh I see, I misread your orignal comment about docker and thought they had figured out how to do this inside of a ppa.  I'll see if I can get our apt/debian packager to comment on this as it's not just a button that I can ask him to enable in the ppa build.

**Comment by RRAlex** [comment]
I understand, it indeed requires some change, but I think that a transition with both the new repository and the PPA living side by side for a while would make this quite smooth and useful for everyone.

For example with docker, again (as they just went through this):
They changed their repository and GPG key (+ package name!) but keep publishing to both repository, at least for a while, and will drop the old one in a few months, letting everyone time to adapt.

**Comment by cadavre** [comment]
I'm totally +1 for this because it's 3rd time (I believe so) in past 6 months I need to roll back to previous version while using apt PPA repository. Take `gitlab-ce` as a good example and check their release history kept in PPA.

PS It *definitely* should not "affect 2.4 future idea" because it can be done anytime to keep at least all history since 2.0.0.0.

**Comment by bcoca** [comment]
gitlab does not use PPA, it uses a deb repository, which seems only way to keep multiple versions.

**Comment by cheGGo** [comment]
Indeed. Please leave all available versions on PPA for possible downgrade on a specific distri.
Just today we have to downgrade from 2.3.0.0 to 2.2.1.0 due to a bug on 2.3.0.0 which breaks our deployment.

**Comment by abadger** [comment]
@cheGGo, once again, this is not possible to do with PPAs.  If you want PPAs to do that, please start petitioning Canonical to make that a possibility.  (That would certainly make it easier for us to do this ;-)

**Comment by SuperSandro2000** [comment]
This is totally possible if you release newer untested version to a testing area. In a relase like eoan only one version is available like debian or ubuntu does it.

**Comment by sivel** [comment]
We have no plans to migrate away from using a PPA, and this is a limitation of using a PPA.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
