### ISSUE TITLE
service module doesn't recognise /etc/init.d/XXX status code of 1 as stopped

### ISSUE THREAD

**Issue by rmt** [ansible/ansible#2317]
Testing on Debian, "service cron status" exits with 1, and service fails to recognise it as stopped, so it won't start it again.

```
root@salt:~# service cron stop
Stopping periodic command scheduler: cron.
root@salt:~# service cron status; echo $?
Checking periodic command scheduler...failed (failed to start).
1

$ ansible salt -u root -m service -a 'name=cron state=started'
salt | success >> {
    "changed": false, 
    "name": "cron", 
    "state": "started"
}
```

Proposed patch to library/service:

```
-            if rc in [2, 3, 4, 69]:
+            if rc in [1, 2, 3, 4, 69]:
```

This was only tested on my debian client, so it should be checked manually on some other systems.

**Comment by sfromm** [comment]
For reference purposes:

http://refspecs.linuxbase.org/LSB_4.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html

I'll update the module.

**Comment by mpdehaan** [comment]
fixed per above, thanks!
