### ISSUE TITLE
FAILED: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by dbarobin** [ansible/ansible#23197]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- ansible

##### ANSIBLE VERSION

```
ansible 1.7.2
```

##### CONFIGURATION

```
[defaults]
hostfile       = /etc/ansible/hosts
remote_tmp     = $HOME/.ansible/tmp
pattern        = *
forks          = 5
poll_interval  = 15
sudo_user      = root
transport      = smart
remote_port    = xxxxx
module_lang    = C
gathering = implicit
sudo_exe = sudo
timeout = 10
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
action_plugins     = /usr/share/ansible_plugins/action_plugins
callback_plugins   = /usr/share/ansible_plugins/callback_plugins
connection_plugins = /usr/share/ansible_plugins/connection_plugins
lookup_plugins     = /usr/share/ansible_plugins/lookup_plugins
vars_plugins       = /usr/share/ansible_plugins/vars_plugins
filter_plugins     = /usr/share/ansible_plugins/filter_plugins
fact_caching = memory
[paramiko_connection]
[ssh_connection]
[accelerate]
accelerate_port = 5099
accelerate_timeout = 30
accelerate_connect_timeout = 5.0
accelerate_daemon_timeout = 30
```

##### OS / ENVIRONMENT

> CentOS release 6.3 (Final)

##### SUMMARY

When I ping a group of hosts, error as follows:

``` bash
192.168.1.243 | success >> {
    "changed": false, 
    "ping": "pong"
}

192.168.1.244 | success >> {
    "changed": false, 
    "ping": "pong"
}

192.168.1.241 | success >> {
    "changed": false, 
    "ping": "pong"
}

192.168.2.87 | FAILED => FAILED: [Errno 111] Connection refused
192.168.2.86 | FAILED => FAILED: [Errno 111] Connection refused
192.168.1.210 | success >> {
    "changed": false, 
    "ping": "pong"
}

192.168.1.242 | success >> {
    "changed": false, 
    "ping": "pong"
}

192.168.1.209 | success >> {
    "changed": false, 
    "ping": "pong"
}
```

Configuration file:

```
[test]
192.168.1.243:22
192.168.1.241:22
192.168.1.242:22
192.168.1.244:22
192.168.1.209:22
192.168.1.210:22
192.168.2.87:22
192.168.2.86:22
```

Yet I login via direct ssh of 192.168.2.86 and 192.168.2.87 is OK.

##### STEPS TO REPRODUCE

> NULL

##### EXPECTED RESULTS

Remote server like 192.168.2.86 and 192.168.2.87 have some problem.

##### ACTUAL RESULTS

> NULL

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

FYI, 1.7 has been out of support for a long time and probably every response is going to start with 'upgrade'.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
