### ISSUE TITLE
pip install v2.3.0.0-0.3.rc3.zip -> broken bin/ansible-* files (tar.gz works correctly)

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#23213]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-doc

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### STEPS TO REPRODUCE

```bash
pip install --user --upgrade https://github.com/ansible/ansible/archive/v2.3.0.0-0.3.rc3.zip
cd ~/.local/bin/
-rwxrwxr-x 1 johnb johnb  4879 Apr  3 11:32 ansible
-rwxrwxr-x 1 johnb johnb 13572 Apr  3 11:32 ansible-connection
-rwxrwxr-x 1 johnb johnb     7 Apr  3 11:31 ansible-console
-rwxrwxr-x 1 johnb johnb     7 Apr  3 11:31 ansible-doc
-rwxrwxr-x 1 johnb johnb     7 Apr  3 11:31 ansible-galaxy
-rwxrwxr-x 1 johnb johnb   217 Jan 16 14:34 ansible-lint
-rwxrwxr-x 1 johnb johnb     7 Apr  3 11:31 ansible-playbook
-rwxrwxr-x 1 johnb johnb     7 Apr  3 11:31 ansible-pull
-rwxrwxr-x 1 johnb johnb   219 Jan 16 14:34 ansible-review
-rwxrwxr-x 1 johnb johnb   365 Jul  6  2016 ansible-validate-modules
-rwxrwxr-x 1 johnb johnb     7 Apr  3 11:31 ansible-vault

~/.local/bin/ansible-doc
/home/johnb/.local/bin/ansible-doc: line 1: ansible: command not found


cat ~/.local/bin/ansible-doc 
ansible

```

If you repeat though install from https://github.com/ansible/ansible/archive/v2.3.0.0-0.3.rc3.**tar.gz** the files are created correctly

Thanks to @bobthebutcher for the initial investigation
##### ACTUAL RESULTS
```

```

**Comment by gundalow** [comment]
@bobthebutcher so apparently the zip is auto created by GitHub, and there isn't anyway of disabling it.

The zipfiles doesn't correctly support symlinks, which is the issue we are seeing above.

Where did you see a link/reference to the zipfile?

The release release message[1] point you to http://releases.ansible.com/ansible/ansible-2.3.0.0-0.3.rc3.tar.gz


[1] https://groups.google.com/forum/#!topic/ansible-devel/X8sYLl-ZuTY

**Comment by bwks** [comment]
I found it here: https://github.com/ansible/ansible/releases  
fyi, I originally found this link via ye old faithful: google

**Comment by bobthebutcher** [comment]
I originally found this link via ye old faithful: google

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/issues/19482

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/pull/23102

**Comment by sivel** [comment]
This has been resolved in https://github.com/ansible/ansible/pull/23233
