### ISSUE TITLE
fortios_ipv4_policy.py state=absent

### ISSUE THREAD

**Issue by jmcgill298** [ansible/ansible#23239]
##### General Notes
Issue 1: Clarity
ID is not clear. ID refers to the "edit #" in the config, but not the seq.# that is used in GUI (also the sequence in which they appear in the config).
  EX:
```
  I use this module to configure a new policy for "id: 2", it will either replace or configure a new policy with beginning "edit 2"
  I use the module again to configure a new policy for "id: 3", it will either replace or configure a new policy with beginning "edit 3"
  I use the module again to delete the policy for "id: 2", it will remove policy with beginning "edit 2"
  I use the module again to configure a new policy for "id: 2", it will configure a new policy with beginning "edit 2"
  If I look at the order of the rules in the GUI, "edit 3" will have a sequence number of 2, and "edit 2" will have a sequence number of 3, which corresponds to the order of the rules in both the GUI and CLI.
```

Issue 2 (main issue): Module Error
When setting the "state" to "absent", the module errors because the fortios_ipv4_policy.py file has a line that is trying to pass a "path" variable, which does not exist. I got this to work by replacing with "path" with "firewall policy" (I believe this is what is intended, but please verify this meets all expected behavior).
```python
    #Absent State
    if module.params['state'] == 'absent':
        fortigate.candidate_config[path].del_block(policy_id)
```
to
```python
    #Absent State
    if module.params['state'] == 'absent':
        fortigate.candidate_config['firewall policy'].del_block(policy_id)
```

Issue 3: Update Documentation
The state command's comments read "Specifies if address need to be added or deleted." It seems that the actual intent of this setting is to decide whether a policy "id" (I have chosen "id" as this seems to determining factor, please see Issue 4 below) is to be created/modified or deleted. Suggest to word something like "Specifies if  policy "id" needs to be updated or deleted."

Issue 4: Module Requirements
The module requires unused parameters: "dst_addr", "policy_action", "service", and "src_addr". These are required when state=present, but are completely ignored when state=absent (using my workaround in Issue 2). If these are required, then they should check the policy "id" that is passed in and validate that the policy "id" configuration matches the  "dst_addr", "policy_action", "service", and "src_addr" parameters. Otherwise, these should only be required when setting state=present.
  EX: 
```  
  I have policy id 2 configured for dst_addr=web_servers, policy_action=accept, service=HTTP, and src_addr=users
  I run state=absent (using my fix in Issue 2) with id=2, dst_addr=all, policy_action=deny, service=FTP, and src_addr=all: the result is that policy id 2 is removed from the configuration (even though all 4 parameters do not match the configured policy).
```

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

fortios_ipv4_policy
##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ntc/ansible-modules/']
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

configured module search path = [u'/etc/ntc/ansible-modules/']

##### OS / ENVIRONMENT

Ubuntu -> Fortios
##### SUMMARY

Invalid variable name "path" in fortios_ipv4_policy.py when setting state=absent

##### STEPS TO REPRODUCE

Issue is when setting "state" to absent (used to delete a policy id)

```yaml
  - name: IPv4 ACL CONFIG
    hosts: fortinet
    connection: local
    gather_facts: False
    tags: core

    tasks:
      - name: Add ACL
        fortios_ipv4_policy:
          host: "{{ inventory_hostname }}"
          username: "{{ username }}"
          password: "{{ password }}"
          id: 2
          src_addr: users
          dst_addr: web_servers
          service: HTTP
          policy_action: accept
          state: absent
        tags: acl_conf
```

##### EXPECTED RESULTS

Policy ID 2 to be removed from Fortigate
##### ACTUAL RESULTS

(ans23) #ansible-playbook fpb.yml -t acl_conf -vvvv
Using /etc/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /home/user/ans23/local/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: fpb.yml ****************************************************************************************************************************************************************
3 plays in fpb.yml

PLAY [GETTERS] *******************************************************************************************************************************************************************
META: ran handlers
META: ran handlers
META: ran handlers

PLAY [IPv4 ACL CONFIG] ***********************************************************************************************************************************************************
META: ran handlers

TASK [Add ACL] *******************************************************************************************************************************************************************
task path: /home/user/fpb.yml:28
Using module file /home/user/ans23/local/lib/python2.7/site-packages/ansible/modules/network/fortios/fortios_ipv4_policy.py
<x.x.x.x> ESTABLISH LOCAL CONNECTION FOR USER: user
<x.x.x.x> EXEC /bin/sh -c 'echo ~ && sleep 0'
<x.x.x.x> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp/ansible-tmp-1491250419.7-34981597923660 `" && echo ansible-tmp-1491250419.7-34981597923660="` echo /home/user/.ansible/tmp/ansible-tmp-1491250419.7-34981597923660 `" ) && sleep 0'
<x.x.x.x> PUT /tmp/tmp12VgU1 TO /home/user/.ansible/tmp/ansible-tmp-1491250419.7-34981597923660/fortios_ipv4_policy.py
<x.x.x.x> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1491250419.7-34981597923660/ /home/user/.ansible/tmp/ansible-tmp-1491250419.7-34981597923660/fortios_ipv4_policy.py && sleep 0'
<x.x.x.x> EXEC /bin/sh -c 'python /home/user/.ansible/tmp/ansible-tmp-1491250419.7-34981597923660/fortios_ipv4_policy.py; rm -rf "/home/user/.ansible/tmp/ansible-tmp-1491250419.7-34981597923660/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_HKDLrk/ansible_module_fortios_ipv4_policy.py", line 287, in <module>
    main()
  File "/tmp/ansible_HKDLrk/ansible_module_fortios_ipv4_policy.py", line 228, in main
    fortigate.candidate_config[path].del_block(policy_id)
NameError: global name 'path' is not defined

fatal: [x.x.x.x]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_HKDLrk/ansible_module_fortios_ipv4_policy.py\", line 287, in <module>\n    main()\n  File \"/tmp/ansible_HKDLrk/ansible_module_fortios_ipv4_policy.py\", line 228, in main\n    fortigate.candidate_config[path].del_block(policy_id)\nNameError: global name 'path' is not defined\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
	to retry, use: --limit @/home/user/fpb.retry

PLAY RECAP ***********************************************************************************************************************************************************************
x.x.x.x               : ok=0    changed=0    unreachable=0    failed=1 

```

```

**Comment by gundalow** [comment]
@bjolivot Could you please take a look

It would be good to get this fixed for 2.3 final (Wednesday 12th April) Thanks

**Comment by bjolivot** [comment]
Thank you @jmcgill298 for this detailed bug report.
I've a pull request comming.

As I dont use GUI, I'm not very sure if following doc updates are more understandable:

For 'id' param description:
       Policy ID 
        /!\ Warning: policy I(id)# is different than Policy sequence# /!\
        Default web display show only policies sequence numbers,
        you need to add policy id column in display options.

For 'state' param description:
        Specifies if policy I(id) need to be added or deleted.

Is it more clear for you, feel free to propose better explanations :)

**Comment by jmcgill298** [comment]
Hey @bjolivot, I was thinking of more of a general warning and explanation, but the tip about the GUI is good too. Anyway, here is my stab at it:

For 'id' param description:
Policy ID
/!\ Warning: policy ID # is different than Policy sequence# /!\
The policy ID is the number assigned at policy creation.
The sequence # represents the order in which the Fortigate will evaluate the rule for policy enforcement, and also the order in which rules are listed in the GUI and CLI.
These two numbers do not necessarily correlate: this module is based off policy ID.
* TIP: policy ID can be viewed in the GUI by adding "ID" to the display columns
