### ISSUE TITLE
ansible & ansible-connection logging 2.4

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#23252]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ansible-connection

##### SUMMARY

This ticket is to track the ideas for further improving logging, it builds on https://github.com/ansible/ansible/issues/22703 which was included in 2.3

* Provide more feedback directly (`unable to open shell` case)
* Would love to see full raw SSH connection with correct verbosity. Should be possible with socket.SOCKET_RAW (I think...) @itdependsnetworks in https://github.com/ansible/ansible/issues/22703#issuecomment-287395968

Each update should also update the Network debug guide.

Feel free to add comments to this issues with other ideas

**Comment by gundalow** [comment]
`ssh - G` that may be useful for `ansible-connection` https://github.com/ansible/ansible/pull/23241

**Comment by calfonso** [comment]
We are tracking this as an issue in https://github.com/ansible/ansible/issues/33047 , closing this issue.
