### ISSUE TITLE
ansible-connection: Prompt to add ssh keys

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#23253]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ansible-connection

##### SUMMARY
We need to investigate a way to add ssh keys cleanly without blanket add/ignore.

This would update:

```
# When using persistent connections with Paramiko, the connection runs in a
# background process.  If the host doesn't already have a valid SSH key, by
# default Ansible will prompt to add the host key.  This will cause connections
# running in background processes to fail.  Uncomment this line to have
# Paramiko automatically add host keys.
#host_key_auto_add = True
```

**Comment by calfonso** [comment]
@privateip feedback, no way to do this with current architecture

**Comment by calfonso** [comment]
We are going to improve the messaging around this that it needs be done; however, we aren't able to do it with the current architecture.
