### ISSUE TITLE
Group vars defined under [group:vars] in inventory don't override vars from group_vars/*.yaml

### ISSUE THREAD

**Issue by mbert** [ansible/ansible#23258]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION
```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.6.6 (r266:84292, Aug 18 2016, 08:36:59) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### CONFIGURATION
./.

##### OS / ENVIRONMENT
Oracle Linux 6.8

##### SUMMARY
Group vars from group_vars/*.yaml override vars defined under [group:vars] in an inventory file.
See the below outputs.

Ansible versions prior to the one above (e.g. 2.2.1.0) handled this correctly.

##### STEPS TO REPRODUCE

Inventory file foo.inventory:
```
[foo]
localhost

[foo:vars]
VAR=foo
```

Playbook foo.yaml:

```
---
- hosts: "foo"
  gather_facts: no
  tasks:
  - debug: msg="{{VAR}}"
```

group_vars/all.yaml:
```
---
VAR: bar
```

Now run ansible:
`ansible-playbook -i foo.inventory foo.yaml`

##### EXPECTED RESULTS
```
ok: [localhost] => {
    "changed": false, 
    "msg": "foo"
}
```

##### ACTUAL RESULTS
```
ok: [localhost] => {
    "changed": false, 
    "msg": "bar"
}
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The precedence rules specify that `group_vars` are supposed to override 'group vars' defined in the inventory file.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by mbert** [comment]
In that case the bug is in ansible 2.1.1.0 as it deals with this the way I listed under 'expected' above?

**Comment by mbert** [comment]
See #23459.
