### ISSUE TITLE
when_ conditionals should be ANDed when multiples are used

### ISSUE THREAD

**Issue by skvidal** [ansible/ansible#2326]
tasks:
- name: my task
  action: command run stuff
  when_set: $somevar
  when_failed: $last_task

right now - the last when_ conditional defined is the one that determines if the task will run. I'd like for them to be 'anded'

**Comment by mpdehaan** [comment]
agree!

**Comment by skvidal** [comment]
looking at the code a bit in playbook/task.py I noticed this in the devel branch:

``` python
            elif x.startswith("when_"):
                if 'when' in ds:
                    raise errors.AnsibleError("multiple when_* statements specified in task %s" % (ds.get('name', ds['action'])))
                when_name = x.replace("when_","")
                ds['when'] = "%s %s" % (when_name, ds[x])
                ds.pop(x)
```

which will need to get changed out, I think, to handle multiple when statements per task.

**Comment by mpdehaan** [comment]
conditionals are going to be improved by having a generic when: keyword that takes {{ }} Jinja2 style inline soon, so this should no longer be needed, ex:

when: {{ a = b and c == 2 and type(d) == int and z in [3,4,5] }}

So I am thinking we essentially deprecate (or unadvise) use of the other forms.

**Comment by sevein** [comment]
That would be really cool!

**Comment by surajsavita** [comment]
Do we have this functionality?? if yes then any documentation for the same.
If not, when can we expect it??

**Comment by jimi-c** [comment]
@surajsavita yes this is how the conditionals work now. If you have any further questions, please ask them on the mailing list. Thanks!
