### ISSUE TITLE
Solaris 10

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#2327]
I am very new to Ansible. I get following strange message if I run a command (ansible all -m ping) against some Solaris 10 machines: Only one is successful, others failing with:

sol50 | success >> {
    "changed": false,
    "ping": "pong"
}

sol45 | FAILED >> {
    "failed": true,
    "msg": "Error: ansible requires a json module, none found!",
    "parsed": false
}

sol33 | FAILED >> {
    "failed": true,
    "msg": "Error: ansible requires a json module, none found!",
    "parsed": false
}

sol22 | FAILED >> {
    "failed": true,
    "msg": "Error: ansible requires a json module, none found!",
    "parsed": false
}

What I do not understand?  What is wrong?  Ansible which I test is running on a Ubuntu machine, with actual github sources...

Please help!
Thanks in advance

**Comment by bennojoy** [comment]
HI Afsin,

I think the python's json module is not installed on the failed solaris
machines, can you check if python 2.6  is installed on the nodes, if some
lesser version, install the python simplejson module.
Hopefully that would help.

Regards,
Benno

**Comment by bcoca** [comment]
Python 2.5 and above include json, 2.4 and below require separate install.
Ansible raw module should still work,so you can use to install it.
Brian Coca

**Comment by ghost** [comment]
Thanks much for the comments!  It works now! ;-)

**Comment by ghost** [comment]
Most of Ansible is now running against managed Solaris machines, but I do not know how to solve the following issue:

ansible-host % ssh solaris date
Freitag,  8. März 2013, 15:06:50 Uhr CET

% ansible solaris -a "date"
solaris | FAILED >> {
    "failed": true,
    "msg": "Traceback . . .  'utf8' codec can't decode bytes in position 14-16: invalid data\n",
    "parsed": false
}

Anybody, can help?
Thnx ;-)

**Comment by mpdehaan** [comment]
This is Q&A not a bug, and belongs on the mailing list.

Thanks!
