### ISSUE TITLE
lvol fails on squeeze

### ISSUE THREAD

**Issue by abulimov** [ansible/ansible#2328]
lvol module fails on Debian Squeeze with "Unrecognised field: lv_path" error, because lvm package in Squeeze is old, and does not have option to output lv_path field. For example, in wheezy, rhel6.3 and ubuntu 12.04 this option presents. I've made a patch to fix it.

https://gist.github.com/abulimov/5108115

**Comment by mpdehaan** [comment]
cc @jhoekx ... thoughts?

**Comment by mpdehaan** [comment]
@abulimov -- can you please submit this patch as a pull request?

**Comment by jhoekx** [comment]
Looks good!

**Comment by abulimov** [comment]
I will try to submit this patch as pull request on Monday

**Comment by mpdehaan** [comment]
closing per above PR, thanks
