### ISSUE TITLE
PATH environment variable is not used correctly to launch local scripts

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#23298]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
script

##### ANSIBLE VERSION
```
all stable & unstable latest versions, including
- 2.3.0.0-0.3.rc3
- 2.4.0~git20170404.1daa69d68
```

##### CONFIGURATION
inventory = ./hosts
forks = 1000
gathering = explicit
roles_path =/home/actionmystique/Ansible/Roles/roles
private_role_vars = yes
timeout = 10
fact_caching = redis
fact_caching_timeout = 86400

##### OS / ENVIRONMENT
Ubuntu 16.10 4.8

##### SUMMARY
An error pops up when a script is launched locally indicating that it is not in the expected paths, although it is accessible with the PATH variable. 
Since there is no need to transfer the script to a remote node in this situation, it should not be necessary to indicate the whole script path in the role.
Of course, if I add the whole path to the script, the role execution passes.

##### STEPS TO REPRODUCE
Role launching a local script:
```
- name: Configuring SSH on the remote node
  local_action: script cisco_init_ssh.sh
  register: return_code
```

##### ACTUAL RESULTS
```
fatal: [XEv_Spine_31 -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Unable to find 'cisco_init_ssh.sh' in expected paths."
}
```
Although the script is accessible locally:
```
# which cisco_init_ssh.sh
/home/actionmystique/Bash/Scripts/cisco_init_ssh.sh
# env | grep -i PATH
PATH=...:/home/actionmystique/Bash/Scripts:...
```

**Comment by lassizci** [comment]
I'm afraid it's much worse than not respecting PATH. In fact it seems to be completely broken. I get the error even with full path with all versions >2.1

test.yml:
```
---
- hosts: all
  become: no
  tasks:
    - name: exec a script locally
      local_action: script "/tmp/localscript.sh"
```
/tmp/localscript.sh
```
#!/bin/bash
echo "foo"
```

```
ansible-playbook -i inventory -l myhost test.yml
```

```
TASK [exec a script locally] *********************************************************************************************
fatal: [myhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find '\"/tmp/localscript.sh\"' in expected paths."}
```

**Comment by jean-christophe-manciot** [comment]
I am able to run local scripts when their full path is provided:
```
- name: Configuring SSH on the remote node
  local_action: script /home/actionmystique/Bash/Scripts/cisco_init_ssh.sh {{ nms_mgt_ip_address }} {{ ansible_host }} {{ inventory_hostname }} {{ remote_domain_name }} {{ os_family }} {{ connections.ssh.username }} {{ connections.ssh.password }}
  register: return_code
```

**Comment by sivel** [comment]
Ansible does not utilize many profile or rc files normally available to you when logging in interactively as a user.

Each task is executed in it's own non-interactive shell.  You are likely modifying `PATH` via one of those profile or rc files not sources on non-interactive logins.

You will need to experiment or research where you can place these `PATH` manipulations so that they are available to you.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
