### ISSUE TITLE
only_if, find, and quoting

### ISSUE THREAD

**Issue by ChrisEineke** [ansible/ansible#2330]
Background:
I store the results of a /command/ task in a register. That register has a stdout property that need check for a certain string. If that string is found, do another /command/ task. The stdout string contains single quotes and may contain even double quotes.

Issue:
If my only_if clause is: "'${my_reg.stdout}'.find('foo') != -1" and stdout contains any single quotes or if my only_if clause is: "\"${my_reg.stdout}\".find('foo') != -1", and stdout contains any double quotes, I run into issues with string escaping.

Question:
What's the proper approach to finding needles in strings that contain either quote styles? Am I doing it wrong? ;P

**Comment by dhozac** [comment]
```
when_string: 'foo' in ${my_reg.stdout}
```

should work well.

In general though, triple-quoting should work most of the time.
