### ISSUE TITLE
Automatic test for parsing inventories

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#23303]
##### ISSUE TYPE
 - Missing test

##### COMPONENT NAME
Tests

##### ANSIBLE VERSION
```
devel
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Could you please add a few automatic tests which will test parsing of different inventory files. For example an issue like this one https://github.com/ansible/ansible/issues/23016 could easily be captured if there was a test for it. It should be a relatively easy to add these tests and run them.

**Comment by kustodian** [comment]
@mattclay I was told that you are pretty diligent on test issues :)

**Comment by gundalow** [comment]
Hi @kustodian is this something you'd be able to help with?

**Comment by bcoca** [comment]
FYI we do have several tests that involve parsing inventories, they just happen to no hit that corner case (bad 'ungrouped' hosts).

**Comment by kustodian** [comment]
@gundalow I wouldn't mind adding this test into other inventory tests, if you can point me to the right directory where I should add that.

**Comment by gundalow** [comment]
@kustodian Unit tests live in ` test/units/contrib/inventory` & `test/units/inventory/` 

They can be invoked by doing
`./test/runner/ansible-test units --python 2.7  test/units/contrib/inventory/`

`see ./test/runner/ansible-test units --help` for more info

**Comment by giovannisciortino** [comment]
If I understood well this issue, I think that the last version of test/units/inventory/test_inventory.py is already containing a couple of regression test for the fix #23018 of the issue #23016
There are already two test [test_ini](https://github.com/ansible/ansible/blob/78bb48a0f61563d50f8a05adf445f87f6d43da67/test/units/inventory/test_inventory.py#L122) and [test_ini_explicit_ungrouped](https://github.com/ansible/ansible/blob/78bb48a0f61563d50f8a05adf445f87f6d43da67/test/units/inventory/test_inventory.py#L133) where the host3 is present two times in the inventory: one time is ungrouped, one time is in a group.
The inventory with an same host in and out a group is reported as example in the issue #23016 and it was causing the error: "Unexpected Exception: 'Host' object has no attribute 'remove_group'"
I tried to "rollback" the fix #23018 in ansible 2.4.0 commenting the two function created in the commit of #23018.
With this modification, the use case described in #23018 summary fails again as expected with the error:
`ERROR! Unexpected Exception, this is probably a bug: 'Host' object has no attribute 'remove_group'`
but also the tests running with the command ./test/runner/ansible-test units --python 2.7 test/units/inventory/ fails with the same error (see [here](https://gist.github.com/giovannisciortino/507f0c9f18e97755282ed6cc100b394b) for the test output ) 

If this reasoning is correct, this issue maybe has been already fixed.

**Comment by bcoca** [comment]
closing as per above
