### ISSUE TITLE
Please document regex (and fnmatch) host limiting

### ISSUE THREAD

**Issue by akvadrako** [ansible/ansible#2333]
I found this function by looking at the source, but it isn't mentioned in http://ansible.cc/docs/patterns.html It would be nice to give some examples.

``` python
    def _match(self, str, pattern_str):
        if pattern_str.startswith('~'):
            return re.search(pattern_str[1:], str)
        else:
            return fnmatch.fnmatch(str, pattern_str)
```

**Comment by mpdehaan** [comment]
Will do!   Thanks for filing a ticket!

**Comment by mpdehaan** [comment]
done, will be in next docs push (today)

here is the example I used:

```
'~(web|db).*\.example\.com'
```

matches

db7.example.com
web12.example.com
etc

fnmatch glob patterns were already there

**Comment by trocster** [comment]
regex's containing numerical character ranges do not to work e.g: 

``` regex
 '~test[1-5].example.com' 
```

These seem to get processed by ansible's own enumeration handling, (\d) works though, but is not as flexible.
