### ISSUE TITLE
All OK when using git module and git isn't present. 

### ISSUE THREAD

**Issue by boxrick** [ansible/ansible#23344]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

http://docs.ansible.com/ansible/git_module.html

##### ANSIBLE VERSION
Latest RC as of 06/04/16

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/local/lib/python2.7/dist-packages/ara/plugins/modules']
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609
```

##### OS / ENVIRONMENT
Ubuntu 16.04 4.8 Kernel

##### SUMMARY

When using the GIT module without GIT present, it returns OK and carries on. 

##### STEPS TO REPRODUCE

Use the GIT module and do not have GIT installed. 

```yaml
- name: Clone OSA
  git:
    repo: 'https://git.openstack.org/openstack/openstack-ansible'
    dest: /opt/openstack-ansible
  failed_when: false
```

##### EXPECTED RESULTS

Fail since GIT is not present on the system

##### ACTUAL RESULTS

Simply shows as OK and continues, with a bit of output in message indicating git is not available when extra verbose is enabled. 

```
ok: [dev0] => {
    "changed": false,
    "failed": false,
    "failed_when_result": false,
    "invocation": {
        "module_args": {
            "accept_hostkey": false,
            "bare": false,
            "clone": true,
            "depth": null,
            "dest": "/opt/openstack-ansible",
            "executable": null,
            "force": true,
            "key_file": null,
            "recursive": true,
            "reference": null,
            "refspec": null,
            "remote": "origin",
            "repo": "https://git.openstack.org/openstack/openstack-ansible",
            "ssh_opts": null,
            "track_submodules": false,
            "umask": null,
            "update": true,
            "verify_commit": false,
            "version": "HEAD"
        }
    },
    "msg": "Failed to find required executable git in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
}
```

**Comment by snowsky** [comment]
reproduced the issue.

**Comment by snowsky** [comment]
I know where the problem is, but don't know how to fix:

In git module:
```
git_path  = module.params['executable'] or module.get_bin_path('git', True)
```
get_bin_path failed by fail_json and fail_json called sys.exit(1), but git module didn't catch the SystemExit signal.

**Comment by snowsky** [comment]
When debugging the failed is true:
```
{"msg": "Failed to find required executable git", "failed": true, "invocation": {"module_args": {"executable": null, "force": false, "refspec": null, "reference": null, "dest": "/tmp/openstack-ansible", "verify_commit": false, "clone": true, "accept_hostkey": false, "update": true, "umask": null, "repo": "https://git.openstack.org/openstack/openstack-ansible", "depth": null, "version": "HEAD", "bare": false, "recursive": true, "remote": "origin", "key_file": null, "ssh_opts": null, "track_submodules": false}}}
```

But the ansible command returns false:
```
ok: [localhost] => {
    "changed": false,
    "failed": false,
    "failed_when_result": false,
    "invocation": {
        "module_args": {
            "accept_hostkey": false,
            "bare": false,
            "clone": true,
            "depth": null,
            "dest": "/tmp/openstack-ansible",
            "executable": null,
            "force": false,
            "key_file": null,
            "recursive": true,
            "reference": null,
            "refspec": null,
            "remote": "origin",
            "repo": "https://git.openstack.org/openstack/openstack-ansible",
            "ssh_opts": null,
            "track_submodules": false,
            "umask": null,
            "update": true,
            "verify_commit": false,
            "version": "HEAD"
        },
        "module_name": "git"
    },
    "msg": "Failed to find required executable git"
}
```

**Comment by snowsky** [comment]
The issue here is "failed_when". If I use this playbook, it will pass:
```
  tasks:
    - name: Clone OSA
      git:
        repo: 'https://git.openstack.org/openstack/openstack-ansible'
        dest: /tmp/openstack-ansible
      register: r
      failed_when: r.failed == true
```
Or you can just ignore the last 2 lines.

**Comment by snowsky** [comment]
I don't think it is an Ansible issue.

**Comment by jctanner** [comment]
cc @robinro

**Comment by dagwieers** [comment]
@boxrick @snowsky If you deliberately state: `failed_when: false` you are telling Ansible to not fail (even if the task would have failed). So you are overriding the failure of the task and this will cause the output: `"failed": false` rather than `"failed": true`...

Simply remove the 'failed_when: false` from your task and it behaves the way you expected.

notabug

**Comment by snowsky** [comment]
Thanks @dagwieers for the details and I took some time to look into the codes but missed the failed_when part of codes. I'll revisit and get more ideas.

**Comment by snowsky** [comment]
So basically failed_when: false means ignore_errors, isn't it?

**Comment by sivel** [comment]
`failed_when: false` changes the failure status, so that ansible doesn't see it as failed.  `ignore_errors: true` allows it to fail, display as red, but the failure is ignored and the playbook continues.

**Comment by dagwieers** [comment]
No.
- `ignore_errors: true` means *the task status status failed, but we ignore the consequence of a failed task*.
- `failed_when: false` means *the task status is not failed, even if the task did fail*.

**Comment by snowsky** [comment]
Thanks @sivel @dagwieers

**Comment by abadger** [comment]
Agreed dag and sivel, this is not a bug.
