### ISSUE TITLE
Is there really no web hook to trigger an SCM run?

### ISSUE THREAD

**Issue by roweryan** [ansible/ansible#23372]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION
```
  ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
RHEL7

##### SUMMARY
I make a change in git, it gets pushes to Gitlab, then comes the unfun part: I have to manually log-in to ansible tower and click a button to pull the changes! Tower should support a web hook to pull the change like Puppet Enterprise does!

**Comment by nitzmahone** [comment]
@roweryan: This repo's not for Tower, just the open source Ansible core command-line tools. If you're a Tower customer, you should file that feature request on Tower via support or your sales rep.
