### ISSUE TITLE
Copy module: cannot place multiple copy lines in same task, only executes last one

### ISSUE THREAD

**Issue by jwasham** [ansible/ansible#2339]
Given a task block with more than one "copy:" line (example):
- name: Copy our very important files
  copy: src=managed_files/foo1 dest=/etc/init/foo1 mode=0600 owner=root group=root
  copy: src=managed_files/foo2 dest=/etc/init/foo2 mode=0600 owner=root group=root
  tags: config_files

foo2 will get copied, but foo1 will not.

**Comment by mpdehaan** [comment]
Of course you can't, you have to make more than one task :)

```
- copy: ...
- copy: ...
```

or use "with_items".

See the documentation for examples.
