### ISSUE TITLE
PlayBook initializer should optionally accept playbook as a data structure

### ISSUE THREAD

**Issue by rmt** [ansible/ansible#2341]
Given the possibilities of using data structures as input (in the form of YAML), it would be a nice feature if the PlayBook initializer accepted playbooks as data structures directly. I assume that you'd also have to pass a base directory, to handle relative paths.

One use-case would be a Playbook pre-processor.

**Comment by mpdehaan** [comment]
Hmm, so basically a constructor that was a YAML string rather than a filename too?   That seems reasonable.

**Comment by rmt** [comment]
There's no need to pass (or parse) YAML.  Just a list of dicts, the same as what would be in a YAML playbook, but as a python datastructure instead.

**Comment by mpdehaan** [comment]
patches would be accepted, closing this for now
