### ISSUE TITLE
make rpm fail when try copy man1

### ISSUE THREAD

**Issue by LuckySB** [ansible/ansible#23445]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
make rpm ansible packet 

##### ANSIBLE VERSION
Last version from main branch
```
ansible-2.4.0-100.git201704091600.83a6d90.devel
```

##### CONFIGURATION
none

##### OS / ENVIRONMENT
Centos 7

##### SUMMARY
make rpm fail with error:
cp: cannot stat 'docs/man/man1/*.1': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.CaBVhB (%install)

##### STEPS TO REPRODUCE

git clone https://github.com/ansible/ansible.git
cd ./ansible
git submodule update --init --recursive
make rpm

##### EXPECTED RESULTS
build rpm packet

##### ACTUAL RESULTS
```
+ mkdir -p /home/bond/1ansible/ansible/rpm-build/BUILDROOT/ansible-2.4.0-100.git201704091600.83a6d90.devel.el7.centos.x86_64//usr/share/man/man1/
+ cp -v 'docs/man/man1/*.1' /home/bond/1ansible/ansible/rpm-build/BUILDROOT/ansible-2.4.0-100.git201704091600.83a6d90.devel.el7.centos.x86_64//usr/share/man/man1/
cp: cannot stat 'docs/man/man1/*.1': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.CaBVhB (%install)
```

**Comment by alikins** [comment]
I can duplicate the error and verify the change in https://github.com/LuckySB/ansible/issues/1 fixes it.

@LuckySB can you file that pr against github.com/ansible/ansible ?

**Comment by LuckySB** [comment]
Pull request

https://github.com/ansible/ansible/pull/23469
