### ISSUE TITLE
If included file is a symlink, symlinked path should be added in lookup paths for files and templates

### ISSUE THREAD

**Issue by iljabauer** [ansible/ansible#23442]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
include

##### ANSIBLE VERSION

```
ansible 2.4.0 (symlink_with_tests 1cf607d8a8) last updated 2017/04/09 19:10:56 (GMT +200)
  config file = 
  configured module search path = ['/Users/ibauer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ibauer/Documents/_ITS/ansible/lib/ansible
  executable location = /Users/ibauer/Documents/_ITS/ansible/bin/ansible
  python version = 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

This issue is already reported in #9309 and is not fixed yet.
If a role has following code in the main.yml:

```
- include: test.yml
```

and test.yml is a symlink and has following content:

```
- template: src=test.j2 dest=tmp
```

The file will not be found because the file will be searched in the folder of the main.yml.

With this change the file will be searched in the folder of main.yml first, and the in the symlinked test.yml folder
##### STEPS TO REPRODUCE

Test case is included in the pull request

##### EXPECTED RESULTS

I expect, that if I include as symlinked file, copying files and templates works as expected. Beside this I expect, that I can overwrite the file by placing one with the same name in the including role or playbook
##### ACTUAL RESULTS

Included role or playbook cannot find the referenced file, because it is not searching in the symlinked path

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

If you symlink a file the original path is not supposed to be in the expected search paths, Ansible will (and should) only consider the current path, if need any other resources you can symlink these also.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
