### ISSUE TITLE
Handling of group_vars precedence not handled constently

### ISSUE THREAD

**Issue by mbert** [ansible/ansible#23459]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION
```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
./.

##### OS / ENVIRONMENT
Oracle Linux 6.8

##### SUMMARY
Group vars from group_vars/*.yaml don't override vars defined under [group:vars] in an inventory file.
See the below outputs.

Ansible version  2.3.0 handles this correctly as pointed out by @bcoca in #23258.

##### STEPS TO REPRODUCE

Inventory file foo.inventory:
```
[foo]
localhost

[foo:vars]
VAR=foo
```

Playbook foo.yaml:

```
---
- hosts: "foo"
  gather_facts: no
  tasks:
  - debug: msg="{{VAR}}"
```

group_vars/all.yaml:
```
---
VAR: bar
```

Now run ansible:
`ansible-playbook -i foo.inventory foo.yaml`

##### EXPECTED RESULTS
```
ok: [localhost] => {
    "changed": false, 
    "msg": "bar"
}
```

##### ACTUAL RESULTS
```
ok: [localhost] => {
    "changed": false, 
    "msg": "foo"
}
```

After renaming _group_vars/all.yaml_ to _group_vars/foo.yaml_ the output is 'bar' as expected.

According to the [documentation](http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable) the precedence should be:

1. [...]
2. inventory INI or script group vars (as above)
3. group_vars/all (inventory and playbook)
4. group_vars/* (inventory and playbook)
5. [...]

Hence the value from the inventory should be overridden regardless whether the value defined under _group_vars_ were for group '_all_' or '_foo_'.

**Comment by bcoca** [comment]
closing this as current versions handle this correctly and there are no plans to release any future 2.1  versions
