### ISSUE TITLE
"Failed to find required executable gem" on eligible/installed gem

### ISSUE THREAD

**Issue by jmvbxx** [ansible/ansible#23468]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
gem module

##### ANSIBLE VERSION
```
ansible 2.2.2.0
```

##### CONFIGURATION
No special configurations

##### OS / ENVIRONMENT
Ansible is being run from Ubuntu 16.04.

##### SUMMARY
I have a task to install the `backup` gem.
```
- name: Install backup gem
  become: yes
  become_user: ubuntu
  gem:
    name: backup
    state: present
```
It generates the following error: `Failed to find required executable gem`. However, `gem list --local` shows that the gem is there and `gem install backup` also works. Ruby version is 2.2.6 and installed via rbenv.

##### EXPECTED RESULTS
It is expected that the gem be installed.

##### ACTUAL RESULTS
```
fatal: [zabbix.guba2.infra]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "build_flags": null, 
            "env_shebang": false, 
            "executable": null, 
            "gem_source": "backup", 
            "include_dependencies": true, 
            "include_doc": false, 
            "name": "backup", 
            "pre_release": false, 
            "repository": null, 
            "state": "present", 
            "user_install": true, 
            "version": null
        }, 
        "module_name": "gem"
    }, 
    "msg": "Failed to find required executable gem"
}
```

**Comment by snowsky** [comment]
Gem is kinda pain, I got this:
```
Building native extensions.  This could take a while...
ERROR:  Error installing backup:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.4.0/gems/atomic-1.1.14/ext
/usr/bin/ruby2.4 -r ./siteconf20170410-11348-111ony2.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.4.0/gems/atomic-1.1.14 for inspection.
Results logged to /var/lib/gems/2.4.0/extensions/x86_64-linux/2.4.0/atomic-1.1.14/gem_make.out
```

**Comment by snowsky** [comment]
What is your env output?

**Comment by jmvbxx** [comment]
The backup gem only works on ruby 2.2.6 which is why I had to install via
rbenv. It dies with 2.4.x.

I tried to overcome this by specifying the become_user in the task. Is this
not a valid workaround?

**Comment by snowsky** [comment]
It could be valid, but considering gem is not friendly with root user, it may complain.

**Comment by jmvbxx** [comment]
Thanks for the feedback. I'll install a system wide ruby 2.2.6 to see if it
helps and avoid the entire rbenv mess.
