### ISSUE TITLE
Problem with python path

### ISSUE THREAD

**Issue by onsails** [ansible/ansible#2349]
Hello.
I am trying to add smartos (solaris-based) host to ansible-managed hosts group. When I try to run playbook I get `invalid output was: /bin/sh[1]: /usr/bin/python: not found [No such file or directory]` error.
I discovered that I can specify python path by `ansible_python_interpreter: /opt/local/bin/python` but I should do it conditional because the host group contains linux-based distros too. I am doing the following:

```

---
- hosts: mygroup
  vars_files:
    - ["vars/$ansible_system/common.yml"]
```

But here I get the same error as above. Obviously ansible needs python to discover `$ansible_system` variable, but I need `$ansible_system` variable to specify python path for ansible... Why doesn't ansible get python from env? I have it in `$PATH`.

**Comment by mpdehaan** [comment]
You should use group_vars for this or set the variable in your inventory file.
