### ISSUE TITLE
fetch module (with old python on remote) reports ok but does nothing

### ISSUE THREAD

**Issue by imstochastic** [ansible/ansible#23501]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
fetch module

##### ANSIBLE VERSION
```
ansible 2.2.3.0 (stable-2.2 7ff9fa52cf) last updated 2017/04/07 11:23:53 (GMT -600)
  lib/ansible/modules/core: (detached HEAD d121211bdf) last updated 2017/03/20 12:38:10 (GMT -600)
  lib/ansible/modules/extras: (detached HEAD eacf36b413) last updated 2017/03/20 12:41:32 (GMT -600)
  config file = /home/brycer/IMSAR/systemTests/ansible/ansible.cfg
  configured module search path = ['./library', '/usr/share/my_modules/']
```
I'm running ansible from a git clone, on the ```stable-2.2``` branch.  ```git describe``` says ```v2.2.3.0-0.1.rc1-2-g7ff9fa5```

Have the same problem on:
```
ansible 2.3.0.0 (stable-2.3 0fe53eda86) last updated 2017/04/11 13:09:06 (GMT -600)
  config file = /home/brycer/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Dec  6 2015, 18:08:32) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
```

##### OS / ENVIRONMENT

ANSIBLE_HOME points at my git clone
ansible.cfg changes several paths (roles_path,library,inventory) to point at my repository for ansible stuff.

Running ansible on ubuntu 14.04
The OS under management is an ancient and untouchable (by me) system that uses a very old python (2.4)

##### SUMMARY
I run a single playbook with a single task, the fetch module.  I would expect it to either download the remote file or give an error (probably saying that a newer python is needed), but I get an OK report status and no file.

##### STEPS TO REPRODUCE
command line:
```
ansible-playbook -i myInventory.ini examplePlaybook.yml
```

examplePlaybook.yml contains:
```
- hosts: ku_davinci
  gather_facts: no
  tasks:
    - name: "download the /etc/issue.net file"
      fetch:
        src: /etc/issue.net
        dest: /tmp/ACoolPlace/issue.net
        flat: True
        fail_on_missing: True
        validate_checksum: False

```

##### EXPECTED RESULTS
I expected to either get an error like "Error: ansible requires the stdlib json or simplejson module, neither was found!", or else to have the file downloaded to /tmp/ACoolPlace/issue.net

##### ACTUAL RESULTS
Instead, I get "success", but the file is not downloaded.  /tmp/ACoolPlace/issue.net not created

```
PLAY [old_machine] **************************************************************

TASK [download the /etc/issue.net file] ****************************************
ok: [old_machine]

PLAY RECAP *********************************************************************
old_machine                 : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by abadger** [comment]
Does that mean that simplejson isn't installed on the remote machine and once you install it, things work?

**Comment by abadger** [comment]
I'm unable to reproduce this.
```
[pts/9@roan /srv/ansible/troubleshooting]$ ansible --version                                              (20:17:21)
ansible 2.2.3.0 (detached HEAD 7ff9fa52cf) last updated 2017/04/12 20:17:05 (GMT -700)
  lib/ansible/modules/core: (detached HEAD cfe3c844f4) last updated 2017/04/11 15:15:11 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 8b78d56a08) last updated 2017/04/11 15:15:11 (GMT -700)
  config file = /srv/ansible/troubleshooting/ansible.cfg
  configured module search path = Default w/o overrides

# Without simplejson installed

[pts/9@roan /srv/ansible/troubleshooting]$ ansible-playbook -i 'rhel5-test,' 23501.yml -vv                (20:17:14)
Using /srv/ansible/troubleshooting/ansible.cfg as config file

PLAYBOOK: 23501.yml ************************************************************
1 plays in 23501.yml

PLAY [rhel5-test] **************************************************************

TASK [download the /etc/issue.net file] ****************************************
task path: /srv/ansible/troubleshooting/23501.yml:4
ok: [rhel5-test] => {"changed": false, "file": "/etc/passwd", "msg": "unable to calculate the checksum of the remote file"}

PLAY RECAP *********************************************************************
rhel5-test                 : ok=1    changed=0    unreachable=0    failed=0   

# With simplejson installed

[pts/9@roan /srv/ansible/troubleshooting]$ ansible-playbook -i 'rhel5-test,' 23501.yml -vv                (20:18:13)
Using /srv/ansible/troubleshooting/ansible.cfg as config file

PLAYBOOK: 23501.yml ************************************************************
1 plays in 23501.yml

PLAY [rhel5-test] **************************************************************

TASK [download the /etc/issue.net file] ****************************************
task path: /srv/ansible/troubleshooting/23501.yml:4
changed: [rhel5-test] => {"changed": true, "checksum": "27e7e151c4b28521e2155f18ff4c54b09ad7cc03", "dest": "/tmp/passwd", "md5sum": "942656dac4ab9cb48ef06ec07c61eea3", "remote_checksum": "27e7e151c4b28521e2155f18ff4c54b09ad7cc03", "remote_md5sum": null}

PLAY RECAP *********************************************************************
rhel5-test                 : ok=1    changed=1    unreachable=0    failed=0   

[pts/9@roan /srv/ansible/troubleshooting]$ ls -al /etc/passwd                                             (20:20:58)
-rw-r--r--. 1 root root 5529 Apr  3 11:33 /etc/passwd
```

I'm targetting a centos5 host which only has python-2.4.3 as its python version.

Is there any other information you can give us to help reproduce this?

needs_info

**Comment by imstochastic** [comment]
The output you have more or less matches what I have.  You verified, I presume, that the file was actually downloaded the first time (without simplejson installed)?  The bug is that I saw that output (i.e. an 'OK' result) but the file did not appear.

I cannot install simplejson on the machine in question, so I'm afraid I'm not much help answering that question.

**Comment by abadger** [comment]
@imstochastic Ah, I see!  I saw that the msg was an error "unable to calculate the checksum of the remote file" and completely missed the status.  I'll look into why that's not returning failed to go along with the error message.

**Comment by abadger** [comment]
Okay, looks like this behaviour is/was intentional and goes back to the beginning of the fetch plugin (it was added in ansible 0.2).  After discussion within the core team, we think it should be changed now as ignore_errors (introduced in Ansible 0.6) should enable the use case.  We're figuring out what sort of deprecation strategy we need to follow when changing this.  We're also leaning towards fail_on_missing being ignored here as being a bug (despite apparently being intended behaviour from its implementation as well).  Working out if we can change that separately or push it into the deprecation cycle too.

**Comment by imstochastic** [comment]
Well, I'm glad if a problem was found.  

I'm really not sure what you mean about fail_on_missing.  I interpret the documentation to mean that if fail_on_missing is set to True, the module should fail if the file to be fetched is not present on the remote machine.  That was not the case in my tests: the file in question was present.

As I understand it, you are saying that this is what is happening:
* the fetch module is trying to compute the checksum of the file in question (even though I explicitly asked it not to)
* computing the checksum fails
* the module reports success even though the checksum failed to compute.

If I understand your last comment correctly, returning success even when the checksum fails was intentional, but the core team now thinks it should fail in that case, and people should use ignore_errors to deal with the error.  This I completely agree with.

I'm still missing a couple of things:
* why the checksum is even being computed, especially since I set the validate_checksum parameter to False?
* it seems like the major problem here is that the file is not being transferred, and that failure to do so constitutes failure of the task.  Is this part of the originally intended behavior you are referring to?

**Comment by abadger** [comment]
Yep, you are correctly interpreting what we're thinking the plan going forward needs to be  If we fail to transfer the file we should fail the task.  In the original design of fetch this was not the behaviour because there were cases where you'd want to ignore those failures.  Ansible now has other ways to ignore failures so we don't have to hardcode that into the module's design

* validate_checksum doesn't control whether checksumming is performed.  It determines whether we perform an integrity check via checksumming after downloading.  We always perform an initial checksum to determine whether the file has already been downloaded or not before starting.  Afterwards it's downloaded, verify-checksum controls whether we checksum the newly downloaded file to make sure it matches the remote file.   A user might want to turn this off if the remote file is a constantly changing file (for instance a heavily updated log file) as taking the initial checksum will race with starting the download process.
* Yes, originally, the module was designed so that the task would never fail.  The stated use case was downloading log files that might only exist on some machines.  We've since added ignore_errors and failed_when which can address the same use case.
