### ISSUE TITLE
user & group libraries: uid/gid should be converted to strings before the execv() call

### ISSUE THREAD

**Issue by rmt** [ansible/ansible#2350]
failed: [testhost001] => {"cmd": ["/usr/sbin/useradd", "-u", 1234, "-g", "user1234", "-m", "user1234"], "failed": true, "rc": 257}
msg: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1362925170.15-231534001182353/user", line 1885, in run_command
    stderr=subprocess.PIPE)
  File "/usr/lib64/python2.6/subprocess.py", line 639, in **init**
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1228, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

The workaround is to quote them in the playbook YAML.

**Comment by mpdehaan** [comment]
Can you please paste your playbook?

**Comment by mpdehaan** [comment]
The reason I'm asking is because in the playbook, if using key=value form, they _are_ strings, so curious how you got into that state.

ansible --version?

I'll verify that we are passing the type in to the module constructors.

**Comment by mpdehaan** [comment]
type casting code pushed, still curious how you got into this position

**Comment by rmt** [comment]
You're right that they would be strings if using the key=value form.  But the "modulename": { "arg1": "value1" } form was also mentioned in the docs, and is my preferred form for clarity (and will be the preferred form if generating playbooks programmatically). YAML parser naturally interprets a number as an int unless quoted.

Thanks for the fix.
