### ISSUE TITLE
ipaddr gateway

### ISSUE THREAD

**Issue by itdependsnetworks** [ansible/ansible#23517]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

filter plugin
ipaddr

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ntc/ansible-modules/']
```

##### SUMMARY

The ipaddr filter plugin seems to use `_gateway_query` in multiple areas. I can't seem to understand what it's intention is.

I can submit a PR and tests, just need to understand what the intention was here. Also would think that first_usable (if different then gw intention), next, and previous should be added to ipaddr.

##### STEPS TO REPRODUCE

Jinja Template

```yaml
{% set ipv4_host = '192.168.0.10/23' %}
ipv4_host = '192.168.0.10/23'
    address/prefix  {{ ipv4_host | ipaddr('address/prefix') }}
    cidr            {{ ipv4_host | ipaddr('cidr') }}
    gateway         {{ ipv4_host | ipaddr('gateway') }}
    gw              {{ ipv4_host | ipaddr('gw') }}
    host/prefix     {{ ipv4_host | ipaddr('host/prefix') }}
    hostnet         {{ ipv4_host | ipaddr('hostnet') }}
    router          {{ ipv4_host | ipaddr('router') }}
```

##### EXPECTED RESULTS

```
ipv4_host = '192.168.0.10/23'
    address/prefix  192.168.0.10/23
    cidr            192.168.0.10/23
    gateway         192.168.0.1/23 (or False??)
    gw              192.168.0.1/23 (or False??)
    host/prefix     192.168.0.10/23
    hostnet         192.168.0.10/23
    router          192.168.0.1/23  (or False??)
```
Not totally sure what should be expected here, the idea that gateway is the IP itself does not seem right. The presumption of first usable while common, is not technically correct. cidr_lookup and gw, gateway, etc... being almost functionally equivalent seems odd as well. Here is some relevant func_map parameters.

```
    query_func_map = {
        '': _empty_ipaddr_query,
        'cidr_lookup': _cidr_lookup_query,
        'gateway': _gateway_query,
        'gw': _gateway_query,
        'host/prefix': _gateway_query,
        'hostnet': _gateway_query,
        'router': _gateway_query,
```

##### ACTUAL RESULTS

```
ipv4_host = '192.168.0.10/23'
    address/prefix  192.168.0.10/23
    cidr            192.168.0.10/23
    gateway         192.168.0.10/23
    gw              192.168.0.10/23
    host/prefix     192.168.0.10/23
    hostnet         192.168.0.10/23
    router          192.168.0.10/23
```

**Comment by privateip** [comment]
@itdependsnetworks good question and I think there needs to be some clarification here as to which filters are doing which function.  That said, I think we need to do a bit of a review of the current ipaddr.py implementation to better document the filters available, identify filters that need to be added and also which filters should be removed (if any).  I'm going to add this to the weekly IRC meeting for discussion and reflag this issue as a 2.4 deliverable.

**Comment by itdependsnetworks** [comment]
Thanks, added this PR, since to me it seemed wrong: https://github.com/ansible/ansible/pull/23526

**Comment by itdependsnetworks** [comment]
Fixing and keeping backwards compatibility is mutually exclusive, will close issue.

**Comment by fholzer** [comment]
In case anyone finds this issue and is still wondering how to get the gateway IP, this works for me:

    some_address_prefix | ipaddr('address/prefix') | ipaddr('1') | ipaddr('address')

For `some_address_prefix=10.2.3.4/16` this would result in `10.2.0.1`

**Comment by mmellin** [comment]
Doesn't the following assume that the GW is the first IP?

`some_address_prefix | ipaddr('address/prefix') | ipaddr('1') | ipaddr('address')`

Technically speaking, a gateway can be any host within the host range, although is typically either the first or last.  How does one obtain a list of usable host IP addresses with the current code and guarantee that each are not the GW IP given an arbitrary GW?

**Comment by fholzer** [comment]
>Doesn't the following assume that the GW is the first IP?

Correct. The example also shows that. Nevertheless I though it's worth posting this because it's the most common setup anyway, and likely to help folks looking for this.

**Comment by mmellin** [comment]
While I always appreciate examples, I'm simply pointing out that this just shows how to get the first address of a range, not the gateway.  My point is there is currently no way to get or set the "gateway".  That functionality is missing.  IMHO, a user should be able to set their gateway and the array of hosts IPs should not contain this IP (or it should be flagged).

**Comment by itdependsnetworks** [comment]
Most of what you are looking for should be covered in https://github.com/ansible/ansible/pull/26566

**Comment by mmellin** [comment]
While not ideal, it looks like I found my answer, so I'll post it here in case it may help others. (used with ansible 2.7)

### Goal
To create a list of IPs which do not overlap with an arbitrary gateway.

### Starting variables
I have two vars: `cidr_block: 192.168.0.0/24` and `gw: 192.168.1.2`

### Working Code

(not as pretty as Paltrow and works well for a small use case)
```yaml
- name: Create initial IP list
  set_fact:
    host_ips: >-
      [
      {% for instance_num in range(3) %}
        "{{ cidr_block | ipaddr('net') | ipaddr(instance_num + 1) | ipaddr('address') }}"
        {% if not loop.last %},{% endif %}
      {% endfor %}
      ]

- name: Verify selected IPs and GW do not overlap and recreate list
  set_fact:
    host_ips: >-
      [
      {% set vars = {'count': 0} %}
      {% for ip in host_ips %}
        {% if ip == vmware_vm_gateway %}
          {% if vars.update({'count': 1}) %}{% endif %}
          "{{ ip | ipmath(vars.count) }}"
          {% if not loop.last %},{% endif %}
        {% else %}
          "{{ ip | ipmath(vars.count) }}"
          {% if not loop.last %},{% endif %}
        {% endif %}
      {% endfor %}
      ]
  when: gw in host_ips
```

### Result

```
TASK [vmware_dynamic_inventory : Create initial IP list] **************
ok: [localhost] => {
    "ansible_facts": {
        "host_ips": [
            "10.87.92.1",
            "10.87.92.2",   <<<< Overlaps with GW
            "10.87.92.3"
        ]
    },
    "changed": false
}
Tuesday 05 March 2019  08:18:40 -0800 (0:00:00.082)       0:00:00.336 *********


TASK [vmware_dynamic_inventory : Verify selected IPs and GW do not overlap and recreate list] ***************
ok: [localhost] => {
    "ansible_facts": {
        "host_ips": [
            "10.87.92.1",
            "10.87.92.3",   <<<< No longer overlaps
            "10.87.92.4"
        ]
    },
    "changed": false
}
Tuesday 05 March 2019  08:18:41 -0800 (0:00:00.079)       0:00:01.546 *********
```
