### ISSUE TITLE
azure_rm_securitygroup_facts: Random TLS/SSL CERTIFICATE_VERIFY_FAILED errors on calls to azure api via a proxy

### ISSUE THREAD

**Issue by awalker125** [ansible/ansible#23518]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
azure_rm_securitygroup_facts

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
All default

##### OS / ENVIRONMENT
Redhat Linux 3.10.0-514.2.2.el7.x86_64

##### SUMMARY
Random TLS/SSL CERTIFICATE_VERIFY_FAILED errors on calls to azure api via a proxy.

##### STEPS TO REPRODUCE

Various playbooks which call the azure api are suffering random/intermittent CERTIFICATE_VERIFY_FAILED errors. I have created a simple play that calls azure_rm_securitygroup_facts 50 times as below and when I run this I get a failure rate of about 1 in 25.

Does ansible use connection pooling or anything else that could explain this. We are behind a firewall and use an explicit proxy setting http_proxy and https_proxy env variables before invoking ansible.

```
- hosts: localhost
  connection: local
  tasks:
   - name: get facts for security group
     azure_rm_securitygroup_facts:
      resource_group: test-rg
     register: result
     with_sequence: start=0 end=50
```

##### EXPECTED RESULTS
Retrieve security group fact from the azure api

##### ACTUAL RESULTS
Intermittent CERTIFICATE_VERIFY_FAILED errors on calls to azure api

```
"Traceback (most recent call last):\n  File \"/tmp/ansible_OyZENy/ansible_module_azure_rm_securitygroup_facts.py\", line 286, in <module>\n    main()\n  File \"/tmp/ansible_OyZENy/ansible_module_azure_rm_securitygroup_facts.py\", line 283, in main\n    AzureRMSecurityGroupFacts()\n  File \"/tmp/ansible_OyZENy/ansible_module_azure_rm_securitygroup_facts.py\", line 236, in __init__\n    facts_module=True)\n  File \"/tmp/ansible_OyZENy/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 173, in __init__\n  File \"/usr/lib/python2.7/site-packages/msrestazure/azure_active_directory.py\", line 403, in __init__\n    self.set_token()\n  File \"/usr/lib/python2.7/site-packages/msrestazure/azure_active_directory.py\", line 434, in set_token\n    raise_with_traceback(AuthenticationError, \"\", err)\n  File \"/usr/lib/python2.7/site-packages/msrest/exceptions.py\", line 50, in raise_with_traceback\n    raise error\nmsrest.exceptions.AuthenticationError: , SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

**Comment by nitzmahone** [comment]
As we don't make the connections directly (they're made by the Azure Python SDK), this really isn't an Ansible bug- I'd suggest you might have better luck filing a bug at https://github.com/Azure/azure-sdk-for-python.

**Comment by awalker125** [comment]
Thanks. I've opened it over there at https://github.com/Azure/azure-sdk-for-python/issues/1089
