### ISSUE TITLE
Feature Request: ignore_when

### ISSUE THREAD

**Issue by sonjz** [ansible/ansible#23538]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
Error Handling

##### ANSIBLE VERSION

```
ansible 2.3.0.0
```

##### SUMMARY

I found that `ignore_errors` is a nice to have, but fairly broad as it ignores all errors.
But often, I run a `command` that return an acceptable error.

Example, for arguments sake, lets take `mkdir /tmp/test`.
- `mkdir: cannot create directory ‘/tmp/test’: File exists` is an a acceptable error
- `mkdir: cannot create directory ‘tmp/test’: Permission denied` is not.

`change_when` and `fail_when` work well when you know what you want to change/fail on, but not when you know what you want to ignore, and allow the normal flow for success/failure.

I was hoping that `ignore_when` could be a good addition to address this.
````
- command: mkdir /tmp/test
  register: result
  ignore_when: 'File exists' in result
````

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment]
Why not ```failed_when: result|failed and 'File exists' not in result```?

**Comment by sonjz** [comment]
Thanks!
Works for me:
````
- command: mkdir /tmp/test
  register: result
  failed_when: result|failed and 'File exists' in result.stderr
````
