### ISSUE TITLE
Ansible ignores errors in inventory file

### ISSUE THREAD

**Issue by exowaucka** [ansible/ansible#23537]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

No idea.  Is there a list of components somewhere?

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /Users/alexwauck/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

ansible.cfg:
```
[ssh_connection]
control_path = /tmp/%%C
```

##### OS / ENVIRONMENT
I am running Ansible on OS X El Capitan.

##### SUMMARY
I had an inventory file (inventory.txt) that looked like this:

```
[group1]
host1
host2
host3

[group2]
host4
host5
host6

[group3]
host7
host8
host9

[all:children]
[group1]
group2
group3
```

See the problem?  I accidentally put brackets around `group1` in the list of children for the `all` group.  So, I then ran something like this:

```
ansible-playbook -K -s -i inventory.txt /path/to/playbook.yaml
```

The playbook had this as its hosts specification:

```yaml
hosts: group3
```

This failed because group3 failed to resolve.  No surprise, seeing as "group3" is not a valid hostname.  Ansible gave no indication that there was anything wrong with the inventory file.  Once I removed the incorrect brackets, the `ansible-playbook` command worked.

##### STEPS TO REPRODUCE

Steps to reproduce listed above.  I do not believe it matters what's in the playbook, aside from the `hosts` line.  The playbook I used looked like this (partially redacted but structurally identical):

```yaml
---
- hosts: 'group3'
  become: true
  become_method: 'sudo'
  become_user: 'root'
  tasks:
    - name: 'Create someguy'
      user:
        name: 'someguy'
        groups: 'sudo'
        password: '*'
        shell: '/bin/bash'
    - name: 'Authorize SSH keys'
      authorized_key:
        user: 'someguy'
        key: 'ssh-rsa blah blah blah'

```

##### EXPECTED RESULTS

I expected `ansible-playbook` to either run without errors or complain about the inventory file being malformed.  (I'm not certain that the playbook was actually malformed from Ansible's point of view.  If it wasn't, then I can't see how the typo affected group3.  If it was, then shouldn't Ansible have complained?)

##### ACTUAL RESULTS

```
$ ansible-playbook -vvvv -K -s -i inventory.txt playbooks/add_user.yaml
Using /Users/alexwauck/.ansible.cfg as config file
SUDO password: 
Loading callback plugin default of type stdout, v2.0 from /Users/alexwauck/.venvs/ansible/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: add_user.yaml *****************************************************
1 plays in playbooks/add_user.yaml

PLAY [group3] *****************************************************************

TASK [setup] *******************************************************************
Using module file /Users/alexwauck/.venvs/ansible/lib/python2.7/site-packages/ansible/modules/core/system/setup.py
<group3> ESTABLISH SSH CONNECTION FOR USER: None
<group3> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/tmp/%C group3 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1492018443.88-103920245895354 `" && echo ansible-tmp-1492018443.88-103920245895354="` echo $HOME/.ansible/tmp/ansible-tmp-1492018443.88-103920245895354 `" ) && sleep 0'"'"''
fatal: [group]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: OpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /Users/alexwauck/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/tmp/ad7b9da7b8dba88ca22db3e7bcc636050b30e798\" does not exist\r\nssh: Could not resolve hostname group3: nodename nor servname provided, or not known\r\n", 
    "unreachable": true
}
	to retry, use: --limit @/Users/alexwauck/ansible-stuff/playbooks/add_user.retry

PLAY RECAP *********************************************************************
group3                    : ok=0    changed=0    unreachable=1    failed=0   
```

**Comment by sivel** [comment]
The reason you did not get an error with the inventory file is that it is a perfectly legitimate inventory file.

In your example, do to the typo, you created a new group called `group1` with hosts of `group2` and `group3`

The fact that you did not include anything as part of `[all:children]` does not impact the ability to parse, you simply are telling it that there are no child groups of `[all]`, however `[all:children]` shouldn't even be required, as all the hosts already exist in `all` implicitly.

**Comment by mattparkes** [comment]
I agree with **sivel** -- what you did was define an empty group.

The only way this exact set of circumstances could be caught is by alerting that **group1** was defined twice.

**Comment by bcoca** [comment]
Closing as per above, this is not an actual error to Ansible as that is a perfectly valid config, just not what you meant to do.

**Comment by exowaucka** [comment]
@bcoca I don't understand why this messed up `group3`, though.  I would understand if `all` stopped working, but why did Ansible act like `group3` was a hostname?

**Comment by bcoca** [comment]
Because in the `[group1]` section, you write hostnames, you happen to have group2 and group3 there, which are valid hostnames. `[all:children]` is an empty section.

**Comment by exowaucka** [comment]
@bcoca So, if I use `foobar` as a hostname in a group and as a group name, Ansible will silently ignore the group called `foobar`?

**Comment by bcoca** [comment]
Not ignore as the group will be in `group_names` and `groups` and variables will be inherited accordingly, but it will be confusing (in 2.3 this triggers a warning) when targeting in `hosts:`.
