### ISSUE TITLE
ansible-vault decrypt does no longer read from stdin

### ISSUE THREAD

**Issue by nblock** [ansible/ansible#23567]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vault

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /home/user/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.11 (default, Mar 20 2016, 15:46:50) [GCC 5.3.0]

```

##### CONFIGURATION
```
[defaults]
vault_password_file = my_vault_key
```

##### OS / ENVIRONMENT
Linux

##### SUMMARY
```ansible-vault decrypt``` before 2.3 used to work with data from stdin. Ansible 2.3 does no longer read data from stdin. ```ansible-vault encrypt``` seems to be affected likewise.

##### STEPS TO REPRODUCE
```
$ cat host_vars/host.example.com/vault.yml | ansible-vault decrypt
ERROR! [Errno 2] No such file or directory: u'/home/user/ansible/-'
```
Running ```ansible-vault decrypt host_vars/host.example.com/vault.yml``` works as expected.

##### EXPECTED RESULTS
The decrypted content of vault.yml on stdout.

##### ACTUAL RESULTS
```
ERROR! [Errno 2] No such file or directory: u'/home/user/ansible/-'
```

**Comment by alikins** [comment]
looks like 6c6b647182f2dc8fa254e8b1855c3bc646d742cf busted this.  That commit uses os.path.realpath() to find the target of symlinks, but it also applies CWD to the path. For stdin case, the filename is just '-' and os.path.realpath(filename) expands that to '/home/user/wherever/-' and code deeper in vault is expecting just '-'.

Working on fix (likely just only using realpath on symlinks)
