### ISSUE TITLE
group_vars are not correctly selected when running a play

### ISSUE THREAD

**Issue by wimnat** [ansible/ansible#23562]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible group_vars

##### ANSIBLE VERSION
2.3

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
NA

##### SUMMARY
I have an inventory with three groups.  Each group has a group_vars file.  The group_vars files share common keys (variable names) but different values.

For example,
group_vars/account1 has
`account_id: 1`

group_vars/account2 has
`account_id: 2`

When i run my playbook, I always get the group_vars from the last group defined in the inventory, rather than the group I specified in the play.

##### STEPS TO REPRODUCE
Run this gist - https://gist.github.com/wimnat/ca17177c9e46a07d6d3fc9285c24b243

The script is passed the group name 'account2' but the playbook will output the var from account3

##### EXPECTED RESULTS
I would expect a message of `Account ID: this_is_from_account2`

##### ACTUAL RESULTS
I get a message of `Account ID: this_is_from_account3`

**Comment by bjolivot** [comment]
Localhost is in multiple groups on same level of precedence, for me it's not a bug, your variable is erased 2 times.

**Comment by wimnat** [comment]
I would agree with you if it was a host var but it's not. It's a group var. Why would you ever include vars from a group you haven't referenced?

**Comment by nitzmahone** [comment]
This is by design- inventory group vars are always loaded and resolved "as defined", not "as referenced" (ie, the value will always be the same regardless of which group you're referencing in the play). `group_vars` are applied in alphabetical order by the group name, so the value you see for a given host will be the one in the "highest" alphabetical group (`account3` in your example).

**Comment by bcoca** [comment]
groups are 'properties' of hosts, for example, i'm male and a programmer, I don't stop being one or the other just because you chose me from a pool of 'males' or 'programmers'.

**Comment by wimnat** [comment]
Hmm but males wear blue coats, except when they're programming when they wear red coats. Loading by reference seems like it would be a common requirement. 

Anywho, if it doesn't work that way, any suggestions on how to implement my expected behaviour? An include_vars perhaps with a with_first_found perhaps?

**Comment by bjolivot** [comment]
You could include_vars or choose different groups

**Comment by wimnat** [comment]
Thanks 👍
