### ISSUE TITLE
keytool behaves different when invoked using ansible local_action

### ISSUE THREAD

**Issue by mohtashims** [ansible/ansible#23565]
Issue Type
Bug Report

COMPONENT NAME
local_action

ANSIBLE VERSION
ansible 2.1.0.0

I am using ansible roles called "mgr"

/tmp/roles/mgr/tasks/spull.yml:17 is below:

```
 17 - name: ==== Run script renew.sh on LOCAL hosts with ID 'uxbea' ====
 18
 19   local_action: "shell {{ ROLE_PATH }}mgr/files/renew.sh {{ DOMAIN_NAME }} {{ LOCAL_CERT_HOME }}dump chdir={{ ROLE_PATH }}mgr/files/    " 
```

more /tmp/roles/mgr/files/renew.sh

```
echo "CERT RENEWAL:"$1".jks"

echo "keytool -genkey -alias $1 -keyalg RSA -sigalg SHA256withRSA -keystore $2"/"$1.jks -keysize 2048"

keytool -genkey -alias $1 -keyalg RSA -sigalg SHA256withRSA -keystore $2"/"$1.jks -keysize 2048 < /dev/tty

```
Running ansible roles as below gives error 

```
ansible-playbook -vvv site.yml -i /web/hostfiles/host.txt

TASK [mgr : ==== Run script install_cert.sh on LOCAL hosts at location=/tmp/roles/ with ID 'user1' ====] ***
task path: /tmp/roles/mgr/tasks/spull.yml:17
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ansibleuser
<localhost> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'

changed: [remote.com -> localhost] => {"changed": true, "cmd": "/tmp/roles/mgr/files/renew.sh mydom /tmp/moht/dump", "delta": "0:00:58.055556", "end": "2017-04-13 03:41:54.653376", "invocation": {"module_args": {"_raw_params": "/tmp/roles/mgr/files/renew.sh mydom /tmp/moht/dump", "_uses_shell": true, "chdir": "/tmp/roles/mgr/files/", "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 0, "start": "2017-04-13 03:40:56.597820", "stderr": "Enter keystore password:  Keystore password is too short - must be at least 6 characters\nEnter keystore password:  Keystore password is too short - must be at least 6 characters\nEnter keystore password:  Keystore password is too short - must be at least 6 characters\nToo many failures - try later", "stdout": "CERT RENEWAL:mydom.jks\nkeytool -genkey -alias mydom -keyalg RSA -sigalg SHA256withRSA -keystore /tmp/moht/dump/mydom.jks -keysize 2048", "stdout_lines": ["CERT RENEWAL:mydom.jks", "keytool -genkey -alias mydom -keyalg RSA -sigalg SHA256withRSA -keystore /tmp/moht/dump/mydom.jks -keysize 2048"], "warnings": []}

TASK [mgr : include] ***************************************************
```
Running this command from renew.sh without ansible is interactive and desirable 

```
keytool -genkey -alias $1 -keyalg RSA -sigalg SHA256withRSA -keystore $2"/"$1.jks -keysize 2048 < /dev/tty

Output:
keytool -genkey -alias mydom -keyalg RSA -sigalg SHA256withRSA -keystore /tmp/moht/dump/mydom.jks -keysize 2048

Enter keystore password:
Re-enter new password:
What is your first and last name?
  [Unknown]:  test me
What is the name of your organizational unit?
  [Unknown]:  testing
What is the name of your organization?
  [Unknown]:  tester
What is the name of your City or Locality?
  [Unknown]:
```
but when the same is triggered using ansible it does not prompt the same way as it does above.

Can you please help explain and fix ?

**Comment by nitzmahone** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by mohtashims** [comment]
I did post it to mailing list: https://groups.google.com/forum/#!forum/ansible-project 12 hrs back but it did not even show up. 

I see it now https://groups.google.com/forum/#!topic/ansible-project/zeC9kr9kRXg

but there is no response.

I also suspect it to be a bug however, i m not sure

**Comment by mohtashims** [comment]
Unfortunately, the issue i reported was not fixed here : https://groups.google.com/forum/#!topic/ansible-project/zeC9kr9kRXg

and this thread is also closed without any solution. 

So the problem persists.
