### ISSUE TITLE
is defined no longer works with registered variables of skipped plays

### ISSUE THREAD

**Issue by larsf** [ansible/ansible#23588]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible
##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /opt/mapr/installer/etc/ansible.cfg
  configured module search path = [u'/opt/installer/ansible/playbooks/library/', u'']
  python version = 2.7.13 (default, Apr 13 2017, 03:14:43) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
ansible: python script exited with 0
```

##### CONFIGURATION

[defaults]
command_warnings=False
force_handlers=True
forks=20
gathering=smart
host_key_checking=False
poll_interval=10
remote_tmp=/tmp
retry_files_enabled=False

[paramiko_connection]
#pty=False
record_host_keys=False

[ssh_connection]
control_path=%(directory)s/%%h-%%r
#pipelining=True
scp_if_ssh=True
#ssh_args=-o ControlMaster=auto -o ControlPersist=10m

[privilege_escalation]
become_method=su
##### OS / ENVIRONMENT

CentOS 7.2
##### SUMMARY

"is defined" no longer works correctly on registered variables of plays that are skipped - works in 2.2.0.0

##### STEPS TO REPRODUCE

```yaml
---

- name: Test defined
  hosts: all
  serial: "{{ serial|default(20) }}"
  gather_facts: False

  vars:
    varOne: "thisIsVarOne"

  tasks:
  - shell: "ls -l /tmp/fileDoesNotNeedToExist"
    when:  varTwo is defined and varTwo.rc == 0
    register: cluster_conf

  - shell: "ls -l /tmp/lars1"
    when: cluster_conf is defined and cluster_conf.rc == 0
```

##### EXPECTED RESULTS

PLAY [Test defined] ************************************************************

TASK [command] *****************************************************************
skipping: [localhost]

TASK [command] *****************************************************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0   

[root@qa-node92 ~]# ansible-playbook -vvvv -k -ilocalhost, /tmp/test_defined.yml
Using /etc/ansible/ansible.cfg as config file
SSH password: 
Set default localhost to localhost
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: test_defined.yml *****************************************************
1 plays in /tmp/test_defined.yml

PLAY [Test defined] ************************************************************

TASK [command] *****************************************************************
task path: /tmp/test_defined.yml:20
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional check failed", 
    "skipped": true
}

TASK [command] *****************************************************************
task path: /tmp/test_defined.yml:24
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional check failed", 
    "skipped": true
}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0   
##### ACTUAL RESULTS

```
Set default localhost to localhost
Loading callback plugin default of type stdout, v2.0 from /opt/mapr/installer/build/installer/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: test_defined.yml **********************************************************************************************************************
1 plays in /tmp/test_defined.yml

PLAY [Test defined] *****************************************************************************************************************************
META: ran handlers

TASK [command] **********************************************************************************************************************************
task path: /tmp/test_defined.yml:20
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}

TASK [command] **********************************************************************************************************************************
task path: /tmp/test_defined.yml:24
fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "The conditional check 'cluster_conf is defined and cluster_conf.rc == 0' failed. The error was: error while evaluating conditional (cluster_conf is defined and cluster_conf.rc == 0): 'dict object' has no attribute 'rc'\n\nThe error appears to have been in '/tmp/test_defined.yml': line 24, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - shell: \"ls -l /tmp/lars1\"\n    ^ here\n"
}

PLAY RECAP **************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by sfrolich** [comment]
2.2.1.0 does not display the problem but 2.2.2.0 and 2.3.0.0 do.

**Comment by larsf** [comment]
This may just be a case of ansible 2.2.1 and 2.3 actually doing the correct thing:
cluster_conf is defined (even if the play was skipped, and does contain (in both 2.2.0.0 and 2.3 case)
ok: [localhost] => {
    "cluster_conf": {
        "changed": false, 
        "skip_reason": "Conditional check failed", 
        "skipped": true
    }
}

but somehow ansible 2.2.0.0 evaluated cluster_conf.rc == 0 as false when cluster_conf.rc was undefined, instead throwing an error.  Changing the conditional to :
(not cluster_conf | skipped) and cluster_conf | succeeded
works
