### ISSUE TITLE
Playbook includes failing on non existing playbook since 2.2

### ISSUE THREAD

**Issue by user140547** [ansible/ansible#23601]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
Playbook includes

##### ANSIBLE VERSION

```
ansible 2.2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

no changes

##### OS / ENVIRONMENT

N/A

##### SUMMARY

In Ansible 2.1, a playbook include on a non-existing playbook did not fail when using a condition when: false. Although I am not sure if this was ever intended to be working, it seems to be a breaking change. 

Apart from that, it would add more flexibility if with_fileglob was allowed for playbook includes:
```yaml
- include: "{{item}}"
  with_fileglob: "dir/*.yml"
```
##### STEPS TO REPRODUCE

```yaml
---
- name: test optional playbook
  hosts: localhost
  gather_facts: false

- include: not_existing_playbook.yml
  when: false

```

##### EXPECTED RESULTS

Using ansible 2.1.2.0
```
[root@localhost optionalplaybook]# ansible-playbook -vvv test.yml
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

skipping playbook include 'not_existing_playbook.yml' due to conditional test failure

PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [test optional playbook] **************************************************

PLAY RECAP *********************************************************************
```

##### ACTUAL RESULTS

Using Ansible 2.2 (also tried 2.3)

```
[root@localhost optionalplaybook]# ansible-playbook -vvv test.yml
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! the file_name '/home/vagrant/testnew/optionalplaybook/not_existing_playbook.yml' does not exist, or is not readable

```

**Comment by snowsky** [comment]
I saw some codes were introduced and caused the difference of behaviors.

**Comment by snowsky** [comment]
This commit should fix the issue e3a6accc1d25298c981bdef4e5412e3573730d0c, but I don't see it in 2.2 and 2.3

**Comment by snowsky** [comment]
Actually 2.2 and 2.3 include this commit but this commit 5b87951d6c99b515ceb07674cd862a2375328c7a removed the fix again.

**Comment by user140547** [comment]
It seems that this bug also reproducible on 2.4 RC1 (using import_playbook does not changed its behaviour, just removing the deprecation warning)

```
[root@localhost optionalplaybook]# ansible-playbook test.yml
 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available

[DEPRECATION WARNING]: 'include' for playbook includes. You should use 'import_playbook' instead.
This feature will be removed
in version 2.8. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ERROR! Unable to retrieve file contents
Could not find or access '/home/vagrant/testnew/optionalplaybook/not_existing_playbook.yml'
```

**Comment by samdoran** [comment]
This is working as designed. Playbook imports (and old stlye `include` of playbooks) are static. They will fail in the playbook file does not exist.

For further help with the issue, please reach out on IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
