### ISSUE TITLE
meta: reset_connection not working

### ISSUE THREAD

**Issue by alapidas** [ansible/ansible#23621]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`meta` module's `reset_connection`

##### ANSIBLE VERSION

```
[vagrant@localhost infra-bootstrap]$ ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Sep  5 2016, 02:30:38) [GCC 4.8.5 20150623 (Red Hat 4.8.5-9)]
```

##### OS / ENVIRONMENT

OEL7

##### SUMMARY

Using the `meta: reset_connection` instruction appears to be broken under very simple use case.

##### STEPS TO REPRODUCE

Using a very simple playbook (below), the `meta: reset_connection` instruction stack traces (command below under `ACUAL RESULTS`)

simple `test.yml`:
```yaml
---
- hosts: all
  tasks:
  - meta: reset_connection
```

inventory:
```
# Generated by Vagrant

node01
core ansible_connection=local

[core]
core

[development]
core
```

##### EXPECTED RESULTS

The ssh connection to get reset successfully

##### ACTUAL RESULTS

Ansible stack traces

```
[vagrant@localhost infra-bootstrap]$ ansible-playbook --limit=core --inventory-file=/tmp/vagrant-ansible/inventory -vvv test.yml
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: Found both group and host with same name: core


PLAYBOOK: test.yml ***************************************************************************************************************************************************
1 plays in test.yml

PLAY [all] ***********************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<core> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<core> EXEC /bin/sh -c 'echo ~ && sleep 0'
<core> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp/ansible-tmp-1492207079.55-247174731112807 `" && echo ansible-tmp-1492207079.55-247174731112807="` echo /home/vagrant/.ansible/tmp/ansible-tmp-1492207079.55-247174731112807 `" ) && sleep 0'
<core> PUT /tmp/tmpbuhXwS TO /home/vagrant/.ansible/tmp/ansible-tmp-1492207079.55-247174731112807/setup.py
<core> EXEC /bin/sh -c 'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1492207079.55-247174731112807/ /home/vagrant/.ansible/tmp/ansible-tmp-1492207079.55-247174731112807/setup.py && sleep 0'
<core> EXEC /bin/sh -c '/usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1492207079.55-247174731112807/setup.py; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1492207079.55-247174731112807/" > /dev/null 2>&1 && sleep 0'
ok: [core]
META: ran handlers
ERROR! Unexpected Exception: 'NoneType' object has no attribute 'reset'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 109, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 153, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 284, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 221, in run
    results.extend(self._execute_meta(task, play_context, iterator, host))
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 908, in _execute_meta
    connection.reset()
AttributeError: 'NoneType' object has no attribute 'reset'
```

**Comment by snowsky** [comment]
@ansibot I can reproduce the issue.

**Comment by snowsky** [comment]
If the robot can accept some command from someone to know if this is an issue can be reproduced...

**Comment by alikins** [comment]
Looks like this will fail if the config for 'transport = smart'. Using 'ssh' or 'paramiko' works.

Looks like there 'connection_loader.get' fails for 'smart' and ends up returning None and causing the error.

**Comment by snowsky** [comment]
@alikins yes you are right.

**Comment by piotrsmolinski** [comment]
I am also affected by this. The context is common with related issues. I try installing docker and then use it with the same account as used for connection.

There are three issues happening:
1. The connection of type "smart" is not converted to "ssh" in the meta
https://github.com/ansible/ansible/blob/v2.3.1.0-0.2.rc2/lib/ansible/plugins/strategy/__init__.py#L903
2. The connection parameters are not propagated
3. The ssh stop command is not checked for failure
https://github.com/ansible/ansible/blob/v2.3.1.0-0.2.rc2/lib/ansible/plugins/connection/ssh.py#L817

In the last one the result status and command output are discarded. The play should fail if the status is 
not 0 and the stdout/stderr should be reported as failure cause. I tested it with some additional log statements and it came clear that the target host and most likely port are not passed to the ssh command.

**Comment by Sispheor** [comment]
This should be fixed in ansible 2.3..2.0?

**Comment by liyaka** [comment]
Still have this issues with ansible 2.4.1 - in which version is it fixed?

**Comment by epu** [comment]
If this is still open, what version of this ticket is the one to track for 2.4 and 2.5?

**Comment by soulawaker** [comment]
Using ansible 2.6.5 with python 3.5.2 , I tried below codes. It seems that still not work properly.
```yaml
---
- hosts: all
  tasks:
  - name: try reset_connection
    meta: reset_connection
```
The results does not show its task message. Is it normal for meta module?
```yaml
---
PLAY [all] *****************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************
ok: [10.30.1.4]

PLAY RECAP *****************************************************************************************************************
10.30.1.4                  : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by BarbzYHOOL** [comment]
It does not show and it doesn't seem to do anything @soulawaker 

I compared `ps aux | grep ssh` before and after but it's still the same

Can someone explain us if it's working or not? @bcoca maybe?
