### ISSUE TITLE
ansible 2.3.0.0 cannot install on OS X Yosemite

### ISSUE THREAD

**Issue by misterT1958** [ansible/ansible#23629]
- Bug Report

##### COMPONENT NAME
sudo -H pip install ansible --upgrade

##### ANSIBLE VERSION
ansible 2.2.1.0
config file =

##### CONFIGURATION
none

##### OS / ENVIRONMENT
Mac OS X Yosemite version 10.10.5

##### SUMMARY
cannot install ansible 2.3.0.0

##### STEPS TO REPRODUCE
Successfully installed pip-9.0.1
tw2@warroom3:~/Downloads> sudo pip install --upgrade ansible
The directory '/Users/tw2/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/tw2/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting ansible
  Downloading ansible-2.3.0.0.tar.gz (4.3MB)
    100% |████████████████████████████████| 4.3MB 352kB/s
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 412, in run_egg_info
    self.setup_py, self.name,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/Library/Python/2.7/site-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/Library/Python/2.7/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/Users/tw2/Library/Python/2.7/lib/python/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)

##### EXPECTED RESULTS
I expected to upgrade to Ansible 2.3.0.0

##### ACTUAL RESULTS
see output above, seems there is an incompatibility between ansible 2.3 and pip and python2.7
I have re-installed python2.7, re-installed pip, backtracked to setuptools.py 33.1.1; nothing has worked yet.  Error at end of traceback is always "TypeError: __call__() takes exactly 2 arguments (1 given)"

**Comment by misterT1958** [comment]
dropped back to setuptools 33.1.1, got this:
Installing collected packages: setuptools, ansible
  Found existing installation: setuptools 33.1.1
    Uninstalling setuptools-33.1.1:
      Successfully uninstalled setuptools-33.1.1
  Found existing installation: ansible 2.2.1.0
    Uninstalling ansible-2.2.1.0:
      Successfully uninstalled ansible-2.2.1.0
  Running setup.py install for ansible ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-JLnnWo/ansible/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-UQ38dR-record/install-record.txt --single-version-externally-managed --compile:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Library/Python/2.7/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/Library/Python/2.7/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
        import packaging.requirements
      File "/Library/Python/2.7/site-packages/packaging/requirements.py", line 59, in <module>
        MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
    TypeError: __call__() takes exactly 2 arguments (1 given)

    ----------------------------------------
  Rolling back uninstall of ansible
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-JLnnWo/ansible/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-UQ38dR-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-JLnnWo/ansible/

**Comment by jonhadfield** [comment]
originalTextFor suggests it's an issue with your installed version of pyparsing.
You can check installed version with this:
`python -c 'import pyparsing, setuptools;print(pyparsing.__version__)'`
If it's not the latest, try updating to 2.2.0 then re-installing
`pip install pyparsing==2.2.20`

**Comment by misterT1958** [comment]
Jon, doesn't look like pyparsing is the problem:
tw2@warroom3:~/Library/Caches/pip> python -c 'import pyparsing, setuptools;print(pyparsing.__version__)'
2.2.0

**Comment by jonhadfield** [comment]
It might be pip is using a different set of libraries. To rule this out, trying installing ansible under virtualenv:
```
pip install virtualenv
virtualenv ansible
source ansible/bin/activate
pip install ansible
```

**Comment by misterT1958** [comment]
Jon, thanks for your help.  Before I saw your last suggestion, I found this (excerpted below) on https://github.com/nylas/sync-engine/issues/432.    This worked for me:

> I tried with Python 2.7.13 and even with Python 3.4 (this doesn't work for a variety of other reasons) - to no avail. What finally did fix it for me is this:
> 
> In file /usr/local/lib/python2.7/dist-packages/packaging/requirements.py, line 59 is this one:
> 
> MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
> I changed it to
> 
> MARKER_EXPR = originalTextFor(MARKER_EXPR(""))("marker")
> And that was it - everything went through after that.          

Thanks for your help!
Tony
