### ISSUE TITLE
issue - but intended?

### ISSUE THREAD

**Issue by skvidal** [ansible/ansible#2363]
If there is an ansible.cfg in the cwd ansible-playbook will try to use it. That could, potentially, be dangerous as it could point an unsuspecting user in a /tmp dir at a set of library modules and/or inventory that would steal certain information.

I know it's intended, probably for git-checkout use but it seems like this could be an issue for some folks pretty easily

**Comment by bcoca** [comment]
We can create a no-local-cfg-override var you can stash in a higher lvl
config.

Brian Coca

**Comment by mpdehaan** [comment]
It's intended to be true for the playbook directory (basedir), but I think it's reasonable to make it not work for cwd.

I don't like the idea of another config option that someone wouldn't set by default and am fine with changing this.

**Comment by mpdehaan** [comment]
no updates on this, I am assuming it was current playbook dir as discussed, not CWD

**Comment by skvidal** [comment]
yes - you're correct to close it. I tested it 2 weeks back - after we had lunch - but I forgot to close the issue. Sorry about that, day job got in the way :-)
