### ISSUE TITLE
AnsibleUndefinedVariable error when trying to access variables from included template files

### ISSUE THREAD

**Issue by fnkr** [ansible/ansible#23643]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

template

##### ANSIBLE VERSION

```
ansible 2.2.2.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Default w/o overrides

##### OS / ENVIRONMENT

macOS 10.12.4

##### SUMMARY

Variables set in included template files cannot be accessed within the original template file.

##### STEPS TO REPRODUCE

I made a sample playbook to demonstrate the issue: https://gist.github.com/3e3e57141a675100ea9320d3646ef2b3
```
git clone https://gist.github.com/3e3e57141a675100ea9320d3646ef2b3.git
cd 3e3e57141a675100ea9320d3646ef2b3
./run-playbook
```

##### EXPECTED RESULTS

The variable set in `template_macro.j2` should be available within `template.j2` and the playbook should finish w/o any errors.

##### ACTUAL RESULTS

The playbook fails because `foo` is undefined.

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'foo' is undefined"}
```

**Comment by alikins** [comment]
> The variable set in template_macro.j2 should be available within template.j2 and the playbook should finish w/o any errors.

Was this working in earlier versions?

**Comment by alikins** [comment]
Does the 'include' need to be an 'import'? ala http://jinja.pocoo.org/docs/2.9/templates/#import

**Comment by fnkr** [comment]
> Does the 'include' need to be an 'import'? ala http://jinja.pocoo.org/docs/2.9/templates/#import

Yes, this works. Thanks! (See also #3779.)
```
{% from 'template_macro.j2' import foo with context %}
```
