### ISSUE TITLE
initrd value of ansible_cmdline is not correct when boot in UEFI mode

### ISSUE THREAD

**Issue by gzm55** [ansible/ansible#23647]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`setup` module

##### ANSIBLE VERSION

```
~$ ansible --version
ansible 2.3.0.0
  config file = /home/james/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Ubuntu 17.04, boot in UEFI mode

##### SUMMARY
when booting via UEFI, the initrd= specification uses EFI-style backslashes (`\`) and identifies the initial RAM disk relative to the ESP's root, but backslashes are not encoded in the fact variable `ansible_cmdline.initrd`.

##### STEPS TO REPRODUCE
1. boot a linux machine in efi mode
2. run `cat /proc/cmdline`
3. run `ansible localhost -m setup -a filter=ansible_cmdline`

##### EXPECTED RESULTS
`ansible_cmdline.initrd` should be a EFI-style path.

##### ACTUAL RESULTS
```
~$ cat /proc/cmdline 
initrd=\70ef65e1a04a47aea04f7b5145ea3537\4.10.0-19-generic\initrd root=UUID=50973b75-4a66-4bf0-9764-2b7614489e64 ro quiet
~$
~$
~$
~$ ansible -i inv localhost -m setup -a filter=ansible_cmdline
localhost | SUCCESS => {
    "ansible_facts": {
        "ansible_cmdline": {
            "initrd": "70ef65e1a04a47aea04f7b5145ea35374.10.0-19-genericinitrd", 
            "quiet": true, 
            "ro": true, 
            "root": "UUID=50973b75-4a66-4bf0-9764-2b7614489e64"
        }
    }, 
    "changed": false
}
```

**Comment by snowsky** [comment]
It seems it is different on my VM:
```
root@ubuntu-xenial:/home# ansible localhost -m setup -a filter=ansible_cmdline
localhost | SUCCESS => {
    "ansible_facts": {
        "ansible_cmdline": {
            "BOOT_IMAGE": "/boot/vmlinuz-4.4.0-72-generic",
            "console": "ttyS0",
            "ro": true,
            "root": "UUID=e12e46d9-06c9-4a64-a7b3-60e24b062d90"
        }
    },
    "changed": false
}
root@ubuntu-xenial:/home# cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-4.4.0-72-generic root=UUID=e12e46d9-06c9-4a64-a7b3-60e24b062d90 ro console=tty1 console=ttyS0
```

**Comment by gzm55** [comment]
Hi @snowsky,
your VM use efi to load grub then kernel is loaded by grub, is it?

My kernel is loaded using efi stub and gummiboot/systemd-boot, see http://www.rodsbooks.com/efi-bootloaders/efistub.html .

efi stub loads gummiboot:
```
~$ efibootdump Boot0000
Boot0000: * gummiboot PciRoot(0x0)/Pci(0x1f,0x2)/Sata(1,65535,0)/HD(1,MBR,0x90,0x800,0x32000)/File(\EFI\gummiboot\gummibootx64.efi)
```

gummiboot loads kernel:
```
~$ cat /boot/efi/loader/entries/70ef65e1a04a47aea04f7b5145ea3537-4.10.0-19-generic.conf 
title Ubuntu 17.04
version 4.10.0-19-generic
machine-id 70ef65e1a04a47aea04f7b5145ea3537
options root=UUID=50973b75-4a66-4bf0-9764-2b7614489e64 ro quiet
linux /70ef65e1a04a47aea04f7b5145ea3537/4.10.0-19-generic/linux
initrd /70ef65e1a04a47aea04f7b5145ea3537/4.10.0-19-generic/initrd
```

**Comment by snowsky** [comment]
I don't think ansible's outputs will be in EFI-style path format.

**Comment by gzm55** [comment]
but `/proc/cmdline` is in EFI-style, and `ansible_cmdline` corrupts the `initrd` value.

I think `get_cmdline()` in `facts.py` does not escape backslashes before call `shlex.split()`, and
```python
 for piece in shlex.split(data.replace("\\", "\\\\")):
```

this escaping works for me. The `shlex.split` is for parsing the form of  `key="value with space"`, and assumes that the `data` should be a valid raw shell string, but a backslash violates this assumption.

**Comment by snowsky** [comment]
Got double backslashes then:
```
localhost | SUCCESS => {
    "ansible_facts": {
        "ansible_cmdline": {
            "initrd": "\\70ef65e1a04a47aea04f7b5145ea3537\\4.10.0-19-generic\\initrd",
            "quiet": true,
            "ro": true,
            "root": "UUID=50973b75-4a66-4bf0-9764-2b7614489e64"
        }
    },
    "changed": false
}
```

**Comment by snowsky** [comment]
If this works for you, you may also want to use:
```
for piece in shlex.split(data, posix=False)
```
got the same output as above.

**Comment by gzm55** [comment]
the double backslashes are the ansible formatting style for the single backslash.

`posix` parameter of `shlex.split`  [is added in python 2.6](https://docs.python.org/2/library/shlex.html), but `setup` module should be compatible with python 2.4 on Managed machines right now (for ansible <2.3).

**Comment by alikins** [comment]
devel branch/2.4 will require python 2.6 for modules, so adding posix=False for the shlex.split() would be okay.  

Doing better escaping on /proc/cmdline contents in facts.py seems like a more general fix though.

**Comment by snowsky** [comment]
Ok, let me put a PR to address this issue.

**Comment by gzm55** [comment]
PR works for me, thanks.
So this fix will only go into ansible 2.4?

**Comment by snowsky** [comment]
np, yes, it will be after approved.

**Comment by gundalow** [comment]
@snowsky Thanks for the PR

Can people please review https://github.com/ansible/ansible/pull/23672 so we can look at getting that merged
