### ISSUE TITLE
Spurious warnings about jinja2 in 'when' statements with string literals

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#23658]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- core

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

Ansible now warns about jinja2 delimiters in `when:` statements.  However this warning should not be generated if the jinja2 delimiters are nested inside a quoted string literal as part of a larger expression, as it's quite reasonable to include jinja2 there.

##### STEPS TO REPRODUCE

~~~
- name: check installed nfdump version
  shell: nfdump -V
  register: nfdump_check
  check_mode: no
  ignore_errors: True
  changed_when: False

- include: build_nfdump.yml
  when: '"Version: {{nfdump_version}}" not in nfdump_check.stdout'
~~~

##### EXPECTED RESULTS

Task to run quietly

##### ACTUAL RESULTS

Second task generates this warning:

~~~
[WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: "Version: {{nfdump_version}}" not in nfdump_check.stdout
~~~

**Comment by sivel** [comment]
Your `when` statement should be adjusted to:

```
when: '"Version: " ~ nfdump_version not in nfdump_check.stdout'
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
