### ISSUE TITLE
Setting content in copy module broken with check_invalid_arguments in file module

### ISSUE THREAD

**Issue by skinp** [ansible/ansible#2365]
The `content` argument (following #2296) is unkown to the file module. And since we now have check_invalid_arguments = True (since #2294) in the file module, we get an error when copy calls file (in cases where local_md5 == remote_md5)...

To reproduce:

```
$ ansible localhost -m copy -a "content=test dest=/tmp/test"
localhost | success >> {
    "changed": true,
    ...
}

$ ansible localhost -m copy -a "content=test dest=/tmp/test"
localhost | FAILED >> {
    "failed": true,
    "msg": "unsupported parameter for module: content"
}
```

I guess a quick fix would be to add content to FILE_COMMON_ARGUMENTS in module_common.py, but I'm not sure it's the best solution since for now, content is just used in the copy module. Although, in the long term, I suppose content could also be useful in the other file modules, esp. template.

What do you think? Any better way this could be fixed? Obviously, I can take care of the fix...

**Comment by mpdehaan** [comment]
It seems we want to just disable file argument checking for now.

I'll do that.

**Comment by mpdehaan** [comment]
actually, I just went ahead and added 'content' to the list of FILE_COMMON_ARGUMENTS.   It seems non-damaging because it's not documented that it actually does anything for file by itself (which it does not).  But yes, I agree we could just as easily make it work for the others.

(Closing this since the error has gone way now)

**Comment by mpdehaan** [comment]
If you want to make template take "content" and maybe "file" also take content (like copy) I'm totally open to that.

Let me know!

Thanks!

**Comment by skinp** [comment]
Yes, I was actually planning on adding "content" support to at least template. Should be a simple addition...

**Comment by mpdehaan** [comment]
That would be great.

We've had a few request for inline templates!

On Tue, Mar 12, 2013 at 8:50 AM, Patrick Pelletier <notifications@github.com
