### ISSUE TITLE
Add Timeout for scripts using script module.

### ISSUE THREAD

**Issue by rahul8590** [ansible/ansible#23676]
##### ISSUE TYPE

 - Feature Idea

Add Hard timeout for ansible script module . 

##### COMPONENT NAME

script module

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Jul 13 2015, 12:05:58) [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Currently, the script module only remotely executes the script. It ll be nice to have an option to specify a hard timeout of the script. That way, you can avoid issues when the script hangs and get stuck forever. 

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by fridim** [comment]
Thanks @rahul8590  for the RFE. Just a few remarks before others step in about the RFE itself.

First, i think the simplest (and clean) way is to have the script handle the timeout itself.

That said, there are workarounds:

- use copy + command
  It allows you to use async http://docs.ansible.com/ansible/playbooks_async.html and then set the TTL of your script.

  (You cannot use async directly with script, see https://github.com/ansible/ansible/issues/20232 )

  The flaw with async here is that polling adds a (small) delay if your script usually executes quickly.
  
  If sync is mandatory, you can always use the timeout shell command :
  ```
  - command: timeout 20 /some/script.sh
  ```
  
- run script in background and then use <code>wait_for</code> which supports timeout, waiting for (for example) the presence of a file that would assert script finished properly.

**Comment by rahul8590** [comment]
My use case is slightly different. Many times the script contains network calls  etc, which may  take forever to execute. The `script` module , places the onus on script writer to handle timeouts. Its good to have a fail fast approach. Here are the following issues with the workarounds 

1. `copy + command`  will copy the script to remote host and then, execute. (Correct me if I am wrong) Again, the onus is on the playbook writer to purge the script file after executing in remote node. 

2. `wait_for`  seems a bit hacky. It is useful, if you are expecting / not expecting an event to happen. 

Also many times, we need to execute a binary script where I dont have control on its code. It ll be easier to have a timeout in the script module, in order to fail fast.

**Comment by sivel** [comment]
This issue has been resolved by https://github.com/ansible/ansible/pull/69284
