### ISSUE TITLE
gather other hosts'facts even if --limit is specified

### ISSUE THREAD

**Issue by bruceauyeung** [ansible/ansible#23687]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /root/kda/.kda/ansible.cfg
  configured module search path = ['./library']
```

##### OS / ENVIRONMENT

centos 7
##### STEPS TO REPRODUCE

1. user have configured ansible to enable fact caching
~~~
[defaults]
gathering = smart
fact_caching = jsonfile
fact_caching_connection = /path/to/cachedir
fact_caching_timeout = 86400
# seconds
~~~
2. user have a playbook to ping all hosts(host1,host2,host3) in inventory file. in this playbook, there is a ping task with `gather_facts:yes` explicitly configured. and there is another task in which user access `hostvars[any host expect host1][a variable name]`

3. user run ansible-playbook with `--limit host1` , in this case, ansible will not gather facts for host2,host3 even if json cache is cleared.

##### EXPECTED RESULTS
i expect  when `gathering = smart` is configured and with  `gather_facts:yes` explicitly configured in task,when user access other hosts' hostvars(host2,host3), ansible will be smart enough to gather other hosts' facts even if `--limit host1` is configured

**Comment by bcoca** [comment]
this is not something you want by default, some people don't need those facts, others have very slow hosts, others have a LOT of hosts. To let you control this we added `delegate_facts`  http://docs.ansible.com/ansible/playbooks_delegation.html#delegated-facts
