### ISSUE TITLE
Ansible-galaxy ignores --force

### ISSUE THREAD

**Issue by hoall** [ansible/ansible#23696]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible-galaxy

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/me/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

roles_path    = ~/.ansible/roles

##### OS / ENVIRONMENT

N/A

##### SUMMARY

"ansible-galaxy install" ignores the -f/--force option.

##### STEPS TO REPRODUCE

I have a requirements.yml file. My command is ansible-galaxy install -f -r requirements.yml. I would expect that all existing roles will get replaced.

```yaml

```

##### EXPECTED RESULTS

All roles in the requirements file should be replaced.

##### ACTUAL RESULTS

```
ansible-galaxy install -f -vvvv -r requirements.yml
Using /home/me/.ansible.cfg as config file
Opened /home/me/.ansible_galaxy
found role {'scm': 'git', 'src': 'https://******* } in yaml file
**** is already installed, skipping.
```

**Comment by mscherer** [comment]
Isn't it related to https://github.com/ansible/ansible/pull/23391 ?

**Comment by hoall** [comment]
In some way. A role isn't erased with any command though. 2.3.0 doesn't erase any role data even with the force option. Also, I don't believe it's a good idea to hold even versioned numbers. Not that I don't get the point of doubling downloads, but as long as there's no way to handly multiple role versions -- force is the only option to delete a role version and replace it with another one from devel. Another option would be something like --renew-roles or so.

The point here is simply that I can't replace my role with a newer version because force does not delete them when present ( I don't use versions).

**Comment by abadger** [comment]
@hoall can you test with https://github.com/ansible/ansible/pull/23391 applied?  Looking at the code, I think that it will fix this issue as well (and I've pinged the dev that handles galaxy issues to have a look at merging #23391)

needs_info

**Comment by hoall** [comment]
Sorry I'm not in the office the next days. Got sick and have to stay in bed.

Am 19.04.2017 6:40 nachm. schrieb "Toshio Kuratomi" <
notifications@github.com>:

**Comment by hoall** [comment]
@abadger The commit fixed the problem. Thank you very much! :+1:
