### ISSUE TITLE
AWS Batch support - Should I submit a PR?

### ISSUE THREAD

**Issue by jonmer85** [ansible/ansible#23706]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
AWS Batch

##### SUMMARY
Is anyone working on an AWS Batch (Compute Environment, Job Queue, Job Definition) ansible module? I am about half-way done with writing my own module following a pattern similar to the lambda_policy module. I am happy to submit a PR to the community when I am done if that is desired?

**Comment by snowsky** [comment]
+1

**Comment by dougalb** [comment]
+1

Ping me if you have any questions. I'm the Product Manager for AWS Batch. dougalb at amazon

**Comment by s-hertel** [comment]
+1
I don't think there are any other PRs floating around for that. Thanks!

**Comment by jonmer85** [comment]
Great, I am happy to see there is some interest. Is there a certain branch I should throw my new files into when I create my PR?

**Comment by s-hertel** [comment]
@jonmer85 It doesn't really matter what your branch is named, but the pull request should be to merge it into the devel branch.

**Comment by jonmer85** [comment]
Ok got it. Thanks!

**Comment by jonmer85** [comment]
I submitted a PR for AWS Batch support - https://github.com/ansible/ansible/pull/24402

**Comment by ryansb** [comment]
Closing this as the PR is clearly submitted, and thank you much!
