### ISSUE TITLE
Improve integration test coverage of become methods

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#23712]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
become

##### ANSIBLE VERSION

```
devel
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Per https://github.com/ansible/ansible/pull/23710 we lost `su` functionality in 2.3

We don't explicitly test `su` as a become method.

We should extend our integration test coverage here.  One problem is we will need to connect as an unprivileged user, so that we can `su` to another user, to test prompt matching.

##### STEPS TO REPRODUCE
N/A

**Comment by sivel** [comment]
Another place where improving testing here could have caught an issue: https://github.com/ansible/ansible/issues/25722

**Comment by sivel** [comment]
To expand on what problems we need to resolve to test this properly, we run the tests from within the containers as root.  We cannot use sudo or su as root to get prompts.  As a result, we effectively skip all prompt matching functionality.

We would somehow need to create an unpriv user, and reconnect to the container the tests are running from (or to some other external host) and exercise the become methods.

**Comment by nitzmahone** [comment]
If we categorize those tests as `destructive`, commenting out the pam_rootok.so auth line from /etc/pam.d/su will cause su to prompt root on most distros- certainly enough of them that we could be reasonably sure `su` is working properly in most places.

**Comment by samdoran** [comment]
This is waiting on split controller in our CI.

**Comment by mattclay** [comment]
Closing since this is being actively worked on.
