### ISSUE TITLE
ignore_errors fails to ignore when non existent file is used with $FILE

### ISSUE THREAD

**Issue by leucos** [ansible/ansible#2372]
The following never executes the last play :

```
- hosts: 192.168.33.10

  tasks:
    - action: copy src=/tmp/nonexistent dest=/tmp/file
      ignore_errors: yes

    - action: shell "echo $FILE(~/.ssh/id_rsa.pub)"
      ignore_errors: yes 

    - action: shell "it failed but I'm alive and kickin' !"
```

gives :

```
$ ansible -m ping 192.168.33.10

192.168.33.10 | success >> {
    "changed": false, 
    "ping": "pong"
}

$ ansible-playbook -i pb.yml

PLAY [all] ********************* 

GATHERING FACTS ********************* 
ok: [192.168.33.10]

TASK: [copy src=/tmp/nonexistent dest=/tmp/file] ********************* 
failed: [192.168.33.10] => {"failed": true}
msg: could not find src=/tmp/nonexistent
...ignoring

TASK: [shell "echo $FILE(~/.ssh/id_rsa.pub)"] ********************* 
fatal: [192.168.33.10] => /home/test/.ssh/id_rsa.pub does not exist

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************* 
192.168.33.10                  : ok=2    changed=0    unreachable=1    failed=0    
```

As a side note, it also says `unreachable=1` while host is reachable.

**Comment by mpdehaan** [comment]
Thanks, ignore errors was mainly about the return code of the task, not so much the syntax errors, when originally written.   Though I don't see why this shouldn't also be made to work.  Will take a look.

**Comment by leucos** [comment]
Thanks. I stumbled on this when trying to send DSA key with authorized_key module, and then fallback on RSA. Quite easy to circumvent with copy, bit a bit more verbose. Having 'classic fail' with PIPE, FILE, etc... would be great.

**Comment by mpdehaan** [comment]
first_availlable_file has a fallback that may be useful.

"unreachable" is just the type of "I got an exception, did not make communication in this pass", so it was an unreachable event.   Just a slightly weird name in this case :)

**Comment by leucos** [comment]
Ah yes first_availlable_file, never looked at that very much. I just tried, but it fails when used inside $FILE (doesn't seem to be expanded): 

```
- hosts: 192.168.33.10

  tasks:
    - action: shell "echo $FILE($item)"
      first_available_file:
        - ~/.ssh/id_dsa.pub
        - ~/.ssh/id_rsa.pub
```

gives :

```
PLAY [192.168.33.10] ********************* 

GATHERING FACTS ********************* 
ok: [192.168.33.10]

TASK: [shell "echo $FILE($item)"] ********************* 
fatal: [192.168.33.10] => ./$item does not exist

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************* 
192.168.33.10                  : ok=1    changed=0    unreachable=1    failed=0   
```

Am I stumbling on something else ?

**Comment by mpdehaan** [comment]
Yes, it's not meant to be used with $FILE either, I meant more for your
copy example.

**Comment by mpdehaan** [comment]
FYI, this does work:

```
---
- hosts: all
  tasks:
     - copy: dest=/tmp/wherever
       ignore_errors: True
       first_available_file:
          - /tmp/dne__splat
          - /tmp/dne__splat2
```

Looking into whether making the other work is doable, I'm guessing a conditional try/except would be doable.

**Comment by mpdehaan** [comment]
also $FILE includes things inline, so it's not the same thing as what you had asked for anyway :)

**Comment by mpdehaan** [comment]
Yeah, this is about ignoring module errors.  I'm not inclined to make it ignore exceptions at a higher level.  It seems like it would do too much.

I think you would want to write an alternative file.py lookup plugin that just returned <FILE NOT FOUND> as a string when the file did not exist.
