### ISSUE TITLE
Variable precedence with Ansible 2.3 is incorrect?

### ISSUE THREAD

**Issue by sidcarter** [ansible/ansible#23746]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

core/ variable precedence

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /root/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

No changes to default config.

##### OS / ENVIRONMENT

Tested on Mac OS X:
```shell
$ uname -a
Darwin MacBox.local 16.6.0 Darwin Kernel Version 16.6.0: Wed Apr 12 21:00:08 PDT 2017; root:xnu-3789.60.20.0.1~3/RELEASE_X86_64 x86_64
```
and on CentOS 7.3
```shell
$ uname -a
Linux CentosBox 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)
```

##### SUMMARY

Following variable precedence here - http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

Host variables don't take precedence over group variables in Ansible 2.3.0 and is inconsistent with documentation too.

##### STEPS TO REPRODUCE

With Ansible 2.2.2.0:

```shell
$ ansible --version
ansible 2.2.2.0
  config file = /root/.ansible.cfg
  configured module search path = Default w/o overrides
$
$ ansible -i inventory/test 10.45.16.51 -m shell -a 'echo "{{main_group_var}}"'
10.45.16.51 | SUCCESS | rc=0 >>
cilantro
```

With Ansible 2.3.0

```shell
$ ansible --version
ansible 2.3.0.0
  config file = /root/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
$
$ ansible -i inventory/test 10.45.16.51 -m shell -a 'echo "{{main_group_var}}"'
10.45.16.51 | SUCCESS | rc=0 >>
bananas
```

Host Inventory
```yaml
[all]

[local]
127.0.0.1 ansible_connection=local ht_name=local

[test-server]
10.45.16.51

[test-server:vars]
main_group_var="cilantro"
```
Group Variables
```yaml
# environment details
main_group_var: "bananas"
```

##### EXPECTED RESULTS

When using variables, the host variables should take precedence and the output should be `cilantro`
```shell
$ ansible -i inventory/test 10.45.16.51 -m shell -a 'echo "{{main_group_var}}"'
10.45.16.51 | SUCCESS | rc=0 >>
cilantro
```

##### ACTUAL RESULTS

The actual result is `bananas` which is incorrect

```shell
$ ansible -i inventory/test 10.45.16.51 -m shell -a 'echo "{{main_group_var}}"'
10.45.16.51 | SUCCESS | rc=0 >>
bananas
```

**Comment by evrardjp** [comment]
[test-server:vars] is assigning vars to the test-server group. Group vars.  So these are defined twice. What if main_group_var="cilantro" is set on the same line as 10.45.16.51 ?

**Comment by sivel** [comment]
This variable precedence seems correct, based on the documentation at http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

It specifies:

```
role defaults
inventory INI or script group vars
inventory group_vars/all
playbook group_vars/all
inventory group_vars/*
playbook group_vars/*
```

Based on that, the `main_group_var` defined in your hosts file, for the `test-server` group, has a lower precedence than `main_group_var` that you have defined in `group_vars`

**Comment by sivel** [comment]
I think the confusion comes from this statement you made above:

> Host variables don't take precedence over group variables in Ansible 2.3.0 and is inconsistent with documentation too.

You did not create any host variables.  In both cases, you created group variables.

You created a group called `test-server` with one host called `10.45.16.51` and then you applied a var called `main_group_var` to the `test-server` group.

If you wanted to apply a host var to `10.45.16.51` you would need to do:

```
[test-server]
10.45.16.51 main_group_var="cilantro"
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by sidcarter** [comment]
So, does that mean the bug actually is in 2.2.2.0 and everything prior? @sivel

**Comment by sivel** [comment]
Please see https://groups.google.com/d/msg/ansible-devel/gBMKLk33FhQ/IUY7XIjOBwAJ for a full explanation of the change.
