### ISSUE TITLE
Add <net_os>_config filter

### ISSUE THREAD

**Issue by itdependsnetworks** [ansible/ansible#23751]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

new plugin
##### ANSIBLE VERSION

```
N/A
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A

##### SUMMARY

With the removal of the offline method noted here: https://github.com/ansible/ansible/issues/22619
It would be nice to re-introduce the feature in the form of a filter. Had a brief side conversation with @privateip and should be possible to use same functions as the modules use to get the config difference between an offline file, and new config to be pushed. 

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```
{{ existing_config | ios_offline(old_config ) }}

results
line vty 0 4
 exec-timeout 60 0
```

**Comment by privateip** [comment]
~~resolved_by_pr #24216~~

**Comment by privateip** [comment]
resolved_by_pr ##26565
