### ISSUE TITLE
Ansible cant differentiate if IPs or DNS addresses of multiple hosts are same and port numbers are different.

### ISSUE THREAD

**Issue by asad-urrahman** [ansible/ansible#23754]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

Host file configuration `/etc/ansible/hosts` 

**Issue:** Ansible cant differentiate if IPs or DNS addresses of multiple host are same and port numbers are different. 

##### ANSIBLE VERSION
```shell
ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

`ROUTER_PUBLIC_IP` is IPv4, for security reasons i have not not exposed real IP.

```shell
sudo cat /etc/ansible/hosts
[myhosts]
ROUTER_PUBLIC_IP ansible_port=2000 ansible_user=me
ROUTER_PUBLIC_IP ansible_port=3000 ansible_user=me
```

##### OS / ENVIRONMENT
Ubuntu 16.04 64 bit

##### SUMMARY

My hosts are installed behind NAT, so to access from Public Internet i have done port forwarding configuration on my router. Host file configuration `/etc/ansible/hosts` is configured in such a way that Hosts have Same IP but different Port numbers. Theoretically SSH connections are differentiated via port numbers. 

In my case,  when i disconnect one host (port 3000) one, Ansible stops and throws an error rather than preceding to check other host. While if i connect or disconnect other host (port 2000) than Ansible works fine but doesn't shows that one host is unreachable or connected, Ansible completely ignore first host entry.

**So far I have discovered** 

- If i exchange entries lines in `/etc/ansible/hosts` file than than accessible hosts are also switched, it mean Ansible works only for last entry when IP/DNS address are same. 

Modified host file:
```shell
sudo cat /etc/ansible/hosts
[myhosts]
ROUTER_PUBLIC_IP ansible_port=3000 ansible_user=me
ROUTER_PUBLIC_IP ansible_port=2000 ansible_user=me
```
- Or instead of `ROUTER_PUBLIC_IP` for one host i use DNS address , than both hosts are reachable.

  ```
  sudo cat /etc/ansible/hosts
  [myhosts]
  ROUTER_PUBLIC_IP ansible_port=2000 ansible_user=me
  mydns.mysite.com ansible_port=3000 ansible_user=me
  ```

  while both `ROUTER_PUBLIC_IP` and `mydns.mysite.com` are for same routers, both represent the same router.

##### STEPS TO REPRODUCE

Following play-book i have used for connection testing:

```yaml
---
- name: Check Ansible connectivity to all hosts
  hosts: myhosts
  gather_facts: false
  max_fail_percentage: 0
  tasks:
    - action: ping
      register: cmd_output

    - name: debug ...
      debug: var=cmd_output
```

##### EXPECTED RESULTS

**NOTE:** In this case the connected host is last entry in `/etc/ansible/hosts` , so Ansible should ping one host and show UNREACHABLE 1st host .

```shell

PLAY RECAP *********************************************************************
ROUTER_PUBLIC_IP              : ok=2    changed=0    unreachable=1    failed=0

```

##### ACTUAL RESULTS

**Without Debug:**

```shell
PLAY [Check Ansible connectivity to all hosts]*************************************

TASK [ping] ***********************************************************************
ok: [ROUTER_PUBLIC_IP]

TASK [debug ...] ********************************************************************
ok: [ROUTER_PUBLIC_IP] => {
    "changed": false,
    "cmd_output": {
        "changed": false,
        "ping": "pong"
    }
}

PLAY RECAP *************************************************************************
ROUTER_PUBLIC_IP              : ok=2    changed=0    unreachable=0    failed=0
```
**With Debug:** 

```shell
ansible-playbook -vvv connectionCheck.yml
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: connectionCheck.yml ***************************************************
1 plays in connectionCheck.yml

PLAY [Check Ansible connectivity to all hosts] ***************************************
META: ran handlers

TASK [ping] **************************************************************************
task path: /home/aaaa/connectionCheck.yml:7

  ....SOME OUTPUT INTENTIONALY REMOVED FROM HERE....
  
ok: [ROUTER_PUBLIC_IP] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": null
        }
    },
    "ping": "pong"
}

TASK [debug ...] ********************************************************************
task path: /home/aaaa/connectionCheck.yml:10
ok: [ROUTER_PUBLIC_IP] => {
    "changed": false,
    "cmd_output": {
        "changed": false,
        "ping": "pong"
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP **************************************************************************
ROUTER_PUBLIC_IP              : ok=2    changed=0    unreachable=0    failed=0

```

**Comment by abadger** [comment]
The host file for multiple logical hosts accessed via the same ip should look like this:

```
[myhosts]
symbolic_name1 ansible_host=ROUTER_PUBLIC_IP ansible_port=3000 ansible_user=me
symbolic_name2 ansible_host=ROUTER_PUBLIC_IP ansible_port=2000 ansible_user=me
```

The first field is a name for the host.  It must be unique.  Using ansible_host allows you to then map the name to the ip or dns address that you wish.

If you need more help on this, please reach out on the IRC channel or mailing list.  I'll paste the information on those below

List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by bottlelee** [comment]
I had a similar problem.

My hosts file is like below:

```
[hd3]
hd3-master ansible_host=20.20.20.3
hd3-node1 ansible_host=20.20.20.4
hd3-node3 ansible_host=20.20.20.6

[hd4]
hd4-master ansible_host=20.20.20.4
hd4-node1 ansible_host=20.20.20.5
hd4-node2 ansible_host=20.20.20.6
hd4-node3 ansible_host=20.20.20.7
```

As you can see, the 'hd3-node3' and 'hd4-node2' have same internal IP. And, they're behind different jumper, through the same public IP but different port. The paths look like below:
 
```
                                   |---> port1 ---> hd3-jumper ---> hd3-node3
controler ---> ROUTER_PUBLIC_IP ---|
                                   |---> port2 ---> hd4-jumper ---> hd4-node2
```


In group_vars/hd3, it is

`ansible_ssh_common_args: '-o ProxyCommand="ssh -p 22222 -W %h:%p -q ROUTER_PUBLIC_IP"'`

In group_vars/hd4, it is

`ansible_ssh_common_args: '-o ProxyCommand="ssh -p 33333 -W %h:%p -q ROUTER_PUBLIC_IP"'`

When I check the hostname with

`ansible nodes -m command -a 'hostname'`

I've got these output:

```
hd3-node3 | SUCCESS | rc=0 >>
hd3-node3

hd4-node2 | SUCCESS | rc=0 >>
hd3-node3
```

I hope this can be fixed ASAP.
