### ISSUE TITLE
localhost in multiple groups gets all variables in each group.  How can I limit this?

### ISSUE THREAD

**Issue by snoby** [ansible/ansible#23762]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
localhost and variables

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb 22 2017, 05:33:31) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION

```
[defaults]
inventory = ./inventory/
retry_files_enabled = False



callback_plugins = callbacks/
host_key_checking = False
nocows =1
#make ansible fast

#cache some settings
gather = smart
fact_caching_timeout = 86400
fact_caching = jsonfile
fact_caching_connection = .tmp/ansible_fact_cache

#parallelism
forks = 20
```

##### OS / ENVIRONMENT

running on MacOS Sierra managing kubernetes cluster via kubectl

##### SUMMARY
So I use ansible to send jobs to my k8s cluster via the kubectl command on my local machine.  I have my inventory file setup so that each cluster is it's own group and each cluster is basically a connection to localhost .
```
# Inventory File
#
[east.k.tropo.com]
localhost              ansible_connection=local

[east2.k.tropo.com]
localhost              ansible_connection=local

[k8s.int.ops.tropo.com]
localhost              ansible_connection=local

[k8s.k.dub.tropo.com]
localhost              ansible_connection=local

#[test.c.tropo.com]
#localhost              ansible_connection=local


```
Then in my group_vars directory I have a different file with the name of my group from my inventory file that holds all the different variables for each cluster.

```
ls group_vars/
all/                        east2.k.tropo.com            k8s.int.ops.tropo.com.yaml  k8s.k.dub.tropo.com         test.c.tropo.com.yaml
```
My problem is that I get all the variables from all the different groups even though when I operate a playbook I'm operating on only one group at a time such as:
`ansible-playbook -vv create.yaml -l k8s.int.ops.tropo.com --tags ingress-generate-only`

##### STEPS TO REPRODUCE
I run a template file that looks like below and I can see all the different variables from my different groups as all available:
```
Module Variables ("vars"):
--------------------------------
{{ vars | to_nice_json }}

Environment Variables ("environment"):
--------------------------------
{{ environment | to_nice_json }}

GROUP NAMES Variables ("group_names"):
--------------------------------
{{ group_names | to_nice_json }}

GROUPS Variables ("groups"):
--------------------------------
{{ groups | to_nice_json }}

HOST Variables ("hostvars"):
--------------------------------
{{ hostvars | to_nice_json }}
```

##### EXPECTED RESULTS

I think the reason I'm seeing this is because i'm using localhost in every single group.  I would expect that I would only have the variables defined for that group.

##### ACTUAL RESULTS

```

```

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by snoby** [comment]
@sivel  - so it's not a bug that variables defined in one group are available in another group?

**Comment by sivel** [comment]
In your example `localhost` is in all groups.  As variables and hosts are concerned, group variables are merged down onto the hosts themselves for the groups they are in.  So localhost, gets all of the vars from all the groups it is part of.

From the documentation at http://docs.ansible.com/ansible/intro_inventory.html#splitting-out-host-and-group-specific-data

> If the host is named ‘foosball’, and in groups ‘raleigh’ and ‘webservers’, variables in YAML files at the following locations will be made available to the host:
> 
> /etc/ansible/group_vars/raleigh # can optionally end in '.yml', '.yaml', or '.json'
> /etc/ansible/group_vars/webservers
> /etc/ansible/host_vars/foosball

**Comment by snoby** [comment]
So this nice guy on StackOverflow provided a work around:
http://stackoverflow.com/questions/43504595/ansible-variables-shared-with-multiple-groups-if-inventory-is-only-localhost
I had actually posted twice over the span of a month to the google group and had posted in the IRC room a couple of times.  Github was my last official ansible resource I could go to...
