### ISSUE TITLE
Issue in connecting to VM via ansible host file

### ISSUE THREAD

**Issue by pspravin** [ansible/ansible#23767]
##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /u02/ansible/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### STEPS TO REPRODUCE

```
ansible -m ping all

```

##### ACTUAL RESULTS

```

```

**Comment by pspravin** [comment]
I was able to resolve the issue, thanks!

**Comment by Akasurde** [comment]
@pspravin Can you please add debugging steps for posterity?

**Comment by pspravin** [comment]
@Akasurde - I had to add ansible_user=<VM username> to the inventory host file.
