### ISSUE TITLE
lineinfile with state=absent will delete all lines matching regexp

### ISSUE THREAD

**Issue by dimitrijer** [ansible/ansible#23786]
##### ISSUE TYPE
 - Documentation Report

Note: I'm not sure whether this is desired behavior or a bug. Depending on this, this is a documentation report or a bug report.

##### COMPONENT NAME
lineinfile

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /Users/dimitrijer/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 20 2016, 10:00:44) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
fact_caching enabled:
```
fact_caching = jsonfile
fact_caching_connection = /Users/dimitrijer/.ansible/facts_cache.json
fact_caching_timeout = 86400
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
lineinfile module deletes *all* matching lines when `regexp` and `state=absent` are specified. Documentation hints that `regexp` should remove _the_ matching line (a single line):
> For state=absent, the pattern of the line to remove. Uses Python regular expressions; see http://docs.python.org/2/library/re.html.

##### STEPS TO REPRODUCE
Let's say I wanted to clear the last line matching `1` from file with the following contents (`/etc/nginx/conf.d/test.conf`):
```
2
3
1
1
5
1
6
```

This is how my task looks like:
```yaml
  - name: clear default nginx vhost
    lineinfile:
      dest: /etc/nginx/conf.d/test.conf
      regexp: "1"
      state: absent
    notify:
      - reload nginx
```

##### EXPECTED RESULTS
I was expecting `lineinfile` module to only delete the last matched line in file. 

##### ACTUAL RESULTS
Instead, it deleted all matching lines. Resulting file looks like this:
```
2
3
5
6
```

 I was actually able to clear entire file by specifying `.*` as regexp.

**Comment by Akasurde** [comment]
I think this is working as per documentation 

```
For `state=present', the pattern to replace if found; only the last line found will be replaced. For `state=absent', the pattern of the line to remove.
```

**Comment by dimitrijer** [comment]
I was confused by `the` part:
> ...the pattern of the line to remove...

Think it would be clearer if it read:
> ...the pattern of lines to remove...

**Comment by kustodian** [comment]
Also wasn't `lineinfile` module there to edit just one line in the file (as the name suggests), while `replace` module was added to take care of modifying multiple lines?

**Comment by debianmaster** [comment]
[sorry to hijack this thread] . is it possible to delete  lines which are NOT matching.   ?

**Comment by jacekn2** [comment]
if you have

1
11
111

and you need delete only "1" try use regexp: '^1[\s]' if u use regexp: '^1\s' this dont work

  - name: some test
    lineinfile:
      dest: /test.conf
      regexp: '^1[\s]'
      state: absent
