### ISSUE TITLE
polling for async jobs should list better info

### ISSUE THREAD

**Issue by skvidal** [ansible/ansible#2379]
Right now it just prints out the time left on the total async job timeout.
Ideally it should list:
1. hosts left being polled
2. n/total finished, or waiting, or something.

I may look into this, given time, but it would be a nice feature enhancement - no urgency, of course.

**Comment by mpdehaan** [comment]
if you had 5000 hosts I'm not sure I'd want to see them each time.   I think if it lists when hosts /stop/ being polled that could be useful.

assuming commander callbacks you'd be able to see this more graphically, I imagine.

**Comment by mpdehaan** [comment]
closing per plans that commander should handle this.
