### ISSUE TITLE
copy with backup=yes fails if file is unchanged

### ISSUE THREAD

**Issue by britcey** [ansible/ansible#2380]
~/github/ansible> git pull
Already up-to-date.

~/github/ansible> ansible --version
ansible 1.1 (devel e307658350) last updated 2013/03/12 16:01:30 (GMT -400)

Steps to reproduce:

---

> touch /tmp/testfile1
> 
> cat copytest.yml
> - hosts: nagios
>   connection: ssh
>   sudo: true
>   gather_facts: False
>   tasks:
>   - name: test copy module
>     action: copy src=/tmp/testfile1 dest=/tmp/testfile1 backup=yes
# First run is fine

> ansible-playbook -l *app01* copytest.yml

PLAY [nagios] *********************

TASK: [test copy module] *********************
changed: [prod-nagios-app01.xxx]

PLAY RECAP *********************
prod-nagios-app01.xxx : ok=1    changed=1    unreachable=0    failed=0
# subsequent runs fail

> ansible-playbook -l *app01* copytest.yml

PLAY [nagios] *********************

TASK: [test copy module] *********************
failed: [prod-nagios-app01.xxx] => {"failed": true}
msg: unsupported parameter for module: backup

FATAL: all hosts have already failed -- aborting

PLAY RECAP *********************
prod-nagios-app01.xxxm : ok=0    changed=0    unreachable=0    failed=1

---

I made a brief attempt at debugging, but nothing jumped out.

please let me know if you need more info.

**Comment by skinp** [comment]
This is the same as #2365.

File module is unaware of the option `backup`. The same problem would also arise with option `force` I guess.

**Comment by mpdehaan** [comment]
ok, this comes from recent development work to add 'argument checking' to
file, this is a super easy fix and I'll get this tonight.

Thanks!

On Tue, Mar 12, 2013 at 8:47 PM, Patrick Pelletier <notifications@github.com

**Comment by britcey** [comment]
Confirmed it fixes the issue;  I was in the right area to supply a patch until @dhozac pointed out (rightfully) that 'file' doesn't take 'backup', etc.  Glad I wasn't completely off the mark.  /me delays actually contributing any bugfixes yet again
