### ISSUE TITLE
Clarification of role ./vars/main.yml required structure and permitted options

### ISSUE THREAD

**Issue by spikerobinson** [ansible/ansible#23801]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME
**role** component `vars/main.yml`
**docsite** page http://docs.ansible.com/ansible/playbooks_roles.html

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### CONFIGURATION
Out of the box. 

##### OS / ENVIRONMENT
N/A - documentation

##### SUMMARY
There does not appear to be a description in the docsite of the permitted syntax of a `./vars/main.yml` file in a **role**. The following information I have found by trial and error but would likely be useful to anyone building a **role** using ./vars for the first time. 

1.  The `vars/main.yml` file for a **role** must contain (only?) a dictionary of variables
2.  `include `directives are not permitted / supported within a `vars/main.yml` file
3.  If a `vars:` section is defined in a `vars/main.ym`l file the scope of those defined vars is local only to the `vars/main.yml` file and these vars are **not** provided to consumers of the role

Please add the above information either to the main "Playbook Roles and Includes" docsite page, or on a new page linked off that page. 

To be honest it would also be helpful to have a more concrete specification of each of the component files of a role. We have a description of the layout of the components but not the required contents and optional contents of each component. 

##### STEPS TO REPRODUCE

When executing a role whose vars/main.yml contains an include, this error is emitted:
```yaml
 The vars/main.yml file for role 'abcdef' must contain a dictionary of variables

```

##### EXPECTED RESULTS

My naive assumption, which seemed reasonable, was that:

1. the include directive would be usable in a `vars/main.yml `as it is in other Ansible files
2. I could, or even should, define a `vars:` section in a `vars/main.yml` file, and these values would be available to users of the Ansible **role**

##### ACTUAL RESULTS

1. As noted above, attempting to use an include directive fails with an error
2. Using a `vars:` section in a `vars/main.yml` does not produce any diagnostics or warnings, but the vars defined are local in scope to the `vars/main.yml` and are not available to any playbooks using the role

```

```

**Comment by spikerobinson** [comment]
By the way I would submit a doc patch myself but I read the guidelines on the docsite github and I have accepted the advice to submit the request here rather than learning Sphinx reFactor! :-)

**Comment by bcoca** [comment]
> The vars/main.yml file for a role must contain (only?) a dictionary of variables

this applies to all vars files

> |includedirectives are not permitted / supported within a vars/main.yml file

same as above, this applies to all vars files

> If a vars: section is defined in a vars/main.yml file the scope of those defined vars is local only to the 
> vars/main.yml file and these vars are not provided to consumers of the role

`vars` here becomes a 'variable' which conflicts with the internally used 'vars' variable .. don't do this in ANY vars file.

**Comment by spikerobinson** [comment]
OK great, thanks Brian. So the clarification could be condensed to a
statement that vars/main.yml behaves as per all vars files, with maybe a
link to the description of vars files. And add this other information to
the description of vars files (if it's not already there - sorry I haven't
checked myself).

**Comment by spikerobinson** [comment]
OK so in the light of Brian's helpful explanations I can see that this docsite reference
http://docs.ansible.com/ansible/playbooks_roles.html#roles

has this statement

> Roles are ways of automatically loading certain vars_files, tasks, and handlers based on a known file structure.

which (somewhat indirectly) implies that some of the components of a role are of the type `vars_files`, and in turn I suppose we could guess/deduce that means the files under `vars/` and `defaults/`

I suggest adding a more explicit statement along the lines of

> files under the ./defaults and ./vars directories _[or is it only main.yml in those directories??]_ will be loaded and interpreted as **vars_files**. Note they are **not** loaded and interpreted as if they were **include_vars**.

Problem then still is,  I can find a reference describing `include_vars`
http://docs.ansible.com/ansible/include_vars_module.html
but for the life of me I can't (searching docs.ansible.com with Google) find any page that actually defines the syntax of a valid `vars_file`. 

In fact the `include_vars `page also doesn't define the syntax of a valid `include_vars `file - it gives examples of how to invoke, but no definition or example of what an `include_vars `should look like, other than that it should be valid YAML. 

So - scope creep in this ticket! :-) - looks like what is needed is:

1. a new page or section defining valid `vars_files `content
2. a definition of valid content for `include_vars `on the existing `include_vars `page (link above)
3. add the proposed statement above (or similar) to the roles section of the Playbooks and Roles page (first reference, top of this comment), with links out to  refs 1 and 2.

**Comment by spikerobinson** [comment]
OK I found where the docsite defines `vars_files` - it is in the Variables article:
http://docs.ansible.com/ansible/playbooks_variables.html#variable-file-separation
And yes it does say there that `vars_files` need to consist only of a valid YAML **dictionary** (not just be valid YAML).

So that's where we need to link to: **from** the discussion of the ./vars/ and ./defaults/ files and directories (which are discussed under http://docs.ansible.com/ansible/playbooks_roles.html#roles), stating that ./vars/ and ./defaults/ files for Ansible **roles** need to follow the syntax and usage of `vars_files`.

(The term `vars_files `is not in the table of contents nor in the main text, it's only in the code snippet example, which may be why I couldn't find it even with help from Google).

**Comment by bcoca** [comment]
assigned our doc expert to make sense of this

**Comment by Kiarashz** [comment]
I would like to create an issue to make ansible execute the <role>/vars/main.yml file if it has execution attribute set.
This way, without the need for a custom module, it is possible to have customised and dynamic logic in loading variables.

**Comment by wongster80** [comment]
I looked at https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#using-roles and I don't see much information on how to use roles/x/vars/main.yml .  I would like to also use vars/main.yml to group variables include / import there. 

Also that link doesn't seem to reference the correct content regarding vars_files http://docs.ansible.com/ansible/playbooks_variables.html#variable-file-separation

Can someone provide information on this please?

**Comment by joelparkerhenderson** [comment]
I hit the same issue - the documentation that I found did not seem to explain in ways that I could easily understand and use.

Here's what worked for me, and please let me know if there's a better way.

The file `roles/vars/main.yml` must contain a YAML dictionary such as:

```
foo: "This is my foo variable"
```
The file `roles/tasks/main.yml` loads the variables file:

```
- include_vars: ../vars/main.yml
```

The file `roles/templates/hello.j2` uses the variable:

```
{{ foo }}
```

**Comment by SimonHeimberg** [comment]
> 
> The file `roles/tasks/main.yml` loads the variables file:
> 
> ```
> - include_vars: ../vars/main.yml
> ```
> 

This should be done automatically for ../vars/main.yml. No need to write this.

But this can be used to load other vars files. like:
```yaml
- include_vars: special1.yml
   # looks in playbookDir/roles/thisRole/vars/special1.yml playbookDir/roles/thisRole/special1.yml playbookDir/thisRole/tasks/vars/special1.yml playbookDir/roles/thisRole/tasks/special1.yml playbookDir/vars/special1.yml  special1.yml 
- include_vars: special2.yml
```

I found where ansible searches for the file by running the role when specal1.yml does not exist (in all places).

**Comment by jborean93** [comment]
This issue is quite old and the docs have changed a lot over time. If this is still a problem then I recommend putting it on the agenda for the Documentation Working Group at https://github.com/ansible/community/issues/643 for further discussion with the docs team.
