### ISSUE TITLE
RFE: with_when for loop conditionals instead of when

### ISSUE THREAD

**Issue by kwoodson** [ansible/ansible#23820]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Task

##### ANSIBLE VERSION
Future ansible versions.

##### CONFIGURATION
None

##### OS / ENVIRONMENT
Linux but any would suffice.

##### SUMMARY / Proposal

Add a `with_when` statement to handle conditional logic when performing loops.  This would separate out the `when` logic that is used to include a role, task, or playbook.

We have run into multiple instances where tasks are executed and throw exceptions due to an entire role being included and interpreted when a conditional `when` evaluates to `false`.  This has been considered not a bug in the current implementation of ansible.
https://github.com/ansible/ansible/issues/13950
https://github.com/ansible/ansible/issues/13598
https://github.com/ansible/ansible/issues/16222

This is **not** the expected behavior when attempting to skip tasks with conditional `when` statements.

Conditional logic is such a large component of playbooks, tasks, roles, etc.  Providing a distinction as to when a piece of code gets included could solely be dependent on the `when` statement.  Separating this logic into its own looping conditional would be simplified with a `with_when` statement.  This follows the pattern of `with_items`, `with_dict`, `with_together`, `with_nested`, etc.  This ensures to the author that they are specifically referring to the logic that lives inside of a task and not the logic whether to include or run the task.

```yaml
- name: My super important task
  include: remove_stuff.yml
  when: "{{ need_to_remove_stuff }}"
```

The current code according to documentation places this same `when` condition on each of the tasks included in the playbook.  This means that each task in the playbook then gets interpreted and can throw exceptions.  For example, if a `set_fact|register` is used later from a previously skipped task(s) with a `with_items` it will fail as mentioned in the above linked issues.  This breaks when one would expect the `skip` behavior would be to completely ignore the code being evaluated unless the condition were `true`.

Skipping tasks still incurs the cost of parsing, evaluating, and running the skips.  This is multiplied across the number of hosts running.  If the above feature were to be implemented we could perform a **true** skip which would:

- behave like the executor believes it should
- perform like other languages where items are not brought into scope, parsed, or evaluated
- increase performance
- increase resiliency (you no longer have to worry about code getting interpreted when you don't expect it to)

The downside to this is that it would have problems with backwards compatibility.  Playbooks, tasks, roles, etc would need to be updated for this new behavior.  Painful as it is, this would be one of those features well worth the effort.

**Comment by bcoca** [comment]
or you could just skip the whole thing:
```yaml
- name: My super important task
  include: remove_stuff.yml
  static: no
  when: "{{ need_to_remove_stuff }}"
```

**Comment by kwoodson** [comment]
@bcoca, Big thanks for the suggestion, `static: no` did help in some cases when doing include and include_role.

Here is another case that we run into, maybe you could suggest help or see a reason for `with_when`:
```yaml
  - name: skip
    set_fact:
      test_array:
      - 1
      - 2
      - 3
    when: False

  - name: another skip
    debug:
      msg: "{{ item }}"
    with_items: "{{ test_array }}"
    when: False
```
Results:
```
PLAY [localhost] ***************************************************************

TASK [skip] ********************************************************************
skipping: [localhost]

TASK [another skip] ************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'test_array' is undefined"}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```

Notice that I wanted to skip the `set_fact` and the `debug` but the `with_items` on the second task caused it to be executed before the `when` clause was evaluated.

I think that if a distinct `with_when` and a distinct `when` existed, the `when` would be evaluated before the task was even considered so that it could be skipped.  Its an order of operations issue.

**Comment by bcoca** [comment]
when evaluates for EACH item so with_ always evalutes before when, to avoid this problem do as documented http://docs.ansible.com/ansible/playbooks_conditionals.html#loops-and-conditionals : 
```
    with_items: "{{ test_array|default([]) }}"
    when: False
```

**Comment by sivel** [comment]
Changing `when` to not apply to loops, but only apply to the block as a whole, would be a huge backwards incompatible change that could have huge ramifications to existing playbooks.

I don't see us making that change.

**Comment by kwoodson** [comment]
@sivel, I appreciate the response.  The issue here as @bcoca stated is the order of precedence in which things are evaluated.

`with_items` has a greater precedence than `when`.  That means that there is no way to really `skip` a task.

For example:
```yaml
- block:
  - name: skip
    set_fact:
      test_array:
      - 1
      - 2
      - 3


  - name: another skip
    debug:
      msg: "{{ item }}"
    with_items: "{{ test_array }}"

when: False
```
In this example as well as the earlier one, I would expect that the block would never execute.  The same goes for normal `when` statements.  The results are as follows:
```
PLAY [localhost] ***************************************************************

TASK [skip] ********************************************************************
skipping: [localhost]

TASK [another skip] ************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'test_array' is undefined"}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```

I agree the this proposal (`with_when`) breaks backwards compatibility and is undesirable.  However, the unexpected behavior of executing code that is intended to be skipped is, IMO, even more undesirable.

Maybe adding a `skip` or another attribute that evaluates with a higher precedence than the `with_items` would solve the same problem and provide backwards compatibility.

**Comment by bcoca** [comment]
well, you are making a bad assumption here, blocks don't get evaluated, they are static (compile time), they allow included tasks to inherit properties.

**Comment by sivel** [comment]
The correct way, as @bcoca stated, is that you need to ensure that your `with_` loop, can always evaluate.

So utilizing the following will resolve your problem:

```
with_items: "{{ test_array | default([]) }}"
```

This is documented at http://docs.ansible.com/ansible/playbooks_conditionals.html#loops-and-conditionals

Since I can't see us changing the behavior due to a backwards incompatible change, and the fact that we have this clearly documented, I'm going to close this out.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
