### ISSUE TITLE
Async running some action plugins not marked async will run anyway

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible#23840]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ActionBase

##### ANSIBLE VERSION
2.4.0

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Running some actions not marked as "async OK" will still execute the action, before failing with `async is not supported for this task`. eg, `win_reboot`. Some other actions don't appear to execute though (eg, `copy`). 

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment]
I just pushed fix for this for some actions, so copy now returns:
```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "async is not supported for this task."}

```

**Comment by basictheprogram** [comment]
Assuming this is the same issue?
```
$ ansible --version
ansible 2.4.0 (devel f217dae938) last updated 2017/05/17 14:30:08 (GMT -500)
  config file =
  configured module search path = [u'/Users/tanner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/ansible.git/ansible/lib/ansible
  executable location = /Users/tanner/projects/ansible.git/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  6 2017, 23:53:20) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```
```
- name: Window updates
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
  register: updates 
```
```
- name: reboot
  raw: "Restart-Computer -Force"
  async: 1
  poll: 0
  ignore_errors: True
  when: updates.changed == True
```
```
TASK [win_updates : reboot] ****************************************************
fatal: [surface151]: FAILED! => {"changed": false, "failed": true, "msg": "async is not supported for this task."}
...ignoring
```

**Comment by jhawkesworth** [comment]
@basictheprogram - have you tried using win_reboot instead of the 'raw: "Restart-Computer -Force"' call?
win_reboot is an action plugin that restarts the machine and waits for the restart and polls until winrm service is available again.

**Comment by basictheprogram** [comment]
Thank you! This works great. This is an old role and I'm guess it was around before the addition of win_reboot in 2.1, please close this ticket.
