### ISSUE TITLE
Hi, Support to read  /etc/ansible/hosts  files  from the database 

### ISSUE THREAD

**Issue by ljb-2000** [ansible/ansible#23844]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment]
@ljb-2000  the title alone doesn't convey enough info to figure out what you want, please fill in the template and elaborate
