### ISSUE TITLE
inventory file option interferes with --connection=local option

### ISSUE THREAD

**Issue by ChrisEineke** [ansible/ansible#2386]
If one tries to run a playbook that has _connection_ set to /local/, _hosts_ set to /127.0.0.1/, and you provide an inventory file that doesn't contain a /local/ group, ansible-playbook will not be able to match a host for that playbook and simply do nothing.

I expected the -c local option to synthesize a /local/ group with the /127.0.0.1/ host in (because conceptually speaking, isn't there always is a group with that host in it).

This threw me off when I used the EC2 inventory script as the inventory file, because it doesn't generate a /local/ group.

**Comment by mpdehaan** [comment]
This is not true, you don't have to have a local group, you do need a least one record.

This is why you can set ansible_connection variables in inventory and then not specify the connection in your playbook, and why --limit already exists.

Not a bug.  If you'd like further explanations, please post on the mailing list
