### ISSUE TITLE
Undefined variables and dicts

### ISSUE THREAD

**Issue by jbscare** [ansible/ansible#23871]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Not sure -- something that handles dereferencing variables, presumably?

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 8517fbf936) last updated 2017/04/21 12:38:39 (GMT -400)
  config file = /ansible/dom/ansible.cfg
  configured module search path = [u'/home/jsmift/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jsmift/src/ansible-ansible/lib/ansible
  executable location = /home/jsmift/src/ansible-ansible/bin/ansible
  python version = 2.7.12 (default, Sep  1 2016, 22:14:00) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### CONFIGURATION

None that seems related.

##### OS / ENVIRONMENT

Amazon Linux AMI release 2016.09

##### SUMMARY

If you define a variable that refers to an element in a dict, and that element's parent element isn't defined, you get an error when you try to dereference the variable.

##### STEPS TO REPRODUCE

This playbook:

```yaml
- hosts: localhost
  vars:
    mydict: { a: apple, b: banana }
    myfruit: "{{ mydict[myletter] }}"
  tasks:
    - debug: msg="My fruit is {{ myfruit }}"
      when: myfruit is defined
```

Run the playbook with '--extra-vars myletter=a' and then with '--extra-vars myletter=c'.

##### EXPECTED RESULTS

When run with '--extra-vars myletter=a', we expect a debug task to run and print the message "My fruit is apple".

When run with '--extra-vars myletter=c', we expect the debug task to be skipped, due to the 'when' statement.

##### ACTUAL RESULTS

In Ansible 2.2.1.0, we get the expected results.

In Ansible 2.3.0.0 (and devel, the version mentioned above), we get the expected results with '--extra-vars myletter=a', but with '--extra-vars myletter=c' we get

```
TASK [debug] *******************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'myfruit is defined' failed. The error was: error while evaluating conditional (myfruit is defined): {{ mydict[myletter] }}: 'dict object' has no attribute u'c'\n\nThe error appears to have been in '/home/jsmift/ansible/dom/playbooks/foo.yml': line 6, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - debug: msg=\"My fruit is {{ myfruit }}\"\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
```

**Comment by jbscare** [comment]
Thanks for the fix! An even simpler reproducer:

```yaml
- hosts: localhost 
  tasks: 
    - debug: msg=foo 
      when: foo is defined 
    - debug: msg=foo 
      when: foo['bar'] is defined 
```

Just in case that's useful.

**Comment by krzysztof-magosa** [comment]
Dictionary keys should be checked like that in python: `when: 'bar' in foo`

**Comment by jbscare** [comment]
That's not quite the right syntax; you probably meant this:

```yaml
when: "'bar' in foo"
```

...and that doesn't work either:

```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check ''bar' in foo' failed. The error was: error while evaluating conditional ('bar' in foo): Unable to look up a name or access an attribute in template string ({% if 'bar' in foo %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable\n\nThe error appears to have been in '/home/jsmift/ansible/dom/playbooks/foo.yml': line 5, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      when: foo is defined\n    - debug: msg=foo\n      ^ here\n"}
```

That's presumably because 'foo' isn't defined; so you have to do this:

```yaml
when: foo is defined and 'bar' in foo
```

...and now you've got a non-Pythonic "is defined" in there anyway.

...and it doesn't work with my original example, which is closer to my actual use case:

```yaml
- hosts: localhost
  vars:
    mydict: { a: apple, b: banana }
    myfruit: "{{ mydict[myletter] }}"
  tasks:
    - debug: msg="My fruit is {{ myfruit }}"
      when: myfruit is defined
```

(where myletter comes in as an --extra-vars variable)

...and this worked fine in Ansible 2.2.

**Comment by jbscare** [comment]
To clarify, by "doesn't work with my original example", I mean "I don't see a way to use a 'when' statement to avoid a syntax error in my original example" -- if you do, that'd be cool.

...but if it's a lot more complicated than "when: myfruit is defined", I still think it'd be nice if the thing that used to work still worked.

**Comment by krzysztof-magosa** [comment]
I think it won't work, because `is defined` is operator, and you want to apply it to interpolated value, which will fail during interpolation ;-)

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

`myfruit` is defined (as a templating string), the problem is that `myletter` is pointing to a key that is not.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by jbscare** [comment]
Wait, what? I said right in the description that myletter is being sent in as an --extra-vars variable.

Please reopen this issue.

**Comment by mmanfred** [comment]
If its helpful - this works in 2.2.1.0 but breaks in 2.2.2.0 and higher

**Comment by s-hertel** [comment]
To anyone who cares the fix for this bug has been merged in #25092. I have some tests in #23875 that will hopefully keep this use case noticed.

**Comment by justingood** [comment]
This appears to be still broken in devel, although it includes the referenced PRs.

**Comment by jbscare** [comment]
I guess I should make a new ticket, since this was closed erroneously, and my request that it be reopened was ignored.

I've opened #27268 now.
