### ISSUE TITLE
validate_checksum parameter of fetch module is actually default to "no" does not match the document.

### ISSUE THREAD

**Issue by keepzero** [ansible/ansible#23900]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
fetch

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/xufan/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Sep 28 2016, 15:46:00) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]
```

##### CONFIGURATION

nothing

##### OS / ENVIRONMENT

anything

##### SUMMARY

In the ansible [document](http://docs.ansible.com/ansible/fetch_module.html) the validate_checksum is default set to yes. But actually is "no" in the [fetch.py](https://github.com/ansible/ansible/blob/v2.3.0.0-1/lib/ansible/plugins/action/fetch.py)

##### STEPS TO REPRODUCE
nothing

##### EXPECTED RESULTS

Change the validate_checksum of document default to "no".

##### ACTUAL RESULTS
nothing

**Comment by alikins** [comment]
The module/action does look like it will default to false/no when not specified which doesn't match the docs. 

I'm not sure which is actually correct.

**Comment by abadger** [comment]
Docs are correct, code is wrong.  validate_checksum should default to True.

**Comment by keepzero** [comment]
@abadger Thanks for your reply. I give a new pull request #23995
