### ISSUE TITLE
Probably moot -- yum module traceback CentOS 5.3

### ISSUE THREAD

**Issue by fdavis** [ansible/ansible#2390]
From a fresh install of CentOS 5.3,
if I try to use the yum module to install packages before updating yum, I get the following message,

```
TASK: [make sure various packages are installed] ********************* 
failed: [alpha-0] => (item=dkms,SDL) => {"failed": true, "item": "dkms,SDL", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1363209900.62-108100090326452/yum", line 1480, in ?
    main()
  File "/root/.ansible/tmp/ansible-1363209900.62-108100090326452/yum", line 651, in main
    res = ensure(module, state, pkg, params['conf_file'], enablerepo, disablerepo)
  File "/root/.ansible/tmp/ansible-1363209900.62-108100090326452/yum", line 585, in ensure
    my = yum_base(conf_file)
  File "/root/.ansible/tmp/ansible-1363209900.62-108100090326452/yum", line 93, in yum_base
    my.preconf.debuglevel=0
AttributeError: 'YumBase' object has no attribute 'preconf'
```

I would normally 'yum update' right after installing simplejson, but I ran into this because I'm working on making kernel updates more automated with dkms, so I didn't want to update until dkms was setup. Updating yum resolves the issue.  I wasn't sure if we needed/wanted any fixes for this so I'm reporting it so its at least documented.

Thank you =)

Here is my offending playbook.

```

---
- name: install alpha-0
  hosts: alpha-0
  gather_facts: False

  tasks:
    - name: install ansible target host reqs with raw module
      raw: yum install python-simplejson -y

    - name: make sure various packages are installed
      yum: name=$item state=installed
      with_items:
        - dkms
        - SDL
```

**Comment by mpdehaan** [comment]
Seems like updating the yum is the way to go.

ccing @skvidal just in case there is a possible try/except that could be workable there.

**Comment by mpdehaan** [comment]
ok closing as I haven't heard any other suggested course of action here.

I would hope you get a chance to update your 5.X boxes soon.
