### ISSUE TITLE
Create a module for Keystone endpoints

### ISSUE THREAD

**Issue by rcarrillocruz** [ansible/ansible#23909]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

os_keystone_endpoint

##### SUMMARY

The OpenStack Keystone modules have support for creating domains, services and roles.
Would be good to also have a module for creating Keystone endpoints.

**Comment by MasterofJOKers** [comment]
@rcarrillocruz There's already a PR open for something like this, that seems to need some refinement: #20314 Maybe you can sync up with @mnaser.
