### ISSUE TITLE
Configuration files precedence/overrides

### ISSUE THREAD

**Issue by jlecour** [ansible/ansible#23973]
Hi,

I've been using Ansible on Debian (package installed with "jessie-backports" repository). I can't really verify if the behaviour is the same with the latest version of Ansible.

I've searched the issue list to see if the matter has been discussed, but nothing relevant came up.

I apologize if the issue has been discussed or resolved previously.

Thanks a lot to the entire core team and contributors for making an awesome product :bowing_man:

##### ISSUE TYPE
 Bug Report and/or Feature Idea

##### COMPONENT NAME
configuration file

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /home/jlecour/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
This is the issue itself, details below

##### OS / ENVIRONMENT
```
$ cat /etc/debian_version 
8.7
```

##### SUMMARY

According to the documentation, there are 4 possible locations for configuration : 
* environment variables
* `./ansible.cfg`
* `~/.ansible.cfg`
* `/etc/ansible/ansible.cfg`

The 3 files are mutually exclusives ; if one exists (in order of precedence) the others are ignored completely, even if the sections variables are non overlapping.

In my opinion, it seems to counter-intuitive at least. I wouldn't say that it's a bug (there might be good reasons that I don't know), but it would be really great if it was not the case.

There are many software that can have multiple configuration files, with a specific order of precedence, but they override each-other only on overlapping variables. For example, with MySQL/MariaDB, you can have multiple configuration files.

In Ansible's case, I wanted to have a config file in my $HOME, with a few global configurations (like where I put some external roles, with `roles_path`) and also have a local config file to each Ansible project, with settings like `ask_sudo_pass`, `inventory…

##### STEPS TO REPRODUCE

Create a personal config file : 

```
$ cat ~/.ansible.cfg 
[defaults]
roles_path = ~/external-roles

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=300s
pipelining = True
```

Create a project specific config file : 

```
# cat ~/project/ansible.cfg
[defaults]
retry_files_enabled = False
ask_sudo_pass = True
inventory = ./inventory/hosts
```

##### EXPECTED RESULTS

I'd expect each variable to be evaluated according to the precedence order, instead of ignoring entire config files with lower precedence.

##### ACTUAL RESULTS

Then run playbooks and see that roles present in `~/external-roles` are not visible by the playbook. If the `roles_path` is added to the local config file, it works. If the local config file is removed, it works too.

**Comment by bcoca** [comment]
this is a subset of an existing proposal https://github.com/ansible/proposals/issues/35

**Comment by jlecour** [comment]
Thank you for pointing the original issue.

**Comment by rguhr** [comment]
Even if it's an old issue it is still relevant.

@jlecour as workaround you could build a temporary configuration file which merged all possible ansible.cfg's

Here is a draft of this approach:
https://gitlab.com/snippets/1753039
