### ISSUE TITLE
Set file permissions for openssl_publickey to 0600?

### ISSUE THREAD

**Issue by sbwoodside** [ansible/ansible#23998]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

openssl_privatekey and openssl_publickey

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /Users/.../ansible.cfg
  configured module search path = [u'./ansible/library']
  python version = 2.7.13 (default, Dec 17 2016, 23:03:43) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### OS / ENVIRONMENT

MacOS X 10.11.6

##### SUMMARY

openssl_publickey creates a file with permissions 0644, but it appears that they are generally stored as 0600.

I'm a bit iffy on this because I can't find a clear reference that the **public** key should be stored as 0600 as opposed to say 0644, but on Mac OS X it appears to be the default.

**Comment by Spredzy** [comment]
@sbwoodside Hello and thank you for reporting the issue.

You can already do that with `openssl_privatekey` using the `file` module parameters. The linked PR will ensure it is clearly stated in the documentation.

This option was however missing from `openssl_publickey` and has been added. I'll check with the ansible-core team to see if this can be backported to 2.3.
