### ISSUE TITLE
feature request: apt module can update package only if installed

### ISSUE THREAD

**Issue by aerickson** [ansible/ansible#23992]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
apt module (part of packaging)

##### ANSIBLE VERSION
```
ansible 2.3.0.0
```

##### CONFIGURATION
default

##### OS / ENVIRONMENT
ubuntu 14.04

##### SUMMARY
When doing security patching, it's handy to say keep these packages up-to-date, but don't install them. Basically https://github.com/ansible/ansible-modules-core/pull/4299/files.

##### STEPS TO REPRODUCE
```yaml
n/a
```

##### EXPECTED RESULTS
n/a

##### ACTUAL RESULTS
n/a

**Comment by MarkusTeufelberger** [comment]
Similar to https://github.com/ansible/ansible/issues/23220 ?

**Comment by aerickson** [comment]
Nope, that one just downloads the deb and doesn't install it.

I want ansible to be able to only upgrade a package if it's installed
(currently working around with a script).

**Comment by MarkusTeufelberger** [comment]
So you want to define a package (let's say docker) and if it is installed then update it, if not, do nothing? I thought that's what the "only_upgrade" switch is for...

**Comment by aerickson** [comment]
Thanks. That's exactly what I wanted. 

Confusing that it's not a state.
