### ISSUE TITLE
[doc+tests] document precedence of var definitions

### ISSUE THREAD

**Issue by leucos** [ansible/ansible#240]
vars can be defined in many place, mostly a combination of {inventory, playbook} x {hosts, groups}  

The order of precedence for the declaration should be documented so people could order ther var declarations consistently (apply to all first, then overrides, etc...).

Tests should be written to ensure this order is stricly enforced in ansible so we don't bump on unexpected behavior.

**Comment by mpdehaan** [comment]
ticket belongs in docs project...please file it there

**Comment by leucos** [comment]
oops, sorry about that
