### ISSUE TITLE
Please improve task/include documentation to reflect special constraints/restrictions

### ISSUE THREAD

**Issue by asad-at-srt** [ansible/ansible#2403]
- include paths can only be derived from vars/vars_files but NOT inventory variables
- similarly include parameters should be derived from vars/vars_files, otherwise they are not evaluated on the execution of the include
- and again similarly, with_items used with includes can only be based on vars/vars_files
- lastly, task (but not playbook) includes can be used with conditionals, and are equivalent to putting the conditional on each included action
  (I assume: this works like an AND on existing conditional, and is recursive to arbitrary include depths)

**Comment by mpdehaan** [comment]
we've undocumented most of the 'attach stuff to includes' things in the docs so people won't try these things.
