### ISSUE TITLE
mysql_user module recognizes quotes in .my.cnf where mysql client strips them

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#2405]
If you're setting the root password with the mysql_user module, let's say your .my.cnf looks like this:

```
[client]
user=root
password="n<_665{vS43y"
```

If you run the mysql command-line tool, it will strip the quotes from the password variable.  But if you use the mysql_user module, it won't strip the quotes.

In a recent pull request, I've added to the mysql_user docs to say: "Don't quote the password string in .my.cnf", but it would be best if mysql_user matched mysql client behavior. 

Perhaps switching from RawConfigParser to SafeConfigParser will fix this (?), but I haven't tried it.

**Comment by mpdehaan** [comment]
seems like the code could just strip the quotes too.

send me a patch?

**Comment by lorin** [comment]
This hasn't been thoroughly tested, so I recommend not including it in 1.1.
