### ISSUE TITLE
vmware_guest: Orphaned Resource Pools in VSphere cause failed `assert`

### ISSUE THREAD

**Issue by cboggs** [ansible/ansible#24078]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`vmware_guest` -> `resource_pool`

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/jenkins/workspace/paas-dispenser/deploy/ansible.cfg
  configured module search path = [u'/home/jenkins/workspace/paas-dispenser/deploy/openshift-ansible/roles/openshift_facts/library', u'/home/jenkins/workspace/paas-dispenser/deploy/playbooks/library', u'/home/jenkins/workspace/paas-dispenser/deploy/playbooks/modules/']
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Resource pools are retrieved from VSphere regardless of the state of the `resource_pool` parameter. During this process, each retrieved Resource Pool is checked for the `parent` attribute, and if it exists, the currently-scoped parent object is compared against the Resource Pool's parent object. The method doing the check, however, `assert`s that the parent object is not `None`. In some cases, a Resource Pool will have the `parent` attr, but that `parent` object will be `None`, causing the `assert` to fail.

##### STEPS TO REPRODUCE

Run `vmware_guest` to create a VM in a VMWare cluster that contains at least one orphaned resource pool. `resource_pool` parameter can be populated or omitted - doesn't make a difference.

```yaml

```

##### EXPECTED RESULTS

VM guest should be created successfully, either within the specified `resource_pool`, or in no `resource_pool` if the parameter is omitted.

##### ACTUAL RESULTS

`assert` in vmware_guest module fails due to `None`-type Resource Pool parent object.

```
TASK [Create fresh VM] ********************************************************************************
fatal: [basevm-centos72.ose.bld.f4tech.com -> localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:852
: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  Insecur
eRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_XHEfTR/ansible_module_vmware_guest.py\", line 1348, in <module>\n    main()\n  File \"/tmp/ansible_XHEfTR/ansible_module_vmware_gues
t.py\", line 1337, in main\n    result = pyv.deploy_vm()\n  File \"/tmp/ansible_XHEfTR/ansible_module_vmware_guest.py\", line 1079, in deploy_vm\n    resource_pool = self.select_resource_pool(hostsystem)\n  F
ile \"/tmp/ansible_XHEfTR/ansible_module_vmware_guest.py\", line 1018, in select_resource_pool\n    if self.obj_has_parent(rp[0].parent, host.parent):\n  File \"/tmp/ansible_XHEfTR/ansible_module_vmware_guest
.py\", line 983, in obj_has_parent\n    assert obj is not None and parent is not None\nAssertionError\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

**Comment by cboggs** [comment]
#24079 addresses this bug.

**Comment by jctanner** [comment]
resolved_by_pr https://github.com/ansible/ansible/pull/24079
