### ISSUE TITLE
user module does not append groups on OpenBSD

### ISSUE THREAD

**Issue by nmeum** [ansible/ansible#24074]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`user` module

##### ANSIBLE VERSION

```
ansible 2.2.2.0
  config file = /home/nmeum/src/alpine-ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

From ansible.cfg:

```
[defaults]
no_target_syslog = True
```

##### OS / ENVIRONMENT
I am running Ansible from Alpine Linux and I am managing an OpenBSD 6.1 System.

##### SUMMARY

The `user` module has an `append` option which should append the groups listed in the `groups` option to the user's groups instead of overwriting them. Unfortunately, this doesn't seem to work on OpenBSD 6.1. Instead of appending the given groups to the existing user's groups the user's groups are overwritten.  

##### STEPS TO REPRODUCE

```
$ ssh <host> groups
nmeum git
$ ansible <host> -m user -a "name=nmeum append=yes groups=dialer"
<host> | SUCCESS => {
    "append": true, 
    "changed": true, 
    "comment": "nmeum", 
    "group": 1242, 
    "groups": "dialer", 
    "home": "/home/nmeum", 
    "move_home": false, 
    "name": "nmeum", 
    "shell": "/bin/ksh", 
    "state": "present", 
    "uid": 1242
}
$ ssh <host> groups
nmeum dialer
```

##### EXPECTED RESULTS

In the last step above the output of the `groups(1)` program should have been `nmeum git dialer`.

##### ACTUAL RESULTS
Instead of appending the dialer group to the user's secondary groups, the user's secondary groups have been set to `dialer` instead.

**Comment by toxadx** [comment]
I commit that this bug persist also in 2.3.0.0.
