### ISSUE TITLE
gentoo ebuilds

### ISSUE THREAD

**Issue by bfx81** [ansible/ansible#2409]
The repository with the gentoo ebuild is not "ansible-specific" so I've submitted the v-9999 ebuild and created a v-1.0 ebuild here:
https://bugs.gentoo.org/show_bug.cgi?id=461830

Would be nice (if the ebuild not reach the official portage-tree soon) to provide these ebuilds directly from ansible website.

Tnx for your amazing tool!

**Comment by mpdehaan** [comment]
The docsite takes patches if you would like to revise them.  -- I am not quite sure what you want to add but am quite open to additions!

see the docsite/rst/gettingstarted.rst file

**Comment by mpdehaan** [comment]
closing per PR, thanks!
