### ISSUE TITLE
ansible ping command hangs after few hours run

### ISSUE THREAD

**Issue by stacker2017** [ansible/ansible#24109]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

/usr/bin/ansible  storage*,compute*,controller* -m ping -b --become-method=su --become-user=ansible
##### ANSIBLE VERSION

```
Ansible version: 2.3
```

##### CONFIGURATION

```
[defaults]
inventory = ./hosts
log_path = /dev/null
remote_user = ansible
host_key_checking = False
retry_files_enabled = False

[ssh_connection]
pipelining = True
ssh_args = -o ControlMaster=auto -o ControlPersist=30m -o UserKnownHostsFile=/dev/null
```
OS / ENVIRONMENT
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```
##### SUMMARY

ansible ping command hang after I run it in a loop for a few hours, I can see the connection is open to the remote host when I do netstat command but it never comes back
##### STEPS TO REPRODUCE

I am creating the loop through python script:
```
#! /usr/bin/python


import shlex,subprocess
import logging
import os
import time


logger = logging.getLogger('ping')
timestamp = time.strftime("%Y%m%d")
handler = logging.FileHandler('/tmp/ansible_pinglog-' + timestamp)
formatter = logging.Formatter('%(asctime)s %(levelname)s %(message)s')
handler.setFormatter(formatter)
logger.addHandler(handler)
logger.setLevel(logging.DEBUG)
command_line = ("/usr/bin/ansible  storage*,compute*,controller* -m ping -b --become-method=su --become-user=ansible")
args = shlex.split(command_line)

while True:
   p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

   while True:
      line=p.stdout.readline()
      if line != "":
         log=line.rstrip()
         print log
         logger.info(str(log))
      else:
         break
```

```yaml

```

##### EXPECTED RESULTS

for script to run indefinitly and generate foloowing log:
2017-04-28 12:27:39,091 INFO }
2017-04-28 12:27:39,145 INFO controller-1 | SUCCESS => {
2017-04-28 12:27:39,145 INFO     "changed": false,
2017-04-28 12:27:39,145 INFO     "ping": "pong"
2017-04-28 12:27:39,145 INFO }
2017-04-28 12:27:39,147 INFO storage-6 | SUCCESS => {
2017-04-28 12:27:39,148 INFO     "changed": false,
2017-04-28 12:27:39,148 INFO     "ping": "pong"
2017-04-28 12:27:39,148 INFO }
2017-04-28 12:27:39,203 INFO controller-2 | SUCCESS => {
2017-04-28 12:27:39,203 INFO     "changed": false,
2017-04-28 12:27:39,203 INFO     "ping": "pong"
2017-04-28 12:27:39,204 INFO }
##### ACTUAL RESULTS

It runs for few hours and then ansible hung and never comes back

```

```

**Comment by stacker2017** [comment]
for example after process is hung I see in ps -ef : 
 sshpass -d26 ssh -o ControlMaster=auto -o ControlPersist=30m -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.10.10.16 /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1493062361.12-39668938146748/ /home/ansible/.ansible/tmp/ansible-tmp-1493062361.12-39668938146748/ping.py && sleep 0'

this ping command has been issues but it stays there for ever.

**Comment by jctanner** [comment]
@stacker2017 I see sshpass in the arguments string. Have you tried your test with a key that doesn't require a password so that sshpass is out of the picture?

needs_info

**Comment by stacker2017** [comment]
@jctanner we need to stick to sshpass and keys are not an option for our environments, the error happened again and ansible hanged indefinitely  below is the log of what I see on the server that I am running ansible from(ansible host) and I have not terminated the ansible yet:

pstree -p:

systemd(1)─┬─accounts-daemon(697)─┬─{gdbus}(917)
           │                      └─{gmain}(896)
           ├─acpid(685)
           ├─agetty(911)
           ├─atd(698)
           ├─bash(935)───sleep(8431)
           ├─chronyd(21495)
           ├─cron(695)
           ├─dbus-daemon(686)
           ├─dnsmasq(9839)
           ├─irqbalance(916)
           ├─iscsid(854)
           ├─iscsid(855)
           ├─lvmetad(369)
           ├─mdadm(782)
           ├─nginx(972)─┬─nginx(973)
           │            └─nginx(974)
           ├─polkitd(940)─┬─{gdbus}(944)
           │              └─{gmain}(942)
           ├─python(683)─┬─ansible-playboo(3927)
           │             └─{python}(977)
           ├─rsyslogd(684)─┬─{in:imklog}(688)
           │               ├─{in:imuxsock}(687)
           │               └─{rs:main Q:Reg}(689)
           ├─sshd(828)─┬─sshd(19084)───sshd(19105)───bash(19106)───sudo(19139)───su(19140)───bash(19141)───tmux(19161)
           │           └─sshd(19162)───sshd(19183)───bash(19184)───sudo(19198)───su(19199)───bash(19200)───pstree(8723)
           ├─sshpass(3041)───ssh(3043)
           ├─systemd(5931)───(sd-pam)(5932)
           ├─systemd-journal(334)
           ├─systemd-logind(682)
           ├─systemd-udevd(383)
           ├─tmux(22894)───bash(22895)───ansible-ping.py(26789)───ansible(4508)─┬─ansible(4777)───sshpass(4826)───ssh(4827)
           │                                                                    └─{ansible}(4678)
           ├─tmux(19125)─┬─bash(19121)
           │             └─bash(19126)───sudo(19142)───su(19143)───bash(19144)───sudo(20401)───su(20402)───bash(20403)
           ├─uuidd(22377)
           └─zabbix_agentd(22229)─┬─zabbix_agentd(22230)
                                  ├─zabbix_agentd(22231)
                                  ├─zabbix_agentd(22232)
                                  ├─zabbix_agentd(22233)
                                  ├─zabbix_agentd(22234)
                                  └─zabbix_agentd(22235)

**Comment by stacker2017** [comment]
on ansible host ps -ef | grep  10.1.1.1:

root       440     1  0 17:09 ?        00:00:00 ssh: /usr/local/boss/$HOME/.ansible/cp/ansible-ssh-10.1.1.1-22-ansible [mux]
root      4826  4777  0 15:49 pts/1    00:00:00 sshpass -d26 ssh -o ControlMaster=auto -o ControlPersist=30m -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.55.68.23 /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1493653784.14-29195844624164/ /home/ansible/.ansible/tmp/ansible-tmp-1493653784.14-29195844624164/ping.py && sleep 0'
root     14799 19200  0 17:13 pts/3    00:00:00 grep --color=auto 10.1.1.1

**Comment by stacker2017** [comment]
in the storage node that ansible tries to reach and casued the hang:
**May 01 15:48:23 storage-1 ansible-ping[15050]: Invoked with data=None
May 01 15:48:39 storage-1  ansible-ping[15077]: Invoked with data=None
May 01 15:48:55 storage-1 ansible-ping[15115]: Invoked with data=None**
May 01 15:49:01 storage-1 CRON[15122]: pam_unix(cron:session): session opened for user root by (uid=0)
May 01 15:49:01 storage-1 CRON[15123]: (root) CMD (   test -x /etc/cron.daily/popularity-contest && /etc/cron.daily/popularity-contest --crond)
May 01 15:49:01 storage-1 CRON[15122]: pam_unix(cron:session): session closed for user root
**May 01 15:49:11 storage-1 ansible-ping[15143]: Invoked with data=None**
May 01 15:49:13 storage-1 ceph-osd[5139]: 2017-05-01 15:49:13.611377 7f04c1ecd700  0 -- 169.254.128.10:6839/1005139 >> 169.254.128.2:6833/1002196 pipe(0x561f1eca
0800 sd=125 :34130 s=2 pgs=14035 cs=227 l=0 c=0x561f2c1b6f00).fault with nothing to send, going to standby

**Comment by stacker2017** [comment]
So usually for each ping command I see 3 line logs in server in last case which failed there is only one line record:
May 01 15:49:11 storage-1 ansible-ping[15143]: Invoked with data=None

**Comment by alikins** [comment]
@stacker2017 any ideas if there is anything in the invocation that would make multiple attempts? Wondering what triggers the 4 runs in https://github.com/ansible/ansible/issues/24109#issuecomment-298378663

The config you posted doesnt setup ssh retries, so it shouldn't be that.

Could the ssh connection be timing out (noticed the ssh ConnectTimeout=10 and the 'Invoked with data=None' log entries are slightly more than 10secs apart.). I think if the module doesnt return any data that could cause a timeout out.  Not sure how the wrapper script would handle timeouts so not sure if that could be the cause.
