### ISSUE TITLE
supports_check_mode undocumented in dev docs

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#2410]
The [Module Development](http://ansible.cc/docs/moduledev.html) page does not mention how to implement check mode with the  `supports_check_mode` flag

**Comment by mpdehaan** [comment]
Documentation for 1.1 devel branch features are not yet added

**Comment by lorin** [comment]
Would you accept a doc patch before 1.1 is released?

**Comment by mpdehaan** [comment]
As long as it uses "versionadded" in Sphinx, sure.   Thanks!
