### ISSUE TITLE
SLES login does not work with audited shell

### ISSUE THREAD

**Issue by repcsi** [ansible/ansible#24115]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ping, playbook

##### ANSIBLE VERSION
ansible 2.2.2.0
  config file = /usr/local/etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

##### CONFIGURATION
/usr/local/etc/ansible/ansible.cfg
```
[defaults]
remote_tmp     = ~/.ansible/tmp
gather_timeout = 10
host_key_checking = False
timeout = 10
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
[accelerate]
[selinux]
[colors]
```
##### OS / ENVIRONMENT
ansible OS: FreeBSD 11.0
Env: SLES11, SLES12 with audited shell that puts out a message before the prompt
The audit program is NetIQ Privileged Account Manager

##### SUMMARY
If I connect and ping a normal machine so to speak and get the normal shell ansible works, but if I try to ping or connect to a machine that forks the audited shell at the logon I get an error:
```
machinename | UNREACHABLE! => {
    "changed": false,
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /home/loginusername && sleep 0/.ansible/tmp/ansible-tmp-1493384480.28-161753539207948 `\" && echo ansible-tmp-1493384480.28-161753539207948=\"` echo /home/loginusername && sleep 0/.ansible/tmp/ansible-tmp-1493384480.28-161753539207948 `\" ), exited with result 127",
    "unreachable": true
}
```
If I switch off the audited shell spawning at logon ansible works.
Two differences in my case are:
- that the machine puts out the following "greeting" string, AKS means Audited KSH Shell. Maybe it's a parser issue...
```
Last login: Fri Apr 28 11:24:15 2017 from localhost
    |A|K|S|

$
```
- other on is that is starts a different shell executable

##### STEPS TO REPRODUCE
you need to have the audited shell in place
ansible mygroup -m ping -u loginusername -s -k 

##### EXPECTED RESULTS
```
goodmachine | SUCCESS => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": null
        },
        "module_name": "ping"
    },
    "ping": "pong"
}
```
##### ACTUAL RESULTS
```
machinename | UNREACHABLE! => {
    "changed": false,
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /home/loginusername && sleep 0/.ansible/tmp/ansible-tmp-1493384480.28-161753539207948 `\" && echo ansible-tmp-1493384480.28-161753539207948=\"` echo /home/loginusername && sleep 0/.ansible/tmp/ansible-tmp-1493384480.28-161753539207948 `\" ), exited with result 127",
    "unreachable": true
}
```

**Comment by jctanner** [comment]
@repcsi Can you show us the -vvvv output?

needs_info

**Comment by samdoran** [comment]
This seems like the remote shell setting needs to be changed.

To discuss this further, please reach out on IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
