### ISSUE TITLE
with_items fails with compound item list

### ISSUE THREAD

**Issue by Reagan** [ansible/ansible#24114]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
with_items

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /Users/naroazurutuza/Desktop/work/new_gro/simple-python-test/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.10 (v2.7.10:15c95b7d81dc, May 23 2015, 09:33:12) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

##### OS / ENVIRONMENT
System Version: macOS 10.12 (16A323)
Kernel Version: Darwin 16.0.0

##### SUMMARY
`with_items` fails when reading a multi-level list item e.g. 
```
- name: Include package information
  include_vars: "packages.yml"

- name: Install System packages
  apt: name={{ item }} state=latest
  with_items: common_system_packages
```
fails with the message `with_items` cannot find the item `['X']` where `X` is a var in a multi-level list with var in the file `packages.yml`  e.g.

```
X
  - a
  - b
Y
  - c
  - d
```
##### STEPS TO REPRODUCE
Same as summary above

##### EXPECTED RESULTS
Expected all items in `common_system_packages` to be populated into `{{ item }}` and installed on the specified ansible task 

##### ACTUAL RESULTS
As defined in summary

**Comment by erwilan** [comment]
since ansible 2.3 you have to write it this way:
```
with_items: "{{ common_system_packages }}"
```
https://github.com/ansible/ansible/blob/stable-2.3/CHANGELOG.md#removed-deprecated

**Comment by Reagan** [comment]
Great! It's actually better this way referencing `with_items: "{{ var_name }}"` rather than  `with_items: "{{ item }}"`. Kindly close issue.

**Comment by sivel** [comment]
Closing as requested
