### ISSUE TITLE
CURL from one VM to another gives time out error

### ISSUE THREAD

**Issue by pspravin** [ansible/ansible#24121]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```
curl -verbose 129.146.34.164
```

##### ACTUAL RESULTS

[opc@vm04 ansible]$ curl -verbose 129.146.34.164
* About to connect() to 129.146.34.164 port 80 (#0)
*   Trying 129.146.34.164...
* Connection timed out
* Failed connect to 129.146.34.164:80; Connection timed out
* Closing connection 0
curl: (7) Failed connect to 129.146.34.164:80; Connection timed out
[opc@vm04 ansible]$

```

```

**Comment by sivel** [comment]
I can't see how this has anything to do with ansible.  Care to explain?

**Comment by pspravin** [comment]
@Sivel, you are correct, not entirely Ansible, but I installed CURL using playbook and hence thought someone may be aware of this issue, as I am struggling to get a solution for this since 2 days. Do you know how to resolve ?

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
