### ISSUE TITLE
Unsetting variables

### ISSUE THREAD

**Issue by MOZGIII** [ansible/ansible#24136]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
Defaults.

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I need a way to unset a variable, but there is none. My usecase is:
1. Run a playbook with some settings.
2. ... some jobs happen ...
3. Preserve some variables (`set_fact: { preserve: { ansible_port: '{{ ansible_port || default(ommit) }}' } }`).
4. Set `ansible_port` to other value.
5. Do what's required.
6. Set `ansible_port` back to preserved value.
7. Do the rest with `ansible_port` the same as during (2).

The problem is that in (6) I can't unset the variable if it was not defined (and thus was ommited) at (3).
Setting `ansible_port` to `None` does not work, and the behaviour I want is to use system ssh client port setting there (and to not just hardcode it to 22). Furthermore, there are also other variables that has to be treated that way.

I propose adding a special variable value called `unset` (or `undefine`) to allow for fact undefining.

##### STEPS TO REPRODUCE

```yaml
- name: Define a fact
  set_fact:
    ansible_port: 22

- name: Undefine a fact
  set_fact:
    ansible_port: '{{ unset }}'

- debug:
    var: ansible_port
```

##### EXPECTED RESULTS
A variable to be undefined.

```
TASK [debug] ***************************************************************************************************************************************************************
ok: [host] => {
    "ansible_port": "VARIABLE IS NOT DEFINED!",
    "changed": false
}
```

##### ACTUAL RESULTS
It didn't work.

```
TASK [Undefine a fact] *****************************************************************************************************************************************************
fatal: [host]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'unset' is undefined\n\nThe error appears to have been in '/ansible/test.yml': line x, column y, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: Undefine a fact\n      ^ here\n"}
        to retry, use: --limit @/ansible/test.retry
```

**Comment by xlf12** [comment]
Yes, indeed it is a true issue. If you are forced to use and to toggle variable like "ansible_XYZ" you can't reset them during a play or a series of plays. 
Think of a scenario where you fight your way through a bunch of machines where some accept already ssh keys and some start by asking you for a password. If you what to align all the machines to accept your ssh key you can do that for example with one inventory pointing already to the key which should be used in further plays ...

**Comment by MOZGIII** [comment]
There are some related fetuares, like defining a set of variables with a lifetime bound to some user-defined scope, which may also be considered for implementation together with variable unsetting. Unsetting is a must-have though.

**Comment by ThomasSteinbach** [comment]
Stumbeling over this issue every time. I'd like to declare undefined variables in my `defaults/main.yml` as self documentation, und use `{{ ... if x is defined ...}}` and ` {{ ... | default('y') }}` in my ansible artifacts. But this is still not possible.

I would be very glad to see this feature implemented. `variable: none` would be my preferred declaration.

**Comment by MOZGIII** [comment]
Would `variable: !!null` work for you?

**Comment by ThomasSteinbach** [comment]
No. `{{ variable | default('unset') }}` would not return `unset` as expected but an empty string.

**Comment by MOZGIII** [comment]
I see. Yeah, that is a necessary feature as well.

**Comment by coofercat** [comment]
Without wanting to start a "me too" or "+1" storm, I'll add another use-case...

As a general rule, I like to default absolutely everything. By putting some mention of every variable you use in your defaults/main.yml file, you provide some documentation of what's going on in your tasks and templates. However, there are some cases where you'd like ansible execution to fail if a variable hasn't been set. In such cases, you can't put something like "my_var: unset" in defaults/main.yml.

Consider this template:
```
{{ rails_environment }}:
  database: {{ rails_database_name }}
  username: {{ rails_database_username }}
  password: {{ rails_database_password }}
```
...and a task something like:
```
- name: Save out a database.yml file for capistrano deploys
  template: src=database.yml.j2 dest=/some/path/database.yml
  when: deployed_by_capistrano
```

I'd like to put something like this in my defaults.yml file:
```
deployed_by_capistrano: no
rails_database_name: rails
rails_database_username: rails
rails_database_password: undef
```
That way, if deployed_by_capistrano is set, but the password is not, then execution will fail (which seems like the right thing to do).

As things stand, I tend to just comment out the rails_database_password line in defaults.yml, so it's still in there as a reference, but not used. The trouble with that approach is that it could look like it's been removed from the templates though.

I realise there are workarounds and other ways to structure things to make this all work as intended, but honestly, none of them seem to be as tidy or logical (to me, at least).

**Comment by gbaufake** [comment]
+1 on that feature!

**Comment by snakelab** [comment]
+1

**Comment by morenod** [comment]
+1

**Comment by MartinVUALTO** [comment]
Could/should this be implemented by extending the [meta](https://docs.ansible.com/ansible/2.6/modules/meta_module.html) feature?

    - name: Clear all gathered facts from all currently targeted hosts
      meta: clear_facts

    - name: Clear listed facts from all currently targeted hosts
      meta: clear_facts
          - var1
          - var2
          - var3

This feels like a relatively small extension to an already existing feature.

**Comment by MOZGIII** [comment]
I think we should have it look similar to however we create fact.

It seems like there are some architectural issues preventing ansible from implementing the feature, otherwise it'd be done long ago.

**Comment by relrod** [comment]
Pending #60081.

**Comment by nitzmahone** [comment]
We've actually got a way to do *most* of what you want now with the `undef()` Jinja function: 

https://github.com/ansible/ansible/pull/75435
