### ISSUE TITLE
include with_items executed in files not included

### ISSUE THREAD

**Issue by Tekki** [ansible/ansible#24142]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include / with_items

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/tekki/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### CONFIGURATION

Only inventory path changed.

##### OS / ENVIRONMENT

Debian 8.7

##### SUMMARY

`include` that uses `with_items` is executed even in files that are not included.

##### STEPS TO REPRODUCE
```yaml
# includes.yml
- hosts: testhost
  tasks:
  - include: include_one.yml
    tags: [one]
  - include: include_two.yml
    tags: [two]

# include_one.yml
- debug: msg=One

# include_two.yml
- debug: msg=Two

- set_fact:
    list: [1, 2]

- include: include_three.yml
  with_items: "{{ list }}"

# include_three.yml
- debug: msg=Three
```

Command:

`ansible-playbook includes.yml --tags one`

##### EXPECTED RESULTS
Prints `One`.

##### ACTUAL RESULTS
Prints `One`, followed by
```
TASK [include] ***********************
fatal: [192.168.1.125]: FAILED! => {"failed": true, "msg": "'list' is undefined"}
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The tags on an include do not affect the include itself, but the included tasks, which are still evaluated for correctness even if they are going to be skipped.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
