### ISSUE TITLE
gem module: latest rubygems removes --include-dependencies option

### ISSUE THREAD

**Issue by mattwk** [ansible/ansible#2414]
gem module fails after a gem update:
# gem --version

2.0.3
# gem install --include-dependencies compass

ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --include-dependencies
# ansible --version

ansible 1.1 (devel fc8d9377d5) last updated 2013/03/15 10:43:41 (GMT -400)

Setting include_dependencies=false in the playbook works.

**Comment by mpdehaan** [comment]
Yay Ruby breaking APIs and stuff.

**Comment by mpdehaan** [comment]
Fixed per above
