### ISSUE TITLE
HTTPS certificate validation on OSX trusts unaudited root CA

### ISSUE THREAD

**Issue by cpu** [ansible/ansible#24152]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`module_utils/urls.py` and the `SSLValidationHandler`

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /home/daniel/Code/streisand/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb 11 2017, 12:22:40) [GCC 6.3.1 20170109]
```

The affected code is present in master as of 594d7d5.

##### CONFIGURATION

n/a

##### OS / ENVIRONMENT

n/a - I am on Archlinux but this bug is specific to OSX / Darwin.

##### SUMMARY

In 3b5aa8bd30a3fa84eca6141a434274b1455c591b a hardcoded CA certificate was embedded in PEM format into `module_utils/urls.py` as the constant [`b_DUMMY_CA_CERT`](https://github.com/ansible/ansible/blob/594d7d5d9d1ee77c7455ca8b5933ffe6377ca905/lib/ansible/module_utils/urls.py#L320:L341). The PEM decodes to a self-signed certificate with subject/issuer `C = US, ST = North Carolina, L = Durham, O = Ansible` and serial number `ef:04:d7:64:bb:fe:a1:29`. It is valid until Mar 15 2024. The public key is a 1024 bit RSA key. The certificate has no name constraints in its basic constraints and has the `CA: True` bit set.

In the current code in master, `b_DUMMY_CA_CERT` is prepended to the `tmp_fd` containing the CA bundle [when the platform of the Ansible host is "darwin"](https://github.com/ansible/ansible/blob/594d7d5d9d1ee77c7455ca8b5933ffe6377ca905/lib/ansible/module_utils/urls.py#L649:L651). The `tmp_fd` contents eventually bubble down to [being used for the CA trust store](https://github.com/ansible/ansible/blob/594d7d5d9d1ee77c7455ca8b5933ffe6377ca905/lib/ansible/module_utils/urls.py#L719) when using the `http_request` function.

This is a potential security bug since all Darwin Ansible users have to trust that no entity controls the 1024 bit RSA private key corresponding to the public key in `b_DUMMY_CA_CERT`. While I'm sure that @sivel, the original author of  3b5aa8bd30a3fa84eca6141a434274b1455c591b likely destroyed the private key we can never be certain that it wasn't lost, stolen by malware, or hoarded by the author for his own long term schemes of profit and world domination (muah ha ha!).

If an entity has control of the private key for this dummy CA certificate they are able to mint trusted certificates for use in man-in-the-middle attacks against any Darwin user's Ansible HTTPS requests, even with `validate_certs: true` configured by signing leaf certificates issued by the dummy CA.

##### STEPS TO REPRODUCE

n/a

##### EXPECTED RESULTS

The comment on 3b5aa8bd30a3fa84eca6141a434274b1455c591b describes the need for this dummy CA in terms of a workaround for OSX keychain:

>  This is a dummy cacert provided for Mac OS since you need at least 1 ca cert, regardless of validity, for Python on Mac OS to use the keychain functionality in OpenSSL for validating SSL certificates. See: http://mercurial.selenic.com/wiki/CACertificates#Mac_OS_X_10.6_and_higher

<s>Unfortunately the linked URL is dead and I'm not an OSX user. I have no understanding of what this keychain bug is, or whether the work-around is still required. Ideally the DUMMY_CA workaround can be deleted outright because it no longer applies.</s>

<s>In the worst case, if we assume that the requirement for at least one dummy entry in the Darwin CA bundle is required then I would propose that it be generated at runtime on the system. In that way the user's CA certificate bundle isn't compromised by a required trust on an external entity with no audit requirements/vetting.</s>

Edit: Update, @sivel provided a working URL (https://www.mercurial-scm.org/wiki/CACertificates#Mac_OS_X_10.6_and_higher) & more explanation of the workaround.  The tl;dr is that the intention is to provide 1 dummy CA cert for Python in the case where the linked OpenSSL has been patched to use the keychain CA certs instead of the CA bundle, thereby ignoring the dummy CA cert.

Since it's still believed to be required I will highlight the primary problems with the workaround as it exists in Ansible as compared to the Mercurial version:
1. The dummy CA is **always** used for Darwin hosts, regardless of the Python/OpenSSL being used and whether it has the Keychain patch
2. The dummy CA is being prepended **along with** [the other system CA certs that can be found](https://github.com/ansible/ansible/blob/594d7d5d9d1ee77c7455ca8b5933ffe6377ca905/lib/ansible/module_utils/urls.py#L655%22L676), meaning if a system doesn't have the OpenSSL patch it will not be obvious and the dummy CA will be a trusted CA
3. The dummy CA isn't constrained in any way. It is a fully formed CA capable of issuing certificates for any domains. It should be investigated if this cert can be constrained further if it is required.

Understanding the reason for this workaround my expectation would be that a runtime generated dummy CA cert, or failing that, a maximally restricted CA cert would be used as the only CA cert in the bundle, only when the Ansible host is confirmed to be using the patched OpenSSL.

##### ACTUAL RESULTS

In effect 3b5aa8bd30a3fa84eca6141a434274b1455c591b made the commit's author the operator of a fully trusted root CA for Ansible HTTP requests on OSX.

**Comment by sivel** [comment]
The link has moved to the new mercurial domain:

https://www.mercurial-scm.org/wiki/CACertificates#Mac_OS_X_10.6_and_higher

It is still valid, and does still need to exist.

I followed exactly the steps in that URL, and it was generated without ever writing the key to disk.

I do suppose we could do something similar at run time, but the cost would be pretty large, and I don't think we can tell everyone that they must generate their own for this to work.

All in all, it is still required, the current dummy never had a saved key, and was never used to sign anything.  Although, I surely couldn't convince a security paranoid person of that 100%, as they would not have seen me do it.

However, mercurial does exactly the same thing, as referenced in their documentation: https://www.mercurial-scm.org/repo/hg/rev/d7f7f1860f00

**Comment by cpu** [comment]
> It is still valid, and does still need to exist.

Ahh. That's unfortunate.

> I do suppose we could do something similar at run time, but the cost would be pretty large, and I don't think we can tell everyone that they must generate their own for this to work.

Why do you think the cost would be pretty large? I would expect generating a 1024 bit RSA key & certificate to be a negligible one time cost.

> Although, I surely couldn't convince a security paranoid person of that 100%, as they would not have seen me do it.

I don't think this is the matter of a paranoid perspective. Authentication is a core part of HTTPS/TLS and we have to assume that if folks are using `validate_certs` their expectation is that the remote peer's identity is being authenticated using the trusted CAs on their system, not the trusted CAs + your CA with a pinky-swear that you're being honest.

> However, mercurial does exactly the same thing, as referenced in their documentation: https://www.mercurial-scm.org/repo/hg/rev/d7f7f1860f00

I wouldn't advocate for Mercurial to do this either.

**Comment by sivel** [comment]
Ansible doesn't necessarily have a place where it can guarantee it can write to and that is a permanent storage location.  It wouldn't be a one time run, it would need to happen every time that code path was executed, so if you did 300 http requests, we would end up needing to generate 300 temporarily cacerts.

I am still infavor of leaving this as is, whether this ends up is generating a new very to put in the code or not.

**Comment by cpu** [comment]
> Ansible doesn't necessarily have a place where it can guarantee it can write to and that is a permanent storage location. It wouldn't be a one time run, it would need to happen every time that code path was executed, so if you did 300 http requests, we would end up needing to generate 300 temporarily cacerts.

I'm not versed in Ansible packaging or OSX install methods, but would it not be possible for some kind of post-install hook in the packaging to generate a keypair/cert in a well-defined location when running on OSX? That keypair/cert could be loaded the same way you load the test cert now.

**Comment by sivel** [comment]
There are multiple methods of running ansible, and not all of them involve actually installing, such as running directly from a git clone.  We can't guarantee the install mechanism, which would make that complicated.

If you had multiple people running from a single git clone (which is done) you couldn't guarantee a way or place to write that file.

**Comment by cpu** [comment]
> If you had multiple people running from a single git clone (which is done) you couldn't guarantee a way or place to write that file.

That's a good point. I see the difficulty.

> The link has moved to the new mercurial domain:
> https://www.mercurial-scm.org/wiki/CACertificates#Mac_OS_X_10.6_and_higher

Re-reading this page on the active link I think I understand this a bit better ~and it _may_ be a non-issue~. If the claim about the dummy cert's purpose is accurate then on OSX systems using the system Python/OpenSSL, the local OpenSSL is patched such that it doesn't actually validate against the dumy cert, but the system keychain. 

That said, I'm still concerned that since the dummy CA is appended only based on the system being `Darwin` that hosts using a different Python/OpenSSL (which definitely happens, e.g. brew installed) instead of the system Apple OpenSSL would end up having the dummy cert in the CA bundle that *is* used. I can't verify if this is true or not without an OSX host available

**Comment by cpu** [comment]
> That said, I'm still concerned that since the dummy CA is appended only based on the system being Darwin

To expand on that, the mercurial version of this approach is gated behind this [`_plainapplepython` function](https://www.mercurial-scm.org/repo/hg/file/cdcb5747dc88/mercurial/sslutil.py#l445) that checks the interpreter path as well.

**Comment by cpu** [comment]
Thinking on this more and coming at it from another angle: The danger I'm concerned about is a case where the system _doesn't_ have the keychain patched OpenSSL or the behaviour changes one day and Ansible ends up using the CA bundle that includes your dummy CA.

Two immediate ideas to help minimize that potential danger:
1) Follow the approach taken by Mercurial: when working around this OSX corner case, only include the dummy CA cert in the bundle and no other CA certs. This is a key difference from what Ansible is doing now: including the dummy CA cert [and any additional CA certs it can find through the normal process](https://github.com/ansible/ansible/blob/594d7d5d9d1ee77c7455ca8b5933ffe6377ca905/lib/ansible/module_utils/urls.py#L655"L676). Including **just** the dummy CA ensures that if the keychain patch isn't present that all TLS connections will fail since the dummy CA is just that, a dummy. When you include the dummy CA **and** the system CAs then connections will not break if the system is no longer using the keychain and the dummy CA is a threat that would go unnoticed.
2) If the dummy CA is just a place holder it should be constrained as much as possible while still serving that purpose. For instance: Does it still work to trick the system python if the CA bit is false? Does it still work if there are name constraints & path restrictions added to make the CA only valid for ".invalid" domains? etc.

**Comment by cpu** [comment]
I've updated the original issue description slightly to include the information from the back-and-forth so far in the comments.

**Comment by cpu** [comment]
@sivel Circling back around on this. Early on when I asked if this workaround was still required you indicated it was - is that true for **all** OSX versions? A subset? How did you test?

I ask because trying to do some further software archaeology I found [a comment](https://bugs.python.org/msg254321) that indicates Python on OSX might be working around this itself since ~= 10.6
> But the much more commonly used 10.6+ installer dynamically links with the latest (but deprecated) system OpenSSL libs shipped with OS X, libs that are old but usable and still receiving Apple security fixes on current systems.  The main reason for doing that is that this solution uses the Apple-provided system and user keychains for certificate management. 

I'm not familiar with Python packaging or the OSX ecosystem and I'm having a hard time finding the relevant sourcecode to try and verify without relying on old comments on unrelated bug reports :-/

If this workaround is 100% conclusively required for at least one supported OSX version is the project open to evaluating the potential workarounds from my comment in https://github.com/ansible/ansible/issues/24152#issuecomment-298243283, or should this be closed WONT_FIX?  I don't have access to OSX hardware to test with myself but could pair with someone else to write a PR.

**Comment by bhdicaire** [comment]
Hello, do we have a status on this issue ?

@cpu : I have access to several macOS devices and I'm ready to team with someone to write a PR.

**Comment by cpu** [comment]
> Hello, do we have a status on this issue ?

As far as I know there hasn't been any change in status since my last comment.

> @cpu : I have access to several macOS devices and I'm ready to team with someone to write a PR.

@bhdicaire Awesome! This issue occasionally crosses my mind and I'd love to see it addressed.

I'm not a maintainer and haven't contributed any PRs to the project but would be happy to help team up from a planning/review perspective if that would be helpful.

At a high level I think there are two paths forward:
1) Trying to enumerate the supported OSX versions/Ansible install methods and confirming removing the workaround has no ill effects.
2) Improving the workaround to only be applied when required, and to only use the one dummy certificate for the trust store (perhaps with additional constraints applied). This is what Mercurial does.

My gut feeling is that option 1 is the best place to start. My theory is that OSX 10.6+ doesn't require this and 10.6 is quite old. It would also help find a known-affected configuration to help fine-tune the workaround if required. @bhdicaire What do you think?

**Comment by cpu** [comment]
@sivel Can you explain why this issue was closed? I believe it remains unaddressed.

**Comment by sivel** [comment]
Based on previous remarks, I believe this not to be an issue.  I had honestly forgotten about the issue until it just showed up in my inbox.  As such, I closed it.

**Comment by cpu** [comment]
>  Based on previous remarks, I believe this not to be an issue.

I disagree that it is not an issue. The workaround is not the same as employed by Mercurial: it is too broad (affecting OSX installations that may not require it), and fails open (it includes both the system CA store contents and the fake root), and ultimately may not be required at all. 

If you're not interested in discussing further I will drop the issue and assume its a WONTFIX but if you _are_ interested in continuing the discussion I'd love to understand why Ansible won't tighten the workaround to match what Mercurial does. The current workaround weakens the cryptographic properties of TLS and requires OSX users trust you on your word. That's not ideal and I don't understand the hesitation to address the problem.

**Comment by bhdicaire** [comment]
Hello @sivel , a hardcoded CA certificate is not a best practice — do you agree ?

You have done the right thing at the time.  @cpu and my myself will like to assess what can be done today.  I'll open a RADAR with Apple if no solution is available.

Are your confortable with this approach ?
