### ISSUE TITLE
get_url should support creates

### ISSUE THREAD

**Issue by Tinche** [ansible/ansible#2416]
It would be useful (and low hanging fruit) to allow the get_url module to not execute if a file path exists. I would think a common use case when fetching files is to do something with them (i.e. install them, unzip them somewhere). I might want to clean up the archive afterwards, and skip the step next time if the archive unzipped correctly (so I would need to check something other than dest).

I know there are workarounds, but I'd like my playbooks to be as minimal as possible. :)

Unfortunately I can't use the uri module (httplib2 not available in the Python standard library, nor in the default CentOS 6 repos).

**Comment by mpdehaan** [comment]
This is the force=no flag, which does not download the destination if the file already exists.

The default is force=yes

**Comment by Tinche** [comment]
I'd like to check for the existence of _other_ file(s). For example, I don't want to download software-xyz.tar.gz to /tmp if I've already previously downloaded, unzipped it to /opt/software-xyz and removed the archive from /tmp.

**Comment by bcoca** [comment]
Shell/command support creates= keyword for that purpose.

Brian Coca

**Comment by mpdehaan** [comment]
And there's also 'register', so you could use that with a file or shell
test and a conditional.

**Comment by Tinche** [comment]
... yeah but I'd rather just use a single invocation of the module that downloads files to download my file.

If I implemented this myself, would you consider it? The uri module supporting it is precedent, I suppose.

**Comment by holyjak** [comment]
As mentioned at [this](https://groups.google.com/forum/#!topicsearchin/ansible-project/get_url%7Csort:date%7Cspell:true/ansible-project/3g8l-ntn4XA) and other posts, Ansible people would like somebody to implement a generic support for creates/removes for all sever side modules. Until then, you have to use f.ex. stats, register, and when:

"I would take a patch that adds creates and removes dynamically to all server side modules using the common infra.. That would be interesting."
