### ISSUE TITLE
installation phase sphinx is required too 

### ISSUE THREAD

**Issue by Wizzzo** [ansible/ansible#24163]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
python-sphinx

##### ANSIBLE VERSION
```
ansible-2.4.0-100
```

##### SUMMARY
the python-sphinx is require to the "make rpm" step, and' it's not mentioned

**Comment by agaffney** [comment]
This is also needed for `make deb`, as of some time around 2.3 (iirc)

**Comment by abadger** [comment]
Could you post the error message that you're getting?  I'm not able to create an error message by uninstalling python-sphinx and then doing "make clean ; make rpm".

**Comment by Wizzzo** [comment]
Hi there I'm inatalling ansible on centos 7 aws image and it look like
there are a lot of missing installation..

**Comment by abadger** [comment]
We are unable to reproduce this error at this time.  We need more information about what commands you're running and what the error message is or we won't be able to figure out what the problem might be.  Thanks.

needs_info

**Comment by agaffney** [comment]
When I try to build a DEB inside a Docker container (using `ubuntu:16.04` image) without `python-sphinx` installed, I get:

```
root@95615293a534:/tmp/ansible-2.3.0.0# make local_deb
Cleaning up distutils stuff
rm -rf build
...
make[1]: Entering directory '/tmp/ansible-2.3.0.0/docs/api'
Makefile:22: *** The 'sphinx-build' command was not found. Make sure you have Sphinx installed, then set the SPHINXBUILD environment variable to point to the full path of the 'sphinx-build' executable. Alternatively you can add the directory with the executable to your PATH. If you don't have Sphinx installed, grab it from http://sphinx-doc.org/.  Stop.
```

**Comment by agaffney** [comment]
I get the same output when I run `make rpm` from that environment.

**Comment by abadger** [comment]
Ah ha!  Thanks agaffney.

@alikins It looks like this is the code causing this problem: https://github.com/ansible/ansible/blob/devel/docs/api/Makefile#L20  Since that code is at the toplevel of the Makefile, it gets invoked even on "make clean" or other make targets that don't require sphinx-build.
