### ISSUE TITLE
include_vars is broken in 2.3.0 and 2.2.2

### ISSUE THREAD

**Issue by sean-abbott** [ansible/ansible#24172]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include_vars

##### ANSIBLE VERSION

```
ansible 2.2.2.0
  config file = /home/sean/.ansible.cfg
  configured module search path = Default w/o overrides
```

and
```
ansible 2.3.0.0
  config file = /home/sean/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
~/.ansible.cfg:
```
[defaults]
roles_path = /home/sean/workspace/infra/ansible_roles
#pipelining = False

[ssh_connection]
ssh_args = -o ForwardAgent=yes
```

##### OS / ENVIRONMENT
```
env | grep ANSIBLE
ANSIBLE_VAULT_PASSWORD_FILE=/home/sean/.pd_vault_pass.txt
```

##### SUMMARY
include_vars is working with a role in 2.2.1.  It is not working in 2.2.2 or 2.3.0.

##### STEPS TO REPRODUCE

```yaml
- name: "get dynamic includes"
  include_vars: dynamic_includes.yml
- name: "debug api_jar_filename"
  debug:
    var: api_jar_filename
    verbosity: 1
```

(dynamic_includes.yml)
```yaml
---
# These variables will only work if other variables (timestamp) have been registered
release_time: "{{ timestamp.stdout }}"
release_path: "{{ finmason_api_deploy_path }}/{{ release_time }}"
api_jar_filename: "fmserver-api-{{ finmason_api_version }}-{{ git_info['git_7_hash'] }}.jar"
local_api_jar_path: "/tmp/{{ api_jar_filename }}"
```

##### EXPECTED RESULTS
From run with 2.2.1:
```
TASK [api_capr : get dynamic includes] *****************************************
ok: [10.x.x.x -> 127.0.0.1] => {"ansible_facts": {"api_jar_filename": "fmserver-api-{{ finmason_api_version }}-{{ git_info['git_7_hash'] }}.jar", "local_api_jar_path": "/tmp/{{ api_jar_filename }}", "release_path": "{{ finmason_api_deploy_path }}/{{ release_time }}", "release_time": "{{ timestamp.stdout }}"}, "changed": false}
TASK [api_capr : debug api_jar_filename] ***************************************
ok: [10.x.x.x -> 127.0.0.1] => {
    "api_jar_filename": "fmserver-api-STAT-SNAPSHOT-4e824cc.jar"
}
```

##### ACTUAL RESULTS
From ansible 2.3.0 run.  Results are identical in 2.2.2 run.

```
TASK [api_capr : get dynamic includes] *****************************************************************************************************************************************************************************
task path: /home/sean/workspace/infra/ansible_roles/api_capr/tasks/get_jar.yml:58
ok: [10.x.x.x -> 127.0.0.1] => {
    "ansible_facts": {
        "api_jar_filename": "fmserver-api-{{ finmason_api_version }}-{{ git_info['git_7_hash'] }}.jar", 
        "local_api_jar_path": "/tmp/{{ api_jar_filename }}", 
        "release_path": "{{ finmason_api_deploy_path }}/{{ release_time }}", 
        "release_time": "{{ timestamp.stdout }}"
    }, 
    "changed": false
}
TASK [api_capr : debug api_jar_filename] ***************************************************************************************************************************************************************************
task path: /home/sean/workspace/infra/ansible_roles/api_capr/tasks/get_jar.yml:66
ok: [10.x.x.x -> 127.0.0.1] => {
    "api_jar_filename": "VARIABLE IS NOT DEFINED!", 
    "changed": false
}
```

**Comment by lgfausak** [comment]
I am seeing the same thing.  I just upgraded from 2.1, most of the time the include_vars works (I do an include_vars of the same file from many different places).  So far, in one case, I have found this error.  Same kind of debug, include the file, then debug the variable that was set (worklog).  Here is the code that does the include_vars that works most of the time: 
```
    - name: get user
      delegate_to: localhost
      include_vars: "{{home}}/.vault/worklog.yml"
```
The next tasks references worklog, which is set in the yml file: 
``` 
{"worklog": {"email": "testmeila@doink.com", "pass": "12312313-9912-7312-9212-187987197913"}}
``` 
Normally this works, but in this one case it didn't.  I removed the delegate_to: localhost, and now it works for me.  I am sure it is still lurking as this bug doesn't show a delegate_to: localhost.

**Comment by bcoca** [comment]
When you delegate you are applying the task to that host, so the vars will be in `localhost`, not in `inventory_hostname`

**Comment by sean-abbott** [comment]
Actually, that seems likely/appropriate as that include is happening inside of a 

```
- include: get_jar.yml
  tags:
    - "get_jar"
  run_once: "true"
delegate_to: 127.0.0.1
```

**Comment by sean-abbott** [comment]
I was having another bug where delegate_facts isn't working.  I wonder if they're related.

**Comment by sean-abbott** [comment]
Yes, but in my example both the include_vars and the debug statement are both in the "get_jar" playbook above.  The latter immediately follows the former, and they are both delegated to localhost.

**Comment by bcoca** [comment]
delgation does not mean you get all vars, only connection vars, the rest of the vars are from the `inventory_hostname`

**Comment by sean-abbott** [comment]
...So then was this "broken" in 2.2.1?  Because this is a playbook I've been using daliy for 6 months.  It makes sense that if I set a var in a playbook in it's entirety being run against a particular host, that var would be available for the rest of the same playbook. It doesn't make any sense for it to disappear immediately after it's set.

**Comment by bcoca** [comment]
it does not disappear, its set in `localhost`, using `hostvars['localhost']['api_jar_filename']` should show the value.

We did fix several issues with the surrounding code, I'm unclear on which is the 'correct way' as we also have `delegate_facts` to consider in this case. I see several options:

- We ignore `delegate_to` when it is an `include_vars` task (we do this already with add_host/group_by/etc) (<2.3 behaviour)
- We ignore `delegate_to` except when `delegate_facts=True`
- We use `delegate_to` to apply the variables to that host when using `include_vars` (current 2.3 behaviour)

**Comment by sean-abbott** [comment]
There may be a counterexample available, but I would say that "delegate_to", logically also delegates the facts. I suppose I can also imagine examples of wanting to be able to delegate a fact from within a delegated action (i.e., I delegate_to localhost, but I DO want the fact delegated back from local host to remote host), but I think the least surprising option is that delegate_to also delegates the variables.

IMO, anyway.  :-)  thank you for the pointer!

**Comment by bcoca** [comment]
@sean-abbott delegate_to is not meant to totally substitute the host, just the execution target, hence it always keeps the original host 'context' with the exception of what is needed to alter the execution (connection vars). 

For example you might want to remove a host from the load balancer, so you delegate_to the loadbalancer and use `ansible_host`  to remove the actual IP of the original host, in your scenario the load balancer would only be able to 'remove itself'.

**Comment by sean-abbott** [comment]
While I understand that this isn't how it works, I do wish that when you delegate a set of things (i.e., via an included playbook), that the set en masse would be delegates, rather than logically applying a delegate to each individual action. I think it would allow more fine-grained control and choice of where to run actions, and be much more intuitive. But this obviously works, so oh well.

Again, thank you!

**Comment by sean-abbott** [comment]
...Is there any way to delegate a fact to the global facts, then? Because this is mixing and matching things that I (might) get from group_vars in the inventory and things that I am dynamically setting, apparently tagged specifically to `host localhost`.

**Comment by bcoca** [comment]
There are no "global facts", facts and inventory vars are per host, 'play vars' are across hosts.

**Comment by sean-abbott** [comment]
Is there a way to delegate facts to "play vars", then?

The issue I have with your counter example is that it can be encapsulated in a single task. What I'm doing is dynamically assessing what version of a jar is built according to the state of a git repository and downloading the jar from an artifactory server that my targets hosts (on a separate network) don't have direct access to, before distributing that file to the target hosts from the control (localhost).  It's of necessity a number of different tasks. 

In the apparently "buggy" way, I simply delegated a playbook to localhost, that playbook gathered information and grabbed the jar in a completely intuitive manner. It registered variables and then referenced those variables.  NBD.

Now, I'm trying to figure out all the places that facts are being delegated to some host and hard code a lookup against that host, which also vastly reduces the reusability of the includes, because now I can ONLY include them if they are delegated to localhost.

I still don't find the new (apparently correct) behavior in the slightest bit intuitive. And it's looking like I'm going to need to break this into two roles; one to fetch the jar and one to distribute it. And probably replicate the work to determine the version information.

Or maybe I'm being stupid, I dunno. But no way I can imagine to accomplish this is nearly as neat and straightforward as the "buggy" way.

**Comment by sean-abbott** [comment]
...annnnnddd now, my include_vars isn't even recognizing I'm trying to interpolate variables:

```
TASK [api_capr : debug api_jar_filename] ***********************************************************
ok: [10.30.0.180 -> 127.0.0.1] => {
    "changed": false, 
    "hostvars['localhost']['api_jar_filename']": "fmserver-api-{{ finmason_api_version }}-{{ git_info['git_7_hash'] }}.jar"
}
```

Which is literally resulting in a file name `fmserver-api-{{ fm_api_version }}-{{ git_info['git_7_hash'] }}.jar`

**Comment by sean-abbott** [comment]
So what do I have to do to use include_vars from inside a delegated task and have it interpolate?

**Comment by bcoca** [comment]
or try my PR above

**Comment by sean-abbott** [comment]
Ok, so as far as I can tell, in my setup, "include_vars" does not interpolate other variables (so it cannot be used to set new variables from old variables, and the vars that do get set are set in host vars.

But, set_fact sets play facts which are used without needing to reference localhost.

I'll give the PR a shot.

Also, apologies for having frustration blinders on and not seeing that the above reference was a PR. That was dumb of me.

**Comment by bcoca** [comment]
include_vars (as most modules) doesn't do ANY templating/substitution, that happens at the moment of consumption. Templating happens when a task is 'compiled'.

Also note that if you are setting a var in `localhost` but then want it to resolve in the `inventory_hostname` the  vars you depend on need to be available in the latter.

**Comment by sean-abbott** [comment]
Yes, the PR covers it. The PR also reverts to the behavior where include_vars interpolates variables successfully.

**Comment by bcoca** [comment]
As I mention above, it is not `include_vars` doing it, my PR makes it so the 'new behaviour' can be achieved if you set `delegate_facts: True` and keeps the old behaviour otherwise (which actually ignores `delegate_to` for `include_vars`). So all the vars are present in `inventory_hostname` and it works as it did before.

**Comment by sean-abbott** [comment]
I am describing the behavior from the point of a user. From that POV, in one case I call include vars with `{{ variable }}`s inside of it, and I get variables back that have interpolated those calls into new strings.  In the other case, I get strings that include the original double curly braces.  So regardless of what the code is doing, this is what is happening as a user.

**Comment by lgfausak** [comment]
I am confused as to why my delegation to localhost only failed in one case. Other cases worked. Same file. Weird.
