### ISSUE TITLE
Create a module for OVN

### ISSUE THREAD

**Issue by rcarrillocruz** [ansible/ansible#24195]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ovn

##### SUMMARY

We have modules to manage OVS, there is a project called OVN that is intended to extend its capabilities:

http://openvswitch.org/support/dist-docs/ovn-architecture.7.html

Would be good to have modules for that.

**Comment by keithnoguchi** [comment]
Woohoo!

Any private repo we can play with?  I'm more than happy to do the shot! :)

Thank you, team Ansible!

**Comment by roolebo** [comment]
FYI, I have a WIP repo with a subset of OVN modules: https://github.com/roolebo/ovn-ansible
