### ISSUE TITLE
Unable to read inventory group with hosts and groups

### ISSUE THREAD

**Issue by dtolj** [ansible/ansible#24222]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

hosts file

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

RHEL7

##### SUMMARY

I have a hosts file that contains the following outline:

[dmz]
192.168.3.4

[prod:children]
dmz
192.168.3.3

However I get an error
Attempted to read "../hosts" as ini file: ../hosts:6: Section [prod:children] includes undefined group: 

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by sivel** [comment]
As the error indicates, you included a value `192.168.3.3` as a child of the `prod` group.  Children can only be other defined groups, and `192.168.3.3` would be a host.

Instead you may want:

```
[dmz]
192.168.3.4

[prod:children]
dmz

[prod]
192.168.3.3
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
