### ISSUE TITLE
lot of Duplicate tags in ansible galaxy

### ISSUE THREAD

**Issue by roumano** [ansible/ansible#24224]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ansible galaxy tags

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides

```

##### SUMMARY
Lot of duplicate tags in ansible galaxy

fixing this issue will permit a better visibility of roles, less pages, easier to find a role.

##### STEPS TO REPRODUCE
Download all page of tags : 

```yaml
max=$(curl "https://galaxy.ansible.com/api/v1/tags/?page=1&format=json" | jq '.num_pages')
> /tmp/1.json
for i in $(seq 1 $max );do curl "https://galaxy.ansible.com/api/v1/tags/?page=${i}&format=json" >> /tmp/1.json; done
```
See few duplicates : 
```
cat /tmp/1.json | jq -r '.results[].name' | grep -i raspberry
raspberry
raspberrypi
RaspberryPi
RaspberryPI

cat /tmp/1.son | jq -r '.results[].name' | grep -i ec2
ec2
EC2


```

##### EXPECTED RESULTS
cat /tmp/1.json | jq -r '.results[].name' | grep -i raspberry
raspberrypi

cat /tmp/1 | jq -r '.results[].name' | grep -i ec2
ec2

##### ACTUAL RESULTS

```

```

**Comment by sivel** [comment]
This repository is for the ansible project. For galaxy issues, please report this at https://github.com/ansible/galaxy-issues
