### ISSUE TITLE
Multiple ranges in a host pattern cause Ansible process to hang forever

### ISSUE THREAD

**Issue by c-mart** [ansible/ansible#24274]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
inventory

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /opt/dev/atmosphere-ansible/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION
Contents of ansible.cfg (I suspect not relevant here):
```
[defaults]
hostfile       = /opt/dev/atmosphere-ansible/ansible/hosts
library        = /usr/share/ansible
remote_tmp     = $HOME/.ansible/tmp
pattern        = *
forks          = 45
poll_interval  = 15
sudo_user      = root
transport      = smart
remote_port    = 22
module_lang    = C
retry_files_enabled = False
gathering = smart
roles_path = /opt/dev/atmosphere-ansible/ansible/roles
host_key_checking = False
sudo_exe = sudo
timeout = 10
log_path = /opt/dev/atmosphere/logs/ansible.log
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
action_plugins     = /usr/share/ansible_plugins/action_plugins
callback_plugins   = /opt/env/atmo/lib/python2.7/site-packages/subspace/plugins/callback:/usr/share/ansible_plugins/callback_plugins
connection_plugins = /usr/share/ansible_plugins/connection_plugins
lookup_plugins     = /usr/share/ansible_plugins/lookup_plugins
vars_plugins       = /usr/share/ansible_plugins/vars_plugins
filter_plugins     = /usr/share/ansible_plugins/filter_plugins
strategy_plugins   = /opt/env/atmo/lib/python2.7/site-packages/subspace/plugins/strategy:/usr/share/ansible/plugins/strategy
callback_whitelist = play_logger
nocows = 1
cow_selection = random
fact_caching = redis
fact_caching_timeout = 14400

[ssh_connection]
ssh_args = -o ForwardAgent=yes -o ControlMaster=auto -o StrictHostKeyChecking=no -o ControlPersist=60s
pipelining = True

[accelerate]
accelerate_port = 5099
accelerate_timeout = 30
accelerate_connect_timeout = 5.0
accelerate_daemon_timeout = 30
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY

It's unclear whether Ansible supports multiple ranges in a single host pattern in an inventory file. [This commit](https://github.com/ansible/ansible/commit/25822330a2642eacebde1c038561913ba9d0b9db#diff-a7f77993e47c1039ce36f70242824e1a) ("Add support for multiple ranges in a host") suggests so, but I suspect that [this comment in expand_hosts.py](https://github.com/ansible/ansible/blob/6787fc70a643fb6e2bdd2c6a6202072d21db72ef/lib/ansible/inventory/expand_hosts.py#L72-L77) is a "todo" rather than a "tada".

In reality, it appears that multiple ranges in a host pattern (e.g. `128.110.[2:255].[2:255]`) results in some kind of parsing error that causes the `ansible` process to hang indefinitely. This occurs whenever the multiple-range host pattern is in inventory, even when Ansible is run against a different host pattern in the same inventory file.

Digging into the code, it looks like only the first square-bracketed range in a host pattern is expanded [here](https://github.com/ansible/ansible/blob/6787fc70a643fb6e2bdd2c6a6202072d21db72ef/lib/ansible/inventory/expand_hosts.py#L79).
```
(head, nrange, tail) = line.replace('[','|',1).replace(']','|',1).split('|')
```

##### STEPS TO REPRODUCE
Make an inventory file like this:

```
[testing]
vm0 ansible_host=192.168.1.2
[cloudlab]
192.168.[2:255].[2:255]
```

Then try to run any Ansible against any of the hosts, even the one which doesn't have multiple ranges in its pattern.

```
ansible vm0 -m ping -vvvv
```

##### EXPECTED RESULTS
Anything that isn't "process hangs forever". At minimum, throw an exception and tell me that I have invalid syntax in my inventory file.

It would be especially nice if multiple ranges in a host pattern were expanded N-dimensionally -- so that `192.168.[10:15].[10:15]` was expanded to `192.168.10.10` through `192.168.10.15`, `192.168.11.10` through `192.168.11.15`, and so forth. But that would be a feature request, this is a bug report.

##### ACTUAL RESULTS
```
(atmo) root@vagrant-ubuntu-trusty-64:/opt/dev/atmosphere-ansible/ansible# ansible vm0 -m ping -vvvv
Using /opt/dev/atmosphere-ansible/ansible/ansible.cfg as config file
```
This hangs forever and the `ansible` process pegs the CPU. Ctrl-C results in
```
[ERROR]: User interrupted execution
```

**Comment by nitzmahone** [comment]
Not a bug (at least, not what you've reported): the problem is that you're dynamically adding ~65000 hosts to the inventory. If you try this with saner value ranges, it works fine- I tested values that result in several thousand hosts successfully, eg: 
```
[blar]
192.168.[1:255].[1:15] ansible_connection=local
```

Do you actually have 65000 hosts you're trying to manage?

**Comment by c-mart** [comment]
> Do you actually have 65000 hosts you're trying to manage?

No, not even close. We have an "on-demand private clouds" provider ([CloudLab](https://www.cloudlab.us/)) and we don't quite know which IP range will be allocated to our cloud instances in advance of each Experiment. Our [application which calls Ansible](https://github.com/cyverse/subspace) passes a 'limit hosts' argument at runtime which restricts execution to just one host (currently). I think we just need the broad host patterns in inventory so that we can set group_vars which are specific to a given cloud provider, and the overall IP range for that provider may be quite large.

I'll take a closer look with my colleague, perhaps there's a way we can tighten up the host pattern using something like dynamic inventory. I'm closing this one as I may not get to it for a bit and want to keep the noise down.

Thanks for the triage, @nitzmahone!

**Comment by nitzmahone** [comment]
No worries- I was going to suggest dynamic inventory as a better way to handle this, so you're not actually allocating all those bogus hosts in the Ansible inventory. It'll definitely speed things up!
