### ISSUE TITLE
Var "ansible_fqdn" not getting correct value

### ISSUE THREAD

**Issue by pas256** [ansible/ansible#243]
It looks like the template var "ansible_fqdn" is not getting the correct value from the system (at least not on Ubuntu 11.10).

Here what ansible has:

```
"ansible_fqdn": "domU-12-31-39-04-D6-A1", 
"ansible_hostname": "domU-12-31-39-04-D6-A1", 
```

But here is the output from `hostname` and `hostname -f`

```
$ hostname
domU-12-31-39-04-D6-A1
$ hostname -f
domU-12-31-39-04-D6-A1.compute-1.internal
```

So the correct value should be `domU-12-31-39-04-D6-A1.compute-1.internal`.

As a comparison, I also tried `facter`, and it reports the correct value.

This is on the "devel" branch.

**Comment by mpdehaan** [comment]
Giving this to sfromm as he did the fact stuff.   sfromm -- if you don't have cycles or don't want to take this, let me know and I'll fix it.

Thanks for the report!

**Comment by sfromm** [comment]
The hostname is derived from socket.gethostname().  I suppose we could try platform.uname() as an alternative.

pas256, what does this give you:

```
python -c 'import platform; print platform.uname()[1]'
```

**Comment by sfromm** [comment]
On a related subject, how well does setup detect the virtualization type and role?

**Comment by dne** [comment]
Use [`socket.getfqdn()`](http://docs.python.org/library/socket.html?highlight=fqdn#socket.getfqdn).

**Comment by sfromm** [comment]
Found a host configured a bit differently and socket.getfqdn() is a better option.  I'll send a patch momentarily.
