### ISSUE TITLE
Ansible is silently skipping hosts on two tasks in a playbook

### ISSUE THREAD

**Issue by ilana1291** [ansible/ansible#24320]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-playbook

##### ANSIBLE VERSION
ansible 2.2.0.1

##### OS / ENVIRONMENT
Linux

##### SUMMARY
We are using Ansible for our deployment activities but we are facing this bug that can cause huge issues in Production environments. After the untar step of the package on the 5 hosts, there are two tasks that run post-deploy steps. The post-deploy step is only being run on some of the servers, sometimes 1 server, another time 2 severs. In the log I attached, it only ran on 2 hosts.

##### STEPS TO REPRODUCE
``

**Comment by jctanner** [comment]
@ilana1291 what are the command args you pass to ansible-playbook?

needs_info

**Comment by ilana1291** [comment]
/Data/ansible/playbooks/prod_releases/unix_deployment_playbook.yml -vvvv -i /Data/ansible/configs/BPG.inventory -e "group_name=tpc" -e "ansible_root_dir=/Data/" -e "sccb_identifier=78345" -e "date_time=05_08_07" -e "nexus_url=['url']" -e "pre_deploy_script=NoneFound" -e "post_deploy_script=NoneFound" -e "package_name=['package']" -e "target_env=prod" -e "env_pre_deploy_script_url=url" -e "env_post_deploy_script_url=url" -e "env_pre_deploy_script_name=pre_deploy_script.sh" -e "env_post_deploy_script_name=post_deploy_script.sh"

**Comment by ilana1291** [comment]
I didn't add the urls or package names that I used but that is the command with the parameters. thanks
