### ISSUE TITLE
Ubuntu 17.04 Zesty Zapus deb packages in ppa:ansible/ansible

### ISSUE THREAD

**Issue by jorisoverzet** [ansible/ansible#24322]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

N/A

##### ANSIBLE VERSION

N/A

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Ubuntu 17.04 Zesty Zapus

##### SUMMARY
There is no Ubuntu 17.04 Zesty Zapus configured in the official Ansible PPA repository at launchpad.net. (http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/)

##### STEPS TO REPRODUCE

```yaml
sudo apt-add-repository ppa:ansible/ansible
sudo apt update
```

##### EXPECTED RESULTS

Ansible package list downloaded successfully.
(This makes it's possible to install the latest version (currently 2.3.n.n.) instead of the version in the ubuntu repository (2.2.1.0))

##### ACTUAL RESULTS

```
E: The repository 'http://ppa.launchpad.net/ansible/ansible/ubuntu zesty Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

**Comment by jorisoverzet** [comment]
Is there anything I can do to help to get this resolved?

**Comment by vpassapera** [comment]
Would like latest ansible on 17.04 as well please, currently have to dl yakkety deb and manually install :(

**Comment by maximbaele** [comment]
Issue still persists..

**Comment by sivel** [comment]
cc @shanemcd

**Comment by bertramn** [comment]
I usually install the latest ansible packages from PyPi. Works like a bought one on Zesty.

```sh
sudo apt install python-pip libssl-dev make gcc
sudo pip install -U pip setuptools wheel
sudo pip install ansible

ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by shanemcd** [comment]
Zesty build is now on Launchpad: https://launchpad.net/~ansible/+archive/ubuntu/ansible

@jctanner @sivel I think this issue can be closed now.

**Comment by jimi-c** [comment]
Closed per the above.

Thanks!

**Comment by ghost** [comment]
Broke :(
