### ISSUE TITLE
Yum doesn't see new packages with long name

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#24330]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
`modules/packaging/os/yum.py`

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Jun 24 2015, 00:41:19) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### OS / ENVIRONMENT
CentOS7
```
$ rpm -qi ansible
Name        : ansible
Version     : 2.3.0.0
Release     : 1.el7
Architecture: noarch
Install Date: Tue 18 Apr 2017 02:21:15 AM PDT
Group       : Development/Libraries
Size        : 28579660
License     : GPLv3+
Signature   : RSA/SHA256, Wed 12 Apr 2017 03:12:54 PM PDT, Key ID 6a2faea2352c64e5
Source RPM  : ansible-2.3.0.0-1.el7.src.rpm
Build Date  : Wed 12 Apr 2017 02:06:18 PM PDT
Build Host  : buildhw-09.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://ansible.com
Summary     : SSH-based configuration management, deployment, and task execution system
Description :

Ansible is a radically simple model-driven configuration management,
multi-node deployment, and remote task execution system. Ansible works
over SSH and does not require any software or daemons to be installed
on remote nodes. Extension modules can be written in any language and
are transferred to managed machines automatically.
```

##### SUMMARY
When trying to get latest version of a package on target server, ansible doesn't report any new version, even though `yum check-update` does. The package name and repository name are long and I can see (when doing print debugging) ansible gets them broken into multiple lines. I can also see the regex that is supposed to fix this isn't working correctly and puts `'\x01'` in the output instead.

##### STEPS TO REPRODUCE
One way to reproduce is to setup new CentOS7, add repository with long name and update package with long name via ansible yum module.

Since this is troublesome (I have done this in our production, but I don't expect anyone to create the same environment to test this), it is possible to just try the regex in question, located in `modules/packaging/os/yum.py::parse_check_output()` function.

```
>>> re.sub('\n[^\w]\W+(.*)', ' \1', '\n  abc')
' \x01'
```

Obviously, there should be `r` literal like so.

```
>>> re.sub(r'\n[^\w]\W+(.*)', r' \1', '\n  abc')
' abc'
```

##### EXPECTED RESULTS
Multi-line output of `yum check-update` is properly parsed by the `parse_check_output()`  function.

##### ACTUAL RESULTS
The parsing function breaks the output and omits packages with long names.

Related issues: #20608, #20043

**Comment by jctanner** [comment]
resolved_by_pr https://github.com/ansible/ansible/issues/24331

**Comment by alikins** [comment]
What kind of package names and/or environment are you seeing this fail with?

Do the test/units/modules/os/packages/test_yum.py unit tests pass? Curious why they dont seem to fail in CI.

**Comment by alikins** [comment]
ie, looking for additional test cases to include in the unit tests

**Comment by ghost** [comment]
This is the content of `check_update_output` passed into `parse_check_update()` function:
```
"Loaded plugins: fastestmirror, priorities, rhnplugin\nThis system is receiving updates from RHN Classic or Red Hat Satellite.\nLoading mirror speeds from cached hostfile\n\nAAAAAAAAA-AA-AAAAAAA-AAAAA.noarch\n                        1.16-1            AAAAAAAAAAA-AAA-AAAAAAAAAA-AAAAA      \nglibc.x86_64            2.17-157.el7_3.1  AAAAAAAAAAA-AAA-AAA-AAAAAAAAA-AAAAA-AA\nglibc-common.x86_64     2.17-157.el7_3.1  AAAAAAAAAAA-AAA-AAA-AAAAAAAAA-AAAAA-AA\nlibselinux-utils.x86_64 2.5-6.el7         AAAAAAAAAAA-AAA-AAA-AAAAAAAAA-AAAAA-AA\nlibsemanage.x86_64      2.5-5.1.el7_3     AAAAAAAAAAA-AAA-AAA-AAAAAAAAA-AAAAA-AA\nlibsepol.x86_64         2.5-6.el7         AAAAAAAAAAA-AAA-AAA-AAAAAAAAA-AAAAA-AA\npolicycoreutils.x86_64  2.5-11.el7_3      AAAAAAAAAAA-AAA-AAA-AAAAAAAAA-AAAAA-AA\npython2-boto3.noarch    1.4.4-1.el7       centos7.2_x86_64                      \npython2-botocore.noarch 1.5.26-1.el7      centos7.2_x86_64                      \npython2-crypto.x86_64   2.6.1-13.el7      centos7.2_x86_64                      \npython2-paramiko.noarch 1.16.1-2.el7      centos7.2_x86_64                      \npython2-s3transfer.noarch\n                        0.1.10-1.el7      centos7.2_x86_64                      \nredis.x86_64            3.2.3-1.el7       centos7.2_x86_64                      \nselinux-policy.noarch   3.13.1-102.el7_3.4\n                                          AAAAAAAAAAA-AAA-AAA-AAAAAAAAA-AAAAA-AA\nselinux-policy-targeted.noarch\n                        3.13.1-102.el7_3.4\n                                          AAAAAAAAAAA-AAA-AAA-AAAAAAAAA-AAAAA-AA\n"
```
(I censored some non-public information, but the length of package names and repositories matches)

When I leave the original `re.sub(..., ' \1', check_update_output)`, it fails to see changes (and the task is only "ok"), but when I change the `repl` to `r' \1'`, next ansible run gives me `changed` on given task and the package is seen to be updateable.

I can only run tests against my system-wide ansible, which is 2.3.0.0-5 (on Archlinux)
```
$ py.test-2.7 -sv test_yum.py 
=========================================================================== test session starts ===========================================================================
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.33, pluggy-0.4.0 -- /usr/bin/python2
cachedir: ../../../../../.cache
rootdir: /home/mk/dev/ansible, inifile:
plugins: cov-2.4.0
collected 8 items 

test_yum.py::TestYumUpdateCheckParse::test_empty_output PASSED
test_yum.py::TestYumUpdateCheckParse::test_plugin_load_error PASSED
test_yum.py::TestYumUpdateCheckParse::test_wrapped_output_1 PASSED
test_yum.py::TestYumUpdateCheckParse::test_wrapped_output_2 PASSED
test_yum.py::TestYumUpdateCheckParse::test_wrapped_output_3 PASSED
test_yum.py::TestYumUpdateCheckParse::test_wrapped_output_4 PASSED
test_yum.py::TestYumUpdateCheckParse::test_wrapped_output_rhel7 PASSED
test_yum.py::TestYumUpdateCheckParse::test_wrapped_output_rhel7_obsoletes PASSED

======================================================================== 8 passed in 0.06 seconds =========================================================================
```

**Comment by ghost** [comment]
I managed to write unit test using part of the output, should I submit it too? It doesn't pass without the fix and passed with it.

**Comment by alikins** [comment]
> I managed to write unit test using part of the output, should I submit it too? It doesn't pass without the fix and passed with it.

@mkopta That would be awesome!

**Comment by ghost** [comment]
Good, submitted as #24346 .
