### ISSUE TITLE
chdir arg for script

### ISSUE THREAD

**Issue by thanatos** [ansible/ansible#24348]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
`script` module

##### ANSIBLE VERSION

```
» ansible --version
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The `command` and `shell` modules support the `chdir` argument, but `script` does not. This is kind of jarring, and can be worked around for sure, but it would be nice to have it.

**Comment by abadger** [comment]
https://github.com/ansible/ansible/pull/26436 was merged so closing this.
