### ISSUE TITLE
contrib/inventory/vmware_inventory.py is missing GPL license header

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#24343]
contrib/inventory/vmware_inventory.py is missing GPL license header

Authors involved:

@cgar
@hryamzik
@mattclay
@Shaps
@rafstef
@nerzhul
@jctanner
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
contrib/inventory/vmware_inventory.py

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by gundalow** [comment]
Shaps is going to fix this

**Comment by gundalow** [comment]
resolved_by_pr 24443
