### ISSUE TITLE
Some applications don't restart using service state=restarted

### ISSUE THREAD

**Issue by jeviolle** [ansible/ansible#2435]
For applications that are slow to stop, the service "restart" doesn't actually start the service back up and leaves the service off.

I have a patch available for the service module for review that provide an option for a restart delay to allow the user to control how many seconds before attempting a start after the application is stopped.

**Comment by mpdehaan** [comment]
Sounds reasonable.

Just curious -- It seems an init script should actually wait for the service to be stopped.  which applications?

**Comment by jeviolle** [comment]
The script I've noticed it on was on any of the sensu init scripts, for example sensu-server,  from the omnibus packages. The restart method sets a max wait time, executes stop and then status checks every second to short circuit if it stops sooner.

Just out of curiosity, if I have a patch is the appropriate steps to fork and add the patch?

**Comment by bcoca** [comment]
Some bad init scripts return w/o verifying a stop, just send the term
signal to the pid and 'assume' all is well.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
Yes, a fork + a pull request is ideal.

Thanks!

**Comment by jeviolle** [comment]
pull request sent.

**Comment by mpdehaan** [comment]
closing ticket since we now have the pull request ticket, thank you!
