### ISSUE TITLE
ec2.py Script .ini Filename Incorrectly Generated

### ISSUE THREAD

**Issue by mattmonkey83** [ansible/ansible#24396]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2.py Dynamic Inventory Script

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION

Defaults
##### OS / ENVIRONMENT

N/A
##### SUMMARY

This PR has broken the expected behaviour for the `ec2.py` Dynamic Inventory script - https://github.com/ansible/ansible/pull/21567/files

The docs recommend the following -
>The second option is to copy the script to /etc/ansible/hosts and chmod +x it. You will also need to copy the ec2.ini file to /etc/ansible/ec2.ini. Then you can run ansible as you would normally.

Since this PR was merged the script looks for a corresponding `.ini` (in the same directory) based on the script filename rather than previous default of `ec2.ini`.

Therefore if the docs are followed as quoted above it is looking for `/etc/ansible/hosts.ini` rather than `/etc/ansible/ec2.ini`.
##### STEPS TO REPRODUCE

1. Copy `ec2.py` to `/etc/ansible/hosts` and `chmod +x` it
2. Copy `ec2.ini` to `/etc/ansible/ec2.ini`
3. Run `/etc/ansible/hosts --list`

##### EXPECTED RESULTS

Entire ec2 Inventory should be output in JSON format.
##### ACTUAL RESULTS

Script fails with the following Traceback -

```
$ /etc/ansible/hosts --list
Traceback (most recent call last):
  File "/etc/ansible/hosts", line 1587, in <module>
    Ec2Inventory()
  File "/etc/ansible/hosts", line 181, in __init__
    self.read_settings()
  File "/etc/ansible/hosts", line 252, in read_settings
    configRegions = config.get('ec2', 'regions')
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'ec2'
```

**Comment by ryansb** [comment]
I thought when we introduced that change to look for an ini-file matching its own name that it was supposed to fall back to ec2.ini, but it seems it isn't. 

In the meantime, you can either rename to hosts.ini, or use an older version of the dynamic inventory script.

**Comment by mattmonkey83** [comment]
Yeah we've managed to workaround using a symlink from `hosts.ini` to `ec2.ini` but it did have us scratching our heads for about a day.

Side note - The error isn't particularly helpful - It would have been easier to troubleshoot if it said file not found or similar.

**Comment by mattmonkey83** [comment]
Finally got round to testing the fix - Works perfectly.  Thanks all 😄
