### ISSUE TITLE
How to not display verbose out put when i use the with_items

### ISSUE THREAD

**Issue by kannarajesh26** [ansible/ansible#24416]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```

```

##### SUMMARY

i am using register when i am also using the with_items, but when i display the out put using the debug, it is displaying the weird output, i dont want all that output though, i just need the regular output.
please dont close this issue.,.. i need the correct code to use. i even opened in google groups but no one helped me so far. 
##### STEPS TO REPRODUCE

    -
      name: "Messaging Server Status in messaging node-1"
      shell: "{{ appprofile_home }}/serverStatus.sh {{ item.msgsrvname }}"
      with_items:
        - { msgsrvname: 'hix_ezaudit.Messaging.mnsure-stst2-med-esb-v01Node01.0' }
        - { msgsrvname: 'hix_esor.Messaging.mnsure-stst2-med-esb-v01Node01.0' }
        - { msgsrvname: 'hix_state.Messaging.mnsure-stst2-med-esb-v01Node01.0' }
        - { msgsrvname: 'hix_fedhub.Messaging.mnsure-stst2-med-esb-v01Node01.0' }
        - { msgsrvname: 'hix_cots.Messaging.mnsure-stst2-med-esb-v01Node01.0' }
      register: messagesrvstatus
    -
      debug: msg= {{ item.stdout }}
      with_items: "{{ messagesrvstatus.results }}"

##### ACTUAL RESULTS

```

```

**Comment by abadger** [comment]
Need information about what you are expecting as output versus what output is actually being given.

needs_info

**Comment by abadger** [comment]
Also, this really is a user question so it is much more likely that you'll get actual help on the google group than here.

**Comment by abadger** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
