### ISSUE TITLE
Service module cannot start ActiveMQ.

### ISSUE THREAD

**Issue by dbrossard** [ansible/ansible#2443]
When trying to use the service module to start ActiveMQ that was not installed from a repo but is correctly installed in init.d and upstart on Ubuntu 12.04

I get the error: 

<pre>
10.51.10.77 | FAILED >> {
    "failed": true, 
    "msg": "failed determining the current service state => state stays unchanged"
}
</pre>

Here is my trouble shooting steps on a test server called 'deleteme3'

<pre>
dbrossard@pdx-sysmgmt:/usr/local/playbooks$ ssh 10.51.10.77
dbrossard@deleteme3:~$ service activemq status
ActiveMQ Broker is not running.
dbrossard@deleteme3:~$ sudo /etc/init.d/activemq status
ActiveMQ Broker is not running.
dbrossard@deleteme3:~$ logout
Connection to 10.51.10.77 closed.
dbrossard@pdx-sysmgmt:/usr/local/playbooks$ ansible Temp -K -m service -a "name=activemq state=started"
10.51.10.77 | FAILED >> {
    "failed": true, 
    "msg": "failed determining the current service state => state stays unchanged"
}
</pre>

As you can see upstart and init.d both correctly display the status as "not running" but ansible does not. The work around of course is to use "pattern"

<pre>
dbrossard@pdx-sysmgmt:/usr/local/playbooks$ ansible Temp -K -m service -a "name=activemq state=stopped pattern=mq"
10.51.10.77 | success >> {
    "changed": true, 
    "name": "activemq", 
    "state": "stopped"
}
</pre>

**Comment by mpdehaan** [comment]
Can you please paste the output of 'ansible --version'  ?

This seems to be a quite old error message and you  may have better luck running with what is in git.   We are releasing in a couple of weeks and 1.1 is quite stable, but the service module has been recently retooled which is why I suggest you check it out.

(I'd say 60-70% of everyone actually runs from the latest git versions now)

Let me know if that doesn't straighten things out.

**Comment by dbrossard** [comment]
I am on the previous version 1.0. I didn't see a previous bug report so if it's already been fixed then please ignore.

<pre>dbrossard@pdx-sysmgmt:/usr/local/playbooks$ ansible --version
ansible 1.0</pre>

Thanks

**Comment by mpdehaan** [comment]
Ok, you should be good on 1.1, it's coming out in a few weeks.

As a temporary workaround you can use the 'shell' module to launch the service commands ...you may also want to check the release1.0 branch as I believe there is a service detection fix on that branch that may also fix this issue.
