### ISSUE TITLE
Systemd module doesn't check real service status after start

### ISSUE THREAD

**Issue by pablo-ruth** [ansible/ansible#24450]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module systemd

##### ANSIBLE VERSION
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
Ubuntu 16.04 -> Ubuntu 16.04

##### STEPS TO REPRODUCE

Create a new systemd service in _/etc/systemd/system/fake.service_
```
[Unit]
Description=Fake unit
[Service]
ExecStart=/bin/false
```

Create a task to start the service
```
- systemd:
    name: fake
    daemon_reload: yes
    state: started
```

Execution return "changed"
```
TASK [systemd] ***************************************************
changed: [localhost]
```

But if I check with systemctl, the service failed to start
```
systemctl status fake
● fake.service - Fake unit
   Loaded: loaded (/etc/systemd/system/fake.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2017-05-10 17:37:01 CEST; 2min 21s ago
  Process: 16764 ExecStart=/bin/false (code=exited, status=1/FAILURE)
 Main PID: 16764 (code=exited, status=1/FAILURE)
```

##### EXPECTED RESULTS
I expect ansible to fail if service start failed
```
TASK [systemd] *******************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "fake service failed to start"}
```

##### ACTUAL RESULTS
Ansible just return "changed" at each execution
```
TASK [systemd] ***************************************************
changed: [localhost]
```

**Comment by smeapng** [comment]
+1

**Comment by gundalow** [comment]
resolved_by_pr 24452

**Comment by mafalb** [comment]
I was bitten by this behaviour with raspbians bind9.service unit, that's how I came here.
I found another PR #24778 about this issue.

What #24452 does is doing a `systemctl status` but you really do not know how long it takes for the service to fail. e.g. think for dns resolver timeout or network timeouts in general, such things can take several seconds. How long should ansible sleep?

The example service above has implicit Type=simple, see systemd.service(5). One could argue that the described behaviour (do not wait for failure) could be on purpose and that it would have been possible to set an appropriate Type, see systemd.service(5) . Type=oneshot could work in this example case.

So, I am not sure if it's so simple to fix as #24452 is suggesting or if it is fixable at all or if the responsibility should be handed to the service unit authors.

**Comment by harmathy** [comment]
Systemd units have mainly two states. One is the *load state* which reflects if the unit file was properly loaded from disk. The second is the *active state* which corresponds to the current state of the unit. This state is one of *active*, *reloading*, *inactive*, *failed*, *activating* and *deactivating*.

As you can see, systemd distinguishes between a 'running' and a 'starting' unit. A *simple* service is active as soon as the executable given by *ExecStart* is running. A *oneshot* service will be in state activating as long the executable given by *ExecStart* is running. In both cases the state will be *inactive* after the executable terminates with a return value of 0. Other return values will result in the state *failed*.

The ansible systemd module uses `systemctl show` and uses the output as return value (as dictionary). If you run ansible in verbose mode it will print the return values. For a simple service which immediately fails, chances are that the output will contain `"ActiveState": "failed"`. Therefore detecting early failing services (i.e. something went completely wrong) should be feasible.

The canonical way to determine, if a service is running or not, is by `systemctl is-active`. As a workaround for this issue you can use something like:

```yaml
- systemd:
    name: fake
    daemon_reload: yes
    state: started

- command: systemctl is-active fake
```

**Comment by samdoran** [comment]
We have improved service status checking in recent versions (for example, #72337). If this is still an issue with recent versions of Ansible, please open a new issue.
