### ISSUE TITLE
Force_handlers with_items does not execute handlers

### ISSUE THREAD

**Issue by mvitekql** [ansible/ansible#24460]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Force handlers with_items

##### ANSIBLE VERSION
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = configured module search path = Default w/o overrides
  python version = 2.7.10 (default, May  1 2017, 19:24:18) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]

##### SUMMARY
We expect handlers to run when at least one item is changed when using with_items and force_handlers.

##### STEPS TO REPRODUCE
```
---
- hosts: localhost
  gather_facts: no
  force_handlers: True
  handlers:
    - name: hello_world
      debug:
  vars:
    commands:
      - ls
      - pwd
      - asdf
  tasks:
    - shell: "{{ item }}"
      with_items: "{{ commands }}"
      notify: hello_world
```

##### EXPECTED RESULTS
PLAY [localhost] **************************************************************************************************************************************************************************************************************************************************************

TASK [command] ****************************************************************************************************************************************************************************************************************************************************************
changed: [localhost] => (item=ls)
changed: [localhost] => (item=pwd)
failed: [localhost] (item=asdf) => {"changed": true, "cmd": "asdf", "delta": "0:00:00.001902", "end": "2017-05-10 13:59:28.650743", "failed": true, "item": "asdf", "rc": 127, "start": "2017-05-10 13:59:28.648841", "stderr": "/bin/sh: asdf: command not found", "stderr_lines": ["/bin/sh: asdf: command not found"], "stdout": "", "stdout_lines": []}

RUNNING HANDLER [hello_world] *************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "Hello world!"
}

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=1

##### ACTUAL RESULTS
PLAY [localhost] **************************************************************************************************************************************************************************************************************************************************************

TASK [command] ****************************************************************************************************************************************************************************************************************************************************************
changed: [localhost] => (item=ls)
changed: [localhost] => (item=pwd)
failed: [localhost] (item=asdf) => {"changed": true, "cmd": "asdf", "delta": "0:00:00.001916", "end": "2017-05-10 14:00:00.284031", "failed": true, "item": "asdf", "rc": 127, "start": "2017-05-10 14:00:00.282115", "stderr": "/bin/sh: asdf: command not found", "stderr_lines": ["/bin/sh: asdf: command not found"], "stdout": "", "stdout_lines": []}

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

**Comment by nitzmahone** [comment]
Seems like a hole in the force_handler logic to me...

**Comment by bcoca** [comment]
handlers get notified if the TASK changes, not an item in the task, since one item failed, the TASK is flagged as failed.

**Comment by nitzmahone** [comment]
Ah yeah, this is "as designed'. I spaced that `force_handlers` is only about forcing handlers to run if *some other task* fails. If the task that notifies fails, it would still never notify. If you really need this behavior, you'll need to register the output and use `failed_when` to take control over the failure conditions for an individual item if you want the handlers to be notified, since as-is, this is considered a failing task and will never notify.

**Comment by mvitekql** [comment]
I want the playbook to fail if one of the tasks fails, but I still want some cleanup tasks to run.
My workaround is 3 tasks, and it would help a lot to have a parameter to check changed from inside the original task.

- run task with_items
- check statuses and notify the handler if one changed
- check statuses and fail the play if one failed

**Comment by bcoca** [comment]
or a block with 'notifier' in always section
