### ISSUE TITLE
ansible_user in inventory file being overridden by duplicate host in different section

### ISSUE THREAD

**Issue by mihugo** [ansible/ansible#24465]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible core (ssh login)

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = ... /ansible/etc/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.6.6 (r266:84292, Aug 18 2016, 08:36:59) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### CONFIGURATION

new install from tar ball

##### SUMMARY
When a host file contains the same host under multiple groupings the final ansible_user setting overrides and the  ansible_user=xxx is ignored from the actual host entry being used. 

##### STEPS TO REPRODUCE
Create an inventory file

```
[bobs-machines]
machineA  ansible_user=bob
machineB  ansible_user=bob

[sallys-machines]
machineA ansible_user=sally
machineC ansible_user=sally

```
validate the user that ansible is using

ansible -vvv **bob**s-machine -m ping

##### EXPECTED RESULTS
I would expect that both machineA and machineB are used with ssh user bob.

##### ACTUAL RESULTS
```
ESTABLISH SSH CONNECTION FOR USER: sally
ESTABLISH SSH CONNECTION FOR USER: bob
SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=sally -o ConnectTimeout=10 ...
SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=bob -o ConnectTimeout=10 ...
```

`
If the command was run with ALL to run against all hosts, I'm not sure what I would expect the correct bahavior to be.  There are two possbility of either running against each host once using one or the other ansible_user settings or treating differnt users as different hosts and running against each of them.  The current behavior is to run against each host exaclty 1 time regardelss of ansbile_user settings and use the last ansbile_user specificed.

In this example since the example command above is not running agianst Sally's host, the values for Sally's host should have no impact to Bob's hosts.

**Comment by sivel** [comment]
The "hostname" in your inventory is a unique key.

You have duplicated an individual host, causing the 2nd instance to overwrite the first.

Specifying to only target a single group does not change this behavior, as the inventory has already been parsed before any limiting is done.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
