### ISSUE TITLE
Module for "managed_policy" in Ansible

### ISSUE THREAD

**Issue by PrasadDuvvi** [ansible/ansible#24469]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

- managed_policy in while creating IAM role in AWS

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/pduvvi/Documents/Deloitte/Ansible/my_modules/ansible-modules-extras']
```

##### SUMMARY
 
````
I'm very new to Ansible.
I've just used **iam: ** module to create an IAM role and attached a trust_policy: (something like ec2.amazonaws.com)
How can I add a managed_policy: to my role something like below:
managed_policy:
arn:aws:iam::aws:policy/PowerUserAccess
Is this currently supported by Ansible.. I've tried with module iam_role: but I got an error message as "ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path."
Is managed_policy currently being supported by Ansible ? I can do this with CFN without any issues. 
````

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

````
Managed policies should be attached to the IAM role as soon as it is created
````
##### ACTUAL RESULTS

```

```

**Comment by nitzmahone** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
