### ISSUE TITLE
Raw module with passworded sudo (-K) outputs \r\n before output

### ISSUE THREAD

**Issue by xenithorb** [ansible/ansible#24464]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

raw

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/xenith/test_ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```
(also tested with 2.2.0 from pip) 

##### CONFIGURATION

```
[defaults]
nocows = 1
roles_path = roles
inventory = inventory
retry_files_enabled = 0
```
##### OS / ENVIRONMENT

Control machine: Fedora 25
Managed nodes: Mix of CentOS 7 and Fedora 25

##### SUMMARY

When using passworded sudo (`become: yes` with -K) an additional `\r\n` is added to the beginning of the raw output - which offsets stdout_lines output.

If running against an inconsistent environment, where this user sometimes has or doesn't already have password**less** sudo - inconsistent output is produced because of the additional carriage return and newline. Meaning, the hosts where the user already has passwordless sudo do not output the extra `\r\n`, but the ones where the user does NOT have passwordless so, it does.

I suspect that this is due to the entry of the sudo password (and or sudo asking for the password) - and perhaps the module can filter out the first `\r\n` if and only if a password was _actually_ used. (I say actually because -K doesn't matter if sudo is already passwordless it takes that first) 

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - raw: echo
```

Be sure to run against systems where the user has NOPASSWD and ones without at the same time, and also use `-vv` 

##### EXPECTED RESULTS

```
changed: [host1] => {"changed": true, "rc": 0, "stderr": "Shared connection to 192.168.1.2 closed.\r\n", "stdout": "\r\n", "stdout_lines": [""]}
changed: [host2] => {"changed": true, "rc": 0, "stderr": "Shared connection to 192.168.1.3 closed.\r\n", "stdout": "\r\n", "stdout_lines": [""]}
changed: [host3] => {"changed": true, "rc": 0, "stderr": "Shared connection to 192.168.1.4 closed.\r\n", "stdout": "\r\n", "stdout_lines": [""]}
changed: [host4] => {"changed": true, "rc": 0, "stderr": "Shared connection to 192.168.1.5 closed.\r\n", "stdout": "\r\n", "stdout_lines": [""]}
```
Note: Scroll all the way to the right and compare expected and actual.

##### ACTUAL RESULTS

```
changed: [host1] => {"changed": true, "rc": 0, "stderr": "Shared connection to 192.168.1.2 closed.\r\n", "stdout": "\r\n\r\n", "stdout_lines": ["",""]}
changed: [host2] => {"changed": true, "rc": 0, "stderr": "Shared connection to 192.168.1.3 closed.\r\n", "stdout": "\r\n", "stdout_lines": [""]}
changed: [host3] => {"changed": true, "rc": 0, "stderr": "Shared connection to 192.168.1.4 closed.\r\n", "stdout": "\r\n\r\n", "stdout_lines": ["",""]}
changed: [host4] => {"changed": true, "rc": 0, "stderr": "Shared connection to 192.168.1.5 closed.\r\n", "stdout": "\r\n", "stdout_lines": [""]}
```
Note: Where `host3` and `host1` did not yet have passwordless sudo.

**Comment by abcfy2** [comment]
Same issue here. Please fix this issue.

**Comment by xenithorb** [comment]
Hi, reporting back that this problem is still present in 2.4.0 - no one from @ansibe has commented on this, yet, unfortunately.

@bcoca can you triage this a little better, and possibly update the bug affects?

**Comment by sivel** [comment]
This no longer appears to be an issue.  When using your task, I get `"stdout": "\r\n",`.  I tested this in various scenarios using `echo`, `echo -n`, `echo foo`, and `echo -n foo`.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
