### ISSUE TITLE
include_vars does not expose variables when play is run for host != localhost

### ISSUE THREAD

**Issue by igozali** [ansible/ansible#24478]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

module: `include_vars`

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### OS / ENVIRONMENT

Issue not OS-specific, but running Ansible from macOS 10.12.4.

##### SUMMARY

When using the `include_vars` module with `delegate_to: localhost` to load variables, I expect the variables to be loaded globally such that I can use them when provisioning any other host. However, I see the following strange behavior.

*   If I use include_vars in a play for a host other than localhost, then the variable will not be exposed.
*   If I use include_vars in a play for localhost, then the variable will be exposed.

Just a note, this bug is not seen in ansible 2.1.2.0. In ansible 2.1.2.0, the variable will be exposed regardless of which host the play is being run for.
##### STEPS TO REPRODUCE

```
# Ensure ansible, git, and ansible-playbook command exists
$ git clone https://github.com/igozali/ansible_examples.git
$ cd ansible_examples/include_var_bug
$ ansible-playbook -i ./hosts site.yml
```

##### EXPECTED RESULTS

```
PLAY [the test_host play] ***************************************************************

TASK [example : include vars] ***********************************************************
ok: [test_host -> localhost]

TASK [example : print include_vars_result] **********************************************
ok: [test_host -> localhost] => {
    "changed": false,
    "include_vars_result": {
        "ansible_facts": {
            "some_var": "aaaa"
        },
        "changed": false
    }
}

TASK [example : print some_var] *********************************************************
ok: [test_host -> localhost] => {
    "changed": false,
    "some_var": "aaaa"
}

PLAY [the localhost play] ***************************************************************

TASK [example : include vars] ***********************************************************
ok: [localhost -> localhost]

TASK [example : print include_vars_result] **********************************************
ok: [localhost -> localhost] => {
    "changed": false,
    "include_vars_result": {
        "ansible_facts": {
            "some_var": "aaaa"
        },
        "changed": false
    }
}

TASK [example : print some_var] *********************************************************
ok: [localhost -> localhost] => {
    "changed": false,
    "some_var": "aaaa"
}

PLAY RECAP ******************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
test_host                  : ok=3    changed=0    unreachable=0    failed=0
```
##### ACTUAL RESULTS

```
PLAY [the test_host play] ***************************************************************

TASK [example : include vars] ***********************************************************
ok: [test_host -> localhost]

TASK [example : print include_vars_result] **********************************************
ok: [test_host -> localhost] => {
    "changed": false,
    "include_vars_result": {
        "ansible_facts": {
            "some_var": "aaaa"
        },
        "changed": false
    }
}

TASK [example : print some_var] *********************************************************
ok: [test_host -> localhost] => {
    "changed": false,
    "some_var": "VARIABLE IS NOT DEFINED!"
}

PLAY [the localhost play] ***************************************************************

TASK [example : include vars] ***********************************************************
ok: [localhost -> localhost]

TASK [example : print include_vars_result] **********************************************
ok: [localhost -> localhost] => {
    "changed": false,
    "include_vars_result": {
        "ansible_facts": {
            "some_var": "aaaa"
        },
        "changed": false
    }
}

TASK [example : print some_var] *********************************************************
ok: [localhost -> localhost] => {
    "changed": false,
    "some_var": "aaaa"
}

PLAY RECAP ******************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
test_host                  : ok=3    changed=0    unreachable=0    failed=0
```

**Comment by igozali** [comment]
I think this is related to #24172?

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

`include_vars` has never been 'global' it always adds the variables to the 'current host' (inventory_hostname), the ticket you reference has to do with `delegate_to` behaviour which we fixed to follow `delegate_facts` to assign to delegated machine vs the inventory_hostname.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by igozali** [comment]
Thanks for your answer. Regarding the change in behavior from ansible 2.1.2.0 to ansible 2.3.0.0, do you have any explanation for this? Is the behavior in ansible 2.3.0.0 to be taken as correct behavior?

**Comment by bcoca** [comment]
The behaviour in the fixed PR is the correct behaviour, `include_vars` will add the vars to inventory_hostname except when both  `delegate_to` is set and `delegate_facts` is true, then the vars will go to the delegated host.

**Comment by igozali** [comment]
Thanks for your clarification and for maintaining this fantastic project @bcoca

**Comment by bcoca** [comment]
No problem, sorry for the confusion, this was 'undefined' until the issue that I fixed in the PR above made us make a decision and document and codify the behaviour.
