### ISSUE TITLE
Feature Idea: Integrate/introduce group_vars concept into roles

### ISSUE THREAD

**Issue by jamesongithub** [ansible/ansible#24473]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

Variable scope

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /Users/james/vcs/infrastructure/ansible/ansible.cfg
  configured module search path = [u'modules']
  python version = 2.7.13 (default, Apr 13 2017, 16:18:01) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### SUMMARY

Wanted to propose the concept of `group_vars` in roles. Basically this expands how variables are added into the play in a role. The idea is to be able to add variables at the `group_var` precedence depending if the hosts in execution are in a certain group. One way to do this would be to read files in the `vars/` directory and automatically load those variables which matched the groups of the current hosts. Currently the only file loaded by roles is the `vars/main.yml`. It seems heavyweight to use a entire directory just for 1 file. (Might as well move `defaults/main.yml` to `vars/defaults.yml` while we're at it. After all `defaults` is essentially the same as `var` directory minus the precedence.)

directory structure would be something like
```
vars/
  - defaults.yml
  - main.yml
  - group_1.yml
  - group_2.yml
  - group_3.yml
```

A "global" group_var would then take precedence over a "role" `group_var` since roles are more specific. 

This feature idea spawned mainly from difficulties over overriding conditional variables in roles. What I've seen in a lot of roles and in some of ours are something like

```
- include: some_variables.yml
  when: some condition is true
```

Clients of role are then unable to override variables in `some_variables.yml` while using the role,  since variable that are included are so high in precedence. Extra vars would be the only way and nobody wants to set everything in extra vars.

These "role" group_vars would come in handy when one want to load variable related to the role depending on different conditions (environment/customer/whatever) and doesn't want to pollute the "global" group_vars namespace.

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by trsreagan3** [comment]
This feature would be very useful!

**Comment by edulop91** [comment]
nice

**Comment by jmnavarrol** [comment]
If I understood properly, I don't like this idea.  Roles should be inventory agnostic.  If you want to play with groups to set variables, do it at the playbook level.

For "private" role variables, use the vars/ files; for defaults, use the defaults/ dir.

I would like a more detailed use case to better understand what you try to accomplish.

**Comment by goneri** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.  Our reasons for this are:

   * a role should indeed be inventory agnostic
   * there is already several ways that allows you to achieve what you want

Thank you once again for this and your interest in Ansible!
