### ISSUE TITLE
Variables in host_vars not loading when using inventory directory

### ISSUE THREAD

**Issue by dgarros** [ansible/ansible#24483]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Default Variable management

##### ANSIBLE VERSION
```
ansible 2.4.0 (fix-aos-login-port 395d4d4c5b) last updated 2017/05/09 08:59:20 (GMT -700)
  config file = /Users/damien/projects/cloudlabs-topologies/two-tier-arista-l3/ansible.cfg
  configured module search path = [u'/Users/damien/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/damien/projects/ansible/lib/ansible
  executable location = /Users/damien/projects/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  6 2017, 23:53:20) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION
```

```

##### OS / ENVIRONMENT
Mac OS 10.12.4

##### SUMMARY
When using multiple inventory files, saved in the directory `inventory/`, variables stored in `host_vars/<inventory_hostname>/xxx.yaml` are not loaded. 

Assuming we have 4 devices, defined in 2 inventories files:
```
project/
   inventory/
       inv1 
          host_ccc id=11
          host_ddd id=12
       inv2
          host_aaa id=1
          host_bbb id=2
   host_vars/
       host_aaa/
           fqdn.yaml  `myvar: this is my var` 
       host_bbb.yaml  `myvar: this is my var` 
```

When I'm running a playbook just on 1 device `host_ccc` (using limit)  the variable from `host_aaa` > hostvars['host_aaa'].myvar` is undefined
 
if I merge my inventories files (inv1 and inv2) into a single file, the same variable  `hostvars['host_aaa'].myvar` exist for host_ccc

I clearly have a different behavior with 1 or 2 inventory files

##### STEPS TO REPRODUCE
 - Create a `host_vars` directory and create some variable file for 3 hosts
 - Create a inventory directory and create 2 inventories files, with 2 hosts each
 - Create another inventory with the same content as both previous inventory files combined
 - Create a playbook to show variables defined inside host_vars for each host

```
├── host_vars
│   ├── host_aaa
│   │   └── var.yaml
│   ├── host_bbb.yaml
│   └── host_ccc.yaml
├── inventory
│   ├── inv1
│   └── inv2
├── inventory.ini
└── pb.show_var.yaml
```

```yaml
# pb.show_var.yaml
- name: Print Variables
  hosts: all
  gather_facts: no
  connection: local
  tasks:
    - name: Variables for dev_aaa
      debug: var=hostvars['host_aaa'].myvar

    - name: Variables for dev_bbb
      debug: var=hostvars['host_bbb'].myvar

    - name: Variables for dev_ccc (self)
      debug: var=myvar
```

```ini
# Inventory
host_aaa id=1
host_bbb id=2
host_ccc id=11
host_ddd id=12
```

##### EXPECTED RESULTS
Variables from `host_aaa` and `host_bbb` should be defined `host_ccc` when using multiple inventory files 

##### ACTUAL RESULTS
```
(ansible-dev) ➜  ansible-bug-inventory-01 git:(master) ansible-playbook -i inventory pb.show_var.yaml --limit=host_ccc

PLAY [Print Variables] **********************************************************************************************

TASK [Variables for dev_aaa] **********************************************************************************************
ok: [host_ccc] => {
    "hostvars['host_aaa'].myvar": "VARIABLE IS NOT DEFINED!" <<<<<
}

TASK [Variables for dev_bbb] **********************************************************************************************
ok: [host_ccc] => {
    "hostvars['host_bbb'].myvar": "VARIABLE IS NOT DEFINED!" <<<<<<
}

TASK [Variables for dev_ccc (self)] **********************************************************************************************
ok: [host_ccc] => {
    "myvar": "this is my var"
}

PLAY RECAP **********************************************************************************************
host_ccc                   : ok=3    changed=0    unreachable=0    failed=0

(ansible-dev) ➜  ansible-bug-inventory-01 ansible-playbook -i inventory.ini pb.show_var.yaml --limit=host_ccc

PLAY [Print Variables] *********************************************************************************************

TASK [Variables for dev_aaa] **********************************************************************************************
ok: [host_ccc] => {
    "hostvars['host_aaa'].myvar": "this is my var"
}

TASK [Variables for dev_bbb] **********************************************************************************************
ok: [host_ccc] => {
    "hostvars['host_bbb'].myvar": "this is my var"
}

TASK [Variables for dev_ccc (self)] **********************************************************************************************
ok: [host_ccc] => {
    "myvar": "this is my var"
}

PLAY RECAP **********************************************************************************************
host_ccc                   : ok=3    changed=0    unreachable=0    failed=0
```

**Comment by sivel** [comment]
host_vars and group_vars must live beside the inventory *file*.

when using an inventory directory, you will have to move host_vars and group_vars inside of that directory as well.

This is documented at http://docs.ansible.com/ansible/intro_inventory.html#splitting-out-host-and-group-specific-data

> In Ansible 1.2 or later the group_vars/ and host_vars/ directories can exist in the playbook directory OR the inventory directory

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by dgarros** [comment]
@sivel thanks for looking into it

I was not aware of that but still I'm seeing inconsistent behavior

When using the inventory directory, without `--limit` my host `host_ccc` is seeing the variable from `host_aaa`

if I run the same playbook with limit, the variable is undefined. Is it expected as well ?

```
(ansible-dev) ➜  ansible-bug-inventory-01 ansible-playbook -i inventory pb.show_var.yaml

PLAY [Print Variables] *******************************************************************************************

TASK [Variables for dev_aaa] *******************************************************************************************
ok: [host_ccc] => {
    "hostvars['host_aaa'].myvar": "this is my var"
}
ok: [host_ddd] => {
    "hostvars['host_aaa'].myvar": "this is my var"<<<<<<<<<<<
}
ok: [host_aaa] => {
    "hostvars['host_aaa'].myvar": "this is my var" <<<<<<<<<<<
}
ok: [host_bbb] => {
    "hostvars['host_aaa'].myvar": "this is my var"<<<<<<<<<<<
}

TASK [Variables for dev_bbb] *******************************************************************************************
ok: [host_ccc] => {
    "hostvars['host_bbb'].myvar": "this is my var"<<<<<<<<<<<
}
ok: [host_ddd] => {
    "hostvars['host_bbb'].myvar": "this is my var"<<<<<<<<<<<
}
ok: [host_aaa] => {
    "hostvars['host_bbb'].myvar": "this is my var"<<<<<<<<<<<
}
ok: [host_bbb] => {
    "hostvars['host_bbb'].myvar": "this is my var"
}

TASK [Variables for dev_ccc (self)] *******************************************************************************************
ok: [host_ccc] => {
    "myvar": "this is my var"
}
ok: [host_ddd] => {
    "myvar": "VARIABLE IS NOT DEFINED!"
}
ok: [host_aaa] => {
    "myvar": "this is my var"
}
ok: [host_bbb] => {
    "myvar": "this is my var"
}

PLAY RECAP *******************************************************************************************
host_aaa                   : ok=3    changed=0    unreachable=0    failed=0
host_bbb                   : ok=3    changed=0    unreachable=0    failed=0
host_ccc                   : ok=3    changed=0    unreachable=0    failed=0
host_ddd                   : ok=3    changed=0    unreachable=0    failed=0
```

**Comment by sivel** [comment]
Limits have no impact on variable merging when a host is a member of multiple groups.

Inventory merging happens before any limits, so if you have a host in multiple groups, and those groups define duplicate variables, the later defined variable will overwrite earlier defined variables.

As another person referenced recently:

> Groups are 'properties' of hosts. For example I'm male and a programmer. I don't stop being one or the other just because you chose me from a pool of 'males' or 'programmers'.

**Comment by dgarros** [comment]
> Limits have no impact on variable merging when a host is a member of multiple groups.

That is my understanding as well, and that's why I'm surprised to see a different behavior with and without `--limit` in this case.
It really looks like the variables are loaded differently with `--limit`

**Comment by ghost** [comment]
This is basically the reason why it is not possible to use hostvars when vagrant is use. The hostvars for other hosts are not loaded because vagrant uses --limit and specifies --inventory-file= (directory). Only the variables of the current host are loaded.

Is there a reasonable way to work around this problem with vagrant (without forcing limit=all).?
