### ISSUE TITLE
Documentation: Links in notes are not easily identifiable

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#24492]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

docs / website

##### ANSIBLE VERSION

v2.4

##### SUMMARY

Links inside a module's `notes` section are not easily identified as a link.

E.g. the "template" module is linked from these notes:
http://docs.ansible.com/ansible/win_template_module.html#notes

**Comment by nitzmahone** [comment]
cc @dharmabumstead - looks like a CSS issue in notes

**Comment by dagwieers** [comment]
This seems to be fixed now in v2.5 docs. Still an issue in v2.4 docs.

**Comment by dagwieers** [comment]
I am going to close this as v2.4 is becoming irrelevant now :)
