### ISSUE TITLE
Curl -F option and ansible URI module

### ISSUE THREAD

**Issue by DeanKamali** [ansible/ansible#24524]
I'm trying to use ansible's uri module to mimic curl command, I need to pass options when uploading an XML file.

My curl command has number of options passed via` -F, --form <name=content>` I haven't been able to find an equivalent option on Ansible's uri docs

##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME
uri_module

##### ANSIBLE VERSION
ansible 2.3.0.0

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
