### ISSUE TITLE
junos_facts (and junos_*) provider timeout not used by ansible-connection

### ISSUE THREAD

**Issue by tjuberg** [ansible/ansible#24520]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible-connection /  junos_facts

##### ANSIBLE VERSION

```
ansible 2.3.1.0 (stable-2.3 5f0be9dcd0) last updated 2017/05/11 18:08:41 (GMT +000)
  config file = /root/bachelor/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
hostfile = hosts
log_path = ~/bachelor/ansible.log
host_key_checking = False
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Having modified junos_facts to pull route information from some of busier routers I ran into an issue where the persistent connection would close prior to the play finishing due to the connection being idle while the facts module parses the rather large routing table. This causes the module to fail when trying to issue the next EXEC call via netconf as the connection is now closed and the socket no longer exists.

This behaviour was verified via Wireshark and show that after 10 seconds of the connection becoming idle the connection is dropped.

The problem is that the provider set timeout is never used by ansible-connection despite this value being set high enough to allow for the parsing to complete.

Setting timeout = value in ansible.cfg to override C.DEFAULT_TIMEOUT, and I assume using the environment variable as well from looking at the code, will allow the module time enough to work trough the parsing and successfully make the next EXEC call after finishing.

This issue is possibly related to #24480
##### STEPS TO REPRODUCE

Set timeout = 360 in the provider used for junos_facts.

Reproducing this issue as I encountered it depends entirely on the large amount of data returned (almost 600k lines of xml in my case) which takes a substantial time for python to parse.

However modifying any subset in junos_facts to include something that forces the code to spend more than C.DEFAULT_TIMEOUT before it allows execution of the next command should give the same behaviour.

Watch as ansible-connect disconnects after C.DEFAULT_TIMEOUT has passed, ignoring the timeout value of 360 or higher.

```yaml
- name: Get JunOS facts
  hosts: test
  gather_facts: no
  connection: local
  tasks:

    - name: Gather Junos facts
      junos_facts:
        provider: "{{ ansible_provider }}"
      register: junos

```

##### EXPECTED RESULTS

I expected timeout = 360 to be respected allowing the code to finish parsing the output from the router, allowing for a successful next EXEC call.

##### ACTUAL RESULTS

```
017-05-11 18:45:20,494 p=1627 u=root |  socket operation is EXEC 
2017-05-11 18:45:20,494 ncclient.operations.rpc Requesting 'ExecuteRpc' 
2017-05-11 18:45:38,791 p=1627 u=root |  socket operation completed with rc 0 
2017-05-11 18:45:38,943 p=1627 u=root |  shutting down control socket, connection was active for 0:00:26.770045 secs 
2017-05-11 18:45:38,943 ncclient.operations.rpc Requesting 'CloseSession' 
2017-05-11 18:45:47,301 p=1532 u=root |  fatal: [trd-gw]: FAILED! => { 
    "changed": false,  
    "err": "[Errno 2] No such file or directory",  
    "failed": true,  
    "invocation": { 
        "module_args": { 
            "config_format": "text",  
            "gather_subset": [ 
                "!config" 
            ],  
            "host": null,  
            "password": null,  
            "port": null,  
            "provider": { 
                "host": "xxx.xxx.xxx.xxx",  
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",  
                "port": 22,  
                "ssh_keyfile": null,  
                "timeout": 360,  
                "transport": null,  
                "username": "test" 
            },  
            "ssh_keyfile": null,  
            "timeout": 10,  
            "transport": null,  
            "username": null 
        } 
    },  
    "msg": "unable to connect to socket" 
} 

```

**Comment by ganeshrn** [comment]
The provider `timeout` value indicates how long the underlying `Netconf` session should remain idle in case no new request is received. 

`connect_timeout` under ` [persistent_connection]` in `ansible.cfg` file indicates how long the persisent connection should remian idle before destroying incase no new request is received.

So for long running `rpc's` both provider `timeout` and persistent connection `connect_timeout`
value needs to be increased.

**Comment by tjuberg** [comment]
@ganeshrn Please note, the issue is that the provider ```timeout``` is not used by ```ansible-connection``` which is the core issue I have.

I have to set the global ```timeout``` in ```ansible.cfg``` to affect the value used by ```ansible-connection``` which is not desireable as the majority of plays do not require such high values.

**Comment by ganeshrn** [comment]
@TJuberg 
Did you try increasing the persistent connection timeout `connect_timeout` and provider `timeout` value?
 Keep global `timeout` to its default value.

**Comment by tjuberg** [comment]
@ganeshrn I have tested altering all 3 values. Provider `timeout` is ignored by `ansible-connection` and global `timeout` has to be altered to prevent idle disconnection.

I currently have provider `timeout` set to `360`, however both oberved behaviour as well as added debug statements in `ansible-connection` confirms that the global value of `10` is still being used.

**Comment by ganeshrn** [comment]
@TJuberg Can you please retest after applying PR https://github.com/ansible/ansible/pull/24556
Also please set persistent connection timeout value `connect_timeout` greater than provider timeout.

**Comment by tjuberg** [comment]
@ganeshrn I can confirm that PR #24556 fixes the issue and sets the correct `timeout` value.

With `timeout = 30` set in `ansible.cfg` and `timeout = 360` set in `provider`, `360` is now used in `ansible-connection`

Thank you :+1:

**Comment by ganeshrn** [comment]
@TJuberg Thank you for testing.
