### ISSUE TITLE
Network credentials deprecation notice triggered by Tower (env variables)

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#24537]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
networking

##### ANSIBLE VERSION
```
2.3.0
```

##### SUMMARY
Ansible Tower passes credentials to the tower modules using environment variables, this triggers the deprecation warnings.

It does this by setting `ANSIBLE_NET_USERNAME` and `ANSIBLE_NET_PASSWORD`, and possibly other options.

See the following where we do `env_fallback` and set this on the top-level arguments
https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/eos.py

##### ACTUAL RESULTS
```

```

**Comment by trishnaguha** [comment]
Related issue https://github.com/ansible/ansible/issues/25663
