### ISSUE TITLE
Feature Req: Display date/time stamp during playbooks run using verbose?

### ISSUE THREAD

**Issue by dbrossard** [ansible/ansible#2454]
I think a useful feature, especially when running longer playbooks, would be to show the time stamp at the beginning of each new task, possibly only when running in verbose mode. 
IE:

<pre>
013-03-19 09:29:29 PLAY [Temp] ********************* 

2013-03-19 09:29:30 GATHERING FACTS ********************* 
ok: [10.51.10.76]

2013-03-19 09:29:33 TASK: [install all needed packages] ********************* 
ok: [10.51.10.76] => {"changed": false}

2013-03-19 09:29:52 TASK: [Stop Apache] ********************* 
changed: [10.51.10.76] => {"changed": true, "name": "apache2", "state": "stopped"}
</pre>

or something similar. Maybe only use if running in verbose AND a flag is called similar to --timed. This would help determine if something has hung on the remote side.
Thoughts?

**Comment by mpdehaan** [comment]
ansible commander is going to have date time information of launch events in the database so I think that would be sufficient.  

you could also extend this with a callback plugin to print the dates after every play starts (or task)

**Comment by mahemoff** [comment]
Is Ansible commander still happening? (No commits for a year if it's this https://github.com/mavimo/ansible-commander)

An option for timestamped logs would certainly be useful, as would a summary with total duration.

**Comment by verveguy** [comment]
The lack of timestamps on log output is almost criminally negligent. :-)

**Comment by aconrad** [comment]
+1

**Comment by StigLau** [comment]
+1 Playbooks are often started and left running because of duration time. Having a relation to when old scripts have been run and how much time has been used makes a large difference.

**Comment by fingul** [comment]
+1

**Comment by varas** [comment]
+1

**Comment by miketwo** [comment]
+1

**Comment by MichaelBaydoun** [comment]
+1

**Comment by nocive** [comment]
+1

**Comment by gavD** [comment]
+1

**Comment by moorooboorai-jeroen** [comment]
+1

**Comment by ibratoev** [comment]
+1

**Comment by akatch** [comment]
+1

**Comment by jamesdmorgan** [comment]
+1

**Comment by Govinda-Fichtner** [comment]
+1

**Comment by srgvg** [comment]
https://github.com/ginsys/ansible-plugins/blob/devel/callback_plugins/timestamp.py

**Comment by nocive** [comment]
@sergevanginderachter it doesn't work as expected for me, it doesn't output the time a task takes.
It seems to output the time the ansible ssh command takes to start execution on the remote end, but not the total time the task takes to finish.
Good effort though, thanks.

**Comment by srgvg** [comment]
@nocive it outputs a  `time_elapsed` and a `time_total_elapsed`, the former - noted between ()brackets being per (previous) task

**Comment by nocive** [comment]
@sergevanginderachter duh, stupid me :)
Thanks!

**Comment by kanuku** [comment]
+1

**Comment by yvbeek** [comment]
+1

**Comment by justinko** [comment]
+1

**Comment by codyro** [comment]
+1

**Comment by sankalp-khare** [comment]
+1
