### ISSUE TITLE
[WIP] Make network plugins PY3 complaint

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible#24557]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

asa
dellos6
dellos9
dellos10
eos
ios
iosxr
junos
nxos
sros
vyos

##### ANSIBLE VERSION

```
2.4
```

##### SUMMARY

Issue to track py3 compliance for network modules
##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by Akasurde** [comment]
@ganeshrn Let me know if you need any help in this ? I would like to help here.

**Comment by ganeshrn** [comment]
https://github.com/ansible/ansible/pull/24570
