### ISSUE TITLE
win_ping ERROR

### ISSUE THREAD

**Issue by woshihaoren** [ansible/ansible#24656]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
/usr/local/lib/python3.5/site-packages/ansible/executor/module_common.py

##### ANSIBLE VERSION

```
2.3.0
```

##### STEPS TO REPRODUCE

```yaml
-bash-4.1# cat /etc/ansible/hosts 
[wi]
10.255.33.27  ansible_connection=winrm  ansible_ssh_port=5985 ansible_ssh_user=administrator ansible_ssh_pass=123456789
-bash-4.1# ansible 10.255.33.27 -m win_ping -vvv
No config file found; using defaults
META: ran handlers
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/usr/local/lib/python3.5/site-packages/ansible/executor/task_executor.py", line 521, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python3.5/site-packages/ansible/plugins/action/normal.py", line 45, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/local/lib/python3.5/site-packages/ansible/plugins/action/__init__.py", line 635, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/usr/local/lib/python3.5/site-packages/ansible/plugins/action/__init__.py", line 170, in _configure_module
    play_context=self._play_context, environment=final_environment)
  File "/usr/local/lib/python3.5/site-packages/ansible/executor/module_common.py", line 868, in build_windows_module_payload
    exec_manifest["powershell_modules"][m] = base64.b64encode(to_bytes(_slurp(os.path.join(_MODULE_UTILS_PATH, m + ".ps1"))))
TypeError: can't concat bytes to str

10.255.33.27 | FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

##### ACTUAL RESULTS

```

```

**Comment by jhawkesworth** [comment]
Python 3.x support is still being developed.  Try running using a python 2.6 or later 2.x revision.

**Comment by jhawkesworth** [comment]
Now that https://github.com/ansible/ansible/pull/24744 has been merged into latest devel, please can you try again using latest development version of ansible. 

There are instructions here: http://docs.ansible.com/ansible/intro_installation.html#running-from-source if you are unfamiliar with running ansible from source.

needs_info

**Comment by nitzmahone** [comment]
#24744 fixes basic Windows smoke tests on Python 3.5.3 for me (though I'm getting a lot of finalizer noise, unrelated- seems to be [this](https://bugs.python.org/issue29519)). I'm going to run the full integration suite against py3, and if there are no other issues, I'll probably also backport for Ansible 2.3.1.

**Comment by sivel** [comment]
It looks like as of https://github.com/ansible/ansible/pull/24762 we are now running the full integration suite for windows against py3.

**Comment by nitzmahone** [comment]
Not the full suite, but a set of platform smoke tests that we'll be adding to (as we get things fixed). There are several things still broken for Windows (raw and async immediately come to mind, and I suspect become may have issues as well). Right now, it's just doing win_ping under py3, but that will get added to a bit soon.
