### ISSUE TITLE
create a warning system for un-interpolated variables

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#2465]
It would be nice if there was a warning when things like ${ were left in some template evaluations, but we'll have to be careful about how we do that to not flag $HOME as an error, or other environment variables, etc.  (Maybe the shell command would have less checking).   It should also check templates.

It probably also needs  a way to turn that off too.

**Comment by crucialfelix** [comment]
thanks for filing this issue.

template and .yml files.  ideally all the commands could have their variables converted before even starting the playbook and optionally throw an error ( --break-on-missing-variables or something ).  for instance today I ran a long job and after 25 minutes something failed $because $variable.  not easy to resume and the handlers don't get handled.

**Comment by mpdehaan** [comment]
Somewhat related to this, we should add this to the docs as well:

```
- name: open psql ports to trusted servers
  with_items: ${groups.dbclients}
  action: command ufw allow from ${hostvars.${item}.sip} to any port $psql_port
```

This can be covered in the magic variables section when discussing hostvars in templates.

**Comment by crucialfelix** [comment]
Thanks.  Here's some suggested text for that section after the ${hostvars.{test.example.com}.ansible_distribution} example.

If you have the name of the host in a variable and wish to lookup that host's facts or variables using the hostname (eg. here in variable $hostname):

```
# fact
${hostvars.${hostname}.ansible_eth0.ipv4.address}

# an inventory variable named 'weight'
${hostvars.${hostname}.weight}

# iterating over a group's members
- name: open psql ports to trusted servers
  with_items: ${groups.dbclients}
  action: command ufw allow from ${hostvars.${item}.ansible_ssh_host} to any port $psql_port
```

also the new nested iterator should be able to iterate over all hosts in a group of groups. so an example of that would be great to put in there.

and I would clarify here http://ansible.cc/docs/playbooks2.html#turning-off-facts that gather_facts:no means that variables are not accessible either.  coming from things like facter I assumed that turning off facts just meant skipping a lengthy server side introspection.  didn't occur to me that the hostvars wouldn't be parsed.

thanks Michael !   once I get solid here I'll check out development branch and contribute if I can.

**Comment by mpdehaan** [comment]
Yeah our server side operations are pretty fast, it means don't run
remotely to gather them.

Thanks for suggestions, will get this added soon.

**Comment by mpdehaan** [comment]
This is actually a little tricky, because you have to know what call of the template system is the last in the chain.  What this probably means is the runner loop may print a warning in the new "{{" system, if "{{" is found in the input to a module.

And that would need to be something you could switch off, while "{{" in a template is still an error.

We would need the new Jinja2 templates (which are replacing $foo BTW, but still supporting for backwards compatibility) to not error out of course if not evaluatable at a certain step.

**Comment by mpdehaan** [comment]
doing this as part of #2556
