### ISSUE TITLE
interfaces_file module missing

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#24660]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

interfaces_file

There's a [PR](/ansible/ansible-modules-extras/pull/2027) that was marked as `shipit`` but was never merged, can we get it available?
CC @bcoca

**Comment by gundalow** [comment]
Hi,
If you follow the link on the original PR you can create a new PR and we can review this.
