### ISSUE TITLE
Pull down menus for HTML documentation do not work on iPad or other touch screens

### ISSUE THREAD

**Issue by nigelm** [ansible/ansible#2467]
It looks like this is a bootstrap bug fixed in later versions.

Currently the pull downs just automatically fire the first item on the pull down.

See http://forwebonly.com/fix-for-twitter-bootstrap-dropdown-on-ipad-and-iphone/

**Comment by mpdehaan** [comment]
Ok, so it looks like we just have to update the bootstrap.  Cool.

**Comment by bitmensch** [comment]
I just tried to reproduce this issue on iPad mini and iPhone 5, in Safari and Google Chrome for devel branch and official release (http://ansible.cc/docs/).
For me the dropdown menus are working as expected, no automatic firing of first items.

@nigelm Just to make sure we're on the same page. You are referring to the dropdown menu "Chapter" on http://ansible.cc/docs/?

**Comment by nigelm** [comment]
Having just tested I don't see this now, either.  Nor do I see a fix having gone in for it, and we aren't just pulling the latest google or other CDN bootstrap...
Either the Section or Chapter menu was showing this before.

Heisenbug?

Suggest we close.

**Comment by bitmensch** [comment]
@nigelm I was not able to identify a fix either, but hey, it works. ;)
