### ISSUE TITLE
Gem install fails on installing current version of 'pg' gem.

### ISSUE THREAD

**Issue by jnials** [ansible/ansible#2470]
It seems to be pulling the wrong requirements from the Gem.  Upon running the following playbook snippit on Ubuntu:

```
- name: Install required gems for some clients
  gem: name=$item state=latest
  with_items:
    - pg
```

The following output is generated:

```
TASK: [Install required gems for some clients] ********************* 
failed: [db-master.example.com] => (item=pg) => {"cmd": ["/usr/bin/gem", "install", "--version", "0.14.1 ruby x86-mingw32", "--include-dependencies", "--no-rdoc", "--no-ri", "pg"], "failed": true, "item": "pg", "rc": 1}
stderr: ERROR:  While executing gem ... (ArgumentError)
    Illformed requirement ["0.14.1 ruby x86-mingw32"]

msg: ERROR:  While executing gem ... (ArgumentError)
    Illformed requirement ["0.14.1 ruby x86-mingw32"]

FATAL: all hosts have already failed -- aborting
```

The gem installs fine manually, with `gem install --no-doc --no-ri`

This is on the latest head (92997ec7895b976a54368e74959f0efc95da08ab) of the code.

**Comment by mpdehaan** [comment]
Seems like this is a gem specific issue and not anything to do with ansible.

Let me know if you disagree.

**Comment by AndydeCleyre** [comment]
Hi,

I think this reflects a problem with with the way the gem module determines the "latest" version string with certain gems. It seems that some gems have multiple "latest" variations, and this throws off the gem module.

Here is a task that fails to install the gem named eventmachine:

```
- gem: name=eventmachine state=latest user_install=no
```

Ansible output reveals why the gem fails to install:

```
(item=eventmachine) => {"cmd": ["/usr/bin/gem", "install", "--version",
"1.0.3 ruby java x86-mingw32 x86-mswin32-60", "--include-dependencies",
"--no-user-install", "--no-rdoc", "--no-ri", "eventmachine"], "failed":
true, "item": "eventmachine", "rc": 1}
stderr: ERROR: While executing gem ... (ArgumentError)
Illformed requirement ["1.0.3 ruby java x86-mingw32 x86-mswin32-60"]
```

That version string is just too much. It looks like the gem module will have to recognize multiple "latest" versions, and choose the most generic one of those. Here is the rubygems page for eventmachine: https://rubygems.org/gems/eventmachine .

I disagree that this is a gem and not an ansible issue. Some gems have version variations like this, so ansible's gem module should learn not choke on them.

**Comment by mpdehaan** [comment]
Ok, is this something you might be interested in helping fix BTW?

Figured I would ask.

**Comment by AndydeCleyre** [comment]
This should fix it: https://github.com/ansible/ansible/pull/4344

**Comment by jctanner** [comment]
Thanks for the patch!
