### ISSUE TITLE
apt: wrong alias for autoremove (autoclean)

### ISSUE THREAD

**Issue by rotanid** [ansible/ansible#24718]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
apt module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /home/username/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
(irrelevant)

##### OS / ENVIRONMENT
N/A

##### SUMMARY
in 2016 the feature "autoremove" was merged into ansible modules by https://github.com/ansible/ansible-modules-core/pull/2974
but this merge also contains "autoclean" as an alias for "autoremove", which is totally wrong as was pointed out already in https://github.com/ansible/ansible-modules-core/pull/2974#issuecomment-225105654 and especially https://github.com/ansible/ansible-modules-core/issues/2340#issuecomment-274368451
as explained there, "autoclean" and even "clean" are different features and shouldn't be mixed up with "autoremove".

**Comment by resmo** [comment]
fixed by 2af5556901f0847d835af60f58769a8dd94c4415
