### ISSUE TITLE
Persistent Connection: Proxy information needs logging

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#24721]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
networking

##### ANSIBLE VERSION
```
2.3.0
```

##### SUMMARY
If a user has specified to use a proxy (like https://github.com/gundalow/ansible/blob/7876870b5a2d28d5724080d6ceb9e32593083b68/docs/docsite/rst/porting_guide_2.3.rst#delegate-to-vs-proxycommand) we don't current log that in `ANSIBLE_LOG_PATH` making it difficult to debug issues

**Comment by calfonso** [comment]
We'll not be able to fix this in 2.3 without a substantial changeset, so given the severity level we are moving it to our 2.4 milestone.
