### ISSUE TITLE
Windows via SSH

### ISSUE THREAD

**Issue by MatthewFawcett** [ansible/ansible#24726]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea?

##### COMPONENT NAME

Windows management over SSH 

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/ansible/modules']
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### CONFIGURATION

remote_tmp     = $HOME\ansible\.tmp

also changed $HOME to %HOMEPATH%, C:\temp, etc.

##### OS / ENVIRONMENT

Anisble runner: Linux version 3.10.0-514.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Nov 22 16:42:41 UTC 2016

Managing Windows Server 2016

##### SUMMARY

I'm using Anisble to manage some Linux hosts and am looking at using OpenSSH on Windows Server to manage Windows via SSH (I'm aware I can use the WinRM module but this causes overhead for environmental reasons so I'm in the process of investigating alternatives).

When I run ansible-playbook or "ansible ping" I can get the error below relating to the tmp directory.  I've tried to change this in ansible.cfg to various paths and directories but still get the same error.

For the purpose of the investigative work I've been using the local admin account on the Windows box for all Ansible operations.  I can SSH manually from my Ansible host.

Is it possible to manage Windows Server over SSH with Ansible?

##### STEPS TO REPRODUCE

```yaml
---
- name: IIS DSC Configuration
  hosts: windows-ssh
  tasks:
    - name: Test DSC Configuration
      script: /root/windowsanisble/winrm/TestConfiguration.ps1
      register: out

    - debug: var=out.stdout_lines
```
(Note: the playbook doesn't run, the problem I have is during setup)

##### EXPECTED RESULTS

The playbook runs against the Windows host

##### ACTUAL RESULTS

```
fatal: [10.240.2.139]: UNREACHABLE! => {
    "changed": false,
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo $HOME\\ansible\\.tmp/ansible-tmp-1495026954.16-102309192318079 `\" && echo ansible-tmp-1495026954.16-102309192318079=\"` echo $HOME\\ansible\\.tmp/ansible-tmp-1495026954.16-102309192318079 `\" ), exited with result 1",
    "unreachable": 
```

The part that makes me suspect this is the temp path is:  $HOME\\ansible\\.tmp/ansible-tmp-1495026954.16-102309192318079 `\ as this wouldn't be a valid path on a Windows host.

**Comment by dagwieers** [comment]
Not yet, using Windows over SSH is on the roadmap but I don't think it is a priority right now. SSH is not included in the product, so unless that happens I doubt a lot of effort is being spend on this though.

So there are 2 issues in general:
1. SSH is very Unix-centric inside Ansible, so that needs to be fixed
2. WinRM and Powershell are currently assumed together

**Comment by MatthewFawcett** [comment]
Thanks for the reply and clarification.

**Comment by mindrunner** [comment]
Winrm is unstable, though.

See: https://github.com/ansible/ansible-modules-core/issues/5368

**Comment by jhawkesworth** [comment]
Linking to what I think is the relevant gh project for the purposes of monitoring progress.  https://github.com/PowerShell/Win32-OpenSSH/releases
At the very least this would require a new connection plugin.  Once there is something released it might be worth trying.  However I would be wary of considering that this will solve all problems managing windows hosts.

**Comment by jborean93** [comment]
Closing this issue in favour of https://github.com/ansible/ansible/issues/25344 so we can have one issue to document this.
