### ISSUE TITLE
fact_path in ansible.cfg has no effect

### ISSUE THREAD

**Issue by debalance** [ansible/ansible#24736]
##### ISSUE TYPE
 - Bug Report / Documentation Report

##### COMPONENT NAME
- setup

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
>  [defaults]
>  fact_path = /usr/share/whatever/ansible/facts/

##### OS / ENVIRONMENT
Debian Sid / Ubuntu Xenial

##### SUMMARY
configuring fact_path in ansible.cfg has no effect,
I learned the hard way what these guys already knew:
https://groups.google.com/forum/#!topic/ansible-project/iThupGsqPPQ

##### STEPS TO REPRODUCE
Create your local fact in the configured location and try to use it, it won't be found unless you move it into the default path /etc/ansible/facts.d/.

##### EXPECTED RESULTS
The configured fact_path should be used, or the documentation should be corrected,
as it is listed on http://docs.ansible.com/ansible/intro_configuration.html#fact-path to be a valid parameter for ansible.cfg

##### ACTUAL RESULTS
The default fact_path is used.

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Quoting the docs: **" for the implied setup task when using implied fact gathering"**, this setting only affects the `setup` task that is run triggered by the `gather_facts` keyword, not for `- setup` tasks you add to play.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by debalance** [comment]
I was talking about the implied fact gathering (I think) - the one that happens automatically before my play. When using the setup module explicitely in the play I can simply set fact_path there and it works, which is what I am doing now as a workaround.
