### ISSUE TITLE
Does EC2 Dynamic Inventory work with Assumed Roles in Shared Config?

### ISSUE THREAD

**Issue by ricfeatherstone** [ansible/ansible#24740]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

EC2 Dynamic Inventory

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION

https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory/ec2.py
https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory/ec2.ini

##### OS / ENVIRONMENT

RHEL 7 on AWS

##### SUMMARY

I'm working in an environment where I need to assume a role in all my AWS accounts where I want to run Ansible.

I am looking to use AWS shared credentials files to define profiles for the various roles I need to assume for the different accounts.

Is this even possible currently? I have searched and read a couple of issues but have been unable to find a resolution.

##### QUESTION

Can this be done?

##### STEPS TO REPRODUCE

run aws configure to setup the default credentials and also setup a profile for an assumed role, access keys are only set for the default profile

.aws/config
```
[default]
output = json
region = eu-west-1

[profile test]
role_arn = arn:aws:iam::123456789012:role/test
source_profile = default
```

`./ec2.py --list` works as expected and provides details from the default account, as does `AWS_PROFILE=default ./ec2.py --list`

However, both `./ec2.py --list --profile=test` and `AWS_PROFILE=test ./ec2.py --list` do not work

While searching I found https://github.com/ansible/ansible/issues/15215 which references an ec2.py script that enables `./ec2.py --list --profile test` to work but not `AWS_PROFILE=test ./ec2.py --list`

This is no use because there is no way to use it with Ansible if it is not using the env variable.

For all the failed attempts above the error is boto.provider.ProfileNotFoundError: Profile "test" not found!

Any help with this would be very much appreciated.

**Comment by nitzmahone** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by ricfeatherstone** [comment]
Hi, thanks. I assumed as it didn't work as documented that qualified it as a bug.
If it doesn't work with AWS_PROFILE, it'll not work with ansible or ansible-playbook commands right?
Anyhow, I'll try on the user list

**Comment by sebastianreloaded** [comment]
Yeah, for me this is also a bug. You cant use roles using the standard way, every other tool supports.

**Comment by karlroberts** [comment]
I also regard this as a bug a least with ec2.py maybe not with ansible directly. I need to access accounts via assumed Roles, I normally (aws cli) use a profile as per ricfeatherstone 's description above and add a common role that accesses sts and stores temporary credentials that I use in ansible tasks. But the assumed role is not working with ansible 2.4.0 and ec2.py. It just tells me "[WARNING]: provided hosts list is empty, only localhost is available"

This make the ec2.py remote inventory useless with ansible when you need assumed role access to an account that you are not the admin of.

Adendum, I now notice that you can uncomment iam_role in the ec2.ini file to pass a role to assume in. This works, but is is a shame that the ec2.py script wont use the ~/.aws/config profile as used by ricfeatherstone above.

**Comment by matthewapeters** [comment]
The ownership of ec2.py is with Ansible ("This file is a part of Ansible").  It is broken in that it does NOT support known and documented functionality of boto and/or boto3 and/or AWS with regards to profiles (AKA boto_profile). In particular, it does not provide a means to access cross-account sign-in functionality.  This is a significant issue for enterprise users who authenticate with one account and then work with instances in another (sub)account.

If this was a user issue, there would be a documented way to log in with default credentials, and using AWS_PROFILE (or --boto_profile or --profile at the CLI), assume the (visibility of) the identified role.  The problem is, defining a profile does not change the inventory view to account tied to the profile.  Instead, the inventory of the authenticating account is returned.

I think this ticket was closed naively, as the nuanced use of cross-account sign-in might not have been well appreciated.  Please re-consider the status of this ticket.

**Comment by jimsmith** [comment]
What matthewapeters has raised, this is a blocker for enterprise users and given Ansible is now with RedHat who have enterprise customers this I would love to see being implemented.

I keep coming across this for enterprise customers for more than 3 years now and was hoping this would have been resolved by now.

As `./ec2.py --refresh --profile accountb` and --profile only gets read from `~/.aws/credentials`
however the role_arn profiles which has the cross-account sign for account b are contained within  `~/.aws/config`

**Comment by jimsmith** [comment]
looks like this one is more active.? but slightly different as its temporarily sts token
https://github.com/ansible/ansible/issues/15215

**Comment by jimsmith** [comment]
referencing this it looks like maybe 2.5 version possibly
https://github.com/ansible/ansible/pull/34279

**Comment by ezegolub** [comment]
I rewrote a function in the current `ec2.py` to allow for using `python ec2.py --profile <my_aws_profile>` and it works with the data set in `~/.aws/config`. It's pretty horrible code, but maybe it can help someone else in trouble: 

```python
# add this to the top of file
from boto import sts

def connect_to_aws(self, module, region):
    connect_args = self.credentials
    # THIS PART WAS HACKED TO USE AWS PROFILES PROPERLY. USE AT OWN RISK
    if self.boto_profile:
        connect_args['profile_name'] = self.boto_profile
        aws_cfg = configparser.ConfigParser()
        aws_cfg.read(os.path.expanduser("~/.aws/config"))
        role_arn = dict(aws_cfg.items("profile " + self.boto_profile))["role_arn"]
        # please don't judge me
        del(connect_args['profile_name'])
        
        sts_conn = sts.connect_to_region(region, **connect_args)

        role = sts_conn.assume_role(role_arn, 'ansible_dynamic_inventory')
        connect_args['aws_access_key_id'] = role.credentials.access_key
        connect_args['aws_secret_access_key'] = role.credentials.secret_key
        connect_args['security_token'] = role.credentials.session_token

    conn = module.connect_to_region(region, **connect_args)
    # connect_to_region will fail "silently" by returning None if the region name is wrong or not supported
    if conn is None:
        self.fail_with_error("region name: %s likely not supported, or AWS is down.  connection to region failed." % region)
    return conn
```

**Comment by campee** [comment]
Worth mentioning that you also need to add this to ec2.py to get the above code working:
from boto import sts

**Comment by jgeorgeson** [comment]
thanks @ezegolub, I removed both the `connect_args['profile_name']=` and the `del(connect_args['profile_name'])` and it seems to go ok with that. The only gotcha I'm finding is I can't use `AWS_PROFILE` env variable because `sts.connect_to_region()`  still tries to find the profile in `~/.aws/credentials`.
