### ISSUE TITLE
update from ansible 0.9 -> 1.1 forced a changed sudo configuration 

### ISSUE THREAD

**Issue by holgerkoch** [ansible/ansible#2475]
Hi,

i make a update from ansible 0.9 to 1.1. All works fine, but it seems there are a problem with sudo, because alle privileged actions seems to hang.

I compared the execution call from 0.9 and 1.1:

ansible 0.9
..../bin/sh -c \'/usr/bin/python /opt/ansible/.ansible/tmp/ansible-1362122816.46-47847393406476/com....

ansible 1.1:
..../bin/sh -c \' /usr/bin/python /opt/ansible/.ansible/tmp/ansible-1362122816.46-47847393406476/com....

Who find the difference? There is a space character before the /usr/bin/python. Maybe we can remove it?
It would be great, if the line may never changed, because it it very painful for us to change the sudo configuration over all machines.

Best regards

Holger

**Comment by bcoca** [comment]
Are you being prompted for the sudo password?

ansible hangs in 2 cases, when it tries to use a password and NOPASSWORD is
set in sudoers or when it doesn't use a password and NOPASSWORD isn't set.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by holgerkoch** [comment]
Hi,

ansible will be prompted for a password, because the entry in the sudoers (with NOPASSWD) file is with One space and not with two.

Best regards

Holger

Am 21.03.2013 um 14:32 schrieb Brian Coca notifications@github.com:

**Comment by mpdehaan** [comment]
Ok so this sounds like a missing or wrong --ask-pass and not something Ansible should fix, let me know if not.

**Comment by holgerkoch** [comment]
It seems, that you don't understand me. So i will try to explain it in detail.

I've installed ansible 0.9 and configured the following sudo entry:

Cmnd_Alias AMBOS_CMD     =  /bin/sh -c /usr/bin/python /opt/ansible/.ansible/tmp/_/_; rm -rf /opt/ansible/.ansible/tmp/*
ansible        ALL     =       NOPASSWD: AMBOS_CMD
1. start a ansible playbook execution
2. ansible copied the ressources and connect to the target and login as a none-privilege user ansible
3. the ansible user makes a sudo call and execute the script as user root
4. ansible delete the ressources

With this sudo entry, all works fine without any password prompt. Why so complicated? Unfortunaly, i got no permission for the simple

ansible ALL = NOPASSWD:ALL

because of security reason.

Then i make a update to 1.1 and the privileged ansible execution hangs. After a review, i found the space character forward the /usr/bin/python. So the sudo entry doesn't match anymore and it will be prompted for a password. I changed the sudo entry to:

Cmnd_Alias AMBOS_CMD     =  /bin/sh -c \ /usr/bin/python /opt/ansible/.ansible/tmp/_/_; rm -rf /opt/ansible/.ansible/tmp/*
ansible        ALL     =       NOPASSWD: AMBOS_CMD

and all work fine again.

Is it possible to delete the space character? And it will be great, if the execution line will be changeless.

Thank you. Best regards. 

Holger

PS: Please forgive my terrible english.

**Comment by hugomrdias** [comment]
i have the same problem i can only run playbooks with ssh password , if i use keys it hangs
