### ISSUE TITLE
Documentation Error in command/shell section for playbooks

### ISSUE THREAD

**Issue by chuckadams** [ansible/ansible#2477]
The documentation at http://ansible.cc/docs/playbooks.html#tasks-list has a section that reads: 

> ```
> The command and shell module care about return codes, so if you have a command who’s successful exit code is not zero, you may wish to do this:
> 
> tasks:
>  - name: run this command and ignore the result
>    action: shell /usr/bin/somecommand && /bin/true
> ```

I'm pretty sure you mean to say /usr/bin/someommand || /bin/true

**Comment by mpdehaan** [comment]
ignore_errors: True

is kind of also a better way to do it.

**Comment by mpdehaan** [comment]
fixed, pushing shortly, thanks!
