### ISSUE TITLE
Change in behavior with playbook includes

### ISSUE THREAD

**Issue by alexbrand** [ansible/ansible#24788]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Ansible playbook
##### ANSIBLE VERSION

```
ansible-playbook 2.3.0.0
  config file = /repro/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### OS / ENVIRONMENT

CentOS Linux 7 (Core)

##### SUMMARY

Playbook includes seem to have a different behavior than in previous versions. Currently, when a `when` condition on a playbook include evaluates to `false`, the playbook is still included but the tasks themselves are skipped.

In previous versions (I specifically have been using ansible `2.1.4.0`), it would result in the play being completely skipped, and the logs not showing the play's tasks.
##### STEPS TO REPRODUCE

```yaml
---
  - include: a.yaml
    when: false
```

##### EXPECTED RESULTS

```
# ansible-playbook test.yaml

skipping playbook include 'a.yaml' due to conditional test failure

PLAY RECAP *********************************************************************
```
##### ACTUAL RESULTS

```
PLAY [The A play] ****************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
skipping: [localhost]

TASK [command] *******************************************************************************************************************************************************************
skipping: [localhost]

PLAY RECAP ***********************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0

```

**Comment by user140547** [comment]
This is probably related to the issue I have opened, when the playbook does not exist at all: https://github.com/ansible/ansible/issues/23601

**Comment by samdoran** [comment]
This is working as designed. Playbooks are now always statically imported, meaning the conditional is applied to every task in the play — the inclusion of the playbook is not evaluated and skipped.
