### ISSUE TITLE
async command unable to find python interpreter in alternate location even when specified with  ansible_python_interpreter

### ISSUE THREAD

**Issue by jl-montes** [ansible/ansible#24787]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

async

##### ANSIBLE VERSION

```
2.1.1.0
```

##### CONFIGURATION

[ssh_connection]
ssh_args=""
 
[defaults]
roles_path=roles/
inventory=hosts
private_key_file=/home/xxxxxx/.ssh/ansible_key
host_key_checking = False
remote_user = xxxxxxx
##### OS / ENVIRONMENT

Debian GNU/Linux 8 (jessie) in a Docker container

##### SUMMARY

When the async command is run it generates "async task produced unparseable results 
 and module_name async_status and /usr/bin/python not-found, even though the path to the python interpreter is specified in the hosts file and we've tried specifying it at the command-line.
Other docker playbooks/tasks run fine except for ones that have an async task.
 
##### STEPS TO REPRODUCE

ansible-playbook -vvv playbooks/platform/check-docker.yml -e hosts=10.200.1.1 -e ansible_python_interpreter="/opt/pypy-5.3.1-linux_x86_64-portable/bin/pypy"

```yaml
 - name:  Check docker ps - 20 second timeout
    shell: docker ps
    register: result
    ignore_errors: true 
    async: 20
    poll: 5
  - debug: var=result.stdout_lines

```

##### EXPECTED RESULTS

Expected the task/play to pass if docker responds within 20 seconds, and fail if docker does not respond within 20 seconds.
##### ACTUAL RESULTS

The playbook failed when the async tasks was executed. If we add other tasks/plays to the playbook that do not have async invocations, they run fine, only the ones that have an async invocation fail.

```
fatal: [10.200.1.1]: FAILED! => {"async_result": {"failed": true, "invocation": {"module_name": "async_status"}, "module_stderr": "", "module_stdout": "/bin/sh: /usr/bin/python: No such file or directory\r\n", "msg": "MODULE FAILURE", "parsed": false}, "changed": false, "failed": true, "msg": "async task produced unparseable results"}
```

**Comment by nitzmahone** [comment]
Any chance you could see if this behavior still exists in Ansible 2.2 or 2.3?

**Comment by jl-montes** [comment]
will try 2.2 today and update comments

**Comment by jl-montes** [comment]
works with 2.2  :-)  have not tried 2.3, will have to make a new docker image that includes v2.3 t test

**Comment by jl-montes** [comment]
Ooops , I made a mistake, I didn't wait long enough for my 1st test to complete.
The async command had not yet run

Please standby for test results with 2.2

**Comment by jl-montes** [comment]
I was able to confirm that with Ansible 2.3, this issue is solved/fixed.

**Comment by jl-montes** [comment]
Im happy with the solution in the newer version, will close the ticket
