### ISSUE TITLE
ec2_asg erroring with IndexError: list index out of range

### ISSUE THREAD

**Issue by tman77** [ansible/ansible#24807]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_asg

##### ANSIBLE VERSION

```
ansible 2.2.1.
```

##### OS / ENVIRONMENT

Running from Mac OS, running on EC2 @ AWS

##### SUMMARY

I am running a playbook that sets up some AWS infrastructure.  Security groups, Elastic Load Balancer, Launch Config, tag the ELB, all working well.

When I added an ASG setup using the ec2_asg module, the playbook failed.

##### STEPS TO REPRODUCE

```
#setup Logstash Autoscaling group
    - name: Elkstack LogStash ASG
      ec2_asg:
        name: pro-ELK-LogStash-ASG
        launch_config_name:  " {{ logstash_lc.name }} "
        health_check_period: 300
        health_check_type: EC2
        replace_all_instances: yes
        replace_batch_size: 1
        min_size: 1
        max_size: 4
        desired_capacity: 1
        region: us-east-1
```
For the launch_config_name, I'm getting the value from a register variable I set at the end of the asg_lc module. I've tried using using static (non-variable) entries, result is the same.

##### EXPECTED RESULTS

Expected Task to run with success status and to create the ASG

##### ACTUAL RESULTS

Error, see below:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/var/folders/08/x2n75q_925l5xc9hfjc1gz9c0000gn/T/ansible_HoDGb0/ansible_module_ec2_asg.py", line 875, in <module>
    main()
  File "/var/folders/08/x2n75q_925l5xc9hfjc1gz9c0000gn/T/ansible_HoDGb0/ansible_module_ec2_asg.py", line 864, in main
    create_changed, asg_properties=create_autoscaling_group(connection, module)
  File "/var/folders/08/x2n75q_925l5xc9hfjc1gz9c0000gn/T/ansible_HoDGb0/ansible_module_ec2_asg.py", line 437, in create_autoscaling_group
    launch_config=launch_configs[0],
IndexError: list index out of range

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "ec2_asg"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/08/x2n75q_925l5xc9hfjc1gz9c0000gn/T/ansible_HoDGb0/ansible_module_ec2_asg.py\", line 875, in <module>\n    main()\n  File \"/var/folders/08/x2n75q_925l5xc9hfjc1gz9c0000gn/T/ansible_HoDGb0/ansible_module_ec2_asg.py\", line 864, in main\n    create_changed, asg_properties=create_autoscaling_group(connection, module)\n  File \"/var/folders/08/x2n75q_925l5xc9hfjc1gz9c0000gn/T/ansible_HoDGb0/ansible_module_ec2_asg.py\", line 437, in create_autoscaling_group\n    launch_config=launch_configs[0],\nIndexError: list index out of range\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE"
}
```

**Comment by tman77** [comment]
Any help troubleshooting this, is greatly appreciated...
Thank you

**Comment by tman77** [comment]
@nitzmahone Why was the needs_triage removed?  Just curious....

**Comment by s-hertel** [comment]
needs_triage means the ticket still needs to checked for accuracy of labels/if enough information is provided. 

As of 2.3 ec2_asg has been ported to use boto3 and I am unable to reproduce this bug using it. But looking at your task, do you intend to have spaces around your launch configuration? e.g. if logstash_lc.name is 'asg-lc' I think the variable will be read with your syntax as ' asg-lc '. Does`launch_config_name:  "{{ logstash_lc.name }}"` produce the same error?

**Comment by tman77** [comment]
Ok, I reran without the spaces. I received a new error...

`"msg":` "Failed to create Autoscaling Group: BotoServerError: 400 Bad Request\n<ErrorResponse xmlns=\"http://autoscaling.amazonaws.com/doc/2011-01-01/\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>AssociatePublicIpAddress field can not be specified without a subnet id</Message>\n  </Error>\n  <RequestId>5ef6adc1-3cd3-11e7-9fbe-3f369cdbdeb8</RequestId>\n</ErrorResponse>\n"`

**Comment by s-hertel** [comment]
I was able to reproduce this on stable-2.2 with extra spaces around the variable, but not with 
the corrected syntax. When you specify the variable explicitly in the playbook, what does it look like?
needs_info

**Comment by tman77** [comment]
OK, specifying the vpc_zone_identifiers resolved the issue, thank you for the second set of eyes.
