### ISSUE TITLE
Apply a delegate_to to an include

### ISSUE THREAD

**Issue by asad-at-srt** [ansible/ansible#2480]
I have encapsulated a number of actions in a task.
I'm now able to run them conveniently on the executing server. Now I have a need to run this same task on a remote server.

It would be very powerful to be able to do:
- include: sometask
  delegate_to: <remote_server>

**Comment by mpdehaan** [comment]
There is a general thread on the mailing list about being able to apply arbitrary statements to includes and have them auto-affix to included tasks.

I think if we do this, it should be reasonably generic.

**Comment by mpdehaan** [comment]
deciding not to do this given I think it's rather confusing to read.
