### ISSUE TITLE
inventory group_vars/* do not win precedence over playbook group_vars/all as documented

### ISSUE THREAD

**Issue by gerrnot** [ansible/ansible#24824]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
inventory/group vars

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel d4857ed6c4) last updated 2017/05/19 12:44:14 (GMT +200)
  config file = 
  configured module search path = [u'/home/anon/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/anon/opt/ansible/ansible-devel/ansible/lib/ansible
  executable location = /home/anon/opt/ansible/ansible-devel/ansible/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```
and
```
ansible-playbook 2.3.1.0 (detached HEAD 5a3f52d988) last updated 2017/05/19 12:33:42 (GMT +200)
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```
##### OS / ENVIRONMENT
Linux Mint 18.1 Serena
However, defect should be independent of OS!

##### SUMMARY
More specific group vars (e.g.: vars defined in "inventory/testinventory" as "[testhostgroup:vars]") should always win precedence via less specific group vars (e.g.: "group_vars/all.yml") according to documentation. The behaviour worked in 2.1 as expected and makes sense imo. Unfortunately this seems having been broken since 2.3. (I did not check for 2.2).

### Folder Structure
group_vars/all.yml
```yaml
myvar: "group_vars/all.yml"
```
main.yml
```yaml
- hosts: testhostgroup
  tasks:
  - debug:
      var: myvar
```
testinventory
```
[all:vars]
myvar="file: testinventory [all:vars]"

[testhostgroup]
localhost

[testhostgroup:vars]
myvar="file: testinventory [testhostgroup:vars]"
```

### Playbook execution
```
ansible-playbook main.yml -i testinventory
```

##### EXPECTED RESULTS
```
"myvar": "file: testinventory [testhostgroup:vars]"
```
##### ACTUAL RESULTS
```
"myvar": "group_vars/all.yml"
```

**Comment by sivel** [comment]
The variable precedence docs state:
```
role defaults [1]
inventory INI or script group vars [2]
inventory group_vars/all
playbook group_vars/all
inventory group_vars/*
playbook group_vars/*
[SNIP]
```

The top has lower precedence.

Based on this, your INI groups vars listed in `[testhostgroup:vars]` have lower precedence than those listed in `group_vars/all.yml`

Based on this, the behavior you are seeing is correct, and clearly documented.

http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

**Comment by sivel** [comment]
To get the behavior you want, you need to move your vars out of `[testhostgroup:vars]` from you INI inventory file into `group_vars/testhostgroup.yml`

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
