### ISSUE TITLE
BUG (feature?) in file module: mount points not treated as dirs when mounted

### ISSUE THREAD

**Issue by robparrott** [ansible/ansible#2484]
Found an odd issue where a file module invocation for creating a mount point would fail. This is the latest devel on a Fedora 17 target host.

The "play" is this:

```
- name: setup a mount point for the gluster fs volume
  action: file path=/mnt/gv0 state=directory owner=root group=root mode=0755
```

And would fail, because it tried to create a directory "/mnt/gv0" that was already there.

Double checking, this directory is present with proper permissions, but it looks like the relevant issue was that the gluster volume had been mounted there already. It appears that the python call:

```
os.path.lexists(path)
```

returns False, so that the variable "previous_state" is incorrectly set to "absent." The error I see is:

```
failed: [ec2-54-234-255-179.compute-1.amazonaws.com] => {"failed": true, "item": "", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/ec2-user/.ansible/tmp/ansible-1363968920.06-246928354359522/file", line 1113, in <module>
main()
  File "/home/ec2-user/.ansible/tmp/ansible-1363968920.06-246928354359522/file", line 228, in main
    os.makedirs(path)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/mnt/gv0'
```

When I fire up python on the target system from a shell, os.path.lexists(path) return True for the target path. In addition, when I unmount the volume from that mount point, the module works properly as well. 

Any ideas?

**Comment by mpdehaan** [comment]
I don't think it has to do with the lexists, but I'll take a look and see if I can replicate the behavior.  This seems strange to me.

Maybe you have a Schroendinger quantum directory :)

**Comment by robparrott** [comment]
I wouldn't bother at this point. Some strange voodoo was going on related
to directory mounts.

**Comment by mpdehaan** [comment]
Ok.   Curious to what that was though.

Thanks!

**Comment by cordmata** [comment]
@robparrott Did you ever find out the cause of this? I'm seeing the exact same behavior.

**Comment by nueces** [comment]
I did some changes in my vars that modified the /etc/exports (change netblok ip clients) in the nfs server, thats remove the permission to the host in where the mount was configured, then when the play run in the client, it fail with the error:

```
failed: [nfs-client] => {"failed": true, "item": ""}
msg: Error making dir /srv/plone/buildout/var/blobstorage: [Errno 17] File exists: '/srv/plone/buildout/var/blobstorage'
```

```
nfs-client $ python
>>> import os
>>> path = "/srv/plone/buildout/var/blobstorage"
>>> os.path.lexists(path)
False
```

```
nfs-client $ cd /srv/plone/buildout/var/
nfs-client $ ls -l
ls: cannot access blobstorage: Permission denied
total 56
d????????? ? ?     ?        ?                ? blobstorage
[..]
```

If I umount the directory before run the play it works as expect. I'm not sure about whats is the best way to manage this, but I leave the info here in case that it could help others.
