### ISSUE TITLE
Wrong temp path OSX

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#24844]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /Users/mateus/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### CONFIGURATION
ask_become_pass=True
ask_sudo_pass=True
local_tmp = /Users/mateus/.ansible/tmp

##### OS / ENVIRONMENT
macOS 101.12.5

##### SUMMARY
For some reason Ansible is trying to create a temp file on the wrong directory, since macOS uses /Users/ instead of /home/.
My $HOME variable is fine (/Users/mateus/)
Already tried setting local_tmp and remote_tmp.
As you can see below, the ControlPath is right, only the mkdir is wrong

##### ACTUAL RESULTS
```
<[HIDDEN_IP]> ESTABLISH SSH CONNECTION FOR USER: mateus
<[HIDDEN_IP]> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/Users/mateus/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=mateus -o ConnectTimeout=10 -o ControlPath=/Users/mateus/.ansible/cp/6cf90d6e66 [HIDDEN_IP] '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<[HIDDEN_IP]> (0, '/home/mateus\n', '')
<[HIDDEN_IP]> ESTABLISH SSH CONNECTION FOR USER: mateus
<[HIDDEN_IP]> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/Users/mateus/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=mateus -o ConnectTimeout=10 -o ControlPath=/Users/mateus/.ansible/cp/6cf90d6e66 [HIDDEN_IP] '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/mateus/.ansible/tmp/ansible-tmp-1495220924.36-187159279265629 `" && echo ansible-tmp-1495220924.36-187159279265629="` echo /home/mateus/.ansible/tmp/ansible-tmp-1495220924.36-187159279265629 `" ) && sleep 0'"'"''
<[HIDDEN_IP]> (1, '', 'mkdir: cannot create directory \xe2\x80\x98/home/mateus/.ansible/tmp/ansible-tmp-1495220924.36-187159279265629\xe2\x80\x99: No space left on device\n')
```

**Comment by sysadmin75** [comment]
<[HIDDEN_IP]> (1, '', 'mkdir: cannot create directory \xe2\x80\x98/home/mateus/.ansible/tmp/ansible-tmp-1495220924.36-187159279265629\xe2\x80\x99: No space left on device\n')

If you look at the error, it shows there is no space left on the partition for the server this task is ran on.

If you still feel there is a bug, then more info is needed. Please provide the OS version of the management server (the server you're running ansible) and the OS version of the managed server (the server that you want the task to run on.
And provide the tasks that you're running.

**Comment by ghost** [comment]
@sysadmin75 

Management Server: My dev machine (macOS 10.12.5, ansible installed via Homebrew)
Managed Server: Ubuntu 14.04

The problem is that Ansible is trying to create some temporary files on my local machine, but it's using the wrong path, there's no `/home/[user]/` on a mac, it's in `/Users/[user]/`.

The error message it's actually wrong since there are plenty of free GBs on my system. The weird thing is that SSH `ControlPath` path is correct, only the mkdir after that is wrong. The error comes right after the "Gathering Facts", but I can provide a full log on Monday.

Here is a screenshot showing that there's no users on /home/, my $HOME variable and the amount free in the system. Thank you.
![screen shot 2017-05-20 at 14 23 31](https://cloud.githubusercontent.com/assets/6289699/26278006/5d6c219a-3d68-11e7-82e5-d8279615bb22.png)

**Comment by sivel** [comment]
It looks as though you are connecting to the Mac host via SSH, and it is returning `/home/user` as a result of `echo ~`

Not sure why, and I haven't experienced that myself.
