### ISSUE TITLE
does postgresql_db  support dump and import states ? 

### ISSUE THREAD

**Issue by engineer-it1** [ansible/ansible#24882]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by aioue** [comment]
@engineer-it1, [no it does not currently support these states. A PR would likely be welcome.](http://docs.ansible.com/ansible/postgresql_db_module.html)

**Comment by alikins** [comment]
This is not a bug report or a feature request, so closing.
