### ISSUE TITLE
ansible_processor_count seems wrong

### ISSUE THREAD

**Issue by thekad** [ansible/ansible#2492]
Hi,

When using ansible's builtin facter mechanism, the following happens:

```
    "ansible_processor": [
        "Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz",
        "Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz",
        "Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz",
        "Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz"
    ],
    "ansible_processor_cores": 2,
    "ansible_processor_count": 1,
```

As you can see, there are 4 processors (two dual core processors) but the processor count seems wrong. The /proc/cpuinfo file in the machine agrees and there are 4 processors recognized by the linux kernel. I am missing something obvious here?

**Comment by thekad** [comment]
Sorry, using ansible 1.0 as packaged for fedora 18.

**Comment by lwade** [comment]
Actually this is correct. Your CPU is dual core with hyperthreading, so its counting the number of physical CPUs (1) correctly. It's then counting the number of physical cores correctly (2) and finally its showing all cores (2 physical and 2 virtual hyperthreaded).

I've not looked at the module source but this _looks_ fine.

**Comment by cyrusdavid** [comment]
I'm having mine like this:

```
        "ansible_processor": [
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz", 
            "GenuineIntel", 
            "Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz"
        ], 
        "ansible_processor_cores": 6, 
        "ansible_processor_count": 1, 
        "ansible_processor_threads_per_core": 2, 
        "ansible_processor_vcpus": 12
```

But I think it's only having two cores:

```
$ cat /proc/cpuinfo 

processor   : 0
vendor_id   : GenuineIntel
cpu family  : 6
model       : 62
model name  : Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz
stepping    : 4
cpu MHz     : 2600.109
cache size  : 15360 KB
physical id : 0
siblings    : 12
core id     : 0
cpu cores   : 6
apicid      : 0
initial apicid  : 0
fpu     : yes
fpu_exception   : yes
cpuid level : 13
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dts tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips    : 5200.21
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor   : 1
vendor_id   : GenuineIntel
cpu family  : 6
model       : 62
model name  : Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz
stepping    : 4
cpu MHz     : 2600.109
cache size  : 15360 KB
physical id : 0
siblings    : 12
core id     : 1
cpu cores   : 6
apicid      : 2
initial apicid  : 2
fpu     : yes
fpu_exception   : yes
cpuid level : 13
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dts tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips    : 5200.21
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

Am I suppose to divide a value by something to get the right value (ansible_processor_vcpus / ansible_processor_cores)? Thanks. And sorry for my noobity.

**Comment by bcoca** [comment]
@vohof 
From intel's own specs, this is a 1 die, 6 core (12 counting hyperthreading) cpu.
http://ark.intel.com/products/64593/Intel-Xeon-Processor-E5-2630-15M-Cache-2_30-GHz-7_20-GTs-Intel-QPI

so ansible does seem to be getting it right, not sure why cpuinfo is only showing 2, are you under some type of virtualization (xen,kvm,etc)?.

**Comment by cyrusdavid** [comment]
Hi, yes. I think it's under openvz.

**Comment by bcoca** [comment]
openvz will modify cpuinfo to show cpu resource limitation to that instance, ansible is showing the full hardware data as openvz does not modify all the data sources about the cpu, which ansible uses.

**Comment by cyrusdavid** [comment]
@bcoca I see. For future reference this is what I have done:

``` yaml
  - shell: cat /proc/cpuinfo | grep processor | wc -l
    register: processor_count
    tags: processor_count
```

**Comment by coofercat** [comment]
(If it matters, I'm using Centos 6 and 7 on Google Cloud VMs - which also reports CPU counts incorrectly)

I went a stage further and used @vohof's shell command to make a `/etc/ansible/facts.d/apparent_cpus.fact` file.

I appreciate the core of Ansible shouldn't contain every last possible thing, but it'd be great if it could contain something like this - if changing the existing counters is problematic for compatibility, then an additional variable with the "actual" CPU count would be very helpful.

**Comment by yaron-tracxpoint** [comment]
@vohof:
Maybe consider using less binaries:
`shell: grep -c processor /proc/cpuinfo`

This will only count the occurrences of the word "processor" in `/proc/cpuinfo`.
