### ISSUE TITLE
ansible_ssh_host populated from CloudForms inventory in Ansible Tower should contain external IP

### ISSUE THREAD

**Issue by quarckster** [ansible/ansible#24920]
##### ISSUE TYPE

 - Feature

##### COMPONENT NAME

https://github.com/ansible/ansible/blob/devel/contrib/inventory/cloudforms.py#L264

##### SUMMARY

The variable returned as 'ansible_ssh_host' for AWS EC2 instances in Ansible Tower (from CloudForms) contains the internal AWS IP address. As a result Ansible Tower cannot access the instance to perform configuration/run playbooks. ManageIQ developers have made the required changes https://github.com/ManageIQ/manageiq/pull/11491. Now ansible code should be changed as proposed here https://bugzilla.redhat.com/show_bug.cgi?id=1375639#c15.

**Comment by ryansb** [comment]
For code changes, please file a pull request so we can follow the normal review process.

**Comment by jctanner** [comment]
cc @mrjoshuap

**Comment by snecklifter** [comment]
This is a problem for VMs running OpenShift as well. Its pot luck whether they return the correct IP. Usually its the docker one.

**Comment by switchboardOp** [comment]
Same issue here, running OpenShift nodes on vmware. Inventory is synced from CloudForms and it is a crap-shoot which IP will be set for `ansible_ssh_host`.

Why use IPs here at all? I would assume `ansible_ssh_host` should be a hostname.

**Comment by AlanCoding** [comment]
if this is still an issue you can file in the AWX issue queue (if it's not already there, which it may be)

close_me
