### ISSUE TITLE
lineinfile test fails in dev branch

### ISSUE THREAD

**Issue by Tinche** [ansible/ansible#2493]
After checking out the latest git version, running the tests results in:

``` python
test_lineinfile (TestRunner.TestRunner) ... FAIL

======================================================================
FAIL: test_lineinfile (TestRunner.TestRunner)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tin/pg/ansible/test/TestRunner.py", line 308, in test_lineinfile
    assert result['changed'] == True
AssertionError: 
    {u'msg': u'', 'invocation': {'module_name': 'lineinfile', 'module_args': "dest=/home/tin/pg/ansible/test/test_data/rocannon.out.txt regexp='^First: ' line='First: Line added by default at the end of the file.'"}, u'changed': False} = self._run(*('lineinfile', ['dest=/home/tin/pg/ansible/test/test_data/rocannon.out.txt', "regexp='^First: '", "line='First: Line added by default at the end of the file.'"]))
>>  assert {u'msg': u'', 'invocation': {'module_name': 'lineinfile', 'module_args': "dest=/home/tin/pg/ansible/test/test_data/rocannon.out.txt regexp='^First: ' line='First: Line added by default at the end of the file.'"}, u'changed': False}['changed'] == True
    assert {u'msg': u'', 'invocation': {'module_name': 'lineinfile', 'module_args': "dest=/home/tin/pg/ansible/test/test_data/rocannon.out.txt regexp='^First: ' line='First: Line added by default at the end of the file.'"}, u'changed': False}['msg'] == 'line added'
    artifact = [ x.strip() for x in open('/home/tin/pg/ansible/test/test_data/rocannon.out.txt').readlines() ]

-------------------- >> begin captured stdout << ---------------------
DEBUG: using args=dest=/home/tin/pg/ansible/test/test_data/rocannon.out.txt regexp='^First: ' line='First: Line added by default at the end of the file.'
RESULTS={'dark': {}, 'contacted': {'localhost': {u'msg': u'', 'invocation': {'module_name': 'lineinfile', 'module_args': "dest=/home/tin/pg/ansible/test/test_data/rocannon.out.txt regexp='^First: ' line='First: Line added by default at the end of the file.'"}, u'changed': False}}}

--------------------- >> end captured stdout << ----------------------
```

This is on 64-bit Quantal. 64-bit CentOS 6.3 has the same issue.

**Comment by mpdehaan** [comment]
I'm wondering if it's an actual problem or the test is just a little off.

A real world check would probably help say for sure.

Something you would like to investigate, perhaps?

**Comment by Tinche** [comment]
Sure, let me get back to you in a day or two.

**Comment by mpdehaan** [comment]
Excellent, thanks.

lineinfile is a module I usually try to avoid using, when possible, just
because templates work out that much nicer.

Thanks!

**Comment by tima** [comment]
This is the commit that broke this test: https://github.com/ansible/ansible/commit/bff581be4c30ec17fd146954eab4cf0d60b20810

My comments cover what I think it the problem that it is failing here.

**Comment by Tinche** [comment]
Thanks for bringing that up, @tima.

Let me just make sure I understand what the lineinfile module is supposed to be doing, because the documentation and the offending test case seem to be at odds with each other here.

The lineinfile module is being executed with the following params: dest regexp line (state is unspecified and defaults to 'present', and I guess insertafter defaults to EOF). The regexp doesn't match any lines in the file.

According to the module documentation, the regexp parameter stands for: 

> The regular expression to look for in the file. For C(state=present), **the pattern to replace**. 

To me, this is saying the following: the module will loop over all lines in the file and try to match them against the regexp; if a line matches, it will be replaced with the 'line' param. If no lines match, nothing will be done.

The offending test, however, understands it another way: if no lines match, the line param will be added to the end of the file.

From a logical standpoint, the reasoning of the test makes sense: the module will ensure the line is in the file. If the test behavior is the correct one, I would suggest (in addition to fixing the module) to amend the documentation slightly; the regexp param is the pattern to replace **if found**, else the line will be added according to insertbefore/insertafter (which could be better documented too).

So to confirm, if the regexp doesn't match any lines, the line should be added according to insertbefore/insertafter?

**Comment by Tinche** [comment]
P.S. I hope you guys like pep8.

**Comment by Tinche** [comment]
Another question before I go to sleep: mutually_exclusive arguments with default values aren't supported?

**Comment by mpdehaan** [comment]
Not sure I understand that last question.

We can revert the above, but if you have a better fix coming, that would be great.   Let me know!

**Comment by Tinche** [comment]
1) I'll have something for you in the evening.

2) the lineinfile module declares insertbefore and insertafter as mutually_exclusive. If I change insertafter to default to 'EOF' (as stated in the docs and needed for the module to work properly) I get errors if only insertbefore is specified. (u"parameters are mutually exclusive: ['insertbefore', 'insertafter']")

3) Merging https://github.com/ansible/ansible/commit/84ee05a3c0d7921da9489a2ddeda1644b7faa4d9 (allow use of backrefs in lineinfile) changed th semantics of lineinfile slightly, leading to https://github.com/ansible/ansible/commit/bff581be4c30ec17fd146954eab4cf0d60b20810 (disabled appending file with garbage when regexp didn't match).

It's simple if you think about it: using back references in 'line' makes 'line' dependent on the regexp matching (so the backrefs can be populated). This breaks the use case when the regexp doesn't match at all, and line is expected to be inserted into the file. This is why the other user had problems with garbage being inserted: he was using a line with back references and a file which didn't have any lines matching the regexp. I'm not sure how to deal with this without breaking backward compatibility. 

I'd need to know if 'line' contains backrefs, so either ask the user (via a param) or parse the line for backslashes? (Might get false positives? Who knows what people use backslashes for.)

But even if this could be fixed somehow, the lineinfile module would behave differently based on if the 'line' param contained backrefs. This might be a problem since the module isn't the simplest to begin with.

What's your opinion on all of this? I'd be happy to clarify anything you want.

**Comment by mpdehaan** [comment]
backreferences are new in 1.1, so a parameter to enable backreferences is reasonable to add, we wouldn't be breaking compat with a previous release.

**Comment by Tinche** [comment]
Roger, I'll do that then.

**Comment by Tinche** [comment]
This is in progress at https://github.com/Tinche/ansible. I still want to expand a little in the unit tests, clarify/expand the documentation and do a proper functional test before doing a PR).

**Comment by srgvg** [comment]
fyi, guess it's related:

``` bash
serge@goldorak:~/tmp$ cat test
cat: test: No such file or directory
serge@goldorak:~/tmp$ ansible -c local -i localhost, all -m lineinfile -a "regexp=testline line=testline state=present dest=/home/serge/tmp/test create=yes"
localhost | success >> {
    "changed": false, 
    "msg": ""
}

serge@goldorak:~/tmp$ cat test
cat: test: No such file or directory
```

**Comment by mpdehaan** [comment]
Fixed per nice work from @Tinche above, so closing.
