### ISSUE TITLE
ConfigureRemotingForAnsible.ps1 doesn't allow me to use existing machine certificate

### ISSUE THREAD

**Issue by kamranayub** [ansible/ansible#24931]
Related #21263

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ConfigureRemotingForAnsible.ps1

##### ANSIBLE VERSION
```
2.2.3
```

##### OS / ENVIRONMENT
Ansible configuring Windows (2012/2016)

##### SUMMARY
The enable remoting script does not seem to be compatible with an environment that already pre-provisions machine certs from Active Directory. Usually in a domain-joined environment, each machine already gets a CA signed certificate matching its DNS host name. I'd like to use *that* certificate, not a self-signed one

##### STEPS TO REPRODUCE
1. Have a signed certificate already in the machine cert store
2. Run the ConfigureRemotingForAnsible.ps1 script

##### EXPECTED RESULTS
I think defaulting to a self-signed cert is expected and desirable for most use cases, but I would like to pass a switch to use an existing cert, if it is present.

##### ACTUAL RESULTS
Observe how it creates and uses a self-signed cert rather than using the existing signed cert.

##### PROPOSAL

I can contribute a change that allows the user to pass in a switch, `-UseExistingMachineCert` that will just use an existing certificate if it matches the machine name instead. If there is no match, it continues to create a self-signed cert. The rest of the script should be unaffected since CA verfication is turned off.

It looks like there's an unused param, `$CreateSelfSignedCert` that could be used for this purpose too, if it's `$false` it would not create a self-signed cert unless `-ForceNewSSLCert` was enabled for an existing listener.

**Comment by ryansb** [comment]
cc/ @nitzmahone

**Comment by trondhindenes** [comment]
That's funny, I'm _quite_ sure we added support for only generating a cert if a fitting one isn't already in place. I'll have a look at this.

**Comment by trondhindenes** [comment]
hm, so it seems _lots_ of stuff happened since I last had a look at that file. You are indeed right, it will (re)generate a cert regardless of any existing certificate. I'll see if I can get a PR in that will fix this. 
I'm thinking the logic will be like this: If there's already a cert in place with the required type (ie that it can be used for `Server Authentication`) and the cert isn't expired, then we will use that instead of generating a new one. For users who want to override this, they kan set a `ForceNewSSLCert` switch parameter. I'm pretty sure that's how the original version of the script worked. Note that we _dont_ check the name of the original certificate, only usage type and expiry.  Would you agree with the logic?

**Comment by kamranayub** [comment]
That should work in my case at least. As long as the script ensures the
NETWORK SERVICE user has access to the key, it should work. Thanks!

**Comment by trondhindenes** [comment]
Why would you need network service access? It seems to me that this is a very environment-specific requirement, and shouldn't necessary be added to a generic bootstrap script.

**Comment by kamranayub** [comment]
It's just a requirement of how WinRM works over HTTPS, since it runs as the
NETWORK SERVICE account. Without that step, it won't work.

**Comment by kamranayub** [comment]
I should say specifically it's how it works with domain certificates.
Obviously it's been working with self signed ones fine. Most tutorials skip
that fact, but it's documented in various places.
https://social.technet.microsoft.com/Forums/windowsserver/en-US/be06b96d-9485-4564-a78e-ba523a908259/powershell-remoting-credssp-http-500-from-winrm-service?forum=winserverpowershell

**Comment by jborean93** [comment]
Closing, see https://github.com/ansible/ansible/pull/24938#issuecomment-354687634
