### ISSUE TITLE
ConfigureRemotingForAnsible.ps1 enables Basic auth which may not be desirable

### ISSUE THREAD

**Issue by kamranayub** [ansible/ansible#24933]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ConfigureRemotingForAnsible.ps1

##### ANSIBLE VERSION
```
2.2.3
```

##### OS / ENVIRONMENT
Ansible configuring Windows (2012/2016)

##### SUMMARY
Currently, the ConfigureRemotingForAnsible.ps1 script will enable Basic auth (and optionally CredSSP). However, in some instances a VM may already have WinRM over HTTP enabled so enabling Basic over HTTP would be undesirable for security (and CredSSP to an extent as well). The script should allow you to pass in a list of auth types to enable (Basic/CredSSP). Additionally, it might be good to remove HTTP listeners if the user wants.

##### PROPOSAL

Add a new parameter, `-AuthTypes` defaulted to `Basic, CredSSP` for back-compat but that allows users to override what auth types to enable (maybe add Kerberos too?).

Add a new parameter, `-EnsureSslOnly` that will ensure only the HTTPS listener is enabled and remove the HTTP listener and any firewall rules that allow that listener through. Alternatively, could have a choice parameter `-Protocols Http, Https` that would allow some customization. Using SSL only is probably best practice anyway. Up for debate!

These changes should be backwards compatible with the existing script.

**Comment by ryansb** [comment]
cc/ @nitzmahone

**Comment by jborean93** [comment]
Closing see https://github.com/ansible/ansible/pull/24938#issuecomment-354687634
