### ISSUE TITLE
copy module: broken recursive copy with relative paths for dest

### ISSUE THREAD

**Issue by abadger** [ansible/ansible#24949]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
copy.py

##### ANSIBLE VERSION

```
devel
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

For When given a destination directory that is relative, the copy module throws an error instead of copying.

##### STEPS TO REPRODUCE
```
$ ansible localhost -m copy -a 'src=/var/tmp/idna-2.5 dest=sub'
```

##### EXPECTED RESULTS

Copy would copy the files successfully.
##### ACTUAL RESULTS

```
localhost | FAILED! => {
    "changed": false, 
    "checksum": "8f1c8edad0338f65dace85a9b68ea469c858427b", 
    "failed": true, 
    "msg": "Destination directory sub/idna-2.5/idna does not exist"

```

**Comment by jctanner** [comment]
resolved_by_pr https://github.com/ansible/ansible/pull/24393
