### ISSUE TITLE
Ansible command module generating file not found error when running source command

### ISSUE THREAD

**Issue by os2tux** [ansible/ansible#24956]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```[root@enaic ~]# ansible --version 
ansible 2.4.0 (devel 4a718645e8) last updated 2017/05/19 16:34:26 (GMT -500)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible/lib/ansible
  executable location = /root/ansible/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]```

##### CONFIGURATION
<!---
N/A
-->

##### OS / ENVIRONMENT
<!---
server running Ansible:
[root@enaic ~]# cat /etc/fedora-release 
Fedora release 25 (Twenty Five) 

server being managed:
[ec2-user@ip-100-104-150-88 ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.3 (Maipo)
-->

##### SUMMARY
<!---Whenever I attempt to run a source command against a shell script downloaded as part of an installation process governed by my playbook, Ansible errors out and says that the file can't be found on the remote host. I confirmed the file is available, and copied and pasted the command directly from the error output generated running in verbose mode to confirm it works on the server being managed when run outside of the Ansible playbook, which it did. I also validated no permissions issues existed. I also spun up a second EC2 instance to determine whether is an issue in the current packaged release for RHEL (since my other box is running from source) and I experienced the same issue. While observing the verbose output of the running playbook, it looks a directory is being removed prior to the that error being generated, leading me to wonder if the message is referencing this missing directory rather than the file I'm trying to source, since I know Ansible creates a local temp directory for artifacts needed to run the actions specified in the playbook. I also confirmed Ansible is attempting to run the command remotely as opposed to locally by creating the file locally and watching Ansible fail to find the specified file from the server running the playbook.  -->

##### STEPS TO REPRODUCE
<!---
If you attempt to source the rvm shell script generated as part of the installation process for rvm, in either Ansible 2.3 or 2.4, the issue occurs. Running the command specified in the playbook (copying and pasting directly from the playbook) does not exhibit the same behavior
-->

<!--- Paste example playbooks or commands between quotes below -->
```---
- hosts: oxidized_servers
  remote_user: ec2_user
  become: yes
  become_user: root
  tasks:
      - name: install repository channel required for package availability
        command: yum-config-manager --enable rhui-REGION-rhel-server-optional
       
      - name: Install required packages for oxidized
        yum:
          name:
            - curl
            - gcc-c++
            - patch
            - readline
            - readline-devel
            - zlib
            - zlib-devel
            - libyaml-devel
            - libffi-devel
            - openssl-devel
            - make
            - cmake
            - bzip2
            - autoconf
            - automake
            - libtool
            - bison
            - libssh2-devel
          state: latest

      - name: import mpapis public key in order to download rvm artifacts
        command: gpg2 --keyserver hkp://keys.gnupg.net --recv-keys     command: rvm use --default 2.3.4

      - name: install oxidized
        command: gem install oxidized oxidized-web
    command: rvm use --default 2.3.4

      - name: install oxidized
        command: gem install oxidized oxidized-web
409B6B1796C275462A1703113804BB82D39DC0E3

      - name: download the rvm artifacts
        get_url:
            url: http://get.rvm.io
            dest: /tmp/rvm_installation_script.sh
            mode: 0755
      
      - name: run the rvm installation script
        command: sh /tmp/rvm_installation_script.sh

      - name: source the rvm shell script to initialize rvm
        command: source /etc/profile.d/rvm.sh

      - name: install ruby into the rvm environment
        command: rvm install 2.3.4

      - name: make installed version of Ruby default for this rvm environment    
         command: rvm use --default 2.3.4

      - name: install oxidized
        command: gem install oxidized oxidized-web```

<!--- You can also paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!---I expected the playbook to run the source command to activate rvm, which works when running the command outside of the playbook--->

##### ACTUAL RESULTS
<!---The playbook process fails with an error stating that it can't find the specified file, despite it clearly existing on the server being managed (cmd output below) -->

<!--- Paste verbatim command output between quotes below -->
```
<100.104.150.88> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/NetSVCS_dev_privkey.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/bdd0e53fed -tt 100.104.150.88 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-itojnmwotcjsiuhbivjoepbuviftoapc; /usr/bin/python /home/ec2-user/.ansible/tmp/ansible-tmp-1495472025.21-149485595102166/command.py; rm -rf "/home/ec2-user/.ansible/tmp/ansible-tmp-1495472025.21-149485595102166/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<100.104.150.88> (0, '\r\n{"msg": "[Errno 2] No such file or directory", "failed": true, "cmd": "source /etc/profile.d/rvm.sh", "rc": 2, "invocation": {"module_args": {"warn": true, "executable": null, "_uses_shell": false, "_raw_params": "source /etc/profile.d/rvm.sh", "removes": null, "creates": null, "chdir": null}}}\r\n', 'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 71: Applying options for *\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 64693\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to 100.104.150.88 closed.\r\n')
```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

In any case, the issue is that `source` is NOT a command, its a shell builtin, also it is a useless command as each task does it's own login and gets a new shell, so sourcing a file in a task will not affect subsequent tasks.

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by os2tux** [comment]
Brian:

Makes sense; I resolved my issue successfully by making some changes to my command invocation syntax. Thanks for the quick response and for pointing that out to me.

It’s appreciated!

Respectfully,

Joseph Shelby

Sr. Network Services Engineer, IT Voice and Data Networks
zoom: https://asurion.zoom.us/my/josephshelby
voice: 615.445.1240 | mobile: 615.210.6139
mail: Asurion I 648 Grassmere Park, Nashville, TN 37211
www.asurion.com<http://www.asurion.com/> I Twitter<https://twitter.com/Asurion> I Facebook<https://www.facebook.com/Asurion>
