### ISSUE TITLE
Ansible repository for Ubuntu 17.04 broken

### ISSUE THREAD

**Issue by adam-kosseck** [ansible/ansible#24961]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
-  Ansible Repository

##### ANSIBLE VERSION
- 2.3.x

##### CONFIGURATION
- N/A

##### OS / ENVIRONMENT
- Ubuntu 17.04 (Zesty)

##### SUMMARY
Attempts to install Ansible on Ubuntu 17.04, by following the [install guide](http://docs.ansible.com/ansible/intro_installation.html) fail due to a missing release file.
During the 3rd step (repository update), the following errors are encountered:
```
Err:18 http://ppa.launchpad.net/ansible/ansible/ubuntu zesty/main amd64 Packages
  404  Not Found
.
.
.
W: The repository 'http://ppa.launchpad.net/ansible/ansible/ubuntu zesty Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/zesty/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

##### STEPS TO REPRODUCE
Follow Ansible install steps for Ubuntu:

```
$ sudo apt-get install software-properties-common
$ sudo apt-add-repository ppa:ansible/ansible
$ sudo apt-get update
$ sudo apt-get install ansible
```

**Comment by golgoth31** [comment]
This is not a bug from ansible, it's related to the ppa witch doesn't have any build for zesty currently. you should change your ansible ppa list to yakkety.

**Comment by adam-kosseck** [comment]
Ok - my apologies. I assumed the Ansible team was responsible for creating/providing builds for each release.

**Comment by gundalow** [comment]
Sounds like this isn't a bug, so closing. Please re-open if that's not the case.
