### ISSUE TITLE
Update docs for junos module

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/ansible#24975]
##### ISSUE TYPE

  - Documentation Report

##### COMPONENT NAME

junos_* modules

##### ANSIBLE VERSION

```
2.3.0.0
```

##### SUMMARY

With Ansible 2.3 junos modules dont need junos-eznc as dependency. But the docs for few of junos module still mention junos-eznc as required dependency. So just need to update the docs.

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by jctanner** [comment]
cc @Qalthos @ganeshrn
