### ISSUE TITLE
Yum Group Installs reporting changed everytime Centos6.3

### ISSUE THREAD

**Issue by rubbsdecvik** [ansible/ansible#2499]
# Description:

When installing a yum package group, the yum module will report `"changed": true` every time, even if the packages in the group are already installed
# What is expected:

If all packages in the group are installed, `"changed"` should be false.
# To reproduce

Run the yum module on a Centos 6.3 server with a group name in the `"name="` argument.
# Example:

```
pregan@fizban:~/workspace/local_ansible$ ansible -i ./hosts kvm -m yum -a"name='@Virtualization Platform' state=present"

ak002 | success >> {
    "changed": true, 
    "msg": "Warning: Group virtualization-platform does not have any packages.\n", 
    "rc": 0, 
    "results": [
        "Package virt-who-0.8-5.el6.centos.noarch already installed and latest version\nPackage libvirt-client-0.10.2-18.el6_4.2.x86_64 already installed and latest version\nPackage libvirt-0.10.2-18.el6_4.2.x86_64 already installed and latest version\n"
    ]
}
```

**Comment by mpdehaan** [comment]
@skvidal I can't remember what the consensus for this was on IRC.  Any idea what we need to change here?

**Comment by rubbsdecvik** [comment]
@mpdehaan No consensus yet. I was hoping to take a look at it to see if I can at least identify why it's not working, but yesterday was crazy busy for me and today is my birthday, so I won't even look at it until tomorrow.

@skvidal may have more info.

**Comment by mpdehaan** [comment]
closing given no progress on this.  I don't think it's too terrible in the current state.   Patches welcome.
