### ISSUE TITLE
win_command hangs when running batch file with start /b

### ISSUE THREAD

**Issue by Aroweeri** [ansible/ansible#25004]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - win_command

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5
```

##### OS / ENVIRONMENT

Controller: CentOS Linux 7 (Core)
Remote: Windows 8.1

##### CONFIGURATION
Fresh install of ansible. Edited hosts file, added playbooks.
Installed pywinrm on Linux controller w/ ```pip install "pywinrm>=0.2.2"```
Set up basic authentication to the remote windows box using the ConfigureRemotingForAnsible.ps1 script.

##### SUMMARY

When trying to run a windows script that starts a background process, I find that ansible never finishes execution.

##### STEPS TO REPRODUCE

Set up a windows remote host. Test connection with ```ansible windows -m win_ping``` (this works for me)

Run a playbook, startup.yml:
```
---
- hosts: Windows

  tasks:
  - name: start_platform
    win_command: run.bat
```
With the command: ```ansible-playbook startup.yml```

run.bat (notepad is just for example, but ansible hangs with this example script anyways).
```
@echo off
start /b notepad
echo hello
```

##### EXPECTED RESULTS

Ansible starts notepad (or any other process) in the background, runs remaining statements in script and exits, reporting success/failure.

##### ACTUAL RESULTS

```
[user@server ansible]$ ansible-playbook startup.yml 
 ________________
< PLAY [windows] >
 ----------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 ________________________
< TASK [Gathering Facts] >
 ------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [192.168.1.239]
 _______________________
< TASK [start_platform] >
 -----------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

```
And it hangs there. It doesn't finish running the script, doesn't return (I waited 10 minutes). When I run run.bat directly on the remote machine things are fine. I get the output "hello". Apologies if I forgot something important, I'll be here to add more information on request.

**Comment by jhawkesworth** [comment]
Sorry, this is not going to work - as mentioned in the documentation for win_shell here: https://docs.ansible.com/ansible/win_shell_module.html

"WinRM will not return from a command execution until all child processes created have exited. Thus, it is not possible to use win_shell to spawn long-running child or background processes. Consider creating a Windows service for managing background processes."

The same thing will be true for win_command as it operates over WinRM.

The win_nssm module is useful for wrapping up programs and running them as windows services.

**Comment by Aroweeri** [comment]
Thanks for pointing me in the right direction.
