### ISSUE TITLE
ec2_elb_facts not loading AWS config after 'aws configure'

### ISSUE THREAD

**Issue by kerber** [ansible/ansible#25000]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

module

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = ./ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.6.9 (unknown, Sep  1 2016, 23:34:36) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### CONFIGURATION
- Base instance
- Ansible 2.3.0 
- AWS Configured via 'aws configure'

##### OS / ENVIRONMENT

Amazon Linux

##### SUMMARY

It would appear that the ec2_elb_facts module is not properly pulling AWS credentials from the ~./aws/ directory. I've confirmed that the configuration is correct by using the aws command line tool after setup.

##### STEPS TO REPRODUCE
1. Start new EC2 instance with Amazon Linux.
2. Install ansible 2.3.0 via `sudo yum install ansible --enablerepo epel`
3. Set up Amazon config/credentials via `aws configure`
4. Attempt to run the ec2_elb_facts module via `ansible -m ec2_elb_facts localhost -vvvv`

##### EXPECTED RESULTS

Successful result, returning the ELB facts
##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "ec2_url": null,
            "names": [],
            "profile": null,
            "region": null,
            "security_token": null,
            "validate_certs": true
        }
    },
    "msg": "region must be specified"
}
```

**Comment by s-hertel** [comment]
There can be many profiles specified in your credentials file so you'll need to either export your AWS credentials (i.e. `export AWS_DEFAULT_PROFILE=yourprofile` on the command line) or specify `profile: yourprofile` in the task so ansible knows which credentials to find/utilize. You can also export access keys/secret keys/sts tokens or specify them in your task as well. Let me know if that fixes the problem :)

**Comment by kerber** [comment]
The problem persists with the `profile` task option.

After some more testing and research, I think the problem is that the default library, boto2, doesn't understand the output of the `aws configure` command. According to the [doc](http://boto.readthedocs.io/en/latest/boto_config_tut.html#details), boto2 doesn't look at ~/.aws/config, which is where `aws configure` dumps out the region setting. The current library, boto3, [properly understands the aws config placement](http://boto3.readthedocs.io/en/latest/guide/quickstart.html#configuration).

I think this could be fixed by requiring boto3 as a dep and enabling it by changing
[**ec2_elb_facts.py#L248**](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_elb_facts.py#L248)
`aws_connect_params = get_aws_connection_info(module)`
to
`aws_connect_params = get_aws_connection_info(module, true)`
The library handling the config loading, ansible.module_utils, supports boto3 and can be told to use it by the above change. It looks like it even prints out a clear error message if boto3 needs to be installed.

**Comment by s-hertel** [comment]
You're right. This module shouldn't be hard to port to boto3 since there aren't a lot of calls.

**Comment by willthames** [comment]
Changing line 248 isn't sufficient, you'd have to port the whole module to boto3.

This will need someone to do this work - at some point it might get picked up as part of the overall migration towards boto3, but I wouldn't count on it happening any time soon (i.e., if you're willing to do the change, it'll happen sooner)

**Comment by Akasurde** [comment]
@s-hertel Can we close this issue since #27435 is merged ? Thanks.

**Comment by sivel** [comment]
Closing per above
