### ISSUE TITLE
Gathering facts hangs when an NFS mount is inaccessible

### ISSUE THREAD

**Issue by rcgoodfellow** [ansible/ansible#25046]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
[facts.py](https://github.com/ansible/ansible/blob/85c7a7b844bf429fc9cc0ffce5dd9bf05ed47b5a/lib/ansible/module_utils/facts.py)

##### ANSIBLE VERSION
2.3.0.0

##### OS / ENVIRONMENT
debian-stretch

##### SUMMARY
[This](https://github.com/ansible/ansible/blob/85c7a7b844bf429fc9cc0ffce5dd9bf05ed47b5a/lib/ansible/module_utils/facts.py#L607) line of code hangs indefinitely when an NFS directory is mounted but not accessible (figured out through running python -m trace --trace). While in spirit [this](https://github.com/ansible/ansible/blob/85c7a7b844bf429fc9cc0ffce5dd9bf05ed47b5a/lib/ansible/module_utils/facts.py#L2114) timeout [decorator](https://github.com/ansible/ansible/blob/85c7a7b844bf429fc9cc0ffce5dd9bf05ed47b5a/lib/ansible/module_utils/facts.py#L85) seems to be intended to solve this, the problem is that the underlying linux call to `statvfs` is impervious to SIGALRM.

##### STEPS TO REPRODUCE
Mount an NFS directory on a Linux machine with the `hard` mount option set. Make that mount inaccessible (easily done by deleting the directory on the NFS server). Try to run an Ansible task on the machine.

##### EXPECTED RESULTS
Task execution does not hang.

##### ACTUAL RESULTS
Task execution hangs.

##### WORKAROUND
This issue does not seem manifest itself when the NFS directory is mounted with the `soft` option. However, `soft` mounting may not be an option in some situations. Also `hard` mounting is the default in Debian and likely others.

**Comment by bcoca** [comment]
fixed via 98d223a51b6e13f06ee24e02568fabe8657d7e47, should be out in 2.3.1 and above
