### ISSUE TITLE
runme.sh integration tests not reported as "tests" in CI

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#25042]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-test

##### ANSIBLE VERSION

```
devel
```

##### SUMMARY

`ansible-test` when using a `runme.sh` doesn't report in tests, and actually makes finding the error in integration tests difficult.

Example:  https://app.shippable.com/github/ansible/ansible/runs/23293/31/console

`Tests` is listed as `All Passed`

In this specific case, the error was indicated with:

```
2017-05-25 16:17:34 ++ ansible-playbook test_handlers.yml -i inventory.handlers -v -vvvvvv --tags scenario2 -l A
2017-05-25 16:17:34 ++ egrep -o 'RUNNING HANDLER \[test_handlers : .*?]'
2017-05-25 16:17:37 + '[' 'RUNNING HANDLER [test_handlers : set handler fact]
2017-05-25 16:17:37 RUNNING HANDLER [test_handlers : test handler]' = 'RUNNING HANDLER [test_handlers : test handler]' ']'
```

Which wasn't super explicit in the failure either, but I suppose that is a different issue.

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by mattclay** [comment]
To be more specific, the results of output from `runme.sh` scripts will not be found in the junit output reported on Shippable. However, the output from `ansible-playbook` run within those scripts will be.

It should be easy to have `ansible-test` create junit output for `runme.sh` scripts to remedy this. However, this may result in multiple test results reported for a single test role depending on what the script does.

**Comment by sivel** [comment]
@mattclay is this something we want to work on?  Otherwise I have no problem closing.

**Comment by mattclay** [comment]
@sivel Yes, this is still something I'd like to implement, although I haven't had time to think through all the implementation details yet.

**Comment by jborean93** [comment]
Closing for now as per @mattclay request. This is not a simple thing to fix.
