### ISSUE TITLE
Can't set sudo_user: as sudo_user: $var that is loaded from vars_files

### ISSUE THREAD

**Issue by iliv** [ansible/ansible#2504]
In the vein of #2032 sudo_user: can't be set as a variable loaded from vars_files.

For example in playbook.yml

```

---
- hosts: bitarena
  vars_files:
    - ../vars/general.yml
  user: $sys_user
  sudo_user: $sudo_user_db
```

Connection log

> <bitarena> ESTABLISH CONNECTION FOR USER: ansiblemgr on PORT 22 TO bitarena
> <bitarena> EXEC /bin/sh -c 'mkdir -p /tmp/ansible-1364316856.83-103086297282724 && chmod a+rx /tmp/ansible-1364316856.83-103086297282724 && echo /tmp/ansible-1364316856.83-103086297282724'
> <bitarena> REMOTE_MODULE setup 
> <bitarena> PUT /tmp/tmpA3E09G TO /tmp/ansible-1364316856.83-103086297282724/setup
> <bitarena> EXEC /bin/sh -c 'chmod a+r /tmp/ansible-1364316856.83-103086297282724/setup'
> <bitarena> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=oiokygakeauprdjzkhpyvbfztvactecp] password: " -u $sudo_user_db /bin/sh -c '"'"' /usr/bin/python /tmp/ansible-1364316856.83-103086297282724/setup; rm -rf /tmp/ansible-1364316856.83-103086297282724/ >/dev/null 2>&1'"'"''
> fatal: [bitarena] => ssh connection closed waiting for password prompt

**Comment by mpdehaan** [comment]
This should be good to go, but I need to test it to make sure.

**Comment by nigma** [comment]
Also the sudo_user $var is not resolved when the value is passed as a role param from the playbook roles section. Loading the value from role's vars/main.yml file works fine.

**Comment by mpdehaan** [comment]
sudo user can be passed in now, but there's not a variable for it that I'm aware of.
