### ISSUE TITLE
unable to load configuration from /home/work/.ansible/tmp/ansible-tmp-1495801371.42-161582421329274/archer.py\n

### ISSUE THREAD

**Issue by hearto1314** [ansible/ansible#25066]
root playbook result:{'fail': {u'control': {'_ansible_parsed': False, '_ansible_no_log': False, 'module_stderr': u'**unable to load configuration from /home/work/.ansible/tmp/ansible-tmp-1495801371.42-161582421329274/archer.py\n**', 'changed': False, 'module_stdout': u'', 'failed': True, 'rc': 0, 'invocation': {'module_name': u'archer'}, 'msg': u'MODULE FAILURE'}}, 'succ': {}}

get this error when call ansible playbook  run method in django.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
2.3.0

##### CONFIGURATION
default

##### OS / ENVIRONMENT
centos 6.3

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a developer question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible-devel on irc.freenode.net   
   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
