### ISSUE TITLE
module/file: attributes: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by gdzx** [ansible/ansible#25078]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
`file` module with the `attributes` parameter.

##### ANSIBLE VERSION

```ansible 2.3.0.0```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

- `Arch Linux 4.10.13-1-ARCH x86_64`
- `Python 2.7.13`
- `Python 3.6.1`

##### SUMMARY

The file module allows to specify extended attributes (for instance, 'C' to disable CoW), used by the `chattr` command.

Unfortunately, the exception _"cannot use a string pattern on a bytes-like object"_ is triggered at this location [module_utils/basic.py#2413](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L2413).

_As a sidenote, the documentation could be improved by adding an example with the attributes (`chattr` allows to specify "+C" or "-C" but the module calls `chattr =<attrs>` thus this is not allowed)._

##### STEPS TO REPRODUCE

`ansible-playbook -v -c local -i 'localhost,' sample.yaml`

```yaml
---
- hosts: all
  tasks:
    - file:
        path: /var/log/journal
        attr: 'C'
```

##### EXPECTED RESULTS

Replacing `if PASSWD_ARG_RE.match(arg):` by `if PASSWD_ARG_RE.match(to_text(arg)):` in [module_utils/basic.py#2413](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L2413) yields the following expected result:

```
PLAY [all] *******************************************************************************

TASK [Gathering Facts] *******************************************************************
ok: [localhost]

TASK [file] ******************************************************************************
changed: [localhost] => {"path": "/var/log/journal", "changed": true, "diff": {"before":
{"path": "/var/log/journal", "attributes": ""}, "after": {"path": "/var/log/journal",
"attributes": "C"}}, "uid": 0, "gid": 190, "owner": "root", "group": "systemd-journal",
"mode": "02755", "state": "directory", "size": 12, "invocation": {"module_args":
{"path": "/var/log/journal", "attr": "C", "attributes": "C", "recurse": false,
"force": false, "follow": false, "state": null, "original_basename": null,
"diff_peek": null, "validate": null, "src": null, "mode": null, "owner": null,
"group": null, "seuser": null, "serole": null, "selevel": null, "setype": null,
"content": null, "backup": null, "remote_src": null, "regexp": null,
"delimiter": null, "directory_mode": null, "unsafe_writes": null}}}

PLAY RECAP *******************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

##### ACTUAL RESULTS

```
PLAY [all] *******************************************************************************

TASK [Gathering Facts] *******************************************************************
ok: [localhost]

TASK [file] ******************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "details": "cannot use a string
pattern on a bytes-like object", "failed": true, "gid": 190, "group": "systemd-journal",
"mode": "02755", "msg": "chattr failed", "owner": "root", "path": "/var/log/journal",
"size": 12, "state": "directory", "uid": 0}
	to retry, use: --limit @/sample.retry

PLAY RECAP *******************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by ElijahLynn** [comment]
I know this is closed but just gonna say it took me a while how to figure out how to pass the attributes. I first tried "+i", then "----i--------e-", then finally found this thread and tried "i" and finally "ie". So, yeah, we definitely need an example.

**Comment by abadger** [comment]
A documentation pr would be welcomed.  Make sure you mark it documentation
pull retest so we get it into the correct reviewer's queue.
