### ISSUE TITLE
Script inventory broken since inventory plugins merge if script has no file extension

### ISSUE THREAD

**Issue by robinro** [ansible/ansible#25130]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

lib/ansible/plugins/inventory/script.py

##### ANSIBLE VERSION
ansible 2.4.0 (devel 6dd8a4cf78)

##### CONFIGURATION
defaults

##### OS / ENVIRONMENT
opensuse

##### SUMMARY
The new inventory plugin system breaks dynamical inventory plugins, when they don't have the correct file extension.

##### STEPS TO REPRODUCE

Have a minimal dynamical inventory, called `inv`:
```
#!/bin/bash
echo '{ "mygroup": { "hosts": [ "testhost1" ] }, "_meta": { "hostvars": {} } }'
```
Run `ansible -i inv --list-hosts all`

##### EXPECTED RESULTS
With versions up to 91a72ce7da:
```
Using /etc/ansible/ansible.cfg as config file
  hosts (1):
    testhost1
```

##### ACTUAL RESULTS
Since the merge of #23001 in 8f97aef1a365cbbbb822d6d09f96af17a076b295:
```
 [WARNING]:  * Failed to parse /tmp/foo/inv with <ansible.plugins.inventory.script.InventoryModule object at 0x7f6c286de850> inventory plugin: string indices must be integers

 [WARNING]:  * Failed to parse /tmp/foo/inv with <ansible.plugins.inventory.ini.InventoryModule object at 0x7f6c286de810> inventory plugin: /tmp/foo/inv:2: Expected key=value
host variable assignment, got: { "mygroup": { "hosts": [ "testhost1" ] }, "_meta": { "hostvars": {} } }

 [WARNING]: Unable to parse /tmp/foo/inv as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available

 [WARNING]: No hosts matched, nothing to do

  hosts (0):
```

There is a workaround: Rename the inventory script from `inv` to `inv.sh`.

**Comment by robinro** [comment]
To me it sounds like the extension is checked and an exception raised if there is no extension, but I couldn't find the corresponding line in the code.

@bcoca Can you have look?

**Comment by bcoca** [comment]
so i fixed the error message to not be a 'object class dump',

now fixing the "string indices must be integers"
