### ISSUE TITLE
win_updates.ps1 always uses default arguments

### ISSUE THREAD

**Issue by hughobrien** [ansible/ansible#25156]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
Ansible 2.3.0.0
Python 2.7.12
```

##### CONFIGURATION

Standard configuration
##### OS / ENVIRONMENT

N/A
##### SUMMARY

win_updates.ps1 script does not correctly parse the `category_names` string. Contents are silently ignored and default values used instead.

##### STEPS TO REPRODUCE

Method 1: Attempt to use win_updates.ps1 to install any update type other than the default values.
Method 2: Modify win_updates.ps1 line 107 replacing the param `$criteria` with an empty string. Observe found updates that should have been present with the supplied category types

##### EXPECTED RESULTS

win_updates should parse the boundparms / category_names correctly

##### ACTUAL RESULTS

Default values are used.

```

```

##### NOTE
I believe this also extends to the ` state ` variable, which defaults to ` installed ` this means the module will perform changes when it is not expected do. I have not confirmed this as thoroughly as above.

**Comment by hughobrien** [comment]
Reproducing method 3: 

1. Specify DefinitionUpdates as a target category name (this is not in the default set).
2. Run in searched mode. Observe no available updates.
3. Override $criteria on line 107 with the string you would expect it to generate to filter for DefinitionUpdates e.g.
```
"(IsInstalled = 0 AND CategoryIDs contains 'E0789628-CE08-4437-BE74-2495B842F43B')".
```
4. Re run. Observe relevant updates displayed that were not displayed before.

**Comment by bcoca** [comment]
cc @nitzmahone
