### ISSUE TITLE
creates= on command/shell tasks shows 'skipped' not 'ok'

### ISSUE THREAD

**Issue by skvidal** [ansible/ansible#2518]
When running a shell or command task with creates=

if the file creates points to exists then the task is shown as 'skipped' in the ansible-playbook output.

Since the point of creates= is to create idempotence for shell/command tasks it should be reported as 'ok' and 'unchanged' not as 'skipped' to be consistent with the other idempotent tasks.

thanks!

**Comment by mpdehaan** [comment]
Should be changeable in the command module by not putting skipped in the dict and just returning something like dict(msg="not running command since %s exists" % whatever_variable)

and doing the same for removes.

**Comment by mpdehaan** [comment]
fixed per above, so closing
