### ISSUE TITLE
Ansible cannot map the network drive on the Windows 10

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#25196]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```
ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT
Ansible running on: Ubuntu 16.04.2 x64
Ansible managing: Microsoft Windows 10 Enterprise ;OS Version is 10.0.10240 N/A Build 10240

##### SUMMARY
net use command does not work.

##### STEPS TO REPRODUCE
playbook:
```
- hosts: windows

  roles:
     - windows_common
```
role:
```
  - name: map drive
    win_command: 'net use z: \\path\to\network\share password /user:domain\user'
```
group_vars/windows.yml
```
ansible_user: Administrator
ansible_password: password
ansible_port: 5986
ansible_connection: winrm
# The following is necessary for Python 2.7.9+ (or any older Python that has backported SSLContext, eg, Python 2.7.5 on RHEL7) when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore
```
run "ansible-playbook /path/to/play/config.yml" and got error:
```
TASK [windows_common : map drive] **********************************************
fatal: [Host IP]: FAILED! => {"changed": true, "cmd": "net use z: \\\\path\\to\\network\\share password /user:domain\\user", "delta": "0:00:04.839104", "end": "2017-05-31 09:54:25.297533", "failed": true, "rc": 2, "start": "2017-05-31 09:54:20.458428", "stderr": "System error 1312 has occurred.\r\n\r\nA specified logon session does not exist. It may already have been terminated.\r\n\r\n", "stderr_lines": ["System error 1312 has occurred.", "", "A specified logon session does not exist. It may already have been terminated.", ""], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/etc/ansible/playbooks/win_common/config.retry
```

```yaml

```

##### EXPECTED RESULTS
I expect that network share "\\path\to\network\share\" will be mounted as z:\ drive.

##### ACTUAL RESULTS

I got error:
"System error 1312 has occurred. A specified logon session does not exist. It may already have been terminated."
```
TASK [windows_common : map drive] **********************************************
fatal: [host IP]: FAILED! => {"changed": true, "cmd": "net use z: \\\\path\\to\\network\\share password /user:domain\\user", "delta": "0:00:04.839104", "end": "2017-05-31 09:54:25.297533", "failed": true, "rc": 2, "start": "2017-05-31 09:54:20.458428", "stderr": "System error 1312 has occurred.\r\n\r\nA specified logon session does not exist. It may already have been terminated.\r\n\r\n", "stderr_lines": ["System error 1312 has occurred.", "", "A specified logon session does not exist. It may already have been terminated.", ""], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/etc/ansible/playbooks/win_common/config.retry
```

**Comment by jhawkesworth** [comment]
Looks to me like you have hit the so-called 'second hop' issue where windows disallows access to machine.  There are ways around this but you will need to use an authentication scheme that support credential delegation for this to work, as mentioned here: 
http://docs.ansible.com/ansible/intro_windows.html#credential-delegation

This means you will either need to use kerberos (domain account) or credssp.

This stuff could be better documented but there is more information available here https://groups.google.com/forum/#!topic/ansible-project/vEl-mrvFkrY

http://www.absolutejam.co.uk/blog/ansible-windows-credssp/ 

Hope this helps.

**Comment by ghost** [comment]
I have updated the issue.  I got another error related to credentials. Will try your advice.

**Comment by nitzmahone** [comment]
We've got a mapped drive module on the roadmap for 2.4, though if you're just trying to get at a shared drive for ephemeral use within your playbooks (not configure a permanent mapped drive), you'll want to look into Kerberos + delegation, CredSSP or `become` to solve the multi-hop problem. Regardless, these are known limitations when working under WinRM, so I'm going to close this as "by design".
