### ISSUE TITLE
Duplicate role skipped in playbook

### ISSUE THREAD

**Issue by biolds** [ansible/ansible#25194]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ansible-playbook

##### ANSIBLE VERSION

```
ansible 2.2.2.0
```

##### OS / ENVIRONMENT

Debian Jessie

##### SUMMARY

Duplicate role in a playbook is played only once, this changes behaviour compared to ansible-playbook 2.2.1.0

##### STEPS TO REPRODUCE

```yaml
- hosts: my_hosts
  roles:
    - { role: a }
    - { role: a }
```

Run:
```
ansible-playbook -i hosts playbook.yaml
```

##### EXPECTED RESULTS
with 2.2.1.0:
```
PLAY [my_hosts] ****************************************************************

TASK [setup] *******************************************************************
ok: [my_host]

TASK [a : debug] ***************************************************************
ok: [my_host] => {
    "msg": "test a"
}

TASK [a : debug] ***************************************************************
ok: [my_host] => {
    "msg": "test a"
}

PLAY RECAP *********************************************************************
my_host            : ok=3    changed=0    unreachable=0    failed=0
```

##### ACTUAL RESULTS
with 2.2.2.0:

```
PLAY [my_hosts] ****************************************************************

TASK [setup] *******************************************************************
ok: [my_host]

TASK [a : debug] ***************************************************************
ok: [my_host] => {
    "msg": "test a"
}

PLAY RECAP *********************************************************************
my_host            : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by biolds** [comment]
Behaviour is still wrong with ansible 2.3.0.0

**Comment by nitzmahone** [comment]
Do you have `allow_duplicates` set in your role's metadata? If not, the bug is likely in 2.2.1, not the new stuff (default behavior is to only allow one execution of the role).

**Comment by biolds** [comment]
No, but indeed allow_duplicates let's run it twice.
I'm not sure when the change was introduced, but i can tell the default behavior was to play them twice on version < 2.0, it's still the case in 2.2.1, but have not tested other versions in-between.
Still, the doc mentions allow_duplicates only for role dependencies (http://docs.ansible.com/ansible/playbooks_roles.html#role-dependencies)...

**Comment by biolds** [comment]
Actually if it's the new behavior, the wrong part of the documentation is there:
http://docs.ansible.com/ansible/playbooks_roles.html#roles
"Roles are just automation around ‘include’ directives as described above, and really don’t contain much additional magic beyond some improvements to search path handling for referenced files."

**Comment by bcoca** [comment]
closing as per above
