### ISSUE TITLE
S3 module should have a download option

### ISSUE THREAD

**Issue by lwade** [ansible/ansible#2519]
The s3 module should really have an option to simply download key contents to the local filesystem.  This would be useful for uploading to S3 and then later downloading in another play/playbook natively using the module.

**Comment by lwade** [comment]
@mpdehaan, could you make this a feature request plz.  This is a place for discussion. cc'ing @pas256

**Comment by lwade** [comment]
Maybe make "state" a mutex with a "dest" parameter.  If "dest" is defined, then see if the bucket and key exist and if they do, download the key contents to the destination file.  If they don't exist, just error back to the user.

Or should the local presence of the file be inside the whole notion of state?

**Comment by pas256** [comment]
I would like the S3 module to support the following modes of operation
1. GET object and store on local machine
2. GET object and store on remote machine (where the module is running)
3. PUT object from local machine to S3
4. PUT object from remote machine to S3

Perhaps for 1 and 3, we can use `local_action`? Thoughts?

Right now, the S3 module has the following params
- bucket
- expiry
- path
- state

I propose adding `src` for PUT, and `dest` for GET.

Please add comments here before we start coding this :)

**Comment by pas256** [comment]
Examples:

```
- name: GET object from S3
  s3: bucket=mybucket path=dir/obj.txt dest=/tmp/obj.txt

- name: GET and store on local machine
  local_action: s3 bucket=mybucket path=dir/obj.txt dest=/home/pas/obj.txt

- name: PUT object into S3
  s3: bucket=mybucket path=dir/obj.txt src=templates/fancy-file.j2

- name: PUT object into S3 from local machine
  local_action: s3 bucket=mybucket path=dir/obj.txt src=/home/pas/obj.txt
```

I think in these examples, `state=present` is the default value, so is not explicitly needed.

Going further to deleting an objecting an object

```
- name: Delete object from S3
  s3: bucket=mybucket path=dir/obj.txt state=absent
```

and going further still, the GET options could support everything that `file` does (e.g. owner, group, mode). I think the module redesign done a few months ago makes this easy, but I haven't done it.

**Comment by lwade** [comment]
This was kinda the dilemma I ran across.  To me, this example is confusing:

`- name: GET object from S3
  s3: bucket=mybucket path=dir/obj.txt dest=/tmp/obj.txt`

... since its a GET or download operation and the path is the full path to a file locally which you want to get from remote S3.  Thus both of the arguments are locations on the local machine.

To me it makes more sense to do something like:

`-name: GET object from S3
s3: bucket=mybucket object=bla dest=/tmp/bla.txt`

then a put would be (with src replacing file):

`-name: PUT object into S3
s3: bucket=mybucket src=/my/obj.txt state=present`

Removing, much like currently:

`-name: Delete from S3
s3: bucket=mybucket src=/my/obj.txt state=absent`

Maybe we do away with src and file completely and just have "object".  Having just an "object" parameter would do away with confusion I think and we could check in the code to see if its a local file or just a key name.  If there is no state, then we can assume its a GET and just taking the object name to pull from the bucket.  Then we use dest parameter to define that the action is a GET operation.

Thoughts?

I'm mainly focused on trying to make it easy to understand here.

**Comment by pas256** [comment]
I think that makes sense... so remove `path`, and only use the combination of `bucket` and `object` for S3 regardless of whether it is GET, PUT, DELETE, URL or other.

So then, `src` and `dest` are always local to the module, and `src` is used for PUT, and `dest` is for GET.

To maintain backwards compatibility with the S3 module that is out now, we can make `path` an alias for `object` for the first release.

So, updating the examples:

```
- name: GET object from S3
  s3: bucket=mybucket object=dir/obj.txt dest=/tmp/obj.txt

- name: PUT object into S3
  s3: bucket=mybucket object=dir/obj.txt src=files/file.txt

- name: Delete object from S3
  s3: bucket=mybucket object=dir/obj.txt state=absent

- name: Get URL of object for downloading
  s3: bucket=mybucket object=dir/obj.txt expiry=300
```

Make sense?

**Comment by mpdehaan** [comment]
Seems like this would be a good discussion for the mailing list.

Having an open ticket here is not going to get this implemented, even if it is a good idea.

Much better to submit a pull request to do it, and if we want to have a discussion, the ML has a much wider audience.

**Comment by premctl** [comment]
how can I get more than one object from s3 ?
