### ISSUE TITLE
When condition not evaluated correctly when using Jinja2 default filter

### ISSUE THREAD

**Issue by pfink** [ansible/ansible#25217]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core / playbook

##### ANSIBLE VERSION

```
2.3.1.0
```

##### CONFIGURATION

```
task_includes_static = True
handler_includes_static = True
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When I use the Jinja2 default filter setting a when expression to `false` by default and then explicetly set the variable used within the expression via CLI to false, expression is evaluated to true (even if it should be false).

##### STEPS TO REPRODUCE
Prepare a test role with some debug message output. Then, execute the following playbook:

```yaml
- hosts: localhost
  pre_tasks:
      -  debug: var="(testflag | default(false))"
  roles:
    - { role: testrole, when: "(testflag | default(false))" }
```

##### EXPECTED RESULTS
`ansible-playbook test.yml` -> no debug output from testrole (role not executed)
`ansible-playbook test.yml -e testflag=false` -> no debug output from testrole (role not executed)
`ansible-playbook test.yml -e testflag=true` -> debug output from testrole (role is executed)

##### ACTUAL RESULTS

<span style="color:green">`ansible-playbook test.yml` -> no debug output from testrole (role not executed)</span>
<span style="color: red">**`ansible-playbook test.yml -e testflag=false` -> debug output from testrole (role is executed)**</span>
<span style="color:green">`ansible-playbook test.yml -e testflag=true` -> debug output from testrole (role is executed)</span>

The following result output is from the failing test case (the one which is bold):
```
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

Loading callback plugin skippy of type stdout, v2.0 from /opt/ansible/lib/ansible/plugins/callback/__init__.pyc
Loading callback plugin profile_tasks of type aggregate, v2.0 from /opt/ansible/lib/ansible/plugins/callback/__init__.pyc

PLAYBOOK: mytest.dev.yml *******************************************************************************************************************************************************
1 plays in mytest.dev.yml

PLAY [localhost] ***************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************
Wednesday 31 May 2017  16:06:50 +0200 (0:00:00.101)       0:00:00.101 ********* 
Using module file /opt/ansible/lib/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: pfink
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
ok: [localhost]

TASK [debug] *******************************************************************************************************************************************************************
task path: /home/pfink/ansible-workspace/dabag-ansible-ru/mytest.dev.yml:3
Wednesday 31 May 2017  16:06:51 +0200 (0:00:00.695)       0:00:00.796 ********* 
ok: [localhost] => {
    "(reset_db | default(false))": "false"
}
META: ran handlers

TASK [testrole : debug] ********************************************************************************************************************************************************
task path: /home/pfink/ansible-workspace/dabag-ansible-ru/roles/testrole/tasks/main.yml:1
Wednesday 31 May 2017  16:06:51 +0200 (0:00:00.030)       0:00:00.827 ********* 
ok: [localhost] => {
    "msg": "hooooooooooooraaaayyyyyy!!!!!!"
}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   

Wednesday 31 May 2017  16:06:51 +0200 (0:00:00.036)       0:00:00.863 ********* 
=============================================================================== 
Gathering Facts --------------------------------------------------------- 0.70s
 ------------------------------------------------------------------------------
testrole : debug -------------------------------------------------------- 0.04s
/home/pfink/ansible-workspace/dabag-ansible-ru/roles/testrole/tasks/main.yml:1 
debug ------------------------------------------------------------------- 0.03s
/home/pfink/ansible-workspace/dabag-ansible-ru/mytest.dev.yml:3 ---------------
```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case your issue is that 'false' is not False, to be safe and get 'proper typing' use `|bool`:
```when: (testflag | default(False))```
or to be safe:
```when: (testflag | default(False))|bool```
another way:
```when: testflag is defined and testflag|bool```

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
