### ISSUE TITLE
group_vars host overwritten with multiple inventories

### ISSUE THREAD

**Issue by rvgate** [ansible/ansible#25247]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
inventory

##### ANSIBLE VERSION
devel@9d8aa43
2.3.0.0

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
Ubuntu 16.04.2 LTS
Python 2.7.12

##### SUMMARY
`ansible -i inventory/t1 -m shell -a "echo {{ GROUP_VAR_ALL }}" all`
GROUP_VAR_ALL has the correct value.

`ansible -i inventory/t1 -i inventory/t2 -m shell -a "echo {{ GROUP_VAR_ALL }}" all`
GROUP_VAR_ALL defined in t1 gets overwritten by the value defined in t2

`ansible -i inventory -m shell -a "echo {{ GROUP_VAR_ALL }}" all`
GROUP_VAR_ALL is undefined (expected here, but would be awesome if this works to)

##### STEPS TO REPRODUCE
Create the alternative layout described here: http://docs.ansible.com/ansible/playbooks_best_practices.html#alternative-directory-layout

For each inventory, create a group_var/all variable with a different value.

Try to run a playbook or ad-hoc command and give multiple inventories

`ansible -i inventory/t1 -i inventory/t2 -m shell -a "echo {{ GROUP_VAR_ALL }}" all`

##### EXPECTED RESULTS
Have the correct GROUP_VAR_ALL assigned for the hosts

##### ACTUAL RESULTS
GROUP_VAR_ALL  gets overwritten by the last given inventory

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

You are not using multiple inventories, just the last one passed, to use multiple inventory sources put them in a directory and use `-i /directory`.  That said, it will still not give you the result you are looking for as Ansible always merges the sources into THE single inventory.

FYI, in 2.4 (current devel) we now allow using multiple -i in the command line, but it still merges them into a single inventory.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by rvgate** [comment]
> You are not using multiple inventories, just the last one passed,

When given multiple inventories using for example: `-i inventory/t1 -i inventory/t2`, it will add all the hosts from both given inventories, even the correct host_vars given in individual inventories, but the group_vars (when given simular names) they get overwritten by the last one.

Edit: for example:
`ansible tomcat -i inventory/t1 -i inventory/t3 --list-hosts` = hosts (12)
`ansible tomcat -i inventory/t1 --list-hosts` = hosts (6)
