### ISSUE TITLE
passwordstore lookup uses pwgen utility, but this isn't mentioned anywhere

### ISSUE THREAD

**Issue by 3onyc** [ansible/ansible#25256]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
passwordstore lookup

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/.../ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb 11 2017, 12:22:40) [GCC 6.3.1 20170109]
```

##### STEPS TO REPRODUCE
1. Run passwordstore lookup with `create=true`
2. OSError: File Not Found

##### EXPECTED RESULTS
Clearly error when `pwgen` isn't installed, or any other appropriate solution

##### ACTUAL RESULTS
```
AnsibleError: {{ lookup('passwordstore', inventory_hostname ~ '/passphrase create=true length=64') }}: An unhandled exception occurred while running the loo$up plugin 'passwordstore'. Error was a <type 'exceptions.OSError'>, original message: [Errno 2] No such file or directory
```

---

The `password` lookup uses a built-in password generation function, yet passwordstore [relies on the `pwgen` utility](https://github.com/ansible/ansible/blob/v2.3.0.0-1/lib/ansible/plugins/lookup/passwordstore.py#L120) which isn't necessarily installed by default.

It should either throw a clearer error when it's missing or rely on a built-in password generation function.

I'll submit a pull request when we've decided on a solution.

**Comment by robinro** [comment]
pass provides a `generate` command. I'd recommend to adapt to code and use that command instead.

**Comment by nitzmahone** [comment]
+1 to self-contained/builtin solution if reasonable on supported platforms (think OSX, FreeBSD, etc), otherwise, better error messaging and docs would be a good thing. :)

**Comment by 3onyc** [comment]
The `pass` command line utility also has a built-in generate function (see `generate` on the [man page](https://git.zx2c4.com/password-store/about/)), this would work as a replacement for `pwgen`.

Alternatively, where would I move `password.py:_generate_password()` to as to not duplicate it in `passwordstore.py`?

Finally, how would I install additional dependencies when running tests on shippable as gnupg2 is required for the integration tests to work, and that seems to be missing on OSX
