### ISSUE TITLE
allow sudo: True/False to be set via extra vars

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#2526]
it appears we are not running the sudo variable through the template engine per a mailing list post, and we should, so that behavior can be passed in via -e like everything else.

**Comment by akvadrako** [comment]
Hi. We would like to be able to set use_sudo on a per-host basis in host files. Would this improvement also make that possible?

**Comment by mpdehaan** [comment]
duplicate of #2504 more or less, will fix together

**Comment by jimus2** [comment]
Hi.

Is this issue fixed?

I'm trying on ansible 1.5, but I'm not able to set sudo through host_vars variables

**Comment by Nosmoht** [comment]
Hi,

more than one year after the last post. I'm trying to use "sudo: '{{ myvar }}'" with Ansible 1.8.4 but it still fails.

Will there be a solution ?

**Comment by chandru9279** [comment]
Hi any workarounds for this?

I have 3 environments, two with sudo, and one without sudo perms.

Please halp!
