### ISSUE TITLE
S3 awareness if local and remote file are equivalent and force overwrite

### ISSUE THREAD

**Issue by magnusart** [ansible/ansible#2529]
I would love to see A) a comparison of the remote and the local file to see if they have the equivalent content and B) the option to force overwriting a remote/local file if already exists.

One way of solving A) above would be to have the S3 module additionally upload a file with the same name but added extension ".md5", that contains the md5 checksum for the specified file.

This together with being able to download a file from S3 (Issue #2519) would enable me to easily publish artifacts of my application and then later deploy/install them on a EC2 instance.

Not much of a python programmer, but I'll help where I can if needed.

**Comment by pas256** [comment]
S3 itself stores the MD5 of every object, so that can be queried directly without an extra file.

**Comment by mpdehaan** [comment]
I'm not really taking feature requests for the S3 module in the github tracker.  Perhaps you should bring this up on the mailing list.

@lwade or some others may be interested
