### ISSUE TITLE
Not sure about .ssh/config

### ISSUE THREAD

**Issue by ottuzzi** [ansible/ansible#253]
Hi,

   I'm not a git expert so I'm not sure I'm testing the .ssh/config patch.
Here are my steps on a ansible git clone:
    $ git branch --track devel origin/devel
    $ git checkout devel
    $ git pull
    $ make

Am I right?
Then I have the following .ssh/config
    host vps
        user test
        hostname vps.brucalipto.org
        port 8443
        proxycommand socat - PROXY:127.0.0.1:%h:%p,proxyport=3128
And if I run
    $ ssh vps
from commandline everything is working but if I run
    $ ansible vps -a "/bin/echo hello" --ask-pass -D
    SSH password:
    vps | FAILED => FAILED: [Errno 8] hostname nor servname provided, or not known

What am I missing?

Many thanks for your work
Bye
Piero

**Comment by mpdehaan** [comment]
questions should be asked to the mailing list, there are no support tickets.
