### ISSUE TITLE
INI inventory plugin don't fail to parse YAML formatted files

### ISSUE THREAD

**Issue by pilou-** [ansible/ansible#25321]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Inventory plugin

##### ANSIBLE VERSION
```
ansible --version
ansible 2.4.0 (devel 6ba040591c) last updated 2017/06/02 23:13:54 (GMT +200)
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### SUMMARY
In some case, ini plugin is able to parse Yaml formatted inventory without any error, resulting in a wrong list of hosts.

##### STEPS TO REPRODUCE
Inventory based on sample contained in [code](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/yaml.py#L35):
```
$ cat /tmp/test.yaml
all: # keys must be unique, i.e. only one 'hosts' per group
    hosts:
        test1:
        test2:
    vars:
    children:
        other_group:
            children:
                group_x:
                    hosts:
                        test5
            vars:
            hosts:
                test4:
        last_group:
            hosts:
                test1
            vars:
```

```
$ ansible all --list-hosts -i /tmp/coin.yml 
  hosts (12):
    all:
    hosts:
    test1:
    test2:
    vars:
    children:
    other_group:
    group_x:
    test5
    test4:
    last_group:
    test1
```

```
$ ANSIBLE_DEBUG=y ansible localhost -m setup -i /tmp/test.yaml |grep 'Attempting to use plugin'
 22312 1496442935.87788: Attempting to use plugin host_list
 22312 1496442935.87794: Attempting to use plugin script
 22312 1496442935.87806: Attempting to use plugin ini
```

##### EXPECTED RESULTS
Yaml plugin should be used in order to read/parse yaml inventory.

**Comment by bcoca** [comment]
As workaround you can change `inventory_enabled` in ansible.cfg to either control the order (put YAML before ini) or just remove ini from the list
```ini
inventory_enabled = host_list, yaml, ini, script
```

**Comment by pilou-** [comment]
Should not we check extension of INI formatted inventories (`.cfg`/`.ini`/no extension would be accepted) in `lib/ansible/plugins/inventory/ini.py:verify_file` method ?

**Comment by bcoca** [comment]
@pilou no, In previous versions .ini files ignored when traversing directories, as they were normally config files for dynamic inventory scripts, so that is not a restriction that is backwards compatible.

**Comment by bcoca** [comment]
I will look into making this more configurable in the future, but it might depend on `ansible-config` feature getting done.
