### ISSUE TITLE
handler is unfindable when handler name refers to a dict which have a value referring to 'inventory_dir'

### ISSUE THREAD

**Issue by pilou-** [ansible/ansible#25334]
##### ISSUE TYPE
 - Bug Report
 
##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible-playbook 2.4.0 (devel bc9dbf38b0) last updated 2017/06/03 23:05:26 (GMT +200)
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### SUMMARY
Since 8f97aef1a365cbbbb822d6d09f96af17a076b295 (inventory plugins), the following playbook fails:

```yaml
---
- hosts: localhost
  vars:
    testdict:
      name: 'main'
      path: '{{ inventory_dir }}/test'
  tasks:
    - debug:
        msg: '{{ inventory_dir }}'
    - debug:
        msg: '{{ inventory_dir }}'
      changed_when: true
      notify: 'testhandler-{{ testdict.name }}'
  handlers:
    - name: 'testhandler-{{ testdict.name }}'
      debug:
        msg: 'handler called ({{ testdict.name }})'
```

##### STEPS TO REPRODUCE
Using the playbook above, the following command fails:
```
$ ansible-playbook -i hosts -l localhost test.yml
```

The inventory contains only one line:
```
$ cat /tmp/hosts
localhost
```

The output is:
```
PLAY [localhost] ***

TASK [Gathering Facts] ***
ok: [localhost]

TASK [debug]  ***
ok: [localhost] => {
    "failed": false, 
    "msg": "/tmp"
}

TASK [debug] ***
ERROR! The requested handler 'testhandler-main' was not found in either the main handlers list nor in the listening handlers list`
```

Note that the error doesn't occur if `testdict` is replaced with two simple variables (`name: 'main'` and `path: '{{ inventory_dir }}/test'`).

##### EXPECTED RESULTS
The handler should be called and the playbook should not fail:

```
$ ansible-playbook -i /tmp/hosts -l localhost /tmp/test.yml 

PLAY [localhost] ********************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************
ok: [localhost]

TASK [debug] ************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "/tmp"
}

TASK [debug] ************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "/tmp"
}

RUNNING HANDLER [testhandler-{{ testdict.name }}] ***********************************************************************************************************
ok: [localhost] => {
    "msg": "handler called (main)"
}

PLAY RECAP **************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0   
```

**Comment by mscherer** [comment]
So testing a few stuff:
- using -i 'localhost,' give the same result, we can exclude the parsing code of inventory.

Removing 'path' from testdict work. 
Using a undefined variable invetory (spelling mistake) give a different error.

Adding debug to see testdict show that inventory dir is present before running the handler.

**Comment by mscherer** [comment]
So, I think we can simplify the case to that:
```
---
- hosts: localhost
  vars:
    testdict:
      name: 'main'
      path: '{{ foo }}'
  tasks:
   - debug:
        msg: 'Test'
     changed_when: true
     notify: 'testhandler-main'
  handlers:
    - name: 'testhandler-{{ testdict.name }}'
      debug:
        msg: 'handler called ({{ testdict.name }})'
```

If the line with 'foo' is commented, it work.

So I think there is 2 errors:
- ansible silently ignore undefined variable somewhere
- the plugin do not define the variable at the same time as before, thus letting inventory_dir to be undefined when handlers name are evaluated (while it was defined before), thus triggering the first issue

**Comment by pilou-** [comment]
@mscherer:
- source of the first [problem](https://github.com/pilou-/ansible/blob/5d17ca6ee30e7e8e6d5c6fa2a89cf569e460cd7d/lib/ansible/plugins/strategy/__init__.py#L292), not sure if this could be fixed;
- second problem should be fixed by #26569.

**Comment by pilou-** [comment]
Nothing to do: [task/handler names are not supposed to be 'host dependent'](https://github.com/ansible/ansible/pull/26569#issuecomment-314164285) and since Ansible 2.4 [we can have multiple, inventory_dir/file needs to be per host](https://github.com/ansible/ansible/commit/8f97aef1a365cbbbb822d6d09f96af17a076b295).

**Comment by bcoca** [comment]
inventory_dir could only have one value before 2.4 so we could set it 'globally'.

In 2.4 we can have multiple inventory sources so it's value can change, hence it is not available for usage in 'task names' anymore.
