### ISSUE TITLE
HP-UX hardware facts fail on virtualized ia64

### ISSUE THREAD

**Issue by mtkunkel** [ansible/ansible#25368]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

facts/hardware/hpux.py
##### ANSIBLE VERSION

```
2.4.0

also affects facts.py in 2.1, 2.2, 2.3
```

##### OS / ENVIRONMENT

Managing Virtualized HPUX ia64
##### SUMMARY

machinfo returns questionable cpu data for virtualized ia64 systems.   Causes module failure in 2.1 through 2.3.   2.4 runs and is missing all hardware facts.
##### STEPS TO REPRODUCE

```yaml
ansible all -m setup -i hp1123VM-ia64server, -u root
```

##### EXPECTED RESULTS

Should return list of hardware facts, including memtotal_mb, swaptotal_mb, firmware_version, product_serial.
##### ACTUAL RESULTS

All hardware facts are missing on 2.4.   Module failure with traceback prior in 2.1-2.3.

```
From 2.2:

| FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Warning: Permanently added 't' (RSA) to the list of known hosts.\r\nTraceback (most recent call last):\n  File \"/tmp/ansible_vA4QLB/ansible_module_setup.py\", line 134, in <module>\n    main()\n  File \"/tmp/ansible_vA4QLB/ansible_module_setup.py\", line 126, in main\n    data = get_all_facts(module)\n  File \"/tmp/ansible_vA4QLB/ansible_modlib.zip/ansible/module_utils/facts.py\", line 3518, in get_all_facts\n  File \"/tmp/ansible_vA4QLB/ansible_modlib.zip/ansible/module_utils/facts.py\", line 3461, in ansible_facts\n  File \"/tmp/ansible_vA4QLB/ansible_modlib.zip/ansible/module_utils/facts.py\", line 2002, in populate\n  File \"/tmp/ansible_vA4QLB/ansible_modlib.zip/ansible/module_utils/facts.py\", line 2015, in get_cpu_facts\nIndexError: list index out of range\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE"
}
```

**Comment by sivel** [comment]
This appears to be the same bug you reported in https://github.com/ansible/ansible/issues/25365

Any reason we can't use a single bug report?

**Comment by mtkunkel** [comment]
I will have a PR shortly to fix this issue specific to HPUX facts.   #25365 is more generic in that the setup module will no longer fail with traceback in 2.4.   Need a way to get debug info from module_utils/facts/hardware/*.py
