### ISSUE TITLE
AIX hardware facts fail on single core AIX5 series

### ISSUE THREAD

**Issue by mtkunkel** [ansible/ansible#25362]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
module_utils/facts/hardware/aix.py

##### ANSIBLE VERSION

```
2.4.0

Also affects 2.1.0, 2.2.0, 2.3.0
```

##### OS / ENVIRONMENT

Running from any supported Linux platform.   Managing AIX5 series

##### SUMMARY
AIX hardware facts fail when run on single core AIX5 (attribute smt_threads is not defined)

/usr/sbin/lsattr -El proc0 -a smt_threads
lsattr: 0514-528 The "smt_threads" attribute does not exist in the predefined
        device configuration database.

##### STEPS TO REPRODUCE

```yaml
ansible all -m setup -i aix5boxname_redacted, -u root 
```

##### EXPECTED RESULTS

Should include hardware facts such as:
        "ansible_processor": "PowerPC_POWER4",
        "ansible_processor_count": 4,
        "ansible_memfree_mb": 5126,
        "ansible_memtotal_mb": 8192,

##### ACTUAL RESULTS

No hardware facts present.  facts/hardware/aix.py failing silently.   Facts redacted due to sensitive info (internal hostnames/ip addresses).

```

```

**Comment by mtkunkel** [comment]
PR:  https://github.com/ansible/ansible/pull/25364

**Comment by alikins** [comment]
Was this ever working before? If so, what versions?

**Comment by mtkunkel** [comment]
It failed in 2.1, 2.2, 2.3.   In 2.4 it runs without failure however the facts are missing.  (hardware/aix.py likely fails but does not result in traceback due to splitting of facts.py in 2.4).

**Comment by alikins** [comment]
@pilotmattk That is what I suspected looking at the code, but was curious if I broke it somehow in the facts refactor.
