### ISSUE TITLE
Wrong ansible_os_family returned on Linux Mint

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#25391]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

module_utils

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb 11 2017, 12:22:40) [GCC 6.3.1 20170109]
```

##### OS / ENVIRONMENT

Linux Mint

##### SUMMARY
Ansible does not return the correct ansible_os_family when gathering facts on a Linux Mint host.
Linux Mint is derived from Ubuntu and ansible_os_family should therefore be set to 'Debian'.

##### STEPS TO REPRODUCE

```
ansible -m setup linux-mint-host
```

##### EXPECTED RESULTS

ansible_os_family set to 'Debian'

##### ACTUAL RESULTS

ansible_os_family set to 'Linuxmint'

```

```

**Comment by roadmapper** [comment]
@bcoca @nitzmahone If this needs to be in the 2.3.0 milestone does there need to be another PR for merging into the 2.3.0 branch? The module_utils facts Python code is structured differently in 2.3.0, so it would need to be backported. If this isn't going to be backported, perhaps the 2.4.0 milestone should be applied instead.

**Comment by apteryks** [comment]
It just got worst in 2.7.0; os_family now reads as 'ClearLinux' on Linux Mint 18.3 :-/.

**Comment by xcompass** [comment]
Same here. Showing 'ClearLinux' on CoreOS. ansible=2.7.5
