### ISSUE TITLE
Async API

### ISSUE THREAD

**Issue by jhoekx** [ansible/ansible#254]
Currently async operations in playbooks and /usr/bin/ansible are duplicating a lot of code. Using async through the API is also very ugly.

I've been thinking about this and would propose a method runAsync() on Runner that returns an object with a poll() method and does all the bookkeeping involved. Timing would be external?

Async is also not fully integrated in the callback system, this can also be fixed, along with cleaning up the files in ~/.ansible_async.

Any feedback? I could probably do this by the weekend.

**Comment by mpdehaan** [comment]
I'm ok with duplication as they may want to diverge later.  We have a sizeable backlog of things we need to impelment so I do not want to persue refactoring until more tickets are knocked out.
