### ISSUE TITLE
get_url: check mode reports changes with force enabled

### ISSUE THREAD

**Issue by twouters** [ansible/ansible#25418]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

check_url

##### ANSIBLE VERSION

```
ansible 2.4.0 (pr24732 0dd35a2048) last updated 2017/05/19 11:22:31 (GMT +200)
```

##### CONFIGURATION

No special configuration needed.

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Changes are reported when running tasks in check mode (--check/-C) even though there are no expected changes.

##### STEPS TO REPRODUCE

```
ansible -m get_url -a "dest=/tmp/example url=https://www.kernel.org/pub/linux/kernel/README force=yes" localhost
ansible -C -m get_url -a "dest=/tmp/example url=https://www.kernel.org/pub/linux/kernel/README force=yes" localhost
```

(Note: to validate the behaviour on 2.3, the second command would be skipped, so check mode should be removed there. This results in changed:false since both checksums match)

##### EXPECTED RESULTS

I'm not entirely sure what to expect, but the module should not return changed if there are no changes.  
I realize that using force=yes makes this task idempotent, since there's no way to predict that the file on the remote end (`url`) has been changed or not.
It might not be possible to perform checksum validations when using a HEAD request, so stating that the file has changed without knowing it did feels weird.

##### ACTUAL RESULTS

```
ansible -m get_url -a "dest=/tmp/example url=https://www.kernel.org/pub/linux/kernel/README" localhost
localhost | SUCCESS => {
    "changed": true, 
    "checksum_dest": null, 
    "checksum_src": "11f19a73fb8a7aa4f8582b6e137fb3b2f404b061", 
    "dest": "/tmp/example", 
    "gid": 1000, 
    "group": "group", 
    "md5sum": "9beb331d9307ecb8b561a940402d001a", 
    "mode": "0644", 
    "msg": "OK (12056 bytes)", 
    "owner": "user", 
    "size": 12056, 
    "src": "/tmp/tmpW86xYJ", 
    "state": "file", 
    "status_code": 200, 
    "uid": 1000, 
    "url": "https://www.kernel.org/pub/linux/kernel/README"
}
ansible -C -m get_url -a "dest=/tmp/example url=https://www.kernel.org/pub/linux/kernel/README force=yes" localhost
localhost | SUCCESS => {
    "changed": true, 
    "dest": "/tmp/example", 
    "gid": 1000, 
    "group": "group", 
    "mode": "0644", 
    "msg": "OK (12056 bytes)", 
    "owner": "user", 
    "size": 12056, 
    "src": "/tmp/tmpzFCw_f", 
    "state": "file", 
    "uid": 1000, 
    "url": "https://www.kernel.org/pub/linux/kernel/README"
}
```

**Comment by nitzmahone** [comment]
This is by design: check_mode is supposed to say whether a change *would* have been made- in the case of `force: true` on this module, we'll always report changed outside of check mode, so always reporting changed in check mode is consistent and correct.

**Comment by twouters** [comment]
As far as I know, `force:true` does not report changed outside of check mode, unless the local file's checksum differs from that of the remote.
My tests seem to have confirmed that.

**Comment by nitzmahone** [comment]
Sure, but how would you know that? You can always change this behavior in your own tasks with `changed_when: false`, but just like with shell/command/raw and others where we can't predict whether a change has or has not occurred, we err on the side of reporting that it has, so this is consistent...
