### ISSUE TITLE
Reimplement Python testserver.py in Powershell

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#25420]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

win_uri

##### ANSIBLE VERSION

v2.4

##### SUMMARY
In order to do proper integration tests for **win_uri** (#25373), just like the **uri** module, we need a Powershell implementation of [testserver.py](https://github.com/ansible/ansible/blob/devel/test/integration/targets/uri/files/testserver.py).

I am not very proficient in Powershell and would like someone else to write *testserver.ps1* in order to do the same tests that exist for the **uri** module with the **win_uri** module.

So the functionality we need is listed here:
https://github.com/ansible/ansible/blob/devel/test/integration/targets/uri/tasks/main.yml

And the aim for #25373 is to reorganize those tests, and make the module-name and the testserver filename a variable so we can use the same playbook for both **uri** as for **win_uri**. This may not be 100% possible because of certificate-support difference, but it will be very close.

cc: @nitzmahone @jborean93 @jhawkesworth @trondhindenes @blakfeld for the implementation :-)
cc: @gundalow @mattclay for feedback wrt. testing

needs_contributor

**Comment by dagwieers** [comment]
So the stuff I already did was:
```powershell
param (
    [int]$port = 8000,
)

$listener = New-Object Net.HttpListener
$listener.Prefixes.Add("http://+:$port/")
$listener.Start()

try {
    while ($listener.IsListening) {
        $context = $listener.GetContext()
        $Request = $context.Request
        $Response = $context.Response
        # Read $Request.url.localpath
        # Return content
        #$Response.Headers.Add("Content-Type", "text/plain")
        $buffer = [Text.Encoding]::UTF8.GetBytes($data)
        $Response.ContentLength64 = $buffer.length
        $Response.OutputStream.Write($buffer, 0, $buffer.length)

        $Response.Close()
    }
} finally {
    $listener.Stop()
    $listener.Close()
}
```
But there's a lot more to do to support different mime-types, HTTPS, and everything else the integration tests need.

**Comment by jborean93** [comment]
We might be better off running up an IIS site for this instead. You will then have access to a wide range of options around auth types and response settings from there and don't have to play around with trying to get the PS script running as a service.

**Comment by dagwieers** [comment]
@jborean93 But it would be a lot harder to reuse the existing **uri** tests using IIS infrastructure. I honestly don't know how hard it is to re-implement testserver.py, so you may as well be right. I plan to add some basic integration tests using google.com for the time being, but we do need a proper solution for testing.

So what is the path of least resistance ? :-)

**Comment by daBONDi** [comment]
My 2 Cents :-)
maybe use caddy
https://github.com/mholt/caddy

Written in go, simple binary, easy start stop

**Comment by trondhindenes** [comment]
There are Powershell-based micro web frameworks available, we shouldn't have to write this from scratch ourselves. But yeah - does it have to be Powershell? Why not reuse testserver.py?

**Comment by dagwieers** [comment]
So this ticket is a little bit outdated. The consensus was to open up the httptester docker infrastructure to be used by the (Windows) VM infrastructure. At the moment that is not possible.

It is an action-item for @mattclay in the Windows action plan and a requirement to improve the **win_uri** and **win_geturl** integration tests.
