### ISSUE TITLE
Documentation win_dsc_module is incorrectly rendering as single-character bullet points

### ISSUE THREAD

**Issue by MadelineRitchie** [ansible/ansible#25426]
http://docs.ansible.com/ansible/win_dsc_module.html

The first paragraph is split like this:

* T
* h
* e

* f
* i

etc

**Comment by jhawkesworth** [comment]
This is being worked on under https://github.com/ansible/ansible/pull/25405, so I hope you won't mind if I  close this as a duplicate.

**Comment by MadelineRitchie** [comment]
Don't mind at all. I did attempt to find an issue but I should have searched PRs as well. Thanks.
