### ISSUE TITLE
Add the ability to deep merge lists

### ISSUE THREAD

**Issue by gilesw** [ansible/ansible#25436]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

merge_hash

##### ANSIBLE VERSION
ansible 2.3.0.0

##### CONFIGURATION
see https://github.com/tdac/Ansible-HashMerge-Issue

##### OS / ENVIRONMENT
N/A

##### SUMMARY
A standard module pattern is to define a many single key: value hash configuration values, but then often a few iterable lists. The hash merge feature is often used to sensibly override some values at the group_var level how when lists are used they end up replacing the list, unexpected.

The newly added combine filter can and is used to get round this issue but this requires each module owner to add this.

##### STEPS TO REPRODUCE

see https://github.com/tdac/Ansible-HashMerge-Issue

##### EXPECTED RESULTS
see https://github.com/tdac/Ansible-HashMerge-Issue

##### ACTUAL RESULTS
see https://github.com/tdac/Ansible-HashMerge-Issue

##### FOLLOWUP

I'm proposing a optional behaviour which is available in other data merging systems like heira:-

https://docs.puppet.com/puppet/4.10/hiera_merging.html#deep

A pull request will follow..

**Comment by gilesw** [comment]
This module has been flagged to me:-

https://github.com/sailthru/ansible-oss/tree/master/tools/echelon

The logic is the same as what I've added except with deep merging within lists is included.

**Comment by s-hertel** [comment]
Fixed by #57894
