### ISSUE TITLE
Variable containing currently executed role name [feature_idea]

### ISSUE THREAD

**Issue by selivan** [ansible/ansible#25447]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ansible core

##### SUMMARY
I suppose sometimes it's useful to have a comment in config file that shows from which role it was created. If you specify the role explicitly, this comment can become obsolete in case the role is renamed. Now I use this ugly kludge to solve this:

`# Generated by ansible role: {{ role_path | regex_replace('^.*/([^/]+)$', '\\1') }}`.

It would be nice to have a special variable `ansible_role` that will contain name of currently executed role. Also it may be a good idea to make placeholder `{role}` available for `ansible_managed` variable.

**Comment by sivel** [comment]
You can also get this much more simplistically by using the `basename` filter:

```
role_path|basename
```

**Comment by selivan** [comment]
@sivel O_o that's much better, thank you. Seems that whatever you are trying to do, already there is a jinja filter to do it. `template: dest=/etc/mysql/my.cnf content="{{ 'mysql' | make_config_fast_reliable_and_secure }}"` :)

@bcoca I leave it to you whether to realize this feature or just close the issue. Probably just close. At least, it may be worth adding this to examples in documentation.

**Comment by selivan** [comment]
Ansible 2.8 got new variable `role_name`, so this issue is resolved.
