### ISSUE TITLE
AWS was not able to validate the provided access credentials

### ISSUE THREAD

**Issue by winstonsimon** [ansible/ansible#25459]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
AWS plugin

##### ANSIBLE VERSION

```
ansible 2.3.1.0
```

##### OS / ENVIRONMENT
```
AWS - Ubuntu - RHEL7
```

##### SUMMARY
I am trying to use temporary credentials to spin up our EC2 instance. Our deployment pipeline is basically Packer job  creates an AMI image and then trigger Ansible scripts to spin up new EC2 instance. With temp credentials, PACKER is able to spin up jobs in our AWS account but Ansible is failing with following error.

```
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/h3/3s8j9m9s2518cy6zmh9t5tmm0000gn/T/ansible_WEmDn1/ansible_module_ec2_vpc.py", line 759, in <module>
    main()
  File "/var/folders/h3/3s8j9m9s2518cy6zmh9t5tmm0000gn/T/ansible_WEmDn1/ansible_module_ec2_vpc.py", line 750, in main
    (vpc_dict, new_vpc_id, subnets_changed, igw_id, changed) = create_vpc(module, vpc_conn)
  File "/var/folders/h3/3s8j9m9s2518cy6zmh9t5tmm0000gn/T/ansible_WEmDn1/ansible_module_ec2_vpc.py", line 356, in create_vpc
    previous_vpc = find_vpc(module, vpc_conn, id, cidr_block)
  File "/var/folders/h3/3s8j9m9s2518cy6zmh9t5tmm0000gn/T/ansible_WEmDn1/ansible_module_ec2_vpc.py", line 212, in find_vpc
    previous_vpcs = vpc_conn.get_all_vpcs(None, {'cidr': cidr, 'state': 'available'})
  File "/usr/local/Cellar/ansible/2.3.0.0_2/libexec/lib/python2.7/site-packages/boto/vpc/__init__.py", line 110, in get_all_vpcs
    return self.get_list('DescribeVpcs', params, [('item', VPC)])
  File "/usr/local/Cellar/ansible/2.3.0.0_2/libexec/lib/python2.7/site-packages/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 401 Unauthorized
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>991d3f9b-0fea-4ce7-a398-38024a33f2ec</RequestID></Response>

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/h3/3s8j9m9s2518cy6zmh9t5tmm0000gn/T/ansible_WEmDn1/ansible_module_ec2_vpc.py\", line 759, in <module>\n    main()\n  File \"/var/folders/h3/3s8j9m9s2518cy6zmh9t5tmm0000gn/T/ansible_WEmDn1/ansible_module_ec2_vpc.py\", line 750, in main\n    (vpc_dict, new_vpc_id, subnets_changed, igw_id, changed) = create_vpc(module, vpc_conn)\n  File \"/var/folders/h3/3s8j9m9s2518cy6zmh9t5tmm0000gn/T/ansible_WEmDn1/ansible_module_ec2_vpc.py\", line 356, in create_vpc\n    previous_vpc = find_vpc(module, vpc_conn, id, cidr_block)\n  File \"/var/folders/h3/3s8j9m9s2518cy6zmh9t5tmm0000gn/T/ansible_WEmDn1/ansible_module_ec2_vpc.py\", line 212, in find_vpc\n    previous_vpcs = vpc_conn.get_all_vpcs(None, {'cidr': cidr, 'state': 'available'})\n  File \"/usr/local/Cellar/ansible/2.3.0.0_2/libexec/lib/python2.7/site-packages/boto/vpc/__init__.py\", line 110, in get_all_vpcs\n    return self.get_list('DescribeVpcs', params, [('item', VPC)])\n  File \"/usr/local/Cellar/ansible/2.3.0.0_2/libexec/lib/python2.7/site-packages/boto/connection.py\", line 1186, in get_list\n    raise self.ResponseError(response.status, response.reason, body)\nboto.exception.EC2ResponseError: EC2ResponseError: 401 Unauthorized\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>991d3f9b-0fea-4ce7-a398-38024a33f2ec</RequestID></Response>\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

 ```

If I use standard user credentials then playbook works without any issue. I have also checked the timestamp in the host and it's correct.

Policy Used:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:*"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt"
            ],
            "Resource": [
                "arn:aws:kms:us-east-1:xxxxx:key/xxxxx"
            ]
        }
    ]
}
```
```
cat ~/.aws/credentials                                                                                                                                  [default]
aws_access_key_id = xxxxxx
aws_secret_access_key = xxxxx
aws_session_token = xxxx
 ```

##### EXPECTED RESULTS
Spin up AWS EC2 Instance

##### ACTUAL RESULTS
ERROR will running the playbook.

#
With the same credentials, I am able to use aws cli and also able to get all the information

eg:
```
aws ec2 describe-vpcs                                                                                                                                   
{
    "Vpcs": [
        {
            "VpcId": "vpc-xxx", 
            "InstanceTenancy": "default", 
            "Tags": [
                {
                    "Value": "stage", 
                    "Key": "Environment"
                }, 
                {
                    "Value": "xxxx-VPC", 
                    "Key": "Name"
                }
            ], 
            "State": "available", 
            "DhcpOptionsId": "dopt-xxxx", 
            "CidrBlock": "10.0.0.0/20", 
            "IsDefault": false
        }
}
```

```
ansible-playbook ansible/deploy.yml  --extra-vars "region=us-east-1 envName=stage"
```

**Comment by nitzmahone** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by winstonsimon** [comment]
@nitzmahone 
Reponse from IIRC.

agaffney - Guest91457: I've never used IAM temp credentials, but I really doubt there's a bug in multiple places in ansible around using them, when the docs you pointed to above pretty much say that they're identical

Could you please reopen this issue?

**Comment by nitzmahone** [comment]
The most common reason for this failure is date/time issues on the control host. Regardless, we don't treat temporary credentials any differently than permanent ones (they all just get passed through to boto), so the problem most likely doesn't lie with Ansible. cc @s-hertel - if you feel like trying to validate...

**Comment by winstonsimon** [comment]
Ok.. made it working by explicitly exporting all the following variables.

```
    export AWS_ACCESS_KEY_ID=$(sed -n -e 's/aws_access_key_id=//p' < ~/.aws/credentials)
    export AWS_SECRET_ACCESS_KEY=$(sed -n -e 's/aws_secret_access_key=//p' < ~/.aws/credentials)
    export AWS_SESSION_TOKEN=$(sed -n -e 's/aws_session_token=//p' < ~/.aws/credentials)
```

**Comment by mwchristiansen** [comment]
this is still broken.  any plans to fix it?

**Comment by pracucci** [comment]
I confirm the issue. Following up @winstonsimon solution (thanks), I believe a better way is to replace `sed` with `aws` cli, so that it supports credentials files with multiple profiles:

```
export AWS_ACCESS_KEY_ID=$(aws --profile=REPLACE-ME configure get aws_access_key_id)
export AWS_SECRET_ACCESS_KEY=$(aws --profile=REPLACE-ME configure get aws_secret_access_key)
export AWS_SESSION_TOKEN=$(aws --profile=REPLACE-ME configure get aws_session_token)
```

**Comment by MrMarvin** [comment]
Funnily enough, not all AWS resources are affected. Creating an ec2 key_pair or security group works, `DescribeInstances` (in my case) or the `DescribeVpcs` call in the initial issue however seems to somehow get their AWS SDK configuration messed up. 
It appears that somewhere in that particular call-chain there's something setting/unsetting `AWS_` env vars...

ANSIBLE VERSION
```
ansible==2.7.2
boto==2.49.0
boto3==1.4.7
botocore==1.7.47
```

Example:
```yaml
# works, no issues
- name: Create keypairs
      ec2_key:
        name: "{{ keypair_name }}"
        region: "{{ item.region }}"
      with_items: "{{ molecule_yml.platforms }}"
      register: keypairs

# fails with 'AWS was not able to validate the provided access credentials'
- name: Create molecule instance(s)
      ec2:
        key_name: "{{ keypair_name }}"
        image: "{{ item.image }}"
        region: "{{ item.region }}"
        instance_type: "{{ item.instance_type }}"
        vpc_subnet_id: "{{ item.vpc_subnet_id | default(None) }}"
        group: "{{ security_group_name }}"
        instance_tags:
          instance: "{{ item.name }}"
        wait: true
        assign_public_ip: true
        exact_count: 1
        count_tag:
          instance: "{{ item.name }}"
      register: server
      with_items: "{{ molecule_yml.platforms }}"
```

In our environment we rely on the AWS SDK's multi-step credential resolution to pick up `AWS_PROFILE` and read temporary access keys from the local `~/.aws/credentials` on local dev and on IAM InstanceProfiles on prod, so we never set `AWS_ACCESS_KEY_ID` etc.

**Comment by blastik** [comment]
same issue here!
affecting 2.7.2 when using `profile = whatever` in ec2 module.
all the rest of modules seem to be right!

**Comment by MrMarvin** [comment]
So, um, not sure how to move on with this... ping @nitzmahone, @s-hertel: Thanks for taking a first look some time ago. However I do not think your initial understanding that this is a user question is correct. This issue is highly interesting and I would kindly ask you to consider reopening it.

**Here is why:**
Ansible cloud/amazon modules are inconsistent in their use of the underlying AWS library. Some are on the newer boto3, while others are still using the older boto library. `ec2` is an example of the later.

You said:
> [...] we don't treat temporary credentials any differently than permanent ones (they all just get passed through to boto)

This is not entirely correct, there is a lot of logic for supporting modules using the legacy `boto` over `boto3` for AWS in places like https://github.com/ansible/ansible/blob/e0d8d9c2bfe1ca0431d528ef55c89ee61c337cf9/lib/ansible/module_utils/ec2.py#L322-L327
This code however only triggers in cases were credentials are passed to Ansible, not in cases where an `~/.aws/credentials` file + `AWS_PROFILE` or any form of dynamic instance profiles is used.

>  so the problem most likely doesn't lie with Ansible.

Agreed. **This is an issue in diverging support for modern AWS authentication mechanisms between `boto` and `boto3`.**
For modules that use `boto`, we are hitting https://github.com/boto/boto/issues/2988. There is fix available but not yet merged in https://github.com/boto/boto/pull/3767.
As it seems right now, the boto maintainers don't prioritize support for this, so its likely this will never be integrated.
So while its true that this issue does not lie with Ansible, it has an ever-growing impact on its users. I would assume that more and more AWS users are following best-practices to not use static IAM access keys, but rely on dynamic access credentials providers. These users will sooner or later get hit by it, without a clear way to understand why its happening (e.g. some modules work, some don't). Not good.

I am unsure if Ansible should 
* i) push on removing boto and rewriting the remaining modules to use the future proof boto3,
* ii) work with the boto maintainers to get the fix merged or 
* ii) implement a work-around that somehow wraps or patches boto. The above linked `module_utils/ec2.py` already does something like that. Generally it does not seem to be advisable to try to implement the AWS access credentials logic ourselves, that's something that should be left to the SDK.

Do you think that's something Ansible can do?

**Comment by s-hertel** [comment]
@MrMarvin i) Is the solution in progress. Here's the page keeping track of modules being ported to boto3 https://github.com/ansible/community/blob/master/group-aws/boto3.md. In regard to iii), we are trying to not add more boto code. boto is no longer actively maintained, so ii) will be very unlikely to happen. I agree with you that it should be left to the SDK, although we need to maintain compatibility with what has already been done. For people using the ec2 module, there aren't plans to port it as a cleaner ec2_instance module using boto3 has been introduced.

**Comment by Vikash082** [comment]
Any update on this ? I can't create even security group. 

Error:
ClientError: An error occurred (AuthFailure) when calling the DescribeSecurityGroups operation: AWS was not able to validate the provided access credentials.

My ansible version:

    ansible 2.7.9

Is there a temp. fix ? I tried the above suggested environment variable, but it didn't resolved.
