### ISSUE TITLE
Client certificate authentication with WinRM using a .pfx file need documentation

### ISSUE THREAD

**Issue by MittchoBaroco** [ansible/ansible#25480]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME
windows certificate authentification

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```
#####CONFIGURATION
```
ansible_connection=winrm
ansible_winrm_transport=certificate
ansible_winrm_cert_pem=windows/roles/locksrv/files/locksrv_cert.pem
ansible_winrm_cert_key_pem=windows/roles/locksrv/files/locksrv_cert.pfx
ansible_winrm_server_cert_validataion=ignore
```
##### SUMMARY
we are generating our certificate from the script present on this link https://cloudbase.it/windows-without-passwords-in-openstack/ and we can't find the way to open the connection.

ansible is returning the error below
```
fatal: [xxx.xxx.xxx.xxx]: UNREACHABLE! => {"changed": false, "msg": "certificate: [('PEM routines', 'PEM_read_bio', 'no start line'), ('SSL routines', 'SSL_CTX_use_PrivateKey_file', 'PEM lib')]", "unreachable": true}
```

**@hehe2 on #16243 seems to have found a solution. would be nice to have that on the doc.**

##### EXPECTED RESULTS
open a connection with the server
##### ACTUAL RESULTS

```
Using module file /usr/local/Cellar/ansible/2.3.0.0_2/libexec/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1
<xxx.xxx.xxx.xxx> ESTABLISH WINRM CONNECTION FOR USER: None on PORT 5986 TO xxx.xxx.xxx.xxx
fatal: [xxx.xxx.xxx.xxx]: UNREACHABLE! => {
    "changed": false, 
    "msg": "certificate: [('PEM routines', 'PEM_read_bio', 'no start line'), ('SSL routines', 'SSL_CTX_use_PrivateKey_file', 'PEM lib')]", 
    "unreachable": true
}
```

**Comment by jborean93** [comment]
You cannot use `pfx` certificates with certificate auth as public cert and private need to be exported to a PEM first. The upcoming docs gives you info on how to create as well as convert a key with OpenSSL. These docs can be found here https://github.com/ansible/ansible/pull/30783.

**Comment by jborean93** [comment]
The docs above have been merged and will be online under the devel version on the next rebuild.
