### ISSUE TITLE
Refresh Inventory for AWS EC2 via Tower not working

### ISSUE THREAD

**Issue by manan00** [ansible/ansible#25523]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Ansible Tower 

##### ANSIBLE VERSION

```
2.2.2.0
```

##### SUMMARY
I am using Ansible Tower 2.4.5. I have setup dynamic inventory for AWS EC2. Through my playbook I intend to create an EC2 instance on AWS and once instance is up & running perform some configurations. Currently my playbook fails while configuration as it is not able to connect to newly created host. It fails with following error 

fatal: [ec2_host_name]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}

I can use meta: refresh_inventory however I found multiple threads saying it doesn't work with Tower. 

Any pointers/suggestions ?
##### STEPS TO REPRODUCE

```yaml
1. Setup Dynamic inventory for AWS  ( Update on launch is set )
2. Create Project, Credentials, Job templates
3. Trigger job - playbook which creates and configure an EC2 instance
```

##### ACTUAL RESULTS

EC2 instance gets created and configured successfully. 

```
fatal: [ec2_host_name]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
```

**Comment by jctanner** [comment]
@manan00 tower is not supported in this issue tracker. Please open an issue with the tower support team per https://docs.ansible.com/ansible-tower/latest/html/administration/license-support.html#support
