### ISSUE TITLE
credssp: a float is required, ssl: a float is required, plaintext: a float is required

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#25539]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

WinRM

##### ANSIBLE VERSION

v2.4

##### SUMMARY

When you accidentally configure `ansible_winrm_read_timeout_sec` as a string `90` (don't ask, these are generated), you get a confusing error message. At least $CUSTOMER was surprised ;-)

So it makes sense to do something better with this.

```
system01 | UNREACHABLE! => {
    "changed": false,
    "msg": "credssp: a float is required, ssl: a float is required, plaintext: a float is required",
    "unreachable": true
}
```

**Comment by nrwahl2** [comment]
@dagwieers Where is this param hooked in? I can't find it in any files except a doc file. Have you already made a change?

I grepped recursively through the whole Ansible directory structure... most promising thing I could find was `plugins/connections/winrm.py`.

**Comment by dagwieers** [comment]
No, I haven't looked at fixing this. I think we need a discussion here what we expect first.

**Comment by nrwahl2** [comment]
That's fair. Just trying to find where the `ansible_winrm_read_timeout_sec` is even handled in the code.
```
$ grep -Ri winrm_read_timeout_sec
docs/docsite/rst/intro_windows.rst:* ``ansible_winrm_read_timeout_sec``: Increase the WinRM read timeout if you experience read timeout errors (default: ``30``), e.g. intermittent network issues.
grep: test/integration/targets/copy/files/subdir/subdir1/invalid2: No such file or directory
grep: warning: test/integration/targets/copy/files/subdir/subdir1/circles: recursive directory loop
grep: test/integration/targets/copy/files/subdir/subdir1/ansible-test-abs-link: No such file or directory
grep: test/integration/targets/copy/files/subdir/subdir1/ansible-test-abs-link-dir: No such file or directory
grep: test/integration/targets/copy/files/subdir/subdir1/out_of_tree_circle: No such file or directory
grep: test/integration/targets/copy/files/subdir/subdir1/invalid: Too many levels of symbolic links
```

**Comment by dagwieers** [comment]
It's in pywinrm.

**Comment by jborean93** [comment]
@nrwahl2, most of the `ansible_winrm_*` are passed directly into the winrm protocol args here https://github.com/diyan/pywinrm/blob/master/winrm/protocol.py where `*` is the key in pywinrm.

**Comment by nrwahl2** [comment]
Thanks!

**Comment by nrwahl2** [comment]
Yep, I see now, in the plugin.
```
        # arg names we're going passing directly
        internal_kwarg_mask = set(['self', 'endpoint', 'transport', 'username', 'password', 'scheme', 'path', 'kinit_mode', 'kinit_cmd'])

        self._winrm_kwargs = dict(username=self._winrm_user, password=self._winrm_pass)
        argspec = inspect.getargspec(Protocol.__init__)
        supported_winrm_args = set(argspec.args)
        supported_winrm_args.update(internal_kwarg_mask)
        passed_winrm_args = set([v.replace('ansible_winrm_', '') for v in hostvars if v.startswith('ansible_winrm_')])
```

**Comment by nrwahl2** [comment]
Couldn't we just try a type conversion (at least for the timeout) in the winrm plugin? It's ultimately calling Python's `requests.Session.send` method via `winrm.transport`.Transport and expects a float if a single value is passed. (Okay, not **ultimately**... it goes down through `requests.packages.urllib3.util.timeout` for `Timeout`.)

Tests with dummy values:
With string value for `read_timeout_sec`:
```
>>> x
<winrm.transport.Transport object at 0x7fb781033750>
>>> x.__dict__
{'username': 'username', 'kerberos_hostname_override': 'kerberos', 'endpoint': 'http://endpoint', 'keytab': 'keytab', 'service': 'service', 'ca_trust_path': 'ca_trust_path', 'default_headers': {u'Content-Type': u'application/soap+xml;charset=UTF-8', u'User-Agent': u'Python WinRM client'}, 'read_timeout_sec': '40', 'session': <requests.sessions.Session object at 0x7fb773041c90>, 'cert_pem': 'cert_pem', 'kerberos_delegation': True, 'realm': 'realm', 'server_cert_validation': 'validate', 'password': 'password', 'auth_method': 'ssl', 'cert_key_pem': 'cert_key_pem'}

>>> x.send_message('asdf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 184, in send_message
    response = self.session.send(prepared_request, timeout=self.read_timeout_sec)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/util/connection.py", line 70, in create_connection
    sock.settimeout(timeout)
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
TypeError: a float is required
```

With int value for `read_timeout_sec`:
```
>>> x.read_timeout_sec
40

>>> x.send_message('asdf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 184, in send_message
    response = self.session.send(prepared_request, timeout=self.read_timeout_sec)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

# Fails due to my using dummy values
```

**Comment by jborean93** [comment]
I feel that the parsing and potentially trying to convert the values should be in pywinrm as Ansible doesn't have full control over the kwargs that are parsed in. The reason why these variables are dynamic is so different pywinrm versions can be installed to take advantage of newer functionality without the need to update Ansible. If we were to hard code in these conversions for some of the timeout kwargs in Ansible then we are a bit at the mercy of pywinrm changes and have started to tightly couple them.

On the other handle the error message in that case would still be a bit confusing to end users as they will put in `ansible_winrm_read_timeout_sec` but the error would just refer to `read_timeout_sec` if it is in pywinrm.

I don't mind where is goes ultimately as yes we should be giving a better error message but I'll leave it for @nitzmahone to chime in and see how he feels.

**Comment by nrwahl2** [comment]
I agree with that. Unless that will break something else in pywinrm, typecasting with `float()` in pywinrm ought to work:
```
        self.read_timeout_sec = float(read_timeout_sec)
        self.operation_timeout_sec = float(operation_timeout_sec)
```
^in protocol.py causes the "float is required" error to stop happening for me.

**Comment by lawrence-c** [comment]
$Customer here is confused :-) using ansible version 2.4.1.0

I get `fatal: [redacted-url]: UNREACHABLE! => {"changed": false, "msg": "ssl: a float is required", "unreachable": true}`

When I use it in the command line with the following:
```
ANSIBLE_CONFIG=./ansible.cfg ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook -v -i ./ansible/hosts -l "TEST_nodes" -e "ansible_user=username ansible_password=password ansible_become_pass=password ansible_port=5986 ansible_connection=winrm ansible_winrm_server_cert_validation=ignore ansible_winrm_read_timeout_sec=150 ansible_winrm_operation_timeout_sec=120" ./ansible/site.yml
```
Am I not allowed to use it in this way?

**Comment by dagwieers** [comment]
@SurferL Try using `ansible_winrm_read_timeout_sec=150.0` ?
If that doesn't work, it's because the legacy key=value syntax does not support YAML type detection (and it probably should).

**Comment by lawrence-c** [comment]
@dagwieers Thanks for the response! I'm afraid that didn't work (comes up with the same error)

**Comment by dagwieers** [comment]
@SurferL This deserves a separate issue. Can you create a new issue ticket ?

**Comment by jborean93** [comment]
A beta of pywinrm has been released which fixed the issue around `ansible_winrm_read_timeout_sec` and `ansible_winrm_operation_timeout_sec`, details of it are here https://groups.google.com/forum/#!topic/ansible-project/2ywJphGNNJs. While not officially released this issue is somewhat separate to Ansible so I am going to close it.
