### ISSUE TITLE
Vault key rotation using ansible

### ISSUE THREAD

**Issue by mpostument** [ansible/ansible#25604]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
vault module

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```
##### SUMMARY
It will be nice to have ansible vault module.
I need to rotate vault keys every 90 days for few github repo. And i would like ansible module which
allow to specify vault file, old password and new one. And ansible will update those vault files with new

**Comment by alikins** [comment]
@Infectsoldier You mention an ansible vault module. Would the intention be a module that can run on a remotely managed system and vault encrypt/decrypt/rekey files there?

Or would having 'ansible-vault' on the controller supporting this be sufficient?

**Comment by bcoca** [comment]
on the controller, `ansible-vault` already supports key rotation either via prompt or 2 key files or other combinations.

**Comment by mpostument** [comment]
@alikins on the controller

**Comment by bcoca** [comment]
@Infectsoldier soo, i'm just going to close this as 'already implemented'

**Comment by Infectsoldier** [comment]
@bcoca can you give me an example how to use key rotation?
I can't find any example

**Comment by mpostument** [comment]
@bcoca yeah rekey is similar what i need, but would be nice to have possibility to specify old and new password from command line or ansible, without typing

**Comment by bcoca** [comment]
@Infectsoldier use vault 'secret' files, having it in the command line directly is a security issue, we don't allow this for any of our passwords
