### ISSUE TITLE
File module expands found file names

### ISSUE THREAD

**Issue by thepax** [ansible/ansible#25639]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

file

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### SUMMARY

File module expands file names.

##### STEPS TO REPRODUCE

```
mkdir /tmp/testdir
touch '/tmp/testdir/$_'
ansible all -i "localhost," -c local -m file -a "path=/tmp/testdir recurse=true mode=0400"
```

##### EXPECTED RESULTS

Permission is changed

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 13] Permission denied: '/tmp/testdir//usr/bin/python'
localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_zETib4/ansible_module_file.py\", line 480, in <module>\n    main()\n  File \"/tmp/ansible_zETib4/ansible_module_file.py\", line 362, in main\n    changed |= recursive_set_attributes(module, to_bytes(file_args['path'], errors='surrogate_or_strict'), follow, file_args)\n  File \"/tmp/ansible_zETib4/ansible_module_file.py\", line 171, in recursive_set_attributes\n    changed |= module.set_fs_attributes_if_different(tmp_file_args, changed)\n  File \"/tmp/ansible_zETib4/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1298, in set_fs_attributes_if_different\n  File \"/tmp/ansible_zETib4/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1064, in set_mode_if_different\nOSError: [Errno 13] Permission denied: '/tmp/testdir//usr/bin/python'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

**Comment by andreaso** [comment]
Here we have where the breaking expansion happens.

https://github.com/ansible/ansible/blob/bf63301b341ef68abb5c7c0f9d3ae7b475800f48/lib/ansible/module_utils/basic.py#L1177-L1178

...as well as the some context from the module itself.

https://github.com/ansible/ansible/blob/bf63301b341ef68abb5c7c0f9d3ae7b475800f48/lib/ansible/modules/files/file.py#L165-L185

Without having thought things through all the way it feels like the right solution involves making sure that the _file_ module always calls `set_fs_attributes_if_different()` with the `expand=False` argument.

Not sure yet whatever or not we need to compensate by doing an initial expand of the path input.

**Comment by andreaso** [comment]
Nope, no need to do any initial expand of the path parameter, as it's already being expanded, based on its type.

https://github.com/ansible/ansible/blob/bf63301b341ef68abb5c7c0f9d3ae7b475800f48/lib/ansible/modules/files/file.py#L193
https://github.com/ansible/ansible/blob/bf63301b341ef68abb5c7c0f9d3ae7b475800f48/lib/ansible/module_utils/basic.py#L1797-L1799
