### ISSUE TITLE
ini-file inventories behave oddly with group/children ordering

### ISSUE THREAD

**Issue by skvidal** [ansible/ansible#2564]
If we create an inventory file like this:

``` ini
[simple]
host1

[complex:children]
simple

[complex]
host2

```

and then we run this script

``` python
import ansible.inventory
inv = ansible.inventory.Inventory('inventory_file')
total = set(inv.get_hosts())
allgroup = inv.get_group('all')
all = set(allgroup.get_hosts())
odd = list(total.difference(all))[0]
print odd.name
```

We will see that 'host2' is not included in the 'all' group.

If we change the inventory file to be

``` ini
[simple]
host1

[complex]
host2

[complex:children]
simple

```

then it all works.

I'm not sure where the bug is, but it was very confusing when I was trying to see if the variables from group_vars/all we're being picked up correctly.

**Comment by skvidal** [comment]
I think this is the fix for it. It fixes for the case I outlined above
https://github.com/ansible/ansible/pull/2570

**Comment by mpdehaan** [comment]
closed per above, thanks!
