### ISSUE TITLE
django_manage environment variables

### ISSUE THREAD

**Issue by kerridge0** [ansible/ansible#2568]
How can I pass secret_key and/or DJANGO_SETTINGS_MODULE variables to django_manage?

I've tried setting up the environment variables in the end of the virtualenv activate script but it's not getting activated.

**Comment by mpdehaan** [comment]
technically there is an environment keyword in 1.1, though there is also a settings param to the management module

```
- django_manage: foo
  environment: 
      DJANGO_SETTINGS_MODULE=foo
```

BTW, please ask questions to the mailing list, not the bug tracker, that allows others to help answering them and you may get a quicker answer, and then others benefit from discussion too.

Thanks!
