### ISSUE TITLE
ansible-vault Logs Decrypted Contents to Log

### ISSUE THREAD

**Issue by selble** [ansible/ansible#25719]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-vault

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /opt/ansible/sysadmin/ansible.cfg
  configured module search path = ['/usr/share/ansible/', '/opt/ansible/sysadmin/library/']
```

##### CONFIGURATION
```
[defaults]
hostfile       = /opt/ansible/sysadmin/hosts
library = /usr/share/ansible/:/opt/ansible/sysadmin/library/
remote_tmp     = /tmp/.ansible-$USER
pattern        = *
forks          = 15
poll_interval  = 15
transport      = smart
remote_port    = 22
module_lang    = C
gathering = smart
roles_path = ~/git/ansible/sysadmin/roles:/opt/ansible/sysadmin/roles:/etc/ansible/roles
host_key_checking = False
sudo_exe = sudo
timeout = 10
remote_user = sysadmin
log_path = /var/log/ansible.log
ansible_managed = Ansible managed - do not edit manually
action_plugins     = /usr/share/ansible_plugins/action_plugins
callback_plugins   = /usr/share/ansible_plugins/callback_plugins
connection_plugins = /usr/share/ansible_plugins/connection_plugins
lookup_plugins     = /usr/share/ansible_plugins/lookup_plugins
vars_plugins       = /usr/share/ansible_plugins/vars_plugins
filter_plugins     = /usr/share/ansible_plugins/filter_plugins
fact_caching = jsonfile
fact_caching_connection = /var/cache/ansible_facts
fact_caching_timeout = 1209600
vault_password_file = /etc/ansible/sysadmin/vaultpass
[privilege_escalation]
[paramiko_connection]
record_host_keys=False
[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=1800s
pipelining = True
scp_if_ssh = True
[accelerate]
accelerate_port = 5099
accelerate_timeout = 30
accelerate_connect_timeout = 5.0
accelerate_daemon_timeout = 30 
```

##### OS / ENVIRONMENT
Ansible is running on a CentOS 7.3.1611 system

##### SUMMARY
We had implemented transparent encryption of certain file types (*.key, etc.) using Ansible Vault, more-or-less as described here:

https://leucos.github.io/articles/transparent-vault-revisited/

It generally worked well, but we recently noticed that sensitive data was getting logged in the Ansible log file when doing "git diff", "git checkout", etc.

While this may sound like an issue with the Git configuration and/or the ansible-vault-* scripts referenced on the github.io site (and it may well be partially an issue there), I'm still struggling to explain why it seems to be the ansible-vault process that is logging it:

```
2017-06-13 17:48:47,106 p=23807 u=selble |  -----BEGIN RSA PRIVATE KEY----- <--- from /var/log/ansible.log

...and the corresponding strace when doing a git diff, showing the PID correlation...

[pid 23807] rt_sigaction(SIGCHLD, {SIG_DFL, [], SA_RESTORER|SA_RESTART, 0x7faae67a3250}, {0x441200, [], SA_RESTORER|SA_RESTART, 0x7faae67a3250}, 8) = 0
[pid 23807] open("/dev/null", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
[pid 23807] dup2(5, 2)                  = 2
[pid 23807] close(5)                    = 0
[pid 23807] execve("/usr/bin/ansible-vault", ["ansible-vault", "view", "/tmp/tmp.jdxaoFmpWO"], [/* 27 vars */]) = 0
[pid 23807] brk(0)                      = 0x2422000
```

##### STEPS TO REPRODUCE

Checkout Git repository and branch that contains encrypted data and a .gitattributes file that lists the filters and diff statements:

```
*.key filter=ansible-vault diff=ansible-vault
*.pw filter=ansible-vault diff=ansible-vault
```

Run a git diff

Sensitive data will be logged in /var/log/ansible.log

##### EXPECTED RESULTS
Don't log my sensitive data

##### ACTUAL RESULTS

Sensitive data was logged

```
N/A
```

**Comment by alikins** [comment]
'ansible-vault view' is using ansible.cli.vault.VaultCLI.execute_view, which does:

``` python
     self.pager(to_text(self.editor.plaintext(f)))
```

self.pager is ansible.cli.CLI.pager which does:

``` python
     if not sys.stdout.isatty():
         display.display(text)
```

(or some variant of display.display())... display.display -> ansible.utils.display.Display.display()

display.display() will also log to the log_file if it is not called with 'screen_only'.

In other words, to fix the bug we need to pass 'display_only=True' from VaultCLI.excute_view() down through CLI.pager() to display.display().

**Comment by selble** [comment]
Many thanks for the quick fix on this. As you might imagine, having sensitive data show up in logs that in turn are ingested into Splunk can raise some eyebrows.
