### ISSUE TITLE
host_group_vars.py incorrectly accesses non-YAML files

### ISSUE THREAD

**Issue by wincent** [ansible/ansible#25712]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

host_group_vars.py

##### ANSIBLE VERSION

Current HEAD of the "devel" branch:

```
ansible 2.4.0 (devel 6b99f0d65c) last updated 2017/06/14 09:06:03 (GMT -700)
  config file = None
  configured module search path = [u'/Users/glh/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/glh/code/ansible-configs/vendor/ansible/lib/ansible
  executable location = /Users/glh/code/ansible-configs/vendor/ansible/bin/ansible
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### OS / ENVIRONMENT

Running on macOS, but it's almost certainly irrelevant.

##### SUMMARY

Attempts to run a playbook are blowing up because host_group_vars.py is trying to parse files like "group_vars/all/.gitignore" as YAML.

(Note that in practice, I discovered this issue because of another invisible dot-file in one of my directories, but I am using ".gitignore" in the example here because it is probably more representative of the kind of scenario people could conceivably run into in the wild.)

##### STEPS TO REPRODUCE

In any Ansible project that uses group_vars, create a "group_vars/all/.gitignore" file containing something that is not valid YAML — eg. "!foo" — then run the playbook.

##### EXPECTED RESULTS

Playbook should run without errors.

##### ACTUAL RESULTS

Playbook blows up:

```
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/tmp/demo/group_vars/all/.gitignore': line 1, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


!foo
^ here

exception type: <class 'yaml.constructor.ConstructorError'>
exception: could not determine a constructor for the tag '!foo'
  in "<unicode string>", line 1, column 1
```

#### WORKAROUND

Instead of blindly appending files from the directory to the list of found files, only do it with files that have YAML extensions:

```
diff --git a/lib/ansible/plugins/vars/host_group_vars.py b/lib/ansible/plugins/vars/host_group_vars.py
index 9612b2f4b9..055c9a82b7 100644
--- a/lib/ansible/plugins/vars/host_group_vars.py
+++ b/lib/ansible/plugins/vars/host_group_vars.py
@@ -111,7 +111,7 @@ class VarsModule(BaseVarsPlugin):
                         full_spath = os.path.join(full_path, spath)
                         if os.path.isdir(full_spath):
                             found.extend(self._find_vars_files(full_spath, ''))
-                        else:
+                        elif full_spath.endswith(tuple(C.YAML_FILENAME_EXTENSIONS)):
                             found.append(full_spath)
                 else:
                     found.append(full_path)
```

Not sure whether we need to do the same on the other `found.append()` call further down as well, or whether this is compatible enough (`endswith` only started accepting a tuple argument in Python 2.5, and I don't know how far back Ansible supports). Additionally, this is obviously a case-sensitive check. We might want a case-insensitive one.

**Comment by bcoca** [comment]
we already filter in `_find_vars_files`, but this includes files w/o an extension as `group_vars/all` is also valid, we should skip hidden files though.

**Comment by bcoca** [comment]
```
diff --git a/lib/ansible/plugins/vars/host_group_vars.py b/lib/ansible/plugins/vars/host_group_vars.py
index 9612b2f4b9..6bebdb0f34 100644
--- a/lib/ansible/plugins/vars/host_group_vars.py
+++ b/lib/ansible/plugins/vars/host_group_vars.py
@@ -108,6 +108,8 @@ class VarsModule(BaseVarsPlugin):
                 if os.path.isdir(full_path):
                     # matched dir name, so use all files included recursively
                     for spath in os.listdir(full_path):
+                        if spath.startswith('.'):
+                            continue
                         full_spath = os.path.join(full_path, spath)
                         if os.path.isdir(full_spath):
                             found.extend(self._find_vars_files(full_spath, ''))
```

**Comment by wincent** [comment]
Yep, that would solve my concrete case.
