### ISSUE TITLE
Local_connection return local facts when hostvars variable uses  ansible_variables

### ISSUE THREAD

**Issue by lberruti** [ansible/ansible#2572]
Local_connection return local facts when hostvars variable uses  ansible_variables

```
# hosts file
127.0.0.1 a=a$ansible_domain
fw.inter.nos a=b$ansible_domain
mail.inter.nos a=c$ansible_domain
mail.outer.nos a=d$ansible_domain
```

```
# test.yml playbook

---
- hosts: all:!127.0.0.1
  tasks:
    - debug: msg="$a"

- hosts: 127.0.0.1
  connection: local
  tasks:
    - template: src=templ.j2 dest=/tmp/templ
```

```
# templ.j2 template
{%- for host in groups['all'] %}
{{ host }} ==> {{ hostvars[host].a }}
{% endfor%}
```

/tmp/templ contains

```
fw.inter.nos ==> blocal
mail.inter.nos ==> clocal
mail.outer.nos ==> dlocal
127.0.0.1 ==> alocal
```

instead of

```
fw.inter.nos ==> binter.nos
mail.inter.nos ==> cinter.nos
mail.outer.nos ==> douter.nos
127.0.0.1 ==> alocal
```

**Comment by bennojoy** [comment]
Not sure, when the variables in the inventory are populated, but wouldnt it
be possible to achieve the same result via

# templ.j2 template

{%- for host in groups['all'] %}
{{ host }} ==> {{ hostvars[host].ansible_domain }}
{% endfor%}

Benno

**Comment by lberruti** [comment]
Yes, It works using ansible_domain.
But let's see another example: autogenerate ssh_config with proxycommand

```
# ssh_config.j2
{% for host in groups['all'] %}
{% if hostvars[host]['ssh_proxy_host'] %}
Host {{ host }}
  ProxyCommand ssh {{ hostvars[host]['ssh_proxy_host'] }} nc -q 0 %h %p
{% endif %}
{% endfor %}
```

```
# group_vars/all
# standard default
ssh_proxy_host: gw.${ansible_domain} #ie. no, gw.${ansible_domain}
```

```
# host_vars/nostandard.example.com
ssh_proxy_host: frontend.example.com
```

```
# host_vars/directaccess.example.com
ssh_proxy_host: no
```

Luca

**Comment by bennojoy** [comment]
Would this help

# group_vars/all

# standard default

ssh_proxy_host: no

# ssh_config.j2

{% for host in groups['all'] %}
{% if hostvars[host]['ssh_proxy_host'] %}
Host {{ host }}
  ProxyCommand ssh {{ hostvars[host]['ssh_proxy_host'] }} nc -q 0 %h %p

{% else %}

Host {{ host }}
  ProxyCommand ssh {{ hostvars[host]['ansible_hostname'] }} nc -q 0 %h %p

{% endif %} {% endfor %}

**Comment by mpdehaan** [comment]
The local connection specifies talking to all entries in the host file as local.

If you wish to make some local, set "ansible_connection=ssh" in them as inventory variables and don't specify the connection in the playbook.

This is working as designed.
