### ISSUE TITLE
Ansible should not preserve quotes on /etc/lsb-release DISTRIB_ID value

### ISSUE THREAD

**Issue by naftulikay** [ansible/ansible#25725]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Ansible facts, specifically `ansible_distribution` et al, and how they are evaluated.

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /home/naftuli/Documents/Development/naftulikay/ansible-role-time/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

None.

##### OS / ENVIRONMENT

elementary OS Loki, which is Ubuntu 16.04. 

##### SUMMARY

My `ansible_distribution` here is being reported as the literal string `"elementary"` including the quotes, because these are present in `/etc/lsb-release`:

```
DISTRIB_ID="elementary"
DISTRIB_RELEASE=0.4.1
DISTRIB_CODENAME=loki
DISTRIB_DESCRIPTION="elementary OS 0.4.1 Loki"
```

##### STEPS TO REPRODUCE

Run the following Ansible command on a Loki VM or something:

```
$ ansible -i 127.0.0.1, -c local all -m setup -a filter=ansible_distribution
127.0.0.1 | SUCCESS => {
    "ansible_facts": {
        "ansible_distribution": "\"elementary\""
    },
    "changed": false
}
```

##### EXPECTED RESULTS

I expected Ansible to unescape quotes in `/etc/lsb-release`, as this file is straight from the upstream distribution, unmodified.

##### ACTUAL RESULTS

I instead get the literal string `"elementary"` as opposed to `elementary`:

```
127.0.0.1 | SUCCESS => {
    "ansible_facts": {
        "ansible_distribution": "\"elementary\""
    },
    "changed": false
}
```

**Comment by alikins** [comment]
Looking around, the format of lsb-release isn't really specified. The shell version of the 'lsb_release' command doesn't seem to read /etc/lsb-release, while the newer python based lsb_release.py does read it and will remove quotes.

Assuming no one has named their distro  "THE_QUOTES_ARE_INCLUDED_IN_THE_NAME" and expect the quotes to be included, removing them in the facts code should be ok.

What is the output of the lsb_release command?

-  `lsb_release`
- `lsb_release -a`
- `lsb_release -i`

**Comment by alikins** [comment]
Stripping the quotes breaks an existing unit test that has the DISTRIB_DESCRIPTION quoted.

The Ubuntu 16.04 /etc/lsb-release looks like:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
```

with description quoted but not ID. To me, I would say quoting the the DISTRIB_ID is unconventional,
but cant say it's wrong.

Is there is a good doc describing the /etc/lsb-release format that explains the expected behavior for quoted values? 

I think we should just leave it as is for now until we see a better spec for the format.

**Comment by naftulikay** [comment]
@alikins Here are the commands you requested:

```
naftuli@reprisal:~$ lsb_release
No LSB modules are available.
naftuli@reprisal:~$ lsb_release -a
No LSB modules are available.
Distributor ID: elementary
Description:    elementary OS 0.4.1 Loki
Release:        0.4.1
Codename:       loki
naftuli@reprisal:~$ lsb_release -i
Distributor ID: elementary
naftuli@reprisal:~$ cat /etc/lsb-release
DISTRIB_ID="elementary"
DISTRIB_RELEASE=0.4.1
DISTRIB_CODENAME=loki
DISTRIB_DESCRIPTION="elementary OS 0.4.1 Loki"
```

This is a _very_ stock installation of elementary OS, being a downstream from Ubuntu 16.04 Xenial.

```
$ ansible -i 127.0.0.1, -c local all -m setup | grep distribution
        "ansible_distribution": "\"elementary\"",
        "ansible_distribution_major_version": "0",
        "ansible_distribution_release": "loki",
        "ansible_distribution_version": "0.4.1",
```

And again, for giggles:

```
$ ansible --version
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
```
