### ISSUE TITLE
shell module: ansible variables not resolved when not in first whitespace separated string and full line not quoted

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#2573]
This works, ansible resolves $BAMBOO_URL

```
shell: 'java -Dbamboo.home=/opt/bamboo-agent/agent${item} -jar /opt/bamboo-agent/agent.jar $BAMBOO_URL install'
```

This does not, $BAMBOO_URL is not resolved by ansible, and becomes empty at the end (probaly resolved by the shell)

```
shell: java -Dbamboo.home=/opt/bamboo-agent/agent${item} -jar /opt/bamboo-agent/agent.jar $BAMBOO_URL install
```

**Comment by dagwieers** [comment]
I think it's because YAML doesn't allow strings containing colons (:) unless they are quoted.

**Comment by mpdehaan** [comment]
I'm not sure what you say is true, @sergevanginderachter but it is true colons must be quoted, though I don't see a colon.

I would need a playbook to reproduce.  I would suggest posting on the mailing list.

**Comment by srgvg** [comment]
there ain't much more to give than this task. with_item contained [1,2,3] and $BAMBOO_URL did contain an URI, including http://...,  thus yes there was a colon.
So @dagwieers might be right, although I would expect this to yield an error instead of silently not resolve the var.

Leave this closed, I'll get back here if I encounter more use cases.
