### ISSUE TITLE
Service module uses commands prefixed with 'one' on FreeBSD

### ISSUE THREAD

**Issue by thnee** [ansible/ansible#25743]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`modules/system/service`

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /path/playbooks/ansible.cfg
  configured module search path = [u'../library/']
  python version = 2.7.13 (default, Apr 29 2017, 01:15:48) [GCC 4.2.1 Compatible FreeBSD Clang 3.8.0 (tags/RELEASE_380/final 262564)]
```

##### CONFIGURATION

```
[defaults]
log_path = ../ansible.log
library = ../library/
roles_path = ../roles/
inventory = ../inventory/hosts.ini
vault_password_file = ../.vault_password

[colors]
debug = purple
```

##### OS / ENVIRONMENT

FreeBSD 11, both as manager and managee.

##### SUMMARY

The `FreeBsdService` subclass of the service module uses `onestart` / `onestop` / `onereload` / `onestatus` instead of the expected `start` / `stop` / `reload` / `status`. These commands are not functionally equivalent, the commands prefixed with `one` **overrides** any flags in `rc.conf`.

I propose that ansible uses that standard `start` / `stop` / `reload` / `status`. If the commands prefixed with `one` are desired, they should be available under some other abstraction. (Or, optionally, if this truly is an intentional design decision, document it clearly, because this strongly deviates from what is to be expected).

One example package where this issue becomes very clear is `samba46`, which has multiple daemons that are controlled with separate enable flags. Even though samba is a good example, this applies to all packages, regardless of how many daemons it happens to contain

Relevant code is here: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/service.py#L1084
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/service.py#L1005

Similar issue in salt: https://github.com/saltstack/salt/issues/10619

##### STEPS TO REPRODUCE case 1

Set state `started` on `samba_server` service while it is not started, with these variables set in `rc.conf`:
```
samba_server_enable="YES"
winbindd_enable="NO"
```

```yaml
- name: 'start samba'
  service:
    name: 'samba_server'
    state: 'started'
```

##### EXPECTED RESULTS case 1

Only `smbd` and `nmbd` should be started, `winbindd` should not be started.

##### ACTUAL RESULTS case 1

Not only are `smbd` and `nmbd` started, but also `winbindd`, because `onestart` overrides any enable flags in `rc.conf`.

##### STEPS TO REPRODUCE case 2

Set state `started` on `samba_server` service while it is started, with these variables set in `rc.conf`:
```
samba_server_enable="YES"
winbindd_enable="NO"
```

```yaml
- name: 'start samba'
  service:
    name: 'samba_server'
    state: 'started'
```

##### EXPECTED RESULTS case 2

`FreeBsdService:get_service_status` should return `True`.

```
TASK [samba : start samba] *****************************************************************************************************************************************************************************************
ok: [smb]
```

##### ACTUAL RESULTS case 2

`FreeBsdService:get_service_status` returns `False`, because it uses `onestatus`, where as the correct command `status` would produce correct results.

```
TASK [samba : start samba] *****************************************************************************************************************************************************************************************
task path: /path/roles/samba/tasks/main.yml:31
<ioc-86b494ae-3530-4f59-b3ca-76bc4b3ab3b3> Jail smb has been translated to ioc-86b494ae-3530-4f59-b3ca-76bc4b3ab3b3
Using module file /path/library/freebsd_service.py
<ioc-86b494ae-3530-4f59-b3ca-76bc4b3ab3b3> ESTABLISH JAIL CONNECTION FOR USER: None
<ioc-86b494ae-3530-4f59-b3ca-76bc4b3ab3b3> EXEC ['/usr/sbin/jexec', 'ioc-86b494ae-3530-4f59-b3ca-76bc4b3ab3b3', u'/bin/sh', '-c', u"/bin/sh -c 'echo ~ && sleep 0'"]
<ioc-86b494ae-3530-4f59-b3ca-76bc4b3ab3b3> EXEC ['/usr/sbin/jexec', 'ioc-86b494ae-3530-4f59-b3ca-76bc4b3ab3b3', u'/bin/sh', '-c', u'/bin/sh -c \'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1497530533.1-257564126878009 `" && echo ansible-tmp-1497530533.1-257564126878009="` echo /root/.ansible/tmp/ansible-tmp-1497530533.1-257564126878009 `" ) && sleep 0\'']
<ioc-86b494ae-3530-4f59-b3ca-76bc4b3ab3b3> PUT /tmp/tmp7g2QKw TO /root/.ansible/tmp/ansible-tmp-1497530533.1-257564126878009/freebsd_service.py
<ioc-86b494ae-3530-4f59-b3ca-76bc4b3ab3b3> EXEC ['/usr/sbin/jexec', 'ioc-86b494ae-3530-4f59-b3ca-76bc4b3ab3b3', u'/bin/sh', '-c', u'dd of=/root/.ansible/tmp/ansible-tmp-1497530533.1-257564126878009/freebsd_service.py bs=65536']
<ioc-86b494ae-3530-4f59-b3ca-76bc4b3ab3b3> EXEC ['/usr/sbin/jexec', 'ioc-86b494ae-3530-4f59-b3ca-76bc4b3ab3b3', u'/bin/sh', '-c', u"/bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1497530533.1-257564126878009/ /root/.ansible/tmp/ansible-tmp-1497530533.1-257564126878009/freebsd_service.py && sleep 0'"]
<ioc-86b494ae-3530-4f59-b3ca-76bc4b3ab3b3> EXEC ['/usr/sbin/jexec', 'ioc-86b494ae-3530-4f59-b3ca-76bc4b3ab3b3', u'/bin/sh', '-c', u'/bin/sh -c \'/usr/local/bin/python2.7 /root/.ansible/tmp/ansible-tmp-1497530533.1-257564126878009/freebsd_service.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1497530533.1-257564126878009/" > /dev/null 2>&1 && sleep 0\'']
fatal: [smb]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "arguments": "", 
            "enabled": null, 
            "name": "samba_server", 
            "pattern": null, 
            "runlevel": "default", 
            "sleep": null, 
            "state": "started"
        }
    }, 
    "msg": "nmbd already running?  (pid=52843).\nsmbd already running?  (pid=52849).\n"
}
```

**Comment by bcoca** [comment]
IIRC the `one` prefix was added specifically to ensure the status of the service was followed and any enabled/disabled entry in rc was ignored.  Having a service be 'multiple services' was probably not a case considered at the time.

**Comment by thnee** [comment]
Thanks for taking the time to reply. Not sure what that means "the status of the service was followed". Using `onestart` and the like clearly breaks when using perfectly valid configuration flags in `rc.conf`, as shown by case 2 above. These commands are provided in FreeBSD as a way of overriding configuration. They should not be considered a default mode of operation for a service module, especially without any explicit comment as to why.

**Comment by bcoca** [comment]
status/start/stop would now work to reflect the expected 'state' in the task, as they would 'obey' the configuration, this is fine for services that have a single daemon/daemon state to consider.

What was not considered is your case, that the service is actually multiple daemons, optional via configuration.

**Comment by thnee** [comment]
I see. It would still be possible to 'obey' the configuration of having the service started, assuming that the user has also enabled it beforehand. This is the standard way of using services on FreeBSD.

**Comment by bcoca** [comment]
@thnee understood, but this was decided long ago to 'normalize' the behaviour as on other unicies for the module.

**Comment by thnee** [comment]
For the corner case where people actually want to start a service that is not enabled, I can think of two possible solutions:

- Have the `service` module automatically enable the service before starting it.
- Provide a `force` flag on the `service` module, that would convert `start` into `onestart` etc. Could look like this:

```
- name: 'start samba'
  service:
    name: 'samba_server'
    state: 'started'
    force: true
```

The one case where it might actually make sense to always convert the command, is from `stop` into `onestop`. Because all currently running daemons in the service should be stopped in either case. And it would save having to check if it is enabled, or forcing it.

**Comment by bcoca** [comment]
so this just affects started/status ? ... is there a flag where we can discover if a service is a composite?

**Comment by thnee** [comment]
Generally, I believe this affects all states of the `service` module on FreeBSD, that's why they all have the prefixed counterparts.

Converting from `stop` into `onestop` is a case where it probably would not do something totally unexpected. Although, since the `service` module already handles this by not executing anything at all if the state is not changing, I guess this is a moot point.

**Comment by thnee** [comment]
@bcoca Any feedback on the previous suggestions?

Yet another suggestion could be to add a configuration variable to control this behavior, although I must say I think adding a `force` flag would be much more in line with general expectations.

**Comment by bcoca** [comment]
My current thinking is to finish the 'separation from service.py' and have a rc_service module that has specific options for one vs 'non-one-prefixed' calls.

**Comment by bsdxbsdx** [comment]
I discovered this issue today because I noticed Ansible starting a service that was essentially disabled by default in rc.conf by not being listed. It happens to be a service (xenguest) that starts automatically at boot if a kernel feature is detected and no longer needs to be specifically enabled in rc.conf. I have Ansible install the xe-guest-utilities packages in case the VM gets moved to a Xen hypervisor later but I only want the service to run on systems actually running under Xen. I have a state=started task intending to start it only on the appropriate systems.

To some degree I can agree that I am telling Ansible to do something that I may not actually want and it is following my orders, but it should not be using the service framework to do this more forcefully than intended.

Furthermore I tried commenting out the onestart replacement in service.py. Ansible no longer started the service (good) but reported the task status as [changed] which it actually had not (bad). I think it would be fair for the task to fail if it was asked to start a service that is not enabled, without some kind of supplied force flag.

My initial reason for looking into this was very minor so I am just following to find out the outcome.

**Comment by samdoran** [comment]
This still seems to be the case. This currently exists in the `service` module. We need to create a new module called `bsdinit` that will be called by the `service` action plugin. We want to avoid adding new capability to the `service` module.  A parameter can be added to that `bsdinit` module to allow disabling the use of the `one` prefix.

**Comment by s-hertel** [comment]
Since we don't plan on implementing this in the `service` module, I'm closing this issue. New modules should be submitted to a collection.  Thank you very much for your interest in Ansible.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.libera.chat
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
