### ISSUE TITLE
provide option to consider any changes a junit failure in junit plugin

### ISSUE THREAD

**Issue by hogarth-sv** [ansible/ansible#25740]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
junit

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 31 2017, 17:58:17) [GCC 7.1.1 20170503 (Red Hat 7.1.1-1)]
```

##### CONFIGURATION
```
[defaults]
callback_whitelist = junit

-------
ENV VARS:
JUNIT_TASK_CLASS="True" 
JUNIT_OUTPUT_DIR="/srv/ansible/results-something-run2"
```
##### OS / ENVIRONMENT
N/A

##### SUMMARY
A fairly common scenario is an idempotent test to ensure that multiple runs are safe.

In this situation any "changed" reported should be considered a fail in junit reporting.

##### STEPS TO REPRODUCE
Any playbook that results in a task reporting "changed" with multiple runs

The junit report states that there were no test failures on the multiple runs, although if doing idempotent testing then any subsequent runs that report "changed" should be considered a junit failure.

##### EXPECTED RESULTS
The junit report to consider it a test failure for any tasks reporting "changed" when directed that it is an idempotent test.

##### ACTUAL RESULTS
The generated junit report stating all tests passed on any run making idempotent testing trickier

**Comment by hogarth-sv** [comment]
resolved_by_pr #25752

**Comment by Akasurde** [comment]
Closing this issue as PR is merged. If issue persists, please feel free to re-open.
