### ISSUE TITLE
The Logger() setup by utils.display uses an unconventional name

### ISSUE THREAD

**Issue by alikins** [ansible/ansible#25757]
##### SUMMARY

The logging.Logger() class setup by ansible.utils.display() uses an unconventional name  ('p=$PID u=$USER | ')

``` python
     logger = logging.getLogger("p=%s u=%s | " % (mypid, user))
```

Normal convention is to use the module name for the Logger() name, ie

``` python
    logger = logging.getLogger(__name__)
```

https://docs.python.org/2/howto/logging.html#advanced-logging-tutorial

> A good convention to use when naming loggers is to use a module-level logger, in each module which uses logging, named as follows:
> 
> logger = logging.getLogger(__name__)
> 
> This means that logger names track the package/module hierarchy, and it’s intuitively obvious where events are logged just from the logger name.

This results in the Logger() used for display being hard to reference from other code or from logging configuration since the logger name is dynamic. If a different log handler is added to that logger (for ex, a syslog handler), then the log events are generated with unusual and unpredictable names.

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

lib/ansible/utils/display.py

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 44687bb917) last updated 2017/06/15 13:12:13 (GMT -400)
  config file = None
  configured module search path = [u'/home/adrian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]


```

##### CONFIGURATION

```
[defaults]
log_path = /path/to/some/log/file.log
```
##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment]
the logger was meant to record 'ansible actions' not internal library errors, its more a 'cli tool logger'

**Comment by ssbarnea** [comment]
@bcoca I am on @alikins side here, ansible should use Python logging facilities correctly. Python logging was not designed only for library errors, in fact it was designed using the same concepts as the Java ones that allow very well refined logging with handlers, filters.

Ansible should adapt and extend its logging to fit actions into normal logging without abusing them.

**Comment by samdoran** [comment]
After some discussion, the best way to solve this is to standardize `__name__` and add that to our logging format since we need the existing information in the log message.
