### ISSUE TITLE
Not all spellings of boolean "false" in inventory are interpreted as false by  Jinja

### ISSUE THREAD

**Issue by fthommen** [ansible/ansible#25784]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
inventory
template
jinja

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
none special

##### OS / ENVIRONMENT
CentOS 7 on x86_64

##### SUMMARY
Boolean variables set in the inventory are not respected by Jinjia as one would expect.  According to http://docs.ansible.com/ansible/YAMLSyntax.html e.g. the boolean value false can be written "false", "False", "FALSE" or "no".  But only the exact spelling "False" is seen as false by Jinjia, all other spellings are seen as true value.

This is similar to and maybe related to (or the same problem as)  #25778.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  tasks:
  - shell: "echo \"The switch is {% if switch %}ON{% else %}OFF{% endif %} ({{ switch }})\""
    register: echo

  - debug:
      var: echo
```
set "switch" to various values in the inventory.

##### EXPECTED RESULTS

switch=False: The switch is OFF (False)
switch=FALSE: The switch is **OFF** (FALSE)
switch=false: The switch is **OFF** (false)
switch=no: The switch is **OFF** (no)
switch=0: The switch is OFF (0)
switch=true: The switch is ON (true)
switch=blah: _(not sure what to expect here, probably an error message)_

##### ACTUAL RESULTS
echo results:

switch=False: The switch is OFF (False)
switch=FALSE: The switch is **ON** (FALSE)
switch=false: The switch is **ON** (false)
switch=no: The switch is **ON** (no)
switch=0: The switch is OFF (0)
switch=true: The switch is ON (true)
switch=blah: The switch is ON (blah)

**Comment by pilou-** [comment]
@fthommen could you specify how you set `switch` value in the inventory (paste inventory content and filename) ?

I am not able to reproduce this issue defining the `switch` variable in an YAML file:

```
$ cat switch.yml
---
switch: FALSE

$ ansible-playbook -i localhost -e@switch.yml test.yml
[...]
"cmd": "echo \"The switch is OFF (False)\"",
[...]
```

**Comment by fthommen** [comment]
I do it in the ansible inventory with switch=FALSE (http://docs.ansible.com/ansible/intro_inventory.html#host-variables)

**Comment by pilou-** [comment]
See [25778](https://github.com/ansible/ansible/issues/25778#issuecomment-309014901):
> Variables which are not [behavioral inventory parameters](https://docs.ansible.com/ansible/intro_inventory.html#list-of-behavioral-inventory-parameters) and are defined in an INI-like inventory are interpreted as strings. This doesn't seem [documented](https://docs.ansible.com/ansible/intro_inventory.html), there is an hint in the note [here](https://docs.ansible.com/ansible/playbooks_variables.html#passing-variables-on-the-command-line).

**Comment by fthommen** [comment]
Thanks @pilou- . Very pity and IMHO somehow inconsistent.  In this case - since that seems to be a design decision - please make this issue a documentation issue, not a bug report.

**Comment by fthommen** [comment]
btw I then still wonder, why "False" is interpreted as a boolean....  I can't find the notion of a boolean type in the Jinja documentation at all

**Comment by bcoca** [comment]
You need to specify type on 'consumption' we try to conserve it but both jinja2 and the ini format 'stringify everything'. 

This should give you more predictable results:
``` - shell: "echo \"The switch is {% if switch|bool %}ON{% else %}OFF{% endif %} ({{ switch }})\""```

**Comment by pilou-** [comment]
@fthommen INI parser [tries `ast.literal_eval`](https://github.com/ansible/ansible/blob/43468b825d19c5990c07d19f5f269d8352f084f8/lib/ansible/plugins/inventory/ini.py#L346) for every value and 'stringify' when `literal_eval` fails.

**Comment by bcoca** [comment]
^ note that ast evals use 'python booleans' unlike jinja2 and yaml which use an extensive list.
