### ISSUE TITLE
constants API changing in devel

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#25820]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lookup_plugins

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 26b8f90c9a) last updated 2017/06/17 12:12:20 (GMT +200)
```

##### SUMMARY
In the current devel I'm suddenly getting exceptions from a custom lookup module calling:
`from ansible.constants import p, get_config`

##### STEPS TO REPRODUCE
Create a lookup plugin and call it from a playbook:
Mine looks like this:
```
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

import os
import sys
import requests
import json
from ansible.errors import AnsibleError
from ansible.plugins.lookup import LookupBase
from ansible.constants import p, get_config

try:
    from __main__ import display
except ImportError:
    from ansible.utils.display import Display
    display = Display()

class LookupModule(LookupBase):
    def run(self, terms, variables, **kwargs):
        #<the code>
```

##### EXPECTED RESULTS
It works

##### ACTUAL RESULTS
```
  File "/media/sf_Documents/projects/Ansiblemodules/lookup_plugins/passwordstate.py", line 10, in <module>
    from ansible.constants import p, get_config
ImportError: cannot import name p
```
Note that if I use Ansible 2.3.0 everything works fine.

**Comment by sivel** [comment]
This is a result of https://github.com/ansible/ansible/pull/12797 that changes much of how configure parsing is done

**Comment by bcoca** [comment]
the config API is undergoing major changes, this is not a break in lookup plugins but in your use of the internal API.

**Comment by trondhindenes** [comment]
ok. I'm assuming it's too early to ask for documentation/guidelines for updating my cusom plugins to use the new api.

**Comment by bcoca** [comment]
i hope to have it in such a way that the docs in your plugins declare the config items they need an then the plugin will 'recieve' them (still not sure on delivery method yet).

**Comment by bcoca** [comment]
@trondhindenes added `get_config` back, see if this now works for you again.

**Comment by trondhindenes** [comment]
Yup, I got the stuff I needed, and the new api is super-neat. Thanks!

Closing this.
