### ISSUE TITLE
Please enhance when: to accept a list

### ISSUE THREAD

**Issue by asad-at-srt** [ansible/ansible#2585]
The semantics should be an AND of the items in the list

when:
- expression-1
- expression-2

should be equivalent to:

when: expression-1 and expression-2

Justification:
Long/complex expressions are made eminently more readable by breaking them down into components.
This is quite general, any boolean expression can be transformed into an AND-form with negation: a or b = ^(^a and ^b)

**Comment by mpdehaan** [comment]
I did not expect a lessen on DeMorgan's law on the github tracker today :)

**Comment by mpdehaan** [comment]
given a list doesn't have and/or semantics I think it's still better if we allow the user to put their own ands and ors in.

this was more of a problem when comparisons of different types were required, such as when you needed when_integer and when_string (legacy, in Ansible 1.1).

The generalized "when" should be cool with whatever expression you care to write.
