### ISSUE TITLE
Dynamic inventory shows some internal host incorrectly

### ISSUE THREAD

**Issue by AnthonyWC** [ansible/ansible#25875]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Dynamic inventory (AWS)

##### ANSIBLE VERSION
ansible --version
```
ansible 2.3.0 (devel 444b67ca0c) last updated 2017/03/13 15:44:39 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/library']
  python version = 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
```
##### CONFIGURATION
ec2.ini
``` ini
destination_variable = private_dns_name
vpc_destination_variable = private_ip_address
route53 = True
```
##### OS / ENVIRONMENT
Ubuntu 14.04 but I think that's irrelevant

##### SUMMARY
I am currently using dynamic inventory with ec2.ini set to use private_dns_name & private_ip_address

However certain host in a different subnet are showing up as ip-x.x.x.x.ec2-internal as opposed to just returning their private IP (which they have).  Does anyone have an idea why this is happening?

e.g. I ran a playbook based on tag and some returned incorrectly:

![image](https://user-images.githubusercontent.com/6215805/27298390-6bbf0758-54f6-11e7-9b00-041e78c8812f.png)

```

**Comment by alikins** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

 This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

**Comment by AnthonyWC** [comment]
Are you sure that this is not a bug?  It should return IP address when in fact it did not, that looks like a bug to me.  As the very least it should not be considered abnormal behaviors.
