### ISSUE TITLE
CI warnings encourage terrifying breaches of PEP8 (line break before binary operator)

### ISSUE THREAD

**Issue by michael-dev2rights** [ansible/ansible#25898]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME

pep8 validator 

##### ANSIBLE VERSION

devel / CI 

```
ansible 2.4.0 (mdd_rds_split_fix_new 7e2c4f2cf2) last updated 2017/06/20 10:22:42 (GMT +100)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mikedd/dev/ansible/ansible-add-modules/library']
  ansible python module location = /home/mikedd/dev/ansible/ansible-add-modules/lib/ansible
  executable location = /home/mikedd/dev/ansible/ansible-add-modules/bin/ansible
  python version = 2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

running continous integration in the shippable

##### OS / ENVIRONMENT

multiple / N/A
##### SUMMARY

Warnings like 
```
W503 line break before binary operator
```

encourage bad programming practices (it's not clear what the reason for a following line is if the binary operator is not at the start of the line) 
and are clear breaches of pep8  (https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator) 

##### STEPS TO REPRODUCE

Write some correctly formatted code 

```
this_is_a_very_long_variable_name = 1
and_this_is_another_long_variable_name = 1

this_new_variable_has_an_even_longer_name_than_the_other_two = this_is_a_very_long_variable_name
                                                               + and_this_is_another_long_variable_name
```

and some criminal, illegal, sinful, in breach of PEP8 code: 

```
this_is_a_very_long_variable_name = 1
and_this_is_another_long_variable_name = 1

this_new_variable_has_an_even_longer_name_than_the_other_two = this_is_a_very_long_variable_name +
                                                               and_this_is_another_long_variable_name
```

and then commit to ansible repo

##### EXPECTED RESULTS

The programmers writing code in breach of PEP8 should be admonished for their illegal state of sinful ignomy.

The programmers writing correct code should be encouraged by a lack of warnings.

##### ACTUAL RESULTS

The programmers writing code in breach of PEP8 should are encouraged to continue illegal state of sinful ignomy.

The programmers writing correct code are unjustifiably and unfairly attacked with terrifying warnings suggesting that they should change their code in a way which would be beyond the pale.

**Comment by mattclay** [comment]
This is due to W503 being a default check in pep8. It is ignored by default in pycodestyle, the successor to pep8: https://pypi.python.org/pypi/pycodestyle

W503 will need to be ignored by ansible-test until we migrate from pep8 to pycodestyle.

**Comment by pilou-** [comment]
Related: #25947 (use pycodestyle instead of pep8).

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Style is not a bug.
In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
