### ISSUE TITLE
when host is added to group with add_host, variable inheritance and overrides are broken

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#25894]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

add_host

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### OS / ENVIRONMENT

Debian stretch

##### SUMMARY

When host is added to a "leaf" group with `add_host` module, it does not inherit variables from parent group.
##### STEPS TO REPRODUCE

Suppose we have inventory with three groups in a tree, one host in root group and one variable in branch group:
```
[root-group]
host1
[root-group:children]
branch-group

[branch-group]
[branch-group:vars]
foo=bar
[branch-group:children]
leaf-group

[leaf-group]
```
Runing a role with add_host task:
```
  - name: group selector
    add_host:
      name: "{{ inventory_hostname }}"
      groups: "leaf-group"

  - name: show groups and vars
    debug: 
      msg: "host is in groups: {{ group_names | join(', ') }}. foo={{ foo | default('bummer') }}."
```

##### EXPECTED RESULTS

Same behavior as if host1 was manually listed in `leaf-group` in the inventory.
host1 inherits variable from `branch-group` and debug message states:
```
host is in groups: root-group, leaf-group. foo=bar.
```
##### ACTUAL RESULTS

host1 fails to inherit variable from `branch-group` and debug message states: 

```
host is in groups: root-group, leaf-group. foo=bummer.
```

**Comment by Vladimir-csp** [comment]
I tried to work around this by using add_host to add host to all groups of the branch (`groups: "branch-group","leaf-group"`). But in this case variable defined in `leaf-group` does not override variable from `branch-group`.
Again, if host is listed in groups manually, then inheritance and overrides work as expected. add_host behavior should be the same.

**Comment by jctanner** [comment]
@Vladimir-csp have you tested this with 2.3+ or devel?

needs_info

**Comment by Vladimir-csp** [comment]
Tried with 2.3.1 from ppa. No issue here, it even lists branch groups in `group_names` without explicitly adding host to them.
Sorry for disturbance.
