### ISSUE TITLE
sanity check bin scripts with ansible-test

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#25905]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ansible-test

##### ANSIBLE VERSION

```
devel
```

##### SUMMARY

Enable pep8/sanity/pylint/etc testing on `bin/` files.

Currently we are completely excluding `bin/ansible` and `bin/ansible-connection`.  We should explicitly add these in to our checks.

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by jctanner** [comment]
cc @gundalow @mattclay

**Comment by mattclay** [comment]
This is being fixed by https://github.com/ansible/ansible/pull/28355

**Comment by mattclay** [comment]
Fixed by #28355
