### ISSUE TITLE
openbsd_pkg: add support for pkgname%branch syntax

### ISSUE THREAD

**Issue by landryb** [ansible/ansible#25910]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
openbsd_pkg

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jun 17 2017, 15:16:02) [GCC 4.2.1 20070719 ]

```

##### OS / ENVIRONMENT
OpenBSD -current or 6.1
##### SUMMARY
Trying to use the pkgname%branch syntax fails

##### STEPS TO REPRODUCE

```
ansible -C localhost -m openbsd_pkg -a 'name=openldap-server--%openldap state=installed'
```

##### EXPECTED RESULTS
installing openldap-server 2.44 from the databases/openldap branch. works fine in a shell:
```
#pkg_add -n openldap-server--%openldap
quirks-2.304 signed on 2017-04-02T15:01:33Z
openldap-server-2.4.44p3:icu4c-58.2p0: ok
openldap-server-2.4.44p3:openldap-client-2.4.44p3: ok
openldap-server-2.4.44p3:db-4.6.21p3v0: ok
openldap-server-2.4.44p3:e2fsprogs-1.42.12p4: ok
openldap-server-2.4.44p3: ok

```

##### ACTUAL RESULTS

The openbsd_pkg module errors out.

```
$ansible -C localhost -m openbsd_pkg -a 'name=openldap-server--%openldap state=installed'

localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "unable to parse package name at versionless_match: openldap-server--%openldap"
}

```

**Comment by landryb** [comment]
@eest since you're the maintainer of this module...

**Comment by eest** [comment]
Thanks for notifying me @landryb. This looks like the code path for verifying package name syntax for versionless packages does not properly understand the branch syntax. Currently not close to a proper computer but should be able to investigate in the coming days.

**Comment by eest** [comment]
@landryb: Please give the patch a spin, it should fix your problem.

**Comment by landryb** [comment]
Works for me, thanks !

```
$ansible localhost -b --become-method=doas -m openbsd_pkg -a 'name=openldap-server--%openldap state=installed'
localhost | SUCCESS => {
    "build": false, 
    "changed": true, 
    "name": [
        "openldap-server--%openldap"
    ], 
    "state": "installed"
}
```
