### ISSUE TITLE
yum module problem in version 1.1 working on centos5.x

### ISSUE THREAD

**Issue by alaxli** [ansible/ansible#2597]
in the version 1.1 ,the yum module is rewrited ,and use python module "yum"
import yum
then ,as working on centos5.x, I update python version from 2.4 to 2.6，but the new version python couldnot contain the module "yum", so,when using ansible with yum module, it return "ImportError: No module named yum" 
but with the ansible version 0.6, the yum module donot need "import yum" ,and it works well.
So, it is not compatible on centos5.x with yum module using ansible version 1.1 ?

**Comment by skvidal** [comment]
the yum module wasn't rewritten in 1.1 that I'm aware of.

the problem you're having is that you updated python on centos 5 system from 2.4 to 2.6. Python 2.6 on your  system does not have access to the yum python module.

There's nothing to fix here.

**Comment by mpdehaan** [comment]
yep, agreed, closing this ticket.

**Comment by alaxli** [comment]
Thanks a lot！

**Comment by KyleJamesWalker** [comment]
Note: I had the same error when the default python did not support the yum import and fixed by adding the following to my hosts file:

```
ansible_python_interpreter=/usr/bin/python26
```

Source: http://docs.ansible.com/faq.html#how-do-i-handle-python-pathing-not-having-a-python-2-x-in-usr-bin-python-on-a-remote-machine
