### ISSUE TITLE
Issues when running on OSX

### ISSUE THREAD

**Issue by raul** [ansible/ansible#2606]
As far as I know, `pip` is the recommended way to install python packages and `homebrew` the [recommended approach](http://docs.python-guide.org/en/latest/starting/install/osx.html) to install python on OSX. Combining both with the ansible docs, I've followed [these steps](https://gist.github.com/raul/6c5a99ecb5827bcf55e6) to install ansible on OSX but when running the basic example:

```
ansible -i /tmp/sample-hosts all -m ping
```

It raises the following error:

```
<my-server-ip> | FAILED >> {
    "failed": true, 
    "msg": "Traceback (most recent call last):\n  File \"/home/raul/.ansible/tmp/ansible-1365392547.16-53398321391558/ping\", line 71, in <module>\n    import shlex\nImportError: No module named shlex\n", 
    "parsed": false
}
```

I run `python -c 'import shlex'` successfully, so initially I'm discarding a problem with the python setup and suspect that there is a problem with the way I installed ansible or with ansible itself.

As an alternative, I did `pip uninstall ansible` and tried cloning the project in my home directory and doing `source ./hacking/env-setup`, but it raised the same error. My python skills are too rusty to dig into the problem right now. Can I run something specific to debug it? Any ideas?

**Comment by mpdehaan** [comment]
Q&A really should go to the mailing list, not the bug tracker.

You've got module path issues still.

source ./hacking/env-setup from a git checkout and you should be good to go.

**Comment by mpdehaan** [comment]
BTW, in case you are not aware, this error pertains to 'my-server-ip' and the /usr/bin/python on that box.
If you need to specify another python, set ansible_python_interpreter as per the docs.

**Comment by raul** [comment]
> Q&A really should go to the mailing list, not the bug tracker.

Sorry Michael.

> BTW, in case you are not aware, this error pertains to 'my-server-ip' and the /usr/bin/python on that box.

I didn't noticed it, that's probably the issue – thanks for responding so fast!

**Comment by hyao** [comment]
Had this issue; then find out only python-minimal is installed on remote vm. 

Seems we need a normal python installation with standard modules on the managed vm for ansible to function correctly?
