### ISSUE TITLE
ansible vault enhacement

### ISSUE THREAD

**Issue by johnscancella** [ansible/ansible#26091]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Ansible Vault

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /Users/jscancella/development/repos/lc-prometheus-server/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I would like to be able to use a keychain for managing access to ansible vault encrypted files. This way I don't have to worry about remembering a password and I can securely share it with other developers.

##### STEPS TO REPRODUCE
1. Add your vault password to the system keyring
2. then run
```
ansible-playbook <PLAYBOOK_NAME> --keyring-vault-pass
```

**Comment by alikins** [comment]
There is some support for this already by using ansible vault password scripts and the 'vault-keyring.py` script in contrib/vault (https://github.com/ansible/ansible/blob/devel/contrib/vault/vault-keyring.py)

**Comment by alikins** [comment]
Is the support available via the vault-keyring.py password script sufficient? 

If not, what additional functionality is needed?

**Comment by johnscancella** [comment]
it is sufficient, but feels like a hack. Why do I need to specify a script that then asks the keychain? Why can't that be built in?

**Comment by alikins** [comment]
> Why do I need to specify a script that then asks the keychain? Why can't that be built in?

Mostly to isolate the keychain support so the main app doesnt have hard requirements on the various deps needed to implement keyring support (the deps required by the python 'keyring' module).

There is a config option to specify DEFAULT_VAULT_PASSWORD_FILE to configure it for your environment:

``` ini
[defaults]
vault_password_file = /path/to/vault-keyring.py
```

**Comment by diogobaeder** [comment]
Hi,

Can't the keyring support be built-in, but not having `keyring` or its deps listed as ansible deps as well, and then fail to the user if they don't have `keyring` installed? Then it could be implemented in a way to not bubble up the import error, but rather tell the user to install the keyring and its optional implementations (`keyrings.alt`) if desired.

How does this sound?

**Comment by bendem** [comment]
Come upon this today, I have a small script we have been using for quite a while, it might help others: https://paste.gg/p/bendem/e1dbf689fa7f497b877878346c1b3213

**Comment by bcoca** [comment]
closing as the functionality is already provided via a vault script
