### ISSUE TITLE
delegate_to localhost and local_action both attempt winrm

### ISSUE THREAD

**Issue by nwsparks** [ansible/ansible#26101]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Any

##### ANSIBLE VERSION
```
[ec2-user@ip-10-5-1-169 ansible]$ ansible --version
ansible 2.3.1.0
  config file = /opt/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Sep  1 2016, 22:14:00) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

```
##### CONFIGURATION
Default configuraiton

##### OS / ENVIRONMENT
Ansible host is amazon linux latest ami

##### SUMMARY

When running a play that connects to Windows hosts via dynamic inventory, local actions fail because Ansible attempts to connect to itself with WinRM.

I'm using dynamic inventory, but run into the same issue when using an inventory file.

group_vars/WindowsConnect.yml just contains the WinRM connection details

##### STEPS TO REPRODUCE

```yaml
- hosts: tag_Function_IIS
  serial: 1
  vars_files:
    - group_vars/WindowsConnect.yml
  pre_tasks:
  - local_action: command hostname

  - name: test delegate
    command: hostname
    delegate_to: 127.0.0.1
```

##### ACTUAL RESULTS
```
[ec2-user@ip-10-5-1-169 ansible]$ ansible-playbook deploy-code.yml -vvvv
Using /opt/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: deploy-code.yml *******************************************************************************************************************************************************************************************************************
1 plays in deploy-code.yml

PLAY [tag_Function_IIS] *********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1
<IIS> ESTABLISH WINRM CONNECTION FOR USER: ansible@DOMAIN.COM on PORT 5986 TO IIS
EXEC (via pipeline wrapper)
ok: [IIS]

TASK [command] ******************************************************************************************************************************************************************************************************************************
task path: /opt/ansible/deploy-code.yml:8
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/commands/command.py
<localhost> ESTABLISH WINRM CONNECTION FOR USER: ansible@DOMAIN.COM on PORT 5986 TO localhost
fatal: [IIS]: UNREACHABLE! => {
    "changed": false,
    "msg": "kerberos: authGSSClientStep() failed: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Configuration file does not specify default realm', -1765328160)), ssl: HTTPSConnectionPool(host='localhost', port=5986): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7dad165410>: Failed to establish a new connection: [Errno 111] Connection refused',))",
    "unreachable": true
}

```

**Comment by bcoca** [comment]
does your inventory define localhost or 127.0.0.1?

**Comment by nwsparks** [comment]
It's using dynamic inventory within AWS based on tags and the ec2.py script. I've tried an inventory file though and the behavior is the same.

For the "delegate_to:" I've tried both localhost and 127.0.0.1 and the behavior is the same.

**Comment by bcoca** [comment]
I cannot reproduce the behaviour except when i define `ansible_connection=winrm` for localhost

try this:
```
- hosts: localhost
  gather_facts: false
  tasks:
    - debug: var=vars
```

**Comment by nwsparks** [comment]
Ok thanks. I messed with it some more and it seems that if I remove this 

```
  vars_files:
    - group_vars/WindowsConnect.yml
```

it works. all that is contained in that is the winrm connection info

```
ansible_user: "{{ lookup('env','WINUSER') }}"
ansible_password: "{{ lookup('env','WINPW') }}"
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_realm: "{{ win_domain_name }}"
ansible_winrm_server_cert_validation: ignore

```

Instead I moved it to group_vars/tag_Function_IIS.yml  and it now works as expected. Not sure if this is a bug still or expected behavior.

I'm guessing the difference between the working and non-working methods are that "local_action" and "delegate_to" are doing their own variable lookups instead of using what matches "hosts: tag_Function_IIS"?

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

You should not be including `group_vars` that way, they are automatic and should be included if the host is in that group.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
