### ISSUE TITLE
apt module upgrade & update_cache

### ISSUE THREAD

**Issue by mhofstra** [ansible/ansible#2611]
The apt module in 1.1 and current git fails to do a full upgrade combined with an update_cache. It seems logical to me that you might want to first update and then do the upgrades.

(-XXX-@X)[~]$ ansible server -vvv -m apt -a "upgrade=yes update_cache=yes" --sudo
<server> ESTABLISH CONNECTION FOR USER: -XXX- on PORT 22 TO server
<server> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1365431712.15-54651301141473 && chmod a+rx $HOME/.ansible/tmp/ansible-1365431712.15-54651301141473 && echo $HOME/.ansible/tmp/ansible-1365431712.15-54651301141473'
<server> REMOTE_MODULE apt upgrade=yes update_cache=yes
<server> PUT /tmp/tmpRoWfLx TO /home/-XXX-/.ansible/tmp/ansible-1365431712.15-54651301141473/apt
<server> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=jkmszngggdynbrkfpbbbuzeurmbadjbp] password: " -u root /bin/sh -c '"'"' /usr/bin/python /home/-XXX-/.ansible/tmp/ansible-1365431712.15-54651301141473/apt; rm -rf /home/-XXX-/.ansible/tmp/ansible-1365431712.15-54651301141473/ >/dev/null 2>&1'"'"''
server | success >> {
    "changed": false
}

Nothing has been updated after this command. After doing a manual apt-get update on the server:

(-XXX-@X)[~]$ ansible server -vvv -m apt -a "upgrade=yes" --sudo
<server> ESTABLISH CONNECTION FOR USER: mass on PORT 22 TO server
<server> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1365431778.06-229377353249990 && chmod a+rx $HOME/.ansible/tmp/ansible-1365431778.06-229377353249990 && echo $HOME/.ansible/tmp/ansible-1365431778.06-229377353249990'
<server> REMOTE_MODULE apt upgrade=yes
<server> PUT /tmp/tmpaCsxdp TO /home/-XXX-/.ansible/tmp/ansible-1365431778.06-229377353249990/apt
<server> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=seayvaoepplikfrnuiavtymnqhptfwfi] password: " -u root /bin/sh -c '"'"' /usr/bin/python /home/-XXX-/.ansible/tmp/ansible-1365431778.06-229377353249990/apt; rm -rf /home/-XXX-/.ansible/tmp/ansible-1365431778.06-229377353249990/ >/dev/null 2>&1'"'"''
server | success >> {
    "changed": true
}

Now the upgrade was successful.

**Comment by mpdehaan** [comment]
ok, thanks

**Comment by mpdehaan** [comment]
recent changes to apt module pushed that should address the different upgrade types

**Comment by srgvg** [comment]
Yes, the module in 1.1 would allways exit after "update_cache". Now it will also upgrade, if requested.
