### ISSUE TITLE
Variable is not set if interpolation is used in lookup filename and in the read file

### ISSUE THREAD

**Issue by ojab** [ansible/ansible#26118]
##### ISSUE TYPE
 - Bug repors

##### COMPONENT NAME
Unfortunately dunno

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### CONFIGURATION
Nothing changed from stock fedora-25 version

##### OS / ENVIRONMENT
Fedora Workstation 25, `dnf install ansible`.

##### SUMMARY
Variable is not set if interpolation is used in filename for lookup.

##### STEPS TO REPRODUCE
`playbooks/deploy-consul.yml`:
```yaml
---
- name: Deploy consul
  hosts: localhost
  roles:
    - consul
```
`playbooks/roles/consul/secrets/staging.yml`:
```yaml
key: "{{ some_key }}"
```
`playbooks/roles/consul/tasks/main.yml`:
```yaml
---
- name: Load data
  set_fact:
    one_secret: "{{ lookup('file', 'secrets/{{ env }}.yml') }}"
    two_secret: "{{ lookup('file', 'secrets/staging.yml') }}"

- debug: var=one_secret
- debug: var=two_secret
```
run with `ansible-playbook playbooks/deploy-consul.yml -e env=staging`

##### EXPECTED RESULTS
Both one_secret and two_secret are set.

##### ACTUAL RESULTS
```
TASK [consul : Load data] *****************************************************************************************
task path: /tmp/ansible_test/playbooks/roles/consul/tasks/main.yml:2
looking for "secrets/staging.yml" at "/tmp/ansible_test/playbooks/roles/consul/files/secrets/staging.yml"
looking for "secrets/staging.yml" at "/tmp/ansible_test/playbooks/roles/consul/secrets/staging.yml"
File lookup using /tmp/ansible_test/playbooks/roles/consul/secrets/staging.yml as file
looking for "secrets/staging.yml" at "/tmp/ansible_test/playbooks/roles/consul/files/secrets/staging.yml"
looking for "secrets/staging.yml" at "/tmp/ansible_test/playbooks/roles/consul/secrets/staging.yml"
File lookup using /tmp/ansible_test/playbooks/roles/consul/secrets/staging.yml as file
ok: [localhost] => {
    "ansible_facts": {
        "one_secret": "key: \"{{ some_key }}\"",
        "two_secret": "key: \"{{ some_key }}\""
    },
    "changed": false
}

TASK [consul : debug] *********************************************************************************************
task path: /tmp/ansible_test/playbooks/roles/consul/tasks/main.yml:8
ok: [localhost] => {
    "one_secret": "VARIABLE IS NOT DEFINED!"
}

TASK [consul : debug] *********************************************************************************************
task path: /tmp/ansible_test/playbooks/roles/consul/tasks/main.yml:9
ok: [localhost] => {
    "two_secret": "key: \"{{ some_key }}\""
}
META: ran handlers
META: ran handlers
```

**Comment by krzysztof-magosa** [comment]
You need to replace `"{{ lookup('file', 'secrets/{{ env }}.yml') }}"` to `"{{ lookup('file', 'secrets/' ~ env ~'.yml') }}"` and it should work.

**Comment by ojab** [comment]
Thanks a lot! Tilda notation fixed the issue.
But I still don't understand why it works if interpolation is removed from the target file or `{{}}` interpolation isn't used in `lookup` :/

**Comment by ojab** [comment]
...and it seems that I can't find docs google for tilda+ansible/tilda+jinja/etc, could you please point me to the docs?

**Comment by ojab** [comment]
whoops, found it http://jinja.pocoo.org/docs/2.9/templates/#other-operators

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

In any case, you don't stack `{{ }}`, just use concatenation as others have noted above.

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by ojab** [comment]
But why one_secret is set correctly and why debug of `Load data` task says that `two_secret` is actually set?
Still looks like a bug for me.
