### ISSUE TITLE
Regression when playbook including playbook with task includes + with_items

### ISSUE THREAD

**Issue by gw0** [ansible/ansible#2612]
I think I found a regression in Ansible 1.2 develop branch. Afaik the following worked in the 1.1 develop branch around 1 week ago.

__test_site.yml_:

```

---
- include: _test_playbook.yml
```

__test_playbook.yml_:

```

---
- hosts: all
  tasks:
    - include: _test_task.yml name=${item}
      with_items:
        - foo
        - bar
```

__test_task.yml_:

```

---
- debug: msg="name is ${name}"
```

Results when running `ansible-playbook -v _test_site.yml` are not as expected:

```
TASK: [debug msg="name is "] **************************************************
ok: [xxx] => (item=foo) => {"item": "foo", "msg": "name is "}

TASK: [debug msg="name is "] **************************************************
ok: [xxx] => (item=bar) => {"item": "bar", "msg": "name is "}
```

Result when running `ansible-playbook -v _test_playbook.yml` are as expected:

```
TASK: [debug msg="name is foo"] ***********************************************
ok: [xxx] => (item=foo) => {"item": "foo", "msg": "name is foo"}

TASK: [debug msg="name is bar"] ***********************************************
ok: [xxx] => (item=bar) => {"item": "bar", "msg": "name is bar"}
```

**Comment by mpdehaan** [comment]
include + with_items is important for some cases so we should fix this, but it can also be confusing.

I generally like the idea of icnluding the $items loops inside the individual tasks that are included.
- action: bfoo
   with_items: $users

etc

**Comment by mpdehaan** [comment]
see above fix
