### ISSUE TITLE
lvol doesn't work 

### ISSUE THREAD

**Issue by VampireJason** [ansible/ansible#2614]
When I try to use ansible-playbook to create lv to another server, the problem as below;

ansible-playbook test.yml -i custom_hosts

PLAY [test] *******************************************************************

GATHERING FACTS ***************************************************************
ok: [10.110.10.44]

TASK: [test] ******************************************************************
failed: [10.110.10.44] => {"err": "/bin/sh: lvs: command not found\n", "failed": true, "rc": 127}
msg: Volume group domovg does not exist.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
10.110.10.44               : ok=1    changed=0    unreachable=0    failed=1

anyone can help?

**Comment by bcoca** [comment]
So a couple of guesses  either you don't have the lvm installed on the
target  or the lvs executable isn't in your path (/sbin/lvs in my case),
try using -K (sudo) as /sbin should be in root's path.
