### ISSUE TITLE
Feature Request: host flag for ansible-playbook

### ISSUE THREAD

**Issue by xamox** [ansible/ansible#2615]
It would be nice to specify or override the host using a flag for playbooks instead of just having to create hosts file and using -i to point to it when running the playbook.

**Comment by bcoca** [comment]
already exists:

ansible-playbook  -i 'myhost,' playbook.yml

trailing , is needed.

**Comment by mpdehaan** [comment]
Yes, it is a list of hosts seperated by commas, if there is one host it needs to end in a comma.
