### ISSUE TITLE
UnboundLocalError: local variable 'f' referenced before assignment

### ISSUE THREAD

**Issue by l0neranger** [ansible/ansible#2618]
Version: 1.2
SHA: 917704ee3aceb22e3d453b74e3dd9f969558af98
Module: authorized_key
Server/Client OS: Debian

When using the authorized_key module both in a playbook or running it manually the authorized_key module fails with the following message:

invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1365459042.26-247034169035691/authorized_key", line 1053, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1365459042.26-247034169035691/authorized_key", line 215, in main
    results = enforce_state(module, module.params)
  File "/root/.ansible/tmp/ansible-1365459042.26-247034169035691/authorized_key", line 190, in enforce_state
    writekeys(module, keyfile(module, user, write, path, manage_dir), keys)
  File "/root/.ansible/tmp/ansible-1365459042.26-247034169035691/authorized_key", line 135, in keyfile
    f.close()
UnboundLocalError: local variable 'f' referenced before assignment

This worked with ansible version 1.1 build. Did something change with the way authorized_key modules works? This is what I have as a task in a playbook:

<pre>
  - name: add ssh auth key for test
    authorized_key: user=test key="ssh-rsa BLAHBLAHBLAHBLAH test"
</pre>

**Comment by mpdehaan** [comment]
ok.

**Comment by fcambus** [comment]
Experiencing the same issue.

Actually, this seems to happen when there is no .ssh directory in the user's home directory.

**Comment by mmercerpdb** [comment]
I have seen this error recently as well (only in recent devel pulls, post 1.1).  It seems you can work around by adding in an extra task to ensure that there is a .ssh directory before running the authorized_key module, but this does extend operations time and makes for a kludgy feeling

**Comment by l0neranger** [comment]
In my playbook, I have a create user task using the "user" module right before the "authorized_key" task. I'm guessing something changed with the "user" module then? It doesn't create the .ssh directory by default or may be theres a race condition? I know these questions might be OS specific so have to do some more testing.

**Comment by mmercerpdb** [comment]
I am in the same situation.  On Ubuntu {10,12}.04.

My workaround is to use the file plugin and ensure that /home/user/.ssh state=directory occurs before the actual auth key occurs:

file: path=/home/user/.ssh owner=user group=user mode=0700 state=directory

(I have user set via a list and run it through with_items)

It seems to be working for me, at least until we figure out what broke this.

**Comment by mmercerpdb** [comment]
Looking at the authorized_key module:

```
if manage_dir in BOOLEANS_TRUE:
    if not os.path.exists(sshdir):
        os.mkdir(sshdir, 0700)
        if module.selinux_enabled():
            module.set_default_selinux_context(sshdir, False)
    os.chown(sshdir, uid, gid)
    os.chmod(sshdir, 0700)
```

It _should_ be creating the sshdir if it doesnt exist prior to placing the file.  The above specifically checks to see if the authorized_keys module manages the ssh directory.  Its an easy fix to get the bug working, remove manage_dir check, increase tab on os.chown and os.chmod
Done.

**Comment by mpdehaan** [comment]
I have pushed a fix for this on the development branch.
