### ISSUE TITLE
Update docs for module set_stats to say how it is displayed

### ISSUE THREAD

**Issue by Aralin** [ansible/ansible#26191]
Issue Type: Documentation Report
Component name: module/set_stats
Ansible Version: 2.3

Summary:
Please update the documentation for set_stats module to say to tell the user that to display the stats collected by the set_stats module, the SHOW_CUSTOM_STATS has to be set to true by either "show_custom_stats=true" in the ansible.cfg or by setting ANSIBLE_SHOW_CUSTOM_STATS

Expected Results:
Learn from documentation how to display stats collected by set_stats

Actual Results:
Hours of investigative work in source code.

**Comment by jhawkesworth** [comment]
Thanks for digging in and find this out - I had been wondering how to get them to display too.

**Comment by samdoran** [comment]
@Aralin Please let me know if #26250 fixes your issue.
