### ISSUE TITLE
Update installation documentation for MacOS

### ISSUE THREAD

**Issue by dashfwd** [ansible/ansible#2619]
In http://ansible.cc/docs/gettingstarted.html, the instructions for "If you wish to install the latest build via the MacPorts system from a git checkout, run" didn't work for me.

While the file `ansible/packaging/macports/README.md` in the source code gives somewhat better instructions, it still will end up getting you the latest code from the "devel" branch.  There are currently no instructions on how to get a specific build (release1.1 for example) on the Mac.

Can you update both:
http://ansible.cc/docs/gettingstarted.html
and 
`ansible/packaging/macports/README.md`

with the updated documentation below, which fixes those issues.  (I've ran though these instructions on a new box and they work perfectly for me on Mountain Lion, and probably will for older OSX releases too).
## Updated instructions

**Via MacPorts**
An OSX port is available via MacPorts.  You can install the latest stable version or a specific release.

**To install the stable version of Ansible from MacPorts** (this is the recommended way).
First, install MacPorts as described on http://www.macports.org if you haven't already done so.  Note that you may need to upgrade XCode too if you have an older version.

Then open a new Terminal window and run:
`$ sudo bash`
`# port -v selfupdate` (this is to update to the latest list of ports)
`# sudo port install ansible`

**Installing a specific release/git branch**
After doing the steps above, if you wish to install different build via the MacPorts system from a git checkout, do these additional steps (based on information found in http://guide.macports.org/#development.local-repositories):
`# cd /tmp`
`# git clone git://github.com/ansible/ansible.git`
`# cd /tmp/ansible/packaging/macports`

By default, the latest code on the 'devel' branch will be installed.  If you'd rather install a specific release / git branch, edit the file `/tmp/ansible/packaging/macports/sysutils/ansible/Portfile` and change this line:

`version         devel`

to the name of the git branch you want to use.  For example, if you want the `release1.1` git branch, edit that line as follows:

`version         release1.1`

Next you will edit the `/opt/local/etc/macports/sources.conf` file to point to a directory in the cloned git repository.  In that file, add the line:
`file:///tmp/ansible/packaging/macports`

right **before** (not after, before) the last line in the file, which is this one:
`rsync://rsync.macports.org/release/tarballs/ports.tar [default]`

Now you'll run these commands in terminal to tell MacPorts to use the new Portfile, and reinstall Ansible:
`# portindex`
`# port uninstall ansible`
`# port install ansible`

At this point open a new Terminal window (don't reuse the existing window, open a new one) to start using Ansible:
`$ ansible --version`

---

Thanks much.

**Comment by mpdehaan** [comment]
BTW, did you know you can submit patches to the doc site?

docsite files are in source control, see docsite/rst/*.rst if you want to submit changes

I actually just run from source and install deps from pip when I do OS X.  It's easier, and I think we'll just show people how to do that.

**Comment by dashfwd** [comment]
I didn't know about the docsite files, thanks for pointing that out.  I can update both in a branch with my version of the instructions if you like, but if you have a better process maybe that should be documented instead.

Also, is release1.1 considered stable at this point, and if so, could MacPorts be updated to be that release?

**Comment by mpdehaan** [comment]
I don't maintain the macports release, I recommend installing from source.
