### ISSUE TITLE
LocalConnection in Connection class error

### ISSUE THREAD

**Issue by emmatt** [ansible/ansible#262]
I'm doing this on the devel branch.

Trying to run a playbook with "connection: local" results in:

unreachable: [localhost] => Traceback (most recent call last):
  File "/opt/ansible/lib/ansible/runner.py", line 538, in _executor
    (host, ok, data, err) = self._executor_internal(host)
  File "/opt/ansible/lib/ansible/runner.py", line 559, in _executor_internal
    conn = self.connector.connect(host, port)
  File "/opt/ansible/lib/ansible/connection.py", line 54, in connect
    conn = LocalConnection(self.runner, host, None)
TypeError: __init__() takes exactly 3 arguments (4 given)

Maybe there is something incoming here but the class definition for LocalConnection in connection.py doesn't give any clues. Here was the short patch to line connection.py line 53 to get working again.

> diff --git a/lib/ansible/connection.py b/lib/ansible/connection.py
> index ca85cdc..6192eba 100644
> --- a/lib/ansible/connection.py
> +++ b/lib/ansible/connection.py
> @@ -51,7 +51,7 @@ class Connection(object):
>      def connect(self, host, port=None):
>          conn = None
>          if self.transport == 'local' and self._LOCALHOSTRE.search(host):
> -            conn = LocalConnection(self.runner, host, None)
> -            conn = LocalConnection(self.runner, host)
>        elif self.transport == 'paramiko':
>            conn = ParamikoConnection(self.runner, host, port)
>        if conn is None:

**Comment by mpdehaan** [comment]
already fixed on devel
