### ISSUE TITLE
Add a documention chapter about how to use the Ansible Vagrant plugin in Vagrant 1.2

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#2621]
cc @commandtab

**Comment by mpdehaan** [comment]
Just making a note, I would love to have a basic writeup for the docs site.

**Comment by command-tab** [comment]
Cool, I'll see if I can put something together.

**Comment by mpdehaan** [comment]
I'll let you do this if you want, but I'm going to go ahead and close the ticket.  It seems we could just link to the docs on the vagrantup page somewhere in the getting started area if you want to do that.

**Comment by command-tab** [comment]
Looping back around to this issue on my to-do list, and on second thought it seems like perhaps a short blurb and a link to the Vagrant docs would probably be best. Those docs are kept up to date, and then we won't have duplicate content spread around.
