### ISSUE TITLE
Unable to use privilege escalation when calling playbook from python

### ISSUE THREAD

**Issue by SideHustleDev** [ansible/ansible#26246]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
become, become_user, become_method

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides

```

##### CONFIGURATION
host_key_checking=False

##### OS / ENVIRONMENT
Ubuntu 14.04
Python 2.7.6

##### SUMMARY
I am calling an ansible playbook programmatically from a Python script. I ssh into each host as a specific user with a specific private key file. In the playbook I need to run certain commands as root and to do that I need to enable become. 

I cannot enable become when calling the playbook because it does not attempt to ssh into the hosts as the user I need it too, I believe it tries to do it as root. If I try entering become: True in the playbook I get NoneType object error probably because I can't enable it when I pass it into the options. When I fill out become, become_user, become_method in the playbook I get a timeout no matter how long I set the timeout. 

I believe I need to enable become when passing in my options, but doing so prevents me from ssh-ing into my hosts. If there is a way out of this paradox please let me know.

[Potentially relevant bug report ](https://bugzilla.redhat.com/show_bug.cgi?id=1445712)

##### STEPS TO REPRODUCE
![help](https://user-images.githubusercontent.com/7435273/27692883-d224ed48-5cb5-11e7-979e-974fe3dd2d29.PNG)

```
- name: VM Configurations
  hosts: thehosts

  vars:
     ansible_ssh_private_key_file: "/key/file/path"

- name: Set file permissions
        become: True
        file: path=/etc/dir/file mode=0755

- name: Any task with become
       become: True

```

##### EXPECTED RESULTS

I would be able to run a task with sudo/as root 

##### ACTUAL RESULTS

If I ran playbook with 'become:True', 'become_user: root', 'become_method: su' at top level of playbook, in a task or with becomes enabled in options I get the first error

If I run with becomes turned off in options, with first task being shell: "sudo yum -y install package" (it works) I get the second error

```
TASK [setup] *******************************************************************
fatal: [10.114.2.14]: FAILED! => {"failed": true, "msg": "Timeout (32s) waiting for privilege escalation prompt: "}
fatal: [10.114.2.6]: FAILED! => {"failed": true, "msg": "Timeout (32s) waiting for privilege escalation prompt: "}
---------------------------------------------------------------------------------------------
TASK [setup] *******************************************************************
ok: [10.114.2.14]
ok: [10.114.2.6]

TASK [Install Package] ************************************************************
changed: [10.114.2.14]
 [WARNING]: Consider using 'become', 'become_method', and 'become_user' rather than running sudo

changed: [10.114.2.6]

TASK [Copy a file] *********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not iterable
fatal: [10.114.2.6]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not iterable
fatal: [10.114.2.14]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a developer question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible-devel on irc.freenode.net   
   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
