### ISSUE TITLE
Template with lookup plugin gives wrong failure message if binary files are involved

### ISSUE THREAD

**Issue by emmanuel-oginni** [ansible/ansible#26256]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- template with lookup plugin to fetch files

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
 
```

##### CONFIGURATION

default settings
##### OS / ENVIRONMENT

CentOS Linux release 7.2.1511 (Core)
##### SUMMARY

Templating fails with wrong message given below if there is a binary file. This occur when template module is used with lookup plugin.
The file that caused the failure is not indicated

##### STEPS TO REPRODUCE

Include a binary file in list of files to be templated., which is fetched using lookup plugin.

```
- name: Templates all .j2 files recursively
  template: src={{ item }} dest={{base_package_dir}}/{{release_no}}/{{build_no}}/{{ item|replace(autodeploy_path , 'config') }}  
  with_items: "{{ lookup('pipe', 'find '+ autodeploy_path + '  -type f -regextype posix-egrep -regex \".*\\.(j2)$\"').split('\n') }}"
  tags: property_template_2

```

##### EXPECTED RESULTS

Expected that Ansible will indicate the file that caused the template failure. e.g. Error templating file binaryxxxx.file
##### ACTUAL RESULTS

The task fails, other files are properly templated but the files that have problems are not indicated.

```
[WARNING]: Failure using method (v2_runner_item_on_failed) in callback plugin (<ansible.plugins.callback.default.CallbackModule object at
0x359afd0>): 'ascii' codec can't decode byte 0xef in position 101: ordinal not in range(128)
```

**Comment by jctanner** [comment]
resolved_by_pr https://github.com/ansible/ansible/pull/26288
