### ISSUE TITLE
playbook: make hosts optional

### ISSUE THREAD

**Issue by sgohl** [ansible/ansible#26252]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ansible-playbook

##### ANSIBLE VERSION
```
ansible-playbook 2.3.1.0
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### SUMMARY

In my use case playbooks are almost always not host-dependent.
I write all sorts of general tasks and when I want to run them, I decide on which host/group.
But playbooks require the hosts option. It is very insecure to put "hosts: all" and then limit them, because if I forget to pass the --limit option, unwanted actions could happen.

Suggestion: add a special option value like "hosts: none" and make --limit just run that on the given hosts

**Comment by resmo** [comment]
This could already be done by templating hosts

~~~
 $ cat test.yml 
---
- hosts: "{{ hosts | default('none') }}"
  gather_facts: no
  tasks:
  - debug: msg="ok"
~~~

and passing extra vars

~~~
 ansible-playbook test.yml -i hosts -e "hosts=one"
~~~

**Comment by sgohl** [comment]
thanks! this wasn't obvious via docs.

**Comment by resmo** [comment]
Luckily (and unfortunately for the docs creators), ansible is very adaptable and it is hard to document every possible way to do something.

So let's turn this feature request in: Make the default host group configurable by ansible.cfg.

**Comment by bcoca** [comment]
We used to have that feature, no one used it. It actually broke and I only noticed 9 versions later when doing code clean up.

**Comment by resmo** [comment]
@bcoca Impressive, I wasn't aware of that. So this "feature" is gone now? I also assume it is not the feature everyone is waiting for so tempting would just fit for those users, need something different than all group.

**Comment by bcoca** [comment]
From ansible.cfg before I removed it, long after the actual feature stopped working.
```
# the default pattern for ansible-playbooks ("hosts:")
pattern = *
```

Mostly because people just used `hosts: {{ target|default('all') }} ` or similar and never bothered using this.

**Comment by resmo** [comment]
Perfect, let's close this request. 

Thanks all.
