### ISSUE TITLE
postgresql_user exception with PostgreSQL 8.x (needs info)

### ISSUE THREAD

**Issue by EvanDotPro** [ansible/ansible#2626]
Using PostgreSQL 8.4.13 (CentOS 6).

When using the postgresql_user module, it works for the initial user creation, however when the playbook is ran again once the user exists, it resulted in an error:

```
fatal: [127.0.0.1] => failed to parse: Traceback (most recent call last):
  File "/tmp/ansible-1365514683.06-249630031833156/postgresql_user", line 1069, in <module>
    main()
  File "/tmp/ansible-1365514683.06-249630031833156/postgresql_user", line 402, in main
    changed = user_alter(cursor, user, password, role_attr_flags)
  File "/tmp/ansible-1365514683.06-249630031833156/postgresql_user", line 156, in user_alter
    cursor.execute(select, {"columns": columns, "user": user})
psycopg2.ProgrammingError: column "rolreplication" does not exist
LINE 1: ...,rolinherit,rolcreaterole,rolcreatedb,rolcanlogin,rolreplica...
                                                             ^
```

Not sure if this is a bug with my local environment, pypostgres, or the postgresql_user module itself. I haven't dug into the code yet.

**Comment by mpdehaan** [comment]
I'm using CentOS 6 and was ok with the postgresql module. 

Please let me know more info.

https://github.com/ansible/ansible-commander/blob/master/app_setup/setup.yml

**Comment by mpdehaan** [comment]
Still need more info.  Please supply details about your playbook and I can reopen this, thanks!

**Comment by EvanDotPro** [comment]
Well, I finally revisited this, and was unable to reproduce, plus we ended up upgrading to Postgres 9.x, so it's a non-issue now. If I ever do come across it again, I'll try to collect more information up front to be a little more helpful. :smile:
