### ISSUE TITLE
win_updates; add comprehensible messages when Windows Update Client fails

### ISSUE THREAD

**Issue by jhawkesworth** [ansible/ansible#26277]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
win_updates
```

##### CONFIGURATION

Stock configuration
##### OS / ENVIRONMENT

ansible 2.3.0.0
  config file = /home/SMCORP/jhawkesworth/ansible/ansible.cfg
  configured module search path = [u'/home/SMCORP/jhawkesworth/ansible/library']
  python version = 2.7.5 (default, Sep 15 2016, 22:37:39) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

Target: Windows Server 2012 R2 (but target not likely relevant)

##### SUMMARY

When windows update client fails, raw COM errors are returned.  See ansible #26238 for an example.
Lots of things could cause windows update client to fail - network errors, windows update server outages.

The suggestion I'm making here is to wrap any errors from the windows update client so ansible users have a reasonable suggestion of what is wrong and what could be tried next.

For example, returning
'It appears Windows Update Client is having problems.  Try running Windows Update interactively on the affected host, or try again later.  Original exception message was .. (original error would go here)
would be an improvement.

##### STEPS TO REPRODUCE

N/A

```yaml

```

##### EXPECTED RESULTS

When win_updates fails due to a windows update client problem, suggest what can be done about it.

##### ACTUAL RESULTS

see error message reported in #26238 

```
fatal: [windows_host]: FAILED! => {"changed": false, "error": "Exception calling "Search" with "1" argument(s): "Exception from HRESULT: 0x8024401C"", "failed": true, "location: "at DoWindowsUpdate, : line 72\r\nat , : line 222"}
```

**Comment by ShachafGoldstein** [comment]
Still relevant to current versions?

**Comment by jborean93** [comment]
Yes it is but there really is no way to automatically get the error message without adding our own manual conversions.

**Comment by ShachafGoldstein** [comment]
Trying to follow this lead: https://docs.microsoft.com/en-us/cpp/cpp/com-error-class?view=vs-2019

**Comment by jborean93** [comment]
There is not much we can do here as there's no way (that I know of) to translate COM error codes to a message for WUA. If there is a way around this I am happy to see it but for now I am closing this as something we can't fix.
