### ISSUE TITLE
Cryptography dependency breaks deb installation for Ubuntu 14

### ISSUE THREAD

**Issue by rmfitzpatrick** [ansible/ansible#26305]
With the addition of https://github.com/ansible/ansible/commit/e238ae999b90b771f662ac15e6cceff8aa0b721f the deb built from `make deb` creates a package with these dependencies:

```
Package: ansible
Version: 2.4.0-100.git201706301418.5c374cd.HEAD~trusty
Architecture: all
Maintainer: Ansible, Inc. <info@ansible.com>
Installed-Size: 18888
Depends: python-jinja2, python-yaml, python-paramiko, python-httplib2, python-six, python-crypto (>= 2.6), python-setuptools, sshpass, python:any (<< 2.8), python-cryptography, python-pkg-resources, python, python:any (>= 2.7.5-5~)
```

`python-cryptography` is not available as a deb in Ubuntu 14 and pip installations are not recognized as satisfying the dependency:

```
root@node:~# apt-get install ansible
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ansible : Depends: python-cryptography but it is not installable
E: Unable to correct problems, you have held broken packages.
```

@abadger has suggested that the cryptography dependency can be avoid w/ `ANSIBLE_CRYPTO_BACKEND=pycrypto` on `setup.py install` invocations but setting this env var for the deb-src target doesn't remove the dependency.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Makefile, `make deb`

##### ANSIBLE VERSION
devel

##### CONFIGURATION
```
 deb-src: debian
 	@for DIST in $(DEB_DIST) ; do \
-	    (cd deb-build/$${DIST}/$(NAME)-$(VERSION)/ && $(DEBUILD) -S) ; \
+	    if test $${DIST} = trusty ; then \
+	        CRYPTO_BACKEND=pycrypto ; \
+	    else \
+	        CRYPTO_BACKEND=cryptography ; \
+	    fi ; \
+	    (export ANSIBLE_CRYPTO_BACKEND=$${CRYPTO_BACKEND} && cd deb-build/$${DIST}/$(NAME)-$(VERSION)/ && $(DEBUILD) -S) ; \
 ```

##### OS / ENVIRONMENT
Ubuntu 14

##### STEPS TO REPRODUCE

Attempt to install a devel deb on ubuntu 14

**Comment by abadger** [comment]
I'm not entirely sure about the debian makefile rules but perhaps deb-src is not enough?  If the deb-src target is building the source deb but  not the deb that's being installed on the end user systems then it won't be enough.

**Comment by abadger** [comment]
Looking at the jenkins job that I think is driving this, it seems like it calls make deb-upload.  So maybe the change has to be made in the deb target rather than the deb-src target.

**Comment by rmfitzpatrick** [comment]
Thanks, @abadger, I was able to get this to work w/ https://github.com/ansible/ansible/pull/26500

```
root@b6a23008a2d0:/ansible/reprepro/dists/trusty/main/binary-amd64# cat Packages
Package: ansible
Version: 2.4.0-100.git201707060000~trusty
Architecture: all
Maintainer: Ansible, Inc. <info@ansible.com>
Installed-Size: 18943
Depends: python-jinja2, python-yaml, python-paramiko, python-httplib2, python-six, python-crypto (>= 2.6), python-setuptools, sshpass, python, python:any (<< 2.8), python:any (>= 2.7.5-5~), python-pkg-resources
```

**Comment by rmfitzpatrick** [comment]
Closed PR as it doesn't resolve issue for all affected distros or use proper deb build technique.  I can research a method that satisfies @bcoca's points but if anyone w/ more experience can take a look at this it'd be greatly appreciated.

**Comment by abadger** [comment]
note: If we need to get this working, I'm okay with merging PR #26500 as a fix for now and when someone with deb building experience has time, getting a better fix in later.

**Comment by ghjm** [comment]
See https://github.com/ansible/ansible/pull/26705 @rmfitzpatrick @abadger @bcoca

**Comment by ghjm** [comment]
Here's a better fix @rmfitzpatrick @abadger @bcoca
