### ISSUE TITLE
Ansible modules works on all hosts except few

### ISSUE THREAD

**Issue by beingnishas** [ansible/ansible#26311]
[https://github.com/ansible/ansible/issues/5725](url)
I am getting error
192.168.xx.xx | UNREACHABLE! => {
    "changed": false,
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo $HOME/.ansible/tmp/ansible-tmp-1498903022.87-229814248506479 `\" && echo ansible-tmp-1498903022.87-229814248506479=\"` echo $HOME/.ansible/tmp/ansible-tmp-1498903022.87-229814248506479 `\" ), exited with result 1",
    "unreachable": true
}

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Any module
##### ANSIBLE VERSION

```
 ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/my_modules']


```

##### OS / ENVIRONMENT

NA
##### SUMMARY

I have a inventory with around 10 hosts and my playbook runs on all except 2. I am able to login to those 2 hosts passwordlessly from Ansible Server. But when I run the playbook or even a simple ping module or even command module like I get error:

 ansible -i myinventory unreachable -m ping -vvvvvv
 ansible -i myinventory unreachable -m command -a "ls /home/myuser" -e "remote_tmp=/tmp/.ansible-myuser/tmp"

Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/system/ping.py
<192.168.x.xxx> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.x.xxx> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<192.168.x.xxx> SSH: ansible_password/ansible_ssh_pass not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<192.168.x.xxx> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<192.168.x.xxx> SSH: PlayContext set ssh_common_args: ()
<192.168.x.xxx> SSH: PlayContext set ssh_extra_args: ()
<192.168.x.xxx> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/home/webtech/.ansible/cp/ansible-ssh-%h-%p-%r)
<192.168.x.xxx> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/webtech/.ansible/cp/ansible-ssh-%h-%p-%r 192.168.x.xxx '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1498903623.29-3475268059842 `" && echo ansible-tmp-1498903623.29-3475268059842="` echo $HOME/.ansible/tmp/ansible-tmp-1498903623.29-3475268059842 `" ) && sleep 0'"'"''
192.168.5.70 | UNREACHABLE! => {
    "changed": false,
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo $HOME/.ansible/tmp/ansible-tmp-1498903623.28-102912985697365 `\" && echo ansible-tmp-1498903623.28-102912985697365=\"` echo $HOME/.ansible/tmp/ansible-tmp-1498903623.28-102912985697365 `\" ), exited with result 1",
    "unreachable": true
}

Whereas I can login passwordlessly with myuser and can create dir in /home/myuser/.ansible even in /tmp

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

Any simple module like ping should return the status reachable

##### ACTUAL RESULTS

192.168.xx.xx | UNREACHABLE! => {
    "changed": false,
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo $HOME/.ansible/tmp/ansible-tmp-1498903623.28-136703981609211 `\" && echo ansible-tmp-1498903623.28-136703981609211=\"` echo $HOME/.ansible/tmp/ansible-tmp-1498903623.28-136703981609211 `\" ), exited with result 1",
    "unreachable": true
}

```

```

**Comment by jctanner** [comment]
@Niceha based on the ssh command in your vvvv output, it doesn't appear as if an ssh password or key was defined in inventory.

```
ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/webtech/.ansible/cp/ansible-ssh-%h-%p-%r 192.168.x.xxx
```

Do you have ssh-agent running on your control host's session? What key is used to authenticate to the remote host? Does ansible authenticate successfully when you defined ansible_ssh_private_key_file in the inventory?

needs_info

**Comment by beingnishas** [comment]
@jctanner yes ssh-agent is running. After a lot of troubleshooting and googling got the issue, it was related to user's shell access. After giving user access to /bin/bash this worked.
