### ISSUE TITLE
backup=yes changed time-stamp of the file

### ISSUE THREAD

**Issue by mmahajan-qasource** [ansible/ansible#26315]
How to take backup of file **without changing its time-stamp** with Ansible playbook? I tried `backup=yes` but the problem is like it changes the time-stamp of the file.

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
backup

##### ANSIBLE VERSION

```
ansible 2.1.2.0

```

##### SUMMARY
How to take backup of file **without changing its time-stamp** with Ansible playbook? I tried `backup=yes` but the problem is like it changes the time-stamp of the file. 

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by jctanner** [comment]
@mmahajan-qasource what module?

needs_info

**Comment by mmahajan-qasource** [comment]
The module is `backup`  which we use to take backup before change in any file 
Example: `lineinfile: dest={{item}} state=absent regexp='TLSv1' **backup=yes**` 
Here we are removing TLSv1 line from Nginx file but before removing we want to take backup of file using `backup=yes`, but the issue is that if we do backup=yes it changes the timestamp of the file which is the problem for me. I don't want timestamp to be changed for my backup files.

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

This is expected, it reflects the time at which the backup was made, this is how the backup function is supposed to work.

You can use your own backup module or  use the `touch` command to change the time of the backup in an additional task.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
