### ISSUE TITLE
One or more SELinux operations fail when path is given in complex args

### ISSUE THREAD

**Issue by dsedivec** [ansible/ansible#2632]
Passing paths as complex args in playbooks makes them end up as unicode instances in the module, as opposed to the str instances you get when using key=value arguments.  selinux.matchpathcon(), and probably other functions in the selinux module, raise TypeError when given unicode instances.

For example, this playbook fails on my CentOS 6 system with SELinux in enforcing mode and python-selinux installed:

```
- hosts: all
  tasks:
    - action: copy
      args:
        src: some_file
        dest: /tmp/some_other_file
```

The exception is as follows:

```
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-1365569148.43-637871259277/copy", line 998, in <module>
    main()
  File "/home/user/.ansible/tmp/ansible-1365569148.43-637871259277/copy", line 142, in main
    module.atomic_replace(dest_tmp, dest)
  File "/home/user/.ansible/tmp/ansible-1365569148.43-637871259277/copy", line 927, in atomic_replace
    context = self.selinux_default_context(dest)
  File "/home/user/.ansible/tmp/ansible-1365569148.43-637871259277/copy", line 409, in selinux_default_context
    ret = selinux.matchpathcon(path, mode)
TypeError: in method 'matchpathcon', argument 1 of type 'char const *'
```

In this example the `path` being passed to matchpathcon is the `dest` argument to the task.  It is unicode and not a str because the complex arguments are passed as JSON, and decoding with Python's json module results in unicode instances.

I don't exactly know if/how this should be fixed.  Is the real problem in python-selinux?  Should Ansible make sure to first convert all potential arguments to selinux functions to strs?  (`dest = str(module.params["dest"])`, and non-ASCII paths be damned?)

**Comment by mpdehaan** [comment]
I would assume it would accept UTF-8 encoded strings and we should just decode them if we get a unicode here.

Thanks for the heads up!
