### ISSUE TITLE
URI module broken

### ISSUE THREAD

**Issue by HanXHX** [ansible/ansible#26352]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
uri

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
```

##### CONFIGURATION
none

##### OS / ENVIRONMENT

* Ansible 2.1 on Debian Jessie (pip)
* Ansible 2.3 on Xubuntu 16.04 (pip)

##### SUMMARY

The uri module crashes.

##### STEPS TO REPRODUCE
```
$ ansible -vv -m uri -a 'uri=https://www.ansible.com/' localhost,
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

localhost | FAILED! => {
    "changed": false, 
    "content": "", 
    "failed": true, 
    "msg": "Status code was not [200]: An unknown error occurred: 'NoneType' object has no attribute 'find'", 
    "redirected": false, 
    "status": -1, 
    "url": null
}

```

##### EXPECTED RESULTS
No error

**Comment by hleb-rubanau** [comment]
For those who will google this error in the need to fix it: module parameter should be _**url**=http://example.com_  and NOT _**uri**=http://example.com_

**Comment by jai1824** [comment]
I am trying to check the status code of a site and i am seeing below error

[user]$ ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
---
- hosts: localhost
  tasks:
     - uri: 
       url: "https://wwww.example.com/programs/software"
       register: result
     - debug: msg="{{ result.status }}"

Seeing below error
failed: [localhost] (item=<html ng-app="ThirdParty" ng-controller="TemplateController" lang="en">) => {"content": "", "failed": true, "item": "<html ng-app=\"ThirdParty\" ng-controller=\"TemplateController\" lang=\"en\">", "msg": "Status code was not [200]: An unknown error occurred: 'NoneType' object has no attribute 'find'", "redirected": false, "status": -1, "url": null}
