### ISSUE TITLE
`become_user: $something` should imply `become: yes`

### ISSUE THREAD

**Issue by dwt** [ansible/ansible#26389]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ansible tasks

##### ANSIBLE VERSION
```
% ansible --version
ansible 2.2.1.0
  config file = /Users/dwt/Code/Projekte/sntl/provisioning/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I just burned another half hour today before I figured out that `become_user: $someone` is not enough to actually trigger the user change, but that I also needed an additional line `become: yes` for it to work.

So here's the idea: why doesn't `become_user: $someone` imply `become: yes`? That would make the playbooks shorter and completely remove that error type. Of course an explicit `become: no` should still override this.

Here's the question: There are very few scenarios where you want `become: no` when you have written `become_user: ...`, but many instances where forgetting the other will lead to wrong behavior (and probably in many instances even a silent error that you can't easily see from the output).

If you are unwilling to add this implication, I strongly urge you to add at least warning output that the user probably forgot to also specify `become: yes`.

##### STEPS TO REPRODUCE
1. add `become_user:  {{some user}}` to an existing step
2. Execute it
3. Scratch your head why it doesn't achieve the desired effect (i.e. fails silently)
4. goto 2

##### EXPECTED RESULTS
It should either just work or emit a warning, as this error is really hard to see.

##### ACTUAL RESULTS
´become_user: $foo` is just silently ignored

**Comment by gundalow** [comment]
Hi
This is by design.

You can have become settings per host
or in config
or in keywords

This allows for customization/overrides while not forcing you to do diff tasks/plays when you have mixed environments.

**Comment by dwt** [comment]
Well, I appreciate that you have many places to set a default.

But still, if there is an explicit setting on a task to `become_user: $foo` but no explicit setting to `become: ...` anywhere, a warning would be really helpful (especially since many commands will just silently do the wrong thing if you forget the `become: yes`.

Or am I missing something important here?

**Comment by bcoca** [comment]
For many people this would be an unwanted warning, the task is doing exactly what you ask of it.

The become_user can be changing the default (root) for the cases in which you set become by host (mixed environments) w/o forcing hosts that do not require it to also use it. 

We agree, it makes less sense in homogeneous environments, but we would not want to penalize those that are in a different situation.
