### ISSUE TITLE
can vmware_vm_facts module return's data have mac address?

### ISSUE THREAD

**Issue by woshihaoren** [ansible/ansible#26386]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
modules/cloud/vmware/vmware_vm_facts.py

##### ANSIBLE VERSION

```
2.3.0
```

##### SUMMARY

mac_address is useful

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

        "test-118": {
            "guest_fullname": "Red Hat Enterprise Linux 6 (64-bit)",
            "ip_address": "10.25.3.118",
            "mac_address": "xx:xx:xx:xx:xx:xx",
            "power_state": "poweredOn"
        }

##### ACTUAL RESULTS

```
        "test-118": {
            "guest_fullname": "Red Hat Enterprise Linux 6 (64-bit)",
            "ip_address": "10.25.3.118",
            "power_state": "poweredOn"
        }
```

**Comment by gundalow** [comment]
@jcpowermac I believe you created this module, though you are not listed as a maintainer in https://github.com/ansible/ansibullbot/blob/master/MAINTAINERS.txt would you like to be?

**Comment by jcpowermac** [comment]
@gundalow I think I used to be.  It would be great if someone else could pick up the maintenance of these modules since VMware is no longer my focus.  Thanks!

**Comment by woshihaoren** [comment]
@gundalow I slove it 
https://github.com/ansible/ansible/pull/26527

**Comment by Akasurde** [comment]
@gundalow We can close this issue as #26527 is merged.
