### ISSUE TITLE
[devel] process vars_files for only hosts in the play

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#264]
reported that it runs against all hosts, though I'm having a hard time believing this.

Anyway, we probably want to cache the loaded files such that we don't need to keep hitting the disk.

**Comment by dcoutu** [comment]
Here's an example of what I see, using a YAML inventory list.

[me@whee lib]$ ~/git/ansible/bin/ansible-playbook sites/dc1/deploy.yml -K
sudo password: 

PLAY [hostk01] ****************************

SETUP PHASE ****************************

ok: [hostk01]

VARIABLE IMPORT PHASE ******************

hosta01: importing sites/dc1/vars/common_vars.yml
hosta01: importing sites/dc1/release.yml
hosta02: importing sites/dc1/vars/common_vars.yml
hosta02: importing sites/dc1/release.yml
hostd01: importing sites/dc1vars/common_vars.yml
hostd01: importing sites/dc1/release.yml
hostd02: importing sites/dc1/vars/common_vars.yml
hostd02: importing sites/dc1/release.yml
hostp01: importing sites/dc1/vars/common_vars.yml
hostp01: importing sites/dc1/release.yml
hostp02: importing sites/dc1/vars/common_vars.yml
hostp02: importing sites/dc1/release.yml
hostb01: importing sites/dc1/vars/common_vars.yml
hostb01: importing sites/dc1/release.yml
hostb02: importing sites/dc1/vars/common_vars.yml
hostb02: importing sites/dc1/release.yml
hostk01: importing sites/dc1/vars/common_vars.yml
hostk01: importing sites/dc1/release.yml
hostk02: importing sites/dc1/vars/common_vars.yml
hostk02: importing sites/dc1/release.yml
ok: [hostk01]

**Comment by mpdehaan** [comment]
sure, that's what the bug was about.

**Comment by mpdehaan** [comment]
fixed per PR above.  Closing!
