### ISSUE TITLE
Unexpected behaviour with difference filter

### ISSUE THREAD

**Issue by thmshmm** [ansible/ansible#26425]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
Filter: difference

##### ANSIBLE VERSION

```
ansible 2.3.1.0 (stable-2.3 b5c2f2dc71) last updated 2017/06/16 13:30:23 (GMT +000)
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The "difference" filter documentation states that it returns "items in 1 that don’t exist in 2". This is true, but if there are two or more equal objects in list 1 the equal items are contained only once in the result list.

##### STEPS TO REPRODUCE

```yaml
- debug: msg="{{ ["test1", "test2", "test2"]|difference(["test1"]) }}"
```

##### EXPECTED RESULTS

```
["test2", "test2"]
```
##### ACTUAL RESULTS

```
["test2"]
```

**Comment by bcoca** [comment]
It is one of the 'set' operators, sets are unique by nature.

**Comment by abadger** [comment]
Going to go ahead and close this as it is working as expected.  I'll link to the mailing list and irc channel in case you need more help.


List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
