### ISSUE TITLE
ansible_virtualization_type on CloudLinux OS

### ISSUE THREAD

**Issue by silverwind** [ansible/ansible#26424]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
facts

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['./modules', '/etc/ansible/modules/', '/usr/share/ansible']
  python version = 3.6.1 (default, Mar 24 2017, 12:50:34) [GCC 5.4.0]
```

##### SUMMARY
[This code](https://github.com/ansible/ansible/blob/e7deb07a87ea17881bef8d55890531a7f34f7d8e/lib/ansible/module_utils/facts/virtual/linux.py#L58-L64) tests for `/proc/vz` and sets `ansible_virtualization_type` to `openvz` when it exists.

The CloudLinux Distribution is actually not an OpenVZ system but both share some history which lead to the existance of `/proc/vz` on it. A [similar issue](https://projects.puppetlabs.com/issues/6728) was encountered and fixed for Puppet.

##### STEPS TO REPRODUCE
Install a [ISO](https://docs.cloudlinux.com/index.html?installing_new_servers.html) and gather facts on the installed host.

##### EXPECTED RESULTS
`ansible_virtualization_type` to be something different than `openvz`.

##### ACTUAL RESULTS
`ansible_virtualization_type` is `openvz`.

Here are some more facts from the machine I've tested on:
````json
"ansible_distribution": "CloudLinux",
"ansible_distribution_major_version": "6",
"ansible_distribution_release": "Igor Volk",
"ansible_distribution_version": "6.9",
"ansible_virtualization_role": "host",
"ansible_virtualization_type": "openvz",
````

**Comment by Akasurde** [comment]
@silverwind Thanks for reporting this issue. 

Is it ok to have - 

```"ansible_virtualization_type": "cloudlinuxos", ```

**Comment by silverwind** [comment]
I think `"NA"` might be more correct for both `ansible_virtualization_role` and `ansible_virtualization_type`. 

CloudLinux does per-user virtualization and the other possible values for this field (`"lxd"`, `"vmware"`, etc.) seem to be orientated towards machine virtualization. The underlying technology for this is LVE, so `"lve"` is also a possibilty, but as I said, it's not really machine virtualization.
