### ISSUE TITLE
Documentation examples for ``lineinfile`` still shows 'owner' and 'mode', although not supported in 1.1

### ISSUE THREAD

**Issue by vmalloc** [ansible/ansible#2643]

**Comment by mpdehaan** [comment]
Can you tell me if you are seeing an error or if you think they are just not supported?  There is common code available for this purpose.

**Comment by vmalloc** [comment]
Ok, it seems I was using 1.0 accidentally. However, the fact that these arguments are not documented under the `lineinfile` section is confusing...
