### ISSUE TITLE
New module: vmware_host_facts 

### ISSUE THREAD

**Issue by woshihaoren** [ansible/ansible#26472]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
2.3
```

##### SUMMARY

Setup module  can  get  linux system info.
But for vmware host. Doesn't have a module to get it.

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by Akasurde** [comment]
+label vmware

**Comment by woshihaoren** [comment]
https://github.com/ansible/ansible/pull/26492
new_module

**Comment by jctanner** [comment]
resolved_by_pr https://github.com/ansible/ansible/pull/26492

**Comment by Akasurde** [comment]
Closing this issue as PR #26492 is merged. If issue persists, please feel free to re-open.
