### ISSUE TITLE
DOCS: 'with_fileglob:' missing

### ISSUE THREAD

**Issue by matamouros** [ansible/ansible#2648]
Letting you know that there seems to be no mention of 'with_fileglob' in the copy module (and maybe others), like mentioned in this Google Groups thread: https://groups.google.com/d/msg/ansible-project/HXnhJoG_Rk8/QrrZ6uIcPjwJ

Thanks.

**Comment by mpdehaan** [comment]
Am thinking there should probably be a chapter on lookup_plugins altogether.

**Comment by matamouros** [comment]
Not sure I can do anything to help, but do let me know if you feel I can, in any way.

**Comment by mpdehaan** [comment]
Thanks, I'll start a chapter or section on this shortly.

There are some other things to cover too!

**Comment by mpdehaan** [comment]
present
