### ISSUE TITLE
Executing same command in multiple directories

### ISSUE THREAD

**Issue by lmilbaum** [ansible/ansible#26514]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION
ansible 2.3.1.0
  config file = /Users/liora/git/depy-utils/release/ansible.cfg
  configured module search path = [u'library']
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

##### SUMMARY

Executing the same command in multiple directories. For example:

```
 - command: git checkout master
   args:
      chdir: "{{ lookup('env', 'HOME') }}/git/{{ item }}"
   with_items:
     - repo1
     - repo2

**Comment by Akasurde** [comment]
Hi @lioramilbaum !

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
