### ISSUE TITLE
$FILE plugin fails with_items

### ISSUE THREAD

**Issue by Daemoen** [ansible/ansible#2652]
- name: ${item} SSH Key
  authorized_key: user=${item} key='$FILE(../files/ssh/${item}_mmx.pub)' state=present
  with_items: ${mmx_users}

**Comment by mpdehaan** [comment]
This should be enough to repro, though FYI, you should also paste the error you are getting when you are filing tickets.

Thanks!

**Comment by mpdehaan** [comment]
BTW, the workaround for this, is:

```
authorized_key: <blarg> key="{{ lookup('file', 'path/blarg/' + item + '/rest') }}"
```

**Comment by bcoca** [comment]
just ran into same issue, used workaround

**Comment by mpdehaan** [comment]
this is now fixed on the development branch, thanks!
