### ISSUE TITLE
include_role doesn't support notify

### ISSUE THREAD

**Issue by farcaller** [ansible/ansible#26537]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 3.6.1 (default, Jul  6 2017, 10:09:38) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
`include_role` doesn't support changed status, making it impossible to trigger handlers or further activities based on `include_role` invocation.

##### STEPS TO REPRODUCE
```yaml
- include_role: {name: other_role}
  register: role
- debug:
  msg: '{{role.changed}}'
```

##### EXPECTED RESULTS
role.changed would be `true` if any task within included role was changed

##### ACTUAL RESULTS
role is empty

**Comment by alikins** [comment]
ping @bcoca @jimi-c

**Comment by bcoca** [comment]
includes (aside from include_vars) don't return anything, they get substituted by the included tasks

**Comment by christiang830** [comment]
+1

**Comment by pilou-** [comment]
Should not an error be raised when `notify` is used with `includes_*` ?

`block` don't support `notify` too and an error is raised (`'notify' is not a valid attribute for a Block`) when `notify` is used with `block`.

**Comment by christiang830** [comment]
For my understanding a notify at the include_* task should be triggered, when one of the included tasks is changed. I think that would greatly improve the functionality of these include tasks.

For example:
We have some roles that deploy applications which all need their own init scripts.
What i want now is a role (i call them utility role) "init_script" that i can include with include_role and the specific variables from the application roles. But If the init script has changed, sometimes i would need to retrigger a restart or similar. That is not possible at the moment.

**Comment by bcoca** [comment]
includes either return a list of tasks or fail, they are never changed nor any other status. `notify` is a valid keyword .. but really a noop in this case. I did open a PR about warning when ignoring the keywords  #27897 

@kami8607 it seems you want a 'new feature' and that is for includes to reflect the status of the summary of tasks included. I'm curious on how/which thresholds affect the include, how many skipped tasks makes it skipped?  how do we count failure? how should it interact with block's rescue/always?
This can get complicated and requires a proposal https://github.com/ansible/proposals

**Comment by MarkusTeufelberger** [comment]
I would expect it to work like this:

Failed > Changed > Unchanged > Skipped

Meaning that if any higher ranked return type occurs, the current one gets overwritten. If at least one command is ran in a role, it can't be called "skipped" any more, only changed, unchanged or failed. similar for other scenarios.

In any case the missing return type should be documented in http://docs.ansible.com/ansible/latest/include_role_module.html imho.

**Comment by Hippolyteb** [comment]
+1

**Comment by jmooo** [comment]
The lack of this feature kind of goes against Ansible's best practices to break code up into reusable roles.

If `role1` can't restart itself after `include_role: helper_util` finishes (in my case, helper is a role to set envvars that a lot of different roles import), then you have to duplicate that helper code into every role that uses it

**Comment by goldencut** [comment]
+1 so 'notify:' could be used. With latest version Ansible rises an error if 'notify:' is there so now I have to remove all the ones I preemptively had added.. :/

**Comment by runiq** [comment]
I think @MarkusTeufelberger's [suggestion re:return types](https://github.com/ansible/ansible/issues/26537#issuecomment-338167934) sound sensible. I'd love to be able to notify handlers once per block that way.

**Comment by samdoran** [comment]
This was proposed in https://github.com/ansible/proposals/issues/136.
