### ISSUE TITLE
Directory upload support ?

### ISSUE THREAD

**Issue by fclairamb** [ansible/ansible#2653]
Hi

What is planned regarding directory upload ? Even uploading a tar-gz file of a dir would be valid solution for a lot of cases. It's way better than nothing.

In my case, I want to get a set of public [tinc](http://www.tinc-vpn.org/) keys from each host and upload them back to every host. Ansible is perfect for that except for this kind of simple task.

Florent

**Comment by mpdehaan** [comment]
Nothing in plan, open to pull requests.

The git module is available, as is "local_action: rsync

Stop by the mailing list if you have questions.
