### ISSUE TITLE
Strict mode for missing template variables

### ISSUE THREAD

**Issue by nigma** [ansible/ansible#2654]
At the moment evaluation of template variables that are not defined in the template context can result in unexpected output. Undefined variables are either evaluated to empty string or to variable name itself:
- `{{ missing }}` -> empty value
- `$missing` -> `$missing`
- `${missing}` -> `${missing}`
- `{{ missing.attr }}` -> "missing is undefined" exception
- `${missing.attr}` -> `${missing.attr}`

This can lead to all sorts of errors (some of them possibly costly and unrecoverable in the worst case scenario) that can pass unnoticed until the resulting configuration file is examined on the destination hosts or the managed host or service goes down.

What I would like to propose is to evaluate all templates in a strict mode and raise exception (or at least issue a warning) for any variable that is not defined in the template context.

This would allow to avoid all kinds of typo mistakes and missing var definitions as well as make the template rendering more predictable.

As for the current way of evaluating undefined `{{ x }}` into an empty value, the  `{{ x|default("") }}` [default](http://jinja.pocoo.org/docs/templates/#default) filter or [defined](http://jinja.pocoo.org/docs/templates/#defined)/[undefined](http://jinja.pocoo.org/docs/templates/#undefined) test can be used to provide default values inside templates (which is the right approach anyway as it clearly communicates the intended behavior).

Also don't want to sound clichéd, but:

> Explicit is better than implicit.

Handling of undefined variables in task definitions is yet to be evaluated.

CC: #2617

**Comment by legrostdg** [comment]
I totally agree with you! Ansible should rely on jinja2 only for evaluating template variables. This ansible specific "$variable", evaluated to either '$variable' or the value of $variable, makes no sense, and may be dangerous (especially when working on config files which use "$"). I think we should use "{{ variable }}" only (and it seems to be planned, I had a discussion with mpdehann on irc). A last advantage is that it would simplify the use of other template languages...

**Comment by mpdehaan** [comment]
Yep,

Jinja2 in templates is completely available in Ansible 1.2, and will be the only thing the docs mention (though previous docs will be available).

It is not true that {{ missing }} should result in an empty variable though, I'll double check that this is not the case.

**Comment by legrostdg** [comment]
so, $variable will be replaced by '$variable' in Ansible 1.2 (and not the value of $variable)?

**Comment by mpdehaan** [comment]
no, I've never said that, the old ways do keep working.

Meanwhile, I have checked and if a template string cannot be evaluated in a playbook with Jinja2 expressions it does not evaluate to empty string, however in a playbook it currently does -- however, as this is present behavior, I think it should stay.

I did just push a fix so the debug module plays nicer with unevaluated Jinja2 statements

**Comment by nigma** [comment]
I beg to disagree.

I think the current behavior is basically too dangerous and to some extent unpredictable.

The main reason for using a templating system is that people want to parametrize config files and substitute `{{ }}` expressions with values passed from the runner.

When I put a `{{ var }}` statement in a template I would expect it to be replaced with the exact value of _var_ and nothing else. And if for some reason I forget to define the variable or the value is not passed to the template because of a runner error, I would expect the whole process to be interrupted before the invalid content is written to the config file and I end up with `Port` undefined line in the sshd config or any other file that may result in unrecoverable errors or require post-mortem investigation.

Similarly for the yaml playbook definitions. When the `{{ x }}` syntax is used to output a variable, the last thing people expect is that the statement is silently replaced with something other than the value of _x_ and the process just happily carries on and passes rubbish to the sudo shell.

Falling back to empty value for undefined variable could be acceptable when rendering a web page, but in my humble opinion it provides no real benefit when outputting things as precise and fragile as system config files.

Having said that I do understand the backward compatibility thing and that suddenly making all context lookup errors raise exceptions could result in an intense discussion on the mailing group.

However making the template evaluation more strict could probably at the beginning be controlled by a flag defined in the config file or passed as a param, and the documentation could advertise this and recommend use of `{{ |default('') }}` filter to explicitly control behavior of not provided default values.

In my opinion pushing this change forward would only benefit the project and make ansible more reliable and trustworthy, so hopefully you will be willing to reconsider my arguments.

Btw. as of now a line in playbook with `"{{ defined_var }} {{ undefined_var }}"` passes unmodified, which is counter-intuitive and different from how this line would be processed in a j2 template.

**Comment by legrostdg** [comment]
So, if you keep the current behaviour of $variable in the templates (and I totally agree with nigma that this should not be the case), you should at least keep it in the doc, too.
