### ISSUE TITLE
issue in pdb  while using test-module

### ISSUE THREAD

**Issue by piusranjan** [ansible/ansible#26563]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME
ansible/hacking/test-module

##### ANSIBLE VERSION

```

```

##### SUMMARY
Hi ,
I am facing issue if I use --debugger option as below:
```
python $HOME/learning/ansible/hacking/test-module -m $HOME/streams/fnd_ansible/modules/libraries/mymodule .py -a "name=test" --debugger /usr/lib64/python2.7/pdb.py
```

```
(Pdb) c
Traceback (most recent call last):
File "/tmp/ansible_ppYxMR/ansible_module_yum_ss.py", line 29, in 
module = AnsibleModule(
File "/tmp/ansible_ppYxMR/ansible_module_yum_ss.py", line 29, in 
module = AnsibleModule(
File "/usr/lib64/python2.7/bdb.py", line 49, in trace_dispatch
return self.dispatch_line(frame)
File "/usr/lib64/python2.7/bdb.py", line 68, in dispatch_line
if self.quitting: raise BdbQuit
bdb.BdbQuit
```

I am using .set_trace() , just before creation of module . It can happen anywhere , when i declare set_trace().

``` python
import pdb

pdb.set_trace()
module = AnsibleModule(
argument_spec = dict(
name=dict(aliases=['pkg'], type="list"),
exclude=dict(required=False, default=None),
state=dict(default='installed', choices=['absent','present','installed','removed','latest']),
```

Thanks,
Pius

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by alikins** [comment]
You didn't mention which version of ansible you are using, but this looks related to a bug fix in hacking/test-module: https://github.com/ansible/ansible/commit/56d33a2967231f954e788ff40763e4591ee88907

That fix is only in git devel/ branch at the moment.

**Comment by piusranjan** [comment]
@alikins . Thanks for your response.
I am using 2.4.0 0.0.devel

**Comment by piusranjan** [comment]
@alikins , I  took the devel/ branch  code and still having the same issue.

**Comment by Akasurde** [comment]
@piusranjan Could you please check on latest Ansible devel branch and let us if it works for you ? As I am not able to reproduce this.

```
$ python /data/src/ansible/hacking/test-module -m test_module.py -a "name=test" --debugger /usr/lib/python2.7/pdb.py
* including generated source, if any, saving to: /Users/akasurde/.ansible_module_generated
> /Users/akasurde/.ansible_module_generated(1)<module>()
-> import pdb
(Pdb) n
```
needs_info

**Comment by piusranjan** [comment]
@Akasurde . Thanks for  the reply . Actually I  had to manage in different way to test my custom  ansible module as above did not work at that time. I will let you know again I am required to to use the above way to test .
