### ISSUE TITLE
Allow ansible hosts file to be able to specify a [group_name] including other group_names

### ISSUE THREAD

**Issue by sjmudd** [ansible/ansible#2658]
I have quite a large number of hosts to manage and they can be categorised into different groups depending on how you work on them. So I'd like to be able to do the following which currently seems impossible:

[dc1-frontend-slaves]
f-slave-[01:10].dc1.domain.com

[dc1-backend-slaves]
b-slave-[01:10].dc1.domain.com

[dc2-frontend-slaves]
f-slave-[01:10].dc2.domain.com

[dc2-backend-slaves]
b-slave-[01:10].dc2.domain.com

[dc1-slaves]
dc1-frontend-slaves
dc1-backend-slaves

[dc2-slaves]
dc2-frontend-slaves
dc2-backend-slaves

[all-slaves]
dc1-slaves
dc2-slaves

or

[all-slaves]
dc1-frontend-slaves
dc1-backend-slaves
dc2-frontend-slaves
dc2-backend-slaves

which would have the same result.

This avoids duplication of names anywhere and also allows a more hierarchical definition.

The example may look far fetched but real-life usage, at least where I work, would allow me to simplify somewhat the rather large ansible file I'm currently using.

**Comment by bcoca** [comment]
this should work if you use the :children when including groups into groups

[dc1-slaves:children]
dc1-frontend-slaves
dc1-backend-slaves

**Comment by mpdehaan** [comment]
yep, child groups are what you want....
