### ISSUE TITLE
Documentation/Feature request - Divide modules by context with additional intermediate headers (eg User admin, Files,  cloud service )

### ISSUE THREAD

**Issue by devdave** [ansible/ansible#2659]
Two reasons:

 Will cut down discovery time for new ansible users trying to figure out which module to use ( initially thought I needed to use file for copy local => remote, then saw copy module ).

 This might increase future safety for the ansible doc's and make it easier to see the projects capabilities at a glance.

If I get time this weekend I can give it a try, I looked at the raw rst and can see it will be problematic as currently it just iterates over a list.

**Comment by mpdehaan** [comment]
Yep, this is already in plan.

We are probably going to add a category field and do something with angular.js for filtering.

**Comment by mpdehaan** [comment]
dup of #2194
