### ISSUE TITLE
Powershell path validation fails on nonexistent drive letter

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible#26623]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module_utils/powershell.ps1

##### ANSIBLE VERSION
2.4.0

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
`Get-AnsibleParam -Type Path` will fail on a path with an invalid drive letter (it's only supposed to validate the "shape" of the path). This is an underlying problem with `Test-Path -IsValid`.

**Comment by dagwieers** [comment]
+label windows
