### ISSUE TITLE
hostname not returned correctly

### ISSUE THREAD

**Issue by flynfish** [ansible/ansible#2663]
Looking at the setup module code, it looks like the `$ansible_hostname` uses the `socket.getfqdn()` which doesn't give me the actual hostname of the remote server.

When running `python -c 'import socket; print socket.getfqdn()'` I get `localhost` which isn't really the hostname. 

When running `python -c 'import socket; print socket.gethostname()'` I get the correct hostname. 

Is there a reason why `gethostname()` is not used in place of `getfqdn()` ?

**Comment by ciupicri** [comment]
`getfqdn` seems to return a different result than `gethostname` if the hostname of the machine is an alias.

For example if I have this in `/etc/hosts`:

```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 ansible.tld
```

and then set the hostname to `ansible.tld` the following happens:

```
[root@hermes ~]# python -c 'import socket; print socket.getfqdn()'
localhost.localdomain
[root@hermes ~]# python -c 'import socket; print socket.gethostname()'
ansible.tld
```

**Comment by srgvg** [comment]
Why retrieving the hostname by a socket? A 'network name' is basically an external (dns, ...) parameter (so is IMHO /etc/hosts).

The local hostname is what is set by hostname(1). Not sure but wouldn't that be platform.node() ?

**Comment by flynfish** [comment]
@sergevanginderachter 

`platform.node()` also returns the correct hostname in my situation. If that is better than using `socket.gethostname()` then I am all for it.

**Comment by ciupicri** [comment]
I've looked at the source code for `platform.node` and it calls [`os.uname`](http://hg.python.org/cpython/file/026ee0057e2d/Lib/platform.py#l1188). If it fails, it calls [`_node`](http://hg.python.org/cpython/file/026ee0057e2d/Lib/platform.py#l1199) which will then call [`socket.gethostname()`](http://hg.python.org/cpython/file/026ee0057e2d/Lib/platform.py#l968).

The `gethostname(2)` man page says:

> The GNU C library does not employ the gethostname() system call; instead, it implements gethostname()  as a library function that calls uname(2) and copies up to len bytes from the returned nodename field into name.

So using `platform.node()` might be the way to go after all.

As a side note, `gethostbyname` returns immediately on my Fedora 18 system (python-2.7.3-13) even if I block the responses from my DNS servers, so there doesn't seem to be any risk using it if the DNS servers are slow or down.

**Comment by mpdehaan** [comment]
Ok, sounds reasonable to use platform.node then. Somebody send me a patch, please?

**Comment by mpdehaan** [comment]
closing since we have a PR open on this now.  See above.

**Comment by stoned** [comment]
ciupicri: re PR #2677 

Please bear with my poor choice of words.

And yes you are 100% right.

The thing is I would expect ansible_fqdn to get its value from the
host name resolution process, be it straight from DNS or overriden
by /etc/hosts or whatever.

And I would expect ansible_hostname to get its value from
uname(3)/gethostname(3) hence most likely from platform.node()

So what I saying is that platform.node() should most likely be used
in a couple of places in ansible code, like you proposed, but I
think that ansible_fqdn should be left alone with socket.fqdn()
value.

**Comment by ciupicri** [comment]
To draw another parallel, you seem to want the output of the command `hostname --fqdn` (which depends on the resolver), while others want `hostname`.

In case it matters, I run facter-1.6.18-1.fc18 using the setup mentioned in [the second comment](https://github.com/ansible/ansible/issues/2663#issuecomment-16312325) and the result was:

```
fqdn => ansible.tld
hostname => ansible
```

instead of `localhost` (what `hostname --fqdn` returns) or `localhost.localdomain` (what `socket.getfqdn()` returns).

Also, if I don't put `ansible.tld` in `/etc/hosts` and I block the responses from my DNS servers (using iptables), it takes 40 seconds to run `socket.getfqdn()` on my Fedora 18 system.

**Comment by mpdehaan** [comment]
now using platform.node for the hostname, but leaving fqdn as is.

Seemed to be the best consensus. 

ciuprici -- understood, maybe don't do that then :)

**Comment by ciupicri** [comment]
What about the `ansible_domain` field? Will it remain related to `ansible_fqdn`?

I'm also wondering if there are people out there who assumed that `ansible_hostname`.`ansible_domain` = `ansible_fqdn`.

P.S. [cfengine](https://cfengine.com/manuals/cf3-Reference#Variable-context-sys) has [sys.fqhost](https://cfengine.com/manuals/cf3-Reference#Variable-sys_002efqhost), [sys.domain](https://cfengine.com/manuals/cf3-Reference#Variable-sys_002edomain), [sys.uqhost](https://cfengine.com/manuals/cf3-Reference#Variable-sys_002euqhost) (which seem to be DNS based) and [sys.host](https://cfengine.com/manuals/cf3-Reference#Variable-sys_002ehost) (which seems to be extracted from uname).
