### ISSUE TITLE
test-module cannot parse complex arguments that contain characters like : or /

### ISSUE THREAD

**Issue by chbndrhnns** [ansible/ansible#26636]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`hacking/test-module`

##### ANSIBLE VERSION
```
ansible 2.4.0 (3-access-to-networks 6a61aecebc) last updated 2017/07/11 11:36:57 (GMT +200)
  config file = None
  configured module search path = [u'/Users/jo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jo/repos/ansible/lib/ansible
  executable location = /Users/jo/repos/ansible/bin/ansible
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
Mac OS X 10.12

##### SUMMARY
Using `hacking/test-module` to run one of my modules locally fails when I supply arguments that contain some special characters like:

- `:`
- `/`

##### STEPS TO REPRODUCE
Have an arbitrary module and use the `test-module` command:

```
/hacking/test-module -m contrail_network.py -a "{"auth": [{"endpoint": "localhost:8082"},{}]}"
```

##### EXPECTED RESULTS
Correct parsing of the parameters

##### ACTUAL RESULTS
Parsing error

```
Traceback (most recent call last):
  File "../../../../../hacking/test-module", line 266, in <module>
    main()
  File "../../../../../hacking/test-module", line 247, in main
    (modfile, modname, module_style) = boilerplate_module(options.module_path, options.module_args, interpreters, options.check, options.filename)
  File "../../../../../hacking/test-module", line 134, in boilerplate_module
    complex_args = utils_vars.combine_vars(complex_args, loader.load(args))
  File "/Users/jo/repos/ansible/lib/ansible/parsing/dataloader.py", line 115, in load
    self._handle_error(yaml_exc, file_name, show_content)
  File "/Users/jo/repos/ansible/lib/ansible/parsing/dataloader.py", line 221, in _handle_error
    raise AnsibleParserError(YAML_SYNTAX_ERROR, obj=err_obj, show_content=show_content, orig_exc=yaml_exc)
ansible.errors.AnsibleParserError: Syntax Error while loading YAML.


The error appears to have been in '<string>': line 1, column 29, but may
be elsewhere in the file depending on the exact syntax problem.

exception type: <class 'yaml.scanner.ScannerError'>
exception: while scanning a plain scalar
  in "<byte string>", line 1, column 20
found unexpected ':'
  in "<byte string>", line 1, column 29
make: *** [test-1] Error 1
```

**Comment by chbndrhnns** [comment]
In the gitter channel I came across the idea to use single quotes for the whole thing which works.

So, if that's the intended, then the `README.md` is wrong where the example is like this:

> Use:
> 
>   $ ./hacking/test-module -m module \
>        -a "{"parent": {"child": [{"item": "first", "val": "foo"}, {"item": "second", "val": "bar"}]}}"

Still, the `child` value in Python is then a string, although I expected a nested dictionary.

**Comment by sivel** [comment]
This issue has been resolved in the documentation via https://github.com/ansible/ansible/pull/26667

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
