### ISSUE TITLE
obsolete code paths hardcoded in .gitignore cause users to unwittingly run ancient versions of ansible

### ISSUE THREAD

**Issue by zzzeek** [ansible/ansible#26650]
- Bug Report

##### COMPONENT NAME

distribution

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 0fc0b6f059) last updated 2017/07/11 12:17:53 (GMT -400)
  config file = None
  configured module search path = [u'/home/classic/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/classic/dev/ansible/lib/ansible
  executable location = /home/classic/.venv/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### CONFIGURATION

plain vanilla

##### OS / ENVIRONMENT

fedora linux

##### SUMMARY

ansible hardcodes obsolete source file locations in .gitignore:

https://github.com/ansible/ansible/blob/devel/.gitignore#L80

```
# old submodule dirs
lib/ansible/modules/core
lib/ansible/modules/extras

```

Because of this, I've been using a broken ansible for many weeks.  I only found this because I finally decided to fix all the bugs i was finding in docker_container.py, and then spent another few hours pulling my hair out wondering why all my changes that happened to be in the correct file were making no effect;  "git pull" "git status" etc. are not able to tell me anything about the existence of these files because of this .gitignore entry.  

I understand I'm using git checkout I'm supposed to know my way around but having source code files that have been removed from the project stuck in .gitignore doesn't seem like a good practice.

**Comment by dagwieers** [comment]
You are absolutely right, this is a recipe for disaster.

PS You can create a PR yourself with a change like this. Would have saved me a minute or two :-)

**Comment by zzzeek** [comment]
I tend to file an issue because I wasn't sure if there was some reason those ignores were there.

**Comment by dagwieers** [comment]
Fair enough. They surely were added for a reason, but definitely the wrong reason ;-)
