### ISSUE TITLE
ERROR! Unexpected Exception: 'module' object has no attribute 'load_vars'

### ISSUE THREAD

**Issue by sponnusamy** [ansible/ansible#26670]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /Users/sponnusamy/ansible.cfg
  configured module search path = [u'library']
  python version = 2.7.10 (default, Jul 30 2016, 18:31:42) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT
Mac OSX Sierra Version 10.12

##### SUMMARY

Getting below error when I try to bootstrap the hosts ERROR! Unexpected Exception: 'module' object has no attribute 'load_vars'

##### STEPS TO REPRODUCE
Im trying to bootstrapping hosts.

```yaml
ansible-playbook -vvv -I <hosts_file> < bootstrap.yaml> --limit <HOST_NAME> -e "login_groups=<Group_Name> sudo_groups=<Group_Name> owner_group=<Group_Name>"
```

##### ACTUAL RESULTS

```

```

**Comment by Shaps** [comment]
Hi @sponnusamy, do you know which module fails? I see you have `library` in the module search path, maybe it's something wrong with a module in there?

**Comment by samdoran** [comment]
The `~/Library` directory on macOS confuses Ansible, so it's best not to use your home directory for Ansible things on macOS. You can ask for further clarification on the mailing list or IRC.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by sponnusamy** [comment]
The issue is resolved. I supposed to run the command in 1.9 instead of 2.3. After the downgrade it works

**Comment by kravietz** [comment]
I also experienced this error on Ubuntu 16.04 and this was caused by outdated `pyOpenSSL` library. The fix:

    sudo -H pip2 uninstall pyOpenSSL
    sudo -H pip2 install pyOpenSSL

Now on `pyOpenSSL-17.2.0` it works perfectly.

**Comment by JOduMonT** [comment]
interesting
On ubuntu 16.04LTS
I have this error only if
I install ansible via pip or ppa.

If I use ansible 2.02, which come from the ubuntu repo
this issue is not present

sadly the `sudo -H pip2 install pyOpenSSL not working for me`
and pip return an issue with OpenSSL; which is a kind of a loop

**Comment by danilochilene** [comment]
@jodumont , try ```pip2 install -U pyOpenSSL```

Fixed for me.

**Comment by yuriw** [comment]
"sudo pip2 install -U pyOpenSSL"  fixed for me too !

**Comment by dshuvar** [comment]
For ubuntu 16.04 command `sudo pip install -U pyOpenSSL` fixed it for me.

**Comment by rgaufman** [comment]
I'm getting this, any ideas?<

```
$ sudo pip install -U pyOpenSSL
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 13, in <module>
    from pip.exceptions import InstallationError, CommandError, PipError
  File "/usr/lib/python2.7/dist-packages/pip/exceptions.py", line 6, in <module>
    from pip._vendor.six import iteritems
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 64, in <module>
    vendored("cachecontrol")
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/adapter.py", line 3, in <module>
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/__init__.py", line 53, in <module>
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 54, in <module>
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
deployer@xancloud:~/deploy/myansible$
```

**Comment by amioranza** [comment]
the commands below worked for me on Ubuntu 16.04

```
sudo rm -rf /usr/lib/python2.7/dist-packages/OpenSSL/
/usr/bin/pip2 install -U pyOpenSSL
```

**Comment by drewburr** [comment]
> the commands below worked for me on Ubuntu 16.04
> 
> ```
> sudo rm -rf /usr/lib/python2.7/dist-packages/OpenSSL/
> /usr/bin/pip2 install -U pyOpenSSL
> ```

This worked for me! Thank you!

**Comment by the-mikedavis** [comment]
To build on the existing workaround (^), if your pip isn't the `/usr/bin/pip` one, make sure to find it before removing everything:

```sh
$ type pip2
/usr/local/bin/pip2
$ rm -rf /usr/local/lib/python2.7/dist-packages/OpenSSL/
$ pip2 install -U pyopenssl
```
