### ISSUE TITLE
Play attributes don't override inventory parameters

### ISSUE THREAD

**Issue by jody-frankowski** [ansible/ansible#26697]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- Variables
- Inventory

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 7ffa882f9d) last updated 2017/07/12 14:34:39 (GMT +200)
  config file = /home/me/.ansible.cfg
  configured module search path = ['/home/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/me/code/ansible/lib/ansible
  executable location = /home/me/code/ansible/bin/ansible
  python version = 3.6.1 (default, Mar 27 2017, 00:27:06) [GCC 6.3.1 20170306]
```

##### CONFIGURATION

None

##### OS / ENVIRONMENT

Arch linux

##### SUMMARY

Setting play attributes, such as:

* user/remote_user
* become

Don't override inventory variables such as `ansible_user` and `ansible_become`.

My use case is to set the "usual" ansible user for every host in the inventory, which allows me not to set it in all my plays.
However for some special plays (think utility playbooks) I need another user. So I wanted to override it just right there.

Note: My workaround is to override those variables with a `vars:` block in the plays, but I think that the play attributes should be able to override them too.

##### STEPS TO REPRODUCE

Example playbook: https://github.com/jody-frankowski/play-attributes

```
ansible-playbook -i inventory -vvvv test.yml
```

##### EXPECTED RESULTS

See that ssh uses the `play` user.

##### ACTUAL RESULTS

See that ssh uses the `inventory` user.

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Connection variables have the highest precedence, they override play keywords. If you want to set defaults do so in ansible.cfg or the command line.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
