### ISSUE TITLE
only_if false_negative with with_items

### ISSUE THREAD

**Issue by wgj** [ansible/ansible#2669]
[wes@mgmt001 ~]$ ansible --version
ansible 1.1 (from devel)

ansible_hostname for mgmt.dal05 is 'mgmt':

[wes@mgmt001 ~]$ ansible -i workspace/ansible/etc/hosts -m setup -k mgmt.dal05\* |grep ansible_hostname
SSH password: 
        "ansible_hostname": "mgmt", 

Conditional comparing item 'mgmt' with 'ansible_hostname':

 10   - template: src=files/sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0600
 11     with_items: [ 'mgmt', 'mgmt001']
 12     only_if: "'item' == 'ansible_hostname'"

Ansible-playbook is not able to match:

PLAY [all] ********************\* 

GATHERING FACTS ********************\* 
ok: [comments-test.dal05]
ok: [hcmailer-test.dal05]
ok: [tagger-test.dal05]
ok: [mgmt.dal05]

TASK: [template src=files/sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0600] ********************\* 
skipping: [hcmailer-test.dal05] => (item=mgmt)
skipping: [hcmailer-test.dal05] => (item=mgmt001)
skipping: [comments-test.dal05] => (item=mgmt)
skipping: [comments-test.dal05] => (item=mgmt001)
skipping: [mgmt.dal05] => (item=mgmt)
skipping: [mgmt.dal05] => (item=mgmt001)
skipping: [tagger-test.dal05] => (item=mgmt) skipping: [tagger-test.dal05] => (item=mgmt001)

PLAY RECAP ********************\* 
comments-test.dal05            : ok=2    changed=0    unreachable=0    failed=0  
hcmailer-test.dal05            : ok=2    changed=0    unreachable=0    failed=0  
mgmt.dal05                     : ok=2    changed=0    unreachable=0    failed=0  
tagger-test.dal05              : ok=2    changed=0    unreachable=0    failed=0

**Comment by mpdehaan** [comment]
Ok, so the problem here is a missing dollar sign in 1.1

only_if: "'item' == 'ansible_hostname'"

Looks like that should be "$item" to me.  (So, not a bug)

(This is why in 1.2, I have super cleaned this up so you can just say...)

when: item == 'ansible_hostname'
