### ISSUE TITLE
Please improve the tags section on the Advanced Playbooks Wiki to document the tags= syntax with includes

### ISSUE THREAD

**Issue by asad-at-srt** [ansible/ansible#2671]
When I started implementing tags, this is where I came looking for information.
Since we used includes extensively, I couldn't figure out how to use tags with includes.
The tags= parameter on includes isn't self-evident.

Please enhance this section to mention:
-include: some_task tags=<comma-separated-tags>

**Comment by mpdehaan** [comment]
seems we would just have #2672
