### ISSUE TITLE
upgrade task include/roles: to accept a "tags:" in addition to the current tags= variable syntax

### ISSUE THREAD

**Issue by asad-at-srt** [ansible/ansible#2672]
Please consider supporting the following synonym

include: some-task
tags: t1

where each action within the task would get tagged with tag t1
This is because the above syntax is simply consistent with the rest of Ansible.

We assumed the above, and when it failed, we searched the Wiki/google and still couldn't find direct information on how to use includes with tags.
It's only later (through an Ansible groups posting) that we realized the tags= parameter on includes (very gratifying indeed).

We contend that the above syntax is more "obvious" to early/intermediate Ansible users - especially the one's who didn't grow up with Ansible in it's first year. Of course improving the Wiki would also benefit future adopters so I'm also filing an issue for that.

**Comment by mpdehaan** [comment]
Yep, this is something I would like to see happen.

Patches would be welcome.
