### ISSUE TITLE
Want to connect Windows10 from Ansible installed on CentOS 7/Ubuntu 16.04

### ISSUE THREAD

**Issue by cyrilsebastian** [ansible/ansible#26739]
Hi. I want to access on Windows10 via Ansible which is installed in CentOS 7 and test lab is on VMware workstation.

Things I have completed
- Successfully run ConfigureRemotingForAnsible.ps1 on Windows10 powershell.
- Installed Ansible 2.3 and WinRM on CentOS 7.
- Enabled Administrator on Windows 10.

Tree structure of the configuration files are at /etc/ansible/
```
 ansible/
  ├── group_vars
  │   └── windows.yml
  └── hosts
```

windows.yml
```
 #this includes the login credentials for Windows
 ansible_user: administrator
 ansible_password: passwd
 ansible_port: 5986
 ansible_connection: winrm
 ansible_winrm_server_cert_validation: ignore
```

hosts
 ```
[windows]
 192.168.1.25
```
When I am running mentioned command below I am getting error with no host file.
 
[root@localhost ansible]# ansible windows -i hosts -m win_ping
192.168.1.25 | UNREACHABLE! => { "changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.25 port 22: Connection refused\r\n", "unreachable": true }

Tried the same with Ubuntu 16.04, but still I am getting error.
```
192.168.1.25 | UNREACHABLE! => {
    "changed": false,
    "msg": "ssl: 500 WinRMTransport. [SSL:         CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)",
    "unreachable": true
}
```

Want to do more testing on it with chocolatey installation, but since it is not working I am stuck. Kindly help.

 ISSUE TYPE
 - Support Request
 - Need Info
 - Needs Triage
 - Windows

 COMPONENT NAME
 - WinRM

 ANSIBLE VERSION
 - Ansible 2.3

 OS / ENVIRONMENT
 - Ansible 2.3 installed on Centos 7 and Ubuntu 16.04
 - Trying to connect with Windows 10 - 1607

**Comment by jborean93** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by cyrilsebastian** [comment]
I tried asking the same in the group, but I didn't get any response. By any chance, can you please share links which can be useful. Thanks.

**Comment by jborean93** [comment]
Do you have a link for it, happy to help over there but I just had a quick look and couldn't find it.

There are more out there and this is a bit stale but it is a good place to start to see what variables should be defined and the different auth types http://docs.ansible.com/ansible/latest/intro_windows.html

**Comment by cyrilsebastian** [comment]
Thanks @jborean93. Much appreciated.

**Comment by SnehitR** [comment]
@cyrilsebastian - I was trying the same and got some issues .
Could you like to help me please.
err: Unable to establish an HTTP or HTTPS remoting session. in pS
