### ISSUE TITLE
ansible tries every loaded ssh key even though you specify --private-key option

### ISSUE THREAD

**Issue by filip-vt** [ansible/ansible#26749]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
--private-key

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### OS / ENVIRONMENT
macos, managing ubuntu 14.04/16.04

##### SUMMARY
Even though you specify explicitly the private key to use, with --private-key, ansible will try every loaded key (with `ssh-add`) when trying to SSH. This becomes a problem when you have a certain number of keys loaded. Because of the `MaxAuthTries` directive that defaults to 6 tries in ubuntu. Ansible should ignore all other keys and use the one you specified. Came across it while using packer, that generates a new priv key every time.

##### STEPS TO REPRODUCE
load 6 different private keys with ssh_add. Try to connect with ansible --private-key to an ubuntu box, specifying a 7th key (loaded or not loaded)

##### EXPECTED RESULTS
I expected that the key I specified would be used.

##### ACTUAL RESULTS
Got a `Received disconnect from 127.0.0.1 port 50428:2: too many authentication failures`

```
PLAY [default] ******************************************************************

TASK [Gathering Facts] *********************************************************
failed to handshake
fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '[127.0.0.1]:50428' (RSA) to the list of known hosts.\r\nReceived disconnect from 127.0.0.1 port 50428:2: too many authentication failures\r\nsetsockopt TCP_NODELAY: Invalid argument\r\nsetsockopt IP_TOS 8: Invalid argument:\r\nmuxclient: master hello exchange failed\r\nFailed to connect to new control master\r\n", "unreachable": true}
to retry, use: --limit @/LOCATION/test1-playbook.retry

PLAY RECAP *********************************************************************
default                     : ok=0    changed=0    unreachable=1    failed=0
```

**Comment by calfonso** [comment]
Hi!

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel. When you bring it to the list we can talk about your ssh agent config.

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!

**Comment by JimtotheB** [comment]
@filip-vt I followed you over here from Packer, I'm having this exact same issue, pretty much down to the local OS and remote OS versions.  I'm unsure why they decided to close this issue....

**Comment by danielcompton** [comment]
@calfonso this isn't a user question, it's a bug report? Ansible should use the private-key that is specified first, rather than cycling through all loaded SSH keys before getting to this one. You can also reproduce this issue just by having many SSH keys loaded into your ssh-agent (without using Packer). It looks like specifying [IdentitiesOnly=yes](https://superuser.com/a/268777) to the SSH command would prevent this from happening.

**Comment by calfonso** [comment]
Ansible is working as ssh does. Adding ssh_args is for the user to decide. If Ansible is behaving differently than one would expect ssh to behave, then we have a bug to fix. I don't believe that's the case.

**Comment by danielcompton** [comment]
When providing `--private-key` to Ansible, the most likely interpretation the user will take is that that private key will be provided to the remote hosts first. It is possible to configure Ansible to pass the right SSH arguments, but most people will not realise that they need to do that.

It seems like sensible behaviour that by default when passing `--private-key`, that Ansible also configures SSH to just use that key. This will fix the most common case that most users will run into. You can see this discussed a while ago at https://groups.google.com/forum/#!topic/ansible-project/mySoOhZ6BtA.

**Comment by calfonso** [comment]
This is probably worth bringing up in the core working group on IRC. Feel free to add it as an agenda item for further discussion.

**Comment by sivel** [comment]
Specifying `IdentitiesOnly=yes` as a default could be a bad thing, and in my use case would cause immediate problems.  It causes ssh to follow a different code path, that actually breaks functionality for us, where keys are added to the agent and then deleted.  `IdentitiesOnly=yes` causes ssh to require that the file be present on the filesystem, regardless of existing in an agent.

Outside of `IdentitiesOnly` I don't know of a way to tell SSH to only use the one specific key when an ssh agent is also involved.

**Comment by danielcompton** [comment]
@sivel when you say

> Specifying IdentitiesOnly=yes as a default could be a bad thing

Do you mean specifying it as a default when `--private-key` is provided to Ansible, or just as a global default? I'm only suggesting it for the former case.

@calfonso which IRC channel should this go to? `#ansible`?

**Comment by sivel** [comment]
I am saying that specifying it under any circumstance as a default is bad.  Whether with `--private-key`, or with `ansible_private_key_file`

If you were using agent forwarding to a server where you then run ansible on, `IdentitiesOnly` would prevent that situation from working. Without it, you could reference the path to a key in the agent, that didn't exist locally.
