### ISSUE TITLE
Per-host sudo options

### ISSUE THREAD

**Issue by steverweber** [ansible/ansible#2678]
ansible_sudo=True/False 
in inventory.

```
[krb5]
localhost
s8webera ansible_ssh_user=root ansible_sudo=False ansible_python_interpreter=/usr/bin/python2.7
```

This is important on mixed environment where some system dont have sudo installed.

Here is a current working solution that im using in production.
This was programmed as a hack.. So please could a project maintainer develop this fix correctly. 

file:///home/s8weber/srv/ansible/lib/ansible/runner/**init**.py

```
    def _executor_internal(self, host):
        ''' executes any module one or more times '''

        host_variables = self.inventory.get_variables(host)

        if host_variables.get('ansible_sudo', None):
          self.sudo = host_variables.get('ansible_sudo', None) == 'True' 

     ....
```

**Comment by mpdehaan** [comment]
This can be handled by addressing the sudoables in different plays right now.

Pull requests would be accepted, but the following invocation is inappropriate as it's causing a side effect with the constructor variable.

It should instead make sure it passed down appropriately.

**Comment by mpdehaan** [comment]
I should also point out that ansible_ssh_user=root need not be set if you just put "user: root" in your playbook.

Overrides are still available if needed.

I would also probably set your interpreter variable in a group variable as well instead of setting it host by host.

**Comment by mpdehaan** [comment]
Closing ticket since there is already a way to do this using multiple plays.

**Comment by steverweber** [comment]
Using multiple plays as a solution seems horrible!
I'm not sure you understand my use case.  Or perhaps I dont understand your solution.

Please reopen.and think this through.
I have many servers, some have sudo installed some dont.

I'm running an advanced setup that runs many different plays on many different servers.

Some plays require the user to not sudo because the play needs to evaluate ~/ as home dir.  Other plays require the user to be evaluated as root so sudo: yes is used.  But on some systems I cant sudo because its not installed, so I instead connect with a user such as root.

Now if i were to create new plays for every system that dont have sudo installed I would have to duplicate around 10 plays create new host groups and mark the plays without sudo...

An ansible_sudo var would clean this issue up nicely.

I'm happy to develop the fix.. I tried to do it..
But as I said previously:

```
This was programmed as a hack.. So please could a project maintainer develop this fix correctly.
```

I dont know how to do it correctly and could use some help.

**Comment by zenoamaro** [comment]
+1 for reopening.

`sudo`, `ssh_user`, and `root_user` are all per-host or per-group settings.

I can't have to update many different plays just because I have different configurations, when they all use the same logic apart from different values of `sudo`. Not only this is basically asking for human errors, but those are exactly the kinds of errors which provisioning is supposed to prevent in the first place.

If anything, these vars should be allowed ONLY in inventory, group, and host vars.

**Comment by mpdehaan** [comment]
You're responding to some outdated comments from 4 months ago.

sudo_user is already settable per task, sudo is already settable per task.

There is no variable root_user, ssh_user is "user" and must be set per play.
