### ISSUE TITLE
ability to configure shell module defaults like enabling strict mode

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#26792]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
shell

##### ANSIBLE VERSION

```
2.3.1
```

##### SUMMARY
It seems that at this moment there is no way to configure defaults for shell module. 

Adding extra lines like `set -euo pipefail` or `set -euox pipefail` to each shell call is an almost impossible task because it would involved playbooks and roles from too many sources (even external ones).

The solution for this is to allow us to define the shell mode inside `ansible.cfg` and/or a variable like  `ANSIBLE_SHELL_MODE`. 

Note: I would be more than happy to raise a PR that implements something like this but before writing code I would like to get feedback regarding how this should behave.

Examples:
```
# original shell command:
some_command | grep xxx

# as you can see this code is buggy if some_sommand returns an error code
set -euo pipefail # enable bash strictmode
some_command | grep xxx

# 2nd example works better because it will return correct error code
```
Most users writing Ansible scripts forget to enable strict mode or they do not even know about it.

By being able to inject or change the default mode for shell, we can avoid introducing hidden bugs inside Ansible tasks.

The only way to achieve this would be by allowing to change default behaviour of shell using Ansible configuration.

**Comment by bcoca** [comment]
by default the modules uses `/bin/sh` and the applicability of those switches varies a lot across OSs/distros/versions. I would create a setting that pairs with `executable`(which allows you to set a specific shell).

**Comment by ibotty** [comment]
I understand @bcoca in that it is desired.

I think it might make sense to configure it as per-host, because one should know whether (one set of) hosts use which shell.

There is the possibility to make it flexible with a `shell_prelude` attribute that just specifies commands to prepend for every shell invocation.  I would prefer a `safe_mode` attribute though.

I can look into auto-detecting shell capabilities, but I am not sure, that is needed for a first draft.

**Comment by bcoca** [comment]
Closing as per above, this is something that can be implemented in shell plugins.
