### ISSUE TITLE
No download on ansible.cc

### ISSUE THREAD

**Issue by tonk** [ansible/ansible#2682]
When I look at the website http://ansible.cc there is the link: "DOCS & DOWNLOADS" and when I click on that I go to the page http://ansible.cc/docs/. And there is nothing to download.

I also struggle to find an URL that points me to the stable versions. I guess these files should be simpler to find, so less 'gihub-experienced' sysadmins are able to get Ansible and git it running.

**Comment by srgvg** [comment]
It's there, but indeed not easy to find.

docs -> http://ansible.cc/docs/gettingstarted.html?highlight=downloads -> http://ansible.cc/releases/

**Comment by tonk** [comment]
Indeed, not easy to find. I (personally) think that the .deb's and .rpm's should only be two/three clicks away.

Maybe like: http://ansible.cc -> Downloads -> Ubuntu

And if the RPM's are available, why are they not in the download section?

If it's to difficult to find, people just go away and look for something else. And that would be to bad.

**Comment by mpdehaan** [comment]
Thanks, I think it would be nice to consider making this more prominent, though you can find these on the getting started page.

Will keep in mind when we redesign the site and so on.

Thanks!
