### ISSUE TITLE
with_sequence document error

### ISSUE THREAD

**Issue by tonk** [ansible/ansible#2683]
When I follow the documentation on the website and in the file

```
./docsite/latest/rst/playbooks2.rst:
```

and put 

```
with_sequence: start=0 stop=32 format=testuser%02x
```

in a playbook, I get

```
fatal: [master] => unknown error parsing with_sequence arguments: 'start=1 stop=10 format=testuser%02x'
```

Looking in the code it turns out that the `stop` option does not exist. `with_sequence` accepts `end` only.

This should be fixed in the docs or in the module.

**Comment by mpdehaan** [comment]
fix pushed and will be in next rebuild, thanks!
