### ISSUE TITLE
Include the module arguments when running python scripts via sudo

### ISSUE THREAD

**Issue by moshloop** [ansible/ansible#2684]
Currently when you use sudo to elevate permissions and run a python script the command logged to syslog does not include any information about the arguments given to the module.

e.g. _sudo:  ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c /usr/bin/python /home/ansible/.ansible/tmp/ansible-1366024328.03-136906168552928/command; rm -rf /home/ansible/.ansible/tmp/ansible-1366024328.03-136906168552928/ >/dev/null 2>&1_

This makes it difficult to audit what was actually executed for security or debugging purposes (kernel auditing would be overkill for this)

it would be nice if the command arguments where echoed e.g. 

_command: rm -rf /_

would result in the following:

_sudo:  ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo "rm -rf /"; /usr/bin/python /home/ansible/.ansible/tmp/ansible-1366024328.03-136906168552928/command; rm -rf /home/ansible/.ansible/tmp/ansible-1366024328.03-136906168552928/ >/dev/null 2>&1_

I would be willing to sponsor the development of this feature for $200

**Comment by mpdehaan** [comment]
I am having a little trouble following.

Have you seen what the ansible module themselves write to syslog on the remote machine?  Module arguments are logged by those modules.

Is this about what gets logged on the remote machine or the control machine?

**Comment by moshloop** [comment]
I have seen the logs created by ansible but they still have a few problems:

1) It does not indicate if elevated permissions were requested via sudo
2) It does not indicate who requested elevated permissions 
3) It logs to a different facility (or the change in facility could be configured incorrectly/maliciously) so it might be skipped by log shipping application applications or be difficult to correlate with a specific sudo command

**Comment by bcoca** [comment]
auth.log should have if sudo permissions were required, easy to correlate
both

On Thu, Apr 18, 2013 at 2:52 AM, Egis-Moshe notifications@github.comwrote:

> I have seen the logs created by ansible but they still have a few problems:
> 
> 1) It does not indicate if elevated permissions were requested via sudo
> 2) It does not indicate who requested elevated permissions
> 3) It logs to a different facility (or the change in facility could be
> configured incorrectly/maliciously) so it might be skipped by log shipping
> application applications or be difficult to correlate with a specific sudo
> command
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/2684#issuecomment-16560596
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
Yep, agree.   That all happens before the module runs so the module log doesn't know such things.
