### ISSUE TITLE
last_result.changed does not work when task is skipped

### ISSUE THREAD

**Issue by megoix** [ansible/ansible#2685]
Hi,

Consider the following:
- name: MySQL | Deploy basic large configuration file
  template: src=$templates/etc-my.cnf-large.j2 dest=/etc/my.cnf
  when_string: $ansible_memtotal_mb > '512'
  register: last_result
- name: MySQL | Restart MySQL, if new configuration file
  service: name=mysqld state=restarted
  only_if: '${last_result.changed}'

This will fail with the following message: "fatal: [xx] => Conditional expression must evaluate to True or False: ${last_result.changed}"

In essence it doesn't work when you apply a conditional to the action. I guess it boils down to if skipping equals changed. Which it does not strictly speaking. But if it cant be made that way, could you add "changed_or_skipped"?

**Comment by mpdehaan** [comment]
Larger issue is skipped doesn't register anything.   I'll think about this...  it seems it could at least register last_result with something so you could use the new 1.2 when and say something like:

when:   'changed' in last_result and last_result['changed']

or something similar.

Note: that syntax would require 1.2 and also that we register something for the variable on skipped scenarios.

**Comment by mpdehaan** [comment]
Fixed pushed, '.changed' is now available (and nothing else) in these cases.

**Comment by knightlabs** [comment]
Confirmed as working even when the previous task is skipped; thx again!

**Comment by mpdehaan** [comment]
BTW, megoix, if on 1.2:

when: last_result.changed

slightly more elegant.

also $foo is accessible as {{ foo }} since we can use Jinja2 everywhere.

I have updated the documentation on this but still need to update examples/playbooks in the checkout

**Comment by senorsmile** [comment]
This issue seems to be back in 1.3.3: 
- name: setup networking
  file: src=./etc.network.interfaces dest=/etc/network/interfaces owner=root group=root mode=0644
  register: networking_changed
- name: restart networking
  service: name=network state=restarted args={{ item }}
  - eth0
  - eth1
  
  when_changed: $networking_changed

##Conditional expression must evaluate to True or False: is_changed($networking_changed)

I have also tried using when: last_result.changed to no avail.

**Comment by senorsmile** [comment]
Never mind, the syntax seems to have changed.  This works: 
- name: setup networking
  file: src=./etc.network.interfaces dest=/etc/network/interfaces owner=root group=root mode=0644
  register: setupnetwork
- name: restart networking
  service: name=network state=restarted args={{ item }}
  - eth0
  - eth1
  
  when: setupnetwork.changed
