### ISSUE TITLE
${environment} local variable can be used with ansible 1.1+

### ISSUE THREAD

**Issue by arrfab** [ansible/ansible#2687]
Due to a code change between 1.0 and 1.1 a variable named "environment" can't be used because of this : 
"Another powerful feature I want to highlight — the new “environment” keyword can quickly swap in environment settings for different tasks, allowing users to easily work with multiple proxy servers (or no proxy server) when dealing with content coming from different sources."
That means that it can break current playbooks for people using a variable named "environment" (solution is to massively change that in the inventory/variables but a better one would be to internallly rename that environment keyword inside ansible)
Up to the maintainer (I've myself decided to rename the 'environment' variable to something else in our playbooks/inventory)

**Comment by mpdehaan** [comment]
Ok, I figured out why this was there, someone added a feature to easily debug everything by a template, including vars and hostvars, so it was added, just like that.

The use of environment is somewhat established there, so I think we'll leave this as is, at least for now.

I agree we need to watch this in the future as I didn't think about this when merging the commit.

Thanks!
