### ISSUE TITLE
Define more same roles with various variables.

### ISSUE THREAD

**Issue by mjablecnik** [ansible/ansible#26884]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

Define more same roles with various variables in playbook.

##### ANSIBLE VERSION

```
2.3.0.0
```

##### OS / ENVIRONMENT

Ubuntu 16.04 LTS

##### STEPS TO REPRODUCE

I have Ansible with this roles in playbook:
```
- { role: bwt-container, tags: ['bwt_en', 'bwt'], vars: { app_lang: "en" } }
- { role: bwt-container, tags: ['bwt_de', 'bwt'], vars: { app_lang: "de" } }

```
BWT application have various languages, which I would like define in vars.

##### EXPECTED RESULTS

I would like have defined more same roles with various variables..

##### ACTUAL RESULTS

 app_lang variable have "de" value because second app_lang variable rewrite first..

**Comment by alikins** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

 This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.
