### ISSUE TITLE
Specifying that a module is non-core

### ISSUE THREAD

**Issue by andy-maier** [ansible/ansible#26881]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
plugin.rst.j2
validate-modules

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY

The module documentation currently allows specifying these cases for the support of a module:

* core: module shipped by Ansible maintained by the core team.
* curated: module shipped by Ansible maintained by the community with core team oversight.
* community: module shipped by Ansible maintained by the community without core team oversight.

It does not allow specifying that a module is a not shipped with Ansible (i.e. a third party module).

##### STEPS TO REPRODUCE
The basic idea is to specify that a module is a "third-party" module. A third-party module is one that is not in the Ansible source repo, and that is not shipped with Ansible. The other type of module would be a "built-in" module (i.e. all the modules currently in the Ansible repo).

See PR #26896 for a proposal on how this could be specified.

##### EXPECTED RESULTS
See above.

##### ACTUAL RESULTS
See above.

**Comment by andy-maier** [comment]
PR #26896 has been created as a proposal on how this issue could be addressed.

**Comment by abadger** [comment]
Going to close the issue... we're going to want a proposal ticket so we don't need to have three tickets for the same issue.
