### ISSUE TITLE
validate-modules insists on GPL v3 license for modules

### ISSUE THREAD

**Issue by andy-maier** [ansible/ansible#26882]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
`validate-modules`

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The `validate-modules` checker insists on the GPL v3 license in the module being checked That makes it unusable for non-core modules.

##### STEPS TO REPRODUCE
The GPL license check should be performed only if the module is an Ansible core module.

Whether a module is an Ansible core module can for example be determined by looking at the `supported_by` attribute of `ANSIBLE_METADATA`. Note that issue #26881 proposes a new value for non-core modules, so finding any of the currently supported values (`core`, `community`, `curated`) would imply a core module, and any other value would imply a non-core module.

##### EXPECTED RESULTS
See above.

##### ACTUAL RESULTS
See above.

**Comment by alikins** [comment]
ping @mattclay @gundalow @sivel

**Comment by sivel** [comment]
All modules contributed to ansible must be GPLv3 regardless of the `supported_by` value.  

If you are not submitting the module to ansible, it need not meet these requirements, and the error can be ignored.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
