### ISSUE TITLE
RFE: consider a lookaside fact cache

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#2690]
Consider a lookaside fact cache that can pull (and store) facts in a local sqlite3 database such that you do not have to always hit hosts to get their fact data each time

This would prevent the "need to talk to hosts previously" case and save some communication time in other cases.

**Comment by jctanner** [comment]
@bcoca has started working on this in https://github.com/bcoca/ansible/tree/cache

**Comment by bcoca** [comment]
I might create a few branches before i'm done as I fine tune the direction
(and get feeback), currently working on diff way of subclassing dicts in 
https://github.com/bcoca/ansible/tree/cache branch

**Comment by mpdehaan** [comment]
I've merged the above and tweaked this some as indicated on https://groups.google.com/forum/#!topic/ansible-devel/aC-BjeBTMho ... still need to add some persistent examples

**Comment by mpdehaan** [comment]
We are currently thinking this might just happen via a callback, so I'm going to close this ticket for now, though we are still throwing some ideas around.
