### ISSUE TITLE
New-style variable interpolation syntax doesn't work with 'with_' style lookup plugins loops.

### ISSUE THREAD

**Issue by cmhamill** [ansible/ansible#2696]
In the following code:

```
vars:        
  foo:
    - /etc/resolv.conf
    - /etc/hosts
tasks:          
  - debug: msg={{ item }}
    with_file: foo

  - debug: msg={{ item }}
    with_file: "{{ foo }}"
```

neither task shown will work. The old '${var}' style works, of course. Updating this for consistency with the new-style 'with_items' might be worthwhile.

**Comment by mpdehaan** [comment]
Thanks, I made an explicit change for "with_items" and "with_nested" that probably needs to be applied more generically here as well.

**Comment by mpdehaan** [comment]
Done, tested in both forms, and both should be operational now.

Thanks for the heads up!
