### ISSUE TITLE
Group variable does not update if a host is a member of different groups

### ISSUE THREAD

**Issue by sasvirco** [ansible/ansible#26990]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Inventory group variables

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### CONFIGURATION
host_key_checking = False

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
I have a host, that is a member of 2 different groups. Both groups have a variable with the same name, but different value. If I run a playbook for the first group, then change to the second group, the variable value does not get updated. 

##### STEPS TO REPRODUCE
Create an inventory with 2 groups and the same host inside. Declare variable for both groups that has different values per group. Run a playbook against both groups that uses the variable, or use the debug module to print the value.

Create 2 groups with 2 group variables. Put the same host in both groups.
```yaml
Example:
[qa]
csxism01

[perf]
csxism01

[qa:vars]
vertical = qa

[perf:vars]
vertical = perf
```

##### EXPECTED RESULTS
ansible -m debug -a "var=vertical" -i inventories/64bit/ qa
csxism01 | SUCCESS => {
    "vertical": "qa"
}
ansible -m debug -a "var=vertical" -i inventories/64bit/ perf
csxism02 | SUCCESS => {
    "vertical": "perf"
}

##### ACTUAL RESULTS

ansible -m debug -a "var=vertical" -i inventories/64bit/ qa
csxism01 | SUCCESS => {
    "vertical": "qa"
}
ansible -m debug -a "var=vertical" -i inventories/64bit/ perf
csxism02 | SUCCESS => {
    "vertical": "qa"
}

```

```

**Comment by abadger** [comment]
Groups are not first class citizens in ansible.  Only hosts are.  So you're really defining a host several times here and giving it several different possible values for the vertical variable.  The last one defined wins (in this case, alphabetical sorting is defining the qa entry last).

If you want hosts with different values for the variable depending on the context I would do it something like this:
```
[qa]
csxism01-qa ansible_host=csxism01

[perf]
csxism01-perf ansible_host=csxism01

[qa:vars]
vertical = qa

[perf:vars]
vertical = perf
```

If you'd like to talk about other alternative methods to achieve what you want, ask on the mailing list or IRC channel.  There's lots of people there who are using ansible in various different ways.  I'll paste the list information below:

List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
