### ISSUE TITLE
ansible user module option groups wont append.

### ISSUE THREAD

**Issue by steverweber** [ansible/ansible#2703]
Module: http://ansible.cc/docs/modules.html#user

The user module can cause issues when trying to append a group to the users predefined groups.

Currently the 'groups' option sets the users groups and drops the extra ones they belong to.

Would be nice to have an option like; groups_append: [yes,no]
This option would add the user to the groups but not remove extra groups they might already belong to.

The workaround I use for this issue is running:

```
    - name: ensure user is member of group tomcat7
      shell: usermod -a -G tomcat7 $ansible_user_id

      # TODO FIX user module to allow appending a group
      #user: name=$ansible_ssh_user groups=tomcat7 state=present
```

**Comment by pytte** [comment]
This already exists ? 
append
If yes, will only add groups, not set them to just the list in groups.
Example: 

```
user: name=johnd groups=joes append=yes
```

**Comment by steverweber** [comment]
Opps, pytte is correct

Thanks.
