### ISSUE TITLE
ansible raw modules 

### ISSUE THREAD

**Issue by 191801737** [ansible/ansible#27046]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

raw  module
##### ANSIBLE VERSION

```

[root@centos7 ~]# ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/my_modules/']
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### CONFIGURATION

vim /etc/ansible/hosts
```ini
[h3c]
10.101.48.234 ansible_ssh_user=admin ansible_ssh_pass=admin
```
##### OS / ENVIRONMENT

CentOS Linux release 7.3.1611 (Core) 

##### STEPS TO REPRODUCE

```yaml
ansible h3c -m raw -a 'display version' -vvv
```

##### EXPECTED RESULTS

i have a switch H3C S5110-52P i want to use raw module to connect to it 
when i Execute the command  ```ansible h3c -m raw -a 'display version'``` 
it return  ```10.101.48.234 | UNREACHABLE! => ```

when i  Execute the command  "```ansible h3c -m raw -a 'display version' -vvv ```" 
i can see ansible has connected the switch  and execute the command hut how  the ansible return `UNREACHABLE`
##### ACTUAL RESULTS

```
ansible h3c -m raw -a 'display version' -vvv
Using /etc/ansible/ansible.cfg as config file
META: ran handlers
<10.101.48.234> ESTABLISH SSH CONNECTION FOR USER: admin
<10.101.48.234> SSH: EXEC sshpass -d12 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=admin -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/a10b93dbae -tt 10.101.48.234 'display version'
<10.101.48.234> (255, "\r\n******************************************************************************\r\n* Copyright (c) 2004-2015 Hangzhou H3C Tech. Co., Ltd. All rights reserved.  *\r\n* Without the owner's prior written consent,                                 *\r\n* no decompiling or reverse-engineering shall be allowed.                    *\r\n******************************************************************************\r\n\r\n<h3c5110>\r\nH3C Comware Platform Software\r\nComware Software, Version 5.20.99, Release 1108\r\nCopyright (c) 2004-2015 Hangzhou H3C Tech. Co., Ltd. All rights reserved.\r\nH3C S5110-52P uptime is 29 weeks, 3 days, 14 hours, 43 minutes\r\n\r\nH3C S5110-52P\r\n128M    bytes DRAM\r\n32M     bytes Flash Memory\r\nConfig Register points to Flash\r\n\r\nHardware Version is REV.A\r\nBootrom Version is 111\r\n[SubSlot 0] 48GE+4SFP Hardware Version is REV.A\r\n\r\n<h3c5110>", 'Shared connection to 10.101.48.234 closed.\r\n')
10.101.48.234 | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: Shared connection to 10.101.48.234 closed.\r\n", 
    "unreachable": true
}
```

**Comment by jborean93** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by lkx007** [comment]
@191801737 meet the same error, how to solve it?  thanks a lot.

**Comment by 191801737** [comment]
@lkx007 ansible 官方还没有配置H3C的模块，后来改用netmiko了。

**Comment by lkx007** [comment]
@191801737 多谢！！！
