### ISSUE TITLE
setup.py sdist converts symlinks to files breaking webdoc generation and other features

### ISSUE THREAD

**Issue by fredericlepied** [ansible/ansible#27105]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

webdocs

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/fred/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fred/external/ansible/.tox/py27/lib/python2.7/site-packages/ansible
  executable location = /home/fred/external/ansible/.tox/py27/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### OS / ENVIRONMENT

Fedora 25

##### STEPS TO REPRODUCE

python setup.py sdist

# and then from the extracted tarball:

make webdocs

```yaml

```

##### EXPECTED RESULTS

doc built

##### ACTUAL RESULTS

```
$ make webdocs
(cd docs/docsite/; CPUS=4 make docs)
make[1]: Entering directory '/home/fred/external/ansible/ansible-2.4.0/docs/docsite'
rm -rf htmlout
rm -rf _build
rm -f .buildinfo
rm -f objects.inv
rm -rf *.doctrees
Cleaning up minified css files
find . -type f -name "*.min.css" -delete
Cleaning up byte compiled python stuff
find . -regex ".*\.py[co]$" -delete
Cleaning up editor backup files
find . -type f \( -name "*~" -or -name "#*" \) -delete
find . -type f \( -name "*.swp" \) -delete
Cleaning up generated rst
rm rst/list_of_*.rst
rm: cannot remove 'rst/list_of_*.rst': No such file or directory
Makefile:28: recipe for target 'clean' failed
make[1]: [clean] Error 1 (ignored)
rm rst/*_by_category.rst
rm rst/*_module.rst
rm rst/playbooks_directives.rst
rm: cannot remove 'rst/playbooks_directives.rst': No such file or directory
Makefile:28: recipe for target 'clean' failed
make[1]: [clean] Error 1 (ignored)
rm rst/playbooks_keywords.rst
../bin/testing_formatter.sh
PYTHONPATH=../../lib ../bin/dump_keywords.py --template-dir=../templates --output-dir=rst/ -d ./keyword_desc.yml
PYTHONPATH=../../lib ../bin/plugin_formatter.py -t rst --template-dir=../templates --module-dir=../../lib/ansible/modules -o rst/
rendering: ipadm_ifprop
rendering: ecs_taskdefinition
rendering: selinux
rendering: cl_interface_policy
rendering: gce_lb
rendering: os_keystone_domain_facts
rendering: os_recordset
rendering: junos_rpc
rendering: pn_ospf
rendering: gcpubsub_facts
rendering: zabbix_maintenance
rendering: svc
rendering: nxos_gir_profile_management
rendering: kernel_blacklist
rendering: cs_snapshot_policy
rendering: nxos_command
rendering: os_user_facts
rendering: bigip_ucs
rendering: net_l3_interface
rendering: logentries
rendering: bigip_pool_member
rendering: avi_api_session
rendering: avi_networkprofile
rendering: os_floating_ip
rendering: avi_backup
rendering: win_feature
rendering: ce_evpn_global
rendering: win_service
rendering: ec2_elb
rendering: win_tempfile
rendering: ovirt_templates_facts
rendering: iam_policy
rendering: win_reboot
rendering: jenkins_plugin
rendering: avi_useraccountprofile
rendering: supervisorctl
rendering: rax_cbs_attachments
rendering: mysql_user
rendering: ec2_group
rendering: junos_l3_interface
rendering: consul_session
rendering: parted
rendering: ec2_win_password
rendering: ec2_vpc_vgw
rendering: win_domain_controller
rendering: vmware_maintenancemode
rendering: jenkins_job
rendering: ec2_lc_find
rendering: ce_netstream_global
rendering: sf_snapshot_schedule_manager
rendering: ec2_vpc_peer
rendering: ec2_vpc_subnet_facts
rendering: gunicorn
rendering: ovirt_storage_domains_facts
rendering: airbrake_deployment
rendering: digital_ocean_block_storage
rendering: netscaler_cs_action
rendering: ovirt_vmpools_facts
rendering: avi_gslbapplicationpersistenceprofile
rendering: yum_repository
rendering: bigmon_policy
rendering: vyos_interface
rendering: aos_template
rendering: ec2_ami_find
rendering: ec2_facts
*** ERROR: DEPRECATED MODULE MISSING 'deprecated' DOCUMENTATION: ../../lib/ansible/modules/cloud/amazon/_ec2_facts.py, ec2_facts ***

Makefile:53: recipe for target 'modules' failed
make[1]: *** [modules] Error 1
make[1]: Leaving directory '/home/fred/external/ansible/ansible-2.4.0/docs/docsite'
Makefile:311: recipe for target 'webdocs' failed
make: *** [webdocs] Error 2
```

**Comment by bcoca** [comment]
removed "from sdist tarball" as that does not matter for this error as it is present in the `/devel` branch no matter how you consume it.

**Comment by fredericlepied** [comment]
it matters as the sdist process is creating a regular file and btw making
the doc build process fail as it checks that it's a symlink.

**Comment by bcoca** [comment]
that is diff issue then, sdist should preserve symlinks, Ansible treats them in special ways so having it as a file is a problem.

**Comment by fredericlepied** [comment]
Could be but that's not the case. That's why I opened it this way as it'll
fail at release time and that's not a good thing ;-)

**Comment by abadger** [comment]
That's how distutils works and always has.  I believe i added some code to replace the files with symlinks but I believe that code activates at install time, rather than build time.  We could look at moving that code to run at a different/additional times but it seems strange to me that it would only be breaking now....

**Comment by bcoca** [comment]
it is rare that people do docs from sdist instead of git checkout, also it is rare that we rename modules

**Comment by abadger** [comment]
Oh, and this isn't the bin scripts; it's the modules that are renamed...  we don't have any code that changes those.

**Comment by abadger** [comment]
Found an upstream (setuptools) bug report: https://github.com/pypa/setuptools/issues/415#issuecomment-316788191  I've left a comment and told the maintainer about it so they can think about it.  We'll still need a workaround for the foreseeable future, though.

**Comment by abadger** [comment]
@fredericlepied could you try out: https://github.com/ansible/ansible/pull/27149  ? I don't have a clean tree right now.  That PR could use some cleanups so I don't repeat the code and data in multiple places but I think it will fix this issue.

**Comment by fredericlepied** [comment]
@abadger Just tested the change and it works. Good to go!

**Comment by fredericlepied** [comment]
@bcoca I'm running a continuous packaging experiment for Fedora and that's what
the package building process is doing. See the current report here:
http://38.145.33.116/dlrn/report.html

**Comment by fredericlepied** [comment]
@abadger I have added your patch and it seems the package build is failing: http://38.145.33.116/dlrn/a5/3d/a53dabf66474822ab5e2b001c8b3ce3d44dfb2d2_d7460d19/rpmbuild.log

**Comment by abadger** [comment]
How are you building?  If by continuous you mean you're checking out from the git repo and then you're doing a build and install, I can see how that error arises.  I just switched over to creating the SYMLINK_CACHE.json file at sdist build time so that it stays up to date if more symlinks are added.

However, that means you'd have to run python setup.py sdist if the file does not exist.  That might be a bad idea for how people are installing ansible now... Will have to look at how we could do it differently.  It is somewhat problematic, though.  We can only generate the cache if we have a repository checkout.  We run sdist from a repository checkout but build and install are run from both a repo checkout and from a tarball.  Have to think of just what we can do to make that safe.

**Comment by abadger** [comment]
@fredericlepied Okay, pushed what I hope is a fix for invoking setup.py build or setup.py install directly from a git checkout.  Give it another try in your CI system.

**Comment by fredericlepied** [comment]
@abadger it works. I was testing the wrong way on the previous run.
