### ISSUE TITLE
Typo - ismount should be is_mount

### ISSUE THREAD

**Issue by richharp** [ansible/ansible#27128]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by nitzmahone** [comment]
Can we get some context on this? Please fill out the relevant parts of the issue template...

**Comment by richharp** [comment]
There is a typo in the "Testing strings" section of this doc:
http://docs.ansible.com/ansible/latest/playbooks_tests.html
The reference to "ismount" should say "is_mount"
