### ISSUE TITLE
Variable precedence not working as described in docs

### ISSUE THREAD

**Issue by j9** [ansible/ansible#2713]
The official docs have a section about how Ansible uses variables and their precedence described [here](http://ansible.cc/docs/playbooks2.html#understanding-variable-precedence)

First two options say the following:
1. Any variables specified with –extra-vars (-e) on the ansible-playbook command line.
2. Variables loaded from YAML files mentioned in ‘vars_files’ in a playbook.

Unfortunately they are not working as described or I'm doing something wrong.

My scenario:
I have vars file with global variables called `globals.yml` and also I have vars file with defaults called `defaults.yml`, but sometimes I want to override some default variables from CLI with `--extra-vars`. So in the example below, I am trying to override the `sshd_port` variable .

Sample playbook and detailed explanation follows:

Playbook with referenced files:
- [playbook sshd_config](http://pastebin.com/JybEvgwh)
- [task file for playbook](http://pastebin.com/V7hvEHzg)
- [globals.yml and defaults.yml](http://pastebin.com/5vz9y4gx)
- [sshd_config_key_only.j2 template used for inclusion in task file](http://pastebin.com/8C5UyksF)

And here is the shell command:
`$> ansible-playbook playbooks/common/sshd_config.yml --extra-vars="sshd_port=29" --limit test`

Resulting in no changes on the final teamplate output (sshd_port remains default - 22).

An interesting thing is if I delete the `defaults.yml` line from `vars_files:` section in playbook and move the same variables from `defaults.yml` to playbook `vars:` section, the override **is** working.

`ansible-playbook` version I'm using is:
ansible-playbook 1.2 (devel 3238d0947d) last updated 2013/04/18 17:57:19 (GMT +300)

**Comment by mpdehaan** [comment]
So if I understand correctly you are saying vars_files trumps extra-vars but vars does not, yes?

**Comment by j9** [comment]
Yes. extra-vars can override vars, but does not work with vars_files.

**Comment by mpdehaan** [comment]
Docs have been updated, per mailing list thread on the same subject.

Should be clearer now.  You can still use extra vars in vars_files paths BTW.
