### ISSUE TITLE
The copy module leaves .tmp files behind on successful copy

### ISSUE THREAD

**Issue by pol** [ansible/ansible#2715]
Expected Behavior:
When using the copy module, src files are copied to dest and tmp src files are left on dest only when there is a failure.

Behavior: 
The tmp files are left on the server even if there is a success.

Note: it appears that the behavior or module#atomic_replace changed.

**Comment by pol** [comment]
Note, this also affects the template module (for the same reason presumably).

**Comment by bcoca** [comment]
a update to atomic_replace (during a cron module cleanup #2698 ) caused this, I'm working on a fix

**Comment by bcoca** [comment]
The change to module_common was reverted but I'm still updating the atomic_replace function as the cron module will have issues otherwise.

**Comment by mpdehaan** [comment]
I have reverted the offending commit, thanks!
