### ISSUE TITLE
NXOS scp file from server

### ISSUE THREAD

**Issue by sanjmonkey** [ansible/ansible#27163]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

NXOS SCP file from server (nxos_copy ?)

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.4.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
No modifications from standard

##### OS / ENVIRONMENT
Controlling NXOS devices, eg: 7.0(3)I6(1)

##### SUMMARY

It would be nice to have native support to tell NXOS hosts to go fetch files from scp servers, such as new OS images / SMU's etc.  Much in the same way as @jedelman8 did in [example play](https://github.com/jedelman8/nxos-ansible/blob/master/example-playbooks/how-to/examples-copy.yml)

##### STEPS TO REPRODUCE

```yaml
tasks:
    # copy config file from server to switch
    - nxos_copy:
        server_host=192.168.200.56
        server_path='/home/cisco/Public/switch_config.cfg'
        server_un=cisco
        server_pw=cisco
        copy_type=scp
        local_path='bootflash:switch_config1.cfg'
        vrf=management
        host={{ inventory_hostname }}

```

##### EXPECTED RESULTS

Files to appear in the hosts local_path

##### ACTUAL RESULTS

```

```

**Comment by calfonso** [comment]
This is now supported in the latest release (2.4).
