### ISSUE TITLE
There are two doc pages about error handlers which don't refer to each other

### ISSUE THREAD

**Issue by alexxa** [ansible/ansible#27165]
##### ISSUE TYPE

 - Documentation Report

##### ANSIBLE VERSION

```
devel
```

##### SUMMARY

There are two separate doc pages:

1.  [Error Handling In Playbooks ](http://docs.ansible.com/ansible/latest/playbooks_error_handling.html)
https://github.com/ansible/ansible/blob/stable-2.3/docs/docsite/rst/playbooks_error_handling.rst
2.  Blocks and its subsection [Error Handling in Blocks](http://docs.ansible.com/ansible/latest/playbooks_blocks.html#error-handling)
https://github.com/ansible/ansible/blob/stable-2.3/docs/docsite/rst/playbooks_blocks.rst

I believe it will be beneficial to merge them accordingly or to add references to each other. Also, I would add that `ignore_errors: yes` works on Block level, so one doesn't need to use it with every task in a playbook if it's a set of tests which may or may not fail.

**Comment by acozine** [comment]
Still an issue - the pages in question are now https://docs.ansible.com/ansible/devel/user_guide/playbooks_blocks.html#error-handling and https://docs.ansible.com/ansible/devel/user_guide/playbooks_error_handling.html.
