### ISSUE TITLE
setup module gives incorrect fqdn for hostname.

### ISSUE THREAD

**Issue by tonk** [ansible/ansible#2721]
When I run the setup module on my `CentOS 6` box, I get `master.tonkersten.com` for the `hostname` and for the `fqdn`. This happens since the switch to `platform.node()`

On `Ubuntu` it works as designed, only giving the `hostname` and **not** the `fqdn`.

It would be very handy to have the original results back, so I suggest the following patch in the `library/setup` file:

**`line 142`**

```
self.facts['hostname'] = platform.node()
```

changed to

```
self.facts['hostname'] =  platform.node().partition('.')[0]
```

I can create a pull request, if needed.

**Comment by mpdehaan** [comment]
Agreed.

A pull request would be great, thanks!

**Comment by tonk** [comment]
OK. I'll create one
