### ISSUE TITLE
NFTables module

### ISSUE THREAD

**Issue by jan-xyz** [ansible/ansible#27229]
#### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
- nftables

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION
- standard

##### OS / ENVIRONMENT
- macOS Sierra

##### SUMMARY
Seeing that Debian moved to nftables in version 9 (Stretch) and others will probably follow. Is there any plan on the roadmap to support the new netfilter tool?

**Comment by bcoca** [comment]
Nothing on roadmap, but all current firewall modules were community driven.

**Comment by vladimirtiukhtin** [comment]
Any chance this to be implemented?

**Comment by varac** [comment]
[Debian buster release is planned for July 6 2019](https://lists.debian.org/debian-devel-announce/2019/06/msg00003.html), and it [uses the nftables framework by default](https://wiki.debian.org/nftables).
A nftables module would be awesome to have soon !

**Comment by lunarthegrey** [comment]
+1 since Debian 10 (Buster) uses it by default now.

**Comment by andreagrax** [comment]
+1 CentOS 8 too

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. We are no longer accepting new modules in this repository.

You may wish to re-submit this feature request to https://github.com/ansible-collections/community.general

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
