### ISSUE TITLE
update from ansible 0.9 -> 1.1 forced a changed sudo configuration, related to #2475

### ISSUE THREAD

**Issue by holgerkoch** [ansible/ansible#2723]
I've installed ansible 0.9 and configured the following sudo entry:

Cmnd_Alias AMBOS_CMD = /bin/sh -c /usr/bin/python /opt/ansible/.ansible/tmp/_/_; rm -rf /opt/ansible/.ansible/tmp/*
ansible ALL = NOPASSWD: AMBOS_CMD

```
start a ansible playbook execution
ansible copied the ressources and connect to the target and login as a none-privilege user ansible
the ansible user makes a sudo call and execute the script as user root
ansible delete the ressources
```

With this sudo entry, all works fine without any password prompt. Why so complicated? Unfortunaly, i got no permission for the simple

ansible ALL = NOPASSWD:ALL

because of security reason.

Then i make a update to 1.1 and the privileged ansible execution hangs. After a review, i found the space character forward the /usr/bin/python. So the sudo entry doesn't match anymore and it will be prompted for a password. I changed the sudo entry to:

Cmnd_Alias AMBOS_CMD = /bin/sh -c \ /usr/bin/python /opt/ansible/.ansible/tmp/_/_; rm -rf /opt/ansible/.ansible/tmp/*
ansible ALL = NOPASSWD: AMBOS_CMD

and all work fine again.

Is it possible to delete the space character? And it will be great, if the execution line will be changeless.

Thank you. Best regards.

Holger

PS: Please forgive my terrible english.

**Comment by mpdehaan** [comment]
Hi Holger,

I've pushed a fix to the development branch.

Thanks!
