### ISSUE TITLE
lookup('password'/'passwordstore') returns different passwords if executed for multiple hosts

### ISSUE THREAD

**Issue by tbe** [ansible/ansible#27277]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lookup-password, passwordstore

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /home/tberger/repos/1und1/influxservice/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Dec 29 2016, 13:02:44) [GCC 4.9.3]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
If `lookup('password',...)` or lookup('passwordstore',...) is used within a run on multiple hosts, different passwords are returned on the first call within the play, if the password must be generated.

We use the lookup to set passwords on a database cluster with logical replication. On the first run, the hosts has different passwords set.

##### STEPS TO REPRODUCE
Example:

```yaml
---
- hosts: influxhosts
  tasks:
  - name: "password run1"
    debug:
      msg: "password: {{ lookup('passwordstore','test/password1 create=true') }}"
  - name: "password run2"
    debug:
      msg: "password: {{ lookup('passwordstore','test/password1 create=true') }}"
```

##### EXPECTED RESULTS
Both debug lines produce exactly the same output for all hosts

##### ACTUAL RESULTS

In the first run, the passwords are different

```

PLAY [influxhosts] ************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
ok: [db1]
ok: [db2]

TASK [password run1] **********************************************************************************************************************************************************************************************************************************************************
ok: [db1] => {
    "msg": "password: BFkWBg8n5tSzRO2H"
}
ok: [db2] => {
    "msg": "password: z5RwZeNR7a0GXmrO"
}

TASK [password run2] **********************************************************************************************************************************************************************************************************************************************************
ok: [db1] => {
    "msg": "password: z5RwZeNR7a0GXmrO"
}
ok: [db2] => {
    "msg": "password: z5RwZeNR7a0GXmrO"
}

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
db1: ok=3    changed=0    unreachable=0    failed=0
db2 : ok=3    changed=0    unreachable=0    failed=0

```

**Comment by 3onyc** [comment]
This probably ties into #23816 and the need for some kind of locking

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This is not a bug, it is by design, to achieve what you want do the following:

```
 - set_fact: mypass=lookup(...)
   run_once: true
```
This will generate the password once and with the same value for all hosts in the play batch.

We'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
