### ISSUE TITLE
ios_command failure for cisco with rc=1

### ISSUE THREAD

**Issue by vvs1987** [ansible/ansible#27275]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

IOS 
##### ANSIBLE VERSION

```
-bash-4.1$ ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.6.6 (r266:84292, Aug  9 2016, 06:11:56) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]

```

##### OS / ENVIRONMENT

NA
##### SUMMARY

i am trying to run a simple ios_command, the ios command gives proper output when run on the cisco switch but returns rc=1 when run 

##### STEPS TO REPRODUCE

```
- name: Ak BGP Neighbor check
ignore_errors: yes
ios_command:
commands:
- sh ip bgp neighbors xxx.xxx.xxx.x advertised-routes
provider: "{{ cli }}"
register: AkCheck
```

##### EXPECTED RESULTS

•	hostname # sh ip bgp neighbors xxx.xxx.xxx.x advertised-routes 
BGP table version is 6, local router ID is xxx.xxx.xxx.5
Status codes: s suppressed, d damped, h history, * valid, > best, i - internal, 
              r RIB-failure, S Stale, m multipath, b backup-path, f RT-Filter, 
              x best-external, a additional-path, c RIB-compressed, 
Origin codes: i - IGP, e - EGP, ? - incomplete
RPKI validation codes: V valid, I invalid, N Not found

     Network          Next Hop            Metric LocPrf Weight Path
 *>  xxx.xxx.xxx.x    0.0.0.0                  0         32768 i

Total number of prefixes 1 

##### ACTUAL RESULTS

```
fatal: [***********]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "auth_pass": null,
            "authorize": null,
            "commands": [
                "sh ip bgp neighbors xxx.xxx.xxx.x advertised-routes"
            ],
            "host": null,
            "interval": 1,
            "match": "all",
            "password": null,
            "port": null,
            "provider": {
                "auth_pass": null,
                "authorize": true,
                "host": "***********",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "cli",
                "username": "fc.abc"
            },
            "retries": 10,
            "ssh_keyfile": null,
            "timeout": null,
            "username": null,
            "wait_for": null
        }
    },
    "msg": "ditional-path, c RIB-compressed, \r\nOrigin codes: i - IGP, e - EGP, ? - incomplete\r\nRPKI validation codes: V valid, I invalid, N Not found\r\n\r\n     Network          Next Hop            Metric LocPrf Weight Path\r\n *>  xxx.xxx.xxx.x    0.0.0.0                 ",
    "rc": 1
}

```

**Comment by jborean93** [comment]
ping @privateip @rcarrillocruz

**Comment by calfonso** [comment]
@vvs1987 would you mind testing this on our devel branch as we believe it's fixed and will be part of our 2.4 release. Thanks!

**Comment by rcarrillocruz** [comment]
fixed on https://github.com/ansible/ansible/pull/27100

**Comment by calfonso** [comment]
Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
