### ISSUE TITLE
Unable to run ConfigureRemotingForAnsible.ps1 on Windows Nano Server to allow ansible connection

### ISSUE THREAD

**Issue by zihanzheng** [ansible/ansible#27304]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
[ConfigureRemotingForAnsible.ps1](https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1)

##### ANSIBLE VERSION
```
ansible 2.3.1.0
```

##### CONFIGURATION
none

##### OS / ENVIRONMENT
Running Ansible from a Linux Server, managing Windows Nano Servers

#####  #SUMMARY
This issue is also reported in #23990, but it lacks some issue details and thus could not be resolved. I list more details of the issue here so let's see if anyone could help.

For normal windows server (Windows Servers **except** Windows Nano Server), in order to allow ansible connection, authentication, and Powershell commands execusion, we need to run a Powershell script [ConfigureRemotingForAnsible.ps1](https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1) that is given in this ansible repository on the Windows Server.
However, when I run the script in a Windows Nano Server, it gives:
![Image of Yaktocat](https://cloud.githubusercontent.com/assets/1503131/25411533/40fb2122-29eb-11e7-88b1-543d55024fd2.png) 

Seems like Nano Server does not support a bunch of Powershell commands, so the script is not able to run on a Nano Server. Is is true that Nano Server cannot allow ansible connection? Is there any way to go around this issue, so I can allow ansible connection on a Nano Server?

##### STEPS TO REPRODUCE
First, copy [ConfigureRemotingForAnsible.ps1](https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1) to the Nano Server. What I did is copy the code to the nano server using[ Windows Powershell's Copy-Item command](https://msdn.microsoft.com/en-us/library/mt708806(v=vs.85).aspx). 

Then I connect to the Nano Server in Powershell and run 
`powershell.exe -File ConfigureRemotingForAnsible.ps1 -EnableCredSSP`
to run the script I just copied to the Nano Server. 
Then the error message shown in the Summary section shows up.

##### EXPECTED RESULTS
This is what I get after I run the script on a Windows Server 2016
```
PS C:\Users\Administrator\Documents> C:\Users\Administrator\Desktop\ConfigureRemotingForAnsible.ps1
Self-signed SSL certificate generated; thumbprint: 8501072A86FD6AD6F6A679091BCFDE9A16A6CD9E


wxf                 : http://schemas.xmlsoap.org/ws/2004/09/transfer
a                   : http://schemas.xmlsoap.org/ws/2004/08/addressing
w                   : http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd
lang                : en-US
Address             : http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous
ReferenceParameters : ReferenceParameters

Ok.
```
##### ACTUAL RESULTS
This is what I get after I run the script on a Windows Nano Server
```
[10.0.1.252]: PS C:\Users\Administrator\Documents> powershell.exe -File ConfigureRemotingForAnsible.ps1 -EnableCredSSP
Unable to find type [System.Diagnostics.EventLog].
At C:\Users\Administrator\Documents\ConfigureRemotingForAnsible.ps1:153 char:5
+ If ([System.Diagnostics.EventLog]::Exists('Application') -eq $False - ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Diagnostics.EventLog:T 
   ypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

Any help or suggestion to go around this issue is appreciated!

**Comment by jborean93** [comment]
Hey @zihanzheng I'm going to close this issue and reference it here https://github.com/ansible/ansible/issues/23990 as there is an existing conversation there. Currently the ConfigureRemotingForAnsible.ps1 won't work with Nano server as it uses some .NET classes which are not available in .NET core. I haven't played with Nano yet so I can't say whether Ansible works with it but considering the full .NET framework is not available in Nano I would say a fair few modules would suffer from the same issue.

Feel free to add some more tests or thoughts to this issue at https://github.com/ansible/ansible/issues/23990
