### ISSUE TITLE
Add variable suffix to inventory hostname

### ISSUE THREAD

**Issue by xswqaz** [ansible/ansible#27305]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
ansible-2.3.1.0-1.el7.noarch
```

##### OS / ENVIRONMENT

```
3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

##### SUMMARY

I want to add default suffix to inventory hostname
eg.
```
[testgroup]
hostnameA
hostnameB
```
Failed to get hostname which formatted fqdn ( like hostnameA.site1.local ) in group_vars
```
{{ groups['testgroup'] }} 
```
```
[all:vars]
ansible_host="{{ inventory_hostname }}.{{domain}}.local"
```
was useless

Is there any way for this?

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

```
ok: [test] => {
    "testgroup": [
        "hostnameA.site1.local,
        "hostnameB.site1.local"
    ]
}
```

##### ACTUAL RESULTS

```
ok: [test] => {
    "testgroup": [
        "hostnameA",
        "hostnameB"
    ]
}
```

**Comment by abadger** [comment]
The host entries in an ansible inventory don't map one::one to actual dns hostnames so this isn't a natural thing to do.   You'll probably find more help on the mailing list or IRC channel about how you might automatically combine the ansible host with a domain name as there's many users there who have solved many differing problems over time.  I'll paste the mailing list and irc information below.

List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
