### ISSUE TITLE
empty plays don't run anymore

### ISSUE THREAD

**Issue by tgerla** [ansible/ansible#2732]
Commit 32fb6c8 (Allow handlers to run in between pre_tasks, roles, tasks...) broke an idiom I was using in lamp_haproxy...an empty task list to force fact-gathering, like this:

```

---
- hosts: monitoring
  tasks:

- hosts: webservers
  user: root

...actual tasks here...
```

Now the monitoring play doesn't fire at all, so facts don't get gathered. Adding a debug task to that play works fine and is a suitable workaround.

**Comment by mpdehaan** [comment]
Yep, I think there is something that sets run_plays = True for empty plays, and now I think with roles meta tasks it's non-empty now. 

Looking now.

**Comment by mpdehaan** [comment]
fix pushed, now checking against 4 (the number of meta 'handler flush' tasks you don't see) instead of 0.
