### ISSUE TITLE
delegate_to uses None when host ansible_ssh_host var specified

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible#27351]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
delegate_to

Have tested using as an option for the `shell` & `debug` tasks

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.4.0
  config file = None
  configured module search path = [u'/Users/alancoding/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.4.0-py2.7.egg/ansible
  executable location = /Users/alancoding/.virtualenvs/ansible/bin/ansible
  python version = 2.7.10 (default, Jul 13 2015, 12:05:58) [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
```

also tested 2.3.1.0 and 2.2.3.0. Same behavior was observed for all versions tested.

##### CONFIGURATION
defaults only

##### OS / ENVIRONMENT
N/A

##### SUMMARY
If you `delegate_to` a host with `ansible_ssh_host` set as a hostvar, the delegated host will be `None` (see `[target_host -> None] `  in the play output). Actions that should run on the machine delegated to will not run there.

##### STEPS TO REPRODUCE
Run the following playbook:

```yaml
---
- name: produce bug
  hosts: target_host
  gather_facts: false
  tasks:

    - debug: msg='debug message'
      delegate_to: delegator
```

against the following inventory file

```ini
delegator ansible_ssh_host=delegator_new
target_host
```

##### EXPECTED RESULTS
```
$ ansible-playbook -i tools/docker-custom/inventories/inventory_isolated_large tools/docker-custom/customize.yml -vvv
ansible-playbook 2.4.0
  config file = None
  configured module search path = [u'/Users/alancoding/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.4.0-py2.7.egg/ansible
  executable location = /Users/alancoding/.virtualenvs/ansible/bin/ansible-playbook
  python version = 2.7.10 (default, Jul 13 2015, 12:05:58) [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
No config file found; using defaults
Parsed /Users/alancoding/Documents/ansible-tower/tools/docker-custom/inventories/inventory_isolated_large inventory source with ini plugin

PLAYBOOK: customize.yml *******************************************************************************************************************************************************************************
1 plays in tools/docker-custom/customize.yml

PLAY [produce bug] ************************************************************************************************************************************************************************************
META: ran handlers

TASK [debug] ******************************************************************************************************************************************************************************************
task path: /Users/alancoding/Documents/ansible-tower/tools/docker-custom/customize.yml:7
ok: [target_host -> delegator_new] => {
    "msg": "debug message"
}
META: ran handlers
META: ran handlers

PLAY RECAP ********************************************************************************************************************************************************************************************
target_host                : ok=1    changed=0    unreachable=0    failed=0   
```

This result is obtained if you change `ansible_ssh_host=delegator_new` inside of the inventory file to `ansible_host=delegator_new`.

##### ACTUAL RESULTS
```
$ ansible-playbook -i tools/docker-custom/inventories/inventory_isolated_large tools/docker-custom/customize.yml -vvv
ansible-playbook 2.4.0
  config file = None
  configured module search path = [u'/Users/alancoding/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.4.0-py2.7.egg/ansible
  executable location = /Users/alancoding/.virtualenvs/ansible/bin/ansible-playbook
  python version = 2.7.10 (default, Jul 13 2015, 12:05:58) [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
No config file found; using defaults
Parsed /Users/alancoding/Documents/ansible-tower/tools/docker-custom/inventories/inventory_isolated_large inventory source with ini plugin

PLAYBOOK: customize.yml *******************************************************************************************************************************************************************************
1 plays in tools/docker-custom/customize.yml

PLAY [produce bug] ************************************************************************************************************************************************************************************
META: ran handlers

TASK [debug] ******************************************************************************************************************************************************************************************
task path: /Users/alancoding/Documents/ansible-tower/tools/docker-custom/customize.yml:7
ok: [target_host -> None] => {
    "msg": "debug message"
}
META: ran handlers
META: ran handlers

PLAY RECAP ********************************************************************************************************************************************************************************************
target_host                : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by nitzmahone** [comment]
Interesting- do you see the same result with `ansible_host`? If not, I'm thinking it's a place where we're not fully sync'ing the values between those two (as well as a reminder that it's probably past time to deprecate `ansible_ssh_host` altogether).

**Comment by bcoca** [comment]
@nitzmahone `ansible_ssh_host` is not deprecated, its just plugin specific, `ansible_host` is the 'general one'

**Comment by AlanCoding** [comment]
> Interesting- do you see the same result with `ansible_host`? If not, I'm thinking it's a place where we're not fully sync'ing the values between those two

In that case, it delegates to the value of `ansible_host` (or at least that's what it prints out), as in the expected result. Which one should be used was not obvious to me. For clarity, consider the inventory:

```
delegator ansible_host=delegator_new
target_host
```

(apologies for calling it "delegator" when it may have more accurately be called "delegatee")

In this case, the stdout reads `[target_host -> delegator_new]`, I presume that's correct.

The case I originally hit, someone actually had used the same value for the host's name as in ansible_ssh_host, like `delegator ansible_ssh_host=delegator`. This _also_ causes it to use None.

I anticipated that somewhere there's a hard-coded swap done for `ansible_host`, but neglecting `ansible_ssh_host`. I found 4 places in the code where those 2 things occur in the same file, these all looked like promising causes of the behavior, but my attempts at a fix with that approach have so-far been unsuccessful.

https://github.com/ansible/ansible/search?l=Python&q=delegate_to+ansible_host&type=&utf8=%E2%9C%93

Additional note: even if you fully deprecated `ansible_ssh_host` I would expect that it would actually fix the case of `delegator ansible_ssh_host=delegator`, because assigning any other random hostvar doesn't cause it to delegate to None.

**Comment by nitzmahone** [comment]
@bcoca: But that's not the case (unless something's changed since the last time I looked)... We make some efforts to make them appear equivalent, but it looks like we missed at least one. What I'm saying is that maybe it's time to consider deprecating it- we have an ongoing maintenance hassle with it that's only got the potential to get worse/more complicated with first-class plugin specific connection vars.

**Comment by bcoca** [comment]
the config project should make it so this is transparent vs each plugin having to deal with the vars, make it so one time in config, rest of the time it is 'resolved for you'

**Comment by jladdjr** [comment]
@nitzmahone - I'm looking into updating our inventory files and playbooks to not use `ansible_ssh_` vars. 

http://docs.ansible.com/ansible/latest/intro_inventory.html mentions that `ansible_ssh_user`, `ansible_ssh_host` and `ansible_ssh_port` are deprecated. I see places where we also use `ansible_ssh_pass` and `ansible_ssh_control_path`. Are those deprecated as well?

**Comment by nitzmahone** [comment]
@jladdjr I'd assume ssh_pass would also be deprecated (in favor of `ansible_password`), but control_path should remain an SSH-specific arg whenever we fix that for real.

**Comment by nitzmahone** [comment]
@AlanCoding @bcoca here's where the problem occurs: https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/play_context.py#L343-L365 - this code appears to be a little out of sync with how we handle hosts in a number of other places (esp since `ansible_ssh_host` is hardcoded in a number of places, where this one isn't). At the end of the day, I think the delegation is correct, it's just an output display issue because of the way the default callback plugin looks up `ansible_host` and other things not always setting it. I can think of a few different ways to fix it, but it would depend on how we'd ultimately like this to work. I don't *think* we want to support ansible_X_host as a special thing forever (just "ansible_host"), but I could be wrong...

**Comment by bcoca** [comment]
i'm changing how that works in anisble-config, it wont be a catchall but specific declarations by plugin

**Comment by nitzmahone** [comment]
@bcoca: curious to see how that pans out- I've got a mostly backwards-compatible design for the connection var delegation stuff in my head. I'm assuming what you're doing in config won't directly address that, but would allow plugins to declare config/default value key names for their various vars...

**Comment by bcoca** [comment]
Soo WIP https://github.com/bcoca/ansible/tree/config_from_plugin_docs , very much still in flux, but ssh plugin has near 'final' doc format.

**Comment by paulRbr** [comment]
Hi all, 

I have had a similar problem when using `ansible_host` variable that depends on the `inventory_hostname` variable (see steps below). Please let me know if you want me to open another issue.

_Tested against 2.3.1.0 and latest `devel` branch._

##### STEPS TO REPRODUCE

Run the following playbook:

```yml
---
- name: produce bug
  hosts: target_host
  tasks:

    - debug: msg='debug message'
      delegate_to: delegator
```

against the following inventory file

```
delegator ansible_host="private.{{ inventory_hostname }}"
target_host
```

##### EXPECTED RESULTS

```
TASK [debug] ******************************************************************************************************************************************************************************************
task path: /whever/test.yml:7
ok: [target_host -> private.delegator] => {
    "msg": "debug message"
}
```

##### ACTUAL RESULTS

```
TASK [debug] ******************************************************************************************************************************************************************************************
task path: /whever/test.yml:7
ok: [target_host -> private.{{ inventory_hostname }}] => {
    "msg": "debug message"
}
```

**Comment by kivilahtio** [comment]
This bug is biting me as well.

Using ansible 2.5.3

**Comment by diranetafen** [comment]
Hi
I've got the same issue on my own environment:
- tower (containerize version) : **ansible 2.5.3**

**_Bypass method_**
I've bypassed this bug by downgrading ansible to **2.4.3.0** ! Now all is working as expected
_command line_: pip install -I ansible==2.4.3.0

**Comment by charlyhue** [comment]
There is a workaround for this issue. You can use a block:

```
- block:
    - name: Include file
      include_tasks: tasks.yml
delegate_to: localhost
```

[Documentation](https://docs.ansible.com/ansible/2.5/user_guide/playbooks_blocks.html)

**Comment by bcoca** [comment]
So this seems to be specific to `ansible_ssh_host` as `ansible_winrm_host` does display the correct output. This is probably caused by some of the old 'special behaviour' assigned to `ansible_ssh_host`.

**Comment by srgvg** [comment]
FYI this is also biting the openshift-ansible project, see https://github.com/openshift/openshift-ansible/issues/9018#issuecomment-410316084

**Comment by sivel** [comment]
This appears to be fixed now:

```
TASK [debug] *********************************************************************************************************************************************************************************************************************************
ok: [target_host -> delegator] => {
    "msg": "debug message"
}
```

I'm going to go ahead and close this. If you are still having problems, please open a new issue.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
