### ISSUE TITLE
copy module copies contents of CWD when src=""

### ISSUE THREAD

**Issue by kostrzewa9ld** [ansible/ansible#27363]
##### ISSUE TYPE

 - Bug Report / Question

##### COMPONENT NAME

plugin/module: copy

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT
```
Linux Mint 18.1 Serena (GNU/Linux 4.4.0-81-generic x86_64)
```

##### SUMMARY

When copy module is invoked with `src` set to an empty path it copies contents of the current working directory.

##### STEPS TO REPRODUCE
```
mkdir /tmp/foo /tmp/bar
touch /tmp/foo/baz
cd /tmp/foo && ansible -m copy -a "src= dest=/tmp/bar" -c local localhost
ls -l /tmp/bar/baz
```

##### EXPECTED RESULTS
Copy module fails.

##### ACTUAL RESULTS
Copy module copied contents of current working directory to destination.

**Comment by nitzmahone** [comment]
IMO this is a bug (probably a behavior of `_find_needle` that we should paper over by ensuring the source path is not empty in the action plugin).
