### ISSUE TITLE
Could not find imported module support code for 'Ansible.ModuleUtils.PowerShellLegacy'

### ISSUE THREAD

**Issue by yuriyostapenko** [ansible/ansible#27374]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Windows support

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/test/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

Irrelevant

##### OS / ENVIRONMENT

Ubuntu 16.04.2 (WSL) control machine to Windows Server 2016 with WMF 5.1
##### SUMMARY

Most modules that can be run on Windows fail in latest 2.4 `devel` branch: all `win_*` I tried and `setup` too.
However, `raw` does work.

Switching to ...ansible.git@stable-2.3 everything works again.

##### STEPS TO REPRODUCE

```sh
sudo -H pip install git+https://github.com/ansible/ansible.git@devel
ansible -i dev -m setup [windows_target]
```

##### EXPECTED RESULTS

Successful task execution
##### ACTUAL RESULTS

```
windows-target | FAILED! => {
    "failed": true,
    "msg": "Could not find imported module support code for 'Ansible.ModuleUtils.PowerShellLegacy'."
}
```

**Comment by nwchandler** [comment]
I just ran into this too... Not sure what happened, but in my case, at least, when I did a pip install of a local development branch into a virtual environment, it did not copy over the PowerShell modules into my virtual environment's /lib/python2.7/site-packages/ansible/module_utils/powershell/ directory. I copied them over manually, and the error went away... I don't know why they were not copied automatically, but this may allow you to work around the issue if you are running into the same thing I did...

**Comment by yuriyostapenko** [comment]
@nwchandler, thanks, that worked!
I can confirm that error is due to files missing in `module_utils/powershell/`

**Comment by nitzmahone** [comment]
Thanks for the extra bit of data that it only broke on a pip install- looks like we need to update some of the paths on setup.py to get the Powershell modules (and including the subtrees).

**Comment by yuriyostapenko** [comment]
@nitzmahone, I've submitted a PR for this one.
