### ISSUE TITLE
Please pin the version of dependencies on releases.

### ISSUE THREAD

**Issue by srikalyan** [ansible/ansible#27397]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
requirements.txt should have pinned versions so that installing a specific version in a new virtualenv does not create any sideeffects. 

##### ANSIBLE VERSION

```
*
```

##### CONFIGURATION

requirements.txt

##### OS / ENVIRONMENT

N/A

##### SUMMARY

As we are not pinning the dependency versions, newer releases of dependencies are being installed even when installing a specific version of Ansible. A released version of Ansible should bring fixed dependencies so that we get reproducible virtual environments.  Problem with these newer dependencies are 
1. May be or may not be compatible with Ansible
2. May or may not have bugs (recently a dependency named cryptography was released which has errors causing segmentation faults even though we were installing a specific version of Ansible)

A simple line in your release process to say "pip freeze | grep -v ansible > requirements.txt" would fix the problem

##### STEPS TO REPRODUCE

Install any older version of ansible and observe that it is installing the latest version of the dependencies. 

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by nitzmahone** [comment]
Sorry, this probably isn't going to happen. We'd have to pin the transitive closure of the entire tree of package dependencies to make this work, and install them in an exact order. Even that would fail for "smarter" items that use dynamic dependency calculation in setup.py... If you want to freeze and restore a specific set of deps, you're welcome to do so just as you've described, but Ansible only version-pins deps on a temporary basis to deal with specific failures on upstreams (and we try to get them resolved ASAP so we can un-pin).
