### ISSUE TITLE
patterns with more than 7 groups do not match any host

### ISSUE THREAD

**Issue by socro** [ansible/ansible#27411]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Patterns (host selection)

##### ANSIBLE VERSION
```
"ansible 2.3.0.0
  config file = /data/ansible/ansible.cfg
  configured module search path = [u'/TVM/Python/bin/ansible', u'/data/ansible/modules']
  python version = 2.7.13 (default, Apr 24 2017, 09:46:22) [GCC 4.3.4 [gcc-4_3-branch revision 152973]]"

"ansible 2.4.0 (devel a49c419651) last updated 2017/07/28 08:06:43 (GMT +200)
  config file = None
  configured module search path = ['/home/socro/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/socro/run/ansible/lib/ansible
  executable location = bin/ansible
  python version = 3.6.2 (default, Jul 20 2017, 03:52:27) [GCC 7.1.1 20170630]"
```
##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When using a pattern with more than 7 groups linked by ':' no hosts are matched even though there are hosts that should be matched by that pattern

##### STEPS TO REPRODUCE
inventory:
[001]
host-a
[002]
host-b
[003]
host-c
[004]
host-d
[005]
host-e
[006]
host-f
[007]
host-g
[008]
host-h
[009]
host-i

does not work:
**ansible -i hosts '001:002:003:004:005:006:007:008' -m ping  --list-hosts**

works:
ansible -i hosts '001:002:003:004:005:006:007' -m ping  --list-hosts

##### EXPECTED RESULTS
all hosts should be listed/matched:
  hosts (8):
    host-a
    host-b
    host-c
    host-d
    host-e
    host-f
    host-g
    host-h

##### ACTUAL RESULTS
```
 [WARNING]: Could not match supplied host pattern, ignoring: 001:002:003:004:005:006:007:008
 [WARNING]: No hosts matched, nothing to do
```

**Comment by bcoca** [comment]
seems like it is confusing your list with an IPv6 address

workaround, use `,` as a separator

**Comment by socro** [comment]
Of course! Did not thought of that. Thanks @bcoca for the workaround, works for me.
