### ISSUE TITLE
solaris md5 problem

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#2742]
after a git pull today, I am no more able to work with ansible against solaris targets. anybody has an idea?

I get the following error:

ansible 'solaris' -m copy -a 'src=/home/.../.solaris10-sparc dest=/export/home/.../.solaris10-sparc'

md5sum command failed unusually, please report this to the list so it can be fixed

output: {'stdout': '', 'stderr': '/bin/sh: test: Argument erwartet\n', 'rc': 1}

**Comment by mpdehaan** [comment]
fixed per above merge, thanks!
