### ISSUE TITLE
possible bug with templating of new style variables ("{{ var }}")

### ISSUE THREAD

**Issue by b6d** [ansible/ansible#2743]
This is the verson of Ansible I'm referring to:

```
$ ansible --version
ansible 1.2 (devel 3e0c33c1fa) last updated 2013/04/22 00:04:37 (GMT +200)
```

I'm trying to use complex args as described in `examples/playbooks/complex_args.yml`. Specifying these using `$var`-syntax works for me, but using `{{ var }}`-like syntax leads to the following trace:

```
  File "/home/bernhard/dvl/ansible/lib/ansible/runner/__init__.py", line 322, in _executor
exec_rc = self._executor_internal(host)
  File "/home/bernhard/dvl/ansible/lib/ansible/runner/__init__.py", line 387, in _executor_internal
return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=self.complex_args)
  File "/home/bernhard/dvl/ansible/lib/ansible/runner/__init__.py", line 533, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/home/bernhard/dvl/ansible/lib/ansible/runner/action_plugins/debug.py", line 38, in run
    args.update(complex_args)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

This is a basic playbook that might help to reproduce the error: 

```

---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  vars:
    - my_args:
        msg: mymsg
  tasks:
    - name: "this works"
      action: debug
      args: $my_args
    - name: "this doesn't"
      action: debug
      args: '{{ my_args }}'
```

I tried to isolate the cause of this and ended up in `ansible.utils.template.template(...)`, which is invoked for both tasks (`complex_args = template.template(self.basedir, complex_args, inject)`) and leads to different results for each (a dict in the first case and a unicode string in the second).

**Comment by mpdehaan** [comment]
What we need to do here is what we did with "with_items" and that args should just allow a variable name, like so:

args: my_args

The same is also true of the environment keyword, and with_nested too, which I think currently don't work that way.

Thanks for the heads up!

**Comment by mpdehaan** [comment]
Fixed up in latest devel, thanks

you can also now do:

args: some_hash

where some_hash is a variable, without all the need for the quoting and bracketing, but both now work

thanks!
