### ISSUE TITLE
Wrong recursive loop detection in new 1.2-style variables

### ISSUE THREAD

**Issue by gw0** [ansible/ansible#2744]
I noticed that the new 1.2-style variables do not behave exactly the same as the old ones and report an recursive loop detection where it does not exist.

Originally I had a complex case where I spotted the bug. I was setting variables in hosts inventory and than adding it to a dict structure in group_vars from where it was used in other variables... In that case the playbook started, but crashed with:

```
fatal: [xxx] => recursive loop detected in template string: {{foo_bar}}
```

After isolating the problem it started to behave differently (but I think it is the same reason) and the playbook doesn't even to start and is complaining about:

```
ERROR: recursive loop detected in template string: {{foo.bar}}
```

This works with pre-1.2 style variables:

```
- hosts: all
  vars:
    foo_bar: 123
    foo:
      bar: ${foo_bar}
      xxx: ${foo.bar}
  tasks:
    - debug: msg="{{ foo_bar }} {{ foo.bar }}"
```

The same with new 1.2 style variables doesn't even start if `xxx` is present:

```
- hosts: all
  vars:
    foo_bar: 123
    foo:
      bar: "{{ foo_bar }}"
      xxx: "{{ foo.bar }}"
  tasks:
    - debug: msg="{{ foo_bar }} {{ foo.bar }}"
```

It seems that `foo.bar` and `foo_bar` are treated as the same thing or that there is a depth limit for resolving variables set very low.

**Comment by mpdehaan** [comment]
Referencing something inside of the datastructure shouldn't be allowed, really.   That it worked before I think we can say was nice, but you can think of it as saying that foo wasn't defined yet, so referencing a property of foo inside foo wouldn't make sense.

It is not true that foo.bar and foo_bar are the same, it's just the internal reference in xxx that is the problem.
