### ISSUE TITLE
role can not run multiple time using ansible-playbook

### ISSUE THREAD

**Issue by futangw** [ansible/ansible#27466]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

use default
##### OS / ENVIRONMENT

Linux stackclient 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY

A same role can not run multiple times, for example, below code the role1 only run once:
- role: role1
- role: role2
- role: role1

a workaround could be:
- role: role1
- role: role2
- role: role1
  when: true

but below code role1 will run 3 times:
- role: role1
- role: role1
- role: role1

##### STEPS TO REPRODUCE

write roles as below and run it with playbook:
- role: role1
- role: role2
- role: role1
- role: role2
- role: role1
- role: role2

```yaml

```

##### EXPECTED RESULTS

each role1 and role2 run 3 ttime
##### ACTUAL RESULTS

```
each one only run 1 time. Note: each role is independent.
```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case I would urge you to read up on the `allow_duplicates` setting for roles.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
