### ISSUE TITLE
Is there an ansible module for lun mapping for na_cdot

### ISSUE THREAD

**Issue by Amruthapv** [ansible/ansible#27473]
##issue type
 - Feature Idea
 

##### COMPONENT NAME
na_cdot_lun_mapping

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

```

##### OS / ENVIRONMENT
ubuntu 14.04

##### SUMMARY
Wanted to know if the above module already exists.Iam not talking about netapp_e_lun_mapping.
If not what documentation can I refer to write such modules.

**Comment by Amruthapv** [comment]
After doing ansible -doc --list I could not locate the module.

**Comment by Akasurde** [comment]
@Amruthapv I am not sure about the na_cdot_lun_mapping module, but there is something more closer to [that](http://docs.ansible.com/ansible/latest/na_cdot_lun_module.html). If you want to develop a new module, you can refer this [page](http://docs.ansible.com/ansible/latest/dev_guide/developing_modules.html)

**Comment by Amruthapv** [comment]
okay thank you @Akasurde

**Comment by alikins** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

 This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.
