### ISSUE TITLE
Errors after install

### ISSUE THREAD

**Issue by SeanBannister** [ansible/ansible#275]
I'm new to Python and configuration management so excuse my lack of knowledge, I followed the Getting Started Guide (http://ansible.github.com/gettingstarted.html) but I'm receiving errors when I run Ansible:

```
root@log1:/usr/local/ansible/bin> ./ansible all -m ping
192.168.0.12 | FAILED => Traceback (most recent call last):
  File "/usr/local/ansible/lib/ansible/runner.py", line 535, in _executor
    (host, ok, data, err) = self._executor_internal(host)
  File "/usr/local/ansible/lib/ansible/runner.py", line 574, in _executor_internal
    result = self._execute_normal_module(conn, host, tmp, module_name)
  File "/usr/local/ansible/lib/ansible/runner.py", line 347, in _execute_normal_module
    module = self._transfer_module(conn, tmp, module_name)
  File "/usr/local/ansible/lib/ansible/runner.py", line 198, in _transfer_module
    outpath = self._copy_module(conn, tmp, module)
  File "/usr/local/ansible/lib/ansible/runner.py", line 644, in _copy_module
    conn.put_file(in_path, out_path)
  File "/usr/local/ansible/lib/ansible/connection.py", line 161, in put_file
    sftp = self.ssh.open_sftp()
  File "/usr/lib/pymodules/python2.6/paramiko/client.py", line 390, in open_sftp
    return self._transport.open_sftp_client()
  File "/usr/lib/pymodules/python2.6/paramiko/transport.py", line 827, in open_sftp_client
    return SFTPClient.from_transport(self)
  File "/usr/lib/pymodules/python2.6/paramiko/sftp_client.py", line 106, in from_transport
    return cls(chan)
  File "/usr/lib/pymodules/python2.6/paramiko/sftp_client.py", line 87, in __init__
    server_version = self._send_version()
  File "/usr/lib/pymodules/python2.6/paramiko/sftp.py", line 108, in _send_version
    t, data = self._read_packet()
  File "/usr/lib/pymodules/python2.6/paramiko/sftp.py", line 179, in _read_packet
    raise SFTPError('Garbage packet received')
SFTPError: Garbage packet received
```

One thing that could be improved in the guide is mentioning how to install Python packages for newbs, I ended up using easy_install however it couldn't find python-jinja2 and instead I found a package at jinja2.

Could this be related to my problem?

**Comment by jkleint** [comment]
You're right, that could be clearer in the docs.  python-jinja2 would be the RPM (or Debian) package name you'd install with yum (or apt-get) to install it system-wide, whereas it's just jinja2 when using easy_install (or pip) to install to a specific python.  If you're using the system python, you probably want the former.

Your error doesn't look related, however; that looks like an SSH issue.  As a first step, can you just use normal command-line sftp to connect to all of the machines in your inventory?  Just try copying some file to your machines and see what you get.  For each machine, do `sftp machine` then `put /usr/share/dict/words` (or any file).  `quit` will get you back to the command line.  Also, this should work without a password; if not, either look into setting up your ssh-agent (http://www.debian-administration.org/articles/152) or look at ansible's --ask-pass or --sudo options.

It would also help to know if you're using public key authentication, an ssh agent, if your private key requires a password, what operating system, and what version of ansible.  (You might also try the devel branch.)

**Comment by SeanBannister** [comment]
When I tried sftp it returned `Received message too long [some numbers, keeping private]`. It turns out its because I'm logged in as root and the remote machine won't allow me to login as root but if I specify `sftp ubuntu@example.com` it works fine. That lead me to trying `ansible all -m ping -u ubuntu` which unfortunately returned:

```
Traceback (most recent call last):
  File "./ansible", line 26, in <module>
    import ansible.runner
ImportError: No module named ansible.runner
```

I presume this has something to do with python not knowing about runner.py or runner.pyc in the lib directory?

**Comment by mpdehaan** [comment]
You have an error, but you did not specify anything about what platform you were using.   Anyway, this is mostly a support question, not a bug in Ansible... I would recommend IRC or the mailing list.   What OS on hosts and clients?

It seems that most likely you don't have sftp enabled in your SSH config.

**Comment by SeanBannister** [comment]
Sorry should of been more specific I'm running Ubuntu 10.10, Python 2.6.6 on the host. The client is running Ubuntu 12.04, Python 2.7.3.

I've successfully logged into the client from the host with sftp and uploaded a file. I've also used SSH between the two.

**Comment by mpdehaan** [comment]
sounds like you need to do a make install to me.

If you just want to run from checkout, run ./hacking/env-setup

**Comment by SeanBannister** [comment]
_face palm_ As I read the documentation I skipped the `make install` as I saw the first few commands I'd already run in the section above. My mistake should of thought it threw.

Thanks for your help.

**Comment by jringoot** [comment]
Maybe this can help someone:
The server from where I run ansible is a Centos  6.4 x86_64
I had a similar issue with a git checkout in the directory of the user that I wanted to run ansible.
But it worked for  root. with a git checkout in /opt.
I tried "source ./hacking/env-setup" from /opt/ansible as the user + "export ANSIBLE_HOSTS=/etc/ansible/hosts"
And ansible worked for that user.

And to make it permanent for that user, for any new shell, I added the following lines to its ".bashrc":

export PATH=/opt/ansible/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:
export PYTHONPATH=/opt/ansible/lib:
export ANSIBLE_LIBRARY=/opt/ansible/library
export MANPATH=/opt/ansible/docs/man:
export ANSIBLE_HOSTS=/etc/ansible/hosts
