### ISSUE TITLE
ec2.py module shabang

### ISSUE THREAD

**Issue by devdave** [ansible/ansible#2750]
https://github.com/ansible/ansible/commit/9dda148679c32299bc7cbed2c19874a3e3e1db72#commitcomment-3064604

ec2.py requires boto to be installed to the system's python library and not to a virtualenv which is why the last iteration had #!/usr/bin/env python versus current explicit one.  I am using ec2.py via a local_action and it fails without editing the shabang.

**Comment by mpdehaan** [comment]
So modules aren't meant to run within a virutalenv.  Never were.

If you want to change the interpreter line, you set ansible_python_interpreter via a variable to what you need it to be.

The previous usage of /usr/bin/env breaks the ansible_python_interpreter sytem of replacing the shebang on a per host basis.

If you have further questions please stop by the list.
