### ISSUE TITLE
Don't scare users away from using roles that are Container Enabled

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#27537]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

Ansible Galaxy / role installation

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When users install my `geerlingguy.solr` role, which is 'container enabled' but is also made to work 100% correctly either when used with Ansible Container or when used with traditional infrastructure... they get a big scary magenta warning in their console:

```
[WARNING]: geerlingguy.solr is a Container Enabled role and should only be installed using Ansible Container
```

##### STEPS TO REPRODUCE

```
ansible-galaxy install geerlingguy.solr
```

Or use a `requirements.txt` file and add `geerlingguy.solr` to it, then run:

```
ansible-galaxy install -r requirements.txt
```

##### EXPECTED RESULTS

Users would have the `geerlingguy.solr` role installed. And they wouldn't be scared from using the role because of big pink WARNINGs.

##### ACTUAL RESULTS

Users are scared of my role, because they see

```
[WARNING]: geerlingguy.solr is a Container Enabled role and should only be installed using Ansible Container
```

**Comment by geerlingguy** [comment]
Are roles meant to be 100% exclusive to either being used in traditional infra builds, or container builds only? For my solr role, there were literally like two little changes required to make it work in _both_ places.

Maybe we could only pop that warning if the role adds some other flag like "only_run_in_containers_wont_work_with_normal_infrastructure" or something like that? I'm not going to put in the effort to convert my other roles to be container-compatible if it means the thousands of existing users are going to start seeing these warnings on install, in CI environments, etc...

**Comment by chouseknecht** [comment]
@geerlingguy 

Based on your feedback, seems like removing the warning is a good idea. I'll work on ejecting it today.

Thanks!

**Comment by chouseknecht** [comment]
Scary message removed via #27578
