### ISSUE TITLE
ansible_python_interpreter not effective

### ISSUE THREAD

**Issue by frawau** [ansible/ansible#27538]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible variables

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 1517db06c5) last updated 2017/08/01 09:27:33 (GMT +700)
  config file = None
  configured module search path = ['/home/fw/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fw/Sysadm/Ansible/ansible/lib/ansible
  executable location = /home/fw/Sysadm/Ansible/ansible/bin/ansible
  python version = 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

Setting ansible_python_interpreter on the command line or in the ansible_host file does not work
##### STEPS TO REPRODUCE

ansible -e "ansible_python_interpreter='/usr/bin/python3'" --version

```yaml

```

##### EXPECTED RESULTS

The python version to be 3.5 in both cases
##### ACTUAL RESULTS

When trying to set ansible_python_interpreter, python 2.7 is used

```
ansible -e "ansible_python_interpreter='/usr/bin/python3'" --version
ansible 2.4.0 (devel 1517db06c5) last updated 2017/08/01 09:27:33 (GMT +700)
  config file = None
  configured module search path = [u'/home/fw/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fw/Sysadm/Ansible/ansible/lib/ansible
  executable location = /home/fw/Sysadm/Ansible/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

/usr/bin/python3 /home/fw/Sysadm/Ansible/ansible/bin/ansible --version
ansible 2.4.0 (devel 1517db06c5) last updated 2017/08/01 09:27:33 (GMT +700)
  config file = None
  configured module search path = ['/home/fw/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fw/Sysadm/Ansible/ansible/lib/ansible
  executable location = /home/fw/Sysadm/Ansible/ansible/bin/ansible
  python version = 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]

```

**Comment by andreaso** [comment]
What you are seeing is the expected/documented behavior.

https://docs.ansible.com/ansible/latest/python_3_support.html

**Comment by frawau** [comment]
Well... when I use -e "ansible_python_interpreter='/usr/bin/python3'"  I expect 

 python version = 3.5.3

but I get 

 python version = 2.7.13

So how is that the expected behaviour? The page you mention (and I did check it before hand) states
<code>
       Set the ansible_python_interpreter configuration option to /usr/bin/python3.
       ......
       Note that you can also use the -e command line option to manually set the python interpreter 
</code>
So please do enlighten me on how that is the expected behaviour.

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The `ansible_python_interpreter` affects the module execution on targets, NOT the execution of Ansible itself on the controller, that is controlled by the shebang in the `ansible` executable.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by frawau** [comment]
Thank you.  Clear now.
