### ISSUE TITLE
module for Windows quality of service policy generation

### ISSUE THREAD

**Issue by sebLopezCot** [ansible/ansible#27564]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

win_quality_of_service_policy

##### ANSIBLE VERSION

```

```

##### SUMMARY

Would like the ability to create and ensure the existance of quality of service policies set in Windows. Powershell supports creation and listing of policies. https://technet.microsoft.com/itpro/powershell/windows/netqos/netqos
##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by jborean93** [comment]
needs_contributor

**Comment by jborean93** [comment]
Closing as I am trying to cull older new module requests. If someone is interested in implementing this then I would recommend they create an Ansible collection and distribute the module that way.
