### ISSUE TITLE
Relicense module_utils/api.py to BSd

### ISSUE THREAD

**Issue by abadger** [ansible/ansible#27599]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
lib/ansible/module_utils/api.py

##### ANSIBLE VERSION

```
devel, 2.3
```

##### SUMMARY
We want to have module_utils be BSD code but api.py has a GPLv3+ header.  If at all possible we wnat code (especially generically useful code) like this to be relicensed.

**Comment by abadger** [comment]
Need signoff from:

* Author: Toshio Kuratomi @abadger
* Author: Dag Wieers @dagwieers 
* Author: Jonathan Davila @defionscode 
* Author: Brian Coca @bcoca

**Comment by dagwieers** [comment]
@abadger I'd like to know why in this case we want this code to be BSD licensed ? Earlier I was told everything had to be GPLv3+ ?

**Comment by bcoca** [comment]
@dagwieers true for most of the project, but module_utils was always supposed to be an exception and allow for shared code to be BSD so 3rd parties could ship modules using this code w/o dealing with licensing issues.

**Comment by bcoca** [comment]
Consider this my consent to re-license

**Comment by juliedavila** [comment]
I consent

**Comment by abadger** [comment]
This is code in module_utils.  Since module_utils is being used by both our, and third party modules (where the third party modules may be commercial, for instance), we want that code to be BSd licensed.

There is some info here:

https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/dev_guide/developing_modules_in_groups.rst#before-you-start-coding

I believe that information was in the long coding guideline checklist before it migrated to the developing modules in groups page.

**Comment by abadger** [comment]
I give permission for all my contributions to lib/ansible/module_utils/api.py to be relicensed under the BSD license.  An example of the BSD license I mean is here: https://github.com/ansible/ansible/blob/97a34cf008501088ae012f24e4712e2bc6dd6d4c/lib/ansible/module_utils/basic.py#L11

**Comment by dagwieers** [comment]
I give permission for all my contributions to lib/ansible/module_utils/api.py to be relicensed under the BSD license.

**Comment by abadger** [comment]
Thanks @bcoca @dagwieers @defionscode.  License header updated
