### ISSUE TITLE
(CentOS 6.2, steps to repro?) Crypto error: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'

### ISSUE THREAD

**Issue by denen99** [ansible/ansible#276]
hello,

 I installed all the pre-reqs but when trying to run the sample setup i am getting the following error:

[root@dev-m01 ansible]# python -V
Python 2.6.6
[root@dev-m01 ansible]# cat /etc/redhat-release 
CentOS release 6.2 (Final)
[root@dev-m01 ansible]# 
# ansible all -m ping --ask-pass

Traceback (most recent call last):
  File "/usr/local/src/ansible/bin/ansible", line 27, in <module>
    import ansible.runner
  File "/usr/local/src/ansible/lib/ansible/runner.py", line 34, in <module>
    import ansible.connection
  File "/usr/local/src/ansible/lib/ansible/connection.py", line 26, in <module>
    import paramiko
  File "/usr/lib/python2.6/site-packages/paramiko/**init**.py", line 69, in <module>
    from transport import randpool, SecurityOptions, Transport
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 32, in <module>
    from paramiko import util
  File "/usr/lib/python2.6/site-packages/paramiko/util.py", line 32, in <module>
    from paramiko.common import *
  File "/usr/lib/python2.6/site-packages/paramiko/common.py", line 98, in <module>
    from rng import StrongLockingRandomPool
  File "/usr/lib/python2.6/site-packages/paramiko/rng.py", line 22, in <module>
    from Crypto.Util.randpool import RandomPool as _RandomPool
  File "/usr/lib64/python2.6/site-packages/Crypto/Util/randpool.py", line 30, in <module>
    import Crypto.Random
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/__init__.py", line 29, in <module>
    from Crypto.Random import _UserFriendlyRNG
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 38, in <module>
    from Crypto.Random.Fortuna import FortunaAccumulator
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 39, in <module>
    import FortunaGenerator
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py", line 34, in <module>
    from Crypto.Util.number import ceil_shift, exact_log2, exact_div
  File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 56, in <module>
    if _fastmath is not None and not _fastmath.HAVE_DECL_MPZ_POWM_SEC:
AttributeError: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'

**Comment by mpdehaan** [comment]
Is this CentOS 6.2 + EPEL or did you get these libraries from somewhere else?

This does not happen for me and I develop on exactly the same OS.

**Comment by denen99** [comment]
i did notice EPEL repos.d files in /etc/yum.repos.d does this cause an issue ?

**Comment by mpdehaan** [comment]
I use EPEL and haven't had any problems.  Can you bring this up on the mailing list?

**Comment by mpdehaan** [comment]
nobody on list seems to be able to replicate this, can't repro...

I'll make sure my libraries are up to date just in case this is a recent thing.  Any other info would be helpful.

**Comment by mpdehaan** [comment]
closing

**Comment by denen99** [comment]
~~FWIW i commented out line 56 of /usr/lib64/python2.6/site-packages/Crypto/Util/number.py~~~

```
# You need libgmp v5 or later to get mpz_powm_sec.  Warn if it's not available.
#if _fastmath is not None and not _fastmath.HAVE_DECL_MPZ_POWM_SEC:
#    _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)
```

~~and it worked...~~

THIS IS NOT A FIX, IT LEAVES YOUR SYSTEM VULNERABLE

**Comment by Katafalkas** [comment]
hi,

I had the same problem. denen99's solution worked like a charm. Thank you !

**Comment by gsps1** [comment]
thanks. it worked. i was facing this issue with running python fabric.

**Comment by rmarscher** [comment]
The solution from @denen99 worked for me on CentOS 6.4.  Thanks!

**Comment by sochoa** [comment]
Yep, me-four!  Commenting out that line worked!  :)

**Comment by mpdehaan** [comment]
Strange, I still do _NOT_ see this issue on CentOS 6.4

Is there a chance paramiko is coming from another repo?

**Comment by cbrinker** [comment]
Just had the same issue, solution worked just fine. I believe I had achieved this via "yum install ansible", and then used pip to upgrade ansible to the 1.2.2 version (which forced me to download a compiler to build and install pycrypto)

**Comment by bkdinoop** [comment]
The solution from @denen99 worked for me on CentOS 6.3 in Azure VM. Thanks!

**Comment by mgarabed** [comment]
This problem cropped up on a Scientific Linux 6.1 install as well.  The root cause seems to be a pip upgrade of pycrypto over an existing RPM-installed version.  For some reason, all of the files are not removed as part of the process, so a lingering .so file (_fastmath.so) stays around and isn't compatible with the new version.

Trying to manually update/compile this was fruitless too:  the latest pycrypto requires a version of libgmp that isn't in the main repo's (version >= 5).  

Ultimately these steps solved the problem cleanly:

```
$ sudo pip uninstall python-keyczar pycrypto pyasn1
$ sudo yum erase python-keyczar python-crypto pyasn1
$ sudo yum install python-keyczar <plus any packages that were removed in step 2>
```

**Comment by bcoca** [comment]
Mixing diff package managers is fun!

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by lsiu** [comment]
@denen99 solution also worked for me on Centos 6.5 build from minimal.

**Comment by darKoram** [comment]
i am seeing this using the centos vm using the image at http://catn.com/labs/project/centos-images/
We then do a  yum clean all, yum upgrade, yum update.
Note, we do the yum clean because the image seems to have stale/broken yum state/repos.

Ansible is not functional until i apply denen99's fix
      sed -e '/mpz_powm_sec/I s/^/# /' < /usr/lib64/python2.6/site-packages/Crypto/Util/number.py > /usr/lib64/python2.6/site-packages/Crypto/Util/number.py.new
      mv -f /usr/lib64/python2.6/site-packages/Crypto/Util/number.py.new /usr/lib64/python2.6/site-packages/Crypto/Util/number.py

**Comment by goozbach** [comment]
As another datapoint, I'm seeing this on a CentOS 6.3 box never installed anything via pip.

I'm upgrading to 6.5 now to see if it persists.

**Comment by jctanner** [comment]
@goozbach if so, can you open a new bug please?

**Comment by goozbach** [comment]
@jctanner butofcourse

**Comment by bamford** [comment]
The solution by @mgarabed worked for me on Scientific Linux 6.3.  Thanks!

**Comment by telsasoft** [comment]
For me, the issue was that I had python-crypto package installed via yum, and then had later installed pycrypto module via pip.  "yum remove python-crypto" worked for me.

**Comment by mjmaisey** [comment]
+1 on the solution that @telsasoft suggested (RHEL 6.5)

**Comment by nov314k** [comment]
@denen99 Worked brilliantly, thank you so much!

**Comment by ecs-hk** [comment]
Problem confirmed on Scientific Linux 6.5.

My approach was similar to @mgarabed 's:

```
# pip uninstall pycrypto
# yum erase python-crypto
# yum install python-crypto python-paramiko
```

(Second command removed paramiko.)

I'd imagine this dance will be required again if/when pip updates pycrypto.

**Comment by jhawkesworth** [comment]
+1 for denen99 fix.  Once I'd seen further discussion I then also applied ecs-hk's solution so +1 for that too.

**Comment by kidlj** [comment]
+2 on the solution that @telsasoft suggested (RHEL 6.5)

**Comment by liul85** [comment]
+3 on the solution that @telsasoft suggested (RHEL 6.5)

**Comment by bcoca** [comment]
so denen99's solution is not a fix, it leaves you with an insecure system, it just bypasses raising the error. The proper fix should be updating to the latest versions of the packages, we worked with the distros and EPEL to make sure they included the secure version and should not emit the warning anymore.

**Comment by agasthik** [comment]
@ecs-hk  's solution worked for me

I am using Oracle Enterprise Linux 6.5

**Comment by superleo** [comment]
@mgarabed 's solution worked for me 
I am using RHEL Workstation 6.7 x64

**Comment by syntaxerrormmm** [comment]
+1 to @telsasoft solution. Needed ansible at least v2 on CentOS 6.7, EPEL has only 1.9.4.

**Comment by kt-ssp** [comment]
Just had a similar issue with ReviewBoard on CentOS 6.7 after an installation of another python app. The comment made by @mgarabed above about _"pip upgrade of pycrypto over an existing RPM-installed version"_ prompted me to `yum reinstall python-crypto` (which in my case was to _2.0.1-22.el6_) and ReviewBoard started to work again.

**Comment by toshiueno** [comment]
@kt-ssp @denen99 Installing gmp-devel and reinstalling python-crypto worked for me! tks!

**Comment by juju4** [comment]
It seems this error appears constantly with ansible v2.2 and centos6. at least in all my kitchen test (1.13.2) with ansible and lxd_cli.

changing ansible_version in provisioner of .kitchen.yml is a valid workaround

```
platforms:
  - name: centos-6
    provisioner:
      ansible_version: 2.1.2.0
```

**Comment by kishore-vkrn** [comment]
Uninstalling pycrypto gave me issues, simply installed specific version of PyCrypto
`pip install PyCrypto==2.3`

refer: [Stackoverflow](https://stackoverflow.com/questions/22941029/python-fabric-error-module-object-has-no-attribute-have-decl-mpz-powm-sec)
