### ISSUE TITLE
New variable convention with group_by causes error

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#2761]
I'm using an inventory variable with group_by and it's causing some interesting behavior:

task:

```
- name: Create a group based on riak node type.
    group_by: key={{ node_type }}
```

output:

```
TASK: [Create a group based on riak node type.] ******************************* 
DEBUG: data = {{
DEBUG: data = {{
changed: [10.42.0.7] => {"changed": true, "groups": {"{{": ["10.42.0.7", "10.42.0.8"]}}
```

If I reference it as {{node_type}} or ${node_type}, things work fine.

This is with an updated devel branch (as of 10 minutes ago).

**Comment by mpdehaan** [comment]
Looks like we need to call smush_braces more generically before running action plugins.

Thanks for the heads up, will get this fixed.

**Comment by mpdehaan** [comment]
Fix pushed for this yesterday, you should be good to go.  Thanks!
