### ISSUE TITLE
Not able to include the path variable in extra vars gives error

### ISSUE THREAD

**Issue by Amruthapv** [ansible/ansible#27658]
##### ISSUE TYPE

 - Bug Report
 

##### COMPONENT NAME
own module for lun_mapping

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/my_modules/']
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

```

##### OS / ENVIRONMENT
ubuntu 14.04

##### SUMMARY
My module contains a variable called path " /vol/volumename/lunname" but inside the playbook when i try to explicitly provide the path using extra vars it says module fail error.

##### STEPS TO REPRODUCE
have a look at lun_create in na_cdot_lun module

**Comment by Akasurde** [comment]
@Amruthapv Could you please elaborate more about the issue by providing - Playbook example, Expected Behaviour, Current Behaviour, Steps to reproduce, Name of module ?

This will help us to pin point the issue. Thanks for reporting this bug.

**Comment by Amruthapv** [comment]
@Akasurde well i solved the bug by making changes to path variable in the module itself. Thanks

**Comment by Akasurde** [comment]
@Amruthapv Cool. Could you please close this issue then ? Please join #ansible IRC channel on freenode.net, so that you can get quick fixes and better answers. It also avoids to-and-fro in bug reports.

**Comment by Amruthapv** [comment]
@Akasurde  sure thanks!
