### ISSUE TITLE
ansible-test completions fail under python3

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible#27656]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ansible-test

##### ANSIBLE VERSION
2.4.0

##### CONFIGURATION
NA

##### OS / ENVIRONMENT
Python3.5.3 under a virtualenv (any supported py3 should exhibit)

##### SUMMARY
Many of the dynamic target completions fail due to string/bytes mismatches, usually with the error `endswith\ first\ arg\ must\ be\ bytes\ or\ a\ tuple\ of\ bytes,\ not\ str `. I tried a few small code changes that kinda moved the problem around, but looks like ultimately we need to make sure that all the completions are uniformly text or bytes.

##### STEPS TO REPRODUCE
Under a py3 venv (where `python` points at a py3 interpreter), do:
`ansible-test windows-integration <tab>`

##### EXPECTED RESULTS
list of windows integration targets

##### ACTUAL RESULTS
Error text appended to commandline:

```
ansible-test windows-integration endswith\ first\ arg\ must\ be\ bytes\ or\ a\ tuple\ of\ bytes,\ not\ str endswith\ first\ arg\ must\ be\ bytes\ or\ a\ tuple\ of\ bytes,\ not\ str 
```

**Comment by mattclay** [comment]
Resolved with #28248.
