### ISSUE TITLE
Unable to get a role with ansible-galaxy from private Github HTTPS url via requirements.yml (but works in CLI)

### ISSUE THREAD

**Issue by mechastorm** [ansible/ansible#27677]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-galaxy

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]

```

##### CONFIGURATION

all defaults

##### OS / ENVIRONMENT

macOS Sierra Version 10.12.6

##### SUMMARY
I cannot get a role from a private github installation via HTTPs via the requirement.yml method. But it works fine direclty via the command line

##### STEPS TO REPRODUCE

This works

```
ansible-galaxy install git+https://private-github-urlt/my-org/my-role --roles-path=roles-remote
```

This breaks 

```
# requirements.yml
- src: git+https://private-github-urlt/my-org/my-role
```

run the command

``
$  ansible-galaxy install --force -r requirements.txt --roles-path=roles-remote
``

##### EXPECTED RESULTS

I should be able to download a role from a private github installation via requirements.yml

##### ACTUAL RESULTS
```
[DEPRECATION WARNING]: going forward only the yaml format will be supported.
This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
- downloading role from - src: https://private-github-urlt/my-org/my-role
 [ERROR]: failed to download the file: <urlopen error unknown url type: - src>

 [WARNING]: - system-update was NOT installed successfully.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by nitzmahone** [comment]
Does it work with just a straight https:// (not git+https://) URL?

**Comment by mechastorm** [comment]
It is still the same with straight https

When I set my requirements.yml to be

```
- src: https://private-github-urlt/my-org/my-role
```

I still get the same error when I ran the command
```
$  ansible-galaxy install --force -r requirements.txt --roles-path=roles-remote
[DEPRECATION WARNING]: going forward only the yaml format will be supported.
This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
- downloading role from - src: https://private-github-urlt/my-org/my-role
 [ERROR]: failed to download the file: <urlopen error unknown url type: - src>

 [WARNING]: - system-update was NOT installed successfully.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by mechastorm** [comment]
This seems to be fixed now 

doing this config seems work fine in Ansible 2.3
```
- src: git+https://my-private-github-enterprise/org/repo.git
  version: master
```

**Comment by mihai-satmarean** [comment]
Hello,
not working for me with the following info. 
 
> ansible --version
> ansible 2.7.4
>   config file = None
>   configured module search path = ['/home/gitlab-runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
>   ansible python module location = /home/gitlab-runner/builds/9ab00147/0/ds-roles/ds-profile-core/virtenv36b/lib/python3.6/site-packages/ansible
>   executable location = /home/gitlab-runner/builds/9ab00147/0/ds-roles/ds-profile-core/virtenv36b/bin/ansible
>   python version = 3.6.6 (default, Aug 13 2018, 18:24:23) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
> $ molecule --version
> molecule, version 2.19.0

seems related to this https://github.com/ansible/ansible/issues/45475

sorry for the messy post, I'm in a hurry :)

Very good product though!

**Comment by cavamagie** [comment]
same for me

- src: git+https://gitlab.anacard.com/Ansible-Galaxy/Common.git

not working

EDIT: if using http credential work

**Comment by mihai-satmarean** [comment]
seems that it just works with ansible 2.7.7

**Comment by JosueCayola** [comment]
me ocurio este error 
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
es por que usaba mal el path
`ansible-galaxy install --roles-path=roles  geerlingguy.supervisor`
