### ISSUE TITLE
ansible_port is missing from vars

### ISSUE THREAD

**Issue by TheCapsLock** [ansible/ansible#27675]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vars

##### ANSIBLE VERSION
```
ansible 2.4.0 (detached HEAD a328e96455) last updated 2017/08/02 22:41:03 (GMT +200)
  config file = /home/test/Documents/playbooks/ansible.cfg
  configured module search path = [u'/home/test/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/test/Documents/ansible/lib/ansible
  executable location = /home/test/Documents/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

```

##### CONFIGURATION

ansible.cfg : 

```
[defaults]
inventory = ./hosts
pipelining = True
become_ask_pass = True
nocow=1
```

My inventory file do not specify a port to connect to ssh, I let ansible rely on ~/.ssh/config (which also works to connect to hosts listening on non standard port for ssh connections)

##### OS / ENVIRONMENT
OS running Ansible : Ubuntu17.04
target OS : debian stretch

##### SUMMARY
when running

```
ansible -m setup targetmachine
```

*ansible_port* is missing from vars. It also unset when used in templates

##### STEPS TO REPRODUCE
Just run :

```
ansible -m setup targetmachine
```
then in received json you'll see ansible_port is missing

##### EXPECTED RESULTS
ansible_port is available

##### ACTUAL RESULTS
ansible_port is missing

**Comment by nitzmahone** [comment]
The various connection plugins will use a default for ansible_port if it's not specified (if port even makes sense for that connection type), but if you want to ensure a variable value is always available for use in templates and stuff, you'll need to set it yourself- the connection plugins don't have a way to smuggle out the value they used.
