### ISSUE TITLE
YAML syntax error when string contains a colon + space

### ISSUE THREAD

**Issue by gw0** [ansible/ansible#2769]
There is a YAML syntax error if you try to enter a colon followed by a space (`": "`) inside any string (doesn't seem to matter what if before or after).

```
$ cat _test.yml

---
- hosts: all
  tasks:
    - debug: msg="foo: bar"
```

In Ansible 1.2 development branch:

```
$ ansible-playbook -v _test.yml 
ERROR: Syntax Error while loading YAML script, _test.yml
Note: The error may actually appear before this position: line 4, column 22

  tasks:
    - debug: msg="foo: bar"
                     ^
```

A use case where this will cause trouble is when using `lineinfile` module.

**Comment by b6d** [comment]
Hi,

as far as I can tell this is malformed YAML (the first quotes in your example do not start a string, they are part of an implicit string).

you can test this online here: https://yaml-online-parser.appspot.com/

**Comment by mpdehaan** [comment]
You can quote the YAML string, this is not a bug.

**Comment by nafg** [comment]
What is the correct way to write it?

**Comment by gw0** [comment]
I prefer:

```
- debug: "msg='foo: bar'"
```

**Comment by rdw** [comment]
I ran into this problem today, and I wanted to document some of the things that don't work for future searchers.  This is the first thing I tried and didn't work:

```
- lineinfile: dest=/etc/aliases insertafter=EOF line=root: {{ admin_email }}
```

Quoting the pair didn't resolve the YAML syntax error:

```
- lineinfile: dest=/etc/aliases insertafter=EOF "line=root: {{ admin_email }}"
```

Nor did single quotes:

```
- lineinfile: dest=/etc/aliases insertafter=EOF 'line=root: {{ admin_email }}'
```

Nor does quoting the value only:

```
- lineinfile: dest=/etc/aliases insertafter=EOF line="root: {{ admin_email }}"
```

Quoting the entire line passed the YAML syntax check, but failed during execution of the playbook ("this module requires key=value arguments")

```
- lineinfile: "dest=/etc/aliases insertafter=EOF line=root: {{ admin_email }}"
```

In the end, I had to quote both the entire line, and the value:

```
- lineinfile: "dest=/etc/aliases insertafter=EOF line='root: {{ admin_email }}'"
```

Another tactic that worked was to remove the space after the colon.  Might work, depending on the target file:

```
- lineinfile: dest=/etc/aliases insertafter=EOF line="root:{{ admin_email }}"
```

**Comment by DaveQB** [comment]
I have this problem a lot on ansible 1.4.1

No of those solutions are working for me. I have had to work around it each time.

Right now I have this.

```
cron: "state=present name='zpool status' minute='30' job='for i in $(/sbin/zpool list -o name  -H) ; do /sbin/zpool status $i|grep -q 'state: ONLINE' || echo error with zpool $i on $(hostname)|mail me ;done'"
```

The state: ONLINE is what is tripping it up.

I have tried as number of quoting here but nothing gets me past this error.

**Comment by DaveQB** [comment]
Using {{':'}} is the only option that worked for me.
All other quoting just did not pass by ansible's standards. Although it did pass YAML checks.

**Comment by chicks-net** [comment]
What a pain!  The official docs examples do not work.  <sigh>

Thanks for the myriad of suggestions.

**Comment by vladcosorg** [comment]
nothing in official docs about that
thanks!

**Comment by gw0** [comment]
Because having a malformed YAML because of a colon is such a common problem, it would make sense to display a more informative error message describing exactly what is the problem and how it should be fixed (with an example).

**Comment by cemo** [comment]
here is mine:

```
line="hostname:{{ ' ' }}{{ item.droplet.name }}"
```

**Comment by skozin** [comment]
**UPD**: ignore this, it doesn't work.

You can quote just colons:

``` yaml
- debug: msg="foo':' bar"
- lineinfile: "dest=/etc/aliases insertafter=EOF line=root':' {{ admin_email }}"
```

Yes, it's a pain.

**Comment by skozin** [comment]
The help message is not helpful, unfortunately, because it doesn't take into account the space after colon:

``` text
ERROR: Syntax Error while loading YAML script, /path/to/main.yml
Note: The error may actually appear before this position: line 4, column 42

- name: copy some file
  copy: src=file.txt dest='/path/filename: with_space_and_colon.txt'
                                         ^
This one looks easy to fix.  There seems to be an extra unquoted colon in the line
and this is confusing the parser. It was only expecting to find one free
colon. The solution is just add some quotes around the colon, or quote the
entire line after the first colon.

For instance, if the original line was:

    copy: src=file.txt dest=/path/filename:with_colon.txt

It can be written as:

    copy: src=file.txt dest='/path/filename:with_colon.txt'

Or:

    copy: 'src=file.txt dest=/path/filename:with_colon.txt'
```

I got bitten by this trying to launch my very first playbook, which contained something like `debug: msg="TODO: implement this"`, and I can't say that it was a pleasant experience for a newcomer :)

I propose to reopen this issue until the docs and the help message get fixed.

**Comment by n0n3such** [comment]
I ran into this writing my first playbook. Very unpleasant surprise. Does not encourage the use of ansible. In general I find most ansible-playbook error messages less than helpful and more than slightly annoying.

In my case I was able to work around the problem by removing the space following the offending colon character.

**Comment by srgvg** [comment]
http://docs.ansible.com/YAMLSyntax.html#gotchas

**Comment by regner** [comment]
For those coming along later reading this, as I just came across this error today, the best solution I have found so far is to format it like this:

```
    - name: Add deploy user to sudoers.
      lineinfile: >
        dest=/etc/sudoers
        regexp="{{ DEPLOY_USER_NAME }} ALL"
        line="{{ DEPLOY_USER_NAME }} ALL=(ALL) NOPASSWD: ALL"
        state=present
        validate="visudo -cf %s"
```

Using the greater than symbol tells YAML to accept a multiline string, which also seems to help avoid this issue.

**Comment by duckybsd** [comment]
@Regner Thanks you very much, you saved the day!

**Comment by leopepe** [comment]
Had the same problem. I could scape de colons by arraging in a different way the argument parsing to the module:

```
- name: lininfile change
  debug:
    msg: "foo: bar"
```

**Comment by paulmaunders** [comment]
I had been battling with the following string for an hour or so...

`line="Source11: {{nps_src_bundle}}"`

Ansible was complaining that 'We could be wrong, but this one looks like it might be an issue with missing quotes.'

It was fixed by replacing the colon with {{':'}} as @DaveQB had mentioned above

`line="Source11{{':'}} {{nps_src_bundle}}"`

**Comment by paulmaunders** [comment]
The previous solution was giving me some problems with syntax highlighting so I have used another solution which also works, but without the syntax highlighting issues.

`lineinfile: 'dest="~{{build_usr}}/rpmbuild/SPECS/nginx.spec" regexp="^Source11" insertafter="^Source10" line="Source11: {{nps_src_bundle}}"'`

Essentially I have just enclosed everything after lineinfile: inside single quotes.

**Comment by xezpeleta** [comment]
Thanks @DaveQB ! I also solve it with **{{':'}}**

``` yaml
replace: dest=/home/vagrant/parameters.yml.dist regexp='database_user:\smyuser' replace='database_user{{':'}} root'
```

**Comment by dejayc** [comment]
I'm glad this "bug" was closed.  After all, you wouldn't want something that's encountered so often, and under such reasonable circumstances, to be handled sensibly by Ansible's YAML parser.

Please keep this feature deliberately confusing and broken, as it will help ensure my job security.  TIA!

**Comment by yvbeek** [comment]
This, fairly normal use case, results in a syntax error as well:

``` ansible
name: Setup the app database
command: bundle exec rake db:setup
when: db_server == 'localhost' and db_version.stdout == 'Current version: 0'
```

My workaround for now is that I extract just the version number by adding `awk '{print $NF}'` to the db_version shell command. But it is a bit nasty.

**Comment by bcoca** [comment]
@Zyphrax or you could do this:

`when: "db_server == 'localhost' and db_version.stdout == 'Current version: 0'"`

**Comment by haozhang2** [comment]
I have the same problem on Ansible 2.1.0 .

```
when: not "'Number of Peers: 2' in number_of_peers.stdout"
```

**Comment by bitdivine** [comment]
I love the way the error message says "We could be wrong, but" .. and gives no recourse when they ARE wrong.

**Comment by tedder** [comment]
`{{':'}}` is deprecated for a 'when' clause in Ansible2. `':'` isn't sufficient. Not sure how to fix now. I changed my content upstream, but that isn't always possible.

**Comment by j127** [comment]
This should have a better error message. It took me a couple of hours to find a solution.

"You can't have a space after a string unless you use a multi-line quote or quote it..." (or whatever will solve it -- I removed the space).

**Comment by mftovey** [comment]
I am using Ansible version 2.3.1.0.  I got past this with the following syntax:

  - debug:
        msg: "My message with colon: {{somevar}} - this works for me"

**Comment by jbertozzi** [comment]
I had the issue in a filter. I used '\s' as workaround:
debug: msg={{key.stdout | regex_replace('^sshPublicKey:\s(.*)$', '\1') }}
