### ISSUE TITLE
Replacing $item in action using with_items failed with "src and dest are required"

### ISSUE THREAD

**Issue by jkleint** [ansible/ansible#277]
After tracing this one down, I'm pretty sure it ended up being a bug in Python itself, so I'm reporting in case anyone else runs into it.

I have a bunch of config file templates in a directory mirroring the Linux filesystem hierarchy, which I'd like to template out to my nodes.  So I have a playbook with an action like this:

```
- action: template src=$item dest=/$item owner=hdfs group=hadoop mode=0644
  with_items:
  - etc/hadoop/conf/core-site.xml
  - etc/hadoop/conf/hdfs-site.xml
```

The intent is that the files in `./etc/` end up in `/etc/` on the nodes.  However, ansible-playbook gives an error:

```
TASK: [Copy config etc/hadoop/conf/core-site.xml] *********

failed: [node00] => {"failed": true, "msg": "src and dest are required"}
```

Tracing it down, it seems the variable replacement is actually being done fine, and it gives the same error with and without the `/` in `dest=$item`.  Here's where it gets weird:  in `utils.parse_kv()`, the args string is getting parsed just fine, but when it goes into the options dict, it comes out looking like this:

```
{'s\x00r\x00c\x00': '\x00e\x00t\x00c\x00/\x00h\x00a\x00d\x00o\x00o\x00p\x00/\x00c\x00o\x00n\x00f\x00/\x00c\x00o\x00r\x00e\x00-\x00s\x00i\x00t\x00e\x00.\x00x\x00m\x00l\x00', '\x00o\x00w\x00n\x00e\x00r\x00': '\x00h\x00d\x00f\x00s\x00', '\x00d\x00e\x00s\x00t\x00': '\x00e\x00t\x00c\x00/\x00h\x00a\x00d\x00o\x00o\x00p\x00/\x00c\x00o\x00n\x00f\x00/\x00c\x00o\x00r\x00e\x00-\x00s\x00i\x00t\x00e\x00.\x00x\x00m\x00l\x00', '\x00m\x00o\x00d\x00e\x00': '\x000\x006\x004\x004\x00', '\x00g\x00r\x00o\x00u\x00p\x00': '\x00h\x00a\x00d\x00o\x00o\x00p\x00'}
```

Looks as if it's converting to UTF-16, or there's some UCS2 vs UCS4 issue...  No idea.  This is with Python 2.7.2 64-bit UCS2 built from source on rhel5.  Python 2.7.3 works fine.

**Comment by mpdehaan** [comment]
I'll see if I can repro this, this is likely just a string being passed where something expects a list.

**Comment by mpdehaan** [comment]
which branch?

**Comment by jkleint** [comment]
devel, but it's likely Python's fault, not yours.  It was literally sticking one thing into a dictionary and getting another out.  Upgrading Python fixed it.

**Comment by mpdehaan** [comment]
Built from source, didn't see that earlier..  Ok, I don't think anyone's going to be using that particular version, so closing this.   Thanks!
