### ISSUE TITLE
security risk: ansible reads "ansible.cfg" from current working directory

### ISSUE THREAD

**Issue by mdellweg** [ansible/ansible#27762]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /home/vagrant/ansible.cfg
  configured module search path = [u'modules']
  python version = 2.7.13+ (default, Jul 19 2017, 18:15:03) [GCC 6.4.0 20170704]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Security risk: Ansible reads and uses options from an ansible.cfg file in the current working directory iff it exists.
In case the security relevance is not obvious to anyone: It is possible to completely reconfigure ansible (e.g. to include malicious modules) whenever an admin runs it from a directory you have control over.
That is exactly, why you do not include '.' in your PATH variable, and it breaks any expectation a typical unix admin has on a tool that executes code on any machine with user_id == 0.

This has already been mentioned by @bcoca in https://github.com/ansible/ansible/issues/11175#issuecomment-109493707, but might have gone unheard by being burried deep inside another issue.

##### STEPS TO REPRODUCE
create malicious ansible.cfg
call ansible

##### EXPECTED RESULTS
ansible should not read "./ansible.cfg"

##### ACTUAL RESULTS
ansible replaces all configuration by options found in "./ansible.cfg"

**Comment by bcoca** [comment]
closing as dupe of #11175, sadly we won't be able to revise ansible.cfg search paths anytime soon as too many people rely/want this behaviour. I advise to avoid running Ansible from directories you don't control in the meantime.
