### ISSUE TITLE
Implement yum clean/makecache support 

### ISSUE THREAD

**Issue by infrascripting** [ansible/ansible#27780]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /opt/uss/ansible/config/2.3.1.cfg
  configured module search path = [u'/usr/share/ansible']
  python version = 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

From the original issue:

version
`ansible v2, devel`

issue
when changing multiple yum repos (e.g. in a common/base role), it can be necessary to clean the cache so yum will refresh and any future actions will get the updated meta.

current
it's necessary to either run a shell/command,

- command: yum clean all

which currently gives a warning [WARNING]: Consider using yum module rather than running yum

Or put update_cache: yes in at least one yum (present, installed, latest) task after the repo changes. If there isn't such a yum task after repo changes, then we don't get the updates. Which means we'd need to put update_cache: yes elsewhere we use yum - which is likely overkill.

desired

    the ability to use update_cache as a standalone action
    (optional) a param to `clean XYZ`.

### LINK: https://github.com/ansible/ansible-modules-core/issues/2667

**Comment by DBezemer** [comment]
Note that update_cache observes the configured metadata cache timeout and will only refresh when this timeout is reached. This means it's **NOT** comparable to yum clean metadata or yum clean all as this force-refreshes the yum metadata information and cache.

**Comment by gantte** [comment]
I support this feature update idea.
There is current no way to "yum clean all", other than via command: module.  
Using command: yum clean all, provides a warning:
 [WARNING]: Consider using yum module rather than running yum
If I could actually USE the yum module and pass "clean all", I would.

**Comment by jborean93** [comment]
Some more history https://github.com/ansible/ansible/issues/29976

**Comment by sengaya** [comment]
I did not discover this issue (and the previous issues) until now. I implemented `yum clean` just 2 days ago, see https://github.com/ansible/ansible/pull/31450

**Comment by sengaya** [comment]
My PR will not be merged, see https://github.com/ansible/ansible/pull/31450#issuecomment-352889579

**Comment by kcd83** [comment]
I can see how this feature needs to be idempotent. How does apt achieve this?
```
  apt:
    update_cache: yes
    cache_valid_time: 86400 # one day
```
(in other words can a yum module do the same)

**Comment by sengaya** [comment]
The `update_cache` option is only about updating the cache (I guess running `apt-get udpate`). As far as I can see there is no option to run `apt-get clean` which would be the equivalent to `yum clean`.

**Comment by kcd83** [comment]
I would think the only reason to clean is to ensure the next package action does an update... clear cache vs clear cache and update

**Comment by sivel** [comment]
Per the decision in https://github.com/ansible/ansible/pull/31450 I am going to close this issue out.
