### ISSUE TITLE
Template all files under a directory

### ISSUE THREAD

**Issue by jkleint** [ansible/ansible#278]
I'd like to use Ansible to set all my systems' configuration files in one go.  Currently, if you want to template a bunch of files, you have to list each one in a `with_items` clause, and a separate template action is run for each one, which is slow.  It would be nice if you could just give it a source and dest directory, and it would recursively template each file in the source directory to the corresponding location in the dest directory.  

You could either give the template module `srcdir` and `destdir` parameters, or do it with a separate `templatedir` module.  Thoughts?

**Comment by mpdehaan** [comment]
templatedir sounds reasonable as a runner module, but it would make sense that there was also a copydir, and I would stick with naming params 'src' and 'dest'.

something you are going to work on?

(speed will mostly be handled by local playbook execution with ansible pulling over git, which is in work)

**Comment by jkleint** [comment]
Cool, thanks.  I probably won't get to it until it really becomes a problem.  ;)

**Comment by mpdehaan** [comment]
closing

**Comment by michael-donat** [comment]
Guys, any planned movement on this? Closed without a comment some 3 years ago ;)

**Comment by tduchateau** [comment]
Same question as @michael-donat :-)
