### ISSUE TITLE
pre_handlers and post_handlers playbook properties

### ISSUE THREAD

**Issue by logan2211** [ansible/ansible#27813]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

Playbooks

##### SUMMARY

It would be extremely handy if ansible allowed a pre_handlers and post_handlers list of tasks to be defined as handlers that should always run before or after the normal handlers lists in the playbook or roles.

Currently, take a galera cluster behind a set of haproxy load balancers for example. The galera role does not have any awareness of the haproxy load balancer, or other load balancers that may be supported by the project, because it has no need to. The playbook should handle orchestrating the load balancer management. However that is difficult currently because handlers from the role, such as "restart mysql", cannot be wrapped with a "take down load balancer endpoint" and "activate load balancer endpoint" task without defining all 3 handlers in the playbook at the same execution level.

The ability to wrap handlers in the role, such as "restart mysql", with a handler in the playbook that may be listening to the same "restart mysql" notification to take down the load balancer endpoint as a pre_handler, restart mysql using the handler in the role, and then bring the LB endpoint back active in the post_handlers, would be an extremely valuable feature for ansible to add.

**Comment by alikins** [comment]
pinging @jimi-c

**Comment by alikins** [comment]
One variation of this that I've wanted before is per task/role/block handlers. A handler attached directly to a task would get run immediately after task completion.

Sort of an analog to event handlers attached to widgets in a GUI app. For any event, the widget is checked if it has a handler for handling the event, and if not, the parent widget is checked, continuing up to the root widget. A ansible handler attached to a block or task would get the chance to process the request before the top level handlers are tried at the end of the play.

**Comment by resmo** [comment]
I think, the `handlers listen` clause would be a use case for this. I created an example project https://github.com/resmo/tmp-ansible-handlers-listen-lb.  NOTE: The key point is that the mysql role has no dependency to the lb role handlers.

This is output is below

~~~
 $ ansible-playbook test.yml

PLAY [localhost] *****************************************************************************************************************************************************************

TASK [mysql : change config of service] ******************************************************************************************************************************************
changed: [localhost]

RUNNING HANDLER [lb-common : take member out of LB] ******************************************************************************************************************************
ok: [localhost] => {
    "msg": "take member localhost out of LB"
}

RUNNING HANDLER [mysql : restart mysql] ******************************************************************************************************************************************
ok: [localhost] => {
    "msg": "mysql restarted"
}

TASK [lb-member : ensure host is in LB] ******************************************************************************************************************************************
ok: [localhost] => {
    "msg": "host localhost is behind LB"
}

PLAY RECAP ***********************************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0  
~~~

**Comment by jimi-c** [comment]
Handlers execute in the order they're defined, ordering them should not really be a problem.

**Comment by logan2211** [comment]
@jimi-c: When handlers are defined in the playbook they are scheduled _after_ role handlers. I'm proposing that ansible offer orchestration at the playbook level to control how playbook handlers are scheduled.

I played around with some workaround ideas tonight here https://github.com/Logan2211/tmp-ansible-27813, thanks @alikins for an idea on that. In the ``workaround`` the downside I see is this: If I'm using an upstream role to deploy a service (pretend ``testservice`` role is galaxy sourced and not mine), I probably don't have control over what handlers it is notifying so I have to add a listener to my LB orchestration role for everything. So aside from not being able to specify ordering at the playbook level, I also don't have the ability to provide a Jinja2 var to my LB orchestration role to implement a dynamic "listen" for the handler tasks. This is demonstrated in ``featurereq``. It would be nice if the ``listen:`` could accept a templated var to avoid having to define a bunch of one-off listens in that role that all try to match upstream notification names.

**Comment by jimi-c** [comment]
Hi, this feature request has been open for well over a year but has not received any attention. Additionally, now that `include/import_role` exist controlling the execution order of roles is much easier. Due to the above, we're going to close this issue.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
