### ISSUE TITLE
get_url should check if directory exists

### ISSUE THREAD

**Issue by philipwhiuk** [ansible/ansible#27836]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ansible/get_url

##### ANSIBLE VERSION
Commit 0765ceb66dfad116ec0519a0f9272158da6600d0 (current master)

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Ansible should report if the current directory doesn't exist.

It already checks if the file exists, but not the directory.

##### STEPS TO REPRODUCE
Provide the path to a non-existing directory

##### EXPECTED RESULTS
"Destination %s does not exist"

##### ACTUAL RESULTS
"Destination %s not writable"

##### Relevant LOC

https://github.com/ansible/ansible/blob/0765ceb66dfad116ec0519a0f9272158da6600d0/lib/ansible/modules/net_tools/basics/get_url.py#L519

**Comment by jborean93** [comment]
Hi @philipwhiuk, a PR was just merged to fix this.
