### ISSUE TITLE
proxmox module

### ISSUE THREAD

**Issue by prologic** [ansible/ansible#2784]
It would be really nice if we could have a **proxmox** module much like ec2 and friends where one could create plays that create and maintain openvz or kvm guests (via the proxmox api). The Python library I had in mind which seems nice is: https://github.com/baseblack/proxmoxia

Anyone else interested?

**Comment by mpdehaan** [comment]
Perhaps something to talk about on the list, where it will get some more eyeballs and generate some more discussion than the bug tracker?
