### ISSUE TITLE
Skipped tasks cause "when: result.changed" to fail

### ISSUE THREAD

**Issue by knightlabs** [ansible/ansible#2787]
In the following scenario from https://gist.github.com/knightlabs/aa03bce563dbf5a57247, if the Makefile from the configure step exists, the task is skipped, and the task checking "when: result.changed" then fails with:

"Conditional expression must evaluate to True or False: {% if configured.changed %} True {% else %} False {% endif %}" 

Per mdehaan:

10:38 mdehaan: bug: ok, so when the task comes back with 'skipped' it looks like I should also add a "changed=False", can you file a github ticket?
10:39 bug: will do
10:39 mdehaan: I believe the answer may be slightly different than what I said but will figure it out and get you something

**Comment by mpdehaan** [comment]
dup of #2685

**Comment by mpdehaan** [comment]
fixed, see other ticket, thanks

**Comment by knightlabs** [comment]
Saw, and thanks!
