### ISSUE TITLE
Install multiple packages at once with yum and apt

### ISSUE THREAD

**Issue by jkleint** [ansible/ansible#279]
I'd like to use Ansible to install a big list of packages.  Currently, I have to list each package in the with_items clause of a yum action.  This is a bit cumbersome to maintain, as the packages have to be listed in dependency order.  It runs a separate yum invocation for each package, which is especially slow since yum has a large startup overhead.  It would be nice if I could give yum (or apt) a list of packages to install.  

For the implementation, you could probably get away with passing a space-separated list of package names to the pkg= parameter.  The list could come from a vars_files list and a little Jinja2.  Thoughts?

**Comment by mpdehaan** [comment]
you can, see with_items in the docs.

**Comment by jkleint** [comment]
Right; it's possible, but it's cumbersome and slow.  It runs a separate yum install for each package, no?  And if I need to install hadoop before hadoop-hdfs, I have to manually figure out the dependencies among my packages and order them myself.  If I just slap them all on one yum command, I don't have to do that.

**Comment by mpdehaan** [comment]
I don't want all modules to start inconsistently taking lists.  Does hadoop-hfs not properly require hadoop?   It should.   You can of course just execute yum or create a yum meta-package that describes want to install.

Ansible is in many ways a Minimal Viable Product, so I think there are enough options here that we don't have to teach every module to operate in list mode.   Edit to be clear -- I "think" means I'm not going to do it :)

**Comment by jkleint** [comment]
Fair enough; I can use the command module.

**Comment by mpdehaan** [comment]
right

**Comment by mpdehaan** [comment]
compromise plan:  doing yum only is ok, and I'll make with_items do magic.   apt can follow later as it is too hard to coordinate otherwise :)

**Comment by goozbach** [comment]
I'm currently looking at this. 

I'll add the comma delimited packages, for mpdehaan to come back and do the magic.

**Comment by mpdehaan** [comment]
Note to self:

once this is done, we will be able to make with_items work with host specific vars_files also, just for the modules that support this.   So basically if you wanted to keep a list of packages per host in ${inventory_hostname}_packages.yml, that would work with this.

**Comment by mpdehaan** [comment]
now implemented for both modules + the core with_items code.   Thanks everyone!
