### ISSUE TITLE
Feature Request: Ability to Run Shell Scripts in only_if or Similar Construct

### ISSUE THREAD

**Issue by copperlight** [ansible/ansible#2793]
I would like the ability to have shell tests attached to command modules.
- name: enable swapfile
  command: swapon /swapfile if_test="grep '^/swapfile' /proc/swaps"

**Comment by mpdehaan** [comment]
Yeah, that's great.

Send me a pull request.

I've updated your syntax to something I would accept.

**Comment by copperlight** [comment]
Oh, that's a lot easier to implement that what I was originally envisioning and it is just as concise.

I'll take a swing at that.

**Comment by mpdehaan** [comment]
yeah FWIW your original example was only 24 lines due to whitespace ... if you drop the optional names, half that :)
