### ISSUE TITLE
ansible can't read user and password from inventory if use bastion node

### ISSUE THREAD

**Issue by justin-ren** [ansible/ansible#27934]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

core
##### ANSIBLE VERSION

```
JUREN-mac:Downloads juren$ ansible --version
ansible 2.3.2.0
  config file = /Users/juren/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT

OS is macOS Sierra 10.12.6, same issue is happened on OL7 Linux with control node installed.

##### SUMMARY

Must use --ask-pass for bastion, or ansible not work.
If not use --ask-pass, this '%h %p' not replace to user/host address

'ProxyCommand=ssh -q root@10.209.2.11 nc %h %p' 
##### STEPS TO REPRODUCE

hosts file:
----
[gatewayed]
rwsbj10-p ansible_host=10.209.12.112
ansible_user=root
ansible_ssh_pass=welcome1

group_vars/gateway.yml
------
 ansible_ssh_common_args: '-o ProxyCommand="ssh -q root@10.209.2.11 nc %h %p"'

```yaml
---
- hosts: 
  - rwsbj10-p
  user: root
  tasks:
    - name: Check node name from jump node 
      command: hostname
      register: name
    - debug: var=name
```
JUREN-mac:Downloads juren$ ansible-playbook ~/AnsibleScripts/my_project/basic_uptime.yml -vvv
Using /Users/juren/.ansible.cfg as config file

PLAYBOOK: basic_uptime.yml **********************************************************************************************************************************************************
1 plays in /Users/juren/AnsibleScripts/my_project/basic_uptime.yml

PLAY [rwsbj10-p] ********************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************
Using module file /Users/juren/Scripts/ansible-2.3.2.0-1/lib/ansible/modules/system/setup.py
<10.209.12.112> ESTABLISH SSH CONNECTION FOR USER: root
<10.209.12.112> SSH: EXEC sshpass -d44 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o 'ProxyCommand=ssh -q root@10.209.2.11 nc %h %p' -o ControlPath=/Users/juren/.ansible/cp/fd714e3ccf 10.209.12.112 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /tmp/.ansible/tmp/ansible-tmp-1502250209.53-8176121225747 `" && echo ansible-tmp-1502250209.53-8176121225747="` echo /tmp/.ansible/tmp/ansible-tmp-1502250209.53-8176121225747 `" ) && sleep 0'"'"''
<10.209.12.112> (5, '', '')
fatal: [rwsbj10-p]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Authentication failure.", 
    "unreachable": true
}
	to retry, use: --limit @/Users/juren/AnsibleScripts/my_project/basic_uptime.retry

PLAY RECAP **************************************************************************************************************************************************************************
rwsbj10-p                  : ok=0    changed=0    unreachable=1    failed=0  

##### EXPECTED RESULTS

need to work without --ask-pass.
##### ACTUAL RESULTS

below is the result with --ask-pass
```
JUREN-mac:Downloads juren$ ansible-playbook ~/AnsibleScripts/my_project/basic_uptime.yml -vvv --ask-pass
Using /Users/juren/.ansible.cfg as config file
SSH password: 

PLAYBOOK: basic_uptime.yml **********************************************************************************************************************************************************
1 plays in /Users/juren/AnsibleScripts/my_project/basic_uptime.yml

PLAY [rwsbj10-p] ********************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************
Using module file /Users/juren/Scripts/ansible-2.3.2.0-1/lib/ansible/modules/system/setup.py
<10.209.12.112> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO 10.209.12.112
<10.209.12.112> CONFIGURE PROXY COMMAND FOR CONNECTION: ssh -q root@10.209.2.11 nc 10.209.12.112 22
root@10.209.2.11's password: 
<10.209.12.112> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/.ansible/tmp/ansible-tmp-1502250794.21-147286405180239 `" && echo ansible-tmp-1502250794.21-147286405180239="` echo /tmp/.ansible/tmp/ansible-tmp-1502250794.21-147286405180239 `" ) && sleep 0'
<10.209.12.112> PUT /var/folders/dd/1vl2w39531dc_tc9lgztp4gw0000gn/T/tmpTYMOPA TO /tmp/.ansible/tmp/ansible-tmp-1502250794.21-147286405180239/setup.py
<10.209.12.112> EXEC /bin/sh -c 'chmod u+x /tmp/.ansible/tmp/ansible-tmp-1502250794.21-147286405180239/ /tmp/.ansible/tmp/ansible-tmp-1502250794.21-147286405180239/setup.py && sleep 0'
<10.209.12.112> EXEC /bin/sh -c '/usr/bin/python /tmp/.ansible/tmp/ansible-tmp-1502250794.21-147286405180239/setup.py; rm -rf "/tmp/.ansible/tmp/ansible-tmp-1502250794.21-147286405180239/" > /dev/null 2>&1 && sleep 0'
ok: [rwsbj10-p]
META: ran handlers

TASK [Check node name from jump node] ***********************************************************************************************************************************************
task path: /Users/juren/AnsibleScripts/my_project/basic_uptime.yml:28
Using module file /Users/juren/Scripts/ansible-2.3.2.0-1/lib/ansible/modules/commands/command.py
<10.209.12.112> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO 10.209.12.112
<10.209.12.112> CONFIGURE PROXY COMMAND FOR CONNECTION: ssh -q root@10.209.2.11 nc 10.209.12.112 22
root@10.209.2.11's password: 
<10.209.12.112> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/.ansible/tmp/ansible-tmp-1502250812.11-67599582475303 `" && echo ansible-tmp-1502250812.11-67599582475303="` echo /tmp/.ansible/tmp/ansible-tmp-1502250812.11-67599582475303 `" ) && sleep 0'
<10.209.12.112> PUT /var/folders/dd/1vl2w39531dc_tc9lgztp4gw0000gn/T/tmpW0Bw2G TO /tmp/.ansible/tmp/ansible-tmp-1502250812.11-67599582475303/command.py
<10.209.12.112> EXEC /bin/sh -c 'chmod u+x /tmp/.ansible/tmp/ansible-tmp-1502250812.11-67599582475303/ /tmp/.ansible/tmp/ansible-tmp-1502250812.11-67599582475303/command.py && sleep 0'
<10.209.12.112> EXEC /bin/sh -c '/usr/bin/python /tmp/.ansible/tmp/ansible-tmp-1502250812.11-67599582475303/command.py; rm -rf "/tmp/.ansible/tmp/ansible-tmp-1502250812.11-67599582475303/" > /dev/null 2>&1 && sleep 0'
changed: [rwsbj10-p] => {
    "changed": true, 
    "cmd": [
        "hostname"
    ], 
    "delta": "0:00:00.009806", 
    "end": "2017-08-09 03:53:44.607322", 
    "invocation": {
        "module_args": {
            "_raw_params": "hostname", 
            "_uses_shell": false, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }
    }, 
    "rc": 0, 
    "start": "2017-08-09 03:53:44.597516", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "rwsbj10", 
    "stdout_lines": [
        "rwsbj10"
    ]
}

TASK [debug] ************************************************************************************************************************************************************************
task path: /Users/juren/AnsibleScripts/my_project/basic_uptime.yml:31
ok: [rwsbj10-p] => {
    "name": {
        "changed": true, 
        "cmd": [
            "hostname"
        ], 
        "delta": "0:00:00.009806", 
        "end": "2017-08-09 03:53:44.607322", 
        "rc": 0, 
        "start": "2017-08-09 03:53:44.597516", 
        "stderr": "", 
        "stderr_lines": [], 
        "stdout": "rwsbj10", 
        "stdout_lines": [
            "rwsbj10"
        ]
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP **************************************************************************************************************************************************************************
rwsbj10-p                  : ok=3    changed=1    unreachable=0    failed=0   


```

**Comment by justin-ren** [comment]
Also hit this issue if use red-hat ol7 linux node as control node.
Aso tried to install ssh-pass on bastion, but not help.
Tried other target node configured OpenSSH later than 5.4, and use 'ssh -W %h:%p'. 
Still hit this problem.

**Comment by nitzmahone** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel. Bastion host configuration via ssh is not actually a supported option- though it can  be done, debugging credential issues can be quite complex. 

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by justin-ren** [comment]
It's OK without options, but the password in inventory not work.

**Comment by justin-ren** [comment]
@nitzmahone , please have a look again.

**Comment by justin-ren** [comment]
thank you for replay. I searched all documents in #ansible site, but I
can't find any clue, could you have a look again?

**Comment by chenli0906** [comment]
Have you solved it? I have the same issue.

**Comment by ssarraju** [comment]
Whats the resolution for this? I have the same issue
