### ISSUE TITLE
template: significant slowdown after upgrade to 2.3

### ISSUE THREAD

**Issue by zarnovican** [ansible/ansible#27956]
We have noticed that our production plays run significantly slower on 2.3.2, compared to 2.2.0. It seems, it is caused by `template` tasks (it is worse if they have `with` loops).

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

template module

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.3.2.0
  config file = /home/zarnovic/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jun 26 2017, 10:20:05) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

##### CONFIGURATION

Default (empty) configuration. In the tests below, I have included also results with `pipelining=True`.

##### OS / ENVIRONMENT

Target host is `m1.small` Ubuntu 16.04.2 on AWS. EC2 hosts generally have bad latency, which contribute to the percieved speed.

The issue is not platform specific, AFAIK.

##### SUMMARY

Template tasks are significantly slower (30-40%) compared to times on Ansible 2.2. These results are from an AWS EC2 instance. In other environments, the slowdown might be less dramatic.

Analyzing the issue, I have found the commit causing the problem: cdd6ab000b2c85d5dd0dc86c2ae8580e6978b819. It is related to https://github.com/ansible/ansible/pull/24477

My understaning of the code change, is that if you are using `template` where destination is a file, then ansible will do one additional remote command to check if the target exists and it is a directory. This will slowdown the task. It is worse, if you have multiple templates files (in a loop) and you are copying them to target host, which is slow by itself.

Time to run Ansible play in various configurations:
```
ansible 2.2.3 (pipelining=False): 17.671, 18.843, 17.411 ~ avg 18.0s
ansible 2.3.2 (pipelining=False): 25.603, 26.426, 25.423 ~ avg 25.8s (+43%)

ansible 2.2.3 (pipelining=True): 9.320, 9.104, 9.279 ~ avg 9.23s
ansible 2.3.2 (pipelining=True): 12.778, 12.127, 12.775 ~ avg 12.56s (+36%)
```

##### STEPS TO REPRODUCE

1. create some empty jinja template files

```bash
touch foo{0..4}.j2
```

2. create an inventory file with your target host

```
echo "foo.example.com" > inventory
```

3. playbook
```yaml
---
- name: 'Foo'
  hosts: all

  tasks:
  - name: 'copy some files'
    template:
      src: "{{ item }}"
      dest: "/tmp/{{ item | basename | splitext | first }}"
      #dest: /tmp/
    with_fileglob: "*.j2"
```

4. run
```bash
time ansible-playbook -i inventory site.yaml
```

##### EXPECTED RESULTS

Times on Ansible 2.2.3:
```bash
$ time ansible-playbook -i inventory site.yaml 
...
real	0m17.295s
user	0m4.479s
sys	0m0.848s
```

##### ACTUAL RESULTS

Times on Ansible 2.3.2:
```
$ time ansible-playbook -i inventory site.yaml 

PLAY [Foo] ***************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [foo.example.com]

TASK [copy some files] ***************************************************************************************************************************************
ok: [foo.example.com] => (item=/home/zarnovic/tmp/ansible_test/foo3.j2)
ok: [foo.example.com] => (item=/home/zarnovic/tmp/ansible_test/foo2.j2)
ok: [foo.example.com] => (item=/home/zarnovic/tmp/ansible_test/foo1.j2)
ok: [foo.example.com] => (item=/home/zarnovic/tmp/ansible_test/foo0.j2)
ok: [foo.example.com] => (item=/home/zarnovic/tmp/ansible_test/foo4.j2)

PLAY RECAP ***************************************************************************************************************************************************
foo.example.com           : ok=2    changed=0    unreachable=0    failed=0   


real	0m25.635s
user	0m4.340s
sys	0m1.226s
```
Notice the time difference: 17.3s vs 25.6s !!

**Comment by abadger** [comment]
This isn't a bug as ansible's behaviour is more correct now.  I'll see if I can get any of that speed difference back but we have to have correct behaviour even if it is slower.

**Comment by abadger** [comment]
@zarnovican See if #28044 fixes this for you.  For my tests using ssh against a local VM and ssh against localhost it provides a significant speedup but is still a little slower than the 2.2.x code.  However, it does one less round trip than the 2.2.x code (when piplining is off) so I think it should be comparable or perhaps even a little faster for your workload.

**Comment by zarnovican** [comment]
@abadger I have re-tested it from your branch and it looks good :+1: 
```
ansible 2.2.3 (pipelining=False): 16.259, 16.275, 17.495 ~ avg 16.6s
ansible 2.4.x-PR (pipelining=False): 18.389, 17.394, 17.299 ~ avg 17.7s
```
I have also retested it on one real ansible play:
```
ansible 2.2.0      41.480s
ansible 2.4.x-PR   45.427s
ansible 2.3.2      66.220s
```

**Comment by abadger** [comment]
Thanks for testing!

**Comment by karolyi** [comment]
I can attest to the fact that py36-ansible-2.7.5 is still **significantly** slower in executing tasks than 2.3 was.
