### ISSUE TITLE
fallback argument_spec parameter is broken

### ISSUE THREAD

**Issue by caphrim007** [ansible/ansible#27978]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

AnsibleModule

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = None
  configured module search path = [u'/Users/trupp/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/trupp/src/envs/ansible-dev/lib/python2.7/site-packages/ansible
  executable location = /Users/trupp/src/envs/ansible-dev/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION
[defaults]
retry_files_enabled = False
host_key_checking=False
library=./library

##### OS / ENVIRONMENT
Mac OSX Sierra (10.12.6)

##### SUMMARY

fallback functionality for an argument spec is broken.

##### STEPS TO REPRODUCE

Download the following module and put it in `repro.py` in your `library` directory
* https://gist.github.com/caphrim007/8dd2f8ad3f7a58b6186ec53ba97cc96a

Next, download the example playbook and put it in `repro.yaml`
* https://gist.github.com/caphrim007/cfaa7b8d1edef984fb2e2c416980e804

Finally, run the following command

`ansible-playbook -i notahost, repro.yaml`

##### EXPECTED RESULTS

I expect that the playbook should run without error. "ok" should equal 2

##### ACTUAL RESULTS

The playbook fails with the error

`"msg": "missing required arguments: server"`

```
(ansible-dev) SEA-ML-RUPP1:f5-ansible trupp$ ansible-playbook -i notahost, repro.yaml 

PLAY [Test the bigip_dns_record_facts module] ************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************
ok: [notahost]

TASK [Repro 27119] ***************************************************************************************************************************
task path: /Users/trupp/src/trupp/f5-ansible/repro.yaml:9
Using module_utils file /Users/trupp/src/envs/ansible-dev/lib/python2.7/site-packages/ansible/module_utils/basic.py
Using module_utils file /Users/trupp/src/envs/ansible-dev/lib/python2.7/site-packages/ansible/module_utils/_text.py
Using module_utils file /Users/trupp/src/envs/ansible-dev/lib/python2.7/site-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /Users/trupp/src/envs/ansible-dev/lib/python2.7/site-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /Users/trupp/src/envs/ansible-dev/lib/python2.7/site-packages/ansible/module_utils/pycompat24.py
Using module_utils file /Users/trupp/src/envs/ansible-dev/lib/python2.7/site-packages/ansible/module_utils/six/__init__.py
Using module file /Users/trupp/src/trupp/f5-ansible/library/repro.py
<notahost> ESTABLISH LOCAL CONNECTION FOR USER: trupp
<notahost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<notahost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/trupp/.ansible/tmp/ansible-tmp-1502309149.77-186982986195915 `" && echo ansible-tmp-1502309149.77-186982986195915="` echo /Users/trupp/.ansible/tmp/ansible-tmp-1502309149.77-186982986195915 `" ) && sleep 0'
<notahost> PUT /var/folders/jc/9d1188j962931rhqrlm4173w5j5m45/T/tmpMVbdIY TO /Users/trupp/.ansible/tmp/ansible-tmp-1502309149.77-186982986195915/repro.py
<notahost> EXEC /bin/sh -c 'chmod u+x /Users/trupp/.ansible/tmp/ansible-tmp-1502309149.77-186982986195915/ /Users/trupp/.ansible/tmp/ansible-tmp-1502309149.77-186982986195915/repro.py && sleep 0'
<notahost> EXEC /bin/sh -c 'F5_SERVER=1.1.1.1 /usr/bin/python /Users/trupp/.ansible/tmp/ansible-tmp-1502309149.77-186982986195915/repro.py; rm -rf "/Users/trupp/.ansible/tmp/ansible-tmp-1502309149.77-186982986195915/" > /dev/null 2>&1 && sleep 0'
fatal: [notahost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {}
    }, 
    "msg": "missing required arguments: server"
}
        to retry, use: --limit @/Users/trupp/src/trupp/f5-ansible/repro.retry

PLAY RECAP ***********************************************************************************************************************************
notahost                   : ok=1    changed=0    unreachable=0    failed=1   
```

**Comment by caphrim007** [comment]
@nitzmahone @ganeshrn @Qalthos

**Comment by caphrim007** [comment]
Here's another breaking change. A default of `None` used to be perfectly valid and there's no reason it shouldn't stay that way. consider when the user doesn't want to supply a value for a param and they are updating an existing config.

ansible module
* https://gist.github.com/caphrim007/e81df8de85b295535a80f35a30dda172

ansible playbook
* https://gist.github.com/caphrim007/43a80e89acdfed448c2878eaa297609e

The above examples effectively break every f5 module.

**Comment by caphrim007** [comment]
@bcoca @abadger

**Comment by caphrim007** [comment]
correction, that last set of gists was because of the addition of this

https://github.com/ansible/ansible/blob/6d33e59ca19bc8db60281c1022db105d97b61958/lib/ansible/module_utils/basic.py#L1739

is the following syntax no longer valid?

```
            from ansible.module_utils.parsing.convert_bool import BOOLEANS
            full_sync=dict(
                type='bool',
                choices=BOOLEANS
            ),
```

**Comment by nitzmahone** [comment]
It's redundant with `type='bool'` but if it's not still working, that's a bug, too.

Bummer that we don't have a test suite around this yet- I created the basic.py argument_spec unit test when I plugged in the callable validator stuff, but I only covered what I added... All these little dusty corners need to be in there. :(

**Comment by nitzmahone** [comment]
Ah, I remember, @ganeshrn added a bunch of tests in a different place. We should definitely extend those to include regression tests for these things that are failing, along with the fixes...

**Comment by caphrim007** [comment]
@nitzmahone someone on the irc channel mentioned that fallback used to be used by the network modules, but no longer is. what do those modules use instead?

**Comment by nitzmahone** [comment]
Fallback support hasn't been removed from the code, so yet another bug if that's broken. I'm not aware of a different way to do what it does, but someone on the networking team might be able to shed more light.
