### ISSUE TITLE
Add documentation for multiple vault passwords and vault-ids

### ISSUE THREAD

**Issue by alikins** [ansible/ansible#28012]
Need to add docs for vault multiple password support

roadmap item: https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_4.rst#vault
primary implementation pull request: https://github.com/ansible/ansible/pull/22756

(I plan on collecting my notes and getting a draft in soon ish, but obviously will still need a ton of work from docs folks)

##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

vault
docs

##### ANSIBLE VERSION

```
ansible 2.4.0 (issue-20494-tests 81c09b50ec) last updated 2017/08/09 12:39:25 (GMT -400)
  config file = None
  configured module search path = [u'/home/adrian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by abitrolly** [comment]
Are there any notes that can be added as comments at least?

**Comment by alikins** [comment]
Fixed by https://github.com/ansible/ansible/pull/26979
