### ISSUE TITLE
setup module error (possibly because of no ipv4 interfaces?)

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#2802]
```
% ansible all -m copy -u root -a 'src=/home/afsin/.zshrc dest=/home/afsin/.zshrc owner=afsin group=afsin'
```

does work.

but:

```
% ansible-playbook afsin.yaml
```

doesn't work.

```
% nl -ba afsin.yaml
 1 ---
 2   - hosts: all
 3     user: root
 4     tasks:
 5       - name: copy .zshrc
 6         action: copy src=/home/afsin/.zshrc dest=/home/afsin/.zshrc owner=afsin group=afsin
```

**Comment by mpdehaan** [comment]
Output of ansible --version please?

**Comment by mpdehaan** [comment]
/usr/bin/ansible doesn't run the setup module to gather facts, BTW.   So
there's not an incosistency.

Can you also share the output of ifconfig and uname -a ?

I'm wondering if you might not have any ipv4 interfaces (and yes, we'd want
to handle that)

Thanks!

**Comment by mpdehaan** [comment]
I am not sure why but github seems to have eaten the comments here (or they were edited?)

Can you repaste the traceback you were seeing?

**Comment by ghost** [comment]
it was so yesterday. after a refresh git pull it works now...

**Comment by ghost** [comment]
afsin@s15426859:~ % (cd ansible ; git pull)
remote: Counting objects: 54, done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 36 (delta 22), reused 16 (delta 2)
Unpacking objects: 100% (36/36), done.
From git://github.com/ansible/ansible
   4bea9a6..c15d52c  devel      -> origin/devel
Updating 4bea9a6..c15d52c
Fast-forward
 lib/ansible/callbacks.py      |   10 +++++++---
 lib/ansible/playbook/task.py  |    6 ++++++
 lib/ansible/utils/template.py |   35 ++++++++++++++++++++---------------
 library/system/setup          |    2 +-
 setup.py                      |    5 ++++-
 5 files changed, 38 insertions(+), 20 deletions(-)

**Comment by ghost** [comment]
I am using daily copy of github. Here my settings:
     afsin@s15426859:~ % env|fgrep -i ansible
     PATH=/home/afsin/ansible/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/home/afsin/bin
     PYTHONPATH=/home/afsin/ansible/lib:
     ANSIBLE_LIBRARY=/home/afsin/ansible/library
     ANSIBLE_HOSTS=/home/afsin/.inventory
     afsin@s15426859:~ %

**Comment by mpdehaan** [comment]
Thanks, can you share the traceback again?

**Comment by mpdehaan** [comment]
also, can you share your ifconfig output?

**Comment by ghost** [comment]
sorry, I lost my traceback from yesterday. but here ifconfig:

```
afsin@s15426859:~ %  ansible all -m shell -a 'ip a'
vps47673 | success | rc=0 >>
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: venet0: <BROADCAST,POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN
    link/void
    inet 127.0.0.2/32 scope host venet0
    inet 84.201.3.157/32 scope global venet0:0

s15426859 | success | rc=0 >>
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: venet0: <BROADCAST,POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN
    link/void
    inet 127.0.0.1/32 scope host venet0
    inet 87.106.25.155/32 scope global venet0:0

vps48154 | success | rc=0 >>
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: venet0: <BROADCAST,POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN
    link/void
    inet 127.0.0.2/32 scope host venet0
    inet 84.201.25.194/32 scope global venet0:0
```

**Comment by ghost** [comment]
please note I also implemented a change in my first playbook to deaktivate ipv6 from nodes:

```
afsin@s15426859:~ % cat afsin.yml
- hosts: all
  user: root
  tasks:
  - name: copy .zshrc
      action: template src=/home/afsin/.zshrc.j2 dest=/home/afsin/.zshrc owner=afsin group=afsin
  - name: disable ipv6
      action: copy src=/etc/sysctl.d/disable-ipv6.conf dest=/etc/sysctl.d/disable-ipv6.conf
afsin@s15426859:~ %
```

before the two of this three nodes were (default) with IPv6 support. All three are very small virtual servers...

**Comment by ghost** [comment]
ok, now I am understanding GitHub formating features... I will report better in the future...

**Comment by mpdehaan** [comment]
Yeah the markdown formatting in issues can be confusing.  I think the trick
is to indent everything by four spaces.

**Comment by ghost** [comment]
or begin with 

``````
 ``` 
``````

and end with 

``````
```
``````

then everything between them is a clear code block! ;-)

**Comment by ghost** [comment]
``` python
    def foo:
      if not bar:
        return true
```

**Comment by ghost** [comment]
Yeah, now with syntax highlighting!
The trick was to give following (without 4 spaces!)

``````
```python
def foo:
  if not bar:
    return true
```
``````

Then as above ;-)

**Comment by mpdehaan** [comment]
We've fixed some things about missing interfaces and SHOULD be good to go now, can you check with the latest and share your traceback if not?

I did not have the original traceback above to look and know if what was fixed was related or not.   

Thanks!

**Comment by ghost** [comment]
As I said before I lost the mentioned traceback. I updated ansible again, it is working as expected. The situation was only 6 days ago (with a version on that day). Sorry, I can not remember the traceback. I was/am new to GitHub and I didn't copy clearly the traceback in this issue. One day later after Ansible update it was solved.
Best regards!
