### ISSUE TITLE
Too many links: '/tmp/ansible_qlMioE' Error in Ansible 2.3.2

### ISSUE THREAD

**Issue by chenli0906** [ansible/ansible#28049]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### OS / ENVIRONMENT

RedHat 6.5

##### SUMMARY

ansible task：
```
ansible 192.168.1.101 -m ping 
```
error raised 
```
192.168.1.101 | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Shared connection to 192.168.1.101 closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1502415640.53-136978294112636/ping.py\", line 112, in <module>\r\n    temp_path = tempfile.mkdtemp(prefix='ansible_')\r\n  File \"/usr/local/python2.7/lib/python2.7/tempfile.py\", line 333, in mkdtemp\r\n    _os.mkdir(file, 0700)\r\nOSError: [Errno 31] Too many links: '/tmp/ansible_2MFKNR'\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
