### ISSUE TITLE
Possible quote filter issue

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#28084]
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME
Template Module

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I'd like to use the `map("quote")` filter to surround elements of a list with quotes.
It seems that this does not work as expected as some strings are quoted - some are not.

##### STEPS TO REPRODUCE

I've setup a repo to demonstrate this:
https://github.com/yves-vogl/ansible-quote-issue.git

This is my list:

```yaml
---
  
backuppc_config_backup_files_exclude:
  - '/dev/*'
  - '/proc/*'
  - '/sys/*'
  - '/tmp/*'
  - '/var/tmp/*'
  - '/var/log/*'
  - '/var/cache/*'
  - '/mnt'
  - '/var/named/run-root/proc/*'
  - '/var/lib/php5/*'
  - '*/temp/*'
  - '*/tmp/*'
  - '*/.spamassassin/bayes_journal'
  - '/var/lib/php/session/*'
  - '/var/lib/BackupPC/*' 
```

That's the task:

```yaml
---
  
  
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Configure BackupPC server
      template: 
        src: "exclude.txt.j2" 
        dest: "/tmp/exclude.txt"
```

And that's the run:

```yaml
ansible-playbook -i inventory tasks.yml --diff

PLAY [localhost] *********************************************************************************************************************************************************

TASK [Configure BackupPC server] *****************************************************************************************************************************************
--- before
+++ after: dynamically generated
@@ -0,0 +1,5 @@
+$Conf{BackupFilesExclude} = {
+  '*' => [
+    '/dev/*', '/proc/*', '/sys/*', '/tmp/*', '/var/tmp/*', '/var/log/*', '/var/cache/*', /mnt, '/var/named/run-root/proc/*', '/var/lib/php5/*', '*/temp/*', '*/tmp/*', '*/.spamassassin/bayes_journal', '/var/lib/php/session/*', '/var/lib/BackupPC/*'
+  ]
+};
\ No newline at end of file

changed: [localhost]

PLAY RECAP ***************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```

As you can see, the element */mnt* is not quoted.

##### EXPECTED RESULTS
I'd have expected that even *"/mnt"* would have been quoted.

##### ACTUAL RESULTS
*/mnt* is not beeing quoted.

**Comment by dagwieers** [comment]
So, first of all in YAML you don't need to quote strings, you only have to quote special strings (e.g. when it consists of something that YAML would misinterpret, like `: ` in a dict-value or `,` in a list-value). So in your example playbooks, no string in there actually requires quoting (not even the ones with an asterisk). We usually recommend to only quote when it is required, this helps to understand YAML better.

That said, there's something similar going on for the quote-filter in Ansible. The documentation of that filter states: "return its argument quoted for shell usage". So the quote filter decides that a string with an asterisk needs to be quoted, but "/mnt" is fine without quotes. Which is correct for shell usage.

I don't think the quote-filter is what you need to use for your use-case as your intended output is not specific to the shell. It's probably easier to do the formatting in a for-loop inside a jinja2-block and add your quotes and comma exactly the way as required for the configuration file format.

**Comment by dagwieers** [comment]
If you think we should update the existing documentation so this is more clear for future users, feel free to propose the required changes as a PR to the documentation. You don't even need to use Git, you can directly edit documentation files inside the Github web-interface in order to create a PR with your recommended changes).

**Comment by acozine** [comment]
The comments above address the use case, and this issue is now owned by `ghost`. Closing.
