### ISSUE TITLE
'zip' template filter is missing under python3

### ISSUE THREAD

**Issue by andriilahuta** [ansible/ansible#28117]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
zip template filter

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 3.6.0+ (default, Feb  4 2017, 11:11:33) [GCC 4.9.4]
```

##### CONFIGURATION

None

##### OS / ENVIRONMENT

Ubuntu

##### SUMMARY
Ansible can't load zip filter under python3. The problem seems to be at this line: 
https://github.com/ansible/ansible/blob/21bd7bcbb09d21f2c9a33cd2d6ff906de3cd0926/lib/ansible/plugins/filter/mathstuff.py#L164
zip is a builtin function in python3 and is not located in itertools

##### STEPS TO REPRODUCE

```yaml
ansible -m debug -a "msg={{ [1,2,3]|zip(['a','b','c'])|list }}" all
```

##### EXPECTED RESULTS

Output
```
<hostname> | SUCCESS => {
    "msg": [
        [
            1,
            "a"
        ],
        [
            2,
            "b"
        ],
        [
            3,
            "c"
        ]
    ]
}
```

##### ACTUAL RESULTS

```
<hostname> | FAILED! => {
    "failed": true,
    "msg": "template error while templating string: no filter named 'zip'. String: {{ [1,2,3]|zip(['a','b','c'])|list }}"
}
```

**Comment by andreaso** [comment]
Yepp, looks like you are right about the cause.

I have created the https://github.com/ansible/ansible/pull/28158 pull request.
