### ISSUE TITLE
dynamic include

### ISSUE THREAD

**Issue by kernel164** [ansible/ansible#2814]
I'm trying to use dynamic include as shown below.

<pre>
- include: java{{ java_version }}-{{ java_install_mode }}.yml
</pre>

currently it is not working.

**Comment by mpdehaan** [comment]
insufficient data provided.

suggest possibly reading:  http://www.catb.org/esr/faqs/smart-questions.html :)

doesn't work how?  Where are your variables set?   Etc.    

As this is not a great place for a support forum, please stop by the mailing list.

**Comment by kernel164** [comment]
sorry :)

**Comment by kernel164** [comment]
folder structure:
- playbook
  - group_vars
    - all // the variables
  - roles
    - common
      - tasks
        - main.yml // include is here

file: playbook/group_vars/all

<pre>
java_version: 7
java_install_mode: apt
</pre>

file: playbook/roles/common/tasks/main.yml

<pre>
- include: java${java_version}-${java_install_mode}.yml
</pre>

I'm using vagrant and the 'vagrant provision' output is

<pre>
....
[default] Running provisioner: ansible...
ERROR: file not found: .../playbook/roles/common/tasks/java${java_version}-${java_install_mode}.yml
</pre>

I will try to test few more time and discuss in forum if I couldn't solve. :) thanks

**Comment by mpdehaan** [comment]
inventory scoped variables can differ per host and are not available when choosing include paths to task files -- all the tasks need to be the same for all hosts.

other good options include conditional vars_files (which do work), group_by to slice up hosts where a condition is true, or using a conditional.
