### ISSUE TITLE
File module fails on broken symbolic links when follow=yes and recurse=yes

### ISSUE THREAD

**Issue by mabes** [ansible/ansible#28165]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
file module

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel b9c3329950) last updated 2017/08/14 16:27:45 (GMT +200)
  config file = /home/user/.ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/tmp/ansible/lib/ansible
  executable location = ./bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION
No configuration

##### OS / ENVIRONMENT
Tested on Debian Stretch and Centos 7

##### SUMMARY
Ansible's file module crashes when encountering an invalid symlink when the *recurse* and *follow* options are both enabled

##### STEPS TO REPRODUCE

```
mkdir /tmp/testdir
ln -s invalid /tmp/testdir/a
ansible -i localhost, -c local -m file -a "path=/tmp/testdir mode=0755 state=directory recurse=yes follow=yes" localhost
```

##### EXPECTED RESULTS

Invalid symlinks, although they may indicate an issue somewhere else, should not crash Ansible. They could however display a warning to the user.

My use case is a web application that has a test directory containing a purposefully broken symlink for its own non-regressions tests. I expect Ansible to silently skip this link when attempting to recursively change all permissions on a parent dir.

##### ACTUAL RESULTS

The current result of the above command is:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 2] No such file or directory: '/tmp/testdir/invalid'
localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_zjolcA/ansible_module_file.py\", line 472, in <module>\n    main()\n  File \"/tmp/ansible_zjolcA/ansible_module_file.py\", line 349, in main\n    changed |= recursive_set_attributes(module, to_bytes(file_args['path'], errors='surrogate_or_strict'), follow, file_args)\n  File \"/tmp/ansible_zjolcA/ansible_module_file.py\", line 173, in recursive_set_attributes\n    changed |= module.set_fs_attributes_if_different(tmp_file_args, changed, expand=False)\n  File \"/tmp/ansible_zjolcA/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1450, in set_fs_attributes_if_different\n  File \"/tmp/ansible_zjolcA/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1181, in set_mode_if_different\nOSError: [Errno 2] No such file or directory: '/tmp/testdir/invalid'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

**Comment by alikins** [comment]
ping @abadger

**Comment by alikins** [comment]
@mabes was this working in earlier versions of ansible? (curious if this is a regression)

**Comment by mabes** [comment]
@alikins good question, I assumed it never worked, but after bisection 
the test starts failing at d0556885ff8cad8d0899757a0132a360a44d272c

This commit makes the follow+recurse combo work correctly for valid 
symbolic links, which it didn't before. But it introduces the crash on 
invalid symlinks, which in my humble opinion are legitimate or at least 
are to be expected on a filesystem.

Should I file this bug against the module repo instead?

**Comment by abadger** [comment]
We've merged allmodules into the ansible/ansible repo so this is the proper place for a ticket.

Here's the ticket that lead to d055688:
* https://github.com/ansible/ansible-modules-core/issues/778

There were two commits stemming from that; one in file and one in basic.py.

For 2.4 I rewrote a large amount of the copy module to handle this and other, similar problems.  It seems like we'll have to do something similar for file.  Probably move the code I rewrote for copy into module_utils and make both the copy action plugin and file module use it.

Not sure if that's going to make 2.4 or will have to wait for 2.5.... This would technically be a bugfix so it would be okay that way but it's a large invasive change to a very central module so it would be hard to justify for 2.4 because of that.

**Comment by Hnasar** [comment]
Ran into this because ansible 2.5 changed the default of `follow` to `yes`:
http://docs.ansible.com/ansible/latest/modules/file_module.html

**Comment by kamathe** [comment]
This seems to be working for me

Setup information

```bash
[root@dhcp209-142 x]# ansible --version
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
[root@dhcp209-142 x]# 
[root@dhcp209-142 x]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.6 (Maipo)
[root@dhcp209-142 x]# 
[root@dhcp209-142 x]# uname  -a
Linux dhcp209-142.testsetup.com 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@dhcp209-142 x]# 
```

Steps to reproduce

```bash
[root@dhcp209-142 x]# mkdir /tmp/testdir
[root@dhcp209-142 x]# 
[root@dhcp209-142 x]# ln -s invalid /tmp/testdir/a
[root@dhcp209-142 x]# 
[root@dhcp209-142 x]# ls -l
total 4
-rwxr-xr-x. 1 root root 181 Jul 26 15:18 test.py
[root@dhcp209-142 x]# find /tmp/ | grep -i invalid
[root@dhcp209-142 x]# ls -l /tmp/testdir/a 
lrwxrwxrwx. 1 root root 7 Jul 26 15:24 /tmp/testdir/a -> invalid
[root@dhcp209-142 x]# 
[root@dhcp209-142 x]# ansible -i localhost, -c local -m file -a "path=/tmp/testdir mode=0755 state=directory recurse=yes follow=yes" localhost
localhost | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": false, 
    "gid": 0, 
    "group": "root", 
    "mode": "0755", 
    "owner": "root", 
    "path": "/tmp/testdir", 
    "secontext": "unconfined_u:object_r:user_tmp_t:s0", 
    "size": 15, 
    "state": "directory", 
    "uid": 0
}
[root@dhcp209-142 x]# 
[root@dhcp209-142 x]# ls -l /tmp/testdir/a 
lrwxrwxrwx. 1 root root 7 Jul 26 15:24 /tmp/testdir/a -> invalid
[root@dhcp209-142 x]# 
[root@dhcp209-142 x]# 
```

**Comment by s-hertel** [comment]
The error seems to be handled properly on recent versions. If this is affecting you on 2.16+, please open a new issue, or reach out on IRC or the mailing list.

   * IRC: #ansible on [irc.libera.chat](https://libera.chat/)
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

See  this page for a complete and up to date list of communication channels and their purposes:

   * https://docs.ansible.com/ansible/latest/community/communication.html
