### ISSUE TITLE
Docs need to be clear about defining the PASSWORD lookup 'length=' parameter 

### ISSUE THREAD

**Issue by joelrebel** [ansible/ansible#2821]
Hey,

 I could not figure from that docs how  $PASSWORD lookup accepts the 'length' parameter.

I ended up trying multiple methods to pass the length value, until I looked at the code.
Seems like PASSWORD expects its args to be space separated and not comma separated values.

Defining something like : PASSWORD(/some/file,6) resulted in a file being created with the name  '/some/file,6' 

Maybe this might have been my oversight, and I have missed reading the right docs, if so this can be ignored! :)

**Comment by mpdehaan** [comment]
Can you share what version of Ansible you are using?

**Comment by mpdehaan** [comment]
This info from another ticket since I was looking recently and failed to reply (sorry!   perhaps answered on list already for you)

```
It's $PASSWORD(foo length=6) 
```

In 1.2

```
{{ lookup('password','/some/file length=6') }}
```

Yes, we do need to add to docs...
