### ISSUE TITLE
ansible complains about unbalanced quotes, when they are indeed balanced

### ISSUE THREAD

**Issue by x-yuri** [ansible/ansible#28216]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
[ansible/lib/ansible/parsing/splitter.py][1]

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb 11 2017, 12:22:40) [GCC 6.3.1 20170109]
```
##### OS / ENVIRONMENT
Arch Linux

##### SUMMARY
Consider this snippet: `command: echo '{{ 'a' | regex_replace('"', '\"') }}'`. `ansible` ignores `jinja` tokens while keeping track of currently open quote. That is, it basically treats the second param (`'{{ 'a' | regex_replace('"', '\"') }}'`) as the following list of quoted/nonquoted strings:
```
'{{ '
a
' | regex_replace('
"', '\"') }}'
```
And fails.

##### STEPS TO REPRODUCE
`playbook.yml`:
```yaml
- hosts: all
  tasks:
    - command: echo '{{ 'a' | regex_replace('"', '\"') }}'
```

##### EXPECTED RESULTS
It succeeds.

##### ACTUAL RESULTS
```
ERROR! failed at splitting arguments, either an unbalanced jinja2 block or quotes: echo '{{ 'a' | regex_replace('"', '\"') }}' 

The error appears to have been in '/srv/http/vlad/ansible-configuration/1.yml': line 3, column 7, but may                      
be elsewhere in the file depending on the exact syntax problem.                                                                

The offending line appears to be:                              

  tasks:                       
    - command: echo '{{ 'a' | regex_replace('"', '\"') }}'     
      ^ here                   
We could be wrong, but this one looks like it might be an issue with                                                           
missing quotes.  Always quote template expression brackets when they                                                           
start a value. For instance:   

    with_items:                
      - {{ foo }}              

Should be written as:          

    with_items:                
      - "{{ foo }}"            
```

##### PS
I believe this much info must be enough. If not, feel free to ask what else you need.

On a side note, I wonder why you have [another splitter][2].

[1]: https://github.com/ansible/ansible/blob/v2.3.2.0-1/lib/ansible/parsing/splitter.py#L199
[2]: https://github.com/ansible/ansible/blob/v2.3.2.0-1/lib/ansible/module_utils/splitter.py#L62-L202

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

FYI, your quotes are broken,  ```'{{ '``` is a string then you have `a` as a variable and no operators in between.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
