### ISSUE TITLE
Documentation on how to enable ANSIBLE_PARAMIKO_HOST_KEY_AUTO_ADD in ansible.cfg is incomplete

### ISSUE THREAD

**Issue by skamithi** [ansible/ansible#28290]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME

Network Troubleshooting Guide

##### ANSIBLE VERSION

devel branch of the document

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY

The [network debugging guide](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/network_debug_troubleshooting.rst#error-connecting-to-host-hostname-returned-an-error-or-bad-address) has incomplete information about how to enable the ANSIBLE_PARAMIKO_HOST_KEY_AUTO_ADD using ``ansible.cfg``.

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A

**Comment by nrwahl2** [comment]
@skamithi : Thanks for reporting this! The code block was there but wasn't displaying due to a syntax error (missing colon). I've submitted PR #28695
