### ISSUE TITLE
CIFS Module Failing on Second Run

### ISSUE THREAD

**Issue by knechtionscoding** [ansible/ansible#28406]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.3.1.0
config file = /etc/ansible/ansible.cfg
configured module search path = Default w/o overrides
python version = 2.7.5 (default, Nov 6 2016, 00:28:07) [ GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### SUMMARY

Using the Mount Module to mount a CIFS share works the first time, if CIFS Share is still mounted when run again the module errors out with a fatal error about a shared connection.
##### STEPS TO REPRODUCE

1. Setup CIFS Share
2. Configure Credentials and path
3. Run the below playbook against a machine.
4. Run the playbook again.

```yaml
- name: Copy and place SMB Credentials
  copy:
    src=cifs.credentials
    dest=/root/cifs.credentials
    owner=root
    group=root
    mode=0644


- name: Add correct directory 
  file:
    path: /data/apps
    state: directory
    mode: 0777

- name: add mount for log files
  mount:
   fstype: cifs
   state: mounted
   path: /data/apps/
   src: //share/apps/
   opts: "credentials=/root/cifs.credentials rw 0 0"
```

##### EXPECTED RESULTS

Cifs share to remain mounted and playbook to continue without issue.

##### ACTUAL RESULTS

Playbook fails with the beneath error code. Seems to be an issue where Ansible is trying to open a second connection?

```
fatal: [root@X.X.X.X]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 10948\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to X.X.X.X closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_zTdeh2/ansible_module_file.py\", line 480, in <module>\r\n    main()\r\n  File \"/tmp/ansible_zTdeh2/ansible_module_file.py\", line 359, in main\r\n    changed = module.set_fs_attributes_if_different(file_args, changed, diff)\r\n  File \"/tmp/ansible_zTdeh2/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1298, in set_fs_attributes_if_different\r\n  File \"/tmp/ansible_zTdeh2/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1123, in set_mode_if_different\r\nOSError: [Errno 13] Permission denied: '/data/apps'\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 0
```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case, your issue seems to be lack of quoting, `0777` is being read as an octal, you want a string: ```mode: "0777"``` to set the permissions you expect.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
