### ISSUE TITLE
Add support for EC2 spot instances

### ISSUE THREAD

**Issue by extesy** [ansible/ansible#2846]
I couldn't find any mentioning of spot instances in [ec2 module documentation](http://ansible.cc/docs/modules.html#ec2). Please add support for them, making sure to consider their specific behavior: depending on the current spot price, they might go down and then back up at any time.

**Comment by extesy** [comment]
Something along the lines of https://github.com/AppScale/appscale/wiki/Using-Spot-Instances-in-EC2

**Comment by mpdehaan** [comment]
Not something on my personal radar, but patches for this would be accepted.

**Comment by extesy** [comment]
So you don't even want to leave this request open for future consideration?

**Comment by mpdehaan** [comment]
Patches will definitely be considered.
