### ISSUE TITLE
Tower inventory variable encrypted strings don't save.

### ISSUE THREAD

**Issue by apenen** [ansible/ansible#28497]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Ansible-Tower 3.1.3

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.2 (Maipo)

##### SUMMARY
Inventory vaulted variables failed to parse.

##### STEPS TO REPRODUCE
'ansible-vault encrypt_string' result pasted on tower inventory variables throw error:

Failed to parse variables. Attempted to parse yaml. Parser did not return an object.

##### EXPECTED RESULTS
Saved variables.

##### ACTUAL RESULTS
Error Failed to parse variables. Attempted to parse yaml. Parser did not return an object.

**Comment by bcoca** [comment]
For Ansible Tower support or questions, please utilize https://access.redhat.com/products/ansible-tower-red-hat

This issue tracker is for the open source Ansible CLI tools project.
