### ISSUE TITLE
file directory check mode shows wrong status if dir exitst

### ISSUE THREAD

**Issue by oheinz** [ansible/ansible#2850]
check mode for  a directory shows "changed" although the directory exists with right permissions/ownership.

directory exits

<code>root@ansible:~/ansible/playbooks# ls -lad /var/www/TEST/cache
**drwxrws--- 2 www-data users 4096 Apr 30 11:57 /var/www/TEST/cache**</code>

non-check shows everything is "ok"

<code>root@ansible:~/ansible/playbooks# ansible-playbook -l localhost -i hosts -v playbooks/dirtest.yml 
PLAY [imp-webserver] *********************************************************\* 
GATHERING FACTS **************************************************************\* 
ok: [localhost]
localhost: importing /root/ansible/playbooks/vars/Debian.yml
TASK: [create test dir] ******************************************************\* 
**ok: [localhost] => (item=TEST) => {"changed": false, "gid": 100, "group": "users", "item": "TEST", "mode": "02770", "owner": "www-data", "path": "/var/www/TEST/cache", "size": 4096, "state": "directory", "uid": 33}**
PLAY RECAP *******************************************************************\* 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   </code>

check-mode shows "changed", were everything should be "ok"

<code>root@ansible:~/ansible/playbooks# ansible-playbook -l localhost -i hosts -C -v playbooks/dirtest.yml 
PLAY [imp-webserver] *********************************************************\* 
GATHERING FACTS **************************************************************\* 
ok: [localhost]
localhost: importing /root/ansible/playbooks/vars/Debian.yml
TASK: [create test dir] ******************************************************\* 
**changed: [localhost] => (item=TEST) => {"changed": true, "gid": 100, "group": "users", "item": "TEST", "mode": "02770", "owner": "www-data", "path": "/var/www/TEST/cache", "size": 4096, "state": "directory", "uid": 33}**
PLAY RECAP *******************************************************************\* 
localhost                  : ok=2    changed=1    unreachable=0    failed=0</code>

**Comment by mpdehaan** [comment]
Can you please paste the task from your playbook?  ("create test dir")

**Comment by mpdehaan** [comment]
Also, what is the output of 'ansible --version' ?

Thanks!

**Comment by oheinz** [comment]
<pre><code>root@ansible:~/ansible/playbooks# cat  playbooks/dirtest.yml 
---
- hosts: imp-webserver
  user: root
  vars_files:
    - "../vars/{{ ansible_os_family }}.yml"
  tasks:
    - include: ../roles/dirtest/tasks/create_testdir.yml</code></pre>

<pre><code>root@ansible:~/ansible/playbooks# cat roles/dirtest/tasks/create_testdir.yml
---
- name: create test dir
  action: file path={{ imp_web_root_dir }}/{{ item }}/cache state=directory owner={{ apache_user }} group=users mode=2770
  with_items: stage</code></pre>

<pre><code>root@ansible:~/ansible/playbooks# ansible --version
ansible 1.2</code></pre>

pulled latest changes today

**Comment by mpdehaan** [comment]
Fixes pushed in 672c106 thank you!
