### ISSUE TITLE
How start about writing a vmware module . 

### ISSUE THREAD

**Issue by Amruthapv** [ansible/ansible#28502]
##### ISSUE TYPE

 - Feature Idea
 

##### COMPONENT NAME
VMware module for mapping the VM created using vmware_guest ,to the volume created on NetApp filer/cluster.

##### ANSIBLE VERSION
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/my_modules/']
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

##### OS / ENVIRONMENT
ubuntu14.04

##### SUMMARY
Trying to write a vmware module of the above description but not sure how to start off with. Is there any sdk for the same?. I have gone through the part of the documentation that tells about how to write a module. Any other detailed suggestions?

**Comment by Akasurde** [comment]
@Amruthapv Thanks for proposing a feature idea for VMware module.

First of all take a look at existing VMware modules [here](https://github.com/ansible/ansible/tree/devel/lib/ansible/modules/cloud/vmware/) how these modules use [Pyvmomi](https://github.com/vmware/pyvmomi/) library to talk to VMware infrastructure. You can follow documentation for developing new module which can be found [here](http://docs.ansible.com/ansible/latest/dev_guide/index.html)

Finally, join #ansible , #ansible-devel and #ansible-vmware on irc.freenode.net where you can find everyone who can help you developing your module.

**Comment by Amruthapv** [comment]
@Akasurde  thanks for the info. Could you please give me the correct link  for the IRC channel. "irc.freenode.net" doesn't seem to work.

**Comment by Akasurde** [comment]
@Amruthapv Try this http://webchat.freenode.net/

**Comment by Amruthapv** [comment]
thank you @Akasurde

**Comment by Amruthapv** [comment]
@Akasurde  could you please me point out to me as to how the pyvmomi library can be used to develop any module. I am quite new to python.

**Comment by Akasurde** [comment]
@Amruthapv Take a look into the Pyvmomi community [examples](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/).

Good way to start with Pyvmomi is [hello_world_vcenter](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/hello_world_vcenter.py).

**Comment by Amruthapv** [comment]
okay thank you . That should help!

**Comment by dav1x** [comment]
@Amruthapv You might also check out - https://github.com/snobear/ezmomi

I used it to learn pyvmomi as well.

**Comment by Akasurde** [comment]
@dagwieers Could you please close this issue as it is more of a user question?
