### ISSUE TITLE
Service module fails to reload cron on Ubuntu 16.04

### ISSUE THREAD

**Issue by vandrijevik** [ansible/ansible#28518]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`service` module

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /Users/vladimir/code/vandrijevik/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### CONFIGURATION
```
$ cat ansible.cfg 
[defaults]
retry_files_enabled = False
vault_password_file = .ansible-vault-password
```

##### OS / ENVIRONMENT
Running Ansible from macOS 10.12.6 (16G29), managing Ubuntu 16.04.3 LTS

##### SUMMARY
Running `ansible all -i production -m service -a 'name=cron state=reloaded' --become` fails, but running `sudo service cron reload` on the managed host works.

##### STEPS TO REPRODUCE
1. Run `ansible all -i production -m service -a 'name=cron state=reloaded' --become`

##### EXPECTED RESULTS
The command completes successfully, reloading the cron service’s configuration.

##### ACTUAL RESULTS
The command fails with the following error:

```
host1 | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Unable to reload service cron: Failed to reload cron.service: Job type reload is not applicable for unit cron.service.\nSee system logs and 'systemctl status cron.service' for details.\n"
}
```

However, running `sudo service cron reload` on the host works as expected.

**Comment by bcoca** [comment]
So the system seems to be running systemd and it is not allowing for cron reloading, yet you are restarting it using upstart/sysv init.   Can you confirm this is the case?

**Comment by sivel** [comment]
Looking at the `service` command on Ubuntu 16.04 shows the following behavior:

```
      reload)
         _canreload="$(systemctl -p CanReload show ${UNIT} 2>/dev/null)"
         if [ "$_canreload" = "CanReload=no" ]; then
            # The reload action falls back to the sysv init script just in case
            # the systemd service file does not (yet) support reload for a
            # specific service.
            run_via_sysvinit
         else
            exec systemctl $sctl_args reload "${UNIT}"
         fi
         ;;
```

Looking at the output of systemctl:

```
$ systemctl -p CanReload show cron.service
CanReload=no
```

That means that it should run the sysvinit script for cron.  Looking at the sysvinit script for cron on ubuntu 16.04 shows:

```
reload|force-reload) log_daemon_msg "Reloading configuration files for periodic command scheduler" "cron"
        # cron reloads automatically
        log_end_msg 0
        ;;
```

So the init script is actually doing nothing for reload, other than printing the log message that states:

```
Reloading configuration files for periodic command scheduler cron
```

As such, there is no reason to run `reload` at all for the `cron` service on Ubuntu 16.04.  The error is correct.  `cron` does not allow `reload`.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by vandrijevik** [comment]
> As such, there is no reason to run reload at all for the cron service on Ubuntu 16.04.

Thanks for tracking that down! I’ll just remove my handler then.

> The error is correct. cron does not allow reload.

This is confusing to me, because I would expect Ansible’s `service` module to behave like the `service` command on the managed OS, and there is a discrepancy in this case (an error vs. a successful run). However, since the problem is solved, perhaps this is a non-issue.

**Comment by bcoca** [comment]
service is a 'general term' for dealing with services, in some cases (like yours) you are actually executing the `systemd` module (as that is the 'detected service manager'), so expecting that it behaves like the `service` tool is incorrect.
