### ISSUE TITLE
test/integration: inventory file contains incorrect value for ansible_host for facthost[0:20]

### ISSUE THREAD

**Issue by nrwahl2** [ansible/ansible#28540]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
test/integration

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel a9458ca609) last updated 2017/08/22 22:14:18 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/ansible/lib/ansible
  executable location = /home/ansible/ansible/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION
/etc/ansible/ansible.cfg (defaults)

##### OS / ENVIRONMENT
N/A

##### SUMMARY
ansible/test/integration/inventory file contains incorrect value for ansible_host for facthost[0:20]. IP is set to 1270.0.0.1 instead of 127.0.0.1.

##### STEPS TO REPRODUCE

```
[ansible@nrwahl1 integration]$ grep facthost inventory
facthost[0:20] ansible_host=1270.0.0.1 ansible_connection=local
```

##### EXPECTED RESULTS
[ansible@nrwahl1 integration]$ grep facthost inventory
facthost[0:20] ansible_host=127.0.0.1 ansible_connection=local

##### ACTUAL RESULTS
```
[ansible@nrwahl1 integration]$ grep facthost inventory
facthost[0:20] ansible_host=1270.0.0.1 ansible_connection=local
```

**Comment by bcoca** [comment]
I'm not sure this is wrong, but we can have that discussion in the PR

it is an incorrect IP, but we might want to actually test for that

**Comment by nrwahl2** [comment]
@bcoca : I agree that testing what would happen for an incorrect IP is a valid scenario, but this affect 20+ tests. The entirety of `test_gathering_facts.yml` uses `facthost[0:20]` to test against.

The integration test for `facthost12` happens to fail consistently on certain OSes in Shippable, breaking my PR #28535. (Interestingly it fails on CentOS 7.3 in Shippable and my test box where it works fine with the devel code is RHEL 7.3, but I digress.) Those failures got me looking at the code that it's actually running to test fact-gathering, and I've seen a couple of oddities like this that I want to address.

Also as I noted in the PR for this issue, everything from `facthost10 to facthost20` was added in 2.4-devel, so not sure how stable the tests are.

```
[nwahl@sdiprovtst002 gathering_facts]$ grep hosts test_gathering_facts.yml
- hosts: facthost7
- hosts: facthost0
- hosts: facthost19
- hosts: facthost13
- hosts: facthost11
- hosts: facthost12
- hosts: facthost1
- hosts: facthost2
- hosts: facthost3
- hosts: facthost4
- hosts: facthost5
- hosts: facthost6
- hosts: facthost7
- hosts: facthost8
- hosts: facthost14
- hosts: facthost15
- hosts: facthost9
- hosts: facthost9
- hosts: facthost9
- hosts: facthost20
```
