### ISSUE TITLE
Documentation for the Windows RoboCopy Module is Incorrectly Formatted

### ISSUE THREAD

**Issue by LukeShortCloud** [ansible/ansible#28571]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
Windows module: win_robocopy
http://docs.ansible.com/ansible/latest/win_robocopy_module.html

##### ANSIBLE VERSION
The latest documentation was last published on August 16th, 2017 (2017-08-16).

##### SUMMARY
At the bottom of the page there is a "Return Values" table. The last row is for "output." There is not a example and, instead, the footer along with notes, status, and support are all placed inside the example field for "output" when it should be outside and below of the table.

I would love to submit a pull request upstream to fix this (and a few other non-related documentation fixes) however I cannot find where I can modify this page in the project.

##### STEPS TO REPRODUCE
View the current page at the bottom: http://docs.ansible.com/ansible/latest/win_robocopy_module.html

##### EXPECTED RESULTS
The "output" return value section should have a real world example of standard output from the RoboCopy Windows command.
Also, the footer of the page should not be in the Return Values table.

##### ACTUAL RESULTS
The "output" section does not have the correct information and the page is incorrectly formatted.

**Comment by jborean93** [comment]
@ekultails thanks for raising this issue, a fix for this was merged just recently https://github.com/ansible/ansible/commit/e6316765461b6b97eb6b4742427b22dab288d800 and the live site will be updated some time in the future with this.

I am going to close the ticket as the fix is already there.
