### ISSUE TITLE
ssh transport doesnt correctly use passwords...

### ISSUE THREAD

**Issue by djzort** [ansible/ansible#2861]
(hostnames removed to protect the innocent)...

n.b. im using ansible 1.1 (from the ppa)

export ANSIBLE_TRANSPORT=ssh
ansible-playbook -vvv -i /etc/ansible/envs/foo /etc/ansible/basic.yml -l bar -k

SSH password: 

PLAY [basic] ********************\* 

GATHERING FACTS ********************\* 
<foo> ESTABLISH CONNECTION FOR USER: root
<foo> EXEC ['sshpass', '-d5', 'ssh', '-tt', '-q', '-o', 'PasswordAuthentication=no', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'ldev4.mob-labs.com', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1367992733.49-235331512308674 && echo $HOME/.ansible/tmp/ansible-1367992733.49-235331512308674'"]
<foo> REMOTE_MODULE setup 
<foo> PUT /tmp/tmp8DMg0n TO /setup

notice how 'PasswordAuthentication=no' is set, making password log in impossible. it also doesnt look like the actual password is being provided to sshpass at all?

paramko works fine

**Comment by mpdehaan** [comment]
Password authentication should only passed when a password is set, but I found a problem in the example configuration file.   Look at your /etc/ansible/ansible.cfg and remove the offending line and you should be good to go.

The code will additionally add the following:

```
   if self.password:
        self.common_args += ["-o", "GSSAPIAuthentication=no",
                             "-o", "PubkeyAuthentication=no"]
    else:
        self.common_args += ["-o", "KbdInteractiveAuthentication=no",
                             "-o", "PasswordAuthentication=no"]
```

This is probably a leftover in the example config from when passwords were not supported, which was a while back.

I'll fix the config file on our end as well.

Thanks!

**Comment by mpdehaan** [comment]
See 8ef18c2f9841375c73352f5abc39d499786dd046

**Comment by djzort** [comment]
thanks for that, i really appreciate the quick turn around.

**Comment by mpdehaan** [comment]
no problem, glad to help!
