### ISSUE TITLE
template should provide a 'follow' parameter

### ISSUE THREAD

**Issue by Jean-Daniel** [ansible/ansible#28655]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

template task

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /Users/jddupas/Projects/python/playbooks/app/ansible.cfg
  configured module search path = ['/Users/jddupas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jddupas/Projects/python/playbooks/env/lib/python3.5/site-packages/ansible
  executable location = /Users/jddupas/Projects/python/playbooks/env/bin/ansible
  python version = 3.5.3 (default, Apr 23 2017, 18:09:27) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Just like `file` and `copy`, `template` should provide a follow argument to let the caller choose what to do with symlink.

I encounter cases where I want to replace a symlink by a plain file, and this is not currently possible using template, as it will unconditionally follow the symlink and update the target file instead or deleting the link and create a new file.

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS

Would like to be able to replace a symlink by a plain templated file. This is possible using copy, but does not fill my need.

##### ACTUAL RESULTS

Have to delete the symlink first (which require additional `state` + `file` tasks)

**Comment by giovannisciortino** [comment]
This pull request(already merged to devel) https://github.com/ansible/ansible/pull/28044  contains:

- Add a follow parameter to template that mirrors the follow parameters
for file and copy.

From an updated version of ansible-doc:
```
$ ./bin/ansible-doc template|grep follow
- follow
        if they exist, should be followed.
```
I think that this issue can be closed

**Comment by bcoca** [comment]
closing as per above
