### ISSUE TITLE
Ansible-playbook not honoring port numbers (or default port)

### ISSUE THREAD

**Issue by evanccnyc** [ansible/ansible#2868]
I am using the latest git pull of 1.2 and see the following behavior (oddly it seems to sometimes work with other playbooks and sometimes not):

If the port is specified as different than 22 either via the hosts file or the remote_port in ansible.cfg it still tries to connect to port 22.

hosts file:

[backend-mongoconf]
10.0.20.91
10.0.21.91
10.0.22.91

part of playbook file:
- name: Backend MongoConf Setup
  hosts: backend-mongoconf
  user: ubuntu

ansible.cfg:

remote_port=2222

Error from ansible-playbook --vvv:

GATHERING FACTS **************************************************************\* 
<10.0.20.91> ESTABLISH CONNECTION FOR USER: ubuntu on PORT 22 TO 10.0.20.91
<10.0.21.91> ESTABLISH CONNECTION FOR USER: ubuntu on PORT 22 TO 10.0.21.91
fatal: [10.0.20.91] => {'msg': 'FAILED: [Errno 111] Connection refused', 'failed': True}
fatal: [10.0.21.91] => {'msg': 'FAILED: [Errno 111] Connection refused', 'failed': True}
<10.0.22.91> ESTABLISH CONNECTION FOR USER: ubuntu on PORT 22 TO 10.0.22.91
fatal: [10.0.22.91] => {'msg': 'FAILED: [Errno 111] Connection refused', 'failed': True}

**Comment by evanccnyc** [comment]
I figured out the problem.

If a host is specified in the hosts file with a port number _before_ the hosts group in question, that port will be used no matter what port is set via ansible.cfg or the hosts file.

For example in a hosts file:

[ssh-fix]
10.0.20.91:22
10.0.21.91:22
10.0.22.91:22

[backend-mongoconf]
10.0.20.91
10.0.21.91
10.0.22.91

will lead to to ansible _always_ using port 22 for backend-mongoconf no mater what is specified in the hosts file or the ansible.cfg

**Comment by mpdehaan** [comment]
Correct, inventory overrides the default.

I am a little confused though because what you are specifying (inventroy) and "the hosts file" are the same thing.

Sounds like there is no problem then?  Let me know if you disagree.

**Comment by evanccnyc** [comment]
Well if its specified under one group as port 22 and another group doesnt have it specified as port 22 but the default it just wont work..

I dont disagree it was just hard to figure out what was going on when connecting to a host under 2 different groups but only one of them had it set to use :22 and the other didnt.
