### ISSUE TITLE
Running AWS command using shell module fails in one hosts saying UNREACHABLE

### ISSUE THREAD

**Issue by sreeprasadn** [ansible/ansible#28703]
##### SUMMARY

Running aws command line utility using shell module. This command works in all the hosts in the same vpc except one (10.0.57.247). all other commands and modules are working fine. All the servers have the same configuration. Only difference is this server is in different availability zone

```
ansible 10.0.57.247  shell -a "/usr/local/bin/aws ec2 describe-instances --region "us-west-2""

10.0.57.247 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Shared connection to 10.0.57.247 closed.\r\n",
    "unreachable": true
}
```

##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME

shell/command module

##### ANSIBLE VERSION

```
[root@ip-10-0-57-139 ssh]# ansible --version
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Sep  1 2016, 22:14:00) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### OS / ENVIRONMENT
```
NAME="Amazon Linux AMI"
VERSION="2017.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.03"
PRETTY_NAME="Amazon Linux AMI 2017.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
Amazon Linux AMI release 2017.03
```

##### STEPS TO REPRODUCE
Ansible controller,servers in one availabilty zone and one server in another availabilty zone. Try running the command on server in other availability zone

```
ansible 10.0.57.247  shell -a "/usr/local/bin/aws ec2 describe-instances --region "us-west-2""
```

##### EXPECTED RESULTS

Executed in another server and output is as below. Truncating the output as result is large

```
[root@ip-10-0-57-139 ssh]# ansible 10.0.57.49 -m  shell -a "/usr/local/bin/aws ec2 describe-instances --region "us-west-2"" | more
10.0.57.49 | SUCCESS | rc=0 >>
{
    "Reservations": [
        {
            "OwnerId": "394196313971",
            "ReservationId": "r-0d08fb1aa5a407c24",
            "Groups": [],
            "Instances": [
                {
                    "Monitoring": {
                        "State": "disabled"
                    },
                    "PublicDnsName": "",
                    "RootDeviceType": "ebs",
                    "State": {
                        "Code": 80,
                        "Name": "stopped"
                    },
                    "EbsOptimized": false,
                    "LaunchTime": "2017-01-03T13:41:34.000Z",
                    "PrivateIpAddress": "172.31.3.170",
                    "ProductCodes": [
                        {
                            "ProductCodeId": "eatuvsbbicw1b4cx89ppozcjt",
                            "ProductCodeType": "marketplace"
                        }
                    ],
<...>
```

##### ACTUAL RESULTS

```
<10.0.57.247> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<10.0.57.247> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<10.0.57.247> SSH: ANSIBLE_PRIVATE_KEY_FILE/private_key_file/ansible_ssh_private_key_file set: (-o)(IdentityFile="/etc/ansible/AWS-IRM.pem")
<10.0.57.247> SSH: ansible_password/ansible_ssh_pass not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<10.0.57.247> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User=ec2-user)
<10.0.57.247> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=30)
<10.0.57.247> SSH: PlayContext set ssh_common_args: ()
<10.0.57.247> SSH: PlayContext set ssh_extra_args: ()
<10.0.57.247> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/root/.ansible/cp/249818cb90)
<10.0.57.247> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/etc/ansible/AWS-IRM.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/249818cb90 -tt 10.0.57.247 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-olbveebvqjlsokgibhjjwyyliietjndp; /usr/bin/python /home/ec2-user/.ansible/tmp/ansible-tmp-1503838299.31-167867308962823/command.py; rm -rf "/home/ec2-user/.ansible/tmp/ansible-tmp-1503838299.31-167867308962823/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<10.0.57.247> (255, '', 'OpenSSH_6.6.1, OpenSSL 1.0.1k-fips 8 Jan 2015\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 28183\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Control master terminated unexpectedly\r\nShared connection to 10.0.57.247 closed.\r\n')
10.0.57.247 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: OpenSSH_6.6.1, OpenSSL 1.0.1k-fips 8 Jan 2015\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 28183\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Control master terminated unexpectedly\r\nShared connection to 10.0.57.247 closed.\r\n",
    "unreachable": true
}
```

**Comment by nrwahl2** [comment]
@sreeprasadn I don't see how this is an issue with the shell or command module. The error says the host is unreachable over SSH. Based on that, the same thing should happen if you run `ansible 10.0.57.247 -a 'hostname'`.

Can you connect to 10.0.57.247 over SSH from this server, OUTSIDE of Ansible? If so, then you need to be looking at your Ansible connection configs for that host. (Try it with `-c paramiko` to rule out issues with control persist or local locks on the socket: ref. #12919 bcoca.) If not, then it's not an Ansible issue at all.

**Comment by sreeprasadn** [comment]
@nrwahl2 The command ansible 10.0.57.247 -a 'hostname' works fine and no issues with it. Only issues is with aws ec2 describe-instances command, but this command works fine if run it locally.
[root@ip-10-0-57-139 ~]# ansible 10.0.57.247 -a 'hostname'
10.0.57.247 | SUCCESS | rc=0 >>
ip-10-0-57-247.us-west-2.compute.internal

[root@ip-10-0-57-139 ~]#

**Comment by nrwahl2** [comment]
Any luck with `-c paramiko`?

-------- Original Message --------

**Comment by sreeprasadn** [comment]
with paramiko I am getting the error. All other commands and module are working except ec2-describe instance

[root@ip-10-0-57-139 tasks]# ansible 10.0.57.247 -c paramiko -m  shell -a "/usr/local/bin/aws ec2 describe-instances --region "us-west-2""
10.0.57.247 | UNREACHABLE! => {
    "changed": false,
    "msg": "Incompatible ssh server (no acceptable macs)",
    "unreachable": true
}

I am able to run version command using the same commnd 

[root@ip-10-0-57-139 tasks]# ansible 10.0.57.247 -m  shell -a "/usr/local/bin/aws --version"
10.0.57.247 | SUCCESS | rc=0 >>
aws-cli/1.11.141 Python/2.7.12 Linux/4.9.27-14.31.amzn1.x86_64 botocore/1.6.8

[root@ip-10-0-57-139 tasks]#

Instance has permission to fetch all these information , if run it locally it works fine

**Comment by nrwahl2** [comment]
Can you update the issue with your OS version?

I'd like for you to try setting `ControlMaster=no` and removing `ControlPath`. This has been a good workaround for some users seeing this issue.

Sources:
https://serverfault.com/questions/705657/issues-with-ssh-and-ansible
https://github.com/ansible/ansible/issues/17935
https://github.com/ansible/ansible/issues/26359

Setting `serial: 1` has helped some users as well -- but I don't **think** that will help you since you're running against a single host.

**Comment by alikins** [comment]
> I'd like for you to try setting ControlMaster=no and removing ControlPath. This has been a good workaround for some users seeing this issue.

That also usually results in better error messages from ssh as well, so double useful (especially when using ssh verbose output like here).

**Comment by alikins** [comment]
(ssh stderr reformatted for easier reading)

```
    "msg": "Failed to connect to the host via ssh:  OpenSSH_6.6.1, OpenSSL 1.0.1k-fips 8 Jan 2015
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 56: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 28183
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Control master terminated unexpectedly
Shared connection to 10.0.57.247 closed.
```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
