### ISSUE TITLE
Passwordstore Lookup - New 'errors=ignore' not working

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible/ansible#28702]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
passwordstore lookup

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /home/me/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The passwordstore lookup doesn't seem to be working with the Jinja2 default() filter. 
##### STEPS TO REPRODUCE

I have defined code as below:

```yaml
- name: Root - Set root password
  user:
    name: root
    comment: "root at {{ ansible_nodename }}"
    password: "{{ lookup('passwordstore', 'root-passwords/' + ansible_fqdn)|default(lookup('passwordstore', 'root-passwords/default')) }}"
```
But this doesn't result in Ansible looking up the 'root-passwords/default' entry, as the lookup fails with an error, therefore shorting out the playbook's execution

##### EXPECTED RESULTS

If the host does not have a specific password configured, configure the password defined in the default() filter
##### ACTUAL RESULTS

This error (as verbose as it gets):

```
$ ansible-playbook rootpassword.yml 

PLAY [all] ***********************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************
ok: [somehost.example.com]

TASK [common : Root - Set root password] *****************************************************************************
fatal: [somehost.example.com]: FAILED! => {"failed": true, "msg": "An unhandled exception occurred while running the lookup plugin 'passwordstore'. Error was a <class 'ansible.errors.AnsibleError'>, original message: passname: root-passwords/somehost.example.com not found, use create=True"}

PLAY RECAP ***********************************************************************************************************
somehost.example.com : ok=1    changed=0    unreachable=0    failed=1
```

#### WORKAROUND
There seems to be an undocumented workaround, by defining the code as follows:
```yaml
- name: Root - Set root password
  user:
    name: root
    comment: "root at {{ ansible_nodename }}"
    password: "{{ lookup('passwordstore', 'root-passwords/' + ansible_fqdn + ' create=true userpass=!') }}"
```

But this will create new files for all hosts (which is just messy) and can only contain a password hash (if desired)

**Comment by nrwahl2** [comment]
@Thulium-Drake Try it as:
```
- name: Root - Set root password
  user:
    name: root
    comment: "root at {{ ansible_nodename }}"
    password: "{{ lookup('passwordstore', 'root-passwords/' + ansible_fqdn)|default(lookup('passwordstore', 'root-passwords/default'), true) }}"
```

http://nikhilism.com/post/2016/understanding-ansible-jinja2-default-filter/

**Comment by Thulium-Drake** [comment]
@nrwahl2 I have, but alas, it didn't work.

I've also checked the code of this plugin, but from what I can see it errors out when the requested password doesn't exist

```python
def check_pass(self):
        try:
            self.passoutput = check_output2(["pass", self.passname]).splitlines()
            self.password = self.passoutput[0]
            self.passdict = {}
            for line in self.passoutput[1:]:
                if ":" in line:
                    name, value = line.split(':', 1)
                    self.passdict[name.strip()] = value.strip()
        except (subprocess.CalledProcessError) as e:
            if e.returncode == 1 and 'not in the password store' in e.output:
                # if pass returns 1 and return string contains 'is not in the password store.'
                # We need to determine if this is valid or Error.
                if not self.paramvals['create']:
                    raise AnsibleError('passname: {} not found, use create=True'.format(self.passname))
                else:
                    return False
            else:
                raise AnsibleError(e)
        return True
```

So instead of returning Undefined or False, it raises the error stating that the create flag should be passed.

**Comment by bcoca** [comment]
@Thulium-Drake `|default` is not meant to swallow errors, only undefined values, this is NOT meant to work this way.

**Comment by Thulium-Drake** [comment]
Agreed, and changing that will lead to undesired behavior all over the place.

I think what we need is the snippet of code I quoted above to return False or Undefined as the output of the lookup.

**Comment by nrwahl2** [comment]
I'm tentatively in agreement. Is there a valid reason why it should fatally error out? There are a lot of design decisions that don't make sense at first glance but were made for a reason.

**Comment by Thulium-Drake** [comment]
I can't say for sure, but I also can't think of any reason it should.

I'm asking Ansible to look for something, if it can't find it, then there's the default filter to look for a backup value.

Come to think of it, maybe the author thought that if the lookup is empty, it could cause (security) problems. In cases where the default filter is not used, this could allow for user accounts (or wherever a secret is required) with no password.

On the other hand, it's basically a MollyGuard, especially because I haven't encountered other lookup plugins that have similar behaviour.

**Comment by bcoca** [comment]
it is not only lookup that does so, many end in 'error' for missing resources or bad options, we can add a 'ok_if_missing=false|true' option to this lookup to make the behaviour optional

**Comment by Thulium-Drake** [comment]
As long as it's in the documentation, I'm good with any solution :-)

But your option sounds good

**Comment by nrwahl2** [comment]
@Thulium-Drake : Submitted PR #28908

**Comment by Thulium-Drake** [comment]
Cool, thanks! I'll be looking forward to that being merged :-)

**Comment by nrwahl2** [comment]
:) If you need it now, just copy the new file to your libs haha.

**Comment by Thulium-Drake** [comment]
Of course xD thanks for reminding me :-)

I've also tested it, works like a charm! Although I had to comment out the following line to make it work in 2.3:

`from ansible.utils.encrypt import random_password`

But that will probably be fixed when 2.4 is released.

Thanks again!

**Comment by bcoca** [comment]
so this did not make it in by the freeze date for 2.4, so it will probably go into 2.5

**Comment by dgm** [comment]
This also affects the credstash lookup ; the ok_if_missing option on set_fact works in the 2.5-stable branch at this time.   I do still need to add a default value if it is missing.

**Comment by bcoca** [comment]
so i created an alternative 'generic' solution for all lookups #35932

**Comment by dgm** [comment]
correction, it did not work yet.    Really hard to make my script idempotent.

**Comment by sivel** [comment]
With https://github.com/ansible/ansible/pull/35932 being merged, this is now possible using `errors='ignore'`:

```
    password: "{{ lookup('passwordstore', 'root-passwords/' + ansible_fqdn, errors='ignore')|default(lookup('passwordstore', 'root-passwords/default')) }}"
```

This functionality will be included in the 2.6 release.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by Thulium-Drake** [comment]
Hi Sivel,

Sorry for the late reply! I've been testing this, but on my system (Debian 9.4) it doesn't seem to work.

```
ansible 2.6.1
  config file = /home/user/git/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]

```

I've made the following playbook to test:
```
---
- hosts: some.host
  vars:
     passwordhash: "{{ lookup('passwordstore', 'root-passwords/' + ansible_fqdn, errors='warn')|default(lookup('passwordstore', 'root-passwords/default', errors='warn')) }}"
  tasks:
   - debug:
      msg: "hostname: {{ ansible_fqdn }}, hash : {{ passwordhash }}"
```

When running this, the password hash is empty, but the lookup DOES check if the file is there. See below for output when I renamed the 'default' fallback file:

```
PLAY [some.host] ************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************
ok: [some.host]

TASK [debug] *********************************************************************************************************
 [WARNING]: An unhandled exception occurred while running the lookup plugin 'passwordstore'. Error was a <class
'ansible.errors.AnsibleError'>, original message: passname: root-passwords/some.host not found, use
create=True

 [WARNING]: An unhandled exception occurred while running the lookup plugin 'passwordstore'. Error was a <class
'ansible.errors.AnsibleError'>, original message: passname: root-passwords/default not found, use create=True

ok: [some.host] => {
    "msg": "hostname: some.host, hash : "
}

PLAY RECAP ***********************************************************************************************************
some.host : ok=2    changed=0    unreachable=0    failed=0   
```

When running it with the fallback file, the second warning goes away, but the passwordhash still is not retrieved:

```
PLAY [some.host] ************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************
ok: [some.host]

TASK [debug] *********************************************************************************************************
 [WARNING]: An unhandled exception occurred while running the lookup plugin 'passwordstore'. Error was a <class
'ansible.errors.AnsibleError'>, original message: passname: root-passwords/some.host not found, use
create=True

ok: [some.host] => {
    "msg": "hostname: some.host, hash : "
}

PLAY RECAP ***********************************************************************************************************
some.host : ok=2    changed=0    unreachable=0    failed=0   

```

It does work when I make sure that the first lookup succeeds (I could paste another recap here, but you'll get the picture :-) )

Is there anything I missed?

Thanks in advance!

**Comment by Thulium-Drake** [comment]
@sivel: Hi Sivel, 

Did you catch my last update? :-) Either I'm missing something, or it's broken with the new implementation. I don't seem to be able to get it to actually retrieve something.
