### ISSUE TITLE
Issue in trying ou to create a facts module - enos_facts.py

### ISSUE THREAD

**Issue by amuraleedhar** [ansible/ansible#28719]
[enos.txt](https://github.com/ansible/ansible/files/1256540/enos.txt)
[enos_facts.txt](https://github.com/ansible/ansible/files/1256539/enos_facts.txt)

My issue is not related to any bug with Ansible. 
I am trying to create a facts module in line with ios and dellos. 
I need help to figure out why I am not able to run the module where it is failing at connection.py 
I am not able to figure out to set the socket information for my module

sf = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
sf.connect(module._socket_path) 

 _socket_path is coming as none. How to set this, what is the right approach to do this?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/modules/network/enos/enos_facts.py
lib/ansible/module_util/enos/enos.py

##### ANSIBLE VERSION
root@Ansible01:/home/test/ansible/sheru# ansible --version
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.4.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

##### CONFIGURATION
None

##### OS / ENVIRONMENT
root@Ansible01:/home/test/ansible/sheru# uname -a
Linux Ansible01 3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linu

##### SUMMARY
When executing the playbook to gather facts. I am stuck on the an issue in connection.py that module is not set with _socket_path

##### STEPS TO REPRODUCE
1. Created enos_facts.py as attached above (Rename txt to py)
2. Created enos.py as attached above (Rename txt to py)
3. Created a enos.yaml which calls a role enos_facts
4. Made tasks/main.yml and vars/main.yml as pasted below
5. Try to execute using command ansible-playbook -vvvv enos.yaml 

tasks/main.yml
---
- name: Test Sys Info
  test_facts: provider={{ cli }}
  with_items: "{{test_showsysinfo_data}}"

vars/main.yml
---
cli:
  host: "{{ inventory_hostname }}"
  port: 0
  username: admin
  password: admin
  transport: cli
  auth_pass:

test_showsysinfo_data:
  - {enablePassword: "anil"}

##### EXPECTED RESULTS
The only command I employed in my facts module is to show version. 

##### ACTUAL RESULTS
When I run the playbook with command 
 ansible-playbook -vvvv enos.yaml
Its failing at connection.py stating that the line
sf.connect(module._socket_path) is None/Null
I am not setting the _socket_path in the module. How to set this value?

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_8NwVQP/ansible_module_test_facts.py", line 156, in <module>
    main()
  File "/tmp/ansible_8NwVQP/ansible_module_test_facts.py", line 141, in main
    inst.populate()
  File "/tmp/ansible_8NwVQP/ansible_module_test_facts.py", line 36, in populate
    super(Default, self).populate()
  File "/tmp/ansible_8NwVQP/ansible_module_test_facts.py", line 26, in populate
    self.responses = run_commands(self.module, self.COMMANDS, check_rc=False)
  File "/home/test/ansible/sheru/library/enos.py", line 54, in run_commands
    rc, out, err = exec_command(module, cmd)
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.4.0-py2.7.egg/ansible/module_utils/connection.py", line 67, in exec_command
    sf.connect(module._socket_path)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
TypeError: argument must be string or read-only character buffer, not None

failed: [10.241.105.24] (item={u'enablePassword': u'anil'}) => {
    "changed": false,
    "failed": true,
    "item": {
        "enablePassword": "admin"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_8NwVQP/ansible_module_test_facts.py\", line 156, in <module>\n    main()\n  File \"/tmp/ansible_8NwVQP/ansible_module_test_facts.py\", line 141, in main\n    inst.populate()\n  File \"/tmp/ansible_8NwVQP/ansible_module_test_facts.py\", line 36, in populate\n    super(Default, self).populate()\n  File \"/tmp/ansible_8NwVQP/ansible_module_test_facts.py\", line 26, in populate\n    self.responses = run_commands(self.module, self.COMMANDS, check_rc=False)\n  File \"/home/test/ansible/sheru/library/enos.py\", line 54, in run_commands\n    rc, out, err = exec_command(module, cmd)\n  File \"/usr/local/lib/python2.7/dist-packages/ansible-2.4.0-py2.7.egg/ansible/module_utils/connection.py\", line 67, in exec_command\n    sf.connect(module._socket_path)\n  File \"/usr/lib/python2.7/socket.py\", line 224, in meth\n    return getattr(self._sock,name)(*args)\nTypeError: argument must be string or read-only character buffer, not None\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}

**Comment by alikins** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

 This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

**Comment by gundalow** [comment]
I believe they've resolved this issue
