### ISSUE TITLE
Scalability / performance issues with host_vars in large inventories

### ISSUE THREAD

**Issue by kinware** [ansible/ansible#28751]
##### ISSUE TYPE

 - Performance/Bug Report
##### COMPONENT NAME

inventory / host_vars

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION

Minimal.

##### OS / ENVIRONMENT

Linux control machine. Managed hosts are Linux and Windows.

##### SUMMARY

Ansible 2.3 _upon startup_ parses host_vars/<inventory_hostname> _for every host defined in the inventory - even if only a single host is being targeted_. This causes huge CPU and memory usage when there are many hosts with a modest amount of variables for each. . Ansible 1.x did not do this - it only parsed variables for the hosts being targeted ("lazy loading").

More details about our use case is described below.

##### STEPS TO REPRODUCE

See attached script (rename to generate_files.py), and more detailed explanation below.
[generate_files.py.txt](https://github.com/ansible/ansible/files/1259769/generate_files.py.txt)

##### EXPECTED RESULTS

Normal startup time, normal CPU usage and normal RAM usage.

```
# Running with ansible 1.x
$ ./generate_files.py 1000 1 && ./run_test.sh
[snip]
real 0.31
user 0.17
sys 0.02
```

##### ACTUAL RESULTS

Startup is slow, takes more CPU and most importanty can eat gigabytes of RAM for larger inventories (thousands of hosts).

```
# Running with ansible 2.3
$ ./generate_files.py 1000 1 && ./run_test.sh
[snip]
real 12.67
user 11.74
sys 0.56

```

##### MORE DETAILS

When migrating from ansible 1.x (earlier releases) to ansible 2.3 we ran into a
show stopping performance problem. Our use case is a fairly large inventory (a
few thousand hosts) where each host has a few hundred variables defined which
are used by the playbooks that operate on the target hosts. During each run of
ansible-playbook only a single host is being targeted. Playbook can run for up
to a couple of hours.

The problem for us is that ansible 2.3 upon startup parses
host_vars/<inventory_hostname> _for every host defined in the inventory_ -
even if only a single host is being targeted. Ansible 1.x did not do this, it only
parsed variables for the hosts being targeted ("lazy loading").

This behaviour causes the ansible/python process to spend tens of seconds with
high CPU load and RAM usage parsing YAML files. RAM usage in ansible 1.x is
roughly 100MB. With ansible 2.3 this can grow to gigabytes for larger
inventories. When running maybe a hundred parallell instances of ansible (which
our use case requires), things quite fast start falling apart since the control
machine does not have hundreds of gigs of RAM.

I've attached a test script that demonstrates the problem. Run it as

```
  python generate_files.py 1000 1 && ./run_tests.sh
```

This will generate a 1000 host inventory with (roughly) 1*10 kb of variables.
To test the same volume of variable data but distributed among fewer hosts you
could do for example "python generate_files.py 250 4" which would generate 250
hosts with 40 kb of data for each. If you look at memory usage for the ansible
process you can see it grows during startup then stays at roughly the same
level during the actual playbook run.

In our tests, running the above with arguments 1000 1, ansible 1.x takes 
~1s and uses 100mb of RAM. On ansible 2.3 it takes ~10s and uses 400mb of RAM.

A quick test of modifying inventory/__init__.py to remove the calls to
self.get_host_vars(host) in parse_inventory() and set_playbook_basedir() shows
that the performance problem goes away. Naturally nothing works, as variables
are not loaded :)

Any idea of how this can be solved? The change in ansible to load all variables
during inventory load was probably done for a reason, but I am wondering if
there is anything preventing work to re-introduce lazy load of variables (i.e
upon first use) or only load variables for hosts being targeted?

Any guidance would be much appreciated.

**Comment by bcoca** [comment]
In 2.4 we restructured inventory and host_vars/group_vars are back to be 'loaded on demand', please test that this helps with your use case.

**Comment by kinware** [comment]
Will test with 2.4 to-be and report back!

**Comment by kinware** [comment]
Can report that the performance problem is no longer present in latest develop - only the targeted hosts has their host_vars files read. Closing this issue and looking forward to the upcoming 2.4 release (guessing timed with AnsibleFest in September?).

Taking this opportunity to thank you Brian and everyone else working hard to make Ansible even better than it already is! Awesome!
