### ISSUE TITLE
How to execute a cli comand via ansible

### ISSUE THREAD

**Issue by rajnkamr** [ansible/ansible#28761]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.1.0.0
```

##### SUMMARY

I am trying to do some cli based config on a router via ansible,
I can execute command on shell via ansible but is it possible to add any new config via cli command ?
##### STEPS TO REPRODUCE

Execute below command via yml

```yaml
- name: run shell for cli based command
  shell: |
    set timeout 100
    spawn ssh security@{{ cimc_host }}

    expect "security@10.1.18.47's password:"
    send "{{ "xyz" }}"

    config
    oam-enable
    commit
    set timeout 50
    #send "{{ cimc_command }}"

    exit 0

```

##### EXPECTED RESULTS

I  should be able to configure on cli
##### ACTUAL RESULTS

I am not able to configure on cli

```

```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
