### ISSUE TITLE
with_items does not accept variable in {{ }} - syntax error

### ISSUE THREAD

**Issue by nigelm** [ansible/ansible#2876]
If a playbook contains a with_items: item using the 1.2 variable expansion syntax, the ansible parser raises an error on startup:-

```
ERROR: Syntax Error while loading YAML script, playbook.yml
Note: The error may actually appear before this position: line 19, column 20

    - action: debug {{ item.name }} {{ item.value }}
      with_items: {{ complexvar }}
                   ^
```

Sample failing playbook at:-
https://gist.github.com/5548005

Version: 1.2 (8ef18c2f9841375c73352f5abc39d499786dd046)
Have seen this with slightly earlier 1.2 versions.

**Comment by kjkuan** [comment]
This is a YAML thing. You need to quote it. Eg, with_items: "{{ complexvar  }}"  

## 

Jack Kuan

On Thursday, 9 May, 2013 at 11:03 AM, Nigel Metheringham wrote:

> If a playbook contains a with_items: item using the 1.2 variable expansion syntax, the ansible parser raises an error on startup:-
> ERROR: Syntax Error while loading YAML script, playbook.yml Note: The error may actually appear before this position: line 19, column 20 - action: debug {{ item.name (http://item.name) }} {{ item.value }} with_items: {{ complexvar }} ^  
> Sample failing playbook at:-
> https://gist.github.com/5548005  
> Version: 1.2 (8ef18c2 (https://github.com/ansible/ansible/commit/8ef18c2f9841375c73352f5abc39d499786dd046))
> Have seen this with slightly earlier 1.2 versions.  
> 
> —
> Reply to this email directly or view it on GitHub (https://github.com/ansible/ansible/issues/2876).

## 

_This email and any files transmitted with it are confidential and intended 
solely for the recipient(s). If you are not the named addressee you should 
not disseminate, distribute, copy or alter this email. Any views or 
opinions presented in this email are solely those of the author and might 
not represent those of theScore, Inc. or any of its affiliates. Warning: 
Although theScore, Inc. has taken reasonable precautions to ensure no 
viruses are present in this email, the company cannot accept responsibility 
for any loss or damage arising from the use of this email or attachments._

**Comment by mpdehaan** [comment]
Yes, that's true.

As shared in chat,  you can also just do:

with_items: something

in 1.2, no need for the {{ foo }}

**Comment by erickyellott** [comment]
Is this documented somewhere? Took some digging to find this ticket. I've basically been searching for "with_items" in the modules documentation and didn't see mention of it.
