### ISSUE TITLE
Server patterns from CLI not matching fine

### ISSUE THREAD

**Issue by yajo** [ansible/ansible#28819]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

cli/adhoc
cli/playbook

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /***/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jun 26 2017, 10:20:05) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

##### CONFIGURATION

```
[defaults]
; Unless you specify another inventory, use the production one
inventory = production
```

##### OS / ENVIRONMENT

From Fedora 26 to Ubuntu 16.04.

##### SUMMARY

Ad-hoc commands and playbooks don't understand host patterns as the inventory file does.

##### STEPS TO REPRODUCE

Set this into `./production`:

```
[mygroup]
server-[003:012].example.com
```

Now add a `site.yaml` playbook, no matter which one, and run these commands:

```
➤ ansible 'server-*.example.com' --list-hosts
  hosts (20):
    server-003.example.com
    server-004.example.com
    server-005.example.com
    server-006.example.com
    server-007.example.com
    server-008.example.com
    server-009.example.com
    server-010.example.com
    server-011.example.com
    server-012.example.com

➤ ansible 'server-[009:013].example.com' --list-hosts
 [WARNING]: No hosts matched, nothing to do

  hosts (0):
```

Using `ansible-playbook site.yaml -l $PATTERN` yields similar results.

##### EXPECTED RESULTS

`server-[009:013].example.com` should be a valid CLI host pattern.

##### ACTUAL RESULTS

See above.

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Ranges are supported in host definitions, but not in host patterns. http://docs.ansible.com/ansible/latest/intro_patterns.html

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
