### ISSUE TITLE
Allow disable of syslog logging

### ISSUE THREAD

**Issue by mvo5** [ansible/ansible#2884]
Hi,

I ran into the issue that I wanted to transmit a secret (that got inputed via the ansible vars_prompt) via the "copy" module and its "conent=" feature. But I noticed that this conent is fully logged into syslog. So I would like to ask for a way to stop certain commands or parameters from syslog logging. Looking at the source (and https://github.com/ansible/ansible/pull/2198/files)  it seems there is no_log=True internally but its not possible to set this in a playbook. Or am I missing something?

It seems like the most trivial fix (for me anyway) is to use:

<pre>
$ diff --git a/library/files/copy b/library/files/copy
index 837cf1b..b5a1086 100644
--- a/library/files/copy
+++ b/library/files/copy
@@ -93,7 +93,7 @@ def main():
         argument_spec = dict(
             src               = dict(required=False),
             original_basename = dict(required=False), # used to handle 'dest is a directory' via template, a slight hack 
-            content           = dict(required=False),
+            content           = dict(required=False, no_log=True),
             dest              = dict(required=True),
             backup            = dict(default=False, type='bool'),
             force             = dict(default=True, aliases=['thirsty'], type='bool'),
</pre>

But I can see if I can work on a better version if you prefer a more generic solution.

Thanks for considering,
 Michael

**Comment by bcoca** [comment]
We already avoid logging passwords in some cases, should be easy to avoid
logging 'private' variables.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
Yep, there is a parameter in this in the argument spec, I believe it is
"no_log=True"

**Comment by mvo5** [comment]
Thanks a bunch for this quick review and merge!
