### ISSUE TITLE
all.yml overrides specific .yml, but it should be vice versa

### ISSUE THREAD

**Issue by chillum** [ansible/ansible#28884]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

core, I believe

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 19 2017, 12:34:40) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### OS / ENVIRONMENT

macOS 10.12 -> CentOS 7.x

##### STEPS TO REPRODUCE

Try to override a variable that is declared in `group_vars/all.yml` by a server-specific group_vars file.

`group_vars/all.yml`
```yaml
some_option: 1
```

`group_vars/myrole.yml`
```yaml
some_option: 2
```

`inventory`
```
[myrole]
myhostname
```

##### EXPECTED RESULTS

I expect `some_option` to be `2` on that host.

##### ACTUAL RESULTS

It's `1`.

**Comment by sivel** [comment]
I cannot duplicate this issue.

```
.
├── 28884.yml
├── group_vars
│   ├── all.yml
│   └── testgroup.yml
└── hosts
```

28884.yml
```
---
- hosts: all
  gather_facts: false
  tasks:
    - debug: var=test
```

group_vars/all.yml
```
test: 1
```

group_vars/testgroup.yml
```
test: 2
```

hosts:
```
[testgroup]
localhost ansible_connction=local
```

```
$ ansible-playbook -i hosts 28884.yml

PLAY [all] ***********************************************************************************************************************************************************************

TASK [debug] *********************************************************************************************************************************************************************
ok: [localhost] => {
    "test": 2
}

PLAY RECAP ***********************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

I've tested with both v2.3.2 and devel, and cannot duplicate.

It may be useful to show an exact replicator of the problem, either like I did, or in it's own git repo so that it is easier to visualize and test.

needs_info

**Comment by chillum** [comment]
hm, now I cannot as well and it seems like it was my error.
thanks and sorry for disturbing.
