### ISSUE TITLE
DigitalOcean module_utils params bug

### ISSUE THREAD

**Issue by BondAnthony** [ansible/ansible#28923]
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME

module_utils/digital_ocean.py
##### ANSIBLE VERSION

```
ansible 2.4.0 (devel ae6d27fa29) last updated 2017/09/01 08:43:30 (GMT -400)
  config file = /Users/devMac/ansible.cfg
  configured module search path = [u'/Users/devMac/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/devMac/Development/github/ansible/lib/ansible
  executable location = /Users/devMac/Development/github/ansible/bin/ansible
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
```

##### CONFIGURATION

retry_files_enabled = False
##### OS / ENVIRONMENT

osx 10.11.6
##### SUMMARY

When using the digital_ocean_tag module the api_token isn't found. The problem is within the module_utils/digital_ocean.py. The self.module.params isn't searching for a possible env variables or params. 
##### STEPS TO REPRODUCE

Run the follow task.

```yaml
- name: Create Ansible Managed Tag
  digital_ocean_tag:
      api_token: "{{ do_api_key }}"
      name: "{{ do_tag_name }}"
      state: present
```

##### EXPECTED RESULTS

The module_util should continue to the next lookup and set ```self.oauth_token``` correctly.
##### ACTUAL RESULTS

 This module will toss an exception because oauth_token can't be found.

```
The full traceback is:
  File "/var/folders/fy/p77h9wx95p7__x1wdyjlxfxw0000gn/T/ansible_Uygt2t/ansible_modlib.zip/ansible/module_utils/digital_ocean.py", line 97, in get_do_oauth_token
    self.module.params['oauth_token'] or \

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "name": "ansible_mng", 
            "resource_id": null, 
            "resource_type": "droplet", 
            "state": "present"
        }
    }, 
    "msg": "Unable to load api_toke"
}
```

**Comment by s-hertel** [comment]
@BondAnthony In the reproducer you've provided, are you passing a value for do_api_key? Or not providing a value, making it look at environment vars next? I'll test your fix.

**Comment by BondAnthony** [comment]
Yes the do_api_key is being set, I'm doing that from within host_vars. You can supply the key directly in the task to receive the same error. The issue comes about because the digital_ocean_tags module is looking for Api_token. I just realized I copied the wrong task let me edit this issue.

On Sep 1, 2017, at 9:05 AM, Sloane Hertel <notifications@github.com> wrote:

@BondAnthony In the reproducer you've provided, are you passing a value for do_api_key? Or not providing a value, making it look at environment vars next? I'll test your fix.

**Comment by s-hertel** [comment]
@BondAnthony Thanks, I figured it out. I left a review on your PR. I think the environment vars need to use the same strategy. Looks good.

**Comment by BondAnthony** [comment]
resolved_by_pr 28924
