### ISSUE TITLE
Failed to remote ssh connection.

### ISSUE THREAD

**Issue by morenice** [ansible/ansible#28986]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

none

##### ANSIBLE VERSION

```
ansible 2.3.2.0
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The remote root account does not connect when using a program other than shell (/bin/ sh or /bin /bash)

ex) /etc/passwd 
root:x:0:0:root:/root:/opt/vendor/bin/program

##### STEPS TO REPRODUCE

just connection to remote.

```
 ansible -i hosts all -m ping
```

##### EXPECTED RESULTS

Success ssh connection.

##### ACTUAL RESULTS

```
Using module file /usr/local/lib/python3.4/dist-packages/ansible/modules/system/setup.py
<205.134.173.70> ESTABLISH SSH CONNECTION FOR USER: root
<205.134.173.70> SSH: EXEC sshpass -d15 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o User=root -o ConnectTimeout=10 asdf -o ControlPath=/home/dev/ansible/.ansible/cp/d742fc862c X.X.X.X **'/bin/sh -c '"'"'echo ~ && sleep 0'"'"''**
<205.134.173.70> (1, b'', b"/opt/vendor/bin/program
: invalid option -- 'c'\nTry `program --help' for more information.\n")
```

Can I choose not to run IP config after the command? '/bin/sh -c ...'

**Comment by nrwahl2** [comment]
It's unclear what you're trying to do. Are you trying to run a shell command via the ping module? If your goal is to run `/bin/sh -c "echo ~ && sleep 0"` on the target machine, then either of the following should work:

`$ ansible localhost -c ssh -i hosts.ini -m shell -a '/bin/sh -c "echo ~ && sleep 0"'`
`$ ansible localhost -c ssh -i hosts.ini -m shell -a 'echo ~ && sleep 0"`

Example:
```
[reid@laptop ~/git]$ ansible localhost -c ssh -i hosts.ini -m shell -a '/bin/sh -c "echo ~ && sleep 0"'
localhost | SUCCESS | rc=0 >>
/home/reid
```

**Comment by samdoran** [comment]
@morenice It looks like you changed the default shell for the root user to `/opt/vendor/bin/program`. In order for modules assuming a standard shell to work, you may need to change the [executable](http://docs.ansible.com/ansible/latest/intro_configuration.html#executable).

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by nrwahl2** [comment]
Thanks, @samdoran.

**Comment by morenice** [comment]
When I login to remote as root, I get CLI instead of shell.
- Note that there is a command to go to the shell after connecting to the CLI.
- I can't solve it with execute setting.

I'll use the mailling list as you said. 

Thank you for your quick review. : )
