### ISSUE TITLE
Windows activation using Win_command throws error

### ISSUE THREAD

**Issue by sharath-tp** [ansible/ansible#28999]
Not reported

##### ISSUE TYPE
 - **Bug Report**
 

##### COMPONENT NAME
`win_command`
`win_shell`

##### ANSIBLE VERSION
  ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]

```

##### CONFIGURATION
<!---
No change in ansible.cfg
-->

##### OS / ENVIRONMENT
<!---
OS --> Ubuntu 14.04 - ansible
Windows 2012R2 - Target
-->

##### SUMMARY

Win_command throws below error when trying to activate the windows machine with command.
The command works fine executing directly on target machine using cmd prompt & Powershell but not via ansible win_command.

Using Win_Shell, Playbook hangs/paused at the task and does not complete the playbook even after some time however, the command executes and windows will be activated when verified on target machine directly.

##### STEPS TO REPRODUCE
Requires Windows which Product ID -> not activated & activation Product Key to activate running playbook

**Playbook:**
---
- name: Activating Windows
  win_command: "slmgr /ipk <Product key>"

OR
win_shell: "slmgr /ipk <Product key>"

Example:-  ( win_command: "slmgr /ipk XXXXX-XXXXX-XXXXX-XXXXX")

##### EXPECTED RESULTS

changed: [remote host] => {
    "changed": true,
    "cmd": "slmgr /ipk XXXX-XXXX-XXXX-XXXX"
    "delta": "0:00:00.031248",
    "end": "2017-09-04 10:22:31.843023",
    "rc": 0,
    "start": "2017-09-04 10:22:31.811774",
    "stderr": "",
    "stderr_lines": [],
    "stdout": " *****"
    "stdout_lines": [
        ******* ......... update successful.",

or "Command completed successfully"
        ""
    ]
}


##### ACTUAL RESULTS

TASK [win-activation : Activating Windows] *************************************
task path: /opt/ansible/code/roles/win-activation/tasks/Windows1.yml:3
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/windows/win_command.ps1
<Remote Host> ESTABLISH WINRM CONNECTION FOR USER: Admin on PORT 5986 TO Remote Host
EXEC (via pipeline wrapper)
fatal: [Remote Host]: FAILED! => {
    "changed": false,
    "cmd": "slmgr /ipk XXXXX-XXXXX-XXXXX-XXXXX-XXXXX",
    "failed": true,
    "msg": "The system cannot find the file specified",
    "rc": 2
}


```

**Comment by jhawkesworth** [comment]
@sharath-tp win_command is really for running executables, but slmgr is a visual basic script, so that's unlikely to work.
I suggest trying win_shell instead.  You may need to do a chdir as well so that you aren't dependent on slmgr.vbs being on the path.

In addition, slmgr seems to like to create popups, which will stop the script from completing, but I see from here https://serverfault.com/questions/287400/slmgr-vbs-supress-dialog that you can run using cscript to avoid the popup on success.

Try something like this:
```

- name: Activate windows
  win_shell: cscript slmgr.vbs /ipk XXXXX-XXXXX-XXXXX-XXXXX-XXXXX
  args:
    chdir: C:\Windows\System32\

```

I can't test this at the moment, so please advise if the above fixes for you.

needs_info

**Comment by samdoran** [comment]
cc @dagwieers @jborean93

**Comment by sharath-tp** [comment]
@jhawkesworth Many thanks, this worked. Product key successfully installed.

TASK [win-activation : Activating Windows] *****************************************************************************************************************************
task path: /opt/ansible/code/roles/win-activation/tasks/Windows1.yml:8
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/windows/win_command.ps1
<Remote host> ESTABLISH WINRM CONNECTION FOR USER: Admin on PORT 5986 TO Remote host
EXEC (via pipeline wrapper)
changed: [Remote host] => {
    "changed": true,
    "cmd": "cscript slmgr.vbs /ipk XXXXX-XXXXX-*******",
    "delta": "0:00:00.531254",
    "end": "2017-09-06 06:42:16.048333",
    "rc": 0,
    "start": "2017-09-06 06:42:15.517078",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "Microsoft (R) Windows Script Host Version 5.8\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n\r\nInstalled product key XXXXX-XXXXX successfully.\r\n\r\n",
    "stdout_lines": [
        "Microsoft (R) Windows Script Host Version 5.8",
        "Copyright (C) Microsoft Corporation. All rights reserved.",
        "",
        "Installed product key XXXXX-XXXXX successfully.",
        ""
    ]
}

**Comment by dagwieers** [comment]
@jhawkesworth @sharath-tp Is there anything we can improve in the (module) documentation to help users avoid this ?
