### ISSUE TITLE
Add a preserve option to the copy module

### ISSUE THREAD

**Issue by sfromm** [ansible/ansible#290]
This would preserve a copy of the destination file before it is updated with the source file.  This would look like:

```
copy src=sourcefile.txt dest=/etc/foo/bar preserve=/path/to/preserved
```

The preserve argument would be a directory.  The destination file would be copied to that directory and have a timestamp suffix added to the filename.

**Comment by mpdehaan** [comment]
hmm.   I think 'backup_dir' might be clearer. 

If you ran it again, what happens to the older backups though?   Do they go on as .1, .2, .3, forever?  That could be rough.

I think if you want to preserve files you should just use the fetch module as the first step of the playbook maybe.

Would like to keep things simple.

**Comment by sfromm** [comment]
On Tue, 2012-05-01 at 15:44 -0700, Michael DeHaan wrote:

> hmm.   I think 'backup_dir' might be clearer. 

Sure, that works.

> If you ran it again, what happens to the older backups though?   Do they go on as .1, .2, .3, forever?  That could be rough.

No, the suffix would be the timestamp of when the copy action occurs.
That should ensure it is unique.  For example, backing
up /etc/ssh/sshd_config to /var/backup would yield:  

/var/backup/sshd_config.2012-05-01T19:15:01

The above format is ISO 8601. 

> I think if you want to preserve files you should just use the fetch module as the first step of the playbook maybe.

That option works too.  I like the backup option being part of the copy
module so that it happens all in one step.

> Would like to keep things simple.

Sure.  :-)
