### ISSUE TITLE
Unable to `with_items: groups` or `with_items: groups['group1']`

### ISSUE THREAD

**Issue by gw0** [ansible/ansible#2900]
On Ansible development branch the following does not work.

One would expect that `with_items` would iterate over the `groups` variable, but instead you get `with_items expects a list`. As can be seen Jinja2 is able to iterate over such variables.

The same happens if you try to iterate over hosts in a specific group with `with_items: groups['group1']`.

```
- hosts: all
  user: root
  gather_facts: no
  tasks:
    - debug: msg="a {% for g in groups %}{{ g }}, {% endfor %}"
    - debug: msg="b {{ item }}"
      with_items: groups
#    - debug: msg="c {{ item }}"
#      with_items: ${groups}
#    - debug: msg="d {{ item }}"
#      with_items: "{{ groups }}"
```

Results in:

```
PLAY [all] ******************************************************************** 

TASK: [debug msg="a {% for g in groups %}{{g}}, {% endfor %}"] **************** 
ok: [xxx.lan] => {"msg": "a ungrouped, group1, all, group2, "}

TASK: [debug msg="d {{item}}"] ************************************************ 
fatal: [xxx.lan] => with_items expects a list

FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
groups is actually a hash

groups.groupname the list of hosts.

**Comment by mpdehaan** [comment]
The following did work:

```
- name:  moo
  hosts: localhost

  tasks:
    - shell: echo "hey {{ item }}"
      with_items: groups.webservers
```

I'm checking now why with_items: groups['webservers'] did not.

I would have expected it to, but missed that in your earlier report.   However it is true that you cannot "with_items" over a hash.

**Comment by mpdehaan** [comment]
Ok, fix coming soon for the groups['webservers'] form ...

**Comment by mpdehaan** [comment]
Pushed f2a8c0d ... thanks for the report!

**Comment by gw0** [comment]
Thanks for the fix! It works now. :)
