### ISSUE TITLE
python api PlaybookExecutor options'tags has problem

### ISSUE THREAD

**Issue by woshihaoren** [ansible/ansible#29020]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

lib/ansible/playbook/play_context.py
##### ANSIBLE VERSION

```
2.3.0
```

##### SUMMARY

when use python api call PlaybookExecutor. Each call PlayContext will retain the last parameter (like only_tags,skip_tags).
##### STEPS TO REPRODUCE

1.PlayContent class add print("only_tags", self.only_tags, id(self.only_tags))

    def __init__(self, play=None, options=None, passwords=None, connection_lockfd=None):

        super(PlayContext, self).__init__()

        print("only_tags", self.only_tags, id(self.only_tags))

        if passwords is None:
            passwords = {}

        self.password    = passwords.get('conn_pass','')
        self.become_pass = passwords.get('become_pass','')
2.my python code, run in a flask web

        print('tags', tags)
        play = PlayBookRunner(assets, playbook_path=name, tags=tags)
        result = play.run()
3.first url trigger run, tags is 'whoami'
print log

tags ['whoami']
only_tags set() 140108704140648
only_tags {'whoami'} 140108704140648

4.second url trigger run ,tags is 'id'， I just run id ,but whoami and id both run
print log

tags ['id']
only_tags {'whoami'} 140108704140648
only_tags {'whoami', 'id'} 140108704140648
only_tags {'whoami', 'id'} 140108704140648

```yaml
- hosts: 10.255.21.10
  gather_facts: no

  tasks:
  - name: whoami
    shell: whoami
    tags: whoami
  - name: id
    shell: id
    tags: id
```

I think playbook python api run on engineering, PlayContext instance 's property is same memory address,so PlayContext class's  set_options funcation ,use self.only_tags.update() and self.skip_tags.update() to modify data is wrong.

##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment]
dupilcate of #29001

**Comment by woshihaoren** [comment]
@bcoca   this does not affect the Ansible CLI tools, but python api call has problem.

**Comment by zabbixfan** [comment]
@bcoca  i also have this problem ,when i use my api twice by different tags, second tag excutor first tag
pbexe('simple/mail.yml', 'one')
pbexe('simple/mail.yml', 'two')

this my playbook:
---
- hosts: all
  gather_facts: false
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
    - name: first
      shell: date
      tags: one
    - name: second
      shell: whoami
      tags: two

this my api:
import os,time
import sys,json
import random
from collections import namedtuple
from ansible.parsing.dataloader import DataLoader


def pbexe(yaml,tags):
    from ansible.vars import VariableManager
    from ansible.inventory import Inventory
    from ansible.executor.playbook_executor import PlaybookExecutor

    variable_manager = VariableManager()
    loader = DataLoader()
    hostfile = 'simple/hosts'
    inventory = Inventory(loader=loader, variable_manager=variable_manager,host_list=hostfile)
    playbook_path = yaml
    if not os.path.exists(playbook_path):
        print playbook_path
        print '[INFO] The playbook does not exist'
        sys.exit()

    Options = namedtuple('Options', ['listtags', 'listtasks', 'listhosts', 'syntax', 'connection','module_path', 'forks', 'remote_user', 'private_key_file', 'ssh_common_args', 'ssh_extra_args', 'sftp_extra_args', 'scp_extra_args', 'become', 'become_method', 'become_user', 'verbosity', 'check','tags'])
    options = Options(listtags=False, listtasks=False, listhosts=False, syntax=False, connection='ssh', module_path=None, forks=100, remote_user='root', private_key_file=None, ssh_common_args=None, ssh_extra_args=None, sftp_extra_args=None, scp_extra_args=None, become=True, become_method=None, become_user='root', verbosity=None, check=False,tags=[tags])
    variable_manager.extra_vars = {} # This can accomodate various other command line arguments.`
    passwords = {}
    pbex = PlaybookExecutor(playbooks=[playbook_path],  inventory=inventory, variable_manager=variable_manager, loader=loader, options=options, passwords=passwords)
    results = pbex.run()
    return results

**Comment by zabbixfan** [comment]
it's my output
PLAY [all] *********************************************************************

TASK [first] *******************************************************************
changed: [192.168.4.119]

PLAY RECAP *********************************************************************
192.168.4.119              : ok=1    changed=1    unreachable=0    failed=0   


PLAY [all] *********************************************************************

TASK [first] *******************************************************************
changed: [192.168.4.119]

TASK [second] ******************************************************************
changed: [192.168.4.119]

PLAY RECAP *********************************************************************
192.168.4.119              : ok=2    changed=2    unreachable=0    failed=0

**Comment by woshihaoren** [comment]
@zabbixfan  You can use  https://github.com/ansible/ansible/pull/29001 the code temporary fix this problem

**Comment by ghost** [comment]
Hi @woshihaoren @bcoca We met the same issue on ansible API call, and it is proved that this bug does not impact CLI, I see we have the play_context.py update for this issue, I think we need fix it and do a plan when this fix can go to which version?

**Comment by liaozd** [comment]
I have the same issue, please approve the MR.
