### ISSUE TITLE
Cannot remove a package on RHEL5 with yum-utils installed

### ISSUE THREAD

**Issue by jamescasbon** [ansible/ansible#2904]
See also #2002 

It seems repoquery is broken....

``` bash
$ cat /etc/issue
CentOS release 5.6 (Final)
Kernel \r on an \m

$ sudo yum list installed python
Installed Packages
python.x86_64   2.4.3-44.el5                                             installed
$ repoquery --pkgnarrow=installed python 
$
```

**Comment by mpdehaan** [comment]
A few questions:

Do you really have that in /etc/issue ?

Can you shw the command you are running from your ansible-playbook or /usr/bin/ansible invocation and the output?

What version of ansible are you using?

Can you show me your repoquery version from 'rpm -qa' ?  (yum-utils)

**Comment by jamescasbon** [comment]
Sorry, that was a crap bug report.  

Using ansible 1.1 from Ubuntu 12.10.  I was doing 'ansible -s -m yum "name=package state=latest"' or very similar, (now on phone).

Output was 'package is not installed'. I traced the execution to the is_installed function in the yum module. It switches to use repoquery if available.  However repoquery is

**Comment by rubbsdecvik** [comment]
I have access to a RHEL 5.6 (several actually) machine and I'm not able to reproduce this issue.

```
[root@zoltan ~]# cat /etc/issue
Red Hat Enterprise Linux Server release 5.6 (Tikanga)
Kernel \r on an \m

[root@zoltan ~]#yum list installed python
Loaded plugins: downloadonly, security
Excluding Packages in global exclude list
Finished
Installed Packages
python.i386                      2.4.3-43.el5                          installed
[root@zoltan ~]# repoquery --pkgnarrow=installed python
python-0:2.4.3-43.el5.i386
[root@zoltan ~]#
```

**Comment by jamescasbon** [comment]
OK thanks, there must be something wrong with my yum-utils then.

**Comment by jamescasbon** [comment]
Updating to this worked: http://pkgs.org/centos-5-rhel-5/centos-rhel-i386/yum-utils-1.1.16-21.el5.centos.noarch.rpm/download/
