### ISSUE TITLE
Failed to connect to the host via ssh: Connection closed

### ISSUE THREAD

**Issue by darkogav** [ansible/ansible#29067]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- ping

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.4.0-py2.7.egg/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### CONFIGURATION
I clone directly from github

##### OS / ENVIRONMENT
Ansible is installed on CentOS 7.3.1611
The client I am trying to connect to is a Solaris system.

##### SUMMARY
SSH to the host works fine. If I try to use ansible I get the error 

Failed to connect to the host via ssh: Connection closed

The logs on the client indicate its accepting the public key.

Accepted publickey for ####### from ####### port 43870 ssh2

Below is the full verbose output I am getting.

I tried all variations of 

ansible_user=root ansible_ssh_private_key_file= ansible_host= ansible_port=22

To luck. 

If anybody has any tips of suggestions.

ansible 2.4.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.4.0-py2.7.egg/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
No config file found; using defaults
Parsed /srv/ansible/hosts inventory source with ini plugin
META: ran handlers
Using module file /usr/lib/python2.7/site-packages/ansible-2.4.0-py2.7.egg/ansible/modules/system/ping.py
Using module file /usr/lib/python2.7/site-packages/ansible-2.4.0-py2.7.egg/ansible/modules/system/ping.py
<REDACTED> ESTABLISH SSH CONNECTION FOR USER: None
<REDACTED> ESTABLISH SSH CONNECTION FOR USER: None
<REDACTED> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/145912cffb REDACTED '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<REDACTED> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ee88dcfe91 REDACTED '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<REDACTED> (255, '', 'Connection closed by REDACTED17\r\n')
REDACTED | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Connection closed by REDACTED17\r\n",
    "unreachable": true
}
<REDACTED> (255, '', 'Connection closed by REDACTED14\r\n')
REDACTED | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Connection closed by REDACTED14\r\n",
    "unreachable": true
}

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
