### ISSUE TITLE
inconsistent facts format for network interfaces on AIX and Linux

### ISSUE THREAD

**Issue by marvin-sinister** [ansible/ansible#29079]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
facts collection

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/library/']
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### OS / ENVIRONMENT
Running from CentOS 7.3 host
Running on CentOS 7.3 target
Running on AIX 7.1 target

##### SUMMARY
Facts returned from targets differ on different platforms, AIX returns list of dictionaries, while CentOS returns the dictionary.

##### STEPS TO REPRODUCE
just run setup module on CentOS and AIX

```
$ ansible all -m setup
```

##### EXPECTED RESULTS
I would expect to get same format from both targets

##### ACTUAL RESULTS
AIX returns:
```
        "ansible_lo0": {
            "device": "lo0",
            "flags": [
              ... irelevant ...
            ],
            "ipv4": [
                {
                    "address": "127.0.0.1",
                    "broadcast": "127.255.255.255",
                    "netmask": "255.0.0.0",
                    "network": "127.0.0.0"
                }
            ],
```
While CentOS returns:
```
        "ansible_lo": {
            "active": true,
            "device": "lo",
            "features": {
              ... irelevant ...
            },
            "ipv4": {
                "address": "127.0.0.1",
                "broadcast": "host",
                "netmask": "255.0.0.0",
                "network": "127.0.0.0"
            },
```

Note that both targets return same format for ipv6:
AIX:
```
            "ipv6": [
                {
                    "address": "::1%1/0"
                }
            ],
```
CentOS:
```
            "ipv6": [
                {
                    "address": "::1",
                    "prefix": "128",
                    "scope": "host"
                }
            ],
```

**Comment by bcoca** [comment]
this breaks backwards compatibility for those already using the current AIX output

**Comment by marvin-sinister** [comment]
Fixing this would actually break for those using current Linux output, so it's not happening. Will look into coming up with other solution (for refference, the problem is #29209).
