### ISSUE TITLE
SELinux context not set on /root/.ssh/authorized_keys

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#2907]
Using ansible to push out `/root/.ssh/authorized_keys` to a CentOS 6.4 server:

```

---
- hosts: all
  tasks:
    - authorized_key: user=root key='$FILE(/root/.ssh/authorized_keys)'
```

After this, you still cannot login using a private key. But strangely if you start sshd manually in debug mode you can! Turns out this is an SELinux problem:

```
[pid  7352] open("/root/.ssh/authorized_keys", O_RDONLY|O_NONBLOCK) = -1 EACCES
(Permission denied)
```

[Solution](http://www.centos.org/modules/newbb/viewtopic.php?topic_id=32251):

```
/sbin/restorecon -r /root/.ssh
```

In an attempt to make a workaround I tried adding some selinux tasks:

```
    - file: path=/root/.ssh state=directory context=default
    - file: path=/root/.ssh/authorized_keys context=default
```

However, after these the context is not set correct. `ls -Z` still shows `unconfined_u:object_r:admin_home_t:s0` whereas after restorecon it is `unconfined_u:object_r:ssh_home_t:s0`

I'm not sure if the file module with `context=default` is supposed to apply the default targeted policy for that file, which in this case comes from `/etc/selinux/targeted/contexts/files/file_contexts`

```
/root/\.ssh(/.*)?   system_u:object_r:ssh_home_t:s0
```

In any case, it would be nice if:
1. the authorized_key module had a flag to set the SELinux context automatically on the directory and key file; and/or
2. the file module had a way to restore the policy SELinux context on a file

Otherwise, this issue may at least be worth a note in the docs for the authorized_keys module.

**Comment by bcoca** [comment]
which version? this issue should be fixed in current 1.2

On Tue, May 14, 2013 at 6:13 AM, Brian Candler notifications@github.comwrote:

> Using ansible to push out /root/.ssh/authorized_keys to a CentOS 6.4
> server:
> 
> ---
> - hosts: all
>   tasks:
>   - authorized_key: user=root key='$FILE(/root/.ssh/authorized_keys)'
> 
> After this, you still cannot login using a private key. But strangely if
> you start sshd manually in debug mode you can! Turns out this is an SELinux
> problem:
> 
> [pid  7352] open("/root/.ssh/authorized_keys", O_RDONLY|O_NONBLOCK) = -1 EACCES
> (Permission denied)
> 
> Solutionhttp://www.centos.org/modules/newbb/viewtopic.php?topic_id=32251
> :
> 
> /sbin/restorecon -r /root/.ssh
> 
> In an attempt to make a workaround I tried adding some selinux tasks:
> 
> ```
> - file: path=/root/.ssh state=directory context=default
> - file: path=/root/.ssh/authorized_keys context=default
> ```
> 
> However, after these the context is not set correct. ls -Z still shows
> unconfined_u:object_r:admin_home_t:s0 whereas after restorecon it is
> unconfined_u:object_r:ssh_home_t:s0
> 
> I'm not sure if the file module with context=default is supposed to apply
> the default targeted policy for that file, which in this case comes from
> /etc/selinux/targeted/contexts/files/file_contexts
> 
> /root/.ssh(/.*)?   system_u:object_r:ssh_home_t:s0
> 
> In any case, it would be nice if:
> 1. the authorized_key module had a flag to set the SELinux context
>    automatically on the directory and key file; and/or
> 2. the file module had a way to restore the policy SELinux context on
>    a file
> 
> Otherwise, this issue may at least be worth a note in the docs for the
> authorized_keys module.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/2907
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by candlerb** [comment]
It's 1.0, from ubuntu-precise

Ah, I see commit ccca5fc does something in this area.

Not sure why my "file ... context=default" didn't update it though. Looking at `library/files/file` I can see `context:` in the documentation section, but I can't for the life of me work out where this argument is parsed or acted on!

**Comment by mpdehaan** [comment]
closing as report is on an old version.
