### ISSUE TITLE
add regex import for lib/ansible/runner.py

### ISSUE THREAD

**Issue by mrproper** [ansible/ansible#291]
adding the regex library allows us to do more interesting things in the playbooks

as an example:

---
- hosts: all
  vars:
    is_foo: "re.match('(^F)', '$ansible_foobar') != None"

then later
- name: install bar if foo
  action: xxxx
  only_if: '$is_foo'

**Comment by mpdehaan** [comment]
Sounds simple enough, how about a patch and a test?

**Comment by mpdehaan** [comment]
closing, please fix PR, won't need to update the ticket.
