### ISSUE TITLE
Docs say default ansible module is "command", but it's actually "ping"

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#2910]
The [docs say](http://ansible.cc/docs/examples.html#parallelism-and-shell-commands) that for the ansible command:

> Normally commands also take a -m for module name, but the default module name is ‘command’

However, the default ansible module is currently ping, not command.

I don't know whether the docs should be changed to match the current implementation, or vice versa. I personally prefer "command" since I use that one more, but I can see an argument for "ping".

**Comment by srgvg** [comment]
I'm not sure why you think 'ping' is the default?

Default, as used in bin/ansible is ansible.constants DEFAULT_MODULE_NAME

https://github.com/ansible/ansible/blob/devel/bin/ansible#L61
https://github.com/ansible/ansible/blob/devel/lib/ansible/constants.py#L76

and is 'command'.

Did you somehow reconfigure that default in ansible.cfg?

**Comment by lorin** [comment]
Whoops, I had this in my ansible.cfg:

```
# Default module
module_name = ping
```

I was confused because ansible --help said this:

```
 -m MODULE_NAME, --module-name=MODULE_NAME
                        module name to execute (default=ping)
```

**Comment by mpdehaan** [comment]
Right, the default is loaded with the default from your config file, so ...
yep!
