### ISSUE TITLE
Docs: consistency using "yes|no", "True|False" options

### ISSUE THREAD

**Issue by pestrella** [ansible/ansible#2930]
Hello,

There are some inconsistencies with the use of `yes`|`no`, `True`|`False`, `true`|`false` values. For instance, in the [`bzr` module](http://ansible.cc/docs/modules.html#bzr) the property `force` has a default value of `yes` but a choice of `True`|`False`.

**Comment by mpdehaan** [comment]
Yep, both are accepted, but we should probably use yes|no everywhere to keep it simple.

**Comment by mpdehaan** [comment]
Updated lots of things just now, thanks!
