### ISSUE TITLE
Issue with location of "ip" binary

### ISSUE THREAD

**Issue by techyjoel** [ansible/ansible#2933]
OpenWRT hosts don't have the ip binary at /sbin/ip, rather it's at /usr/sbin/ip. The code in library/system/setup uses a fixed value of /sbin/ip, which causes a stack trace when I try to use it. I modified it to use /usr/sbin/ip and that fixed my issue.

I see a merge a while ago that seems like it should have fixed it, but is now gone from the code:
https://github.com/ansible/ansible/commit/2adff56ef56ec5d20ba6e919c900708aa64a61b5

**Comment by bcoca** [comment]
this should use the get_bin_path function available to modules

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
this is now fixed, so closing, thanks
