### ISSUE TITLE
Incorrect value for 'inject' in jinja2 lookup function

### ISSUE THREAD

**Issue by DazWorrall** [ansible/ansible#2936]
Discussion [here](https://groups.google.com/forum/?fromgroups=#!topic/ansible-project/C971CekRRVs):

> The value of inject when you use the lookup function in a jinja template is the builtin [vars function](http://docs.python.org/2/library/functions.html#vars), you can see it passed in [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/template.py#L84).

**Comment by mpdehaan** [comment]
looking into this now...

**Comment by mpdehaan** [comment]
Fix pushed, help testing welcome.

Thanks!

**Comment by DazWorrall** [comment]
Its not working I'm afraid - its no longer a builtin, its just `None`. `kwargs` doesnt contain `vars` at all:

```
/Users/daz/.virtualenvs/48fdcb4d8ac9eecd/lib/python2.7/site-packages/ansible/utils/template.py(84)lookup()
-> instance = utils.plugins.lookup_loader.get(name.lower(), basedir=kwargs.get('basedir',None))
(Pdb) print kwargs
{'basedir': '.'}
```

It might be taking a different code path - if I put a break just inside [my_lookup](https://github.com/ansible/ansible/commit/496f06c3c90cfd89802622c640480328436746c6#L0R405) it doesn't fire.

**Comment by DazWorrall** [comment]
Ah, I think the you also need to set `kwargs['vars'] = vars` in `template_from_string` [here](https://github.com/ansible/ansible/blob/496f06c3c90cfd89802622c640480328436746c6/lib/ansible/utils/template.py#L484), however when I do that, the vars that get passed down is a very small selection: `{'delegate_to': None, 'ignore_errors': False}`
