### ISSUE TITLE
RH/Centos 6.4  python-jinja2 installation

### ISSUE THREAD

**Issue by JamesUoM** [ansible/ansible#2938]
I came across this issues when installing ansible 1.2 from github on RH/Centos 6.4. 

EPEL only has python-jinja2-26 available. When this is installed it isn't automatically picked up by python as it is meant to be a side-by-side install with the previous version (though where that package is I don't know). You need to give python the path to the python-jinja2-26 egg. Some further details/conformation here:

https://bugzilla.redhat.com/show_bug.cgi?id=882016

In ansible just needed to edit: lib/ansible/utils/template.py

**Comment by mpdehaan** [comment]
Seems like this should be corrected in the RPM for RHEL (but not CentOS) instead.

As mentioned on IRC though it seemed strange no one else has run into this until now.   I am wondering what they are doing differently.

**Comment by mpdehaan** [comment]
Talked with @skvidal and he says Jinja2 should come from rhel6-optional, so you need to enable that channel.

This is folded into the base in CentOS so does not occur there.

Hope this helps!

**Comment by skvidal** [comment]
add the rhel-optional channel in rhn/subscription manager and then install
python-jinja2 pkg from there not the one from epel
