### ISSUE TITLE
Regular Expressions

### ISSUE THREAD

**Issue by sakabio** [ansible/ansible#29432]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```
ansible 2.3.2.0
```

##### SUMMARY

I need help with a regular expression to filter out what ever is between brackets an example is below.

 "57671680 bytes total (10711552 bytes free)"
get everything enclosed in ()

thanks

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by Akasurde** [comment]
@sakabio Could you please elaborate in which Ansible Module you are facing this issue ?

**Comment by alikins** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

 This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.
