### ISSUE TITLE
Task include that works in 1.1 can't find task in devel branch

### ISSUE THREAD

**Issue by kjkuan** [ansible/ansible#2946]
<pre>
common.yml
common/
    tasks/
        main.yml
        some_task.yml
</pre>

`common.yml` is a playbook that has a task include that includes `common/tasks/main.yml`, which in turns includes task `common/tasks/some_task.yml`. This setup works in Ansible 1.1, but when switched to the latest Ansible devel branch, it shows an error like: `ERROR: file not found: ..../common/tasks/common/tasks/some_task.yml`.

NOTE: I know in 1.2 there's going to be support for roles, and all these explicit includes won't be necessary. But this is what we have now and we thought it should help us transition to 1.2 but looks like the semantic of where to look for included tasks has changed? Another way to make it work both in 1.1 and 1.2 would be to use absolute pathes.

**Comment by srgvg** [comment]
I noticed this behaviour also; not sure what changed that.

**Comment by mpdehaan** [comment]
Can you please show your playbooks to go along with the dir structure?

**Comment by kjkuan** [comment]
common.yml:

<pre>
---
- hosts: all
  tasks:
    - include: common/tasks/main.yml
</pre>

common/tasks/main.yml:

<pre>
- include: common/tasks/some_task.yml
</pre>

common/tasks/some_task.yml:

<pre>
- name: this is some_task
  action: shell echo do something
</pre>

**Comment by mpdehaan** [comment]
Thanks.

If the basedirs are in fact all relative now, I'd consider that a good
thing.

Will investigate.

**Comment by mpdehaan** [comment]
Ok, I looked into this.

The deal here is that the basedir for the first file is now correctly loaded, so the include needs to either include a relative path to the first file (as you would expect) or an absolute path (which most people won't do, and that's fine).

In other words, yes, the 1.1 stuff doesn't work -- but I tend to think the 1.1 pathing was wrong in this case.

This should only affect folks that have task includes doing task includes so I think this change in behavior is acceptable.
