### ISSUE TITLE
RFE:  in a role, include all variables in the roles/foo/vars/ directory

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#2958]
Some users want to break variables in roles up into multiple files in the roles dir.

Currently only main.yml is included, can we include all of the variables.   Yes, we could, though overriding could become a question.

We should include main.yml first then everything else alphabetically so it is predictable.

**Comment by jarv** [comment]
It might be confusing if we aren't also doing this for handlers/ though I don't a reason why you would need that many handler definitions.

**Comment by mpdehaan** [comment]
While that may be true, both tasks and handlers can leverage includes (and often do), and order matters there much more so.

(Handlers run in the order defined, not the order notified)

**Comment by benosman** [comment]
I'm looking at creating a patch for this, a couple of questions:

Should it require all variable files to have .yml extension, or also allow .yaml and no extension like the current behaviour for the main file?

Is the main file required to load in the other files - i.g if main.yml is missing should it skip checking if other variables files exist, or should it load them anyway?

**Comment by mpdehaan** [comment]
Sorry for delay, did not see the comment earlier

First question: yes

Second question: no

**Comment by reusch** [comment]
Wouldn't it be possible to provide a way to include other files from the main.yml, relative to the roles/x/vars/ directory? (Maybe I am too naive? :smile: )

This way everyone could predict the result.

**Comment by mpdehaan** [comment]
Now that include_vars exists and is often used to conditionally load variables from here, we do not want to implement this now, so I'm closing this ticket.

@reusch - no, but see "include_vars" from the task section if you want to.
