### ISSUE TITLE
fix service module path handling (for Debian/Ubuntu in particular)

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#296]
the code should do this:

try /sbin and /usr/sbin for the service module, then leave room for systemctl (nothing yet) and maybe launchd -- which are not supported but should raise friendly errors.

if os.path.exists(a)
    use a
if os.path.exists(b)
    use b
else
    return error, cannot find service command

(service still works on Linux distros, no need to worry about directly calling the new ctl wrapper yet)

chkconfig also needs this handling

**Comment by cocoy** [comment]
> chkconfig also needs this handling
> hmm..i think update-rc.d is used for Ubuntu, not sure with other OS's.

**Comment by mpdehaan** [comment]
Ubuntu doesn't have chkconfig?   Let me know.

**Comment by cocoy** [comment]
You have to install chkconfig first. By default it's using update-rc.d

**Comment by leucos** [comment]
I'll take care of this if it's ok with you

**Comment by cocoy** [comment]
leucos: it's  ok with me.  :)

**Comment by haarts** [comment]
update-rc.d is the old way of doing it I believe. [Upstart](http://upstart.ubuntu.com/) is the way forward.

**Comment by haarts** [comment]
I read a little more and I believe this to be quite the task. Upstart doesn't come with something as `chkconfig`, instead you're supposed to edit files in `/etc/init/`. So running a command like it's been done: https://github.com/ansible/ansible/blob/devel/library/service#L45 won't work.
Also it appears that not all packages distributed by Ubuntu use Upstart. Some (like Monit) use something else.

**Comment by leucos** [comment]
@cocoy :)
@haarts : indeed. If you want to use upstart, I suppose the only way is to push files in `/etc/init`. There is no way to use something like `chkconfig` since it works with a dependency system. I really don't get the added value of upstart, especially on servers really. Yet another Ubuntu stupid move.

**Comment by mpdehaan** [comment]
haarts, pull request 306 is already linked above your comment and in queue for testing.

**Comment by mpdehaan** [comment]
patch committed, let me know if it doesn't work for you

**Comment by pas256** [comment]
I just tried this with disabling rsync on an Ubuntu 12.04 server and it did not work.

Starting to debug now......

**Comment by mpdehaan** [comment]
thanks.

good to have people using the platform testing this.

**Comment by pas256** [comment]
False alarm... typo on my part:

```
enable=off
```

not

```
enabled=off
```

Thanks for getting this working
