### ISSUE TITLE
allow for nonexistent src when creating symlinks

### ISSUE THREAD

**Issue by ccxcz** [ansible/ansible#2964]
Currently when creating symlink using file command I get:
msg: src file does not exist
There are rare instances where it is desirable to have ability to create such symlinks, so I'd like to see at least a flag to disable this check.

**Comment by bcoca** [comment]
Not all systems allow you to create a dangling symlink, but it should def
be an option.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by srgvg** [comment]
+1 for the option

**Comment by mpdehaan** [comment]
This is a duplicate of another ticket about symlink validation so I am closing this one.

In other words, more people agree :)

**Comment by mmoya** [comment]
FTR this got fixed by PR #3116 (I was unable to find the previous ticket @mpdehaan was referring to).
