### ISSUE TITLE
Setup module doesn't capture several FreeBSD facts

### ISSUE THREAD

**Issue by base10** [ansible/ansible#2968]
It appears that the setup module does not establish several facts for FreeBSD (8.0) hosts. This has an effect on the utility of the group-by module. Missing facts include:
- ansible_distribution
- ansible_distribution_release
- ansible_distribution_version
- ansible_os_family
- ansible_pkg_mgr

Example output from a FreeBSD 8.0 host vs. an Ubuntu 12.04 LTS host:
https://gist.github.com/base10/5623049

(opened by request of svg in #ansible May 21, 2013)

**Comment by mpdehaan** [comment]
Patches would be accepted!
