### ISSUE TITLE
Errors on systems with both Python 2 and 3

### ISSUE THREAD

**Issue by DMBuce** [ansible/ansible#2974]
[PEP 394](http://www.python.org/dev/peps/pep-0394/) states that "`python` _should_ refer to the same target as `python2` but _may_ refer to `python3` on some bleeding edge distributions".

I use a bleeding edge distribution (Arch Linux) with `/usr/bin/python -> python3` and `/usr/bin/python2 -> /usr/bin/python2.7` symlinks. As I was going through ansible's Getting Started guide, I got this error when running `ansible all -m ping`:

```
batou | FAILED >> {
    "failed": true, 
    "msg": "  File \"/home/buce/.ansible/tmp/ansible-1369237309.08-11857157842580/ping\", line 322\n    except OSError, e:\n                  ^\nSyntaxError: invalid syntax\n", 
    "parsed": false
}
```

I did some digging and found that the scripts under both bin/ and library/ in the source tarball point at `/usr/bin/python`. At build time, setup.py automagically converts the shebangs of the bin scripts to point at python2, but leaves the library scripts alone. After briefly looking at the distutils documentation I don't see an easy way to do the same for the scripts under library/. I could have easily overlooked something, though.

As a temporary workaround, I did `sed -i '1 s/python/python2/' library/*` on the source before building ansible to solve the issue, but I'm not sure what the proper fix is. It would be great if ansible's build system could take care of that by itself, so that users of the bleeding edge distributions referenced by PEP 394 could build ansible without hacking the source.

**Comment by bcoca** [comment]
You can use ansible_python_interpreter to set the 'correct' one, as to
which one is correct, I let PEP vs implementtions fight it out.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
Yep, you just have to set the ansible_python_interpreter variable and it will find the right python.

**Comment by DMBuce** [comment]
Thanks for pointing out `ansible_python_interpreter`. I had glossed over that when going through the Getting Started guide. (I wasn't sure what an "inventory" was at the time, and my attempts to set the variable in the hosts file failed because I didn't yet understand the syntax).

Even so, a clean build on a system with python -> python3 correctly changes the shebang to use `python2` for bin scripts to, but not library scripts. This inconsistency "feels" wrong to me, and impedes packagers' ability to configure a sane default for the path to python. I realize it's a small matter and probably not very important to ansible developers, but if I put in the legwork and submitted a pull request to correct the path to Python 2 in the shebang at build time, would the devs consider it? Or are there reasons for ansible_python_interpreter being the only way to specify an alternate python?

**Comment by mpdehaan** [comment]
The shebang is misleading, we use it to tell what language something is in,
but we cannot trust the user environment.

While this feels wrong to you, it's an established thing in Ansible and is
how ansible python interpeter works.

if you correct the shebang line, you _break_ ansible.

**Comment by mpdehaan** [comment]
Assume for instance if you are managing EL6 hosts and Arch python3
/usr/bin/python hosts at the same time.

ansible_python_interpreter says "who cares about the user and their
possibly wrong environment?  I can manage both of these at once!"

**Comment by DMBuce** [comment]
Yes, you're right, in such a situation, I would expect ansible to respect ansible_python_interpreter as it does now.

However, when ansible_python_interpreter is not set, what is the expected behavior? Currently AFAICT, ansible modules (is that the right name for the scripts under ./library/?) use /usr/bin/python, while ansible itself uses whatever distutils configures -- probably /usr/bin/python in most cases, but on systems like Arch where ansible is installed with `python2 setup.py install`, it ends up being /usr/bin/python2.

I would expect ansible modules to use the same interpreter that ansible itself is using, so that admins don't have to worry about ansible_python_interpreter if the OSes in their environment are homogenous.

> The shebang is misleading, we use it to tell what language something is in, but we cannot trust the user environment.

I'm not suggesting that you trust the user environment. I'm suggesting that the interpreter that modules use should be configured at build time in the same way that the interpreter for ansible itself is.

>  if you correct the shebang line, you _break_ ansible.

I'm not experiencing this behavior at all. For me, ansible is broken _unless_ I change the shebang of its modules, or set ansible_python_interpreter.

**Comment by DMBuce** [comment]
> >    The shebang is misleading, we use it to tell what language something is in, but we cannot trust the user environment.
> 
> I'm not suggesting that you trust the user environment. I'm suggesting that the interpreter that modules use should be configured at build time in the same way that the interpreter for ansible itself is.

In case this is unclear; it should be configured at build time _by whoever is installing ansible_, e.g. an admin or packager (not the user), and only if ansible_python_interpreter is not explicity set in the config.

**Comment by bcoca** [comment]
The problem with distutils is that it would move the modules to bin (i
tried this), I temporarily had a hack on make that ran sed against the
library for the local system but it wasn't 'nice' or very portable (worked
for me!).

If you have a better solution I'm all for it.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
Disagree on this, there is the perspective of the ansible control machine,
and then there is the perspective of all of the machines it is is managing.

The OSes need not be even remotely the same.
