### ISSUE TITLE
make sure there is no command timeout

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#298]
SSH timeout ok, SSH timeout applied to command runtime, bad

**Comment by jkleint** [comment]
I can do this; shouldn't be too hard.

I actually like having commands timeout, but I can see that you might not want it the default.  Just to clarify: you want the initial ssh connection to timeout only; not waiting for the sudo prompt and not if a command takes too long?

**Comment by mpdehaan** [comment]
I may have failed to parse that.

I think the sudo prompt, it's ok if that uses the SSH timeout.

If it tries to apply the command timeout to stuff that happens after the sudo prompt (while a module is running) that can be bad, because services may take longer than 30 seconds to restart, other ops can take a lot longer, etc.

Basically long running ops just shouldn't timeout.

**Comment by jkleint** [comment]
Hrrm, sorry, not sure how to attach a PR to an existing issue.  Here you go.

jkleint/ansible@cbbaee8a9fb65140af30e3a42dd4f3c809033615

**Comment by mpdehaan** [comment]
closing
