### ISSUE TITLE
current directory's ansible.cfg doesn't work when using ansible-pull

### ISSUE THREAD

**Issue by xiangchu0** [ansible/ansible#29943]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
2.3.2.0
```

##### CONFIGURATION
```yaml
1. create a ansible.cfg file in current directory

cat ansible.cfg
[defaults]
inventory      = hosts

2. create a hosts file

cat hosts
[local]
127.0.0.1
```

##### OS / ENVIRONMENT
```yaml
N/A
```

##### STEPS TO REPRODUCE

```yaml
ansible-pull -U https://github.com/training-devops/ansible-pull-example
```

##### EXPECTED RESULTS
```yaml
 no [WARNING]: Host file not found: /etc/ansible/hosts
```

##### ACTUAL RESULTS
```yaml
Starting Ansible Pull at 2017-09-12 15:11:15
/usr/local/bin/ansible-pull -U https://github.com/training-devops/ansible-pull-example
localhost | SUCCESS => {
    "after": "70339e8d7f435272e99798de9b004b10ccd7cd10",
    "before": "70339e8d7f435272e99798de9b004b10ccd7cd10",
    "changed": false,
    "remote_url_changed": false
}
 [WARNING]: Host file not found: /etc/ansible/hosts
 [WARNING]: provided hosts list is empty, only localhost is available
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The ansible.cfg for the play should be in the play directory as `ansible-pull` explicitly changes to that directory before running `ansible-playbook`. So the config you created ONLY affects `ansible-pull`, but not the `ansible-playbook` invocation.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by xiangchu0** [comment]
Thank your
