### ISSUE TITLE
authenticated_key action creates .ssh directory owned as root

### ISSUE THREAD

**Issue by bryanlarsen** [ansible/ansible#2997]
If you use the authenticated_key directive on a user without a .ssh directory, it creates a .ssh directory, but doesn't change the owner of the directory to the appropriate user.

**Comment by mpdehaan** [comment]
I assume you mean authorized_key, right?

**Comment by mpdehaan** [comment]
Should have applied a fix for this just now, let me know if you are still seeing it with latest devel branch and I'll reopen.
