### ISSUE TITLE
Document how to turn off old style substitution (config file) 

### ISSUE THREAD

**Issue by kjkuan** [ansible/ansible#3002]
Strings like $var_name and ${var_name} in a template got replaced by ansible vars

This behavior is surprising given that it's advertised to use jinja2 for templates, one would expect that only `{{...}}` or other default jinja2 syntax gets replaced. I think it should either be fixed or documented.

**Comment by mpdehaan** [comment]
The old 1.1 and before syntax still gets replaced unless you turn it off in settings, but turning it off could have other consequences.

We should still mention how to do it.

**Comment by kjkuan** [comment]
Can it be turned off just for file templates?

**Comment by mpdehaan** [comment]
It just has the global shutoff.

I really don't think it has that many other consequences really :)

**Comment by mpdehaan** [comment]
This is shown in the example ansible.cfg that is part of the package.
