### ISSUE TITLE
Role documentation in the role itself

### ISSUE THREAD

**Issue by tonk** [ansible/ansible#3008]
As time is nearing where people will start sharing complete roles (as the Forge....) I think it's a good idea to establish a standard for documenting the role itself.

I propose a file called `Role.info` in the top of the role directory

Content could be:

```
name: NTP
version: 0.0.1
author: Ton Kersten
license: GPL
summary: NTP module for timeserver and clients
description: Setup NTP for the timeserver and for all clients.
                   The timeserver is defined in the vars section and is called 'timeserver'
                   The fqdn is needed.

                   This role works for RedHat and Debian based systems
```

**Comment by mpdehaan** [comment]
Yep, I almost started a thread about that.   

It should be YAML though, to be consistent, and OS support should be machine parseable.

The problem I still have with this idea is usually the content in such systems is untested and very idiomatic or environment centric, hence why we rally around "batteries included" modules and well tested use case examples, but also make a language that is very easy to develop from scratch.

I can see this coming at some point in the future though.

**Comment by tonk** [comment]
Since the Galaxy is growing very fast I would like to re-open this discussion.

**Comment by jctanner** [comment]
@tonk The ansible-project or ansible-devel mailing list are the places to have discussions.
