### ISSUE TITLE
inconsistency in group_variable precedence according to group depth

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#3009]
Original discussion on the list: https://groups.google.com/forum/#!topic/ansible-project/rZssWk_cKuw

One example, though there are other cases, is shown in https://gist.github.com/sergevanginderachter/5605645

It uses a "simple" inventory according to this structure:

```
#        app1 var=app1          app2  var=app2
#       /    \             /     \
#   app1-dev      app1-prod        app2-dev       app2-prod     var=app{1,2}-{dev,prod} (set to respective groupname)
#      /          \         /        \
# app1-dev-node app1-prod-node  app2-dev-node   app2-prod-node      ${group}-node is the single member of $group
#
# each node ${group}-node should get as value for $var -> ${group} 
# being the value of its respective group name ${group}
```

One single variable 'var' is defined on each of the groups. Each node is expected to get the variable of the respective child group it is the sole member of. This is how precedence is documented: "" If a variable is defined in multiple groups and one group is a child of the other, the child group variable will override the variable set in the parent. ""

​O​utput (see gist) shows that ​some​ nodes get the variable from the parent group​, in this case when pointing the inventory to a dir containing the ini file.​

**Comment by srgvg** [comment]
Other corner cases can occur when some groups or nodes, become a member of other groups, outside of this tree. Those extra group's don't need to have variables defined on them, but their mere presence triggers the logic (sometimes) to define other depth values on the original groups.

Defining groups in another order in the ini file can also trigger different results, again because of the different order in which groups get parsed.

Putting an ini file in multiple subdirs, also can trigger different outcomes, as everything gets re-parsed, possibly in another order, for each dir. 

One of the things I tried was adding some debug statements in `inventory/dir.py` and `inventory/group.py`. I also tried to patch them, which at first seemed to solve this, but in the mean time I found out this still leaves corner cases open. See 09edcf1 for details.

**Comment by mpdehaan** [comment]
FWIW, the following does not reproduce this behavior:

[app1:vars]
vartest=app1
[app1:children]
app1-dev
app1-prod
[app1:vars]
vartest=app1
[app2:children]
app2-dev
app2-prod
[app2:vars]
vartest=app2
[app1-dev]
node-app1-dev ansible_ssh_host=127.0.0.1
[app1-dev:vars]
vartest=app1-dev
[app1-prod]
node-app1-prod ansible_ssh_host=127.0.0.1
[app1-prod:vars]
vartest=app1-prod
[app2-dev]
node-app2-dev ansible_ssh_host=127.0.0.1
[app2-dev:vars]
vartest=app2-dev
[app2-prod]
node-app2-prod ansible_ssh_host=127.0.0.1

**Comment by mpdehaan** [comment]
Now checking your original example.

**Comment by mpdehaan** [comment]
Ok, so this only occurs when the inventory source is a directory and occurs even if there is only one thing in that directory.

I was missing that in the original bug report.

Got it.

**Comment by mpdehaan** [comment]
Ok it turned out the directory mode was copying objects while throwing away the depth info.  I've made a fix here, which is not 100% comprehensive, but should fix most things:

15c97dd

If you have multiple inventory files or sources referring to the same groups or hostnames, things may still be a little weird about depth order, so I recommend not doing that :)

**Comment by srgvg** [comment]
the commit is c52abd4
