### ISSUE TITLE
Error with virtualenv and Fish

### ISSUE THREAD

**Issue by pvledoux** [ansible/ansible#3010]
I'm trying to get ansible working with virtualenv in a [fish-shell](https://github.com/fish-shell/fish-shell) but I get the following error:

```
Traceback (most recent call last):
  File "/Users/pvledoux/.virtualenvs/ansible-env/bin/ansible", line 149, in     <module>
    callbacks.display("", log_only=True)
AttributeError: 'module' object has no attribute 'display'
```

Any idea how I can make it works?

**Comment by mpdehaan** [comment]
Looks like you are using a callbacks class that doesn't have a ".display" method.

Did you customize Ansible or perhaps have a mixed install from a recent upgrade?

I suspect this doesn't have anything to do with fish.

**Comment by mpdehaan** [comment]
callbacks.py has a function called display, BTW, so I don't see a problem there.

Let me know if you find further info:

https://github.com/ansible/ansible/blob/devel/lib/ansible/callbacks.py

**Comment by pvledoux** [comment]
Hi, sorry for that, I checkout the 1.1 instead of the master and now it works.
