### ISSUE TITLE
missing system/filesystem declaration in ansible.spec breaks rpm-build

### ISSUE THREAD

**Issue by isavoy** [ansible/ansible#3013]
missing %file declaration causes make rpm to fail.

need something like:

 94 %files
 95 %defattr(-,root,root)
 96 %{python_sitelib}/ansible*
 97 %{_bindir}/ansible*
 98 %dir %{_datadir}/ansible
 99 %{_datadir}/ansible/_/[a-eg-z]_
100 %{_datadir}/ansible/_/f[a-hj-z]_
101 %{_datadir}/ansible/_/file
102 %{_datadir}/ansible/_/filesystem <---- diff
103 %config(noreplace) %{_sysconfdir}/ansible
104 %doc README.md PKG-INFO COPYING
105 %doc %{_mandir}/man1/ansible*
106 %doc %{_mandir}/man3/ansible.[a-eg-z]*
107 %doc %{_mandir}/man3/ansible.f[a-hj-z]*
108 %doc %{_mandir}/man3/ansible.file*
109 %doc examples/playbooks

**Comment by mpdehaan** [comment]
There is a dumb regex in there that ignores things starting with f except
some things.

We need to understand why that's there and remove it.

2013/5/24 doomed9 notifications@github.com

**Comment by mpdehaan** [comment]
Removed!
