### ISSUE TITLE
Yum module waits for lock indefinitely

### ISSUE THREAD

**Issue by bjoernfan** [ansible/ansible#3026]
I'm running ansible against 100+ hosts, this time just doing a basic yum: name=pidgin ensure=latest from a playbook, only running this task using tags.

What happened was it gathered facts for all hosts (that all went fine), and then it proceeded to run the task for all hosts. Everything looked fine, a few changes, a lot of ok's, but when I expected ansible-playbook to return me to the shell, nothing happened. A few minutes went by, I lost patience, copied all the output and compared the fact gathering result with all the task responses. One machine was not in the second list.

I used SSH to get into that last box, ran ps, saw two yum related commands -- one of which were through ansible -- and one from something called pirut.

Ran strace on the yum process invoked through ansible, and sure enough it was waiting for pirut to finish.

I'm managing peoples desktops, who are free to use yum and other software, so I can't just shut that down on their machines.

If this module (or tasks in general) could fail after a timeout, I'd be very happy. It's kind of hard to spot what machine is having trouble if you're managing this many machines.

If only I saw what task/hosts were left/not finished, it would make me very happy. :)

Oh, and thanks for a great piece of software!

Edit: Using Ansible 1.1 on CentOS 6.

**Comment by jpalomaki** [comment]
You can already run tasks asynchronously and specify a max duration:

```
- name: Install pidgin
  yum: name=pidgin state=latest
  async: <max duration of task>
  poll: <poll every seconds>
```

**Comment by mpdehaan** [comment]
Yep, you want async here.   Note that however this can kill something during a package update, so it might be better to just have a step that waits for the lock to go away and if not exits the playbook using the fail module or something similar, rather than risking yum being slain by the async timeout should it start toward the end of the cycle.

(I would not run a seperate yum update manager on servers, obviously)

**Comment by bjoernfan** [comment]
Shouldn't the ansible yum module be able to exit after a certain amount of time if it can't get a lock? So I don't have to worry about killing a install in progress?
