### ISSUE TITLE
Option variable for --diff

### ISSUE THREAD

**Issue by msasso** [ansible/ansible#30270]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
utils/vars.py

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### SUMMARY
It would be useful if Ansible exposed the diff option to its modules.

A possible use case is to produce relevant output from inside the shell module.

Implementation is as easy as adding
```
options_vars['ansible_diff'] = options.diff
```
to load_options_vars() in ansible/utils/vars.py (tested).

##### STEPS TO REPRODUCE
```yaml
- debug:
    var: ansible_diff
```

##### EXPECTED RESULTS

```
{
    "ansible_diff": true
}
```

##### ACTUAL RESULTS
```
{
    "ansible_diff": "VARIABLE IS NOT DEFINED!",
    "changed": false
}
```

**Comment by bcoca** [comment]
It is already exposed to the modules themsleves, `AnsibleModule` has a `diff` property which is true/false reflecting if a diff is wanted or not.

**Comment by msasso** [comment]
That's ok, but I was talking about shell scripts running under the shell module.

Right now, if I didn't miss it, there's no way to, say, be more verbose when the --diff option is on. On the other hand, I can know about --check by starting my scripts with

```yaml
shell: |
  CHECK_MODE={{ansible_check_mode*1}}
```

I hope the issue is clearer now. 
Thank you.

**Comment by bcoca** [comment]
done #30379
