### ISSUE TITLE
SELinux labels

### ISSUE THREAD

**Issue by kwevers** [ansible/ansible#3031]
Ansible doesnt' apply the correct SELinux label when creating/pushing a file form a template.
I'm following the https://github.com/ansible-provisioning/workshop instructions, using the root user, and in the 02-httpd.yml playbook the file /etc/httpd/conf.d/packages.conf is created.
Because it is moved from a dir in /root it gets the admin_home_t type.
If I understand correctly https://github.com/ansible/ansible/pull/2817 should fix this.
I am however using the latest git version:

[root@vm01 ansible]# git pull
Already up-to-date.
[root@vm01 ansible]# git show
commit 5ec35fa38850e6fc2d8b6b70141b4233b5e3036a
Merge: ce142be b432ae5
Author: Michael DeHaan michael.dehaan@gmail.com
Date:   Mon May 27 08:06:27 2013 -0700

```
Merge pull request #3025 from lorin/keystone-docs

Documentation for keystone_user
```

This is the output of the playbook:

TASK: [Configure yum package location] ***************************************\* 
<vm01> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO vm01
<vm01> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1369672985.61-141562976349528 && echo $HOME/.ansible/tmp/ansible-1369672985.61-141562976349528'
<vm01> EXEC /bin/sh -c 'rc=0; [ -r "/etc/httpd/conf.d/packages.conf" ] || rc=2; [ -f "/etc/httpd/conf.d/packages.conf" ] || rc=1; [ -d "/etc/httpd/conf.d/packages.conf" ] && rc=3; (/usr/bin/md5sum /etc/httpd/conf.d/packages.conf 2>/dev/null) || (/sbin/md5sum -q /etc/httpd/conf.d/packages.conf 2>/dev/null) || (/usr/bin/digest -a md5 /etc/httpd/conf.d/packages.conf 2>/dev/null) || (/sbin/md5 -q /etc/httpd/conf.d/packages.conf 2>/dev/null) || (/usr/bin/md5 -n /etc/httpd/conf.d/packages.conf 2>/dev/null) || (/bin/md5 -q /etc/httpd/conf.d/packages.conf 2>/dev/null) || (echo "${rc}  /etc/httpd/conf.d/packages.conf")'
<vm01> PUT /tmp/tmpyI0ahe TO /root/.ansible/tmp/ansible-1369672985.61-141562976349528/file
<vm01> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-1369672985.61-141562976349528/file; rm -rf /root/.ansible/tmp/ansible-1369672985.61-141562976349528/ >/dev/null 2>&1'
ok: [vm01] => {"changed": false, "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/etc/httpd/conf.d/packages.conf", "size": 135, "state": "file", "uid": 0}

TASK: [Start and enable Apache] **********************************************\* 
<vm01> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO vm01
<vm01> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1369672986.35-128312720760334 && echo $HOME/.ansible/tmp/ansible-1369672986.35-128312720760334'
<vm01> REMOTE_MODULE service name=httpd state=started enabled=yes
<vm01> PUT /tmp/tmpE6GqTb TO /root/.ansible/tmp/ansible-1369672986.35-128312720760334/service
<vm01> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-1369672986.35-128312720760334/service; rm -rf /root/.ansible/tmp/ansible-1369672986.35-128312720760334/ >/dev/null 2>&1'
failed: [vm01] => {"failed": true}
msg: httpd: Syntax error on line 221 of /etc/httpd/conf/httpd.conf: Could not open configuration file /etc/httpd/conf.d/packages.conf: Permission denied

FATAL: all hosts have already failed -- aborting

SELinux labels:
[root@vm01 ansible]# ll -Z /etc/httpd/conf.d/
-rw-r--r--. root root unconfined_u:object_r:admin_home_t:s0 packages.conf
-rw-r--r--. root root system_u:object_r:httpd_config_t:s0 README
-rw-r--r--. root root system_u:object_r:httpd_config_t:s0 welcome.conf

When running a restorecon on the file the playbook finishes without a problem:

[root@vm01 ansible]# restorecon -v /etc/httpd/conf.d/packages.conf 
restorecon reset /etc/httpd/conf.d/packages.conf context unconfined_u:object_r:admin_home_t:s0->unconfined_u:object_r:httpd_config_t:s0
[root@vm01 ansible]# ansible-playbook ../workshop/plays/02-httpd.yml

PLAY [Configure the web server] **********************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [vm01]

TASK: [Install Apache] *******************************************************\* 
ok: [vm01]

TASK: [Configure yum package location] ***************************************\* 
ok: [vm01]

TASK: [Start and enable Apache] **********************************************\* 
changed: [vm01]

PLAY RECAP *******************************************************************\* 
vm01                       : ok=4    changed=1    unreachable=0    failed=0   

[root@vm01 ansible]#

**Comment by mpdehaan** [comment]
I suspect you need to install the python selinux modules.

Can you please try the following on the managed host?

$ python
import SELinux

and tell me if that gives you an import error or not?

**Comment by kwevers** [comment]
[root@vm01 ~]# python
Python 2.6.6 (r266:84292, Feb 22 2013, 00:00:18) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import SELinux
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named SELinux

So yes the python-selinux module is indeed missing.
After installing it the playbook works as expected.
I would expect some error about this though?

**Comment by luisperlaz** [comment]
Is this need of python-selinux documented anywhere? I had to came across this issue to know why after using lineinfile the selinux type of one of my files was being changed.

**Comment by mpdehaan** [comment]
Ansible now fails when this is not installed in latest 1.3, which it really should have all along.
