### ISSUE TITLE
access the remote host by a regular user, not root

### ISSUE THREAD

**Issue by pwang99** [ansible/ansible#30360]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /home/pwang/ansible/ansible.cfg
  configured module search path = [u'/usr/share/my_modules/']
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### CONFIGURATION

File -- /etc/ansible/hosts
test1 ansible_ssh_host=xxx.xxx.xxx.xxx ansible_user=xxxx

File -- ansible.cfg
remote_user = xxxx

##### STEPS TO REPRODUCE

[pwang@centos72temp ansible]$ ansible-playbook -k --ask-sudo-pass ntpd.yml -vvv
Using /home/pwang/ansible/ansible.cfg as config file
SSH password:
SUDO password[defaults to SSH password]:

PLAYBOOK: ntpd.yml ******************************************************************************************************************
1 plays in ntpd.yml

PLAY [test1] ************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<xx.xx.xx.xx> ESTABLISH SSH CONNECTION FOR USER: ## **root**

```yaml

```

I specified the user account under ansible.cfg as well as hosts; but ansible still tried to access the remote host as root, not regular user.

##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
