### ISSUE TITLE
Can't connect using ssh

### ISSUE THREAD

**Issue by nlamirault** [ansible/ansible#30418]
##### ISSUE TYPE

 - Bug Report
 

##### COMPONENT NAME
ping

##### ANSIBLE VERSION

```
$ ansible --version
$ ansible 2.3.2.0
  config file = /home/pirate/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]

```

##### SUMMARY

I've got 2 RaspberryPI with same OS (HypriotOS, a Raspbian). 
I can connect on the 2 host from the master (ssh keys are exported using ssh-copy-id) :

```
$ ssh pirate@192.168.1.20

HypriotOS (Debian GNU/Linux 8)

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Sep 15 14:20:55 2017 from wifibridge.home

$ ssh pirate@192.168.1.26

HypriotOS (Debian GNU/Linux 8)

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Sep 15 12:34:04 2017 from wifibridge.home
```

But i can't use ansible ping with this inventory file : 

```
$ cat inventory 
[master]
local           ansible_connection=local

[nodes]
192.168.1.20    ansible_connection=ssh  ansible_user=pirate
192.168.1.26    ansible_connection=ssh  ansible_user=pirate
```

##### STEPS TO REPRODUCE
```
$ ansible -vvvvvvv 192.168.1.20 -m ping -i inventory

$ ansible -vvvvvvv 192.168.1.26 -m ping -i inventory
```

##### EXPECTED RESULTS

SUCCESS for 2 hosts. 

##### ACTUAL RESULTS

Results : https://gist.github.com/nlamirault/8611c31c49f5b71d341371037046ac5c

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
