### ISSUE TITLE
ANSIBLE_CONFIG variable is being ignored

### ISSUE THREAD

**Issue by simbalion** [ansible/ansible#30454]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible --version shows:
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/simba/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.5.0-py2.7.egg/ansible
  executable location = /home/simba/git/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]


```
##### OS / ENVIRONMENT
Debian 9

##### SUMMARY
Ansible appears to be ignoring the $ANSIBLE_CONFIG environment variable. Also I tried symlinking my desired config to ~/.ansible.cfg and that was also ignored.

##### STEPS TO REPRODUCE
Installed using the 'install from source' method, did 'sudo make install' at the end.
Configured ANSIBLE_CONFIG variable in .bashrc

```yaml

```

##### EXPECTED RESULTS
Should load /home/simba/.ansible/ansible.cfg

##### ACTUAL RESULTS
echo $ANSIBLE_CONFIG results in:
```
/home/simba/.ansible/ansible.cfg
```
ansible -vvv 'command' results in:
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/simba/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.5.0-py2.7.egg/ansible
  executable location = /home/simba/git/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
Using /etc/ansible/ansible.cfg as config file
```

**Comment by bcoca** [comment]
Issue was due to env var not being exported.

**Comment by simbalion** [comment]
PEBKAC
