### ISSUE TITLE
hostvars structure differs across operating systems

### ISSUE THREAD

**Issue by gintautassulskus** [ansible/ansible#30476]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

gather_facts, hostvars

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

macOS Sierra (10.12.6)

##### SUMMARY

hostvars data structure differs across operating systems.
The following clause
`hostvars[inventory_hostname]['ansible_eth0'].ipv4`
in CoreOS returns an Object (see expected results) and in macOS - an array of Objects (see actual results).

##### STEPS TO REPRODUCE

```
- hosts: CoreOS
  gather_facts: yes
  pre_tasks:
    - debug:
        var: hostvars[inventory_hostname]['ansible_eth0'].ipv4

- hosts: macOS
  gather_facts: yes
  pre_tasks:
    - debug:
        var: hostvars[inventory_hostname]['ansible_eth0'].ipv4
```

##### EXPECTED RESULTS
CoreOS:

```
        "ansible_eth0": {
            "ipv4": {
                "address": "192.172.0.4",
                "broadcast": "192.172.0.255",
                "netmask": "255.255.255.0",
                "network": "192.172.0.0"
            }
         }
```

##### ACTUAL RESULTS

macOS:
```
        "ansible_eth0": {
            "ipv4": [
                {
                    "address": "192.168.0.15",
                    "broadcast": "192.168.0.255",
                    "netmask": "255.255.255.0",
                    "network": "192.168.0.0"
                }
            ]
        }
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

hostvars was never meant to have a specific structure, much less guarantee a unified one across hosts. It just reflects the 'variables and data' available for a host, so the structure is very dependent on what is present for each host.

In this case you are having an issue with gathered facts, which can be very different by platform even if some of the information is similar. At most this would be an issue with the fact gathering plugin, not with hostvars.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
