### ISSUE TITLE
maybe a bug

### ISSUE THREAD

**Issue by aes256ctr** [ansible/ansible#30503]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```
ansible 2.3.1
tower 3.1.4
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```
i selected 2 hosts in tower web UI and exectue a command,but tower only tell me the results of one host.

I'am sure the command is effective on both hosts.

Only if i set the debug level,I can see the two hosts's results.

**Comment by bcoca** [comment]
for tower support https://access.redhat.com/
