### ISSUE TITLE
Coloring bug in selective callback plugin

### ISSUE THREAD

**Issue by ogenstad** [ansible/ansible#30506]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- plugins/callback/selective

##### ANSIBLE VERSION

```
ansible 2.4.0.0 (stable-2.4 3c805f85bc) last updated 2017/09/18 14:08:17 (GMT +200)
  config file = /Users/patrick/src/napalm-dev/ansible.cfg
  configured module search path = [u'/Users/patrick/src/forks/napalm-ansible/library']
  ansible python module location = /Users/patrick/src/forks/ansible/lib/ansible
  executable location = /Users/patrick/src/forks/ansible/bin/ansible
  python version = 2.7.12 (default, Dec  5 2016, 11:55:02) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION

N/A

##### SUMMARY
A recent commit has broken the coloring in this module. I think it's due to a different colorize function being used. Instead of printing the codes to change the color in the terminal it just prints "yellow" and such. It's due to the change to using `C.COLOR_CHANGED`.

##### EXPECTED RESULTS
Don't know if I can use colors here, but as per below the color for changed is just prefixed before the router name.

##### ACTUAL RESULTS
```
ansible-playbook -i hosts basic-network.yml --limit router1
...

# STATS *******************************************************************************************************************
yellowrouter1    : ok=3	changed=2	failed=0	unreachable=0
(prod)~/
```

**Comment by gundalow** [comment]
resolved_by_pr 30528
