### ISSUE TITLE
Comment quotes in the inventory file

### ISSUE THREAD

**Issue by pol** [ansible/ansible#3051]
If you have the following inventory file:

```
host1 # this is my first comment
host2 # this is my second
host3 # this can't succeed
```

The system will error with a "ValueError: No closing quotation".  By removing the `'` in the third line, the inventory file will load.  It will not fail if you move the comment to its own line.

This does not seem to be working as expected.  This might be a shlex bug.

**Comment by mpdehaan** [comment]
Yep, we need to split the "#" stuff off before the shlex.

Probably not the role of shlex.

**Comment by pol** [comment]
Added a pull request with a patch.

**Comment by mpdehaan** [comment]
fixed per pull request, thanks!
