### ISSUE TITLE
Backwards Incompatible get_vars Change

### ISSUE THREAD

**Issue by naftulikay** [ansible/ansible#30583]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`ansible.vars.VariableManager.get_vars` ([2.3.2.0](https://github.com/ansible/ansible/blob/v2.3.2.0-1/lib/ansible/vars/__init__.py#L203) vs [2.4.0.0](https://github.com/ansible/ansible/blob/v2.4.0.0-1/lib/ansible/vars/manager.py#L200))

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /home/travis/build/ansible/seven/ansible.cfg
  configured module search path = ['/home/travis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/ansible
  executable location = /home/travis/virtualenv/python3.5.3/bin/ansible
  python version = 3.5.3 (default, Jun 26 2017, 08:40:10) [GCC 4.8.4]
```

##### CONFIGURATION

```
[defaults]
callback_whitelist = goss_format
retry_files_enabled = false
roles_path: .galaxy-roles:roles

[ssh_connection]
ssh_args = -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
```

##### OS / ENVIRONMENT

CentOS 7.3.

##### SUMMARY

Due to a refactor in Ansible in 2.4.0.0, [my callback plugin](https://github.com/naftulikay/ansible-role-degoss/blob/master/callback_plugins/goss_format.py#L50) has been broken due to `VariableManager.get_vars` not taking a `loader` parameter anymore.

##### STEPS TO REPRODUCE

Use my `naftulikay.degoss` Galaxy role to test a system. My callback module's method which is triggering this broken behavior looks like this:

```
   def funnel(self, result):
        """Central ingress point for tasks and formatted output."""
        task = result._task
        loader = task._loader if task else None
        host = result._host
        role = task._role
        play = role._play if role else None
        vm = task._variable_manager
        facts = vm.get_vars(loader=loader, task=task, host=host, play=play) if vm else {}

        goss_output = facts.get('goss_output', {})

        if result.is_failed() and 'format_goss_output' in task.tags:
            # if we had a failure and the task is failed with format_goss_output, errors will be formatted
            self.print_goss_output(goss_output, facts.get('goss_output_format'), error=True)

        if not result.is_failed() and task.action == 'goss' and 'format_goss_output' in task.tags and \
                facts.get('degoss_debug', False):
            # if result is successful, this is a goss run, it has been tagged for formatting, and debug mode is enabled,
            # success will be displayed
            self.print_goss_output(goss_output, facts.get('goss_output_format'), error=False)

        if 'format_goss_stacktrace' in task.tags:
            # if the module failed and there's a stacktrace, print it prettily
            self.print_python_stacktrace(goss_output.get('exception', goss_output.get('module_stderr', "")))
```

My module basically dumps the output of the Goss run so that test status can be examined.

##### EXPECTED RESULTS

I expected Ansible to retain a compatible API.

##### ACTUAL RESULTS

Ansible refactored which broke my code.

```
[WARNING]: Failure using method (v2_runner_on_ok) in callback plugin
(<ansible.plugins.callback.goss_format.CallbackModule object at 0x2b2035ef8f98>): get_vars() got an unexpected keyword argument 'loader'
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.
As the first paragraph in the docs states http://docs.ansible.com/ansible/latest/dev_guide/developing_api.html, the API is not meant for direct consumption and it is mostly there to support the CLI tools. 

This was change was done on purpose as well as configuration and inventory APIs were extensively changed.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
