### ISSUE TITLE
Ansible API can not run on  2.4

### ISSUE THREAD

**Issue by makatitime** [ansible/ansible#30598]
##### ISSUE TYPE

 - Documentation Report

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### OS / ENVIRONMENT

CentOS Linux release 7.3.1611 (Core) 
##### SUMMARY

http://docs.ansible.com/ansible/latest/dev_guide/developing_api.html
I use Official Demo Can not run successfully
Please Update New Deomo
##### STEPS TO REPRODUCE

```yaml
http://docs.ansible.com/ansible/latest/dev_guide/developing_api.html
```

##### ACTUAL RESULTS

```

```

**Comment by sivel** [comment]
resolved_by_pr #30640
