### ISSUE TITLE
Setup module cannot find dmidecode binary

### ISSUE THREAD

**Issue by E-M** [ansible/ansible#3061]
Ansible 1.2

Setup module cannot launch dmidecode binary on RHEL5 systems because it cannot find it. There must be provided full path to dmidecode or full path must be found:
- self.facts['bios_date'] = execute('dmidecode -s bios-release-date') or 'NA'
- self.facts['bios_date'] = execute('/usr/sbin/dmidecode -s bios-release-date') or 'NA'

**Comment by mpdehaan** [comment]
Yes we should use the module common find binary code here.   @sfromm had sent in a patch to change this slightly but contained a few other things that we didn't want, so this is a pretty small change to make it look for it in the right place.

Will take care of this soon, thanks for the report!
