### ISSUE TITLE
Cannot set become_flags globally since 2.4

### ISSUE THREAD

**Issue by ppanczyk** [ansible/ansible#30629]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

become

##### ANSIBLE VERSION

Both stable:
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/pipanczy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```
and devel:
```
ansible 2.5.0 (devel d74c871559) last updated 2017/09/20 15:19:48 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/piotrp/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/piotrp/github/fresh/ansible/lib/ansible
  executable location = /home/piotrp/github/fresh/ansible/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=2h
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = ~/.ssh/ansible-ssh-%%h-%%p-%%r
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = memory
DEFAULT_ASK_PASS(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME_FLAGS(/etc/ansible/ansible.cfg) = -H -S -n -i
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 24
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 120
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_REMOTE_TMP(/etc/ansible/ansible.cfg) = /tmp/$USER/ansible/
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 90
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY

Since Ansible 2.4, it is impossible to set become_flags globally, both by ansible.cfg and by environment variable, as described in the [docs](http://docs.ansible.com/ansible/latest/config.html#default-become-flags).
The option sudo_flags still works, but displays a warning that this feature will be removed in version 2.8.

##### STEPS TO REPRODUCE

Set become_flags to non-default value in ansible.cfg or by the environment variable and run anything anywhere with high verbosity (-vvv).

```
$ ANSIBLE_BECOME_FLAGS='-H -S -n -i' ansible -a true localhost -vvv
```

##### EXPECTED RESULTS

In 2.3, the output of the above command used to be:
```
[...]
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S  -i -p "[sudo via ansible, key=...
[...]
```

##### ACTUAL RESULTS

Since 2.4 it is:

```
[...]
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=...
[...]
```

**Comment by bcoca** [comment]
this is caused by the new configuration settings 'always existing' so 'default sudo' flags are overriding become_flags

**Comment by bcoca** [comment]
@ppanczyk  confirm that PR above fixes the issue fro you

**Comment by ppanczyk** [comment]
Yes, it does, thanks for the quick reaction :)

BTW, I believe it's worth to document this option in [Configuration file](http://docs.ansible.com/ansible/latest/intro_configuration.html) section (and maybe to add it to the configuration file itself), because now the documentation is a little bit inconsistent - it mentions the option in the [Configuration](http://docs.ansible.com/ansible/latest/config.html) section, but not in [Configuration file](http://docs.ansible.com/ansible/latest/intro_configuration.html).

**Comment by bcoca** [comment]
@ppanczyk , the first one is the canonical one, it is actually generated from the configuration and not manually maintained like the 2nd. I have an update in the queue to remove the latter, but it has not made it in yet.

**Comment by Vladimir-csp** [comment]
It is still not overrideable in ansible.cfg:
```
$ ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
...

$ cat /etc/ansible/ansible.cfg | grep become_flags
become_flags = -H -S -n -i

$ ansible-config dump | grep -i flags
DEFAULT_BECOME_FLAGS(default) = 
DEFAULT_SUDO_FLAGS(default) = -H -S -n
DEFAULT_SU_FLAGS(default) = 
```

**Comment by nffdiogosilva** [comment]
Hi there.
Is there any hack to solve this? Or has a solution been already found? If so, it was not merge yet, since I still have this problem. Thank you

**Comment by jameswmcnab** [comment]
Having this issue with 2.7; `sudo_flags` in `ansible.cfg` work but will be removed in 2.8, `become_flags` in `ansible.cfg` are ignored.

**Comment by sivel** [comment]
Please note that `become_flags` needs to be specified under the `[privilege_escalation]` section, and not under `[defaults]`.
