### ISSUE TITLE
ansible_pkg_mgr is "unknown" on OpenBSD since 2.4

### ISSUE THREAD

**Issue by sparunakian** [ansible/ansible#30623]
Hi,

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Facts

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /home/stephane/.ansible.cfg
  configured module search path = [u'/home/stephane/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jul 21 2017, 03:24:34) [GCC 7.1.1 20170630]
```

##### CONFIGURATION

```
ANSIBLE_SSH_CONTROL_PATH(/home/stephane/.ansible.cfg) = %(directory)s/%%h-%%r
ANSIBLE_SSH_PIPELINING(/home/stephane/.ansible.cfg) = True
CACHE_PLUGIN(/home/stephane/.ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/stephane/.ansible.cfg) = ~/.cache/ansible/
CACHE_PLUGIN_TIMEOUT(/home/stephane/.ansible.cfg) = 39600
DEFAULT_GATHERING(/home/stephane/.ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/stephane/.ansible.cfg) = [u'/home/stephane/ansible/inventory']
DEFAULT_LOG_PATH(/home/stephane/.ansible.cfg) = /tmp/ansible.log
DEFAULT_ROLES_PATH(/home/stephane/.ansible.cfg) = [u'/home/stephane/ansible/roles']
DEFAULT_SQUASH_ACTIONS(/home/stephane/.ansible.cfg) = ['apk', 'apt', 'dnf', 'homebrew', 'pacman', 'pkgng', 'yum', 'zypper']
DEFAULT_VAULT_PASSWORD_FILE(/home/stephane/.ansible.cfg) = /home/stephane/ansible/scripts/get_vault_password.sh
RETRY_FILES_ENABLED(/home/stephane/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ansible running from ArchLinux, managing an OpenBSD machine.

##### SUMMARY

Since Ansible 2.4, the `ansible_pkg_mgr` fact is set to `unknown`, instead of `openbsd_pkg` (<= Ansible 2.3.2.0). As the `package` module uses this variable to choose the package manager to invoke, it became unusable on OpenBSD.

##### STEPS TO REPRODUCE

Execute the following command with an OpenBSD machine as a target:
```
ansible openbsd_machine -m setup -a "filter=ansible_pkg_mgr"
```

##### EXPECTED RESULTS

```
openbsd_machine | SUCCESS => {
    "ansible_facts": {
        "ansible_pkg_mgr": "openbsd_pkg"
    }, 
    "changed": false
}
```

##### ACTUAL RESULTS

```
openbsd_machine | SUCCESS => {
    "ansible_facts": {
        "ansible_pkg_mgr": "unknown"
    }, 
    "changed": false, 
    "failed": false
}
```
Let me know if I can be of any help concerning this issue.

Regards

**Comment by bcoca** [comment]
cc @alikins

**Comment by alikins** [comment]
@sparunakian What does the 'ansible_system' fact end up being set to?  The pkg_mgr fact collection code has a special case for ansible_system='OpenBSD' to set pkg_mgr='openbsd_pkg'

If you can provide the full output of 'ansible openbsd_machine -m setup.py' (all of the facts without filters) that may be useful.

When you use the 'package' module, how does it fail? If possible, please provide a copy of the output from running with verbosity set to '-vvv' or higher (either 'ansible' or 'ansible-playbook' against a host showing the problem, whichever is easier)

**Comment by alikins** [comment]
My suspicion is this is related to the order the facts are collected in, and that 'ansible_system' may not be known when the pkg_mgr fact is collected. There is currently no explicit partial ordering for the facts collection so the ordering may be random which could cause the 'ansible_system' to be unknown when pkg_mgr is determined. If thats the case, I need to go ahead and implement some ordering to the collectors to generally fix this.

**Comment by bcoca** [comment]
also dependencies, since now you can avoid collecting 'platform' information

**Comment by sparunakian** [comment]
Thank you for the fix, it works fine now on devel! Are your requests in https://github.com/ansible/ansible/issues/30623#issuecomment-330904957 still required? I did not have time to do that before, but I can do it now.
