### ISSUE TITLE
Issue with ansible_host when delegate_to is used

### ISSUE THREAD

**Issue by flo-renaud** [ansible/ansible#30630]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Sep  5 2017, 08:53:59) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]

```

##### OS / ENVIRONMENT
Fedora release 26 (Twenty Six)

##### SUMMARY
The value for ansible_host isn't properly set when delegate_to is used and the inventory defines ansible_host value for the host.

##### STEPS TO REPRODUCE

I am using the following site.yml playbook:
```
---
- hosts: clients
  tasks:
  - name: test
    delegate_to: server.example.com
    debug:
      var: ansible_host
```

With the following inventory file:
```
[clients]
client.example.com

[servers]
server.example.com
```
The output is the following:
```
TASK [test] ********************************************************************
ok: [client.example.com -> server.example.com] => {
    "ansible_host": "server.example.com"
}
```
Now if I modify the inventory and add a ansible_host value to the client machine:
```
[clients]
client.example.com ansible_host=192.168.100.10

[servers]
server.example.com
```
The output changes to:
```
TASK [test] ********************************************************************
ok: [client.example.com -> server.example.com] => {
    "ansible_host": "192.168.100.10"
}
```

We can see that in the first run, ansible_host was pointing to the delegate_to host, and in the 2nd run it is using the value for the inventory host instead. This behavior seems inconsistent.

##### EXPECTED RESULTS
I would expect the output to always show the value ansible_host: server.example.com, as the doc 
http://docs.ansible.com/ansible/latest/playbooks_delegation.html states that "The ansible_host variable (ansible_ssh_host in 1.x or specific to ssh/paramiko plugins) reflects the host a task is delegated to."

**Comment by gaudenz** [comment]
The same issue still exists in 2.4.2.

**Comment by mkrizek** [comment]
@flo-renaud can you provide your real use case? The `debug` module is executed on the controller so that's why the value of `ansible_host` is that of the controller.

**Comment by mkrizek** [comment]
needs_info

**Comment by gaudenz** [comment]
@mkrizek This is not dependent on the usage of the debug module. It can also be reproduced using the following playbook (run with -v to see the command output)
```
- hosts: clients
  tasks:
    - name: test
      delegate_to: server.example.com
      shell: 'echo {{ ansible_host }}'
```

**Comment by myrdd** [comment]
This can be also reproduced using the commands `hostname` or `cat /etc/hostname` (run playbook with `-v`):

```
- hosts: clients
  tasks:
    - name: test
      delegate_to: server.example.com
      command: hostname
```

**Comment by custa** [comment]
same issue in Ansible 2.7.4 .

**Comment by acmnu** [comment]
Supposed it's a good solution to add checks into delegate functions, but maybe it's better to do this during variable parsing.

**Comment by vdloo** [comment]
This appears to be still an issue in 2.9.2. We encountered this upgrading from 1.9.4 to 2.x, on Python 3.7 the earliest version we could run was 2.5 and it was broken there already as well. the ansible output is pretty confusing, it still does the `->` thing making you think some delegation is still going on:

```
changed: [37.72.165.58 -> 83.217.90.222] => {
    "changed": true,
    "cmd": "echo test > /tmp/test",
    "delta": "0:00:00.013490",
    "end": "2019-12-24 13:54:58.768640",
    "invocation": {
```

we used delegate_to to perform an rsync from a second host to the host on which Ansible was running, that caused rsync to silently only run on the destination host and exit 0, syncing no data.

**Comment by linionbb** [comment]
Strange this issue has been here for so long...

Debug works, but delegate refers to whatever is set in "ansible_host" variable.
```yaml
     - debug:
         msg: "{{ delegate_master }}"
       delegate_to: "{{ delegate_master }}"
```

Result:
```http
ok: [host.example.com -> {{ ansible_ssh_host }}] => {
    "msg": "delegatemaster.example.com"
}
```

**Comment by bcoca** [comment]
This fixed using the correct variables for the actual connection, https://github.com/ansible/ansible/pull/69244, still open is the part about what is 'displayed' which is really 'what value is available at task template time' ... which can also vary during loops.
