### ISSUE TITLE
Intermittent SIGHUP when using SSH connection and lengthy task

### ISSUE THREAD

**Issue by ScottSturdivant** [ansible/ansible#3063]
Given this "lengthy" playbook:

```

---
- hosts: foo
  user: root
  tasks:
    - shell: echo {{ item }}
      with_sequence: start=0 end=50
    - service: name=supervisord state=started enabled=yes
```

When I run this with the ssh connection (ansible-playbook -c ssh....), I get a SIGHUP occurring on the target 70% of the time.  This manifests itself in the supervisord log files as such:

```
2013-05-30 09:19:24,046 INFO daemonizing the supervisord process
2013-05-30 09:19:24,052 INFO supervisord started with pid 40365
2013-05-30 09:19:25,068 INFO spawned: 'worker_1' with pid 40368
2013-05-30 09:19:25,078 INFO spawned: 'worker_0' with pid 40369
2013-05-30 09:19:25,090 INFO spawned: 'worker_2' with pid 40370
2013-05-30 09:19:25,099 WARN received SIGHUP indicating restart request
```

Supervisord apparently can't really handle that and the end result is that supervisord isn't actually started at the conclusion of the play.

The length of the play is important, hence the shell task.  If only the single service task is executed, I do not see the problem.

Similarly I have never seen the problem if I do not utilize the -c ssh option.

**Comment by mpdehaan** [comment]
This sounds like it is from your individual service init script or supervisor and not an Ansible thing.

**Comment by ScottSturdivant** [comment]
Absolutely agree that supervisord is broken (https://github.com/Supervisor/supervisor/issues/121) with regards to properly handling a SIGHUP.  The question is, why is ansible even causing a SIGHUP to occur?  If I remove the 'busy wait' part of the play, it works 100% of the time.

**Comment by mpdehaan** [comment]
(A) I'm not sure it is.

(B) What OS is this?

All it should be doing is calling the service status command.

**Comment by ScottSturdivant** [comment]
This is from a Ubuntu 13.04 host to a FreeBSD 9.1 target.

It's absolutely _not_ the ansible service module itself.  If I set ANSIBLE_KEEP_REMOTE_FILES=1 and execute the file directly on the target, the problem never occurs.

After disabling the ControlMaster options for SSH, I have not seen the SIGHUP.  

Reading a bit about ControlMaster [here](http://www.anchor.com.au/blog/2010/02/ssh-controlmaster-the-good-the-bad-the-ugly/), I came across this:

> Because all of your SSH sessions are multiplexed down a single TCP connection initiated by the first SSH
> session, that first session must stay alive until all of the other sessions are complete. This problem will
> manifest itself as an apparent “hang” when you log out of the remote session that is acting as the master — 
> instead of getting your local prompt back, SSH will just sit there. If you Ctrl-C or otherwise kill this session, all 
> of the other sessions you’ve got setup to that server will drop, so don’t do that.

Is it possible that the first SSH connection (gathering facts) is being closed / killed before the final task executes and somehow that's causing the closing of the final (service management) connection?

**Comment by bcoca** [comment]
> Is it possible that the first SSH connection (gathering facts) is being
> closed / killed before the final task executes and somehow that's causing
> the closing of the final (service management) connection?

We would have seen that way sooner, but it possible your control master has
issues.

Openssh deployment schedules vary and I've had hard times making even
minor versions work correctly together (specially across FreeBSD/Linux).
Check versions and check for any bugs on openssh side, they are pretty good
at fixing issues but then distros need to update packages.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno
