### ISSUE TITLE
Inventory binary is executed N+1 times (N == each host defined)

### ISSUE THREAD

**Issue by FearTheBadger** [ansible/ansible#30664]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Ansible

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
``` ansible.cfg
[defaults]
ask_pass = True
remote_user = admin
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Ansible will execute the inventory binary script for every host produced by the binary, plus one.

This becomes a huge problem if you have a large list of hosts that are being generated from a remote source.

##### STEPS TO REPRODUCE

`-rwxr-xr-x    ./inventory`

```python
#!/usr/bin/python

from datetime import datetime

with open("test.txt", "a") as myfile:
  myfile.write(str(datetime.now()) + "\n")

print "{"
print "  \"linuxOS\": {"
print "    \"hosts\": ["
print "      \"192.168.1.10\","
print "      \"192.168.1.11\","
print "      \"192.168.1.12\","
print "      \"192.168.1.13\","
print "      \"192.168.1.14\""
print "    ]"
print "  }"
print "}"
```

`$ ansible all -i inventory -m ping`

This will Ping/Pong the servers and you will generate a file at the Ansible root with the filename of test.txt

##### EXPECTED RESULTS
`$ cat test.txt`
```
2017-09-20 22:38:55.186288
```

##### ACTUAL RESULTS
`$ cat test.txt`
```
2017-09-20 22:38:55.186288
2017-09-20 22:38:55.217923
2017-09-20 22:38:55.243893
2017-09-20 22:38:55.270643
2017-09-20 22:38:55.296092
2017-09-20 22:38:55.321244
```

**Comment by sivel** [comment]
The way dynamic inventory scripts work in ansible, is that if the script does not return a top level key of `_meta`, ansible will call the script for each host using `--host inventory_hostname` where `inventory_hostname` will be the name of each individual host.

Please see http://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html for more information about developing a dynamic inventory source.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by FearTheBadger** [comment]
Thank you for the correction.
I'm sorry to have wasted your time with this non-problem.
