### ISSUE TITLE
ansible_processor_vcpus  is not reported on Darwin

### ISSUE THREAD

**Issue by afrittoli** [ansible/ansible#30688]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible/module_utils/facts/hardware/darwin.py

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = None
  configured module search path = ['/Users/af/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/af/virtualenvs/ansible/lib/python3.6/site-packages/ansible
  executable location = /Users/af/virtualenvs/ansible/bin/ansible
  python version = 3.6.2 (default, Sep 20 2017, 12:41:21) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
macOS Sierra 10.12.6

##### SUMMARY
ansible_processor_vcpus is not reported on darwin. This is because the get_cpu_facts in the darwin modules only reports processor type and count:

It should be possible on Darwin to obtain the number of cores and vcpus (typically cores * 2 to include threads) by reading the following values from sysctl respectively:

https://github.com/ansible/ansible/blob/62f49120cd1c0e7af9d71b8da14b0bc9b21b05ed/lib/ansible/module_utils/facts/hardware/darwin.py#L73

hw.logicalcpu: 4
hw.physicalcpu: 2

On  my laptop:

$ sysctl hw | egrep '(logical|physical)cpu:'
hw.logicalcpu: 4
hw.physicalcpu: 2

##### STEPS TO REPRODUCE
```
$ ansible -m setup all | grep processor
        "ansible_processor": "Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz",
        "ansible_processor_cores": "2",
```

##### EXPECTED RESULTS
```
$ ansible -m setup all | grep processor
        "ansible_processor": "Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz",
        "ansible_processor_cores": "2",
        "ansible_processor_vcpus": "4",
```

##### ACTUAL RESULTS
```
$ ansible -m setup all | grep processor
        "ansible_processor": "Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz",
        "ansible_processor_cores": "2",
```

**Comment by Akasurde** [comment]
@afrittoli Thanks for reporting this issue. Could you please try above patch and let me know if it works for you ?

**Comment by Akasurde** [comment]
resolved_by_pr #30708

**Comment by alikins** [comment]
Was the processor_vcpu working in earlier versions (and if so, which versions). Or is this new?

**Comment by afrittoli** [comment]
Sorry for the late reply and thanks for looking into this. The fix looks good.
