### ISSUE TITLE
vars used in include_role or import_role are evaluated too early

### ISSUE THREAD

**Issue by halberom** [ansible/ansible#30700]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include_role
import_role

##### ANSIBLE VERSION
```
ansible-playbook 2.4.0.0
  config file = 
  configured module search path = [u'/Users/lynchg/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/lynchg/.virtualenvs/a2x/lib/python2.7/site-packages/ansible
  executable location = /Users/lynchg/.virtualenvs/a2x/bin/ansible-playbook
  python version = 2.7.13 (default, Dec 18 2016, 07:03:34) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

##### CONFIGURATION
NA

##### OS / ENVIRONMENT
Mac OSX

##### SUMMARY
When using a variable as the target for an include_role or import_role, it is evaluated at the beginning of an ansible-playbook run, before it may exist.

##### STEPS TO REPRODUCE
https://gist.github.com/halberom/2c9aa046f63b096f78b26401a11e78d4

Create a playbook
```
# play.yml
---
- hosts: localhost
  gather_facts: False
  connection: local
  roles:
    - { role: test1, rolename: test2 }
```
Create a role
```
# roles/test1/tasks/main.yml
- debug: var=rolename

- include_role:
    name: "{{ rolename }}"
```
Create a second role
```
# roles/test2/tasks/main.yml
- debug: msg="in {{ role_path }}"
```

##### EXPECTED RESULTS
In the gist - uncommenting the import_role or include_role statements in the gist should work without bugs.

In the example above - you should get a "in /path/to/role" output from the debug in the `test2` role.

##### ACTUAL RESULTS
No tasks are processed, and an error is output

```
# ERROR! 'rolename' is undefined
```
where `rolename` is the variable being used in the gist.

It works if you move the `rolename: test2` to the vars section of the play.  See also the alternative playbook in the gist.

**Comment by halberom** [comment]
Note this was first reported by stanislava in irc, with a link to https://gist.github.com/XooR/f5f15b0610ba6c15c4820e89a2b92ce0

**Comment by Shaps** [comment]
Some more info for this:
- Works correctly if the included role `test1` doesn't have an `include_role` task
- Works correctly if the `rolename` var is defined in the play `vars:` section

**Comment by alikins** [comment]
Started some intg tests for this at https://github.com/ansible/ansible/compare/devel...alikins:include_role_intg_tests

Do the tests at https://github.com/ansible/ansible/compare/devel...alikins:include_role_intg_tests?expand=1#diff-201e87e7cc1d4faad12a30a3a540c8c9 and https://github.com/ansible/ansible/compare/devel...alikins:include_role_intg_tests?expand=1#diff-9223a0c4b39f8ab67818bac876e944c7 look like a good reproducer?

running the test_incldue_role_no_vars.yml playbook against devel(cc288aba47) I get:

```
+ ansible-playbook -i ../../inventory -vvv test_include_role_no_vars.yml
ansible-playbook 2.5.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible/lib/ansible
  executable location = /root/ansible/bin/ansible-playbook
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
No config file found; using defaults
Parsed /root/ansible/test/integration/inventory inventory source with ini plugin
ERROR! 'rolename' is undefined
```

**Comment by Shaps** [comment]
@alikins Yep that's what I was doing too, it does look good to me!
