### ISSUE TITLE
ERROR! 'import_plays' is not a valid attribute for a Play

### ISSUE THREAD

**Issue by hadrien-toma** [ansible/ansible#30744]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
* `import_plays`

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ash/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT
Ubuntu 16.04, 64 bits.

##### SUMMARY
Trying to import a play throws an unexpected error.

##### STEPS TO REPRODUCE
Run this bash commands to reproduce:
```
cd
mkdir import_plays_error
cd import_plays_error

echo '
---
- hosts: localhost
  roles:
    - {role: "foo", bar: "baz_1"}
- import_plays: ./plays/test.yml
' > index.yml

mkdir roles
ansible-galaxy init --init-path roles/ foo
echo '
---
# tasks file for foo
- name: foo task
  debug: msg={{bar}}
' > roles/foo/tasks/main.yml

mkdir plays
echo '
---
- hosts: localhost
  roles:
    - {role: "foo", bar: "baz_2"}
- import_plays: ./plays/test.yml
' > plays/test.yml

ansible-playbook -vvvv index.yml
```

##### EXPECTED RESULTS
I expected to have the play imported in the parent one.

##### ACTUAL RESULTS
This is the output given from the `ansible-playbook -vvvv index.yml` command:
```
ansible-playbook 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ash/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! 'import_plays' is not a valid attribute for a Play

The error appears to have been in '/home/ash/import_plays_error/index.yml': line 6, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - {role: "foo", bar: "baz_1"}
- import_plays: ./plays/test.yml
  ^ here
```

**Comment by SubOptimal** [comment]
Maybe an error in the documentation.

-- here it's mentioned as `import_playbook`
[https://docs.ansible.com/ansible/latest/playbooks_reuse.html](https://docs.ansible.com/ansible/latest/playbooks_reuse.html#dynamic-vs-static)

-- where as here it's mentioned as `import_plays`
[https://docs.ansible.com/ansible/latest/playbooks_best_practices.html](https://docs.ansible.com/ansible/latest/playbooks_best_practices.html#top-level-playbooks-are-separated-by-role)
https://docs.ansible.com/ansible/latest/import_plays_module.html

If you change your code

    # - import_plays: ./plays/test.yml
    - import_playbook: ./plays/test.yml
it would do what you expect. (btw. you need as well to fix `plays/test.yml` before)

**Comment by hadrien-toma** [comment]
Alright, so I confirm that it seems to be a documentation issue, using `import_playbook` instead of `import_plays` works for me (of course, after fixing `plays/text.yml`^^). Thank you @SubOptimal!

**Comment by bcoca** [comment]
sorry about the mess, i wrote the docs based on the roadmap .. not on the implementation, PR above should correct it.

**Comment by sksairaj9934** [comment]
mn k,, lj
