### ISSUE TITLE
Add support for Digital Ocean cloud hosting

### ISSUE THREAD

**Issue by extesy** [ansible/ansible#3074]
API documentation available at https://api.digitalocean.com

**Comment by mpdehaan** [comment]
Patches would be considered.

**Comment by neomantra** [comment]
I've started working on this here:
https://github.com/neomantra/ansible-digitalocean

No promises on how far I go with it... ;)

**Comment by neomantra** [comment]
Some module support for this has been added here:
https://github.com/ansible/ansible/blob/devel/library/cloud/digital_ocean

I'm currently updating my inventory plugin to use the same base library (dopy)as that module.

**Comment by neomantra** [comment]
Here's the pull request for the inventory script.  If you use DigitalOcean, please give it a try!
https://github.com/ansible/ansible/pull/3357
