### ISSUE TITLE
Accessing host variables slow on >= v2.3.1.0

### ISSUE THREAD

**Issue by hhsnow** [ansible/ansible#30773]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
templating, host vars

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /home/username/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.6.2 (default, Jul 20 2017, 03:52:27) [GCC 7.1.1 20170630]

ansible 2.4.0.0
  config file = /home/henrys/.ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/username/virutalenvs/ansible24/lib/python3.6/site-packages/ansible
  executable location = /home/username/virutalenvs/ansible24/bin/ansible
  python version = 3.6.2 (default, Jul 20 2017, 03:52:27) [GCC 7.1.1 20170630]

```

##### OS / ENVIRONMENT

Linux, controlling linux

##### SUMMARY
Iterating over host vars in versions >= v2.3.1.0 takes a significantly longer time then 2.3.0.0 and earlier. 

##### STEPS TO REPRODUCE

```yaml
- name: Upload keepalived.conf template
  template:
    src: template.j2
    dest: /home/username/test.out 
```
Abbreviated template.j2 (has more vars,etc in reality), with 100+ hosts in host_group
```
{% for host in groups[host_group] %}
    {% if hostvars[host]['ansible_' ~ (hostvars[host]['iface_public'])] is defined %}
    {{ hostvars[host]['ansible_' ~ (hostvars[host]['iface_public'])]['ipv4']['address'] }} {...}
    {% endif %}
{% endfor %}
```

##### EXPECTED RESULTS
A short runtime:
Ansible 2.3.0.0: 11.03s user

##### ACTUAL RESULTS

Ansible 2.3.1.0, Ansible 2.4.0.0: 106.82s user

**Comment by hhsnow** [comment]
I did try with the patch in https://github.com/ansible/ansible/pull/30587, did not change execution time.

**Comment by bcoca** [comment]
that patch is unrelated, it only affects slowdown seen in reading inventory from 2.3.2 to to 2.4, not related to templating nor hostvars during execution.

**Comment by jimi-c** [comment]
My test:
```
$ for i in {1..100}; do printf "host%03d ansible_connection=local\n" ${i}; done > hosts

$ cat test.yml 
- hosts: all
  gather_facts: no
  tasks:
  - name: Upload keepalived.conf template
    template:
      src: template.j2
      dest: "/tmp/30773_{{inventory_hostname}}.out"

$ cat group_vars/all 
ansible_eth0:
  ipv4:
    address: 1.1.1.1
```
and the same template.j2 as above. I'm using group_vars/all here to avoid any differences in timing related to gathering facts.

On my system:
2.2.0: 
```
$ time ansible-playbook -vv -i hosts test.yml -f 100 -e host_group=all -e iface_public=eth0 2>&1 >/dev/null

real	0m16.951s
user	0m48.758s
sys	0m11.859s
```

2.3.0: 
```
$ time ansible-playbook -vv -i hosts test.yml -f 100 -e host_group=all -e iface_public=eth0 2>&1 >/dev/null

real	0m17.966s
user	0m50.792s
sys	0m12.849s
```
2.3.1: 
```
$ time ansible-playbook -vv -i hosts test.yml -f 100 -e host_group=all -e iface_public=eth0 2>&1 >/dev/null

real	0m23.332s
user	1m5.278s
sys	0m18.626s
```
2.4.0: 
```
$ time ansible-playbook -vv -i hosts test.yml -f 100 -e host_group=all -e iface_public=eth0 2>&1 >/dev/null

real	0m34.724s
user	1m47.681s
sys	0m17.673s
```
So while I'm not seeing quite as bad a degradation as reported above, I am seeing that 2.4.0 takes about twice as long as 2.2.0/2.3.0, and the slowdown did start sometime around 2.3.1.

**Comment by jimi-c** [comment]
Bisect says this is the guilty commit:
```
$ git bisect bad; find . -name "*.pyc" -delete
8f97aef1a365cbbbb822d6d09f96af17a076b295 is the first bad commit
commit 8f97aef1a365cbbbb822d6d09f96af17a076b295
Author: Brian Coca <bcoca@users.noreply.github.com>
Date:   Tue May 23 17:16:49 2017 -0400

    Transition inventory into plugins (#23001)
```

**Comment by bcoca** [comment]
@jimi-c that is probably due to how host/group_vars now  work. They used to get loaded at 'inventory compilation' which front loaded a lot of the effort w/o needing it most of the time, now it happens in vars manager on `get_vars`. This should make the first time they get queried slower, but it caches files so it should even out in performance as it did before with inventory preloading and end up in better performance in general as only the ones needed are loaded, vs all of them.

That said, that was a huge patch so other things might be impacting performance, like making group variable precedence configurable.

**Comment by lassizci** [comment]
Also probably worth mentioning, that increasing forks does poor job in scaling, when accessing hostvars. The same tests @jimi-c posted:

These are on 2.4.0:
```
time ansible-playbook -vv -i hosts test.yml -f 5 -e host_group=all -e iface_public=eth0 2>&1 >/dev/null

real    0m42.388s
user    1m8.976s
sys     0m12.475s
```

```
time ansible-playbook -vv -i hosts test.yml -f 10 -e host_group=all -e iface_public=eth0 2>&1 >/dev/null

real    0m46.017s
user    1m15.317s
sys     0m13.452s
```

```
time ansible-playbook -vv -i hosts test.yml -f 20 -e host_group=all -e iface_public=eth0 2>&1 >/dev/null

real    0m41.792s
user    1m8.212s
sys     0m12.529s
```

```
time ansible-playbook -vv -i hosts test.yml -f 50 -e host_group=all -e iface_public=eth0 2>&1 >/dev/null

real    0m40.639s
user    1m6.425s
sys     0m12.265s
```

```
time ansible-playbook -vv -i hosts test.yml -f 100 -e host_group=all -e iface_public=eth0 2>&1 >/dev/null

real    0m40.153s
user    1m5.754s
sys     0m12.084s
```

**Comment by diclophis** [comment]
I can also attest to performance regressions in our playbooks with the upgrade to 2.4

**Comment by valentin-krasontovitsch** [comment]
Still seeing this with ansible 2.5.5 (latest release, as far as I understand), just fyi

... but on develop, it seems fixed!

**Comment by s-hertel** [comment]
This should be fixed by the [RUN_VARS_PLUGIN](https://docs.ansible.com/ansible/devel/reference_appendices/config.html#run-vars-plugins) option added in 2.10. Instead of loading vars whenever they are used, you can load them after parsing inventory instead.
