### ISSUE TITLE
Git module broken for systems using zsh

### ISSUE THREAD

**Issue by robinro** [ansible/ansible#30803]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
git

##### ANSIBLE VERSION
devel
introduced by #29069 in  f8005d2

##### OS / ENVIRONMENT
debian with zsh on target

##### SUMMARY
Any action of git using ssh fails.

##### STEPS TO REPRODUCE
`ansible -c local -m git -a 'repo=git@github.com:github/debug-repo dest=/tmp/foo' localhost -vvvv`

##### EXPECTED RESULTS
Successful clone.

##### ACTUAL RESULTS

fails with
```
The full traceback is:
  File "/tmp/ansible_QsVkLf/ansible_module_git.py", line 434, in clone
    os.makedirs(dest_dirname)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)

localhost | FAILED! => {
    "changed": false, 
    "cmd": "/usr/bin/git clone --origin origin '' /tmp/foo", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "accept_hostkey": false, 
            "archive": null, 
            "bare": false, 
            "clone": true, 
            "depth": null, 
            "dest": "/tmp/foo", 
            "executable": null, 
            "force": false, 
            "key_file": null, 
            "recursive": true, 
            "reference": null, 
            "refspec": null, 
            "remote": "origin", 
            "repo": "git@github.com:github/debug-repo", 
            "ssh_opts": null, 
            "track_submodules": false, 
            "umask": null, 
            "update": true, 
            "verify_commit": false, 
            "version": "HEAD"
        }
    }, 
    "msg": "Cloning into '/tmp/foo'...\nssh: Could not resolve hostname  -o batchmode=yes: Name or service not known\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.", 
    "rc": 128, 
    "stderr": "Cloning into '/tmp/foo'...\nssh: Could not resolve hostname  -o batchmode=yes: Name or service not known\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n", 
    "stderr_lines": [
        "Cloning into '/tmp/foo'...", 
        "ssh: Could not resolve hostname  -o batchmode=yes: Name or service not known", 
        "fatal: Could not read from remote repository.", 
        "", 
        "Please make sure you have the correct access rights", 
        "and the repository exists."
    ], 
    "stdout": "", 
    "stdout_lines": []

```

Commenting the `GIT_SSH_COMMAND` line fixes it. It appears zsh doesn't like the way the wrapper is built/passed.

**Comment by robinro** [comment]
I'd recommend to revert f8005d2, since it doesn't fix the original bug reported in #27699 for many systems. `GIT_SSH_COMMAND` is only available on newer git versions.

**Comment by robinro** [comment]
Instead of writing the wrapper, one can also construct the full ssh command and pass that into `GIT_SSH_COMMAND`. There is no need for a shell if `ssh` is called directly.

**Comment by alikins** [comment]
pinging @bcoca (via https://github.com/ansible/ansible/commit/f8005d27379c4d67bc86cf6af83ba1b1823bb10f)

**Comment by alikins** [comment]
@bcoca has a pr at https://github.com/ansible/ansible/pull/30850

**Comment by samdoran** [comment]
We need to verify if this is still an issue.

**Comment by sivel** [comment]
I cannot reproduce this issue any longer.  If you are still experiencing issues with devel, please feel free to open a new issue.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
