### ISSUE TITLE
Loop iterator iterates both sequentially and in parallel.

### ISSUE THREAD

**Issue by gintautassulskus** [ansible/ansible#30816]
##### ISSUE TYPE

 - Bug Report
OR
 - Feature Idea AND Documentation Report

Depends.

##### COMPONENT NAME

Loop _with_indexed_items_.

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A
##### SUMMARY

Loop with_indexed_items performs both sequential and parallel runs when loop's data sets across nodes are not identical but partially overlap, e.g.: dataset for node-1 is ['item1', 'item_node-1'] and for node-2 - ['item1', 'item_node-2'].
The example is provided further below.

Imho, the loop should run everything in a predictable manner - sequentially XOR in parallel.
The iteration logic should be 'dumb' and not perform any "optimisations".
It is up to the user to provide data in an appropriate order.

##### STEPS TO REPRODUCE

The play has two hosts: ['node-1', 'node-2'].

main.yml
```
-  include_role:
    name: roleX
    tasks_from: roleX_tasks.yml
  with_indexed_items:
    - "{{items}}"
```
roleX_tasks.yml

```
- debug:
    var: item

- debug:
    msg: other tasks
```

variables:
```
items:
  - item1
  - "item2_{{inventory_hostname}}"
```

##### EXPECTED RESULTS

The tasks for each data item should run either in parallel:

```
TASK [roleX : debug] ***************************************************************************************************************************************************************************************************************************
ok: [node-1] => {
    "msg": "item1"
}
ok: [node-2] => {
    "msg": "item1"
}

TASK [roleX : debug] ***************************************************************************************************************************************************************************************************************************
ok: [node-1] => {
    "msg": "other tasks"
}
ok: [node-2] => {
    "msg": "other tasks"
}

TASK [roleX : debug] ***************************************************************************************************************************************************************************************************************************
ok: [node-1] => {
    "msg": "item2_node-1"
}
ok: [node-2] => {
    "msg": "item2_node-2"
}

TASK [roleX : debug] ***************************************************************************************************************************************************************************************************************************
ok: [node-1] => {
    "msg": "other tasks"
}

ok: [node-2] => {
    "msg": "other tasks"
}
```

or sequentially:

```
TASK [roleX : debug] ***************************************************************************************************************************************************************************************************************************
ok: [node-1] => {
    "msg": "item1"
}

ok: [node-1] => {
    "msg": "other tasks"
}

TASK [roleX : debug] ***************************************************************************************************************************************************************************************************************************
ok: [node-2] => {
    "msg": "item1"
}
ok: [node-2] => {
    "msg": "other tasks"
}

TASK [roleX : debug] ***************************************************************************************************************************************************************************************************************************
ok: [node-1] => {
    "msg": "item2_node-1"
}

ok: [node-1] => {
    "msg": "other tasks"
}

TASK [roleX : debug] ***************************************************************************************************************************************************************************************************************************
ok: [node-2] => {
    "msg": "item2_node-2"
}
ok: [node-2] => {
    "msg": "other tasks"
}
```

##### ACTUAL RESULTS

The first item, identical on both nodes, is executed in parallel. The second item, different across the nodes, is executed sequentially.
In all cases and at all times ansible_play_batch is equal to ['node-1', 'node-2'].

```
TASK [roleX : debug] ***************************************************************************************************************************************************************************************************************************
ok: [node-1] => {
    "msg": "item1"
}
ok: [node-2] => {
    "msg": "item1"
}

TASK [roleX : debug] ***************************************************************************************************************************************************************************************************************************
ok: [node-1] => {
    "msg": "other tasks"
}
ok: [node-2] => {
    "msg": "other tasks"
}

TASK [roleX : debug] ***************************************************************************************************************************************************************************************************************************
ok: [node-1] => {
    "msg": "item2_node-1"
}

TASK [roleX : debug] ***************************************************************************************************************************************************************************************************************************
ok: [node-1] => {
    "msg": "other tasks"
}

TASK [roleX : debug] ***************************************************************************************************************************************************************************************************************************
ok: [node-2] => {
    "msg": "item2_node-2"
}

TASK [roleX : debug] ***************************************************************************************************************************************************************************************************************************
ok: [node-2] => {
    "msg": "other tasks"
}
```

```

```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

There are 2 main loops in Ansible, the `hosts:` loop (runs in parallel by default) and the `with_` loop which is sequential. When running the 'include_x' with items you are running one task in parallel inside a sequential loop, this task happens to generate more tasks, which are run sequentially per host inside that loop, hence the confusion.

If you used an `import_` instead it would be what you expected above as that would run multiple tasks, each in parallel, each with it's own sequential loop.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by gintautassulskus** [comment]
Thanks, @bcoca for the explanation. 

In regards to `import_`, it cannot be used with loops.

I am not sure though that what I see in my given example is consistent with your explanation.
Yes, both hosts are run in parallel, but Ansible tends to synchronise a run on each step/task unless it is used with `serial/run_once`.

In this particular example, the run type (parallel or sequential) is determined by the **data** and not by `with_` or `include_/import_`.
When the _{{item}}_ value is identical for both hosts, Ansible runs the tasks within `include_` in parallel, but in synchronised steps. This is a typical Ansible execution.

```
TASK [roleX : debug]  <------- STEP 1: both hosts execute the same task ***************************************************************************************************************************************************************************************************************************
ok: [node-1] => {
    "msg": "item1"
}
ok: [node-2] => {
    "msg": "item1"
}

TASK [roleX : debug] <------- STEP 2: both hosts execute the same task ***************************************************************************************************************************************************************************************************************************
ok: [node-1] => {
    "msg": "other tasks"
}
ok: [node-2] => {
    "msg": "other tasks"
}
```

When the _{{item}}_ value differs across the hosts, Ansible firstly runs all tasks within `include_` for "node-1" and only then runs all tasks for "node-2". The order of the hosts to be run is deterministic, there is no parallelism here.

```
TASK [roleX : debug] STEP 1 for node-1 ***************************************************************************************************************************************************************************************************************************
ok: [node-1] => {
    "msg": "item2_node-1"
}

TASK [roleX : debug] STEP 2 for node-1 ***************************************************************************************************************************************************************************************************************************
ok: [node-1] => {
    "msg": "other tasks"
}

TASK [roleX : debug] STEP 1 for node-2 ***************************************************************************************************************************************************************************************************************************
ok: [node-2] => {
    "msg": "item2_node-2"
}

TASK [roleX : debug] 
 STEP 2 for node-2***************************************************************************************************************************************************************************************************************************
ok: [node-2] => {
    "msg": "other tasks"
}
```

I have attached a minimal ansible project that demonstrates the issue: 
[loops.tar.gz](https://github.com/ansible/ansible/files/1331223/loops.tar.gz).
Run it with `ansible-playbook -i node-1,node-2,node-3 play.yml`.

The task execution pattern is more evident with more hosts and host-specific data.
If we have a loop (taken from the attached example project)
```
- include_tasks: dummy.yml
  with_indexed_items:
    - "{{items}}"
```
and the following data strcuture
```
items:
  - item1
  - "item2_{{inventory_hostname}}"
  - "item3_{{inventory_hostname}}"
  - "item4_{{inventory_hostname}}"
  - item5
```
the following "loop" data would be generated for the three hosts: 
```
node-1 = [item1, item2_node-1...item4_node-1, item5]
node-2 = [item1, item2_node-2...item4_node-2, item5]
node-3 = [item1, item2_node-3...item4_node-3, item5]
```
The run pattern would then look like this:
1. item1: **node-1, node-2 and node-3** run in parallel, synchronised after each task.
2. item2_node-1: **only node-1** runs
....
item4_node-1: **only node1** runs
3. item5: **node-1, node-2 and node-3** run in parallel, synchronised on after each task.
4. item2_node-2: **only node-2** runs
...
item4_node-2: **only node-2** runs
5. item2_node-3: **only node-3** runs
...
item4_node-3: **only node-3** runs

The execution sequence is not intuitive or consistent with typical Ansible run patterns.

**Comment by bcoca** [comment]
import + loops behaves like static includes, the loop is inherited by the tasks included. 

when dynamic, the include does depend on the data, both hosts 'run' in parallel, but one host does 'noop' tasks per task of the other hosts' tasks, unless the tasks are the same for all hosts.

**Comment by gintautassulskus** [comment]
I have a couple of comments/questions regarding iterations **over host-specific** data:

1.  Is there a reason to use 'noop' when data differs across the hosts?
'noop' eliminates the advantage of parallel processing and adds dual behaviour (some task parallel, some - not). I have a case where this behaviour breaks the 'run'.

2. The iterator does not iterate over the data in a consistent manner. Please look at the last given example. Steps 4 and 5 always run after step 3  and do not correspond to item positions in the respective data arrays.

I doubt many people are perfectly clear on such subtleties. Imho, this iterator behaviour is unintuitive and does not fit Ansible's "radically simple" statement. Or maybe it's just me :)
