### ISSUE TITLE
Assert module always returning "All assertions passed"

### ISSUE THREAD

**Issue by edgardmota** [ansible/ansible#30843]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
assert module

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
- Running from CentOS Linux release 7.2.1511 (Core)  to manage Microsoft Windows 7 Professional Service Pack 1;
- Running from CentOS Linux release 7.2.1511 (Core)  to manage CentOS Linux release 7.2.1511 (Core).

##### SUMMARY
Any assertion is ***always*** passing, ***even when hosts are down***

##### STEPS TO REPRODUCE
On the ad-hoc mode, you can simply try to check if host has total memory of 1MB (an absurd, BTW), even if the host is down:
```
sudo ansible MY_HOST -m assert -a "that= \"ansible_memtotal_mb == 1\" msg= \"MY_HOST failed\""
```

##### EXPECTED RESULTS
Anything related to the fail of the assertion.

##### ACTUAL RESULTS
```
MY_HOST | SUCCESS => {
    "changed": false, 
    "msg": "All assertions passed"
}
```

**Comment by alikins** [comment]
I can't reproduce this.

with stable-2.3:

```
[newswoop:F25:ansible (stable-2.3 % u=)]$ ansible localhost -m assert -a 'that="ansible_memtotal_mb == 1" msg="MY_HOST failed"'
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

localhost | FAILED! => {
    "failed": true, 
    "msg": "The conditional check 'ansible_memtotal_mb == 1' failed. The error was: error while evaluating conditional (ansible_memtotal_mb == 1): 'ansible_memtotal_mb' is undefined"
}
```

And with a simpler assert conditional:

```
[newswoop:F25:ansible (stable-2.3 % u=)]$ ansible localhost -m assert -a 'that="2 == 1" msg="MY_HOST failed"'
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

localhost | FAILED! => {
    "assertion": "2 == 1", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true, 
    "msg": "MY_HOST failed"
}
```

with version 2.3.2.0
```
ansible 2.3.2.0 (detached HEAD ref: refs/) last updated 2017/09/25 13:12:33 (GMT -400)
  config file = /home/adrian/src/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

**Comment by bcoca** [comment]
@alikins, understandable as it is a gathered facts, that adhoc command would only work with persistent caching enabled.

@edgardmota  which is why there is a section for 'configuration' above, which should have shown you are using a persistent cache plugin.

**Comment by edgardmota** [comment]
Performing some further tests, It seems to me that the issue is related to the space between the equal sign of the parameter ```that``` and the condition. Trying the simpler sugestion of @alikins with and without that space gave me different outputs:

***Without the space:***
```
ansible localhost -m assert -a "that=\"2 == 1\" msg=\"MY_HOST failed\""
localhost | FAILED! => {
    "assertion": "2 == 1", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true, 
    "msg": "MY_HOST failed"
}
```

***With the space:***
```
ansible localhost -m assert -a "that= \"2 == 1\" msg=\"MY_HOST failed\""
localhost | SUCCESS => {
    "changed": false, 
    "msg": "All assertions passed"
}
```
Could anyone reproduce such behaviour?

**Comment by bcoca** [comment]
the space is probably registering the whole thing as a string vs an expression .. strings evaluate as True.

**Comment by edgardmota** [comment]
Got it, @bcoca. However, that's still odd and unexpected. Look what happens when this space is placed between the ```msg``` parameter and its value:

```
ansible localhost -m assert -a 'that="2 == 1" msg= "MY_HOST failed"'
ERROR! this task 'assert' has extra params, which is only allowed in the following modules: command, win_command, shell, win_shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta
```

Why ansible perfoms so differently in such similar situations? As reported earlier, even hosts which are down are passing all assertions and that doesn't seem right.

**Comment by bcoca** [comment]
The issue is mostly the x3 conversions you go through in Adhoc, bash, k=v parser and Jinja2, this can create weird results with conditionals, but conditionals were never really meant to work with adhoc. Since you cannot use `when` clauses with adhoc,   no one has seen this before, probably  because fail/assert also make little sense with adhoc.

**Comment by samdoran** [comment]
Using `assert` with `ad-hoc` is not useful and making this work properly, due to all the conversion gymnastics mentioned above, is probably not worth the effort.

To discuss this further, please reach out on IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
