### ISSUE TITLE
Subdependencies don't update, event when their parent dependencies in `requirements.yml` update

### ISSUE THREAD

**Issue by hadrien-toma** [ansible/ansible#30867]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- requirements.yml

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ash/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
Defaults

##### OS / ENVIRONMENT
* Ubuntu 16.04 64 bits

##### SUMMARY
When a dependency in the requirements.yml has changed, a re-run of `ansible-galaxy install -p ./plays/roles -r requirements.yml` will trigger its update. However, its dependencies are not updated and are logged as `already installed`. I think this issue is related to #16909, conflicting in the name of the same subrole and so ignoring it.

##### STEPS TO REPRODUCE
I tested with GitHub as the source code provider:
* Create two GitHub projects A and B.
* Clone these projects and use `ansible-galaxy` to scaffold them.
* Push role A to GitHub.
* Update role B `meta/main.yml` file in order to assign role A as a dependency.
* Push role B to GitHub.
* Create an empty Ansible project and init a `requirements.yml` file containing B as a requirement.
* Use `ansible-galaxy` to install dependencies **-> Works as expected, the two roles are fetched.**
* Edit and push a difference in role B. Use `ansible-galaxy` to install dependencies **-> Works as expected: the role B is updated.**
* Edit and push a difference in role A. Use `ansible-galaxy` to install dependencies **-> Doesn't work as expected: the role A is not updated.**

##### EXPECTED RESULTS
I expected the role A to be updated, event if it is not a direct dependency of the project.

##### ACTUAL RESULTS
The role A is not updated (more details in the STEPS TO REPRODUCE section).

**Comment by alikins** [comment]
pinging @bcoca

**Comment by danowar2k** [comment]
This also happens in Ansible 2.4.2.0.

```
ansible 2.4.2.0
  config file = /home/vagrant/playbooks/playbook-moodle/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```
I have two roles A and B that act as wrappers to another role C (A and B have a dependency to C). I updated C and updated my roles in my playbook using requirements.yml. C didn't update ("already installed").

I had to delete the directory of C and again install the requirements to acquire the current version of C. None of my roles yet use versions. I tried with no version and with version set to "master".

The roles don't seem to download the .git directories, either. I couldn't git pull inside the role directory. I don't know if this is intended.

**Comment by ghost** [comment]
@danowar2k  The .git dirs are dropped in role install due to that being the behaviour of git archive. See https://github.com/ansible/ansible/pull/34642/files for a pending fix for that.

Pull request is in that fixes the handling of role dependencies when using force.

**Comment by bcoca** [comment]
fixed by #49347

**Comment by samdoran** [comment]
You can use `ansible-galaxy install --force-with-deps` in a newer version of Ansible to get what you need.

**Comment by paylocity-sflanders** [comment]
@samdoran what version implements that --force-with-deps?

**Comment by samdoran** [comment]
@paylocity-sflanders This is new in Ansible 2.8.
