### ISSUE TITLE
Does Ansible Support AWS NLB?

### ISSUE THREAD

**Issue by winstonsimon** [ansible/ansible#30870]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
feature
##### ANSIBLE VERSION

```
ansible --version                                                                                                                              git:aws
ansible 2.3.1.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT
AWS

##### SUMMARY
How do we configure AWS new NLB? Do you have any documentation for this?

##### STEPS TO REPRODUCE
Refer: http://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.html

##### EXPECTED RESULTS
Ansible should provide a feature to create AWS NLB

##### ACTUAL RESULTS
Ansible should provide a feature to create AWS NLB

**Comment by s-hertel** [comment]
Ansible doesn't have a module yet for this feature. There is a request for it here: #30701. I'm going to close this ticket since the other was opened first so we can track the progress in one location.

duplicate_of: #30701
