### ISSUE TITLE
Breaking changes in minor revisions of ansible

### ISSUE THREAD

**Issue by pfremm** [ansible/ansible#30871]
As an example I see include in 2.8 is scheduled to be deprecated.  
http://docs.ansible.com/ansible/latest/include_module.html

Why are breaking changes being done in minor revisions of ansible?  Normally minor revisions should not result in breaking changes as an industry standard.  This is very troublesome behavior.  

Does ansible have a versioning strategy published?

**Comment by sivel** [comment]
Ansible does not follow strict symver.  X.Y are not considered minor versions.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
