### ISSUE TITLE
New ansible-inventory option to return variables at group level

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible#30877]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
`ansible-inventory` CLI, found at https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/inventory.py

##### ANSIBLE VERSION
2.4 or 2.5

##### CONFIGURATION
Any, functionality of output should be consistent with any valid Ansible configurations.

##### OS / ENVIRONMENT
N/A

##### SUMMARY
`ansible-inventory` will return all variables at the host level. This is consistent with behavior inside of playbooks, but can lead to very large outputs, because variables defined at the group level will be replicated with each host inside of it.

I previously made an attempt at this in https://github.com/bcoca/ansible/pull/4, but that solution needed more work to respect the users existing configuration customizations.

##### STEPS TO REPRODUCE

Copy this folder to your local machine, cd into it.

https://github.com/AlanCoding/Ansible-inventory-file-examples/tree/master/issues/gvars

`ansible-inventory -i inventory.ini --list`

##### EXPECTED RESULTS

Perhaps by adding another flag, like `--optimized`, we could get output without the `airport_code` variable duplicated, like so:

```
{
    "_meta": {
        "hostvars": {
            "host1": {}, 
            "host2": {}
        }
    }, 
    "all": {
        "children": [
            "raleigh", 
            "ungrouped"
        ]
    }, 
    "raleigh": {
        "hosts": [
            "host1", 
            "host2"
        ],
       "vars": {
           "airport_code": "RDU"
       }
    }, 
    "ungrouped": {}
}
```

##### ACTUAL RESULTS

The only currently available way of using this command will put `airport_code` (a variable specific to the group `raleigh`) in hostvars.

```
{
    "_meta": {
        "hostvars": {
            "host1": {
                "airport_code": "RDU"
            }, 
            "host2": {
                "airport_code": "RDU"
            }
        }
    }, 
    "all": {
        "children": [
            "raleigh", 
            "ungrouped"
        ]
    }, 
    "raleigh": {
        "hosts": [
            "host1", 
            "host2"
        ]
    }, 
    "ungrouped": {}
}
```

RESOLVED: ~Note that `ansible_inventory_sources` appears to be some other unrelated thing, and I may raise a separate issue about that.~

**Comment by simfarm** [comment]
@bcoca I've run into this too while going through our Tower tests.

I feel like having Ansible return variables in this way is more intuitive to the user.

**Comment by bcoca** [comment]
@simfarm yet misleading as they would get the impression that ansible itself will be able to access by group

**Comment by simfarm** [comment]
Can you explain @bcoca? Why would we not want to present full group variables under host variables?

**Comment by bcoca** [comment]
we DO present them, they are in the hostvars

we DONT present them in the group that set them as the groups 'go away' once inventory is processed.

**Comment by simfarm** [comment]
It is really not intuitive to me that we'd show group variables partially in host variables.

**Comment by bcoca** [comment]
intuitive or not, the current output represents what Ansible itself sees when the play starts, not the original inventory layout.

If we present the variables by group we are not showing the final flattening/resolution, aka the value you would be using in the playbook. 

I do want to add this option, but it should not be the default and clearly state that this is NOT what is available in the playbooks.

**Comment by AlanCoding** [comment]
> I do want to add this option, but it should not be the default and clearly state that this is NOT what is available in the playbooks.

Agreed, it should be some flag specifically for tools that want to use this (more memory-efficient) data model. AWX is a prime example.

----
Also consider that current group vars behavior is not consistent. Example:

https://github.com/AlanCoding/Ansible-inventory-file-examples/blob/master/static/group_vars.ini

https://gist.github.com/AlanCoding/a07cc14e96f5267336ebefe1692994be

```json
    "southeast": {
        "children": [
            "atlanta", 
            "raleigh"
        ], 
        "vars": {
            "escape_pods": 2, 
            "halon_system_timeout": 30, 
            "self_destruct_countdown": 60, 
            "some_server": "foo.southeast.example.com"
        }
```

you can see that `escape_pods` _are_ defined on the group level, but they are also defined on the hostvars level.

As a counter-example, if you run the file `static/vars_dirs/inv` in that repo, you find that group var `halon_system_timeout` is _only_ defined in hostvars (it comes from a `group_vars` folder).

I expect that `escape_pods` will be removed from the group-level vars in the normal "flat" use as a side-effect of this enhancement. This would make the behavior fully consistent.

**Comment by bcoca** [comment]
yep, that is a bug

**Comment by ghjm** [comment]
In addition to Alan's concern about memory efficiency, the big issue here for Tower / AWX is that in the UI and API prior to running a playbook, we actually do need to distinguish between host vars and group vars. If you have a group var defined, it makes no sense for Tower to display it as a host var on each of your 10,000 hosts, and have an empty "group vars" section in the UI that never gets populated.

I completely understand that when you're actually running a playbook, Ansible flattens this and there is no difference between a host and a group var - each host just gets what it gets in the the host loop.  But that's not the only use case for the ansible-inventory script, and if all the dynamic inventory sources are going to be in core now, Tower / AWX needs some way of picking up group vars from them.

(@matburt please comment on the above and let me know what parts I got wrong)

**Comment by ryansb** [comment]
Thanks for clarifying - I'm going to look at porting parts of Alan's start on this to the version of ansible-inventory that's on devel.

**Comment by ryansb** [comment]
Looking at the implementation options for this, it's going to require some deep changes to how values are discovered (and track their source) for hosts. It would be along the lines of https://github.com/ansible/ansible/compare/devel...alikins:var_man_changed_inv_plugins , which definitely can't be done after the 2.5 core freeze, so this fix will have to wait until the next feature cycle.

**Comment by alikins** [comment]
@ryansb I tend to agree with pushing this to 2.6, 
Ignore the invasiveness of https://github.com/ansible/ansible/compare/devel...alikins:var_man_changed_inv_plugins , the other issue would that it is based
on tracking scope/context of vars as setup by a playbook.  ansible-inventory does
it own thing for building up the data structures it uses for dumping the output that
mostly bypasses VariableManager.get_vars() and combine_vars() so that branch
doesn't know anything about the results.

**Comment by bcoca** [comment]
i think we can still have this in 2.5, just diff approach, just use some of the functions from varsmanager directly instead of consuming the results of `get_vars`
