### ISSUE TITLE
Random output of "sudo -H -S -n"

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#30893]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Core?

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.5.0 (devel e4c9ffa7e6) last updated 2017/09/25 08:22:05 (GMT -500)
  config file = None
  configured module search path = [u'/Users/tanner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/ansible.git/ansible/lib/ansible
  executable location = /Users/tanner/projects/ansible.git/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT

Management host: macOS
Managed host: Windows 7

##### SUMMARY

Looks like debug code made it into devel and the become logic displays, 
```
sudo
-H -S -n
```
##### STEPS TO REPRODUCE

```yaml
Any task that becomes: yes
```

##### EXPECTED RESULTS

Not to display sudo -H -S -n

##### ACTUAL RESULTS

```
TASK [updates ] *************
skipping: [www.XXXXX.org]
sudo
-H -S -n
sudo
-H -S -n
sudo
-H -S -n
sudo
-H -S -n
```

**Comment by vikwin** [comment]
This is caused by these two lines in /lib/ansible/playbook/play_context.py at line number ~536:
```
  print(exe)
  print(flags)
```

These seem to be forgotten debug lines, they should be safe to remove.
