### ISSUE TITLE
Ansible stopped recognizing my group vars after commit(?)

### ISSUE THREAD

**Issue by dekked** [ansible/ansible#3093]
Commit https://github.com/ansible/ansible/commit/6cd3ba5b06578deda4aca19e77debb59d1d7df49 probably introduced a bug (didn't happen in the previous commit to it) that made Ansible stop recognizing my group_vars. If required, I can provide an example playbook for this to be reproduced.

I have traced it to the following condition in inventory/vars_plugins/group_vars.py, which was not present before:

``` python
# it's not an eror if the directory does not exist, keep moving
if not os.path.exists(basedir):
    continue
```

My 'basedir' is empty, so of course os.path.exists(basedir) returns False and the loop is skipped every time.

However,

``` python
p = os.path.join(basedir, "group_vars/all")
print os.path.exists(p)
>>> True
```

So the variables actually exist but Ansible can't find them because basedir is empty and this prevents the second check from ever being made.

I did no PR to fix this because I am not sure why 'basedir' comes in empty and if it is right to skip the first check.

Any idea if I missed a setting, something changed, or this is indeed a bug? Thanks.

**Comment by mpdehaan** [comment]
It sounds like you are saying 'basedir' does not exist but basedir/group_vars/all does exist, which is confusing to me.

Please provide some steps to reproduce, along with the ansible-playbook command you have executed and the structure of your inventory directory.

**Comment by mpdehaan** [comment]
Just made a change for this, it appears python's os.path.dirname function can return '' if a file is doesn't have a directory component, we were handling None but not ''.

Try the latest 1.2 out now and see if you are good, I think you'll be fixed up.   Thanks!

**Comment by dekked** [comment]
Works like a charm, thanks to you!
