### ISSUE TITLE
Inventory class object not available in 2.4

### ISSUE THREAD

**Issue by derfUrban** [ansible/ansible#30953]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 /ansible/inventory

##### ANSIBLE VERSION

ansible-playbook 2.4.0.0
  config file = ansible.cfg
  configured module search path = ['/library']
  ansible python module location = python3.5/site-packages/ansible
  executable location = ansible-playbook
  python version = 3.5.3 (default, Apr 23 2017, 18:09:27) [GCC 4.2.1 Compatible Apple LLVM 8.0.0
##### CONFIGURATION

[DEPRECATION WARNING]: DEFAULT_SUDO_FLAGS option, In favor of become which is a generic framework . This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
DEFAULT_ACTION_PLUGIN_PATH(/ansible.cfg) = ['/plugins/action']
DEFAULT_CALLBACK_PLUGIN_PATH(/ansible.cfg) = ['/plugins/callback']
DEFAULT_FILTER_PLUGIN_PATH(/ansible.cfg) = ['/plugins/filter']
DEFAULT_HOST_LIST(/ansible.cfg) = ['/inventory']
DEFAULT_JINJA2_EXTENSIONS(/ansible.cfg) = jinja2.ext.do
DEFAULT_LOOKUP_PLUGIN_PATH(/ansible.cfg) = ['/plugins/lookup']
DEFAULT_MODULE_PATH(/ansible.cfg) = ['/library']
DEFAULT_ROLES_PATH(/ansible.cfg) = ['/roles']
DEFAULT_STDOUT_CALLBACK(/ansible.cfg) = skippy
DEFAULT_SUDO_FLAGS(/ansible.cfg) = -H -S
RETRY_FILES_ENABLED(/ansible.cfg) = False

##### OS / ENVIRONMENT

Darwin C02SV6VAFVH4 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

##### SUMMARY
 As in ansible 2.1 the Inventory class object is not available in 2.4 as otherwise mentioned in articles below
Documents need correcting for Ansible2.4
http://docs.ansible.com/ansible/latest/dev_guide/developing_api.html
ansible.inventory.Inventory is not available
https://github.com/ansible/ansible/tree/devel/lib/ansible/inventory

##### STEPS TO REPRODUCE
Download ansible 2.4 through pip install ansible --upgrade. Try import Inventory using python API

```yaml

```

##### EXPECTED RESULTS
Inventory module to be present

##### ACTUAL RESULTS
No need to run playbook. Just try to import, expected Inventory module to be present

 N/A a
```

```

**Comment by sivel** [comment]
resolved_by #30640
