### ISSUE TITLE
Path parsing bug (git HEAD 79ec5fa)

### ISSUE THREAD

**Issue by m-o-e** [ansible/ansible#3098]
The following two commands are currently **not** equivalent:
1. `ansible-playbook -i ./production site.yml`
2. `ansible-playbook -i production site.yml`

Command 1 works correctly.

Command 2 leads to inventory.basedir() == None. In consequence ansible fails to look up `group_vars`, `host_vars`, and perhaps other things.

Command 2 is from the best practices guide.

**Comment by mpdehaan** [comment]
fix pushed, try things now and let me know if you're better

**Comment by m-o-e** [comment]
:+1:
