### ISSUE TITLE
split the changelog

### ISSUE THREAD

**Issue by bcoca** [ansible/ansible#30996]
Split changelog into file per release, it is getting unwieldy, also it would be nice to create ToC and sunset the RELEASES.txt as it is mostly duplicate information. 

##### ISSUE TYPE

 - Feature Idea
 - Documentation Report

##### COMPONENT NAME

changelog

##### ANSIBLE VERSION

```
2.5
```

**Comment by alikins** [comment]
Would be a good time to convert it to rst as well, so we can include it directly in docs/docsite

**Comment by webknjaz** [comment]
//side note: recent best practice in python communities is to use [towncrier](https://pypi.python.org/pypi/towncrier). consider using it.

The flow is simple:
1. you define a folder for separate changes related to PRs and enforce PR authors include description of changes they did into that folder.
2. after that at some point you hit "generate me a changelog, please" command, which adds all of those files into normal changelog and deletes 'em from that folder.

**Comment by Akasurde** [comment]
@bcoca is this issue still valid since we have changelog fragments ?

**Comment by webknjaz** [comment]
It's probably outdated, yes. @mattclay has pushed #40421 and #41169 into devel recently. And there was a tool @abadger ended up adopting in spring IIRC.

**Comment by Akasurde** [comment]
@webknjaz Thanks for the information.
