### ISSUE TITLE
Add datetime type to argspec

### ISSUE THREAD

**Issue by bcoca** [ansible/ansible#31017]
This should allow any string date and/or time representation to be accepted for an option and autmatically get it converted to a datetime object for use inside a module

##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

module_utils/basic

##### ANSIBLE VERSION

```
2.5
```

**Comment by Jeyanthinath** [comment]
@bcoca  Shall I give it a try ?

**Comment by bcoca** [comment]
less work for me? yes, definitely

**Comment by bcoca** [comment]
Adding filters to Jinja2 to handle conversion of date time is a better approach than dding all this complexity into argspec for such small demand.
