### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'startswith'" when trying to update packages

### ISSUE THREAD

**Issue by serenecloud** [ansible/ansible#3101]
Hi,

I'm new to ansible and I'm trying to set it up to manage some VPS boxes I have, but I'm having a problem with one of them.
My playbook:

<pre>

---
- hosts: vps                                                                                          
  user: ansible
  sudo: yes 
  tasks:
    - name: get latest packages
      action: apt update_cache=yes
    - name: install latest packages
      action: apt upgrade=safe
</pre>

Output from running:

<pre>
TASK: [install latest packages] *********************************************** 
fatal: [husker.crimson.net.nz] => failed to parse: Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-1370213747.54-271802212190720/apt", line 1238, in <module>
    main()
  File "/home/ansible/.ansible/tmp/ansible-1370213747.54-271802212190720/apt", line 318, in main
    upgrade(module, p['upgrade'])
  File "/home/ansible/.ansible/tmp/ansible-1370213747.54-271802212190720/apt", line 232, in upgrade
    apt_cmd_path = m.get_bin_path(apt_cmd, required=True)
  File "/home/ansible/.ansible/tmp/ansible-1370213747.54-271802212190720/apt", line 1049, in get_bin_path
    path = os.path.join(d, arg)
  File "/usr/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
</pre>

The failed VPS is running 32bit Debian Wheezy with what looks like a custom built kernel (it's OpenVZ, I didn't get the choice). I also had this issue when it was running Sqeeze.

The last debug line for the host before it fails is:

<pre>
<husker.crimson.net.nz> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=REDACTED] password: " -u root /bin/sh -c '"'"'/usr/bin/python /home/ansible/.ansible/tmp/ansible-1370214294.3-55940724642282/apt; rm -rf /home/ansible/.ansible/tmp/ansible-1370214294.3-55940724642282/ >/dev/null 2>&1'"'"''
</pre>

Because this runs fine on my other VPS (64bit Debian Squeeze) I'm assuming the playbook is fine. I can login as the ansible user and execute sudo apt-get update and and sudo apt-get upgrade without sudo.

I'm running ansible 1.2 - build from github a couple of days ago.

**Comment by mpdehaan** [comment]
Thanks for the heads up.  This si the first time I've seen this though it may only affect the upgrade=safe option and will look into this.

You should be able to use the command or shell module for a quick workaround.

**Comment by mpdehaan** [comment]
Just tried this on Wheezy, 32bit, on latest 1.2 (as of right now) and did not encounter any problems.

Suspect this _may_ be an issue with your custom setup.

You may wish to debug with ./hacking/test-module to se see if you can find a specific source of this error.

**Comment by serenecloud** [comment]
I've given it a try with upgrade=yes and I get the same issue on the same line.

Are there some docs I can read about using ./hacking/test-module? I'm quite a python newbie.

**Comment by serenecloud** [comment]
Oh, I should include the fact that the failing VPS only has 256MB of RAM (the other has 512MB) - could that be a factor?

**Comment by serenecloud** [comment]
I've been experimenting a bit more and I've found some more info:
- Ansible runs fine on a 128MB RAM system, so it's not that.
- The box in question was 32bit Squeeze, not Wheezy as I thought, my apologies for that mistake :(
- I've rebuilt the box as 64bit Wheezy and it's working fine now.

**Comment by bcoca** [comment]
I run ansible on a 32bit Gentoo with 256RAM w/o any issues

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
This looks like it is just a bug in the upgrade code of the apt module,
perhaps, shouldn't be architecture specific but interesting it has resolved
itself.

It is definitely not a resource issue.

**Comment by swestcott** [comment]
I'm getting this same error on a 64bit Ubuntu Lucid VPS, but not a 64bit Ubuntu Quantal VPS.

**Comment by swestcott** [comment]
Ah, I missed the note in the docs which says aptitude must be installed for upgrade to work... this was missing from my Lucid VPS. Installing it fixed this error.

Perhaps the apt module could provide a better error message or just install aptitude if missing?

**Comment by mpdehaan** [comment]
I totally agree it should provide a better error message.

Something someone wants to send in a pull request for?

**Comment by serenecloud** [comment]
Added pull request #3379 for this :)

**Comment by mpdehaan** [comment]
This has been merged so I can close this one, thanks!
