### ISSUE TITLE
SSH Key Login to Encrypted Home Directory Fail

### ISSUE THREAD

**Issue by sangwei** [ansible/ansible#3102]
Ansible Version: ansible 1.2 (devel b8630d2bc4) last updated 2013/05/31 08:59:33 (GMT +000)
Remote PC: Ubuntu 12.10 (GNU/Linux 3.5.0-17-generic x86_64)
Want to login to it with SSH Key
I can do that with 'ssh -i ~/.ssh/id_rsa -p 12345 userx@.....', but when using ansible, I keep getting: 'FAILED => failed to transfer file to /ping'
Here is debug output detail:
ansible all -m ping -i ./ansible_hosts --private-key=~/.ssh/id_rsa -vvv

<10.10.10.10> ESTABLISH CONNECTION FOR USER: rooot on PORT 36785 TO 10.10.10.10
<10.10.10.10> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1370223773.13-205181425068983 && chmod a+rx $HOME/.ansible/tmp/ansible-1370223773.13-205181425068983 && echo $HOME/.ansible/tmp/ansible-1370223773.13-205181425068983'
<10.10.10.10> REMOTE_MODULE ping
<10.10.10.10> PUT /tmp/tmpQcGzzP TO /ping
remote | FAILED => failed to transfer file to /ping

ansible_hosts:
remote ansible_ssh_port=36785 ansible_ssh_host=10.10.10.10 ansible_ssh_user=rooot

I am not sure if remote encrypted home directory caused the problem. But just run 'ssh -i key_file ...' is working.

**Comment by bennojoy** [comment]
The username is rooot, is that right ? should it be "root" . Also is the
authorized_key set for root. can you do a ssh -i id_rsa
root@10.10.10.10from you ansible host?
- Benno

**Comment by sangwei** [comment]
Benno, strange, but yes, is rooot ... And authorized_key on server is located at /etc/ssh/rooot/authorized_key, and config in /etc/ssh/sshd_config (AuthorizedKeysFile      /etc/ssh/%u/authorized_keys)
/etc/ssh/rooot
drwxr-xr-x 2 rooot rooot   4096 Jun  2 21:16 rooot
/etc/ssh/rooot/authorized_keys
-rw-r--r-- 1 rooot rooot 400 Jun  2 21:16 authorized_keys

**Comment by bennojoy** [comment]
by default Ansible uses sftp to transfer the file, can you check if the
sftp subsystem is enabled, and if files can be transferrred using sftp.

Thanks,
Benno

**Comment by sangwei** [comment]
sftp -P 36785 -i ~/.ssh/id_rsa rooot@10.10.10.10
Connected to 10.10.10.10.
sftp> ls
smoke
sftp> put ttt
Uploading ttt to /home/rooot/ttt
ttt                                           100%    0     0.0KB/s   00:00
sftp> ls
smoke  ttt
sftp>

Benno, sftp is working.

**Comment by bennojoy** [comment]
can you check what is the value of the variable remote_tmp in your
ansible.cfg. from the debug output it seems it is trying to put the file in
"/"
can you try changing it to: remote_tmp = $HOME/.ansible/tmp
- Benno

**Comment by sangwei** [comment]
Problem solved. My rooot's remote home directory (/home/rooot) somehow is:
dr-x------ 2 rooot rooot 4096 Jun  3 11:36 rooot
No 'w' for user rooot
chmod 755, and everything is OK now.
Thank you Benno!
