### ISSUE TITLE
normalize temp dir/file usage (remote_tmp, etc)

### ISSUE THREAD

**Issue by bcoca** [ansible/ansible#31022]
All subsystems should use same temp dirs (ansiballz, shell+action,  modules, async)
Temp dirs should be more configurable (right now they are global, should be host specific)

In doing this we should address/fix the following issues:
~~#20886~~
#27699 ansiballz not using remote_tmp
~~#17908~~ (not main issue, but having per host configurable remote_tmp would mitigate)
#30064 git module creates script in /tmp which does not work on 'no exec systems'
~~#30074~~ (not main issue, giving 'url using' module a predictable tmp to write to)
~~#25831~~ read only /tmp
~~#25794~~
~~#22203~~ 
~~#21562~~
~~#18391~~ (mostly by allowing per host 'world readable tmp files')
~~#13876~~
#16046
~~#11937~~
~~#28318~~
~~#29019~~
~~#33079~~
~~#31617~~
Related prs:
~~#28716~~

##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

core
##### ANSIBLE VERSION

```
2.5
```

**Comment by abadger** [comment]
https://github.com/ansible/ansible/issues/11937 => Can't use default location of .ansible_async file because it is read-only.

**Comment by alikins** [comment]
https://github.com/ansible/ansible/pull/28716  pr for 'ansible_async' in remote_tmp

**Comment by alikins** [comment]
(reference everything again so the github issue history expands to include bug title)
#20886
#27699
#17908 (not main issue, but having per host configurable remote_tmp would mitigate)
#30208 
#30064
#30074 (not main issue, giving 'url using' module a predictable tmp to write to)
#25831 
#25794
#22203
#21562
#18391 (mostly by allowing per host 'world readable tmp files')
#13876
#16046
#16048
#11937

Related prs:
#28716

**Comment by alikins** [comment]
More refs:
https://github.com/ansible/ansible/issues/28318
https://github.com/ansible/ansible/issues/29019

**Comment by sivel** [comment]
Another ref: https://github.com/ansible/ansible/issues/31617

In cloud-init it seems `$HOME` is not set, and that impacts the ability to use `~`.  cloud-init would require special treatment, as to not depend on either, or to:

1. use a `remote_tmp` without `$HOME` or `~`
1. set `$HOME`

Of additional note, python falls back to using the pwd module to determine the homedir, if `$HOME` isn't set.  More info in https://github.com/ansible/ansible/issues/31617#issuecomment-339721417

**Comment by s-hertel** [comment]
Since there are only a couple issues open, we'll handle the rest as individual tickets.
