### ISSUE TITLE
win async: The shell cannot be started REGDB_E_READREGDB

### ISSUE THREAD

**Issue by jborean93** [ansible/ansible#31030]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
async

##### ANSIBLE VERSION
```
2.5
```

##### CONFIGURATION
default

##### OS / ENVIRONMENT
Windows

##### SUMMARY
When using async over a host with a higher latency the async task fails with the error

```
The shell cannot be started. A failure occurred during initialization:\r\nCould not read key from registry (Exception from HRESULT: 0x80040150 (REGDB_E_READREGDB))\r\n
```

It seems like the HKCU profile is being unloaded on an async task in a specific scenario which in the end stops the task from actually starting. This seems to happen more often on a Server 2012 (non R2) host but it can affect the others. Originally the errors were found when running the win_wait_for tests which is why they have been disable for now.

The trouble is that because the task is run asynchronously without any polling, Ansible will never fail with this error and the only reason why it was found was through the `async_status` module.

##### STEPS TO REPRODUCE
The below playbook, if run multiple times, will eventually result in this error. I found if connecting to a host over the internet (like AWS servers) and not on a private network it occurs more often.

```yaml
- hosts: windows
  gather_facts: no
  tasks:
  - win_shell: Start-Sleep -Seconds 5; Write-Host hi
    register: async
    async: 10
    poll: 0
  
  - pause:
      seconds: 10

  - async_status:
      jid: '{{async.ansible_job_id}}'
    register: status
  
  - debug:
      var: status
```

**Comment by jhawkesworth** [comment]
Nice find.  Feels like a windows issue, or perhaps an assumption about how windows is going to be used.

**Comment by jborean93** [comment]
I've played around with this and so far I have been unable to create a scenario in which this always fails. I can still get the occasional error when running on an AWS host but without a way to reliably produce this error, I will find it hard to come up with a fix. So far what I've tried

* Add some sleeps in the `$exec_wrapper` of the `async_wrapper` to wait to execute the powershell script after it receives it on the stdin. This was to rule out any issues with the profile being unloaded after the stdin is sent but before the module is actually executaed
* A sleep before win_shell starts the powershell executable to see what happens there
* Holding all the keys of HKLM and HKCU open as a variable to stop the profile from being unloading
* Resume the async pid manually after the process is created and the WinRM session has been closed

When looking at it further, it seems like the async task starts up correctly and calls the module we want to run, in this case `win_shell`. The error occurs is when the `win_shell` module tries to start the `powershell.exe` executable and sets the `REGDB_E_READREGDB` error on that modules `stderr` return value.

Will still continue to look into it but so far no major progress.

**Comment by jborean93** [comment]
It's been a while since I've last looked at this but I came across a similar issue today with another process. It failed with the error

```
The shell cannot be started. A failure occurred during initialization:
Could not read key from registry (Exception from HRESULT: 0x80040150 (REGDB_E_READREGDB))
```

The ultimate cause for this was that the user that the process had started from was never logged on interactively before and had no profile to load. This could be the cause of the async issues as I've only ever had the error come up in AWS with a newly provisioned host, potentially the user we are running as was never logged in before and caused the issue.

**Comment by briantist** [comment]
I have a similar issue with `win_service`. The `async` job starts fine.

Here's the error from `async_status`:
```yaml
fatal: [host.fqd.name]: FAILED! => {
    "ansible_job_id": "svc.ansible_job_id",
    "attempts": 1,
    "changed": false,
    "finished": 1,
    "msg": "could not find job at 'C:\\Users\\username\\.ansible_async'",
    "started": 1
}
```

And here's the contents of the async job file (formatted for readability):
```json
{
    "ansible_async_watchdog_pid": 3200,
    "exception": "Illegal operation attempted on a registry key that has been marked for deletion. \nAt line:375 char:16\r\n+ ...  $wmi_svc = Get-CimInstance -ClassName Win32_Service -Filter \"name=\u0027$ ...\r\n+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n    + CategoryInfo          : NotSpecified: (:) [Get-CimInstance], CimException\n    + FullyQualifiedErrorId : HRESULT 0x800703fa,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand\r\n\r\nScriptStackTrace:\r\nat Set-ServiceConfiguration, \u003cNo file\u003e: line 375\r\nat \u003cScriptBlock\u003e, \u003cNo file\u003e: line 418\r\n\r\nMicrosoft.Management.Infrastructure.CimException: Illegal operation attempted on a registry key that has been marked for deletion. \r\n   at Microsoft.Management.Infrastructure.Internal.Operations.CimAsyncObserverProxyBase`1.ProcessNativeCallback(OperationCallbackProcessingContext callbackProcessingContext, T currentItem, Boolean moreResults, MiResult operationResult, String errorMessage, InstanceHandle errorDetailsHandle)",
    "results_file": "C:\\Users\\username\\.ansible_async\\878578141507.1272",
    "ansible_job_id": "878578141507.1272",
    "msg": "Unhandled exception while executing module: Illegal operation attempted on a registry key that has been marked for deletion. ",
    "started": 1,
    "_ansible_suppress_tmpdir_delete": true,
    "failed": true,
    "finished": 1
}
```
Here's the exception from above formatted for readability:
```
Illegal operation attempted on a registry key that has been marked for deletion. 
At line:375 char:16
+ ...  $wmi_svc = Get-CimInstance -ClassName Win32_Service -Filter "name='$ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x800703fa,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand

ScriptStackTrace:
at Set-ServiceConfiguration, <No file>: line 375
at <ScriptBlock>, <No file>: line 418

Microsoft.Management.Infrastructure.CimException: Illegal operation attempted on a registry key that has been marked for deletion. 
   at Microsoft.Management.Infrastructure.Internal.Operations.CimAsyncObserverProxyBase`1.ProcessNativeCallback(OperationCallbackProcessingContext callbackProcessingContext, T currentItem, Boolean moreResults, MiResult operationResult, String errorMessage, InstanceHandle errorDetailsHandle)
```

In my case, the error is definitely not that the user has never logged in before. It's also the same whether the user is currently logged in or not.

In any case, seems related to what's happening with `win_shell` but not quite the same error text. Maybe it's a new clue.

**Comment by jhawkesworth** [comment]
@briantist iirc, in later windows versions, windows removes user registry hives when a user disconnects to improve security. There is a gpo you can set to get it not to do this I think in S2012R2. So you might need to change that, temporarily. If it isn't obvious, ping me and I'll dig out the gpo details.

**Comment by briantist** [comment]
> @briantist iirc, in later windows versions, windows removes user registry hives when a user disconnects to improve security. There is a gpo you can set to get it not to do this I think in S2012R2. So you might need to change that, temporarily. If it isn't obvious, ping me and I'll dig out the gpo details.

Thanks @jhawkesworth , I don't think we'd want to disable that, for the same security reasons (doubt our security team would approve it anyway). Plus it happens even when the user is logged in. 

But anyway this actually came out of a discussion with @jborean93 in IRC and I was offering some additional evidence as to the underlying problem. He suspects that for `win_service` at least, this is probably fixed indirectly by the changes in https://github.com/ansible-collections/ansible.windows/pull/34 which remove the dependence on WMI. I'm going to test that out this week or next.

**Comment by jhawkesworth** [comment]
Thanks @briantist good to know

**Comment by jborean93** [comment]
I was hoping I could replicate the win_service issue under an async task but I've tried all sorts of combination of running with async + become, fire and forget and still can't replicate this particular problem. @briantist is the service you are trying to get the info for a special type of service or is this a problem with any builtin ones? Anything special about become, connection user, auth method or something that might help me replicate the problem?

It's a pity as I was hoping that I could use that to potentially figure out the problem here.

**Comment by jborean93** [comment]
No worries appreciate the info and this falls in line with what I’ve seen before, where it only happens when you aren’t ready to debug it :)

**Comment by briantist** [comment]
@jborean93 I've got another instance of `async_status` giving me a similar error. 

This time happens to be using `win_iis_webapppool`:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 176
fatal: [<hostname>]: FAILED! =>
```
```json
{
  "ansible_async_watchdog_pid": 4456,
  "ansible_job_id": "10545895423.2468",
  "attempts": 1,
  "changed": false,
  "finished": 1,
  "msg": "Unhandled exception while executing module: Cannot retrieve the dynamic parameters for the cmdlet. Retrieving the COM class factory for component with CLSID {228FB8F7-FB53-4FD5-8C7B-FF59DE606C5B} failed due to the following error: 800703fa Illegal operation attempted on a registry key that has been marked for deletion. (Exception from HRESULT: 0x800703FA).",
  "results_file": "C:\\Users\\****\\.ansible_async\\10545895423.2468",
  "started": 1
}
```
Stacktrace:
```
Cannot retrieve the dynamic parameters for the cmdlet. Retrieving the COM class factory for component with CLSID {228FB8F7-FB53-4FD5-8C7B-FF59DE606C5B} failed due to the following error: 800703fa Illegal operation attempted on a registry key that has been marked for deletion. (Exception from HRESULT: 0x800703FA).
At line:176 char:9
+ $pool = Get-Item -Path IIS:\AppPools\$name -ErrorAction SilentlyConti ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Item], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : GetDynamicParametersException,Microsoft.PowerShell.Commands.GetItemCommand

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 176
```

It doesn't do this on every machine, but it seems (at least for the moment) to be repeatable on a pair of machines. This particular process actually does a sort of failover so each time it runs the "source" machine is shut down and then started back up at the end, and on the next run it would be the opposite host. I only mention this to say that state like a persistent logged in user would be wiped out on each run and yet it's still repeatable on this pair of machines.

It's running as a service account, but when I try to run similar tasks as my own user account directly from my workstation I don't have this issue.

If there's more info you want gathered while I have a somewhat repeatable situation let me know and I'll see what I can find.

**Comment by briantist** [comment]
The instance referenced above was definitely repeatable but only with a specific user on a specific pair of machines. No roaming profiles used. Same user on other machines (configured the same), and different user on these same machines did not produce the issue.

I don't recall who recommended this in the WWG meeting that one time, but this group policy/registry setting for not forcing the registry to unload on user log out definitely fixed the issue:
https://support.microsoft.com/en-us/help/2287297/a-com-application-may-stop-working-in-windows-when-a-user-logs-off

It's been over a week, no issues or side effects for me (again though we don't use roaming profiles).

**Comment by s-hertel** [comment]
closing at @jborean93's request
