### ISSUE TITLE
stdout_lines doesn't work with quote filter

### ISSUE THREAD

**Issue by perolausson** [ansible/ansible#31036]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Quote filter

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /home/pao/Development/Automation/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION

Standard

##### OS / ENVIRONMENT

Ubuntu 17.04

##### SUMMARY
Using quote filter to process stdout_lines fails with:

##### STEPS TO REPRODUCE

Quote filter works with stdout but does not work with stdout_lines

```yaml
---
 - hosts: localhost
   tasks:
     
     - name: Produce some lines
       shell: date; date
       register: dates

     - debug: msg={{dates.stdout_lines}}
       
     - name: Grab line
       shell: echo {{ dates.stdout_lines | quote }}
 
```

##### EXPECTED RESULTS
Two dates are printed.

##### ACTUAL RESULTS

```
$ ansible-playbook -vvv line_test.yml
TASK [Grab line] **********************************************************************************************************************************************************************
task path: /home/pao/Development/Automation/line_test.yml:11
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 481, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 437, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 659, in do_template
    res = j2_concat(rf)
  File "<template>", line 13, in root
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/filter/core.py", line 126, in quote
    return shlex_quote(a)
  File "/usr/lib/python2.7/pipes.py", line 278, in quote
    return "'" + file.replace("'", "'\"'\"'") + "'"
AttributeError: 'list' object has no attribute 'replace'

fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```

**Comment by sivel** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:

   * The quote filter does not work on stdout_lines

However, however what is happening is that:

   * The `quote` filter does not support lists

We would suggest:

   * Operate on `stdout` or use the `map` filter combined with `quote` such as `stdout_lines|map('quote')`
   * Potentially even using the `to_json` filter or other filters depending on what you expect your output to be

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
