### ISSUE TITLE
Variable substitution in task names

### ISSUE THREAD

**Issue by StuartHarris** [ansible/ansible#3103]
Variables from group_vars are not substituted into task names (like variables passed in other ways):

```
$ cat group_vars/all.yml
%YAML 1.2

---
foo: bar

$ cat hosts
localhost

$ cat play.yml
%YAML 1.2

---
- hosts: all
  gather_facts: no
  tasks:
    - name: test {{foo}}
      debug: msg="test {{foo}}"

$ ansible-playbook -i hosts -c local play.yaml

PLAY [all] ********************************************************************

TASK: [test {{foo}}] **********************************************************
ok: [localhost] => {"msg": "test bar"}

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0

$ ansible-playbook -i hosts -c local play.yaml -e foo=bar

PLAY [all] ********************************************************************

TASK: [test bar] **************************************************************
ok: [localhost] => {"msg": "test bar"}

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

**Comment by mpdehaan** [comment]
This is actually not a bug.

The variable you are using is in inventory scope, so it can't be substituted.

Think about what would happen if you had more than one host.

**Comment by StuartHarris** [comment]
Awesome - thanks Michael.  I understand this better now.

**Comment by hayeah** [comment]
I see. I've made a comment in #943 on a use case.

In an include, I might want 'nginx configure ${app}'. Instead, I have to say "nginx configuration"

If I wanted something more descriptive, I end up having another task doing debug echo

``` yml
# sample play
- name: configure nginx my-app
  debug: msg="configure nginx for my-app"
- include: tasks/nginx.conf app=$my-app
```

Is this idiomatic?

**Comment by maxamg** [comment]
@mpdehaan sorry to drag this from the past. Should the same be true for host_vars? For a single host I'm trying to reuse (include) a common task in several roles, providing a property override that is defined under host_vars. Something like:

```
# host_vars/web@localhost
dirs:
      install_dir: /tmp/web_dir
```

```
# roles/role1/tasks/main.yml
- include: ../../common/tasks/create_default_dirs.yml dir_name="{{ dirs['install_dir'] }}"
```

```
# roles/common/tasks/create_default_dirs.yml
- name: "create {{ dir_name }}"
  file: etc
```

**Comment by dannyman** [comment]
What is a better way to do this, then?

I want to mount an NFS volume based on an inventory-level variable name, like so:

```
  - name: Mount /data/{{env}}
    mount name: /data/{{env}} src={{env}}-nas:/exports/{{env}} fstype=nfs state=mounted
```

So, any host in the inventory that hits this recipe correctly mounts /data/prod, for example ... what is wrong with having the task name substitute the variable?  Or, how should I be doing this differently?

Thanks,
-danny

**Comment by frio** [comment]
Agreed -- I have a playbook along the lines of:

```
- hosts: databases
  roles:
    - mysql-server

- hosts: databases
  tasks: 
    - { include: tasks/provision-database.yml, database: "{{ nagios }}" }
    - { include: tasks/provision-database.yml, database: "{{ nagios_web }}" }
```

And so on and so on.  Without variable substitution in task names, all my output says is `ensure {{ database.name }} exists`; `ensure {{ database.name }}'s schema is imported` and the like.

My design may be wrong, of course, and I'd appreciate any suggestions for doing this better -- but that seems like a reasonably straightforward use case :).

**Comment by msabramo** [comment]
Same problem here. 

``` yaml
# group_vars/all.yml
devpi_server_url: "http://devpi.mycompany.com"
```

``` yaml
# roles/python/tasks/main.yml
- name: "devpi use {{ devpi_server_url }}"
  command: devpi use {{ devpi_server_url }}
  tags:
    - devpi-client
```

Output:

```
18:55:06 O: TASK: [python | devpi use {{devpi_server_url}}] *******************************
18:55:12 O: changed: [192.168.21.254]
```

Interestingly, substitution into `name` works when the var was a parameter to a role.

**Comment by frio** [comment]
Ah @msabramo, I had noticed it working sometimes and was wondering what the delineation was.  My roles also substitute correctly :).

**Comment by yvbeek** [comment]
Would it be possible to detect if the variable is a constant and then substitute?
Or is there another way to define global variables?
There must be a better way than defining `var_files` everywhere.

**Comment by UnquietCode** [comment]
I encounter this when passing parameters to a role, when the input parameter is a variable.

`{ role: SomeRole, param: "{{ some_variable }}" }`

In this case the role cannot make use of `param` in all places because it prints as "{{ some_variable}}". When and where things get replaced seems inconsistent, and that's the trouble really, not that replacement is enabled or disabled in some cases.

**Comment by monasuncion** [comment]
This same thing is happening in my ansible script. I'm trying to make the names more specific and informative but getting the variable name printed out instead:

script:
- name: Git checkout target environment {{ target_branch }}
  sudo: yes
  sudo_user: jenkins
  command: git checkout {{ target_branch }}
  args:
        chdir: '{{ app_repo_dir }}'

output name:

Git checkout target environment {{ target_branch }}

**Comment by sontek** [comment]
Any way we can get this re-opened now that @mpdehaan has stepped down?  I still feel variable expansion of global/host vars is a reasonable request.

**Comment by wyrdangel** [comment]
@sontek I agree and would love to see this re-opened as well.

**Comment by srgvg** [comment]
Imagine you have several hosts, and each host has another different value for the variable that you want to use in the task name.

Which value should be used for the task name?

**Comment by msabramo** [comment]
Well, yeah good point, maybe if it's a variable that can vary by host, then it should punt and say "<multiple values>" or something.

But if the variable is a global variable that doesn't change by host, then it should be able to just use the one.

**Comment by srgvg** [comment]
By very definition, inventory variables are host specific, and not global. Maybe you define a variable top level, in a major group, or even the 'all' group, but when ansible handles the inventory, it retrives variables on that host level. It has no knowledge of where it came from.

So, not global if it is an inventory variable. Even if you wanted to implement such a thing, how would you define a rule to select one out of multiple instances?

If it's a global variable (depending of the type, I believe it gets resolved as you wish, e.g. the --extra -vars)

**Comment by infinityandbian** [comment]
is there a settlement on the best approach to have variable-based task names?

**Comment by hobson** [comment]
+1 for docs on a best practice for variable-based task names

**Comment by iafilatov** [comment]
Was going to rant about how variables are fine in the body of a task, but not in the name of that very task, but then I kind of figured out, why things are the way they are.  I think this is because host(-group) level variables can alter how a task is performed _on a specific host_ (what it does), but they cannot influence _the essence of the task_ (what it is). Name is one of the things that define a task, and conceptually the same result should be accomplished regardless of host specifics. Therefore, the name of the task must make sense for all the hosts where it is performed.

This constitutes a kind of task-centric approach, where tasks are primary and hosts are secondary. Thing is, it's really confusing if you look at it from a host-centric point of view. So I agree that docs should maybe make better effort to describe these concepts.

**Comment by franklinwise** [comment]
+1 for the docs explaining why there are no variable based task names

**Comment by bcoca** [comment]
@franklinwise its an open bug

**Comment by janreges** [comment]
+1

**Comment by vikas027** [comment]
@bcoca Is it an open bug ? I would also like to have this feature. Thanks.

**Comment by msabramo** [comment]
I wish to use variable substitution like this

``` yaml
name: Install {{ item }}
apt: pkg={{ item }} state=latest
with_items:
  - libmemcached-dev 
```

It won't work in the task name though.

**Comment by franklinwise** [comment]
@bcoca - Thank you for clarifying.

**Comment by msabramo** [comment]
Folks have brought up cases where the variable can have multiple values so there's no way to show a single value on the TASK line.
1. Is it possible to print something like "<3 values>" or even print those values if there are less than a certain number? That's a bit more useful than not expanding the variable at all. Even if it just said "<multiple values>", that doesn't give a ton on info but at least it tells the user that ansible realized there was a variable there, but didn't expand it because it could have multiple values. Which would help to clear up confusion hopefully leading to less bug reports about variables not being expanded in task names. 
2. In some cases, there is only one possible value for the variable because it's set in group_vars/all or at the playbook level or from the command line or by set_fact from a previous task. It would be nice if ansible could expand the variable when it's not ambiguous. 

The really weird thing is that I think it works in a small amount of cases - IIRC, it works if the variable was a role parameter but not much else. So that's a little confusing. It might be better if it just always failed and said that variables aren't allowed in task names so it didn't give people false hope. :-)

**Comment by yvbeek** [comment]
Perhaps the variables should be split in two:
- Constants: these variables are the same for all hosts, they can be a direct value (string, number etc.) or a (local) lookup.
- Variables: these variables are host specific

This way there should be no problem to use constants in the name command.

An alternative would be to print out the _unique_ variable values:

```
For example we have three hosts: host1, host2, host3

var1: World
var2: "{{ inventory_hostname }}"

name: Hello {{var1}}
=> Hello World

name: Hello {{var2}}
=> Hello [host1, host2, host3]

or repeat the line

name: Hello {{var2}}
=> Hello host1
=> Hello host2
=> Hello host3
```

**Comment by aioue** [comment]
Referencing related issue: https://github.com/ansible/ansible/issues/10347

**Comment by gadelkareem** [comment]
+1

**Comment by ghost** [comment]
This is weird. My variable gets interpolated...but the {{ }} remains...e.g:

```
- name: "download {{ gemname }} codec gem"
  get_url: "dest...
```

Prints:

```
TASK: [logstash | Deploy {{ logstash_codec_xml }} logstash codec] ********** 
```

I am passing gemname into this task by including it from another role.

**Comment by adeelshahid** [comment]
+1

**Comment by cybertk** [comment]
+1

**Comment by bigHosting** [comment]
+1

**Comment by messiahUA** [comment]
why this issue is closed?

**Comment by adeelshahid** [comment]
I hopefully assume it's part of the next Ansible release.

**Comment by lvii** [comment]
variables could print more better info in task name , hope to add this feature.

**Comment by serdardalgic** [comment]
+1 

I read all the comments here and could not draw myself back from putting another +1 here, this is really annoying when I can not use the variables in the names.

**Comment by EvgeniyV** [comment]
+1

**Comment by puneet2k5** [comment]
+1

**Comment by abadger** [comment]
Note: this is a closed issue so it's not being seen by anyone doing any work on ansible.  If you'd like to open a new issue, probably the first step is to either download one of the ansible-2.0 release candidates from http://releases.ansible.com/ansible/ or checkout from source and run the devel branch: http://docs.ansible.com/ansible/intro_installation.html#running-from-source  We think we've managed to restore the substitution of variables that are available at the time the header is printed (variables that do not depend on which host is being used).  If there's other variables that you think should be available that aren't working you can then file a bug for those.  We'd also take a Pull Request that updates the documentation to make clear which variables are available for the name field and which are not.
