### ISSUE TITLE
Using "--i server," inventory option only loads vars from playbook directory, not current dir

### ISSUE THREAD

**Issue by rsanzante** [ansible/ansible#31041]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME
Variable management

##### ANSIBLE VERSION

```
ansible 2.4.1.0 (stable-2.4 f7b0908315) last updated 2017/09/28 12:32:51 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib/ansible
  executable location = /opt/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

```
This has been tested also with current devel branch.

##### OS / ENVIRONMENT

Ubuntu 17.04

##### SUMMARY

The [documentation states](http://docs.ansible.com/ansible/latest/intro_inventory.html#splitting-out-host-and-group-specific-data) about group_vars and host_vars loading:

> Tip: In Ansible 1.2 or later the group_vars/ and host_vars/ directories can exist in the playbook directory OR the inventory directory. If both paths exist, variables in the playbook directory will override variables set in the inventory directory.

The problem is the way those vars are loaded have changed since 2.3. Before 2.4 when using:
```
ansible-playbook -i "$server," my_playbook.yml
```
Ansible looked for the groups_vars in the current directory plus playbook directory. This makes sense, because this way there's no inventory file, the inventory is passed as a command line parameter, so the inventory directory can be the current path.

This changed in 2.4. Ansible no more looks in the current path, only in the playbook directory.

I understand this situation is not clearly stated, so the behavior of looking in the current path may be a bug that has been fixed in the 2.4 release. In that case this should be a documentation improvement report.

##### STEPS TO REPRODUCE

 Uncompress provided zip file with the following files and directories:
```
├── group_vars
│   └── all
│       └── vars.yml
└── playbooks
    └── my_playbook.yml

```

Contents:
vars.yml
```
---

dummy: foo

```

my_playbook.yml

```
---

- name: Bug report playbook
  hosts: all


  tasks:
    - debug:
        msg: "Dummy var is: '{{ dummy }}'"

```

Execute the playbook with the command:

`ansible-playbook -i <server>, playbooks/my_playbook.yml`

DON'T FORGET the comma after the server name or IP!

##### EXPECTED RESULTS

Ansible should load vars.yml file and execute the playbook happily. This is the output from ansible 2.3:

```
$ ansible-playbook -i myserver, playbooks/my_playbook.yml

PLAY [Bug report playbook] **************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************
ok: [myserver]

TASK [debug] ****************************************************************************************************************************************************************
fatal: [myserver]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dummy' is undefined\n\nThe error appears to have been in '/XXXX/playbooks/my_playbook.yml': line 8, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - debug:\n      ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dummy' is undefined"}
        to retry, use: --limit @/XXXX/playbooks/my_playbook.retry

PLAY RECAP ******************************************************************************************************************************************************************
myserver            : ok=1    changed=0    unreachable=0    failed=1   

```

##### ACTUAL RESULTS

With Ansible 2.4:
```
$ ansible-playbook -i myserver, playbooks/my_playbook.yml

PLAY [Bug report playbook] **************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************
ok: [myserver]

TASK [debug] ****************************************************************************************************************************************************************
fatal: [myserver]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dummy' is undefined\n\nThe error appears to have been in '/XXXX/playbooks/my_playbook.yml': line 8, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - debug:\n      ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dummy' is undefined"}
        to retry, use: --limit @/XXXX/playbooks/my_playbook.retry

PLAY RECAP ******************************************************************************************************************************************************************
myserver            : ok=1    changed=0    unreachable=0    failed=1   

```

**Comment by rsanzante** [comment]
[ansible_issue_31041.zip](https://github.com/ansible/ansible/files/1340816/ansible_issue_31041.zip)

Zip with files to reproduce the issue.

**Comment by bcoca** [comment]
I'll update the docs, it was never meant to use the 'current directory' as this poses security issues i.e `cd /tmp && ansible-playbook ~/send_secrets.yml`. 

I'll update porting guide and changelog

**Comment by larede** [comment]
I have exactly the same problem
