### ISSUE TITLE
commit b8a66ce breaks lookup plugins when already usedwith roles looking for files outside the roles structure

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#3104]
Basically, it only looks for files within the roles/x/files dir, and not (anymore) in the playbook path, which breaks current playbooks.

*\* running first_found with some debug print statements, I saw it loop twice through the same various paths beneath the roles dir, and not looking at paths outside the roles dir.

(on a sidenote, when using a lookup plugin with the template module, it still looks into the files/ dir, nog the templates/d dir, not sure that's a bug though)

some basic example showing the problem: 

``` bash
serge@goldorak:~/tmp$ tree
.
|-- files
|   |-- a
|   `-- b
|-- main.yml
`-- roles
    `-- test
        `-- tasks
            `-- main.yml

4 directories, 4 files
serge@goldorak:~/tmp$ cat main.yml roles/test/tasks/main.yml 
- hosts: localhost
  gather_facts: false
  roles:
  - test
- copy: src={{item}} dest=/tmp
  with_fileglob:
  - files/*
```

testing with ansible before the said commit works:

``` bash
serge@goldorak:~/tmp$ (cd ~/src/ansible; git co devel~11 2>/dev/null); ansible-playbook main.yml -v

PLAY [localhost] ************************************************************** 

TASK: [copy src= dest=/tmp] *************************************************** 
ok: [localhost] => (item=/home/serge/tmp/files/b) => {"changed": false, "gid": 1000, "group": "serge", "item": "/home/serge/tmp/files/b", "mode": "0664", "owner": "serge", "path": "/tmp/b", "size": 0, "state": "file", "uid": 1000}
ok: [localhost] => (item=/home/serge/tmp/files/a) => {"changed": false, "gid": 1000, "group": "serge", "item": "/home/serge/tmp/files/a", "mode": "0664", "owner": "serge", "path": "/tmp/a", "size": 0, "state": "file", "uid": 1000}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

Testing with latest devel: it skips the task as the result of the lookup plugin is an empty list:

``` bash
serge@goldorak:~/tmp$ (cd ~/src/ansible; git co devel); ansible-playbook main.yml -v
Previous HEAD position was 7f0e89a... Explain when statements with |failure and |success.
Switched to branch 'devel'

PLAY [localhost] ************************************************************** 

TASK: [copy src= dest=/tmp] *************************************************** 
skipping: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=0    changed=0    unreachable=0    failed=0   
```

**Comment by srgvg** [comment]
as per irc, @mpdehaan  told me "paths are relative, you can 'climb out' of the roles structure, it does not magically look in two locations" so the previous report is not really an issue

in the mean time I documented another broken behaviour, that doesn't involves roles:

(I added some print statements to `lib/ansible/utils/__init__.py` (basedir, given) and to `lib/ansible/runner/lookup_plugins/fileglob.py` (term & dwimmed) to debug)

``` bash
cat main.yml 
- hosts: localhost
  gather_facts: false
  tasks:
  - include: tasks/ssh_authorized_keys.yml sshauthuser=someuser keypath=files/ssh_keys/acd/* 
# Configureer ssh authorized_keys for ${sshauthuser}
```

``` bash
cat tasks/ssh_authorized_keys.yml 

- name: Voeg ssh keys toe van de Systeembeheerders aan ACD servers
  action: authorized_key user=${sshauthuser} key="{{ lookup('file', item ) }}" state=present
  with_fileglob:
  - $keypath
  tags: ssh_keys
```

``` bash
serge@goldorak:~/tmp$ ansible-playbook main.yml 
basedir,given =  . tasks/ssh_authorized_keys.yml

PLAY [localhost] ************************************************************** 

TASK: [Voeg ssh keys toe van de Systeembeheerders aan ACD servers] ************ 
term =  files/ssh_keys/acd/*
basedir,given =  /home/serge/tmp/tasks/../files files/ssh_keys/acd/*
dwimmed =  /home/serge/tmp/files/files/ssh_keys/acd/*
skipping: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=0    changed=0    unreachable=0    failed=0   
```

So basedir gets `basedir = /home/serge/tmp/tasks/../files` which seems to come from that new code?
Whereas with ansible before said commit, I get 
`basedir,given =  . /home/serge/tmp/files/ssh_keys/acd/user1.pub`

**Comment by mpdehaan** [comment]
Yep, can't really have it both ways.   Most people want basedirs the way described above relative to the file, as that makes more sense.

Really not a lot of people using with_fileglob and the like, so I expect the disruption to be minimal.

As for the other, it seems the objection is the "../" so I can call os.path.abspath. -- doing that shortly.

**Comment by srgvg** [comment]
the objection is "../files" that gets added, not just "../":

`basedir,given =  /home/serge/tmp/tasks/../files files/ssh_keys/acd/*`

So I get here 2x 'files/':

`dwimmed =  /home/serge/tmp/files/files/ssh_keys/acd/*`

**Comment by mpdehaan** [comment]
'files' is added such that it works like 'files' in roles.

That is, if you include a task, you do not have to specify something comes from 'files', but that it will look there automatically if the subdirectory exists. 

This seemed like something lots of people would be asking for if it did not already do that.

I am inferring the directory segment 'files' was already in your 'keypath'?

This seems to say your keypath should just not include 'files' in it.

**Comment by srgvg** [comment]
I'm not sure hardcoding files/ here is a good idea. i expect this will break for more users than you seem to think.
Also, using lookup plugins with templates, templates need to be stored in files/ and not templates/ now.

You might want to document all of this, as it's pretty confusing, and inconsistent.

**Comment by mpdehaan** [comment]
I don't think it's confusing, and no, not that many people are using lookup
plugins.  Those that are really would expect roles to load things relative to the role.

We either fix this now or we do not fix it.  The time is now.

As for with_template, we really shouldn't even document it, and I'm not really sure why we ever included it.  It's weird and hardly anyone is using it.  I'm ok if it has a bit of a quirk to it.

**Comment by srgvg** [comment]
- I meant, it's inconsistent to not have to mention 'files/' when _not_ using roles.
- I was talking about using the template module, combined with_ (file) lookup plugins, not the template-lookup-plugin. (such to have to put the sources to the template module in files/ and not in templates/)

**Comment by mpdehaan** [comment]
It adds on the 'files/' path only when the 'files/' directory is present,
otherwise it does not use the files path.

Hmm, point noted on second part, but there's no way for the system to know
that is what you are trying to do, and I do think it's a minority case.
