### ISSUE TITLE
ignore_errors doesn't work with copy

### ISSUE THREAD

**Issue by bryanlarsen** [ansible/ansible#3107]
```
- copy: src=../../../../shared/secrets.json dest=/srv/clara/shared/secrets.json backup=yes
  ignore_errors: yes
```

fails with

```
fatal: [127.0.0.1] => input file not found at /home/rof/clara/shared/secrets.json or /shared/secrets.json

FATAL: all hosts have already failed -- aborting
```

original discussion:  https://groups.google.com/forum/?fromgroups#!topic/ansible-project/lVPeBJftHBo

**Comment by bcoca** [comment]
ignore_errors normally applies to the target host, it doesn't expect that
the local side is broken.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
Correct.

This is a great place to use "with_first_found" to identify the file to use, or do a local_action test (the stat module in 1.3 is good) to see if the file is there.

I think missing input is more serious than a remote error and probably should not be ignored by this, so I am going to close this ticket.

**Comment by ypid** [comment]
Could this then be implemented as parameter for the copy module instead? Might come in handy …
