### ISSUE TITLE
except Exception preventing pdb to enter post-mortem mode

### ISSUE THREAD

**Issue by JulienPalard** [ansible/ansible#31086]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bin/ansible

##### ANSIBLE VERSION

```
  ansible 2.4.0.0 (detached HEAD d14467b029) last updated 2017/09/29 10:48:35 (GMT +200)
  config file = /home/julien/meltygroup-ansible/ansible.cfg
  configured module search path = ['/home/julien/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/julien/ansible/lib/ansible
  executable location = /home/julien/.venvs/meltygroup-ansible/bin/ansible
  python version = 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]

```

##### SUMMARY

The `except Exception` in [bin/ansible](https://github.com/ansible/ansible/blob/v2.4.0.0-1/bin/ansible#L128) prevents pdb to enter post-mortem mode on exception, as the exception is handled.

##### STEPS TO REPRODUCE

Manually add a `raise Exception()` (so it's still reproductible after the actual bug I found is fixed) at the top of the try statement and run:

```
python3 -m pdb /path/to/ansible/bin/ansible-playbook -vvvv playbook.yml
```

##### EXPECTED RESULTS

I expected `pdb` to enter post-mortem state so I can easily debug what happend, like:

```
$ python3 -m pdb /path/to/ansible/bin/ansible-playbook -vvvv playbook.yml
> /path/to/ansible/bin/ansible-playbook(21)<module>()
-> from __future__ import (absolute_import, division, print_function)
(Pdb) c
[…redacted lots and lots of stacktaces…]
TypeError: string indices must be integers
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /path/to/ansible/lib/ansible/plugins/inventory/__init__.py(86)populate_host_vars()
-> self.inventory.set_variable(host, k, variables[k])
(Pdb) p variables
'ansible_host=62.210.89.103'
(Pdb) p k
'a'
(Pdb) 
```

This way my issue is really easy to diagnose, post-mortem debugging is cool.

##### ACTUAL RESULTS

As the exception was expected, `pdb` didn't see it, and just restarted the program, as documented:

```
[…same as expected up to here…]
TypeError: string indices must be integers
The program exited via sys.exit(). Exit status: 250
> /path/to/ansible/bin/ansible-playbook(21)<module>()
-> from __future__ import (absolute_import, division, print_function)
(Pdb) 
```

**Comment by bcoca** [comment]
I'm not sure what you are asking for, if it is for removal of the exception capture, I would be against it. 

Anyone running `pdb`  certainly has this skills to comment that code out, but non-python programmers would be 'greeted' with a (to them) incomprehensible stacktrace.

**Comment by JulienPalard** [comment]
I totally agree, removing it is not the best solution. I'd be more for a kind of `if cli.options.verbosity > 2: raise` to re-raise the exception and let Python display the stacktrace instead of printing it with `traceback.format_exc()`.

**Comment by Akasurde** [comment]
Closing this issue as PR #31114 is merged. If issue persists, please feel free to re-open.
