### ISSUE TITLE
dig plugin docs misformatted

### ISSUE THREAD

**Issue by wenottingham** [ansible/ansible#31104]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
dig lookup plugin

https://docs.ansible.com/ansible/devel/plugins/lookup/dig.html

##### ANSIBLE VERSION
N/A

##### SUMMARY

![screenshot from 2017-09-29 11-04-23](https://user-images.githubusercontent.com/5208768/31022191-05f92b78-a506-11e7-9618-5ba981792d3c.png)

**Comment by s-hertel** [comment]
cc @dharmabumstead

**Comment by prasadkatti** [comment]
fixed by 43cbcbc

**Comment by bcoca** [comment]
closing as per above
