### ISSUE TITLE
Pipelining seems to be disabled since Ansible 2.4

### ISSUE THREAD

**Issue by PaulMougel** [ansible/ansible#31125]
This issue is related to https://github.com/ansible/ansible/issues/31091 , which was closed yesterday. I investigated a bit, tried my best to test on multiple Ansible versions with the same tasks. I feel that pipelining behavior has changed between Ansible 2.3 and recent releases, starting at 2.4 and affecting also devel.

Let me know if you need more information or if I missed something. I'll be glad to help!

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
SSH Pipelining.

##### ANSIBLE VERSION
Ansible 2.3 is not affected, Ansible 2.4 and greater (most notably devel, ran straight from source) are affected.

Here is an example with Ansible 2.4, straight from source:
```
$ git checkout stable-2.4
$ source hacking/env-setup
$ ansible --version
ansible 2.4.1.0 (stable-2.4 6945f6d3b2) last updated 2017/09/30 14:39:20 (GMT +200)
  config file = None
  configured module search path = [u'/Users/pmougel/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /private/tmp/ansible/lib/ansible
  executable location = /private/tmp/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT
My machine: Mac OS Sierra 10.12.6 (16G29).
Remote: Debian GNU/Linux 8

##### SUMMARY

Enabling pipelining does not work on Ansible 2.4+.

##### STEPS TO REPRODUCE

*See [this gist](https://gist.github.com/PaulMougel/a00997b4ac9757c653674d65e6b6c1a4)* for the full log.

Basically: default ansible configuration, test with `ANSIBLE_SSH_PIPELINING=False` and `ANSIBLE_SSH_PIPELINING=True` the following command:

```
ansible -vvv -i /tmp/my-host my-host.com -m shell -a 'echo ok'
```

On Ansible 2.3, the expected behavior matches the actual results:
- If pipelining is disabled, 4 `EXEC ssh` and one `EXEC sftp` commands are launched. It takes around 0.84s to execute the command.
- If pipelining is enabled, only one `EXEC ssh` command is launched. It takes around 0,46s to execute the command.

On Ansible 2.4 and devel:
- If pipelining is disabled, 4 `EXEC ssh` and one `EXEC sftp` commands are launched. It takes around 1s to execute the command.
- If pipelining is disabled, 4 `EXEC ssh` and one `EXEC sftp` commands are launched. It takes around 1s to execute the command.

##### EXPECTED RESULTS

- Similar behavior between Ansible 2.4 & devel and Ansible 2.3.
- No `sftp` commands when pipelining is enabled, as in Ansible 2.3
- Thus, shorter execution time when pipelining is enabled, as show in Ansible 2.3

##### ACTUAL RESULTS

Activating the pipelining option does not seem to have any effect.

**Comment by StephanZaat** [comment]
#30760 Shows similar behaviour

**Comment by abadger** [comment]
Workaround:  Looks like ANSIBLE_PIPELINING is working.

@bcoca I looked in base.yml and noticed that there's both ANSIBLE_PIPELINING and ANSIBLE_SSH_PIPELINING and could not see nay link between the two entries.  Could it be that ANSIBLE_SSH_PIPELINING is being overridden by ANSBILE_PIPELINING?

**Comment by ralphie02** [comment]
@PaulMougel Excellent work on this. Hoping to see this fixed (if it is a bug) on the next release

**Comment by PaulMougel** [comment]
@abadger You are correct!

It looks like:
- `ANSIBLE_PIPELINING` works as intended
- `ANSIBLE_SSH_PIPELINING` is ignored
- the `pipelining` option in the `[ssh_connection]` section of the `ansible.cfg` configuration file is ignored as well

**Comment by bcoca** [comment]
@PaulMougel good work tracking this down

@abadger  pushing PR to remove the 'unused configs' ... previously these were 'undocumented' and unused ... sadly I documented them, removing for now as we plan to allow this by transport in the future.

**Comment by PaulMougel** [comment]
Thank you @bcoca for your work and everyone for your quick answers.

~~If I understand correctly, Ansible now only supports:~~
~~- the `ANSIBLE_PIPELINING` environment variable;~~
~~- the `pipelining` option in the `defaults` section of the `ansible.cfg` configuration file.~~

~~Sounds good to me!~~

_Edit: See my last post, this one is incorrect._

**Comment by ralphie02** [comment]
@PaulMougel How do you get `pipelining` option to work in the ansible.cfg?? Mine doesn't seem to take an effect.

`ANSIBLE_PIPELINING=True` in the environment variable works on the other hand

**Comment by bcoca** [comment]
so it seems i was wrong ... the ansible_ssh_ versions should work .. im going to restore those, it seems i had attempted to migrate and consolidate but did it incorrectly. My latest 'fix' just went in the wrong direction.

**Comment by bcoca** [comment]
#31244 should be the correct fix this time, sorry for the confusion.

**Comment by abadger** [comment]
I don't know the precedence the code enforcement but I can see these are
defined in opposite orders (ssh level vs connection level).  Is that right?

**Comment by bcoca** [comment]
within a source (i.e ini), last defined wins, but that only affects if both are defined at same time

**Comment by PaulMougel** [comment]
Thank you everyone! @bcoca your latest commit fixes my issue, thank you very much.

If anyone finds this issue later and want to enable pipelining:

- If you are using `ansible.cfg`, either set `pipelining=True` in the  `[connection]` or `[ssh_connection]` section
- if you are using environment variables, either set `ANSIBLE_PIPELINING=True` or `ANSIBLE_SSH_PIPELINING=True`

**Comment by tkeeler33** [comment]
What is the proper way to set this directly in Python? I have added `pipelining=True` to my options but it does not appear to be using pipelining. Setting the environment variable works though.

**Comment by ZhilinS** [comment]
@tkeeler33 I had the same issue and I found that the problem was with upgrading ansible
`ansible --version` showed `ansible 2.4.1.0`, but the symlink in `/usr/local/bin/ansible` was targeting at 2.4.0 package
Long story short, just try to delete ansible and install it again.

**Comment by tkeeler33** [comment]
Hmm i'm at `2.4.2.0` and still having this problem... 

More specifically I need to be able to dynamically turn on/off pipelining in my python script which is why I can't use the `ANSIBLE_PIPELINING` environment variable or `ansible.cfg`. Here is what I'm currently doing:

```python

Options = namedtuple('Options', ['connection', 'module_path', 'forks',
                'become', 'become_method', 'become_user', 'check',
                'private_key_file', 'ssh_pass', 'remote_user', 'diff', 'ssh_extra_args',
                'pipelining'])

self.options = Options(connection='ssh', module_path=None, forks=100, become='yes', \
become_method='sudo', become_user='root', check=False, private_key_file=private_key_file, \
remote_user=remote_user, ssh_pass=ssh_pass, diff=False, ssh_extra_args=ssh_extra_args, \
pipelining=True)

tqm = TaskQueueManager(
                inventory=self.inventory,
                variable_manager=self.variable_manager,
                loader=self.loader,
                options=self.options,
                stdout_callback=self.results_callback,
            )
result = tqm.run(self.play)
```
but `pipelining=True` has no effect.

**Comment by zakabluk** [comment]
Hi! I have same problem for ansible 2.4.2.0.  I resolved problem as:
added in ansible.cfg an option   pipelining=True .
Can you explain me, why we have error? And what will be in future? 

My case:
I launched my playbook and got error:
`fatal: [10.6.220.125]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an                                                       unprivileged user (rc: 1, err: chown: changing ownership of ‘/tmp/ansible-tmp-1516305715.98-191373091817149/’: Operation not permit                                                      ted\nchown: changing ownership of ‘/tmp/ansible-tmp-1516305715.98-191373091817149/command.py’: Operation not permitted\n}). For info                                                      rmation on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}`

**Comment by abadger** [comment]
This is a closed bug report.  We seldom s see new comments on closed bug
reports.  If you think you are still experiencing this big, please open a
new ticket.

**Comment by Richard-Foo** [comment]
An important detail for others that may stumble across the same issue (since this bug report is high in the search results)...  In the docs, pipelining = True is described as a feature unique to OpenSSH.  Ansible will work without OpenSSH installed, but pipelining will not.

In my case, SSH was excluded from a minimal OS install.  Installing OpenSSH accelerated my playbook from 250 seconds to 70 and went from 75 SSH connections to 1.
