### ISSUE TITLE
sudo: sorry, you must have a tty to run sudo

### ISSUE THREAD

**Issue by johnjelinek** [ansible/ansible#31131]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
paramiko pty

##### ANSIBLE VERSION

```
ansible --version
ansible 1.9.4
  configured module search path = None
```

##### CONFIGURATION
```
[defaults]
host_key_checking = False
local_tmp = /tmp/ansible
timeout = 300
transport = paramiko

[paramiko_connection]
pty=True
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
This works in `2.4.0.0`, but for `1.9.4`, I get the message: `sudo: sorry, you must have a tty to run sudo`.

##### STEPS TO REPRODUCE
If a server has `Defaults:    requiretty` in `/etc/sudoers`

```yaml
---
- hosts: all
  gather_facts: no

  tasks:
  - name: restart service
    command: sudo /sbin/service service restart
```
(I can't use the service module because of environmental constraints).

This will result in a failure with the message: `sudo: sorry, you must have a tty to run sudo`.

##### EXPECTED RESULTS
I expected success without needing to change the `requiretty` setting

##### ACTUAL RESULTS
```
<server> ESTABLISH CONNECTION FOR USER: user on PORT 22 TO server
<server> REMOTE_MODULE command sudo /sbin/service service restart
<server> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1506787787.55-264508601443223 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1506787787.55-264508601443223 && echo $HOME/.ansible/tmp/ansible-tmp-1506787787.55-264508601443223'
<server> PUT /var/folders/m0/frnhv63n43q2r9lzdy045kl4h1v2p3/T/tmpY8s0YQ TO /home/user/.ansible/tmp/ansible-tmp-1506787787.55-264508601443223/command
<server> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/user/.ansible/tmp/ansible-tmp-1506787787.55-264508601443223/command; rm -rf /home/user/.ansible/tmp/ansible-tmp-1506787787.55-264508601443223/ >/dev/null 2>&1'
failed: [server] => {"changed": true, "cmd": ["sudo", "/sbin/service", "service", "restart"], "delta": "0:00:00.004718", "end": "2017-09-30 11:10:03.502447", "rc": 1, "start": "2017-09-30 11:10:03.497729", "warnings": []}
stderr: sudo: sorry, you must have a tty to run sudo
```

**Comment by sivel** [comment]
Ansible 1.9 is no longer supported and not receiving any more updates.  Since this works as expected in 2.4 I’m going to close this out.

**Comment by johnjelinek** [comment]
@sivel: thanks for responding. I realize 1.9 is no longer supported, but because of constraints, I can't upgrade right now. Can I get some advice on back porting the feature? In the 1.9 codebase, the feature appears to be there, maybe there's a small patch.
