### ISSUE TITLE
Chown failed selinux vagrant

### ISSUE THREAD

**Issue by MacFlurry** [ansible/ansible#31150]
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME
file module

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/Users/vegasus/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION
RAS

##### OS / ENVIRONMENT
vagrant provisioning VM with Ansible
Vagrant 2.0.0 ( centos/7 box )
##### SUMMARY
Vagrant file configured with nfs like this: 
```
    config.vm.synced_folder "yii2/", "/var/www/html/yii2", create: true, type: "nfs", \
      mount_options: ['rw', 'vers=3', 'tcp'], \
      linux__nfs_options: ['rw','no_subtree_check','all_squash','async']
```
I configured my ansible to be provisioned like this : 
```
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbook.yml"
        ansible.sudo = true
    end
```

my playbook.yml calls roles.
in php7 role, I set my /var/www/html/yii2 to vagrant user and group

vars:
```
$ cat ansible/roles/php7-fpm/defaults/main.yml
---
html_dir: "/var/www/html"
```
set owner and group.
```
$ cat ansible/roles/php7-fpm/tasks/install.yml

- name: Set vagrant owner of webserver directory
  file:
    path: '{{ html_dir }}'
    owner: 'vagrant'
    group: 'vagrant'
    mode: 0775
    recurse: yes
```

And the error:

```
TASK [php7-fpm : Set vagrant owner of webserver directory] *********************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "gid": 20, "group": "games", "mode": "0755", "msg": "chown failed", "owner": "502", "path": "/var/www/html/yii2", "secontext": "system_u:object_r:nfs_t:s0", "size": 128, "state": "directory", "uid": 502}
```

##### STEPS TO REPRODUCE
```
to reproduce:
use the config.vm.synced_folder with nfs as above
use centos/7 as box
use ansible to launch a playbook as above
in you playbook set vagrant as owner and group owner as above
vagrant up
```

##### EXPECTED RESULTS
no errors

##### ACTUAL RESULTS
```
TASK [php7-fpm : Set vagrant owner of webserver directory] *********************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "gid": 20, "group": "games", "mode": "0755", "msg": "chown failed", "owner": "502", "path": "/var/www/html/yii2", "secontext": "system_u:object_r:nfs_t:s0", "size": 128, "state": "directory", "uid": 502}
```

thanks for your help.

**Comment by bcoca** [comment]
Can you try with the following PR https://github.com/ansible/ansible/pull/31217?

it seems we are swallowing the underlying error, this PR will now display such to the user.

**Comment by MacFlurry** [comment]
hello,

where is the "lib/ansible/module_utils/basic.py" in macOS ? ( I'm using macOS 10.13 High Sierra )
cannot find it.
thanks for your help

**Comment by MacFlurry** [comment]
I found it in ./libexec/lib/python2.7/site-packages/ansible/module_utils/basic.py
let me try, I'll be back to you

**Comment by MacFlurry** [comment]
Hello,

I added the PR #31217 

Now this is the error with chown failed : 
```
TASK [php7-fpm : Set vagrant owner of webserver directory] *********************
fatal: [default]: FAILED! => 
{
  "changed": false, 
  "failed": true, 
   "gid": 20, 
   "group": "games", 
   "mode": "0755", 
   "msg": "chown failed: [Errno 1] Operation not permitted: '/var/www/html/yii2'",
   "owner": "502", 
   "path": "/var/www/html/yii2", 
   "secontext": "system_u:object_r:nfs_t:s0",
   "size": 128,
   "state": "directory",
   "uid": 502
}
```

thanks for your help.

**Comment by bcoca** [comment]
ok, so that normally means a permissions issue, i would look at mount, file, selinux, flags, etc to find out which one is restricting your access.

**Comment by admirabilis** [comment]
The thing is, Vagrant creates */var/www/html/yii2* as owned by `vagrant:vagrant`, but it first creates */var/www/html/* first as owned by `root:root`, I don't know if on purpose. I don't understand either why Ansible fails to chown the directory, but running `chown` directly works:

    - name: fix permission of directory created by vagrant
      become: yes
      command: chown '{{ ansible_user_id }}:{{ ansible_user_id }}' /var/www/html/

**Comment by florian-asche** [comment]
wtf

**Comment by bcoca** [comment]
I still need something more to reproduce the issue as the 'chown' failure seems a straight permissions issue

needs_info

**Comment by MacFlurry** [comment]
Hello,
I had since fixed this issue by forcing the `chown`. 
I will close this matter.
Yours sincerely,
MacFlurry

**Comment by MacDada** [comment]
> I had since fixed this issue by forcing the `chown`.

@MacFlurry What do you mean by `forcing`?
