### ISSUE TITLE
ansible-vault on RHEL 6 

### ISSUE THREAD

**Issue by deadmalc** [ansible/ansible#31169]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible-vault
##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.6 (r266:84292, Aug  9 2016, 06:11:56) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]

```

##### SUMMARY

ansible-vault is broken on rhel 6 after ansible 2.4 upgrade
##### STEPS TO REPRODUCE

```
ansible-vault create test
New Vault password: 
Confirm New Vault password: 
ERROR! ansible-vault requires either the cryptography library (preferred) or a newer version of pycrypto in order to function.

```

##### EXPECTED RESULTS

Ansible to require new libraries on install and vault to work
##### ACTUAL RESULTS

```

```

**Comment by alikins** [comment]
Afact, either 'cryptography' or 'pycrypto >= 2.6.1' are required.

What versions of 'cryptography' or 'pycrypto' are installed?

ie, results of:
```
pip show cryptography
pip show pycrypto
rpm -qi python-cryptography
rpm -qi python-crypto

```

**Comment by alikins** [comment]
What was the installation method?

**Comment by deadmalc** [comment]
Installation method was via rpm from the EPEL testing rpm repo. (I also tried the ansible stable repo)
There are two versions of pycrypto:
python-crypto2.6-2.6.1-2.el6.x86_64
python-crypto-2.0.1-22.el6.x86_64

pip shows version 2.0.1

cryptography is not installed or avaliable for RHEL 6
I've used the EPEL testing and the ansible nightly/stable repo with the same result.
ansible (2.4.0.0-2.el6) is showing it requires:
python-crypto
python-crypto2.6
python-keyczar
python-paramiko

**Comment by abadger** [comment]
Can you try rpm -V of the following:
```
rpm -V ansible
rpm -V  python-crypto
rpm -V  python-crypto2.6
```

**Comment by deadmalc** [comment]
Please close ticket, this is going nowhere.
I'm happy to accept that it will not be supported on Centos 6/RHEL 6 as we will be migrating
