### ISSUE TITLE
IOS Modules - Subsequent tasks failing with ignore_errors enabled - device left in config mode

### ISSUE THREAD

**Issue by os4mike** [ansible/ansible#31161]
- Bug Report

Component name
  
All Cisco IOS Modules

ANSIBLE VERSION

        - 2.5.0

##### CONFIGURATION

     - name: Set MAC-MOVE logging to Syslog
        ios_config:
          provider: "{{ provider }}"
          lines:

            - mac address-table notification mac-move
                                                

        ignore_errors: yes

##### OS / ENVIRONMENT
     Linux Ubuntu

##### SUMMARY
    IOS device being left in configuration mode after task Failure and will not run subsequent
    tasks against host. 

    In example specified, legacy host does not contain the ios command-
    'mac address-table notification mac-move' and errors with-

    rtr-om-rt-ts01(config)#mac address-table notification mac-move
                                ^
    % Invalid input detected at '^' marker.

    rtr-om-rt-ts01(config)#

##### ACTUAL RESULTS

TASK [Set MAC-MOVE logging to Syslog] *************************************************************************************************************************
fatal: [rtr-om-rt-ts01]: FAILED! => {"changed": false, "command": "mac address-table notification mac-move", "failed": true, "msg": "mac address-table notification mac-move\r\n                                ^\r\n% Invalid input detected at '^' marker.\r\n\r\nrtr-om-rt-ts01(config)#", "rc": 1}
...ignoring

TASK [Enable SCP] *********************************************************************************************************************************************
fatal: [rtr-om-rt-ts01]: FAILED! => {"changed": false, "failed": true, "msg": "unable to retrieve current config", "stderr": "show running-config\r\n                             ^\r\n% Invalid input detected at '^' marker.\r\n\r\nrtr-om-rt-ts01(config)#", "stderr_lines": ["show running-config", "                             ^", "% Invalid input detected at '^' marker.", "", "rtr-om-rt-ts01(config)#"]}
...ignoring

TASK [Configure CPU and Memory trap thresholds] ***************************************************************************************************************
fatal: [bwy4-om-tplus-ts01]: FAILED! => {"changed": false, "failed": true, "msg": "unable to retrieve current config", "stderr": "show running-config\r\n                             ^\r\n% Invalid input detected at '^' marker.\r\n\r\nrtr-om-rt-ts01(config)#", "stderr_lines": ["show running-config", "                             ^", "% Invalid input detected at '^' marker.", "", "rtr-om-rt-ts01(config)#"]}
...ignoring

**Comment by alikins** [comment]
ping @privateip etc

**Comment by gundalow** [comment]
@os4mike Thanks for this bug. This will be fixed by the connection work in 2.5

**Comment by ganeshrn** [comment]
Fix will be available in 2.4.2beta2 release
