### ISSUE TITLE
Big sections of playbook being missed when upgrading to 2.3.2

### ISSUE THREAD

**Issue by benashton2** [ansible/ansible#31178]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
N/A

##### ANSIBLE VERSION

```
2.3.2.0
```

##### SUMMARY

We use one big playbook that calls different roles based on tags, e.g. 
##### STEPS TO REPRODUCE

Command to run: ansible-playbook --tags=create_logging playbook.yml

```yaml
---

- name: First play
  hosts: localhost
  connection: local
  vars_files:
    - ${our_files}
  roles:
    - { name: role1 , tags: ['always'] }
    - { name: role2 , role_action: create }
    - { name: role2 , role_action: info , tags: ['always'] }

- include: infra_readiness.yml ssh_group=${all_hosts}
  tags: ['always']

- name: Pre-Install
  become: yes
  hosts:
    - ${host_group}
  strategy: free
  gather_facts: true
  tags: ['install']
  roles:
    - { name: common }
```
### role2, action: info
```
- include: get_instances_facts.yml

  - debug: msg="fewer instances found [{{ hosts.instances|length }}] than expected [{{ host_count }}] on stack {{ stack }}"
    when:
      - hosts.instances|length <host_count|int
      - not fail_on_instance_count_mismatch

  - name: Get ASGs Facts
    ec2_asg_facts:
      profile: '{{ aws_profile }}'
      region: '{{ aws_region }}'
      tags:
        "aws:cloudformation:stack-name": '{{ stack }}'
    register: asg_facts
  - set_fact:
      asg_facts: '{{ asg_facts.results }}'

  - name: Populate the group
    add_host:
      name: '{{ item.private_ip_address }}'
      groups: group1
    with_items: '{{ group.instances }}'
    changed_when: false
```

##### EXPECTED RESULTS

Apologies for missing code in examples, had to remove quite a bit.

In 2.2.x which we have been running on for almost a year, the above code runs through fine - when upgrading onto 2.3.x, we are seeing huge bits of code be missed (both from tower and cli) for example, in role2, action:info it would skip straight to 'Populate the group' and not run anything else prior.

I have few theories to why this is happening but have been unable to prove this, something has changed with tags in the new version, for example the create_logging being passed into a playbook with a huge amount of tags is causing issues.

Strategy: free is causing issues although I did take it out from all our code and still had the same problem.

The tasks are being skipped but the output has been changed (have also run this in max debug and there was no skip output)

##### ACTUAL RESULTS

Huge bits of playbook skipped

**Comment by jimi-c** [comment]
Is there anyway you could create a full working example? Trying to piece this together without some semblance of the roles you're using won't be easy.

**Comment by benashton2** [comment]
I was worried that would be the case, I will look at creating a usable example tomorrow.

**Comment by benashton2** [comment]
Hi @jimi-c 

 Sorry for the delay, we have spent some time working through this and have believe we understand the issue. Hopefully you can confirm and possibly advice on a way to best move forward.

```
ansible-playbook playbook.yml --tags="mytag"
```
```- name: First play
  hosts: localhost
  connection: local
  roles:
    - { name: role1 , tags: ['always'] }
    - { name: role2 , role_action: info , tags: ['always'] }
```
**role2, main.yml**
```
---
- include: '{{ role_action | default ("info") }}.yml'

```
**role2, info.yml**
```
---
- include: get_instances_facts.yml
```
**get_instance_facts.yml**
```
- debug: msg="without tag"

- debug: msg="with tag"
  tags: ['mytag']
```

Using the above example, before the first debug inside get_instance_facts.yml would run as the include inside info had been called through the always tag. After upgrading, only the second debug would run when using --tags="mytag".

This snippet from the docs *All of these apply the specified tags to EACH task inside the play, included file, or role, so that these tasks can be selectively run when the playbook is invoked with the corresponding tags.* seems to confirm this.

Does this mean every task inside a playbook should have all relevant tags attached to it?

**Comment by sivel** [comment]
Using your playbook and roles as outlined in https://github.com/ansible/ansible/issues/31178#issuecomment-334462037

I get the following output:

```
$ ansible --version
ansible 2.3.2.0 (detached HEAD c7052b42c7) last updated 2017/10/05 09:56:05 (GMT -500)
  config file = /Users/matt/projects/ansibledev/playbooks/31178/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.6.2 (default, Sep 21 2017, 15:59:27) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]

$ ansible-playbook -v 31178.yml -t mytag
Using /Users/matt/projects/ansibledev/playbooks/31178/ansible.cfg as config file
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] *****************************************************************************************************************************************************************

TASK [role2 : include] ***********************************************************************************************************************************************************
included: /Users/matt/projects/ansibledev/playbooks/31178/roles/role2/tasks/info.yml for localhost

TASK [role2 : include] ***********************************************************************************************************************************************************
included: /Users/matt/projects/ansibledev/playbooks/31178/roles/role2/tasks/get_instances_facts.yml for localhost

TASK [role2 : debug] *************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "without tag"
}

TASK [role2 : debug] *************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "with tag"
}

PLAY RECAP ***********************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0
```

Based on what you are saying, you only see the 2nd debug, and I cannot reproduce this.  I get both. 

I see the same output in 2.2.3, 2.3.2, 2.4.0

**Comment by benashton2** [comment]
Hi @sivel 

Odd, I will have another look at our ansible.cfg and update here if I see anything.

**Comment by jimi-c** [comment]
@benashton2 can you work https://gist.github.com/Shaps/e54482807f5d6f936d793383da1168bf into your example? @Shaps was saying it appeared to be more related to using the loop than tags?

**Comment by Shaps** [comment]
@jimi-c As far as I can tell the `with_together` is parsed before `get_instance_facts.yml` ( which creates the `ose_*` vars ) runs, which obviously results in an undefined variable error. I don't think this can be considered an issue, it's just the way include+loops works. 
In this particular case I believe the fix was to move `get_instances_facts.yml` to a different role/pre_task.

**Comment by benashton2** [comment]
@jimi-c @Shaps Correct, the issue was that the include from line 10-15 was being parsed before the tasks above where we define the facts used for the loop. The fix I used was as below: -

```
- name: Populate the ose_infra group
  include: ose_infra_group.yml
  with_together:
    - '{{ ose_masters.instances }}'
    - '{{ ose_etcd.instances }}'
    - '{{ ose_routers.instances }}'
  when:
    - ose_masters is defined
    - ose_etcd is defined
    - ose_routers is defined
```
This issue can be marked as resolved, one query I would have is how this has changed? e.g. the include with_together snippet being touched before the tasks above, is this due to the new include/import changes? Also surprised the `is defined` conditional is fixing it, does is take this into account when parsing it or am I misunderstanding something?

Thanks for the help.
