### ISSUE TITLE
OSError: [Errno 2] No such file or directory when trying to run ansible-vault view

### ISSUE THREAD

**Issue by rtran58** [ansible/ansible#31226]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- ansible-vault

##### ANSIBLE VERSION
```
root@5782aebefae9:~# ansible --version
ansible 1.9.4
  configured module search path = None
```

##### CONFIGURATION
```
[defaults]
vault_password_file = ~/.vault.pass.txt
```

##### OS / ENVIRONMENT
Ubuntu 14.04 in a docker container

##### SUMMARY
Using ansible-vault, i can create and edit an encrypted file. However, trying to view the same file fails. This works as expected in my local environment. But, when i try to run this command in a docker container, i run into this behavior.

##### STEPS TO REPRODUCE
```
root@5782aebefae9:~# ansible-vault create foo.yml
root@5782aebefae9:~# ansible-vault view foo.yml
ERROR: [Errno 2] No such file or directory
root@5782aebefae9:~# ansible-vault --debug view foo.yml
Traceback (most recent call last):
  File "/usr/local/bin/ansible-vault", line 233, in main
    fn(args, options, parser)
  File "/usr/local/bin/ansible-vault", line 180, in execute_view
    this_editor.view_file()
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/vault.py", line 290, in view_file
    call(self._pager_shell_command(tmp_path))
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

ERROR: [Errno 2] No such file or directory
```

##### EXPECTED RESULTS
I should be able to view contents of the encrypted file

##### ACTUAL RESULTS
System reports "No such file or directory"

**Comment by sivel** [comment]
Ansible 1.9 is no longer supported and not receiving any updates.  Please upgrade to a more recent supported version.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
