### ISSUE TITLE
Ansible local facts not gathered

### ISSUE THREAD

**Issue by dj-wasabi** [ansible/ansible#31239]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
setup

##### ANSIBLE VERSION

```
ansible 2.4.0.0
```

##### CONFIGURATION

DEFAULT_ASK_SUDO_PASS(/Users/wdijkerman/git/vagrant/ansible.cfg) = False
DEFAULT_FILTER_PLUGIN_PATH(/Users/wdijkerman/git/vagrant/ansible.cfg) = [u'/Users/wdijkerman/git/ansible/docker/filters', u'/Users/wdijkerman/git/ansible/elasticsearch/filters']
DEFAULT_FORKS(/Users/wdijkerman/git/vagrant/ansible.cfg) = 5
DEFAULT_HOST_LIST(env: ANSIBLE_HOSTS) = [u'/Users/wdijkerman/git/iwelcome-ansible/etc/host_wrapper']
DEFAULT_MODULE_LANG(/Users/wdijkerman/git/vagrant/ansible.cfg) = C
DEFAULT_MODULE_PATH(/Users/wdijkerman/git/vagrant/ansible.cfg) = [u'/Users/wdijkerman/git/vagrant/Library']
DEFAULT_POLL_INTERVAL(/Users/wdijkerman/git/vagrant/ansible.cfg) = 15
DEFAULT_REMOTE_PORT(/Users/wdijkerman/git/vagrant/ansible.cfg) = 22
DEFAULT_ROLES_PATH(/Users/wdijkerman/git/vagrant/ansible.cfg) = [u'/Users/wdijkerman/git/ansible']
DEFAULT_SCP_IF_SSH(/Users/wdijkerman/git/vagrant/ansible.cfg) = True
DEFAULT_SUDO_USER(/Users/wdijkerman/git/vagrant/ansible.cfg) = root
DEFAULT_TRANSPORT(/Users/wdijkerman/git/vagrant/ansible.cfg) = smart
HOST_KEY_CHECKING(/Users/wdijkerman/git/vagrant/ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/wdijkerman/git/vagrant/ansible.cfg) = False

##### OS / ENVIRONMENT
Ansible is running on Mac OS X SIerra, but the hosts are CentOS 7

##### SUMMARY
When using local_facts, these are always "UNDEFINED". 

##### STEPS TO REPRODUCE

Add in `/etc/ansible/facts.d/` a file named system.fact. Add the following content:

```
{ "host":
    {
        "hostname": "myhost.example.com"
    }
}
```

Executing `ansible -i hosts myhost -m debug -a var=ansible_local.system.host.hostname`  should provide the correct output.

##### EXPECTED RESULTS

It should provide the following output:

```
myhost | SUCCESS => {
    "ansible_local.system.host.hostname": "myhost.example.com"
}
```

##### ACTUAL RESULTS

When executing `ansible -i hosts myhost -m debug -a var=ansible_local.system.host.hostname` it gives the following output:

```
myhost | SUCCESS => {
    "ansible_local.system.host.hostname": "VARIABLE IS NOT DEFINED!"
}
```

**Comment by dj-wasabi** [comment]
I think I made a mistake. Will reopen if I didn't make a mistake. Sorry!

**Comment by indispeq** [comment]
I have the same issue in 2.4.2.0 @dj-wasabi did you find a solution?

**Comment by bcoca** [comment]
@indispeq  he expected `ansible_local.system.host.hostname` but created `ansbile_local.host.hostname`, all my tests show `ansible_local` working fine, if you have an issue please open a new bug with a reproducer.
