### ISSUE TITLE
Ansible Windows Custom Module shows errors

### ISSUE THREAD

**Issue by riponbanik** [ansible/ansible#31281]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```ansible 2.4.0.0
  config file = ./ansible.cfg
  configured module search path = [u'/./lib/windows']
  ansible python module location = /home/rbanik/.local/lib/python2.7/site-packages/ansible
  executable location = /home/rbanik/.local/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### SUMMARY

I have created a custom windows module using powershell to add a windows host file entry. It runs the poweshell script although the parameters passed is wrong order but able to add the entry in the host file but it shows following error.

FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Method invocation failed because [System.Management.Automation.PSCustomObject] \r\ndoes not contain a method named 'ContainsKey'.\r\nAt line:65 char:9\r\n+     if (-not $obj.ContainsKey('changed')) {\r\n+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : InvalidOperation: (ContainsKey:String) [], Paren \r\n   tContainsErrorRecordException\r\n    + FullyQualifiedErrorId : MethodNotFound\r\n \r\n\r\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

Run the module without any error and get parameters in correct order.

##### ACTUAL RESULTS

```

```

**Comment by jborean93** [comment]
What version of Ansible are you running, are you able to share some snippets like how you define `$result`?

**Comment by riponbanik** [comment]
Ansible verion 2.4.0

I have uploaded the code in git -

https://github.com/riponbanik/ansible_win_host

**Comment by jborean93** [comment]
Ok, it looks like in 2.4 this commit https://github.com/ansible/ansible/commit/0e160d5c7eca9aa5275c3f47d05c287a9e81401c will automatically set `changed` on the `$result` object. Unfortunately older practices for Windows module development were set to use a `[PSObject]` which did not contain the method `ContainsKey` and will break with 2.4.

For your code to work with 2.4, you will need to change the following
* When defining the `$result` object, change it from `$result = New-Object psobject` to `$result = @{}`
* Any `Set-Attr $result *` parts can be changed to just `$result.*`, e.g. `Set-Attr $result changed $true` will now be `$result.changed = $true

You can see the latest standards that we are using for windows modules here http://docs.ansible.com/ansible/2.4/dev_guide/developing_modules_general_windows.html#windows-new-module-development.

**Comment by riponbanik** [comment]
Thanks a lot for your very quick response. It resolves the issue.

**Comment by jborean93** [comment]
No worries, I am going to close the issue.

**Comment by riponbanik** [comment]
@jborean93 I have also updated my github repo with the remove functionality as well and tested both works. Would like to have your suggestion to submit it to ansible core extra if not is not submitted already. Thanks Again.

**Comment by jborean93** [comment]
I'm not sure this would be merged into Ansible, it looks like the same actions can be some with `win_lineinfile`.

**Comment by riponbanik** [comment]
@jborean93  Thanks for your feedback.  For future

 1.what are the process and stages for submission?

2. how do i enable check and diff in powershell module?

3.  Is there any way to make my script reusable e.g. run the script locally as well as a ansible module?  

4. Any plan to support DSC?

**Comment by riponbanik** [comment]
@jborean93 sorry asked too many questions, just one- how do i enable check and diff in powershell module?

**Comment by jborean93** [comment]
Hey @riponbanik, have a look at the page I sent you around developing Windows modules. The example in there shows you how to determine whether Ansible is running with check mode or diff mode. It also gives you info on how to debug Ansible modules on a Windows server which is quite useful for larger and more complex modules. For the DSC stuff, have a look at [win_dsc](http://docs.ansible.com/ansible/2.4/win_dsc_module.html)

**Comment by riponbanik** [comment]
@jborean93 Thanks I have go the other info from the page, was not sure how to make check mode enabled in Powershell, seems to be get auto enabled now.

**Comment by jborean93** [comment]
Check mode is enabled by your code, Ansible can pass in info as to whether Ansible is running in check mode but you need to put in the logic to either not run a command that will change something or, if supported, use the `-WhatIf` parameter that is available on some powershell cmdlets.
