### ISSUE TITLE
if hosts is localhost or 127.0.0.1 don't require it to be in inventory

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#3129]
If the host pattern is explicitly matching only localhost or 127.0.0.1 for a connection localhost play and the host is not in inventory, then temporarily add it to RAM inventory for purposes of executing the play

**Comment by mpdehaan** [comment]
Make sure it isn't matched by the all group UNLESS the host was explicitly added to inventory in which case it SHOULD be matched by the all group.

**Comment by mpdehaan** [comment]
See also #3687 so closing that one

**Comment by jdutton** [comment]
:+1:

**Comment by sivel** [comment]
One other thing I would like to see in addition to just "implying" localhost, is to set ansible_python_interpreter automatically for localhost, using sys.executable.  (And of course ansible_connection=local)

When working in a virtualenv, setting ansible_python_interpreter is required, or at least a good idea.

The other option, and maybe we implement both, is an easy way to override ansible_python_interpreter for localhost, that avoids having to drop localhost back into inventory.
