### ISSUE TITLE
ansible2.4 broke Inventory class and didn't update examples

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#31292]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
2.4.0.0
```

##### SUMMARY
It seems that the refactorings made around Inventory were not tested well enough because examples were not updated and were rendered useless, see https://github.com/ansible/ansible/blob/devel/examples/scripts/uptime.py#L6

Even the most basic linting on examples source code could have uncovered that the refactorings broke them as they would sport the missing import.

So there are two issues here: **regression** and the **lack of basic gating** that allowed this to happen, are the example in exclude for linting? ... that's clearly not a good practice. 
 
##### STEPS TO REPRODUCE

```python
from ansible.inventory import Inventory
```

##### EXPECTED RESULTS
Sucess?

##### ACTUAL RESULTS

```
ImportError: cannot import name Inventory
```

**Comment by sivel** [comment]
resolved_by https://github.com/ansible/ansible/pull/31246
