### ISSUE TITLE
with_items is evaluated before a task's conditional

### ISSUE THREAD

**Issue by zonk1024** [ansible/ansible#3134]
I have a conditional that I use to tell the ec2 module whether to run or not, and if it does it registers it's output. After that I have another task with the same condition in it's conditional that uses the registered output of the ec2 module.  Problem is that when the condition evals to false the playbook bombs out b/c the 2nd task tries, and fails, to process the list in with_items before checking to see if it should even run.

**Comment by mpdehaan** [comment]
Please supply a playbook that demonstrates this problem and the syntax you are using, along with the output of ansible --version.

**Comment by mpdehaan** [comment]
Ok so seeing this on the list today (I think) the conditional is there to decide whether to execute the task or not, and your with_items included item, which was not defined.

Can you paste the segment of the playbook if this is not the case?

The conditional is not used for each item in the item loop.

**Comment by ghost** [comment]
Was this fixed? Or why was it dropped? I run into this problem all the time. super annoying that I can't use with_items on a conditionally-available variable without jumping though hoops to ensure its declared as an empty list if not present.

```
with_items: "{{ cond_variable | default([]) }}" # Actually this doesn't work at all

with_items: "cond_variable[key] | default([])" # my new lead, Nevermind, actually also doesn't work at all. Am I going crazy or what.
```

Seems to work, but I never trust using templates to pass a variable correctly and not a string :|

**Comment by bridavis** [comment]
I'm seeing this error as well. Is there a fix, and if so, which Ansible version?
