### ISSUE TITLE
How to pass string into Ansible Variable array

### ISSUE THREAD

**Issue by rohingupta** [ansible/ansible#31349]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION
2.7.5 

##### SUMMARY
<I have the below list of variables

abc: 3V4L-CA6S-UHJ8
xyz: 06342107

MC_INI_VAR: " {{abc}} {{xyz}}"

This has been invoked in playbook using the below rule
 name : Starting generration process
  become: yes
  become_user: centos
  shell : java -jar run.jar {{MC_INI_VAR}}
  register: out
- debug: var=o

At the remote machine the transformed command was
java -jar run.jar  3V4L-CA6S-UHJ8 1688647

If I just change the variable in all.yml to
abc: 3V4L-CA6S-UHJ8
xyz: "06342107"

At the remote machine the transformed command was
java -jar run.jar  3V4L-CA6S-UHJ8 06342107

My problem is that if xyz=06342108; it is sent correctly without quotes

Also, this value is getting populated from another script which does not add quotes. I am reading about issues of handling long int in ansible variable and I need to understand on how can I fix this issue.

I do not wish to send this in quotes and and i have tried solutions like 
MC_INI_VAR: " {{abc | string}} {{xyz}}" but it ain't worked
>

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
