### ISSUE TITLE
Compare two hosts before/after copy?

### ISSUE THREAD

**Issue by jhtapp76** [ansible/ansible#31356]
Does anyone know of a way to compare the configuration of two separate hosts before and/or after a deployment? Meaning, I want to conduct a diff on numerous files in a pre-deployment and post deployment state to ensure there are no variances between the destination hosts. 

Thanks for any tips.

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
