### ISSUE TITLE
No file created on the localhost when running by Tower

### ISSUE THREAD

**Issue by fhamed** [ansible/ansible#31359]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Tower

##### ANSIBLE VERSION
2.3.2.0

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
CentOS 7

##### SUMMARY
Trying to create a file on the localhost. Running the playbook from command line creates the file as expected.
Running the same playbook from Tower does not.

##### STEPS TO REPRODUCE
``` 
- name: create a file on the localhost
    copy:
      content: ""
      dest: /tmp/test.txt
      force: no
      mode: 0666
```
##### EXPECTED RESULTS
A new file on the /tmp directory when running the playbook from Tower

##### ACTUAL RESULTS
Output of Tower:

Using module file /usr/lib/python2.7/site-packages/ansible/modules/files/stat.py
<192.168.26.121> ESTABLISH LOCAL CONNECTION FOR USER: awx
<192.168.26.121> EXEC /bin/sh -c 'echo ~ && sleep 0'
<192.168.26.121> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1507212675.73-99099831602473 `" && echo ansible-tmp-1507212675.73-99099831602473="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1507212675.73-99099831602473 `" ) && sleep 0'
<192.168.26.121> PUT /tmp/tmp0KZV3P TO /var/lib/awx/.ansible/tmp/ansible-tmp-1507212675.73-99099831602473/stat.py
<192.168.26.121> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1507212675.73-99099831602473/ /var/lib/awx/.ansible/tmp/ansible-tmp-1507212675.73-99099831602473/stat.py && sleep 0'
<192.168.26.121> EXEC /bin/sh -c '/usr/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1507212675.73-99099831602473/stat.py; rm -rf "/var/lib/awx/.ansible/tmp/ansible-tmp-1507212675.73-99099831602473/" > /dev/null 2>&1 && sleep 0'
<192.168.26.121> EXEC /bin/sh -c 'echo ~ && sleep 0'
<192.168.26.121> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1507212677.07-122723910382946 `" && echo ansible-tmp-1507212677.07-122723910382946="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1507212677.07-122723910382946 `" ) && sleep 0'
<192.168.26.121> PUT /tmp/tmpqEi9QI TO /var/lib/awx/.ansible/tmp/ansible-tmp-1507212677.07-122723910382946/source
<192.168.26.121> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1507212677.07-122723910382946/ /var/lib/awx/.ansible/tmp/ansible-tmp-1507212677.07-122723910382946/source && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/files/copy.py
<192.168.26.121> PUT /tmp/tmpvgGZB1 TO /var/lib/awx/.ansible/tmp/ansible-tmp-1507212677.07-122723910382946/copy.py
<192.168.26.121> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1507212677.07-122723910382946/ /var/lib/awx/.ansible/tmp/ansible-tmp-1507212677.07-122723910382946/copy.py && sleep 0'
<192.168.26.121> EXEC /bin/sh -c '/usr/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1507212677.07-122723910382946/copy.py; rm -rf "/var/lib/awx/.ansible/tmp/ansible-tmp-1507212677.07-122723910382946/" > /dev/null 2>&1 && sleep 0'

**Comment by nitzmahone** [comment]
You should probably use your support contact for Tower to get this figured out- there's not enough information here to nail this down to a core issue- it's probably Tower configuration related...
