### ISSUE TITLE
Feature Request: configurable entry-point for a role's tasks.

### ISSUE THREAD

**Issue by b6d** [ansible/ansible#3136]
My Problem:

I have a role, say "webserver", which is set up with the tasks in roles/webserver/tasks/main.yml.

On some occasions I'd like to manually invoke cretain tasks that have little to do with setting up the system itself (like "make a backup right now") or tasks I'd rather not run every time I invoke ansible-playbook (like "upgrade the
OS and reboot")

I don't know a good way to implement this -- all solutions I can thinkof seem a bit ugly to me.

Current solutions I can think of:
- Tagging: "upgrade_and_reboot" could be a tag. Disadvantage: If I _don't_ want   to upgrade and reboot (the normal case), I have to invoke ansible-playbook like this: `ansible-playbook webserver.yml --tags some_tag,some_other_tag,...`, listing all tags that _aren't_ `upgrade_and_reboot`
- Separate roles for these tasks ("webserver_backup_now",  "webserver_upgrade_and_reboot") having the necessary tasks listed in their  main.yml-files. Disadvantages: 
  - This might lead to a lot of roles
  - The new roles can't reference the files of the webserver-role without resorting to a lot of `../`'s
  - Intuitively, for me these things should not be roles in the first place.
- stand-alone-playbooks ("webserver_backup_now.yml", ...), referencing their task-files and var-files and handlers explicitly. Disadvantage: All the nice features of roles get lost.

Maybe making the entry point for a role's tasks (currently main.yml) configurable with main.yml being the default could be helpful here, maybe like this:

_webserver_backup_now.yml:_

```
- hosts: webservers
  roles:
    - role: webserver 
      tasks: backup.yml # this would call roles/webserver/tasks/backup.yml 
                        # instead of main.yml
```

While the standard webserver playbook would still look like this:

_webserver.yml:_

```
- hosts: webservers
  roles:
    - webserver # this would still call roles/webserver/tasks/main.yml 
```

If something like this can't already be done at the moment, I'd welcome such a feature.

**Comment by mpdehaan** [comment]
Hi!

I'm not going to implement this feature as it's not very well defined (and we already have tags and task includes and lots of ways this can be done), but if you would like to have a discussion about how to solve this modelling problem please stop by the Google Group and I would be glad to talk about it.

**Comment by b6d** [comment]
Thanks, I will stop by the Google group.
