### ISSUE TITLE
Will there be an include_handler added soon?

### ISSUE THREAD

**Issue by cjimison** [ansible/ansible#31380]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

include_handler

##### ANSIBLE VERSION

```
2.4+
```

##### SUMMARY

With Ansible 2.4 the - include command was deprecated and I found that the following commands were added:

include_playbook
include_tasks

However I cannot find an include_hander

What is the correct way to include handlers now?  Documentation doesn't have any info and shows the old system that uses include

##### STEPS TO REPRODUCE

```yaml

---
- name: Do Thing
  hosts: all
  tasks:
    ...
  handlers:
  - include:  handler.yml
```

##### EXPECTED RESULTS

It would be nice if it would tell me what the right API to us, because include_tasks it not right.

##### ACTUAL RESULTS

```
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This feature will be removed in a future release. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale.. This feature will be removed in a future release. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

**Comment by sivel** [comment]
Handlers are just tasks, use `import_tasks` for an equivalent to a static `include`

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
