### ISSUE TITLE
constructed inventory not loaded when using dir as inventory source

### ISSUE THREAD

**Issue by halberom** [ansible/ansible#31405]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
constructed

##### ANSIBLE VERSION
```
ansible-playbook 2.4.0.0
  config file = /private/tmp/ansible/ansible.cfg
  configured module search path = [u'/Users/lynchg/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/lynchg/.virtualenvs/a2x/lib/python2.7/site-packages/ansible
  executable location = /Users/lynchg/.virtualenvs/a2x/bin/ansible-playbook
  python version = 2.7.13 (default, Dec 18 2016, 07:03:34) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

##### CONFIGURATION
```
INVENTORY_ENABLED(/private/tmp/ansible/ansible.cfg) = ['ini', 'constructed']
```

##### OS / ENVIRONMENT
macOS

##### SUMMARY
A config file for the constructed inventory plugin is not loaded when using a dir as inventory source

##### STEPS TO REPRODUCE
Similar to https://gist.github.com/halberom/e7791aa22c7dd1ef3f1ece3c815b4af8, but using `inventory` dir

```
mkdir inventory
```

```yaml
# inventory/hosts
host1
host2 foo=bar
host3 foo=foo
host4
host5 foo=foo
```

```yaml
# inventory/dynamic.config
plugin: constructed
strict: False
keyed_groups:
  - prefix: foo
    key: foo|default('none')
```

```
# ansible.cfg
[inventory]
enable_plugins = ini, constructed
```
```
ansible host5 -i inventory -m debug -a 'var=groups'
```

##### EXPECTED RESULTS
The constructed plugin runs, and generated keyed groups

##### ACTUAL RESULTS
No keyed groups are generated.

I have to explicitly call it, e.g. with
```
ansible host5 -i inventory -i inventory/dynamic.groups -m debug -a 'var=groups'
```

The list of excluded extensions (http://docs.ansible.com/ansible/devel/config.html#inventory-ignore-exts) does not include `.config`.

_by the way, shouldn't that BLACKLIST_EXTS be expanded in the docs? - known issue?_

**Comment by bcoca** [comment]
I cannot reproduce, putting both files in a directory and using `-i inv/` gets them both invoked.

I'll look at the docs expansion

**Comment by halberom** [comment]
I thought it might be my shell expansion or something, so I spun up a quick gitlab-ci solution to try
- https://gitlab.com/halberom/ansible_constructed/-/jobs/35340315  (running in centos6 - playbook)
- https://gitlab.com/halberom/ansible_constructed/-/jobs/35340326  (running in centos6 - adhoc)

both reproduce the issue, if only passed dir, the constructed plugin doesn't run.

**Comment by halberom** [comment]
I think I've figured it out.
with `enable_plugins = ini, constructed`

this works:
```
.
├── ansible.cfg
├── inventory
│   ├── hosts
│   └── hosts.config
└── play.yml
```
and ... this doesn't
```
tree
.
├── ansible.cfg
├── inventory
│   ├── dynamic.config
│   └── hosts
└── play.yml
```

**Comment by halberom** [comment]
So guessing it's getting a file list, and then iterates for ini, and doesn't reset to the start of the list for constructed.

**Comment by bcoca** [comment]
no, dyanmic.config IS getting used by constructed .. but since there is no host data at that point, nothing happens, then hosts is processed, constructed skips, ini populates ... we are done with inventory sources.

It does not go back to previously parsed sources. It's 2 for loops (pseudo code):

```
for source in (dyhamic.config, hosts):
    for plugin in (constructed, ini):
         if plugin.parse(source):
            break
```
the parse just has to be successful, not even yield any hosts/groups

**Comment by halberom** [comment]
That doesn't make sense - I thought that as the order was `ini, constructed`, it'd parse all ini files first, then do constructed.  But what you're saying is, it's reading each file alphabetically and processing them in order of enabled plugin.  That is not intuitive.

**Comment by bcoca** [comment]
no, order is 'which plugin i try' the file order is independent of plugin order, since the plugins need to run to identify which files they CAN handle .. not sure how to do it otherwise.

**Comment by halberom** [comment]
ok, i guess this is a 'feature' then.  I was expecting something like
```
get list of plugins
get list of files
for plugin in plugin_list
  for file in file_list
    try and parse file using plugin
```
whereas it sounds like the loops are swapped
```
get list of plugins
get list of files
for file in file_list
  for plugin in plugin_list
    try and parse file using plugin
```
and i'm guessing that changing is not going to be likely/possible.

**Comment by halberom** [comment]
unless you could add a flag and some handling? `inventory_order: plugins (default: files)`  
;)

**Comment by bcoca** [comment]
i would also need to mark 'sources' as parsed and remove them from the inner loop, did not seem logical.

also i expect `-i /path1/file -i /path3/file` to be parsed in that order, over plugin order.

**Comment by halberom** [comment]
Not sure why you'd need to mark as parsed, except for performance reasons.  

Anyway, I can live with it.  Just need to change muscle memory and start prefixing all inventory files with a number.

thanks for your time!
