### ISSUE TITLE
Jinja2 variables cannot be used immediately following a command in a playbook

### ISSUE THREAD

**Issue by jlund** [ansible/ansible#3143]
The following command doesn't work:

```
- name: Test command
  command: {{ ruby_location }}/bin/gem list
```

It fails with the following error:

```
ERROR: Syntax Error while loading YAML script, /home/jlund/.../main.yml
Note: The error may actually appear before this position: line 30, column 31

- name: Test command
  command: {{ ruby_location }}/bin/gem list
                              ^
```

These commands work:

```
- name: Test command
  action: command {{ ruby_location }}/bin/gem list

- name: Test command
  command: ${ruby_location}/bin/gem list
```

**Comment by mpdehaan** [comment]
This is not true actually (that it doesn't work), rather what you have to do is quote the line because when YAML sees a line starting with a "{" it thinks it is a hash.

command: "{{ ruby_location }}/bin/gem list"

etc

**Comment by jlund** [comment]
That works. Sorry about the confusion. Thanks for your help!
