### ISSUE TITLE
extra_vars being ignore after ansible upgrade to tower 3.2.0

### ISSUE THREAD

**Issue by jacksonp2008** [ansible/ansible#31432]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
Tower

##### ANSIBLE VERSION

```
root@tower:~/ansible-tower-setup-3.2.0# ansible --version
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/spollock/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]
root@
```

##### OS / ENVIRONMENT
<!---
root@tower:~/ansible-tower-setup-3.2.0# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

##### SUMMARY
Upgraded Ansible tower.
Playbook works locally
Tower has an extra variable which is always passed
 ---
vcsnapshotname: ready

When I send extra_vars with the API it no longer works.  In addition to upgrading tower, I also changed to API V2.

##### STEPS TO REPRODUCE

API link is:  https://tower.forescoutuniversity.com/api/v2/job_templates/19/launch/

Passing these in the body via POSTMAN:
{"extra_vars": "{\"vcsnapshotstate\": \"present\",\"vcsnapshotkit\": \"test\",\"vcsnapshotname\": \"snapshot1\",\"vcsnapshotdescription\": \"snapshot description\"}"}

##### EXPECTED RESULTS
Expected tower to use the parameters passed, overiding anything statically define in the tower template and also anything defined in the playbook itself.  This was the previous behavoir.

##### ACTUAL RESULTS

```
API Call returns:  {
    "ignored_fields": {
        "extra_vars": "{\"vcsnapshotstate\": \"present\",\"vcsnapshotkit\": \"test\",\"vcsnapshotname\": \"snapshot1\",\"vcsnapshotdescription\": \"snapshot description\"}"

Again, this worked as expected prior to upgrade.
```

**Comment by jacksonp2008** [comment]
##### ISSUE TYPE


 - Bug Report


##### COMPONENT NAME
```
Tower
```
##### ANSIBLE VERSION

```
root@tower:~/ansible-tower-setup-3.2.0# ansible --version
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/spollock/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]
root@
```

##### CONFIGURATION

```
tower 3.2.0
```

##### OS / ENVIRONMENT
```
root@tower:~/ansible-tower-setup-3.2.0# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

```
##### SUMMARY
```
Upgraded Ansible tower.
Playbook works locally
Tower has an extra variable which is always passed
 
vcsnapshotname: ready

When I send extra_vars with the API it no longer works.  In addition to upgrading tower, I also changed to API V2.
```
##### STEPS TO REPRODUCE
```
API link is:  https://tower.forescoutuniversity.com/api/v2/job_templates/19/launch/

Passing these in the body via POSTMAN:
{"extra_vars": "{\"vcsnapshotstate\": \"present\",\"vcsnapshotkit\": \"test\",\"vcsnapshotname\": \"snapshot1\",\"vcsnapshotdescription\": \"snapshot description\"}"}

```

##### EXPECTED RESULTS
Expected tower to use the parameters passed, overiding anything statically define in the tower template and also anything defined in the playbook itself.  This was the previous behavoir.

##### ACTUAL RESULTS

```
API Call returns:  {
    "ignored_fields": {
        "extra_vars": "{\"vcsnapshotstate\": \"present\",\"vcsnapshotkit\": \"test\",\"vcsnapshotname\": \"snapshot1\",\"vcsnapshotdescription\": \"snapshot description\"}"

Again, this worked as expected prior to upgrade.
```

**Comment by jacksonp2008** [comment]
Unfortunate formatting required here.

**Comment by sivel** [comment]
For tower issues you will need to utilize your tower support contract.

https://access.redhat.com/products/ansible-tower-red-hat

**Comment by jacksonp2008** [comment]
haha
