### ISSUE TITLE
module argument parser is returning literal 'None' instead of logical 'None'

### ISSUE THREAD

**Issue by earchibald** [ansible/ansible#3144]
Per discussion at: https://groups.google.com/forum/?fromgroups=#!topic/ansible-project/XW_NKrP26vA

**Comment by mpdehaan** [comment]
Here's what I said.

"Yep, I think the solution here is to make the Ansible "Module Common" code auto convert "None" to None.

Can you please file a ticket for this, I may dig into this tonight but would like to have it tracked."

I still need to think about repercussions :)

**Comment by mpdehaan** [comment]
Inclined to think maybe we should NOT fix this, and instead the inventory script should set flags for things that are not set and possibly return empty string for things that need to be as such.

It seems useful to be able to use the string None for a username for instance :)
