### ISSUE TITLE
command module behaves weird

### ISSUE THREAD

**Issue by shibumi** [ansible/ansible#31480]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
`command`-module 

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/chris/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 20 2017, 01:25:59) [GCC 7.2.0]
```

##### CONFIGURATION
```
[defaults]
inventory           = hosts
roles_path          = roles
library             = library
retry_files_enabled = False

[ssh_connection]
pipelining          = True
scp_if_ssh          = True
```

##### OS / ENVIRONMENT
Ansible is running on Arch Linux. Target Host is an ubuntu 16.04 machine.

##### SUMMARY
The command module behaves differently as invoking the command manually.
The line is the following:
```
- name: migrate database
  command: php artisan app:install chdir=/var/www/html/Cachet
```

With ansible I get the following output when I run it:
```
fatal: [10.0.0.23]: FAILED! => {"changed": true, "cmd": ["php", "artisan", "app:install"], "delta": "0:00:00.201405", "end": "2017-10-09 17:02:34.522753", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2017-10-09 17:02:34.321348", "stderr": "", "stderr_lines": [], "stdout": "Clearing settings cache...\nSettings cache cleared!\nBackup skipped: SQLite is not supported.\nApplication key [base64:LNs8H0IE8idLNBKAwYDPIqzZD1YnNBC2iyO57wTqZjs=] set successfully.\nConfiguration cache cleared!\nConfiguration cached successfully!\nRoute cache cleared!\nRoutes cached successfully!\nCopied Directory [/vendor/roumen/feed/src/views] To [/resources/views/vendor/feed]\nPublishing complete for tag []!\n\n                                                                            \n  [InvalidArgumentException]                                                \n  Database (/var/www/html/Cachet/database/database.sqlite) does not exist.  \n                                                                            ", "stdout_lines": ["Clearing settings cache...", "Settings cache cleared!", "Backup skipped: SQLite is not supported.", "Application key [base64:LNs8H0IE8idLNBKAwYDPIqzZD1YnNBC2iyO57wTqZjs=] set successfully.", "Configuration cache cleared!", "Configuration cached successfully!", "Route cache cleared!", "Routes cached successfully!", "Copied Directory [/vendor/roumen/feed/src/views] To [/resources/views/vendor/feed]", "Publishing complete for tag []!", "", "                                                                            ", "  [InvalidArgumentException]                                                ", "  Database (/var/www/html/Cachet/database/database.sqlite) does not exist.  ", "                                                                            "]}

```

When I run it manually the output is completly different. 

##### STEPS TO REPRODUCE
Use the following ansible role: https://paste.archlinux.de/vOXDS/
Deploy it on a fresh ubuntu 16.04 container.
You can bootstrap a container via debootstrap and systemd-nspawn.

##### EXPECTED RESULTS
It should install cachet the same way as I would install it manually.

##### ACTUAL RESULTS
The installation fails when Invoked via ansible. 

##### QUESTION

Any Idea how I can fix this issue or get it done via ansible?

EDIT: don't worry the API key in the snippet is just a test-key. Not used in production.

**Comment by jborean93** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
