### ISSUE TITLE
using user with append results in changed always being true

### ISSUE THREAD

**Issue by mrproper** [ansible/ansible#315]
When using --append for groups,  the task always returns changed regardless of the user changing

eg:
Create a user using:

ansible host1 -m user --ask-pass -a 'name=ansible createhome=yes groups=wheel'
SSH password: 
graphite01 | success >> {
    "changed": false, 
    "comment": "", 
    "createhome": true, 
    "group": 500, 
    "groups": [
        "wheel"
    ], 
    "home": "/home/user", 
    "name": "user", 
    "shell": "/bin/bash", 
    "state": "present", 
    "uid": 500
}

Now throw append in:

ansible host -m user --ask-pass -a 'name=user createhome=yes groups=wheel append=yes'
SSH password: 
graphite01 | success >> {
    "changed": true, 
    "comment": "", 
    "createhome": true, 
    "group": 500, 
    "groups": [
        "wheel"
    ], 
    "home": "/home/user", 
    "name": "user", 
    "shell": "/bin/bash", 
    "state": "present", 
    "uid": 500
}

if i run the last command again the changed flag is still true

This is on master (0.3) running on a centos 6 machine

**Comment by mpdehaan** [comment]
Thanks for the report.

**Comment by mrproper** [comment]
I'm working a patch for it should have it over to you in a couple days
On May 4, 2012 10:12 PM, "Michael DeHaan" <
reply@reply.github.com>
wrote:

**Comment by mpdehaan** [comment]
Great!

**Comment by mrproper** [comment]
pull request submitted

**Comment by mpdehaan** [comment]
pull request is #327, needs to be rebased so we can apply it...
