### ISSUE TITLE
add some notes to the YAML syntax page

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#3151]
Just a few small gotchas:

When a line starts with "{{" you should quote the line

When a line contains an extra colon, quote the line.

Understanding of hashes, etc

**Comment by srgvg** [comment]
Some info I assembled from tips from @mpdehaan on list and irc:

Don't use $foo in when expressions, as the whole point of 1.2 is to eliminate the need for the legacy ${perl_like} syntaxes

```
when:  foo == 2
```

If you put $foo in a when statement, it's going to evaluate that variable to a string and lose it's type information.  You definitely don't want that in the case where you are passing in a list or integer something. If you want to use in, you are probably starting your YAML expression with a string and have to quote the whole line to keep YAML happy:

```
when: '"asdf" in bar'
```

To avoid weird quoting from having to start the line, this is often just as nice:

```
when:  bar.find("asdf") != -1
```

Other examples:

```
when: inventory_hostname in groups['webservers']
when: hostvars[inventory_hostname]['foo']
```

**Comment by mpdehaan** [comment]
We already updated the gotchas section so I think we can close this.
