### ISSUE TITLE
Flattened lookup plugin gives inconsistent results with string lists.

### ISSUE THREAD

**Issue by lassizci** [ansible/ansible#31528]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

flattened lookup plugin

##### ANSIBLE VERSION

```
ansible 2.5.0 (devel f2ade09dce) last updated 2017/10/06 19:23:45 (GMT +300)
```
Affects at least 2.3 too

##### SUMMARY

flattened lookup acts different with strings-only lists and mixed types.

##### STEPS TO REPRODUCE

```
ansible localhost -m debug -a msg="{{ lookup('flattened', [1,2]) }}"
ansible localhost -m debug -a msg="{{ lookup('flattened', [1,['aa','bb'], 'cc']) }}"
ansible localhost -m debug -a msg="{{ lookup('flattened', [['aa','bb'], 'cc']) }}"
ansible localhost -m debug -a msg="{{ lookup('flattened', ['bb','aa']) }}"
```

##### EXPECTED RESULTS

All outputs should consistently be list type.
```
localhost | SUCCESS => {
    "msg": [
        1, 
        2
    ]
}
```
```
localhost | SUCCESS => {
    "msg": [
        1, 
        "aa", 
        "bb", 
        "cc"
    ]
}
```
```
localhost | SUCCESS => {
    "msg": [
        "aa",
        "bb",
        "cc"
    ]
}
```
```
localhost | SUCCESS => {
    "msg": [
        "bb",
        "aa"
    ]
}
```

##### ACTUAL RESULTS
If list contains only strings, a string is returned instead.

```
localhost | SUCCESS => {
    "msg": [
        1, 
        2
    ]
}
```
```
localhost | SUCCESS => {
    "msg": [
        1, 
        "aa", 
        "bb", 
        "cc"
    ]
}
```
```
localhost | SUCCESS => {
    "msg": "aa,bb,cc"
}
```
```
localhost | SUCCESS => {
    "msg": "bb,aa"
}
```

**Comment by nomarek** [comment]
This is a problem with a `lookup` itself. If you try to run `list` lookup:
```ansible localhost -m debug -a msg="{{ lookup('list', 1,'a','b','c') }}"```
it prints:
```
localhost | SUCCESS => {
    "msg": [
        1, 
        "a", 
        "b", 
        "c"
    ]
}
```
but if we replace `1` with `'1'`:
```ansible localhost -m debug -a msg="{{ lookup('list', '1','a','b','c') }}"```
it prints:
```
localhost | SUCCESS => {
    "msg": "1,a,b,c"
}
```
Source of the problem can be found in `ansible.template.Templar._lookup`. It tries to join list arguments and when it fails (when one of the arguments is not a string), calls `wrap_var` on each element and returns it:
```python
try:
    ran = UnsafeProxy(",".join(ran))
except TypeError:
    if isinstance(ran, list) and len(ran) == 1:
        ran = wrap_var(ran[0])
    else:
        ran = wrap_var(ran)
```
Maybe this join shouldn't be there?

**Comment by andriilahuta** [comment]
This also causes problems with `fileglob` lookup. It returns a comma-separated string of paths, which can be split into a list of course, but that would fail when path itself contains commas.

**Comment by bcoca** [comment]
lookups should use the `wantlist=True` parameter to ensure a list is returned

**Comment by andriilahuta** [comment]
Totally missed that, thanks. It should probably be mentioned in _playbooks_loops_ docfile as well, because it is easy to miss when migrating from `with_` to `loop`.

**Comment by sivel** [comment]
Closing per above.

See also: https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#ensuring-list-input-for-loop-query-vs-lookup

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
