### ISSUE TITLE
setup fails in get_device_facts on SuSE 11 SP2

### ISSUE THREAD

**Issue by dirtyharrycallahan** [ansible/ansible#3152]
setup host fails on some hosts in get_device_facts. The host is SuSE 11 SP2 on an internal network.
line 650, in get_device_facts
d['host'] = m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Afraid this is all I can report right now. For now I am just commenting out that problematic call in setup.

**Comment by mpdehaan** [comment]
Will take a look.

Were you running this as root or as you?

Updating description...

**Comment by mpdehaan** [comment]
What version of ansible?

ansible --version?

**Comment by dirtyharrycallahan** [comment]
I built the rpm last night (EST) off the devel branch so 1.2 ish. I run my playbooks with the -K option so sudo'd.

**Comment by mpdehaan** [comment]
Sudo'ed to root or another user?

Thanks!

**Comment by dirtyharrycallahan** [comment]
root. I will try to go through that section of setup and see exactly where it is failing. Of the almost 20 hosts I have been working with today the code only failed on one host.

**Comment by dirtyharrycallahan** [comment]
Looks like a block device is failing when trying to find a match in the pcidata. I am not a python master so I will have to add some print statement to find out why the expected match is failing. There are really no comments in the code but perhaps you need to test the match.

**Comment by dirtyharrycallahan** [comment]
On my blade servers there are multiple pci buses and the lsipci data looks like this
nnnn:nn:nn.n. When get_device_facts lists the block devices is it looking for nn:nn.n/hostn. It looks lspci (pci-utils 3.1.17) does not output the 0000 when there is only one pci bus. What I would probably do is look at the pcidata, determine the format nnnn:nn:n.n or nn:nn.n, and adjust the /sys/block regular expression to extract the required information. The earliest I could submit a patch is tomorrow.

**Comment by dirtyharrycallahan** [comment]
I believed that I submitted a patch for this and it was accepted so I think this one should be closed.
