### ISSUE TITLE
win_smart_facts: New module to show disk SMART information

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#31521]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
win_smart_facts

##### ANSIBLE VERSION
v2.5

##### SUMMARY
This functionality would be nice to have to get an overview of the wear and tear of hard disks. A similar module could be implemented for Linux systems, but on Windows it is likely easier to get from WMI ?

**Comment by jhawkesworth** [comment]
Nice idea.  Might want to tinker with the proposed name to avoid confusion with 'smart' fact gathering.

**Comment by nitzmahone** [comment]
My limited experience with trying to get SMART data from WMI was fairly maddening back in the day. It seems like the data availability and accuracy is wildly inconsistent across HDD/storage adapter manufacturers, both at the detail and even "big picture" levels (eg, "predicted failure, yes/no"). A bit of Googling shows that I wasn't alone in this...

**Comment by ShachafGoldstein** [comment]
Maybe use these from `root\wmi` namespace in the disk facts module?
```
 MSStorageDriver_FailurePredictStatus
 MSStorageDriver_FailurePredictData
 MSStorageDriver_FailurePredictEvent
 MSStorageDriver_FailurePredictFunction
```

**Comment by ShachafGoldstein** [comment]
@dagwieers - Still relevant?

**Comment by jborean93** [comment]
Closing, if someone wants to implement this as an info module they can but I am trying to cull these feature requests which has sat over time.
