### ISSUE TITLE
template fails with undefined value despite default

### ISSUE THREAD

**Issue by mcaulifn** [ansible/ansible#31553]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
template

##### ANSIBLE VERSION
```
ansible --version
ansible 2.4.0.0
  config file = /mnt/c/Users/Nmcauliffe/repos/ansible-lab/ansible.cfg
  configured module search path = [u'/home/nmcauliffe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
DEFAULT_CALLBACK_WHITELIST(/mnt/c/Users/Nmcauliffe/repos/ansible-lab/ansible.cfg) = ['jsnapy']
DEFAULT_HASH_BEHAVIOUR(/mnt/c/Users/Nmcauliffe/repos/ansible-lab/ansible.cfg) = merge
DEFAULT_HOST_LIST(/mnt/c/Users/Nmcauliffe/repos/ansible-lab/ansible.cfg) = [u'/mnt/c/Users/Nmcauliffe/repos/ansible-lab/
DEFAULT_ROLES_PATH(/mnt/c/Users/Nmcauliffe/repos/ansible-lab/ansible.cfg) = [u'/etc/ansible/roles', u'/mnt/c/Users/Nmcau
DEPRECATION_WARNINGS(/mnt/c/Users/Nmcauliffe/repos/ansible-lab/ansible.cfg) = False

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
Jinja2 default filter is being ignored when applying template

##### STEPS TO REPRODUCE
I have a jinja template that uses a defined/learned value or is defaulted to 0. Ansible is complaining about a variable being undefined.

```yaml
- name: test template
  template: >
    src=test.j2
    dest={{ build_dir }}/test-{{ ansible_host }}.conf
```
```xml
<as>{{ instance.as|default('0') }}</as>
```

##### EXPECTED RESULTS
template defaults to 0

##### ACTUAL RESULTS

```
TASK [vrfs : test template] ********************************************************************************************
task path: /mnt/c/Users/Nmcauliffe/repos/ansible-lab/roles/vrfs/tasks/main.yaml:12
fatal: [sea-cer01]: FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "AnsibleUndefinedVariable: 'instance' is undefined"
}
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

it is not being ignored, it just only applies to the last var `as`, you need 
`{{ (instance|default({})).as|default('0') }}` to cover both variables.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by mcaulifn** [comment]
@bcoca Thanks for the heads up! Is there some documentation that needs to be updated? I'd be happy to help with that.
