### ISSUE TITLE
Should documentation apply to the latest released version?

### ISSUE THREAD

**Issue by close2design** [ansible/ansible#3158]
At this time, the docs a new user sees are actually "devel docs", which can be misleading.

As a new user myself, I just installed Ansible with Homebrew, and then started trying to scrape a playbook together, following the docs.

I was confused about why the {{ variable }} syntax didn't work, even though it was used all over the docs, until it turned out that the docs I were perusing apply to a version that's not yet even been released.

As Ansible gains wider adoption, I'd imagine other newcomers will get confused too.

**Comment by mpdehaan** [comment]
This is a one time thing since we want to get everyone on the new syntax and wanted to remove traces of confusing variable usages.

1.2 releases Monday.

**Comment by mpdehaan** [comment]
BTW, 1.1 docs available here:

http://ansible.cc/docs/released/1.1/
