### ISSUE TITLE
Exception when using `with_items` and `delegate_to`

### ISSUE THREAD

**Issue by sm4rk0** [ansible/ansible#31591]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
loop

##### ANSIBLE VERSION

```
ansible 2.5.0 (devel 97d5e0d027) last updated 2017/10/11 17:53:42 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/administrator/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/administrator/ansible/lib/ansible
  executable location = /home/administrator/ansible/bin/ansible
  python version = 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I think PR #30464 caused this issue. @bcoca , please check.
Excuse my brevity, I had limited time to write this.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:
  - debug:
      message: "{{ item }}"
    with_items:
      - one
    delegate_to: localhost
```

##### EXPECTED RESULTS
ok: [localhost -> localhost] => (item=one) => {
    "item": "one",
    "msg": "one"
}
##### ACTUAL RESULTS

```
ERROR! Unexpected Exception, this is probably a bug: unhashable type: 'AnsibleSequence'
```

Check [this gist](https://gist.github.com/sm4rk0/1d1a09a34bfdf4764ecb4c4443a27098) with added display.warning("Plugin name: %s" % name) to 
lib/ansible/plugins/loader.py#255

**Comment by jctanner** [comment]
@sm4rk0 can you confirm if https://github.com/ansible/ansible/pull/31588 addresses this issue?

needs_info

**Comment by samdoran** [comment]
@sm4rk0 This should be fixed in the latest `devel`. Please test and let us know if you're still seeing the issue.

**Comment by sm4rk0** [comment]
@jctanner Yes. Sorry, I searched existing issues before opening this one, but not the PRs, too.
@samdoran Tested. Fixed. Closing this one.
Cheers
