### ISSUE TITLE
Decryption failed ('no vault secrets would found that could decrypt)

### ISSUE THREAD

**Issue by paulcalabro** [ansible/ansible#31620]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-vault

##### ANSIBLE VERSION

```
ansible 2.5.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I have organized my configs into a role based directory structure. Some of those roles have default variable files that have encrypted text. Here's a simplified and tested task list from one that is failing:

```
---
- name: 'Include some additional variables'
  include_vars:
    dir: "{{playbook_dir}}/roles/foo/defaults/vars"
  tags: 'debug'

- name: 'Debug: display the variables'
  debug:
    msg: "{{item}}"
  with_items:
    - "{{encrypted_text_from_yml_file}}"
  tags: 'debug'

- name: 'Deploy Foo plugins'
  block:
    - name: 'Transfer the folder to the application directory'
      synchronize:
        src: 'some_src_folder'
        dest: "{{some_unencrypted_text_from_another_yml_file}}"
        archive: false
        recursive: true
  tags: 'debug'
```

##### STEPS TO REPRODUCE
1.) Setup a sample role
2.) In that sample role, create a defaults/var/{whatever.yml, vault.yml}
3.) Use the code above. Might require some minor edits.
4.) Configure passwords to be read from file
5.)  Run the playbook

```yaml
ansible-playbook -i production-servers site.yml -K --limit 'some-servers' --tags debug -v
```

##### EXPECTED RESULTS
The playbook should have transferred the files to the remote server.

##### ACTUAL RESULTS
```
Debug message shows variables decrypted as expected.
This fatal exception occurs, however:

TASK [<some_app> : Transfer the <some_folder> folder to the application directory] **********************************************************************************
fatal: [<some_hostname>]: FAILED! => {"failed": true, "msg": "Decryption failed (no vault secrets would found t
hat could decrypt)"}
```

**Comment by paulcalabro** [comment]
I see the following error message:

`Tried to use the vault secret (default) to decrypt (None) but it failed. Error: HMAC verification failed: Signature did not match digest.`

**Comment by AyushyaChitransh** [comment]
I am facing the same error when I try to edit my file:

```
ERROR! Decryption failed (no vault secrets would found that could decrypt) for /path/to/file
```

I could not understand what causes this error or how it was resolved. Should this issue be reopened?

**Comment by stanchan** [comment]
I'm also facing this issue with synchronize and the src has no encrypted data.

`FAILED! => {"msg": "Decryption failed (no vault secrets would found that could decrypt)"}`

**Comment by Akasurde** [comment]
Re-open as per #36408

**Comment by bcoca** [comment]
FYI, issue was closed by reporter, no reason given. 

The message indicates that none of the 'secrets provided' were able to be used to decrypt the vaults, we would need a reproducer to see if this is a bug or not.

**Comment by Akasurde** [comment]
@bcoca Yes. @ivan046 Could you please provide playbook and `-vvvv` output for reproducing this issue ?

**Comment by ivan046** [comment]
@Akasurde of course! here:

playbook file:
```- name: Monitoring for TechGC servers
  hosts: all
  remote_user: ubuntu
  become: yes
  gather_facts: false
  roles:
    - monitoring/nrpe
```
role file:
```
- name: copy nrpe configuration data
  synchronize:
    src: "{{ role_path }}/files/conf/"
    dest: /techgc/nrpe/conf/
    recursive: yes
    archive: no
    links: yes
    mode: push
  tags:
  - monitoring
```
in group_vars directory there is a file for 6 servers:
```
env_prefix: prod
mms_group_id: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64343937323766643031346561636661393763393935333439323864333837656266663865386637
          3333616330306664393733653431393862666665663339380a656330376237303236346462366266
          35386565353138373130313965346133656534326330633438303962333439383564626133303136
```
Setup (gather_facts) and other tasks in the role ('docker_container' & 'file' modules) show now errors, so I left only the task with the issue. In the output (attached file) there can be seen that task fails for the servers from the group having variable with vaulted value in group_vars but shows no errors for the servers from another group.
[ansible.tar.gz](https://github.com/ansible/ansible/files/1740840/ansible.tar.gz)
[output.txt](https://github.com/ansible/ansible/files/1740841/output.txt)

**Comment by harrytruman** [comment]
I just saw this error pop up with someone I was [tmux] screen-sharing with today. We verified over and over that we were using the same password; sure enough, it's repeatable.

> RHEL 7.4, 3.10.0-693.11.1
> ansible 2.4.2.0
>   python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
 
It seems to be a text encoding problem with Microsoft WSL in our case. I verified via tmux that it's repeatable both with putty and WSL bash from at least one location. Will troubleshoot more ASAP.

**Comment by ivan046** [comment]
@harrytruman you talk about absolutely different issue there. This thread is about the problem in some modules that try to load and use all group_vars including vaulted but not only the vars they need. This causes error executing playbook that forces user to set '--ask-vault-pass' (or another bay to provide vault password) even for playbooks and roles that contain no vaulted data. That's the pain. 

And you are talking about misbehaviour related with Linux/Windows incompatible encoding during SSH sessions. Please create a separate thread for it.

**Comment by harrytruman** [comment]
@ivan046 My results are identical to @paulcalabro, @AyushyaChitransh, and @stanchan.

**Comment by whytoe** [comment]
ENV: Windows 10 running Windows Subsystem Linux (WSL)
DESTINATION Hosts: RHEL 6.9/7.4

@harrytruman  I have found these steps reproduce the issue, the encrypt/decrypted value is still in my vault but when its embedded in the playbook after I close the session, Ansible loses some context of the variable.

1. Run ansible-vault encrypt_string test
2. Save the variable to a playbook vars file just like @ivan046 example for *mms_group_id*
3. Run the playbook
4. **Completes with no issues**
5. Close WSL
6. Reopen WSL
6. Run playbook on *another destination*, an error occurs *"Decryption failed (no vault secrets would found that could decrypt)"*
7. *ansible-vault decrypt '$ANSIBLE_VAULT;1.1;AES256....'*
8. test is displayed as the result

**Comment by harrytruman** [comment]
@whytoe Are you accessing a cloned repo directly or are you reading from a Windows folder (/mnt/c/...)? Based on colleague input, this is potentially a known issue under that circumstance -- let me know if this plays into what you're experiencing as well.

**Comment by unguiculus** [comment]
We are having the same issue. We use `ansible-vault` directly. Files are encrypted locally on MacOS. Jenkins cannot decrypt them. The Jenkins agent runs as a Ubuntu 16.04 Docker container. Ansible version is 2.4.3.0 in both cases.

```
ansible-vault 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-vault
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /etc/ansible/ansible.cfg as config file
Trying secret FileVaultSecret(filename='/home/ubuntu/workspace/mysecret-test-QUAQECKK4KIQW75NXAHEJYLPYDGM22352AWL345QG7WMCR4N2RRQ/vault_id.txt') for vault_id=default
Tried to use the vault secret (default) to decrypt (None) but it failed. Error: HMAC verification failed: Signature did not match digest.
ERROR! Decryption failed (no vault secrets would found that could decrypt) for mysecret.txt
```

FWIW, a file encrypted in the Ubuntu container can be successfully decrypted again. Files encrypted on MacOS cannot.

**Comment by unguiculus** [comment]
Also happens when I encrypt a file in the Ubuntu container and try to decrypt it on MacOS.

**Comment by bcoca** [comment]
So it seems we have several issues, none of them clearly the original of this ticket:
- one seems to be purely WSL based
-  one is 'author on osX and deploy on ubuntu' , probably due to encoding differences, encodings need to be the same
- Another is 'vaults in group vars are always open', this is not a bug, this is how Ansible works and won't change, as Ansible CANNOT know w/o decrypting the vault if it needs the values inside the vault. If you want to ONLY decrypt vaults for certain plays, don't put them in host_vars/group_vars.

As such I'm going to close this ticket and ask that those with the 2 first problems outlined above each open their own ticket.

**Comment by ivan046** [comment]
@bcoca You are not right about the 3th issue:

 --- Another is 'vaults in group vars are always open', this is not a bug, this is how Ansible works and won't change, as Ansible CANNOT know w/o decrypting the vault if it needs the values inside the vault. If you want to ONLY decrypt vaults for certain plays, don't put them in host_vars/group_vars.

As you can see, I'm talking not about vaulted files in inventory (ansible always should try to decrypt and load them which is not possible without providing password or password-file) but about variables with vaulted values.  As i've mentioned above I've included only task using 'synchronize' module in the role 'monitoring',
 because other tasks in the role such as ones using 'docker_container' & 'file' or 'setup' modules show no errors, and ansible play stops with the error only at 'synchronize' task!
Usual ansible behaviour is to check variable when task asks about it (and show error if it's not defined or contains non-proper data or format).
So all the playbook and roles with tasks don't show error if there is a variable with vaulted value in 'group_vars' which they don't use, but 'synchronize' shows error ``` FAILED! => {"msg": "Decryption failed (no vault secrets would found that could decrypt)"}``` about that variable even if it is not needed for that role! Sorry but it's not ansible usual behaviour. Tell me if i'm not right. Thank you in advance!

**Comment by bcoca** [comment]
@ivan046 i had read only your last post, yes, that seems like a bug, but you are mistaken about 'some modules' .. NO module does any templating, it always gets done on the controller side BEFORE calling the modules themselves. Still it is different problem from the others even if the error message is the same.

**Comment by alikins** [comment]
@ivan046 @unguiculus @stanchan @paulcalabro 

For that particular error message, there is even more verbosity output  available at -vvvv and -vvvvv verbosity levels. That should include which file is trying to be decrypted.

(the value of the vault passwords themselves are not show at these levels...)

**Comment by alikins** [comment]
If anyone wants to add a reproducer test case to test/integration/targets/vault/ that would be excellent.

**Comment by ivan046** [comment]
@alikins even with '-vvvvv' it just gives
```
TASK [monitoring/nrpe : copy nrpe configuration data] ************************************************************************************************
task path: /tmp/mozilla_windmillvane0/roles/monitoring/nrpe/tasks/main.yml:1
fatal: [ec2-18-220-140-203.us-east-2.compute.amazonaws.com]: FAILED! => {
    "msg": "input is not vault encrypted data"
}
```
without any additional info.

**Comment by alikins** [comment]
@ivan046 I can reproduce your error with the repro case at https://github.com/alikins/ansible-bug-repro/tree/master/vault_sync_decrypt_fail_31620

summary:
  - ansible-playbook fails on stable-2.4
  - ansible-inventory fails on stable-2.4
  - ansible-playbook works on devel/
  - ansible-inventory fails on devel/

Using above repro case with stable-2.4 branch with ansible-playbook and ansible-inventory
(https://gist.github.com/alikins/55f38059de4f09e56f7614a17f764394)
(https://gist.github.com/alikins/0425df18372b96a53d3b9495398f2151 for output with ANSIBLE_DEBUGGING=1 enabled)

```
[newswoop:F27:vault_sync_decrypt_fail_31620 (master % u=)]$ ansible-playbook -vvvvvv -i hosts test.yml 
ansible-playbook 2.4.4 (stable-2.4 5328bfd99b) last updated 2018/03/02 10:11:32 (GMT -400)
  config file = None
  configured module search path = [u'/home/adrian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible-playbook
  python version = 2.7.14 (default, Feb 17 2018, 10:42:17) [GCC 7.3.1 20180130 (Red Hat 7.3.1-2)]
No config file found; using defaults
setting up inventory plugins
Parsed /home/adrian/src/ansible-bug-repro/vault_sync_decrypt_fail_31620/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /home/adrian/src/ansible/lib/ansible/plugins/callback/default.py

PLAYBOOK: test.yml *********************************************************************************************************************************************************************************************
1 plays in test.yml

PLAY [all] *****************************************************************************************************************************************************************************************************
META: ran handlers

TASK [monitoring/nrpe : copy nrpe configuration data] **********************************************************************************************************************************************************
task path: /home/adrian/src/ansible-bug-repro/vault_sync_decrypt_fail_31620/roles/monitoring/nrpe/tasks/main.yml:1
fatal: [somehost]: FAILED! => {
    "failed": true, 
    "msg": "Attempting to decrypt but no vault secrets found"
}
	to retry, use: --limit @/home/adrian/src/ansible-bug-repro/vault_sync_decrypt_fail_31620/test.retry

PLAY RECAP *****************************************************************************************************************************************************************************************************
somehost                   : ok=0    changed=0    unreachable=0    failed=1   
@alikins
```
with ansible-inventory
```
[newswoop:F27:vault_sync_decrypt_fail_31620 (master % u=)]$ ansible-inventory -vvvvv -i hosts --list
ansible-inventory 2.4.4 (stable-2.4 5328bfd99b) last updated 2018/03/02 10:11:32 (GMT -400)
  config file = None
  configured module search path = [u'/home/adrian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible-inventory
  python version = 2.7.14 (default, Feb 17 2018, 10:42:17) [GCC 7.3.1 20180130 (Red Hat 7.3.1-2)]
No config file found; using defaults
setting up inventory plugins
Parsed /home/adrian/src/ansible-bug-repro/vault_sync_decrypt_fail_31620/hosts inventory source with ini plugin
ERROR! Attempting to decrypt but no vault secrets found
```




On devel/, 'ansible-playbook' works. But 'ansible-inventory -i hosts' fails with a similar error.
(https://gist.github.com/alikins/36253155059427cd7d658094a6ea8c96 gist with ANSIBLE_DEBUG=1 and -vvvvv for working 'ansible-playbook' and failing 'ansible-inventory'
```
[newswoop:F27:vault_sync_decrypt_fail_31620 (master % u=)]$ ansible-playbook -v -i hosts test.yml 
No config file found; using defaults

PLAY [all] *****************************************************************************************************************************************************************************************************

TASK [monitoring/nrpe : copy nrpe configuration data] **********************************************************************************************************************************************************
changed: [somehost] => {"changed": true, "cmd": "/bin/rsync --delay-updates -F --compress --recursive --links --out-format=<<CHANGED>>%i %n%L /home/adrian/src/ansible-bug-repro/vault_sync_decrypt_fail_31620/roles/monitoring/nrpe/files/conf/ /tmp/techgc/nrpe/conf/", "msg": ">f..T...... another_config.ini\n>f..T...... some_config.cfg\n>f..T...... some_sub_dir/blorp.conf\n", "rc": 0, "stdout_lines": [">f..T...... another_config.ini", ">f..T...... some_config.cfg", ">f..T...... some_sub_dir/blorp.conf"]}

PLAY RECAP *****************************************************************************************************************************************************************************************************
somehost                   : ok=1    changed=1    unreachable=0    failed=0   
```

**Comment by alikins** [comment]
(referring to files/hosts as in https://github.com/alikins/ansible-bug-repro/tree/master/vault_sync_decrypt_fail_31620 here)

With ansible-playbook in stable-2.4 and ansible-inventory in 2.4 and devel, something[1] is trying to read/decrypt the encrypted 'mms_group_id' var defined in group_vars/some_group
and failing. 

The encryption fails because either there is no vault password secret ("Attempting to decrypt but no vault secrets found") or there are vault passwords but not the correct one ("Decryption failed (no vault secrets would found that could decrypt)" (sic))

[1] The something appears to be the  host_group_vars VarsPlugin
https://gist.github.com/alikins/0425df18372b96a53d3b9495398f2151#file-gistfile1-txt-L212-L220
https://gist.github.com/alikins/0425df18372b96a53d3b9495398f2151#file-gistfile1-txt-L255-L286

Some notes about that:
 - Seems like synchronize action ends running the VarsPlugins.  Not sure yet if that is normal.
 - The VarsPlugins and presumably the decryption appears to be happening in a worker process

For this particular repro, I don't see an obvious reason ansible-playbook is trying to decrypt that 'mms_group_id' var.

**Comment by ivan046** [comment]
@alikins Wow, that's a really cool example of how to test, thank you! So it's a real bug and we have to wait until it is fixed. Until then I'll use``` - include_vars: "../vaulted/<<FILE-WITH-VALULTED-VARS>>.yml" ``` task inside the role that needs that vars. It's the only way i've found to bypass that issue. The ```../vaulted/``` directory is outside the inventory directory.

**Comment by alikins** [comment]
Running git-bisect between devel and stable-2.5 points to dae737c8b714f2c6d28663ef0afeab10e6d3a667 as the commit that fixed ansible-playbook in devel

**Comment by alikins** [comment]
Note:  dae737c was a fix for https://github.com/ansible/ansible/issues/33259 but is apparently causing other problems.

**Comment by alikins** [comment]
The 'ansible-inventory' failures I mentioned may be a different bug related to ansible-inventory's use of json/yaml decoders that dont grok vaulted vars. 

If that is the case, then it seems to be related to https://github.com/ansible/ansible/issues/31141 and https://github.com/ansible/ansible/pull/31946

If I disable all the 'friendly' top level exception handling so I can get a full traceback, 
the 'ansible-inventory -i hosts --list' as run against the 'hosts' from https://github.com/alikins/ansible-bug-repro/tree/master/vault_sync_decrypt_fail_31620 fails like:

```
ERROR! Attempting to decrypt but no vault secrets found
Traceback (most recent call last):
  File "/home/adrian/src/ansible/bin/ansible-inventory", line 118, in <module>
    exit_code = cli.run()
  File "/home/adrian/src/ansible/lib/ansible/cli/inventory.py", line 178, in run
    results = self.dump(results)
  File "/home/adrian/src/ansible/lib/ansible/cli/inventory.py", line 195, in dump
    results = jsonify(stuff, sort_keys=True, indent=4)
  File "/home/adrian/src/ansible/lib/ansible/module_utils/basic.py", line 784, in jsonify
    return json.dumps(data, encoding=encoding, default=_json_encode_fallback, **kwargs)
  File "/usr/lib64/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib64/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib64/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib64/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib64/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib64/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib64/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/home/adrian/src/ansible/lib/ansible/module_utils/basic.py", line 778, in _json_encode_fallback
    raise TypeError("Cannot json serialize %s" % to_native(obj))
  File "/home/adrian/src/ansible/lib/ansible/module_utils/_text.py", line 149, in to_bytes
    value = str(obj)
  File "/home/adrian/src/ansible/lib/ansible/parsing/yaml/objects.py", line 131, in __str__
    return str(self.data)
  File "/home/adrian/src/ansible/lib/ansible/parsing/yaml/objects.py", line 107, in data
    return self.vault.decrypt(self._ciphertext).decode()
  File "/home/adrian/src/ansible/lib/ansible/parsing/vault/__init__.py", line 660, in decrypt
    plaintext, vault_id = self.decrypt_and_get_vault_id(vaulttext, filename=filename)
  File "/home/adrian/src/ansible/lib/ansible/parsing/vault/__init__.py", line 698, in decrypt_and_get_vault_id
    raise AnsibleVaultError('Attempting to decrypt but no vault secrets found')
ansible.parsing.vault.AnsibleVaultError: Attempting to decrypt but no vault secrets found
```

**Comment by alikins** [comment]
(another vaguely related bug for reference purposes: https://github.com/ansible/ansible/issues/22737) - Vault variables undefined when using delegate_to

**Comment by alikins** [comment]
poking at a stable-2.5 with the repro test case and some logging turned on and using stack_info just before the vault error is raised gets me: https://gist.github.com/alikins/3f8611e907c82a5508178515c4d432de

That confirms:
 - The "Attempting to decrypt but no vault secrets found" error is coming from an attempt to decrypt vaulted variables in a task worker process and not the main process.
 - The 'synchronize' action is involved
 - The synchronize action is requesting dest host inventory vars which seems to lead to the decrypt attempt  https://gist.github.com/alikins/3f8611e907c82a5508178515c4d432de#file-gistfile1-txt-L49-L50

lib/ansible/vars/hostvars.py", line 89 calls to_bytes() on the data which leads to yaml calling the repr() on the vaulted string which attempts to decrypt it.


Not sure if there is anything that is expecting to catch a vault error there and suspect it is just bubbling back to worker process top level (and back across mp queue to main process?)
 ```   
File "/home/adrian/src/ansible/lib/ansible/plugins/action/synchronize.py", line 216, in run
dest_host_inventory_vars = task_vars['hostvars'].get(inventory_hostname)
```

**Comment by bcoca** [comment]
@ivan046 @alikins  please open a separate issue as this one has been hijacked and has different and unrelated problems in it.

**Comment by ivan046** [comment]
@alikins https://github.com/ansible/ansible/issues/31620#issuecomment-369994283 Can you do it? I'm confused with too much data you put there already...

**Comment by tcd156** [comment]
Is there any news on this issue? I am receiving the HMAC issue as well, and I have tried numerous permutations of the problem. I have:

- encrypted the strings on OS X and Ubuntu
- used different passwords
- tried encrypting a whole file, or just encrypting single values

and I always receive:  "Decryption failed (no vault secrets would found that could decrypt)"

I couldn't find a new issue that references this.

**Comment by svetlyak40wt** [comment]
I also received this error message today:

```
ERROR! Attempting to decrypt but no vault secrets found
```

Problem was solved when I added a `--ask-vault-pass` command line option. And entered a vault's password when it was requested.

**Comment by 2anoyu** [comment]
Here is what worked for my setup.

for the  -  ERROR! Attempting to decrypt but no vault secrets found 

If you embed your secret vault password configuration in your ansible.cfg file with 

default_vault_password_file = /path-to-/secret-vault-password-file       ( this secret-vault-password-file should not be in a Git and not accessible to the average user on the system)

The above message will suddenly start appearing, this is because the format appears to have changed in the newer version of ansible.cfg.  This is usually caused by a new install of Ansible or apt install upgrade.
 
For the FIX change this to 
vault_password_file = /path-to-/secret-vault-password-file

This resolved the problem and is a solution if you have a single secret-vault-password-file.   Since we have multiple ansible versions on different systems, it was necessary to have both lines in the ansible.cfg

default_vault_password_file = /path-to-/secret-vault-password-file 
vault_password_file = /path-to-/secret-vault-password-file

This does work, as the older versions use the older format and the newer versions use the new format of what is in the ansible.cfg file

If someone has a solution for using multiple secret-vault-password-files - please do share.

**Comment by devantoine** [comment]
I can confirm this bug.

I ran my playbook with `--vault-password-file=vault` and got 

>Decryption failed (no vault secrets would found that could decrypt)

If I ran the same playbook with `--ask-vault-pass` everything goes fine.

**Comment by aaronmehar** [comment]
I've found the opposite to be true here, `--ask-vault-pass` was giving me the error, where as setting this in the ansible.cfg file, allowed the decryption

```ansible-playbook 2.5.5
  config file = /Users/amehar/Library/Mobile Documents/com~apple~CloudDocs/Documents/git/homeinfra/playbooks/ansible.cfg
  configured module search path = [u'/Users/amehar/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.15 (default, Oct  2 2018, 11:47:18) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]
Using /Users/amehar/Library/Mobile Documents/com~apple~CloudDocs/Documents/git/homeinfra/playbooks/ansible.cfg as config file
statically imported: /Users/amehar/Library/Mobile Documents/com~apple~CloudDocs/Documents/git/homeinfra/playbooks/roles/common/tasks/centos.yaml
statically imported: /Users/amehar/Library/Mobile Documents/com~apple~CloudDocs/Documents/git/homeinfra/playbooks/roles/common/tasks/ubuntu.yaml
```

**Comment by songokudbz** [comment]
Still not working. I have encoded it on my Ubuntu 16.04 with Ansible 2.6.4 and my colleague tried to decrypt it Ansible 2.6.4 with Ubuntu 18.04 and it's still not working ....

**Comment by songokudbz** [comment]
My bad people, it is working. It seems that I should have read the documentation correctly. I needed to use the following command: `ansible-vault view --vault_id=.vault_pass vault.yml` (the problem was that I forgot to give the --vault_id)
