### ISSUE TITLE
setup module fails to detect upstart

### ISSUE THREAD

**Issue by aabdnn** [ansible/ansible#31651]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
setup

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/Users/anandb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION
ANSIBLE_SSH_CONTROL_PATH(env: ANSIBLE_SSH_CONTROL_PATH) = /tmp/%%r@%%h
ANSIBLE_SSH_PIPELINING(env: ANSIBLE_SSH_PIPELINING) = True
DEFAULT_GATHERING(env: ANSIBLE_GATHERING) = smart
DEFAULT_HASH_BEHAVIOUR(env: ANSIBLE_HASH_BEHAVIOUR) = merge
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/Users/anandb/repo/ansible/hosts']
DEFAULT_REMOTE_TMP(env: ANSIBLE_REMOTE_TEMP) = /tmp
DEFAULT_TIMEOUT(env: ANSIBLE_TIMEOUT) = 75
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
RETRY_FILES_ENABLED(env: ANSIBLE_RETRY_FILES_ENABLED) = False

##### OS / ENVIRONMENT
Running ansible from MacOSX 10.12.6, and managing CentOS 6.9

##### SUMMARY
The ansible_service_mgr fact should contain "upstart" but contains "service" instead.

##### STEPS TO REPRODUCE
```
ansible centos6.host -bK -m setup -a filter=ansible_service_mgr
```

##### EXPECTED RESULTS
I expected "ansible_service_mgr" to contain "upstart".

##### ACTUAL RESULTS
```
centos6.host | SUCCESS => {
    "ansible_facts": {
        "ansible_service_mgr": "service"
    }, 
    "changed": false, 
    "failed": false
}
```

**Comment by alikins** [comment]
duplicate_of https://github.com/ansible/ansible/issues/31095

https://github.com/ansible/ansible/commit/95abc1d82e4c40832c802253107ad3f9aeebc68d fixes it, should be in devel/ and headed for the 2.4.1.0 release.
