### ISSUE TITLE
hosts file should not be read more than once

### ISSUE THREAD

**Issue by Debilski** [ansible/ansible#3166]
Currently, a supplied hosts file (with `ansible -i hostfile`) is read twice because it is checked for a legacy YAML structure before the file path is being handed to `InventoryParser`.
This makes it impossible to use a pipe for the hostsfile.

Examples:

```
$ ansible -i <( hostname ) all -m ping
mymachine.local | success >> {
    "changed": false, 
    "ping": "pong"
}
```

Or, more useful than the above, using an external tool like mcollective to supply ad hoc nodes.

```
$ ansible -i <( mco find -C someMCOclass ) all -m ping
```

If the hostsfile is read more than once, this does not work.

**Comment by Debilski** [comment]
This would easily fix the problem but also removes a (legacy) warning: https://github.com/Debilski/ansible/compare/fix-duplicate-host-reads

**Comment by mpdehaan** [comment]
This removes executable inventory support here though, which is bad stuff.

I would be open to patches that left this in and still kept everything else
working.

**Comment by Debilski** [comment]
Oops. Sorry, looks like I mistakenly removed the `elif` branch which checks for `utils.is_executable`. I have restored that one in my git repo.

**Comment by mpdehaan** [comment]
Ok please send me a pull request for this if you like.

Thanks!
