### ISSUE TITLE
UnicodeEncodeError when using when_string

### ISSUE THREAD

**Issue by herveleclerc** [ansible/ansible#3167]
Hello,

_Ansible 1.2_

While Trying to check the content of a returned web page by uri module;  i'm getting this this error :

TASK: [Check Return] **********************************************************
Traceback (most recent call last):
  File "/opt/devops/envs/ansible/lib/python2.7/site-packages/ansible/runner/**init**.py", line 66, in _executor_hook
    return_data = multiprocessing_runner._executor(host)
  File "/opt/devops/envs/ansible/lib/python2.7/site-packages/ansible/runner/__init__.py", line 353, in _executor
    msg = str(ae)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 2025: ordinal not in range(128)

ere is the playbook :

Is it a bug, or i'm doing something wrong ?
## 
- hosts: 127.0.0.1
  vars:
    http_port: 80
    max_clients: 200
  user: devops
  tasks:
  - name: "Register a task that might fail"
    local_action:  uri url="http://www.alterway.fr" return_content=yes
    register: result
    ignore_errors: True
  - name: "Check Return"
    action: fail
    when_string: '"AWESOME" not in "${result.content}"'

Ansible : Version 1.2

**Comment by mpdehaan** [comment]
Thanks for the heads up on this.

Clearly we don't want this to happen when using the legacy 'when_string', however I wanted to share a quick workaround using the new syntax available (and preferred) in 1.2

when: "'AWESOME' not in result.content"

Basically you can just use Python (well Jinja2) expressions now, so no need for all of the pseudo-Perl or the typed "whens", and the operator we use for this, is "when".  I tested this and it does not produce the error in the above scenario.

**Comment by mpdehaan** [comment]
Yeah looks like you will need to switch over to the new format anyway, since the expression, even with unicode fixes, will still not evaluate true/false in the old form.

Switch over to "when" and you will be ok.

Also note no need for the old  style variables inside the when expression.

Thanks and let me know if you have any questions!

**Comment by herveleclerc** [comment]
Thank you! works like a charm !
