### ISSUE TITLE
Pipelining works only when config option in connection section (not ssh_connection)

### ISSUE THREAD

**Issue by luqasz** [ansible/ansible#31784]
##### ISSUE TYPE
 - Bug Report
 - Documentation Report

##### COMPONENT NAME
pipelining

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /Users/lkostka/devbox/prov/ansible.cfg
  configured module search path = [u'/Users/lkostka/devbox/prov/modules']
  ansible python module location = /Users/lkostka/.virtualenvs/prov/lib/python2.7/site-packages/ansible
  executable location = /Users/lkostka/.virtualenvs/prov/bin/ansible
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/Users/lkostka/devbox/prov/ansible.cfg) = True
ANSIBLE_SSH_ARGS(env: ANSIBLE_SSH_ARGS) =
DEFAULT_CALLBACK_PLUGIN_PATH(/Users/lkostka/devbox/prov/ansible.cfg) = [u'/Users/lkostka/devbox/prov/callbacks']
DEFAULT_FILTER_PLUGIN_PATH(/Users/lkostka/devbox/prov/ansible.cfg) = [u'/Users/lkostka/devbox/prov/filters']
DEFAULT_FORKS(/Users/lkostka/devbox/prov/ansible.cfg) = 40
DEFAULT_LOOKUP_PLUGIN_PATH(/Users/lkostka/devbox/prov/ansible.cfg) = [u'/Users/lkostka/devbox/prov/lookups']
DEFAULT_MODULE_PATH(/Users/lkostka/devbox/prov/ansible.cfg) = [u'/Users/lkostka/devbox/prov/modules']
DEFAULT_SCP_IF_SSH(/Users/lkostka/devbox/prov/ansible.cfg) = true
DEFAULT_TRANSPORT(/Users/lkostka/devbox/prov/ansible.cfg) = ssh
DEPRECATION_WARNINGS(/Users/lkostka/devbox/prov/ansible.cfg) = True
RETRY_FILES_ENABLED(/Users/lkostka/devbox/prov/ansible.cfg) = False
```

##### OS / ENVIRONMENT
mac os

##### SUMMARY
In order to use pipelining, it must be specified in `connection` section. Documentation states that it had to be in `ssh_connection` section.

##### STEPS TO REPRODUCE
Remove any pipelining config options.
Add `pipelining = True` in ansible.cfg in `ssh_config` section.
exec ansible with `-vvv` and modules are copied, not pipelined.
move `pipelinig = True` to `connection` section.
Now works

##### EXPECTED RESULTS
Either fix documentation to state valid section or change behavior in ansible.

##### ACTUAL RESULTS
pipelining in `ssh_config` does not cause ansible to use pipelining

**Comment by bcoca** [comment]
this was a bug in 2.4, fixed in #31244 which will be part of 2.4.1
