### ISSUE TITLE
[CI] Split network-infra so it just contains configuration/data

### ISSUE THREAD

**Issue by rcarrillocruz** [ansible/ansible#31781]
##### ISSUE TYPE
N/A

##### COMPONENT NAME
N/A

##### ANSIBLE VERSION
N/A

##### SUMMARY

We have consolidated network-infra as the repo that contains playbooks to deploy our CI and its configuration.
Split code from configuration/data, so network-infra stays private having our  configuration and create a new one that will host the playbooks (we could name it network-infra-installer or network-infra-playbooks).

**Comment by gundalow** [comment]
At this time also ensure all changes to the following repos are in the of the above new repos then kill:

* https://github.com/ansible/dci-partner-ansible
* https://github.com/ansible/dci-ansible-testrunner

**Comment by rcarrillocruz** [comment]
closing, we splitted this in repos network-infra-playbooks + network-infra
