### ISSUE TITLE
cron module traceback

### ISSUE THREAD

**Issue by skvidal** [ansible/ansible#3180]
this action:
 cron: cron_file=geoip_sync name=geoip_sync state=present minute=0 hour=1 day=4 user=root job="/usr/local/bin/syncFiles.sh bigfiles/geoip /usr/share/GeoIP" 

results in this traceback:

failed: [mirrorlist-ibiblio.fedoraproject.org] => {"failed": true, "item": "", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1370981885.36-255864325591023/cron", line 1258, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1370981885.36-255864325591023/cron", line 346, in main
    (rc, out, err) = install_jobs(module,user,tmpfile.name, cron_file)
TypeError: 'NoneType' object is not iterable
Exception OSError: (2, 'No such file or directory', '/tmp/tmp1XV_Lh') in <bound method _TemporaryFileWrapper.__del__ of <closed file '<fdopen>', mode 'w+b' at 0x8fc030>> ignored

**Comment by mpdehaan** [comment]
Is this something you would like to help fix perhaps?

**Comment by skvidal** [comment]
perhaps - I had to move along so I punted to copying the file into place

**Comment by JamesTuthill** [comment]
I can confirm this bug with Ansible 1.2.

**Comment by mpdehaan** [comment]
We have a pull request for cron module cleanup that should take care of this.

In queue for testing, so closing this ticket
