### ISSUE TITLE
External Inventory script parser should allow _hostvars dict in addition to host list

### ISSUE THREAD

**Issue by earchibald** [ansible/ansible#3182]
[As discussed in https://groups.google.com/forum/?fromgroups=#!topic/ansible-project/YXmKqAypZS8 ]
- The external inventory script parser SHALL allow an additional top-level dict to be returned when called with --list, defining hostvars in one unified call (rather than N calls to --host HOST)

"_hostvars" : {
    "asdf.example.com" : {
        "x" : 12,
        "y" : "fjord",
    } ,
}

**Comment by mpdehaan** [comment]
Implemented.

Details here:

https://github.com/ansible/ansible/commit/8955ac1eda048eeda7e4126ee0cc26c2a4b06147
