### ISSUE TITLE
elb_target_group module does not support tcp as protocol, and amazon does

### ISSUE THREAD

**Issue by ramonamis** [ansible/ansible#31896]
##### ISSUE TYPE

 - ~~Bug Report~~
- Feature Idea

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/Users/ramonamis/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ramonamis/.virtualenvs/devops/lib/python2.7/site-packages/ansible
  executable location = /Users/ramonamis/.virtualenvs/devops/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### SUMMARY
The elb_target_group module fails when provided with protocol: tcp
```
TASK [lb-route53-create : Create lb target group] **************************************************
Wednesday 18 October 2017  16:27:41 +0200 (0:00:00.081)       0:00:50.817 *****
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "value of protocol must be one of: http,https,HTTP,HTTPS, got: tcp"}
```
##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS
module supports tcp protocol, since amazon supports it

##### ACTUAL RESULTS

```

```

**Comment by jborean93** [comment]
cc @wimnat

**Comment by wimnat** [comment]
Support has been merged it's just not in 2.4. Use the latest version in devel brancg

**Comment by s-hertel** [comment]
Support for tcp protocol has been added in 044dd699c22ae23cad80d62d3a4b4e23aeb8a00d. If you need the feature now you can add the latest version in your local library/ so it overrides the 2.4 version of the module.

**Comment by ramonamis** [comment]
Thank you!

**Comment by mohannmurthy** [comment]
Hi I am using ansible 2.5 and yet i am seeing this issue. Does not allow TCP to be used for the protocol. 
ansible --version
ansible 2.5.0rc3 (detached HEAD 144e5ae65a) last updated 2018/07/23 16:50:15 (GMT +100)
