### ISSUE TITLE
/etc/ansible and ansible.cfg directory and files are missing in macosx

### ISSUE THREAD

**Issue by ubersol** [ansible/ansible#31907]
##### ISSUE TYPE

 - Bug Report
 

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/Users/deniz/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION

$ ansible-config dump --only-changed
$

##### OS / ENVIRONMENT

MACOSX SIERRA Version 10.12.5

##### SUMMARY

When installed Ansible through pip, I am unable to find ansible.cfg file or /etc/ansible. There does not seem to be a default place ansible.cfg reside.
##### STEPS TO REPRODUCE

Install Ansible through PIP:
 sudo pip install ansible
Password:
The directory '/Users/deniz/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/deniz/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting ansible
  Downloading ansible-2.4.0.0.tar.gz (6.6MB)
    100% |████████████████████████████████| 6.6MB 204kB/s
Requirement already satisfied: jinja2 in /Library/Python/2.7/site-packages (from ansible)
Requirement already satisfied: PyYAML in /Library/Python/2.7/site-packages (from ansible)
Collecting paramiko (from ansible)
  Downloading paramiko-2.3.1-py2.py3-none-any.whl (182kB)
    100% |████████████████████████████████| 184kB 4.0MB/s
Collecting cryptography (from ansible)
  Downloading cryptography-2.1.1-cp27-cp27m-macosx_10_6_intel.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 732kB/s
Requirement already satisfied: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from ansible)
Requirement already satisfied: MarkupSafe in /Library/Python/2.7/site-packages (from jinja2->ansible)
Collecting pynacl>=1.0.1 (from paramiko->ansible)
  Downloading PyNaCl-1.1.2-cp27-cp27m-macosx_10_6_intel.whl (178kB)
    100% |████████████████████████████████| 184kB 3.1MB/s
Collecting bcrypt>=3.1.3 (from paramiko->ansible)
  Downloading bcrypt-3.1.4-cp27-cp27m-macosx_10_6_intel.whl (51kB)
    100% |████████████████████████████████| 61kB 4.4MB/s
Collecting pyasn1>=0.1.7 (from paramiko->ansible)
  Downloading pyasn1-0.3.7-py2.py3-none-any.whl (63kB)
    100% |████████████████████████████████| 71kB 3.2MB/s
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography->ansible)
  Downloading cffi-1.11.2-cp27-cp27m-macosx_10_6_intel.whl (238kB)
    100% |████████████████████████████████| 245kB 1.9MB/s
Collecting enum34; python_version < "3" (from cryptography->ansible)
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting idna>=2.1 (from cryptography->ansible)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 3.1MB/s
Collecting asn1crypto>=0.21.0 (from cryptography->ansible)
  Downloading asn1crypto-0.23.0-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 3.4MB/s
Collecting ipaddress; python_version < "3" (from cryptography->ansible)
  Downloading ipaddress-1.0.18-py2-none-any.whl
Requirement already satisfied: six>=1.4.1 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from cryptography->ansible)
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography->ansible)
  Downloading pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 1.8MB/s
Installing collected packages: pycparser, cffi, pynacl, enum34, idna, asn1crypto, ipaddress, cryptography, bcrypt, pyasn1, paramiko, ansible
  Running setup.py install for pycparser ... done
  Running setup.py install for ansible ... done
Successfully installed ansible-2.4.0.0 asn1crypto-0.23.0 bcrypt-3.1.4 cffi-1.11.2 cryptography-2.1.1 enum34-1.1.6 idna-2.6 ipaddress-1.0.18 paramiko-2.3.1 pyasn1-0.3.7 pycparser-2.18 pynacl-1.1.2

2)  Check the system for configuration file:
$sudo find / | grep ansible.cfg | grep -v Vagrant
/Library/Python/2.7/site-packages/ansible/galaxy/data/container_enabled/tests/ansible.cfg

and the content of that file is:
$ cat /Library/Python/2.7/site-packages/ansible/galaxy/data/container_enabled/tests/ansible.cfg
[defaults]
inventory=./inventory

3) Check /etc directory for ansible:
$ ls /etc/ansible
ls: /etc/ansible: No such file or directory

```yaml
No yaml or playbooks yet
```

##### EXPECTED RESULTS

I was expecting that i could have ansible.cfg out of the box when I do install through pip. /etc/ansible is also missing. This is not the case with other OS installations such as centos or ubuntu? so what's missing here?
##### ACTUAL RESULTS

```

```

**Comment by jborean93** [comment]
Is This A Bug?
==============

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:

   * These directories or files are not created when Ansible is installed and is expected that you either create the /etc/ansible directory or make your own ansible.cfg file

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
   
   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Comment by bazmera** [comment]
Have you found the solution for this solution? I am having same problem.
