### ISSUE TITLE
Documentation Home breadcrumb disappears when viewing documentation

### ISSUE THREAD

**Issue by garethrees** [ansible/ansible#3191]
Is the natural place to click, but it disappears when viewing the docs

![screen shot 2013-06-12 at 13 04 58](https://f.cloud.github.com/assets/282788/647937/755eae66-d418-11e2-8730-94cfbb9bdcbc.png)

![screen shot 2013-06-12 at 13 05 07](https://f.cloud.github.com/assets/282788/647938/776df86a-d418-11e2-82bc-4a6e04526c8b.png)

**Comment by mpdehaan** [comment]
Yep, @tgerla and I are aware of this one.

Should be fixed soon!

**Comment by garethrees** [comment]
:+1:

**Comment by mpdehaan** [comment]
@tgerla want an internal ticket instead?  Thanks!

**Comment by tgerla** [comment]
Please. Thanks.

On Tue, Aug 6, 2013 at 1:50 PM, Michael DeHaan notifications@github.comwrote:

> @tgerla https://github.com/tgerla want an internal ticket instead?
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/3191#issuecomment-22210217
> .

## 

Tim Gerla
tim@gerla.net

**Comment by mpdehaan** [comment]
This is now done, thanks @tgerla!
