### ISSUE TITLE
Failed to connect to the host via ssh: command-line line 0: garbage at end of line;

### ISSUE THREAD

**Issue by loranger** [ansible/ansible#31916]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Core

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /Users/loranger/.ansible.cfg
  configured module search path = [u'/Users/loranger/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:54:19) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION
DEFAULT_HOST_LIST(/Users/loranger/.ansible.cfg) = [u'/Users/loranger/.ansible/hosts']
DEFAULT_REMOTE_TMP(/Users/loranger/.ansible.cfg) = $HOME/.ansible/tmp
DEFAULT_ROLES_PATH(/Users/loranger/.ansible.cfg) = [u'/Users/loranger/.ansible/roles']
HOST_KEY_CHECKING(/Users/loranger/.ansible.cfg) = False

##### OS / ENVIRONMENT
Using Ansible on macOS 10.13 to various debians

##### SUMMARY
I used to use [mackup](https://github.com/lra/mackup) in order to keep my dotfiles synced on dropbox. It basically makes some symlinks from the original path to a synced one, such as dropbox, depending on the configuration written for an application. [Here is the configuration file used for ansible](https://github.com/lra/mackup/blob/master/mackup/applications/ansible.cfg).
Anyway, at work, we created a specific dropbox account for team and since the new dropbox was added to my home directory, I cannot use ansible anymore.
I soon as I try to use my inventory file, I get the `Failed to connect to the host via ssh: command-line line 0: garbage at end of line;` error 

How can I get rid of this issues ?

##### STEPS TO REPRODUCE
```shell
❯ ansible all -m ping
```

##### EXPECTED RESULTS
```shell
chaos | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
```

##### ACTUAL RESULTS
```
ansible 2.4.0.0
  config file = /Users/loranger/.ansible.cfg
  configured module search path = [u'/Users/loranger/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:54:19) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
Using /Users/loranger/.ansible.cfg as config file
setting up inventory plugins
Parsed /Users/loranger/.ansible/hosts/composer inventory source with ini plugin
Parsed /Users/loranger/.ansible/hosts/dujour.conf inventory source with ini plugin
Parsed /Users/loranger/.ansible/hosts/hosts inventory source with ini plugin
Parsed /Users/loranger/.ansible/hosts/northern.conf inventory source with ini plugin
Parsed /Users/loranger/.ansible/hosts/perso.conf inventory source with ini plugin
Parsed /Users/loranger/.ansible/hosts/phoenix.disable inventory source with ini plugin
Parsed /Users/loranger/.ansible/hosts/puccia.conf inventory source with ini plugin
Parsed /Users/loranger/.ansible/hosts/raspberry.conf inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
META: ran handlers
Using module file /usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible/modules/system/ping.py
<chaos> ESTABLISH SSH CONNECTION FOR USER: None
<chaos> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o 'ControlPath=/Users/loranger/Dropbox (Personnelle)/OSX/mackup/.ansible/cp/eead3d7599' chaos '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1508359150.0-45696358822537 `" && echo ansible-tmp-1508359150.0-45696358822537="` echo $HOME/.ansible/tmp/ansible-tmp-1508359150.0-45696358822537 `" ) && sleep 0'"'"''
<chaos> (255, '', 'command-line line 0: garbage at end of line; "(Personnelle)/OSX/mackup/.ansible/cp/eead3d7599".\r\n')
chaos | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: command-line line 0: garbage at end of line; \"(Personnelle)/OSX/mackup/.ansible/cp/eead3d7599\".\r\n", 
    "unreachable": true
}

```

**Comment by jborean93** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
