### ISSUE TITLE
--limit does not work with ansible-inventory CLI

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible#31929]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea

##### COMPONENT NAME
ansible-inventory CLI

##### ANSIBLE VERSION
```
ansible --version
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/alancoding/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible
  executable location = /Users/alancoding/.virtualenvs/ansible/bin/ansible
  python version = 2.7.10 (default, Jul 13 2015, 12:05:58) [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
```

##### OS / ENVIRONMENT
Mac

##### SUMMARY
`ansible-inventory` command does not respect `--limit` option.

##### STEPS TO REPRODUCE
I'm using a basic example inventory file example with 2 groups and 4 hosts.

https://github.com/AlanCoding/Ansible-inventory-file-examples/blob/master/top_level_file.ini

```
$ cat top_level_file.ini 
[fooland]
foo1
foo2

[barland]
bar1
bar2
```

To reproduce:

```
ansible-inventory -l foo1 -i top_level_file.ini --list
```

or

```
ansible-inventory --limit foo1 -i top_level_file.ini --list
```

##### EXPECTED RESULTS
I expect the only hosts in the output to be "foo1".

##### ACTUAL RESULTS
All hosts are returned. `--limit` or `-l` has no effect.

```
$ ansible-inventory -l foo1 -i top_level_file.ini --list
{
    "_meta": {
        "hostvars": {
            "bar1": {}, 
            "bar2": {}, 
            "foo1": {}, 
            "foo2": {}
        }
    }, 
    "all": {
        "children": [
            "barland", 
            "fooland", 
            "ungrouped"
        ]
    }, 
    "barland": {
        "hosts": [
            "bar1", 
            "bar2"
        ]
    }, 
    "fooland": {
        "hosts": [
            "foo1", 
            "foo2"
        ]
    }, 
    "ungrouped": {}
}
```

Trying `ansible-inventory --list-hosts foo1 -i top_level_file.ini --list` also doesn't work, although I didn't think its functionality makes sense with `ansible-inventory` anyway.

**Comment by bcoca** [comment]
not sure it makes sense, `--limit` has never really affected the inventory itself, just the response to the play selection criteria aka `hosts:`.

**Comment by AlanCoding** [comment]
Alright, I'm okay to close this. I get what you're saying about how this is really asking for novel functionality, and there's not any real need driving that.

**Comment by bcoca** [comment]
keeping open, as we might need to remove the option from ansible-inventory if it is of no use, but it might  make sense for the --list-hosts option.

**Comment by hogarth-sv** [comment]
Either the --limit needs to be removed from the --help (and docs) or this needs to work as it's just silly as it stands right now.

Personally I'd love to see `ansible-inventory --limit` work as it's a great way to list variables for a given target, and being able to "pre filter" using that is much better than trying to "post filter" with jq etc

**Comment by tonyskidmore** [comment]
I spent quite a while looking at this until I found this issue.  I too was hoping that ```--limit``` was going to filter inventory output.

**Comment by gforster** [comment]
I would much rather see this implemented than simply have the errant doc corrected. I have a use case where I need to create separate static inventory files from a dynamic inventory based on certain groups. It seems I should easily be able to do that with --limit and cannot.

**Comment by bcoca** [comment]
@gforster implementing it is not as simple as it sounds as many of the options make no sense with `--limit`, for now i decided to remove until I had time to make it work in a sensible fashion or someone else submits a PR that does so.

**Comment by gforster** [comment]
@bcoca - understood. However, it does seem to work with the --graph param which is interesting. I can get close to what I need using --graph --vars --limit <SUBSET>.

**Comment by bcoca** [comment]
@gforster afaik `--limit` does not work with `ansible-inventory`, i have a PR to remove it from the help display for that utility
