### ISSUE TITLE
New Feature "Force Handlers"

### ISSUE THREAD

**Issue by jurgenhaas** [ansible/ansible#3198]
I can the execution of a playbook gets interrupted (i.e. because of errors), the notified handlers at that point will get lost and we would have to have to new features to better handle such circumstances:

1) information about the handlers that couldn't be executed but were waiting in the queue
2) a command line option for ansible-playbook to  only execute a given list of handlers

For more details, please also see https://groups.google.com/forum/#!topic/ansible-project/2T7VEHvgmag

**Comment by jurgenhaas** [comment]
Strange. I got 3 notifications but I can't see any of the contained 
comments on github. Have they been deleted or do I not have permission 
to see comments?

Am Mi 19 Jun 2013 16:33:17 CEST schrieb Michael DeHaan:

**Comment by jurgenhaas** [comment]
Sound iteresting, just that I couldn't find any documentation for this.
Can you please point me in the right direction?

Am 19.06.2013 16:32, schrieb Michael DeHaan:

**Comment by nornagon** [comment]
Why did this get closed? Is there a way to manually run handlers now?

**Comment by bcoca** [comment]
As already stated above:
- meta: flush_handlers

On Mon, Sep 30, 2013 at 5:30 PM, Jeremy Apthorp notifications@github.comwrote:

> Why did this get closed? Is there a way to manually run handlers now?

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by nornagon** [comment]
Oh, I didn't expect that to be behind the fold. Thanks!
