### ISSUE TITLE
Option --ask-pass interpreted differently depending on whether a key file is supplied (paramiko_ssh)

### ISSUE THREAD

**Issue by ossark** [ansible/ansible#31988]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
paramiko_ssh

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.4.0.0
  config file = /Users/johndoe/.ansible.cfg
  configured module search path = [u'/Users/johndoe/repos/ansible/library']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
ANSIBLE_SSH_CONTROL_PATH(/Users/johndoe/.ansible.cfg) = %(directory)s/%%C
DEFAULT_FORKS(/Users/johndoe/.ansible.cfg) = 100
DEFAULT_GATHERING(/Users/johndoe/.ansible.cfg) = smart
DEFAULT_HOST_LIST(/Users/johndoe/.ansible.cfg) = [u'/Users/johndoe/repos/ansible/inventory']
DEFAULT_JINJA2_EXTENSIONS(/Users/johndoe/.ansible.cfg) = jinja2.ext.do,jinja2.ext.i18n
DEFAULT_LOG_PATH(/Users/johndoe/.ansible.cfg) = /Users/johndoe/.ansible.log
DEFAULT_MANAGED_STR(/Users/johndoe/.ansible.cfg) = Ansible managed: modified on %Y-%m-%d by {uid} on {host}
DEFAULT_MODULE_PATH(/Users/johndoe/.ansible.cfg) = [u'/Users/johndoe/repos/ansible/library']
HOST_KEY_CHECKING(/Users/johndoe/.ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/johndoe/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Supplying the --ask-pass option to ansible-playbook is interpreted by paramiko as either being the password for you SSH connection or the passphrase for your private key. It is not obvious to the user which one is done.

##### STEPS TO REPRODUCE
Prereqs: 
Having a host (Cisco Catalyst IOS device in my case) that only accepts password auth, not publickey.

Playbook:
```
---
- hosts: catalyst
  gather_facts: no
  connection: local

  tasks:
    - name: show version
      ios_command:
         commands: show version
```

Not working case:
```
$ cat ~/.ansible.cfg | grep private_key
private_key_file=ssh/ansible
$ ansible-playbook catalyst.yaml -k
SSH password: 

PLAY [catalyst] ****************************************************************************************************************************************************************************************************************************

TASK [show version] ************************************************************************************************************************************************************************************************************************
fatal: [10.35.0.25]: FAILED! => {"changed": false, "failed": true, "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"}

PLAY RECAP *********************************************************************************************************************************************************************************************************************************
10.35.0.25                 : ok=0    changed=0    unreachable=0    failed=1   
```

Working case:
```
$ cat ~/.ansible.cfg | grep private_key
#private_key_file=ssh/ansible
$ ansible-playbook catalyst.yaml -k
SSH password: 

PLAY [catalyst] ****************************************************************************************************************************************************************************************************************************

TASK [show version] ************************************************************************************************************************************************************************************************************************
ok: [10.35.0.25]

TASK [debug] *******************************************************************************************************************************************************************************************************************************
ok: [10.35.0.25] => {
    "data": {
        "changed": false, 
        "failed": false, 
        "stdout": [
      <LOTZ OF DATAZ>
            ]
        ]
    }
}

PLAY RECAP *********************************************************************************************************************************************************************************************************************************
10.35.0.25                 : ok=2    changed=0    unreachable=0    failed=0   

```

##### EXPECTED RESULTS
--ask-pass (-k) should put password auth as first option. Supplying a passphrase should be done in another way. The duality of the ---ask-pass option for paramiko_ssh is not very user friendly.

**Comment by gundalow** [comment]
This needs clarifying in documentation (so adding `label:docs_report`).

I believe this could impact any thing that uses ssh, though this was spotted while doing `label:networking` as that's where this was spotted.

**Comment by calfonso** [comment]
This bug report is actually a feature idea to provide another argument other than `--ask-pass` to use for unlocking the private key rather than overloading `--ask-pass` for two cases (providing a password for password based auth OR using it for unlocking the private key). Since this is not a networking specific issue, I'm going to move this over to core and set it to a feature idea for their evaluation.

**Comment by gundalow** [comment]
Added to the Core IRC Meeting agenda https://github.com/ansible/community/issues/273#issuecomment-341108984

**Comment by bcoca** [comment]
@calfonso sadly this does not seem something we can control when using paramiko, its part of it's API

**Comment by abadger** [comment]
@ossark how comfortable are you patching code?  I think this may be a bug in paramiko rather than Ansible.  I've proposed the following PR upstream: https://github.com/paramiko/paramiko/pull/1106

**Comment by ossark** [comment]
I could test thinkgs if needed. Point me in the correct direction and I'll
patch locally.

**Comment by abadger** [comment]
Cool.  Go to this paramiko bug: <https://github.com/paramiko/
paramiko/pull/1106>

and try applying that change to your version of paramiko.

**Comment by gundalow** [comment]
@ossark Just wondering if you had a chance to test https://github.com/paramiko/paramiko/pull/1106 ?

**Comment by ossark** [comment]
Not yet. Busy busy...

Will make an attempt next week

**Comment by gundalow** [comment]
@ossark Just reviewing open issues, did you get a chance to test https://github.com/paramiko/paramiko/pull/1106 ?

**Comment by ossark** [comment]
Hello,

I did just test it. Does not seem to work properly, no change in behaviour. Did some paramiko logging. Here are the relevant parts.
```
DEB [20180108-10:22:12.295] thr=1   paramiko.transport: Authentication type (none) not permitted.
DEB [20180108-10:22:12.295] thr=1   paramiko.transport: Allowed methods: [u'keyboard-interactive', u'password']
INF [20180108-10:22:12.311] thr=1   paramiko.transport: Disconnect (code 2): Protocol error: expected packet type 50, got 5
```

**Comment by samdoran** [comment]
Closing since this is longstanding, though problematic, behavior of Paramiko and we do not plan to work around it at this time. We could work around this limitation in Paramiko if there is more demand to change this behavior, but that would most likely result in a breaking change for those relying in this behavior currently.
