### ISSUE TITLE
Support for ECR Lifecycle policies

### ISSUE THREAD

**Issue by snemetz** [ansible/ansible#32003]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
lib/ansible/modules/cloud/amazon/ecs_ecr.py

##### ANSIBLE VERSION
```
2.4.0.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Amazon added Lifecycle policies to ECR repositories this month.
It would be great if this was supported in the ecs_ecr module

**Comment by alikins** [comment]
pinging @leedm777 @willthames

**Comment by leedm777** [comment]
Spent some time on this last night. Turned out to be almost identical to the existing policy stuff, so not too bad. Should have a PR up soon.

**Comment by leedm777** [comment]
PR #32137 submitted.

**Comment by markuman** [comment]
@SpamapS any progress here? do you need help?
