### ISSUE TITLE
Add Azure Container Registry (ACR)

### ISSUE THREAD

**Issue by yaweiw** [ansible/ansible#32027]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.5.0 (yaweiw b83582d280) last updated 2017/10/20 15:53:19 (GMT +800)
  config file = None
  configured module search path = [u'/Users/yaweiwang/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/yaweiwang/ansible/lib/ansible
  executable location = /Users/yaweiwang/ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### SUMMARY

Mac OS 10.12.6

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by yaweiw** [comment]
@xscript @zikalino @yuwzho

**Comment by thaumos** [comment]
just to confirm, are you asking for an azure_container_registry module?

**Comment by thaumos** [comment]
@tstringer, @haroldwongms

**Comment by yaweiw** [comment]
@thaumos, our team is taking over the owner of module work for Azure from @tstringer @haroldwongms. We are working on adding new modules for container on Azure e.g. ACI, ACR etc.

**Comment by kyliel** [comment]
@nitzmahone @jordonr Could you please have a review? Thanks.

**Comment by kyliel** [comment]
@zikalino , could you please attach the PR for ACR here and close this one? Thank you.

**Comment by yuwzho** [comment]
resolved_by_pr 33597

**Comment by yuwzho** [comment]
@ansibot
