### ISSUE TITLE
error in installation of ansible via yum

### ISSUE THREAD

**Issue by arun8796** [ansible/ansible#32091]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME
installation of ansible via yum

##### ANSIBLE VERSION

```

```

##### OS / ENVIRONMENT
x86_64 x86_64 GNU/Linux

##### SUMMARY
trying to install ansoble via yum method as per link https://developers.redhat.com/blog/2016/08/15/install-ansible-on-rhel/

 sudo rpm -i epel-release-latest-7.noarch.rpm
        package epel-release-7-10.noarch is already installed
[sudo yum update
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
No packages marked for update
 sudo yum install ansible
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
No package ansible available.
Error: Nothing to do

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS
ansible localhost -m ping
##### ACTUAL RESULTS

 ansible --version
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

```

**Comment by sivel** [comment]
`ansible` is no longer being provided by EPEL for EL7.  As per the installation docs at http://docs.ansible.com/ansible/latest/intro_installation.html#latest-release-via-yum you must use the Extras channel for EL7.

I suppose this is a docs report, but we do not have direct access via the community to edit that blog post.

**Comment by sivel** [comment]
cc @dharmabumstead

**Comment by arun8796** [comment]
Thanks @sivel 

Now i tried EPEL 6 using link https://maprdocs.mapr.com/52/AdvancedInstallation/EnableEPELreposCentOSorRH6.html

after installing when i do yum update i face below error

--> Finished Dependency Resolution
Error: Package: python2-hwdata-2.3.5-1.el6.noarch (epel)
           Requires: python(abi) = 2.6
           Installed: python-2.7.5-58.el7.x86_64 (@anaconda/7.4)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.5-16.el7.x86_64 (rhui-REGION-rhel-server-releases)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.5-18.el7_1.1.x86_64 (rhui-REGION-rhel-server-releases)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.5-34.el7.x86_64 (rhui-REGION-rhel-server-releases)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.5-38.el7_2.x86_64 (rhui-REGION-rhel-server-releases)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.5-39.el7_2.x86_64 (rhui-REGION-rhel-server-releases)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.5-48.el7.x86_64 (rhui-REGION-rhel-server-releases)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python34-3.4.5-2.el6.i686 (epel)
               python(abi) = 3.4
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Please help

**Comment by arun8796** [comment]
thanks all.. i tried with centOs and able to install successfuly

**Comment by sukughantoji** [comment]
Try this - it helped:-
sudo easy_install pip
sudo pip install ansible

**Comment by nitinakula** [comment]
Hey i had been stuck with this error since last two hours.   It helped me to solve this... Thank you

**Comment by alokkusingh** [comment]
If you are stuck and don't have any other option then try with "--skip-broken" option.
