### ISSUE TITLE
Sporadic/Random Error - Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fd04f6e2bf8>

### ISSUE THREAD

**Issue by fligi7** [ansible/ansible#32095]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
N/A

##### ANSIBLE VERSION
`$ ansible --version`
> ansible 2.4.0.0
  config file = None
  configured module search path = ['/home/labadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.5/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.5.3 (default, May 11 2017, 09:10:41) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

Installed via pip:
`$ sudo -E pip install ansible`
>Collecting ansible
  Downloading ansible-2.4.0.0.tar.gz (6.6MB)
    100% |████████████████████████████████| 6.6MB 207kB/s
Collecting jinja2 (from ansible)
  Downloading Jinja2-2.9.6-py2.py3-none-any.whl (340kB)
    100% |████████████████████████████████| 348kB 3.8MB/s
Collecting PyYAML (from ansible)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 4.4MB/s
Requirement already satisfied: paramiko in /usr/lib/python3.5/site-packages (from ansible)
Requirement already satisfied: cryptography in /usr/lib64/python3.5/site-packages (from ansible)
Requirement already satisfied: setuptools in /usr/lib/python3.5/site-packages (from ansible)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib64/python3.5/site-packages (from jinja2->ansible)
Requirement already satisfied: pynacl>=1.0.1 in /usr/lib64/python3.5/site-packages (from paramiko->ansible)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/lib64/python3.5/site-packages (from paramiko->ansible)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/lib/python3.5/site-packages (from paramiko->ansible)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/lib/python3.5/site-packages (from cryptography->ansible)
Requirement already satisfied: idna>=2.1 in /usr/lib/python3.5/site-packages (from cryptography->ansible)
Requirement already satisfied: cffi>=1.7 in /usr/lib64/python3.5/site-packages (from cryptography->ansible)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python3.5/site-packages (from cryptography->ansible)
Requirement already satisfied: pycparser in /usr/lib/python3.5/site-packages (from cffi>=1.7->cryptography->ansible)
Installing collected packages: jinja2, PyYAML, ansible
  Running setup.py install for PyYAML ... done
  Running setup.py install for ansible ... done
Successfully installed PyYAML-3.12 ansible-2.4.0.0 jinja2-2.9.6

##### CONFIGURATION
`$ ansible-config dump --only-changed`
>Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fd04f6e2bf8>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fd04f6e2bf8>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fd04f6e2bf8>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fd04f6e2bf8>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fd04f6e2bf8>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fd04f6e2bf8>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fd04f6e2bf8>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable

`$ ansible-config dump --only-changed`
No results

##### OS / ENVIRONMENT
Fedora 24
4.11.12-100.fc24.x86_64

##### SUMMARY
Sporadic/random errors/faults as you can see happened above. Sometimes it runs fine with no errors, sometimes not.

##### STEPS TO REPRODUCE
`$ ansible all -m ping -c ssh -k`

##### EXPECTED RESULTS
Successful execution, no errors

##### ACTUAL RESULTS
`$ ansible all -m ping -c ssh -k`
>SSH password:
localhost | SUCCESS => {
    "changed": false,
    "failed": false,
    "ping": "pong"
}
FED | SUCCESS => {
    "changed": false,
    "failed": false,
    "ping": "pong"
}
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f6f36827158>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f6f36827158>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f6f36827158>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f6f36827158>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f6f36827158>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f6f36827158>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
...

**Comment by goldyfruit** [comment]
Same issue here.

**Ansible version**
```
$ ansible --version
ansible 2.4.0.0
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]
```

**Operating system**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.2 (stretch)
Release:	9.2
Codename:	stretch
```

**Kernel**
```
$ uname -r
4.12.0-0.bpo.2-amd64
```

**Command**
```
$ ansible all -i inventories/bastion/hosts -m setup

Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f22898ba510>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f22898ba510>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f22898ba510>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f22898ba510>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```

**Comment by gundalow** [comment]
1) Do you have a an `ansible.cfg` file, if so what's in it?
2) What does `env | grep -i ansible` return?

**Comment by fligi7** [comment]
1. No ansible.cfg
2. Nothing returned

**Comment by abadger** [comment]
I've seen this before.  Here's the information I have about it:

* This is a warning, not an error.  Ansible should have completed correctly despite these messages
* This is a problem with python, not with Ansible.  See the upstream Python bug for information: https://bugs.python.org/issue29519
  * This should be fixed in newer versions of both Python2 and Python3.
