### ISSUE TITLE
error in installation of ansible via source method in linux

### ISSUE THREAD

**Issue by arun8796** [ansible/ansible#32090]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
installation
##### ANSIBLE VERSION

```

```

##### OS / ENVIRONMENT
LINUX x86_64 x86_64 GNU/Linux

##### SUMMARY

Trying to install ansible as per link https://developers.redhat.com/blog/2016/08/15/install-ansible-on-rhel/ 

via source option and error appears when i run **sudo make install**
Error:- 
Running cffi-1.11.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-flD3qT/cryptography-2.1.2/temp/easy_install-Kx_HqS/cffi-1.11.2/egg-dist-tmp-GF9UCF
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
compiling '_configtest.c':
__thread int some_threadlocal_variable_42;

gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -c _configtest.c -o _configtest.o
unable to execute gcc: No such file or directory
failure.
removing: _configtest.c _configtest.o
compiling '_configtest.c':
int some_regular_variable_42;

gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -c _configtest.c -o _configtest.o
unable to execute gcc: No such file or directory
failure.
removing: _configtest.c _configtest.o

    No working compiler found, or bogus compiler options passed to
    the compiler from Python's standard "distutils" module.  See
    the error messages above.  Likely, the problem is not related
    to CFFI but generic to the setup.py of any Python package that
    tries to compile C code.  (Hints: on OS/X 10.8, for errors about
    -mno-fused-madd see http://stackoverflow.com/questions/22313407/
    Otherwise, see https://wiki.python.org/moin/CompLangPython or
    the IRC channel #python on irc.freenode.net.)
error: Setup script exited with 1
make: *** [install] Error 1

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS
i should be able to ping localhost using ansible

ansible localhost -m ping

##### ACTUAL RESULTS

 ansible localhost -m ping
Traceback (most recent call last):
  File "/bin/ansible", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cryptography

ansible --version
Traceback (most recent call last):
  File "/bin/ansible", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cryptography

```

```

**Comment by gundalow** [comment]
@sakthiom2014 If you follow the steps on http://docs.ansible.com/ansible/latest/intro_installation.html does that work?

**Comment by gundalow** [comment]
needs_info

**Comment by arun8796** [comment]
thanks all.. i tried with centOs and able to install successfuly
