### ISSUE TITLE
Ansible VMware Module for 'VM/Host rules' and 'VM/Host Groups'

### ISSUE THREAD

**Issue by forescout-spollock** [ansible/ansible#32109]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

new module

##### SUMMARY
Missing functionality
reference:  https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.resmgmt.doc/GUID-0591F865-91B5-4311-ABA6-84FBA5AAFB59.html

Functionality should be available in Ansible, it's basic operations for a cluster.

##### ANSIBLE VERSION

```
ansible --version
ansible 2.4.0.0
  config file = /Users/spollock/ansible/fs-vmw-control/ansible.cfg
  configured module search path = [u'/Users/spollock/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]

```

##### CONFIGURATION

ansible-config dump --only-changed
DEFAULT_REMOTE_PORT(/Users/spollock/ansible/fs-vmw-control/ansible.cfg) = 22
DEFAULT_REMOTE_USER(/Users/spollock/ansible/fs-vmw-control/ansible.cfg) = spollock
DEFAULT_TIMEOUT(/Users/spollock/ansible/fs-vmw-control/ansible.cfg) = 30
RETRY_FILES_ENABLED(/Users/spollock/ansible/fs-vmw-control/ansible.cfg) = False

##### OS / ENVIRONMENT

Running from MAC OSX 10.11.6
Running against vSphere 6.5

##### SUMMARY

Missing functionality
reference:  https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.resmgmt.doc/GUID-0591F865-91B5-4311-ABA6-84FBA5AAFB59.html

Functionality should be available in Ansible, it's basic operations for a cluster.
##### STEPS TO REPRODUCE

```yaml
 
```

##### EXPECTED RESULTS

Needed

##### ACTUAL RESULTS

Doesn't work today

```

```

**Comment by Akasurde** [comment]
+label vmware
-label needs_triage

**Comment by forescout-spollock** [comment]
Any update?
