### ISSUE TITLE
Remote lookup plugins?

### ISSUE THREAD

**Issue by zbal** [ansible/ansible#3211]
Is there any way to perform remote lookups on the boxes being managed? (Without going through custom ansible facts)

Several examples;
- have a ENV variable only available on that remote box
- have a DNS entry only worth having on the box (say you are in geo-dns setup)
- etc.

I've seen from the doc that all the lookup are currently ran on the controlling (ansible) box; and wondered if there was anything similar but for the remote boxes.

**Comment by skvidal** [comment]
I am working on a local facts option to the setup module that should let you retrieve custom facts that you set in a Dir on the managed system.

**Comment by mpdehaan** [comment]
Yep, we're going to do something like a /etc/ansible/facts.d/

However you should also look at the 'register' keyword in the docs as it allows all of this without custom facts too, right now :)

**Comment by mpdehaan** [comment]
This exists in 1.3 now, see changelog for details.  Not yet documented yet as not quite released, but there!

(Thanks go to @skvidal for implementation)

**Comment by zbal** [comment]
Sweeeet ! I'll look into it as soon as I can :) thanks @skvidal @mpdehaan 

Side question kinda related; is it possible to get those facts "interpreted" on the remote machine only? or does it still go back to the Ansible server? I've looked into it and it seems a bit painful as we'd have to get those facts imported in various templates and would also require jinja2 to be exported on a per-host run ..
