### ISSUE TITLE
Documentation typo in PUREFA_SNAP module

### ISSUE THREAD

**Issue by sdodsley** [ansible/ansible#32138]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
purefa_snap

##### ANSIBLE VERSION
2.4

##### SUMMARY
Examples for the purefa_snap module reference a variable ```fa_api_token```. This should read ```api_token```

**Comment by jborean93** [comment]
Fixed in https://github.com/ansible/ansible/pull/32140
