### ISSUE TITLE
Inventory pattern matching while running locally

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#32147]
##### ISSUE TYPE

 - Bug Report
 - Documentation Report

##### COMPONENT NAME

yml config

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

```
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
```

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

I am trying to run a playbook locally. I want one role applied to every host that runs this playbook. If the machine's hostname is in the inventory file I want it to apply an additional role or two as well. When I try it now on a machine which is not defined in the inventory, all roles are applied regardless.

##### STEPS TO REPRODUCE

`ansible-playbook -i playbook/hosts playbook/site.yml`

playbook/site.yml:
```yaml
---
- hosts: example-client
  roles:
    - client

- hosts: example-server
  roles:
    - server

- hosts: example-frontend
  roles:
    - frontend
```

playbook/hosts:
```
[example-client]
localhost ansible_connection=local

[example-server]
example-server-hostname ansible_connection=local

[example-frontend]
example-frontend-hostname ansible_connection=local
```

##### EXPECTED RESULTS

- Running `ansible-playbook -i playbook/hosts playbook/site.yml` on a client machine applies only the `client` role.
- Running `ansible-playbook -i playbook/hosts playbook/site.yml` on `example-server-hostname` applies the `client` and `server` roles.
- Running `ansible-playbook -i playbook/hosts playbook/site.yml` on `example-frontend-hostname` applies the `client` and `frontend` roles.

##### ACTUAL RESULTS

- Running `ansible-playbook -i playbook/hosts playbook/site.yml` on a client machine applies all three roles.

Sorry if this is the wrong place for this. If it is a question better asked somewhere else please let me know. Thanks.

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
