### ISSUE TITLE
authorized_keys module fails when pubkey contains UTF-8

### ISSUE THREAD

**Issue by tyll** [ansible/ansible#3214]
If a public key contains UTF-8, e.g. in the comment area after the key, ansible fails to store it:

```
fatal: [hostname] => Traceback (most recent call last):
  File "/github-ansible/lib/ansible/runner/__init__.py", line 344, in _executor
    exec_rc = self._executor_internal(host)
  File "/github-ansible/lib/ansible/runner/__init__.py", line 423, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/github-ansible/lib/ansible/runner/__init__.py", line 577, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/github-ansible/lib/ansible/runner/action_plugins/normal.py", line 54, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/github-ansible/lib/ansible/runner/__init__.py", line 264, in _execute_module
    (remote_module_path, module_style, shebang) = self._copy_module(conn, tmp, module_name, args, inject, complex_args)
  File "/github-ansible/lib/ansible/runner/__init__.py", line 717, in _copy_module
    encoded_args = repr(str(module_args))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 822: ordinal not in range(128)
```

**Comment by mpdehaan** [comment]
Can you please show the line you have in your playbook where you are calling this, and share what version of Ansible you are also using?  (ansible --version)?

**Comment by tyll** [comment]
I am using current git, I call it like this:

```
action: authorized_key user=username key='$FILE(~/.ssh/id_rsa)'
```

**Comment by tyll** [comment]
Here is a minmal working example:
`$ ansible 192.168.123.123  -m authorized_key --user root -a 'user=till key="$FILE(keyfile)"'
192.168.123.123 | FAILED => Traceback (most recent call last):
  File "lib/ansible/runner/__init__.py", line 367, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "lib/ansible/runner/__init__.py", line 451, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "lib/ansible/runner/__init__.py", line 612, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "lib/ansible/runner/action_plugins/normal.py", line 54, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "lib/ansible/runner/__init__.py", line 285, in _execute_module
    (remote_module_path, module_style, shebang) = self._copy_module(conn, tmp, module_name, args, inject, complex_args)
  File "lib/ansible/runner/__init__.py", line 752, in _copy_module
    encoded_args = repr(str(module_args))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 15: ordinal not in range(128)
`

`$ cat keyfile
ä
`

**Comment by tyll** [comment]
ansible 1.3 (devel 4dfbbc4499) last updated 2013/07/05 23:16:38 (GMT +200)

**Comment by tyll** [comment]
Here is a patch that would fix this and shows the problem:
https://github.com/tyll/ansible/commit/0df366a2bf4b28dbd94d653cc2d8af3325db07b5

But I assume it is incomplete.

**Comment by mpdehaan** [comment]
Yes, generalized latin1 encoding seems like that would cause some problems
:)

This was encountered by the authorized_key module and the key parameter,
yes?

**Comment by tyll** [comment]
If ansible used latin1 encoding everyhere internally, the problem would not exist, because latin1 decode().encode() works with any data.

Yes, it was the key paramater in the authorized_key module.

**Comment by bcoca** [comment]
er ... no, not really. It probably works with ALL the data YOU deal with,
but it is not a good encoding to use in general as there are many problems
when you are or deal with data from outside the US and 1/2 of Europe.

**Comment by mpdehaan** [comment]
Correct, utf-8 is a _much_ safer choice for a standard.

In this case, there's probably nothing to tell what encoding is used in the
data supplied, so it's a bit trickier than expected.

**Comment by bcoca** [comment]
Only thing I can think of, add a encoding option, that defaults to utf-8.
You SHOULD know what encoding your own data is in (actually we mostly
assume).

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
That's probably reasonable, but we'd need a way to pass this to the remote
end on the module command line, likely using sys.argv[1] if new style
python modules otherwise
sys.argv[2] for old style modules that still pass the argument file.

**Comment by bcoca** [comment]
ssh normally preserves source host encoding in the terminal, or we can set
it as param, not simple but this might solve many encoding issues in the
end.

On Mon, Jul 15, 2013 at 10:41 AM, Michael DeHaan
notifications@github.comwrote:

> That's probably reasonable, but we'd need a way to pass this to the remote
> end on the module command line, likely using sys.argv[1] if new style
> python modules otherwise
> sys.argv[2] for old style modules that still pass the argument file.
> 
> On Mon, Jul 15, 2013 at 10:38 AM, Brian Coca notifications@github.comwrote:
> 
> > Only thing I can think of, add a encoding option, that defaults to
> > utf-8.
> > You SHOULD know what encoding your own data is in (actually we mostly
> > assume).
> > 
> > ## 
> > 
> > Brian Coca
> > Stultorum infinitus est numerus
> > 
> > 0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
> > 
> > Pedo mellon a minno
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ansible/ansible/issues/3214#issuecomment-20973687>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/3214#issuecomment-20973899
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by tyll** [comment]
> On Mon, Jul 15, 2013 at 8:35 AM, tyll notifications@github.com wrote:
> 
> > If ansible used latin1 encoding everyhere internally, the problem would
> > not exist, because latin1 decode().encode() works with any data.

On Mon, Jul 15, 2013 at 07:21:23AM -0700, Brian Coca wrote:

> er ... no, not really. It probably works with ALL the data YOU deal with,
> but it is not a good encoding to use in general as there are many problems
> when you are or deal with data from outside the US and 1/2 of Europe.

Can you please explain any problem in the current context, e.g. show me
any value for the variable foo where foo.decode("latin1").encode("latin1") does not
return the value for foo? As you can see in the commit comment, it works
for latin1 and utf-8 encoding and I can show you that it works for any
binary data. Also in the current case, it is not really used as an
encoding, because the data is first decoded to get an internal unicode
representation and then later encoded to get the original data back. But
here it works without any need to specify the encoding of the original
data.

**Comment by tyll** [comment]
Btw. here you can test that it works for all characters:
    In [14]: set([chr(x).decode("latin1").encode("latin1") == chr(x) for x in range(0,256)]) == set([True])
    Out[14]: True

**Comment by mpdehaan** [comment]
There are way more than 256 characters.

**Comment by tyll** [comment]
On Mon, Jul 15, 2013 at 09:07:33AM -0700, Michael DeHaan wrote:

> There are way more than 256 characters.

I should have written bytes (which is the C type char), because the code
does not care about the encoding of the underlying data. x ==
x.decode("latin1").encode("latin1") will always be True for each value
of x and it does not matter whether x is UTF-8 encoded or binary data or
whatever. As you can see the commit fixes the handling of
authorized_keys containing UTF-8 characters (and also latin1 characters
or any other binary character), it is just binary safe and does not make
any assumptions. E.g. if you do x.decode("UTF-8") you assume that x is
valid UTF-8 data. Please take a look at the patch and the problem
description and do not just trigger on "latin1" being used, because the
patch is not about encoding data in latin1, but about properly handling
any data read with file lookups. You can use any encoding where
x.decode("foo").encode("foo") == x holds true. Alternatively you could
just use str objects instead of unicode objects internally and skip the
decode/encode steps.

**Comment by mpdehaan** [comment]
I'm not convinced with this, nor with just using unicode internally is
sufficient but I have this in my list to review -- thanks!

**Comment by bcoca** [comment]
except that there are multibyte encodings, which need to examine N number
of them to form a character (utf8 does this).

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by srgvg** [comment]
Just FYI, I bumped into this problem when testing authorized_keys with a random string as ssh_key. I acidently had a non ASCII char in that string. I'm not sure this is a problem as possibly an SSH_KEY contains only ASCII chars; not sure if that's right though. At the very least it would be nice to yield a proper error if  not.

**Comment by bcoca** [comment]
the key itself should be inside the ASCII range, the problem might be the
comments (after key, usually <user>@<host>) or command/filter (before key,

## normally empty) sections which are arbitrary and not 'armored'.

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by tyll** [comment]
On Mon, Jul 15, 2013 at 10:24:08AM -0700, Brian Coca wrote:

> except that there are multibyte encodings, which need to examine N number
> of them to form a character (utf8 does this).

Except what? Can you please provide context. There is nowhere in my code
any restriction to the amount of bytes and as you can see in the commit
example, multibyte UTF8 encodings are handled just fine, because the
code does not care about what the data represents that is stored as
unicode internally. Please give me one example where it does not work.

**Comment by bcoca** [comment]
one that hits me with windows: \u201c

On Mon, Jul 15, 2013 at 2:25 PM, tyll notifications@github.com wrote:

> On Mon, Jul 15, 2013 at 10:24:08AM -0700, Brian Coca wrote:
> 
> > except that there are multibyte encodings, which need to examine N number
> > of them to form a character (utf8 does this).
> 
> Except what? Can you please provide context. There is nowhere in my code
> any restriction to the amount of bytes and as you can see in the commit
> example, multibyte UTF8 encodings are handled just fine, because the
> code does not care about what the data represents that is stored as
> unicode internally. Please give me one example where it does not work.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/3214#issuecomment-20991901
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by bcoca** [comment]
## basically any unicode character that doesn't fit into a byte.

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by tyll** [comment]
On Mon, Jul 15, 2013 at 11:39:27AM -0700, Brian Coca wrote:

> basically any unicode character that doesn't fit into a byte.

Obviously you still did not read the commit, because it already contains
an example for a multibyte UTF-8 encoded character:

| >>> '\xc3\xa4'.decode("latin1").encode("latin1")
| '\xc3\xa4'

As you can see, nothing bad happens.

**Comment by tyll** [comment]
On Mon, Jul 15, 2013 at 11:38:47AM -0700, Brian Coca wrote:

> one that hits me with windows: \u201c

This is not valid python code. Please write a value for a str object
where
    x.decode("latin1").encode("latin1") == x
is False

According to http://www.fileformat.info/info/unicode/char/201c/index.htm
\u201c is '\xe2\x80\x9c', and it works:
    In [8]: '\xe2\x80\x9c'.decode("latin1").encode("latin1")
    Out[8]: '\xe2\x80\x9c'

**Comment by tyll** [comment]
On Mon, Jul 15, 2013 at 11:38:47AM -0700, Brian Coca wrote:

> one that hits me with windows: \u201c

An please do not confuse the proposed code with:
    u'\u201c'.encode("latin1")

which does not work and is not proposed.

**Comment by bcoca** [comment]
yet some windows user can be kind enough to include it in your key file as

## a comment.

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by bcoca** [comment]
The real way to avoid encoding issues with python is treating the file as
true bytes (open with 'rb') but then you loose things like, line splitting,
searching, etc. This actually does what you think latin1 does, treat
everything as a byte (vs assume a 1 byte=> 1 char, which is what latin1
does.

You are not even guaranteed a file, a line or even the same word follows
the same encoding, this is a HARD problem because many people don't
understand it correctly and 'solve' it by breaking it for others but fixing
it for their single use case.

Just read this (the 2 linked documents are also good).
http://blog.lumino.so/2012/08/20/fix-unicode-mistakes-with-python/

So here I offer 2 solutions that should work for the most part. Add a
'encoding' paramater to file (used by copy and template) which defaults to
utf8 and a 'binary' parameter to copy that keeps the file intact no matter
what the encoding. Neither of these are simple/easy to implement, python2
is not very good with encoding (most programming languages aren't).

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by tyll** [comment]
On Mon, Jul 15, 2013 at 12:19:12PM -0700, Brian Coca wrote:

> yet some windows user can be kind enough to include it in your key file as
> a comment.

Yes, please. Do it and it will not fail due to the latin1 de/encoding.

**Comment by tyll** [comment]
On Mon, Jul 15, 2013 at 12:46:37PM -0700, Brian Coca wrote:

> The real way to avoid encoding issues with python is treating the file as
> true bytes (open with 'rb') but then you loose things like, line splitting,

Please read the documentation about open():
http://docs.python.org/2/library/functions.html#open

The "b" in the mode only affects line endings and not encoding.

> searching, etc. This actually does what you think latin1 does, treat
> everything as a byte (vs assume a 1 byte=> 1 char, which is what latin1
> does.

It is not what I think what latin1 does. ansible uses unicode objects
internally and populates them with the file lookup and later creates
string objects again to dump the data in a file. This is not binary safe
as I showed. Using latin1 it is binary safe.

> You are not even guaranteed a file, a line or even the same word follows
> the same encoding, this is a HARD problem because many people don't
> understand it correctly and 'solve' it by breaking it for others but fixing
> it for their single use case.

Yes, and this is what happened with ansible.
.decode("UTF-8").encode("UTF-8") has been used which as I showed breaks
contents, because

```
x.decode("UTF-8").encode("UTF-8") == x
```

is not True for every value of x.

> Just read this (the 2 linked documents are also good).
> http://blog.lumino.so/2012/08/20/fix-unicode-mistakes-with-python/

You should read it, because it actually proves my code. It again says
that x.decode("latin1").encode("latin1") == x holds true.

> So here I offer 2 solutions that should work for the most part. Add a
> 'encoding' paramater to file (used by copy and template) which defaults to
> utf8 and a 'binary' parameter to copy that keeps the file intact no matter
> what the encoding. Neither of these are simple/easy to implement, python2
> is not very good with encoding (most programming languages aren't).

As long as ansible does not modify a file, it does not need to know
which encoding the file has. Do you not wonder why cp does not have an
encoding parameter but
    cp foo bar
works for any file contents?
You only need encoding parameters if you would like to change the
encoding, e.g. if you read a latin1 file and want to store it in UTF-8,
but then you need two parameters, one for the source and one for the
target.

**Comment by mpdehaan** [comment]
The solution here is really to not use lookup plugins to serve up binary
files in the middle of the option lines, which are supposed to be strings.

Enough conversation on this one, we have enough data to play around and see
what _actually_ works.

Thanks!

**Comment by tyll** [comment]
On Mon, Jul 15, 2013 at 01:43:04PM -0700, Michael DeHaan wrote:

> The solution here is really to not use lookup plugins to serve up binary
> files in the middle of the option lines, which are supposed to be strings.

I am not sure what strings are supposed to mean, but currently they are
(sometimes UTF-8 encoded) unicode endpoints. Also this bug report is not
about binary data, e.g. files containing the bytes 0x00-0x1F and 0x7F
(which probably do not create any problem, because they can be encoded
in ASCII), but about a text file containing valid UTF-8 data. It only
helps to think of it as binary data, because it should not matter to
ansible what the file contains.

> Enough conversation on this one, we have enough data to play around and see
> what _actually_ works.

I agree.

**Comment by tyll** [comment]
Btw. there is also one key question unanswered? Why does ansible use
unicode objects internally? I suspect that it is because the data is
transfered as JSON where latin1 encoding/decoding would help again:

```
In [6]: json.loads(json.dumps("\xff".decode("latin1"))).encode("latin1")
Out[6]: '\xff'
In [7]: json.loads(json.dumps("\xff"))
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-7-8d56f163c6b6> in <module>()
----> 1 json.loads(json.dumps("\xff"))
In [8]: json.loads(json.dumps("\xff").decode("utf-8"))
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-8-d89b3823509e> in <module>()
----> 1 json.loads(json.dumps("\xff").decode("utf-8"))
```

**Comment by mpdehaan** [comment]
This is a dup of the 'binary data' ticket, so closing this one.
