### ISSUE TITLE
add hosts directive for import_playbook

### ISSUE THREAD

**Issue by thinkmassive** [ansible/ansible#32173]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
import_playbook

##### ANSIBLE VERSION
```
ansible 2.4.0.0
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### SUMMARY
Large environments may have a playbook for each major part of the environment, each which has multiple plays in-line. In many cases it's desirable to have a single master playbook that includes the other multi-play playbooks. This is possible with `import_playbook`, however every play will still be parsed, which can take a long time and produce a lot of useless output in complex environments.

If `import_playbook` had a `hosts` directive, or some other conditional that only applies to the import statement (instead of simply being passed to every child play), we could have much faster and cleaner execution from a single master playbook in complex environments.

Consider a simplified example with two applications, each which has a multi-tier environment with many hosts and hostgroups, plus some common infrastructure...

Directory structure:
```
ansible-repo/
    inventory
    master.yml
    playbooks/
        appA.yml
        appB.yml
        ops.yml
```

Inventory file (partial--assume appB is similar to appA):
```
[appA:children]
appA_web
appA_db

[appA_web]
appA_web[0-3]

[appA_db]
appA_db[1-2]
appA_db_readonly

[ops]
logs
monitoring

[web:children]
appA_web
appB_web

[db:children]
appA_db
appB_db
```

Each application playbook contains multiple plays (at least one for each hostgroup), and each play consists of many tasks. The master playbook contains some common tasks needed by all hosts, and it imports the other playbooks:

```
---
- hosts: all
  tasks: <common-starting-stuff>

- import_playbook: playbooks/appA.yml
- import_playbook: playbooks/appB.yml
- import_playbook: playbooks/ops.yml

- hosts: all
  tasks <common-ending-stuff>
```

For the sake of brevity this example is greatly simplified, but assume the common plays consist of many tasks and roles, and each application playbook contains tens or hundreds of in-line plays. To accomplish a simple change on a small subset of hosts requires Ansible to parse every play in all 4 playbooks.

As a workaround I have pulled common plays into their own file, which is imported at the beginning of each application playbook. The downside to this approach is that common plays are repeated from every playbook imported by master, even if they only need to run once.

If `import_playbook` offered a `hosts` directive, or anything similar, we could retain the simplicity of a single master playbook that only runs the relevant imported plays:
```
---
- hosts: all
  tasks: <common-starting-stuff>

- import_playbook: playbooks/appA.yml
  hosts: appA

- import_playbook: playbooks/appB.yml
  hosts: appB

- import_playbook: playbooks/ops.yml
  hosts: ops

- hosts: all
  tasks <common-ending-stuff>
```

##### STEPS TO REPRODUCE
n/a

##### EXPECTED RESULTS
Ability to skip `import_playbook` based on some condition

##### ACTUAL RESULTS
`import_playbook` always parses every play within the imported file

**Comment by abitrolly** [comment]
I was about to propose adding `hosts` to `import_playbook` as well, but for a different reason. I need it to limit the scope of imported playbooks.

Imported playbooks in my case contain generic logic, such as installing Python as a prerequisite for Ansible itself:
```
- hosts: all
  gather_facts: no
  pre_tasks:
  - name: python is required
    raw: test -e /usr/bin/python || apt-get -y install python
    register: output
    changed_when: output.stdout != ""
```
The scope is `all` hosts and this is going to work as far as all hosts are Linux Debian based. But this playbook is included by default into many more specific books - webservers.yml, devservers.tml etc. What I want to prevent is disaster when somebody adds new entry onto `hosts` file that doesn't have any `apt-get` or `test` commands. Executing any book then will make it fail. Some hosts also require manual password entry and some users don't have those passwords. When imported playbook tries to run on all hosts, users will see access errors. I also don't want them to touch servers that are out of scope of the main playbook.

**Comment by thinkmassive** [comment]
@abitrolly I believe I have a similar situation, which I currently work around by changing `hosts: all` to `hosts: "{{hostlist}}"`, and then appending `hostlist=<MyHostOrGroup>` to the `import_playbook` item.

For example...

common_setup.yml:
```
- hosts: "{{hostlist}}"
  gather_facts: no
  pre_tasks:
  - name: python is required
  ...
```

appA.yml:
```
- import_playbook: common_setup.yml hostlist=appA
```

appB.yml:
```
- import_playbook: common_setup.yml hostlist=appB
```

If you have a master playbook...
master.yml:
```
- import_playbook: common_setup.yml hostlist=all
```

**Comment by bcoca** [comment]
don't use inline vars var=val, as those have issues and are deprecated, use `vars:`

**Comment by gio-salvador** [comment]
Please select this for deployment at your earliest convenience, this will facilitate reusability of playbooks in many folds.

**Comment by sivel** [comment]
Playbooks require the explicit use of `hosts:`.  The comment made at https://github.com/ansible/ansible/issues/32173#issuecomment-339731817 is the correct way to do this, with the exception of using `vars` instead of inline key=value vars.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
