### ISSUE TITLE
SSH Broken Pipe

### ISSUE THREAD

**Issue by chrisvel** [ansible/ansible#32177]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
SSH ?

##### ANSIBLE VERSION
```
2.4.0.0
```

##### CONFIGURATION
<empty>

##### OS / ENVIRONMENT
Host & guests are the same O/S: 
Manjaro 17.0.5
Kernel: 4.9.53-1-MANJARO
(Clean installs, tried in a Virtualbox VM and two laptops). 

##### SUMMARY
I am using the spark repo to configure a laptop of mine: https://github.com/pigmonkey/spark

Unfortunately I am getting these kind of messages in pacman and aur (listed in "Actual Results" section).

Then the shell halts and after 3-4 minutes it fails. The system I am trying to deploy is a clean install of the latest Manjaro O/S (Arch). Not every role it has fails - I have commended everything out in order to find why this error happens. The OpenSSH server has the default configuration, so nothing fancy here.

**I have downgraded to ansible 2.3 via pip and the issues seem to have dissappeared.** 

##### STEPS TO REPRODUCE
clone the repo and run against any manjaro client

##### ACTUAL RESULTS
```
    <192.168.1.2> (0, '', 'OpenSSH_7.6p1, OpenSSL 1.1.0f  25 May 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: 
    auto- mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: 
    mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: 
    mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 7263\r\ndebug3: mux_client_request_session: session 
    request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r
    \ndebug2: Received exit status from master 0\r\n')
```

**Comment by nitzmahone** [comment]
Just to narrow things down, can you reproduce the issue on 2.4 with `ansible_connection=paramiko`?

**Comment by chrisvel** [comment]
@nitzmahone yes and thanks for the hint! I was able to deploy my host.

**Comment by bcoca** [comment]
closing as per above

**Comment by samdoran** [comment]
Closing per above discussion.
