### ISSUE TITLE
Elastic Search management module

### ISSUE THREAD

**Issue by EddyP23** [ansible/ansible#32179]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ElasticSearchModule

##### SUMMARY

It would be nice to have a module that manages Elastic Search cluster and performs operations like Index creation/deletion, Mapping creation to begin with at least.

The idea is pretty simple, having able to write some simple tasks that manage ES cluster in a usual idemponent way.

Ansible has some modules that send HTTP requests, but you are left to deal with response/error handling yourself, which isn't nice.

##### PULL REQUEST

I might be happy to write a pull request, if this is not in the plans yet, but would be considered as an addition to the ansible module family.

**Comment by nitzmahone** [comment]
cc @ThePixelDeveloper

**Comment by samdoran** [comment]
Closing since this has remained open with no contributors stepping up to implement this and this is not something the Core team plans to implement at this time.
