### ISSUE TITLE
Git module stopped forwarding ssh-agent after updating to 2.4

### ISSUE THREAD

**Issue by theoden-dd** [ansible/ansible#32232]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

git

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/$USER/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

`ansible-config dump --only-changed` prints nothing

##### OS / ENVIRONMENT

Both, local and remote boxes are Ubuntu 16.04 with the latest updates from official repos.

##### SUMMARY

I've got an ssh-key with a passphrase for accessing gitlab.com repos and pretty big deploy script.
Everything _worked just fine_ until an update came from the official repo `deb http://ppa.launchpad.net/ansible/ansible/ubuntu xenial main` around the 19-th of September, 2017.
Now, at version 2.4 deploy script works fully except a git module instruction in a play, which says that git repo is inaccessible. However, when I login to the same server via ssh, I **can** run git commands for the same repo (thanks to ssh-agent forwarding).

##### STEPS TO REPRODUCE

Run the command below in the same environment, and fail.
After, manually login to the server and succeed with an access to the same (gitlab.com) repo.

The only step that fails to work:
```yaml
- name: Setup the Git repo
  git: repo={{ git_repo }} dest={{ repo_path }} version={{ git_branch }} accept_hostkey=yes
  register: git_pull_result
  notify: restart application
```

##### EXPECTED RESULTS

Repo is successfully cloned/pulled.

##### ACTUAL RESULTS

The quoted step says "repo inaccessible", see below:

```
TASK [web : Setup the Git repo] ***************************************************************************************************************************************************************************
fatal: [server-alias]: FAILED! => {"changed": false, "cmd": ["/usr/bin/git", "fetch", "--tags", "origin"], "failed": true, "msg": "Failed to download remote objects and refs:  Permission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"}
```

**Comment by theoden-dd** [comment]
Well, just a couple of hours later came an update to 2.4.1. It seems it fixes the bug.

**Comment by FlavioAlexander** [comment]
Was this solve? I am getting the error with `2.4.1.0`
