### ISSUE TITLE
Add 'placement groups' support to ec2 module.

### ISSUE THREAD

**Issue by mxxcon** [ansible/ansible#3232]
Boto v2.9.5+ supports AWS EC2's placement groups.
Please update Ansible's ec2 module to also support this feature.

https://aws.amazon.com/ec2/faqs/#What_is_a_cluster_placement_group
https://boto.readthedocs.org/en/latest/ref/ec2.html#module-boto.ec2.placementgroup

**Comment by lwade** [comment]
Thanks for the reminder @mxxcon - just submitting a pull request for this now.

**Comment by mpdehaan** [comment]
closing per above
