### ISSUE TITLE
shell module output for various hosts gets intermingled which prevents automatic processing of output

### ISSUE THREAD

**Issue by sjmudd** [ansible/ansible#3233]
I frequently run -m shell -a "...." type output on some database servers I manage. I notice that this produces intermingled output between the output of several different servers. Therefore processing this output to do later work is more complicated.

example of checking the mysql server uptime and replication delay using existing scripts:

[sjmudd@m7 ~]$ ansible ams4-sessmdb -m shell -a "sudo -i mysql_uptime; sudo -i show_replication_status"
mc101sessmdb-01 | success | rc=0 >>
host:  10:40:48 up 3 days, 19:18,  1 user,  load average: 0.01, 0.01, 0.00
mysql: 10:40:48 up 0 days,  1:13, 5 users, 1 slave (mc101sessmdb-01.ams4.prod.booking.com, 5.6.11-log)
Server:            mc101sessmdb-01.ams4.prod.booking.com (5.6.11-log) on /mysql/sess/data/
Instance:          Using default mysql connection information
State:             Waiting for master to send event
Master:            repl_sess@mc101sessmdb-02.ams4.prod.booking.com:3306
Slave IO Running:  Yes
Slave SQL Running: Yes
Replication Delay: 0   [NO REPLICATION DELAY]   

mc102sessmdb-02 | success | rc=0 >>
host:  10:40:48 up 3 days, 19:12,  1 user,  load average: 0.05, 0.05, 0.10
mysql: 10:40:48 up 0 days,  0:36, 4 users, 1 slave (mc102sessmdb-02.ams4.prod.booking.com, 5.6.11-log)
Server:            mc102sessmdb-02.ams4.prod.booking.com (5.6.11-log) on /mysql/sess/data/
Instance:          Using default mysql connection information
State:             Waiting for master to send event
Master:            repl_sess@mc102sessmdb-01.ams4.prod.booking.com:3306
Slave IO Running:  Yes
Slave SQL Running: Yes
Replication Delay: 0   [NO REPLICATION DELAY]   

mc103sessmdb-01 | success | rc=0 >>
host:  10:40:48 up 3 days, 19:09,  1 user,  load average: 0.23, 0.31, 0.26
mysql: 10:40:48 up 0 days,  0:34, 5 users, 1 slave (mc103sessmdb-01.ams4.prod.booking.com, 5.6.11-log)
Server:            mc103sessmdb-01.ams4.prod.booking.com (5.6.11-log) on /mysql/sess/data/
Instance:          Using default mysql connection information
State:             Waiting for master to send event
Master:            repl_sess@mc103sessmdb-02.ams4.prod.booking.com:3306
Slave IO Running:  Yes
Slave SQL Running: Yes
Replication Delay: 0   [NO REPLICATION DELAY]   

mc102sessmdb-01 | success | rc=0 >>
mc101sessmdb-02 | success | rc=0 >>
host:  10:40:48 up 3 days, 19:14,  1 user,  load average: 0.04, 0.15, 0.15
host:  10:40:48 up 3 days, 19:16,  1 user,  load average: 0.00, 0.00, 0.00
mysql: 10:40:48 up 0 days,  0:38, 4 users, 1 slave (mc102sessmdb-01.ams4.prod.booking.com, 5.6.11-log)
mysql: 10:40:48 up 0 days,  0:29, 5 users, 1 slave (mc101sessmdb-02.ams4.prod.booking.com, 5.6.11-log)
Server:            mc102sessmdb-01.ams4.prod.booking.com (5.6.11-log) on /mysql/sess/data/
Server:            mc101sessmdb-02.ams4.prod.booking.com (5.6.11-log) on /mysql/sess/data/
Instance:          Using default mysql connection information
Instance:          Using default mysql connection information
State:             Waiting for master to send event
State:             Waiting for master to send event
Master:            repl_sess@mc102sessmdb-02.ams4.prod.booking.com:3306
Master:            repl_sess@mc101sessmdb-01.ams4.prod.booking.com:3306
Slave IO Running:  Yes
Slave IO Running:  Yes
Slave SQL Running: Yes
Slave SQL Running: Yes
Replication Delay: 0   [NO REPLICATION DELAY]  
Replication Delay: 0   [NO REPLICATION DELAY]   

mc103sessmdb-02 | success | rc=0 >>
host:  10:40:48 up 3 days, 19:07,  1 user,  load average: 0.00, 0.00, 0.00
mysql: 10:40:48 up 0 days,  0:33, 5 users, 1 slave (mc103sessmdb-02.ams4.prod.booking.com, 5.6.11-log)
Server:            mc103sessmdb-02.ams4.prod.booking.com (5.6.11-log) on /mysql/sess/data/
Instance:          Using default mysql connection information
State:             Waiting for master to send event
Master:            repl_sess@mc103sessmdb-01.ams4.prod.booking.com:3306
Slave IO Running:  Yes
Slave SQL Running: Yes
Replication Delay: 0   [NO REPLICATION DELAY]   

mc104sessmdb-02 | success | rc=0 >>
host:  10:40:48 up 10 days, 19:58,  1 user,  load average: 0.00, 0.07, 0.08
mysql: 10:40:48 up 0 days,  0:28, 5 users, 1 slave (mc104sessmdb-02.ams4.prod.booking.com, 5.6.11-log)
Server:            mc104sessmdb-02.ams4.prod.booking.com (5.6.11-log) on /mysql/sess/data/
Instance:          Using default mysql connection information
State:             Waiting for master to send event
Master:            repl_sess@mc104sessmdb-01.ams4.prod.booking.com:3306
Slave IO Running:  Yes
Slave SQL Running: Yes
Replication Delay: 0   [NO REPLICATION DELAY]   

mc104sessmdb-01 | success | rc=0 >>
host:  10:40:48 up 10 days,  1:13,  2 users,  load average: 0.06, 0.10, 0.08
mysql: 10:40:48 up 9 days, 17:31, 7 users, 1 slave (mc104sessmdb-01.ams4.prod.booking.com, 5.6.11-log)
Server:            mc104sessmdb-01.ams4.prod.booking.com (5.6.11-log) on /mysql/sess/data/
Instance:          Using default mysql connection information
State:             Waiting for master to send event
Master:            repl_sess@mc104sessmdb-02.ams4.prod.booking.com:3306
Slave IO Running:  Yes
Slave SQL Running: Yes
Replication Delay: 0   [NO REPLICATION DELAY]   

[sjmudd@m7 ~]$ 

The detail is not that relevant except for the fact that the output gets mixed as can be seen by:

Slave IO Running:  Yes
Slave IO Running:  Yes
Slave SQL Running: Yes
Slave SQL Running: Yes
Replication Delay: 0   [NO REPLICATION DELAY]  
Replication Delay: 0   [NO REPLICATION DELAY]   

While keeping the output and showing when it's complete may not be sensible perhaps it would be possible to add a prefix to each line of text with say the hostname as then the full output can be easily filtered on say hostname, to collect the output for that host and then later process it.

Perhaps I'm missing how to use ansible for this type of process and may be I should be looking at other ansible modules. Nevertheless there will "always" (?) be a need to do adhoc work on several servers and the ansible shell module makes that much easier, but only if it's easier to identify from which server the output is being produced.

Seen this on 
[sjmudd@m7 ~]$ ansible --version
ansible 1.1

on Mac OS X but I imagine this is a generic issue.

**Comment by bcoca** [comment]
ansible has a -t <dir> option, it will save a jsonified stdout/stderr per
machine if you want nice and tidy and separate output.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by sjmudd** [comment]
I was not aware of the -t option and yes it does produces the json output you mention. So thanks for the hint.
I was surprised that even using the -t option output still goes to stdout. I had been expecting output to go to one location or the other.
That said generating json may be good for some things but simple shell scripts or even other language scripts need "a bit more work" parsing json than just parsing the output from the relevant shell command.

So maybe an option to produce "tee output" in other formats: (1) stderr/stdout to a single file perhost with perhaps a summary line or (2) files of the form hostname.stderr, hostname.stdout, hostname.status (containing the entries in the json file), something like:

changed: true
cmd: mount | grep /mysql/dw
delta: 0:00:00.004545
end: 2013-06-18 00:06:20.975457
rc: 0
start: "2013-06-18 00:06:20.970912

All of which is easy to grep on use simple shell commands to obtain the needed info.

This was one reason I'd suggested a hostname: prefixed output to the "normal output" as that is trivial to process and filter once the ansible command has finished running.

**Comment by bcoca** [comment]
As a shell pipe fan myself I completely understand, just pointed to
existing feature that approximated to your needs. In previous job I had a
script that dejsonified this output for such usage, its on my list to
create a new public version.

In any case you should be able to create/patch the callback to do this.

---

Brian Coca

**Comment by mpdehaan** [comment]
this should already be fixed in Ansible 1.2 which has a flock to prevent intermingled output

Let me know if you are seeing this in 1.2
