### ISSUE TITLE
Lookup plugin flattens single-element lists

### ISSUE THREAD

**Issue by andriilahuta** [ansible/ansible#32348]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

lookup plugin

##### ANSIBLE VERSION

```
Latest ansible devel:
ansible 2.5.0
  config file = 
  configured module search path = 
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.2 (default, Sep 14 2017, 22:51:06) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

None

##### OS / ENVIRONMENT

Ubuntu
##### SUMMARY

Lookup plugin runner (`ansible.template.Templar._lookup`) flattens single-element lists.
The problem seems to lie here:
https://github.com/ansible/ansible/blob/4a19482413bf2542b01d5d5fe74019dee3dbf4b9/lib/ansible/template/__init__.py#L605-L611
#31528 might be related.

##### STEPS TO REPRODUCE

```yaml
- debug: msg='{{ lookup('items', [1]) }}'
```

##### EXPECTED RESULTS

```
ok: [...] => {
    "msg": [
        1
    ]
}
```

##### ACTUAL RESULTS

```
ok: [...] => {
    "msg": "1"
}
```

**Comment by sivel** [comment]
This is expected and was part of the fix to resolve issues in https://github.com/ansible/ansible/issues/14541

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by andriilahuta** [comment]
Shouldn't it be documented then?
Also it reduces flattened/items lookups usability with the new `loop` keyword.

**Comment by sivel** [comment]
`loop` does not require the use of the `items` lookup as it natively accepts a list.  Running it through the `items` lookup would be unnecessary.

**Comment by andriilahuta** [comment]
In some cases I need to flatten it first. So `loop` will fail for such a construct: `{{ lookup('flattened', [[1]]) }}`, but will work for `{{ lookup('flattened', [[1, 2]]) }}`

**Comment by andriilahuta** [comment]
Problem solved. Turns out I should've passed `wantlist=True` to lookup.
