### ISSUE TITLE
allow to specify a header in the copy module

### ISSUE THREAD

**Issue by tyll** [ansible/ansible#3234]
add a parameter header that can be used like

header="# {{ansible_managed}}"

or similar to add a header to copied files to identify them as ansible-managed and to show include the timestamp of the change.

**Comment by bcoca** [comment]
how would you know the files are different? currently we rely on md5, which
would always be different if the file includes a timestamp generated at
runtime.

In any case the file should already have a timestamp (filesystem) that can
tell you that w/o having ansible put it inside.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by tyll** [comment]
The header can be removed prior to calculating the checksum. IIRC the ansible_managed variable contains more detailed information than just the timestamp and especially a note that ansible is used to manage said file. The template module already supports this if one uses it instead of the copy module and adds the header manually to the input file, but it is much more cumbersome.

**Comment by bcoca** [comment]
and if the remote file has the previous header? you need to remove that
also?

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by tyll** [comment]
You only need to remove the header from the remote file. My approach would be to calculate the md5sum of the local input file and the md5sum of the remote file without the first line if a header parameter is set. If both are equal, then no change needs to occur. Otherwise the header is added to the local file and the result stored as the new remote file.

**Comment by mpdehaan** [comment]
This is too involved to be computationally efficient for the copy module as the remote md5sum code would have to tell if there was an Ansible managed line, without knowing what the value of that line would be, and would need to remove it prior to the md5 check.

**Comment by tyll** [comment]
Would you please show me how to add a parameter to the copy module, then I can provide a patch. Even after I added header to the argument_spec of copy ansible complained that the argument is not supported: http://paste.fedoraproject.org/19317/37154697/
I error I modified in module_common.py is always triggered.
