### ISSUE TITLE
Script plugin error handling fix not cherry-picked to 2.4-stable branch

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible#32341]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Inventory script plugin

##### ANSIBLE VERSION
2.4.0.0

Important bit:
```
[WARNING]: * Failed to parse /tmp/awx_58_88J1ON/inventory with script plugin:
local variable 'err' referenced before assignment
File "/usr/lib/python2.7/site-packages/ansible/plugins/inventory/script.py", line 99, in parse
raise AnsibleError("failed to parse executable inventory script results from {0}: {1}\n{2}".format(path, to_native(e), err))
```

##### CONFIGURATION
Ansible 2.4.0.0

##### OS / ENVIRONMENT
AWX, Ubuntu 16.04

##### SUMMARY
Script plugin encountered error, but error is unknown because of another error that gets thrown when formatting the error message.

This has already been solved in `devel` branch, but I see no indication that it will be released in the 2.4.x series, and I think it should be.

Please, just cherry-pick https://github.com/ansible/ansible/commit/cf938e99926a384303c1e291e47770d8f9c74b85 into the 2.4 branch.

##### STEPS TO REPRODUCE
See related AWX issue this is just a re-filing in Ansible.

https://github.com/ansible/awx/issues/524

##### EXPECTED RESULTS
The error message formatting does not fail due to undefined variable.

##### ACTUAL RESULTS
This code is obviously failing because `err` isn't defined.

https://github.com/ansible/ansible/blob/2c4cb42337b191b682c0236931ff2a33281fd6dc/lib/ansible/plugins/inventory/script.py#L98-L99

`err` is not defined because the subprocess running the script produces no stderr.

https://github.com/ansible/ansible/blob/2c4cb42337b191b682c0236931ff2a33281fd6dc/lib/ansible/plugins/inventory/script.py#L83-L84

This is a programming error, and it is fixed by https://github.com/ansible/ansible/commit/cf938e99926a384303c1e291e47770d8f9c74b85, please cherry-pick it onto branch `stable-2.4` for the next release in that series.

**Comment by mattclay** [comment]
Cherry picked to stable-2.4 in https://github.com/ansible/ansible/commit/f00f2466d47852b2460f8f2efddc6a0f060ecc72
