### ISSUE TITLE
rabbitmq_user module doesn't change password without force

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#3237]
the rabbitmq_user account won't change the password of an existing user unless the force paramter is used. For example, this doesn't do what you would expect:

```
rabbitmq_user: user=guest password=newpasswordhere
```

On the other hand, this does the right thing:

```
rabbitmq_user: user=guest password=newpasswordhere force=yes
```

Ideally, we would fix rabbitmq_user, but at a minimum the docs should be updated to reflect this.

**Comment by mpdehaan** [comment]
Want to send in a docs patch?
