### ISSUE TITLE
lost control rhel verion 5

### ISSUE THREAD

**Issue by raynewstar** [ansible/ansible#32380]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

ansible
##### ANSIBLE VERSION

```
2.4.0.0-5.el7
```

##### OS / ENVIRONMENT

CentOS Linux release 7.4.1708
##### SUMMARY

After upgrading to version 2.4, I lost control of the group by the servers which consists of the version Oracle Linux 5, RHEL 5, Centos 5.
Another version OS 6 and 7 I can control.
##### STEPS TO REPRODUCE

ansible 10.2.7.219 -m ping

10.2.7.219 | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 14339\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to 10.2.7.219 closed.\r\n", 
    "module_stdout": "  File \"/tmp/ansible_rwj8fy/ansible_module_command.py\", line 191\r\n    out = b''\r\n            ^\r\nSyntaxError: invalid syntax\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

```yaml

```

##### ACTUAL RESULTS

Made the version rollback on ansible-2.3.2.0-2.el7 and work again.

ansible 10.2.7.219 -m ping
10.2.7.219 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}

```

```

**Comment by jborean93** [comment]
Hi, Ansible 2.4 has changed the required for Python to be on 2.6 or newer. RHEL 5 came with Python 2.4 by default. You can either

* Install a newer version of Python and set `ansible_python_interpreter` to this newer version
* Keep on using 2.3 for your older hosts
* Upgrade to a newer OS which come with a newer version of Python

http://docs.ansible.com/ansible/latest/intro_installation.html#managed-node-requirements
