### ISSUE TITLE
Ansible 2.4 does not find inventory file in CWD

### ISSUE THREAD

**Issue by peteeckel** [ansible/ansible#32383]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
inventory plugin

##### ANSIBLE VERSION
    ansible 2.4.1.0
      config file = /Users/pete/.ansible.cfg
      configured module search path = [u'/Users/pete/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
      ansible python module location = /usr/local/Cellar/ansible/2.4.1.0/libexec/lib/python2.7/site- packages/ansible
      executable location = /usr/local/bin/ansible
      python version = 2.7.14 (default, Sep 25 2017, 09:53:17) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

##### CONFIGURATION
    CACHE_PLUGIN(/Users/pete/.ansible.cfg) = jsonfile
    CACHE_PLUGIN_CONNECTION(/Users/pete/.ansible.cfg) = ~/.ansible-facts.json
    CACHE_PLUGIN_TIMEOUT(/Users/pete/.ansible.cfg) = 86400
    DEFAULT_GATHERING(/Users/pete/.ansible.cfg) = smart
    DEFAULT_GATHER_TIMEOUT(/Users/pete/.ansible.cfg) = 60
    DEFAULT_HOST_LIST(/Users/pete/.ansible.cfg) = [u'/Users/pete/hosts']
    DEFAULT_ROLES_PATH(/Users/pete/.ansible.cfg) = [u'/Users/pete/Documents/Ansible/roles']
    DEFAULT_TIMEOUT(/Users/pete/.ansible.cfg) = 60
    DEFAULT_VAULT_PASSWORD_FILE(/Users/pete/.ansible.cfg) = /Users/pete/.ansible-vault.pass
    HOST_KEY_CHECKING(/Users/pete/.ansible.cfg) = False
    RETRY_FILES_ENABLED(/Users/pete/.ansible.cfg) = False

##### OS / ENVIRONMENT
macOS X 10.11.6, ansible installed via homebrew

##### SUMMARY
My configuration file contains the following setting for the inventory file: 

    [defaults]
    inventory=hosts

##### STEPS TO REPRODUCE
Minimal setup: 

    $ cat ~/.ansible.cfg
    [defaults]
    inventory=hosts

    $ pwd 
    /Users/pete/test

    $ ls
    hosts    test.yml

    $ cat hosts
    [all]
    localhost

    $cat test.yml
    #!/usr/bin/env ansible-playbook

    - name: test
      hosts: all
      tasks: []

##### EXPECTED RESULTS
Test with Ansible 2.3.2:

    $ ansible --version 
    ansible 2.3.2.0
      config file = /Users/pete/.ansible.cfg
      configured module search path = Default w/o overrides
      python version = 2.7.14 (default, Sep 25 2017, 09:53:17) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

$ ./test.yml 

    PLAY [test] ************************************************************************************************************************

    TASK [Gathering Facts] *************************************************************************************************************
    ok: [localhost]

    PLAY RECAP *************************************************************************************************************************
    localhost                  : ok=1    changed=0    unreachable=0    failed=0 

##### ACTUAL RESULTS
Test with Ansible >= 2.4:

    $ ansible --version 
    ansible 2.4.1.0
      config file = /Users/pete/.ansible.cfg
      configured module search path = [u'/Users/pete/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
      ansible python module location = /usr/local/Cellar/ansible/2.4.1.0/libexec/lib/python2.7/site-packages/ansible
      executable location = /usr/local/bin/ansible
      python version = 2.7.14 (default, Sep 25 2017, 09:53:17) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

    $ ./test.yml 
     [WARNING]: Unable to parse /Users/pete/hosts as an inventory source

     [WARNING]: No inventory was parsed, only implicit localhost is available

     [WARNING]: Could not match supplied host pattern, ignoring: all

     [WARNING]: provided hosts list is empty, only localhost is available

    PLAY [test] ************************************************************************************************************************
    skipping: no hosts matched

    PLAY RECAP *************************************************************************************************************************

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Relative paths in the configuration file are relative to the file itself, 2.4.1 fixed a bug in which some configuration items defaulted to cwd, this is considered a security flaw. There is a `{{CWD}}` macro  you can use if you insist on relying on this behaviour.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by peteeckel** [comment]
Hi, 

> We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.
> 
> Relative paths in the configuration file are relative to the file itself, 2.4.1 fixed a bug in which some configuration items defaulted to cwd, this is considered a security flaw. There is a {{CWD}} macro you can use if you insist on relying on this behaviour.

perfect, thanks a lot. That change slipped my attention. 

I understand that this behaviour is insecure, but I need it in a development context with several Vagrant environments (which are inherently insecure anyway) that have different inventories, and where putting a specific ansible.cfg file in place for every setup did not seem really practical. 

Thanks again, 

  Peter.

**Comment by markstos** [comment]
@bcoca It would be hepful if "DEFAULT_HOST_LISTS" documented how relative paths are handled. It could clarify if they are supported and what they relative, too.
