### ISSUE TITLE
WinRM connection Error during playbook execution

### ISSUE THREAD

**Issue by sanjeevrg473** [ansible/ansible#32395]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- WinRM
- win_reboot
- wait_for_connection

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /xxx/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
```

##### SUMMARY

I am executing 2 roles. First role does the server roles+feature install and 2nd role installs core packages. After server roles and features install I have win_reboot module that reboots the systems and waits for 900 seconds. I also added wait_for_connection. After this step it should move on to the next role of copy files to the remote windows machine. I get connection refused error.

After the first role execution ansible should pick the connection after reboot and continue with the second role

##### STEPS TO REPRODUCE

ansible-playbook server.yaml
- hosts: xxxx
  gather_facts: yes

  roles:
    - { role: xxx, when: ansible_os_family == "Windows", tags: ['xxx']  }
    - { role: xxx, when: ansible_os_family == "Windows", tags: ['xxx'] }

Inside the first role I have the below tasks:

  - name: install server roles and features
    win_feature:
      name: Application-Server, AS-NET-Framework, FS-FileServer, Storage-Services, Remote-Desktop-Services, NFS-Client, Telnet-Client, NET-Framework-Core, Desktop-Experience
      state: present
      restart: False
      include_management_tools: True
  - name: check server state
    win_reboot:
      shutdown_timeout: 900
      reboot_timeout: 900
  - name: Wait for system to become reachable over WinRM
    wait_for_connection:
      timeout: 500

```yaml

```

##### EXPECTED RESULTS

It should continue executing the second role
##### ACTUAL RESULTS

Execution failed...

TASK [windows-pre : install server roles and features] ************************************************************************************************************************
changed: [xxx]

TASK [windows-pre : check server state] ***************************************************************************************************************************************
changed: [xxx]

TASK [windows-pre : Wait for system to become reachable over WinRM] ***********************************************************************************************************
ok: [xxx]

TASK [windows-core : copy files] ***********************************************************************************************************
 [WARNING]: FATAL ERROR DURING FILE TRANSFER: Traceback (most recent call last):   File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 273, in
_winrm_exec     self._winrm_send_input(self.protocol, self.shell_id, command_id, data, eof=is_last)   File "/usr/lib/python2.7/site-
packages/ansible/plugins/connection/winrm.py", line 253, in _winrm_send_input     protocol.send_message(xmltodict.unparse(rq))   File "/usr/lib/python2.7/site-
packages/winrm/protocol.py", line 207, in send_message     return self.transport.send_message(message)   File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 184,
in send_message     response = self.session.send(prepared_request, timeout=self.read_timeout_sec)   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 596, in
send     r = adapter.send(request, **kwargs)   File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 471, in send     raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ConnectionError: HTTPSConnectionPool(host='xxxx', port=5986): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f986042ee50>: Failed to establish a new connection: [Errno 111] Connection refused',))
fatal: [xxx]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
        to retry, use: --limit @/opt/eetnfs/ansible/playbooks/sample.retry

PLAY RECAP ********************************************************************************************************************************************************************
xxxx   : ok=17   changed=12   unreachable=0    failed=1

```

```

**Comment by jhawkesworth** [comment]
I wonder if the features you are installing require multiple reboots to install?  If so the connection could be disappearing.  Worth making sure no pending windows updates, and automatic maintenance isn't running too.

**Comment by sanjeevrg473** [comment]
@jhawkesworth Yes the features and roles need multiple restarts. I am not sure how many. Do you have any solution on what I should do?

**Comment by jhawkesworth** [comment]
Not really, but there are things you can try.

You could maybe split up the win_feature into multiple steps and work out which ones require reboots.

Or you could insert a long playbook pause before the wait_for_connection (with a when condition on it).

Or perhaps you could move the win_reboot, the long pause and wait_for_connection into a handler and just use a notify for the handler on the win feature.  Sure you might have to wait 10 minutes the first time the playbook is run, but on subsequent runs, if no new features are installed (which you aren't going to do often, probably) then the handler won't fire so no reboot will take place).

If you have a virtualisation environment I guess you could watch the vm  and time how long it takes to go through all of the necessary reboots, then add a bit and use that as the length of time for your pause step.

I don't really think this is an issue with ansible per se, rather the way windows works so I'm going to close this issue.  User questions like this are best asked on ansible-project or in #ansible or #ansible-windows irc channels (because more people will see them than in the github issue tracker).
