### ISSUE TITLE
Mount action doesn't work on FreeBSD

### ISSUE THREAD

**Issue by geoffgarside** [ansible/ansible#3241]
The mount action currently isn't working on FreeBSD as the command path is hard coded to `/bin/mount` rather than `/sbin/mount`. Is there any functionality for platform variances in terms of the implementations of the library actions?

**Comment by bcoca** [comment]
please test, had this 'done' for a while but don't have testing machines
right now

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno
