### ISSUE TITLE
Exact filename required for roles/X/tasks/main.yml

### ISSUE THREAD

**Issue by ninetythirty** [ansible/ansible#3248]
main.yml must be named main.yml. main.yaml fails.

**Comment by mpdehaan** [comment]
main.yml must be named main.yml is a true statement, if not a tautology.

Insufficient information in bug report to understand what problem you are actually seeing.

If this is a question, please stop by the mailing list and we'll get you sorted out.

Thanks!

**Comment by ninetythirty** [comment]
The problem is that main task files with the name "main", containing valid YAML, differing only by a common variant suffix (e.g. "main.yaml") fail because Ansible looks for "main.yml" only. This is unexpected behavior.

**Comment by srgvg** [comment]
What @ninetythirty meant, AFAICS: as we already support the optional extensions yml or yaml for group vars and host vars, I suppose it might be consequent to support this also within roles.

**Comment by mpdehaan** [comment]
This is why doing that other thing was a trap.

I will accept patches to allow this, sure!

**Comment by ninetythirty** [comment]
@mpdehaan, I'll submit a patch in the next day or two. Do you want to allow main/main.yml/main.yaml, or just main.yml/main.yaml, or ?
