### ISSUE TITLE
azure resource providers can not be registered to Azure subscription used by ansible CI environment

### ISSUE THREAD

**Issue by yaweiw** [ansible/ansible#32481]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```

```

##### SUMMARY

{
"changed": false, 
"msg": "Error creating / updating the ACR instance: Azure Error: MissingSubscriptionRegistration\nMessage: The subscription is not registered to use namespace 'Microsoft.ContainerRegistry'. See https://aka.ms/rps-not-found for how to register subscriptions.\nException Details:\n\tError Code: MissingSubscriptionRegistration\n\tMessage: The subscription is not registered to use namespace 'Microsoft.ContainerRegistry'. See https://aka.ms/rps-not-found for how to register subscriptions.\n\tTarget: Microsoft.ContainerRegistry"
}
##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by yaweiw** [comment]
PR #32336 added a method in azure_rm_common e.g. register_namespace that registers the missing azure resource provider into the subscription. But CI still claimed that 'Azure Error: MissingSubscriptionRegistration\nMessage: The subscription is not registered to use namespace 'Microsoft.ContainerRegistry'.

The fix has been proven working locally. For example, one of my subs doesn't have 'TrendMicro.DeepSecurity' registered. Set a bp at register_namespace and call self.register('TrendMicro.DeepSecurity') leads to the resource provider shown as registered.
PS Azure:\> Get-AzureRmResourceProvider -ListAvailable | Select-Object ProviderNamespace, RegistrationState

ProviderNamespace                        RegistrationState
-----------------                        -----------------
Microsoft.ClassicCompute                 Registered
Microsoft.ClassicStorage                 Registered
Microsoft.ContainerRegistry              Registered
Microsoft.ContainerService               Registered
Microsoft.Network                        Registered
Microsoft.ServiceBus                     Registered
Microsoft.Sql                            Registered
Microsoft.Storage                        Registered
Microsoft.Web                            Registered
TrendMicro.DeepSecurity                  Registered
84codes.CloudAMQP                        NotRegistered
AppDynamics.APM                          NotRegistered
Aspera.Transfers                         NotRegistered
Auth0.Cloud                              NotRegistered
Citrix.Cloud                             NotRegistered

**Comment by yaweiw** [comment]
@gundalow
@jborean93
@mattclay
@nitzmahone
@ryansb
@shertel
@thaumos

**Comment by yaweiw** [comment]
@haroldwongms @tstringer @xscript @zikalino FYI

**Comment by mattclay** [comment]
@yaweiw `Microsoft.ContainerRegistry` has been registered. Is this issue resolved now?

**Comment by yaweiw** [comment]
@mattclay yeah mate. it's resolved! Thanks. Please also help review the PR #32336
