### ISSUE TITLE
ansible_pass is ignored

### ISSUE THREAD

**Issue by dcotruta** [ansible/ansible#32493]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ansible-playbook

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = SOMETHING/PRIVATE/ansible.cfg
  configured module search path = ['SOMETHING/PRIVATE/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = SOMETHING/PRIVATE/.local/lib/python3.5/site-packages/ansible
  executable location = SOMETHING/PRIVATE/.local/bin/ansible
  python version = 3.5.2 (default, Sep 14 2017, 22:51:06) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST( SOMETHING/PRIVATE/rabbitmq/ansible.cfg) = ['SOMETHING/PRIVATE/rabbitmq/inventory']
```

##### OS / ENVIRONMENT
 
Ubuntu 16.04 on both

##### SUMMARY
ansible-playbook ignores ansible-pass setting in hosts file

##### STEPS TO REPRODUCE
Create a playbook.
Add a host that you can connect to using a password.
Add ansible-pass: SOMEPASSWORD (use a vault if you like) in the host's configuration.
Try to run the playbook aimed at that host.
Fail.

```
all:
  hosts:
    SOME_NAME:
      ansible_host: SOME_HOST
      ansible_user: "SOME_USER"
      ansible_pass: "SOME_PASSWORD"
```

##### EXPECTED RESULTS

That I would be able to set a password in the hosts file for a host and therefore be able to execute my playbook.

##### ACTUAL **RESULTS**

The playbook fails to run as the password is ignored and the ssh command is run with PasswordAuthentication=no. SSH part of the connection attempt below

```
 SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o P
asswordAuthentication=no -o User=SOME_USER -o ConnectTimeout=10 -o ControlPath=SOMETHING/PRIVATE/.ansible/cp/0080a0a05d 172.16.8.77 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<SOME_HOST> (255, b'', b'Permission denied (publickey,password).\r\n')
```

##### IMPORTANT NOTES

Yes, this works if I use --ask-pass but then what's the point of the setting? This is a bug. I am happy to investigate and produce a PR for it, if that is OK.

**Comment by dcotruta** [comment]
I am silly. I read about the deprecation of ansible_ssh_user to ansible_user and then went code blind and saw ansible_pass where the docs actually read ansible_ssh_pass. May be worthwhile thinking about deprecating ansible_ssh_pass to ansible_pass as that same setting is used for RDP, etc...
Apologies.

My other ticket stands, it's not based on this one.

**Comment by bcoca** [comment]
it would still not be `ansible_pass`, `ansible_password` is the 'generic' version, then each connection plugin can have it's own overriding version.

**Comment by karniemi** [comment]
ansible_password does not seem to be documented, though.
