### ISSUE TITLE
Ansible RPM installation not picking up non-standard Python installation

### ISSUE THREAD

**Issue by ristillu** [ansible/ansible#32498]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/toby/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Apr 12 2017, 06:56:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### SUMMARY

Fresh installation of 2.4.1.0 (and 2.4.0.0) using yum install rpm, which picks up the standard OS python installation at /usr/lib/python2.7/site-packages despite my system using SCL python and PYTHONPATH only referring to the SCL version of Python.

##### STEPS TO REPRODUCE

```
from ansible.vars import VariableManager
```

##### EXPECTED RESULTS
>>> from ansible.vars import VariableManager
>>>

##### ACTUAL RESULTS
>>> from ansible.vars import VariableManager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ansible.vars
>>>

```
>>> from ansible.vars import VariableManager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ansible.vars

>>> import os
>>> print os.environ['PYTHONPATH'].split(os.pathsep)
['/opt/rh/devtoolset-6/root/usr/lib64/python2.7/site-packages', '/opt/rh/devtoolset-6/root/usr/lib/python2.7/site-packages', '/opt/rh/devtoolset-6/root/usr/lib64/python2.7/site-packages', '/opt/rh/devtoolset-6/root/usr/lib/python2.7/site-packages', '/opt/rh/devtoolset-6/root/usr/lib64/python2.7/site-packages', '/opt/rh/devtoolset-6/root/usr/lib/python2.7/site-packages']
```

**Comment by nitzmahone** [comment]
I'm not aware of a way to get our current RPM builds working with arbitrary SCL-hosted Pythons. You'd probably have better luck installing via `pip` or from source. If you've got knowledge of such things and would like to pitch in on getting RPM installs working with SCLs, feel free to stop by during a core IRC meeting and bring it up.
