### ISSUE TITLE
ERROR! A worker was found in a dead state

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#32554]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

Unknown

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.5.0 (devel 53940670fd) last updated 2017/11/03 00:16:06 (GMT -500)
  config file = None
  configured module search path = [u'/Users/tanner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/ansible.git/ansible/lib/ansible
  executable location = /Users/tanner/projects/ansible.git/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION

$ ansible-config dump --only-changed

##### OS / ENVIRONMENT

Ansible host: macOS 10.12.6
Managed hosts: various Window releases

##### SUMMARY

Random Window hosts hang on random tasks eventually timing out with the message, "ERROR! A worker was found in a dead state"

##### STEPS TO REPRODUCE

As stated above this happens on random tasks. Listed a couple of the tasks below.

```yaml
- name: remove old/deprecated packages (choco)
  win_chocolatey:
    name: "{{ item }}"
    state: "absent"
  when:
    - chocolatey_remove_packages is defined
  with_items:
      - "{{ chocolatey_remove_packages }}"
```
```yaml
- name: Window updates
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    log_path: C:\temp\ansible_win_updates.log
  register: updates 
```

##### EXPECTED RESULTS

Random tasks would not hang and time out.

##### ACTUAL RESULTS

```
$  ANSIBLE_DEBUG=1 ansible-playbook -i testing ../windows.yml -vvvv -f1
<PC147> ESTABLISH WINRM CONNECTION FOR USER: Administrator@LAB on PORT 5986 TO PC147
 19323 1509722061.85590: RUNNING CLEANUP
ERROR! A worker was found in a dead state
```

**Comment by jhawkesworth** [comment]
Hey, noticed you are running from a mac - just wondering if you are hitting the maxfiles limit? - described and workaround here: https://github.com/ansible/ansible/issues/12259#issuecomment-137962724

I suggest having a look at your os logging messages (sorry don't know exact location for macOS) - /var/log/syslog type of thing to see if there are any clues in there.

Hope this helps.

Jon

**Comment by basictheprogram** [comment]
Won't the -f1 limit the forks to just one? Because I thought it was a thread issue I -f1 to reduce that risk.

Also nothing in logs

```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 4864
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited
```

**Comment by jhawkesworth** [comment]
Sorry, I missed that you had set -f1

Are the modules that it is failing on taking longer than usual to run?

If there is a nothing in the syslog on your controller, I suggest having a look look on the machines that are affected.

This might be irrelevant but I had an issue recently where a Windows box timed out on a wait_for_connection following a reboot. When I logged into the vm it was 100 ‰ cpu usage, all being eaten by tiworker process, which is a sign that automatic maintenance is running. The vm was single cpu so we just had to wait for the maintenance to finish. From what I have read, if there is an update to dot Net, maintenance will recompile all of the dot net code it can, so this can take a while. By default it only uses a single cpu so on multi cpu systems it doesn't max out available cpu. 

Otherwise I am a bit out of ideas. 

Jon

**Comment by basictheprogram** [comment]
This is continues to be a problem. Always with 
```yaml
- name: remove old/deprecated packages (choco)
  win_chocolatey:
    name: "{{ item }}"
    state: "absent"
  when:
    - chocolatey_remove_packages is defined
  with_items:
      - "{{ chocolatey_remove_packages }}"
```
But random hosts. Super frustrating that I don't know how to report anymore information then what's in this ticket.

**Comment by LuckySB** [comment]
try version 2.3.0

ansible 2.4.0+ has many memory-leaks and got overmuch memory when run 

PS: i make and use devel version from commit e9c9473819
ansible-2.4.0-100.git201708150932.e9c9473819.devel.el7.centos

**Comment by basictheprogram** [comment]
Updating info. 

New ansible. 
Same task, same problem. 
Still using -f1 to reduce threading issue.
```
$ ansible --version
ansible 2.5.0 (devel 9e09a9ea61) last updated 2017/12/20 22:12:04 (GMT -500)
  config file = None
  configured module search path = [u'/Users/tanner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/ansible.git/ansible/lib/ansible
  executable location = /Users/tanner/projects/ansible.git/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```
```yaml
- name: remove old/deprecated packages (choco)
  win_chocolatey:
    name: "{{ item }}"
    state: "absent"
  when:
    - chocolatey_remove_packages is defined
  with_items:
      - "{{ chocolatey_remove_packages }}"
```
```yaml
- name: Window updates
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    log_path: C:\temp\ansible_win_updates.log
  register: updates 
```
```shell
$ ansible-playbook -i testing ../windows.yml  --limit="windows7,windows10"   -f1
ERROR! A worker was found in a dead state
```
When ansible appears hung but before it errors out a dtruss shows the below over and over
```
96766/0x109cdfe:  select(0x0, 0x0, 0x0, 0x0, 0x7FFF584CB638)		 = 0 0
96766/0x109cdfe:  wait4(0x17ADA, 0x7FFF584CAD9C, 0x1)		 = 0 0
```
So python is waiting on something, but if I read the select correct, all the fds are NULL? Something stomp them?

Hangs here, which is not where I expected it to hang.
```
  2326 1513832251.98624: done with get_vars()
  2326 1513832251.98645: done getting variables
  2326 1513832251.98654: entering _queue_task() for surface148/win_updates
  2696 1513832252.00143: Loading Connection 'winrm' from /Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/connection/winrm.py
  2696 1513832252.00187: Loading ShellModule 'powershell' from /Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/shell/powershell.py
  2696 1513832252.02167: assigned :doc
  2696 1513832252.02225: Loaded config def from plugin (connection/winrm)
  2696 1513832252.02318: Loading ActionModule 'normal' from /Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/action/normal.py
  2696 1513832252.02332: starting attempt loop
  2696 1513832252.02337: running the handler
Using module file /Users/tanner/projects/ansible.git/ansible/lib/ansible/modules/windows/win_updates.ps1
  2696 1513832252.02957: _low_level_execute_command(): starting
  2696 1513832252.02963: _low_level_execute_command(): executing: -
<PC147> ESTABLISH WINRM CONNECTION FOR USER: Administrator@LAB on PORT 5986 TO PC147.LAB
EXEC (via pipeline wrapper)
```
I can ping PC147
I can RDP to PC147
winrm is running, tested with 'winrm e winrm/config/listener'

For giggles, I disconnected the network interface on PC147. I wanted to see what happens.
```
  2696 1513836320.48767: error closing connection: HTTPSConnectionPool(host='pc147', port=5986): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10d8a31d0>: Failed to establish a new connection: [Errno 61] Connection refused',))
  2696 1513836320.49188: done running TaskExecutor() for PC147/TASK: win_updates : Window updates [a0999b17-eebb-2b5e-fb60-000000000073]
  2696 1513836320.49210: sending task result for task a0999b17-eebb-2b5e-fb60-000000000073
  2696 1513836320.49242: done sending task result for task a0999b17-eebb-2b5e-fb60-000000000073
  2696 1513836320.49409: WORKER PROCESS EXITING
  2326 1513836320.52293: worker is 1 (out of 1 available)
  2326 1513836320.52672: exiting _queue_task() for surface148/win_updates
  2326 1513836320.53173: marking PC147 as failed
  2326 1513836320.53361: marking host PC147 failed, current state: HOST STATE: block=3, task=2, rescue=0, always=0, run_state=ITERATING_TASKS, fail_state=FAILED_NONE, pending_setup=False, tasks child state? (None), rescue child state? (None), always child state? (None), did rescue? False, did start at task? False
  2326 1513836320.53396: ^ failed state is now: HOST STATE: block=3, task=2, rescue=0, always=0, run_state=ITERATING_COMPLETE, fail_state=FAILED_TASKS, pending_setup=False, tasks child state? (None), rescue child state? (None), always child state? (None), did rescue? False, did start at task? False
  2326 1513836320.53422: getting the next task for host PC147
  2326 1513836320.53434: host PC147 is done iterating, returning
The full traceback is:
Traceback (most recent call last):
  File "/Users/tanner/projects/ansible.git/ansible/lib/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/Users/tanner/projects/ansible.git/ansible/lib/ansible/executor/task_executor.py", line 523, in _execute
    result = self._handler.run(task_vars=variables)
  File "/Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/action/normal.py", line 45, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars, wrap_async=wrap_async))
  File "/Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/action/__init__.py", line 753, in _execute_module
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
  File "/Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/action/__init__.py", line 859, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/connection/winrm.py", line 457, in exec_command
    result = self._winrm_exec(cmd_parts[0], cmd_parts[1:], from_exec=True, stdin_iterator=stdin_iterator)
  File "/Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/connection/winrm.py", line 406, in _winrm_exec
    self.protocol.cleanup_command(self.shell_id, command_id)
  File "/Users/tanner/projects/ansible.git/lib/python2.7/site-packages/winrm/protocol.py", line 372, in cleanup_command
    res = self.send_message(xmltodict.unparse(req))
  File "/Users/tanner/projects/ansible.git/lib/python2.7/site-packages/winrm/protocol.py", line 234, in send_message
    resp = self.transport.send_message(message)
  File "/Users/tanner/projects/ansible.git/lib/python2.7/site-packages/winrm/transport.py", line 256, in send_message
    response = self._send_message_request(prepared_request, message)
  File "/Users/tanner/projects/ansible.git/lib/python2.7/site-packages/winrm/transport.py", line 261, in _send_message_request
    response = self.session.send(prepared_request, timeout=self.read_timeout_sec)
  File "/Users/tanner/projects/ansible.git/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/tanner/projects/ansible.git/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='pc147', port=5986): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10d6fa410>: Failed to establish a new connection: [Errno 61] Connection refused',))

fatal: [PC147.]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

**Comment by jhawkesworth** [comment]
Now that pywinrm 0.3.0 is out I wonder if its worth trying that (with the message encryption and skipping the https comms).

I fear the issue is that something that you are uninstalling causes the http stack to get restarted which will bust winrm (and I imagine could well leave workers hanging around with nothing to talk to).

I suppose you might be able to work around that by sticking in a big long pause after the chocolately call and then doing a wait_for_connection before proceeding, just to give the winm comms a chance to settle down.

**Comment by basictheprogram** [comment]
I've been using pywinrm 0.3.0 since it was available via pip.
```shell
$ pip freeze | grep pywinrm
pywinrm==0.3.0
```
For testing, I pull the latests ansible from github and do the below 
```shell
$ pip install --upgrade pip
$ pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
```
To make sure I've got the latest python package installed.

Here is the list of packages I'm uninstalleding
```yaml

chocolatey_remove_packages:
  - ccleaner
  - malwarebytes
  - uninstalltool
  - veeam-endpoint-backup-free
```
But the problem still occurs even when my test computers do not having any of the above listed packages installed.

**Comment by pipoe2h** [comment]
Hello,

I have found the same issue on an Ubuntu 16.04 machine after install pyOpenSSL to use the openssl_certificate module. When I remove the library, the error is fixed. 

```
ansible 2.4.3.0
python 2.7.12

```

**Comment by craig08** [comment]
I got the same issue and found that my deploy machine running ansible quickly ran out of memory while templating specfic file.
After carefully reviewed the template, I found that some of the variables in jinja2 template using wrong type while calculating a large number. It can be easily reproduced by following playbook and template:

#### playbook:
```
- name: Test
  hosts: all_nodes
  tasks:
    - name: template
      template:
        src: templates/aa.j2
        dest: /tmp/aa.conf
  vars:
    count: 256
    times: "256"
```

#### template:
```
{{ count * times * 1024 * 1024 }}
```

Changing the template to following resolves this issue.

```
{{ count | int * times | int * 1024 * 1024 }}
```

**Comment by dagwieers** [comment]
@craig08 Exactly, I described the same problem here: https://github.com/ansible/ansible/issues/35344

We should probably add a hint in that error-message about memory-related Jinja issues :)

**Comment by mfish82** [comment]
We as an ORG had that issue last night. We're running Ansible on a RHEL 7.5 server with 8gb of RAM, and we ran various Ansible scripts against 100+ Cisco network devices. While the memory utilization only peaked at 75% on the server, multiple users all had the same `ERROR! A worker was found in a dead state`. Some half way through the playbook, others right as they were executed.  We did have one script that was running against a large chunk of devices pull over 6GB alone. I think what @LuckySB had said last year about the memory leak is still very prevalent. We're running Ansible 2.6.3. Information is below. 

The snippet below was taken from a playbook that doesn't use loops or any math, just imports a Jinja template and commits to a router. But, we didn't even get to that point. It failed on a simple command. 

Task code that failed:
`  - name: Validate Cisco ASR9K Gold Code
    iosxr_command:
      commands:
        - show version brief
      wait_for:
        - result[0] contains "Cisco IOS XR Software, Version 5.3.4"`

```
TASK [Cisco-ASR9k-Gold-Code_Pre-Check : Validate Cisco ASR9K Gold Code] ******************************************************
fatal: [HOST1]: FAILED! => {"msg": ""}
fatal: [HOST3]: FAILED! => {"msg": "Error reading SSH protocol banner[Errno 104] Connection reset by peer"}

TASK [fail] ******************************************************************************************************************
ERROR! A worker was found in a dead state
```

`ansible --version
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules', u'/root/.ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]`


UPDATE: 

To further add to this, the server we run this on is a VM. Our vCenter only showed a max of 75% utilization at any given point during those runs, but logs taken from Linux show that at peak utilization, there was only 10MB of memory left out of 8GB available.

**Comment by eliskovets-sixt** [comment]
Hi guys, in case if somebody still struggle with the issue. 
For me `no_proxy="*"` before ansible command solved the issue. 
Here you can find more details about the issue: https://www.whatan00b.com/posts/debugging-a-segfault-from-ansible/

**Comment by coltenkrauter** [comment]
Can you please show an example @eliskovets-sixt ? I can't get this working.

**Comment by adirks-ata** [comment]
> Hi guys, in case if somebody still struggle with the issue.
> For me `no_proxy="*"` before ansible command solved the issue.
> Here you can find more details about the issue: https://www.whatan00b.com/posts/debugging-a-segfault-from-ansible/

Using Ansible 2.9.2 on Mac OS Catalina and had a similar issue that was fixed by this solution. Thanks!

**Comment by eliskovets-sixt** [comment]
> Can you please show an example @eliskovets-sixt ? I can't get this working.

Something like this works for me:
```bash
env no_proxy='*' ansible-playbook collect-facts.yml
```
You can also add `export no_proxy="*"` to your `.bashrc` or `.zshrc`, so you don't need to type it every time.

**Comment by adirks-ata** [comment]
> > Can you please show an example @eliskovets-sixt ? I can't get this working.
> 
> Something like this works for me:
> 
> ```shell
> env no_proxy='*' ansible-playbook collect-facts.yml
> ```
> 
> You can also add `export no_proxy="*"` to your `.bashrc` or `.zshrc`, so you don't need to type it every time.

Before running the ansible playbook, you should run the `export no_proxy='*'` command to create a local environmental variable. You'll be able to confirm this is in your environmental variables if you run `env | grep no_proxy` after running the above command. 

You would then run the `ansible-playbook collect-facts.yml` command as normal.
Note: Every time you open a new terminal, you will have to run `export no_proxy='*'` before running this playbook.

**Comment by jborean93** [comment]
This is a known problem on macOS and we even have it documented for the WinRM connection plugins under https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/user_guide/windows_winrm.rst#what-is-winrm

> Using the winrm or psrp connection plugins in Ansible on MacOS in the latest releases typically fail. This is a known problem that occurs deep within the Python stack and cannot be changed by Ansible. The only workaround today is to set the environment variable no_proxy=* and avoid using Kerberos auth.

There's nothing we can do from an Ansible perspective as it's a result of checking the proxy settings on the type of worker that Ansible forks.

**Comment by 7AC** [comment]
FWIW I've seen this on macOS talking to Linux hosts, using `-f` to lower the number of forks seems to mitigate.
