### ISSUE TITLE
useradd and set password using sudo

### ISSUE THREAD

**Issue by getrue** [ansible/ansible#32570]
Hi all,

We want to add newuser and set password with user 'user1' using sudo. inventory file has server ip addresses.
We need correct playbook.yml file :) Could you please share yml file content for to add new user and set password.

* Destination servers has no root login. 
* So we will login with 'user1' later user1 will create newuser and set password for newuser using sudo command.

We need playbook.yml file format and correct cli command to run playbook.

If you share content of yml file I will be very happy.

Best regards,

##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### OS / ENVIRONMENT
ansible server is REDHAT  and client servers are AIX

##### SUMMARY
Direct root login is closed. So we login with user1 and we will add "newuser", set password using sudo. user1 has sudo permission.

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by alikins** [comment]
This looks like a question about use of ansible, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can ask there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.
