### ISSUE TITLE
host pattern warning

### ISSUE THREAD

**Issue by dalmadebreceni** [ansible/ansible#32594]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

- Pattern

##### ANSIBLE VERSION

```
ansible 2.4.1.0
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

When defining multiple patterns, I get warnings. This did not happen with the previous ansible versions.
##### STEPS TO REPRODUCE

```yaml
- hosts: "security_group_a:tag_group_b:tag_group_offlinehost"
  tasks: ...
```
ansible-playbook test.yml --limit tag_group_b:!tag_setup_true

##### EXPECTED RESULTS

To match one of the listed patterns, excluding the host if it has the setup:true tag (EC2).
##### ACTUAL RESULTS

 [WARNING]: Could not match supplied host pattern, ignoring: tag_setup_true
 [WARNING]: Could not match supplied host pattern, ignoring: tag_group_offlinehost

```

```

**Comment by alikins** [comment]
cc'ing @bcoca

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, this is not a bug but a new feature added in 2.4. We now warn when a pattern is not matched, several users requested this for the following case:

`groupa:!poduction` <= the misspelled `production` would be accepted w/o notice and deliver an undesired result.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by dalmadebreceni** [comment]
Hi,

When I read the changelog before submitting this, I did not find anything related, unless it is "Improved warnings and error messages across the board". I actually found one similar ticket about templates in which someone wrote it should be reopened, and then described pretty much the same issue I did. 
I believe this is very confusing and I'm apparently not alone, my users will surely ask the question a lot of times.
Is there a way to suppress this warning? Or at least, call it "INFO"?

**Comment by jurgenhaas** [comment]
I'm confused too. When writing playbooks for multiple inventories, you never know if all of the used host patterns in the playbooks do exist in all of your inventories. Often they don't and then we have to live with a warning all the time? That's not ideal at least.

**Comment by tbouvet** [comment]
@bcoca I have the same problem. When I want to  push the hosts with an extra var, I have the same warning:
```
- hosts: "{{ group | mandatory }}"
```
```
 [WARNING]: Could not match supplied host pattern, ignoring: {{
 [WARNING]: Could not match supplied host pattern, ignoring: group
 [WARNING]: Could not match supplied host pattern, ignoring: |
 [WARNING]: Could not match supplied host pattern, ignoring: mandatory
 [WARNING]: Could not match supplied host pattern, ignoring: }}
```
I think this one is a bug.

**Comment by dhiratgithub** [comment]
[root@ansiblecontrolnode ~]# ansible --version
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

[root@ansiblecontrolnode ~]# ping -c2 ansiblemanagednode
PING ansiblemanagednode.example.com (192.168.1.101) 56(84) bytes of data.
64 bytes from ansiblemanagednode.example.com (192.168.1.101): icmp_seq=1 ttl=64 time=0.977 ms
64 bytes from ansiblemanagednode.example.com (192.168.1.101): icmp_seq=2 ttl=64 time=0.256 ms

--- ansiblemanagednode.example.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.256/0.616/0.977/0.361 ms

[root@ansiblecontrolnode ~]# ansible ansiblemanagednode -m ping
 [WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available

 [WARNING]: Could not match supplied host pattern, ignoring: ansiblemanagednode

 [WARNING]: No hosts matched, nothing to do

Please suggest what is wrong here.

Thanks,
Dhirendra

**Comment by dhiratgithub** [comment]
It's not working even when IP address is passed as argument -

[root@ansiblecontrolnode ~]# ansible 192.168.1.101 -m ping
 [WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available

 [WARNING]: Could not match supplied host pattern, ignoring: 192.168.1.101

 [WARNING]: No hosts matched, nothing to do


Thanks,
Dhirendra

**Comment by dhiratgithub** [comment]
Pls ignore my previous updates.

It's working for me now.

I did following -
1. Generated ssh key and copied to remote host
2. Added both hostname and IP in host file
[root@ansiblecontrolnode ~]# grep -v "^#"  /etc/ansible/hosts | sed '/^$/d'
ansiblemanagednode.example.com
192.168.1.101

[root@ansiblecontrolnode ~]# ansible 192.168.1.101 -m ping
192.168.1.101 | SUCCESS => {
    "changed": false,
    "failed": false,
    "ping": "pong"
}

**Comment by ssbarnea** [comment]
Currently there is no way to avoid getting this warning even for simple cases, so I ended up raising this as an individual bug at https://github.com/ansible/ansible/issues/36306
