### ISSUE TITLE
Missing docs on precedence of vars defined in roles

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#3268]
The [Understanding Variable Precedence](http://www.ansibleworks.com/docs/playbooks2.html#understanding-variable-precedence) section of the docs doesn't say anything about the precedence of variables defined in roles.

I would update it, but I don't know what the behavior is. It currently is not what I expect.  Consider this example play:

```
- hosts: server1
  vars:
    activate: true

  pre_tasks:
    debug: msg="activate={{ activate }}"

  roles:
    - myrole
```

Where `roles/myrole/vars/main.yml` contains:

```
activate: false
```

Right now, `activate` will evaluate to _false_ in the myrole tasks and in the pre_tasks(!). This really confused me, because I figured that defining the variable in a play would override the role. 

However, I have no idea if this is a bug, or Ansible is functioning as intended.

**Comment by mpdehaan** [comment]
role variables work exactly like vars_files (which apply to the entire play)

for instance, this allows having a role like "datacenter1" and things like that that pull in variables usable by other roles and tasks.

**Comment by mpdehaan** [comment]
I will tweak docs shortly.
