### ISSUE TITLE
include support for vars?

### ISSUE THREAD

**Issue by rchady** [ansible/ansible#3270]
It would be nice if vars also supported the 'include' pragma.  In the particular case I'm dealing with, I have a role that I wanted to separate the vars out in to separate files and include them via the vars/main.yml of the role, like I do for the tasks.  

Unfortunately, that does not work.  Is this something that could be added?  It would make things feel a lot more consistent.

**Comment by mpdehaan** [comment]
Actually what we want to do here instead is for it to pull in every YAML file in the vars/ directory of the role, and that is what we are going to do instead.
