### ISSUE TITLE
Unable to Ping from ansible machine remote machine

### ISSUE THREAD

**Issue by R-yogesh** [ansible/ansible#32719]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
/etc/ansible/hosts

##### ANSIBLE VERSION

```
2.3.2
```

##### ACTUAL RESULTS

```
| UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/root/.ansible/cp/8625c99978\" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\ndebug1: Connecting to xx.xx.xx.xx [xx.xx.xx.xx] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address xx.xx.xx.xx port 22: Connection timed out\r\nssh: connect to host xx.xx.xx.xx port 22: Connection timed out\r\n",
    "unreachable": true

```

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
