### ISSUE TITLE
vars_prompt does not display variable's value in prompt message

### ISSUE THREAD

**Issue by andreibaban** [ansible/ansible#32723]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vars_prompt 

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/tora5/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/python27/lib/python2.7/site-packages/ansible
  executable location = /opt/python27/bin/ansible
  python version = 2.7.14 (default, Nov  9 2017, 03:10:36) [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
```

##### CONFIGURATION
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30

##### OS / ENVIRONMENT
2.6.32-642.4.2.el6.x86_64 GNU/Linux

##### SUMMARY
Variables defined in playbook or read via extra-vars are not displayed in vars_prompt's prompt. Instead {{ var_name }} is displayed

##### STEPS TO REPRODUCE
1. define a variable: var1=x
2. create a prompt that contains var1's value : "value of var1 is {{ var1 }}"

```yaml
vars: 
    var1: "test_value"

vars_prompt:
    - name: "confirmation"
      prompt: "Value of var1 is {{ var1 }}"
```

##### EXPECTED RESULTS
prompt displays 
Value of var1 is test_value

##### ACTUAL RESULTS
prompt displays
```
Value of var1 is {{ var1 }}
```

**Comment by samdoran** [comment]
The `prompt` value is not currently templated. It _may_ be possible to do this, but could easily turn into a chicken/egg scenario.

`vars_prompt` happens very early on because the variables supplied at the prompt are most likely required in the play.

I'll see what it would take to do this, though.

**Comment by samdoran** [comment]
Please test with PR #32802 and see if this works for you.

**Comment by andreibaban** [comment]
thanks! just tested with PR #32802 and this works exactly as I wanted it.
