### ISSUE TITLE
ansible role doest not run the main playbook

### ISSUE THREAD

**Issue by weiwei100** [ansible/ansible#3279]
## site.yml
- name: setup basic packages
  hosts: all
  user: root
  
  roles:
  - test
## ./test/tasks/main.yml
- name: this is a loose task
- shell: echo 'this is a loose task'

Any help is appreciated

**Comment by mpdehaan** [comment]
Can you please share this on the mailing list?

We are probably going to need some more information and it will be easier if we discuss this there.  Thanks!
