### ISSUE TITLE
multiple actions for a task are executed in reverse order

### ISSUE THREAD

**Issue by mrproper** [ansible/ansible#328]
creating a user usually involves multiple steps 
in my example below: create user, create ssh dir, copy auth keys

however ansible executes the actions from bottom to top (this should be reversed):

  tasks:
- name: setup user ansible1
  action: copy src="../files/ssh/ansible1-authorized_keys" dest="/home/ansible1/.ssh/authorized_keys"
  action: file dest="/home/ansible1/.ssh" state=directory owner=ansible1 group=ansible1 mode=0700
  action: user name=ansible1 createhome=yes shell=/bin/bash groups="$admin_group" append=yes

**Comment by mpdehaan** [comment]
I don't understand.   

Tip:  when formatting for github, intent YAML four spaces on each line.   This tricks markdown into thinking YAML is not markdown, which it is not.

It sounds like you just pasted a playbook that was backwards and then said it was backwards.

**Comment by mrproper** [comment]
Sorry probably didnt explain that well

If i list multiple actions in the order i want them ordered in. eg: create user, then create dir, then copy file

when i actually run that playbook, it tries to execute the actions in reverse order, ie copy file, created dir then create user

to get around that, in my playbook i have reversed the order i want the actions run to get the behaviour i want
does that make sense ?

**Comment by mpdehaan** [comment]
no.   tasks in plays are arrays, executed top down.   I think you've got some weird formatting going on, please post to the mailing list if you are having trouble with github eating your formatting.

There is no such thing as "multiple actions for a task" so that may be part of the problem, hard to tell with the formatting confused like that.

**Comment by mrproper** [comment]
```
tasks:
- name: setup user ansible1
  action: user ....
  action: file ....
  action: copy ....
```

so with the above, copy gets run first instead of user during a play

**Comment by mpdehaan** [comment]
The intended syntax is:

```
tasks:
- name: name is optional, I will leave it off the next three..
  action: foo
- action: bar
- action: baz
```

ETC

I have no idea how what you pasted works at all, curious... but see examples/playbooks in a checkout for plenty of examples.   Will have to investigate what that sends over but I do NOT expect that to work.

**Comment by mpdehaan** [comment]
closing, see previous comment (edited), happy to continue discussion though this isn't a bug

**Comment by mrproper** [comment]
tasks are executed top down, actions in those tasks are not

**Comment by mrproper** [comment]
thanks for the info ill look into it further

**Comment by mrproper** [comment]
i see what the issue is, 

you can specify action multiple times for name and it only uses the last value of action, perhaps that needs some sanity checks on it?
eg:
    - name: foo
      action: foo
      action: bar
      action: baz

baz is what will be actioned. but it does not complain about the extra action params

**Comment by mpdehaan** [comment]
It is just yaml, this is what hashes slash dictionaries are supposed to do.
Glad it is just doing the last one as that makes sense!
