### ISSUE TITLE
Unexpected shell module behaviors (with and without cmd:)

### ISSUE THREAD

**Issue by wknapik** [ansible/ansible#32800]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
shell

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/foo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 20 2017, 01:25:59) [GCC 7.2.0]
```

##### CONFIGURATION
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The shell module behaves differently depending on whether `shell: some_command`, or `shell: { cmd: some_command }` is used.

I ran into this when using heredocs (thanks to @halberom for pointing me towards [this explanation](https://stackoverflow.com/questions/40230184)) and with `regex_replace` (example below).

This is unexpected, difficult to debug and undocumented. 

##### STEPS TO REPRODUCE
Works:
```yaml
- shell:
    cmd: echo {{ foo|regex_replace('/', '\\\\')|quote }}
```
Fails:
```yaml
- shell: echo {{ foo|regex_replace('/', '\\\\')|quote }}
```

##### EXPECTED RESULTS
Same behavior.

##### ACTUAL RESULTS
Different behavior.
```
ERROR! failed at splitting arguments, either an unbalanced jinja2 block or quotes: echo {{ foo|regex_replace('/', '\\\\')|quote }}
```

**Comment by giovannisciortino** [comment]
I'm observing also from my ansible 2.5 repository that the shell module hasn't any 'cmd' options in ansible-doc documentation, 'cmd' is only a return value.

```
$ ./bin/ansible-doc shell |grep -A4 cmd
[gsciorti@gsciorti ansible]$ ./bin/ansible --version
[DEPRECATED] [defaults]hostfile: The key is misleading as it can also be a list of hosts, a directory or a list of paths. It will be removed in 2.8. As alternative use one of [inventory]
ansible 2.5.0 (devel 3277e6328b) last updated 2017/09/11 20:13:12 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/gsciorti/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gsciorti/PycharmProjects/ansible/lib/ansible
  executable location = ./bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

$ ./bin/ansible-doc shell
....
RETURN VALUES:
....
cmd:
    description: The command executed by the task
    returned: always
    type: string
    sample: 'rabbitmqctl join_cluster rabbit@master'

```

**Comment by halberom** [comment]
@giovannisciortino - I raised https://github.com/ansible/ansible/issues/32729 in relation to the lack of 'cmd' docs, as a result of my discussion in irc.

**Comment by bcoca** [comment]
This is expected, `cmd` bypasses special parsing `shell` does, that is the reason it exists in the first place.
