### ISSUE TITLE
import_tasks does not process variables in parameters

### ISSUE THREAD

**Issue by timuster** [ansible/ansible#32812]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

import_tasks

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /mnt/c/Users/sumitkumar/Desktop/DGX-Upgrade/Ansible/git/ansible/ansible.cfg
  configured module search path = [u'/home/sumit/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /mnt/c/Users/sumitkumar/Desktop/DGX-Upgrade/Ansible/venv/local/lib/python2.7/site-packages/ansible
  executable location = /mnt/c/Users/sumitkumar/Desktop/DGX-Upgrade/Ansible/venv/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION

HOST_KEY_CHECKING(/foo/project/ansible.cfg) = False

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The following documentation states that I can pass a variable to an imported or included task like `- import_tasks: wordpress.yml wp_user=timmy`. However, it only works for `include_tasks` and not when I use `import_tasks`. When using `import_tasks` in the aforementioned way, I get an exception that the passed variable is undefined - as can also be seen in the error section below.

Like I said, the same code works if I swap `import_tasks` with `include_tasks`

Here's the document I'm referring to: https://docs.ansible.com/ansible/2.4/playbooks_reuse_includes.html#including-and-importing-task-files

##### STEPS TO REPRODUCE

1. Have a playbook under tasks/abc.yml that relies on a variable that's not defined in vars, like:

```yaml
- name: echo
  shell: "echo {{ my_special_var }}
```

2. In your master playbook.yml, call the first task by adding this line: 
`import_tasks: tasks/abc.yml my_special_var=Hello`

##### EXPECTED RESULTS

The task is imported and the variable from the master playbook gets passed.

##### ACTUAL RESULTS

`...exception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'my_special_var' is undefined`

```

```

**Comment by dexpl** [comment]
Same here with http://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/ansible-2.4.1.0-1.el7.ans.noarch.rpm; ansible-2.4.0.0-5.el7.noarch from CentOS 7 extras repo works as expected.

**Comment by samdoran** [comment]
I was able to duplicate this. Works in 2.4.0, broken in 2.4.1 as well as `devel`

Seems to be a problem only with the `k=v` syntax of `import_tasks`. Using multi-line YAML avoids this error, which you could use as a workaround for now.

Example playbook:
```yaml
- hosts: localhost
  connection: local
  gather_facts: no
  become: no

  tasks:
    - include_tasks: tasks.yml my_special_var=task1
    - import_tasks: tasks.yml my_special_var=task2        # This does not properly pass in vars in 2.4.1

    - include_tasks: tasks.yml
      vars:
        my_special_var: task3

    - import_tasks: tasks.yml
      vars:
        my_special_var: task4
```

`tasks.yml`
```yaml
- debug:
    var: my_special_var
```

## Fails on 2.4.1 and `devel` ##
```
> ansible --version
ansible 2.5.0 (devel 1eae3b6b59) last updated 2017/11/16 10:04:23 (GMT -400)
  config file = /Users/sdoran/Projects/Vagrant/Ansible Lab/ansible.cfg
  configured module search path = [u'/Users/sdoran/Source/ansible/library']
  ansible python module location = /Users/sdoran/Source/ansible/lib/ansible
  executable location = /Users/sdoran/Source/ansible/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]

> ansible-playbook testlocal.yml

PLAY [localhost] ***********************************************************************************************

TASK [include_tasks] *******************************************************************************************
included: /Users/sdoran/Projects/Vagrant/Ansible Lab/tasks.yml for localhost

TASK [debug] ***************************************************************************************************
ok: [localhost] => {
    "my_special_var": "task1"
}

TASK [debug] ***************************************************************************************************
ok: [localhost] => {
    "my_special_var": "VARIABLE IS NOT DEFINED!"
}

TASK [include_tasks] *******************************************************************************************
included: /Users/sdoran/Projects/Vagrant/Ansible Lab/tasks.yml for localhost

TASK [debug] ***************************************************************************************************
ok: [localhost] => {
    "my_special_var": "task3"
}

TASK [debug] ***************************************************************************************************
ok: [localhost] => {
    "my_special_var": "task4"
}

PLAY RECAP *****************************************************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0
```


## Works on 2.4.0
```
> ansible --version
ansible 2.4.0.0 (detached HEAD d14467b029) last updated 2017/11/16 11:26:49 (GMT -400)
  config file = /Users/sdoran/Projects/Vagrant/Ansible Lab/ansible.cfg
  configured module search path = [u'/Users/sdoran/Source/ansible/library']
  ansible python module location = /Users/sdoran/Source/ansible/lib/ansible
  executable location = /Users/sdoran/Source/ansible/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]

> ansible-playbook testlocal.yml

PLAY [localhost] ***********************************************************************************************

TASK [include_tasks] *******************************************************************************************
included: /Users/sdoran/Projects/Vagrant/Ansible Lab/tasks.yml for localhost

TASK [debug] ***************************************************************************************************
ok: [localhost] => {
    "my_special_var": "task1"
}

TASK [debug] ***************************************************************************************************
ok: [localhost] => {
    "my_special_var": "task2"
}

TASK [include_tasks] *******************************************************************************************
included: /Users/sdoran/Projects/Vagrant/Ansible Lab/tasks.yml for localhost

TASK [debug] ***************************************************************************************************
ok: [localhost] => {
    "my_special_var": "task3"
}

TASK [debug] ***************************************************************************************************
ok: [localhost] => {
    "my_special_var": "task4"
}

PLAY RECAP *****************************************************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0
```

**Comment by sivel** [comment]
I'm honestly surprised that the `key=value` syntax actually worked.  That syntax for includes has been deprecated for some time, and the recommended way is using the YAML `vars:` instead.

I'm not sure we should fix this, but should probably ensure we warn when people use `key=value`, to prevent people from using it.

**Comment by bcoca** [comment]
no, `vars:` is the 'supported way' + 1 for warning/error

**Comment by dexpl** [comment]
> I'm honestly surprised that the key=value syntax actually worked. That syntax for includes has been deprecated for some time, and the recommended way is using the YAML vars: instead.

[Documentation](https://docs.ansible.com/ansible/latest/playbooks_reuse_includes.html#including-and-importing-task-files) says nothing about deprecation, as I see. Bug in docs?

**Comment by samdoran** [comment]
So fixes for this:
1. Update docs
2. Warn/error if `k=v` syntax is found for import/includes

**Comment by bcoca** [comment]
its already an 'error' in `include_role`, should also be in `import_role`, `include_tasks`, `import_tasks`, `import_plays` ... the `include` might not be worth it as the keyword itself is also deprecated

**Comment by ssuchter** [comment]
A good starting place to fix the docs might be the [official page on including and importing](https://docs.ansible.com/ansible/2.4/playbooks_reuse_includes.html). It currently actively recommends using the k=v syntax:

> You can also pass variables into imports and includes:
> 
> ```
> tasks:
> - import_tasks: wordpress.yml wp_user=timmy
> - import_tasks: wordpress.yml wp_user=alice
> - import_tasks: wordpress.yml wp_user=bob
> ```

**Comment by sivel** [comment]
Inline var definition on `import_tasks` is unsupported.  Docs have been updated to reflect this (https://github.com/ansible/ansible/pull/35753)

A future change (currently in PR) will prohibit this syntax and give an error similar to:

```
Invalid options for import_tasks: wp_user
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by Walid-Shouman** [comment]
How is it possible to achieve the same result with the new syntax while redefining the same variable each time?

Example: the following will result in ```found a duplicate dict key (tasks). Using last defined value only.```
```
tasks:
- import_tasks: wordpress.yml
  vars:
  - wp_user=timmy
- import_tasks: wordpress.yml
  vars:
  - wp_user=alice
...
```

**Comment by bcoca** [comment]
```yaml
vars:
  wp_user: alice
```
