### ISSUE TITLE
Attaching tags to roles

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#3283]
The proscribed way to select a subset of tasks from the CLI is to use tags.
However, Roles (like tasks) are also an entity I often wish I could single out for execution.

I've been unable to find a way to either:
1) Limit a run to a specific role(s) via a command line switch.
2) Attach a tag to a role. 

as an aside, I've been frustrated a few times by the distinction between task includes 
and playbooks, which hurts composability IMO. In this instance, I cannot specify a 
`tags:` key in roles/foo/tasks/main.yml, I've had the same problem with vars
(and since role/vars isn't scoped to the role, it's no substitute, as discussed in #2796).

What's the proper way to do this?

P.S.
I've been using ansible heavily lately, it's been useful and friendly. Thanks.

**Comment by mpdehaan** [comment]
You can do this already.

roles:

```
- { role: foo, tags: [ 'tag1', 'tag2' ] }
```

This results in tagging all tasks in the role.

please ask questions to the mailing list and not the bug tracker, thanks!

**Comment by ghost** [comment]
That was not really a question, but a feature request. Point taken none the less.

The example you gave attaches tags to the use of a role, not the role itself. 
I have to reapply the (same) tag everytime I use the role:

site.yml

```
 - include webserver.yml
 - include elasticsearch.yml
```

webserver.yml

```
...
  - { role: monit, tags: ['monit']  }
```

elasticsearch.yml

```
...
  - { role: monit }
```

Then running

```
ansible-playbook -i inventory site.yml  -t tags monit
```

will not execute the `monit` role on the servers in the elasticsearch group, correct?

It's still useful though, and I notice it doesn't appear explicitly in the docs anywhere, 
I'll send a PR.
