### ISSUE TITLE
Not able to create VM in Google cloud with Ansible.

### ISSUE THREAD

**Issue by cyrilsebastian** [ansible/ansible#32848]
##### ISSUE TYPE

 - Documentation Report

##### ANSIBLE VERSION

```
Ansible 2.4
```

##### SUMMARY

I am trying to make VMs and load balancer as shown in [Google Cloud Demo](https://github.com/GoogleCloudPlatform/compute-video-demo-ansible).

Things I have already done
- Created and downloaded Service Account with Compute Admin and Service Role as actor.
- Installed Ansible with PyCrypto and Apache-Libcloud(with pip)
- I am using a VM in Google Cloud to build other machines with ansible.

Before running the Ansible command/playbook
```
export GCE_PROJECT=project-XXXXXX
export GCE_PEM_FILE_PATH=/home/key/XXXXXXX.json
export GCE_EMAIL=ansible@XXXXXXXXX.iam.gserviceaccount.com
export ANSIBLE_HOST_KEY_CHECKING=False
export ANSIBLE_HOSTS=ansible_hosts
```

```
git clone https://github.com/ansible/ansible
cp ansible/contrib/inventory/gce.py ~/gce/ansible/inventory/
cp ansible/contrib/inventory/gce.ini ~/gce/ansible/
```

`~/gce/ansible/inventory/gce.py --list --pretty`
till now everything is working fine, as I am able to view all the machines listed in Google
Cloud.

```
ansible -i ~/gce/ansible/inventory/gce.py all -m ping
hostname1 | UNREACHABLE! => {
    "changed": false,
    "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue",
    "unreachable": true

hostname2 | UNREACHABLE! => {
    "changed": false,
    "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue",
    "unreachable": true
```

But when I run Ansible command to ping all the machines, it gives me host unreachable error.

Apart from that, when I run the ansible playbook it returns an error.

```
ansible-playbook -i ansible_hosts --private-key=~/.ssh/google_cloud_compute gce-instances.yml
ansible-playbook -v --private-key=~/.ssh/google_cloud_compute gce-instances.yml #by default take /etc/ansible/ansible.cfg as config file
ansible-playbook -v --private-key=~/.ssh/google_cloud_compute site.yml #by default take /etc/ansible/ansible.cfg as config file

PLAY [Create Compute Engine instances] *****************************************

TASK [Bring up the instances in the first zone] ********************************
fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=0    changed=0    unreachable=1    failed=0

ansible-playbook -i ~/git/ansible/inventory/gce.py --private-key=~/.ssh/google_cloud_compute site.yml

PLAY [Create Compute Engine instances] *****************************************
skipping: no hosts matched

PLAY [Deploy Apache and custom html page] **************************************
skipping: no hosts matched

PLAY [Set up networking] *******************************************************
skipping: no hosts matched

PLAY RECAP *********************************************************************
```

Not able to connect with GCE. I tried using Ansible documentation as well but still not
able to connect.
##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by samdoran** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you find that there is a problem in the docs after engaging the community for support, please file an issue or PR with the specifics.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
