### ISSUE TITLE
Inventory plugin fails when passing correct JSON data

### ISSUE THREAD

**Issue by guilledipa** [ansible/ansible#32840]
- Bug Report
 - Documentation Report

##### COMPONENT NAME
ansible/plugins/inventory/script.py

##### ANSIBLE VERSION

Python libraries: 

```
2.5.0 0.0.devel
```

```
$ ansible --version
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION
No settings change/added/removed in ansible.cfg

##### OS / ENVIRONMENT
N/A

##### SUMMARY

Inventory plugin expects non valid JSON data.

##### STEPS TO REPRODUCE

```
$ ansible -i inventory.json --list-hosts site.test
ERROR! Attempted to read "inventory.json" as YAML: list indices must be integers, not AnsibleUnicode
Attempted to read "inventory.json" as ini file: inventory.json:2: Expected key=value host variable assignment, got: { 
```

Sample playbook:
```yaml
---
# file: site.yml
- hosts: site.test
  tasks:
  - name: Ping test
    ping:
```

Sample inventory:
```json
{
    "site": {
        "children": {
            "site.test",
        }
    },
    "site.test": {
        "hosts": [
            "test-host.google.com"
        ]
    }
}
```

##### EXPECTED RESULTS
I expect the inventory would require a valid JSON. Ansible documentation shows an example using valid json data:

```
{
    "string": {
        "hosts": [],
        "vars": {},
        "children": []
    },
}
```

As per:
http://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html#script-conventions

Ansible will fail even using the documentation example.

I expect Ansible rejects invalid JSON data and, therefore, accept valid data.

##### ACTUAL RESULTS

When using valid JSON data. Ansible returns errors:

```
ERROR! Attempted to read "inventory.json" as YAML: list indices must be integers, not AnsibleUnicode
Attempted to read "inventory.json" as ini file: inventory.json:2: Expected key=value host variable assignment, got: { 
```

However, when I supply a wrong json:

```
{
    "site": {
        "children": {
            "site.test",
        }
    },
    "site.test": {
        "hosts": {
            "test-host.google.com"
        }
    }
}
```

InventoryManager() is able to parse it:

```
$ ansible -i inventory.json --list-hosts site.test
  hosts (1):
    test-host.google.com
```

**Comment by sivel** [comment]
You are not using an inventory script, you are using a JSON file as an inventory source.  In that case, it will be handled by the YAML inventory plugin, and will need to follow the conventions of the YAML inventory plugin, which does not adhere to the same format of the JSON output from a dynamic inventory script.

See https://github.com/ansible/ansible/blob/devel/examples/hosts.yaml

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

While Ansible supports parsing JSON files as inventory, they are not the same JSON format as the one inventory scripts output (see @sivel's answer above).

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
