### ISSUE TITLE
User ID displayed in ansible.log not correct if doing an sesu - to the ID

### ISSUE THREAD

**Issue by ilana1291** [ansible/ansible#32867]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### CONFIGURATION

I added this line to ansible.cfg to enable logging: 
log_path = /Data/tools/apache-tomcat-7.0.42/webapps/openbd/sccb/data/logs/ansible/all-logs/ansible.log

##### OS / ENVIRONMENT

Linux

##### SUMMARY

We want to use the logging utilty to be able to see if any ID ran Ansible that is not our standard processing ID. This is for Audit and traceability. The issue is if someone does an "sesu - <id>" the id that is logged in ansible.log is the ID that is sesued TO not the ID that is sesued FROM. 

##### STEPS TO REPRODUCE

```
Ran the following:
1. sesu - scbmd1m
2. ansible -m ping -i /Data/ansible/configs/test.inventory all

```

##### EXPECTED RESULTS

ansible.log should look like the following with my ID (xbblql8):
2017-11-13 14:27:31,504 p=36500 u=xbblql8 |  inanjuxaws11 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
2017-11-13 14:27:31,506 p=36500 u=xbblql8 |  inanjuxaws12 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}

##### ACTUAL RESULTS

```
ansible.log shows the ID sesued to (scbmd1m):
2017-11-13 14:27:31,504 p=36500 u=scbmd1m |  inanjuxaws11 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
2017-11-13 14:27:31,506 p=36500 u=scbmd1m |  inanjuxaws12 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
```

This makes it difficult for traceability to know which ID actually ran ansible. thanks

**Comment by bcoca** [comment]
no, that seems correct, as I read it the `scbmd1m` user IS the one running Ansible.

This would be the same with sudo/su/doas/etc .. the 'current user running' is the one Ansible reports.

**Comment by ilana1291** [comment]
From an audit perspective, that doesn't have any traceability...
