### ISSUE TITLE
INI inventory regression: empty groups are no longer rejected

### ISSUE THREAD

**Issue by stromnet** [ansible/ansible#32860]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
inventory/ini.py

##### ANSIBLE VERSION
stable-2.4 (based on code review)

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
N/A

##### SUMMARY
With the inventory refactoring in 2.4, the ini module it no longer rejects empty groups.
In 1.9 empty groups was not checked. When I tested my playbooks with 2.4 I did not notice any errors. 
When testing with 2.3 (since thats what's available out-of-the-box on RHEL6), I noticed that empty groups are not supported.
Judging from code comments, it should still not be allowed:
 https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/ini.py#L180
##### STEPS TO REPRODUCE
Example hosts file:
```
[all:vars]
a=a

[test:vars]
a=b

[other]
myhost
```

##### EXPECTED RESULTS
Running ansible 2.3, targeting `myhost` , gives:
```
ERROR!  Attempted to read "hosts" as ini file: hosts:3: Section [test:vars] not valid for undefined group: test
```

##### ACTUAL RESULTS
Running the same on 2.4 does not fail. 

My guess of the problem:

 https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/ini.py#L180

When a `[...:vars]` line is seen, `invantory.add_group` is called, and entry is added to `pending_declarations` (as `state=='vars'`).
Eventually, on line 242, `pending_declarations` is iterated but as we have already called `add_group` , the  check  `if g not in self.inventory.groups` ensure that we never throw the error.

**Comment by bcoca** [comment]
confirmed, currently groups only defined as a 'vars' section don't cause errors.
