### ISSUE TITLE
Create automatic redirect HTTP->HTTPS for release.ansible.com

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#32898]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
release.ansible.com

##### ANSIBLE VERSION
N/A

##### SUMMARY
There is no reason to use HTTP if the website supports HTTPS, so just make a redirect from HTTP->HTTPS.

**Comment by resmo** [comment]
Thanks, but this is not an ansible issue, related to redhat release team.
~notabug~

**Comment by gundalow** [comment]
We don't have anywhere else (that I'm aware of) that we can publicly tack these types of issues. I know it's a slight abuse of gh/ansible/ansible/issues though I don't want to have to require people to remember it

**Comment by resmo** [comment]
I see, never mind.

**Comment by resmo** [comment]
bot_skip

**Comment by acozine** [comment]
This is fixed. When I hit http://releases.ansible.com I get bumped automatically to https:.
