### ISSUE TITLE
Missing SHA sums for stable releases in release.ansible.com

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#32897]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
release.ansible.com

##### ANSIBLE VERSION
N/A

##### SUMMARY
All releases on http://releases.ansible.com/ansible/ have SHA sums, except the stable ones (which ore the most important ones), so it's not possible to validate if the archive is genuine.

**Comment by gundalow** [comment]
We don't have anywhere else (that I'm aware of) that we can publicly tack these types of issues. I know it's a slight abuse of gh/ansible/ansible/issues though I don't want to have to require people to remember it.

**Comment by nitzmahone** [comment]
We've fixed the build job that creates the stable release tarballs to generate and upload sha256sum output alongside the tar.gz itself. We're using the same build job now for the 2.5+ pre-releases as well (they were previously manual), so you can see that it worked for 2.5.0a1/b1, and will for all releases built from it going forward.
