### ISSUE TITLE
Playbook hosts incorrectly skipped when using --limit flag

### ISSUE THREAD

**Issue by abedef** [ansible/ansible#32906]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`ansible-playbook`'s `--limit` flag

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/abed/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 20 2017, 01:25:59) [GCC 7.2.0]
```

##### CONFIGURATION

*None*

##### OS / ENVIRONMENT

- Arch Linux
- CentOS 7

##### SUMMARY

`ansible-playbook`'s `--limit` flag fails to select intended hosts in some inventories. An example inventory is provided below.

##### STEPS TO REPRODUCE

Run `$ ansible-playbook -i inventory --limit dev-* --list-hosts main.yml` using the following inventory:
```
[dev-tests]
dev-test0
dev-test1
dev-test2

[mongo-replica-set]
dev-mongo0
dev-mongo1
dev-mongo2
```

For the sake of completeness, though it is probably not relevant to the issue, this is the playbook I used to produce the inconsistent results.
```yaml
- hosts: all
  tasks:
    - debug:
        msg: a message
```

##### EXPECTED RESULTS

```
playbook: main.yml

  play #1 (all): test play	TAGS: []
    pattern: [u'all']
    hosts (6):
      dev-test2
      dev-test1
      dev-test0
      dev-mongo2
      dev-mongo1
      dev-mongo0
```

##### ACTUAL RESULTS

```
ansible-playbook 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/abed/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.14 (default, Sep 20 2017, 01:25:59) [GCC 7.2.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /home/abed/test/test_inventory inventory source with ini plugin
1 plays in main.yml

playbook: main.yml

  play #1 (all): test play	TAGS: []
    pattern: [u'all']
    hosts (3):
      dev-test2
      dev-test1
      dev-test0
```

If the command is re-run with the argument `dev-m*` instead of `dev-*` (which, in my understanding, is a subset of the original argument) supplied to the `--limit` flag, the following output is produced:
```
playbook: main.yml

  play #1 (all): test play	TAGS: []
    pattern: [u'all']
    hosts (3):
      dev-mongo0
      dev-mongo1
      dev-mongo2
```

This behaviour is inconsistent with the behaviour specified in the docstring of the pattern-matching method [here](https://github.com/ansible/ansible/blob/afc460c9437bad282651609857f73990060ebbc4/lib/ansible/inventory/manager.py#L420-L421).

The issue persists when using the forms `--limit="dev-*"` or `dev*` as well.

**Comment by bcoca** [comment]
please check PR above fixes it for you
