### ISSUE TITLE
Strings with spaces in conditionals cause errors

### ISSUE THREAD

**Issue by rsniezynski** [ansible/ansible#3295]
Running this playbook:

``` yaml
- hosts: localhost
  vars:
    test_var: "foo bar"
  tasks:
    - debug: msg=executed
      when_string: $test_var != "foo bar"
```

causes: `fatal: [localhost] => Conditional expression must evaluate to True or False: 'foo bar' != "foo 'bar"'`

Without the space in the value it works fine. Tested with 1.2 and master head.

**Comment by bennojoy** [comment]
Hey,
you could do the same with
- hosts: localhost
  vars:
    test_var: "foo bar"
  tasks:
  - debug: msg=executed
    when: test_var != "foo bar"
- Benno

**Comment by mpdehaan** [comment]
Yeah, when is the new way.  You would need to quote that expression if you are still using the legacy format, but "when" in 1.2 is much nicer.

Hope that helps!
