### ISSUE TITLE
ansible-setup divulges username on source computer's syslog

### ISSUE THREAD

**Issue by draxxris** [ansible/ansible#32972]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ansible-setup

##### ANSIBLE VERSION
```
ansible 2.3.2.0
```

##### OS / ENVIRONMENT
Linux

##### SUMMARY
Facts gathering at start of playbook run (ansible-setup) divulges username on source computer. This is a security and privacy issue. When you run ansible-playbook on a target node, the ansible-setup logs to syslog:
```
Invoked with filter=* gather subset=['all'] fact path=home/XYZ/ansible/facts.d gather timeout=0
```

There needs to be an option to NOT log this line as it clearly divulges your username (XYZ) on the target system's syslog file. Normally you can use no_log=True, but this isn't available during the fact-gathering phase.

**Comment by bcoca** [comment]
First, `no_log` is settable at play level, that would affect the fact gathering, second, you have a specific configuration that already does just this http://docs.ansible.com/ansible/devel/config.html#default-no-target-syslog

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by draxxris** [comment]
Yes I know, that would shut off all logging. But there is no way to shut off logging for _fact gathering_ only.
