### ISSUE TITLE
Running ansible-playbook with -K settings makes all tasks run as sudo user

### ISSUE THREAD

**Issue by markmandel** [ansible/ansible#3297]
For example:
`ansible-playbook -vvv -K -i hosts primary.yml`

This will run all tasks as sudo, rather than as the executing user.

**Comment by hayeah** [comment]
I've run into this issue. Furthermore, tasks for which sudo is not True would hang at "ask password:"

**Comment by mpdehaan** [comment]
Wish the pull request for this only affected --ask-sudo-user and not the sudo_user option, and then I could merge this.

See comments in other ticket.

**Comment by markmandel** [comment]
This can now be closed as #3303 was merged into devel.
