### ISSUE TITLE
 ssh: illegal option

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#32999]

**Comment by Akasurde** [comment]
@rameshkumar132 It seems that your hostgroup in inventory contains wrong values. Could you paste content of inventory ?

**Comment by ghost** [comment]
```
```

**Comment by sivel** [comment]
Your error is the errant inclusion of `---` at the top of your inventory file.  Remove that line and you should no longer receive this error.

The `---` that you likely see elsewhere is for YAML documents, and your inventory is not a YAML file and should not include this line.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
