### ISSUE TITLE
restarting service asking for sudo password and throwing error 

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#33023]

**Comment by sivel** [comment]
`become_user` identifies the user that you will become.  Can that service be restarted as `admin`? Does `admin` have full sudo access?  My guess is instead that needs to be `root` which is actually the default value.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by rameshkumar132** [comment]
It has all the privileges including restarting the service. I can able to do it via command prompt/CLI.

**Comment by bcoca** [comment]
@rameshkumar132  use -vvv and you'll see what Ansible executes, having access to restarting the service and Ansible being able to do so are not the same thing. Ansible requires 'full privileges' as a user not specific commands  http://docs.ansible.com/ansible/latest/become.html
