### ISSUE TITLE
Variable substitution not done in hosts declaration

### ISSUE THREAD

**Issue by broferek** [ansible/ansible#3308]
- hosts: S6_scanner_dc1
  tasks:
  - set_fact: datacenter={{ dc }}
- hosts: S6_scanner_{{ datacenter }}
  tasks:
  - shell: echo {{ datacenter }}

In this playbook, the variable "datacenter" is well substituted in the shell command but it is not in the hosts declaration of the 2nd play.

Ansible version used : 1.2

If I pass the variable as an extra_vars in ansible-playbook command, it works fine. 
ansible-playbook myplaybook.yml -e "datacenter=dc1"
- hosts: S6_scanner_{{ datacenter }}
  tasks:
  - shell: echo {{ datacenter }}

The best use case would be that it works between plays but also even if we include playbooks. For ex:
- hosts: S6_scanner_dc1
  tasks:
  - set_fact: datacenter={{ dc }}
- include anotherplaybook.yml => could reuse var in this playbook

**Comment by mpdehaan** [comment]
Yep, set_fact sets inventory scoped variables which cannot be used in host declarations.

A much better way to do this would be to use the "group_by" module if you wish to create a dynamic group of certain hosts matching certain facts (I'm not fully understanding your question) or also to use "-e" on the command line if you want to pass something in for use in the host specification.

Though really, it sounds like you might just want to use seperate inventory files for each datacenter, possibly in a common directory so you could still just pass -i to the directory name.

In any event, it is expected that facts, which relate to particular hosts, wouldn't be expandable here.

Stop by the mailing list if you want to explore the use case more.

**Comment by broferek** [comment]
Thanks for the answer.

I already have an inventory for each datacenter. 
Let me explain the real use case.

The real playbook is actually composed of 2 plays. The first play is the post install of a server being in any of the 2 datacenters. The second play is an update of files from a particular master server of the datacenter I'm running the playbook on.

What I want to do is automatically discover the datacenter in the first play so that I can target the good master server is the second play.

Actually, it is just to save typing extra_vars as I can indeed use "-e" as you said. 

Both our datacenters are exactly the same except the name of the servers so all my playbooks must be able to target any datacenter so that I avoid duplicate playbooks.

**Comment by mpdehaan** [comment]
Datacenter seems like it should be an inventory variable to me.

group_vars/<datacenter>

or similar.

In either case, you would still be able to use the "group_by" module to
create a dynamic group based on the fact name, so I would definitely look
into "group_by".

**Comment by shakthimaan** [comment]
I would really like this feature for automated cron tasks that get launched dynamically on newer instances. It will be simpler to specify the host using variable substitution.
