### ISSUE TITLE
Remote commands cannot return data on stderr

### ISSUE THREAD

**Issue by madduck** [ansible/ansible#3309]
At least the `ssh` connection plugin forces a TTY for the channel, even if a TTY isn't really necessary (e.g. due to sudo) (see #2650).

Since a TTY only has one output channel and SSH adheres to this convention, `stderr` is merged into `stdout` and only one data stream is returned.

If we are going to support sudo passwords and those really require a TTY, then at least the documentation should mention that all output, including `stderr` is returned as one stream, and probably the `stderr` element should be removed from the JSON return data.

However, if there could be a way to feed a password to sudo without a TTY, then that would be much preferred. However, I cannot invest more time into this, I am sorry.

**Comment by mpdehaan** [comment]
Yeah there is no bug here, modules are expected to return JSON on stdout.

**Comment by madduck** [comment]
Why does the data structure contain a `stderr` field (which is always empty)?
