### ISSUE TITLE
Role templates access fails when role tasks/ has tasks in a subdir.

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#3312]
I was trying to share comon tasks includes between roles, by using
the following dir structure:

```
util/
   include1
   include2
roles
  foo
    templates
      tmpl1
    tasks
      task1
      task2
      util -> ../../../util
  bar
    tasks
      task3
      task4
      util -> ../../../util
```

and then including `util/include1` from task1/2/3/4.

However, I found that when include1 has a `template` (and presumably
a `copy`) task, tmpl1 isn't found because foo/tasks/templates/ is searched
rather then templates/.

**Comment by mpdehaan** [comment]
Please share your playbooks that you are using with this, I don't have enough to replicate from what you have shared so far.

Thanks.

**Comment by ghost** [comment]
I understand, I'll convert it into a question: What's the proper way to share common tasks across roles?

**Comment by ghost** [comment]
Update: and here's the example repo. https://github.com/y-p/ansible_example_3312

I'll try to explain the problem again: I'd m trying to avoid having to specify a relative path, and use the 
shortcut of having files in roles/foo/templates be accessible directly by name, even when
called from an include, as long as it's executed in the context of a role.

**Comment by mpdehaan** [comment]
Sounds like the answer here is to avoid the symlinks :)

**Comment by ghost** [comment]
Not if the problem is how to avoid duplication...

**Comment by mpdehaan** [comment]
Well there are other ways to avoid duplication, but point is noted.

Still leaving this open to investigate when able.

**Comment by jimi-c** [comment]
Looking back on this, you have at least one error in your role: the "foo" template should be in a `templates` directory, not `files`. Beyond that, I believe this is an easy fix, however I believe the templates should live in the utils directory, otherwise we may introduce weird expectations about where files should be found.

**Comment by ghost** [comment]
You're right, that's an error in the example repo, the problem described
is real enough though. Glad to see it addressed.

Can I suggest you have a look at #3261? my previous pleas to reopen were ignored,
but the problem has been confirmed by at least one other user and afaik still exists.

Thanks.
