### ISSUE TITLE
apt_key does not verify downloaded key

### ISSUE THREAD

**Issue by madduck** [ansible/ansible#3320]
Instead of checking the non-unique key ID, `apt_key` should really be using the key's fingerprint to identify and verify keys, e.g.

```
apt_key: url=http://… fpr="acc87eacf876dec876f8a6c8d…"
apt_key: keyserver=subkeys.gpg.net fpr="acc87eacf876dec876f8a6c8d…"
```

This should be a trivial change since GnuPG (and `apt-key`) already lets you use the fingerprint wherever you might use the ID.

**Comment by mpdehaan** [comment]
Patches would be considered provided they are backward compatible.

**Comment by madduck** [comment]
Why do you close the issue?

**Comment by mpdehaan** [comment]
We generally don't leave feature requests open and prefer pull requests.

Github makes it relatively unmanageable when the issue queue is large, so we keep open major ideas and bug reports, but if someone just has an idea,  it's better to communicate that someone is not going to be working on it.
