### ISSUE TITLE
test-module doesn't work

### ISSUE THREAD

**Issue by madduck** [ansible/ansible#3321]
Unfortunately, `hacking/test-module` seems not to be working anymore:

```
% ./hacking/test-module -m library/commands/shell -a 'echo hi'
* module boilerplate substitution not requested in module, line numbers will be unaltered
***********************************
RAW OUTPUT

library/commands/shell: 5: library/commands/shell: DOCUMENTATION: not found
library/commands/shell: 47: library/commands/shell: EXAMPLES: not found

***********************************
PARSED OUTPUT
{
    "failed": true, 
    "msg": "", 
    "parsed": false
}
```

I get this also with `template` and `command`. I have not tried anything else.

**Comment by mpdehaan** [comment]
That's because there's technically no shell module.

Use "command" and append the value of -a with " #USE_SHELL"

**Comment by mpdehaan** [comment]
Similarly, the template module has a server side component.

The test-module script is only for pure remote modules.
