### ISSUE TITLE
Ability to hide tasks from output

### ISSUE THREAD

**Issue by madduck** [ansible/ansible#3324]
When a task registers output of a command in variable and another task uses that variable, it might be desirable to just hide the first task from the output. Maybe a new flag like "report" could be added, e.g.:

```

---
- name: register a variable
  shell: find …
  register: output
  report: no

- name: use variable
  …
```

**Comment by mpdehaan** [comment]
This is unlikely to be implemented.   If running in non-verbose mode there will be a minimum of output for the task.   You could also write a custom facts module to minimize the number of tasks that might be gathering data.

**Comment by wojtekhaj** [comment]
i could use a function like that as some of the tasks that i run are just unnecessary to display

**Comment by stucki** [comment]
I'd like you to reconsider this change.

For example, collecting data with "grep" is not a task and will never change. While using `changed_when: false` for it, it also makes sense to hide this task from any output.

**Comment by eproxus** [comment]
I have another use case for this:

We currently have a `users` role that will output for each item, the user's username and SSH key among other things. This would be nice to hide so it is not stored/visible in some log/cache somewhere.

**Comment by kiranos** [comment]
I would like this feature aswell, for me it would be enough in some cases that ansible reported if all tasks completed ok or if it exited on a specific task before it could complete.

**Comment by rameshraithatha** [comment]
+1

**Comment by observerss** [comment]
I am going to write a debug only playbook, but are unable to hide tasks that are no need to display
I'll +1 on this.

**Comment by danillos** [comment]
+1

**Comment by m-emelchenkov** [comment]
I use conditional include statements and would like to get this feature too.

**Comment by tsemerad** [comment]
I agree with @mikhailguru. I find displaying the skipped tasks unnecessary sometimes.

**Comment by felixfischer** [comment]
+1

**Comment by vigodeltoro** [comment]
+1
i also use conditonal includes

**Comment by eugef** [comment]
+1

**Comment by tahajahangir** [comment]
+1
It nice to have a directive like `report_when`

**Comment by toddwells** [comment]
Until this gets into ansible, skipping lines can be removed using a relatively simple awk script.    Then called like this.
ansible-playbook ........ | noskip

#cat noskip

```
#!/usr/bin/awk -f
# Remove Skipped lines from Ansible output, and if a full TASK section has only skipped lines do not print TASK line
# Written by Todd Wells  todd@wells.ws
#
# If TASK line, put line in buffer and do not print
# Remove all skipping lines ( both with and without color coding)
# if TASK buffer empty, print line
# if TASK buffer is full and current line is blank, TASK was followed only by skipped lines.  Do not print TASK and clear buffer
# TASK buffer full and current line not blank.  TASK followed by a non-skipped line ( OK, Changed).  Print TASK, current line and clear buffer
#
# color coding can be preserved by using the environment variable option
# export ANSIBLE_FORCE_COLOR=true
# to preserve color in jenkins, https://major.io/2014/06/25/get-colorful-ansible-output-in-jenkins/

/^TASK/ { TL=$0; next }
/^skipping/ { next }
/^^[\[0;36mskipping/ { next }
{
  if ( TL== "" ){
       print }
  else if ( $0 == ""  ) {
       TL=""; next }
  else {
       print TL; print ; TL="" }
}
```

**Comment by mauricios** [comment]
+1

**Comment by anthcourtney** [comment]
+1

**Comment by zatekusen** [comment]
+1

**Comment by claytono** [comment]
+1

**Comment by armenr** [comment]
We ended up running ansible-playbook name_of_playbook.yml | grep 'yermom'

Said by my colleague when we figured out we can't suppress tasks from output:
"That fact that a scripting tool needs to be piped to grep indicates that it's lacking something."

**Comment by s-boyle** [comment]
+1

I have a use case similar to stucki.  Workarounds, like those proposed by toddwells, indicate that Ansible is lacking a way to get the desired result.

**Comment by stucki** [comment]
Should we create a new issue about it or is anyone able to reopen this please?

**Comment by bwhaley** [comment]
+1

**Comment by michaelkrieger** [comment]
Agreed-  Example use case is here for me.  A main.yml creates my standard users, deploys the motd and other universal items.  Then I want to fork out to each system.  I don't care that it skipped my redhat package install on a debian system, or that it skipped installing outdated software on another.

I just want to suppress the skipped warning for any hosts that are excluded by this.  This could be an extension to when.  when is used for a condition (that should show skipped) and 'only_when' or 'if' or 'matching' to match conditions to even consider the task in the first place.
- include: debian.jessie.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie/sid'
- include: debian.wheezy.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'wheezy'

PS: sadly, include debian.{{ansible_distribution_release}}.yml doesn't work either, though I figured it wouldn't.

**Comment by npearson72** [comment]
+1

**Comment by stucki** [comment]
I find it annoying that this is closed without further discussion. If you think it's not an issue, please let us know how the examples above can be achieved.

**Comment by cemo** [comment]
+1

**Comment by vollendorf** [comment]
+1

**Comment by kiiadi** [comment]
+1

**Comment by Gerst20051** [comment]
:+1:

**Comment by bcoca** [comment]
We don't monitor closed threads, feel free to bring issues up on ansible-devel. In any case there is already something close to what is requested, DISPLAY_SKIPPED_HOSTS=0  will only show the task name header, but will not enumerate each skipped host.
