### ISSUE TITLE
$ansible_processor_cores returns "NA" when run under QEMU/KVM 1.5.0

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#3325]
```
vagrant@vagrant-ubuntu-raring-64:/$ cat /proc/cpuinfo 
processor   : 0
vendor_id   : GenuineIntel
cpu family  : 6
model       : 2
model name  : QEMU Virtual CPU version 1.5.0
stepping    : 3
microcode   : 0x1
cpu MHz     : 2906.998
cache size  : 4096 KB
fpu     : yes
fpu_exception   : yes
cpuid level : 4
wp      : yes
flags       : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl pni cx16 hypervisor lahf_lm
bogomips    : 5813.99
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

```

Shows a single processor as configured.

**Comment by mpdehaan** [comment]
what remote OS and ansible version?

**Comment by ghost** [comment]
stock 1.2 and ubuntu raring 13.04 cloud image.

**Comment by mpdehaan** [comment]
thanks!

**Comment by ghost** [comment]
It also happens for me on a Centos 6.4 in a Virtualbox image.
Should I open an another issue or it is related (probably I guess) ?

cat /proc/cpuinfo 
processor   : 0
vendor_id   : GenuineIntel
cpu family  : 6
model       : 42
model name  : Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
stepping    : 7
cpu MHz     : 3379.939
cache size  : 6144 KB
fdiv_bug    : no
hlt_bug     : no
f00f_bug    : no
coma_bug    : no
fpu     : yes
fpu_exception   : yes
cpuid level : 5
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc up pni monitor ssse3 lahf_lm
bogomips    : 6759.87
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

**Comment by jimi-c** [comment]
@QuelleVille no, another issue is not required, since this one is still open.

**Comment by jimi-c** [comment]
This appears to be happening because the OS is not being detected correctly, as there is no code path for the Linux hardware detection that results in "NA" being set for the number of cores (but there are in the Solaris/*BSD and a couple of others). So this would seem to be an issue with the load_platform_subclass() in module_common.py.

**Comment by mscherer** [comment]
I think that we need the output of "ansible all -c local -m setup" to diagnose it properly.

**Comment by jctanner** [comment]
@y-p and @QuelleVille please paste in your "ansible all -c local -m setup" outputs per mscherer's suggestion. I am not able to reproduce this on centos 6.4 or ubuntu 13.04 running on qemu 1.2.x

**Comment by ghost** [comment]
Thanks. I'm using other tools now and so I can't provide more info.

Please close if you believe this has been resolved.
