### ISSUE TITLE
Copy Module issue

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#33283]

**Comment by sivel** [comment]
You have instructed Ansible to copy the contents from the previous task to a directory called `.output` On the host `lab2-rtr2`

The error indicates that the directory does not exist on `lab2-rtr2`

You likely wanted to use `delegate_to: localhost`

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
