### ISSUE TITLE
When trying to add a variable as condition Ansible throws an error.

### ISSUE THREAD

**Issue by mlopeza** [ansible/ansible#3331]
ansible 1.3

I defined some variables to make it available to all my playbooks in an easy way.

So my variables are currently formatted in this way.

is_1004: "ansible_distribution_version == '10.04"
is_1010: "ansible_distribution_version == '10.10"
is_1104: "ansible_distribution_version == '11.04"
is_1110: "ansible_distribution_version == '11.10"
is_1204: "ansible_distribution_version == '12.04"
is_1210: "ansible_distribution_version == '12.10"
is_1304: "ansible_distribution_version == '13.04"

is_two_selected: "is_1004 or is_1010"

And when I try to add them in the when condition:
 roles:
    - { role: Ubuntu_List, when: is_two_selected}

It passes the test even when it shouldnt.
(The host was an ubuntu 13.04 VM)

TASK: [Print all Variables available] ****************************************\* 
changed: [127.0.0.1] => {"changed": true, "cmd": "echo ansible_distribution == 'Ubuntu' ", "delta": "0:00:00.001433", "end": "2013-06-24 10:34:55.899721", "rc": 0, "start": "2013-06-24 10:34:55.898288", "stderr": "", "stdout": "ansible_distribution == Ubuntu"}
# 

I also tried the old way.
# Ubuntu Versions

is_1004: "'$ansible_distribution_version' == '10.04'"
is_1010: "'$ansible_distribution_version' == '10.10'"
is_1104: "'$ansible_distribution_version' == '11.04'"
is_1110: "'$ansible_distribution_version' == '11.10'"
is_1204: "'$ansible_distribution_version' == '12.04'"
is_1210: "'$ansible_distribution_version' == '12.10'"
is_1304: "'$ansible_distribution_version' == '13.04'"

is_two_selected: "$is_1004 or $is_1010"

And my roles selection file:

  roles:
    - { role: Ubuntu_List, when: $is_two_selected}

But it keeps giving me this error:

TASK: [Adding source.] *******************************************************\* 
fatal: [192.168.1.112] => Conditional expression must evaluate to True or False: {% if '6.2' == '10.04' or '6.2' == '10.10' %} True {% else %} False {% endif %}

**Comment by mpdehaan** [comment]
This is related to #3460, so leaving just that one ticket open

**Comment by mpdehaan** [comment]
This was fixed this morning on the development branch.

You can also say:

when: variable_name

**Comment by mlopeza** [comment]
Thanks

**Comment by rr-ricardo-aravena** [comment]
Is this fixed ? I'm seeing with the only_if condition.
