### ISSUE TITLE
ansible-playbook: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n", "unreachable": true}

### ISSUE THREAD

**Issue by garyyang6** [ansible/ansible#33321]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible --version
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/luop/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### OS / ENVIRONMENT

CentOS Linux release 7.4.1708 (Core) 
##### SUMMARY

I login as root at docker01.works.com. As root, I am able to ssh to docker02.works.com without password. Also, as root, at docker02.works.com, I am able to ssh to docker01.works.com without password. But, I got Permission denied when I run ansible-playbook as root.

ansible-playbook  ~/openshift-ansible/playbooks/byo/config.yml

```
TASK [Gathering Facts] *******************************************************************************************************
fatal: [docker01.works.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n", "unreachable": true}
```

Content of /etc/ansible/hosts:
```
cat /etc/ansible/hosts
# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=worksid

# If ansible_ssh_user is not root, ansible_become must be set to true
ansible_become=true

openshift_deployment_type=origin

# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

# host group for masters
[masters]
docker01.works.com

# host group for etcd
[etcd]
docker02.works.com

# host group for nodes, includes region info
[nodes]
docker01.works.com
```

##### STEPS TO REPRODUCE

Per the document, https://docs.openshift.org/latest/install_config/install/advanced_install.html, 
Running the Advanced Installation

```yaml
cat ~/openshift-ansible/playbooks/byo/config.yml
---
- include: openshift-cluster/config.yml
cat openshift-cluster/config.yml
---
- include: ../../init/main.yml

- include: ../../common/openshift-cluster/config.yml


```

##### EXPECTED RESULTS

Openshift Origin should be installed
##### ACTUAL RESULTS

Installation failed.

```
ansible-playbook  ~/openshift-ansible/playbooks/byo/config.yml
[DEPRECATION WARNING]: 'include' for playbook includes. You should use 'import_playbook' instead. This feature will be removed in version 2.8. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for 
dynamic inclusions. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False 
in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain 
more about this rationale.. This feature will be removed in a future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: The use of 'static' has been deprecated. Use 'import_tasks' for static inclusion, or 'include_tasks' for dynamic 
inclusion. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.

PLAY [Initialization Checkpoint Start] ***********************************************************************************************************

TASK [Set install initialization 'In Progress'] **************************************************************************************************
ok: [docker02.works.com]

PLAY [Populate config host groups] ***************************************************************************************************************

TASK [Load group name mapping variables] *********************************************************************************************************
ok: [localhost]

TASK [Evaluate groups - g_etcd_hosts or g_new_etcd_hosts required] *******************************************************************************
skipping: [localhost]

TASK [Evaluate groups - g_master_hosts or g_new_master_hosts required] ***************************************************************************
skipping: [localhost]

TASK [Evaluate groups - g_node_hosts or g_new_node_hosts required] *******************************************************************************
skipping: [localhost]

TASK [Evaluate groups - g_lb_hosts required] *****************************************************************************************************
skipping: [localhost]

TASK [Evaluate groups - g_nfs_hosts required] ****************************************************************************************************
skipping: [localhost]

TASK [Evaluate groups - g_nfs_hosts is single host] **********************************************************************************************
skipping: [localhost]

TASK [Evaluate groups - g_glusterfs_hosts required] **********************************************************************************************
skipping: [localhost]

TASK [Evaluate groups - Fail if no etcd hosts group is defined] **********************************************************************************
skipping: [localhost]

TASK [Evaluate oo_all_hosts] *********************************************************************************************************************
ok: [localhost] => (item=docker01.works.com)
ok: [localhost] => (item=docker02.works.com)

TASK [Evaluate oo_masters] ***********************************************************************************************************************
ok: [localhost] => (item=docker01.works.com)

TASK [Evaluate oo_first_master] ******************************************************************************************************************
ok: [localhost]

TASK [Evaluate oo_new_etcd_to_config] ************************************************************************************************************

TASK [Evaluate oo_masters_to_config] *************************************************************************************************************
ok: [localhost] => (item=docker01.works.com)

TASK [Evaluate oo_etcd_to_config] ****************************************************************************************************************
ok: [localhost] => (item=docker02.works.com)

TASK [Evaluate oo_first_etcd] ********************************************************************************************************************
ok: [localhost]

TASK [Evaluate oo_etcd_hosts_to_upgrade] *********************************************************************************************************
ok: [localhost] => (item=docker02.works.com)

TASK [Evaluate oo_etcd_hosts_to_backup] **********************************************************************************************************
ok: [localhost] => (item=docker02.works.com)

TASK [Evaluate oo_nodes_to_config] ***************************************************************************************************************
ok: [localhost] => (item=docker01.works.com)

TASK [Add master to oo_nodes_to_config] **********************************************************************************************************
skipping: [localhost] => (item=docker01.works.com) 

TASK [Evaluate oo_lb_to_config] ******************************************************************************************************************

TASK [Evaluate oo_nfs_to_config] *****************************************************************************************************************

TASK [Evaluate oo_glusterfs_to_config] ***********************************************************************************************************

TASK [Evaluate oo_etcd_to_migrate] ***************************************************************************************************************
ok: [localhost] => (item=docker02.works.com)
 [WARNING]: Could not match supplied host pattern, ignoring: oo_lb_to_config

 [WARNING]: Could not match supplied host pattern, ignoring: oo_nfs_to_config


PLAY [Ensure that all non-node hosts are accessible] *********************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************
fatal: [docker01.works.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n", "unreachable": true}
ok: [docker02.works.com]

NO MORE HOSTS LEFT *******************************************************************************************************************************
        to retry, use: --limit @/root/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0   
docker01.works.com : ok=0    changed=0    unreachable=1    failed=0   
docker02.works.com : ok=2    changed=0    unreachable=0    failed=0   


INSTALLER STATUS *********************************************************************************************************************************
Initialization             : In Progress (0:00:07)
```

**Comment by garyyang6** [comment]
I noticed "<docker02.works.com> ESTABLISH SSH CONNECTION FOR USER: none". I made changes in /etc/ansible/hosts and rerun the script. I still got Permission denied.

ansible-playbook  -vvv ~/openshift-ansible/playbooks/byo/config.yml

TASK [Gathering Facts] ************************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<docker01.works.com> ESTABLISH SSH CONNECTION FOR USER: root
<docker01.works.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/f94ef48be1 docker01.works.com '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<docker02.works.com> ESTABLISH SSH CONNECTION FOR USER: root
<docker02.works.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/0365af963e docker02.works.com '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<docker01.works.com> (255, '', 'Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n')
fatal: [docker01.works.com]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n", 
    "unreachable": true
}
<docker02.works.com> (0, '/root\n', '')
<docker02.works.com> ESTABLISH SSH CONNECTION FOR USER: root

**Comment by jborean93** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by dhiratgithub** [comment]
[student@ansiblecontrolnode dep-manage]$ ansible www.example.com -m command -a 'id' -u devops  -vvv
ansible 2.4.1.0
  config file = /home/student/dep-manage/ansible.cfg
  configured module search path = [u'/home/student/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Using /home/student/dep-manage/ansible.cfg as config file
Parsed /home/student/dep-manage/inventory inventory source with ini plugin
META: ran handlers
Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
<www.example.com> ESTABLISH SSH CONNECTION FOR USER: devops
<www.example.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=devops -o ConnectTimeout=10 -o ControlPath=/home/student/.ansible/cp/ee12a52b38 www.example.com '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<www.example.com> (255, '', 'Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n')
www.example.com | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n",
    "unreachable": true
}

**Comment by dhiratgithub** [comment]
I tried copying ssh key -

[student@ansiblecontrolnode dep-manage]$ ssh-copy-id devops@ansiblemanagednode

But same issue is reported.

[student@ansiblecontrolnode dep-manage]$ ansible www.example.com -m command -a 'id' -u devops  -vvv                                                                                              ansible 2.4.1.0
  config file = /home/student/dep-manage/ansible.cfg
  configured module search path = [u'/home/student/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Using /home/student/dep-manage/ansible.cfg as config file
Parsed /home/student/dep-manage/inventory inventory source with ini plugin
META: ran handlers
Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
<www.example.com> ESTABLISH SSH CONNECTION FOR USER: devops
<www.example.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=devops -o ConnectTimeout=10 -o ControlPath=/home/student/.ansible/cp/ee12a52b38 www.example.com '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<www.example.com> (255, '', 'Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n')
www.example.com | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n",
    "unreachable": true
}

**Comment by ghost** [comment]
I have exactly the same problem - installing with ansible from cygwin. In former days i remember have read about an issue with the statement ControlMaster=auto. The value should be changed to no instead of auto. I can not test it since my cygwin ansble ignores created ansible.cfg and the changed statement in it.
Could you try this in your files?

**Comment by dhiratgithub** [comment]
Thanks Aleksey Shumilin!

It was my mistake -

I copied ssh key on ansiblemanagednode host
[student@ansiblecontrolnode dep-manage]$ ssh-copy-id devops@ansiblemanagednode

but was trying to run ansible ad-hoc on www.example.com (different host) -
[student@ansiblecontrolnode dep-manage]$ ansible www.example.com -m command -a 'id' -u devops -vvv 

I realized this later. Just started learning Ansible. 

Thanks for your update!

**Comment by ghost** [comment]
Great, i solved my problem also, just completed some statements in the cfg file, its ignored otherwise.

**Comment by RakeshNagarajan** [comment]
You might have configured the ssh wrongly...

reconfigure the SSH

CAUTION: RECONFIGURING THE SSH LEADS TO THE REMOVAL OF CURRENT SSH CONFIGURATION

**Comment by enablex3** [comment]
Something I tried (and it worked) when I had this same issue:

"ansible [dev] -m command -a "whatever command" -k" The "-k" prompts you for the ssh password to the target server. This worked for me. Also, nothing complex in the hosts file just added:

"[dev]
target_server_ip"

**Comment by sher-ocs-79** [comment]
Solved by removing ansible_become=true in the /etc/ansible/hosts file.
