### ISSUE TITLE
The `when` statement is broken in roles

### ISSUE THREAD

**Issue by dpedu** [ansible/ansible#33352]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`when` statement of playbooks

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /home/ubuntu/minib/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/minib/ansible/library']
  ansible python module location = /home/ubuntu/minib/.pyenv/local/lib/python2.7/site-packages/ansible
  executable location = /home/ubuntu/minib/.pyenv/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(/home/ubuntu/minib/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/ubuntu/minib/ansible/ansible.cfg) = -F ./ansible/ssh.config
DEFAULT_FORKS(/home/ubuntu/minib/ansible/ansible.cfg) = 500
DEFAULT_GATHERING(/home/ubuntu/minib/ansible/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/home/ubuntu/minib/ansible/ansible.cfg) = [u'/home/ubuntu/minib/ansible/inventory.cfg']
DEFAULT_LOG_PATH(/home/ubuntu/minib/ansible/ansible.cfg) = /home/ubuntu/minib/ansible/ansible.log
DEFAULT_MODULE_LANG(/home/ubuntu/minib/ansible/ansible.cfg) = en_US.UTF-8
DEFAULT_MODULE_PATH(/home/ubuntu/minib/ansible/ansible.cfg) = [u'/home/ubuntu/minib/ansible/library']
DEFAULT_PRIVATE_KEY_FILE(/home/ubuntu/minib/ansible/ansible.cfg) = /home/ubuntu/minib/ansible/ssh.key
DEFAULT_REMOTE_TMP(/home/ubuntu/minib/ansible/ansible.cfg) = /tmp/ansible
DEFAULT_REMOTE_USER(/home/ubuntu/minib/ansible/ansible.cfg) = ubuntu
DEFAULT_ROLES_PATH(/home/ubuntu/minib/ansible/ansible.cfg) = [u'/home/ubuntu/minib/ansible/roles']
HOST_KEY_CHECKING(/home/ubuntu/minib/ansible/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/home/ubuntu/minib/ansible/ansible.cfg) = /home/ubuntu/minib/ansible/tmp
```

##### OS / ENVIRONMENT
Ubuntu 14.04.5 64 bit

##### SUMMARY

Then `when` condition is skipped when used in a second-level include in a role.

##### STEPS TO REPRODUCE

I have a main.yml playbook in a role's task dir that looks like this, fairly identical to the example shown [here](http://docs.ansible.com/ansible/latest/playbooks_reuse_roles.html#role-directory-structure):

```
- name: Copy something to all machines
  copy:
   src: files/whatever.txt
   dest: /tmp/whatever.txt

- import_tasks: online-repo.yml
  when: not install_offline|bool

- import_tasks: offline-repo.yml
  when: install_offline|bool
```

Here, the `when` statement works fine. Only one of the two playbooks is included. One of the included playbooks looks like this:

```
- name: Do something
  become: True
  shell: rm -rf /something

- debug:
    var: ansible_host

- debug:
    msg: '{{ ansible_host in ["localhost", "127.0.0.1"] }}'

- name: Do local things
  become: True
  local_action: shell echo hello
  when: ansible_host in ["localhost", "127.0.0.1"]
  run_once: True

- name: Do something else
  synchronize:
    <args>
  when: ansible_host not in ["localhost", "127.0.0.1"]
```

##### EXPECTED RESULTS

In the logic above, since `ansible_host` is either in the list or not, I expect one step to be skipped and one to be executed.

##### ACTUAL RESULTS

BOTH steps are executed, even though the boolean condition clearly evaluates to false.

```
TASK [myrole : Copy something to all machines] ******************
changed: [10.0.1.223]

TASK [myrole : debug] ************
ok: [10.0.1.223] => {
    "ansible_host": "10.0.1.223"
}

TASK [myrole : debug] *********
ok: [10.0.1.223] => {
    "msg": false
}

TASK [myrole : Do local things **********
changed: [10.0.1.223 -> localhost]

TASK [myrole : Do something else] ********
changed: [10.0.1.223]
```

**Comment by sivel** [comment]
On first glance, this may be "expected" in these cases.

1. When running `local_action` that delegates the task to localhost,  so the `when` statement is passing
2. `synchronize` does some things on the backend that cause the task to be delegated to localhost.

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by dpedu** [comment]
@bcoca why is this closed? The behavior above is both extremely odd, and undocumented. Definitely a bug.

**Comment by bcoca** [comment]
@dpedu I'm not sure if i can clarify over what @sivel already did. 

The way it is working is exactly as it should, `local_action` is documented as an alias to `delegate_to: localhost` and in delegation docs it does tell you about how connection variables for the delegated host will be used, `ansible_host` is one of those vars.
