### ISSUE TITLE
lineinfile gets permission denied writing temporary file into immutable dir

### ISSUE THREAD

**Issue by ngarfink** [ansible/ansible#3335]
The lineinfile module should check if the /tmp dir and destination dir are on the same partition and not do an intermediate copy in that case.  Our existing code broke when lineinfile tried to create a temporary file in our immutable (chattr +i) .ssh dir.

This broke existing 1.1 code for us.

**Comment by bcoca** [comment]
I can patch to do this, it will still break if you have it set to immutable
and set tmp dir to diff partition.

**Comment by ngarfink** [comment]
Thanks, yes I know.   I added .ssh to the chattr.  I filed the bug because
it busts 1.1 code.   However I also changed our code.  Don't need a patch,
tnx.

**Comment by mpdehaan** [comment]
Closing per above.
