### ISSUE TITLE
sudo fails with fingerprint reader

### ISSUE THREAD

**Issue by groks** [ansible/ansible#3345]
Trying ansible for the first time and running a simple playbook on the local machine fails. Boiled it down to this:

```
[sd@yo ~]$ ansible all -c local -m command -a "/bin/whoami"
yo | success | rc=0 >>
sd

[sd@yo ~]$ ansible all --sudo -c local -m command -a "/bin/whoami"
yo | FAILED => failed to parse: {"changed": true, "end": "2013-06-25 21:04:39.265573", "stdout": "root", "cmd": ["/bin/whoami"], "start": "2013-06-25 21:04:39.260617", "delta": "0:00:00.004956", "stderr": "", "rc": 0}
Swipe your right index finger on UPEK Eikon 2

[sd@yo ~]$ ansible all --sudo -K -c local -m command -a "/bin/whoami"
sudo password: 
yo | FAILED => sudo output closed while waiting for password prompt:
{"changed": true, "end": "2013-06-25 21:06:02.444736", "stdout": "root", "cmd": ["/bin/whoami"], "start": "2013-06-25 21:06:02.439969", "delta": "0:00:00.004767", "stderr": "", "rc": 0}
Swipe your right index finger on UPEK Eikon 2
```

When I try with --sudo the command pauses for me to swipe my finger (no message on screen, little green light lights up), I swipe, and it fails. The swipe message appears after the error message.

(My credentials should already be cached - running sudo whoami runs immediately)

If I try with --sudo and the -K switch, it asks for password but still pauses for me to swipe my finger. It then fails anyway.

I created a brand new user, added them to wheel, and logged in on a virtual terminal. Fingerprint swiping is not set up.

```
[joe@yo ~]$ ansible all -v -i hosts -c local -m command -a "/bin/whoami"
yo | success | rc=0 >>
joe

[joe@yo ~]$ ansible all --sudo -K -v -i hosts -c local -m command -a "/bin/whoami"
sudo password: 
yo | success | rc=0 >>
root

[joe@yo ~]$ ansible all --sudo -v -i hosts -c local -m command -a "/bin/whoami"
yo | FAILED >> {
    "failed": true, 
    "msg": "[sudo via ansible, key=zajiomnrbcgkyyawejazfmfuglsbwphf] password: \n", 
    "parsed": false
}
```

Note that while --sudo -K worked, --sudo by itself does not. However, it at least seems to parse the error message correctly, unlike the example with fingerprint swiping.

ansible-1.1-1.fc18.noarch

**Comment by mpdehaan** [comment]
Can you disable your finger printey thing somehow?

I have no experience with your device and you didn't specify what it was.

Also sounds like you running against "all" might include your local box?

**Comment by groks** [comment]
Sorry, forgot to mention: this is a Thinkpad X220 with built-in fingerprint reader, and the only machine in the hosts file is 'localhost'. I'm just trying to manage the local machine (to start with). I'd rather not disable the fingerprint reader if possible - it's very convenient.

**Comment by groks** [comment]
I don't know if this following is also sudo (or at least login) related, but it seems I can't even skip local connections and use either ssh method, even though ssh works fine:

```
[sd@yo ~]$ ssh localhost
Last login: Tue Jun 25 22:18:50 2013 from localhost.localdomain

[sd@yo ~]$ exit
logout
Connection to localhost closed.

[sd@yo ~]$ ansible localhost -v -c ssh -m command -a "/bin/whoami"
localhost | FAILED => failed to transfer file to /home/sd/.ansible/tmp/ansible-1372195578.41-259797944447402/command:

Received message too long 458961005


[sd@yo 2 ~]$ ansible localhost -v -c paramiko -m command -a "/bin/whoami"
localhost | FAILED => failed to open a SFTP connection (Garbage packet received
```

This is just a laptop with a fairly vanilla install of Fedora 18.

**Comment by groks** [comment]
Forget the previous message. SCP wasn't working because of a customised PS1. But the original incompatibility between ansible and any unusual pam auth method still stands.

**Comment by bcoca** [comment]
Ansible takes over the interactivity of ssh so you can 'batch' the plays,
it stands to reason that uncommon extra inputs for ssh or sudo will trouble
it.

You can disable fingerprint for ssh access only. It doesn't make much sense
in most cases, you don't want to run up to a managed cluster and swipe your
finger each time you change configs.

Brian Coca

**Comment by mpdehaan** [comment]
Yeah I believe we are not going to be able to fix this one cleanly, and Ansible is really designed for batch management.
