### ISSUE TITLE
Documentation for test module (README) should reference different module path

### ISSUE THREAD

**Issue by ninetythirty** [ansible/ansible#3348]
In [ansible/hacking/README.md](https://github.com/ansible/ansible/blob/devel/hacking/README.md), the following example doesn't work:

```
$ ./hacking/test-module -m library/shell -a "echo hi"
```

The example should be replaced with a working command:

```
$ ./hacking/test-module -m library/commands/command -a "echo hi"
```

**Comment by mpdehaan** [comment]
Thanks for the heads up!

**Comment by mpdehaan** [comment]
fix pushed to devel
