### ISSUE TITLE
Wrong evaluation context for `hostvars`

### ISSUE THREAD

**Issue by gw0** [ansible/ansible#3351]
As described `hostvars[]` should enable one to access the variables from another host (exactly same as if the play would be run on that host). But this is not the case for non-trivial variables, eg:

```
#hosts
first
second
```

```
group_vars/all

---
foo: "{{ inventory_hostname }}"
```

```

---
- hosts: first
  tasks:
    - debug: msg="{{ hostvars['second']['foo'] }}"
```

Expected result is the inventory hostname `second`, but because the Jinja2 template in the variable gets evaluated in `first` context it returns that instead.

Happend with latest development branch of Ansible 1.3.

**Comment by mpdehaan** [comment]
inventory_hostname is a variable that is set in Runner code based on the node that is currently going through the loop.

You should use hostvars['second']['ansible_hostname'] and get data from a fact.

**Comment by gw0** [comment]
So this unexpected behavior should than be mentioned in the documentation that should state that _only_ facts are accessible. Not inventory variables or internal things set in Runner code.

Actually using inventory_hostname was just a simplified example, my original problem was accessing a host variable set in the hosts file in that way.

**Comment by mpdehaan** [comment]
Inventory variables are accessible.

**Comment by gw0** [comment]
No. There was an error in my description of the problem and I also think there was a misunderstanding. Here is a more complete example of the problem:

```
#hosts
first  node_int_ip=10.0.0.1
second  node_int_ip=10.0.0.2
```

```
#group_vars/all
---
foo: "{{ node_int_ip }}"
bar: "{{ inventory_hostname }}"
```

```
#ee.yml
---
- hosts: all
  user: root
  tasks:
    - debug: msg="from self - {{ foo }}"
    - debug: msg="from second - {{ hostvars['second']['foo'] }}"
    - debug: msg="inventory_hostname from self - {{ bar }}"
    - debug: msg="inventory_hostname from second - {{ hostvars['second']['bar'] }}"
```

Result:

```
TASK: [debug msg="from self - {{foo}}"] *************************************** 
ok: [first] => {"msg": "from self - 10.0.0.1"}
ok: [second] => {"msg": "from self - 10.0.0.2"}

TASK: [debug msg="from second - {{hostvars['second']['foo']}}"] *** 
ok: [first] => {"msg": "from second - {{node_int_ip}}"}
ok: [second] => {"msg": "from second - {{node_int_ip}}"}

TASK: [debug msg="inventory_hostname from self - {{bar}}"] ******************** 
ok: [first] => {"msg": "inventory_hostname from self - first"}
ok: [second] => {"msg": "inventory_hostname from self - second"}

TASK: [debug msg="inventory_hostname from second - {{hostvars['second']['bar']}}"] *** 
ok: [first] => {"msg": "inventory_hostname from second - {{inventory_hostname}}"}
ok: [second] => {"msg": "inventory_hostname from second - {{inventory_hostname}}"}
```

It seems that values returned from `hostvars` do not get evaluated and are therefore not exactly the same as they are for the host you are trying to access. Is there a way to overcome this?

**Comment by mpdehaan** [comment]
"It seems that values returned from hostvars do not get evaluated and are
therefore not exactly the same as they are for the host you are trying to
access"

I don't understand what you are asking here.

**Comment by gw0** [comment]
As can be seen from the last example debug prints out `"from second - {{node_int_ip}}"` instead `"from second - 10.0.0.2"`.

One would expect that `{{ hostvars['second']['foo'] }}` on any host would return exactly the same as running `{{ foo }}` on `second` host, but it doesn't.

**Comment by mpdehaan** [comment]
Ok, I see, it's a question of group_vars referencing something inside of
host_vars.

Got it.

**Comment by tdubrownik** [comment]
I can confirm running into exactly this same problem - a variable set dynamically in role/something/vars/main.yml is not visible from another host, even though it works fine on the host itself. I see this issue is closed - shouldn't you reopen it? I don't think this is expected behavior.

**Comment by barsteadr** [comment]
@tdubrownik @gw0 @mpdehaan I'm dealing with an issue similar to what you reported/commented on here #3351. Is there a work around for this?
