### ISSUE TITLE
constants.py should set to default port to None, not 22

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#3352]
I'm using the ssh config as a single location for holding all the confi
associated with connecting to a remote node, with the inventory
file just referencing the names of ssh host aliases, and use  ANSIBLE_TRANSPORT=ssh always.
It works great for most things (keys, IPs, jump hosts), but if a remote host
uses a non-standard port, ansible ignores the port specified in the ssh
config and tries to connect on port 22, which fails.

**Comment by mpdehaan** [comment]
You should set ansible_ssh_port

**Comment by mpdehaan** [comment]
another way to do this is, in inventory

hostname:1234

**Comment by ghost** [comment]
That means I have to put connection information in the inventory, duplicating the information in
the ssh config. It would be nicer not to have to.

```
[foo]
foo1
foo2


```

ssh config

```
Host foo1
 config_this
 config_that
 jump_3_hosts_here

Host foo2
 config_this
 config_that
 public_ip
```

That really seems like good practice to me.

**Comment by mpdehaan** [comment]
Ok, looks to be a little off actually, constants.py should be setting the
SSH port to None, and it's setting the default to 22.

Thanks.
