### ISSUE TITLE
Misleading error message when undefined variable is referenced in shell command

### ISSUE THREAD

**Issue by timchen** [ansible/ansible#3354]
Example:

shell: echo {{ misspelled_variable }} chdir={{ sources_dir }}

you get this output

failed: [192.168.111.222] => {"failed": true, "item": "", "rc": 258}
msg: cannot change to directory '{{sources_dir}}': path does not exist

when in fact it's an issue with the parsing of the jinsa style variable that doesn't exist (or in my case, i had misspelled)

**Comment by mpdehaan** [comment]
Yeah can't do anything about this, if there are errors, the line will not expand, which is as designed.

If you like, using 1.3, you can make any undefined variables fatal in Ansible 1.3, which will make this clearer, and I think is exactly what you want.

see examples/ansible.cfg
