### ISSUE TITLE
Inconsistent behavior of the hg module w.r.t. dest path

### ISSUE THREAD

**Issue by rsniezynski** [ansible/ansible#3360]
If the destination path contains user expansion (~), the repo is cloned to correct directory but re-running the task causes an error:

```
msg: abort: repository ~/dev/repo already exists!
```

If the path doesn't contain expansion, re-running the task succeeds.

(ansible rev. 27d90e9003, mercurial 2.6.2)

**Comment by dljsjr** [comment]
I've encountered the exact same problem. Reproducible, and exactly as described above; ansible 1.2.2, mercurial 2.0.2

**Comment by mpdehaan** [comment]
fixed per above, so closing
