### ISSUE TITLE
selinux module should import json/simplejson

### ISSUE THREAD

**Issue by jfchevrette** [ansible/ansible#3363]
```
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1372354191.45-74111142245263/selinux", line 62, in <module>
    print json.dumps(failed=True, msg='python-selinux required for this module')
NameError: name 'json' is not defined
```

As I can understand it, json/simplejson is loaded in lib/ansible/module_common.py but that hasn't fired yet. I guess we could either try to load json/simplejson first or use sys.strerr which could be ugly. The npm package module is doing the former.

**Comment by mpdehaan** [comment]
It can simply print a string that is JSON, as some other modules do.

The npm module should match.

**Comment by trbs** [comment]
See pull request: https://github.com/ansible/ansible/pull/3534

**Comment by mpdehaan** [comment]
merged the above so can close this
