### ISSUE TITLE
playbook host list can't start with a variable

### ISSUE THREAD

**Issue by prune998** [ansible/ansible#3371]
In a playbook, the hosts value can't start with a variable : 
- hosts: {{ type }} 

leads to : 
ERROR: Syntax Error while loading YAML script, playbooks/test2.yml

using this form works : 
- hosts: my-{{ type }}

**Comment by mpdehaan** [comment]
This is not a bug in ansible but rather a misunderstanding of how YAML syntax works.

Do this:

hosts: "{{ foo }}"

This is because YAML sees "{" and things you are starting a hash, which you are not.
