### ISSUE TITLE
Extend ansible-pull to support other repository types

### ISSUE THREAD

**Issue by sfromm** [ansible/ansible#3372]
There are requests for ansible-pull to support other source repositories such as mercurial.  I propose adding support to extending ansible-pull to support other repositories, as long as there is a module for it.

As an aside, there was a request for s3 support.  However, the s3 module is for putting a file in s3 and not for downloading.

One thing that would help is if the source_control modules were a bit more consistent about parameter names.  As part of this change, I propose make name an alias for repo (if not already present) and version an alias for revision.  Modules that need the name alias:  hg.  Modules that need the version alias:  subversion, hg.

I've started some preliminary work on this.  Any comments on the above, before I submit a PR?

**Comment by giulianob** [comment]
Looking forward to this!

**Comment by mpdehaan** [comment]
We already have a pull request for this, so I am going to close the ticket, the PR is very likely to be merged and this keeps it easier to organize github.
