### ISSUE TITLE
Want to run ansible with cron using ssh and sudo with a password file

### ISSUE THREAD

**Issue by jpop1010** [ansible/ansible#33786]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME

```

```

##### SUMMARY

I cannot use password-less logins or sudo but want to automate my ansible playbooks.  New to ansible and I am having a hard time figuring out the best method for this.  It looks like vault might be my best but I am not sure about the options.  I would like to make this global using the ansible.cfg so that any of the admins can use it.  Any advice would be greatly appreciated.

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
