### ISSUE TITLE
localinstall for yum package?

### ISSUE THREAD

**Issue by nybble73** [ansible/ansible#338]
Is support for localinstall for the yum package anywhere in the roadmap? Would love to be able to send over specific rpm's to install - can copy the file over and shell out, but it'd be super pleasant to have all the goods such that it doesn't even copy over the file if the version hasn't changed.

**Comment by mpdehaan** [comment]
Hi Felix,

Questions really should be asked to the mailing list so use cases can be discussed -- being this is not a bug, and I only hold feature requests open that I intend to see implemented.

But I am interested in discussing your use case on the mailing list if you'd like to stop by.

**Comment by athompso** [comment]
For the edification of google and others who need this functionality... the yum module apparently supports a syntax like:

```
  yum: name=/path/to/local/rpm/file
```

which behaves like yum localinstall.

(FYI: _my_ use case is installing newer versions of `amanda-client`, for which no yum repo currently seems to exist.)
