### ISSUE TITLE
sysctl module does not work on FreeBSD

### ISSUE THREAD

**Issue by arsatiki** [ansible/ansible#3380]
The sysctl module appears to be using procfs to set sysctl values. On FreeBSD, procfs is now deprecated and the sysctl tool is the preferred way to set values.

Also, the FreeBSD sysctl does not support the -p switch for reloading the data.

I am using command and lineinfile as a workaround. It would be better to have a working syctl module, however.

**Comment by mpdehaan** [comment]
Is this something you would like to work on?

If not, we should at least modify the documentation.

**Comment by arsatiki** [comment]
I can look into it. Not immediately, but hopefully within the week.

I'd like to ask for one clarification on the sysctl module.

With the sysctl tool, the primary mode of operation is to modify the option in the running kernel. Persisting the change in sysctl.conf is sort of secondary.

The module, to me, seems to primarily be about setting values in sysctl conf; modifying live values is done via the "reload". So it's sort of flipped. Is this understanding correct.

**Comment by bcoca** [comment]
The changes should be easy, FreeBSD allows setting values using the sysctl
cmd line tool (much easier than playing with proc). I'll add to my list,
i'll probably have time for it within 2weeks (unless someone beats me to
it).

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno
