### ISSUE TITLE
Feature request: rc_file module

### ISSUE THREAD

**Issue by arsatiki** [ansible/ansible#3381]
FreeBSD seems very fond of "rc-style" configuration files, which have the following format:

```
# Comment
SOMETHING=somevalue
```

Examples of this are make.conf, sysctl.conf, rc.conf and many others.

The format is close, but not exactly the INI-format, which makes the ini_file module unusable. The lineinfile module works but is wordy and makes the playbook look cumbersome.

I'd like to see an rc_file module, that would help in configuring values for such files.

I'm nearly volunteering to write one myself, but there is a gotcha. At least the service module contains code that manipulates rc.conf directly to set (some of the values) there. Would it be important to refactor that code into a centralized location and if so, what would that place be? I am not overly familiar with Ansible internals.

**Comment by mpdehaan** [comment]
lineinfile is pretty painful, I agree.

Can you not use the template module for managing these files?

No, I generally don't think we need to worry about code sharing at this point, but I'm also inclined to maybe _not_ include this one, but link to it from the contrib modules resources page.

(Closing this not because I disagee with the idea, but just because I tend to not leave feature request tickets open we're not committing to.)

**Comment by arsatiki** [comment]
Some of these files are easy to manage with simply copy. Also, if I fix #3380, that will take away one of the offenders, sysctl.conf.

But looking at my playbooks, that leaves at least rc.conf, which I can't generate in an easy fashion. The bloody file is manipulated by the service module, by some FreeBSD tools and probably something I don't even know. Some of the options in the file are services, some control file systems and others are just config options to services. It's a semantic nightmare!

I could, of course, just duplicate the configuration and copy the file over... but that would make the service module useless. Also, I very much prefer to keep my plays focused on a single thing: "Configure ZFS", "Configure fileserver" etc. That sort of non-local configuration seems ugly to me.

I'll have to mull it over a bit. Perhaps templating could work. But I doubt it.

**Comment by arsatiki** [comment]
Please disregard previous. Someone has replaced my brain with a bag of sand, it seems. There is, in fact, an rc.conf.d directory, which trivially solves the rc.conf problem. That removed my last usecase for such a module.
