### ISSUE TITLE
Conditionally registered variables are considered defined, even when the condition is false

### ISSUE THREAD

**Issue by wknapik** [ansible/ansible#33827]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/foo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 20 2017, 01:25:59) [GCC 7.2.0]
```
2.5.0.34308.807bebaa1f-1

##### CONFIGURATION
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Conditionally registered variables are always considered defined, which, among other things, trips up the `default()` filter.

##### STEPS TO REPRODUCE
```yaml
- shell: echo 42
  when: false
  register: foo
- debug:
    msg: "{{ foo is defined }}"
```
The message is "True".

The practical consequence is that
```yaml
- shell: echo 42
  when: false
  register: foo
- shell: echo 24
  register: bar
- debug:
    msg: "{{ (foo|default(bar)).stdout }}"
```
Will fail with `The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'`.

Maybe that's considered "by design", in which case feel free to close the issue, but the behavior with `default()` was unexpected to me. Perhaps the filter could be updated to cover this case ?

##### EXPECTED RESULTS
I expected a variable that appears to only be assigned when a condition is met, to be undefined if the condition is not met.

##### ACTUAL RESULTS
The variable is still defined and is a dictionary (`{'skipped': True, 'changed': False, 'skip_reason': u'Conditional result was False'}`).

**Comment by wknapik** [comment]
I (now) know this is the difference between `is defined` and `is skipped`, but the end result is that the variable holds no usable value. It would be nice if `default()` handled both cases, or if a new filter was introduced, that does.

**Comment by sivel** [comment]
This is not a bug and is expected, very specifically, so that you can test whether that task was skipped using `foo is skipped`.

`default` is a core filter of jinja, and I don't see us overriding or replacing it with our own.  You are likely to be well served using the `ternary` filter.

Something like:

```
((foo is not skipped)|ternary(foo, bar))['stdout'] 
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
