### ISSUE TITLE
service module does not work on FreeBSD, if startup script name differs from the "rcvar"

### ISSUE THREAD

**Issue by arsatiki** [ansible/ansible#3382]
Setting up a service on FreeBSD requires writing an rcvar line, i.e. "XXX_enabled = yes" to /etc/rc.conf and starting the daemon via startup script via the service tool.

At least for avahi-daemon, the names of the startup script and the rcvar differ. The startup script is called avahi-daemon, but the rcvar is avahi_daemon_enable. This breaks the FreeBSD service module for avahi-daemon.

It is possible to dig up the rcvar with the service command:

```
[ars@zardoz ~]$ service avahi-daemon rcvar
# avahi_daemon
#
avahi_daemon_enable="YES"
#   (default: "")

[ars@zardoz ~]$ 
```

The change looks easy enough, so I can provide a pull request once I've had time to work on it. However, I don't have time to work on it for at least for the few next days. If some one else wants to pick this up, feel free.

**Comment by mpdehaan** [comment]
Thanks, if you can take a crack at this, it would be much appreciated!

**Comment by arsatiki** [comment]
As a note to future myself or anyone else investigating this, here's a list of services I've encountered so far that suffer from this issue:
- avahi-daemon
- statd
- lockd

Also possibly sendmail.

**Comment by arsatiki** [comment]
Sendmail's situation is more complex. It seems that a single script in rc.d can launch several daemon processes, each which have their own rcvars. So `service sendmail rcvar` returns this when sendmail is enabled:

```
# sendmail
#
sendmail_enable="yes"
#   (default: "")

# sendmail_clientmqueue
#
sendmail_enable="yes"
#   (default: "")
sendmail_msp_queue_enable="YES"
#   (default: "")
```

**Comment by mpdehaan** [comment]
merged the above so should be able to close this
