### ISSUE TITLE
ansible-doc does not extend doc fragments

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#33864]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible-doc

##### ANSIBLE VERSION

```
2.4.2 
devel
```

##### CONFIGURATION

NA

##### OS / ENVIRONMENT

NA

##### SUMMARY
ansible-doc does not show docs of doc fragments but shows e.g. for cs_vpc

~~~
AUTHOR: René Moser (@resmo)
EXTENDS_DOCUMENTATION_FRAGMENT: cloudstack
        METADATA:
          status:
          - stableinterface
~~~
##### STEPS TO REPRODUCE

```yaml
ansible-doc cs_vpc
```

##### EXPECTED RESULTS

full docs including docs in doc fragments

##### ACTUAL RESULTS

~~~
AUTHOR: René Moser (@resmo)
EXTENDS_DOCUMENTATION_FRAGMENT: cloudstack
        METADATA:
          status:
          - stableinterface
~~~

**Comment by gundalow** [comment]
`2.3.3.0 (stable-2.3 d4ea3c6ca2)` works

**Comment by bcoca** [comment]
probably fixed in  #31677

**Comment by gundalow** [comment]
#31677 includes feature work, so are we happy having this broken in 2.4?

**Comment by resmo** [comment]
I confirm, #31677 fixes the issue.
