### ISSUE TITLE
inventory global variables failing

### ISSUE THREAD

**Issue by buggsdummy** [ansible/ansible#33956]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vpha200/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]

```

##### SUMMARY

I have a variables defined in stg.yml and a [stg:vars] with a global var Environment=stg, it is the only place that's defining that and it's not seeing it anymore. 

##### STEPS TO REPRODUCE

```yaml

ansible-playbook -i stg system-ch2/system_s1.yml

```

##### EXPECTED RESULTS

Be able to use those variables

##### ACTUAL RESULTS

: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'Environment' is undefined"}

```

```

**Comment by sivel** [comment]
Can you please provide a more complete minimal reproducer so that we can better understand your issue?  As it is there isn't much information to go on.

Consider creating a repository with a minimal set of reproducer files that show this issue and provide that to us.

needs_info
