### ISSUE TITLE
playbook with "hosts: all" gathers all hosts from inventory including other groups, even though it's restricted with specific group "all: children and children: group"

### ISSUE THREAD

**Issue by rajeshcipher** [ansible/ansible#33988]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/rajesh/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### SUMMARY

I have different inventories based on my environments (staging inventory, QA inventory, production inventory etc..) and different group within the inventories (DB, App, Web etc..,) and also additional group of hosts within the same inventory which serves a different purpose (for example group name is mobileservers)

I have to run certain tasks in all three groups DB, App, Web and certain tasks only on mobileservers.

[all:vars]
ansible_user=admin
ansible_become=true
ansible_become_method=su
ansible_become_user=root

[all:children]
staging

[staging:children]
staging_app
staging_web
staging_db

[mobileservers:children]
mobileservers_staging

mobileservers_staging
192.168.x.x

My playbook example 

- hosts: all
  roles:
  - firewalld

If I run this playbook, it gathers all the hosts in the inventory including the mobileservers, when 'all' is restricted only to staging which has to collect the information of app, db and web only.

**Comment by sivel** [comment]
I'm not following your problem.

You have explicitly defined `hosts: all`, so I would expect it to gather facts for all hosts in the inventory.

You do make a vague mention about:

> when 'all' is restricted only to staging

But it's not clear to me what this means.

Can you provide a more verbose explanation, and explain more about your "restricted only to staging" comment?

It will also be useful to see the exact command you execute, and the output of `ansible-playbook` with a minimum of `-v`

needs_info

**Comment by RyanSammon** [comment]
@sivel It looks like he is trying to alter what `all` means by specifying its children (only the `staging` group). Looking through the documentation, but not the code, my guess is `all` is implemented as a pattern, not a group, so what he is trying to do won't work.

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

All groups are ALWAYS children of `all`, does not matter that you define them or not as such.
You CANNOT restrict `all` to less than that, as such this is not a bug. 

Both `all` and `ungrouped` are special groups in Ansible and you can't change the rules of their membership.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by tishma** [comment]
@bcoca Are you saying that one can not limit play to a group of hosts by saying:
`ansible-playbook play/my_book.yml  --limit mygroup`.
That's very disappointing because:
1. various resources found on internet suggest it is possible (yet I can't get it to work) AND
2. http://docs.ansible.com/ansible/latest/cli/ansible-playbook.html#cmdoption-ansible-playbook-l says nothing about what is allowed and what not.
