### ISSUE TITLE
hostvars leak between ansible-playbook invocations when hostnames/IPs are re-used between inventories

### ISSUE THREAD

**Issue by anlutro** [ansible/ansible#34035]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/home/andreas/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/andreas/.local/venvs/ansible/local/lib/python2.7/site-packages/ansible
  executable location = /home/andreas/.local/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION
No configuration, all defaults.

##### OS / ENVIRONMENT
Debian 9, Linux

##### SUMMARY
We have a setup of test/production inventories. The machines in these inventories have private 192.168.0.0/24 IPs which are reached through separate jumphosts. Because of the machines being on private subnets, there is a chance of IPs being identical across inventories.

I'm seeing that `hostvars` are somehow cached between multiple `ansible-playbook` runs, despite not having any fact caching enabled.

I've tried all sorts of combinations of `meta: clear_facts` tasks and `gather_facts: true/false` on the plays, to no effect.

##### STEPS TO REPRODUCE
Set up 2 separate inventories, where two machines in separate inventories share an IP. A stripped down version of our inventories looks like this:

```
[jumphost]
1.2.3.4 ansible_ssh_common_args=""

[example]
192.168.0.1

[all:vars]
ansible_ssh_common_args = -o ProxyCommand="ssh -q -o StrictHostKeyChecking=no -W %h:%p root@1.2.3.4"
```

The playbook I'm running:

```yaml
- name: collect hostnames
  hosts: all
  tasks:
    - name: run command to get host fqdn
      command: hostname -f
      register: fqdn_cmd

- name: print hostnames
  hosts: jumphost
  tasks:
    - debug:
        msg: >
          {% for ip in groups['all']|sort if 'fqdn_cmd' in hostvars[ip] %}
          {{ ip }}={{ hostvars[ip].fqdn_cmd.stdout }}
          {% endfor %}
```

##### EXPECTED RESULTS
I expect to see hostnames of the machines in the inventory I specify.

##### ACTUAL RESULTS
```
$ ansible-playbook -i inventory/test ./test.yml 

PLAY [collect hostnames] *******************************************************************************

TASK [Gathering Facts] *********************************************************************************
ok: [XX.XXX.XX.44]
ok: [192.168.0.12]
ok: [192.168.0.17]
ok: [192.168.0.10]
ok: [192.168.0.11]

TASK [run command to get host fqdn] ********************************************************************
changed: [XX.XXX.XX.44]
changed: [192.168.0.10]
changed: [192.168.0.17]
changed: [192.168.0.12]
changed: [192.168.0.11]

PLAY [print hostnames] *********************************************************************************

TASK [Gathering Facts] *********************************************************************************
ok: [XX.XXX.XX.44]

TASK [debug] *******************************************************************************************
ok: [XX.XXX.XX.44] => {
    "msg": " 192.168.0.10=host1.test.redacted.com  192.168.0.11=host2.test.redacted.com  192.168.0.12=host3.test.redacted.com  192.168.0.17=host4.test.redacted.com  XX.XXX.XX.44=host5.test.redacted.com \n"
}

PLAY RECAP *********************************************************************************************
192.168.0.10               : ok=2    changed=1    unreachable=0    failed=0   
192.168.0.11               : ok=2    changed=1    unreachable=0    failed=0   
192.168.0.12               : ok=2    changed=1    unreachable=0    failed=0   
192.168.0.17               : ok=2    changed=1    unreachable=0    failed=0   
XX.XXX.XX.44               : ok=4    changed=1    unreachable=0    failed=0   
```

```
$ ansible-playbook -i inventory/prod ./test.yml 

PLAY [collect hostnames] *******************************************************************************

TASK [Gathering Facts] *********************************************************************************
ok: [XX.XXX.XX.40]
ok: [192.168.0.11]
ok: [192.168.0.13]

TASK [run command to get host fqdn] ********************************************************************
changed: [XX.XXX.XX.40]
changed: [192.168.0.11]
changed: [192.168.0.13]

PLAY [print hostnames] *********************************************************************************

TASK [Gathering Facts] *********************************************************************************
ok: [XX.XXX.XX.40]

TASK [debug] *******************************************************************************************
ok: [XX.XXX.XX.40] => {
    "msg": " 192.168.0.11=host2.test.redacted.com  192.168.0.13=host4.prod.redacted.com  XX.XXX.XX.40=host5.prod.redacted.com \n"
}

PLAY RECAP *********************************************************************************************
192.168.0.11               : ok=2    changed=1    unreachable=0    failed=0   
192.168.0.13               : ok=2    changed=1    unreachable=0    failed=0   
XX.XXX.XX.40               : ok=4    changed=1    unreachable=0    failed=0
```

Notice `test.redacted.com` in the second output block. That's not the correct hostname of the instance that's being connected to, it's the hostname of the machine with the same IP from the test environment.

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Ansible isn't doing any caching, the cache would only affect 'facts' if it were enabled, not host vars. The issue here is that you are using ssh sockets based on host IP and port, since this happens both locally and the jumphost you are reusing existing connections instead of establishing new ones (as both things match across environments). Either make the ssh socket names unique by adding the inventory name or some other way, or ensure that existing sockets and connections are dead before rerunning plays.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
