### ISSUE TITLE
free_form parameter doc for command module

### ISSUE THREAD

**Issue by hyao** [ansible/ansible#3403]
At http://www.ansibleworks.com/docs/modules.html#commands

The free_form parameter is 'yes' for required; maybe it's meant to be 'yes' for default?

Thanks,

**Comment by mpdehaan** [comment]
There is no default for the command module parameter here, you have to specify what command you want to execute.

For example:

command: /usr/bin/foo --asdf --jkl

The "free form" here is the whole command string to be executed.
