### ISSUE TITLE
'file' module does not accept "context" argument

### ISSUE THREAD

**Issue by c0rner** [ansible/ansible#3408]
The man file for the file module states "context accepts only default as value. This will restore a file’s SELinux context in the policy".

I know this used to work in the past but for some reason 'context' is no longer accepted as argument

> msg: unsupported parameter for module: context

I just verified this using commit 25aaee4c38f339b4c8450f08c9cf87aa66a76df2 from the devel branch.

Is the manual wrong or do we have a bug in module_common?

**Comment by c0rner** [comment]
Just installed 'libselinux-python' on both source and destination servers with no change in behaviour.

To reproduce:

> $ ansible all -m file -a "path=/tmp state=directory context=default" -i"localhost,"
> localhost | FAILED >> {
>    "failed": true, 
>    "msg": "unsupported parameter for module: context"
> }

**Comment by bcoca** [comment]
the error you are getting is that it just doesn't accept the parameter, not even related to selinux bindings being installed or not, dies much sooner than that.  Nor is this related to the other error about contexts being destroyed. 

Not sure if this was ever implemented or taken out by accident, will give it a look.

**Comment by bcoca** [comment]
just went back in history a bit, I don't think this was ever implemented. What DOES work is that new files get default context if selinux is enabled and python bindings are installed. If I'm reading the code correctly.

**Comment by mpdehaan** [comment]
maybe a long time ago, I believe it only accepted context=default but new
files should get default context of course.

I think we just have to make it fatal, really.

**Comment by bcoca** [comment]
it is already fatal, it doesn't allow the context param, I think you are
mixing with the other issue about copy not preserving the selinux context.

On Sun, Jul 14, 2013 at 11:19 PM, Michael DeHaan
notifications@github.comwrote:

> maybe a long time ago, I believe it only accepted context=default but new
> files should get default context of course.
> 
> I think we just have to make it fatal, really.
> 
> On Sun, Jul 14, 2013 at 11:13 PM, Brian Coca notifications@github.comwrote:
> 
> > just went back in history a bit, I don't think this was ever
> > implemented.
> > What DOES work is that new files get default context if selinux is
> > enabled
> > and python bindings are installed.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ansible/ansible/issues/3408#issuecomment-20950117>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/3408#issuecomment-20950207
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
The fatal checking has already been implemented, and I have just removed "context" from the docs since it's not implemented.

It would probably be nice if it were reinstated.
