### ISSUE TITLE
ansible_processor_cores is wrong on ec2 m1.xlarge

### ISSUE THREAD

**Issue by DazWorrall** [ansible/ansible#3409]
m1.xlarge has 4 vcpus, but ansible_processor_cores is 1. Looking at the code, this seems to be because the cpuid of all the processors in cpuinfo is the same int, but the core count is 1 - which seems wrong anyway. As far as I can see, nothing will give me the number '4', not even the ec2_facts module

Here's a gist with the setup and cpuinfo output: https://gist.github.com/DazWorrall/5909754

**Comment by mpdehaan** [comment]
something you would like to work on, perhaps?

**Comment by DazWorrall** [comment]
With a bit of a steer, sure. I'm not sure if this a quirk of xen or paravirt - what is the right approach when you cant 'trust' the cpu id's and core count? Should the code identify it's on xen and count the cpus differently, or should we have another fact which is just the count of the processors the kernel sees?

I've added a couple more /proc/cpuinfo examples to the gist, from a multi vcpu KVM machine and a dual cpu real server, for reference.

**Comment by mpdehaan** [comment]
Yeah, I don't know.

**Comment by mpdehaan** [comment]
closing per above, thanks!

**Comment by danvaida** [comment]
sorry to bump into this one again, is it possible for this issue to still exist?
I'm experiencing it on ansible 1.8 (devel 9edf3a749a) last updated 2014/08/13 09:45:46 (GMT +200)

**Comment by amccloud** [comment]
I am also experiencing this issue with m3.xlarge

**Comment by craigbruce** [comment]
Using 1.7.1 my m3.xlarge instance is reporting 2 not 4 cores.

**Comment by manuel-sousa** [comment]
Instance c3.large has the same issue
