### ISSUE TITLE
When: -> jinja2 conditionals not translating correctly

### ISSUE THREAD

**Issue by fignew** [ansible/ansible#3410]
I'm iterating with_items: over a dict (no problem with .keys() after the variable name) but I need to check the value of the key with when:

In 1.1 I did:
- `only_if: ${lamp_httpd_confd.${item}} == 0`

but I can't get the same thing to work in 1.2.
- `when: ${lamp_httpd_confd.${item}}`
  - `Conditional expression must evaluate to True or False: {% if True %} True {% else %} False {% endif %}`

Same thing happens with a slightly different conditonal (and True/False replaced with 1/0 in var:)
- `when: ${lamp_httpd_confd.${item}} == 0`
  - `Conditional expression must evaluate to True or False: {% if 1 == 0 %} True {% else %} False {% endif %}`

lamp_httpd_confd looks like `{'ssl': 1, 'drudev': 1, 'php': 1, 'site_internet': 1, 'logstash': 0}`
### var_file:

```
lamp_httpd_confd:
    logstash: 0
    php: 1
    ssl: 1
    drudev: 1
    site_internet: 1
```
### play:

```
- name: lamp | configure apache conf.d
  action: shell echo ${lamp_httpd_confd.${item}}
  with_items: lamp_httpd_confd.keys()
  when: ${lamp_httpd_confd.${item}} == 0
```

I've tested this on a Ansible 1.2 release on RHEL and Ubuntu.

**Comment by mpdehaan** [comment]
You probably should not use the ${old_style} stuff with when, all of that stuff is effectively deprecated. Most operations will still work but it will occasionally cause problems.

This can all be simplified:

when:  some_variable[some_string]

Now, conditionals in with_items don't work like that IIRC, they decide whether or not to execute the entire statement, so I think this is probably about "item" not being in scope mostly.
