### ISSUE TITLE
azure_rm_storageaccount error <SkuName.standard_lrs: 'Standard_LRS'> is not valid value for enum <enum 'SkuName'>

### ISSUE THREAD

**Issue by stacker2017** [ansible/ansible#34122]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.2.0
```

##### SUMMARY
When trying to run following playbook:
- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create storage account
    azure_rm_storageaccount:
       resource_group: awx
       name: testaccount2018
       type: Standard_LRS

get the error:
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_mYsI6M/ansible_module_azure_rm_storageaccount.py", line 462, in <module>
    main()
  File "/tmp/ansible_mYsI6M/ansible_module_azure_rm_storageaccount.py", line 459, in main
    AzureRMStorageAccount()
  File "/tmp/ansible_mYsI6M/ansible_module_azure_rm_storageaccount.py", line 204, in __init__
    supports_check_mode=True)
  File "/tmp/ansible_mYsI6M/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py", line 285, in __init__
  File "/tmp/ansible_mYsI6M/ansible_module_azure_rm_storageaccount.py", line 240, in exec_module
    self.results['state'] = self.create_account()
  File "/tmp/ansible_mYsI6M/ansible_module_azure_rm_storageaccount.py", line 416, in create_account
    poller = self.storage_client.storage_accounts.create(self.resource_group, self.name, parameters)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/azure/mgmt/storage/v2017_06_01/operations/storage_accounts_operations.py", line 159, in create
    body_content = self._serialize.body(parameters, 'StorageAccountCreateParameters')
  File "/home/ubuntu/.local/lib/python2.7/site-packages/msrest/serialization.py", line 466, in body
    SerializationError, "Unable to build a model: "+str(err), err)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/msrest/exceptions.py", line 48, in raise_with_traceback
    raise error
msrest.exceptions.SerializationError: Unable to build a model: <SkuName.standard_lrs: 'Standard_LRS'> is not valid value for enum <enum 'SkuName'>, DeserializationError: <SkuName.standard_lrs: 'Standard_LRS'> is not valid value for enum <enum 'SkuName'>

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_mYsI6M/ansible_module_azure_rm_storageaccount.py\", line 462, in <module>\n    main()\n  File \"/tmp/ansible_mYsI6M/ansible_module_azure_rm_storageaccount.py\", line 459, in main\n    AzureRMStorageAccount()\n  File \"/tmp/ansible_mYsI6M/ansible_module_azure_rm_storageaccount.py\", line 204, in __init__\n    supports_check_mode=True)\n  File \"/tmp/ansible_mYsI6M/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 285, in __init__\n  File \"/tmp/ansible_mYsI6M/ansible_module_azure_rm_storageaccount.py\", line 240, in exec_module\n    self.results['state'] = self.create_account()\n  File \"/tmp/ansible_mYsI6M/ansible_module_azure_rm_storageaccount.py\", line 416, in create_account\n    poller = self.storage_client.storage_accounts.create(self.resource_group, self.name, parameters)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/azure/mgmt/storage/v2017_06_01/operations/storage_accounts_operations.py\", line 159, in create\n    body_content = self._serialize.body(parameters, 'StorageAccountCreateParameters')\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/msrest/serialization.py\", line 466, in body\n    SerializationError, \"Unable to build a model: \"+str(err), err)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/msrest/exceptions.py\", line 48, in raise_with_traceback\n    raise error\nmsrest.exceptions.SerializationError: Unable to build a model: <SkuName.standard_lrs: 'Standard_LRS'> is not valid value for enum <enum 'SkuName'>, DeserializationError: <SkuName.standard_lrs: 'Standard_LRS'> is not valid value for enum <enum 'SkuName'>\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}

##### STEPS TO REPRODUCE

create a test.yml file and copy:
name: Create Azure VM
hosts: localhost
connection: local
tasks:
name: Create storage account
azure_rm_storageaccount:
resource_group: awx
name: testaccount2018
type: Standard_LRS

you should also put the credential file in ~/.azure/credentials
[default]
subscription_id=xxxxxxxxxxxxxxxxxxx
client_id=xxxxxxxxxxxxxxxxxxxxxxx
secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
tenant=xxxxxxxxxxxxxxxxxxxxxxxxx

```yaml

```

##### EXPECTED RESULTS
the storage account to be created in azure!

##### ACTUAL RESULTS

```

```

**Comment by ianwijaya** [comment]
got same error @_@

**Comment by stacker2017** [comment]
@ianwijaya try https://github.com/Azure/msrest-for-python/issues/75 the workaround solved my issue, I am going to close this ticket since is being worked on under different ticket
