### ISSUE TITLE
 Ansible startup performance slow due to time spent loading in ConfigManager

### ISSUE THREAD

**Issue by Hercules888** [ansible/ansible#34147]
##### ISSUE TYPE
- Feature Idea
 
##### ANSIBLE VERSION

```
ansible 2.4.1.0
```

##### OS / ENVIRONMENT

Linux pine64 3.10.104-2-pine64-longsleep #113 SMP PREEMPT Thu Dec 15 21:46:07 CET 2016 aarch64 aarch64 aarch64 GNU/Linux

##### SUMMARY

Ansible startup performance on (slow) test system 10 sec. mainly due to parsing of ansible/config/base.yml.
Could be reduced by patching ansible/config/manager.py, and adding 
`yaml.SafeLoader = yaml.CSafeLoader`
before 
`yaml.safe_load(config_def) `
is invoked.
Reduces startup time to 1/3rd of initial time.

I checked pyyaml if CSafeLoader can be forced as a default one way or another, 
and after a quick check, I didn't find a possibility to set a default loader (except with extra parameter)
(https://github.com/yaml/pyyaml/blob/master/lib/yaml/__init__.py)

Is it possible to have the CSafeLoader as the default behaviour when running ansible?

##### STEPS TO REPRODUCE

Just run ansible executable

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by jctanner** [comment]
@Hercules888 Could you retest with the AnsibleLoader class?

`from ansible.parsing.yaml.loader import AnsibleLoader`

If that retains the same performance as csafeloader, could you submit a PR?

Thanks for digging into this, it's very much appreciated.
