### ISSUE TITLE
service: name=sshd.socket: "msg: service name not recognised"

### ISSUE THREAD

**Issue by groks** [ansible/ansible#3417]
With these tasks:

```
- name: deactivate ssh daemon mode
  service: name=sshd state=stopped enabled=no

- name: activate sshd socket
  service: name=sshd.socket state=started enabled=yes
```

I get this error message:

```
TASK: [activate sshd socket] ************************************************** 
failed: [host] => {"failed": true, "item": ""}
msg: service name not recognized
```

But sshd.socket exists:

```
$ systemctl status sshd.socket 
sshd.socket - SSH Socket for Per-Connection Servers
       Loaded: loaded (/etc/systemd/system/sshd.socket; enabled)
       Active: active (listening) since Fri 2013-06-28 16:06:14 BST; 4 days ago
       Listen: [::]:22 (Stream)
     Accepted: 137; Connected: 0
```

I need to specify .socket to distinguish between sshd.service, but it looks like ansible is unhappy with it.

ansible-1.2-1.fc18.noarch, fedora 18

**Comment by mpdehaan** [comment]
Why can't you just activate sshd in this case?

**Comment by groks** [comment]
sshd.service and sshd.socket are two completely different things. sshd.service is the file supplied by fedora which starts sshd listening on port 22. sshd.socket is a file supplied by me which tells systemd to listen on port 22 and start sshd if anyone connects. A .socket file is how you write a systemd socket-activated service.

I tried naming the new file sshdsocket.socket but ansible still complained: service name not recognised. Looks like it's not happy about .socket files.

**Comment by bcoca** [comment]
IIRC the service module looks specifically for .service files

Brian Coca

**Comment by mpdehaan** [comment]
Yes, this is true.

You might just want to use the command module to start it here, especially since it is supplied by you in this case.

The service module has a lot of logic to figure out if something is systemd versus older systems, etc, and is expecting to manage services.   

Now, I'm open to it getting smarter, and noticing if there is a ".foo" in it, that it shouldn't try to add the ".service", and if you want to have a go at hacking the module source a bit, that might be a good solution -- it would be helpful if you could do that and test on your end, especially as you've added in some software components not in the stock distro.

Sound reasonable?

**Comment by bcoca** [comment]
to disable a service for systemd you can just rename the extension, ansible

## just looks for .service, it should also look for .socket.

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by groks** [comment]
Turns out there's a variety of unit types that systemd handles. In the following patch, if the user explicitly specifies a valid unit type, eg. `foo.socket`, respect that. If only `foo` is passed, try adding `.service` as before.

``` diff
diff --git a/library/system/service b/library/system/service
index f0b330b..4ae1d3e 100644
--- a/library/system/service
+++ b/library/system/service
@@ -394,19 +394,28 @@ class LinuxService(Service):
             return
         elif location.get('systemctl', None):

-            # verify service is managed by systemd
-            rc, out, err = self.execute_command("%s list-unit-files" % (location['systemctl']))
+            # default to .service if the unit type is not specified
+            name = self.name
+            if name.find('.') > 0:
+                unit_name, unit_type = name.rsplit('.')
+                if unit_type not in ("service", "socket", "device", "mount", "automount",
+                                     "swap", "target", "path", "timer", "snapshot"):
+                    name = "%s.service" % name
+            else:
+                name = "%s.service" % name

             # adjust the service name to account for template service unit files
-            index = self.name.find('@')
-            if index == -1:
-                name = self.name
-            else:
+            index = name.find('@')
+            if index > 0:
                 name = self.name[:index+1]

-            look_for = "%s.service" % name
+            self.__systemd_unit = name
+
+            # verify service is managed by systemd
+            rc, out, err = self.execute_command("%s list-unit-files" % (location['systemctl']))
+
             for line in out.splitlines():
-                if line.startswith(look_for):
+                if line.startswith(self.__systemd_unit):
                     self.enable_cmd = location['systemctl']
                     break

@@ -516,7 +525,7 @@ class LinuxService(Service):
                 return

         if self.enable_cmd.endswith("systemctl"):
-            (rc, out, err) = self.execute_command("%s show %s.service" % (self.enable_cmd, self.name))
+            (rc, out, err) = self.execute_command("%s show %s" % (self.enable_cmd, self.__systemd_unit))

             d = dict(line.split('=', 1) for line in out.splitlines())
             if "UnitFileState" in d:
@@ -585,7 +594,7 @@ class LinuxService(Service):
         if self.enable_cmd.endswith("rc-update"):
             args = (self.enable_cmd, add_delete, self.name + " " + self.runlevel)
         elif self.enable_cmd.endswith("systemctl"):
-            args = (self.enable_cmd, enable_disable, self.name + ".service")
+            args = (self.enable_cmd, enable_disable, self.__systemd_unit)
         else:
             args = (self.enable_cmd, self.name, on_off)

@@ -609,7 +618,7 @@ class LinuxService(Service):
             else:
                 # systemd commands take the form <cmd> <action> <name>
                 svc_cmd = self.svc_cmd
-                arguments = "%s %s" % (self.name, arguments)
+                arguments = "%s %s" % (self.__systemd_unit, arguments)
         elif self.svc_initscript:
             # upstart
             svc_cmd = "%s" % self.svc_initscript

```

It seems to do the business and hasn't broken any of the tests, but I haven't had a chance to test it extensively.

**Comment by mpdehaan** [comment]
Can you please submit this patch as a pull request?
