### ISSUE TITLE
Is it possible to launch an anisble playbook remotely using a JAVA / rest API. 

### ISSUE THREAD

**Issue by jackhalfalltrades** [ansible/ansible#34242]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
2.3.1.0
```

##### SUMMARY
Trying to execute remote Ansible playbook, through a JAVA or Rest API.

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by clementtrebuchet** [comment]
If you have Tower or AWX you can do it.
http://docs.ansible.com/ansible-tower/2.3.0/html/towerapi/intro.html

**Comment by maxamillion** [comment]
Remote execution via a REST API is not a part of Ansible Core functionality at this time.
