### ISSUE TITLE
Name variable no longer inherited 

### ISSUE THREAD

**Issue by mscherer** [ansible/ansible#34272]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### CONFIGURATION

Nothing special

##### SUMMARY
So I do use variable inheritence quite a lot, especially to define roles that pull others roles with specific change. However, I found that if a variable is called name, this is no longer inherited.

I bisected to that commit:
0d35a69f0eea191f423ba6b0120ffffcbd6d9ed1

I suspect the "inherit=False" is the root cause of my issue. I did verify that changing the name of the variable do fix the issue (e.g., it only manifests for 'name', not for 'name2'.

I do use this construct for example on https://github.com/gluster/gluster.org_ansible_configuration/blob/master/playbooks/deploy_proxy_vm.yml  with a common set of param being set by using meta and dependencies on https://github.com/gluster/gluster.org_ansible_configuration/blob/master/roles/guest_proxy_rht/meta/main.yml

##### STEPS TO REPRODUCE

play.yml

```yaml
---
- hosts: 127.0.0.1
  roles:
  - role: foo
    name: foo1

```
roles/foo/meta/main.yml

```yaml
---
dependencies:
- role: foo2
```

roles/foo2/tasks/main.yml
```yaml
---
- name: "Test if {{ name }} is defined"
  debug:
    var: name
```

##### EXPECTED RESULTS

I expected this message to be displayed:
```
TASK [foo2 : Test if {{ name }} is defined] *************************************************************
ok: [127.0.0.1] => {
    "name2": "foo1"
}
```

##### ACTUAL RESULTS

This message is displayed

```
TASK [foo2 : Test if {{ name }} is defined] *************************************************************

ok: [127.0.0.1] => {
    "name": "VARIABLE IS NOT DEFINED!"
}
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

This was actually a bug fix, role `name `is NOT a variable but a property of the role that is aliased/overlaps with the `role` property. If you need a 'name' variable, use the `vars:` property to define it.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by mscherer** [comment]
That's still a behavior change that break existing playbook, and so should be documented at minima.

**Comment by mscherer** [comment]
Looking at https://docs.ansible.com/ansible/devel/playbooks_reuse_roles.html this is not documented or anything. So pushing a change as a bugfix for a non documented behavior that result in breakage of users playbooks is not really great, I would at least expect the usual deprecation cycle if that's the way we want to go, and have something somewhere in CHANGELOG.

**Comment by samdoran** [comment]
Role docs have been updated to use `vars`.  There is a [porting guide entry](https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_2.5.html?highlight=porting%20guide#fixed-handling-of-keywords-and-inline-variables) that addresses this change in behavior.
