### ISSUE TITLE
execution does not through sudo when umask is set to 077

### ISSUE THREAD

**Issue by dyleck** [ansible/ansible#343]
I have created simple playbook for testing purposes to upgrade some package through yum module. Due to configuration of my hosts I instructed ansible to execute the playbook using sudo. The execution failed with the following output

---

PLAY [test] ****************************

SETUP PHASE ****************************

failed: [elmo] => {"failed": true, "msg": "", "parsed": false}

stderr: [elmo] => cat: /home/oper/.ansible/tmp/ansible.q61g2U/sudo_result.77871: Permission denied

TASK: [test] *********

no hosts matched or remaining

PLAY RECAP **********************

elmo                           : ok=   0 changed=   0 unreachable=   0 failed=   1

---

Here is my playbook

---

---
- hosts: test
  user: oper
  sudo: true
  tasks:
  - name: test
    action: yum pkg=openssl.x86_64 state=latest

---

**Comment by mpdehaan** [comment]
hmm, this would require root to chmod it again.   Fix should be pretty simple, if you want to take a look, it's probably connection.py.

If not, I've aligned this with the 0.5 release.

**Comment by dyleck** [comment]
I will take a look. My python knowledge is quite lame but I always was quick lerner. :)

**Comment by jkleint** [comment]
What version of Ansible are you using?  This looks like the same issue I had with an older version, but is hopefully fixed in development.  You might try the devel branch and see if it's still an issue.

**Comment by dyleck** [comment]
It was development branch downloaded yesterday using the "download repo as zip" functionality.

**Comment by jkleint** [comment]
Hmm, I can't seem to find anywhere in the development source where `cat` or `sudo_result` are used.  Would you mind grepping your source for `sudo_result` and letting me know where it occurs?  And the contents of the VERSION file from the same source?  And the command line you're using with ansible-playbook?

**Comment by dyleck** [comment]
elmo:~/ansible-ansible-5a156d6 # find . -exec grep -ni sudo_result {} \; -print
116:            result_file = os.path.join(tmp_path, "sudo_result.%s" % r)
./lib/ansible/connection.py

elmo:~/ansible-ansible-5a156d6 # cat VERSION
0.3.1

I have just downloaded the branch again. Unfortunately my firewall rules forbids me to use git clone so I have to use the download as zip. I have a feeling that it is providing the quite recent version.

**Comment by mpdehaan** [comment]
0.3.1 is the last tagged release, this doesn't happen on the development branch.   Closing this since it's on the master branch and we're going to have a release really soon, and this is not something I want to incur the fun of backporting and retesting given that pending release.

BTW, if you look at the github page by the clone URL you can click http:// and then clone over http:// instead of git://
