### ISSUE TITLE
Date in YAML can't work with to_nice_json

### ISSUE THREAD

**Issue by burtonator** [ansible/ansible#34312]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
to_nice_json

##### ANSIBLE VERSION

```
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

```

##### CONFIGURATION
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_JINJA2_EXTENSIONS(/etc/ansible/ansible.cfg) = jinja2.ext.do,jinja2.ext.i18n

##### OS / ENVIRONMENT
Debian 9.2

##### SUMMARY
the to_nice_json function can't work with YAML date_time objects.

I have some metadata like:

    created_test0: 2017-12-01T01:01:00-08:00
    created_test1: 2010-04-16 16:32:03 -5

Both are just test variables. Both are parsed into dates and then to_nice_json chokes on them.

##### STEPS TO REPRODUCE

Create a YAML file with dates, use a jinja2 template to convert it to a json file and it will fail.

##### EXPECTED RESULTS

Returned as an ISO8601 string in JSON:

https://stackoverflow.com/questions/10286204/the-right-json-date-format

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleError: Unexpected templating type error occurred on ({{static_yaml_data | to_nice_json}}): datetime.datetime(2017, 12, 1, 9, 1) is not JSON serializable"}

```

**Comment by InputNeuron** [comment]
This looks like a reasonable solution:

https://gist.github.com/drmalex07/5149635e6ab807c8b21e
