### ISSUE TITLE
openstack-ansible setup-hosts.yml giving error!!

### ISSUE THREAD

**Issue by sukhan85** [ansible/ansible#34317]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

2.2.3.0

##### CONFIGURATION

ubuntu@deployment01:/opt/openstack-ansible/playbooks$ ansible-config dump --only-changed
[WARNING]: log file at /var/log/ansible.log is not writeable and we cannot create it, aborting

ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = %(directory)s/%%h-%%r
ANSIBLE_SSH_CONTROL_PATH_DIR(/etc/ansible/ansible.cfg) = ~/.ansible/cp
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /home/ubuntu/.ansible/tmp/ansible-local-4573FWikpX
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/my_modules']
DEFAULT_MODULE_UTILS_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/my_module_utils']
DEFAULT_REMOTE_TMP(/etc/ansible/ansible.cfg) = ~/.ansible/tmp
DEFAULT_SCP_IF_SSH(/etc/ansible/ansible.cfg) = True

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

when running setup-hosts.yml I get the following ERROR message. After this error "ansible -m ping all" also breaks and prompt the same message below.
```
ubuntu@deployment01:/opt/openstack-ansible/playbooks$ openstack-ansible setup-hosts.yml -vvvv
Variable files: "-e @/etc/openstack_deploy/user_secrets.yml -e @/etc/openstack_deploy/user_variables.yml "
[WARNING]: log file at /openstack/log/ansible-logging/ansible.log is not writeable and we cannot create it, aborting

Using /etc/ansible/ansible.cfg as config file
ERROR! Unexpected Exception: 'CacheModule' object has no attribute 'plugin_name'
the full traceback was:

Traceback (most recent call last):
  File "/opt/ansible-runtime/bin/ansible-playbook", line 103, in <module>
    exit_code = cli.run()
  File "/opt/ansible-runtime/local/lib/python2.7/site-packages/ansible/cli/playbook.py", line 126, in run
    variable_manager = VariableManager()
  File "/opt/ansible-runtime/local/lib/python2.7/site-packages/ansible/vars/__init__.py", line 97, in __init__
    self._fact_cache = FactCache()
  File "/opt/ansible-runtime/local/lib/python2.7/site-packages/ansible/plugins/cache/__init__.py", line 35, in __init__
    self._plugin = cache_loader.get(C.CACHE_PLUGIN)
  File "/opt/ansible-runtime/local/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 358, in get
    obj = obj(*args, **kwargs)
  File "/opt/ansible-runtime/local/lib/python2.7/site-packages/ansible/plugins/cache/jsonfile.py", line 70, in __init__
    raise AnsibleError("error in '%s' cache, configured path (%s) does not have necessary permissions (rwx), disabling plugin" % (self.plugin_name, self._cache_dir))
AttributeError: 'CacheModule' object has no attribute 'plugin_name'
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by maxamillion** [comment]
It looks like whatever path you're attempting to use as the cache, ansible doesn't have the appropriate permissions to write to.

```
File "/opt/ansible-runtime/local/lib/python2.7/site-packages/ansible/plugins/cache/jsonfile.py", line 70, in init
raise AnsibleError("error in '%s' cache, configured path (%s) does not have necessary permissions (rwx), disabling plugin" % (self.plugin_name, self._cache_dir))
```

Please verify this.

**Comment by maxamillion** [comment]
needs_info

**Comment by sukhan85** [comment]
You are correct, it was to do with permissions. All resolved.

**Comment by ramyak10** [comment]
Hi Can you tell me which file's permission you modified. am getting the same error
File "/opt/ansible-runtime/local/lib/python2.7/site-packages/ansible/plugins/cache/jsonfile.py", line 70, in init
raise AnsibleError("error in '%s' cache, configured path (%s) does not have necessary permissions (rwx), disabling plugin" % (self.plugin_name, self._cache_dir))
