### ISSUE TITLE
riak module stats timeout

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#3433]
Riak module can sometimes timeout when trying to fetch stats, this exception is not properly caught:

NOTIFIED: [wait for kv] *******************************************************
failed: [192.168.1.113] => {"failed": true, "item": ""}
msg: Could not fetch Riak stats: timed out

need to implement an exception catch for socket timeouts in additional to the urllib2.URLerror catch

**Comment by mpdehaan** [comment]
assuming you are working on this, yes?

**Comment by jsmartin** [comment]
Yep! Pull request coming.
