### ISSUE TITLE
Digital Ocean inventory plugin throws error on run

### ISSUE THREAD

**Issue by bobobo1618** [ansible/ansible#3438]
Using the Digital Ocean inventory plugin I get the following errors:

```
~> ./plugins/inventory/digital_ocean.py --droplets

Traceback (most recent call last):
  File "./plugins/inventory/digital_ocean.py", line 451, in <module>
    DigitalOceanInventory()
  File "./plugins/inventory/digital_ocean.py", line 182, in __init__
    self.load_all_data_from_digital_ocean()
  File "./plugins/inventory/digital_ocean.py", line 294, in load_all_data_from_digital_ocean
    self.build_inventory()
  File "./plugins/inventory/digital_ocean.py", line 328, in build_inventory
    image_name = self.index['image_to_name'][droplet['image_id']]
KeyError: '495741'
```

I'm using Ansible from Git and Python 2.7 on Arch Linux 64 bit.

**Comment by neomantra** [comment]
This will happen when the underlying items returned by DigitalOcean changes. For example, they recently removed the NY region and that caused similar problems.  So an image ID changed. 

I will look to make this more resilient.

**Comment by neomantra** [comment]
Oh, also, please use the plugin with this pull request applied #3415... you'll find the workflow smoother.

**Comment by bobobo1618** [comment]
Problem is that this happened on my first run. The script never returned valid information to me.

Also, where's the cache, so I can remove it if need be?

**Comment by bobobo1618** [comment]
Weird, I pulled that version and the problem persists. I've forced a refresh of the cache and even pointed it at an empty directory and that doesn't help.

The weird thing is it works without any errors when I have absolutely no droplets running.

It seems it can't find my image. Using the exact same client and api keys as I have set in my environment variables and making a request to `https://api.digitalocean.com/images/`, the image I'm using appears. When I remove all droplets from my account and use your script though, only the default images appear.

**Comment by neomantra** [comment]
The default cache location is `/tmp/ansible-digital_ocean.cache`, but you can change it from `/tmp` using `--cache-path` (or the INI file entry of the same name).

When you used the API, are you putting any filter argument in?   I see now that the underlying library, dopy (https://github.com/devo-ps/dopy/blob/master/dopy/manager.py) is using "global" as the default filter (see `all_images).  Perhaps that is not right?   I'll look deeper later today, but this might take a small change to dopy -- they are quite receptive to changes so that shouldn't be a concern.

**Comment by neomantra** [comment]
Oh, you could test this yourself quick, by changing the fragment:
`manager.all_images()`
to:
`manager.all_images(filter=None)`

I was thinking dopy needs a change as I think their code won't handle this `None` well:

```
 def all_images(self, filter='global'):
        params = {'filter': filter}
        json = self.request('/images/', params)
        return json['images']
```

But I'm not really a Python programmer, so my ability to run the interpreter in my head is weak.

**Comment by bobobo1618** [comment]
You're pretty good it seems because it worked!

Just putting that None in there worked fine, all is well!

**Comment by neomantra** [comment]
Sweet, thanks for testing.  I'll submit a pull request shortly.

**Comment by neomantra** [comment]
This has been added to pull request #3415.

**Comment by zbal** [comment]
Thanks guys - I'll review the needed changes to dopy and will get them fixed by tomorrow the latest.

In the mean time, I'd appreciate if you could [summarize the issues there](https://github.com/devo-ps/dopy/issues)

**Comment by neomantra** [comment]
I don't think any changes are needed to dopy -- I missed that the default filter on all_images was 'global'.   By passing, `filters=None`, it was easily fixed.

**Comment by zbal** [comment]
From @neomantra [other related ticket](/ansible/ansible/pull/3357#issuecomment-20525081)

**Comment by zbal** [comment]
@neomantra - no more issues then ? it may be worth setting such filter's value as a default, ([dopy](https://github.com/devo-ps/dopy/) has been build for ansible due to the lack of updated digital ocean libs.)

**Comment by neomantra** [comment]
I don't think so... until people start using it and find something else...

**Comment by blocke** [comment]
This issue still seems to be occurring.  This is from Ansible devel branch pulled a few minutes ago:

```
Traceback (most recent call last):
  File "./digital_ocean.py", line 483, in <module>
    DigitalOceanInventory()
  File "./digital_ocean.py", line 188, in __init__
    self.load_all_data_from_digital_ocean()
  File "./digital_ocean.py", line 315, in load_all_data_from_digital_ocean
    self.build_inventory()
  File "./digital_ocean.py", line 359, in build_inventory
    image_name = self.index['image_to_name'][droplet['image_id']]
KeyError: '25306'
```

It appears to be still choking on image ids still even with the above filter change.  This occurs before a cache file can even be generated for the first time.

**Comment by neomantra** [comment]
Can you look in your cache file, `/tmp/ansible-digital_ocean.cache` unless you specified, and see what `25306` corresponds to?

Either way, I guess these nested array-accesses should be protected.

**Comment by neomantra** [comment]
Try this patch:
https://github.com/neomantra/ansible/commit/1b40611064ffb865707e55f04e58ba146feeae6c
or this file:
https://github.com/neomantra/ansible/blob/1b40611064ffb865707e55f04e58ba146feeae6c/plugins/inventory/digital_ocean.py

If it works for you, I'll submit a pull request.

**Comment by neomantra** [comment]
I messed up the branching and put it on a new branch.  Pull request is #3806

**Comment by ranjansatya** [comment]
Digital ocean inventory plugin has stopped working with following exception. I am using Ansible 1.6.1. Please help.

Traceback (most recent call last):
  File "/Users/satya/work/event-bid-source/37events-config/ansible/inventory/dev/dohosts", line 487, in <module>
    DigitalOceanInventory()
  File "/Users/satya/work/event-bid-source/37events-config/ansible/inventory/dev/dohosts", line 188, in **init**
    self.load_all_data_from_digital_ocean()
  File "/Users/satya/work/event-bid-source/37events-config/ansible/inventory/dev/dohosts", line 306, in load_all_data_from_digital_ocean
    self.data['domains']  = self.sanitize_list(manager.all_domains())
  File "/Library/Python/2.7/site-packages/dopy/manager.py", line 178, in all_domains
    json = self.request('/domains/')
  File "/Library/Python/2.7/site-packages/dopy/manager.py", line 249, in request
    raise ValueError("The API server doesn't respond with a valid json")
ValueError: The API server doesn't respond with a valid json

ERROR: failed to parse executable inventory script results: {'msg': '', 'failed': True, 'parsed': False}

**Comment by neomantra** [comment]
@ranjansatya   Hello, I am not actively using this plugin, but can try to help....

See the line:

```
File "/Library/Python/2.7/site-packages/dopy/manager.py", line 249, in request
raise ValueError("The API server doesn't respond with a valid json")
```

Can you go into `dopy/manager.py` and instrument it to print the invalid response it is getting?  I think something like `print resp.text` between `requests.get` and `json = resp.json` would do the trick; this is based on looking at the current master for dopy on github.

**Comment by ranjansatya** [comment]
Thanks. 
Here's the json response I am getting after putting the print statement. Looks like it's a invalid json.  I have slightly modified the json text to remove some of the sensitive information.

{
    "status": "OK",
    "droplets": [
        {
            "id": 124442,
            "name": "test.com",
            "image_id": 12575,
            "size_id": 62,
            "region_id": 1,
            "backups_active": false,
            "ip_address": "184.55.56.133",
            "private_ip_address": null,
            "locked": false,
            "status": "active",
            "created_at": "2013-03-15T14:17:45Z"
        }
    ]
}{
    "status": "OK",
    "regions": [
        {
            "id": 1,
            "name": "New York 1",
            "slug": "nyc1"
        },
        {
            "id": 3,
            "name": "San Francisco 1",
            "slug": "sfo1"
        },
        {
            "id": 4,
            "name": "New York 2",
            "slug": "nyc2"
        },
        {
            "id": 5,
            "name": "Amsterdam 2",
            "slug": "ams2"
        },
        {
            "id": 6,
            "name": "Singapore 1",
            "slug": "sgp1"
        }
    ]
}{
    "status": "OK",
    "images": [
        {
            "id": 1201961,
            "name": "ci-ubuntu-image",
            "slug": null,
            "distribution": "Ubuntu",
            "public": false,
            "regions": [
                4
            ],
            "region_slugs": [
                "nyc2"
            ]
        },
        {
            "id": 1339970,
            "name": "config-master snapshot",
            "slug": null,
            "distribution": "Ubuntu",
            "public": false,
            "regions": [
                4
            ],
            "region_slugs": [
                "nyc2"
            ]
        },
        {
            "id": 1351895,
            "name": "minion-ubuntu-12.04LTS",
            "slug": null,
            "distribution": "Ubuntu",
            "public": false,
            "regions": [
                4
            ],
            "region_slugs": [
                "nyc2"
            ]
        },
        {
            "id": 1601,
            "name": "CentOS 5.8 x64",
            "slug": "centos-5-8-x64",
            "distribution": "CentOS",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 1602,
            "name": "CentOS 5.8 x32",
            "slug": "centos-5-8-x32",
            "distribution": "CentOS",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 12573,
            "name": "Debian 6.0 x64",
            "slug": "debian-6-0-x64",
            "distribution": "Debian",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 12575,
            "name": "Debian 6.0 x32",
            "slug": "debian-6-0-x32",
            "distribution": "Debian",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 14097,
            "name": "Ubuntu 10.04 x64",
            "slug": "ubuntu-10-04-x64",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 14098,
            "name": "Ubuntu 10.04 x32",
            "slug": "ubuntu-10-04-x32",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 350424,
            "name": "Arch Linux 2013.05 x64",
            "slug": "arch-linux-2013-05-x64",
            "distribution": "Arch Linux",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 361740,
            "name": "Arch Linux 2013.05 x32",
            "slug": "arch-linux-2013-05-x32",
            "distribution": "Arch Linux",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 376568,
            "name": "CentOS 6.4 x32",
            "slug": "centos-6-4-x32",
            "distribution": "CentOS",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 562354,
            "name": "CentOS 6.4 x64",
            "slug": "centos-6-4-x64",
            "distribution": "CentOS",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 3100616,
            "name": "Ubuntu 12.04.4 x32",
            "slug": "ubuntu-12-04-x32",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 3101045,
            "name": "Ubuntu 12.04.4 x64",
            "slug": "ubuntu-12-04-x64",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 3101580,
            "name": "Ubuntu 13.10 x32",
            "slug": "ubuntu-13-10-x32",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 3101918,
            "name": "Ubuntu 13.10 x64",
            "slug": "ubuntu-13-10-x64",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 3102721,
            "name": "Fedora 19 x32",
            "slug": "fedora-19-x32",
            "distribution": "Fedora",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 3102879,
            "name": "Fedora 19 x64",
            "slug": "fedora-19-x64",
            "distribution": "Fedora",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 3121555,
            "name": "Ghost 0.4.2 on Ubuntu 12.04",
            "slug": "ghost",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 3240033,
            "name": "Ubuntu 14.04 x32",
            "slug": "ubuntu-14-04-x32",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 3240036,
            "name": "Ubuntu 14.04 x64",
            "slug": "ubuntu-14-04-x64",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 3243143,
            "name": "Fedora 20 x32",
            "slug": "fedora-20-x32",
            "distribution": "Fedora",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 3243145,
            "name": "Fedora 20 x64",
            "slug": "fedora-20-x64",
            "distribution": "Fedora",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 3445812,
            "name": "Debian 7.0 x64",
            "slug": "debian-7-0-x64",
            "distribution": "Debian",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 3445920,
            "name": "Debian 7.0 x32",
            "slug": "debian-7-0-x32",
            "distribution": "Debian",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 3448641,
            "name": "CentOS 6.5 x64",
            "slug": "centos-6-5-x64",
            "distribution": "CentOS",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 3448674,
            "name": "CentOS 6.5 x32",
            "slug": "centos-6-5-x32",
            "distribution": "CentOS",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 3935257,
            "name": "Django on Ubuntu 14.04",
            "slug": "django",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 3961756,
            "name": "LAMP on Ubuntu 14.04",
            "slug": "lamp",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 4136458,
            "name": "Wordpress on Ubuntu 14.04",
            "slug": "wordpress",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 4143358,
            "name": "LEMP on Ubuntu 14.04",
            "slug": "lemp",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 4148217,
            "name": "GitLab 6.9.2 CE",
            "slug": "gitlab",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 4201396,
            "name": "Redmine on Ubuntu 14.04",
            "slug": "redmine",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 4204318,
            "name": "MEAN on Ubuntu 14.04",
            "slug": "mean",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 4261622,
            "name": "Ruby on Rails on Ubuntu 14.04 (Nginx + Unicorn)",
            "slug": "ruby-on-rails",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 4295378,
            "name": "node-v0.10.29 on Ubuntu 14.04",
            "slug": "node",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 4296335,
            "name": "Docker 1.0 on Ubuntu 14.04",
            "slug": "docker",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        },
        {
            "id": 4381169,
            "name": "Dokku v0.2.3 on Ubuntu 14.04 (w/ Docker 1.0)",
            "slug": "dokku",
            "distribution": "Ubuntu",
            "public": true,
            "regions": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "region_slugs": [
                "nyc1",
                "ams1",
                "sfo1",
                "nyc2",
                "ams2",
                "sgp1"
            ]
        }
    ]
}{
    "status": "OK",
    "sizes": [
        {
            "id": 66,
            "name": "512MB",
            "slug": "512mb",
            "memory": 512,
            "cpu": 1,
            "disk": 20,
            "cost_per_hour": 0.00744,
            "cost_per_month": "5.0"
        },
        {
            "id": 63,
            "name": "1GB",
            "slug": "1gb",
            "memory": 1024,
            "cpu": 1,
            "disk": 30,
            "cost_per_hour": 0.01488,
            "cost_per_month": "10.0"
        },
        {
            "id": 62,
            "name": "2GB",
            "slug": "2gb",
            "memory": 2048,
            "cpu": 2,
            "disk": 40,
            "cost_per_hour": 0.02976,
            "cost_per_month": "20.0"
        },
        {
            "id": 64,
            "name": "4GB",
            "slug": "4gb",
            "memory": 4096,
            "cpu": 2,
            "disk": 60,
            "cost_per_hour": 0.05952,
            "cost_per_month": "40.0"
        },
        {
            "id": 65,
            "name": "8GB",
            "slug": "8gb",
            "memory": 8192,
            "cpu": 4,
            "disk": 80,
            "cost_per_hour": 0.11905,
            "cost_per_month": "80.0"
        },
        {
            "id": 61,
            "name": "16GB",
            "slug": "16gb",
            "memory": 16384,
            "cpu": 8,
            "disk": 160,
            "cost_per_hour": 0.2381,
            "cost_per_month": "160.0"
        },
        {
            "id": 60,
            "name": "32GB",
            "slug": "32gb",
            "memory": 32768,
            "cpu": 12,
            "disk": 320,
            "cost_per_hour": 0.47619,
            "cost_per_month": "320.0"
        },
        {
            "id": 70,
            "name": "48GB",
            "slug": "48gb",
            "memory": 49152,
            "cpu": 16,
            "disk": 480,
            "cost_per_hour": 0.71429,
            "cost_per_month": "480.0"
        },
        {
            "id": 69,
            "name": "64GB",
            "slug": "64gb",
            "memory": 65536,
            "cpu": 20,
            "disk": 640,
            "cost_per_hour": 0.95238,
            "cost_per_month": "640.0"
        }
    ]
}{
    "status": "OK",
    "ssh_keys": [
        {
            "id": 52261,
            "name": "digital-ocean-salt-cloud.pub"
        },
        {
            "id": 52262,
            "name": "test.mac"
        },
        {
            "id": 52271,
            "name": "Vagrant"
        },
        {
            "id": 53278,
            "name": "config-master"
        }
    ]
}{
    "status": "OK",
    "domains": [
        {
            "id": 123242,
            "name": "test.com",
            "ttl": 1800,
            "live_zone_file": "****",
            "error": null,
            "zone_file_with_error": null
        }
    ]
}

**Comment by neomantra** [comment]
Yes, it does look like invalid JSON.  I suggest you print out the URL and the params, and attempt to GET it directly with a web browser or curl.  If it is indeed a malformed response, submit a bug report to DigitalOcean.
