### ISSUE TITLE
combine two variables into one

### ISSUE THREAD

**Issue by JoshuaSeidel** [ansible/ansible#34484]
how do i combine two vars to be used as one.

example

app_name = ui
ui_memory = 128

variable to use in playbook: {{ app_name + _memory }} ?????

how do i use a var or vars combined to make a var name?

**Comment by Akasurde** [comment]
If you want output as ui128 then

```yaml
- debug: msg=" value is  {{ app_name ~ ui_memory }} "
```
  
Also, if you want 128, then

```yaml
- debug: msg=" value is {{ vars[app_name ~ '_memory'] }}"
```

**Comment by Akasurde** [comment]
Hi @JoshuaSeidel !

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
