### ISSUE TITLE
ansible-pull uses directory+file path after chdir into directory

### ISSUE THREAD

**Issue by nyetsche** [ansible/ansible#3449]
When attempting to use ansible-pull, if I use a -d [directory] with a relative path, the command fails since it passes the relative path to ansible-playbook:

```
(hacking) vagrabuntu:~/ansible.git $ ~/ansible.git/bin/ansible-pull -U ~/ansible-work/ -d ansible-work-checkout -i hosts
Starting ansible-pull at 2013-07-05 16:51:36
Running: 'ansible all -c local -i "localhost," --limit "localhost:127.0.0.1" -m git -a "repo=/home/vagrant/ansible-work/ dest=ansible-work-checkout version=HEAD"'
localhost | success >> {
    "after": "9ee76f4",
    "before": "9ee76f4",
    "changed": false
}


Running: 'ansible-playbook -c local --limit "localhost:127.0.0.1" ansible-work-checkout/local.yml -i "hosts"'

ERROR: the playbook: ansible-work-checkout/local.yml could not be found
```

If I pass a full directory path, such as ~/ansible-work-checkout/local.yaml, it "works", but that's because ansible-playbook is now using a full path.

The problem seems to come from bin/ansible-pull:

```
145     cmd = 'ansible-playbook -c local --limit "%s" %s' % (limit_opts, playbook)
146     if options.inventory:
147         cmd += ' -i "%s"' % options.inventory
148     os.chdir(options.dest)
149     rc, out = _run(cmd)
```

As there's both the chdir(options.dest) and full path in the variable 'playbook'. 

Easiest solution would be to remove the os.chdir(options.dest). 

Better solution might be to trim the variable playbook with 'os.path.basename(playbook)'?

**Comment by mpdehaan** [comment]
cc @sfromm

**Comment by nyetsche** [comment]
Also, at least in my setup, I'd like to keep a local inventory file within that git checkout, so I think the better solution keep the chdir(), but make options.dest a full path earlier in the code:

```
115     if not options.dest:
116         parser.error("Missing required directory argument")
117         return 1
118
119     options.dest = os.path.abspath(options.dest)
120
121     if not options.url:
```

If this seems reasonable I can do a pull request.

**Comment by sfromm** [comment]
I think the os.chdir() should be kept.  Calling os.path.abspath() on options.dest seems like the best path forward.  @nyetsche if you want to submit the PR, go for it.  Otherwise, I have the file open and can easily submit the fix.

**Comment by nyetsche** [comment]
PR coming shortly, thanks.

**Comment by sfromm** [comment]
thanks @nyetsche :)

**Comment by nyetsche** [comment]
PR #3454
