### ISSUE TITLE
FR: Optional role dependencies / optionally execute role with task instead of at the beginning

### ISSUE THREAD

**Issue by danowar2k** [ansible/ansible#34566]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /home/vagrant/playbooks/playbook-moodle/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/home/vagrant/playbooks/playbook-moodle/ansible.cfg) = True
COLOR_VERBOSE(/home/vagrant/playbooks/playbook-moodle/ansible.cfg) = bright blue
DEFAULT_BECOME_METHOD(/home/vagrant/playbooks/playbook-moodle/ansible.cfg) = sudo
DEFAULT_HOST_LIST(/home/vagrant/playbooks/playbook-moodle/ansible.cfg) = [u'/home/vagrant/playbooks/playbook-moodle/inventory/debug_hosts.ini']
DEFAULT_STDOUT_CALLBACK(/home/vagrant/playbooks/playbook-moodle/ansible.cfg) = debug
DEFAULT_TIMEOUT(/home/vagrant/playbooks/playbook-moodle/ansible.cfg) = 30
DIFF_ALWAYS(/home/vagrant/playbooks/playbook-moodle/ansible.cfg) = True
PERSISTENT_CONNECT_TIMEOUT(/home/vagrant/playbooks/playbook-moodle/ansible.cfg) = 60
```
##### OS / ENVIRONMENT
N/A

##### SUMMARY
At the moment, an ansible role can define dependencies to other roles.
These roles are then executed before the role depending on them.

It would be nice if you could somehow mark a role as "will be executed manually later". This would allow optional dependencies. Then the role could decide if it needs to execute some other role based on some registered variable or something like it.

Of course the role can then be called with different parameters depending on other criteria.

Also interesting: Being able to define the other role's VCS somehow in the file, so you don't have to have the dependency in the playbook. (But this will be recorded in another issue)

##### STEPS TO REPRODUCE
**meta/main.yml**
```yaml
dependencies:
    - { 
   role: role-builder
   optional: true
}
```
##### EXPECTED RESULTS
N/A (Maybe multiple templates for tickets would be a good idea?)

##### ACTUAL RESULTS
N/A

**Comment by alikins** [comment]
Some related issues:
- https://github.com/ansible/ansible/issues/22169 -  Roles are ran multiple times if both referenced as dependency and from playbook
- https://github.com/ansible/ansible/issues/17661 - role dependency doesn't work as expected
- https://github.com/ansible/ansible/issues/13215 - Allow Excluding and/or overriding transitive role dependencies

**Comment by alikins** [comment]
cc'ing @bcoca @jimi-c

**Comment by rockandska** [comment]
Just had this conversation with bcoca / agaffney on irc.
it will be a huge improvement to have all the dependencies used by "include_role" automatically downloaded recursively by ansible-galaxy.
Without this possibility, each role who use "include_role" need to have a requirements.yml and force the user to launch a ansible-galaxy -r and could be really a pain for recursive dependencies.
Today we can't use role var with dependencies, to be able to use them with "include_role" will had this possibility too if i'm right.

Regards,

Edit: related to #16359 too

**Comment by bcoca** [comment]
@rockandska I'm not sure that is workable, see this example:

`- include_role: name={{hostvar}}` 

at this point you don't know which role you'll have until you execute the task.

**Comment by rockandska** [comment]
@bcoca not sure my explanations was clear, or maybe misunderstanded what you say, what i meant was:

if dependencies could be optional, we could benefit of the automatic (recursive ?) download of the dependencies present inside "meta/main.yml" with the ability to use them with "include_role".

dependencies in meta/main.yml have the benefits to be automatically (recursive ?) downloaded but can't see the variables from the role who calling them and can't be trigger when the user need them.

To resume, the ability to have the dependencies trigger later in the role will solve :

- automatic recursive download of ALL dependencies the role and his dependencies
- relay on only 1 file to manage the dependencies inside role ( today: requirements.yml and meta/main.yml but works differently)
- ability to use the dependencies with include_role and let the dependencies see the "master" role variables
- let the "master" role trigger the dependencies when it is require

Regards,

**Comment by bcoca** [comment]
dependencies are by nature 'non optional' you DEPEND on them, that is why every package manager fails if a dependency cannot be installed and most offer a 'recommended' or 'related' packages to optionally install, which seems to be what you want.

I'm for eliminating the current dependencies in meta/main.yml and create a requirements file that takes care of 'install, build and runtime' requirements, that way you can 'require/depend' on a role on install, but not during run time.

**Comment by cognifloyd** [comment]
I think we need a way to declare "role A needs role B. role A will run role B using import_role or include_role." So, it's more like a pip or galaxy requirements, but loaded (not run) by Ansible directly. If while loading, Ansible saw this kind of dependency, and it could not resolve the indicated role, it should fail.

**Comment by martinRibotDeBressac** [comment]
I have a role that requires another role as a dependancy, but this role is called multiple times during the play and is not called at the start or at the end.

This would be a nice adition to have for ansible-galaxy install while avoiding execution at the start of the include_role. :smiley:

**Comment by ssoerensen** [comment]
Is there any progress on this issue?

**Comment by bcoca** [comment]
Closing as this is possible now via `import_role` and `include_role`. For installing these roles you can add them to `meta/requirements.yml` .
