### ISSUE TITLE
ping library module uses inflexible shebang interpreter line

### ISSUE THREAD

**Issue by szaydel** [ansible/ansible#3459]
Because some systems do not have python at `/usr/bin/python`, the `shebang` line in the ping module should be modified from:

```
#!/usr/bin/python
```

to:

```
#!/usr/bin/env python
```

This is not a huge issue, but an inconvenience to be sure. Thanks!

**Comment by mpdehaan** [comment]
This is incorrect.

read all about ansible_python_interpeter in the docs for why this works the way it does, and how you can set it differently to manage multiple types of hosts at the same time.

**Comment by szaydel** [comment]
Thank you. I will be sure to follow the vars approach. Sorry for wasting time with this issue.
