### ISSUE TITLE
When ansible can't authenticate against a host, and your answer is no, ansible crash

### ISSUE THREAD

**Issue by cristobalrosa** [ansible/ansible#3466]
Hi guys, 

I've two hosts on my ansible configuration file. When I try to do a ping against them, and ansible can't authenticate with one of them, Ansible asks me a question:
Are you sure you want to continue connecting (yes/no)?

When my answer is 'no', ansible crashes:

/etc/ansible/hosts:
XXX.XXX.XXX
YYY.YYY.YYY

Steps to reproduce:

ansible all -m ping -u root

paramiko: The authenticity of host 'XXX.XXX.XXX.XXX' can't be established.
The ssh-rsa key fingerprint is zzzzzzzzzzzzzzzz
Are you sure you want to continue connecting (yes/no)?
no
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/**init**.py", line 70, in _executor_hook
    return_data = multiprocessing_runner._executor(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 378, in _executor
    self.callbacks.on_unreachable(host, msg)
  File "/usr/local/lib/python2.7/dist-packages/ansible/callbacks.py", line 357, in on_unreachable
    display("%s | FAILED => %s" % (host, res), stderr=True, color='red', runner=self.runner)
  File "/usr/local/lib/python2.7/dist-packages/ansible/callbacks.py", line 114, in display
    log_flock(runner)
  File "/usr/local/lib/python2.7/dist-packages/ansible/callbacks.py", line 83, in log_flock
    fcntl.lockf(LOG_LOCK, fcntl.LOCK_EX)
IOError: [Errno 35] Resource deadlock avoided
yyy.yyy.yyy | success >> {
    "changed": false,
    "ping": "pong"
}

Ansible has been installed using pip.

**Comment by mpdehaan** [comment]
Out of curiosity, What operating system are you running from?

**Comment by cristobalrosa** [comment]
Both are linux (Debian testing)

**Comment by mpdehaan** [comment]
Thanks.... looks like I need to make the log locking a little smarter.

Will fix this on 1.3.

**Comment by safabelkacem** [comment]
i have the same problem , please any idea for the solution ??

**Comment by mpdehaan** [comment]
fixed per above, so closing
