### ISSUE TITLE
Which method can judge the playbook is ended or failed or succeed in callback plugin

### ISSUE THREAD

**Issue by zhangchengshan** [ansible/ansible#34677]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
2.4.1
```

##### CONFIGURATION

```
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=4h -o ControlPath=/root/.ssh/sockets/%r@%h-%p -o Compression=yes -o StrictHostKeyChecking=no
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
CentOS 7.2
```

##### SUMMARY

When i use callback plugin to record log, i don't know which method can judge the playbook is ended or failed or succeed. Example, i can know the playbook is started on v2_playbook_on_start, but no method as v2_playbook_on_end tell me the playbook is ended. And i can get  the failed information on v2_runner_on_failed whenever the ignore_error is True or False, but i don't know whether the playbook is failed or succeed on v2_playbook_on_stat. So which method can help me to know the playbook status clearly, Thanks.

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by sivel** [comment]
You are correct that there is no `v2_playbook_on_end`, so you have to infer that the playbook has ended by either `v2_playbook_on_start` being called again, or by `v2_playbook_on_stats` being called.

As for determining failure, you will need to store the results from `v2_runner_on_failed`, or process the stats results in `v2_playbook_on_stats`.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
