### ISSUE TITLE
Monit module error

### ISSUE THREAD

**Issue by cristobalrosa** [ansible/ansible#3468]
I think monit module has issue. 

When the module cheks for the state, it's checking the 'Running' state with UpperCase meanwhile the monit summary gives you all the results in lower case:

Monit summary output:

<pre><code>
monit summary
The Monit daemon 5.1.1 uptime: 6m

Process 'nfsen'                     running
Process 'mongod'                    running
Process 'memcached'                 running
Process 'openvassd'                 running
</code></pre>

so the following line:

<pre><code>
running = 'Running' in out
</code></pre>

should be:

<pre><code>
running = 'Running'.lower() in out.lower()
</code></pre>

Thanks!

**Comment by mpdehaan** [comment]
How about sending in a pull request?

Thanks!

**Comment by cristobalrosa** [comment]
Pull request sent! #3471
