### ISSUE TITLE
Error trying to ping windows with winRM

### ISSUE THREAD

**Issue by gk95** [ansible/ansible#34692]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

winrm module

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/anaconda3/lib/python3.6/site-packages/ansible
  executable location = /opt/anaconda3/bin/ansible
  python version = 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) [GCC 7.2.0]

```

##### CONFIGURATION

No output for "ansible-config dump --only-changed" - so no changes to standard config
##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 6.5 
##### SUMMARY

I am trying to remotely ping a windows server using kerberos authentication. I can successfully run the OS level kerberos commands and get a TGT. I have also confirmed WinRM on the target host using curl successfully. So when I try to run the following command:

ansible windowssample -vvvvv -m win_ping

I get 

  File "/opt/anaconda3/lib/python3.6/site-packages/ansible/plugins/connection/winrm.py", line 320, in _connect
    self.protocol = self._winrm_connect()
  File "/opt/anaconda3/lib/python3.6/site-packages/ansible/plugins/connection/winrm.py", line 216, in _winrm_connect
    self._kerb_auth(self._winrm_user, self._winrm_pass)
  **File "/opt/anaconda3/lib/python3.6/site-packages/ansible/plugins/connection/winrm.py", line 193, in _kerb_auth
    stdout, stderr = p.communicate(password + b'\n')
TypeError: must be str, not **bytes****

10.241.37.108 | FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

##### STEPS TO REPRODUCE

Install anaconda distribution of Python
yum install OS dependencies
set up kerberos authentication and verify with kinit and klist
pip install ansible and dependencies
create /etc/ansible/hosts file
create /etc/ansible/group_vars/windowssample.yml 

Works successfully with linux hosts.
And finally if you run the commands for the windows host:
ansible windowssample -vvvvv -m win_ping

I get the following:
10.241.37.108 | FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

```yaml

No playbooks used
```

##### EXPECTED RESULTS

A success message
##### ACTUAL RESULTS

```
ansible 2.4.2.0
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/anaconda3/lib/python3.6/site-packages/ansible
  executable location = /opt/anaconda3/bin/ansible
  python version = 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) [GCC 7.2.0]
No config file found; using defaults
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /opt/anaconda3/lib/python3.6/site-packages/ansible/plugins/callback/__init__.py
META: ran handlers
Using module file /opt/anaconda3/lib/python3.6/site-packages/ansible/modules/windows/win_ping.ps1
<10.241.37.108> ESTABLISH WINRM CONNECTION FOR USER: user@company.com on PORT 5986 TO 10.241.37.108
creating Kerberos CC at /tmp/tmpy3qsvs0f
calling kinit for principal user@company.com
The full traceback is:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 130, in run
    res = self._execute()
  File "/opt/anaconda3/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 528, in _execute
    result = self._handler.run(task_vars=variables)
  File "/opt/anaconda3/lib/python3.6/site-packages/ansible/plugins/action/normal.py", line 45, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars, wrap_async=wrap_async))
  File "/opt/anaconda3/lib/python3.6/site-packages/ansible/plugins/action/__init__.py", line 740, in _execute_module
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
  File "/opt/anaconda3/lib/python3.6/site-packages/ansible/plugins/action/__init__.py", line 889, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/opt/anaconda3/lib/python3.6/site-packages/ansible/plugins/connection/winrm.py", line 347, in exec_command
    super(Connection, self).exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/opt/anaconda3/lib/python3.6/site-packages/ansible/plugins/connection/__init__.py", line 52, in wrapped
    self._connect()
  File "/opt/anaconda3/lib/python3.6/site-packages/ansible/plugins/connection/winrm.py", line 320, in _connect
    self.protocol = self._winrm_connect()
  File "/opt/anaconda3/lib/python3.6/site-packages/ansible/plugins/connection/winrm.py", line 216, in _winrm_connect
    self._kerb_auth(self._winrm_user, self._winrm_pass)
  File "/opt/anaconda3/lib/python3.6/site-packages/ansible/plugins/connection/winrm.py", line 193, in _kerb_auth
    stdout, stderr = p.communicate(password + b'\n')
TypeError: must be str, not bytes

10.241.37.108 | FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

**Comment by gk95** [comment]
I managed to resolve the issue by the following steps:
1. Use knit command to create TGT
2. Blank the password field in windows.yml file
This results in a successful run. Is there any requirement that I have to encrypt the windows.yml file if I specify the password in there?

**Comment by jhawkesworth** [comment]
@gk95 the winrm connection plugin in 2.4.2 doesn't work with python 3.x unfortunately due an api change in subprocess 

I believe this is fixed in latest devel although I can't check at the moment.

You can hack it like this if you don't mind it only working on python 3:

```
diff --git a/lib/ansible/plugins/connection/winrm.py b/lib/ansible/plugins/connection/winrm.py
index ccf0a96..f79059d 100644
--- a/lib/ansible/plugins/connection/winrm.py
+++ b/lib/ansible/plugins/connection/winrm.py
@@ -190,7 +190,7 @@ class Connection(ConnectionBase):
         p = subprocess.Popen(kinit_cmdline, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, e

         # TODO: unicode/py3
-        stdout, stderr = p.communicate(password + b'\n')
+        stdout, stderr = p.communicate(bytes(password + '\n', 'utf-8'))

         if p.returncode != 0:
             raise AnsibleConnectionFailure("Kerberos auth failure: %s" % stderr.strip())
(END)
```

**Comment by gk95** [comment]
I made that change in the code and it worked a treat. Brilliant, thanks!
