### ISSUE TITLE
ansible thinks redis is managed with chkconfig when it's systemd (Fedora19)

### ISSUE THREAD

**Issue by teburd** [ansible/ansible#3474]
Currently on Fedora 19 I have both chkconfig and systemctl. The native init is systemd. Ansible chooses chkconfig however.

As an example here is me attempting to test out the service module for redis

```
[vagrant@localhost ansible]$ hacking/test-module -m "library/system/service" -a "name=redis enabled=yes state=started"
* including generated source, if any, saving to: /home/vagrant/.ansible_module_generated
* this will offset any line numbers in tracebacks/debuggers!
***********************************
RAW OUTPUT
{"msg": "unknown service name", "failed": true}


***********************************
PARSED OUTPUT
{
    "failed": true, 
    "msg": "unknown service name"
}
[vagrant@localhost ansible]$ systemctl status redis
redis.service - A persistent key-value database
   Loaded: loaded (/usr/lib/systemd/system/redis.service; disabled)
   Active: inactive (dead)
```

The "unknown service name" message is only done for trying to enable a chkconfig service.

**Comment by mpdehaan** [comment]
This is probably because it finds the chkconfig script which might should not be present.

We can change the ordering though.

**Comment by teburd** [comment]
Well fedora has some backwards compatibility thing with the older sysvinit scripts. In some cases the service may very well be a sysvinit script which chkconfig should be used for. Its almost guaranteed RHEL 7 will work the same way.

**Comment by mpdehaan** [comment]
Right and in that case I would _suspect_ it to work, so perhaps it goes a bit deeper...
