### ISSUE TITLE
shell vars used in ansible.cfg as shown in example cfg are not expanded

### ISSUE THREAD

**Issue by pieska** [ansible/ansible#3475]
according to the example ansible.cfg i could use $HOME in path names but it didn't work because ansible does not expand env vars.
i fixed it by the mini patch (sorry no pull request, my fork is borken):

diff --git a/lib/ansible/constants.py b/lib/ansible/constants.py
index 0d1e27c..ee41d24 100644
--- a/lib/ansible/constants.py
+++ b/lib/ansible/constants.py
@@ -70,7 +70,7 @@ def shell_expand_path(path):
     ''' shell_expand_path is needed as os.path.expanduser does not work
         when path is None, which is the default for ANSIBLE_PRIVATE_KEY_FILE '''
     if path:
-        path = os.path.expanduser(path)
- ```
     path = os.path.expandvars(os.path.expanduser(path))
  ```
  
   return path
  
  p = load_config_file()

**Comment by mpdehaan** [comment]
Can you please share where you expect $HOME to be expanded with a playbook example?  (never mind this, I expect you mean you want to use $HOME in ansible.cfg values?)

Also if you would like to send in a patch, please send in a github pull request versus pasting in the ticket.

Thanks!

**Comment by pieska** [comment]
yes, i want to use $HOME in ansible.cfg. funny thing is, the example config already uses $HOME for remote_tmp ;-)

**Comment by jimi-c** [comment]
Closing, as the above PR was merged in. Thanks!
