### ISSUE TITLE
with_lines fires before when

### ISSUE THREAD

**Issue by ScottSturdivant** [ansible/ansible#3491]
Trying to skip a task that uses the with_lines lookup plugin if the specified file does not exist.  Discovered that 'when' doesn't execute until after the with_lines lookup, so it cannot be skipped but instead fails.

Sample playbook:

```

---
- hosts: localhost
  tasks:
    - action: debug msg={{ foo }}
      when: foo is defined
      with_lines:
        - cat /this/doesnt/exist
```

Output:

```
PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [debug msg={{foo}}] ***************************************************** 
cat: /this/doesnt/exist: No such file or directory
fatal: [localhost] => lookup_plugin.lines(cat /this/doesnt/exist) returned 1

FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
Right, the when is not executed on each line of the iteration, but it is
true the iteration is computed early.

We should investigate and change this if this is in fact the case (which it
seems to be).

**Comment by ScottSturdivant** [comment]
It had actually never occurred to me that the 'when' would apply to each item being iterated.  I do however now see that in the docs and it does make sense.  So perhaps this is working as designed and there's another way to skip the task?

**Comment by bcoca** [comment]
a file exists filter or plugin? I would like this took

when: foo is defined and '/this/doesnt/exist' is file

**Comment by srgvg** [comment]
As  the conditional is applied to every item, the iteration is and should be calculated early. With other plugins, one can now do stuff like `when: item.name is defined`, where the conditional depends on the iteration items.

I'm not sure what @mpdehaan means by "the when is not executed on each line of the iteration", was that a typo? And what should we exactly change?

**Comment by mpdehaan** [comment]
Yes, the conditional does need to be evaluated per item.

I was confused in the earlier comment, so closing this one.
