### ISSUE TITLE
cron module throws exceptions when using the cron_file= option

### ISSUE THREAD

**Issue by jeks313** [ansible/ansible#3495]
Few issues with the code in library/system/cron
1. It's using NamedTemporaryFile that auto deletes the temp file after you're done, but install_job moves the temporary file into /etc/cron.d, throws an exception when module exits.
2. install_job does not return a tuple when cron_file= is in use throwing an exception
3. The jobs are enumerated for logging after the temporary file has been moved using cron_file= leading to another exception.

Example changes that would fix all three issues.
1. add delete=False to the NamedTemporaryFile so it doesn't try and clean up automagically.
2. return 0, None, None as the result in install_job when cron_file= is used <-- probably not a great idea, as it should check the return code of the module.atomic_move
3. Move the enumeration of the jobs for logging above where the file is moved, thus making it available at that time.

---

```
diff --git a/library/system/cron b/library/system/cron
index 633bccb..f5ef809 100644
--- a/library/system/cron
+++ b/library/system/cron
@@ -153,6 +153,7 @@ def install_jobs(module, user, tmpfile, cron_file):
     if cron_file:
         cron_file = '/etc/cron.d/%s' % cron_file
         module.atomic_move(tmpfile, cron_file)
+        return 0, None, None
     else:
         cmd = "crontab %s %s" % (user, tmpfile)
         return module.run_command(cmd)
@@ -311,7 +312,7 @@ def main():
     if job is None and do_install:
         module.fail_json(msg="You must specify 'job' to install a new cron job")

-    tmpfile = tempfile.NamedTemporaryFile()
+    tmpfile = tempfile.NamedTemporaryFile(delete=False)
     (rc, out, err) = get_jobs_file(module,user,tmpfile.name, cron_file)

     if rc != 0 and rc != 1: # 1 can mean that there are no jobs.
@@ -343,6 +344,12 @@ def main():
             os.unlink(backupfile)
             module.exit_json(changed=changed,cron_file=cron_file,state=state)

+    # get the list of jobs in file
+    jobnames = []
+    for j in get_jobs(tmpfile.name):
+        jobnames.append(j[0])
+    tmpfile.close()
+
     if changed:
         # If the file is empty - remove it
         if rm and cron_file:
@@ -354,12 +361,6 @@ def main():
             if (rc != 0):
                 module.fail_json(msg=err)

-    # get the list of jobs in file
-    jobnames = []
-    for j in get_jobs(tmpfile.name):
-        jobnames.append(j[0])
-    tmpfile.close()
-
     if not backup:
         os.unlink(backupfile)
         module.exit_json(changed=changed,jobs=jobnames)
```

**Comment by dirtyharrycallahan** [comment]
I submitted a pull request a few days ago that should fix this problem and others.

**Comment by mpdehaan** [comment]
Yep, in queue for testing!

**Comment by mpdehaan** [comment]
should be fixed per @dirtyharrycallahan 's recent patches, let me know if these work for you on devel.

Thanks!
