### ISSUE TITLE
Host specifiers should be sorted

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#3500]
This is rather minor, but to ensure consistent behavior, hosts should look like this:

hosts: webservers:&boston:!rack42

So when applying the host selectors, run those without the "&" first, then the &s, then the !s.

**Comment by srgvg** [comment]
I gave this a shot, not 100% sure how the 'all' default is expected to work. 
Now you can do something like  `ansible "!production" -m shell -a reboot`
