### ISSUE TITLE
ANSIBLE_KEEP_REMOTE_FILES=True should be equivalent to =1

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#3507]
something is not being casted right as =True does not work, but =1 does.

**Comment by bcoca** [comment]
how about changing to 'set', default None and test against None? 

IIRC, its how nocows works

nvmd, just saw mk_boolean

**Comment by mpdehaan** [comment]
why would anyone disable the cows?   That's udderly ridiculous.
