### ISSUE TITLE
Source file location issue with spaces in path on mac and using -c ssh and SFTP (default)

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#3509]
User has home dir of /Volumes/Macintosh HD/UsersHD/name

and is using the copy module to move a file from there

for some reason SFTP in connection plugin is NOT returning an error code but is not moving the file on his computer (OS X).

In this case, figure out why an error does not come up, or pipes.quote the original path (probably what is needed).

Reproduce and submit fix.

**Comment by mpdehaan** [comment]
workarounds include:

use scp in ansible.cfg instead

include a relative path explicitly off of ~/ to avoid the space in the src

**Comment by binduwavell** [comment]
FWIW my home directory is /Users/name. I have a symlink in my home directory for a folder called projects that is on /Volumes/Macintosh HD/UsersHD/name/projects. I have my ansible setup in a folder under projects.

**Comment by binduwavell** [comment]
Adding a note I already sent to IRC. Issue does not appear to have anything to do with symlinks has to do with there being a space in the path as you suspected. I confirmed with several tests producing both success and failures.

**Comment by mpdehaan** [comment]
I've pushed some changes in 4196615 ... let me know if this works for you, and if not, I can reopen.

Should be good to go.

Thanks!
