### ISSUE TITLE
Add 2.5 porting guide notes about include_role and inherited attributes

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#35096]
##### ISSUE TYPE
 - Documentation Report

##### ANSIBLE VERSION

```
2.5
```

##### CONFIGURATION
N/A
##### OS / ENVIRONMENT
N/A
##### SUMMARY
In 2.5 we resolved a bug in `include_*` to meet our expectations that attributes applied to `include_*` should not be inherited by the included tasks.  That functionality is reserved for `import_*`

We need to document this change in the 2.5 porting guide.

ref #35065 

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by grassyknolling** [comment]
This looks related to #34974 "inconsistent documentation for tags on dynamic-include tasks"

**Comment by sivel** [comment]
@grassyknolling I will see what I can do in regards to existing documentation inconsistencies as well.
