### ISSUE TITLE
Output SSH username for requested SSH password

### ISSUE THREAD

**Issue by matthiasbalke** [ansible/ansible#35174]
Ansible should output the SSH username it is requesting an SSH passwort for.

##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.2.0
  config file = /mnt/c/XX/YYY/ZZZZ/ansible.cfg
  configured module search path = [u'/home/balke/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]
```

##### CONFIGURATION

```
DEFAULT_ASK_PASS(/mnt/c/XX/YYY/ZZZZ/ansible.cfg) = True
DEFAULT_HOST_LIST(/mnt/c/XX/YYY/ZZZZ/ansible.cfg) = [u'/mnt/c/XX/YYY/ZZZZ/hosts']
```

##### OS / ENVIRONMENT

Windows 10 (1607)
Ubuntu Bash for Windows 
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

##### SUMMARY

Ansible should output the SSH username it is requesting an SSH passwort for.

When using Ansible in different projects, it is not always obvious if the default username or a predefined username gets used. This is very confusing, especially for beginners. In my opinion it would be good, if Ansible prints the username it uses like most ssh clients do (example see below).

##### STEPS TO REPRODUCE

```
$ ansible-playbook site.yml --check --diff
```

##### EXPECTED RESULTS

```
Using username "balke".
SSH password:
```

##### ACTUAL RESULTS

```
SSH password:
```

**Comment by sivel** [comment]
Unfortunately I cannot see a reasonable way for this to work reliably.  In fact, I think it could make things more confusing if we were to do this.

Think of the example where you have supplied `-u` on the command line, but specified a different `ansible_user` in `group_vars/all`.  Or supplied various `ansible_user` values.  We would be indicating the value from `-u` but never using that during connections.

By the time that the message has been displayed, there is no reliable way to tell if the user you are connecting with is supplied in vars or playbooks by that point.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
