### ISSUE TITLE
setup module crash on unavailable mounts

### ISSUE THREAD

**Issue by pfalcon** [ansible/ansible#3520]
Here I'm sitting on Samsung (ARM CPU) Chromebook, with Ubuntu running in chroot using crouton (https://github.com/dnschneid/crouton). Using chroot means that not all mount points are available inside, df for example starts with:

$ df
df: `/mnt/stateful_partition': No such file or directory

And just the first command I ran with ansible (master branch) crashes on that:

$ ansible -m setup -i hosts localhost -c local
localhost | FAILED >> {
    "failed": true, 
    "msg": "Traceback (most recent call last):\n  File \"/home/pfalcon/.ansible/tmp/ansible-1373731679.78-82911260348706/setup\", line 3051, in <module>\n    main()\n  File \"/home/pfalcon/.ansible/tmp/ansible-1373731679.78-82911260348706/setup\", line 2135, in main\n    data = run_setup(module)\n  File \"/home/pfalcon/.ansible/tmp/ansible-1373731679.78-82911260348706/setup\", line 2073, in run_setup\n    facts = ansible_facts()\n  File \"/home/pfalcon/.ansible/tmp/ansible-1373731679.78-82911260348706/setup\", line 2063, in ansible_facts\n    facts.update(Hardware().populate())\n  File \"/home/pfalcon/.ansible/tmp/ansible-1373731679.78-82911260348706/setup\", line 505, in populate\n    self.get_mount_facts()\n  File \"/home/pfalcon/.ansible/tmp/ansible-1373731679.78-82911260348706/setup\", line 629, in get_mount_facts\n    statvfs_result = os.statvfs(fields[1])\nOSError: [Errno 2] No such file or directory: '/mnt/stateful_partition'\n", 
    "parsed": false
}

**Comment by mpdehaan** [comment]
Editing this down to the actual error reported, if you have more, please file them!

**Comment by mpdehaan** [comment]
what is ansible --version ?

**Comment by pfalcon** [comment]
ansible 1.3 (devel fba1f7ef42) last updated 2013/07/12 13:51:06 (GMT +200)

**Comment by mpdehaan** [comment]
Thanks!

**Comment by mpdehaan** [comment]
This is fixed in Ansible 1.3 so I can close this ticket.

Thanks!
