### ISSUE TITLE
Move module_utils to top level name (lib/ansible/module_utils -> lib/ansible_module_utils and )

### ISSUE THREAD

**Issue by alikins** [ansible/ansible#35237]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.5.0 (devel ffe0ddea96) last updated 2018/01/22 17:14:12 (GMT -400)
  config file = None
  configured module search path = [u'/home/adrian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible
  python version = 2.7.14 (default, Jan 17 2018, 14:28:32) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]

```

##### SUMMARY

At some point in the future...

Move module_utils to it's own top level dir.

ansible.module_utils.basic -> ansible_module_utils.basic

###### why?

module_utils is the runtime for modules and to some degree, the module SDK.

* code in module_utils/* can't and shouldn't use code from the ansible app (lib/ansible/playbook for ex)
* code in ansible.{everything except module_utils and modules}* is (mostly) GPL, while code in module_utils and modules is an assorted mix
* arguably, code in app shouldn't be using code in module_utils directly
* clearer distinction between app code and module/remote code
* breaks a coupling between app code and module_util code
* opens a path to supporting multiple implementations of module_utils 
   * versioned impls
   * arch specific impls
      * the python impl could include compiled libs (aka, 'C modules')
      * for arch specific runtimes (Go, etc)

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by sivel** [comment]
> arguably, code in app shouldn't be using code in module_utils directly

We have previously decided that this is acceptable.  To change this would require some other 3rd directory that both modules and core could use, and I'm not sure that is worth it.

**Comment by samdoran** [comment]
We have no plans to implement this feature at this time.

To discuss this further, please reach out on IRC or the mailing list:

   * IRC: #ansible-devel on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel
