### ISSUE TITLE
Empty groups trip "could not match supplied host pattern" warning

### ISSUE THREAD

**Issue by dekimsey** [ansible/ansible#35255]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /root/ansible/ansible.cfg
  configured module search path = [u'/root/ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY

The new 2.4 [warning](https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/manager.py#L545) on misspelled groups is quite noisy. There is no distinction made between an empty group and a misspelled one. Having ansible generate a warning about them on every run is not helpful and confuses our users. They are defined, and they are defined to be empty.

##### STEPS TO REPRODUCE

Any empty group used as a host pattern in a playbook.

```
- name: Tier 3 (Re)start NG applications
  hosts: ng-app-tier-3
  roles: [ng-app-instance-condrestart]

- name: Tier 4 (Re)start NG applications
  hosts: ng-app-tier-4
  roles: [ng-app-instance-condrestart]

- name: Tier 5 (Re)start NG applications
  hosts: ng-app-tier-5
  roles: [ng-app-instance-condrestart]
```

##### EXPECTED RESULTS

No warnings emitted for defined but empty groups.

##### ACTUAL RESULTS

```
$ ansible-playbook site-ng.yml --list-hosts
 [WARNING]: Could not match supplied host pattern, ignoring: ng-app-tier-3

 [WARNING]: Could not match supplied host pattern, ignoring: ng-app-tier-6

 [WARNING]: Could not match supplied host pattern, ignoring: ng-app-tier-7

  play #17 (ng-app-tier-3): Tier 3 (Re)start NG applications	TAGS: []
    pattern: [u'ng-app-tier-3']
    hosts (0):

  play #18 (ng-app-tier-4): Tier 4 (Re)start NG applications	TAGS: []
    pattern: [u'ng-app-tier-4']
    hosts (12):
      ...snip

  play #19 (ng-app-tier-5): Tier 5 (Re)start NG applications	TAGS: []
    pattern: [u'ng-app-tier-5']
    hosts (98):
      ...snip

  play #20 (ng-app-tier-6): Tier 6 (Re)start NG applications	TAGS: []
    pattern: [u'ng-app-tier-6']
    hosts (0):

  play #21 (ng-app-tier-7): Tier 7 (Re)start NG applications	TAGS: []
    pattern: [u'ng-app-tier-7']
    hosts (0):
```

**Comment by dekimsey** [comment]
For what it's worth, I think the misspell detection is good. We've had that happen to us. But we definitely have groups that are empty in one inventory and not another (for instance our blue/green stacks are not fully fleshed out in pre-production environments).

I don't have any good suggestions to addressing this. Maybe a play level `empty_pattern_okay` flag? I dunno.

**Comment by ssbarnea** [comment]
Also raised at https://github.com/ansible/ansible/issues/36306

**Comment by alexander-bauer** [comment]
I'm also hit by this. I'm using a `group_by` play to split hosts between a `foreman_managed` and `foreman_unmanaged` group. When I limit my play to *just* hosts that aren't managed by Foreman, I see this error.

```
# site.yml
- hosts: all
  tasks:
    - name: Assign foreman_managed / foreman_unmanaged groups
      group_by:
        key: foreman_{{ 'managed' if foreman is defined and foreman['managed'] else 'unmanaged' }}

- hosts: foreman_managed
  roles:
    - foreman_managed
```

For a host that winds up in `foreman_unmanaged`, I see the following output.

```
$ awx-cli job launch -J 'Apply Site' --limit abauer.desk --monitor
------Starting Standard Out Stream------
Identity added: /tmp/awx_980_Ry8OcM/credential_4 (/tmp/awx_980_Ry8OcM/credential_4)
SSH password:
SUDO password[defaults to SSH password]:

PLAY [all] *********************************************************************


TASK [Gathering Facts] *********************************************************
ok: [abauer.desk]

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [abauer.desk]

TASK [Assign foreman_managed / foreman_unmanaged groups] ***********************
ok: [abauer.desk]
 [WARNING]: Could not match supplied host pattern, ignoring: foreman_managed


PLAY [foreman_managed] *********************************************************
skipping: no hosts matched
```

So long as there's at least one host that goes to `foreman_managed`, this warning doesn't appear.

I hope there comes to be an elegant way to avoid this, though none come easily to mind. Obviously it's not easy to walk all of the logic routes to try and generate the empty groups for all possible outcomes in the inventory. Maybe a way to suppress the warnings for particular groups or for particular plays is the best that can be done.

**Comment by pjnagel** [comment]
I'm also in favor of the option to silence this warning.

I have a single playbook with multiple plays that are intended to import the correct role depending on which group a host is in. So it is normal behaviour for only 1 out of 3 of the plays to match hosts.

I structured the playbook this way because if I have one play that conditionally imports the roles, then I either trip over #31751 or #18594

**Comment by sudoforge** [comment]
I'm building [Archer](https://github.com/bddenhartog/archer), a playbook for managing Arch Linux installations. The intended default target is simply `localhost`, and the intended use is running the playbook via `ansible-pull`.

My `/etc/ansible/hosts` file exists and has just one line:

```
localhost ansible_connection=local
```

And my playbook is pretty simple:

```
- hosts: localhost
  roles:
    - { role: foo, tags: ['foo'] }
```

My **`/etc/hosts`** has two hostnames set up for my local machine:

```
127.0.0.1 my-hostname my-hostname.localdomain
```

And I see the following output when running the playbook via `ansible-pull`:

```
/usr/bin/ansible-pull -U https://github.com/sudoforge/archer
 [WARNING]: Could not match supplied host pattern, ignoring: my-hostname.localdomain
 [WARNING]: Could not match supplied host pattern, ignoring: my-hostname
localhost | SUCCESS => {
    "after": "...",
    "before": "...",
    "changed": false,
    "remote_url_changed": false
}
 [WARNING]: Could not match supplied host pattern, ignoring: my-hostname.localdomain
 [WARNING]: Could not match supplied host pattern, ignoring: my-hostname
```

The playbook then proceeds to run. This is, in my opinion, overly verbose and unecessary. Additionally, I'm not sure why `ansible-pull` is reading entries from my `/etc/hosts` file -- is this behavior documented somewhere other than the main docs page for `ansible-pull`?

**Comment by jhgorrell** [comment]
When running with a dynamically generated host list, some of the groups are empty which is ok.  Would be nice to have a way to suppress the empty groups warning, so real warnings stood out.

**Comment by ssbarnea** [comment]
While the proposed patch would address most of the issue there is still one case which is not covered: groups that do not exist. Currently there is no way to convince ansible to run some tasks against a group if this group exists.

Here is the workaround which is a bit inconvenient because `add_host` **is not able to add an empty group**, we are forced to add an empty one directly inside the inventory, so we can use it as fallback

**inventory file**
```
[empty]
```

**your playbook**
```
- hosts: "{{ xxx | default('empty') }}"
```

I would have preferred not to have to hack the inventory which can be stored in many ways, or be dynamic. Maybe Ansible should have an implicit empty group that can be used for this purpose (maybe `_empty`)

**Comment by sudoforge** [comment]
> While the proposed patch would address most of the issue there is still one case which is not covered: groups that do not exist.

Good catch, albiet a little late. In fact, it looks like this was merged before the author submitted another commit that the reviewer and author agreed upon.

Are there plans to address this, @agaffney?

**Comment by agaffney** [comment]
I'm fairly sure that the entire point of the warning is to let the user know when they've used a group that doesn't exist, presumably to help catch misspellings. It was likely an unintended side effect that it also showed on empty groups, which my PR addressed.

**Comment by ssbarnea** [comment]
@agaffney Here is the question I have: we have code here that is cleaning up (deprovision) hosts from various groups, and obviously that is perfectly normal for these groups not to defined in nothing was provisioned.

So a real challenge: **How to run some tasks if a group exists or do nothing if it doesn't exist, without displaying any warning messages?**

PS. Adding an 'empty' group gets out of question because combination of bugs that makes it unusable (add_module being unable to add empty groups and inventory sources can of too many formats, dynamic, ....).

**Comment by agaffney** [comment]
That's should be a separate issue, really. This issue was specifically for the warning being triggered on empty groups, which was addressed by my PR.

**Comment by ssbarnea** [comment]
@agaffney I never said we should reopen this bug. I did  great job solving it, thanks! This is why I raised #40030 so we can continue there. At this moment I have no idea what it would be the right way to address it.
