### ISSUE TITLE
azure_rm_mysqldatabase integration test fails

### ISSUE THREAD

**Issue by mattclay** [ansible/ansible#35308]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

azure_rm_mysqldatabase

##### ANSIBLE VERSION

```
ansible 2.5.0 (devel 8ea0bfe9a3) last updated 2018/01/24 10:27:23 (GMT -700)
  config file = None
  configured module search path = [u'/Users/mclay/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mclay/code/mattclay/ansible/lib/ansible
  executable location = /Users/mclay/code/mattclay/ansible/bin/ansible
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Shippable

##### SUMMARY

The `azure_rm_mysqldatabase` integration test fails and has been [disabled](https://github.com/ansible/ansible/commit/ebe925405c9b450488e42f46e3c009868a22dc76) in CI.

CI failure: https://app.shippable.com/github/ansible/ansible/runs/52072/53/tests

The error is `failure: Error creating the MySQL Server instance: Azure Error: StorageMbTooLow Message: The storage size of 2048 MB does not meet the minimum required storage of 51200 MB.`

##### STEPS TO REPRODUCE

Run the `azure_rm_mysqldatabase` on Shippable or locally with `ansible-test`:

`ansible-test integration azure_rm_mysqldatabase --docker -v`

##### EXPECTED RESULTS

Tests pass.

##### ACTUAL RESULTS

Tests fail.

**Comment by mattclay** [comment]
I've also [disabled](https://github.com/ansible/ansible/commit/bbedb9aac458915989a5f0e930dc3cbb4decdbda) the `azure_rm_mysqlserver` test as it was failing with the same error:

https://app.shippable.com/github/ansible/ansible/runs/52118/53/tests

**Comment by mattclay** [comment]
I've also [disabled](https://github.com/ansible/ansible/commit/e9e85625aa08fe38dbfbbd52e2c98efc709c25f5) the failing `azure_rm_postgresqlserver` and `azure_rm_postgresqldatabase` tests:

https://app.shippable.com/github/ansible/ansible/runs/52126/53/tests

**Comment by zikalino** [comment]
@mattclay i will fix this asap, seems like some additional check was added in MySQL and PostgreSQL service.

**Comment by rcaron** [comment]
We ran into this issue, too. My suggestion to try for now (pending a more concrete resolution) is to make an explicit declaration of 51200 in the JSON for storageMB in properties. Even though it’s marked as not required, there may be some issue with that.

[https://docs.microsoft.com/en-us/azure/templates/microsoft.dbformysql/servers](https://docs.microsoft.com/en-us/azure/templates/microsoft.dbformysql/servers)
