### ISSUE TITLE
Add support for launching EC2 instances with IAM roles attached

### ISSUE THREAD

**Issue by boosh** [ansible/ansible#3532]
Would be great if EC2 instances could be launched with IAM roles attached. In boto terms, this just means adding support for passing the `instance_profile_name` parameter to `ec2.run_instances()`.

**Comment by lwade** [comment]
Your wish is Ansible's command!  ;)   Please give it a test.

**Comment by boosh** [comment]
Thanks! I'll give it a whirl :-)

**Comment by boosh** [comment]
I can launch with an instance profile, but the returned JSON doesn't include the profile name. I'm new to ansible so not sure if it should do or not. 

Anyway, thanks!

**Comment by felibb** [comment]
@boosh @lwade has the ec2_instance_profile not showing up ever been resolved? I can see this bit (with empty value) for all instances that are not launched with roles, but I cannot see it for the single instance that is actually using an IAM role.

**Comment by boosh** [comment]
@felibb I'm not sure. I haven't had to use this in a while.
