### ISSUE TITLE
parse YAML before asking for sudo? 

### ISSUE THREAD

**Issue by agshekeloh** [ansible/ansible#3535]
It would be really nice if ansible would parse the playbook YAML
before requesting the sudo password.

I'm just learning YAML, and rely on ansible to tell me I'm wrong. I'm
frequently wrong.

Our company's ansible account has a tedious and annoying sudo
password. (It's not security through obscurity, it's security through
"I can't even type the damn thing.")

From a user perspective, this seems like an easy change to make. Any
chance your could add this to ansible, even as an option in
ansible.cfg or something?

(filed per mpdehaan's request on mailing list)

**Comment by mpdehaan** [comment]
We've suggested running some various levels of playbook and YAML error scanning prior to running ansible, so I think that (a more general purpose solution) would apply well here and also be useful for other things.

We have discussed also detecting common YAML errors and duplicate hash keys in hashes, etc, as part of ansible's normal file loading routine.

**Comment by mpdehaan** [comment]
This is #3424 so I am going to link these tickets and close this one.
