### ISSUE TITLE
"AnsibleError: template error while templating string: no filter named 'http2'

### ISSUE THREAD

**Issue by arun8796** [ansible/ansible#35420]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### SUMMARY
trying to create nginx role and ended up with this error

"AnsibleError: template error while templating string: no filter named 'http2'

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by Akasurde** [comment]
@sakthiom2014 Thanks for reporting this issue. Could you please provide playbook that producing this error and `-vvvv` output ?

needs_info

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
