### ISSUE TITLE
Windows User cannot checkout devel from github because of ":" as a filename

### ISSUE THREAD

**Issue by daBONDi** [ansible/ansible#35422]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Gitrepo itself
/test/units/modules/network/dellos10/fixtures/show_processes_node-id_1__grep_Mem:   <-- there is a : in filename

##### ANSIBLE VERSION
devel

##### CONFIGURATION
Nothing want to fetch devel

##### OS / ENVIRONMENT
Windows 10

##### SUMMARY
```
Cloning into 'ansible'...
remote: Counting objects: 293213, done.
remote: Compressing objects: 100% (31/31), done.
Rremote: Total 293213 (delta 15), reused 21 (delta 12), pack-reused 293169
Receiving objects: 100% (293213/293213), 100.03 MiB | 3.16 MiB/s, done.
Resolving deltas: 100% (185945/185945), done.
error: unable to create file test/units/modules/network/dellos10/fixtures/show_processes_node-id_1__grep_Mem:: Invalid argument
Checking out files: 100% (8295/8295), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
```

##### STEPS TO REPRODUCE
Clone devel on Windows Systems

##### EXPECTED RESULTS
Ansible/devel should be cloneable on windows for development :-(

##### ACTUAL RESULTS
Cannot clone repo :-)
```

```

**Comment by daBONDi** [comment]
Follow Comit is the problem https://github.com/ansible/ansible/commit/2f46f8f9447a510a20d26321388ad75d3c831bc8

Thanks for fixing it, i know windows ppl are anoying :-)

**Comment by jhawkesworth** [comment]
I am not able to test it, but I made a pull request to rename the file #35423 

@skg-net @gundalow - please can you check and see if its ok to remove the : from the filename - if so please merge #35423 **Edit** please use jborean93's PR below - mine didn't fix the problem.

**Comment by jborean93** [comment]
Fix added with https://github.com/ansible/ansible/pull/35430, waiting on network people's approval. One thing I want to add to the tests is a checkout on Windows to try and avoid this from happening in the future. Unfortunately this won't be an easy thing to do.
