### ISSUE TITLE
stat module follows symlinks

### ISSUE THREAD

**Issue by sfromm** [ansible/ansible#3543]
As it is now, the stat module follow symlinks instead of returning stat information of the link itself.  For example, /etc/localtime is a symlink but stat reports (abbreviated output below):

$ hacking/test-module -m library/files/stat -a 'path=/etc/localtime'

---

PARSED OUTPUT
{
    "changed": false, 
    "stat": {

```
    "isblk": false, 
    "ischr": false, 
    "isdir": false, 
    "isfifo": false, 
    "isgid": false, 
    "islnk": false, 
    "isreg": true, 
    "issock": false, 
    "isuid": false, 
```

Fixing the call from `os.stat` to `os.lstat` fixes the stat module so that it properly reports that the file is a symlink (note that islnk is now true):

```
    "isblk": false, 
    "ischr": false, 
    "isdir": false, 
    "isfifo": false, 
    "isgid": false, 
    "islnk": true, 
    "isreg": false, 
    "issock": false, 
    "isuid": false, 
```

I'm happy to submit a PR to fix the stat module, but wasn't sure if the module should accept an option to follow symlinks if so desired.  I think the default should be to _not_ follow links, but am happy to implement either way.

**Comment by bcoca** [comment]
since it already follows the symlinks the 'backwards compatible' option
would be "follow: yes (default) | no"

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by sfromm** [comment]
@bcoca Looks like the module was added in 1.3, which is still under development.  If it were part of 1.2, then I would agree with you that retaining backwards compatibility would be critical.  As it is now, it looks more like a bug than intended behavior.

**Comment by mpdehaan** [comment]
agreed with @sfromm and +1 for adding follow=yes (default no) (though I think it might be unlikely for follow to be used much)

**Comment by mpdehaan** [comment]
Closing per above, thanks!
