### ISSUE TITLE
[Ansible 2.4.2.0] Plugin lookup not found 

### ISSUE THREAD

**Issue by agaillar** [ansible/ansible#35445]
##### ISSUE TYPE
 - Bug Report
 - Question

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /usr/users/xxxxxx/apps/ansible/cfg/ansible.cfg
  configured module search path =
  ansible python module location = /usr/users/xxxxxx/ansible-2.4.2.0/lib/python2.7/site-packages/ansible
  executable location = /usr/users/xxxxxx/ansible-2.4.2.0/bin/ansible
  python version = 2.7.14
```

##### CONFIGURATION
\# set plugin path directories here, separate with colons
action_plugins     = ./plugins/action
cache_plugins      = ./plugins/cache
callback_plugins   = ./plugins/callback
connection_plugins = ./plugins/connection
lookup_plugins     = ./plugins/lookup:/usr/users/xxxxxx/apps/ansible/lookup
inventory_plugins  = ./plugins/inventory
vars_plugins       = ./plugins/vars
filter_plugins     = ./plugins/filter
test_plugins       = ./plugins/test
terminal_plugins   = ./plugins/terminal
strategy_plugins   = ./plugins/strategy

##### OS / ENVIRONMENT
CentOS 7

##### SUMMARY
I'm running a playbook with the lookup plugin in the folder <playbook>/plugin/lookup/my_plugin.py.
The configuration file look for the lookup plugin in the folder ./plugin/lookup.
Ansible returns the following error:
```yaml
fatal: [localhost]: FAILED! => {"msg": "lookup plugin (my_plugin) not found"}
```
:ok: with ansible's version : `2.2.1.0`, `2.3.3.0`, `2.4.0.0`
:x: **KO with ansible's version** : `2.4.1.0`, `2.4.2.0`

Is it a error in my playbook or Ansible ?
Thanks for you help.

##### STEPS TO REPRODUCE

```yaml
...
action_plugins     = ./plugins/action
cache_plugins      = ./plugins/cache
callback_plugins   = ./plugins/callback
connection_plugins = ./plugins/connection
lookup_plugins     = ./plugins/lookup
inventory_plugins  = ./plugins/inventory
vars_plugins       = ./plugins/vars
filter_plugins     = ./plugins/filter
test_plugins       = ./plugins/test
terminal_plugins   = ./plugins/terminal
strategy_plugins   = ./plugins/strategy
...
```

```yaml
---                                             
- name: test 
  hosts: localhost                              
                                               
  tasks:                                        
    - name: test my_pluging 
      debug: msg={{ lookup('my_pluging') }} 
```

**Comment by sivel** [comment]
This change is documented in the porting guide at http://docs.ansible.com/ansible/devel/porting_guide_2.4.html#configuration

All paths are relative to the ansible.cfg file, which would indicate that ansible is looking for your plugin at:

```
/usr/users/xxxxxx/apps/ansible/cfg/plugins/lookup
```

Per that porting guide, there is a new macro called `{{CWD}}` which may resolve your issue.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by agaillar** [comment]
Thanks Sivel, i had not seen this information in the doc !! Sorry.
