### ISSUE TITLE
Ansible PIP does not seem to have the correct path to the current virtualenv's bin

### ISSUE THREAD

**Issue by shuhaowu** [ansible/ansible#3544]
Attempting to install [gevent](https://github.com/surfly/gevent) in a virtualenv via pip does not seem to work as ansible doesn't seem to recognize `cython` in the virtualenv, a prerequisite. Installation command is

```
 pip install cython -e git://github.com/surfly/gevent.git@1.0rc2#egg=gevent
```

**Comment by mpdehaan** [comment]
Can you please include the playbook command used and the output of "ansible --version" ?

**Comment by shuhaowu** [comment]
Version is ansible 1.2.2

I'm also installing as a part of requirements.txt

But this is the specific line:

```
- name: install requirements
  pip: virtualenv=/home/a1/venv/
       requirements=/home/a1/app/production-requirements.txt
```

Inside production-requirements:

```
Cython==0.19.1
Flask==0.9
Flask-Classy==0.6.3
Flask-Login==0.1.3
Flask-SeaSurf==0.1.16
Jinja2==2.7
MarkupSafe==0.18
Werkzeug==0.8.3
argparse==1.2.1
-e git://github.com/surfly/gevent.git@454a77ca561868854760b2d9cbfa3bf3bbd2e062#egg=gevent-dev
greenlet==0.4.0
leveldb==0.1
-e git://github.com/shuhaowu/leveldbkit.git@ebf3fb25ed24d0a4939f067a0d33b01db653de1b#egg=leveldbkit-dev
misaka==1.0.2
requests==1.2.3
ujson==1.33
wsgiref==0.1.2
```

**Comment by mpdehaan** [comment]
May be useful to look around line 144 here:

https://github.com/ansible/ansible/blob/devel/library/packaging/pip

This is how it selects which pip to use.

I would like to see the working pip command (non-ansible) you are using if you can share.

**Comment by shuhaowu** [comment]
The real command is this:

```
source ~/venv/bin/activate
pip install -r production-requirements
```

That works just fine.

I still suspect it is a path issue. I can have it so that I dump the
PATH while in ansible vs just in shell in the near future. That should
be pretty easy to do and I'll do that later.

Shuhao

**Comment by mpdehaan** [comment]
any update on this one?

**Comment by shuhaowu** [comment]
i haven't really had time to investigate further. If someone wants to confirm, I'm all for it.

**Comment by mpdehaan** [comment]
Ansible executes modules via a remote xfer mechanism so if you want to target a specific virtualenv you do that by setting ansible_python_interpreter.

It stands to reason that this if selecting a given virtualenv would not know to look at pip in that virtualenv.

That seems logical to me, but if there's a way to detect that the pip lies relative to the python location being executed I am fine with patches to improve this detection.

However I'd just pass the virtualenv parameter...

**Comment by jerm** [comment]
The issue here isn't the python interpreter, it's the lack of the rest of PATH pointing to the virtualenv for things other than pip or {{ansible_python_interpreter}}.  In this case, cython was installed in the virtualenv, and then gevent tries to use cython during its install process, but because the effective PATH in the session doesn't point to the virtualenv/bin (just a pointer to pip or python),  everything else currently installed in the virtualenv is  effectively non-existent.

What should be happening is that when given the virtualenv= and get_bin_path is called from _get_pip, is that that (correct) found path should be getting prepended to the working PATH in the session.

I don't see a way to pass a PATH (or PATH prefix) in to run_command currently, but I think it needs to be there as this is basic virtualenv functionality.  I also can't imagine there aren't plenty of other use cases for wanting a custom PATH for a certain command.

As such I've created a pull request to do just those things. https://github.com/ansible/ansible/pull/4413

**Comment by hackermd** [comment]
I ran into similar problems with `cython` when trying to install it via _Ansible_.

Both approaches didn't install `cython`:

``` yaml
pip: name=cython editable=no
become: yes
```

``` yaml
shell: pip install cython
become: yes
```

as evidenced by executing `python -c 'import cython'` on the remote machine.

However, _Ansible_ playbooks report a successful installation:

```
changed: [compute_node] => (item=cython) => {"changed": true, "cmd": "/usr/local/bin/pip install cython --user", "item": "cython", "name": "cython", "requirements": null, "state": "present", "stderr": "", "stdout": "Collecting cython\n  Downloading Cython-0.24.1-cp27-cp27mu-manylinux1_x86_64.whl (5.9MB)\nInstalling collected packages: cython\nSuccessfully installed cython-0.24.1\n", "stdout_lines": ["Collecting cython", "  Downloading Cython-0.24.1-cp27-cp27mu-manylinux1_x86_64.whl (5.9MB)", "Installing collected packages: cython", "Successfully installed cython-0.24.1"], "version": null, "virtualenv": null}
```

also, when rerunning the playbook, the package is reported to be successfully installed:

```
changed: [compute_node] => {"changed": true, "cmd": "pip install cython --upgrade", "delta": "0:00:00.729831", "end": "2016-10-16 15:56:53.796813", "rc": 0, "start": "2016-10-16 15:56:53.066982", "stderr": "", "stdout": "Requirement already up-to-date: cython in /root/.local/lib/python2.7/site-packages", "stdout_lines": ["Requirement already up-to-date: cython in /root/.local/lib/python2.7/site-packages"], "warnings": []}
```

When ssh-ing into the remote machine directly and executing `sudo pip install cython` directly it works.
