### ISSUE TITLE
Specifying multiple groups in a playbook

### ISSUE THREAD

**Issue by serenecloud** [ansible/ansible#3546]
Hi,

Apologies if this isn't a bug, but I've been trying to split my servers into groups for use in my playbook to no avail.

/etc/ansible/hosts

<pre>
[vps]
server1
server2

[home]
server3
</pre>

playbook:

<pre>

---
- hosts: vps,home
  user: ansible
  sudo: yes
  tasks:
    - name: get latest packages
      action: apt update_cache=yes
    - name: install latest packages
      action: apt upgrade=safe
</pre>

command line output:

<pre>
$ ansible-playbook ~/ansible/playbooks/apt_update_upgrade.yaml -K
sudo password:

PLAY [vps,home] ***************************************************************
skipping: no hosts matched

PLAY RECAP ********************************************************************
</pre>

vps and home work individually, but not together in the hosts: line. Using the keyword 'all' works. I'm running ansible 1.2.

My understanding of the format comes from the pedantically commented playbook: https://gist.github.com/marktheunissen/2979474

**Comment by srgvg** [comment]
@serenecloud the right syntax for combining multiple groups can be found here:

http://www.ansibleworks.com/docs/patterns.html#selecting-targets

That would become, for your example:

``` yaml
- hosts: vps:home
```

**Comment by serenecloud** [comment]
Ah, I see, thanks @sergevanginderachter! It is working now. I'll submit an issue to the pedantically commented playbook.

**Comment by PavelVanecek** [comment]
The correct link to the pattern documentation is now http://docs.ansible.com/ansible/intro_patterns.html#patterns

**Comment by AndreiPashkin** [comment]
Hm, the new version lacks information about `:` notation.

**Comment by emteeoh** [comment]
@AndrewPashkin Actually, it doesn't lack the info, but its wrong. The prose says to use a colon, but the example shows a comma.

**Comment by amenonsen** [comment]
The `:` notation is deprecated, and `,` is the recommended separator now. @emteeoh feel like submitting a PR to fix colon → comma? I missed that when replacing stuff because it wasn't a literal colon.

**Comment by MeanderingCode** [comment]
There should be a note on the patterns documentation about the change from one version to the next.  My version 1.9.4 doesn't support the comma syntax and finding this issue through a Google search is the only way I discovered to use a colon.

**Comment by MeanderingCode** [comment]
Made pull request https://github.com/ansible/ansible/pull/12958
Unsure of what version introduces the change, so please correct.

**Comment by joshrivers** [comment]
+1. Just spent an hour trying to figure out the problem with version 1.9.4 installed via pip install yesterday. Until 2.0 emerges from alpha, the documentation should really mention using the colon.

**Comment by bcoca** [comment]
docs were already updated to show : and note that , is broken in 1.9

**Comment by joshrivers** [comment]
Do the docs need deploying? http://docs.ansible.com/ansible/intro_patterns.html does not mention the colon.

**Comment by bcoca** [comment]
yep, needs deploying

**Comment by spq** [comment]
documentation is still wrong, examples are now consistent but description mentions comma

**Comment by enwood** [comment]
In Ansible 2.1.0, specifying multiple hosts doesn't appear to work:

I have this in my inventory file:
```
[testservers]
YK82-VAPP02T
[prod-web]
YK82-VWEB02P
YK82-VWEB03P
[prod-db]
YK82-VDB01P
```
and this in my playbook:
`- hosts: testservers,prod-web,prod-db`

I've also tried this:
`- hosts: testservers:prod-web:prod-db`

and this:
`- hosts: :"testservers,prod-web,prod-db"`

to no avail.
The only machine that gets hit with the task is the one machine in the [testservers] group. 

The documentation states that a colon represents an "OR" condition. If that's true, how do I tell Ansible to hit multiple hosts in an "AND" condition?

**Comment by mbigras** [comment]
After reviewing this issue I'm not clear if we're able to specify multiple patterns in one play, from this example it looks like I'd need to break them out into separate plays:

In some.yml I'm using two plays, each with one host pattern, overall the playbook finds 11 hosts:

```
cat some.yml
- hosts:
    - tag_Silo_dev
  tasks:
    - name: print something
      debug: msg="hello world"

- hosts:
    - tag_Environment_dev:&tag_node_type_bastion
  tasks:
    - name: print something
      debug: msg="hello world"
ansible-playbook some.yml | grep msg | wc -l
11
```

Then I combine the two host patterns into one play except only the `tag_Environment_dev:&tag_node_type_bastion` host is found:

```
cat more.yml
- hosts:
    - tag_Silo_dev
    - tag_Environment_dev:&tag_node_type_bastion
  tasks:
    - name: print something
      debug: msg="hello world"

ansible-playbook more.yml | grep msg | wc -l
1
```

Are we able to use multiple patterns?
Do I need to split patterns out into separate plays?
