### ISSUE TITLE
ansible command has problems with unicode characters

### ISSUE THREAD

**Issue by smooge** [ansible/ansible#3553]
Problem seems to be with a non-interactive shell ansible (ansible-1.2-1.el6.noarch) crashes when getent contains unicode. [I tried via > and | and got the same traceback.]
# ansible people03.fedoraproject.org -m shell -a 'getent passwd | grep ^toshio:'

people03.fedoraproject.org | success | rc=0 >>
toshio:x:100068:100068:Toshio くらとみ:/home/fedora/toshio:/bin/bash
# ansible people03.fedoraproject.org -m shell -a 'getent passwd | grep ^toshio:' > c

people03.fedoraproject.org | FAILED => Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/runner/**init**.py", line 344, in _executor
    exec_rc = self._executor_internal(host)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 423, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 605, in _executor_internal_inner
    self.callbacks.on_ok(host, data)
  File "/usr/lib/python2.6/site-packages/ansible/callbacks.py", line 339, in on_ok
    self._on_any(host,res)
  File "/usr/lib/python2.6/site-packages/ansible/callbacks.py", line 385, in _on_any
    display(msg, color=color)
  File "/usr/lib/python2.6/site-packages/ansible/callbacks.py", line 108, in display
    print msg2
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 219: ordinal not in range(128)

**Comment by jimi-c** [comment]
I just tried this with the current devel HEAD, and was unable to reproduce this:

<pre>
# ansible -m shell -a 'getent passwd | grep Über' ubuntu
192.168.1.190 | success | rc=0 >>
Über:x:1000:1000::/home/Über:/bin/sh
</pre>

Can you confirm if the recent development version fixes your issue, or the 1.2.3 release?

**Comment by jimi-c** [comment]
Since there has been no response on this in a week, I'm going to go ahead and close it as the issue appears to be fixed as of the 1.3 release. If you are still having problems you believe may be related to this issue, please feel free to open a new github issue. Thanks!
