### ISSUE TITLE
nginx/Ubuntu state=reloaded returns stopped even if running

### ISSUE THREAD

**Issue by titanous** [ansible/ansible#3556]
``` text
$ ansible -v -m service -a "name=nginx state=reloaded" brochure
10.10.39.10 | success >> {
    "changed": true,
    "name": "nginx",
    "state": "stopped"
}
```

nginx is actually running (Ubuntu). I'm not sure if the `state` being stopped is a bug or not, but it's suprising to me.

```
ansible 1.3 (devel fb869e58ee) last updated 2013/07/16 21:45:38 (GMT -400)
```

**Comment by mpdehaan** [comment]
Yeah so I've got a few bug reports about nginx on Ubuntu lately, I'm inclined to think this is an issue with the nginx status command.

Will investigate.

**Comment by bcoca** [comment]
Ubuntu's nginx config puts pid file in diff place than init script expects,
I had to fix that in my installation and now service module works fine.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by titanous** [comment]
This is the nginx package from the official `nginx.org` apt repo. Let me know if you need more info.

**Comment by mpdehaan** [comment]
Seems like we may need to workaround this (as much of the service module is
a workaround for crap init scripts and packaging issues).

**Comment by titanous** [comment]
@bcoca `/etc/init.d/nginx` has `PIDFILE=/var/run/nginx.pid` and I have `pid /var/run/nginx.pid;` in my nginx config.

**Comment by titanous** [comment]
``` text
$ sudo /etc/init.d/nginx status
 * nginx is running
```

**Comment by bcoca** [comment]
then we don't have same issue.

On Tue, Jul 16, 2013 at 10:01 PM, Jonathan Rudenberg <
notifications@github.com> wrote:

> @bcoca https://github.com/bcoca /etc/init.d/nginx has
> PIDFILE=/var/run/nginx.pid and I have pid /var/run/nginx.pid; in my nginx
> config.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/3556#issuecomment-21087608
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by bcoca** [comment]
what is the return code?, that is what service module uses to determine
status (as per standard).

On Tue, Jul 16, 2013 at 10:02 PM, Jonathan Rudenberg <
notifications@github.com> wrote:

> $ sudo /etc/init.d/nginx status
> - nginx is running
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/3556#issuecomment-21087643
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by titanous** [comment]
@bcoca It's `0` as expected.

**Comment by mpdehaan** [comment]
which Ubuntu is this BTW?

**Comment by titanous** [comment]
12.04.2 x64

**Comment by resmo** [comment]
/me is having a look at this asap.

**Comment by jimi-c** [comment]
This was also on my todo list for this week. There are 5-6 other issues related to the service module as well, so it seems like it could be improved a bit to handle shoddily written init.d scripts.

**Comment by srgvg** [comment]
works for me +1

**Comment by resmo** [comment]
lol, nice fix :+1:
