### ISSUE TITLE
Expose shell glob as Jinja2 filter

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#3563]
User would like to iterate across filesystem files in a Jinja2 template

This seems like we'd want to expose a filter to do this.

**Comment by bradleyy** [comment]
Trying to parse what this means. Would something like the following be the intended look and feel?

  name: do things with files
  command: do_something {{ item }}
  with_items(lines?): {{"/path/to/*.glob"|as_fileglob }}

Does that meet the requirement? I think this is doable, and meets the need. Not 100% on the aesthetics. Something about it bugs me, but I can't put my finger on it.

**Comment by mpdehaan** [comment]
Nope, this is a Jinja2 filter not a lookup plugin.

Something like

{% for x in "/tmp/files/*" | fileglob %}

{% endfor %}

Not super high priority.

**Comment by sivel** [comment]
A pull request has been added for this: https://github.com/ansible/ansible/pull/4306
