### ISSUE TITLE
Ansible should yell about not finding sshpass

### ISSUE THREAD

**Issue by xshadow** [ansible/ansible#3564]
A user complained about a failing playbook (https://groups.google.com/forum/#!topic/ansible-project/yyUXKMFD6Jg) : 

> Hi 
> I am trying to find if a package is installed using playbook
> - hosts: workstations
> 
> user: root
> 
>  tasks:
> - name: ensure xyz is installed
>   action: yum pkg=xyz state=installed
> 
> But its failing with error
> $ansible-playbook playbook.yml -c ssh 
> 
> Output : PLAY [workstations] *********************
> 
> GATHERING FACTS *********************
> fatal: [127.0.0.1] => failed to transfer file to /setup:
> 
> Connecting to 127.0.0.1...
> Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
> Couldn't read packet: Connection reset by peer

The solution is, that sshpass is not installed: 

> You have to install sshpass first.
> And then you should run the playbook with --ask-pass option like:
> ansible-playbook --ask-pass playbook.yml -c ssh

Would be better if ansible rings the bell and says "sshpass is not installed".

**Comment by mpdehaan** [comment]
I'm actually seeing decent error handling here (using 1.3), can you confirm your ansible version?

[root@localhost lib]# ansible all -m ping -c ssh -k
SSH password: 
127.0.0.1 | FAILED => to use -c ssh with passwords, you must install the sshpass program
127.0.0.2 | FAILED => to use -c ssh with passwords, you must install the sshpass program
127.0.0.3 | FAILED => to use -c ssh with passwords, you must install the sshpass program
127.0.0.4 | FAILED => to use -c ssh with passwords, you must install the sshpass program
127.0.0.5 | FAILED => to use -c ssh with passwords, you must install the sshpass program

**Comment by xshadow** [comment]
[17:31:38] root:~ $ ansible --version
ansible 1.2.2

**Comment by mpdehaan** [comment]
ok seems resolved in 1.3, I am going to close this ticket then.

Thanks!

**Comment by fabienlege** [comment]
I have the same problem in version 1.4 ! I just try this command :
ansible localhost -i .ansible/hosts --ask-pass -a "whoami"
and the result is :
localhost | FAILED => to use the 'ssh' connection type with passwords, you must install the sshpass program

What is the problem ?!

**Comment by gregbuehler** [comment]
You should try `ansible localhost -i .ansible/hosts --ask-pass -a "whoami" -c paramiko`

**Comment by hajmos** [comment]
for ubuntu :
sudo apt-get install sshpass

**Comment by JoaoSeger** [comment]
To version 1.9.4 I used the information in https://gist.github.com/arunoda/7790979 and worked.

**Comment by shako92** [comment]
თქვენ გაიხარეთ!

**Comment by rajvlr25** [comment]
It is possible to use ansible without ssh keys. This may be useful if you are unable to use keys in your environment for some reason.

You need the -k flag to prompt for the password, and to install the sshpass helper program.

$ ansible all -m ping -k
SSH password: <type the password here>
hostXXX.ws.nsrc.org | FAILED => to use the 'ssh' connection type with
passwords, you must install the sshpass program

$ sudo apt-get install sshpass
...
$ ansible all -m ping -k
SSH password: <type the password here>
hostXXX.ws.nsrc.org | success >> {
    "changed": false,
    "ping": "pong"
}
