### ISSUE TITLE
Action "service state=enabled" does not ensure links exist for update-rc.d

### ISSUE THREAD

**Issue by jongiddy** [ansible/ansible#3572]
Running the "service" library action with "state=enabled" on Ubuntu 12.04 runs "update-rc.d enable", but this command only works if the /etc/rcN.d links have previously been installed using "update-rc.d defaults" or "update-rc.d start".

To ensure the service is correctly configured to start on reboot, the library should ensure the links exist before calling "update-rc.d enable".

Simplest solution would be to always call "update-rc.d defaults" (a no-op if links already exist) before calling "update-rc.d enable".

A more complicated solution could check for a "runlevel" parameter and use "update-rc.d start" if present.

**Comment by mpdehaan** [comment]
Quick question, which service did you have this problem with?

I haven't heard this reported before, so it seems like a packaging problem.

Doesn't seem to be a bad idea, regardless!

**Comment by bcoca** [comment]
My default debian based distros run update-rc.d on install, this can happen
after manually running it to remove the links or when forcing install
without triggers.

Brian Coca

**Comment by jongiddy** [comment]
This is for the Rserve service from the Ubuntu package r-cran-rserve. It doesn't include startup scripts (many users might start it up only occasionally using their own user account).

To start it as a permanently available service available to everyone, I use Ansible to install it, and add my own /etc/init.d/rserve script.

I then need to run "update-rc.d defaults" to install the symlinks to make start on reboot active.  It would be nice if I could use "service enable" to do this step in a platform-independent way.

**Comment by jongiddy** [comment]
I have attached a patch in issue #3589.

Note, this patch also reverts #3315 (change detection for update-rc.d), as it does not work on Ubuntu 12.04 LTS. The output of update-rc.d seems to change dramatically between distibutions / releases.

**Comment by bcoca** [comment]
He, I also had to write my reserve init and did run an update-rc.d

Brian Coca

**Comment by jongiddy** [comment]
I have added issue #3615 to revert the incorrect change detection, in order to avoid adding the reversion in this patch. Thanks, Jon.

**Comment by jimi-c** [comment]
Please give the above patch a try, it has resolved the issue in my testing. Thanks!
