### ISSUE TITLE
need way in Ansible core to turn off the retry file by environment variable

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#3573]
There should be a way to not generate the host retry file.

**Comment by mpdehaan** [comment]
Low priority.

**Comment by mpdehaan** [comment]
I think we can close this.

**Comment by hynek** [comment]
Is there some way I missed to avoid that ansible litters my home directory with retry files? This ticket is all I found when googling for the obvious terms and nobody knew anything on IRC…

**Comment by dsalzr** [comment]
+1. I was looking for a way to disable the retry files in the config but no luck.

**Comment by dghubble** [comment]
+1

**Comment by rwehner** [comment]
+1. I'd like to be able to disable them or at least configure them to go into a directory other than $HOME.

**Comment by kuba** [comment]
Although this bug report has been closed 6 months ago being a low priority, @mpdehaan recently agreed on ansible-devel mailing list to accept an appropriate patch. **Please subscribe to #5515** instead, where we currently discuss it.
