### ISSUE TITLE
Increased memory usage in ansible-playbook from 2.4.2 to 2.4.3

### ISSUE THREAD

**Issue by mattclay** [ansible/ansible#35796]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

ansible-playbook

##### ANSIBLE VERSION

```
ansible 2.4.3.0 (detached HEAD 8a7f9beab7) last updated 2018/02/06 09:50:10 (GMT -700)
  config file = None
  configured module search path = [u'/Users/mclay/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mclay/code/mattclay/ansible/lib/ansible
  executable location = /Users/mclay/code/mattclay/ansible/bin/ansible
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### CONFIGURATION

None

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

The `git` integration tests consume far more memory under 2.4.3 than they did under 2.4.2.

##### STEPS TO REPRODUCE

1. Apply the [mprof patch](https://gist.github.com/mattclay/c7ee66370ddc15fe649a2e5f289b74f2) to `ansible-test` to track `ansible-playbook` memory usage.
1. Run the `git` integration test: `ansible-test integration git --docker ubuntu1604 -v`
1. Compare the results of `test/results/logs/mprofile*.dat` between a 2.4.2 and 2.4.3 test run.

##### EXPECTED RESULTS

Peak memory usage around 280 MB (2.4.2):

```
MEM 280.367188 1517945476.7207
```

##### ACTUAL RESULTS

Peak memory usage over 1500 MB (2.4.3):

```
MEM 1525.949219 1517944990.4613
```

With a low enough memory limit the test fails with: `[Errno 12] Cannot allocate memory`

**Comment by sivel** [comment]
After bisecting from 2.4.2 to 2.4.3, it seems the spike in memory utilization comes from https://github.com/ansible/ansible/commit/f1c458303a1ad00675497597e1f7fbc0539e314e

**Comment by sivel** [comment]
The fix has been backported to stable-2.4 for an upcoming 2.4.4 release, it is also in stable-2.5 for the 2.5.0.b1 release and is in devel.

**Comment by holta** [comment]
@sivel this issue (or https://github.com/ansible/ansible/issues/31673 or similar?) has returned on Ansible 2.5.0 on Raspbian 2018-03-13 on Raspberry Pi 3.  As documented at https://github.com/iiab/iiab/issues/669#issuecomment-376005065 :

> TASK [network : Copy /etc/sysconfig/dhcpd file] ********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 12] Cannot allocate memory
fatal: [127.0.0.1]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

**Comment by knightsg** [comment]
This is happening for me also on stable-2.4 (commit #00348c3d):

TASK [common : set system timezone] ********************************************
ERROR! Unexpected Exception, this is probably a bug: [Errno 12] Cannot allocate memory
to see the full traceback, use -vvv
FATAL: command execution failed

**Comment by trondhindenes** [comment]
possibly related:
https://github.com/ansible/ansible/issues/38532
