### ISSUE TITLE
Problem with when: statement

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#3580]
This refers to community discussion: https://groups.google.com/forum/#!topic/ansible-project/tsSaBtDikSc

I have variables set in a file under host_vars, and I have when statements in the playbook to execute actions based off the vars.   Such as

when: ostype == "rhel6"

The first action that uses the when fires, but second ones that have the same when statement are "skipped".  

I put a sample playbook on gist:

https://gist.github.com/rlbeaver/ece9bf8c35c0b4d18c12

**Comment by mpdehaan** [comment]
Ok, this is related to some typos on your end.

Take a look at this:

```
- name: Fetch rhel5 epel repo file
get_url: url=ftp://mirrors.rit.edu/epel/6/i386/epel-release-6-8.noarch.rpm dest=/tmp/epel-release-6-8.noarch.rpm mode=0440
when: ostype == "rhel6"

- name: Fetch rhel5 epel repo file
get_url: url=ftp://mirrors.rit.edu/epel/5/i386/epel-release-5-4.noarch.rpm dest=/tmp/epel-release-6-8.noarch.rpm     mode=0440
when: ostype == "rhel5"
```

The name in the first task says "rhel5", but it's really about rhel6.

There does not appear to be any problem here with the conditional support.  Let me know if you find otherwise.

**Comment by ghost** [comment]
The name field is wrong, if I fix the name option, the second action with a "when: ostype =="rhel6"" is still skipped.   In the add_app_mounts.yml, it also skips the second action which doesn't have a type in the name field.  I don't think the -name option matters to the when statement, does it?

In fact, in that file, it executed the get_url action, but skipped the following yum install option...

In every instance where I have multiple actions with the conditional like that, it will execute the first action and skip the subsequent actions with the same conditional as if the var was reset or something.   

It also doesn't matter if I remove the two rhel5 actions from the file...

**Comment by ghost** [comment]
I think I figured out the issue, it behaves differently when --check is used than without.  I'm guessing I missed somehwere that --check will cause some commands to skip becuase they are not "testable" since they're just commands.

**Comment by mpdehaan** [comment]
right!
