### ISSUE TITLE
Lots of references to discouraged ${var} on modules doc page

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#3581]
I was looking at the [Ansible modules doc page](http://www.ansibleworks.com/docs/modules.html), and noticed there are a number of references to the discouraged $foo or ${foo} syntax for variable interpolation instead of {{ foo }}:

```
$ curl -s http://www.ansibleworks.com/docs/modules.html | grep '\$' | wc -l
  43
```

The module documentation should be updated to use the new style of variable references to avoid confusing new users.

**Comment by mpdehaan** [comment]
I agree!

I will attack this shortly as I think I most want continuity here, though wanted to point out corrections to module YAML are very very welcome too and greatly appreciated :)

**Comment by mpdehaan** [comment]
working on this now.

**Comment by mpdehaan** [comment]
Should all be fixed, will be in next docs push.  Thanks!
