### ISSUE TITLE
vyos_ping

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#35870]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
vyos_ping

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
there is no vyos_ping (or linux equivalent) 

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A

**Comment by IPvSean** [comment]
already have bug filed, net_ping should fail until this exists-> https://github.com/ansible/ansible/issues/35869

**Comment by ikhan2010** [comment]
@NilashishC can we start exploring what will it take to get this feature implemented?  Can we estimate the time?

**Comment by NilashishC** [comment]
@ikhan2010 ~I have finished writing the module. Currently adding unit test for it. I should have a PR ready by tomorrow(12/20).~ PR for this in review.

**Comment by ikhan2010** [comment]
@gdpak can you please review this?

**Comment by NilashishC** [comment]
Resolved by #50193
