### ISSUE TITLE
apt-get upgrade hangs when installing grub

### ISSUE THREAD

**Issue by commandodev** [ansible/ansible#3592]
Running Vagrant with both box precise64 and precise32 has resulted with my playbook seeming to hang when running apt-get upgrade.

The problem seems to be upgrading grub, which when I log into the box and upgrade manually drops me into a package configuration asking me to configure the GRUB install device.

Is this user error (i.e. is there a flag I should be using) or a bug?

**Comment by mpdehaan** [comment]
Are you calling this with the shell or the apt module? 

Please include the line from your playbook.

Thanks.

**Comment by commandodev** [comment]
Gah, looks like user error! I'm using a playbook adapted from 5minbootstrap. This is the line I'm using unchanged: https://github.com/phred/5minbootstrap/blob/master/bootstrap.yml#L13

If I change to using apt: upgrade=yes I assume it will work?

Sorry for the noise!
