### ISSUE TITLE
Include dns servers from /etc/resolv.conf in facts

### ISSUE THREAD

**Issue by przemolb** [ansible/ansible#3593]
It would be good to add dns servers from /etc/resolv.conf to ansible facts - it gives even more data about each node.

**Comment by mpdehaan** [comment]
I think this could be done with a custom facts module if you wanted, or even leveraging the facts.d mechanism in 1.3 (documentation TBD) but am not sure I want to include this in core setup.

**Comment by jpmens** [comment]
There's an open PR for this as a module. Even if it isn't taken to core, you could use the module in your own library/ , @przemolb : https://github.com/ansible/ansible/pull/3594

**Comment by przemolb** [comment]
My answer: https://github.com/ansible/ansible/pull/3594#issuecomment-21333511
