### ISSUE TITLE
Feature request: make documentation friendlier for tools like doc2dash

### ISSUE THREAD

**Issue by vmalloc** [ansible/ansible#3601]
It would be nice to be able to create a quick module reference for tools like Dash (http://kapeli.com/dash). Dash provides its own doc2dash python package for quickly converting sphinx-documented projects to Dash docsets. Unfortunately it seems Ansible's documentation isn't trivial to process using doc2dash.

**Comment by mpdehaan** [comment]
I haven't heard of this before and it isn't something I think we're likely to work on, given I don't know of anyone using this.

**Comment by chrisberkhout** [comment]
I love Dash. It's Mac only, but there's a clone for Linux and Windows that reads the same docset format: [Zeal](http://zealdocs.org/).

@vmalloc now has now [built an Ansible docset](http://rotemy.com/blog/posts/2012/dash-python/). It's a bit out of date (v1.2.1) and the index page should probably be populated like the contents page, but it's still helpful. Thanks!

**Comment by drewda** [comment]
Thanks for making an Ansible docset, @vmalloc

(I've been getting great use out of Dash and am glad to see more and more others doing the same!)

**Comment by vmalloc** [comment]
You're welcome. I only regret that the documentation is so hard to convert via doc2dash, and requires some hacky preprocessing.

**Comment by patrickheeney** [comment]
I found this via a google search. I would also be interested in this. Using the site for documentation now is pretty painful when used to a tool like dash. I find it difficult to find anything except for module information on the docs.
