### ISSUE TITLE
Unstable integration test azure_rm_postgresqldatabase

### ISSUE THREAD

**Issue by mattclay** [ansible/ansible#36069]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

azure_rm_postgresqldatabase integration test

##### ANSIBLE VERSION

2.5

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Shippable

##### SUMMARY

Unstable integration test azure_rm_postgresqldatabase:

https://app.shippable.com/github/ansible/ansible/runs/54385/62/tests

##### STEPS TO REPRODUCE

Run tests on Shippable.

##### EXPECTED RESULTS

Tests pass.

##### ACTUAL RESULTS

Tests are unstable or fail.

> test/integration/targets/azure_rm_postgresqldatabase/tasks/main.yml:6 / [localhost] azure: azure_rm_postgresqldatabase : Create PostgreSQL Server sku={u'tier': u'basic', u'name': u'PGSQLS100'}, name=postgresqlsrv{{ rpfx }}, resource_group={{ resource_group }}, storage_mb=51200, admin_username=zimxyz, location=westus, enforce_ssl=True, admin_password=Testpasswordxyz12!

> failure: Error creating the PostgreSQL Server instance: Azure Error: OperationTimedOut Message: The operation timed out and automatically rolled back. Please retry the operation.

```
{
"changed": false, 
"failed": true, 
"msg": "Error creating the PostgreSQL Server instance: Azure Error: OperationTimedOut\nMessage: The operation timed out and automatically rolled back. Please retry the operation.", 
"warnings": [
"Azure API profile latest does not define an entry for PostgreSQLManagementClient"
]
}
```

**Comment by mattclay** [comment]
@zikalino Can you take a look at this?

**Comment by mattclay** [comment]
These tests have been temporarily disabled in https://github.com/ansible/ansible/commit/a9a7d15698ced118eabff5c606239b87196b3d5f due to the high frequency of failures.

**Comment by zikalino** [comment]
preparing generic solution for this kind of issues, should be available at some point next week.

**Comment by zikalino** [comment]
just working on it again

**Comment by yungezz** [comment]
closed since 'untable' removed.
