### ISSUE TITLE
Unstable integration test azure_rm_postgresqlserver

### ISSUE THREAD

**Issue by mattclay** [ansible/ansible#36070]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

azure_rm_postgresqlserver integration test

##### ANSIBLE VERSION

2.5

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Shippable

##### SUMMARY

Unstable integration test azure_rm_postgresqlserver:

https://app.shippable.com/github/ansible/ansible/runs/54385/62/tests

##### STEPS TO REPRODUCE

Run tests on Shippable.

##### EXPECTED RESULTS

Tests pass.

##### ACTUAL RESULTS

Tests are unstable or fail.

> test/integration/targets/azure_rm_postgresqlserver/tasks/main.yml:25 / [localhost] azure: azure_rm_postgresqlserver : Create instance of PostgreSQL Server sku={u'tier': u'basic', u'name': u'PGSQLS100'}, name=postgresqlsrv{{ rpfx }}, resource_group={{ resource_group }}, storage_mb=51200, admin_username=zimxyz, location=westus, enforce_ssl=True, admin_password=Testpasswordxyz12!

> failure: Error creating the PostgreSQL Server instance: Azure Error: OperationInterrupted Message: The operation on the resource could not be completed because it was interrupted by another operation on the same resource.

```
{
"changed": false, 
"failed": true, 
"msg": "Error creating the PostgreSQL Server instance: Azure Error: OperationInterrupted\nMessage: The operation on the resource could not be completed because it was interrupted by another operation on the same resource.", 
"warnings": [
"Azure API profile latest does not define an entry for PostgreSQLManagementClient"
]
}
```

> test/integration/targets/azure_rm_postgresqlserver/tasks/main.yml:6 / [localhost] azure: azure_rm_postgresqlserver : Create instance of PostgreSQL Server -- check mode sku={u'tier': u'basic', u'name': u'PGSQLS100'}, name=postgresqlsrv{{ rpfx }}, resource_group={{ resource_group }}, storage_mb=51200, admin_username=zimxyz, location=westus, enforce_ssl=True, admin_password=Testpasswordxyz12!

> error: Timestamp: 2018-02-11 00:07:09Z

```
Traceback (most recent call last):
  File "/tmp/ansible_tv6IM6/ansible_module_azure_rm_postgresqlserver.py", line 365, in <module>
    main()
  File "/tmp/ansible_tv6IM6/ansible_module_azure_rm_postgresqlserver.py", line 362, in main
    AzureRMServers()
  File "/tmp/ansible_tv6IM6/ansible_module_azure_rm_postgresqlserver.py", line 199, in __init__
    supports_tags=False)
  File "/tmp/ansible_tv6IM6/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py", line 323, in __init__
  File "/usr/local/lib/python2.7/dist-packages/msrestazure/azure_active_directory.py", line 440, in __init__
    self.set_token()
  File "/usr/local/lib/python2.7/dist-packages/msrestazure/azure_active_directory.py", line 473, in set_token
    raise_with_traceback(AuthenticationError, "", err)
  File "/usr/local/lib/python2.7/dist-packages/msrest/exceptions.py", line 48, in raise_with_traceback
    raise error
msrest.exceptions.AuthenticationError: , UnauthorizedClientError: (unauthorized_client) AADSTS70001: Application with identifier '6ec68e6b-38db-432d-9e26-69c55d3d2168' was not found in the directory 51cfe857-2f92-4581-b504-ee3eba3db075
Trace ID: de7a888b-0d20-4775-956e-06b8fbfc0000
Correlation ID: 043597ba-ef5a-40e8-81f5-f52014b34007
Timestamp: 2018-02-11 00:07:09Z
```

**Comment by mattclay** [comment]
@zikalino Can you take a look at this?

**Comment by mattclay** [comment]
These tests have been temporarily disabled in https://github.com/ansible/ansible/commit/a9a7d15698ced118eabff5c606239b87196b3d5f due to the high frequency of failures.

**Comment by zikalino** [comment]
preparing generic solution for this kind of issues, should be available at some point next week.

**Comment by zikalino** [comment]
a bit delayed but working on it this week

**Comment by yungezz** [comment]
close since removed unstable tag
