### ISSUE TITLE
Unstable integration test azure_rm_mysqldatabase

### ISSUE THREAD

**Issue by mattclay** [ansible/ansible#36087]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

azure_rm_mysqldatabase integration test

##### ANSIBLE VERSION

2.5

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Shippable

##### SUMMARY

Unstable integration test azure_rm_mysqldatabase:

https://app.shippable.com/github/ansible/ansible/runs/54076/51/console

##### STEPS TO REPRODUCE

Run tests on Shippable.

##### EXPECTED RESULTS

Tests pass.

##### ACTUAL RESULTS

Tests are unstable or fail.

> 2018-02-08 13:44:18 TASK [azure_rm_mysqldatabase : Create instance of MySQL Database] **************
> 2018-02-08 13:50:51 fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error creating the MySQL Database instance: Azure Error: OperationTimedOut\nMessage: The operation timed out and automatically rolled back. Please retry the operation."}

**Comment by mattclay** [comment]
@zikalino Can you take a look at this?

**Comment by zikalino** [comment]
preparing generic solution for this kind of issues, should be available at some point next week.

**Comment by zikalino** [comment]
working on it

**Comment by mattclay** [comment]
Closing this as the tests are not currently marked unstable and I haven't noticed failures recently. I will re-open if I start seeing issues again.
