### ISSUE TITLE
fire and forget mode (async w/ poll: 0) should show some progress of issuing tasks

### ISSUE THREAD

**Issue by omgjlk** [ansible/ansible#3608]
Right now there is 0 output for the task (in -v mode). I would expect that there would be some indication that the task was started for a host.

**Comment by mpdehaan** [comment]
Yep, this is basically because Ansible outputs things when things are done and not started

Maybe the -v level should show show task initiation in general, or maybe at least -vv

**Comment by mpdehaan** [comment]
Should be fixed by 6ba43311619e814ca41025c8c8da0f6784e3b30c -- let me know if this doesn't work for you.

Thanks!
