### ISSUE TITLE
Unstable integration test azure_rm_sqlserver_facts

### ISSUE THREAD

**Issue by mattclay** [ansible/ansible#36085]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

azure_rm_sqlserver_facts integration test

##### ANSIBLE VERSION

2.5

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Shippable

##### SUMMARY

Unstable integration test azure_rm_sqlserver_facts:

https://app.shippable.com/github/ansible/ansible/runs/54373/62/console

##### STEPS TO REPRODUCE

Run tests on Shippable.

##### EXPECTED RESULTS

Tests pass.

##### ACTUAL RESULTS

Tests are unstable or fail.

> 2018-02-10 16:23:50 TASK [azure_rm_sqlserver_facts : Create SQL Server - 2] ************************
> 2018-02-10 16:48:16 fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error creating the SQL Server instance: Azure Error: OperationTimedOut\nMessage: The operation timed out and automatically rolled back. Please retry the operation."}

**Comment by mattclay** [comment]
@zikalino Can you take a look at this?

**Comment by mattclay** [comment]
These tests have been temporarily disabled in https://github.com/ansible/ansible/commit/a9a7d15698ced118eabff5c606239b87196b3d5f due to the high frequency of failures.

**Comment by zikalino** [comment]
preparing generic solution for this kind of issues, should be available at some point next week.

**Comment by zikalino** [comment]
working on it

**Comment by Fred-sun** [comment]
@zikalino Could you please help update the issue? Thanks!

**Comment by Fred-sun** [comment]
@zikalino Could you help update the comment? Thanks!
