### ISSUE TITLE
Rolling updates should allow max percentage of failure 

### ISSUE THREAD

**Issue by kavink** [ansible/ansible#3609]
While doing rolling updates, would be nice to have a configurable parameter to indicate max number of node failures allowed before stopping the playbook. The reason is if there is some issue in upgrade and tomcat or some other step fails to comeup on many machines, We should stop the playbook and not take down majority of the nodes.

i.e. Suppose in playbook i configure, 

```
# From the group of servers , if 5% have failed, Stop running the playbook
 - hosts: {{host_group}}
   serial: 10
   maxfail: 5%
```

So if you have 300 servers, and serial: 25 and maxfail: 5%. In the first 2 runs combined, (50 servers) , 15 servers failed , like 10 in 1st and 15 in second. Stop the playbook

**Comment by mpdehaan** [comment]
Yep, this is a very good idea.

For info of others, the current behavior is to stop after "serial: N" number of failures, which will ensure a failed playbook block will not continue to update the whole system if that block fails, but if half that block fails, it would still move onto the next rolling update block.

**Comment by mpdehaan** [comment]
So we already have the pull request so I can close this ticket about the feature.
