### ISSUE TITLE
Cannot force a local connection with an Action module plugin.

### ISSUE THREAD

**Issue by tima** [ansible/ansible#3612]
This was discovered testing and debugging pull request 3173 and is a blocker to its acceptance until resolved. 

https://github.com/ansible/ansible/pull/3173

It seems that once the connection is established that changing the delegate in the inject data has no effect. See this commit here: https://github.com/tima/ansible/commit/1bf90df9655fb745dcc687c392d9d0f6b83e7778

Here is the verbose output with some debugging message in my action modules run:

$ ansible -i rsync.ini -m synchronize -a "src='./hacking' dest='/tmp/'" --private-key ~/.ssh/gsg-foo.pem -vvv -u ubuntu -c ssh all
<foo.appnel.com> ESTABLISH CONNECTION FOR USER: ubuntu
<foo.appnel.com> EXEC ['ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'IdentityFile=/Users/tima/.ssh/gsg-foo.pem', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PasswordAuthentication=no', '-o', 'User=ubuntu', '-o', 'ConnectTimeout=10', 'foo.appnel.com', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1374122730.46-187893212842113 && chmod a+rx $HOME/.ansible/tmp/ansible-1374122730.46-187893212842113 && echo $HOME/.ansible/tmp/ansible-1374122730.46-187893212842113'"]
DEBUG in synchronize run method now
DEBUG no delegate defined -- setting to 127.0.0.1
DEBUG remote handling 127.0.0.1 to foo.appnel.com
<foo.appnel.com> PUT /var/folders/42/xv4f750d1sb3k8l4vrjn1sz00000gn/T/tmpzzaWBE TO /home/ubuntu/.ansible/tmp/ansible-1374122730.46-187893212842113/synchronize
<foo.appnel.com> EXEC ['ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'IdentityFile=/Users/tima/.ssh/gsg-foo.pem', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PasswordAuthentication=no', '-o', 'User=ubuntu', '-o', 'ConnectTimeout=10', 'foo.appnel.com', "/bin/sh -c '/usr/bin/python /home/ubuntu/.ansible/tmp/ansible-1374122730.46-187893212842113/synchronize; rm -rf /home/ubuntu/.ansible/tmp/ansible-1374122730.46-187893212842113/ >/dev/null 2>&1'"]

Despite setting inject['delete_to'] to the localhost Ansible does a PUT and EXEC of the module file.

**Comment by mpdehaan** [comment]
To add some detail for others, the question here is about developing the rsync module, and the need inside the module to force the module to run under "local_action".

I believe this can be done just by calling the internals of runner with the appropriate flags or adding a new flag, so will investigate.

**Comment by tima** [comment]
From tracing through the code here around line 559 in runner/**init**.py the connection gets established:

```
        conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file)
        if delegate_to or host != actual_host:
            conn.delegate = host
```

Maybe 20 lines later it calls the action's run module:

```
        result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
```

It too late by then because a lot of decision have been made based on the delegate. Before the connection has been established, back on around 516 you have all this going on...

```
    # the delegated host may have different SSH port configured, etc
    # and we need to transfer those, and only those, variables
    delegate_to = inject.get('delegate_to', None)
    if delegate_to is not None:
```

In order to override things to force the local connection in an action's run method you'd need to undo everything inside that if statement. 

I'm thinking we'd need to introduct an optional init method for an action module. Ansible would pass that method things like the inject data structure (perhaps the same params as run?) that would let a developer override anything before the connection and further processing takes place. Maybe something like this right after conn = None around line 506?

```
    try:
        handler.init(conn, tmp, module_name, module_args, inject, complex_args)
    except AttributeError:
        pass
```

**Comment by tima** [comment]
I branched off of my ansible-rsync-take2 branch and brought in a try block (with less params going to init) that works with changing the delegate_to value in inject. I'll submit it as a separate pull request for your review.

If you thought more params should be passed in to the init method (tmp, module_args, complex_args) we'd have to move some lines up ahead of the where I have the try block now.

**Comment by mpdehaan** [comment]
fixed per above, thanks!

**Comment by defunctzombie** [comment]
> To add some detail for others, the question here is about developing the rsync module, and the need inside the module to force the module to run under "local_action".

I have tried looking for this feature in the docs but have not found it. How would I go about setting a flag in my module to force running as a local_action?
