### ISSUE TITLE
Ranges in inventory doesn't work as expected

### ISSUE THREAD

**Issue by nu7hatch** [ansible/ansible#3614]
Hello! I have this in my inventory:

```
33.33.33.[101:105] hostname=api[1:5].dev
```

Now, when i try to use `{{ hostname }}` in one of my templates what i get is plain `node[1:2].dev`, where it should be `node1.dev` etc.

Btw, maybe I'll give you some background what i wanna do, so you can give me some eventual tips if there's a better way. Simply, I wan't new machines that i'm bringing up to be provisioned in pull mode. To know what group machine belongs to i'm discovering it's ip and executing something like this:

```
ansible-playbook -i$env -l$ip -clocal site.yml
```

This way i right away can figure out that `33.33.33.105` is my `api5` server that should be provisioned in a certain way. The process is also configurationless, as the $env is taken from ec2 tags for production and staging (or if not provided set to test, on vagrant). Any better idea to solve this?

Coming back to initial issue, I could of course put 5 different entries what i did for now, but in a long run where i expect 50+ machines in production it doesn't make sense.

**Comment by bcoca** [comment]
ranges work for hosts defined in inventory, I don't believe there is
anything that will make them work for variables.

**Comment by nu7hatch** [comment]
Yeap, there's nothing that would handle vars in the code. For the reasons I've posted earlier I can't use hostnames in inventory. Basically hostname is something i have no idea about at any stage of creation of the instance. I could get it from tags or instance name in meta-data on ec2, but on vagrant i have no way to work it out. 

I think the easiest way maybe would be to provide some extra variable that can be used there, for example:

```
33.33.33.[101:105] hostname="api{{ inventory_host_range }}"
```

Or with multiple ranges:

```
33.33.[33:34].[101:105] hostname="api{{ inventory_host_range.0 }}-{{ inventory_host_range.1 }}"
```

EDIT: Btw, not sure if there's support for jinja in inventory variables, but i would work for me anyway as i could set hostname from group_vars. 

EDIT 2: Well it does support jinja... but this will be not so easy as i expected, because having let's say that `inventory_host_range` there, it will give me a value for current host (so running playbook against `33.33.33.101` will make `inventory_host_range` to have that value everywhere)

**Comment by nu7hatch** [comment]
Ok, for now I've solved it this way:

```
33.33.33.[101:105] hostname="api-{{ host_id }}.dev"
```

Then in my `group_vars/all` I have:

```
host_id: "{{ '-'.join(inventory_hostname.split('.')[2:]) }}"
```

Finally, in a template for `/etc/hosts` i have that ugly thing:

```
{% for x in groups.all %}
{{ hostvars[x].inventory_hostname }} {{ hostvars[x].hostname.replace("{{ host_id }}", "-".join(hostvars[x].inventory_hostname.split('.')[2:])) }} {{ hostvars[x].public_hostname }}
{% endfor %}
```

However, I'm not worried about the last one because it will go away whenever I'll bring up a custom dns server to the formation. Well, and even if not there are probably way worst things than this. This one works at least ;)

So, now it's up to you guys, if there will be no further requests for this feature i can live without it and you can just reject this issue.

Cheers!

**Comment by mpdehaan** [comment]
Correct in that these are not intended to work for variables (nor were documented to work this way), but I understand where you are coming from :)

You may wish to use an external inventory script to populate your hosts (see API guide in docs) or code generate the INI file for them, might be easier.
