### ISSUE TITLE
service enablement change reporting not showing changed on Ubuntu 12.04 (request to revert 3315)

### ISSUE THREAD

**Issue by jongiddy** [ansible/ansible#3615]
The patches to the service module in Issue #3315 do not work on Ubuntu 12.04, the latest Long Term Support release.

The patch relies on the update-rc.d emitting lines starting with the word "rename" when changes are (or would be) made to detect whether self.changed should be true.

On Ubuntu 12.04, update-rc.d messages do not contain lines matching this pattern.

Since change detection should be conservative, preferring false indications of change to false indications of no-change, I suggest undoing this patch.

**Comment by mpdehaan** [comment]
Your request is reasonable but I'd rather hold this ticket open and fix the problem.
