### ISSUE TITLE
Issue with Loop element list in 2.5.0a1/b1/stable-2.5/devel(2.6.0)

### ISSUE THREAD

**Issue by mmercer-apixio** [ansible/ansible#36152]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible, ansible inventory

##### ANSIBLE VERSION

```
bash-4.2$ ansible --version
ansible 2.6.0
  config file = /mnt/data/devops-automation/ansible/ansible.cfg
  configured module search path = [u'/opt/devops-automation/ansible/library', u'/usr/share/ansible']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
```
bash-4.2$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/mnt/data/devops-automation/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/mnt/data/devops-automation/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=30m -o ControlPath=/opt/devops-automation/ansible/.cp/%h-%r
CACHE_PLUGIN(/mnt/data/devops-automation/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/mnt/data/devops-automation/ansible/ansible.cfg) = /opt/devops-automation/ansible/json_cache
CACHE_PLUGIN_TIMEOUT(/mnt/data/devops-automation/ansible/ansible.cfg) = 7200
COMMAND_WARNINGS(/mnt/data/devops-automation/ansible/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/mnt/data/devops-automation/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_FORKS(/mnt/data/devops-automation/ansible/ansible.cfg) = 25
DEFAULT_GATHERING(/mnt/data/devops-automation/ansible/ansible.cfg) = smart
DEFAULT_LOG_PATH(/mnt/data/devops-automation/ansible/ansible.cfg) = /opt/devops-automation/ansible/logs/ansible.log
DEFAULT_MANAGED_STR(/mnt/data/devops-automation/ansible/ansible.cfg) = {file} is managed by Ansible and was last modified: %Y-%m-%d %H:%M:%S
DEFAULT_MODULE_PATH(/mnt/data/devops-automation/ansible/ansible.cfg) = [u'/opt/devops-automation/ansible/library', u'/usr/share/ansible']
DEFAULT_ROLES_PATH(/mnt/data/devops-automation/ansible/ansible.cfg) = [u'/opt/devops-automation/ansible/roles']
DEFAULT_SCP_IF_SSH(/mnt/data/devops-automation/ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/mnt/data/devops-automation/ansible/ansible.cfg) = actionable
DEPRECATION_WARNINGS(/mnt/data/devops-automation/ansible/ansible.cfg) = True
DISPLAY_SKIPPED_HOSTS(/mnt/data/devops-automation/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/mnt/data/devops-automation/ansible/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/mnt/data/devops-automation/ansible/ansible.cfg) = /opt/devops-automation/ansible/retries
```

##### OS / ENVIRONMENT
Host: CentOS 7
Node: CentOS 7
Impact -- None

##### SUMMARY
Ansible behavior during 2.5.0 changed from an early state to the current devel state, causing an issue with inventory processing

##### STEPS TO REPRODUCE
https://gist.github.com/mmercer-apixio/01768adac98cfbd26648fe4564bba4f1

##### EXPECTED RESULTS
https://gist.github.com/mmercer-apixio/01768adac98cfbd26648fe4564bba4f1#file-error-txt-L148

Line 151 should not even exist, as that host (10.1.16.228) is *not* in the operating inventory, as can be seen in any of the other tasks, the only host that exists in the inventory at this stage is 10.1.16.181

Note that there is *no* difference between doesnt_work.yml and works.yml as far as invocation goes.  The only difference is that doesnt_work.yml is part of the complete playbook, and somehow gets the additional host at the wrong time, while works.yml was an attempt to verify any potential syntax issues with the filter expression.

##### ACTUAL RESULTS
10.1.16.228 is being operated on, but as it is not a *real* member of the inventory set, the filter *cannot* complete against it, and it errors.

Possibly related to https://github.com/ansible/ansible/issues/35845

I had discussed this issue briefly with agaffney and flowerysong, as initially, i had not realized the issue (the non present inventory item), so we were attempting to debug the filter.  At this point, it does not seem that this is at all related to the filter, but somehow associated with an inventory issue.

**Comment by mmercer-apixio** [comment]
Added a bit more information to the gist,  shows inventory creation, et cetera.

**Comment by mmercer-apixio** [comment]
I was able to go back to 2.4.3 and *reproduce* the error....  Which leaves me completely boggled.  I had been running 2.5.0 devel from git in order to get elb_target, and this has worked for months.  I copied elb_target from the amazon cloud modules into library, and ran it against 2.4.3 and it fails at the same filter expression.  It almost seems like there was something in the early stage of 2.5.0 that may have actually been broken... that i was leveraging?  I will continue to test the 2.4.x branch to see if i can find a version that works.

**Comment by mmercer-apixio** [comment]
2.4.2 reproduces as well.  It is *very* peculiar that only that *single* task shows 2 hosts though....  everything else works 'as expected'

**Comment by mmercer-apixio** [comment]
2.4.1 reproduces as well.  I think it was a 'fluke' that it worked for months on 2.5.0 (pre alpha)...

**Comment by mmercer-apixio** [comment]
I have gone back to january 4th in our ansible repo to see what could possibly have changed, because the circumstance for this is so peculiar...  Nothing that explains this behavior stands out.  I will ultimately attempt to go back to an older version and keep replaying to see if I can definitively figure out the cause.

**Comment by mmercer-apixio** [comment]
My manager managed to get an idea -- he converted the plays to set a fact first, then use the fact as the with_items loop:

```
diff --git a/roles/manage_services/tasks/loadbalancer_config.yml b/roles/manage_services/tasks/loadbalancer_config.yml
index 2912ab9..9c72c77 100644
--- a/roles/manage_services/tasks/loadbalancer_config.yml
+++ b/roles/manage_services/tasks/loadbalancer_config.yml
@@ -20,22 +20,28 @@
       target_id: "{{ facter_ec2_metadata['instance-id'] }}"
       state: present

+  - name: set the variable for old targets
+    set_fact:
+      old_targets: "{{ (alb_targets.stdout | from_json).TargetHealthDescriptions | map(attribute='Target.Id') | list }}"
+
   - name: remove original instances from ALB target group
-    elb_target:
+    elb_target:
       target_group_name: "{{ component ~ '-' ~ datacenter }}"
       target_id: "{{ item }}"
       state: absent
-    with_items: "{{ (alb_targets.stdout | from_json).TargetHealthDescriptions | map(attribute='Target.Id') | list }}"
+    with_items: "{{ old_targets }}"
+    # with_items: "{{ (alb_targets.stdout | from_json).TargetHealthDescriptions | map(attribute='Target.Id') | list }}"

   - name: setup the temporary host list for stopping consul on removed hosts
     add_host:
       hostname: "{{ groups[item][0] }}"
       groups: stop_consul
-    with_items: "{{ (alb_targets.stdout | from_json).TargetHealthDescriptions | map(attribute='Target.Id') | list }}"
+    with_items: "{{ old_targets }}"
+#    with_items: "{{ (alb_targets.stdout | from_json).TargetHealthDescriptions | map(attribute='Target.Id') | list }}"

   - name: add alb data to slack message
     set_fact:
-      alb_message: "{{ alb_message ~ ' Removed ALBs: ' ~ (alb_targets.stdout | from_json).TargetHealthDescriptions | map(attribute='Target.Id') | list}}"
+      alb_message: "{{ alb_message ~ ' Removed ALBs: ' ~ old_targets }}"

   - name: tag ec2 instance(s) for decomission
     ec2_tag:
@@ -44,7 +50,8 @@
       state: present
       tags:
         Decommissioned: "{{ btime | default('Not Provided') }}"
-    with_items: "{{ (alb_targets.stdout | from_json).TargetHealthDescriptions | map(attribute='Target.Id') | list }}"
+    with_items: "{{ old_targets }}"
+#    with_items: "{{ (alb_targets.stdout | from_json).TargetHealthDescriptions | map(attribute='Target.Id') | list }}"
   connection: local
   become: false
   tags:
@@ -63,7 +70,8 @@
       target_group_name: "{{ component ~ '-' ~ datacenter ~ '-http' }}"
       target_id: "{{ item }}"
       state: absent
-    with_items: "{{ (alb_targets.stdout | from_json).TargetHealthDescriptions | map(attribute='Target.Id') | list }}"
+    with_items: "{{ old_targets }}"
+#    with_items: "{{ (alb_targets.stdout | from_json).TargetHealthDescriptions | map(attribute='Target.Id') | list }}"
```

Now.... why in the world would the set_facts loops work, but the with items explicit calls not work?

**Comment by mmercer-apixio** [comment]
I take it noone on the team has any ideas?

**Comment by agaffney** [comment]
I don't think you really provided a complete test case for someone to be able to reproduce it. It appears that the gist from the description no longer exists, so I can't verify.

**Comment by mmercer-apixio** [comment]
unfortunately, the deletion was a misdeletion, and I can't recover it myself either.  I guess i'll close this one.  I had been checking it but had no feedback prior to yours so wasn't sure what else was needed (and only deleted the gist file in the past few days) -- it went well over 2 weeks without any feedback, which makes it difficult to maintain momentum and sanity for the situation
