### ISSUE TITLE
Allow to use the same variable name in left and right  part of variable definintion

### ISSUE THREAD

**Issue by amarao** [ansible/ansible#36171]
##### ISSUE TYPE
 - Feature request

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/amarao/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14+ (default, Feb  6 2018, 19:12:18) [GCC 7.3.0]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = %(directory)s/%%h-%%r
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = .facts
COMMAND_WARNINGS(/etc/ansible/ansible.cfg) = True
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 16
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = merge
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /tmp/ansible.log
DEFAULT_SUDO_FLAGS(/etc/ansible/ansible.cfg) = -H -S
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 59
DEFAULT_UNDEFINED_VAR_BEHAVIOR(/etc/ansible/ansible.cfg) = True
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```
##### OS / ENVIRONMENT
Ubuntu 18.04

##### DESCRIPTION
Allow to define variable to itself.

There is no way to use `somevar: {{somevar}}` in `vars` section.

Any attempt to do so fails with `recursive loop detected in template string: {{somevar}}"`.

##### RATIONALE

To pass variable to another role/template it's often to perform some small changes to it:

Example:
```
- include_role: name=somerole
  vars:
    somevar: '{{somevar + suffix}}'
    another_var: '{{another_var|default([])}}'
```

Currently a single way is to rename 'nested' variable (f.e. `somevar` -> `some_var`, or `somevar_inner`, etc), and this is very annoying.

**Comment by samdoran** [comment]
This is common in programming languages, but Ansible playbooks are not a programming language. I understand your use case, however, the way that Ansible handles variables does not allow for self referencing. Enabling this behavior would take a lot of refactoring of how Ansible handles variables and at what point they are available during play execution.

Please feel free to stop by IRC in #ansible-devel or the [mailing list](https://groups.google.com/forum/#!forum/ansible-project) if you would like to discuss this further.

**Comment by piscesvivian** [comment]
ansible is not design for people, but for fun, thanks
we design vars in dict but won't support this feature. 
so we need write a hundreds like:

spring_app1_jvm_opts: -Xms1G -Xmx2G
spring_app1_port: 1000
spring_app1_path: /usr/lib/app1

spring_app2_jvm_opts: -Xms1G -Xmx2G
spring_app2_port: 1000
spring_app2_path: /usr/lib/app2

spring_app3_jvm_opts: -Xms1G -Xmx2G
spring_app3_port: 1000
spring_app3_path: /usr/lib/app3

spring_tomcat_jvm_opts: -Xms1G -Xmx2G
spring_tomcat_port: 1000
spring_tomcat_path: /usr/lib/tomcat

spring_debug_app_jvm_opts: -Xms1G -Xmx2G
spring_debug_app_port: 1000
spring_debug_app_path: /usr/lib/debug_app

spring_debug_app2_jvm_opts: -Xms1G -Xmx2G
spring_debug_app2_port: 1000
spring_debug_app2_path: /usr/lib/debug_app2

....... more and more, and similar code, endless debug time. good luck

so use docker is a best choice, ansible is not good enough
