### ISSUE TITLE
Don't allow docs to be served with trailing slashes

### ISSUE THREAD

**Issue by ches** [ansible/ansible#3618]
I arrived at http://www.ansibleworks.com/docs/playbooks2.html/ via a Google search, and there appear to be a lot of Google results for the docs site indexed this way.

When viewing a page served this way, inter-document references break -- for example, try the link to "Inventory & Patterns" in the _Note_ for http://www.ansibleworks.com/docs/playbooks2.html/#variable-file-separation. I spent a few minutes verifying the reST labels and Sphinx `:ref:`s to see if I could submit a fix before realizing there is in fact nothing broken in the source.

**Comment by mpdehaan** [comment]
We know about this one and it's going to take a while for google to update itself to not link to things wrongly.

**Comment by ches** [comment]
FWIW, [Webmaster Tools](http://www.google.com/webmasters/tools/‎) can help you take an active role in cleaning up the index, and of course redirects so it doesn't regress...
