### ISSUE TITLE
Ansible cant manage multiple encrypted passwords in vars-file

### ISSUE THREAD

**Issue by CayoM** [ansible/ansible#36229]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

ansible-config dump --only-change
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/modules']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Ubuntu 16.04.3 LTS

##### SUMMARY

Ansible dont seems to be able to process multiple encrypted passwords contained in a vars_file. Only the first one is used, the following ones are not decrypted.

##### STEPS TO REPRODUCE

My playbook contains:

```
- hosts: management
  become: yes
  vars_files:
    - vars/mgmt.yml
    - vars/mgmt_vault.yml

  roles:
    - external/geerlingguy.mysql
    - external/geerlingguy.gogs
```

my vars_files contains:

vars/mgmt.yml

```
---
# Vault File
vault_password_file: /etc/ansible/vault-files/mgmt.txt

# MySQL Variables
mysql_packages:
  - mariadb-client
  - mariadb-server
  - python-mysqldb
mysql_root_password: "{{ vault_mysql_root_password }}"

# gogs Variables
gogs_use_mysql: true
gogs_db_name: gogs
gogs_db_username: gogs
gogs_db_password: "{{ vault_gogs_db_password }}"
```

vars/mgmt_vault.yml

```
---
vault_mysql_root_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      64333838636532626438356338323763643437316264396566333136643762613137633035306236
      6263643932396465323735316265366364303933323263320a316665653536396537363461613334
      38636162326164653338313131653432383538376235366439383832316136303364653938623236
      6161333163666464350a356561653537316464656163333336663236326635366161316436393630
      6566
vault_gogs_db_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      35656566333434353231306131366434626534333830386330633633333831356437643366643937
      3637343238373064326438643864396234366438353038650a383764633937663461663838383337
      64633264306634643638373039656464356339306662636231343132623538643239316138393866
      3739666466613761350a336462346665633663646236326363343536326239666138633463653361
      3464
```

##### EXPECTED RESULTS

since im following the best-practices for ansible vault usage, i dont know if this is really correct because every document/links only shows this example for secret-management with only one variable. I would expect to be able to use multiple encrypted passwords in a single vars_file/encrypted or unencrypted file.

##### ACTUAL RESULTS

extra verbosity doesnt show more output.

```
fatal: [mgmt]: FAILED! => {"msg": "{{ vault_gogs_db_password }}: Attempting to decrypt but no vault secrets found"}
```

**Comment by CayoM** [comment]
update:

if i instead of inserting single vault-encrypted just encrypt the whole file vars/mgmt_vault.yml it works.
So it seems its not possible to mix multiple unencrypted and encrypted variables in the same vars_file.

is this meant to be like this?

**Comment by mkrizek** [comment]
cc @alikins

**Comment by alikins** [comment]
@CayoM What does the command line invocation look like?  Are you providing multiple vault passwords?

Are the vaulted values for 'vault_mysql_root_password' and 'vault_gogs_db_password' encrypted with the same vault password or different vault passwords?

> I would expect to be able to use multiple encrypted passwords in a single vars_file/encrypted or unencrypted file.

Yup, should be able to. It should work for the case where all of the vaulted variables (the '!vault' content of 'vault_mysql_root_password' for ex) are encrypted with the same vault secret or with different vault secrets.

**Comment by CayoM** [comment]
@alikins i used the same vault-password-file to encrypt them manually. I copied the encrypted passwords then to the vars_file.

 ansible-vault encrypt_string --vault-id /etc/ansible/vault-files/mgmt.txt 'test123' --name 'mysql_root_password'
ansible-vault encrypt_string --vault-id /etc/ansible/vault-files/mgmt.txt 'blabla123' --name 'gogs_db_password'


another thing i notice:
 the variable
vault_password_file: /etc/ansible/vault-files/mgmt.txt

doesnt seem to work. It only works when calling the playbook using --vault-password-file

**Comment by alikins** [comment]
@CayoM 

> ```
> fatal: [mgmt]: FAILED! => {"msg": "{{ vault_gogs_db_password }}: Attempting to decrypt but no vault secrets found"}
> ```

I'm assuming that 'vault_mysql_root_password' decrypted correctly in this case?  

On the cli, was one or more of ('--ask-vault-pass', '--vault-password-file', '--vault-id') used?

Was this working for you prior to 2.4.3.0?

**Comment by alikins** [comment]
> another thing i notice:
> the variable
> vault_password_file: /etc/ansible/vault-files/mgmt.txt
> 
> doesnt seem to work. It only works when calling the playbook using --vault-password-file

`vault_password_file` is only a configuration option (set in 'ansible.cfg') or command line option, it can't be set in a playbook.

**Comment by CayoM** [comment]
i did some more testing here and found out the problem was related to the vault_password_file variable beeing set in the vars_file, which doesnt work. I got this missinformation from here: https://devops.stackexchange.com/questions/703/what-is-ansibles-config-equivalent-of-vault-password-file

after trying again with a dedicated vars_file/encrypted_vault.yml (which contains manually encrypted entries) and --vault-password-file option it worked.

the issue can be closed, since there is no bug and the official documentation doesnt mention "vault-password_file" possibility for playbook or vars_file.

**Comment by alikins** [comment]
I added a repro of this scenario at https://github.com/ansible/ansible/compare/devel...alikins:vault_multi_36229  

The branch above includes an example of using multiple vault passwords for different vars inside a vars file
(in https://github.com/alikins/ansible/tree/vault_multi_36229/test/integration/targets/vault/repro/multi_36229)
