### ISSUE TITLE
why doesnt my .profile doesn't load in the same -name

### ISSUE THREAD

**Issue by jeid85341** [ansible/ansible#36248]
- name: load the profile and check the status
     command: "{{ item }}"
     with_items:
         - sh ~/.profile
         - sh mycommand.sh parameter
     register: details

why doesnt my alias which was defined in .profile doesnt get called/resolved in the second script, 
I was thinking this should all run in a single shell. please help

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
