### ISSUE TITLE
Aptitude cannot be installed using apt module due to check for aptitude

### ISSUE THREAD

**Issue by jongiddy** [ansible/ansible#3625]
It is impossible to install the "aptitude" package using the "apt" module, due to aptitude now being a pre-requisite for the apt module.

Issue #3379 discusses the potential problem, and concludes that almost every OS will have aptitude installed. While this may be true on existing configured systems, it is less likely to be installed on a fresh OS installation, where Ansible is commonly used.

**Comment by mpdehaan** [comment]
I am fine with moving the check for this until the point(s) where it is used.

Let's make it so.

Something you or @serenecloud would like to work on perhaps ?

**Comment by mpdehaan** [comment]
workaround is of course (temporarily):

```
shell: apt-get install aptitude --whatever-flags-you-like
```

**Comment by mpdehaan** [comment]
fix pushed to devel, should be good to go.

**Comment by serenecloud** [comment]
Ah, I hadn't considered installing aptitude with apt, I assumed it would be done manually on a new box (like sudo). Thanks for the tag & fix @mpdehaan.
