### ISSUE TITLE
library/cloud/ec2 can't provision vpc instance with security-group-id

### ISSUE THREAD

**Issue by ralph-tice** [ansible/ansible#3626]
Commit 07bea63533ce56509231dd34b298b148ef34116d introduces a regression involving security groups that causes this error to be emitted:

```
TASK: [provision instance] ****************************************************
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1374513771.46-75304508980230 && chmod a+rx $HOME/.ansible/tmp/ansible-1374513771.46-75304508980230 && echo $HOME/.ansible/tmp/ansible-1374513771.46-75304508980230']
<127.0.0.1> REMOTE_MODULE ec2 group_id=sg-ffffffff instance_tags='{ "Name" : "vpc-nat-1e", "role" : "vpc-nat" }' keypair=mysecretkeypair instance_type=t1.micro vpc_subnet_id=subnet-ffffffff image=ami-ffffffff
<127.0.0.1> PUT /var/folders/80/1wb2rsb15yx25vtglvzhyny80000gn/T/tmpssFVBT TO /Users/ralphtice/.ansible/tmp/ansible-1374513771.46-75304508980230/ec2
<127.0.0.1> EXEC ['/bin/sh', '-c', '/usr/bin/python /Users/ralphtice/.ansible/tmp/ansible-1374513771.46-75304508980230/ec2; rm -rf /Users/ralphtice/.ansible/tmp/ansible-1374513771.46-75304508980230/ >/dev/null 2>&1']
failed: [127.0.0.1] => {"failed": true}
msg: InvalidParameterCombination: The parameter groupName cannot be used with the parameter subnet

FATAL: all hosts have already failed -- aborting
```

I'm still debugging, will update here if i figure it out.

/cc @lwade @jarv @mynameisdaniil

**Comment by mpdehaan** [comment]
Speculation in channel is that this could possibly have been a boto version issue.

**Comment by mpdehaan** [comment]
BTW, this is not a regression.  If you can show me a previous bug report about this being fixed and I might consider it to be one, but it's really immaterial.   Just report the bug :)

http://ohjeezlinux.wordpress.com/2013/01/03/new-rule-about-regressions/

**Comment by ralph-tice** [comment]
OK, so I upgraded from boto 2.9.5 to 2.9.8 and this was fixed.  Is there any intent to support non-latest versions of boto? 2.9.5 was "only" 2 months ago.

**Comment by mpdehaan** [comment]
Intent is probably a function of whether you want to send in any pull requests to do this.

**Comment by ralph-tice** [comment]
Argh, super sorry, I had reverted part of the commit listed above when I reported it fixed.  It's still broken, but I fixed it by reverting line 348 from the commit. I'll submit a PR.
