### ISSUE TITLE
ansible virtualization facts not provided on CentOS 5

### ISSUE THREAD

**Issue by perrioto** [ansible/ansible#3633]
Hi, 

I have two VMs kvm, one in centos5 and another in centos6
For centos6 with the setup module I have these facts :
        "ansible_virtualization_role": "guest",
        "ansible_virtualization_type": "kvm"
But for centos5 I have nothing.

**Comment by mpdehaan** [comment]
(sorry for confusion, reopening) 

edited this down to relevant parts (so I don't get confused again), thanks!

**Comment by jctanner** [comment]
This appears to have been resolved in the 1.2 release and higher.
