### ISSUE TITLE
optional role path or role search path

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#3647]
It would be nice to have a feature analogous to this:

ansible-playbook --rolepath /this/is/where/i/keep/my/roles

That would allow me to keep nice clean playbooks like:

  roles:
- rolea
- roleb

If this is an interesting feature and something you'd accept, I'd consider working on it.

**Comment by mpdehaan** [comment]
--extra-vars can allow passing in things like this.

I don't see this being a command line option.

I could see this being a config file option.

**Comment by mpdehaan** [comment]
Closing just to keep the github ticket orderly, as this is more of a conversation.
