### ISSUE TITLE
Host inventory information from an inventory-script is serialized and a bottleneck

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#3652]
In case you have an inventory script that can do caching, but where the caching has expired (e.g. in our case every 24 hours) and gathering the host-information can take up to 1 second, a command run using ansible on 2000 servers will take up up to 2000 seconds (i.e. about half an hour) whereas if this part was parallellized (e.g. using -f 20) it would make it 20x faster.

Even if the inventory-script would be faster (say a host-lookup would take 0.1 second) for 2000 servers that would still mean 200 seconds (about 3 minutes).

Although this does not happen frequently (at least once a day in our case) the fact that we have to wait for half an hour before continuing to use Ansible on all hosts is at the very least a nuisance in large deployments.

**Comment by dagwieers** [comment]
BTW Even when cached, a host-lookup using our inventory-script takes 0.17 secs at the moment. So it's not a theoretical issue or something we can improve on the inventory-script. The factor is the number of hosts, which is growing quickly (50+ each month is not unusual).

**Comment by mpdehaan** [comment]
Ok so there is already a feature request ticket open on this...

**Comment by dagwieers** [comment]
I didn't find it and searched through the index for "inventory", do you have a reference ?
