### ISSUE TITLE
Type conversion of variables in inventory is inconsistent

### ISSUE THREAD

**Issue by mtnbikenc** [ansible/ansible#36544]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Inventory

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/rteague/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Jan 17 2018, 14:28:32) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

##### CONFIGURATION

Default

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Inventory variables are treated differently depending on where they are defined.  If a variable is provided on the host line in an ini-style inventory, Ansible will perform automatic type conversion.  The same does not apply for variables defined in a vars group.

##### STEPS TO REPRODUCE

```
# test-inv
[masters]
localhost host_line_defined="{'host-type': 'master', 'sub-host-type': 'default', 'region': 'infra'}"

[masters:vars]
vars_group_defined="{'host-type': 'master', 'sub-host-type': 'default', 'region': 'infra'}"
```

##### EXPECTED RESULTS

It is expected that variables are treated the same regardless of where they are defined in the inventory.  This can cause issues when users define variables for hosts in different ways which result in unexpected behavior in playbooks.

##### ACTUAL RESULTS

The variable `host_line_defined` is converted to a `dict`.
The variable `vars_group_defined` remains a `string`.

```
$ ansible-inventory -i inventory/test-inv --list --yaml
all:
  children:
    masters:
      hosts:
        localhost:
          host_line_defined:
            host-type: master
            region: infra
            sub-host-type: default
          vars_group_defined: '{''host-type'': ''master'', ''sub-host-type'': ''default'',
            ''region'': ''infra''}'
    ungrouped: {}
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

I don't see that as inconsistent, the ini format does not support 'type discovery', you can use the YAML format if you care about types, though if you pass them through templating they might still be stringified:
```
vars_group_defined: {''host-type'': ''master'', ''sub-host-type'': ''default'',
            ''region'': ''infra''}
```
In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by sivel** [comment]
This does appear to be a valid bug. There is a functionality difference between `_parse_host_definition` and `_parse_variable_definition` in the `ini` plugin, that prevents variable definitions from being ast parsable.

**Comment by sivel** [comment]
It looks like the difference is that `shlex_split` removes the wrapping `"` around the right side of the variable definition:

wrapped with `shlex.split`:
```
["vars_group_defined={'host-type': 'master', 'sub-host-type': 'default', 'region': 'infra'}"]
```

Not wrapped:

```
vars_group_defined="{'host-type': 'master', 'sub-host-type': 'default', 'region': 'infra'}"
```

So we likely need to duplicate the use of `shlex.split` into `_parse_variable_definition`.

**Comment by bcoca** [comment]
sorry, missed that it 'worked on one side' ... that was probably implemented in the original ini.py parser and just copied into the current plugin. 

Only caveat, either way it is fixed ... someone is probably going to be surprised by it suddenly being typed/not typed.

**Comment by sivel** [comment]
Maybe a change like:

```diff
diff --git a/lib/ansible/plugins/inventory/ini.py b/lib/ansible/plugins/inventory/ini.py
index 82d4e1899d..765ffa90f9 100644
--- a/lib/ansible/plugins/inventory/ini.py
+++ b/lib/ansible/plugins/inventory/ini.py
@@ -273,8 +273,12 @@ class InventoryModule(BaseFileInventoryPlugin):
         # _parse_value to sort out. We should be more systematic here about
         # defining what is acceptable, how quotes work, and so on.
 
-        if '=' in line:
-            (k, v) = [e.strip() for e in line.split("=", 1)]
+        tokens = shlex_split(line)
+        if not tokens or len(tokens) > 1:
+            raise ValueError('Expected a single key=value, got: %r' % line)
+
+        if '=' in tokens[0]:
+            (k, v) = tokens[0].split("=", 1)
             return (k, self._parse_value(v))
 
         self._raise_error("Expected key=value, got: %s" % (line))
```

**Comment by bcoca** [comment]
at this point im thinking it needs to be a config toggle

**Comment by michaelgugino** [comment]
The following is not valid json:
```yaml
"{'host-type': 'master', 'sub-host-type': 'default', 'region': 'infra'}"
```

If the string above is parsed into a dictionary in the ini-style format in the hosts line, we should do it in the group line as well.  It's not usable as json in the current form.  Given that, I think the risk of properly parsing it as a dictionary is low to existing users.

I'm in favor of parsing.

**Comment by sivel** [comment]
@michaelgugino as a work around, if you unquote the value, it works as expected:

```
[masters:vars]
vars_group_defined={'host-type': 'master', 'sub-host-type': 'default', 'region': 'infra'}
```

**Comment by bcoca** [comment]
its not JSON, its python, iirc its literal_eval based.

**Comment by abadger** [comment]
This is a ui wart but not really a bug...  The format of the two lines are necessarily different.  Host lines take multiple key=value parameters per line.  Therefore they need a way to indicate that a space is part of a value rather than a separator.  In contrast, :vars are a single entry per line.  So we can tell that everything after the = is the value for the entry.

If we made these the same format, we'd end up inconveniencing people using one or the other if these formats.

**Comment by sivel** [comment]
Closing per https://github.com/ansible/ansible/issues/36544#issuecomment-367467591

If you need to ensure types, it is recommended to switch to something like the YAML or TOML inventory formats, or move definition of complex vars to `host_vars` or `group_vars`

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
