### ISSUE TITLE
when_unset does not appear to behave as documented or expected after 62b39d3d

### ISSUE THREAD

**Issue by base10** [ansible/ansible#3658]
I'm attempting to write a playbook that tests for for the presence of certain variables. Between Friday, July 19 and Monday, July 22 it appears the behavior of the when_unset conditional changed.

In short, in a reduced test case, when_unset is failing regardless of whether a var is set or unset.

I have documented my findings with the following gist: [https://gist.github.com/base10/6066475](https://gist.github.com/base10/6066475)

I tested and found that commits up to and including ca512c7 behave as I would expect them to. Commits from 62b39d3d onward do not behave as expected and documented.

**Comment by mpdehaan** [comment]
Ok, not saying this shouldn't be fixed for backwards compat reasons, but really what you should be saying here in 1.2 and later is:

when: foo is defined

when operations have the benefit of not having to do string references among other things.

Similarly, this allows more advanced things like:

when: foo is defined and foo > 12

which was impossible in the earlier conditional forms.

I should also point out that "${foo}" is quite out of style in favor of "{{ foo }}" which is consistent between playbooks and templates.

**Comment by base10** [comment]
Thanks. I'll give the recommendations a shot and report back.

**Comment by base10** [comment]
I updated as recommended, and [it doesn't appear to work](https://gist.github.com/base10/6081009) with an undefined var. I'm completely open to the possibility I'm being thick and missing something obvious.

**Comment by stoned** [comment]
Latest devel version of ansible would allow you to do the following: http://paste.debian.net/19052

**Comment by mpdehaan** [comment]
Hey Nathan,

The "when" condition is not evaluated for each step in a list, but just
once _outside_ the list.   (For instance, yum and apt when used with
'with_items' produce one large package transaction).

Thus you would want to have the when condition to check if the outer
variables are defined, like so:

```
 when: x is defined and y is defined and z is defined
```

While what stoned says is technically correct, it's beyond the threshold of
programming that I want anyone to have to go to.

Another simpler way is just:

```
- fail: msg='foo is required'
  when: foo is not defined

- fail: msg='bar is required'
  when: bar is not defined
```

Finally, there's a filter added in 1.3 that some people like:

```
"{{ x | mandatory }}"
```

Which yells if x isn't defined, right then and there:
https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/filter_plugins/core.py

I can't recall offhand if that prints out the name of the failed variable
though, but it should.

**Comment by mpdehaan** [comment]
Seeing this is now many months super-deprecated and undocumented I am going to close this one.
