### ISSUE TITLE
When listing multiple inventories, variables of the last-listed "win"

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [ansible/ansible#36600]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Inventory

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = None
  configured module search path = ['/mi/.ansible/plugins/modules', '/opt/share/ansible/plugins/modules']
  ansible python module location = /opt/lib/python3.6/site-packages/ansible
  executable location = /opt/bin/ansible
  python version = 3.6.4 (default, Dec 22 2017, 10:28:34) [GCC 4.2.1 Compatible FreeBSD Clang 5.0.0 (tags/RELEASE_500/final 312559)]
```

##### CONFIGURATION
No changes from default.

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Using the "Altnernative Directory Layout" described on the ["Best Practices Page"](http://docs.ansible.com/ansible/latest/playbooks_best_practices.html#directory-layout), I have set up multiple inventories, each with its `group_vars/` subdirectory. A couple of variables are also specified in each `hosts`-file directly.

When the inventories are used by themselves, things work as expected.

However, when I attempt to process multiple inventories in the same invocation, such as, for example:

`% ansible-inventory -i inventories/mff/prod -i inventories/mff/uat --list`

or simply:

`% ansible-inventory -i inventories/mff/  --list`

I notice, that the settings found in the `group_vars/` of the _last_-listed inventory are applied to _all_ inventories.

This seems like a bug -- ansible should be applying the variable settings found in the `hosts`-file (as well as in the `group_vars/` next to it) only to the hosts listed _there_.

This would certainly make it more useful without affecting the common (and, until recently, the _only_) use case of single inventory per invocation.

##### STEPS TO REPRODUCE
Create the following two inventory-files:
```ini
[mammals]
kangaroo

[mammals:vars]
type=marsupial
```
and
```ini
[mammals]
dog

[mammals:vars]
type=placental
```
Call `ansible-inventory -i a.ini -i b.ini --list` and then `ansible-inventory -i b.ini -i a.ini --list`. The type of each animal will be the same... Depending on the order, _both_ dog and kangaroo will either be placental or marsupial, instead of the setting found in the inventory applying only to the hosts in the inventory.

The situation is the same with each inventory having its own `group_vars/` next to it, but that makes for a messier example.

##### EXPECTED RESULTS

```json
{
    "_meta": {
        "hostvars": {
            "dog": {
                "type": "placental"
            },
            "kangaroo": {
                "type": "marsupial"
            }
        }
    },
    "all": {
        "children": [
            "mammals",
            "ungrouped"
        ]
    },
    "mammals": {
        "hosts": [
            "dog",
            "kangaroo"
        ]
    },
    "ungrouped": {}
}
```
##### ACTUAL RESULTS
```json
{
    "_meta": {
        "hostvars": {
            "dog": {
                "type": "placental"
            },
            "kangaroo": {
                "type": "placental"
            }
        }
    },
    "all": {
        "children": [
            "mammals",
            "ungrouped"
        ]
    },
    "mammals": {
        "hosts": [
            "dog",
            "kangaroo"
        ]
    },
    "ungrouped": {}
}
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Ansible only sees one inventory in the end, you can specify 'multiple sources' but they all get merged into a single inventory.  
If a host or group is referenced in more than one source, they are identified as the same host/group, any variables they define will be processed accordingly.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by UnitedMarsupials-zz** [comment]
> If a host or group is referenced in more than one source, they are identified as the same host/group, any variables they define will be processed accordingly.

In that case, an attempt to redefine the already set variable should trigger a warning or even an error.

But, although you are perfectly free to define, how you want these things to work, my argument is, the current choice is not useful.

Invoking ansible once with multiple inventories listed on command-line should result in the same variable-values as invoking it once _for each inventory_. The former can be useful as it allows for better process-control and possible cooperation between target-hosts, but it is unusable because of the problem I describe.

Unusable for no good reason -- what possible use case is there for, what possible value is there in the current behavior?

Given that the multiple-inventory feature is a recent one, maybe, it is not too late to change it yet?

**Comment by bcoca** [comment]
The feature is "multiple sources", before the only way to do this was creating symlinks into a directory and using that as the single source. As for the usefulness, there are many that had asked for it as the symlink solution did not work for them, there are many different setups in which this works, there are also many setups for which this is not a solution.

The 'core' of inventory has not changed. Ansible can only use one unified source of truth internally.
For example, if you create a play with `hosts: myhost`, but myhost is defined in 3 of the sources ... which one should i target? which vars should i load for it? The expectations you are setting have never been part of how Ansible works.

**Comment by UnitedMarsupials-zz** [comment]
> before the only way to do this was creating symlinks into a directory and using that as the single source

Ok, yes, the new feature is not _entirely_ useless. However, it is not as useful as it could've been, because it is gratuitously difficult to combine the inventories (sources) while retaining the variables.

Consider the following use-case:
- Ansible is used to manage multiple instances (Dev, UAT, QA, Production) of a distributed application
- Each application instance uses multiple servers playing different roles (database, front-end, back-end, etc.)

Now, it makes perfect sense to have an inventory for each instance of the application, with different machines grouped inside it:
- `inventories/dev1/hosts`
- `inventories/dev2/hosts`
- `inventories/production/hosts`
- `inventories/qa/hosts`
- `inventories/uat/hosts`

Some machines may even be listed in multiple inventories: for example, the same machine may be part of several development-instances...

And yet, some things -- such as user-accounts and ssh-keys, or application start/stop scripts -- can (and should!) be done to all the servers regardless of their application-instances. In these cases, why can't I run ansible with the inventory specified as just `-i inventories/`?

Oh, I can, but the group-variables will all be screwed up -- because, instead of applying the group_vars found next to each inventory-file to the machines _in that inventory_ (such as in `inventories/dev1/group_vars/` applying only to hosts listed in `inventories/dev1/hosts`), ansible will apply the last-detected group_vars (the uat's) to _all_ inventory-files.

I struggle to understand, who could possibly benefit from such an implementation, whereas what I am asking for would benefit a large number of people...

**Comment by netmonk** [comment]
Totally agree, currently trying to achieve something specific : having 3 inventories for three differents production environment (multi-tenant cloud). I defined a specific ssh relay server in each inventories, to access clients subnet. 
im trying to create an ssh config file wich match each client subnet and their relative ssh relay ip, but i cannot do that with ansible, while all information (ssh relay ip per plateform, client's subnet per platform) are in 3 inventory files. Sad.
