### ISSUE TITLE
known_hosts: add key argument

### ISSUE THREAD

**Issue by neomantra** [ansible/ansible#3665]
This was discussed in pull request #3627.   Moving it to its own issue since I don't have time to tackle it properly for a week or more.

Please include options for a raw key. Its nice that you support the resolving of hostnames to a key but doing this at runtime would circumvent the point of the known_host file. :)

example:
known_hosts: user=charlie key="sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTuAAABBBOA9j6O+vsyCY5MnTL8s6RIJijNfyOHGm/RL1MmhDlbeK4FpqZlybzZG/nQZjGm8qbpIXZjZlRhQ7Iq1UhG++Co="

this would also support using lookup like how authorized_key examples.
- specify host, with optional key; if key is not set then look it up with ssh-keyscan
- if just key is specify insert/remove it verbatim similar to authorized_key module

**Comment by steverweber** [comment]
`known_hosts: user=charlie key="{{ lookup('pipe','ssh-keyscan -t rsa test.com') }}"`

**Comment by mpdehaan** [comment]
So the known_hosts module is a seperate pull request which we did not merge yet, so a pull request to UPDATE the known hosts module does not make sense at this time.

Please either (A) update the main module if it is yours on that PR, or (B) wait until it is merged.

Feel free to comment on that other ticket about features you might like to see.
