### ISSUE TITLE
ansible shortname task detection when specifying module path

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#3668]
```
ansible-playbook -v -i ../../inventory/hosts -c paramiko -M ../../library/ setup.yml 
ERROR: ufw is not a legal parameter in an Ansible task or handler
```

but the library definitely exists:

```
ls -l ../../library/
total 32
-rw-r--r--@ 1 jmartin  staff  2734 Jul 24 09:50 bashobench
-rw-r--r--  1 jmartin  staff  4325 May 13 12:40 riakcs_creds
-rw-r--r--  1 jmartin  staff  2567 May 13 12:40 ufw
```

The only way around it for me is to make a symlink to library -> ../../library in the playbook dir.

**Comment by bcoca** [comment]
Tested this also, -M does seem to work for ansible and ansible-doc, but
fails with ansible-playbook

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
This is not an issue about -M but rather about how short name detection is used.

It's been a thing for a while actually, but yes, it should be fixed up.

**Comment by mpdehaan** [comment]
workaround is:

action: modulename ..

**Comment by mpdehaan** [comment]
Fixed per above, so closing.
