### ISSUE TITLE
lvol module int casting error

### ISSUE THREAD

**Issue by blocke** [ansible/ansible#3669]
The example for lvol provided in the Ansible Modules documentation does not appear to work.

Variants of the example:
- lvol: vg=firefly lv=test size=100%FREE

return the following Python traceback:

fatal: [xxx] => failed to parse: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1374779879.02-271577099511291/lvol", line 1043, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1374779879.02-271577099511291/lvol", line 90, in main
    size = int(size)
ValueError: invalid literal for int() with base 10: '100%FREE'

The "100%FREE" is a correctly formatted string for specifying size to the LVM tools.

**Comment by stoned** [comment]
Hi,
FYI, this had been fixed in devel version of ansible.

**Comment by mpdehaan** [comment]
yep, closing per above, thanks for reminder!
