### ISSUE TITLE
Modules with syntax errors should show in counts as failures.

### ISSUE THREAD

**Issue by bradobro** [ansible/ansible#367]
While (hopefully) not likely to happen in production, I noticed while working on some module hacks that a syntax error in a module produces something like:

fatal: [paras.utions.org] => failed to parse:   File "/var/tmp/ansible.EpslqY/sshkey", line 125

But does not register as a failure in the summary:

PLAY RECAP **********************
paras.utions.org : ok=   3 changed=   1 unreachable=   1 failed=   0 

Better, I think, to report them as failed, not Ok.

(Working off development 4e65b537da1f0c0cb3987f0679ee6c6a83f24d25)

**Comment by mpdehaan** [comment]
aligned to release 0.5

**Comment by mpdehaan** [comment]
this is showing up as an "unreachable", though me might want to rename this, it is essentially recording it correctly as a failed communication.

**Comment by bradobro** [comment]
You're essentially right: there's nothing factually wrong with "uneachable," and there's a lot wrong with exploding the number of diagnostics messages. OTOH, to ease the life of playbook and module developers, it could really reduce frustration to distinguish between the things "unreachable" means: 
- "can't reach this host," 
- "can't find this module," 
- "found the module but can't execute it" (which can be perms, syntax, dependencies), "  
- "can't find src" (for template)

**Comment by mpdehaan** [comment]
This is already shown in the output, I will not be splitting out the counts further.

-- Michael

**Comment by bradobro** [comment]
Ok
