### ISSUE TITLE
Roles with same notifications - notifications executed too many times

### ISSUE THREAD

**Issue by analytically** [ansible/ansible#3674]
See my demonstration at https://www.dropbox.com/s/5jzij0npvxh9moj/ansible-bug.tar.gz

Run with:
ansible-playbook -i hosts site.yml --tags "kibana"

**Comment by mpdehaan** [comment]
Please share this via gist or github or something so it can be read online without having to download a tarball?

I still remain skeptical of this report, but am happy to look :)

**Comment by analytically** [comment]
https://github.com/analytically/ansible-bug

**Comment by mpdehaan** [comment]
This is not a minimal example (it's a full playbook) and there's not really any output here to show what has been run twice.

If you can reproduce this with a minimal example let me know, and please include the playbook output when you do.

Thanks!
