### ISSUE TITLE
Bug: inventory_basedir doesn't work

### ISSUE THREAD

**Issue by boosh** [ansible/ansible#3682]
Using inventory_basedir in a task doesn't work. It's not populated. So there doesn't appear to be any way to get the basedir of where the ansible plays are located. E.g.:

``` yml
- name: transferring SSL certs
  local_action: command /usr/bin/rsync -e '/usr/bin/ssh -i {{ inventory_basedir }}/{{inventory_dir}}/{{ ssh_private_key }} -o passwordauthentication=no' --rsync-path='sudo /usr/bin/rsync' -a {{ inventory_basedir }}/{{inventory_dir}}/roles/webserver/files/pki {{ user }}@{{ inventory_hostname }}:/etc/pki
```

**Comment by mpdehaan** [comment]
Yep, changelog is incorrect.

It's "inventory_dir" as a variable.

Thanks, I'll update the changelog and any referencing documentation.
