### ISSUE TITLE
Role dependencies & defaults

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#3686]
Some folks would like roles to pull in content from other roles automatically.

I am envisioning it like this:

roles/foo/meta/main.yml

And in there:

```
dependencies:
   - { role: higher, x: 42, y: 12 }
   - { role: component, y: 17, z: "blippy" }
```

etc

**Comment by mpdehaan** [comment]
The idea is it would auto-include the roles to the play if not already included, ahead of the current role.

This would need to be recursive.

**Comment by drewblas** [comment]
I agree this would be highly useful.  I'm searching for a way to do this now.  For a concrete example if I have the roles:

```
- base_app_code
- webserver
- background_worker
- manual_console
- dbserver
```

Then I might want `webserver, background_server, & manual_console` to all have the `base_app_code`.  However, the `dbserver` would have no need for that.  I can't come up with any other way to specify this relationship without just duplicating `base_app_code` for every server that needs it (which is MOST, but not ALL of them)
