### ISSUE TITLE
Cloudformation module should accept AWS credentials as parameters

### ISSUE THREAD

**Issue by boosh** [ansible/ansible#3688]
The other AWS modules accept credentials passed as the parameters `ec2_access_key` and `ec2_secret_key`. It'd be useful & consistent if the cloudformation module accepted credentials like this too.

**Comment by mpdehaan** [comment]
Yes we have another ticket open about standardizing many of these and I agree CloudFormation should be similar.

**Comment by jimi-c** [comment]
The above patch has been merged in, which should resolve this issue. If you run into any further problems regarding this, please let us know. Thanks!
