### ISSUE TITLE
Running ansible-playbook with "ANSIBLE_STDOUT_CALLBACK=json" adds "to retry, use: --limit @/opt/ansible/site.retry" to the top of the output

### ISSUE THREAD

**Issue by mattthehearn** [ansible/ansible#36928]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible-playbook

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /home/mhearn/git/ansible/ansible.cfg
  configured module search path = [u'/home/mhearn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

ANSIBLE_FORCE_COLOR(/opt/ansible/ansible.cfg) = True
DEFAULT_BECOME(/opt/ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/opt/ansible/ansible.cfg) = False
DEFAULT_BECOME_METHOD(/opt/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/opt/ansible/ansible.cfg) = root
DEFAULT_HOST_LIST(/opt/ansible/ansible.cfg) = [u'/opt/ansible/hosts']
DEFAULT_VAULT_PASSWORD_FILE(/opt/ansible/ansible.cfg) = /opt/ansible/.vault_pass
DEPRECATION_WARNINGS(/opt/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/opt/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

Running ansible-playbook with "ANSIBLE_STDOUT_CALLBACK=json" adds "to retry, use: --limit @/opt/ansible/site.retry" to the top of the output when any tasks fail, breaking the json, and making it unparseable

##### STEPS TO REPRODUCE

ANSIBLE_STDOUT_CALLBACK=json ansible-playbook -C site.yml

##### EXPECTED RESULTS

Generate a json-formatted output of the playbook results.

##### ACTUAL RESULTS

It generates a json-formatted output _**plus**_ the string "to retry, use: --limit @/opt/ansible/site.retry" at the top of the output.

Output snippet:

```
        to retry, use: --limit @/opt/ansible/site.retry
{
    "plays": [
        {
            "play": {
                "id": "506b8d61-b65c-ce4e-a4de-000000000023",
                "name": "all"
            },
            "tasks": [
                {
                    "hosts": {
```

**Comment by sivel** [comment]
This is known, and we have plans to improve the situation.  Currently the `json` callback has no way to prevent that message from being displayed as that message doesn't use the callback.

You will also need to utilize `ANSIBLE_RETRY_FILES_ENABLED=0` as well to suppress that message.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
