### ISSUE TITLE
Feature Request: Export config module for Palo Alto

### ISSUE THREAD

**Issue by arkaraung1993** [ansible/ansible#36932]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.4.2.0
```

##### SUMMARY

Configuration cannot export from Palo Alto Firewall

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by kbreit** [comment]
if a module is created, I’d like to know if it will be approved since existing modules, which would be used as a base, use the requests library.

**Comment by justjais** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/PaloAltoNetworks/pan-os-ansible.

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

    IRC: #ansible on irc.freenode.net
    mailing list: https://groups.google.com/forum/#!forum/ansible-project
