### ISSUE TITLE
New option to auto-accept ssh host keys

### ISSUE THREAD

**Issue by omgjlk** [ansible/ansible#3694]
SSH can auto accept keys if desired. Ansible could to, and it sort of does if you disable host key checking. However if you have host key checking on, Ansible will lock around writing out to the known hosts file. When fork count is small this is manageable, but when fork count is high (say 750 range) the locking gets a bit intense and really slows things down.

A new option to enable auto accept of the key that would remove the lock would be useful here.

**Comment by mpdehaan** [comment]
additional summary of IRC discussion:

Suggest we add this to 

[ssh]

section of inventory file and if set we not only pass the -o option but also disable the flock calls.

**Comment by jimi-c** [comment]
Since StrictHostKeyChecking=no is already being set, for this new option do we just want to disable the file locking, or were we also thinking this would be the option that set -o UserKnownHostsFile=/dev/null?

**Comment by lwade** [comment]
cc @lorin

**Comment by omgjlk** [comment]
So I think ssh has it's own locking around the file and can do it quite well. When using the ssh connection option it would make sense to be able to auto-accept at the Ansible config level, which will set the right flags to allow ssh itself to autoaccept, and allow ssh to do it's own locking around the known hosts file.

BUT, I can' understand not wanting to expose EVERY ssh option known to man, and a line has to be drawn somewhere. I'm not hard set on this being exposed, just making a suggestion.

**Comment by jimi-c** [comment]
@j2sol and I talked this through on IRC a bit, and after looking through the code it was determined that setting host_key_checking=False corresponds to StrictHostKeyChecking=no. In that situation, ssh is still checking and writing host keys to the known_hosts file under the hood (via its own locking mechanism). Ansible only uses file locks in the ssh connection module when it is necessary to prompt the user to accept the host key, which happens only when host_key_checking=True.

So really there's nothing required here, unless we ultimately decide to add an option to allow setting -o UserKnownHostsFile=/dev/null.
