### ISSUE TITLE
Be smarter about mkdir output

### ISSUE THREAD

**Issue by omgjlk** [ansible/ansible#3695]
It appears that the calls to mkdir to create a temp directory to copy ansible module content can fail, in a way that ansible takes the fail output as the directory name, and then uses it in subsequent calls. 

Scenario would be when the remote server is out of disk space.

32766 pts/2    S+     0:00 scp -o ControlMaster=auto -o ControlPersist=3600s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ConnectTimeout=5 -o Port=22 -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o ConnectTimeout=10 /tmp/tmpG0aUle 10.21.16.120:mkdir: cannot create directory `/root/.ansible': No space left on device/get_url

**Comment by mpdehaan** [comment]
What Ansible version was this reported on BTW?  1.3 adds additional error code checking on the temp location which is why I ask.   If this was on 1.3 we need to better check the output to see if it looks like an md5sum, otherwise the rc checking code should be sufficient.

**Comment by omgjlk** [comment]
1.2

**Comment by jimi-c** [comment]
Can you try this with the head of the devel branch? I just tried it on a system where I set the users disk quote below their current usage, and this is what I got back:

<pre>
$ ansible-playbook -i hosts test.yml 
PLAY [all] ******************************************************************** 
TASK: [test 1] **************************************************************** 
fatal: [192.168.1.196] => Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-1376372921.25-276630184878237 && chmod a+rx $HOME/.ansible/tmp/ansible-1376372921.25-276630184878237 && echo $HOME/.ansible/tmp/ansible-1376372921.25-276630184878237, exited with result 1: mkdir: cannot create directory `/home/testing/.ansible/tmp/ansible-1376372921.25-276630184878237': Disk quota exceeded
FATAL: all hosts have already failed -- aborting
</pre>

So this may not be an issue anymore.

**Comment by jimi-c** [comment]
I haven't heard any follow up on this, so I'm going to close it as resolved based on my previous comment. If it's still an issue, let us know.

Thanks!
