### ISSUE TITLE
fireball2

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#3696]
In theory, it should be possible for a connection type to auto-bootstrap fireball if available without having to specially do the handoff that is now required

Further, it should be possible to detect the OS and call the right modules for auto-installing fireball deps.   As such it might just be a config setting or a play setting that says "fireball: True" rather than the whole handoff sequence.

A major goal should be replacing 0mq with just a basic socket server, to ease deps further, as 0mq has very little value add here.

(When this is done it should also be sending files in chunks, which FB does not do now)

**Comment by jimi-c** [comment]
Merged in last night, so closing this.
