### ISSUE TITLE
$FILE doesn't use role directory structure

### ISSUE THREAD

**Issue by mkaluza** [ansible/ansible#3698]
When using $FILE from a task in a role, it still wants to include a file as if it was used normally in a playbook. It would be nice if it searched files/ subdir similarly to copy action.

**Comment by mpdehaan** [comment]
Yep, though we need to do this in a way that also keeps it looking in existing locations as well.   The role basically needs to set some sort of path context on the runner object that the Runner() class can see.

BTW, the new preferred way to use this, consistent with other types of evaluation is:

```
{{ lookup('file', 'path') }}
```

**Comment by mkaluza** [comment]
Thanks for the hint - it works with roles.

**Comment by mpdehaan** [comment]
The above is fine for roles so since the old way is more or less deprecated I think we can close this one.
