### ISSUE TITLE
module Parameter defaults

### ISSUE THREAD

**Issue by henk84** [ansible/ansible#3699]
I’d like being able to set defaults for module parameters.
The one case I consider them almost necessary is the apt-module’s 'install_recommends' parameter which defaults to 'yes'. That’s a decision I usually do not make package by package, but generally disable it. So being able to set it as the default value for apt packages would really be helpful.

Thanks for consideration.

**Comment by mpdehaan** [comment]
I should update the status on this one.

This is not something we're going to actively work on, but pull requests will be considered.

It is probably worthwhile to discuss implementation on ansible-devel first.
