### ISSUE TITLE
copy fails when used with sudo_user

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#3705]
I'm getting an  error when using the copy action when specifying a sudo_user. Here's an example playbook:

```
- hosts: myserver
  sudo: True
  sudo_user: lorin
  tasks:
    - name: ensure .gitconfig file is present
      copy: src=files/.gitconfig dest=/home/lorin/.gitconfig
```

Running this returns the following error:

```
TASK: [ensure .gitconfig file is present] *************************************
failed: [myserver] => {"failed": true}
msg: Could not replace file: /tmp/ansible-1375213714.07-124608323343148/source to /home/lorin/.gitconfig: [Errno 13] Permission denied
```

Error reproduces when sudo_user is attached to either the play or the task.

I did a git-bisect, and the commit that introduced the commit appears to be dafbcf87d35bf3d1100b7ef66ee9099c2cd32814

**Comment by mpdehaan** [comment]
Let's not categorize regression or not regression, you have a bug report :)
