### ISSUE TITLE
arrays/lists are handled differently in 'with_items' depending on the place, where they are defined

### ISSUE THREAD

**Issue by mkaluza** [ansible/ansible#3712]
arrays defined in vars or vars_files work ok, while those from host/group vars and inventory (${groups.somegroup} are handled incorrectly

See attached gist (full test case with output)
https://gist.github.com/mkaluza/6121615

vars 'a' and 'c' behave correctly, while var 'b' and group 'grp' does not

**Comment by mpdehaan** [comment]
All of this is rather archaic syntax, as you can just do:

with_items: listvar

If you have a problem with that syntax let me know and we'll look into it.

**Comment by mkaluza** [comment]
Yes - I still have the same problem. Results for debug/with_items and include/with_items are inconsistent and depend on the place where listvar was defined
Playbook:

```
---
- hosts: localhost
  vars:
    a:
    - 1
    - 2
  vars_files:
  - vars_c
  tasks:
    - debug: msg="variable - $a"
    - debug: msg="variable - {{a}}"
    - debug: msg="item - $item"
      with_items: a
    - include: sub.yml var=$item
      #works
      with_items: a

    - debug: msg="variable - $b"
    - debug: msg="variable - {{b}}"
    - debug: msg="item - $item"
      with_items: b
    - include: sub.yml var=$item
      #doesn't work
      with_items: b

    - debug: msg="variable - $c"
    - debug: msg="variable - {{c}}"
    - debug: msg="item - $item"
      with_items: c
    - include: sub.yml var=$item
      #works
      with_items: c

    - debug: msg="variable - ${groups.grp}"
    - debug: msg="variable - {{groups.grp}}"
    - debug: msg="item - $item"
      with_items: groups.grp
    - include: sub.yml var=$item
      #doesn't work
      with_items: groups.grp
```

Output with my comments (===)

PLAY [localhost] *************************************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [localhost]

TASK: [debug msg="variable - 1,2"] *******************************************\* 
ok: [localhost] => {"msg": "variable - 1,2"}

TASK: [debug msg="variable - [1, 2]"] ****************************************\* 
ok: [localhost] => {"msg": "variable - [1, 2]"}

TASK: [debug msg="item - $item"] *********************************************\* 
ok: [localhost] => (item=1) => {"item": 1, "msg": "item - 1"}
ok: [localhost] => (item=2) => {"item": 2, "msg": "item - 2"}

=== this iterates correctly over listvar 'a' for include/with_items

TASK: [debug msg="sub 1"] ****************************************************\* 
ok: [localhost] => (item=1) => {"item": 1, "msg": "sub 1"}

TASK: [debug msg="sub 2"] ****************************************************\* 
ok: [localhost] => (item=2) => {"item": 2, "msg": "sub 2"}

TASK: [debug msg="variable - $b"] ********************************************\* 
ok: [localhost] => {"msg": "variable - x,y"}

TASK: [debug msg="variable - {{b}}"] *****************************************\* 
ok: [localhost] => {"msg": "variable - ['x', 'y']"}

TASK: [debug msg="item - $item"] *********************************************\* 
ok: [localhost] => (item=x) => {"item": "x", "msg": "item - x"}
ok: [localhost] => (item=y) => {"item": "y", "msg": "item - y"}

=== this one is incorrect - I expected two messages - 'sub x' and 'sub y'

TASK: [debug msg="sub b"] ****************************************************\* 
ok: [localhost] => (item=b) => {"item": "b", "msg": "sub b"}

TASK: [debug msg="variable - A,B"] *******************************************\* 
ok: [localhost] => {"msg": "variable - A,B"}

TASK: [debug msg="variable - ['A', 'B']"] ************************************\* 
ok: [localhost] => {"msg": "variable - ['A', 'B']"}

TASK: [debug msg="item - $item"] *********************************************\* 
ok: [localhost] => (item=A) => {"item": "A", "msg": "item - A"}
ok: [localhost] => (item=B) => {"item": "B", "msg": "item - B"}

TASK: [debug msg="sub A"] ****************************************************\* 
ok: [localhost] => (item=A) => {"item": "A", "msg": "sub A"}

TASK: [debug msg="sub B"] ****************************************************\* 
ok: [localhost] => (item=B) => {"item": "B", "msg": "sub B"}

TASK: [debug msg="variable - ${groups.grp}"] *********************************\* 
ok: [localhost] => {"msg": "variable - host2,host1"}

TASK: [debug msg="variable - {{groups.grp}}"] ********************************\* 
ok: [localhost] => {"msg": "variable - ['host2', 'host1']"}

TASK: [debug msg="item - $item"] *********************************************\* 
ok: [localhost] => (item=host2) => {"item": "host2", "msg": "item - host2"}
ok: [localhost] => (item=host1) => {"item": "host1", "msg": "item - host1"}

=== same problem here - it treats groups.grp as string, whereas in debug above it iterates over it correctly
TASK: [debug msg="sub groups.grp"] *******************************************\* 
ok: [localhost] => (item=groups.grp) => {"item": "groups.grp", "msg": "sub groups.grp"}

PLAY RECAP *******************************************************************\* 
localhost                  : ok=19   changed=0    unreachable=0    failed=0

**Comment by mpdehaan** [comment]
include + with_items really isn't endorsed/supported anymore (it has never worked with inventory variables for good reason, because the tasks must have the same objects for all hosts, the other parts technically DO work but are confusing when folks should switch to inventory variables).

In other words, this is expected.

You should loop inside the task instead, by putting the with_items inside there.

If you need multiple loops, there is with_nested, etc.

**Comment by gnosek** [comment]
Some of these examples have been included for completeness, but some are actually a real pain. Pushing the loops down to included files is ugly and leads to duplication (what if that included file has 20 tasks? should we decorate every one with the same "with_items"?)

I guess the problem is that Ansible (somewhat like Django templates) evaluates includes before everything else. If there was a construct that evaluated includes lazily, that would solve at least some of the quirks. To name some:
- broken include+with_items
- include nonexistent_file.yml when: False fails
- include file.yml when: False shows all tasks from the file as skipped, instead of not showing them at all

This would be roughly equivalent to replacing includes with local_action: command ansible-playbook ... but without the massive amount of suckage re-executing ansible-playbook would entail.

**Comment by mpdehaan** [comment]
including files that don't exist is not a feature I _WANT_ to have.

I've already mentioned why we want when to be conditional per task.

**Comment by mkaluza** [comment]
Now that we know how its done it makes sense why it's not working. While I think that gnosek's idea of lazy includes is nice, I'm aware that it could require significant changes in ansible's architecture.

Would it at least be possible that tags could work with include? If I understand it right, include applies when clause to every task from included file. Could it also append any tags assigned to it to all those tasks?
