### ISSUE TITLE
gather_facts on shared freebsd vps target may fail to find dmesg

### ISSUE THREAD

**Issue by dckc** [ansible/ansible#37146]
- Bug Report

##### COMPONENT NAME
platform detection

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 17 2016, 20:05:07) [GCC 6.4.0]
```

##### OS / ENVIRONMENT

controller: Ubuntu 16.04
target: FreeBSD 11.1-RELEASE on https://www.nearlyfreespeech.net/

##### SUMMARY
I have a simple `playbook.yml` with just `ping` and `inventory.yml` with one host, which happens to be a FreeBSD host. When I do `ansible-playbook -i inventory.yml playbook.yml`, I get:
`... "cmd": "/sbin/dmesg", "failed": true, "msg": "[Errno 2] No such file or directory" ...`

work-around: add `gather_facts: false` to `playbook.yml`.

##### STEPS TO REPRODUCE
full details are in
https://gist.github.com/dckc/9872524e016eaf8f32ffe02d2961c5cf

##### EXPECTED RESULTS

ok=1

##### ACTUAL RESULTS

fail

**Comment by sivel** [comment]
It isn't the ping.  A play implicitly runs the `setup` module as part of the gather facts phase.  It is failing at that location before reaching the `ping` task.

`/sbin/dmesg` is called when `/var/run/dmesg.boot` is empty or missing.  We may need to add a graceful degradation there instead of hard failing.

**Comment by bcoca** [comment]
discussed in irc, the target is a hosted image that is missing the `/sbin/dmesg` utility, this should still not be a fatal error when gathering facts, we should fix to warn/ignore the missing utilities and present only the possible facts.
