### ISSUE TITLE
Blockign people comments, BAD

### ISSUE THREAD

**Issue by nextgenthemes** [ansible/ansible#37157]
https://github.com/ansible/ansible/issues/37097

@sivel I think I was pretty clear on that I do not care to run the PPA version. But I see you are just closing off. You clearly have not even read what I posted ot thought about it.

**Comment by bcoca** [comment]
@nextgenthemes he did not block comments, he just closed the ticket based on the information in the form. You can still post on the ticket, there is no need to open ones like this one.
