### ISSUE TITLE
SSH known host checking needs to understand hashed known hosts

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#3716]
-c ssh tries to lock smartly when a host is mentioned in known hosts as it knows it will not have to add questions

In Debian Wheezy, it hashes hosts which looks like this:

|1|oklWNJl7OLmrw3EBkLTTJPtyu4U=|JU9imy/HzvGub6s8cvVIGFsNprw= ssh-rsa AAAAB3...

I have been pointed to 

http://twistedmatrix.com/trac/browser/trunk/twisted/conch/client/knownhosts.py#L305

**Comment by jimi-c** [comment]
Current work-around: set "HashKnownHosts no" in your /etc/ssh/ssh_config or .ssh/config files.

**Comment by mpdehaan** [comment]
fixed per above, so closing
