### ISSUE TITLE
Need to detect a successful deployment of VCSA

### ISSUE THREAD

**Issue by arjunprakashn** [ansible/ansible#37231]
##### ISSUE TYPE

  - Documentation Report

##### COMPONENT NAME

VCSA
##### ANSIBLE VERSION

```
ansible 2.5
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

how to detect a successful deployment of  vCenter Server Appliance ,after successful deployment of VCSA and PSC through playbooks.

##### STEPS TO REPRODUCE

I am deploying vcsa through playbook and i need to detect a successful deployment ,how can i detect ?

##### ACTUAL RESULTS

N/A

**Comment by rcarrillocruz** [comment]
Can you please confirm if you are asking how to perform that task or you are suggesting to add such howto to docs?

If docs, please describe a bit more what content you have in mind.

Regards

**Comment by Akasurde** [comment]
@arjunprakashn Could you please provide details about playbooks which you are talking about ? There is no module to provide such functionality.

**Comment by Akasurde** [comment]
@arjunprakashn Any news ?

**Comment by arjunprakashn** [comment]
hi ,I am asking how to perform task for detecting sucessfull deployement of vcsa ?

**Comment by Akasurde** [comment]
@arjunprakashn There is no module which can be used to detect VCSA deployment. Are you using any third party roles or playbook ?

**Comment by arjunprakashn** [comment]
i am using ansible-role-vcsa for deploying vcsa and i need to detect vcsa , so i am not sure how we can do? yes we don't have any playbook but how to detect successful deployment is my question

**Comment by Akasurde** [comment]
@arjunprakashn This is third party role. You may need to open a bug against the repository which provides this role.

**Comment by Akasurde** [comment]
Closing this as issue is related to external Ansible Role. I would recommend to open an issue against the original repository where this role is provided.
