### ISSUE TITLE
usage of the vcsa-role provided by ansible

### ISSUE THREAD

**Issue by arjunprakashn** [ansible/ansible#37230]
##### ISSUE TYPE

 - Documentation Report

##### ANSIBLE VERSION

```
ansible 2.5
```

##### SUMMARY
Need the proper documentation for usage of https://github.com/vmware/ansible-role-vcsa

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

NA
##### ACTUAL RESULTS

```
NA
```

**Comment by rcarrillocruz** [comment]
I'm afraid that role is not provided by Ansible, as it's within VMWare repo.
I suggest you open the PR or issue in their project.

Thanks
