### ISSUE TITLE
add a regex Jinja2 filter

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#3725]
Folks would like to do

```
foo | search(some_regex)
```

in expressions from Jinja2 and re.search does not work.

Need to test if foo.search is already avail in regular templates and then it may just be a matter of importing in playbooks to enable foo.search

**Comment by sivel** [comment]
Jinja2 does not have any regex filters.  I have written `match` and `search` filters for use in my playbooks.  However for my use case, I am returning bool().  What are others looking for?  Would you prefer match groups or are sticking with booleans sufficient?

**Comment by mpdehaan** [comment]
When statements want a True/False value, so I think that would cover nearly all of the cases, want to submit a pull request for "core.py" ?

**Comment by sivel** [comment]
Absolutely.  I am putting some final touches on the code and adding test cases.

**Comment by sivel** [comment]
Pull request has been added: https://github.com/ansible/ansible/pull/4288

**Comment by sivel** [comment]
``` shell
$ nosetests test/
.........................................................................S..............................................
----------------------------------------------------------------------
Ran 120 tests in 28.143s

OK (SKIP=1)
```

``` shell
$ nosetests -v test/TestFilters.py
test_bool_no (TestFilters.TestFilters) ... ok
test_bool_none (TestFilters.TestFilters) ... ok
test_bool_true (TestFilters.TestFilters) ... ok
test_bool_yes (TestFilters.TestFilters) ... ok
test_match_case_insensitive (TestFilters.TestFilters) ... ok
test_match_case_sensitive (TestFilters.TestFilters) ... ok
test_match_no_match (TestFilters.TestFilters) ... ok
test_quotes (TestFilters.TestFilters) ... ok
test_regex (TestFilters.TestFilters) ... ok
test_search_case_insensitive (TestFilters.TestFilters) ... ok
test_search_case_sensitive (TestFilters.TestFilters) ... ok

----------------------------------------------------------------------
Ran 11 tests in 0.005s

OK
```

**Comment by mpdehaan** [comment]
closing as we have the PR open now, thanks @sivel!

**Comment by astorije** [comment]
I could not find documentation on this on Ansible doc so I ended up looking for a regex filter on Jinja2 side... and ended up here!

Could we add that in the doc? I can submit a patch if you tell me where you want to see this appear plus anything that can help me with style (like if you see it as a new section, what kind of info, ...).

**Comment by sivel** [comment]
The regex filter docs can be found in the section at the following URL:

http://docs.ansible.com/playbooks_variables.html#other-useful-filters

**Comment by astorije** [comment]
Wow, I need better glasses... Thanks and sorry for the noise!

**Comment by kevinrivers** [comment]
Just a quick update for those that land here, the docs for these filters are now here:
http://docs.ansible.com/playbooks_filters.html#other-useful-filters

**Comment by F30** [comment]
The documentation's location changed again through #16646, it is now located at https://docs.ansible.com/ansible/playbooks_tests.html#testing-strings.
