### ISSUE TITLE
Jinja2 template setting overrides breaks on non-string values

### ISSUE THREAD

**Issue by bgw** [ansible/ansible#3726]
According to [the Ansible documentation](http://www.ansibleworks.com/docs/modules.html#template),

> You can override jinja2 settings by adding a special header to template file. i.e. `#jinja2: trim_blocks: False`

The code that handles that is in [`lib/ansible/utils/template.py`](https://github.com/ansible/ansible/blob/8cc13590b407a8bc0c9d0110e437f8c884cc695e/lib/ansible/utils/template.py#L432). It works for key-value pairs where the value should be a string, but in the example the passed value is a boolean. When using the header from the example, `"False"` is evaluated as `True`, as `bool("False") is True`.

I'm submitting this as an issue instead of a pull request, because I'm not completely sure what the best course of action would be. We could just use PyYAML here (as we're going for yaml-like syntax anyways), or we could special case booleans and numbers.

---

_Sidenote: The linked block of code that handles this doesn't put spaces after commas or around the plus operator, violating PEP-8, which is really bothering me._

**Comment by bcoca** [comment]
wow, someone else is actually using this?

I'll take a look, iirc i implemented by just dividing into strings w/o any
regards to type.

On Thu, Aug 1, 2013 at 3:56 PM, Benjamin Woodruff
notifications@github.comwrote:

> According to the Ansible documentationhttp://www.ansibleworks.com/docs/modules.html#template
> ,
> 
> You can override jinja2 settings by adding a special header to template
> file. i.e. #jinja2: trim_blocks: False
> 
> The code that handles that is in lib/ansible/utils/template.pyhttps://github.com/ansible/ansible/blob/8cc13590b407a8bc0c9d0110e437f8c884cc695e/lib/ansible/utils/template.py#L432.
> It works for key-value pairs where the value should be a string, but in the
> example the passed value is a boolean. When using the header from the
> example, "False" is evaluated as True, as bool("False") is True.
> 
> I'm submitting this as an issue instead of a pull request, because I'm not
> completely sure what the best course of action would be. We could just use
> PyYAML here (as we're going for yaml-like syntax anyways), or we could
> 
> ## special case booleans and numbers.
> 
> _Sidenote: The linked block of code that handles this doesn't put spaces
> after commas or around the plus operator, violating PEP-8, which is really
> bothering me._
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/3726
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
closing per above, thanks
