### ISSUE TITLE
Allow sudo and sudo_user in delegate_to

### ISSUE THREAD

**Issue by mkaluza** [ansible/ansible#3734]
When installing and setting up some app now we need to use three plays instead of one, because usually it involves creating a database on different host and different user. It would be nice if we could do 
delegate_to: dbhost sudo=yes sudo_user=db_owner

(syntax is just an example)

**Comment by mpdehaan** [comment]
You can already do this

```
- action: foo bar=1 baz=2
  delegate_to: foo
  sudo: True
  sudo_user: bar
```
