### ISSUE TITLE
set_fact lookup plugin doesn't play nice with lookup plugins

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#3735]
Given this example play:

``` yaml
- hosts: localhost
  gather_facts: False
  tasks:

  - set_fact: VM_DATASTORE="test1"
  - debug: msg={{VM_DATASTORE}}

  - set_fact: VM_DATASTORE={{ item }}
    with_random_choice:
    - randomtest1_A
    - randomtest1_B
  - debug: msg={{ VM_DATASTORE }}

  - set_fact: VM_DATASTORE="test2"
  - debug: msg={{VM_DATASTORE}}

  - set_fact: VM_DATASTORE={{ lookup('random_choice', ('randomtest2_A', 'randomtest2_B') )}} 
  - debug: msg={{ VM_DATASTORE }}
```

Output: 

``` bash
PLAY [localhost] ************************************************************** 

TASK: [set_fact VM_DATASTORE="test1"] ***************************************** 
ok: [localhost] => {"ansible_facts": {"VM_DATASTORE": "test1"}}

TASK: [debug msg={{VM_DATASTORE}}] ******************************************** 
ok: [localhost] => {"msg": "test1"}

TASK: [set_fact VM_DATASTORE={{item}}] **************************************** 
ok: [localhost] => (item=randomtest1_A) => {"ansible_facts": {"VM_DATASTORE": "randomtest1_A"}, "item": "randomtest1_A"}
ok: [localhost] => (item=randomtest1_B) => {"ansible_facts": {"VM_DATASTORE": "randomtest1_B"}, "item": "randomtest1_B"}

TASK: [debug msg={{VM_DATASTORE}}] ******************************************** 
ok: [localhost] => {"msg": "test1"}

TASK: [set_fact VM_DATASTORE="test2"] ***************************************** 
ok: [localhost] => {"ansible_facts": {"VM_DATASTORE": "test2"}}

TASK: [debug msg={{VM_DATASTORE}}] ******************************************** 
ok: [localhost] => {"msg": "test2"}

TASK: [set_fact VM_DATASTORE=randomtest2_B] *********************************** 
ok: [localhost] => {"ansible_facts": {"VM_DATASTORE": "randomtest2_A"}}

TASK: [debug msg={{VM_DATASTORE}}] ******************************************** 
ok: [localhost] => {"msg": "randomtest2_A"}

PLAY RECAP ******************************************************************** 
localhost                  : ok=8    changed=0    unreachable=0    failed=0   
```

As you can see, there is a problem when setting a fact in the second set_fact task, using the with_ construct.

My guess it's not assigned as a fact as the result set is encapsulated in a {result: { ...} } dict.

Workaround, using the {{ lookup () }} syntax works. I'm not sure if there 's an elegant solution to make it work both ways though.

**Comment by rishid** [comment]
Isn't the lookup one broken too?

```
TASK: [set_fact VM_DATASTORE=randomtest2_B] *********************************** 
ok: [localhost] => {"ansible_facts": {"VM_DATASTORE": "randomtest2_A"}}
```

TASK print out says setting to B but verbose logging says it is getting set to A.

**Comment by srgvg** [comment]
@rishid hm, that's actually a bug in my playbook, that makes the task 'name' having it's var resolved:

I should have noted:

``` yaml
- set_fact: VM_DATASTORE={{ lookup('random_choice', ( [ 'randomtest2_A', 'randomtest2_B' ] ) ) }} 
- debug: msg={{ VM_DATASTORE }}
```

Note the addional [ ] brackets, making it a list instead of comma-separated strings (which the lookup plugin happens to listify I guess).

**Comment by mpdehaan** [comment]
The bug reported is not the actual issue.

You need to set a name for the task.

If a task does not set a name, the TASK is set for the name, and in this case the lookup task will run twice

The actual assignment is running fine here.

Optionally we could disable lookup plugins for printing "name" lines.

**Comment by srgvg** [comment]
I added names to all those tasks, that doesn't make a difference. Notice though, the point was not the names, but the debug output.

See http://pastie.org/8200070

Look at line 10, which returns "ansible_facts": {"VM_DATASTORE": "randomtest1_A"}
Then look at line 13, showing  => {"msg": "test1"}, which is still the value of the preceding set_fact.
