### ISSUE TITLE
change 'include' with 'when' behavior

### ISSUE THREAD

**Issue by mkaluza** [ansible/ansible#3736]
Often in roles/main.yml we use - 'include' with 'when' to conditionally execute multiple statements. It seems that despite 'when' condition being false ansible includes the file anyway and then skips all the tasks from it. While it works ok, it has two disadvantages
- if the file doesn't exist, ansible will crash even if it doesn't really need it.
  - output of the playbook is less readable and confusing

**Comment by srgvg** [comment]
This is expected behavior: the when clause is not a conditional to the include, but is actually appended to every task.

As you can use inventory variables in conditionals, those can only be evaluated at run(ner) time, and not when the playbook is parsed.

**Comment by mpdehaan** [comment]
You should use the 'group_by' task to create dynamic groups if you want to avoid this behavior.

The conditional is definitely per host so the skipped logic is useful and neccessary here.
