### ISSUE TITLE
Cannot return a dict from custom facts

### ISSUE THREAD

**Issue by gnosek** [ansible/ansible#3737]
I tried to expose the environment (for whatever reason) via a dictionary in ansible facts, but the returned dictionary seems empty from templates. Running the fact module from the command line returns a nicely formatted nested dict with the expected contents.

Details on reproducing the issue: https://gist.github.com/gnosek/6139435

**Comment by mpdehaan** [comment]
This can't be quite true, because TONS of people's modules use custom facts, as does setup.py

I've always done: 

action: my_facts

But your syntax should be fine there.

Let's bring this up on the mailing list so we can walk through it.
