### ISSUE TITLE
No error was reported when "tasks" was written twice in a play and unusual output of it

### ISSUE THREAD

**Issue by GulshanPrasad** [ansible/ansible#37384]
##### ISSUE TYPE

 - Bug Report
When I by mistake wrote "tasks" section twice in a play, no error was reported in syntax check.Moreover, when i ran that playbook with two "tasks" section in a play, having one task in each "tasks" section, then, first task of first "task" section did not run at all, only second task of second "task" section ran.

 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by Akasurde** [comment]
@GulshanPrasad Thanks for reporting this issue. Could you please provide `-vvvv` output and playbook that you are using ?

needs_info

**Comment by GulshanPrasad** [comment]
Thanks Abhijeet for quick response
I understood the issue.
When we write "tasks" twice in one play
second task is listened because I saw a warning saying
"duplicate dict key: tasks detected, using the last dict key"

Thanks

**Comment by Akasurde** [comment]
Thanks. Closing this issue. If issue persists, please feel free to re-open.
