### ISSUE TITLE
Add depth=N option to git module

### ISSUE THREAD

**Issue by sfromm** [ansible/ansible#374]
Add depth=N option to git module to allow for shallow clones.  This could then be used with ansible-pull to minimize the history cloned/pulled.  Can wait for after 0.4

**Comment by mpdehaan** [comment]
I assume you want these tickets you've opened assigned to you?  I'm putting them in the 0.5 bucket.

**Comment by sfromm** [comment]
On Fri, May 11, 2012 at 4:50 PM, Michael DeHaan <
reply@reply.github.com

> wrote:
> 
> I assume you want these tickets you've opened assigned to you?  I'm
> putting them in the 0.5 bucket.

Sure, I'll take them.  Opening the issues was more an act of getting them
out of my head.

sf

**Comment by mpdehaan** [comment]
amen to that.  Need that free space for other computations :)

**Comment by mpdehaan** [comment]
no movement on this one, so closing RFEs, just want bugs in the tracker if they are just ideas

**Comment by sfromm** [comment]
ditto.  been swamped with other things.  :-(
