### ISSUE TITLE
Variable Loading Messages

### ISSUE THREAD

**Issue by hanej** [ansible/ansible#37408]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jhane/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = False
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=no -o ControlPersist=60s
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = %(directory)s/ansible-ssh-%%h-%%p-%%r
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = /var/lib/awx/fact_cache
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 3600
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_GATHER_SUBSET(/etc/ansible/ansible.cfg) = all,!facter
DEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /home/jhane/.ansible/tmp/ansible-local-4051_xOAPF
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Ansible managed
DEFAULT_REMOTE_TMP(/etc/ansible/ansible.cfg) = ~/.ansible/tmp
DEFAULT_SCP_IF_SSH(/etc/ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = skippy
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 10
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT
RHEL 6/7

##### SUMMARY
There seems to be constant confusion with the order of how Ansible applies variables (inventory variables, group_vars, role vars, etc).  Please provide debug messages that show the loading order of variables.  A `--list-variable-order` would be a great addition too.  Hiera does this very well with Puppet.  This will clear up a lot of confusion and will help in designing variable loading strategies.

**Comment by dougthor42** [comment]
I came here to submit a similar request: a simple `--list-vars` or `--list-variables` option for `ansible` and `ansible-playbook`. I'd imagine that it would solve this issue, at least to some extent, by letting users verify that their variables are what they expect.

## Example:

### The Command
Listing all the variables 
```shell
$ ansible-playbook -i ./hosts dummy_playbook.yml --list-vars

playbook: dummy_playbook.yml

  host bar.example.com. applied variables (2):
    ansible_python_interpreter: /usr/bin/python3   (from group: linux)
    zabbix_server_ip: 192.168.1.1/32   (from group: linux)
  host foo.example.com   applied variables (2):
    ansible_python_interpreter: /usr/bin/python3   (from group: linux)
    zabbix_server_ip: 192.168.1.1/32   (from group: linux)
  host old_1.example.com   applied variables (3):
    ansible_python_interpreter: /usr/bin/python2   (from group: legacy)
    os_version: 12.04   (from group: legacy)
    zabbix_server_ip: 192.168.1.1/32   (from group: linux)
  host old_2.example.com   applied variables (3):
    ansbile_port: 5555   (from host: old_2.example.com)
    ansible_python_interpreter: /usr/bin/python2   (from group: legacy)
    os_version: 12.04   (from group: legacy)
    zabbix_server_ip: 192.168.1.1/32   (from group: linux)
  host one.example.com   applied variables (2):
    ansible_python_interpreter: /usr/bin/python3   (from group: linux)
    zabbix_server_ip: 192.168.1.1/32   (from group: linux)
  host three.example.com   applied variables (2):
    ansible_python_interpreter: /usr/bin/python3   (from group: linux)
    zabbix_server_ip: 192.168.1.1/32   (from group: linux)
  host two.example.com   applied variables (2):
    ansible_python_interpreter: /usr/bin/python3   (from group: linux)
    zabbix_server_ip: 192.168.1.1/32   (from group: linux)
```

Listing variables for a specific host uses the existing `--limit` arg:
```shell
$ ansible-playbook -i ./hosts dummy_playbook.yml --list-vars --limit old_2.example.com

playbook: dummy_playbook.yml

  host old_2.example.com   applied variables (3):
    ansbile_port: 5555   (from host: old_2.example.com)
    ansible_python_interpreter: /usr/bin/python2   (from group: legacy)
    os_version: 12.04   (from group: legacy)
    zabbix_server_ip: 192.168.1.1/32   (from group: linux)
```

## Discussion/Questions
1. Note that in the examples here, the hosts and variables are sorted alphabetically. This is not a requirement, but I think it makes finding an item of interest much easier.
2. The group or host that provides the variable should be listed. This would help with debugging.
3. The variable value should be listed.
4. Grouping. The above example lists variables grouped by hosts. It might be better to group hosts by variables, like so (If we really want to get fancy, there could be an arg or it could auto-decide based on the number of hosts or variables, but that's out of scope):
    ```
    ansible_port: 5555   hosts (1)   from host: old_2.example.com
      old_2.example.com
    ansible_python_interpreter: /usr/bin/python2   hosts (2)   from group: legacy
      old_1.example.com
      old_2.example.com
    ansible_python_interpreter: /usr/bin/python2   hosts (5)   from group: linux
      bar.example.com
      foo.example.com
      one.example.com
      three.example.com
      two.example.com
    os_version: "12.04"   hosts (1)   from group: legacy
      old_2.example.com
    zabbix_server_id: "192.168.1.1/32"   hosts (7)   from group: linux
      bar.example.com
      foo.example.com
      old_1.example.com
      old_2.example.com
      one.example.com
      three.example.com
      two.example.com
    ```
5. Formatting. Some variables might be long. It might be better to put things like "from group/host" on a new line.
6. Color coding would be nice, but not required.
7. Should variables provided by the playbook be included? I'm not sure...
8. Note that the `mail.example.com` hosts is not listed in any of the above examples - it doesn't have any variables set in the hosts file (see below).

## Files used to generate the examples
These are the files that were used to generate the examples, above.

### Hosts file
```
mail.example.com

[linux]

[linux:vars]
ansible_python_interpreter=/usr/bin/python3
zabbix_server_ip="192.168.1.1/32"

[linux:children]
webservers
dbservers
legacy

[webservers]
foo.example.com
bar.example.com

[dbservers]
one.example.com
two.example.com
three.example.com

[legacy]
old_1.example.com
old_2.example.com ansible_port=5555

[legacy:vars]
ansible_python_interpreter=/usr/bin/python2
os_version="12.04"
```

### dummy_playbook.yml
```yaml
- hosts: linux
  remote_user: me
  become: no
  tasks:
    - name: Play a game of ping pong
      ping:
        data: pong          # yes, I know this is not needed.
```

**Comment by bcoca** [comment]
FYI `ansible-inventory --graph --vars`

```
@all:
  |--@linux:
  |  |--@dbservers:
  |  |  |--one.example.com
  |  |  |--three.example.com
  |  |  |--two.example.com
  |  |--@legacy:
  |  |  |--old_1.example.com
  |  |  |--old_2.example.com
  |  |  |  |--{ansible_port = 5555}
  |  |  |--{ansible_python_interpreter = /usr/bin/python2}
  |  |  |--{os_version = 12.04}
  |  |--@webservers:
  |  |  |--bar.example.com
  |  |  |--foo.example.com
  |  |--{ansible_python_interpreter = /usr/bin/python3}
  |  |--{zabbix_server_ip = 192.168.1.1/32}
  |--@ungrouped:
  |  |--mail.example.com

```

**Comment by dougthor42** [comment]
@bcoca Well hot damn! My Google-fu was apparently lacking, sorry for the trivial question. That's pretty much exactly what I was looking for. Thanks a bunch!

Is that command also supposed to pull in variables from the `group_vars` folder?

If so, either I have a fundamental misunderstanding of things (likely) or it doesn't appear to be working as intended (probably less likely). Below is the example. Note that the `http_port: 8080` value is not listed under the `dbservers` group (even when adding the `--playbook-dir=.` option):

```
$ pwd
/home/dthor/ansible_test
$ tree
.
├── group_vars
│   └── webservers.yml
├── hosts                        # same as before
└── site.yml                     # dummy_playbook.yml renamed to site.yml
$ cat group_vars/webservers.yml
http_port: 8080
$ ansible-inventory -i hosts --graph --vars -vvvvv
ansible-inventory 2.5.0
  config file = None
  configured module search path = ['/home/dthor/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]
No config file found; using defaults
setting up inventory plugins
Parsed /home/dthor/ansible_test/hosts inventory source with ini plugin
@all:
  |--@linux:
  |  |--@dbservers:
  |  |  |--one.example.com
  |  |  |--three.example.com
  |  |  |--two.example.com
  |  |--@legacy:
  |  |  |--old_1.example.com
  |  |  |--old_2.example.com
  |  |  |  |--{ansible_port = 5555}
  |  |  |--{ansible_python_interpreter = /usr/bin/python2}
  |  |  |--{os_version = 12.04}
  |  |--@webservers:
  |  |  |--bar.example.com
  |  |  |--foo.example.com
  |  |--{ansible_python_interpreter = /usr/bin/python3}
  |  |--{zabbix_server_ip = 192.168.1.1/32}
  |--@ungrouped:
  |  |--mail.example.com
```

**Comment by bcoca** [comment]
looks like bug

**Comment by bcoca** [comment]
this seems to fix it:
```
diff --git a/lib/ansible/cli/inventory.py b/lib/ansible/cli/inventory.py
index d5fefadbf4..008fc74131 100644
--- a/lib/ansible/cli/inventory.py
+++ b/lib/ansible/cli/inventory.py
@@ -301,7 +300,7 @@ class InventoryCLI(CLI):
                 result.append(self._graph_name(host.name, depth))
                 result.extend(self._show_vars(host.get_vars(), depth + 1))

-        result.extend(self._show_vars(group.get_vars(), depth))
+        result.extend(self._show_vars(self._get_group_variables(group), depth))
```

**Comment by dougthor42** [comment]
Yup, that worked for me too. I guess I won't open a new issue then. 😄

**Comment by Akasurde** [comment]
Closing this issue since PR #38744 is merged. Please feel free to open a new issue if problem persists.
