### ISSUE TITLE
ec2 module incorrectly returns changed=True when there is no change

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#3746]
If I invoke the ec2 module multiple times with the `id` parameter set, then it will return `changed=True` every time, even if there are no changes on the subsequent calls.

It looks like the module is hard-coded to always return `changed=True`.

**Comment by mpdehaan** [comment]
Thanks for this.

BTW, if you are going to submit a PR there is no need to also open the other ticket, leaves me with 2x the tickets in the queue since the PR is also a ticket.
