### ISSUE TITLE
constructed inventory compose only string variables

### ISSUE THREAD

**Issue by lufik** [ansible/ansible#37467]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
constructed

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
ANSIBLE_INVENTORY_ENABLED=yaml,constructed

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The variable created via constructed plugin using compose is everytime unicode string.
Debug module shows dictionary/list ok but internally it's unicode string so if I try to access
value in dictionary I get VARIABLE IS NOT DEFINED or just char at index instead of value
in list.

##### STEPS TO REPRODUCE
inventory yaml (inventory/host.yml):
```yaml
all:
  hosts:
    localhost:
```
inventory constructed (inventory/z_constructed.config):
```yaml
plugin: constructed
strict: False

compose:
  vdict: "{ 'key': 'value' }"
  vlist: "[ 'one', 'two' ]"
  vstr:  "'string'"
```

playbook (test.yml):
```yaml
- hosts: localhost
  tasks:
    - name: Dump Str
      debug: var=vstr

    - name: Dump Dict
      debug: var=vdict
    - name: Dump Dict value
      debug: var=vdict.key

    - name: Dump List
      debug: var=vlist
    - name: Dump List value
      debug: var=vlist[0]
```

Run:
ANSIBLE_INVENTORY_ENABLED=yaml,constructed ansible-playbook -i inventory test.yml

##### EXPECTED RESULTS
```
PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Dump Str] ****************************************************************
ok: [localhost] => {
    "vstr": "string"
}

TASK [Dump Dict] ***************************************************************
ok: [localhost] => {
    "vdict": {
        "key": "value"
    }
}

TASK [Dump Dict value] *********************************************************
ok: [localhost] => {
    "vdict.key": "value"
}

TASK [Dump List] ***************************************************************
ok: [localhost] => {
    "vlist": [
        "one", 
        "two"
    ]
}

TASK [Dump List value] *********************************************************
ok: [localhost] => {
    "vlist[0]": "one"
}

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0   
```

##### ACTUAL RESULTS
```
PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Dump Str] ****************************************************************
ok: [localhost] => {
    "vstr": "string"
}

TASK [Dump Dict] ***************************************************************
ok: [localhost] => {
    "vdict": {
        "key": "value"
    }
}

TASK [Dump Dict value] *********************************************************
ok: [localhost] => {
    "vdict.key": "VARIABLE IS NOT DEFINED!"
}

TASK [Dump List] ***************************************************************
ok: [localhost] => {
    "vlist": [
        "one", 
        "two"
    ]
}

TASK [Dump List value] *********************************************************
ok: [localhost] => {
    "vlist[0]": "["
}

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0   
```

**Comment by bcoca** [comment]
You are specifically creating them as strings:
```
compose:
  vdict: "{ 'key': 'value' }"
  vlist: "[ 'one', 'two' ]"

```

if you want a dict or a list:
```
  vdict: { 'key': 'value' }
  vlist: [ 'one', 'two' ]
```

**Comment by lufik** [comment]
Take a look I have to specify "'string'" (quote and apostrophe) for string value - otherwise it gets it as a variable name. Compose gives everything into {{ }} for jinja2 templating.

I find the problem using my own filter creating dictionary. It works from group_vars but it doesn't work from compose.

This is the result of what you mentioned:
PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Dump Str] ****************************************************************
ok: [localhost] => {
    "vstr": "string"
}

TASK [Dump Dict] ***************************************************************
ok: [localhost] => {
    "vdict": "VARIABLE IS NOT DEFINED!"
}

TASK [Dump Dict value] *********************************************************
ok: [localhost] => {
    "vdict.key": "VARIABLE IS NOT DEFINED!"
}

TASK [Dump List] ***************************************************************
ok: [localhost] => {
    "vlist": "VARIABLE IS NOT DEFINED!"
}

TASK [Dump List value] *********************************************************
ok: [localhost] => {
    "vlist[0]": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0

**Comment by lufik** [comment]
Exactly from documentation:
server_type: "ansible_hostname | regex_replace ('(.{6})(.{2}).*', '\2')"

When I change "strict: True" I get this output with your suggested change:
ERROR! Could not parse inventory source /ansible/test/constructed_compose_iter/inventory/z_constructed.config with available plugins:
Plugin constructed failed: failed to parse /ansible/test/constructed_compose_iter/inventory/z_constructed.config: Could set vlist: template error while templating string: expected token ',', got 'string'. String: {{[u'one', u'two']}} 

When I commented out vlist definition the error message changes to:

ERROR! Could not parse inventory source /ansible/test/constructed_compose_iter/inventory/z_constructed.config with available plugins:
Plugin constructed failed: failed to parse /ansible/test/constructed_compose_iter/inventory/z_constructed.config: Could set vdict: template error while templating string: expected token ':', got 'string'. String: {{{u'key': u'value'}}}

**Comment by bcoca** [comment]
which leads me to .. why are you 'composing' static values? the feature is designed for dynamic creation.

Also, adding a filter should fix the above `|list` or `|dict`

**Comment by lufik** [comment]
I'm using filter in my use case and the result is dynamic. I provided minimal reproducible test case.

It doesn't work without quotes (can I stop testing it without quotes?):
```
ERROR! Could not parse inventory source /ansible/test/constructed_compose_iter/inventory/z_constructed.config with available plugins:
Plugin constructed failed: Unable to parse /ansible/test/constructed_compose_iter/inventory/z_constructed.config: Syntax Error while loading YAML.


The error appears to have been in '/ansible/test/constructed_compose_iter/inventory/z_constructed.config': line 6, column 29, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  vdict: { 'key': 'value' }
  vlist: [ 'one', 'two' ] | list
                            ^ here

exception type: <class 'yaml.scanner.ScannerError'>
exception: while scanning a block scalar
  in "<unicode string>", line 6, column 27
did not find expected comment or line break
  in "<unicode string>", line 6, column 29
```

it doesn't work with "| list" (dict filter doesn't exist so I used only "| list"):
```
PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Dump Str] ****************************************************************
ok: [localhost] => {
    "vstr": "string"
}

TASK [Dump Dict] ***************************************************************
ok: [localhost] => {
    "vdict": {
        "key": "value"
    }
}

TASK [Dump Dict value] *********************************************************
ok: [localhost] => {
    "vdict.key": "VARIABLE IS NOT DEFINED!"
}

TASK [Dump List] ***************************************************************
ok: [localhost] => {
    "vlist": [
        "one", 
        "two"
    ]
}

TASK [Dump List value] *********************************************************
ok: [localhost] => {
    "vlist[0]": "["
}

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0
```

**Comment by lufik** [comment]
I tried much more to make it work. I played with it more than one day. I also tried to take a look into the code but I don't understand the internals enough to find the root cause.

Feel free to mark it as feature request if you don't like it as bug report.

**Comment by bcoca** [comment]
sorry about the no quotes, that was just 'yaml typing', I had forgotten that those are always templated.

I'll look into the rest, there is no reason why the type should be lost in the end if you tell jinja2 to use one.

**Comment by AlanCoding** [comment]
I may have hit this with the `ec2_state_code`. I need to use compose to re-produce this variable which was given by the old contrib inventory script.

So we used

```yaml
compose:
  ec2_state_code: state.code
```

This variable is actually an integer when the compose logic gets it, but it is returned as a string. Even when I try adding `| int`, it still returns as a string.

Practically, the value is:

```json
{"ec2_state_code": "16"}
```

The old script would give

```json
{"ec2_state_code": 16}
```

There seems to be no way to get the integer out of the compose variables.

**Comment by jctanner** [comment]
Test playbook:
```
- hosts: localhost
  gather_facts: False
  tasks:

    - name: Dump Str
      debug: var=vstr
    - name: Dump Str
      debug:
        msg: "{{ vstr|type_debug }}"

    - name: Dump Dict
      debug: var=vdict
    - name: Dump Dict
      debug:
        msg: "{{ vdict|type_debug }}"

    - name: Dump Dict value
      debug: var=vdict.key
    - name: Dump Dict value
      debug:
        msg: "{{ vdict.key|type_debug }}"

    - assert:
        that:
            - "vdict.key == 'value'"

    - name: Dump List
      debug: var=vlist
    - name: Dump List
      debug:
        msg: "{{ vlist|type_debug }}"

    - name: Dump List value
      debug: var=vlist[0]
    - name: Dump List value
      debug:
        msg: "{{ vlist[0]|type_debug }}"
```

version | rc
------ | ------
v2.4.0.0-0.1.rc1 |  2
v2.4.0.0-0.2.rc2 |  2
v2.4.0.0-0.3.rc3 |  2
v2.4.0.0-0.4.rc4 |  2
v2.4.0.0-0.5.rc5 |  2
v2.4.0.0-1 |  2
v2.4.1.0-0.3.rc1 |  2
v2.4.1.0-0.4.rc2 |  2
v2.4.1.0-1 |  2
v2.4.2.0-0.5.rc1 |  2
v2.4.2.0-1 |  2
v2.4.3.0-0.4.rc1 |  2
v2.4.3.0-0.5.rc2 |  2
v2.4.3.0-0.6.rc3 |  2
v2.4.3.0-1 |  2
v2.4.4.0-0.3.rc2 |  2
v2.4.4.0-1 |  2
v2.4.4-0.2.rc1 |  2
v2.4.5.0-0.1.rc1 |  2
v2.4.5.0-1 |  2
v2.4.6.0-1 |  2
v2.6.0 |  0
v2.6.0a1 |  0
v2.6.0a2 |  0
v2.6.0rc1 |  0
v2.6.0rc2 |  0
v2.6.0rc3 |  0
v2.6.0rc4 |  2
v2.6.0rc5 |  0
v2.6.1 |  0
v2.6.2 |  0
v2.6.3 |  0
v2.6.4 |  0
v2.6.5 |  0
v2.6.6 |  0
v2.6.7 |  0
v2.6.8 |  0
v2.6.9 |  0
v2.6.10 |  0
v2.6.11 |  0
v2.6.12 |  0
v2.6.13 |  0
v2.7.0 |  0
v2.7.0.a1 |  0
v2.7.0b1 |  0
v2.7.0rc1 |  0
v2.7.0rc2 |  0
v2.7.0rc3 |  0
v2.7.0rc4 |  0
v2.7.1 |  0
v2.7.2 |  0
v2.7.3 |  1
v2.7.4 |  0
v2.7.5 |  0
v2.7.6 |  0
v2.7.7 |  0
v2.5.0a1 |  2
v2.5.0b1 |  2
v2.5.0b2 |  2
v2.5.0rc1 |  2
v2.5.0rc2 |  2
v2.5.0rc3 |  2
v2.5.0 |  2
v2.5.1 |  0
v2.5.2 |  0
v2.5.3 |  0
v2.5.4 |  0
v2.5.5 |  0
v2.5.6 |  0
v2.5.7 |  0
v2.5.8 |  0
v2.5.9 |  0
v2.5.10 |  0
v2.5.11 |  0
v2.5.12 |  0
v2.5.13 |  0
v2.5.14 |  0
devel-1da5e21289 |  0

**Comment by jctanner** [comment]
The bug in the original description was fixed in v2.5.1 and has remained working ever since, aside from a brief regression in v2.7.3.

**Comment by jctanner** [comment]
```
[jtanner@jtw530 AP-37467.b]$ tree  .
.
├── ansible.cfg
├── ansible.version
├── inventory
│   ├── host.yml
│   └── z_constructed.yml
├── report.sh
├── report.txt
├── site.yml
├── test.retry
├── test.sh
└── test.yml
```

**Comment by jctanner** [comment]
@AlanCoding the issue you've described is not a problem within the constructed feature, but it is a problem with the design of jinja. Jinja will always return strings and Ansible has to guess during post processing what the "correct" type is and can very often be wrong. The solution for that problem will always be to enable native types so that jinja returns the real datastructure instead of a casted string.

http://jinja.pocoo.org/docs/2.10/nativetypes/

**Comment by AlanCoding** [comment]
Confirmed, with my examples. Our take-away here is that we needed to set `ANSIBLE_JINJA2_NATIVE=true`.

With the keyed_groups commented out, I obtain this output:

```
ANSIBLE_JINJA2_NATIVE=true ansible-inventory -i plugins/constructed/inv_content.ini -i plugins/constructed/constructed.yml --list --export
{
    "_meta": {
        "hostvars": {
            "foobar": {
                "var1": 3, 
                "var2": 5, 
                "var_sum": 8
            }, 
            "not_web": {}, 
            "web_1": {
                "sort_me2": "group_two", 
                "tag": "foo"
            }, 
            "web_2": {
                "sort_me": "group_one", 
                "tag": "bar"
            }
        }
    }, 
    "all": {
        "children": [
            "private_only", 
            "ungrouped", 
            "webservers"
        ]
    }, 
    "private_only": {
        "hosts": [
            "foobar", 
            "not_web", 
            "web_1", 
            "web_2"
        ]
    }, 
    "webservers": {
        "hosts": [
            "web_1", 
            "web_2"
        ]
    }
}
```

hostvar `var_sum` is 8, as an integer.

With this example:

https://github.com/AlanCoding/Ansible-inventory-file-examples/tree/master/plugins/constructed

Thank you, this is very helpful information and is a setting we will want to apply moving forward.

When I left the keyed_groups in _and_ applied this setting I got https://github.com/ansible/ansible/issues/52158, which is out of scope here.
