### ISSUE TITLE
Feature Request: Add config file option to permanently enable verbose output

### ISSUE THREAD

**Issue by LukWe99** [ansible/ansible#37479]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Ansible

##### ANSIBLE VERSION

```
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python2.7/site-packages/ansible
executable location = /bin/ansible
python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

No changes made. 

##### OS / ENVIRONMENT
N/A

##### SUMMARY
To enable verbose output for playbooks you always have to use the -v parameter on the command line. As I always want to have verbose output this is inconvenient for me. 

So I suggest adding an option to the config file which permanently enables verbose output. 

##### STEPS TO REPRODUCE

That's how a config file parameter could look like: 

```
verbose_output = v
verbose_output = vvv
```

##### EXPECTED RESULTS
With verbose_output=v Ansible should show the same output as if it is started with -v command line parameter. 
verbose_output=vvv should show the same output as Ansible started with -vvv parameter. 

##### ACTUAL RESULTS
N/A

**Comment by bladecoates** [comment]
This can be accomplished with DEFAULT_VERBOSITY. 

http://docs.ansible.com/ansible/latest/config.html

**Comment by LukWe99** [comment]
Thank you! 
Solves my issue. 
Sorry for the inconveniences...
