### ISSUE TITLE
More options for ansible-pull

### ISSUE THREAD

**Issue by sfromm** [ansible/ansible#375]
More options for ansible-pull:
- -a/--args - Specify extra arguments for git module.  Partly related to issue #374, now that the git module supports more options, it would be useful to provide them to ansible-pull
- -R/--remove - Remove checked-out git repository after playbook run.  

Let me know if you want to break feature freeze for 0.4 for this and #374.

**Comment by mpdehaan** [comment]
closing RFE ticket, will accept pull requests
