### ISSUE TITLE
Minimal set of modules in requirements.txt is incomplete

### ISSUE THREAD

**Issue by knaapjvd** [ansible/ansible#37519]
When testing the documentation for a module, the venv is missing required python modules. Please add the following modules to requirements.txt:
 - six
 - sphinx-docstring-typing

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible

##### ANSIBLE VERSION

```
ansible 2.6.0 (devel 93d2761551) last updated 2018/03/16 12:36:41 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/knaapjvd/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/knaapjvd/ansible/lib/ansible
  executable location = /home/knaapjvd/ansible/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

Not relevant, first setup in accordance with the [instructions](http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html#environment-setup).

##### OS / ENVIRONMENT

```
Red Hat Enterprise Linux Server release 7.4 (Maipo)
Linux hostname 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 13 10:46:25 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
pip 1.4.1 from /home/knaapjvd/ansible/venv/lib/python2.7/site-packages (python 2.7)
```
The umask is set to `0077` and I need sudo to install via yum & pip.
Not installed: `python-sphinx-1.1.3-11.el7.noarch`

##### SUMMARY
There is a requirements.txt file in which (minimally) required python modules are listed. Sphinx is missing from this list. When absent, the `make webdocs` [instruction](http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#testing-documentation) fails.

##### STEPS TO REPRODUCE

Set up a RedHat OS, like mentioned above.
Follow the instructions in the links provided above.
Try to `make webdocs`.

##### EXPECTED RESULTS

Successful generation of docs.

##### ACTUAL RESULTS

```
../bin/testing_formatter.sh
CPUS=2 make -f Makefile.sphinx html
make[2]: Entering directory `/home/knaapjvd/ansible/docs/docsite'
sphinx-build -M html "rst" "_build" -j 2 -n -w rst_warnings
Traceback (most recent call last):
  File "/home/knaapjvd/ansible/venv/bin/sphinx-build", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/knaapjvd/ansible/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3195, in <module>
    @_call_aside
  File "/home/knaapjvd/ansible/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3179, in _call_aside
    f(*args, **kwargs)
  File "/home/knaapjvd/ansible/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3208, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/knaapjvd/ansible/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 681, in _build_master
    ws.require(__requires__)
  File "/home/knaapjvd/ansible/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 999, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/knaapjvd/ansible/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 885, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'typing' distribution was not found and is required by Sphinx
make[2]: *** [html] Error 1
make[2]: Leaving directory `/home/knaapjvd/ansible/docs/docsite'
make[1]: *** [htmldocs] Error 2
make[1]: Leaving directory `/home/knaapjvd/ansible/docs/docsite'
make: *** [webdocs] Error 2
```

**Comment by s-hertel** [comment]
I think these are the requirements you're looking for: https://github.com/ansible/ansible/blob/devel/docs/api/docs-requirements.txt

**Comment by knaapjvd** [comment]
I think so too. This was not obvious from the [testing-documentation](http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#testing-documentation) nor [environment-setup](http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html#environment-setup) docs.
Perhaps, it should suffice to clarify this at either link?

**Comment by sivel** [comment]
From https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html there is a line that reads:

> You should also test the HTML output of your module documentation

Clicking on the link takes you to https://docs.ansible.com/ansible/latest/dev_guide/testing_documentation.html

Which indicates:

pip install --user -r docs/docsite/requirements.txt

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
