### ISSUE TITLE
Jinja-style variable expansion works differently in playbooks

### ISSUE THREAD

**Issue by junegunn** [ansible/ansible#3755]
Please take a look at this playbook.

``` yaml

---
- hosts: localhost
  connection: local
  vars:
    a: 1
    b: 2

  tasks:
  - debug:
      msg: "${a} ${b}"

  - debug:
      msg: "${a} ${b} ${c}"

  - debug:
      msg: "{{a}} {{b}}"

  - debug:
      msg: "{{a}} {{b}} {{c}}"
```

So in here, we have `a` and `b` defined, but not `c`. The result is then given as follows.

```
TASK: [debug ] ****************************************************************
ok: [localhost] => {"msg": "1 2"}

TASK: [debug ] ****************************************************************
ok: [localhost] => {"msg": "1 2 ${c}"}

TASK: [debug ] ****************************************************************
ok: [localhost] => {"msg": "1 2"}

TASK: [debug ] ****************************************************************
ok: [localhost] => {"msg": "{{a}} {{b}} {{c}}"}
```

In the second case, only the known variables are expanded leaving `${c}` unchanged, while in the last case, none of the expressions is expanded.

Are we okay with this inconsistent behavior? I know it's not a good practice to have undefined variables around, still it was quite surprising as it's not clearly documented anywhere.

---

As a side note, I tried to set `ANSIBLE_ERROR_ON_UNDEFINED_VARS` environment variable, but currently it doesn't seem to work. I looked into the code, and the problem is `fail_on_undefined` variable is not properly passed along the call stack. (see [320](https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/template.py#L320), [328](https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/template.py#L328), and [332](https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/template.py#L332))

I'm not sending a pull request since it still seems to be a yet undocumented feature, and I'm not perfectly sure whether the argument is not being passed on purpose, or just by mistake.

**Comment by mpdehaan** [comment]
I'm ok with it.

But I'd be very interested in patches that made it expand as much as it possibly could.

**Comment by mpdehaan** [comment]
undefined variable checking has some patches in queue, BTW.
