### ISSUE TITLE
Auto mkdirs when copying file

### ISSUE THREAD

**Issue by iven** [ansible/ansible#3759]
An option should be added to create required directories when copying file if they don't exist.

For example, when copying pip.conf to $HOST/root/.pip/, we may meet following error:

```
msg: Destination directory /root/.pip does not exist
```

I think /root/.pip should be automatically created (or at least add an option and let the user decide.)

**Comment by mpdehaan** [comment]
I disagree with this, because you really do need to set a permissions for the directory as well as the file.

Just add a task before that says:
- file: path=/some/dir/to/wherever state=directory

and consider passing ownership and mode parameters.

**Comment by fewknow** [comment]
@mpdehaan it should set the default permissions for the directory.  As it does in your example....you are not setting permissions for the directory, but allowing the defaults.   Having to add this is annoying at best.

**Comment by hadrien-toma** [comment]
@mpdehaan so, maybe this should be re-opened?
