### ISSUE TITLE
Image parameter shouldn't be required for the EC2 module

### ISSUE THREAD

**Issue by boosh** [ansible/ansible#3760]
It'd be good to be able to use ansible to add and remove tags on running EC2 instances. Unfortunately the image parameter is currently required, so this isn't possible.

This would allow, for example, a monitoring system to tag an instance as 'ready: False', and have ansible kill it, start another one, wait until services become ready, and then tag it as 'ready: True'.

**Comment by jctanner** [comment]
@boosh Adding tags to a running instance is a task already handled by the ec2_tag module ...

http://www.ansibleworks.com/docs/modules.html#ec2-tag
