### ISSUE TITLE
Outputting stdout/stderr as it comes for async tasks

### ISSUE THREAD

**Issue by dhorbach** [ansible/ansible#3761]
Based on https://groups.google.com/d/topic/ansible-project/UGb8i7wU8Jk/discussion.
This feature will be awesome to have for continuous application deployments where build/deploy scripts (Ant, Maven) are the main players and produce a lot of information to trace in realtime (during Jenkins build for example).

**Comment by mpdehaan** [comment]
This is a duplicate ticket, so I'm closing it.

But yes, this is something we should do sometime.

**Comment by fdhenard** [comment]
+1

Also what is the duplicate id?

**Comment by jctanner** [comment]
@fdhenard https://github.com/ansible/ansible/issues/3887
