### ISSUE TITLE
The file module doesn't respect the owner key when applying on hierarchy of folders. 

### ISSUE THREAD

**Issue by oren** [ansible/ansible#3765]
`- file: path=/home/oren/misc/projects state=directory owner=oren group=oren mode=0644 recurse=yes`
And misc is set to root:root

 ansible 1.3 (devel 56a00e0667) last updated 2013/08/06 00:23:20 (GMT -700)

**Comment by srgvg** [comment]
@oren I didn't notice it when you talked about this on irc, but now I see your example, the recurse option will go "downwards", not "upwards".
You need to issue a file task on /home/oren/misc to set owner from there, downwards.

**Comment by mpdehaan** [comment]
Correct, this is not a bug.

Clearly don't want to set permissions on "/" here, and it's really better to be explicit at each level rather than relying on recurse (in case different levels need to be different)
