### ISSUE TITLE
mysql_user command fail with dots in database names

### ISSUE THREAD

**Issue by vdboor** [ansible/ansible#3767]
As I use the domainname of a site as database name, ansible fails on these values.

`_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.nl.* TO 'www.mysite.nl'@'localhost'' at line 1")`

MySQL server version: 5.5

I'm using the action:

`mysql_user name=$mysql_user host=localhost password=$mysql_password state=present priv=$mysql_db.*:ALL`

The grant statement needs to have the database name quoted:

`grant all privileges on `www.mysite.nl`.* to 'gtd.edoburu.nl'@localhost;`

I've did some digging through the ansible source code, but couldn't really find how to change that.

**Comment by johnhamelink** [comment]
I'm also experiencing this, but with the following database name: "glasgow-locum-group_production" (minus quotes). I'm using mariaDB 5.5.32.

I'm going to have a dig and see if I can cook up a pull request.

**Comment by sevein** [comment]
@johnhamelink - I forgot to say: thank you for taking care of this! :+1:

**Comment by johnhamelink** [comment]
No problem @sevein!

**Comment by echo-devnull** [comment]
Could it be that this error is back again?

_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ON _._ TO 'replication'@'localhost'' at line 1")

With this ansible setup: 
- name: create replication user
  mysql_user: name=replication password=***********\* priv=_._:REPLICATION state=present

(This comment is removing the stars, please also see here: http://pastebin.com/iBWHZfZM )

ansible version: 1.6.2

**Comment by kilex** [comment]
@markmaas +1

```
ansible --version
ansible 1.7
```

in role task:
`mysql_user: name=kilex.ru password=****** priv=`kilex.ru`.*:ALL state=present`
error in result:

```
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1404502036.04-132588940619042/mysql_user", line 1774, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1404502036.04-132588940619042/mysql_user", line 462, in main
    changed = user_add(cursor, user, host, password, priv)
  File "/root/.ansible/tmp/ansible-tmp-1404502036.04-132588940619042/mysql_user", line 164, in user_add
    privileges_grant(cursor, user,host,db_table,priv)
  File "/root/.ansible/tmp/ansible-tmp-1404502036.04-132588940619042/mysql_user", line 292, in privileges_grant
    cursor.execute(query)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1103, "Incorrect table name ''")
```

**Comment by Jmainguy** [comment]
#7769 reports this same issue. #7804 is believed to fix this issue.

**Comment by ziras** [comment]
#7804 fixes this issue but the issue is closed without any commit merged into the core repo.
