### ISSUE TITLE
Can't run 1.2.2 on OSX

### ISSUE THREAD

**Issue by pvledoux** [ansible/ansible#3769]
Hi,

I tried to upgraded from 1.1 to 1.2.2 but I have an error when running ansible:

```
Traceback (most recent call last):
  File "/usr/local/share/python/ansible", line 149, in <module>
  callbacks.display("", log_only=True)
AttributeError: 'module' object has no attribute 'display'
```

I did the following to upgrade:

```
#git checkout -b release1.2.2 origin/release1.2.2
#python setup.py install
```

I cleaned up ansible for /usr/share and lib completely and reinstalled from scratch, no success.

I installed back 1.1 and it works.

Cheers,

**Comment by mpdehaan** [comment]
Haven't heard this from any of our 1.2.2 users, any chance you have a non clean install?

Are you doing "source ./hacking/env-setup"  or have any old callback plugins installed?

**Comment by pvledoux** [comment]
Hi Michael, in fact, it was a fish/homebrew/python combination of problem.
Now I'm pointing all required env variables that are normally setup in env-setup directly in fish config, and now I can run ansible, directly from my local ansible repo. Much easier.

For the record, I edited my ~/.config/config.fish and added those lines:

```
set -x PATH ~/src/ansible/bin $PATH
set -x ANSIBLE_HOME ~/src/ansible
set -x PYTHONPATH ~/src/ansible/lib $PYTHONPATH
set -x ANSIBLE_LIBRARY ~/src/ansible/library
set -x MANPATH ~/src/ansible/docs/man $MANPATH
```

No more wondering about /usr/share or /usr/local/share, fish or bash, all works now out of the box.

Cheers,
