### ISSUE TITLE
ini_file-module does not create a section, when no option/value is defined (2.0.0.2)

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#37711]
_From @my2ndhead on February 8, 2016 19:30_

##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

ini_file module
##### ANSIBLE VERSION

N/A
##### SUMMARY

When a section does not already exist, it will not be created, when no options/values are defined. This was working under 1.9.

When manually creating the section and running the task, a key-value-pair of "None = none" is created.

```
name: "Creating section" 
ini_file: dest=section
          state=present
```

_Copied from original issue: ansible/ansible-modules-core#2987_

**Comment by dagwieers** [comment]
_From @ansibot on July 31, 2016 18:33_



@jpmens, @noseka1, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
_From @ansibot on September 7, 2016 3:17_

@jpmens, @noseka1, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
_From @jpmens on September 7, 2016 6:42_

*I cannot fix it* due to time constraints

**Update:** Rephrased so it doesn't trigger the bot again ;-)

**Comment by dagwieers** [comment]
_From @my2ndhead on September 7, 2016 6:52_

You can't just close this issue just because of time constraints. This is a major bug that breaks a lot of things.

**Comment by dagwieers** [comment]
_From @jpmens on September 7, 2016 7:2_

I agree. I did not close it.
I assume my comment caused the bot to close it. What I meant to do was to say "I cannot fix this"

@bcoca Please reopen.

**Comment by dagwieers** [comment]
_From @eden881 on March 21, 2018 12:29_

Any updates on this? We have this problem too...

**Comment by dagwieers** [comment]
needs_contributor

**Comment by dagwieers** [comment]
bot_broken

**Comment by Spreadcat** [comment]
Stumbled over this today. Is there any update on this? Otherwise I guess I'll have to learn to teach myself messing with "your" code....#emptythread :)
