### ISSUE TITLE
Support for documenting return values of modules

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#3775]
Currently, the documentation string format doesn't support specifying the return value of a module (or, if it does, I can't find any examples of this).

For example, the "ec2" module returns `instance_ids` (a list of instances) and `instances` (a list of dictionaries with useful fields like `public_ip`).

It would be helpful if the documentation string format had support for describing these return values.

**Comment by mpdehaan** [comment]
For now, this can be largely covered in the examples section and include examples that leverage add_host in particular.

There is some "fun" to be had including JSON output inside YAML and not sure we want to go there as that is why we made the EXAMPLES free form section.

See also the AWS chapter, but I agree other cloud providers need to be covered.

**Comment by nathancahill** [comment]
For one-level JSON, a table like the Options table is probably the best way to do this. See here: https://github.com/nathancahill/ansible/commit/21a488898d6a631e0c0208899f4dedab19ca1e1a and an example module here: https://github.com/nathancahill/ansible/commit/f02b860de718a8f095e09b883efe66483bc92556. A good number of modules can use this format. For more than one level, nested table rows?

**Comment by mpdehaan** [comment]
This is pretty much how I'd see it happening.  The lion's share of the work will be in annotating all of the existing modules (or most of them).

**Comment by mpdehaan** [comment]
Was referring to flat returns -- it's probably just best if we show example JSON actually and do something like RETURN_VALUE_EXAMPLES = docstring

**Comment by nathancahill** [comment]
Cool. I wrote a little python script that generates yaml from the module.exit_json, so I'll run it for all the flat returns and post back here with an update. Agreed that example JSON is the best for complex returns.

**Comment by bcoca** [comment]
implemented in #10457
