### ISSUE TITLE
Feature Request: Run task inside a custom module

### ISSUE THREAD

**Issue by tszming** [ansible/ansible#3776]
I am thinking if it is possible to re-use the existing module when you are developing your own custom module.

For example, I need to download file using S3 in my own module, why I need to use boto to do job when there is already a S3 module?

In chef, it is easy to re-use existing resource like

```
# Create user/group
u = user new_resource.user do
    system true
    shell "/bin/false"
    action :nothing
end
u.run_action(:create)
```

In mailing list you said to use the common.py but I guess you won't want to put all the stuffs like s3 module inside it.

**Comment by mpdehaan** [comment]
We are not Chef.

The get_url functions should be moved to module common if we want to reuse the download code.

**Comment by tszming** [comment]
I think you are right that the get_url should be moved into common module, but what about module like the `s3`? Will you move into the common module? If not, supporting launching a sub-task inside a custom module sound like a good alternative rather than reinventing the wheel?

Actually, I am not talking extending or monkey patching the existing modules like [1], this will be problematic when the library is changed. I am referring to launch a sub task using the published interface in order to enjoy the functionalities which are already implemented.

As an example, the following method will put a file using `s3` with a single line

```
module.run_subtask(task='s3', bucket='mybucket', object='/my/desired/key.txt src=/usr/local/myfile.txt', mode='put')
```

[1] https://groups.google.com/forum/#!topic/ansible-project/7SByPqJxa7Q
