### ISSUE TITLE
vmware_guest num_cpu_cores_per_socket does not work

### ISSUE THREAD

**Issue by talhajilal** [ansible/ansible#37807]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by talhajilal** [comment]
Hello Team , 

I am trying to create vm with vmware_guest module and using linux os template. 

My syntax for hardware section is , 

hardware:
      memory_mb: "{{ ram_size }}"
      num_cpus: "{{ cpu_nums }}"
      num_cpu_cores_per_socket: 2


Issue : CPU sockets are ok but virtual CPU does not take any change ? 

############## Debug log ######

ok: [kuber-n-03] => {
    "deploy": {
        "changed": true,
        "failed": false,
        "instance": {
            "annotation": "",
            "current_snapshot": null,
            "customvalues": {},
            "guest_tools_status": "guestToolsNotRunning",
            "guest_tools_version": "2147483647",
            "hw_eth0": {
                "addresstype": "assigned",
                "ipaddresses": null,
                "label": "Network adapter 1",
                "macaddress": "00:50:56:b7:a8:a8",
                "macaddress_dash": "00-50-56-b7-a8-a8",
                "summary": "VM Network"
            },
            "hw_guest_full_name": null,
            "hw_guest_id": null,
            "hw_interfaces": [
                "eth0"
            ],
            "hw_memtotal_mb": 2048,
            "hw_name": "kuber-n-03",
            "hw_power_status": "poweredOn",
            "hw_processor_count": 2,
            "hw_product_uuid": "42371497-b8e6-5c9d-8859-6d73af6b9f78",
            "ipv4": null,
            "ipv6": null,
            "module_hw": true,
            "snapshots": []
        }
    }
}


########## End debug log ##########

**Comment by talhajilal** [comment]
google discussion link :   https://groups.google.com/forum/#!topic/ansible-project/jnf9cpT27U0

**Comment by mkrizek** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by talhajilal** [comment]
Ansible Version 2.5.

I run some more tests and find the following issue. 

VMware_guest module only support one value at one time.

If you set this value in ansible playbook 
num_cpu_cores_per_socket

then 

num_cpus " This option does not work " 


But 

num_cpus " This option only work alone" 

Any help ? 


My code is some thing like this. 


    hardware:
      memory_mb: "{{ ram_size_gb }}"
      num_cpus: 4
      num_cpu_cores_per_socket: 4
      scsi: paravirtual
