### ISSUE TITLE
Enhance the win_dns_client windows module to support adding DNS suffix

### ISSUE THREAD

**Issue by tchia04** [ansible/ansible#37879]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by alikins** [comment]
@tchia04 Need more info than that. Whats the intended usage? What is something that could be after that feature that can't be done now?

Closing for now. If there is additional info, open a new issue with all of the info.
