### ISSUE TITLE
feature request: inventory_file

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#3789]
We use the hosts file like our "environment" like `hosts/production` has all production hosts and  `hosts/testing` has all testing hosts, but same groups. 

So testing becomes very natural:

```
ansible-playbook -i hosts/testing playbook.yml
```

if testing is ok, apply to production 

```
ansible-playbook -i hosts/production playbook.yml
```

But sometimes it makes sense to know in which "environment" (from which inventory_file) you apply the task.

e.g. this would be very nice:

```
action: foobar...
when: {{ inventory_file }} is "hosts/production"
```

**Comment by jimi-c** [comment]
This really seems like something that should be done with groups. Why not
just put [production] at the top of the production file. Or, if there are
more groups in each file, just add them as child groups.

Also, with a directory-based inventory, it is possible a host could be in
multiple sources, so this variable could be misleading.

**Comment by mpdehaan** [comment]
I think I'd be fine with a variable that returned the name of the inventory
file, and you could just do {{ inventory_filename | basename }}

That's relatively generic.
