### ISSUE TITLE
2.5.0 - ansible CLI command throws ImportError for to_unicode

### ISSUE THREAD

**Issue by jm-welch** [ansible/ansible#37954]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`ansible` command

##### ANSIBLE VERSION

```
# Cannot use ansible --version, due to the nature of the bug itself
$ ansible-playbook --version
ansible-playbook 2.5.0
  config file = /home/jwelch32/ansible-lxss-setup/ansible.cfg
  configured module search path = [u'/home/jwelch32/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

No settings changed

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Stack trace thrown when running the `ansible` command, regardless of settings.

##### STEPS TO REPRODUCE

```
$ ansible
```

##### EXPECTED RESULTS

Expected command to run

##### ACTUAL RESULTS

```
$ ansible
Traceback (most recent call last):
  File "/usr/bin/ansible", line 41, in <module>
    from ansible.utils.unicode import to_unicode
ImportError: cannot import name to_unicode
```

**Comment by jm-welch** [comment]
Seems to be the effect of #34828, which removed several methods from the `ansible.utils.unicode` library.

I haven't had time to dig into how this should be fixed, but wanted to get a report out there as soon as I noticed it.

**Comment by bcoca** [comment]
cc @mscherer  @maxamillion

**Comment by bcoca** [comment]
I believe you are mixing ansible versions, as there should be no code calling that function after that change.

**Comment by jm-welch** [comment]
Yeah, I just saw that that line isn't in `bin/ansible` at 2.5.0. I'm trying to figure out where else ansible would have come from on this system - it's a newly installed Ubuntu on Windows subsystem, so it's not like other folks have had access to it. All I've done so far:

```
$ sudo apt-get update
$ sudo apt-get install -y python-pip
$ sudo -H pip install -U pip ansible
```

**Comment by jm-welch** [comment]
I found it. I had apparently run an `apt-get install ansible` on here before I installed pip and ran the install that way. Looks like that dropped 2.0.2 on here before pip put 2.5.0 on, though I'm still not sure why the install via pip didn't overwrite. I'm rebuilding without doing the install via apt first to confirm that that was the problem.

**Comment by bcoca** [comment]
closing as per above
