### ISSUE TITLE
have a last_result variable be available containing the last command results

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#380]
mostly for usage with only_if

This should be implemented entirely in terms of playbooks, not something that happens in runner.py

With the OO refactoring of things, I want to be able to ask each host object what it's last result was, etc.

**Comment by mpdehaan** [comment]
people wanting this aren't doing the work, and I don't need this one.

**Comment by xoJIog** [comment]
this feature would be nice

**Comment by mpdehaan** [comment]
patches accepted
