### ISSUE TITLE
Cannot get SSH agent forwarding to work

### ISSUE THREAD

**Issue by danxshap** [ansible/ansible#3803]
I'm trying to use SSH agent forwarding so that I can authenticate and pull from a github repo via ansible. I'm using OS X 10.6.8 locally and Ubuntu remotely.

My ~/.ssh/config works fine when I use ssh manually - I can type "ssh my_host_shortname" and connect to my machine and then I can pull from github because I have ForwardAgent properly set to "yes".

Here's my inventory file:

```
ec2-51-213-14-212.us-west-2.compute.amazonaws.com  ansible_ssh_private_key_file=~/.ssh/my_key.pem  ansible_ssh_user=ubuntu ansible_connection=ssh
```

Here's my config:

```
[defaults]
remote_tmp=/tmp/.ansible/

[ssh_connection]
scp_if_ssh=True
```

Furthermore, I ran `export ANSIBLE_SSH_ARGS=""` in my shell.

(note: when using `ansible_connection=ssh`, I could not get anything to work without adding both of the above items to my config and also setting that environment variable, which I discovered only after lots of searching/talking in IRC)

I can run "ansible all -m ping" and it works fine, but if I run "ansible all -a 'ssh -T git@github.com'" then I get a permission denied error because my ssh agent was not forwarded.

This has been causing me lots of frustration and if anyone can shed some light on what might be the issue here I'd appreciate it very much.

Thank you!

**Comment by mpdehaan** [comment]
Can you please stop by the mailing list?

This is more of a question about SSH than a bug report.

Thanks!
