### ISSUE TITLE
[WIP] ignore me

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#38065]
# Disabled Test

Integration tests are disabled due to known failures for the following modules [explain]:

* aaa
* bbb

Consider fixing the integration tests before or alongside changes.

# Unstable Test

Integration tests are known to be unstable for the following modules [explain]:

* aaa
* bbb

Tests may need to be restarted due to failures unrelated to changes.

# Unsupported Test
Integration tests are not supported in CI for the following modules [explain]:

* aaa
* bbb

Consider running the tests manually against changes.

# Untested Module

Integration tests do not exist for the following modules [explain]:

* aaa
* bbb

Consider adding integration tests before or alongside changes.

The test `ansible-test sanity --test pep8` [[explain](https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/pep8.html)] failed with 2 errors:
```
test/integration/targets/plugin_loader/override/filter_plugins/core.py:5:1: E302 expected 2 blank lines, found 1
test/integration/targets/plugin_loader/override/filter_plugins/core.py:8:1: E302 expected 2 blank lines, found 1
```

The test `ansible-test sanity --test shellcheck` [[explain](https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/shellcheck.html)] failed with 6 errors:
```
test/integration/targets/plugin_loader/runme.sh:7:15: SC2006 Use $(..) instead of legacy `..`.
test/integration/targets/plugin_loader/runme.sh:7:15: SC2045 Iterating over ls output is fragile. Use globs.
test/integration/targets/plugin_loader/runme.sh:9:26: SC2086 Double quote to prevent globbing and word splitting.
test/integration/targets/plugin_loader/runme.sh:17:15: SC2006 Use $(..) instead of legacy `..`.
test/integration/targets/plugin_loader/runme.sh:17:15: SC2045 Iterating over ls output is fragile. Use globs.
test/integration/targets/plugin_loader/runme.sh:19:26: SC2086 Double quote to prevent globbing and word splitting.
```

The test `ansible-test sanity --test yamllint` [[explain](https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/yamllint.html)] failed with 4 errors:
```
test/integration/targets/plugin_loader/normal/filters.yml:13:15: commas too few spaces after comma
test/integration/targets/plugin_loader/normal/filters.yml:13:17: commas too few spaces after comma
test/integration/targets/plugin_loader/override/filters.yml:15:15: commas too few spaces after comma
test/integration/targets/plugin_loader/override/filters.yml:15:17: commas too few spaces after comma
```

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
bot_skip

**Comment by gundalow** [comment]
skip_bot

**Comment by mattclay** [comment]
Integration tests **do not exist** for the following modules [[explain]](url):

* aaa
* bbb

Consider adding integration tests before or alongside changes.

**Comment by mattclay** [comment]
Integration tests __do not exist__ for the following modules [[explain](https://github.com/)]:

* aaa
* bbb

Consider adding integration tests before or alongside changes.
