### ISSUE TITLE
azure_rm_virtualmachine_scaleset_facts should return facts matching main module parameters

### ISSUE THREAD

**Issue by zikalino** [ansible/ansible#38078]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
azure_rm_virtualmachine_scaleset_facts

##### ANSIBLE VERSION
2.5

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
any

##### SUMMARY

Facts module returns just raw resource definition from Azure REST API.
It's extremely difficult to update existing VMSS by:
- querying VMSS using facts module
- updating VMSS using main module

Facts module should provide two options "raw" and "ansible" for facts format.
"ansible" format should return a structure that would match azure_rm_virtualmachine_scaleset parameters.

**Comment by jborean93** [comment]
!component =lib/ansible/modules/cloud/azure/azure_rm_virtualmachine_scaleset_facts

**Comment by yuwzho** [comment]
+label easyfix

**Comment by yuwzho** [comment]
-label bug
+label feature

**Comment by zikalino** [comment]
fixed by #39722
