### ISSUE TITLE
Can't checkout code to a directory I own?

### ISSUE THREAD

**Issue by yeago** [ansible/ansible#3811]
http://dpaste.com/hold/1337564/

tl;dr = msg: /home/live/apps/repo/src/.git: Permission denied

**Comment by mpdehaan** [comment]
Not sure how a permission denied error is our problem.  Feel free to bring it up on the mailing list as this seems more like a question than a bug report.

Also, you really should move to using new style variables like {{ foo }}, just makes it more consistent with what everyone else is now doing.  (Public service announcement!)

For future reference when filing a bug report you must explain the problem in the bug, linking to a pastebin site is not sufficient as these are ephemeral and also cannot be searched with the github search.

**Comment by yeago** [comment]
The paste attempts to show that the 'live' user has the permissions necessary in the directory its checking out.

Manually logging in as live and executing the command works fine.
