### ISSUE TITLE
django_manage virtualenv parameter doesn't work with "~"

### ISSUE THREAD

**Issue by danxshap** [ansible/ansible#3817]
This is pretty minor but caused me some confusion so figured it was worth reporting.

With the `django_manage` module, if I set the `virtualenv` parameter to `~/.virtualenvs/my_venv` then I get a python error which suggests Django is not installed (i.e. it doesn't activate the virtualenv properly). If I change it to `/home/ubuntu/.virtualenvs/my_venv` then it works fine.

This is in contrast with the `pip` module which happily accepts `~/.virtualenvs/my_venv` for its `virtualenv` parameter.

**Comment by mpdehaan** [comment]
This means the module just has to call os.path.expanduser around that parameter.

Is this something you would like to work on, perhaps?
