### ISSUE TITLE
Ansible 2.5: delegate_to with inventory_hostname returns None in the task output

### ISSUE THREAD

**Issue by IvanovOleg** [ansible/ansible#38193]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Core
##### ANSIBLE VERSION

```
2.5.0
```

##### OS / ENVIRONMENT

Centos 7
##### SUMMARY

If I use the delegate_to parameter with an inventory_hostname of the required node I get:
`changed: [k8s-agent-0 -> None]`
##### STEPS TO REPRODUCE

```
...
delegate_to: k8s-master-0

```

##### EXPECTED RESULTS

`changed: [k8s-agent-0 -> k8s-master-0]`
##### ACTUAL RESULTS

`changed: [k8s-agent-0 -> None]`

```

```

**Comment by sivel** [comment]
I cannot duplicate this with any simple reproducer that I have tried.

Please provide a minimal reproducer that shows this behavior.

needs_info

**Comment by IvanovOleg** [comment]
When I try to use delegate_to with synchronize module, I get:
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 138, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 554, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/action/synchronize.py", line 340, in run
    src = self._process_remote(_tmp_args, src_host, src, user, inv_port in localhost_ports)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/action/synchronize.py", line 104, in _process_remote
    return self._format_rsync_rsh_target(host, path, user)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/action/synchronize.py", line 66, in _format_rsync_rsh_target
    if self._host_is_ipv6_address(host):
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/action/synchronize.py", line 52, in _host_is_ipv6_address
    return ':' in host
TypeError: argument of type 'NoneType' is not iterable
```

It looks like a side effect of the first issue. I will create a simple example soon.

**Comment by IvanovOleg** [comment]
I think this issue is probably Azure specific

inventory:
```
[tmp:children]
cluster

[cluster:children]
master
agent

[master]
master-0

[agent]
agent-0
```
playbook:
```
- hosts: cluster:&test-tmp-rg
  gather_facts: True
  tasks:
    - name: test delegation
      file:
        path: /tmp/test
        state: touch
      delegate_to: test-tmp-master-0
      when: inventory_hostname in groups['agent']
```

It does the action, but returns:
`changed: [test-tmp-agent-0 -> None]`

I also use the modified azure_rm.py dynamic inventory that builds the groups tree and allows to access them that way.

**Comment by IvanovOleg** [comment]
Ok, I've investigated the issue. The problem is in the azure_rm.py script. It sets
`host_vars['ansible_host'] = public_ip_address.ip_address` only if public ip exists. I've added the `host_vars['ansible_host'] = ip_config.private_ip_address` outside of the condition and got:
  `changed: [test-tmp-agent-0 -> 10.10.0.7]`

**Comment by hotstepper13** [comment]
There seems to be an undocumented feature which can be enabled via configuration to use internal ip addresses. I did not find the right syntax to enable `use_private_ip`so i changed the default in the script instead.

just change
`self.use_private_ip = False`

to
`self.use_private_ip = True`

In my case the issues with `synchronize` were gone afterwards.

**Comment by IvanovOleg** [comment]
@hotstepper13 I've fixed it long time ago) I use private dns names taken from Azure for resolving nodes instead of ip adresses

**Comment by pgassmann** [comment]
close_me
