### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Cool0329** [ansible/ansible#38222]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by maxamillion** [comment]
This bug report contains no information so I'm closing it. Please feel free to open a new one with information about the bug so that we may resolve the issue. Thank you.
