### ISSUE TITLE
i am not able to ping a server through ansible though i can connect it through ssh

### ISSUE THREAD

**Issue by meenaven** [ansible/ansible#38310]
##### ISSUE TYPE

 - Bug Report
 i am not able to ping a server through ansible though i can connect it through ssh
##### ANSIBLE VERSION

```

```

##### SUMMARY

```
m-C02NJ3ZKG3QP:~ m0subra$ ansible all -m ping -u m0subra -k
SSH password:
10.247.209.230 | UNREACHABLE! => {
    "changed": false,
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /export/home/msubramanyam/.ansible/tmp/ansible-tmp-1522887176.87-227285247264767 `\" && echo ansible-tmp-1522887176.87-227285247264767=\"` echo /export/home/msubramanyam/.ansible/tmp/ansible-tmp-1522887176.87-227285247264767 `\" ), exited with result 1",
    "unreachable": true
}
```

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
