### ISSUE TITLE
Raw module - disable ssh fingerprint

### ISSUE THREAD

**Issue by odedovdat** [ansible/ansible#3836]
Hey,
I manage several remote hosts using the raw module, but it seems I have to add the fingerprint of a new hosts before run ansible
so before using ansible I just connent via SSH and add the fingerprint to the known_hosts.
skipping this step will make my life much easier, Is there a way to disable the ssh fingerprint request?
I tried adding "StrictHostKeyChecking=no" to the inventory file but it doesn't work

thanks

**Comment by jimi-c** [comment]
If you wish to auto-accept SSH keys, uncomment the `host_key_checking = False` line in /etc/ansible/ansible.cfg. Please note that this is not recommended, and a better approach is to use ssh-keyscan to add entries to your known_hosts file. We are currently discussing adding some logic to have ansible run this command on your inventory for you, however at this time it is still a manual step.

**Comment by odedovdat** [comment]
I wasn't familiar with ssh-keyscan but it's exactly what I need !
thanks!
