### ISSUE TITLE
import a host`s passwords instead store in inventory

### ISSUE THREAD

**Issue by odedovdat** [ansible/ansible#3839]
Hey,
I don't want to store my hosts passwords in the ansible`s inventory, nor manually insert them for every login. I have them stored in an secured DB, is there a good solution to get the passwords and use them with ansible ?

**Comment by jimi-c** [comment]
Currently the only options are to use passwords (stored in the inventory or prompted), SSH keys, or to use the AWX product which provides an authentication layer with role-based access controls.

**Comment by bcoca** [comment]
there is a password lookup plugin that can be pointed to external
files/repos and can even generate them if they don't exist. In any case
this belongs more in IRC or the mailing list vs opening a issue.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno
