### ISSUE TITLE
Issue with jinja template filter abs in ansible 2.5

### ISSUE THREAD

**Issue by orderedchaosdev** [ansible/ansible#38419]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

abs filter

##### ANSIBLE VERSION

```
ansible 2.5.0
  python version = 2.7.14 (default, Mar 21 2018, 16:45:24) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

In ansible 2.4 a template worked fine and in 2.5 it throws an error.
##### STEPS TO REPRODUCE

Run the playbook below

```yaml
---

- hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - debug:
        msg: "{{ (-5*4000)|int|abs }}"

```

##### EXPECTED RESULTS

I get a number back
```
ansible 2.4 output
ok: [localhost] => {
    "msg": "20000"
}
```
##### ACTUAL RESULTS

It throws an Attribute Error as well as a warning that abs is a test rather than a filter

```
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|abs` instead use `result is abs`. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'int' object has no attribute 'startswith'
fatal: [localhost]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Comment by sivel** [comment]
Already resolved by https://github.com/ansible/ansible/pull/37881 that will be included in an upcoming 2.5.1 release.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
