### ISSUE TITLE
error when asking host questions from cron could be more clear

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#3841]
If running ansible playbook from cron and it asks a host key question there is no stdin, as such, we need to make this error message better and suggest how to work around the problem (and/or just be cool if no stdin)

fatal: [127.0.0.1] => {'msg': 'FAILED: argument must be an int, or have a fileno() method.', 'failed': True}

**Comment by alisaifee** [comment]
I've just started encountering the same issue. However, in my case I'm not executing the playbook via cron, its directly from the shell. The problem has started occurring right after i changed the ssh port of a target host.

Subsequently I was able to recover from this state by ssh'ing manually to the host on the new port and then running ansible.

**Comment by jimi-c** [comment]
As noted in #3902, the issue was a failure to dupe stdin when forks == 1. The above patch should correct the problem for you and will be included in 1.3. Thanks!
