### ISSUE TITLE
async workdir should be configurable

### ISSUE THREAD

**Issue by itiserik** [ansible/ansible#3846]
The async module does not write in the /tmp/ dir but in the ~/ . I use a readonly filesystem so my homedir is not writable. Can async get a configuration parameter to adjust the working dir?

**Comment by mpdehaan** [comment]
This is already configurable in ansible.cfg.

Ask the list if you would like some help!

**Comment by itiserik** [comment]
No that is the ansible tmp dir.
Just look at async_wrapper:85 and async_status:65 of the devel branch.
