### ISSUE TITLE
lineinfile without regex

### ISSUE THREAD

**Issue by leth** [ansible/ansible#3847]
We'd like to use lineinfile to add entries into our ssh_known_hosts file.

Unfortunately we can't use the line itself as the regex value, because it contains non-escaped characters.

What would be great is you could omit the regex option, and then ansible would match only the insertion text verbatim.

**Comment by mpdehaan** [comment]
Thanks for the suggestion.

I can definitely recognize that line in file can be a bit complex and can see this being useful.

**Comment by leth** [comment]
Awesome, thanks :)
