### ISSUE TITLE
Unstable integration test win_exec_wrapper

### ISSUE THREAD

**Issue by mattclay** [ansible/ansible#38494]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

win_exec_wrapper integration test

##### ANSIBLE VERSION

```
2.6
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Shippable

##### SUMMARY

Unstable integration test win_exec_wrapper:

https://app.shippable.com/github/ansible/ansible/runs/60530/14/tests

##### STEPS TO REPRODUCE

Run tests on Shippable.

##### EXPECTED RESULTS

Tests pass.

##### ACTUAL RESULTS

Tests are unstable or fail.

> failure: non-zero return code

```
{
"changed": true, 
"cmd": "set | more", 
"delta": "0:00:00.140400", 
"end": "2018-04-09 07:10:11.871200", 
"msg": "non-zero return code", 
"rc": 1, 
"start": "2018-04-09 07:10:11.730800", 
"stderr": "Not enough memory.\r\n", 
"stderr_lines": [
"Not enough memory."
], 
"stdout": "", 
"stdout_lines": []
}
```

**Comment by mattclay** [comment]
Failures seen on:

- 2008 - https://app.shippable.com/github/ansible/ansible/runs/60530/13/tests
- 2008 R2 - https://app.shippable.com/github/ansible/ansible/runs/60530/14/tests

**Comment by mattclay** [comment]
The failure appears to be a recent development. These runs did not have the failures:

- April 4th - https://app.shippable.com/github/ansible/ansible/runs/60021/summary/console
- April 5th - https://app.shippable.com/github/ansible/ansible/runs/60154/summary/console

But these runs did fail:

- April 6th - https://app.shippable.com/github/ansible/ansible/runs/60337/13/tests
- April 7th - https://app.shippable.com/github/ansible/ansible/runs/60479/14/tests
- April 8th - https://app.shippable.com/github/ansible/ansible/runs/60503/14/tests
- April 9th - https://app.shippable.com/github/ansible/ansible/runs/60530/13/tests

**Comment by mattclay** [comment]
Once this test is stable it should be moved to group 1 and added to the smoke tests.

**Comment by jborean93** [comment]
@mattclay are we still installing KB2842230, I was told recently the URL for the hotfix was changed recently so that may be silently failing and we don't realise it.

**Comment by mattclay** [comment]
@jborean93 I verified KB2842230 is still being installed. We download patches from our own S3 bucket so we shouldn't be affected by download changes.

**Comment by jborean93** [comment]
That is true, thanks for verifying, I'll have a look sometime this week as this is a pretty important test.

**Comment by jborean93** [comment]
Fix for this is here https://github.com/ansible/ansible/pull/38504
