### ISSUE TITLE
ec2_elb: times out on de-register

### ISSUE THREAD

**Issue by bhang** [ansible/ansible#3849]
Ansible version: git checkout of devel - 10a0f03cdc
Module: ec2_elb
Version: 8171b7ba48

I have a playbook that deals with a common scenario - software deploys to instances behind an ELB. The playbook runs serially and performs the following steps:
- deregister instance
- upgrade software
- register instance

This works well with the ec2_elb module until the commit prior to the one I listed above. With the latest commit, I get an error: operation timed out.

invalid output was: 

``` python
Traceback (most recent call last):
  File "/Users/shubhang/.ansible/tmp/ansible-1376500488.44-71167606737633/ec2_elb", line 1188, in <module>
    main()
  File "/Users/shubhang/.ansible/tmp/ansible-1376500488.44-71167606737633/ec2_elb", line 227, in main
    response = urllib2.urlopen('http://169.254.169.254/latest/meta-data/placement/availability-zone')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 394, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 412, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1199, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1174, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 60] Operation timed out>
```

Thinking that perhaps I had to specify the region (even though it's not required), I added the `ec2_region` argument but then I got a new error:

```
msg: ELB [u'<ELB-NAME>'] does not exist
```

The previous version of this module d6449711ae works just fine.

**Comment by lwade** [comment]
Which region does your elb exist in?  Does it exist in the same region as
passed to the ec2_region parameter?

**Comment by bhang** [comment]
Yes, `us-east-1`

Looking at the code, I think it might be assuming that the module is being run _within_ EC2 since it tries to query the metadata service if region is not specified. That might be why it's timing out (the first error). Not sure yet why the ELB isn't being found.

**Comment by lwade** [comment]
Sorry, I missed that.  Yes, that's correct.  BruceP has removed that in his
latest PR for this, found here:
https://github.com/ansible/ansible/pull/3832

**Comment by lwade** [comment]
I should have expanded my last comment a little more.  As you have probably
noticed, this part of the code should only be called if ec2_region isn't
set (either via param or env variable on the host).  So you should be able
to specify ec2_region to the region in which your ELB exists and then
happily continue in your work :)

**Comment by bhang** [comment]
So, I guess I'll temporarily use the older version until the PR makes it in. Should I close this issue ?

**Comment by mpdehaan** [comment]
Sounds like it needs to stay open but I'll reference it

#3832

**Comment by lwade** [comment]
Or better still, try out the changes which will soon be merged by grabbing
the module from https://github.com/ansible/ansible/pull/3832

**Comment by jimi-c** [comment]
Can we confirm if this is still an issue? The PR above was merged.

**Comment by bhang** [comment]
I pulled the latest from github but I don't see any modifications for this module.

**Comment by jimi-c** [comment]
Yeah my bad, I thought the above had been merged but it had just been closed. I'll take a look into this today. Can you share an example of your playbook to help replicate this?

**Comment by lwade** [comment]
Once Bruce's changes get merged, specifying the region will resolve this I
feel.

**Comment by bhang** [comment]
@jimi1283 - here's an example of what I'm trying to do: https://gist.github.com/bhang/6320004

@lwade - looking forward to the merge

**Comment by jimi-c** [comment]
@bhang I've been testing Bruce's patch, and it does appear that this resolves the error, so as soon as that's merged in I'll close this as being fixed. The one gotcha is you'll have to add "region: " to all of your ec2_elb tasks (in fact region is going to be require for most if not all of the ec2\* modules going forward).

**Comment by bhang** [comment]
@jimi1283 - sounds good, thanks!

**Comment by jimi-c** [comment]
Merged, give it a test and let me know if you're still having problems.

**Comment by bhang** [comment]
So, after pulling the latest, the de-register works fine when I add the `region` argument, but the register step fails (even after adding the `region` argument). The error is:

```
failed: [ec2-xxx-xx-xx-xx.compute-1.amazonaws.com] => {"failed": true}
msg: ELB [u'APP-ELB'] does not exist

FATAL: all hosts have already failed -- aborting
```

Of course, if I don't supply the `region` argument to the register step, I get the (expected) error:

```
msg: Either region or EC2_REGION environment variable must be set.
```

**Comment by jimi-c** [comment]
That's odd, it appears the name is being interpreted as a list. Can you look in the library/cloud/ec2_elb code and tell me if you see something like this towards the end of the file?

<pre>
    for elb in ec2_elbs:
        if not elb_man.exists(elb):
            msg="ELB %s does not exist" % elb
            module.fail_json(msg=msg)
</pre>

**Comment by bhang** [comment]
Yep, I see it. Here's the end of the file on my machine:

``` python
    for elb in ec2_elbs:
        if not elb_man.exists(elb):
            msg="ELB %s does not exist" % elb
            module.fail_json(msg=msg)

    if module.params['state'] == 'present':
        elb_man.register(wait)
    elif module.params['state'] == 'absent':
        elb_man.deregister(wait)

    ansible_facts = {'ec2_elbs': [lb.name for lb in elb_man.lbs]}
    ec2_facts_result = dict(changed=elb_man.changed, ansible_facts=ansible_facts)

    module.exit_json(**ec2_facts_result)

# this is magic, see lib/ansible/module_common.py
#<<INCLUDE_ANSIBLE_MODULE_COMMON>>

main()
```

**Comment by jimi-c** [comment]
And how are you specifying the ELB's? Is it like this:

<pre>
      ec2_elbs:
        - testing
</pre>

Or like this:

<pre>
      ec2_elbs: testing
</pre>

If it's the later, could you try the top syntax?

**Comment by bhang** [comment]
It's the former i.e.

```
ec2_elbs:
  - testing
```

**Comment by jimi-c** [comment]
That is very odd, that's how I'm testing it and not running into that problem.

**Comment by lwade** [comment]
Can we see your playbook for registration and deregistration?

**Comment by bhang** [comment]
@lwade - I've updated the gist that I shared earlier to include the region arg. This playbook fails at the "Register instance with ELB" task.

https://gist.github.com/bhang/6320004

**Comment by jimi-c** [comment]
@bhang actually I forgot that you were using a variable for your register step. Could you make sure that variable is an array? I think that may be where the code is getting confused.

**Comment by bhang** [comment]
I'm confused. The de-register is supposed to return a fact ec2_elbs which is the list of ELB names (also provided as a list to the de-register). Shouldn't the fact be interpolated as a list when I register? This was working just fine earlier.

**Comment by jimi-c** [comment]
So it looks like the issue here is that the fact being passed in as an argument results in it being interpreted as a string, despite the fact that it is an array. If you use with_items as follows, it works perfectly, albeit with multiple iterations:

<pre>
  - name: Deregister instance from ELB
    local_action:
      module: ec2_elb
      ec2_elbs: "{{ item }}"
      instance_id: '{{ ansible_ec2_instance_id }}'
      state: absent
      region: us-east-1
    sudo: false
    with_items: ec2_elbs
</pre>

This is despite the fact that the module arg is specifically listed as an array, so I'm not quite sure why that's the case here. As a temporary workaround, you can use the syntax above to get this working, and I'll continue debugging.

**Comment by jimi-c** [comment]
It looks like this is a known issue with the way array facts are interpreted (this is being handled in another issue). Right now, I'd recommend continuing to use the with_items method I posted above, or don't use the fact since you know the names of the LB's you're using in the registration step.

**Comment by bhang** [comment]
@jimi1283 - Thanks, I'll try the options you suggested.
