### ISSUE TITLE
make user home configurable

### ISSUE THREAD

**Issue by kodemaniak** [ansible/ansible#385]
In the user module there is an option to create a home, but no way to specify the location of the home directory. In our case we need to create a user for a service and its home directory is not supposed to be under /home. (I assume the createhome parameter creates the home directory at /home/<username>?)

**Comment by mpdehaan** [comment]
sure, sounds reasonable.   how about a patch?

**Comment by kodemaniak** [comment]
Will have a look at it, should not be too complicated.

**Comment by kodemaniak** [comment]
Had a look at the code, and actually it sees there is already the 'home' parameter. It is just not documented in the ansible docs. Have not had the time to test it yet, but it seems to do exactly what I initially wanted (i.e. passes the home dir as the '-d <home>' param to useradd/usermod). I will test it later and close this issue when appropriate.

**Comment by mpdehaan** [comment]
closing now, reopen if there is a bug.

will file a doc ticket

thanks
