### ISSUE TITLE
is there a known limit of number of hosts?

### ISSUE THREAD

**Issue by holgerkoch** [ansible/ansible#3856]
Hi,

we use anbile 1.2 and have an ansiblehosts file with nearly 3000 hosts and wanna make a simple connection test with:

ansible all -m ping

It seems to us, that ansible stops the processing until 1200hosts (+/- 200 hosts).

Did anybody make the same experience? How big is the biggest known ansible installation?

best regards

**Comment by bcoca** [comment]
You might need to change your ulimit settings (check dmesg), I don't
believe ansible has a built in limit, but you might be hitting an OS set
limit

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
Please ask questions on the mailing list rather than the bug tracker please!

Thanks!

**Comment by holgerkoch** [comment]
you are right, but we have raise all limits:

-bash-3.2$ ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 10
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 29995
virtual memory          (kbytes, -v) unlimited

Then we found out, that a 32 Bit Python can only open 255 Files on Solaris. After correct this, ansible runs a little bit better, but it seems that there are some further limits.
