### ISSUE TITLE
apt_repository wrong file permission

### ISSUE THREAD

**Issue by hyao** [ansible/ansible#3857]
I'm using the latest trunk of ansible. When I add a apt repo using:
apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian precise contrib'     state=present

A file is created under sources.list.d with permission of 600, which causes ubuntu update manager to show an error. Shouldn't it have the same permission as sources.list - 644 ?

Thanks,

**Comment by sjahl** [comment]
Not sure how to reference a pull request here... https://github.com/ansible/ansible/pull/3878

**Comment by resmo** [comment]
@mpdehaan can be closed.

**Comment by jimi-c** [comment]
Closing, the issue has been resolved by the PR above.
