### ISSUE TITLE
The fact variable {{ ansible_nodename}} has an extra dot at the end on the windows which without domain name

### ISSUE THREAD

**Issue by mary09242003** [ansible/ansible#38571]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

module

##### ANSIBLE VERSION

```
ansible 2.4.2.0
```

##### OS / ENVIRONMENT

Windows

The infomation from GetIPGlobalProperties() as below:
```
HostName      : jobwin8
DomainName    :
NodeType      : Hybrid
DhcpScopeName :
IsWinsProxy   : False
```
##### SUMMARY

When I try to use the fact {{ ansible_nodename}} of the Windows machine which without DomainName, I found that {{ ansible_nodename}} is incorrect. It has an extra dot at the end. For example, my hostname is "jobwin8" without domain name, but the {{ ansible_nodename}} and {{ ansible_fqdn}} is "jobwin8.". I think it is not right. On the Redhat OS the fact variable is right.
I found that in the code ansible/lib/ansible/modules/windows/setup.ps1, the {{ ansible_nodename}} and {{ ansible_fqdn} is be joined by hostname , dot and domain name. When the DomainName is empty, the dot also be added.
```
    $ansible_facts += @{
        ansible_architecture = $win32_os.OSArchitecture
        ansible_domain = $ip_props.DomainName
        ansible_fqdn = ($ip_props.Hostname + "." + $ip_props.DomainName)
        ansible_hostname = $env:COMPUTERNAME
        ansible_kernel = $osversion.Version.ToString()
        ansible_nodename = ($ip_props.HostName + "." + $ip_props.DomainName)
```
##### STEPS TO REPRODUCE

Output the hostvars for the windows machine which without domain name.

```yaml
---
  - debug:
      var: hostvars
```

##### ACTUAL RESULTS

```

```

**Comment by ShachafGoldstein** [comment]
This is still the case nowadays, I haven't seen any other issues regarding the . (dot).

would you still want this to be discussed?

**Comment by ShachafGoldstein** [comment]
#56279 - fixed this

@jborean93 @nitzmahone  - this can be closed
