### ISSUE TITLE
variable interpolation with_nested

### ISSUE THREAD

**Issue by jurgenhaas** [ansible/ansible#3858]
This is the issue for the problem discussed here: https://groups.google.com/forum/#!topic/ansible-project/6piS-u_rPF8

This is working:

```
- name: Test with nested loops
    debug: msg="A = {{ item[0] }} / B = {{ item[1] }}"
    with_nested:
        - ['test', 'y']
        - list_of_items
```

This is NOT working:

```
- name: Test with nested loops
    debug: msg="A = {{ item[0] }} / B = {{ item[1] }}"
    with_nested:
        - groups['webserver']
        - list_of_items
```

**Comment by mpdehaan** [comment]
Curious if groups.webserver works

(Edited out the last part about older syntaxes since it wasn't related, that's working for a different reason)

**Comment by jurgenhaas** [comment]
groups.webserver doesn't work either.

**Comment by mlieberman85** [comment]
I'm running into the same issue. If I call an attribute of an object and that attribute is a list it won't work in with_nested. It will work in with_items and it will work if I use ${object.attribute} syntax.

**Comment by jurgenhaas** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi Michael,

I guess your post never reached the list as it went to
ansible@noreply.github.com but as it might be helpful I hope you gonna
post it again directly on github.

Thanks
Jürgen

Am Di 10 Sep 2013 00:35:46 CEST schrieb Michael Lieberman:

> I'm running into the same issue. If I call an attribute of an object
> and that attribute is a list it won't work in with_nested. It will
> work in with_items and it will work if I use ${object.attribute} syntax.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible/issues/3858#issuecomment-24120535.
> 
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v1.4.12 (GNU/Linux)

iQEcBAEBAgAGBQJSLqffAAoJEGMwkysX8CInMEkIAKW9AJ+SjCobRWH4wIH+ttsC
oT0Vrf4lOT6UHLVAcVCksEATiyQnaxuouM3Hkfxn4bD5dunRSpMxksURZvNAQDSq
a5CSa5eLHgZll9hvXHKKbuRYopE/vCnyzDbL+NVpxJK9YLnLWOBeVAx7856qR9VW
YLybnLO/C6XxBgURctMan0aPttEQ1QJtIFu6o4qAzwUCxogtxzuidceh+z2D56n5
4NbpPDKcPvShzds1jkZ5TzG6juz7cn8436ZCIxp2a5b+weJ6HM2Hq+JO4s5W606j
Q2MgXeI+8M/mhzbXPXS1ddh2OQRj2EysnOc0Y8+SJg+5CC648WtxEf7lSlg1K+I=
=ZVYd
-----END PGP SIGNATURE-----
