### ISSUE TITLE
{{ foo|default }} blows up when foo is not defined

### ISSUE THREAD

**Issue by bryanlarsen** [ansible/ansible#3859]
Given an undefined variable foo:

In ansible 1.2, `{{ foo }}` would put `{{ foo }}` in the template.   In ansible 1.3 this instead raises an error.   I heartily approve of this change.

However, `{{ foo|default('foo') }}`, which works well in 1.2, raises an error in 1.3.   Instead the more cumbersome `{% if foo is defined %}{{ foo }}{% else %}foo{% endif %}` must be used.

**Comment by mpdehaan** [comment]
Hi Bryan, you are missing a closing parenthesis on your 'foo'

**Comment by bryanlarsen** [comment]
Sorry, that was a cut and paste error.  My code wasn't missing a parenthesis, works find on 1.2 and doesn't work on 1.3.   Here's an actual snippet from my git log, which is part of a json.j2 file:

```
-  "numWorkers": {{ numWorkers|default(0, true) }},
+  "numWorkers": {% if numWorkers is defined %}{{ numWorkers }}{% else %}0{% endif %},
```

**Comment by bcoca** [comment]
try setting error_on_undefined_vars = False
