### ISSUE TITLE
ec2.py Inventory pass-in or store credentials

### ISSUE THREAD

**Issue by geoffjukes** [ansible/ansible#3860]
The EC2.py Inventory script is great, but it relies on Environment variables.

I believe it would be useful to add support for storing these either in the 'ini', or pass them in at execution time.

**Comment by mpdehaan** [comment]
definitely agree on the INI.

execution time does not work so well due to the way ansible likes to invoke them.

**Comment by pas256** [comment]
The EC2 inventory file relies on Boto's chain of discovery for finding credentials. Environment variables are just 1 of the many ways to pass credentials to. The full doc is here:

http://boto.cloudhackers.com/en/latest/boto_config_tut.html

I personally use a .boto file in my home directory with the credentials stored in there. On an EC2 instance, I use IAM Roles and have the credentials automatically discovered by boto, without every knowing what they are.

If you want a system wide config, use /etc/boto.cfg.

Hope that solves your issues.

**Comment by jimi-c** [comment]
@geoffjukes Is the solution @pas256 suggested sufficient? It seems unnecessary to add these to the ec2.ini if having them in one of the other two config files works.

**Comment by TomFrost** [comment]
Not a real distributable solution, but it worked for my team -- we're using a slightly modified ec2.py with this added to the top of the read_settings() function:

```
    ''' Reads the credentials from aws_creds.enc.ini '''
    creds = ConfigParser.SafeConfigParser()
    creds.read(os.path.dirname(os.path.realpath(__file__)) + '/../config/aws_creds.enc.ini')
    os.environ['AWS_ACCESS_KEY_ID'] = creds.get('aws', 'access_key_id')
    os.environ['AWS_SECRET_ACCESS_KEY'] = creds.get('aws', 'secret_access_key')
```

We use git-crypt to auto encode/decode any file with `*.enc*` in the filename when it's pushed/pulled from git, so having a separate file in the config folder of our playbook repo was convenient.  This is a bit hacky (ideally we wouldn't be passing these into environment variables), but it allows ec2.py to follow the same pattern as the rest of our codebase.  This eliminates the need for each user to set up independent config files.

**Comment by pas256** [comment]
Assuming that code is running on an EC2 instance, that is a manual alternative to use IAM Roles, except that credentials are hard coded, and not auto rotated.

Sharing credentials between users is like sharing a password between users. I probably don't need to go into details about best practices here.

**Comment by mpdehaan** [comment]
Closing per above.

AWX is also going to have some nice features to share credentials between people without them being able to see them too.
