### ISSUE TITLE
raw module commands should be even more raw

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#3864]
As we are not transferring a module, there is no need to generate a temp dir if the module name is set as 'raw'.   (As a result, there's also no temp dir to delete)

**Comment by mpdehaan** [comment]
useful for sending commands to embedded devices, in this case, a NetApp.

**Comment by mscherer** [comment]
I think this one was fixed by bda08c8a1b501 or I do not understand what this is about.

**Comment by mpdehaan** [comment]
(late response)

Not quite, though the same mechanism could perhaps be used for the raw module.   We'd need to try it.

I'm going to close this one anyway as the original ticket was a bit theoretical, if the problem comes up, we can deal with it :)
