### ISSUE TITLE
Ansible Documentation Error

### ISSUE THREAD

**Issue by tbar74235** [ansible/ansible#38660]
##### ISSUE TYPE

 - Documentation Report

##### ANSIBLE VERSION

```
ansible 2.5.0
```

##### SUMMARY

The link to the file module within http://docs.ansible.com/ansible/latest/modules/list_of_files_modules.html leads not to the description of the file module. It currently leads to the lookup plugin file what is wrong in my opinion.

##### STEPS TO REPRODUCE

N/A

##### EXPECTED RESULTS

The link to the file module has to lead me to the file module description (http://docs.ansible.com/ansible/latest/modules/file_module.html).

##### ACTUAL RESULTS

N/A

N/A

**Comment by tbar74235** [comment]
This applies to the file module link within http://docs.ansible.com/ansible/latest/modules/list_of_all_modules.html too.

**Comment by acozine** [comment]
duplicate of #38439

**Comment by tbar74235** [comment]
The only difference is that #38439 points out to a wrong link to the template module. Here we are talking about a wrong link to the file module.

**Comment by sivel** [comment]
Closing as a duplicate of https://github.com/ansible/ansible/issues/38439

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
