### ISSUE TITLE
Feature Request: pre_tasks and post_tasks for roles.

### ISSUE THREAD

**Issue by benosman** [ansible/ansible#3869]
I would like to be able to have pre_tasks and post_tasks for each role - most likely in a role/pre_tasks/main.yml file to keep a consistent format. I looked and it doesn't seem like this behaviour is there yet. 

I want to use this step to add package repositiories for each role, without triggering a repository update after each step. Then in the main tasks file for the role I will be doing the actual installation.

Would this be considered for ansible, or am i missing a better way of achieving this?

**Comment by mpdehaan** [comment]
Pre tasks and post tasks are largely designed for working with load balancers.

Can you let me know a bit more about y our use case?

I'd like to have a discussion before the feature request, and discussions should really happen on the mailing list where more people can see them.   Can you stop by?

Thanks!

**Comment by drzraf** [comment]
**Use case**
I've a bootstrap role whose tasks are critical (adding user, ssh, keys, ...)
and then a couple of others, "less critical" (firewall, logs, ...)
My role depends upon 2 others roles which help me adding features (eg: fail2ban rules, ...)
I want to run own role critical tasks first (like in a pre_tasks/) and only then load the roles marked as dependencies to use them and the libraries they provide.

Or is there another way to do that (it seemed to me like it's what pre_tasks are useful for, aren't they?)

**Comment by podarok** [comment]
let's add pre_tasks or better pre_roles for prioritizing maintainence or recover meaning roles before everything else is executed.

**Comment by Hubbitus** [comment]
I wish use it in next scenario. Say I have 2 roles - `postgres` and `postgres-slave`. Postgres do main server setup like services, directories, users… `postgres-slave` should setup replication. For that it must empty main base directory or `postgres` role will fail on `initdb` stage what it does not empty. Off course I could add many conditional variables for certain tasks, but it seams not elegant. It will be cool define `pre-tasks` for role and depend from another.
