### ISSUE TITLE
Document aliases of file parameters in docs

### ISSUE THREAD

**Issue by dcere** [ansible/ansible#3870]
I was looking for the 'dest' argument in the file module (http://www.ansibleworks.com/docs/modules.html#file) and I couldn't find it although I knew it works as its use is explained in the example below.
Maybe it should be more clear that the 'dest' and 'name' parameters are aliases to the path parameter?

**Comment by jimi-c** [comment]
After talking this over, we're not going to document the aliases any more than they already are in order to ensure that there is a level of consistency in examples. For files, `path` is the correct parameter to use.

Thanks!

**Comment by dcere** [comment]
Ok. Thanks for taking the time.
