### ISSUE TITLE
fetch wont use slurp mode and fails

### ISSUE THREAD

**Issue by steverweber** [ansible/ansible#3871]
when preforming a fetch if a mdfsum is found the slurp method to get a file is skipped.

The issue with this might be that  _remote_md5() is using sudo 
Or perhaps the stat /usr/bin/md5sum is running with root privileges... /I haven't investigated/

On a locked up server ansible is getting the remote_md5 but conn.fetch_file(source, dest) seems to fail.

```
        # calculate md5 sum for the remote file
        remote_md5 = self.runner._remote_md5(conn, tmp, source)

        if remote_md5 in ('1', '2') and self.runner.sudo:
      slurpres = self.runner._execute_module(conn, tmp, 'slurp', 'src=%s' % source, inject=inject)
      if slurpres.is_successful():
          if slurpres.result['encoding'] == 'base64':
          remote_data = base64.b64decode(slurpres.result['content'])
          if remote_data is not None:
          remote_md5 = utils.md5s(remote_data)
```

Perhaps add a option like force_slurp.
to: lib/ansible/runner/action_plugins/fetch.py

```
force_slurp = options.get('force_slurp', False)

if force_slurp or ( remote_md5 in ('1', '2') and self.runner.sudo) :
```

Thanks

**Comment by steverweber** [comment]
taking a little more look and i see in _remote_md5 that the command is marked with sudoable=True

```
    def _remote_md5(self, conn, tmp, path):
        ....
         data = self._low_level_exec_command(conn, cmd, tmp, sudoable=True)
```

Perhaps another solution would be to add sudoable as an argument

```
remote_md5 = self.runner._remote_md5(conn, tmp, source, sudoable=False)
```

**Comment by mpdehaan** [comment]
This is a dup of a feature request we are already tracking.

**Comment by steverweber** [comment]
guessing ref #3111

**Comment by mpdehaan** [comment]
yep!  In queue for getting done this release.

ETA end of this month unless someone beats us to it :)

**Comment by steverweber** [comment]
You are doing an excellent job.
Keep up the good work!

p.s. I hope 3807 gets into the release /its my only remaining issue/ :)

**Comment by jimi-c** [comment]
@steverweber just commited a fix to correct this, if you'd like to give it a try.

**Comment by steverweber** [comment]
git pull &&.. make install
Seems to work.  Thanks! @jimi1283
