### ISSUE TITLE
homebrew_cask outputs "OK" and does nothing, although it should have changed

### ISSUE THREAD

**Issue by du5tball** [ansible/ansible#38772]
##### ISSUE TYPE
 - Bug Report (Regression)

##### COMPONENT NAME
homebrew_core

##### ANSIBLE VERSION
$ ansible --version
ansible 2.5.0
  config file = /Users/dustball/.ansible.cfg
  configured module search path = ['/Users/dustball/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dustball/workspace/venv/ansible/lib/python3.6/site-packages/ansible
  executable location = /Users/dustball/workspace/venv/ansible/bin/ansible
  python version = 3.6.5 (default, Mar 29 2018, 15:37:32) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

##### CONFIGURATION
CACHE_PLUGIN(/Users/dustball/.ansible.cfg) = redis
CACHE_PLUGIN_TIMEOUT(/Users/dustball/.ansible.cfg) = 86400
DEFAULT_GATHERING(/Users/dustball/.ansible.cfg) = smart
DEFAULT_REMOTE_USER(/Users/dustball/.ansible.cfg) = root
DEFAULT_VAULT_PASSWORD_FILE(/Users/dustball/.ansible.cfg) = /Users/dustball/.config/ansible/vaultpass.txt
HOST_KEY_CHECKING(/Users/dustball/.ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/dustball/.ansible.cfg) = False

##### OS / ENVIRONMENT
macOS High Sierra (10.13.4 (17E199))

##### SUMMARY
homebrew_cask states "OK" and does absolutely nothing when it should install the package.

##### STEPS TO REPRODUCE
```
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - homebrew_cask:
        name: firefox
        state: present
```

##### EXPECTED RESULTS
Firefox should be installed

##### ACTUAL RESULTS
Firefox is not installed, yet the output is:

```
PLAY [*] ***************************************************************************************************************************************************************************************************

TASK [homebrew_cask] ***************************************************************************************************************************************************************************************
OK: [localhost]

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

**Comment by du5tball** [comment]
Now that I've gotten the formalities out of the way: The playbook above produces an erroneous "OK", whereas removing "connection" and "become" and instead putting "remote_user" produces "changed".

While testing for erroneous configurations I managed to find one that printed the homebrew-output (I think I forced root everywhere I could):

PLAY [*] ***************************************************************************************************************************************************************************************************

TASK [homebrew_cask] ***************************************************************************************************************************************************************************************
fatal: [localhost]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: root@localhost: Permission denied (publickey,password,keyboard-interactive).\r\n", "unreachable": true
}

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=1    failed=0

**Comment by linux-modder** [comment]
Note: While it was only for debug, the fail on ssh root@localhost is expected on a securely managed system.

Is there anything in ansible.log or the homebrew instance on that node that indicates any permissions issues or space issues?

Also see if adding a notify:    adds any useful info or shows where things might be disconnecting and giving false results back to ansible.

**Comment by du5tball** [comment]
With ansible 2.4.2.0, ansible does throw an error:

`fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Error: Running Homebrew as root is extremely dangerous and no longer supported.\nAs Homebrew does not drop privileges on installation you would be giving all\nbuild scripts full access to your system."}`

With ansible 2.5.0.0, the debug output is:

```
ansible-playbook 2.5.0
  config file = /Users/dustball/.ansible.cfg
  configured module search path = ['/Users/dustball/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dustball/workspace/venv/ansible/lib/python3.6/site-packages/ansible
  executable location = /Users/dustball/workspace/venv/ansible/bin/ansible-playbook
  python version = 3.6.5 (default, Mar 29 2018, 15:37:32) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
Using /Users/dustball/.ansible.cfg as config file
Parsed /Users/dustball/tmp/ansitest/inventory inventory source with ini plugin

PLAYBOOK: play.yml *****************************************************************************************************************************************************************************************
1 plays in play.yml

PLAY [127.0.0.1] *******************************************************************************************************************************************************************************************
META: ran handlers

TASK [homebrew_cask] ***************************************************************************************************************************************************************************************
task path: /Users/dustball/tmp/ansitest/play.yml:6
Using module file /Users/dustball/workspace/venv/ansible/lib/python3.6/site-packages/ansible/modules/packaging/os/homebrew_cask.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: dustball
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/dustball/.ansible/tmp/ansible-tmp-1523785351.171993-68841946270638 `" && echo ansible-tmp-1523785351.171993-68841946270638="` echo /Users/dustball/.ansible/tmp/ansible-tmp-1523785351.171993-68841946270638 `" ) && sleep 0'
<127.0.0.1> PUT /Users/dustball/.ansible/tmp/ansible-local-93325h52i2a3b/tmp2fwfe7ag TO /Users/dustball/.ansible/tmp/ansible-tmp-1523785351.171993-68841946270638/homebrew_cask.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/dustball/.ansible/tmp/ansible-tmp-1523785351.171993-68841946270638/ /Users/dustball/.ansible/tmp/ansible-tmp-1523785351.171993-68841946270638/homebrew_cask.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-oxkbxhwavlklwlnqwrospklmhtwectgw; /usr/bin/python /Users/dustball/.ansible/tmp/ansible-tmp-1523785351.171993-68841946270638/homebrew_cask.py'"'"' && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/dustball/.ansible/tmp/ansible-tmp-1523785351.171993-68841946270638/ > /dev/null 2>&1 && sleep 0'
ok: [127.0.0.1] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "accept_external_apps": false,
            "install_options": [],
            "name": [
                "firefox"
            ],
            "path": "/usr/local/bin",
            "state": "present",
            "update_homebrew": false,
            "upgrade_all": false
        }
    },
```
    "msg": "Cask already installed: firefox"
}
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=0

Note that the output is false, firefox is not installed.
