### ISSUE TITLE
API - Verbosity arguments are not honoured without modifying utils.VERBOSITY by side-effect

### ISSUE THREAD

**Issue by brianmhunt** [ansible/ansible#3880]
It seems that the verbosity argument to e.g. 

```
playbook_cb = callbacks.PlaybookCallbacks(verbose=opts.verbose)
runner_cb = callbacks.PlaybookRunnerCallbacks(stats, verbose=opts.verbose)
```

is not honoured unless one also sets the verbosity by side-effect in `ansible.utils` with something like:

```
from ansible import utils
utils.VERBOSITY = opts.verbose
```

Since modification by side-effect and ignoring arguments is unintuitive and unexpected behaviour, I thought I would raise this issue.

Cheers

**Comment by mpdehaan** [comment]
Appears to be the case.   

I'm putting this in the queue but it's relatively low priority so if you want to send in a patch that would be welcome.

**Comment by brianmhunt** [comment]
Thanks for the acknowledgment and queuing.

I will see if I understand the codebase well enough to pitch a pull request, in due course.

Cheers

**Comment by jimi-c** [comment]
Is this still an issue? The actual lines of code which seem to be referenced above are as follows:

<pre>
# grep -r VERBOSITY *
bin/ansible-playbook:        playbook_cb = callbacks.PlaybookCallbacks(verbose=utils.VERBOSITY)
bin/ansible-playbook:        runner_cb = callbacks.PlaybookRunnerCallbacks(stats, verbose=utils.VERBOSITY)
</pre>

So it would seem these are referencing the global variable correctly and don't suffer from the side-effect described above?

**Comment by mpdehaan** [comment]
@jimi-c there's no code problem in this case but that the test code assigned a value to a global.

C.foo = something

In which case it should set it back at the end of the test function, and probably test using a closure try/except block or whatever to ensure it gets set back.

**Comment by jimi-c** [comment]
Ahh I see, it was for the test code only. I'll remove the pending closure tag then, but as you noted side-effects in test cases are pretty low priority.

**Comment by mpdehaan** [comment]
I see a little bit of usage of this for verbosity in playbooks so I don't want to remove this parameter.

It's basically there to send the constant value down, but lots of code uses the value in constants.py

I checked and verbosity is not a parameter to Runner or the Playbooks class, so this seems ok to me.
