### ISSUE TITLE
Ansible 1.2.2 hangs on playbook with sudo: yes

### ISSUE THREAD

**Issue by ringe** [ansible/ansible#3881]
$ ansible-playbook -v playbooks/vim.yaml 

PLAY [all] *******************************************************************\* 

GATHERING FACTS ***************************************************************

=== stuck here, no feedback ===

$ ansible-playbook -v playbooks/vim.yaml -K
=== all good ===

Adding -T 10 does not help avoid the hang either.

**Comment by mpdehaan** [comment]
So you need to specify --ask-pass if you need a sudo password.

This is true and not a bug.

Stop by the list if you have questions and we are happy to help.

**Comment by mpdehaan** [comment]
See also --ask-sudo-pass

**Comment by ringe** [comment]
@mpdehaan I'm not saying there's something wrong with the way it works, technically. The issue here is valid: There is no feedback, just a hang, which makes ansible unnecessary hard to approach for a new user, like me.

Besides, why does it not time out, even with -T ?

**Comment by ringe** [comment]
I discovered the -K and -k options, which let me do what I wanted. But it took me a lot longer than a simple feedback would, thank you.

**Comment by hjwp** [comment]
this tripped me up too...

**Comment by jsmits** [comment]
Me too...

**Comment by pldimitrov** [comment]
any idea how to get around that when using awx?

**Comment by mpdehaan** [comment]
(A) please don't comment on old tickets, they are unlikely to be read

(B) for AWX/Tower questions, please use the support link on the main website.  This tracker is just for the core project.
