### ISSUE TITLE
Ansible fails to complete - Authentucation failure

### ISSUE THREAD

**Issue by bwghughes** [ansible/ansible#3882]
Background - I'm provisioning a Vagrant box with Ansible. I've isolated the ansible-playbook command being run by the vagrant process.

When I run:

``` bash
$ ansible-playbook --private-key=/Users/ben/.vagrant.d/insecure_private_key --user=vagrant --inventory-file=ansible_hosts --limit=vfq-local-01 --verbose common.yml
```

I get this:

``` bash
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
fatal: [vfq-local-01] => Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-1376921310.08-24143383698732 && chmod a+rx $HOME/.ansible/tmp/ansible-1376921310.08-24143383698732 && echo $HOME/.ansible/tmp/ansible-1376921310.08-24143383698732, exited with result 255

TASK: [Update APT package cache] **********************************************
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ********************************************************************
           to retry, use: --limit @/var/tmp/ansible/common.retry

vfq-local-01               : ok=0    changed=0    unreachable=1    failed=0
```

However, if I `vagrant sssh` into the box, I can run the `mkdir -p` command just fine.

Any ideas?

**Comment by mpdehaan** [comment]
So there's nothing busted with Ansible authentication, if you would like help with this or integrating with Vagrant please stop by the mailing list.

Thanks!

**Comment by bwghughes** [comment]
Hi Michael,

Thanks for your reply - I see you're point, however Vagrant I can SSH into it using the Vagrant SSH config, and just raw ssh login and run the commands-- however the ansible-playbook command fails on gathering facts.

I've tried the ansible-playbook on a non-vagrant (Digital Ocean VM) with the same outcome. Again, I can log into  the VM and manually run the command and it works fine.

Any ideas?

Ben

**Comment by bwghughes** [comment]
Nothing appears in the /var/log/auth.log, so it seems the process isn't logging into the machine - so the message about permissions might be a bit of a red herring.

**Comment by srhyne** [comment]
@bwghughes were you able to figure this out? I'm having the same problem. I can run `vagrant up`, `ssh vagrant` (config from ssh-config). However, I cannot connect through my inventory at all!

`vagrant ansible_ssh_user=vagrant ansible_ssh_port=2222 ansible_ssh_private_key_file=/Users/stephenrhyne/Documents/ansible/vkey ansible_ssh_host=127.0.0.1`

**Comment by pgehres** [comment]
Try setting -c paramiko to the command.

If this works, you can add 
transport = paramiko
to you ansible.cfg to make it the default.

The default changed from paramiko to ssh in ansible 1.3.  I was having similar issues (not with vagrant) and traced this back as the root cause.

**Comment by srhyne** [comment]
Thanks @pgehres. Actually my issue was caused by [issues/3943](https://github.com/ansible/ansible/issues/3943)

I removed my pip installation and git cloned instead. The devel branch is working for me.
