### ISSUE TITLE
External Inventory Script returning ansible_ssh_host in _meta is not effective

### ISSUE THREAD

**Issue by tidzo** [ansible/ansible#3884]
I created a trivial external inventory script which returns the following json:

$> ./inv.py --list
{"webservers": {"hosts": ["testweb01"]}, "_meta": {"hostvars": {"testweb01": {"ansible_ssh_host": "IP_REDACTED"}}}}

I expected to be able to execute the following successfully:

$> ansible -i ./inv.py -m ping testweb01

That failed, but when using the IP (in both the returned json and the invocation) it worked.  This leads me to believe that ansible_ssh_host, and possibly other variables, are not honoured when returned by an external inventory script in _meta.

**Comment by jimi-c** [comment]
Closing this, since the above was merged.
