### ISSUE TITLE
Handle IPv6 addresses in inventory correctly

### ISSUE THREAD

**Issue by jimi-c** [ansible/ansible#3888]
Having an IPv6 address like 'fe80::216:3eff:fe1c:3ec9' in inventory causes this traceback:

<pre>
Traceback (most recent call last):
  File "/opt/devel/ansible/bin/ansible", line 157, in <module>
    (runner, results) = cli.run(options, args)
  File "/opt/devel/ansible/bin/ansible", line 79, in run
    inventory_manager = inventory.Inventory(options.inventory)
  File "/opt/devel/ansible/lib/ansible/inventory/__init__.py", line 102, in __init__
    self.parser = InventoryParser(filename=host_list)
  File "/opt/devel/ansible/lib/ansible/inventory/ini.py", line 40, in __init__
    self._parse()
  File "/opt/devel/ansible/lib/ansible/inventory/ini.py", line 44, in _parse
    self._parse_base_groups()
  File "/opt/devel/ansible/lib/ansible/inventory/ini.py", line 109, in _parse_base_groups
    host = Host(name=hn, port=port)
  File "/opt/devel/ansible/lib/ansible/inventory/host.py", line 31, in __init__
    self.set_variable('ansible_ssh_port', int(port))
ValueError: invalid literal for int() with base 10: '3ec9'
</pre>

IPv6 addresses should be handled appropriately, as shown in https://github.com/ansible/ansible/pull/3879

**Comment by jimi-c** [comment]
One consideration for this - using the same notation as #3879 can be problematic, since the address will appear to be an INI-section header. Escaping the brackets as follows seems to get around the issue:

<pre>
\[fe80::216:3eff:fe1c:3ec9\]
</pre>

But then the connection over SSH fails because the brackets need to be removed:

<pre>
# ansible -vvv -m ping -i /etc/ansible/ipv6 all
<[fe80::216:3eff:fe1c:3ec9]> ESTABLISH CONNECTION FOR USER: root
<[fe80::216:3eff:fe1c:3ec9]> EXEC ['ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '-6', '[fe80::216:3eff:fe1c:3ec9]', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1376944483.19-260166673258505 && echo $HOME/.ansible/tmp/ansible-1376944483.19-260166673258505'"]
[fe80::216:3eff:fe1c:3ec9] | FAILED => Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-1376944483.19-260166673258505 && echo $HOME/.ansible/tmp/ansible-1376944483.19-260166673258505, exited with result 255
</pre>

**Comment by mscherer** [comment]
Using a different notation for ini that from -i is annoying and counter intuitive. I think we should try to use the same fix, and maybe have a refactoring. Since there is now proper tests for in place inventory, this would be easier.

**Comment by mscherer** [comment]
I do not see how we could have a intuitive notation for the ssh port and keep the ini file style. So for now, i left it out. I will add tests later, so for now, that's just for comments/tests.
