### ISSUE TITLE
executable hosts _meta["hostvars"] does not appear to work properly

### ISSUE THREAD

**Issue by earchibald** [ansible/ansible#3896]
I'm having issues with the newly-implemented _meta functionality not providing hostvars, as described in a google groups post:

https://groups.google.com/forum/#!searchin/ansible-project/eugene/ansible-project/YXmKqAypZS8/_BhnVyVBeWoJ

A sample hosts executable is at https://gist.github.com/earchibald/e0ee1905923ac9cc9dbc to demonstrate the issue.

**Comment by jimi-c** [comment]
I'm having some trouble reproducing this. I took your script from the gist and just modified the hostname to the IP of a system I have configured locally. Running against this playbook:

<pre>
$ cat ~/test_3896.yml
---
- hosts: all
  gather_facts: false
  tasks:
  - command: echo '{{ datacenter }}'
</pre>

I get the following output:

<pre>
$ ansible-playbook -vi /etc/ansible/test ~/test_3896.yml 
PLAY [all] ******************************************************************** 
TASK: [command echo '{{datacenter}}'] ***************************************** 
<x.x.x.x> REMOTE_MODULE command echo 'da1'
changed: [x.x.x.x] => {"changed": true, "cmd": ["echo", "da1"], "delta": "0:00:00.024649", "end": "2013-08-22 04:16:48.655268", "rc": 0, "start": "2013-08-22 04:16:48.630619", "stderr": "", "stdout": "da1"}
PLAY RECAP ******************************************************************** 
x.x.x.x              : ok=1    changed=1    unreachable=0    failed=0   
</pre>

Can you confirm if you're seeing the same issue with the script you posted in the gist?

**Comment by earchibald** [comment]
Nope - still happening. Here's the playbook and output:

``` shell
$ cat test-checkvars.yaml
---
- hosts: nssva:!inactive
  gather_facts: false

  tasks:
    - name: test
      debug: "datacenter is {{ datacenter }}"

$ ansible-playbook -vi /tmp/test test-checkvars.yaml

PLAY [nssva:!inactive] ********************************************************

TASK: [test] ******************************************************************
fatal: [131charlie-bos01-cdp01] => One or more undefined variables: 'datacenter' is undefined

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/var/tmp/ansible/test-checkvars.yaml.retry

131charlie-bos01-cdp01     : ok=0    changed=0    unreachable=1    failed=0
```

Let me know what else I can do information-wise. I've already tried moving /usr/share/ansible to {}.bak and doing a fresh make install - just haven't had available cycles to walk through things with pdb.

**Comment by jimi-c** [comment]
Are you sure that name resolves to a server? I notice it's actually being reported as "unreachable", not failed. I just reran this with your sample playbook above and it works fine:

<pre>
ansible-playbook -vvvi /etc/ansible/test test_3896.yml 
PLAY [nssva:!inactive] ******************************************************** 
TASK: [test] ****************************************************************** 
<192.168.1.196> ESTABLISH CONNECTION FOR USER: root
ok: [192.168.1.196] => {"msg": "datacenter is da1"}
PLAY RECAP ******************************************************************** 
192.168.1.196              : ok=1    changed=0    unreachable=0    failed=0   
</pre>

Even with a bogus name in there, it's working for me with just the debug statement:

<pre>
ansible-playbook -vvvi /etc/ansible/test test_3896.yml 
PLAY [nssva:!inactive] ******************************************************** 
TASK: [test] ****************************************************************** 
<some.unknown.name> ESTABLISH CONNECTION FOR USER: root
ok: [some.unknown.name] => {"msg": "datacenter is da1"}
PLAY RECAP ******************************************************************** 
some.unknown.name          : ok=1    changed=0    unreachable=0    failed=0   
</pre>

Can you confirm that you're using the most recent version of the development branch?

**Comment by earchibald** [comment]
I'm certain it's reachable; it works with the non _meta version of the hosts script.

Note that I'm using 'debug' and gather_facts: false to remove specifics about the actual server from the equation.

...

I've updated to the latest dev build and it works. Odd. I know the _meta code was there, because I read through it.

Closing this issue. Thank you!

**Comment by jimi-c** [comment]
Great, glad you got it working. Thanks!
