### ISSUE TITLE
Problems with ansible runner forking 

### ISSUE THREAD

**Issue by chrishamant** [ansible/ansible#3902]
There seems to be some sort of bug causing problems with modules that need a response from the user? 

In my case I was running into this error when I had a playbook that would provision a host with ec2 module, add it to inventory with 'add_host' and then execute remaining tasks. The runner would fail with

``` javascript
{'msg': 'FAILED: argument must be an int, or have a fileno() method.', 'failed': True}
```

after hitting a task that tried to connect to server for first time.
It is something to do with paramiko prompting to accept the ssh host key... (This would happen regardless if I was using host key checking...) If I manually ssh into the instance this error will not occur if I run a playbook connecting to the same host. 

Some googling of this error turned up #3841 which might be related as it alludes to asking for response from user.

I tracked the bug down to 4d1f4479083e87e97419fb554a943dafadce00d5 which I think tries to limit the number of forks used by the runner...

FWIW I was able to fix my specifc problem by just changing 

``` python
if self.forks == 0 or self.forks > len(hosts):
            self.forks = len(hosts)
```

to

``` python
if self.forks == 0 or self.forks > len(hosts):
            self.forks = len(hosts) + 1
```

Sorry to do this inline but I'm not sure a pull request would be appropriate or if this is an appropriate fix...

**Comment by chrishamant** [comment]
https://gist.github.com/chrishamant/9a03c2a404efcea13a8a is a distilled version of what I'm doing which should trigger this error. (assuming you have SSH keys setup correct for this AMI)

**Comment by jimi-c** [comment]
From the looks of it, I would say that in your case len(hosts) is returning 0, so it's always setting the forks to that. I'm checking this out now, I'm just curious why adding 1 to the length would fix the issue.

**Comment by jimi-c** [comment]
Found the problem, stdin wasn't being duped properly when forks == 1. The above patch should correct the issue (I've tested with a variant of your gist and it works fine now).

**Comment by jimi-c** [comment]
Thanks for reporting this!

**Comment by chrishamant** [comment]
thanks for fixing it!

**Comment by bcoca** [comment]
sorry i caused it!

**Comment by jimi-c** [comment]
@bcoca Actually, no you didn't :) It was an odd corner case that popped up when using paramiko with forks==1. Your patch just exposed it since it was dropping the forks down to 1 from the default 5.
