### ISSUE TITLE
inventory: Host variables are merged from all groups

### ISSUE THREAD

**Issue by legionus** [ansible/ansible#3903]
Host variables are merged from all groups if host  if present in more than one group. In the documentation I could not mention that it should happen.

Here is illustration of this:

Testcase:

```
#!/usr/bin/python

import sys
from ansible.inventory import Inventory

if len(sys.argv) != 3:
    print "Usage: swift-inventory INVFILE GROUP"
    sys.exit(1)

inv_file = sys.argv[1]
group    = sys.argv[2]

inv = Inventory(inv_file)

for host in inv.get_hosts(group):
    print host.name, host.get_variables()['var']
```

Inventory file:

```
[group1]
127.0.0.1 var=FOO
[group2]
127.0.0.1 var=BAR
```

$ ./swift-inventory-testcase ./inventory group1
127.0.0.1 BAR

$ ./swift-inventory-testcase ./inventory group2
127.0.0.1 BAR

In the documentation I could not mention that it should happen.

This is because the global dict is used for host names:
https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/ini.py#L106

**Comment by srgvg** [comment]
This is actually referenced here: http://www.ansibleworks.com/docs/playbooks2.html#understanding-variable-precedence

**Comment by legionus** [comment]
Thanks, but it's not my case. I have two groups, and they do not depend on each other.

**Comment by srgvg** [comment]
OK, your case is not explicitly mentioned, but your host is in two groups of the same 'depth', and a variable mentioned in both will have a value from one of them; priority in this case is not explicitly defined (the latter definition overwrites the former here in this example, but depending on how you structure your inventory, eg with dirs, that might turn out in another order), and one might want specify that in this do paragraph.

While in your example code, you ask for variables from different groups, groups get always resolved to the underlying hosts, so basically your script returns the same info both times.

**Comment by legionus** [comment]
My code is just to demonstrate the problem. In the script I use something like the following:

```
- Host: group1
   command: echo {{ inventory_hostname }} {{ var }}
```

In this case, the result is very surprising because group is uniquely determined.

**Comment by srgvg** [comment]
Sorry, same answer as previously. Group is uniquely determined, but here they resolve to the same node, which inherits the same variable set from both groups. Whether you point your play at group1 or group2 doesn't make any difference.

**Comment by legionus** [comment]
I know. So I wrote a code for a better illustration :)

**Comment by jimi-c** [comment]
Since they are the same node, whichever is evaluated last is the one that will win in regards to setting the variable. Variables are not stored on a per-group basis, they are stored with the node. If you need different variables for the same host, you should use group_vars or host_vars files.
