### ISSUE TITLE
ansible_fqdn does not return the same text as facter_fqdn

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#3905]
"ansible_fqdn": "centos3", 
 "facter_fqdn": "centos3.mycompany.com",

Not sure if this is by design or a bug.

**Comment by jimi-c** [comment]
This is pulled from the getfqdn() function of the python socket library, so this should return whatever is set as the system's hostname. If you run the "hostname" command from the CLI, what does it return? Also, is there an entry in /etc/hosts for the IP of the system?

**Comment by patrickw-nf** [comment]
facter's FQDN calculation is not based solely on the server's own configuration, but also pulls in the gateway. This can be a vicious problem when trying to setup Puppet minions! For example, you can have a server with avahi-daemon that tries to report its FQDN as "devmachine.local" but facter will instead claim that it's "devmachine.mycompany.com"

But this is ansible's bug tracker and not Puppet or facter's, so enough of that.

**Comment by jsmartin** [comment]
All fair enough points.  I suppose this shouldn't be a bug then.  Feel free to close.

**Comment by jimi-c** [comment]
Yeah I could see where that might be useful if only the short name were configured, however I don't think it's something we're going to implement. Closing this per the above.
