### ISSUE TITLE
AIX user module problem

### ISSUE THREAD

**Issue by melodous** [ansible/ansible#3908]
User module code for AIX platform dont work correctly when use groups parameter:
# ansible hostname -m user -a "groups=sys,bin,root  append=yes name=user"

hostname| FAILED => failed to parse: Traceback (most recent call last):
  File "//.ansible/tmp/ansible-1377109563.31-193658514588869/user", line 2384, in <module>
    main()
  File "//.ansible/tmp/ansible-1377109563.31-193658514588869/user", line 1407, in main
    (rc, out, err) = user.modify_user()
  File "//.ansible/tmp/ansible-1377109563.31-193658514588869/user", line 537, in modify_user
    return self.modify_user_usermod()
  File "//.ansible/tmp/ansible-1377109563.31-193658514588869/user", line 1284, in modify_user_usermod
    groups.extend(current_groups)
AttributeError: 'set' object has no attribute 'extend'

**Comment by jimi-c** [comment]
What is the python version on the target system?

**Comment by melodous** [comment]
I think the current code doesn’t make sense, there was some illegal operation over the sets, and probably it didn’t work ever. I made some modification, PR3953, in the modify_user_usermod function to make the code similar to other platforms.

Jimi I was able to reproduce the issue with python 2.6 version, but I don't think that was the problem.

**Comment by jimi-c** [comment]
Thanks, I saw your PR and will take a look at it.

**Comment by mpdehaan** [comment]
@jimi-c do you know if this PR is still open or got merged?

Cleaning up github tickets.  Thanks!

**Comment by jimi-c** [comment]
Yes, the PR was https://github.com/ansible/ansible/pull/3953, which was merged, so this is now closed.
