### ISSUE TITLE
get_url: "sslv3 alert handshake failure" for wildcard certs on Centos 6

### ISSUE THREAD

**Issue by bfallik** [ansible/ansible#39098]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

get_url

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.5.1
  config file = /Users/bfallik/sandbox/ansible/ansible.cfg
  configured module search path = [u'/Users/bfallik/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.1/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 22 2018, 21:14:39) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

$ ansible-config dump --only-changed
[DEPRECATION WARNING]: DEFAULT_MODULE_LANG option, Modules are coded to set
their own locale if needed for screenscraping . This feature will be removed in
 version 2.9. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
CACHE_PLUGIN(/Users/bfallik/sandbox/ansible/ansible.cfg) = memory
DEFAULT_ACTION_PLUGIN_PATH(/Users/bfallik/sandbox/ansible/ansible.cfg) = [u'/usr
DEFAULT_BECOME_METHOD(/Users/bfallik/sandbox/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/Users/bfallik/sandbox/ansible/ansible.cfg) = root
DEFAULT_CALLBACK_PLUGIN_PATH(/Users/bfallik/sandbox/ansible/ansible.cfg) = [u'/u
DEFAULT_CONNECTION_PLUGIN_PATH(/Users/bfallik/sandbox/ansible/ansible.cfg) = [u'
DEFAULT_FILTER_PLUGIN_PATH(/Users/bfallik/sandbox/ansible/ansible.cfg) = [u'/usr
DEFAULT_FORKS(/Users/bfallik/sandbox/ansible/ansible.cfg) = 5
DEFAULT_GATHERING(/Users/bfallik/sandbox/ansible/ansible.cfg) = implicit
DEFAULT_HOST_LIST(/Users/bfallik/sandbox/ansible/ansible.cfg) = [u'/Users/bfalli
DEFAULT_JINJA2_EXTENSIONS(/Users/bfallik/sandbox/ansible/ansible.cfg) = jinja2.e
DEFAULT_LOOKUP_PLUGIN_PATH(/Users/bfallik/sandbox/ansible/ansible.cfg) = [u'/usr
DEFAULT_MANAGED_STR(/Users/bfallik/sandbox/ansible/ansible.cfg) = Ansible manage
DEFAULT_MODULE_LANG(/Users/bfallik/sandbox/ansible/ansible.cfg) = C
DEFAULT_POLL_INTERVAL(/Users/bfallik/sandbox/ansible/ansible.cfg) = 15
DEFAULT_REMOTE_PORT(/Users/bfallik/sandbox/ansible/ansible.cfg) = 22
DEFAULT_REMOTE_USER(/Users/bfallik/sandbox/ansible/ansible.cfg) = root
DEFAULT_ROLES_PATH(/Users/bfallik/sandbox/ansible/ansible.cfg) = [u'/Users/bfall
DEFAULT_TIMEOUT(/Users/bfallik/sandbox/ansible/ansible.cfg) = 10
DEFAULT_TRANSPORT(/Users/bfallik/sandbox/ansible/ansible.cfg) = smart
DEFAULT_VARS_PLUGIN_PATH(/Users/bfallik/sandbox/ansible/ansible.cfg) = [u'/usr/s
HOST_KEY_CHECKING(/Users/bfallik/sandbox/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Running ansible from OSX 10.13.4 trying to apply changes to a CentOS 6.9 server.

##### SUMMARY
I'm trying to apply the Datadog [ansible role](https://github.com/DataDog/ansible-datadog) to our servers but encounter an SSL certificate validation error during the [Download RPM key task](https://github.com/DataDog/ansible-datadog/blob/master/tasks/pkg-redhat.yml#L2).

##### STEPS TO REPRODUCE
1. provision centos 6.9 server
2. apply the datadog role

##### EXPECTED RESULTS
success

##### ACTUAL RESULTS
```
TASK [Datadog.datadog : Download new RPM key] **********************************
fatal: [staging-gillnetweb4.clypd.com]: FAILED! => {"changed": false, "msg": "Failed to validate the SSL certificate for yum.datadoghq.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine  (the python executable used (/usr/bin/python) is version: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]) or you can install the `urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: [Errno 1] _ssl.c:492: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure."}
```

**Comment by bfallik** [comment]
I believe this may be caused by Datadog's use of a wildcard cert but I'm not certain of that.

**Comment by sivel** [comment]
I just did a little investigation, and confirmed that the host is using SNI for SSL cert selection.

As described in the error message:

> If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine  (the python executable used (/usr/bin/python) is version: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]) or you can install the `urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended

Due to this, your version of python has no current way to validate SSL certs on hosts utilizing SNI.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by bfallik** [comment]
@sivel ok, thx for confirming at least

**Comment by sivel** [comment]
For documentation on my tests:

```shell
$ dig yum.datadoghq.com +short | head -1
d24tfdc47ugio8.cloudfront.net.
$ echo quit | openssl s_client -servername yum.datadoghq.com -connect d24tfdc47ugio8.cloudfront.net:443 2>&1 | grep '^subject='
subject=/OU=Domain Control Validated/OU=PositiveSSL Wildcard/CN=*.datadoghq.com
$ echo quit | openssl s_client -servername datadoghq.com -connect d24tfdc47ugio8.cloudfront.net:443 2>&1 | grep '^subject='
subject=/CN=datadoghq.com
$ echo quit | openssl s_client -connect d24tfdc47ugio8.cloudfront.net:443 2>&1 | grep '^subject='
$
```
