### ISSUE TITLE
credssp: must be type, not classobj

### ISSUE THREAD

**Issue by DRAKUN** [ansible/ansible#39104]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### OS / ENVIRONMENT

CENTOS/7
##### STEPS TO REPRODUCE

```yaml
192.168.56.101 | UNREACHABLE! => {
    "changed": false,
    "msg": "credssp: must be type, not classobj",
    "unreachable": true
}
```

##### EXPECTED RESULTS

[ansible@localhost UT5]$ ansible windows -i hosts -m win_ping
192.168.56.101 | UNREACHABLE! => {
    "changed": false,
    "msg": "credssp: must be type, not classobj",
    "unreachable": true
}
##### ACTUAL RESULTS

[ansible@localhost UT5]$ ansible windows -i hosts -m win_ping -vvvv                                              
ansible 2.5.0                                                                                                    
  config file = /etc/ansible/ansible.cfg                                                                         
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/module
s']                                                                                                              
  ansible python module location = /usr/lib/python2.7/site-packages/ansible                                      
  executable location = /usr/bin/ansible                                                                         
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]                
Using /etc/ansible/ansible.cfg as config file                                                                    
setting up inventory plugins                                                                                     
Parsed /home/ansible/UT5/hosts inventory source with ini plugin                                                  
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callba
ck/minimal.pyc                                                                                                   
META: ran handlers                                                                                               
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_ping.ps1                          
<192.168.56.101> ESTABLISH WINRM CONNECTION FOR USER: administrateur on PORT 5986 TO 192.168.56.101              
checking if winrm_host 192.168.56.101 is an IPv6 address                                                         
192.168.56.101 | UNREACHABLE! => {                                                                               
    "changed": false,                                                                                            
    "msg": "credssp: must be type, not classobj",                                                                
    "unreachable": true                                                                                          
}                                                                                                                
[ansible@localhost UT5]$                                                                                         

```

```

**Comment by jborean93** [comment]
Can you share your inventory setup as just showing the commands is not enough for us to find out what is happening

needs_info

**Comment by DRAKUN** [comment]
My inventory
````
[windows]
192.168.56.101
````
vim group_vars\windows
````
ansible_user: administrateur
ansible_password: 123456
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
# AUTHENTIFICATION BASIC
# ansible_winrm_transport: basic

# AUTHETIFICATION CREDSSP
ansible_winrm_transport: credssp
ansible_winrm_credssp_disable_tlsv1_2: false
ansible_winrm_message_encryption: always
#ansible_winrm_transport: basic, credssp
````

**Comment by jborean93** [comment]
Hmm that doesn't really show what may be happening unfortunately, are you able to give us some more info such as;

* Run with `-vvvvv` (5 v's), it will display the stacktrace from the error https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/winrm.py#L371
* `pip list` on the Ansible controller
* Changing the auth to Basic, e.g. `ansible_winrm_transport: basic`
* Do any previous versions of Ansible fail

needs_info

**Comment by DRAKUN** [comment]
ansible_winrm_transport: basic is done and OK
I wanted to use CREDSSP authentication

## pip list
`
Package                      Version
---------------------------- ---------
ansible                      2.5.0
asn1crypto                   0.24.0
awscli                       1.15.5
Babel                        0.9.6
backports.ssl-match-hostname 3.4.0.2
botocore                     1.10.5
certifi                      2018.4.16
cffi                         1.11.5
chardet                      3.0.4
colorama                     0.3.7
configobj                    4.7.2
cryptography                 2.2.2
decorator                    3.4.0
docutils                     0.14
enum34                       1.0.4
futures                      3.2.0
httplib2                     0.9.2
idna                         2.6
iniparse                     0.4
ipaddress                    1.0.16
Jinja2                       2.7.2
jmespath                     0.9.3
kitchen                      1.1.1
MarkupSafe                   0.11
ntlm-auth                    1.1.0
paramiko                     2.1.1
perf                         0.1
pip                          10.0.1
ply                          3.4
pyasn1                       0.4.2
pycparser                    2.14
pycrypto                     2.6.1
pycurl                       7.19.0
pygobject                    3.22.0
pygpgme                      0.3
pyliblzma                    0.5.3
pyOpenSSL                    17.5.0
python-dateutil              2.6.1
python-keyczar               0.71rc0
python-linux-procfs          0.4.9
pyudev                       0.15
pywinrm                      0.3.0
pyxattr                      0.5.1
PyYAML                       3.12
requests                     2.18.4
requests-credssp             1.0.0
requests-ntlm                1.1.0
rsa                          3.4.2
s3transfer                   0.1.13
schedutils                   0.4
setuptools                   39.0.1
six                          1.11.0
slip                         0.4.0
slip.dbus                    0.4.0
urlgrabber                   3.10
urllib3                      1.22
wheel                        0.31.0
xmltodict                    0.11.0
yum-metadata-parser          1.1.4
`

**Comment by jborean93** [comment]
Thanks can you run with `-vvvvv`, the requests-credssp version you have is quite new and possibly has a bug in it. The traceback we get with 5v's should let us know where it is failing

**Comment by DRAKUN** [comment]
here the debug
````
[ansible@localhost UT5]$ ansible windows -i hosts -m win_ping -vvvvv
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /home/ansible/UT5/hosts inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/minimal.pyc
META: ran handlers
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_ping.ps1
<192.168.56.101> ESTABLISH WINRM CONNECTION FOR USER: administrateur on PORT 5986 TO 192.168.56.101
checking if winrm_host 192.168.56.101 is an IPv6 address
<192.168.56.101> WINRM CONNECT: transport=credssp endpoint=https://192.168.56.101:5986/wsman
<192.168.56.101> WINRM CONNECTION ERROR: must be type, not classobj
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 345, in _winrm_connect
    self.shell_id = protocol.open_shell(codepage=65001)  # UTF-8
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 157, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 234, in send_message
    resp = self.transport.send_message(message)
  File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 256, in send_message
    response = self._send_message_request(prepared_request, message)
  File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 261, in _send_message_request
    response = self.session.send(prepared_request, timeout=self.read_timeout_sec)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 625, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests_credssp/credssp.py", line 447, in response_hook
    response = self.handle_401(response, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests_credssp/credssp.py", line 486, in handle_401
    out_token, step_name = credssp_gen.send(in_token)
  File "/usr/lib/python2.7/site-packages/requests_credssp/credssp.py", line 111, in credssp_generator
    ts_request = TSRequest()
  File "/usr/lib/python2.7/site-packages/requests_credssp/asn_structures.py", line 105, in __init__
    super(TSRequest, self).__init__(**kwargs)
TypeError: must be type, not classobj

192.168.56.101 | UNREACHABLE! => {
    "changed": false,
    "msg": "credssp: must be type, not classobj",
    "unreachable": true
}

````

**Comment by jborean93** [comment]
I am only able to replicate this issue once I install a version of pyasn1 that is really old (0.1.1),  all versions from 0.3.1 and newer work fine and that is the minimum set in the package requirements for requests-credssp. From what it sounds like it could be that pyasn1 that is installed in the same Python environment as Ansible is too old. Are you able to try the following

* Verify that `which pip` is showing `/usr/bin/pip`
* Verify that `pyasn1>=0.3.1` is installed when running `/usr/bin/pip list`
* If all else fails, run `/usr/bin/pip install pyasn1 --upgrade --force-reinstall` to completely reinstall that package

I can definitely get it working, I just spun up a new Centos 7 container and ran the following

```
yum install -y epel-release
yum install -y python-pip
pip install ansible pywinrm[credssp]
```

From there CredSSP worked fine when connecting to a Windows host so something seems to be up with your Python install.

**Comment by DRAKUN** [comment]
Okay 
````
[ansible@localhost UT5]$ which pip
/usr/bin/pip
````

my pyasn version 
````
pyasn1                       0.4.2
````
upgrading 
````
[ansible@localhost UT5]$ sudo /usr/bin/pip install pyasn1 --upgrade --force-reinstall
Collecting pyasn1
  Using cached https://files.pythonhosted.org/packages/ba/fe/02e3e2ee243966b143657fb8bd6bc97595841163b6d8c26820944acaec4d/pyasn1-0.4.2-py2.py3-none-any.whl
Installing collected packages: pyasn1
  Found existing installation: pyasn1 0.4.2
    Uninstalling pyasn1-0.4.2:
      Successfully uninstalled pyasn1-0.4.2
Successfully installed pyasn1-0.4.2
````
yum install -y epel-release
````
Determining fastest mirrors
 * base: mirror.steadfast.net
 * epel: mirror.awanti.com
 * extras: mirror.steadfast.net
 * updates: mirror.steadfast.net
Package epel-release-7-11.noarch already installed and latest version
Nothing to do
````
yum install -y python-pip
````
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : python2-pip-8.1.2-6.el7.noarch                                                                                                            1/1

  Verifying  : python2-pip-8.1.2-6.el7.noarch                                                                                                            1/1


Installed:
  python2-pip.noarch 0:8.1.2-6.el7


Complete!
````
pip install ansible pywinrm[credssp]
````
[ansible@localhost UT5]$ sudo pip install ansible pywinrm[credssp]
Requirement already satisfied (use --upgrade to upgrade): ansible in /usr/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pywinrm[credssp] in /usr/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /usr/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /usr/lib64/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): paramiko in /usr/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): cryptography in /usr/lib64/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/site-packages (from pywinrm[credssp])
Requirement already satisfied (use --upgrade to upgrade): requests-ntlm>=0.3.0 in /usr/lib/python2.7/site-packages (from pywinrm[credssp])
Requirement already satisfied (use --upgrade to upgrade): requests>=2.9.1 in /usr/lib/python2.7/site-packages (from pywinrm[credssp])
Requirement already satisfied (use --upgrade to upgrade): xmltodict in /usr/lib/python2.7/site-packages (from pywinrm[credssp])
Requirement already satisfied (use --upgrade to upgrade): requests-credssp>=0.0.1; extra == "credssp" in /usr/lib/python2.7/site-packages (from pywinrm[credssp])
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/lib64/python2.7/site-packages (from jinja2->ansible)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /usr/lib/python2.7/site-packages (from paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.7; platform_python_implementation != "PyPy" in /usr/lib64/python2.7/site-packages (from cryptography->ansible)
Requirement already satisfied (use --upgrade to upgrade): enum34; python_version < "3" in /usr/lib/python2.7/site-packages (from cryptography->ansible)
Requirement already satisfied (use --upgrade to upgrade): asn1crypto>=0.21.0 in /usr/lib/python2.7/site-packages (from cryptography->ansible)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.1 in /usr/lib/python2.7/site-packages (from cryptography->ansible)
Requirement already satisfied (use --upgrade to upgrade): ipaddress; python_version < "3" in /usr/lib/python2.7/site-packages (from cryptography->ansible)
Requirement already satisfied (use --upgrade to upgrade): ntlm-auth>=1.0.2 in /usr/lib/python2.7/site-packages (from requests-ntlm>=0.3.0->pywinrm[credssp]) Requirement already satisfied (use --upgrade to upgrade): certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests>=2.9.1->pywinrm[credssp])
Requirement already satisfied (use --upgrade to upgrade): chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests>=2.9.1->pywinrm[credssp]) Requirement already satisfied (use --upgrade to upgrade): urllib3<1.23,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests>=2.9.1->pywinrm[credssp]) Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL>=16.0.0 in /usr/lib/python2.7/site-packages (from requests-credssp>=0.0.1; extra == "credssp"->pywinrm[credssp])
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/lib/python2.7/site-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography->ansible)
````
it's already work with basic auth 
````
[ansible@localhost UT5]$ ansible windows -i hosts  -m "win_ping"
192.168.56.101 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
````

now it's work too with credssp
````
[ansible@localhost UT5]$ ansible windows -i hosts  -m "win_ping"
192.168.56.101 | SUCCESS => {                                   
    "changed": false,                                           
    "ping": "pong"                                              
}                                                               
````

Thanks bro

**Comment by jborean93** [comment]
No worries, glad it started working again. I believe the reinstall of the oyasn1 package through pip must have blow away any older remnant of pyasn1 and forced the newer package. While there is still probably a better way of fixing it, it seems to work for now.

**Comment by snwbr** [comment]
Hi there! I'm facing the same situation, my pip is under /usr/local/bin but the rest is the same. I've reinstalled pyasn1 but didn't work. I'm on a Mac. Have you faced this issue on a Mac?
Thanks!
