### ISSUE TITLE
Host *\n User: foo not detected in ssh transport

### ISSUE THREAD

**Issue by rektide** [ansible/ansible#3911]
```
Host *
  User: foo
```

as ~/.ssh/config is not detected by ansible for ssh transport. Thus, specifying a -u $USER will have no effect (for all cases where $USER != foo, and ssh will use foo, not $USER. This leaves no way to connect as $USER.

**Comment by mpdehaan** [comment]
Correct, set the ansible_ssh_user variable in inventory.

Ansible allows connecting from _MULTIPLE_ users to the same hosts.

Think of it as a general purpose systems management application, not just an extension of SSH.
