### ISSUE TITLE
Fix inheritance order to evaluate group_vars and host_vars after roles

### ISSUE THREAD

**Issue by gregbuehler** [ansible/ansible#3912]
Roles clobbers group_vars, host_vars, and other roles. You can reproduce/demonstrate this issue using the following example.

See: https://github.com/gregbuehler/ansible-inheritance-demo

```
[root@test ~]# cat /opt/ansible/common
variable is set from from_roles_testapp

[root@test ~]# cat /opt/ansible/testapp
variable is set from from_roles_testapp
```

Ansible should evaluate variables such that roles can be modified by group_vars and host_vars, not the opposite.

[Understanding Variable Precedence](http://www.ansibleworks.com/docs/playbooks2.html#id27) makes an attempt at explaining away the convoluted inheritance system where some variables clobber others, but it seems like this could use further consideration.

Roles would seemingly be better suited higher in the hierarchy:
group_vars/all -> roles -> group_vars/per_group -> host_vars

**Comment by jimi-c** [comment]
We have https://github.com/ansible/ansible/pull/3891 open, and are discussing this there.
