### ISSUE TITLE
Ansible 2.5.1 breaks Molecule tests

### ISSUE THREAD

**Issue by tonk** [ansible/ansible#39157]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/tonk/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

##### CONFIGURATION

```
# ansible-config dump --only-changed
(results in nothing)
```

##### OS / ENVIRONMENT

```
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 27 (Twenty Seven)
Release:        27
Codename:       TwentySeven
```

##### SUMMARY
Testing roles with Ansible Molecule version 2.5.0 work, with version 2.5.1 it results in a 'KeyError'

##### STEPS TO REPRODUCE

```yaml
molecule create
molecule converge
molecule verify
```
Testinfra file, Molecule configuration file and error in a gist:
https://gist.github.com/tonk/50cd329b029cfb0d654f5afc54b451db

When I run the `molecule verify with these packages:

```
ansible==2.5.0
docker==2.7.0
docker-compose==1.9.0
docker-py==1.10.6
docker-pycreds==0.2.2
dockerpty==0.4.1
molecule==2.12.1
pymarkdownlint==0.3.1
requests==2.18.4
requestsexceptions==1.4.0
```
everything works as expected.

When I upgrade Ansible to version 2.5.1 the error occurs.

##### EXPECTED RESULTS

100 % correct infra tests

##### ACTUAL RESULTS

The run breaks with with the message:

```
    /usr/lib/python2.7/site-packages/ansible/config/manager.py:304: in get_config_value_and_origin
        defs = self._plugins[plugin_type][plugin_name]
    E   KeyError: 'inventory'
    !!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
    =========================== 1 error in 1.85 seconds ============================
```

```
See: https://gist.github.com/tonk/50cd329b029cfb0d654f5afc54b451db error.log
```

**Comment by sivel** [comment]
Should This Be Filed Elsewhere?
===============================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be something that should be filed against another project or bug tracker, and let us explain our reasons for thinking this:

   * This appears to be a bug in the other referenced project

If you can stop by the tracker or forum for one of those projects, we'd appreciate it.  

Should you still wish to discuss things further, or if you disagree with our thought process, please stop by one of our two mailing lists:

  * https://groups.google.com/forum/#!forum/ansible-project
  * https://groups.google.com/forum/#!forum/ansible-devel

We'd be happy to discuss things.

Thank you once again!
