### ISSUE TITLE
Feature Request: let authorized_keys module accept from= and command=

### ISSUE THREAD

**Issue by agshekeloh** [ansible/ansible#3921]
Running: ansible 1.3 (devel ae98a025bb) last updated 2013/08/21 11:59:02 (GMT -400)

The authorized_keys module strips quotes from keys. If you have a key that includes from="x.x.x.x" or command="whatever", the needed quotes are removed from the key.

It would be nice if the module would accept these features in keys. Without it, I'm back to copying keys as files.

**Comment by mscherer** [comment]
Looking at the module, it seems there is a key_options argument that would solve your issue. Have you looked at it ?

**Comment by mpdehaan** [comment]
should be done now, so closing
