### ISSUE TITLE
option to pipe command output back from remote server

### ISSUE THREAD

**Issue by crucialfelix** [ansible/ansible#3939]
In the case of any prompt or unexpected result it is impossible to know that the remote command is stuck.  Eventually you just have to give up and kill it and I can't find anyway to discover what the problem was.

/var/log/syslog does log the command.  maybe it could at least be possible to at least opt to direct stdout/stderr to a logfile on the remote server.

but echoing results back to the initiating computer would be ideal.

**Comment by mpdehaan** [comment]
There's already a feature request open to make async show intermediate status.

I think it's unlikely that we'll do this for things that aren't async.

**Comment by crucialfelix** [comment]
but how about logging stdout ?  that seems to me easy.  I had absolutely no way to figure out what failed and had to eventually just make a script on the server and run this step manually.  

command: is not async, is it ?
