### ISSUE TITLE
Ansible Failed to connect to the host via ssh: Permission denied

### ISSUE THREAD

**Issue by ajit2678** [ansible/ansible#39461]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by ajit2678** [comment]
```
192.168.10.23 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.10.23 port 223: Connection refused\r\n",
    "unreachable": true
}
```

**Comment by rusik69** [comment]
maybe you need port 22, not 223

**Comment by ajit2678** [comment]
No I have configure ssh to listen on port 223 if I enabled root access,
then ansible ping at port 223 but when I disabled the root access it show
me this error message

**Comment by rusik69** [comment]
ansible by default login as root to remote hosts

**Comment by ajit2678** [comment]
why i can assign ansible to different port to listen, there must me a way to connected ansible with different port

plz help anyone

**Comment by rusik69** [comment]
google says you can use somethink like 
`[docker-hosts]
docker1:223`

**Comment by ajit2678** [comment]
means docker1 is a host name then the port number

**Comment by rusik69** [comment]
yeah

**Comment by ajit2678** [comment]
That doesn't work for me. 
I try that to.
same error i am getting
Failed to connect to the host via ssh: Permission denied (publickey,password).

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
