### ISSUE TITLE
ovirt.ini - mentioning of libcloud is wrong (oVirt does not support it) in ovirt.ini

### ISSUE THREAD

**Issue by mykaul** [ansible/ansible#39478]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

```
2.5.1
```

##### SUMMARY
In https://github.com/ansible/ansible/blob/devel/contrib/inventory/ovirt.ini , the lines around:
```
# ovirt Service Account configuration information can be stored in the
# libcloud 'secrets.py' file.  Ideally, the 'secrets.py' file will already
# exist in your PYTHONPATH and be picked up automatically with an import
# statement in the inventory script.  However, you can specify an absolute
# path to the secrets.py file with 'libcloud_secrets' parameter.
```

Are a bit wrong - there's no libcloud support for oVirt, etc.

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by mykaul** [comment]
CC @mwperina  , @machacekondra

**Comment by machacekondra** [comment]
This file is actually shared with `ovirt.py` dynamic inventory used by V3 API which use it libcloud. Anyway I will improve the comment so it's clear.
