### ISSUE TITLE
Add dpkg_options to the apt module

### ISSUE THREAD

**Issue by telbizov** [ansible/ansible#3955]
Hey guys,

This is regarding a missing piece of functionality in the "apt" module.
Currently we are not able to pass custom DPKG_OPTIONS from the playbooks.
The values are hardcoded as:

```
DPKG_OPTIONS = '-o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"'
```

In the specific case I need to pass "--force-confnew" instead of those.

What I envision is:
- Keep the current DPKG_OPTIONS as defaults
- Add a new option in the apt module called "dpkg_options" which will accept options like the above and will overwrite the defaults
- Document the new option and point the defaults that the module assumes

Thank you

Rumen Telbizov,
[Unix Systems Administrator](http://telbizov.com)

**Comment by somodi** [comment]
+1
I come here needing to pass "--allow-unauthenticated" option.
I would be wonderfull.

**Comment by ReifiedException** [comment]
We need dpkg_options, too.

**Comment by malvim** [comment]
Yes, "--allow-unauthenticated" would be great, as for some machines we use a local repo (with unauthenticated packages) and install fails unless we set "force=yes" on our apt directive.

Of course having to set "force=yes" is not a generally good solution, since it will bypass other errors as well.

**Comment by malvim** [comment]
By the way, here's the workaround I did in order to be able to pass "--allow-unauthenticated" to apt: https://gist.github.com/malvim/6802083 .

This is probably not an acceptable solution, but it does work for general arguments. Not sure how to do it for dpkg_options.

**Comment by srgvg** [comment]
FYI, one can add lots of options in a more permanent way to apt.conf, e.g. `APT::Get::AllowUnauthenticated "true";`

**Comment by mgudzenko** [comment]
Dpkg_options  important for us

**Comment by malvim** [comment]
Thanks @sergevanginderachter !

Though I think this is a nice option (and probably one I'll be using, since it's better than maintaining a custom apt module), having extra_args is not unheard of (pip module has it, for instance), and it seems like a nice thing to have.

**Comment by jctanner** [comment]
Closing per #4358
