### ISSUE TITLE
Typo in first page of porting guide documentation

### ISSUE THREAD

**Issue by msoultan** [ansible/ansible#39581]
##### ISSUE TYPE

 - Documentation Report

##### ANSIBLE VERSION

```

```

##### SUMMARY

This page has a typo:

http://docs.ansible.com/ansible/latest/porting_guides/porting_guides.html

The very first sentence is missing a word - I'm guessing it's supposed to be "port":

"This section lists porting guides that can help you [???] playbooks, plugins and other parts of your Ansible infrastructure from one version of Ansible to the next."

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by Akasurde** [comment]
@msoultan Thanks for reporting this issue.

**Comment by Akasurde** [comment]
resolved_by_pr #39582

**Comment by Akasurde** [comment]
Closing this issue as PR is merged. If issue persists, please feel free to re-open.
