### ISSUE TITLE
Failure when using "sudo: yes" and -K on sudo command that doesn't ask for password

### ISSUE THREAD

**Issue by zoni** [ansible/ansible#3958]
I have noticed that Ansible 1.2.3 as well as the current HEAD fails when you run a task with `sudo: yes` and supply the sudo password on the command line with `-K` when sudo doesn't prompt for a password. Specifically:

This is executed on a system which allows key-based SSH login as root, with sudo set up so that root can run any command without being prompted for a password (which is pretty standard). So the output of `sudo whoami` as root would just be `root`, no password prompt or anything. 

It also has a normal user account, `zoni.tb`, which can execute any command as root by using sudo, and being prompted for that user's password (though it would likely yield te same results with `Defaults targetpw`), such that:

```
$ sudo whoami
[sudo] password for zoni.tb: 
root
```

Given the following inventory file `test.inventory`:

``` yaml
localhost
```

and the playbook `test.yml`:

``` yaml

---
- hosts: localhost
  gather_facts: no
  user: root
  sudo: yes
  tasks:
   - name: Expose ansible bug
     shell: whoami
```

We get the following (expected) output when running ansible without `-K`:

```
ansible-playbook test.yml -i test.inventory -v

PLAY [localhost] ************************************************************** 

TASK: [Expose ansible bug] **************************************************** 
changed: [localhost] => {"changed": true, "cmd": "whoami ", "delta": "0:00:00.001987", "end": "2013-08-28 15:59:34.169458", "rc": 0, "start": "2013-08-28 15:59:34.167471", "stderr": "", "stdout": "root"}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```

We get a failure however when we do specify a sudo password, using `-K` (note: It doesn't matter whether we specify a correct or incorrect password):

```
ansible-playbook test.yml -i test.inventory -v -K
sudo password: 

PLAY [localhost] ************************************************************** 

TASK: [Expose ansible bug] **************************************************** 
fatal: [localhost] => ssh connection closed waiting for sudo password prompt

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/zoni.tb/test.retry

localhost                  : ok=0    changed=0    unreachable=1    failed=0   
```

When in our playbook we change `user: root` to `user: zoni.tb` and execute again with `-K`, we once again get correct output:

```
ansible-playbook test.yml -i test.inventory -v -K
sudo password: 

PLAY [localhost] ************************************************************** 

TASK: [Expose ansible bug] **************************************************** 
changed: [localhost] => {"changed": true, "cmd": "whoami ", "delta": "0:00:00.002947", "end": "2013-08-28 16:04:09.160855", "rc": 0, "start": "2013-08-28 16:04:09.157908", "stderr": "", "stdout": "root"}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```

**Comment by mpdehaan** [comment]
-K is --ask-sudo-pass and should only be specified when your sudo is going to prompt for a password.

This is expected behavior.

So in your case, don't pass "-K" and that means "I don't have a sudo password".

**Comment by zoni** [comment]
This was definitely not "expected behavior" from my point of view :) I've opened a pull request to make a mention of this in the docs, since I expected it to just ignore the password on tasks which don't need one. Hopefully that will prevent confusion for other people.

I don't quite agree this should be expected behaviour though. I have in the past had sudo setups where some commands would be executed password-less, but others required a password to be specified. Granted this isn't very common, but I think it's still a valid use-case.

I don't see a way to make Ansible and sudo play nice in such a situation unless you split up your playbooks there, to specify one with `-K` for commands which will ask for a password, and leave it off on the other playbooks where you do stuff that won't prompt for a password.

Or am I overlooking something here?
