### ISSUE TITLE
Regression in variable expansion

### ISSUE THREAD

**Issue by karniemi** [ansible/ansible#39590]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
2.5.1
```

##### SUMMARY

Ansible 2.5.1 introduced a regression in variable expansion. For example, the following no longer works as it used to:

```
---
- hosts: all
  vars:
    list:
      - item1
      - item2
  tasks:
    - set_fact: pacs="{{ pacs|default([]) }} + [ '{{ item }}' ]"
      with_items:
        - "{{ list }}"
    - debug: msg="{{ item }}"
	  with_items:
	    - "{{ pacs }}"
```

Up to ansible 2.5 both item1 and item2 were included in pacs, and both were printed out by debug module. In 2.5.1 only item2 ends up in pacs.

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

With the example, both item1 and item2 should be in pacs
##### ACTUAL RESULTS

With the example, only item1 is included in pacs

```

```

**Comment by Akasurde** [comment]
@karniemi Thanks for reporting this issue. This has been resolved in #38302 and has been included in the 2.5.2 release.

If you have further questions please stop by IRC or the mailing list:

- IRC: #ansible on irc.freenode.net
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
