### ISSUE TITLE
Allow arbitrary parameters to an inventory script

### ISSUE THREAD

**Issue by danhanks** [ansible/ansible#3962]
Would like to be able to specify -i "/some/path/inventory.sh --arg1 --arg2"

so, '-i /some/where/inventory' would act as currently does, looking for the executable bit on the file specified, but if the argument to -i is space delimited, additional tokens would be interpreted as extra arguments to pass to the inventory script.

**Comment by jimi-c** [comment]
We already have the --extra-vars option for this (when using ansible-playbook), or the host/group vars should be used as designed.

**Comment by gregbuehler** [comment]
This should be reopened. Extra vars does not cover arguments passed to a script.

Consider:
`ansible-playbook -i "./somescript.py --find-by term" ./playbook.yaml`

**Comment by jimi-c** [comment]
Ahh, I understand, however this should be done through environment variables instead.

**Comment by gregbuehler** [comment]
@jimi1283 I agree. scripts should look at either environment variables or at an ini file.

**Comment by resmo** [comment]
wasn't there a merge recently that covered:

```
ansible-playbook playbook.yaml -i  < ./somescript.py --find-by term
```

?
