### ISSUE TITLE
Documentation layout issues make it illegible on Firefox Nightly

### ISSUE THREAD

**Issue by mlissner** [ansible/ansible#39644]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
The table of options on every page of the documentation

##### ANSIBLE VERSION
```
n/a
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
Linux, Firefox Nightly

##### SUMMARY
On the documentation website, all of the tables are nearly illegible on Firefox Nightly. They all look like this:

![screenshot from 2018-05-02 14-56-04](https://user-images.githubusercontent.com/236970/39551336-7b6b4136-4e19-11e8-8ef9-13a3e66816c3.png)

##### STEPS TO REPRODUCE
1. Install and open Firefox Nightly
2. Load up any page in the docs, for example: http://docs.ansible.com/ansible/latest/modules/lineinfile_module.html

##### EXPECTED RESULTS
Table should be legible. 

##### ACTUAL RESULTS
Table is nearly illegible due to being collapsed. Weird stuff.

**Comment by sivel** [comment]
Should This Be Filed Elsewhere?
===============================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be something that should be filed against another project or bug tracker, and let us explain our reasons for thinking this:

   * This only seems to occur in Firefox nightly an no other browser.

If you can stop by the tracker or forum for one of those projects, we'd appreciate it.  

Should you still wish to discuss things further, or if you disagree with our thought process, please stop by one of our two mailing lists:

  * https://groups.google.com/forum/#!forum/ansible-project
  * https://groups.google.com/forum/#!forum/ansible-devel

We'd be happy to discuss things.

Thank you once again!

**Comment by mlissner** [comment]
I mean, suit yourself. If it's broken in nightly today, it'll be broken in Firefox itself soon. It's possible this is a weird edge case, but nightly doesn't tend to have display bugs like this. Usually this means your website is doing something weird that used to work, but won't keep working for much longer..
