### ISSUE TITLE
Previously working ansible 1.1. playbook using authorized_key fails under ansible 1.2.3

### ISSUE THREAD

**Issue by justinkitagawa** [ansible/ansible#3968]
A previously working playbook is failing running with ansible 1.2.3.  Using the authorized_key module, I get the following error:

```
% bin/ansible-playbook -u root  -vvv -i hostfile  -k playbook/setup-auth.yml

TASK: [Enabled key-based ssh access for root] ********************************* 
<x.x.x.x> ESTABLISH CONNECTION FOR USER: root
fatal: [x.x.x.x] => to use -c ssh with passwords, you must install the sshpass program
```

With ansible-1.1, the playbook works as excepted.

Environment:
- python 2.7.5
- ansible 1.2.3

Target host operating system:
- Debian 6.0 64-bit VM

Playbook:

```
##
# setup-auth.yml
# Ansible playbook for initializing ansible and system
#
#

---
- hosts: targethost
  sudo: no
  gather_facts: no
  vars:
  - keyuser: "ansible"
  - authusers: [ "root" ]

  tasks:

  - name: Enabled key-based ssh access for root
    authorized_key: user=$item key='$FILE(/home/$keyuser/.ssh/id_rsa.pub)'
    with_items: $authusers
```

**Comment by jimi-c** [comment]
In 1.1 paramiko was the default transport, but in 1.2+ it is "smart" (which uses ssh when it detects the ControlPersist option is available). You can either install the sshpass package or you should use "-c paramiko" (or you can make paramiko the default in your ansible.cfg).

**Comment by justinkitagawa** [comment]
James-

Adding the -c paramiko flag fixed the issue. 

```
% bin/ansible-playbook -u root  -vvv -i hostfile  -k -c paramiko playbook/setup-auth.yml
```

Many thanks.
