### ISSUE TITLE
Support One-Time Passwords

### ISSUE THREAD

**Issue by nimajalali** [ansible/ansible#3969]
I use a [YubiKey](http://www.yubico.com/faq/what-is-a-yubikey/) to generate one-time passwords (otp) for ssh authentication. At the ssh password prompt I enter my usual password followed by the OTP. 

Unfortunately Ansible has the assumption that passwords do not vary per host or per session. 

I use fireball to get around the per session limitation. So Ansible uses the password once and then the fireball connection takes over.

This work around breaks down once you have multiple hosts because fireball will attempt to use the same password to setup all the hosts. The first host wins and the rest fail due to the OTP being used again.

Hitting a wall here and I'd rather not allow access to the servers without the OTP solution.

Thoughts?

**Comment by bcoca** [comment]
If your ssh is modern enough you can use ssh persistent connections to
avoid session issue (ansible tries to default to this). I don't see a
solution for the otp, aside from a patch.

Brian Coca

**Comment by mpdehaan** [comment]
Yep, not something we're immediately planning to support.

You should really consider SSH keys.

**Comment by JensRantil** [comment]
Ping. I am too interested in hearing about whether this is possible or not.

**Comment by markusfrei1** [comment]
Ping, too. We have the same issue, using YubiKeys (and therefore password auth) for ssh authentication.

**Comment by JensRantil** [comment]
I am no longer interested in this as I have switched to Saltstack for various reasons. This was one.
