### ISSUE TITLE
Option to enable playbook output on ansible-pull

### ISSUE THREAD

**Issue by axlroden** [ansible/ansible#3973]
When running an ansible-pull on a large playbook there is no feedback on progress until it is completely run trough.

This can be somewhat annoying if you are running an automated process but have no idea if it's stalled or not.

It would be nice to have an option of at least being able to turn on regular playbook output.

From briefly looking at the ansible-pull code, it seems to be pretty doable, but I'm no expert so I doubt you want my attempt at a bad hack in there :)

**Comment by jctanner** [comment]
@axlroden I stole the code from ssh.py to replace p.communicate() in ansible-pull if --verbose is passed. Try it out and let me know your results. Thanks!

**Comment by axlroden** [comment]
cool! I'll have a check tomorrow morning

**Comment by jctanner** [comment]
Reverting patch, and moving to a feature brach on my own fork.

**Comment by jctanner** [comment]
@axlroden I made a pull request to test this before merging into devel. https://github.com/ansible/ansible/pull/5362
