### ISSUE TITLE
Pull request #3488 merged to devel, but not tagged for release

### ISSUE THREAD

**Issue by jshprentz** [ansible/ansible#3979]
Ansible 1.2.3 failed with the following error when the `apt` module failed to upgrade with the `force=yes` flag set:

```
TASK: [Upgrade packages] ******************************************************
<sonar.shprentz.com> REMOTE_MODULE apt upgrade=dist update_cache=yes cache_valid_time=3600 force=yes
failed: [sonar.shprentz.com] => {"failed": true, "item": ""}
msg: '/usr/bin/apt-get dist-upgrade' failed: E: There are problems and -y was used without --force-yes
```

This problem was fixed by pull request #3488. That request was merged to devel on 2013-07-11, but was not tagged for any subsequent release.

Please include it in 1.2.4 or 1.3. Thanks.

**Comment by mpdehaan** [comment]
Ansible 1.3 has not been released yet and is due next week.
