### ISSUE TITLE
 ansible/docs/templates/plugin.rst.j2 has a CSS bug

### ISSUE THREAD

**Issue by simbalion** [ansible/ansible#39822]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
 ansible/docs/templates/plugin.rst.j2

##### ANSIBLE VERSION
current live web docs

##### CONFIGURATION
unrelated

##### OS / ENVIRONMENT
unrelated

##### SUMMARY
In Firefox 60b (developer browser) the parameters section doesn't display properly. 

##### STEPS TO REPRODUCE
View page in Firefox 60b

##### EXPECTED RESULTS
see attachment
![ansible_firefox_height_bug2](https://user-images.githubusercontent.com/19638988/39723769-d7121038-5214-11e8-95fe-fe0d7a7c043d.png)

##### ACTUAL RESULTS
see attachment
![ansible_firefox_height_bug](https://user-images.githubusercontent.com/19638988/39723768-d6fed5a4-5214-11e8-9503-5d2a862c1294.png)

**Comment by simbalion** [comment]
I narrowed down the issue to table.documentation-table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(2) and similar elements, the .return-value-column class has a height of 1px. If that's removed the problem goes away. In general height should not be explicitly defined, and should be allowed to be dictated by content + padding.

**Comment by sivel** [comment]
Please reach out to the firefox dev team.  As this only impacts the unreleased version of firefox, we are currently inclined to believe it is a bad change in that browser.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by simbalion** [comment]
It's not a bug in the browser, it's bad CSS. Firefox is trying to render the height as 1px, it's doing what it's told to do.

There's no reason you would ever define height as 1 pixel, except as a hack to make up for other mistakes in CSS. The height should be 'auto', it's a bug in the CSS.

That the browser doesn't correct for developer errors is not really a 'bug' in the browser.
