### ISSUE TITLE
role defaults behavior broken by commit 

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#3985]
See https://github.com/ansible/ansible/commit/e0df5b58889d0d8551b556630d97b8a3debcc8f1

role defaults need to have lower priority than inventory.

This commit undoes that behavior in the attempt to namespace things, and the previous behavior was more important.

**Comment by jimi-c** [comment]
I reverted the portion of the commit that broke the new feature, and will work out a different way to achieve this.
