### ISSUE TITLE
unable to use item variable with "notify"

### ISSUE THREAD

**Issue by acranox** [ansible/ansible#3988]
I have a dictionary with all the parameters for a bunch of config files.  I want to do this:

```
  template: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  notify: restart {{ item.name }}
  with_items: config_files
```

but when I run the playbook, I just get this:

```
ERROR: change handler (restart {{item.name}}) is not defined
```

it looks like I can't resolve the item variables within the notify function.  Or maybe my syntax is just all wrong?

**Comment by jimi-c** [comment]
Can you show your handler definition?

**Comment by acranox** [comment]
the handler looks like this:

```
- name: restart ntp
  action: service name=ntp state=restarted
```

an example of the variable config_files would be this:
config_files: [{name: "ntp", src: "ntp.conf.j2", dest: "/etc/ntp.conf", owner: "ntp", group: "ntp", mode: "0444"}]

**Comment by acranox** [comment]
it looks like this should work, based on the example in this merge:
https://github.com/ansible/ansible/pull/456

**Comment by mpdehaan** [comment]
I would not really expect it to work, as it becomes effectively one single task object to return a value.

However, it would be nice if it did.

(Also -- very old ticket number)

**Comment by acranox** [comment]
Yeah, after looking through the code a bit, I think I understand why it doesn't work, but it would be nice if it did.

I've had some success with workarounds(registering the result into a variable and then parsing it in a second task, looking for ones that changed), but they aren't very elegant, and don't work in every case (if I need to restart two services, for which the handlers work really well).

**Comment by jimi-c** [comment]
I believe @bcoca mentioned he was working on supporting parameterized handlers (see discussion here: https://groups.google.com/forum/#!topic/ansible-project/BFhudWcf5JI), so I'm going to close this for now.
