### ISSUE TITLE
reported unit test failures (2)

### ISSUE THREAD

**Issue by ferringb** [ansible/ansible#3989]
Two separate set of breakages:

1) The undefined vars tests are each broken- they were added via e3adfbf5 .  Those tests were reliant on behaviour that doesn't actually work- changing constants after the fact, in addition to a bug w/ the defaults not force integer conversion where required.

2) test_playbook_hash_replace was broken by 25e3eed519b ; I've no fix for that one, it's a new breakage since I last had free time for ansible.  The test output isn't particularly useful, but is thus:

```
======================================================================
FAIL: test_playbook_hash_replace (TestPlayBook.TestPlaybook)
----------------------------------------------------------------------
 Traceback (most recent call last):
   File "/home/bharring/source/ansible/test/TestPlayBook.py", line 383, in test_playbook_hash_replace
    self._compare_file_output(filename, expected_lines)
  File "/home/bharring/source/ansible/test/TestPlayBook.py", line 520, in _compare_file_output
    assert actual_lines == expected_lines
AssertionError:
>>  assert ['goodbye: Goodbye World!'] == ['inside_a_role: Indeed!']

-------------------- >> begin captured stdout << ---------------------
**ACTUAL**
['goodbye: Goodbye World!']
**EXPECTED**
['goodbye: Goodbye World!']
**ACTUAL**
['goodbye: Goodbye World!']
**EXPECTED**
['inside_a_role: Indeed!']

--------------------- >> end captured stdout << ----------------------
```

The invoking environment is ubuntu 12.0 , python2.7.3-0ubuntu3.2 w/ jinja 2.7-3 (rebuilt from upstream, confirmed to not be the cause via reverting for testing).

**Comment by mpdehaan** [comment]
Note, The associated commits mentioned here are not going to be applied, the last commit misunderstands how constructor defaults work for integers and strings.

**Comment by ferringb** [comment]
Michael- I'm sorry, but you're wrong about python behaviour here.  The following code directly contradicts your view of constructor behaviour; respectfully, this misunderstanding is the source of peoples issues w/ mutable args as an optional argument: http://stackoverflow.com/questions/1132941/least-astonishment-in-python-the-mutable-default-argument .  Either way, demo code:

```
s = "binding one"
def func(my_opt=s):
  print "my_opt is %r" % (my_opt,)
func()
s = "this modifies the locals()['s'] = this value, but the func already got the previous var reference in it's definition"
print "this should be something other than binding one, it isn't however since default opt binding occurs at func definition time"
func()
print "these are the function bound defaults- pulled from the function object itself"
print func.func_defaults
```

Sorry; in hindsight this isn't obvious unless you've worked on the interpreter guts a bit (which I have).  The parser shoots through building an AST- that AST has the defaults bound in at the time of _definition_, not at run time.

Please look at https://github.com/ansible/ansible/blob/devel/test/TestPlayBook.py#L272 ; note, it's trying to replace (not modify, replace) a variable in the modules scope.  The test changes the defaults/constants, but Runner.**init** has already (by the time of that invocation) been bound to the defaults it _first_ saw.

The patch I posted fixes a valid issue- it's luck that the existing tests are working, or moreso, a sign that the tests aren't actually testing what they claim (they should be breaking).

Regardless, I have actual tests I've been trying to add for the missing filter changes that directly exposes this bug- I cut this intermediate patch because it was required to make the test code work as intended, rather than me randomly chasing idiocy.

If there's any questions, please feel free to ask, but I reiterate, you're misunderstanding how cpython/pypy/jython do their binding here- it's not obvious, but it's easy to isolate the behaviour as I did above to prove it.

Please reopen and apply; if you don't like the fix and prefer a different route, please let me know; that said there is an issue here that needs to be fixed if my missing filters fixes are to land.

Cheers-

**Comment by mpdehaan** [comment]
we're not appending to arguments or mutating them here, so I don't understand what the actual problem you are having is.

I prefer defects to be phrased around actual problems encountered from using ansible not theoretical code issues.

**Comment by ferringb** [comment]
Just relaying the conversation from IRC:

The tests at https://github.com/ansible/ansible/blob/devel/test/TestPlayBook.py#L272 /are/ trying to mutate the global defaults and have the runner automatically pick that up (which fails since those defaults are already bound to Runner.**init**).

I'd assumed that was intentional; Michael stated otherwise, as such the args will just be passed in.  Another PR inbound shortly.

**Comment by mpdehaan** [comment]
unit tests can just set this back at the end of the function, no other changes needed
