### ISSUE TITLE
ansible-playbook 1.3 devel hang during on gathering facts (needs info)

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#3994]
During running a playbook I had a network interrupt. 

After that, I was not able to run the playbook again. 

I had a few days old ansible upstream build, updated to the latest, didn't solve the issue. I could successfully run `ansible -m setup`, but not `ansible-playbook`. 

I checkout out 1.2.3 release and run the playbook successfully there, switching back to latest devel 266d2008d8a97494d159d8e3a907e6c01e12c8a6 and I was able to run the playbook also on devel. 

It seems it could not ssh in to the host. and waited for ever... however, I could not really debug. 

Sorry for not having more infos.

**Comment by jimi-c** [comment]
If you can replicate this, next time disable host_key_checking in ansible.cfg and see if that corrects the issue, as it sounds like a stale lock file.

**Comment by resmo** [comment]
my ansible.cfg looks like:

```
[defaults]
connection = ssh
host_key_checking = false
```

**Comment by mpdehaan** [comment]
Closing this until we can get some steps to reproduce as there is not enough info to go on here.

It sounds like you have an ansible-playbook process still running holding onto a lock that you will need to kill.
