### ISSUE TITLE
[WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

### ISSUE THREAD

**Issue by francklafon** [ansible/ansible#40000]
Hello Everyone ! :) I'm beginner in Ansible. I install on my MacBook Pro Ansible with homebrew. 

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/franck/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 22 2018, 14:43:05) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

##### 
franck$ ansible-playbook playbook.yaml --private-key key_ansible -b -K
SUDO password:
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

 [WARNING]: Could not match supplied host pattern, ignoring: 192.168.50.159

**Comment by mkrizek** [comment]
This isn't a bug. It's just a warning that you didn't provide any valid inventory file (`/etc/ansible/hosts` is default).

**Comment by mkrizek** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
