### ISSUE TITLE
Issues related to undefined dict keys

### ISSUE THREAD

**Issue by wknapik** [ansible/ansible#40006]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/foo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Apr 16 2018, 20:08:15) [GCC 7.3.1 20180406]
```

##### CONFIGURATION
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Behavior is different for dicts with undefined keys between assignment via `vars` and `set_fact`. In the former case, there's no error.   

##### STEPS TO REPRODUCE
```yaml
vars:
  foo: "{{ { bar: 1 } }}"
tasks:
  - debug: var=foo
```
produces
```
ok: [localhost] => {
    "foo": "VARIABLE IS NOT DEFINED!"
}
```
while
```yaml
tasks:
  - set_fact:
      foo: "{{ { bar: 1 } }}"
  - debug: var=foo
```
produces
```
TASK [set_fact] *******************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {}

MSG:

The task includes an option with an undefined variable. The error was: 'bar' is undefined
```

##### EXPECTED RESULTS
I expected the two examples above to produce the same error.

##### ACTUAL RESULTS
Different behavior.

Could be related to #15722, but seemed different enough to deserve a separate issue.

**Comment by webknjaz** [comment]
-label needs_triage

**Comment by pilou-** [comment]
With `debug` module, use `msg: {{ foo }}` (instead of `var` debug module parameter) in order to trigger an error when expression isn't defined. That behavior:
* isn't mentioned in `debug` module documentation
* is [tested in an integration test](https://github.com/ansible/ansible/blob/7ec82cdfc91d1bc4dff2546e1f5b088ce1a6a1c0/test/integration/targets/var_blending/roles/test_var_blending/tasks/main.yml#L41-L47)

=> this seems a documentation issue rather a bug.

!component =docs

**Comment by jctanner** [comment]
Duplicate of https://github.com/ansible/ansible/issues/15722

**Comment by pilou-** [comment]
@jctanner did the debug module documentation mention that an error doesn't occur when an undefined variable is used with `var` parameter ?
