### ISSUE TITLE
wait_for does not work with host aliases

### ISSUE THREAD

**Issue by mspaulding06** [ansible/ansible#4000]
Given a host file containing aliases like this:

```
myhost ansible_ssh_host=192.168.10.3

[hosts]
myhost
```

And a playbook like this:

```

---
- name: Test
  hosts: hosts
  tasks:
    - name: Check for SSH Up
      wait_for: host={{ inventory_hostname }}
                timeout=600
                port=22
```

The _wait_for_ will time out if the ports are open or not. If I remove the alias and use the ip address directly it works fine.

**Comment by srgvg** [comment]
This is how it's supposed to work. You are saying to check the port on "inventory_hostname", not the alias. There is no reason ansible goes looking to ansible_ssh_host here.

**Comment by mspaulding06** [comment]
So I tried replacing inventory_hostname with ansible_ssh_host and this does not work either.

**Comment by mpdehaan** [comment]
Can you please use the debug module to tell us the value of the ansible_ssh_host that doesn't work for you and also share your test playbook?

I agree that the hostname alias isn't always going to be a hostname so the original bug as reported isn't a problem, the other thing I'm pretty sure works but I'm suspecting we can help with a misunderstanding somewhere.   But I could be wrong!

**Comment by mpdehaan** [comment]
No reply in 24 days so I am going to close this one.
