### ISSUE TITLE
nova_compute module doesn't work the same as other modules with regards to register and with_items

### ISSUE THREAD

**Issue by ggillies** [ansible/ansible#4001]
Hi,

I'm trying to have a use case where I have an inventory file with something like

```
[openstack-instances]
instance1
instance2

[database-hosts]
instance1

[web-hosts]
instance2
```

Then use a playbook/role similar to

http://pastebin.com/weM00pTb

To create the instances in nova, then use some add_host trickery to be able to use those hosts in other roles later on to configure those systems. This follows off the ec2 example at

http://www.ansibleworks.com/docs/modules.html#ec2

However, this doesn't seem to work how I expected. Instances get created ok, but the other tasks only execute once. Looking at the code for the nova_compute module and the ec2 module, it seems that the ec2 module returns an array of running instances that it was asked to create (or that are just running in that account?, while the nova_compute module returns the details about the host created only. I think this difference in expected behaviour between the two modules can cause confusion, and not allow you to perform the ec2 provision-then-configure pattern with the nova_compute modules.

Regards,

Graeme

**Comment by bennojoy** [comment]
Hi Graeme,

If i am not mistaken ec2 module uses "id" field to uniquely identify a set
of hosts and make sure the operations are idempotent, As far as i could
figure out there was no field in openstack module to uniquely identify a
deployment set, hence the name field was chosen to make the operations
idempotent. That is the reason the module returns the details of the new
instance created, or if an instance exists with that name returns that
instance's data.
I am open to any new ideas on how this can be improved but keeping
idempotency in mind. Please do let us know if you have any options in mind.

Regards,
Benno

**Comment by ggillies** [comment]
Hi Benno,

Thanks for taking the time to respond. I'm pretty sure there is a unique id for all instances in openstack/nova because it's visible from the nova command line tool (and the nova_compute ansible models utilises the python-novaclient library

```
# nova list
+--------------------------------------+----------------+--------+-----------------------------------+
| ID                                   | Name           | Status | Networks                          |
+--------------------------------------+----------------+--------+-----------------------------------+
| 497774df-eda5-44bd-bb49-a67a3f9d0031 | ansible-master | ACTIVE | default=192.168.0.5, 10.10.154.11 |

# nova show 497774df-eda5-44bd-bb49-a67a3f9d0031
+-------------------------------------+----------------------------------------------------------+
| Property                            | Value                                                    |
+-------------------------------------+----------------------------------------------------------+
| status                              | ACTIVE                                                   |
| updated                             | 2013-08-29T01:45:04Z                                     |
| OS-EXT-STS:task_state               | None                                                     |
| OS-EXT-SRV-ATTR:host                | REMOVED                                                  |
| key_name                            | REMOVED                                                  |
| image                               | rhel-6.4-x86_64 (afd60717-e1b5-4d22-9f2b-3307e79e8b08)   |
| hostId                              | a6acdaab6b750e9fd2657fbc21ba35cb5bba2b5c46eba2aa5ec5bc8c |
| OS-EXT-STS:vm_state                 | active                                                   |
| OS-EXT-SRV-ATTR:instance_name       | instance-000004ba                                        |
| OS-EXT-SRV-ATTR:hypervisor_hostname | REMOVED                                                  |
| flavor                              | m1.tiny (1)                                              |
| id                                  | 497774df-eda5-44bd-bb49-a67a3f9d0031                     |
| security_groups                     | [{u'name': u'default'}]                                  |
| user_id                             | a4ea569bc4ac41c29a152a849a96b003                         |
| name                                | ansible-master                                           |
| created                             | 2013-08-07T01:15:21Z                                     |
| tenant_id                           | b0785756ead14a6d8b9855769a58ee9e                         |
| OS-DCF:diskConfig                   | MANUAL                                                   |
| metadata                            | {}                                                       |
| accessIPv4                          |                                                          |
| accessIPv6                          |                                                          |
| progress                            | 0                                                        |
| OS-EXT-STS:power_state              | 1                                                        |
| OS-EXT-AZ:availability_zone         | nova                                                     |
| default network                     | 192.168.0.5, 10.10.154.11                                |
| config_drive                        |                                                          |
+-------------------------------------+----------------------------------------------------------+
```

I'm sure that ID should be available through the api calls somehow.

**Comment by bennojoy** [comment]
Hi Greame,

If i am not mistaken that is the unique identifier for that particular
instance, but say we are creating 5 instance, giving count as 5 then is
there a way to check if that the 5 instances are created and running.
For a single instance usecase the id field works but we chose name field
other wise you would have to generate and provide this id.

You could accomplish the same as ec2 does by using with_items. here's a
psuedo playbook
- name: Instance create
  nova_compute:>
    name: "{{ item }}"
  with_items:
  - vm1
  - vm2
  - vm3
    register: nova
- name: add the hosts
  add_hosts: host="{{ item.private_ip }}" group="openstack_instances"
  with_items: nova.results

I dont have an openstack cluster to test the above playbook, but i am
pretty sure it should work.

Regards,
Benno

**Comment by ggillies** [comment]
Hi Benno,

Had a look over the source code of both the ec2 and nova_compute module and what you are saying hit me like a lightning bolt. You are correct, the only unique identifier we have in ansible land is the instance name, so between distinct runs that's the only discernible identifier we can use to determine if the instance exists in openstack or not. As you said, names are not unique, so this poses a problem.

Working more with my tasks I think I've figured out that my problem actually isn't to do with the nova_compute module at all, but rather with the add_hosts task, which I can only seem to get to fire once instead of once per host in the inventory.

I'll close this ticket as I see this actually isn't a bug.

Regards,

Graeme
