### ISSUE TITLE
Syntax problem: name: unseal vault

### ISSUE THREAD

**Issue by lvthillo** [ansible/ansible#40032]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.5.2
```

##### OS / ENVIRONMENT

`Ansible on Mac OS Sierra (nodes are Centos7)`

##### SUMMARY

```
Error when running playbook:
$ ansible-playbook -i inventory/mycluster/hosts.ini cluster.yml


ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/Users/xx/xx/kubernetes-project/kubespray/roles/vault/handlers/main.yml': line 44, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: unseal vault
```

##### STEPS TO REPRODUCE

```yaml
 [kube-master]
 node1.domain.com
 node2.domain.com

 [etcd]
 node1.domain.com
 node2.domain.com
 node3.domain.com

 [kube-node]
 node2.domain.com
 node3.domain.com

 [kube-ingress]
 node2.domain.com
 node3.domain.com

 [k8s-cluster:children]
 kube-master
 kube-node
 kube-ingress

```

##### EXPECTED RESULTS

To start the playbook

```

**Comment by sergiylegmelnik** [comment]
@lvthillo How did you sole this issue?

**Comment by lvthillo** [comment]
@sergiylegmelnik It was kubespray related: https://github.com/kubernetes-incubator/kubespray/issues/2764
Fixed it by performing: 

`sudo pip install -r requirements.txt`

 (or pip3 in some cases)

**Comment by nadimm90** [comment]
Running `sudo pip install -r requirements.txt`
is retunring the below:

Installing collected packages: requests, hvac, ansible-modules-hashivault
  Found existing installation: requests 2.6.0
Cannot uninstall 'requests'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
