### ISSUE TITLE
unable to avoid Could not match supplied host pattern warning with non existing groups

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#40030]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
2.4.0.0 to devel
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
It seems that Ansible tries to outsmart us by throwing warnings if it fails to match host patterns, even if this is perfectly normal use case.

What is worse that that this feature/bug gives us no real choice to avoid it or to disable it completely.

Hosts and groups can be retried from various sources (file format or dynamic) and there is effectively no way to surpres these warnings and tell ansible to go.

These warnings go to stderr (expected) but the do create confusions for those users that do redirect ansible output.

I would like to request removal of this feature which caused at least a dozen of open tickets since it was introduced in ansible 2.4, everyone asking about the same thing: how to get rid of it.

**It it perfectly normal for an inventory group to be empty or even to not be defined.**

Yesterday a change was merged into devel (2.6) to disable the warning on empty groups, still this is not enough because it would not cover for the case where the group is missing.

I spend a good number of hours trying to find a way to avoid a warning, but its seems [impossible to avoid it in a reliable way.](https://github.com/ansible/ansible/issues/35255#issuecomment-387846173)

Unless this feature can be implemented in a way that allows user to enable/disable it, we would be all better off without it as it creates a big amount our fake runtime warnings. Better to migrate it to ansible-linter where people can disable that check ;)

**Comment by ph0en** [comment]
> It it perfectly normal for an inventory group to be empty or even to not be defined.

In my case I have this warning when i want to "--limit" with host inside group and try to set tag
And now I have to tun playbooks with all tasks in it.

**Comment by gservat** [comment]
In my case, I wish Ansible wouldn't exit with error code `1` when the group is missing or empty. Why? Because I run a job from a CI system and exit of `1` is bad, and in my case the fact that Ansible couldn't find the group (or if it's empty) is not a bad thing. It just means no hosts matched, which in my particular case it's an OK thing to happen. I understand this may not be desirable for all Ansible users, but it would be great if we could tweak this behaviour via `ansible.cfg` (e.g. `no_hosts_ok = true`) or similar.

**Comment by ssbarnea** [comment]
Any chance to make this happen? I would say that in lots of cases is perfectly normal to have empty groups. 

Maybe the best place to implement the allow_empty would be at the lines that can trigger it. If the settings would be global or at group definition, there is the risk of missing to spot places where empty group is not expected.

Maybe a jinja2 filer like `hosts: emptygroup|allow_empty_group`?

**Comment by MichaelBaydoun** [comment]
+1

**Comment by bcoca** [comment]
does the toggle in PR above give you all the options you wanted?

**Comment by MichaelBaydoun** [comment]
The PR looks great for my needs.

**Comment by ssbarnea** [comment]
I am afraid that is not the way I was hoping to see it fixed because there are places where having no match is perfectly ok (expected) and places where no host match is clearly a reason to be warned about or even stop execution completely.

Still, the decision about the behaviour is about each usage and a global settings is of less use for that.

If hosts is used in hundreads of places across multiple repositories, disabling the warning would likely be too dangereus.
