### ISSUE TITLE
S3 module does not return time-limited URL in 'put' mode if file not changed

### ISSUE THREAD

**Issue by tidzo** [ansible/ansible#4006]
The docs for the S3 module say that 'If or once the key (file) exists in the bucket, it returns a time-expired download URL'.  However, if a 'put' operation discovers that the key already exists and has not changed, it does not return the URL.

The 'overwrite' parameter is available to force uploading in this case, and of course the module can be called again after the 'put' operation in 'geturl' mode, but to support the stated behaviour of returning a URL "if or once the key exists", it should, I suggest, return the URL regardless of whether the file was actually changed. 

Here is the output of a debug action showing the variable registered by the call to the module, where the key already existed and was unchanged:

{u'msg': u'Local and remote object are identical, ignoring. Use overwrite parameter to force.', 'invocation': {'module_name': 's3', 'module_args': u'mode=put bucket=[redacted] object=[redacted] src=[redacted]}, u'changed': False}

A 'url' element was expected based on the 'if or once' statement in the documentation.

**Comment by jctanner** [comment]
Matt, 

Thanks for the suggestion! Committed in https://github.com/ansible/ansible/commit/9c3fb9c2b7ffde1e831bab53810001d90448018e
