### ISSUE TITLE
Vault variables show up in logs unmasked when using Expect module

### ISSUE THREAD

**Issue by kavink** [ansible/ansible#40107]
When using `expect` module, the unencrypted vault passwords show up in logs ? As of now  im using the following in module

```
responses:
            (?i)password: "{{ my_pass }}"
```

is there some special way to mask it?

Expected behavior: vault passwords should show up encrypted in log `****`

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
