### ISSUE TITLE
multiline only_if not working

### ISSUE THREAD

**Issue by mkaluza** [ansible/ansible#4016]
Changelog says that in 0.8 it was fixed, but I couldn't find the commit, so either it wasn't fixed or it's a regression.

```
  - debug: msg=test
    only_if: >
      1<2 and 2<3
```

```
TASK: [debug msg=test] ********************************************************
fatal: [localhost] => Conditional expression must evaluate to True or False: 1<2 and 2<3\n
```

For those 'use when instead of only_if' - I've tried, but couldn't pull this one:

```
- name: >
    Check for required variables.
  fail: msg="Variable '$item' not set"
  only_if: is_set("${REQUIRED_VARS}") and ( (not is_set("${$item}") and not is_set("${item.name}")) or (is_set("${item.actions}") and is_set("$action") and "$action" in "${item.actions}" and not is_set("${${item.name}}")) )
  with_items: $REQUIRED_VARS
```

which checks for specific vars and handles structure like this:

```
REQUIRED_VARS:
- var1
- name: var2
  actions: install
```

**Comment by mpdehaan** [comment]
only_if is very very old.

You can do this:

```
when: 1<2 and 2<3
```

Let me know if that doesn't work in multi-line mode.

**Comment by mkaluza** [comment]
"when" does work and I would gladly use it, but I don't know how to rewrite the condition presented above (with is_set) and specifically - how to access a variable, whose name is in another variable - like ${$item}

**Comment by mkaluza** [comment]
Looking at the error message, only_if objects to a newline char at the end - wouldn't a simple .strip() somewhere fix it?
