### ISSUE TITLE
Inconsistent allow_duplicates behaviour on role dependencies.

### ISSUE THREAD

**Issue by benosman** [ansible/ansible#4017]
I was running into issues with a dependency being included multiple times when i thought the default was to only include once.

I had been trying allow_duplicates: false in the top level role but that had no effect. After stepping through the code in a debugger i noticed that it was looking in the dependency role itself for a meta.yml file which was not present. So now for my situation I can get it working.

However, I wanted to post this issue to see if this is how it is intended.

It seems to work like the following:

Top role depends on Base role.

Base role contains no meta/main.yml  => Role can be included many times
Base role contains empty meta/main.yml => Role only included once.
Base role contains meta/main.yml with allow_duplicates set => works as expected

The code in playbook/play.py is as follows on ~ line 188.

```
if os.path.isfile(meta):
    meta_data = utils.parse_yaml_from_file(meta)
        if meta_data:
            allow_dupes = utils.boolean(meta_data.get('allow_duplicates',''))
            if not allow_dupes:
                if dep in self.included_roles:
                    continue
                else:
                    self.included_roles.append(dep)
```

The allow_dupes is only set if the meta file exists, so the simplest thing to do here is add an else statement to the outer if statement.

```
if os.path.isfile(meta):
    meta_data = utils.parse_yaml_from_file(meta)
        if meta_data:
            allow_dupes = utils.boolean(meta_data.get('allow_duplicates',''))
            if not allow_dupes:
                if dep in self.included_roles:
                    continue
                else:
                    self.included_roles.append(dep)
else:
    continue
```

**Comment by jimi-c** [comment]
I believe you're correct, and I didn't account for this situation. Go ahead and send this to me in a PR and I'll merge it in.

**Comment by jimi-c** [comment]
Merged that patch, thanks!
