### ISSUE TITLE
Support using paramiko to set up accelerate connection

### ISSUE THREAD

**Issue by sfromm** [ansible/ansible#4022]
Right now, if you use paramiko as the connection type, you get a warning that ANSIBLE_SSH_ARGS/ansible_ssh_args must be set when you use accelerate on a play:

```
fatal: [node.example.net] => using -c ssh on certain older ssh versions may 
not support ControlPersist, set ANSIBLE_SSH_ARGS="" (or ansible_ssh_args 
in the config file) before running again
```

It would be nice if ansible supported using paramiko to set up accelerate.

**Comment by sfromm** [comment]
Not a fancy patch, but it gets the job done.  :-)

**Comment by mpdehaan** [comment]
Closing per above, thanks!
