### ISSUE TITLE
In the modules documentation it says there is a region setting on ec2_elb

### ISSUE THREAD

**Issue by likwid** [ansible/ansible#4024]
However, when I run an action with the module, I get the following error:

TASK: [Add to ELB] ************************************************************
failed: [ec2-XX-XX-X-XXX.compute-1.amazonaws.com] => {"failed": true}
msg: unsupported parameter for module: region

FATAL: all hosts have already failed -- aborting

Here is my task:

tasks:
- ec2_facts:
- name: Add to ELB
  action:
    module: ec2_elb
    instance_id: "{{ ansible_ec2_instance_id }}"
    ec2_elbs: XXXBlue
    state: 'present'
    aws_region: us-east-1

Any ideas what I am doing wrong?

**Comment by mpdehaan** [comment]
What version of Ansible are you using?

**Comment by likwid** [comment]
Sorry, I totally meant to put that in there. I'm using the dev branch. Running ansible --version returns 1.3

**Comment by jimi-c** [comment]
In your playbook, you have aws_region. That is configured to be an alias of the region variable, but could you change it to be just "region:" to make sure?

**Comment by likwid** [comment]
Just in case, I uninstalled and reinstalled from the latest develop branch and it seems to be working now. It works with region and aws_region both.

Closing.
