### ISSUE TITLE
test_playbook_hash_replace failing

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#4026]
Since commit 25e3eed519b7 (I ran it through git bisect) test_playbook_hash_replace has been failing (at least within my environment). 

Looks like the test should succeed based on my understanding of desired behaviour but as the same fix seems to have removed the need for me to prefix role variables I'm not sure why the test is failing.

**Comment by mlieberman85** [comment]
I'm having the same issue.

**Comment by bcoca** [comment]
confirming, I see it too
