### ISSUE TITLE
in playbooks, have --verbose display output from executions

### ISSUE THREAD

**Issue by afsilva** [ansible/ansible#403]
A lot of times a person may need to review the output of a command, for example, a tail or diff output to make sure something got installed or started correctly. A --verbose option would be really nice for this project.

**Comment by mpdehaan** [comment]
we should also remove "-D" at the same time, if any vestiges remain, as that doesn't do anything now

**Comment by mpdehaan** [comment]
this is now implemented in the latest git, use -v/--verbose with /usr/bin/ansible/playbook

(There is also now a -v on /usr/bin/ansible, but this is currently not wired to do anything meaningful)
