### ISSUE TITLE
Trying to connect with another user if previews user unable to connect in playbook

### ISSUE THREAD

**Issue by abhaysrivastava83** [ansible/ansible#40308]
##### ISSUE TYPE
 - Bug Report

##### STEPS TO REPRODUCE

---
- name: PLAY 1
  hosts: all
  gather_facts: false
  remote_user: centos
  tasks:
    - import_tasks: centos_change_user.yml
      ignore_errors: yes

- name: PLAY 2
  hosts: all
  gather_facts: false
  remote_user: cloud
  any_errors_fatal: true

  tasks:
    - import_tasks: cloud_change_user.yml
      ignore_errors: yes

##### ACTUAL RESULTS

```

```

**Comment by mkrizek** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
