### ISSUE TITLE
Accelerate connection and local_action

### ISSUE THREAD

**Issue by ScottSturdivant** [ansible/ansible#4035]
Given an existing working playbook, I thought I'd take advantage of the accelerate connection by simply adding `accelerate: True` to a play.  Unfortunately, some of the roles I have defined include `local_action` tasks.  For instance, this task:

```
- name: Make sure the destination directory exists
  local_action: file dest=credentials/passwords/{{ inventory_hostname }} state=directory
```

When executing the playbook, it then begins erroring out on that task:

```
TASK: [Make sure the destination directory exists] **************************** 
fatal: [hostname.local] => Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-1378392391.25-102475063025397 && echo $HOME/.ansible/tmp/ansible-1378392391.25-102475063025397, exited with result 255
```

As this playbook works with a `ssh` connection, I would have expected it also work with `accelerate`.

**Comment by jimi-c** [comment]
Merged above request, so closing this.
