### ISSUE TITLE
Role dependency hierarchies executing differently than before

### ISSUE THREAD

**Issue by cayblood** [ansible/ansible#4038]
I have two roles (let's call them rr and jr) that are both dependent on another shared role (let's call it uwsgi). uwsgi has context-specific tasks in it that must be executed for each role that depends on it. However, after updating to the latest code in devel today, it seems that uwsgi only gets executed for rr, so when my provisioning process gets to jr, the context-specific tasks in uwsgi haven't been run for it yet, and it fails.

What should be the correct behavior for this kind of thing? It seems like role dependencies are not very useful if a shared role can't be executed more than once in a context-sensitive manner.

**Comment by jimi-c** [comment]
Add the `meta/main.yml` file to the uwsgi role directory with the following content:

<pre>
---
allow_duplicates: true
</pre>

This was part of the update I sent earlier this week, in regards to switching the default behavior to NOT allow roles to execute more than once (ie. in a diamond pattern of dependencies).

**Comment by cayblood** [comment]
Worked. Thanks.
