### ISSUE TITLE
Unable to supply SHA as version for git module when target host has git version 1.8.1.2

### ISSUE THREAD

**Issue by alisaifee** [ansible/ansible#4047]
Supplying a SHA1 to `git clone --branch` raises a 'Remote branch ${SHA1} not found in upstream' error. A git bisect shows https://github.com/git/git/commit/9049816140e75d3f7b15264e97e042f5ab0bf392 to be the first commit that introduced the change in behavior.

**Comment by mpdehaan** [comment]
That's a git bisect of the _git_ source.

Are you sure you meant to file this on Ansible?

**Comment by alisaifee** [comment]
The rationale behind providing the bisect of the git source was to highlight the potentially affected hosts. 

```
git tag --contains 9049816 | head -n 1
v1.7.10
```

It does make sense that --branch should only accept branch names or tags. The git module already switches to the specified version after cloning or pulling so providing the version as an argument to the clone function could be skipped. The one draw back of skipping that argument that I could see is that if the depth argument is provided the tree will be clone with the latest commit in each branch/tag, instead of just the specified on in the version argument.

**Comment by jimi-c** [comment]
This seems to be an upstream issue, and nothing we can really fix, so I'm going to close this. If it becomes an issue, we can revisit it, however I'm confident the vast majority of users use tags and actual branch names so this should not be a major problem.
