### ISSUE TITLE
No 'changed' attribute on script module

### ISSUE THREAD

**Issue by ScottSturdivant** [ansible/ansible#4052]
When executing the script module, I've been led to believe that if the script itself outputs `changed=True` to stdout, the task will register as changed.  This is not the case as of the following ansible version:

```
$ ansible --version
ansible 1.3 (devel 4e9dee6093) last updated 2013/09/06 08:23:33 (GMT -600)
```

Take for example this script (foo.sh):

```
#!/bin/sh
echo "changed=True"
```

Execute this, and here is the result:

```
TASK: [try a script] ************************************************* 
ok: [hostname] => {"rc": 0, "stderr": "", "stdout": "changed=True\r\n"}
```

**Comment by mpdehaan** [comment]
So a script should not echo changed=True to return changed.  This would be wrong.  (text output is not significant, this is not a module!)

However, the return code for the script module should always add a "changed: True" in there in the script.py code.

I am opening a ticket about this instead.

**Comment by mpdehaan** [comment]
See #4053
