### ISSUE TITLE
script module (script.py) should add a changed: True attrribute in JSON

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#4053]
The script module should return a changed; True attribute, seems to be currently missing.

(Probably also the raw command).

**Comment by ScottSturdivant** [comment]
Just a comment that I wouldn't expect this to be a hard code True.  Would like to have the ability for the script to somehow notify ansible if something has indeed changed.

**Comment by jimi-c** [comment]
@SirScott I would think that would be a different feature request, along the lines of what the command/script modules do with the creates/removes arguments.
