### ISSUE TITLE
an action to set persistent facts

### ISSUE THREAD

**Issue by gdamjan** [ansible/ansible#4061]
When installing apps with a more complex setup - like a rails app that setups a mysql database - the playbook is not idempotent, since it doesn't know to see that the database is already configured.

One recommendation I was given was to touch a file on the filesystem and check it with creates=... But that's a bit ad-hoc.

For a more systematic approach I'd suggest an action that sets local facts on the target, so that you can check for them on the next run.

**Comment by srgvg** [comment]
Could be a module set_local_fact sets e.g. /etc/ansible/facts.d/mysql.fact

**Comment by mpdehaan** [comment]
Yeah this is already there.

**Comment by gdamjan** [comment]
what is where? … reference?

**Comment by srgvg** [comment]
http://www.ansibleworks.com/docs/playbooks2.html#local-facts-facts-d

**Comment by resmo** [comment]
To be correct: not yet released. will be there in 1.3.

**Comment by gdamjan** [comment]
ok. but that page talks about reading the facts, not setting them.

I could have a task to leave a file in /etc/ though

**Comment by lied** [comment]
gdamjan, I also need this. Until something like this works I'm using ini_file module to set facts
