### ISSUE TITLE
Django `collectstatic` is mentioned in the documentation but only implemented in the development branch.

### ISSUE THREAD

**Issue by kurtismullins** [ansible/ansible#4067]
In the primary documentation, the [Django module](http://www.ansibleworks.com/docs/modules.html#id286) supposedly has the capability to call `collectstatic`.

Inspecting the source code, this functionality is not implemented in the current release (1.2.3). However, it is available in the development branch.

Can this either be pushed to a release or the documentation modified appropriately? Thanks!

**Comment by mpdehaan** [comment]
It's in 1.3, so this is just a docs issue.

Since 1.3 is out Friday I'm just going to close this.

**Comment by kurtismullins** [comment]
Thanks!
