### ISSUE TITLE
ecc2b6e7 kills module rhn_register in CentOS 6.4

### ISSUE THREAD

**Issue by mpontes** [ansible/ansible#4069]
Commit ecc2b6e7 kills module rhn_register in my system (CentOS 6.4). Just initialising the module throws Python into a 100% CPU loop. It seems that the issue here is that the class in question is inheriting from another one called Config that is present in `/usr/share/rhn/up2date_client/config.py` in my system, which contains both `has_key`and `__getitem__` implementations. Using the `in` syntax makes it use the `__getitem__` implementation, which throws it into a loop.

```
  File "rhn_register", line 175, in get_option_default
    if 'key' in self:
  File "/usr/share/rhn/up2date_client/config.py", line 258, in __getitem__
    if self.stored.has_key(name):
  File "/usr/share/rhn/up2date_client/config.py", line 178, in has_key
    return self.dict.has_key(name)
```

The RHN client that installs this file is [this RPM](http://spacewalk.redhat.com/yum/latest/RHEL/6/x86_64/rhn-client-tools-2.0.1-1.el6.noarch.rpm), in case you need the source to check what's going on.

**Comment by jimi-c** [comment]
Went ahead and reverted this as it was a minor change, thanks for reporting it!
