### ISSUE TITLE
show which role is processed in ansible-playbook

### ISSUE THREAD

**Issue by tyll** [ansible/ansible#4076]
ansible-playbook only shows which task are processes without any indication which role is used, therefore if two roles use the same task name e.g. "install dependencies", there is no context about which task is really used. Therefore pleas mention the role as well.

**Comment by mpdehaan** [comment]
Yes, the "task name" is already there.   I'm fine with adding the role name in brackets before the task name like

[apache] blarg

vs

blarg

something you might like to work on?
