### ISSUE TITLE
Both stdout and stdout_lines should not be in playbook output

### ISSUE THREAD

**Issue by marcusphi** [ansible/ansible#4077]
I noticed that when a task fails on a host that uses register, both stdout and stdout_lines were in the output. This makes the logs verbose and harder to read, and it seems like an unnecessary duplication. I had the impression that the stdout_lines were only there to be able to loop using with_items, and it has no place in an output intended for humans.

I am using Ansible 1.3.

**Comment by mpdehaan** [comment]
I would generally agree, we should modify the callback to copy the datastructure and pop stdout_lines

If this is something you would like to work on, please submit a pull request, and it would be greatly appreciated.

**Comment by mpdehaan** [comment]
I'm currently not seeing this behavior on the latest development branch:

```
 - hosts: foo

   tasks:
    - shell: cat /etc/motd
      register: foo
```

ansible-playbook /tmp/test.yml -v
