### ISSUE TITLE
unexpected change in dynamic inventory behaviour

### ISSUE THREAD

**Issue by n0vember** [ansible/ansible#40776]
##### SUMMARY

An undocumented change occured in 2.5 version of ansible that can make old dynamic inventories unusable.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ansible
ansible-playbook

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /home/n0vember/.ansible.cfg
  configured module search path = ['/home/n0vember/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.5 (default, May 11 2018, 04:00:52) [GCC 8.1.0]
```

##### CONFIGURATION

ANSIBLE_PIPELINING(/home/n0vember/.ansible.cfg) = True
DEFAULT_SCP_IF_SSH(/home/n0vember/.ansible.cfg) = true
DEFAULT_TRANSPORT(/home/n0vember/.ansible.cfg) = ssh
RETRY_FILES_ENABLED(/home/n0vember/.ansible.cfg) = False

##### OS / ENVIRONMENT

Host is Archlinux, guest can be whatever OS

##### STEPS TO REPRODUCE

This script is a minimal exemple of a working dynamic inventory in 2.4 :

```
#!/usr/bin/env bash

[ "$1" != "--list" ] && exit

cat <<EOF
{
  "inv_tmp" : {
    "hosts" : [  "192.168.1.135", ],
  },
  "inv" : {
    "children" : [ "inv_tmp", ],
    "vars": {
      "ansible_ssh_common_args": "-o StrictHostKeyChecking=no -o CheckHostIp=False -o UserKnownHostsFile=/dev/null",
      "ansible_user": "root",
    },
  },
}
EOF
```

It can be used running the following command : 
```
ansible -i old_inv all -m setup
```

##### EXPECTED RESULTS

Expected result is a list of fact for the mentionned host

##### ACTUAL RESULTS

Actual output is : 

```
 [WARNING]:  * Failed to parse /home/n0vember/tmp/inv/old_inv with script plugin: Invalid data from file, expected dictionary and got:  None

 [WARNING]:  * Failed to parse /home/n0vember/tmp/inv/old_inv with yaml plugin: Syntax Error while loading YAML.   did not find expected alphabetic or numeric character  The error appears to have been in '/home/n0vember/tmp/inv/old_inv': line 3, column 23, but may be
elsewhere in the file depending on the exact syntax problem.  The offending line appears to be:   [ "$1" != "--list" ] && exit                       ^ here

 [WARNING]:  * Failed to parse /home/n0vember/tmp/inv/old_inv with ini plugin: not enough values to unpack (expected 3, got 2)

 [WARNING]: Unable to parse /home/n0vember/tmp/inv/old_inv as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
```

**Comment by n0vember** [comment]
Doing some tests and reading documentation, I found that problem can be solved two ways.

Either by removing the test on the --list argument. Script is then : 
```
#!/usr/bin/env bash

cat <<EOF
{
  "inv_tmp" : {
    "hosts" : [  "192.168.1.135", ],
  },
  "inv" : {
    "children" : [ "inv_tmp", ],
    "vars": {
      "ansible_ssh_common_args": "-o StrictHostKeyChecking=no -o CheckHostIp=False -o UserKnownHostsFile=/dev/null",
      "ansible_user": "root",
    },
  },
}
EOF
```
It is not satisfying because my real script soed other things when called without --list.

Either by adding a '_meta' entry within the output. New script : 
```
#!/usr/bin/env bash

cat <<EOF
{
  "_meta": {
    "hostvars": {}
  },
  "inv_tmp" : {
    "hosts" : [  "192.168.1.135", ],
  },
  "inv" : {
    "children" : [ "inv_tmp", ],
    "vars": {
      "ansible_ssh_common_args": "-o StrictHostKeyChecking=no -o CheckHostIp=False -o UserKnownHostsFile=/dev/null",
      "ansible_user": "root",
    },
  },
}
EOF
```
It is OK for me, but it is unclear in the doc that this is to be added.

Link to the documentation : 
https://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html#tuning-the-external-inventory-script

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

As documented here http://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html#script-conventions, dynamic inventory scripts must also allow for a `--hosts <hostname>` invocation. Ansible will use this option UNLESS they supply a `_meta` key, which is an optimization meant to invoke the script a single time vs 1 initial + 1 per host.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
