### ISSUE TITLE
option to auto-install python-apt module

### ISSUE THREAD

**Issue by iivvoo** [ansible/ansible#4079]
If the 'apt' module is used but python-apt is not installed on the target host, ansible bails out with:

```
TASK: [Install sudo] ********************************************************** 
failed: [hoppi] => {"failed": true}
msg: Could not import python modules: apt, apt_pkg. Please install python-apt package.

FATAL: all hosts have already failed -- aborting
```

which means you're always forced to do some workaround to make sure python-apt is installed.

An option to somehow auto-install python-apt if necessary would be nice.

**Comment by mpdehaan** [comment]
This would actually be a pretty good idea, and I don't think it needs to be an option.

The module is a packaging module and has a non-stock-OS dependency, which is a problem for people with stock images and makes the initial user experience on Debian/Ubuntu rougher than on Red Hat.

We should test if it's not there and then feed in the command line to auto-install it.

**Comment by resmo** [comment]
We should considering to add this to the documentation. 

If you are doing a minimal installation, you may not have python as well. So bootstrapping ansible dependencies is not only an problem using the apt module.

So better doing less magic, print an good error message so users just can do:

```
ansible -m raw -a "apt-get install python-apt -y"
```

**Comment by mpdehaan** [comment]
No, it should not be documentation, we should auto install the module.

If someone left out Python they ignored most of the install instructions for using Ansible, so I'm less concerned with that.

**Comment by jctanner** [comment]
@resmo can you make a pull request for https://github.com/resmo/ansible/commit/ba561dbefd4d8e89d4d75eee8d641703185cc64d ?

**Comment by marcusramberg** [comment]
I still see this issue with Ansible 1.5.5. Which release did this change go into?

**Comment by jimi-c** [comment]
@marcusramberg this is definitely in 1.6.0.

**Comment by Wilfred** [comment]
Similarly, apt_repository depends on python-curl. Should this be autoinstalled too?

**Comment by jimi-c** [comment]
@Wilfred the installation is done via apt, so deps should be installed along with that package.

**Comment by d-mo** [comment]
I'm getting this error with Ansible version 1.8.2. Downgrading to 1.7.2 fixes it.

**Comment by hwmrocker** [comment]
I get this error with ansible 1.9.1, and 1.7.2 will not install in a virtual env because it cannot delete stuff in /usr/share WTF

**Comment by anton-rudeshko** [comment]
On Ubuntu Hardy 8.04 I always get: 

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
  python-apt: Depends: libapt-pkg-libc6.7-6-4.6
E: Broken packages
```

Is there a way to fix this?
