### ISSUE TITLE
Ansible installed in a virtualenv uses /usr/bin/python (ansible_python_interpreter does not help)

### ISSUE THREAD

**Issue by jcassee** [ansible/ansible#4083]
When I install Ansible in a virtualenv using `pip`, modules keep using `/usr/bin/python` and setting `ansible_python_interpreter` does not help.

To reproduce extract [this archive](https://dl.dropboxusercontent.com/u/3020657/ansible-bug2.tar.gz) and run the following commands:

```
virtualenv .
. bin/activate
pip install -r requirements.txt
ansible -i hosts playbook.xml
```

The error message is "boto required for this module". Running with `strace -f` confirms that boto is not looked for in the virtualenv and the Python interpreter used is `/usr/bin/python`.

**Comment by mpdehaan** [comment]
You didn't really share where you set ansible_python_interpreter (or share the playbook to know what hosts you were talking to).

it's an inventory variable you need to set on localhost.

Best to just not use virtualenv if you want to keep it simple on yourself, this is what VMs are for, etc, but it works fine.

Stop by the mailing list if you would like some help.

**Comment by jcassee** [comment]
I think I did by isolating the problem in a downloadable testcase. Anyway, I'll post to the list.

**Comment by cristobalrosa** [comment]
Hi Joost
I'm using Ansible inside a virtualenv and it works properly. Have you used
"--no-site-packages" when you built your virtualenv?

**Comment by jcassee** [comment]
Absolutely, I need some package versions that are not available (or even conflict) with the system packages.

**Comment by cristobalrosa** [comment]
You can try to run the below command inside the virtualenv to see which
paths is using python

 ansible 127.0.0.1 -m shell -a "python -c 'import sys; print sys.path'"
--connection=local

and check if boto in the pythonpath.

Or you can create a file .pth inside the python site-packages file to
specify the boto module path. (http://docs.python.org/2/library/site.html)

**Comment by jcassee** [comment]
If I run that command the pythonpath does contain the boto package.

**Comment by cristobalrosa** [comment]
Ok, then you coud add a path file to your  python site-packages folder.
This way your python will find the boto module.

If you have created your virtualenv using the --no-site-packages option,
you should have a folder under  your virtualenv path  where python has been
installed.

This folder is usually VIRTUALENV_PATH/lib/python2.x/
Under this folder you should have a folder named site-packages, then you
can create a path file under this folder with your boto module installation
path:

echo "boto_path" >> VIRTUALENV_PATH/lib/python2.x/site-packages/boto.pth

For example

cd /home/myuser/myvirtualenvs/test/
echo "boto_path" >> ./lib/python2.7/site-packages/boto.pth

Hope this helps!

**Comment by jcassee** [comment]
Sure, but that would mean that the system packages are on the pythonpath again when I am developing my Python code, and they conflict with the virtualenv packages. That was the whole reason for isolating the environment in the first place...

**Comment by cristobalrosa** [comment]
Is there any reason not to use a boto module installed inside the virtualenv?
I've installed boto inside the virtualenv using pip:
pip install boto

Then I could use it inside the virtual env:

(test)my_user@my_machine:~/projects/vir/test$ python
Python 2.7.3 (default, Apr 10 2013, 05:13:16)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import boto
> > > print boto.**file**
> > > /home/my_user/projects/vir/test/local/lib/python2.7/site-packages/boto
> > > /**init**.pyc

if you have already installed another version of boto in your system path,
you could force to use the version you wish by using the pkg_resources
package

import pkg_resources
pkg_resources.require("boto==2.12.0")

import boto
print boto.**file**

**Comment by jcassee** [comment]
No, there is every reason to use that module! In fact I added both ansible and boto to requirements.txt. The problem is that Ansible modules all start with `#!/usr/bin/python` so they do not pick up the virtualenv Python packages. I have not been able to get ansible_python_interpreter either.

(See also [my message to the list](https://groups.google.com/d/msg/ansible-project/BT-tY3TKYlA/WZDlkqDGtwwJ).)

**Comment by frnsys** [comment]
For future reference: I just finished wrestling with this `boto` issue myself (on OSX 10.9). I was using a virtualenv and couldn't get that to work, even when setting `ansible_python_interpreter` (by the looks of it, the setting was respected for the first task, then it fell back to `/usr/bin/python` for the rest). I tried installing `boto` outside the virtualenv but that didn't work either (I'm using Python installed with homebrew, i.e. at `/usr/local/bin/python`). 

What ended up working was explicitly installing `boto` to system python:

```
$ sudo /usr/bin/easy_install boto
```

And then there were no more complaints!

Edit:
FYI I was setting `ansible_python_interpreter` both via the command line and as a var in my playbook.

**Comment by diasjorge** [comment]
I was experiencing this error executing this:
`ansible-playbook eureka.yml -c local -i "localhost,"`
I changed it to
`ansible-playbook eureka.yml -c local -i "127.0.0.1,"` and it works. No idea why.

**Comment by TerryHowe** [comment]
I saw a similar thing that @diasjorge saw, where 127.0.0.1 worked and in my case it was because of a bad /etc/ansible/hosts file.

**Comment by amireldor** [comment]
I ran something like this from my venv:

    ansible-playbook -i inventory.txt -c local \
                     --extra-vars="ansible_python_interpreter=$(which python)" \
                     upload_static.yml
