### ISSUE TITLE
Support user-switching without sudo

### ISSUE THREAD

**Issue by psy-q** [ansible/ansible#4084]
Debian systems generally don't install sudo, and none of our production servers have it installed. Instead, when we need to execute commands as another user, we use `su username -c`.

Could Ansible be modified to support different user-switching techniques than sudo? `su -c` can't be made to accept the same options as sudo, as far as I know. At least trying to set sudo_exe to various invocations of `su -c` weren't successful for me.

The problem showed up when trying to use the postgresql_user module as user 'postgresql' on a Debian machine. If I use `sudo_user: postgresql` on a machine without sudo, things fail, of course, since the root user (which we normally connect as) isn't allowed to admin the PostgreSQL database.

This can be solved in two ways, either by making root a trusted superuser on PostgreSQL by rewriting pg_hba.conf via Ansible or by having a different mechanism to become the user postgres.

We would prefer not to install sudo anywhere, since we don't have a need for it and it just adds one more layer and attack vector to the system's security and is yet another component we'd have to manage.

**Comment by jimi-c** [comment]
A pull request (#4063) has been submitted to address this, so I'm closing this as a duplicate. Thanks!

**Comment by bcoca** [comment]
#4063 was done to enable and normalize #3932 which allows you to change login user (remote_user) per task, this would preclude using sudo as you are already the target user, but not really let you use alternate methods of becoming another user (su).
