### ISSUE TITLE
be able to set no_log: True on a task

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#4088]
It appears the syslog facility setting isn't passed down to module common.

That's ok, if so, we should remove the setting from the config file and just use the LOG_USER bits.

Though it would be nice if there was a way to turn this off that is user accessible.

It would also be nice if there was a way to turn this off on a per module basis by having a task attribute

no_log: True

There is some support for this on the command module but it's not really surfaced.

**Comment by jimi-c** [comment]
The facility is being passed down, so I'm changing this to a feature request for the no_log: True part.

**Comment by mpdehaan** [comment]
Updated description.

If not true, it should maybe also be able to take a list of field names not to log?  Maybe I'm overthinking it.
