### ISSUE TITLE
--ask-sudo-password impacting more than it should?

### ISSUE THREAD

**Issue by WramblinWreck** [ansible/ansible#4090]
I'm noticing some unexpected behavior in a playbook I've written.  Here's what I'm seeing:

I have a playbook containing two plays
- name: play one
  hosts: localhost
  connection: local
  sudo: true
  gather_facts: false
  tasks:
  ...some tasks
- name: play two
  hosts: web
  user: root
  sudo: false
  gather_facts: false
  tasks:
  ...some tasks

The first play requires sudo and is performing some local actions.  The
second play is doing remote actions and does not require sudo.  The
problem is, the second play requires the private ssh key in my home
directory to work ~/.ssh/...

When I run the playbook I specify '-K' so that sudo is prompted.  Ansible
then runs the first play just fine, but when it gets to the second play it
can't find my ssh key and so ssh login fails prompting for a password.  If
I then run the playbook again and limit it just to the second play and do
NOT pass '-K' to prompt for sudo, the second play runs just fine.  I
suspect that ansible is running the second play as root locally because of
the sudo password and as such is trying to ssh to web as root instead of
as me.  So,

root$ ssh root@web     instead of     my_user$ ssh root@web

Is this the expected behavior?  Is there a way to get these two plays to work together in the same playbook?  I'm running ansible 1.2.2 on my Mac.

**Comment by mpdehaan** [comment]
The second play doesn't specify connection: local and should be a remote play, so I don't think it's running locally.

But yes, specifying --ask-sudo-password should not imply sudo is active for a play.

Can you retest this on 1.3 (devel) to see if you still have the same problem there?

**Comment by WramblinWreck** [comment]
Ok, I can't seem to get the playbook I was running yesterday to fail in the same way in either 1.2.2 or in 1.3, but when running it from 1.3 (devel), it fails for something completely different.

Here's the playbook:
- hosts: localhost
  connection: local
  sudo: true
  gather_facts: false
  tasks:
  - name: install pyrax
    pip: name=pyrax
  - name: Create web server
    sudo: false
    rax:
      creds_file: /Users/john.madrid/.raxpub
      region: ORD 
      name: web1
      flavor: 2
      image: f613b402-ebbf-49fe-a780-101a75c03704
      files:
        /root/.ssh/authorized_keys: /Users/john.madrid/.ssh/id_rsa.pub
      wait: true
      state: present
      wait_timeout: 900
    register: rax
  - name: Add web instance to host group
    add_host: name=${item.accessIPv4} groups=web
    with_items: ${rax.instances}
  - name: Create db server
    sudo: false
    rax:
      creds_file: /Users/john.madrid/.raxpub
      region: ORD 
      name: db
      flavor: 2
      image: f613b402-ebbf-49fe-a780-101a75c03704
      files:
        /root/.ssh/authorized_keys: /Users/john.madrid/.ssh/id_rsa.pub
      wait: true
      state: present
      wait_timeout: 900
    register: rax
  - name: Add web instance to host group
    add_host: name=${item.accessIPv4} groups=db
    with_items: ${rax.instances}
- name: Install base packages
  sudo: false
  hosts: web
  user: root
  tasks:
  - name: get python dependency
    raw: yum -y install python-simplejson
    tags:
    - setup
  - name: install epel
    command: /bin/rpm -Uvh --force http://mirrors.kernel.org/fedora-epel/5/i386/epel-release-5-4.noarch.rpm creates=/etc/yum.repos.d/epel.repo
    tags:
    - setup
  - name: install yum packages
    yum: state=installed pkg={{item}}
    with_items:
    - git
    - httpd
      tags:
    - setup

In 1.3 it installs pyrax fine, and then on the next task it errors with this:

TASK: [Create web server] ****************************************************\* 
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1379000922.63-154377807579993 && chmod a+rx $HOME/.ansible/tmp/ansible-1379000922.63-154377807579993 && echo $HOME/.ansible/tmp/ansible-1379000922.63-154377807579993']
<127.0.0.1> REMOTE_MODULE rax image=f613b402-ebbf-49fe-a780-101a75c03704 state=present creds_file=/Users/john.madrid/.raxpub region=ORD name=web1 
<127.0.0.1> PUT /var/folders/zY/zYOY1q4eF+GNwpk6Hikbebt4d+w/-Tmp-/tmpMJ8O0O TO /Users/john.madrid/.ansible/tmp/ansible-1379000922.63-154377807579993/rax
<127.0.0.1> EXEC ['/bin/sh', '-c', '/usr/bin/python -tt /Users/john.madrid/.ansible/tmp/ansible-1379000922.63-154377807579993/rax; rm -rf /Users/john.madrid/.ansible/tmp/ansible-1379000922.63-154377807579993/ >/dev/null 2>&1']
failed: [127.0.0.1] => {"failed": true}
msg: pyrax required for this module

FATAL: all hosts have already failed -- aborting

The exact same playbook runs fine from 1.2.2.

If I leave off the 'sudo: false' on the second play, it fails in 1.2.2 with the behavior I was seeing yesterday.

**Comment by WramblinWreck** [comment]
Here's a clearer copy of the playbook:  https://gist.github.com/RackerJohnMadrid/6539866

**Comment by jimi-c** [comment]
Is there some kind of python version mismatch, where pip isn't installing it in the correct location for the default version you're using maybe? If you open a python shell, can you type "import pyrax" successfully?

**Comment by WramblinWreck** [comment]
Seems like I can import it.  I'm not a python dev, so I don't know if this test is valid.  This was from the same shell where I'm running ansible 1.3 with it's environment modifications.

$ sudo pip freeze | grep pyrax
pyrax==1.5.0

$ python --version
Python 2.7.5

$ python
Python 2.7.5 (default, Sep  7 2013, 23:24:49) 
[GCC 4.2.1 (Apple Inc. build 5664)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > import pyrax

**Comment by mpdehaan** [comment]
--ask-sudo-pass no longer forcibly implies --sudo in 1.3.X

As the pyrax error is unrelated to the topic I am going to close this ticket, though I suspect you just need to set ansible_python_interpreter.
