### ISSUE TITLE
ansible (with default config) leaves $HOME/~None/ directories on target hosts (ESTABLISH SSH CONNECTION FOR USER: None)

### ISSUE THREAD

**Issue by adiemu5** [ansible/ansible#40929]
##### SUMMARY

Ansible 2.5.3 using all the defaults in a passwordless-ssh environment (hostbased-auth) creates $HOME/~None/ directories on target hosts.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ansible

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = None
  configured module search path = [u'/home/ctracy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/python-2.7/linux/lib/python2.7/site-packages/ansible
  executable location = /opt/python-2.7/linux/bin/ansible
  python version = 2.7.8 (default, Aug 25 2014, 14:57:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
```

##### CONFIGURATION

Completely default config.  ('ansible-config dump --only-changed' returns no output)

##### OS / ENVIRONMENT

CentOS 7.4
CentOS 6.9

##### STEPS TO REPRODUCE

Default install of ansible.  Very basic inventory:
```
[dell]
linux60801
```
Then run something like as any user (root or non-root):
```
ansible -i inventory dell -m command -a id
```

##### EXPECTED RESULTS

No creation of $HOME/~None/ directory.  (And ansible properly uses the username of whoever invoked it)

##### ACTUAL RESULTS

The directory $HOME/~None/ is created on the target system.

Looks like ansible thinks it's running as the user "None" and thus tries to write to "~None/.ansible/tmp" which, since "None" isn't a valid user on the target system, end up being interpreted as the relative path"./~None/.ansible/tmp" which in this case works out to the absolute path "/home/ctracy/~None/.ansible/tmp".  (If run as root, that ends up being "/root/~None/.ansible/tmp")

```
$ whoami
ctracy
$ ansible -vvvv -i inventory dell -m command -a id
ansible 2.5.3
  config file = None
  configured module search path = [u'/home/ctracy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/python-2.7/linux/lib/python2.7/site-packages/ansible
  executable location = /opt/python-2.7/linux/bin/ansible
  python version = 2.7.8 (default, Aug 25 2014, 14:57:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
No config file found; using defaults
setting up inventory plugins
Parsed /DCNFS/users/student/ctracy/ansible/inventory inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /opt/python-2.7/linux/lib/python2.7/site-packages/ansible/plugins/callback/minimal.pyc
META: ran handlers
Using module file /opt/python-2.7/linux/lib/python2.7/site-packages/ansible/modules/commands/command.py
<linux60801> ESTABLISH SSH CONNECTION FOR USER: None
<linux60801> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/DCNFS/users/student/ctracy/.ansible/cp/a843a5c5d4 linux60801 '/bin/sh -c '"'"'echo ~None && sleep 0'"'"''
<snip>
<linux60801> PUT /home/ctracy/.ansible/tmp/ansible-local-18833kufxPg/tmpGLAT7j TO ~None/.ansible/tmp/ansible-tmp-1527736983.09-101580444648740/command.py
<snip>
```
Afterwards, on the target system:
```
$ ls -l /home/ctracy/
<snip>
drwx------. 3 ctracy gdm 21 May 30 15:05 /home/ctracy/~None
<snip>
$ find /home/ctracy/\~None/
/home/ctracy/~None/
/home/ctracy/~None/.ansible
/home/ctracy/~None/.ansible/tmp
```

**Comment by mkrizek** [comment]
Thanks for the bug report! This has been resolved and the fix will be included in version `2.5.4`.

**Comment by akcrisp** [comment]
when is 2.5.4 being released - this is now causing us major pain. Can a 2.5.3-2 be released with this fix if 2.5.4 is some way off

**Comment by rlb2015** [comment]
I'm noticing in Linux version 2.6.1, it sometimes leaves ~none, sometimes ~username, usually in the home folder, but I've seen in some other folders periodically.  For the latter, I have not ascertained the circumstance that causes it (file copy maybe? bad command line?)   

I've been wondering if it's because our usernames contain the AD format (i.e. DOMAIN\\username) causing ~DOMAINusername folders, or if there is some configuration/setting/playbook option I should be using but am not.

In any event, for what it's worth, I figured I'd report it here.

**Comment by kanitaly** [comment]
I am having the same problem, sorry being novice 

+++++++

root@***************:~# python3 -m venv venv
root@***************:~# source venv/bin/activate
(venv) root@***************:~# pip install ansible
Collecting ansible
  Downloading https://files.pythonhosted.org/packages/56/fb/b661ae256c5e4a5c4285                                                                                                                                                             9860f59f9a1a0b82fbc481306b30e3c5159d519d/ansible-2.7.5.tar.gz (11.8MB)
    100% |████████████████████████████████| 11.8MB 94kB/s
Collecting PyYAML (from ansible)
  Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f                                                                                                                                                             136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
    100% |████████████████████████████████| 276kB 3.6MB/s
Collecting cryptography (from ansible)
  Downloading https://files.pythonhosted.org/packages/60/c7/99b33c53cf3f20a97a4c                                                                                                                                                             4bfd3ab66dcc93d99da0a97cc9597aa36ae6bb62/cryptography-2.4.2-cp34-abi3-manylinux1                                                                                                                                                             _x86_64.whl (2.1MB)
    100% |████████████████████████████████| 2.1MB 522kB/s
Collecting jinja2 (from ansible)
  Downloading https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a                                                                                                                                                             7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl (126kB                                                                                                                                                             )
    100% |████████████████████████████████| 133kB 7.3MB/s
Collecting paramiko (from ansible)
  Downloading https://files.pythonhosted.org/packages/cf/ae/94e70d49044ccc234bfd                                                                                                                                                             ba20114fa947d7ba6eb68a2e452d89b920e62227/paramiko-2.4.2-py2.py3-none-any.whl (19                                                                                                                                                             3kB)
    100% |████████████████████████████████| 194kB 4.9MB/s
Requirement already satisfied: setuptools in ./venv/lib/python3.6/site-packages                                                                                                                                                              (from ansible)
Collecting idna>=2.1 (from cryptography->ansible)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1c                                                                                                                                                             f41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 7.6MB/s
Collecting cffi!=1.11.3,>=1.7 (from cryptography->ansible)
  Downloading https://files.pythonhosted.org/packages/6d/c0/47db8f624f3e4e2f3f27                                                                                                                                                             be03a93379d1ba16a1450a7b1aacfa0366e2c0dd/cffi-1.11.5-cp36-cp36m-manylinux1_x86_6                                                                                                                                                             4.whl (421kB)
    100% |████████████████████████████████| 430kB 2.4MB/s
Collecting six>=1.4.1 (from cryptography->ansible)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe8                                                                                                                                                             98238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography->ansible)
  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a51057                                                                                                                                                             6f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl                                                                                                                                                              (101kB)
    100% |████████████████████████████████| 102kB 7.5MB/s
Collecting MarkupSafe>=0.23 (from jinja2->ansible)
  Downloading https://files.pythonhosted.org/packages/08/04/f2191b50fb7f0712f03f                                                                                                                                                             064b71d8b4605190f2178ba02e975a87f7b89a0d/MarkupSafe-1.1.0-cp36-cp36m-manylinux1_                                                                                                                                                             x86_64.whl
Collecting bcrypt>=3.1.3 (from paramiko->ansible)
  Downloading https://files.pythonhosted.org/packages/31/4b/4057d0716e7170c29ff1                                                                                                                                                             2e19791eb6037422620835e4a58a01d4790e56d1/bcrypt-3.1.5-cp34-abi3-manylinux1_x86_6                                                                                                                                                             4.whl (55kB)
    100% |████████████████████████████████| 61kB 7.6MB/s
Collecting pyasn1>=0.1.7 (from paramiko->ansible)
  Downloading https://files.pythonhosted.org/packages/d1/a1/7790cc85db38daa874f6                                                                                                                                                             a2e6308131b9953feb1367f2ae2d1123bb93a9f5/pyasn1-0.4.4-py2.py3-none-any.whl (72kB                                                                                                                                                             )
    100% |████████████████████████████████| 81kB 8.2MB/s
Collecting pynacl>=1.0.1 (from paramiko->ansible)
  Downloading https://files.pythonhosted.org/packages/27/15/2cd0a203f318c2240b42                                                                                                                                                             cd9dd13c931ddd61067809fee3479f44f086103e/PyNaCl-1.3.0-cp34-abi3-manylinux1_x86_6                                                                                                                                                             4.whl (759kB)
    100% |████████████████████████████████| 768kB 1.4MB/s
Collecting pycparser (from cffi!=1.11.3,>=1.7->cryptography->ansible)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead12                                                                                                                                                             90e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
    100% |████████████████████████████████| 163kB 5.4MB/s
Building wheels for collected packages: ansible, PyYAML, pycparser
  Running setup.py bdist_wheel for ansible ... error
  Complete output from command /root/venv/bin/python3 -u -c "import setuptools,                                                                                                                                                              tokenize;__file__='/tmp/pip-build-icxf2699/ansible/setup.py';f=getattr(tokenize,                                                                                                                                                              'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(comp                                                                                                                                                             ile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpktfhqhl8pip-wheel- --python                                                                                                                                                             -tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for ansible
  Running setup.py clean for ansible
  Running setup.py bdist_wheel for PyYAML ... error
  Complete output from command /root/venv/bin/python3 -u -c "import setuptools,                                                                                                                                                              tokenize;__file__='/tmp/pip-build-icxf2699/PyYAML/setup.py';f=getattr(tokenize,                                                                                                                                                              'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compi                                                                                                                                                             le(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpk94okxpwpip-wheel- --python-                                                                                                                                                             tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for PyYAML
  Running setup.py clean for PyYAML
  Running setup.py bdist_wheel for pycparser ... error
  Complete output from command /root/venv/bin/python3 -u -c "import setuptools,                                                                                                                                                              tokenize;__file__='/tmp/pip-build-icxf2699/pycparser/setup.py';f=getattr(tokeniz                                                                                                                                                             e, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(co                                                                                                                                                             mpile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpy0rgb5gepip-wheel- --pyth                                                                                                                                                             on-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for pycparser
  Running setup.py clean for pycparser
Failed to build ansible PyYAML pycparser
Installing collected packages: PyYAML, idna, pycparser, cffi, six, asn1crypto, c                                                                                                                                                             ryptography, MarkupSafe, jinja2, bcrypt, pyasn1, pynacl, paramiko, ansible
  Running setup.py install for PyYAML ... done
  Running setup.py install for pycparser ... done
  Running setup.py install for ansible ... done
Successfully installed MarkupSafe-1.1.0 PyYAML-3.13 ansible-2.7.5 asn1crypto-0.2                                                                                                                                                             4.0 bcrypt-3.1.5 cffi-1.11.5 cryptography-2.4.2 idna-2.8 jinja2-2.10 paramiko-2.                                                                                                                                                             4.2 pyasn1-0.4.4 pycparser-2.19 pynacl-1.3.0 six-1.12.0
(venv) root@***************:~#
(venv) root@***************:~#
(venv) root@***************:~#
(venv) root@***************:~#
(venv) root@***************:~#
(venv) root@***************:~# ansible --version
ansible 2.7.5
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/venv/lib/python3.6/site-packages/ansible
  executable location = /root/venv/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
(venv) root@***************:~# cd /etc/
Display all 149 possibilities? (y or n)
(venv) root@***************:~# cd /etc/a
acpi/         alternatives/ apache2/      apm/          apparmor/     apparmor.d/   apport/       apt/          avahi/
(venv) root@***************:~#
++++++++

could not see any files on /etc/ansible
