### ISSUE TITLE
documentation: index of task properties

### ISSUE THREAD

**Issue by gdamjan** [ansible/ansible#4092]
it seems the only place to find about what properties a task can have is looking at the source code:
https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/task.py#L36

it would be nice to have them indexed in the documentation somewhere, linking to wherever they are documented.

**Comment by mpdehaan** [comment]
Yep, this should be true for plays as well.

**Comment by jctanner** [comment]
When the new docs are pushed, this will show up at http://www.ansibleworks.com/docs/playbooks_tasks.html
