### ISSUE TITLE
Idea: use python-mysqldb from the local host

### ISSUE THREAD

**Issue by gdamjan** [ansible/ansible#4093]
Currently the mysql_\* modules require python-mysqldb on the target (remote) host.

Why not use it locally on the controlling host with ssh providing the redirection of the connection.

This would  eliminate requirements from the target host.

**Comment by bcoca** [comment]
you can already do this:

local: mysql_

**Comment by mpdehaan** [comment]
Yep, what bcoca says is correct.

You can run it form the local host and pass in the server name

{{ inventory_hostname }} as a variable contains the address of the host in the loop you are currently looping over.

Hope this helps!

Thanks!
