### ISSUE TITLE
Ansible does not detect appropriately ansible.cfg file

### ISSUE THREAD

**Issue by siran** [ansible/ansible#40969]
##### SUMMARY
When executing from a directory where `ansible.cfg` does not exist not, `ansible` command fails to find it even using `--playbook-dir` flag

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.5.0
```

##### CONFIGURATION

<empty>

##### OS / ENVIRONMENT

MacOS Sierra

##### STEPS TO REPRODUCE

1- When you execute `$ ansible --playbook-dir ansible-playbooks -v -i ansible-playbooks/hosts-us/hosts --list-hosts all --limit=xx`

it says: 
No config file found; using defaults

although there is an ansible.cfg in ansible-playbooks/ relative path.

```yaml

```

##### EXPECTED RESULTS

Ansible should look for configuration file ALSO in playbook-dir path (in addition to current dir, home dir, etc)

##### ACTUAL RESULTS

`ansible.cfg` was not found

```
No config file found; using defaults
```

**Comment by sivel** [comment]
Ansible does not look in the playbook directory for an ansible.cfg file.

Per http://docs.ansible.com/ansible/latest/reference_appendices/config.html#the-configuration-file ansible.cfg may exist in one of the following:

* `ANSIBLE_CONFIG` (environment variable if set)
* `ansible.cfg` (in the current directory)
* `~/.ansible.cfg` (in the home directory)
* `/etc/ansible/ansible.cfg`

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
