### ISSUE TITLE
Log to /var/log/ansible.log (not /var/log/messages)

### ISSUE THREAD

**Issue by jlaska** [ansible/ansible#4101]
There are numerous issues filed related to logging.  Apologies if this issue is being tracked elsewhere.

`/var/log/messages` is chock full of ansible related playbook execution.  After running plays on a system over a period of days, the file has become too cluttered with ansible related information.  This doesn't feel like the right place for that level of detail.  

It should be configurable in `/etc/ansible/ansible.cfg`, but perhaps `/var/log/ansible.log` (with rotation) would be more appropriate for ansible playbook logging.

**Comment by mpdehaan** [comment]
I disagree here, it's using syslog.

This was originally added for Fedora infrastructure's usage and in this case it's about actions happening on the local system.  

You can filter it any way you like by configuring syslog, and can deploy those configurations with Ansible if you like.

**Comment by vincentvdk** [comment]
I kind of like the idea. Maybe as a config option with messages as default?

**Comment by przemolb** [comment]
Why not give people a choice and let it be configurable using ansible ?

**Comment by bcoca** [comment]
I use ansible to configure syslog to send ansible log messages to
/var/log/ansible.log

**Comment by przemolb** [comment]
But when you have hundreds or thousands of servers to change syslog config (even with ansible) you need to raise a Change Request which in big environments might take a lot of time to test, deploy, etc. It is much, much easier to change just ansible config. After all ansible is to make our, sysadmins/devops, life easier so why to complicate it ?

**Comment by bcoca** [comment]
I would argue that getting the remote logging to work correctly would
require more setup, from permissions, locking scheme (same or multiple
users running ansible against same machine), log rotation, etc is a lot
more complicated than just using syslog.

**Comment by przemolb** [comment]
I repeat it again: why not give people a choice ?

**Comment by bcoca** [comment]
Implementing that choice is non trivial, if you want to submit a PR that
works I doubt there will be much resistance, I just warn you it ends up
being a lot more complicated than a syslog config is.
