### ISSUE TITLE
service enable invokes a false state change event 

### ISSUE THREAD

**Issue by gottwald** [ansible/ansible#4102]
The service module has a bug when you set `enable=true`.

Regardless in what state your service is, if you set `enable=true` the service module starts your service.
When your service is already running, most init scripts are fine with that and present you a message that it's already running with a return code 0.
Some init scripts like varnish on ubuntu 12.04 LTS will return an error that it's already running with error code 1. That breaks your playbook..

I was digging into the code and saw that the Service Method `service.service_enable` sets `self.changed = True` at the end.

The bad thing is that the following method in the program flow is `service.check_service_changed()`.
And this method checks the value `self.changed` to determine if a service needs to be started or not.

Is the `self.changed = True` in `service.service_enable()` in any way needed or is it just cosmetics for the module json return values?

**Comment by jimi-c** [comment]
It is required for other logic I believe, so I don't want to change that. Overall, it sounds like we may just need to check the stdout/stderr for certain strings when the rc != 0 to prevent false negatives like this.

**Comment by gottwald** [comment]
I strongly disagree!
rc is way more specific than a random free form error message.
Some scripts may have no output at all and just set the rc.

I think we should go down to the core problem which is:
There doesn't always have to be a service state change when there's a change in the enable part.

**Comment by jimi-c** [comment]
My point was, if rc != 0 it may not necessarily mean the script failed, as with the varnish script above, so looking for certain strings in the output may help avoid errors like the one you're seeing.

As for the other question, I agree the code should only trigger a start if it detects the service is not running. Feel free to send a PR if you get this debugged, otherwise I'll look into it as soon as possible.

**Comment by gottwald** [comment]
Oh.. now that's awkward...
Didn't test against the latest development tree. Shame on me..
Just started to dig into this and realized that commit 3df2e15 already fixed this.
Sorry!

**Comment by jimi-c** [comment]
That's interesting, I wouldn't have expected that commit to fix the problem you describe, but yes there were a few other recent changes to the service module to try and eliminate some corner cases (a large number of which involved 12.04).

**Comment by gottwald** [comment]
Well it fixed my special case of varnish.
Because after installing varnish it's automatically enabled at boot.
So with the mentioned commit `self.changed` is `false` in my special case.
In other cases, when the service is not enabled at boot automatically it will still fail.

**Comment by gottwald** [comment]
Basically it's still one design flaw.

There are two individual "changes" in there: 
1) the state change of the service 
2.) the enabled at boot change
And both states get tracked with 1 variable.

The only legit solution I can think of is to split it into two "change"-variables

Any thoughts?

**Comment by bcoca** [comment]
Other modules use a single changed status, even when multiple attributes
are involved.

for example:
file: path=/etc/resolv.conf owner=root group=root mode=600 state=link
src=/tmp/hackme

if any of the attributes changes, changed will return true, it will only be
false if nothing has changed.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by gottwald** [comment]
@bcoca that's right.
I think I didn't state it correctly in my last comment.
Besides the tracking if a change did happen, the `service.change` variable is additionally used in the method `service.modify_service_state()`.
But this time it's not used as a tracking variable if a change did happen. 
It marks that a service state change should happen.
The mark ist set before in `service.check_service_changed()`

**Comment by jimi-c** [comment]
Closing, since the above was merged. Thanks!
