### ISSUE TITLE
UserWarning: Unknown distribution option: 'install_requires'

### ISSUE THREAD

**Issue by josephtate** [ansible/ansible#4105]
Since the setup.py uses distutils instead of setuptools, the install_requires is not being used. This means that setting up ansible isn't as simple as running python setup.py install, you have to manually install the requirements.

I've also noticed that python setup.py develop fails, so working on ansible is much harder than it should be.

**Comment by mpdehaan** [comment]
Thanks for sharing feedback.

Ansible is a program that is written in Python, but is exclusively not a pure python program -- as such, I'm ok with some of this.  It also relies on some other things, for instance, if using -c ssh with passwords you have to install sshpass, which is a native application, and -c ssh also uses the openssh binary.   I think we are ok in how requirements are installed, and with pip, python requirements are definitely sucked down, which handles the Python user who expects to get it from pip as opposed to yum, apt, or so on.

I've never used python setup.py develop to work on ansible.  You can run just "source ./hacking/env-setup" and you are running fully out of checkout, which is also needed to set some env variables.
