### ISSUE TITLE
git module should take more options to be able to specify keys and auth

### ISSUE THREAD

**Issue by chrisblossom** [ansible/ansible#4108]
I'm trying to clone a private git repo using the git module. The problem I am running into is my sshkey I am using is password-protected so the git just hangs and nothing happens. I've tried to find someone that has solved this problem but I can't seem to find an actual fix without using a passwordless sshkey. 

It would be great if we could specify a git-key with the gitmodule to solve this problem. Or somehow forward the sshauth session over to the client.

**Comment by mpdehaan** [comment]
Thanks for writing this up.

Getting git to work has frequently been a concern and I agree. 

My suggestion is that we consider adding a "private_key" "username" and "password" option to the git module and handle the expect-based stuff as well as adding the host to known hosts (optional) as needed.

**Comment by chrisblossom** [comment]
What I ended up doing was using git like this:
git: repo=https://username:password@github.com/username/gitrepo.git dest=/path/ version=branch

I suppose this isn't anyless secure than keeping a passwordless sshkey as a file inside Ansible, but I think I'd still prefer not to put a plaintext password inside a file if possible.

**Comment by mpdehaan** [comment]
Ansible can filter some field names based on what it knows that they are, but it's fields like "password" and "login_password" do get logged by syslog.   We might consider also changing the git module to pass the no_log=True flag when defining argument_spec for the repo field, this would keep that from being shared in the log.

**Comment by jctanner** [comment]
Hangs for unknown keys have been addressed by:

8665b0638a1d3a70f985126b0f007a26c81273cb
eeee1e1c5aa9dd4f84175966e0f9e467fd7fc600
3719f3f496bb4517eddf52d9f47b406fe14f63b8

**Comment by chrisblossom** [comment]
I am seeing a very long delay on private git repos using HTTPS. There is no delay using private git ssh repos, or public HTTPS repos.

Detailed setup: http://pastebin.com/ZAyBmMBa
Detailed Log: http://pastebin.com/Yjq67T39

```
Also noted running via command-line manually:
⚡ root@dev  ~  time /usr/bin/git ls-remote https://username:Password1234!@github.com/github-account/repo.git -h refs/heads/master
686948bb077e14fb818d078ceaddd6a680fcfced    refs/heads/master
/usr/bin/git ls-remote  -h refs/heads/master  0.16s user 0.01s system 17% cpu 0.979 total


⚡ root@dev  ~  time /usr/bin/git clone https://username:Password1234!@github.com/github-account/repo.git
Cloning into 'repo'...
remote: Reusing existing pack: 30, done.
remote: Total 30 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (30/30), done.
/usr/bin/git clone   0.26s user 0.03s system 17% cpu 1.663 total
```

**Comment by jctanner** [comment]
In case pastebin expires:

```
1.91 genericpath.py(21):     return True
1.91 os.py(157):     mkdir(name, mode)
1.91 git-https-private(140):     except:
1.91 git-https-private(141):         pass
1.91 git-https-private(142):     os.chdir(dest_dirname)
1.91 git-https-private(143):     cmd = [ git_path, 'clone' ]
1.91 git-https-private(144):     if bare:
1.91 git-https-private(147):         cmd.extend([ '--origin', remote, '--recursive' ])
1.91 git-https-private(148):         if is_remote_branch(git_path, module, dest, repo, version) \
 --- modulename: git-https-private, funcname: is_remote_branch
1.91 git-https-private(233):     cmd = '%s ls-remote %s -h refs/heads/%s' % (git_path, remote, version)
1.91 git-https-private(234):     print "### DEBUG: %s" % cmd
### DEBUG: /usr/bin/git ls-remote https://_______:Password1234!@github.com/______/_____.git -h refs/heads/master
1.91 git-https-private(235):     (rc, out, err) = module.run_command(cmd, check_rc=True)
 --- modulename: git-https-private, funcname: run_command
1.91 git-https-private(1416):         if isinstance(args, list):
1.91 git-https-private(1418):         elif isinstance(args, basestring):
1.91 git-https-private(1419):             shell = True
1.91 git-https-private(1423):         rc = 0
1.91 git-https-private(1424):         msg = None
1.91 git-https-private(1425):         st_in = None
1.91 git-https-private(1428):         env=os.environ
1.91 git-https-private(1429):         if path_prefix:
1.91 git-https-private(1432):         if data:
1.91 git-https-private(1434):         try:
1.91 git-https-private(1435):             if path_prefix is not None:
1.91 git-https-private(1445):                 cmd = subprocess.Popen(args,
1.91 git-https-private(1446):                                        executable=executable,
1.91 git-https-private(1447):                                        shell=shell,
1.91 git-https-private(1448):                                        close_fds=close_fds,
1.91 git-https-private(1449):                                        stdin=st_in,
1.91 git-https-private(1450):                                        stdout=subprocess.PIPE,
1.91 git-https-private(1451):                                        stderr=subprocess.PIPE)
```

**Comment by chrisblossom** [comment]
Also I should note that after the initial ~45 minute hang the https private repo will respond quickly. To reproduce I delete the temp files and reboot the server.

**Comment by jctanner** [comment]
remote host is ubuntu 12.04 on digital ocean

**Comment by jctanner** [comment]
The http based hang appears to be a bad interaction with subprocess.Popen and git-credential-cache. If the cache is turned on, then the process poll takes however long the cache timeout was set to.

Example problematic gitconfig:

```
[credential]
  helper = cache
```

The workaround is to either remove the helper definition or set a smaller timeout than default:

```
[credential]
  helper = cache --timeout=2
```

**Comment by chrisblossom** [comment]
I have started to work around the ssh-key issue by doing the following:
1. Creating /usr/local/bin/ssh-git.sh mode=0755

```
#!/bin/sh
if [ -z "$GIT_KEY" ]; then
    # if GIT_KEY is not specified, run ssh using default keyfile
    ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o KbdInteractiveAuthentication=no -o ChallengeResponseAuthentication=no "$@"
else
    ssh -i "$GIT_KEY" -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o KbdInteractiveAuthentication=no -o ChallengeResponseAuthentication=no "$@"
fi
```
1. Placing the ssh-key in /etc/ssh/github.rsa mode=0644
2. Adding the following to any task:

```
environment:
  GIT_SSH: /usr/local/bin/ssh-git.sh
  GIT_KEY: /etc/ssh/github.rsa
```

As you can see I have set StrictHostKeyChecking=no, but when I run the command I receive the error:

```
msg: github.com has an unknown hostkey. Set accept_hostkey to True or manually add the hostkey prior to running the git module
```

The problem with this is when a user does not have a home directory, such as www-data, it is not possible for the known_hosts file to exist. If I add "accept_hostkey=yes" to the task, the following error occurs:

```
msg: failed to add github.com hostkey: /bin/sh: 1: cannot create /var/www/.ssh/known_hosts: Directory nonexistent
```

A workaround I have done is to:
1. Have ansible create the home and .ssh directory for the user.
2. Add accept_hostkey=yes to the task.

**Comment by offby1** [comment]
@chrisblossom Another idea is to invoke "git" as some user who _does_ have a home directory, and then run "chown" afterwards to fix it up.

**Comment by jctanner** [comment]
@chrisblossom thanks for doing all the research on this!
