### ISSUE TITLE
--list-hosts ignores tags

### ISSUE THREAD

**Issue by omgjlk** [ansible/ansible#4109]
When doing --list-hosts ansible-playbook will list all the hosts for all the plays, regardless of which tags were passed in.

It'd be nice from a sanity checking POV to filter by tags.

**Comment by mpdehaan** [comment]
Thanks for filing this.

As shared on IRC, this is because the --list-hosts stuff doesn't really use playbook code, but reads the files and such.

We really need to standardize this in the future to solve this problem.

**Comment by jctanner** [comment]
Re-categorizing to a feature_idea

@j2sol can you give an example of an inventory and a playbook where this would be useful?

**Comment by mpdehaan** [comment]
So @jctanner the usage of this is pretty straightforward -- namely that you want to see what hosts would be affected by a play.  I believe this should remain filed as a bug report and we should straighten this out.

**Comment by omgjlk** [comment]
I believe I worded this a bit wrong. It's not really a tag to host relationship, it's more that --list-hosts will list out hosts for every play, and now that I think more about it, tags apply to tasks too, so it's hard for --list-hosts to filter on tag.  --list-tasks is more appropriate to use, AND --list-tasks already filters on tag, so I would consider this a misfiled non-issue.

**Comment by jctanner** [comment]
It looks like we could possibly have the --list-hosts code narrow down the enumerated plays based on the input tags ...

```
jtanner@u1204:~/issues/4109-list-host-tags$ ansible-playbook -i inventory site.yml -t one

PLAY [a:b:c:d] ****************************************************************

TASK: [debug msg="{{inventory_hostname + 'one'}}"] ****************************
ok: [a] => {
    "msg": "aone"
}
ok: [b] => {
    "msg": "bone"
}
ok: [c] => {
    "msg": "cone"
}
ok: [d] => {
    "msg": "done"
}

PLAY RECAP ********************************************************************
a                          : ok=1    changed=0    unreachable=0    failed=0
b                          : ok=1    changed=0    unreachable=0    failed=0
c                          : ok=1    changed=0    unreachable=0    failed=0
d                          : ok=1    changed=0    unreachable=0    failed=0

jtanner@u1204:~/issues/4109-list-host-tags$ ansible-playbook -i inventory site.yml -t one --list-hosts

playbook: site.yml

  play #1 (a:b:c:d): host count=4
    a
    b
    c
    d

  play #2 (e:f:g:h): host count=4
    e
    f
    g
    h
```

**Comment by omgjlk** [comment]
We might use that, but because it doesn't have introspection into the in-play tasks it wouldn't be as useful data. Mostly we were looking for a way to validate that our tag option was being properly read, and at the time we only knew about --list-hosts. That was the hammer. With --list-tasks it's much clearer information and more in-line with what we were looking for.

**Comment by jctanner** [comment]
The above patch moves the tag filtering code out of just the --list-tags section so that it runs for list-hosts and list-tasks. The result is the following:

```
jtanner@u1204:~/issues/4109-list-host-tags$ ansible-playbook -i inventory site.yml --list-hosts

playbook: site.yml

  play #1 (a:b:c:d): host count=4
    a
    b
    c
    d

  play #2 (e:f:g:h): host count=4
    e
    f
    g
    h

  play #3 (i:j:k:l): host count=4
    i
    j
    k
    l

jtanner@u1204:~/issues/4109-list-host-tags$ ansible-playbook -i inventory site.yml -t one --list-hosts

playbook: site.yml

  play #1 (a:b:c:d): host count=4
    a
    b
    c
    d
```
