### ISSUE TITLE
Future of Ansible @ GitHub after Microsoft acquisition

### ISSUE THREAD

**Issue by sm4rk0** [ansible/ansible#41097]
##### SUMMARY
I don't want to continue using GitHub after it (and all of us, its users and projects) have been sold to Microsoft. Is there any plan on migrating elsewhere, or is this the end of my contributorship?
I understand this is still very fresh news, at least for me, so I don't expect this question answered ASAP.

https://blog.github.com/2018-06-04-github-microsoft/
https://news.microsoft.com/2018/06/04/microsoft-to-acquire-github-for-7-5-billion/

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
   * To propose major features or changes: https://github.com/ansible/proposals

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
