### ISSUE TITLE
play / task tags that are not strings or lists get dropped

### ISSUE THREAD

**Issue by omgjlk** [ansible/ansible#4110]
lib/ansible/playbook/task.py line 229 attempts to deal with tags that might be on a task. It has a path if the tag is str, unicode or a path if the tag is a list, but if neither of those are true, the tag is just dropped and never added to self.tags.

I discovered this when I had set my tags to just numbers without quotes, which made them into ints in the yamldata. I was looking for a place to cast the tags into strings (or at least attempt to) when I discovered that the tags are just getting dropped in this routine. I'm not sure the right way to go about fixing this, as play.py line 65 suffers from the same problem.

I'm filing this issue so that it doesn't get lost, as I don't think I'll be able to fix it right now.

**Comment by mpdehaan** [comment]
My suggestion is that we just auto-cast any things specified to tags that is not a string (like an integer) as a string.

This should solve the problem.
