### ISSUE TITLE
accelerate mode and gather_facts true always calls sudo

### ISSUE THREAD

**Issue by nirik** [ansible/ansible#4111]
This simple playbook: 
- name: foo
  hosts: test
  gather_facts: yes
  accelerate: true
  
  tasks:
  - name: foobar
    action: command yum clean expire-cache

run with -u root shows: 

GATHERING FACTS **************************************************************\* 
failed: [arawn] => {"failed": true, "parsed": false}
invalid output was: sudo: sorry, you must have a tty to run sudo

It shouldn't be calling sudo at all if you are running it as root. If you set gather_facts to no, everything works fine.

**Comment by jimi-c** [comment]
I believe this patch corrects the issue, if you'd like to give it a test to confirm:

<pre>
diff --git a/lib/ansible/runner/connection_plugins/accelerate.py b/lib/ansible/runner/connection_plugins/accelerate.py
index f835a7d..e39d0d7 100644
--- a/lib/ansible/runner/connection_plugins/accelerate.py
+++ b/lib/ansible/runner/connection_plugins/accelerate.py
@@ -141,7 +141,7 @@ class Connection(object):
         if executable == "":
             executable = constants.DEFAULT_EXECUTABLE
 
-        if self.runner.sudo or sudoable and sudo_user:
+        if self.runner.sudo and sudoable and sudo_user:
             cmd, prompt = utils.make_sudo_cmd(sudo_user, executable, cmd)
 
         vvv("EXEC COMMAND %s" % cmd)
</pre>

**Comment by nirik** [comment]
I can confirm that fixes it. ;) Thanks for the quick fix.

**Comment by mpdehaan** [comment]
One possible question here.

Under what situation would self.runner.sudo be true and sudoable be true
and "sudo_user" is set to a False value?
