### ISSUE TITLE
Don't abort if log_path is not writable for user that runs ansible but a writeable logfile exists

### ISSUE THREAD

**Issue by r-p-e** [ansible/ansible#4113]
If a /var/log/ansible.log file exists and is not writeable by the user, that runs ansible, it should not abort. I would like to suggest to change the behaviour to check for an existing and writeable logfile.

**Comment by mpdehaan** [comment]
Hmm, I understand that some people may want it both ways, but we believe if you have requested logging be enabled, and it's _NOT_ able to log, it should force fixing that issue as the user had selected the logging was important to them -- somebody wanted that log file.   (Logging is also off by default, and the path could include $HOME to make for user specific paths)

This is fixable on a per user basis by configuring either ~/.ansible.cfg or ansible.cfg in the current working directory, so I think those options should provide suitable workarounds.
