### ISSUE TITLE
broken doc in module pkgutil

### ISSUE THREAD

**Issue by dermute** [ansible/ansible#4122]
Ansible 1.3 included the new module pkgutil, but it's documentation format is broken: http://www.ansibleworks.com/docs/modules.html#pkgutil

**Comment by dermute** [comment]
I'm so sorry, I just have been kinda confused this morning an pushed my failed fixed with a failed rebase >.<
40e70dc and ef256aa are just the solution (missed deleting one line)

**Comment by mpdehaan** [comment]
Can you please resubmit this as one commit ?

You may wish to use an interactive-rebase to squash your commits together.

**Comment by dermute** [comment]
Finally the resubmit f3aa445.

**Comment by mpdehaan** [comment]
ignore the close, pressed the wrong button :)

**Comment by mpdehaan** [comment]
This is weird, I don't see a merge button... was this submitted as a pull request?   Seems like it might not have been or something is mixed up.

I'll fix this manually, thanks and sorry for the confusion.

**Comment by mpdehaan** [comment]
Will appear next time we push docs, thanks again!
