### ISSUE TITLE
Project/directory specific ansible.cfg

### ISSUE THREAD

**Issue by mvo5** [ansible/ansible#4123]
I would like to have ansible look for ansible.cfg in the current working directory or alternatively in .ansible/ansible.cfg to allow project specific overrides (just like git).

My use case is that I have the ansible/hosts file in git with the rest of my playbooks and it would save me the typing of ansible-playbook -i ./inventory/hosts

Alternatively if ansible could search ./inventory/hosts and merge that with the global inventory that would solve my use-case as well (but having project specific ansible.cfg may still be useful in its own right).

I'm happy to work on this feature and send a pull request if there is agreement that this is a useful thing to have.

Thanks for your consideration,
 Michael

**Comment by srgvg** [comment]
Actually, ansible already does this, looking for ansible.cfg in $PWD:
http://www.ansibleworks.com/docs/examples.html#id11

**Comment by jimi-c** [comment]
Yes it does, closing this. @mvo5 if you're having issues with this I'd recommend asking on the mailing list. Thanks!
