### ISSUE TITLE
Mask values in extra variables in ansible tower

### ISSUE THREAD

**Issue by avinash-fissionhq** [ansible/ansible#41233]
##### SUMMARY
I am trying to run tower job template with extra variables from jenkins pipeline script. When the job is running I do not want tower to show my credentials in tower extra variables box. Is there any way to mask or encrypt those values?

##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```
Ansible tower version : 3.2.5
```

**Comment by sivel** [comment]
Should This Be Filed Elsewhere?
===============================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be something that should be filed against another project or bug tracker, and let us explain our reasons for thinking this:

   * This issue tracker is for the open source Ansible project, and not for Tower bugs or support.

If you can stop by the tracker or forum for one of those projects, we'd appreciate it.  

Should you still wish to discuss things further, or if you disagree with our thought process, please stop by one of our two mailing lists:

  * https://groups.google.com/forum/#!forum/ansible-project
  * https://groups.google.com/forum/#!forum/ansible-devel

We'd be happy to discuss things.

Thank you once again!
