### ISSUE TITLE
authorized_key can't remove key from a previously removed user's homedir

### ISSUE THREAD

**Issue by jhagg** [ansible/ansible#4124]
(This is ansible 1.2+devel_d2bf244)

I have a problem when I want to remove a user account and
also any keys in ~/.ssh/authorized_keys.

The module authorized_key assumes that a user exists and
tries to get uid and other stuff from the passwd file.

This is a problem if the user just has been removed.

So if the module could ignore uid/gid when state is 'absent',
just relying on path, then it would be able to remove a key.

Actually, most of keyfile() actions is not needed for absent keys
if a complete path is specified to the module.

**Comment by mpdehaan** [comment]
Seems like if you are removing the user you could (also) remove his home directory?

In this case, maintaining the list of all the keys he shouldn't have doesn't seem to need to apply when the user is missing.

In other words I don't expect heavy usage of the state=absent form for keys on non-existant users, as that user can't login anyway.

**Comment by srgvg** [comment]
You could also remove the keys prior to removing the user.

Also, maybe the user module could have an option to delete the home dir, honoring the userdel --remove option. I didn't think that was possible now.

**Comment by jhagg** [comment]
Well, yes, a removed users homedir could be removed.

This is, however, not always the righ thing to do. There
may be important things in the homedir that needs to be preserved.
It could also be that the account just happened to expire.
(This is handled as an account removal here, therefore
the homedir isn't automatically removed. :-)

And yes, it is also possible to do it in the right order. I tried that
but it will complain the next time when the account is missing.

So there will be problems when state is absent and the user is removed,
even if the key already is removed.

As I see it, an absent key should be able to stay absent until
the account is enabled again without complaints.

**Comment by srgvg** [comment]
Point taken.
However: how will you know the deleted user's home directory without it's passwd entry? Plainly assuming it lives in /home/$user seems wrong to me.
If you only want expire or disable an account, you can do that without removing the user.
Other option: using the file module, making sure .ssh/authorized_keys is absent, but you'll still need to know $HOME

**Comment by jhagg** [comment]
That's true, I do need to know the homedir. So an easy solution could be
to not have 'user' required if 'path' is provided, also
ignore uid/gid changes unless 'user' was given.

Would that work?

**Comment by mpdehaan** [comment]
If the user is truly gone, the easiest would probably be:
- copy: content='' dest=/whatever/path/id_rsa.pub

But since the user was already deleted, they can't login anyway, so this seems like a concern that won't come up much.

Patches would be considered depending on complexity, though I don't think this is really a bug given they can't login anyway.
