### ISSUE TITLE
template_path variable documented to be relative path, should say absolute path

### ISSUE THREAD

**Issue by wu-lee** [ansible/ansible#4126]
Documentation currently here claims that {{ template_path }} in a template will expand to the _relative_ template path:

   http://www.ansibleworks.com/docs/modules.html#template

What appears to be inserted is actually the absolute path.

Tested on:

```
ansible-playbook --version
ansible-playbook 1.4 (devel f4b3defcbf) last updated 2013/09/16 10:55:26 (GMT +100)
```

See this gist for a test case:  https://gist.github.com/wu-lee/6581115

The actual output I get is 

```
hello from /path/to/my/playbook/test.j2
```

First noticed this when using {{ansible_managed}} variable in templates  - which inserts the full path using what is essentially this template_path variable.  Would much prefer the relative path!

**Comment by jimi-c** [comment]
The template path can be specified as a relative path in the play, but internally it will (and should) always be expanded to the full path to make sure we're accessing the file that was requested, even during user transitions like sudo.

**Comment by mpdehaan** [comment]
Looks like there is in fact a docs bug here where it should say "absolute"

**Comment by mpdehaan** [comment]
note: I'm saying this is a docs bug, and we are not going to include the relative path.

**Comment by wu-lee** [comment]
The option to get just the template name would be preferable if relative path information is lost.  What I'm actually interested in is making the output in {{ansible_managed}} readable when it includes the {file} tag.

**Comment by sa2ajj** [comment]
Sorry to comment on this closed issue: I've been "hit" by this problem as I did not read the phrasing very carefully and _assumed_ that `_fullpath` would be different becasue of the name.  But it turned out that both variables -- `template_path` and `template_fullpath` -- now have the same value and the same documentation.
