### ISSUE TITLE
Modifying ec2_vol module to allow "detach/delete previously created ebs volume" feature

### ISSUE THREAD

**Issue by pattu777** [ansible/ansible#4127]
I have been using ansible and via its ec2_vol module, I can create an ebs volume and optionally attach it to an instance. 

My code snippet is 

  tasks:

```
- name: Launch Instances
  local_action: ec2 keypair={{keypair}} group={{security_group}} instance_type={{instance_type}} image={{image}} wait=true count={{count}} region={{region}} instance_tags='{"Name":"NewansibleTest021"}'
  register: ec2

- name: Add volume
  local_action: ec2_vol instance={{item.id}} volume_size=5 
  with_items: ec2.instances
  register: ec2_vol
```

But there is no provision to detach the volume from the instance and subsequently deleting it(state='absent' kinda thing in ec2 module). So it would be great to have this feature enabled into ec2_vol module.

Thanks,

**Comment by snapo** [comment]
since this is not yet implement, i try to use it in this way:
module: uri
https://ec2.amazonaws.com/?Action=DetachVolume&VolumeId=volume-id&InstanceId=instance-id&AUTHPARAMS
could be that this will help you too

**Comment by mpdehaan** [comment]
Hi,

We've keeping track of this list but haven't seen any traction here, so are closing this ticket out.  If someone would like to submit a pull request, that would be welcome, and we're still open to it.
