### ISSUE TITLE
ec2_group "delete security group" feature

### ISSUE THREAD

**Issue by pattu777** [ansible/ansible#4128]
I used ansible's ec2_group module to create new security groups with some default rules. But it does not have the feature to delete a previously created security group.

Currently I am using "aws ec2 delete-security-groups" via ansible's command module to perform this task. My snippet is - 

tasks: 

```
- name: delete a security group
  local_action: command aws ec2 delete-security-group --region={{region}} --group-id=xxxx
```

So it would be really helpful to have that feature enabled.

Thanks,

**Comment by neh** [comment]
Does https://github.com/ansible/ansible/pull/4338 solve this?

**Comment by mpdehaan** [comment]
Yep, closing this, thanks!
