### ISSUE TITLE
Empty main.yml in role defaults directory causes ansible to crash

### ISSUE THREAD

**Issue by gregbuehler** [ansible/ansible#4129]
```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 268, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-playbook", line 168, in main
    play = ansible.playbook.Play(pb, play_ds, play_basedir)
  File "/Library/Python/2.7/site-packages/ansible/playbook/play.py", line 123, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/Library/Python/2.7/site-packages/ansible/playbook/play.py", line 410, in _load_tasks
    default_vars = utils.combine_vars(self.default_vars, x.get('default_vars', {}))
  File "/Library/Python/2.7/site-packages/ansible/utils/__init__.py", line 853, in combine_vars
    return dict(a.items() + b.items())
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by jimi-c** [comment]
I believe the following patch should fix this, if you'd like to give it a try:

<pre>
diff --git a/lib/ansible/playbook/play.py b/lib/ansible/playbook/play.py
index 1c833a4..578a2d8 100644
--- a/lib/ansible/playbook/play.py
+++ b/lib/ansible/playbook/play.py
@@ -407,7 +407,12 @@ class Play(object):
                     else:
                         raise errors.AnsibleError("parse error: task includes cannot be used with other directives: %s" % k)
 
-                default_vars = utils.combine_vars(self.default_vars, x.get('default_vars', {}))
+                default_vars = x.get('default_vars', {})
+                if not default_vars:
+                    default_vars = self.default_vars
+                else:
+                    default_vars = utils.combine_vars(self.default_vars, default_vars)
+
                 if 'vars' in x:
                     task_vars = utils.combine_vars(task_vars, x['vars'])
                 if 'only_if' in x:
</pre>

**Comment by srgvg** [comment]
FYI, empty yaml files yield errors in a more general way (which can be python failing to parse an empty file), AFAIK. 
E.g. an empty host/groups_vars file will error when read at startup.

**Comment by jimi-c** [comment]
@sergevanginderachter yeah I think we were a little more accommodating in the code we added recently.
