### ISSUE TITLE
Gathering facts confirmation

### ISSUE THREAD

**Issue by brandonhilkert** [ansible/ansible#4131]
I upgraded to 1.3.1 from 1.2.3 and on the gather facts setup now, it asked this:

```
GATHERING FACTS ***************************************************************
The authenticity of host 'ec2-54-227-139-150.compute-1.amazonaws.com (54.227.139.150)' can't be established.
RSA key fingerprint is 5f:6f:43:70:3f:bd:16:d2:8f:63:eb:ad:49:76:5c:b8.
Are you sure you want to continue connecting (yes/no)? yes
<ec2-54-227-139-150.compute-1.amazonaws.com> REMOTE_MODULE setup
ok: [ec2-54-227-139-150.compute-1.amazonaws.com]
```

It never did this before. What's the recommended way to silent or auto-accept this?

**Comment by jimi-c** [comment]
During your upgrade, did you replace your ansible.cfg? You can disable this by un-commenting (or adding) `host_key_checking = False` in the ansible.cfg.

**Comment by brandonhilkert** [comment]
Where does this config file go? I installed via homebrew?

**Comment by jimi-c** [comment]
You can put it in your home directory. Refer to the `examples/ansible.cfg` file for the default file.
