### ISSUE TITLE
Error when create Notification from Ansible tower to HipChat

### ISSUE THREAD

**Issue by mbrother2** [ansible/ansible#41389]
##### SUMMARY
Error when create Notification from Ansible tower to HipChat

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

Create Notifications

##### ANSIBLE VERSION

```
Ansible 2.5.2
Tower 3.2.0
```

##### CONFIGURATION

NOTIFICATION COLOR: Gray

##### OS / ENVIRONMENT

CentOS 7.5

##### STEPS TO REPRODUCE

- Config notification from Ansible Tower to HipChat
- Run test notification

##### ACTUAL RESULTS

Test notification fail and error log in /var/log/tower/tower.log
"message": "Value u'Gray' for field 'color' is not in the enumeration: ['yellow', 'green', 'red', 'purple', 'gray', 'random']",

**Comment by mbrother2** [comment]
I must edit core file "/var/lib/awx/public/static/app.js" to change Gray value (two positions) to gray. Then I run test notification, it works!

**Comment by sivel** [comment]
Should This Be Filed Elsewhere?
===============================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be something that should be filed against another project or bug tracker, and let us explain our reasons for thinking this:

   * This issue tracker is for the open source ansible project, and does not support Tower or AWX

Feel free to utilize your support contact to file this issue, or consider logging a bug at https://github.com/ansible/awx

Should you still wish to discuss things further, or if you disagree with our thought process, please stop by one of our two mailing lists:

  * https://groups.google.com/forum/#!forum/ansible-project
  * https://groups.google.com/forum/#!forum/ansible-devel

We'd be happy to discuss things.

Thank you once again!
