### ISSUE TITLE
Missing Azure functionality - sql firewall? 

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#41394]
##### SUMMARY

I can't find any information about setting firewall on azure sqlserver (az command: az sql server firewall-rule create) but i can't find how to achieve by ansible.
##### ISSUE TYPE
 - Documentation Report

##### ANSIBLE VERSION

```
2.5.0
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by ryansb** [comment]
It doesn't appear there's a module for the SQL Server firewall rules available in Ansible 2.5.0, you can see the full list of Azure modules that are available in [the module index](https://docs.ansible.com/ansible/devel/modules/list_of_cloud_modules.html#azure). Instead, it's possible to use the `command` module to run the Azure CLI to set your rules.
