### ISSUE TITLE
Sequence should use kwargs rather than parsing a string.

### ISSUE THREAD

**Issue by Everspace** [ansible/ansible#41417]
##### SUMMARY

Sequence parses a string rather than taking kwargs in a lookup

##### ISSUE TYPE
 - Feature Idea
 - Bug Report

##### COMPONENT NAME

sequence

##### ANSIBLE VERSION
```
ansible 2.5.2
  config file = /ansible/ansible.cfg
  configured module search path = ['/ansible/library', '/usr/share/ansible']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.5 (default, May  5 2018, 03:09:35) [GCC 4.9.2]
```

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE

```yaml
  - debug:
      msg: "{{lookup('sequence', 'start=1 end=5')}}"
```
works

```yaml
  - debug:
      msg: "{{lookup('sequence', start=1, end=5)}}"
```
Produces empty string.

##### EXPECTED RESULTS

The kwarg version should produce an array, and the string version should be deprecated.

##### ACTUAL RESULTS

An empty array is produced

**Comment by sivel** [comment]
It is recommended instead of using `sequence` to instead use the jinja2 `range` function:

```
- debug:
    # range omits the endpoint, so 6 here instead of 5
    msg: "{{ range(1, 6)|list }}"
```

See also: https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_2.5.html#with-sequence

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by Everspace** [comment]
Right, so there should be a deprecation warning which is more what I am
concerned about.

**Comment by sivel** [comment]
We typically don't deprecate in the same version we add a new recommended way of achieving a result.  Because we had not previously called out a change in recommended way to achieve a result until just recently, we haven't added a deprecation.  A deprecation will follow in a future version.
