### ISSUE TITLE
Unable to set selevel, file attributes on SELinux enabled hosts always marked as changed

### ISSUE THREAD

**Issue by kuba** [ansible/ansible#4142]
With SELinux enabled host, every run of the following command:

```
ansible host -m lineinfile -a "line=test regexp=test dest=/tmp/test"
```

results in the following message:

```
"msg": "ownership, perms or SE linux context changed".
```

although no file permissions change before or after the run:

```
# ls -alZ /tmp/test 
-rw-r--r--. 1 ansible ansible unconfined_u:object_r:user_tmp_t:SystemLow 5 Sep 17 21:41 /tmp/test
```

The problem exists with every file related module: copy, template, etc.. I believe this is caused by the following line from **module_common.py**:

```
selevel   = params.get('serange', 's0')
```

It's not possible to set **_serange**_ as modules do not accept it, and **_selevel**_ is never read.

**Comment by kuba** [comment]
Yup, I think #4143 solves this issue -  my terminal just got greener :)

**Comment by jimi-c** [comment]
#4143 was merged in, so closing this. Thanks for reporting it!
