### ISSUE TITLE
Ansible Galaxy missing folders inside repository

### ISSUE THREAD

**Issue by bradhanebury** [ansible/ansible#41446]
##### SUMMARY
There appears to be a discrepancy between what `ansible-galaxy` installs and what should be available. We have a private Github repository that we use to share common Ansible roles across projects. Inside our `requirements.yml` file we include it as such:

````
- src: git@github.com:mobials/devops.git
  version: master
  scm: git
````
We set the version to `master` when developing the application, however in production we plan on setting it to a specific version (however, in order to help debug this issue, we have attempted requesting a specific version). 

When we install the role via the following command, what appears inside the roles folder is not what is currently available on our `master` branch on this repository. 

`ansible-galaxy install -v -p roles -r requirements.yml`

We have also tried installing this single role directly and not within a requirements file via: 

`ansible-galaxy install git+git@github.com:mobials/devops.git`

We have tried using the `--force` param as well. We have also had multiple people on our team attempt the above on different systems and even in different locations (to rule out a bizarre ISP caching issue).

We have also done a clean `git clone git@github.com:mobials/devops.git` and were able to verify that the contents are different. At this point, we have no explanation for what might be happening.  

As for what is different: from what we can tell there is one specific role missing in all instances which is named `node` (it obviously installs Node and performs some setup for our systems). 

Directory structure of this repo for the roles is roughly
````
- devops
  - roles
     - app (multiple roles in here)
     - service (multiple roles in here)
        - node (this is the role / directory that is missing)
     - system (multiple roles in here
````

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
Ansible version 2.5.2
```

##### OS / ENVIRONMENT

Ubuntu 16.04 
MacOSX - multiple versions

##### STEPS TO REPRODUCE

Unfortunately as this is a private repository, it cannot be reproduced exactly. However, below is a list of the `ansible-galaxy` commands we have used in an attempt to remedy this. 

`ansible-galaxy install -v -p roles -r requirements.yml`
`ansible-galaxy install git+git@github.com:mobials/devops.git`
`ansible-galaxy install --force git+git@github.com:mobials/devops.git`

Below are the contents of our playbook file

```yaml
- src: git@github.com:mobials/devops.git
  version: master
  scm: git
```

##### ACTUAL RESULTS

```

```

**Comment by maxamillion** [comment]
Thank you for the issue report! Unfortunately, I think I'm going to need a little more information. What is the expected results and the actual results? I don't think I have enough information to really track this one down but I'm happy to look into it further if you can offer some sanitized example output.

**Comment by bradhanebury** [comment]
Without being able to provide access to the repository:

Expected Result is that the repository being requested via `git@github.com:mobials/devops.git` is included in full inside the `roles` folder. 

The Actual Result is that the files in the roles folder created by ansible galaxy are missing directories that are present in the repo. 

For A better understanding, I've included two screen shots of the Expected directory structure (as via a `git clone` and the Actual directory structure (via ansible-galaxy install). Note how the `node` folder is present on the expected (this is local, but also mirrors `master` on Github at the above repository), but it is absent in the actual. 

Expected:

![screen shot 2018-06-12 at 12 20 59 pm](https://user-images.githubusercontent.com/868645/41303403-2a566f04-6e3b-11e8-9308-79037dd00e3b.png)

Actual

![screen shot 2018-06-12 at 12 21 26 pm](https://user-images.githubusercontent.com/868645/41303409-2eb5b9e2-6e3b-11e8-80a4-b6af07ea48b0.png)

**Comment by bradhanebury** [comment]
My assumption is that this is due to how ansible-galaxy is including the repository. My understanding is that by including the role (it's actually a collection of roles) via a private Github URL, ansible-galaxy should ideally just `git clone` the repository. However, it appears to be modifying the base directory structure by adding additional folders that would be relevant to a repository hosting a single role.

**Comment by maxamillion** [comment]
`anisble-galaxy` as it stands today only handles single-role per scm repo structures, there's an [active proposal to change this](https://github.com/ansible/galaxy/issues/245) but it's not true at this time

**Comment by bradhanebury** [comment]
I was aware of that fact, but I am surprised that loading a role via `ansible-galaxy` is modifying its base directory structure. This feels like it might be the source of the odd behaviour.

**Comment by maxamillion** [comment]
I'm going to go ahead and close this. I think [mazer](https://github.com/ansible/mazer) might be of interest though.
