### ISSUE TITLE
alternative ansible 1st argument syntax

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#4149]
I use tool with part of ansible functionality. It has following syntax: <b>command group1,group2,host1,host2,-group3,-host3 action 'arg1 arg2 # etc...'</b>
I think, it is more shell-friendly -- there is no need to quote expression (ansible asks for <b>"!"</b> symbol, which is pre-defined in bash). And <b>","</b> is easier for me, than <b>":"</b>.

Can this syntax be integrated in ansible? Or I have to write my wrapper?

**Comment by jimi-c** [comment]
That is non-standard unix syntax, and supporting multiple methods of specifying command line arguments would be error-prone and confusing. Thanks for the suggestion, however we will be sticking with syntax we're currently using.

**Comment by jimi-c** [comment]
Also, I highly recommend asking questions of this nature on the ansible-devel mailing list/Google group we just created, which would is a better forum for bouncing ideas off of users.
