### ISSUE TITLE
Loop collections undergo evaluation, even when the task containing the loop is skipped

### ISSUE THREAD

**Issue by wknapik** [ansible/ansible#41555]
##### SUMMARY
Loop collections undergo evaluation, even when the task containing the loop is skipped.

The behavior is different if the lookups are a part of the task being skipped, rather than the collection used in the loop (no error, just skipped execution).

I ran into this while using a block where some files are created in the first task and the second task uses a loop to do something with the content of each of them. If you run a lookup on those files, despite the failed condition for the block, this will trigger an error, because they don't exist.

##### ISSUE TYPE
Bug Report

##### COMPONENT NAME

core

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/foo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.5 (default, May 11 2018, 04:00:52) [GCC 8.1.0]
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml
- when: false
  debug: msg=""
  loop: ["{{ lookup('file', '/nonexistent') }}"]
```

##### EXPECTED RESULTS

skipping

##### ACTUAL RESULTS

fatal

```
TASK [debug] **********************************************************************************************************************************************************************************************************************************
 [WARNING]: Unable to find '/nonexistent' in expected paths (use -vvvvv to see paths)

fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: /nonexistent"}
```

**Comment by sivel** [comment]
This is the expected behavior.  The `when` statement is evaluated for each iteration of the loop, not before the loop is processed.

As such, your loop must be able to be evaluated, regardless of the `when` statement.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by wknapik** [comment]
With the behavior being so dramatically different between
```
- when: false
  debug: msg="{{ item }}"
  loop: ["{{ lookup('file', '/nonexistent') }}"]
```
and
```
- when: false
  debug: msg="{{ lookup('file', '/nonexistent') }}"
```
shouldn't that at least be pointed out in the docs somewhere ?

**Comment by sivel** [comment]
From https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#standard-loops:

> Also be aware that when combining Conditionals with a loop, the `when:` statement is processed separately for each item. See The When Statement for an example.

**Comment by wknapik** [comment]
Yeah, I would not figure out that behavior based on that... It says nothing about the loop collection being evaluated unconditionally (which could have side-effects other than just failure).

Anyway - is there a workaround for this when the loop is used because of `include_tasks`  tasks using `item` (expecting to be used in a loop) ?

**Comment by wknapik** [comment]
For those who get here from google - if you're using ansible >=2.6, you can use `lookup(..., errors='ignore')`; if you're on <2.6, use `set_fact` with either an appropriate `when` condition, or `ignore_errors: true` and loop over the variables.

**Comment by wknapik** [comment]
Didn't find this #13950 before.
