### ISSUE TITLE
fetch module fails due to permissions even when using sudo

### ISSUE THREAD

**Issue by mplonka** [ansible/ansible#4155]
I'm not sure if the issue is fixable at all. It could save other users some frustration if it's documented at least.

**Steps to reproduce the problem**

**On the managed node**

```
sudo su -
touch /tmp/test.txt
chmod 600 /tmp/test.txt
```

**Ansible, without sudo**

```
ansible -i INV -m fetch -a "dest=/tmp src=/tmp/test.txt" targethost
```

_result:_

```
targethost| success >> {
    "changed": false,
    "file": "/tmp/test.txt",
    "msg": "no read permission on remote file, not transferring, ignored"
}
```

**Ansible, with sudo**

```
ansible -i INV -m fetch -a "dest=/tmp src=/tmp/test.txt" targethost -s
```

_result:_

```
targethost | FAILED => failed to transfer file from /tmp/test.txt
```

**Comment by mpdehaan** [comment]
I'm not sure what Ansible version you are using but newer versions of fetch will use the "slurp" module and not scp.  This may just be a case of wanting better errors from the slurp module when it can't read things.

**Comment by mpdehaan** [comment]
I'm going to call this message ok for now.  I will entertain upgrades.
