### ISSUE TITLE
accelerate mode only has one timeout value

### ISSUE THREAD

**Issue by omgjlk** [ansible/ansible#4162]
Unlike ssh, which appears to have a connection timeout value which is wholly different from a task execution timeout, accelerate mode only appears to have one timeout.

This can create a very big problem, where one has to set the timeout very high to deal with long running processes, but then have to deal with very long timeouts on dark hosts.

It would be quite nice to duplicate what exists for ssh, where one can have a very short connection timeout (5 seconds) to give up on dark hosts, but a very long session timeout to handle long running tasks w/out resorting to a ton of async usage.

In our rather large environment we constantly have dark hosts, so this single timeout value will prevent us from going forward with accelerate mode.

**Comment by bcoca** [comment]
Since it uses ssh to step, would that not solve the issue already?

Brian Coca

**Comment by jimi-c** [comment]
The analog to the connection timeout is hard-coded, but it has been decreased quite a bit from the alpha-version (3 retries with a 0.1 second sleep in between). The overall timeout was increased to 5 minutes (if no data is received this is hit), so that's probably the one you'd like to setup to be configurable, correct?

**Comment by omgjlk** [comment]
In my testing, I was seeing a VERY lengthy delay when any of the hosts were dark. It seemed like the 5 minute timeout was used. Making that shorter (5 seconds) definitely made ansible give up on dark hosts a lot faster, but then a simple command: sleep 10 will error out on ALL the hosts, because 10 second sleep is longer than the 5 second timeout.

BTW I'm testing with cac9e02aead564aece043d43a8aee4fa3bfe3faa , the 1.3.1 release.

**Comment by jimi-c** [comment]
Yeah the 3 retry setting I mentioned above should be in the 1.3.1 release, however if the host is dark it will attempt the accelerated connection (0.3s to timeout) and then try SSH which will timeout according to its setting. Once the accelerated connection is started, there is a (currently the default) 300s timeout to receive something on the socket. The longer delay should only be hit if the connection was actually completed but then one side stopped sending data back. This might happen if the daemon is killed or some other error occurred. So really what would be required there would be some kind of keepalive mechanism (which I know we discussed via IRC in the past), which should probably be a separate request from this.
