### ISSUE TITLE
Remove needs to use {{ lookup('foo', 'bar') }} by adding options in filters

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#4164]
These kinds of syntaxes are a little gross and it's confusing what is a lookup plugin vs a filter sometimes.   It would be easier if lookup plugins were for getting collections and then they would only be used for "with_*" type cases.

Let's keep lookup plugins for "with_" \* type usage but these can be implemented as filters.

```
{{ path | contents }}
{{ path | password(param, param) }}
```

etc

If we were to move these over we might have to make the old usage still work (could legacy lookup plugins call into filter code to reuse?) but could update lots of examples including the doc to make this feel much better.

**Comment by srgvg** [comment]
So this means you want to get rid of the "lookup()" syntax as a keyword? If so we better need to come up with another syntax for the nested with_ lookups as per #4060.

**Comment by mpdehaan** [comment]
No, I don't want to get rid of it, but rather it is more elegant and readable to not have to know what lookup plugins are.  

I was thinking they could be offered both ways.

**Comment by mpdehaan** [comment]
Also note this is about using lookup plugins in "lookup" mode, not in the way they are used to implement loops.

While these come from the same plugins, this is not something users have to worry about.

**Comment by mpdehaan** [comment]
We don't have any plans to change this at this time -- usage of lookup() has been pretty well minimized already.
