### ISSUE TITLE
with_items: groups[] inconsistent behavior

### ISSUE THREAD

**Issue by faust64** [ansible/ansible#4171]
using ansible-1.3 from pip

with the following syntax:

testrole/tasks/main.yml:
- include: /root/testreport/roles/testrole/tasks/stuff.yml
  with_items: groups['all']

testrole/tasks/stuff.yml
- name: dummy stuff
  file: dest=/tmp/{{ item }} owner=root group=root mode=0700

I have the following error:
ansible:~/testreport# ansible-playbook -i hostfile site.yml -l ansible.example.com
ERROR: with_items expects a list
ansible:~/testreport# vim production 

Expected result could be obtained either with the following testrole/tasks/main.yml
- include: /root/testreport/roles/testrole/tasks/stuff.yml
  with_items:
    - ansible.example.com
    - muninone.example.com
    - munintoo.example.com

Or the following testrole/tasks/stuff.yml:
- name: dummy stuff
  file: dest=/tmp/{{ item }} owner=root group=root mode=0700
  with_items: groups['all']

Is there some reason with_items: can't invoke groups[] on include tasks?

**Comment by mpdehaan** [comment]
with_items + include is not a supported feature, this is expected.

You will notice include + with_items is not mentioned in the docs for this reason.

The solution is to just loop over the collections inside the task, using "with_nested" where you might need a double loop.

**Comment by faust64** [comment]
ok, thanks
