### ISSUE TITLE
hostvars[] access from playbook

### ISSUE THREAD

**Issue by faust64** [ansible/ansible#4173]
using ansible-1.3 from pip

Having something like this:
- name: ensure hosts from current run gets munin-monitored
  template: src=/x/munin/templates/client.j2 dest=/etc/munin/objects/{{ item }}.conf ...
  with_items: groups['all']
  when: hostvars[{{ item }}] is defined

When evaluates to true for each host. Which is expected.

Within the client.j2 template, If related {{ item }} has been contacted during current run, I can use its variables using {{ hostvars[item]['ansible_default_ipv4']... }} and such. Otherwise, not. Which is expected.

Now when I try to check for a fact, guaranteeing related host has been contacted during current run :
- name: ensure hosts from current run gets munin-monitored
  template: src=/x/munin/templates/client.j2 dest=/etc/munin/objects/{{ item }}.conf ...
  with_items: groups['all']
  when: hostvars[{{ item }}]['ansible_default_ipv4'] is defined

Expected result would involve the addition/update of several /etc/munin/objects/$fqdn.conf corresponding to hosts included in current run.
For now, all nodes skip this step:

> ansible-playbook -i production centos.yml -l muninservices
> [...]
> TASK: [install munin server configuration file] *******************************
> ok: [muninone.example.com]
> ok: [munintoo.example.com]

TASK: [ensure hosts from current run gets munin-monitored] ********************
[...]
skipping: [muninone.example.com] => (item=muninone.example.com)
skipping: [munintoo.example.com] => (item=muninone.example.com)
skipping: [munintoo.example.com] => (item=munintoo.example.com)
skipping: [muninone.example.com] => (item=munintoo.example.com)
[...]

I would normally have considered this feature request, since your documentation only quote samples related to templates.
Yet it seem I can check for hostvars[{{ item }}] is defined, within playbook.
So maybe is this bug report?

**Comment by jimi-c** [comment]
Did you see the reply on the mailing list regarding this? The suggestion was to do this instead: `{{ hostvars[item]['ansible_default_ipv4']['address'] }}`.

**Comment by faust64** [comment]
I've just replied.
Such syntax errors here.

ansible:~/playbooks# cat roles/munin/tasks/server/suckit.yml 
- name: ensure hosts from current run gets munin-monitored
  template: src=/x/munin/templates/client.j2 dest=/etc/munin/objects/{{ item }}.conf owner=root group={{ gid_zero }} mode=0644
  with_items: groups['all']
  when: {{ hostvars[item]['ansible_default_ipv4'] }}
# when: {{ hostvars[item]['ansible_default_ipv4'] }} is defined
# when: ansible_default_ipv4['address'] in hostvars[{{item}}]['munin_queryhost']
# when: hostvars[{{ item }}] is defined
# when: hostvars[{{ item }}] is defined and hostvars[{{ item }}]['ansible_default_ipv4'] is defined
# when: hostvars[{{ item }}]['ansible_default_ipv4'] is defined

ansible:~/playbooks# ansible-playbook -i production centos.yml -l muninservices
ERROR: Syntax Error while loading YAML script, /x/munin/tasks/server/suckit.yml
Note: The error may actually appear before this position: line 5, column 20

  with_items: groups['all']
  when: {{ hostvars[item]['ansible_default_ipv4'] }}

**Comment by faust64** [comment]
here it is:

\- name: ensure hosts from current run gets munin-monitored
  template: src=/x/munin/templates/client.j2 dest=/etc/munin/objects/{{ item }}.
  when: "hostvars[item]['ansible_default_ipv4'] is defined"

TASK: [ensure hosts from current run gets munin-monitored] ********************
changed: [muninone.example.com] => (item=muninone.example.com)
changed: [munintoo.example.com] => (item=muninone.example.com)
changed: [muninone.example.com] => (item=munintoo.example.com)
changed: [munintoo.example.com] => (item=munintoo.example.com)

Well, I guess this is not a bug. Even if quoting it felt strange the first time, I can get used to it.
However this could be told in the docs.

Anyway, thanks, and great work!

**Comment by anirudh-wa** [comment]
I am using the variable in the proper format and I get recursive loop error. Any help ?

maxHeapSizeAnsi:        "{{(hostvars[inventory_hostname]['ansible_memtotal_mb'] \* 3 / 4)|int}}"
