### ISSUE TITLE
S3 ImportError: No module named hashlib

### ISSUE THREAD

**Issue by sgoodliff** [ansible/ansible#4174]
hi,

As requested on google groups

I'm running ansible 1.3 from git on RHEL5 and is all working great, I'm trying to get the s3 module up and running for some log archiving but  when i try something like

tasks:
- name: GET OBJECT from S3
   local_action: s3 bucket=sjgmedia object=/photos/locations/copenhagen/DSC_0001.JPG dest=/tmp/DSC_0001.pg overwrite=true

ansible-playbook s3test.yml -vv

PLAY [cobbler] ****************************************************************

TASK: [GET OBJECT from S3] ****************************************************
<127.0.0.1> REMOTE_MODULE s3 bucket=sjgmedia object=/photos/locations/copenhagen/DSC_0001.JPG dest=/tmp/DSC_0001.pg overwrite=true
failed: [cobbler] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/sgoodliff/.ansible/tmp/ansible-1379592526.12-166004534605062/s3", line 113, in ?
    import hashlib
ImportError: No module named hashlib

FATAL: all hosts have already failed -- aborting

I installed boto from git and lss3 works for example.

**Comment by lwade** [comment]
Hi Steven,

Is the python-hashlib package installed?

Lester

**Comment by sgoodliff** [comment]
Hi,

Yep,

I have the following files

/usr/lib64/python2.6/hashlib.py
/usr/lib64/python2.6/hashlib.pyc
/usr/lib64/python2.6/hashlib.pyo
/usr/lib64/python2.6/lib-dynload/_hashlib.so

and

python
Python 2.6.8 (unknown, Nov  7 2012, 14:47:45)
[GCC 4.1.2 20080704 (Red Hat 4.1.2-52)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import hashlib

works.

Thanks

**Comment by lwade** [comment]
OK, and on the system on which you are targeting for the module invocation
right?

**Comment by jimi-c** [comment]
@sgoodliff You don't have any other python interpreters on the system do you? And you're not setting ansible_python_interpreter in the inventory?

**Comment by sgoodliff** [comment]
Hi,

Its a RHEL5 server so it has python 2.4 as well, I'm not setting the
ansible_python_interpreter.

Also I'm trying to run the playbook on this server.

Thanks

**Comment by sgoodliff** [comment]
Hi,

I tried the same on a RHEL6 server. boto and ansible installed exactly the same way. 

So must be a clash somewhere with the python 2.4 interpreter installed on the RHEL5 server.

**Comment by sgoodliff** [comment]
HI,

ansible/library/cloud/s3 has #!/usr/bin/python as the 1st line. setting it to #!/usr/bin/env python fixes it for me.

**Comment by ScottSturdivant** [comment]
It appears you have python2.6 and python2.4 installed side by side but hashlib installed only in 2.6.  `/usr/bin/python` is presumably 2.4 without hashlib, whereas `/usr/bin/env python` launches 2.6 with hashlib. Thus it seems like the correct fix would be to set `ansible_python_interpreter` to point to your python2.6 install.  Ansible replaces the shebang lines appropriately. See:  http://ansibleworks.com/docs/faq.html#id5

**Comment by jctanner** [comment]
Steven, 

if you still see this problem when setting ansible_python_interpreter to a python 2.6 path on your EL5 system, please open a new bug.
