### ISSUE TITLE
not able to start filebeat, metricbeat using ansible in RHL6 

### ISSUE THREAD

**Issue by santomanto04** [ansible/ansible#41750]
I am running this task in ansible playbook.
- name: Start filebeat service
   shell:  /fisc/uts/bin/sudo filebeat start 

This does not start the filebeat agent. But I have checked manually running "/fisc/uts/bin/sudo filebeat start" on the test servers. It works fine.  (I tried 'command' instead of 'shell', it doesn't work either)

The stop command works tho if I replace start with stop. But "start" and "restart" doesnot work". Can anybody help?

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
