### ISSUE TITLE
make rpm packaging work for SuSE

### ISSUE THREAD

**Issue by dirtyharrycallahan** [ansible/ansible#4175]
The rpm packaging does not work for SuSE. It has never worked as long as I have been using Ansible so each time I install or update I have been hacking ansible.spec to create an rpm. [open]SuSE package names, when available, are not the same as those used by the RHEL based distros.

**Comment by bcoca** [comment]
If you could submit your changes as a pull request it might help them to
include it in for the next release.

**Comment by dirtyharrycallahan** [comment]
Will try but I'll need to spawn more virtual machines to test SuSE, openSuSE, CentOS 5 and 6, RHEL 5 and 6, Fedora ...

**Comment by mpdehaan** [comment]
Any progress on this?

**Comment by dirtyharrycallahan** [comment]
I started with trying to understand a little bit more about how python, how the setup code gets installed, ... Got a new cluster at work and have been working on that. Have not had the time to get back to it. I will put in a few hours this coming weekend to try to sort it out.

**Comment by dirtyharrycallahan** [comment]
I was able to find some time last night to start working on this. I read through the SuSE python packaging docs and I got as far as being able to create the rpm on openSuSE 11.4. I will test it on openSuSE 11.4 and 12.3; and CentOS 6 and RHEL 5/6 for regression.

**Comment by mpdehaan** [comment]
We have another pull request that cuts out a lot of the OS specifics that we are going to review, so I am going to close this ticket so we can track the new one.

Thanks!
