### ISSUE TITLE
Add clone command to virt module [feature request]

### ISSUE THREAD

**Issue by gdamjan** [ansible/ansible#4178]
as in 
http://linux.die.net/man/1/virt-clone

**Comment by mpdehaan** [comment]
patches would be considered if this is something you want to work on.

However, as many people don't manage virtual machines directly and are using cloud infrastructure these days, I don't think this is something we are going to work on.

**Comment by mrlesmithjr** [comment]
Anyone opposed to making this a separate module such as `virt_clone` rather than adding clone to the existing `virt` module?
