### ISSUE TITLE
"Invalid ini entry" with hosts-script and ini-file

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#4186]
My ansible version:
ii  ansible                                1.3.0-precise-unstable-1                Ansible Application

I have got script in /etc/ansible/hosts and in my working directory (it is the same file):
$ md5sum /etc/ansible/hosts
f2a884c00bedebe12a331b2c498ec25b  /etc/ansible/hosts
$ md5sum c2a.py 
f2a884c00bedebe12a331b2c498ec25b  c2a.py

I am running without "-i":
$ ansible myhostgroup --list-hosts
    host1.example.com
    host2.example.com
I am running with "-i":
$ ansible myhostgroup --inventory-file=$(pwd)/c2a.py --list-hosts
ERROR: Invalid ini entry: requests - need more than 1 value to unpack

**Comment by jimi-c** [comment]
Is the c2a.py marked as executable?

**Comment by ghost** [comment]
It wasn't, sorry :(
I was confused by error text, can we have special error for this case?

**Comment by jimi-c** [comment]
It might be possible, though tricky, since the only indication that it's a script is whether the executable bit is set.
