### ISSUE TITLE
When looping, item is reported as None

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [ansible/ansible#41911]
##### SUMMARY
When looping, `item` is reported as `None`

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.5.5
  config file = /mi/A/ansible.cfg
  configured module search path = ['/mi/A/playbooks/library']
  ansible python module location = /opt/lib/python3.6/site-packages/ansible
  executable location = /opt/bin/ansible
  python version = 3.6.5 (default, Jun 14 2018, 17:43:00) [GCC 4.2.1 Compatible FreeBSD Clang 6.0.0 (tags/RELEASE_600/final 326565)]
```

##### CONFIGURATION
ALLOW_WORLD_READABLE_TMPFILES(/mi/A/ansible.cfg) = True
DEFAULT_FORKS(/mi/A/ansible.cfg) = 53
DEFAULT_MODULE_PATH(/mi/A/ansible.cfg) = ['/mi/A/playbooks/library']
DEFAULT_TIMEOUT(/mi/A/ansible.cfg) = 23

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE

Run the below playbook, no inventory necessary:
```yaml
- hosts: localhost
  gather_facts: false
  tasks:
  - debug: msg="{{ item }}"
    with_items: with_items: ["a", "b", "c"]
```

##### EXPECTED RESULTS
```
ok: [localhost] => (item=a) => {
    "msg": "a"
}
ok: [localhost] => (item=b) => {
    "msg": "b"
}
ok: [localhost] => (item=c) => {
    "msg": "c"
}
```

##### ACTUAL RESULTS

```
ok: [localhost] => (item=None) => {
    "msg": "a"
}
ok: [localhost] => (item=None) => {
    "msg": "b"
}
ok: [localhost] => (item=None) => {
    "msg": "c"
}
```

Also, if I change the debug task from `msg="{{ item }}"` to `var=item`, I get _empty_ output from each debug. Not right...

This seems like a recent regression.

**Comment by sivel** [comment]
This issue has recently been resolved in https://github.com/ansible/ansible/pull/41331 and is expected to be included in the 2.6 release, and potentially a future 2.5.x release.
