### ISSUE TITLE
Moustache variables passed to dependant roles can stringify boolean False into "False" truth

### ISSUE THREAD

**Issue by wu-lee** [ansible/ansible#4194]
Given a role 'consumer' and which depends on another 'dep'.

Let consumer accept a boolean parameter, and pass it on to dep verbatim.

If dollar variables are used, all is well.

If moustaches are used, False is apparently converted to "False", which is True, and Ansible deletes your webserver.

See reproducing test case here: https://github.com/wu-lee/test-playbooks/tree/moustached-boolean-parameters-stringified

Tested with

```
ansible-playbook 1.4 (devel f4b3defcbf) last updated 2013/09/16 10:55:26 (GMT +100)
```

**Comment by mpdehaan** [comment]
In ansible you say:

```
when: foo
```

you do not say 

```
when: "{{ foo }}"
```

**Comment by wu-lee** [comment]
Thank you, I do know that. In my example, I do not say

```
when: "{{ foo }}"
```

anywhere, except perhaps indirectly by defining the foo variable elsewhere like this:

```
foo: "{{ bar }}"
```

Surely you cannot be suggesting I make the following change?

```
--- a/roles/consumer/meta/main.yml
+++ b/roles/consumer/meta/main.yml
@@ -2,8 +2,8 @@
 dependencies:
   - role: dep
     dep:
-      falsyM: "{{consumer.falsy}}"
-      truthyM: "{{consumer.truthy}}"
+      falsyM: consumer.falsy
+      truthyM: consumer.truthy
```

This would be no more sensible than my original case.  Trying it, instead of:

```
"This is executed, but dep.falsyM is False!"
```

We now get the literal variable name, which of course is not a string and not false value:

```
"This is executed, but dep.falsyM is consumer.falsy!"
```

See the updated github repository example, specifically: https://github.com/wu-lee/test-playbooks/commit/60e59b8f06af4c8fd9fb8bde910015cb3d4fd7ca

Hopefully you can see what I am trying to do in my example and if I am mistaken and Ansible supports assigning booleans in a consistently workable way, point me to an example of how to do it correctly.  I believe this is at the very least an omission in the documentation of variable semantics.
