### ISSUE TITLE
Broken link at How Can I Help online doc

### ISSUE THREAD

**Issue by jerryrelmore** [ansible/ansible#41947]
##### SUMMARY

Link to Ansible development process page [https://docs.ansible.com/ansible/latest/community/development_process.rst] from page section [https://docs.ansible.com/ansible/latest/community/how_can_I_help.html#review-and-submit-pull-requests] is incorrect. The correct link is [https://docs.ansible.com/ansible/latest/community/development_process.html].
##### ISSUE TYPE
 - Documentation Report

##### ISSUE TYPE
 - Documentation Report

##### ANSIBLE VERSION

```
2.5
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by jerryrelmore** [comment]
Subsumed under issue #41949.

**Comment by Akasurde** [comment]
resolved_by_pr #41949
