### ISSUE TITLE
include_tasks compatibility silently broken

### ISSUE THREAD

**Issue by mscherer** [ansible/ansible#41984]
##### SUMMARY
include_tasks compatibility silently broken

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include_tasks

##### ANSIBLE VERSION
HEAD

##### STEPS TO REPRODUCE
So using those file:

foo.yml
```
---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - include_tasks: bar.yml bar=2
```

bar.yml 
```
---
- debug:
    var: bar
```

On 2.6 and before, it work. On version HEAD since https://github.com/ansible/ansible/commit/da4ff18406bb9e052a7e81796aed11e2dea1bfc9 it fail

##### EXPECTED RESULTS

```
$ ansible-playbook foo.yml
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost
does not match 'all'


PLAY [127.0.0.1] ****************************************************************************************

TASK [Gathering Facts] **********************************************************************************
ok: [127.0.0.1]

TASK [include_tasks] ************************************************************************************
included: /tmp/ttt/bar.yml for 127.0.0.1

TASK [debug] ********************************************************************************************
ok: [127.0.0.1] => {
    "bar": "2"
}

PLAY RECAP **********************************************************************************************
127.0.0.1                  : ok=3    changed=0    unreachable=0    failed=0   
```

##### ACTUAL RESULTS
```
$ ansible-playbook foo.yml

ERROR! Invalid options for include_tasks: bar

The error appears to have been in '/tmp/ttt/foo.yml': line 5, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
  - include_tasks: bar.yml bar=2
    ^ here
```

This was a perfectly valid syntax for include, and a syntax that got carried over for include_tasks. And so while that's not the "modern" way, this was working fine.

Now, that is again yet another breaking change, with a undocumented silent deprecation without warning or anything.

**Comment by mscherer** [comment]
So that's linked to https://github.com/ansible/ansible/pull/39236

People already opened 2 bugs on things broken by that change:
- https://github.com/ansible/ansible/issues/41540
- https://github.com/ansible/ansible/issues/38129

**Comment by sivel** [comment]
This was a conscious decision to make this change for the 2.7 release.  The `include_tasks` module is documented as being in `preview` status.

The documentation for `preview` status indicates:

> This module is a tech preview. This means it may be
> unstable, the parameters may change, or it may require libraries or
> web services that are themselves subject to incompatible changes.

We decided to make a change to the interface that improves usability long term.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by fransflippo** [comment]
It could be me, but I'm not clear on what the correct way of writing the reporter's now would be? I have a similar issue and the documentation is not helping me solve it.

I'm happy to ask on IRC, but it would probably be useful for many people for this to be documented permanently somewhere. 

@sivel can you show what OP's `foo.yml` should look like on >2.7 ? Thanks.

**Comment by fransflippo** [comment]
OK apparently this should be correct:
```
- hosts: 127.0.0.1
  connection: local
  tasks:
  - include_tasks: bar.yml 
    vars:
      bar: 2
```

**Comment by fransflippo** [comment]
Porting guide: https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.7.html
