### ISSUE TITLE
Undefined variables: error message omits name of 'dict object'

### ISSUE THREAD

**Issue by wu-lee** [ansible/ansible#4209]
Hi,

I've noticed that when running with 'error_on_undefined_vars = True', the error messages emitted when an undefined variable is discovered don't tell you on what object the variable was set:  

```
One or more undefined variables: 'dict object' has no attribute 'state' 
```

Please could some disambiguation be added?  Ideally the variable's full path would be shown. The above message is too vague to be helpful when there is more than one instance of an attribute called 'state' in the task triggering the error.  

The most simple example of this would be:

```
- debug: msg="{{mysqldb}}"
```

When:

```
mysqldb:
    name: foo
    state: absent
    users:
        - name: joe:
          state: absent
```

This is just a trivial example. When any of host/group vars, vars files, roles and the like are involved, it gets increasingly hard to track down what is not being set.

Tested on:

```
ansible-playbook 1.4 (devel 0252aac226) last updated 2013/09/23 11:10:03 (GMT +100)
```

Thanks.

**Comment by mpdehaan** [comment]
The variable detection message is not under our control here.

However there is already a feature request/ticket to indicate the YAML line when problems happen, so this can be covered by that feature request/ticket

**Comment by wu-lee** [comment]
That wouldn't actually help in cases like my example, would it?

Anyway, I'll look and see if I can add this point to that ticket.

**Comment by mpdehaan** [comment]
Kind of saying I can't help you here.

**Comment by mahemoff** [comment]
I see this kind of error a lot and it's difficult to track down. Anything that could be done to help diagnosing it would be useful though I appreciate it's not directly handled by Ansible.
