### ISSUE TITLE
password lookup not evaluated in host_vars file

### ISSUE THREAD

**Issue by jabclab** [ansible/ansible#4211]
I'm attempting to use `lookup` in order to generate random passwords as part of files in a `hosts_vars` directory. Currently I have:

``` yaml

---
name: client01
server:
  http:
    auth:
      password: "{{ lookup('password', 'credentials/' + $inventory_hostname + '/password length=10') }}"
```

Then within a task I make use of these `hostvars` like:

``` yaml
- name: Add known clients
  shell: ./add_clients.sh
          -u "{{ users.admin.username }}:{{ users.admin.password }}"
          {% for client in groups['clients'] %}
            -c "{{ hostvars[client].name }}:{{ hostvars[client].server.http.auth.password }}"
          {% endfor %}
         chdir=/tmp/
```

My directory structure looks like:

```
.
|- development
  |- inventory
  |- host_vars
    |- client01 # <-- hosts_vars file
  |- group_vars
    |- clients
|- roles
  |- xxx
    |- tasks
      |- main.yml # <-- where the task is
```

If I obtain verbose output from Ansible I see that the `lookup` hasn't been evaluated, i.e. the `server.http.auth.password` attribute has been obtained but it contains `"{{lookup('password'), ..."`.

This can be replicated by simply using:

``` yaml
- name: test password generation
  debug: msg="{{ hostvars['client01'].server.http.auth.password }}"

# TASK: [test password generation] *******************************************************************
#ok: [client01] => {"item": "", "msg": "{{lookup('password', 'credentials/' + client01 + '/password length=10')}}"}
```

I've also tried using `lookup('env', 'XXX')` and this also doesn't work.

I'm using:
- Ansible **1.3.1**
- Python **2.7.5**
- OS X **10.8.2**

Thanks :-)

**Comment by mpdehaan** [comment]
So you're using lookup plugins wrong:

```
  password: "{{ lookup('password', 'credentials/' + $inventory_hostname + '/password length=10') }}"
```

Should be

```
  password: "{{ lookup('password', 'credentials/' + inventory_hostname + '/password length=10') }}"
```

There is no need to use legacy templating instead lookup plugins.

**Comment by mpdehaan** [comment]
Stop by the mailing list if you have further questions.

Thanks!

**Comment by jabclab** [comment]
Thanks for the response :-)

I've tried using:

```
password: "{{ lookup('password', 'credentials/' + inventory_hostname + '/password length=10') }}"
```

And I'm now seeing the following in my verbose output:

```
# TASK: [test password generation] **********************************************
# ok: [vagrant.xxx] => {"item": "", "msg": "{{lookup('password', 'credentials/' + inventory_hostname + '/password length=10')}}"}
```

This appears to be the same apart form the fact that `inventory_hostname` hasn't been resolved this time.

**Comment by mpdehaan** [comment]
please stop by the list :)

**Comment by jabclab** [comment]
Will do, thanks :-)
