### ISSUE TITLE
Route53: NoAuthHandlerFound: No handler was ready to authenticate.

### ISSUE THREAD

**Issue by devoncrouse** [ansible/ansible#4212]
I generally get this error when I've forgotten to set my AWS environment variables, but in this case I have, and other EC2 modules in the same play succeed. This is our first attempt to use the Route53 module, so I'm not ruling out something wrong on our end...

Both set correctly:
AWS_SECRET_ACCESS_KEY
AWS_ACCESS_KEY_ID

The full error:
fatal: [10.248.47.140] => failed to parse: Traceback (most recent call last):
  File "/home/ec2-user/.ansible/tmp/ansible-1379958186.04-93384843625847/route53", line 1189, in <module>
    main()
  File "/home/ec2-user/.ansible/tmp/ansible-1379958186.04-93384843625847/route53", line 189, in main
    conn = boto.route53.connection.Route53Connection(aws_access_key, aws_secret_key)
  File "/usr/lib/python2.6/site-packages/boto/route53/connection.py", line 68, in **init**
    validate_certs=validate_certs)
  File "/usr/lib/python2.6/site-packages/boto/connection.py", line 552, in **init**
    host, config, self.provider, self._required_auth_capability())
  File "/usr/lib/python2.6/site-packages/boto/auth.py", line 670, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV3Handler'] Check your credentials

**Comment by jimi-c** [comment]
That almost seems like an API endpoint issue, and not necessarily a problem in the code or your configuration. Are you able to recreate it consistently or is it transient?

**Comment by devoncrouse** [comment]
It's consistent; I still have yet to get it working. Tried pulling latest from the devel branch as well. Any thoughts on what else I might try to further troubleshoot?

**Comment by jimi-c** [comment]
What version of boto and ansible are you using?

**Comment by jimi-c** [comment]
Any follow-up on this?

**Comment by devoncrouse** [comment]
It's actually on my plate to revisit today or tomorrow; sorry for the delay.

**Comment by jimi-c** [comment]
No problem. I'm pretty confident this is a configuration issue though, that error message is pretty specific and like you said it's almost always related to AWS credentials not being configured properly.

**Comment by devoncrouse** [comment]
Pulling/installing latest from the Ansible devel branch, and upgrading python-boto from 2.9.5 to 2.13.3 didn't fix the issue for me.

**Comment by devoncrouse** [comment]
Upgrading python-botocore from 0.9.2-1.0 to 0.17.0-1.2 made things worse, and now I get the following on any attempt to use the ec2.py inventory.

ERROR: failed to parse: Looks like AWS is down again:
EC2ResponseError: 401 Unauthorized
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>e1825833-8826-4acc-a2ab-c603cd84858d</RequestID></Response>

_EDIT:_ Subsequently updating our ec2.py/ec2.ini from devel fixed the botocore issue, however Route53 still returns boto.exception.NoAuthHandlerFound: No handler was ready to authenticate.

**Comment by devoncrouse** [comment]
This was a misunderstanding on my part. The Route53 commands were actually being executed from the target EC2 instances instead of the machine ansible was called from, and their environment wasn't set up. Closing this; sorry for the trouble.
