### ISSUE TITLE
Tilde expansion with fetch module doesn't work on RHEL 5 w/ Ansible r1.3.1

### ISSUE THREAD

**Issue by faldridge** [ansible/ansible#4215]
The following task:

```
- name: fetch the backup to the local machine
  fetch: src=~{{ ansible_ssh_user }}/dump.sql dest=~/dump.sql flat=yes
```

Yields the following error on RHEL 5 with Ansible release 1.3.1:

```
ok: [<IP address>] => {"changed": false, "file": "~custadm/dump.sql", "msg": "the remote file does not exist, not transferring, ignored"}
```

From the error message and having confirmed that the file does exist in the custadm user's home directory on the server, it would appear that the fetch module is failing to do tilde expansion on the remote server.

**Comment by jimi-c** [comment]
Have you tested this on other systems, or are you just reporting it for the above?

**Comment by faldridge** [comment]
Just reporting for the above.

**Comment by jimi-c** [comment]
Here's a patch that may fix the issue for you, if you'd like to give it a try:

<pre>
diff --git a/lib/ansible/runner/action_plugins/fetch.py b/lib/ansible/runner/action_plugins/fetch.py
index 65b0aeb..28e06f8 100644
--- a/lib/ansible/runner/action_plugins/fetch.py
+++ b/lib/ansible/runner/action_plugins/fetch.py
@@ -56,6 +56,8 @@ class ActionModule(object):
             results = dict(failed=True, msg="src and dest are required")
             return ReturnData(conn=conn, result=results)
 
+        source = os.path.expanduser(source)
+
         if flat:
             if dest.endswith("/"):
                 # if the path ends with "/", we'll use the source filename as the
@@ -68,7 +70,8 @@ class ActionModule(object):
         else:
             # files are saved in dest dir, with a subdir for each host, then the filename
             dest = "%s/%s/%s" % (utils.path_dwim(self.runner.basedir, dest), conn.host, source)
-        dest   = dest.replace("//","/")
+
+        dest = os.path.expanduser(dest.replace("//","/"))
 
         # calculate md5 sum for the remote file
         remote_md5 = self.runner._remote_md5(conn, tmp, source)
</pre>

**Comment by faldridge** [comment]
Ran the code with a "GOT HERE" just to make sure the new code was invoked, and I experienced no change.  :(

**Comment by faldridge** [comment]
Thanks for that lightning-fast reply in any case, though!

**Comment by mpdehaan** [comment]
@jimi-c -- was reported this with "src" not "dest" ... might be it if I'm not misreading

**Comment by jimi-c** [comment]
@mpdehaan yes missed that, though it looks like it'd be an issue for both.

**Comment by jimi-c** [comment]
Updated the patch above with the source expanded as well.

**Comment by jimi-c** [comment]
Merged in the above patch, so let us know if you find any other issues with this. Thanks!
