### ISSUE TITLE
accelerate mode fails on gather_facts when sudo: True on play

### ISSUE THREAD

**Issue by bcoca** [ansible/ansible#4217]
simple test:

```
   - hosts: qa
     accelerate: True
     sudo: True
     tasks:
        - debug: msg="{{ansible_hostname}}"
```

this works if I remove sudo:True, otherwise it fails with:

```
fatail [hostname]   => failed to put the file in the requested location
```

and I get this from the target system:

```
hostname:   Sep 23 17:53:28 : loginuser: 3  incorrect password attempts ; TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/cp /home/loginuser/.ansible/tmp/ansible.KrnBs_ /home/loginuser/.ansible/tmp/ansible-1379973208.35-153146373981338/setup
```

ansible 1.4 (devel 080f35f63a) last updated 2013/09/23 15:46:20 (GMT -400)
on ubuntu 12 and 13

**Comment by jimi-c** [comment]
It looks like you're using sudo with a password? If so, accelerated mode does not yet support this (and may not be able to, due to the lack of a TTY, still exploring that). 

Does it work if you use 'NOPASSWD' for the sudoers line of the user you're connecting with?

**Comment by bcoca** [comment]
correct, I use passwords for sudo, if it is not supported I cannot use. I'll disable the accelerate mode then.

thanks
