### ISSUE TITLE
make it possible to assign variables that are the result of template calls

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#422]
ex:

vars:
  asdf: bar
  bar: foo/$asdf/123
  baz: something/$bar

ETC

This would require lots of templating calls using successive results of the template dictionary.

Possibly reconsider allowing Jinja usage to access python functions.

**Comment by phred** [comment]
Seems like allowing Jinja in the playbooks could lead to really messy playbooks.  Maybe I'm missing something?

I think it's best to make the simple case work like people expect for now.

**Comment by mpdehaan** [comment]
people would be expected to know what was good for them, which I can trust them to do.

**Comment by mpdehaan** [comment]
this is now done
