### ISSUE TITLE
missing role name in name of included task

### ISSUE THREAD

**Issue by jeromew** [ansible/ansible#4223]
Recently ansible output has started to prepend the role name in front of the task name.
- r|name of task

the role name is missing in the output for included tasks

roles/r/tasks/main.yml
- include: other.yml

all tasks names in other.yml are not prepended with r|

**Comment by jctanner** [comment]
jeromew, thank you for the bug report.

it appears that this issue has been resolved in the devel branch:

<pre>
jtanner@u1304:~/issues/4223-missing-role-name$ ansible-playbook -i hosts site.yml 
PLAY [localhost] ************************************************************** 
GATHERING FACTS *************************************************************** 
ok: [localhost]
TASK: [r | other.yml] ********************************************************* 
ok: [localhost] => {"item": "", "msg": "I am in r's included other.yml"}
TASK: [r | r-main.yml] ******************************************************** 
ok: [localhost] => {"item": "", "msg": "I am in r's main.yml"}
PLAY RECAP ******************************************************************** 
localhost                  : ok=3    changed=0    unreachable=0    failed=0 
</pre>
