### ISSUE TITLE
no-pty option in ssh breaks ansible usage

### ISSUE THREAD

**Issue by nextus** [ansible/ansible#4227]
Hello. For some particularly purposes I'm using restricted user for getting access to the servers by ssh. This user has «no-pty» option in ssh authorized key and when I run task through ansible without «sudo: yes» option it runs great. But sudoable commands is crashed with this traceback:

```
GATHERING FACTS ***************************************************************
fatal: [alma.relax.ru] => Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 364, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 443, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 597, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/python2.6/site-packages/ansible/runner/action_plugins/normal.py", line 54, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 333, in _execute_module
    res = self._low_level_exec_command(conn, cmd, tmp, sudoable=True)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 637, in _low_level_exec_command
    rc, stdin, stdout, stderr = conn.exec_command(cmd, tmp, sudo_user, sudoable=sudoable, executable=executable)
  File "/usr/lib/python2.6/site-packages/ansible/runner/connection_plugins/paramiko_ssh.py", line 203, in exec_command
    height=int(os.getenv('LINES', 0)))
  File "/usr/lib/python2.6/site-packages/paramiko/channel.py", line 158, in get_pty
    self._wait_for_event()
  File "/usr/lib/python2.6/site-packages/paramiko/channel.py", line 1084, in _wait_for_event
    raise e
SSHException: Channel closed.
```

I've scoured ansible source code and found paramiko function get_pty() call in the paramiko_ssh.py file with shady comment «sudo _usually_ requires a PTY» and without any checks if that is really necessary. I have disabled following option in my sudoers: `#Defaults    requiretty` and I really don't need that.

   I've just comment out this function call and, in the first glance, all starts work seamless. After that, I read discussion in #1801 and it shed some light about problem. I've been using fabric with option `sudo.pty = False` in my configuration on CentOS and FreeBSD for two years without any problems. I think some additional option `pty: no` following with `sudo: yes` would be great. 

   I don't familiar with ansible internal architecture so I haven't written a patch by myself yet.

**Comment by jimi-c** [comment]
If such an option were added, it should be in the ansible.cfg section for ssh/paramiko and not a playbook option.

**Comment by monitorjbl** [comment]
I added something similar to the duplicate issue, but I thought I'd add it here too since it's been closed:

It would be nice if Ansible could catch when a host is not able to support an interactive/non-interactive shell and report more meaningful errors to help out users. Paramiko doesn't throw an exception if the shell was killed, so the user doesn't have much to go on other than that the command Ansible tried to run didn't work. Maybe just see if stdout and stderr are blank and have the error message state that the current configuration requires that the host support interactive/non-interactive shells?

**Comment by mpdehaan** [comment]
closing per the above.

I'm not entirely sure a check on seeing if you had no output indicates that kind of failure, FWIW.
