### ISSUE TITLE
Remove hosts with failed tasks from run list.

### ISSUE THREAD

**Issue by bradobro** [ansible/ansible#423]
Looks to me like devel branch keeps running tasks on hosts that have had a task return json containing: {'failed':true...

I'm willing to help isolate.

**Comment by mpdehaan** [comment]
sure, that would be great.  thanks for the heads up.

**Comment by bradobro** [comment]
can you give me an idea where the test for failure goes?

--Brad Olson (from phone)
On May 29, 2012 4:13 PM, "Michael DeHaan" <
reply@reply.github.com>
wrote:

**Comment by mpdehaan** [comment]
in practice these are unlikely to regress enough to suffer through a test for something so specific, so I'd just figure out why it was broke using a real life run (starting a service that doesn't exist is easy enough) and fix it, versus worrying about the unit test.

**Comment by bradobro** [comment]
Ok assign to me

--Brad Olson (from phone)
On May 29, 2012 4:20 PM, "Michael DeHaan" <
reply@reply.github.com>
wrote:

**Comment by mpdehaan** [comment]
done!

**Comment by bradobro** [comment]
Minor logic fix.

First time contributing via an issue. Let me know if you want something special in commit messages, etc.

**Comment by mpdehaan** [comment]
Basically I think all you need to do is mention the ticket # in the PR and it will link them up and auto close things.  Commit messages really don't matter, just explain the why of the commit.

**Comment by bradobro** [comment]
ok, did that, we'll see how it works

**Comment by mpdehaan** [comment]
hmm, didn't auto close but it showed a record of it, which is good enough for me.

Thanks!

**Comment by bradobro** [comment]
You're welcome. Thanks for all your work.
