### ISSUE TITLE
test-module fails with shell module example

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#4233]
jtanner@u1304:~/ansible$ ./hacking/test-module -m library/commands/shell -a "echo hi"
- module boilerplate substitution not requested in module, line numbers will be unaltered
  ***********************************
  RAW OUTPUT

library/commands/shell: 5: library/commands/shell: DOCUMENTATION: not found
library/commands/shell: 47: library/commands/shell: EXAMPLES: not found

---

PARSED OUTPUT
{
    "failed": true, 
    "msg": "", 
    "parsed": false
}

**Comment by mpdehaan** [comment]
If specifying "shell" it should add "#USE_SHELL" on the end of the command.  I suspect this might be cause the code to do this assumed the old "library/shell"

**Comment by mpdehaan** [comment]
As this is a low level module testing tool I don't believe emulating too much ansible main logic would be desired here, so I am going to close this one.
