### ISSUE TITLE
Docs should include an explicit list of available connection types

### ISSUE THREAD

**Issue by ajdecon** [ansible/ansible#4235]
Connection types are not very discoverable. :( I just learned about the "chroot" connection type, which will be extremely useful in building reproducible bare-metal deployment images; but I had to learn about it through the survey tweeted by @mpdehaan because it isn't well called-out in the docs. 

(Doing a search of ansibleworks.com, chroot seems to be mentioned only in the middle of a paragraph in Getting Started, the AWS page, and in part of an example in the FAQ.)

The docs should have an explicit list of connection types with short explanations and mentions of limits. (For example: chroot must run as root.) This should probably be a top-level docs page since I don't see another page where it would fit well.

This is especially important given the increasing number of connection types (local, ssh, chroot, paramiko, accelerated, and pending lxc and jail), all of which are very useful in their specific contexts.

**Comment by mpdehaan** [comment]
Strongly agree!  We should totally have examples.

Lester had an example of using chroot to build an AWS image somewhere, which was a neat trick.

**Comment by mpdehaan** [comment]
This should be better referenced now but would welcome a guide section on using the chroot/jail/lxc other mods.
