### ISSUE TITLE
tags exclusion from command line

### ISSUE THREAD

**Issue by broferek** [ansible/ansible#4237]
After discussion on IRC, Benno suggested I opened a feature about this.

It would be good to be able to exclude a tagged task from the command line. Say you want to run a long playbook with many tagged tasks except one. For the moment, you need to specify all the tags you want to run, it would be better to have an command line option like --t 'all:!foo' or even simplier -t '!foo'

Thanks

**Comment by mpdehaan** [comment]
This is something that we've talked about before and I'm open to this.

Tagging this as a feature request as there are some other things in the pipe so it may be a while before we get to it.

If someone wants to take a crack at it, please go ahead, but --list-tags in /usr/bin/ansible-playbook should (A) also take this into effect, and (B) be made to share code with the main playbook system so it is no longer duplicated.

**Comment by JensRantil** [comment]
I just noticed that there is a `--skip-tags` parameter to `ansible-playbook`. Isn't that doing this? Have I missunderstood something?

**Comment by resmo** [comment]
looks also like --skip-tags to me. 

However it might look more clear if there is only one option for `run tagged tasks` and implemented as @broferek suggested.

.o(did not test but what happens if you mix --skip-tags ans --tags? having same tag in it?)

**Comment by mpdehaan** [comment]
Yep, this is --skip-tags so this can be closed.
