### ISSUE TITLE
VMware: export an ovf file from a Virtual Machine on vSphere vCenter

### ISSUE THREAD

**Issue by judyQD** [ansible/ansible#42397]
##### SUMMARY

use ansible to generate the ovf & vmdk file from a Virtual Machine on vSphere vCenter
##### ISSUE TYPE
 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.5.0
```

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

ansible has some kind of module to generate ovf based on one specific VM on vCenter.
##### ACTUAL RESULTS

```

```

**Comment by tonyreveal** [comment]
I would really like to see import / export OVF functionality implemented.  Every quarter we
 develop VM templates by using a kickstart or answer file in conjunction with Ansible roles in lower environments and put those VM templates through testing processes.  When the template is ready we manually export the template to an OVF that has to be copied and imported into another VMware environment.  We typically encounter delays in getting the templates "migrated".  Troubles finding an owner, someone with available time to perform the action, and even problems finding someone with the necessary privileges in VMware.

With support for import / export functionality we could automate this process.  Export the template to an OVF which we would check-in to Artifactory.  Then, through a sign-off / approval process the template is copied from Artifactory and promoted / imported to a higher environment.  Dev -> Test -> Stage -> Production

**Comment by bhairav13** [comment]
+1.  It's uncanny, but I happen to have the exact same need as @tonyreveal :).  It would be great to have this support.

**Comment by maxrainer** [comment]
+1 exact same issue here...

**Comment by elliott2019** [comment]
+1

**Comment by Tomorrow9** [comment]
If no one is working on this, I can try to take care of this. Thanks.

**Comment by Akasurde** [comment]
@judyQD Could you please take a look at above PR and let us know if it works for you ? Thanks.
