### ISSUE TITLE
Run all actions in task

### ISSUE THREAD

**Issue by bradobro** [ansible/ansible#424]
Not sure about this. I'm assuming tasks can have multiple template actions governed by a single only_if, and state should be checked for each action.

Looks like the task is skipped if the first action is ok.

**Comment by mpdehaan** [comment]
only_if is per task, because tasks is a list of tasks and there is no other place to put it.

**Comment by bradobro** [comment]
Okay, but help my ignorance: can tasks have multiple actions?

**Comment by mpdehaan** [comment]
Tasks are a list of … tasks, the task action is the what when the task runs, the name is just a human readable label.

**Comment by bradobro** [comment]
Ok. I see that now as I dig deeper into the code and consider the YAML. My bad.
