### ISSUE TITLE
mysql_user module failing on RDS

### ISSUE THREAD

**Issue by nicolas-g** [ansible/ansible#4241]
I'm currently getting the bellow error when running the example.yml to create a user that already exist : 

```
ansible --version
ansible 1.4 (devel 0252aac226) last updated 2013/09/23 10:19:38 (GMT +000)

CentOS 5
Linux 2.6.34.7-56.40.amzn1.x86_64 #1 SMP Fri Oct 22 18:48:49 UTC 2010 x86_64 x86_64 x86_64 GNU/Linux

boto version: 2.13.3
```
# example.yml

```

---
- hosts: localhost  
  connection: local 
  user: root
  gather_facts: false 

  vars:
     DB_DNS : xyz.cf6uoyzbegkp.us-east-1.rds.amazonaws.com
     DB_USER : "user"
     DB_USER_PASSWORD : "password"

  tasks:

  - name: set DB user for remote access
    mysql_user: login_user={{ DB_USER }} login_password={{ DB_USER_PASSWORD }} name={{ DB_USER }} password={{ DB_USER_PASSWORD }} host=% priv=*.*:ALL state=present login_host={{ DB_DNS }}
```
# Error

```
ansible-playbook example.yml -vvvv

PLAY [localhost] **************************************************************

TASK: [set DB user for remote access] ********************************
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1380115091.34-232519956907480 && chmod a+rx $HOME/.ansible/tmp/ansible-1380115091.34-232519956907480 && echo $HOME/.ansible/tmp/ansible-1380115091.34-232519956907480']
<localhost> REMOTE_MODULE mysql_user login_user=user login_password=password name=user password=password host=% priv=*.*:ALL state=present login_host=xyz.cf6uoyzbegkp.us-east-1.rds.amazonaws.com
<localhost> PUT /tmp/tmpRYB5NX TO /home/nicolasg/.ansible/tmp/ansible-1380115091.34-232519956907480/mysql_user
<localhost> EXEC ['/bin/sh', '-c', '/usr/bin/python /home/nicolasg/.ansible/tmp/ansible-1380115091.34-232519956907480/mysql_user; rm -rf /home/nicolasg/.ansible/tmp/ansible-1380115091.34-232519956907480/ >/dev/null 2>&1']
failed: [localhost] => {"failed": true}
msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/nicolasg/example.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

The bellow commands works and confirms the credentials are correct : 

```
mysql -h xyz.cf6uoyzbegkp.us-east-1.rds.amazonaws.com -u user --ppassword
```

**Comment by jimi-c** [comment]
And you're running that mysql command from the same host as the ansible playbook?

**Comment by nicolas-g** [comment]
yes

**Comment by jctanner** [comment]
@nicolas-g I ran some tests against mysqld on rhel5 and mostly fought with creating the right grants to allow my user to access the server from the public IP. However, when the grants were wrong, I saw the same error you posted in your initial description. I would say that only a few things could possibly be wrong:

Invalid IP/hostname
Invalid credentials
Insufficient grants 
Invalid variable substitution for the mysql credentials in your play

In /var/log/messages on your client machine, check for ansible log entries related to the connection:

<pre>
Oct 15 23:13:42 localhost ansible-mysql_user: Invoked with login_port=3306 name=root login_user=root login_host=el5.lab.net append_privs=False state=present login_unix_socket=None host=% user=root login_password=NOT_LOGGING_PASSWORD check_implicit_admin=False password=NOT_LOGGING_PASSWORD priv=*.*:ALL 
</pre>

If the right user is there, we can probably move on to checking grants. If not, then something might be wrong with variable substitution.

When  this is returned from the module ...

<pre>
unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
</pre>

The module has made a connection to the database server, but the credentials were rejected either for being invalid or for not having the right grants OR the connection failed (takes a while to timeout). I'm not sure if you can do this in RDS, but with mysqld, query logging can be enabled to further debug:

http://dev.mysql.com/doc/refman/5.1/en/query-log.html

Good connection:

<pre>
131015 23:29:19       2 Connect     root@u1304.lab.net on 
</pre>

Bad connection:

<pre>
131015 23:30:02       4 Connect     Access denied for user 'root000'@'u1304.lab.net' (using password: YES)
</pre>

With that being said, I'm going to equate your issue to a mysql configuration problem and not an ansible bug. If you can enable query logging on your RDS instance or even reproduce and log with a different mysqld, please do so and file a new bug.
