### ISSUE TITLE
Scaleway inventory plugin doesn't list hosts' adresses correctly

### ISSUE THREAD

**Issue by mhalano** [ansible/ansible#42431]
##### SUMMARY

I was unable to execute an ad-hoc ping because the inventory plugin returns the ID of instances and not their IP addresses.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

scaleway inventory plugin

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /home/marcos/projs/scaleway/ansible.cfg
  configured module search path = [u'/home/marcos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

INVENTORY_ENABLED(/home/marcos/projs/scaleway/ansible.cfg) = ['scaleway', 'ini']

##### OS / ENVIRONMENT

I'm on a Ubuntu 18.04 LTS managing two Scaleway cloud instances with Ubuntu Xenial.

##### STEPS TO REPRODUCE

```yaml
ansible -i scaleway.yml -m "ping" all

```

##### EXPECTED RESULTS

```
XXX.XXX.XXX.XXX | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
YYY.YYY.YYY.YYY | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
```

##### ACTUAL RESULTS

```
cce89a0e-cadf-4823-82e8-7c9e0bf0b5d1 | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname cce89a0e-cadf-4823-82e8-7c9e0bf0b5d1: Name or service not known\r\n", 
    "unreachable": true
}
9d5c078a-6774-464e-b0e2-4a45545dd02f | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname 9d5c078a-6774-464e-b0e2-4a45545dd02f: Name or service not known\r\n", 
    "unreachable": true
}

```

**Comment by s-hertel** [comment]
Please fill this out with Ansible version and the expected and actual results. The title doesn't indicate what is happening or why the behavior wrong. needs_info

**Comment by s-hertel** [comment]
cc/ @sieben

Most inventory plugins use constructed features so the user can specify what to use as the ansible_host. Such as, with the aws_ec2 inventory plugin, the user can specify to use the private IP as the host to connect to:
```
plugin: aws_ec2
regions:
  - us-east-1
compose:
  # private_ip_address is a host variable that you can see with ansible-inventory -i file --list
  ansible_host: private_ip_address
```
scaleway could be updated to use it easily- in a nutshell, import Constructable, update InventoryModule to be `class InventoryModule(BaseInventoryPlugin, Constructable):`, add to the docs `extends_documentation_fragment: constructed`, and then call self._set_composite_vars, self._add_host_to_composed_groups, and self._add_host_to_keyed_groups where necessary.

**Comment by remyleone** [comment]
@mhalano Could this dynamic inventory help you: https://github.com/ansible/ansible/pull/41658?
@s-hertel I'm going to look into this. Do you think https://github.com/ansible/ansible/pull/41658 could be merged before I implement the compose feature?

**Comment by mhalano** [comment]
@sieben This pull request resolves my problem. I just mention a little bug on your code on pull request itself. Beside that this solution closes this bug.

**Comment by remyleone** [comment]
Thanks :) feel free to close when you see fit

**Comment by mhalano** [comment]
@sieben I will close this bug after 2.7 was released. That's ok for you?

**Comment by remyleone** [comment]
I think you could close it now. Why do you want to wait?

**Comment by mhalano** [comment]
Feature already implemented in latest devel version.
