### ISSUE TITLE
Incorrect output for unreachable host

### ISSUE THREAD

**Issue by darKoram** [ansible/ansible#4243]
This is a feature request to make the output for an incorrectly specified host ip more clear.  Detecting an ip that can't ping should be easy to catch.

I mis-typed the correct ip as 10.0.9.190 as 10.0.0.190 in group_vars/all

Output is
GATHERING FACTS **************************************************************\* 
<10.0.0.190> ESTABLISH CONNECTION FOR USER: root
<10.0.0.190> EXEC ['ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '10.0.0.190', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1380119711.17-139899932942352 && echo $HOME/.ansible/tmp/ansible-1380119711.17-139899932942352'"]
fatal: [Linux-Elasticsearch] => could not create temporary directory, SSH (mkdir -p $HOME/.ansible/tmp/ansible-1380119711.17-139899932942352 && echo $HOME/.ansible/tmp/ansible-1380119711.17-139899932942352) exited with result 255

From the output, i assumed that the connection was successful and it was directory creation that was the problem.

SUGGESTION:
Output should indicate weather or not the connection was successful.

This is an overloaded error message. I have receieved this sort of error for three distinct reasons.  The one above, plus

Once, it was fixed by setting SELINUX=disabled in
/etc/sysconfig/selinux

Another time it was fixed by adding ssh and sudo password prompts -K and -k
ansible-playbook  -u elasticsearch -K -k -i hosts site.yml -vvv

It's much harder to google-hunt-fix bugs when there are multiple reasons for the same error message.

thanks

**Comment by jimi-c** [comment]
The output message for this failure has been clarified in 1.3+, so I would recommend upgrading to the latest release. Thanks!

**Comment by darKoram** [comment]
Thanks for the speedy reply!

I am running 1.3
I just did a pull ( i guess from release branch cause it's been 2 months and it says i'm up to date.)

ansible --version
ansible 1.3 (devel d1effecb2e) last updated 2013/07/26 09:40:45 (GMT -500)

There is now a message about libselinux which handles some cases of the SELINUX setting mentioned above which is an improvement.  However, the bad ip issue still stands.

**Comment by jimi-c** [comment]
The messages you could see with 1.3.2 are as follows:

If ssh returns a 255 value (unknown error), you should see this:

<pre>
FAILED => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue
</pre>

If other non-zero return codes are returned, you should see this:

<pre>
Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: XXXXXXXXXXXXXXXXXXXXX, exited with result VALUE
</pre>

If you're not seeing one of those two messages, it may mean that you're not up to date and your repository may be pointing at an incorrect origin.

**Comment by jimi-c** [comment]
I did just notice the date 2013/07/26, that is quite old. We do commits daily, so you're two months out of date.

**Comment by darKoram** [comment]
Yes.  i had a stale redirect for the github url.  With 1.3.2 I get this.

Fantastic!

fatal: [Linux-Elasticsearch] => SSH encountered an unknown error. The
output was:
OpenSSH_5.9p1, OpenSSL 0.9.8x 10 May 2012
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket
"/Users/kbroughton/.ansible/cp/ansible-ssh-10.0.0.190-22-root" does not
exist
debug2: ssh_connect: needpriv 0
debug1: Connecting to 10.0.0.190 [10.0.0.190] port 22.
debug2: fd 3 setting O_NONBLOCK
debug1: connect to address 10.0.0.190 port 22: Operation timed out
ssh: connect to host 10.0.0.190 port 22: Operation timed out

Issue closed.

On Wed, Sep 25, 2013 at 12:00 PM, James Cammarata
notifications@github.comwrote:

> I did just notice the date 2013/07/26, that is quite old. We do commits
> daily, so you're two months out of date.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/4243#issuecomment-25105242
> .

## 

Kesten Broughton
512 701 4209
