### ISSUE TITLE
Cant Restore Mattermost ( Postgres ) Database With Ansible 

### ISSUE THREAD

**Issue by char543** [ansible/ansible#42498]
##### SUMMARY
Unable to restore Postgres database inside container using ansible. Ansible modules, shell commands and shell scripts via ansible can not restore db inside docker container. When executed manually from same backup it works. When commands have been run from ansible that were successful on any container, the container/s consistently restarts.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
root@ansible:~# ansible --version

ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

root@ansible:~# ansible-config dump --only-changed
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = skippy

##### OS / ENVIRONMENT
ubuntu 16.04

##### STEPS TO REPRODUCE
Backup and restore database using ansible on latest version of mattermost (v5 +)

As far as I can see, as long as the format is : Ansible > remote host > docker container > Postgres CLI
any commands that successfully execute inside the Postgres CLI cause the container to enter a restart loop rendering restores useless and uncheckable.

```yaml

```

##### EXPECTED RESULTS

Database restores, container starts, mattermost works, can log in etc

have tried:
pg_restore
psql < (-U, -h, -c etc...)
cat the db and pipe into container
docker_container ansible module with command option

command strings, various shell scripts, piping commands into docker exec etc

##### ACTUAL RESULTS

```
cant access .sock file
cant find global relation mapping file

commands or strings work to execute Postgres commands inside the psql CLI inside a docker container and from stdout (ansible) I can see things have worked as expected (no errors, drop roles or databases and recreate db with specified privileges) however, when this is the case (tasks run without failing or errors) it will consistently restart. It does not matter how the commands were executed (shell script, commands or modules) as far as I can see as long as it is Ansible > remote host > docker container > Postgres CLI it will restart after the commands have been executed. This all works fine when executed manually from the same backup on the remote host
```

Summary

Steps to reproduce

backup and restore database using ansible on latest version of mattermost (v5 +)

As far as I can see, as long as the format is : Ansible > remote host > docker container > Postgres CLI
any commands that successfully execute inside the Postgres CLI cause the container to enter a restart loop rendering restores useless and uncheckable.

Using latest version of mattermost (docker)
Ansible V 2.5.2

Expected behavior

Database restores, container starts, mattermost works, can log in etc

have tried:
pg_restore
psql < (-U, -h, -c etc...)
cat the db and pipe into container
docker_container ansible module with command option

command strings, various shell scripts, piping commands into docker exec etc

Observed behavior (that appears unintentional)

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
