### ISSUE TITLE
"No closing quotation" error when user does not exists

### ISSUE THREAD

**Issue by haarts** [ansible/ansible#425]
When using the 'file' module (possibly others) like so:

```
file path=/some/random/path state=directory owner=some_non_existing_user
```

The [json parser](https://github.com/ansible/ansible/blob/devel/lib/ansible/utils.py#L185) in the `utils.py` throws a `ValueError: No closing quotation` error.

The data the being parsed has an extra two lines (`print data`):

```
/bin/chown: invalid user: `some_non_existing_user'

group=root failed=True state=directory mode=0755 msg=chown failed path=/some/random/path user=root
```

I recon the chown error and the new line cause the error.

Stacktrace:

```
fatal: [127.0.0.1] => Traceback (most recent call last):
  File "/Users/xxx/bin/ansible/lib/ansible/runner/__init__.py", line 611, in _executor
    exec_rc = self._executor_internal(host)
  File "/Users/xxx/bin/ansible/lib/ansible/runner/__init__.py", line 655, in _executor_internal
    result = self._execute_normal_module(conn, tmp, module_name)
  File "/Users/xxx/bin/ansible/lib/ansible/runner/__init__.py", line 378, in _execute_normal_module
    exec_rc = self._execute_module(conn, tmp, module, self.module_args)
  File "/Users/xxx/bin/ansible/lib/ansible/runner/__init__.py", line 315, in _execute_module
    result1 = utils.parse_json(res)
  File "/Users/xxx/bin/ansible/lib/ansible/utils.py", line 186, in parse_json
    tokens = shlex.split(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
  ValueError: No closing quotation
```

Host system: Mac OSX Lion 10.7.4
Target system: Ubuntu 10.04 Server edition
Ansible version: branch 'devel', last commit c92ddad517d0f733a9ce96d4d0e7de0f99b7963d

**Comment by haarts** [comment]
The problem also occurs with the 'template' module when the target contains a parent directory which doesn't exist (in this case /etc/apache):

```
cp: cannot create regular file `/etc/apache2/sites-available/foobar': No such file or directory

md5sum=b9e0d24424bc6536ac8c8ba0a98fe173 changed=True
```

The output is from adding a `print data` on line 185 of utils.py.

**Comment by mpdehaan** [comment]
sounds like you have this bug tracked down, how about a patch?

**Comment by haarts** [comment]
I've never done Python before but here are my findings so far. 
The result of a call to `exit_kv` line 38 of the [library/file](https://github.com/ansible/ansible/blob/devel/library/file#L38) also prepends to stderr.

**Comment by haarts** [comment]
I don't get it. Somehow stderr gets prepended to stdout.

**Comment by mpdehaan** [comment]
strange.

the way we have to use the TTY with paramiko we cannot seperate stderr and stdout, therefore all modules should ONLY output JSON to stdout.

print_kv however, only outputs to stdout, so I don't think this is outputing anything to stderr.

I think it's more likely that the command dealing with the non_existing_user (chown) is not capturing stderr

That's enough for me to fix if you want to leave this one open.

Temporary workaround is to not chown to a non-existing user by having a previous usage of the user module to make sure that user is state=present

**Comment by mpdehaan** [comment]
I recently pushed a change to make the call to chown redirect stderr to /dev/null.  Should fix this.
