### ISSUE TITLE
PDF documentation

### ISSUE THREAD

**Issue by rfleschenberg** [ansible/ansible#4265]
It would be nice to have a pre-built PDF of the docs. Building them yourself with Sphinx is somewhat cumbersome.

**Comment by mpdehaan** [comment]
This is not a priority for us at this time as it's important for people to see what is new and available and we can share news this way.

I would suggest slurping down the website or using offline browser modes, but ansible-doc may be an even better solution.

**Comment by php-coder** [comment]
I agree, that is was a good idea to publish generated documentation in PDF format.

**Comment by cooniur** [comment]
PDF documentation is really a good idea, especially when you don't have internet connection, for example, on a commute train. Please make one!

**Comment by felipythondev** [comment]
It would be really nice, I would like to read about it on train going to work.

**Comment by kikicarbonell** [comment]
+1

**Comment by jeremypruitt** [comment]
+1

**Comment by mpasternak** [comment]
I'd gladly grab ANY form of offline docs. I've built myself, with Sphinx, only to find out, that search function still redirects to docs.ansible.com . PDFs would be great.  :+1:

**Comment by lqueryvg** [comment]
+1

**Comment by lqueryvg** [comment]
A very quick and dirty DIY solution is as follows (I'm on CentOS):
- `yum install pandoc pandoc-pdf`
- `git clone` ansible from github
- `cd ansible/docsite/rst`
- `for file in *.rst; do pandoc -f rst -o ${file%.rst}.pdf $file; done`

You now have lots of pdf files, one for each rst. You could read them offline like this, or concatenate them all into one pdf with `pdfunite *.pdf ansible_docsite.pdf`.

Of course, the ordering is a bit messed up (you could spend some time fixing this by specifying the exact order you want with the `pdfunite` command line), but it's good enough for me to be able to read on the train!

**Comment by mpasternak** [comment]
Hi,

I'm on Mac OS X. I found this wonderful application for offline docs, with great integration with system and my IDE (PyCharm). Yes, this sounds like spam. No, I'm no way affiliated or endorsed by authors. It's called "Dash".

**Comment by xenithorb** [comment]
https://github.com/bonndan/ansible-userguide-pdf

**Comment by pythononwheels** [comment]
I know that this is old but I looked for myself for a way to carry the docs around and found no pdf.
But I think this one is a really simple workaround: (You need python 3.x)

**Prereqs:**
1. get the ansible repo: `git clone https://github.com/ansible/ansible.git`
2. install sphinx:  `pip install sphinx`

**Build the HTML doc**
1. got to the ansible repo (locallay) and switch to the docsite dir.
   
   `cd ansible\docsite`
2. run the build-site.py script which generates the html into the htmlout dir.
   
   `python build-site.py`
3. change the name of the css file theme.css to theme.min.css in ansible\docsite\htmlout_static\css. 
4. change to the ansible\docsite\htmlout dir 
   `cd ansible\docsite\htmlout`

**Watch it locally**
1. run the embedded webserver from python 
    `python -m http.server 8000`
2. watch it in you browser: http://localhost:8000

Result: after a Minute or two you have the html locally and can use the embedded python webserver to view it in the browser just like online.

**Comment by xenithorb** [comment]
[ansible-doc-v2.0.1 - Unknown.pdf](https://github.com/ansible/ansible/files/339852/ansible-doc-v2.0.1.-.Unknown.pdf)

Last time I looked at the project I pasted, I actually got it working (date of that is in the doc I think). It probably still works with some futzing. The attached is the last one I generated for myself (for my kindle)

---

Odd tangent: I actually [printed the pages out and bound them together into a book for myself (never finished the cover)](https://imgur.com/a/z4JnZ) (_sigh_, I'm not good at step-by-steps, and I forgot to capture pics of the gluing and drying and trimming process) - I do strange things when I'm out of work :)

**Comment by rodolof** [comment]
Hi, I followed the instructions from pythononwheels and I am writing what it worked for me ( some corrections)

Prereqs:

```
get the ansible repo: git clone https://github.com/ansible/ansible.git
install sphinx: pip install sphinx  
```

in case we don't have pip, we should install it
 yum -y install python-pip.noarch   

Build the HTML doc

```
got to the ansible repo (locally) and switch to the docsite dir.

cd ansible/docsite

run the build-site.py script which generates the html into the htmlout dir.

python build-site.py

change the name of the css file theme.css to theme.min.css in ~/ansible/docsite/htmlout/_static/css

change to the ansible/docsite/htmlout dir
cd ansible/docsite/htmlout
```

Watch it locally

```
run the embedded webserver from python, in the following directory: /home/ansible/ansible/docsite/htmlout
```

python -mSimpleHTTPServer

Starts serving a site from the current directory on port 8000 with directory listing activated.

Accessible from http://127.0.0.1:8000

```
watch it in you browser: http://localhost:8000
```

Result: after a Minute or two you have the html locally and can use the embedded python webserver to view it in the browser just like online.

THank you very much, it really helps, to have the HTML documentation locally. Now I can work from my laptop, anywhere ( and with my virtual machines)
Kudos¡

**Comment by rjlohman** [comment]
+1 on the PDF version. I have a 1:15 train ride, and having access to an off-line module reference would be huge.

That said, I've tried building the pages, both HTML and PDF. I've completed each successfully, but there does not seem to be any documentation on the individual modules. Perhaps I've missed something?

**Comment by onurozgurozkan** [comment]
+1

**Comment by mpasternak** [comment]
Friendly reminder, https://kapeli.com/dash , I'm not affiliated with the author.

**Comment by mdawar** [comment]
Since Ansible's documentation is hosted on readthedocs.org you can go to the downloads page https://readthedocs.org/projects/ansible/downloads/ and download the docs in pdf, html or epub.
**Update**: download the **latest PDF** not the **stable PDF**.

**Comment by sensiblemedia** [comment]
https://readthedocs.org/projects/ansible/downloads/ pdf download is incomplete, its only seven pages in length and what is available is lacking in content.

**Comment by mdawar** [comment]
@sensiblemedia actually you seem to be downloading the wrong PDF file, the first one **stable PDF** is 7 pages long and has nothing useful, download the **latest PDF** and check it out, it has 388 pages which is the full documentation.

**Comment by sensiblemedia** [comment]
@mdawar Thanks buddy, that did the trick (changed my thumbs down to up on your previous post)

**Comment by hymie0** [comment]
Sorry to bring up an old thread, but the "latest" PDF/Epub do not include the module documentation.  That's what I'm personally looking for.

**Comment by ghost** [comment]
@mpdehaan clearly, for [numerous](https://github.com/ansible/ansible/issues/4265) people (myself included), the absence of PDF docs *is indeed a bug*. I'll unpack that for you.

Many projects that use ReadTheDocs have a PDF variant, so users come to expect this of other projects (such as Ansible) that also use ReadTheDocs.

It is additionally reasonable for users to want and expect such a variant, for the reasons given above (global searchability, offline convenience, etc).

When such a user looks for the PDF documentation, and cannot find it, the instinctive conclusion is *not* to say to oneself, "Ah, the Ansible developers must have deliberately chosen to inconvenience me and other people, by consciously declining the option to publish PDF versions of the documentation." It is to say to oneself, "Huh, the PDF documentation pipeline must be broken. I should be a good citizen and report this bug."

By not having PDF documentation, you waste these people's time *three times over*:

1. in searching for the PDF documentation in vain;
1. in attempting to file a bug report, only to discover several existing such bug reports that have been dismissed out of hand;
1. in having to figure out how to build (or to [download from a non-obvious ReadTheDocs link](https://github.com/ansible/ansible/issues/4265#issuecomment-313460298)) a PDF of the docs themselves, to work around the Ansible team's intransigence.

GNU projects handle the differing preferences of different readers very well, by offering docs in multiple formats upfront, including:

- HTML, one page per (sub)section;
- HTML, all on one page;
- PDF.

Ansible would benefit from taking that approach. It would satisfy those (like you) who seem to prefer one page per (sub)section, *and* it would satisfy those (like me, and other participants in this thread and the linked issues) who would prefer a single page or PDF solution, for easier offline reading and global searching.

Please reconsider your decision to close this issue as WONTFIX.

**Comment by ghost** [comment]
+1 on this.

Not only is  there no PDF, you can't even print out the pages of the Ansible Docs.

The pages have scroll windows which the print command doesn't seem to pick up on. You'll only get a single page of docs that should be multiple pages. E.g. https://docs.ansible.com/ansible/latest/modules/apt_module.html#apt-module

**Comment by ghost** [comment]
Posting this again here so it's easy to see: https://readthedocs.org/projects/ansible/downloads/

**Comment by rl4518** [comment]
The lack of a pdf version of the ansible (latest) release is yet another reason not to waste time with it. Honesty, what major project like this doesn't have every possible method of documentation distribution method available to it.

How can you be a champion of a system with such a draconian view, ignoring it's own user community

**Comment by Bercik1337** [comment]
Oh, so I'm not the only one who thinks lack of PDF docs it's not just weird, but really unprofessional.

**Comment by rodolfocasas** [comment]
Try this tool https://zealdocs.org/

I checked now and all modules documentation inside zeal were updated 15 days ago(15 March 2019). I know...it's not PDF, but it works offline and it is updated
