### ISSUE TITLE
Feature Request: Ability to define roles in a single file

### ISSUE THREAD

**Issue by darkone23** [ansible/ansible#4266]
Sometimes my roles are incredibly simple.  They are a single task, maybe a single handler, and some vars.  I find it hard to maintain the three individual files at around three lines each, and would rather have a simple 9 line main.yaml defining my role.

So instead of:

```
roles/role/tasks/main.yaml
roles/role/meta/main.yaml
```

I might define:

```
roles/role/main.yaml
```

containing:

``` yaml

tasks:
  - debug: msg="I'm a role!"
vars:
  foo: "bar"

```

**Comment by mpdehaan** [comment]
We are not going to do this because it causes a problem when you need to convert them to seperate bits later and does not allow roles to offer good pathing solutions.

This has been discussed on the lists a few times.
