### ISSUE TITLE
Tag 1.4 is not yet created but VERSION shows 1.4

### ISSUE THREAD

**Issue by sathishvc** [ansible/ansible#4271]
While reading documentation, found that `user` is renamed to `remote_user` in 1.4. But git tag 1.4 is not available here for download.

**Comment by srgvg** [comment]
1.4 is currently in development, where the remote_user was already implemented; as this is not a released version, there's no 1.4 tag.

**Comment by jimi-c** [comment]
Closing, not an issue. If you have any questions about this please ask on the mailing list. Thanks!
