### ISSUE TITLE
Local_action directory creation fails with multiple hosts

### ISSUE THREAD

**Issue by base10** [ansible/ansible#4276]
I have a playbook that runs a pre-task to create a directory on my local machine (Mac OS X 10.8.5, python 2.7.5, ansible devel branch as of 039d4c95d). The first iteration will create the directory, but the second iteration fails with a stack trace:

failed: [redacted2.example.com] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/nathan/.ansible/tmp/ansible-1380298478.27-260287155991478/file", line 1272, in <module>
    main()
  File "/Users/nathan/.ansible/tmp/ansible-1380298478.27-260287155991478/file", line 247, in main
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/tmp/mysql_slap_results/2013-09-27T12:14:38Z'

Full sample: https://gist.github.com/base10/6731096

My expectation is that the directory would be seen on the second iteration and bypassed.

**Comment by mpdehaan** [comment]
Is this possibly a race condition with this step happening on multiple hosts with the same directory name each time?

**Comment by bcoca** [comment]
This might be caused when  creating files with names based only on
timestamp (from play start?) and this would of course overlap if you do
more than 1 host on a target that shares storage (nfs or local). mktemp
adds randomness which helps with uniqness, but pid+hostname+timestamp would
ensure files don't overlap.

**Comment by base10** [comment]
Sorry for delay in response. So, I apologize for not being clearer, but what's failing is directory creation on the machine that's running the playbook (my laptop). This is a local action. It is entirely possible I have the action locally happening twice (we're calling ansible-playbook with -f 10) as a race condition.

I want to collect results files from the machines the tests are running on and I want to make sure I have a directory to put those test results files in to. I'm naming the files by ansible_hostname. I'm not otherwise worried about the files themselves overlapping and, in fact, see multiple test results files.

Anything else I can answer that might be helpful?

**Comment by bcoca** [comment]
i would have a pre-play that creates the dir (hosts: localhost) then
populate with the files by hostname (btw, I think fetch module does all
this automatically).

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by base10** [comment]
@bcoca So, I commented out my pre_task and just relied on the fetch module and, as you suggested, that works like a charm.

So, I'm fine closing this unless there's some benefit of looking into the stack trace further.

**Comment by mpdehaan** [comment]
Yep, you could inject a micro-play at any time and execute it only once.

I would agree this is closeable, so I am closing.

Glad it got solved!
