### ISSUE TITLE
get_url does not show mismatched sha256sum

### ISSUE THREAD

**Issue by jorgenschaefer** [ansible/ansible#4277]
Using `get_url` to fetch a file and checking using `sha256sum` just exhibited some odd behavior here.

Local download of the file:

```
# sha256sum logstash-1.2.1-flatjar.jar 
d0b8a56fb1aa71d54c2bab71709d900b359fdf8c6d7d6ff15578423a0d86ee23  logstash-1.2.1-flatjar.jar
```

tasks/main.yml:

```
- name: logstash|downloading
  get_url: url=https://download.elasticsearch.org/logstash/logstash/logstash-1.2.1-flatjar.jar
           sha256sum=﻿d0b8a56fb1aa71d54c2bab71709d900b359fdf8c6d7d6ff15578423a0d86ee23
           dest=/srv/logstash/logstash-1.2.1-flatjar.jar
           mode=0644 owner=logstash group=logstash
  notify:
    - logstash|restart logstash
```

Ansible gave me an error:

```
failed: [vagrant] => {"failed": true, "item": ""}
msg: The SHA-256 checksum for /srv/logstash/logstash-1.2.1-flatjar.jar did not match ﻿d0b8a56fb1aa71d54c2bab71709d900b359fdf8c6d7d6ff15578423a0d86ee23
```

I'm still not sure why that happened, but it would be at least useful to have the mismatched sha256sum in the error message.

**Comment by mpdehaan** [comment]
forcer updated the debug message and got

The SHA-256 checksum for /srv/logstash/logstash-1.2.1-flatjar.jar did not match ﻿d0b8a56fb1aa71d54c2bab71709d900b359fdf8c6d7d6ff15578423a0d86ee23; it was d0b8a56fb1aa71d54c2bab71709d900b359fdf8c6d7d6ff15578423a0d86ee23

**Comment by jorgenschaefer** [comment]
Ok, my actual problem is resolved: There was a zero-width non-breaking space in my tasks file (I have no idea how it got there), which would explain the mismatch. It _might_ be sensible to use `.strip()` on the hashes, but I'm not sure if that's a real issue.

Still, getting a message for the mismatched checksum would be good.

**Comment by jlund** [comment]
Now that the patch has been merged, this should be fixed. @jorgenschaefer, can you confirm that this works for you?

**Comment by jorgenschaefer** [comment]
Looks good to me. Thank you!
