### ISSUE TITLE
error:10.0.3.225 | FAILED | rc=0 >> MODULE FAILURE  

### ISSUE THREAD

**Issue by sridhar2787** [ansible/ansible#42855]
##### SUMMARY

I have created three containers in Ubuntu vm, one as a database and two for web servers. When I'm trying to use arguments, every time ended up with the following error "10.0.3.225 | FAILED | rc=0 >>
MODULE FAILURE"

examples:
```
ansible all -a "free -m" -i /etc/ansible/hosts
"10.0.3.225 | FAILED | rc=0 >>
MODULE FAILURE
ansible all -a "dpkg -l" -i /etc/ansible/hosts
"10.0.3.225 | FAILED | rc=0 >>
MODULE FAILURE
```
Ansible version - 2.3
ubuntu virtual machine

Debug output:
```
sudo ansible 10.0.3.225 -a "dpkg -l" -i /etc/ansible/hosts -vvvv
Using /etc/ansible/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<10.0.3.225> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<10.0.3.225> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.0.3.225 '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1531754536.58-6531342971028 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1531754536.58-6531342971028 )" )'
```

##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

``` 
ansible 2.0.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible


```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by sridhar2787** [comment]
and it looks like connectivity works fine 
sudo ansible all -m ping -i /etc/ansible/hosts
10.0.3.225 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
10.0.3.254 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
10.0.3.65 | SUCCESS => {
    "changed": false, 
    "ping": "pong"

**Comment by Akasurde** [comment]
Hi @sridhar2787 !

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
