### ISSUE TITLE
Ansible 2.4.X unavailable as RPM

### ISSUE THREAD

**Issue by zigarn** [ansible/ansible#42891]
##### SUMMARY

Latest ansible 2.4.X (2.4.5.0-1) was released on [2018-06-22](https://github.com/ansible/ansible/releases/tag/v2.4.5.0-1) and is [still supported](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#release-status), but the RPM is not available in https://releases.ansible.com/ansible/rpm/release/ except for fedora-28-x86_64.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.5
```

##### OS / ENVIRONMENT

RedHat/CentOS/Fedora

##### STEPS TO REPRODUCE

1. Go to https://releases.ansible.com/ansible/rpm/release/
1. Go in any subfolder
1. Look for a ansible 2.4.X RPM

##### EXPECTED RESULTS

Find RPM for (at least) latest 2.4.5 version.

##### ACTUAL RESULTS

Only available for `fedora-28-x86_64`

**Comment by aoyawale** [comment]
can't say for sure why but, its probably easier to maintain that version that is only available and perhaps it fixed a lot of issues.

**Comment by mattclay** [comment]
@zigarn I'm currently seeing Ansible 2.4.6 RPMs in all 5 repositories. However, it does look like we have an issue with pruning old RPMs from the repositories across releases, which I'm looking at fixing.

**Comment by zigarn** [comment]
@mattclay at the time I wrote this issue, 2.4.6 wasn't released yet and 2.4.5 (or any older 2.4.X) wasn't available (should have take a screenshot). So, for me it's solved now as I have 2.4.6.
Maybe I was looking at the wrong time during the release of 2.4.6 and old 2.4.X was pruned (except for fedora 28, which is still the case). But, from what I remember, old releases were never pruned before.

**Comment by mattclay** [comment]
I've disabled the automatic pruning on the preview and release repos -- leaving it only for the nightlies.
