### ISSUE TITLE
xmllint make error, typo

### ISSUE THREAD

**Issue by stemid** [ansible/ansible#43]
$ sudo make install
a2x -D docs/man/man1/ -d manpage -f manpage docs/man/man1/ansible.1.asciidoc
a2x: ERROR: xmllint --nonet --noout --valid /Users/nocturnal/Development/homebrew/ansible/docs/man/man1/ansible.1.xml returned non-zero exit status 4
make: **\* [docs/man/man1/ansible.1] Error 1
$ sudo xmllint --noent --noout --valid /Users/nocturnal/Development/homebrew/ansible/docs/man/man1/ansible.1.xml

On Mac OS X Lion 10.7.3, it used to work before the last git pull.

**Comment by mpdehaan** [comment]
Thanks for the report.

we're going to remove asciidoc from the build steps and check in the manpage output, closing as a dup of #42
