### ISSUE TITLE
mysql_db module's state=dump should include detailed error message

### ISSUE THREAD

**Issue by E-M** [ansible/ansible#4301]
mysql_db module when used with state=dump fails without reason given. It should have stdout at least.

ansible localhost -c local -u root -m mysql_db -a "login_password=xxxx login_user=root name=prod state=dump target=/backup/backup-prod.sql" -vvv

<17.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1380549742.98-31810291682605 && echo $HOME/.ansible/tmp/ansible-1380549742.98-31810291682605']
<17.0.0.1> REMOTE_MODULE mysql_db login_password=xxxxx login_user=root name=prod state=dump target=/backup/backup-prod.sql
<17.0.0.1> PUT /tmp/tmpdG_TMr TO /root/.ansible/tmp/ansible-1380549742.98-31810291682605/mysql_db
<17.0.0.1> EXEC ['/bin/sh', '-c', '/usr/bin/python /root/.ansible/tmp/ansible-1380549742.98-31810291682605/mysql_db; rm -rf /root/.ansible/tmp/ansible-1380549742.98-31810291682605/ >/dev/null 2>&1']
localhost | FAILED >> {
    "failed": true, 
    "msg": "dump failed!"
}

**Comment by E-M** [comment]
Small correction: I am also using login_unix_socket=/path/to/mysqlserver.sock when connecting to DB with mysql_db module.

**Comment by jimi-c** [comment]
Can you verify if a similar mysqldump command (including the destination path) works when run manually? I'm wondering if it's something simple here, like disk space or something similarly mundane.

**Comment by E-M** [comment]
When I run mysqldump from command line, it works just fine:

mysqldump -uroot -p -S /var/temp/mysqlserver.sock prod > /backups/backup-prod.sql

**Comment by jimi-c** [comment]
Looking at the code, it appears the module is hard-coded to use `/usr/bin/mysqldump`, and will run the command `/usr/bin/mysqldump -q -h $host -u $user --password=$password $dbname > /path/to/target`. Can you verify the mysqldump command is at that path, and the command works with the options specified above?

**Comment by jimi-c** [comment]
Actually it looks like the issue is probably the fact that the above command doesn't take the -S option into account for the control socket.

**Comment by E-M** [comment]
which mysqldump
/usr/bin/mysqldump

Yes, I think problem is --socket path... As I wrote, I am using login_unix_socket=/path/to/mysqlserver.sock parameter when connecting to DB with mysql_db module, but it seems that module does not take it into account. Btw, when use mysql_db with state=present or state=absent, everything works as expected.

**Comment by jctanner** [comment]
https://github.com/ansible/ansible/commit/807e60222822fc61dbe7ea573dbb5adb1ee3e76c
