### ISSUE TITLE
Add ansible_sudo_user inventory parameter

### ISSUE THREAD

**Issue by jlaska** [ansible/ansible#4305]
## Summary

Ansible allows you to specify an alternative ssh username via the inventory parameter `ansible_ssh_user`.  Unfortunately, when using a non-root user, there is no way to also specify that sudo is required for the host.  The command-line parameters `--sudo` and `--sudo-user` apply to all hosts.  In my case, not all hosts need the use of sudo.
## TLDR

While managing inventory spread across multiple cloud providers, I've found that not all cloud providers support login as the root user.  For example, different AWS distributions require different, non-root, usernames to login.  Once logged in, the non-root user is able to `sudo`.

Currently, ansible allows one to manage host access by way of the host inventory file.  A user is able to specify a hostname alias, different login user name, and a [selection of other variables](http://www.ansibleworks.com/docs/patterns.html#list-of-reserved-inventory-parameters).  It would be helpful to also allow specifying whether sudo is required for a host.  Perhaps the syntax might look like ...

```
ansible_sudo
    Specify whether sudo is required for the host.  The default is false.
ansible_sudo_user
    Specify a per-host sudo username. 
```
## Version Tested

`ansible 1.3.2`

**Comment by mpdehaan** [comment]
This should be implemented now, let me know if you feel things are still missing.
