### ISSUE TITLE
Improve ability to find out about commandline options to improve visiblity.

### ISSUE THREAD

**Issue by michaelkaye** [ansible/ansible#43087]
##### SUMMARY
The features to provide human readable output from ansible CLI commands are not discoverable. This unfortunately is equivalent to them not existing for new users who do not already know about them.

Things that didn't help me find them:
1) Nothing links from the ansible / ansible-playbook online documentation to the list of available configuration options / environment variables - I have to search through the side menu to find it. There should be a clear link to https://docs.ansible.com/ansible/latest/reference_appendices/config.html

2) The "common options" section, https://docs.ansible.com/ansible/latest/cli/ansible-playbook.html#common-options lists options, and I would think the options to make the output readable are commonly used if know about.

3) And there should be a clear mention of how to improve the readability of the commandline output on the commandline tool page, as this will enable people to use ansible as a beginner, independently of the other links.

4) Going to the configuration page here:

https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-stdout-callback

The only available option here is "default" - there is no link or information on how to find other options.

Having searched around I find this page: https://docs.ansible.com/ansible/latest/plugins/callback.html

The multiple stage process required to find available options, each time without a link in the documentation, makes these useful features non-existent.

This should also be included in the documentation here: https://docs.ansible.com/ansible/latest/user_guide/intro_getting_started.html#your-first-commands

I'm fairly sure someone who has used the commandline enough could write a one paragraph, discussion on how to get started. It can and should have a strong opinion, and link off to various configuration options that you have.

##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
ansible
ansible-playbook
etc...

##### ANSIBLE VERSION

Ansible 2.5+

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

I'm somewhat confused how you "replicate" a documentation bug for online documentation. There are links above to documentation that should be updated, but that's just the one path I found - there seems to be very few cross link to other sources of information, and no beginners guide.

N/A

##### EXPECTED RESULTS

N/A

##### ACTUAL RESULTS

N/A

```

```

**Comment by maxamillion** [comment]
cc @acozine

**Comment by bcoca** [comment]
We should be able to add a link from the config https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-stdout-callback
to the callback list to show 'available options' https://docs.ansible.com/ansible/latest/plugins/callback.html

Adding a mention to the --help should also be possible, to at least point to the callback stdout entry.
