### ISSUE TITLE
Ansible 'user' module does not handle SLES 10 for 'groups'

### ISSUE THREAD

**Issue by daleq** [ansible/ansible#4312]
Running a playbook with a task that uses 'user' module
# cat min.yml

---
- hosts: all
  user: root
  vars:
  - username: dale
  
  tasks:
  - name: Add user to 'wheel' group
    user: name={{ username }} state=present append=yes groups=wheel createhome=no
# ansible-playbook min.yml -v  -i inventory_tmp

failed: [192.168.10.192] => {"failed": true, "name": "dale", "rc": 2}
msg: /usr/sbin/usermod: invalid option -- a
Try `usermod --help' or`usermod --usage' for more information.
FATAL: all hosts have already failed -- aborting

**Comment by mpdehaan** [comment]
Yay for SLES10!

Looks like we need to check to see how old usermod is.

**Comment by daleq** [comment]
Note that nowhere in the bug do I say that I _like_ SLES...  :-)

On SLES 10

# cat /etc/issue

Welcome to SUSE Linux Enterprise Server 10 SP3 (x86_64) - Kernel \r (\l).

# usermod -v

usermod (pwdutils) 3.0.7.1

The usermod manpage does NOT show a '-A' option.

On SLES 11

# cat /etc/issue

Welcome to SUSE Linux Enterprise Server 11 SP1  (x86_64) - Kernel \r (\l).

# usermod (pwdutils) 3.2.8

The usermod manpage DOES show a '-A' option.

Hope this helps.
Dale

**Comment by daleq** [comment]
Better formatting of above...

On SLES 10 

# cat /etc/issue

Welcome to SUSE Linux Enterprise Server 10 SP3 (x86_64) - Kernel \r (\l). 

# usermod -v

usermod (pwdutils) 3.0.7.1  

The usermod manpage does NOT show a '-A' option.   

On SLES 11 

# cat /etc/issue

Welcome to SUSE Linux Enterprise Server 11 SP1  (x86_64) - Kernel \r (\l). 

# usermod (pwdutils) 3.2.8

The usermod manpage DOES show a '-A' option.  

Hope this helps.

**Comment by daleq** [comment]
Thanks for creating a fix!

I'm not a python expert, but it looks to me like line 378
  if self.append and not has_append:
should be
  if self.append and has_append:
(note the removed 'not')

Otherwise, if 'has_append' is true, then the command will try to use -G.

Thanks again.

**Comment by jctanner** [comment]
@daleq,

On opensuse 10, has_append will be False. So once it gets to the "self.append and not has_append", it will evaluate to "not False", aka True, 

<pre>
[root@localhost ~]# python -c "print (not False)"
True
</pre>
