### ISSUE TITLE
Do/until should fail when retries are reached

### ISSUE THREAD

**Issue by jimi-c** [ansible/ansible#4314]
If retries are exceeded without a successful result, the task should fail exactly as if there was no retry specified.

**Comment by mpdehaan** [comment]
Documentation should also be updated to match too.

**Comment by mpdehaan** [comment]
This is a new feature so we should get it tweaked before we release, still time before changing compat.

**Comment by jctanner** [comment]
This is working in the current devel branch, based on the example documented in http://www.ansibleworks.com/docs/playbooks_loops.html#id14.

<pre>
TASK: [script test.sh] ******************************************************** 
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1381160688.44-132123467122422 && chmod a+rx $HOME/.ansible/tmp/ansible-1381160688.44-132123467122422 && echo $HOME/.ansible/tmp/ansible-1381160688.44-132123467122422']
<localhost> PUT /home/jtanner/issues/4314-do_until_retry_break/test.sh TO /home/jtanner/.ansible/tmp/ansible-1381160688.44-132123467122422/test.sh
<localhost> EXEC chmod +x /home/jtanner/.ansible/tmp/ansible-1381160688.44-132123467122422/test.sh; /home/jtanner/.ansible/tmp/ansible-1381160688.44-132123467122422/test.sh 
<localhost> EXEC ['/bin/sh', '-c', 'rm -rf /home/jtanner/.ansible/tmp/ansible-1381160688.44-132123467122422/ >/dev/null 2>&1']
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1381160688.45-129603112292500 && chmod a+rx $HOME/.ansible/tmp/ansible-1381160688.45-129603112292500 && echo $HOME/.ansible/tmp/ansible-1381160688.45-129603112292500']
<localhost> PUT /home/jtanner/issues/4314-do_until_retry_break/test.sh TO /home/jtanner/.ansible/tmp/ansible-1381160688.45-129603112292500/test.sh
<localhost> EXEC chmod +x /home/jtanner/.ansible/tmp/ansible-1381160688.45-129603112292500/test.sh; /home/jtanner/.ansible/tmp/ansible-1381160688.45-129603112292500/test.sh 
<localhost> EXEC ['/bin/sh', '-c', 'rm -rf /home/jtanner/.ansible/tmp/ansible-1381160688.45-129603112292500/ >/dev/null 2>&1']
Result from run 1 is: {'attempts': 1, 'stdout': 'thisint = 3\n', 'stderr': '', 'rc': 0}
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1381160688.46-220949088400458 && chmod a+rx $HOME/.ansible/tmp/ansible-1381160688.46-220949088400458 && echo $HOME/.ansible/tmp/ansible-1381160688.46-220949088400458']
<localhost> PUT /home/jtanner/issues/4314-do_until_retry_break/test.sh TO /home/jtanner/.ansible/tmp/ansible-1381160688.46-220949088400458/test.sh
<localhost> EXEC chmod +x /home/jtanner/.ansible/tmp/ansible-1381160688.46-220949088400458/test.sh; /home/jtanner/.ansible/tmp/ansible-1381160688.46-220949088400458/test.sh 
<localhost> EXEC ['/bin/sh', '-c', 'rm -rf /home/jtanner/.ansible/tmp/ansible-1381160688.46-220949088400458/ >/dev/null 2>&1']
Result from run 2 is: {'attempts': 2, 'stdout': 'thisint = 0\n', 'stderr': '', 'rc': 0}
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1381160688.48-50189552520610 && chmod a+rx $HOME/.ansible/tmp/ansible-1381160688.48-50189552520610 && echo $HOME/.ansible/tmp/ansible-1381160688.48-50189552520610']
<localhost> PUT /home/jtanner/issues/4314-do_until_retry_break/test.sh TO /home/jtanner/.ansible/tmp/ansible-1381160688.48-50189552520610/test.sh
<localhost> EXEC chmod +x /home/jtanner/.ansible/tmp/ansible-1381160688.48-50189552520610/test.sh; /home/jtanner/.ansible/tmp/ansible-1381160688.48-50189552520610/test.sh 
<localhost> EXEC ['/bin/sh', '-c', 'rm -rf /home/jtanner/.ansible/tmp/ansible-1381160688.48-50189552520610/ >/dev/null 2>&1']
Result from run 3 is: {'attempts': 3, 'stdout': 'thisint = 4\n', 'stderr': '', 'rc': 0}
failed: [localhost] => {"attempts": 3, "failed": true, "rc": 0}
stdout: thisint = 4
msg: Task failed as maximum retries was encountered
FATAL: all hosts have already failed -- aborting
</pre>
