### ISSUE TITLE
Unicode Character in hosts file (as a variable value) causes exception

### ISSUE THREAD

**Issue by chemhack** [ansible/ansible#4316]
A host variable is defined in hosts file as

hostname test_var=测试

And this variable is used in j2 template file with {{ test_var }}

Both template file and hosts file is saved in UTF-8 encoding.

When executing the template task, an error come up:

fatal: [hostname => {'msg': "'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)", 'failed': True}

ansible version: 1.3.2

**Comment by mpdehaan** [comment]
I do want to fix this.

As a suggested workaround though, I suspect if you move this to the host_vars/hostname file it will be ok?

**Comment by chemhack** [comment]
@mpdehaan Thank you. It works in host_vars. But I really want to have it in the inventory file.

**Comment by mpdehaan** [comment]
Confirmed this also affects the development branch.

Our templating code for strings is different from files, so I think basically we need to make the two code sections share more.

**Comment by mpdehaan** [comment]
This no longer causes an exception on the devel branch so I'm going to close this one.

Sorry for the delay in response, we have been swamped with community input!

Thanks!
