### ISSUE TITLE
Support installing with --user

### ISSUE THREAD

**Issue by flub** [ansible/ansible#4318]
Version: 1.3.2

Reproduce: `pip install --user ansible` or `python setup.py install --user`

Expected result: Install ansible library in ~/.local/share/ansible/

Actual result: ansible library is installed into /usr/share/ansible 

The correct install scheme should be used.  Currently when installing with --user the data files will still be installed into /usr/share/ansible instead of ~/.local/share/ansible.  You can get access to correct location using `sysconfig.get_path('data', 'posix_user')` (or whatever the appropriate scheme.  The only issue is knowing which scheme you are using.  In setup.py it as simple as not using DEFAULT_MODULE_PATH but simply using 'share/ansible/' instead.

For the runtime setting of DEFAULT_MODULE_PATH this might be a little harder.  One could just iterate over all the installation schemes until you find a directory but that's easy to pick up a wrong version.  So maybe instead the install command could be extended in setup.py to modify the DEFAULT_MODULE_PATH upon installation to write the scheme used or the location into ansible/constants.py.  This can easily be done in a way where it falls back to the current behaviour.

**Comment by jimi-c** [comment]
Are you familiar with the hacking/env-setup script we include in the git repository? It does essentially what you're wanting above.

**Comment by mpdehaan** [comment]
While I completely agree that this makes it easier, I'm thinking we should finally fix this problem for those that don't read the docs.

The catch is of course the defaults in Ansible won't be too smart, and if no --user is supplied I'd want it to work exactly as it does now.

Patches would be entertained.

**Comment by flub** [comment]
I'll see if I can create a patch for my second proposal, but it will be a few weeks before I can get to it.  And yes, `python setup.py install` should keep behaving exactly as it does now.

**Comment by pwaller** [comment]
One should be able to install the project without root by writing simply `pip install --user [--editable] ansible`. In fact, this seems to work without `[--editable]`. Unfortunately [due to a bug in `distribute/pip`](https://bitbucket.org/tarek/distribute/issue/177/setuppy-develop-doesnt-support-package_dir) `package_dir` isn't currently supported correctly in `setup.py`.

**Comment by mpdehaan** [comment]
Didn't see any traction on the above so I think we can close the above.

Pull requests for improvements would still be considered.

Thanks!
