### ISSUE TITLE
Inventory file with duplicate hostnames

### ISSUE THREAD

**Issue by thijsterlouw** [ansible/ansible#4319]
This does not work (note the usage of localhost two times; I am running Vagrant (ssh port 2222) and within the vagrant box I am running a Docker container (ssh port 29007); this container has not been started yet ):

```
[hostvessels]
localhost ansible_ssh_user=core ansible_ssh_port=2222 ansible_ssh_private_key_file=/home/thijsterlouw/.vagrant.d/insecure_private_key

[containers]
localhost ansible_ssh_user=root ansible_ssh_port=29007 ansible_ssh_pass=password
```

error:

```
TASK: [ensure container path for docker.sh] *********************************** 
fatal: [localhost] => Authentication failure.
```

But this does work (note I renamed the first host):

```
[hostvessels]
coreos.vagrant ansible_ssh_user=core ansible_ssh_port=2222 ansible_ssh_private_key_file=/home/thijsterlouw/.vagrant.d/insecure_private_key

[containers]
localhost ansible_ssh_user=root ansible_ssh_port=29007 ansible_ssh_pass=password
```

Where coreos.vagrant is mapped in /etc/hosts to 127.0.0.1

I am running this with 

```
ansible-playbook -i generated/servers.ini static/site.yml --tags="predeploy,deploy"
```

The container inside the Vagrant box is not yet running, but this should be ignored because I am only performing tasks that hit the hostvessels. 

Why does Ansible think the host is down, even though the appropriate ssh port is perfectly available. Looks like a bug to me.

```
ansible --version
ansible 1.4
```

**Comment by bcoca** [comment]
not a bug, if you define a host var in more than one group, they are
overridden by the last group loaded. you are not getting 2 ansible_ssh_port
for localhost, only one, does not matter which group you used to select a
host, all group vars get loaded.

**Comment by jimi-c** [comment]
As @bcoca says, this is not a bug. Please refer to the inventory documentation here http://www.ansibleworks.com/docs/patterns.html (which may be moving soon, due to the document restructuring going on) to see how to put things into child groups without having to re-specify the host name.

**Comment by thijsterlouw** [comment]
thanks @bcoca : that is what I understood from the Ansible behavior.
@jimi-c I reread the patterns page, but I don't understand how this can work. How do I get only the variables to load/apply that I actually want to use? Even if I use groups + children + separate group_vars the host will still pickup the vars from the last group it was in.

inventory that will still be wrong:

```
[hosts]
localhost

[hostvessels:children]
hosts

[containers:children]
hosts

[hostvessels:vars]
ansible_ssh_user=core
ansible_ssh_port=2222
ansible_ssh_private_key_file=/home/thijsterlouw/.vagrant.d/insecure_private_key

[containers:vars]
ansible_ssh_user=root
ansible_ssh_port=29007
ansible_ssh_pass=password
```

I guess the only solution is to give them different names; eg each vm a different name and each container inside each vm also another name.

**Comment by tszming** [comment]
While this is not a bug according to the doc, I agree with @thijsterlouw that it can be better handled like, e.g.

site.yml

```
- hosts: web
  user: ubuntu
```

hosts

```
[web]
server-1

[db]
server-1

[web:vars]
test=FOO

[db:vars]
test=BAR
```

If I am running playbook against hosts "web", there is no reason why the "db" group variables "BAR" should overwrite my expected variables "FOO"

**Comment by yudai09** [comment]
Similar to others, I got a unexpected Ansible result.
It is a wrong group_vars adaption like below.
- command

```
ansible-playbook -i hosts_localhost playbook.yml -e "target=service_mm"
```
- results

```
Variables stored in templates is not "service_mm" vars but "stage" vars.
```

configs are below
- hosts_localhost

```
[stage]
localhost
[service]
localhost
[service_mm]
localhost
```
- playbook.yml

```
- hosts: '{{target}}'
   sudo: yes
   tasks:
           - template: ・・・
```
- ansible directory 

```
group_vars/
├── service
├── service_mm
└── stage
```

I specified group name "service_mm" in command line, but Ansible adapts “stage” variables  for templates files.
I guess Ansible find localhost in “service_mm” section first, and it searched localhost again, and find localhost in “stage” section.

I understand it is not bug, but I want to be informed about the duplication of variables.

**Comment by asaphe** [comment]
A single playbook with two `Hosts:` directive each targeting a different hosts group.
The host itself has the same name but different IPs. (Internal/External)

**Expected Result:**
Ansible should target the correct host per group.

**Result**:
Ansible targets only one of the hosts under a specific group
**Note** that list actually targets the different group and manages to select the correct hostname

Invenotry:
```
[external-server]
server1 ansible_host=1.1.1.1

[internal-server]
server1 ansible_host=2.2.2.2

```
List-Hosts:
```
  play #1 (external-server): external-server	TAGS: [external]
    pattern: [u'external-server']
    hosts (1):
      server1

  play #2 (internal-server): internal-server	TAGS: [internal]
    pattern: [u'internal-server']
    hosts (1):
     server1
```
