### ISSUE TITLE
Accelerate mode fails at gather_facts stage with sudo non-root to non-root

### ISSUE THREAD

**Issue by daveadams** [ansible/ansible#4321]
Using sudo from a non-root user to a non-root user, I get an error when using accelerated mode even with NOPASSWD and with requiretty disabled. Disabling accelerated mode does allow it to work, but seems like this scenario should be acceptable. Relates to #4217 but it seems like this should work.

Here's the relevant snippet of my playbook:

```
- hosts: testing
  accelerate: true
  remote_user: subsuperuser
  sudo: yes
  sudo_user: myappuser
  tasks:
    - command: touch /apps/test.txt
```

When I execute the playbook I get this result:

```
GATHERING FACTS *************************************************************** 
fatal: [testhost] => failed to put the file in the requested location
```

It appears that during the gathering facts section, accelerated mode tries to copy the setup file using sudo with the root user, not the specified sudo_user value. From syslog:

```
Oct  1 10:52:34 : subsuperuser : no tty present and no askpass program specified ;
    TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/cp
    /home/subsuperuser/.ansible/tmp/ansible.QQfqHp /tmp/ansible-1380639154.41-57741279324315/setup
```

If I remove "accelerate: true" from the playbook, the playbook works, and I see this in syslog instead:

```
Oct  1 10:53:06 : subsuperuser : TTY=pts/2 ; PWD=/home/subsuperuser ; USER=myappuser ;
    COMMAND=/bin/sh -c /usr/bin/python /tmp/ansible-1380639181.86-9412934553665/setup
Oct  1 10:53:12 : subsuperuser : TTY=pts/2 ; PWD=/home/subsuperuser ; USER=myappuser ;
    COMMAND=/bin/sh -c /usr/bin/python /tmp/ansible-1380639188.42-30873271079521/command
```

**Comment by jimi-c** [comment]
Thanks for reporting this, I'm taking a look into it now.

**Comment by daveadams** [comment]
Looks like the issue may be in ./library/utilities/accelerate, the "put" method:

```
if final_path:
    log("moving %s to %s" % (out_path, final_path))
    args = ['sudo','cp',out_path,final_path]
    rc, stdout, stderr = self.server.module.run_command(args, close_fds=True)
    if rc != 0:
        return dict(failed=True, stdout="failed to copy the file into position with sudo")
    args = ['sudo','chown',final_user,out_path,final_path]
    rc, stdout, stderr = self.server.module.run_command(args, close_fds=True)
```

Both "run_command" executions attempt to sudo to copy and then chown the file without specifying the user, so it's trying to copy as root. If the sudo_user is not root, I'm thinking the behavior should be to just do the copy using "sudo -u [sudo_user]" and to skip the chown step.

Simply making that change, however, appears to interfere with other earlier steps in the process and the failure happens sooner. Where can I find the logging that's supposedly happening on the other end of the connection?

**Comment by jimi-c** [comment]
By default, log messages from the accelerate daemon are sent to syslog, so you should see them wherever your system is configured (ie. for RHEL/CentOS it's /var/log/messages).

I'm about to merge this patch into devel, if you'd like to give it a test:

<pre>
diff --git a/library/utilities/accelerate b/library/utilities/accelerate
index 371e4ad..70411cb 100644
--- a/library/utilities/accelerate
+++ b/library/utilities/accelerate
@@ -311,14 +311,7 @@ class ThreadedTCPRequestHandler(SocketServer.BaseRequestHandler):
 
         if final_path:
             log("moving %s to %s" % (out_path, final_path))
-            args = ['sudo','cp',out_path,final_path]
-            rc, stdout, stderr = self.server.module.run_command(args, close_fds=True)
-            if rc != 0:
-                return dict(failed=True, stdout="failed to copy the file into position with sudo")
-            args = ['sudo','chown',final_user,out_path,final_path]
-            rc, stdout, stderr = self.server.module.run_command(args, close_fds=True)
-            if rc != 0:
-                return dict(failed=True, stdout="failed to chown the file via sudo")
+            self.server.module.atomic_move(out_path, final_path)
         return dict()
 
 def daemonize(module, password, port, minutes):
</pre>
