### ISSUE TITLE
Script module can't find ansible tmp directory

### ISSUE THREAD

**Issue by horseinthesky** [ansible/ansible#43216]
##### SUMMARY

I'm using **script** module to transfer python script to remote host and execute it.

I'm getting an error message from the remote host about the script was not found in ansible tmp folder.
My user **horseinthesky** exists on both local (Ansible Controller) and remote hosts. It has sudo.
The **tmp** directory with the specified name doesn't exist on the remote host and I don't know why.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

script module

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /home/horseinthesky/netprog/Ansible/05_deploy_JunOS_vRR/ansible.cfg
  configured module search path = ['/home/horseinthesky/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0]
```

##### CONFIGURATION

```
[defaults]
inventory = ./hosts.yml
host_key_checking=False
retry_files_enabled = False
gathering = explicit
remote_user = horseinthesky
ask_pass = True
```

##### OS / ENVIRONMENT

Linux Kappa 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

```
- name: Making router reachable via CLI
  script: magic_wand.py
  become: no
```

##### EXPECTED RESULTS

File to be trasfered and executed on remote host.

##### ACTUAL RESULTS

```
fatal: [192.168.0.95]: FAILED! => {
    "changed": true,
    "msg": "non-zero return code",
    "rc": 127,
    "stderr": "Shared connection to 192.168.0.95 closed.\r\n",
    "stderr_lines": [
        "Shared connection to 192.168.0.95 closed."
    ],
    "stdout": "/bin/sh: 1: /home/horseinthesky/.ansible/tmp/ansible-tmp-1532444223.63863-119969896692260/magic_wand.py: not found\r\n",
    "stdout_lines": [
        "/bin/sh: 1: /home/horseinthesky/.ansible/tmp/ansible-tmp-1532444223.63863-119969896692260/magic_wand.py: not found"
    ]
}
```

**Comment by horseinthesky** [comment]
I can workaround with this using combination of **copy** and **command** but I want to understand if i'm doing something wrong with **script**
```
- name: Copy magic_wand script to host
  copy:
    src: magic_wand.py
    dest: "/home/{{ lookup('env', 'USER') }}/"
  become: no

- name: Making router reachable via CLI
  command: python "/home/{{ lookup('env', 'USER') }}/magic_wand.py"
```

**Comment by ryansb** [comment]
Make sure that the playbook itself and the `magic_wand.py` script are in the same directory. Are both the host and target running Ubuntu Kappa?

needs_info

**Comment by horseinthesky** [comment]
Yes. magic_wand.py is in playbook directory. Otherwise, ansible just says that it can't find it.
And yes, both hosts are ubuntu, Kappa is 18.04, remote host is 16.04.
I've tried using absolute and relative path. Also tried **become: yes** and **become: no**.

I guess ansible is using **tmp** folders for its action so I'm ok with that. What I don't understand is why and how it always generates **tmp** dir with a number that doesn't exist.

**Comment by jk2K** [comment]
I have same issue

- WSL environment

```
ansible --version                                                                                                                             
  ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/lee/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

```bash
ls -l
total 8
-rwxrwxrwx 1 lee lee   27 Jul 17 23:50 deploy1.sh
-rwxrwxrwx 1 lee lee  269 Jul 17 00:50 deploy_frontend.sh
-rwxrwxrwx 1 lee lee  469 Jul 15 00:08 start.sh
```

`ansible $server_name -m script -a "deploy_frontend.sh"` works

`ansible ali -m script -a "deploy1.sh"` not work

really weird

**Comment by jk2K** [comment]
may duplicate https://github.com/ansible/ansible/issues/16046

**Comment by jk2K** [comment]
After many attempts, I found the reason

refer to [script – Runs a local script on a remote node after transferring it](https://docs.ansible.com/ansible/latest/modules/script_module.html)

the local script is executed by default using `/bin/sh`. If I specify the executor in the script, I will get the above error

for example

```bash
#!/bin/bash

echo "hello"
```

In this case, the `executable` parameter is required, 

you can try: `ansible ali -m script -a "deploy1.sh executable=/bin/bash"`

the problem is solved, but this error message is too unfriendly, the error made me misunderstood

**Comment by horseinthesky** [comment]
Thank you. I'll remember for future use =)
