### ISSUE TITLE
Passing variables between different playbooks

### ISSUE THREAD

**Issue by cloudbluedigital** [ansible/ansible#43226]
##### SUMMARY

So it's probably not even a bug but I cannot find a solution

I basically have a bash like this:

```
ansible-playbook ./init-playbook.yml -i hosts
ansible-playbook ./rds-playbook.yml -i hosts
```

In init playbook I set a fact with branch variable and in rds playbook I want to use that variable however it is not defined, if I move code from rds playbook to init playbook everything works fine.

So the question is really how do I assign a variable in init-playbook and use that variable in rds-playbook

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = None
  configured module search path = [u'/Users/arthur/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/arthur/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /Users/arthur/Library/Python/2.7/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

Init Playbook

```
- hosts: server
  connection: local
  become: no

  tasks:
    - name: Check Current Branch
      shell: |
        git branch | grep -e "^*" | cut -d' ' -f 2
      register: branch

    - debug:
        var: branch.stdout

    - set_fact:
        branch: branch.stdout

```

rds playbook

```

- hosts: server
  connection: local
  become: no
  vars_files:
    - dev.yml

  tasks:

    - debug:
        var: hostvars['localhost']['branch']
```

##### EXPECTED RESULTS

Variable not defined
##### ACTUAL RESULTS

Name of the branch

```

```

**Comment by ryansb** [comment]
Facts are not settable across playbooks by default. You can discover the branch (per those shell tasks) in a common `tasks/get-branch.yml` file, then use `include_tasks` to include that series of tasks in both playbooks. You can also create a role, if you want more than just the few tasks, so you can invoke the role in both playbooks and have the variables discovered the same way both times.
