### ISSUE TITLE
Support passworded sudo with ansible_ssh_pass

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#4323]
When providing ansible_ssh_pass as a hostvar, such as from an inventory script, ansible should be capable of utilizing the already provided password for passworded sudo.

**Comment by mpdehaan** [comment]
I would suggest we implement this as ansible_sudo_pass being a variable (if not already) and then ansible_sudo_pass having a special value of "ansible_ssh_pass" that would let it reuse the default maybe?

**Comment by sivel** [comment]
I believe that to be a good solution.

**Comment by resmo** [comment]
good job!
