### ISSUE TITLE
ssh extra args passed as group variables do not override ansible.cfg

### ISSUE THREAD

**Issue by jaepetto** [ansible/ansible#43257]
##### SUMMARY
ssh_extra_args passed as group variables within an inventory file do not override parameters in the ansible.cfg

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /Users/jaep/cede/code/prod_repos/epflstack/src/edx-configuration/playbooks/ansible.cfg
  configured module search path = [u'/Users/jaep/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION
```
ANSIBLE_SSH_ARGS(/Users/jaep/cede/code/prod_repos/epflstack/src/edx-configuration/playbooks/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="~/.ansible/tmp/ansible-ssh-%h-%p-%r" -o ServerAliveInterval=30
DEFAULT_JINJA2_EXTENSIONS(/Users/jaep/cede/code/prod_repos/epflstack/src/edx-configuration/playbooks/ansible.cfg) = jinja2.ext.do
DEFAULT_MANAGED_STR(/Users/jaep/cede/code/prod_repos/epflstack/src/edx-configuration/playbooks/ansible.cfg) = This file is created and updated by ansible, edit at your peril
DEFAULT_REMOTE_USER(/Users/jaep/cede/code/prod_repos/epflstack/src/edx-configuration/playbooks/ansible.cfg) = ubuntu
DEFAULT_ROLES_PATH(/Users/jaep/cede/code/prod_repos/epflstack/src/edx-configuration/playbooks/ansible.cfg) = [u'/Users/jaep/cede/code/prod_repos/epflstack/src/ansible-roles/roles', u'/Users/jaep/cede/code/prod_repos/epflstack/src/ansible-private/roles', u'/Users/jaep/cede/code/prod_repos/epflstack/src/ansible-roles']
DEFAULT_VAULT_PASSWORD_FILE(/Users/jaep/cede/code/prod_repos/epflstack/src/edx-configuration/playbooks/ansible.cfg) = /Users/jaep/.vault_password
HOST_KEY_CHECKING(/Users/jaep/cede/code/prod_repos/epflstack/src/edx-configuration/playbooks/ansible.cfg) = False
```
##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
Set your `ansible.cfg` with the following `ssh_args`
```
[ssh_connection]
 ssh_args=-o ControlMaster=auto -o ControlPersist=60s -o ControlPath="~/.ansible/tmp/ansible-ssh-%h-%p-%r" -o ServerAliveInterval=30
```
Set your inventory file with group variables:
```
[app_servers]
devstack ansible_host=127.0.0.1

[all:vars]
ansible_port=2222 
ansible_user=vagrant 
ansible_ssh_private_key_file=/Users/jaep/.vagrant.d/boxes/ginkgo-devstack-2017-07-14/0/virtualbox/vagrant_private_key
ansible_ssh_extra_args="-o UserKnownHostsFile=/dev/null -o ControlMaster=no"
```

Not really relevant. However (surprisingly the below command works - probably because it does not require ssh multiplexing)

```bash
ansible -i hosts.ini -m ping all -vvv
```

##### EXPECTED RESULTS
The passed command should only retain the parameter `-o ControlMaster=no`

##### ACTUAL RESULTS
the passed ssh command is:
```
EXEC ssh -o ControlMaster=auto -o ControlPersist=60s -o 'ControlPath=~/.ansible/tmp/ansible-ssh-%h-%p-%r' -o ServerAliveInterval=30 -o StrictHostKeyChecking=no -o Port=2222 -o 'IdentityFile="/Users/jaep/.vagrant.d/boxes/ginkgo-devstack-2017-07-14/0/virtualbox/vagrant_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=no 127.0.0.1 '/bin/sh -c '"'"'echo ~vagrant && sleep 0'"'"''
```
The ControlMaster option is passed twice:
Once with value auto and once with the value no.

Only the first instance is kept by the ssh command, resulting in a failure (because the path in ControlPath=~/.ansible/tmp/ansible-ssh-%h-%p-%r is too long - but that's another topic).

**Comment by sivel** [comment]
`ansible_ssh_extra_args` and the `ssh_args` from ansible.cfg are completely different configurations that are not meant to replace the value.

However the order that these vars are processed and passed to ssh end up achieving this same behavior.  As you mention:

> The ControlMaster option is passed twice:
> Once with value auto and once with the value no.

The effective behavior here, due to how ssh works, will be to use the last supplied.  So the value of `no` will be the configuration utilized.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
