### ISSUE TITLE
Add ability to use variables for async and poll

### ISSUE THREAD

**Issue by base10** [ansible/ansible#4325]
When I use poll or async with a task, I cannot use variables with them. Since I have a number of tasks that I would like to make asynchronous, I would appreciate having the ability to set a value in a group_vars file or in vars with the playbook itself instead of individually by task.

This functionality works with integers, but fails with variables. I've created a sample playbook and captured the stacktrace here: https://gist.github.com/base10/6780137

Thanks!

**Comment by mpdehaan** [comment]
Yep, we can template these.

**Comment by base10** [comment]
Fantastic. That'll be very helpful.

**Comment by mpdehaan** [comment]
Reclassifying this as a bug report so it doesn't get lost :)

**Comment by jctanner** [comment]
@base10 this should be functional in devel now, thanks!

**Comment by base10** [comment]
@jctanner Yay! Thanks.
