### ISSUE TITLE
Role dependencies: Allow duplicates per dependency

### ISSUE THREAD

**Issue by TomFrost** [ansible/ansible#4328]
Currently, the meta/main.yml file in roles supports controlling whether duplicate dependencies will be allowed based on the `allow_duplicates` field at the root level.  However, it's possible that some dependencies should not be duplicated, while others within the same file should be.

**Implementation:** `allow_duplicates` could remain at the root level, while `allow_duplicate` could be passed in each dependency block to override the root setting.

**Use case:** A role to install an application from a git repo depends on nginx and PHP, and so is dependent upon the 'webserver' role.  If a server runs more than one application, webserver itself should not be loaded again.

However, another 'application_release' role may be responsible for following a long series of steps to install an application, such as cloning/updating it from git, running make, copying this release into a new folder, symlinking a 'current_release' folder to the new release, deleting old releases, etc.  This role is appropriate for application-specific roles to load more than once, with different variables to control the git repo, version, application name, etc.

In the above, one would require the 'webserver' dependency to not be duplicated, but the 'appliaction_release' role be duplicated as often as other roles require it.

**Comment by mpdehaan** [comment]
Do you have a suggested syntax for what this might look like in meta.yml or elsewhere?

**Comment by mpdehaan** [comment]
Closing given lack of a syntax example.

This might be a good conversation for ansible-devel if you would like to bring it up on the google group.

Thanks!
