### ISSUE TITLE
Add `loop` object automatically in loop

### ISSUE THREAD

**Issue by guoqiao** [ansible/ansible#43282]
##### SUMMARY

In Jinja2 or Django template, when you do a for loop, it defines a `loop` object automatically.
You can do things like:

```
{% for item in items %}
{{loop.index}} - {{item}}
{% endfor %}
```
This is very nature and handy.
However, in Ansible, we need to do:

```
- name: a loop demo
  debug: msg="{{index}} - {{item}}"
  loop: "{{items}}"
  loop_control:
    index_var: index
```
This is annoying for people familiar with Jinja2 or Django template syntax.
And I think it should be easy to add a default `loop` object automatically in a loop,
just like how the `item` var is added. And we can add the same vars in the loop object, 
such as `loop.index`, `loop.index0`, just like Jinja2 and Django template do.

##### ISSUE TYPE
 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.6.1
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by sivel** [comment]
I have a PR that adds this functionality at https://github.com/ansible/ansible/pull/42134

**Comment by mkrizek** [comment]
The PR above has been merged. Closing.
