### ISSUE TITLE
Playbook support for sudo_flags

### ISSUE THREAD

**Issue by mhite** [ansible/ansible#4331]
sudo_flags can currently be expressed as environmental variable and in the .cfg file. This issue proposes support in the playbook.

**Comment by mpdehaan** [comment]
So if I'm understanding your sudo flags varies by group of host?

Curious of underlying info, not opposed, just curious.

Thanks!

**Comment by bcoca** [comment]
I'm guessing the plan is to set them per host/groups with a inventory var
"ansible_sudo_options"

**Comment by mpdehaan** [comment]
Inventory var versus new PB keyword makes a bit more sense, I'd think, yes.

**Comment by mpdehaan** [comment]
Hi,

We've keeping track of this list but haven't seen any traction here, so are closing this ticket out.  If someone would like to submit a pull request, that would be welcome, and we're still open to it.
