### ISSUE TITLE
Should rax_clb_nodes exist independently?

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#4340]
The 'rax' module was designed initially with the potential of supporting additional Rackspace public cloud products and supports a parameter 'service' that would be used to make this selection.

It does however appear as though many of the other modules have independent files for each product, so I am unsure if that should be considered the standard or not.

Regardless, I might also like to see it renamed rax_clb for consistency, and for flexibility of additions to the code base.

Thoughts? (@j2sol)

**Comment by mpdehaan** [comment]
Hi @sivel, super interested in this, but can we have this discussion on ansible-devel please?

This way more people will see it.

I do agree _nodes was confusing to me and I am not opposed to forcing the rename.

cc @jimi-c  @jctanner also
