### ISSUE TITLE
I'd love this way to do an implicit group_by...

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#4341]
Instead of using group_by, which still has value, sometimes I want to write conditional plays.

```
- hosts: whatever_groups
  when: 
    - ansible_os_family == "Debian"
    - foons > sporks
    - not emergency_mode
```

Etc

And if the host didn't meet the criteria, it would get pulled out of the group, rather than generating a lot of skips.

There's nothing to say this has to wait for fact caching but would be greatly improved should it exist.

**Comment by zirpu** [comment]
So if 'when' has a list instead of scalar, it would "and" those conditions together?

**Comment by mpdehaan** [comment]
yep

**Comment by jimi-c** [comment]
Alternative idea: task groups:

<pre>
- hosts: all
  task_group:
  - when: ansible_os_family == "Debian"
    tasks:
    - name: task 1
      ...
</pre>

Alternative to the alternative, define the task groups outside of the play and allow tasks to be added to them, as follows:

<pre>
- task_group: foo
  when: something is true
- task_group: bar
  when: something is false
- hosts: all
  tasks:
  - name: do something
    task_group: foo
  - name: do something else
    task_group: foo
  - name: do something only for bar
    task_group: bar
</pre>

**Comment by jimi-c** [comment]
For the second case, the task group definition would not have to be outside of the play, but it could help simplify things for playbooks that contain multiple plays.

**Comment by mpdehaan** [comment]
Hi,

We've keeping track of this list but haven't seen any traction here, so are closing this ticket out.  If someone would like to submit a pull request, that would be welcome, and we're still open to it.
