### ISSUE TITLE
Solaris: FAILED => FAILED: Authentication failed.

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#435]
On a Solaris 10 (sparc) using OpenSSH 5.8p1 I get the following errors. Direct log on as root using keys works.

When using ansible towards a Solaris 10 (x86) I got the following python traceback:

```
system | FAILED => FAILED: Authentication failed.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/runner.py", line 586, in _executor
    (host, ok, data, err) = self._executor_internal(host)
  File "/usr/lib/python2.6/site-packages/ansible/runner.py", line 627, in _executor_internal
    result = self._execute_normal_module(conn, host, tmp, module_name)
  File "/usr/lib/python2.6/site-packages/ansible/runner.py", line 358, in _execute_normal_module
    module = self._transfer_module(conn, tmp, module_name)
  File "/usr/lib/python2.6/site-packages/ansible/runner.py", line 195, in _transfer_module
    outputpath = self._copy_module(conn, tmp, module)
  File "/usr/lib/python2.6/site-packages/ansible/runner.py", line 702, in _copy_module
    conn.put_file(in_pat, out_path)
  File "/usr/lib/python2.6/site-packages/ansible/conection.py", line 154, in put_file
    sftp = self.ssh.open_sftp()
  File "/usr/lib/python2.6/site-packages/paramiko/client.py", line 385, in open_sftp
    return self._transport.open_sftp_client()
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 820, in open_sftp_client
    return SFTPClient.from_transport(self)
  File "/usr/lib/python2.6/site-packages/paramiko/sftp_client.py", line 106, in from_transport
    return cls(chan)
  File "/usr/lib/python2.6/site-packages/paramiko/sftp_client.py", line 89, in __init__
    raise SSHException('EOF during negotiation')
SSHException: EOF during negotiation
```

In a few cases I got the following traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/connection.py", line 156, in put_file
    sftp.put(in_path, out_path)
  File "/usr/lib/python2.6/site-packages/paramiko/sftp_client", line 557, in put
    fr = self.file(remotepath, 'wb')
  File "/usr/lib/python2.6/site-packages/paramiko/sftp_client", line 245, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/usr/lib/python2.6/site-packages/paramiko/sftp_client", line 624, in _request
    return self._read_response(num)
  File "/usr/lib/python2.6/site-packages/paramiko/sftp_client", line 671, in _read_response
    self._convert_status(msg)
  File "/usr/lib/python2.6/site-packages/paramiko/sftp_client", line 687, in _convert_status
    raise IOError(errno.ENOENT, text)
IOError:  [Errno 2] No such file
```

**Comment by dagwieers** [comment]
In this particular case, doing an sftp to the system causes the connection to close directly. So SFTP is not working on this installation.

```
# sftp system
Connecting to system...
Connection closed
```

Even though the configuration does seem to allow sftp:

```
Subsystem       sftp     internal-sftp
```

**Comment by dagwieers** [comment]
Modifying the configuration to include:

```
Subsystem       sftp     /usr/local/libexec/sftp-server
```

makes no difference.

**Comment by dagwieers** [comment]
Syslog mentions:

```
[ID 800047 auth.info] Accepted publickey for root from W.X.Y.Z port 37382 ssh2
[ID 800047 auth.info] subsystem request for sftp by user root
[ID 800047 auth.info] Received disconnect from W.X.Y.Z: 11: disconnected by user
```

**Comment by dagwieers** [comment]
Even a connection to localhost using sftp fails in this way. Must be a problematic setup :-(

**Comment by dagwieers** [comment]
Using `sftp -D /usr/local/libexec/sftp-server` on the local system does work as expected.

**Comment by dagwieers** [comment]
Using the below command it does work:

```
/usr/local/bin/sftp -s /usr/local/libexec/sftp-server localhost
```

And apparently the openssh installation is using _/etc/openssh/sshd_config_ and not _/etc/ssh/sshd_config_ which explains why some of the changes I did, did not work as expected. Looking at fixing the configuration, however restarting the openssh service on Solaris can throw your ssh connection out. Debugging like it's 1999, yeah !

**Comment by dagwieers** [comment]
Once the proper path was added in the correct _sshd_config_ (and eventually a fresh reboot :-/), the conection worked as expected. The setup module returns only some internal facts, but also outputs the following error:

```
system-solaris | FAILED => failed to parse: /bin/ksh: /var/tmp/ansible.bPaWef/setup:  not found
//bin/ksh: /var/tmp/ansible.bPaWef/setup: not found
/setup {
    "group_names": [
        "solaris"
    ],
    "inventory_hostname": "system-solaris",
    "metadata": "/etc/ansible/setup",
}
```

**Comment by dagwieers** [comment]
Now that we fixed #436 for AIX, I see the same problem on AIX. It seems as if the setup module has not been copied to the remote end.

```
system-aix | FAILED => failed to parse: /usr/bin/ksh: /var/tmp/ansible-1338476998.11-101665829257855/setup:  not found.
//usr/bin/ksh: /var/tmp/ansible-1338476998.11-101665829257855/setup:  not found.
/setup {
    "group_names": [
        "aix"
    ],
    "inventory_hostname": "system-aix",
    "metadata": "/etc/ansible/setup",
}
```

**Comment by mpdehaan** [comment]
ok, so this is basically going to be a doc item?  We could make a special page for "non-Linux setup instructions" or something.

**Comment by dagwieers** [comment]
The problem seems to be that the location of the python interpreter hardcoded in _library/setup_ is `/usr/bin/python` and that is incorrect on at least Solaris. On solaris it is located in _/usr/local/bin/python_ (from sunfreeware.com), on AIX it is located in _/usr/bin/python_ (from IBM AIX Toolbox) but was not installed yet.

Once it is installed it fails in too many ways that we have to fix :-)

**Comment by dagwieers** [comment]
@mpdehaan Yes, it started off as a "bugreport" for Solaris, so that others with similar issues would find the relevant bits. But indeed I would like to take the relevant bits and move them at some point into a guide. But only when we have it working...
- On Solaris: the location of python is alarming (how would we want to fix that ?)
- On AIX and Solaris: it requires a good look at the Linux-specific stuff and shielding it off from AIX and Solaris users, implementing other facts instead

We should probably look what stuff puppet and/or chef are doing on those platforms. And then do it better ;-) Since this is just an evaluation, I cannot tell if I can continue with this for very long...

**Comment by mpdehaan** [comment]
ok, it seems this ticket belongs in the docs project (ansible/ansible.github.com) then.

If you can reopen it there that would be good.
