### ISSUE TITLE
user module doesn't create home if user already exists and home is unchanged

### ISSUE THREAD

**Issue by maethor** [ansible/ansible#4350]
First, I have created a user using the ansible "user " module. 
    user: name=foo state=present system=yes home=/srv/foo

Then, I discovered this doesn't creates the home directory, so I simply added "createhome=yes" like this :
    user: name=foo state=present system=yes home=/srv/foo createhome=yes

But when I run the playbook :

```
TASK: [Add foo user] ******************************************************** 
ok: [host.domain.tld]
```

I think you should add a test to see if home directory is created, even if everything else is unchanged.

Thanks you for the awesome work :)

I'm using ansible 1.3.1.

**Comment by mpdehaan** [comment]
Thanks for the heads up.  Quick question.

where you say:

```
 But when I run the playbook :

 TASK: [Add foo user] ******************************************************** 
 ok: [host.domain.tld]
```

Are you suggesting that create_home did not create the directory on the remote system, or that it did not return the changed attribute?   I would agree it should return changed but wanted to check.

Thanks!

**Comment by maethor** [comment]
Both, it doesn't return "changed", and the directory is not created.
