### ISSUE TITLE
blockinfile missing validate example

### ISSUE THREAD

**Issue by vossenjp** [ansible/ansible#43561]
##### SUMMARY
The blockinfile module docs say "The path to the file to validate is passed in via '%s' which must be present as in the example below." but there is no example, at least in https://docs.ansible.com/ansible/2.3/blockinfile_module.html.

##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME

blockinfile_module

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = .../ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

Read the doc, the example is missing.

```yaml
N/A
```

##### EXPECTED RESULTS

I expect to see the example.  :-)

##### ACTUAL RESULTS

```
N/A
```

**Comment by sivel** [comment]
Ansible v2.3 is end of life, and recent versions have this documented as expected.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by vossenjp** [comment]
Fair enough, thanks for the quick reply.  (I'm not happy about my CentOS-5 either, but it's going away Real Soon Now.  Real.  Soon.)
