### ISSUE TITLE
docs search to include snippits

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#43573]
##### SUMMARY

If there is any way to make your internal search engine include snippets where matches are found it might feel more "natural"  (thank Google for setting the standard)

##### ISSUE TYPE
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by acozine** [comment]
Thanks @gundalow for reporting this - can you provide examples? Something like "currently if I search for `cabbage` the results don't include [link to page where `cabbage` is included in a snippet]". Examples will help with testing any fixes we try.

**Comment by samccann** [comment]
looking at this - it seems the top-left search doesn't have snippets, but the bottom-right 'site search' does.

**Comment by samccann** [comment]
This was resolved when we switched to just providing swiftype search results.
