### ISSUE TITLE
Allow playbooks to require a specific version of Ansible

### ISSUE THREAD

**Issue by magnus919** [ansible/ansible#4357]
I would like to be able to require a specific release or do a comparison test for minimum/maximum version of Ansible to make sure plays will run as expected. Ansible versions outside of that specified in the playbook should ideally fail to run with a useful human readable error.

**Comment by mpdehaan** [comment]
Thanks for the feature request.

This is easy to do and I'll probably look at doing this soon as it's been a frequent request.

It probably looks like this

```
- hosts: blarg
  ansible_required: 1.4
```

We should also do the same for roles, where this could be stored in the "meta" file already being used to control dependencies for roles.

**Comment by candlerb** [comment]
A more flexible way would be to expose it as a variable, then you could do things like:

```
- local_action: apt pkg=ansible state=latest
  when: ansible_version < "01.04.00"
```

or

```
- action: some_future_module foo=bar
  when: ansible_version >= "01.05.00"
```

(suggest "xx.yy.zz" to avoid problems with "1.4.10" < "1.4.9")

**Comment by gregbuehler** [comment]
@candlerb +1

you can just start roles/plays with something like

```
 - fail: msg="This playbook requires Ansible 1.0.5.00 or greater."
   when: {{ ansible_version }} <= "01.05.00"
```

**Comment by mpdehaan** [comment]
We've keeping track of this list but haven't seen any traction here, so are closing this ticket out.  If someone would like to submit a pull request, that would be welcome, and we're still open to it.

**Comment by alimony** [comment]
For anyone finding their way here, I solved this by adding this to the top of my playbook:

``` ruby
- hosts: all
  tasks:
    - name: Get current Ansible version on local host
      local_action: command ansible --version
      register: local_ansible_version
    - assert:
        that:
          - "'1.5.4' in local_ansible_version.stdout"
```

**Comment by srgvg** [comment]
FYI #6619 is in queue to have an version var available, and there is a filter in 1.6 that allows to compare "versions".

**Comment by axelabs** [comment]
This doesn't work when comparing to version 2+ since ansible_version is a dictionary but this seems to work:

```
  tasks:
  - debug: msg="You'll need ansible > 1.9.3 to update all packages (https://goo.gl/4J8NXy) {{ ansible_version }}"
    when: update_all_packages == True and ansible_version.major < "2"
```

srvg points out [Jinja2's version_compare filter](http://docs.ansible.com/ansible/playbooks_filters.html#version-comparison-filters), which I'll try and update this post with results...

**Comment by ssbarnea** [comment]
I think we need an option inside the ansible.cfg file, so we can enforce this for the entire repository, not only for specific playbooks.

**Comment by viatcheslavmogilevsky** [comment]
@ssbarnea you can write callback plugin that can check ansible version and fail whole execution with human  readable message if version is not correct (see (v2_)playbook_on_start event)

**Comment by viatcheslavmogilevsky** [comment]
Just maked example

**Comment by martbhell** [comment]
A lot of roles have galaxy meta information and have an ansible min version in there. 
I think it would be cool if ansible looked in there and give an error if it's not right.

**Comment by ypid** [comment]
@martbhell I had the same idea. Tracked in https://github.com/ansible/ansible/issues/18375
