### ISSUE TITLE
Simplified role folder structure alternative

### ISSUE THREAD

**Issue by ydewit** [ansible/ansible#4359]
For most of the playbooks I create, I get a sense that the recommended folder structure, although flexible, is a bit too much:

```
roles/
   myrole/
      defaults/
          main.yml
      meta/
          main.yml
     tasks/
          main.yml
      handlers/
          main.yml
      templatest/
          ….
      files/
          ….
```

This may very well be justified for larger playbooks, but I would like to propose a leaner alternative that should play along with the above structure:

```
roles/
   myrole/
      defaults.yml
      meta.yml
      tasks.yml
      handlers.yml
      templatest/
          ….
      files/
          ….
```

Basically defaults.yml is the equivalent, and replaces it, to the defaults/main.yml. Later, when the project grows it may naturally evolve into a structure similar to the current one where defaults.yml imports extra defaults located in the defaults/ folder. E.g.:

```
   myrole/
      defaults.yml
      defaults/
          extra1.yml
          extra2.yml
      meta.yml
      meta/
         extra1.yml
      tasks.yml
      tasks/
         extra1.yml
      handlers.yml
      handlers/
          extra1.yml
      templatest/
          ….
      files/
          ….
```

**Comment by jimi-c** [comment]
This has been discussed in the past, however we do not wish to change the folder structure at this time, nor allow all of the files in one folder as we feel it would complicate things unnecessarily. Most people do not use nor require every folder/main.yml to be present. Also, we have a feature request (if not already merged in) to allow multiple vars files to be created in the vars directory, so this would make that detection quite a bit more difficult. 

Thanks for the suggestion though!

**Comment by ydewit** [comment]
That's too bad. Is there another way to override this implicit structure?

**Comment by mpdehaan** [comment]
Nope, you should follow the conventions everyone uses so we have a good
medium of communication.

Ultimately having a short form will cause you to want to migrate to the
long form later.

**Comment by aljungberg** [comment]
+1 for the OP. Over-engineering for theoretical future situations reduces usability. Complexity affects productivity negatively. I think many users are drawn to Ansible for its simplicity, so the explosion of folders and files was a surprise to me.

**Comment by jeffersongirao** [comment]
I agree with @aljungberg, the explosion of folders with small files adds extra complexity plus to having all of them named main.yml turns suboptimal the use of fuzzy finders in text editors. Why not to have a single file with the current standardized sections? If the code grows to the point you need to move to different file a "include"-like statement would work.

**Comment by jirutka** [comment]
+1, I agree with @aljungberg.

**Comment by fadishei** [comment]
I am also disappointed by the way ansible forces a fixed folder structure while sysadmins may like other forms of organization. In fact, the "best practices" title in the docs should be renamed to "the only practice"!

**Comment by wu-lee** [comment]
I agree with the OP, not only is using files as described here conceptually simpler, it is far more convenient for authors. Locating the right edit buffer when every file is called "main.yml" is frustrating.

Whereas the reasons stated here why the convention could not be altered now do not sound very strong. 

Even if "most people do not use nor require every folder/main.yml to be present", then this isn't an argument for making those who do create extra structure. "Following conventions" is well and good, but here the choice of convention could be improved by being simpler and more convenient. It doesn't seem an arduous or radical change to use the proposed vars.yml etc. if they are there, and to choose a precedence rule to resolve the presence of the vars/main.yml and the postulated other files.

**Comment by jimi-c** [comment]
@wu-lee you do not have to have those folders there if they are not being used. The structure the OP posted is only there if you're using every feature of a role including variables, defaults, handlers, etc. If your role is only tasks, you only have to have the `tasks/main.yml` file and nothing else.

**Comment by wu-lee** [comment]
Understood.  However I find I usually _do_ need at least vars, tasks, and templates, frequently meta, handlers and files too.  A role with only one or two of these is a rarity.

**Comment by alexdunae** [comment]
+1 on this, if only to make Cmd+T searching in text editors easier.

**Comment by pakal** [comment]
+1

I came to Ansible seduced by its "fabtools under steroids" feeling (and I still am), but that over-complexity of roles is a huge drawback to me. How do we expect people to browse and reuse existing roles if they're so hard to grok ? It's a noble goal to avoid to creators the pain of, maybe, having to rename some files a day, but in the end we also make the whole stuff obtuse to hoards of potential readers, currently (my Notepad++ or Pydev is just _unusable_ when editing my playbooks).

About none of the numerous roles I've looked at needed so much sophistication ; almost all of them are < 100 lines of codes and would easily fit in a single file, so why go as far as having a separate "handlers/" packages for example (typically 2 to 4 lines per handlers file...) ? If someone needs all that hierarchy of folders, chances are he might separate it into more atomic roles, and link them via dependencies.

Python introduced a very simple-to-explain distinction between modules and packages, to begin little and still grow without hassle, so why not keep the same semantic (ie. /handlers/main.yaml package can, if wanted, be replaced by a mere /handlers.yml file) ? Looks _very_ clear, simple, readable, retrocompatible, and I doubt people would complain about this complementary level of "role architecture".

PS : I posted a message about this on the googlegroup, and it never appeared in the topic, too bad I lost it that way.

**Comment by jefdaj** [comment]
+1 for OP. I find myself having to write scripts to generate the right directory structure, which is more complicated than renaming a few files! I also assumed this feature existed and spent a long time trying to figure out what I was doing wrong because files weren't being found. I think for most people it's the obvious "right" way, and if they get to the point of wanting a more complex structure they'll be fine moving things then.

**Comment by jimi-c** [comment]
@jefdaj, there is no need for a script, the `ansible-galaxy init` command will generate everything for you, as well as create all of the correct YAML files.

Since we have previously stated that we have no plans to change the directory structure, we are locking this issue. If anyone has any further questions in regard to this, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you!
