### ISSUE TITLE
Ansible python error related to unicode?

### ISSUE THREAD

**Issue by jerrac** [ansible/ansible#4361]
I keep getting an odd error when trying to configure my php.ini template.

It ends with:

> UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 68552: ordinal not in range(128)

I've posted the code that causes this at: https://gist.github.com/jerrac/0fb97c4477b7611d0ad6

The error does not happen if I comment out the php_overrides vars. 

As far as I can tell, I'm saving the files as plain text. I use Sublime Text.

Any suggestions?

ansible --version
ansible 1.3.0

**Comment by tsailiming** [comment]
I had the same problem with 1.3.2 except that if I comment out the `only_if: is_set(‘${config_client}’}`, it will work.

And I have a host_var for that hosts.

**Comment by jctanner** [comment]
David, I can not reproduce this issue with the current devel code. Have you tried your test with a current checkout?

**Comment by jerrac** [comment]
@jctanner I'm not a python guy, so I haven't tried running the devel code. I'm just using what's in the ansible repo. Can you checkout the 1.3.0 code? Or the 1.3.2 code. I'm on a different computer that has that version of ansible installed, and I get the same error.

If you can't, how would I install the devel version of ansible? Preferably in a way that can be replaced by the next release from the repo...

**Comment by jctanner** [comment]
I verified that all 1.3.x releases still have this bug. This is the commit that appears to have fixed the bug: https://github.com/ansible/ansible/commit/fd101dd2

**Comment by jerrac** [comment]
@jctanner Thanks for verifying it. Any idea when that bugfix will get into the repos?

**Comment by jctanner** [comment]
We are on a 2 month release schedule for major releases, so I think we are going to push 1.4 out sometime\* around the end of this month (October). 1.3 was released 24 days ago.

If you have interest in running from a checkout, here's the doc: http://www.ansibleworks.com/docs/intro_installation.html#running-from-source

**Comment by mgcrea** [comment]
Still got this bug using latest devel. Any workaround available?

**Comment by mgcrea** [comment]
Error is related to an hidden utf8 char in the default apache2 php.ini (on ubuntu 12.04).

> ; XSL_SECPREF_CREATE_DIRECTORY | XSL_SECPREF_WRITE_NETWORK | XSL_SECPREF_WRITE_FILE = 44

Problematic char is after the second pipe.

**Comment by jerrac** [comment]
@mgcrea Thanks! I thought there must be some weird character in there, but was not able to find it. How did you find it?

**Comment by mgcrea** [comment]
Had to [divide & conquer](http://en.wikipedia.org/wiki/Divide_and_conquer_algorithm) ;-).

**Comment by copperlight** [comment]
I ran into this as well.  Here is a technique for finding invisible unicode characters, using Gnu grep on OSX:

```
brew tap homebrew/dupes
brew install grep
ggrep --color='auto' -P -n "[\x80-\xFF]" file.xml
```

Output will look like this:

```
75: ?? ??<encoder>
76: ?? ??  <pattern>%date %message%n</pattern>
77: ?? ??  <immediateFlush>true</immediateFlush>
78: ?? ??</encoder>
```
