### ISSUE TITLE
ansible role dependencies + absolute path issue

### ISSUE THREAD

**Issue by darkone23** [ansible/ansible#4363]
There is a bug when you include a role by absolute path and that role depends on a relative role. The relative role is searched for relative to the including playbook rather than relative to the role that declared the dependency.

I have created an example case here:

https://github.com/eggsby/ansible-weirdness/tree/role-bug

There are two projects, project a, where the roles live, and project b, which wants to use a role from project a.

Project a has a role which includes a role "a", this role depends on another role "b".  It works as expected within a single project, since the search path can find "b" by name when it is included.

If project b depends on a role from project a by absolute path, and that role has a dependency local to project a, it won't be found since it is not local to project b.

Note: in the example the "absolute path" uses the lookup for PWD.  This works as expected and is required to demonstrate the absolute path issue in a portable way, but feel free to change it to the absolute location of your checkout in order to verify.

**Comment by darkone23** [comment]
In a refactor I have proposed to the way role paths are found (pull request #4278), ansible iterates over a list of possible directories that may contain the role. As a solution for this issue we can push and pop a different list of 'search paths' for the role dependencies (in this case, making it search relative to the role depended on).

Thanks,
-- Thomas Omans

**Comment by jctanner** [comment]
@eggsby I'm closing this since it looks like your merged PR #4278 solves this issue. Please correct me if I misunderstood.
