### ISSUE TITLE
Make stdout_callback in cfg take more than one input

### ISSUE THREAD

**Issue by ganchandrasekaran** [ansible/ansible#43697]
##### SUMMARY

At the moment stdout_callback in the cfg file can take in only one value. But it would be good to have this produce result with combination of more than one value. For Instance "stdout_callback = selective" prints out only the status for each machine. Where as "stdout_callback = json", prints a lot of value in JSON format along with the status for each machine. If I can specify "stdout_callback = json,selective" then I will see the status of each machine alone in JSON format. 

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.6.2
```

##### STEPS TO REPRODUCE

in the ansible.cfg file
```yaml
stdout_callback = selective, json
```

##### EXPECTED RESULTS

```
{
"stats": {
        "firewall": {
            "changed": 0, 
            "failures": 0, 
            "ok": 1, 
            "skipped": 0, 
            "unreachable": 0
        }, 
        "webServ1": {
            "changed": 0, 
            "failures": 0, 
            "ok": 1, 
            "skipped": 0, 
            "unreachable": 0
        }, 
        "webServ2": {
            "changed": 0, 
            "failures": 0, 
            "ok": 1, 
            "skipped": 0, 
            "unreachable": 0
        }
    }
}
```

##### ACTUAL RESULTS

```
ERROR! Invalid callback for stdout specified: selective,json

```

**Comment by sivel** [comment]
I see the point you are trying to make, but unfortunately callback plugins do not function like you are expecting.

A stdout callback plugin is responsible for the output of data to stdout, so stacking multiple stdout callbacks would simply output info from the multiple stdout callbacks in their own format.  

If you want functionality to change the output of a callback, please submit a feature request for that plugin.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by bcoca** [comment]
@ganchandrasekaran note that you can enable the syslog_json callback (which is not 'stdout' type) and it will run at the same time as other callbacks, you just cannot have more than 1 deal with the main output of Ansible.

**Comment by ganchandrasekaran** [comment]
@sivel As suggested I will submit a feature request for that plugin..  This can be very useful feature for  tools that use Ansible to abstract a layer of automation..

**Comment by bcoca** [comment]
we already have 'stacking' .. those that are 'aggregate' type, but those add additional output and do not take over the main output for ansible. Not sure there is a way to stack stdout ones as they just repeat the same data.
