### ISSUE TITLE
ec2 inventory error - ConfigParser.NoSectionError: No section: 'ec2'

### ISSUE THREAD

**Issue by jbrockett** [ansible/ansible#4369]
I am trying to use the ec2.py inventory file to connect to EC2 and list my hosts.  I got the latest version of ec2.py from github, set my environment variables, and ran "./ec2.py --list" and get the following error:

Traceback (most recent call last):
  File "/Users/me/ansible/ec2.py", line 576, in <module>
    Ec2Inventory()
  File "/Users/me/ansible/ec2.py", line 140, in **init**
    self.read_settings()
  File "/Users/me/ansible/ec2.py", line 192, in read_settings
    configRegions = config.get('ec2', 'regions')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 599, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'ec2'

I am running:
Mac OSX 10.8.5
ansible 1.3.2
python 2.7.2
boto 2.13.3
paramiko 1.12.0
PyYAML 3.10
jinja2 2.7.1

Am I missing something in my config?  Thanks.

**Comment by jbrockett** [comment]
I finally found the issue.  There was a typo in ec2.ini.  I corrected that and now it works.  This issue can be closed.

**Comment by mpdehaan** [comment]
Glad you have it working.

Thanks!

**Comment by harishbsrinivas** [comment]
This message also shows up if you do not have the ec2.ini file in the same directory as the ec2.py inventory script. set EC2_INI_PATH to the location of your file.

**Comment by sholtomaud** [comment]
@jbrockett  What was the typo? I'm having the same error 

```
File "./ec2.py", line 808, in <module>
    Ec2Inventory()
  File "./ec2.py", line 151, in __init__
    self.read_settings()
  File "./ec2.py", line 207, in read_settings
    configRegions = config.get('ec2', 'regions')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'ec2'
```

**Comment by jbrockett** [comment]
It's been so long, that I can't remember the exact issue.  I believe it was something wrong with "region = " parameter.  Use the default ec2.ini file from ansible and try to do "./ec2.py --list"  Make sure you have the most recent versions of ec2.py and ec2.ini and ensure you have set your EC2 environment variables properly.  If that works, then start making changes to ec2.ini one by one to isolate the issue.

**Comment by markmsmith** [comment]
@shotlom I encountered this issue when I had a bad environment variable set for EC2_INI_PATH that I'd forgotten about.  Clearing that and making sure ec2.ini was in the same folder made it work for me.

**Comment by lindes** [comment]
I don't know whether it makes sense to re-open this or not, but I'd like to just point out that even if the ec2 config for the particular situation above was sorted, there's still an outstanding issue with this error message not being particularly helpful... it'd be nice to know which file it was parsing for an ec2 section, for example.  ('ec2.ini', I get... but I didn't know that before finding this issue, and it still would be useful to know the actual pathname(s) being scanned for that...)

**Comment by iamnatalie** [comment]
for me it was wrong location for ec2.ini
needed to be in the same working dir as the script ec2.py
