### ISSUE TITLE
Ansibles mishandles user homedir references (~)

### ISSUE THREAD

**Issue by pfalcon** [ansible/ansible#4372]
Some might argue, but I find it's very convenient, at least for development systems, to deploy stuff into some users' homedirs (including "current user's homedir", as parametrized by ansible_ssh_user hostvar).

And then, using paths like ~/foo and ~user/foo:
1) mosty appears even work;
2) sometimes doesn't, e.g. with sudo=yes ~/ gets resolved to root homedir;
3) sometimes leads to subtle issues, like for example I found that

```
copy: src=files/foo.txt dest=~/bar/
```

always leads to the file being copied, because `self.runner._remote_md5()` returns "1" for ~/bar/foo.txt.

So, there can be 2 solutions perceived:
1. Bother to resolve ~ stuff. Dunno how hard it would be to implement it. But may imagine that it would  definitely be boring. All in all, one might expect that from a high-level tool like Ansible. 
2. Alternatively, quitter's solution of checking absoluteness of (all?) paths and erroring out early to avoid undefined behavior. With a mandatory FAQ entry of "Q: I wanna use my homedir to deploy stuff to, you don't let me, OY? A: You're welcome to. Just define deploy dir explicitly as something like "deploydir: /home/$ansible_ssh_user", then use  $deploydir consistently".

**Comment by pfalcon** [comment]
Btw, looking at `_remote_md5()` it doesn't handle ~ because it does pipes.quote(path) right away. But even that is fixed, it will probably miswork with sudo=yes.

**Comment by jimi-c** [comment]
2) This is not an issue. When you sudo a command, you're running it (by default, if sudo_user is not specified) as root. The expansion is done on the target system as that user, because there is no way to do the expansion before-hand. This is expected behavior and no different that running `sudo ssh somehost 'touch ~/myfile'` or even `ssh somehost 'sudo touch ~/myfile'`. In both of those cases, the file touched would be `/root/myfile`. Note that if you allowed the expansion before the connection, the result would be to expand `~` as the user running the command, which is potentially different frrom the one you're using to connect to the remote.

3) Could be an issue worth investigating.

**Comment by pfalcon** [comment]
> 2) This is not an issue.

Umm, no, it's pretty an issue. When I write something like:

```
  - name: Download Jenkins LTS package
    get_url: url=http://pkg.jenkins-ci.org/debian-stable/binary/jenkins_{{jenkins_version}}_all.deb dest=~/jenkins_{{jenkins_version}}_all.deb
  - name: Install Jenkins
    shell: dpkg -i --skip-same-version ~/jenkins_{{jenkins_version}}_all.deb
    sudo: yes
```

I expect it do exactly what's written, specifically: 1) download a file to my homedir; 2) install that file using dpkg, giving it superuser permission for that action.

Arguing that Ansible does that because `ssh somehost 'sudo touch ~/myfile'` does that is mixing up different levels. Users should not care about such details as how exactly command and parameter users give in action gets wrapped into low-levels shell commands. If they cared, they'd probably use shell right away, but most people using Ansible probably vice-versa migrate from such shell scripts full of low-level details, which obfuscate high-level deployment process. So, it's pretty reasonable of users to expect that Ansible provides context-free resolution rules for action arguments, regardless of environment in which action itself is run.

But as I wrote, fixing that is somewhat boring. One obvious way to deal with that is don't pass -H to sudo. Other might be something like "arg1=~/foo; sudo command $arg1". Any such solution would have some downsides and require somewhat careful handling, why implementing it is "boring". But not doing anything about that (like allowing current behavior) is even more confusing IMHO.

**Comment by bcoca** [comment]
Yes I read this as:  sudo + ~/ implies 'home of the sudoed to user' while
~/ w/o sudo implies home of the user im logging in and running as. I expect
ansible to follow the common convention and not your specific expectation
which seems to deviate from it.

Just my opinion, in the end it matters how ansible developers see it.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by pfalcon** [comment]
@bcoca, two points:

1) You may treat it that way because again you may be mixing up "sudo: yes" flag of Ansible with "sudo" Unix command. Suppose that flag was called "superuser" in Ansible, what would you expect of it - to change resolution context for action arguments?

2) Common convention? You must be kidding me. Watch this:

```
pfalcon@x34f:~/projects-3rdparty/ansible$ sudo ls -ld ~
drwxr-xr-x 205 pfalcon pfalcon 12288 Oct  4 19:40 /home/pfalcon
```

and even this:

```
pfalcon@x34f:~/projects-3rdparty/ansible$ sudo bash -c 'ls -ld ~'
drwxr-xr-x 205 pfalcon pfalcon 12288 Oct  4 19:40 /home/pfalcon
```

And only this behaves differently, but I explicitly gave it -H for that!:

```
pfalcon@x34f:~/projects-3rdparty/ansible$ sudo -H bash -c "ls -ld ~"
drwx------ 24 root root 4096 Mar 23  2013 /root
```

That's Ubuntu 12.04 stock, and definitely Debian stock then.

So, tell me about common conventions...

**Comment by jimi-c** [comment]
Your first example happens because the ~ is interpreted by bash before it is sent through to the command. The next two are the opposite of what I would expect, and not what happens on stock Fedora:

<pre>
$ sudo bash -c 'ls -ld ~'
dr-xr-x---. 31 root root 4096 Oct  1 15:52 /root
$ sudo bash -c "ls -ld ~"
dr-xr-x---. 31 root root 4096 Oct  1 15:52 /root
$ sudo -H bash -c "ls -ld ~"
dr-xr-x---. 31 root root 4096 Oct  1 15:52 /root
</pre>

I actually would have expected the double-quoted one to work as follows:

<pre>
$ sudo bash -c "ls -ld $HOME"
drwx--x---+ 52 jamesc jamesc 4096 Sep 29 22:39 /home/jamesc
</pre>

But regardless, when you run a command in ansible as a different user via sudo, things will be executed and created as that user.

**Comment by jimi-c** [comment]
And @bcoca is not mixing up the flag, "sudo: yes" means to run the command via sudo, not some generic "superuser". The commands are actually run via sudo. You can use different users via sudo besides root (people do this all the time with Ansible), and changing things to follow your logic would mean breaking a LOT of others playbooks.

**Comment by mpdehaan** [comment]
agree with the above, OS handling should win here and when needed you should be specific about what you want.

**Comment by pfalcon** [comment]
> But regardless, when you run a command in ansible as a different user via sudo, things will be executed and created as that user.

Ok, is this documented somewhere? IMHO, this is worth even FAQ entry, because this doesn't work how interactive shell / shell script works, and this _is_ confusing.

> would mean breaking a LOT of others playbooks.

Just curious, any pointers for that?

**Comment by pfalcon** [comment]
> agree with the above, OS handling should win here and when needed you should be specific about what you want.

Oh, one of famous @mpdehaan's rulings ;-). Again, OS handling is that script of:

```
wget http://pkg.jenkins-ci.org/debian-stable/binary/jenkins_1.509.3_all.deb -O ~/j.deb
sudo dpkg -i ~/j.deb
```

Works in DWIM manner even if scp'ed remotely and run via ssh. So, Ansible's behavior (triggered by layers of indirections and quotings) is not obvious and worth being well documented, including in FAQ.

And what about case 3 in the original bug description - it's also "OS handling"?

**Comment by igormukhingmailcom** [comment]
Hi, guys.

This is how I dealing with that behaviour:

```
    - name: Create the SSH public key file
      copy:
        src: "files/keys/id_rsa.pub"
        dest: "~/.ssh/id_rsa.pub"
        mode: 0644
      sudo_user: "{{ ansible_ssh_user }}"

    - name: Create the SSH private key file
      copy:
        src: "files/keys/id_rsa"
        dest: "~/.ssh/id_rsa"
        mode: 0600
      sudo_user: "{{ ansible_ssh_user }}"
```

Without `sudo_user: "{{ ansible_ssh_user }}"` I see `msg: Destination directory /root/.ssh does not exist` during `vagrant provision`.

```
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # ...
    config.vm.provision :ansible do |ansible|
        ansible.playbook = '../playbook.yml'
        ansible.extra_vars = {
            ansible_ssh_user: 'vagrant',
            vagrant: true
        }
    end
end
```
