### ISSUE TITLE
Allow empty and non existing vars_files

### ISSUE THREAD

**Issue by prune998** [ansible/ansible#4374]
I would like to report a feature need.

In my playbooks, I load vars_files depending on variables I set on the command line.
Ex :

ansible-playbook playbooks/toto.yml -e "type=frontend place=uat"

Playbook is like :

  vars_files:
    - "vars/{{ type }}.yml" # load type specific vars (frontend, contribution or webservice)
    - "vars/{{ place }}.yml" # load place specific vars (production, uat, review)
    - "vars/{{ type }}-{{ place }}.yml" # load the most specific vars, like TCP ports

Sometimes the var file does not exists and lead to an playbook error.
The only trick I found from the doc was using a "default" vars file as : 

  vars_files:
    - ["vars/{{ type }}.yml", "vars/default.yml"] # load type specific vars (frontend, contribution or webservice)
    - ["vars/{{ place }}.yml", "vars/default.yml"] # load place specific vars (production, uat, review)
    - ["vars/{{ type }}-{{ place }}.yml", "vars/default.yml"] # load the most specific vars, like TCP ports

In this situation, the vars/default.yml HAVE TO be a real yml file WITH at least one variable defined.
Also, the playbook will fail if the vars_file is empty, which is not the case if we call the file without a default.

Would it be possible to either : 
- allow an empty string ("") to be set instead of a file (vars/default.yml)
- allow the var file to be skipped if it is the only one in the list and not present, like :
  - ["vars/{{ type }}-{{ place }}.yml"]

Thanks.

**Comment by mpdehaan** [comment]
This is not something I would like to implement because the detection of a missing file is important.

However, you can have an empty yaml document defining a zero-length hash and will be ok.

```
 {}
```

etc

**Comment by prune998** [comment]
ok thanks
