### ISSUE TITLE
ansible-2.6.x.tar.gz doesn’t contains correct file of ansible_release.py.

### ISSUE THREAD

**Issue by susumuf** [ansible/ansible#43759]
##### SUMMARY

Released binaries v2.6.x(0,1 and latest) of tar.gz doesn’t match a file of zip. It makes error pip3 install ansible under windows.
A way reproduce as below;
> pip3 install ansible
    creating build\lib\ansible\module_utils
    copying lib\ansible\module_utils\acme.py -> build\lib\ansible\module_utils
    error: can't copy 'lib\ansible\module_utils\ansible_release.py': doesn't exist or not a regular file

ansible-2.6.x.tar.gz contains ansible_release.py. but it is Zero byte. Archived released of github are same case.
On the other hand archived Zip release of github contains Not Zero bytes.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
v2.6.x
```

##### CONFIGURATION

Not installed yet.

##### OS / ENVIRONMENT

Windows10

##### STEPS TO REPRODUCE

```yaml
pip3 install ansible
```

##### EXPECTED RESULTS

n/a

##### ACTUAL RESULTS

Just fail

```
python-3.6.5-amd64.exe /passive InstallAllUsers=1 PrependPath=1 Include_test=0 TargetDir=c:\\Python\\Python36
pip3 install ansible
    …
    creating build\lib\ansible\module_utils
    copying lib\ansible\module_utils\acme.py -> build\lib\ansible\module_utils
    error: can't copy 'lib\ansible\module_utils\ansible_release.py': doesn't exist or not a regular file
```

**Comment by sivel** [comment]
We do not support installing ansible on a Windows host.  Ansible can only be installed on a linux/unix like operating system.

https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#control-machine-requirements

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by 2ps** [comment]
@sivel :  with all due respect, windows users like myself and the original poster here understand that we can't use windows as a control machine  But we do develop on windows which means that we have editors, IDEs, etc., that work better when we can actually install ansible on windows.  Installing with pip worked as late as version 2.5.6.  Is there any way that we can move this up to at least a low priority issue?
