### ISSUE TITLE
Why isn't there a list comprehension filter?

### ISSUE THREAD

**Issue by NikiSchlifke** [ansible/ansible#43778]
##### SUMMARY
It always strikes me as weird when I have to learn about several different unique (to ansible) methods for manipulated sequential and structured data, when living in the python ecosystem we don't need that.
I get that there probably are security concerns about ust passing it through to the python interpreter, but would a simple validator suffice to make it secure?
Is there another reason why it is not included I am unaware of?
##### ISSUE TYPE
- simple example of how I think the syntax could look like.
```
"{{[ 'www'+ domain for domain in [test.com, aaa.net]}}"
```
##### COMPONENT NAME
simply list_comprehension in the filters.
If above syntax isn't acceptable perhaps use the function call syntax instead of square brackets.

**Comment by sivel** [comment]
That functionality, the lexer for templating, is handled by an external library called jinja2.

jinja2 does not provide that functionality, largely to prevent people from trying to use the templating language as a full programming language.

However, that functionality can be achieved using:

```
"{{['test.com', 'aaa.net']|map('regex_replace', '(.*)', 'www.\\1')|list }}"
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by NikiSchlifke** [comment]
Thanks I'll ask in IRC. Of course it would be a jinja2 extension of which ansible already has a bunch of it's own additional filters.
To argue for it, ansible's use of jinja2 isn't strictly it's original use case since we use jinja2 syntax inside our playbook/role/task YAML - inside strings.
This is rather specific and does away with the practicality of using the file structure of the template for things like loops, conditionals, etc.
