### ISSUE TITLE
ansible hangs when cloning git repo if using sudo or sudo_user

### ISSUE THREAD

**Issue by zt9** [ansible/ansible#4378]
I am using ansible 1.3.2.

_Local Machine_: [macbook] Darwin sh.local 12.4.0 Darwin Kernel Version 12.4.0: Wed May  1 17:57:12 PDT 2013; root:xnu-2050.24.15~1/RELEASE_X86_64 x86_64
_Local OS_: OS X 10.8.4

_Remote Machine_: [vps cloud] - Linux 3.2.0-53-virtual #81-Ubuntu SMP Thu Aug 22 21:21:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
*Remote OS: Ubuntu 12.04 LTS 

_Steps to reproduce problem_

I have ssh agent forwarding working correctly on my local machine such that the following does _not_ have a problem..

```
ansible all -a 'ssh -T git@github.com'
```

The following task just hangs:

```
  - name: myapp | clone git
     git: repo=git@github.com:kennethreitz/python-guide.git dest=/home/bob/pythonguide
     sudo: true
```

Debug output gives me:

```
<testappt.myap.com> ESTABLISH CONNECTION FOR USER: bob
<testappt.myap.com> EXEC ['ssh', '-tt', '-vvv', '-o', 'ForwardAgent=yes', '-o', 'Port=2197', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'testappt.myap.com', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1381007086.9-126776159136313 && chmod a+rx $HOME/.ansible/tmp/ansible-1381007086.9-126776159136313 && echo $HOME/.ansible/tmp/ansible-1381007086.9-126776159136313'"]
<testappt.myap.com> REMOTE_MODULE git repo=git@github.com:kennethreitz/python-guide.git dest=/home/bob/myap
<testappt.myap.com> PUT /var/folders/xz/6mcpwtdj6zj3wdf1pm6vb5kpd80000gn/T/tmplcrg4c TO /home/bob/.ansible/tmp/ansible-1381007086.9-126776159136313/git
<testappt.myap.com> EXEC ['ssh', '-tt', '-vvv', '-o', 'ForwardAgent=yes', '-o', 'Port=2197', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'testappt.myap.com', '/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=exclxhfuikrdvqfwemnksdflqrkezaunkjz] password: " -u root /bin/sh -c \'"\'"\'/usr/bin/python /home/bob/.ansible/tmp/ansible-1381007086.9-126776159136313/git; rm -rf /home/bob/.ansible/tmp/ansible-1381007086.9-126776159136313/ >/dev/null 2>&1\'"\'"\'\'']
```

The following has the same problem:

```
  - name: myapp | clone git
     git: repo=git@github.com:kennethreitz/python-guide.git dest=/home/bob/pythonguide
     sudo: true
     sudo_user: martin
```

However, the following works properly:

```
  - name: myapp | clone git
     git: repo=git@github.com:kennethreitz/python-guide.git dest=/home/bob/pythonguide
```

So it seems like there is a problem forwarding the key over to github when sudo is used. Not sure why it is hanging.

**Comment by mpdehaan** [comment]
You probably need add github to known hosts.

We have an open ticket about adding some more options and stuff to make this easier, but lots of people doing git checkouts.

Stop by the mailing list if you have questions, but I agree it's not immediately clear to users that this is required.

**Comment by sivel** [comment]
This is not an ansible issue but a sudoers configuration on the remote machine.  You need to tell sudo to keep the SSH_AUTH_SOCK environment variable.  If you were to log in manually and run that ssh command via sudo it should fail as well, ruling out ansible.

The following line must appear in /etc/sudoers or in a /etc/sudoers.d/ file:

`Defaults env_keep += "SSH_AUTH_SOCK"`

You can get this added using ansible as well, so just put something like this before your git clone:

``` yaml
- name: Copy /etc/sudoers.d/ssh_auth_sock into place
  copy: content='Defaults env_keep += "SSH_AUTH_SOCK"' dest='/etc/sudoers.d/ssh_auth_sock' validate='visudo -cf %s' owner=root group=root mode=0440
```

Also, and it looks like you have it, but you need to tell ssh to ForwardAgent:

ansible.cfg:

```
[ssh_connection]
ssh_args = -o ForwardAgent=yes
```

**Comment by mpdehaan** [comment]
We definitely _do_ need to add info to the git module about these things, though I'm really hoping we can add easier/nicer ways to do some of this, like being able to pass a deploy key or username/password to the module as well.

Assumed SSH forwarding was already used above, but yep, that too!

**Comment by jeromew** [comment]
sivel,

can you confirm you solution works only for sudo_user=root because root has R/W access to the SSH_AUTH_SOCK file ?

did you do something special to make it work when sudo_user != root ?

**Comment by sivel** [comment]
@jeromew,

That is a good point.  That was not a situation that I had tested.

If I get time I’ll also take a look into that.

**Comment by ghost** [comment]
From a security perspective, ssh agent forwarding is much more attractive than putting usernames/passwords into the configuration management system. 

In some cases (think of a development VM) it may be nice to check out repositories R/W onto (semi-trusted) virtual machine. 

When I talk of semi-trusted, think for example of digital ocean who didn't zero out disk records before reallocating virtual storage to other customers. I am sure that won't be the last example of information leakage from a cloud provider.

**Comment by HelloGrayson** [comment]
Aahh. Stuck on the same thing. Wondering what the best approach is here.

**Comment by ghost** [comment]
AFAIK It is not related to whether you use sudo. 

SSH Agent Forwarding does not currently work with Ansible.

This leaves two options.
- Generate a new keypair on the instance, copy the public key into your Github account, then run the playbooks again, this time they will be able to check out your project. 
- Use HTTPS URLs. Embedding the username and password in the URL, which may be somewhat sub-optimal from a security perspective.

To be perfectly honest I don't think either approach is particularly nice. Both leave your account vulnerable to compromise. 

Another option is to run your playbooks, create a script on the new host (/home/foo/bar.sh) , containing for example:

```
 #!/bin/bash
 git clone git@github.com:/bar/baz.git
 git clone git@github.com:/bar/other_project.git
 git clone git@github.com:/bar/some_other_project.git
```

Then ssh -A <hostname> -c "/home/foo/bar.sh" to check them all out at once. Again, sub-optimal.

**Comment by Jorge-Rodriguez** [comment]
On a somewhat related note that might address this issue, I think the key_file parameter should refer to a local for in the control machine, or at least have the option of specifying it as such.
The way I see it, if I'm setting this parameter is because my got credentials for git on the control machine are not the default rather than residing on the remote machine.
If we're able to set and unlock the identity file this way, sudo would work.

**Comment by mblarsen** [comment]
I'm experiencing a slightly different scenario. In my case I can see files being "checked out" of the repo in the `dest` dir. But it never completes.
1. I've created a user `tiny`
2. I've deployed a _github deploy key_ and put it in `/home/tiny/.ssh/id_rsa.github-TinyAPI`

(since I deploy keys `ForwardAgent=yes` should be necessary, correct?)

My _sudo user_ is `vagrant` and my task to checkout looks like this:

```
    - name: API | Clone git repo
      git: repo=git@github.com:TinyCarrier/TinyAPI.git
           dest=/home/tiny/api/
           accept_hostkey=yes
           force=yes
           key_file=/home/tiny/.ssh/id_rsa.github-TinyAPI
      tags: deploy
```

I've tried running the ansible script that is pushed to the host manually, it ends up asking me for a username:

```
root@api-staging:/home/vagrant/.ansible/tmp/ansible-tmp-1407856080.38-165109807912337# chmod u+x git
root@api-staging:/home/vagrant/.ansible/tmp/ansible-tmp-1407856080.38-165109807912337# ./git repo=git@github.com:TinyCarrier/TinyAPI.git dest=/home/tiny/api accept_hostkey=yes force=yes key_file=/home/tiny/.ssh/id_rsa.github-TinyAPI
Username for 'https://github.com':
```

... and strangely enough it has switched to `https`. I'm clueless. But this might be besides the point. Since `/home/tiny/api` actually contains the cloned repo.

`git clone` is run as sudo from `vagrant` on and into `tiny`-user's home and with it's keys. But since it is sudo it should matter, should it?

Here is the -vvvv output (ip changed to x.x.x.x):

Ansible: 1.7

```
TASK: [API | Clone git repo] **************************************************
<x.x.x.x> ESTABLISH CONNECTION FOR USER: vagrant
<x.x.x.x> REMOTE_MODULE git repo=git@github.com:TinyCarrier/TinyAPI.git dest=/home/tiny/api accept_hostkey=yes force=yes key_file=/home/tiny/.ssh/id_rsa.github-TinyAPI
<x.x.x.x> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/vagrant/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'IdentityFile="/home/vagrant/.ssh/google_compute_engine"', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'x.x.x.x', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1407856080.38-165109807912337 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1407856080.38-165109807912337 && echo $HOME/.ansible/tmp/ansible-tmp-1407856080.38-165109807912337'"]
<x.x.x.x> PUT /tmp/tmpc3aHy7 TO /home/vagrant/.ansible/tmp/ansible-tmp-1407856080.38-165109807912337/git
<x.x.x.x> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/vagrant/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'IdentityFile="/home/vagrant/.ssh/google_compute_engine"', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'x.x.x.x', u'/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=plcsabendfoopazloswchihmndhuknox] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-plcsabendfoopazloswchihmndhuknox; LANG=C LC_CTYPE=C /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1407856080.38-165109807912337/git; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1407856080.38-165109807912337/ >/dev/null 2>&1\'"\'"\'\'']
```

**Comment by mblarsen** [comment]
I figured out the cause of my issue. It has to do that my repo includes a private sub-module on github for which the "main" key does not work. There is a solution for this that involves changing the submodule origin to include a name specified in ssh config. See this SO question http://stackoverflow.com/questions/10608285/permission-denied-error-when-using-github-deploy-keys

**Comment by mblarsen** [comment]
Posted a gist for my solution here: https://gist.github.com/mblarsen/62d2c0451e69a607a66a

**Comment by priyavartk** [comment]
I am also facing similar but strange issue, when I do run my playbook where destination is already cloned ,it gets stuck but when I do fresh (after deleting destination) it works fine. 

In previous case destination was already checked out by another user and I wanted to override that.

**Comment by priyavartk** [comment]
Looking for a solution , I tried all other methods of making entry in known_hosts but I dnt think that was the issue because like I said when I create fresh clone , it has no problem. Only causes this to hang when i already have repo on destination .
