### ISSUE TITLE
Add use_proxy parameter to win_package module

### ISSUE THREAD

**Issue by GitStorm** [ansible/ansible#43818]
##### SUMMARY

The win_package module permits to specify "path" as an URL. It would therefore maybe make sense to add the "use_proxy" parameter (as found in the win_get_url module).

##### ISSUE TYPE
 - Feature Idea

##### ANSIBLE VERSION

ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by jborean93** [comment]
I probably would be against this, the only really why we support a URL is for historical reasons and we can't really remove it. If you need more advanced functions like authentication/proxy/timeout configuration I would suggest using `win_get_url` to download the package beforehand.

**Comment by GitStorm** [comment]
Thanks Jordan. I'll use the approach you suggested then.

**Comment by jborean93** [comment]
While this was not something we wanted to do, with the web request functionality in a module_util we have been able to easily share the same functionality across modules.

This has been implemented wit hhttps://github.com/ansible/ansible/pull/66931.
