### ISSUE TITLE
More output from apt

### ISSUE THREAD

**Issue by uvizhe** [ansible/ansible#4385]
Sometimes apt comes across some difficulties installing packages and reports something like this:

```
The following packages have unmet dependencies:
 foo-package : Depends: bar-package (>= 0.21.18) but 0.21.7 is to be installed
E: Unable to correct problems, you have held broken packages.
```

But only the last line goes to STDERR and regardless of verbosity level ansible-playbook shows only this last line. So it's very hard to understand what has actually happened.

Would be great to include STDOUT in ansible-playbook output at some verbosity level.

**Comment by jctanner** [comment]
@uvizhe I think what you are asking for has been added by 9faaa2b98b9c9843d927179148015b6f92ef285f

Please take a look and open a new ticket with an example playbook if it does not meet your needs.

Thanks!
