### ISSUE TITLE
Feature : add the tag list in the TASK output line

### ISSUE THREAD

**Issue by prune998** [ansible/ansible#4387]
It would be great to have the list of tags of a task added to the output line, something like : 
TASK: [elasticsearch-settings.json] [tag1,tag2,tag3]*************************************
ok: [frontend-2]
ok: [frontend-0]
ok: [frontend-4]
ok: [frontend-1]
ok: [frontend-3]

I know I could add the list of tags in the "name:" section of each task, but why not having it by default ? 

This would enable to restart only the task that failed by using the --tags= on the command line...

**Comment by mpdehaan** [comment]
I believe this clutters up the output and would dislike having this feature.
