### ISSUE TITLE
Add Global Notify Functionality

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#4390]
We should add a way to be able to perform cross play notifications.

Here is an example scenario:

You have an application deployment playbook containing 2 plays.  1 play for your app servers, another for your proxy servers.  Upon the app being updated on the app server, perhaps detected by the git module, notify a task in your proxy play, to flush caches.

I haven't put much thought into the implementation yet.  Per @mpdehaan "best part would be thinking about what the syntax might look like in the playbook"

**Comment by mpdehaan** [comment]
Hi,

We've keeping track of this list but haven't seen any traction here, so are closing this ticket out.  If someone would like to submit a pull request, that would be welcome, and we're still open to it.
