### ISSUE TITLE
role_name variable

### ISSUE THREAD

**Issue by gnat42** [ansible/ansible#4392]
It would be nice to be able test against roles as variables.  I would like to have a template where I can test against what roles a particular playbook is including.

Particularly in the iptables space. Being able to say open ports 80,443 because I included httpd role. Or any other grouping of ports based on inclusion of a role would be awesome.

**Comment by mpdehaan** [comment]
Proposal would be add a "role_names" array that works like group_names.

**Comment by lfrancke** [comment]
+1 `role_names` would be perfect for the exact reasons mentioned.

**Comment by LeonB** [comment]
+1 `role_names` would also be useful with configuring monitoring.

**Comment by jirutka** [comment]
+1, it'll be very helpful.

**Comment by jnv** [comment]
I have a hunch this may lead to tightly coupled roles, especially the usage with Galaxy roles may be problematic. On the other hand, this is probably the most obvious way how to keep roles generic enough for more heterogenous infrastructure—the custom written roles, that is.
:+1:

**Comment by mpdehaan** [comment]
This would be useful for iptables templates for instance, so I believe we should just knock this out.  Labelling as priority.

**Comment by holms** [comment]
Dear @mpdehaan is there's any docs for using this? It's merged 7 month ago, seems to be a nice feature to have. I'm breaking my head in here how to distinct some actions and execute different tasks order in role? This seems to be could be a case. Having when statement which each include is not an option at all, especially when you see tons of skip messages, when you have 300 of them, it's kind of noisy.
