### ISSUE TITLE
Ansibe vault is kicking in without to be needed

### ISSUE THREAD

**Issue by 1001QAdotNET** [ansible/ansible#43936]
##### SUMMARY
Ansible is trying to use vault when there is no need for that
I suspect this is because I have encrypted passwords in a file dropped in the Inventory folder

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.7
```

##### OS / ENVIRONMENT

Ubuntu 18.x
##### STEPS TO REPRODUCE
```
- hosts: myhosts
  gather_facts: False
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      platform: "cisco_ios"
      connection: ssh
      username: minime
      password:whatever
      connection_args:
      ssh_config_file: 'config'
  tasks:
   - name: ntc_show_command
     ntc_show_command:
      template_dir: "/home/minime/ntc-ansible/ntc-templates/templates/"
      command: 'show ip arp'
      provider: "{{ cli }}"
      #template_dir: "/home/minime/ntc-ansible/ntc-templates/templates"
     register: results
   - debug: var=results.response
```

##### ACTUAL RESULTS

```
task path: /home/Minime/Ansible/test2.yml:21
fatal: [mdc101]: FAILED! => {
    "msg": "Attempting to decrypt but no vault secrets found"
}
        to retry, use: --limit @/home/MiniMe/Ansible/test2.retry

```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

This is chicken/egg issue
Ansible  cannot know that the vault isn't needed, if it cannot decrypt the vault to see the variables defined and then compare to those used in the play.

If you don't the vault to always be decrypted, don't put it in inventory, you can use play adjacent group/host_vars or just a vars/ dir and reference them in the plays that use them.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
