### ISSUE TITLE
Cannot install prerelease gems with the gem module

### ISSUE THREAD

**Issue by DavidMikeSimon** [ansible/ansible#4393]
It is not currently possible to install prerelease gems using the gem module; that is to say, there is no equivalent in the gem module to the gem CLI's "--pre" flag.

**Comment by bobzoller** [comment]
See the pull request above, but FYI you can work around it by specifying the prerelease gem version and it will install no problem.  Using scout as an example:

``` yaml
gem: name=scout version=5.8.0.pre state=present
```

**Comment by DavidMikeSimon** [comment]
@bobzoller Thanks much! :+1:

**Comment by mpdehaan** [comment]
I'm closing this ticket as we have a pull request open now that tracks this issue, just to keep github easier to organize.   This ticket can still be found from the other.
