### ISSUE TITLE
try do document what connection plugin is required by each module

### ISSUE THREAD

**Issue by 1001QAdotNET** [ansible/ansible#43934]
##### SUMMARY

try do document what connection plugin is required by each module
I based my work on ssh and suddenly one module required paramiko_ssh and it could not work with something else
##### ISSUE TYPE
bug

##### ANSIBLE VERSION

```
Ansible 2.6 and below
```

##### ACTUAL RESULTS

```

```

**Comment by 1001QAdotNET** [comment]
well I just realized that most of them have "Provider" in the description but not all of them ...
Most of the network modules (which I am interested in) have that but not all the modules have that info

**Comment by sivel** [comment]
Modules do not have a 1 to 1 relationship with connection plugins, and this is on purpose.  The goal is to allow use of whatever connection meets your needs.

As such, there is no way to explicitly document this relationship.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
