### ISSUE TITLE
'Fetch' should check if 'dest' is a directory instead of checking if it has a trailing slash

### ISSUE THREAD

**Issue by jphalip** [ansible/ansible#4399]
When using `flat=yes`, `fetch` checks whether the `dest` value has a trailing `/` to determine whether it's a directory the file should be downloaded to. This is a little flaky as it's easy to forget appending a trailing slash to `dest`, in which case the action will crash with the error "IOError: [Errno 21] Is a directory: u'/path/without/trailing/slash'"

In comparison, the `mv` Unix command (e.g. `mv myfile /path/without/trailing/slash`) recognizes when the destination is a directory and then moves the source file to that directory instead of attempting to rename the source file with the directory's name.

So, I suggest testing whether `dest` is in fact a directory instead of looking for a trailing slash in the value.

Does it make sense and do you agree? If so I'm happy to work on a patch.

**Comment by mpdehaan** [comment]
Sure, that's great.

I'm going to close this as you were going to work on the pull request.

Thanks very much!
