### ISSUE TITLE
Running f5 bigip_pool module

### ISSUE THREAD

**Issue by wingZero21** [ansible/ansible#4400]
Hi,

Just wondering if someone can advise, trying to run one of the example f5 bigip_pool module playbooks.

Comes back with the below, installed bigsuds python stuff, is there anything else needed for this to run?

Details:
playbook details
local_action: >
bigip_pool
server=172.17.0.45
user=testuser
password=test
state=absent
name=POOL
partition=common
host="{{ ansible_default_ipv4["172.22.13.181"] }}"
port=80

Output
ERROR: Syntax Error while loading YAML script, bigip.yml
Note: The error may actually appear before this position: line 3, column 1

bigip_pool
server=172.17.0.45
^

**Comment by mpdehaan** [comment]
If you have questions, please stop by the mailing list.

This is a YAML syntax error, not a bug in Ansible.
