### ISSUE TITLE
timeout parsed as string in ansible.cfg

### ISSUE THREAD

**Issue by evgkrsk** [ansible/ansible#4401]
Very similar, but old (ansible-0.x) issue: https://github.com/ansible/ansible/issues/1371

New (ansible-1.3.2) issue: https://github.com/dominis/ansible-shell/issues/14 that breaks external programs using ansible (ansible-shell in this case).

**Comment by mpdehaan** [comment]
This appears to be fixed already on the development branch

If it's from ansible.cfg it shouldn't be affecting this other project if you comment out the line, not sure if it's using the Runner API or what.

Let me know if you see this on 1.4.X.

**Comment by mpdehaan** [comment]
Here's the relevant line from constants.py:

```
DEFAULT_TIMEOUT           = get_config(p, DEFAULTS, 'timeout',          'ANSIBLE_TIMEOUT',          10,     integer=True)
```

If you have a pull request to fix something specific, I'd also be interested.  You may have a better feeling of what's wrong than what I can glean from the above description.

Thanks!

**Comment by evgkrsk** [comment]
Ok, I will wait for 1.4.x...

**Comment by evgkrsk** [comment]
Seems OK in 1.4.0. Thanks!
