### ISSUE TITLE
[WARNING]: Module invocation had junk after the JSON data

### ISSUE THREAD

**Issue by MaxCCC** [ansible/ansible#44013]
##### SUMMARY

I see the following warning while everything seems to work:
` [WARNING]: Module invocation had junk after the JSON data:   Broadcast message from root@node3.local (Sun 2018-08-12 22:07:03 CEST):    The system is going down for reboot at Sun 2018-08-12 22:08:03`
CEST!
##### ISSUE TYPE
 - don't expect the output

##### ANSIBLE VERSION

```
ansible --version
ansible 2.6.2
  config file = /Users/lorenzvanthillo/.ansible.cfg
  configured module search path = [u'/Users/lorenzvanthillo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jul 23 2018, 21:27:06) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

#### Configuration
```
  - name: restart server
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true
    become: yes
```

```

**Comment by sivel** [comment]
This is just as warning, and per the code where this check exists:

```
        # Trailing junk is uncommon and can point to things the user might
        # want to change.  So print a warning if we find any
```

In your case, as this is not causing any issues, it can be safely ignored.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
