### ISSUE TITLE
docker_container export option 

### ISSUE THREAD

**Issue by sagarpinninti** [ansible/ansible#44080]
##### SUMMARY

docker_container is creating container but it would be nice to have feature to do docker export of same container.
As docker_image have an option to archive similar function in docker_container will be helpful
##### ISSUE TYPE
 - Feature Idea
docker export of container is required
##### ANSIBLE VERSION

```2.6.2

```

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

Need export of container created by docker_container module.
##### ACTUAL RESULTS

```

```

**Comment by felixfontein** [comment]
I don't think this should be part of `docker_container`. A new module, something like `docker_container_export`, would probably be better for this.

For now, I guess you can simply use the `command` module to execute `docker export`.

**Comment by samdoran** [comment]
The `docker_container` module moved to the [community.general](https://github.com/ansible-collections/community.general) collection. If this is still an issue, please open it in that repository.
