### ISSUE TITLE
The get function for the s3 module is not correctly replacing files if the md5sum is different

### ISSUE THREAD

**Issue by mbarrin** [ansible/ansible#4408]
Version: 1.3.1

Expected behaviour: If the md5 of the local file does not match the md5sum of the remote file, the remote file should be pulled down.

Actual behaviour: If the md5 sum of the local file does not match the md5sum of the remote file, an error is thrown, unless overwrite is set to true. And then it will download the file everytime the playbook runs.

Steps:
- Place an object in a s3 bucket
- Have a file with a different md5sum but the same file name locally
- Create a play that uses the s3 module to copy a file
- Run the play
- If overwrite is set to false the following error will be displayed: "msg: WARNING: Checksums do not match. Use overwrite parameter to force download."

**Comment by mpdehaan** [comment]
My notes:
- The "overwrite" parameter should be an alias like force
- Force should work like copy, as a general standard in ansible
- The default for force is "yes"
- It should always overwrite if the md5 sum is different by default
- If force is set to no, it would not overwrite if different

**Comment by jctanner** [comment]
@mbarrin thanks for the report! I've committed a fix in https://github.com/ansible/ansible/commit/c679491ece82fd727a1ac132ffb69645dceb0126
