### ISSUE TITLE
sudo_user parametrization

### ISSUE THREAD

**Issue by jeromew** [ansible/ansible#4411]
Hello,

I am looking for a way to do this at the task level but when I try : 
- name: create sites directory
  file: path=/home/{{ item }}/sites state=directory
  sudo: yes
  sudo_user: "prefix{{ item }}suffix"
  with_items:
  - user1
  - user2

I get the error :
   invalid output was: sudo: unknown user: prefixsuffix

so the templating seems to be done, but without the correct value for {{ item }}.

**Comment by mpdehaan** [comment]
Yep, as commented on the list sudo_user on the task is new and I dont think we expected someone to do this inside a with_items loop.

We can see if it is easily tweakable.

**Comment by jctanner** [comment]
closing per #4425
