### ISSUE TITLE
Template fails changing file owned by nonexistent owner.

### ISSUE THREAD

**Issue by bradobro** [ansible/ansible#442]
Wierd case, but we should catch it.

I had a host were user 1000 owned /etc/hostname, only I had removed that user in a previous play (long story).

I did:

action: template src=templates/hostname.j2 dest=/etc/hostname

And the file module failed looking up user 1000, the previous owner of hostname, in an attempt to change ownership.

**Comment by mpdehaan** [comment]
steps to repro:

```
 ./hacking/test-module ./library/file dest=/tmp/motd owner=nonexistant
```

OUTPUT to stderr that should be caught:

/bin/chown: invalid user: `nonexistant'

**Comment by mpdehaan** [comment]
fixed on devel with a 2>/dev/null

**Comment by bradobro** [comment]
Great, thanks!

On Thu, May 31, 2012 at 10:19 PM, Michael DeHaan <
reply@reply.github.com
