### ISSUE TITLE
Inventory host variable in INI format is not interpreted as a string

### ISSUE THREAD

**Issue by totoroliu** [ansible/ansible#44237]
##### SUMMARY

According to the Note from [Working with Inventory](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#hosts-and-groups),

> Values passed in the INI format using the key=value syntax are not interpreted as Python literal structure (strings, numbers, tuples, lists, dicts, booleans, None), but as a string. 

But if I have an inventory file below:
```
[340-A1-56L-Win]
172.16.181.238 rack_num=56L
```
with playbook:
```yaml
- debug:
    var: rack_num
```
I will have this result:
```
ok: [172.16.181.238] => {
    "rack_num": 56
}
```

If change the value of inventory variable to:
```
[340-A1-56L-Win]
172.16.181.238 rack_num=56_L
or
[340-A1-56L-Win]
172.16.181.238 rack_num=L56L
```
then playbook would show up the same without issue.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/rickliu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 18 2017, 11:31:52) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

None

##### OS / ENVIRONMENT

Ansible running from "Ubuntu 16.04.5 LTS" to manage a "Windows 10" host.

##### STEPS TO REPRODUCE

Inventory:
```
[340-A1-56L-Win]
172.16.181.238 rack_num=56L
```
Playbook:
```yaml
- debug:
    var: rack_num
```

##### EXPECTED RESULTS

```
ok: [172.16.181.238] => {
    "rack_num": 56L
}
```

##### ACTUAL RESULTS

```
ok: [172.16.181.238] => {
    "rack_num": 56
}
```

**Comment by samdoran** [comment]
I am able to duplicate this and found it only is a bug on Python 2. Python 3 works correctly.

```
>
ansible --version; ansible-playbook testlocal.yml -i inventory/hosts
ansible 2.6.2 (detached HEAD c997811f45) last updated 2018/08/16 14:20:15 (GMT -400)
  config file = /Users/sdoran/Projects/Vagrant/Ansible Lab/ansible.cfg
  configured module search path = ['/Users/sdoran/Source/ansible/library']
  ansible python module location = /Users/sdoran/Source/ansible/lib/ansible
  executable location = /Users/sdoran/Source/ansible/bin/ansible
  python version = 3.7.0 (default, Jun 28 2018, 11:03:27) [Clang 9.1.0 (clang-902.0.39.2)]

PLAY [Local testing playbook] ***************************************************************

TASK [debug] ********************************************************************************
ok: [testhost] => {
    "rack_num": "56L"
}

PLAY RECAP **********************************************************************************
testhost                   : ok=1    changed=0    unreachable=0    failed=0
```

```
>
ansible --version; ansible-playbook testlocal.yml -i inventory/hosts
ansible 2.6.2 (detached HEAD c997811f45) last updated 2018/08/16 14:20:15 (GMT -400)
  config file = /Users/sdoran/Projects/Vagrant/Ansible Lab/ansible.cfg
  configured module search path = [u'/Users/sdoran/Source/ansible/library']
  ansible python module location = /Users/sdoran/Source/ansible/lib/ansible
  executable location = /Users/sdoran/Source/ansible/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 05:51:27) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]

PLAY [Local testing playbook] ***************************************************************

TASK [debug] ********************************************************************************
ok: [testhost] => {
    "rack_num": 56
}

PLAY RECAP **********************************************************************************
testhost                   : ok=1    changed=0    unreachable=0    failed=0
```

**Comment by marcjay** [comment]
Ran into this today. Lot of head-scratching as the behaviour directly contradicts what the docs say. Would love to see this fixed, needed an ugly jinja2 format() filter to workaround it

**Comment by sivel** [comment]
This behavior is documented for the ini inventory plugin at: https://docs.ansible.com/ansible/latest/plugins/inventory/ini.html

> Variable values are processed by Python’s ast.literal_eval function (https://docs.python.org/2/library/ast.html#ast.literal_eval) which could cause the value to change in some cases. See the Examples for proper quoting to prevent changes. Another option would be to use the yaml format for inventory source which processes the values correctly.

As such, to prevent Ansible from assuming you meant to define a `long` value, you will need to add additional quoting:

```
rack_num="'56L'"
```

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by marcjay** [comment]
Thanks @sivel - I hadn't seen that. I think that info would also be useful on https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#hosts-and-groups which was what I, and @totoroliu were reading
