### ISSUE TITLE
Fact gathering is NOT ignored when play level tags don't match

### ISSUE THREAD

**Issue by hanxinyu** [ansible/ansible#44251]
##### SUMMARY

Fact gathering is NOT ignored when play level tags don't match.
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.6.2
```

##### CONFIGURATION

```
ansible-config dump --only-changed
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT

CentOS Linux release 7.3.1611 (Core)
##### STEPS TO REPRODUCE

site.yml:

```yaml
- hosts: dpc
  roles:
  - role: dpc
    become: True
  tags:
    - dpc
```
run:
ansible-playbook site.yml -i hosts --tags=abc

##### EXPECTED RESULTS

Expected was that "Gathering Facts" will be ignored.
##### ACTUAL RESULTS

```
PLAY [dpc] **************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************
ok: [10.124.131.128]

PLAY RECAP **************************************************************************************************************************************************************************
10.124.131.128             : ok=1    changed=0    unreachable=0    failed=0   

```

**Comment by samdoran** [comment]
I don't see where fact gathering is disabled anywhere in your config or playbook.

needs_info

**Comment by bcoca** [comment]
fact gathering has an automatic 'always' tag

**Comment by hanxinyu** [comment]
I specify another tag ('abc', not 'dpc') to skip this play, and expect the fact gathering is ignored. How to implement that?
ansible-playbook site.yml -i hosts --tags=abc  --skip-tags=always ?????
But why fact gathering's tag mechanism does not follow the tag mechanism of it's play?

**Comment by bcoca** [comment]
it was a backwards compatibility decision, in 1.x Ansible also ignored tags at play level when dealing with fact gathering. As a workaround i suggest `gather_facts:  '{{ "abc" in ansible_run_tags }}`

**Comment by hanxinyu** [comment]
@bcoca Thanks for your suggestion.
