### ISSUE TITLE
hg module fails with: AttributeError: 'AnsibleModule' object has no attribute 'parames' 

### ISSUE THREAD

**Issue by madsweitling** [ansible/ansible#4430]
_What version of ansible you are using (ansible --version)_
ansible 1.4 (devel 8d16a39af9) last updated 2013/10/10 14:26:52 (GMT +000)

_Steps to reproduce the problem_
Use the 'hg' module in a playbook:

```
- name: Check out "{{ source_hg_rev }}" from "{{ source_hg_url }}" into "{{ project_dir }}"
  hg: repo="{{ source_hg_url }}" revision="{{ source_hg_rev }}" dest="{{ project_dir }}" force=yes
```

_Expected results_
Successful clone or pull from the specified Hg repo.

_Actual results_
ansible-playbook fails with a Python AttributeError:

```
File "/home/ubuntu/.ansible/tmp/ansible-1381412566.16-67695383086670/hg", line 237, in main
    hg_path = module.parames['executable'] or module.get_bin_path('hg', True)
AttributeError: 'AnsibleModule' object has no attribute 'parames'   
```

Seems to be a typo in this line: https://github.com/ansible/ansible/blob/d8c61528db20094f95c3581655a73c54b707fd36/library/source_control/hg#L237

**Comment by mpdehaan** [comment]
oh wow, that's not good :)

Thanks for the heads up!

Should be an easy pull request to fix if you would like to submit one real quick and claim the points!

**Comment by madsweitling** [comment]
I'll get on it :)

**Comment by jimi-c** [comment]
The above PR was merged in to fix this, so closing this issue. Thanks!
