### ISSUE TITLE
EC2_EIP module: Can't associate EIP with VPC instance

### ISSUE THREAD

**Issue by bhutch** [ansible/ansible#4436]
Hello,

When trying to use ec2_eip to allocate and associate an EIP to a VPC instance, I receive the error "You must specify an allocation id when mapping an address to a VPC instance".

Error:

  File "/usr/lib/python2.7/dist-packages/boto/ec2/connection.py", line 1456, in associate_address
    return self.get_status('AssociateAddress', params, verb='POST')
  File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 1096, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>You must specify an allocation id when mapping an address to a VPC instance</Message></Error></Errors>

$ ansible --version
ansible 1.4 (devel c2572b0379) last updated 2013/10/10 10:40:31 (GMT -500)

boto.Version
'2.9.6'

Is this functionality not supported yet for this module, or am I doing something wrong?

Thanks!

**Comment by pas256** [comment]
VPC is not supported by ec2_eip at the point, and I share your pain. I have made some modifications to the EIP module and will be submitting a PR within a week.

**Comment by pas256** [comment]
Yay! Only 1 day over my promise of "within a week"... that's progress right there.
:)

**Comment by jctanner** [comment]
#4593 merged thanks to @pas256. @bhutch please try using the new "in_vpc" parameter.
