### ISSUE TITLE
add_host breaks on commit c2e5f78

### ISSUE THREAD

**Issue by neh** [ansible/ansible#4442]
I'm running ansible from git, commit c2e5f78.

Running a play that uses add_host fails with the message "FATAL: no hosts matched or all hosts have already failed -- aborting" on the first task that applies to the newly added host.

**Comment by mpdehaan** [comment]
yep, we need to invalidate the cache when that happens.

Thanks for the report.

**Comment by mpdehaan** [comment]
Just pushed a fix, let us know if it works for you.

Thanks!

**Comment by neh** [comment]
That works here, thanks Michael.
