### ISSUE TITLE
Feature request: special cleanup tasks that are executed even after a failure

### ISSUE THREAD

**Issue by pauloneves** [ansible/ansible#4443]
I'd like to have special "cleanup tasks". Tasks that should be executed even if a previous task fail. 

It would be a important security enhancement. Imagine this use case: my application database hardcoded user has few permissions: it can't drop or create table. Can't even delete records. But during a playbook, I need to do database migrations, create tables, and optimize the database. The playbook would be like this:

1) Give extra permissions to my user (e.g., updating a .my.cnf mysql user configuration file that specifies a super user and have a cleartext password)
2) migrate database 
3) cleanup task: remove file .my.cnf

The step 3 would be executed even if the step 2 fails, leaving my super user password disclosed for the minimum time necessary).

I image it as a finally clause of a exception, something to clean after the processing. Like a test tear down method.

**Comment by jimi-c** [comment]
Sure, I could definitely see this being useful. Taking it even further, we could make this very similar to try/except/finally in that we could have an on_error: block that was only executed when a task failed, for instance to rollback changes. The finally: block would always be run at the end, no matter what.

**Comment by nicolai86** [comment]
This sounds like a really interesting feature, especially when using ansible for deployment. 

Is there a timeline or conception for this feature? And while it's not directly possible: are there any workarounds available which lead to the same or a similar result?

**Comment by bcoca** [comment]
This would be a nice extension to handlers:

run_when: successful (default and current behaviour)|errored|always

**Comment by resmo** [comment]
+1
also think about there is a `always_run` in task when running in check mode http://docs.ansible.com/playbooks_checkmode.html
so suggesting `always_run` should become `run_when: checked`

**Comment by mpdehaan** [comment]
We've keeping track of this list but haven't seen any traction here, so are closing this ticket out.  If someone would like to submit a pull request, that would be welcome, and we're still open to it.

**Comment by pauloneves** [comment]
Shouldn't the feature request stay in a queue to be prioritized someday? I accept an answer like: "we won't implement because this and that", but "no traction here" doesn't like a good motive. Other people like this feature requeste.

**Comment by jctanner** [comment]
@pauloneves we do have https://github.com/ansible/ansible/issues/4777 still open, which requests the same behavior.

**Comment by youngJeezy858** [comment]
Can this be revived?  I'd like this very much pls

**Comment by bcoca** [comment]
closing this thread to comments as the new v2  engine will allow for try/except/finally logic in blocks of tasks
