### ISSUE TITLE
mysql_user module does not recognize 'login_port' parameter

### ISSUE THREAD

**Issue by sperantus** [ansible/ansible#4444]
**Ansible version**
ansible 1.3.2

**Expected result**
Setting login_port parameter for mysql_user works as specified in the documentation

**Actual result**
The task fails with the message:

```
msg: unsupported parameter for module: login_port
```

If login_port is removed then the task succeeds.

**How to reproduce**
Run the following playbook:

<pre>

---
- hosts: vagrant
  sudo: yes
  sudo_user: tracpoint

  tasks:
  - name: "Create database grants for new databases"
    mysql_user: >
                login_host=localhost
                login_user=root
                login_password=somerootpasswd
                login_port=3306
                name=someuser
                password=someuserpasswd
                priv=mydb.*:ALL
                state=present
</pre>

**Comment by mpdehaan** [comment]
This parameter was added in 1.4 and someone failed to tag the parameter as new in 1.4.

Sorry about that.

Filing this as a docs ticket.

https://github.com/ansible/ansible/blob/devel/library/database/mysql_user

**Comment by mpdehaan** [comment]
documentation has been updated and this will appear in the next push.

**Comment by sperantus** [comment]
Good to know - thank you! Overall Congrats for the great work - Ansible has been a relief for us - we are migrating from Chef and so far we haven't hit any walls and saved a lot of time in debugging issues.
