### ISSUE TITLE
Use env command in shebang instead of python

### ISSUE THREAD

**Issue by schtibe** [ansible/ansible#4451]
I wanted to do some module testing. Unfortunately, although I set up a virtualenv, the modules were run by Python 3 instead of 2.

The reason for that is the shebang, which is `#!/usr/bin/python`  pretty much everywhere in the code. When changed to `#!/usr/bin/env python`, the correct python binary from the virtualenv is executed.

Is there a reason this shebang is used? Otherwise I think it should be changed to the 'env-version'.

**Comment by mpdehaan** [comment]
You need to read up on ansible_python_interpreter in the docs.

This is fully controllable.

Long story short -- not having to trust the user path and not assuming python is named python!

**Comment by claco** [comment]
This does bring up a point though, which is that while surfing through all of the code in all of the library modules, it's pretty inconsistent. Some are bin python, some are bin python -tt, some are env python, etc.

Same goes now for the ansible magic line at the bottom of modules vs the new imports.

Any thought about cleaning all of these up en masse? I'd be happy to take a crack at it.
