### ISSUE TITLE
Config load priority places ~/.ansible.cfg above <playbook dir>/ansible.cfg

### ISSUE THREAD

**Issue by pschwartz** [ansible/ansible#4452]
Ansible version: 1.3.3

Actions to repeat:
    Create ~/.ansible.cfg
    Create <playbook dir>/ansible.cfg with different options then ~/.ansible.cfg
    Attempt to run the playbook to see which config file options are run.

Currently load_config_file returns configs in this order:
    ~/.ansible.cfg
    <playbook dir>/ansible.cfg
    /etc/ansible/ansible.cfg

The documentation has this as <playbook dir>/ansible.cfg take precedent to ~/.ansible.cfg

**Comment by jimi-c** [comment]
Go ahead and send the PR and I'll get this merged in. Thanks!

**Comment by jimi-c** [comment]
Oops, didn't see it was in already, since it was just referenced from the commit and not a PR. Merged, so closing, thanks!
