### ISSUE TITLE
Deprecated functionality in module_utils/gcp

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#44538]
##### SUMMARY
I am auditing deprecated calls to make sure we are up to date on removals of deprecated functionality and found 2 past due deprecated calls in module_utils/gcp:

```
lib/ansible/module_utils/gcp.py:126:12: ansible-deprecated-version Deprecated version (2.5) found in call to Display.deprecated or AnsibleModule.deprecate
lib/ansible/module_utils/gcp.py:270:12: ansible-deprecated-version Deprecated version (2.5) found in call to Display.deprecated or AnsibleModule.deprecate
```

I am not familiar enough with the `gcp` functionality to remove these myself.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lib/ansible/module_utils/gcp.py

##### ANSIBLE VERSION

```
2.7
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by sivel** [comment]
cc @rambleraptor @erjohnso @supertom

**Comment by sivel** [comment]
cc @ryansb

**Comment by erjohnso** [comment]
See https://github.com/ansible/ansible/pull/44602#issuecomment-416936953
