### ISSUE TITLE
mysql_user can't handle all syntax features of .my.cnf

### ISSUE THREAD

**Issue by jhagg** [ansible/ansible#4454]
When mysql_user tries to read my ~/.my.cnf it chokes on two things:
1. My TAB-indentation
   I like pretty files. :-)
   But I can live without it.
2. Flags without values
   Like 'silent'.
   This I can't live whithout. :-)

Example: .my.cnf

[client]
    password=XXXXXXXXXX
    default-character-set=utf8

[mysql]
    silent

I suspect that the real problem here is the ConfigParser class so
fixing this might be difficult.

A simple workaround would be to be able set the filename instead of
forcing it to ~/.my.cnf.
That could even make this module more flexible. :-)

**Comment by jctanner** [comment]
The cnf file format as you have seen is not quite compliant with the ini spec that configparser wants. 

https://github.com/ansible/ansible/commit/3c4dd618e4a41a116a1043249077c6ca377eeddb is a workaround. Long term, the mysql connection parameter "read_default_file" should be used instead.

**Comment by jctanner** [comment]
Test playbook:

<pre>
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
     DB_DNS : localhost
     DB_USER : "root"
     DB_USER_PASSWORD : "redhat"
  tasks:
    - name: check connection with user+pass
      mysql_user: login_user={{ DB_USER }} 
                  login_password={{ DB_USER_PASSWORD }}
                  name={{ DB_USER }} 
                  password={{ DB_USER_PASSWORD }} 
                  host=% 
                  priv=*.*:ALL 
                  state=present 
                  login_host={{ DB_DNS }}
      ignore_errors: yes
    - name: create a good cnf file
      shell: echo -e "[client]\nuser=root\npassword=redhat" > ~/.my.cnf
      ignore_errors: yes
    - name: check connection with no user ... good cnf
      mysql_user: login_user={{ DB_USER }} 
                  name={{ DB_USER }} 
                  password={{ DB_USER_PASSWORD }} 
                  host=% 
                  priv=*.*:ALL 
                  state=present 
                  login_host={{ DB_DNS }}
      ignore_errors: yes
    - name: check connection with no user or password ... good cnf
      mysql_user: name={{ DB_USER }} 
                  password={{ DB_USER_PASSWORD }} 
                  host=% 
                  priv=*.*:ALL 
                  state=present 
                  login_host={{ DB_DNS }}
      ignore_errors: yes
    - name: create a bad cnf file
      shell: echo -e "[client]\nuser=root\npassword=redhat\nemptyvar" > ~/.my.cnf
      ignore_errors: yes
    - name: check connection with no user or password ... bad cnf
      mysql_user: name={{ DB_USER }} 
                  password={{ DB_USER_PASSWORD }} 
                  host=% 
                  priv=*.*:ALL 
                  state=present 
                  login_host={{ DB_DNS }}
      ignore_errors: yes
</pre>

Results:

<pre>
PLAY [localhost] ************************************************************** 
TASK: [check connection with user+pass] *************************************** 
ok: [localhost] => {"changed": false, "user": "root"}
TASK: [create a good cnf file] ************************************************ 
changed: [localhost] => {"changed": true, "cmd": "echo -e \"[client]\\nuser=root\\npassword=redhat\" > ~/.my.cnf ", "delta": "0:00:00.002659", "end": "2013-10-18 17:41:02.741237", "rc": 0, "start": "2013-10-18 17:41:02.738578", "stderr": "", "stdout": ""}
TASK: [check connection with no user ... good cnf] **************************** 
failed: [localhost] => {"failed": true}
msg: when supplying login arguments, both login_user and login_password must be provided
...ignoring
TASK: [check connection with no user or password ... good cnf] **************** 
ok: [localhost] => {"changed": false, "user": "root"}
TASK: [create a bad cnf file] ************************************************* 
changed: [localhost] => {"changed": true, "cmd": "echo -e \"[client]\\nuser=root\\npassword=redhat\\nemptyvar\" > ~/.my.cnf ", "delta": "0:00:00.002581", "end": "2013-10-18 17:41:02.927619", "rc": 0, "start": "2013-10-18 17:41:02.925038", "stderr": "", "stdout": ""}
TASK: [check connection with no user or password ... bad cnf] ***************** 
ok: [localhost] => {"changed": false, "user": "root"}
PLAY RECAP ******************************************************************** 
localhost                  : ok=6    changed=2    unreachable=0    failed=0   
</pre>
