### ISSUE TITLE
confusing error message:  error 'Private key file is encrypted'

### ISSUE THREAD

**Issue by ludovicc** [ansible/ansible#446]
Hello,

I'm giving a try to the dev version of ansible.
I'm accessing my remote machine with ssh keys, and my keys are in the authorized_keys of the remote machine.

I'm getting this error:

> ansible all -m ping
> web-c1m1d.sys.dev | FAILED => FAILED: Private key file is encrypted

How can I solve it?
Thanks, Ludovic

**Comment by jkleint** [comment]
This comes up a lot.  By default, Ansible tries to ssh as root.  If you add the parameter `-u$USER`, it will ssh as you.

**Comment by mpdehaan** [comment]
it seems we should consider catching the error and making a better error message.   Moving to 0.5

**Comment by mpdehaan** [comment]
error message fixed in devel branch
