### ISSUE TITLE
8fc46a3a dramatically slows down host list processing

### ISSUE THREAD

**Issue by Preston4tw** [ansible/ansible#4460]
8fc46a3a appears to dramatically slow down parsing of the hostfile. I've got 2500 hosts in my hostfile and it's very noticeable. Found the commit with git bisect.

**Comment by mpdehaan** [comment]
Please paste what ansible --version you are running.

There are caching improvements you may not have applied and I need to know.

**Comment by Preston4tw** [comment]
ansible 1.4 (devel 41aaad69aa) last updated 2013/10/11 13:38:11 (GMT -700) on python 2.7.5 on CentOS 5.3 (bleck) x64.

**Comment by Preston4tw** [comment]
For each host it's checking a series of paths, group_vars host_vars both in my homedir as well as cwd it looks like, with the hostname appended .yml or .yaml files and taking ~220ms for each host.

**Comment by jimi-c** [comment]
A recent patch regarding this was just merged in, could you please re-pull and test? Thanks!

**Comment by Preston4tw** [comment]
Still having the issue.

**Comment by mpdehaan** [comment]
that = self.__get_hosts(p) itself is not well cached so I can take a look there.   That would seem to be it.

If you are capable of debugging python and running performance capture data I'd be interested which functions are slowest on your end.

Meanwhile it's not a bad 

Did you have a .yml file for each host ?

**Comment by mpdehaan** [comment]
I've submitted a bit of a blind fix that may help by moving the caching code a bit higher up.

Let me know if this helps or not.  

If it doesn't, I would like to know if you a host file or each host and how you are defining inventory among other things.

(Also 220ms for just a few stats seems a bit high.   Nothing mounted on fuse or crazy slow NFS I hope?)

**Comment by mpdehaan** [comment]
commit is https://github.com/ansible/ansible/commit/1b2d4c328caee8ab399e032b5d3c9ce0fb067120

**Comment by mpdehaan** [comment]
Closing this due to lack of feedback, please let me know by email if you are still having problems and we can investigate.
