### ISSUE TITLE
missing ansible.cfg documentation for "remote_tmp"

### ISSUE THREAD

**Issue by leegarrett** [ansible/ansible#44682]
##### SUMMARY
The documentation for get_url has this excerpt for the tmp_path parameter: "When run on Ansible 2.5 or greater, path defaults to ansible's remote_tmp setting"

However, remote_tmp is not documented:
https://docs.ansible.com/ansible/latest/search.html?q=remote_tmp&check_keywords=yes&area=default#

##### ISSUE TYPE
 - Documentation Report

##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = /home/randall/Coding/gits-playbook/ansible.cfg
  configured module search path = [u'/home/randall/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

This is irrelevant, as it's a documentation issue on https://docs.ansible.com/ansible/latest/reference_appendices/config.html#ansible-configuration-settings
##### OS / ENVIRONMENT

This is irrelevant, as it's a documentation issue on https://docs.ansible.com/ansible/latest/reference_appendices/config.html#ansible-configuration-settings
##### STEPS TO REPRODUCE

Browse to https://docs.ansible.com/ansible/latest/reference_appendices/config.html#ansible-configuration-settings and try to find the setting for remote_tmp

```yaml

```

##### EXPECTED RESULTS

Find some documentation about remote_tmp, where I can set it, what it affects, and what the default is, in https://docs.ansible.com/ansible/latest/reference_appendices/config.html#ansible-configuration-settings

##### ACTUAL RESULTS

Did not find any documentation about it, other than that it can be set in unusual settings.

**Comment by jborean93** [comment]
@leegarrett remote_tmp used to be a global configuration but was moved to be a shell specific config. You can find the documentation for the default shell plugin `sh `[here](https://docs.ansible.com/ansible/latest/plugins/shell/sh.html) and for Windows [here](https://docs.ansible.com/ansible/latest/plugins/shell/powershell.html).
