### ISSUE TITLE
Conditional include order question

### ISSUE THREAD

**Issue by dmac** [ansible/ansible#4469]
If a playbook conditionally includes a task file, and one of the tasks in the included file has a "when" field that uses a variable registered by a previous task, the play fails when the conditional include evaluates to false.

``` yaml

---
# file: playbook.yml
- name: playbook
  hosts: "{{ hosts }}"
  tasks:
    - include: tasks.yml
      when: false # This causes the playbook to fail
```

&nbsp;

``` yaml

---
# file: tasks.yml
- name: register a var
  command: echo "hi"
  register: message

- name: print a var
  debug: msg="{{ message.stdout }}"
  when: message.stdout == "hi"
```

&nbsp;

``` bash
$ ansible-playbook playbook.yml
PLAY [playbook] *************************************************************

GATHERING FACTS ***************************************************************
ok: [hosts]

TASK: [register a var] ********************************************************
skipping: [hosts]

TASK: [print a var] ***********************************************************
fatal: [hosts] => error while evaluating conditional: {% if message.stdout == "hi" %} True {% else %} False {% endif %}

FATAL: all hosts have already failed -- aborting
```

**Comment by MasseGuillaume** [comment]
current workarround

```
---
# file: playbook.yml
- name: playbook
  hosts: "{{ hosts }}"
  tasks:
    - include: tasks.yml message=nope
      when: false # This causes the playbook to fail
```

**Comment by mpdehaan** [comment]
checking this now...

**Comment by mpdehaan** [comment]
I confirmed an ordering issue where the first conditional was evaluated after the second.

I agree this is frustrating and I thought we had the last of these down, but apparently missed one.   Sorry about that!

I do not anticipate we will be doing another dot release on the 1.3 release branches, so you may wish to cherry-pick this commit or choose to run 1.4 (devel) -- which is actually not an uncommon thing to do among those that wish to pick up new features, because there's no installation required on the remotes.

Thanks for the heads up!

**Comment by mpdehaan** [comment]
See what I just pushed a bit to see if this helps any, though some more info on structure of your environment would be useful, this is a bit of a blind attempt.

If you are still seeing things I can use more info to reproduce things in a closer-to-yours setup.

**Comment by dmac** [comment]
Awesome, thanks for the fast turnaround! Works great from devel.

Was that second commit supposed to reference a different issue?

**Comment by hadimc** [comment]
Using Ansible 1.7.1, I see the following behaviour. When:
- there are two roles including the "tasks.yml" file (possibly passing different parameters)
- the first role has a false condition on its include 
- the second role has no condition on its include

then I can see the second role throws the same error as shown above running the task "print a var". Please confirm.

**Comment by coryfklein** [comment]
Ugh, seeing this in 2.0.1:

Given this task conditional:

> when: False and obj.result

I get this error when running the task:

> fatal: [192.168.33.10]: FAILED! => {"failed": true, "msg": "The conditional check 'False and obj.result' failed. The error was: error while evaluating conditional (False and obj.result): 'dict object' has no attribute 'result'

Looks like the conditional is not respecting order of evaluation rules here.
