### ISSUE TITLE
Get 0.4.0 in Fedora/EPEL

### ISSUE THREAD

**Issue by timlnx** [ansible/ansible#447]
Task for me.

**Comment by mpdehaan** [comment]
glad to see you're alive and stuff.

I think there are a few things to pick up so maybe we want to tag 0.4.1 in a week and then do it.

**Comment by timlnx** [comment]
Heh. After the crap going on at work I'm glad I'm alive and stuff too :-)

I'm not against delaying until 0.4.1. Before you tag it though, can you pull in [0](version updates) and run 'make docs'?

[0] https://github.com/tbielawa/ansible/tree/0.4.1

**Comment by mpdehaan** [comment]
"0" linked weird, but send me a pull request and sure.  I'm going to give it a week and make sure we don't get any more fixes in.

**Comment by timlnx** [comment]
May I direct your attention to #466

**Comment by timlnx** [comment]
daniel_hozac on IRC tipped me off to this today:

> <tbielawa>@(deepfryer)[~/Projects/ansible] 9:37:32  (master)
> $ make rpm
> Cleaning up distutils stuff
> rm -rf build
> rm -rf dist
> Cleaning up byte compiled python stuff
> find . -type f -regex "._.py[co]$" -delete
> Cleaning up editor backup files
> find . -type f ( -name "_~" -or -name "#_" ) -delete
> find . -type f ( -name "_.swp" ) -delete
> Cleaning up asciidoc to man transformations and results
> find ./docs/man -type f -name "_.xml" -delete
> find ./docs/man -type f -name "_.asciidoc" -delete
> Cleaning up output from test runs
> rm -rf test/test_data
> Cleaning up RPM building stuff
> rm -rf MANIFEST rpm-build
> Cleaning up Debian building stuff
> rm -rf debian
> rm -rf deb-build
> python setup.py sdist -t MANIFEST.in
> Traceback (most recent call last):
>   File "setup.py", line 11, in <module>
>     from ansible import **version**, **author**
> ImportError: cannot import name **author**
> make: **\* [sdist] Error 1

For the fix I would like to direct your attention to #467.

**Comment by mpdehaan** [comment]
tags for 0.4.1 applied, new tarball uploaded

**Comment by timlnx** [comment]
Official builds for 0.4.1 have been made and tagged into $dist-candidate on koji. Here's the direct download links. Updates will be submitted into fedora admin presently.

f15: http://koji.fedoraproject.org/koji/taskinfo?taskID=4163005

f16: http://koji.fedoraproject.org/koji/taskinfo?taskID=4163004

f17: http://koji.fedoraproject.org/koji/taskinfo?taskID=4163008

f18: http://koji.fedoraproject.org/koji/taskinfo?taskID=4162948

el6: http://koji.fedoraproject.org/koji/taskinfo?taskID=4163009

**Comment by mpdehaan** [comment]
closing ticket
