### ISSUE TITLE
Get error of set ec2 tags

### ISSUE THREAD

**Issue by harrisongu** [ansible/ansible#4472]
Ansible version: 1.2.3
Issue: Using ec2_tags module to set tags for EC2 instances. One tag already exist in my instance, and I tried to run ansible to add new tag for this instance is successful at first time. but I'm get a response error when run this action again. The error shows:

TASK: [set ec2 tags] ********************************
failed: [xx.xx.xx.xx] => {"failed": true, "item": "", "parsed": false}
invalid output was: Traceback (most recent call last):
 File "/home/xxxxx/.ansible/tmp/ansible-1381512428.88-141973985852996/ec2_tag", line 1108, in <module>
   main()
 File "/home/xxxxx/.ansible/tmp/ansible-1381512428.88-141973985852996/ec2_tag", line 190, in main
   tagger = ec2.create_tags(resource, dictadd)
 File "/usr/lib/python2.6/site-packages/boto/ec2/connection.py", line 3265, in create_tags
   return self.get_status('CreateTags', params, verb='POST')
 File "/usr/lib/python2.6/site-packages/boto/connection.py", line 1115, in get_status
   raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>You must specify one or more tags to create</Message></Error></Errors><RequestID>e299dfdb-1225-447d-8fb1-b4f32f8e9b25</RequestID></Response>

I checked the ec2_module python file(/usr/share/ansible/cloud/ec2_tag) found a problem in the following code snippet:

```
if state == 'present':
    if set(tags) == set(tagdict):
        module.exit_json(msg="Tags already match for %s." %resource, changed=False)
    else:
        for (key, value) in set(tags.items()): 
            if (key, value) not in set(tagdict.items()):
                dictadd[key] = value
    tagger = ec2.create_tags(resource, dictadd)
    gettags = ec2.get_all_tags(filters=filters)
    module.exit_json(msg="Tags %s created for resource %s." % (dictadd,resource), changed=True)
```

I want to change to:

```
if state == 'present':
    if set(tags).issubset(set(tagdict)):
        module.exit_json(msg="Tags already exists in %s." %resource, changed=False)
    else:
        for (key, value) in set(tags.items()): 
            if (key, value) not in set(tagdict.items()):
                dictadd[key] = value
    tagger = ec2.create_tags(resource, dictadd)
    gettags = ec2.get_all_tags(filters=filters)
    module.exit_json(msg="Tags %s created for resource %s." % (dictadd,resource), changed=True)
```

Any ideas on this issue?

**Comment by mpdehaan** [comment]
This seems reasonable.

Would you like to submit a pull request?

Thanks!

**Comment by harrisongu** [comment]
Yeah, I've send a pull request, please review. Thanks.

**Comment by mpdehaan** [comment]
closing per above, thank you!
