### ISSUE TITLE
ConfigureRemotingForAnsible.ps1 compatibility with Windows CIS Hardened Image

### ISSUE THREAD

**Issue by ryancabrera** [ansible/ansible#44738]
##### SUMMARY

When attempting to enable remoting for ansible on a CIS hardened image, the default policies prevent the ConfigureRemotingForAnsible.ps1 scripts from running without modifications to the policies. Specifically, it would be nice to modify this script to accommodate CIS hardened AMIs to allow for the enabling/disabling of necessary policies.

##### ISSUE TYPE
 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /Users/ryancabrera/projects/vce/ansible.cfg
  configured module search path = [u'/Users/XXX/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### CONFIGURATION

ANSIBLE_SSH_ARGS(/Users/XXX/projects/XXX/ansible.cfg) = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=10m
ANSIBLE_SSH_CONTROL_PATH(/Users/XXX/projects/XXX/ansible.cfg) = %(directory)s/%%h-%%r
DEFAULT_ASK_VAULT_PASS(/Users/XXX/projects/XXX/ansible.cfg) = True
HOST_KEY_CHECKING(/Users/XXX/projects/XXX/ansible.cfg) = False
##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

Running ConfigureRemotingForAnsible.ps1 with any arguments will fail on CIS Microsoft Windows Server 2012 R2 Benchmark v2.3.0 Level 1 AMI, and will probably fail on other hardened images.

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by jhawkesworth** [comment]
needs_contributor

**Comment by ShachafGoldstein** [comment]
@ryancabrera -  If this is still relevant can you give more info? like an output of a failed run?

**Comment by jborean93** [comment]
This script is not really designed to be the ultimate script for enabling Windows just a simple script for people to test with. Unfortunately to make it compatible with hardened images we would have to change defaults or add numerous switches making it even more complex than it already is. It should be used as inspiration for someone to create their own script that sets up what they require in their environment.
