### ISSUE TITLE
change in behaviour of "when:"

### ISSUE THREAD

**Issue by jcftang** [ansible/ansible#4475]
This ticket follows up on a conversation at...

https://groups.google.com/forum/#!topic/ansible-project/AxgcmrvExJU

I've a sample case of it failing here...

https://github.com/jcftang/vars-failure-evaluation

**Comment by mpdehaan** [comment]
Should be fixed now, see development list for details.

**Comment by jcftang** [comment]
thanks, thats fixed it for me
