### ISSUE TITLE
document "with_lines"

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#4478]
This should be shown in the loops section.

**Comment by mpdehaan** [comment]
done, just not pushed yet

**Comment by SupremeGit** [comment]
IF ITS BEEN DONE, BUT NOT PUSHED, THEN WHERE THE HELL IS IT??

**Comment by SupremeGit** [comment]
3 GODDAMN YEARS AGO
AND IT'S NOT DOCUMENTED.

HOPELESS.

**Comment by SupremeGit** [comment]
IF IT IS NOT DOCUMENTED, THEN IT MIGHT AS WELL NOT EXIST.

REMOVE IT. 
IF YOU"RE NOT GOING TO DOCUMENT IT.

**Comment by jimi-c** [comment]
http://docs.ansible.com/ansible/playbooks_loops.html#iterating-over-the-results-of-a-program-execution
