### ISSUE TITLE
apt_repository module does not do update_cache=yes by default

### ISSUE THREAD

**Issue by DSpeichert** [ansible/ansible#4481]
Documentation on apt_repository module claims update_cache default value is yes. However, it only updates cache when declared explicitly, which means it is not yes by default.

**Comment by mpdehaan** [comment]
Yep, there's already a ticket on this one, it's a docs bug and I'm going to sort that out shortly.

Leaving this open just in case I'm wrong about the duplicate.

**Comment by DSpeichert** [comment]
I believe that in most cases the anticipated solution would be to update the cache when you add/delete apt repository. So I would say it's not the docs bug but module bug.

**Comment by jch-gh** [comment]
I would agree with @DonDaniello.  The addition/deletion of an apt repository almost certainly should imply a cache refresh by default when a repo change occurs.  I'd argue it is going to be a fairly rare situation where you would want to add or remove a repository and wind up with stale entries in your apt cache.

**Comment by bcoca** [comment]
I only see a case for not updating the cache: when adding multiple repos,
in which case cache_update=false is easy enough to add.

**Comment by DSpeichert** [comment]
I don't know if that is technically possible to code in a module right now but adding to what @bcoca said, it would be nice to have apt_repository automatically detect consecutive additions/deletions using apt_repository module and invoke one update at the end of the series.

**Comment by mpdehaan** [comment]
Sorry just now getting to the some of the older docs tickets as we have been chasing bug reports.

Current code is yes by default for apt_repository so I believe this is closable.  Let me know if you disagree.
