### ISSUE TITLE
Accelerated mode does not work with IPv6

### ISSUE THREAD

**Issue by kafeinnet** [ansible/ansible#4485]
Hi,

Acelerated mode daemon listens on 0.0.0.0 and there is no configuration option to change this.

```
root@phoeneeks:/tmp/ruby/ruby-2.0.0-p247# netstat -anptlwee | grep 5099
tcp        0      0 0.0.0.0:5099            0.0.0.0:*               LISTEN      1000       63088       488/python      
```

Maybe you should add a "accelerated_host" to choose the listening IP so we can set it to "::".

Fab.

**Comment by mpdehaan** [comment]
If we did this, I'd probably call it something like "accelerate_ipv6=True/False" and just set it there.   

accelerate_host seems like it would be confusing as the host file is local.

**Comment by kafeinnet** [comment]
Yep, the name is maybe not so clever.
What about accelerate_listen ?

It maybe better not to listen on all IP addresses in certain cases for more security ?
