### ISSUE TITLE
Double quotes are converted to single quotes on variable assignment if contents look like JSON

### ISSUE THREAD

**Issue by emz00** [ansible/ansible#44897]
##### SUMMARY
When I assign a variable containing double quotes to another variable the double quotes (`"`) sometimes get converted to single quotes (`'`). This appears to happen when the variable contents look like valid JSON.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

core

##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = /media/sf_work/lops/ansible/ansible.cfg
  configured module search path = [u'/home/evgeny/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

```
DEFAULT_BECOME(/media/sf_work/lops/ansible/ansible.cfg) = True
DEFAULT_HASH_BEHAVIOUR(/media/sf_work/lops/ansible/ansible.cfg) = merge
DEFAULT_ROLES_PATH(/media/sf_work/lops/ansible/ansible.cfg) = [u'/media/sf_work/lops/ansible/roles']
DEFAULT_TRANSPORT(/media/sf_work/lops/ansible/ansible.cfg) = smart
DEFAULT_VAULT_PASSWORD_FILE(/media/sf_work/lops/ansible/ansible.cfg) = /home/evgeny/.ansible/password
RETRY_FILES_ENABLED(/media/sf_work/lops/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Linux Mint 19 Tara

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  connection: local
  gather_facts: false

  vars:
    plain_text: '{"double": "quotes"'
    plain_text_again: "{{ plain_text }}"
    maybe_json: '{"double": "quotes"}'
    maybe_json_again: "{{ maybe_json }}"

  tasks:
    - debug:
        msg: "plain_text = {{ plain_text }}, again = {{ plain_text_again }}"
    - debug:
        msg: "maybe_json = {{ maybe_json }}, again = {{ maybe_json_again }}"
```

##### EXPECTED RESULTS

```
    "msg": "plain_text = {\"double\": \"quotes\", again = {\"double\": \"quotes\""
    "msg": "maybe_json = {\"double\": \"quotes\"}, again = {\"double\": \"quotes\"}"
```

##### ACTUAL RESULTS

```
    "msg": "plain_text = {\"double\": \"quotes\", again = {\"double\": \"quotes\""
    "msg": "maybe_json = {\"double\": \"quotes\"}, again = {'double': 'quotes'}"
```

**Comment by sivel** [comment]
This is a known issue, and related to the interaction between Ansible and Jinja2.  Jinja2 has historically only allowed returning strings, so we have some code to attempt to convert things that look like python data structures, into actual python data structures.

We have merged a new feature (that is toggled off by default for now) to utilize new Jinja2 native types.

When enabled, this problem will not occur.

This feature will be included in the upcoming 2.7 release of Ansible, and you can find more information about it at: https://docs.ansible.com/ansible/devel/reference_appendices/config.html#default-jinja2-native

If you are interested in a more verbose explanation of what is happening, see https://github.com/ansible/ansible/issues/34595#issuecomment-356091161

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
