### ISSUE TITLE
service: name=supervisor state=reloaded does not work

### ISSUE THREAD

**Issue by iivvoo** [ansible/ansible#4494]
A supervisor handler for reloading the configuration does not work,

```
handlers:
- name: reload supervisor
  service: name=supervisor state=reloaded
```

will result in

```
failed: [vagrant-vps02] => {"failed": true}
msg: Usage: /etc/init.d/supervisord {start|stop|restart|force-reload|status|force-stop}
```

**Comment by mpdehaan** [comment]
Information about your OS and ansible version is required.

Please provide steps to reproduce this problem per contributing.md.

**Comment by jarv** [comment]
I have reproduced this on ubuntu 12.04 using the sysV init script that comes with the supervisor package, ansible 1.4.
May want to consider the proposal in https://github.com/ansible/ansible/issues/4495 or allowing force-reload as a valid state option. Any preference?

**Comment by iivvoo** [comment]
This is with ansible 1.2.3 on a pristine "precise32" vagrant box, ubuntu 12.04 with updates.

**Comment by mpdehaan** [comment]
So interestingly enough restarting supervisor on Ubuntu is just a problem in general, in Ubuntu 12.04 you have to stop it, sleep, and restart it.

I suspect this is just an issue with the init script and not Ansible.

**Comment by mpdehaan** [comment]
In fact, yes, it doesn't support "reloaded" per the output from the service binary, you would just use the shell command in this case.

Open to the idea of the other ticket of course!

**Comment by anoopksreyas** [comment]
Try sudo supervisorctl -c /etc/supervisord/supervisord.conf restart <process_name>

**Comment by shiplu** [comment]
the command line tool `supervisorctl` supports a sub command `reload`. But ansible doesn't support it. 
Then how can we reload supervisor config files?

**Comment by anoopksreyas** [comment]
If I'm not wrong, You can create an ansible task to run the restart command.

**Comment by shiplu** [comment]
@anoopksreyas  `restart` and `reload` are not same.  `reload` restarts the supervisor daemon while `restart` restarts the underlying process.

**Comment by anoopksreyas** [comment]
Then you need to stop first and start it again. Will that answer your query?

**Comment by jeffwidman** [comment]
This should be re-opened but filed as a feature request, not a bug. And filed against the [`ansible-modules-core`](https://github.com/ansible/ansible-modules-core/) repo, not the main ansible repo.

Looks like there's already an open PR: 
https://github.com/ansible/ansible-modules-core/pull/3755

**Comment by lhoss** [comment]
I've got the *exact* same problem with the `rsyslog` service, when trying state `reloaded` which yields to a failure (also because it doesn't support `reload` but `force-reload`) !
A real pity to have to fall back to use the shell/cmd module (with all related disadvantages)

A nice enough solution IMO would be to finally implement a `service`module feature to give custom state values, long time requested in https://github.com/ansible/ansible-modules-core/issues/1616

**Comment by robario** [comment]
@mpdehaan 
In LSB5, `reload` action is optional.
> https://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html
> The start, stop, restart, force-reload, and status actions shall be supported by all init scripts; the reload and the try-restart actions are optional.
> force-reload | cause the configuration to be reloaded if the service supports this, otherwise restart the service if it is running

I suspect this is just an issue with the Ansible and not init script.
Ansible should run `service foo force-reload` when `service: name=foo state=reloaded`.
