### ISSUE TITLE
want to ask supervisor to be able to reload/update supervisor

### ISSUE THREAD

**Issue by iivvoo** [ansible/ansible#4495]
the supervisorctl module requires a name= argument to specify the configuration to work on. 

But supervisorctl can also manage the supervisor process itself: reload, restart, update. 

Since the mode of operation of the service module in combination with supervisor is very limited, it would be useful if these operations could be executed through the supervisorctl module (in stead of a shell module)

**Comment by mpdehaan** [comment]
We've keeping track of this list but haven't seen any traction here, so are closing this ticket out.  If someone would like to submit a pull request, that would be welcome, and we're still open to it.
