### ISSUE TITLE
Ansible 1.4 rhn_register module not working with RHEL 5

### ISSUE THREAD

**Issue by beuker81** [ansible/ansible#4496]
I have a playbook registering a system to satellite. If I run this playbook I get:

fatal: [euphrates.ict.domain.nl] => failed to parse: 
Traceback (most recent call last):
  File "/home/jurrien/.ansible/tmp/ansible-1381755089.64-208400602114918/rhn_register", line 1314, in ?
    main()
  File "/home/jurrien/.ansible/tmp/ansible-1381755089.64-208400602114918/rhn_register", line 358, in main
    rhn.register(module.params['enable_eus'] == True, activationkey)
  File "/home/jurrien/.ansible/tmp/ansible-1381755089.64-208400602114918/rhn_register", line 272, in register
    run_command(register_cmd)
  File "/home/jurrien/.ansible/tmp/ansible-1381755089.64-208400602114918/rhn_register", line 110, in run_command
    stderr=subprocess.STDOUT)
  File "/usr/lib64/python2.4/subprocess.py", line 550, in **init**
    errread, errwrite)
  File "/usr/lib64/python2.4/subprocess.py", line 996, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

It cannot find rhnreg_ks.

When I change line 265 of the module rhn_register from:
register_cmd = "rhnreg_ks --username '%s' --password '%s' --force" % (self.username, self.password)

to:
register_cmd = "/usr/sbin/rhnreg_ks --username '%s' --password '%s' --force" % (self.username, self.password)

It works.

The playbook looks like this:

---
- copy: src=roles/common_rhn/files/RHN-ORG-TRUSTED-SSL-CERT dest=/usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT owner=root group=root mode=644
  notify:
  - deletesystemid
- lineinfile: dest=/etc/sysconfig/rhn/up2date regexp="^serverURL=" line="serverURL=https://prdrhn0001.ict.domain.nl/XMLRPC"
  notify:
  - deletesystemid
- meta: flush_handlers
- name: EL5 i386
  rhn_register: state=present activationkey=1-46997fb837ebbc2518fade8357abb2ab
  when: ansible_distribution_release == "Tikanga" and ansible_architecture == "i386"
- name: EL5 x86_64
  rhn_register: state=present activationkey=1-723258bfe78cc231194490019158cde2
  when: ansible_distribution_release == "Tikanga" and ansible_architecture == "x86_64"
- name: EL6 x86_64
  rhn_register: state=present activationkey=1-14d5d214bb16b829b17687cebe50f582
  when: ansible_distribution_release == "Santiago" and ansible_architecture == "x86_64"

**Comment by mpdehaan** [comment]
So looks like this is just a path issue because of going through sudo.

I'm ok with adding the explicit path as it won't be anywhere else, would you like to send in a pull request?

**Comment by beuker81** [comment]
Done
