### ISSUE TITLE
EC2 module: Using "wait" parameter as variable

### ISSUE THREAD

**Issue by bhutch** [ansible/ansible#4500]
Hello,

There may be a bug when using the "wait" parameter as a variable with the EC2 module.

$ ansible --version
ansible 1.4 (devel b8ec300d4c) last updated 2013/10/14 11:43:46 (GMT -500)

playbook "vars" section:
wait: yes

tasks section:
local_action: ec2 keypair={{ keypair }} group_id={{ group_id }} instance_type={{ instance_type }} image={{ image }} region={{ region }} wait={{ wait }} instance_tags='{"Name":"Example"}'

Error:
failed: [localhost] => {"failed": true}
msg: value of wait must be one of: yes,on,1,true,1,no,off,0,false,0, got: True

As a workaround, I've just been using "wait=yes" or "wait=true" when calling the ec2 module.

**Comment by mpdehaan** [comment]
looks like booleanification needs to lowercase when it's really fed a python True

I'll look into it.
