### ISSUE TITLE
request better error message for leading --- : YAML syntax error

### ISSUE THREAD

**Issue by darKoram** [ansible/ansible#4501]
The new error messages are great.  Here's one that gave a misleading message though:

vars/main.yml

---
# Note the space above

var1: "value"

With the errant space, the error message is as follows:
The "It may occur above" is a good message.
But perhaps some special checking for the correct first three dashes would be possible.

514 kbroughton:lynx-ansible$ ansible-playbook -i hosts site.yml --limit=localhost --tags="accumulo"
['pubkey_file', ' "~/.ssh/id_rsa.pub"']
ERROR: Syntax Error while loading YAML script, /Users/kbroughton/vcp/git/21ct/proto/lynx-ansible/roles/accumulo/vars/main.yml
Note: The error may actually appear before this position: line 24, column 1

pubkey_file: "~/.ssh/id_rsa.pub"
^
We could be wrong, but this one looks like it might be an issue with 
unbalanced quotes.  If starting a value with a quote, make sure the 
line ends with the same set of quotes.  For instance this arbitrary 
example:

```
foo: "bad" "wolf"
```

Could be written as:

```
foo: '"bad" "wolf"'
```

**Comment by mpdehaan** [comment]
Can you share a failing playbook with a gist so I can get the exact file?

Thanks!

**Comment by darKoram** [comment]
sure!
https://gist.github.com/darKoram/6981909

**Comment by mpdehaan** [comment]
At least the "we could be wrong" part applied :)

**Comment by darKoram** [comment]
whoever thought of leading with that caveat was genius

On Mon, Oct 14, 2013 at 7:14 PM, Michael DeHaan notifications@github.comwrote:

> At least the "we could be wrong" part applied :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/4501#issuecomment-26299541
> .

## 

Kesten Broughton
512 701 4209

**Comment by mpdehaan** [comment]
that's great, cause it was me!  So I can be a genius and also wrong!  :)
