### ISSUE TITLE
ansible-pull should offer git's "--verify-signatures" option

### ISSUE THREAD

**Issue by jgeerds** [ansible/ansible#4503]
As of `git` v1.8.3 it is possible to verify that the commits being merged have good and trusted GPG signatures (see `--verify-signatures` / `--no-verify-signatures` switch). This feature should also be available in `ansible-pull` to work with untrusted repositories.

**Comment by mpdehaan** [comment]
Sounds great, something you would like to add a pull request for?

**Comment by jgeerds** [comment]
I have already investigated the source code but it seems to be quite hard to implement. We need to extend ansible's git module. The `--verify-signatures` option provided by git is a merge option and therefore only available for e.g. `merge` or `pull`. In other words, we need a local "not-up-to-date"-branch which we can use for the merge. It looks like ansible's git module doesn't use local branches right now.

Do you have other ideas to implement this feature? Maybe a simple wrapper arround `ansible-pull` which check out the repository, merge the branch and then tell `ansible-pull` to use the already existing repository? However, this sounds a bit dirty…

**Comment by mpdehaan** [comment]
Hi,

We've keeping track of this list but haven't seen any traction here, so are closing this ticket out.  If someone would like to submit a pull request, that would be welcome, and we're still open to it.
