### ISSUE TITLE
Tasks tagged [always,b] are skipped by --skip-tags b

### ISSUE THREAD

**Issue by amenonsen** [ansible/ansible#45045]
##### SUMMARY
Tasks tagged 'always' should be skipped only if you do ``--skip-tags always``

##### ISSUE TYPE

 - ~Bug  Report~
- Feature Idea

##### COMPONENT NAME

core

##### ANSIBLE VERSION

```
devel
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

I noticed when testing the new "apply" feature that tasks tagged with ``[always,b]`` were being skipped by ``--skip-tags b``, which should not happen per playbooks_tags.rst. I looked at ``evaluate_tags``, and found that it does this:
```
        if should_run and skip_tags:

            # Check for tags that we need to skip
            if 'all' in skip_tags:
                if 'always' not in tags or 'always' in skip_tags:
                    should_run = False
            elif not tags.isdisjoint(skip_tags):
                should_run = False
            elif 'tagged' in skip_tags and tags != self.untagged:
                should_run = False
```
Because the ``'always' not in tags or 'always' in skip_tags`` test is wrapped in the ``'all' in skip_tags`` test, it doesn't work as intended. Indeed, if you do ``--skip-tags all,b``, then tasks tagged with ``[always,b]`` are **NOT** skipped, as I would expect. However, the ``all`` skip-tags is neither documented, nor does ``--skip-tags all,b`` make sense from a UI perspective.

If I change the code to:
```
        if should_run and skip_tags:

            # Check for tags that we need to skip
            if not tags.isdisjoint(skip_tags):
                if 'always' not in tags or 'always' in skip_tags:
                    should_run = False
            elif 'tagged' in skip_tags and tags != self.untagged:
                should_run = False
```
…then it behaves exactly as I would expect.

Having "always"-tagged tasks be skipped based on an "apply"-ed tag is not helpful behaviour, and is contrary to the documentation (and intuition based on the meaning of "always" in general). I have looked for some explanation of the rationale for this change in commit messages etc., but have been unable to find anything.

Therefore I think it's clearly a bug, and ``evaluate_tags()`` should be changed as described above.

```yaml
- debug: msg="foo"
  tags: [always, b]
```

##### EXPECTED RESULTS

The task should have been run.

##### ACTUAL RESULTS

The task was skipped.

**Comment by amenonsen** [comment]
Please note that this doesn't have anything to do with the ``apply:`` feature itself. It's purely to do with how tags are evaluated, as in the example above.

**Comment by agaffney** [comment]
What's the point of using `always` and another tag together on a task?

**Comment by amenonsen** [comment]
> What's the point of using `always` and another tag together on a task?

a.yml says:
```
- include_tasks:
    file: b.yml
    apply:
      tags: b
```

b.yml says:
```
- debug: msg=foo
  tags: always

- debug: msg=bar
```

The first debug task ends up tagged with [always,b].

If you _don't_ use apply as above, then the only way to accomplish the
same effect is to explicitly set «tags: b» on every task but the always
one. And if that's what you have to do to make it work, what's the point
of using apply?

**Comment by bcoca** [comment]
so it was on purpose that `[always, b]` would be skipped with `--skip-tags b` as the expectation was that 'always include unless explicitly skipped', which `--skip-tags b` would be in my book. Mixing that with inheritance does make it more 'interesting' and might need reevaluating.

**Comment by amenonsen** [comment]
> so it was on purpose that `[always, b]` would be skipped with
> `--skip-tags b` as the expectation was that 'always include unless
> explicitly skipped', which `--skip-tags b` would be in my book.

That would imply that --skip-tags sees "always" as being no more special
than "b", which is not what the documentation led me to believe. You're
right, this question takes on new importance now that we have "apply".

I think we should make always be special for skip-tags too, on the basis
that it's useful to have an "escape hatch" from include_role+apply (and
there's no easy way to accomplish the same effect).

**Comment by bcoca** [comment]
that might also require  changing 'never' as it works in similar way, it 'never runs unless explicitly targeted' , which currently includes other tags on same task

**Comment by relrod** [comment]
Closing as per above.

**Comment by amenonsen** [comment]
"As per above" means you're saying "Yes, it's a problem with no easy workaround, we might have to fix it in two places, so let's just go ahead and close it instead".

**Comment by relrod** [comment]
Well, no. "As per above" means we discussed it in a backlog meeting today and decided as a team that after reviewing the above information, we aren't planning on taking further action on this at this time.

**Comment by amenonsen** [comment]
Maybe there was supposed to be a note about the meeting and that decision somewhere "above", but there wasn't. Anyway, I appreciate your taking the time to provide more context. Thank you.
