### ISSUE TITLE
Add a way to specify multiple separate & intersections in a single play

### ISSUE THREAD

**Issue by tgerla** [ansible/ansible#4505]
Consider the following inventory:

```
[group1]
g11 ansible_ssh_host=127.0.0.11
g12 ansible_ssh_host=127.0.0.12

[group2]
g21 ansible_ssh_host=127.0.0.21
g22 ansible_ssh_host=127.0.0.22

[both]
g21
```

It might be nice to target a play like this:

```
hosts:
  - group1
  - group2:&both
```

...but this actually only selects g21 since this host specification is equivalent to group1:group2:&both and &both applies to group1 and group2, not just group2.

A workaround is to do separate plays.

Feature idea: expand the syntax to allow this sort of "or" selection.

**Comment by mpdehaan** [comment]
So what i think this this requesting is evaluate each seperate pattern string seperately (each one on a different line) and then OR the results of each pattern execution together?

Am I correct?

**Comment by pgehres** [comment]
Correct.

**Comment by mpdehaan** [comment]
Hi,

We've keeping track of this list but haven't seen any traction here, so are closing this ticket out.  If someone would like to submit a pull request, that would be welcome, and we're still open to it.
