### ISSUE TITLE
shell module: to run a script in backend, however, the shell script was run partly

### ISSUE THREAD

**Issue by judyQD** [ansible/ansible#45096]
This issue is not already reported on GitHub
##### SUMMARY

Shell module will excute a shell script such as a.sh.  a.sh will execute b.sh in backend. Howerver, the b.sh only be run partly. There is no other wrong. 
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]

```

##### OS / ENVIRONMENT

DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = root
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### STEPS TO REPRODUCE

test.yml
```yaml
---
- name: test shell module
  hosts: localhost

  tasks:

  - name: start b.sh
    shell: "./a.sh"
    args:
      chdir: /root/judy/judy_deploy_clcm
    become: yes

```
a.sh:
```
#! /bin/bash
source b.sh | tee test.log 2>&1 &
```
b.sh:
```
#! /bin/bash

echo "Enter b.sh..."

ansible-playbook ./changepasswd.yml

if [ $? -ne 0 ]; then
    echo "Password status not right"
    exit 1
else
    echo "Password status is right"
fi

```

##### EXPECTED RESULTS

test.log contains all the log info. If the password stauts is right, "Password status is right" will be in test.log
##### ACTUAL RESULTS

The b.sh is partly run. The playbook changepasswd.yml runs partly. 
cat test.log
```
Enter b.sh...

PLAY [check password status] ***************************************************

TASK [Gathering Facts] *********************************************************
```

```
ansible-playbook test.yml
```

**Comment by judyQD** [comment]
@ansibot @anotherjesse @uggedal @jvantuyl @fivethreeo  Could you please help check this? It is so nice of you to reply and help me.

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by doWolf1234** [comment]
backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;backgroud:#$v1;
