### ISSUE TITLE
Failed to create new process(%1 is not a valid Win32 application, Win32ErrorCode 193)\"",

### ISSUE THREAD

**Issue by shinux85** [ansible/ansible#45107]
##### SUMMARY
unable to run a powershell script via ansible plabook on windows 2008R2 server.But able to run directly from the server.
The same playbook works fine on windows 2012 servers

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

```ansible 2.4.2.0

```

##### CONFIGURATION

```yaml
[root@ansb01 windows]# cat ssm_nonprod_generic.yml
---
- name: To install and configure ssm Agent
  hosts: all
  roles:
   - role: win_ssm

[root@ansb01 windows]# cat roles/win_ssm/tasks/main.yml
---
- name: copy the SSM Package to client servers
  win_copy:
    src: /home/isopsxa/repo/Win_SSM/SSM_Agent
    dest: C:\
- name: Run the SSM Installation script
  win_command: C:\SSM_Agent\ssm.ps1
[root@ansb01 windows]#

```

##### EXPECTED RESULTS
Should be able to install the agent

##### ACTUAL RESULTS
[root@ansb01 windows]# ansible-playbook ssm_nonprod_generic.yml --limit=crm07d -vvv
ansible-playbook 2.4.2.0
  config file = /root/.ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.6.6 (r266:84292, Aug  9 2016, 06:11:56) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
Using /root/.ansible.cfg as config file
Parsed /etc/ansible/hosts inventory source with ini plugin

PLAYBOOK: ssm_nonprod_generic.yml ***********************************************************************************************************************************************************************************************************
1 plays in ssm_nonprod_generic.yml

PLAY [To install and configure ssm Agent] ***************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
Using module file /usr/lib/python2.6/site-packages/ansible/modules/windows/setup.ps1
<crm07d> ESTABLISH WINRM CONNECTION FOR USER: M1\s_isops on PORT 5986 TO crm07d
EXEC (via pipeline wrapper)
ok: [crm07d]
META: ran handlers

TASK [win_ssm : copy the SSM Package to client servers] *************************************************************************************************************************************************************************************
task path: /home/isopsxa/windows/roles/win_ssm/tasks/main.yml:2
Using module file /usr/lib/python2.6/site-packages/ansible/modules/windows/win_copy.ps1
<crm07d> ESTABLISH WINRM CONNECTION FOR USER: M1\s_isops on PORT 5986 TO crm07d
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
<crm07d> PUT "/tmp/tmp9WgCV9/win_copy.zip" TO "C:\Users\s_isops\AppData\Local\Temp\ansible-tmp-1535967250.14-133604231003698\source.zip"
Using module file /usr/lib/python2.6/site-packages/ansible/modules/windows/win_copy.ps1
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
changed: [crm07d] => {
    "changed": true,
    "dest": "C:\\",
    "operation": "folder_copy",
    "src": "/home/isopsxa/repo/Win_SSM/SSM_Agent"
}
TASK [win_ssm : Run the SSM Installation script] ********************************************************************************************************************************************************************************************
task path: /home/isopsxa/windows/roles/win_ssm/tasks/main.yml:10
Using module file /usr/lib/python2.6/site-packages/ansible/modules/windows/win_command.ps1
<crm07d> ESTABLISH WINRM CONNECTION FOR USER: M1\s_isops on PORT 5986 TO crm07d
EXEC (via pipeline wrapper)
fatal: [crm07d]: FAILED! => {
    "changed": false,
    "cmd": "C:\\SSM_Agent\\ssm.ps1",
    "msg": "Exception calling \"RunCommand\" with \"5\" argument(s): \"Failed to create new process (%1 is not a valid Win32 application, Win32ErrorCode 193)\"",
    "rc": 2
}
        to retry, use: --limit @/home/isopsxa/windows/ssm_nonprod_generic.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
crm07d                     : ok=4    changed=3    unreachable=0    failed=1

[root@ansb01 windows]#

```

```

**Comment by jborean93** [comment]
While I can't 100% say this is the reason but I believe this is due to the default behaviour in Windows, where the default application for opening a .ps1 file is to open it up in notepad. I've seen other cases where the `PATH` executable is corrupted causing invalid

I recommend you specify the executable when using win_command as that module is designed to be used to run executables rather than scripts.

```
- win_command: powershell.exe -File C:\SSM_Agent\ssm.ps1

# or if you want to skip the PATH resolution
- win_command: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -File C:\SSM_Agent\ssm.ps1
```

This starts the executable `powershell.exe` as a process and passes in the path to your script as one of the arguments.

In the future we try and encourage user's to post user questions in the mailing list or IRC channels

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

We understand it can be hard to identify an actual bug vs weird behaviour and find it best to try those channels out first before filing a GitHub issue.

**Comment by shinux85** [comment]
still failing
TASK [win_ssm_2008 : Run the SSM Installation script] ***************************************************************************************************************************************************************************************
task path: /home/isopsxa/windows/roles/win_ssm_2008/tasks/main.yml:10
Using module file /usr/lib/python2.6/site-packages/ansible/modules/windows/win_command.ps1
<crm07d> ESTABLISH WINRM CONNECTION FOR USER: M1\s_isops on PORT 5986 TO crm07d
EXEC (via pipeline wrapper)
fatal: [crm07d]: FAILED! => {
    "changed": true,
    "cmd": "powershell.exe -File C:\\SSM_Agent\\ssm.ps1",
    "delta": "0:00:00.686400",
    "end": "2018-09-04 12:38:03.069634",
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2018-09-04 12:38:02.383234",
    "stderr": "Thread failed to start.\r\n",
    "stderr_lines": [
        "Thread failed to start."
    ],
    "stdout": "",
    "stdout_lines": []
}
        to retry, use: --limit @/home/isopsxa/windows/ssm_nonprod_generic_win2008.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
crm07d                     : ok=4    changed=3    unreachable=0    failed=1
