### ISSUE TITLE
Rewrite oVirt dynamic inventory to inventory plugin

### ISSUE THREAD

**Issue by machacekondra** [ansible/ansible#45104]
##### SUMMARY

This issue asks to rewrite oVirt dynamic inventory into inventory plugin.

##### ISSUE TYPE
 - Feature Idea

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by Akasurde** [comment]
@machacekondra Could you please review this PR https://github.com/ansible/ansible/pull/49085 ? Thanks in advance.

**Comment by AlanCoding** [comment]
That was merged into the collection

**Comment by mnecas** [comment]
Resolved in ovirt collection

**Comment by mnecas** [comment]
close_me
