### ISSUE TITLE
"service enabled=yes" is always considered "changed"

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#4511]
Platform: target Debian Wheezy, host Ubuntu 12.04. ansible 1.2 from rquillo precise PPA.

I use service tasks to ensure that the service is running (state=started) and to ensure that the service will auto-start when the machine next boots (enabled=yes).

I believe this ought to be idempotent, and do nothing if the service is already running and configured to auto-start. However every time the task reports "changed":

```
TASK: [service name=ntp state=started enabled=yes] *************************
changed: [dar4.example.com]

... ditto for snmpd, condor

PLAY RECAP ********************************************************************
dar4.example.com    : ok=57   changed=3    unreachable=0    failed=0
```

However after running this task, the processes are not restarted, and the timestamps on the symlinks /etc/rc_.d/_ntp\* are the same.

Testing separately:
- `service: name=ntp state=started`
  
  Green (unchanged)
- `service: name=ntp enabled=yes`
  
  Yellow (changed)

So it appears to be "enabled=yes" which is reporting spurious changes.

**Comment by mpdehaan** [comment]
Ansible 1.3 is the current version.

Please re-report this if it occurs on 1.3.X

**Comment by geerlingguy** [comment]
I'm getting the same issue (ntp enabled=yes causing changed to report true) on 1.3.4, which is the latest version available via pip... should I open a new issue?
