### ISSUE TITLE
authorized_key broken 

### ISSUE THREAD

**Issue by nicolas-g** [ansible/ansible#4513]
### configuration

```
ansible --version
ansible 1.4 (devel e131de4de0) last updated 2013/10/15 13:19:30 (GMT +300)

CentOS 5
Linux 2.6.34.7-56.40.amzn1.x86_64 #1 SMP Fri Oct 22 18:48:49 UTC 2010 x86_64 x86_64 x86_64 GNU/Linux

boto version: 2.13.3
```

This is working fine for other ssh users I create but is breaking for a specific user (test-user2) with the latest version of Ansible, with Ansible stable release 1.3.3 there are no problems.

I'm deploying ssh user keys file from roles/common/files/public-keys/test-user2.pub using the bellow task : 
### task

```
- name: Deploying user(s) ssh key(s)
  authorized_key: user={{ item.user }} key="{{ lookup('file', 'public-keys/' + item.user + '.pub') }}"
  with_items: ssh_users
```
### error message

```
failed: [ec2-54-227-121-48.compute-1.amazonaws.com] => (item={'user': 'test-user2'}) => {"failed": true, "item": {"user": "test-user2"}}
msg: invalid key specified: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAs4iqaTnWa5aF3ZsNX0Hae/c/4N5XMWJCZ7idN2B2sGwREIXEP7bsUkrylfkMVD97ddpKVINzZ3uQK/9t5EiRM6/dCJc3hqSzXRitpkSYJHgaSh56ysNvEmIY5DWl1DWu82ETu804miCkGizYEaXw0EA2njvybuavCCud0DwOn6JDfYAeSfgqn5a1Dn/81CEQjxGcYb1SCmKBIAS6yLs1HhKbEV7oDgycB72E3ZsVYggH9AHKUuAuMFDgPyWy5UFfjQe8yo+/TWx7emgQMX/JYVPNBNdqcTSdMdMZ1zHBCqQtT+ScgC1V6ZPYE/TSnM3LQ6xV7JFzBlnVLxD5LH4+1w==
```

**Comment by jimi-c** [comment]
Does the public key have the comment at the end (typically the user@host where it was generated)? I know that's optional, but it is expected in the file format. I can fix the check if so, I just want to verify what may be causing the above.

**Comment by nicolas-g** [comment]
no it doesn't while other users keys that have no problems have this comment.

**Comment by jimi-c** [comment]
Ok, I'll have a patch merged into devel shortly. Thanks!

**Comment by jimi-c** [comment]
There you go, please let us know if you continue to have problems with this. Thanks again!

**Comment by nicolas-g** [comment]
I confirm it's fixed, thanks for the quick patch.

**Comment by mikesparr** [comment]
This was breaking for me too and I had the `name=jim key="{{ lookup('file', ...) }}"` in the vars list for each user.  I changed the vars to just `name=jim` and `key=keys/jim.pub` in vars file, then in the task I changed to: `authorized_key user={{ items[user] }} key="{{ lookup('file', items[key]) }}" with_items=users` instead and then playbook worked again with relative path to the `files` folder.  Hope that helps someone.

**Comment by gvenka008c** [comment]
@mikesparr @nicolas-g @jimi-c I have the below in my playbook for accessing the users public key from github

```
  - name: Add SSH Keys for user from github
    authorized_key: user=username key=https://github.com/username.keys
```

I am getting the below error. Please suggest.

```
Error: fatal: [067cea8f-3725-40ff-aa02-675c54d988da]: FAILED! => {"changed": false, "failed": true, "msg": "invalid key specified: <!DOCTYPE html>"}
```

```
ansible --version
ansible 2.0.0.2
  config file = /Users/gvenka008c/caps-sps/jenkins_mesos/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by jimi-c** [comment]
@gvenka008c Could you please open a new issue? This should also go to ansible/ansible-modules-core.

**Comment by jagankondapalli** [comment]
@gvenka008c - were you able to solve your problem? I have the same exact problem now. please suggest
