### ISSUE TITLE
callback test fails on ubuntu 13.04

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#4515]
<pre>jtanner@u1304:~/ansible$ make tests
PYTHONPATH=./lib nosetests -d -v
test_callback (TestCallback.TestInventory) ... /bin/sh: 1: source: not found
Traceback (most recent call last):
  File "/home/jtanner/ansible/bin/ansible-playbook", line 24, in <module>
    import ansible.playbook
ImportError: No module named ansible.playbook
FAIL
test_callback_disabled (TestCallback.TestInventory) ... /bin/sh: 1: source: not found
Traceback (most recent call last):
  File "/home/jtanner/ansible/bin/ansible-playbook", line 24, in <module>
    import ansible.playbook
ImportError: No module named ansible.playbook
ok

...

======================================================================
FAIL: test_callback (TestCallback.TestInventory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jtanner/ansible/test/TestCallback.py", line 50, in test_callback
    assert os.path.exists(FILE_RUN)
AssertionError: 
    self.run_ansible_playbook()
>>  assert <module 'os' from '/usr/lib/python2.7/os.pyc'>.path.exists('/tmp/ansible_test_finish')
    self.clean_file()
    

----------------------------------------------------------------------
Ran 85 tests in 23.525s

FAILED (SKIP=1, failures=1)
make: *** [tests] Error 1
</pre>

**Comment by jctanner** [comment]
Reproduced with a fresh ubuntu install.

**Comment by jctanner** [comment]
This appears to be a problem with /bin/sh being a symlink to dash instead of bash in 13.04.

Workaround:

<pre>
jtanner@u1304:~/$ ls -al /bin/sh
lrwxrwxrwx 1 root root 4 Sep 17 22:12 /bin/sh -> dash
jtanner@u1304:~/e$ sudo rm /bin/sh
jtanner@u1304:~/$ sudo ln -s /bin/bash /bin/sh
</pre>

**Comment by mpdehaan** [comment]
We have plans to redo the way playbook tests work in the future so I'm ok with this being what it is for now.

We should probably remove the need for it to call source in the future and pull requests to this affect would be fine.
