### ISSUE TITLE
File module doesn't handle hardlinks properly (with no state specified)

### ISSUE THREAD

**Issue by evgkrsk** [ansible/ansible#4516]
ansible-1.3.3 (298d8d78ca92797429120138542c277e07e54421)

testplay:
- name: test
  
  file: path=/lib64/libnss_mdns4_minimal.so.2

ansible-playbook's error message:

msg: refusing to convert between hard and file for None

ls -lht /lib64/libnss_mdns4_minimal.so.2 on affected host:
-rw-r--r-- 4 root root 11K Jun 11 19:44 /lib64/libnss_mdns4_minimal.so.2

**Comment by mpdehaan** [comment]
Were you running this to just get the info about the file or something else?

Curious why there was no state specified, agree the message about None indicates a problem but just trying to ask the larger question.

Thanks!

**Comment by evgkrsk** [comment]
Yes, I just want to be sure that file exists on target machine (actually, I need to check that some package is installed, but at a moment ansible lacks support for my package manager) and stop with error if it is not.

state is optional arg (as per http://www.ansibleworks.com/docs/modules.html#id193), state=file doesn't change anything.
