### ISSUE TITLE
Module ini_file removed comments in file.

### ISSUE THREAD

**Issue by marcinpraczko** [ansible/ansible#4522]
Hi,

Version: Ansible 1.3.2

I think that module ini_file is not working correctly. I've created following tasks:
- name: Copy default ini file template
  template: src=general.ini.j2 dest=/etc/managed-ansible/general.ini
- name: Add primary variable to ini file.
  ini_file: 
    dest=/etc/managed-ansible/general.ini
    section=general
    option=managed_by_ansible
    value=yes
    state=present

And this is template for general.ini.j2
  # General INI file for details about what is managing by ansible.
  # 
  # Warning: If version is not the same as on ansible, every manual change 
  #          will be lost after re-running ansible.
  # 
  # Version is defined in ansible role vars:
  # Version: {{ r_ini_file_ver }}

[general]

Issue:
When runing this
- template will be copied to host - this is OK
- ini_file module will remove all comments (started by #) and just add section [general] with one value managed_by_ansible = yes.

Expected result:
Just add value under [general] section - not removing comments from file. 

Best regards,
Marcin Praczko

**Comment by mpdehaan** [comment]
This is a known thing about the INI module.

I believe the fact that it removes comments should be documented, however.

**Comment by marcinpraczko** [comment]
Thank you for reply. 

From my point of view this issue sould be counted as bug - not only lack of documentation. In this case there is no way to attach even simple comment to ini file like: # {{ansible_manage}}. So there is no track on file that file is managed by ansible.

I think ini_file module is really nice module and brings value to project especially when content by ini file must be modified by many roles. Would be very nice to see this working without removing comments from ini file. 

Best regards, 
Marcin Praczko
