### ISSUE TITLE
when clause causes syntax error if first argument is a string

### ISSUE THREAD

**Issue by gregbuehler** [ansible/ansible#4526]
Can be reproduced using the playbook 

```
- hosts: all
  tasks:
    - name: test operator order, var then string
      debug: msg="variable first"
      when: ansible_virtualization_type != "virtualbox"

    - name: test operator order, string then var
      debug: msg="string first"
      when: "virtualbox" != ansible_virtualization_type
```

**Comment by mpdehaan** [comment]
1.4 already warns about this, but in YAML, if you start a line with a quote it expects you are sharing a string and wants to see a matching end quote.

This is not a bug.

**Comment by mpdehaan** [comment]
Example fix:

when: '"virtualbox" != ansible_virtualization_type'

Or just flip the order around
