### ISSUE TITLE
Problems with creating deb package?

### ISSUE THREAD

**Issue by zack-perry** [ansible/ansible#453]
I tried to follow the instructions in http://ansible.github.com/gettingstarted.html#getting-ansible to retrieve the latest version from git and build a deb package on my notebook running Ubuntu 11.04 64 bit.

I got two errors along the way. They are marked with ^^^^^ below.  Not yet familiar with the deb packaging scheme yet, I would appreciate a hint or two:

root@nb1:~# git clone git://github.com/ansible/ansible.git
Cloning into ansible...
remote: Counting objects: 4952, done.
remote: Compressing objects: 100% (1655/1655), done.
remote: Total 4952 (delta 2904), reused 4767 (delta 2741)
Receiving objects: 100% (4952/4952), 808.79 KiB | 831 KiB/s, done.
Resolving deltas: 100% (2904/2904), done.
root@nb1:~# git checkout -t origin/devel
fatal: Not a git repository (or any of the parent directories): .git
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ -------- (1)

So, the instructions in the wiki generated a fatal error here.

root@nb1:~# cd ./ansible
root@nb1:~/ansible# make debian
Cleaning up distutils stuff
rm -rf build
rm -rf dist
Cleaning up byte compiled python stuff
find . -type f -regex "._.py[co]$" -delete
Cleaning up editor backup files
find . -type f ( -name "_~" -or -name "#_" ) -delete
find . -type f ( -name "_.swp" ) -delete
Cleaning up asciidoc to man transformations and results
find ./docs/man -type f -name "_.xml" -delete
find ./docs/man -type f -name "_.asciidoc" -delete
Cleaning up output from test runs
rm -rf test/test_data
Cleaning up RPM building stuff
rm -rf MANIFEST rpm-build
Cleaning up Debian building stuff
rm -rf debian
rm -rf deb-build
python setup.py sdist -t MANIFEST.in
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running sdist
running check
warning: sdist: standard file not found: should have one of README, README.txt
[...]

Then, I followed the instructions in debian/README.txt and did the following:

root@nb1:~/ansible/packaging# dpkg-buildpackage -us -uc -rfakeroot
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: export CFLAGS from dpkg-buildflags (origin: vendor): -g -O2
dpkg-buildpackage: export CPPFLAGS from dpkg-buildflags (origin: vendor): 
dpkg-buildpackage: export CXXFLAGS from dpkg-buildflags (origin: vendor): -g -O2
dpkg-buildpackage: export FFLAGS from dpkg-buildflags (origin: vendor): -g -O2
dpkg-buildpackage: export LDFLAGS from dpkg-buildflags (origin: vendor): -Wl,-Bsymbolic-functions
parsechangelog/debian: warning:     debian/changelog(l5): badly formatted heading line
LINE: -- Michael DeHaan michael.dehaan@gmail.com Fri, 25 May 2012 16:40:00 -0400
parsechangelog/debian: warning:     debian/changelog(l7): found start of entry where expected more change data or trailer
LINE: ansible (0.4) debian; urgency=low
parsechangelog/debian: warning:     debian/changelog(l7): found eof where expected more change data or trailer
dpkg-buildpackage: source package ansible
dpkg-buildpackage: source version 0.5
dpkg-buildpackage: error: unable to determine source changed by
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ------ (2)

What can I do to "fix" the above issues?  I took a look of the debian/changelog.  The format didn't look wrong to me when I compare its content with other packages'.  Of course, being a newbie in this aspect, I stand to be corrected.

Regards,

Zack

**Comment by mpdehaan** [comment]
I don't know anything about Debian packaging, can you ask on the mailing list?
