### ISSUE TITLE
easy_install throwing an AttributeError on latest devel

### ISSUE THREAD

**Issue by thaumos** [ansible/ansible#4532]
https://gist.github.com/thaumos/6998744 is the gist of the error. 

Attempting to install the following in a playbook

easy_install: name=$item
  with_items:
     - pip
     - python-keyczar

**Comment by ChadScott** [comment]
After some experimentation, I see that revision 3c33273071474d1382da95642cc96b8a7579aec9 is the last that works properly on library/packaging/easy_install.

**Comment by jctanner** [comment]
Taking a look now.

**Comment by jctanner** [comment]
Looks like this is caused by a parameter "executable" default of None. I'm sorting out why the virtualenv code works this way and if a quick fix can be put in place without breaking the virtualenv code.
