### ISSUE TITLE
Problem with absolute path for inventory_dir

### ISSUE THREAD

**Issue by jurgenhaas** [ansible/ansible#4535]
As reported in https://github.com/ansible/ansible/issues/4291 there is still that problem when the "-i ../path/to/inventory/hosts" command line parameter is a relative path.

To reproduce this, please use the files from https://github.com/ansible/ansible/issues/4291 and put them into a directory structure shown in the attached screen shot.
![auswahl_001](https://f.cloud.github.com/assets/1475675/1340407/16f9c378-362f-11e3-8637-db7f935b478f.jpg)

**Comment by mpdehaan** [comment]
I pushed a few additions to absolute-ify the path, which we missed previously.

Tested with your example above, you should be good to go.

let me know if not.

Thanks!
