### ISSUE TITLE
Right way to invoke ActionBase._execute_module for modules with "free_form" argument

### ISSUE THREAD

**Issue by sankaravadivel** [ansible/ansible#45370]
##### SUMMARY
I am building a custom action plugin and I am trying to invoke the command module using ActionBase._execute_module. But unfortunately, I couldn't find any document or samples showing how to pass the command to module_args parameter. I set _raw_params value to my command and got it working. But I am not sure if that is the recommended approach

 cmd = 'ls  -a'
 command_task.args["_raw_params"] = cmd
 command_task.args['_uses_shell'] = True
 module_return = self._execute_module(module_name='command', module_args=command_task.args, task_vars=task_vars)
##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'                                                                                        /usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (R                                                                                        ed Hat 4.8.5-28)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

RHEL 7.5

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a developer question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible-devel on irc.freenode.net   
   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
