### ISSUE TITLE
ansible Failed when connected to H3C switch by ssh 

### ISSUE THREAD

**Issue by CptJason** [ansible/ansible#45416]
##### SUMMARY

![image](https://user-images.githubusercontent.com/397285/45293152-eed4a500-b529-11e8-9a3e-ab6a0d3d3cc3.png)

1. ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=user1 -o ConnectTimeout=5 -o ControlPath=/root/.ansible/cp/4c801cc0ae 1.1.1.1 '/bin/sh -c '"'"'echo ~$USER && sleep 0'"'"''

2.  ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=user1 -o ConnectTimeout=5 -o ControlPath=/root/.ansible/cp/4c801cc0ae 1.1.1.1

Why dose 1st one fail but 2nd succeed? Is that a BUG in ansible version 2.5.3?
![ansible-version](https://user-images.githubusercontent.com/397285/45293280-4541e380-b52a-11e8-9e7b-edbc54f9a813.png)

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by CptJason** [comment]
# SSH DEBUG INFO
Failed to connect to the host via ssh: OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013

\ndebug1: Reading configuration data /user1/.ssh/config

\ndebug1: Reading configuration data /etc/ssh/ssh_config

\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *

\ndebug1: auto-mux: Trying existing master

\ndebug1: Stale control socket /user1/.ansible/cp/4c801cc0ae, unlinking

\ndebug2: ssh_connect: needpriv 0

\ndebug1: Connecting to 1.1.1.1 [1.1.1.1] port 22.

\ndebug2: fd 3 setting O_NONBLOCK

\ndebug1: fd 3 clearing O_NONBLOCK

\ndebug1: Connection established.

\ndebug3: timeout: 4998 ms remain after connect

\ndebug1: permanently_set_uid: 0/0

\ndebug3: Incorrect RSA1 identifier

\ndebug3: Could not load \"/user1/.ssh/id_rsa\" as a RSA1 public key

\ndebug1: identity file /user1/.ssh/id_rsa type 1

\ndebug1: identity file /user1/.ssh/id_rsa-cert type -1

\ndebug1: identity file /user1/.ssh/id_dsa type -1

\ndebug1: identity file /user1/.ssh/id_dsa-cert type -1

\ndebug1: identity file /user1/.ssh/id_ecdsa type -1

\ndebug1: identity file /user1/.ssh/id_ecdsa-cert type -1

\ndebug1: identity file /user1/.ssh/id_ed25519 type -1

\ndebug1: identity file /user1/.ssh/id_ed25519-cert type -1

\ndebug1: Enabling compatibility mode for protocol 2.0

\ndebug1: Local version string SSH-2.0-OpenSSH_6.6.1

\ndebug1: Remote protocol version 1.99, remote software version Comware-5.20

\ndebug1: no match: Comware-5.20

\ndebug2: fd 3 setting O_NONBLOCK

\ndebug3: load_hostkeys: loading entries for host \"1.1.1.1\" from file \"/dev/null\"

\ndebug3: load_hostkeys: loaded 0 keys

\ndebug1: SSH2_MSG_KEXINIT sent

\ndebug1: SSH2_MSG_KEXINIT received

\ndebug2: kex_parse_kexinit: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1

\ndebug2: kex_parse_kexinit: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,ssh-rsa,ssh-dss

\ndebug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se

\ndebug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se

\ndebug2: kex_parse_kexinit: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96

\ndebug2: kex_parse_kexinit: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96

\ndebug2: kex_parse_kexinit: zlib@openssh.com,zlib,none

\ndebug2: kex_parse_kexinit: zlib@openssh.com,zlib,none

\ndebug2: kex_parse_kexinit: 

\ndebug2: kex_parse_kexinit: 

\ndebug2: kex_parse_kexinit: first_kex_follows 0 

\ndebug2: kex_parse_kexinit: reserved 0 

\ndebug2: kex_parse_kexinit: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1

\ndebug2: kex_parse_kexinit: ssh-dss,ssh-rsa

\ndebug2: kex_parse_kexinit: aes128-cbc,3des-cbc,des-cbc

\ndebug2: kex_parse_kexinit: aes128-cbc,3des-cbc,des-cbc

\ndebug2: kex_parse_kexinit: hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96

\ndebug2: kex_parse_kexinit: hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96

\ndebug2: kex_parse_kexinit: none

\ndebug2: kex_parse_kexinit: none

\ndebug2: kex_parse_kexinit: 

\ndebug2: kex_parse_kexinit: 

\ndebug2: kex_parse_kexinit: first_kex_follows 0 

\ndebug2: kex_parse_kexinit: reserved 0 

\ndebug2: mac_setup: setup hmac-md5

\ndebug1: kex: server->client aes128-cbc hmac-md5 none

\ndebug2: mac_setup: setup hmac-md5

\ndebug1: kex: client->server aes128-cbc hmac-md5 none

\ndebug1: kex: diffie-hellman-group-exchange-sha1 need=16 dh_need=16

\ndebug1: kex: diffie-hellman-group-exchange-sha1 need=16 dh_need=16

\ndebug1: SSH2_MSG_KEX_DH_GEX_REQUEST(1024<3072<8192) sent

\ndebug1: expecting SSH2_MSG_KEX_DH_GEX_GROUP

\ndebug2: bits set: 2036/4096

\ndebug1: SSH2_MSG_KEX_DH_GEX_INIT sent

\ndebug1: expecting SSH2_MSG_KEX_DH_GEX_REPLY

\ndebug1: Server host key: RSA 50:...:69

\ndebug3: load_hostkeys: loading entries for host \"1.1.1.1\" from file \"/dev/null\"

\ndebug3: load_hostkeys: loaded 0 keys

\nWarning: Permanently added '1.1.1.1' (RSA) to the list of known hosts.

\ndebug2: bits set: 2101/4096

\ndebug1: ssh_rsa_verify: signature correct

\ndebug2: kex_derive_keys

\ndebug2: set_newkeys: mode 1

\ndebug1: SSH2_MSG_NEWKEYS sent

\ndebug1: expecting SSH2_MSG_NEWKEYS

\ndebug2: set_newkeys: mode 0

\ndebug1: SSH2_MSG_NEWKEYS received

\ndebug1: SSH2_MSG_SERVICE_REQUEST sent

\ndebug2: service_accept: ssh-userauth

\ndebug1: SSH2_MSG_SERVICE_ACCEPT received

\ndebug2: key: /user1/.ssh/id_rsa (0x7f9dd3bfcf70),

\ndebug2: key: /user1/.ssh/id_dsa ((nil)),

\ndebug2: key: /user1/.ssh/id_ecdsa ((nil)),

\ndebug2: key: /user1/.ssh/id_ed25519 ((nil)),

\ndebug1: Authentications that can continue: publickey

\ndebug3: start over, passed a different list publickey

\ndebug3: preferred gssapi-with-mic,gssapi-keyex,hostbased,publickey

\ndebug3: authmethod_lookup publickey

\ndebug3: remaining preferred: ,gssapi-keyex,hostbased,publickey

\ndebug3: authmethod_is_enabled publickey

\ndebug1: Next authentication method: publickey

\ndebug1: Offering RSA public key: /user1/.ssh/id_rsa

\ndebug3: send_pubkey_test

\ndebug2: we sent a publickey packet, wait for reply

\ndebug1: Server accepts key: pkalg ssh-rsa blen 279

\ndebug2: input_userauth_pk_ok: fp b0:...:9f

\ndebug3: sign_and_send_pubkey: RSA a0:...:9f

\ndebug1: key_parse_private2: missing begin marker

\ndebug1: read PEM private key done: type RSA

\ndebug1: Authentication succeeded (publickey).

\nAuthenticated to 1.1.1.1 ([1.1.1.1]:22).

\ndebug1: setting up multiplex master socket

\ndebug3: muxserver_listen: temporary control path /user1/.ansible/cp/4c801cc0ae.82yGFQjbcxRKnuFx

\nControlSocket /user1/.ansible/cp/4c801cc0ae already exists, disabling multiplexing

\ndebug2: fd 5 setting O_NONBLOCK

\ndebug2: fd 6 setting O_NONBLOCK

\ndebug1: channel 0: new [client-session]

\ndebug3: ssh_session2_open: channel_new: 0

\ndebug2: channel 0: send open

\ndebug1: Entering interactive session.

\ndebug2: callback start

\ndebug2: fd 3 setting TCP_NODELAY

\ndebug3: packet_set_tos: set IP_TOS 0x08

\ndebug2: client_session2_setup: id 0

\ndebug1: Sending environment.

\ndebug3: Ignored env XDG_SESSION_ID

\ndebug3: Ignored env HOSTNAME

\ndebug3: Ignored env SHELL

\ndebug3: Ignored env TERM

\ndebug3: Ignored env HISTSIZE

\ndebug3: Ignored env USER

\ndebug3: Ignored env LS_COLORS

\ndebug3: Ignored env MAIL

\ndebug3: Ignored env PATH

\ndebug3: Ignored env PWD

\ndebug1: Sending env LANG = en_US.UTF-8

\ndebug2: channel 0: request env confirm 0

\ndebug3: Ignored env HISTCONTROL

\ndebug3: Ignored env SHLVL

\ndebug3: Ignored env HOME

\ndebug3: Ignored env LOGNAME

\ndebug3: Ignored env LESSOPEN

\ndebug3: Ignored env _

**_`\ndebug1: Sending command: /bin/sh -c 'echo ~user1 && sleep 0'`_**

\ndebug2: channel 0: request exec confirm 1

\ndebug2: callback done

\ndebug2: channel 0: open confirm rwindow 131072 rmax 32496

\ndebug2: channel_input_status_confirm: type 99 id 0

\ndebug2: exec request accepted on channel 0

\ndebug2: channel 0: rcvd close

\ndebug2: channel 0: output open -> drain

\ndebug2: channel 0: close_read

\ndebug2: channel 0: input open -> closed

\ndebug3: channel 0: will not send data after close

\ndebug1: channel 0: free: client-session, nchannels 1

\ndebug3: channel 0: status: The following connections are open:

\n  #0 client-session (t4 r1 i3/0 o1/0 fd -1/5 cc -1)

\n

\ndebug1: fd 1 clearing O_NONBLOCK

\ndebug1: fd 2 clearing O_NONBLOCK

\nConnection to 1.1.1.1 closed by remote host.

\nTransferred: sent 3848, received 3376 bytes, in 0.1 seconds

\nBytes per second: sent 27167.5, received 23835.1

\ndebug1: Exit status -1

\n

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
