### ISSUE TITLE
Warning about unnecessary {{ doesn't specify file

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#4542]
Ran a playbook and got a warning:

```
$ ./myplaybook.yaml
 [WARNING]: It is unneccessary to use '{{' in loops, leave variables in loop
expressions bare.
```

It would help if Ansible outputted the name of the file that contained the extraneous `{{`.

**Comment by mpdehaan** [comment]
Yes, it's a little tricky as we don't have the context in the code there easily, but I agree.

We would have to record the YAML line number somehow as we are parsing the file.

I don't think this will be easily solveable in the way it is currently implemented, but could be done by pre-processing the file instead, which is what I think we should do.

Eventually... not the top priority for now.  If anyone is interested, it can be found in utils if you look for the "parse_yaml" functions how we do it for some deprecation warnings, but those are triggered on YAML syntax errors.

In all, it's a little tricky as technically it would be legal to have a variable named "with_items" :)

In the end, my gut feeling is this isn't easily fixable, but should perhaps suggest how to find them with a simple grep for "with__: ._{{" or something close.

**Comment by mpdehaan** [comment]
Basically this is going to require refactoring roles to be more objecty and any resource that has a file associated with it to be an object that remembers the filename.  I'm leaving this open for notes about that refactoring being desirable but this may not come soon.

**Comment by bcoca** [comment]
the warnings were removed
