### ISSUE TITLE
Variable Scoping: The active role variables do not take precedence when activated as a dependency

### ISSUE THREAD

**Issue by briceburg** [ansible/ansible#4545]
Example code has been simplified to clearly demonstrate the variable scoping issue that occurs when a dependent role is activated.

This is a duplicate of issue #4528  -  which I've added after reading advice from: https://groups.google.com/forum/#!msg/ansible-project/BPnZPe_Ixhg/aDU9dkvrUjcJ

The scoping issue is a major showstopper for us; and I'd like to at least get confirmation that this is a bug with intent to fix vs. desirable behavior.

Summary: 

https://github.com/briceburg/ansible-variable-scoping/tree/master/simple

**Comment by jimi-c** [comment]
What you're seeing is expected behavior. Since the variable you're using is defined in both roles, it is scoped locally to that role so it sees a consistent snapshot of its own variables without having to worry about another role overriding its variables in the global scope. If you want the dependent role `test_service` to have its variables overridden, you should move them to `defaults/main.yml`. Default variables have the lowest precedence, and are overridden by all other variable scopes, however they are not passed on to dependent roles. 

I'm going to go ahead and close this, but if you have any other questions regarding this feel free to ask them here or on the mailing list.

**Comment by briceburg** [comment]
@jimi-c Thanks for looking -- although I'm still quite confused. According to a post by michael, 

"... within a role, the variables in roles/y/vars/main.yml are guaranteed to be applied to that specific role, just as if they were parameters explicitly passed to the role." ( https://groups.google.com/d/msg/ansible-project/0JIrNlnRXuI/tx1-inKYoUQJ )

As such; when the test_service role is executing and running tasks from roles/test_service/tasks/main.yml  -- I would expect these tasks to use variable definitions from roles/test_service/vars/main.yml

I thought the whole purpose of these posts was to ensure that the active role always got its definitions [unless, of course they are being overriden by --extra-vars or the base playbook defining them which are supposed to take higher precedence]. 

I'll play around with defaults, although don't recall being successful with this on my last attempt.

For now, if the current behavior is desirable; we're stuck with having to prefix all variable names w/ a namespace.

**Comment by jimi-c** [comment]
@briceburg re-reading this, I think I misunderstood the issue. I saw the EXPECT lines and thought things were working. I'll re-open this and take a look into it.

**Comment by briceburg** [comment]
@jimi-c Please let me know if my example is clear. I very much appreciate your feedback.

[edit]
Today I spent a long time experimenting with scoping and believe to have uncovered another issue. Using default/main.yml vs. vars/main.yml works as I would originally expect; meaning the roles that get called in by the dependency mechanism have their variable definitions take precedence when active. If, however, I include tasks in one of these roles; the included tasks will use variable definitions from a different role.

An example of this is posted here:

https://github.com/briceburg/ansible-variable-scoping/tree/master/simple_defaults

The specific file that performs the include is:
https://github.com/briceburg/ansible-variable-scoping/blob/master/simple_defaults/roles/test_nested_service/tasks/main.yml

Notice the 3rd task in the output shows 8080 instead of 9000. 

Is this expected? Please let me know if I can help fix.

**Comment by mpdehaan** [comment]
These examples might be easier to skim on the web if you update the comments to say "expected 1234, got 5678"

**Comment by briceburg** [comment]
@mpdehaan I've made the change I believe you requested and feel that things are now absolutely distilled to their minimum. If you require another change; please provide an example of what you'd like to see.

The repository has two scoping examples. One shows an issue when using vars/main.yml , the other when using defaults/main.yml .

These are:

https://github.com/briceburg/ansible-variable-scoping/tree/master/simple_vars

and 

https://github.com/briceburg/ansible-variable-scoping/tree/master/simple_defaults

respectively.

While writing this I had a hankering to investigate what you guys are using for testing; it appears that there's no specific "test"/"assert" module; but you're using ansible itself and running playbooks. If you want I can alter these examples to use the "fail" module to fail when a variable doesn't == an assertion.

Thanks again for your review. I'm sorry this has been so painful.

**Comment by briceburg** [comment]
There is a lot of confusion in this issue. I've opened two issues to address each issue discussed here.

#4641  
#4642
