### ISSUE TITLE
When conditional doesn't work correctly when filtering through default

### ISSUE THREAD

**Issue by WramblinWreck** [ansible/ansible#4550]
I'm seeing strange behavior for a "when" expression when using the default() jinja filter.  Here's a test I created to illustrate the issue:

https://gist.github.com/RackerJohnMadrid/7015529

When I run the above playbook with:
ansible-playbook -i local test.yml -vvv -e foo=false

I would expect that both tasks would be skipped.  Instead the first task prints "false is the value".  If I put the following for the when condition for the first task instead, both tasks are skipped:
when: foo|default('some text', true) == true

The developer in me doesn't like to use == true when evaluating boolean expressions.  Not sure what's going on here.

**Comment by mpdehaan** [comment]
pasting from above:

```
- hosts: localhost
  connection: local

  tasks:

  - name: test 1
    debug: msg="{{foo}} is the value"
    when: foo|default('some text', true)

  - name: test 2
    debug: msg="{{foo}} is the value"
    when: foo
```

**Comment by mpdehaan** [comment]
First off, you did not specify what version of ansible you are using.   I'm assuming 1.3.X?

What has happened here though is you've passed in "string false"

You could pass in "-e" as JSON to force the boolean.

I'm confused about what you are trying to do with the |default though.

I would have just done this:

```
   - name: test 1
     debug: msg="foo is {{ foo }}"
     when: foo | bool
```

And that will cast it for sure.

You can also make sure variables are loaded with type information by using group_vars or host_vars directories and in 1.4 even those inline in inventory files come back with proper types

But as given, there's no way to know what you meant was a "false" vs a boolean False, and that seems to be the problem.

If there are further questions please stop by ansible-devel

Thanks!

**Comment by mpdehaan** [comment]
update: Fixed  formatting
