### ISSUE TITLE
with_fileglob returns full path

### ISSUE THREAD

**Issue by ninetythirty** [ansible/ansible#4551]
The with_fileglob plugin incorrectly adds the full path to {{ item }}.

Playbook: 
- name: Static libraries exist
  copy: src={{ item }} dest=/usr/local/lib/app/{{ item }}
  with_fileglob:
  - lib/app/*.a

Output:

failed: [X.X.X.X] => (item=/path/to/roles/role/files/lib/app/match_timediff.a) => {"failed": true, "item": "/path/to/roles/role/files/lib/app/match_timediff.a"}
msg: Destination directory /usr/local/lib/app//path/to/roles/monitoring/files/lib/app does not exist

Is this the same as #1618 which was fixed by #1643?

Ansible version 1.3.3

**Comment by mpdehaan** [comment]
I'm not sure this is undesirable, because you can do {{ item | filename }} and get the filename part but may actually want the full path in many cases.

I am going to close this given the above solution exists.

**Comment by mkubenka** [comment]
Just for future reference, don't you mean `{{ item | basename }}` ?
