### ISSUE TITLE
devel: bug on user module with createhome enforcement

### ISSUE THREAD

**Issue by jeromew** [ansible/ansible#4554]
Hello,

after commit https://github.com/ansible/ansible/commit/23cbdba65e0f7e8cfd93be8e736244a2b1bec506
a new bug appeared on the user module 

when home creation relies on the "default" homedir (/root, or /home/user) and user.home is not defined, ansible breaks.

fatal: [IP] => failed to parse: Traceback (most recent call last):
  File "/home/xx/.ansible/tmp/ansible-1382005747.2-31396738490267/user", line 2461, in <module>
    main()
  File "/home/xx/.ansible/tmp/ansible-1382005747.2-31396738490267/user", line 1516, in main
    if not os.path.exists(user.home) and user.createhome:
  File "/usr/lib64/python2.6/genericpath.py", line 18, in exists
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

I first added a test on the existence of user.home but I think the patch should probably include a default value for user.home so I prefer leaving it to someone who knows the module better.

**Comment by jctanner** [comment]
@jeromew thanks for the report. The committed fix was tested against the following playbook ...

<pre>
- hosts: el6.lab.net
  gather_facts: False
  tasks:
    - shell: userdel bob
    - group: name=bob state=present
    - name: create user + homedir
      user: name=bob group=bob state=present system=yes createhome=yes
    - file: path=/home/bob state=absent
    - name: create user + homedir
      user: name=bob group=bob state=present system=yes createhome=yes
</pre>
