### ISSUE TITLE
Lookup 'template' with roles searches in <role>/files instead of <role>/templates

### ISSUE THREAD

**Issue by gwillem** [ansible/ansible#4555]
(ansible 1.3.3)

``` yaml
- authorized_key: user=mysql key='{{ lookup('template', 'auth-keys/mysql-backup-restrict-rsync.j2' )}}'
```

yields

```
fatal: [10.0.3.67] => unable to read FULLPATH/ansible/roles/mysql-master/files/auth-keys/mysql-backup-restrict-rsync.j2
```

**Comment by mpdehaan** [comment]
This is not a bug, but is in fact intended for lookup plugins.

Hardly anyone uses the template lookup plugin -- it's actually not even documented, so I'm not particularly concerned.

You can "../templates" to get where you want to go.
