### ISSUE TITLE
Problem with authorized_keys and key_options

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#4556]
Hello,

I am trying to prepend the following string to a key

```
key_options='environment="KEYOWNER={{item}}"'
```

So that this variable gets injected in the remote host.
However the double quotes are stripped from the string and the result is

```
environment KEYOWNER=name <<SSH_KEY>>
```

Am I doing something wrong?

**Comment by jimi-c** [comment]
This is due to the way the arguments are parsed from the YAML file (which is done through the python shlex module). To get this to work properly, just escape the quotes:

<pre>
key_options='environment=\"KEYOWNER={{item}}\"'
</pre>

**Comment by jimi-c** [comment]
Going to go ahead and close this issue, let us know if you have any other issues regarding this module. Thanks!

**Comment by ghost** [comment]
Hello, thank you for answering.
I tried all sorts of escaping and none of them seemed to work. Will try again and let you know.
