### ISSUE TITLE
Unable to install ansible on windows 7

### ISSUE THREAD

**Issue by chenhb-zte** [ansible/ansible#45672]
##### SUMMARY
 os.symlink attribute can not be found while installing ansible via `pip install ansible` on windows 7.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION
latest version

##### CONFIGURATION
None

##### OS / ENVIRONMENT
windows 7, python 2.7.13

##### STEPS TO REPRODUCE
None

##### ACTUAL RESULTS
```
      File "c:\users\test\appdata\local\temp\pip-install-y2ob82\ansible\setup.py", line 103, in
run
        _maintain_symlinks('library', self.build_lib)
      File "c:\users\test\appdata\local\temp\pip-install-y2ob82\ansible\setup.py", line 97, in _
maintain_symlinks
        os.symlink(source, dest_path)
    AttributeError: 'module' object has no attribute 'symlink'
```

**Comment by mscherer** [comment]
Ansible is not supported on Windows, at least not as a controller: 

https://docs.ansible.com/ansible/latest/user_guide/windows_faq.html#can-ansible-run-on-windows

I would recommend getting a newer version of windows with WSL, or getting a Linux VM if you can. 

Therefor, closing this issue.

**Comment by chenhb-zte** [comment]
Thanks
