### ISSUE TITLE
Solaris interface(nxge2:4) KeyError: 'nxge2:4'

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#4567]
Hey, 

We are getting the below when gathering facts: 

ansible-playbook -i ./hosts ./blah.yml -vvvvv

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
<ndcpeh581> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO ndcpeh581
<ndcpeh582> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO ndcpeh582
<ndcpeh582> EXEC /bin/sh -c 'mkdir -p /tmp/.ansible/tmp/ansible-1382029803.83-89067387745201 && echo /tmp/.ansible/tmp/ansible-1382029803.83-89067387745201'
<ndcpeh581> EXEC /bin/sh -c 'mkdir -p /tmp/.ansible/tmp/ansible-1382029803.9-261043832837157 && echo /tmp/.ansible/tmp/ansible-1382029803.9-261043832837157'
<ndcpeh582> REMOTE_MODULE setup
<ndcpeh582> PUT /tmp/tmpzdqSSA TO /tmp/.ansible/tmp/ansible-1382029803.83-89067387745201/setup
<ndcpeh581> REMOTE_MODULE setup
<ndcpeh581> PUT /tmp/tmpo0dHdl TO /tmp/.ansible/tmp/ansible-1382029803.9-261043832837157/setup
<ndcpeh582> EXEC /bin/sh -c '/usr/bin/python /tmp/.ansible/tmp/ansible-1382029803.83-89067387745201/setup; rm -rf /tmp/.ansible/tmp/ansible-1382029803.83-89067387745201/ >/dev/null 2>&1'
<ndcpeh581> EXEC /bin/sh -c '/usr/bin/python /tmp/.ansible/tmp/ansible-1382029803.9-261043832837157/setup; rm -rf /tmp/.ansible/tmp/ansible-1382029803.9-261043832837157/ >/dev/null 2>&1'
failed: [ndcpeh581] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/tmp/.ansible/tmp/ansible-1382029803.9-261043832837157/setup", line 3108, in <module>
    main()
  File "/tmp/.ansible/tmp/ansible-1382029803.9-261043832837157/setup", line 2169, in main
    data = run_setup(module)
  File "/tmp/.ansible/tmp/ansible-1382029803.9-261043832837157/setup", line 2107, in run_setup
    facts = ansible_facts()
  File "/tmp/.ansible/tmp/ansible-1382029803.9-261043832837157/setup", line 2098, in ansible_facts
    facts.update(Network().populate())
  File "/tmp/.ansible/tmp/ansible-1382029803.9-261043832837157/setup", line 1538, in populate
    self.merge_default_interface(default_ipv4, interfaces, 'ipv4')
  File "/tmp/.ansible/tmp/ansible-1382029803.9-261043832837157/setup", line 1715, in merge_default_interface
    ifinfo = interfaces[defaults['interface']]
KeyError: 'nxge2:4'

failed: [ndcpeh582] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/tmp/.ansible/tmp/ansible-1382029803.83-89067387745201/setup", line 3108, in <module>
    main()
  File "/tmp/.ansible/tmp/ansible-1382029803.83-89067387745201/setup", line 2169, in main
    data = run_setup(module)
  File "/tmp/.ansible/tmp/ansible-1382029803.83-89067387745201/setup", line 2107, in run_setup
    facts = ansible_facts()
  File "/tmp/.ansible/tmp/ansible-1382029803.83-89067387745201/setup", line 2098, in ansible_facts
    facts.update(Network().populate())
  File "/tmp/.ansible/tmp/ansible-1382029803.83-89067387745201/setup", line 1538, in populate
    self.merge_default_interface(default_ipv4, interfaces, 'ipv4')
  File "/tmp/.ansible/tmp/ansible-1382029803.83-89067387745201/setup", line 1715, in merge_default_interface
    ifinfo = interfaces[defaults['interface']]
KeyError: 'nxge2:4'

TASK: [test] ******************************************************************
FATAL: no hosts matched or all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/blah.retry

ndcpeh581                  : ok=0    changed=0    unreachable=0    failed=1
ndcpeh582                  : ok=0    changed=0    unreachable=0    failed=1

---
- hosts: all
  user: root
  
  tasks:
  - name: test
    shell: df -h

**Comment by ghost** [comment]
Not sure whats going on, but it just worked and when I re-ran it failed.

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
<ndcpeh581> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO ndcpeh581
<bep26> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO bep26
<ndcpeh581> EXEC /bin/sh -c 'mkdir -p /tmp/.ansible/tmp/ansible-1382033632.48-229821587920839 && echo /tmp/.ansible/tmp/ansible-1382033632.48-229821587920839'
<ndcpeh581> REMOTE_MODULE setup
<ndcpeh581> PUT /tmp/tmpxUV7_S TO /tmp/.ansible/tmp/ansible-1382033632.48-229821587920839/setup
<bep26> EXEC /bin/sh -c 'mkdir -p /tmp/.ansible/tmp/ansible-1382033632.6-105946088253150 && echo /tmp/.ansible/tmp/ansible-1382033632.6-105946088253150'
<bep26> REMOTE_MODULE setup
<bep26> PUT /tmp/tmpWk3kuS TO /tmp/.ansible/tmp/ansible-1382033632.6-105946088253150/setup
<ndcpeh581> EXEC /bin/sh -c '/usr/bin/python /tmp/.ansible/tmp/ansible-1382033632.48-229821587920839/setup; rm -rf /tmp/.ansible/tmp/ansible-1382033632.48-229821587920839/ >/dev/null 2>&1'
<bep26> EXEC /bin/sh -c '/usr/bin/python /tmp/.ansible/tmp/ansible-1382033632.6-105946088253150/setup; rm -rf /tmp/.ansible/tmp/ansible-1382033632.6-105946088253150/ >/dev/null 2>&1'
ok: [ndcpeh581]
ok: [bep26]

TASK: [test] ******************************************************************
<bep26> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO bep26
<ndcpeh581> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO ndcpeh581
<ndcpeh581> EXEC /bin/sh -c 'mkdir -p /tmp/.ansible/tmp/ansible-1382033637.41-154347081534873 && echo /tmp/.ansible/tmp/ansible-1382033637.41-154347081534873'
<ndcpeh581> REMOTE_MODULE command df -h #USE_SHELL
<ndcpeh581> PUT /tmp/tmpxUV7_S TO /tmp/.ansible/tmp/ansible-1382033637.41-154347081534873/command
<bep26> EXEC /bin/sh -c 'mkdir -p /tmp/.ansible/tmp/ansible-1382033637.52-19827152058702 && echo /tmp/.ansible/tmp/ansible-1382033637.52-19827152058702'
<bep26> REMOTE_MODULE command df -h #USE_SHELL
<ndcpeh581> EXEC /bin/sh -c '/usr/bin/python /tmp/.ansible/tmp/ansible-1382033637.41-154347081534873/command; rm -rf /tmp/.ansible/tmp/ansible-1382033637.41-154347081534873/ >/dev/null 2>&1'
<bep26> PUT /tmp/tmpxUV7_S TO /tmp/.ansible/tmp/ansible-1382033637.52-19827152058702/command
<bep26> EXEC /bin/sh -c '/usr/bin/python /tmp/.ansible/tmp/ansible-1382033637.52-19827152058702/command; rm -rf /tmp/.ansible/tmp/ansible-1382033637.52-19827152058702/ >/dev/null 2>&1'
changed: [ndcpeh581] => {"changed": true, "cmd": "df -h ", "delta": "0:00:00.037185", "end": "2013-10-17 18:15:05.375029", "rc": 0, "start": "2013-10-17 18:15:05.337844", "stderr": "", "stdout": "Filesystem                                                      Size  Used Avail Use% Mounted on\n/                                                                15G  1.8G   13G  12% /\n/dev                                                             15G  1.8G   13G  12% /dev\n/ehbackups                                                      493G  167G  322G  35% /ehbackups\n/ehdb                                                           394G  207G  184G  54% /ehdb\n/ehealth                                                         40G   14G   26G  36% /ehealth\nswap                                                             28G  8.7G   20G  31% /etc/svc/volatile\n/platform/SUNW,T5140/lib/libc_psr/libc_psr_hwcap2.so.1           15G  1.8G   13G  12% /platform/sun4v/lib/libc_psr.so.1\n/platform/SUNW,T5140/lib/sparcv9/libc_psr/libc_psr_hwcap2.so.1   15G  1.8G   13G  12% /platform/sun4v/lib/sparcv9/libc_psr.so.1\nswap                                                             28G  8.7G   20G  31% /tmp\nswap                                                             28G  8.7G   20G  31% /var/run"}
changed: [bep26] => {"changed": true, "cmd": "df -h ", "delta": "0:00:00.059384", "end": "2013-10-17 18:15:01.146897", "rc": 0, "start": "2013-10-17 18:15:01.087513", "stderr": "", "stdout": "Filesystem                                                      Size  Used Avail Use% Mounted on\n/                                                                15G  4.1G   11G  28% /\n/dev                                                             15G  4.1G   11G  28% /dev\n/ehbackups                                                      887G  518G  361G  59% /ehbackups\n/ehdb                                                           985G  633G  343G  65% /ehdb\n/ehealth                                                         40G   13G   27G  33% /ehealth\n/opt/peData                                                      30G  7.0G   23G  24% /opt/peData\nswap                                                             61G  312K   61G   1% /etc/svc/volatile\n/platform/SUNW,T5140/lib/libc_psr/libc_psr_hwcap2.so.1           15G  4.1G   11G  28% /platform/sun4v/lib/libc_psr.so.1\n/platform/SUNW,T5140/lib/sparcv9/libc_psr/libc_psr_hwcap2.so.1   15G  4.1G   11G  28% /platform/sun4v/lib/sparcv9/libc_psr.so.1\nswap                                                             61G   68M   61G   1% /tmp\nswap                                                             61G  184K   61G   1% /var/run"}

PLAY RECAP ********************************************************************
bep26                      : ok=2    changed=1    unreachable=0    failed=0
ndcpeh581                  : ok=2    changed=1    unreachable=0    failed=0

[root@ndcpans01 ~]# ansible-playbook -i ./hosts ./blah.yml -vvvvv

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
<bep26> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO bep26
<ndcpeh581> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO ndcpeh581
<ndcpeh581> EXEC /bin/sh -c 'mkdir -p /tmp/.ansible/tmp/ansible-1382033668.53-63530341182995 && echo /tmp/.ansible/tmp/ansible-1382033668.53-63530341182995'
<bep26> EXEC /bin/sh -c 'mkdir -p /tmp/.ansible/tmp/ansible-1382033668.55-27699177898106 && echo /tmp/.ansible/tmp/ansible-1382033668.55-27699177898106'
<ndcpeh581> REMOTE_MODULE setup
<ndcpeh581> PUT /tmp/tmpF2FsKT TO /tmp/.ansible/tmp/ansible-1382033668.53-63530341182995/setup
<bep26> REMOTE_MODULE setup
<bep26> PUT /tmp/tmpO1ybkK TO /tmp/.ansible/tmp/ansible-1382033668.55-27699177898106/setup
<ndcpeh581> EXEC /bin/sh -c '/usr/bin/python /tmp/.ansible/tmp/ansible-1382033668.53-63530341182995/setup; rm -rf /tmp/.ansible/tmp/ansible-1382033668.53-63530341182995/ >/dev/null 2>&1'
<bep26> EXEC /bin/sh -c '/usr/bin/python /tmp/.ansible/tmp/ansible-1382033668.55-27699177898106/setup; rm -rf /tmp/.ansible/tmp/ansible-1382033668.55-27699177898106/ >/dev/null 2>&1'
failed: [ndcpeh581] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/tmp/.ansible/tmp/ansible-1382033668.53-63530341182995/setup", line 3116, in <module>
    main()
  File "/tmp/.ansible/tmp/ansible-1382033668.53-63530341182995/setup", line 2177, in main
    data = run_setup(module)
  File "/tmp/.ansible/tmp/ansible-1382033668.53-63530341182995/setup", line 2118, in run_setup
    facts = ansible_facts()
  File "/tmp/.ansible/tmp/ansible-1382033668.53-63530341182995/setup", line 2109, in ansible_facts
    facts.update(Network().populate())
  File "/tmp/.ansible/tmp/ansible-1382033668.53-63530341182995/setup", line 1549, in populate
    self.merge_default_interface(default_ipv4, interfaces, 'ipv4')
  File "/tmp/.ansible/tmp/ansible-1382033668.53-63530341182995/setup", line 1726, in merge_default_interface
    ifinfo = interfaces[defaults['interface']]
KeyError: 'nxge2:4'

ok: [bep26]

TASK: [test] ******************************************************************
<bep26> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO bep26
<bep26> EXEC /bin/sh -c 'mkdir -p /tmp/.ansible/tmp/ansible-1382033673.14-196797792703042 && echo /tmp/.ansible/tmp/ansible-1382033673.14-196797792703042'
<bep26> REMOTE_MODULE command df -h #USE_SHELL
<bep26> PUT /tmp/tmpF2FsKT TO /tmp/.ansible/tmp/ansible-1382033673.14-196797792703042/command
<bep26> EXEC /bin/sh -c '/usr/bin/python /tmp/.ansible/tmp/ansible-1382033673.14-196797792703042/command; rm -rf /tmp/.ansible/tmp/ansible-1382033673.14-196797792703042/ >/dev/null 2>&1'
changed: [bep26] => {"changed": true, "cmd": "df -h ", "delta": "0:00:00.042636", "end": "2013-10-17 18:15:36.763640", "rc": 0, "start": "2013-10-17 18:15:36.721004", "stderr": "", "stdout": "Filesystem                                                      Size  Used Avail Use% Mounted on\n/                                                                15G  4.1G   11G  28% /\n/dev                                                             15G  4.1G   11G  28% /dev\n/ehbackups                                                      887G  518G  361G  59% /ehbackups\n/ehdb                                                           985G  633G  343G  65% /ehdb\n/ehealth                                                         40G   13G   27G  33% /ehealth\n/opt/peData                                                      30G  7.0G   23G  24% /opt/peData\nswap                                                             61G  312K   61G   1% /etc/svc/volatile\n/platform/SUNW,T5140/lib/libc_psr/libc_psr_hwcap2.so.1           15G  4.1G   11G  28% /platform/sun4v/lib/libc_psr.so.1\n/platform/SUNW,T5140/lib/sparcv9/libc_psr/libc_psr_hwcap2.so.1   15G  4.1G   11G  28% /platform/sun4v/lib/sparcv9/libc_psr.so.1\nswap                                                             61G   68M   61G   1% /tmp\nswap                                                             61G  184K   61G   1% /var/run"}

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/blah.retry

bep26                      : ok=2    changed=1    unreachable=0    failed=0
ndcpeh581                  : ok=0    changed=0    unreachable=0    failed=1

**Comment by ghost** [comment]
FIX:

```
def merge_default_interface(self, defaults, interfaces, ip_type):
     try:
         #print "self, defaults, interfaces, ip_type", self, defaults, interfaces, ip_type
         if not 'interface' in defaults.keys():
             return
         ifinfo = interfaces[defaults['interface']]
         # copy all the interface values across except addresses
         for item in ifinfo.keys():
             if item != 'ipv4' and item != 'ipv6':
                 defaults[item] = ifinfo[item]
         if len(ifinfo[ip_type]) > 0:
             for item in ifinfo[ip_type][0].keys():
                 defaults[item] = ifinfo[ip_type][0][item]
     except:
         pass
```

**Comment by mpdehaan** [comment]
Sure, as discussed on IRC, send a pull request along?

**Comment by mpdehaan** [comment]
Seeing there is a pull request about this I am going to close the ticket as the PR is also a ticket
