### ISSUE TITLE
Deprecation warning is triggered by ^mysql\$ string in template

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#4569]
String was found in [/etc/default/automysqlbackup configuration](https://github.com/drybjed/ansible-aiua/blob/master/playbooks/roles/mysql/templates/etc/default/automysqlbackup.j2#L25).

**Comment by mscherer** [comment]
Could you post a reproducer ( ie, a ansible playbook, if needed, the platform where this happen, etc ) ?

**Comment by drybjed** [comment]
It was on Ubuntu 13.04, deployed system was Debian Wheezy. [Example playbook](https://github.com/drybjed/ansible-tests).

**Comment by mscherer** [comment]
So yeah, \$ trigger the deprecation warning, and this is replaced by '$', see here: https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/template.py#L164

I am not exactly sure on what to do here. Any change in semantic would break the old system.

**Comment by drybjed** [comment]
It's not a critical bug, and I suppose when legacy support will be removed, warnings will disappear too. It's good to know where the problem exists in case somebody else stumbles upon it. I'm closing the issue.
