### ISSUE TITLE
Until loop doesn't work as expected with actions that fail

### ISSUE THREAD

**Issue by gregkare** [ansible/ansible#4572]
I was trying to use the `uri` module with a `until` to wait for a web application to be really up (the port responds but it takes a while for the API to be usable, so I can't rely on `wait_for`). It took me a while to realize this issue was happening because I set a delay on my `wait_for`, so sometimes the API was responding. I want to avoid using delays and just retry until the API is available.

This is of course on the develop branch, up-to-date.
- If I'm using a `command` to use curl, it keeps trying the specified number of times after the specified delay: https://gist.github.com/gkarekinian/f8711829b3e2a1ee4ce6#file-works_output
- If I'm using a `uri`, it stops trying after the first try: https://gist.github.com/gkarekinian/f8711829b3e2a1ee4ce6#file-test-yml
- If I'm using a `uri` with `ignore_errors: True`, it ignores the error and does not try again: https://gist.github.com/gkarekinian/f8711829b3e2a1ee4ce6#file-test_with_ignore_errors

There's more info in the gist: https://gist.github.com/gkarekinian/f8711829b3e2a1ee4ce6

I'm expecting until to work the same as it does for a `command`: ignore the error and try again the set number of times. I would look at the code but it's pretty late here and I'm going to sleep.

**Comment by mpdehaan** [comment]
Yep, I agree this is goofy.

Until it's the last iteration any errors should be swallowed.

The last one should matter unless ignore_errors is set.

**Comment by jctanner** [comment]
random exit httpd: https://gist.github.com/jctanner/7199435

**Comment by jctanner** [comment]
Thanks to benno for this fix!
