### ISSUE TITLE
remove in docs where it says there might be some other variables

### ISSUE THREAD

**Issue by lfrancke** [ansible/ansible#4575]
The documentation about [Variables](http://www.ansibleworks.com/docs/playbooks_variables.html#magic-variables-and-how-to-access-information-about-other-hosts) has a sentence suggesting that there might be some undocumented Magic variables:

> Just a few other ‘magic’ variables are available... There aren’t many.

To me that sounds like there are more _magic_ variables than mentioned in the documentation. If others feel similar it'd be great to clear this paragraph by explicitly listing all the magic variables.

**Comment by jpcaruana** [comment]
:+1:

**Comment by mpdehaan** [comment]
done, thanks!
