### ISSUE TITLE
Testing definedness of variables does not work for undefined variables in when conditions

### ISSUE THREAD

**Issue by thomasvnoort** [ansible/ansible#4579]
I'm running into some strange behaviour when checking for definedness of variables and using these in the when-conditions of tasks. 

I'm running ansible 1.4 from the devel branch (that is, commit b0f6e77f66f77cc3765f3f084d9a9b19a041b815).

Please consider the following playbook:

```

---
- hosts: localhost
  connection: local
  vars:
    a: "a"
    check_a: "{{ a is defined }}"
    check_b: "{{ b is defined }}"
  tasks:
  - debug: msg="check_a is {{ check_a }}"

  - debug: msg="when check_a"
    when: check_a

  - debug: msg="when not check_a"
    when: not check_a

  - debug: msg="check_b is {{ check_b }}"

  - debug: msg="when check_b"
    when: check_b

  - debug: msg="when not check_b"
    when: not check_b
```

The output is as follows:

```
PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************

ok: [127.0.0.1]

TASK: [debug msg="check_a is True"] *******************************************

ok: [127.0.0.1] => {
    "msg": "check_a is True"
}

TASK: [debug msg="when check_a"] **********************************************

ok: [127.0.0.1] => {
    "msg": "when check_a"
}

TASK: [debug msg="when not check_a"] ******************************************

TASK: [debug msg="check_b is False"] ******************************************

ok: [127.0.0.1] => {
    "msg": "check_b is False"
}

TASK: [debug msg="when check_b"] **********************************************

TASK: [debug msg="when not check_b"] ******************************************

PLAY RECAP ********************************************************************
127.0.0.1                  : ok=4    changed=0    unreachable=0    failed=0
```

Strangely, none of the two debug messages for `b` fire, even though `check_b` is `False`.

**Comment by mpdehaan** [comment]
I have a RFE open to keep the types of variables in place when being evaluated, that may help here.

I would suggest not establishing the conditional in the variable for now.

I suspect the value is string "True", not True, and that's what is happening there.

**Comment by mpdehaan** [comment]
I recently pushed code to take care of all of the above.  As a result, this all appears to be working on the latest development branch for me.

Let me know if you experience any problems.

Thanks!

**Comment by thomasvnoort** [comment]
Unfortunately, this doesn't work for us. I've tried the exact same example with the latest ansible from the devel branch (commit c876ce4b8a39d57915a422a17df5dd15ada73785), but I get the exact same output. 

Additionally, using the lookup function seems to be broken now. For example:

```
vars:
  aws_key: "{{ lookup('env', 'AWS_KEY') }}"
```

Such a definition now results in error like:

`One or more undefined variables: 'lookup' is undefined`

We also use this function in our ansible configuration for the locations of the hosts file and the roles path, but those do not seem to expand anymore. It seems like commit 35cb9dc22fca1851a716917dff9d224ad4fa06f7 broke this specifically, but we're not 100% sure. If you'd prefer, I can create a separate issue for this.

**Comment by thomasvnoort** [comment]
Someone already reported the error with the lookup plugin, #4608.
