### ISSUE TITLE
Solaris prtdiag hangs during gather facts

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#4583]
This seems to be a known issue with solaris 10. way to fix is to restart picl before running prtdiag. 

Could add something like the below to setup: 
    def get_virtual_facts(self):
        module.run_command("svcadm restart svc:/system/picl:default")
        rc, out, err = module.run_command("/usr/sbin/prtdiag")

python debug output:

-bash-3.00# python -m pdb setup

> /tmp/.ansible/tmp/ansible-1382106487.8-10732644317884/setup(21)<module>()
> -> import os
> (Pdb) continue

^C{"msg": "Traceback (most recent call last):\n  File \"setup\", line 3089, in run_command\n    out, err = cmd.communicate(input=data)\n  File \"/opt/csw/lib/python2.6/subprocess.py\", line 691, in communicate\n    return self._communicate(inpu
t)\n  File \"/opt/csw/lib/python2.6/subprocess.py\", line 1211, in _communicate\n    rlist, wlist, xlist = select.select(read_set, write_set, [])\nKeyboardInterrupt\n", "failed": true, "cmd": "/usr/sbin/prtdiag", "rc": 257}
The program exited via sys.exit(). Exit status:  1

**Comment by jctanner** [comment]
Sorry, closed the wrong bug

**Comment by rrtj3** [comment]
I've seen prtdiag hang, though when using puppet's facter, and indeed restarting picl temporarily fixes the issue. I'm not sure I'm comfortable with the idea of restarting it on every box every time setup is run when it's usually only an issue on a few boxes. If you're going to try to work around the issue in code maybe there's a way to catch the exception on the boxes that do fail on prtdiag and restart picl only then.

**Comment by ghost** [comment]
It does not throw an exception it just hangs, I waited for 30 minutes today
before I killed it.  Could just time the prtdiag and if it takes longer
than 5 seconds throw an warning to manually restart picl on that box. That
is, if automatically restarting it is not wanted in the setup module.

John

On Fri, Oct 18, 2013 at 3:11 PM, Romeo Theriault
notifications@github.comwrote:

> I've seen prtdiag hang, though when using puppet's facter, and indeed
> restarting picl temporarily fixes the issue. I'm not sure I'm comfortable
> with the idea of restarting it on every box every time setup is run when
> it's usually only an issue on a few boxes. If you're going to try to work
> around the issue in code maybe there's a way to catch the exception on the
> boxes that do fail on prtdiag and restart picl only then.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/4583#issuecomment-26621932
> .

## 

-John

**Comment by mpdehaan** [comment]
Sounds like the solution might be to not call it in the facts if it is unreliable, though you could also execute it in a subprocess (painful) and kill it if a timeout is exceeded.

I think I'd rather remove it, if that seems reasonable?

**Comment by brettheath** [comment]
I would like to see the warning to restart picl rather than removal of the prtdiag info

**Comment by ghost** [comment]
Hi,

all prtdiag is giving is the 'BIOS Configuration:'. Is this truly needed?

rc, out, err = module.run_command("/usr/sbin/prtdiag")
        for line in out.split('\n'):
            if 'VMware' in line:
                self.facts['virtualization_type'] = 'vmware'
                self.facts['virtualization_role'] = 'guest'
            if 'Parallels' in line:
                self.facts['virtualization_type'] = 'parallels'
                self.facts['virtualization_role'] = 'guest'
            if 'VirtualBox' in line:
                self.facts['virtualization_type'] = 'virtualbox'
                self.facts['virtualization_role'] = 'guest'
            if 'HVM domU' in line:
                self.facts['virtualization_type'] = 'xen'
                self.facts['virtualization_role'] = 'guest'

There maybe other ways to get this information. prtconf may work but it may
also rely on the picl service.

On Sat, Oct 19, 2013 at 1:34 PM, brettheath notifications@github.comwrote:

> I would like to see the warning to restart picl rather than removal of the
> prtdiag info
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/4583#issuecomment-26654781
> .

## 

-John

**Comment by brettheath** [comment]
I was looking at it from the SPARC perspective, and prtdiag has a lot of useful info, but I'll bet you could glean just about all of it from other commands.

**Comment by ghost** [comment]
from the setup module the only thing prtdiag is use for is virtualization_type/role. Any idea what other commands or files may contain that info? I been seaching with no luck.

**Comment by dagwieers** [comment]
Is it possible that prtdiag behaves differently when there is a pseudo-tty, rather than no tty ?

A lot of Ansible 'hangs' are related to the fact that commands run with a pseudo-tty, and so it may issue a prompt to the user, rather than be silent.

**Comment by rrtj3** [comment]
@dagwieers , I don't believe it behaves differently in this case. When I've seen prtdiag hang with 'facter' in the past it would also hang when I ran it manually in a terminal.

**Comment by jimi-c** [comment]
Can anyone confirm if this is still an issue?

**Comment by bcoca** [comment]
Can anyone confirm that my patch fixes this? #17464

**Comment by mavit** [comment]
It's still an issue.

I can confirm that the patch allows `setup` to complete on a Solaris 10 SPARC host that has a hanging `prtdiag`.  I can also confirm that, for LDoms, `ansible_virtualization_role` and `ansible_virtualization_type` are collected as previously using the information returned by `virtinfo`.
