### ISSUE TITLE
How to syntax check list of tasks

### ISSUE THREAD

**Issue by furstenheim** [ansible/ansible#45851]
##### SUMMARY

This might be in the docs, but I cannot find it. I have the following files:

   first-playbook.yml
   second-playbook.yml
   common-tasks.yml

common-tasks.yml is a list of tasks that is used in first-playbook.yml and second-playbook.yml through `include_tasks common-tasks.yml`

I'd like to syntax check everything before deploying. For playbooks I can do:

    ansible-playbook --syntax-check first-playbook.yml

However, it is not possible for common tasks because it is a list of tasks
https://github.com/ansible/ansible/issues/16778
Another option would be that tasks got validated when including them, but that is not the case:
https://github.com/ansible/ansible/issues/15709

Is there a flag/ansible command that I can use to syntax check a list of tasks?

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below
ansible 2.6.4

```

##### CONFIGURATION

```paste below

```

**Comment by jborean93** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
