### ISSUE TITLE
Variable containing a column in their name are difficult to access :  "ansible_eth0:0"

### ISSUE THREAD

**Issue by Oldkarkass** [ansible/ansible#4586]
Hi

I had an issue to access a variable named  "ansible_eth0:0" in a template. 
This is with ansible 1.3.2
More details here : https://groups.google.com/forum/#!topic/ansible-project/MURGULUV2mU

Thanks
Frank

**Comment by mpdehaan** [comment]
Is it safe to delete from a collection while iterating across them?

Might want to do this in two steps?

Thanks!

**Comment by mscherer** [comment]
I tested it, but only with 1 single interface, and indeed, that would be safer. I will push a updated module soon.
