### ISSUE TITLE
apt_repository says Linux Mint is unsupported

### ISSUE THREAD

**Issue by sharjeel** [ansible/ansible#4587]
Adding a PPA on LinuxMint with Ansbile fails with the following message:

`msg: Module apt_repository supports only Debian and Ubuntu.`

LinuxMint is a derivative of Ubuntu. Ubuntu's repositories work well for LinuxMint. Support for Ubuntu should imply support for LinuxMint

**Comment by mscherer** [comment]
If you run the following:

```
import aptsources.distro
distro = aptsources.distro.get_distro()
print distro
```

In a python shell, what is printed on screen ?

**Comment by mpdehaan** [comment]
I'm fine with this being upgraded to also work on Mint, provided it is then tested and works properly.

Some distros handle apt repository differently hence the Ubuntu variance explicit in the code.

If you would like to submit a pull request to make this work, that would be welcome.

**Comment by bcoca** [comment]
I'm thinking we reverse this, if ubuntu then use specific case, else try
debian style.

if users of other debian derivatives run into problems we can then solve
those, right now they cannot use the module at all.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mscherer** [comment]
The problem is that Mint is not properly integrated into python-apt. The python module detect if that's a Debian, a Ubuntu or a generic derivate. And mint identify itself as generic, as this is the default answer. 

So either we take this in account and make generic treated like Debian ( that mean no ppa ), or we add a special case to fix the bug in ansible. Or we ask to upstream to properly fix and we wait until this is fixed, to avoid adding a hack in ansible.

In the meantime, I will propose a patch that treat generic as regular debian, so at least, the module is not completly broken on mint.

**Comment by mscherer** [comment]
In fact, since apt_repository use the codename of the linux distribution to find what PPA url to use, and since LinuxMint changed the codename, the current code cannot add the proper url. However, it seems that apt-add-ppa is able to guess the release, so maybe someone can find a way.

**Comment by jcftang** [comment]
this commit breaks when "repo='ppa:someuser/somerepo" on an ubuntu system

perhaps something like this might be better?

<pre>
commit 0568abeb1471e54e0796bcf41d623ece003223bb
Author: Jimmy Tang <jcftang@gmail.com>
Date:   Sat Oct 19 14:41:00 2013 +0100
    check for ubuntu distribution first
diff --git a/library/packaging/apt_repository b/library/packaging/apt_repository
index 55994ed..c77a644 100644
--- a/library/packaging/apt_repository
+++ b/library/packaging/apt_repository
@@ -349,11 +349,11 @@ def main():
     update_cache = module.params['update_cache']
     sourceslist = None
-    if isinstance(distro, aptsources.distro.DebianDistribution) or \
+    if isinstance(distro, aptsources.distro.UbuntuDistribution):
+        sourceslist = UbuntuSourcesList(add_ppa_signing_keys_callback=get_add_ppa_signing_key_callb
+    elif isinstance(distro, aptsources.distro.DebianDistribution) or \
             isinstance(distro, aptsources.distro.Distribution):
         sourceslist = SourcesList()
-    elif isinstance(distro, aptsources.distro.UbuntuDistribution):
-        sourceslist = UbuntuSourcesList(add_ppa_signing_keys_callback=get_add_ppa_signing_key_callb
     else:
         module.fail_json(msg='Module apt_repository supports only Debian and Ubuntu.')
</pre>

**Comment by mscherer** [comment]
yep, clearly. I just did a quick test on a Mint distro I installed, I forgot about this one. 
Can you make a PR for that one ?

**Comment by jcftang** [comment]
will do, the above works for me on ubuntu, you will need to test on debian/mint to make sure its all working as expected.

**Comment by alefteris** [comment]
Still not able to add a PPA in Linux Mint 17.1 with the apt_repository module:

```
msg: Invalid repository string: ppa:git-core/ppa
```

Some relevant info that might be useful for solving the issue:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 17.1 Rebecca
Release:    17.1
Codename:   rebecca
```

```
$ cat /etc/upstream-release/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04 LTS"
```

```
$ whereis add-apt-repository 
add-apt-repository: /usr/bin/add-apt-repository /usr/bin/X11/add-apt-repository
$ dpkg -S /usr/bin/add-apt-repository
mintsources: /usr/bin/add-apt-repository
```

Relevant python source code file from the mintsources package: https://github.com/linuxmint/mintsources/blob/master/usr/lib/linuxmint/mintSources/mintSources.py . It seems that even though they are importing `aptsources.distro` they don't use it.

Mintsources config is at /usr/share/mintsources/rebecca/mintsources.conf. Interesting section of it:

```
[general]
description=Linux Mint 17.1 "Rebecca"
codename=rebecca
base_codename=trusty
use_ppas=true
```

```
$ python
>>> import aptsources.distro
>>> aptsources.distro.get_distro()
<aptsources.distro.Distribution object at 0x7f1f14dcad50>
```

apt_repository python source code is at https://github.com/ansible/ansible-modules-core/blob/devel/packaging/os/apt_repository.py

There has has also been an issue opened against python-apt https://bugs.launchpad.net/ubuntu/+source/python-apt/+bug/1414229
