### ISSUE TITLE
ansible cross pm2: fail.

### ISSUE THREAD

**Issue by zhuangya** [ansible/ansible#4589]
there is an unicode `\u232c` : ⌬ in [pm2](https://github.com/Unitech/pm2)'s output resule.

and when `ansible` come across this character, it would complain:

```
UnicodeEncodeError: 'ascii' codec can't encode character u'\u232c' in position 20: ordinal not in range(128)
```

and here is the full [error](https://gist.github.com/zhuangya/ead293008160ef09a488)

it looks like that ansbile did not support all the unicode or sth?

**Comment by mpdehaan** [comment]
Can you please share a playbook that minimally reproduces this issue?

**Comment by zhuangya** [comment]
i tried, but i did not make it.

i think it could be my virtual machine's locale problem.

my problem is almost exactly the same with [this](http://docs.python.org/2/howto/unicode.html#the-unicode-type)

as far as i can tell, it should be a configuration problem. close this for now, if i reproduce this, i will fire another issue 

thanks!
