### ISSUE TITLE
azure_rm_containerregistry_facts  failed to returned credentials

### ISSUE THREAD

**Issue by yungezz** [ansible/ansible#45893]
##### SUMMARY

azure_rm_containerregistry_facts  error when retrieve_credentials=true

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.7
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "No handlers could be found for logger \"msrestazure.azure_active_directory\"\nTraceback (most recent call last):\n  File \"/tmp/ansible_MW55aq/ansible_module_azure_rm_containerregistry_facts.py\", line 264, in <module>\n    main()\n  File \"/tmp/ansible_MW55aq/ansible_module_azure_rm_containerregistry_facts.py\", line 260, in main\n    AzureRMContainerRegistryFacts()\n  File \"/tmp/ansible_MW55aq/ansible_module_azure_rm_containerregistry_facts.py\", line 173, in __init__\n
   super(AzureRMContainerRegistryFacts, self).__init__(self.module_arg_spec, supports_tags=False)\n  File \"/tmp/ansible_MW55aq/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 317, in __init__\n  File \"/tmp/ansible_MW55aq/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2370, in exit_json\n  File \"/tmp/ansible_MW55aq/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2363, in _return_formatted\n  File \"/tmp/ansible_MW55aq/ansible_modlib.zip/ansible/module_utils/basic.py\", line 534, in remove_values\n  File \"/tmp/ansible_MW55aq/ansible_modlib.zip/ansible/module_utils/basic.py\", line 517, in _remove_values_conditions\nTypeError: Value of unknown type: <class 'azure.mgmt.containerregistry.v2017_10_01.models.registry_list_credentials_result.RegistryListCredentialsResult'>, {'username': u'acrfest1', 'passwords': [<azure.mgmt.containerregistry.v2017_10_01.models.registry_password.RegistryPassword object at 0x7f3eeeb58050>, <azure.mgmt.containerregistry.v2017_10_01.models.registry_password.RegistryPassword object at 0x7f3eeeb58090>], 'additional_properties': {}}\n",

```paste below

```

**Comment by zikalino** [comment]
fixed with pr #45897
