### ISSUE TITLE
Ubuntu Install Fails due to SSHPASS dependency, Installation instructions need update 

### ISSUE THREAD

**Issue by NealSmithCRGT** [ansible/ansible#45918]
##### SUMMARY

When following the latest install instructions for Ubuntu 18.04 the command "sudo apt-get install ansible"  fails with an unmet dependency.   

Quoted here:

the following packages have unmet dependencies:
 ansible : Depends: sshpass but it is not installable
E: Unable to correct problems, you have held broken packages.

Apparently sshpass is not distributed by Ubuntu any longer.  

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below
Ansible 2.6
```

##### CONFIGURATION

```paste below

```

**Comment by andreaso** [comment]
Looks more like an issue on your end.

```
$ lsb_release --description
Description:	Ubuntu 18.04.1 LTS
$ apt policy sshpass
sshpass:
  Installed: 1.06-1
  Candidate: 1.06-1
  Version table:
 *** 1.06-1 500
        500 http://se.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
$
```

https://packages.ubuntu.com/bionic/sshpass

**Comment by NealSmithCRGT** [comment]
Thanks, but odd.  It is a fresh install.  I will try again.

Neal

On Sep 20, 2018, at 4:21 PM, Andreas Olsson <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks more like an issue on your end.

$ lsb_release --description
Description:    Ubuntu 18.04.1 LTS
$ apt policy sshpass
sshpass:
  Installed: 1.06-1
  Candidate: 1.06-1
  Version table:
 *** 1.06-1 500
        500 http://se.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
$


https://packages.ubuntu.com/bionic/sshpass<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpackages.ubuntu.com%2Fbionic%2Fsshpass&data=01%7C01%7Cneal.smith%40salientcrgt.com%7Ce8cad8ff62094df2f5cc08d61f36ad8a%7C6499e3f51d3e4f099ad352b9e2f67fb8%7C1&sdata=MW%2FHfUWRhvB7Dh5RtM8rgp5ZzWOdspSqB5H9L%2BUfFSM%3D&reserved=0>

**Comment by sivel** [comment]
I have confirmed as well that `sshpass` is available on Ubuntu 18.04.

This appears to be a local configuration issue.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by christofferliberg** [comment]
I have a fresh install but can't find sshpass either when trying to install ansible.

root@ansible:/home/nexus# lsb_release --description
Description:    Ubuntu 18.04.1 LTS

root@ansible:/home/nexus# apt policy sshpass
sshpass:
  Installed: (none)
  Candidate: (none)
  Version table:

**Comment by andreaso** [comment]
@christofferliberg: Like sivel said, try the IRC channel or the mailing list.

Feel free to highlight me on IRC. I go by the nickname __andol__.

**Comment by christofferliberg** [comment]
The issue was fixed by enabling the universe repository.

sudo add-apt-repository universe

**Comment by jiedongd** [comment]
> The issue was fixed by enabling the universe repository.
> 
> sudo add-apt-repository universe
thanks a lot, it works for me

**Comment by ghost** [comment]
> The issue was fixed by enabling the universe repository.
> 
> sudo add-apt-repository universe

Having come across this issue and this page I have also got it to work by adding the universe repo. Maybe ansible docs should be updated to include this for Ubuntu as it's clearly an issue for fresh 18.04 build.

**Comment by bogd** [comment]
Same issue here on a fresh Ubuntu 18.04 install. Also solved by adding the universe repo.

+1 for updating the docs with this information.

**Comment by krishn10** [comment]
> > The issue was fixed by enabling the universe repository.
> > sudo add-apt-repository universe
> > thanks a lot, it works for me

Thanks a bunch. This worked for me.
