### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '30%'

### ISSUE THREAD

**Issue by humblepilot** [ansible/ansible#45928]
##### SUMMARY

Want to run the play with serial 30% or any percentage defined on a hostgroup having 10 or more hosts. Followed https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#rolling-update-batch-size to set that up. For percentage definition did not find any ansible version mandate

Error observed:
``` 
ValueError: invalid literal for int() with base 10: '30%'
```

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible 1.5.3

```

##### CONFIGURATION

```
log_path=/tmp/ansible-playbook.log
host_key_checking = False

[ssh_connection]
control_path = %(directory)s/%%h-%%p-%%r
```

##### OS / ENVIRONMENT

Linux HOSTNAME 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

- name: test play
  hosts: YOUR_HOSTGROUP
  serial: "30%"

```yaml
ansible-playbook -i inventory/INV_NAME playbooks/site.yml -vvvv --limit HOSTGROUP --extra-vars  --ask-vault-pass
```

##### EXPECTED RESULTS

Ideally it should pick 30% of available server in parallel for deploy 

##### ACTUAL RESULTS

```paste below
22:24:44 Traceback (most recent call last):
22:24:44   File "bin/ansible-playbook", line 307, in <module>
22:24:44     sys.exit(main(sys.argv[1:]))
22:24:44   File "bin/ansible-playbook", line 247, in main
22:24:44     pb.run()
22:24:44   File "/local/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 247, in run
22:24:44     play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
22:24:44   File "/local/lib/python2.7/site-packages/ansible/playbook/play.py", line 110, in __init__
22:24:44     self.serial           = int(ds.get('serial', 0))
22:24:44 ValueError: invalid literal for int() with base 10: '30%'
22:24:44 Ansible failed when running against target .
22:24:44 Cannot continue.
```

**Comment by sivel** [comment]
This error indicates that you are using Ansible version 1.9 or older, which is unsupported at this point, and does not permit percent based serial configurations.

Please upgrade to a more recent version of Ansible.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
