### ISSUE TITLE
Failing integration test sts_assume_role

### ISSUE THREAD

**Issue by mattclay** [ansible/ansible#46024]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

sts_assume_role

##### ANSIBLE VERSION

```
ansible 2.8.0.dev0 (devel 3b52d968e6) last updated 2018/09/21 18:23:51 (GMT -700)
  config file = None
  configured module search path = [u'/Users/mclay/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mclay/code/mattclay/ansible/lib/ansible
  executable location = /Users/mclay/code/mattclay/ansible/bin/ansible
  python version = 2.7.14 (default, Mar 22 2018, 11:39:16) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The integration test sts_assume_role is disabled because it always fails.

##### STEPS TO REPRODUCE

`ansible-test integration sts_assume_role --docker -v --allow-disabled`

##### EXPECTED RESULTS

Tests pass.

##### ACTUAL RESULTS

Tests fail.

```
TASK [sts_assume_role : assert assume not existing sts role] *******************
fatal: [localhost]: FAILED! => {
    "assertion": "'Not authorized to perform sts:AssumeRole' in result.msg",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
```

**Comment by mattclay** [comment]
Test disabled in commit 7d8f1a7aae45e77ab5f2c0a033009b1c8a970f4e

**Comment by mattclay** [comment]
Resolved by https://github.com/ansible/ansible/pull/46026

**Comment by mwperina** [comment]
Matt/Ryan, is it possible to backport this stable-2.7 branch? Because of this issue we have a problem with failing CI on important 2.7 backport https://github.com/ansible/ansible/pull/46062

@sivel @ryansb
