### ISSUE TITLE
UFW Support

### ISSUE THREAD

**Issue by scottrobertson** [ansible/ansible#4602]
[UFW](https://help.ubuntu.com/community/UFW) would be pretty cool, it would make setting up firewalls a lot easier. Right now, i basically just have to:

```
- action: shell ufw allow 80
```

Which is fine, but it runs every time, which can be annoying.

**Comment by mpdehaan** [comment]
Sure, we're always welcoming of new modules.

Feel free to submit a pull request to add this.
