### ISSUE TITLE
Regression with FreeBSD clients

### ISSUE THREAD

**Issue by alinnow** [ansible/ansible#4605]
Ansible no longer 'just works' with FreeBSD clients.

I have an inventory file of IP addresses, one of which belongs to a FreeBSD box. Previous versions of ansible ran with this inventory file just fine. After upgrading ansible, it is no longer able to even gather facts about it because it assumes that python is in `/usr/bin/python`.

I've read the documentation about the `ansible_python_interpreter` variable. I agree that an override is a good idea for python 3 installations, but I think that ansible should again try to find a python, rather than failing. `/usr/local/bin` is a standard location for python on these systems, after all.

**Comment by mpdehaan** [comment]
Actually, there is no regression or change in behavior here, it's always been this way.

ansible_python_interpreter has existed for a long time.   It's easy to set in inventory_dir/inventroy

```
[all_my_bsd]
one.example.com
two.example.com
```

and in inventory_dir/group_vars/all_my_bsd:

```
ansible_python_interpreter=/usr/bin/wherever
```

Or you can also put the variable directly in the file for the group.

**Comment by alinnow** [comment]
You say that it's "always been this way", but it worked until quite recently. I wouldn't have used an inventory file without the `ansible_python_interpreter` line if it wasn't necessary, as I've been using ansible with a FreeBSD target for many months now.

**Comment by bcoca** [comment]
This was true at least since 0.4 which is when I started using ansible
against freebsd 8.0-8.3, if you check the mailing lists you should even
see me asking the question why we didnt use "env python" back then.

The "fix" I used back then was setting ansible_python_interpreter in
group_vars/all.
