### ISSUE TITLE
Difference in variable resolving between dictionary[ key ] and dictionary.{{ key }}

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#4606]
Initialy discussed on https://groups.google.com/d/msg/Ansible-project/CpYaY-OzkQc/hwzfDX1hafcJ

As i started writing a play for this ticket, I tested it on latest devel with this weekend's updates on variable referencing, and noticed another behaviour than initially discussed on the list; I'll just show the behaviour on latest devel:

A playbook with different outpouts can be found here: http://sprunge.us/PRWJ

*Summary: *
tomcat_libs being a dictionary holding lists as values, and tomcat_version set to an existing key:
- with_items: tomcat_libs.{{ tomcat_version }} works as expected
- with_items: tomcat_libs[ tomcat_version ] seems broken

Setting tomcat_version to a non-existing key;
- with_items: tomcat_libs.{{ tomcat_version }} will not warn about the non existing variable/key, not will it warn about the given value not being a list, but just convert the given string to a list of that one string
- with_items: tomcat_libs[ tomcat_version ] rightfully warns about expecting a list, but might be better to warn about the non existing key?

Also, for the sake of completeness, the same examples but hardcoding the key vcalue in the play, without using a variable, yield some problems too: http://sprunge.us/YHca

This works ok with a known key, but gives different results when the key is not known.
- with_items: tomcat_libs.6 will not warn about the non existing variable/key, not will it warn about the given value not being a list, but just convert the given string to a list of that one string
- with_items: tomcat_libs[ 6 ] rightfully warns about expecting a list, but might be better to warn about the non existing key?

**Comment by mpdehaan** [comment]
There's so much here I'm confused a bit here with what you are trying to say.   

You should never need to use {{ expressions }} in with statements.   Docs don't do this, and people should not make up syntax.  What you did however seems to still work, so that's fine.   Moving on.

There's some bits in the middle later. The phrase "doesn't work" should always be followed up with _what_ something is observed to do and also what you would expect.   "Seems broken" is an equally confusing statement, because it should be immediately followed up with "because it does this".

It seems the actual thing you are talking about is it not detecting that "some_valid_variable.some_invalid_key" does not produce the right warning in various cases where there is "some_invalid_key".

Is that correct?

**Comment by srgvg** [comment]
> You should never need to use {{ expressions }} in with statements. Docs
> don't do this, and people should not make up syntax. What you did however
> seems to still work, so that's fine. Moving on.
> 
> ​Ok, I was not aware of that. Been using ansible for so long, and at times
> docs didn't mention everything​, so yes, it could happen I'm using things I
> shouldn't.
> Also, you did just resolve a ticket where this syntax was mentioned:
> https://github.com/ansible/ansible/issues/4582 Previous to that ticket I
> asked if I should write this in another way, and you didn't say this syntax
> was not supported, so I assembled those examples to be complete.
> 
> There's some bits in the middle later. The phrase "doesn't work" should
> always be followed up with _what_ something is observed to do and also
> what you would expect. "Seems broken" is an equally confusing statement,
> because it should be immediately followed up with "because it does this".
> 
> ​Well, that was the sort summary, in reference to the pastebin examples,
> which are speaking for themselves and are giving those explanations.
> 
> It seems the actual thing you are talking about is it not detecting that
> "some_valid_variable.some_invalid_key" does not produce the right warning
> in various cases where there is "some_invalid_key".
> 
> Yes, that's basically it.

When re-evaluating those differences, discarding mentioning the {{
expressions }} in with statements, it all comes down to one particular
syntax which doesn't give an expected error.

Given this dictionary:

```
tomcat_libs:
  7:  ​
      - item1
      - item2
```

Referencing a  NON existing key, without using a variable like this:
- with_items: tomcat_libs.6

returns ->     "item": "tomcat_libs.6" where I would expect this to error
about tomcat_libs.6 not being an existing variable/key and certainly not
being a list.

Also, doing the same thing, but when putting the key 6 in a variable, does
the correct thing, it yields an error, as expected:
- with_items tomcat_libs[ tomcat_version_6 ]
  returns => with_items expects a list ( where tomcat_version_6 == 6 )

Serge

**Comment by mpdehaan** [comment]
updates have been reverted so closing this one
