### ISSUE TITLE
documented used of 'lookup' now generates variable undefined error 

### ISSUE THREAD

**Issue by tartansandal** [ansible/ansible#4608]
The following documented use of the lookup plugin

```

---
- hosts: all
  tasks:
     - debug: msg="{{ lookup('env','HOME') }} is an environment variable"
```

now generates the following error:

```
TASK: [debug msg="{{lookup('env','HOME')}} is an environment variable"] ******* 
fatal: [localhost] => One or more undefined variables: 'lookup' is undefined
```

I've traced this back to commit 5031104.

**Comment by willthames** [comment]
Also bisected back to commit 5031104c3 which contains the lines:

```
     # TODO: may need some way of using lookup plugins here seeing we aren't calling
     # the legacy engine, lookup() as a function, perhaps? 
```

Ref: https://github.com/ansible/ansible/blob/5031104c3a60bc6f93f5cbcfe2f659882fdaa986/lib/ansible/utils/template.py#L487-488

https://github.com/ansible/ansible/blob/5031104c3a60bc6f93f5cbcfe2f659882fdaa986/lib/ansible/utils/template.py#L501-502

Yeah, I think that does need to be fixed.

**Comment by onnos** [comment]
The workaround seems to be to use the new 1.4 syntax, using the ansible_env facts provided by the setup module.

```
 - debug: msg="{{ lookup('env','HOME') }} is an environment variable"
```

becomes:

```
 - debug: msg="{{ ansible_env['HOME'] }} is an environment variable"
```

**Comment by drybjed** [comment]
The same issue is happening when I try to lookup file for `authorized_key` module:

```
- hosts: all
  sudo: yes

  tasks:
    - authorized_key: user=drybjed key="{{ lookup('file','~/.ssh/id_rsa.pub') }}"
```

Result:

```
TASK: [authorized_key user=drybjed key="{{lookup('file', '~/.ssh/id_rsa.pub')}}" state=present] *** 
fatal: [philote.aiua] => One or more undefined variables: 'lookup' is undefined
```

Is there any replacement for that?

**Comment by willthames** [comment]
And my use case is failing with the template plugin (which is pretty similar to the file plugin - I could just use the template module to output to a temporary file but I'd still need to read it in!)

**Comment by srgvg** [comment]
+1 `fatal: [openam-on-2] => One or more undefined variables: 'lookup' is undefined`

**Comment by willthames** [comment]
So, having looked at the tests around lookups, I spotted the existence of $LOOKUP. 

With the following playbook:

```
---
- connection: local
  hosts: all

  tasks:
  - name: new style lookup
    action: debug msg="$LOOKUP(file, '/etc/nanorc')"
```

It kind of works as expected but with a giant deprecation warning:

```
$ ansible-playbook lookup.yml 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [new style lookup] ****************************************************** 
 [DEPRECATION WARNING]: Legacy variable substitution, such as using ${foo} or
$foo instead of {{ foo }} is currently valid but will be phased out and has
been out of favor since version 1.2. This is the last of legacy features on our
deprecation list. You may continue to use this if you have specific needs for
now. This feature will be removed in version 1.5. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.

ok: [127.0.0.1] => {
    "msg": "set nowrap"
}

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0  
```

Of course this just makes it a problem with:
- The deprecation warning
- The documentation is wrong: http://www.ansibleworks.com/docs/playbooks_lookups.html
- Backward compatibility fails

However, it's a workaround for if you do want to use file or template or password lookups (the env lookup is probably better solved with ansible_env as mentioned above). In the meantime I might just stick to using a non-broken version.

**Comment by bcoca** [comment]
@onno, ansible_env comes from the target host, lookup('env' ...) comes from
the master host, $HOME will probably be the same for the same user but it
is not guaranteed, other env variables will definitely not be the same.

**Comment by onnos** [comment]
@bcoca, thanks! You are right, of course. Turns out I was lucky, I was only using environment lookups in playbooks with "connection: local".

This problem was likely missed because the tests in "tests/lookup_plugins.yml" are incorrect - they're testing for $LOOKUP as @willthames mentioned earlier.

**Comment by mpdehaan** [comment]
Just looks like it needs to add lookups into the namespace, this is simple enough.
