### ISSUE TITLE
postgresql_user shouldn't require a password

### ISSUE THREAD

**Issue by darklajid** [ansible/ansible#4611]
postgresql_user is used to create psql roles.

Roles _don't_ require passwords [1] for postgresql, therefor the parameter should be optional and default to 'PASSWORD NULL' (or to leave out the whole PASSWORD part of the clause).

It's confusing that the module _supports_ connecting with a login_user with no login_password, but doesn't let me create a role that is used in this way.

1: http://www.postgresql.org/docs/9.1/static/sql-createrole.html

**Comment by zehome** [comment]
I agree on this. We use local unix connections where password is not mandatory (using ident)

**Comment by mpdehaan** [comment]
This is marked "required=False" in recent versions and should be resolved.  Please reopen if you are still seeing problems.

Thanks!
