### ISSUE TITLE
mysql_user pure

### ISSUE THREAD

**Issue by axisK** [ansible/ansible#4615]
The mysql_user module currently has a dependency on mysqldb which in turn relies on libmysqlclient being available. Due to some dependency conflicts I can't install libmysqlclient and instead have to rely on using a pure python mysql client. 

At the moment I've got a module called pure_mysql_user which modifies mysql_user to use mysql.connector instead of mysqldb but would like to modify mysql_user to have a pure parameter instead.
Is this something which would have a place in the core ansible modules or should I focus on keeping the separate mysql_user module instead?

**Comment by mpdehaan** [comment]
This sounds like a question for the development list rather than a bug ticket, so I'm closing this one.

Feel free to ask there.
