### ISSUE TITLE
template module with jinja2_native erroneously convert json string to dict and corrupt it

### ISSUE THREAD

**Issue by Jean-Daniel** [ansible/ansible#46169]
##### SUMMARY
I'm using the template module to generate json files. When jina2_native is enabled, the template module convert the generated template string into a dict and then convert this dict to string when writing the template result. This result in a file that is not valid JSON. The indentation is removed (which is not an big issue), and the keys and values are quoted with single quote (which is illegal in JSON).

Note that using lookup('template', …) works and does not expose this bug.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
template

##### ANSIBLE VERSION

```paste below
ansible 2.7.0rc3.post0
  config file = /Users/jddupas/Projects/python/playbooks/nativejson/ansible.cfg
  configured module search path = ['/Users/jddupas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jddupas/Projects/python/playbooks/env/lib/python3.6/site-packages/ansible
  executable location = /Users/jddupas/Projects/python/playbooks/env/bin/ansible
  python version = 3.6.5 (default, Apr 17 2018, 10:37:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

```
jinja2 trunk
```

##### CONFIGURATION

```paste below
DEFAULT_DEBUG(/Users/jddupas/Projects/python/playbooks/nativejson/ansible.cfg) = False
DEFAULT_JINJA2_NATIVE(/Users/jddupas/Projects/python/playbooks/nativejson/ansible.cfg) = True
```

##### OS / ENVIRONMENT

macOS and Linux

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  tasks:
  - template:
      src: 'tpl.txt'
      dest: file.json
```

Template file
```json
{
  "key": "value"
}
```

Run the playbook -> the generated file contains:

```
{'key': 'value'}
```

##### EXPECTED RESULTS

I don't want that `template` convert my string into a dict, even when using the native context.

##### ACTUAL RESULTS

The template module corrupt my file.

**Comment by sivel** [comment]
This seems to potentially be a bug in the upstream `NativeEnvironment`:

```
>>> from jinja2.nativetypes import NativeEnvironment as Environment
>>> e = Environment()
>>> t = e.from_string('''{
...     "foo": "bar"
... }''')
>>> t.render()
{'foo': 'bar'}
>>> type(t.render())
<class 'dict'>
```

cc @mkrizek

**Comment by sivel** [comment]
cc @mkrizek

**Comment by mkrizek** [comment]
Created issue upstream https://github.com/pallets/jinja/issues/917.

**Comment by davidism** [comment]
Serialized JSON data is a string. You need to write a Python string literal to end up with a string containing JSON data when using Jinja's `NativeEnvironment`. You've written a Python dict literal.

The op is asking for a way to load a template as a string, rather than a native type. That's something Ansible would need to address, not Jinja.

**Comment by cueedee** [comment]
I'm experiencing very similar issues when using a `command` task:

```yml
- hosts: all
  tasks:
-  command:
        argv:
            - 'riak-admin'
            - 'bucket-type'
            - 'create'
            - 'some-bt'
            - '{{ ''{ "props": {} }'' }}'
```

The `riak-admin` command itself is irrelevant but demonstrates the issue because of the resulting error:

```json
{
  "changed": true,
  "cmd": [
    "riak-admin",
    "bucket-type",
    "create",
    "document-bt",
    "{'props': {}}"
  ],
  "delta": "0:00:00.339157",
  "end": "2019-07-10 06:43:16.622431",
  "msg": "non-zero return code",
  "rc": 1,
  "start": "2019-07-10 06:43:16.283274",
  "stderr": "",
  "stderr_lines": [],
  "stdout": "Cannot create bucket type document-bt: invalid json",
  "stdout_lines": [
    "Cannot create bucket type document-bt: invalid json"
  ]
}
```

As can be seen, the very last argument to `riak-admin` has been changed from the intended `{ "props": {} }` string to `{'props': {}}`.

I was deliberately using the template literal string in order to specifically _avoid_ any accidental jinja2 templating issues inside the json argument, but somehow it _still_ gets mangled.

**Comment by SpoonMeiser** [comment]
Until the fix for this gets released, is there a workaround we can use?

I've tried using the `|to_json` filter, but that has the same problem - the result is an escaped python string, rather than something that could be interpreted as JSON.
