### ISSUE TITLE
debug var=foo not properly resolving variables, seems to want to resolve the result strings too

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#4618]
```
$ ansible --version
ansible 1.4 (devel c876ce4b8a) last updated 2013/10/20 19:10:52 (GMT +200)
```

Following the latest new features on 
- debug: var=
- updated vars resolving from last weekend

I tested the following example:

``` yaml
$  cat play.yml

- hosts: all
  gather_facts: false
  connection: local

  vars:
    foo: bar
    dict:
      foo: bar
      complex: "{{ 'foo' ~ foo }}"

  tasks:
  - debug: var=foo
  - debug: var=dict.foo
  - debug: var=dict.complex
```

All three tasks fail however:

```
$  ansible-playbook play.yml

PLAY [all] ******************************************************************** 

TASK: [debug var=foo] ********************************************************* 
ok: [localhost] => {
    "foo": "failed to evaluate: name 'bar' is not defined"
}

TASK: [debug var=dict.foo] **************************************************** 
ok: [localhost] => {
    "dict.foo": "failed to evaluate: name 'bar' is not defined"
}

TASK: [debug var=dict.complex] ************************************************ 
ok: [localhost] => {
    "dict.complex": "failed to evaluate: name 'foobar' is not defined"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```

I'd expect, in order, to get:
- foo = bar
- dict.foo = bar
- dict.complex = foobar

Another example with a similar (or same?) bug:

```
$ cat host_vars/localhost 
var: foobar
$ ansible localhost -m debug -a var=var
localhost | success >> {
    "var": "failed to evaluate: name 'foobar' is not defined"
}
```

Expected to return the string foobar, not trying to resolve it as a variable.

Note: updating `host_vars/localhost` with
`var: "foobar"`
yields the same error.

**Comment by mpdehaan** [comment]
While debug: var=foo

should work

I disagree that this completely random syntax:

```
  complex: "{{ 'foo' ~ foo }}"
```

Should mean anything

**Comment by srgvg** [comment]
I do not see what is random to that syntax, that is valid jinja2. The tilde
notation is preferred to the plus sign for string concatenation.

http://jinja.pocoo.org/docs/templates/#math
http://jinja.pocoo.org/docs/templates/#other-operators

**Comment by mpdehaan** [comment]
As the "last weekend" stuff has been reverted this should all once again be operational, so i'm going to close this ticket.

Thanks!

**Comment by srgvg** [comment]
+1, I confirm this is fixed
