### ISSUE TITLE
ansible -u does not take precedence over ansible_ssh_user from inventory

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#4622]
ansible 1.3.3 (OSX).

It appears that the -u option to ansible does not override ansible_ssh_user set in the inventory (even if it is set at the group level)

```
==> group_vars/all <==
ansible_ssh_user: root

==> bsd.inv <==
mon1 ansible_ssh_port=1234
```

Then try to use -u option:

```
$ ansible mon1 -vvvv -i bsd.inv -u brian -k -m ping
SSH password:
<mon1> ESTABLISH CONNECTION FOR USER: root
<mon1> EXEC ['sshpass', '-d7', 'ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/brian/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=1234', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'mon1', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1382384861.22-5263748645168 && chmod a+rx $HOME/.ansible/tmp/ansible-1382384861.22-5263748645168 && echo $HOME/.ansible/tmp/ansible-1382384861.22-5263748645168'"]
mon1 | FAILED => Authentication failure.
```

ansible-playbook is the same.

```
$ ansible-playbook bug.yml -i bsd.inv -l mon1 -u brian -vvvv -k
SSH password:

PLAY [all] ********************************************************************

TASK: [ping] ******************************************************************
<mon1> ESTABLISH CONNECTION FOR USER: root
... etc
```

**Comment by resmo** [comment]
Could also reproduce with latest devel 4f139673865b713ad6b5e90aa79575a19b2b237e 

my hosts file:

```
www.example.com    ansible_ssh_user=jerry
```

test.yml:

```
---
- hosts: web01.ngine.ch
  gather_facts: yes
  tasks:
  - debug: msg="System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
```

cli:

```
ansible-playbook -i hosts test.yml -u tom -vvvv
```

output:

```
<www.example.com> ESTABLISH CONNECTION FOR USER: jerry
...
```

expected:

```
<www.example.com> ESTABLISH CONNECTION FOR USER: tom
...
```

**Comment by drybjed** [comment]
Probably related to #4613 ?

**Comment by bcoca** [comment]
This is intended as host var is smaller scope than command line setting, if
you want to override the host settings use -e "ansible_ssh_user=newval" on
the commandline

**Comment by gregbuehler** [comment]
It seems there have been many issues closed because this "works as intended" on this topic We already know this "works as intended" and the issue is that the intended way is not intuitive and the intended use needs to change. The intent of the user is to override the ssh user.

See also https://github.com/ansible/ansible/issues/4373

**Comment by bcoca** [comment]
@Greg, which the user CAN do with the method I describe. -u overrides
configs, but not inventory data, yes it is confusing the first time but it
does make sense in the ansible context once you are more familiar with it.

**Comment by candlerb** [comment]
@bcoca: group vars as well as host vars.

I can't really see the point of having a command-line flag which doesn't override anything. Is it only there to provide a value when the inventory doesn't have one, but when you can't be bothered to put it in group_vars/all ?

manpage for ansible-playbook does hint at this:

```
       -u USERNAME, --remote-user=USERNAME
           Use this remote user name on playbook steps that do not indicate a
           user name to run as.
```

However the manpage for ansible is definitely misleading.

```
       -u USERNAME, --remote-user=USERNAME
           Use this remote USERNAME instead of the current user.
```

Anyway, if this really is intentional behaviour, I think an explanation is needed. e.g.

> Note: if ansible_ssh_user has been set in the inventory on a host or group, this option does NOT override that setting. If you wish to override it, use -e "ansible_ssh_user=newval" instead

**Comment by bcoca** [comment]
it overrides the user set in ansible.cfg or the current user executing the
commandline (aka you), it does server a purpose, just not to override
inventory data.

**Comment by gregbuehler** [comment]
I guess the main issue that causes confusion is that a configuration or inventory value is still overriding something the user is explicitly setting from the command line. My experience with nearly any other tool is that the command line always wins.

Just my two cents.

**Comment by mpdehaan** [comment]
Works as intended :)

**Comment by bcoca** [comment]
@Greg, if you don't consider inventory a config, but a live object that can
change every invocation (not true with ini, but true with dynamic inventory
scripts), it starts to make more sense. You can override both, but -u is
mainly for ansible.cfg and the assumed default.

**Comment by sirkubax** [comment]
If you really need command line user (like that was importatnt for me), You could do (more or less):

ansible/runner/**init**.py
@@ -660,7 +668,13 @@ class Runner(object):
<code>
         # and finally -e vars are the highest priority
         inject = utils.combine_vars(inject, self.extra_vars)
         # and then special vars

```
     # inject.setdefault('ansible_ssh_user', self.remote_user)

     #JM
     #inject['ansible_ssh_user'] = self.remote_user
     if self.remote_user == 'root':
         inject['ansible_ssh_user'] = self.remote_user
     else:
         inject.setdefault('ansible_ssh_user', self.remote_user)
```

</code>

---

Note:
-inject.setdefault('ansible_ssh_user', self.remote_user)
+inject['ansible_ssh_user'] = self.remote_user

Would _always_ override "inventory user" with default (you) or provided (-u user) user. 
Since I did a simple workaround, to prevent this I did
    if self.remote_user == 'root':
that works well, but will work only for 'root', beaware about that. This is just my custom "one step workaround"

**Comment by bcoca** [comment]
For those finding this thread, to override inventory you just need to pass an extra var:

```
-e 'ansible_ssh_user=user1'
```

this should be available for ansible-playbook in all versions and for ansible and ansible-pull since 1.9
