### ISSUE TITLE
FreeBSD service module enable weird results

### ISSUE THREAD

**Issue by ScottSturdivant** [ansible/ansible#4623]
ansible version: `v1.2-1685-gf9ac88c`  (Because HEAD is broken ATM with regards to the lookup plugin...)

Given this action:  `service name=uwsgi enabled=yes`, I would expect `uwsgi_enabled="YES"` in /etc/rc.conf.  Instead, I get `Processing="YES"` in /etc/rc.conf

When I run `service uwsgi start` manually,  I get the following in my output:  `Processing uwsgi profile: manage` so I'm wondering if it's getting that information and putting it into the rc.conf file.

**Comment by ScottSturdivant** [comment]
Looks like the service modules performs this call:

`service uwsgi rcvar` which on my system returns the following:

```
Processing uwsgi profile: manage
# uwsgi
#
uwsgi_enable="YES"
#   (default: "")
```

**Comment by jctanner** [comment]
@SirScott I'm assuming #4624 fixed this issue.
