### ISSUE TITLE
notify entries should be checked before playbook starts

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#4629]
ansible 1.3.3

If a `notify:` line references a non-existent handler, no error is reported until an attempt to call the non-existent handler is made.

However, `notify:` lines cannot have jinja2 expansions, which is intentional:
https://groups.google.com/forum/#!topic/ansible-project/8RBhrb7I7GM

Therefore it would be straightforward to statically check notify lines against handlers before the playbook starts, and bail immediately for non-existent handlers.

This would be extremely helpful, to avoid half-runs where the config update is done but the corresponding handler fails.

**Comment by JensRantil** [comment]
:+1: I would love this, too! I'm tired of having to fiddle to get the handler running a second time.

**Comment by mpdehaan** [comment]
notifies can have Jinja2'd names now, so I'm not sure this still applies.

I understand where you are coming from, but static checks seem like they are not safe.

**Comment by JensRantil** [comment]
@mpdehaan wrote:

> notifies can have Jinja2'd names now, so I'm not sure this still applies.

...and the Jinja variables can't be resolved before checking if they resolve correctly?
