### ISSUE TITLE
`when:` does not interpolate `item` from `with_items`

### ISSUE THREAD

**Issue by garethrees** [ansible/ansible#4634]
Reopened from #4614 with succinct example.

``` yaml
- hosts: all
  vars:
    version: php54
    modules:
      - cli
      - gd
    php54:
      modules:
        cli:
          name: php54-cli
          source: rpm
        gd:
          name: php54-gd
          source: rpm
  tasks:
    - debug: msg={{php54}}

    - name: Install {{ version }} package modules
      yum: pkg={{ version['modules'][item]['name'] }} state=present
      with_items: modules
      when: "{{version}}['modules'][{{item}}]['source'] == 'rpm'"
```

Error:

``` sh
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [192.168.33.11]

TASK: [debug msg={'modules': {'gd': {'source': 'rpm', 'name': 'php54-gd'}, 'cli': {'source': 'rpm', 'name': 'php54-cli'}}}] ***
ok: [192.168.33.11] => {"msg": "{modules:"}

TASK: [Install php54 package modules] *****************************************
fatal: [192.168.33.11] => error while evaluating conditional: {% if php54['modules'][cli,gd]['source'] == 'rpm' %} True {% else %} False {% endif %}

FATAL: all hosts have already failed -- aborting
```

I'm expecting `{{item}}` to be a single item from the `modules` list.

**Comment by mpdehaan** [comment]
Oooh, this syntax is quite unsupported, undocumented, discouraged, etc :)

```
  when: "{{version}}['modules'][{{item}}]['source'] == 'rpm'"
```

Do this:
      when:  hostvars[inventory_hostname][version]['modules'][item]['source'] == 'rpm'

I'll say this itself looks pretty gross, and I think you're trying to engineer something a little complicated.
Ansible likes to keep it simple and I'd suggest some other ways.

Please stop by the list if you'd like to discuss possible ways to model this.

1.4 will now also give you warnings that you shouldn't put {{ foo }} expressions in vars.

The hostvars trick above _itself_ should not be needed, the idea of passing in the variable called "version" by name is a little uncommon.   I think it could be eliminated in most common cases.

Happy to share but that's more of a free form list discussion.

In any event, unsupported syntax, happy to talk about it on the list.
