### ISSUE TITLE
Problem with conditional role dependencies: conditions are overwritten

### ISSUE THREAD

**Issue by tronner** [ansible/ansible#4635]
Hi,

I encountered a problem with conditional role dependencies. The case is as follows:

Role a depends on role b when var want_b is true.
Role b depends on role c when var want_c is true.

When want_b is false and want_c is true I expect both roles b and c to be skipped, because role b is skipped and role c is a dependency of role b. What happens is that role c is run anyway.

Very simple playbook illustrating this problem: 
https://github.com/tronner/ansible-bug-roledep-conditions

**Comment by mpdehaan** [comment]
Hi

If you want to define booleans instead of strings you should put them in the group_vars/host_vars files.

Please retest with this corrected as both strings have a true value.

Also please read contributing.md about required information to file in a bug report, namely the version of Ansible you are using.

Thanks!

**Comment by tronner** [comment]
Ansible version used: current devel branch (tested commit e34cde6).

About the booleans: want_b=false in the inventory file evaluates to false on my system (FreeBSD 9.2):

```
# cat hosts 
[testservers]
localhost want_b=false want_c=false
# ansible-playbook -i hosts testcase.yml 

PLAY [all] ******************************************************************** 

TASK: [c | debug msg="Running role c"] **************************************** 
skipping: [localhost]

TASK: [b | debug msg="Running role b"] **************************************** 
skipping: [localhost]

TASK: [a | debug msg="Running role a"] **************************************** 
ok: [localhost] => {
    "item": "", 
    "msg": "Running role a"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

When setting want_c to true the faulty behaviour surfaces: 

```
# ansible-playbook -i hosts testcase.yml -e want_c=true

PLAY [all] ******************************************************************** 

TASK: [c | debug msg="Running role c"] **************************************** 
ok: [localhost] => {
    "item": "", 
    "msg": "Running role c"
}

TASK: [b | debug msg="Running role b"] **************************************** 
skipping: [localhost]

TASK: [a | debug msg="Running role a"] **************************************** 
ok: [localhost] => {
    "item": "", 
    "msg": "Running role a"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

```

For completeness I tested setting the variables via group_vars/all (latest commit on https://github.com/tronner/ansible-bug-roledep-conditions) and the behaviour is exactly the same.

Thank you for looking into this.

**Comment by mpdehaan** [comment]
Ok you're running the devel branch so the inventory "eval" stuff is there.  Good deal.

**Comment by mpdehaan** [comment]
@jimi-c can you help take a look at this? 

I didn't remember role deps having conditionals, which may be a case of us needing to raise an error if this is an unsupported keyword.  Although I don't recall.

**Comment by jctanner** [comment]
Tested patch: https://gist.github.com/jctanner/2468258f3f6e9ec5785b#comment-944574

**Comment by pieteravonts** [comment]
When accumulating more than two conditionals a python error is thrown.

I've added a extra role dependency to the original example of tronner to illustrate the problem.
https://github.com/pieteravonts/ansible-bug-roledep-conditions

Running this playbook gives the following:

```
# ansible --version
ansible 1.4.3
# ansible-playbook testcase.yml
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 269, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-playbook", line 209, in main
    pb.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/__init__.py", line 229, in run
    play = Play(self, play_ds, play_basedir)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 83, in __init__
    ds = self._load_roles(self.roles, ds)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 327, in _load_roles
    roles = self._build_role_dependencies(roles, [], self.vars)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 276, in _build_role_dependencies
    self._build_role_dependencies([dep], dep_stack, passed_vars=dep_vars, level=level+1)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 276, in _build_role_dependencies
    self._build_role_dependencies([dep], dep_stack, passed_vars=dep_vars, level=level+1)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 264, in _build_role_dependencies
    tmpcond.join(passed_vars['when'])
AttributeError: 'list' object has no attribute 'join'
```

I think this would fix the problem and also prevent accumulating duplicate conditionals:
https://github.com/pieteravonts/ansible/commit/ca39e1f4158b328955c840d6f1c8a85857e6c1d8

**Comment by dverhelst** [comment]
@pieteravonts : Could you make a pull request for this ? We could use this in our setup aswell :)
