### ISSUE TITLE
Hosts in groups are not ordered

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#4636]
ansible 1.3.3

```
[external_ntp_servers]
0.pool.ntp.org
1.pool.ntp.org
2.pool.ntp.org
3.pool.ntp.org
```

Template:

```
{% for server in groups.external_ntp_servers %}
server {{server}} iburst
{% endfor %}
```

Output:

```
server 3.pool.ntp.org iburst
server 1.pool.ntp.org iburst
server 2.pool.ntp.org iburst
server 0.pool.ntp.org iburst
```

It may not be important for ntp, but it matters for /etc/resolv.conf:

> If there are multiple servers, the resolver library queries them in the order listed.

Also: it's not clear if the order of servers within a group is stable when other hosts are added to the inventory.

As far as I can see the _intention_ is that they be ordered, given that the Group object contains a list of hosts, not a dict.

**Comment by bcoca** [comment]
have you tried using the jinja2 "sort" filter?

**Comment by candlerb** [comment]
I want them to retain the order I put them in the inventory. "sort" may not give the ordering I want.

**Comment by jctanner** [comment]
On 10/22/2013 11:30 AM, Brian Candler wrote:

> I want them to retain the order I put them in the inventory. "sort" 
> may not give the ordering I want.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ansible/ansible/issues/4636#issuecomment-26813487.

Host ordering was improved in the devel branch. If you could, please 
test your usecase from a checkout.

**Comment by candlerb** [comment]
Yes, ordering works in devel branch. It breaks other stuff though: I will submit a separate ticket.

**Comment by jctanner** [comment]
Thanks, I'll close this one then.
