### ISSUE TITLE
ec2_group inconsistent vars

### ISSUE THREAD

**Issue by dpeterka** [ansible/ansible#4639]
ec2_group has ec2_secret_key whereas the other modules have aws_secret_key (same for access), also does not accept a variable in format of {{var}} only ${var}

**Comment by jctanner** [comment]
@dpeterka Thanks for the report. I've been meaning to get around to making all the ec2 modules consistent. I'll use this ticket to track the work.

**Comment by dpeterka** [comment]
Thanks for fast response. If I can sneak in a quick question how to add 'ALL' from the module?

**Comment by jctanner** [comment]
I'm not sure what you mean by "ALL" in this context, but that's probably more suitable for a conversation on the mailing list and/or IRC.

**Comment by jctanner** [comment]
resolved with afa5988391b014e6997e4ceee3ef604340f38134
