### ISSUE TITLE
Bug in Group Variable assignment in Inventory (ini) File

### ISSUE THREAD

**Issue by gottwald** [ansible/ansible#464]
Hi there,

I think there is a bug in the grouping mechanism of the ini inventory file.

To make things easier I tried your example:

```
[atlanta] host1 host2
[raleigh] host2 host3
[southeast:children] atlanta raleigh
[southeast:vars] some_server=foo.southeast.example.com halon_system_timeout=30 self_destruct_countdown=60 escape_pods=2
[usa:children] southeast northeast southwest southeast
```

If i want to run a playbook or the ansible command i get the following error:

```
ERROR: can't add vars to undefined group: southeast some_server=foo.southeast.example.com halon_system_timeout=30 self_destruct_countdown=60 escape_pods=2
```

BTW: I tested on 0.4 as well as on the actual git devel branch

Regards,

Ingo

**Comment by gottwald** [comment]
I was diggin into the code.

Looks like this example is wrong:
http://ansible.github.com/patterns.html#groups-of-groups-and-group-variables

You can't write it in one line, because the group dictionary mapping in here will fial:

```
def _parse_group_variables(self):
    group = None
    for line in self.lines:
        line = line.strip()
        if line.startswith("[") and line.find(":vars]") != -1:
            line = line.replace("[","").replace(":vars]","")
            group = self.groups.get(line, None)
```

Could somebody please fix the example in the link above?
I'm sure others will get confused too.

Thanks

Ingo

**Comment by mpdehaan** [comment]
Yeah, the example is totally wrong.   I am closing this bug and opening a bug on the docs project.
