### ISSUE TITLE
using sudo_user as the user that is already logged in 

### ISSUE THREAD

**Issue by steverweber** [ansible/ansible#4640]
using sudo_user as the user that is already logged in causes:

```
ssh connection closed waiting for sudo password prompt
```

Ansible should be comparing sudo_user with ~ ansible_ssh_user to see if sudo is needed before preforming the sudo.

I understand it might sound silly to have this check.  However its not possible to know how other people may use a playbook/role and sometimes user names will overlap with the sudo_user.

I hit this issue a few times and sure others have!

Thanks

**Comment by mpdehaan** [comment]
Are you parameterizing the user you are sudoing to perhaps.

I would agree this behavior is probably nice to add.

It's probably also a bit low priority so I'm tagging this as a feature idea.

**Comment by steverweber** [comment]
passing sudo_user as var. 

```
in a role...
- name: ensure user
  user: name={{name}} system={{system_user}} shell={{shell}} generate_ssh_key=yes ssh_key_comment="{{ssh_key_comment}}" state={{state}} 
  register: _user

- name: ensure ssh StrictHostKeyChecking is off
  lineinfile: dest={{_user.home}}/.ssh/config regexp='^StrictHostKeyChecking no$' line='StrictHostKeyChecking no' create=true 
  sudo_user: "{{name}}"

- debug: msg="{{ _user.ssh_public_key }}"
- name: Optional add key before continuing; ^C-s to pause, ^C-q continue.
  pause: seconds="{{wait_seconds}}"
  when: wait_seconds > 0
```

**Comment by steverweber** [comment]
If i were to attempt a patch I would try in `runner/__init__.py`

```
def _low_level_exec_command(,,,):

if sudoable == true and sudo_user == remote_user:
  sudoable == false

```

**Comment by mpdehaan** [comment]
That sounds like a good solution actually.

**Comment by steverweber** [comment]
https://github.com/ansible/ansible/pull/4775

**Comment by resmo** [comment]
can be closed as https://github.com/ansible/ansible/pull/4775 has been merged in

**Comment by mpdehaan** [comment]
Yep, thanks all!
