### ISSUE TITLE
ec2_group add group name to options

### ISSUE THREAD

**Issue by dpeterka** [ansible/ansible#4643]
Given I wish to add a security group to a rule it would be great to look up the id.

Consider currently:
create group1
Have no real handle to the group id

Would be nice to:
create group1
create group2 with member of group1

**Comment by brendanhay** [comment]
Seconding this. Would be nice from the perspective group names are constant (say, between regions) but the ids differ.

**Comment by aboyett** [comment]
This sounds like the functionality implemented in https://github.com/ansible/ansible/pull/5380

**Comment by mpdehaan** [comment]
Yep, I'm going to close this ticket and we can track things in that github.
