### ISSUE TITLE
Connection fails with "'msg': 'FAILED: not a valid DSA private key file', 'failed': True"

### ISSUE THREAD

**Issue by tegryan** [ansible/ansible#4645]
When I call a playbook using:
ansible-playbook -i provision provision.yml  -e "dc=eu-ireland"

it creates an instance, waits for SSH to come up, but then fails on the config play with:
fatal: [ec2-<ip>.eu-west-1.compute.amazonaws.com] => {'msg': 'FAILED: not a valid DSA private key file', 'failed': True}

but when I add "ec2-<ip>.eu-west-1.compute.amazonaws.com" to the webservers (inventory file) and run:
ansible-playbook -i webservers webservers.yml

it connects and runs fine.

provision.yml:
http://pastebin.com/9u4FUtXJ

webservers.yml:
http://pastebin.com/k9mCu587

ansible.cgf:
http://pastebin.com/NzF2Lc1Y

OS:  CentOS 6.4 on both config and remote machines.

If there is anything else that would help, please let me know.

**Comment by tegryan** [comment]
In the remote machine in /var/log/secure there is this entry:

Oct 22 20:42:16 ip-<local-ip> sshd[896]: Did not receive identification string from <config-server-ip>

**Comment by mpdehaan** [comment]
Hi, please stop by the mailing list, this is more of a support question than a bug.

Thanks!
