### ISSUE TITLE
Inconsistent permissions for newly created files

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#4646]
ansible-1.3.3

If I create a file e.g. using the 'template' module, and do not specify mode=xxx:
- On the local machine (ansible_connection=local), it appears with mode 644
- On a remote machine (default, which I think is ansible_connection=smart), it appears with mode 600

This means that playbooks tested within the owner environment may not work correctly when run against a target machine over ssh.

Test environment: both the local machine and the target machine are running Ubuntu 12.04 and ansible 1.3.3 from the PPA.

Reproducer:

```
==> test.inv <==
s1 ansible_connection=local
s2 ansible_ssh_host=127.0.0.1 ansible_ssh_user=root

==> test.yml <==
- hosts: s1
  tasks:
    - template: src=/dev/null dest=/tmp/foo
- hosts: s2
  tasks:
    - template: src=/dev/null dest=/tmp/bar

$ sudo ansible-playbook -i test.inv test.yml -l s1
$ sudo rm -rf ~/.ansible/{tmp,cp}
$ ansible-playbook -i test.inv test.yml -l s2
$ ls -l /tmp/foo /tmp/bar
-rw------- 1 root root 0 Oct 22 20:42 /tmp/bar
-rw-r--r-- 1 root root 0 Oct 22 20:40 /tmp/foo
```

Interestingly, if I don't run under sudo (since writing to /tmp doesn't need root perms), I get a different mode again: 664 this time.

```
$ sudo rm /tmp/foo /tmp/bar
$ ansible-playbook -i test.inv test.yml
...
$ ls -l /tmp/foo /tmp/bar
-rw------- 1 brian brian 0 Oct 22 20:45 /tmp/bar
-rw-rw-r-- 1 brian brian 0 Oct 22 20:45 /tmp/foo
```

The difference between root and normal user suggests something to do with umask, which there is:

```
$ umask
0002
$ sudo /bin/bash -c umask
0022
```

However I see the same over ssh too. 

```
$ ssh localhost umask
0002
$ ssh root@localhost umask
0022
```

It seems that ansible is somehow defaulting to file creation with mode 600 over ssh but not locally.

**Comment by mpdehaan** [comment]
This is just an OS thing.  

I would recommend you set explicit permissions all the time wherever you have preference for what they should be, as this will also set them back if the end user sets them to something you don't want them to be anyway -- always conciously thinking about permissions is a good idea.

It does not make sense to me to set a default and therefore override any umask settings every time, and change existing behavior that thousands of people are comfortable with.

**Comment by candlerb** [comment]
Question: when you create files over ssh, and they get mode 600 by default, is this because of something which is set in the ansible python code?
