### ISSUE TITLE
with_items works with lists of dictionaries, doesn't work with lists of lists

### ISSUE THREAD

**Issue by darklajid** [ansible/ansible#4647]
Lots of places (including Michael DeHaan's posts, [1]) claim that this works:
- name: Index into the item
  debug: msg="{{item.0}}"
  # Same with item[0]
  with_items:
  - [ 'Foo', 1 ]
  - [ 'Bar', 2 ]

It doesn't in 1.3.3. {{item}} is always the first thing in the list, {{item.0}} ends up as being the first char (in this case) of the first colum: 'F', 'B'.

Note that the dictionary version still works:
- name: Index into the item
  debug: msg="{{item.key}}"
  with_items:
  - { key: 'Foo', value: 1 }
  - { key: 'Bar', value: 2 }

I guess that's a regression?

1: https://coderwall.com/p/uaeeug

**Comment by mpdehaan** [comment]
This is not a regression but in fact a feature, because if you supply two lists of packages it will install them all in one and has been the case for some time.

Stop by the list if you have questions (you could also write your own lookup plugin if you wanted different behavior).
