### ISSUE TITLE
cron module raises exception when used on Solaris 10

### ISSUE THREAD

**Issue by Jmainguy** [ansible/ansible#4648]
Solaris 10 crontab does not allow a user to load a file into another users cron. It does not support the -u option for this reason. Valid options for cron in Solaris 10 are crontab /path/to/file. Or Crontab -l user. For this reason the file is read, edited for the appropriate entries made by the playbook but errors out on saving it into cron.

Right now the module loads it into cron via the command crontab -u <username> /path/to/file which is not supported.

I have fixed it on my environment by saving the file to /var/spool/cron/crontabs/<username> and then restarting the cron service. I can submit the code if you are interested, however I imagine there must be some better way then restarting the service on every change.

Steps to reproduce: Try using the module on solaris 10.
Expected results: changed: [hostname]
Actual results
: 
TASK: [crontab | Reproduce Bug] ***********************************************
failed: [hostname] => {"failed": true, "item": ""}
msg: /usr/bin/crontab: illegal option -- u
crontab: proper usage is:
        crontab [file | -e | -l | -r ] [user]

FATAL: all hosts have already failed -- aborting

**Comment by mpdehaan** [comment]
I need to know what Ansible version you are using.  Can you share?

(Please read contributing.md for bug reporting suggestions)

Thanks!

**Comment by Jmainguy** [comment]
Sorry about not having that in there.

ansible 1.4

**Comment by mscherer** [comment]
Looking at it, it seems you can either set the user, or a filename, but not both ( ie, crontab $user, or crontab $filename ). I am not sure we can find a better way

**Comment by Jmainguy** [comment]
It is a Solaris limitation to be sure. In solaris you can crontab $filename, or crontab [-e | -l | -r ] $username. If you did crontab $username it would load a file called $username into the user running the command cron. 

If Solaris specific code can be implemented into the module to sudo as the user=$username and then crontab $file once sudo'ed I believe that could fix the issue as well. An issue with solaris 10 and lower is that sudo is not provided either and a third party sudo must be installed. So then there will be a dependency on this module for sudo.

If this idea makes sense I will try and spend some time getting that solution working. Otherwise other ideas would be great to hear.

**Comment by mscherer** [comment]
@jmainguy or we could just use su, as I suspect it would be installed on every unix

**Comment by Jmainguy** [comment]
@mscherer Yeah I initially coded it to use su as a work around as @romeotheriault is suggesting. I however got stuck when ansible deletes the file as soon as I used su. I will put some work into it now to see if I can get around ansible deleting the tmp file before I can load it with su.

**Comment by mscherer** [comment]
Ansible do not delete the file, but the file is root readable only, so I had to make a rather ugly chown. I think the code could be more elegant, or refactored, but it work, so that's IMHO a good starting point.

**Comment by Jmainguy** [comment]
@mscherer you are the best. Tried your pull request and it worked like a charm. +1 for recommending this gets included in 1.4

**Comment by mpdehaan** [comment]
Closing this as we have the pull request ticket to review, thanks!
