### ISSUE TITLE
Yum: Failed state when incomplete transaction occurs

### ISSUE THREAD

**Issue by pcarinhas** [ansible/ansible#4649]
ansible version 1.3.2
OS: Host: Ubuntu 13.04
Target: Centos 6.4

If Yum is in a state where a transaction was not completed it hangs on 
an update process like: 
- name: "{{ role }}: Upgrade base system packages"
  yum: name=\* state=latest
  async: 420
  poll: 5

My solution was to 
1. yum clean all
2. install yum-utils which (has yum-complete-transaction) and then 
3. run the yum-complete-transaction tool. This may add a further dependency.

**Comment by jctanner** [comment]
We should have the module detect incomplete transaction errors/messages, and fail the task instead of hanging (presumably waiting on input).

**Comment by mpdehaan** [comment]
So are you saying a previously non-completed transaction or a current active transaction?

(I've seen the latter but not the former)

**Comment by mpdehaan** [comment]
example:  when PackageKit is running

it will not hang after it completes or you whack it, and still works with outstanding failed transactions

please read contributing.md about how to file bug tickets BTW, always include the version of ansible you are using, etc

Thanks!
