### ISSUE TITLE
reboot causes "failed to parse" on broadcast message

### ISSUE THREAD

**Issue by gthb** [ansible/ansible#465]
When invoking reboot on a Debian Squeeze VM, I get this:

```
$ ansible vmdeb -u gthb -a '/sbin/reboot' --sudo
vmdeb | FAILED => failed to parse: 

Broadcast message from root@vmdeb (pts/0) (Tue Jun 12 14:33:40 2012):



The system is going down for reboot NOW!

{"start": "2012-06-12 14:33:40.956628", "delta": "0:00:00.031075", "changed": true, "end": "2012-06-12 14:33:40.987703", "stderr": "", "stdout": "", "cmd": ["/sbin/reboot"], "rc": 0}
```

The reboot does happen, it's just the response handling that's unclean (apparently confused by the broadcast message appearing on .

Happens just the same whether I run with `-u someuser --sudo` or as root, and whether I use `-m shell` or -m command`.

**Comment by mpdehaan** [comment]
Right, the broadcast message, stderr or not, is being picked up by the command output.

Not sure we'll be able to fix this.

**Comment by mpdehaan** [comment]
We could PERHAPS make the parser look for these two lines and explicitly ignore them, but that feels weird to me.  I'm going to say we can't fix this.

**Comment by gthb** [comment]
But this makes ansible incorrectly conclude that the action failed, and thus would abort a playbook containing the reboot action ... right? (Caveat: I'm very new to ansible)

That seems a pretty large problem to leave unfixed just because the (fairly simple) fix “feels weird”. :)

**Comment by mpdehaan** [comment]
If you want to fix it, submit a patch.
