### ISSUE TITLE
Ansible fails with `su: must be run from a terminal` when running locally on debian

### ISSUE THREAD

**Issue by viciu** [ansible/ansible#46545]
##### SUMMARY
Ansible fails with `su: must be run from a terminal` when running locally on Debian 9.5

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
core, become

##### ANSIBLE VERSION
```
ansible 2.8.0.dev0 (devel 65952571d6) last updated 2018/10/05 14:30:05 (GMT +200)
  config file = None
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/prog/ansible/lib/ansible
  executable location = /home/user/prog/ansible/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]

```

##### CONFIGURATION
```
```

##### OS / ENVIRONMENT
Debian 9.5

##### STEPS TO REPRODUCE

```ansible -c local --become --become-method=su -m ping all -i localhost,```

or

```ansible -c local -S -m ping all -i localhost,```

##### EXPECTED RESULTS
Ping module should run successfully 

##### ACTUAL RESULTS

```ansible -c local -S -m ping all -i localhost,
[DEPRECATION WARNING]: The su command line option has been deprecated in favor of the "become" command line arguments. This feature will be removed in version 2.9. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.
localhost | FAILED! => {
    "changed": false, 
    "module_stderr": "su: must be run from a terminal\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
```

```ansible -c local --become --become-method=su -m ping all -i localhost,
localhost | FAILED! => {
    "changed": false, 
    "module_stderr": "su: must be run from a terminal\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
```

**Comment by mscherer** [comment]
So, after looking during pycon.fr ansible sprint, the issue come from the su version used on debian stable, coming from https://github.com/shadow-maint/shadow rather than newer debian version using https://github.com/karelzak/util-linux

So the problem is to force the tty creation, this can be done for ssh, but not local connection.

**Comment by mscherer** [comment]
The code is on https://github.com/shadow-maint/shadow/blob/master/src/su.c#L689 From what I understand, that's a security feature, assuming that the lack of tty is some potential compromise.

**Comment by mscherer** [comment]
We suspect that the issue would be only on the local plugin, since it work with -c ssh on the same system, without using '-t'.

**Comment by mscherer** [comment]
So, I suspect this might be solved by doing the same as https://github.com/ansible/ansible/pull/1666/files

**Comment by sivel** [comment]
Duplicate of #38696
