### ISSUE TITLE
authorized_key module traceback when using with_items in latest devel branch

### ISSUE THREAD

**Issue by pcgentry** [ansible/ansible#4657]
I have a setup where I use a vars file to setup ssh keys. It is setup like this: 
ssh:
- name: user1
  key: key1
- name: user2
  key: key2

With the play looking like this:
- name: Setup SSH
  authorized_key: user="{{ item.name }}" key="{{ item.key }}"
  with_items: ssh

This update (https://github.com/ansible/ansible/commit/7e8e186b3b8e0bff420de139ef99efe02eece321) caused this error that shows up if the second key does not exist already. : 

  File "/home/ubuntu/.ansible/tmp/ansible-1382558449.2-265179427150644/authorized_key2", line 325, in enforce_state
    existing_keys[parsed_new_key[0]] = parsed_new_key
TypeError: list indices must be integers, not str

I rolled back my local repo in order to narrow down which commit broke my setup, but haven't had time to look more into it yet.

**Comment by zealot128** [comment]
I had the same problem.

I also tried different lookup strategies for providing a pubkey. Using the lookup command from within a role always wants the pubkey path to prefix with the role path. But my pubkeys are stored elsewhere.

I tried that:

**1. via variable in external var file**

``` yaml
# roles/dev/tasks/main.yml
- name: "Add pubkeys"                                                                                     
  authorized_key: user={{user}} key='{{ pubkey }}'   

# external var file
dir: "{{lookup('env','PWD')}}"
pubkey: $FILE($dir/pubkeys/swi.pub)
```

That worked in previous versions (1.3)

**2. Variable**

``` yaml
# main.yml
tasks:
- { include: roles/dev/tasks/account.yml, dev_user: 'stefan', pubkey: '{{lookup("file", "pubkeys/swi.pub")}}' }

# roles/dev/account.yml
authorized_key: user={{dev_user}} key='{{ pubkey }}'
```

Results in wrong path, not PWD/pubkeys/swi.pub, but PWD/roles/dev/pubkeys/swi.pub

**3. direct FILE call in key**

``` yaml
- name: "Add pubkeys"      
  authorized_key: user=stefan key='$FILE(pubkeys/swi.pub)'    
```

```
gives:   File "/home/vagrant/.ansible/tmp/ansible-1382565719.11-126200160077101/user", line 2461, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-1382565719.11-126200160077101/user", line 1516, in main
    if not os.path.exists(user.home) and user.createhome:
  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**4. and finally, resulting in the same error as @pcgentry**

``` yaml
# playbook.yml
tasks:         
    - { include: roles/dev/tasks/account.yml, dev_user: 'stefan', pubkey: '{{lookup("file", lookup("env", "PWD") + "/pubkeys/swi.pub")}}' }

# roles/dev/tasks/account.yml
authorized_key: user=stefan key='{{ pubkey }}'

```

Error:

```
fatal: [default] => failed to parse: Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-1382566383.77-204610628537101/authorized_key", line 1293, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-1382566383.77-204610628537101/authorized_key", line 354, in main
    results = enforce_state(module, module.params)
  File "/home/vagrant/.ansible/tmp/ansible-1382566383.77-204610628537101/authorized_key", line 325, in enforce_state
    existing_keys[parsed_new_key[0]] = parsed_new_key
TypeError: list indices must be integers, not str
```

what is the right way to add pubkeys from a specific local directory to a specific user?

**Comment by mpdehaan** [comment]
There are already some bugs on authorized_keys we know about on devel now -- yep --  we are going to remove the logic that makes it understand commas and make sure it is not special cased for with_items.

cc @jimi-c

**Comment by jimi-c** [comment]
The patch I created for other issues (found here: https://gist.github.com/jimi-c/154048f2a6eafc4e00d2) appears to correct the original issue. I tried it with the following playbook:

<pre>
$ cat test_4657.yml 
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ssh:
      - name: root
        key: "ssh-rsa AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA this is a key"
      - name: root
        key: "ssh-rsa BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB this is another key"
  tasks:
    - name: Setup SSH
      authorized_key: user="{{ item.name }}" key="{{ item.key }}"
      with_items: ssh
(after running it once, which added the keys)
$ ansible-playbook test_4657.yml 
PLAY [localhost] ************************************************************** 
TASK: [Setup SSH] ************************************************************* 
ok: [127.0.0.1] => (item={'name': 'root', 'key': 'ssh-rsa AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA this is a key'})
ok: [127.0.0.1] => (item={'name': 'root', 'key': 'ssh-rsa BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB this is another key'})
PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

I'm still looking into whether or not this caused the second issue reported by @zealot128
