### ISSUE TITLE
Including roles parses comments

### ISSUE THREAD

**Issue by garethrees** [ansible/ansible#4663]
``` yaml
- hosts: all
  roles:
    - php#_fpm
```

Results in

``` sh
ERROR: cannot find role in /Users/gareth/Code/ansible/roles/php#_fpm or /Users/gareth/Code/ansible/php#_fpm
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

This works correctly:

``` yaml
- hosts: all
  roles:
    - php #_fpm
```

**Comment by srgvg** [comment]
This is expected behaviour, and how yaml is parsed.

See http://www.yaml.org/spec/1.2/spec.html#id2780069

_"Comments must be separated from other tokens by white space characters"_

**Comment by jimi-c** [comment]
Thanks @sergevanginderachter, we'll go ahead and close this. @garethrees if you run into any other similar issues, please let us know. Thanks!

**Comment by garethrees** [comment]
Ah didn't realise. My bad. Thanks
