### ISSUE TITLE
Mail module is failing in ansible 2.7

### ISSUE THREAD

**Issue by offlinehoster** [ansible/ansible#46673]
##### SUMMARY
Using the mail module is resulting an error

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mail module

##### ANSIBLE VERSION
```
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION
(nothing changed - default)
```


```

##### OS / ENVIRONMENT
Ubuntu 18.04 LTS latest with Ansible ppa

##### STEPS TO REPRODUCE
Install the latest version of ansible 2.7 from ppa

```
- name: Send mail a user
  local_action:
     module: mail
             host='{{ mail_host }}'
             port='{{ mail_port }}'
             username='{{ admin_mail_username }}'
             password='{{ admin_mail_password }}'
             from="{{ admin_mail_name }} <{{ admin_mail_address }}>"
             to="{{ name }} {{ surname }} <{{ externalmail }}>"
             bcc="<{{ admin_maillist }}>"
             charset="utf-8"
             secure="starttls"
             subject='Account {{ username }}'
             body='{{ lookup('template', './roles/mailtoNewExternalUser/templates/email_template.j2') }}'
```

##### EXPECTED RESULTS
Mail will be send

##### ACTUAL RESULTS
It fails

```
The full traceback is:
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-tmp-1539071591.43-32051129331245/AnsiballZ_mail.py", line 113, in <module>
    _ansiballz_main()
  File "/home/user/.ansible/tmp/ansible-tmp-1539071591.43-32051129331245/AnsiballZ_mail.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/user/.ansible/tmp/ansible-tmp-1539071591.43-32051129331245/AnsiballZ_mail.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_mail_payload_KbWQDC/__main__.py", line 372, in <module>
  File "/tmp/ansible_mail_payload_KbWQDC/__main__.py", line 251, in main
  File "/usr/lib/python2.7/smtplib.py", line 802, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 317, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 807, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.timeout: timed out

fatal: [127.0.0.1 -> localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/user/.ansible/tmp/ansible-tmp-1539071591.43-32051129331245/AnsiballZ_mail.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/user/.ansible/tmp/ansible-tmp-1539071591.43-32051129331245/AnsiballZ_mail.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/user/.ansible/tmp/ansible-tmp-1539071591.43-32051129331245/AnsiballZ_mail.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_mail_payload_KbWQDC/__main__.py\", line 372, in <module>\n  File \"/tmp/ansible_mail_payload_KbWQDC/__main__.py\", line 251, in main\n  File \"/usr/lib/python2.7/smtplib.py\", line 802, in __init__\n    SMTP.__init__(self, host, port, local_hostname, timeout)\n  File \"/usr/lib/python2.7/smtplib.py\", line 256, in __init__\n    (code, msg) = self.connect(host, port)\n  File \"/usr/lib/python2.7/smtplib.py\", line 317, in connect\n    self.sock = self._get_socket(host, port, self.timeout)\n  File \"/usr/lib/python2.7/smtplib.py\", line 807, in _get_socket\n    new_socket = socket.create_connection((host, port), timeout)\n  File \"/usr/lib/python2.7/socket.py\", line 575, in create_connection\n    raise err\nsocket.timeout: timed out\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

```

**Comment by offlinehoster** [comment]
Same config, same playbook, same machine, so nothing changed BUT ansible downgraded to version 2.6.5 is working fine.

```
ansible 2.6.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ùser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

**Comment by sdmorel** [comment]
I see the same error after updating from Ansible 2.5.5 to 2.7.0. But in my case it's intermittent.
More often than not it works, but once in a while the mail notification task fails with the same socket timeout error.

**Comment by webknjaz** [comment]
From traceback it looks like the TCP connection to SMTP server times out (meaning non-stable network)

**Comment by riglersc** [comment]
Possibly related.  The mail module is not working for us either, but the error is different.  For us it fails with "address family not supported by protocol".  Note that we disable ipv6 on our hosts.  Related?  I will open a separate bug report if need be.

with the following message:

        MODULE FAILURE
        See stdout/stderr for the exact error
        
with the following exception:

        Traceback (most recent call last):
          File "<stdin>", line 113, in <module>
          File "<stdin>", line 105, in _ansiballz_main
          File "<stdin>", line 48, in invoke_module
          File "/tmp/ansible_mail_payload_L47nZe/__main__.py", line 372, in <module>
          File "/tmp/ansible_mail_payload_L47nZe/__main__.py", line 251, in main
          File "/usr/lib64/python2.7/smtplib.py", line 789, in __init__
            SMTP.__init__(self, host, port, local_hostname, timeout)
          File "/usr/lib64/python2.7/smtplib.py", line 255, in __init__
            (code, msg) = self.connect(host, port)
          File "/usr/lib64/python2.7/smtplib.py", line 315, in connect
            self.sock = self._get_socket(host, port, self.timeout)
          File "/usr/lib64/python2.7/smtplib.py", line 794, in _get_socket
            new_socket = socket.create_connection((host, port), timeout)
          File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
            raise err
        socket.error: [Errno 97] Address family not supported by protocol
        
and a complete dump of the error:

        Failed: {
            "_ansible_parsed": false, 
            "exception": "Traceback (most recent call last):\n  File \"<stdin>\", line 113, in <module>\n  File \"<stdin>\", line 105, in _ansiballz_main\n  File \"<stdin>\", line 48, in invoke_module\n  File \"/tmp/ansible_mail_payload_L47nZe/__main__.py\", line 372, in <module>\n  File \"/tmp/ansible_mail_payload_L47nZe/__main__.py\", line 251, in main\n  File \"/usr/lib64/python2.7/smtplib.py\", line 789, in __init__\n    SMTP.__init__(self, host, port, local_hostname, timeout)\n  File \"/usr/lib64/python2.7/smtplib.py\", line 255, in __init__\n    (code, msg) = self.connect(host, port)\n  File \"/usr/lib64/python2.7/smtplib.py\", line 315, in connect\n    self.sock = self._get_socket(host, port, self.timeout)\n  File \"/usr/lib64/python2.7/smtplib.py\", line 794, in _get_socket\n    new_socket = socket.create_connection((host, port), timeout)\n  File \"/usr/lib64/python2.7/socket.py\", line 571, in create_connection\n    raise err\nsocket.error: [Errno 97] Address family not supported by protocol\n", 
            "_ansible_no_log": false, 
            "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 113, in <module>\n  File \"<stdin>\", line 105, in _ansiballz_main\n  File \"<stdin>\", line 48, in invoke_module\n  File \"/tmp/ansible_mail_payload_L47nZe/__main__.py\", line 372, in <module>\n  File \"/tmp/ansible_mail_payload_L47nZe/__main__.py\", line 251, in main\n  File \"/usr/lib64/python2.7/smtplib.py\", line 789, in __init__\n    SMTP.__init__(self, host, port, local_hostname, timeout)\n  File \"/usr/lib64/python2.7/smtplib.py\", line 255, in __init__\n    (code, msg) = self.connect(host, port)\n  File \"/usr/lib64/python2.7/smtplib.py\", line 315, in connect\n    self.sock = self._get_socket(host, port, self.timeout)\n  File \"/usr/lib64/python2.7/smtplib.py\", line 794, in _get_socket\n    new_socket = socket.create_connection((host, port), timeout)\n  File \"/usr/lib64/python2.7/socket.py\", line 571, in create_connection\n    raise err\nsocket.error: [Errno 97] Address family not supported by protocol\n", 
            "changed": false, 
            "module_stdout": "", 
            "rc": 1, 
            "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
        }

**Comment by webknjaz** [comment]
@riglersc it's probably a bit different. In your case, check out what's in host arg. Maybe DNS really resolves that into IPv6, which you've disabled :)

**Comment by riglersc** [comment]
Hi, @webknjaz,  according to the doc, host arg should default to "localhost" where sendmail is listening on port 25.  At any rate, we get the same error with the arg omitted, with "localhost" specified and with a known mail server specified.  The same task runs on a server that has Ansible 2.6.

**Comment by dmp-78** [comment]
The same - socket.timeout: timed out, in 2.7 version. Confirm.

**Comment by AndreasDavour** [comment]
Bug also confirmed on CentOS 7.5.1804 and ansible 2.7.0-1

**Comment by webknjaz** [comment]
I think `localhost` (sometimes) resolves into `[::1]`, which might be causing this.

**Comment by riglersc** [comment]
@webknjaz it works when we downgrade back to Ansible 2.6.  Then upgrading to 2.7 it stops working again.  Notably, however, the mail callback works as expected with both versions.

**Comment by webknjaz** [comment]
Could you please run it with `-vvvvv` arg and `ANSIBLE_DEBUG=1` env var? I'd like to see deeper logging.

**Comment by riglersc** [comment]
@webknjaz attached output when run with 2.6 and with 2.7.  This task is using a mail server (instead of localhost) for the host arg.  Can you delete the attachments after you've looked at them (output is not sanitized)?  Thanks.

**Comment by webknjaz** [comment]
@riglersc you'll have to ask GitHub to drop those files from their cache. These are just links, I can edit your comment, but it'll be possible to see previous versions of it + whoever got your message via email notifications will still have those links. I'm not aware of any ways to delete such attachments on your own.

It future, I recommend you sanitizing whatever's important to you and/or using private gists at https://gist.github.com/, so that you'd be in control of that.

**Comment by webknjaz** [comment]
!component +lib/ansible/modules/notification/mail.py

**Comment by webknjaz** [comment]
Ah, it look like the only change since 2.6 was https://github.com/ansible/ansible/pull/42748/files: shuffling "hello" around.

cc @bcoca

**Comment by webknjaz** [comment]
Curious, those changes affect blocks after the one with exception..

Have you tried setting `secure: never` arg?

**Comment by webknjaz** [comment]
Alright @offlinehoster @riglersc @AndreasDavour @dmp-78 and @sdmorel,
it looks like @dagwieers' backport #47019 is going to fix this, so all that's needed is to wait until it gets released at some point :)

**Comment by riglersc** [comment]
@webknjaz setting "secure: never" works for me until the fix is ready.  Thanks for following up.

**Comment by sumkincpp** [comment]
Wow, that was unhappy regression in 2.7.0 release.

**Comment by johnpetersjr** [comment]
We tried secure: never and that isn't working for us either.

Using ansible 2.7, python 2.7.5, the mail module consistently fails with "socket timed out" error.

Switching back to Ansible 2.5, the same playbook/module works fine.

Anything else to try to help fix this in 2.7?

**Comment by webknjaz** [comment]
@johnpetersjr post your traceback here

**Comment by johnpetersjr** [comment]
I take back my comment.  It's working now.  It was a firewall issue, it seems. Sorry about that.
