### ISSUE TITLE
Errors in jinja2 value expansion are not reported

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#4672]
ansible 1.3.3

```
- hosts: localhost
  tasks:
    - template: src=/tmp/a dest=~{{admin_user}}/b owner={{admin_user} mode=644
```

Note one missing brace on `owner={{admin_user}`

Now when you run this:

```
$ ansible-playbook localhost.yml -i localhost.inv -e 'admin_user=brian'
...
TASK: [template src=/tmp/a dest=~{{admin_user}}/b owner={{admin_user} mode=644] ***
failed: [localhost] => {"failed": true}
msg: Destination directory ~{{admin_user}} does not exist
```

What appears to have happened is that the jinja2 template expansion error has been silently ignored, and it has gone ahead trying to write to `~{{admin_user}}` instead of `~brian`

**Comment by mpdehaan** [comment]
So what you asked for, because it was missing the trailing brace, is not a Jinja2 expansion at all.

This is not a bug and there's no way for the template system to detect you didn't use the template system :)

**Comment by candlerb** [comment]
So you're saying that anything which successfully parses as jinja2 is taking as jinja2, and anything which isn't is treated as a plain string?

Does it say that anywhere in the documentation? This violates POLA for me.

**Comment by mpdehaan** [comment]
Let's put it this way.

Suppose you don't read how Jinja2 works and mistype {{ foo }} as

MOOCOW foo QUACKQUACK

how is it to know to replace foo?

This violates user-did-not-read-instructions :)

**Comment by candlerb** [comment]
What I expect is:

```
jinja2 error: missing '}}' at end of file
```

or something like that. Your MOOCOW example is valid jinja2; mine was not.

jinja2 knows what I mean:

```
>>> import jinja2
>>> t = jinja2.Template("MOOCOW foo QUACKQUACK")
>>> t.render()
u'MOOCOW foo QUACKQUACK'
>>> t = jinja2.Template("dest=~{{admin_user}}/b owner={{admin_user} mode=644")
Traceback (most recent call last):
...
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
>>>
```

ansible is silently hiding this exception.

**Comment by mpdehaan** [comment]
Patches would be considered.

**Comment by candlerb** [comment]
Before patches, what's the intended behaviour?

I have just been browsing the group and see suggestions that jinja2 templates are expanded over and over again until no more expansion is possible, is that true?

If it is, it gives a reason why bad jinja2 values must be accepted, because otherwise you would be unable to use any string literal value which happens to be invalid in jinja2 (unless there is some sort of escaping mechanism)

OTOH, I would rather explicitly expand a value once when I want it expanding. I can't think of any other language where "eval" iterates as many times as it can until it fails, and then returns the last value.
