### ISSUE TITLE
modules library/cloud/quantum_* should be renamed to library/cloud/neutron_*

### ISSUE THREAD

**Issue by berendt** [ansible/ansible#4679]
Quantum is not longer used in the upstream. The new name of Quantum is Neutron. We should soon rename all existing modules.

**Comment by berendt** [comment]
Existing modules:
- library/cloud/quantum_floating_ip
- library/cloud/quantum_floating_ip_associate
- library/cloud/quantum_network
- library/cloud/quantum_router
- library/cloud/quantum_router_gateway
- library/cloud/quantum_router_interface
- library/cloud/quantum_subnet

**Comment by mpdehaan** [comment]
Lots of users are probably still deploying older versions, so this would break them.

The module name will probably need to stay the same and be made compatible with both old and new.
