### ISSUE TITLE
ignore sudo: unable to resolve host

### ISSUE THREAD

**Issue by jdamick** [ansible/ansible#468]
I have a playbook that sets up hostname & resolv.conf & dns entries but until it completes sudo kicks back:
"sudo: unable to resolve host"

Even though the playbook runs the command correctly it fails since sudo gave that back, can there be an option to ignore this text rather than attempting to parse it as json and failing?

thanks

**Comment by mpdehaan** [comment]
no idea why sudo is doing this, how about bringing it up on the mailing list?

**Comment by pokono** [comment]
+1
