### ISSUE TITLE
Ansible copy module with src not able to take date formats

### ISSUE THREAD

**Issue by pandugathrinath** [ansible/ansible#46834]
##### SUMMARY

 - name: Copying the the file
     copy:
       src: /tmp/test/abc-$(date +%m-%d-%Y)/yummy/pos.json
       dest: /home/user1/pos.json.bk
       remote_src: yes

when I check the remote system with ls command I can see the file 
ls /tmp/test/abc-$(date +%m-%d-%Y)/yummy/pos.json
/tmp/test/abc-10-11-2018/yummy/pos.json

ansible error msg : "msg": "Source /tmp/test/abc-$(date +%m-%d-%Y)/yummy/pos.json not found"

I have tried with escape characters but there was no luck 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

copy module , src not able to take date format
##### ANSIBLE VERSION

```paste below
2.7.0
```

##### CONFIGURATION

```paste below
COLOR_CHANGED(/etc/ansible/ansible.cfg) = yellow
COLOR_DEBUG(/etc/ansible/ansible.cfg) = dark gray
COLOR_DEPRECATE(/etc/ansible/ansible.cfg) = purple
COLOR_DIFF_ADD(/etc/ansible/ansible.cfg) = green
COLOR_DIFF_LINES(/etc/ansible/ansible.cfg) = cyan
COLOR_DIFF_REMOVE(/etc/ansible/ansible.cfg) = red
COLOR_ERROR(/etc/ansible/ansible.cfg) = red
COLOR_HIGHLIGHT(/etc/ansible/ansible.cfg) = white
COLOR_OK(/etc/ansible/ansible.cfg) = green
COLOR_SKIP(/etc/ansible/ansible.cfg) = cyan
COLOR_UNREACHABLE(/etc/ansible/ansible.cfg) = red
COLOR_VERBOSE(/etc/ansible/ansible.cfg) = green
COLOR_WARN(/etc/ansible/ansible.cfg) = bright purple
```

##### OS / ENVIRONMENT

target os = ubuntu 16.04 
control machine : MacOS
##### STEPS TO REPRODUCE

- name: Copying the pos.json to the /home/Ionpath/gasvalvecontrol
     copy:
       src: /tmp/test/abc-$(date +%m-%d-%Y)/yummy/pos.json
       dest: /home/user1/pos.json.bk
       remote_src: yes

```yaml
ansible-playbook play1.yml --ask-become-pass -f 1 -i inventory -vvvv
```

##### ACTUAL RESULTS

```paste below

```

**Comment by sivel** [comment]
This is expected. We do not process the paths with a shell, so you cannot run shell commands within your paths.

You can instead utilize `ansible_date_time` to achieve your goal.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by pandugathrinath** [comment]
ansible_date_time works, can we get a feature like date format added into copy module

**Comment by sivel** [comment]
There is also a `strftime` filter that can operate on the epoch time returned by `ansible_date_time` which you can find documented at https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html

```
{{ '%m-%d-%Y' | strftime(ansible_date_time.epoch) }}
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
