### ISSUE TITLE
Module timezone does not work on Alpine

### ISSUE THREAD

**Issue by robertdebock** [ansible/ansible#46836]
##### SUMMARY
It's not possible to use the `timezone` module on Alpine.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
timezone

##### ANSIBLE VERSION
```
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/robertdb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

##### CONFIGURATION
```
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/lib/python2.7/site-packages/ara/plugins/callbacks']
```

##### OS / ENVIRONMENT
Controlnode: Fedora 28
Managednode: Alpine 3.8.1

##### STEPS TO REPRODUCE
Start a docker container:
```
docker run -ti --rm --name alpine alpine
```

Run these tasks:
```yaml
ansible -m raw -a "apk add python tzdata" -c docker -i alpine, all
ansible -m timezone -a "name=Europe/Amsterdam" -c docker -i alpine, all
```

##### EXPECTED RESULTS
That Ansible would return `ok:` or `changed:` and the timezone would be Europe/Amsterdam.

##### ACTUAL RESULTS
```
alpine | FAILED! => {
    "changed": false, 
    "msg": "Error message:\ntried to configure name using a file \"/etc/sysconfig/clock\", but could not write to it"
}
```

**Comment by robertdebock** [comment]
It does work in a full VM, just not in docker, closing the issue.

**Comment by bcoca** [comment]
docker 'protects' some files to try to force you to manage them from docker itself and not from inside the container.
