### ISSUE TITLE
feature idea: remember the notified handlers in .retry files on fail/error

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#4687]
if ansible fails, ansible creates a retry file. This is nice, but ansible forgets about handlers, which should have been executed at the end of the play, notified earlier in the play.

What about executing the handlers even after an error or even better, remember in the retry file the handlers, which should have been executed. So they can be executed the next time.

**Comment by mpdehaan** [comment]
Let's discuss this one on ansible-devel.

I'm open to the idea (or alternatives), though this isn't the best medium for group discussion and would like to encourage some brainstorming around this.

Thanks!
