### ISSUE TITLE
interpolation of complex vars inside a host_vars files no longer works

### ISSUE THREAD

**Issue by tartansandal** [ansible/ansible#4692]
Prior to the recent refactoring of variables, complex vars could be set at the top of a host_vars file and reference later using the old $ syntax.  This was great for denormalising data in certain setups.  This as working at commit  0568abe, but no longer works (eg at commit 3722beb).  Using new {{ style variables does not help.  I've produced a minimal test case at  

https://gist.github.com/tartansandal/7190079

This demonstrates the effect of both old and new style variables at aforementioned commit points.  have only tested this for host_vars, but I expect the same for group_vars files too.

**Comment by mpdehaan** [comment]
In queue for investigation -- I was able to have working references in my tests.

**Comment by mpdehaan** [comment]
Your git bisect BTW seems a bit off https://github.com/ansible/ansible/commit/3722beb -- is about the gem command.

**Comment by jctanner** [comment]
@tartansandal What is the expected content of pg_hba.conf ?

**Comment by jctanner** [comment]
If I understand this correctly, it seems that jinja is supposed to be getting a list for group_A_ipaddrs, but is getting a string instead ...

```
(Epdb) print data
{{group_A_ipaddrs}}
(Epdb) print t.render(vars)
['192.168.1.201']
(Epdb) type(t.render(vars))
<type 'unicode'>
(Epdb) t.render(vars)
u"['192.168.1.201']"
```

When jinja tries to reference the members of this string, we get a character by character evaluation in the template.

**Comment by jctanner** [comment]
Simple reproducer:

```
jtanner@u1304:~/issues/4692-complex_vars$ cat test.yml 
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    - contents: ['abc', 'def']
    - alist: "{{ contents }}"
  tasks:
    - debug: var=alist
    - template: src=test.j2 dest=./test.txt
jtanner@u1304:~/issues/4692-complex_vars$ cat test.j2 
{% for item in alist %}
{{ item }}
{% endfor %}

jtanner@u1304:~/issues/4692-complex_vars$ cat test.txt 
{
{
c
o
n
t
e
n
t
s
}
}

```

**Comment by jctanner** [comment]
This is related to https://github.com/ansible/ansible/issues/4616

**Comment by tartansandal** [comment]
Hi jctanner. Thanks for picking this up. You're test case looks spot on.  I thought this had something todo with host_vars files, hence the complex gist, but clearly not.

**Comment by mpdehaan** [comment]
See comments on the other BTW, most of this should be fixed up tomorrow.

**Comment by jctanner** [comment]
@tartansandal as of d154bf87812209409a673fd7f9848d75701e2f32 , this will work if you revert to old style var references ...

```
  vars:
    - alist: ['abc']
    - blist: ${alist} 
```
