### ISSUE TITLE
ansible-playbook --syntax-check does not check includes in tasks:/vars: section

### ISSUE THREAD

**Issue by mvo5** [ansible/ansible#4699]
Hi,

it appears that the ansible-playbook --check-syntax site.yml does not check includes under the "tasks:" or "vars:" sections. 

E.g.

```
$ cat site.yml
- hosts: all
  vars_files:
  - vars/no-file-here

$ ansible-playbook --syntax-check site.yml 
Playbook Syntax is fine
```

However:

```
$ ansible-playbook --list-tasks site.yml  
playbook: site.yml
ERROR: file not found: /tmp/vars/not-there
```

I will attach a very simple diff that fixes it for me.

Thanks for your consideration,
 Michael

**Comment by mvo5** [comment]
This branch: https://github.com/mvo5/ansible/compare/bugfix;more-syntax-check?expand=1 contains a trivial diff that seems to solve it for me, it appears that the tasks loading is done later (or lazy) and by re-using the --list-tasks code we can get the check for free.

**Comment by mpdehaan** [comment]
If you want to submit a code change, please submit a pull request per the process defined in contributing.md
