### ISSUE TITLE
lineinfile not working because of wrong default value of insertafter

### ISSUE THREAD

**Issue by berendt** [ansible/ansible#4700]
```
- lineinfile: dest=/etc/libvirt/libvirtd.conf line="auth_unix_ro = \"none\"" regexp="\#auth_unix_ro = \"none\""
```

Using this task with every run a new line `auth_unix_ro = "none"` is attached at the EOF of /etc/libvirt/libvirtd.conf. That's not the expected behavior. The expected behavior is that the line `#auth_unix_ro = "none"` is replaced by `auth_unix_ro = "none"`.

Looks like the issue is that `insertafter = 'EOF'` is used when not setting insertafter and insertbefore.

**Comment by mpdehaan** [comment]
I'm very skeptical about this as in general this is exactly where you want to add something with lineinfile,  we can take a look.

**Comment by mpdehaan** [comment]
FYI -- I'm closing this ticket because we already have a pull request and there's no sense tracking two tickets.

**Comment by berendt** [comment]
Sorry. Thought there should be also an issue for a pull request.
