### ISSUE TITLE
lineinfile & tab character

### ISSUE THREAD

**Issue by faust64** [ansible/ansible#4710]
Hi,

Using 1.3.1 from pip
Trying to patch some init script, I found out that using tab character when setting the `line' argument of lineinfile plugin syntax errors.

ansible:~/playbooks# ansible-playbook -i production site.yml -l virtservers
ERROR: Syntax Error while loading YAML script, /x/unbound/tasks/service.yml
Note: The error may actually appear before this position: line 6, column 71

name: patch unbound init script (deb)
lineinfile: dest=/etc/init.d/unbound regexp='if ps ax | grep' line="    if ps ax | grep in/u[n]bound >/dev/null; then"

I tried various alternatives (simple quotes, quotes around my grep regexpr, escaping '[' ']', ...), and finally found that replacing the tab character by several spaces works just as expected:

name: patch unbound init script (deb)
lineinfile: dest=/etc/init.d/unbound regexp='if ps ax | grep' line='        if ps ax | grep "in/u[n]bound" >/dev/null; then'
when: ansible_os_family == "Debian"

I've been able to reproduce the problem in several unrelated lineinfile calls.

Nothing critical.

Thanks,

Regards.

**Comment by mpdehaan** [comment]
YAML seems to support a \t

**Comment by faust64** [comment]
Doing such actually prints a \ and a t
I see I'm 3 releases behind. Could this be fixed updating?

**Comment by faust64** [comment]
Updated, no more luck.
Do you have some actual working sample?

**Comment by DaveQB** [comment]
Chiming in with my vote that this is an issue for me. Only cosmetic though.
ansible 1.4.1

**Comment by meshy** [comment]
This is still an issue in ansible 2.0.0.1
