### ISSUE TITLE
Ansible doesn't read global knowhosts files for SSH.

### ISSUE THREAD

**Issue by marcinpraczko** [ansible/ansible#4714]
Hi,

Ansible 1.3.2

I've described more details in mailing list: https://groups.google.com/forum/#!topic/ansible-project/osEh8SSdjhQ

It looks like ansible is not supporting reading global SSH Knowhosts files (which can be modified by SSH options). In world where a lot of virtual machines can be created in cloud and software designed for continuous integration and continuous delivery (like jenkins) reading global/local know hosts files by ansible should be supported. 

Both this options are supported by openssh (-o GlobalKnownHostsFile, -o UserKnowHostFile).

Would be nice if asible will allow to run something like that (relative pahts).
ANSIBLE_SSH_ARGS="-o GlobalKnownHostsFile=/etc/ssh/ssh_known_hosts" ansible-play -i inventory -vvv site.yml
Or the same with UserKnownHostsFile SSH argument.

Best regards,
Marcin Praczko

**Comment by mpdehaan** [comment]
The suggestion here might be to check the SSH args, if specified, and shlex.split them to see if a GlobalKnownHosts param was specified, and if so, look in that file for a host match not the other.

If this is not done the prompts don't lock correctly or lock at the wrong time (see thread).

**Comment by mpdehaan** [comment]
This has been updated recently for ssh.py and there is a ticket open for extending this for parmamiko, so I believe we can close this ticket finally.

Thanks!
