### ISSUE TITLE
Module command hangs when argument requires user input

### ISSUE THREAD

**Issue by haarts** [ansible/ansible#472]
For example:

```
$ ansible -i hosts -m command -a "ufw reset"
```

Seems to hang presumably waiting for user input. `ufw reset` asks for a confirmation. Some feedback would help. Better yet relaying the output to the client and the input back to the server. I'd say this is an enhancement/feature request.

**Comment by mpdehaan** [comment]
yeah, can't do anything about that.   Don't run commands that require user input.

**Comment by haarts** [comment]
Fair enough. Thanks for the insight!
On Jun 14, 2012 6:42 PM, "Michael DeHaan" <
reply@reply.github.com>
wrote:

**Comment by jscheid** [comment]
How about closing stdin on the remote process?

That way at least there would be instant feedback when the remote process attempts to read user input, rather than it hanging indefinitely.

**Comment by mpdehaan** [comment]
Where are you encountering this problem?

Also, can you share the output of ansible --version?

Can you paste an example?   We pass standard in as None already in almost all cases in the current implementation.

**Comment by jscheid** [comment]
ansible 1.0 -- sorry, I haven't actually checked if it is still an issue in HEAD.

In this case I was running "rbenv install (some ruby version)" which asked something along the lines of "it's already installed, overwrite (y/n)?".

I had to log in on the remote host and run this command manually to see this output btw.

Again, sorry for the noise if this is already fixed...

**Comment by mpdehaan** [comment]
are you using shell or command?

**Comment by jscheid** [comment]
This was using command.

OT: it would be awesome to be able to embed multi-line shell scripts in the YAML files, or be able to group multiple commands so that they go over a single SSH connection. I can open a new ticket for that, if there isn't one yet?

**Comment by mpdehaan** [comment]
See the script module for transferring and running scripts.   Already
exists.

As far as multiple SSH connections, you can use SSH with
ControlMaster/ControlPersist, or fireball mode.

**Comment by jscheid** [comment]
I realize there are ways to mitigate the SSH connection overhead, it would still be nice to have the functionality of "script" without having to create separate files. Sort of like sh HERE documents. Not high priority but would be nice to have.

Anyway, I will give HEAD a try but if you have a minute to spare, could you clarify if stdin closing is different between "script" and "command" and/or between 1.0 and HEAD? Thanks for your help... and for creating ansible in the first place, it's fantastically lightweight and a real pleasure to use.

**Comment by mpdehaan** [comment]
See "def module.run_command" in lib/ansible/module_common.py

and then look in library/command for the implementation of both script and
command using that function.

patches are welcome for that.

"Multiple things in one request" is rather incompatible with the
orchestration engine and I've already given quite a few ways to solve that
problem.

**Comment by jscheid** [comment]
The script task already does multiple things in one request, the only difference would be that the script would be inlined in the YAML file rather than having to live in a separate file, no?

Thanks for the pointers to the source code, I'll have a look and send a pull request in case there is room for improvement.

**Comment by mpdehaan** [comment]
Inline YAML scripts would offend my sensibilities, so yeah, seperate file
is the way to go if you really want to do that.

**Comment by jscheid** [comment]
:-)

Fair enough.

**Comment by jscheid** [comment]
But fwiw I'd like to point out that command tasks _are_ inline scripts, only limited to a single line.

**Comment by mpdehaan** [comment]
and are therefore readable.

**Comment by jscheid** [comment]
But what if you need to do more than one thing in a command, say `export FOO=bar; some command`

Right now, if I'm not mistaken, the only way to do this is to either put it into a script file (which seems overkill for such a short sequence of commands, and makes it hard to keep track of what's happening) or do something like:

```
command: bash -c 'export FOO=bar; some command'
```

Compare this to something like (*):

```
script: >
    export FOO=bar
    some command
```

Isn't that more readable than the `bash -c` hack, and at the same time easier to keep track of compared to outsourcing these two lines into a separate file?

(*) I'm not sure what the exact syntax should be, maybe this shouldn't use the `script` task but rather the `command` task could be extended to accept a multi-line command.

PS: sorry for hijacking the ticket... really this discussion should take place elsewhere.

**Comment by mpdehaan** [comment]
There's an environment keyword (see Advanced Playbooks Docs) for setting
the environment.

You can also use the shell module if you want a ";"

Q&A Discussion really belongs on the list, not the issue tracker.

**Comment by fclairamb** [comment]
I land here searching for ufw using ansible, so i'll give a short answer for people coming here for the same reason:

```
ansible <group> -u root -m shell -a "ufw allow ssh && ufw allow from 10.0.0.0/8 </dev/null && echo 'y' | ufw enable"
```

It allows ssh from everywhere, any connection from 10.0.0.0/8 and starts the firewall.

**Comment by mpdehaan** [comment]
Seems this would imply a ufw module might be worthwhile.

**Comment by nigma** [comment]
Regarding ufw, the enable command takes a --force param for non-interactive management, so you can write it as `ufw --force  enable`.

**Comment by fclairamb** [comment]
Yes a ufw module to manage rules might be a good idea.

I actually tested it, this is a rather recent addition. It isn't supported in Debian 6's version but is present on my Ubuntu 12.10 laptop. So I still recommend using the previous command.

If you want the playbook's style:

```
- name: UFW install & setup
  hosts: do
  user: root
  tasks:
  - name: Install UFW
    action: command apt-get install ufw -y
  - name: Set it up
    action: shell ufw allow 22 && ufw allow from 10.0.0.0/8 </dev/null && echo 'y' | ufw enable
```
