### ISSUE TITLE
Not detecting whether variable for 'user' is setup.

### ISSUE THREAD

**Issue by marcinpraczko** [ansible/ansible#4722]
Hi, 

Ansible 1.3.2

When dynamic variable is used for connection with servers - ansible is not checking whether this variable has been setup or not:

Playbook:
Inventory:
  user: "{{ ssh_user }}"
  vars_files:
    - vars/common_sshuser.yml

If 'ssh_user' is defined in command line or in file common_sshuser.yml - everything is working as expected and ansible connects with valid user.
But if this variable is not setup - ansible is trying connect with server without any error and uses '{{ ssh_user }}' variable.

GATHERING FACTS ***************************************************************
<remote-server> ESTABLISH CONNECTION FOR USER: {{ssh_user}} on PORT 22 TO remote-server

Expected result:
Ansible complain with error.

Best regards,
Marcin Praczko

**Comment by mpdehaan** [comment]
You can't define a variable to nothing and have it just know what you mean.

Please stop by the mailing list with your question as this isn't a support forum.

Thanks!
