### ISSUE TITLE
TestRunner - hardcoded path to /tmp/gitdemo

### ISSUE THREAD

**Issue by marcinpraczko** [ansible/ansible#4723]
Hi,

Ansible: branch devel

test/TestRunner.py has hardcoded path to /tmp/gitdemo and /tmp/gd.
This issue doesn't allow run tests by different users on the same machine:

For example:
- Manaul run tests as user1 
- Automated run tests for example with jenkins.

If one user will run tests / another user is not able run this tests because folders has been created on /tmp with different owner and tests fails. 

Expected.
Relative path for this tests instead of absolute.

Best regards,
Marcin Praczko

**Comment by jimi-c** [comment]
The above patch should resolve your issue. Let us know if you continue to have problems with this. Thanks!

**Comment by marcinpraczko** [comment]
Hello, 

Thanks for this patch - Looks like this is fixed - but still have the problem with running tests as normal user and under jenkins.

This is result in jenkins: Every thing looks OK.

```
Ran 96 tests in 52.337s
```

This is result running by normal user on the same machine - just after running jenkins test.

```
FAIL: test_recursive_copy (TestPlayBook.TestPlaybook)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/path/to/code/Projects_OpenSource/ansible/test/TestPlayBook.py", line 410, in test_recursive_copy
    assert utils.jsonify(expected, format=True) == utils.jsonify(actual,format=True)
AssertionError:
>>  assert <module 'ansible.utils' from '/path/to/code/Projects_OpenSource/ansible/lib/ansible/utils/__init__.pyc'>.jsonify({'localhost': {'failures': 0, 'skipped': 0, 'changed': 65, 'ok': 73, 'unreachable': 0}}, format=True) == <module 'ansible.utils' from '/path/to/code/Projects_OpenSource/ansible/lib/ansible/utils/__init__.pyc'>.jsonify({'localhost': {'unreachable': 0, 'skipped': 0, 'ok': 0, 'changed': 0, 'failures': 1}},format=True)

Ran 96 tests in 34.213s
FAILED (SKIP=1, failures=1)
```

However when I removed this folder from /tmp **rm -Rf  ansible-rcopy/** = normal user was able run all tests wihtout any errors. And this folder **/tmp/ansible-rcopy** has been created by normal user. 

Don't know whether I should create new issue for this or is OK to comment this closed issue? 

Best regards
Marcin Praczko

**Comment by jimi-c** [comment]
Yes, please create a new issue for this, and I wouldn't be surprised if there are other hard-coded paths in there. If you could find them all for the new issue, that would be helpful, as this is a somewhat low-priority issue.
