### ISSUE TITLE
Service Module: Service state recognition

### ISSUE THREAD

**Issue by gottwald** [ansible/ansible#473]
Hi there,

I think the state recognition in the service module is pretty unreliable.

This section in particular:

```
# ===========================================
# get service status

rc, status_stdout, status_stderr = _run("%s %s status" % (SERVICE, name))
status = status_stdout + status_stderr


running = False
if status_stdout.find("stopped") != -1 or rc == 3:
    running = False
elif status_stdout.find("running") != -1 or rc == 0:
    running = True
elif name == 'iptables' and status_stdout.find("ACCEPT") != -1:
    # iptables status command output is lame
    # TODO: lookup if we can use a return code for this instead?
    running = True
```

I've tested on Ubuntu 10.04 because we mainly use this release by now.

Let me give you a few examples of the output of the service <servicename> status command.

**MySQL:**
- **Output in stopped state:** mysql stop/waiting
- **Return Code in stopped state:** 0
- **Output in started state:** mysql start/running, process 20846
- **Return Code in started state:** 0

**Apache2:**
- **Output in stopped state:** Apache is NOT running.
- **Return Code in stopped state:** 1
- **Output in started state:** Apache is running (pid 21454).
- **Return Code in started state:** 0

The Problem here is, that the current service module always sees my Apache in the state running, even if it's not.
Since Ubuntu is using two ways for their init scripts. The old init way and the new upstart.

Maybe it would be a better solution to check first if the service has an upstart script. (e.g. with initctl list)
With upstart the service status output is standardized and you can check for the keywords.

The output of the old init scripts is just "free human text" and therefor not reliable for a keyword based check.
Maybe the return code would be a better option but I don't know if it is consistent for all linux distributions and all init scripts.

But using the boolean operator "or" here has to bring up errors because when the recognition by keyword is a false positive, it doesn't matter what the return code says.

So in my opinion the algorithm should be something like this:
1. We should check if it is an upstart script, cause of the standardized outputs where we can rely on a 100% keyword safety
2. We could check return codes (if they are consistent)
3. Try to gather the state by the human readable output
4. Maybe some specials

I know this may be not the best method to do this, but i can't think of a better one at this moment.

What's your opinion on this topic?

Best regards 

Ingo 

P.S.: sorry for the long post, but this topic is really important to me and i think it's a core function of ansible that's broken

**Comment by mpdehaan** [comment]
Can you please move discussion to the mailing list where others can be involved?
