### ISSUE TITLE
stacktrace instead of proper error for "when: inventory_hostname in groups['doesnotexist']"

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#4730]
When referring to the special variable `groups['doesnotexist']`, one usually gets a proper error, as shown here in the first example.

```
serge@goldorak:~/test$ execho "cat play.yml; ansible-playbook play.yml"
$ cat play.yml; ansible-playbook play.yml

- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
  - debug: var={{groups['doesnotexist']}}
  - debug: 
    when: inventory_hostname in groups['doesnotexist']

Wednesday 30 October 2013  14:43:16 +0100

PLAY [localhost] ************************************************************** 
Wednesday 30 October 2013  14:43:16 +0100

TASK: [debug var={{groups['doesnotexist']}}] ********************************** 
Wednesday 30 October 2013  14:43:16 +0100
fatal: [localhost] => One or more undefined variables: 'dict object' has no attribute 'doesnotexist'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
Total elapsed time: 0:00:00.006
           to retry, use: --limit @/home/serge/play.retry

localhost                  : ok=0    changed=0    unreachable=1    failed=0   
```

However, when using the same construct in a conditional, this triggers a stacktrace:

```
$ cat play.yml; ansible-playbook play.yml

- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
#  - debug: var={{groups['doesnotexist']}}
  - debug: 
    when: inventory_hostname in groups['doesnotexist']

Wednesday 30 October 2013  14:43:39 +0100

PLAY [localhost] ************************************************************** 
Wednesday 30 October 2013  14:43:39 +0100

TASK: [debug ] **************************************************************** 
Wednesday 30 October 2013  14:43:39 +0100
fatal: [localhost] => Traceback (most recent call last):
  File "/home/serge/src/ansible/lib/ansible/runner/__init__.py", line 384, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/serge/src/ansible/lib/ansible/runner/__init__.py", line 469, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/home/serge/src/ansible/lib/ansible/runner/__init__.py", line 556, in _executor_internal_inner
    if not utils.check_conditional(cond, self.basedir, inject, fail_on_undefined=self.error_on_undefined_vars):
  File "/home/serge/src/ansible/lib/ansible/utils/__init__.py", line 181, in check_conditional
    conditional = template.template(basedir, presented, inject)
  File "/home/serge/src/ansible/lib/ansible/utils/template.py", line 318, in template
    varname = template_from_string(basedir, varname, vars, fail_on_undefined)
  File "/home/serge/src/ansible/lib/ansible/utils/template.py", line 526, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 9, in root
TypeError: argument of type 'StrictUndefined' is not iterable


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
Total elapsed time: 0:00:00.006
           to retry, use: --limit @/home/serge/play.retry

localhost                  : ok=0    changed=0    unreachable=1    failed=0   
```

Tested with ansible versions 1.4 devel from 
- 20131014
- 20131029
- ansible 1.4 (devel e0fbaea566) last updated 2013/10/30 14:49:14 (GMT +200)
  all with same result.

I bumped into this when removing hosts from a special group, making this group effectively empty and hence unknown to the inventory.

On a side note and besides the ugly stacktrace error, I was wondering if it wouldn't be better to change this behavior from yielding an error, to just resulting in an empty list of hosts for that 'unknown' group, as I can see it happen one has special tasks for special groups, which might occasionally be empty. On the other hand, the obvious workaround is

`when: groups['doesnotexist'] is defined and inventory_hostname in groups['doesnotexist']`

**Comment by mpdehaan** [comment]
Suggested fix for this is to probably detect StrictUndefined in the error message and then raise errors.AnsibleError

**Comment by janeznemanic** [comment]
I will have a look at this issue and try to fix it. If that is fine.

**Comment by jimi-c** [comment]
It appears that this issue has been resolved based on the above commits, and is no longer reproducable on the devel branch:

<pre>
# ansible-playbook -vv ~/testing/test_4730.yml
PLAY [localhost] ************************************************************** 
TASK: [debug ] **************************************************************** 
fatal: [127.0.0.1] => error while evaluating conditional: inventory_hostname in groups['doesnotexist']
FATAL: all hosts have already failed -- aborting
PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/test_4730.retry
127.0.0.1                  : ok=0    changed=0    unreachable=1    failed=0   
</pre>

So I'm going to go ahead and close this. Let us know if you continue having issues with this. Thanks!
