### ISSUE TITLE
git and  hg module should recommand use /etc/ssh/ssh_known_hosts instead of 

### ISSUE THREAD

**Issue by EmmanuelKasper** [ansible/ansible#4732]
The git and the hg modules recommends using `StrictHostKeyChecking no` to bypass the ssh pubkey prompt.
 A much saner way to do this would to put the needed ssh pubkey in `/etc/ssh/ssh_known_hosts`, so you server can still have the MITM defense of publickeys.

The wording could be as such:

If using git over ssh and the task seems to be hanging, first verify that the remote host public key is present in C(.ssh/known_hosts). ssh will prompt the user to authorize the first contact with a remote host. To avoid this prompt, one solution is to add the remote host public key in C(/etc/ssh/ssh_known_hosts) before calling the git module, with the following command: ssh-keyscan remote_host.com >> /etc/ssh/ssh_known_hosts.

**Comment by mpdehaan** [comment]
I'm updating the docs for both now and this will be available in the next push.

Agree and thanks!

**Comment by mpdehaan** [comment]
done, will show up shortly.
