### ISSUE TITLE
SSH known_hosts prompt spews without waiting for response

### ISSUE THREAD

**Issue by Daemoen** [ansible/ansible#4734]
[~/Projects/ansible_source] % git log | head -n1                                                                                               [±] Branch: devel Status: no-change
commit d154bf87812209409a673fd7f9848d75701e2f32

[~/Projects/ItOps/ansible] % ansible -i test all -m raw -a 'groupmod -n mapr hadoop' -u root                                                  [±] Branch: master Status: untracked
dhd1 | FAILED | rc=6 >>
groupmod: group 'hadoop' does not exist

dhd3 | FAILED | rc=6 >>
groupmod: group 'hadoop' does not exist

dhd4 | FAILED | rc=6 >>
groupmod: group 'hadoop' does not exist

dhd11 | FAILED | rc=6 >>
groupmod: group 'hadoop' does not exist

ddd0 | FAILED | rc=6 >>
groupmod: group 'hadoop' does not exist

dhd2 | FAILED | rc=6 >>
groupmod: group 'hadoop' does not exist

dzk2 | FAILED | rc=6 >>
groupmod: group 'hadoop' does not exist

crawl-01 | FAILED | rc=255 >>

dgfe0 | FAILED | rc=6 >>
groupmod: group 'hadoop' does not exist

The authenticity of host 'dmn4 (10.10.5.182)' can't be established.
RSA key fingerprint is e5:a3:8b:71:9e:36:c7:4c:6f:02:85:67:01:35:07:f8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'dsb2 (10.10.5.183)' can't be established.
RSA key fingerprint is e5:a3:8b:71:9e:36:c7:4c:6f:02:85:67:01:35:07:f8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'dmn6 (10.10.5.234)' can't be established.
RSA key fingerprint is e5:a3:8b:71:9e:36:c7:4c:6f:02:85:67:01:35:07:f8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'dr1 (10.10.5.232)' can't be established.
RSA key fingerprint is e5:a3:8b:71:9e:36:c7:4c:6f:02:85:67:01:35:07:f8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'dhd9 (10.10.6.129)' can't be established.
RSA key fingerprint is e5:a3:8b:71:9e:36:c7:4c:6f:02:85:67:01:35:07:f8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'dhd0 (10.10.5.229)' can't be established.
RSA key fingerprint is e5:a3:8b:71:9e:36:c7:4c:6f:02:85:67:01:35:07:f8.
Are you sure you want to continue connecting (yes/no)? dhm0 | FAILED | rc=6 >>
groupmod: group 'hadoop' does not exist

The authenticity of host 'dhd7 (10.10.6.127)' can't be established.
RSA key fingerprint is e5:a3:8b:71:9e:36:c7:4c:6f:02:85:67:01:35:07:f8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'dhd8 (10.10.6.128)' can't be established.
RSA key fingerprint is e5:a3:8b:71:9e:36:c7:4c:6f:02:85:67:01:35:07:f8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'dzk0 (10.10.6.138)' can't be established.
RSA key fingerprint is e5:a3:8b:71:9e:36:c7:4c:6f:02:85:67:01:35:07:f8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'dhd6 (10.10.6.126)' can't be established.
RSA key fingerprint is e5:a3:8b:71:9e:36:c7:4c:6f:02:85:67:01:35:07:f8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'dzk1 (10.10.6.139)' can't be established.
RSA key fingerprint is e5:a3:8b:71:9e:36:c7:4c:6f:02:85:67:01:35:07:f8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'dhd10 (10.10.6.130)' can't be established.
RSA key fingerprint is e5:a3:8b:71:9e:36:c7:4c:6f:02:85:67:01:35:07:f8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'dmgdb1 (10.10.5.184)' can't be established.
RSA key fingerprint is e5:a3:8b:71:9e:36:c7:4c:6f:02:85:67:01:35:07:f8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'dfe3 (10.10.5.244)' can't be established.
RSA key fingerprint is e5:a3:8b:71:9e:36:c7:4c:6f:02:85:67:01:35:07:f8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'dmn5 (10.10.5.233)' can't be established.
RSA key fingerprint is e5:a3:8b:71:9e:36:c7:4c:6f:02:85:67:01:35:07:f8.
Are you sure you want to continue connecting (yes/no)? dr0 | FAILED | rc=6 >>

At this point, even typing yes doesnt seem to work, as it has something else in the buffer it seems, but pressing enter and typing yes doesnt make a difference either.  Also doesnt matter which version of transport is set, affects both paramiko and ssh.

**Comment by mpdehaan** [comment]
Can I ask why you are using the raw module for this?

This is curious it seems to be asking about hosts after for you.

**Comment by mpdehaan** [comment]
Looking at this now BTW

**Comment by mpdehaan** [comment]
Ok, I don't get this behavior using the raw module or other modules.

This behavior is controlled by some flock operations, can I ask some questions about what OS you are running from as your ansible control machine?   (Nothing crazy like Windows I hope?  That's not supported as a control machine).

I'm not sure of your background but you may be interested in poking in the code under lib/ansible/runner/connection_plugins/ssh.py

**Comment by mpdehaan** [comment]
Current speculation is the known host file is not in ~/.ssh/known_hosts but the host IS in ~/.ssh/known_hosts so the lock might not be firing (we know Ansible doesn't know if you have configured it to an odd location). 

This may not match reality though.

**Comment by Daemoen** [comment]
Something weird must have happened to known_hosts itself, not sure what, but removing the file and starting again, the issue disappeared..  Closing as PEBCAK issue.  Apologies.
