### ISSUE TITLE
with_templates look for templates in files/

### ISSUE THREAD

**Issue by kafeinnet** [ansible/ansible#4741]
Hi,

The with_template lookup search templates in files subdir.

Example with "with_template: dummy_all_hosts.j2" :

```
fatal: [fshlogmongoc01] => unable to read /etc/ansible/roles/mongodb/files/dummy_all_hosts.j2
```

I think it'd be better if it looks in the templates subdir were all templates are.

\fd

**Comment by mpdehaan** [comment]
This is just because it's a lookup plugin and that's where they look.

(Almost no one uses with_template because they just use the template module instead -- IIRC it's not documented for that reason even, so it's not a large concern)

You can "../templates" in the path if you like.
