### ISSUE TITLE
Ansible tower license node calculation

### ISSUE THREAD

**Issue by hiteshshaha** [ansible/ansible#47424]
##### SUMMARY

Can anybody explain me how Redhat calculate number of nodes for license perspective.
 is that something, if I have license of 100 nodes then I  can do deployment for only 100 nodes at a time?
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by sivel** [comment]
This issue tracker is for the open source ansible project.  Questions regarding Tower should be directed to your Red Hat support team, or sales person.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
