### ISSUE TITLE
AttributeError: 'list' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by jurgenhaas** [ansible/ansible#4745]
When I have the following task in a role, that works fine:

```
- name: 'Try to install something'
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - iptables
  when: myhosts == "none"
```

However, when the "when" statement is not in the task but in the main playbook when calling the role, then I get the error stack trace below. The playbook looks like this:

```
- name: "Gather Facts"
  hosts: "all"
  connection: ssh
  gather_facts: true
  sudo: yes
  roles:
    - { role: test, when: myhosts == "none" }
```

The stacktrace with the error is this:

```
TASK: [test | Try to install something] *************************************** 
fatal: [vm1] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 389, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 465, in _executor_internal
    if not self.conditional or utils.check_conditional(self.conditional, self.basedir, inject, fail_on_undefined=self.error_on_undefined_vars):
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/__init__.py", line 172, in check_conditional
    if conditional.startswith("jinja2_compare"):
AttributeError: 'list' object has no attribute 'startswith'
```

**Comment by jctanner** [comment]
@jurgenhaas What is the output of "ansible --version" ?

**Comment by mscherer** [comment]
Also, could you edit the bug so we can have playbook without being interpreted by the github markdown parser ?

**Comment by jurgenhaas** [comment]
It's ansible 1.4 and I've done this about 12 hours ago:

git pull (from git://github.com/ansible/ansible)
python setup.py build
python setup.py install

So in other words I believe to be on the latest dev release.

**Comment by jurgenhaas** [comment]
Sorry for the formatting, I have just corrected the original post.

**Comment by mpdehaan** [comment]
Thanks, this is due to some recent feature additions, the code needs to account for the conditional possibly being a list of conditions.   Looking at this now.

**Comment by mpdehaan** [comment]
fixed on latest devel branch and pushed just now, thanks!
