### ISSUE TITLE
rpm_key: add option to avoid importing duplicate keys

### ISSUE THREAD

**Issue by przemolb** [ansible/ansible#4746]
While testing some playbooks with rpm_key module I have noticed that each time I run it it imports the same key. It would be good to have an native ansible option which would prevent importing already imported key.

**Comment by jctanner** [comment]
@przemolb The rpm_key module is idempotent in regards to existing keys based on a quick review of the code. Can you share an example task with a key/url that is repeatedly imported?

**Comment by przemolb** [comment]
When you test your ansible code (i.e. playbook with a lot of tasks and one of them is importing rpm key) you just repeat the same task several times. ANd that is when you run rpm key import several times.

**Comment by jctanner** [comment]
@przemolb 

I re-examined and retested the module code and found that the bahavior is such:

1) Get the keyid for the file by using the gpg command.
2) Call "rpm -q gpg-pubkey"
3) If keyid not in list, import key

The only way a key would be imported more than once, is if the gpg keyid for the file changes after the first transaction.
