### ISSUE TITLE
In what Python file does Ansible formulate the command that executes on the target?

### ISSUE THREAD

**Issue by imthenachoman** [ansible/ansible#47532]
##### SUMMARY
Looking through the source code I can see that Ansible uses the `become*` flags when putting together the command that will inevitably be run on the target host. But all the references I see are in the `test` files -- I assume for testing or example purposes.

Based on my output I can tell the command it ends up with is something like:

    {become_method} {become_flags} -u {become_user} '...' && sleep 0

What I cannot find is exactly where this happens.

Can someone please point me in the right direction and/or tell me the file I want to look through...

##### ISSUE TYPE

 - Question

##### COMPONENT NAME
- `become`
- `become_user`
- `become_method`
- `become_flags`

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
