### ISSUE TITLE
accelerate mode python2.4 compliance - (CentOS 5) part 2

### ISSUE THREAD

**Issue by ksage** [ansible/ansible#4763]
Thanks for the fix for Issue #4739, but now I'm getting a different syntax error out of accelerate mode on CentOS 5:

GATHERING FACTS ***************************************************************
fatal: [sc-scm-ansible-stage-p4-master-01.nvidia.com] => Failed to launch the accelerated daemon on sc-scm-ansible-stage-p4-master-01.nvidia.com (reason:   File "/root/.ansible/tmp/ansible-1383284240.36-155321031921927/accelerate", line 336
    finally:
          ^
SyntaxError: invalid syntax
)

I'm running off the tip of the devel branch (currently: d478eaa6a53a)

Thanks!

**Comment by mpdehaan** [comment]
cc @jimi-c

**Comment by ksage** [comment]
I tested this and looks like the errors have moved to a different file.  I am now getting the following:

fatal: [sc-scm-ansible-stage-p4-master-01.nvidia.com] => failed to parse: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1383585649.37-237033989848421/accelerate", line 125, in ?
    from keyczar.keys import AesKey
  File "/usr/lib/python2.4/site-packages/keyczar/keys.py", line 48
    ACTIVE_CRYPT_LIB = 'm2crypto' if EVP else 'pycrypto'
                                   ^
SyntaxError: invalid syntax

Thanks!

**Comment by jctanner** [comment]
@ksage how did you install keyczar on your el5 machine?

**Comment by ksage** [comment]
@jctanner I just did:

$ sudo yum install python-pip  (which installed 0.8-1.el5)
$ sudo pip-python install python-keyczar

**Comment by jctanner** [comment]
@ksage Did you not get these errors during install?...

```
[root@el5 ~]# pip-python install python-keyczar
Downloading/unpacking python-keyczar
  Downloading python-keyczar-0.71c.tar.gz (237Kb): 237Kb downloaded
  Running setup.py egg_info for package python-keyczar
Requirement already satisfied (use --upgrade to upgrade): pycrypto>2.0 in /usr/lib/python2.4/site-packages/pycrypto-2.7a1-py2.4-linux-x86_64.egg (from python-keyczar)
Requirement already satisfied (use --upgrade to upgrade): pyasn1 in /usr/lib/python2.4/site-packages/pyasn1-0.1.7-py2.4.egg (from python-keyczar)
Installing collected packages: python-keyczar
  Running setup.py install for python-keyczar
      File "/usr/lib/python2.4/site-packages/keyczar/keys.py", line 48
        ACTIVE_CRYPT_LIB = 'm2crypto' if EVP else 'pycrypto'
                                       ^
    SyntaxError: invalid syntax
      File "/usr/lib/python2.4/site-packages/keyczar/keyczar.py", line 342
        return encoder(ciphertext) if encoder else ciphertext
                                    ^
    SyntaxError: invalid syntax
    Installing keyczart script to /usr/bin
Successfully installed python-keyczar
Cleaning up...
```
