### ISSUE TITLE
generated module manpages has warnings

### ISSUE THREAD

**Issue by mvo5** [ansible/ansible#4764]
Hi,

the sphinx generated module man pages (e.g. ansible.zfs.3) give me a warning:
$ man --warnings   ./docs/man/man3/ansible.zfs.3  > /dev/null
<standard input>:2: warning: macro `"' not defined

There is also no "EXAMPLES" section in most man-pages, e.g. ansible.zfs.3 has
." ------ EXAMPLES
." ------ PLAINEXAMPLES
.nf
...
.fi

But no ".SH Examples" section header.

Thanks,
 Michael

**Comment by mpdehaan** [comment]
closing this given we have the other pull request ticket open -- housekeeping :)
