### ISSUE TITLE
Flush handlers on fail/error. 

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#4766]
Hi

As discussed on Google Groups https://groups.google.com/forum/#!topic/ansible-devel/WsWJYgxxoB0 
## Problem:

If ansible fails, ansible does not flush handlers.
## Expected:

ansible should flush handlers even on fail.
## Use case:

```
...
- name: config file of service named foobar
  copy src=foobar.conf dest=/etc/foobar.conf
  notify: restart foobar

- name: we make sure foobar is running
  # having a typo here...
  service: name=foobaR state=running enabled=yes
...
```

So you see I have a typo in 2nd task (foobaR instead of foobar). so ansible says something like "error: could not find service named foobaR".

In the copy task, file was transferred, but service foobar was never restarted. 

The next time you start the play, there is no change, so the service will not restarted again. You have to "remember" it and doing it manually or use --flush-handlers to flush them all.

**Comment by mpdehaan** [comment]
As discussed on the thread, we do _NOT_ want to do this every time.

We want instead a flag for ansible to --force-handlers

Closing this and opening the other as a RFE

**Comment by mpdehaan** [comment]
Opened here:  https://github.com/ansible/ansible/issues/4777

**Comment by resmo** [comment]
ok, misunderstood this... sorry for confusion.
