### ISSUE TITLE
Invalid reference in registeredvariable|changed in doc

### ISSUE THREAD

**Issue by asyd** [ansible/ansible#4771]
http://www.ansibleworks.com/docs/playbooks_variables.html show

```
result|changed
```

while the expecting syntax is

```
result.changed
```

**Comment by sivel** [comment]
That is not necessarily invalid.  

The `changed` filter was added for 1.4, which hasn't been released yet.  The docs, get built from the devel branch (as far as I know), so what you are seeing is documentation for the yet to be released version.

See #4437

**Comment by asyd** [comment]
Hmm ok I can understand. But it's a bit strange than /docs/ refers to the development version rather the stable one ihmo. How I can access to doc about 1.3? I remember it as possible using /docs/released/1.3/ but it doesn't work anymore

**Comment by mpdehaan** [comment]
@sivel We need to indicate the version added in the example, basically.

@asyd was reporting at my request :)
