### ISSUE TITLE
Add a way to force handler execution

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#4777]
If a playbook fails not all handlers may be run.

In this case it would be nice to have a --force-handlers that runs all handlers on a retry.

The line that prints the retry command should also indicate that this flag should be used.

**Comment by alanfairless** [comment]
Conceptually related to #4443.

**Comment by kustodian** [comment]
This would be the number one feature I would vote at this moment. It would also be nice if this flag could be configured as an option in `ansible.cfg` if you want it to be enabled all the time (it can be off by default).

Would this flag also mean that the handlers would be executed if the playbook fails the first time, or only on retry? I don't see why it shouldn't be possible to run handlers even if the playbook fails the first time.

**Comment by mpdehaan** [comment]
This will not be a ansible.cfg setting because we _don't_ want it to run all the time, this would defeat the point of "notify" only running things on change.

In those cases, just make something a task.

Anyway, look for this to come very soon.

The retry command will suggest adding --force-handlers, and --force-handlers is also a CLI switch you can select.  Nothing will be adding this flag automatically.

**Comment by jctanner** [comment]
@alanfairless and @kustodian this is now implemented via the "--force-handlers" parameter in ansible-playbook.

**Comment by voidzero** [comment]
I would like a --skip-handlers, for provisioning reasons (My handlers, for example, reload services. Sometimes those services are not running yet.)

**Comment by kustodian** [comment]
If you need to use --skip-handlers, than you are probably not using handlers the right way. Handlers are run at the end of the play, so just make sure to start the service before it reaches the end and you shouldn't have any problems.

Also handlers support `when: condition`, so you could set a condition for those cases when the service is still not running, even though I wouldn't recommend this.
