### ISSUE TITLE
Inconsistencies in package modules' states

### ISSUE THREAD

**Issue by alinnow** [ansible/ansible#4790]
The `apt` module allows the use of `state=installed` as a synonym for `state=present`. The `yum` and `pacman` modules are also documented with this feature.

Using the same state with the `pkgng` module results in an error that only `present` and `absent` states are allowed. This caught me by surprise, so I would suggest that all the package modules are made consistent where possible−I understand that some will have extra states like `latest`, and that's fine. But when states do the same thing, I think it would be best if they were consistent across modules.

**Comment by mpdehaan** [comment]
Only present/absent are documented, the other aliases are there for backwards compatibility from older versions only.

**Comment by alinnow** [comment]
Okay, so perhaps `state=installed` should be removed from the examples in the documentation to make this clear.
