### ISSUE TITLE
Traceback on UnicodeDecodeError

### ISSUE THREAD

**Issue by arrfab** [ansible/ansible#4796]
Not directly an Ansible issue, but let me explain it (as requested by mdehaan on #ansible) : 

ansible -i hosts/hosts.cfg -m setup mymachine -u root -a 'filter=ansible_product_serial_'  
mymachine | FAILED >> {
    "failed": true, 
    "msg": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-1383501273.05-178496394500210/setup\", line 3080, in <module>\n    main()\n  File \"/root/.ansible/tmp/ansible-1383501273.05-178496394500210/setup\", line 2147, in main\n    module.exit_json(_*data)\n  File \"/root/.ansible/tmp/ansible-1383501273.05-178496394500210/setup\", line 2902, in exit_json\n    print self.jsonify(kwargs)\n  File \"/root/.ansible/tmp/ansible-1383501273.05-178496394500210/setup\", line 2892, in jsonify\n    return json.dumps(data)\n  File \"/usr/lib64/python2.6/json/**init**.py\", line 230, in dumps\n    return _default_encoder.encode(obj)\n  File \"/usr/lib64/python2.6/json/encoder.py\", line 367, in encode\n    chunks = list(self.iterencode(o))\n  File \"/usr/lib64/python2.6/json/encoder.py\", line 309, in _iterencode\n    for chunk in self._iterencode_dict(o, markers):\n  File \"/usr/lib64/python2.6/json/encoder.py\", line 275, in _iterencode_dict\n    for chunk in self._iterencode(value, markers):\n  File \"/usr/lib64/python2.6/json/encoder.py\", line 309, in _iterencode\n    for chunk in self._iterencode_dict(o, markers):\n  File \"/usr/lib64/python2.6/json/encoder.py\", line 275, in _iterencode_dict\n    for chunk in self._iterencode(value, markers):\n  File \"/usr/lib64/python2.6/json/encoder.py\", line 294, in _iterencode\n    yield encoder(o)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte\n", 
    "parsed": false
}

It's due to an empty string in the bios (Serial Number)  : 
[root@mymachine tmp]# dmidecode -s system-serial-number
......................

After having edited my BIOS SN string with a DMI editor : 
[root@mymachine ~]# dmidecode -s system-serial-number
12345678      

->
ansible -i hosts/hosts.cfg -m setup mymachine -u root -a 'filter=ansible_product_serial*'  
mymachine | success >> {
    "ansible_facts": {
        "ansible_product_serial": "12345678"
    }, 
    "changed": false
}

Now I can play my playbooks on that machine ..

**Comment by mpdehaan** [comment]
What is "ansible --version"?

Thanks!

**Comment by arrfab** [comment]
Sorry, I forgot to mention it : ansible 1.3.0 (ansible-1.3.0-1.el6.noarch)

**Comment by tgerla** [comment]
Hi arrfab,

Someone else ran into this and I put together kind of a brute-force fix in my branch:

https://github.com/tgerla/ansible/tree/dmidecodefix

Want to test? There may be a better way to do this, but I had some trouble getting a system to reproduce this so I would appreciate extra testing.

-Tim

**Comment by jctanner** [comment]
@arrfab What kind of system do you have that causes an empty string for the serial number?

What is the output of this command? 

```
 dmidecode -s system-serial-number | od -c
```
