### ISSUE TITLE
Typo in _execute_raw method

### ISSUE THREAD

**Issue by jonten** [ansible/ansible#480]
Hi,

There is a typo in the _execute_raw method in devel branch in the file ../ansible/lib/ansible/runner/__init__.py. As I was told by mpdehaan at the mailinglist it should be result=data and not results=data. I fixed this in a fork and will do a pull request. Not sure if it was necessary though?

Cheers,
//Jon

**Comment by mpdehaan** [comment]
closing from your fix, thanks!
