### ISSUE TITLE
ansible-1.3.4.tar.gz is incomplete on PyPI

### ISSUE THREAD

**Issue by l1k** [ansible/ansible#4804]
The ansible-1.3.4.tar.gz tarball that was uploaded to PyPI is incomplete, it's only got 376763 bytes. The tarball on ansibleworks.com has 450676 bytes. Specifically, the PyPI tarball is missing all the module manpages in docs/man/man3/.

**Comment by mpdehaan** [comment]
should be fixed in latest update
