### ISSUE TITLE
Merge ansible_interfaces and ansible_$iface facts

### ISSUE THREAD

**Issue by Apsu** [ansible/ansible#4809]
Currently the setup module specifies that ansible_interfaces will be a flat list of interface name strings and each interface will have an ansible_$iface dict of the discovered interface information. However, this makes programmatically using the interface information very ugly, especially if you may expect that a given group of hosts may have different interface layouts, be missing interfaces, have unpredictable names but predictable orders, etc.

I propose a simple merging of the two ideas, such that the single fact will be structured like:

```
ansible_interfaces: {
  lo: {
    key: value,
    ...
  },
  eth0: {
  ...
  }
}
```

This allows you to not only check for the presence of a particular interface but also to iterate over them as you like, without having to attempt some sort of nonsense like {{ansible_{{item}}.ipv4.address}} that doesn't really work anyway.

**Comment by mpdehaan** [comment]
While I understand your points, this is not going to happen as it would break backwards compatibility.

**Comment by ghost** [comment]
This is really a good idea! Not a chance to implement it? What about something that can explicitly enabled at run-time, that doesn't affect old stuff, not braking backwards compatibility... ?
