### ISSUE TITLE
Referencing a var inside a hash that is set to !!null will be set to "None" when written out as yaml or json

### ISSUE THREAD

**Issue by jarv** [ansible/ansible#4812]
ansible-playbook 1.4 (devel 6517e0b54d) last updated 2013/11/05 10:43:51 (GMT -400)

Our application has a large configuration hash and we would like to override an element deep in the hash in different environments.  The way we do this is referencing defaults and overrides inside the hash ("my_cfg_hash" below).

In some cases we want to use "!!null" as a default which ends up converting to the string "None" when the hash is written out as either json or yaml using `{{ my_cfg_hash|to_nice_yaml}}` or `{{ my_cfg_hash|to_nice_json }}`

Example:

var file:

```
setting_override: !!null
my_cfg_hash:
  my_setting: "{{ setting_override }}"
```

to_nice_json renders as:

```
{
  "my_setting": "None"
}
```

Using deprecated variable syntax:

```
setting_override: !!null
my_cfg_hash:
  my_setting: $setting_override
```

renders as:

```
{
  "my_setting": "$setting_override"
}
```

What I would like to see this rendered as is 

```
{ 
  "my_setting": null
}
```

**Comment by bcoca** [comment]
!!null is a yamilism. Have you tried setting it to null?

Brian Coca

**Comment by jarv** [comment]
for both: `setting_override: null` and `setting_override: None` I get
`my_cfg_hash|to_nice_json` as:

```
{
    "my_setting": "None"
}
```

**Comment by jimi-c** [comment]
I've been digging into this, and unfortunately it seems to be a limitation of the jinja2 templating engine. At best, I can have it set the value to an empty string instead of "None", if that helps you?

**Comment by jimi-c** [comment]
@jarv I pushed the fix to my copy of the repo, if you'd like to test it. Here is the output I'm seeing (based on your sample vars above):

<pre>
$ cat ~/testing/test_4812.yml
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    setting_override: !!null
    my_cfg_hash:
      my_setting: '{{ setting_override }}'
  tasks:
  - name: dump var
    debug: var='{{ my_cfg_hash|to_nice_json }}'
$ ansible-playbook -vv ~/testing/test_4812.yml
PLAY [localhost] ************************************************************** 
TASK: [dump var] ************************************************************** 
ok: [127.0.0.1] => {
    "{\n    \"my_setting\": \"\"\n}": {
        "my_setting": ""
    }
}
PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

**Comment by jimi-c** [comment]
Since there has been no follow up and the commit above fixed the issue in my test cases, I went ahead and merged it into the main branch. If you continue to have problems with this, let us know. Thanks!
