### ISSUE TITLE
rax: flavor comparison fails with new performance tier

### ISSUE THREAD

**Issue by claco** [ansible/ansible#4814]
Now that the performance tier is happened, the "present" checks fail with an int() conversion on the flavor:

```
if int(flavor) != int(server.flavor['id']):
```

ValueError: invalid literal for int() with base 10: 'performance1-1'

**Comment by sivel** [comment]
This is already resolved and tested in the refactor that I am working on (#4577)

I hope to have that work merged for the 1.4 release.

Testers of that work would be greatly appreciated.

**Comment by mpdehaan** [comment]
Closing per the above merge commit already being merged, let me know if you disagree!

Thanks!
