### ISSUE TITLE
ansible

### ISSUE THREAD

**Issue by YuZongYangHi** [ansible/ansible#48155]
```
mongodb_user:
database: admin
name: pangu
password: sdvxcdlskadlk1231c
state: present
roles:
- db: aitc_matrix
role: userAdmin
Why can I only add admin tables? I try to change to other or nonexistent tables.

he localhost login exception only allows the first admin account to be created
```
Why can I only add admin tables? I try to change to other or nonexistent tables?

And when I initialize the startup, the variables do not seem to work.

Command line is OK.!!!

**Comment by mkrizek** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by YuZongYangHi** [comment]
I don't think so, at least in the examples I've seen so far, you can change user information in tables at will, but in fact you won't be allowed to do so in version 3.6 + of mongo.
