### ISSUE TITLE
Raise a warning when a reserved variable is set

### ISSUE THREAD

**Issue by jcassee** [ansible/ansible#4816]
As per [a list discussion](https://groups.google.com/forum/#!topic/ansible-project/fP0hX2Za4I0), it would be nice if a warning was printed if the user tries to set a reserved variable, such as `environment`.

**Comment by mpdehaan** [comment]
Classifying this as a bug report so it doesn't get lost in the list.

**Comment by samdaltonmaag** [comment]
+1, this had me stumped for a bit using "environment", and only figured it out after guessing it might be the case.

**Comment by FractalizeR** [comment]
Spent several hours figuring out why a variable named `environment` doesn't contain what I suppose it to contain.

+1 from me.

**Comment by FractalizeR** [comment]
BTW, is there is a list of all things 'reserved'? Just not to stumble over such cases again...

**Comment by bcoca** [comment]
not a central one, mostly we have some 'magic' internal vars and then keywords/directives for play, role and task.

**Comment by meebey** [comment]
I tried to pass a variable named port from a role definition like this:

```
- { role: myrole, port: '7689' }
```

The template module didn't like the port variable then like this:

```
AnsibleUndefinedVariable: ERROR! 'port' is undefined
```

The port variable was undefined till I renamed it to something else...

**Comment by FractalizeR** [comment]
@meebey Yep. Very annoying, right? :)

**Comment by schnittchen** [comment]
I just bumped into this as well, exactly as @meeby did.

While I understand that the devs have more important things to do with currently more than 1k issues open, is there a list of reserved variables names somewhere, maybe a link to the code?

**Comment by bcoca** [comment]
if only it where that simple, there are many and defined in different places

i added this for the basic objects, but far from a complete list http://docs.ansible.com/ansible/playbooks_directives.html

**Comment by schnittchen** [comment]
thanks @bcoca!
