### ISSUE TITLE
UnicodeDecodeError when receiving spanish output from a Wndows command

### ISSUE THREAD

**Issue by madmac2501** [ansible/ansible#4821]
I am doing a task that interacts with an spanish Windows. The stderr from one command has the character 'á', the string encoding is lost and later it cannot be interpreted.

I am using ansible v1.3.4

This could be a solution, but I don't really like to lose information.

```
def jsonify(self, data):
    try:
        return json.dumps(data)
    except UnicodeDecodeError:
        print data
        data_encoded = {}
        for k, v in data.items():
            if type(v) == str:
                data_encoded[k] = unicode(v, errors='replace')
            else:
                data_encoded[k] = v
        return json.dumps(data_encoded)
```

Some more information

This is the dictionary passed to jsonify:

{"changed": true, "end": "2013-11-06 06:46:03.987240", "stdout": "Unknown parameter encountered: \"max log size\"\nIgnoring unknown parameter \"max log size\"\nUnknown parameter encountered: \"syslog\"\nIgnoring unknown parameter \"syslog\"\nUnknown parameter encountered: \"passdb backend\"\nIgnoring unknown parameter \"passdb backend\"\nUnknown parameter encountered: \"unix password sync\"\nIgnoring unknown parameter \"unix password sync\"\nUnknown parameter encountered: \"passwd program\"\nIgnoring unknown parameter \"passwd program\"\nUnknown parameter encountered: \"pam password change\"\nIgnoring unknown parameter \"pam password change\"\nUnknown parameter encountered: \"valid users\"\nIgnoring unknown parameter \"valid users\"\nUnknown parameter encountered: \"guest ok\"\nIgnoring unknown parameter \"guest ok\"\nUnknown parameter encountered: \"guest ok\"\nIgnoring unknown parameter \"guest ok\"\nPresione una tecla para continuar . . . \r\nossec-agent\service-stop: Attempting to stop ossec.", "cmd": "echo $'\n' | winexe --user=WIN-0CJSLLCLJEK/jmalbarracin%sys --configfile=/etc/ossim/agent/smb.conf //192.168.8.131 'cmd /c cd \"C:\Program Files (x86)\" & ossec-agent\service-stop' ", "rc": 0, "start": "2013-11-06 06:46:02.702721", "stderr": "El servicio de OSSEC HIDS no se ha iniciado.\r\n\r\nPuede obtener m\u00a0s ayuda con el comando NET HELPMSG 3521.", "delta": "0:00:01.284519"}

The task that reproduces the issue:

```
- name: Stop agent
  action: shell echo $'\n' | winexe --user={{windows_domain}}/{{windows_username}}%{{windows_password}} --configfile={{smb_winexec_config_file}} //{{windows_ip}} 'cmd /c cd "{{PROGRAM_FILES_DRIVE.stdout}}:\{{PROGRAM_FILES_DIR.stdout}}" & ossec-agent\service-stop'
```

The output of the task:

```
TASK: [Stop agent] ************************************************************
<192.168.254.10> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1383729136.45-147956778067881 && chmod a+rx $HOME/.ansible/tmp/ansible-1383729136.45-147956778067881 && echo $HOME/.ansible/tmp/ansible-1383729136.45-147956778067881']
<192.168.254.10> REMOTE_MODULE command echo $'\n' | winexe --user=WIN-0CJSLLCLJEK/jmalbarracin%sys --configfile=/etc/ossim/agent/smb.conf //192.168.8.131 'cmd /c cd "C:\Program Files (x86)" & ossec-agent\service-stop' #USE_SHELL
<192.168.254.10> PUT /tmp/tmpGihYTR TO /home/avapi/.ansible/tmp/ansible-1383729136.45-147956778067881/command
<192.168.254.10> EXEC ['/bin/sh', '-c', '/usr/bin/python /home/avapi/.ansible/tmp/ansible-1383729136.45-147956778067881/command; rm -rf /home/avapi/.ansible/tmp/ansible-1383729136.45-147956778067881/ >/dev/null 2>&1']
failed: [192.168.254.10] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/avapi/.ansible/tmp/ansible-1383729136.45-147956778067881/command", line 1137, in <module>
    main()
  File "/home/avapi/.ansible/tmp/ansible-1383729136.45-147956778067881/command", line 155, in main
    changed = True
  File "/home/avapi/.ansible/tmp/ansible-1383729136.45-147956778067881/command", line 911, in exit_json
    print self.jsonify(kwargs)
  File "/home/avapi/.ansible/tmp/ansible-1383729136.45-147956778067881/command", line 901, in jsonify
    return json.dumps(data)
  File "/usr/lib/python2.6/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.6/json/encoder.py", line 367, in encode
    chunks = list(self.iterencode(o))
  File "/usr/lib/python2.6/json/encoder.py", line 309, in _iterencode
    for chunk in self._iterencode_dict(o, markers):
  File "/usr/lib/python2.6/json/encoder.py", line 275, in _iterencode_dict
    for chunk in self._iterencode(value, markers):
  File "/usr/lib/python2.6/json/encoder.py", line 294, in _iterencode
    yield encoder(o)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 63: invalid start byte


FATAL: all hosts have already failed -- aborting
```

**Comment by jctanner** [comment]
@madmac2501 what are you using for sshd on the windows client? Not relevant to the issue, but I'm curious for testing purposes.

**Comment by madmac2501** [comment]
@jctanner I am running ansible on a linux host, the windows machine doesn't have sshd I use smb for winexec

**Comment by jctanner** [comment]
@madmac2501 oh ok, so the linux machine has the winexe binary and you are calling that to connect over the smb protocols.

**Comment by madmac2501** [comment]
@jctanner Yes, that's it. Also please note that the Windows machine is installed in spanish

**Comment by mpdehaan** [comment]
Ok so this is just a generic unicode issue and not Windows specific.

Sounds reasonable.

Windows clients are definitely not supported at this time.

**Comment by jimi-c** [comment]
The above patch should correct the issue, and seemed a bit simpler than the proposed fix above. Let us know if you continue having issues with this. Thanks!

**Comment by madmac2501** [comment]
Thank you very much for the fix!

**Comment by trantor** [comment]
Using the shell module with a command returning output from remote files containing both utf-8 and latin1 text, the stdout of the command is blank, although the module returns OK as expected.
Git bisect leads to the fix for this issue.
