### ISSUE TITLE
authorized_key module does not rewrite correctly key options

### ISSUE THREAD

**Issue by erachen** [ansible/ansible#4826]
When rewriting authorized_keys file, the module
1. insert space between options
2. remove protecting double quote on the 'command' option
the above lead to a syntax error that may lead to losing control on a server (especially if password login is disabled)

To illustrating that, given an authorized_keys file with 2 key:

```
ssh-dss <long_base64_key> admin@server
no-pty,command="/bin/restricted_shell" ssh-dss <long_base64_key> backup@backupserver
```

after rewriting:

```
ssh-dss <long_base64_key> admin@server
no-pty, command=/bin/restricted_shell  ssh-dss <long_base64_key> backup@backupserver
```

**Comment by sivel** [comment]
I believe this was already resolved in ansible 1.4 (devel).  What version of ansible are you using?  `ansible --version`

**Comment by sivel** [comment]
See #4487

**Comment by erachen** [comment]
Short story: thanks a lot, it is solved !

sorry to have forgot this basic information (it's the end of a long long day...)

well I was using ansible 1.4 on branch devel (here is the last commit I've got in history)
Date:   Sun Oct 20 12:52:09 2013 -0400

and then following you're advice, I checkout the new version and find that it is working perfectly !
Great job!
