### ISSUE TITLE
airbrake_deployment module: allow different hostname to be provided

### ISSUE THREAD

**Issue by drewda** [ansible/ansible#4828]
**_continuing discussion from https://github.com/ansible/ansible/pull/3016#issuecomment-27908668**_

In addition to sending updates about a new deployment to the Airbrake hosted service, I'd like to be able to send an update to my own hosted instance of [Errbit](https://github.com/errbit/errbit), an open-source project that has an API equivalent to Airbrake's.

Here's where the Airbrake endpoint is hard-coded in currently: https://github.com/ansible/ansible/blob/devel/library/monitoring/airbrake_deployment#L119

/cc @bpennypacker

**Comment by bpennypacker** [comment]
@drewda - Go ahead and try this out.  If it works I'll submit a pull request.  If you see any issues go ahead and comment on the commit rather than here:

https://github.com/bpennypacker/ansible/commit/83a1665be55649fb57c1630e5d900e91697badf7

**Comment by mpdehaan** [comment]
any progress on turning this one into a pull request?

I'm going to close this ticket but we'd welcome additions to the pull request queue.

Thanks!

**Comment by bpennypacker** [comment]
@mpdehann: Pull request has been open for a month (and mentioned in this issue): https://github.com/ansible/ansible/pull/5039
