### ISSUE TITLE
No response with shell module on MacOS system.

### ISSUE THREAD

**Issue by kevintsai** [ansible/ansible#4833]
Have no stdout and stderr response when using shell module on MacOS system.
###### Environment:

Host Machine: MacOS 10.8 and Ansible 1.3.2
Target Machine: MacOS 10.9
The 'brew' installed default location: /usr/local/bin/brew

Target Machine the 'which' command execution:

```
$ which brew
/usr/local/bin/brew
```
###### Task as follows:

```
- name: check brew
  shell: echo `which brew`
  register: is_brew_exist
- debug: msg="is brew exist => ${is_brew_exist}"
```
###### The output:

```
ok: [192.168.3.101] => {  
  "item": "", 
  "msg": "is brew exist => {
    u'changed': False, 
    u'end': u'2013-11-07 18:55:55.003999',
    u'stdout': u'', 
    'item': '', 
    u'cmd': u'echo `which brew` ', 
    u'rc': 0, 
    u'start': u'2013-11-07 18:55:54.999054', 
    u'stderr': u'', u'delta': u'0:00:00.004945', 
    'invocation': {'module_name': 'shell', 'module_args': 'echo `which brew`'},
    'stdout_lines': []}"}
```

but when i copy the brew to /usr/bin/brew from /usr/local/bin/brew, the stdout will works fine.

```
u'stdout': u'/usr/bin/brew'
```

**Comment by mpdehaan** [comment]
Sounds like brew just isn't in your path and there's nothing wrong with the command here.

Run "which toadstool" without anything called toadstool installed and you get exactly the same thing.
