### ISSUE TITLE
not_in_host_file() checks wrong user's known_hosts file when ran with sudo

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#4834]
See https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/connection_plugins/ssh.py#L119

When one runs ansible(-playbook) itself through sudo on the local machine, `host_file` resolves to the one in the $SUDO_USER's home folder (probably as $HOME still points to it) not the one from the user ansible is ran as.

This should reference `~$USER`?

**Comment by srgvg** [comment]
`host_file = os.path.expanduser(os.path.expandvars("~${USER}/.ssh/known_hosts"))` solves this.
If that's an acceptable solution, I'll make a PR for it.

**Comment by jctanner** [comment]
@sergevanginderachter yeah that seems good to me. Submit a PR and I'll test it.
