### ISSUE TITLE
insertafter argument to lineinfile causes traceback

### ISSUE THREAD

**Issue by drfickle** [ansible/ansible#4838]
Given this test playbook

```
- name: My Playbook
  hosts: "{{ hosts }}"

  tasks:
    - lineinfile: dest=/etc/network/interfaces regexp="^iface lo inet" line="# Goodbye cruel loopback" backup=yes                                  
    - lineinfile: dest=/etc/network/interfaces regexp="^iface eth0 inet" insertafter="# Monkeys taste delicious" backup=yes
```

and this existing interfaces file

```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet dhcp

```

The 'line' argument goes fine, but the 'insertafter' goes boom

```
TASK: [lineinfile dest=/etc/network/interfaces regexp="^iface eth0 inet" insertafter="# Monkeys taste delicious" backup=yes] *** 
fatal: [HOST OMITTED] => failed to parse: Traceback (most recent call last):
  File "/home/stevefox/.ansible/tmp/ansible-1383854533.0-72200804882391/lineinfile", line 1255, in <module>
    main()
  File "/home/stevefox/.ansible/tmp/ansible-1383854533.0-72200804882391/lineinfile", line 319, in main
    ins_aft, ins_bef, create, backup, backrefs)
  File "/home/stevefox/.ansible/tmp/ansible-1383854533.0-72200804882391/lineinfile", line 208, in present
    if lines[index[0]] != new_line + os.linesep:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by drfickle** [comment]
Duh. I forgot to mention this is with Ansible 1.3.1

**Comment by jctanner** [comment]
@drfickle Have you tested this with any newer releases of 1.3.x or devel?

**Comment by drfickle** [comment]
1.3.4 gives the same error.
devel gives

```
msg: line= is required with state=present
```

**Comment by jctanner** [comment]
@drfickle the message from devel is the right behavior. You did you not specify a line to insert into the file with your second task.

**Comment by drfickle** [comment]
@jctanner I'm confused as to the intent of the argument then. My goal was to locate a line in the file, then insert a new line after the matching one. Doing this

```
lineinfile: dest=/etc/network/interfaces regexp="^iface eth0 inet" line="# Monkeys taste delicious" insertafter="^iface eth0 inet" backup=yes
```

not only seems redundant (specifying both regexp and lineafter), but results in removal of the "iface eth0 inet" line

```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
# Goodbye cruel loopback

# The primary network interface
auto eth0
# Monkeys taste delicious
```

If you can explain this argument to me, I'd be happy to submit a documentation patch to clarify its usage. Thanks.

**Comment by jctanner** [comment]
@drfickle I believe you are getting caught by the meaning of "insertafter". From the module docstring ...

```
  insertafter:
    required: false
    default: EOF
    description:
      - Used with C(state=present). If specified, the line will be inserted
        after the specified regular expression. A special value is
        available; C(EOF) for inserting the line at the end of the file.
        May not be used with backrefs.
    choices: [ 'EOF', '*regex*' ]
```

This is not the string you want to insert, this is a regex to indicate where "line" should go. The string that will be placed in the file is defined by "line". So if you wanted to place "# Monkeys taste delicious" -after- "^iface eth0 inet dhcp", you would set the parameters like this ...

```
    - lineinfile: dest=/tmp/interfaces
                  backup=yes
                  line="# Monkeys taste delicious"
                  insertafter="^iface eth0 inet"
```

**Comment by drfickle** [comment]
@jctanner It looks like it's just a 1.3.x problem again. That branch requires both regex and insertafter, and then essentially ignores the insertafter. I have verified that it works as expected in the 'devel' branch. I will wait to use insertafter until 1.4 is released. Thank you.
