### ISSUE TITLE
Allow the user to set the disk size of the root partition partition on ec2

### ISSUE THREAD

**Issue by evanccnyc** [ansible/ansible#4840]
In boto, you can set the size of the root, before you launch the instance.  This is really helpful if you need more disk size then whatever the ami has.

The example boto code is here:

 https://gist.github.com/anonymous/df0ddf374b3dd982c670

**Comment by lwade** [comment]
Would be good to support block device mappings.  Keep in mind that this example is for EBS-backed instances only, not Instance-store backed.

**Comment by willthames** [comment]
This would be a minor tweak to https://github.com/ansible/ansible/pull/4534
to allow the special case of /dev/sda1 with a custom size.

**Comment by mpdehaan** [comment]
I'm closing this ticket as we have a pull request open now that tracks this issue, just to keep github easier to organize.   This ticket can still be found from the other.
