### ISSUE TITLE
Daemon for accelerated mode starts, connection to it not established

### ISSUE THREAD

**Issue by jangondol** [ansible/ansible#4841]
When using `accelerate: true`, Ansible (1.4) first starts the daemon at the target machine (if not running yet). If the target is specified in ansible_hosts using an IP address or a resolvable hostname, tasks are then executed as expected (using the accelerated connection). However, _task execution fails for non-resolvable hosts_ specified in `~/.ssh/config`, e.g.:

```
Host servernickname
    HostName 10.0.0.10
```

(In this scenario, "servernickname" is a hostname not resolvable outside of SSH -- however, there _is_ a route to IP 10.0.0.10 and it isn't firewalled.)

If such a nickname is used, the first phase (i.e., starting the accelerated mode daemon on the target using ssh transport) works fine, but the connection to the newly created daemon fails (error messages: `Could not connect via the accelerated connection, exceeded # of tries` -- `fatal: [servernickname] => Failed to connect to servernickname:5099` -- `FATAL: all hosts have already failed -- aborting`).

The connection is not created (error message: `failed, retrying...`) -- the line responsible for this is `self.conn.connect((self.host,self.accport))` in `acccelerate.py`. The operation seems to time out because of name resolution.

_Current behavior_: Ansible uses ssh config file to resolve the host name for creation of accelerated mode daemon. Once the daemon is running, it will try a _different_ method for target name resolution, which fails in this scenario (and it seems confusing).

_Desired behavior_: use settings in `~/.ssh/config` for both phases (daemon creation, task execution). The playbook would then behave similarly whether it contains `accelerate: true` or not -- at least for the directly accessible targets (i.e., those not hidden behind bastion hosts).

An easy solution is to specify all hostnames in ansible_hosts using FQDNs or IPs but I'd really prefer to keep the shortened nicknames for convenience and manageability. Does this affect others and should this be fixed?

**Comment by jctanner** [comment]
@jangondol If you add this to your inventory, does it help the issue?

```
servernickname ansible_ssh_hostname=10.0.0.10
```

**Comment by jangondol** [comment]
Hello @jctanner, thank you, I tried the suggested inventory workaround (using the latest checkout from github), same error messages: `failed, retrying...` + finally `Could not connect via the accelerated connection, exceeded # of tries` + `fatal: [servernickname] => Failed to connect to servernickname:5099` + `FATAL: all hosts have already failed -- aborting`

Both using FQDN and using IP in the inventory (even without ansible_ssh_hostname) work as expected. Anyone else able to replicate this?

**Comment by mpdehaan** [comment]
So as accelerate mode isn't SSH I shouldn't expect accelerate mode would dive into ssh config and attempt to figure out what the alias you were using for your host was.

**Comment by jangondol** [comment]
Hello Michael, thanks for commenting.

I think you might be right, and still: it feels somewhat counter-intuitive that the first phase (launching the daemon using SSH) works correctly and the second phase fails silently due to the difference in name resolution method.

Personally, I see at least two ways to address this:

1) Leave the code as it is now but point out in the documentation that users should be aware of the issue (I spent hours trying to figure out what was wrong, seeing the daemon being launched but not being able to connect to it anyway). It would be nice to figure out where the problem was without having to dive into source code.

2) Update the code to use info from SSH config in accelerate.py after launching the daemon.

In case of scenario 1, it might be useful to point out that users should always include FQDNs / IPs and never nicknames for servers if they want to use accelerated mode. Also, the debug error message for accelerated module failure could include a hint to check this first.

If you prefer scenario 1, please let me know and I'll send a PR. For scenario 2, it would be quicker if someone else looked at this (to make sure it's done correctly). What do you think?

**Comment by mpdehaan** [comment]
I think we're ok, I understand why you were confused above, if we get a few more people feeling the same we'll think about it.

I think most people would not except aliases to work the way you have indicated.

**Comment by rgarrigue** [comment]
+1 with @jangondol

**Comment by mpeters** [comment]
+1 with @jangondol 
In my case, it wasn't aliases in the ssh config but in /etc/hosts. They work everywhere else inside ansible and out, but not with ansible accelerated mode. I understand the technical reasons why, but it's still a weird limitation looking from the outside.

**Comment by mwpher** [comment]
+1 with @jangondol 

In my case (OpenBSD control, FreeBSD Node), not even using IPs or FQDN works.

EDIT: I have found that changing the daemon port number to 10000 in ansible.cfg makes the daemon work. I guess this is a separate issue. Ignore me. :)
