### ISSUE TITLE
mysql_db force option

### ISSUE THREAD

**Issue by jkordish** [ansible/ansible#4843]
I have an issue with importing sql schema into databases. If upon importing a table exists it will cause mysql to error thus causing the playbook to fail. The mysql command does allow for force via the -f argument. Using this flag it will continue through the sql import even if a table exists and not error out. 

mysql_db:
138     cmd += " -f --user=%s --password=%s" %(user, password)

While this may not be wanted behavior for all occurrences maybe the addition of a force option for the mysql_db module. Such as a force=yes with the default being no.

**Comment by mpdehaan** [comment]
Going through old tickets.

I think in this case it would be better to just shell out to the mysql command because most folks are not going to want this behavior.

Using a migration system (such as South) can also provide cleaner ways to do conditional upgrades.
