### ISSUE TITLE
can't access to existing "ansible_eth1" fact

### ISSUE THREAD

**Issue by jpcaruana** [ansible/ansible#4848]
I successfully managed to add a private IP address on my servers. I can see both network interfaces eth0 and eth1 when I ask for the facts of this server :

```
$ ansible server -m setup -i production
        "ansible_eth0": {
            "active": true,
            "device": "eth0",
            "ipv4": {
                "address": "x.x.x.x",
                "netmask": "x.x.x.x",
                "network": "x.x.x.x"
            },
            "ipv6": [
                {
                    "address": "x::x:x:x:x",
                    "prefix": "64",
                    "scope": "link"
                }
            ],
            "macaddress": "x:x:x:x:x:x",
            "module": "e1000e",
            "mtu": 1500,
            "type": "ether"
        },
        "ansible_eth1": {
            "active": true,
            "device": "eth1",
            "ipv4": {
                "address": "x.x.x.x",
                "netmask": "x.x.x.x",
                "network": "x.x.x.x"
            },
            "ipv6": [
                {
                    "address": "x::x:x:x:x",
                    "prefix": "64",
                    "scope": "link"
                }
            ],
            "macaddress": "x:x:x:x:x:x",
            "module": "e1000e",
            "mtu": 9000,
            "type": "ether"
        }
```

But when I want to access the "ansible_eth1" fact from my playbook :

```
# dest file is /etc/hosts
# locally resolve private IPs
{% for host in groups['all'] %}
{{ hostvars[host]['ansible_eth1']['ipv4']['address'] }}       {{ host }}
{% endfor %}
```

I get the following error on every single server :

```
fatal: [server] => {'msg': "One or more undefined variables: 'dict object' has no attribute 'ipv4'", 'failed': True}
```

This kind of code worked really good with eth0 ,as you can see in my fully working iptables template extract :

```
{% for host in groups['all'] %}
# access from {{ host }}
-A INPUT -p tcp -m tcp -s {{ hostvars[host]['ansible_eth0']['ipv4']['address'] }} --dport {{ some_port }} -j ACCEPT
{% endfor %}
```

I would like to be able to write :

```
{% for host in groups['all'] %}
# access from {{ host }}
-A INPUT -p tcp -m tcp -s {{ hostvars[host]['ansible_eth1']['ipv4']['address'] }} --dport {{ some_port }} -j ACCEPT
{% endfor %}
```

**Comment by jpcaruana** [comment]
To gather more information, I decided to print the content of the **ansible_eth1** key inside my generated hosts file... I don't know if there is a more straightforward way to enter in debugging mode, still I found interesting data.

I replaced

```
{{ hostvars[host]['ansible_eth1']['ipv4']['address'] }}       {{ host }}
```

with

```
{{ hostvars[host]['ansible_eth1'] }}       {{ host }}
```

in my template

and got this (formatted for your eyes) dict, the content of the **ansible_eth1** key :

```
{
    'macaddress': 'x:x:x:x:x:x',
    'module': 'tg3',
    'mt': 9000,
    'device': 'eth1',
    'ipv4': {
        'netmask': 'x.x.x.x',
        'network': 'x.x.x.x',
        'address': 'x.x.x.x'
    },
    'ipv6': [
        {
            'scope': 'link',
            'prefix': '64',
            'address': 'x::x:x:x:x'
        }
    ],
    'active': True,
    'type': 'ether'
}
```

As we can see, there is a **ipv4** key and inside this there is a **address** key.

Informations are exactly the same with _"ansible server -m setup"_, so I'm satisfied.  I have as many lines in the generated file as my servers in my inventory, so I'm satisfied again.

So why can't I access to **ansible_eth1.ipv4** from my template ?

**Comment by mpdehaan** [comment]
Have you narrowed this down by using --limit to exactly one host and made sure there is an ipv4 address for that host?

I'm guessing one host might not have an ipv4 address for that interface.

**Comment by mpdehaan** [comment]
This is still in a question / tech-support mode and there's no issue with the underlying Jinja2, so I'm going to close this ticket.

Let's continue on the mailing list and/or IRC

**Comment by jpcaruana** [comment]
ok thanks
(sorry for the delay, yesterday was a day off in France (end of world war 1))

**Comment by ihinsdale** [comment]
@jpcaruana Did you find a solution to this? I am having the _exact_ same problem. 

edit: P.S. I have seen your mailing list [thread](https://groups.google.com/forum/#!topic/Ansible-project/RS1Mvdfjk2k) about this but it doesn't seem any resolution was reached there. I am using Ansible version 1.5.4. Thanks for any advice!

edit2: I solved the problem by ensuring my playbook had 'talked' to the servers whose ansible_eth1 ipv4 address I was trying to use, before I tried to use it. It is not enough, apparently, for the hosts whose ansible_eth1 you want to reference to be in your inventory file; you also need to perform some task on them in your playbook. I still don't understand the distinction made in the [documentation](http://docs.ansible.com/playbooks_variables.html#magic-variables-and-how-to-access-information-about-other-hosts) between getting at variables and not being able to see facts--"If, at this point, you haven’t talked to that host yet in any play in the playbook or set of playbooks, you can get at the variables, but you will not be able to see the facts."--but it would seem in this case that successfully referencing ansible_eth1 requires 'seeing the facts', and therefore talking to the host in a play.

**Comment by jpcaruana** [comment]
Hi @ihinsdale,
as a matter of fact, I haven't found a decent solution for this. I put my eth1 IP adresses directly in my template file... :(

**Comment by Ajibola** [comment]
@jpcaruana what is the syntax for putting eth1 ip address in the tpl file? I tried putting 127.0.0.1 but it throws the error float object has no element 0.

I guess it thinks its an object.

**Comment by jpcaruana** [comment]
no syntax, I put the hard coded IP in my template

**Comment by jpcaruana** [comment]
then, I found that some of my servers didn't have an eth1 address (and it is ok)

this finally worked : 

```
{% for host in groups['all'] %}
{% if hostvars[host]['ansible_eth1']['active'] %}
{{ hostvars[host]['ansible_eth1']['ipv4']['address'] }}       {{ host }}
{% endif %}
{% endfor %}
```

**Comment by Ajibola** [comment]
ok, I got this from serverfault : (ansible_eth1 | default(ansible_lo)).ipv4.address. http://serverfault.com/questions/641326/issues-with-ansibles-default-error-handling-in-a-playbook

It seems to get the job done. Thanks.

**Comment by jayunit100** [comment]
FYI For vagrant users, looks like one way to prevent **a similar error** (not this exact one) is to make sure you run with `ansible.limit="all".

**Comment by aluksidadi** [comment]
i fixed this by adding in the beginning of the playbook

```
- name: gather all hosts information
  hosts: all
```

**Comment by ksingh7** [comment]
I hit this and managed to fix it in these two ways

1#  Instead of using hostvars[host]  i used hostvars[inventory_hostname](so it worked for me)
2#  Then i realized that i really need to use hostvars[host]  functionality so i used hostvars[host] without using --limit <hostname> ( which i was using earlier ) 

So my finding was not to use --limit or -l while running ansible-playbook
