### ISSUE TITLE
DEBUG_LEVEL in accelerate

### ISSUE THREAD

**Issue by stevew-Purdue** [ansible/ansible#4851]
The logic for checking DEBUG_LEVEL is reversed in the log function of library/utilities/accelerate (v. 1.3).  It currently tests against DEBUG_LEVEL like this:
    if cap >= DEBUG_LEVEL:
when I believe it should be this:
    if DEBUG_LEVEL >= cap:

Steve

**Comment by jimi-c** [comment]
I haven't seen any issues with it logging things inappropriately, do you have an example of an issue with the code the way it is?

**Comment by stevew-Purdue** [comment]
On 11/09/2013 12:11 AM, James Cammarata wrote:

> I haven't seen any issues with it logging things inappropriately, do 
> you have an example of an issue with the code the way it is?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ansible/ansible/issues/4851#issuecomment-28119182.

This is what I expect to see and do see after the change I made:

> Nov 11 05:44:42 palantir ansible-accelerate: Invoked with debug=0 
> password=NOT_LOGGING_PASSWORD minutes=30 port=5099 timeout=300
> Nov 11 05:44:42 palantir ansible-accelerate: daemon pid 25393, writing 
> /root/.accelerate.pid
> Nov 11 05:44:42 palantir ansible-accelerate: daemonizing successful

But the following debug messages are what I saw until I made the 
change.  I'll only include the first 20 lines since for this example 
there were 814 debug messages logged:

> Nov  8 05:44:35 palantir ansible-accelerate: Invoked with debug=0 
> password=NOT_LOGGING_PASSWORD minutes=30 port=5099 timeout=300
> Nov  8 05:44:35 palantir ansible-accelerate: exiting pid 29613
> Nov  8 05:44:35 palantir ansible-accelerate: daemon pid 29614, writing 
> /root/.accelerate.pid
> Nov  8 05:44:35 palantir ansible-accelerate: pidfile written
> Nov  8 05:44:35 palantir ansible-accelerate: daemonizing successful
> Nov  8 05:44:35 palantir ansible-accelerate: serving!
> Nov  8 05:44:35 palantir ansible-accelerate: waiting for data
> Nov  8 05:44:35 palantir ansible-accelerate: in recv_data(), waiting 
> for the header
> Nov  8 05:44:35 palantir ansible-accelerate: in recv_data(), got the 
> header, unpacking
> Nov  8 05:44:35 palantir ansible-accelerate: data received so far 
> (expecting 249): 0
> Nov  8 05:44:35 palantir ansible-accelerate: data received so far 
> (expecting 249): 249
> Nov  8 05:44:35 palantir ansible-accelerate: received all of the data, 
> returning
> Nov  8 05:44:35 palantir ansible-accelerate: got data, decrypting
> Nov  8 05:44:35 palantir ansible-accelerate: decryption done
> Nov  8 05:44:35 palantir ansible-accelerate: loading json from the data
> Nov  8 05:44:35 palantir ansible-accelerate: received a command 
> request, running it
> Nov  8 05:44:35 palantir ansible-accelerate: executing: mkdir -p 
> $HOME/.ansible/tmp/ansible-1383907475.57-252650594031227 && echo 
> $HOME/.ansible/tmp/ansible-1383907475.57-252650594031227
> Nov  8 05:44:35 palantir ansible-accelerate: got stdout: 
> /root/.ansible/tmp/ansible-1383907475.57-252650594031227
> Nov  8 05:44:35 palantir ansible-accelerate: got stderr:
> Nov  8 05:44:35 palantir ansible-accelerate: thread is done, response 
> from join was {'stdout': 
> '/root/.ansible/tmp/ansible-1383907475.57-252650594031227\n', 
> 'stderr': '', 'rc': 0}

Regards,
Steve

**Comment by mpdehaan** [comment]
Ok the code is this:

```
DEBUG_LEVEL=0
def log(msg, cap=0):
    global DEBUG_LEVEL
    if cap >= DEBUG_LEVEL:
        syslog.syslog(syslog.LOG_NOTICE|syslog.LOG_DAEMON, msg)

def vv(msg):
    log(msg, cap=2)

def vvv(msg):
    log(msg, cap=3)

def vvvv(msg):
    log(msg, cap=4)
```

Let us say that DEBUG_LEVEL is 3.

If we call vvvv, cap of 4 greater than 3 and it will log.

I would agree the code is incorrect.

cc @jimi-c

**Comment by jctanner** [comment]
@stevew-Purdue thank you for isolating this! Feel free to send a pull request next time so that we can give you credit.
