### ISSUE TITLE
Errors out when user can't write to /var/log even if they can to /var/log/ansible.log

### ISSUE THREAD

**Issue by rackergs** [ansible/ansible#4852]
When enabling logging to /var/log/ansible.log and ensuring that the user has access to write to the file, when ansible runs it will fail stating:

```
log file at /var/log/ansible.log is not writeable, aborting
```

If ugo+w is set on /var/log then ansible stops erroring.
### What version of ansible you are using (ansible --version)

ansible 1.3.4
### Steps to reproduce the problem
1. Create /var/log/ansible.log (0775 owned root:ansible am creating ansible group for all users to dump logs here)
   2: Change to user in ansible group
   3: Run ansible
   4: Error
### Expected results

Ansible to run with log data to go into /var/log/ansible.log
### Actual results

```
[me@boxen ~]$ sudo touch /var/log/ansible.log
[me@boxen ~]$ sudo chmod 0775 /var/log/ansible.log
[me@boxen ~]$ sudo chown root:ansible /var/log/ansible.log
[me@boxen ~]$ getent group ansible
ansible:x:1001:me      
[me@boxen ~]$ su - me # to reset my group access
Password:
[me@boxen ~]$ echo 'blah' >> /var/log/ansible.log
[me@boxen ~]$ tail -1 /var/log/ansible.log
blah
[me@boxen ~]$ ll -d /var/log
drwxr-xr-x. 24 root root 4096 Nov  8 09:09 /var/log
[me@boxen ~]$ ll -d /var/log/ansible.log
-rwxrwxr-x. 1 root ansible 26401 Nov  8 09:52 /var/log/ansible.log
[me@boxen ~]$ ansible localhost -m ping -k
log file at /var/log/ansible.log is not writeable, aborting
```
### Whats wrong?

In lib/ansible/callbacks.py on line 34 there is a if or set of logic.

if (path exists and not writeable) or (parent dir of path not writeable) then fail

I'd argue it should just be an and, but could be wrong.  Would need to write out all the possibilities.

**Comment by jctanner** [comment]
@rackergs thank you for isolating this!

**Comment by rackergs** [comment]
thanks for fixing it! :+1:

**Comment by dminca** [comment]
Issue still persisting in `ansible 2.1.2.0`

```
➜  work/ansible git:(master) ✗ ansible -i inventories 'spk' -m command -a 'df -h'  
[WARNING]: log file at /var/log/ansible.log is not writeable and we cannot create it, aborting
```

**Comment by rajasoun** [comment]
Issue still Persists in ansible 2.2
