### ISSUE TITLE
parameterized roles and notification behavior change in ansible 1.4  

### ISSUE THREAD

**Issue by jarv** [ansible/ansible#4853]
## Summary

We would like to have a paramaterized role to configure a service and have a handler that restarts the service using parameters that are passed into the role.

A real world example is a role that installs supervisor that takes a path to a virtual environment and config parameters as parameters.  In that case we want to notify a restart on the service using the parameters for each time it is called.  This seems to work ok in 1.3, it breaks in 1.4.
## Simple example to illustrate the issue:

test/tasks/main.yml:

```
- shell: echo "test - {{ test_param }}"
  notify: test handler
```

test/handlers/main.yml:

```
- name: test handler
  debug: msg="handler {{ test_param }}"
```

play:

```
- hosts: all
  roles:
    - { role: test, test_param: "first call to test" }
    - { role: test, test_param: "second call to test" }
```
### ansible 1.3 output:

_This seems to work as expected_

```
TASK: [shell echo "test - first call to test"] ******************************** 
changed: [localhost]

TASK: [shell echo "test - second call to test"] ******************************* 
changed: [localhost]

NOTIFIED: [test handler] ****************************************************** 
ok: [localhost] => {"item": "", "msg": "handler first call to test"}

NOTIFIED: [test handler] ****************************************************** 
ok: [localhost] => {"item": "", "msg": "handler second call to test"}
```
### ansible-playbook 1.4 (devel f347133d85) output:

_Note that only the handler was triggered only once for the first call. This can be an issue when you call a role with parameters where one of the parameters is used in the notifier (such as a service configuration file location, and a restart handler)_

```
TASK: [test | shell echo "test - first call to test"] ************************* 
changed: [localhost]

TASK: [test | shell echo "test - second call to test"] ************************ 
changed: [localhost]

NOTIFIED: [test | test handler] *********************************************** 
ok: [localhost] => {
    "item": "", 
    "msg": "handler first call to test"
}

```

Changing test/tasks/main.yml to flush its handlers seems to have issues in both versions:

test/tasks/main.yml:

```
- shell: echo "test - {{ test_param }}"
  notify: test handler

- meta: flush_handlers
```
### ansible 1.3:

_Note that both handlers for both parameters are flushing twice._

```
TASK: [shell echo "test - first call to test"] ******************************** 
changed: [localhost]

NOTIFIED: [test handler] ****************************************************** 
ok: [localhost] => {"item": "", "msg": "handler first call to test"}

NOTIFIED: [test handler] ****************************************************** 
ok: [localhost] => {"item": "", "msg": "handler second call to test"}

TASK: [shell echo "test - second call to test"] ******************************* 
changed: [localhost]

NOTIFIED: [test handler] ****************************************************** 
ok: [localhost] => {"item": "", "msg": "handler first call to test"}

NOTIFIED: [test handler] ****************************************************** 
ok: [localhost] => {"item": "", "msg": "handler second call to test"}
```
### ansible 1.4 (devel f347133d85) output:

_In this case when the second call to test.yml flushes its handler it uses the first definition of `{{ test_param }}`, not the second._

```
TASK: [test | shell echo "test - first call to test"] ************************* 
changed: [localhost]

NOTIFIED: [test | test handler] *********************************************** 
ok: [localhost] => {
    "item": "", 
    "msg": "handler first call to test"
}

TASK: [test | shell echo "test - second call to test"] ************************ 
changed: [localhost]

NOTIFIED: [test | test handler] *********************************************** 
ok: [localhost] => {
    "item": "", 
    "msg": "handler first call to test"
}
```

**Comment by mpdehaan** [comment]
I think we're looking at fragments of a reproduction example here, so I'm having trouble understanding all of it.

Can you link to a repo that shows an example of this together?

Thanks!

**Comment by jarv** [comment]
It's a simple example and only the files in the description are needed to reproduce.
Also uploaded here - https://github.com/jarv/ansible-notify-test

**Comment by jsmartin** [comment]
I'm hitting the same or related issue.  TL;DR, 2 roles with the same handler named assigned to host, only 1 handler will be executed. Here's my reproducer:

https://github.com/jsmartin/test-ansible.git

```
ansible-playbook --version
ansible-playbook 1.4 (devel 6dd81f25d9) last updated 2013/11/12 18:50:22 (GMT -400)


PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [a | test role a echo] ************************************************** 
changed: [127.0.0.1] => {"changed": true, "cmd": ["echo", "role a"], "delta": "0:00:00.004943", "end": "2013-11-12 18:55:26.645837", "item": "", "rc": 0, "start": "2013-11-12 18:55:26.640894", "stderr": "", "stdout": "role a"}

TASK: [b | test role b echo] ************************************************** 
changed: [127.0.0.1] => {"changed": true, "cmd": ["echo", "role b"], "delta": "0:00:00.003273", "end": "2013-11-12 18:55:26.747306", "item": "", "rc": 0, "start": "2013-11-12 18:55:26.744033", "stderr": "", "stdout": "role b"}

NOTIFIED: [a | myhandler] ***************************************************** 
changed: [127.0.0.1] => {"changed": true, "cmd": ["echo", "handler for role A activated"], "delta": "0:00:00.003456", "end": "2013-11-12 18:55:26.849426", "item": "", "rc": 0, "start": "2013-11-12 18:55:26.845970", "stderr": "", "stdout": "handler for role A activated"}

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=4    changed=3    unreachable=0    failed=0  
```

Here you can see only the handler in role "a" was activated

Now let's try with 1.3.4

```
ansible-playbook --version
ansible-playbook 1.3.4
ansible-playbook -i hosts -v test.yml 

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [test role a echo] ****************************************************** 
changed: [127.0.0.1] => {"changed": true, "cmd": ["echo", "role a"], "delta": "0:00:00.005104", "end": "2013-11-12 18:57:33.596077", "item": "", "rc": 0, "start": "2013-11-12 18:57:33.590973", "stderr": "", "stdout": "role a"}

TASK: [test role b echo] ****************************************************** 
changed: [127.0.0.1] => {"changed": true, "cmd": ["echo", "role b"], "delta": "0:00:00.004365", "end": "2013-11-12 18:57:33.704722", "item": "", "rc": 0, "start": "2013-11-12 18:57:33.700357", "stderr": "", "stdout": "role b"}

NOTIFIED: [myhandler] ********************************************************* 
changed: [127.0.0.1] => {"changed": true, "cmd": ["echo", "handler for role A activated"], "delta": "0:00:00.004131", "end": "2013-11-12 18:57:33.805843", "item": "", "rc": 0, "start": "2013-11-12 18:57:33.801712", "stderr": "", "stdout": "handler for role A activated"}

NOTIFIED: [myhandler] ********************************************************* 
changed: [127.0.0.1] => {"changed": true, "cmd": ["echo", "handler for role B activated"], "delta": "0:00:00.004174", "end": "2013-11-12 18:57:33.910559", "item": "", "rc": 0, "start": "2013-11-12 18:57:33.906385", "stderr": "", "stdout": "handler for role B activated"}

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=5    changed=4    unreachable=0    failed=0   
```

Here you can see both handlers were activated.

**Comment by jctanner** [comment]
@jsmartin @jarv if you can, test if reverting f51b8ffde9e883a84ac63af000c1442469387a84 resolves this for you. Otherwise, we need to do a bisect and figure out where this changed.

**Comment by jsmartin** [comment]
I went ahead and bisected.. the problem commit is here: f081c68a656488e79255eb6865b930cf56c791a9

**Comment by jctanner** [comment]
@jsmartin your issue is actually different. Can you please open a new bug? This patch potentially resolves your issue ...

```
index 36788f2..7c1eb68 100644
--- a/lib/ansible/playbook/__init__.py
+++ b/lib/ansible/playbook/__init__.py
@@ -547,6 +547,11 @@ class PlayBook(object):

                                 # Resolve the variables first
                                 handler_name = template(play.basedir, handler.name, handler.module_vars)
+
+                                if hasattr(handler, 'role_name'):
+                                    if handler.role_name is not None:
+                                        handler_name = str(handler.role_name) + '-' + handler_name
+                              
                                 if handler_name not in fired_names:
                                     self._run_task(play, handler, True)
                                 # prevent duplicate handler includes from running more than once
```

**Comment by jctanner** [comment]
@jarv per https://github.com/ansible/ansible/issues/3863 you are seeing the expected behavior. If the role name and the handler name are the same, then we really only want to call the handler once. This behavior reduces/optimizes the number of calls to do things like restarting a service during the entire play.

**Comment by jarv** [comment]
>  If the role name and the handler name are the same, then we really only want to call the handler once.

In the example I gave the role name is "test", the handler name is "test handler".  

The issue is that I am calling the role twice so of course the handler name for the two calls will be the same (afaik there is no way for it not to be the same)

On the two calls what handler **does** is different so in that case you want to call it twice. 

If it isn't called twice it will be pretty confusing for someone who is trying to use a role that takes parameters that affect what the handlers do which doesn't seem like an unusual use-case.

**Comment by jimi-c** [comment]
Ansible in 1.4 now supports using variables in the handler name, so to trigger the same handler do the following:

<pre>
- name: "test handler {{ test_param }}"
  debug: msg="handler {{ test_param }}"
</pre>

If you continue having problems with this, let us know. Thanks!

**Comment by jarv** [comment]
ah great, that does make it possible then to have different configuration files for the same handler in a parameterized role.

**Comment by axelson** [comment]
@jimi-c can you point to the documentation for using variables in the handler name? I'm completely unable to find it anywhere.

**Comment by mbukatov** [comment]
@jimi-c I tried it with Ansible 1.8 and it doesn't seem to work. Moreover there
is no documentation  of this feature (as @axelson pointed out) which makes me
think that this feature was not actually included.
