### ISSUE TITLE
Accelerated mode via ssh

### ISSUE THREAD

**Issue by vliw** [ansible/ansible#4863]
i wonder if its possible to connect the accelerate daemons via ssh stdin/stdout instead of using an extra channel? i dont know if i get it, but it should be possible at least via ssh control master and a dedicated channel? this would be great for people with firewall restrictions.

**Comment by jimi-c** [comment]
Unfortunately, no, this is not how accelerated mode works. It is possible to set the port accelerate uses (in ansible.cfg), so you can move it to a port that is more accessible.
