### ISSUE TITLE
deprecation warning issue (?)

### ISSUE THREAD

**Issue by podollb** [ansible/ansible#4873]
The "DEPRECATION WARNING" is displayed when the file being used by the "copy" module contains a "$".

It should not scan the contents of the files in the "files/" directory since those do not even use variable substitution.

NOTE: Here's the deprecation warning for reference (also note there is a typo, the word substitution is mis-spelled).

"[DEPRECATION WARNING]: Legacy variable subsitution, such as using ${foo} or
$foo instead of {{ foo }} is currently valid but will be phased out and has
been out of favor since version 1.2. This is the last of legacy features on our
deprecation list. You may continue to use this if you have specific needs for
now. This feature will be removed in version 1.6. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg."

**Comment by mpdehaan** [comment]
Please provide the playbook that you are referencing here so we can see what you are talking about.

Thanks!

**Comment by mpdehaan** [comment]
am I interpreting this like:

```
src=file$x.txt ?
```

If so I think I understand and we could test that the template didn't change anything once evaluated.  (Though I think this is what we did...)

**Comment by podollb** [comment]
Actually, the situation was where I was just copying a file with a regular filename, such as "src=file.txt", but that file contained (within the file) a "$".

But before we investigate this any further, I may retract this issue (it seems that the DEPRECATION WARNING isn't displayed at the time of the occurrence and can be displayed at anytime during the output (at least that is what it seems is going on)?

If so, it just so happened to show up when I was copying a file that was a large ssh key (which included "$"), and when I re-ran it I had the same error occur in the same spot (so I assumed what the issue was). But subsequent runs haven't shown the error in the same spot (and I found another variable reference that was causing it I believe).

**Comment by podollb** [comment]
- name: overwrite the xxx users temporary public ssh key
  
  copy: src=ssh_keys/xxx.pub dest=/home/xxx/.ssh/id_rsa.pub owner=xxx group=xxx mode=0644

**Comment by podollb** [comment]
TASK: [../roles/common | overwrite the xxx users temporary public ssh key] ***
chang [DEPRECATION WARNING]: Legacy variable subsitution, such as using ${foo} or
$foo instead of {{ foo }} is currently valid but will be phased out and has
been out of favor since version 1.2. This is the last of legacy features on our
deprecation list. You may continue to use this if you have specific needs for
now. This feature will be removed in version 1.6. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.

**Comment by podollb** [comment]
I don't see a "$" in the contents but I still get the deprecation warning...

Here is xxx.pub

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSZIaOdq1KIFAsbwqusDNBbpo4Ji4F8AR1HiHy0Fws2LZe5K8rs6mmulsQt5SDsDb9A9WpfbF0vLMVwMluS7+oZlkBpyLB+k9C6frbKvPMzfE5vpgbzwiNXRWBR6wXzXUE3SvbaRF/VV9Iqx2aKgBMi7SZg3+Viq/yxtFBUSNsVF+Phn6jwj2WRoYnQfPtXSSirgErxGt4lcGg/SrHxiEgjXTt67wKel/3VUFXxPxT5qdVGbp160NkxJiS3x7qHjkSrh7eOFi2P0n/x1tiSft3hMWaaoCkzRtmttwe6t5xmgqvhu52xYI9Ogu1ThXSJNAiPaESzOae1Z98GfojcU0z

**Comment by jctanner** [comment]
@podollb please provide a simplistic playbook that reproduces the issue.

**Comment by podollb** [comment]
The problem ended up being due to the fact that message was being written to stderr, and showing up (for whatever reason) at the same (weird spot) in the stdout, which threw me off. I was running ansible in vagrant (via a shell provisioner), so the ansible output (stdout/stderr) is not continuous. So, I found what was causing the issue (and it was a $ variable substitution issue in a snippet of bash script).

**Comment by jctanner** [comment]
@podollb thanks for the update
