### ISSUE TITLE
Linode Inventory path issue

### ISSUE THREAD

**Issue by mgan59** [ansible/ansible#4875]
In the process of learning how to use ansible with my linode I had pip installed all the necessary libraries.  Then I had cloned the ansible repository to have access to the inventory scripts in my local documents folder.  When I cloned the main repo I named it `ansible-src/` just so I'd remember that it was a clone from a read only repo.

```
python ansible-src/plugins/inventory/linode.py
```

``` bash
    Traceback (most recent call last):
      File "plugins/inventory/linode.py", line 87, in <module>
        from chube import *
      File "/usr/local/lib/python2.7/site-packages/chube/__init__.py", line 4, in <module>
        from .api import api_handler as chube_api_handler
      File "/usr/local/lib/python2.7/site-packages/chube/api.py", line 1, in <module>
        from linode import api as linode_api
      File "/Users/morgan.craft/Documents/projects/ansible-src/plugins/inventory/linode.py", line 89, in <module>
        load_chube_config()
    NameError: name 'load_chube_config' is not defined
```

Took me abit to sort through what was going on, at first I thought pip had exploded on me and trashed my environment. But then I found this section of code in `plugins/inventory/linode.py`

``` python
# chube imports 'yaml', which is also the name of an inventory plugin,
# so we remove the plugins dir from sys.path before importing it.
old_path = sys.path
sys.path = [d for d in sys.path if "ansible/plugins" not in d]
```

Turns out `yaml` isn't all it blocks, but the linode.py file as well from the sys.path inclusion which causes a weird circular import.  This is because of 

``` python
sys.path = [d for d in sys.path if "ansible/plugins" not in d]
```

I don't think we should have a hard coded file/directory path name.  Or if it is the only way then maybe we should propogate an exception if `ansible` is not the cloned repo name so at least devs know their file-pathing doesn't match.  

Happy to work on the issue and submit a pr, just want feedback on how best to approach.

**Comment by jctanner** [comment]
@mgan59  Does this same behavior occur if you copy the inventory script to a 
directory outside the checkout?

**Comment by mgan59** [comment]
confirmed same error

``` bash

cp projects/ansible/plugins/inventory/linode.py ~/
python ~/linode.py

Traceback (most recent call last):
  File "linode.py", line 87, in <module>
    from chube import *
  File "/usr/local/lib/python2.7/site-packages/chube/__init__.py", line 5, in <module>
    from .api import api_handler as chube_api_handler
  File "/usr/local/lib/python2.7/site-packages/chube/api.py", line 1, in <module>
    from linode import api as linode_api
  File "/Users/morgan.craft/linode.py", line 89, in <module>
    load_chube_config()
NameError: name 'load_chube_config' is not defined
```

**Comment by mahemoff** [comment]
+1 same issue here

**Comment by mahemoff** [comment]
I just hit the same issue in a standalone (not Ansible) script. It worked fine, then occurred just after I renamed my script to `linode.py` (and even after I renamed it, the remnant `linode.pyc` still caused the problem). It's a naming conflict with the `linode` library that `chube` builds on.

The solution seems to be renaming ansible's linode module. Or something else involving namespaces, but I don't have enough py-fu to know the best course of action.

**Comment by jimi-c** [comment]
So the issue here is the fact that \* is being imported from chube. That is the source of the namespace collisions, so if we simply removed that and only imported the items we need from that library we wouldn't need to muck around with the sys.paty.

**Comment by jimi-c** [comment]
This is a preliminary patch to correct the issue:

<pre>
diff --git a/plugins/inventory/linode.py b/plugins/inventory/linode.py
index b4bcb1f..fb468f2 100755
--- a/plugins/inventory/linode.py
+++ b/plugins/inventory/linode.py
@@ -80,12 +80,8 @@ try:
 except ImportError:
     import simplejson as json
 
-# chube imports 'yaml', which is also the name of an inventory plugin,
-# so we remove the plugins dir from sys.path before importing it.
-old_path = sys.path
-sys.path = [d for d in sys.path if "ansible/plugins" not in d]
-from chube import *
-sys.path = old_path
+from chube import load_chube_config, Linode, Datacenter
+
 load_chube_config()
 
 # Imports for ansible
</pre>

Could someone with a linode account give this a try?

**Comment by mgan59** [comment]
I have a linode account still, if I have time this evening I'll give it a try.

**Comment by mpdehaan** [comment]
cc @jimi-c can you take care of this applyhing this one?

**Comment by mgan59** [comment]
Sorry the delay, I went to test this and figured I would start with a fresh clone of the ansible repo to first duplicate my initial error.  Of course I didn't get an error and instead everything worked with a json dump of my linode account.  So I was unable to duplicate my initial error which I opened 4 months ago.

Regardless I went ahead and put your patch into place and this is the error I received when I ran `./linode.py`

``` bash
Traceback (most recent call last):
  File "./linode.py", line 85, in <module>
    from chube import load_chube_config, Linode, Datacenter
  File "/usr/local/lib/python2.7/site-packages/chube/__init__.py", line 5, in <module>
    from .api import api_handler as chube_api_handler
  File "/usr/local/lib/python2.7/site-packages/chube/api.py", line 1, in <module>
    from linode import api as linode_api
  File "/Users/morgan.craft/Documents/projects/test-ansible/plugins/inventory/linode.py", line 85, in <module>
    from chube import load_chube_config, Linode, Datacenter
ImportError: cannot import name load_chube_config
```

Not sure what else to say at the moment....  maybe I'll try my other machine and see if I can even duplicate the original error.

**Comment by jimi-c** [comment]
Hrm, ok, I saw this error too but when I ran the lines through the python interpreter directly it didn't error, so I had assumed it was something odd with my machine. I'll look back into this to see what the issue might be.

**Comment by jimi-c** [comment]
@mgan59 I've updated my feature branch above with a fix that gets me around that traceback. As far as I can tell, the chube `__init__.py` does stuff like `import .api ...` that doesn't play well with us changing the PYTHONPATH when using something like the `hacking/env-setup` script, so I think I've found a middle ground where we still have to do some of the odd sys.path munging, but with more selective imports from chube I believe it will get you around the original issue regarding yaml.

Let me know if this fixes your issue, and sorry it took me a while to get back around to this!

**Comment by jimi-c** [comment]
Just did another update, as I noticed it did not like being run when you were sitting in the same directory as linode.py (since internally, chube does an `from linode import ...` that causes a problem).

I did get an API key to test, and this seems to be working without issue now no matter what the relative path may be, so I'm going to go ahead and merge this in.

**Comment by jimi-c** [comment]
Please let us know if you continue to experience this problem. Thanks!

**Comment by mgan59** [comment]
pulled your `issue_4875_linode_inventory` branch and it works.  Thanks!
