### ISSUE TITLE
"ignore_errors: yes" not working in case of mysql_db import failed task (?)

### ISSUE THREAD

**Issue by nicolas-g** [ansible/ansible#4878]
As discussed in [Google Groups](https://groups.google.com/forum/#!topic/ansible-project/9s8ARNfKQyU)

I have a task that imports a db file into mysql but it fails the second time I re-run the playbook.

In order to overcome the failure I need to login to the mysql server and drop the database in order to import successfully in the second play, this is not possible in a production environment and doesn't make my code idempotent. Using the ignore_errors I still get the same problem causing Ansible to stop the execution on the next play and exit .
### Task :

```
    - name: import DB
      mysql_db: login_host={{ DB_ADDRESS }} login_user={{ DB_MASTER_USERNAME }} login_password={{ DB_MASTER_PASSWORD }} name=mmdb state=import target=roles/mmdb/templates/mmdb-init-tables.sql.j2
      ignore_errors: yes
```
### Error message

```
failed: [localhost] => {"failed": true}
msg: ERROR 1062 (23000) at line 4: Duplicate entry 'CM' for key 'PRIMARY'
```
### Ansible version

```
ansible 1.4 (devel 6008ea40ee) last updated 2013/11/12 12:34:58 (GMT +000)
```

In other tasks the "ignore_errors: yes" works just fine but that doesn't seem to be the case for an import failure using the mysql_db module.

**Comment by jctanner** [comment]
@nicolas-g can we see the -vvvv output for that failing task?

**Comment by jctanner** [comment]
@nicolas-g I dont' have the mysql knowledge to create the error you see, but I was able to force the task to fail and then to also ignore the failure ...

```
    # restore the schema
    - name: import test database
      mysql_db:   login_host={{ DB_DNS }}
                  login_user={{ DB_USER }}
                  login_password={{ DB_USER_PASSWORD }}
                  name=test
                  state=import
                  target=/tmp/testdump1.sql
      failed_when: True
      ignore_errors: True
```

The -vvvv output might help me understand your issue better.

**Comment by mpdehaan** [comment]
This should be equivalent to:

```
- fail: msg=failed
  ignore_errors: True
```

More information would be appreciated.

Thanks!

**Comment by nicolas-g** [comment]
Hi @mpdehaan / @jctanner ,

Forgot to mention this happens in ansible-pull mode , there is no "-v" option available.

It's still happening on ansible 1.4 (devel 0ce1123693) last updated 2013/11/18 15:01:07 (GMT +000) .

Regards,
Nicolas.

**Comment by mpdehaan** [comment]
Still not sure why ignore_errors has any knowledge at all about pull mode or this task in particular.

In queue in case anyone has cycles, but actively attacking some other things ATM.

**Comment by nicolas-g** [comment]
Thanks for the update.

**Comment by mpdehaan** [comment]
(closing this as we know ignore_errors is a generic thing)
