### ISSUE TITLE
creating zpool using zfs module

### ISSUE THREAD

**Issue by ddimmich** [ansible/ansible#4880]
The documentation doesn't really clarify how to add devices to a zpool/create a zpool using the zfs module - is this because the zfs module cannot do this and a separate zpool module needs to be written?

**Comment by ddimmich** [comment]
fyi - i created a stackoverflow question to go with this: http://stackoverflow.com/questions/19938439/how-do-i-create-a-zfs-filesystem-zpool-using-ansible-using-zfs-linux

**Comment by bcoca** [comment]
IIRC the zfs module only manages the file system not the pools themselves.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by bcoca** [comment]
you can use the shell or command module to run the zpool cli (idea for
module contribution!)

**Comment by ddimmich** [comment]
Thought that might be the case. Would it be ansible convention to create a new module for zpool or extend the zfs module and keep all the functionality in that?

**Comment by jctanner** [comment]
@ddimmich a new module would be preferable so that we can maintain ease of use on the existing module by not adding a bunch of new options that only make sense in certain operational modes.

**Comment by mpdehaan** [comment]
Hi,

We're tracking all of this incoming requests, but are not seeing any traction on this ticket so we're going to close it out -- pull requests would be very welcome!

**Comment by stanhiller** [comment]
I've submitted a pull request for a working zpool module. https://github.com/ansible/ansible/pull/8205
