### ISSUE TITLE
single vars_files list item does not interpolate multiple {{ }} variables

### ISSUE THREAD

**Issue by ilgarm** [ansible/ansible#4883]
Hi, I am using latest devel branch.

Use case: I need to create several vms using ansible, each vm has the same set of variables defined in var files, file per vm per host, like: vm1-hostname1.yml, vm1-hostname2.yml

Problem: when vars_files list item contains more than one variable specified as {{ var_name }}, none of the varialbes are interpolated, when it has only one variable with {{ }}, it works fine. When it has mix of one {{ var1_name }} and ${var2_name} that works as well, but I would prefer not to mix these two ways of variable usage.

Failing example:

```
vars_files:
    - [ 'vars/{{ vm_name }}-{{ inventory_hostname }}.yml' ]
```

results in:

```
localhost: not importing file: .../vars/{{vm_name}}-{{inventory_hostname}}.yml
ERROR: localhost: FATAL, no files matched for vars_files import sequence: [u'.../vars/{{vm_name}}-{{inventory_hostname}}.yml']
```

Working example:

```
vars_files:
    - [ 'vars/{{ vm_name }}-${inventory_hostname}.yml' ]
```

results in:

```
localhost: importing .../vars/db-localhost.yml
```

Playbook create_vm.yml:

```

---
- hosts: localhost
  vars_files:
    - [ 'vars/xen-config/{{ vm_name }}-${inventory_hostname}.yml' ]
  tasks:
  - name: print
    debug: msg='{{ vm_ip }}'
```

vars/db-localhost.yml:

```

---
vm_ip: '192.168.11.121'
```

command line:

```
ansible-playbook -v -i development create_vm.yml --limit localhost --extra-vars 'vm_name=db'
```

**Comment by rektide** [comment]
Needs to be fixed but 'vars/{{ vm_name+"-"+inventory }}.yml' will workaround

Definitely looking forward to whatever can be done to make more places jinja2 can be stuffed. With_fileglobs for example would be a great addition. This is just one more place where it needs to get done, & needs to get done well, no?

**Comment by ilgarm** [comment]
probably not such a high priority, but in order to make it consistent with other places where such syntax can be used. thanks for looking into it and for the hint!

**Comment by mpdehaan** [comment]
I'm skeptical about this, but it's in queue for reproduction.

I think it's more of an issue here that one variable is coming from global scope and another from inventory scope.

We'll see if we can reproduce this.

**Comment by tflink** [comment]
I believe that I'm hitting the same issue or at least a similar one. The vars_files declaration that I'm using is:

```
vars_files:
  - ../../common/vars/global.yml
  - ['{{ private }}/{{ deployment_type }}.yml']
```

When I run the playbook with this vars_files, I get (fake values of my.hostname and /path/to/playbook):

```
ok: [my.hostname]
my.hostname: not importing file: /path/to/playbook/{{private}}/{{deployment_type}}.yml
ERROR: my.hostname: FATAL, no files matched for vars_files import sequence: [u'/path/to/playbook/{{private}}/{{deployment_type}}.yml']
```

If I hard-code either variable so that only one is being used, the correct var_file is loaded. {{ private }} is defined in the ../../common/vars/global.yml file and {{ deployment_type }} is defined in a host_vars file.

As an interesting side note, if I write the vars_files section like:

```
vars_files:
  - ../../common/vars/global.yml
  - '{{ private }}/{{ deployment_type }}.yml'
```

There are no error messages until one of the variables defined in '{{ private }}/{{ deployment_type }}.yml' is accessed and I get errors about undefined variables.

I'm using ansible 1.4.3 on Fedora 20 installed from the Fedora repos (ansible-1.4.3-1.fc20).

**Comment by carsongee** [comment]
I just wanted to add a plus one to this. I'm running with 1.5 and seeing the same behavior.

**Comment by dopry** [comment]
I experienced a similar error in a handler. Using ansible 1.4.5

service: name={{nodejs_env}}_{{nodejs_name}} state=started

would generate an error the first time I ran a playbook for a project.

NOTIFIED: [nodejs | restart nodejs] *************************
failed: [127.0.0.1] => {"failed": true, "item": ""}
msg: service not found: {{nodejs_env}}_{{{nodejs_name}}

running the playbook again would not recreate the error.

I updated the name declaration to:

service: name={{nodejs_env +"_"+ nodejs_name}} state=started

and the issue stopped happening.

I can provide a the Vagrant file and ansible repo out of band if you need a test case.

**Comment by jctanner** [comment]
Based on my understanding of the issue, it seems to not be a problem as of 1.6 ..

```
$ cat site.yml
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/{{ a }}-{{ b }}.yml
  tasks:
    - debug: var=foobar
    - name: check if foobar equals loaded
      assert:
        that:
            - "foobar == 'loaded'"

$ cat vars/foo-bar.yml
foobar: loaded

$ ansible-playbook -i inventory site.yml -e "a=foo" -e "b=bar"

PLAY [localhost] **************************************************************

TASK: [debug var=foobar] ******************************************************
ok: [localhost] => {
    "foobar": "loaded"
}

TASK: [check if foobar equals loaded] *****************************************
ok: [localhost]

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

Tried other forms and all passed:

```
    - vars/{{ a }}-{{ b }}.yml
    - 'vars/{{ a }}-{{ b }}.yml'
    - [ 'vars/{{ a }}-{{ b }}.yml' ]
```

EDIT:

If I swap out the second var with inventory_hostname, the vars file is not loaded...

```
$ ansible-playbook -i inventory site.yml -e "a=foo"

PLAY [localhost] **************************************************************

TASK: [debug var=inventory_hostname] ******************************************
ok: [localhost] => {
    "inventory_hostname": "localhost"
}

TASK: [debug var=foobar] ******************************************************
ok: [localhost] => {
    "foobar": "{{ foobar }}"
}

TASK: [check if foobar equals loaded] *****************************************
fatal: [localhost] => error while evaluating conditional: foobar == 'loaded'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/jtanner/site.retry

localhost                  : ok=2    changed=0    unreachable=1    failed=0
```

However, there is no FATAL error for a missing filename.

**Comment by jctanner** [comment]
@tflink @carsongee @dopry 

How are the vars that need to be templated to create the filename being set in each of your cases?
- extra vars on the cli ?
- vars defined in playbook ?
- vars defined in another vars file ?

Are you mixing a standard var with a special var like "inventory_hostname" ?

**Comment by carsongee** [comment]
I'm using a var from group_vars/all and a passed in var.  Looks something like:

``` yaml
- name: Configure apps instance(s)
  hosts: apps:&{{ env }}
  sudo: True
  vars_files: 
    - {{ secure_dir }}/vars/{{ env }}/app.yml
  roles:
    - app
```

Where it gets called with

``` shell
ansible-playbook app.yml -e env=prod
```

and secure_dir is in group_vars/all

**Comment by dopry** [comment]
In my case the variable is set in group_vars/all
