### ISSUE TITLE
problem with conditional include handler trigger (needs info) in 1.3.X

### ISSUE THREAD

**Issue by timlo** [ansible/ansible#4885]
Related to the issue: https://github.com/ansible/ansible/issues/3539
Experiencing this on Ansible 1.3.3

Example:

main.yml:

```
- include: extra.yml
  when: do_extra is defined
```

extra.yml:

```
- name: check if we can do task A
  template: src=something.sh.j2 dest=something.sh
  notify: restart apache
```

If you run main.yml and 'do_extra' is not defined, the task will report appropriately as being skipped, however the notification to restart apache will still occur.

**Comment by mpdehaan** [comment]
Please include a link playbook that reproduces this, CLI invocation (with parameters) and output of the playbook run.

Thanks!

(I suspect this won't occur on 1.4 regardless, seeing this releases very soon -- next week -- we are unlikely to do a 1.3.X update)

**Comment by mpdehaan** [comment]
Closing due to lack of feedback.
