### ISSUE TITLE
want to be able to use a variable for the value of ignore_errors

### ISSUE THREAD

**Issue by marcusphi** [ansible/ansible#4892]
AFAICT it's impossible to use a **variable** for _ignore_errors_ 
### Given

```
vars:
    ignore_err: no
```
### Solution Attempts

Interpreted as a string, so always true:

```
ignore_errors: $ignore_err
```

Dito:

```
ignore_errors: {{ ignore_err }}
```

Illegal YAML syntax:

```
ignore_errors: {{ ignore_err | bool }}
```

String again...:

```
ignore_errors: "{{ ignore_err | bool }}"
```

Maybe I'm stupid, but I can't see how to do this. I had to duplicate the task with one ignore_errors: yes and one no and control it with a when...

**Comment by mpdehaan** [comment]
This is probably just because this variable is not being templated, which is a pretty easy thing to add.
