### ISSUE TITLE
roles_path should allow user environment variables

### ISSUE THREAD

**Issue by josh-at-knoesis** [ansible/ansible#4897]
I tried: 

roles_path     = $HOME/Roles

but received, for example:

ERROR: cannot find role in /home/doej/posix/code/gitlab.com/acme-devops/ansible/roles/external_roles/common/group-by or /home/doej/posix/code/gitlab.com/acme-devops/ansible/external_roles/common/group-by or /home/doej/posix/code/gitlab.com/acme-devops/ansible/$HOME/Roles/external_roles/common/group-by

I definitely have a role (with known good tasks dir) in '''$HOME/Roles/external_roles/common/group-by''', but there seems to be a bug because it's prefacing my "roles_path" with the current playbook working dir.

Please let me know if I can help in any way.  Perhaps, environment variables are not intended for use in this fashion.

Thanks,
Joshua

**Comment by jctanner** [comment]
@josh-at-knoesis please indicate which version of ansible you are using.

**Comment by josh-wrale** [comment]
@jctanner 

Sorry about that.  I am running the master branch, which I cloned to the machine about three hours ago.  v1.4

**Comment by nijotz** [comment]
@josh-at-knoesis

roles_path isn't shell expanded

```
103 DEFAULT_ROLES_PATH        = get_config(p, DEFAULTS, 'roles_path',       'ANSIBLE_ROLES_PATH',       None)
104 DEFAULT_REMOTE_TMP        = shell_expand_path(get_config(p, DEFAULTS, 'remote_tmp',       'ANSIBLE_REMOTE_TEMP',      '$HOME/.ansible/tmp'))
```

My work around has been to set ANSIBLE_ROLES_PATH

**Comment by chrishoffman** [comment]
+1.  This is inconsistent in the ansible.cfg file.

**Comment by mpdehaan** [comment]
Reclassifying this as a bug report -- seems like an easy fix should someone wish to send a pull request :)
