### ISSUE TITLE
Implement delete option for recursive copy

### ISSUE THREAD

**Issue by esamattis** [ansible/ansible#4899]
As recursive copy was merged in #4375 it would be nice if it implemented a delete option which would work like `--delete` in rsync: If a file is deleted from the source folder it will be deleted from the target also.
### Use case

I want to manage my nginx configurations and often I need to remove some configuration files from `/etc/nginx/{sites-available,sites-enabled}` because just a existence of a file there has effects on nginx.

**Comment by mpdehaan** [comment]
The synchronize module would be good to use in this case again, I don't see this being implemented for the copy module.

**Comment by esamattis** [comment]
Only issue with synchronize ansible is not able to detect actual changes with it. Instead Ansible always reports synchronize tasks as changed.
