### ISSUE TITLE
formatting issues with raw module output

### ISSUE THREAD

**Issue by jonten** [ansible/ansible#490]
A fix for removing the literal newlines we talked about on the mailinglist (http://groups.google.com/group/ansible-project/browse_thread/thread/220133ac44b8f1e0) is needed. The fix is to replace stdout=stdout with stdout=stdout.replace("\r\n","\n").split("\n")

Cheers,
//Jon

**Comment by mpdehaan** [comment]
It turned out that it was the print function that needed fixing, which I've done so here

https://github.com/ansible/ansible/commit/5f1c7c8e24ae1fe205b4486f9ba45f1817590d57

So this will be fixed in 0.5, thanks!
