### ISSUE TITLE
delegate_to doesn't delegate when using "-c local"

### ISSUE THREAD

**Issue by XavM** [ansible/ansible#4905]
delegate_to doesn't delegate when using "-c local" but plays the task localy

Playbook Example : 

vi ./test.yml 

```
  - hosts: localhost

    tasks:

    - name: test
      shell: hostname
      delegate_to: some_other_host
```

ansible-playbook test.yml -i production/ -v -c local

```
  PLAY [localhost] ************************************************************** 

  GATHERING FACTS *************************************************************** 
  ok: [localhost]

  TASK: [test] ****************************************************************** 
  changed: [localhost] => {"changed": true, "cmd": "hostname ", "delta": "0:00:00.002073", "end": "2013-11-14 18:32:11.276636", "rc": 0, "start": "2013-11-14 18:32:11.274563", "stderr": "", "stdout": "localhost"}

  PLAY RECAP ******************************************************************** 
  localhost                  : ok=2    changed=1    unreachable=0    failed=0   
```

Of course it delegates well when not using local connexion :
ansible-playbook test.yml -i production/ -v 

```
  PLAY [localhost] ************************************************************** 

  GATHERING FACTS *************************************************************** 
  ok: [localhost]

  TASK: [test] ****************************************************************** 
  changed: [localhost] => {"changed": true, "cmd": "hostname ", "delta": "0:00:00.002407", "end": "2013-11-14 18:32:59.133485", "rc": 0, "start": "2013-11-14 18:32:59.131078", "stderr": "", "stdout": "some_other_host"}

  PLAY RECAP ******************************************************************** 
  localhost                  : ok=2    changed=1    unreachable=0    failed=0   
```

**Comment by srgvg** [comment]
I confirm this is the current behaviour, and as I see it, it is the expected behaviour.
-c local forces all connections to local and that's it.
If I'm not mistaken, you can set the connection type per playbook, if you need something more fine grained.

**Comment by XavM** [comment]
Mmm ...

Pretty much sure it can't be the desired behavior : Forcing the connexion to be local is one thing, but overriding the "delegated host" a task is targeted for with localhost is definitely not an expected behavior

I ran into that problem as I was using the standard ansible-pull script, that first clones a git repo and then run the task locally using a combination of --limit "127.0.0.1:hostname" and -c local

This makes the use of delegate_to a terrible nightmare in such case, as it lets you think the play ran fine but instead didn't play the delegated task on the desired host but locally on the node the pull was initiated from

If the play can't be honored because of "-c local", the play should fail

Edit: Of course, being able to use delegate_to AND "-c local" would be even better ;)

**Comment by mpdehaan** [comment]
This is not a bug, -c local overrides the connection type.   The idea of a local delegation for the play wouldn't make sense.

Don't do "-c local", let it use the remote transport.

```
- hosts: foo
```

And then just where you want to do something locally, use "local_action".

**Comment by XavM** [comment]
OK, not a bug, but a warning in the doc about using delegation in conjunction with '-c local' would have been nice
