### ISSUE TITLE
Is the .j2 filename extension necessary for the template module?

### ISSUE THREAD

**Issue by quicksnap** [ansible/ansible#4906]
Nowhere in the docs is it stated whether the j2 filename extension is required for the `template` module. In practice, it works fine without using the extension, which is very helpful for Sublime syntax highlighting. 

Could it be clarified that the filename extension is optional? A future release that requires the filename extension to be present would break a lot of my playbooks.

**Comment by bcoca** [comment]
no, most of us use it so vim uses correct syntax coloring, its just a handy
convention sometimes.

**Comment by mpdehaan** [comment]
(A) no

(B) don't ask questions here, that's what the mailing list and IRC are for.
