### ISSUE TITLE
file compression and uncompression not available

### ISSUE THREAD

**Issue by podollb** [ansible/ansible#4916]
This is more of a question/request about an ansible module to handle compression (and possibly decompression) of files such as zip, gzip, bzip, etc.? I often download a file from a URL that is compressed, and I usually then have a following task using the "command" module to issue my uncompress command. I wonder why there hasn't been the creation of a module to handle this?

**Comment by mpdehaan** [comment]
Ansible questions should be asked to the mailing list, not the bug tracker.
