### ISSUE TITLE
unable to pull ansible-vault

### ISSUE THREAD

**Issue by darKoram** [ansible/ansible#4932]
Hi JP,

I'd like to give your ansible-vault module a whirl.
I've tried several things along the lines of the following, but i can't find a proper branch with ansible-vault in it.

git branch --set-upstream vault https://github.com/jpmens/ansible.git/tree/909a8e518fec431fbe03593d98fb0609ac67ff25

thanks
kesten

**Comment by mpdehaan** [comment]
So this isn't jpmens's repo, this is the main ansible one.

We still want some type of vault-style support in a future release, though we are likely going to want to tweak ideas somewhat.

In any event, this is misfiled, so I'm closing this ticket.
