### ISSUE TITLE
gce.py should be able to read (path to) gce.ini as a parameter

### ISSUE THREAD

**Issue by dch** [ansible/ansible#4954]
`gce.py` uses `os.path.dirname(os.path.realpath(__file__)) + '/gce.ini'` to locate the ini file, viz https://github.com/jsonified/ansible/blob/devel/plugins/inventory/gce.py#L118 

This is at best cryptic, and if run from a relative path fails without useful error message.

A command-line parameter to specify the config file, or at least looking in current working directory for `gce.ini` and subsequently using `libcloud_secrets` to locate the secrets file would be more accessible and intuitive (in line with ansible core).

cc @erjohnso

**Comment by mpdehaan** [comment]
The ec2 plugin does it like this:

```
    ec2_default_ini_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'ec2.ini')
    ec2_ini_path = os.environ.get('EC2_INI_PATH', ec2_default_ini_path)
```

Similarly Rackspace:

```
    creds_file = os.environ['RAX_CREDS_FILE']
```

This would be useful/required if we decide to add Google cloud inventory to AWX as well (as we're already adding for a few other providers initially).

It doesn't need to be a CLI parameter, just an environment variable.

**Comment by erjohnso** [comment]
Ack.  I can get a PR out in the next day or three.

**Comment by mpdehaan** [comment]
excellent, thanks!
