### ISSUE TITLE
Terminal Control Escape Sequences need to be escaped or removed

### ISSUE THREAD

**Issue by ko-zu** [ansible/ansible#4958]
Results contain special chars may break local terminal state.

for example, 

```
ansible all -m shell "clear"
```

will clear local terminal.

atleast control sequences needs to be filtered if stdout is tty.

**Comment by jctanner** [comment]
@ko-zu what is your ansible version?

**Comment by ko-zu** [comment]
ansible (1.3.4)

```
sudo pip install ansible --upgrade
Requirement already up-to-date: ansible in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: paramiko in /usr/local/lib/python2.7/dist-packages (from ansible)
Requirement already up-to-date: jinja2 in /usr/local/lib/python2.7/dist-packages (from ansible)
Requirement already up-to-date: PyYAML in /usr/local/lib/python2.7/dist-packages (from ansible)
Requirement already up-to-date: pycrypto>=2.1,!=2.4 in /usr/local/lib/python2.7/dist-packages (from paramiko->ansible)
Requirement already up-to-date: ecdsa in /usr/local/lib/python2.7/dist-packages (from paramiko->ansible)
Requirement already up-to-date: markupsafe in /usr/local/lib/python2.7/dist-packages (from jinja2->ansible)
```

**Comment by mpdehaan** [comment]
Please include output of the problem you're seeing, I'm failing to understand why someone would do this and why it causes a problem.

in other words, this seems purely theoretical and a non-issue (can you show a more real-world example where something doesn't work that you would expect it to?)

**Comment by alanfairless** [comment]
Historically unfiltered terminal escape sequences have been a source of vulnerabilities, so filtering control characters from output to TTYs is just a recommend practice.  Imagine for example if the Ansible invoked remote shell command displayed output from a log file that contains attacker controlled characters.  

Here's an example vulnerability with a nice small diff (in python) showing the fix: https://bugs.launchpad.net/ubuntu/+source/osc/+bug/1197639  

It's easy to check for the TTY case:

``` #!python
>>> sys.stdout.isatty()
True
```

**Comment by jctanner** [comment]
@alanfairless would you be willing to submit a pull request?

**Comment by rbbratta** [comment]
In case anyone is googling, this seems to prevent parsing register variables containing `find . -print0`  null delimited lists, also `du -0`, `uniq -z`, etc.
