### ISSUE TITLE
action service on FreeBSD: rc.conf parsing error

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#4961]
Ansible errors if your /etc/rc.conf file on FreeBSD has any lines that do not end in a quotation mark. This is bizarre parsing behavior; it is extremely normal for users to have comments in this file.

fatal: [backup1.foo.net] => failed to parse: Traceback (most recent call last):
  File "/home/supraupdate/.ansible/tmp/ansible-1384875495.66-103886466284879/service", line 2080, in <module>
    main()
  File "/home/supraupdate/.ansible/tmp/ansible-1384875495.66-103886466284879/service", line 1092, in main
    service.service_enable()
  File "/home/supraupdate/.ansible/tmp/ansible-1384875495.66-103886466284879/service", line 750, in service_enable
    return self.service_enable_rcconf()
  File "/home/supraupdate/.ansible/tmp/ansible-1384875495.66-103886466284879/service", line 320, in service_enable_rcconf
    rcarray = shlex.split(rcline, comments=True)
  File "/usr/local/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/local/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/local/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/local/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation

**Comment by ghost** [comment]
Might I also add that there are times when you have situations such as many VLAN interfaces and cannot cleanly fit the arguments all on a single line, so you format them to be as readable and editable as possible.

cloned_interfaces="lagg0 \
                        vlan10 vlan994 vlan996 \
                        vlan800 vlan804 vlan805 \
                        vlan807 vlan808 vlan809 \
                        vlan812 \
                        vlan813 vlan815 vlan816 \
                        vlan819 vlan820 vlan822 \
                        vlan826 vlan830 vlan832 vlan834 vlan835 \
                        vlan836 vlan837 vlan838 \
                        vlan841 vlan843 vlan844 vlan848 \
                        vlan850 vlan852 vlan853 \
                        vlan858 vlan997"

**Comment by mpdehaan** [comment]
Can you please paste an example of your rc.conf and the command in Ansible you used to trigger this?

Also please include the output of "ansible --version"

Thanks!

**Comment by ghost** [comment]
# ansible --version

ansible 1.3.4

the command was:
- name: enable nslcd daemon supervisor
  action: service name=nslcd_supervisor enabled=yes

and I cannot post the rc.conf publicly but I could probably send it to
you directly.

**Comment by jctanner** [comment]
@felderado I'm not able to reproduce this on 1.3.4 or with current devel with the following example ...

```
[root@freebsd ~]# cat /etc/rc.conf  | fgrep ntp
ntpd_enable="YES" #comment
```

```
TASK: [service name=ntpd enabled=yes] ***************************************** 
ok: [freebsd.lab.net] => {"changed": false, "enabled": true, "name": "ntpd"}
```

Can you show us the example line in your rc.conf that is causing the error, and also what this command returns?

```
service nslcd_supervisor rcvar
```

**Comment by mpdehaan** [comment]
Closing due to lack of response
