### ISSUE TITLE
Add Rackspace DNS modules

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#4963]
This is just a placeholder so that it's visible that this is being worked on.

Module names:
1. rax_dns - Manage domain
1. rax_dns_record - Manage records within a domain

I'll update this issue as things develop.

**Comment by mpdehaan** [comment]
Appreciate that this is coming.

Perhaps the better way to communicate would be to post this to ansible-devel list

We are trying to keep the number of open tickets manageable

Thanks!
