### ISSUE TITLE
Git module support for file:/// protocol for the repo

### ISSUE THREAD

**Issue by brianmhunt** [ansible/ansible#4964]
It appears that the Ansible git module does not support the `file:///` protocol (per http://git-scm.com/book/ch4-1.html), as running e.g.

```
    tasks:
    - name: Direct deploy
      git
        repo=file:///Users/brianmhunt/package/
        version={{ git_version|default("HEAD") }}
        dest=test_git_deploy
        depth=1
```

results in 

```
msg: fatal: '/Users/brianmhunt/package/' does not appear to be a git repository
fatal: The remote end hung up unexpectedly
```

This would seem to be because the desired behaviour is git pushing to the remote, and the ansible module appears to be attempting to pull.

The ability to git push would allow one to avoid the workaround discussed for [sudoers](https://groups.google.com/forum/#!msg/ansible-project/Tumb7svuGwg/a8eiUdfYoDMJ) i.e. a `git_ssh.j2` file with `exec /usr/bin/ssh -o StrictHostKeyChecking=no -i /home/project_user/deploy.key "$@"%` and adding to the task:

```
      environment:
        GIT_SSH: /home/project_user/git_ssh.sh
```

which has the unfortunate side effect of requiring git keys on the deployment box.

**Comment by jctanner** [comment]
@brianmhunt try quoting your repo path ...

```
repo="file:///tmp/gitdemo"
```

This is how the tests for the git module are run in test/TestRunner.py

**Comment by brianmhunt** [comment]
Thanks @jctanner. Using quotes does not resolve the problem.

As you can see from [test/TestRunner.py](https://github.com/ansible/ansible/blob/devel/test/TestRunner.py#L183), your suggestion works in cases where `dest` is also local. It does not appear to work where `dest` is remote (which case is not tested in TestRunner.py).

The issue stands, I am afraid, but thanks for the suggestion.

**Comment by jctanner** [comment]
@brianmhunt ah, I'll reopen this then.

**Comment by brianmhunt** [comment]
Thanks @jctanner. I hope there is a straightforward fix! :)

**Comment by mpdehaan** [comment]
What do you mean by "dest is local or remote" ?

This module executes on exactly one server so I'm a bit confused here.

Examples of working and failing cases with playbook lines would be useful.

Thanks!

**Comment by brianmhunt** [comment]
Thanks for the attention @mpdehaan - sorry for the confusion as I am figuring out how the git module works. I hope the following helps explain:

The desired behaviour is to git push from a local directory to a repository on the target server.

So the expected behaviour for the following:

```
    tasks:
    - name: Direct deploy
      git
        repo=file:///Users/brianmhunt/package/
        dest=/tmp/destinaction_directory
```

Should be along the lines of `cd /Users/brianmhunt/package; git push ssh://remote_server:/tmp/destination`.

The challenge here seems to be that git would need to be run on the local server. One could work around this with a `local_action` that calls git locally.

Does that help clarify?

**Comment by mpdehaan** [comment]
So the way this works in the example is as follows:

```
- git: repo=git://foosball.example.org/path/to/repo.git
       dest=/srv/checkout
       version=release-0.22
```

And what this does is expected to be executed inside a host loop.
- hosts: webservers
   tasks:
  - git: repo=git://foosball.example.org/path/to/repo.git
          dest=/srv/checkout
       version=release-0.22

Which will on each webserver, do a checkout from foosball.example.com onto that local server in /srv/checkout.

This is what it does.

This does not do a push, it does a clone of a particular branch, and runs that clone from the remote server.

It is designed for deploying operating systems from source control, not for pushing changes to a development repository, hence why it does not use "push".

As this is the bug tracker, I'd suggest further explanation discussions move over to the ansible-project mailing list.

Thanks!
