### ISSUE TITLE
Implement ansible.module_utils.rax

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#4967]
With the addition of a lot of rax modules, there is a lot of duplicate code currently.

Migrate some duplicate boilerplate code that usually shows up in main() into `lib/ansible/module_utils/rax.py`

All rax modules should be updated to use it.

This is just a placeholder so that it's visible that this is being worked on.

I'll update this issue as things develop

**Comment by mpdehaan** [comment]
+1

**Comment by mpdehaan** [comment]
Appreciate that this is coming.

Perhaps the better way to communicate would be to post this to ansible-devel list

We are trying to keep the number of open tickets manageable

Thanks!
