### ISSUE TITLE
Using Google Cloud Repositories as source control

### ISSUE THREAD

**Issue by soeirodefaria** [ansible/ansible#49680]
##### SUMMARY

I'm trying to configure a project type Git in Ansible Tower and use Google Cloud Repository as the source.
I configured the .gitcookies in both the user I use to log into the host as well as root, so the git command works without typing the password. WHen I try via SSH session it works fine. But if I try via Tower I get an authentication failure error

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.7.4
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

Via Tower:

TASK [update project using git] ************************************************
Username for 'https://$encrypted$: Password for 'https://$encrypted$: 
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin https://source.developers.google.com/p/xxxx/r/ansible /var/lib/awx/projects/_6__gcr", "msg": "fatal: Authentication failed for 'https://source.developers.google.com/p/xxx/r/ansible/'", "rc": 128, "stderr": "fatal: Authentication failed for 'https://source.developers.google.com/p/xxx/r/ansible/'\n", "stderr_lines": ["fatal: Authentication failed for 'https://source.developers.google.com/p/rxxx/r/ansible/'"], "stdout": "Cloning into '/var/lib/awx/projects/_6__gcr'...\n", "stdout_lines": ["Cloning into '/var/lib/awx/projects/_6__gcr'..."]}

Via SSH session:

[raphael@ansible-tower ansible]$ sudo git clone --origin origin https://source.developers.google.com/p/xxx/r/ansible /var/lib/awx/projects/_6__gcr
Cloning into '/var/lib/awx/projects/_6__gcr'...
remote: Total 3 (delta 0), reused 3 (delta 0)
Unpacking objects: 100% (3/3), done.

```paste below

```

**Comment by aoyawale** [comment]
this looks like something that should be submitted to tower support.

**Comment by bcoca** [comment]
For Ansible Tower support or questions, please utilize https://access.redhat.com/products/ansible-tower-red-hat

For the OSS version (AWX) https://github.com/ansible/awx

This issue tracker is for the open source Ansible CLI tools project.
