### ISSUE TITLE
include_role ignores tags causing role to be skipped completely

### ISSUE THREAD

**Issue by msoltyspl** [ansible/ansible#49732]
##### SUMMARY

Any attempt to conditionally include a role via include_role: using tags fails.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

include_role:
tags:

##### ANSIBLE VERSION

```
ansible 2.7.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/nozo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.1 (default, Oct 22 2018, 10:41:28) [GCC 8.2.1 20180831]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=3600s
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT
Linux 4.19.4-arch1-1-ARCH #1 SMP PREEMPT Fri Nov 23 09:06:58 UTC 2018 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

Execute: `ansible-playbook -i test.inv -t cond test-role.yml`.

```
test.inv:
localhost ansible_connection=local

test-role.yml:
- hosts: all
  gather_facts: no
  tasks:
    - name: role test
      include_role:
        name: inner
      tags: cond

roles/inner/tasks/main.yml:
- debug:
        msg: "executed"

```

##### EXPECTED BEHAVIOR

Inner role gets executed as per tags specified on the command line.

##### ACTUAL BEHAVIOR

Role gets ignored completely.

**Comment by msoltyspl** [comment]
Now to think about it - are we supposed to use "apply" parameter now, if we want the conditional (by tags) role's tasks to have any effect at all ?

**Comment by sivel** [comment]
`tags` applied to `include_role` only affect the `include_role` itself, and not the tasks within. See https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.5.html#dynamic-includes-and-attribute-inheritance for more information.

As such, if you only tag the `include_role` it will include the role but not execute the tasks within.

To get the functionality you are looking for, you can use something like the following:

```
    - name: role test
      include_role:
        name: inner
        apply:
          tags: cond
      tags: cond
```

Or even:

```
    - name: role test
      include_role:
        name: inner
        apply:
          tags: cond
      tags: always
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by msoltyspl** [comment]
> tags applied to include_role only affect the include_role itself, and not the tasks within. 

That was not my point - I don't care about tags of the role within.

The outermost playbook where tags decide whether something is executed (among those, include_role) is not working.

**Comment by bcoca** [comment]
@msoltyspl the include_role gets executed, the debug task in the role should not (it does not have the 'cond' tag).  This works as expected since the act of including/importing a role is not the same as executing the tasks in the role.

**Comment by jleaders** [comment]
I personally feel that `include_role` _should_ by default apply the tags to the tasks within, and instead of having to do an `apply: tags` one should have to do the inverse: stop the tags from applying. I feel it is non-intuitive that `include_role` executes the tasks within _unless_ it is executed via tag.

It's as if the behavior of `include_role` is dependant on wether or not it was executed via tag-selection or a normal named task
