### ISSUE TITLE
Documentation/code mismatch re: ansible.cfg in the playbook directory

### ISSUE THREAD

**Issue by nijotz** [ansible/ansible#4976]
If I run ansible-playbook from a directory not containing my playbooks:

```
~ $ cd projects
~/projects $ ls
ansible otherthing
~/projects $ ansible-playbook -i ansible/inventories/testenv1 ansible/provision_env.yml
```

then Ansible attempts to load ansible.cfg from `projects/ansible.cfg` not `projects/ansible/ansible.cfg`

I don't have a problem with this, but that's not what the documentation reflects, and I lost some time digging through Ansible code to figure out why my config file wasn't loading.

docsite/rst/intro_configuration.rst

```
    * /etc/ansible/ansible.cfg
    * ~/.ansible.cfg
    * ansible.cfg (in the playbook directory)
```

lib/ansible/constants.py

```
    path1 = os.getcwd() + "/ansible.cfg"
    path2 = os.path.expanduser(os.environ.get('ANSIBLE_CONFIG', "~/.ansible.cfg"))
    path3 = "/etc/ansible/ansible.cfg"
```

**Comment by nijotz** [comment]
This is using the latest devel branch

**Comment by techtonik** [comment]
I actually have problem with this, so I made Ansible load config from playbook's directory - https://github.com/ansible/ansible/pull/5184

**Comment by srgvg** [comment]
This is a bug in the docs, not the other way around.

**Comment by techtonik** [comment]
For some reason I am sure that docs were written upfront, and designer explicitly thought about proper lookup order.  But due to complexity it was not implemented in time. Otherwise I don't know why would anyone provide explicit clarification note that is not just misleading, but completely wrong from the start.

**Comment by mpdehaan** [comment]
Because they're human and they make mistakes :)

The code is correct, there was an error in the docs.  

This error should no longer be in the docs so I'm going to close this ticket.
