### ISSUE TITLE
ec2_tags module won't overwrite existing tags

### ISSUE THREAD

**Issue by devoncrouse** [ansible/ansible#4983]
Looks like if all the tags provided to ec2_tags exist with different values, they aren't updated. So in order to update an existing value, a new tag has to be added...

Ideally, the module would evaluate the tag values and update if different.

**Comment by willthames** [comment]
What version of ansible are you running 

```
ansible --version
```

This behaviour seems to work as expected for me against 1.5. 
If it's not working for you can you share the relevant playbook section and the results of running it under `-vvv`

**Comment by devoncrouse** [comment]
I'm on 1.5, latest from devel.

**Comment by devoncrouse** [comment]
Having trouble reproducing with a very simple example, but ran into it earlier today in a more complex play - let me do a little more testing and figure out what exactly is getting in the way.

**Comment by devoncrouse** [comment]
_Ahem_ latest at the time of opening the issue. Looks like this got fixed by https://github.com/ansible/ansible/commit/33afaebb95832e3bc859da63902dc2d6dc8bc280 a week ago. Closing; thanks :)
