### ISSUE TITLE
mount a sub folder: protocol error?

### ISSUE THREAD

**Issue by YAmikep** [ansible/ansible#4989]
Hi,

From my VM, /projects is a shared folder with my host.
I would like to mount one of its sub folder into the code folder of my VM.
I get this error:
"failed: [10.0.0.102] => {"failed": true}
msg: Error mounting /var/projects/djangotutorial/code/: /sbin/mount.vboxsf: mounting failed with the error: Protocol error"
when I do:

```
  - name: Mount code folder.
    mount: fstype=vboxsf name={{project_root}}/code/ src=/projects/myproject state=mounted
```

However, there is no error and it actually works when I just do "/projects". Why?

```
  - name: Mount code folder.
    mount: fstype=vboxsf name={{project_root}}/code/ src=/projects state=mounted
```

Thank you

**Comment by jctanner** [comment]
@YAmikep Being able to mount it from /projects but not /projects/myproject seems to imply that myproject is not a mountable device.

What happens if you try the mount by hand?

```
- shell: mount /projects/myproject {{project_root}}/code/
```

**Comment by YAmikep** [comment]
Trying the mount by hand gives this error: "mount: /projects/myproject is not a block device"
So I guess it's normal that it does not work.
After looking on the internet, I found the bind option which works:

```
  - name: Mount code folder.
    mount: fstype=vboxsf opts=bind name={{project_root}}/code/ src=/projects/myproject state=mounted
```
