### ISSUE TITLE
Documentation on same host in multiple groups missing

### ISSUE THREAD

**Issue by beberlei** [ansible/ansible#4991]
It seems not to be documented how the behavior is when you want to define the same host in multiple groups.

**Comment by mpdehaan** [comment]
We should probably mention that.

It's just like this:

```
[group1]
hostname

[group2]
hostname
```

**Comment by beberlei** [comment]
@mpdehaan Yes, but things need to be said about variables and overriding. Redefining overrides, last entry wins, Defining once inherits to all the next occurances.

**Comment by mpdehaan** [comment]
Just added this.

As for the latter, that's covered in the precedence section, so I think we are ok.

Thanks!
