### ISSUE TITLE
Add userdata variable to cloud/nova_compute

### ISSUE THREAD

**Issue by butangero** [ansible/ansible#4992]
the novaclient python module has some functionality that isn't expressed in the nova_compute module - specifically I'm looking at the 'userdata' variable.  It would be really useful if it could be added to nova_compute so we could pass configuration scripts to the instance at creation time.

Thanks!

**Comment by mpdehaan** [comment]
I'm closing this ticket as we have the pull request above (linked) to track it.  Thank you!
