### ISSUE TITLE
WinRM 

### ISSUE THREAD

**Issue by sakhamuri4545** [ansible/ansible#49956]
##### SUMMARY

I am trying to setup communication between ansible and windows server, when i try to run the playbook i am getting below error, I have enable port 5985 in windows server and enable liseners on HTTP port, and Authentication i am using is BASIC. 

##### ISSUE TYPE
- Bug Report
WinRM connection Error

##### ANSIBLE VERSION

```
version 2.7.4

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Target OS is windows 2016
##### STEPS TO REPRODUCE

```yaml
My Host file looks like below
[webserver]
sskwin.us.com

[webserver:vars]
ansible_user=windows
ansible_password=PWD
ansible_connection=winrm
ansible_winrm_transport=basic
ansible_winrm_scheme=http
ansible_port=5985
ansible_winrm_server_cert_validation=ignore

And main file is some thing looks like
---
- hosts: webserver
  gather_facts: true
  tasks:
    - name: create a file on windows server
      win_file:
        path: C:/temp/hello
        state: touch
```

##### ACTUAL RESULTS

```Hi,

I am getting following error when i am trying to run a playbook in ansible,

ansible-playbook main.yml -vvvvv

PLAYBOOK: main.yml**********
1.Plays in main.yml

PLAY [webserver]****************

TASK [Gathering Facts]****************
Using module file /usr/lib/python2.7/sitepackages/ansible/modules/windows/setup.ps1
<ssk.com> ESTABLISH WINRM CONNECTION FOR USER: sateesh on PORT 5985 to ssk.com
Checking if winrm_host ssk.com is an IPV6 address
<ssk.com> WINRM CONNECT: transport=basic endpoinnt=http://ssk.com:5985/wsman
<ssk.com> WINRM CONNECTION ERROR: Bad HTTP response returned from server. Code 404
Trackback (most recent call last):
  File"/user/lib/python2.7/sitepackages/ansible/plugins/connection/winrm.py", line 400, in _winrm_connection
   self.shall_id+ protocal.open_shell(codepage=65001)  # UTF-8
  File"/user/lib/python2.7/sitepackages/winrm/protocal.py" Line 157, in open_shell
    res = self.send_message (xmltodict.unphase(req))
  File"/user/lib/python2.7/sitepackages/winrm/protocal.py" Line 242, in send_messgae
    raise ex
WINRMTransportError: Bad HTTP response return from server. Code 404

Fatal: [server] : UNREACHABLE! =>
{
"Changed" : false, "msg": "Basic: Bad HTTP Response FRom Server. code 404",
"Unreachable": True

```

**Comment by agowa** [comment]
Have you enabled unencrypted basic auth over http on the windows server?
Can you post steps to reproduce? E. G. What you've pre configured on your windows server?

**Comment by sakhamuri4545** [comment]
I have set allowunencrypted= true on client and services in listeners
Auth basic=true
Trustedhosts=*
Allow remote access = true
Open port 5985 in windows server

**Comment by jborean93** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

In any case you should **never** use basic auth over http and ever have to enable the allowUnencrypted setting. Basic auth over http means all traffic is unencrypted which is a big issue. If you cannot use HTTPS then at least set 'ansible_winrm_transport: ntlm' as that supports message encryption. I would also recommend that you verify you can use a native tool from Microsoft with the WinRM host as it seems to be a bad setup on the server. We have some guides on how to test this [here](https://docs.ansible.com/ansible/devel/user_guide/windows_setup.html#common-winrm-issues).
