### ISSUE TITLE
No way to indirectly lookup vars: facts

### ISSUE THREAD

**Issue by rektide** [ansible/ansible#5000]
If I `set_fact: foo=bar var=foo` (or include_vars), I can latter lookup whatever var is named in var by doing: `{{hostvars[inventory_hostname][var]}}`. However, if foo was set in vars:, there is no way to indirectly look it up: it exists at a higher level of fact-iness than hostvars do.

Please provide some means to indirectly resolve facts set in `vars` headers of a playbook.

**Comment by mpdehaan** [comment]
This seems like a more involved user question about use cases rather than a bug report, can you please stop by the mailing list?

**Comment by rektide** [comment]
`{{vars[var]}}` allows access to vars. This top level variable is defined here: https://github.com/ansible/ansible/blob/512ebdb9713744d1690ea7095ff8ee80ef1c713e/lib/ansible/runner/__init__.py#L435
