### ISSUE TITLE
ec2 ssh keypair module 

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#5003]
A simple way to add/remove ssh keypairs to ec2 would be great addition to the ec2 modules.

**Comment by pas256** [comment]
This is somewhat ambiguous.

Adding/removing SSH keys on EC2 is no different from any other server, and this:
http://www.ansibleworks.com/docs/modules.html#authorized-key
does that.

If you are referring to generating, importing and deleting EC2 Key Pairs, then I suggest the specifying that explicitly.

**Comment by jctanner** [comment]
@willthames were you planning on submitting a pull request for the commit above?

**Comment by willthames** [comment]
I decided to close the pull request as @zbal's implementation (https://github.com/ansible/ansible/pull/5256) was superior. 

Mine was https://github.com/ansible/ansible/pull/5263 - not sure why the PR is no longer associated with the commit, but guess that's a github bug/feature.

**Comment by jctanner** [comment]
Resolved by https://github.com/ansible/ansible/pull/5256
