### ISSUE TITLE
A file: state=directory that tolerates links

### ISSUE THREAD

**Issue by rektide** [ansible/ansible#5004]
state=directory dies if the thing that's there is a link. it's possible to add control flow to playbooks to tip toe around this failure, but it would be great to have a means baked in that will permit a symlink (if it points to a directory).

**Comment by mpdehaan** [comment]
Can you please try to explain this better?

Perhaps an example playbook or rewording the above, or perhaps steps to reproduce this problem?

Thanks!

**Comment by bcoca** [comment]
It looks like a follow=true option that tests the target to see if its a
symlink, then follows it until a non symlynk source and then apply the file
command to that (default follow=false, would keep module working as is).

**Comment by rektide** [comment]
Rolling with what bcoca has put forth, this would pass:

```
file: path=/tmp/directory state=directory
file: src=/tmp/directory dest=/tmp/dirlink state=link
file: path=/tmp/dirlink state=directory follow=true
```

**Comment by mpdehaan** [comment]
Understood, pull requests for this seem fine to me, but I worry that people would expect consistency for the copy and template (and other) modules as well, so probably needs to leverage some intelligence in module_common code.

**Comment by mpdehaan** [comment]
@bcoca is working on some consistency cleanup for state=link and so forth right now, which should take care of this, so I'm going to close out this ticket.
