### ISSUE TITLE
recursive copy mode does not copy empty source directories

### ISSUE THREAD

**Issue by phy1729** [ansible/ansible#5005]
copy: src=foo dest=/tmp  does not copy the directory foo/bar/ if bar is empty.

**Comment by mpdehaan** [comment]
edited defect description...

**Comment by mpdehaan** [comment]
copy is intended to copy files only.

You may have some luck with the "synchronize" module, which wraps rsync, or "local_action: rsync ..."

**Comment by sgpinkus** [comment]
"copy is intended to copy files only.". But it will do a recursive copy. So it is copying dirs but only when they have stuff in them. That is not really intuitive behavior. It should copy empty dirs.

**Comment by prilka** [comment]
I totally agree. It took me an hour to realize this behavior.

**Comment by njia** [comment]
files only ? what about empty files ? if it copies empty files then it should copy empty directories.
