### ISSUE TITLE
"smart" connection fails to fall back to paramiko in a SmartOS SmartMachine

### ISSUE THREAD

**Issue by jessegit** [ansible/ansible#5011]
SunOS ansible 5.11 joyent_20131102T215831Z i86pc i386 i86pc Solaris
instance (multiarch 13.3.0)

Running 512ebdb9713744d1690ea7095ff8ee80ef1c713e (devel, Fri Nov 22 00:09:37 2013 -0500)

The same happens with "-c ssh" and when no -c is provided. "-c paramiko" works as expected.

~/inventory contains "127.0.0.1 ansible_python_interpreter=/opt/local/bin/python", no ansible.cfg files set up.

```
[root@ansible ~]# ansible -vvvv all -c smart -i ~/inventory -m ping
<127.0.0.1> ESTABLISH CONNECTION FOR USER: root
<127.0.0.1> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '127.0.0.1', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1385124177.4-146279920777102 && echo $HOME/.ansible/tmp/ansible-1385124177.4-146279920777102'"]
previous known host file not found
127.0.0.1 | FAILED => SSH encountered an unknown error. The output was:
Sun_SSH_1.5, SSH protocols 1.5/2.0, OpenSSL 0x1000104f
debug1: Reading configuration data /etc/ssh/ssh_config
command-line: line 0: unknown configuration option: ControlMaster
command-line: line 0: unknown configuration option: ControlPersist
command-line: line 0: unknown configuration option: ControlPath
terminating, 3 bad configuration option(s)
```

**Comment by mpdehaan** [comment]
Yeah so it's supposed to work like this -- to use paramiko if you do not have an SSH new enough to support ControlPersist, it will use paramiko to be faster.

The solution if you want to pick ssh without conrol persist is to specify -c ssh or configure in the cfg file.

**Comment by jessegit** [comment]
Either the functionality or documentation is wrong,

"... however, the version of OpenSSH may be too old to support Control Persist. On these operating systems, Ansible will fallback into using a high-quality python implementation of OpenSSH called ‘paramiko’."
-- http://www.ansibleworks.com/docs/intro_getting_started.html

"The default is ‘smart’, which will use ‘ssh’ (OpenSSH based) if the local operating system is new enough to support ControlPersist technology, and then will otherwise use ‘paramiko’."
-- http://www.ansibleworks.com/docs/intro_configuration.html

"The value of ‘smart’ for a connection allows selection of paramiko or openssh based on system capabilities, and chooses ‘ssh’ if OpenSSH supports ControlPersist, in Ansible 1.2.1 an later."
-- http://www.ansibleworks.com/docs/developing_plugins.html

etc.

Not to mention, the -h help message default is wrong...
"  -c CONNECTION, --connection=CONNECTION
                        connection type to use (default=paramiko)"
-- ansible -h

**Comment by jessegit** [comment]
The real problem is probably at
https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/__init__.py#L196

which expects "Bad configuration option" but sun ssh error is "unknown configuration option"
