### ISSUE TITLE
ansible_distribution_version is not correct on CentOS 7

### ISSUE THREAD

**Issue by Spredzy** [ansible/ansible#50141]
##### SUMMARY

The `ansible_distribution_version` fact does not return correct value

  * `ansible 2.8.0.dev0` -> `"ansible_distribution_version": "7"`
  * `ansible 2.7.5` -> `"ansible_distribution_version": "7.5.1804"`

Faulty commit is: https://github.com/ansible/ansible/commit/61b1daa65f2e1978fac127aa11f7b0831d4ff243

##### ISSUE TYPE

  - Bug Report

##### COMPONENT NAME

  - facts

##### ANSIBLE VERSION

  - devel

##### CONFIGURATION

  - N/A

##### OS / ENVIRONMENT

  - CentOS 7

##### STEPS TO REPRODUCE

  - `ansible localhost -m setup | grep ansible_distribution_version`

##### EXPECTED RESULTS

```
[root@tower318 ansible]# ansible localhost -m setup | grep ansible_distribution_version
        "ansible_distribution_version": "7.5.1804"
```

##### ACTUAL RESULTS

```
[root@tower318 ~]# ansible localhost -m setup | grep ansible_distribution_version
        "ansible_distribution_version": "7",
```

**Comment by Spredzy** [comment]
cc @abadger

**Comment by abadger** [comment]
I'm not sure if this one is a new bug or a bugfix.  /etc/os-release is theoretically supposed to be the canonical source for information and it says that version_id is 7 on centos7.5.  /etc/redhat-release contains the previously presented version as part of it's string and distro does give us access to it via distro.distro_release_{attr,info}().  So we just need to decide whether we should special case using the distro_release_* functions for the version on centos/rhel7.

**Comment by abadger** [comment]
Okay, I had a talk with a CentOS core dev and some rhel people as well.  Their input is that RHEL supports point releases and therefore should return ```ansible_distribution_version: "7.6"```.  CentOS does not support point releases (they just add the new packages to the existing centos7 repository) so they consciously do not add the minor version.  They think their version should be ```ansible_distribution_version: "7"```.  Neither distro should have the extra, third field, as that's just a build artifact that's ending up in a legacy file ( ```/etc/{redhat,centos}-release```).  So I'm doing to say that the new output is a bug fix and we should keep it.

I can update changelogs/fragments/platform-dist-to-nir0s-distro.yaml and add a porting guide entry, though, to say that the facts for some distributions may have changed.

(Also note, this seems to be something that we have to look at on a distro-by-distro basis.  This case seems to be a bugfix but there are other distributions where we've decided that the new behaviour is a bug and we've added shims to enforce different behaviour).

**Comment by Spredzy** [comment]
@abadger thanks for the detailed answer and the effort you've been through to reach out to the CentOS team. Much appreciated.

Just to clarify, and please correct me if I am wrong, from now on there would be no out-of-the-box way (understand facts) to "know" to which minor version a CentOS version belongs as they do not support point in time releases?

```
[root@localhost ansible]# ansible localhost -m setup | grep ansible_distribution
        "ansible_distribution": "CentOS",
        "ansible_distribution_file_parsed": true,
        "ansible_distribution_file_path": "/etc/redhat-release",
        "ansible_distribution_file_variety": "RedHat",
        "ansible_distribution_major_version": "7",
        "ansible_distribution_release": "Core",
        "ansible_distribution_version": "7",
```

So if one wants to retrieve this information, one should poke at the content of `/etc/{redhat,centos}-release` and parse it from there. Is that correct ?

```
[root@localhost ansible]# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
```

**Comment by abadger** [comment]
Correct

>

**Comment by ianabc** [comment]
I know this is closed, but the previous behaviour was more useful. At the moment one of `ansible_distribution_major_version` or `ansible_distribution_release` is redundant. Some external things (e.g. [zfsonlinux](https://github.com/zfsonlinux/zfs/wiki/RHEL-and-CentOS)) depend on the minor version, whether or not CentOS say they explicitly support it. It would be nice to have the more specific string available as a variable rather than having to manually retrieve it every time.

**Comment by guzzijason** [comment]
Also, yes... realized this is closed, but the comment above that `CentOS does not support point releases` is patently false. All you need to do is look at their repo mirrors and you can easily see the point release structure. We've relied on this heavily for years.
