### ISSUE TITLE
Ansible website evolution

### ISSUE THREAD

**Issue by VoidAndAny** [ansible/ansible#5016]
Not really an issue but is it possible to add a button/link "back to top" on the module page of ansible website or better stick the module list (left column) on the top of screen when scrolling.

Not a big deal but this page is huge (what is great because they are a lot of module)

By the way, great great product, I love ansible (tried chef before, no comment...)

**Comment by mpdehaan** [comment]
Yeah this is really more for info@ansibleworks.com about, but I'll pass it along.

I use the "HOME" key on my keyboard for that, but thanks for the suggestion!

**Comment by VoidAndAny** [comment]
Sorry for the pollution...

FYI no home key on mac keyboard (I know it's a shame)
