### ISSUE TITLE
What's the story with #<<INCLUDE_ANSIBLE_MODULE_COMMON>>?

### ISSUE THREAD

**Issue by tony** [ansible/ansible#5018]
Hi, A few questions on the internals of ansible / for people wanting to help hack :smile: 
- Why do the files not have `.py` extensions?
- Why the use of `#<<INCLUDE_ANSIBLE_MODULE_COMMON>>`
- Historically speaking, is their any blog posts, issues, documentation or useful information on it?
- What is the current / roadmap ahead, if any with this module format?
- Is there an intention of modules and ansible being pythonic?
- Is there some documentation of this architectural standpoints for people interested in hacking?

**Comment by jctanner** [comment]
@tony this larger list of questions is more suitable for the ansible-users mailing list. If you want to open a specific bug report on docs, please do.

**Comment by mpdehaan** [comment]
The GitHub issue tracker is not the proper place for Q&A, please post to the mailing list if you'd like more info.  (not to contradict @jctanner, I'd recommend ansible-devel vs ansible-users)

I'll provide some basic info though.

Ansible does lots of things to optimize transfer in the no bootstrapping case.
Namely, Ansible has a highly optimized SSH transport designed for requiring no dependencies to be installed on the remote system.

As such, we don't use python modules that are preinstalled, we transfer everything in one file, including arguments, to make sure we can send structured data in a minimum number of operations.

I would like to direct you to 

https://github.com/ansible/ansible/tree/devel/lib/ansible/module_utils
and
https://github.com/ansible/ansible/blob/devel/library/cloud/ec2#L650

for the new way of doing things (it's 100% compatible with the old and we haven't moved all the modules over yet).

and 

http://ansibleworks.com/docs/developing_modules.html

in the meantime

Modules are easily testable using the ./hacking/test-module script in the git checkout as mentioned in the developer guide.

You can also see this thread:

https://groups.google.com/forum/#!msg/ansible-devel/kUEmV_uqJV0/Bs1cQxdAzH0J

Finally, take note that Ansible allows writing modules in any language, not just Python.

If you have any further questions (other than requests to change how this works, of course!), please ask on Ansible devel!

**Comment by jimi-c** [comment]
Removed my dupe response, mdehaan beat me to it.
