### ISSUE TITLE
A typo at special_variables page

### ISSUE THREAD

**Issue by plastikat** [ansible/ansible#50198]
##### SUMMARY

I was building a list of Ansible special variables to perform a massive facts namespace migration and encountered an error at the following page:
https://docs.ansible.com/ansible/2.7/reference_appendices/special_variables.html

`ansible_connecion` should actually be `ansible_connection`.

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

**Comment by Akasurde** [comment]
@plastikat Thanks for closely reading the documentation and reporting. Would you be interested in opening a PR against your findings ? Thanks.

**Comment by plastikat** [comment]
Sure, here it is: https://github.com/ansible/ansible/pull/50230

**Comment by Akasurde** [comment]
resolved_by_pr #50230
