### ISSUE TITLE
zsh 4.3.10 doesn't like env-setup script

### ISSUE THREAD

**Issue by britcey** [ansible/ansible#5026]
$ zsh --version
zsh 4.3.10 (x86_64-unknown-linux-gnu)

$ . ./hacking/env-setup -q
./hacking/env-setup:8: unrecognized modifier

$ bash
$ . ./hacking/env-setup -q
$ ./bin/ansible --version
ansible 1.4

It looks to be this line:

elif [ ${0:(-9)} = "env-setup" ]; then

which zsh 4.3.10 doesn't like, but newer versions seem fine with (e.g., zsh 4.3.11 on OS X):

$ zsh --version
 zsh 4.3.10 (x86_64-unknown-linux-gnu)
$ echo ${0:(-9)}
zsh: unrecognized modifier

$ zsh --version
zsh 4.3.11 (i386-apple-darwin12.0)
$ echo ${0:(-9)}
-zsh

**Comment by mpdehaan** [comment]
Yeah, it wasn't written for zsh.

You'll notice there's a script for bash and fish.   Perhaps you would like to supply a zsh version or make the existing one compliant?

**Comment by britcey** [comment]
Somewhat hilariously, the last commit for env-setup is 'Add zsh support for working dir independant sourcing', which added the problematic line, so _someone_ thinks it's written for zsh ;-)

It's appears to only be a problem for zsh < 4.3.11, which is only an issue for me because I'm running from a Ubuntu Lucid box;  Precise is rolling out internally anyway & it'll only be an issue for people running Ansible via checkout, so I'll punt & close this out.  If other people bring it up, I'll pow-wow with @phy1729 and figure something out.

Thx.

**Comment by JensRantil** [comment]
> If other people bring it up, I'll pow-wow with @phy1729 and figure something out.

I'm experiencing this, too, for Ansible 1.4.1. I'm running zsh 4.3.10. Worked with 1.3.4.
