### ISSUE TITLE
Hosts module for editing hosts file removed?

### ISSUE THREAD

**Issue by Jurawa** [ansible/ansible#5027]
Wondering why the hosts module existed and was documented on the modules documentation page for a short time but then was removed and not noted in the changelog... we were using it, and though its not a big deal to recreate the functionality, its not great to find these inconsistencies without any documentation of their changes.

Thanks!

Jurawa

Update: found the commit it was removed on... https://github.com/ansible/ansible/commit/b29669dccdd61afac11557f4baa6c1e397e70667

Would have been nice to have this noted in the module documentation and changelog.

**Comment by mpdehaan** [comment]
In general, GitHub is not the place to ask questions, use the mailing list.

This module had some issues and didn't make it into the release.

I hope it gets fixed up for 1.5

**Comment by Jurawa** [comment]
Sure, will do next time. Thanks for the explanation.
