### ISSUE TITLE
traceback on badly formatted playbook, provide nicer error msg?

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#5029]
```
 root@ansible-master:/home/voltagex# ansible-playbook taste.yml
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 269, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 159, in main
    diff=options.diff
  File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 149, in __init__
    (self.playbook, self.play_basedirs) = self._load_playbook_from_file(playbook, vars)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 159, in _load_playbook_from_file
    playbook_data  = utils.parse_yaml_from_file(path)
  File "/usr/lib/pymodules/python2.7/ansible/utils/__init__.py", line 483, in parse_yaml_from_file
    process_yaml_error(exc, data, path)
  File "/usr/lib/pymodules/python2.7/ansible/utils/__init__.py", line 461, in process_yaml_error
    msg = process_common_errors(msg, probline, mark.column)
  File "/usr/lib/pymodules/python2.7/ansible/utils/__init__.py", line 406, in process_common_errors
    if middle[0] in [ '"', "'" ] and middle[-1] in [ '"', "'" ] and probline.count("'") > 2 or probline.count("'") > 2:
IndexError: string index out of range
```

Playbook file is

```
  ---
- hosts: all
        tasks:
        - name: ensure nginx is installed
        apt: pkg=nginx state=present
```

**Comment by codyhatch** [comment]
I think your indentation may be messed up?  Try this:

``` yml
---
- hosts: all
  tasks:
  - name: ensure nginx is installed
    apt: pkg=nginx state=present
```

Make sure you have no spaces at the start of lines 1 and 2, 2 on lines 3 and 4, and 4 on line 5.  The n in "name" and the a in "apt" should be in the same column, just like the t in "tasks" and the h in "hosts".

**Comment by ghost** [comment]
Is it possible to get more helpful error messages out of Ansible?

**Comment by mpdehaan** [comment]
I don't know what voltagex means, there's not like a --please-dont-give-me-a-lousy-error-message-here flag :)

I agree the error message here is suboptimal.

**Comment by codyhatch** [comment]
Well, there is a --syntax-check flag.  Not universally helpful, but it would have helped @voltagex in this case. :smile:

**Comment by ghost** [comment]
@CodyHatch 
ansible-playbook --syntax-check taste.yml

gives the same error as before, but I removed all whitespace and started again and it works. Still, this could be quite confusing for someone new to Ansible/YAML (like myself)

**Comment by codyhatch** [comment]
What version of ansible are you using?  In particular, what's the results of running

```
ansible --version
```

**Comment by ghost** [comment]
ansible 1.4, although I experienced the same after using the latest devel version.

**Comment by jcassee** [comment]
This is a bug in the error handling. Commenting out lines 406 and 407 (Ansible 1.4) gives a nice error message.

**Comment by jimi-c** [comment]
I believe I have fixed this in relation to another similar bug on the exact same line, if someone can re-pull and test.

**Comment by jctanner** [comment]
Confirmed new useful errors with the playbook cited in the description.
