### ISSUE TITLE
do/until delay option should be cast to float

### ISSUE THREAD

**Issue by jeromew** [ansible/ansible#5031]
when using delay: on a do/until loop with a variable e.g.
delay: "{{ variable }}"
you get
=>TypeError: a float is required

the delay should be cast to float() just before creating the timer and after variable rendering.

additional traces :
delay: 60
=> ok

delay: "60"
=>TypeError: a float is required

delay: !!float "60"
=> ok

**Comment by mpdehaan** [comment]
Please include the full playbook that shows where you are defining "variable", but it looks like we should be casting inside the module.

Until then, {{ variable | int }} should take care of you.

**Comment by jamengual** [comment]
here it is : 

```
- name: Wait for akamai to clear
     action: uri url=https://api.ccu.akamai.com{{akamairesponse.json.progressUri}}
             method=GET user=xxx password=xxx
             HEADER_Content-Type="application/json"
             status_code=200
             return_content=yes
     register: akamaistatus
   #- debug: msg="value of status  {{akamaistatus.json.purgeStatus}}"
     until: "'{{akamaistatus.json.purgeStatus}}' == 'Done'"
     retries: 10
     #delay: 60
     delay: '{{akamairesponse.json.estimatedSeconds|int}}'
```

debug shows :

TASK: [debug msg="value of {{akamairesponse.json.estimatedSeconds|int}}"] *****
ok: [localhost] => {
    "msg": "value of 420"
}

debug :

TASK: [Wait for akamai to clear] **********************************************
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1385160064.24-173468909890043 && chmod a+rx $HOME/.ansible/tmp/ansible-1385160064.24-173468909890043 && echo $HOME/.ansible/tmp/ansible-1385160064.24-173468909890043']
<localhost> REMOTE_MODULE uri url=https://api.ccu.akamai.com/ccu/v2/purges/ef63d1a5-5401-11e3-8c54-712f0c54712f method=GET user=xxx password=xxx HEADER_Content-Type="application/json" status_code=200 return_content=yes
<localhost> PUT /tmp/tmpctvzt8 TO /usr/home/jamengual/.ansible/tmp/ansible-1385160064.24-173468909890043/uri
<localhost> EXEC ['/bin/sh', '-c', '/usr/local/bin/python /usr/home/jamengual/.ansible/tmp/ansible-1385160064.24-173468909890043/uri; rm -rf /usr/home/jamengual/.ansible/tmp/ansible-1385160064.24-173468909890043/ >/dev/null 2>&1']
fatal: [localhost] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/**init**.py", line 394, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 485, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 688, in _executor_internal_inner
    time.sleep(delay)
TypeError: a float is required

**Comment by mpdehaan** [comment]
Thanks!

**Comment by jeromew** [comment]
> > Until then, {{ variable | int }} should take care of you.

this workaround does not work. you can try with

```
- hosts: localhost
  gather_facts: no
  vars:
    seconds: 1
  tasks:
    - name: delay bug
      debug: msg="looping"
      register: output
      until: no
      retries: 5
      delay: "{{ seconds | int }}"
```

=> File "/home/node/ansiwork/lib/ansible/runner/**init**.py", line 695, in _executor_internal_inner
    time.sleep(delay)
TypeError: a float is required
