### ISSUE TITLE
service module doesn't work correctly against fedora 15 host

### ISSUE THREAD

**Issue by zart** [ansible/ansible#5037]
Ansible fails `"service: name=rsyslog enabled=yes"` command with `{"failed": true, "msg": "unknown service name"}` against Fedora 15 host.
Old systemd version there doesn't support list-unit-files command which trips systemctl detection logic in service module. Also enabling service doesn't work properly because there is no _UnitFileState_ in `systemctl show` output.

**Comment by mpdehaan** [comment]
Fedora 15 was EOL on 2012-06-26 so I'll consider the pull request if it's non-damaging, but you really should update for security reasons.

**Comment by mpdehaan** [comment]
(Closing redundant ticket as the pull request is also a ticket)
