### ISSUE TITLE
ansible_<interface> problem

### ISSUE THREAD

**Issue by romabysen** [ansible/ansible#5040]
I just upgraded to 1.4 and, well, there seems to be something wrong with how Ansible handle interfaces and "subinterfaces":

```
"ansible_eth0": {
    "active": true, 
    "device": "eth0", 
    "ipv4": {
        "address": "21.4.151.74", 
        "netmask": "255.255.255.0", 
        "network": "21.4.151.0"
    }, 
    "ipv4_secondaries": [
        {
            "address": "21.4.151.75", 
            "netmask": "255.255.255.0", 
            "network": "21.4.151.0"
        }
    ], 
    "ipv6": [
        {
            "address": "fe80::116:3eaf:fe5c:75ce", 
            "prefix": "64", 
            "scope": "link"
        }
    ], 
    "macaddress": "00:16:3e:5c:75:ce", 
    "module": "xen_netfront", 
    "mtu": 1500, 
    "promisc": false, 
    "type": "ether"
}, 
"ansible_eth0_0": {
    "active": true, 
    "device": "eth0", 
    "ipv4": {
        "address": "21.4.151.74", 
        "netmask": "255.255.255.0", 
        "network": "21.4.151.0
    }, 
    "ipv4_secondaries": [
        {
            "address": "21.4.151.75", 
            "netmask": "255.255.255.0", 
            "network": "21.4.151.0"
        }
    ], 
    "ipv6": [
        {
            "address": "fe80::116:3eaf:fe5c:75ce", 
            "prefix": "64", 
            "scope": "link"
        }
    ], 
    "macaddress": "00:16:3e:5c:75:ce", 
    "module": "xen_netfront", 
    "mtu": 1500, 
    "promisc": false, 
    "type": "ether"
}, 
```

You'll notice that eth0 and eth0_0 are actually exactly the same and the more interfaces I add (eth0:1, eth0:2 etc) the more exactly the same sections I get. I would have expected eth0_0 to have as it's ipv4 address the address that is configured on that interface and not that it would be listed as a secondary.
This is on CentOS 6.4.

**Comment by mpdehaan** [comment]
ansible --version ?

Output of /sbin/ip and such?

**Comment by romabysen** [comment]
On the ansible host:

```
$ ansible --version
ansible 1.4
```

On the target:

```
$ cat /etc/redhat-release
CentOS release 6.4 (Final)

$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:19:99:ef:13:65 brd ff:ff:ff:ff:ff:ff
    inet 94.242.255.68/24 brd 94.242.255.255 scope global eth0
    inet 94.242.255.93/32 brd 94.242.255.93 scope global eth0:0
    inet6 fe80::219:99ff:feef:1365/64 scope link 
       valid_lft forever preferred_lft forever

$ ifconfig
eth0      Link encap:Ethernet  HWaddr 00:19:99:EF:13:65  
          inet addr:94.242.255.68  Bcast:94.242.255.255  Mask:255.255.255.0
          inet6 addr: fe80::219:99ff:feef:1365/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:75286736 errors:0 dropped:0 overruns:0 frame:0
          TX packets:74172900 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:70005908594 (65.1 GiB)  TX bytes:71251986742 (66.3 GiB)
          Interrupt:18 Memory:ef900000-ef920000 

eth0:0    Link encap:Ethernet  HWaddr 00:19:99:EF:13:65  
          inet addr:94.242.255.93  Bcast:94.242.255.93  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Interrupt:18 Memory:ef900000-ef920000 
```

**Comment by jctanner** [comment]
Looks like this was broken by a2ac5d6df2059b564fe28c706b349069c2a24e72

**Comment by romabysen** [comment]
I just got back to having to use this again and it seems it is still broken. On some servers I get the subinterfaces with the right address but no ipv4_secondaries on the main interface. On others I get the same problem as above and a list of addresses in ipv4_secondaries.  For some reason ipv4_secondaries also exist on subinterfaces and not only on the main interface.
Ansible is 1.4.4 and the hosts with the original problem are Xen VPS's and the ones with the right subinterface address is Centos 6.x.

On Xen:
$ ip addr 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
    inet 25.0.0.1/32 brd 25.0.0.1 scope global lo:0
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN 
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
3: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether aa:00:58:30:1c:3e brd ff:ff:ff:ff:ff:ff
    inet 101.16.140.106/26 brd 103.16.180.127 scope global eth0
    inet 101.16.140.117/26 brd 103.16.180.127 scope global secondary eth0:0
    inet6 fe80::a800:58ff:fe30:1c3e/64 scope link 
       valid_lft forever preferred_lft forever

On a Centos 6.x:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
    inet 25.0.0.1/32 brd 25.0.0.1 scope global lo:0
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 66:14:15:09:29:d5 brd ff:ff:ff:ff:ff:ff
    inet 208.62.18.125/27 brd 208.62.18.127 scope global eth0
    inet 208.62.18.126/27 brd 208.62.18.127 scope global secondary eth0:0
    inet6 fe80::6414:15ff:fe09:29d5/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by techtonik** [comment]
Can you specify `ip addr` and ansible 1.5.0 output for comparison? I am not sure that the output should be in the last case.

**Comment by techtonik** [comment]
Also see #6274 - it may happen that the output changed again. In any case it is better to open a new issue.
