### ISSUE TITLE
ec2_vpc module parameter wait=yes traceback

### ISSUE THREAD

**Issue by dhml** [ansible/ansible#5043]
boto.vpc.VPCConnection.get_all_vpcs() returns a list of boto.vpc.vpc.VPC, but line 236 in library/cloud/ec2_vpc attempts to access the state attribute directly on the list, resulting in the following:

TASK: [create vpc] ************************************************************
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/ddh/.ansible/tmp/ansible-1385330903.0-22634021687001/ec2_vpc", line 1595, in <module>
    main()
  File "/home/ddh/.ansible/tmp/ansible-1385330903.0-22634021687001/ec2_vpc", line 526, in main
    (vpc_dict, new_vpc_id, subnets_changed, changed) = create_vpc(module, vpc_conn)
  File "/home/ddh/.ansible/tmp/ansible-1385330903.0-22634021687001/ec2_vpc", line 236, in create_vpc
    if pvpc.state == "available":
AttributeError: 'ResultSet' object has no attribute 'state'

**Comment by dhml** [comment]
Trivial fix is to change line 236 to...

if pvpc[0].state == "available":

**Comment by mpdehaan** [comment]
(A)

ansible --version and boto version?

(B) 

If that's the trivial fix, how about a pull request?

**Comment by jctanner** [comment]
@dhml Would you mind trying this patch?

```
diff --git a/library/cloud/ec2_vpc b/library/cloud/ec2_vpc
index 28804a2..663a574 100644
--- a/library/cloud/ec2_vpc
+++ b/library/cloud/ec2_vpc
@@ -233,8 +233,12 @@ def create_vpc(module, vpc_conn):
             wait_timeout = time.time() + wait_timeout
             while wait and wait_timeout > time.time() and pending:
                 pvpc = vpc_conn.get_all_vpcs(vpc.id)
-                if pvpc.state == "available":
-                    pending = False
+                if hasattr(pvpc, 'state'):
+                    if pvpc.state == "available":
+                        pending = False
+                elif hasattr(pvpc[0], 'state'):
+                    if pvpc[0].state == "available":
+                        pending = False
                 time.sleep(5)
             if wait and wait_timeout <= time.time():
                 # waiting took too long
```

From http://boto.readthedocs.org/en/2.0/ref/boto.html#module-boto.resultset it seems that pvpc is always going to be a "list". Is that what you have seen as well?

**Comment by dhml** [comment]
Yes this is what I've observed and what I gather from the boto.vpc docs for this method:

http://boto.readthedocs.org/en/2.0/ref/vpc.html#boto.vpc.VPCConnection.get_all_vpcs

The patch works.  My bad on the pull request ... I'll submit them from now on.  At the time I opened the issue my Ansible version was 1.4.  Same issue now in 1.5 (devel cdbce4a5c8).  boto version is 2.19.0.

**Comment by jctanner** [comment]
@dhml if you want to send a PR with my patch, i'll merge it and give you credit since you were the one who figured it out. It would also help me verify that someone actually tested it.

**Comment by dhml** [comment]
Will do...
