### ISSUE TITLE
Syntax error from wait_for module (Python 2.4 on managed nodes)

### ISSUE THREAD

**Issue by junegunn** [ansible/ansible#5044]
https://github.com/ansible/ansible/commit/bf435e2032a3faa48cb7c571c139fe4b0af344bf

The above commit introduces "with" statement which is not a valid syntax on Python 2.4. So wait_for module fails if the managed nodes are running Python 2.4.

```
failed: [REDACTED] => {"failed": true, "item": "", "parsed": false}
invalid output was: SUDO-SUCCESS-lbxrkrfqqektwhwskkgbfujdhcywjadp
  File "REDACTED", line 160
    with open(path) as f:
            ^
SyntaxError: invalid syntax
```

**Comment by mpdehaan** [comment]
Yep, that's not 2.4 compliant for sure -- we should definitely include this in our next dot release.

cc @jctanner
