### ISSUE TITLE
Service module cannot start services that use "rc_bg=YES" on OpenBSD

### ISSUE THREAD

**Issue by sometimesfood** [ansible/ansible#50460]
##### SUMMARY
The `service` module cannot start services that use `rc_bg=YES` on OpenBSD. The target service is started initially, but the process is killed as soon as the Ansible SSH connection is closed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
service

##### ANSIBLE VERSION
```paste below
ansible 2.7.5
  config file = None
  configured module search path = ['/Users/sebastian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.5/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Dec 27 2018, 07:35:52) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION
```paste below
DEFAULT_KEEP_REMOTE_FILES(env: ANSIBLE_KEEP_REMOTE_FILES) = True
```

##### OS / ENVIRONMENT
Target OS version: OpenBSD 6.4

##### STEPS TO REPRODUCE
1. Spin up a pristine OpenBSD 6.4 VM.
2. Install Python package.
3. Try to start the `ypbind` service (set domain name using `domainname(1)` first).

Note: `ypbind` is the only service in OpenBSD base that uses `rc_bg=YES`. The same happens with any other service that uses `rc_bg=YES`, for example with the Logstash package.

Copy & paste example:
```
export HOST_IP=''
cat >hosts <<EOF
[temp]
temp01 ansible_host=${HOST_IP} ansible_python_interpreter=/usr/local/bin/python3
EOF
ansible temp -i hosts -u root -m raw -a 'pkg_add python%3'
ansible temp -i hosts -u root -m shell -a 'domainname example.com'
ansible temp -i hosts -u root -m service -a 'name=ypbind state=started'
ansible temp -i hosts -u root -m shell -a 'rcctl check ypbind'
```

Example with output:
```
~/ansible-temp % cat >hosts <<EOF
[temp]
temp01 ansible_host=${HOST_IP} ansible_python_interpreter=/usr/local/bin/python3
EOF

~/ansible-temp % ansible temp -i hosts -u root -m raw -a 'pkg_add python%3'
# [...]

~/ansible-temp % ansible temp -i hosts -u root -m shell -a 'uname -a'
temp01 | CHANGED | rc=0 >>
OpenBSD openbsd.example.com 6.4 GENERIC#349 amd64

# set a domain name using the shell module
~/ansible-temp % ansible temp -i hosts -u root -m shell -a 'domainname example.com'
temp01 | CHANGED | rc=0 >>


# try to start ypbind using the service module
~/ansible-temp % ansible temp -i hosts -u root -m service -a 'name=ypbind state=started'
temp01 | CHANGED => {
    "changed": true,
    "name": "ypbind",
    "state": "started"
}
```

##### EXPECTED RESULTS
The `ypbind` service should be running.

##### ACTUAL RESULTS
The `ypbind` service is not running.

```paste below
~/ansible-temp % ansible temp -i hosts -u root -m shell -a 'rcctl check ypbind'
temp01 | FAILED | rc=1 >>
ypbind(failed)non-zero return code
```

**Comment by sometimesfood** [comment]
The same thing happens when using the shell module:

```
~/ansible-temp % ansible temp -i hosts -u root -m shell -a 'rcctl -f start ypbind'
temp01 | CHANGED | rc=0 >>
ypbind(ok)

~/ansible-temp % ansible temp -i hosts -u root -m shell -a 'rcctl check ypbind'
temp01 | FAILED | rc=1 >>
ypbind(failed)non-zero return code
```

However, if I use SSH to perform the same task without Ansible, everything works as expected:
```
~/ansible-temp % ssh root@${HOST_IP} rcctl -f start ypbind
ypbind(ok)
~/ansible-temp % ansible temp -i hosts -u root -m shell -a 'rcctl check ypbind'
temp01 | CHANGED | rc=0 >>
ypbind(ok)
```

**Comment by sometimesfood** [comment]
I used `ANSIBLE_KEEP_REMOTE_FILES` and `ansible -vvv` to better understand this behaviour.

If I run the remote file manually and replace the `sleep 0` with `sleep 30`, the `ypbind` service keeps running for 30 seconds before being killed again:

#### First shell
```
~/ansible-temp % ssh -C -o User=root -tt ${HOST_IP} '/bin/sh -c '"'"'/usr/local/bin/python3 /root/.ansible/tmp/ansible-tmp-1546452174.042668-218079288911190/AnsiballZ_service.py && sleep 120'"'"''

{"name": "ypbind", "state": "started", "changed": true, "invocation": {"module_args": {"name": "ypbind", "state": "started", "runlevel": "default", "arguments": "", "sleep": null, "pattern": null, "enabled": null}}}
```

#### Second shell
```
~/ansible-temp % ssh root@${HOST_IP} rcctl check ypbind; sleep 30; ssh root@${HOST_IP} rcctl check ypbind
ypbind(ok)
ypbind(failed)
```

**Comment by bcoca** [comment]
The service is not backgrounding itself properly, needing rc_bg=yes is an indicator of that, so when the connection closes it is getting killed. The service manager should deal with this specifically, so this is a bug,  until it can be fixed,  try using nohup or dtach with shell when invoking the service.

**Comment by sometimesfood** [comment]
Thanks for the quick response, Brian.

Yes, using nohup in my start script is exactly what I did to work around this behaviour.

**Comment by sometimesfood** [comment]
Just updated the instructions in the description for OpenBSD 6.5. This issue is still present in Ansible 2.8.

Could you please add the label affects_2.8? Thanks.
