### ISSUE TITLE
Unarchive module failure with zip files

### ISSUE THREAD

**Issue by greenbrian** [ansible/ansible#5049]
Unarchive module wasn't working for my zip files and I didn't find any output giving me hints, dug into the module and found a problem with the argument order:

```
def unarchive(self):
cmd = 'unzip "%s" -d "%s" -o'  % (self.src,self.dest)

$ unzip myfile.zip -d /local/ -o
Archive:  myfile.zip
caution: filename not matched:  -o
```

Changed to the following and all was happy:

```
def unarchive(self):
cmd = 'unzip -o "%s" -d "%s"'  % (self.src,self.dest)
```

I'd submit a PR but I don't git so good yet, and this is a matter of a few keystrokes for someone.

**Comment by mpdehaan** [comment]
Please let me know the OS you are managing remotely and what version of unzip.   

Thanks!

**Comment by mpdehaan** [comment]
also I should point out this project does require pull requests for code contributions.

GitHub has a good tutorial here:  https://help.github.com/articles/using-pull-requests

**Comment by greenbrian** [comment]
Local & remote server are both RHEL 5.8 x86_64

```
$ rpm -qa | grep unzip
unzip-5.52-3.el5

$ unzip -version
caution:  both -n and -o specified; ignoring -o
UnZip 5.52 of 28 February 2005, by Info-ZIP.  Maintained by C. Spieler.  Send
bug reports using http://www.info-zip.org/zip-bug.html; see README for details.

Latest sources and executables are at ftp://ftp.info-zip.org/pub/infozip/ ;
see ftp://ftp.info-zip.org/pub/infozip/UnZip.html for other sites.

Compiled with gcc 4.1.2 20071124 (Red Hat 4.1.2-41) for Unix (Linux ELF) on Jul 14 2008.

UnZip special compilation options:
        COPYRIGHT_CLEAN (PKZIP 0.9x unreducing method not supported)
        SET_DIR_ATTRIB
        TIMESTAMP
        USE_EF_UT_TIME
        USE_UNSHRINK (PKZIP/Zip 1.x unshrinking method supported)
        USE_DEFLATE64 (PKZIP 4.x Deflate64(tm) supported)
        VMS_TEXT_CONV
        [decryption, version 2.9 of 05 May 2000]

UnZip and ZipInfo environment options:
           UNZIP:  [none]
        UNZIPOPT:  [none]
         ZIPINFO:  [none]
      ZIPINFOOPT:  [none]
```

I'll see about a making a pull request, thanks for the link.

**Comment by greenbrian** [comment]
Pull request:  https://github.com/ansible/ansible/pull/5050

**Comment by mpdehaan** [comment]
Ok, that looks like it just wasn't tested very well then or it was a newer unarchive that accepted options in a different way. 

Looks good, thanks!

**Comment by jctanner** [comment]
Closing since #5050 was merged.
