### ISSUE TITLE
Roles are ran multiple times if both referenced as dependency and from playbook

### ISSUE THREAD

**Issue by BarbzYHOOL** [ansible/ansible#50522]
##### SUMMARY

Reopen this issue please https://github.com/ansible/ansible/issues/22169

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Playbooks/Roles
##### ANSIBLE VERSION

```paste below
2.7.5
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by sivel** [comment]
We typically do not re-open issues.

Please fill out the template fully with a full minimal reproducer and full description of this issue.

needs_info

**Comment by BarbzYHOOL** [comment]
then why close it, if it's gonna get closed again, then no thx 

anyway I saw that a similar issue is still open

**Comment by bcoca** [comment]
@BarbzYHOOL unsure why you assume this will be closed, I can asure you that if you give us a reproducer we will address the issue. 

You are pointing to a bug that was fixed (see my comment in it with the test output run), you might have a similar bug but we need a reproducer, linking to a closed and verified fixed bug does not help us address your issue.

**Comment by BarbzYHOOL** [comment]
Obviously if i linked the other issue it's because it's the same issue as many other people have commented. There is no special reproducer, you just add your role to meta dependencies and in your playbook and it's ran twice instead of once. As simple as the title implies


"I can asure you that if you give us a reproducer we will address the issue." the question is when? when a playbook is broken it's hard to wait 1 year, but I know you guys have too much work to do with ansible so I accept it and try to find a shitty workaround, but i'm still utterly annoyed, sorry for my behaviour but I can't stop myself from raging lol

**Comment by bcoca** [comment]
@BarbzYHOOL see the last comment on that ticket, i used the exact playbook of the original report and it does NOT show duplicates, i also answered the couple of posts that had actual reproducers. 

I doubt that your issue is the same as the original, since i have a test that proves that was fixed. I'm asking for a reproducer of your exact issue, since I cannot fix generalities.

**Comment by BarbzYHOOL** [comment]
I don't see what is special in his issue. For me, it's just playbook has role A + role B, and in role B, there is meta dependency calling role A

Result = role A ran twice, and role B ran once

**Comment by bcoca** [comment]
@BarbzYHOOL in my tests, that does not happen, so you need to give me a way to reproduce that

**Comment by bcoca** [comment]
play
```yaml
- hosts: localhost
  gather_facts: false
  roles:
    - role: a
    - role: b
```
```
cat roles/b/meta/main.yml
dependencies:
    - name: a
```
output:
```
#> ansible-playbook play.yml

PLAY [localhost] *********************************************************************************************************************************

TASK [a : debug] *********************************************************************************************************************************
ok: [localhost] => {
    "msg": "A"
}

TASK [b : debug] *********************************************************************************************************************************
ok: [localhost] => {
    "msg": "B"
}

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0
```

**Comment by BarbzYHOOL** [comment]
Ok will do then, sorry and thank you for being overly nice.

I'll do it asap here and open an issue if needed

**Comment by BarbzYHOOL** [comment]
@bcoca I retested the above and it worked fine, I don't know what I did specifically but I can't reproduce it (but i clearly remember seeing tasks being ran twice in a row from the same role).

Fuck I should have noted it down as I do usually

**Comment by pacahon** [comment]
@bcoca I'm sorry, should your [test example](https://github.com/ansible/ansible/issues/50522#issuecomment-451462849) works fine with `import_role` instead of `role`? Couldn't figure it out from the documentation.

```yaml
# play.yml
- hosts: localhost
  gather_facts: false
  tasks:
    - import_role:
        name: a
    - import_role:
        name: b
```

My output with ansible 2.7.5

```
PLAY [localhost] ***************************************************************************************************************************************************************************************************************************************************************

TASK [a : debug] ***************************************************************************************************************************************************************************************************************************************************************
Thursday 24 January 2019  11:25:59 +0300 (0:00:00.189)       0:00:00.189 ******
ok: [localhost] => {
    "msg": "A"
}

TASK [a : debug] ***************************************************************************************************************************************************************************************************************************************************************
Thursday 24 January 2019  11:25:59 +0300 (0:00:00.131)       0:00:00.321 ******
ok: [localhost] => {
    "msg": "A"
}

TASK [b : debug] ***************************************************************************************************************************************************************************************************************************************************************
Thursday 24 January 2019  11:25:59 +0300 (0:00:00.129)       0:00:00.451 ******
ok: [localhost] => {
    "msg": "B"
}

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

**Comment by BarbzYHOOL** [comment]
no, I think I've read that it's intended to be able to run it multiple times with tasks
