### ISSUE TITLE
ACL module should support defaults

### ISSUE THREAD

**Issue by huguesalary** [ansible/ansible#5053]
Using ansible 1.4

I'm trying to set a default acl on a directory.
With the command line tool one would do it this way:

```
setfacl -m d:group:mygroup:rwx directory/
```

so I tried to translate that in an ansible format:

```

---
- name: Setup ACL
  acl: name=/var/www entry="d:group:dev:rwx" state=present
```

But I get this error:

```
Invalid entry: 'd:group:dev:rwx', it requires 3 sections divided by ':'
```

The expected result is: no error should be thrown.

This might not be a bug, per se; according to @bcoca:

```
The module currently doesn't support the 'default' option as some systems seem to have problems with it and I didn't get enough feedback to enable detection (POSIXLY_CORRECT is only usable in systems that actually allow for the default option but disable it). 

so:
- name: Setup ACL
  acl: name=/var/www entry="group:dev:rwx" state=present

will work for the directory but not set the default for all files under it. 
```

**Comment by nervo** [comment]
Or maybe this could be supported as a flag, like "-d" in setfacl command ?

Following this way, a recursive flag (-R in setfacl commant) could also be a great idea !

**Comment by bcoca** [comment]
actually thinking back, if I had added default support now I would be
getting actual useful feedback from those platforms that don't support it.
I'll probably add soon as well as expand on current features.

**Comment by leevs** [comment]
it would be nice indeed to have extra options to set default and recursive.

**Comment by bcoca** [comment]
defaults have been added to current patch, I won't add recursive because it
is too complicated to report state.

**Comment by huguesalary** [comment]
Awesome, thanks for adding default support.

Will you not ever consider adding recursive?

**Comment by bcoca** [comment]
you are welcome to try add it yourself, I won't try unless I can find a way to simplify the implementation

**Comment by huguesalary** [comment]
Fair enough!

**Comment by jctanner** [comment]
This is resolved by https://github.com/ansible/ansible/pull/5363
