### ISSUE TITLE
docker module doesn't map ports for docker >= 0.6.5

### ISSUE THREAD

**Issue by joshuaconner** [ansible/ansible#5054]
The Ansible Docker module depends on [`docker-py`](https://github.com/dotcloud/docker-py) and they haven't released an update since the release of Docker 0.6.5, which introduced breaking changes to how ports are mapped. (I'm not sure it's the right approach, but I'd be willing to try and put together a version that uses the Docker CLI instead of the API if you think that's a better approach.)

**Comment by mpdehaan** [comment]
yay, stability.

Something you wish to work on, perhaps?

Also, how about inserting version checks?

**Comment by joshuaconner** [comment]
I would be interested in working on it, but if you want to keep using docker-py we'd be stuck until they push an update (for this and all updates moving forward, presumably).

**Comment by mpdehaan** [comment]
So it might just be a documentation item we should keep in the docs about
what versions it works with?

**Comment by joshuaconner** [comment]
Could be, until 1.0.

**Comment by cdata** [comment]
I'm glad I checked Issues before I spent any more time on this :beer: for what it is worth, it looks like docker-py expects to have mapped ports passed in the call to [`start`](https://github.com/ansible/ansible/blob/devel/library/cloud/docker#L367) ([method definition](https://github.com/dotcloud/docker-py/blob/master/docker/client.py#L584)).
