### ISSUE TITLE
lookup('ini') parse failure with no value options

### ISSUE THREAD

**Issue by andrewbelcher** [ansible/ansible#50594]
##### SUMMARY
Using the `lookup('ini')` fails if the ini file contains no value options.

##### ISSUE TYPE
- ~Bug Report~
- Feature Request

##### COMPONENT NAME
`lookup('ini')`

##### ANSIBLE VERSION
```
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/andrew/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu.

##### STEPS TO REPRODUCE
Perform a `lookup('ini')` for any file with a valueless option.

E.g.
`/etc/my.cnf`:
```ini
[mysqld]
datadir = /path/to/data

[mysqldump]
quick
```

```yaml
- debug:
    msg: "{{ lookup('ini', 'datadir section=mysqld file=/etc/my.cnf') }}"
```

##### EXPECTED RESULTS
```
TASK [debug]
ok: [ansible-test] => {
    "msg": "/path/to/data"
}
```

##### ACTUAL RESULTS
```
TASK [debug] 
fatal: [ansible-test]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'ini'. Error was a <class 'ConfigParser.ParsingError'>, original message: File contains parsing errors: <???>\n\t[line 5]: u'quick\\n'"}
```

**Comment by andrewbelcher** [comment]
It seems to me the sensible solution is to set the `allow_no_value` option for the parser:

`lib/ansible/plugins/lookup/ini.py::107`
```py
    def run(self, terms, variables=None, **kwargs):

        self.cp = configparser.ConfigParser(allow_no_value=True)
```

**Comment by bcoca** [comment]
so we are leaving this open as a feature request, but you already have a `default` option that will bypass the error for missing keys.  https://docs.ansible.com/ansible/latest/plugins/lookup/ini.html#parameters

**Comment by andrewbelcher** [comment]
Unfortunately that doesn't solve it. The key is in the file and has an unknown value (so can't use a default), but due to the valueless key (which is not the one I'm trying to retrieve), the entire file fails and I get no results.

**Comment by bcoca** [comment]
oh, had misunderstood, the whole file is considered invalid if any key does not have a valid value, its not an issue with the specific key you are trying to retrieve.

**Comment by andrewbelcher** [comment]
Yes, that's correct. The default for `ConfigParser` is to not allow valueless keys, but I can't see how that's advantageous for the lookup and it definitely causes problems.

If we want to keep the existing behaviour, exposing it as an additional optional param would allow you to opt into that behaviour.

**Comment by beneb12** [comment]
Ran into a use case for this and having an additional optional param for `allow_no_value` would've been helpful.

Instead, I made a filter to do exactly that

**Comment by Akasurde** [comment]
resolved_by_pr #74806
