### ISSUE TITLE
shell: rm -r /tmp/

### ISSUE THREAD

**Issue by Xinshiyou** [ansible/ansible#50600]
##### SUMMARY

when I run with ansible the following playbook:
```
- name: install R engine
  script: install-R.sh

- name: remove the installation package after installing
  shell: rm -f /tmp/R-3.2.4.tar.gz

- name: verify if R has been installed successfully
  shell: /usr/local/R-3.2.4/bin/R --version
```
Sometimes , /bin/bash will be deleted . And I will not to login again.

##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```paste below
ansible 2.3.1.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by sivel** [comment]
I cannot see how this is possible, but consider the danger of running `rm` from the shell. 

It is recommended to instead utilize the `file` module for removing files and directories.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
