### ISSUE TITLE
session object has no attribute 'merge

### ISSUE THREAD

**Issue by hairatheeav** [ansible/ansible#50611]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by sivel** [comment]
Duplicate of https://github.com/ansible/ansible/issues/50612
