### ISSUE TITLE
"delegate_to" can run concurrent actions on that host

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#5071]
[ansible 1.4]

If tasks for different inventory hosts use "delegate_to" pointing to the same server, then those tasks are actioned in parallel on the that server, rather than sequentially. This can lead to problems.

Demonstration:

```
# test.inv
localhost ansible_connection=local
[vms]
vm1 vm_server=localhost
vm2 vm_server=localhost
vm3 vm_server=localhost

# test.yml
- hosts: vms
  gather_facts: no
  tasks:
    - shell: sleep 20
      delegate_to: "{{vm_server}}"

$ time ansible-playbook test.yml -i test.inv

PLAY [vms] ********************************************************************

TASK: [shell sleep 20] ********************************************************
changed: [vm1]
changed: [vm3]
changed: [vm2]

PLAY RECAP ********************************************************************
vm1                        : ok=1    changed=1    unreachable=0    failed=0
vm2                        : ok=1    changed=1    unreachable=0    failed=0
vm3                        : ok=1    changed=1    unreachable=0    failed=0


real    0m20.203s
user    0m0.228s
sys 0m0.096s
```

In reality, the actions I want to submit are more like this:

```
- virt: name={{inventory_hostname}} state={{state}}
  delegate_to: "{{vm_server}}"
```

However, libvirt screws up if you issue concurrent overlapping commands that start or stop VMs. I want to ensure that only one command is issued at any one time to any given vm_server.

Workaround: set `serial: 1` in the playbook. But then I lose the ability to have concurrent commands issued for hosts which are delegated to different vm_servers.

**Comment by srgvg** [comment]
I think for now, the only solution is to split out tasks in separate plays.

I have already been thinking it would be nice to be able to define the serial parameter on task level, but that looks quite intrusive, as all the code handles that on playbook level.

FWITW: Use case for me: having to set serial differently for a particular task that is part of a role; now I need to split out that role, which isn't always the logical thing to do, role-wise.

**Comment by mpdehaan** [comment]
Yep, use the "serial: " keyword on a play to control how many to run at a time and this is not a problem.

Basically it's already a language feature in Ansible, so you just need to use it.
