### ISSUE TITLE
setup module fails on Solaris box

### ISSUE THREAD

**Issue by ludovicc** [ansible/ansible#508]
Hello,

I'm running this command targetting a Solaris server:

ansible -u lclaude -m "setup" all
web-c1m1d.sys.dev | FAILED => failed to parse: Traceback (most recent call last):

  File "/home/lclaude/.ansible/tmp/ansible-1340718977.9-92796400099413/setup", line 700, in <module>

```
for (k, v) in ansible_facts().items():
```

  File "/home/lclaude/.ansible/tmp/ansible-1340718977.9-92796400099413/setup", line 614, in ansible_facts

```
get_network_facts(facts)
```

  File "/home/lclaude/.ansible/tmp/ansible-1340718977.9-92796400099413/setup", line 476, in get_network_facts

```
facts['interfaces'] = get_interfaces()
```

  File "/home/lclaude/.ansible/tmp/ansible-1340718977.9-92796400099413/setup", line 448, in get_interfaces

```
'iL', length, names.buffer_info()[0])
```

IOError: [Errno 22] Invalid argument

Here are the characteristics of my server:

uname -a
SunOS web-c1m1d 5.10 Generic_141415-04 i86pc i386 i86pc

Using latest Ansible 0.5 (5362f18e53057065f982872aa513b56ed4c2ff30)

Thanks,
Ludovic

**Comment by mpdehaan** [comment]
Ok, so if you are interested in adding Solaris support, I'd recommend you stop by the mailing list or IRC.   I'm sure there's a small amount of work to do and we can talk about it.   

The core of /usr/bin/ansible should work, though and various people are interested and in various levels of working with BSD.

Very interested in this, though it's not something I would expect to work now or am going to fix, so I'm closing the ticket.  This is not to say I'm not interested in the feature, we just need some people with an interest in getting Solaris to work to make it work :)
