### ISSUE TITLE
templates hide error while trying to find legacy variables

### ISSUE THREAD

**Issue by athoune** [ansible/ansible#5081]
I try to reuse elastic search confgi file, with something like

```
# Any element in the configuration can be replaced with environment variables
# by placing them in ${...} notation. For example:
#
# node.rack: ${RACK_ENV_VAR}
```

`${toto}` is not a Jinja2 variable substitution, but an Ansible legacy.

The legacy hack crash without returning a pertinent error : `IndexError: string index out of range`

If you remove the try/except, a better error bubble up :

```
File "/usr/local/Cellar/ansible/1.4.0/lib/python2.7/site-packages/ansible/utils/template.py", line 105, in _legacy_varFindLimitSpace
if part[0] == '{' and part[-1] == '}':
```

_legacy_varFindLimitSpace should manage it's own try/except block and returning a meaningful error.

This is just a weird edge case, Ansible error wrapping is still very nice.

**Comment by mpdehaan** [comment]
I'm not sure this deals with the legacy variable detector at all, but it's a traceback, and we should fix it.

**Comment by jimi-c** [comment]
@athoune Could you give the following patch a try? I believe this should prevent the above traceback:

<pre>
diff --git a/lib/ansible/utils/template.py b/lib/ansible/utils/template.py
index d5824e8..fd3c48a 100644
--- a/lib/ansible/utils/template.py
+++ b/lib/ansible/utils/template.py
@@ -102,7 +102,7 @@ def _legacy_varFindLimitSpace(basedir, vars, space, part, lookup_fatal, depth, e
     if space is None:
         return space
     # A part with escaped .s in it is compounded by { and }, remove them
-    if part[0] == '{' and part[-1] == '}':
+    if len(part) > 0 and part[0] == '{' and part[-1] == '}':
         part = part[1:-1]
     # Template part to resolve variables within (${var$var2})
     part = legacy_varReplace(basedir, part, vars, lookup_fatal=lookup_fatal, depth=depth + 1, expand_lists=expand_lists)
</pre>

**Comment by athoune** [comment]
it works with the same input. Nice patch!

**Comment by jimi-c** [comment]
Committed and pushed to the development branch, thanks!
