### ISSUE TITLE
Be able to set 'remote_user' at the role level.

### ISSUE THREAD

**Issue by pcarinhas** [ansible/ansible#5084]
Current Ansible version: 1.4.
OS: Ubuntu 12.04
# This is a feature request....

If possible make remote_user templatable at the roles level and the playbook level in the roles declaration:

For example....
In  $ansible/myplay.yml:
# $ansible/myplay.yml

---
- hosts: soliton-db2
  
  roles:
  - { role: network, remote_user: root }
  - { role: common-setup , remote_user: bob }

Also, if possible in $ansible/role/network/tasks/main.yml
will it be possible to have a remote_user directive ? :

---
# $ansible/role/network/tasks/main.yml

remote_user: {{ my_remote_user }}
- name: "{{ role }}: Install python apps that ansible needs"  
  command: yum install -y {{ item }}  
  with_items:  
  - yum-utils  
  - python-paramiko  
  - python-jinja2  
  - libselinux-python  
    changed_when: False

**Comment by mpdehaan** [comment]
So basically this is not about templating, it's a request to be able to set remote_user on the role level and have it automatically apply to included tasks, so I'm updating the caption.

I'm not sure about the part with "vars" here.

the way this is dealt with now is to start a new smaller play.

```
- hosts: soliton-db2
  remote_user: bob
  roles:
      - foo
- hosts: soliton-db2
  remote_user: alice
  roles:
      - bar
```

**Comment by pcarinhas** [comment]
Yes, 

  I appologize for my lack of sematic knowledge. Your solution is works fine
  for me.

The vars issue: $ansible/roles/myrole/vars/main.yml (or elsewhere) was a
request to set remote_user in that file and have it used in the task file at
the role level: $ansible/roles/myrole/tasks/main.yml.

 Thanks.. You can close this if you see no possible action.
 The solution you provided below works for that aspect of my ticket.

## 

 -Phil

---

 Phil Carinhas
 http://zenoss.com
 pcarinhas@zenoss.com
 512-815-2099

**Comment by ava-miket** [comment]
The proposed solution doesn't work if ansible_ssh_user is set in the inventory file (see https://github.com/ansible/ansible/issues/4688).  I need a way to connect to a target server using ansible_ssh_user but run a subset of tasks as a different user (specifically for GitHub checkout).  Being able to specify a different user at the role level, or even task level, would help a lot.

**Comment by drybjed** [comment]
@ava-miket You can use `sudo: True` and `sudo_user: otheruser` to specify different user to run a task or a role.

**Comment by mpdehaan** [comment]
Hi,

We've keeping track of this list but haven't seen any traction here, so are closing this ticket out.  If someone would like to submit a pull request, that would be welcome, and we're still open to it.
