### ISSUE TITLE
ignore_unreachable still runs

### ISSUE THREAD

**Issue by abedwardsw** [ansible/ansible#50946]
##### SUMMARY
When making use of the "ignore_unreachable" the following behavior is observed which I think maybe is incorrect:
1. If your task is a "debug" task, this task still runs on the "unreachable" host.  In my opinion this task should be skipped
2. If you use variables such as ansible_date_time.iso8601 in your task, the playbook will fail for the unreachable_hosts instead of being skipped

Hi, as I believe this is not clearly documented, my "bug report" could be an area of interpretation.  However in my opinion it seems like a bug.   My expectation would be that tasks are skipped if the host is unreachable

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible 2.7.4
  config file = /homenfs/aedwards/a_repo/ansible-linux/ansible.cfg
  configured module search path = [u'/homenfs/aedwards/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION
```
DEFAULT_CALLBACK_WHITELIST(/homenfs/aedwards/a_repo/ansible-linux/ansible.cfg) = [u'profile_tasks', u'timer']
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = [u'/homenfs/aedwards/a_repo/roles']
```

##### STEPS TO REPRODUCE

```yaml
- name: "gather_facts : ansible main play"
  hosts: all
  become: no
  ignore_unreachable: "true"

  tasks:
    - debug: msg="I do not feel this should run on a unreachable host"
      tags: p1

    - debug: msg="this causes the play to fail, should be skipped on unreachable {{ ansible_date_time.iso8601 }}"
      tags: p2

    - name: "set dynamic facts"
      set_fact:
        # this causes the playbook to fail due to ansible_date_time undefined for the unreachable host
        # in my opinion this task should be skipped for unreachable hosts and variables should NOT be evaluated
        gather_facts_last_updated: "{{ ansible_date_time.iso8601 }}"
        cacheable: True
      tags: p3
```

##### EXPECTED RESULTS
In my opinion, 
- the play above should succeed (return a return code == 0) when running against a host which is unreachable.
- instead of printing error message saying "variable is undefined" it should  either completely skip the task or print a message similar to below (like it does when you run a copy task etc..).  I do realize that you can use the "default" filter, however this would mean you would have to go update all tasks that use variables in any of your playbooks you want to skip unreachable hosts, I don't think this is viable
```
fatal: [host]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host lprdamq01v.kaltire.com port 22: Connection timed out\r\n", "skip_reason": "Host lprdamq01v.kaltire.com is unreachable", "unreachable": true}  
```
- debug task should not be run, it should be skipped on unreachable hosts

##### ACTUAL RESULTS
below is the output of running the task against two hosts.  host1 is reachable, host2 is not
```paste below
PLAY [gather_facts : ansible main play] ************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************************************************************************************************************************************
Tuesday 15 January 2019  11:19:24 -0800 (0:00:00.077)       0:00:00.077 *******
ok: [host1]
fatal: [host2]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host host2 port 22: Connection timed out\r\n", "skip_reason": "Host host2 is unreachable", "unreachable": true}

TASK [debug] ***************************************************************************************************************************************************************************************************************************************************************************************************************************************
Tuesday 15 January 2019  11:19:34 -0800 (0:00:10.105)       0:00:10.183 *******
ok: [host1] => {
    "msg": "I do not feel this should run on a unreachable host"
}
ok: [host2] => {
    "msg": "I do not feel this should run on a unreachable host"
}

TASK [debug] ***************************************************************************************************************************************************************************************************************************************************************************************************************************************
Tuesday 15 January 2019  11:19:34 -0800 (0:00:00.084)       0:00:10.268 *******
fatal: [host2]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible_date_time' is undefined\n\nThe error appears to have been in '/tmp/debug.yml': line 15, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - debug: msg=\"this causes the play to fail {{ ansible_date_time.iso8601 }}\"\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
ok: [host1] => {
    "msg": "this causes the play to fail 2019-01-15T19:19:25Z"
}

TASK [set dynamic facts] ***************************************************************************************************************************************************************************************************************************************************************************************************************************
Tuesday 15 January 2019  11:19:34 -0800 (0:00:00.072)       0:00:10.341 *******
ok: [host1]
    to retry, use: --limit @/tmp/debug.retry

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************************************************************************
host2     : ok=1    changed=0    unreachable=1    failed=1
host1       : ok=4    changed=0    unreachable=0    failed=0

Tuesday 15 January 2019  11:19:34 -0800 (0:00:00.041)       0:00:10.382 *******

# return code is failure
[]$ echo $?
2
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The `ignore_unreachable` does exactly what we would expect, ignore the `unreachable` status of a host and attempt to execute subsequent tasks. It is not expected to skip them, the point of the keyword is exactly the opposite, it is there to NOT skip the tasks.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by cohenaj194** [comment]
Is there any way we could create a feature request to create a `skip_unreachable` argument?

**Comment by abedwardsw** [comment]
@cohenaj194 fyi, this was the workaround I did, it's not ideal but it does work.  The only drawback is all of the hosts are listed at the bottom of the play even if they skipped.   It would be nice to have this functionality built in somehow.

ps.. code below not tested as it's a minor variation from what I am using, I wrote a custom plugin which does a actual ping command.  In my situation I want a failure to occur if the host is reachable via ping, but cannot successfully ssh to the host.

```
	#
	# GATHER HOST STATUS
	#
	- name: "host status play"
	  gather_facts: false
	  hosts: "*"

	  tasks:

	    - name: "check host status"
	      ping:
	      register: ping_result

	    # we want to report the hosts as unreachable but still have the play succeed
	    - meta: clear_host_errors

	    # populate host_status_offline group
	    - name: "group by host_status"
	      group_by:
	        key: "host_status_{{ ping_result.ping | default('fail') }}"


	#
	# MAIN PLAY
	#
	- name: "ansible main play"
	  hosts: "host_status_success"

    ....
```

**Comment by abedwardsw** [comment]
also, i'd be happy to contribute the ping module if @bcoca confirms it would be accepted and wanted.  The current ping does a full ssh, i wanted simply a "ping" and couldn't find a module that did that.  there was also a net_ping but that only works from a network device from what I could tell.

**Comment by cohenaj194** [comment]
Yes I agree. A new module to accomplish this would be great!  I found a similar solution as well my results can be found here on `[stackoverflow](https://stackoverflow.com/questions/55188936/ansible-how-to-ignore-unreachable-hosts-ansible-2-6-1)`.

**Comment by danci1973** [comment]
Ansible documentation disagrees (https://docs.ansible.com/ansible/latest/reference_appendices/playbooks_keywords.html):

**ignore_unreachable**
    _Boolean that allows you to ignore unreachable hosts and continue with play. This does not affect other task errors (see ignore_errors) but is useful for groups of volatile/ephemeral hosts._

Why in the world would you try executing tasks on a machine you KNOW is unreachable?
