### ISSUE TITLE
Duplicate role execution when using role dependencies

### ISSUE THREAD

**Issue by hineze** [ansible/ansible#50949]
##### SUMMARY
I opening a new issue because I'm encountering the same issue mentioned in the following ticket: [](https://github.com/ansible/ansible/issues/22169)

I read through the above ticket thread and noticed someone mentioned the issue only crops up when using the new `include_roles` syntax with role dependencies which use the old role syntax.

What is happening is that an already executed role is being run again when a second role later in a playbook has the first role listed as a dependency.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
include_role + role dependencies

##### ANSIBLE VERSION
```
ansible 2.7.5
  config file = /Users/q848555/ansible_tests/ansible.cfg
  configured module search path = ['/Users/q848555/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/q848555/virtualenvs/ansible/lib/python3.7/site-packages/ansible
  executable location = /Users/q848555/virtualenvs/ansible/bin/ansible
  python version = 3.7.1 (default, Dec  2 2018, 20:43:29) [Clang 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/Users/q848555/ansible_tests/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/Users/q848555/ansible_tests/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=120s
CACHE_PLUGIN(/Users/q848555/ansible_tests/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/Users/q848555/ansible_tests/ansible.cfg) = /tmp/facts_cache
CACHE_PLUGIN_TIMEOUT(/Users/q848555/ansible_tests/ansible.cfg) = 7200
DEFAULT_GATHERING(/Users/q848555/ansible_tests/ansible.cfg) = smart
DEFAULT_VAULT_PASSWORD_FILE(/Users/q848555/ansible_tests/ansible.cfg) = /Users/q848555/.ansible-vault-password
HOST_KEY_CHECKING(/Users/q848555/ansible_tests/ansible.cfg) = False
```

##### OS / ENVIRONMENT
MacOSX 10.12.6
Python 3.7.1 (installed via pyenv)

##### STEPS TO REPRODUCE
I created a real simple setup of two roles:

- `test1`
- `test2`

test2 has a role dependency that call test1 

```
cat roles/test2/meta/main.yml 
---
dependencies:
  - { role: test1 }
```

My master playbook that call's both role looks like this:

```
---
- name: run role1
  hosts: localhost
  tasks:
    - include_role:
        name: test1
  tags: ['test1']

- name: run role2
  hosts: localhost
  tasks:
    - include_role:
        name: test2
  tags: ['test2']
```

I run the playbook with the following command:

`ansible-playbook test_role_dep.yml`

##### EXPECTED RESULTS
I expect role test1 to only be executed once and for role test2 to not execute role test1 again since it will have already been run.

##### ACTUAL RESULTS
I've include the actual output below...as you can see role test1 is executed twice 
```
PLAY [run role1] ***********************************************************************************************************

TASK [include_role : test1] ************************************************************************************************

TASK [test1 : debug] *******************************************************************************************************
ok: [localhost] => {
    "msg": "Running role1..."
}

PLAY [run role2] ***********************************************************************************************************

TASK [include_role : test2] ************************************************************************************************

TASK [test1 : debug] *******************************************************************************************************
ok: [localhost] => {
    "msg": "Running role1..."
}

TASK [test2 : debug] *******************************************************************************************************
ok: [localhost] => {
    "msg": "Running role2..."
}

PLAY RECAP *****************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   

```

**Comment by hineze** [comment]
Just wanted to add that I just confirmed that using the old role syntax avoids my issues above, but only if I call the roles in the same play:

Playbook:
```
- name: run both roles
  hosts: localhost
  roles:
   - { role: test1 }
   - { role: test2 }
```

Output:
```
PLAY [run both roles] ******************************************************************************************************

TASK [test1 : debug] *******************************************************************************************************
ok: [localhost] => {
    "msg": "Running role1..."
}

TASK [test2 : debug] *******************************************************************************************************
ok: [localhost] => {
    "msg": "Running role2..."
}

PLAY RECAP *****************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

It still fails with the old syntax if I call each role individually:

Playbook:
```
- name: run role1
  hosts: localhost
  roles:
    - { role: test1 }
  
- name: run role2
  hosts: localhost
  roles:
    - { role: test2 }
```

Output:
```
PLAY [run role1] ***********************************************************************************************************

TASK [test1 : debug] *******************************************************************************************************
ok: [localhost] => {
    "msg": "Running role1..."
}

PLAY [run role2] ***********************************************************************************************************

TASK [test1 : debug] *******************************************************************************************************
ok: [localhost] => {
    "msg": "Running role1..."
}

TASK [test2 : debug] *******************************************************************************************************
ok: [localhost] => {
    "msg": "Running role2..."
}

PLAY RECAP *****************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Two things:

a) duplicate detection is PER PLAY, so it only works for roles imported in the same play, what you observed about them being run in 2 different plays is expected behaviour.

b) include_role by default does allow_duplicates  (documented here https://docs.ansible.com/ansible/latest/modules/include_role_module.html#parameters).  To change this behaviour you should use `allow_duplicates: False`.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by hineze** [comment]
> # Possible Misunderstanding
> Hi!
> 
> Thanks very much for your submission to Ansible. It sincerely means a lot to us.
> 
> We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.
> 
> Two things:
> 
> a) duplicate detection is PER PLAY, so it only works for roles imported in the same play, what you observed about them being run in 2 different plays is expected behaviour.
> 
> b) include_role by default does allow_duplicates (documented here https://docs.ansible.com/ansible/latest/modules/include_role_module.html#parameters). To change this behaviour you should use `allow_duplicates: False`.
> 
> In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
> 
> * https://groups.google.com/forum/#!forum/ansible-project
> 
> Thank you once again for this and your interest in Ansible!

ok, I just tried `allow_duplicates: false`:

Playbook:
````
---
- name: Run all roles
  hosts: localhost
  tasks:
    - include_role:
        name: test1
        allow_duplicates: false
    - include_role:
        name: test2
        allow_duplicates: false
````
Output:
````
PLAY [Run all roles] *******************************************************************************************************

TASK [include_role : test1] ************************************************************************************************

TASK [test1 : debug] *******************************************************************************************************
ok: [localhost] => {
    "msg": "Running role1..."
}

TASK [include_role : test2] ************************************************************************************************

TASK [test1 : debug] *******************************************************************************************************
ok: [localhost] => {
    "msg": "Running role1..."
}

TASK [test2 : debug] *******************************************************************************************************
ok: [localhost] => {
    "msg": "Running role2..."
}

PLAY RECAP *****************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
````

As you can see it still ran role1 twice

**Comment by hineze** [comment]
@bcoca please see what I posted above

**Comment by bcoca** [comment]
it applies to the same role, you are running dependencies x2 which is not prevented, though there might still be a bug with allow_duplicates

**Comment by hineze** [comment]
@bcoca so, should I open a new ticket?

It's possible I'm just misunderstanding the definition of what a play actually is, but if those are two different plays, in what context would I use `allow_duplicates`?

I see a bunch of tickets open related to role duplication, some from ansible 2.1: https://github.com/ansible/ansible/projects/15#card-5167976

With the new role syntax, how are we supposed to use role dependencies?

**Comment by bcoca** [comment]
@hineze the context for `allow_duplicates: no` is the following:

role B depends on role A, role C also depends on role A.
so this play:
``` yaml
roles:
  - b
  - c 
```
would run ABC.  if you set `allow_duplicates: yes` then it would run ABAC.

Thiw was never meant to affect different plays:
```
- hosts: dbserver
  roles:
    - b
- hosts: webservers
  roles:
    - c
```
will run AB and then AC

As for the new syntax it is meant to be used instead of 'dependencies' as they allow you for fine grain control on the roles execution.
