### ISSUE TITLE
unable to resolve inventory_hostname via azure dynamic inventory on windows deployment execution

### ISSUE THREAD

**Issue by DhruvBansal86** [ansible/ansible#50967]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by DhruvBansal86** [comment]
Ansbile version 2.5.1.1
while executing ansible playbook via dynamic inventory of azure failing in resolving inventory_hostname in the wsman url. if i try to resolve hosts via local inventory file it is working absolutly fine

<inventory_hostname> WINRM CONNECT: transport=kerberos endpoint=https://inventory_hostname:5986/wsman
<inventory_hostname> WINRM CONNECTION ERROR: authGSSClientStep() failed: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Server nound in Kerberos database', -1765328377))

If the  File "/home/adminuser/.local/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py",

remote_addr changed in this module to hostname of windows machine, it starts working absolutly fine.

**Comment by mattclay** [comment]
!component =contrib/inventory/azure_rm.py

**Comment by mattclay** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by DhruvBansal86** [comment]
@mattclay can you explain what is the solution please? I am unable to understand from the above reply.

**Comment by mattclay** [comment]
@DhruvBansal86 You can ignore the first comment, `!component =contrib/inventory/azure_rm.py`, as that was intended to instruct our bot how to handle this issue. See my second comment for where you can go to get help on this issue: https://github.com/ansible/ansible/issues/50967#issuecomment-456545748

**Comment by DhruvBansal86** [comment]
@mattclay  i have updated my query on google  groups but no response till date. Can you please suggest/guide some other way?
