### ISSUE TITLE
Error for ansible raw in the network devices

### ISSUE THREAD

**Issue by Printerz** [ansible/ansible#51004]
##### SUMMARY

Error for ansible-raw in the network devices
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

raw
##### ANSIBLE VERSION

```paste below
ansible 2.3.2.0
python 2.7.15
```

##### CONFIGURATION

```paste below
[paramiko_connection]
host_key_auto_add = True

[ssh_connection]
transfer_method = smart
```

##### OS / ENVIRONMENT

HUAWEI S5700 series switch
Red Hat Enterprise Linux Server release 6.8 (Santiago)

##### STEPS TO REPRODUCE

When I enter the following instructions：
```
ansible network_CD-XNM-DSW-1-ITV.CDN-A.CSS.9312 -m raw -a "dis cu" -k 
```
and enter the password, it can't work.
BTW, the switch has already built the ssh connect. 

```yaml

```

##### EXPECTED RESULTS

show the switch's configure.

##### ACTUAL RESULTS

```
network_CD-XNM-DSW-1-ITV.CDN-A.CSS.9312 | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: User Authentication\r\nShared connection to 222.241.35.225 closed.\r\n", 
    "unreachable": true
}
```

```paste below

```

**Comment by Printerz** [comment]
@bcoca

**Comment by mattclay** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible-network on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
