### ISSUE TITLE
Variable of variable doesn't work in  ansible 1.4

### ISSUE THREAD

**Issue by miticojo** [ansible/ansible#5102]
I used to use "hosts" property, in ansible playbook, dinamically for example:

hosts: ${$jobprofile.hosts}

where $jobprofile was an external variable that allow me to change hosts based on profile.

Since last 1.4 version, my previous playbook doesn't works any more.
Have you some suggestion to do an EVAL into a playbook?

Thanks
Giorgio

**Comment by mpdehaan** [comment]
So suggestions and questions should be asked to ansible-project, not github.

I have many questions where "jobprofile.hosts" comes from, so we can discuss there.
