### ISSUE TITLE
New to Ansible, need help writing a playbook

### ISSUE THREAD

**Issue by mguttsait** [ansible/ansible#51037]
##### SUMMARY
Just started using Ansible at my internship this week. Was tasked with the following and need a bit of guidance: 
Create an ansible playbook that goes to directory and deletes files that have, for example, "text" in the name.

##### ISSUE TYPE
I figured I would have to use the file module, but I'm not sure how to incorporate into the playbook. What I mean by this is I'm not sure how to phrase in the playbook that I want it to delete files with a certain name in it.  I'm familiar with how to write a play that deletes files that are over a certain date old, but not sure how to delete ones with a specific name in it. 

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
