### ISSUE TITLE
get_url force=yes does not ignore HTTP 304

### ISSUE THREAD

**Issue by pfalcon** [ansible/ansible#5104]
Ansible 1.4.

I have following task:

```
- name: Download Jenkins plugins which overrides standard
  get_url: url={{item.url}} dest=~jenkins/plugins/{{item.file}} force=yes owner=jenkins
  sudo: yes
  with_items: jenkins_override_plugins
```

Note "force=yes". For reproducibility, I reset file on target system: "echo -n '' > /var/lib/jenkins/plugins/credentials.jpi". Executing that leads to:

```
TASK: [jenkins | Download Jenkins plugins which overrides standard] *********** 
<ec2-174-129-179-83.compute-1.amazonaws.com> REMOTE_MODULE get_url url=http://updates.jenkins-ci.org/download/plugins/credentials/1.9.3/credentials.hpi dest=~jenkins/plugins/credentials.jpi force=yes owner=jenkins
ok: [ec2-174-129-179-83.compute-1.amazonaws.com] => (item={'url': 'http://updates.jenkins-ci.org/download/plugins/credentials/1.9.3/credentials.hpi', 'file': 'credentials.jpi'}) => {"changed": false, "dest": "/var/lib/jenkins/plugins/credentials.jpi", "gid": 0, "group": "root", "item": {"file": "credentials.jpi", "url": "http://updates.jenkins-ci.org/download/plugins/credentials/1.9.3/credentials.hpi"}, "mode": "0644", "msg": "HTTP Error 304: Not Modified", "owner": "jenkins", "size": 0, "state": "file", "uid": 106, "url": "http://updates.jenkins-ci.org/download/plugins/credentials/1.9.3/credentials.hpi"}
```

Ansible clearly sees that target file size is 0, but executes some if-modified HTTP request which manages to return 304, which apparently makes get_url think that update not required.

Well, even if it's target HTTP server's fault, it should be more reliable (again, it's force=yes). I'm going to investigate this in more details and add suggestions/patch.

**Comment by mpdehaan** [comment]
I think I'd suggest if force=yes we don't do this part:

  if last_mod_time:
        tstamp = last_mod_time.strftime('%a, %d %b %Y %H:%M:%S +0000')
        request.add_header('If-Modified-Since', tstamp)

It seems to be done unconditionally.

**Comment by pfalcon** [comment]
Yes, looks like that is the culprit. Any ideas how to handle it? If-Modified-Since maybe useful, so just removing it doesn't feel good. I can think of following ways:
1. Make force multi-value option, and have force=always to skip any "heuristics".
2. Maybe "force=yes" actually should be unconditional force. And optimizations should use different values, e.g. force=mtime.
3. Maybe force should stay boolean (for ease of parsing? ;-) ) and separate param added for optimizing re-downloads, e.g. optimize=mtime.

2 & 3 look better for me, because they allow additional optimization methods.

**Comment by pfalcon** [comment]
E.g. one additional method I'd consider is HEAD request (in case file exists). That would be on average more reliable than If-Modified-Since (at the expense of issues two HTTP request of course). Let's compare on the example of "bad" URL above:

```
$ curl --verbose -L -H "If-Modified-Since: Fri, 29 Nov 2013 22:48:37 GMT" http://updates.jenkins-ci.org/download/plugins/credentials/1.9.3/credentials.hpi
* About to connect() to updates.jenkins-ci.org port 80 (#0)
*   Trying 199.193.196.24... connected
> GET /download/plugins/credentials/1.9.3/credentials.hpi HTTP/1.1
> User-Agent: curl/7.22.0 (i686-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
> Host: updates.jenkins-ci.org
> Accept: */*
> If-Modified-Since: Fri, 29 Nov 2013 22:48:37 GMT
> 
< HTTP/1.1 302 Found
< Date: Fri, 29 Nov 2013 23:25:32 GMT
< Server: Apache/2.2.14 (Ubuntu)
< Location: http://mirrors.jenkins-ci.org/plugins/credentials/1.9.3/credentials.hpi
< Vary: Accept-Encoding
< Content-Length: 344
< Connection: close
< Content-Type: text/html; charset=iso-8859-1
< Set-Cookie: SERVERID=Local; path=/
< 
* Closing connection #0
* Issue another request to this URL: 'http://mirrors.jenkins-ci.org/plugins/credentials/1.9.3/credentials.hpi'
* About to connect() to mirrors.jenkins-ci.org port 80 (#0)
*   Trying 199.193.196.24... connected
> GET /plugins/credentials/1.9.3/credentials.hpi HTTP/1.1
> User-Agent: curl/7.22.0 (i686-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
> Host: mirrors.jenkins-ci.org
> Accept: */*
> If-Modified-Since: Fri, 29 Nov 2013 22:48:37 GMT
> 
< HTTP/1.1 302 Found
< Date: Fri, 29 Nov 2013 23:25:33 GMT
< Server: Apache/2.2.14 (Ubuntu)
< X-MirrorBrain-Mirror: ftp-chi.osuosl.org
< X-MirrorBrain-Realm: other
< Location: http://ftp-chi.osuosl.org/pub/jenkins/plugins/credentials/1.9.3/credentials.hpi
< Vary: Accept-Encoding
< Content-Length: 351
< Connection: close
< Content-Type: text/html; charset=iso-8859-1
< Set-Cookie: SERVERID=Local; path=/
< 
* Closing connection #0
* Issue another request to this URL: 'http://ftp-chi.osuosl.org/pub/jenkins/plugins/credentials/1.9.3/credentials.hpi'
* About to connect() to ftp-chi.osuosl.org port 80 (#0)
*   Trying 64.50.236.52... connected
> GET /pub/jenkins/plugins/credentials/1.9.3/credentials.hpi HTTP/1.1
> User-Agent: curl/7.22.0 (i686-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
> Host: ftp-chi.osuosl.org
> Accept: */*
> If-Modified-Since: Fri, 29 Nov 2013 22:48:37 GMT
> 
< HTTP/1.1 304 Not Modified
< Date: Fri, 29 Nov 2013 23:25:33 GMT
< Server: Apache
< ETag: "5e6d56-560d3-4eaae4541ec80"
< 
* Connection #0 to host ftp-chi.osuosl.org left intact
* Closing connection #0
```

```
$ curl -L -I http://updates.jenkins-ci.org/download/plugins/credentials/1.9.3/credentials.hpi
HTTP/1.1 302 Found
Date: Fri, 29 Nov 2013 23:26:12 GMT
Server: Apache/2.2.14 (Ubuntu)
Location: http://mirrors.jenkins-ci.org/plugins/credentials/1.9.3/credentials.hpi
Vary: Accept-Encoding
Connection: close
Content-Type: text/html; charset=iso-8859-1
Set-Cookie: SERVERID=Local; path=/

HTTP/1.1 302 Found
Date: Fri, 29 Nov 2013 23:26:12 GMT
Server: Apache/2.2.14 (Ubuntu)
X-MirrorBrain-Mirror: ftp-nyc.osuosl.org
X-MirrorBrain-Realm: other
Location: http://ftp-nyc.osuosl.org/pub/jenkins/plugins/credentials/1.9.3/credentials.hpi
Vary: Accept-Encoding
Connection: close
Content-Type: text/html; charset=iso-8859-1
Set-Cookie: SERVERID=Local; path=/

HTTP/1.1 200 OK
Date: Fri, 29 Nov 2013 23:26:12 GMT
Server: Apache
Last-Modified: Fri, 08 Nov 2013 18:08:34 GMT
ETag: "30283e-560d3-4eaae4541ec80"
Accept-Ranges: bytes
Content-Length: 352467
Content-Type: text/plain
```

So, with If-Modified-Since, some servers don't even bother to return Content-Length. But HEAD is gotta return same headers as GET, and we get both Content-Length and Last-Modified.

**Comment by pfalcon** [comment]
After thinking about it a bit more, I grow to favor choice 1 over 2&3 above: it's not KISS to burden user with selecting which "optimizations" to use. Instead, it would make sense to have "best effort" optimizations by default (force=yes), but allow to unconditionally force re-download for extreme cases (force=always).

Then, need to make "force=yes" case be more reliable and trustful. I can think of following algo:
1. Start with "If-Modified-Since" request, as it is now.
2. If we get 200 and content, ok.
3. Otherwise if we got 304, don't trust it right away.
4. Instead, issue HEAD request.
5. Compare size and last-modified time returned by HEAD with file's. (Note: comparing just size is definitely not "best effort").
6. If they don't match, redownload file.
7. For check in step 5 to work, after downloading file by any means, set its mtime per response Last-Modified header. (Note: that's how wget behaves by default, so hopefully that won't cause surprise to anyone.)

Any comments before I start to implement it?

**Comment by mpdehaan** [comment]
From the ticket above, it seems like 304 handling may initiate some extra downloads as well and should be revisited unless force=yes, in which case ignore the 304 logic.

**Comment by ChadScott** [comment]
I'm hitting this same problem. I don't understand how a solution can be identified and nothing happens in two months?

**Comment by ChadScott** [comment]
This is blocking numerous infrastructure updates. I'm attempting to fix it myself, but I don't have a lot of cycles. Is anyone at AnsibleWorks paying attention? Help, please.

**Comment by pfalcon** [comment]
>  I don't understand how a solution can be identified and nothing happens in two months?

Well, I started to make a patch for that issue, but had a baby born, if that explains anything ;-). It's still in my TODO list of course.

**Comment by pfalcon** [comment]
> but I don't have a lot of cycles.

It's the same for everyone, including Ansible maintainers.

> Is anyone at AnsibleWorks paying attention?

Yes, but Ansible is open-source project, so they don't have obligation to fix anything (they have big queue of stuff to do anyway). I actually wouldn't write all this, but I saw some tickets with lot of words and few patches closed as wont-fix, what I hope won't happen here, and hero comes who will fix it ;-).

**Comment by CptMauli** [comment]
Is there now a consensus how the behaviour should actually be? What does @mpdehaan think? Is potentially new behaviour for force ok?

I just quote from my issue #5266:

> What I actually would expect is following:
> - get_url without parameters:
>   - dest=file: look if it exists, then download it only if it isn't there
>   - dest=dir: make head request, figure out file name, check if file exists, then download it only if it isn't there
> - get_url with with force=yes:
>   - dest=file: download file and overwrite it when downloaded
>   - dest=dir: download, figure out file name, then overwrite it
> - get_url with with use_timestamp=yes:
>   - dest=file: make request with file timestamp, download if it does not exist, do nothing if status is 304, else download it again
>   - dest=dir: make head request, figure out filename, download if it does not exist, if it exists make request with file timestamp, on 304 do nothing, else download it again

that would mean that force=yes & use_timestamp are somewhat mutual exclusive, but it also means that the existing playbooks still work.

@pfalcon: did you actually start with the patch? I could implement my proposal if we come to an agreement.

**Comment by jimi-c** [comment]
@pfalcon @ChadScott I've pushed up the above commit to my branch, if either of you'd like to test it to confirm it fixes the issue for you. In my testing, it is successfully downloading the file, but since the md5's haven't changed the module is still reporting changed=false.
