### ISSUE TITLE
test-module: ImportError: No module named ansible.utils

### ISSUE THREAD

**Issue by r0bj** [ansible/ansible#5105]
Running ansible/hacking/test-module generates error:

```
Traceback (most recent call last):
  File "ansible/hacking/test-module", line 36, in <module>
    import ansible.utils as utils
ImportError: No module named ansible.utils
```

ansible version 1.4

**Comment by mpdehaan** [comment]
How are you running it?

It sounds like you need to source ./hacking/env-setup first if you haven't installed Ansible.

**Comment by mpdehaan** [comment]
Actually, I'm 99.999999999% positive that is what this is, so I'm closing the ticket.  Let me know if that's not the case.

**Comment by r0bj** [comment]
Thanks, env-setup solves the problem.
