### ISSUE TITLE
vagrant installation of Ansible tower

### ISSUE THREAD

**Issue by ramyakailas** [ansible/ansible#51078]
##### SUMMARY

The vagrant installation of Ansible Tower as pointed to by the docs installs version 3.3.2 instead of version 3.4.0

##### ISSUE TYPE
- Documentation Report
vagrant image has not been updated to install tower version 3.4.0 as pointed to by https://docs.ansible.com/ansible-tower/latest/html/quickinstall/download_tower.html#using-vagrant-amazon-ami-images
##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

**Comment by nqb** [comment]
The latest version available on Vagrant Cloud is 3.3.3: https://app.vagrantup.com/ansible/boxes/tower

**Comment by ramyakailas** [comment]
Right, but the Tower installation docs https://docs.ansible.com/ansible-tower/latest/html/quickinstall/download_tower.html#using-vagrant-amazon-ami-images indicate that you can install the latest version of 3.4.0 using Vagrant

**Comment by sivel** [comment]
This repository is for the open source Ansible project, and not Tower or AWX.

For Tower support, please reach out to your support team.

For AWX, please use https://github.com/ansible/awx
