### ISSUE TITLE
include_vars not compatible with with_first_found 

### ISSUE THREAD

**Issue by aabdnn** [ansible/ansible#5108]
I'm on ansible 1.4.1, and trying to use include_vars: for a role called "firewall". I have:

firewall/tasks/main.yml, which starts with:

---
- include_vars: '{{item}}'
  with_first_found:
  - "{{ansible_hostname}}.yml"
  - default.yml

Then I have firewall/vars/default.yml and firewall/vars/HOSTNAME.yml, where HOSTNAME is my hostname.

However, when I include this role in a playbook and run it, I get:

PLAY [localhost] *************************************************************\* 

GATHERING FACTS ***************************************************************

ok: [localhost]

TASK: [firewall | include_vars ] *********************************************\* 

fatal: [localhost] => input file not found at /Users/anandb/git/gii-ansible/playbooks/roles/firewall/vars/None or /Users/anandb/git/gii-ansible/playbooks/None

FATAL: all hosts have already failed -- aborting

**Comment by mpdehaan** [comment]
This doesn't have anything to do with roles, so I'm editing the description.

**Comment by mpdehaan** [comment]
This might extend to lookup plugins in general, but this of course is easier written as "vars_files" anyway, just in roles context, you don't have that available.

**Comment by mpdehaan** [comment]
So lookup plugins natively look in the "files/" subdirectory, so if you change this to say:

```
- include_vars: '{{item}}' 
   with_first_found:
       "../vars/{{ansible_hostname}}.yml"
```

etc, things will be fine.

(This thing was more designed for basic conditionals, etc, like adding a "when" on the include, etc, and in that case you don't have to worry about it)
