### ISSUE TITLE
module synchronize ignores variable ansible_ssh_port

### ISSUE THREAD

**Issue by r0bj** [ansible/ansible#5109]
I have a host in the inventory:

`c01 ansible_ssh_port=22002 ansible_ssh_host=tunnel01`

I use synchronize module:
`synchronize: src=some/relative/path dest=/some/absolute/path`

Error is generated:

```
failed: [c01] => {"cmd": "rsync --delay-updates --compress --timeout=10 --delete-after --archive --rsh 'ssh  -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' path user@tunnel01:/some/absolute/path", "failed": true, "item": "", "rc": 12}
```

I verified it by tcpdump on host tunnel01, ansible is trying to make rsync connection via ssh on default port 22 ignoring variable ansible_ssh_port.

I use ansible 1.4.

**Comment by miticojo** [comment]
I confirm what you reported. I'm testing docker container locally with custom ssh ports and doesn't work.

**Comment by jctanner** [comment]
@r0bj and @miticojo please retest against the latest commit. File new bugs as needed.
