### ISSUE TITLE
Handling more error type in template

### ISSUE THREAD

**Issue by athoune** [ansible/ansible#5114]
Two days to fix a simple typo, a vicious one. Here is the line, in a tasks/main.yml file

```
- name: graphite conf
  template: src=local_settings.py.j2 dest=/opt/graphite/graphite-web-{{graphite-version}}/webapp/graphite/local_settings.py
```

the raised error is cryptic :

```
fatal: [default] => Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.4.0/lib/python2.7/site-packages/ansible/runner/__init__.py", line 394, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/Cellar/ansible/1.4.0/lib/python2.7/site-packages/ansible/runner/__init__.py", line 485, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/Cellar/ansible/1.4.0/lib/python2.7/site-packages/ansible/runner/__init__.py", line 672, in _executor_internal_inner
    module_args = template.template(self.basedir, module_args, inject, fail_on_undefined=self.error_on_undefined_vars)
  File "/usr/local/Cellar/ansible/1.4.0/lib/python2.7/site-packages/ansible/utils/template.py", line 320, in template
    varname = template_from_string(basedir, varname, vars, fail_on_undefined)
  File "/usr/local/Cellar/ansible/1.4.0/lib/python2.7/site-packages/ansible/utils/template.py", line 543, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 10, in root
TypeError: unsupported operand type(s) for -: 'dict' and 'StrictUndefined'
```

I wrongly suspected the template file. Copypasting a sample config file and adding some `{{ my.variable }}` is always risky.

Error thrown from template evaluation (templates task and, more important, task evaluation itself), should be wrapped, and thrown with a context.

The error here, is just a `-` instead of a `.`

If the content of file `<template>` is displayed, I can fix the typo easily.

Same behavior with a file template. Involved functions are in ansible/utis/template.py `template_from_string`and `template_from_file`.

**Comment by mpdehaan** [comment]
This error message does reflect a problem in the template on your end as an undefined variable can't be used in math operations.  

I'd prefer to discuss what you expect the user visible behavior to be rather than diving into a code discussion.  "Thrown with context" doesn't really help me understand what you expect to see in this case.

Since you have seemed to dive into source and seem to know about what you want in Jinja, some how about a pull request?

**Comment by athoune** [comment]
With a template related error, I would like to watch the template, directly, or a link to it.

Yes, I dive into source, and I can suggest a fix, and pull request it.

Thanks for your blazing fast answer.

**Comment by mpdehaan** [comment]
So obviously a bit of time passes here.  The fix seems to just be to catch this error and raise a nice errors.AnsibleError when we have a TypeError and the message of the error contains StrictUndefined - "one of more variables is undefined" or something similar, if we don't have more detail.

**Comment by risaacson** [comment]
@athoune Your error is now being caught on lib/ansible/runner/action_plugins/template.py:90 as @mpdehaan suggests.

'''
fatal: [test] => {'msg': "unsupported operand type(s) for -: 'StrictUndefined' and 'StrictUndefined'", 'failed': True}
fatal: [test] => {'msg': "unsupported operand type(s) for -: 'StrictUndefined' and 'StrictUndefined'", 'failed': True}
'''

**Comment by mpdehaan** [comment]
I was actually proposing a better error message than the above.

**Comment by jimi-c** [comment]
It does appear again that this message was tweaked as part of 8752ae69, however I added a bit more to it to suggest how to resolve the issue.
