### ISSUE TITLE
ansible.cfg lookup (edit: doesn't match docs)

### ISSUE THREAD

**Issue by techtonik** [ansible/ansible#5115]
According to http://www.ansibleworks.com/docs/intro_configuration.html#the-ansible-configuration-file, `ansible.cfg` in the playbook directory should override any other file, but that doesn't happen, because instead of playbook's directory, `ansible.cfg` is read from current dir.

It happens, because `ansible.cfg` lookup is made during constants import [1], before command line arguments are processed [2] and playbook location is detected. The solution is to reread configuration explicitly once playbook location is known.
1. https://github.com/ansible/ansible/blob/devel/lib/ansible/constants.py#L80
2. https://github.com/ansible/ansible/blob/devel/bin/ansible-playbook#L26

**Comment by mpdehaan** [comment]
This is a docs report, "the playbook directory" should be changed to "the working directory" in the docs.

The code that matches this is correct so it's just a clarification:

```
p = ConfigParser.ConfigParser()
path1 = os.getcwd() + "/ansible.cfg"
path2 = os.path.expanduser(os.environ.get('ANSIBLE_CONFIG', "~/.ansible.cfg"))
path3 = "/etc/ansible/ansible.cfg"
```

**Comment by techtonik** [comment]
Actually the documented way is preferable https://groups.google.com/d/msg/ansible-project/FGLYRptFdPk/RPQdj5itd5oJ even though it is a little tricky to implement - needs ability to reload constants.

**Comment by nijotz** [comment]
#4976 is a duplicate

**Comment by techtonik** [comment]
I am working on it in https://github.com/techtonik/ansible/compare/5115-config-reload - fix is already operational. Current work is to make all constants reloadable - move their initialization inside `load_constants()` function.

**Comment by techtonik** [comment]
Pull request to fix this issue: https://github.com/ansible/ansible/pull/5184

**Comment by mpdehaan** [comment]
Docs have already been tweaked to match the above.   Will review PR seperately.
