### ISSUE TITLE
changed_when and "error while evaluating conditional"

### ISSUE THREAD

**Issue by alledm** [ansible/ansible#5117]
Hello,

I am trying to override the "changed_when" behaviour of the git module, which reports as changed even if a non-related branch has been updated.

I have the following task

```
tasks:
    - name: Running "git pull" on the repository (branch/commit = "{{ branch }}")
      git: repo=git@github.com:project.git dest={{ destination }} version={{ branch }}
      async: 360
      poll: 5
      register: result
      changed_when: "result.after != result.before"
```

but when I run it, I get:

``````
fatal: [staging] => error while evaluating conditional: result.after != result.before

FATAL: all hosts have already failed -- aborting```

It looks as if when the evaluation happens, the variables are still not visible or defined.
I can print/debug each of the just fine.


Using ansible 1.5 latest code

regards
Alessandro

*edited*: changed the phrase "when_changed" to "changed_when" -- MPD
``````

**Comment by mpdehaan** [comment]
So this ticket is actually about "changed_when" so I'm updating the caption.

**Comment by mpdehaan** [comment]
You should probably add debug lines to see what is in result:

```
- name: Running "git pull" on the repository (branch/commit = "{{ branch }}")
  git: repo=git@github.com:project.git dest={{ destination }} version={{ branch }}
  async: 360
  poll: 5
  register: result
- debug: var=result
```

remove the changed when, try that (run with -v), and let us know what you find out?

(I suspect this is more of an async compatibility thing, where this might need to wait until poll is done or something)

Thanks!

**Comment by ghost** [comment]
here!

```
TASK: [Debug] ***************************************************************** 
ok: [staging] => {
    "msg": "{u'after': u'98110a426ab4c10bdebf06b1fa0396ec7e6012ce', u'ansible_job_id': u'356291593582', u'changed': False, u'finished': 1, 'invocation': {'module_name': 'async_status', 'module_args': u'jid=356291593582'}, u'before': u'98110a426ab4c10bdebf06b1fa0396ec7e6012ce'}"
}
```

**Comment by mpdehaan** [comment]
So this does produce a before/after in this case, I suspect it may be evaluating the conditional before the result is complete.  Still in queue to investigate.

**Comment by ghost** [comment]
Removing async made it work btw. Thank you!

**Comment by jimi-c** [comment]
The above patch should resolve this issue when run with async. Please let us know if you continue to have any problems with this. Thanks!
