### ISSUE TITLE
Tags mode, and/or?

### ISSUE THREAD

**Issue by jhogendorn** [ansible/ansible#5118]
It would be very useful to be able to specify the method in which the tag selection happens, whether its an and operation or and or operation. IE
- all tasks that have either `foo` or `bar` (current implementation I believe)
- only tasks that have both `foo` and `bar`

This would enable nice set ups where you could do:

```
# deploy configuration changes of various types
ansible-playbook mybook.yml --tags=deploy,config --tagmode=and
ansible-playbook mybook.yml --tags=deploy,database --tagmode=and

# Install various apps out of the playbook.
ansible-playbook mybook.yml --tags=appnamefoo,appnamebar --tagmode=or
```

Syntax wise, the most powerful would be supporting `&`, `|` and `()`. Not sure if thats particularly user friendly.

```
ansible-playbook mybook.yml --tags=install&(appnamefoo|appnamebar)
```

**Comment by mpdehaan** [comment]
Ansible already has conventions that ":" means or and ":&" means and, and ":!" means not, it's unlikely to support set ops because it would be inconsistent to introduce that.

Marking this as a feature request, it's not something we're going to do anytime soon, so someone is free to take this provided tag matching works like the rest of Ansible

**Comment by jhogendorn** [comment]
Thanks for the reply @mpdehaan, if its not too much trouble could you elaborate on the conventions you mentioned? Is this mentioned in the ansible docs?

**Comment by mpdehaan** [comment]
yes

**Comment by mpdehaan** [comment]
Hi,

We've keeping track of this list but haven't seen any traction here, so are closing this ticket out.  If someone would like to submit a pull request, that would be welcome, and we're still open to it.
