### ISSUE TITLE
reboot command causes a parse error due to broadcast message

### ISSUE THREAD

**Issue by nicolaasuni** [ansible/ansible#513]
If the "action: command reboot" is present on a playbook, the next instruction crashes runner.py and print fatal error.
I haven't found any way to make ansible to wait until the host complete the reboot. What I am missing?

**Comment by mpdehaan** [comment]
You didn't share the actual output or the full command you ran, which you should always do when submitting a ticket.

That being said, I can pretty much be sure it's the "this system is shutting down now" message, which it would require some hijinks in the parser to remove those lines.   I have resisted doing this earlier but I guess I can accept a patch for it.

As for waiting for it to come back, that won't be something playbooks can support and will require using the API.

**Comment by mpdehaan** [comment]
Didn't mean to close this.  Another option is to see if the reboot command can be fed an option to not send the "going down now" message to the current PTY (or all of them).

**Comment by go2sh** [comment]
I did some investigation on this. Rebooting via ConsoleKit might be a solution. Send a message via dbus-send. Running the following command with the command module

```
dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart
```

will output

```
RAW OUTPUT
{"changed": true, "end": "2012-08-08 17:37:38.308046", "stdout": "method return sender=:1.9 -> dest=:1.39 reply_serial=2", "cmd": ["dbus-send", "--system", "--print-reply", "--dest=org.freedesktop.ConsoleKit", "
/org/freedesktop/ConsoleKit/Manager", "org.freedesktop.ConsoleKit.Manager.Restart"], "start": "2012-08-08 17:37:38.295475", "delta": "0:00:00.012571", "stderr": "", "rc": 0}


***********************************
PARSED OUTPUT
{
    "changed": true, 
    "cmd": [
        "dbus-send", 
        "--system", 
        "--print-reply", 
        "--dest=org.freedesktop.ConsoleKit", 
        "/org/freedesktop/ConsoleKit/Manager", 
        "org.freedesktop.ConsoleKit.Manager.Restart"
    ], 
    "delta": "0:00:00.012571", 
    "end": "2012-08-08 17:37:38.308046", 
    "rc": 0, 
    "start": "2012-08-08 17:37:38.295475", 
    "stderr": "", 
    "stdout": "method return sender=:1.9 -> dest=:1.39 reply_serial=2"
}
```

so ansible will not fail.

**Comment by mpdehaan** [comment]
Nice!  Might be something to put in the FAQ.  I'll add a ticket shortly.  

We also already have ignore_errors: True that will not fail the playbook (new in 0.7)

**Comment by mpdehaan** [comment]
correction: I mean new in 0.6

**Comment by go2sh** [comment]
So u can close this ticket. I will add a link to the faq to Arch Linux wiki. There is a nice article describing howto shutdown, reboot, etc. with dbus-send.
