### ISSUE TITLE
ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by rajasaur** [ansible/ansible#5146]
This has been reported in #3518 by @hngkr. 

When running a playbook through celery, the fix for #3518 results in a ValueError: I/O Operation on closed file. 

```
fatal: [centos] => Traceback (most recent call last):
  File "/sources/projects/virtualenvs/customdeploy/ansible/lib/ansible/runner/__init__.py", line 390, in _executor
    self._new_stdin = os.fdopen(os.dup(sys.stdin.fileno()))
ValueError: I/O operation on closed file
```

If I comment out the fix related to #3518, all works fine(through celery task as well as command line).  

Copying the test playbook referenced in the other issue:

```

---
# file: site1.yml
- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  tasks:
  - copy: src="/tmp/blarg" dest="/tmp/blob"
```

**Comment by mpdehaan** [comment]
This appears unrelated to the linked ticket.

**Comment by mpdehaan** [comment]
edit: ah, I see you are saying this line of code is causing the problem.   Interesting, we don't get this when people are running Ansible through Jenkins.   We can take a look.

**Comment by jctanner** [comment]
@rajasaur how are you calling ansible-playbook from celery? Is it importing the ansible libraries or is it running shell commands?

**Comment by jctanner** [comment]
I'm not able to reproduce the error by calling ansible-playbook with subprocess.Popen from a celery task.

**Comment by hngkr** [comment]
I'm seeing the error when I'm creating an ansible.playbook.PlayBook and
running it - I looked at the code in ansible-playbook and mimicked that in
a Celery task.

When that playbook contains copy tasks, then I'm hitting this error (unless
I uncomment the reload(sys) function call). It's just the copy
module/command that fails - everything else executes as expected.

2014/1/2 jctanner notifications@github.com

**Comment by jctanner** [comment]
@hngkr I'm going to need more information, such as an example of your celery task. I just replicated ansible-playbook as a celery task and did not see anything related to the error you and @rajasaur have mentioned.

This is my testcase: https://gist.github.com/jctanner/8229044

**Comment by rajasaur** [comment]
@jctanner , I needed to do it by importing the ansible playbook module and invoking run on it. Here is how I did it.

```
                       pb = ansible.playbook.PlayBook(
                                    playbook=playbook_file,
                                    inventory=inventory,
                                    callbacks=playbook_cb,
                                    stats=stats,
                                    runner_callbacks=runner_cb,
                                    extra_vars={ 'patchfile': patch_path },
                                    )
                        pb.run()
```

The reason I had to do it this way was beacuse of the custom callbacks(playbook_cb) since I was passing some data to the Callbacks' init method and processing results based on the sucess/failure of tasks.

**Comment by rajasaur** [comment]
@jctanner: Produced a repro case using a similar gist like yours: https://gist.github.com/rajasaur/8232504

**Comment by jctanner** [comment]
@rajasaur thank you, that really helped me get into something I could debug. Try this patch:

```
diff --git a/lib/ansible/runner/__init__.py b/lib/ansible/runner/__init__.py
index 3318bcb..105ac82 100644
--- a/lib/ansible/runner/__init__.py
+++ b/lib/ansible/runner/__init__.py
@@ -405,7 +405,12 @@ class Runner(object):
             return flags

         try:
-            if not new_stdin:
+            fileno = sys.stdin.fileno()
+        except ValueError:
+            fileno = None
+
+        try:
+            if not new_stdin and fileno is not None:
                 self._new_stdin = os.fdopen(os.dup(sys.stdin.fileno()))
             else:
                 self._new_stdin = new_stdin
```

**Comment by rajasaur** [comment]
@jctanner Thanks for the quick fix, works for me. I will test this on my other project as well.

**Comment by vpuech** [comment]
Hello the patch fixed the issue for a single host but if i execute the same thing for multiple hosts it pop the error again.
Outside of Celery, everything work great:

```
import ansible.runner
runner = ansible.runner.Runner(
   module_name  = "copy",
   module_args  = "src=/tmp/ansibletest dest=/tmp/ansibletest",
   pattern      = "*"
)
results = runner.run()
```

**Comment by jctanner** [comment]
@vpuech "for multiple hosts" ... what does this mean? Are you trying to say that an inventory with more than one host will still get the error?

**Comment by vpuech** [comment]
Yes, sorry, i have multiple host in my inventory.

**Comment by jctanner** [comment]
@vpuech please open a new bug, referencing this one.
