### ISSUE TITLE
sshd in debug mode causes parsing error

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#5147]
```
#client
$(which sshd) -p 22002 -d -D
```

```
$ fgrep el6 inventory 
el6.lab.net ansible_ssh_user=root ansible_ssh_port=22002
```

```
$ cat site.yml 
- hosts: el6.lab.net
  gather_facts: False
  tasks:
    - shell: whoami
```

jtanner@u1304:~/issues/5109-synchronize-ssh-port$ ansible-playbook -vvvv -c ssh -i inventory site.yml 

PLAY [el6.lab.net] ***********************************************************\* 

TASK: [shell whoami] *********************************************************\* 
<el6.lab.net> ESTABLISH CONNECTION FOR USER: root
<el6.lab.net> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jtanner/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22002', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'el6.lab.net', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1386095900.22-225343375423501 && chmod a+rx $HOME/.ansible/tmp/ansible-1386095900.22-225343375423501 && echo $HOME/.ansible/tmp/ansible-1386095900.22-225343375423501'"]
<el6.lab.net> REMOTE_MODULE command whoami #USE_SHELL
<el6.lab.net> PUT /tmp/tmpId8nGU TO /root/.ansible/tmp/ansible-1386095900.22-225343375423501/command
<el6.lab.net> PUT /tmp/tmp2U5YaH TO /root/.ansible/tmp/ansible-1386095900.22-225343375423501/arguments
<el6.lab.net> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jtanner/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22002', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'el6.lab.net', "/bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-1386095900.22-225343375423501/command /root/.ansible/tmp/ansible-1386095900.22-225343375423501/arguments; rm -rf /root/.ansible/tmp/ansible-1386095900.22-225343375423501/ >/dev/null 2>&1'"]
fatal: [el6.lab.net] => failed to parse: debug1: PAM: reinitializing credentials
debug1: permanently_set_uid: 0/0
Environment:
  LANG=en_US.UTF-8
  USER=root
  LOGNAME=root
  HOME=/root
  PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
  MAIL=/var/mail/root
  SHELL=/bin/bash
  SSH_CLIENT=192.168.1.105 50888 22002
  SSH_CONNECTION=192.168.1.105 50888 192.168.1.148 22002
  SSH_TTY=/dev/pts/1
  TERM=xterm-256color
  RAILS_ENV=foo
{"changed": true, "end": "2013-12-03 13:38:18.844674", "stdout": "root", "cmd": "whoami ", "start": "2013-12-03 13:38:18.837017", "delta": "0:00:00.007657", "stderr": "", "rc": 0}

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/home/jtanner/site.retry

el6.lab.net                : ok=0    changed=0    unreachable=1    failed=0  

```
```

**Comment by jctanner** [comment]
Marked as priority because it may prevent further debugging of #5082 or similar ssh related issues.

**Comment by mpdehaan** [comment]
Curious why it got a fatal here when it returned 0, might be worth debugging around that.

**Comment by jctanner** [comment]
paramiko handles the connection without error.

**Comment by jctanner** [comment]
If I copy ssh.py to ssh-debug.py and call ansible playbook with -c ssh-debug, the error disappears.

**Comment by jctanner** [comment]
Looks like stderr is leaking into the stdout ...

```
debug1: PAM: reinitializing credentials
debug1: permanently_set_uid: 0/0
Environment:
  LANG=en_US.UTF-8
  USER=root
  LOGNAME=root
  HOME=/root
  PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
  MAIL=/var/mail/root
  SHELL=/bin/bash
  SSH_CLIENT=192.168.1.105 52300 22002
  SSH_CONNECTION=192.168.1.105 52300 192.168.1.148 22002
  SSH_TTY=/dev/pts/1
  TERM=xterm-256color
  RAILS_ENV=foo
{"changed": true, "end": "2013-12-04 22:48:25.864783", "stdout": "root", "cmd": "whoami ", "start": "2013-12-04 22:48:25.857101", "delta": "0:00:00.007682", "stderr": "", "rc": 0}
```

A quick workaround is to chop off the last line in runner's _low_level_exec_command ....

```
        rc, stdin, stdout, stderr = conn.exec_command(cmd, tmp, sudo_user, sudoable=sudoable, executable=executable)
        if len(stdout.strip().split('\n')) > 1:
            #import epdb; epdb.st()
            stdout = stdout.strip().split('\n')[-1]
        else:
            open("/tmp/awx.log", "a").write("%s\n" % stdout.strip())
```

**Comment by jctanner** [comment]
If stderr is properly redirected, stdout is clean ...

```
jtanner@u1304:~$ ssh -o Port=22002 root@el6.lab.net "/bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-1386251817.84-149618603536506/command'"
debug1: PAM: reinitializing credentials
debug1: permanently_set_uid: 0/0
Environment:
  LANG=en_US.UTF-8
  USER=root
  LOGNAME=root
  HOME=/root
  PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
  MAIL=/var/mail/root
  SHELL=/bin/bash
  SSH_CLIENT=192.168.1.105 52363 22002
  SSH_CONNECTION=192.168.1.105 52363 192.168.1.148 22002
  RAILS_ENV=foo
{"changed": true, "end": "2013-12-05 08:59:46.445014", "stdout": "root", "cmd": "whoami ", "start": "2013-12-05 08:59:46.437141", "delta": "0:00:00.007873", "stderr": "", "rc": 0}

jtanner@u1304:~$ ssh -o Port=22002 root@el6.lab.net "/bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-1386251817.84-149618603536506/command'" 2>/dev/null
{"changed": true, "end": "2013-12-05 09:00:22.781118", "stdout": "root", "cmd": "whoami ", "start": "2013-12-05 09:00:22.772978", "delta": "0:00:00.008140", "stderr": "", "rc": 0}
```

**Comment by jctanner** [comment]
@iffy do you have any thoughts here?

**Comment by jctanner** [comment]
Removing priority tag since we have fixed #5082

**Comment by iffy** [comment]
@jctanner I don't have any thoughts, but if I get some time I could investigate.

**Comment by mpdehaan** [comment]
I don't think we'll be able to do anything here, so I'm going to close this one.  We do need a clean SSH channel for operations.
