### ISSUE TITLE
apt does not honor update_cache

### ISSUE THREAD

**Issue by ronansalmon** [ansible/ansible#51489]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible/lib/python2.7/site-packages/ansible/modules/packaging/os/apt.py

##### ANSIBLE VERSION

```
ansible 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /home/ansible/ansible/lib/python2.7/site-packages/ansible
  executable location = /home/ansible/ansible/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION
- Default

##### OS / ENVIRONMENT
- Debian GNU/Linux 9

##### SUMMARY
I need to install a custom .deb and for some internal reason some repositories are not working, so I do not want 'apt-get update' to be ran. So, here is my task : 
```
- name: Install package
  apt:
    update_cache: false
    deb: '/root/local_package_amd64.deb'
    state: present
```
when I run the playbook, it seams that ansible is always trying to update the apt cache.
fatal: [hostanem]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "W:....."]}

The issue seams to come from the module : apt (modules/packaging/os/apt.py)
```
    if not HAS_PYTHON_APT:
        if module.check_mode:
            module.fail_json(msg="%s must be installed to use check mode. "
                                 "If run normally this module can auto-install it." % PYTHON_APT)
        try:
            module.run_command(['apt-get', 'update'], check_rc=True)
            module.run_command(['apt-get', 'install', '--no-install-recommends', PYTHON_APT, '-y', '-q'], check_rc=True)
```
We can see that if python-apt is not installed, it will run apt-get update no matter what.
ansible should honor update_cache/cache_valid_time variables

**Comment by resmo** [comment]
resolved_by_pr #56549
