### ISSUE TITLE
ansible-pull pulls an odd commit.

### ISSUE THREAD

**Issue by skorokithakis** [ansible/ansible#5161]
I have ansible-pull that updates a repo, with no branch specified. If I specify "develop", it correctly checks out the HEAD of develop. If I don't specify a branch, it checks always out a specific, weird old commit and stays there. I looked at the source, but it's just using the git module to pull, and I'm not sure why it would default to that commit. Would anyone have any insight on this?

**Comment by mpdehaan** [comment]
Please paste the command line invocation you are using and any relevant output.

**Comment by mpdehaan** [comment]
also ansible --version.

**Comment by skorokithakis** [comment]
Ansible is 1.3. This is what happens:

Branch is on develop, and running the following command takes the repo around 40 commits back:

```
$ ansible-pull -o -d /var/project/code -i /var/project/code/hosts -U git@bitbucket.org:user/project.git
Starting ansible-pull at 2013-12-05 12:34:46
Running: 'ansible all -c local -i "localhost," --limit "localhost:staging.project.com:127.0.0.1" -m git -a "repo=git@bitbucket.org:user/project.git dest=/var/project/code version=HEAD"'
localhost | success >> {
    "after": "dd4c6d1", 
    "before": "cc0223a", 
    "changed": true
}
```

Using the `-C develop` argument brings it back to develop HEAD:

```
$ ansible-pull -o -C develop -d /var/project/code -i /var/project/code/hosts -U git@bitbucket.org:user/project.git
Starting ansible-pull at 2013-12-05 12:35:20
Running: 'ansible all -c local -i "localhost," --limit "localhost:staging.project.com:127.0.0.1" -m git -a "repo=git@bitbucket.org:user/project.git dest=/var/project/code version=develop"'
localhost | success >> {
    "after": "cc0223a", 
    "before": "dd4c6d1", 
    "changed": true
}
```

I have done all sorts of things to the repo, including remove and re-clone it, but this still happens. Ansible just checks out that specific commit if I don't manually specify "develop".

Looking at the output now, `version=HEAD` may be a hint. Which HEAD does it mean?

**Comment by skorokithakis** [comment]
With some extra investigation, it seems that this isn't ansible-related, I think:

```
stavros@staging /v/p/code> git show-ref --head | grep dd4
dd4c6d1d18ff8e8bb881934ab22eea5883892381 refs/heads/master
dd4c6d1d18ff8e8bb881934ab22eea5883892381 refs/remotes/origin/HEAD
dd4c6d1d18ff8e8bb881934ab22eea5883892381 refs/remotes/origin/master
```

**Comment by skorokithakis** [comment]
It looks like HEAD is just the head of whatever branch we set the BitBucket repo to. I'm guessing Ansible's default behaviour (can it be configured?) is to just check out the HEAD of the repo, rather than the HEAD of the current branch?

I'd prefer that, if `-C` were not specified, ansible would just do (or act like it does) a simple git-pull.

**Comment by mpdehaan** [comment]
You have to specify what to checkout .

HEAD in git means the head of the default branch, and is correct.

The documentation for "-c" is as follows:

  parser.add_option('-C', '--checkout', dest='checkout',
                      help='branch/tag/commit to checkout.  '
                      'Defaults to behavior of repository module.')

Sounds like you want to specify "-C foo" if you want to check out what is the latest on foo, rather than saying "-C HEAD".

I'm closing this one because it's doing what you asked it to do.

**Comment by skorokithakis** [comment]
I want to do the equivalent of a "git pull", because I can't easily specify what I want to pull. I just want to get the latest commits in the branch I'm already on. Is there a way to do that?
