### ISSUE TITLE
fetch module: with sudo fails when files are 300kb+ from 4+ hosts

### ISSUE THREAD

**Issue by jhawk28** [ansible/ansible#5164]
in Ansible 1.4, fetch with sudo fails on large files when retrieving from 4+ hosts. Receives error of "No closing quotation"

**Comment by jctanner** [comment]
@jhawk28 is this only happening when using sudo?

Please also post the full error/traceback.

**Comment by jhawk28** [comment]
yes, the same files work when not using sudo

**Comment by jctanner** [comment]
@jhawk28 I am unable to reproduce ...

```
$ fgrep el6 inventory 
el6.lab.net ansible_ssh_user=jtanner

$ cat site.yml 
- hosts: el6.lab.net
  #connection: local
  gather_facts: False
  sudo: True
  sudo_user: root
  tasks:
    - shell: if [ ! -f /tmp/bigfile ] ; then dd if=/dev/urandom of=/tmp/bigfile bs=1024 count=1000; fi
    - shell: ls -alh /tmp/bigfile 
      register: result
    - debug: var=result.stdout

    - fetch: src=/tmp/bigfile dest=/tmp
      register: result

    - debug: var=result

$ ansible-playbook -i inventory site.yml 
PLAY [el6.lab.net] ************************************************************ 

TASK: [shell if [ ! -f /tmp/bigfile ] ; then dd if=/dev/urandom of=/tmp/bigfile bs=1024 count=1000; fi] *** 
changed: [el6.lab.net]

TASK: [shell ls -alh /tmp/bigfile] ******************************************** 
changed: [el6.lab.net]

TASK: [debug var=result.stdout] *********************************************** 
ok: [el6.lab.net] => {
    "result.stdout": "-rw-r--r-- 1 root root 1000K Dec  4 20:48 /tmp/bigfile"
}

TASK: [fetch src=/tmp/bigfile dest=/tmp] ************************************** 
ok: [el6.lab.net]

TASK: [debug var=result] ****************************************************** 
ok: [el6.lab.net] => {
    "result": {
        "changed": false, 
        "dest": "/tmp/el6.lab.net/tmp/bigfile", 
        "file": "/tmp/bigfile", 
        "invocation": {
            "module_args": "src=/tmp/bigfile dest=/tmp", 
            "module_name": "fetch"
        }, 
        "md5sum": "34edb35926b6aa64705b4137b1b7c6a9"
    }
}

PLAY RECAP ******************************************************************** 
el6.lab.net                : ok=5    changed=2    unreachable=0    failed=0 
```

**Comment by jctanner** [comment]
@jhawk28 Please provide an example playbook, the full command you are running, and the full output + error. It would also be helpful to know what connection mode you are using and what the OS versions of your control machine and clients are.

**Comment by jhawk28** [comment]
I'll be able to get an example on Friday. We are using Ubuntu 13.10 for both control/clients. The control is just connecting over ssh.

**Comment by jimi-c** [comment]
@jhawk28 you wouldn't happen to have debugging enabled in your sshd_config, would you? We have noticed some issues with that, and just want to rule that out here.

**Comment by jhawk28** [comment]
I haven't enabled it, but Ill check to see.

**Comment by jhawk28** [comment]
@jimi-c sshd_config has debug logging set to INFO
@jctanner see gist for sample playbook and log: https://gist.github.com/jhawk28/8e0a72de52a10887edae

**Comment by jimi-c** [comment]
@jhawk28 hrm, just tried your playbook with the only modification being that I'm grabbing all of /var/log instead of just the audit logs, and was not able to reproduce this. It appears you're running with SElinux on, could you setenforce 0 on a test (ie. non-production system) and see if the issue still occurs?

**Comment by jhawk28** [comment]
I ran the setenforce 0. I then went through the process of running the playbook on a single host. That worked. It continued to work until had added 4 hosts. It then started to fail. It even failed on the machine with the selinux set to permissive. So, it looks like the issue is related to retrieving large files from multiple hosts using sudo.

**Comment by mpdehaan** [comment]
should be fixed by the JSON fix applied already by @jctanner can you test this again on latest devel?

**Comment by jhawk28** [comment]
I verified that this works on the latest in the Git repo
