### ISSUE TITLE
search string for registered variable.stdout evaluated in a when conditional does work as expected

### ISSUE THREAD

**Issue by erpadmin** [ansible/ansible#51659]
##### SUMMARY

search on registered variable.stdout evaluated in a when conditional does not work as expected

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ruser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 15:24:06) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Fedora 28

##### STEPS TO REPRODUCE

check

- name: test2
    debug:
    msg: "yes"
   when: dnscheck2.stdout is search('/name/')
   
   

relevant output:

TASK [debug1] ******************************************************************************************************************************************************************************************************
ok: [myhost.localnet] => {
    "dnscheck2": {
        "changed": false, 
        "cmd": [
            "awk", 
            "/192.168.0.1/", 
            "/etc/resolv.conf"
        ], 
        "delta": "0:00:00.006063", 
        "end": "2019-02-02 22:09:17.806414", 
        "failed": false, 
        "rc": 0, 
        "start": "2019-02-02 22:09:17.800351", 
        "stderr": "", 
        "stderr_lines": [], 
        "stdout": "nameserver 192.168.0.1", 
        "stdout_lines": [
            "nameserver 192.168.0.1"
        ]
    }
}

TASK [test2] *******************************************************************************************************************************************************************************************************
skipping: [myhost.localnet]

##### EXPECTED RESULTS

debug msg prints

##### ACTUAL RESULTS

task was skipped

**Comment by mkrizek** [comment]
Seems to work as expected to me. There is no `/name/` in `dnscheck2.stdout`. I guess the following is what you wanted?
```
when: dnscheck2.stdout is search('name')
```

https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html#testing-strings

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by erpadmin** [comment]
you are correct, i misinterpreted the doc example and thought the /'s were sed-like

thanks
