### ISSUE TITLE
Powershell code for GPO only giving errors when ran from Ansible playbook

### ISSUE THREAD

**Issue by MMollyy** [ansible/ansible#51695]
##### SUMMARY
Hi,

I'm currently trying to automate some GPOs on a domain controller, but i'm kind of running stranded on an error that is being output by powershell. However, when I run the same script local on the DC with the same input as I would when injecting the values from Ansible the script runs fine.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/awx/venv/tower_venv_ansible_2_6_4/lib/python2.7/site-packages/ansible
  executable location = /var/lib/awx/venv/tower_venv_ansible_2_6_4/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```
Running from Ansible Tower: this command did not output anything when ran from the Tower node
```

##### OS / ENVIRONMENT

Target OS: w2k16 datacenter (domain controller)
Running on either AWS or Azure.

##### STEPS TO REPRODUCE
```
- name: run powershell script
   win_shell: 'C:\folder\gpo.ps1 -gpo {{ item.value | join(",") }}'
   register: psoutput
   with_dict: "{{ gpo_values }}"
```
Using the above for an array input
```
- name: run powershell script
  win_shell: 'C:\folder\test_gpo.ps1 -gpo gpo-name-here'
  register: psoutput_two
```
Using the above for a single value input.
I've tested win_command for both as well, without success.

Neither work. The powershell scripts used are:
```
param(
    [Parameter(Mandatory=$true)]
    [array] $gpo
)

import-module –Name grouppolicy
import-module -Name activedirectory

$ous = Get-ADOrganizationalUnit -Filter *

foreach ($line in $gpo) {
    $existing_gpo = get-gpo -name $line -Domain ([System.DirectoryServices.ActiveDirectory.Domain]::Getcomputerdomain().Name)
    $ous | ForEach-Object {Remove-GPLink -Guid $existing_gpo.Id -Target $_.DistinguishedName -erroraction silentlycontinue}
    }

exit
```
Above is for the array injection for multiple gpos
```
import-module –Name grouppolicy
import-module -Name activedirectory

$gpo = get-gpo -name $rule -Domain ([System.DirectoryServices.ActiveDirectory.Domain]::Getcomputerdomain().Name)
```
Above is for the single value injection

##### EXPECTED RESULTS
Output of powershell showing me the GPOs that i'm looking for. Which, if it worked, I could convert into JSON and then re-use in my ansible playbook.
Something like:
```
DisplayName      : gpo_name
DomainName       : domain_name
Owner            : TST\owner
Id               : 37d1d2b6-ea72-438b-b97f-950193982f44
GpoStatus        : AllSettingsEnabled
Description      : 
CreationTime     : 1/14/2019 12:56:45 PM
ModificationTime : 1/28/2019 10:36:06 AM
UserVersion      : AD Version: 0, SysVol Version: 0
ComputerVersion  : AD Version: 24, SysVol Version: 24
WmiFilter        : 
```

##### ACTUAL RESULTS
```
{
    "_ansible_parsed": true,
    "stderr_lines": [
        "get-gpo : An operations error occurred. (Exception from HRESULT: 0x80072020)",
        "At C:\\folder\\test_gpo.ps1:11 char:5",
        "+     get-gpo -name \"gpo_name\" -Domain ([System.DirectoryS ...",
        "+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
        "    + CategoryInfo          : NotSpecified: (:) [Get-GPO], COMException",
        "    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.GroupPolicy.Commands.GetGpoCommand"
    ],
    "changed": true,
    "end": "2019-02-04 12:15:26.286626",
    "_ansible_no_log": false,
    "stdout": "",
    "cmd": "C:\\folder\\test_gpo.ps1 -gpo gpo_name",
    "start": "2019-02-04 12:15:24.285711",
    "delta": "0:00:02.000915",
    "stderr": "get-gpo : An operations error occurred. (Exception from HRESULT: 0x80072020)\r\nAt C:\\ciswin\\test_gpo.ps1:11 char:5\r\n+     get-gpo -name \"gpo_name\" -Domain ([System.DirectoryS ...\r\n+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [Get-GPO], COMException\r\n    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.GroupPolicy.Commands.GetGpoCommand",
    "rc": 0,
    "stdout_lines": []
}
```

As a scenario sketch: i'm trying to get CIS for windows implemented and it requires a lot of manual work for GPOs. I want this to be done with ansible & powershell because someone might get a waver for a certain part of CIS, and I'd like to give those people the flexibility of enabling/disabling certain GPOs without doing it manually but via code.

If anyone has any suggestions I'm glad to try them.

**Comment by MMollyy** [comment]
As ive started looking at event logging it might seem like the issue is windows related. Investigating ..

**Comment by MMollyy** [comment]
Yes. Can be closed. Apparently there is something wrong with one of my dcom objects according to event log.

**Comment by jborean93** [comment]
Sorry for not getting to this earlier, looks like the bot didn't tag it as Windows because the win_shell component wasn't set. Typically if you are making operations over the network that need authentication you will come across the double hop issue. If you ever come across a problem that works locally but not through Ansible I woudl have a read through https://docs.ansible.com/ansible/latest/user_guide/windows_faq.html#why-can-i-run-a-command-locally-that-does-not-work-under-ansible to see some alternative options.
