### ISSUE TITLE
ANSIBLE_LIBRARY vs library vs DEFAULT_MODULE_PATH

### ISSUE THREAD

**Issue by techtonik** [ansible/ansible#5170]
All these names are not descriptive. I wonder how hard is to deprecate all of those and replace them with ANSIBLE_SHARED_FILES? Is that name makes more sense to everybody else?

**Comment by jctanner** [comment]
@techtonik this is a conversation that is more suitable for the ansible-devel / ansible-users mailing list.

**Comment by techtonik** [comment]
So the answer is no or what?

**Comment by techtonik** [comment]
Done. https://groups.google.com/forum/#!topic/ansible-devel/Nk--1ZXP_rM

**Comment by jctanner** [comment]
@techtonik thank you. I just think this would be a cumbersome change for documentation and for anyone already relying on those var names. I can't say yes or no to making it happen, but it's worth a discussion.

**Comment by techtonik** [comment]
Thanks for explanation. I should have thought about it myself.
