### ISSUE TITLE
Accelerated mode fails when used from multiple clients

### ISSUE THREAD

**Issue by cespare** [ansible/ansible#5171]
I'm trying to use `accelerate: true` (we have lots of little tasks so ~~it's a huge speedup~~ [never mind it's actually not changing the speed for me so I've stopped using it for now]). We run ansible plays and commands from many different computers. After I run an accelerated play from one machine, there's a python daemon running on the remote host and when I try to run the same play from another machine, I get an error:

```
fatal: [host123] => decryption failed
```

If I kill the daemon manually, it works. I'm running the same ansible and python-keyczar version on both client machines as well as the remote host.

In the documentation I see there's an `accelerate_timeout = 30`, and I was hoping this would make the daemon kill itself after 30 seconds, but that's not the case. I guess it closes the socket, but the daemon's still running with the same key. Even if I wait 15 or 20 minutes, I cannot connect from a different client.

I found [this mailing list post](https://groups.google.com/forum/#!msg/ansible-project/WOh157vFHO8/D4XJRWv0wY8J) but it I couldn't find any issue already created.

My workaround for now is to kill the daemon using an unaccelerated ansible task first.

**Comment by mpdehaan** [comment]
Yep, this is a known issue that we are currently working on.

The underlying thing is that your other host doesn't have an active key, and we are not going to terminate the daemon

In this case we most likely will improve the quality of the error message or possibly generate a system where accelerate mode can "add" acceptable keys.

**Comment by cespare** [comment]
I don't see how accelerated mode is usable in this case. Do most ansible users only run from a single client machine?

And what's the point of keeping the daemon around between runs?

**Comment by mpdehaan** [comment]
Yes, many people do use things consistently from one machine, such in the
case of running continuous deployment from Jenkins.

It's a bug, and we're working on it.

**Comment by cespare** [comment]
@mpdehaan OK thanks! I misunderstood your original reply.

**Comment by jimi-c** [comment]
We've been discussing this a bit today, and I the approach we're going to take is to allow the key cache to store multiple keys on the daemon and client side. Since the keys all have a short lifetime (2 hours by default), they can be pruned quite easily when they've expired.

**Comment by mpdehaan** [comment]
@jimi-c let's see if we can maybe get this one done for 1.5?

**Comment by jimi-c** [comment]
@cespare the above patch is in my feature branch if you'd like to give it a test. It is quite a large change though, so we'll be wanting to do a lot more testing on it before merging it in.
