### ISSUE TITLE
Postgres module: "python psycopg2 module is required" error despite having psycopg2 installed

### ISSUE THREAD

**Issue by seanknox** [ansible/ansible#5172]
I'm using Ansible 1.4.1 on OS X. I'm trying to create a Postgresql user using the Postgresql module:

```
- name: Create db user
  postgresql_user: name={{ ansible_user_id }} role_attr_flags=SUPERUSER
```

I've installed psycopg2 via pip. However, Ansible complains that it's not installed.

**Comment by jctanner** [comment]
@seanknox is that a local play or a remote play?

**Comment by seanknox** [comment]
Local.

**Comment by mpdehaan** [comment]
Please stop by ansible project for debugging this.

Sounds like you've just got it installed in a strange place.

**Comment by seanknox** [comment]
"Stop by" meaning the IRC channel?
