### ISSUE TITLE
vars_prompt executed for empty playbook

### ISSUE THREAD

**Issue by JensRantil** [ansible/ansible#5175]
I have a playbook that contains two things
- a single task with a single tag "XXX".
- a single `vars_prompt`.

When I issue

``` bash
$ ansible-playbook --skip-tags XXX
```

I am asked for my `vars_prompt`.

Expected: Since I have no tasks that are to be executed, I expect no `vars_prompt`.

**Comment by JensRantil** [comment]
This also applies if I instead set the tag on the playbook instead of the task.

**Comment by jctanner** [comment]
@JensRantil please indicate your ansible version and it would also be nice to have a simple playbook I could copy/paste for testing.

**Comment by mpdehaan** [comment]
There's no good way to tell where a variable might be accessed in a template so this is not possible to fix.

In most cases people should be using something other than vars prompt to provide data, because it's interactive, such as "--extra-args", and that would avoid you having to type in the data.
