### ISSUE TITLE
Interface name with '.' can't be used in template

### ISSUE THREAD

**Issue by jpte** [ansible/ansible#5176]
Interface name with '.' (like vlan interface) can't be used in template. Jinja use '.' to access to attributes of a variable.

**Comment by jctanner** [comment]
@jpte please indicate your ansible version and give us an example playbook/task that demonstrates the issue.

**Comment by jpte** [comment]
% ansible --version
ansible 1.4.1

From the facts I get this kind of information
"ansible_eth0.2017": {
    "active": true, 
    "device": "eth0.2017", 
    "ipv4": {
        "address": "10.117.0.138", 
        "netmask": "255.255.255.248", 
        "network": "10.117.0.136"
    }, 

So if I want to use the variable {{ ansible_eth0.2017['ipv4']['address'] }} in a template, jinja complains about '2017' because it's an unknown attribute.

**Comment by mpdehaan** [comment]
Actually you can:

hostvars["ansible_eth0.2017"]

will return the fact in question

**Comment by jpte** [comment]
It is not hostvars["ansible_eth0.2017"] but hostvars[<my_local_host>]["ansible_eth0.2017"] right ?
(with <my_local_host> the host on which ansible is playing the playbook)
