### ISSUE TITLE
ansible can't install libxslt-dev?

### ISSUE THREAD

**Issue by mfournierca** [ansible/ansible#5177]
Ansible cannot install libxslt-dev with the apt module, but libxslt-dev can be installed on the host machine via SSH. 

If I run this in a playbook:

```
- name: update the apt cache
  apt: update-cache=yes
  sudo: True
- name: install libxslt-dev
  apt: pkg=libxslt-dev state=installed
  sudo: True
```

Ansible fails with the following message:

```
failed: [192.168.69.169] => {"failed": true, "item": ""}
msg: No package matching 'libxslt-dev' is available
```

However, if I SSH into the host and run 

```
sudo apt-get install libxslt-dev
```

It installs without any problems. I do not know what might be causing this.

**Comment by jctanner** [comment]
@sasquant what is your ansible version, control machine and client machine OS/version ?

It would also be interesting to know if update_cache=yes works around it.

**Comment by mfournierca** [comment]
@jctanner sorry, I should have included that in the original post. Information below. 

Ansible:

```
$ ansible --version
ansible 1.5 (devel 32986c4d64) last updated 2013/11/23 11:58:12 (GMT -400)
```

Control machine:

```
Mac OSX Version 10.7.5
```

Client machine:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.3 LTS
Release:    12.04
Codename:   precise
```

**Comment by mscherer** [comment]
I can reproduce with:

```
$ ansible -k -u   root -i 95.85.30.108, all -m apt -a 'pkg=libxslt-dev state=installed'
SSH password: 
95.85.30.108 | FAILED >> {
    "failed": true, 
    "msg": "No package matching 'libxslt-dev' is available"
}
```

on a digital ocean droplet. 

Installing show:

```
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
```

**Comment by jctanner** [comment]
Reproduced here also. Investigating now ...

```
jtanner@u1304:~/issues/5177-apt-missing-package$ ansible-playbook -i inventory site.yml 

PLAY [localhost] ************************************************************** 

TASK: [apt pkg=libxslt-dev state=present] ************************************* 
failed: [localhost] => {"failed": true}
msg: No package matching 'libxslt-dev' is available

FATAL: all hosts have already failed -- aborting
```

**Comment by mscherer** [comment]
Ok, I found the bug, PR coming.

**Comment by mscherer** [comment]
I think maybe the whole apt module should be redone to take in account various others "corner case" like this one, but that fix is working for now, and the PR is here to discuss :)

**Comment by jctanner** [comment]
@mscherer let's move that to a discussion on the mailing list before we hack up the apt module. Thanks for the bugfix though!

**Comment by mfournierca** [comment]
@mscherer and @jctanner, thanks for the help and the quick response!
