### ISSUE TITLE
Ansible variables - persist

### ISSUE THREAD

**Issue by jyothscupid** [ansible/ansible#51801]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by mkrizek** [comment]
There is no information about the issue provided. Please create a new issue describing the problem you are having.
