### ISSUE TITLE
Playbook fails on rhel-6.4, not centos-6.4 or ubuntu-12.04

### ISSUE THREAD

**Issue by jlaska** [ansible/ansible#5183]
### Summary
- PLAYBOOK: [ansible-examples/language_features/loop_plugins.yml](https://github.com/ansible/ansible-examples/blob/master/language_features/loop_plugins.yml)
- VERSION: ansible-1.5 (built from git devel)

Executing the playbook [ansible-examples/language_features/loop_plugins.yml](https://github.com/ansible/ansible-examples/blob/master/language_features/loop_plugins.yml), fails when run on a rhel-6.4 system.  Running the same play on a centos-6.4, or ubuntu-12.04 completes successfully.

The inventory included in the play includes a mix of rhel-6.4, centos-6.4 and ubuntu-12.04 systems.  It appears that the trigger is when the host running the play is rhel-6.4.
### Playbook success (centos-6.4 or ubuntu-12.04)

```
# ansible-playbook -i inventory -u root -l 'host-1*:&local_1-10' language_features/loop_plugins.yml

PLAY [all] ******************************************************************** 

TASK: [file dest=/etc/fooapp state=directory] ********************************* 
changed: [host-1.example.com]
ok: [host-10.example.com]

TASK: [copy src={{item}} dest=/etc/fooapp/ owner=root mode=600] *************** 
skipping: [host-1.example.com]
skipping: [host-10.example.com]

PLAY RECAP ******************************************************************** 
host-1.example.com         : ok=1    changed=1    unreachable=0    failed=0   
host-10.example.com        : ok=1    changed=0    unreachable=0    failed=0   
```
### Playbook failure (rhel-6.4)

```
# ansible-playbook -i inventory -u root -l 'host-1*:&local_1-10' language_features/loop_plugins.yml

PLAY [all] ******************************************************************** 

TASK: [file dest=/etc/fooapp state=directory] ********************************* 
failed: [host-1.example.com] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1386257903.41-205518042321912/file", line 1381, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1386257903.41-205518042321912/file", line 266, in main
    os.makedirs(path)
  File "/usr/lib64/python2.6/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/etc/fooapp'

changed: [host-10.example.com]

TASK: [copy src={{item}} dest=/etc/fooapp/ owner=root mode=600] *************** 
skipping: [host-10.example.com]

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/awx/loop_plugins.retry

host-1.example.com         : ok=0    changed=0    unreachable=0    failed=1   
host-10.example.com        : ok=1    changed=1    unreachable=0    failed=0   
```

**Comment by jctanner** [comment]
Unable to reproduce

```
[root@jenkins-nightly-rax-rhel-6 ansible-examples]# ansible-playbook -v -c smart -i ~/inventory language_features/loop_plugins.yml 

PLAY [all] ******************************************************************** 

TASK: [file dest=/etc/fooapp state=directory] ********************************* 
ok: [thishost] => {"changed": false, "gid": 0, "group": "root", "mode": "0755", "owner": "root", "path": "/etc/fooapp", "size": 4096, "state": "directory", "uid": 0}

TASK: [copy src={{item}} dest=/etc/fooapp/ owner=root mode=600] *************** 
skipping: [thishost]

PLAY RECAP ******************************************************************** 
thishost                   : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by jctanner** [comment]
If the dir is actually a file: `msg: Could not replace file: /home/jtanner/.ansible/tmp/ansible-1386270968.0-138903888325298/source to /tmp/fooapp/1: [Errno 20] Not a directory`

If the dir already exists: `changed: [localhost] => (item=/home/jtanner/issues/5183-copy-traceback/files/1)`

**Comment by jctanner** [comment]
@jlaska we need more info on this one unfortunately.

**Comment by mpdehaan** [comment]
This ticket caption should also be a lot better -- this isn't a playbook failure, this is a module error.

**Comment by mpdehaan** [comment]
Let's discuss this offline and not in the tracker.

**Comment by jlaska** [comment]
That cause of the reported issue appears to be running the noted play against the same host multiple times, concurrently.  This was accomplished using multiple host aliases all pointing to the same system (ansible_ssh_host=localhost).

The cause is not the fault of ansible or the play .. but running mkdir on the same system at the same time.

**Comment by mpdehaan** [comment]
Yeah aliasing many systems to localhost would not be a suggested configuration as not all operations can be atomic and the system doesn't acquire locks to make a module executing on a system exclusive.

In cases where this needs to be done with a local step and the step needs to occur on only one host you can have things like:
- hosts: webservers:
  tasks:
  - ...
- hosts: localhost
  tasks:
  - ...
- hosts: webservers
  tasks:
  - ...

And there that above step will only occur on the one host.
