### ISSUE TITLE
irc module doesn't send messages if network latency is non-trivial

### ISSUE THREAD

**Issue by nirvinehh** [ansible/ansible#5186]
This trivial IRC use case doesn't work for me:

``` bash
ansible localhost -c local -m irc -a 'server=irc.freenode.net channel="#nirvine-testing" nick=ansible-deploy msg=test'
```

The implementation of irc is fairly naive: it connects, sends some commands over a socket (sleeping for an arbitrary second between commands), then closes the socket.  It never receives data, doesn't check if the JOIN happened, etc., so there could be many sources of problems.

**Comment by sivel** [comment]
I started working on this yesterday, trying to follow some of the RFC docs so I could know what to look for and such.

I actually just pushed my branch earlier today:  https://github.com/sivel/ansible/tree/irc-rfc-loops

I've tested on ircd-seven (freenode) and InspIRCd so far.

**Comment by nirvinehh** [comment]
Great, thanks.  Not sure where we had left it in IRC yesterday.  Let me know if you need a tester ;)

**Comment by mpdehaan** [comment]
Yeah please go ahead and submit a pull request so we can review it.

Thanks!

**Comment by sivel** [comment]
That was my plan. I just hadn't finished up and wasn't sure I was ready for the pull request yet. I'll do so soon.
