### ISSUE TITLE
ec2.py now creates host groups by EC2 instance tags

### ISSUE THREAD

**Issue by tegryan** [ansible/ansible#5193]
All tags are converted to host groups with the new EC2.py script.  If an EC2 instance has a tag:  "Class", with a value of "Web" then it is added to a host group title tag_Class_Web.

**Comment by jctanner** [comment]
to be clear, this is a request to update our AWS guide to reflect this new change to ec2.py

**Comment by jctanner** [comment]
New feature added in https://github.com/ansible/ansible/pull/5188

**Comment by mpdehaan** [comment]
Just added and will appear next time we push docs.

This is actually an older feature prior to the referenced commit above so everyone should have it by now.
