### ISSUE TITLE
Unicode bug when escaping Jinja2 variables

### ISSUE THREAD

**Issue by tusbar** [ansible/ansible#5200]
I’m running ansible a19ef93cf3a9cf0f1c0b3cef36d318d32a1745c8 (top of [devel](https://github.com/ansible/ansible/tree/devel)).

I’m having an issue with the following j2 template: 

```
{{ '{{ hello }}' }}
é
```

Used by the following task:

```
- name: update templates
  template: src=file.html dest=/tmp/file.html
```

I’m getting the following error: 

```
TASK: [foo | update templates] **************************************
fatal: [localhost] => {'msg': "'ascii' codec can't encode character u'\\xe9' in position 12: ordinal not in range(128)", 'failed': True}
fatal: [localhost] => {'msg': "'ascii' codec can't encode character u'\\xe9' in position 12: ordinal not in range(128)", 'failed': True}
```

If I remove the non-ascii character (`é`), it works fine.
If I use `{% raw %}` to escape the variable, it fails as well.

**Comment by mpdehaan** [comment]
What is the value of hello in the above (just making sure that's not part of it).

Thanks!

(in queue to see if we can reproduce as I imagine we'd be getting yelled at a lot if it was as simple as no unicode in template files and have some tests around that)

**Comment by tusbar** [comment]
There’s no `hello` variable, there’s no variables at all.

The expected output would be:

```
{{ hello }}
é
```

So I can use it as a template in a Django app.

To answer the second part of your message, this only happens when using Jinja2 [escaping tags](http://jinja.pocoo.org/docs/templates/#escaping).
