### ISSUE TITLE
Extract ansible_eth0 ipv4 address via hostvars getting Undefined

### ISSUE THREAD

**Issue by michaelseto** [ansible/ansible#52049]
##### SUMMARY
I am using a 'Nodes' group and I am trying to extract the ansible_eth0 ipv4 addresses from it for use in another configuration file, but after the deployment is successfully completed, I see the config file has 'Undefined', but there are 3 'Undefined' so I know the node count is correct, because it should be retrieving 3 ipv4 addresses. Here is the line -

elastic_hot_hosts_ip: "{{ groups['Elastic_Hot_Nodes'] | map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address']) | list }}"

Here is the 'Elastic_Hot_Nodes' group - 

[Elastic_Hot_Nodes]
elastic_v5_Hot1 ansible_ssh_port=22 ansible_ssh_host=10.183.152.140 logs_disks_list='["/dev/sdd"]' data_disks_list='["/dev/sdc"]'
elastic_v5_Hot2 ansible_ssh_port=22 ansible_ssh_host=10.183.152.141 logs_disks_list='["/dev/sdd"]' data_disks_list='["/dev/sdc"]'
elastic_v5_Hot3 ansible_ssh_port=22 ansible_ssh_host=10.183.152.142 logs_disks_list='["/dev/sdd"]' data_disks_list='["/dev/sdc"]'

Here is the resulting entry in the config file -

["http://[Undefined, Undefined, Undefined]:9200"]

I have also tried this line (same result) -

elastic_hot_hosts_ip: "{{ groups['Elastic_Hot_Nodes'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | list }}"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Ansible

##### ANSIBLE VERSION

```paste below
ansible 2.7.7
  config file = /data/ansible/elk/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

```

##### CONFIGURATION

```paste below
elastic_hot_hosts_ip: "{{ groups['Elastic_Hot_Nodes'] | map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address']) | list }}"
```

##### OS / ENVIRONMENT

CentOS 7

##### EXPECTED RESULTS
IP Addresses instead of 'Undefined'

##### ACTUAL RESULTS

```paste below
["http://[Undefined, Undefined, Undefined]:9200"]
```

**Comment by michaelseto** [comment]
Workaround, use 'map('extract', hostvars, ['ansible_ssh_host']) | list }}"'

**Comment by samdoran** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
