### ISSUE TITLE
shell module: Shell echo is including arguments

### ISSUE THREAD

**Issue by patrickheeney** [ansible/ansible#5206]
Task:

```
- shell: "echo -e -n \"test\n\ttest2\" >> test creates=test"
```

Results:

```
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1386356406.38-102382384091680 && echo $HOME/.ansible/tmp/ansible-1386356406.38-102382384091680']
<localhost> REMOTE_MODULE command echo -e -n "test
    test2" >> test creates=test #USE_SHELL
<localhost> PUT /tmp/tmp188keY TO /home/vagrant/.ansible/tmp/ansible-1386356406.38-102382384091680/command
<localhost> EXEC ['/bin/sh', '-c', '/usr/bin/python /home/vagrant/.ansible/tmp/ansible-1386356406.38-102382384091680/command; rm -rf /home/vagrant/.ansible/tmp/ansible-1386356406.38-102382384091680/ >/dev/null 2>&1']
```

Outputs:

```
-e -n test
    test2
```

Expected Result:
The arguments -e or -n should not be in the file.

**Comment by mpdehaan** [comment]
We can take a look to see if we think there is something wrong with the escaping.

First time I've heard of it though.

**Comment by janeznemanic** [comment]
I will have a look at this one and try to figure out something.

**Comment by patrickheeney** [comment]
@janeznemanic It seems to be a bigger issue then just shell and echo:

```
- name: main | check for db existance
  command: >
    mysql -e "show databases" | fgrep {{ item }}
  register: mysql_exist
  with_items:
    - app
```

From this I get the response: `Usage: mysql [OPTIONS] [database]`. So it is not receiving the arguments. It is passing the right information to the remote, something is happening after that.

**Comment by janeznemanic** [comment]
It looks like I can't reproduce the bug. Here is my sample playbook:

 hosts: localhost
  gather_facts: false
  connection: local
  tasks:
- name: debbuging
  
  shell: "echo -e -n \"test\n\ttest2\" >> test creates=test"

The command that I run is: ansible-playbook -i inventory -vv play.yml
Console output is:

PLAY [localhost] *************************************************************\* 

TASK: [debbuging] ************************************************************\* 
<localhost> REMOTE_MODULE command echo -e -n "test
    test2" >> test creates=test #USE_SHELL
changed: [localhost] => {"changed": true, "cmd": "echo -e -n \"test\n\ttest2\" >> test ", "delta": "0:00:00.003495", "end": "2013-12-24 14:44:04.729262", "rc": 0, "start": "2013-12-24 14:44:04.725767", "stderr": "", "stdout": ""}

PLAY RECAP *******************************************************************\* 
localhost                  : ok=1    changed=1    unreachable=0    failed=0

And in file named test I get this:

test
       test2

There is a tab white space before word test2 in file test. But I don't know why this web page doesn't show it.
@patrickheeney Any chances you can provide more data about the bug? Try running ansible-playbook with -vvv option. What about if it is got something to do with your shell? Just wondering.

**Comment by patrickheeney** [comment]
@janeznemanic Running stock ubuntu 12.04 with stock ansible on it and I believe bash. The results I posted in the original report were with it running -vvv. It correctly passed the right command but `-e -n` appeared in the file. In the follow up post it did the same thing with mysql but it says please provide the mysql options even though `-e` was passed.

I am not sure how else I can help. I am happy to run any commands or anything you wish me to try.

**Comment by janeznemanic** [comment]
@patrickheeney No idea what could go wrong. I'm stuck at the moment.

**Comment by dagwieers** [comment]
@patrickheeney I cannot reproduce it, but I have seen something similar (not Ansible related) years ago which was caused by either a busybox echo, or an ash echo, I am not sure.

Can this be reproduced with the latest Ansible (e.g. 1.4.4) ? Just to make sure this is not something that has already been fixed.

**Comment by patrickheeney** [comment]
Not sure, I don't have the exact environment loaded but ill try to get something setup and test this.

**Comment by patrickheeney** [comment]
@dagwieers Finally had a chance to test this. Still an issue for me on ansible 1.5.3. Running stock ubuntu 12.04 still.

**Comment by davidopluslau** [comment]
Reproduced on OS X 10.9, Ansible 1.5.3. Same issue as described above. Happy to get a fix on this one.

**Comment by jctanner** [comment]
Reproduced on ubuntu and simplified it down to a simple python script ...

```
#!/usr/bin/env python

import subprocess
import os

def run_command(args):
    p = subprocess.Popen(args, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = p.communicate()
    rc = p.returncode

    return rc, stdout, stderr

args = 'echo -e -n "test" >> test'
run_command(args)
```

Ubuntu 12.04 + Python 2.7.3

```
$ cat test
-e -n test
$
```

Fedora 18 + Python 2.7.3

```
$ cat test ; echo ''
test
$
```

**Comment by jctanner** [comment]
Ubuntu 12.04

```
$ ls -al /bin/sh
lrwxrwxrwx 1 root root 4 Mar 29  2012 /bin/sh -> dash
```

Fedora 18

```
$ ls -al /bin/sh
lrwxrwxrwx. 1 root root 4 Jun 17  2013 /bin/sh -> bash
```

**Comment by sivel** [comment]
Of importance here: https://wiki.ubuntu.com/DashAsBinSh#echo

**Comment by patrickheeney** [comment]
Interesting. Is there anything that can be done on the ansible level like warnings or anything? Or perhaps a note in the shell command about compatibility across systems?

**Comment by jctanner** [comment]
@patrickheeney in this case, it's a shell code portability issue. If we tried to provide a warning, we'd have to parse the input command for non-portable characters, check where /bin/sh points to, and then decide if the non-portable characters are going to work.

**Comment by patrickheeney** [comment]
@jctanner Understood. I was experiencing the same thing with other commands such as `mysql -e` but it may be more of the same problem or an unrelated issue. I will have to dig in some more on that one.

What do you think about docs note or somewhere so we can reference this?

**Comment by jctanner** [comment]
@patrickheeney I think the shell module docs could use some warnings. If you want to submit a PR for that, I'll review/merge.
