### ISSUE TITLE
Move four modules from network to community maintained

### ISSUE THREAD

**Issue by abenokraitis** [ansible/ansible#52183]
##### SUMMARY

Looking at:
https://docs.ansible.com/ansible/latest/modules/network_maintained.html#network-supported

Four modules should move from `supported_by: network` as they were erroneously added to network supported to `supported_by: community`:

`ftd_configuration – Manages configuration on Cisco FTD devices over REST API`
`ftd_file_download – Downloads files from Cisco FTD devices over HTTP(S)`
`ftd_file_upload – Uploads files to Cisco FTD devices over HTTP(S)`
`slxos_l3_interface – Manage L3 interfaces on Extreme Networks SLX-OS network devices.`

These four modules were written and maintained by entities outside Red Hat.

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

**Comment by sivel** [comment]
cc @thaumos

**Comment by abenokraitis** [comment]
@privateip @ikhan2010 @IPvSean just FYI.
