### ISSUE TITLE
fix various issues with the authorized_keys module

### ISSUE THREAD

**Issue by bradobro** [ansible/ansible#522]
Fix bug where key state=absent will write a non-existent file. No need to change resource in that case, so be idempotent.

**Comment by mpdehaan** [comment]
Merging tickets:

Remove comment ("#Authorized Keys File created by Ansible.") this module currently places in the authorized_key module.

**Comment by mpdehaan** [comment]
also:

the authorized_keys module should work under Python 2.4 and earlier -- remove the with blocks and test

**Comment by mpdehaan** [comment]
closing per PR
