### ISSUE TITLE
duplicate task names are shown in the console output when ansible-playbook is run

### ISSUE THREAD

**Issue by qduxiaoliang** [ansible/ansible#52214]
##### SUMMARY

task name is shown twice in the console output when ansible-playbook is run
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

full_skip
stdout_callback

##### ANSIBLE VERSION

```paste below
ansible 2.7.6
  config file = /demo/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
DEFAULT_GATHERING(/demo/ansible.cfg) = explicit
DEFAULT_REMOTE_USER(/demo/ansible.cfg) = root
DEFAULT_STDOUT_CALLBACK(/demo/ansible.cfg) = full_skip
HOST_KEY_CHECKING(/demo/ansible.cfg) = False

```

##### OS / ENVIRONMENT

 uname -a
Linux server 3.10.0-862.14.4.el7.x86_64 #1 SMP Fri Sep 21 09:07:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

##### DEPENDENCY PROBLEMS

```paste below

```

##### STEPS TO REPRODUCE

 ansible-playbook -c paramiko demo.yml

```yaml
---
- name: demo play
  hosts: localhost
  remote_user: root
  any_errors_fatal: True
  tasks:
    - name: demo task
      shell: echo demo task

```

##### EXPECTED RESULTS

only one task name is shown

##### ACTUAL RESULTS

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'

PLAY [demo play] ******************************************************************************************************

TASK [demo task] ******************************************************************************************************

TASK [demo task] ******************************************************************************************************
changed: [localhost]

PLAY RECAP ************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0

```paste below

```

**Comment by qduxiaoliang** [comment]
please note: there is no such issue in ansible 2.6.5

**Comment by qduxiaoliang** [comment]
after checking the full_skip document as below, this plugin is deprecated
https://docs.ansible.com/ansible/latest/plugins/callback/full_skip.html
a new configuration option named display_skipped_hosts has been added.
this ticket can be closed since another solution can also achieve suppressing the skipping task names in the console output

**Comment by Akasurde** [comment]
@qduxiaoliang Thanks for reporting this issue. Closing this issue as per [comment](https://github.com/ansible/ansible/issues/52214#issuecomment-463469768). Please feel free to re-open if problem persists. Thanks.
