### ISSUE TITLE
python interpreter not found, question on using "/usr/bin/python env" globally

### ISSUE THREAD

**Issue by ytjohn** [ansible/ansible#5223]
I see in #205 that the integration version is using "/usr/bin/env python" to find the location of the python interpreter. I'm currently on ansible v1.4 (installed from pip) and this does not work for me. Linux hosts work fine when python is in /usr/bin/python, but on FreeBSD hosts (where python is in /usr/local/bin/python), not so much.

Was this change not yet released or maybe reverted out? 

What I am having to do currently is place `ansible_python_interpreter="/usr/bin/python env"` after each host in my inventory file. Can `ansible_python_interpreter` be set globally as a default via the config file or an environment variable?

**Comment by bcoca** [comment]
You can set ansible_python_interpreter in group_vars/all  or as an
environment variable in your shell, when I had mixed FreeBSD/linux i had it
set in group_vars/FreeBSD and group_vars/Debian and assigned hosts
accordingly, for example.

/usr/bin/env python  will not be made the default as it breaks
the ansible_python_interpreter functionality and would make it environment

## dependent.

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by jctanner** [comment]
@bcoca thanks for chiming in.

@ytjohn as Brian said, there is a way to accomplish what you want with group vars. I would however consider accepting a pull request for the default interpreter path in ansible.cfg. If you want to code it up, I'll review it.

We also like to encourage these types of discussions/questions to happen on the mailing list instead of through the issue tracker.

**Comment by quinot** [comment]
@jctanner I've just submitted PR #9541 to support a list of possible paths in ansible_*_interpreters, so that if you have e.g. both Debian and FreeBSD hosts, you can just set globally ansible_python_interpreter="/usr/local/bin/python,/usr/bin/python".

**Comment by meskarune** [comment]
It would be great to be able to set a list of binary paths for ansible to use.

**Comment by quinot** [comment]
@meskarune don't hesitate to voice your support for PR #11810 !
