### ISSUE TITLE
undefined jinja2 filter exception not raised

### ISSUE THREAD

**Issue by xchenum** [ansible/ansible#5228]
If a missing filter is used, no error is raised. Instead, the template instantiation process just silently fails, leaving things like {{ ansible_default_ipv4.address }} in its raw form in the output.

**Comment by bcoca** [comment]
this is normally governed by the ansible.cfg setting error_on_undefined_vars, set it to true and this should work as expected. Tested with {{ testvar|fakefilter}}

```
fatal: [localhost] => template error while templating string: no filter named 'fakefilter'
```
