### ISSUE TITLE
content= option for template module

### ISSUE THREAD

**Issue by groks** [ansible/ansible#5230]
When you have many, small files to install or when writing to explain in eg. a blog post the content option of the copy module is super handy:

```
- name: you know it makes sense
  copy:
    dest: /some/where/over/the/rainbow
    owner: wizard
    content: |
      way
      up
      high
```

It would be just as handy when using the template module.

**Comment by mpdehaan** [comment]
This is supported already for the "copy" module, as you linked.

I don't think inline templates are a good idea as the system is going to evaluate all the Jinja2 early, in ways you probably don't want, so I don't see us implementing this for the template module.

Thanks for the idea though!
