### ISSUE TITLE
Export debug msg to a file

### ISSUE THREAD

**Issue by adelmosilva** [ansible/ansible#52326]
##### SUMMARY
Good afternoon
I need to send to a text file a message that appears in debug msg after a check if a directory exists. Follow Playbook below. But it is giving error in the recording of the file

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Debug msg

##### ANSIBLE VERSION
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)

##### CONFIGURATION

ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s
COLOR_CHANGED(/etc/ansible/ansible.cfg) = yellow
COLOR_DEBUG(/etc/ansible/ansible.cfg) = dark gray
COLOR_DEPRECATE(/etc/ansible/ansible.cfg) = purple
COLOR_DIFF_ADD(/etc/ansible/ansible.cfg) = green
COLOR_DIFF_LINES(/etc/ansible/ansible.cfg) = cyan
COLOR_DIFF_REMOVE(/etc/ansible/ansible.cfg) = red
COLOR_ERROR(/etc/ansible/ansible.cfg) = red
COLOR_HIGHLIGHT(/etc/ansible/ansible.cfg) = white
COLOR_OK(/etc/ansible/ansible.cfg) = green
COLOR_SKIP(/etc/ansible/ansible.cfg) = cyan
COLOR_UNREACHABLE(/etc/ansible/ansible.cfg) = red
COLOR_VERBOSE(/etc/ansible/ansible.cfg) = blue
COLOR_WARN(/etc/ansible/ansible.cfg) = bright purple
DEFAULT_BECOME(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/etc/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
DEFAULT_SCP_IF_SSH(/etc/ansible/ansible.cfg) = smart
DEFAULT_SSH_TRANSFER_METHOD(/etc/ansible/ansible.cfg) = smart
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 10
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30

##### OS / ENVIRONMENT
CentOS 7

##### DEPENDENCY PROBLEMS
No depences problems

##### STEPS TO REPRODUCE

---
- hosts: teste
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes

  tasks:
  - name: Verificando Diretórios
    stat:
      path: /etc/teste_path/
    register: path

  - debug:
      msg: "Diretório Ok"
    when: path.stat.isdir is defined and path.stat.isdir

  - debug:
      msg: "Diretório Não existe"
    when: path.stat.exists == False

  - debug: var=path.stdout_lines

  - name: Gravando Valores
    local_action: lineinfile path=/root/find_path.txt line={{path.stdout_lines}}; create=yes

##### EXPECTED RESULTS
Generate a file with informations about if a dir exists or not

##### ACTUAL RESULTS
PLAY [teste] ************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************************
ok: [10.0.10.122]
ok: [10.0.10.117]

TASK [Verificando Diretórios] *******************************************************************************************************************************************************************************
ok: [10.0.10.117]
ok: [10.0.10.122]

TASK [debug] ************************************************************************************************************************************************************************************************
skipping: [10.0.10.122]
ok: [10.0.10.117] => {
    "msg": "Diretório Ok"
}

TASK [debug] ************************************************************************************************************************************************************************************************
skipping: [10.0.10.117]
ok: [10.0.10.122] => {
    "msg": "Diretório Não existe"
}

TASK [debug] ************************************************************************************************************************************************************************************************
ok: [10.0.10.117] => {
    "path.stdout_lines": "VARIABLE IS NOT DEFINED!"
}
ok: [10.0.10.122] => {
    "path.stdout_lines": "VARIABLE IS NOT DEFINED!"
}

TASK [Gravando Valores] *************************************************************************************************************************************************************************************
fatal: [10.0.10.117]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout_lines'\n\nThe error appears to have been in '/root/Ansible/Playbooks/find_path.yaml': line 24, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Gravando Valores\n    ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'stdout_lines'"}
fatal: [10.0.10.122]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout_lines'\n\nThe error appears to have been in '/root/Ansible/Playbooks/find_path.yaml': line 24, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Gravando Valores\n    ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'stdout_lines'"}
        to retry, use: --limit @/root/Ansible/Playbooks/find_path.retry

PLAY RECAP **************************************************************************************************************************************************************************************************
10.0.10.117                : ok=4    changed=0    unreachable=0    failed=1
10.0.10.122                : ok=4    changed=0    unreachable=0    failed=1

**Comment by bbui1997** [comment]
Based on the output of the stat module, you can create a variable that has a string whether or not the path exists.
test_var: "{{ 'Diretório Ok' if * path.stat.isdir is defined and path.stat.isdir else 'Diretório Não existe'}}"

Since you're on Linux, instead of the debug module, you can use the shell and append to the file on the conditions you want.

* name: Verificando Diretórios
  stat:
  path: /etc/teste_path/
  register: path
* name: Directory is defined 
  shell: "echo Diretório Ok >> /root/find_path.txt"
  when: path.stat.isdir is defined and path.stat.isdir
* name: Directory doesn't exist
  shell: "echo Diretório Não existe >> /root/find_path.txt"
  when: path.stat.exists == False

**Comment by adelmosilva** [comment]
Thanks my friends.
Im used the second option. My inventory has 2 ips address where one has the searched folder and the other has no. When I run the Playbook, show this msg:

PLAY [teste] ******************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************
ok: [10.0.10.117]
ok: [10.0.10.122]

TASK [Verificando Diretórios] *************************************************************************************************************************************************************************
ok: [10.0.10.117]
ok: [10.0.10.122]

TASK [Diretório Existente] ****************************************************************************************************************************************************************************
skipping: [10.0.10.122]
changed: [10.0.10.117]

TASK [Diretório Não Existente] ************************************************************************************************************************************************************************
fatal: [10.0.10.117]: FAILED! => {"msg": "The conditional check 'path:stat.exists == False' failed. The error was: template error while templating string: expected token 'end of statement block', got 'stat'. String: {% if path:stat.exists == False %} True {% else %} False {% endif %}\n\nThe error appears to have been in '/root/Ansible/Playbooks/find_path.yaml': line 18, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Diretório Não Existente\n    ^ here\n"}
fatal: [10.0.10.122]: FAILED! => {"msg": "The conditional check 'path:stat.exists == False' failed. The error was: template error while templating string: expected token 'end of statement block', got 'stat'. String: {% if path:stat.exists == False %} True {% else %} False {% endif %}\n\nThe error appears to have been in '/root/Ansible/Playbooks/find_path.yaml': line 18, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Diretório Não Existente\n    ^ here\n"}
        to retry, use: --limit @/root/Ansible/Playbooks/find_path.retry

PLAY RECAP ********************************************************************************************************************************************************************************************
10.0.10.117                : ok=3    changed=1    unreachable=0    failed=1
10.0.10.122                : ok=2    changed=0    unreachable=0    failed=1
"

Could you help me again?

Thanks man

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
