### ISSUE TITLE
Accessing variables of other hosts does not work

### ISSUE THREAD

**Issue by vasiliyb** [ansible/ansible#5239]
Folks, The following code is producing errors.

code:

{% for k,v in hostvars.iteritems() %}
        {{ v['ansible_all_ipv4_addresses'][0] }}  {{ v['ansible_hostname'] }}
{% endfor %}

error:

{'msg': "One or more undefined variables: 'tuple object' has no attribute 'ansible_all_ipv4_addresses'", 'failed': True}
What should this look like if i wanted an /etc/hosts file like:

192.168.111.222 hostnameA
192.168.111.211 hostnameB
...
Thanks!

**Comment by vasiliyb** [comment]
Facts are being gathered:

GATHERING FACTS **************************************************************\* 
ok: [foo.us-west-2.compute.internal]
ok: [bar.us-west-2.compute.internal]
ok: [baz.us-west-2.compute.internal]

**Comment by jctanner** [comment]
For a bug report we need more information:

1) ansible version
2) control machine operating system type and version
3) client machine operating system type and version
4) an example playbook
5) an example inventory file

**Comment by mpdehaan** [comment]
The caption (accessing hosts from other variables) definitely does work, please stop by the mailing list if you would like some help.

Closing this due to lack of info.
