### ISSUE TITLE
Allow recursive 'dest' in lineinfile module

### ISSUE THREAD

**Issue by iqbalhasnan** [ansible/ansible#5242]
- name: upate name on every _.conf file
  lineinfile: dest=/tmp/httpd/conf.d/_.conf backup=yes state=present regexp="^  SSLCertificateFile" line="  SSLCertificateFile      /etc/pki/tls/certs/abc_cert.cer"
  tags: update-cert

**Comment by mpdehaan** [comment]
This is unlikely to be added but could be dealt with using a "register" statement and an ls, etc.

Please stop by the mailing list and we can discuss.

Thanks!
