### ISSUE TITLE
git module doesn't update repo when changing branch/version

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#5245]
I'm controlling the branch/version of the git repo I clone using a variable, like this:
wordpress_version: 3.7-branch

If I perform a deploy and then afterward change the value of the variable to 
wordpress_version: HEAD, the expected behaviour is for the git module to pull the new branch/version on the next run of the playbook. In fact, nothing happens - the original branch/version will be kept. My workaround is to delete the repo directory (which breaks "idempodence").

**Comment by mpdehaan** [comment]
Linking this with https://github.com/ansible/ansible/issues/4658 to merge the tickets.  Thanks!

**Comment by lechat** [comment]
Hi,

If you need to checkout another branch, you need to pass 'update=true' parameter to git module. If you don't - behaviour will be as you described.

Hope this helps!
