### ISSUE TITLE
file module: state=absent fails in check mode

### ISSUE THREAD

**Issue by lalinsky** [ansible/ansible#5246]
This code in the file module causes problems in the check mode:

```
    if prev_state != 'absent' and state == 'absent':
        try:
            if prev_state == 'directory':
                if os.path.islink(path):
                    if module.check_mode:
                        module.exit_json(changed=True)
                    os.unlink(path)
                else:
                    try:
                        if module.check_mode:
                            module.exit_json(changed=True)
                        shutil.rmtree(path, ignore_errors=False)
                    except:
                        module.exit_json(msg="rmtree failed")
            else:
                if module.check_mode:
                    module.exit_json(changed=True)
                os.unlink(path)
        except Exception, e:
            module.fail_json(path=path, msg=str(e))
        module.exit_json(path=path, changed=True)
```

The line `module.exit_json(changed=True)` raises `SystemExit`, but there are two `except` lines that catch it and report it as error. However at that point, the first JSON was already printed, so there are two JSONs in the response.

I can send a patch to fix this if you want, but I think the best solution would be to remove the large and generic `try`/`except`.

**Comment by mpdehaan** [comment]
Yeah, the exception is a little wide but it's transforming some important errors into JSON, so we can't just remove it (but we could make it more granular around the right operations).

We probably want to catch the appropriate exception types instead.

Patches would be welcome!

**Comment by lalinsky** [comment]
duplicate of #5159
