### ISSUE TITLE
Adding an option to ignore_errors: yes short_message: yes

### ISSUE THREAD

**Issue by rgarrigue** [ansible/ansible#5249]
Hi guys

I'm using ansible to disable some useless services. Because they depends on the way server got installed (minimal, desktop, etc) I've a huge with_items: ended by a ignore_errors: yes. The output isn't pretty, a lot of red failed, blue ignoring.

Would it be possible to add an option to ignore_errors so we only get short message? Something like

```
failed => [slave] => (item=rpcgssd) => ...ignoring
```

Instead of 

```
failed: [slave] => (item=rpcgssd) => {"failed": true, "item": "rpcgssd"}
msg: cannot find 'service' binary or init script for service,  possible typo in service name?, aborting
...ignoring

```

**Comment by jctanner** [comment]
@rgarrigue an interesting idea. Do you think you might be able to code it up?

**Comment by rgarrigue** [comment]
Sorry, that's not likely. I've never got my hand in python.

**Comment by rgarrigue** [comment]
Out of curiosity, I browsed the code a bit. I guess the output part would be easy to do, it's all around line 448-479 in lib/ansible/callbacks.py.

The part I'm not sure off is "how do you pass down the option?". As I don't know the code, I'm afraid I'ld miss something, or screw up something adding one more param, Maybe making ignore_errors an enumeration, like "yes, no, silently" would do, but it seems it's treated like a boolean at line 198...

Nah, I'm really not confident about how to do this cleanly :-/

**Comment by mpdehaan** [comment]
Sounds like the option might wish to be something like

ignore_errors: silently

and the option no longer is a boolean, but should raise errors when not a boolean or 'silently'

**Comment by mpdehaan** [comment]
I'm closing this as we have the pull request about silently to track this ticket now, so basic housekeeping
