### ISSUE TITLE
standardize TLS connection properties

### ISSUE THREAD

**Issue by jamescassell** [ansible/ansible#52506]
##### SUMMARY

There are are a variety of options for TLS connection options and settings.  These should be standardized.

I propose:
- `client_cert`: certificate for client identity, might also include the private key
- `client_key`: private key for `client_cert`
- `ca_cert`: public key to validate server's identity, usually a root certificate
- `validate_certs`: boolean to enable or disable certificate validity checking

All of the above except `ca_cert` are currently supported by the `uri` and `get_url` modules.  We should standardize on these names for both module args, ini settings, and plugin configuration, including variables for connection plugins.

Variants I've seen for these include `verify`, `key`, `cacert`, `cert`, `verify_ssl`, `server_insecure`, `sslcacert`, `sslclientcert`, `sslclientkey`, `sslverify`, `ssl_ca_cert`, `key_file`, `cert_file`

Based on the last two examples, we should also specify whether this is key is being passed directly to the module, or whether the module should look up the key at the specified path.  Most modules seem to look up the client_key/client_cert/ca_cert at specified path on the target machine.  I'd suggest that if we want to support passing the key/cert data directly, that we add a variant of the option called `client_cert_data` or `client_cert_content`.

This Issue is similar in principle to #51757 (standardize connection vars to be `user` and `password`).  There is a much larger variation in these 4 option-names/vars, and many modules don't support `ca_cert` in any form even if it supports others such as `client_cert`, forcing the playbook developer to use `validate_certs: no`

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

core
connection_plugins

##### ANSIBLE VERSION

```
ansible 2.8.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/ansible-ansible/lib/ansible
  executable location = /home/user/ansible-ansible/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

**Comment by bcoca** [comment]
core discussion +1 to standarizing and making aliases of any 'divergent' names in modules.

**Comment by jamescassell** [comment]
Other items to standardize:
- `require_tls`: specify this option to require an encrypted connection, rather than allowing a plain-text connection. (variants include `use_ssl`, `use_tls` (multi-variant), `<module-name>_use_ssl`)
