### ISSUE TITLE
yum disablerepo=* appears to clobber enablerepo

### ISSUE THREAD

**Issue by jasonenfuego** [ansible/ansible#5255]
Including "disablerepo=*" appears to disable all repos, including those explicitly enabled with enablerepo.

From within the vm, the following installs the package as expected:

```
sudo yum install yum-plugin-downloadonly --disablerepo=* --enablerepo=mylocalrepo
```

However, with the following playbook entry, the package cannot be found:

```
- name: installing yum-plugin-downloadonly
  action: yum name=yum-plugin-downloadonly
          disablerepo=*
          enablerepo=mylocalrepo
          state=present
  tags: yum-config
  sudo: yes

TASK: [common | installing yum-plugin-downloadonly] *************************** 
failed: [10.10.10.100] => {"changed": false, "failed": true, "item": "", "rc": 0, "results": []}
msg: No Package matching 'yum-plugin-downloadonly' found available, installed or updated

FATAL: all hosts have already failed -- aborting
```

**Comment by janeznemanic** [comment]
@jasonenfuego I think that disablerepo=\* works as it should and is not a problem here. I think that the problem here is that module can't find repo mylocalrepo on your machine. Try to run:

/usr/bin/repoquery --show-duplicates --plugins --quiet -q --enablerepo mylocalrepo --disablerepo \* --qf %{name}-%{version}-%{release}.%{arch} --whatprovides yum-plugin-downloadonly

Hopefully this will provide additional hints where is the mistake.

**Comment by jasonenfuego** [comment]
@janeznemanic Here you go:

```
[vagrant@localhost ~]$ /usr/bin/repoquery --show-duplicates --plugins --quiet -q --enablerepo mylocalrepo --disablerepo * --qf %{name}-%{version}-%{release}.%{arch} --whatprovides yum-plugin-downloadonly
yum-plugin-downloadonly-1.1.30-14.el6.noarch
yum-plugin-downloadonly-1.1.30-14.el6.noarch
yum-plugin-downloadonly-1.1.30-14.el6.noarch
yum-plugin-downloadonly-1.1.30-14.el6.noarch
```

**Comment by janeznemanic** [comment]
@jasonenfuego Interesting. Unfortunately not getting closer to the problem.

**Comment by jasonenfuego** [comment]
@janeznemanic Are you able to reproduce? 

FWIW, here is what I've done:
1. Download some yum packages to a local directory (using yum-plugin-downloadonly).
2. Create a local repository (using createrepo) from that directory.
3. Create an entry for the local repo in /etc/yum.repos.d/
4. Attempt to yum install from the local repo with the others disabled.
        This works when done manually, but fails from within a play.

**Comment by sa2ajj** [comment]
@jasonenfuego Did you consider running ansible-playbook -vvvv ?  It will give you a lot of information and, maybe, a hint?  (Sorry, my background is mostly Debian based systems, so I can't provide specific help here.)

**Comment by jctanner** [comment]
@jasonenfuego this problem was two fold ...
- disablerepo=\* must come before enablerepo or yum won't enable anything
- the parameters for the yum command were space separated and should have been joined like "enablerepo=foo"
