### ISSUE TITLE
vault_password_file can't be relative while ANSIBLE_VAULT_PASSWORD_FILE can

### ISSUE THREAD

**Issue by gangefors** [ansible/ansible#52566]
##### SUMMARY

ansible.cfg option vault_password_file doesn't behave identical to environment variable ANSIBLE_VAULT_PASSWORD_FILE.
ANSIBLE_VAULT_PASSWORD_FILE can be a relative path, vault_password_file in ansible.cfg can not.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

core

##### ANSIBLE VERSION

```paste below
ansible 2.7.7
  config file = /home/stefanga/.ansible.cfg
  configured module search path = ['/home/stefanga/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/stefanga/.pyenv/versions/3.7.2/envs/ansible/lib/python3.7/site-packages/ansible
  executable location = /home/stefanga/.pyenv/versions/ansible/bin/ansible
  python version = 3.7.2 (default, Feb 14 2019, 09:28:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```paste below
DEFAULT_VAULT_PASSWORD_FILE(/home/stefanga/.ansible.cfg) = /home/stefanga/.vault_pass
```

##### OS / ENVIRONMENT

debian stretch

##### STEPS TO REPRODUCE

Create an ansible.cfg with the following content.
```
[defaults]
vault_password_file = .vault_pass
```

Also create `.vault_pass` with
```
test
```

Create the following playbook.
```yaml
---
- hosts: localhost
  tasks:
    - set_fact:
        mypass: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            35656534316565316338373735356532626436363136653163373563316365316463336665366633
            3135326532333566353065663666636633393234366463610a383935623737316131303230336364
            35303863393131373735373432303838316632623035366130333265663064343536656330663663
            3864373639346262660a643534653239663661643037313965346564613435333866376564396166
            3562

    - debug:
        msg: "{{ mypass }}"

```

##### EXPECTED RESULTS

`vault_password_file = .vault_pass`
Should not be interpreted as $HOME/.vault_pass and
$ ansible-playbook test.yml
should be able to run successfully with .vault_pass in the same folder as the playbook.

##### ACTUAL RESULTS

```paste below
$ ansible-playbook test.yml
ERROR! The vault password file /home/stefanga/.vault_pass was not found

$ ANSIBLE_VAULT_PASSWORD_FILE=.vault_pass ansible-playbook test.yml
PLAY [localhost] ****************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************
ok: [localhost]

TASK [set_fact] *****************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ********************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "test"
}

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   

```

**Comment by sivel** [comment]
Paths defined in ansible.cfg are relative to the ansible.cfg file, not relative to CWD, giving a predictable relative path.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by gangefors** [comment]
Do you have any place in the documentation where this is specified?

I have found this, but I didn't know if it actually referred to the ansible.cfg file.
https://docs.ansible.com/ansible/2.7/user_guide/playbook_pathing.html

But in the section about the actual config file there is no mention of this, and that confused me to the point where I opened this issue.
https://docs.ansible.com/ansible/2.7/reference_appendices/config.html

**Comment by sivel** [comment]
I've re-opened this issue, to track the progress of ensuring that we have documentation around relative pathing of values specified in the config file.
