### ISSUE TITLE
redhat_subscribe applies variable expansion to password

### ISSUE THREAD

**Issue by cwilkers** [ansible/ansible#52585]
##### SUMMARY

When using a password containing shell special characters, those characters are expanded during run_command instead of passed directly through.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

redhat_subscribe register() function
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/redhat_subscription.py#L381

##### ANSIBLE VERSION

```
ansible 2.7.0
  config file = /home/cwilkers/git/pit-hybrid/cookbooks/federation-development/aws/ansible.cfg
  configured module search path = [u'/home/cwilkers/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

```
ANSIBLE_NOCOWS() = True
ANSIBLE_PIPELINING() = True
ANSIBLE_SSH_ARGS() = -o ControlMaster=auto -o ControlPersist=600s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=false
ANSIBLE_SSH_CONTROL_PATH() = %(directory)s/%%h-%%r
CACHE_PLUGIN() = jsonfile
CACHE_PLUGIN_CONNECTION() = $HOME/ansible/facts
CACHE_PLUGIN_TIMEOUT() = 600
DEFAULT_CALLBACK_WHITELIST() = [u'profile_tasks']
DEFAULT_FORKS() = 20
DEFAULT_GATHERING() = smart
DEFAULT_LOG_PATH() = /home/cwilkers/ansible.log
DEFAULT_PRIVATE_KEY_FILE() = /home/cwilkers/git/pit-hybrid/ssh-keys/summit-hybrid-aws-2019
DEFAULT_REMOTE_USER() = ec2-user
DEFAULT_ROLES_PATH() = [u'/home/cwilkers/.ansible/roles', u'/etc/ansible/roles', u'/usr/share/ansible/roles']
DEFAULT_TIMEOUT() = 90
HOST_KEY_CHECKING() = False
PERSISTENT_CONNECT_TIMEOUT() = 30
RETRY_FILES_ENABLED() = False

```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Workstation release 7.5 (Maipo)

##### DEPENDENCY PROBLEMS
N/A

##### STEPS TO REPRODUCE

When rhsm_password contains a $ it will be expanded rather than passed through, and result in a failed registration.

Alternatively, use $DOESNOTEXIST or similar unset environment variable at the end of a correct password, which should cause failure, but will not if expanded.

```yaml
- redhat_subscription:
        state: present
        username: "{{ rhsm_user }}"
        password: "{{ rhsm_password }}"
        pool_ids: "{{ rhsm_pool }}"
```

##### EXPECTED RESULTS

Don't expand any parameters in subscription-manager call.

##### ACTUAL RESULTS

Parameter expansion is happening.

Work-around: Forcibly quote password before passing to redhat_subscription (but doing so fails elsewhere if installing OpenShift, thus the issue.)

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Modules don't do variable expansion, this happens via Ansible core, so this is not a redhat_subscribe issue.  To avoid 'variable expansion' or templating you can define values as 'unsafe':

`rhsm_password: !unsafe This$will{{notbeTemplated`


In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by cwilkers** [comment]
To clarify, I'm not talking about Jinja2 templating in a variable, but shell (e.g. sh or bash) variable expansion during the actual subscription-manager call (performed by the Ansible run_command() function)

Modules don't do variable expansion, but the shell called by run_command() does, and it can be turned off, but isn't in the redhat_subscribe register function.

I just tested locally, and adding the `use_unsafe_shell=True` parameter to the `run_command` invocation works as expected. I'll generate a PR in a moment.
