### ISSUE TITLE
Use systemwise temporary directory for *.retry files

### ISSUE THREAD

**Issue by JensRantil** [ansible/ansible#5260]
When I execute a playbook and decide to cancel it by pressing CTRL+C (sigint) I find temporary files in my home directory (*.retry files). They are not cleaned up.

Expected: That the files are cleaned up. If they, for some technical reason, can't be cleaned up I suggest they are stored in a systemwide temporary directory, such as `/tmp` (`tempfile.gettempdir()`).

**Comment by srgvg** [comment]
I'd rather have them in a configurable place, defaulting to some tmp directory. I don't like $HOME for that, as it leaves it cluttered now.

**Comment by JensRantil** [comment]
Digging into [the code](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/__init__.py#L476) a little bit I notice that they are explicitly put in `$HOME`.I didn't know about the retry functionality until now.

> I'd rather have them in a configurable place, defaulting to some tmp directory. I don't like $HOME for that, as it leaves it cluttered now.

I agree. `--retry-file-path` or similar that defaults to tmp directory would work.

Also, when ansible is given SIGINT, I think retry files should be cleaned up (see #5261).

**Comment by srgvg** [comment]
Should be a config in ansible.cfg (and possibly an environment var.)
At SIGINT, no files were created yet (except from a previous run). I'm not sure cleaning those up would be a good idea at that time.

**Comment by mpdehaan** [comment]
While I'm fine with making this configurable, I do NOT think these should be any way put in a system directory, access control is important.

retry files are generated on failed playbook runs, when ansible completes, it does not write them halfway through the process.

If you'd like to discuss this further, let's discuss on the mailing list (ansible-devel seems most appropriate)

**Comment by sa2ajj** [comment]
I run into .retry files being created in the home directory, and the code above suggests that the retry files would be created next to the inventory (otherwise, why all this pain of setting basedir in one place and then pass it over).

However while basedir is extracted from the inventory, it's just ignored in the code that forms the file name.

Is it intentional?
