### ISSUE TITLE
Incorrect sudo password freezes ansible-playbook

### ISSUE THREAD

**Issue by JensRantil** [ansible/ansible#5261]
When I execute a playbook with `sudo: yes` (in playbook) and `-K` on command line, the first task will freeze if I enter the wrong password. If I try to push CTRL+C (sigint), it does not bring me back to my shell.

Expected: Presenting an error message saying something like "Unable to execute sudo; check your password." and then quitting. If that can't be done, at least sigint should be handled gracefully.

Workaround: When I happen to have fat fingers I open up an additional terminal and kill the ansible process. I then perform a manual [cleanup of *.retry files in my Home directory](#5260).

**Comment by mpdehaan** [comment]
What version of Ansible are you using and what connection type?  (If you don't know your connection type, what OS?)

There is some sudo password error reporting provided, but it may not be 100% comprehensive.

**Comment by bcoca** [comment]
Tested on current devel and I get:

 FAILED => Incorrect sudo password

from/against ubuntu 12.04.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by JensRantil** [comment]
> What version of Ansible are you using

Version 1.4.1.

> and what connection type?

SSH.

I'm running Ubuntu 10.04.

``` bash
$ python -V
Python 2.6.5
```

**Comment by mpdehaan** [comment]
So given this appears to be fixed in devel I'm going to close this ticket.  Let us know if you experience problems on the 1.5 branch.

Thanks!
