### ISSUE TITLE
Ansible playbook powershell script remote execution : inconsistent output

### ISSUE THREAD

**Issue by Darknight123** [ansible/ansible#52641]
##### SUMMARY

We are trying to execute powershell script through ansible-playbook via win_shell module. Where script has multiple checks and found that for many cases we are getting inconsistent output when run from ansible server. Whereas same script if run locally gives consistent output. For eg - one of the command inside powershell is finding a localuser using command - "net localgroup Administrators | Select-String -Pattern "abc"" , This command if run from ansible-playbook via win_shell module sometimes gives output as 'abc' and sometimes it gives blank stdout. Due to this, conditions checks which are depending on this command gets failed and as a result gives false output. We have tried to run this command separately via adhoc ansible commands but result is same. using ansible 2.6.3. Please assist here as all our checks are getting wrong output if ran from ansible server. Let me know if any details are required.
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
