### ISSUE TITLE
yum: ansible not able to find package

### ISSUE THREAD

**Issue by wgj** [ansible/ansible#527]
ansible-playbook/yum module isn't able to find a package that I can find manually. This issue 'goes away' if I install the package manually.

[wes@mgmt001 ~]$ ssh root@host.domain yum clean all
Loaded plugins: fastestmirror
Cleaning up Everything
Cleaning up list of fastest mirrors

[wes@mgmt001 ~]$ ssh root@host.domain yum list epel-release
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Available Packages
epel-release.noarch                        5-4                        private-repository

[wes@mgmt001 ~]$ ansible-playbook -i /tmp/all_hosts_badtz -f 30 ~/ansible/playbooks/company/company.yml 
<snip>
TASK: [yum: install epel-release] ********************\* 
<snip>
failed: [host.domain] => {"changed": false, "failed": true, "msg": "No Package matching 'epel-release' found available, installed or updated"}

From playbook: 
- name: "yum: install epel-release"
  action: yum pkg=epel-release state=latest

**Comment by mpdehaan** [comment]
I don't know what may be happening here, please ask the list and reopen if we confirm this is an issue with ansible.
