### ISSUE TITLE
Add support for "build-dep" to apt module

### ISSUE THREAD

**Issue by nathanhruby** [ansible/ansible#5270]
As a system administrator I want to install build dependency packages for developer and buildhost machines using the same syntax I install normal packages with.  

It would be useful if one could install build-deps via the apt module instead of mixing and matching apt module and commands for "apt-get build-dep <list of stuff>"

**Comment by mpdehaan** [comment]
so there's already an install_recommends=yes|no so are you thinking this would be like a install_build_deps=yes|no ?

If so, might this be something you would like to work on?

**Comment by nathanhruby** [comment]
That seems like a sane way to handle it.  I've never hacked on ansible modules (still a newish user to ansible) but I can take a stab at adding this over the weekend.

**Comment by nathanhruby** [comment]
Huh, I thought I responded to this, but gmail says I did not, forgive me if
this is a duplicate message.

Sure, that makes sense, I can take a stab at this over the weekend.  I'm
new to ansible and python is not my first or second langauage, so please be
kind during review :-)

Thanks!

-n

On Thu, Dec 12, 2013 at 11:17 AM, Michael DeHaan
notifications@github.comwrote:

> so there's already an install_recommends=yes|no so are you thinking this
> would be like a install_build_deps=yes|no ?
> 
> If so, might this be something you would like to work on?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/5270#issuecomment-30447276
> .

## 

---

nathan hruby nhruby@gmail.com

## metaphysically wrinkle-free

**Comment by nathanhruby** [comment]
made #5296 to add this feature, let the heckling begin!

**Comment by mpdehaan** [comment]
closing ticket now that we have the PR

**Comment by metakermit** [comment]
+1 I would like to see this option released too. Will rely on the shell module for now.
