### ISSUE TITLE
Way to execute command inside virtualenv

### ISSUE THREAD

**Issue by mikepurvis** [ansible/ansible#5278]
I asked about this on SO [here](http://stackoverflow.com/questions/20040141/ansible-command-from-inside-virtualenv).

The generic statement of the problem is "source some setup script, then execute a command". Would there be an openness to adding a parameter onto the command module for this, or even adding a `virtualenv` parameter to match the one available on the pip and easy_install modules?

The current workaround is to create a templated wrapper script which sets up the environment and then runs the command, eg:

```
#!/bin/bash
source /my/env/activate
$@
```

And then in the playbook:

```
- command: do_something arg1 arg2 arg3 executable=/my/env/wrapper
```

This is sufficiently awkward that I think first-class support would be great. Alternatively, I can see about at least see about providing a PR which documents this method on the website for the sake of future travellers.

**Comment by jctanner** [comment]
@mikepurvis development inquiries should be sent to the ansible-devel mailing list. The community developers are more likely to see your question there, and will definitely get you a quicker response.

**Comment by mikepurvis** [comment]
Okay, thanks. I don't think this issue is worth joining the mailing list at this time—I'll just stick with my workaround. If there's interest in a pull request for it in the future, feel free to ping me and I'll be happy to contribute.
