### ISSUE TITLE
Combine ansible_eth[n] and ansible_interfaces

### ISSUE THREAD

**Issue by byronmccollum** [ansible/ansible#5286]
Combine ansible_eth[n] and ansible_interfaces, so that...

`ansible_eth0.ipv4.address`

...becomes...

`ansible_interfaces.eth0.ipv4.address`

Makes dynamically grabbing an IP address based on the interface much cleaner...For instance, let say we have the variable...

`iface: eth0`

Grabbing the address requires a traversal up to hostvars so we can dynamically build the key...

`{{ hostvars[inventory_hostname]["ansible_" + iface].ipv4.address }}`

Using the ansible_interfaces it simply becomes...

`{{ ansible_interfaces[iface].ipv4.address}}`

**Comment by mpdehaan** [comment]
While I understand the idea, this breaks backwards compatibility and cannot be accepted.

It is possible to iterate as you say -- while not optimal, we can't be changing the structure as it would affect too many playbooks.

**Comment by byronmccollum** [comment]
Can you just mirror the interface objects in both places?

**Comment by nightwolfzor** [comment]
+1 we would really like to see this!

**Comment by mikegleasonjr** [comment]
I landed while looking for the same thing.. but turns out I found a way:

```
hostvars[ansible_hostname]['ansible_' + 'eth1'].ipv4.address
```

Better late than never..
