### ISSUE TITLE
pass custom hipchat server?

### ISSUE THREAD

**Issue by brentley** [ansible/ansible#5288]
https://github.com/ansible/ansible/blob/ad837709bdcf1b4d5441bc298369e98531696573/library/notification/hipchat#L75

Can we create a way to specify the hipchat server?  We are running a custom internal hipchat instance, so the URL is different than the default hosted URL.

**Comment by mpdehaan** [comment]
This sounds like a feature request.

As we're not actively using hipchat, the best way to do this is probably for you to submit this feature yourself, or mention it on the mailing list and maybe someone with a hipchat instance could test it?

If you'd like to take a crack at adding a "server" parameter that would be great though!

**Comment by mpdehaan** [comment]
I'm going to close this as we aren't actively working on hipchat things, though if someone would like to submit a pull request this would be gladly accepted.

Thanks!
