### ISSUE TITLE
TaskResult.clean_copy() discards strip_internal_keys() result

### ISSUE THREAD

**Issue by dw** [ansible/ansible#52910]
##### SUMMARY

Per subject. The strip_internal_keys() function returns a copy rather than in-place mutation, but clean_copy() discards the return value.

strip_internal_keys() is responsible for 20% of all result processing overhead in a particular run. (due to TaskQueueManager.send_callback()). If nothing's broken per above, how about we just remove it instead.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lib/ansible/executor/task_result.py

##### ANSIBLE VERSION

devel

##### OS / ENVIRONMENT

Linux

##### EXPECTED RESULTS

strip_internal_keys() return value is used somehow.

##### ACTUAL RESULTS

20% slowdown on (presently) wasted work.

**Comment by dw** [comment]
More pro-removal: that code hasn't been touched since October 2017. Seems more likely something could break by fixing things!

**Comment by bcoca** [comment]
actually, i would keep this (fix) the copy and remove from callbacks and strategy so there is only one spot that uses it
