### ISSUE TITLE
VMware: vmware_cluster field name 'datacenter_name' deviates from convention enforced by other vmware modules

### ISSUE THREAD

**Issue by abensch** [ansible/ansible#52934]
##### SUMMARY
The field name 'datacenter_name' used by the vmware_cluster module does not match the name used by other modules for a similar field titled 'datacenter'. This doesn't break any functionality, but is confusing syntactically.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
2.7.6
```

##### CONFIGURATION

```paste below
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
```

##### OS / ENVIRONMENT

RHEL 7.6

##### STEPS TO REPRODUCE

Seen in official documentation. See [vmware_cluster](https://docs.ansible.com/ansible/latest/modules/vmware_cluster_module.html#vmware-cluster-module)

**Comment by Akasurde** [comment]
!component =lib/ansible/modules/cloud/vmware/vmware_cluster.py

**Comment by Akasurde** [comment]
@abensch Thanks for reporting this issue. This is already been addressed by https://github.com/ansible/ansible/pull/37072

**Comment by Akasurde** [comment]
Closing this issue as PR is merged. If issue persists, please feel free to re-open.
