### ISSUE TITLE
Ansible plugin in rundeck fails to update the nodes

### ISSUE THREAD

**Issue by iam0ky** [ansible/ansible#52938]
##### SUMMARY
Ansible plugin in rundeck fails to update the nodes.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Ansible plugin for rundeck

##### OS / ENVIRONMENT
MAC OS

##### STEPS TO REPRODUCE

###ERROR

"ansible-playbook" (in directory "/var/folders/lp/8tysddbx6t98fyk2znq5wg5c0000gn/T/ansible-hosts6517972527244697441"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.batix.rundeck.core.AnsibleRunner.run(AnsibleRunner.java:475)
	... 57 more
Caused by: java.io.IOException: error=2, No such file or directory

Any sort of help really helps me...

**Comment by sivel** [comment]
Thank you for your interest in Ansible.  However, we do not support the Ansible plugin for rundeck.

Please open an issue with rundeck.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
