### ISSUE TITLE
inventory file parsing broken when line contains two more more ':', such as when using "multiple ranges" or "FQDN with ports"

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#5297]
On devel it appears that if you have two (or more) ':' characters in a host line in your inventory file it breaks the parser.

1)
We use two ranges to define our hosts, first for the bladecenter, then the blade slot, so we have hosts defined like this:

```
[servers]
host-[1:6]-[1:16].example.com
```

gives (Line numbers might be slightly out due to due to extra debugging I've added)

``` python
File "/mnt/data/home/johnb/development/ansible/mine/lib/ansible/inventory/host.py", line 31, in __init__
    self.set_variable('ansible_ssh_port', int(port))
ValueError: invalid literal for int() with base 10: 'com:2222'
```

I believe this is a regression over 1.3.4, possibly caused by https://github.com/ansible/ansible/commit/948d019fef8781b22960859caaa93485a074e339
Though the docs are not that clear if multiple ranges are supported.

Changing lib/ansible/inventory/ini.py

``` python
if hostname.find(".") != -1:
```

to

``` python
# IPv6 Addresses with a port specified will contain exactly one '.' character
if hostname.count(".") == 1:
```

Appears to fix this particular issue.

2)

```
[servers]
host-[1:10].example.com:2222
```

With the above hostname.count(".") fix, doesn't solve the whole problem

As Ansible then looks to connect to
host: host-4-4.example.com:2222
port: 22

I assume expand_hostname_range in lib/ansible/inventory/expand_hosts.py needs some work

I've created some more tests (that fail) and will add them shortly

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/pull/5299 Adds sometests, which will currently fail till the above is fixed

**Comment by mpdehaan** [comment]
So it would be more helpful that instead of writing the test you'd fix it instead :)

**Comment by gundalow** [comment]
@mpdehaan If you are happy with the if hostname.count(".") == 1:
change I'll push that through shortly

I'm not sure what the correct fix for (2) is

**Comment by mscherer** [comment]
Having 2 differents bugs would also be helpful to refer to each fix, and to discuss them separately.

**Comment by gundalow** [comment]
I'll get all of the tidied up, and done "the right way"
closing this.

**Comment by gundalow** [comment]
For the record
1) Is fixed by my patch https://github.com/ansible/ansible/pull/5337
2) Bug raised https://github.com/ansible/ansible/issues/5338
