### ISSUE TITLE
Ansible unable to winrm to Windows Server 2012

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#52991]
##### SUMMARY
1. Using Python 2.7 in RHEL7
2. Executed powershell script in windows machine ConfigureRemotingForAnsible.ps1
3. Configured yml file to the below:

* name: hit windows test instance
  hosts: "tag_class_windows_{{ env }}_{{ ec2_class }}"
  vars:
  ansible_user: Administrator
  ansible_password: {{ password }}
  ansible_port: 5986
  ansible_connection: winrm
  ansible_winrm_server_cert_validation: ignore
  ansible_winrm_operation_timeout_sec: 60
  ansible_winrm_read_timeout_sec: 70
  tasks:
  
  * ec2:
    state: 'absent'
    instance_ids: {{ instance_id }}'
    ec2_region: '{{ ec2_region }}'
    delegate_to: localhost

Error encountered:
fatal: [xxx.xxx.xxx.xxx]: UNREACHABLE! => {"changed": false, "msg": "ssl: HTTPSConnectionPool(host='localhost', port=5986): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fefb0fdf3d0>: Failed to establish a new connection: [Errno 111] Connection refused',))", "unreachable": true}

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
winrm

##### ANSIBLE VERSION
ansible 2.4.3.0

##### CONFIGURATION
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Host: RHEL 7
WinRM to Windows 2012

##### STEPS TO REPRODUCE
ansible-playbook -i /etc/ansible/ec2.py hitwin.yml  --extra-vars "ec2_class=appservers env=test"

* name: hit windows test instance
  hosts: "tag_class_windows_{{ env }}_{{ ec2_class }}"
  vars:
  ansible_user: Administrator
  ansible_password: {{ password }}
  ansible_port: 5986
  ansible_connection: winrm
  ansible_winrm_server_cert_validation: ignore
  ansible_winrm_operation_timeout_sec: 60
  ansible_winrm_read_timeout_sec: 70
  tasks:
  
  * ec2:
    state: 'absent'
    instance_ids: {{ instance_id }}'
    ec2_region: '{{ ec2_region }}'
    delegate_to: localhost

##### EXPECTED RESULTS
Expected success to win rm and shutdown server

##### ACTUAL RESULTS
PLAY [hit windows test instance] ***********************************************

TASK [Gathering Facts] *********************************************************
ok: [xxx.xxx.xxx.xxx]

TASK [ec2] *********************************************************************
fatal: [xxx.xxx.xxx.xxx]: UNREACHABLE! => {"changed": false, "msg": "ssl: HTTPSConnectionPool(host='localhost', port=5986): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fefb0fdf3d0>: Failed to establish a new connection: [Errno 111] Connection refused',))", "unreachable": true}

        to retry, use: --limit @/home/ec2-user/ansible-netenv/hitwin.retry

PLAY RECAP *********************************************************************
xxx.xxx.xxx.xxx                 : ok=1    changed=0    unreachable=1    failed=0

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
