### ISSUE TITLE
Using hostname module raises an error

### ISSUE THREAD

**Issue by jiv-e** [ansible/ansible#5304]
I tried to use the hostname module but it raises an error.

``` sh
ERROR: hostname is not a legal parameter in an Ansible task or handler
```

See: http://www.ansibleworks.com/docs/modules.html#hostname

I ran this command:

``` sh
$ ansible-playbook -i hosts test.yml --private-key=~/.vagrant.d/insecure_private_key
```

Here's my _hosts_ file:

```
[dev]
192.168.56.102
```

Here's my _test.yml_ file:

``` yml

---
- hosts: dev
  user: vagrant
  tasks:
    - ping:
    - hostname: name=newname
```

Ping works, but as soon as I add the hostname call the error is raised.

I'm on the devel branch 1.4.1 release. See also...

``` sh
$ which ansible-playbook
/usr/local/bin/ansible-playbook
$ ansible-playbook --version
ansible-playbook 1.4
$ git log -- library/system/hostname
commit cc3678730c97244efe1e8a2a5b1b0b323a7beb7a
Author: David Hummel <david_hummel@hms.harvard.edu>
Date:   Sat Dec 7 21:10:42 2013 -0500

    Fix issue #5214: hostname persistence on RedHat/CentOS
$ python --version
Python 2.7.5
```

I'm using a clean vagrant precise64 box. Here's the vagrantfile...

``` ruby
Vagrant.configure("2") do |config|
  config.vm.box = "UbuntuPrecise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.network "private_network", ip: "192.168.56.102"

  config.vm.synced_folder "~/Sites/test", "/var/www", id: "vagrant-root", :nfs => false

  config.vm.usable_port_range = (2200..2250)
  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.customize ["modifyvm", :id, "--name", "test"]
    virtualbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    virtualbox.customize ["modifyvm", :id, "--memory", "2048"]
    virtualbox.customize ["setextradata", :id, "--VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end

  config.ssh.username = "vagrant"

  config.ssh.shell = "bash -l"

  config.ssh.keep_alive = true
  config.ssh.forward_agent = false
  config.ssh.forward_x11 = false
  config.vagrant.host = :detect
end
```

I'm using Mac OS X Mavericks as my local machine.

**Comment by mpdehaan** [comment]
This sounds like you are running from a mixed or older environment where it's not finding the hostname module, rather than a problem in Ansible.

What you say here "I'm on the devel branch 1.4.1 release", doesn't quite make sense as 1.4.1 has released, and the development branch corresponds to 1.5

Can you please stop by the mailing list or IRC and we can figure this out?

**Comment by jiv-e** [comment]
With the help of jtanner I was able to solve this.

Originally I followed the instructions to install ansible from source: http://www.ansibleworks.com/docs/intro_installation.html#running-from-source

I probably run 'sudo make install' earlier and somehow I was confused how the system works. At the time of installing the hostname module didn't exist yet.

I deleted these folders and files:
rm -r /Library/Python/2.7/site-packages/ansible
rm -r /private/etc/ansible
rm /usr/local/bin/ansible*
rm -r /usr/share/ansible

I did 'git pull' and 'sudo make install' again and it worked.

**Comment by hjwp** [comment]
I'm seeing this error when running from the 1.8/devel branch, today...

**Comment by hjwp** [comment]
looks like the ansible/modules folder is empty, in the version i got from the zipfile?  i guess it's not including submodules...

**Comment by sivel** [comment]
A zip file download from github will probably not get you what you want.  You may want to look at http://docs.ansible.com/intro_installation.html#running-from-source or pip installing directory from github:

```
pip install -I git+https://github.com/ansible/ansible.git@devel#egg=ansible
```

**Comment by hjwp** [comment]
yep. it's unfortunate that gihub zip files don't suport submodules.  i've gone for the `git+`  solution.  takes ages to do the clone, but it works.
