### ISSUE TITLE
authorized_keys module unable to parse key when run from CLI using a key_string

### ISSUE THREAD

**Issue by KjellTeirlynck** [ansible/ansible#5306]
For my company's control panel we would like to be able to deploy SSH keys to certain users on a certain host. Ansible authorized_keys module is perfect for this and works as inteded using a regular playbook with hardcoded variables.
However, this command will be called upon from the CLI (fired after a form is filled in on the web-app) and it will use the parameters from this form. Clients have also previousily added SSH-Keys to their SSH-library which they can connect to this account and have it deployed to this specific user.

What happens when I run the command from CLI and give it the SSH-key as a CLI-variable (--extra-vars "key=<key_goes_here>") I always receive a parseKey error. In verbose mode the command even splits up ssh-rsa, the key and user@host as if they're several variables, or as if the spaces are being seen as delimiters of some sort?
I have tried escaping it or using different quotating marks. I am using Ansible Version 1.4.1.

---

In short: Can't use SSH-Key as variable with key=-field from authorized_keys module
In detail:

I have a simple playbook as followed:

```
  tasks:
  - name: Add user
    authorized_key: user={{user_name}} key={{key_string}} state=present
```

When running this from the CLI with the following command:

```
ansible-playbook authorizedkey.yml --extra-vars "user_name=test key_string=\'ssh-rsa anActualKeyHere user@host\'"
```

I get the following error

```
failed: [x.x.x.x] => {"failed": true}
msg: this module requires key=value arguments (['user=test', 'key=ssh-rsa', 'anActualKeyHere', 'user@host', 'state=present'])

FATAL: all hosts have already failed -- aborting
```

The key is then not added to authorized_keys

Whereas I expected the key to be added to authorized_keys on the host just as it did with my other ansible playbook (which is the same) that uses hardcoded variables instead of the blade-syntax ones.

**Comment by jctanner** [comment]
@Krapuul please try quoting your key inputs:

```
  tasks:
  - name: Add user
    authorized_key: user="{{user_name}}" key="{{key_string}}" state=present
```

**Comment by KjellTeirlynck** [comment]
Quoting the key inputs in the playbook, and escaping those on the CLI resolved this issue. Thank you very much!
Might I propose a simple example to be included in the documentation under the authorized_keys module?

**Comment by jctanner** [comment]
@Krapuul please file a separate bug for a module docs update or submit a pull request.

**Comment by jitendrabhalothia** [comment]
tasks:
  - name: Added  key to ssh
    authorized_key: user=UserName key="{{ lookup('file', '/home/UserName/.ssh/id_rsa.pub') }}"
