### ISSUE TITLE
synchronize module: understand role paths

### ISSUE THREAD

**Issue by BrianAI** [ansible/ansible#5307]
When trying to run a playbook with the synchronize module, the relative path is relative to where you are executing the playbook from, and it does not follow the roles logic.

Example Playbook:

-- roles/server/files/etc/scripts/test1.txt
-- roles/server/files/etc/scripts/test2.txt

-- roles/server/tasks/keep_files_synchronized.yml
     -->   name: copy files to server
     -->   synchronize: src=etc/scripts/ dest=/etc/scripts/ delete=yes

**Comment by jjshoe** [comment]
@mpdehaan - If you have thoughts on what to look at to make this work, add them here, I might tackle it. Might depends on complexity.

**Comment by Malvineous** [comment]
I just came across this issue too.  As someone new to Ansible it was a bit counter-intuitive given the documentation about roles touts the benefits of using relative paths and that you should use synchronize to copy files recursively, but then when you do that it doesn't actually work!

**Comment by jctanner** [comment]
@BrianAI this should be fixed in devel by 2492c2714a8dfe5dc8de083580a5dcafd61ddb47

The relative basedir will be the inventory filepath or roles/foo/files in the case of role tasks. This is the same pattern we put in the assemble action plugin as well.
