### ISSUE TITLE
Deprecation Warning message pointing to future version doc URL that doesn't exists.  

### ISSUE THREAD

**Issue by aniketkhisti** [ansible/ansible#53120]
##### SUMMARY

Incorrect URL in Deprecation Warning.
The interpreter discovery doc is suggested in the comment but with reference to the version which does not exists yet. It should be either devel or latest. 

I understand that current devel version is going to be 2.8 in future and maybe because of that the documentation URL is pointing to 2.8 version instead of devel. But for now, 2.8 doesn't exists.
IMHO, Its still a poor experience for devel users(developers & beta users) and because devel documentation exists already[1], it should be a matter of code correction.     

@Akasurde  @gundalow is it its a valid bug? If yes, I would like to assign it to myself to fix it.

[1] See expected results.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible/lib/ansible/executor/interpreter_discovery.py

##### ANSIBLE VERSION

```paste below
$ git branch
* devel
```

##### OS / ENVIRONMENT

```
$ uname -r
4.20.3-200.fc29.x86_64

$ python --version
Python 3.7.2
```

##### STEPS TO REPRODUCE

```
$ ansible -m ping localhost
[DEPRECATION WARNING]: Distribution fedora 29 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform 
python for this host. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
127.0.0.1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "ping": "pong"
}
```

##### EXPECTED RESULTS

```
$ curl https://docs.ansible.com/ansible/devel/reference_appendices/interpreter_discovery.html -s -o /dev/null -w "%{http_code}\n" 

200
```
```
$ curl https://docs.ansible.com/ansible/latest/reference_appendices/interpreter_discovery.html -s -o /dev/null -w "%{http_code}\n" 

200
```

##### ACTUAL RESULTS

```
$ curl https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html -s -o /dev/null -w "%{http_code}\n"  

404
```

**Comment by aniketkhisti** [comment]
I just read something in 
lib/ansible/utils/plugin_docs.py
```

def get_versioned_doclink(path):
    """
    returns a versioned documentation link for the current Ansible major.minor version; used to generate
    in-product warning/error links to the configured DOCSITE_ROOT_URL
    (eg, https://docs.ansible.com/ansible/2.8/somepath/doc.html)

    :param path: relative path to a document under docs/docsite/rst;
    :return: absolute URL to the specified doc for the current version of Ansible
    """
```
which confirms, it would not be reproducible on production.
Rather its a corner case of first or last entity in the chicken-egg problem.   
But please feel free let me know if this experience can be improved.

**Comment by nitzmahone** [comment]
@aniketkhisti thanks for reporting that; already had a plan for a fix but hadn't gotten to it yet. Heuristic fix to the doclink generator to detect devel is incoming...
