### ISSUE TITLE
Add module to generate locales in Debian/Ubuntu

### ISSUE THREAD

**Issue by dlee** [ansible/ansible#5314]
When I log into a Debian/Ubuntu system, I get warning message for missing locale:

```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
    LANGUAGE = (unset),
    LC_ALL = (unset),
    LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
```

The standard way to generate locales is by running:

```
dpkg-reconfigure locales
```

However, the above command starts an ncurses UI, which is definitely not something we want for ansible.

**Comment by spk** [comment]
You can also add locales in `/etc/locale.gen` and run `locale-gen`

**Comment by bcoca** [comment]
In general you can use preseeds to avoid prompts/dialogs from
dpkg-reconfigure.

**Comment by jctanner** [comment]
@dlee what are you suggesting we do to resolve this with ansible?

**Comment by dlee** [comment]
I just want to be able to do:

```
---
- name: Create en_US.UTF-8 locale
  locale: name=en_US.UTF-8 state=present
```

**Comment by mpdehaan** [comment]
Something you might like to work on?

(Also might it be less OS specific?)

**Comment by mpdehaan** [comment]
another option might be to develop this as a role for ansibleworks galaxy (releasing this week) where it uses the script module to push over something basic.  But it sounds like a module might be better.

**Comment by mpdehaan** [comment]
closing this ticket since we have the above
