### ISSUE TITLE
If the ansible_managed line is the only change to a template, do not mark it as changed.

### ISSUE THREAD

**Issue by ingmar** [ansible/ansible#5317]
When templating files with {{ ansible_managed }} inside the template, the file is considered changed every time ansible runs because the default ansible_managed contains a timestamp that always changes (and other bits that often change, i.e. when deploying from different machines/users).

It would be good if Ansible would consider the file as unchanged (and not update it) if only that line was changed and no other part of the file, as that would prevent unnecessary work and more importantly, unnecessary restart handlers being invoked.

Perhaps it could be an option on the template module, in case anyone does find the current behavior desirable.

**Comment by bcoca** [comment]
the code the looks if files have changed does a full md5 on the files, so
there would need to be a major rework to accommodate this

I see 3 options:
- don't use date in ansible_managed
- if the template is in version control use the date the file was last
  updated (the issue here is that you can update the data and change the
  result independently).
- put the ansible managed date in an extended attribute (xattr) (or ignore
  as the mtime of the file already should reflect this).

**Comment by ingmar** [comment]
We've currently switched to the first option as a workaround, i.e. we've simply put a static "This file is managed in Ansible, if you fiddle with it here, expect your changes to be overwritten." at the top. But the nice thing about ansible_managed was that it included when, who and from where it was last deployed, all of which are bound to change between updates that may not make any other changes to the file.

Another possibility would be to a) recognize an existing ansible_managed entry (perhaps with markers a la RCS `$Id:$`) in the live file and b) exclude that part from the MD5.

**Comment by bcoca** [comment]
that would require having 2 copies of the file and template w/o that line
to compare md5

**Comment by ingmar** [comment]
You can generate those on the fly. E.g. if the template looks like this:

```
# {{ ansible_managed }}
bla = foo
```

And the file on the server like this:

```
# $Ansible managed: file.conf modified on 2013-12-25 12:00:42 by santa on elf.northpole$
bla = foo
```

Then you chop out the ansible_managed bit on both files (marked by $s, but feel free to pick something smarter) and what you feed into your MD5 function is:

```
# 
bla = foo
```

Which tells you they're the same file. Does that make sense?

**Comment by mpdehaan** [comment]
I understand the request for this, though it would be quite invasive for the way the changed logic works.

And in some essences it's still changing the file.

I don't see this one being fixed.

**Comment by oppianmatt** [comment]
can we possible have a ansible_managed_last_change or something similar that only puts the tag in if the contents has changed? I want to see who changed the file last on the server and I don't want to restart services if the file hasn't actually changed. It should be idempotent, but with that header in the file it isn't, but that header is useful for seeing who ran it last and when.

**Comment by infernix** [comment]
'''
-# Ansible managed: /home/infernix/ansible-playbooks/cluster/roles/ferm/templates/ferm.conf modified on 2014-04-08 01:21:00 by infernix on believe
+# Ansible managed: /home/infernix/ansible-playbooks/cluster/roles/ferm/templates/ferm.conf modified on 2014-04-08 01:05:50 by infernix on xps
'''

A diff like this that is triggering service restarts because of handlers is bad.

I understand that this is non-trivial, but without a fix the ansible_managed variable is useless for any file that has a handler with an action that causes service disruption.

The only solution today is to set ansible_managed in ansible.cfg to a message without any variables, like "Ansible managed - do not edit" so that roles that reference it won't cause this problem.

**Comment by jonhattan** [comment]
So ansible_managed is almost useless...

**Comment by ruudk** [comment]
I hope to see this fixed too. It's really annoying to see services restarted without a reason :(

**Comment by infernix** [comment]
@ruudk just use:

```
[defaults]
ansible_managed = This file is managed by ansible, don't make changes here - they will be overwritten.
```

in `ansible.cfg` in your playbook projects root folder or system wide. If you need to keep a mutation history, the `backup=yes` option in the various module would work if the syslog history is not sufficient.

Edit: changed to `defaults` as per @nauger below.

**Comment by nauger** [comment]
@infernix To chime in here, to save people from pulling out hair.  The config heading is [defaults], so it should read:

```
[defaults]
ansible_managed = This file is managed by ansible, don't make changes here - they will be overwritten.
```

Although-- +1 for changing this behavior (although I understand that's a bit of a tough problem!)

**Comment by eikonomega** [comment]
We've got the same problem that @infernix refers to.  It's defeats the purpose of having intelligent handlers if changes to this tag mark a file as being changed...

**Comment by rbu** [comment]
As others have pointed out, {{ ansible_managed }} is pointless the way it works right now. It should add markers to the file that can be used to normalize the file when deciding changed=True/False.

Please reopen this bug.

**Comment by bryder** [comment]
This causes us troubles as well.

Is there a way to have ansible write the data currently in ansible managed (the person, filepath of the ansible template file  and time the file was modified) into another file? So we can look at that file to see what changed? 

Then the ansible_managed string could say

This file is managed by ansible - see /var/tmp/ansible_changes/<md5_of_pathname>.changes

so there would be one file in /var/tmp/ansible_changes for each changed file that holds the same data we have in ansible_managed.

It would have the pathname, user name and time the source file changed.

 I don't this this is kept in history or syslog. I could be wrong about that. Am I?

**Comment by bcoca** [comment]
I used to save it as an extended attribute (xattr module).

**Comment by bryder** [comment]
So you just set an extended attribute to {{ ansible_managed }} and write something static into the template. Good idea. It'll be OK for a workaround even though it's an extra task. 

It would be nice if ansible could do that in a more transparent way.

**Comment by sumpfralle** [comment]
Adding the 'ansible_managed' variable with its default setting to a template file breaks the change-detection of ansible and causes undesired handler actions.

This is not the good kind of surprise.

Please re-open this issue.
In case that there is no easy way to implement a fix then you should at least change the default value of 'ansible_managed' to a value that does not break the change-detection of ansible (i.e. remove 'uid', 'host' and time-dependent placeholders).

**Comment by memelet** [comment]
Indeed. I was quite surprised to see this. What is the value of using ansible_managed as it is?

**Comment by bryder** [comment]
@memelet - it warns an unwary administrator that file edits will be lost if ansible is run again. And it is useful to know the user and location of the last source file used during a deploy so you know who
to talk to about it.

It is useful from that perspective because we don't have to write that info in by hand. 

But of course the false differences reduce the value greatly.

**Comment by gundalow** [comment]
We use the following, to avoid the file being updated:

```
[defaults]
ansible_managed = Ansible managed file, do not edit directly
```

**Comment by oppianmatt** [comment]
We stick at least the file, uid and host (things that are unlikely to change)

```
ansible_managed = Ansible managed, do not edit directly: {file} by {uid} on {host}
```

That way if someone copies or moves the file you can see what the original file was and what host.

I guess it will change if someone else runs the script.

**Comment by schlueter** [comment]
This appears to have been resolved such that a template containing `{{ ansible_managed }}` will not be changed when that is the only thing changed.

Is this now the expected behaviour?

**Comment by bryder** [comment]
Hi @schlueter  - are you sure about that? I can't find how that's done in the code. The only thing I could find was for that wordpress playbook but I might have been looking in the wrong branch or something (I was looking at develop).

**Comment by jsumners** [comment]
Thank you for the suggesting the playbook local ansible.cfg fix. I 1) didn't know a local ansible.cfg would be uses and 2) this problem was really bugging me.

**Comment by steenzout** [comment]
@schlueter I just tested and it seems to work if you run from the same username / host.
if you use another account you are using to run the playbook or run the playbook on another host it will trigger a `changed` status.

it seems the same thing applies if the modification time of the template is changed even though the content doesn't (touch command, add/delete then ends up with the same content, git clone?).

best way is to set a static message on the `ansible.cfg`.

**Comment by sumpfralle** [comment]
@steenzout: thank you for confirming this behaviour with the current ansible codebase.

If ansible would be designed for the use-case of single-user administration then everything would be ok.
But in fact I consider ansible to be a tool for distributed administration.

Thus I would be happy to see one of the following situations:
- the ansible_managed variable is static by default

OR
- changes of the ansible_managed variable do not trigger the "changed" status of a template operation

From my point of view this would result in the least surprising behaviour.

**Comment by mindreader** [comment]
In my organization some people love ansible_managed and the info it gives (devops) and don't care about services randomly getting restarted during maintenances or being able to see what config files will be changed or what services will be arbitrarily restarted (developers) on the next maintenance causing all sorts of problems and hassle and late night calls.

I realize this is hard to solve, but it is a persistent headache and the only flaw I can really find in ansible.  Please just take a stab at fixing this.

**Comment by steenzout** [comment]
@mindreader I've been defining the `ansible_managed` variable on the `ansible.cfg` and I don't have this problem anymore.

e.g.: https://github.com/ansiblebit/primogen/blob/master/tests/ansible.cfg#L2

I suggest you do it too.

**Comment by sumpfralle** [comment]
@steenzout
this is the point of this thread: the current default value of "ansible_managed" defeats the purpose of a very important feature of ansible: change detection. We can either recommend to everyone that they should change its value on their own or ansible should seed it with a reasonable value. Lack of surprise is certainly a welcome feature.

Please change the default of "ansible_managed" to a sane value. Thank you!

**Comment by zxaos** [comment]
Even better than changing `ansible_managed` to a default that doesn't fire every time, would be changing the way ansible evaluates file differences s that if the `ansible_managed` line was the only thing that changed, the file itself would not be modified at all.

That's a much bigger ask though.

**Comment by chetan** [comment]
Not sure why this would be such a massive change. Can't we just do:

```
cat $file | grep -v 'Ansible managed' | md5sum
```

Even better would be the use of a marker as mentioned at the top of this issue.

**Comment by sumpfralle** [comment]
@chetan: this specific fix would not work for files with a non-line-based syntax. Additionally the 'Ansible managed' part o the string is user configurable - this cannot be done in in code.

The perfect solution would probably involve specific handling of the "ansible_managed" variable (aribitrarily disable/enable for change detection only).
An imperfect (but acceptable) solution could be to change the default of 'ansible_managed' to a fixed string (independent of time and actor).

**Comment by sumpfralle** [comment]
@mpdehaan: you closed this ticket, even though the behaviour described in its title still persists. Please consider re-opening this ticket.
Alternatively you may want to change the title, if you think, that it does not reflect the above discussion.

**Comment by abadger** [comment]
Please open new issues rather than commenting on closed issues.  Closed issues don't get looked at so it's easy to miss seeing reports that a behaviour is still occurring or could be looked at in a different way.

I've opened this issue: https://github.com/ansible/ansible/issues/17947  with a summary of the problems with the default setting of ansible_managed.  As mpdehaan said at the start of this issue, we probably can't change the logic but changing the default value of ansible_managed is a lot less intrusive change.

I'll lock this issue.  if there's more comments needed, please add them to #17947 instead.
