### ISSUE TITLE
ignore-errors in loops are ignored with ssh_alt connection plugin

### ISSUE THREAD

**Issue by PhilEv** [ansible/ansible#5320]
Ansible version: ansible-1.5-0.git201312162123.fc20.noarch.rpm
Running from a F20 control node.

Using the ansible-playbook with -c ssh_alt option lead to a fatal error
 in a loop even if ignore_errors is set to True.
The same commad withtout -c option (smart mode) 0r -c ssh does not fail.

How to reproduce:

have a Play with one task like:
- name: Make sure the following services are turned off
  service: name={{ item }} enabled=no state=stopped
  with_items: disabled_services_list_var
  ignore_errors: True
  tags:
  - service_disable

and with the following variable : 

disabled_services_list_var:
- 'blk-availability'
  - 'certmonger'
  - 'cpuspeed'

Note: that certmonger rpm is not installed in the target system

run the play with -c ssh_alt gives:

TASK: [Make sure the following services are turned off] **********************\* 
changed: [targetsystem] => (item=blk-availability)
fatal: [targetsystem] => SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh

FATAL: all hosts have already failed -- aborting

running without ssh_alt gives:

TASK: [Make sure the following services are turned off] **********************\* 
changed: [targetsystem] => (item=blk-availability)
failed: [targetsystem] => (item=certmonger) => {"failed": true, "item": "certmonger"}
 msg: cannot find 'service' binary or init script for service,  possible typo in service name?, aborting
...ignoring
ok: [targetsystem] => (item=cpuspeed)

PLAY RECAP *******************************************************************\* 
targetsystem        : ok=2    changed=1    unreachable=0    failed=0

**Comment by jctanner** [comment]
@jeromew can you take a look at this?

**Comment by jeromew** [comment]
@jctanner 
should be fixed with https://github.com/ansible/ansible/pull/5321

I think you can merge this as it only impacts ssh_alt + I think this error handling is better than the "catch-all" patch I wrote the other day for the "dark host issue". It would be easier I guess for @PhilEv to test again.

**Comment by jctanner** [comment]
@PhilEv update to HEAD and try again please.

**Comment by PhilEv** [comment]
test passed . Problem fixed
thanks !

Phil

2013/12/17 jctanner notifications@github.com
