### ISSUE TITLE
ssh_alt does not understand -vvvv mode

### ISSUE THREAD

**Issue by jimi-c** [ansible/ansible#5330]
When running "-c ssh_alt" and "-vvvv" (four v's), the SSH connection is still only initiated with 3 v's. Example:

<pre>
$ ansible -m setup -i vagrant_ansible_inventory_awx --private-key=~/.vagrant.d/insecure_private_key all -vvvv -u vagrant -c ssh_alt
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', ...
</pre>

**Comment by jctanner** [comment]
@jeromew can you take a look at this please?

**Comment by mpdehaan** [comment]
Actually this seems to be a little off.

 if utils.VERBOSITY > 3:
            ssh_cmd += ["-vvv"]
        else:
            ssh_cmd += ["-q"]

**Comment by mpdehaan** [comment]
It should send 3 v's to enable SSH debug when ansible is in -vvvv which the above output does.

So I think it seems to be fine.   I am going to close this, you guys can reopen if you disagree.

**Comment by jeromew** [comment]
just as a side note, ssh_alt has the same implementation as ssh on this point

openbsd documentation: 

-v      Verbose mode.  Causes ssh to print debugging messages about its
             progress.  This is helpful in debugging connection,
             authentication, and configuration problems.  Multiple -v options
             increase the verbosity.  The maximum is 3.
