### ISSUE TITLE
Cant white list any variables from clean.py

### ISSUE THREAD

**Issue by MarianoRubio** [ansible/ansible#53335]
##### SUMMARY
I want is to be able to whitelist any variable so that https://github.com/ansible/ansible/blame/9773a1f2896a914d237cb9926e3b5cdc0f004d1a/lib/ansible/vars/clean.py does not get rid of it.

currently i'm just removing

del data[r_key] in line 147... but means patching every version of Ansible....

related to #52935 wrongly closed...
##### ISSUE TYPE
- ~Bug  Report~
- Feature Idea

##### ANSIBLE VERSION

```paste below
ansible 2.7.6
  config file = None
  configured module search path = ['plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.6/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Jan 13 2019, 12:51:54) [Clang 9.0.0 (clang-900.0.39.2)]

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by bcoca** [comment]
The reason we remove those variables is to avoid security issues by disclosing data to callback plugins (which are used for logging/exporting data to other systems), this is by design.

I would ask what exactly do you want to accomplish? Not the implementation details, but the complete picture of what you are trying to achieve.

**Comment by MarianoRubio** [comment]
What i'm trying to do is enhance some of the variables fetched from our dynamic inventories.

I do this to make transparent for the user the personalisation of a common inventory.

I could probably fall to lookup modules to compensate, but this lack a proper cache mechanism and would be reevaluated on every task...  

suggestions are welcome..

**Comment by bcoca** [comment]
callbacks are not the correct spot to do this, see 'constructed' inventory plugin instead https://docs.ansible.com/ansible/latest/plugins/inventory/constructed.html

**Comment by MarianoRubio** [comment]
Yeah contructed plugging will hardcode the lookup for example to pick the value lets say (ansible_user) but the lookup will still execute every time I try to pick the variable right?

Also just spotted a nice feature, the value of any magic variable is exposed in the warning message !!

  display.warning("Removed unexpected internal key in module return: %s = %s" % (key, data[key]))
            del data[key]

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
