### ISSUE TITLE
Implement a generic session caching mechanism

### ISSUE THREAD

**Issue by mariolenz** [ansible/ansible#53361]
##### SUMMARY
Implement a generic session caching mechanism.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
core

##### ADDITIONAL INFORMATION
We've implemented a lot of VMware (SOAP) and RedFish (REST) tasks. Unfortunately, every module opens a new connection for every host... for example: 15 tasks for 100 hosts will result in 1500 connections. This is a lot of overhead. As @ckotte pointed out in #47428 it would be a good idea to cache sessions. I think that Ansible should provide a generic session caching mechanism that modules can use. Otherwise, all modules would have to solve the same problem again and again.

**Comment by bcoca** [comment]
we kind of have one already https://github.com/ansible/ansible/blob/devel/bin/ansible-connection

**Comment by mariolenz** [comment]
> we kind of have one already https://github.com/ansible/ansible/blob/devel/bin/ansible-connection

Thanks, didn't know ansible-connection yet. Is there some kind of documentation or example how this is supposed to be used? I wasn't able to find any but maybe I was just too stupid to google.

**Comment by bcoca** [comment]
only if you count existing code as 'documentation' ....

**Comment by mariolenz** [comment]
I think I can read the code and understand what it _does_, but I'm not sure if that's enough to understand how to _use_ it.

Btw: My idea was to have a session caching mechanism that modules can use but since ansible-connection is located under bin/ it seems to be something different. I've grep'ed for ansible-connection in modules but no module seems to use it. So some kind of documentation and / or examples would be helpful.

@jimi-c You did the first commit of ansible-connection, how did you intend it to be used?

**Comment by bcoca** [comment]
my point was, no we don't have docs.

Yes, this only exists on controller, but modules that handle their own connection normally get run `delegate_to: localhost`. The ones that use this facility automatically do this and that is why they can use ansible-connection.

This is a complex subject due to many factors (including module execution location, cache management, resource limits, throttling, etc) and I am planning on writing a full proposal on this. There are just a lot of kinks to work out to make this generalized and available to all modules vs the 'hackish' way we do this currently for a very specific subset of modules.

**Comment by mariolenz** [comment]
> sorry, i was trying to inject humor, but my point was: no, we don't have docs.

Yes, I thought so. But from

> only if you count existing code as 'documentation' ....

alone I wasn't sure whether you're planning to do something about it or not. Now that you're telling me that you're

> planning on writing a full proposal on this

I'm quite satisfied. I agree that this is a complex subject, so I don't expect a solution in 2.8.

Btw: Thanks for working on this! I really think that this is important to make ansible more efficient.

**Comment by mariolenz** [comment]
@bcoca Any news? Does ansible have a generic session caching mechanism now or are you guys still working on it?

**Comment by bcoca** [comment]
We implemented a version fo this for modules to opt into 

https://github.com/ansible-collections/cloud.common/blob/main/README_ansible_turbo.module.rst

We might still add a similar feature into core but for now I'm going to close this as resolved by the feature above.

**Comment by mariolenz** [comment]
Thanks @bcoca I'll have a look at it.
