### ISSUE TITLE
ansible ignores group_vars if inventory is outside of playbook directory

### ISSUE THREAD

**Issue by amarao** [ansible/ansible#53396]
##### SUMMARY
If inventory is located outside of playbook directory, all group_vars/host_vars directories in playbook directory are ignored.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
plugins/vars/host_group_vars.py

##### ANSIBLE VERSION
```paste below
 ansible --version
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/amarao/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16rc1 (default, Feb 18 2019, 11:05:09) [GCC 8.2.0]
```

##### CONFIGURATION
```paste below
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o Control
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /tmp/%%h-%%r
DEFAULT_SUDO_FLAGS(/etc/ansible/ansible.cfg) = -H -S
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 15
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Ubuntu 18.04

##### STEPS TO REPRODUCE
```sh
cd /tmp
mkdir playbook_directory
echo '"example": {"hosts": {"localhost": {}}}' >inventory.yaml
cd playbook_directory
mkdir group_vars
echo 'foo: bar' > group_vars/example.yaml
ansible -i ../inventory.yaml -m debug -a var=foo example
```

##### EXPECTED RESULTS
```
localhost | SUCCESS => {
    "foo": "bar"
}
```

##### ACTUAL RESULTS
```paste
localhost | SUCCESS => {
    "foo": "VARIABLE IS NOT DEFINED!"
}

```

According to the documentation https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html

Tip: The group_vars/ and host_vars/ directories can exist in the playbook directory OR the inventory directory. If both paths exist, variables in the playbook directory will override variables set in the inventory directory.

This is proven to be wrong. Ansible does not look into group_vars in playbook directory.

**Comment by sumkincpp** [comment]
Isn't this working as expected since you are running ad-hoc module command without playbook?

So, the only path to search is upper directory with inventory, which of course doesn't have group_vars/ and host_vars/.

**Comment by amarao** [comment]
You are absolutely right. It works with playbook as expected. This bug is invalid.

We had had our own issue, which was around location of inventory and playbooks. When I've tried to debug it I got to this testcase with ad-hoc Ansible. But Ansible have a reasonable behavior here, and ansible-playbook does respect group_vars in playbook directory.

**Comment by bcoca** [comment]
Also see `--playbook-dir` option

**Comment by amarao** [comment]
My Ansible (2.7.5) does not have such option (--playbook-dir), but I would be happy if ansible would report it in -vvvvvvvvvv mode.

**Comment by bcoca** [comment]
added in 2.8 for those using 'ahdoc' but wanting 'playbook group_vars/host_vars'
