### ISSUE TITLE
spurious CONDITIONAL_BARE_VARS warnings

### ISSUE THREAD

**Issue by jamescassell** [ansible/ansible#53428]
##### SUMMARY

Suprrious Deprecation warning and regular (non-deprecation) warnings when using boolean vars.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

core

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/ansible-ansible/lib/ansible
  executable location = /home/user/ansible-ansible/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = debug
```

##### OS / ENVIRONMENT

CentOS/RHEL 7, Fedora 29

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: no
  vars:
    mybare: true
    myfalse: false
    mycomplex: "{{ mybare or myfalse }}"
  tasks:
  - debug:
      msg: bare
    when: mybare
  - debug:
      msg: complex
    when: mycomplex
```

##### EXPECTED RESULTS

Results on ansible 2.7:
```
PLAY [localhost] ****************************************************************************************************************************************************************************************************************************

TASK [debug] ********************************************************************************************************************************************************************************************************************************
ok: [localhost] => {}

MSG:

bare


TASK [debug] ********************************************************************************************************************************************************************************************************************************
ok: [localhost] => {}

MSG:

complex


PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

##### ACTUAL RESULTS

Results on devel/2.8

```paste below
PLAY [localhost] ****************************************************************************************************************************************************************************************************************************

TASK [debug] ********************************************************************************************************************************************************************************************************************************
[DEPRECATION WARNING]: evaluating mybare as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This feature will be removed
 in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [localhost] => {}

MSG:

bare


TASK [debug] ********************************************************************************************************************************************************************************************************************************
[DEPRECATION WARNING]: evaluating mycomplex as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This feature will be
removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{ mybare or myfalse }}

ok: [localhost] => {}

MSG:

complex


PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by mz0** [comment]
same here:
```
- name: Flag swap LV found (skip otherwise).
  set_fact: swap_lv=yes
  when: res.stdout == "vg-lv_swap"

- name: Flag swap LV not found (skip otherwise).
  set_fact: swap_lv=no
  when: res.stdout != "vg-lv_swap"

- block:
  - ... (5 tasks omitted)
  when: swap_lv|bool
```
(shown with silencing workaround, without this '|bool' each task in block shows that warning)

```
[DEPRECATION WARNING]: evaluating swap_lv as a bare variable, this behaviour will go away and you
might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS 
configuration toggle.. This feature will be removed in version 2.12. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
```

**Comment by sivel** [comment]
This is a purposeful warning for this situation.

The behavior that it is warning about, relates to how a single bare variable is handled in conditionals.

We have a piece of logic, that can perform unexpected actions that we are deprecating in 2.12.

That logic would enable the following bad behavior:

```
- debug:
    msg: "This should run with 'thing' is the string 'false'"
  when: thing
  vars:
    thing: "false"
```

This task actually gets skipped, instead of run.  A string should be a truthy value, but is unwound in a way that makes it falsy.

Instead of treating that as:

```
{% if thing %}True{% else %}False{% endif %}
```

It instead get's treated as:

```
{% if false %}True{% else %}False{% endif %}
```

**Comment by jamescassell** [comment]
I assume my reproducer playbook will work identically as it does today (2.7) once the deprecation message is gone.  Can an option to be added to squash only this warning?  There is nothing wrong w/ the playbook I described above.

The second warning in the "complex" task for certain seems like a recurrence of a bug that happened a few releases ago.

**Comment by sivel** [comment]
It should work the same.  You can try to silence it by setting `CONDITIONAL_BARE_VARS` to `False` (https://docs.ansible.com/ansible/devel/reference_appendices/config.html#conditinal-bare-vars)

There are issues aside from bool conversion as well.

In the case of `thing: "foo"`, it would be changed to `{% if foo %}` which would give an undefined var error, if `foo` did not exist, or if it existed, it could also give an unexpected outcome.

**Comment by jamescassell** [comment]
So this feature is opt-in for now?  And if I opt-in, it will squash the warning?

**Comment by sivel** [comment]
It is opt-in, and if you opt-in, the warning will disappear.  Once 2.12 lands, the default will swap to `False`, the current default is `True`

**Comment by ChristianCiach** [comment]
Does it make sense to show the warning even if the variable in question is undoubtedly a boolean? There is no difference in this case (as far as I understand this). It doesn't make sense to pipe a boolean variable through the `|bool` filter.

**Comment by dbilling** [comment]
Completely agree with @ChristianCiach -- shouldn't this warning be only issued when a bare **string** variable is used in a conditional?  That would be deserving of a warning. However, this deprecation warning also seems to be issued when a bare **boolean** variable is being used in a conditional. 

Let's look at an example included in ansible's own documentation:  https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#the-when-statement
```
vars:
  epic: true
tasks:
    - shell: echo "This certainly is epic!"
       when: epic
```

Why is this triggering the deprecation warning?   This warning will cause a tremendous tremendous amount of work .. that is  tons of playbooks will need to be rewritten that have conditionals checking bare booleans.  (adding the | bool filter to every naked boolean being checked to make the warning go away)  Wouldn't it make sense to only have the deprecation warning pop out when it's a naked string variable is being evaluated, and not have the warning for a naked boolean variable?

**Comment by ChristianCiach** [comment]
It should also be mentioned that ansible-lint rule E602 explicitly encourages the use of bare-variable conditionals that trigger deprecation warnings now.

**Comment by jamescassell** [comment]
> It should also be mentioned that ansible-lint rule E602 explicitly encourages the use of bare-variable conditionals that trigger deprecation warnings now. https://docs.ansible.com/ansible-lint/rules/default_rules.html

Nothing is really being deprecated, only a default changed.  I agree that it should not be triggered in this case. You can squash these warnings by opting in to the new behavior, which is what everyone wanted anyway from the start.

**Comment by dbilling** [comment]
Opting into the new/future behavior  (i.e. setting conditional_bare_variables to false in ansible.cfg) is only a resonable solution for an end user.  For those that write and maintain roles consumed by others, these spurious warnings create a horrible choice: they will either need to continuously tell all their users to ignore the copious warnings/reconfigure their ansible.cfg file, or, alternatively, make silly changes to the role to make the spurious warnings go away.    Most role maintainers will simply give in, and add a " | bool" filter, even though using the | bool filter on a boolean is a just silly.   This is really a sad situation, and I'm really surprised to see Ansible miss so badly.  Ansible's own examples are create this spurious warning, yet there have been no changes to the examples!

**Comment by sivel** [comment]
After a discussion in our recent IRC meeting (https://meetbot.fedoraproject.org/ansible-meeting/2019-05-30/ansible_public_core_irc_meeting.2019-05-30-15.01.log.html#l-116) we would entertain a PR that tries to further clarify the warning, or restrict it to a smaller subset of conditions.

Accepting the PR would be dependent on the implications of the change and specific implementation, ensuring that we do not cause performance regressions or cause other problems.

**Comment by s-hertel** [comment]
I have opened a tentative solution [here](https://github.com/ansible/ansible/pull/57190) to restrict it to a smaller subset of warnings and would appreciate any feedback.
