### ISSUE TITLE
Error overriding nested role variable from playbook

### ISSUE THREAD

**Issue by btatnall** [ansible/ansible#5352]
```
$ ansible --version
ansible 1.4.1
```

I'm getting an error when I try to override a nested role variable from a playbook.

Example:

appservers.yml

```

---
- hosts: appservers
  roles:
    - common
    - { role: foo, foo: { version: 1.5.1 } }
```

role/foo/vars.yml

```

---
foo:
  version: 1.5.0
```

Output:

```
fatal: [host] => One or more undefined variables: 'dict object' has no attribute 'dir'

FATAL: all hosts have already failed -- aborting
```

Is it possilbe to override nested variables from a playbook? The 'foo: { version: 1.5.1 }' part of my example.

I'd expect the playbook to run with foo.version set to 1.5.1.

Thanks,
Brian

**Comment by mpdehaan** [comment]
Can we see the source to the role "foo" (or is there any task files?)

**Comment by btatnall** [comment]
This was my mistake misunderstanding how variable merge/replace works in ansible. I didn't realize that setting the foo variable in the playbook would override the entire foo hash.

role/foo/vars.yml

```
---
foo:
  version: 1.5.0
  version_name: foo-${foo.version}
```

The task couldn't find foo.version_name because the playbook variable replaced foo with a hash that has no version_name.

Thanks.

**Comment by kareblak** [comment]
@btatnall So how did you overwrite the nested variable?

**Comment by tzookb** [comment]
joining @kareblak question....
