### ISSUE TITLE
hostname provider should create `/etc/hostname` on Debian if it is missing

### ISSUE THREAD

**Issue by timurb** [ansible/ansible#5353]
When defining hostname like `hostname: name=foobar` and when `/etc/hostname` is missing the exception is raised and nothing is done. I guess it behaves in the similar way for RH.

It would be nice if it still worked or a provider had a parameter to control that.

Steps to reproduce:

```
$ rm -f /etc/hostname
$ ansible monitoring -s -m hostname -a name=foobar
monitoring | FAILED >> {
    "failed": true, 
    "msg": "failed to read hostname: [Errno 2] No such file or directory: '/etc/hostname'"
}
```

Version info:

```
$ lsb_release -d
Description:    Debian GNU/Linux 7.3 (wheezy)
$ ansible --version
ansible 1.5 (devel f96f69ece3) last updated 2013/12/16 16:23:13 (GMT +400)
```

**Comment by mpdehaan** [comment]
Can you please paste the exception and the ansible version you are using per instructions in CONTRIBUTING.md?

Thanks!

**Comment by timurb** [comment]
Sure, I've updated the ticket.
