### ISSUE TITLE
RFE: Support awx group by options in ec2 inventory source by always returning `platform` as host var for aws_ec2 inventory plugin

### ISSUE THREAD

**Issue by kdelee** [ansible/ansible#53532]
##### SUMMARY

Support awx group by options in ec2 inventory source by always returning `platform` as host var for aws_ec2 inventory plugin, when unkown provide `""` or `platform_undefined`.

This will help @AlanCoding construct the `platforms` group which is one of the groups we want to make sure we can use in the `group_by` feature of awx.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

lib/ansible/plugins/inventory/aws_ec2.py

##### ADDITIONAL INFORMATION

By always providing a value, even if an empty string, for the `platform` hostvar, we can create the groups we want.

ping @AlanCoding for more info

here is a note from our conversations about this:
> The problem comes down to a weird shortcoming in feature sets. keyed_groups will create an arbitrary number of groups based on an expression you give it, combined with the key. There's no way to not use the key, of course, because unlimited groups could be created so a static name doesn't make sense. groups will let me make a group based off a static name, but that's won't allow me to add it to parent_group, because that was never implemented there. I also can't use groups to add platform_undefined to platforms, because groups only operates on hosts, unlike keyed_groups which operates on hosts and groups.

```yaml

```

**Comment by AlanCoding** [comment]
No this might be my bad, I think this syntax may be working now:

```yaml
keyed_groups:
  - prefix: platform
    key: platform
    parent_group: platforms  | regex_replace('^$', 'undefined')
```

...working on testing that.

**Comment by bcoca** [comment]
`platforms == '' |ternary('undefined', platforms)`

**Comment by AlanCoding** [comment]
one way or the other, I think we'll be able to work around this problem.

**Comment by AlanCoding** [comment]
This was resolved, the `platform_undefined` group and other issues have been working for some time now. I didn't use the above syntax, but I found something that works.

feel free to close this issue
