### ISSUE TITLE
Ansible file should check the python script whether the word is matching in the file in same directory. 

### ISSUE THREAD

**Issue by mushamajay** [ansible/ansible#53545]
##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by mushamajay** [comment]
#### My Ansible playbook is searching a word in another file which is in the same directory.

  - name: copying input to another file
    local_action: copy content= "{{ output }}" dest=/var/lib/awx/projects/Netapp-pbk/useropcollection2.txt
    #owner: root
    #group: root
    #mode: 1777
    #remote_src: yes
  - name: search Lunname in outputfile
    script: /var/lib/awx/projects/Netapp-pbk/useropcollection.py
    owner: root
    group: root
    mode: 1777
    remote_src: yes


###
#Python program
##

import yaml
import yamlordereddictloader

def check():
        datafile = file('/var/lib/awx/projects/Netapp-pbk/useropcollection1.txt')
        found = False
        for line in datafile:
            if vars.name in line:
                found = True
                break

        return found

found = check()
if found:
    print "Matched"
else:
    print "not matched"
************************************

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
