### ISSUE TITLE
Supplying an incorrect sudo password to ansible-playbook causes long timeout

### ISSUE THREAD

**Issue by leximayfield** [ansible/ansible#5358]
Pretty simple.  Try this:

```
ansible-playbook <a_playbook> -Ksu <user>
```

Supply an incorrect password to the prompt.  Ansible will freeze at `GATHERING FACTS`.  It will eventually time out, but it takes a very long time.

**Comment by mpdehaan** [comment]
This should be resolved by upgraded sudo password detection in recent releases, though this could use some verification.

**Comment by jctanner** [comment]
Fixed per https://github.com/ansible/ansible/issues/5888#issuecomment-37854184
