### ISSUE TITLE
config file precedence puts ANSIBLE_CONFIG too low

### ISSUE THREAD

**Issue by jrbl** [ansible/ansible#5359]
The old behavior was that ANSIBLE_CONFIG trumped everything else, and I think this is still desirable. I think it should be:
ANSIBLE_CONFIG
./ansible.cfg
~/.ansible_cfg

But right now it seems to be
./ansible.cfg
ANSIBLE_CONFIG
~/.ansible_cfg

I think this probably changed with #4452

**Comment by mpdehaan** [comment]
in queue to be reproduced, thanks.

(Haven't heard any reports about config loader order so a bit skeptical)

**Comment by mpdehaan** [comment]
I definitely agree with this.  Moving to priority queue.

Current code:

```
p = ConfigParser.ConfigParser()
path1 = os.getcwd() + "/ansible.cfg"
path2 = os.path.expanduser(os.environ.get('ANSIBLE_CONFIG', "~/.ansible.cfg"))
path3 = "/etc/ansible/ansible.cfg"

if os.path.exists(path1):
    p.read(path1)
elif os.path.exists(path2):
    p.read(path2)
elif os.path.exists(path3):
    p.read(path3)
else:
    return None
return p
```

The environment variable should be "path0" above (and path2 should just be the os.path.expanduser)

**Comment by risaacson** [comment]
This was fixed, tested and resolved.
