### ISSUE TITLE
Provide correct command-line when there is a whitespace in a role name

### ISSUE THREAD

**Issue by zart** [ansible/ansible#5364]
Some roles uploaded to galaxy contain whitespaces in their names - https://galaxy.ansibleworks.com/list#/roles/22 for example.

For such roles provided command-line to install should properly quote the argument like `$ ansible-galaxy install "user.some funny role"`

**Comment by mpdehaan** [comment]
Yes, this is true.   Totallly agree!

However, this is not the galaxy bug tracker :)   

We have filed a ticket on this internally and are going to auto-change them to "_" and fix in a upcoming migration.

Thanks!
