### ISSUE TITLE
ansible-galaxy: missing options in help output

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#5368]
Help shows:

```
ansible-galaxy 
Usage: ansible-galaxy [init|info|install|list|remove] [options] ...

Options:
  -h, --help  show this help message and exit
```

expected at least additional:

```
--ignore-errors
--roles-path
--force
```

some thougts:
maybe `--force` should be a synonym for new action `update`?

**Comment by mpdehaan** [comment]
These options are all added when you show ansible-galaxy subcommand --help so I don't see this being a problem.

ansible-galaxy --force wouldn't mean anything

Not sure what you mean about force, perhaps we should discuss on ansible-devel ?
