### ISSUE TITLE
apt module: "upgrade=yes force=yes" does not work

### ISSUE THREAD

**Issue by rakuco** [ansible/ansible#5369]
(This is Ansible 1.4.1)

While trying to manage a Ubuntu 12.04 host, I tried using `ansible -i <inventory> -m apt -a 'upgrade=yes force=yes' <host>` (and later tried the same thing in a playbook), but it failed:

```
stdout: aptitude 0.6.6
Usage: aptitude [-S fname] [-u|-i]
       aptitude [options] <action> ...
  Actions (if none is specified, aptitude will enter interactive mode):

[...]

msg: '/usr/bin/aptitude safe-upgrade' failed: /usr/bin/aptitude: unrecognized option '--force-yes'

FATAL: all hosts have already failed -- aborting
```

If I use `upgrade=dist`, everything works fine.

**Comment by gundalow** [comment]
It's right aptitude doesn't take a --force-yes option, it does however take a --assume-yes option.
In your first example you are using "upgrade" which works via apt-get

In your 2nd you are using "safe-upgrade" which works via aptitude http://www.ansibleworks.com/docs/modules.html#apt

I wonder if https://github.com/ansible/ansible/blob/devel/library/packaging/apt#L323 and https://github.com/ansible/ansible/blob/devel/library/packaging/apt#L327 need updating to change the flag if you are using aptitude (v apt-get)

Or if force shouldn't be used for safe-upgrade

**Comment by jctanner** [comment]
We are already passing "-y" to the command, which appears to be equivalent to "--assume-yes":

```
DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical /usr/bin/aptitude -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" --force-yes  safe-upgrade
```

```
-y             Assume that the answer to simple yes/no questions is 'yes'.
```

We really only need to prevent appending the force option if aptitude is the chosen package manager.
