### ISSUE TITLE
ansible playbook executing to install packages but on remote hosts its not actually installs the packages

### ISSUE THREAD

**Issue by ramanjk** [ansible/ansible#53739]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
tried with both ansible 2.7 and 2.4
```

##### CONFIGURATION

```paste below
default configurations used /etc/ansible/ansible.cfg
/etc/ansible/hosts

[webservers]
server[a:d].example.com

```

##### OS / ENVIRONMENT

centsos 7.6

##### STEPS TO REPRODUCE

```yaml
[root@workstation ~]# cat deploy.yaml
---
- name: deploy nginx
  hosts: all
  tasks:
  - name: install nginx
    yum:
     name: nginx
     state: latest

```

##### EXPECTED RESULTS

PLAY RECAP *****************************************************************************************************************************
servera.example.com        : ok=2    changed=1    unreachable=0    failed=0
serverb.example.com        : ok=2    changed=1    unreachable=0    failed=0
serverc.example.com        : ok=2    changed=1    unreachable=0    failed=0

##### ACTUAL RESULTS

PLAY RECAP *****************************************************************************************************************************
servera.example.com        : ok=2    changed=1    unreachable=0    failed=0
serverb.example.com        : ok=2    changed=1    unreachable=0    failed=0
serverc.example.com        : ok=2    changed=1    unreachable=0    failed=0

```paste below
on remote hosts checked the installed package
[root@serverc ~]# yum list installed nginx
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.mojohost.com
 * epel: reflector.westga.edu
 * extras: mirror.jaleco.com
 * updates: repos.mia.quadranet.com
Error: No matching Packages to list

```

**Comment by ramanjk** [comment]
Its working fine 2 days back,but i don't no what happened now..is this ansible bug facing by all recently..

**Comment by samdoran** [comment]
The results don't seem to match the output of your play. Please run the play with `-vvv`

needs_info

**Comment by bluikko** [comment]
@ramanjk the yum module is working in here in similar setup.

In your RECAP it says `ok=2 changed=1` - it is different from your playbook. Can you please run the playbook again with options `-vvv` as in `ansible-playbook -vvv [...]` and paste output here as suggested earlier?

**Comment by ramanjk** [comment]
Hello All,

Thanks for the response..I just did a mistake while running playbook
command..i.e I used option "-C" in the running command,it prevents the
actual remote execution,it will just show the what are the changes going to
be happen.... issue is resolved.. thanks to all
