### ISSUE TITLE
Finding blank item when iterating a task that has notify

### ISSUE THREAD

**Issue by abdulg** [ansible/ansible#5374]
I have the following task:-

  name: Trigger required handlers
  command: echo 'trigger handlers'
  notify: xxx-{{ item }}
  with_items: [1, 2, 3]
  sudo: yes
  tags: deployer

It gives the following output

TASK: [deploy | Trigger required handlers] ***********************************\* 
changed: [z.z.z.z.compute-1.amazonaws.com] => (item=1)
changed: [y.y.y.y.compute-1.amazonaws.com] => (item=1)
changed: [z.z.z.z.compute-1.amazonaws.com] => (item=2)
changed: [y.y.y.y.compute-1.amazonaws.com] => (item=2)
changed: [z.z.z.z.compute-1.amazonaws.com] => (item=3)
changed: [y.y.y.y.compute-1.amazonaws.com] => (item=3)
ERROR: change handler (xxx-) is not defined

Why is it trying to find handler xxx-?

**Comment by mpdehaan** [comment]
The current design is that notify doesn't happen for each item, but is run if there are any changes in the aggregrate result.  (i.e. if any of the items have changed, then they all fire).

However, I don't really see a problem with detecting that "{{ item }}" is in there (ignoring whitespace) and in that case notifying differently.

It's kind of a half-bug/half-feature request, I think this is the first time some one has tried it this way but I don't see why it shouldn't work provided if there is no item templating in the handler it would still work as expected previously too.

**Comment by abdulg** [comment]
My idea was to have a single playbook into which I could pass a package and a list of handlers. This would allow me to create a generalised deploy playbook for multiple apps.

Frankly I am not convinced that that is the best way. It may be DRY, but I'm leaning towards separate playbooks even if it means repeating myself because maintenance will probably be easier as a result.
