### ISSUE TITLE
you should be able to use "import: /path/to/plays.yml" inside a playbook

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#538]
Use of top level includes would allow playbooks to import other playbooks.   The included file could be a single play or a list of them.

Don't care if they support recursion or not, initially.

**Comment by dagwieers** [comment]
The use-case here is that certain sets of tasks (plays) for certain sets of systems are self-contained. And while (e.g. for provisioning or compliance) they are executed on all your systems (think thousands of systems) together with all other plays (consider provisioning comprise of up to 100 different plays), if you are modifying only a single play (e.g. the ntp configuration) for your environment having to run all 100 plays on all 2000 systems just to get one change across seems overly complicated.

So having different plays in separate "playbooks" that can be executed independently, but can also be included in a larger "provisioning" playbooks seems interesting.

**Comment by mpdehaan** [comment]
The suggestion in chat today I made, which I still think is good, is to allow an include in the playbook to be able to include plays or play books.  

This way your "everything.yml" could include your "ntp.yml".

This would effectively implement tagged resources in a completely different way, and is a lot simpler.

**Comment by mpdehaan** [comment]
Ah, you are commenting on that, versus emailing the list.   Never mind :)

**Comment by mpdehaan** [comment]
done
