### ISSUE TITLE
Mark delegated tasks in the output

### ISSUE THREAD

**Issue by timurb** [ansible/ansible#5390]
It would be nice if the delegated tasks were marked as such in the output.

Currently we don't know where each action is run:

```
TASK: [bounce balancer] **************************** 
```

But we would see that explicitely in the output, something like:

```
TASK@balancer.domain.org: [bounce balancer] **************************** 
```

Not sure which should be format for the string ­— probably we should move the box name to the tail of the line for example.

**Comment by timurb** [comment]
Another possible solution — display actual hostname in ok/notok line.

**Comment by mpdehaan** [comment]
So the task can be delegated at the host level, so it does not make sense to display it at the task line.

The action line about the host is _about_ the host, so it still make sense to display what's in the host loop.

I think what you're asking for is best done by adding a "delaged_to" variable in the JSON that you could see with -v.

**Comment by srgvg** [comment]
>  So the task can be delegated at the host level, so it does not make sense to display it at the task line.
> The action line about the host is about the host, so it still make sense to display what's in the host loop.

I disagree. Sometimes you need to run delegated tasks where the relation with the host is less trivial. When doing a delegated task it can make sense to show it's delegated. seems like a trivial thing to do actually.

Use case: 

I have a health-check role, part (dependency) of another app specific role, which I call 3 times from the master role. In the first invocation, it gets delegated to the other node in the cluster, to check that at least one cluster node is alive while (re-)deploying the current node.

Now I work around this by adding debug tasks to make this difference clear.

**Comment by mpdehaan** [comment]
The delegation can change per host, and it can't fit in the task line.  Definitely can't.

So this seems to be a request to show it in the host line, something like this:

```
 [xyz.example.com on behalf of blarg.example.com] => result
```

Which would be doable.

**Comment by srgvg** [comment]
Yes, I obviously was talking about tasks that get delegated to one fixed host.

**Comment by mpdehaan** [comment]
Hi everyone,

We're keeping track of these lists of requests internally, but are not seeing any traction on this via pull requests, so we're going to close this ticket out -- but I wanted to point out that pull requests for this kind of thing would still be welcome.

Thanks!
