### ISSUE TITLE
Deploy role twice with different settings

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#53919]
##### SUMMARY

Currently it is not documented how to deploy a single role twice with different settings within one playbook.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/Private/ansible-1/lib/ansible
  executable location = /home/user/Private/ansible-1/bin/ansible
  python version = 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]
```

##### CONFIGURATION

```paste below

```

##### ADDITIONAL INFORMATION

I see the question of how to deploy a module twice within one playbook, but with different settings arising many times, but currently there is no documentation on how to do it.

What? For example there is a role that deploys wordpress within a docker container, but the user wants to have two distinct instances on one server. The role does not provide the possibility to deploy both instances in one go.

How? It could be solved by writing a loop that unpacks a list from group/host_vars by using playbooks_blocks and loops.

Why? Running a module twice with different settings is a very basic task for advanced users, but it can be an unsolvable challenge for beginners and because it is an question often ask by beginners, an example should be added to the docs.

**Comment by Akasurde** [comment]
@agowa338 Thanks for reporting this issue. I think this page - [Reusing Roles](https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html) provides the information about how to run role with different settings. Is that what you are looking for ? Let me know. Thanks,

needs_info

**Comment by agowa338** [comment]
> @agowa338 Thanks for reporting this issue. I think this page - [Reusing Roles](https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html) provides the information about how to run role with different settings. Is that what you are looking for ? Let me know. Thanks,
> 
> needs_info

no, it is not, it does not mention how to deploy one role twice within one playbook.

# Example

You have the role: https://chaos.expert/agowa338-ansible/ansible-gitlab-docker that deploys gitlab within a docker container. But you for some reason don't want to have one gitlab server, but two/three/... independent gitlab servers (or wordpress like mentioned earlier).

Currently there is no documentation, that this is even possible, but it is by using `blocks`, specifying the configuration parameters within a list and unrolling that list within a loop associated with that blocks-statement.

**Comment by mkrizek** [comment]
The information is there: https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#role-duplication-and-execution. Any suggestions on how to make it more clear? Thanks!

**Comment by mkrizek** [comment]
needs_info

**Comment by agowa338** [comment]
@mkrizek That is what I mean. It needs to be extended with a better example, like deploying two wordpress instances, may also link to an example project. Also using the shortened syntax like:

```
- hosts: webservers
  roles:
  - role: foo
    vars:
         message: "first"
  - { role: foo, vars: { message: "second" } }
```

could be a problem for beginners. I would recommend rewriting the example to match a group_vars syntax of e.g.:

```
- foo:
  - message: "first"
    other_var: "example"
  - message: "second"
    other_var: "example2"
```
and a example playbook where the variable foo is unroled to invoke the module n-times.

**Comment by Akasurde** [comment]
resolved_by_pr #71440
