### ISSUE TITLE
boolean is stored as string in certatin conditions when returned by Jinja template

### ISSUE THREAD

**Issue by timurb** [ansible/ansible#5392]
When the boolean value is being constructed from Jinja template it sometimes seems to be stored as string (literally "False" or "True") and thus produces incorrect results.

Consider this simple playbook:

```
- hosts: localhost
  vars:
  - foobar: "{{ myvar is defined and myvar }}"

  tasks:
  - debug: var=foobar
  - debug: msg="{{ foobar is defined and foobar }}"
    when: foobar is defined and foobar
```

The last debug message is expected to be skipped but it gets processed as the following:

```
TASK: [debug var=foobar] ****************************************************** 
ok: [localhost] => {
    "foobar": "False"
}

TASK: [debug msg="False"] ***************************************************** 
ok: [localhost] => {
    "msg": "False"
}
```

You can also define `myvar` to be `False` with the same outcome (which is also incorrect).

If I define `foobar` as literally `True` or `False` it works ok. As well it works ok if I use plain `when: foobar` as a condition for the last task.

This should not be related to `debug` provider as I've seen that first for some different provider.
I also see the same behaviour when I define variables in the same way in inventory or `group_vars/all` but not in the playbook.

```
$ ansible --version
ansible 1.5 (devel f96f69ece3) last updated 2013/12/16 16:23:13 (GMT +400)
```

**Comment by mpdehaan** [comment]
Yes, "{{ foo }}" generally produces a string because you might have also said "{{ foo }} bar" and how is it to know, etc?  :)

You should able to fix that up by saying {{ foo | bool }}

Let me know if that doesn't work.

**Comment by timurb** [comment]
Yes, that is fine, I didn't know about cast filters, I'm closing the ticket.

Probably there should be a page in documentation summarizing all filters defined in Ansible as currently this info is a bit sparse.

**Comment by nrser** [comment]
is there any way to actually define the variable as a boolean? i really want to be able to define variables as booleans.

this seems like a pretty big 'gotcha':

```
---
- hosts: localhost

  vars:
    attrs: ['ssd', 'desktop']
    ssd: "{{ 'ssd' in attrs }}" # => u'True'
    laptop: "{{ 'laptop' in attrs }}" # => u'False'

  tasks:
  # works fine
  - debug: msg="i am a laptop!"
    when: laptop

  # works fine
  - debug: msg="i have an SSD"
    when: ssd

  # does NOT work as expected
  - debug: msg="i am a laptop with an SSD"
    when: laptop and ssd
```

**Comment by bcoca** [comment]
try:

```
 laptop: "{{ 'laptop' in attrs|bool }}"
```

also we don't normally see comments on closed tickets, I just happened to stumble across this one.

**Comment by nrser** [comment]
thanks, but that doesn't seem to help.

i had to add parens `laptop: "{{ ('laptop' in attrs) | bool}}"` but the variable is still getting defined as the string `"False"`. i imagine that it won't matter what expression i put inside `"{{ ... }}"`, it will produce a string.

the issue is that the variable assigner takes the string `"False"` to mean the string `"False"`, while the `when` conditional takes the string `"False"` to mean the boolean `False`.

should i start a new ticket for this?

i don't see any solution that wouldn't potentially cause significant changes in behavior, but the current implementation certainly tripped me up, and i'm sure i'm not the only one. since we're talking about system configuration here, mistakes like this can have a pretty serious impact.

**Comment by bcoca** [comment]
It is not as much how it is stored as how when: evaluates them, the following 2 cases seem to work:

```
    when: "{{laptop|bool and ssd|bool}}"
```

and

```
    when:
        - "{{laptop|bool}}"
        - "{{ssd|bool}}"
```

**Comment by LeeseHe** [comment]
Seems bool is not supported anymore? I have this in template: "{{fabric|bool}}" but seeing the following error. Is there any other way to cast the string in boolean?  The template is in yaml.

jinja2.exceptions.TemplateAssertionError: no filter named 'bool'
