### ISSUE TITLE
Add OS X support to user module

### ISSUE THREAD

**Issue by tomtaylor** [ansible/ansible#5393]
It'd be great to have OS X support in the user module. It uses a completely different mechanism for managing users from other *nix OSes, but it's all scriptable. 

Leaving this here for me to pick up sometime, if someone else doesn't beat me to it.

**Comment by mpdehaan** [comment]
Yes, it would.

Something you would like to work on perhaps?

**Comment by HelloGrayson** [comment]
+1 - would love to be able to configure developer environments with ansible as opposed to boxen (puppet)

**Comment by mpdehaan** [comment]
Hi,

We've keeping track of this list but haven't seen any traction here, so are closing this ticket out.  If someone would like to submit a pull request, that would be welcome, and we're still open to it.

**Comment by anthonygreen** [comment]
Was this added with the merger of https://github.com/ansible/ansible-modules-core/pull/66 ?
