### ISSUE TITLE
bug with utf8 encoded env variables

### ISSUE THREAD

**Issue by dbrgn** [ansible/ansible#5395]
Ansible cannot handle utf8 encoded environment variables ([mpd] referring to variables in the environment keyword). Both systems (local and remote) default to UTF8 encoding in bash. The "problematic" env variable is a database password with an umlaut in it.

Example:

``` yaml
# test.yml

---
- hosts: webservers
  gather_facts: no

  tasks:
  - name: Set a regular env variable.
    shell: echo $FOO
    environment:
      FOO: foo
  - name: Set an utf8 env variable.
    shell: echo $SNOWMAN
    environment:
      SNOWMAN: snowman ☃☃☃ snowman
```

The first command succeeds, while the second command fails:

```
ansible-playbook -i stage test.yml -vv
...
TASK: [Set a regular env variable.] *******************************************
changed: [10.10.10.2] => {"changed": true, "cmd": "echo $FOO ", "delta": "0:00:00.001388", "end": "2013-12-22 01:19:21.767871", "rc": 0, "start": "2013-12-22 01:19:21.766483", "stderr": "", "stdout": "foo"}

TASK: [Set an utf8 env variable.] ********************************************* 
<10.10.10.2> REMOTE_MODULE command echo $SNOWMAN #USE_SHELL
fatal: [10.10.10.2] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 394, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 485, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 685, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/action_plugins/normal.py", line 54, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 299, in _execute_module
    environment_string = self._compute_environment_string(inject)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 281, in _compute_environment_string
    result = "%s=%s %s" % (k, pipes.quote(str(v)), result)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 8-10: ordinal not in range(128)
```

**Comment by mpdehaan** [comment]
Hi,

Quick FYI -- I notice you are still using the legacy variable syntax, please note we're moving universally to {{ snowman }} and legacy variable support will be removed in 1.5.

Per Contributing.md, please share what version of Ansible you are using?

Thanks!

**Comment by mpdehaan** [comment]
I notice you mentioned a database password, were you trying to pass that via an environment variable BTW?  Or perhaps something else?

Thanks!

**Comment by dbrgn** [comment]
This is not the legacy syntax, this is the syntax for echo-ing an environment variable :) Or at least that's what it seems to do when running the command.

My ansible version:

```
$ ansible --version
ansible 1.4.1
```

**Comment by dbrgn** [comment]
> I notice you mentioned a database password, were you trying to pass that via an environment variable BTW? Or perhaps something else?

Yes, my webapp (Django) is reading the database credentials from the environment variables, similar to the way Heroku does it.

**Comment by lichesser** [comment]
Check my referenced commit above for a proposal on how to fix this bug.

The exception is caused by the `str(v)` call inside `pipes.quote`.
I assumed the `str()` call is there to convert the environment variable value to string in case it isn't of type string/unicode already.

Of course this assumption might be wrong.  Maybe @mpdehaan can provide further info as he did f7497e75e5d04dd02bc2c3fddd0cc2ad4b5a8b31

**Comment by jimi-c** [comment]
The above patch should resolve the issue for you. Please let us know if you continue having problems with this. Thanks!
