### ISSUE TITLE
hashes ('#') within strings are not parsed as expected (treated as external comments)

### ISSUE THREAD

**Issue by bostrick** [ansible/ansible#5396]
unexpected behavior:

```
lineinfile: dest=/etc/hosts regexp="provision"
            line="{{build_env.provision_ip}}  provision #BUILD"
```

generates the error:

```
  File "/usr/lib64/python2.6/shlex.py", line 172, in read_token
raise ValueError, "No closing quotation"
```

while removing the hash from within the quote:

```
    lineinfile: dest=/etc/hosts regexp="provision"
            line="{{build_env.provision_ip}}  provision BUILD"
```

parses cleanly.

(backslash-escaping the '#' works as well, but is an unexpected requirement)

**Comment by mpdehaan** [comment]
Thanks and I understand your request, however we're using YAML libraries for parsing here, so this isn't going to change.  You will need to backlash the #.
