### ISSUE TITLE
remove mysql user fail

### ISSUE THREAD

**Issue by r0bj** [ansible/ansible#5398]
Default ubuntu mysql instalation and anonymous user:

mysql> select host,user from user where user = '';
+-----------+------+
| host      | user |
+-----------+------+
| c01       |      |
| localhost |      |
+-----------+------+

mysql> select host,db,user from db;
+------+---------+------+
| host | db      | user |
+------+---------+------+
| %    | test    |      |
| %    | test_% |      |
+------+---------+------+

Removing anonymous user via ansible:
mysql_user: name='' host=localhost state=absent
mysql_user: name='' host=c01 state=absent
This works ok.

But removing user ''@'%' does not work:
mysql_user: name='' host=% state=absent

Mysql query for that: drop user ''@'%' works fine and removes privileges.

So there is no way to remove mysql privileges for anonymous user and db test.

ansible version 1.4.2

**Comment by mpdehaan** [comment]
So the module is intended to take a username, not a "host=" and all of the above.

Further, you are not passing in consistent quotes, so I imagine you're running something very different from what you posted.

Please stop by the mailing list and we can help you work through this.
