### ISSUE TITLE
Add ability to insert contents of another file in templates

### ISSUE THREAD

**Issue by dlee** [ansible/ansible#5402]
Hi,

In a template, I would like to do something like this:

``` jinja2
This is my name:
{{ file/path/to/my/name.txt }}

This is my address:
{{ file/path/to/my/address.txt }}
```

Perhaps this is already possible, but I couldn't figure out how to do it.

**Comment by bcoca** [comment]
{% include file/path/to/my/address.txt %}

the template system is jinja2 you can find more docs on it:
http://jinja.pocoo.org/docs/templates/

**Comment by mpdehaan** [comment]
Closing per above

In the future, if you have questions, please ask them on the mailing list.
