### ISSUE TITLE
Seems to ignore ssh user flags, always uses root

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#5403]
I am using ansible 1.4.3.

I have been trying to track down a bug in the Vagrant Ansible provider.

I discerned the shell command that Vagrant executes when running Ansible.

I trimmed it down, and tried running it myself.

```
%ansible-playbook -u vagrant --private-key=/Users/bryanhunt/.vagrant.d/insecure_private_key --inventory-file=/common/picsolve-ansible/u12.04/vagrant_ansible_inventory_default  -vvvv ../playbooks/base.yml  | head

...
<127.0.0.1> ESTABLISH CONNECTION FOR USER: root
<127.0.0.1> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/bryanhunt/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=2222', '-o', 'IdentityFile=/Users/bryanhunt/.vagrant.d/insecure_private_key', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '127.0.0.1', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1387807463.55-22242219147459 && echo $HOME/.ansible/tmp/ansible-1387807463.55-22242219147459'"]
```

Then because it connected as the wrong user (root)

```
fatal: [default] => SSH encountered an unknown error. The output was:
```

OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011

If you look at the output above, you will notice that the EXEC ssh which ansible is running specifies to use 'User=root'.

No matter what permutation of flags I try, I cannot get it to connect using any other user.

With Vagrant, I need it to use the vagrant user and then sudo execute the commands. 

The contents of the inventory file, '/common/picsolve-ansible/u12.04/vagrant_ansible_inventory_default' are as follows. 

```
default ansible_ssh_host=127.0.0.1 ansible_ssh_port=2222
```

Have I missed something silly, or is this a bug?

**Comment by ghost** [comment]
If I update the inventory file AND change the command then it runs correctly.

```
ansible-playbook -u vagrant --private-key=/Users/bryanhunt/.vagrant.d/insecure_private_key --inventory-file=/common/picsolve-ansible/u12.04/vagrant_ansible_inventory_default -s -vvvv ../playbooks/base.yml
```

Here's the updated inventory file

```
default ansible_ssh_host=127.0.0.1 ansible_ssh_port=2222 ansible_ssh_user=vagrant
```

So it seems to only pick up the ssh user setting from the inventory file, unfortunate as Vagrant does not seem to be writing that config to it.

**Comment by ghost** [comment]
And finally here's what Vagrant is trying to do.

[default] Running provisioner: ansible...
      ansible-playbook
      --private-key=/Users/bryanhunt/.vagrant.d/insecure_private_key
      --user=vagrant
      --inventory-file=/common/picsolve-ansible/u12.04/vagrant_ansible_inventory_default
       --sudo
       -vvvv
        ../playbooks/base.yml
        {:env=>{"ANSIBLE_FORCE_COLOR"=>"true", "ANSIBLE_HOST_KEY_CHECKING"=>"false",  "PYTHONUNBUFFERED"=>1}, :notify=>[:stdout, :stderr], :workdir=>"/common/picsolve-ansibl/u12.04"}

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
127.0.0.1> ESTABLISH CONNECTION FOR USER: root^[[0m
127.0.0.1> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/bryanhunt/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=2222', '-o', 'IdentityFile=/Users/bryanhunt/.vagrant.d/insecure_private_key', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '127.0.0.1', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1387809779.74-186156305972782 && echo $HOME/.ansible/tmp/ansible-1387809779.74-186156305972782'"]^[[0m
fatal: [default] => SSH encountered an unknown error. The output was:

**Comment by ghost** [comment]
So if there is no default set, is it correct for Ansible to ignore the ssh user setting when it is set on the command line for ansible-playbook ?

**Comment by mpdehaan** [comment]
The vagrant provisioner is part of the Vagrant project, not Ansible, so I can't do anything with this ticket.

**Comment by ghost** [comment]
Hi Michael, I am aware of that. I'm creating a patch for that project.

The reason I created this ticket was to verify that Ansible behavior was correct, i.e that it is necessary to specify the --user=x in the command line, and also ansible_ssh_user=x in the inventory file.

Perhaps this behavior is intentional, but considering the plugin-in messed it up, and I couldn't figure it out, this might be a breach of DRY principles. 

Or perhaps this is intended behavior, I don't know.

**Comment by gildegoma** [comment]
For the records: The effective user (root) is set from the play definition (which has higher priority than `--user` argument). See also ansible/ansible#1518.
