### ISSUE TITLE
Debugging modules add callstack/invocation hierarchy

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#54110]
##### SUMMARY
While debugging a module it occurred, that some assumptions are misleading and there is no documentation to guide the right way. Therefore I want to request documenting the callstack of how ansible invokes modules. E. G. What happens step by step when one runs the temp file from .ansible/tmp/ansible-tmp-*/*.py manually.
From an beginners standpoint it looks strange to find an inline zip file (`invoke_module` function) and load that zipfile as library and than mock an variable into that module and than invoke another module that relies on that mocking, but honestly I don't know how one would write that in a sane way...

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
https://docs.ansible.com/ansible/devel/dev_guide/debugging.html#debugging

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/Private/ansible-1/lib/ansible
  executable location = /home/user/Private/ansible-1/bin/ansible
  python version = 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Archlinux

**Comment by jctanner** [comment]
Having the debugging doc link to https://docs.ansible.com/ansible/devel/dev_guide/developing_program_flow_modules.html#ansiballz-framework might help provide better context for the readers.

**Comment by agowa338** [comment]
I also would suggest adding a callstack/invocation path:

ansible-playbook -> remote script within .ansible/tmp/ansible-tmp-*/AnsiballZ_vmware_guest.py -> extracting embedded zip and placing the module file within /tmp, setting up the environment by mocking `basic._ANSIBLE_ARGS = json_params` -> the module /tmp/module.py

**Comment by samdoran** [comment]
The debugging docs were recently updated. We do have a detailed [explanation of how AnsiballZ](https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#ansiballz-framework) works, but a simple example would be helpful to add to the docs.

**Comment by s-hertel** [comment]
The documentation seems to have been improved (both the debugging docs and AnsiballZ framework documentation), so I'm closing this, but if you have ideas on how to further improve it, please reach out on IRC or the mailing list (or submit a PR!).


   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
