### ISSUE TITLE
Ansible is failing due to Python Exceptions

### ISSUE THREAD

**Issue by adurthisridhar** [ansible/ansible#54128]
##### SUMMARY
I am trying to execute a python script calling from Ansible playbook. While I am executing ansible playbook, I am getting below exception

TASK [sridhar-test : Set Tesgting facts] **************************************************************************************************************************************************************
fatal: [xx.xx.xx.xx]: FAILED! => {"changed": false, "msg": "list index out of range"}

my python code is about 400 lines and for some values it is getting executed successfully and for some it is not. I am not able to find in which line exactly it is failing. Is there any possibility to do that?

##### ISSUE TYPE
- Out of range exception

##### COMPONENT NAME
Ansible

##### ANSIBLE VERSION
ansible 2.7.5

```

##### CONFIGURATION

##### OS / ENVIRONMENT
Linux

##### STEPS TO REPRODUCE

##### EXPECTED RESULTS

##### ACTUAL RESULTS

**Comment by mkrizek** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
