### ISSUE TITLE
setup module doc

### ISSUE THREAD

**Issue by hyao** [ansible/ansible#5417]
On page http://www.ansibleworks.com/docs/modules.html#setup

In the code snippet, there's the following lines:

`# Display only facts returned by facter.
ansible all -m setup -a 'filter=ansible_eth[0-2]'`

The comment should be something like:
`# Display Ethernet interfaces eth0, eth1, eth2`

**Comment by mpdehaan** [comment]
Thanks for the heads up, in the future this document is in source control in library/system/setup if you would like to submit a pull request.

Fixing this now
