### ISSUE TITLE
digital_ocean module docs

### ISSUE THREAD

**Issue by hyao** [ansible/ansible#5418]
On page http://www.ansibleworks.com/docs/modules.html#digital-ocean
In the code snippet section where name=my_new_droplet

When I ran the example, I get:
`failed: [127.0.0.1] => {"failed": true, "item": ""}
msg: Name Only valid hostname characters are allowed. (a-z, A-Z, 0-9, . and -)`

Guess a change from my_new_droplet to my-new-droplet would fix it.

**Comment by mpdehaan** [comment]
Thanks, I'll take care of this now.

**Comment by mpdehaan** [comment]
This will appear when we next push docs, likely around 1/1
