### ISSUE TITLE
RFE: Create ovirt_configure module

### ISSUE THREAD

**Issue by tmichett** [ansible/ansible#54199]
##### SUMMARY

Create module to allow configuration of parameters in RHV/oVirt. This module would specifically allow configuration of items in Administration => Configure. 

Initially the request was for ovirt_configure_instances to be able to create instance types through Ansible. However, there is also a need to be able to create/define roles with an Ansible playbook.

##### ISSUE TYPE
- Feature Idea

ovirt_configure module could do the following:

instance_types:
- define new instance types with all parameters. Similar to defining a VM. This component would have very similar dictionaries and lists of a VM (console, memory, etc.)

roles:
- Ability to create new custom roles and assign functions to that role.

##### COMPONENT NAME

ovirt_configure

##### ADDITIONAL INFORMATION

This module would be used to automate the creation of new instance types and custom roles among other functions. It would allow administrators to run a playbook to create a repeatable RHV configuration without the need of using the RHV-M WebUI. Currently, Ansible doesn't provide a method of performing Administration => Configuration tasks.

```yaml

```

**Comment by tmichett** [comment]
[11_Configuring_VM_System_Types_Lab.pdf](https://github.com/ansible/ansible/files/2994201/11_Configuring_VM_System_Types_Lab.pdf)

**Comment by tmichett** [comment]
[12_Config_RHVM_Custom_Roles_Lab.pdf](https://github.com/ansible/ansible/files/2994205/12_Config_RHVM_Custom_Roles_Lab.pdf)

**Comment by tmichett** [comment]
Updated with attachments describing at least two (2) problems this will solve.

**Comment by mnecas** [comment]
+label ovirt

**Comment by mnecas** [comment]
@machacekondra  @mwperina

**Comment by sivel** [comment]
!component =lib/ansible/modules/cloud/ovirt/
