### ISSUE TITLE
roles_path not being picked up from ~/ansible.cfg

### ISSUE THREAD

**Issue by tant4lus** [ansible/ansible#5423]
Ansible does not appear to be picking up the roles_path from what I have setup in ~/ansible.cfg

I don't have Ansible installed in default location and running it from a github clone.  So I'm using doing `./hacking/env-setup` with an ansible.cfg in my home dir.

```
mtan$ cat VERSION 
1.4.3

mtan$ ansible-galaxy install bennojoy.nginx
 no version specified, installing master
 - downloading role from https://github.com/bennojoy/nginx/archive/master.tar.gz
 - extracting bennojoy.nginx to /etc/ansible/roles/bennojoy.nginx
Error: you do not have permission to modify files in /etc/ansible/roles/bennojoy.nginx
bennojoy.nginx was NOT installed successfully.
You can use --ignore-errors to skip failed roles.

mtan$ grep role ~mtan/ansible.cfg 
# additional paths to search for roles in, colon seperated
roles_path    = /Users/mtan/Code/Ansible/ansible/roles

mtan$ ls -l /etc/ansible*
ls: /etc/ansible*: No such file or directory
```

**Comment by mpdehaan** [comment]
Old versions of ansible-galaxy don't know about the roles path. 

The version in 1.4.3 does, but "cat VERSION" doesn't mean you are necessarily running that version.

Please stop by the mailing list if you can't sort it out.

Thanks!

**Comment by talishte** [comment]
You can use the -p option for path, Like:

ansible-galaxy install bennojoy.nginx -p ~ANSIBLE_HOME/roles

or

ansible-galaxy install bennojoy.nginx -p  /home/$HOME/ansible-versions/ansible1.7/roles
