### ISSUE TITLE
add more magic variables

### ISSUE THREAD

**Issue by liuyangc3** [ansible/ansible#54301]
##### SUMMARY

ansible_play_group

‘current’ active group name in the current task

playbook_file

The playbook yaml file that was passed to the ansible-playbook command line

role_name

The role name for the ‘current’ host being iterated over in the play

##### ISSUE TYPE
- Feature Idea, to get more infomation when execute tasks

**Comment by mkrizek** [comment]
`role_name` already exists.

**Comment by liuyangc3** [comment]
@mkrizek there is a `role_names` described in  https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html, and this refs all role's names imported into the current play. and `role_name` refs a `current` executing role in play.

**Comment by mkrizek** [comment]
See https://docs.ansible.com/ansible/devel/reference_appendices/special_variables.html which is up to date.

**Comment by mkrizek** [comment]
`role_name` does work, it just hasn't been documented properly.

**Comment by bcoca** [comment]
`ansible_play_group` won't work as `hosts:` gets resolved to a list of hosts, we don't use groups other than for selection and they are just a 'host property' in the play (`group_names`), and all hosts are always part of at least 2 groups, but not limited to that.

**Comment by bcoca** [comment]
closing as per above
