### ISSUE TITLE
ansible yum module still search for proxy when proxy is disabled in yum.conf

### ISSUE THREAD

**Issue by liuyangjason** [ansible/ansible#54306]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.7.8
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS Linux release 7.6.1810 (Core)

##### STEPS TO REPRODUCE

put follow 3 lines into /etc/yum.conf
proxy=_none_
proxy_username=
proxy_password=

yum works properly. But ansible yum module fails to work. ansible yum module still try to search http proxy configuration

```yaml
ansible localhost -m yum -a "name=https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm state=present"
```

##### ACTUAL RESULTS

```paste below

```

**Comment by mkrizek** [comment]
With both yum CLI and Ansible yum module I get:
```
Error parsing "proxy = 'none'": URL must be http, ftp, https, socks4, socks4a, socks5 or socks5h not ""
```

Tested with CentOS 7.6.1810 and yum-3.4.3-161 on the managed node.

Which I think is expected behavior since you specifed `none` as a proxy which is an incorrect value. I don't think this is a bug.

**Comment by mkrizek** [comment]
needs_info

**Comment by liuyangjason** [comment]
i think it is bug because the ansible yum module is to mimic yum and yum can work properly while ansible yum module does not work properly.

**Comment by mkrizek** [comment]
> ... yum can work properly ...

As I already mentioned in my previous comment, that is not true according to my testing. Providing more detailed output:

```
[mkrizek@localhost ~]$ cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 

[mkrizek@localhost ~]$ rpm -q yum
yum-3.4.3-161.el7.centos.noarch

[mkrizek@localhost ~]$ grep proxy /etc/yum.conf 
proxy=none
proxy_username=
proxy_password=

[mkrizek@localhost ~]$ sudo yum install https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
[sudo] password for mkrizek:
Loaded plugins: fastestmirror, product-id, search-disabled-repos, subscription-manager
Options error: Error parsing "proxy = 'none'": URL must be http, ftp, https, socks4, socks4a, socks5 or socks5h not ""
```

Can you provide more information about your environment/what I am doing differently?

needs_info

**Comment by liuyangjason** [comment]
[vagrant@lonelyslot ~]$ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
[vagrant@lonelyslot ~]$ rpm -q yum
yum-3.4.3-161.el7.centos.noarch
[vagrant@lonelyslot ~]$ grep proxy /etc/yum.conf
proxy=_none_
proxy_username=
proxy_password=
[vagrant@lonelyslot ~]$ sudo yum install https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
nodesource-release-el7-1.noarch.rpm                                                                                                                        | 8.6 kB  00:00:00
Examining /var/tmp/yum-root-roa_Uu/nodesource-release-el7-1.noarch.rpm: nodesource-release-el7-1.noarch
/var/tmp/yum-root-roa_Uu/nodesource-release-el7-1.noarch.rpm: does not update installed package.
Error: Nothing to do
[vagrant@lonelyslot ~]$

**Comment by mkrizek** [comment]
Thank you for the actual output. I still can't reproduce your issue though.

What value did you actually set `proxy` to? In your output I notice `none` is rendered in _italics_ as _none_.

I still think we should not tolerate invalid configs though.

needs_info

**Comment by liuyangjason** [comment]
if possible, you can reproduce it by using vagrant.
(1) vagrant init  geerlingguy/centos7
(2) install and configure vagrant-proxyconf plugin. make proxy.enbaled to be true
(3) vagrant up and provision
(4) vagrant halt
(5) make proxy.enabled still to be true. But empty proxy.http|https|no_proxy
(6) vagrant up
(7) try yum and ansible yum module.

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by nvtkaszpir** [comment]
I believe the reporter forgot to wrap yum config in triple backticks, thus markdown renders the value as 'none' in italics.
Also in my case the issue was caused by vagrant-proxyconf plugin (2.0.1) under vagrant 2.2.2. Re-creating vms from scratch, no time to debug further.
