### ISSUE TITLE
support backup option in file module

### ISSUE THREAD

**Issue by phraktle** [ansible/ansible#5433]
A feature idea: it would be useful to support the backup mechanism in file, similar to copy/template/etc.

My particular use case involves updating a symlink occasionally to point to a different location (e.g. a new version of a deployed asset, etc). It would be nice to retain a backup of where the symlink was previously pointing.

**Comment by mpdehaan** [comment]
the current backup system leaves remote backups and I'm not really sure how this would work, so I'm going to close this ticket

However, if you'd like to have a discussion about the backup system on ansible-devel mailing list, I would be very interested in talking about it more.

Thanks!
