### ISSUE TITLE
127.0.0.2 errors when running tests

### ISSUE THREAD

**Issue by msabramo** [ansible/ansible#544]
When trying to run the tests via `make tests`, I get a bunch of errors like this:

```
======================================================================
FAIL: test_template (TestRunner.TestRunner)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/marca/dev/git-repos/ansible/test/TestRunner.py", line 129, in test_template
    "metadata=%s" % metadata
  File "/Users/marca/dev/git-repos/ansible/test/TestRunner.py", line 77, in _run
    assert "127.0.0.2" in results['contacted']
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
DEBUG: using args=src=/Users/marca/dev/git-repos/ansible/test/sample.j2 dest=/Users/marca/dev/git-repos/ansible/test/test_data/sample.out metadata=/Users/marca/dev/git-repos/ansible/test/metadata.json
RESULTS={'dark': {'127.0.0.2': {'msg': 'FAILED: timed out', 'failed': True}}, 'contacted': {}}
```

Do I need to set up another IP address on my machine?

I am running this on OS X; I wonder if other OS's automatically map 127.0.0.2 to localhost?

**Comment by mpdehaan** [comment]
these are live tests, it couldn't SSH

**Comment by willthames** [comment]
Still seeing this issue today.

If 127.0.0.2 doesn't exist (and it doesn't by default on my Fedora workstation), then the tests would be expected to fail. Is there a prerequirement step to set up a 127.0.0.2 interface that needs to be performed for the tests to succeed?

**Comment by mpdehaan** [comment]
Its a loopback, should be fine out of the box.  001 used to be implied local connection type though this is not true anymore

**Comment by willthames** [comment]
Yes, you're quite right - in the end this was because sshd wasn't running on the local machine. Once I'd started sshd and run ssh-copy-id, the tests succeeded.
