### ISSUE TITLE
S3: get/put fail when multi-part file already on S3

### ISSUE THREAD

**Issue by lorrin** [ansible/ansible#5442]
The s3 module has a `keysum` method that fails when the file on S3 got there via multipart upload:

```
etag_multipart = md5_remote.find('-')!=-1 #Check for multipart, etag is not md5
if etag_multipart is True:
    module.fail_json(msg="Files uploaded with multipart of s3 are not supported with checksum, unable to compute checksum.")
```

It is used by `get` and `put` in overwrite scenarios to determine whether the source and destination are identical. The resulting behavior is that the module fails prematurely, regardless of whether `overwrite=True` was passed.

**Comment by mpdehaan** [comment]
Can you please share the output of "ansible --version" and also share some examples that show with what you are doing in the playbook in addition to just showing the internal code snippets?

Thanks!

**Comment by lorrin** [comment]
I'm running ansible 1.4.1, but the bug appears to still be present in master.

The relevant part of the playbook is:

```
- name: Fetch Spark
  s3: bucket=my-bucket object=/spark-0.8.1-incubating-bin-hadoop1.tgz dest=/tmp/spark-0.8.1-incubating-bin-hadoop1.tgz mode=get aws_access_key={{aws_access_key_id}} aws_secret_key={{aws_secret_access_key}}
```

As a successful work-around, I re-uploaded the file to S3 as a single-part upload, which made the eTag be an md5.

**Comment by lorrin** [comment]
@mpdehaan, let me know if there is more info you need. Cheers.

**Comment by jimi-c** [comment]
See my recent comment on the mailing list in regards to multipart handling with the s3 module. Unfortunately, there's no simple solution so for the time being the solution is as you've done above. If you have any questions about this, please let us know. Thanks!

**Comment by hiwaylon** [comment]
@lorrin How were you able to re-upload the file as a single-part upload? I cannot find any details at all on how to prevent multipart uploading.

**Comment by lorrin** [comment]
@hiwaylon, IIRC I used s3cmd rather than the standard AWS CLI to do the upload.

**Comment by willybarro** [comment]
If anyone else is having problem with that and don't really care of downloading the file again, a possible workaround is to remove the object from the target before trying to redownload from S3. Something like this:

```
- name: Remove artifact if it exists locally.
  file: path=/tmp/file.deb state=absent

- name: Download artifact from S3
  s3: aws_access_key={{ s3_access_key }}
      aws_secret_key={{ s3_secret_key }}
      bucket={{ s3_bucket }}
      object=file.deb
      dest=/tmp/file.deb mode=get
```

**Comment by crafty78** [comment]
The current behaviour is that it fails if the file was upload as multi-part, propose a new attribute to the module called syncstrategy with following values:

* md5 (default) - same behaviour as now
* sizeandtime - use timestamp and filesize to see if files needs to be downloaded/uploaded (this is similar to native s3 sync command)
* sizeonly - use file size only to compare to see if files needs to be downloaded/uploaded (there is a similar option native s3 sync command)

**Comment by fuzzyami** [comment]
This workaround worked for me, but I had to add a short pause between the deletion and and the downloading.

**Comment by lindes** [comment]
It would be nice if there were some way to have this work... even if it didn't check the checksum, and/or checked a user-supplied checksum (see https://github.com/ansible/ansible-modules-core/issues/2404 )...

**Comment by iainelder** [comment]
I don't understand why this is closed without a fix.

The native `aws s3 cp` handles multipart objects just fine.

Can Ansible not just use that?

**Comment by jimi-c** [comment]
See my post here (https://groups.google.com/d/msg/ansible-project/Dg7aAmpoS2A/iWkJ6Yp2L3YJ) for the reasons why I closed this. We use boto internally, and have no plans on changing that.

**Comment by iainelder** [comment]
In the meantime, you can use this shell task as a workaround.

```
  - name: Get big object from S3
    shell: 'aws s3 cp "s3://your-bucket/big-object.tgz" /tmp/big-object.tgz'
```

**Comment by hyperized** [comment]
For future reference, if you are uploading large objects (like tarred / zipped files) and you are looking to replace objects, you can still use the s3 module by simply deleting the existing object (if you are not actively serving traffic towards the object). This might not be ideal for all use cases, but it still keeps things away from the shell module.

```
- s3: 
    bucket: "{{ s3_bucket }}"
    object: "{{ dump_file }}"
    mode: delobj
    aws_access_key: "{{ s3_access_key }}"
    aws_secret_key: "{{ s3_access_secret }}"

- s3:
    bucket: "{{ s3_bucket }}"
    object: "{{ dump_file }}"
    mode: put
    aws_access_key: "{{ s3_access_key }}"
    aws_secret_key: "{{ s3_access_secret }}"
```

**Comment by tyleha** [comment]
This issue has cropped up for me today as of upgrading to ansible 2.3.0.0. On a separate machine running 2.2.1.0 I have no problem. What's changed between those releases? This is a 2 year old bug - can't imagine somehow it just got rolled into a release.

**Comment by wvidana** [comment]
This issue still happened to us with 2.2.1, the workaround was to use shell module with aws cli instead of s3 module.

**Comment by jwitko** [comment]
Also having this issue on 2.3.0.0, Error comes up no matter what "overwrite:" is set to.  Can't even download the file into an empty directory with the current state of the module.  Does anyone have a work-around for 2.3.0.0 that doesn't involve going to the CLI?  The above ansible work-arounds don't seem to work on 2.3.0.0.

**Comment by erickpatrick** [comment]
It also happens to my team. We are trying to provision an AWS EC2 instance, every other task works but this one.

Runner machine (Local VM):
```shell
$ ansible --version
ansible 2.3.0.0
  config file = /home/ubuntu/mr-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```
```shell
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```
Target Machine (AWS EC2 Instance):
```shell
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

$ python --version
Python 2.7.12
```
Code snippet used:
```yml
- name: download media snapshot
  s3:
    bucket: "{{ media_s3.bucket_name }}"
    object: "{{ media_s3.file_name }}"
    region: "{{ media_s3.region }}"
    dest: "/tmp/ansible-s3-snapshot/{{ media_s3.file_name }}"
    mode: get
    aws_access_key: "{{ media_s3.access_key }}"
    aws_secret_key: "{{ media_s3.secret_key }}"
```

**Comment by psalaberria002** [comment]
Same issue here with 2.3.0.0.

**Comment by Craig1f** [comment]
This is happening to me. Also, I'm pretty sure that my file isn't a multi-part upload. Commenting out the "overwrite" property has no effect. Going to have to use a shell command instead.

**Comment by Craig1f** [comment]
@iainelde, I just tried your approach. The file downloads fine, but Ansible treats the download message as an error, and the playbook stops. Did you get it working?

**Comment by erickpatrick** [comment]
My team and I decided that was better to install the aws-cli and use it directly (through some ansible-shell tasks) instead of relying on ansible-s3 module. In the end we got better speed and no problems at all.

**Comment by Craig1f** [comment]
@erickpatrick I just did the same thing and it's working great!

**Comment by ramgrandhi** [comment]
This trick worked for me:

1. First, deleted what I uploaded to S3.

2. aws configure set default.s3.multipart_threshold 1024MB

3. aws s3 cp your-local-file "s3://bucket-name/object-name"

Since then, all future ansible module (s3) 'get' calls have resulted success. HTH.
