### ISSUE TITLE
authorized_key key path broken?

### ISSUE THREAD

**Issue by t2d** [ansible/ansible#5444]
Today, we updated from ansible 1.3 to 1.4.3

This part of the play worked until now

```
- name: ensure key files for ssh are present
    action: authorized_key
                  user={{ item }}
                  key='files/{{ item }}.pub'
    with_items:
       - user1
       - user2
```

but now, we get those errors 

```
TASK: [common | ensure key files for ssh are present] ************************* 
failed: [example.org] => (item=user1) => {"failed": true, "item": "user1"}
msg: invalid key specified: files/user1.pub
failed: [example.org] => (item=user2) => {"failed": true, "item": "user2"}
msg: invalid key specified: files/user2.pub
```

The files are still in the same place. Does this happen on purpose and what is the right way to do this now?

**Comment by mpdehaan** [comment]
The bug tracker is for reporting bugs, it sounds like this is still in the "I have a question" phase, can you please ask on ansible-project (the mailing list)?

Thanks!
