### ISSUE TITLE
feature request: include should behave like include_vars

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#5447]
## Summary

in a role i would like to include task based on os family, like

```
- include: "{{ ansible_os_family }}.yml"
```

or even a more fancy hierarchical conditional include

```
- include_vars: "{{ item }}"
  first_available_file:
  - "{{ ansible_os_family }}.yml"
  - unsupported_os_family.yml
```
## Problem

This fails:

```
ERROR: file not found: /path/role/tasks/{{ansible_os_family}}.yml
```

But using `include_vars` in tasks identically, doesn't fail.

```
- include_vars: "{{ ansible_os_family }}.yml"
```
## Expected

`include` should behave like `include_vars`
## Workaround

for the moment I use

```
- include: Debian.yml
  when: ansible_os_family == 'Debian'
  tags: package

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags: package
```

**Comment by mpdehaan** [comment]
This can not happen, task objects (though not their values hence they can be parameterized) must be applied evenly to all hosts.   When does this too, it just applies a parameterized conditional to each task.

If you would like to discuss, it won't change anything, but you may do so on the development list.
