### ISSUE TITLE
galaxy: can not find any way to update my roles (anymore)

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#5448]
I just see how I can delete my role, but not update. No infos found anyware, I remember there was an "update my role" button. Can not find it anymore.

**Comment by resmo** [comment]
just added a new role and there is a "re-import" action. but for my resmo.zabbix-agent the state is "no import task found"

**Comment by resmo** [comment]
I deleted the resmo.zabbix-agent and wanted to re-add it by creating it again. But now I got an error: 
"You have already created a role with that name." 

Help please :)

**Comment by mpdehaan** [comment]
We're already aware of this one and will be implementing a fix in a future release.

cc @jimi-c

**Comment by mpdehaan** [comment]
(closing as this isn't the issue tracker for galaxy, in fact, there isn't one as we are just using the mailing list...)
