### ISSUE TITLE
galaxy: --roles-path missed in help

### ISSUE THREAD

**Issue by evgkrsk** [ansible/ansible#5450]
# 

evg@thinkpad ~/.ansible $ansible-galaxy --help  
Usage: ansible-galaxy [init|info|install|list|remove] [options] ...

Options:
#   -h, --help  show this help message and exit

evg@thinkpad ~/.ansible $ansible-galaxy install bennojoy.ntp  
 no version specified, installing master
- downloading role from https://github.com/bennojoy/ntp/archive/master.tar.gz
- extracting bennojoy.ntp to /etc/ansible/roles/bennojoy.ntp
  Error: you do not have permission to modify files in /etc/ansible/roles/bennojoy.ntp
  bennojoy.ntp was NOT installed successfully.
  You can use --ignore-errors to skip failed roles.
  ========================================================
  evg@thinkpad ~/.ansible $ansible-galaxy install bennojoy.ntp  --roles-path /home/evg/.ansible/roles
  no version specified, installing master
- downloading role from https://github.com/bennojoy/ntp/archive/master.tar.gz
- extracting bennojoy.ntp to /home/evg/.ansible/roles/bennojoy.ntp
  bennojoy.ntp was installed successfully
  ========================================================

Please, add --roles-path (and other hidden options) to ansible-galaxy --help. It would be very nice to add man page for ansible-galaxy, too.

**Comment by mpdehaan** [comment]
Options are automatically generated by the option parser when you use a subcommand.

ansible-galaxy install --help

**Comment by evgkrsk** [comment]
It is not obvious and not documented anywhere (AFAIK).

**Comment by mpdehaan** [comment]
Well, it's documented in the usage string per Unix conventions:

Usage: ansible-galaxy [init|info|install|list|remove] [options] ...

It would not make sense to add it globally as it depends on the subcommand whether it's relevant.

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/pull/5376 hopefully makes this a little clearer
