### ISSUE TITLE
Galaxy account username limit is 6 chars

### ISSUE THREAD

**Issue by groks** [ansible/ansible#5455]
Just tried to log in to Galaxy with my github account, which has a 5 character username, but the Galaxy website is complaining that it wants at least 6. Could you relax the requirement to 5 characters?

**Comment by mpdehaan** [comment]
Yes, we're aware.  We have an internal ticket to reduce this.

I'm going to close this as this isn't the Galaxy issue tracker (we're keeping this elsewhere), but rest assured this is on our list of things to improve from the beta.

Thanks!
