### ISSUE TITLE
Error while adding variables and comparing them with another variable in 'when'

### ISSUE THREAD

**Issue by hitechshiva** [ansible/ansible#5456]
hi all,
I'm trying run the below playbook and facing an exception

ansbile version : 1.4.3
os : debian wheezy
# playbook:

---
- hosts: db
  gather_facts: false
  tasks:
  - name: get free mem  
     shell: free | grep Mem | awk '{print $4}'
     register: free_mem
  - name: get buffer 
     shell: free | grep Mem| awk '{print $6}'
     register: buffer 
  - name: get cache
     shell: free | grep Mem | awk '{print $7}'
     register: cache
  - name: get swap used 
     shell: free | grep Swap| awk '{print $3}'
     register: swap_used
  - name: swap on swap off 
     shell: echo "yeah we can sawpoff and on"
     when: free_mem + buffer + cache > swap_used 
# 
# Exception:

TASK: [swap on swap off] *****************************************************\* 
fatal: [db1] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/**init**.py", line 394, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 485, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 572, in _executor_internal_inner
    if not utils.check_conditional(cond, self.basedir, inject, fail_on_undefined=self.error_on_undefined_vars):
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/__init__.py", line 186, in check_conditional
    conditional = template.template(basedir, presented, inject)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/template.py", line 319, in template
    varname = template_from_string(basedir, varname, vars, fail_on_undefined)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/template.py", line 543, in template_from_string
    return res
UnboundLocalError: local variable 'res' referenced before assignment

FATAL: all hosts have already failed -- aborting

Please let me know if you need further details.

Regards
Shiva

**Comment by hitechshiva** [comment]
Hi,
Created a generic playbook to reproduce the error

# Playbook:

---
- hosts: local
  gather_facts: false
  vars:
   a: '0'
   b: '0'
   c: '0'
  tasks:
  - name: echo 1
    command: echo 1
    register: a
  - name: echo 2
    command: echo 2
    register: b
  - name: echo 5
    command: echo 5
    register: c
  - name: echo on add
    command: echo "helo my summ darling"
    when: a  + b >= c

Please let me know if you need further details.

Regards
Shiva

**Comment by mpdehaan** [comment]
Thanks -- in queue for testing!

Future FYI if you indent your content four spaces it will render correctly in GitHub.

**Comment by mpdehaan** [comment]
(note: this prob. shouldn't work but it shouldn't throw a traceback either)

**Comment by jimi-c** [comment]
This appears to have been fixed already. When the sample playbook given above is run, the result is:

<pre>
TASK: [echo on add] *********************************************************** 
fatal: [127.0.0.1] => an unexpected type error occured. Error was unsupported operand type(s) for +: 'dict' and 'dict'
</pre>

When the following syntax is used:

<pre>
  - name: echo on add
    command: echo "helo my summ darling"
    when: a.stdout|int + b.stdout|int >= c.stdout|int
</pre>

the logic works as intended:

<pre>
TASK: [debug msg="{{a.stdout|int + b.stdout|int}} and {{c.stdout|int}}"] ********** 
ok: [127.0.0.1] => {
    "msg": "3 and 5"
}
</pre>

If you have any further problems regarding this issue, please let us know. Thanks!

**Comment by hitechshiva** [comment]
perfect, thanks :)
