### ISSUE TITLE
Galaxy category for personal laptop customisation

### ISSUE THREAD

**Issue by groks** [ansible/ansible#5458]
The list of categories in the meta/main.yml file after an 'ansible-galaxy init' is server focussed. How about adding something like laptop, desktop, or personalisation? Here are a couple of examples of the kinds of roles I would put under this category:
- extra repos containing end-user software
- packages to enable mp3 and other multimedia
- services to disable and other tweaks to enable fast cold boot
- firewall rules to enable music and file sharing
- power saving tweaks

etc.

**Comment by mpdehaan** [comment]
Thanks!  Can you please share galaxy-suggestions on the ansible-project mailing list where more people can talk about them?  This could be an interesting discussion and I'd like a wider audience.

I'd probably say these all fit into "system" squarely right now but am open to other views.
