### ISSUE TITLE
vars_prompt without default set does not result in error

### ISSUE THREAD

**Issue by beefsalad** [ansible/ansible#5460]
Here is an example, and I think you'll see why we should have an option to fail (or reprompt) when vars_prompt is empty...
- hosts: myhost
  user: me
  gather_facts: False
  
  vars:
    server1vars: foo_something, bar_something
  vars_prompt:
  - name: "district"
    prompt: "which district?"
    private: no
    confirm: no
  
  tasks:
  - shell: ./some command | grep {{ district }}_
    changed_when: False
    register: db_names
  - fail: msg="bailing out, we didn't find the {{ district }} district!"
    when: "server1vars |intersect(db_names) is not defined"

$ ansible-playbook informix.yml -i ../../inventory -u me
For which district is this account?: 

PLAY [myhost] **************************************************\* 

TASK: [shell ./some command | grep _ | cut -f 3- -d " "] **\* 
ok: [myhost]

TASK: [fail msg="bailing out, we didn't find the  district!"] ****************\* 
skipping: [myhost]

PLAY RECAP *******************************************************************\* 
myhost       : ok=1    changed=0    unreachable=0    failed=0   

Please add an optional to 'vars_prompt' to require the prompt to not be null (required: true/false?)

I would submit a PR, but without digging through all of the code I can't be sure this will not effect anything else.  I will work on a full review of the code for a while to see if I think I can easily add it, but a dev familiar with Ansible internals would be able to do this much easier than myself.

**Comment by mpdehaan** [comment]
You can do this with the "fail" module if you want.
- fail: msg="AIEEE"
  when: foo is not defined

We're unlikely to actively work on this one given the above, but I can imagine an option for "required: True/False" would be fine if someone wants to send in a request.
