### ISSUE TITLE
become: yes ignored if LOGNAME set

### ISSUE THREAD

**Issue by Sec42** [ansible/ansible#54724]
##### SUMMARY

If the environment variable "LOGNAME" is set to "root", become: yes is silently ignored

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible 2.6.4
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

run below playbook as

```
env LOGNAME=root ansible-playbook becometest.yml
```

```yaml
- hosts: 127.0.0.1
  become: yes
  tasks:
  - name:  Get uid
    shell: id
    register: id

  - debug: var=id.stdout
```

##### EXPECTED RESULTS

Ansible to run commands as root.

```
TASK [debug] ******************************************************************************************************************************************************************************
ok: [127.0.0.1] => {
    "id.stdout": "uid=0(root) gid=0(root) groups=0(root)"
}
```

##### ACTUAL RESULTS

ansible silently ignoring become and running commands as invoking user:

```paste below
 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [127.0.0.1] **************************************************************************************************************************************************************************

TASK [Get uid] ****************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [debug] ******************************************************************************************************************************************************************************
ok: [127.0.0.1] => {
    "id.stdout": "uid=1000(sec) gid=1000(sec) groups=1000(sec),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),115(lpadmin),131(sambashare),132(wireshark),999(docker)"
}

PLAY RECAP ********************************************************************************************************************************************************************************
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0   
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The `become` setting is not being ignored, but Ansible by default does not use privilege escalation when the login user is the same as the target user, to change this behaviour see 
https://docs.ansible.com/ansible/latest/reference_appendices/config.html?#become-allow-same-user
Setting `LOGNAME` is fooling Ansible as to which user it is logged in as, so I really don't recommend you do this.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by Sec42** [comment]
I understand your viewpoint, but LOGNAME is not a statement as to which user you are. It is just an environment variable.

One example case to reproduce:

1. log in as user
2. run `sudo -s`
3. run `sudo -H -u nonroot ansible-playbook ...`

LOGNAME will still be `root`although ansible is running as `nonroot`.

I maintain ansible should check for the actual uid instead of blindly trusting env variables.

**Comment by bcoca** [comment]
`LOGNAME` is normally set to 'user that logged in', which Ansible compares against the 'user you want to become', since you are setting `LOGNAME` to root and you by default 'become root' Ansible is matching those and skipping the become step (unless you toggle the option i linked above).

This is not about the value of `LOGNAME` after privilege escalation, its about it BEFORE we attempt it.

**Comment by Sec42** [comment]
I feeling you are not getting my point, let me make a last attempt at explaining myself.

`LOGNAME`is an environment variable. It is a convention that it is set to the current username, but it is not necessarily true.

I provided a real-world example where `LOGNAME` is set incorrectly in my previous comment.

As to your second/third paragraph: I never talked about `LOGNAME` after ansible is running. The actions outlined above are actions done by the user before running ansible.

I agree my example may be not the most common use-case, but a fairly straightforward way to run commands as a fixed central user. In this case it is an ansible job that is usually run from a cronjob, but sometimes people need to manually trigger it, and thus use sudo to run ansible as the correct user.

Regardless of how common or not this is, there are several ways to get the current user that are authoritative and always correct. See e.g. http://man7.org/linux/man-pages/man2/getuid.2.html or https://linux.die.net/man/1/id - `LOGNAME` simply is not one of them.

I don't understand why ansible is using a flawed and clearly inferior way to detect the current user, and why you insist that it is correct and even state that this is a misunderstanding.

**Comment by bcoca** [comment]
the misunderstanding is that 'become is ignored', I explained that we do when processing become. 

Ansible itself does NOT query `LOGNAME` directly, but it does use Python APIs that include it in their resolution of 'what is my current user'. 

This mainly affects 'local connections' since the `local` connection plugin uses `getpass.getuser()` to get the 'current user' and is fooled by the use of `LOGNAME`. Other connection plugins don't have this issue.

In any case this looks like a self inflicted issue and not really a bug, you clearly disagree and are welcome to bring it up in the public IRC meetings to make your case.  https://github.com/ansible/community/issues?q=is%3Aopen+is%3Aissue+label%3Acore+label%3Ameeting_agenda

**Comment by Sec42** [comment]
Your statement about this being a python bug intrigued me.

It is indeed true that ansible is using
`self._play_context.remote_user = getpass.getuser()`
in `./plugins/connection/local.py`

`getpass.getuser()` is indeed being stupid and looking at environment variables before trusting the system. Probably in a misguided attempt to avoid importing the `pwd` module.

I am however surprised to see ansible use a module intended for password input _solely_ for the reason to get the current user name.

What's interesting is, that in other places, ansible DOES the correct thing:

e.g. in `plugins/action/__init__.py`:

```
        if new_info.connection == 'local':
            if not new_info.connection_user:
                new_info.connection_user = new_info.remote_user
            new_info.remote_user = pwd.getpwuid(os.getuid()).pw_name
```

If there is precedent within ansible to do it properly, I would suggest to just fix it with a patch like this:

```
--- ansible/plugins/connection/local.py.orig    2019-04-04 17:05:57.344945502 +0200
+++ ansible/plugins/connection/local.py 2019-04-04 17:06:03.196945502 +0200
@@ -33,7 +33,7 @@
 import shutil
 import subprocess
 import fcntl
-import getpass
+import pwd
 
 import ansible.constants as C
 from ansible.compat import selectors
@@ -62,7 +62,7 @@
         # Because we haven't made any remote connection we're running as
         # the local user, rather than as whatever is configured in
         # remote_user.
-        self._play_context.remote_user = getpass.getuser()
+        self._play_context.remote_user = pwd.getpwuid(os.getuid()).pw_name
 
         if not self._connected:
             display.vvv(u"ESTABLISH LOCAL CONNECTION FOR USER: {0}".format(self._play_context.remote_user), host=self._play_context.remote_addr)

```
