### ISSUE TITLE
Please bring back the "single page" module index

### ISSUE THREAD

**Issue by pdevine** [ansible/ansible#5475]
The new docs look very spiffy, however, it was really, really handy to have a single page view with the module index.  With the new docs, it means a lot more hunting to find out which module has which command.

Would it be possible to have both views?  That way you get the organizational benefits from various categories, but get the convenience of being able to easily search for a particular command.

**Comment by mpdehaan** [comment]
Just added "All Modules" here - http://docs.ansible.com/modules_by_category.html
