### ISSUE TITLE
Docs for "cron" module say "name" is not required

### ISSUE THREAD

**Issue by ajchace** [ansible/ansible#5479]
The documentation for the "cron" module says that the "name" parameter is not required. Attempting to execute a playbook that calls the "cron" module without the "name" parameter produces the following error message:

failed: [fcadmin01.fullcount.net] => {"failed": true}
msg: You must specify 'name' to install a new cron job

ansible-playbook --version
ansible-playbook 1.4.3

**Comment by mpdehaan** [comment]
It's true, name isn't required for all options, which is what "required" means here.

Look at the example section of the module docs to see what I mean.

Thanks!
