### ISSUE TITLE
no way to change permissions on link destination (not the link itself)

### ISSUE THREAD

**Issue by rtirrell** [ansible/ansible#548]
It's not possible to use the file module to change the permissions of a symbolic link (really, the file pointed to by a symbolic link). The link is created outside of the scope of ansible, so I don't know where it actually leads. 

Is there a good way to remedy this, e.g., if only the dest is given, and it already exists, assume we are only modifying permissions?

**Comment by rtirrell** [comment]
Specifically, the file module complains that both src and dest are required.

**Comment by mpdehaan** [comment]
Yes.

The file module doesn't normally require a src and dest, it's just the link code, which is a bit more recent than the rest of the module.  Good catch.   How about a patch to do what you suggested?

**Comment by rtirrell** [comment]
Also, is there a reason the recurse parameter isn't respected - i.e., that it's not as simple as it would appear to be. If that's the case, what's the complication?

**Comment by mpdehaan** [comment]
(edited answer to this, upon review)

Looks like it just wasn't finished, would accept patches to reinstate it.  Should probably default to yes.

**Comment by rtirrell** [comment]
I had just gotten around to guessing that idempotency was probably the hangup.

**Comment by mpdehaan** [comment]
yeah, just edited previous answer... it looks like it is always doing -R, which I guess is ok, because most of the time it won't be run on directories.

(We are not a super hardcore stickler for idempotency in this case, because it's not like it is doing anything destructive by running it twice.)

**Comment by mpdehaan** [comment]
Oh, you want to change the permission of the _destination_ file by following the link.   That's different than what I was thinking.

I am not sure how you'd specify that with the file module, because what that's all about is the permissions on the link itself.

In this case, I think you most likely just want to use the shell module with some voodoo to see where the link points.

I am not sure how you would specify that the permissions you want to adjust are all about the thing the link points at.

Though if we get past syntax, there is definitely a technical way.

Thoughts on what this might look like?

file owner=root src=wherever state=link adjust=destination

where the default is 'source'?

That feels a bit weird to me.

**Comment by rtirrell** [comment]
The documented behavior of chmod is to dereference the link and change the permissions on the file pointed to. For this specific case, it seems appropriate to me to use state=link and specify a path. 

OK, I don't really know how to manage two pull requests at once and I kind of mixed them up with one another. This commit is the one to look at: https://github.com/rtirrell/ansible/commit/a93a36fb9894d33f418c7298d30a10568cf510f0

**Comment by rtirrell** [comment]
Actually, what I said about the documented behavior may have been a lie. Let me dig in...

**Comment by mpdehaan** [comment]
ok, so it seems that, already, chmod is doing the right thing (good!) and we just need to make it be tolerant of not having both parameters.

Looks good from first inspection, if you send me a pull request for it I can do some testing locally.

Thanks!

**Comment by mpdehaan** [comment]
you seem to be talking about -H (or maybe -h!)

might need to add a parameter follow=yes/no for that that would only be valid with state=link  and then would only affect the chown and chmod arguments?   Just a thought.  Not positive.

**Comment by rtirrell** [comment]
So the mode of a symbolic link is strictly theoretical. follow/dereference (I think deference a better name because follow could sort of be confused with directory traversal) would not apply there (right?).

Changing user and group is a bit more complicated for two reasons: 
1) With files, you can modify either referer (-h) or referent (--dereference, the default). I don't have a strong understanding of when one versus the other is appropriate.
2) When using -R, you also have -H (traverse symbolic links to directories explicitly given on command line), -L (traverse all) or -P (traverse nothing) to consider. I don't know what the right behavior is here. Maybe it's best to ignore this case, and the only new parameter added to the module is follow/dereference for handling files.

**Comment by rtirrell** [comment]
(dereference is itself not completely clear, but it more closely matches the language in the docs)

**Comment by rtirrell** [comment]
Another option would be to always affect the referent, which (as I've implemented it) just piggybacks on the logic used for changing files. This is simpler, because you don't have to dispatch between os.stat and os.lstat.

**Comment by rtirrell** [comment]
And I imagine modifying the referent satisfies most use cases.

**Comment by mpdehaan** [comment]
This seems like other folks may have opinions, how about bringing it up on the mailing list?

**Comment by rtirrell** [comment]
Will do.
