### ISSUE TITLE
feature request: ansible-pull define a second URL playbook repository

### ISSUE THREAD

**Issue by nicolas-g** [ansible/ansible#5483]
Will be nice if we could define one more repository URL so in case the first Git server is down ansible-pull will still be able to checkout the code from a "slave" or "standby" Git server that will have the same code in sync..

This is suitable in for a Git High Availability environment .

At the moment we deinfe the Git repository using the -U URL/--url=URL arguments, for a second Git repo I would suggest something like -U2 URL2/--url2=URL2 .

Regards,
Nicolas.

**Comment by mpdehaan** [comment]
I don't think we'd want to add a seperate option, some sort of seperator in the URL (probably a space) could be used for a split operation.

This is not likely something we'll add, but pull requests would be considered.

Thanks!
