### ISSUE TITLE
RPM build fails at devel due to missing doc (edit: change makefile targets, etc)

### ISSUE THREAD

**Issue by gkristic** [ansible/ansible#5484]
When trying to `make rpm` out of the devel branch, this is what I get (initial output omitted for brevity):

```
+ cp -v 'docs/man/man3/*.3' /home/gkristic/projects/ansible/rpm-build/BUILDROOT/ansible-1.5-0.git201401030424.x86_64//usr/share/man/man3/
cp: cannot stat 'docs/man/man3/*.3': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.RlHSWt (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.RlHSWt (%install)
make: *** [rpm] Error 1
```

There's effectively no man page under man3, so the copy fails. Digging a bit into this, I found that there's no longer a docs target at the Makefile, such as the one leading to the `modulepages` target that run `module_formatter.py` at v1.4.3. Running the later by hand yields the following output at devel:

```
gkristic@hubble:~/projects/ansible> PYTHONPATH=./lib python hacking/module_formatter.py -A 1.5.0 -t man -o docs/man/man3/ --module-dir=library --template-dir=hacking/templates # --verbose
Traceback (most recent call last):
  File "hacking/module_formatter.py", line 323, in <module>
    main()
  File "hacking/module_formatter.py", line 301, in main
    env, template, outputname = jinja2_environment(options.template_dir, options.type)
  File "hacking/module_formatter.py", line 175, in jinja2_environment
    raise Exception("unknown module format type: %s" % typ)
Exception: unknown module format type: man
```

Commenting out the [copy](https://github.com/ansible/ansible/blob/devel/packaging/rpm/ansible.spec#L84) and the [%doc](https://github.com/ansible/ansible/blob/devel/packaging/rpm/ansible.spec#L101) for man3 works, but I wonder what happened with module pages anyway. Note also that there's still a comment at the Makefile stating `docs` as a target.

**Comment by mpdehaan** [comment]
make docs will take care of this for now, so I need to add the makefile dep and also remove the modulepages target

We don't include manpages for each module anymore, since we have ansible-doc modulename for people to run.

**Comment by gkristic** [comment]
Okay. If that's the case then removing the lines I pointed out from the Makefile seems to be the way to go.

Thanks for checking @mpdehaan!

**Comment by rgarrigue** [comment]
Just a though here, make docs will require asciidocs as a buildrequires, and build-rpm too if you use make rpm (both are not needed for pure python %build)

**Comment by mpdehaan** [comment]
True.

**Comment by jctanner** [comment]
@gkristic I'm unable to reproduce this. Perhaps this is no longer an issue for you, but if it is can you shed more light on how to create the error? Starting with a clean EL6 machine, what steps do I take to see the copy/man3 error?

**Comment by gkristic** [comment]
@jctanner The error showed up simply by cloning the Git repo and running `make rpm`. Here's the tip of develop when I opened this issue: 89abc35e59b7595ad29a5a2e2d65620795c908e2. But I've just fetched the latest version and it's gone; the RPM is now generated. Thanks!
