### ISSUE TITLE
What is the difference between runing playbook on ansible host and from Jenkins

### ISSUE THREAD

**Issue by jinnabaalu** [ansible/ansible#54867]
##### SUMMARY

Failed to connect to the host via ssh: Host key verification failed

I have set of EC2 instance, i want to do application automation through jenkins UI using ansible plugin.
##### ISSUE TYPE
- Bug Report
I am able to run the playbooks from the ansible host, but not from the jenkins UI using ansible plugin.
##### COMPONENT NAME

jenkins ansible plugin, ec2 instance with pem file

##### ANSIBLE VERSION

```paste below
ansible 2.7.9
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 18.04

##### STEPS TO REPRODUCE

```bash
ansible  -m shell -a "free -m" --private-key=/etc/ansible/pem/WSStaging.pem -u ubuntu staging-app
```

##### EXPECTED RESULTS

Both ansible host terminal and jenkins Ui need to work the same

##### ACTUAL RESULTS

I am able to ping or execute any command in ansible server 
![image](https://user-images.githubusercontent.com/11784253/55564396-6ad84980-5715-11e9-9716-8b1b2e79a87c.png)

But when I run the same command from the Jenkins using Ansible plugin i am unable to execute it successfully.
Always the same error 
**Failed to connect to the host via ssh: Host key verification failed.**

![image](https://user-images.githubusercontent.com/11784253/55565103-d2db5f80-5716-11e9-8ecf-45653c326979.png)

Thanks in advance.

```paste below

```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by JinnaBalu** [comment]
Thanks @bcoca I am posting in google groups. closing thisa ticket now
