### ISSUE TITLE
Query for installed homebrew packages fail for some libraries

### ISSUE THREAD

**Issue by daghoidahl** [ansible/ansible#5488]
Some libraries, e.g. libjpeg and libgeoip, are not reported with their package names by `brew list`  (for these libraries "lib" is not included). This makes  the `query_package` function fail.

**Comment by mpdehaan** [comment]
Is this something that needs to be fixed in homebrew?  (Or how would you solve it via the CLI?)

**Comment by mpdehaan** [comment]
Saw your comment on the other pull request, I'm going to close this one as the pull request can track the issue.

Thanks for this!
