### ISSUE TITLE
The output of win_command / win_shell become corrupted with some commands in Japanese.

### ISSUE THREAD

**Issue by h-hirokawa** [ansible/ansible#54896]
##### SUMMARY
Some windows commands do not support Unicode yet, and when the system default display language is Japanese, the output encoding become [cp932](https://en.wikipedia.org/wiki/Code_page_932_(Microsoft_Windows)).
However, Ansible treats stdout/stderr as UTF8 and replace invalid chars to `�`, so the cp932 output become corrupt[ed.

Since it is difficult to automatically determine the correct encoding, it seems better to add optional params to win_command/win_shell modules for specifying encoding .

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible 2.7.9
  config file = /Users/hirokawahidetoshi/.ansible.cfg
  configured module search path = ['/Users/hirokawahidetoshi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.9/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]
```

##### CONFIGURATION

```paste below
DEFAULT_ROLES_PATH(/Users/hirokawahidetoshi/.ansible.cfg) = ['/Users/hirokawahidetoshi/.ansible/roles']
HOST_KEY_CHECKING(/Users/hirokawahidetoshi/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Windows 10

##### STEPS TO REPRODUCE

1. Prepare ansible-ready Windows machine and set default display language to Japanese.

2. Run the following ansible command.
```
$ ansible jp.windows.host -m win_command -a ipconfig
```

##### EXPECTED RESULTS

```
jp.windows.host | CHANGED | rc=0 >>

Windows IP Configuration


Ethernet adapter イーサネット:
…
```

##### ACTUAL RESULTS

```
jp.windows.host | CHANGED | rc=0 >>

Windows IP Configuration


Ethernet adapter �C�[�T�l�b�g:
…
```

**Comment by h-hirokawa** [comment]
Now I'm working on it.
https://github.com/h-hirokawa/ansible/tree/fix-54896

**Comment by ShachafGoldstein** [comment]
@h-hirokawa - Still working on this?

**Comment by h-hirokawa** [comment]
@ShachafGoldstein
I pushed the branch rebased with the latest devel to #54966.
Would you review it?
