### ISSUE TITLE
group_by does not source group_vars when hosts are added

### ISSUE THREAD

**Issue by mcodd** [ansible/ansible#5499]
Per discussion at https://groups.google.com/forum/#!topic/ansible-project/A79N7LRm-9I, when I add systems to a group using group_by, they don't get variables for that group which are defined in group_vars.

I've given an example that shows the issue in current devel (c41a23a35a) in a gist at https://gist.github.com/mcodd/8250193.  When running the test.yml playbook, I'd expect the variable groupvar to resolve to "this_group_var", but it instead remains undefined.

**Comment by mpdehaan** [comment]
This is _possibly_ related to #5495

**Comment by jctanner** [comment]
@mcodd this seems to work for me with one slight change:

```
- name: group by testvar
  group_by: key=testvar
```

Should be ...

```
- name: group by testvar
  group_by: key="{{ testvar }}"
```

Please modify your testcase and we can reopen the ticket if it still fails, but I'm fairly confident that it won't.

**Comment by mcodd** [comment]
ah, great... i've confirmed this works just fine (both in 1.4.3 and currently), thanks James!

**Comment by JasonGiedymin** [comment]
I'm having a similar issue but my group by is by `{{ansible_distribution}}`, with my vars in `group_vars/all`. I expected that the vars be accessible from any of the roles that get executed. Do I have the wrong expectation? I'm looking for a way to specify distribution paths but not having to duplicate vars for each. I also understand that I could specify another layer of yml with a simple `include` clause but I figured I would eliminate complexity by using `group_vars`. Please advise. Thanks!

**Comment by JasonGiedymin** [comment]
Disregard, I understand now that `group|host_vars` pertains to inventory and thus must be relative. My notion of nested includes would suffice as an instrument to share variables on a playbook level.
