### ISSUE TITLE
Nginx folder deleted after ansible

### ISSUE THREAD

**Issue by yanlinaung30** [ansible/ansible#55016]
##### SUMMARY

I have lost **/etc/nginx** folder after installing the [kubespray](https://github.com/kubernetes-sigs/kubespray) with ansible.
I can find only this log.
```
Apr  8 13:33:25 node1 ansible-file: Invoked with directory_mode=None force=False remote_src=None _original_basename=None path=/etc/nginx owner=None follow=True group=None unsafe_writes=None state=absent content=NOT_LOGGING_PARAMETER serole=None selevel=None setype=None access_time=None access_time_format=%Y%m%d%H%M.%S modification_time=None regexp=None src=None seuser=None recurse=False _diff_peek=None delimiter=None mode=None modification_time_format=%Y%m%d%H%M.%S attributes=None backup=None
```

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 18.04 LTS

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by mkrizek** [comment]
The log you provided contains `state=absent` for `path=/etc/nginx` so `/etc/nginx` being deleted is expected. I am not sure what `installing the kubespray with ansible` means but you should either fix your playbook to not delete the directory if you don't want it to be deleted or consult https://github.com/kubernetes-sigs/kubespray project if the playbook is part of that project. This is not an Ansible issue.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
