### ISSUE TITLE
module.exit_json and unicode

### ISSUE THREAD

**Issue by LeonB** [ansible/ansible#5501]
My custom module returns something like this:

``` python
module.exit_json(changed=False, result={'unicode': 'test'})
```

While running the ansible playbook I get this error:

```
fatal: [polly.vanutsteen.nl] => error while evaluating conditional: not {u'unicode': u'test'}
```

When I let exit_json return `{}` I don't get the error. Also, if I replace then `when:` condition in my playbook with `not {u'unicode': u'test'}` it fails. If I replace the condition with `not {'unicode': 'test'}` it works.

So it looks like something is going wrong with evaluating conditionals and UTF-8.

**Comment by LeonB** [comment]
This is the conditional that gets generated:

``` jinja
{% if not {u'unicode': u'test'} %} True {% else %} False {% endif %}
```

**Comment by mpdehaan** [comment]
So (A) custom module questions should be asked to the ansible-devel mailing
list.

However, "error while evaluating conditional" has nothing to do with your
module per se, but has to do with your conditional.

Please share the playbook line where you are registering the variable and
also show the "when" line you are using, as this is the underlying problem
you need to correct, and we can help with that.

Let's not presume there's anything wrong with conditionals until we see
more detail :)

**Comment by LeonB** [comment]
You're absolutely right. I've made a minimal testcase for this problem: https://github.com/LeonB/ansible_issue_5501_testcase

**Comment by mpdehaan** [comment]
Looks like what you have here is a result that is a hash

when: "not {{mountpoint_noatime_check.result}}"

registered_variable.result.unicode

would contain the boolean the way you have returned it above.

please ask questions to the mailing list, rather than the bug tracker, if you have any follow ups.

Thanks!
