### ISSUE TITLE
geting error while installing package in host lxd container

### ISSUE THREAD

**Issue by amiya-elear** [ansible/ansible#55036]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

errror i am getting

fatal: [ec2_jenkins:jenkinslxd]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /tmp/ansible-tmp-1554810763.41-131120353067104 `\" && echo ansible-tmp-1554810763.41-131120353067104=\"` echo /tmp/ansible-tmp-1554810763.41-131120353067104 `\" ), exited with result 1", "unreachable": true}

i am able to log in to host system ans i created a lxd container also while going inside container it saying that UNREACHABLE! and i am getting this error

inventory file:
ec2_jenkins ansible_ssh_host=xx.xx.xx.xx ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/home/Downloads/main.pem

[server]
ec2_jenkins

[jenkins-containers_docker]

#########################
main.yml 

- name: expose lxd bridge to the network
  hosts: server
  become: true
  roles:
     - lxdsetup

- name: create containers for jenkins installation
  hosts: server
  become: true
  roles:
     - jenkins_containers

- name: install jenkins on containers created above
  hosts: jenkins-containers_docker
  become: true
  gather_facts: False
  roles:
     - jenkins

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
