### ISSUE TITLE
hashi_vault can't be used to retrieve secrets

### ISSUE THREAD

**Issue by groenator** [ansible/ansible#55040]
I created this task to retrieve the secrets from the vault and save them as variables by using the vars module, however, when I run the task ansible is throwing an error.  even if I use the example from the documentation I get the same error about the misspelling. 

task to retrieve secrets

```
- name: configure user
  vars:
    username: "{{ lookup('hashi_vault', 'secret=secret/hello:username') }}"
```
error from ansible:

```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
14:30:32  
14:30:32  The error appears to have been in '/ansible/roles/role-jenkins-master/tasks/main.yml': line 67, column 3, but may
14:30:32  be elsewhere in the file depending on the exact syntax problem.
14:30:32  
14:30:32  The offending line appears to be:
14:30:32  
14:30:32  
14:30:32  - name: configure user
14:30:32    ^ here
```

Does anyone know what could be the reason?

**Comment by Akasurde** [comment]
Hi! @groenator You may want to use `set_fact` to set vars in given tasks like this -

```
---
- set_fact:
    username: "{{ lookup('hashi_vault', 'secret=secret/hello:username') }}"

- debug:
    msg: "{{ username }}"
```

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by groenator** [comment]
> fyi, there is NO `vars:` module, that is a task keyword

that make's sense wh vars didn't work. i will use set_fact instead.
