### ISSUE TITLE
Change shebang to #!/usr/bin/env python

### ISSUE THREAD

**Issue by jkeskikangas** [ansible/ansible#5507]
Would you consider accepting a the change, if I provide a pull request? I'm aware of #892, which seemed to be closed as won't fix.

Using hard coded `#!/usr/bin/python` makes life difficult on development laptops, e.g., when some devs have linux platforms and others OS X with homebrew installed python. Either OS X people have to use separate inventory file with proper `localhost ansible_python_interpreter=...` set or they have to uninstall python via homebrew and use the one provided with OS X.

I guess using `#!/usr/bin/env python` would be more robust on servers too, and would need a lot less `ansible_python_interpreter` definitions in inventory files [1].

Regarding `-tt` command line parameter, it's used only in [9 scripts out of 192](https://gist.github.com/pyykkis/8272767) and 27 scripts already uses `#!/usr/bin/env python`. For the syntax checking, programs like [pylint](http://www.pylint.org/) could be used provide similar functionality.

1: http://stackoverflow.com/questions/2429511/why-do-people-write-usr-bin-env-python-on-the-first-line-of-a-python-script

**Comment by srgvg** [comment]
This has been requested many times now. ansible_python_interpreter is the way to set an alternative interpreter within your inventory

Please see http://docs.ansible.com/faq.html#how-do-i-handle-python-pathing-not-having-a-python-2-x-in-usr-bin-python-on-a-remote-machine

**Comment by jkeskikangas** [comment]
Have you considered maybe people are actually having difficulties with the issue, if this has been requested for many times? As I said, I'm happy to provide the pull request for the change (instead of just asking someone to do it).

I know it can be set in the inventory file. It doesn't work for developer laptops running ansible, e.g., OS X with homebrew'ed python.

Instead of just saying "this is the way", I wonder if you could point me to any earlier discussions, or provide rational for your opinion? Especially, as it seems, there's no established policy in place (please 
see grep from ansible sources: https://gist.github.com/pyykkis/8272767).

**Comment by srgvg** [comment]
Many requests b/c few are aware of the inventory variable, once people learn about this, their problem usually is solved. Also, I'm just a member of the community, I don' t make policies, I'm only explaining you what is now and has always been. Just trying to help.

Also, from your gist, you confuse modules (which are run remotely on the targetted hosts, and where the shebang is handled by ansible_python_interpreter) and other scripts, wich are run from the control hostm and AFAICS do use env in the shebang. People working on development will run the latter, I expect, and remote hosts shoudl have python in a consistent place for each of them?

Frankly, I don't understand the exact issue you have. Could you elaborate how you work, where you run wich scripts, and how this doesn't work?

**Comment by mpdehaan** [comment]
@sergevanginderachter linked the FAQ above how to handle this for modules, and yes, it's already handled with /usr/bin/env for scripts.  

A config management system absolutely should not rely on the user's path to find a python, nor should it assume /usr/bin/python is the right python, for instance on some Arch installs, /usr/bin/python is sometimes Python 3.  It's certaintly less robust to rely on the path and precludes supplying one's own python.

It is very important that we be able to manage multiple pythons at the same time on different systems, and the inventory configuration is working well for everyone.
