### ISSUE TITLE
ansible_userspace_bits fact is incorrect when running 32bit python on 64bit architecture

### ISSUE THREAD

**Issue by KimNorgaard** [ansible/ansible#5510]
### Cause
- The `userspace_bits` fact is generated using `platform.architecture`.
- `platform.architecture` uses `sys.executable` (as the first argument to `platform.architecture`) by default to determine the architecture.
- `sys.executable` is the python interpreter and if this is a 32-bit binary, then `userspace_bits` report 32. Even if the underlying architecture of the OS is 64-bit.
### Example

Ansible says:

```
$ ansible -i ansible-hosts -m setup solarisserver|grep bits
        "ansible_userspace_bits": "32"
```

On the server:

```
$ uname -m -s -r -v -p -i
SunOS 5.10 Generic_147441-27 i86pc i386 i86pc

$ file /usr/bin/python
/usr/bin/python:        ELF 32-bit LSB executable 80386 Version 1 [FPU], dynamically linked, not stripped, no debugging information available

$ isainfo -kv
64-bit amd64 kernel modules
```
### Possible solutions

I have come up with a few solutions, though there are probably more:
1. Supply another executable as the first argument to `platform.architecture`. This will probably not work because it's hard to find a binary that exists on all platforms and that is linked to that platform's architecture.
2. Move away from `platform.architecture` and use system native methods to figure out the architecture (isainfo on SunOS, getconf on HPUX, etc.). This method will probably render more consistent results, but it has the disadvantage that you must take all sorts of variables into consideration (os types, os versions, releases, hardware architectures, etc.).

**Comment by mpdehaan** [comment]
I've changed the defect topic from "cannot be trusted" to "is incorrect", as this totally sounded like some kindof security issue, and it's not :)

Further, I don't think this is not a bug.  

There are other facts for architecture (like 'ansible_architecture'), as this was added to detect that we were running a 32bit python on a 64 bit OS, so is working as designed, IMHO.   

If you disagree, let's discuss on the ansible-devel list.
