### ISSUE TITLE
ssh connection closed

### ISSUE THREAD

**Issue by shdat** [ansible/ansible#55119]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by Akasurde** [comment]
@shdat It would be nice if you can some details about the problem you are facing and reproducer. Thanks

needs_info

**Comment by mkrizek** [comment]
As stated above, please create a new issue with details on how to reproduce the issue and complete output from running Ansible.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
