### ISSUE TITLE
Deprecation warning on 'inventory/__init__.py'

### ISSUE THREAD

**Issue by tonk** [ansible/ansible#5513]
Since last night (I'm running the latest version from Github) I get:

```
/usr/lib/python2.6/site-packages/ansible/inventory/__init__.py:24: DeprecationWarning: the sets module is deprecated
  from sets import Set
```

Git logging shows that this is new, added on 2014-01-06 by James Tanner.

I'm wondering why this construction is used, because as far as I know Python 2.4 also support sets.

**Comment by lichesser** [comment]
Check #5517
