### ISSUE TITLE
Docs have collapsed navigation on module pages.

### ISSUE THREAD

**Issue by jiv-e** [ansible/ansible#5514]
Module pages on docs have a collapsed navigation. I compiled the docs locally and it works as I would expect. Are the online docs up to date?

See: https://twitter.com/jiv_e/status/419953803073712128

Online: http://docs.ansible.com/accelerate_module.html

Compare to my locally compiled docs:
![screen shot 2014-01-06 at 23 34 16](https://f.cloud.github.com/assets/831144/1854407/b6d6b0ea-771b-11e3-907c-1de58e8d5d2e.png)

**Comment by mpdehaan** [comment]
Updated Sphinx on my dev instance and seems to match now.

Let me know if you disagree.  Thanks!
