### ISSUE TITLE
Make with_items and first_available_file usable together or otherwise warn

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#552]
first_available_file currently clobbers the "src" variable.   

If we want to fix this, to allow both to be used in conjunction, "first_available_file" should set a variable called "file" and do less magic.   Currently it first_available_file sets src=<path> for you, which is not neccessarily what you want to do, because you might want to use it with a shell command, etc.   To avoid clashing with with_items, first_available_file should use "$file", while with_items uses "$item".

This will require updating the docs and we should mention this in the release notes that the variable is different.

**Comment by mpdehaan** [comment]
I am inclined to just make this an error, there are few cases where you should do this, and most times you want first_available_file you could just use vars_files.

**Comment by mpdehaan** [comment]
done, now raises an error if used together.

**Comment by rektide** [comment]
Hi. I'd just like to chime in that I would really like this not to be an error!

I want to be able to loop through variables creating files. And I want to be able to do first_available_file to decide what template I want to render, on a file by file basis.

I've put forth some example code that could be used as a test fixture were this feature to be implemented-
https://github.com/rektide/ansible-with-first

**Comment by rektide** [comment]
In particular, I'm trying to create a bunch of /etc/bind9/zone.d/blah.zone files, and allow these files to either come from a stock template, or to have the template sourced from an override for the specific zone.

**Comment by bcoca** [comment]
jinja2 has 'first available' includes, you should be able to do this w/o any new features

**Comment by bcoca** [comment]
An example, this will include specfic.tpl if it exists, otherwise it tries to include default.tpl

{% include ['specific.tpl', 'default.tpl'] %}

**Comment by rektide** [comment]
it seems most unpure to me to have to have a top level template whose purpose is to immediately figure out the real template to run, but this is a great hackjob that i'm going to gladly embrace right now. i would far prefer this issue be given further consideration: with_{plugin} is about creating iterations of an action, first_available_file can complement that by looking up files within these iterations.

**Comment by rektide** [comment]
i just stumbled upon https://github.com/ansible/ansible/pull/2260 which is furthering the act of conjoining/conflating first_available_file to with_{plugin}.
