### ISSUE TITLE
register fails to create variables

### ISSUE THREAD

**Issue by kormoc** [ansible/ansible#5522]
As of 32aec8ea1d17635f583fb44bf7f9e7c5d692622b, register seems to fail to create the proper variable.

Example playbook:

```

---
- shell: /usr/bin/uptime
  register: result
- debug: var=result

- stat: path=/etc/yum.repos.d/epel.repo
  register: check_path
- debug: var=check_path
```

Run result:

```
PLAY [all] ******************************************************************** 

TASK: [repos | shell /usr/bin/uptime] ***************************************** 
changed: [flexo.kormoc.com]

TASK: [repos | debug var=result] ********************************************** 
ok: [flexo.kormoc.com] => {
    "item": "", 
    "result": "{{ result }}"
}

TASK: [repos | stat path=/etc/yum.repos.d/epel.repo] ************************** 
ok: [flexo.kormoc.com]

TASK: [repos | debug var=check_path] ****************************************** 
ok: [flexo.kormoc.com] => {
    "check_path": "{{ check_path }}", 
    "item": ""
}
```

As you can see, `result` and `check_path` fail to be valid variables.

**Comment by srgvg** [comment]
I can comfirm this, tested on 

ansible 1.5 (devel 32aec8ea1d) last updated 2014/01/07 09:51:42 (GMT +200)

**Comment by srgvg** [comment]
Running git bisect yields 3ca9b1123ba29f550e0307ef1222c15b7edf163f is the first bad commit

```
3ca9b1123ba29f550e0307ef1222c15b7edf163f is the first bad commit
commit 3ca9b1123ba29f550e0307ef1222c15b7edf163f
Author: Michael DeHaan <michael@ansibleworks.com>
Date:   Mon Jan 6 17:59:00 2014 -0500

    Work in progress on fact caching implementation.
```

**Comment by lichesser** [comment]
Yes I also confirmed 3ca9b1123ba29f550e0307ef1222c15b7edf163f but didn't get around to post it earlier. So it wasn't me :relieved:

**Comment by mpdehaan** [comment]
Looking at this now.

**Comment by mpdehaan** [comment]
I've switched the default fact caching to 'memory' to avoid this problem until I can fix the implementation of 'bypass'.

This is now resolved on the development branch.
