### ISSUE TITLE
Please provide a way to turn off syslog module invocation logging on the remote machine

### ISSUE THREAD

**Issue by mvo5** [ansible/ansible#5525]
Hello,

I'm the debian maintainer of ansible and we got the following bugreport:
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=707275

that asks to allow to turn off the syslog message when a remote module is invoked, i.e. in syslog:
"""
Jan  7 14:19:03 xxxx ansible-ping: Invoked with data=None 
"""

It looks like this is needs to be done by providing a way for the runner to pass "no_log" for a BasicModule. But it looks to do this module would have to be touched which does not look like a good solution. 

I'm happy to look deeper and hack on this if there is a chance for it to get merged.

Cheers,
 Michael

**Comment by mpdehaan** [comment]
no_log is actually about not logging a certain parameter.

I think what we want here is an ansible config file setting for disabling the syslog info, which means each module needs to take a (hidden) parameter to disable the log.

**Comment by mvo5** [comment]
Thanks, I followed your advice and implemented this as you suggested (or as I understood it :)

**Comment by mpdehaan** [comment]
I'm closing this extra ticket record as we have a pull request ticket pointing at it now, and can still get to this page from there.  Thanks!
