### ISSUE TITLE
Misbehavior of 'register:'  when using sudo with 'script' module

### ISSUE THREAD

**Issue by LucianoCavalheiro** [ansible/ansible#5533]
While capturing the output of a remote script executed using the 'script' module with sudo enabled, a sudo "success_key", which is a string in the form "SUDO-SUCCESS-(some random key...)" is prepended to actual output produced by the remote script, leaving garbage in the registered variable stdout field.

This behavior is observed in Ansible 1.4.3 as well as on current development branch in git, however it does not affect commands executed via 'command' module. 

This used to work just fine in with Ansible 1.3.x series.

The following playbook demonstrates the issue:

```

---
- name: "Test with sudo and register"
  hosts: www-php5-4
  tasks:
    - command: /bin/ls /
      register: result
    - debug: "var=result.stdout"
    - script: files/scripts/list_dir "/"
      register: result
    - debug: "var=result.stdout"
```

Where list_dir could be any script. 

Here is the produced verbose output:

```
TASK: [command /bin/ls /] *****************************************************
changed: [www-php5-4] => {"changed": true, "cmd": ["/bin/ls", "/"], "delta": "0:00:00.009592", "end": "2014-01-07 13:58:27.294366", "rc": 0, "start": "2014-01-07 13:58:27.284774", "stderr": "", "stdout": "bin\nboot\ndev\netc\nhome\nhome-sys\ninitrd.img\nlib\nlib64\nlost+found\nmedia\nmnt\nopt\nproc\nroot\nrun\nsbin\nselinux\nsrv\nsys\ntmp\nusr\nvar\nvmlinuz"}

TASK: [debug var=result.stdout] ***********************************************
ok: [www-php5-4] => {
    "result.stdout": "bin\nboot\ndev\netc\nhome\nhome-sys\ninitrd.img\nlib\nlib64\nlost+found\nmedia\nmnt\nopt\nproc\nroot\nrun\nsbin\nselinux\nsrv\nsys\ntmp\nusr\nvar\nvmlinuz"
}

TASK: [script files/scripts/list_dir "/"] *************************************
changed: [www-php5-4] => {"changed": true, "rc": 0, "stderr": "", "stdout": "\r\nSUDO-SUCCESS-wbzcrtmosfpuylypyhbeoaxovzwkmgjw\r\nbin etc\tinitrd.img  lost+found\topt   run      srv  usr\r\nboot home\tlib\t    media\tproc  sbin     sys  var\r\ndev   home-sys\tlib64\t    mnt\t\troot  selinux  tmp  vmlinuz\r\n"}

TASK: [debug var=result.stdout] ***********************************************
ok: [www-php5-4] => {
    "result.stdout": "\r\nSUDO-SUCCESS-wbzcrtmosfpuylypyhbeoaxovzwkmgjw\r\nbin etc\tinitrd.img  lost+found\topt   run      srv  usr\r\nboot home\tlib\t    media\tproc  sbin     sys  var\r\ndev   home-sys\tlib64\t    mnt\t\troot  selinux  tmp  vmlinuz\r\n"
} 
```

**Comment by LucianoCavalheiro** [comment]
The problem seems to have been introduced by commit ea2ec6237aa97e6c434ccf4af124f0632747ef06 which executes an 'echo' of the sudo success_key before actually executing the script. 

It seems this value was left from some debugging stage of development, since it is used at no where.

**Comment by mpdehaan** [comment]
Yeah so it's not related to debugging, it's related to detecting errors sudoing.   We'll just have to figure out how to nicely strip it out (or why this is not done in the sudo script case)

**Comment by sivel** [comment]
Since it was asked on the commit as well:  Here is the link to my response there too:

https://github.com/ansible/ansible/commit/ea2ec6237aa97e6c434ccf4af124f0632747ef06#commitcomment-5004720

**Comment by LucianoCavalheiro** [comment]
Unless your sudo prompt is distinct from what I have here in by box, I think the 'echo' would be suppressed.

Please review my argument at:
https://github.com/ansible/ansible/commit/ea2ec6237aa97e6c434ccf4af124f0632747ef06#commitcomment-5005118

**Comment by sivel** [comment]
Let's try to keep discussion here, rather than on the commit.

The echo always happens regardless of needing to give a password or not.  Because, the heart of the problem is that, you cannot know (unless you have another system that tells you) whether or not sudo will actually prompt you for a password.  So the echo in that location, is for the scenario where you provided a password but the prompt was never encountered, but the sudo attempt was successful.

If you don't echo a success key, and you never get a prompt, are you sure the sudo was successful?

If you see the prompt, send the password. If you see the success_key, assume that sudo was successful, and didn't require a password, so don't send the password.

I see 1 option here if this is actually a problem, and it should be pretty simple.  Just add the following code exec_command:

`stdout = stdout.replace(success_key, '')`

**Comment by LucianoCavalheiro** [comment]
I think this should work for me. But since will always be doing a replace over the whole output there should be a penalty involved, even when no replace would be necessary.

Since SUDO-SUCCESS will always happen, I would rather change the loop to something like this:

``` diff
-            while not sudo_output.endswith(prompt) and success_key not in sudo_output:
+            while success_key not in sudo_output:
                 rfd, wfd, efd = select.select([p.stdout], [],
                                               [p.stdout], self.runner.timeout)
                 if p.stdout in rfd:
                     chunk = p.stdout.read()
                     if not chunk:
                         raise errors.AnsibleError('ssh connection closed waiting for sudo password prompt')
                     sudo_output += chunk
+                    if sudo_output.endswith(prompt):
+                        stdin.write(self.runner.sudo_pass + '\n')
                 else:
                     stdout = p.communicate()
                     raise errors.AnsibleError('ssh connection error waiting for sudo password prompt')
-            if success_key not in sudo_output:
-                stdin.write(self.runner.sudo_pass + '\n')        
```

Do you think this would break something?

**Comment by sivel** [comment]
So although I participated in discussion throughout the day on this, I just got time to test and cannot reproduce the issue of the success_key leaking into stdout of the shell module.

Can you provide more info about the OS of the target machines?

Of special interest here, it would appear that the shell and command module are actually the same, it is just that when using shell, the command is not split using shlex.split

See:

https://github.com/ansible/ansible/blob/release1.4.4/lib/ansible/runner/action_plugins/normal.py#L48-L51
https://github.com/ansible/ansible/blob/release1.4.4/library/commands/command#L182-L184
https://github.com/ansible/ansible/blob/release1.4.4/library/commands/command#L134-L135
https://github.com/ansible/ansible/blob/release1.4.4/lib/ansible/module_utils/basic.py#L948

Going back to what @mpdehaan said on the mailing list "I would probably look to see what's normally absorbing this message and why it doesn't in the script module case, provided you can see this behavior on the development branch."

I think we should probably start there, as opposed to attempting to make changes to the sudo detection code right away.

Here is my test playbook:

``` yaml
---
- hosts: all
  sudo: yes
  tasks:
  - name: Run whoami via shell
    shell: whoami
    register: whoami
  - name: Output whoami.stdout
    debug:
      var: whoami.stdout

  - name: Create a list_dir script
    copy:
      content: |
        #!/bin/bash
        ls "$@"
      dest: /tmp/list_dir
      mode: 0755

  - name: run the list_dir script via shell
    shell: /tmp/list_dir "/"
    register: list_dir
  - debug:
      var: list_dir.stdout
```

The invocation of ansible-playbook looks similar to the following:

`ansible-playbook -K -u myuser -i rhel5_host shell.yml`

I have the playbook create a list_dir script that to the best of my understanding does what your example does.

I ran this on the following machines:
1. RHEL5 (Python 2.4.3 with simplejson 2.0.9)
2. RHEL6 (Python 2.6.6 with json 1.9)
3. Ubuntu 12.04 (Python 2.7.3 json 2.0.9)

In all cases everything appears to work as expected.  Here were their outputs:

RHEL5:

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [rhel5.example.org]

TASK: [Run whoami via shell] **************************************************
changed: [rhel5.example.org]

TASK: [Output whoami.stdout] **************************************************
ok: [rhel5.example.org] => {
    "whoami.stdout": "root"
}

TASK: [Create a list_dir script] **********************************************
ok: [rhel5.example.org]

TASK: [run the list_dir script via shell] *************************************
changed: [rhel5.example.org]

TASK: [debug ] ****************************************************************
ok: [rhel5.example.org] => {
    "list_dir.stdout": "bin\nboot\ndev\netc\nhome\ninstaller.sh\nlib\nlib64\nlost+found\nmedia\nmisc\nmnt\nopt\nproc\nroot\nsbin\nselinux\nsrv\nsys\ntmp\nusr\nvar"
}

PLAY RECAP ********************************************************************
rhel5.example.org            : ok=6    changed=2    unreachable=0    failed=0
```

RHEL6:

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [rhel6.example.org]

TASK: [Run whoami via shell] **************************************************
changed: [rhel6.example.org]

TASK: [Output whoami.stdout] **************************************************
ok: [rhel6.example.org] => {
    "whoami.stdout": "root"
}

TASK: [Create a list_dir script] **********************************************
changed: [rhel6.example.org]

TASK: [run the list_dir script via shell] *************************************
changed: [rhel6.example.org]

TASK: [debug ] ****************************************************************
ok: [rhel6.example.org] => {
    "list_dir.stdout": "bin\nboot\ndev\netc\nhome\ninstaller.sh\nlib\nlib64\nlost+found\nmedia\nmnt\nopt\nproc\nroot\nsbin\nselinux\nsrv\nsys\ntmp\nusr\nvar"
}

PLAY RECAP ********************************************************************
rhel6.example.org            : ok=6    changed=3    unreachable=0    failed=0
```

Ubuntu 12.04:

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [ubu12.example.org]

TASK: [Run whoami via shell] **************************************************
changed: [ubu12.example.org]

TASK: [Output whoami.stdout] **************************************************
ok: [ubu12.example.org] => {
    "whoami.stdout": "root"
}

TASK: [Create a list_dir script] **********************************************
changed: [ubu12.example.org]

TASK: [run the list_dir script via shell] *************************************
changed: [ubu12.example.org]

TASK: [debug ] ****************************************************************
ok: [ubu12.example.org] => {
    "list_dir.stdout": "bin\nboot\ndev\netc\nhome\ninitrd.img\ninitrd.img.old\nlib\nlib64\nlost+found\nmedia\nmnt\nopt\nproc\nroot\nrun\nsbin\nselinux\nsrv\nsys\ntmp\nusr\nvar\nvmlinuz\nvmlinuz.old"
}

PLAY RECAP ********************************************************************
ubu12.example.org            : ok=6    changed=3    unreachable=0    failed=0
```

**Comment by LucianoCavalheiro** [comment]
I'm not using the 'shell' module. I tested your playbook and with 'shell', likewise 'command', things work just fine.
The problem I reported occurs when I use the 'script' module. 

Would you mind to re-run your test playbook using the 'script' instead of shell module?

The box I'm testing is Debian/7.0 (stable) with Python 2.7.3.

**Comment by sivel** [comment]
Thank you for that.  I apparently glossed right over that.  I will update the test and see what I can come up with.

**Comment by LucianoCavalheiro** [comment]
It seems that commad and shell, as new-style modules, are execute via `Runner._execute_module`. 
https://github.com/ansible/ansible/blob/release1.4.4/lib/ansible/runner/action_plugins/normal.py#L54 

This, after the moduled is execute, calls `utils.parse_json` to processes module output:
https://github.com/ansible/ansible/blob/release1.4.4/lib/ansible/runner/__init__.py#L369

Function `parse_json` has code to discard arbitrary messages output at the session before module json data:
https://github.com/ansible/ansible/blob/release1.4.4/lib/ansible/utils/__init__.py#L297
https://github.com/ansible/ansible/blob/release1.4.4/lib/ansible/utils/__init__.py#L735- L750

---

However, 'script' module is implemented over 'raw' module and so follows a different execution path:
https://github.com/ansible/ansible/blob/release1.4.4/lib/ansible/runner/action_plugins/script.py#L75

Module raw uses `runner._low_level_exec_command` directy instead of `runner._execute_module`. So, `parse_json` is never called and no part of output is discarded.

While it would be possible to hack script and raw to discard the success_key of sudo, I think that would be misplaced if done there. Such code belongs to connection handler, because sudo success/failure is processed there. 

The modification I proposed at https://github.com/ansible/ansible/issues/5533#issuecomment-31779205 seems to solve the issue. As a (good) side effect, I think it would also make the 'filter_leading_non_json_lines' hack at parse_json no longer necessary, since any messages prior the success_key will be discarded.

**Comment by sivel** [comment]
I'll look more into your proposed solution, however the `filter_leading_non_json_lines` "hack" has been there for some time, and I am sure that it has a purpose beyond the success_key.

**Comment by sivel** [comment]
I have indeed confirmed this behavior, both with `script` and `raw`, but only when a sudo password is prompted for.  Here is the modified test play I have been using:

``` yaml
---
- hosts: all
  sudo: yes
  tasks:
  - name: Create a list_dir script
    local_action:
      module: copy
      content: |
        #!/bin/bash
        ls "$@"
      dest: "{{ playbook_dir }}/list_dir"

  - name: run the list_dir script via script
    script: list_dir "/"
    register: list_dir
  - debug:
      var: list_dir.stdout
  - fail:
      msg: "SUDO-SUCCESS in stdout"
    when: "'SUDO-SUCCESS' in list_dir.stdout"
    ignore_errors: true

  - name: run whoami via raw
    raw: whoami
    register: whoami
  - debug:
      var: whoami.stdout
  - fail:
      msg: "SUDO-SUCCESS in stdout"
    when: "'SUDO-SUCCESS' in whoami.stdout"
    ignore_errors: true

```

**Comment by MorrisA** [comment]
In response to the last comment by sivel (of course my screen updated with lots more comments since) I have to butt in and say that it does not appear to be an issue with the shell module, but the script module.  From some poking I did last night it looks like the SUDO-SUCCESS is eaten by make_sudo_cmd -n lib/ansible/utils/**init**.py but the script plugin (lib/ansible/runner/action_plugins/script.py) does not use that function...

I hope that this helps.

Adam

**Comment by sivel** [comment]
My testing so far on the solution proposed in https://github.com/ansible/ansible/issues/5533#issuecomment-31779205 seems to work.

I have however only tested this with a small subset of functionality and target operating systems.  I imagine this would need more testing to validate that everything is still good.

**Comment by LucianoCavalheiro** [comment]
@MorrisA `make_sudo_cmd`is actually where SUDO-SUCCESS is inserted in the output. `make_sudo_cmd`is called by connection plugins, and so indirectly called when the script module invokes `runner._low_level_exec_command`. Please see https://github.com/ansible/ansible/issues/5533#issuecomment-31831514

Regarding my proposed soluting in https://github.com/ansible/ansible/issues/5533#issuecomment-31779205 i see a potential problem which could affect the current implementation too: depending on how information is flushed in the ssh connection, `chunk = p.stdout.read()` may return data that is after the success_key, and thus is part of the output of the script. If that ever happens, those bytes will be lost since `stdout` variable is initialized to an empty string a few lines bellow dropping any remaining content in sudo_output where success_key is.

Although I think it could happen in theory, I could not manage to force this error to occur inside ansible because it depends heavily on timing.

**Comment by LucianoCavalheiro** [comment]
The new solution bellow, although not solving the entirely the problem, avoids masking the situation when sudo_output eats bytes that would rather belongs to command's stdout (ssh will timeout in the case). 

``` diff
--- a/lib/ansible/runner/connection_plugins/ssh.py
+++ b/lib/ansible/runner/connection_plugins/ssh.py
@@ -202,7 +202,7 @@ class Connection(object):
             fcntl.fcntl(p.stdout, fcntl.F_SETFL,
                         fcntl.fcntl(p.stdout, fcntl.F_GETFL) | os.O_NONBLOCK)
             sudo_output = ''
-            while not sudo_output.endswith(prompt) and success_key not in sudo_output:
+            while not sudo_output.rstrip('\r\n').endswith(success_key):
                 rfd, wfd, efd = select.select([p.stdout], [],
                                               [p.stdout], self.runner.timeout)
                 if p.stdout in rfd:
                     chunk = p.stdout.read()
                     if not chunk:
                         raise errors.AnsibleError('ssh connection closed waiting for sudo password prompt')
                     sudo_output += chunk
+                    if sudo_output.endswith(prompt):
+                        stdin.write(self.runner.sudo_pass + '\n')
                 else:
                     stdout = p.communicate()
                     raise errors.AnsibleError('ssh connection error waiting for sudo password prompt')
-            if success_key not in sudo_output:
-                stdin.write(self.runner.sudo_pass + '\n')
             fcntl.fcntl(p.stdout, fcntl.F_SETFL, fcntl.fcntl(p.stdout, fcntl.F_GETFL) & ~os.O_NONBLOCK)

         # We can't use p.communicate here because the ControlMaster may have stdout open as well
```

I think that the full solution would just require detecting and transporting any extra bytes after success_key in `sudo_output` to `stdout` variable.

**Comment by LucianoCavalheiro** [comment]
I'll propose a patch covering all connection plugins by the weekend. 
@sivel Thanks for all the hints.

**Comment by LucianoCavalheiro** [comment]
I've just made a pull request with a patch for this issue. 
Would you take a look and provide some feedback on whether it is acceptable?

As far as I could test, this patch also fix the problem of `success_key` handling code eating part of the remote command output depending on when ssh connection is flushed. For instance:

```
---
# 
- name: "Test with sudo and register"
  hosts: "{{target)}}"
  sudo: True
  vars:
    msg: "PIGBACK"
  tasks:
    - raw: echo {{msg}}
      register: result
      sudo: True    
    - debug:
        var: result.stdout
    - fail: msg="no match"
      when: not result.stdout.startswith(msg)
```

`result.stdout`never includes the message in '{{msg}}' although it completes with success. This occurs since `echo` is handled faster because it is built in the shell, but since it a matter of timing it would affect other commands under specific hardware I think.

**Comment by LucianoCavalheiro** [comment]
@mpdehaan Following the suggestions from you and Brian in https://github.com/ansible/ansible/pull/5599, I've reviewed that pull request, re-based everything and split into per-connection type PR. Would you mind to take a look and confirm this look ok this time?

https://github.com/ansible/ansible/pull/5605
https://github.com/ansible/ansible/pull/5606
https://github.com/ansible/ansible/pull/5607
https://github.com/ansible/ansible/pull/5608

That patch is essentially the same I've tested before with Debian 7.0/stable and Python 2.7.3.

**Comment by jimi-c** [comment]
We decided to go another, more simple way with this fix. Thanks for reporting it, and let us know if you have any other questions regarding this issue!

**Comment by LucianoCavalheiro** [comment]
I've ended converting my script into an ansible module because of other aspects.

@jimi-c  My only concern with the solution you chose to implement is that it somewhat go against encapsulation, since it leaks an information that belongs to connection management into a module, while in theory all modules should be agnostic to connection plugins. I acknowledge that I'm often too purist about such aspects and I understand that today it only affects module 'raw' and 'script' but I wonder if that will hold for any new modules that came out. 

Anyway, thanx for the feedback.

**Comment by jimi-c** [comment]
Yeah those are somewhat special cases since they do not deal in JSON output directly and are also handled by action_plugins. This should not really ever come up again.
