### ISSUE TITLE
overriding role's default variable doesn't work with structured variables

### ISSUE THREAD

**Issue by obormot** [ansible/ansible#5537]
Ansible 1.4.4, Python 2.7.5 on Mac OS X

In the example below `normal_var` works as expected - its default value defined in the role is getting overridden by the playbook. `dict_var` however (its attribute `b`) stays intact. I tried to define it in other places - in host_vars/testhost file, inline in the playbook, and same result everywhere. 
## Role:

```
# file: roles/test/defaults/main.yml
dict_var:
  a: 'a_default'
  b: 'b_default'
normal_var: 'n_default'

# file: roles/test/tasks/main.yml
- debug: msg="{{ normal_var }}"
- debug: msg="{{ dict_var }}"
```
## Playbook:

```
- hosts: testhost
  vars:
    - normal_var: 'n_override'
    - dict_var.b: 'b_override'

  roles:
    - test
```
## Output:

```
TASK: [test | debug msg="n_override"] *****************************************
ok: [127.0.0.1] => {
    "item": "",
    "msg": "n_override"
}

TASK: [test | debug msg="{{dict_var}}"] ***************************************
ok: [127.0.0.1] => {
    "item": "",
    "msg": "{'a': 'a_default', 'b': 'b_default'}" <<<<<<<<< **BUG**
}
```

**Comment by mpdehaan** [comment]
"    - dict_var.b: 'b_override'"

This isn't a valid or intended syntax and will create a new variable with a dot in it.

It would probably be better to first start with "how do I do this" and then we'll get there.

It sounds like you may wish to turn on hash merging in ansible.cfg and rely on variable overriding via group_vars and other things, but a discussion of the use case is probably a good place to start.

In any event, please pose this on the mailing list.

I'm going to close this as the syntax above wasn't intended to be a thing.

Thanks!
