### ISSUE TITLE
Forced push on devel and release1.3.0?

### ISSUE THREAD

**Issue by lichesser** [ansible/ansible#5539]
Did you just do a forced push to the world public  `devel` and the `release1.3.0` branches?

On `git pull` on a clone of this repo I got prompted to do a merge and have the following output

```
[snip]
From https://github.com/ansible/ansible
 + 32aec8e...c8bd149 devel      -> origin/devel  (forced update)
 + 272bdeb...1fb73a7 release1.3.0 -> origin/release1.3.0  (forced update)
[snip]
```

and `git status`

```
# On branch devel
# Your branch is ahead of 'origin/devel' by 20 commits.
#
```

And then there is this troubling message https://github.com/ansible/ansible/pull/5534#issuecomment-31778190

Also all the "new cache" related commits are now gone. I hope the repo gets fixed in the proper way by getting back the "old history" and just doing a new commit which removes the "new cache" related commits.

**Comment by sivel** [comment]
Yes, the repo was force pushed, to remove the FactCache code that had broken functionality in the branch and could not be easily fixed.

See https://groups.google.com/d/msg/ansible-devel/aC-BjeBTMho/_8XIcv9CZzUJ

There are no plans to "restore" history.

Per @mpdehaan:

```
We are aware but this was easier and more important that we revert what was going on,
versus wait to make it all pretty as many people checkout devel directly. Generally this
is something we don't do, but in this case, there was enough lurking not covered by tests
where that had to go
```

**Comment by mpdehaan** [comment]
_YES_

(If you would like to ask questions, please stop by the ansible-devel mailing list)

This tracker is for filing bugs and submitting code, etc -- but not so much group discussion.

The list post will also give you commentary on the fact caching bits.
