### ISSUE TITLE
cdbs: missing dependency

### ISSUE THREAD

**Issue by elimisteve** [ansible/ansible#5545]
I ran these commands on 64-bit Ubuntu 10.10...

```
git clone git://github.com/ansible/ansible.git
cd ansible
make deb
```

...and got these errors:

```
...
creating dist
tar -cf dist/ansible-1.5.tar ansible-1.5
gzip -f9 dist/ansible-1.5.tar
tar -cf dist/ansible-1.5.tar ansible-1.5
gzip -f9 dist/ansible-1.5.tar
removing 'ansible-1.5' (and everything under it)
cp -r packaging/debian ./
chmod 755 debian/rules
fakeroot debian/rules clean
make[1]: Entering directory `/home/steve/repos/ansible'
debian/rules:4: /usr/share/cdbs/1/rules/debhelper.mk: No such file or directory
debian/rules:6: /usr/share/cdbs/1/class/python-distutils.mk: No such file or directory
make[1]: *** No rule to make target `/usr/share/cdbs/1/class/python-distutils.mk'.  Stop.
make[1]: Leaving directory `/home/steve/repos/ansible'
make: *** [deb] Error 2
```

After running `sudo apt-get install cdbs`, `make deb` worked.

**Comment by elimisteve** [comment]
Update:

Running

`sudo dpkg -i ansible_1.5_all.deb`

Resulted in...

```
Selecting previously deselected package ansible.
(Reading database ... 248069 files and directories currently installed.)
Unpacking ansible (from ansible_1.5_all.deb) ...
dpkg: dependency problems prevent configuration of ansible:
 ansible depends on python-jinja2; however:
  Package python-jinja2 is not installed.
 ansible depends on python-yaml; however:
  Package python-yaml is not installed.
 ansible depends on sshpass; however:
  Package sshpass is not installed.
dpkg: error processing ansible (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db ...
Errors were encountered while processing:
 ansible
```

I figured I must have forgotten some dependencies, but running `sudo pip install paramiko PyYAML jinja2 httplib2` resulted in...

```
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /usr/local/lib/python2.6/dist-packages
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /usr/local/lib/python2.6/dist-packages
Requirement already satisfied (use --upgrade to upgrade): httplib2 in /usr/local/lib/python2.6/dist-packages
Requirement already satisfied (use --upgrade to upgrade): paramiko in /usr/local/lib/python2.6/dist-packages
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.1 in /usr/local/lib/python2.6/dist-packages (from paramiko)
Cleaning up...
```

**Comment by elimisteve** [comment]
Update #2: Additionally running this worked --

```
sudo apt-get install python-jinja2 python-yaml sshpass
```

More detailed output:

```
...
Fetched 295kB in 43s (6,829B/s)                                                          
Selecting previously deselected package python-jinja2.
(Reading database ... 248367 files and directories currently installed.)
Unpacking python-jinja2 (from .../python-jinja2_2.5.2-2ubuntu1_amd64.deb) ...
Selecting previously deselected package python-yaml.
Unpacking python-yaml (from .../python-yaml_3.09-4build1_amd64.deb) ...
Selecting previously deselected package sshpass.
Unpacking sshpass (from .../sshpass_1.04-1_amd64.deb) ...
Processing triggers for man-db ...
Setting up python-jinja2 (2.5.2-2ubuntu1) ...
Setting up python-yaml (3.09-4build1) ...
Setting up sshpass (1.04-1) ...
Setting up ansible (1.5) ...
Installing new version of config file /etc/ansible/hosts ...
Processing triggers for python-support ...
```

Ideally I wouldn't have to run these and installing them via `pip` would be good enough, but at least I got it working :-).

Making `cdbs` an explicit dependency is still important IMO.

**Comment by bcoca** [comment]
cdbs are a dependency of building debian packages, ansible does not depend
on them to work.

**Comment by elimisteve** [comment]
Hi @bcoca. I followed the instructions for installing Ansible on a Debian-based OS and it didn't work.  It seems like there should be some good way to make the `make deb` requirements/dependencies as explicit as the dependencies for getting Ansible in the other ways, don't you think?

**Comment by mpdehaan** [comment]
This seems to be an OS dependency rather than an Ansible dependency.

At least, I run this project and have no idea what the cdbs package is :)

does something normally pull this in as we're not explicitly installing this in any of our build or test machines.

**Comment by bcoca** [comment]
The instructions of installing ansible from .deb should have no
dependencies,  the instructions of building a .deb assumes your system is
setup to do so, a basic dependency for building ANY .deb is the debian
build tools, which cdbs is part of.

Also, check your distro, ansible (maybe not latest version) should already
be available from their main repos.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by lichesser** [comment]
To me it seems that [packaging/debian/README.md](https://github.com/ansible/ansible/blob/devel/packaging/debian/README.md) lists `cdbs` among other things as dependency for making debian package

But maybe this file should be linked up somewhere more prominently

**Comment by elimisteve** [comment]
@lichesser Good idea IMO.

**Comment by mpdehaan** [comment]
Ok, so no action required?

**Comment by mpdehaan** [comment]
Closing per comment from @bcoca above
