### ISSUE TITLE
subversion module - fails when using locale fr_FR.UTF-8

### ISSUE THREAD

**Issue by albanduval** [ansible/ansible#5549]
The method to get data from the svn info is locale dependent.

When using a french locale for example, the output of a `svn info` would be :

```
Chemin : .
URL : http://my.svn.com/myproject/trunk
Racine du dépôt : http://my.svn.com/myproject
UUID du dépôt : 5441de51-5781-4c35-9d14-90f6f03185cc
Révision : 3546
Type de nœud : répertoire
Tâche programmée : normale
Auteur de la dernière modification : last_commit_user
Révision de la dernière modification : 318
Date de la dernière modification: 2013-12-26 11:45:22 +0100 (Thu 26 Dec 2013)
```

Then the regexp used to get Revision number would not work (library/source_control/subversion line 130) : 

``` python
rev = re.search(r'^Revision:.*$', text, re.MULTILINE).group(0)
```

I guess the right way to fix this would be to force the C locale before executing the `svn info`.

**Comment by mpdehaan** [comment]
Yep, seems like it.

Thanks for the report.

If you want to work on it, we'll also happily take pull requests!

**Comment by resmo** [comment]
@albanduval are you working no the fix?

**Comment by mpdehaan** [comment]
the above is merged so looks like we can close this
