### ISSUE TITLE
Variables don't stick to hosts from ec2.py

### ISSUE THREAD

**Issue by sebmaynard** [ansible/ansible#5559]
Similar to https://github.com/ansible/ansible/issues/5235

Variables don't stick to hosts pulled in from ec2.py dynamic inventory script.

See https://gist.github.com/sebmaynard/035d9dc6ecaf02e45304 for example files and output - using set_fact does work, but I can't set those from group_vars or inventory.

**Comment by mpdehaan** [comment]
I'm not sure what "doesn't stick" means here.

Can you elaborate in words to complement the attached playbook example?

Many people are using the ec2 inventory script and I haven't heard problems reported on this before of this nature, and what you are linking to is not something that is related to how the ec2 inventory plugin sets variables.

**Comment by sebmaynard** [comment]
By stick, I meant that the variables aren't being set (or at least don't
seem visible to the playbook) as I tried to demonstrate in the Gist's output

**Comment by mpdehaan** [comment]
What version fo Ansible were you using for the above?   

Most issues we know from group_vars and host_vars/ have been dealt with.

**Comment by sebmaynard** [comment]
This was using Ansible checked out from HEAD, on the day I submitted. I've
got around this for now by using set_fact for the bits of information I
need attached to each host.

Seb

**Comment by mpdehaan** [comment]
set_fact applies to the host one is currently looping over, so it wouldn't apply to what was added with add_host.  This is the problem with the above example.
