### ISSUE TITLE
unclear if a shell is ansible-hacking enabled

### ISSUE THREAD

**Issue by vegitron** [ansible/ansible#5560]
I have too many shells open, so it gets hard to track which shells I've run hacking/env-setup in.  If the prompt could be enhanced, that would make it easier for me to track what's happening.

**Comment by bcoca** [comment]
I just source it in my bashrc ... so ALL shells have it.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
This is not a bug but we would consider reading pull requests, as you have opened one, this ticket is redundant and I'll comment there.

Thank you!
