### ISSUE TITLE
invalid Jinja2 usage exposes python syntax error (edited description)

### ISSUE THREAD

**Issue by tartansandal** [ansible/ansible#5566]
The following playbook generates a traceback when run on the devel branch:

```
- name: test
  hosts: all
  gather_facts: false
  vars:
    - a_list:
      - a_value
  tasks:
    - name: I meant to concat a string with an array value
      debug: msg="{{ 'foo => ' + a_list[0] }}"  

    - name: But I accidentally concat a string with array
      debug: msg="{{ 'foo => ' + a_list }}"
```

The stacktrace generated:

```
fatal: [rizo] => Traceback (most recent call last):
  File "/srv/ansible-source/lib/ansible/runner/__init__.py", line 418, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/srv/ansible-source/lib/ansible/runner/__init__.py", line 509, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/srv/ansible-source/lib/ansible/runner/__init__.py", line 703, in _executor_internal_inner
    module_args = template.template(self.basedir, module_args, inject, fail_on_undefined=self.error_on_undefined_vars)
  File "/srv/ansible-source/lib/ansible/utils/template.py", line 319, in template
    varname = template_from_string(basedir, varname, vars, fail_on_undefined)
  File "/srv/ansible-source/lib/ansible/utils/template.py", line 550, in template_from_string
    return res
UnboundLocalError: local variable 'res' referenced before assignment
```

I gather that relates to a bug in the error trapping code rather than the jinja2 error.

The above minimal example was derived from a much more complex playbook. 
It took me a while to figure out that the problem was with the data for a particular host, given that the playbook worked on other hosts :-(

**Comment by bcoca** [comment]
On Thu, Jan 9, 2014 at 10:35 PM, Kal Hodgson notifications@github.comwrote:

> debug: msg="{{ 'foo => ' + a_list }}"

what about?

debug: msg="foo =>{{a_list}}"

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by tartansandal** [comment]
Hi Brian,

Yeah, if I do that I get a 'stringified' list

```
"msg": "foo => ['a_value']"
```

which would at least highlight the data error.

The actual context where I was doing this was building a path to pass to a lookup:

```
key="{{ lookup('file', '/srv/ansible-private/ssh/' + item + '.pub') }}"
```

so, unfortunately moving the braces is not going to help here.

Looking at the code above line 550 in utils/template.py, I think there may be a case for some more exception handling here, but I don't know enough bout what is going on here to offer any suggestions.

Kal

**Comment by mpdehaan** [comment]
This:

```
key="{{ lookup('file', '/srv/ansible-private/ssh/' + item + '.pub') }}"
```

Is known to work fine though.

So it seems this ticket is just about the debug module needing to return a better message when a variable doesn't exist, as "foo => bar" isn't a valid variable name by any means.

**Comment by tartansandal** [comment]
Hi Guys,

I think the bug report is being misinterpreted :-( 
1. This is a general case: I just used the debug module to generate a minimal test case, with some extra language to explain what was going on. The original module that triggered the issue was authorised_keys.
2. The variable is defined, the string concatenation in jinja2 seems to require both sides to be strings
3. This does seem to be related to #5563
4. The unbound variable in the traceback is the Python variable, not the Jinja2 variable. This looks like the Python syntax exception is masking the other exception.

The following python script throws the same exception and uses the same form
as in the utils/template.py:

```
#!/bin/env python

def throw_error():
    raise Exception('barf')

def run():
    try:
        res = throw_error()
    except Exception, e:
        print e.message 

    return res

run()
```

It seems the symbol 'res' is not bound before the exception is thrown causing the interpreter to throw another exception that masks the original. Simply setting the variable before the try block resolves the issue and allows the original exception to surface.

This is not a real solution for the ansible code: a lot more seems to be going on there and I don't understand enough of it to suggest a real fix.

**Comment by maedox** [comment]
``` python
authorized_key: user={{ item }} key="{{ lookup('file', 'public_keys/' + item) }}"
```

```
fatal: [localhost] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 394, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 514, in _executor_internal
    complex_args=complex_args
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 679, in _executor_internal_inner
    module_args = template.template(self.basedir, module_args, inject, fail_on_undefined=self.error_on_undefined_vars)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/template.py", line 319, in template
    varname = template_from_string(basedir, varname, vars, fail_on_undefined)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/template.py", line 543, in template_from_string
    return res
UnboundLocalError: local variable 'res' referenced before assignment
```

@mpdehaan, what you said was known to work doesn't seem to work.

I'm using Ansible 1.4.4 on Linux Mint 15 (Python 2.7.4).

I can't seem to find a working way to handle a list of users with a file per user containing one or more public keys. :-/

**Comment by sivel** [comment]
@maedox We may need to see more of your play in order to figure out what is wrong.  However, do note that there have been many fixes to the authorized_key module already in devel (1.5).  Additionally the traceback you are seeing has also been "fixed" and will now give you a more appropriate error message.

**Comment by maedox** [comment]
I installed 1.5 directly from the Git repo and got a bit further. I realize it might be a bit off topic, but if anyone can point me in the right direction it would be much appreciated.

``` yaml
-
  hosts: local

  vars:
    users:
      test

  tasks:
    - name: Add public key(s) for admin users
      authorized_key: user={{ item }} key="{{ lookup('file', item }}"
      with_items:
        users
```

The playbook file "test.yml" (above) and "test" (containing some RSA keys) are files on the same level. I intend to use the "Best practice" directory/file layout, but I simplified it a bit for troubleshooting purposes.

Running the play with:
ansible-playbook -vvv -i local test.yml -s

yields:

```
failed: [localhost] => (item=test) => {"failed": true, "item": "test"}
msg: Failed to lookup user {{item}}: 'getpwnam(): name not found: {{item}}'
```

I've been banging my head against the wall for a while now trying to get this to work, so apologies if it's obvious. (It's my first attempt at an Ansible play.)

**Comment by maedox** [comment]
Submitted as https://github.com/ansible/ansible/issues/5908.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is sample output using your example above:

<pre>
TASK [But I accidentally concat a string with array] ****************************
fatal: [localhost]: FAILED! => {"msg": "ERROR! an unexpected type error occurred. Error was cannot concatenate 'str' and 'list' objects", "failed": true}
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
