### ISSUE TITLE
tarballs seem to be broken (needs info)

### ISSUE THREAD

**Issue by iliv** [ansible/ansible#5569]
```
ansiblemgr@monitoring:~/ansible/releases/ansible-1.4.4$ make deb
cat: VERSION: No such file or directory
fatal: Not a git repository (or any of the parent directories): .git
Cleaning up distutils stuff
rm -rf build
rm -rf dist
Cleaning up byte compiled python stuff
find . -type f -regex ".*\.py[co]$" -delete
Cleaning up editor backup files
find . -type f \( -name "*~" -or -name "#*" \) -delete
find . -type f \( -name "*.swp" \) -delete
Cleaning up manpage stuff
find ./docs/man -type f -name "*.xml" -delete
find ./docs/man -type f -name "*.asciidoc" -delete
find ./docs/man/man3 -type f -name "*.3" -delete
Cleaning up output from test runs
rm -rf test/test_data
Cleaning up RPM building stuff
rm -rf MANIFEST rpm-build
Cleaning up Debian building stuff
rm -rf debian
rm -rf deb-build
rm -rf docs/json
rm -rf docs/js
Cleaning up authors file
rm -f AUTHORS.TXT
PYTHONPATH=./lib python hacking/module_formatter.py -A  -t man -o docs/man/man3/ --module-dir=library --template-dir=hacking/templates # --verbose
python: can't open file 'hacking/module_formatter.py': [Errno 2] No such file or directory
make: *** [modulepages] Error 2
```

The same release number builds deb package from a git just fine.

This happens on Ubuntu Server (precise), on two different systems.

**Comment by iliv** [comment]
Oh, same thing for 1.4.3

**Comment by lichesser** [comment]
Are you sure you followed [packaging/debian/README](https://github.com/ansible/ansible/blob/devel/packaging/debian/README.md)

**Comment by mpdehaan** [comment]
Sounds like a step is missing here as I would have expected a lot more reports if this were the case, and this content has not changed for a long time.

**Comment by iliv** [comment]
Yes, I am sure. As I said I tried to build 1.4.4 at least twice on two different machines. 1.4.4 release from git builds just fine in the same environment, but not if the code is from tarball.

**Comment by mpdehaan** [comment]
Closing this as these files are long sense replaced and are the official build system artifacts that the distros use, and those same tarballs are used for PyPi.

(No more chance of manual upload)
