### ISSUE TITLE
Support tagging tasks

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#557]
A task should be taggable:

```
action:  foo
tags: a
```

ALSO

```
action: foo
tags: 
    - foo  
    - bar
```

And ansible-playbook should take a "--tags"

So I can do "ansible-playbook --tags ntp" to just run part of my playbooks.

This should be a very easy addition.

The setup tasks should always run, as should any notified handlers, regardless of tag.   It should be an error if a handler has a tag, probably.

For bonus points, it might be nice to be able to shorthand an include:

```
 - include: /path/to/tasks.yml
```

AS

```
- include: 
   file: /path/to/tasks.yml
   tags:
     - foo
     - bar
```

(Tags directly above should also be specifiable as a single string, as further above)

**Comment by davehatton** [comment]
--tags takes multiple tags?

**Comment by mpdehaan** [comment]
yes, this should a optparse multi-thingy

**Comment by mpdehaan** [comment]
might also want to support tagging whole plays too

**Comment by mpdehaan** [comment]
tagging tasks is in, though some sort of syntax to make the includes support tags is pending.

suggested to the list:

```
  - include: "/path/to/foo.yml as tagname"
```

?

**Comment by mpdehaan** [comment]
done, syntax chosen was:

include: /path/to/foo.yml tags=xyz

**Comment by lyra-** [comment]
**The following has no interest**, figured out (thx Joel_re) that include: foo.yaml tags=bar adds the tag bar to all of the tasks in foo when including it. :)

# 

Syntax chosen doesn't seem to work for me :

```
---
- hosts: local
  connection: local
  tasks:
  - include: ./tasks_tags.yml tags=foo
```

used with tasks_tags.yaml :

```
---
- name: foo
  shell: echo 'foo'
  tags: foo
- name: bar
  shell: echo 'bar'
  tags: bar
```

gives me :

```
PLAY [local] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [foo] ******************************************************************* 
changed: [127.0.0.1]

TASK: [bar] ******************************************************************* 
changed: [127.0.0.1]

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=3    changed=2    unreachable=0    failed=0   
```

The task bar shouldn't be run

Also, I found out that tags is recognized as a variable : 
`- include: ./tasks_tags.yml tags="bla"`

used with :

```
---
- name: foo
  shell: echo $tags > test_file
  tags: foo
```

executes the following : `echo "bla" > test_file` (checked by ls + cat).

Any clue ?
