### ISSUE TITLE
slow ssh and ssh_alt (needs info)

### ISSUE THREAD

**Issue by lberruti** [ansible/ansible#5570]
The ssh/ssh_alt transport has become painfully slow, anyone else have this problem? 

Probably with 8cef210 (ssh) and 5c965a7 (ssh_alt)

Some measures (single target host, lan connection, Debian 7.2, OpenSSH_6.0p1):
- devel(ea4bb9f…) ssh 4m27.902s, ssh_alt 3m30.481s
- devel(5c965a7…^) ssh_alt 0m14.641s
- devel(8cef210…) ssh 4m29.508s
- devel(8cef210…^) ssh 0m5.732s

**Comment by mpdehaan** [comment]
Actually no, we haven't heard about this, and would have expected to hear lots if the case.

I'm also a bit confused as your commits don't seem to be ordered chronologically.  The last one shows the exact same commit SHA, and times that are wildly different -- and some report ssh_alt times, and some do not.

Can you please bring this up on the mailing list, this really isn't the forum for user questions, and this will get much more response there.

Thanks!

**Comment by mpdehaan** [comment]
Just saw the linked commit, we can check this out very soon.  Thanks!

**Comment by mpdehaan** [comment]
I think the confusion was I was reading your commit and thinking you were linking a commit in the tree already.

Still interested about this part and what the first SHA was.

devel(8cef210…) ssh 4m29.508s
devel(8cef210…^) ssh 0m5.732s

Thanks!

**Comment by lberruti** [comment]
I'm sorry, I try to explain me better:
- with ansible at 8cef210: my test playbook runs within 4m29.508s (using '-c ssh')
- with ansible before 8cef210 (i.e. 929f8a5): my test playbook runs within 0m5.732s (using '-c ssh')

8cef210 belongs to pull request "Make sure ssh pipes are empty before moving on" that closes #5082

So, I think 8cef210 introduces delay

**Comment by mpdehaan** [comment]
Ok I'm finding it a little hard to believe that things are going from 5s to 4m30 in a general case, may be something environmental on your end.

Let's transfer this over to the mailing list as looking at the patch this would no longer consume extra input and that's definitely not something we want to do and I want to understand more, but we should probably also see if others are experiencing anything weird -- which I would venture they aren't.
