### ISSUE TITLE
Variables defined in defaults not avaible in task name

### ISSUE THREAD

**Issue by dantleech** [ansible/ansible#5574]
With **ansible 1.4.3**

If I define the following:

```
# /roles/foobar/defaults/main.yml
foobar: foo
```

and have a task:

```
# roles/foobar/tasks/main.yml
- name: This is {{ foobar }}
```

The output is:

```
TASK: [... | This is {{foobar}}]
```

If I put the variables in `roles/foobar/vars` then it works as expected.

**Comment by mpdehaan** [comment]
This is normal because inventory scoped variables, as defaults are, will be different between hosts.

The results of this is that we can't show the variable in the task header because there could be 500 different values.

This is not actually a bug.
