### ISSUE TITLE
provide template ansible directory layout

### ISSUE THREAD

**Issue by dch** [ansible/ansible#5578]
The directory layout for ansible takes a while to get used to, even with the excellent [guide](http://docs.ansible.com/playbooks_best_practices.html#directory-layout) now available.

Perhaps ansible (or playbook) could be extended to create the best practices layout within a specified new directory. It may be that this functionality could be used by others to provide similar template functions for their own playbooks or organisations.

I'd guess something like this `ansible --new-project acme/projects/foo` would create a new `acme/projects/foo` dir and a layout matching http://docs.ansible.com/playbooks_best_practices.html#directory-layout :

```
foo
└── inventory
├── group_vars/
│   ├── group1
│   └── group2
└── host_vars/
    └── host1
...
```

An option to specify custom layout with  `--template acme` would be double-plus-good cake.

**Comment by mpdehaan** [comment]
The ansible-galaxy CLI already does this for creating new roles.

If you have further questions please stop by the mailing list.
