### ISSUE TITLE
ec2: Why parameter "key_name" is mandatory required?

### ISSUE THREAD

**Issue by AlexLov** [ansible/ansible#5579]
Subj.
As I can see in code, this module uses boto function run_instance(), and in this function parameter "key_name" is not required for creating new instance.

In my case, I already have my own ami with pre-configured ssh key inside it and I don't want change it or add new one when launching new instance.

Maybe parameter "key_name" in module ec2 should be optional? Or how I can avoid this requirements?

**Comment by mpdehaan** [comment]
questions should be posted to the mailing list, not the bug tracker.
