### ISSUE TITLE
assemble module should boolean-ify remote_src input

### ISSUE THREAD

**Issue by r0bj** [ansible/ansible#5581]
I'm not sure if this issue from mailing list was reported here so I created new ticket.
https://groups.google.com/forum/#!msg/ansible-project/5i2nARmcMWA/iK-NB4LI2ZgJ

I haven't been able to assemble a file on a host from fragments on the Ansible server. 
It fails with "msg: Source (/etc/ansible/roles/test/files/fragments/) does not exist".

If I create and populate that path in the destination host, the file is assembled from those files.

That is, remote_src seems to be ignored.

$ ansible --version
ansible 1.4.3

``` ---
# /etc/ansible/test.yml
- hosts: test
  sudo: yes
  roles:
    - test

---
# /etc/ansible/roles/test/tasks/main.yml
- name: Assemble files from Ansible server on remote host
  assemble: >
    dest=/tmp/assembled.file
    remote_src=False
    src=/etc/ansible/roles/test/files/fragments/
```

```
# /etc/ansible/roles/test/files/fragments/one
First Fragment

# /etc/ansible/roles/test/files/fragments/two
Second Fragment
```

Changing 'src' to 'roles/test/files/fragments/', 'files/fragments/', or removing the trailing slash, have no effect.

**Comment by mpdehaan** [comment]
My reply on the mailing list:

This email sounds like it's really "assemble module not working with remote_src=False".

Looking at the problem, it appears the code was written to not boolean-ify the input arguments, which is definitely a bug.   Please file a ticket if you don't mind.

```
    remote_src = options.get('remote_src', True)
```

It appears from looking at things, this may work for you:

```
- assemble:
     src: blah
    dest: blah
     remote_src: False
```

Which prevents sending string arguments to the code.    The fix is to boolean-ify the string, which we have some utility functions for.

editing description of ticket to match

**Comment by Ernest0x** [comment]
> The fix is to boolean-ify the string, which we have some utility functions for.

This seems not to be enough. I added the line:

```
remote_src = utils.boolean(remote_src)
```

And now I get ther error:

```
unsupported parameter for module: remote_src
```

**Comment by bcoca** [comment]
the module has:

remote_src=dict(default=False, type='bool'),

which should already take care of that.

**Comment by Ernest0x** [comment]
I would agree, but, without that line, the initial error was:

```
Source (/some/path) does not exist
```

Of course `/some/path` does exist locally.

Besides, I would expect that the line I added would be innocent enough to not produce an `unsupported parameter for module: remote_src` error. But it is not.

I' m trying with last git commit  36250c6b86 and I added the line at file: /lib/ansible/runner/action_plugins/assemble.py

**Comment by muffl0n** [comment]
Is this still unfixed in upcoming releases? I'm experiencing the same behaviour with 1.4.5.

**Comment by Ernest0x** [comment]
> Is this still unfixed in upcoming releases? I'm experiencing the same behaviour with 1.4.5.

If you ask whether it will be fixed in an upcoming release, then, yes, since it is a bug, it should be fixed in an upcoming release. Meanwhile, you could workaround this with three tasks like this:

```
- name: Create combined file in /tmp on local host
  shell: /bin/cat /path/to/file/parts/to/assemble/* > /tmp/combined_file
  delegate_to: localhost

- name: Copy combined file to remote host
  copy: src=/tmp/combined_file dest=/path/on/remote/host/combined_file

- name: Remove combined file in /tmp on local host
  file: path=/tmp/combined_file state=absent
  delegate_to: localhost
```

And guess what, your remote task is still idempotent!
