### ISSUE TITLE
some logical expressions are evaluated incorrectly (edited)

### ISSUE THREAD

**Issue by obormot** [ansible/ansible#5584]
Ansible v1.4.4

It looks like a bug to me: in one case, the expression is evaluated to True, in another case to False. The only thing different is the order.

Playbook:

```
- hosts: test
  tasks:
  - set_fact: this_is_false="{{ 0 | bool}}"   # tried different ways here

  - shell: echo 'foo'
    register: echo_out

  - debug: var=this_is_false

  - debug: var=echo_out.changed

  - debug: var="echo_out.changed or this_is_false"

  - debug: var="this_is_false or echo_out.changed"
```

Output:

```
TASK: [set_fact this_is_false="False"] *************************
ok: [127.0.0.1]

TASK: [shell echo 'foo'] ***************************************
changed: [127.0.0.1]

TASK: [debug var=this_is_false] ********************************
ok: [127.0.0.1] => {
    "this_is_false": "False"
}

TASK: [debug var=echo_out.changed] *****************************
ok: [127.0.0.1] => {
    "echo_out.changed": "True"
}

TASK: [debug var="echo_out.changed or this_is_false"] **********
ok: [127.0.0.1] => {
    "echo_out.changed or this_is_false": "True"   <<<<< True here
}

TASK: [debug var="this_is_false or echo_out.changed"] **********
ok: [127.0.0.1] => {
    "this_is_false or echo_out.changed": "False"    <<<<< False here 
}
```

**Comment by mpdehaan** [comment]
While this initially looks curious, this is an undocumented and unsupported usage of debug "var=".  It's meant to print variables not expressions.

If anything what is to be done here is to yell that the input expression is not a variable and raise an error.

**Comment by obormot** [comment]
Use of debug: var was just an example; I initially faced this behavior using the evaluation in a conditional expression (when:)

**Comment by obormot** [comment]
I don't believe this has been correctly assessed, @mpdehaan 
Here is another example to demonstrate broken logical evaluations, this time using conditional instead of debug var.

Playbook:

```
tasks:
- set_fact: false_fact="{{ 0 | bool}}"

- debug: msg="0 or 0 - I must be skipped but I'm not"
  when: "false_fact or false_fact"

- debug: msg="0 or 0 - Rightfully skipped in this variation"
  when: "{{ false_fact or false_fact }}"
```

Output:

```
TASK: [set_fact false_fact="False"] *******************************************
ok: [127.0.0.1]

TASK: [debug msg="0 or 0 - I must be skipped but I'm not"] ********************
ok: [127.0.0.1] => {
    "msg": "0 or 0 - I must be skipped but I'm not"
}

TASK: [debug msg="0 or 0 - Rightfully skipped in this variation"] *************
skipping: [127.0.0.1]
```

**Comment by bcoca** [comment]
On Wed, Jan 15, 2014 at 12:04 AM, Oscar notifications@github.com wrote:

> when: "{{ false_fact or false_fact }}"

This is telling jinja to return a string, as much as you want a boolean
evaluation inside, you are returning a string

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by obormot** [comment]
The real question is why condition 1 executes when its condition is "false or false".
Well I guess when I change it to

```
when: (false_fact or false_fact) == true
```

then it's getting skipped..   seems rightfully so,
BUT if I try to use the same construct and both facts are True, i.e.

```
- set_fact: true_fact="{{ 1 | bool}}"
```

then this ALSO gets skipped (i.e. evaluates to False), while it shouldn't

```
- debug: msg="1 or 1"
  when: "(true_fact or true_fact) == true"
```

**Comment by mpdehaan** [comment]
This is more of a case of set_fact needing some more intelligence.

When you are doing key={{ some_expression }}

regardless of type, because you are doing that in string context it's going to give you a string.

The solution here is to make set_fact not take key/value arguments in this case, which warrants a seperate ticket to disambiguate that conditional are working fine, as they are.

I'll open one.

Thanks!
