### ISSUE TITLE
requerimientos 

### ISSUE THREAD

**Issue by luisAngelPerezCastillo** [ansible/ansible#55866]
##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by mkrizek** [comment]
Please create a new issue with a proper information about a bug/feature.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
