### ISSUE TITLE
ansible.cache missing from setup.py

### ISSUE THREAD

**Issue by haskjold** [ansible/ansible#5600]
Please add ansible.cache to packages list in setup.py

Current devel version gives import error because this is missing.

**Comment by mpdehaan** [comment]
Actually we reverted this a while back, if you update again you shouldn't see any references to this.

**Comment by srgvg** [comment]
There are still plenty of references to ansible.cache as of 57a6672:

```
[dvl] serge@goldorak:~/ansible$ grep ansible.cache lib/ansible/ -r
lib/ansible/playbook/__init__.py:import ansible.cache
lib/ansible/playbook/__init__.py:   SETUP_CACHE = ansible.cache.FactCache()
lib/ansible/utils/plugins.py:    'ansible.cache',
lib/ansible/runner/__init__.py:from ansible.cache import FactCache
lib/ansible/runner/__init__.py:            self.setup_cache = ansible.cache.FactCache()
```

I opened a new ticket #5611
