### ISSUE TITLE
Pip module raises NameError: global name 'virtualenv' is not defined when using extra_args

### ISSUE THREAD

**Issue by robmadole** [ansible/ansible#5601]
I have confirmed this issue on version 1.4.4. It previously worked on 1.4.3.

The following example task:

```
- name: Install the web app in development mode
  pip: executable=pip-3.3 name=/path/to/code extra_args='-e'
```

Raises the following error:

```
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-1389641998.4-98108193785888/pip", line 1381, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-1389641998.4-98108193785888/pip", line 325, in main
    cmd_opts = _get_cmd_options(module, cmd)
  File "/home/vagrant/.ansible/tmp/ansible-1389641998.4-98108193785888/pip", line 152, in _get_cmd_options
    module.fail_json(msg="Could not get --help output from %s" % virtualenv)
NameError: global name 'virtualenv' is not defined
```

I believe the root problem is that `_get_cmd_options` [function](https://github.com/ansible/ansible/blob/45dde5b3e221e785d64c7b750ea1ec985d17caf9/library/packaging/pip#L147) is being called with a `cmd` argument of `pip3.3 -e`. This results in the value of `thiscmd` being `pip3.3 -e --help` when ran (on line 149) which fails.

The `-e` gets thrown onto the `cmd` on [this line](https://github.com/ansible/ansible/blob/45dde5b3e221e785d64c7b750ea1ec985d17caf9/library/packaging/pip#L291).

**Comment by robmadole** [comment]
I believe this may be relevant to #4601.

**Comment by jctanner** [comment]
@robmadole the patch above was tested with the following playbook:

```
- hosts: el6.lab.net
  gather_facts: False
  tasks:
    - pip: name=bottle extra_args='-v'
    - pip: name='git+git@github.com:succhiello/ansible-playbook-wrapper.git#egg=ansible-playbook-wrapper' extra_args='-e'
```

**Comment by robmadole** [comment]
Perfect, thanks @jctanner!
