### ISSUE TITLE
Violation of lazy evaluation of 'or' in 'when' clause

### ISSUE THREAD

**Issue by amarao** [ansible/ansible#56017]
##### SUMMARY
When there is a conditional in `when` clause with 'or' in it, ansible evaluate all statement. (See example below).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible itself.

##### ANSIBLE VERSION
```paste below
ansible 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/amarao/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
```

##### CONFIGURATION
```paste below
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o Control
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /tmp/%%h-%%r
DEFAULT_SUDO_FLAGS(/etc/ansible/ansible.cfg) = -H -S
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 15
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT
Ubuntu 19.04

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: false
  tasks:
   - debug:
     when: foo or bar
     vars:
       foo: true
       bar: "{{ [][1] }}"
```

##### EXPECTED RESULTS
"hello world" in output.

##### ACTUAL RESULTS

```paste below
TASK [debug] *******************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'foo or bar' failed. The error was: error while evaluating conditional (foo or bar): list object has no element 1\n\nThe error appears to have been in '/tmp/a1/play.yaml': line 5, column 6, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n   - debug:\n     ^ here\n"}
```
P.S. Normally, python performs evaluation of 'or' clause in lazy way:

```
>>> a=[]
>>> a[1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
>>> True or a[1]
True
```
The same behaviour is expected from Ansible, as it was promised that jinja2 variables are evaluated lazily.

P.P.S. The key scenario where this bites a lot is with analysis of 'register' of 'command' module output. It's common to say `when: reg.rc!=0 or reg.stdout_lines[2]=="foo"`. Normally, if rc is not zero, second part should not be evaluated. This example from above showing how it does otherwise.

**Comment by joel-schaal** [comment]
I have investigated a little the code base but got lost in `template/__init__.py`:
```python
831             jvars = AnsibleJ2Vars(self, t.globals)
832
833             self.cur_context = new_context = t.new_context(jvars, shared=True)
834             rf = t.root_render_func(new_context)
835
836             try:
837                 res = j2_concat(rf)
838                 if getattr(new_context, 'unsafe', False):
839                     res = wrap_var(res)
840             except TypeError as te:
841                 if 'AnsibleUndefined' in to_native(te):
842                     errmsg = "Unable to look up a name or access an attribute in template string (%s).\n" % to_native(data)
843                     errmsg += "Make sure your variable name does not contain invalid characters like '-': %s" % to_native(te)
844                     raise AnsibleUndefinedVariable(errmsg)
845                 else:
846                     display.debug("failing because of a type error, template data is: %s" % to_text(data))
847                     raise AnsibleError("Unexpected templating type error occurred on (%s): %s" % (to_native(data), to_native(te)))
848
```

On my tests, the Undefined exception comes from the line `res = j2_concat(rf)`. 
From what I gathered, `USE_JINJA2_NATIVE` is `False`  and I use `from jinja2.utils import concat as j2_concat`.

Not sure if this can help, I'm lacking some Python debugging skills to go further...

**Comment by bcoca** [comment]
There is a difference between Ansible's lazy evaluation of variables and Jinja2 expression evaluation (non lazy).

It means that Ansible won't force the evaluation of `bar` until it is used in an expression, it does not mean `bar` won't be evaluated when used in an expression in  a 'branch' that could logically end execution before needing the variable.  

In this case `bar` is being used in the expression, so it is evaluated, the 'concat' code that @joel-schaal narrowed it down to is the part that 'adds' all the different tokens in the expression having been evaluated (variables foo, bar , so then we can proceed with the 'logical or').

**Comment by bcoca** [comment]
in any case, we have a WIP #56116 that can implement this feature
