### ISSUE TITLE
Debug documentation

### ISSUE THREAD

**Issue by stormfleet** [ansible/ansible#56027]
##### SUMMARY
Hi everyone, first post to Github, woohoo!

Having an issue with writing some Ansible playbooks for deploying to Linode and Vultr. I've got a nice one fully working for Digital ocean, with the following site.yml file:

`    - name: create the droplet used to build releases
      digital_ocean:
        state: present
        command:
        name:
        api_token: 
        size_id:                               
        region_id:
        image_id:
        wait_timeout: 500
        ssh_key_ids: "{{ blah blah }}"
        unique_name: yes
      register: new_droplet`

Once this part of the playbook is executed, the debug message immediately following it is the following:

`- debug:
    msg: "IP address is {{ new_droplet.droplet.ip_address }}"`

Which nicely returns the IP address and prints it as part of the playbook's output to the command line. I didn't find this function myself, I found it as part of an existing repo, but I'm curious as to where the construction of the `droplet.ip_address` comes from? I can't seem to find any documentation on this, either for Digital Ocean - thankfully I don't need it since the script works

##### ISSUE TYPE
Is there a list somewhere online, detailing the Linode and Vultr equivalent of Digital Ocean's `droplet.ip_address` variables returned from the server? I can't seem to find any documentation either on the docs or in any other repos.

Hopefully that's enough information, I figured this isn't an operating system or playbook related issue so it doesn't require any additional information? Apologies if not!

**Comment by mkrizek** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
