### ISSUE TITLE
Host file 

### ISSUE THREAD

**Issue by JohnMahady** [ansible/ansible#56112]
Can i do this in my hosts/inventory file? Also, can i pass a host group in command line -e?

[env1]
vm1 ansible_host=vm001
vm2 ansible_host=vm002

[env2]
vm1 ansible_host=vm888
vm2 ansible_host=vm999

I want to use the same synonym host name in my playbook (vm1 or vm2 ) but point to different virtual machine depending on what group i specify in the yml file. (hosts: env1)
This way i can make the code generic across groups with the same vm1 or vm2. I have duplicate VMs for testing and development.

thanks

**Comment by mkrizek** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
