### ISSUE TITLE
zypper_repository doesn't support check mode

### ISSUE THREAD

**Issue by yhekma** [ansible/ansible#5614]
When modifying things with the zypper_repository module, even when "--check" is specified on the command line, it still performs the action.
For example when I do:

ansible host1 -m zypper_repository -a '"name=SUSE*" repo="cd:///?devices=/dev/sr0" state=absent' -KC

I would not expect ansible to remove the repository.

**Comment by resmo** [comment]
https://github.com/ansible/ansible/blob/devel/library/packaging/zypper_repository#L123

yep, this is a bug.

`supports_check_mode=True`, but I don't see any conditional statement for check_mode. So  the fix would be changing into:

`supports_check_mode=False`

do you like to do the fix? should I do the fix?

**Comment by mpdehaan** [comment]
Closing since we have the PR above, thanks!

**Comment by mpdehaan** [comment]
Oh I see you haven't submitted it, yes, please!

**Comment by mpdehaan** [comment]
Merged the above, thanks!
