### ISSUE TITLE
complex clauses in hosts line

### ISSUE THREAD

**Issue by timurb** [ansible/ansible#5619]
It would be nice if we could specify some complex statements in hosts line.
For example:

```

---
- hosts: not webservers
  ........
```

The "NOT" operation looks like the most important for me atm but more complex statements should be nice to have too.

**Comment by mpdehaan** [comment]
you already can do this.

hosts: webservers:!otherservers

etc

If you have more questions please stop by the mailing list and also see the documentation section on patterns.

http://docs.ansible.com/intro_patterns.html

Thanks!

**Comment by timurb** [comment]
Thanks for pointing that out!

I've searched for that several times but I could not find references to this so I assumed it is not possible.
I think I've looked in in "Playbooks" chapter and have taken a look to "Inventory" chapter but could not find references to this.
I see now that there are several references throughout the docs to "Patterns" chapter but you are likely to miss them if you've already read through the docs and occasionally consult it later.

Probably the chapter should have more explicit name like "Host patterns", what do you think?
