### ISSUE TITLE
ansible-playbook gives return code of zero on failure

### ISSUE THREAD

**Issue by bagheera** [ansible/ansible#562]
echo $? gives 0

**Comment by mpdehaan** [comment]
yeah, it's a known thing.   No one has been willing to do the work to fix it so far.   If you want to you, you can, though it could also be argued that it does return 1 on playbook crashes, but individual host failure is not a failure condition.   I could go either way.

**Comment by kurtismgit** [comment]
I expected no zero return code as well ;(

I need to create a script that calls a series of playbooks with different inventory files that are generated dynamically.  And I want to stop the series if any task fail along the way.  Any suggestions are welcomed.

**Comment by ocervell** [comment]
Still an issue now with Ansible 2.5.0.
**Common use case**: running `ansible-playbook` from a CI build, the build status is always based on the return value of `ansible-playbook`, and so never fails when one of the tasks fails.
Please reopen.

**Comment by weiming-hyperanna** [comment]
+1 for reopen

**Comment by willthames** [comment]
@ocervell: ansible-playbook does exit with non-zero status in a normal run.

However, if you use `always` or `rescue` to clean up after failure, it will exit with return code 0.

I'd say that's not necessarily a bug, but it is worth raising as a separate issue distinct from this one - it's actually quite difficult to get the behaviour correct for all use cases (sometimes you want rescue for an expected issue that you just want to ignore)
