### ISSUE TITLE
Bastian Jump Host integration into playbooks/vars/inventory - core feature 

### ISSUE THREAD

**Issue by rtulke** [ansible/ansible#56210]
##### SUMMARY

It would be absolutely useful if we could directly assign an ansible proxy command variable to any ansible src host. I work in an environment with up to 15K hosts and we have more then 100 jumphosts. 

It is very complicated if you have to make a SSH proxy entry for every x host and then have to distribute it to everyone every time you change it. Because the SSH config is not exactly the same for everyone, you always have to merge the local private ssh config with the one where the host is defined.

One possibility would be a kind of auto-discovering but also this is expensive and not nice.

A simple possibility would be to specify the bastian/jump host directly in the inventory as variable via which Ansible should connect.

Another possibility would be if Ansible could test a host with existing Jumphosts through. 
For example, you could define a list of existing jumphosts in your configuration (ansible.cfg) but you would not need a direct order to the host but Ansible will automatically find the correct jumphost. 

For both solutions it would be easier to just distribute this one file either ansible.cfg - with more magic or a little practice near - each host gets assigned a jumphost when it needs one.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
core

**Comment by bcoca** [comment]
https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-configure-a-jump-host-to-access-servers-that-i-have-no-direct-access-to

**Comment by samdoran** [comment]
Closing per above documentation link. `ansible_ssh_common_args` can be set at a host or group var.
