### ISSUE TITLE
Task's tags with variables. Undefined variable in scope of playbook's roles.

### ISSUE THREAD

**Issue by theg4sh** [ansible/ansible#56231]
##### SUMMARY

Too pure error message when variable used in one of tag. Probably, if it is expected that tag could contain a variable then there is an wrong order of expanding variables.

##### ISSUE TYPE
- Bug Report
- Feature Request

##### ANSIBLE VERSION

```paste below
ansible 2.7.8
  config file = /home/user/repos/ansible-test/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
DEFAULT_HASH_BEHAVIOUR(/home/user/repos/ansible-test/ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/user/repos/ansible-test/ansible.cfg) = ['/home/user/repos/ansible-test/hosts/all.yaml']
```

##### OS / ENVIRONMENT

Ubuntu 16.04

##### STEPS TO REPRODUCE

Here is an example of galaxy:
https://gist.github.com/theg4sh/fcb43ce57adfce1cccd1270ed57c4eaa
Run one of playbooks.

If uncomment `roleA_tag` in one of playbook, then task will finished without error.

##### EXPECTED RESULTS

Customizable tag value or warning on invalid tag's name.

##### ACTUAL RESULTS

```
ERROR! 'roleA_tag' is undefined
```
`roleA_tag` could be also declared in `roleA/defaults/main.yaml`, but it will not override with value from `host_vars` while filtering by tag.

**Comment by jillr** [comment]
Hi!

Thanks very much for your submission to Ansible.  It means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:
When the variable is undefined, there should be a different error message.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
