### ISSUE TITLE
RFE: have a 'version=' attribute on the apt module

### ISSUE THREAD

**Issue by msolo** [ansible/ansible#5625]
If you have this:
-  apt: pkg=lxc-docker=0.7.2 state=present

And the target has no version of lxc-docker already installed, you get a crash on an unknown attribute.

Here is the fix:

```
diff --git a/third-party/ansible/library/packaging/apt b/third-party/ansible/library/packaging/apt
--- a/third-party/ansible/library/packaging/apt
+++ b/third-party/ansible/library/packaging/apt
@@ -191,7 +191,7 @@
             # assume older version of python-apt is installed
             package_is_installed = pkg.isInstalled

-    if version:
+    if version and package_is_installed:
         try:
             installed_version = pkg.installed.version
         except AttributeError:
```

**Comment by resmo** [comment]
do you make a pull request of this fix?

**Comment by mpdehaan** [comment]
Basically this is really (should be) a feature request for the module to support pkg=version style semantics like yum, where it does not already now.   The existing version logic in the apt module is not how we want to continue.

Currently we support this in yum by having a package specifier in the name attribute, but what I'd really like to see is a version parameter that supports "version=" but also "version=1.2" or "version='>1.2'" etc on both modules, and continuing to support what we do with yum for backwards compat.

**Comment by msolo** [comment]
I didn't expect this to be a feature request since the documentation and
examples linked seem to suggest this functionality should exist:

http://docs.ansible.com/apt_module.html

I will say from experience that it is not smooth, but I couldn't tell if
that was due the way the docker folks have their apt repository set up.

Irrespective of that, I think this one-liner is just a bug.

**Comment by nightshade427** [comment]
having same issue here

**Comment by nightshade427** [comment]
the above patch fixed my issue, it installed package fine and also skipped if it was already installed.
