### ISSUE TITLE
RFE: rsync module should take arbitrary options

### ISSUE THREAD

**Issue by cespare** [ansible/ansible#5627]
`--copy-dest` is a really great rsync option that lets rsync use an existing directory on the remote machine to copy any unchanged files. We've found it invaluable for deployments -- instead of copying everything over the wire, you just need to copy the changed bits. In most of our use cases it's a massive speedup.

To quote the man page:

> This option behaves like --compare-dest, but rsync will also copy unchanged files found in DIR to the destination directory using a local copy.  This is useful for doing transfers to a new destination while leaving existing files intact, and then doing a flash-cutover when all files have been successfully transferred.

We have our own rsync task that we use but we'd love to switch to the official synchronize module. For our task, we set copy-dest to be equal to dest if the user doesn't provide it (often a good guess) -- I'm not sure if you'd want to adopt that behavior or not.

**Comment by mpdehaan** [comment]
I disagree that there should be a flag for copy==dest, but that there should be a flag to pass arbitrary options in.

Of course the easy workaround for now is to just do:

local_action: rsync ...

and then you can pass along any flags you want.

I'm updating the defect title to match the above concept.

**Comment by mpdehaan** [comment]
I'm suggesting "rsync_options='--foo --bar'"

etc

**Comment by jctanner** [comment]
Resolved by https://github.com/ansible/ansible/pull/6702
