### ISSUE TITLE
modprobe module uses env python2 as shebang

### ISSUE THREAD

**Issue by landryb** [ansible/ansible#5630]
Trying to use ansible modprobe module against a lenny server (which doesnt have /usr/bin/python2), it fails

```
invalid output was: 
SUDO-SUCCESS-jhgpqdduehxojitucpzwidbbsxquwtcs
/usr/bin/env: python2: Aucun fichier ou répertoire de ce type
```

modprobe's shebang looks inconsistent with the rest of the modules..

after a quick grep, seems it's also the case for packaging/rpm_key & net_infrastructure/openvswitch_{port,bridge}

**Comment by mpdehaan** [comment]
Yep, it should be /usr/bin/python so the ansible_python_interpreter stuff works as expected.

I'll make the appropriate changes.

**Comment by mpdehaan** [comment]
Done, thanks!
