### ISSUE TITLE
[FR] Option to ignore LV size mismatch for lvol module

### ISSUE THREAD

**Issue by evgkrsk** [ansible/ansible#5642]
It would be great if we can command to lvol module that it must skip LV re-creation, if it already exists but doesn't match in size.

It is common case that human creates bigger or smaller LV according to some in-place limitations.

**Comment by mpdehaan** [comment]
Sounds fine with me, is this something you would like to work on?

**Comment by evgkrsk** [comment]
Maybe, later.

**Comment by mpdehaan** [comment]
I'm going to close this one as I haven't seen any updates on this ticket, but wanted to indicate we are still open to pull requests here if you want to submit something.

Thanks!
