### ISSUE TITLE
feature request: improve apt module pkg version

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#5644]
issue GH-5625

@mpdehaan wrote:
Basically this is really (should be) a feature request for the module to support pkg=version style semantics like yum, where it does not already now. The existing version logic in the apt module is not how we want to continue.

Currently we support this in yum by having a package specifier in the name attribute, but what I'd really like to see is a version parameter that supports "version=" but also "version=1.2" or "version='>1.2'" etc on both modules, and continuing to support what we do with yum for backwards compat.

**Comment by mpdehaan** [comment]
Yeah so ther other ticket has been repurposed so I'm going to close this one as it just references the other.

Thank you!
