### ISSUE TITLE
EC2 inventory script: AuthFailure

### ISSUE THREAD

**Issue by dbrgn** [ansible/ansible#5647]
I'm using the current devel version of `ec2.py` and boto 2.23.0.

I exported `AWS_ACCESS_KEY_ID`, `AWS_ACCESS_KEY`, `AWS_SECRET_ACCESS_KEY` and `AWS_SECRET_KEY`.

The credentials are correct, they work when using ansible directly (e.g. to spin up new instances), but when calling the ec2.py script, it fails:

```
$ python ec2.py --list
Looks like AWS is down again:
EC2ResponseError: 401 Unauthorized
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>48dcaa19-91b6-475f-a7ed-0a1aadca6e41</RequestID></Response>
```

Any idea what the cause could be?

**Comment by mpdehaan** [comment]
Please stop by the mailing list for user questions.

Thanks!
