### ISSUE TITLE
Self-documenting tags

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#5648]
It would be nice to have self-documenting tags. What I imagine it would be something like this:

$> ansible-playbook playbook.yml -t show

possible values: tag1,tag2,tag3

$> ansible-playbook playbook.yml -t tag1 show

included plays: play1,play2,play3

$> ansible-playbook playbook.yml -t tag1

[actually runs the tag]

The idea would be to have an extra argument for the tags so that I can know which tags are available without having to read the playbook and the same or even another extra argument that will show which plays are included. Something like the --check, but just informative.

I thought about it because I always end up wrapping everything on a script so that whoever runs the playbook has some aid as to what the execution will do without needing to read the playbook.

If you think is something that you would like to have, I can definitely sit on it and try to come up with a patch for it.

**Comment by mpdehaan** [comment]
So there's already "--list-tasks" for this purpose that respons to tags.

We are definitely not going to have a magic tag called "show".

It may be reasonable to have a "--list-tags" though right now if you pass an invalid tag it will offer suggestions, you could file a RFE for this, so I'm going to close this ticket, if you would like to submit that for tracking purposes that would be fine.
