### ISSUE TITLE
Store  ssh passphrase for  another session

### ISSUE THREAD

**Issue by sveemani** [ansible/ansible#56493]
##### SUMMARY
Store  ssh passphrase for  another session.
I have a set of ansible client servers  accessible from ansible engine using ssh-key and passphrase.
When I  run a ansible ad-hoc  command , I have to enter passphase on each servers connections and this is repeating for all the tasks.

However from github search , find a way to reduce the enter the passphrase only one time  by using the  ssh-agent `"eval "$(ssh-agent -s)" ; ssh-add ~/.ssh/id_rsa" ` and by entering passphrase once .
When I exit the shell and re-login the I have to re-run and  enter the  commands and passphrase again . 

How can I avoid this ?  Is there a way  to store the passphrase  as like in ansible-vault and use it for login? 

##### ISSUE TYPE
-  Feature availability

##### ANSIBLE VERSION
2.7.8

##### OS / ENVIRONMENT
CENTOS 7

##### STEPS TO REPRODUCE
Passphrase have to be entered for each clients.
```
ansible]$  ansible client1,client2   -m command -a "uptime"
Enter passphrase for key '/home/veeru/.ssh/id_rsa': client2 | CHANGED | rc=0 >>
 17:00:51 up 53 days,  9:48,  1 user,  load average: 0.08, 0.04, 0.00


Enter passphrase for key '/home/veeru/.ssh/id_rsa':
client1 | CHANGED | rc=0 >>
 17:01:15 up 14 days,  1:22,  1 user,  load average: 0.00, 0.01, 0.00

```
##### EXPECTED RESULTS
No passphrase to be prompted for ansible play  , even on another sessions   by using a stored passphrase.

**Comment by samdoran** [comment]
We have no plans to implement this feature at this time.

To discuss this further, please reach out on IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by dangerousness** [comment]
Add this to your bash_profile:

`# Configure ssh-agent (begin)
SSH_ENV="$HOME/.ssh/environment"
function start_agent {
    echo "Initializing new SSH agent..."
    /usr/bin/ssh-agent |sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    /usr/bin/ssh-add ~/.ssh/$(whoami);
}

# Source SSH settings, if required
if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    ps -ef |grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
      start_agent;
  }
else
    start_agent;
fi
# Configure ssh-agent (end)`

Cheers,
Dangerousness
