### ISSUE TITLE
[Docs] Update network platform options page to include more platforms

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#56589]
##### SUMMARY

The existing Network platform options page doesn't include a number of newer platforms. Update the table with the network platforms and add sections for platform examples where available.
https://docs.ansible.com/ansible/latest/network/user_guide/platform_index.html

Also add a section to the Network developer guide to explain to developers how/where to update this platform options page when adding new platforms and/or changing which connection options are supported (network_cli, httpapi, etc).

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

**Comment by abenokraitis** [comment]
Request that we add:

- Cisco ACI
- Cisco NSO
- Cisco UCS
- Cisco AireOS
- Cisco Meraki
- Aruba
- Checkpoint
- Fortimanager
- Fortios
- FRR
-

**Comment by kbreit** [comment]
I like the list from @abenokraitis. Adding Cisco Firepower into the mix though.

**Comment by samccann** [comment]
This page describes how to create the network platform options pages - https://docs.ansible.com/ansible/devel/network/dev_guide/documenting_modules_network.html#documenting-modules-network

**Comment by samccann** [comment]
@dagwieers can you create network platform options documentation for Cisco ACI?

**Comment by ryanmerolle** [comment]
Many of these platforms are supported by 2.8.  Is there anyway we can move this to be set for affects_2.8?

**Comment by samccann** [comment]
Added the label @ryanmerolle. Thanks!
