### ISSUE TITLE
unarchive module fails on FreeBSD hosts

### ISSUE THREAD

**Issue by ryanschulze** [ansible/ansible#5659]
Ansible version 1.4.3

```
- name: upload and extract file
  unarchive: src=foobar.tar.gz dest=/usr/local/src/
```

Works on Linux servers, but fails on FreeBSD servers with the error "dest must be an existing dir" (yes, the directory exists). 

Unfortunately I have no experience with python, but as far as I can tell the root problem is that the _remote _md5() function is returning a md5 back to the unarchive module (because "/sbin/md5 <directory>" on FreeBSD will give you a md5 for directories).

Unfortunately I have no good suggestion for a solution. The best thing I can think of offhand is a dirty workaround to skip /sbin/md5 if it is a directory on FreeBSD, no idea how this would affect other modules though.

```
( [ ! -d %s ] && /sbin/md5 -q %s 2>/dev/null)
```

**Comment by bcoca** [comment]
There is a common md5 function that works with *BSDs that other modules use
(file,copy,etc) so this should be easy to fix.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by bcoca** [comment]
Sorry, I misunderstood the issue. The _remote_md5 functions is already used
and it has it's own test to figure out the type:

"rc=0; [ -r \"%s\" ] || rc=2; [ -f \"%s\" ] || rc=1; [ -d \"%s\" ] && rc=3"

^ %s gets subsituted with the path

unarchive tests for != 3 to return   "dest must be an existing dir".

This should work on FreeBSD and would not depend on the output of the md5
command (unless I'm reading the code incorrectly).

**Comment by ryanschulze** [comment]
the "3" is initially correctly set, but get's overwritten because /sbin/md5 on FreeBSD returns true (and prints a md5sum) for directories and the both are connected via || 

Other Linux/*NIX flavors return false and no md5sum for directories.

**Comment by bcoca** [comment]
so AC (After Coffee) and reading more code, it seems that your initial
assessment was on the nose.

The rc var i mentioned in previous posts, only gets returned when md5
fails, directories do so on linux, but not on BSDs. For once this is not a
POSIX ambiguity as the standard says nothing about md5 command line
utilities, so just different programs/implementations.

BTW, this bug also affects the copy module in specific cases (content=).

I can probably submit a patch this weekend that solves this.

**Comment by ryanschulze** [comment]
Thanks, that's awesome :-)

**Comment by bcoca** [comment]
I looked at the original _remote_md5 function and it basically tries to
behave like a cheap stat when md5 fails (which it does on dirs for linux
but not bsd). The change here should not be too hard except it affects
copy,assemble, fetch and template modules, some of which rely heavily on
this 'feature'.

My thoughts are that it should always return 2 values, the dir/file
indicator and the md5 hash (which can be empty). This will require a lot of
testing as it seem the different md5 tools have much different outputs and
parsing it all might get challenging (also i don't have all possible OSs
setup to test with).

**Comment by mpdehaan** [comment]
Should be fixed per the abov,e let me know if you disagree (reopening would be fine).

Thanks!
