### ISSUE TITLE
COPY with sudo fail with file rights 750

### ISSUE THREAD

**Issue by dlucille** [ansible/ansible#56730]
##### SUMMARY

I am connected with user "user1"
"user1" is a sudoer
I have a file "foo.txt" with followings rights: 
`-rwxr-x---  1 user2 user2    0 mai   21 16:37 foo.txt`
user1 can not read foo.txt

I am trying to execute a COPY with a become_user=user2
the execution fails with a read-only error

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user1/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

```

##### CONFIGURATION

```


```

##### OS / ENVIRONMENT

VM Xubuntu (on oracle virtualbox)

##### STEPS TO REPRODUCE

my playbook is 
```
- hosts: localhost
  become: yes
  become_user: "user2"
  become_method: sudo
  tasks:
    - name: copie du fichier
      copy:
        src: "/tmp/foo.txt"
        dest: "/tmp/bar.txt"
        mode: 0750
```

when i run the playbook i get the following error:
`fatal: [localhost]: FAILED! => {"msg": "an error occurred while trying to read the file '/tmp/foo.txt': [Errno 13] Permission denied: '/tmp/foo.txt'"}`

##### EXPECTED RESULTS

I expect the COPY command to copy the file foo.txt to the destination

##### ACTUAL RESULTS

```TASK [copie du fichier] **********************************************************************************************************************************************************************************************************
task path: /home/user1/Workspace/ansible_scripts/AS/test_copy_sudo.yml:6
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: user1
<127.0.0.1> EXEC /bin/sh -c 'echo ~user1 && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/tmp/ansible-tmp-1558451982.64-19597711833329 `" && echo ansible-tmp-1558451982.64-19597711833329="` echo /var/tmp/ansible-tmp-1558451982.64-19597711833329 `" ) && sleep 0'
fatal: [localhost]: FAILED! => {
    "msg": "an error occurred while trying to read the file '/tmp/foo.txt': [Errno 13] Permission denied: '/tmp/foo.txt'"
}


```

**Comment by hvindin** [comment]
To me this looks like it's caused by copy assuming that the source file is owned by the user running ansible.

Given that you are targeting localhost you would need "become" on the remote (ie. localhost) to read the file.
So either ensuring that the user that is executing ansible can read the file, or specifying:

```
  remote_src: true
```

should make this work.

**Comment by dlucille** [comment]
Using ` remote_src: true` solved my problem. The file is on the remote machine.
