### ISSUE TITLE
s3 not downloading properly for ansible-1.4.1

### ISSUE THREAD

**Issue by jokerswild663** [ansible/ansible#5674]
Originally, I was using the s3 module as such:
-- name: testing ssl key download
-  sudo: false
-  local_action:
-   module: s3
-   aws_secret_key: "{{ aws_default_secret }}"
-   aws_access_key: "{{ aws_default_access }}"
-   bucket: "{{ s3_ssl_cert_bucket }}"
-   object: "{{ s3_ssl_cert_object_folder }}/{{ s3_ssl_cert_object }}"
-   dest: "/tmp/{{ s3_ssl_cert_object}}"
-   expiration: 600
-   mode: get
-   overwrite: false

However, when run, this play would finish successfully, but not actually download files to the path in dest:

So, this syntax does work:

-- name: something ssl key download
   sudo: false
   s3: aws_secret_key={{ aws_default_secret }}
         aws_access_key={{ aws_default_access }}
         bucket={{ s3_ssl_cert_bucket }}
         object={{ s3_ssl_cert_object_folder }}/{{ s3_ssl_cert_object }}
         dest=/tmp/certs.zip
         expiration=600
         mode=get
         force=false
   tags: noblehour

It would be very helpful if the docs for s3 were updated to explicitly state this.  Or if the module could be updated.

**Comment by sivel** [comment]
You do have a difference in your examples, which is your use of:

`"/tmp/{{ s3_ssl_cert_object}}"` vs  `dest=/tmp/certs.zip`

Also if you indent your examples with 4 spaces on each line they will be displayed better.  As it is, I cannot really determine anything else.  You may have an issue with your formatting, but I cannot tell due to how github interpreted your example.

**Comment by sivel** [comment]
Also, it may be beneficial to know what error you received.

**Comment by mpdehaan** [comment]
Since this is still in "figure it out" mode and says "doesn't work, but doesn't define what happens", I would suggest you stop by the ansible-project mailing list instead so it can be discussed in greater detail.
