### ISSUE TITLE
command 'ls' on directory with wildcard returns fail

### ISSUE THREAD

**Issue by philipnorton42** [ansible/ansible#5675]
I was trying to get a list of all jar files from a directory using the command module and a wildcard search.

```
ansible --inventory-file=hosts.ini all -m command -a 'ls -1 /some/directory/*.jar' 
```

This seems like the correct syntax to use, but Ansible returns an error stating that the containing directory doesn't exist.

```
192.168.100.100 | FAILED | rc=2 >>
ls: cannot access /some/directory/*.jar: No such file or directory
```

I can't tell if this is a bug or expected behaviour that isn't in the documentation for the command module, but either way it seemed incorrect to me.

I managed to get around this issue by using the shell module with the following arguments.

```
ansible --inventory-file=hosts.ini all -m shell -a 'ls -1 /some/directory/ | grep .jar’ 
```

This returns something like this, which is what I was originally after.

```
192.168.100.100 | success | rc=0 >>
examplefile1.jar
examplefile2.jar
examplefile3.jar
```

On a side note. Thanks for creating Ansible. It's an amazing tool :)

**Comment by redbaron** [comment]
asterisk expansion is done not by ls or any other command, but by shell, therefore to make use of it you can run something like "/bin/sh -c 'ls -1 /some/directory/*.jar' "

**Comment by srgvg** [comment]
The command module just runs a command, without shell, hence no shell expansion. If you need to use shell syntax, you need to use the shell module instead, so your assessment is correct. It's not a bug, it's a feature, if I may say so.

**Comment by mpdehaan** [comment]
yep, this is working as designed.   Switch to the shell module.

**Comment by potetm** [comment]
This really needs to be part of the documentation of the command module.  The documentation already lists variables, redirection, piping, and backgrounding, but it doesn't say anything about shell expansion.  That lead me to believe that file expansion was doable with the command module.

This problem is exacerbated by the existence of answers like [this](http://serverfault.com/a/511650/126874) on ServerFault.

**Comment by srgvg** [comment]
It is documented that the command module plainly run commands, whilst the shell module uses a shell to do that. Hence _shell_ expansion only works with the shell module.

I don't think ServerFault answers are any reference here, that answer clearly is mistaken :-)

**Comment by Cho1409** [comment]
I was having a similar problem. I was trying to install all rpm packages from a directory like this:

name: Install RPM Packages
command: yum -y *.rpm

Now it's working

name: Install RPM Packages
shell: yum -y *.rpm chdir=/path/to/files/

Thanks!

**Comment by th3morg** [comment]
How about using "ls | grep '.jar'" instead?

**Comment by redbaron** [comment]
@th3morg  , thanks for you advice, I think @philipnorton42  can finally close last remaining issue from Jan 2014 sprint
