### ISSUE TITLE
Group output for hosts with the same diff for easier verification in --diff mode

### ISSUE THREAD

**Issue by dwt** [ansible/ansible#56773]
##### SUMMARY

When looking at ansible output for multiple hosts, it can quickly get very hard to see that one of the hosts has a different diff than all the others.

It would be immensely helpful if ansible could group the output so that all hosts with identical diff are shown together / only once, so the different ones are easier to see.

This would also help to make ansible output much tighter.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

core

##### ADDITIONAL INFORMATION

This would be used when rolling out changes to multiple servers.

```yaml

```

**Comment by samdoran** [comment]
We have no plans to implement this feature at this time. You can do this using a custom callback plugin.

To discuss this further, please reach out on IRC or the mailing list:

   * IRC: #ansible-dev on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel
