### ISSUE TITLE
Ansible 2.8.0 warning on `when: variable` when variable is dynamic

### ISSUE THREAD

**Issue by kesor** [ansible/ansible#56830]
##### SUMMARY
When a variable is created using a Jinja2 template, for example:

    vars:
        foo: "{{ bar | default(False, True) }}"

Then using this variable in a `when` statement results in a warning. Example:

    when: foo

will print

    [WARNING]: conditional statements should not include jinja2 templating
    delimiters such as {{ }} or {% %}. Found: {{ bar | default(False, True) }} 

I would suspect that it was caused by the merge of this change -
https://github.com/ansible/ansible/pull/51030

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr  8 2019, 18:17:52) [GCC 8.3.0]
```

##### EXPECTED RESULTS
I expected to not see an ugly warning.

##### ACTUAL RESULTS
I got an ugly warning on valid code.

**Comment by sivel** [comment]
We likely just need to move the `if C.CONDITIONAL_BARE_VARS:` block below the `if templar.is_template(conditional):` block, effectively back to where it was before this warning was added: https://github.com/ansible/ansible/commit/4a0fceaa3bf9180b9c4adbf5d7bdb2ed4c7dbc0d

**Comment by jamescassell** [comment]
duplicate of https://github.com/ansible/ansible/issues/53428

**Comment by sivel** [comment]
This is not exactly a duplicate. I consider this one a bug, in that we changed the order of some logic that caused a regression in checking for jinja2 delimiters in when statements.
