### ISSUE TITLE
Ansible should play nicely with fakes3.

### ISSUE THREAD

**Issue by ethercrow** [ansible/ansible#5685]
fakes3 (https://github.com/jubos/fake-s3) allows having local S3-like storage, it would be nice if ansible's s3 module could use that.

To be more specific, what I'm trying to accomplish is:
 Setup: some vagrant machines provisioned by ansible. When created, they download some third-party packages from real Amazon S3.
 Work loop: developer makes changes to his package, puts it on fakes3 running on his local machine and runs ansible-playbook that checks his fake S3 server for updates.

Currently ansible has configurable parameter s3_url, but it doesn't quite do what's necessary for the use case above. If I set s3_url to something like `s3://fakes3.amazonaws.com:3333`, ansible sees that hostname ends with "amazonaws.com", then just throws away custom host and port and uses real S3. If s3_url value doesn't look like amazonaws.com, ansible thinks that it's walrus and just calls boto.connect_walrus, which throws away custom port and goes to `{{ s3_url.hostname }}:8773/something/walrus/specific`.

**Comment by mpdehaan** [comment]
Thanks for this idea, I can see that being useful -- Pull requests for this would be entertained if this is something you would like to work on.

**Comment by mpdehaan** [comment]
Closing this RFE as we now have the pull request.

Thanks!
