### ISSUE TITLE
set_facts module force boolean cast

### ISSUE THREAD

**Issue by nicocsgamer** [ansible/ansible#56857]
##### SUMMARY
    - name: test
      set_fact:
       language={'{{ "NO"  }}'}

    - name: debug
      debug:
       msg: language is {{ language }}

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
2.6.3
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS
language is NO

##### ACTUAL RESULTS
language is False

```paste below

```

**Comment by dagwieers** [comment]
That's not `set_facts` doing. We can't do anything about this behavior, it has been widely reported and documented.
