### ISSUE TITLE
Grant priv on database name with '.'

### ISSUE THREAD

**Issue by lperezs** [ansible/ansible#5686]
DatabaseName: database.version

Priv Example: database.version.*:ALL
Priv Output: {'_._': ['USAGE'], '`database`.`version`.*': ['ALL']}

to fix this, edit "ansible/database/mysql_user" 
function privileges_unpack  

replace:  pieces[0] = pieces[0].split('.')
to: pieces[0] = pieces[0].rsplit('.',1)

**Comment by mpdehaan** [comment]
Thanks for filing a ticket, per contributing.md can you please share the version of Ansible you are using?  Also can you share the arguments that you passed to the module and steps to replicate this, it's unclear what is being discussed by just seeing the patch.

(Also pull requests would be accepted, if you would like to contribute code, pull requests are preferred to just including what lines need to be changed, and that way you also get credit in the source tree).

Thanks!

**Comment by mpdehaan** [comment]
Closing this due to lack of info follow up.
