### ISSUE TITLE
ini_file is not safe enough, looses content

### ISSUE THREAD

**Issue by eigood** [ansible/ansible#5688]
In the following snippet, you'll see the before file, and the after file.  ini_file has:

1: removed comments
2: added spaces around the '='
3: reordered the lines.

The only thing I was attempting to do was changed enabled from 1 to 0.

[root@centos-63 ~]# cat /etc/yum/pluginconf.d/fastestmirror.conf 
[main]
enabled=1
verbose=0
always_print_best_host = true
socket_timeout=3
# Relative paths are relative to the cachedir (and so works for users as well
# as root).

hostfilepath=timedhosts.txt
maxhostfileage=10
maxthreads=15
# exclude=.gov, facebook
# include_only=.nl,.de,.uk,.ie

[root@centos-63 ~]# cat /etc/yum/pluginconf.d/fastestmirror.conf 
[main]
maxthreads = 15
verbose = 0
socket_timeout = 3
enabled = 0
hostfilepath = timedhosts.txt
always_print_best_host = true
maxhostfileage = 10

**Comment by mpdehaan** [comment]
So yes, spaces should not be significant in the INI file module, nor order -- so I don't see a problem with this per se.

Further, comments are not preserved, but we make a note of this in the docs, as we are using standard Python config parser to work with this and this is standard when programatically editing the file.

I think this is acceptable given it's mentioned.

Again, order should not be significant.

If this is a problem, we'd recommend using the template module instead.

**Comment by eigood** [comment]
I use etckeeper on the target machine, to save changes.  I have all my 
tasks that modify files in etc sending a notify to etckeeper, that then 
saves commits.  The ini_file module does too much changes to the dest, 
when all it needs to do is either add the line, or change the line, in 
the proper section.

The ini_file module is not the consumer of the file, it's whatever other 
program is.  So, ini_file shouldn't be adding spaces(could be 
configurable), as the program in question might not be as forgiving.

I can totally use the template module, but I thought the ini_file should 
be smarter(I realize it might be using a python library for ini 
management, and if so, then that library is also doing things in a 
sub-standard way).
