### ISSUE TITLE
Notification handler is skipped if required by both skipped and non-skipped tasks

### ISSUE THREAD

**Issue by xb** [ansible/ansible#5696]
I have a role "a", which has a dependent role "b". However, that dependent role "b" is evaluated only conditionally using the "when" key in the dependencies hash of "a/meta/main.yml".

Both roles "a" as well as "b" define a handler named "c" (and defined in exactly the same way), and both notify that handler the execution of their tasks.
### Expected behaviour

When executing role "a", it is expected that handler "c" is also executed.
### Observed behaviour

When executing role "a", handler "c" is not executed, it is skipped.
### Analysis

Probably naming both handlers in exactly the same way makes ansible mix up handlers. This is not a problem per se, as both handlers have not only the same name, but also the same definition, and thus perform the same action. However, the handler "c" of role "b" seems to be notified by the tasks of role "a" instead of the handler "c" of role "a". In turn, role "b" is considered skipped wholly, thus handler "b | c" is also not executed. Thus, the handler as intended by role "a" is erroneously not executed, neither as handler "a | c" nor as handler "b | c".
### Recommended solution

If a role notifies a handler by a "notify: foo" statement, then the handler object to be search by the name "foo" is to be searched first in the current role, and only if that handler is not found in the current role, other roles may (or may not) be searched for applicable handlers. In short: the current role should take precedence when searching for handlers.

**Comment by mpdehaan** [comment]
Per contributing.md, can you please share the version of Ansible you are using?

Also, can you share a link to a minimal repo that reproduces this problem?

**Comment by mpdehaan** [comment]
I'm closing this due to lack of feedback on the above, this may already be resolved or addressed by other tickets.
