### ISSUE TITLE
Running checks before asking for passwords

### ISSUE THREAD

**Issue by fbruetting** [ansible/ansible#56962]
##### SUMMARY
Would be cool if syntax checks etc. could run before before asking the user to type in any passwords.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- ansible
- ansible-playbook

##### ADDITIONAL INFORMATION
When I misspelled a module and try to run the playbook, I first get asked for the SSH/become passwords and then get displayed the syntax error. This is quite unfortunate, because with every mistake, I have to superfluously enter the passwords. So it would be cool if as much checks as possible could run before asking for passwords.

Another issue was that Ansible sometimes processes `-m setup -a filter=<…>` commands even if I enter completely wrong passwords – so Ansible seems to either cache the `setup` result, or maybe even reuse connections from previous commands. I don’t know if the fact that “no new SSH connection needs to be established” could (easily) be inferred right at the start – but for running repeated `setup` filters for grepping/validating some Ansible facts, it would be cool if we would not have to enter the passwords every time, when these don’t even get used at all!

Example (Ansible v2.8):

```
> ansible-playbook -Kk multimedia.yaml
SSH password: 
BECOME password[defaults to SSH password]: 
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to be in '/var/home/frank/Projekte/ansible/roles/grundsystem/tasks/main.yaml': line 69, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
```

**Comment by JayWelborn** [comment]
If this is a desired change and no one's working on it, I'd like to take a look at it.

**Comment by fbruetting** [comment]
Ah that’d be cool! Could save quite some time, especially on small setups where you don’t need to work with a root-like ansible account.
