### ISSUE TITLE
Synchronize module incorrectly uses ssh for local connection

### ISSUE THREAD

**Issue by nikut** [ansible/ansible#5702]
The synchronize module in current devel is unusable when remote_user does not exist on the Ansible control host. This is because the module insists on using ssh and the configured remote_user for the local connection. It should either use the local transport or at least leave out remote_user when connecting to localhost. 

Setting "connection: local" or "delegate_to: localhost" or using local_action are not useful workarounds as they will only cause the module to rsync from localhost to localhost.

Playbook example (run as user 'ansible'):

```

---
- name: Rsync test
  hosts: some-ec2-instance
  gather_facts: no
  remote_user: ec2-user

  tasks:
    - name: Rsync
      synchronize: src=/tmp/testfile dest=/tmp/testfile
```

Actual result:

```

PLAY [Rsync test] ************************************************************* 

TASK: [Rsync] ***************************************************************** 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: ec2-user on PORT 22 TO 127.0.0.1
fatal: [10.6.16.46] => {'msg': 'FAILED: Authentication failed.', 'failed': True}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/ansible/synctest.retry

10.6.16.46                 : ok=0    changed=0    unreachable=1    failed=0   
```

Expected result: the local connection is performed either using the local transport or using ssh as the ansible user and the file is synchronized to the remote host.

**Comment by jctanner** [comment]
@nikut Can you post the contents of your inventory file?

**Comment by nikut** [comment]
My inventory consists of a hosts file and a couple of dynamic inventory scripts so I can't really post that. However your comment made me realize what's causing this. 

This inventory fails:

```
localhost
otherhost
```

This inventory works:

```
localhost ansible_connection=local
otherhost
```

Also this inventory works:

```
otherhost
```

So it turns out that it was user error, although this behavior is certainly non-obvious and should probably be changed or at least documented.

Thanks for pointing me in the right direction!

**Comment by jctanner** [comment]
@nikut I ran a basic test with synchronize based on having a remote_user that does not exist on the local machine, and it did fail per your description. Looking further into the issue though, I realized that this is not an issue with the synchronize module ...

```
jtanner@u1304:~/issues/5702-synchronize-remote_user-localhost$ cat inventory
localhost
el6.lab.net
jtanner@u1304:~/issues/5702-synchronize-remote_user-localhost$ cat site.yml
- hosts: el6.lab.net
  #connection: local
  gather_facts: False
  remote_user: ec2_user
  tasks:
    - shell: whoami; uname -a
    #- synchronize: src=/tmp/nobody dest=/tmp/nooboody
```

Result:

```
PLAY [el6.lab.net] ************************************************************

TASK: [shell whoami; uname -a] ************************************************
<el6.lab.net> ESTABLISH CONNECTION FOR USER: ec2_user
<el6.lab.net> REMOTE_MODULE command whoami; uname -a #USE_SHELL
<el6.lab.net> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jtanner/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=ec2_user', '-o', 'ConnectTimeout=10', 'el6.lab.net', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1390406149.1-67284590520786 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1390406149.1-67284590520786 && echo $HOME/.ansible/tmp/ansible-tmp-1390406149.1-67284590520786'"]
fatal: [el6.lab.net] => SSH encountered an unknown error. The output was:
OpenSSH_5.9p1 Debian-5ubuntu1, OpenSSL 1.0.1 14 Mar 2012
debug1: Reading configuration data /home/jtanner/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket "/home/jtanner/.ansible/cp/ansible-ssh-el6.lab.net-22-ec2_user" does not exist
debug2: ssh_connect: needpriv 0
debug1: Connecting to el6.lab.net [192.168.1.148] port 22.
debug2: fd 3 setting O_NONBLOCK
debug1: fd 3 clearing O_NONBLOCK
debug1: Connection established.
debug3: timeout: 10000 ms remain after connect
debug3: Incorrect RSA1 identifier
debug3: Could not load "/home/jtanner/.ssh/id_rsa" as a RSA1 public key
debug1: identity file /home/jtanner/.ssh/id_rsa type 1
debug1: Checking blacklist file /usr/share/ssh/blacklist.RSA-2048
debug1: Checking blacklist file /etc/ssh/blacklist.RSA-2048
debug1: identity file /home/jtanner/.ssh/id_rsa-cert type -1
debug1: identity file /home/jtanner/.ssh/id_dsa type -1
debug1: identity file /home/jtanner/.ssh/id_dsa-cert type -1
debug1: identity file /home/jtanner/.ssh/id_ecdsa type -1
debug1: identity file /home/jtanner/.ssh/id_ecdsa-cert type -1
debug1: Remote protocol version 2.0, remote software version OpenSSH_5.3
debug1: match: OpenSSH_5.3 pat OpenSSH*
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: Trying private key: /home/jtanner/.ssh/id_dsa
debug3: no such identity: /home/jtanner/.ssh/id_dsa
debug1: Trying private key: /home/jtanner/.ssh/id_ecdsa
debug3: no such identity: /home/jtanner/.ssh/id_ecdsa
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/jtanner/site.retry

el6.lab.net                : ok=0    changed=0    unreachable=1    failed=0
```

This failure is expected, since ec2_user does not exist on this host. As mentioned in your previous comment, the connection will need to be local if the remote user is set to a non-existing user. We can't really fix this within the synchronize module because it's an error that would pop up in any task that tries to connect over any transport besides local.

**Comment by nikut** [comment]
@jctanner, that makes sense, my only issue with this is that there is no way to force the connection to be local in the playbook when using the synchronize module. The fact that you need to either add "ansible_connection=local" for localhost in the inventory or remove localhost from the inventory altogether was not at all obvious to me. 

When you are using something like the shell module, it's clear what you are connecting to and you can set the remote_user and connection type accordingly in the playbook, but with the synchronize module you cannot do that. You have to set remote_user according to the remote host's needs and use magic (ie. "localhost ansible_connection=local" in the inventory) to force the local connection to not use ssh. Using "connection: local" in the playbook will not do what you would expect. I'm not sure that this is a bug but it's certainly confusing.

**Comment by jctanner** [comment]
My misunderstanding was the remote_user does actually exist on the remote host, and in that case other modules would work without issue.

**Comment by nikut** [comment]
Just to be clear, removing localhost from the inventory fixed the issue for me and seems to be the recommended way in any case now that localhost is "magic". This is not an issue for me anymore but I imagine it may still cause trouble for others. @jctanner, feel free to keep this open or close it as you see best. Thanks for your help!

**Comment by mscherer** [comment]
Was this on git head ?  ( since #5668 is about a problem that looked similar, and this was fixed in HEAD )

**Comment by nikut** [comment]
@mscherer, yes, latest devel, and I believe it's a different issue. Note that in my case the connection to the destination needs to be ssh, the problem is/was with connecting locally to the source (localhost) specifically when ansible_connection=local is _not_ specified for it.

**Comment by jctanner** [comment]
nikut, dug some more into this. As you stated, not defining localhost in inventory or defining ansible_connection=local for localhost will allow your playbook to function. The reason this works is because the connection object passed into the synchronize action plugin is "local". By only defining "localhost" in inventory, the conn object defaults to "ssh" or whatever "smart" dictates on your control host. It's this conn object that must be local to avoid ssh'ing to localhost as a non-existing user. We can't actually fix this in the synchronize code, since runner and inventory are how the conn object is created. 

I'm going to go ahead and close this issue since we understand how to make it work.

**Comment by FiloSottile** [comment]
I spent a great amount of time on this one, and I think it should be explained better. The inventory suggested by the docs here http://docs.ansible.com/guide_aws.html will trigger this behavior.

At least the docs are to fix.

**Comment by jctanner** [comment]
@FiloSottile this issue is closed, please open a documentation bug.

**Comment by icoloma** [comment]
I would suggest to include it in the default hosts file _and_ the documentation. This issue is the only place where this is documented so far.

**Comment by podarok** [comment]
I have an issue with 

``` yml
  - name: Copy local files for enabling jenkins permissions
    sudo: yes
    synchronize: src=files/jenkins/ dest=/var/lib/jenkins recursive=yes archive=no
    when: prbuilder_stat.stat.exists == false
    tags:
      - jenkins_jobs
```

When there is 

``` ini
[localhost]
127.0.0.1
```

in inventory file defined
Removing it from inventory fixes ssh connection error

**Comment by mpdehaan** [comment]
You can remove it, since it's automagical, but you can also do:

[localhost]
127.0.0.1 ansible_connection=local

**Comment by xrow** [comment]
Dang! Ran into the same issue. I guess an automagical improvement would be, if ansible would know that  127.0.0.1 & localhost are always local.

I would like to reopen it as minor improvement.

**Comment by balboah** [comment]
Spent an hour or two trying to figure out what was happening as well.
Setting `ansible_connection=local` made it work like I was expecting it to work.

The reason that I specified it in hosts file was to have settings for EC2 connections with group_vars:

```
# Talking to EC2 API is always from localhost
[aws_ireland]
localhost
```

**Comment by danmbox** [comment]
Oh, it's a "documentation bug" you see... What a time-waster, I had to strace sshd and its children to track it, since OF COURSE the damn thing hangs and doesn't provide any errors.

But I still don't get it. I'm running ansible-playbook on localhost with `-i localhost,`. That is a reasonable use-case -- I want to configure the local machine according to some given patterns. Why does ansible need a ssh within ssh? Isn't a single ssh enough?

**Comment by danmbox** [comment]
... and I gather that since I need to specify --connection=local (I'm not modifying the playbook just so I can use it on localhost), I can't mix local and other hosts? Nice!

**Comment by bcoca** [comment]
you can set connection at many levels, if you set it as local just for localhost, you can mix/match easily

**Comment by danmbox** [comment]
Command line is most convenient for dynamic inventories. But why the ssh-to-localhost within an ssh-to-localhost? I can understand one ssh, but why nest a second one (which hangs without agent forwarding)?

**Comment by gbane2012** [comment]
Hey guys,I need some help with that jenkins job result 
PLAY [Deploy to status servers] **********************************************\* 

GATHERING FACTS **************************************************************\* 
<172.16.21.129> ESTABLISH CONNECTION FOR USER: ubuntu
<172.16.21.129> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/var/lib/jenkins/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'IdentityFile=/root/.ssh/ProdCSkeylocal.pem', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=ubuntu', '-o', 'ConnectTimeout=10', '172.16.21.129', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1445955891.1-256226679010016 && chmod a+rx $HOME/.ansible/tmp/ansible-1445955891.1-256226679010016 && echo $HOME/.ansible/tmp/ansible-1445955891.1-256226679010016'"]
fatal: [prodstatus0] => SSH encountered an unknown error. The output was:
OpenSSH_5.9p1 Debian-5ubuntu1.1, OpenSSL 1.0.1 14 Mar 2012
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket "/var/lib/jenkins/.ansible/cp/ansible-ssh-172.16.21.129-22-ubuntu" does not exist
debug2: ssh_connect: needpriv 0
debug1: Connecting to 172.16.21.129 [172.16.21.129] port 22.
debug2: fd 3 setting O_NONBLOCK
debug1: fd 3 clearing O_NONBLOCK
debug1: Connection established.
debug3: timeout: 10000 ms remain after connect
debug1: identity file /root/.ssh/ProdCSkeylocal.pem type -1
debug1: identity file /root/.ssh/ProdCSkeylocal.pem-cert type -1
debug1: Remote protocol version 2.0, remote software version OpenSSH_5.9p1 Debian-5ubuntu1.4
debug1: match: OpenSSH_5.9p1 Debian-5ubuntu1.4 pat OpenSSH*
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1.1
debug2: fd 3 setting O_NONBLOCK
debug3: load_hostkeys: loading entries for host "172.16.21.129" from file "/var/lib/jenkins/.ssh/known_hosts"
debug3: load_hostkeys: found key type ECDSA in file /var/lib/jenkins/.ssh/known_hosts:188
debug3: load_hostkeys: loaded 1 keys
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: kex_parse_kexinit: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ssh-rsa,ssh-dss
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug2: kex_parse_kexinit: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug2: mac_setup: found hmac-md5
debug1: kex: server->client aes128-ctr hmac-md5 none
debug2: mac_setup: found hmac-md5
debug1: kex: client->server aes128-ctr hmac-md5 none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ECDSA ee:1a:2a:a3:da:a1:b3:c8:e8:a7:68:10:be:15:7c:8a
debug3: load_hostkeys: loading entries for host "172.16.21.129" from file "/var/lib/jenkins/.ssh/known_hosts"
debug3: load_hostkeys: found key type ECDSA in file /var/lib/jenkins/.ssh/known_hosts:188
debug3: load_hostkeys: loaded 1 keys
debug1: Host '172.16.21.129' is known and matches the ECDSA host key.
debug1: Found key in /var/lib/jenkins/.ssh/known_hosts:188
debug1: ssh_ecdsa_verify: signature correct
debug2: kex_derive_keys
debug2: set_newkeys: mode 1
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug2: set_newkeys: mode 0
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: /root/.ssh/ProdCSkeylocal.pem ((nil))

TASK: [nodejs_app | Put upstart script in place] *****************************\* 
FATAL: no hosts matched or all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/var/lib/jenkins/deploy_system_status.retry

prodstatus0                : ok=0    changed=0    unreachable=1    failed=0

**Comment by ramayer** [comment]
IMHO There's too much magic in that synchronize module.

I find it easier to understand and more reliable to just call rsync directly as described here: 

https://groups.google.com/d/msg/ansible-project/aC3WStjfoh4/Hd1Pjvvsb-wJ

I.e. use this: 

```
rsync task:

    - name: my copy in bin dir
      sudo: no
      local_action: >
        command
        rsync
        --delay-updates -FF --compress --timeout=10 --delete-after
        --archive --no-owner --no-group
        --rsh 'ssh -i /home/mumble/.ansible/keys/mumble-id_rsa -o stricthostkeychecking=no'   
        --rsync-path 'sudo rsync'
        --out-format='<<CHANGED>>%i %n%L'
        {{ inventory_dir }}/working/mumble-bin/
        admin@{{ inventory_hostname }}:/mumble/bin
```

instead of the synchronize module.

**Comment by pdougall1** [comment]
So I was getting really stuck with just the intro installation here: http://docs.ansible.com/ansible/intro_installation.html

an particularly this line `$ echo "127.0.0.1" > ~/ansible_hosts`

possibly it should read `$ echo "127.0.0.1 ansible_connection=local" > ~/ansible_hosts`?
