### ISSUE TITLE
Please add failback feature for delegate_to

### ISSUE THREAD

**Issue by nomadcz** [ansible/ansible#57034]
##### SUMMARY

Please add failback feature for delegate_to so when host is not available or timeouts another one is tried.

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

We occasionally have some not clustered setup when multiple servers provide same service.
We have to do some setup via delegate_to and it would be helpful to switch to another host when there is a connection/timeout issue.

Something like this would be helpful:
```yaml

   delegate_to:
      - host1
      - host2
```

or

```yaml

   delegate_to: host1
   delegate_to_backup: host2
```

**Comment by bcoca** [comment]
i would read that as 'delegate the task to both hosts' not fallback to x host

**Comment by nitzmahone** [comment]
Thanks for the idea, but this is probably not something widely enough needed that we'd consider implementing it... You might want to try using block/rescue to implement similar behavior if you have a critical point where delegating to a fallback host might be needed.
