### ISSUE TITLE
ansible-pull should have -e (--extra-vars) option (same as ansible-playbook)

### ISSUE THREAD

**Issue by ingmar** [ansible/ansible#5707]
It'd be quite useful to pass in machine-dependent stuff at startup, in this case some instance user-data data from an EC2 autoscaling group.

**Comment by ingmar** [comment]
Meanwhile I just hacked it into the local ansible-pull, like so (against ansible 1.4.4):

```
121a124,125
>     parser.add_option('-e', '--extra-vars', dest="extra_vars", action="append",
>                       help="set additional variables as key=value or YAML/JSON", default=[])
173a178,179
>     for ev in options.extra_vars:
>         cmd += ' -e "%s"' % ev
```

**Comment by mpdehaan** [comment]
If you would like to submit a patch, please do so by submitting a pull request.

Thanks!
