### ISSUE TITLE
Tags not found if 2 levels of dependency between playbook and role with tasks/main.yml 

### ISSUE THREAD

**Issue by sebbrochet** [ansible/ansible#5709]
Let's say my main playbook _site.yml_ is:

```
# site.yml
- hosts: myhosts
  user: root
  roles:
    - {role: myrole, tags: "myrole"}
```

And _myrole_ is a virtual role with only dependencies:

```
# myrole/meta/main.yml

---
dependencies:
  - { role: myrole1 }
```

And _myrole1_ is a virtual role with only dependencies:

```
# myrole1/meta/main.yml

---
dependencies:
  - { role: myrole2 }
```

While _myrole2_ is a concrete role with a _tasks/main.yml_: 

```
#myrole2/tasks/main.yml
- name: stuff
  shell: echo hello
```

If I try to execute my playbook with a specific tags, it fails:

```
# ansible-playbook -i myhosts site.yml --tags foobar
ERROR: tag(s) not found in playbook: foobar.  possible values:
```

ansible is not able to infer the _myrole_ tag in the list of possible tags.

But if I change _myrole/meta/main.yml_ to depend on _myrole2_ instead of _myrole1_

```
# myrole/meta/main.yml

---
dependencies:
  - { role: myrole2 }
```

Tags are correctly found:

```
# ansible-playbook -i myhosts site.yml --tags foobar
ERROR: tag(s) not found in playbook: foobar.  possible values: myrole
```

I can workaround this behaviour by creating a dummy _tasks/main.yml_ in _myrole1_ but I'd prefer to have more than 1 level of lookup for role detection...

Thanks

(BTW, I've come with this use-case when implementing [platform-specific roles](https://groups.google.com/forum/#!searchin/Ansible-project/subrole/ansible-project/c_n9_6u0iec/aH5RT-RwdVcJ) and playbook decomposed by tiers with 1 virtual role to describe 1 tier...)

**Comment by mpdehaan** [comment]
Can you please share a repo that implements this scenario for test purposes?

Thanks!

**Comment by sebbrochet** [comment]
Sure, here it is: https://github.com/sebbrochet/Ansible-Tags-not-found-if-2-levels-of-dependency-between-playbook-and-role

**Comment by jimi-c** [comment]
@sebbrochet I believe I have partially fixed this in the current development branch, if you would like to verify it. The "partially" is due to the fact that the error message shown still does not list all of the tags found in the roles, which I will continue to work on.

**Comment by sebbrochet** [comment]
@jimi-c I've just git-cloned Ansible and tested.
myrole tag is executed if asked explicitly but no tags are displayed if tag doesn't exist (as described above).

How is the output supposed to have changed ?

**Comment by jimi-c** [comment]
@sebbrochet I thought it wasn't finding the tags at all if nested as above. I'm still working on the tag output issue.

**Comment by jimi-c** [comment]
This should now be resolved:

<pre>
[root 5709]# ansible-playbook site.yml --tags=foo
ERROR: tag(s) not found in playbook: foo.  possible values: myrole
[root 5709]# ansible-playbook site.yml --tags=myrole
PLAY [localhost] ************************************************************** 
TASK: [myrole2 | stuff] ******************************************************* 
changed: [127.0.0.1]
PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=1    changed=1    unreachable=0    failed=0   
</pre>

Please let us know if you continue having problems with this issue. Thanks!

**Comment by sebbrochet** [comment]
Hi jimi-c,

Thanks for the fix, it corrects this use-case.
Unfortunately, there are still some glitches with tags used in subroles, please have look on #6557
