### ISSUE TITLE
sudo'd service module execution does not appear to match pattern in sudoers file

### ISSUE THREAD

**Issue by bpb** [ansible/ansible#5712]
<h1>Bug</h1>

Sudo'ing the service module using a user other then root causes Ansible to halt on password prompt even if the sudo user has permission to run the service.

<h2>Example</h2>

<h3>Preliminary Setup:</h3>

Create a server called <b>testbox</b> with the user <b>bpb</b>. Create a ssh authorization id_dsa.pem key for the bpb user.
Add bpb to sudoers.

<b>etc/sudoers</b>

<pre><code>
...
bpb All=(root) NOPASSWD:/sbin/service mongod *
...
</code></pre>

When logged into linux as user bpb I can execute "sudo service mongod restart" without password prompt.

<h3>Simple Playbook test</h3>

Create the following playbook and handler

<b>test.yml</b>

<pre><code>

---
- name: Test
  hosts: all
  remote_user: bpb

  tasks:
  - name: test task
    command: echo "This is a test"
    notify:
       - restart mongod service

  handlers:
    - include:
        handler.yml
</code></pre>

<b>handler.yml</b>

<pre><code>

---
- name: restart mongod service
  service: name=mongod state=restart
  sudo: yes
</code></pre>

<b>Command line execution</b>

<pre><code>
[root ~]# ansible-playbook -v -i hosts --limit tst --private-key id_dsa.pem test.yml
</code></pre>

Upon execution Ansible halts for approximately 5 minutes waiting on a password prompt.

<h3>Result</h3>

<b>Ansible</b>

<pre><code>
PLAY [Test] ******************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [testbox]

TASK: [test task] ********************************************************** 
changed: [testbox] => {"changed": true, "cmd": ["echo", "This is a test"], "delta": "0:00:00.001316", "end": "2014-01-21 13:07:34.632441", "rc": 0, "start": "2014-01-21 13:07:34.631125", "stderr": "", "stdout": "This is a test"}

NOTIFIED: [restart mongod service] ******************************************** 
failed: [testbox] => {"failed": true, "item": "", "parsed": false}
invalid output was: [sudo via ansible, key=nadiqotunmgfbfqizdazxiawpnkuwhhj] password: 

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/test.retry
testbox              : ok=2    changed=1    unreachable=0    failed=1
</code></pre>

Doing a "ps -ef | grep bpb" on the test box during the 5 minute wait show that Ansible is trying to execute the following line when it was stopped by the password prompt.

<b>running "ps -ef |  grep bpb" on testbox server</b> 

<pre><code>
root      5947  5927  0 13:07 ?        00:00:00 
sudo -H -S -p [sudo via ansible, key=nadiqotunmgfbfqizdazxiawpnkuwhhj] password:  -u root /bin/sh -c echo SUDO-SUCCESS-nadiqotunmgfbfqizdazxiawpnkuwhhj;
<b>/usr/bin/python /home/bpb/.ansible/tmp/ansible-1390311519.49-229208254774912/service /home/bpb/.ansible/tmp/ansible-1390311519.49-229208254774912/arguments;</b> 
rm -rf /home/bpb/.ansible/tmp/ansible-1390311519.49-229208254774912/ >/dev/null 2>&
</code></pre>

<h2>Conclusion</h2>

It appears that the Ansible execution of sudo'd service module does not match the pattern in /etc/sudoers.

<h2> Work Around </h2>

Change the handler.yml to a pure command using the raw module.
<b>handler.yml</b>

<pre><code>

---
- name: restart mongod service
  raw: sudo service mongod restart
</code></pre>

**Comment by bcoca** [comment]
No it does not, it runs sudo on a shell that calls a temp script (which
normally involves python) that then call the service binary (or init
script/etc).

This is not a bug, this is how ansible works, all modules will have the
same issue as ansible must generalize it's sudo usage when it executes
arbitrary code (the module).

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by bpb** [comment]
I understand and that this happens on all modules. But then what is the work around other then calling a raw command. It is not clear what Ansible is trying to execute through its modules behind the scenes and so it is not clear what the sudoers pattern should look like in this situation.

**Comment by bcoca** [comment]
If you run with -vvvv you will see exactly what ansible executes, since it
is using temp files it will be pretty hard to come up with an acceptable
sudo pattern, most ansible users using sudo, have ALL.

**Comment by bpb** [comment]
I apologize if this sounds naive and maybe this is an obvious condition on under which all modules in Ansible operate but from a system admin perspective elevating any user through which Anisble executes to ALL privileges seems unreasonable.

**Comment by bcoca** [comment]
Yes and no, since configuration management normally requires root or full
root privileges, it makes sense for ansible, most users either login as
root or have sudo ALL privs.

For those that are in very restricted environments and only have privileges
for very specific actions, ansible won't work for you, nor most
configuration management tools as they either have to execute as root or
use a similar sudo/su approach.

**Comment by bcoca** [comment]
clarification: ansible CAN work for you but you'll be restricted to mostly
the raw module and will be unable to use it fully.

Another option is to follow the 'agent' model and use ansible-pull from
root cron and drop privileges for most commands (but not service
restarts), this is how most other tools work.

**Comment by bpb** [comment]
This is good to know thank you.

**Comment by mminklet** [comment]
I realise this is closed, but I find this a little unreasonable.

Perhaps when using ansible for server provisioning this makes sense, but Ansible is a bigger tool than that. To use it for deployments, you don't want to give root access to the deployment, you want to use a deploy specific user. Granting that user access to do anything is not an option, and ansible makes it very difficult to allow fine tuning of passwordless sudo.

I have been trying to get ansible to restart the php5-fpm service for hours now. And nothing I add to the sudoers list works, and every ansible module I use to execute this gives me an error. I find this disturbing tbh, that it's so difficult to securely execute playbooks as anyone but root.

I have tried raw, shell and command and none work, nor give me a usable error message when using -vvvv.

**Comment by nanobeep** [comment]
For anyone else hitting this issue, here's a quick write-up of a couple possible workarounds: https://gist.github.com/nanobeep/3b3d614a709086ff832a
