### ISSUE TITLE
fail module with_items prints the whole item even if using loop_control label

### ISSUE THREAD

**Issue by amirwollman** [ansible/ansible#57128]
Related to bug report #35493: 
https://github.com/ansible/ansible/issues/35493

##### SUMMARY
Same as the debug module, the fail module output includes all the items in the output.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
fail module

##### ANSIBLE VERSION
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o ServerAliveInterval=30 -o ServerAliveCountMax=30
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = memory
DEFAULT_ACTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/action_plugins']
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/callback_plugins']
DEFAULT_CONNECTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/filter_plugins']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 5
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = implicit
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_LOOKUP_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/lookup_plugins']
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_MODULE_LANG(/etc/ansible/ansible.cfg) = C
DEFAULT_POLL_INTERVAL(/etc/ansible/ansible.cfg) = 15
DEFAULT_SUDO_EXE(/etc/ansible/ansible.cfg) = sudo
DEFAULT_SUDO_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 10
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = smart
DEFAULT_VARS_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/vars_plugins']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
CentOS.7

##### STEPS TO REPRODUCE
```
  - name: Verify installation on all hosts
    fail:
      msg:
      - "Service {{ item.item }} failed to install"
    with_items: "{{ setup_service.results}}"
```
*changed to {{ item.item }} as per @bcoca comment.
and setup_service.results is:
```
{
            "_ansible_item_label": {
                "_ansible_ignore_errors": null,
                "_ansible_item_label": "analytics",
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "_ansible_parsed": true,
                "ansible_job_id": "177763316316.24500",
                "changed": true,
                "failed": false,
                "finished": 0,
                "item": "analytics",
                "results_file": "/root/.ansible_async/177763316316.24500",
                "started": 1
            },
            "_ansible_item_result": true,
            "_ansible_no_log": true,
            "_ansible_parsed": true,
            "ansible_job_id": "177763316316.24500",
            "attempts": 1,
            "changed": false,
            "failed": true,
            "finished": 0,
            "invocation": {
                "module_args": {
                    "jid": "177763316316.24500",
                    "mode": "status"
                }
            },
            "item": {
                "_ansible_ignore_errors": null,
                "_ansible_item_label": "analytics",
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "_ansible_parsed": true,
                "ansible_job_id": "177763316316.24500",
                "changed": true,
                "failed": false,
                "finished": 0,
                "item": "analytics",
                "results_file": "/root/.ansible_async/177763316316.24500",
                "started": 1
            },
            "started": 1
        }
```

##### EXPECTED RESULTS
something of the below sort:
```
failed: [localhost] (item=analytics) => {"msg": ["Service analytics failed to install"]}
```

##### ACTUAL RESULTS
```
TASK [Verify installation on all hosts] ************************************************************************************************************************************
failed: [localhost] (item=analytics) => {"changed": false, "item": {"ansible_job_id": "950275398852.1021", "attempts": 1, "changed": false, "failed": true, "finished": 0, "invocation": {"module_args": {"jid": "950275398852.1021", "mode": "status"}}, "item": {"ansible_job_id": "950275398852.1021", "changed": true, "failed": false, "finished": 0, "item": "analytics", "results_file": "/root/.ansible_async/950275398852.1021", "started": 1}, "started": 1}, "msg": ["Service analytics failed to install"]}
```

**Comment by amirwollman** [comment]
I'm running with one level of verbosity (-v) but see the same results with no verbosity

**Comment by bcoca** [comment]
`_ansible_*` vars are for internal use and not supposed to work in user provided expressions

**Comment by amirwollman** [comment]
> `_ansible_*` vars are for internal use and not supposed to work in user provided expressions

Noted. Thanks for the comment. However, correct me if I'm wrong but this is unrelated to the question..

**Comment by bcoca** [comment]
well, to answer your question, i dont see a reason why you would expect the full item not to be displayed, i believe you want:

```   - "Service {{ item.item['msg'] }} failed to install"```

**Comment by amirwollman** [comment]
Same as with the debug module, I would like the output to be the msg only rather than the entire item iterated + the message.
Maybe I'm using the wrong module for what I want?
I'll try and achieve what I want with the debug module combined with failed_when though if I remember correctly I tried it and it did not work..

Also, If this is the expected (and desired) result please go ahead and close this bug report - though I do believe this is something which may be beneficial in some cases, so maybe a feature request?

**Comment by bcoca** [comment]
again, you are specifying the item, not the 'msg' key, there is not magic that will autoselect a subkey

**Comment by amirwollman** [comment]
I think I see what you mean now, however I don't think it's applicable in this case since the msg key belongs to the output of the fail module rather than the item I'm iterating over.

(Running this results in:
TASK [Verify installation on all hosts] *****************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "'dict object' has no attribute 'msg'"}
)

I can do that with "register: fail_output" and "msg: 'Service {{ item.item['msg'] }} failed to install'"
However this is not optimal I think..
