### ISSUE TITLE
VMware: module to assign permissions on folders

### ISSUE THREAD

**Issue by markatdxb** [ansible/ansible#57210]
##### SUMMARY

Build new module allowing to assign VCS permissions on objects. 
##### ISSUE TYPE
- Feature Idea
Currently we are able to create VM folders but unable to push VCS permissions 
##### ADDITIONAL INFORMATION

Same concept as vmware_object_role_permission  - which work on ESXi level but have this for VCS

```yaml

```

**Comment by dczupryn** [comment]
It would be great to have as well other modules that works with local ESXi (vmware_local_role_manager, vmware_local_user_manager) to work with vCenter server.

**Comment by digifuchsi** [comment]
> It would be great to have as well other modules that works with local ESXi (vmware_local_role_manager, vmware_local_user_manager) to work with vCenter server.

2nd this

**Comment by Akasurde** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.vmware.

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
