### ISSUE TITLE
ACI exiting config validations and stop further script accordingly

### ISSUE THREAD

**Issue by amitswt** [ansible/ansible#57235]
##### SUMMARY
I have created my playbook for day to day activities like edge port configurations , most of interface modules merge the configurations  to exisitng configurations.

I need help how i can validate if there is existing IPG/BD/EPG with same name and if its there do not go ahead and  merge configurations to existing IPG/BD/EPG as per new IPG/BD/EPG creation playbook. So want to avoid configurations chnages to existing IPG/BD/EPG.

If IPG/BD/EPG is present with same name playbook should stop and do not do any chnages , i know fail module is there but not getting idea how i can use that.

##### COMPONENT NAME

lib/ansible/modules/network/aci/aci_bd.py
lib/ansible/modules/network/aci/aci_epg.py
##### ANSIBLE VERSION
Ansible 2.7

```

**Comment by samdoran** [comment]
This is better addressed in IRC or the mailing list:

   * IRC: #ansible-network on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
