### ISSUE TITLE
Not detecting python-boto

### ISSUE THREAD

**Issue by eproxus** [ansible/ansible#5734]
On OS X: Python and Ansible installed by running `brew install python ansible`. python-boto installed by running `pip install boto` (in the global site-packages for the python that is first in `PATH`, the one from Homebrew).

Everything comes from Homebrew:

```
$ which python
/usr/local/bin/python
$ which ansible-playbook
/usr/local/bin/ansible-playbook
$ which ansible
/usr/local/bin/ansible
$ ansible --version
ansible 1.4.4
```

python-boto is available:

```
» python
Python 2.7.6 (default, Jan 14 2014, 12:13:06)
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.2.79)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto
>>>
```

Still, Ansible can't find python-boto:

```
$ ansible-playbook ec2_test.yml -i hosts

PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [Create EC2 web group] **************************************************
failed: [localhost] => {"failed": true}
msg: boto required for this module

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/alind/ec2_security.retry

localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by eproxus** [comment]
Fixed by changing `hosts` inventory file from:

```
[localhost]
127.0.0.1
```

to

```
[localhost]
127.0.0.1 ansible_python_interpreter=/usr/local/bin/python
```

**Comment by jondlm** [comment]
Another way of fixing this is with `export PYTHONPATH="/usr/lib/python2.6/site-packages"` which works on CentOS. Just make sure `PYTHONPATH` is pointing to the same place that `pip` is installing the packages, a folder called `site-packages`.

**Comment by brandonrich** [comment]
I'm in the exact same boat as the original poster, but none of the fixes are working.  I did 

`export PYTHONPATH=/usr/lib/python2.6/site-packages`

and made sure the path matches what `pip install boto` says for the location of boto.

No dice.  Then I tried `ansible_python_interpreter=/usr/local/bin/python` and I get this:

`SUDO-SUCCESS-ovbfydigjsszmypyvbyrsidfumzpobfa`
`/bin/sh: /usr/local/bin/python: No such file or directory`

I'm trying to use the s3 module to get a file that is not available to the public, so I can't use get_url.  I need it to use the AWS CLI / boto so it runs as my AWS user...

**Comment by eproxus** [comment]
Could it be that `/usr/local/bin/python: No such file or directory` comes from the remote machine?

**Comment by brandonrich** [comment]
I had considered that, but I'm not sure.  Can any Ansible folks clarify whether the s3 module initiates its connection to s3 locally, or on the remote host?  In either case, I have to use STS to get temporary credentials before using the AWS API.   I can set that up in advance on my local machine, but if this module depends on the remote host having valid credentials to the s3 bucket, the automation aspect is kind of hosed.

**Comment by bcoca** [comment]
modules always execute on target server unless you tell them otherwise, so
if you are not using local_action: or connection: local, it will try to
execute on 'inventory_hostname'

**Comment by brandonrich** [comment]
Yeah, I was just writing an edit to the previous post:  it does seem to refer to the destination machine (confirmed by bcoca).  Installing pip/boto on the target got me further.  However, I'm getting this:

`No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials`

which gets into the authorization problem.  This bucket has a pretty restrictive access policy on it, so I'm going to have to figure something out.  That's off-topic of this thread, though.

Possibly on-topic:  is it possible to use this module to execute the s3 download locally, then push the file to the remote machine?

**Comment by bcoca** [comment]
You can execute s3 locally by using local_action, connection: local or
delegate_to: localhost, but then you need a separate 'copy' task.

**Comment by brandonrich** [comment]
That's perfect.  Thanks!

**Comment by Laxman-SM** [comment]
HI,

when i executed ansible-playbook, i'm getting below mentioned error. every time i ran playbook, this will create new instance. that is strange. 

PLAY [Configure Zookeeper instances] *****************************************\* 

GATHERING FACTS **************************************************************\* 
<ec2-54-226-184-40.compute-1.amazonaws.com> ESTABLISH CONNECTION FOR USER: ubuntu
<ec2-54-226-184-40.compute-1.amazonaws.com> REMOTE_MODULE setup
fatal: [ec2-54-226-184-40.compute-1.amazonaws.com] => Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/runner/**init**.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/runner/__init__.py", line 789, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1036, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/runner/action_plugins/normal.py", line 62, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/runner/__init__.py", line 474, in _execute_module
    tmp = self._make_tmp_path(conn)
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1293, in _make_tmp_path
    result = self._low_level_exec_command(conn, cmd, None, sudoable=False)
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1174, in _low_level_exec_command
    in_data=in_data)
  File "/usr/local/Cellar/ansible/1.9.4/libexec/lib/python2.7/site-packages/ansible/runner/connection_plugins/ssh.py", line 295, in exec_command
    vvv("EXEC %s" % ' '.join(ssh_cmd), host=self.host)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 20: ordinal not in range(128)

TASK: [jdk | JDK | Oracle JDK | Make sure openjdk is uninstalled] ************\* 
FATAL: no hosts matched or all hosts have already failed -- aborting

also unable to run limit block.
ansible-playbook -vvv --private-key=~/Desktop/key/p.pem -u ubuntu  kafka.yml --limit @/Users/laxmansingh/kafka.retry
ERROR: Specified --limit does not match any hosts

which python
/usr/local/bin/python

which ansible-playbook
/usr/local/bin/ansible-playbook

which ansible
/usr/local/bin/ansible

ansible --version
ansible 1.9.4
  configured module search path = None

laxmansingh$  export PYTHONPATH="/usr/local/lib/python2.7/site-packages"

Mac-Laxman:KafkaOnEC2 laxmansingh$ python
Python 2.7.11 (default, Jan 22 2016, 08:28:37) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.


but still failing with above mentioned error. any one has any suggestion.
