### ISSUE TITLE
package module is becoming less useful

### ISSUE THREAD

**Issue by opoplawski** [ansible/ansible#57415]
##### SUMMARY

We manage both Ubuntu and RedHat/Fedora systems from the same playbooks.  One of the tools that has been very helpful for us in this is the generic "package" module.  However, with the recent change to the yum lock timeout behavior with ansible 2.8, we are now required to set "lock_timeout" to avoid yum failing during the periodic (hourly) yum cache updates.  This then breaks using package with apt:

    Unsupported parameters for (apt) module: lock_timeout

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
package

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /export/home/orion-admin/ansible-boulder/ansible.cfg
  configured module search path = [u'/export/home/orion-admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr  8 2019, 14:44:40) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/export/home/orion-admin/ansible-boulder/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/export/home/orion-admin/ansible-boulder/ansible.cfg) = -C -o ControlMaster=auto -
DEFAULT_BECOME(/export/home/orion-admin/ansible-boulder/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/export/home/orion-admin/ansible-boulder/ansible.cfg) = [u'profile_tasks
DEFAULT_FORKS(/export/home/orion-admin/ansible-boulder/ansible.cfg) = 25
DEFAULT_GATHERING(/export/home/orion-admin/ansible-boulder/ansible.cfg) = smart
DEFAULT_HOST_LIST(/export/home/orion-admin/ansible-boulder/ansible.cfg) = [u'/export/home/orion-adm
DEFAULT_ROLES_PATH(/export/home/orion-admin/ansible-boulder/ansible.cfg) = [u'/export/home/orion-ad
DEFAULT_STRATEGY_PLUGIN_PATH(/export/home/orion-admin/ansible-boulder/ansible.cfg) = [u'/export/hom
DEFAULT_TIMEOUT(/export/home/orion-admin/ansible-boulder/ansible.cfg) = 20
PERSISTENT_CONNECT_TIMEOUT(/export/home/orion-admin/ansible-boulder/ansible.cfg) = 30
RETRY_FILES_ENABLED(/export/home/orion-admin/ansible-boulder/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Controller - EL7.  Targets - EL7, Fedora, Ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
- name: "Install ansible"
  package:
    name: ansible
    state: present
    lock_timeout: 120
```

##### EXPECTED RESULTS
ansible package is installed on all targets

##### ACTUAL RESULTS

```paste below
fatal: [ubuntu]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (apt) module: lock_timeout Supported parameters include: allow_unauthenticated, autoclean, autoremove, cache_valid_time, deb, default_release, dpkg_options, force, force_apt_get, install_recommends, only_upgrade, package, policy_rc_d, purge, state, update_cache, upgrade"}
```

**Comment by opoplawski** [comment]
If we could set the yum lock_timeout in ansible.cfg that would avoid this issue.

**Comment by opoplawski** [comment]
pie in the sky - package could filter out unknown parameters.  Would such a PR be considered?

**Comment by sivel** [comment]
Modules don't expose the params they accept in a way that `package` could know that dynamically.  Maintaining a list statically, isn't feasible.

We have actually just been discussing that `package` should restrict the params it accepts to the lowest common denominator, and only allow params that are globally accepted by all underlying modules.  However, that would likely cause a backwards incompatible change.

**Comment by opoplawski** [comment]
Unfortunately module_defaults does not work for yum invoked via package, see #57482 

As for exposing module argument parameters, it seems that that could be fixed by exporting the argument_specs in a consistent manner.

One of the great appeals of management software is being able paper over the differences between different operating systems.  If I'm going to have to write a bunch of:
```
- apt: name=pkg state=present
  when: ansible_os_family == 'Debian'

- yum: name=pkg state=present
  when: ansible_os_family == 'RedHat'
```
then ansible becomes a **lot** less appealing.
