### ISSUE TITLE
digitalocean module: add ssh_key_names option?

### ISSUE THREAD

**Issue by hyao** [ansible/ansible#5747]
I have the following play to create a droplet, and the deploy key is on DO already. However it's doesn't get added to the new droplet. I sshed into the droplet and saw there's an empty line in /root/.ssh/authorized_keys. Tried a couple of times with the same result.

Thanks,

``` yaml
- digital_ocean: >
      command=droplet
      name=ca4
      size_id=66                        
      region_id=3
      image_id=1505447
      virtio=yes
      ssh_key_ids=deploy
      state=present
      client_id={{ do_client_id }}
      api_key={{ do_api_key }}
      wait_timeout=500
```

**Comment by zimbatm** [comment]
The key id is not the same as the name. To find the ID in the web UI, go to the key management and inspect the edit button, 
![screen shot 2014-01-24 at 12 02 26](https://f.cloud.github.com/assets/3248/1994493/89d8dc30-84ef-11e3-94b5-6dea7bf445cf.png)

Alternatively you can define the key using ansible and then use the registered return to extract the id:

``` yaml
  - digital_ocean: >                                                          
      api_key={{ do_api_key }}                                                
      client_id={{ do_client_id }}                                            
      command=ssh                                                             
      name=home                                                               
      ssh_pub_key='{{ lookup("file", "~/.ssh/id_rsa.pub") }}'                 
      state=present                                                           
    register: my_key                                                          
  - digital_ocean: >                                                          
      api_key={{ do_api_key }}                                                
      client_id={{ do_client_id }}                                            
      command=droplet                                                         
      image_id={{ do_image }}                                                 
      name=home                                                               
      region_id={{ do_region }}                                               
      size_id={{ do_size }}                                                   
      ssh_key_ids={{ my_key.ssh_key.id }}                                     
      state=present                                                           
      unique_name=yes                                                         
      wait_timeout=500                                                        
```

**Comment by hyao** [comment]
Thank you very much for the answer!

Is it possible to add an ssh_key_names option, which would be much easier to use?

Thanks,

**Comment by zimbatm** [comment]
I agree, it would be great if a `ssh_keys` attribute could contain either names or ids. I'm sure if you submit a pull-request it will be accepted.

Maybe it's worth discussing it with digitalocean too, I don't know if their API supports this directly or if another round-trip has to be made to fetch the ids of the provided key names.

**Comment by hyao** [comment]
Looked at DO's api doc; it seems to return both id and name at the same time:

```
https://api.digitalocean.com/ssh_keys/?client_id=[your_client_id]&api_key=[your_api_key]
```

``` yaml
{
  "status": "OK",
  "ssh_keys": [
    {
      "id": 10,
      "name": "office-imac"
    },
    {
      "id": 11,
      "name": "macbook-air"
    }
  ]
}
```

**Comment by zimbatm** [comment]
The API to start new droplets expects the key id so you would first have to resolve the names to ids before issuing the request.

**Comment by zimbatm** [comment]
`https://api.digitalocean.com/droplets/new?client_id=[your_client_id]&api_key=[your_api_key]&name=[droplet_name]&size_id=[size_id]&image_id=[image_id]&region_id=[region_id]&ssh_key_ids=[ssh_key_id1],[ssh_key_id2]`
- ssh_key_ids: Optional, Numeric CSV, comma separated list of ssh_key_ids that you would like to be added to the server

**Comment by hyao** [comment]
That would mean an additional api call to get ssh_keys. I see, thanks.

**Comment by mpdehaan** [comment]
Sorry for late trawl through the queue here.

I'm not sure exactly where we should proceed here but I will say we are open to pull requests for upgrades.

Mostly we are focusing on EC2/Rackspace/OpenStack/etc in this area so patches from others to keep things like DO doing all the latest are always welcome.

If you would like to submit a pull request, please do, thanks!
