### ISSUE TITLE
Git failing when user's home directory doesn't exist

### ISSUE THREAD

**Issue by chrisblossom** [ansible/ansible#5750]
When using the git module with a user that doesn't have a home directory, such as www-data, the module will fail.

```
- name: Web_deploy | Pull sources from the repository.
  git: repo={{ item.git_repo }} dest=/webapps/{{ item.site }} version={{ item.git_branch }} key_file=/etc/ssh/github.rsa ssh_opts="-o StrictHostKeyChecking=no"
  when: item.git_repo is defined
  with_items: web_config
  sudo: yes
  sudo_user: www-data
```

```
msg: github.com has an unknown hostkey. Set accept_hostkey to True or manually add the hostkey prior to running the git module

FATAL: all hosts have already failed -- aborting
```

**Comment by eigood** [comment]
A similar thing happens if the $HOME actually _does_ exist, but .ssh does not.

I don't think the module should auto-vivify the full path; if $HOME doesn't exist, and accept_key=true, then the module must fail.  But, if $HOME exists, and .ssh does not, then create it.

**Comment by jctanner** [comment]
@chrisblossom @eigood the patch above should fix everything you have brought up. Please file new bugs if you find any issues. Thanks!
