### ISSUE TITLE
Allow su_user to be templated

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#5752]
Currently sudo_user allows templating, but su_user does not.  To bring them closer to feature parity, let's look at adding that functionality.

**Comment by sivel** [comment]
cc @angstwad

**Comment by eigood** [comment]
I've got this fixed locally, need to create a fork on github, and push it up.  It was _very_ simple.

**Comment by eigood** [comment]
Submitted PR #5754.

**Comment by jimi-c** [comment]
The above PR was merged, so this issue should be resolved. Thanks!

**Comment by eigood** [comment]
This merge was done incorrectly.  lib/ansible/runner/**init**.py, line 635 and 849 are incorrect.  How should I go about submitting that?

On 635, the self.su_user line should be deleted, it is handled earlier in the file, the same as as sudo_user.

**Comment by jimi-c** [comment]
Ahh, I was actually fixing another issue and probably changed that - there was a merge conflict when I merged my fix in so I assumed my branches version was correct. Just create a new branch and PR and I'll get it corrected.

**Comment by eigood** [comment]
Ok, I'll get to that tomorrow.
