### ISSUE TITLE
"Share" documentation between modules

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#5753]
With modules taking advantage of module_utils/{ec2,rax}.py there is a lot of duplicated documentation that has to be managed per module.  This is especially true of the rax modules.

Currently all rax modules, have documentation references to the following attributes:

```
    api_key
    credentials
    region
    username
```

The docs for these get copy/pasted into all new modules.  Additionally the 'notes' portion of the DOCUMENTATION is identical or should be identical between all rax modules.

I'm not sure if it possible, but I am wondering if we could find a way to not have to duplicate all of those docs.

Especially, as I have plans to add a bit more standard attributes for all rax modules that revolve around authentication.

Since currently we just open/read the module files and parse with ast I don't have an answer for this, and haven't dug into it deeply, but if there are any recommendations, I'd be happy to look into the required changes.

**Comment by mpdehaan** [comment]
Questions like this should be asked on the mailing list and not the bug tracker.

I do think they should be repeated though.
