### ISSUE TITLE
Unable to disable and enable yum repositories in one step using example provoded

### ISSUE THREAD

**Issue by KarieCook** [ansible/ansible#57619]
##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

**Comment by mkrizek** [comment]
Please create a new issue with information about what examples are incorrect or stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
