### ISSUE TITLE
Incorrect sector size for 4K (4096) disk

### ISSUE THREAD

**Issue by ciupicri** [ansible/ansible#5761]
Ansible reports that a [Hitachi HDS724040ALE640](http://www.hgst.com/tech/techlib.nsf/techdocs/3C330019E6ED04A48825797700626F0D/$file/DS7K4000_ds.pdf) disk has 512 bytes sectors, even they're really 4096 bytes (4K).

The output of the **setup** module is:

```
# ansible -v -i <(echo localhost) -c local -m setup '*'
    ...
    "sdd": {
        "holders": [],
        "host": "SATA controller: Intel Corporation 7 Series/C210 Series Chipset Family 6-port SATA Controller [AHCI mode] (rev 04)",
        "model": "Hitachi HDS72404",
        "partitions": {
            "sdd1": {
                "sectors": "7814035087",
                "sectorsize": 512,
                "size": "3.64 TB",
                "start": "2048"
            }
        }, 
        "removable": "0",
        "rotational": "1",
        "scheduler_mode": "cfq",
        "sectors": "7814037168",
        "sectorsize": "512",
        "size": "3.64 TB",
        "support_discard": "0",
        "vendor": "ATA"
    }
```

**fdisk** says something else:

```
Disk /dev/sdd: 3.7 TiB, 4000787030016 bytes, 7814037168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
```

I'm running kernel-3.12.8-300.fc20.x86_64 and `/sys/block/sdd/queue` looks like this:
- hw_sector_size = 512 (this is used by Ansible right now)
- logical_block_size = 512
- physical_block_size = 4096
- minimum_io_size = 4096
- optimal_io_size = 0

The files are explained in the [kernel documentation](https://www.kernel.org/doc/Documentation/block/queue-sysfs.txt):

> hw_sector_size (RO)
> This is the hardware sector size of the device, in bytes.
> 
> logical_block_size (RO)
> This is the logical block size of the device, in bytes.
> 
> physical_block_size (RO)
> This is the physical block size of device, in bytes.
> 
> minimum_io_size (RO)
> This is the smallest preferred io size reported by the device.
> 
> optimal_io_size (RO)
> This is the optimal io size reported by the device.

Also the [source code](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/block/blk-sysfs.c#n359) from `block/blk-sysfs.c`:

```
static struct queue_sysfs_entry queue_hw_sector_size_entry = {
    .attr = {.name = "hw_sector_size", .mode = S_IRUGO },
    .show = queue_logical_block_size_show,
};
```

shows that **hw_sector_size** is probably a compatibility file.

Therefore I think that Ansible should switch from **hw_sector_size** to **physical_block_size**.

**Comment by jkramarz** [comment]
@ciupicri do you know when physical_block_size file has been introduced? As far as I know, it's there for at last 5 years, but I'm wondering if fallback to hw_sector_size should be implemented there if physical_block_size is not present.

**Comment by jimi-c** [comment]
I've gone ahead and merged the above PR in, as it does seem sane. If you'd like to add a safety fallback for that, just send us another PR. Thanks!

**Comment by ciupicri** [comment]
It seems that is was added by [commit c72758f33784e5e2a1a4bb9421ef3e6de8f9fcf3](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=c72758f33784e5e2a1a4bb9421ef3e6de8f9fcf3) in May 2009.

I have a virtual machine running Scientific Linux 6.1 (RHEL 6.1 compatible) with kernel 2.6.32-431.17.1.el6.i686 and it has the file `/sys/block/vda/queue/physical_block_size`.

**Comment by jkramarz** [comment]
Thank you @jimi-c for merging my previous PR. I've added fallback in #7771 , because I can't test previous change on RHEL 5.
