### ISSUE TITLE
How to run only one included yml tasks file?

### ISSUE THREAD

**Issue by rightaway** [ansible/ansible#5763]
I'm running "ansible-playbook roles/myrole/tasks/myincludedfile.yml -i inventory -c local -vv", where the yml file contains only:

```
name: Install packages
sudo: yes
apt: pkg=mypackage state=present
```

And I get an error message "ERROR: apt is not a legal parameter in an Ansible Playbook". I'm using a recent ansible, 1.4.3.

Is it not possible to run one included tasks file like this directly? I don't want to run the entire set of ansible playbooks referred to in my top-level suite.yml, because it takes too long and I'm just doing some quick development work.

I also don't want to annotate all tasks in an included tasks file with the same tag in order to run just that tag (I'd think separating these tasks into a its own file would be enough to run just those tasks).

**Comment by bcoca** [comment]
you cannot run tasks outside of a play (which maps hosts to tasks).

You can run the same tasks from different plays using includes, so you just
need to create a small play that does this.

**Comment by mpdehaan** [comment]
Hi, please ask questions on the mailing list and keep the bug tracker for bugs and pull requests and the like, please.

Look at CONTRIBUTING.md for mailing list info, thanks!
