### ISSUE TITLE
fix slow ssh connections on FreeBSD SMP

### ISSUE THREAD

**Issue by lifanov** [ansible/ansible#5768]
This reduces single ssh connection overhead from ~2.5 seconds to ~0.3 on FreeBSD SMP machines, which was a regression since 1.4.1

```
diff --git a/lib/ansible/runner/connection_plugins/ssh.py b/lib/ansible/runner/connection_plugins/ssh.py
index 3df297a..11751e1 100644
--- a/lib/ansible/runner/connection_plugins/ssh.py
+++ b/lib/ansible/runner/connection_plugins/ssh.py
@@ -292,13 +292,13 @@ class Connection(object):
                 stderr += dat
                 if dat == '':
                     rpipes.remove(p.stderr)
+            # Calling wait while there are still pipes to read can cause a lock
+            if not rpipes and p.poll() == None:
+                p.wait()
             # only break out if we've emptied the pipes, or there is nothing to
             # read from and the process has finished.
             if (not rpipes or not rfd) and p.poll() is not None:
                 break
-            # Calling wait while there are still pipes to read can cause a lock
-            elif not rpipes and p.poll() == None:
-                p.wait()
         stdin.close() # close stdin after we read from stdout (see also issue #848)

         if C.HOST_KEY_CHECKING and not_in_host_file:
```

**Comment by mpdehaan** [comment]
In the future, so if you would like to submit a patch, please submit this as a github pull request.

I'm curious why this isn't causing issues on other platforms but there's also another variant of this out here on GitHub, one sec...

**Comment by mpdehaan** [comment]
I'm going to close this one and link it to #5572 where we can still see the patch info there.

Thanks!

**Comment by lifanov** [comment]
On 2014-01-25 11:44, Michael DeHaan wrote: 

> In the future, so if you would like to submit a patch, please submit this as a github pull request. 
> 
> I'm curious why this isn't causing issues on other platforms but there's also another variant of this out here on GitHub, one sec... 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

Thanks! I will submit a pull request next time. I'm still new to github
way of doing things. 

## Links:

[1] https://github.com/ansible/ansible/issues/5768#issuecomment-33293265
