### ISSUE TITLE
Upgrade docs build to Sphinx 2.x

### ISSUE THREAD

**Issue by acozine** [ansible/ansible#57709]
##### SUMMARY
Sphinx 2.0.0 came out on March 28, 2019. We'd like to upgrade. Currently running `make webdocs` on Sphinx 2.x fails with:

`RecursionError: maximum recursion depth exceeded while calling a Python object`

The upgrade may also break dependencies. Be sure to test the 404 page generation in particular. 

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
docs.ansible.com

##### ANSIBLE VERSION
2.9

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

**Comment by acozine** [comment]
If you've found this issue because you've been trying to build the docs and are getting that error message, here's the workaround to get versions that work for the Ansible docs build:

- uninstall Sphinx 2.x with `pip uninstall sphinx` 
- install version 1.8.5 with `pip install sphinx==1.8.5`

**Comment by acozine** [comment]
Tested today with Sphinx 2.1.2, which avoids the error I reported above. It does generate a few new warnings, but not many and they are all caused by the same thing:
```
ansible/docs/docsite/rst/user_guide/windows_dsc.rst:372: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
ansible/docs/docsite/rst/user_guide/windows_setup.rst:199: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
ansible/docs/docsite/rst/user_guide/windows_setup.rst:246: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
ansible/docs/docsite/rst/user_guide/windows_setup.rst:345: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
ansible/docs/docsite/rst/user_guide/windows_setup.rst:357: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
ansible/docs/docsite/rst/user_guide/windows_setup.rst:380: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
ansible/docs/docsite/rst/user_guide/windows_winrm.rst:72: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
ansible/docs/docsite/rst/user_guide/windows_winrm.rst:94: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
ansible/docs/docsite/rst/user_guide/windows_winrm.rst:220: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
ansible/docs/docsite/rst/user_guide/windows_winrm.rst:520: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
ansible/docs/docsite/rst/user_guide/windows_winrm.rst:572: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
```

**Comment by samccann** [comment]
A note that while this works today with local builds, we do not currently publish the docs to the website with Sphinx 2.x  We are tied to Sphinx 1.7.9 via this:

https://github.com/ansible/ansible/blob/devel/test/lib/ansible_test/_data/requirements/constraints.txt#L9

This is due to a limitation in rstcheck.  While the 3.3.1 version of rstcheck supports Sphinx 1.8 and greater now, it is still not testing/supporting Sphinx 2.x according to this issue:
https://github.com/myint/rstcheck/issues/58
