### ISSUE TITLE
Add force Switch for lvol

### ISSUE THREAD

**Issue by encbladexp** [ansible/ansible#5774]
lvchange/lvreduce requires a --force switch to make Logical Volumes smaller. Currently ansible could shrink manual resized volumes and destroy filesystems on this volumes.

A force: true Option would require that an Admin know what he does, even if someone makes a volume "by hand" bigger than with ansible created in the past.

Ansible modules should never run things with --force if not requested so by the user/admin. Most developers had good reasons for an --force switch ;)

**Comment by mpdehaan** [comment]
This sounds reasonable, is this something you would like to work on?

**Comment by encbladexp** [comment]
I made a Pull Request for this Issue: https://github.com/ansible/ansible/pull/5775

**Comment by mpdehaan** [comment]
I'm closing this ticket as we have the linked pull request above to track this.  Thank you!
