### ISSUE TITLE
More granular output control

### ISSUE THREAD

**Issue by burner1024** [ansible/ansible#5777]
1) I wish there was a "quiet" or "silent" option for running ansible-playbook. The default output is too verbose. As long as everything is ok (no errors), I don't care what exactly was performed. Just "Play recap" is enough.
It would be nice if it also removed the extra newlines.

2) on the contrary, when there's (for example) a connection error, I have to re-run the playbook adding "-vvvv" to debug it. It doesn't make much sense, why make the user go and perform manual actions? if there's something wrong, let the user debug it, print the whole output.

**Comment by mpdehaan** [comment]
This is unlikely to happen for (1)

2 should probably be brought up as a seperate ticket, I'm curious what kind of error you are having that would be connection related? 

In any event, let's discuss this on the list if possible?

Thanks!
