### ISSUE TITLE
extra-vars on command line does not work for complex variables for ansible-playbook

### ISSUE THREAD

**Issue by yauh** [ansible/ansible#5780]
I have a role that has a complex variable defined in defaults/main.yml:

```
jenkins:
   port: 8080
```

Now I wish to override this from the command line using `--extra-vars="jenkins.port=8088"` when executing the playbook.

This does not work, even with `export ANSIBLE_HASH_BEHAVIOUR=merge` applied for the shell executing ansible-playbook. The expected behaviour would be to be able to overwrite also complex vars from the command line.

**Comment by sivel** [comment]
You will need to use something like JSON passed to --extra-vars to get the functionality you are looking for.

You are literally creating a variable called "jenkins.port"

Something like:

```
--extra-vars='{jenkins: {port: 8088}}'
```

Keep in mind that this is a issue tracker.  For questions, you should stop by the mailing lists as outlined in contributing.md

**Comment by yauh** [comment]
Hi Matt, thanks, it works as expected.

I didn't mean to use the issue tracker as a support system, been discussing this issue with benno on IRC for a while and we agreed it would be best to open an issue.
