### ISSUE TITLE
pip reports success even if executable doesn't exist

### ISSUE THREAD

**Issue by jimrybarski** [ansible/ansible#5781]
On my server the only Python 3 pip executable is `pip3`, not `pip-3.3`. I mistakenly used `pip-3.3` in my playbook, but there was no error. In fact, it installed the package for Python 2.7, which was not expected at all. I would have expected that the playbook would throw an error and quit instead of silently defaulting to 2.7.

Excerpt from my playbook:

```
- name: rabbitmq | Install Python 3.3 packages
  pip: name=rabbitpy executable=pip-3.3
```

Output:

```
TASK: [rabbitmq | rabbitmq | Install Python 3.3 packages] ********************* 
changed: [23.253.87.140]
```

Going into python3.3:

```
$ python3.3
Python 3.3.2+ (default, Oct  9 2013, 14:50:09) 
[GCC 4.8.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rabbitpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'rabbitpy'
```

**Comment by risaacson** [comment]
A fix in in for this that instead of thinking it is smarter will fail the module if an executable is defined but not found on the system.

The fix will be packaged as of 1.5.
