### ISSUE TITLE
Plugins not in any package

### ISSUE THREAD

**Issue by DavidJFelix** [ansible/ansible#5786]
Neither the apt ppa nor the pip package come with the plugins and there is no package for the plugins in pip or in the ppa. I have not tested other packaged versions. This makes the EC2 plugin unusable out of the box unless I build from source.

**Comment by jctanner** [comment]
@DavidJFelix I presume this issue is related to https://groups.google.com/forum/#!topic/ansible-project/jjuapMOLkr8  ?

**Comment by DavidJFelix** [comment]
@jctanner it seems to be related. IMO it's an issue whether or not you agree with the plugins being part of the package.
- You believe the plugins should be a part of the package: clearly they are not, and need to be added.
- You believe the plugins should not be a part of the package: the documentation makes no mention of this and needs to be changed to accommodate people who don't install from source.

**Comment by jctanner** [comment]
@DavidJFelix any suggestions on altering setup.py or MANIFEST.in to make this work for distro packages, pip, and virtualenvs ?

**Comment by DavidJFelix** [comment]
@jctanner My personal opinion is that it should come "batteries included", at least in the case of plugins that are already written and reside in this repository. For MANIFEST.in wouldn't a recursive-include of plugins/ be enough? For the Debian, I'd say the current plugins belong in /usr/local/lib/python2.7/site-packages/ansible/plugins/ or /usr/lib/pymodules/python2.7/ansible/plugins/.

On the other hand, a modification to docsite/rst/intro_dynamic_inventory.rst to mention more explicitly that ec2.py is not provided (note -- running `locate ec2.py` will find module_utils/ec2.py, which **is** included by packaging but is not the same file). Some other docs may require modification too, but I'm not sure.

**Comment by mpdehaan** [comment]
I'm fine with having an examples dir but the question of what to do with people doing local installs or virtualenv has not yet been resolved.

I strongly believe this should not be in a python language dir, but belongs in something like /usr/share/

**Comment by DavidJFelix** [comment]
What directories does virtualenv create for pip to use?

My thought behind putting it in the python language dir is that's where the module_utils/ec2.py helper is already.

**Comment by mpdehaan** [comment]
Well, that's actually part of the package.

**Comment by jctanner** [comment]
@DavidJFelix i think this needs to be a broader discussion. Let's continue figuring this out on the mailing list:

https://groups.google.com/forum/#!topic/ansible-project/jjuapMOLkr8
