### ISSUE TITLE
Set manage_dir to false when path is specified in the authorized_keys module and allow mode/owner

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#5796]
First problem with this module is that `manage_dir` is by default set to `True`, but if you specify an alternative `path` it would probably be safer to set `manage_dir` to false in that case, so that it doesn't lock anyone out.

I know there is this example in the documentation about this:

```
# Using alternate directory locations:
- authorized_key: user=charlie
                  key="{{ lookup('file', '/home/charlie/.ssh/id_rsa.pub') }}"
                  path='/etc/ssh/authorized_keys/charlie'
                  manage_dir=no
```

but if you miss the example, set a central directory for authorized_keys like in the example and don't set `manager_dir=no` you will probably lock yourself out of SSH. The documentation should either be updated to add a notices for the `path` argument, or the `manager_dir`should automatically be set to no if `path` is set.

The second problem with this module is that when it creates an authorized_keys file it sets the owner of the file to the user for which account that file will be used. This is bad if you would like to disallow the users to edit their authorized_keys because of security, which makes this module useless in that situations. It would be great if the module supported the `owner`, `group` and `mode` arguments, so that we could set the permissions/owner manually.

If you like these two ideas, I would like to update this module and its documentation.

**Comment by jctanner** [comment]
@kustodian i don't like the idea of manage_dir having a different default value for different contexts. I do agree that it would be nice to put some sort of warning in the parameter documentation.

The ownership could be handled as you described, but I would prefer the defaults to be as they are now.

If you would like to tackle these, feel free to submit a PR.

**Comment by kustodian** [comment]
Thanks for feedback and I have to say that I agree with you about having different meanings for different context is bad. I will see about the documentation part and will probably add the mode/owner/group options to the modules later on.

**Comment by ojtibi** [comment]
Hello, I'm having a difficult time understanding what `manage_dir` really does.
- What are the steps that the `authorized_key` module does to manage a directory?
- If I configured my SSH daemon to read files from another directory, how does `manage_dir` affect the operation?
- If I leave the SSH options at default (SSH daemon reads .ssh/authorized_keys in home directory of the user), what's the difference of turning `manage_dir` on or off?

**Comment by kustodian** [comment]
Asking a question in a closed issue is not the best way to ask for help, since no one except those who are following this issue will reply to this issue. It is better to ask on the forum https://groups.google.com/forum/#!forum/ansible-project

Anyway when `managed_dir` is `True` the owner of the directory in which the authorized_keys is will set to the user for which you are setting the authorized_keys and it's permissions will be set to 700.
