### ISSUE TITLE
Variables not passed on playbook include?

### ISSUE THREAD

**Issue by dekked** [ansible/ansible#5801]
Given these two files:

site.yml

```

---

- include: site2.yml a_variable="My Name"
```

site2.yml

```

---

- name: test
  hosts: all
  connection: local

  vars:
    - another_variable: "{{ a_variable }} Second"

  tasks:

    - debug: msg={{ another_variable }}
```

The following command fails

```
ansible-playbook -i 127.0.0.1, site.yml
```

```
fatal: [127.0.0.1] => One or more undefined variables: 'a_variable' is undefined
```

Why is that? When using include, I am clearly passing the variable as I should.

This, however, works fine:

```
ansible-playbook -i 127.0.0.1, site.yml -e "a_variable=something"
```

Is this a bug? or am I assuming something wrong?

**Comment by jimi-c** [comment]
This should be resolved, please let us know if you run into any further issues. Thanks!

**Comment by wolfgangmeyers** [comment]
I'm seeing this behavior, and I just updated to ansible 1.8.2

**Comment by jamesmoriarty** [comment]
@jimi-c +1

**Comment by dragoscirjan** [comment]
Hello there.
Has this issue been fixed ?

**Comment by wolfgangmeyers** [comment]
I'm not sure I could reproduce the issue I had before. I think it was resolved when we switched to using roles.

**Comment by dragoscirjan** [comment]
I'm experiencing this issue within a role I wrote.

I have tasks/main.yml  which includes tasks/conf.yml .

When calling this role from a playbook, main.yml has the variables I'm giving within the playbook, while conf.yml is has the default variables from the role itself.

**Comment by dragoscirjan** [comment]
I can confirm a new issue. When using include_vars in tasks/main.yml

within the include declarations which will follow in main.yml the variables declared in playbook when calling the role are ignored.

I will post a new issue.

**Comment by trompx** [comment]
Also seeing this with ansible 2.0.2-1

I have a bash script in which I pass variables with extra-vars
`ansible-playbook -i myinv myplay.yml --extra-vars "var1=test1"`

In myplay.yml, I include another global playbook with the variables passed with extra vars, and I want to hardcode one variable directly in the playbook.
```
- include: otherplay.yml 
    var1={{ var1 }}
    var2='test' OR var2="test" OR var2=test --> all fails
```

If instead I do:
`ansible-playbook -i myinv myplay.yml --extra-vars "var1=test var2=test2"`
and
```
- include: otherplay.yml 
    var1={{ var1 }}
    var2={{ var2 }}
```
That works... but I really need to hardcode the second one.

**Comment by trompx** [comment]
Also seeing this with ansible 2.0.2-1

I have a bash script in which I pass variables with extra-vars
`ansible-playbook -i myinv myplay.yml --extra-vars "var1=test1"`

In myplay.yml, I include another global playbook with the variables passed with extra vars, and I want to hardcode one variable directly in the playbook.

```
- include: otherplay.yml 
    var1={{ var1 }}
    var2='test' OR var2="test" OR var2=test --> all fails
```

If instead I do:
`ansible-playbook -i myinv myplay.yml --extra-vars "var1=test var2=test2"`
and

```
- include: otherplay.yml 
    var1={{ var1 }}
    var2={{ var2 }}
```

OR

```
- include: otherplay.yml 
    var1={{ var1 }}
```

That works... but I really need to hardcode the second one.
