### ISSUE TITLE
pip install --user fails /usr/share/ansible permission quandary

### ISSUE THREAD

**Issue by hihellobolke** [ansible/ansible#5814]
When installing Ansible as a non root installation for Ansible it still likes to write to path **/usr/share/ansible** ... Even when specifying `--user` and setting `$PYTHONUSERBASE` it still likes to write to /usr/share. 

> running install_data
> creating /usr/share/ansible
> 
> error: could not create '/usr/share/ansible': Permission denied

Suggest to write to `$PYTHONUSERBASE/share/ansible` if `/usr/share/ansible` fails

**Comment by jctanner** [comment]
@hihellobolke is this something you could write a pull request for?

**Comment by sivel** [comment]
For historical reference from another issue relating to this see #4831

**Comment by ghost** [comment]
I'd like to see this fixed, as I usually use a $HOME-installed Python.  I can work on the code, but would like some guidance.  If the installer puts things into a location other than `/usr/share/ansible`, what other portions of the codebase need to change so they aren't _looking_ just in `/usr/share/ansible` for those items?

**Comment by mpdehaan** [comment]
Yep this is frequently discussed, we are likely moving to setuptools in the future -- for other reasons which will help rectify  this and enable pull requests of this nature.
