### ISSUE TITLE
Bug? "register" should be performed AFTER "when" is evaluated

### ISSUE THREAD

**Issue by dekked** [ansible/ansible#5817]
Given the following playbook

```

---

- name: test
  hosts: all
  connection: local

  tasks:

    - command: echo "Hello"
      register: my_var
      when: extra is defined

    - command: echo "Goodbye"
      register: my_var
      when: extra is not defined

    - debug: msg={{ my_var.stdout }}
```

When invoked like this `ansible-playbook -i 127.0.0.1, site3.yml` it prints "Goodbye" as expected.

When passing "extra", I would expect the last task to print "Hello". However, this is what happens:

```
ansible-playbook -i 127.0.0.1, site3.yml -e "extra=yes"
```

```
 ___________________________________
< TASK: debug msg={{my_var.stdout}} >
 -----------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


fatal: [127.0.0.1] => One or more undefined variables: 'dict object' has no attribute 'stdout'

FATAL: all hosts have already failed -- aborting
```

In general, I would expect the "when" condition to be evaluated before anything and short-circuit if False, not continuing the parse looking for undefined variables, performing "register", etc.

**Comment by mpdehaan** [comment]
This is not the case because the value may be different for different hosts.

Since this is a question and not a bug report, perhaps open a thread on ansible-project if you have further questions.

Thanks!
