### ISSUE TITLE
implicit localhost plays fail with host not found: localhost

### ISSUE THREAD

**Issue by omgjlk** [ansible/ansible#5820]
This is with devel as of 61d283e2ad58916d640b129cdd0b1ef866bcb332

```
$ cat test.yaml
- name: derp
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: derp
      command: echo

$ ansible-playbook -i foo.com, test.yaml -vv

PLAY [derp] *******************************************************************
ERROR: host not found: localhost

$ ansible-playbook -i foo.com, test.yaml -vv --list-hosts

playbook: test.yaml

  play #1 (derp): host count=1
    localhost
```

When I did some quick digging it appears to be a problem somewhere in attempting to insert variable data. I will do some more digging, but wanted to get the simple reproducer logged here.

**Comment by omgjlk** [comment]
Duplicated with devel as of 48c477ffc8e0f0bd8ec7672a00b05bc818a87fa6 too.

**Comment by sivel** [comment]
One thing I noticed this morning, if your inventory file or script is empty, you get a message stating that the inventory list returned no results.

In my case I was using an inventory script, I had no existing inventory but was about to build several servers targeting localhost in my initial play.

This might be deserving of another issue, just adding it here for visibility for the time being.

**Comment by mpdehaan** [comment]
@sivel -- So implicit localhost is a feature in the above, so let's not mix these two issues up.   Delegating to hosts without having localhost in inventory makes it easy to configure localhost without it being in the all gorup.

**Comment by mpdehaan** [comment]
@jlk -- It seems to me that this is saying implicit localhost (new feature) doesn't work with -i "foo," syntax, so it's a new feature that doesn't exist for -i's host hack (undocumented feature BTW), rather than a regression.

**Comment by jimi-c** [comment]
@j2sol After some discussion, I believe the fact that this "worked" in ansible < 1.5 was a bug. I say "worked", because it simply reports no hosts were matched (which I believe is the incorrect result). 

Since the `-i host,` syntax sets the inventory in a pretty static way, the fact that localhost is not found is the correct result and it should be specified as `-i localhost,foo.com` when running your example playbook.

**Comment by omgjlk** [comment]
@jimi-c Hrm, so I used the -i hack to make things really simple, but in my production case I'm using a dynamic inventory. Perhaps I misunderstood, but I thought I could drop localhost from being explicitly added to my dynamic inventory and enjoy the implicit addition feature.

When I have localhost in my inventory, I then have to explicitly exclude it from host: listings that include all, as localhost is being lumped into all. That's the big thing I was hoping to avoid, remembering to exclude localhost.

**Comment by jimi-c** [comment]
@j2sol hrm yeah, it seems like it's not just with the -i host, syntax:

<pre>
# ansible-playbook -i /etc/ansible/ec2.py ~/testing/test_5820.yml -vv
ERROR: provided hosts list is empty
</pre>

I'll keep looking into this.

**Comment by jimi-c** [comment]
The above patch fixes the issue for me. I believe the ec2 issue above was simply that I didn't have any hosts on ec2, when I used rax.py (where we have hosts) I got the same result as using `-i host,` 

Let me know if you have any further problems with this. Thanks!

**Comment by sanear** [comment]
I'm still seeing this behavior with a fresh homebrew install of v. 1.8.2. Did the fix not make this release?
