### ISSUE TITLE
Changes to git module require Python 2.6

### ISSUE THREAD

**Issue by mrbanzai** [ansible/ansible#5822]
The installation guide currently lists Python 2.4 as a requirement for the managed nodes, but the recent changes to the `git` module in 18050d50 mandate at least Python 2.6, specifically using `NamedTemporaryFile` with the `delete` parameter.

**Comment by jctanner** [comment]
@mrbanzai thanks for the report. I can take a look into fixing this for py24, but if you already know of a way to fix this, please submit a pull request.

**Comment by mpdehaan** [comment]
merged the above, thanks
