### ISSUE TITLE
add option to copy : do nothing when hash of src and dst are equal

### ISSUE THREAD

**Issue by max-l** [ansible/ansible#5824]
It would be nice if copy had an option to avoid 
the file transfer when a hash of src and dest are equal
- name: copy huge file
  copy: src=./hugeFile dest=aDir

ansible version :  1.4.3

client host : 
 Linux max-ubuntu 3.8.0-27-generic #40-Ubuntu SMP Tue Jul 9 00:17:05 UTC 2013 x86_64 x86_64  x86_64 GNU/Linux

server host : 
 Linux cogol 3.8.0-29-generic #42~precise1-Ubuntu SMP Wed Aug 14 16:19:23 UTC 2013 x86_64  x86_64 x86_64 GNU/Linux

**Comment by bcoca** [comment]
er ... i believe this IS how it is supposed to behave.

I will look at code soon (in transit), in the meantime, please add ansible
version, OSs involved and a test case as per
https://github.com/ansible/ansible/blob/devel/CONTRIBUTING.md

**Comment by max-l** [comment]
Wow, that's an awesome response time ! 

It turns out that in my case I was using ziped files, and zip will add time info of files. 

md5sum returns different values for the same directory compressed twice

does ansible use md5sum internally ? 

If ansible does this check it would be nice to document it : http://docs.ansible.com/copy_module.html

**Comment by bcoca** [comment]
Yes, it uses md5 hashing (different programs depending on the OS).

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by max-l** [comment]
ok, just tested it and it does work, I still think it should be documented, you guys need to brag about your nice features  ;-)

**Comment by bcoca** [comment]
the docs are part of the repo, they accept Pull Requests for those the same
as for code.

**Comment by jctanner** [comment]
@max-l it sounds like this was a non-issue. I'm going to go ahead and close it.

**Comment by max-l** [comment]
Yes it can be closed, I sent a pull request to document this behavior https://github.com/ansible/ansible/pull/5833
