### ISSUE TITLE
Sporadic errors on very long command outputs

### ISSUE THREAD

**Issue by lukyanov** [ansible/ansible#5832]
Reproducible on the last devel branch (086f879df9).

Sometimes when the output of a command is very long, ansible reports a error "failed to parse json".

Here is the full output:
https://gist.github.com/lukyanov/8711630

The same could happen when gathering facts.

I'm using transport 'ssh'.

Ansible 1.4.4 doesn't seem to have such an issue.

**Comment by jctanner** [comment]
@lukyanov can you do me a favor and revert commit ID fe091ec00d2c646cffbc2e916e89c04febb24426 in your checkout and retest?

```
git revert -m1 fe091ec00d2c646cffbc2e916e89c04febb24426
```

**Comment by lukyanov** [comment]
Reverted. It works. No more errors detected.
But it now looks very slow.

**Comment by jctanner** [comment]
@lukyanov ok, we are going to go with correctness over speed here. fe091ec00d2c646cffbc2e916e89c04febb24426 has been reverted and we can try to revisit it later.

**Comment by lberruti** [comment]
I can reproduce systematically this error by reducing the os.read buffer (e.g. from 9000 to 9).
I think that happens when the process is finished and there are more than 'buffer_size' bytes to read.
One solution could be this:

``` patch
             if p.stdout in rfd:
-                stdout += os.read(p.stdout.fileno(), 9000)
+                stdout += p.stdout.read() if process_over else os.read(p.stdout.fileno(), 9000)
             if p.stderr in rfd:
-                stderr += os.read(p.stderr.fileno(), 9000)
+                stderr += p.stderr.read() if process_over else os.read(p.stderr.fileno(), 9000)
             if process_over:
                 break
```

@lukyanov, can you check this one inside your environment?
