### ISSUE TITLE
synchronize module tries to rsync to localhost when remote is a VM running in localhost

### ISSUE THREAD

**Issue by mtpereira** [ansible/ansible#5834]
Hello,

I'm trying to use synchronize module to rsync files from my localhost to a VM running on my localhost, with ssh on a different port than 22. I get a destination error (no such file or directory) on an absolute path.

This is the output from a -vvvv for ansible 1.4.4: https://gist.github.com/mtpereira/8714558

This is the output from a -vvvv for ansible devel: https://gist.github.com/mtpereira/8714590

In the first case, ssh port is not taken into account. In the second case it is but it still fails.

Here are the relevant parts of the playbook: https://gist.github.com/mtpereira/8714618
The inventory file has the following contents:

```

ansible-prm ansible_ssh_host=127.0.0.1 ansible_ssh_port=2222
```

This has been discussed on #ansible with @jctanner .

Thank you!

**Comment by jctanner** [comment]
@please retest with 9ce46e5f41d6017f3f12780c97705d103e759dd3 or higher. If the issue still remains we can reopen this ticket or a new one.

**Comment by ffledgling** [comment]
Looks like this was reintroduced with one of the newer ansible releases as seen here: https://github.com/ansible/ansible-modules-core/issues/5385
