### ISSUE TITLE
feature request: ansible-playbook <playbook> --list-tags

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#5838]
similar functionality as e.g. --list-tasks but for tags

**Comment by mpdehaan** [comment]
See comments on https://github.com/ansible/ansible/pull/3677 -- first the listing logic must use playbook code then we will entertain pull requests.

You can specify an invalid tag and see what tags are available.

**Comment by resmo** [comment]
what a hack :) this is exactly what I wanted. 

Couldn't we have a more user friendly way to show the list, e.g. maybe "--tags" without argument?

```
ansible-playbook playbooks/common.yml --tags 
ansible-playbook: error: --tags option requires an argument 
possible values: configuration,package,pubkeys,service
```
