### ISSUE TITLE
Ansible 2.8.1 ignores inventory setting in ansible.cfg

### ISSUE THREAD

**Issue by jimbarlow** [ansible/ansible#58477]
##### SUMMARY

Unlike previous versions, when a local ansible.cfg file is used to overwrite the inventory file location, it is not read by ansible

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
2.8.1
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Fedora 30 and RHEL 7.6

##### STEPS TO REPRODUCE

create an ansible.cfg in the current directory
create an inventory in that directory
cat ansible.cfg
[default]
inventory = ./inventory

```yaml
ansible all -m ping
```

##### EXPECTED RESULTS

I expect the inventory file specified in the local ansible.cfg to be used

##### ACTUAL RESULTS

```paste below
[jbarlow@localhost ~]$ ansible all -m ping -vvv
ansible 2.8.1
  config file = ./ansible.cfg
  configured module search path = ['/home/jbarlow/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, May 11 2019, 00:38:04) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
Using /home/jbarlow/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: provided hosts list is empty, only localhost is available. Note
that the implicit localhost does not match 'all'

```

**Comment by s-hertel** [comment]
I think you have a typo. Can you try with `[defaults]` not `[default]`?

**Comment by s-hertel** [comment]
needs_info

**Comment by Akasurde** [comment]
@jimbarlow I agree with @s-hertel that you have typo in your ansible.cfg. Change `[default]` to `[defaults]`. Thanks.

**Comment by mkrizek** [comment]
Closing as per above.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
