### ISSUE TITLE
Is dynamic compilation alllowed in ReactJS ?

### ISSUE THREAD

**Issue by PRASHANT1104** [ansible/ansible#58499]
So , as of now what i know is if i use dynamic import , react creates a context chunk and when you require the files/components ,it downloads it then . but say i have a syntax error in one of the files i want to import , although the main app compiles , i get a syntax error warning in my terminal about that component , which means it is compiling all the files in the directory of dynamic import , otherwise how would it know about the syntax error ?

so my concern is , is it possible to compile those files on demand (at run-time) not build time 
?

**Comment by Akasurde** [comment]
@PRASHANT1104 This project is related to Ansible and not React.js. Please use correct Organization and repo to file issue. Thanks.
