### ISSUE TITLE
Some modules fail on Python 2.5

### ISSUE THREAD

**Issue by timurb** [ansible/ansible#5852]
When I manage a box with Python 2.5 installed some modules fail with the following error:

```
failed: [foobar.com] => {"failed": true, "item": "", "parsed": false}
invalid output was: /root/.ansible/tmp/ansible-1391358428.72-277252128095684/apt_repository:179: Warning: 'with' will become a reserved keyword in Python 2.6
  File "/root/.ansible/tmp/ansible-1391358428.72-277252128095684/apt_repository", line 179
    with open(file, 'r') as f:
            ^
SyntaxError: invalid syntax
```

This is caused by "with"-statement not yet fully supported in Python 2.5.

The simplest way would be to add the following line to all files that use "with" statements:

``` python
from __future__ import with_statement
```

See http://stackoverflow.com/questions/7918745/python-2-5-2-what-was-instead-of-with-statement for reference.

Alternatively we could do that only for modules so that only managed boxes would support Python 2.5

**Comment by timurb** [comment]
If you don't mind I'll add the error similar to this one here:

```
failed: [foobar.com] => {"failed": true, "item": "", "parsed": false}
invalid output was:   File "/tmp/ansible-tmp-1391361695.47-175323675669122/apt_repository", line 209
    except IOError as err:
                    ^
SyntaxError: invalid syntax
```

This is fixed by replacing the construct into `except IOError, err:`.
In fact I see the case in some of the providers (yum, etc).

**Comment by mpdehaan** [comment]
most of the above should be resolved now, if there are other problems that exist please send pull requests. 

Thanks!
