### ISSUE TITLE
ini_file should only change what was specified and nothing more

### ISSUE THREAD

**Issue by rightaway** [ansible/ansible#5860]
In addition to the other changes ini_file makes, like removing comments, reordering entries within a section, adding spaces around the '=' (as mentioned in https://github.com/ansible/ansible/issues/5688), is there any reason why ini_file couldn't be changed to make as minimal changes as possible?

Other changes it makes are making keys lowercase and removing blank quotation marks ("") as values.

```
KEY1 = value1
key2 = ""
```

to

```
key1 = value1
key2 = 
```

ini_file won't be used in our infrastructure because anything in a configuration management system that changes more than what we've specifically asked it to change (even if those other changes are documented) is doing too much and can cause problems that we'll have to track down later whenever they decide to manifest in the application. And it's problems like these that provisioning tools are trying to solve in the first place. ini_file could be dangerous in its current form for applications that may not be using ini files in standard ways. For our infrastructure, ini_file in its current form is unsuitable for production use. (Which is a shame, because we are managing multiple ini files.)

Some applications require case-sensitive keys (like just as an example when defining keyboard shortcuts as the keys where it makes a difference between 'a' and 'A'). Others may complain if their expected "" becomes a blank instead.

ini_file should make only the changes that were specified (and absolutely nothing more...no reordering, removing comments, etc), like the lineinfile module. In fact, I've been using lineinfile for our ini files for this very reason, searching by just the key. But of course this isn't good either, as it will cause problems if there is the same key in 2 different sections, like:

```
[section1]
key1=value1

[section2]
key1=value2
```

I know these changes that Ansible makes to ini_files _shouldn't_ make a difference, but isn't it better for Ansible to make only the changes that are needed rather than intrusively changing too much? Who knows if some quirk in the application doesn't follow ini file standards and requires case-sensitive keys, or maybe even a certain order to the keys. Yes it would be wrong for the application to do that, but it's not Ansible's job to pass judgment on other applications, but instead just to make configuring them easy and unintrusive.

But I'm sure there were good reasons for designing ini_file the way it was. Maybe there can be some way to change ini_file to meet all goals?

**Comment by jctanner** [comment]
@rightaway I do not disagree with any of your statements here, but the implication is a complete rewrite of the ini_file module. This is something that should be discussed on the ansible-devel mailing list as opposed to a github ticket. Please start a thread there and if you have some code in mind, please submit a pull request.
