### ISSUE TITLE
S3 module does not allow downloading only when MD5 checksums are different

### ISSUE THREAD

**Issue by anslav** [ansible/ansible#5861]
My issue is described from the GET perspective, but the same can be applied to PUT.

As it stands right now, it is not possible to tell the S3 module to download and overwrite a file only when the hashes are different.

When overwrite is true, the file is downloaded regardless of the md5 checksum (which is performed anyway). When overwrite is false, the file is never downloaded, if it already exists.

Overwrite property should have 3 states, which are not adequately represented by the on/off nature of the overwrite/force setting:
- disabled: no overwriting happens
- diffonly: overwrite only when the hashes are different
- force: always overwrite

A backwards compatible solution would be to make overwrite and force separate parameters, both defaulting to True.
- force=True: would overwrite regardless of the checksum and imply overwrite=True
- overwrite=False: would never overwrite and imply force=False
- overwrite=True, force=False: would overwrite only when the checksum is different

If the solution is adequate, I could submit a pull request for the changes.

Tested on ansible 1.4.1, S3 module doesn't appear to have been touched since then.

**Comment by jctanner** [comment]
@anslav I would like to see this submitted as a pull request and also have a thread on ansible-devel to inform other ec2/s3 users that a change has been proposed.

**Comment by coopernurse** [comment]
Has there been any more work on this?  I'm running into this same issue now where I'd like to only download the S3 asset if the checksum is different.

**Comment by ghost** [comment]
related: https://github.com/ansible/ansible-modules-core/issues/489
