### ISSUE TITLE
with_items and yum

### ISSUE THREAD

**Issue by garethrees** [ansible/ansible#5871]
##### Issue Type:

Bug Report
##### Ansible Version:

``` sh
$ ansible --version
ansible 1.4.4
```
##### Environment:

**Host:** OS X
**Guest:** CentOS 6.5
##### Summary:

`with_items` doesn't install itemised yum packages.
##### Steps To Reproduce:

``` yaml
- hosts: all
  tasks:
    - name: Install extra PHP Packages
      yum: pkg=php54-{{item}} state=installed
      with_items:
        - gd
        - pdo
```
##### Expected Results:

php54-gd and php54-pdo installed on the guest.

``` sh
$ yum search php54-pdo
# ...
php54-pdo.x86_64 : A database access abstraction module for PHP applications
```
##### Actual Results:

``` sh
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [192.168.33.11]

TASK: [Install extra PHP Packages] ********************************************
failed: [192.168.33.11] => (item=gd,pdo) => {"changed": false, "failed": true, "item": "gd,pdo", "rc": 0, "results": ["php54-gd-5.4.24-1.ius.centos6.x86_64 providing php54-gd is already installed"]}
msg: No Package matching 'pdo' found available, installed or updated

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/gareth/my-playbook.retry

192.168.33.11              : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by garethrees** [comment]
I've raised a similar issue before, which seems to have had attention in 7201a6ffad68d158d30e5f5896c54cbfe3deaded.

**Comment by jimi-c** [comment]
I've replicated this and am looking into it.

**Comment by jimi-c** [comment]
Actually, this has come up before, and is a limitation of the templating engine. We currently do not support pre-fixing variables in this manner when using a lookup plugin, so the correct way to handle this is:

<pre>
- hosts: all
  tasks:
    - name: Install extra PHP Packages
      yum: name={{item}} state=installed
      with_items:
        - php54-gd
        - php54-pdo
</pre>

If you have any other questions regarding this, please let us know. Thanks!

**Comment by garethrees** [comment]
Hmm, that doesn't really suit my use-case.

I'd like my role interface to be:

``` yaml
roles:
  - { role: php, version: php54, modules: ['gd', 'pdo']
```

I haven't seen any documentation regarding the support of this. It seems like pre/postfixing a variable with normal text is okay, so it seems logical that one can use them this way.

``` yaml
# http://docs.ansible.com/playbooks_variables.html#conditional-imports
- [ "vars/{{ ansible_os_family }}.yml", "vars/os_defaults.yml" ]
```

**Comment by srgvg** [comment]
Workaround:
Copy or symlink the yum module to a local /library folder, and rename it to e.g. yum2 or yum_items, then use that name as action.
Downside: module is re-run for each package.

**Comment by jimi-c** [comment]
@garethrees in that case, do this:

<pre>
- hosts: awxlocal
  vars:
  - php_ver: php
  tasks:
  - name: Install extra PHP Packages
    yum: name={{item}} state=installed
    with_items:
    - '{{php_ver}}-gd'
    - '{{php_ver}}-pdo'
</pre>

**Comment by garethrees** [comment]
The `with_items` list should be dynamic, in that it can be specified as an argument to a role:

``` yaml
  - { role: php, version: php54, modules: ['gd', 'pdo']
```

**Comment by jimi-c** [comment]
In that case, you can acheive something similar to what @sergevanginderachter proposes using with_nested:

<pre>
  vars:
  - version: php
  - modules: ['gd','pdo']
  tasks:
  - name: Install extra PHP Packages
    yum: name={{ item|join('-') }} state=installed
    with_nested:
    - version
    - modules
</pre>

The result is the same however, where the packages are installed one at a time instead of all at once.

**Comment by garethrees** [comment]
@jimi-c that works, thanks.

Just out of interest, the output of that is:

``` sh
ok: [192.168.33.11] => (item=[u'php54', 'gd'])
```

What's the `u` doing there?

**Comment by codezerk** [comment]
http://docs.python.org/2.7/howto/unicode.html

It's a unicode decorator.

**Comment by cjw296** [comment]
@jimi-c - I don't see how this can be a templating issue, if I change from yum to debug, everything works as expected:

```
  - name: Install rpms
    debug: msg="prefix_{{item}}" state=present
    with_items: ['x', 'y', 'z']
```

...gives:

```
TASK: [Install rpms] ********************************************************** 
ok: [localhost] => (item=x) => {
    "item": "x",
    "msg": "prefix_x"
}
ok: [localhost] => (item=y) => {
    "item": "y",
    "msg": "prefix_y"
}
ok: [localhost] => (item=z) => {
    "item": "z",
    "msg": "prefix_z"
}
```

...while:

```
  - name: Install rpms
    yum: name="prefix_{{item}}" state=present
    with_items: ['x', 'y', 'z']
```

...gives:

```
TASK: [Install rpms] ********************************************************** 
failed: [localhost] => (item=x,y,z) => {"changed": false, "failed": true, "item": "x,y,z", "rc": 0, "results": []}
msg: No Package matching 'prefix_x' found available, installed or updated
```

_nb_: the "item" key is wrong there, so the prefix only gets applied to the first one.

This does seems very specific to the yum module...

**Comment by sivel** [comment]
@cjw296 you may be interested in https://github.com/ansible/ansible/pull/15657

**Comment by cjw296** [comment]
@sivel - yes indeed! thanks :-)

**Comment by jimi-c** [comment]
@cjw296 btw, just for reference it's a templating issue due to the way we silently squash items for certain modules (namely packaging modules like yum).

**Comment by cjw296** [comment]
@jimi-c - really? If I were to guess, I'd point the finger at this code:

https://github.com/ansible/ansible/blob/7201a6ffad68d158d30e5f5896c54cbfe3deaded/lib/ansible/runner/__init__.py#L460

Where does the equivalent live on master or develop? (sorry, can't figure out the branch structure this repo uses).

**Comment by jimi-c** [comment]
@cjw296 that code is essentially here now: https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/task_executor.py#L267

The idea is the same, for certain modules we optimize the call by squashing the list down (after evaluating conditionals on each item) and execute a single pass. The problem comes from trying to figure out which params in the module need to be templated with the `item` value (or as we now use loop_control, the `loop_var` value). I won't get in to it, but we'd essentially have to guarantee that one and only one param uses the loop_var value, and that param name would either have to be the same across all modules we squash or we'd have to have some way to look up which param it is. I'm not saying it's impossible, but it's not something we're doing right now.

**Comment by michaelgugino** [comment]
This bug is affecting me as well:

Here is my usecase:

```
- name: Download st2 rpms to host
  get_url:
    url:  "{{ rpm_url_base }}/{{ item }}"
    dest: /tmp/{{ item }}
  with_items: "{{ rpms_to_copy }}"

- name: Yum install st2.rpm
  yum:
    name: /tmp/{{ item }}
    state: present
  with_items: "{{ rpms_to_copy }}"
```

Definitely not intuitive based on behavior of most other modules.

**Comment by dccampbell** [comment]
I spent a good bit of time on this today, and was often pointed here by searches, so maybe I can save someone else some trouble posting my work-around here. Jimi's answer worked, but as he mentioned required looping through individual yum commands, as opposed to passing one list which gets run all at once. So I separated the work out into a fact and used the `format` filter to do the string manipulation:
```
- hosts: localhost
  vars:
    php_versions:
      - "php56"
      - "php70"
      - "php71"
    php_modules:
      - "mbstring"
      - "mcrypt"
      - "pdo"
      - "pecl-imagick"
  tasks:
    - set_fact: php_packages=[]
    - set_fact:
        php_packages: "{{ php_packages }} + [ '{{ \"%s-php-%s\"|format(item[0],item[1]) }}' ]"
      with_nested:
        - "{{ php_versions }}"
        - "{{ php_modules }}"
```
This gives you a single list to hand to the `yum` module:
```
"php_packages": [
    "php56-php-mbstring", 
    "php56-php-mcrypt", 
    "php56-php-pdo", 
    "php56-php-pecl-imagick", 
    "php70-php-mbstring", 
    "php70-php-mcrypt", 
    "php70-php-pdo", 
    "php70-php-pecl-imagick", 
    "php71-php-mbstring", 
    "php71-php-mcrypt", 
    "php71-php-pdo", 
    "php71-php-pecl-imagick"
]
```
