### ISSUE TITLE
Lookup plugin not run when there's an undefined legacy variable in the template string.

### ISSUE THREAD

**Issue by kjkuan** [ansible/ansible#5875]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.4
##### Environment:

N/A
##### Summary:

Lookup plugin not run when there's an undefined legacy variable in the template string.
##### Steps To Reproduce:

In Ansible 1.1(old I know, I'm trying to upgrade it to 1.4.4, and found this bug)
Example: When the variable `world` is undefined...

<pre>
shell: echo "$PIPE(echo hello $world)"
</pre>

##### Expected Results:

With the jinja syntax:

<pre>
shell: echo "{{ lookup('pipe', 'echo hello $world') }}"
</pre>

the expected output is produced:

<pre>
changed: [localhost] => {"changed": true, "cmd": "echo \"hello\" ", "delta": "0:00:00.003010", "end": "2014-02-04 15:18:24.253940", "rc": 0, "start": "2014-02-04 15:18:24.250930", "stderr": "", "stdout": "hello"}
</pre>

##### Actual Results:

<pre>
changed: [localhost] => {"changed": true, "cmd": "echo \"$PIPE(echo hello $world)\" ", "delta": "0:00:00.002986", "end": "2014-02-04 15:11:47.997792", "rc": 0, "start": "2014-02-04 15:11:47.994806", "stderr": "", "stdout": "(echo hello )"}
</pre>

I traced down the cause of the discrepancy to these lines in `template.py`:

> ```
>    if isinstance(args, basestring) and args.find('$') != -1:
>        # unable to evaluate something like $FILE($item) at this point, try to evaluate later
>        return None
> ```

With the above lines commented out, the lookup would work correctly. I can't see why those lines are needed. Any thoughts?

**Comment by bcoca** [comment]
$ syntax has been deprecated for a long time and then removed, those lines
enforce the removal

**Comment by kjkuan** [comment]
the deprecation warning says it will be removed in 1.5, so I think if ansible is going to bother with slowly deprecating a feature while providing backward compatibility before the feature is removed, then at least it should fix the bug? Although..., if the next release is going to be 1.5 then don't bother... . I can work around it myself.

**Comment by jctanner** [comment]
@kjkuan our policy for point releases (1.4.x for example) are to only cherry pick **_critical**_ bugfixes from devel. As $ is a deprecated syntax, and no longer available in devel/1.5, we would not fix it and cherry pick for a 1.4.5 release. 

1.5 is the next planned release, unless we do find some critical bug in 1.4.4. So far, we haven't found one.
