### ISSUE TITLE
Template Module Documenation: force option

### ISSUE THREAD

**Issue by pcarinhas** [ansible/ansible#5884]
##### Issue Type:=

Documentation Request
##### Ansible Version:

All
##### Environment:

Linux
##### Summary:

Please include a short description and example of the force option in the Templates module.
Apparently that option is described in the copy section, but not stated anywhere.
##### Steps To Reproduce:

none
##### Expected Results:

none
##### Actual Results:

none

**Comment by mpdehaan** [comment]
Will be in the next docs push, thanks!

**Comment by pdeaudney** [comment]
Did this ever documented? I don't see a force option in http://docs.ansible.com/template_module.html

**Comment by TomNaessens** [comment]
:+1: It still hasn't been documented.
