### ISSUE TITLE
Failure to parse stdout line with whitespace and equal signs

### ISSUE THREAD

**Issue by dewaegw** [ansible/ansible#5887]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.4
##### Environment:

Ubuntu 12.04
##### Summary:

Ansible shows a "failed to parse" error message for a line on stdout that contains a whitespace and an equal sign.

Simple example output line: "foo bar=baz"
##### Steps To Reproduce:

Following the code to lib/ansible/utils/init.py parse_json():

```
In [1]: data = "foo bar=baz"
In [2]: from ansible.utils import parse_json
In [3]: parse_json(data)
---------------------------------------------------------------------------
AnsibleError                              Traceback (most recent call last)
<ipython-input-3-8b8a33d672fa> in <module>()
----> 1 parse_json(data)

~/venv/local/lib/python2.7/site-packages/ansible/utils/__init__.pyc in parse_json(raw_data)
    311         for t in tokens:
    312             if t.find("=") == -1:
--> 313                 raise errors.AnsibleError("failed to parse: %s" % orig_data)
    314             (key,value) = t.split("=", 1)
    315             if key == 'changed' or 'failed':
```

AnsibleError: failed to parse: foo bar=baz
The initial json.loads() error is caught and falls back to "Baby JSON" parsing (with shlex), which also fails because the first items has no '='

```
In [4]: import shlex
In [5]: shlex.split(data)
Out[5]: ['foo', 'bar=baz']
```

If this is a bug ticket, please enter the steps you use to reproduce the problem in the space below.  If this is a feature request, please enter the steps you would use to use the feature.  If an example playbook is useful, please include a short reproducer inline, indented by four spaces.  If a longer one is neccessary, please link one uploaded to gist.github.com. 
##### Expected Results:

As we cannot always control what a module or command will put on stdout/stderr,
the output should always be parse-able to prevent the playbook from failing.
##### Actual Results:

See steps to reproduce
##### Suspected source:

lib/ansible/utils/init.py filter_leading_non_json_lines()
Docstring mentions "need to filter anything which starts not with '{', '[', ', '='",
but the code actually filters all lines with a '=' instead of only lines starting with '='

**Comment by mpdehaan** [comment]
Closing per above response, thanks!
