### ISSUE TITLE
with ask_sudo_pass=True incorrectly entering sudo password locks the terminal up

### ISSUE THREAD

**Issue by crucialfelix** [ansible/ansible#5888]
##### Issue Type:

Bug Report
##### Ansible Version:

1.4.3
##### Environment:

Running on OS X

Managing Ubuntu 12.04 LTS
##### Summary:

with ask_sudo_pass=True incorrectly entering sudo password locks the terminal up and even ctrl-c cannot interrupt it
##### Steps To Reproduce:

ansible.cfg

transport=paramiko
ssh_args=-o PasswordAuthentication=no -o ControlMaster=auto -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ControlPersist=60s
scp_if_ssh=True
ask_sudo_pass=True

task:

sudo=yes
user=deploy
sudo_user=somebody
1. Run an ansible command
2. Enter an incorrect sudo password on the command line
##### Expected Results:

Authenticating and performing the command.
##### Actual Results:
1. there is no feedback that the password was incorrectly entered. You just to have to realize after a while that its dead waiting on the other end.
2. the terminal is now stuck. ctrl-c does not even stop it. I have to shut the window. there are sometimes rogue ansible processes left running on the server.

**Comment by jctanner** [comment]
@crucialfelix this appears to be fixed as of 1.5.3 ...

```
jtanner@u1204:~/issues/6467-sudo-broken$ ansible -vvvv el6.lab.net -i inventory -m ping
sudo password: 
<el6.lab.net> ESTABLISH CONNECTION FOR USER: jtanner
<el6.lab.net> REMOTE_MODULE ping
<el6.lab.net> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jtanner/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'el6.lab.net', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1395081771.68-164061128644725 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1395081771.68-164061128644725 && echo $HOME/.ansible/tmp/ansible-tmp-1395081771.68-164061128644725'"]
<el6.lab.net> PUT /tmp/tmpogOjwD TO /home/jtanner/.ansible/tmp/ansible-tmp-1395081771.68-164061128644725/ping
<el6.lab.net> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jtanner/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'el6.lab.net', '/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=ztxadptsprglzwkejhallxtjhrphofkr] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-ztxadptsprglzwkejhallxtjhrphofkr; /usr/bin/python /home/jtanner/.ansible/tmp/ansible-tmp-1395081771.68-164061128644725/ping; rm -rf /home/jtanner/.ansible/tmp/ansible-tmp-1395081771.68-164061128644725/ >/dev/null 2>&1\'"\'"\'\'']
el6.lab.net | FAILED => Incorrect sudo password
```

If you still see the same issue after updating, we can reopen the issue.
