### ISSUE TITLE
Ansible confuses group name with host name

### ISSUE THREAD

**Issue by DXist** [ansible/ansible#5894]
##### Issue Type:

Bug Report
##### Ansible Version:

1.4.4
##### Environment:

N/A
##### Summary:

I get following message in ansible verbose output in GATHERING FACTS section:

``` bash
ssh: Could not resolve hostname ru-celeryworkers: Name or service not known
```

Ansible thinks that ru-celeryworkers is hostname but it is a group name.
If you comment out [celeryworkers:children] group in inventory below the error will disapear.
##### Steps To Reproduce:

ansible-playbook -i inventory.ini ru-celeryworkers.yml -vvvv

Inventory

``` ini
########### HOST VARIABLES ##############################################
127.0.1.1 ansible_connection=local DESTDIR="{{ lookup('env', 'PWD') }}/roots/ru-celeryworkers" PROJECT_ROOT="{{ lookup('env', 'PWD') }}"
127.0.1.2 ansible_connection=local DESTDIR="{{ lookup('env', 'PWD') }}/roots/ru-appservers" PROJECT_ROOT="{{ lookup('env', 'PWD') }}"

########### FUNCTIONAL AND GEOGRAPHIC INFRASTRUCTURE DIVISION ################
# infrastructure in Russia
[ru:children]
ru-appservers
ru-celeryworkers

# servers with celery
[celeryworkers:childen]
ru-celeryworkers

# uwsgi application servers
[appservers:children]
ru-appservers

########### HOOKS FOR SECRET VARIABLES ########################################

[ru-celeryworkers:children]
ru-celeryworkers-secret

[ru-appservers:children]
ru-appservers-secret

########### HOST->GROUP MATCHING ##############################################

[ru-celeryworkers-secret]
127.0.1.1

[ru-appservers-secret]
127.0.1.2
```

Playbook

``` yaml

---
# playbook for RU celeryworkers
- hosts: ru-celeryworkers
```
##### Expected Results:

Ansible should work with hosts in ru-celeryworkers group.
##### Actual Results:

Ansible tries to connect with ru-celeryworkers host during facts gathering fase.

**Comment by bcoca** [comment]
have you tried with hosts/groups without a - in the name?

**Comment by DXist** [comment]
No, I haven't. Is dash allowed in group names?

**Comment by g-k-r** [comment]
fix the typo in

```
[celeryworkers:childen]
```

and try again

**Comment by DXist** [comment]
Ooops! Now it works. Two heads are better than one. Thank you!
