### ISSUE TITLE
provide some facts for free

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#59]
While it's great to leverage facter and ohai (because they have a lot of good work in them), often you will not want them installed.

The setup module should generate a few 'ansible_' variables of it's own, at least OS version, OS type, arch, etc... so that the majority of users do not need to install any prerequisite software to use advanced playbook features like conditional imports and the proposed only_if support

**Comment by sfromm** [comment]
i'll take this

**Comment by mpdehaan** [comment]
awesome!

**Comment by mpdehaan** [comment]
this is closeable by #160, since we have that as a pull request I can go ahead and close that ticket.  Will look into testing PR tomorrow.  thanks again!
