### ISSUE TITLE
connection=local requires paramiko_ssh

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#591]
On experimenting with ansible --connection=local, I note that `lib/ansible/runner/connection/__init__.py` tries to import paramiko_ssh on line 33. This means that, even if no SSH is used on hosts that do ansible-local, the module has to be installed.

I've commented it out in a local copy, and ansible-local works. Can that import be made conditional and not required with connection=local?

**Comment by mpdehaan** [comment]
Sure.

a try/except around the import is what we should do here, raising an error only if attempting to use the connection when is used and it's not available

The RPM can and should still require paramiko, and I believe the distutils stuff should as well.

**Comment by mpdehaan** [comment]
done

**Comment by jpmens** [comment]
Tested. Works. Thank you.
