### ISSUE TITLE
Error when terminating ec2 instance with module ec2

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#5925]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5 (devel 36250c6b86) last updated 2014/02/10 07:57:30 (GMT +000)
##### Environment:

Running from Vagrant box with CentOS 6.5 and MacOS X. Hosts are Amazon AMI on EC2
##### Summary:

When using the ec2 module to terminate an instance on Amazon EC2, the instance gets terminated but the play ends in error with a traceback
##### Steps To Reproduce:

1.- Create an instance on Amazon EC2.

2.- Use ansible to terminate the instance with a play like this one:
- name: Terminate instance
  gather_facts: false
  hosts: all
  tasks:
  - name: Terminate instance
    local_action: ec2 region=us-east-1 instance_ids={{ instance_id }} state=absent
##### Expected Results:

The instance should be terminated and ansible should mark it as changed.
##### Actual Results:

I get the following traceback:

```
TASK: [Terminate instance] ****************************************************
failed: [127.0.0.1] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1391963851.62-221510921386672/ec2", line 2202, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1391963851.62-221510921386672/ec2", line 1073, in main
    module.exit_json(changed=changed, instance_ids=new_instance_ids, instances=instance_dict_array, tagged_instances=tagged_instances)
UnboundLocalError: local variable 'tagged_instances' referenced before assignment
```

I checked the relevant part of the code and the error makes sense since the 'tagged_instances' list is only initialised when 'state == present':

```
    if module.params.get('state') == 'absent':
        instance_ids = module.params.get('instance_ids')
        if not isinstance(instance_ids, list):
            module.fail_json(msg='termination_list needs to be a list of instances to terminate')

        (changed, instance_dict_array, new_instance_ids) = terminate_instances(module, ec2, instance_ids)

    elif module.params.get('state') == 'running' or module.params.get('state') == 'stopped':
        instance_ids = module.params.get('instance_ids')
        if not isinstance(instance_ids, list):
            module.fail_json(msg='running list needs to be a list of instances to run: %s' % instance_ids)

        (changed, instance_dict_array, new_instance_ids) = startstop_instances(module, ec2, instance_ids)

    elif module.params.get('state') == 'present':
        # Changed is always set to true when provisioning new instances
        if not module.params.get('image'):
            module.fail_json(msg='image parameter is required for new instance')

        tagged_instances = []
        if module.params.get('exact_count'):
            (tagged_instances, instance_dict_array, new_instance_ids, changed) = enforce_count(module, ec2)
        else:           
            (instance_dict_array, new_instance_ids, changed) = create_instances(module, ec2)

    module.exit_json(changed=changed, instance_ids=new_instance_ids, instances=instance_dict_array, tagged_instances=tagged_instances)
```

**Comment by mpdehaan** [comment]
Sorry for the delay in responding to this one.

Is this something you would like to work on and submit a pull request for?

Thanks!

**Comment by ghost** [comment]
I'll try to make some time to fix it and write a pull request for this.

**Comment by ghost** [comment]
On a second thought, I see this has already been fixed in the code, so I guess it's safe to close this issue.

**Comment by mpdehaan** [comment]
Excellent, thanks!
