### ISSUE TITLE
[patch] Unable to remove all groups from a user...

### ISSUE THREAD

**Issue by sean-** [ansible/ansible#5933]
##### Summary:

When attempting remove all groups from a user using the user module, ansible fails with the following message:

```
failed: [host] => {"failed": true}
msg: Group  does not exist
```
##### Steps To Reproduce:

Use the user module with an empty groups parameter. e.g.:

```
user: name=someuser state=present 'groups='
```

The bug is due to splitting an empty string:

```
>>> set(''.split(','))
set([''])
>>> set(filter(None, ''.split(',')))
set([])
```

The latter behavior is the desired and I'm guessing the assumed input for the rest of the function. Running through filter() is the fastest way to remove empty strings from the set. The following patch fixes the above error and the correct and documented behavior is restored. It looks like this has been broken for ~8-9mo (since #3062).
##### Expected Results:

It should be possible to remove a user from all auxiliary groups.
##### Actual Results:

... how about this ansibot template stuffs itself and someone applies the following patch (or comes up with a better solution):

```
diff --git a/library/system/user b/library/system/user
index bf7af53..b0b2394 100644
--- a/library/system/user
+++ b/library/system/user
@@ -443,7 +443,7 @@ class User(object):
         if self.groups is None:
             return None
         info = self.user_info()
-        groups = set(self.groups.split(','))
+        groups = set(filter(None, self.groups.split(',')))
         for g in set(groups):
             if not self.group_exists(g):
                 self.module.fail_json(msg="Group %s does not exist" % (g))
```

**Comment by mpdehaan** [comment]
Hi, if you would like to submit a patch, can you please submit a pull request on GitHub?

That ensures us we are all merging and reviewing things the same way and is neccessary with a project of our size.

Please read https://help.github.com/articles/using-pull-requests if you haven't used these before.

Thanks!

**Comment by sean-** [comment]
Done. See #5944.
