### ISSUE TITLE
playbook hosts wildcard syntax should be more full featured

### ISSUE THREAD

**Issue by mpetrive** [ansible/ansible#5936]
##### Issue Type:

Feature Idea
##### Ansible Version:

1.4.4
##### Environment:

N/A
##### Summary:

In a playbook, hosts should be selectable from the inventory using regular expressions and/or wildcards (e.g. '_') before and after the string.  For example if I want to specific DHCP servers from the inventory where hosts are defined with FQDNs I would expect *dhcp1_ to select "xx01-dhcp1.domain.int"
##### Steps To Reproduce:

N/A

```
- hosts: *dhcp1*
  user: root
  tags: [ dhcp_keydeploy ]
  tasks:
   - debug: do key deploy 1
   - authorized_key: user=root 
                 key="{{ lookup('file', 'tmp/dhcp_server1_id_rsa.pub') }}"
                 path='/root/.ssh/authorized_keys'
                 manage_dir=no
```
##### Expected Results:

Selection of xx01-dhcp1.domain.int
##### Actual Results:

Syntax error

**Comment by mpdehaan** [comment]
This is not something we are likely to implement and we generally feel that host names should not be signfiicant in most architectures, and that host specifiers should be used for groups when possible.

In this case, we're just using a basic fnmatch, so it's going to be limited to what fnmatch can do, but 99% of the time, people are driving inventory from groups.

However, you could use the "range" support in inventroy to make groups without having to type in each hostname.

**Comment by escoreal** [comment]
Yes i see, it's an old issue. But if someone is looking for this:

`~(.*)dhcp1(.*)` works for me on 1.9.2.
But you would maybe need this: `~(.+)dhcp1(.+)`

http://docs.ansible.com/intro_patterns.html
"Most people don’t specify patterns as regular expressions, but you can. Just start the pattern with a ‘~’:"
