### ISSUE TITLE
Ansible block + with_together

### ISSUE THREAD

**Issue by sundertinwar** [ansible/ansible#59398]
##### SUMMARY

I am new with Ansible and still figuring out how to use with_together with block.
UseCase: Trying to compare configuration of device A and device B. Below is a snippet from my script.

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below
2.7.9
```

##### CONFIGURATION

```paste below
-
  hosts: pairB
  connection: network_cli
  name: script to audit HSRP config of pair B device
  tasks:
    -
      name: running hsrp brief on device B
      nxos_command:
        commands:
          - command: sh hsrp brief
            output: json
      register: hsrpB

-
  hosts: localhost
  vars:
    deviceA: "{{ hostvars[groups['pairA'][0]]['hsrpA']['stdout'][0].TABLE_grp_detail.ROW_grp_detail }}"
    deviceB: "{{ hostvars[groups['pairB'][0]]['hsrpB']['stdout'][0].TABLE_grp_detail.ROW_grp_detail }}"
  tasks:
    - name: compare hsrp config of device A and device B      
      block:
        - name: "compare config"
          debug:
            msg: "check config of device A and device B"
          when:
            - item.0.sh_active_router_addr != item.1.sh_active_router_addr or item.0.sh_authentication_data != item.1.sh_authentication_data
            - ((item.0.sh_prio < item.1.sh_prio and item.0.sh_group_state == "Active" and item.1.sh_group_state == "Standby") or (item.0.sh_prio > item.1.sh_prio and item.0.sh_group_state == "Standby" and item.1.sh_group_state == "Active"))
      rescue:
        - debug:
            msg: "config does not match for device A and B"
      with_together:
        - "{{ deviceA }}"
        - "{{ deviceB }}"
```

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
