### ISSUE TITLE
Submit ansible to Pypi

### ISSUE THREAD

**Issue by alixmartineau** [ansible/ansible#595]
Hello,

Do you have any plan to put Ansible on [Pypi](http://pypi.python.org/pypi) ?

Thanks,

**Comment by mpdehaan** [comment]
Thanks for the reminder, I'll look into it.

**Comment by mpdehaan** [comment]
Looked into this, seems things like to upload via setup.py, as we are a whole systems management application we have a lot of things like config files and such, and I am not sure this makes sense.

So, closing for now, given the work required in the setup.py stuff, and knowing that if we put those files in library/ into setup.py it causes problems on some platforms.

**Comment by skorokithakis** [comment]
I would like to reopen this. It would be _very_ useful to many people, and I don't see what's wrong with having config files. PyPI is meant to host packages as they are, and to upload ansible there you shouldn't really need to do anything other than `python setup.py sdist upload`...

Could you elaborate a bit on why you think it's a hassle?

**Comment by skorokithakis** [comment]
I have published ansible (tag 0.8) to PyPI, mainly as a test (I want to see if `pip` installs it fine, so far so good). If this is disagreeable, let me know and I'll remove it.

**Comment by mpdehaan** [comment]
It's disagreeable, please remove it.

**Comment by mpdehaan** [comment]
What you can do is contribute any neccessary patches to Ansible to make it
/publishable/ via PyPi (including modules and config files all installed in
the right place), provided they can be done in a way that keeps RPM builds
working on all platforms.   Let me see that first and I can take care of
publishing it, but I need to own the PyPi package records.

**Comment by skorokithakis** [comment]
I have removed it. I don't see why it isn't publishable, as, from what I can tell, installing the package from a checkout or from PyPI does the exact same thing, and it worked exactly the same for the few minutes it was published.

That said, I couldn't install it in a virtualenv, as it tried to copy libraries to `/usr/lib/ansible` (if I remember correctly), but the packaging was no problem. I couldn't install the checkout in a virtualenv either.

**Comment by mpdehaan** [comment]
Right, that's the problem.

That latter part is exactly the problem, the number of people trying it in
a virtualenv gets to be quite annoying to keep answering those questions.

Seeing this is an application and not a python library, I don't see this
being a dealerbreaker though if it's not in PyPi, but provided the above is
actually solved, I'll publish it.

**Comment by skorokithakis** [comment]
Ah, I'm one of the people who prefers to not even install applications globally. However, the virtualenv problem should be a separate bug that is blocking this one, as it's not really related to publishing or not.

I'll have a look and see if I can fix it, and comment on #1410 if I get anywhere.

Is there a way to add something like "Blocked by #1410" here?

**Comment by mpdehaan** [comment]
Blocking tickets is not really meaningful/important.

**Comment by skorokithakis** [comment]
Never mind, I fixed the issue. Issuing a pull request now.
