### ISSUE TITLE
ansible-playbook --syntax-check: error message for spaces not well-formed

### ISSUE THREAD

**Issue by HonkingGoose** [ansible/ansible#59547]
##### SUMMARY

Misspelled words, missing punctuation, capitalization in error message from ```ansible-playbook --syntax-check``` 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible-playbook

##### ANSIBLE VERSION

```
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/giraffe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

##### CONFIGURATION

```

```

There's no output from the ansible-config dump command.

##### OS / ENVIRONMENT

Ubuntu 18.04.2 LTS, installed Ansible from *ppa:ansible/ansible*

##### STEPS TO REPRODUCE

1. Use the below testcase, copy-paste into testcase.yml file.
1. Run ```ansible-playbook testcase.yml --syntax-check```
1. Note error message for ```found a tab character that violate intendation``` .
1. Note error message is not well-formed. See EXPECTED RESULTS for suggested improvements.
1. End of steps to reproduce.

```
---

# Ansible testcase

- hosts: localhost
						
---
```

##### EXPECTED RESULTS

The proper spelling and syntax would be:
```
ERROR! Syntax Error while loading YAML.
  Found a tab character that violates indentation.
```

##### ACTUAL RESULTS

Error message contains: 1 misspelled word **intendation**, **violate** should be violates, missing capitalization at start of sentence, no full stop at end of sentence.

```
ansible-playbook 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/giraffe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the
implicit localhost does not match 'all'

ERROR! Syntax Error while loading YAML.
  found a tab character that violate intendation

The error appears to be in '/home/giraffe/Documents/testcase.yml': line 6, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- hosts: localhost

^ here
There appears to be a tab character at the start of the line.

YAML does not use tabs for formatting. Tabs should be replaced with spaces.

For example:
    - name: update tooling
      vars:
        version: 1.2.3
#    ^--- there is a tab there.

Should be written as:
    - name: update tooling
      vars:
        version: 1.2.3
# ^--- all spaces here.


```

**Comment by HonkingGoose** [comment]
I tried searching the ```ansible/ansible``` master branch for **intendation** but that yields no results...
So I'm not sure where this error message is coming from.

**Comment by bcoca** [comment]
the last part from `pyyaml` library, which is the YAML parser we use, we capture it and try to show it with more context so people can fix the issue, but Ansible itself does not generate the underlying error.

**Comment by sivel** [comment]
Yes, that error actually comes from libyaml which is used in the C implementation of pyyaml:

https://github.com/yaml/libyaml/blob/567353cee9c8c5f8de1f438f89a9a2fa7a7b06fe/src/scanner.c#L3526

**Comment by HonkingGoose** [comment]
Thank you for your comments @bcoca and @sivel. I'll go fix this with a PR on the libyaml repo. :)

**Comment by mkrizek** [comment]
Thanks @HonkingGoose. I am going to close this since it's now tracked in https://github.com/yaml/libyaml/pull/151.
