### ISSUE TITLE
VirtualBox module wrapper

### ISSUE THREAD

**Issue by mikhailov** [ansible/ansible#5955]
##### Issue Type:

Feature Idea
##### Ansible Version:

ANY
##### Environment:

OS X, Linux
##### Summary:

Since I lost hope on Vagrant from high complexity to extend to Ruby syntax for VMs configuration I tried to build some simple version of VBoxManage CLI that based on .vagrant configuration (pretty weird data structure with files): https://gist.github.com/mikhailov/8104790

The misconception of Vagrant is the configuration is a Ruby code to execute which is totaly wrong in terms of Ansible approach. Perhaps, many Ansbile users tend to keep Vagrant just to bootstrap VM, that is it, all the provisioning, orchastration and life-cycle management happens via Ansbile.

Ansible has [modules set](http://docs.ansible.com/list_of_cloud_modules.html) for Rackspace, EC2, DigitalOcean, Azure, AWS and VMware. Is there plan to build the same for VirtualBox without Vagrant?
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
Ideas for perspective features like this if not completely fleshed out are probably best discussed on the ansible mailing list, where we can get more information and also engage more people in the discussion.

Can you please start a thread there?  Thanks!

**Comment by mikhailov** [comment]
@mpdehaan as you asked, I moved it to Mailing List: https://groups.google.com/forum/#!topic/ansible-project/DukoxFoGo0g
