### ISSUE TITLE
Use issuetemplate.com to make issue triaging easier.

### ISSUE THREAD

**Issue by kentcdodds** [ansible/ansible#5961]
##### Issue Type:

Feature Idea
##### Ansible Version:

N/A
##### Environment:

N/A
##### Summary:

I made a web app for the AngularJS project to help them triage their huge amounts of issues they have to deal with. I noticed your project gets a lot of issues as well and thought you could find it useful. Give it a look and feel free to ask me any questions or submit issues to the repository.
[**http://issuetemplate.com/**](http://issuetemplate.com/)
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by kentcdodds** [comment]
This is awesome. Based on the fact that you have a bot I'm going to guess you're going to love this thing :) Instead, your bot could say this:

Hey! I noticed you didn't use our template. Please go here to update your issue using the template:
http://issuetemplate.com/ansible/ansible/{{template-name}}/{{issue-number}}

And their issue info would be included in the form they fill out. I think you'll love this thing :)

**Comment by mpdehaan** [comment]
So it does look very good!

If you don't mind, I'm a bit leery (no offense implied) of depending on external SaaS thingy, but I see you've open sourced it, which is great too.   I had a little hard time gleaning some of this from the webpage, but can you share a bit about what's the hosting and business plan behind this project, etc if it might exist?   Also is it possible to have a seperate template for pull requests?

(We would probably also need a bot to scan the template as we were trying to auto-tag but maybe it can do that... anyway, easily done)

Anyhow, thanks for sharing!   

cc @jctanner

**Comment by kentcdodds** [comment]
This is a labor of love. I'm not planning on making money from it. It's free to use by the open source community. Firebase is sponsoring one of their candle plans for hosting the templates. You can have any number of templates, so you could have a pull request template if you want (though I haven't tested this on pull requests yet, not sure how that would work).

Also, in the template you could add a comment that is not visible to the submitter, but your bot would be able to parse it and assign it to the right person, give it the right labels, tell that the template was used, etc.

Let me know if you have any other questions :)

**Comment by mpdehaan** [comment]
Nice, I'll talk it over with the team.  I do like the interface!

**Comment by mpdehaan** [comment]
Closing this due to time/resources needs, but thanks very much for the idea.

Looks like a neat project!
