### ISSUE TITLE
SSH inside of a playbook

### ISSUE THREAD

**Issue by aminjam** [ansible/ansible#5963]
##### Issue Type:

What kind of ticket is this?  You can say “Bug Report”, “Feature Idea”, “Feature Pull Request”, “New Module Pull Request”, “Bugfix Pull Request”, “Documentation Report”, or “Docs Pull Request”.
##### Ansible Version:

ansible 1.4.4
##### Environment:

Mac OSx
##### Summary:

I don't know if it's possible or not, but I have docker running inside of my VM, and part of the deploying the app requires me to ssh into the root@localhost -p 20022 (20022) is my Docker container SSH port. Here is what I have in my playbook. 

```
 # SSH into Docker
 - name: SSH into Docker
   shell: ssh root@localhost -p 40022 -o StrictHostKeyChecking=no 
```

After I run the playbook, it hangs on ssh command. Is that even possible? If so, am I missing something obvious. Thanks for the help.
##### Steps To Reproduce:

inside of a playbook
     # SSH into Docker
     - name: SSH into Docker
       shell: ssh root@localhost -p 40022 -o StrictHostKeyChecking=no 
##### Expected Results:

ssh into the box.
##### Actual Results:

hangs.

**Comment by bcoca** [comment]
you are telling a batch systems to open an interactive terminal ... i
expect it to hang.

what do you need to do after the ssh? you should be able to just use a
delegated task.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by aminjam** [comment]
basically I have a base node container, so I would like to ssh into the container, git clone my code, then npm install, and run the app. Here the complete playbook.

---
- hosts: all
  sudo: yes
  tasks:
  - name: SSH into Docker
    shell: ssh root@localhost -p 40022 -o StrictHostKeyChecking=no 
  - name: Ensure we got the App code
    git:
     repo=git://github.com/aminjam/express-hello-world.git
     dest=/opt/node-hello-world
  - name: Ensure the npm dependencies are installed
    command:
     chdir=/opt/node-hello-world
     npm install
    ignore_errors: yes
  - name: Install forever
    shell: npm install -g forever
  - name: Run the App
    shell: forever start /opt/node-hello-world/server.js

**Comment by bcoca** [comment]
ok ... ansible doesn't work that way, if you ssh in task 1 to another
machine, task2 WILL NOT execute on that machine, it will execute on the
current host target.

you want to define the docker hosts and run the play against them.

**Comment by aminjam** [comment]
Docker is running inside of the host. These are not two different hosts. Docker run as a low level lxc-container, so you can create as many containers communicating with each other on a single VM, so as a result, you can create a base Node container, and just push the code repo on the ansible level. so I am trying to figure out how to ssh into the localhost port 40022 which is created by the Docker container. This may not be possible with ansible as it stands, but it would be a very useful feature to add.

**Comment by bcoca** [comment]
I know how docker works. In any case,  it is a 'virtual host' on your
current host, ansible even has a docker connection plugin to manage it as
such.

Your tasks as they are WILL NOT WORK. You need to point directly at the
docker "host", either through ssh (you can enable this inside your
container) or use the ansible docker connection plugin.

**Comment by bcoca** [comment]
hit enter early. ...

you are already accessing it over ssh, just non standard port, you can even
configure this in ansible with ansible_ssh_host=localhost and
ansible_ssh_port=20022 when you define it in the inventory.

**Comment by aminjam** [comment]
Perfect. Thanks for your help. I see what I was missing. It worked like a charm when I just ssh with 20022 instead of double ssh.
