### ISSUE TITLE
local_action doesn't use python extensions installed in virtualenv with pip

### ISSUE THREAD

**Issue by datasmid** [ansible/ansible#5978]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.4
##### Environment:

CentOS release 6.4
##### Summary:

ansible local_action doesn't use python extensions installed in virtualenv with pip
##### Steps To Reproduce:
1. Pip install ansible in virtualenv, note the use of the python extension 'httplib2'
   virtualenv venv
   venv/bin/pip install --upgrade ansible
   venv/bin/pip install --upgrade paramiko PyYAML jinja2 httplib2
   virtualenv --relocatable venv
2. Now to reproduce on Centos verify the RPM is absent
   $ rpm -q python-httplib2
   package python-httplib2 is not installed
3. And provoke the bug with a playbook:
   - name: 'make sure myUrl is accessible' 
     local_action: uri url=${myUrl} method=OPTIONS
##### Expected Results:

```
failed: [somehost] => {"failed": true}
msg: Unable to resolve the host name given.
```
##### Actual Results:

```
failed: [somehost] => {"failed": true}
msg: httplib2 is not installed
```
1. Verify that the system python is required for extensions by running the above after this:
   yum install -y  python-httplib2
##### Concern:

How to isolate Ansible in virtualenv and avoid dependency hell?

**Comment by sivel** [comment]
You may be interested in #5335

Also, if you want to keep ansible from attempting to install files to /usr/share/ansible you need to precreate ~/.ansible.cfg with something like:

```
[defaults]
library = /path/to/venv/library
```

But you might also benefit from the running from source install instructions.

**Comment by sivel** [comment]
Also note that with local_action this should already be fixed in 1.5 (devel) assuming you don't explicitly declare localhost in your inventory.

localhost is now implicit with 1.5 and uses the python bin used to run ansible (sys.executable)

2 different way to solve the issue.

**Comment by datasmid** [comment]
It looks like Ansible is not relocatable for re-packaging.

**Comment by mpdehaan** [comment]
This is true, we are likely moving to setuptools in the future that may assist with some of this.

But yes, running from source helps a lot here.

**Comment by mpdehaan** [comment]
Closing as this is all related to the larger issue of the install script.
