### ISSUE TITLE
Config `.ansible_async` location

### ISSUE THREAD

**Issue by nxt-ext** [ansible/ansible#5990]
##### Issue Type:

“Feature Idea”
##### Ansible Version:

Latest
##### Environment:

“N/A”. 
##### Summary:

There are a lot of limitations at [OpenShift Online](https://www.openshift.com/products/online). One of them - restricted `~` folder. To deploy there with ansible default tmp folders `~/.ansible` and `~/.ansible_async` should be changed. I can change `~/.ansible` @ `ansible.cfg`, but I can do nothing with `~/.ansible_async`.
##### Steps To Reproduce:

“N/A”. 
##### Expected Results:

“N/A”. 
##### Actual Results:

“N/A”.

**Comment by mpdehaan** [comment]
I'd be open to the idea that this could be configurable at least on a global level.

Something you might like to add a pull request for?

**Comment by mpdehaan** [comment]
Seeing OpenShift is a PaaS I suspect there's not a lot of Ansible user crossover, so I'm not entirely sure of the urgency of this one -- yet I wanted to point out that we are very opent o pull request for this.

Nonetheless, I'm going to close this ticket as it's unlikely we're going to tackle this one ourselves.

Thanks!
