### ISSUE TITLE
Linode module: Don't prepend Linode ID

### ISSUE THREAD

**Issue by mahemoff** [ansible/ansible#5991]
##### Issue Type:

Feature request
##### Ansible Version:

1.4.4
##### Environment:

Ubuntu 12.04
##### Summary:

The [doc](http://docs.ansible.com/linode_module.html) says "To keep sanity on the Linode Web Console, name is prepended with LinodeID"., but I have a logical naming scheme which is interrupted by the arbitrary Linode IDs.

I think this feature should at very least be optional.
##### Steps To Reproduce:

ansible localhost -m linode -a "name=web (other-ags ..."
##### Expected Results:

Linode created is called "web" in Linode console.
##### Actual Results:

Linode created is called "1234_web" in Linode console, where "1234" is the Linode node ID.

**Comment by mahemoff** [comment]
The ID's prepended at https://github.com/ansible/ansible/blob/devel/library/cloud/linode#L252

**Comment by mpdehaan** [comment]
Can we start a discussion on this on ansible-project?

I'm open to the idea but wouldn't want to break anyone or remove soemthing some folks were liking.

Thanks!

**Comment by mpdehaan** [comment]
Also, this is is unlikely to be something we are going to personally work on. Should you wish to do this, the best thing to do would be to submit a pull request.

For discussion topics, we prefer the list as there are more people reading the list (several thousands) versus github history (a couple).

Thanks!

**Comment by pilwon** [comment]
@mpdehaan @mahemoff Created PR #7223 for this issue. Please review & merge.
