### ISSUE TITLE
Linode module: Add private IP

### ISSUE THREAD

**Issue by mahemoff** [ansible/ansible#5992]
##### Issue Type:

Feature request
##### Ansible Version:

1.4.4
##### Environment:

Ubuntu 12.04
##### Summary:

An option to add private IP would be great (it's possible in Linode's API - https://www.linode.com/api/linode/linode.ip.addprivate). This is rather cumbersome to do manually as it requires a reboot.
##### Steps To Reproduce:

ansible localhost -m linode -a "private_ip=true (other-args)"
##### Expected Results:

Linode has a private IP and has been rebooted to ensure it's active.
##### Actual Results:

Linode has no private IP. It must be created manually in Linode console.

**Comment by mpdehaan** [comment]
This sounds like it would be a nice idea, but it is not likely something the project admins are going to implement.

Is this something you would like to work on?

If not, perhaps it is something you should bring up on the mailing list to see if someone would like to implement.

Thanks!

**Comment by mahemoff** [comment]
Understand. As I'm time-constrained now, here's a simple Gist of how I got this and #5991 working - https://gist.github.com/mahemoff/8983846

I might mail the list or put a proper patch in later.

**Comment by pilwon** [comment]
@mpdehaan @mahemoff Created PR #7223 for this issue. Please review & merge.

**Comment by aleemb** [comment]
+1

**Comment by arturmartins** [comment]
I actually like the prefix Linode ID. I would recommend that both (Prefix and Private IP) should be active by configuration (example: add_prefix: false, add_private_ip: true)
