### ISSUE TITLE
playbook should take a --local flag allowing playbooks to be used inside kickstarts

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#60]
I'd like a capability to allow playbook to auto-update my system w/o using SSH to itself, but it should not be the default behavior.

This would make for easy use of ansible for initial bringup inside a kickstart file

**Comment by mpdehaan** [comment]
once done, be sure we document this, it is a very nice case to make it easy to fully apply config prior to installation completion

**Comment by mpdehaan** [comment]
no one is asking for this, would complicate usage explanations, passing on this for now

**Comment by jkleint** [comment]
Is this the same capability mentioned as "Local Playbooks" in the documentation?
http://ansible.github.com/playbooks.html#local-playbooks
I'd like this capability, too, but if it's not implemented don't tease me with the docs.  ;)

**Comment by mpdehaan** [comment]
it's implemented, which you could verify by trying the doc example and seeing that the config argument is there :)

Don't trust old ticket comments!  The maintainer of this project might be insane.
