### ISSUE TITLE
debug module does not respect ignore_errors

### ISSUE THREAD

**Issue by ex-nerd** [ansible/ansible#6008]
##### Issue Type:

What kind of ticket is this?  You can say “Bug Report”, “Feature Idea”, “Feature Pull Request”, “New Module Pull Request”, “Bugfix Pull Request”, “Documentation Report”, or “Docs Pull Request”.
##### Ansible Version:

1.4.5
##### Environment:

OSX but likely N/A
##### Summary:

`debug` module does not respect `ignore_errors`
##### Steps To Reproduce:

Run the following playbook:

``` yaml
- name: test
  hosts: localhost
  gather_facts: False
  tasks:
    - debug: msg="debug message 1"
    - debug: msg="{{ undefined_var }}"
      ignore_errors: True
    - debug: msg="debug message 2"
```
##### Expected Results:

Three debug tasks should execute.  One will fail, but `ignore_errors` should allow the final "debug message 2" statement to print.
##### Actual Results:

ansible prints "debug message 1" but execution  stops at:

```
fatal: [localhost] => One or more undefined variables: 'undefined_var' is undefined
```

**Comment by bcoca** [comment]
this is a templating error, ignore_errors is for execution errors. What you
want to use is default:
- debug: msg="{{ undefined_var|default('undefined!') }}"

On Fri, Feb 14, 2014 at 4:30 AM, Chris Petersen notifications@github.comwrote:

> Issue Type:
> 
> What kind of ticket is this? You can say "Bug Report", "Feature Idea",
> "Feature Pull Request", "New Module Pull Request", "Bugfix Pull Request",
> "Documentation Report", or "Docs Pull Request".
> Ansible Version:
> 
> 1.4.5
> Environment:
> 
> OSX but likely N/A
> Summary:
> 
> debug module does not respect ignore_errors
> Steps To Reproduce:
> 
> Run the following playbook:
> - name: test
>   hosts: localhost
>   gather_facts: False
>   tasks:
>   - debug: msg="debug message 1"
>   - debug: msg="{{ undefined_var }}"
>     ignore_errors: True
>   - debug: msg="debug message 2"
> 
> Expected Results:
> 
> Three debug tasks should execute. One will fail, but ignore_errors should
> allow the final "debug message 2" statement to print.
> Actual Results:
> 
> ansible execution stops at:
> 
> fatal: [localhost] => One or more undefined variables: 'undefined_var' is undefined
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/6008
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by jimi-c** [comment]
Agreed, this is not an issue. If you have any further questions about this, let us know. Thanks!
