### ISSUE TITLE
Git module should raise an error when the repo did not originate from a git clone

### ISSUE THREAD

**Issue by goozbach** [ansible/ansible#601]
When using a non-cloned (originally) repository, the git module errors out.

The logic here:

```
cmd = "git branch -a"
cmd = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
(gbranch_out, gbranch_err) = cmd.communicate()

try:
   m = re.search( '^\* (\S+|\(no branch\))$', gbranch_out, flags=re.M )
   cur_branch = m.group(1)
   m = re.search( '\s+remotes/origin/HEAD -> origin/(\S+)', gbranch_out, flags=re.M )
   default_branch = m.group(1)
```

Seems to be the culprit.

There is most likely a different way to determine the default branch. Something like git ls-remotes? or the like?

Currently there are two possible work-arounds:

1) remove and re-clone from the remote repository

2) manually add the symref (untested)

**Comment by mpdehaan** [comment]
How about not supporting non-cloned repos?   I think this is mostly useful for deployment, but maybe I'm missing something.

**Comment by goozbach** [comment]
here are the steps to replicate.

1) on the minion create a new git repo, add and check-in the contents.

2) create a bare remote repo elsewhere (I used gitolite)

3) add the newly created remote repo as a remote using `git remote add origin <LOCATION>`, and do `git push origin master`

4) Try to deploy the newly created remote repo to the location it already existed on the minion using the ansible git module. (ie `ansible host -m git -a 'repo=remote dest=/already/exist'`)

**Comment by goozbach** [comment]
Also the IRC discussion about this issue and #604 we came to the following conclusion to this bug:

1) you shouldn't do this

2) we need better error reporting to detect this issue and print a warning stating you should move and clone the repo.

3) if this is the same issue as #604, then we need to dig deeper anyway.

**Comment by sfromm** [comment]
I see the following on a repository created as described above:

```
$ git remote show origin
* remote origin
  Fetch URL: /tmp/test/remote/
  Push  URL: /tmp/test/remote/
  HEAD branch: master
  Remote branch:
    master tracked
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

If I clone the remote repository, I see this:

```
$ git remote show origin
* remote origin
  Fetch URL: /tmp/test/remote/
  Push  URL: /tmp/test/remote/
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

The only way I can see how to pull in updates on the former, non-cloned repository is to do _git remote update ; git merge origin/master_.

**Comment by go2sh** [comment]
(This is more a response to #604)
My repos was cloned by ansible-pull. I just created the emtpy local directory, everything else was done by the ansible-pull script. The strange thing is. The command ansible runs is:

```
git pull -u origin
```

with the result:

```
Already up-to-date.
```

but when I run the same command in my shell in the same directory, I get that update I want.

**Comment by mpdehaan** [comment]
@sfromm @goozbach this is already fixed by the addition of --track, right?

**Comment by mpdehaan** [comment]
nm, we are talking about 604 on 601.  Yeah, we should just not do this.  Send me a PR if we want to raise an error message or whatever, otherwise I'm closing this

**Comment by sfromm** [comment]
It appears that if you do _git branch --set-upstream master origin/master_ in the local repo, that ansible's git module will be able to pull updates from the remote repo.  @goozbach Can you confirm?
