### ISSUE TITLE
Show progress indicator on CLI while collection is being published

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#60157]
##### SUMMARY

When I publish a collection to Galaxy, I see nothing in my console indicating activity, so I wonder if something is stuck.

Reading the [Collections documentation](https://docs.ansible.com/ansible/devel/dev_guide/collections_tech_preview.html#building-collections), I can see:

> The command waits until the import process completes before reporting the status back. If you wish to continue without waiting for the import result, use the --no-wait argument and manually look at the import progress in your My Imports page.

But it's not apparent just using the CLI, and it would be nice if there was at least something like a row of dots or a spinner or something (even just `|/-\\` in rotation) to just show that something is happening and the process is not locked up.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`ansible-galaxy collection publish`

##### ADDITIONAL INFORMATION

N/A

**Comment by geerlingguy** [comment]
Also, I'm not sure what the collection publish timeout is by default, but it seems fairly short, because it seems after only 30s or so I got:

```
Publishing collection artifact '/Users/jgeerling/Dropbox/VMs/collections/geerlingguy.php_roles/geerlingguy-php_roles-0.9.3.tar.gz' to https://galaxy.ansible.com
ERROR! Timeout while waiting for the Galaxy import process to finish, check progress at 'https://galaxy.ansible.com/api/v2/collection-imports/204/'
```

**Comment by sivel** [comment]
We can see maybe doing this in the future. It likely will not happen for 2.9.  A lot of details will have to be worked out, as urllib doesn't give us great insight into the upload status.

**Comment by geerlingguy** [comment]
@sivel - Even without a progress bar, just an indication that something is happening would be nice.

**Comment by jborean93** [comment]
I agree this can be better, if you run with a higher verbosity it will show something is happening but let's improve it. As for the timeout, it uses a expotential backoff wait which should last for about 60 seconds https://github.com/ansible/ansible/blob/devel/lib/ansible/galaxy/collection.py#L767. I only tested with smaller collections and they all imported within 10 seconds but sounds like a larger collection can take longer. Maybe we should add a cli argument to adjust this.

**Comment by geerlingguy** [comment]
@jborean93 - Yeah, in my case it's a collection with 11 roles: https://galaxy.ansible.com/geerlingguy/php_roles

I'm guessing the role import takes exponentially longer (per role) than modules/plugins, since it does the full linting/metadata process on each one.

**Comment by geerlingguy** [comment]
(I would also presume a collection like [debops.debops](https://galaxy.ansible.com/debops/debops) would be an even more extreme case, as it has over 100 roles).

**Comment by jborean93** [comment]
> I'm guessing the role import takes exponentially longer (per role) than modules/plugins, since it does the full linting/metadata process on each one.

This begs the questions as to whether we want to have a default timeout at all. Maybe we should just indefinitely wait until the import process has finished and allow people to specify their own smaller timeout if they wish. Having a progress indicator would set aside my main concerns that having an indefinite timeout would make people think that something is stuck on long imports.

**Comment by drybjed** [comment]
I'm not sure why Galaxy has to test each role separately with `ansible-lint` etc. The `ansible-lint` command already supports globbing, all you need to do to test all roles in the `roles/` directory is run:
```
ansible-lint roles/*
```
I'm testing 161 roles at once, [this test on Travis takes ~7 minutes](https://travis-ci.org/debops/debops/jobs/570854960). I'm not sure what are the timings for the import on Ansible Galaxy, but I suspect that it is a bit longer than that.

**Comment by newswangerd** [comment]
@awcrosby ^

Can we use globing in the galaxy importer?

**Comment by awcrosby** [comment]
In the galaxy.ansible.com importer the linters are run individually for each role and plugin, as we are capturing and storing the linter output to individually score items. If we see there would be a good performance improvement we could revisit that.
