### ISSUE TITLE
please reference `default` filter as counterpart to `mandatory`

### ISSUE THREAD

**Issue by ex-nerd** [ansible/ansible#6016]
##### Issue Type:

“Documentation Report”
##### Ansible Version:

1.4.5
##### Environment:

N/A
##### Summary:

Per #6008, it would be nice if there was a mention of Jinja's `default` filter alongside the `mandatory` filter described at 
http://docs.ansible.com/playbooks_variables.html#forcing-variables-to-be-defined
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
default is actually not documented right now because while "mandatory" was a filter we added, "default" is a core Jinja2-ism.   

However, it's probably worth referencing as it's one of the more useful ones.

**Comment by ex-nerd** [comment]
Yeah, that was my main thought.  Sometimes it's easy to forget that a large portion of ansible documentation actually lives in Jinja's docs.

**Comment by mpdehaan** [comment]
done, will be in next docs push
