### ISSUE TITLE
Please document that `ignore_errors` does not ignore template errors.

### ISSUE THREAD

**Issue by ex-nerd** [ansible/ansible#6017]
##### Issue Type:

“Documentation Report”
##### Ansible Version:

N/A
##### Environment:

N/A
##### Summary:

Per #6008, "template errors" are not "execution errors".  The docs at http://docs.ansible.com/playbooks_error_handling.html#id4 should probably mention that there are different classes of errors and that the `ignore_errors` flag does not apply to template errors.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
I'd agree here.   Doing that now and will be available in next docs push.
