### ISSUE TITLE
apt module not doing unattended installs

### ISSUE THREAD

**Issue by rdanbrook** [ansible/ansible#602]
The apt module currently brings up dialogs when installing some packages. It can be easily fixed by adding DEBIAN_FRONTEND=noninteractive as an environment variable.

library/apt:
APT = "DEBIAN_PRIORITY=critical %s" % APT_PATH

change to:
APT = "DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical %s" % APT_PATH

**Comment by mpdehaan** [comment]
change applied, but did not test -- if you want to test the latest devel that would be great

**Comment by ChadScott** [comment]
I think we may have a regression on this issue.

I've been testing various new "roles" for Ubuntu 12.04 and I've found a case that doesn't work in Ansible but works properly manually. A simple...

`- name: install slapd`
`apt: pkg=slapd state=installed`

...will hang forever. Closer inspection shows whiptail waiting for a response to the question, "Please enter the password for the admin entry in your LDAP directory."

However, a manual...

`sudo DEBIAN_FRONTEND=noninteractive apt-get -y install slapd`

...works just fine.

**Comment by ChadScott** [comment]
Actually, now that I dig through the code, it looks like Ansible is making no use of `APT_ENVVARS` for the install() action.

I'll send a pull request tomorrow sometime.

**Comment by srgvg** [comment]
@ChadScott see #2763 

`APT_ENVVARS`is indeed new to the upgrade funtion. The way the install function works, didn't change recently.

**Comment by srgvg** [comment]
@ChadScott can you test the fix at #2771 ? thx

**Comment by srgvg** [comment]
Correction, the env vars were called with the install function prior to my recent patch, this was indeed a regression. My bad.
