### ISSUE TITLE
Allow use of 'tests' directory for storage of ansible-test tests and config

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#60218]
##### SUMMARY

Many developers are used to storing testing code in a `tests/` directory in their project root, but the way `ansible-test` works currently requires testing code be stored only in a `test/` directory only.

It would be nice to either allow tests to be picked up from `test/` _or_ `tests/`, or to maybe pass a cli option (like `--test-dir`) or environment variable to specify the directory containing the testing code.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible-test

##### ADDITIONAL INFORMATION
N/A

**Comment by mattclay** [comment]
Currently collections use `test` because that is what Ansible uses. However, the plan is to use `tests` for collections, to match the other top level directories `roles` and `plugins` since they are also plural.
