### ISSUE TITLE
ansible-galaxy collection install requires a mandatory -p option

### ISSUE THREAD

**Issue by anshulbehl** [ansible/ansible#60216]
##### SUMMARY
-p or --collections-path should not be mandatory and should pick up value of COLLECTIONS_PATH variable.
As a user of collection if I don't know which path ansible is using to load collection I will tend to make mistakes installing the collection to right path.
COLLECTIONS_PATH will make sure the collection will get picked up for sure.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

COLLECTIONS

##### ANSIBLE VERSION

```paste below
ansible 2.9.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/abehl/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/abehl/work/src/anshul_ansible/ansible/lib/ansible
  executable location = /home/abehl/work/src/anshul_ansible/ansible/bin/ansible
  python version = 2.7.16 (default, Apr 30 2019, 15:54:43) [GCC 9.0.1 20190312 (Red Hat 9.0.1-0.10)]

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Try installing a collection without giving -p option

```yaml

```

##### EXPECTED RESULTS

if -p provided use provided path, if not provided use COLLECTIONS_PATHS variable

##### ACTUAL RESULTS

-p is mandatory right now

```paste below

```

**Comment by sivel** [comment]
It is expected that the user must provide this value, and this was an explicit choice on our part.

Documentation is in the process of being updated currently: https://github.com/ansible/ansible/pull/60164

In the future, we may extend this to include some form of default value.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by chrismeyersfsu** [comment]
This would be less painful if the debugging output, when you are testing calling the collection you installed, was more verbose. But, as it stands, the debug output when a collection is not found is not very useful.

**Comment by anshulbehl** [comment]
Reopening
@thaumos Can you take a stab as this and please close if this doesn't make sense

**Comment by jborean93** [comment]
During the intial development for `ansible-galaxy collection install` we couldn't come to a consensus of what should be the default install location. The end result was to punt the decision and make it a mandatory argument. For now this won't change for the 2.9 release so I am going to close the issue.
