### ISSUE TITLE
Probably a documentation item: Ansible coerces 'on' to True and 'off' to False

### ISSUE THREAD

**Issue by joshuaconner** [ansible/ansible#6022]
##### Issue Type:

Bug Report/Documentation Report
##### Ansible Version:

ansible 1.5
##### Environment:

OSX 10.9
##### Summary:

Ansible seems to coerce the string `on` to `True` and the string `off` to false.
##### Steps To Reproduce:

Here's a super simple playbook demonstrating the behavior:

```

---
- name: test
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    - should_be_on: on
    - should_be_off: off
  tasks:
    - debug: var=should_be_on
    - debug: var=should_be_off
```
##### Expected Results:

I'd expect to the value `should_be_on` to be `on` and the value of `should_be_off` to be `off` based upon the current documetation.

Ansible's boolean coercion stuff is documented a little [here](http://docs.ansible.com/YAMLSyntax.html#yaml-basics) – it would be nice to either update the documentation, or not coerce `on` and `off` to boolean values.  Unless I am totally missing something! What do you think?
##### Actual Results:

This is the output from the above playbook

```
PLAY [test] *******************************************************************

TASK: [debug var=should_be_on] ************************************************
ok: [localhost] => {
    "should_be_on": "True"
}

TASK: [debug var=should_be_off] ***********************************************
ok: [localhost] => {
    "should_be_off": "False"
}

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by joshuaconner** [comment]
[ticket updated]

**Comment by mpdehaan** [comment]
This is not a bug but is actually part of the YAML spec.

Quote the string to avoid this.

"on"

http://www.yaml.org/refcard.html
