### ISSUE TITLE
Bug Report: delegate_to should work with role dependencies

### ISSUE THREAD

**Issue by t-8ch** [ansible/ansible#6023]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5 (devel 77c42c5c1e) last updated 2014/02/15 09:03:20 (GMT +000)
##### Environment:

N/A
##### Summary:

`delegate_to` does not work for dependencies of roles
##### Steps To Reproduce:

Create a role which depends on another role applied to a different host.

Example configuration ([also as tarball](https://t-8ch.de/ansible_issue_6023_example.tgz)):

``` ini
# file: ansible.cfg
[defaults]
hostfile = hosts
nocows = 1
```

``` ini
# file: hosts
application_server ansible_ssh_host=127.0.0.1 # ansible_python_interpreter=python2
database_server ansible_ssh_host=someinvalidhostname.example.com  # force a failure
```

``` yaml
# file: main.yaml
- hosts: application_server
  roles:
    - application
```

``` yaml
# file: roles/application/tasks/main.yaml
- debug:
    msg: creating *application* on {{ inventory_hostname }}
```

``` yaml
# file: roles/application/meta/main.yaml
dependencies:
  - role: database
    delegate_to: database_server
```

``` yaml
# file: roles/database/tasks/main.yaml
- debug:
    msg: creating *database* on {{ inventory_hostname }}
```

And run it:

``` sh
$ ansible-playbook main.yaml
```
##### Expected Results:

An error indicating the database server has been configured improperly.
The database is a dependency of the application and gets applied first.
##### Actual Results:

```
PLAY [application_server] ***************************************************** 

GATHERING FACTS *************************************************************** 
ok: [application_server]

TASK: [database | debug ] ***************************************************** 
ok: [application_server] => {
    "item": "", 
    "msg": "creating *database* on application_server"
}

TASK: [application | debug ] ************************************************** 
ok: [application_server] => {
    "item": "", 
    "msg": "creating *application* on application_server"
}

PLAY RECAP ******************************************************************** 
application_server         : ok=3    changed=0    unreachable=0    failed=0
```

**Comment by leucos** [comment]
This would be awesome. I'm surprised nobody has commented in 4 months.

### Use case

Create a DB on a database server when deploying an app, without having to change the DB server config (which would introduce coupling in the DB server).

Sorry for triggering a misplaced joy notification @t-8ch !

**Comment by leucos** [comment]
My bad. Thinking of it, this is much more a use case for TASK delegation. Sorry for the noise.

**Comment by Lowess** [comment]
I agree, It would be awesome. I have an other use case with Icinga (Nagios) and NRPE agent installation and I would like to trigger an entire role when the NRPE has been installed on my remote hosts.

Sorry for the noise too @t-8ch ...

**Comment by bailsman** [comment]
Imagine the following use case:

On server A, database needs to be installed.
Then server B needs to be configured to backup the database on server A.
Further assume that both these configurations are sufficiently complex that they cannot be done in one single task.

Currently, you can do one of two things to achieve this:
1. Use a playbook with multiple plays, one running on server A, another running on server B. A big disadvantage to this solution is that you cannot have a playbook as a dependency for something else. Let's say the above needs to happen as a dependency, then what do I do?
2. Another option is to add delegate_to: {{variable}} to every task in your role, and then set that variable before you call the role. This works, but it makes the role a lot less readable.

It would be really nice if you could delegate an entire role to a server.

**Comment by dguerri** [comment]
+1

**Comment by christophlehmann** [comment]
+1

**Comment by mpetrive** [comment]
+1

**Comment by leucos** [comment]
Seeing cccasional '+1' hitting my mailbox, I think this should be discussed further, and I should explain why I changed my mind on this issue.

I don't think this responsibility (delegating the database install) shoud be hardwired in your application role. This couples your application role to your database role and is bad in many ways. If you change your database backend (for instance, going master slave or clustering), it will impact your application role (you will have to handle delegation to multiple hosts, telling one to be master, etc...). It will also make it harder to unit test your roles. Minimizing coupling, is in my top 3 things to aim for when writing stuff (especially Ansible roles and inventories).

The point of a playbook is just this: orchestrating the various roles together. So, unless I originally misunderstood the issue, I guess your problem can be solved more elegantly like so:

```
# file: main.yaml
- hosts: database_server
  roles:
    - database

- hosts: application_server
  roles:
    - application
```

The playbook makes the glue between the various moving parts. No coupling between roles. Things can evolve without impacting others.

**Comment by Lowess** [comment]
I think @leucos is right. I was going in the wrong way with role delegation and I ended up making the glue between my role and the monitoring server reload reload in the playbook file... 

It is also much understandable and maintainable.

In most cases the role delegation can be worked around by calling the role in the playbook file.
