### ISSUE TITLE
Add option to leave integration test container running after test completes

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#60248]
##### SUMMARY

When I'm developing and/or debugging a role in a Collection, there are often times where there's an error (e.g. "package xyz was not found").

If I see the error, under current `ansible-test` behavior, I need to then go somewhere else (e.g. molecule, or set up my own separate test environment locally) to debug this.

It would be nice if there were a CLI option like `--docker-preserve-container` or `--docker-container-no-stop` (something like that) which would, after a test completes, leave the container running (and ideally print the container's name and/or hash to stdout so I could then `docker exec -it [container id] bash` and play around inside.

Doing this allows me to quickly debug the problem that caused the test failure (a lot of times it's just me being dumb and not refreshing a package cache, or using the wrong package name... but it's best if I can go in and run `apt-cache madison [package]` or `dnf search [package]` or whatever).

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

ansible-test

##### ADDITIONAL INFORMATION

N/A

**Comment by geerlingguy** [comment]
Between this and #60219 I think this one might be more helpful/higher priority from a role developer's perspective, just because I have to debug things frequently, and there's an easy enough (but annoying) workaround for #60219.

Note that in comparison, when I develop roles with `molecule`, the equivalent would be running `molecule converge`, which runs all the same stuff as a normal test run, but doesn't destroy the test container/environment at the end.

**Comment by mattclay** [comment]
Resolved by https://github.com/ansible/ansible/pull/68688
