### ISSUE TITLE
Feature request: Linode add private ip address

### ISSUE THREAD

**Issue by bsdlp** [ansible/ansible#6025]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.4.5
##### Environment:

N/A
##### Summary:

The Linode cloud module is currently missing the ability to add private IP addresses to an instance. This is important for the NodeBalancer product, which requires Linodes to be added using the Linode's private IPv4 address.

https://www.linode.com/api/linode/linode.ip.addprivate
##### Steps To Reproduce:

N/A
##### Expected Results:

Adds private IP address after Linode is created, but before it is booted.
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
Sorry for the late response on this as we've been working our way through the queue.

We've been mostly concentrating on extending things like EC2 and Rackspace, but obviously Linode is good stuff too -- is this something you would like to work on?

If so, we are open to pull requests.  

Thanks!

**Comment by pilwon** [comment]
@mpdehaan @fly Created PR #7223 for this issue. Please review & merge.

**Comment by mpdehaan** [comment]
Closing this ticket since pull request above was submitted, thank you very much!
