### ISSUE TITLE
ejabberd_user requires mod_admin_extra

### ISSUE THREAD

**Issue by ToBeReplaced** [ansible/ansible#6027]
##### Issue Type:

Documentation Report
##### Ansible Version:

ansible 1.4.3
##### Environment:

Fedora 20
##### Summary:

The `ejabberd_user` module requires `mod_admin_extra` for the `ejabberdctl check_account user host` call.  This is not noted as a requirement, and it is not configured by default on Fedora.

I don't know whether or not that is a reasonable requirement for the module.  If so, then adding it to the documentation and/or providing a better error message would be sufficient.
##### Steps To Reproduce:

Attempt to create a user with a stock installation of ejabberd from fedora -- ejabberd version `2.1.13`, no changes to `ejabberd.cfg`.
##### Expected Results:

Nothing when the user already exists. 
##### Actual Results:

Failed rc 1 when the user doesn't exist.  The module attempts to call `ejabberdctl check_account user host`, which it can not do because `check_account` depends on `mod_admin_extra` being in the configuration of the running server.

**Comment by efine** [comment]
As an aside, `mod_admin_extra` comes standard with the Debian build of ejabberd `2.1.x`. Because it's so useful, perhaps Fedora should consider adding it (it's a pretty straightforward patch - one extra file and an extra line in `ejabberd.app`).

**Comment by mpdehaan** [comment]
Can you share how you think the docs should be changed to reflect this?

Thanks!
