### ISSUE TITLE
VMware modules: Remove unnecessary Python 2.6 compatibility tests

### ISSUE THREAD

**Issue by mariolenz** [ansible/ansible#60288]
The **Control Node Requirements** in the [Installation Guide](https://docs.ansible.com/ansible/2.8/installation_guide/intro_installation.html#control-node-requirements) are this:

> Currently Ansible can be run from any machine with Python 2 (version 2.7) or Python 3 (versions 3.5 and higher) installed.

The VMware modules all run on a control node. Nevertheless, Shippable tests for Python 2.6 compatibility.

##### SUMMARY
Shippable integration tests fail because #60233 isn't compatible with Python 2.6. Why test for 2.6 compatibility if you don't support this version?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
all VMware modules

##### ANSIBLE VERSION
```paste below
ansible 2.9.0.dev0
  config file = None
  configured module search path = [u'/home/mario/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mario/rme/ansible/lib/ansible
  executable location = /home/mario/rme/ansible/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION
```

```

##### OS / ENVIRONMENT
irrelevant

##### STEPS TO REPRODUCE
Write some code for a new or existing VMware module that isn't Python 2.6 compliant.

##### EXPECTED RESULTS
No fail.

##### ACTUAL RESULTS
Shippable fails.

**Comment by sivel** [comment]
We are working towards a point where we no longer test controller side code on Python 2.6, but that work requires us to implement split controller and target testing.  However, as worded here and in the document you indicate, modules are not controller only execution.

Maintaining python 2.6 compatibility from a syntax check, is easy and simple enough to not cause much of a pain, so at this point, we recommend that you update your syntax to work on python2.6 as well.

Python 2.6 compliant syntax would look like:

```
all_hosts = dict((h.name, h) for h in self.get_all_hosts_by_cluster(self.cluster_name))
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
