### ISSUE TITLE
Support automatically generating a graph of role dependencies

### ISSUE THREAD

**Issue by mtr** [ansible/ansible#6041]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.5
##### Environment:

N/A
##### Summary:

I really enjoy your support for role dependencies and how it encourages reuse of role definitions.  However, as the number of roles in my full site deployment has increased (27+, where many sub-roles are shared between other roles) the complexity of maintaining the playbooks has increased too.  

I believe that if Ansible could output its (inherently computed) dependency graph it would make coping with the orchestration and maintenance complexity a lot easier.  I have asked [if anyone already knows a simple way of doing this](http://stackoverflow.com/q/21721942/126273), but no one has answered yet.

In the meantime, I have created my own dependency graph (in GraphML, but the format is of minor importance) for the project I'm working on.
##### Steps To Reproduce:

ansible-playbook site.yml --generate-dependency-graph=[json|graphml|indented-text]
##### Expected Results:

The generated dependency graph is output on stdout.
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
This is unlikely to be something that will be a feature in the ansible CLI.   If you want to create a script or something to produce this, that would be interesting.
