### ISSUE TITLE
Xenserver XenAPI getting updated in PyPi

### ISSUE THREAD

**Issue by jthompson333** [ansible/ansible#60418]
##### SUMMARY
I wanted to let the maintainer know that the XenAPI will be updated in PyPI at some point.
There is a test version here:
https://test.pypi.org/project/XenAPI/

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
https://docs.ansible.com/ansible/latest/modules/xenserver_guest_module.html
xenserver_guest

##### ANSIBLE VERSION
ansible 2.8.3
  config file = /home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg
  configured module search path = ['/home/johntho/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/lib/python3.6/site-packages/ansible
  executable location = /home/johntho/.local/share/virtualenvs/ansible-stable-MRUwKOHz/bin/ansible
  python version = 3.6.3 (default, May 31 2019, 13:05:43) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

##### CONFIGURATION
CACHE_PLUGIN(/home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg) = redis
CACHE_PLUGIN_CONNECTION(/home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg) = 127.0.0.1:6379
CACHE_PLUGIN_TIMEOUT(/home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg) = 86400
DEFAULT_CALLBACK_WHITELIST(/home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg) = ['yaml']
DEFAULT_FORKS(/home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg) = 20
DEFAULT_GATHERING(/home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg) = smart
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg) = yaml
INVENTORY_ENABLED(/home/johntho/ansible-stable/cqe/ansible_goodies/ansible.cfg) = ['host_list', 'script', 'yaml', 'ini', 'auto', 'nmap', 'azure_rm']

##### OS / ENVIRONMENT
Centos 7

##### ADDITIONAL INFORMATION
The new version should be tested and then the docs updated.

**Comment by jthompson333** [comment]
@bvitnik FYI.  Thanks for all that you do. :)

**Comment by bvitnik** [comment]
@jthompson333 Acknowledged. I'll check it out as soon as I can.

**Comment by Akasurde** [comment]
@jthompson333 Thanks for reporting this.

**Comment by jthompson333** [comment]
Looks like its live now.  The new version that is...

https://pypi.org/project/XenAPI/

**Comment by bvitnik** [comment]
@jthompson333 I did some testing of new version of XenAPI library from PyPI and it worked without any problem. Nothing changed considerably in library itself or the packaging so problems should not be expected.

I will update the docs soon.
