### ISSUE TITLE
Recent ansible (dev) versions fail to connect in accelerated mode to nodes without a $HOME/.ansible

### ISSUE THREAD

**Issue by neh** [ansible/ansible#6047]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5
More specifically: f72f5a20
##### Environment:

Ubuntu 12.04
##### Summary:

When using accelerated mode with hosts that lack $HOME/.ansible, ansible fails to communicate with the managed node ("Failed to get a response from X.X.X.X"). Turning accelerated mode off allows ansible to manage the node normally. The nodes in question have been managed with accelerated ansible previously with no issues.
##### Steps To Reproduce:
1. Git checkout version f72f5a20 or later (a bisect led me to that commit).
2. Run any playbook against a node that does not have a .ansible directory in the ansible user's home directory.
##### Expected Results:

I was expecting ansible to continue to manage the nodes it had successfully managed previously. :-)
##### Actual Results:

The connection fails with the message "fatal: [X.X.X.X] => Failed to get a response from X.X.X.X"

Running with -vvvv results in this log output in the target node syslog:

```
Feb 17 23:42:37 nodetest ansible-<stdin>: Invoked with timeout=300 ipv6=False debug=4 password=NOT_LOGGING_PASSWORD minutes=30 port=5099
Feb 17 23:42:37 nodetest ansible-<stdin>: exiting pid 1418
Feb 17 23:42:37 nodetest ansible-<stdin>: daemon pid 1419, writing /home/ansiblinator/.accelerate.pid
Feb 17 23:42:37 nodetest ansible-<stdin>: pidfile written
Feb 17 23:42:37 nodetest ansible-<stdin>: daemonizing successful
Feb 17 23:42:37 nodetest ansible-<stdin>: serving!
Feb 17 23:42:37 nodetest ansible-<stdin>: waiting for data
Feb 17 23:42:37 nodetest ansible-<stdin>: in recv_data(), waiting for the header
Feb 17 23:42:37 nodetest ansible-<stdin>: in recv_data(), got the header, unpacking
Feb 17 23:42:37 nodetest ansible-<stdin>: data received so far (expecting 105): 0
Feb 17 23:42:37 nodetest ansible-<stdin>: data received so far (expecting 105): 105
Feb 17 23:42:37 nodetest ansible-<stdin>: received all of the data, returning
Feb 17 23:42:37 nodetest ansible-<stdin>: got data, decrypting
Feb 17 23:42:37 nodetest ansible-<stdin>: decryption done
Feb 17 23:42:37 nodetest ansible-<stdin>: loading json from the data
Feb 17 23:42:37 nodetest ansible-<stdin>: received a request to validate the user id
Feb 17 23:42:37 nodetest ansible-<stdin>: validating we're running as ansiblinator
Feb 17 23:42:37 nodetest ansible-<stdin>: response result is {'rc': 0}
Feb 17 23:42:37 nodetest ansible-<stdin>: sending the response back to the controller
Feb 17 23:42:37 nodetest ansible-<stdin>: done sending the response
Feb 17 23:42:37 nodetest ansible-<stdin>: waiting for data
Feb 17 23:42:37 nodetest ansible-<stdin>: in recv_data(), waiting for the header
Feb 17 23:42:37 nodetest ansible-<stdin>: in recv_data(), got the header, unpacking
Feb 17 23:42:37 nodetest ansible-<stdin>: data received so far (expecting 297): 0
Feb 17 23:42:37 nodetest ansible-<stdin>: data received so far (expecting 297): 297
Feb 17 23:42:37 nodetest ansible-<stdin>: received all of the data, returning
Feb 17 23:42:37 nodetest ansible-<stdin>: got data, decrypting
Feb 17 23:42:37 nodetest ansible-<stdin>: decryption done
Feb 17 23:42:37 nodetest ansible-<stdin>: loading json from the data
Feb 17 23:42:37 nodetest ansible-<stdin>: received a command request, running it
Feb 17 23:42:37 nodetest ansible-<stdin>: executing: mkdir -p /tmp/ansible-tmp-1392680557.45-105435893467553 && chmod a+rx /tmp/ansible-tmp-1392680557.45-105435893467553 && echo /tmp/ansible-tmp-1392680557.45-105435893467553
Feb 17 23:42:37 nodetest ansible-<stdin>: got stdout: /tmp/ansible-tmp-1392680557.45-105435893467553
Feb 17 23:42:37 nodetest ansible-<stdin>: got stderr:
Feb 17 23:42:37 nodetest ansible-<stdin>: thread is done, response from join was {'stdout': '/tmp/ansible-tmp-1392680557.45-105435893467553\n', 'stderr': '', 'rc': 0}
Feb 17 23:42:37 nodetest ansible-<stdin>: response result is {'stdout': '/tmp/ansible-tmp-1392680557.45-105435893467553\n', 'stderr': '', 'rc': 0}
Feb 17 23:42:37 nodetest ansible-<stdin>: sending the response back to the controller
Feb 17 23:42:37 nodetest ansible-<stdin>: done sending the response
Feb 17 23:42:37 nodetest ansible-<stdin>: waiting for data
Feb 17 23:42:37 nodetest ansible-<stdin>: in recv_data(), waiting for the header
Feb 17 23:42:37 nodetest ansible-<stdin>: in recv_data(), got the header, unpacking
Feb 17 23:42:37 nodetest ansible-<stdin>: data received so far (expecting 28009): 0
Feb 17 23:42:37 nodetest ansible-<stdin>: data received so far (expecting 28009): 28009
Feb 17 23:42:37 nodetest ansible-<stdin>: received all of the data, returning
Feb 17 23:42:37 nodetest ansible-<stdin>: got data, decrypting
Feb 17 23:42:37 nodetest ansible-<stdin>: decryption done
Feb 17 23:42:37 nodetest ansible-<stdin>: loading json from the data
Feb 17 23:42:37 nodetest ansible-<stdin>: received a put request, putting it
Feb 17 23:42:37 nodetest ansible-<stdin>: the target user doesn't match this user, we'll move the file into place via sudo
Feb 17 23:42:37 nodetest ansible-<stdin>: encountered an unhandled exception in the handle() function
Feb 17 23:42:37 nodetest ansible-<stdin>: error was:#012Traceback (most recent call last):#012  File "<stdin>", line 280, in handle#012  File "<stdin>", line 394, in put#012  File "/usr/lib/python2.7/tempfile.py", line 300, in mkstemp#012    return _mkstemp_inner(dir, prefix, suffix, flags)#012  File "/usr/lib/python2.7/tempfile.py", line 235, in _mkstemp_inner#012    fd = _os.open(file, flags, 0600)#012OSError: [Errno 2] No such file or directory: '/home/ansiblinator/.ansible/tmp/ansible.5M5dLQ'
```

I'm not sure how the nodes in question ended up without their .ansible directories. Once the directory is recreated (eg. by checking out an earlier version and running ansible against that node) then the newer commits appear to work just fine.

**Comment by mpdehaan** [comment]
cc @jimi-c can you take a look at this?

**Comment by neh** [comment]
So it appears that $HOME/.ansible/tmp is not being created by ansible any more. When I configure a new node with my bootstrap role, it works, but then the next run fails. Logging in to the node and running mkdir -p $HOME/.ansible/tmp as the ansible user makes everything work again.

**Comment by jimi-c** [comment]
@neh are you still seeing this with the most recent pull from devel? I've tried reproducing it on ubuntu 12.04/13.10 and CentOS 6.3 (with and without sudo), and haven't been able to see the same error.

**Comment by neh** [comment]
@jimi-c I'm still seeing the same behaviour. Anything else I can test or info you need? I'm testing on an Ubuntu 12.04 node controlled from Ubuntu 13.10.

**Comment by jimi-c** [comment]
@neh how are you installing ansible?

**Comment by neh** [comment]
@jimi-c With the usual 'run from source' method... clone from github and source hacking/env-setup.

**Comment by jimi-c** [comment]
But on the target system, `/home/ansiblinator` exists and there are no permission issues writing to it?

**Comment by neh** [comment]
It does. I can ssh in as that user and mkdir -p ~/.ansible/tmp with no problem, and everything is happy after that.

**Comment by jimi-c** [comment]
Ok, can you gist a playbook that reproduces the issue?

**Comment by ivanvolti** [comment]
I have exactly the same problem when using accelerated mode (ansible 1.5):

```
fatal: [vagrant.local] => Failed to get a response from vagrant.local
```

To make it work I have to ssh to my vagrant and use `mkdir -p ~/.ansible/tmp` command. After that I can use ansible-playbook as usual without any errors. Thanks to @neh for this tip.

**Comment by marselester** [comment]
I have the same problem.

**Comment by neh** [comment]
@jimi-c Apologies for the delay on this response. This is all it takes for me: https://gist.github.com/neh/9373548 . I just run that against a newly created and untouched Ubuntu 12.04 container as below, and I get the above error on the second play.

```
ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook bugtest.yml -i 10.5.4.59, -u ubuntu -k -K
```

**Comment by jimi-c** [comment]
@neh thanks, that led me to the problem. The above commit should resolve the issue for you if you pull the latest devel branch. We will also include this in 1.5.1. Thanks!
