### ISSUE TITLE
Wrong variable resolution with multiple groups

### ISSUE THREAD

**Issue by flaub** [ansible/ansible#6048]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.5
##### Environment:

Ubuntu 12.04
##### Summary:

When a host is specified within multiple groups, variable resolution appears to be based off whichever group is first (lexically).  Here's an example:
##### Steps To Reproduce:

Directory structure:

```
ansible
  groups_vars
    group_a.yml
    group_b.yml
  hosts
  test.yml
```

Contents of `ansible/hosts`

```
[local]
localhost ansible_connection=local

[group_a:children]
local

[group_b:children]
local
```

Contents of `ansible/group_vars/group_a.yml`

```
var: A
```

Contents of `ansible/group_vars/group_b.yml`

```
var: B
```

Contents of `ansible/test.yml`

```
- hosts: group_b
  gather_facts: false
  tasks:
    - debug: msg="{{ var }}"
```
##### Expected Results:

The debug msg should output "B".
##### Actual Results:

Output of `ansible-playbook -i hosts test.yml`

```
$ ansible-playbook -i hosts test.yml

PLAY [group_b] ****************************************************************

TASK: [debug msg="{{var}}"] ***************************************************
ok: [localhost] => {
    "msg": "A"
}

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

**Comment by mpdehaan** [comment]
So both groups are at the same depth, so this behavior is undefined.

I disagree that this is a bug because the groups are on the same depth.

Since this is a bit of "question" mode, feel free to stop by the mailing list to discuss further.

**Comment by flaub** [comment]
Thanks, I started a thread on the mailing list.

**Comment by mpdehaan** [comment]
Excellent.
