### ISSUE TITLE
Ansible-pull module - GitHub link goes to 404 page.

### ISSUE THREAD

**Issue by BryanFogleman** [ansible/ansible#60502]
##### SUMMARY

GitHub links to wrong or missing page.  

##### ISSUE TYPE
- Documentation Report
bad link

##### COMPONENT NAME

ansible-pull

docs/docsite/rst/cli  hasn't been in tree for several releases

##### ANSIBLE VERSION

```paste below
2.8 (latest page url). 
```

##### CONFIGURATION

```paste below

```

**Comment by BryanFogleman** [comment]
Ansible-pull module page --  github link goes to a 404 page. 
https://docs.ansible.com/ansible/latest/cli/ansible-pull.html
Top right corner of the GitHub link goes to missing page.

**Comment by bcoca** [comment]
that should not appear on this page since it is not editable in github, it is generated from the command line options of ansible-pull itself.

**Comment by Nothing4You** [comment]
I guess it's the same issue here: https://docs.ansible.com/ansible/latest/plugins/inventory/vmware_vm_inventory.html

worth noting however is that this one has an edit link at the bottom to the source code which actually works.

**Comment by Nothing4You** [comment]
@bcoca do you want a different issue for the plugin then or still track it here?

**Comment by Akasurde** [comment]
Link is working now. Please feel free to open a new issue if it does not. Thanks.
