### ISSUE TITLE
Please add a note about 'yum-utils' required on some systems to the yum module documentation

### ISSUE THREAD

**Issue by 42wim** [ansible/ansible#6050]
##### Issue Type:

Documentation Report
##### Ansible Version:

1.5
##### Environment:

N/A
##### Summary:

Please add a note about 'yum-utils' required on some systems to the yum module documentation
See https://github.com/ansible/ansible/issues/2002
##### Steps To Reproduce:

N/A
##### Expected Results:

Note being added :-)
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
So a link to an old ticket is a little confusing, is there something particular you found needed yum-utils that was not clear or specifically what problem you are seeing resolved with the installation of this package?

**Comment by 42wim** [comment]
Sorry for the confusion, I created the ticket because jctanner commented in #2002 to create a new bug instead of replying there. 

The issue is that I spend a lot of time looking why the yum module didn't work correctly on a RHEL5 system. It just didn't find a package in "myrepo" with e.g. "enablerepo=myrepo" specified.

After installing yum-utils everything worked fine.

Running yum manually without having yum-utils installed also worked fine.

As you commented https://github.com/ansible/ansible/issues/2002#issuecomment-20772391 and as @ex-nerd commented the module or the documentation on http://docs.ansible.com/yum_module.html should give some notice that yum-utils might be necessary. 

This will save some time for other people running in to this issue.

**Comment by mpdehaan** [comment]
What we're doing in 1.5 is to auto-install it when missing, preventing a large class of errors where it is needed and not available.

So basically this will get resolved in a different way.

Thanks!
