### ISSUE TITLE
if win_chocolatey can install Visual studio community?

### ISSUE THREAD

**Issue by blackhair3000** [ansible/ansible#60551]
when I install vs community it always had errors 

```
ERROR: Running ["C:\Users\Administrator\AppData\Local\Temp\chocolatey\visualstudio2017community\15.9.11.0\vs_community.exe" --quiet --norestart --wait] was not successful. Exit code was '1'. See log for possible error messages.",
        "The install of visualstudio2017community was NOT successful.",
        "Error while running 'C:\ProgramData\chocolatey\lib\VisualStudio2017Community\tools\ChocolateyInstall.ps1'.",
        " See log for details.",
        "",
        "Chocolatey installed 0/1 packages. 1 packages failed.",
        " See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).",
        "",
        "Failures",
        " - visualstudio2017community (exited 1) - Error while running 'C:\ProgramData\chocolatey\lib\VisualStudio2017Community\tools\ChocolateyInstall.ps1'.",
        " See log for details."]
```

So , I wander if win_chocolatey could install the Vistual studio?

**Comment by jborean93** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

Have a look at the log and see if anything jumps out at you. One thing you should try is to run thet ask with [become](https://docs.ansible.com/ansible/latest/user_guide/become.html#become-and-windows) as that fixes some issues that arise when running things through WinRM.
