### ISSUE TITLE
Modules "unarchive" and "copy" do not expand pathes correctly

### ISSUE THREAD

**Issue by muffl0n** [ansible/ansible#6061]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.5 
##### Environment:

Gentoo Base System release 2.2
##### Summary:

This simple playbook:

```
- hosts: localhost
  tasks:

  - name: ensure group test is present
    group: name=test gid=1111

  - name: ensure user test is present
    user: name=test uid=1111 home=/tmp/test

  - file: path=~test/test owner=test group=test mode=0644 state=directory

  - copy: src=test.txt dest=~test/test.txt owner=test group=test mode=0600

  - unarchive: src=test.tar.gz dest=~test
```

produces an error when being executed:

```
$ ansible-playbook test.yml 

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [ensure group test is present] ****************************************** 
ok: [localhost]

TASK: [ensure user test is present] ******************************************* 
changed: [localhost]

TASK: [file path=~test/test owner=test group=test mode=0644 state=directory] *** 
changed: [localhost]

TASK: [copy src=test.txt dest=~test/test.txt owner=test group=test mode=0600] *** 
changed: [localhost]

TASK: [unarchive src=test.tar.gz dest=~test/] ********************************* 
failed: [localhost] => {"failed": true}
msg: dest must be an existing dir

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/svs/test.retry

localhost                  : ok=5    changed=3    unreachable=0    failed=1
```

Apparently unarchive does not expand the home directory "~test/" as file and copy do. Despite the fact that the directory is expanded in https://github.com/ansible/ansible/blob/devel/library/files/unarchive#L176 the corresponding action_plugin let's it fail before the expansion: https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/action_plugins/unarchive.py#L66

I'm quite new to ansible and maybe I mixed up my conclusion. But the error exists and can only be fixed if I change 

```
- unarchive: src=test.tar.gz dest=~test
```

to

```
- unarchive: src=test.tar.gz dest=/tmp/test
```

It seems to me that the copy module does not handle this correctly, too. The call to self.runner._remote_md5() in https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/action_plugins/copy.py#L168 always returns "1" for paths that need to be expanded (like ~test in my example). It does that whether or not the remote file exists. It just doesn't find it because it doesn't expand "~test/test.txt" correctly.
It then calls (https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/action_plugins/copy.py#L295) diff_peek in the file module which itself expands the path correctly (https://github.com/ansible/ansible/blob/devel/library/files/file#L162) and returns an empty diff which the copy module then interprets correctly.

Short story: If the copy module would expand the user path before calling _remote_md5() it could stop there and would not have to call diff_peek in the file module.
##### Steps To Reproduce:
- create test-files: test.txt, test.tar.gz
- Execute above mentioned playbook
##### Expected Results:

Modules unarchive and copy should expand ~test to /tmp/test
##### Actual Results:

unarchive fails, copy does not fail but both don't expand ~test correctly/at all

**Comment by muffl0n** [comment]
Fixed by #6073

**Comment by jimi-c** [comment]
@muffl0n For future reference, if you put "Fixes #xxxx" on a line in your commit message, Github will auto-close referenced issues when the PR is merged in. It's very handy :)

**Comment by muffl0n** [comment]
Sound's great! Thanks for the hint! :)

**Comment by muffl0n** [comment]
I'm sorry that I have to reopen this issue but my tests still show some glitches.

My setup:
local: user "test" with homedir: /tmp/test
remote: user "test" with homedir: /tmp/testuser

The module "copy" works great with expanding the homedir, now:
test-copy.yml:

```
- hosts: remote
  tasks:
    - copy: src=~test/a dest=~test/a owner=root group=root
```

output:

```
$ ansible-playbook -i test test-copy.yml -vv

PLAY [remote] ***************************************************************** 

GATHERING FACTS *************************************************************** 
<remote> REMOTE_MODULE setup
ok: [remote]

TASK: [copy src=~test/a dest=~test/a owner=root group=root] ******************* 
ok: [remote] => {"changed": false, "dest": "/tmp/testuser/a", "gid": 0, "group": "root", "md5sum": "d41d8cd98f00b204e9800998ecf8427e", "mode": "0644", "owner": "root", "size": 0, "src": "/root/.ansible/tmp/ansible-tmp-1393504303.75-12870543321651/source", "state": "file", "uid": 0}

PLAY RECAP ******************************************************************** 
remote                     : ok=2    changed=0    unreachable=0    failed=0
```

But unfortunately unarchive and assemble show some misbehaviour when it comes to proper expanding of homedirs.

test-unarchive.yml:

```
- hosts: remote
  tasks:
    - unarchive: src=~test/test.tar.gz dest=~test
```

output:

```
$ ansible-playbook -i test test-unarchive.yml -vv

PLAY [remote] ***************************************************************** 

GATHERING FACTS *************************************************************** 
<remote> REMOTE_MODULE setup
ok: [remote]

TASK: [unarchive src=~test/test.tar.gz dest=~test] **************************** 
failed: [remote] => {"failed": true}
msg: dest '/tmp/test' must be an existing dir

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/svs/test-unarchive.retry

remote                     : ok=1    changed=0    unreachable=0    failed=1
```

unarchive seems to expand the destdir for the local user. Please see PR #6202 where I modified the error message so that the missing destdir is shown.

test-assemble.yml:

```
- hosts: remote
  tasks:
    - assemble: src=/tmp/test/assemble dest=~test/assemble.conf remote_src=false
    - assemble: src=~test/assemble dest=~test/assemble.conf remote_src=false
```

output:

```
$ ansible-playbook -i test test-assemble.yml -vv

PLAY [remote] ***************************************************************** 

GATHERING FACTS *************************************************************** 
<remote> REMOTE_MODULE setup
ok: [remote]

TASK: [assemble src=/tmp/test/assemble dest=~test/assemble.conf remote_src=false] *** 
ok: [remote] => {"changed": false, "dest": "/tmp/testuser/assemble.conf", "gid": 0, "group": "root", "md5sum": "6ddb4095eb719e2a9f0a3f95677d24e0", "mode": "0600", "owner": "root", "size": 4, "src": "/root/.ansible/tmp/ansible-tmp-1393504442.49-18464552407920/src", "state": "file", "uid": 0}

TASK: [assemble src=~test/assemble dest=~test/assemble.conf remote_src=false] *** 
fatal: [remote] => Traceback (most recent call last):
  File "/home/svs/workspace.kepler/ansible_source/lib/ansible/runner/__init__.py", line 525, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/svs/workspace.kepler/ansible_source/lib/ansible/runner/__init__.py", line 616, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/home/svs/workspace.kepler/ansible_source/lib/ansible/runner/__init__.py", line 802, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/home/svs/workspace.kepler/ansible_source/lib/ansible/runner/action_plugins/assemble.py", line 72, in run
    path = self._assemble_from_fragments(src, delimiter)
  File "/home/svs/workspace.kepler/ansible_source/lib/ansible/runner/action_plugins/assemble.py", line 39, in _assemble_from_fragments
    for f in sorted(os.listdir(src_path)):
OSError: [Errno 2] No such file or directory: '~test/assemble'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/svs/test-assemble.retry

remote                     : ok=2    changed=0    unreachable=1    failed=0 
```

assemble doesn't expand the source homedir at all, for dest it seems correct.

**Comment by jimi-c** [comment]
@muffl0n have you tried this with the most recent version of devel? I made another change yesterday to the code where expanduser was only done in the module rather than the action plugin (the original way you had it). Since some other modules like unarchive call the module directly without going through the action plugin, it needed to be there.

**Comment by muffl0n** [comment]
You are right! Somehow my local copy wasn't up to date. Seems I'm still having trouble understanding git. :(

However, assemble still has problems expanding the homedir correctly. I'm opening a new ticket for this.
