### ISSUE TITLE
Jail connection ignores sudo_user

### ISSUE THREAD

**Issue by mxey** [ansible/ansible#6072]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.4 
##### Environment:

I am running FreeBSD 10.0-RELEASE and managing 10.0-RELEASE jails.
##### Summary:

The connection type “jail" ignores the sudo_user setting, commands are always executed as root. 

As the connection type uses jexec already, this can probably be fixed trivially by using jexec -U 
##### Steps To Reproduce:

```
# ansible putover -U mxey -a "id"
```
##### Expected Results:

```
# ansible putover -U mxey -a "id"                                                 :(
putover | success | rc=0 >>
uid=1001(mxey) gid=1001(mxey) groups=1001(mxey),0(wheel)
```
##### Actual Results:

```
 # ansible putover -U mxey -a "id"
putover | success | rc=0 >>
uid=0(root) gid=0(wheel) groups=0(wheel),5(operator)
```

**Comment by mpdehaan** [comment]
Something you would like to help work on perhaps?

**Comment by mxey** [comment]
I am unsure if I should support sudo_user or remote_user with jexec, because it won't actually use the sudo command.

**Comment by mattclay** [comment]
Unfortunately the jexec -U option uses the current host environment as the environment within the jail.

So while some things work as expected:

```
root@:~ # jexec -U testing freebsd_10_2 grep testing /etc/passwd
testing:*:1001:1001:Testing:/home/testing:/bin/sh
```

```
root@:~ # jexec -U testing freebsd_10_2 id
uid=1001(testing) gid=1001(testing) groups=1001(testing)
```

Others do not:

```
root@:~ # jexec -U testing freebsd_10_2 /bin/sh -c 'echo $HOME'
/root
```

At a minimum, we'll need $HOME to be correct in the jail. This may be a starting point:

```
root@:~ # jexec -U testing freebsd_10_2 env -i sh -c 'HOME=~testing env'
PWD=/
HOME=/home/testing
```
