### ISSUE TITLE
Ping module fails if local locale does not exist on remote end

### ISSUE THREAD

**Issue by stemid** [ansible/ansible#608]
Steps to reproduce this. 
1. Have a locale set on your local end that does not exist on the remote end. 
2. Use ANSIBLE_TRANSPORT=ssh
3. Use ping or copy module on the host. 

Result: Connection closed with error or without any action. 

Example, my local locale is sv_SE.UTF-8 and using the ssh transport method I assume this gets sent over to the remote end. However when the remote Debian machine has not generated the locale sv_SE.UTF-8 using locale-gen yet, the ping module will fail with this error. 

vmlnx-stats01 | FAILED => failed to transfer file to bash: warning: setlocale: LC_ALL: cannot change locale (sv_SE.UTF-8)/ping:

Workaround is to manually generate the locale. 

In normal ssh you would only receive this warning but you would still get a working shell. 

-bash: warning: setlocale: LC_ALL: cannot change locale (sv_SE.UTF-8)

I found it impossible to copy my own locale.gen file until I had generated the proper locale so it's quite possible this goes beyond the ping module. I do not have the python knowledge necessary to investigate.

**Comment by mpdehaan** [comment]
so the way we invoke things this interferes with parsing of returns and such.   I haven't heard this reported before so I think the best answer is to just fix your shell settings, as we probably can't predict all the possible error messages that may come back.
