### ISSUE TITLE
UnboundLocalError: local variable 'vault_pass' referenced before assignment

### ISSUE THREAD

**Issue by djatlantic** [ansible/ansible#6082]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.x
##### Environment:

N/A
##### Summary:

ansible-playbook and --list-hosts gives the following traceback ...

```
Traceback (most recent call last):
  File "/usr/local/ansible/bin/ansible-playbook", line 287, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/ansible/bin/ansible-playbook", line 177, in main
    vault_password=vault_pass
UnboundLocalError: local variable 'vault_pass' referenced before assignment
```
##### Steps To Reproduce:

```
ansible-playbook site.yml --list-hosts
```
##### Expected Results:

No traceback
##### Actual Results:

Traceback

**Comment by jctanner** [comment]
So this appears to have been only possible with --list-hosts. Fixing it now.
