### ISSUE TITLE
action_plugins are not loaded relative to current playbook

### ISSUE THREAD

**Issue by dhorbach** [ansible/ansible#6089]
##### Issue Type:

“Bug Report”
##### Ansible Version:

1.4.5, 1.5 HEAD

$ ansible --version
ansible 1.5 (devel 7fe3db408d) last updated 2014/02/20 13:06:06 (GMT +400)
##### Environment:

Centos 6.4
##### Summary:

I'm trying to test the following statement from docs
"In addition, plugins can be shipped in a subdirectory relative to a top-level playbook, in folders named the same as indicated above."
action_plugins are not loaded but callback_plugins are ok
##### Steps To Reproduce:

test.yml
action_plugins/extract
callback_plugins/test_callback.py

in test.yml:
- hosts: all
  tasks:
  - extract: name=test
##### Expected Results:

Playbook is executed without errors
##### Actual Results:

ansible-playbook -c local -i "localhost," test.yml
ERROR: extract is not a legal parameter in an Ansible task or handler

**Comment by mpdehaan** [comment]
So the problem above is that actual plugins need to be named with ".py" extensions, since they are modules, so this is not a bug.

Please stop by the user mailing list (ansible-project) if you have more questions.

Thanks!

**Comment by dhorbach** [comment]
Unfortunately adding .py extension didn't help
