### ISSUE TITLE
stat module crashes when a file is not readable because of MD5 sum checking

### ISSUE THREAD

**Issue by rassie** [ansible/ansible#6092]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.5
##### Environment:

SLE11SP3
##### Summary:

stat module crashes
##### Steps To Reproduce:

I'm trying to check whether my logging configuration is correct and log files are readable by the proper user. However, if a file is not readable, `stat` module will crash:

```
fatal: [server] => failed to parse: Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-1392907809.76-248263014378401/stat", line 1163, in <module>
    main()
  File "/home/user/.ansible/tmp/ansible-1392907809.76-248263014378401/stat", line 124, in main
    d['md5']        = module.md5(path)
  File "/home/user/.ansible/tmp/ansible-1392907809.76-248263014378401/stat", line 1005, in md5
    return self.digest_from_file(filename, _md5())
  File "/home/user/.ansible/tmp/ansible-1392907809.76-248263014378401/stat", line 995, in digest_from_file
    infile = open(filename, 'rb')
IOError: [Errno 13] Permission denied: '/var/log/log'
```

**Comment by mpdehaan** [comment]
Agree it should return failed=True, msg="file is not readable" instead.

Thanks for the report!

**Comment by rassie** [comment]
I don't think I agree -- there are a lot of situations where an unreadable file is correct behaviour. Also, a lot of information about a file can be checked "from the outside", i.e. without reading its contents. I think an MD5 sum should be skipped if a file can't be read or maybe moved to a different script altogether -- "stat" suggests it's the same as command line 'stat', which does not peek into files.
