### ISSUE TITLE
Creating new Security Group with ec2_group module sometimes results in an exception: "The security group 'sg-xxxxxxxx' does not exist"

### ISSUE THREAD

**Issue by ap1kenobi** [ansible/ansible#6098]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5 (devel /eb26cca29f/) last updated 2014/02/20 00:07:28 (GMT -400)
##### Environment:

Ansible workstation: OSX 10.9.1
Target managed OS: N/A
##### Summary:

Provisioning a **new** Security Group in AWS with ec2_group module sometimes results in error: The security group 'sg-xxxxxxxx' does not exist
##### Steps To Reproduce:

This is an intermittent issue and seems to depend on time of the day - it happens more often during the day in the us-east-1 Region.  Subsequent replay of the failed task results in the expected outcome: security group is created without exceptions.

The following snippet illustrates one of the ansible tasks that results in the above exception, where `env_name:DEV`, `env_vpc_id:vpc-xxxxxxxx`, `env_region: us-east-1` :

```

---
# Create/maintain VPC-wide SSH security group
# -------------------------------------------------------------------------------------------------------------
- name: Maintaining {{ env_name | upper }}-SSH security group
  local_action:
    module: ec2_group
    name: "{{ env_name | upper }}-SSH"
    description: Allow Inbound SSH
    vpc_id: "{{ env_vpc_id }}"
    region: "{{ env_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
  register: sg
```
##### Expected Results:

Security group 'DEV-SSH' is created in a VPC (id: vpc-xxxxxxxx) with a single rule allowing traffic on port 22 from 0.0.0.0/0
##### Actual Results:

The following stack trace is output into the terminal:

```
TASK: [aws-provisioner | Maintaining PCE-SSH security group] ************** 
failed: [localhost] => {"failed": true, "item": "", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/alex/.ansible/tmp/ansible-tmp-1392915376.39-153207393590494/ec2_group", line 1421, in <module>
    main()
  File "/Users/alex/.ansible/tmp/ansible-tmp-1392915376.39-153207393590494/ec2_group", line 236, in main
    group.authorize(rule['proto'], rule['from_port'], rule['to_port'], ip, grantGroup)
  File "/Library/Python/2.7/site-packages/boto/ec2/securitygroup.py", line 204, in authorize
    dry_run=dry_run)
  File "/Library/Python/2.7/site-packages/boto/ec2/connection.py", line 3141, in authorize_security_group
    params, verb='POST')
  File "/Library/Python/2.7/site-packages/boto/connection.py", line 1180, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidGroup.NotFound</Code><Message>The security group 'sg-e4f62381' does not exist</Message></Error></Errors><RequestID>ad70c083-d6b8-4a8b-be46-6a5a7167d5e2</RequestID></Response>


FATAL: all hosts have already failed -- aborting
```

**Comment by ap1kenobi** [comment]
I can take this one, btw.

**Comment by rafaelzimmermann** [comment]
Did you discovery what was causing the exception?

**Comment by evanccnyc** [comment]
I see this as well. Its quite frustrating.

**Comment by ap1kenobi** [comment]
@rafaelzimmermann, I haven't debugged this completely but fundamentally it seems the issue is async nature of AWS and boto's reluctance (inability? bug?) to refresh state of recently created objects.  I observed (and improved) a similar issue in ec2_vpc module when creating subnets.  The fix is to wait in a loop until the object has been created (security group in this case) before doing anything else with it.  
I've been swamped at work and at home, otherwise I'd fix this already.

**Comment by crashdump** [comment]
Any update on this issue ? It seems to happen a lot recently.

**Comment by evanccnyc** [comment]
I wrote a pull request for this:

https://github.com/ansible/ansible/pull/7653

Still waiting for it to be checked in.

**Comment by jimi-c** [comment]
@evanccopengeo if we can get others to test that out a bit more today, I can get it merged in sooner (cc: @crashdump/@ap1kenobi).

**Comment by evanccnyc** [comment]
I ran the test about 25 times and my patch seemed to fix the problem, however testing by someone else is always good.

**Comment by ap1kenobi** [comment]
I can confirm this is working, i.e.: no errors from Ansible.

**Comment by crashdump** [comment]
Seems to have fixed the issue on my side too. Thanks !

**Comment by jimi-c** [comment]
Thanks all, I'll go ahead and merge that PR in.

**Comment by jimi-c** [comment]
Done, please let us know if you see any further problems regarding this. Thanks!

**Comment by theharshest** [comment]
I'm seeing this issue. I'm using development branch, this way - https://github.com/ansible/ansible/tree/devel/hacking

**Comment by jimi-c** [comment]
@theharshest could you please open a new issue for this, with detailed output per the issue template? Thanks!
