### ISSUE TITLE
Filters should be their own chapter in playbooks, as opposed to be in the vars chapter?

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#6099]
##### Issue Type:

Docs Report
##### Ansible Version:

N/A
##### Environment:

N/A
##### Summary:

In the docs, various things are discussed in the variables chapter that I would like to be in the sidebar as seperate topics.   The foremost of these are filters.
##### Steps To Reproduce:

Read the variables chapter or go look for filters on the sidebar and not find it
##### Expected Results:

Filters would be a chapter on the sidebar
##### Actual Results:

Filters are not in the sidebar, but are in the variables chapter, so you have to know where to look for them.

**Comment by jimi-c** [comment]
Closing, as we will address doc cleanups at a later date.
