### ISSUE TITLE
All sections in docs should have named anchors

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#6100]
##### Issue Type:

Documentation Report
##### Ansible Version:

N/A
##### Environment:

N/A
##### Summary:

Want to eliminate stuff like #id22 in hyperlinks in the docs such that they are permanent.
##### Steps To Reproduce:

Read the docs, observe bad hyperlinks
##### Expected Results:

hyperlinks like page.html#this_is_a_topic
##### Actual Results:

hyperlinks like page.html#id22

**Comment by nickhammond** [comment]
Looks like this issue can be closed by looking at the current docs:
- http://docs.ansible.com/playbooks_intro.html#handlers-running-operations-on-change
- http://docs.ansible.com/test_strategies.html#check-mode-as-a-drift-test

**Comment by jimi-c** [comment]
Closing, as we will be addressing doc cleanup/updates at a later date and via the input of our technical writer.
