### ISSUE TITLE
shell: chdir=SOMETHING does not seem execute the script in the chdir

### ISSUE THREAD

**Issue by risaacson** [ansible/ansible#6102]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5 (devel 0719be852f) last updated 2014/02/20 16:56:40 (GMT -400)
##### Environment:

Centos 6
##### Summary:

I am working on putting together some of the new tests and I can execute a script via the full path it works. When I try to use a chdir it can't find the script.
##### Steps To Reproduce:

I expect that in files we have a script called test.sh:

```
#!/usr/bin/env bash

echo -n 'win"
```

With this task

```
- name: execute the test.sh script with chdir
  shell: test.sh chdir="{{output_dir_test}}"
  register: shell_result0
```
##### Expected Results:

```
changed: [testhost] => {"changed": true, "cmd": "~/ansible_testing/test_command_shell/test.sh ", "delta": "0:00:00.005797", "end": "2014-02-20 17:06:33.039538", "item": "", "rc": 0, "start": "2014-02-20 17:06:33.033741", "stderr": "", "stdout": "win"}
```
##### Actual Results:

```
failed: [testhost] => {"changed": true, "cmd": "test.sh ", "delta": "0:00:00.002834", "end": "2014-02-20 17:06:33.129274", "item": "", "rc": 127, "start": "2014-02-20 17:06:33.126440"}
stderr: /bin/sh: test.sh: command not found

FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
chdir is proven to work

```
- hosts: all
  gather_facts: False
  tasks:
    - shell: echo "hi" > foo chdir=/tmp
```

The problem here is your path doesn't have . in it or ./test.sh isn't in it
