### ISSUE TITLE
Route53 error when creating a TXT record

### ISSUE THREAD

**Issue by spatten** [ansible/ansible#6112]
##### Issue Type:

Bug Report
##### Ansible Version:

```
# ansible --version
ansible 1.4.5
```
##### Environment:

Running on OS X. Managing Ubuntu 12.04 LTS on AWS.
##### Summary:

I can't create a TXT record with the route53 module
##### Steps To Reproduce:

Run this playbook:

```
tasks:
  - route53: >
      command=create
      zone={{ domain }}
      record={{ domain }}
      type=TXT
      value="test"
      overwrite=true
      aws_access_key={{ aws_access_key }}
      aws_secret_key={{ aws_secret_key }}
```

Things work fine if I try to create a CNAME or A or MX record with the same variables. For example, this works:

```
- route53: >
    command=create
    zone={{ domain }}
    record=www.{{ domain }}
    type=CNAME
    value={{ domain }}
    aws_access_key={{ aws_access_key }}
    aws_secret_key={{ aws_secret_key }}
```

For TXT records I get the following error:

```
msg: Invalid Resource Record: FATAL problem: InvalidTXTRDATA encountered at test
```

I've checked and checked and I'm pretty sure that it's not me.
##### Expected Results:

A TXT record is created
##### Actual Results:

I get the following output:

```
msg: Invalid Resource Record: FATAL problem: InvalidTXTRDATA encountered at test
```

**Comment by spatten** [comment]
Sorry, I figured out the problem. TXT records need to be surrounded by double-quotes. This works:

```
- route53: >
    command=create
    zone={{ domain }}
    record={{ domain }}
    type=TXT
    value='"test"'
    overwrite=true
    aws_access_key={{ aws_access_key }}
    aws_secret_key={{ aws_secret_key }}
```

**Comment by conrado** [comment]
Anyone else think this is kind of wrong?

**Comment by bseddon** [comment]
@spatten Thanks for posting the fix.  Who would have thought...

**Comment by RRAlex** [comment]
For others trying to fit 2 values in a TXT record, the format is without brackets or lists, but simply by single quoting all the values once:

`value: '"First value", "2nd val"'`
