### ISSUE TITLE
don't uninstall wget while integration testing 'apt'

### ISSUE THREAD

**Issue by Azulinho** [ansible/ansible#6129]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.4
##### Environment:

N/A
##### Summary:

In https://github.com/ansible/ansible/blob/devel/test/integration/roles/test_apt/tasks/apt.yml

the tests to test that 'apt is working' are uninstalling 'wget' before re-installing it, for the sake of 'just testing apt' consider using a package that may not be used anywhere in the system such as the 'hello' package.
its very likely that removing 'wget' from a live system could break some running applicational code
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
Fixed per the above, thanks!
