### ISSUE TITLE
apt_repository fails when adding a PPA

### ISSUE THREAD

**Issue by Bilge** [ansible/ansible#6132]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.4
##### Environment:

Ubuntu 12.04
##### Summary:

apt_repository always fails when adding a PPA complaining pycurl is not installed.
##### Steps To Reproduce:
1. apt-get install python-pycurl
2. run the following task:

``` yml
- name: Subscribe to ondrej PHP5 repo
  apt_repository: repo=ppa:ondrej/php5
```
##### Expected Results:

No missing pycurl error.
##### Actual Results:

> msg: Could not import python modules: pycurl. Please install python-pycurl package.
##### Additional Notes:

Running python from the command line and inputting `import pycurl` does not cause an error.

**Comment by mpdehaan** [comment]
So you need to install pycurl like it says to use this module.  This is not a bug, this is an instruction to you that it is required.

Feel free to stop by the mailing list to ask questions.

**Comment by Bilge** [comment]
What the fuck? Did you even read a word of this report?

> ##### Steps To Reproduce:
> 
>    apt-get install python-pycurl
> 
> Running python from the command line and inputting `import pycurl` **does not cause an error**.

**Comment by nicknovitski** [comment]
Pycurl is required on the node. It sounds like you might have installed it on the control machine instead?

This is what worked for me when I had the identical issue:

``` yaml
- name: install pycurl package in order to use the apt_repository module
    apt: pkg=python-pycurl state=present
    sudo: yes
```
