### ISSUE TITLE
Pre-commands used by "nxos_command"

### ISSUE THREAD

**Issue by ibarrere** [ansible/ansible#61326]
##### SUMMARY

What are the steps that "nxos_command" (with connection: network_cli) takes before running the specified command? I can't find documentation for that. 

For some reason, when issuing "show archive log config all" on two of my Nexus 31108TCVs, the index number decrements by one each time on one switch, but does not on the other. I can't reproduce this by running the commands manually on the device itself, so it seems to be something to do with ansible. I'm not sure it's a bug yet, but I'd like to gather more information before either opening a bug report or opening a ticket with Cisco.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

nxos_command (or maybe network_cli)

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /home/ibarrere-a/git/dv-ansible/ansible.cfg
  configured module search path = [u'/home/ibarrere-a/git/dv-ansible/library']
  ansible python module location = /opt/ansible/source/lib/ansible
  executable location = /opt/ansible/source/bin/ansible
  python version = 2.7.9 (default, Nov 18 2015, 13:07:23) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o ServerAli
CACHE_PLUGIN(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = ./cache
CACHE_PLUGIN_TIMEOUT(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = 86400
DEFAULT_FORKS(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = 25
DEFAULT_GATHERING(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = [u'/home/ibarrere-a/git/dv-ansible/inventory/production']
DEFAULT_LOG_PATH(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MANAGED_STR(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = Ansible managed from {host}
DEFAULT_MODULE_PATH(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = [u'/home/ibarrere-a/git/dv-ansible/library']
DEFAULT_POLL_INTERVAL(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = 7
DEFAULT_ROLES_PATH(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = [u'/home/ibarrere-a/git/dv-ansible/roles']
DEFAULT_TIMEOUT(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = 60
DEFAULT_VAULT_PASSWORD_FILE(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = /home/ibarrere-a/git/dv-ansible/open_the_vault.sh
DISPLAY_SKIPPED_HOSTS(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = 100
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = 100
PERSISTENT_CONNECT_TIMEOUT(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = 100
RETRY_FILES_SAVE_PATH(/home/ibarrere-a/git/dv-ansible/ansible.cfg) = /home/ibarrere-a/.ansible-retry
```

##### OS / ENVIRONMENT

CentOS release 6.10 (Final)

**Comment by NilashishC** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible-network on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
