### ISSUE TITLE
apt_repository always fails when adding a PPA

### ISSUE THREAD

**Issue by Bilge** [ansible/ansible#6133]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.4
##### Environment:

Ubuntu 12.04
##### Summary:

apt_repository always fails when adding a PPA complaining pycurl is not installed.
##### Steps To Reproduce:
1. apt-get install python-pycurl
2. run the following task:

``` yml
- name: Subscribe to ondrej PHP5 repo
  apt_repository: repo=ppa:ondrej/php5
```
##### Expected Results:

No missing pycurl error.
##### Actual Results:

> msg: Could not import python modules: pycurl. Please install python-pycurl package.
##### Additional Notes:

Running python from the command line and inputting `import pycurl` does not cause an error.

Reopening because @mpdehaan is ignorant and condescending, refusing to read issues before closing them.

**Comment by mpdehaan** [comment]
That's not quite fair -- issue was misread, if anything.  Don't assume because someone misread something they were being anything but misreading something.   

This is an open source project and we do ask that people treat each other with respect.  (See contributing.md)

**Comment by mpdehaan** [comment]
I can't reproduce this issue.

Here's the relevant code, from the 1.4.4 branch:

```
try:
    import pycurl
    HAVE_PYCURL = True
except ImportError:
    HAVE_PYCURL = False
```

Here's my dpkg output on Ubuntu 12.04:

```
root@llamacube:/root/ansible# dpkg -s python-pycurl
Package: python-pycurl
Status: install ok installed
Priority: optional
```

Command:

```
ansible localhost -i "localhost," -m "apt_repository" -a "repo=ppa:ondrej/php5" -c local
```

If you would try installing with pip as an experiment I would be curious if that has any affect on your system.

I think most likely you have run the import on a different system, this would be required on the managed system, not the local one.

**Comment by Bilge** [comment]
The error message needs to be clearer, then, since I thought it had to be installed on the control machine. I dislike having to install things on the target machine in order to get Ancible to run. It wasn't worth it, either, since it just spews GPG errors now.
