### ISSUE TITLE
using win_update to install updates on server 2012 R2 returns 0 updates found but shows up updates to be installed in Software Center

### ISSUE THREAD

**Issue by haroonhanif** [ansible/ansible#61381]
Please raise issues via the [new interface](https://github.com/ansible/ansible/issues/new/choose)

Hi,
We are trying to update our windows servers using ansible using manage_server option but it comes back with 0 updates found, 

COMPONENT NAME
win_update module

 Ansilbe module win_update

ANSIBLE VERSION
 ansible 2.8.0
  
The playbooks is as follows
![image](https://user-images.githubusercontent.com/48482560/63782689-aef60180-c8e3-11e9-9a53-1aa472f91863.png)

![image](https://user-images.githubusercontent.com/48482560/63780896-c7185180-c8e0-11e9-827c-a3e88473b0e6.png)

I have the following configuration on the windows server which is to be updated
Following is configured on the server to point to the sccm server
![image](https://user-images.githubusercontent.com/48482560/63780947-de573f00-c8e0-11e9-9903-68a508fbdd05.png)

configure Automatic updates have the following settings
![image](https://user-images.githubusercontent.com/48482560/63781198-4ad23e00-c8e1-11e9-8f80-083c18ece62b.png)

Do Not connect to any windows update internet locations setting is enabled as follows
![image](https://user-images.githubusercontent.com/48482560/63781320-7e14cd00-c8e1-11e9-9847-527b91eb25c3.png)

Allowing Signed updates from intranet Microsoft update service location is enabled as follows
![image](https://user-images.githubusercontent.com/48482560/63782151-e1ebc580-c8e2-11e9-8b13-2ce11d4981bd.png)

Registry settings are as follows
![image](https://user-images.githubusercontent.com/48482560/63782372-3727d700-c8e3-11e9-9e55-8a6d4a4ff3c5.png)
![image](https://user-images.githubusercontent.com/48482560/63782421-4870e380-c8e3-11e9-8e26-9d2bab1f051c.png)

updates to be installed are showing up in the software centre
but when we run above ansible playbook, updates wont install and it will comeback with the message, no updates needed
log file show below information
![image](https://user-images.githubusercontent.com/48482560/63781104-237b7100-c8e1-11e9-87b3-e024fb26b9e0.png)

Could you please advise if I am missing anything, your help is greatly appreciated.
Kind Regards,

**Comment by ShachafGoldstein** [comment]
Keep in mind that software center and the api for win updates aren't the same, what does the local windows update UI says?

**Comment by haroonhanif** [comment]
Thanks ShachafGoldstein for replying
I have the following settings in the windows update UI
![image](https://user-images.githubusercontent.com/48482560/63787734-32b3ec00-c8ec-11e9-94bb-edabaae55678.png)
![image](https://user-images.githubusercontent.com/48482560/63787874-79094b00-c8ec-11e9-8668-c60a910bc040.png)

Kind Regards

**Comment by ShachafGoldstein** [comment]
You can see here that no updates are available, I believe this is because
of the differences between the updates in windows to how systemcenter
manages them, basically system center only uses the updates api for reports
and deployment but you won't see the updates from the UI.

This is a feature of sccm updates deployment and not a bug.

T deploy updates you wpuld have to use sccm itself or its powershell.

**Comment by haroonhanif** [comment]
Thanks ShachafGoldstein,
Could you please recommend as to how we can use ansible to deploy windows updates to servers which don't have internet connection as we are looking to automate the patching setup and rather than pushing updates from SCCM we would like the servers to pull updates from the SCCM server.
Also ansible gives us the option of whitelist and blacklist the updates.

Kind Regards,

**Comment by ShachafGoldstein** [comment]
The github issues are for features, bugs, etc.

Please ask on the mailing list or irc for help on the matter.

You could Google to see how it is done in powershell and use that with
proper modules in ansible.

**Comment by haroonhanif** [comment]
Hi ShachafGoldstein,

Thanks for your help,
Could you please tell us what is the use case for the Server Selection option which gives you choices of 
- default
- Managed_Server
- Windows update
and it clearly specifies SCCM as shown below.

![image](https://user-images.githubusercontent.com/48482560/63839198-ae5a7b00-c976-11e9-9c09-fcbceabd2ce0.png)
As our production environment has restriction for servers going to the internet and we have SCCM as update repository, we would like to utilise that.

I hope you understand my concern
Kind Regards,

**Comment by ShachafGoldstein** [comment]
This is the original pr that added the support
https://github.com/ansible/ansible/pull/51334

As I said above, sccm handles the updates using wsus but not using regular
update mechanisms I.e your ansible and your server update UI returned the
same expected result. Please read on various web results how to deploy
updates in sccm in a scripted way.

Either way this is not a bug. Please use the mailing list and proper
methods for usage examples and help.

**Comment by jborean93** [comment]
Agreed with the above, win_updates just calls the same API as the GUI which as you’ve tested returns no updates available. The module is doing what it should be doing. Please direct further questions to our mailing list or IRC
