### ISSUE TITLE
redis cache plugin broken

### ISSUE THREAD

**Issue by ei-grad** [ansible/ansible#61413]
Adding the `fact_caching = redis` to `ansible.cfg` makes ansible to print warning:

```
 [WARNING]: No setting was provided for required configuration plugin_type: cache plugin: redis setting:
_uri
```

**Comment by s-hertel** [comment]
In addition to setting `fact_caching = redis` in ansible.cfg you'll need to configure _uri (the fact_caching_connection setting in ansible.cfg or the ANSIBLE_CACHE_PLUGIN_CONNECTION environment variable). For the redis plugin this will be a host:port:database value. For example:
```
[defaults]

fact_caching = redis
fact_caching_connection = localhost:6379:0
```

**Comment by bcoca** [comment]
closing as per above, the warning is explaining you need to also set the `_uri` parameter, one way to do that is with `fact_caching_connection` as shown above
