### ISSUE TITLE
k8s module does not honor validate_certs and ca_cert

### ISSUE THREAD

**Issue by sreber84** [ansible/ansible#61435]
##### SUMMARY
The `k8s` module offers configuration of `ca_cert` and `validate_certs` to address certificate chain not available in the systems default trust store. Unfortunately setting `ca_cert` and/or `validate_certs` does not have any effect as the values are not picked up by the underlying tooling.

Applying a fix such as shown below allows the usage of `ca_cert` and `validate_certs` and prevents a fall back to the systems CA trust store (respectively would skip SSL validation).

```
$ diff -ru /usr/lib/python3.7/site-packages/ansible/module_utils/k8s/common.py.orig /usr/lib/python3.7/site-packages/ansible/module_utils/k8s/common.py
--- /usr/lib/python3.7/site-packages/ansible/module_utils/k8s/common.py.orig	2019-08-28 15:31:54.721356415 +0200
+++ /usr/lib/python3.7/site-packages/ansible/module_utils/k8s/common.py	2019-08-28 15:32:26.383649233 +0200
@@ -180,6 +180,8 @@
                 else:
                     setattr(configuration, key, value)
 
+        configuration.verify_ssl = self.params.get('validate_certs')
+        configuration.ssl_ca_cert = self.params.get('ca_cert')
         kubernetes.client.Configuration.set_default(configuration)
         return DynamicClient(kubernetes.client.ApiClient(configuration))
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`k8s` module

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/sreber/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 16:32:37) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
```

##### OS / ENVIRONMENT
```
$ uname -r
5.2.8-200.fc30.x86_64
```

##### STEPS TO REPRODUCE
Simply run the below playbook

```
$ cat main.yml 
---
- hosts: localhost
  tasks:
  - name: Create a k8s namespace
    k8s:
      name: testing
      host: https://openshift.example.com
      api_key: "<token>"
      validate_certs: True
      ca_cert: "/<path-to>/ca.crt"
      api_version: v1
      kind: Namespace
      state: present
```

##### EXPECTED RESULTS
Namespace `testing` being created

##### ACTUAL RESULTS
SSL verification error as certificate chain could not be validated and also verification can not be skipped as both values are not passed to the respective client running the task.

**Comment by fabianvf** [comment]
resolved_by_pr #57418
