### ISSUE TITLE
Documentation of command suboptions in networking command modules is suboptimal

### ISSUE THREAD

**Issue by Qalthos** [ansible/ansible#61441]
##### SUMMARY

We get a lot of issues with the `prompt` suboption on `[netos]_command` modules, and I think this has to do with the option being lightly documented at best.

* Should we change from `prompt` to `prompt_regex` or similar? A lot of prompts end with default values in brackets that make it hard to easily capture the prompt
* Alternately, is it possible to make prompt regex matching toggleable in some way? Having access to regexes is useful (and makes matching prompts easy), but can be surprising if unexpected.
* Regardless, I think more should be done to make clear that when a regex is being used, characters like ?, [, and ] need to be escaped to be used.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

eos_command
ios_command
et al.

##### ANSIBLE VERSION

```paste below
ansible 2.9.0.dev0
  config file = None
  configured module search path = ['/home/nate/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nate/workspace/ansible/ansible/lib/ansible
  executable location = /home/nate/.local/virtualenvs-Arch/ansible-test/bin/ansible
  python version = 3.7.4 (default, Jul 16 2019, 07:12:58) [GCC 9.1.0]
```

**Comment by samccann** [comment]
Fixed by #66584
