### ISSUE TITLE
uninstalled locale with UTF-8 encoding is set to C (ASCII) by ansible

### ISSUE THREAD

**Issue by JonnyJD** [ansible/ansible#61457]
##### SUMMARY
The user running ansible (client system) has some locale set.
For this example I take ```LC_ALL=de_DE.UTF-8```.
Note that this locale includes UTF-8 as encoding, as is something like a "current default" and important for any scripts not only using ASCII characters.

The server also has some (different, but UTF-8) encoding set, for example: ```en_GB.UTF-8```

The locale "survives" ssh with these common ssh settings (like set on Ubuntu):
ssh_config: ```SendEnv LANG LC_*```
sshd_config: ```AcceptEnv LANG LC_*```

Ansible runs ```setlocale``` (in ```_check_locale```).
This fails if the locale from the client is not installed on the server.
Which is usually fine, since most tools just ignore the invalid locale env and use the default.

However, Ansible forces to set the ```C``` locale.
For messages this is effectively the same, but not for the *encoding*,
which is set effectively to ASCII.

Some tools like javac (and ant, using javac) take the encoding from the locale
and fail on non-ASCII characters in source files.
This is just one example. Of course there are workarounds like setting/forcing the encoding in the tools.

The issue is just that Ansible takes a valid encoding (UTF-8) and forces ASCII,
just because the language is not installed.
This led to a really difficult to find bug on our end because everything was working fine without ansible (same server, same client system) and we didn't expect the client locale to have an impact, when it doesn't when logging in directly via ssh.
(we fixed it by changing the ant config, but I think the behavior of Ansible is "not nice", for "non-ASCII people")

This is related to #10698, but I don't care if it is handed through or the server locale is used.
The end result should just be UTF-8 encoding in the locale when both, host and server have it set in the locale.
#10717 wanted to force ```C``` locale, but was closed. I agree with @ringerc there.

The problem was introduced, as far as I can see, with 285d9878ae98dadaaa9dfc240065ebbd2aec93f4 as a fix for #7448

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module_utils/basic.py

##### ANSIBLE VERSION
```
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jonnyjd/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.7.3 (default, Jun 24 2019, 04:54:02) [GCC 9.1.0]
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/home/jonnyjd/git/server-config/ansible.cfg) = ['/home/jonnyjd/git/server-config/inventory']
DEFAULT_LOG_PATH(/home/jonnyjd/git/server-config/ansible.cfg) = /home/jonnyjd/git/server-config/ansible.log
DEFAULT_STDOUT_CALLBACK(/home/jonnyjd/git/server-config/ansible.cfg) = debug
```

##### OS / ENVIRONMENT
host and target are Linux
LC_ALL=de_DE.UTF-8 on client
en_GB.UTF-8 on server

##### STEPS TO REPRODUCE
test.yml
```yaml
- name: test
  hosts:
    - local-dev
   tasks:
    - name: get env
      shell: env | grep LC
      register: env
    - debug: var=env
```

/etc/ssh/sshd_config (server, probably needs ssh restart)
```
AcceptEnv LANG LC_*
```

/etc/ssh/ssh_config (client)
```
SendEnv LANG LC_*
```

and running
```
LC_ALL=de_DE.UTF-8 ansible-playbook test.yml
```

I tested this with a local Ubuntu 18 LTS VM having locale set to en_GB.UTF-8
It should work as lonk as the locale above (de_DE.UTF-8) is not installed and AcceptEnv is set.
If the locale is installed, try another one that isn't.

##### EXPECTED RESULTS
```
ok: [local-dev] => {
    "env": {
        "changed": true,
        "cmd": "env | grep LC",
...
        "stdout_lines": [
            "LC_ALL=de_DE.UTF-8"
        ]
    }
}
```
or en_GB.UTF-8, that would also be fine.
Even C.UTF-8 would fork for me.

##### ACTUAL RESULTS
```
<141.42.181.210> (0, b'/home/ansible\n', b'bash: warning: setlocale: LC_ALL: cannot change locale (de_DE.UTF-8)\n')
...
ok: [local-dev] => {
    "env": {
        "changed": true,
        "cmd": "env | grep LC",
...
        "stdout": "LC_MESSAGES=C\nLC_ALL=C",
        "stdout_lines": [
            "LC_MESSAGES=C",
            "LC_ALL=C"
        ]
    }
}
```

**Comment by JonnyJD** [comment]
For reference, this is a typical error running ``ant`` via ansible (with non-ASCII in files and no explicit encoding set):
```
error: unmappable character (0xC3) for encoding US-ASCII (running test.yml with ansible)
```
Running ant is not part of the test playbook above, but running ant with the setup above boils down to
```
LC_ALL=C ant
```
Similar when running javac directly with LC_ALL=C (as set by ansible).

**Comment by andreaskaris** [comment]
+1 When executing ansible from within the latest Fedora 31 docker container (fedora:31 from docker.io) system and using it against Rhel 7, I get:
~~~
TASK [Gathering Facts] *********************************************************
fatal: [undercloud-0]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 172.16.0.92 closed.\r\n", "module_stdout": "/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)\r\n/bin/sh: -c: line 0: syntax error near unexpected token `('\r\n/bin/sh: -c: line 0: `/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)\r'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
~~~

This seems to be the same issue:
~~~
[root@undercloud-0 ~]# export LC_CTYPE=C.UTF8
-bash: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF8)
-bash: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF8)
~~~

~~~
[infrared@fedora-infrared-f879bdb66-5qgtq /]$ ansible --version
ansible 2.7.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/infrared/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.5 (default, Oct 17 2019, 12:16:48) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
~~~

The container only has the C.UTF-8 locale by default:
~~~
[infrared@fedora-infrared-f879bdb66-5qgtq /]$ locale -a | grep -i utf
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C.utf8
~~~

Assuming that we can simply fall back to C.UTF-8 seems a bit bold given that in RHEL 7, this doesn't work at all:
https://bugzilla.redhat.com/show_bug.cgi?id=1361965

**Comment by bcoca** [comment]
In this case we do not believe this to be a bug with Ansible as it does the expected (fallback to POSIX/C) but with the system  configuration that forces a locale from onto the remote without ensuring it exists.

As such I'm going to close this issue and advise to either install the locales remotely or disable sending locale via ssh for the ansible user.
