### ISSUE TITLE
Be able to escape comment character (#) in main inventory file

### ISSUE THREAD

**Issue by lechat** [ansible/ansible#6147]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5 (devel e2a47162d0) last updated 2014/02/25 00:24:12 (GMT +800) 
##### Environment:

Running: Ubuntu 13.0, CentOS 5.6
Managing: Ubintu 13.0, RHEL 5.6
##### Summary:

Unable to have `#` (hash) symbol in ssh password.
##### Steps To Reproduce:
1. Create user `test` and set its password to `123#456`. 
2. Create inventory:

```
localhost ansible_ssh_pass=123#456 ansible_ssh_user=test
```
1. Execute `ansible -i inventory all -m ping`
##### Expected Results:

Connect to host using password containing `#` and all variables after that symbol to be used. 
##### Actual Results:

```
aleksey@ubuntu ~/src/ansible [devel]
± % ansible -i /home/aleksey/src/inventory all -m ping -vvvv                                                                                                                                                                !3995
<localhost> ESTABLISH CONNECTION FOR USER: aleksey
<localhost> REMOTE_MODULE ping
<localhost> EXEC ['sshpass', '-d6', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/aleksey/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'ConnectTimeout=10', 'localhost', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1393259374.1-140698509289331 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1393259374.1-140698509289331 && echo $HOME/.ansible/tmp/ansible-tmp-1393259374.1-140698509289331'"]
localhost | FAILED => Authentication failure.
```

All inventory variables after `#` symbol are ignored: in this example ansible tries to connect as user `aleksey` while `ansible_ssh_user=test`. 

This is caused by line 68 in `inventory/ini.py` which tries to strip comments from inventory line. So when it encounters hash anywhere - it is treated as start of comment. I think that start of the comment have to be `#<space><space>` so hashes in variables will be treated gracefully.

**Comment by mpdehaan** [comment]
There's an easy workaround for this: as you can store this via host_vars/ or group_vars/ and you'll be fine.

**Comment by mpdehaan** [comment]
updating ticket caption slightly

**Comment by hukl** [comment]
Just ran into the same issue. If you have an ini file format parser you should support escape sequences and not throw the weirdest exceptions.

http://en.wikipedia.org/wiki/INI_file#Escape_characters

varname="# commented out line"  in the inventory throws

```
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.4.5/libexec/bin/ansible-playbook", line 269, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/Cellar/ansible/1.4.5/libexec/bin/ansible-playbook", line 86, in main
    inventory = ansible.inventory.Inventory(options.inventory)
  File "/usr/local/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 105, in __init__
    self.parser = InventoryParser(filename=host_list)
  File "/usr/local/lib/python2.7/site-packages/ansible/inventory/ini.py", line 41, in __init__
    self._parse()
  File "/usr/local/lib/python2.7/site-packages/ansible/inventory/ini.py", line 45, in _parse
    self._parse_base_groups()
  File "/usr/local/lib/python2.7/site-packages/ansible/inventory/ini.py", line 83, in _parse_base_groups
    tokens = shlex.split(line)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
```

**Comment by mpdehaan** [comment]
Throughing the weirdest exception might be a bit of a challenge.  A weird exception would be like "AIEEE, I am being chased by a zombie squid in a hot air balloon and I haven't done my taxes yet and ..."

**Comment by hukl** [comment]
Haha :)

**Comment by mpdehaan** [comment]
This is now implemented such that you can do # in the main file.

Youc an also stick that in group_vars or host_vars as that's regular YAML too.

Hope this helps, thanks!
