### ISSUE TITLE
Problem completing Ansible Tower 3.1.5 install

### ISSUE THREAD

**Issue by alexLorsung** [ansible/ansible#61475]
OS: Centos 7.5
Ansible version: 2.8.4
Ansible Tower Community version: 3.1.5

Trying to install Ansible Tower with a Single VM installation scenario

The setup goes through installing Ansible, postgres, rabbitmq and configuring all of that. The setup.sh script runs until it gets to the following line:

**TASK [awx_install : Migrate the Tower database schema (may take awhile when upgrading).] ***************************************************************************************************************** **

Once it gets there it fails out and spits out this error. I cannot find anything online that tells me why its getting the RC of 1.

`fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["tower-manage", "migrate", "--noinput", "--fake-initial"], "delta": "0:00:03.178395", "end": "2019-08-28 12:10:29.905756", "msg": "non-zero return code", "rc": 1, "start": "2019-08-28 12:10:26.727361", "stderr": "Traceback (most recent call last):\n  File \"/bin/tower-manage\", line 9, in <module>\n    load_entry_point('ansible-tower==3.1.5', 'console_scripts', 'tower-manage')()\n  File \"/lib/python2.7/site-packages/awx/__init__.py\", line 105, in manage\n  File \"/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute_from_command_line\n    utility.execute()\n  File \"/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/core/management/__init__.py\", line 328, in execute\n    django.setup()\n  File \"/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/__init__.py\", line 17, in setup\n    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n  File \"/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/utils/log.py\", line 86, in configure_logging\n    logging_config_func(logging_settings)\n  File \"/usr/lib64/python2.7/logging/config.py\", line 803, in dictConfig\n    dictConfigClass(config).configure()\n  File \"/usr/lib64/python2.7/logging/config.py\", line 560, in configure\n    'formatter %r: %s' % (name, e))\nValueError: Unable to configure formatter 'json': Cannot resolve 'awx.main.utils.formatters.LogstashFormatter': No module named Crypto.Cipher", "stderr_lines": ["Traceback (most recent call last):", "  File \"/bin/tower-manage\", line 9, in <module>", "    load_entry_point('ansible-tower==3.1.5', 'console_scripts', 'tower-manage')()", "  File \"/lib/python2.7/site-packages/awx/__init__.py\", line 105, in manage", "  File \"/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute_from_command_line", "    utility.execute()", "  File \"/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/core/management/__init__.py\", line 328, in execute", "    django.setup()", "  File \"/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/__init__.py\", line 17, in setup", "    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)", "  File \"/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/utils/log.py\", line 86, in configure_logging", "    logging_config_func(logging_settings)", "  File \"/usr/lib64/python2.7/logging/config.py\", line 803, in dictConfig", "    dictConfigClass(config).configure()", "  File \"/usr/lib64/python2.7/logging/config.py\", line 560, in configure", "    'formatter %r: %s' % (name, e))", "ValueError: Unable to configure formatter 'json': Cannot resolve 'awx.main.utils.formatters.LogstashFormatter': No module named Crypto.Cipher"], "stdout": "", "stdout_lines": []}
`

Any interpretation of this error is greatly appreciated.

**Comment by bcoca** [comment]
For Ansible Tower support or questions, please utilize https://access.redhat.com/products/ansible-tower-red-hat

For the OSS version (AWX) https://github.com/ansible/awx

This issue tracker is for the open source Ansible CLI tools project.
