### ISSUE TITLE
replace inner params to contain '-' instead of '_' and get relevant error for the user

### ISSUE THREAD

**Issue by chkp-orso** [ansible/ansible#61549]
##### SUMMARY

replace inner params to contain '-' instead of '_' and get relevant error for the user
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

checkpoint
##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by justjais** [comment]
Fixed in PR #61542
