### ISSUE TITLE
ansible-test not finding roles in collections anymore

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#61550]
##### SUMMARY

I have made no changes to my collection (geerlingguy.php_roles). Six days ago the CI tests passed without issue. Today I noticed the test structure changed (`test` directory is now `tests`), so I simply did a `mv test tests` and when the CI build ran, it picked up the tests as usual, but now I'm getting the following error about my collection role not being found:

```
TASK [Run the PHP role.] *******************************************************
584ERROR! the role 'geerlingguy.php_roles.php' was not found in /root/.ansible/test/tmp/php_role_test-zZQmcA-ÅÑŚÌβŁÈ/tests/integration/roles:/root/.ansible/test/tmp/php_role_test-zZQmcA-ÅÑŚÌβŁÈ/tests/integration/targets:/root/.ansible/test/tmp/php_role_test-zZQmcA-ÅÑŚÌβŁÈ/tests/integration
585
586The error appears to be in '/root/.ansible/test/tmp/php_role_test-zZQmcA-ÅÑŚÌβŁÈ/tests/integration/targets/php_role_test/tasks/main.yml': line 29, column 11, but may
587be elsewhere in the file depending on the exact syntax problem.
588
589The offending line appears to be:
590
591  include_role:
592    name: geerlingguy.php_roles.php
593          ^ here
```

I made no other changes besides moving the test directory to tests, so I'm wondering if core's logic for finding roles in the proper paths has a bug introduced in the past 6 days.

Last successful run: https://travis-ci.com/geerlingguy/ansible-collection-php_roles/builds/124407472
First failed run: https://travis-ci.com/geerlingguy/ansible-collection-php_roles/builds/125080018

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-test

##### ANSIBLE VERSION
```paste below
ansible 2.9.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/jgeerling/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jgeerling/Downloads/ansible/lib/ansible
  executable location = /Users/jgeerling/Downloads/ansible/bin/ansible
  python version = 2.7.16 (default, Apr 12 2019, 15:32:40) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.3)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /tmp/ansible-ssh-%%h-%%p-%%r
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 20
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/Users/jgeerling/Dropbox/VMs/roles']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
macOS (local), Ubuntu (Travis CI)

##### STEPS TO REPRODUCE
See summary above. Basically, run `ansible-test` within the collection's root directory. The collection is inside `~/.ansible/collections`

##### EXPECTED RESULTS
Tests should run without error as before.

##### ACTUAL RESULTS
Tests fail and the only paths scanned are:

  - /root/.ansible/test/tmp/php_role_test-zZQmcA-ÅÑŚÌβŁÈ/tests/integration/roles
  - /root/.ansible/test/tmp/php_role_test-zZQmcA-ÅÑŚÌβŁÈ/tests/integration/targets
  - /root/.ansible/test/tmp/php_role_test-zZQmcA-ÅÑŚÌβŁÈ/tests/integration

It looks like it's not scanning the collections directory (where the test was run) at all.

**Comment by geerlingguy** [comment]
I tested this locally too, where I can verify the path to the collection is exactly:

    ~/.ansible/collections/ansible_collections/geerlingguy/php_roles

I get the same error:

```
TASK [Run the PHP role.] *******************************************************
ERROR! the role 'geerlingguy.php_roles.php' was not found in /root/.ansible/test/tmp/php_role_test-U_Y7cr-ÅÑŚÌβŁÈ/tests/integration/roles:/root/.ansible/test/tmp/php_role_test-U_Y7cr-ÅÑŚÌβŁÈ/tests/integration/targets:/root/.ansible/test/tmp/php_role_test-U_Y7cr-ÅÑŚÌβŁÈ/tests/integration

The error appears to be in '/root/.ansible/test/tmp/php_role_test-U_Y7cr-ÅÑŚÌβŁÈ/tests/integration/targets/php_role_test/tasks/main.yml': line 29, column 11, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  include_role:
    name: geerlingguy.php_roles.php
          ^ here
```

**Comment by geerlingguy** [comment]
Running a `git bisect` locally:

```
6ec0b4ec86c35442b68aaaf8ac683f1ab40901fd is the first bad commit
commit 6ec0b4ec86c35442b68aaaf8ac683f1ab40901fd
Author: Matt Clay <matt@mystile.com>
Date:   Fri Aug 23 18:08:21 2019 -0700

    Sanity test updates for collections support. (#61248)
    
    * Run no-unwanted-files sanity test only on Ansible.
    
    Since collections should be able to use binary modules there is not really any limit on what could exist in a collection `plugins` directory.
    
    * Add support for symlinks in sanity target lists:
    
    - Sanity tests that need to analyze symlinks can do so using the supplied target list.
    - Tests that analyze directories will now only look at symlinks if requested.
    - Directory symlinks will now be seen as directories instead of files.
    
    * Enable symlinks on filename based sanity tests.
    
    Sanity tests that evalulate filenames instead of content should include symlinks.
    
    * Update symlinks sanity test.
    
    Use the sanity test target list now that it can include symlinks.

 .../sanity/code-smell/no-illegal-filenames.json    |  1 +
 .../_data/sanity/code-smell/no-unwanted-files.json |  6 ---
 .../_data/sanity/code-smell/no-unwanted-files.py   | 40 ----------------
 .../_data/sanity/code-smell/symlinks.json          |  3 +-
 .../_data/sanity/code-smell/symlinks.py            | 31 ++++--------
 test/lib/ansible_test/_internal/cover.py           |  4 +-
 .../_internal/provider/layout/__init__.py          | 26 ++++++----
 .../ansible_test/_internal/provider/source/git.py  |  7 +++
 .../_internal/provider/source/installed.py         |  2 +
 .../_internal/provider/source/unversioned.py       |  7 +++
 test/lib/ansible_test/_internal/sanity/__init__.py | 56 +++++++++++++++++-----
 test/lib/ansible_test/_internal/target.py          | 40 ++++++++++------
 test/sanity/code-smell/no-unwanted-files.json      |  7 +++
 test/sanity/code-smell/no-unwanted-files.py        | 40 ++++++++++++++++
 test/sanity/code-smell/obsolete-files.json         |  1 +
 15 files changed, 166 insertions(+), 105 deletions(-)
 delete mode 100644 test/lib/ansible_test/_data/sanity/code-smell/no-unwanted-files.json
 delete mode 100755 test/lib/ansible_test/_data/sanity/code-smell/no-unwanted-files.py
 create mode 100644 test/sanity/code-smell/no-unwanted-files.json
 create mode 100755 test/sanity/code-smell/no-unwanted-files.py
```

**Comment by geerlingguy** [comment]
Detailed steps to reproduce:

  1. Verify I'm on head of master on `php_roles` repo
  2. Verify Ansible repo is on head of devel
  3. `git reset --hard 5434bf74c6` on Ansible repo
  4. `. hacking/env-setup` on Ansible repo
  5. cd back to php_roles repo, `mv tests test`
  6. Run `ansible-test integration --docker geerlingguy/docker-centos7-ansible`
  7. It succeeds.
  8. Check out any later commit on Ansible repo (e.g. `git reset --hard 6ec0b4ec8`)
  9. cd back to php_roles repo, run `ansible-test` again
  9. It fails.

**Comment by mattclay** [comment]
I've narrowed the issue down to the files in the submodules not being included in the working file list. I'm actually surprised submodules were working before https://github.com/ansible/ansible/pull/61248. I'll provide further updates when I learn more.

**Comment by mattclay** [comment]
The issue is that the git source provider doesn't understand submodules. So when it enumerates available files, it sees the submodules as files instead of seeing the files inside them. This worked by accident with `--docker` because the tar creation automatically included all the files in those directories, but this was purely by accident. #61248 fixed that bug, which broke submodules.

**Comment by geerlingguy** [comment]
I can confirm PR #61564 fixes this issue - thank you for your help!
