### ISSUE TITLE
iosxr_lag_interfaces tests not idempotent

### ISSUE THREAD

**Issue by pabelanger** [ansible/ansible#61646]
##### SUMMARY

We have the following iosxr_log_interfaces test that is failing, and blocking other PRs from merging.

https://object-storage-ca-ymq-1.vexxhost.net/v1/a0b4156a37f9453eb4ec7db5422272df/ansible_63/61563/890de10608065ab92b159ccd46ccb7d937a7e91d/third-party-check/ansible-test-network-integration-iosxr-python35/550a3ee/controller/ara-report/

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

zuul.ansible.com

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by pabelanger** [comment]
https://object-storage-ca-ymq-1.vexxhost.net/v1/a0b4156a37f9453eb4ec7db5422272df/ansible_63/61563/890de10608065ab92b159ccd46ccb7d937a7e91d/third-party-check/ansible-test-network-integration-iosxr-python35/315dc3a/controller/ara-report/ is another

**Comment by pabelanger** [comment]
Another failure: https://object-storage-ca-ymq-1.vexxhost.net/v1/a0b4156a37f9453eb4ec7db5422272df/ansible_62/61362/0dcb1287f903dfbea90eea6eeac352d609e133b0/third-party-check/ansible-test-network-integration-iosxr-python35/1c89750/controller/ara-report/

**Comment by NilashishC** [comment]
This has been resolved by https://github.com/ansible/ansible/pull/62998.
The backport is https://github.com/ansible/ansible/pull/63095
