### ISSUE TITLE
Add documentation for ANSIBLE_MODULE_LANG setting

### ISSUE THREAD

**Issue by maesenka** [ansible/ansible#6169]
##### Issue Type:

Documentation Report
##### Ansible Version:

ansible 1.5 (devel 0cca4a3919) last updated 2014/02/25 21:59:52 (GMT +200)
##### Environment:

N/A
##### Summary:

No documentation can be found for ANSIBLE_MODULE_LANG. Neither is in mentioned in the ansible.cfg file.
##### Expected Results:

module_lang setting present and documented in ansible.cfg.
##### Actual Results:

module_lang setting not present.

**Comment by mpdehaan** [comment]
Can you share an example of when you needed to change this setting?

Thanks!

**Comment by maesenka** [comment]
This came up when installing postgresql on a Ubuntu using the apt module. When done manually from a console, the initial database cluster is configured (correctly for my case) to use UTF-8 encoding. When installed using ansible it turned out to be ASCII. This difference is because of the LANG setting in the environment when executing apt.
