### ISSUE TITLE
usefullness of play_hosts variable in cluster membership templates

### ISSUE THREAD

**Issue by vespian** [ansible/ansible#6179]
##### Issue Type:

“Feature Idea”
##### Ansible Version:

ansible 1.5
##### Environment:

Fedora 20
##### Summary:

The problem is that we want to use _play_hosts_ variable and set operations on groups to form cluster memberships in main site.yml file. The problem is that if some of the play hosts fail and/or we limit the play using _-l_ switch - the play_hosts (and thus membership configuration) changes. 
##### Steps To Reproduce:

Lets assume that we have groups serversA, serversB, serversC and marketA, marketB. Part of the serversA hosts belong to marketA, the rest to marketB. The same goes for serverB and serverC groups. We want to form clusters from hosts:

```
serverB:serverC:&marketA
```

using template such as:

```
{% for member in play_hosts if member != inventory_hostname %}
#{{ member }}
    member {
        memberaddr: {{ hostvars[member]['ansible_eth0']['ipv4']['address'] }}
    }
{% endfor %}
```

without the need to create additionall groups (we have quite a lot of clusters such like this).

Now try limiting the playbook run with _-l_ option and/or make some of the hosts fail. The template output will change.
##### Expected Results:

We need is something like 'all_play_hosts' variable that will store the initial host list. I can try to provide a patch.
##### Actual Results:

We have to declare additional groups in the inventory just because of this issue.

**Comment by mpdehaan** [comment]
Ok so this may be just a misconception.

play_hosts is the list of current hosts in the current play which is what we want

groups.foo is the hosts in group foo.

So you could just select the group list instead and be good to go.

I'd rather not add another variable for a slightly different semantic case for this when the above solution would work for most cases.

Thoughts?

**Comment by vespian** [comment]
Thanks for an answer. 

for this particular case, due to the fact that the group is formed using set operations:

```
hosts: serverB:serverC:&marketA
```

there is no groups.foo to use. Creating groups.foo would solve the issue but we wanted to avoid creating new groups just for that. 

I am not sure about this either :)

**Comment by bcoca** [comment]
you have set operation filters in ansible that can reproduce the same
result.

{%for host in  marketA|union([serverb, serverc]) %}

**Comment by vespian** [comment]
Thanks a lot!

This closes the issue.
