### ISSUE TITLE
remove vars directory from ansible-galaxy generated roles

### ISSUE THREAD

**Issue by dghubble** [ansible/ansible#6181]
##### Issue Type:

Design Critique
##### Ansible Version:

1.4
##### Environment:

NA
##### Summary:

Concerning the role generated by ansible-galaxy:

I question the inclusion of the vars directory in the generated role. Populated vars directories in roles in the wild are a barrier to reuse. When I download someone else's role, the defaults should contain all variables needed for the role to operate. vars should be used by the end user of the role only. Users should be free to set any variables under a /vars directory they create to override defaults that come with the role.

User modifications to anything under /vars should probably not be version controlled either. Add /vars to .gitignore in the generated role?

Let me know if I'm neglecting something crucial about the inclusion of /vars ?
##### Steps To Reproduce:

NA
##### Expected Results:

NA
##### Actual Results:

NA

**Comment by dghubble** [comment]
I use the term "user" to distinguish the role creator from the eventual user of the downloaded role.

**Comment by mpdehaan** [comment]
vars are useful places to define constants and vars are scoped to the role.

If you would like to discuss things like this you may post to the ansible-devel mailing list, but I'd rather not have a lot of posts for "Design Critique" cluttering up the issue tracker.

It's not a category in the bug template and we prefer to have discussions on the mailing list so we can get a greater number of people involved and others can also help answer questions.

Thanks!

**Comment by dghubble** [comment]
Thanks for the fast response! And apologies for posting here. I've started a discussion on the email list: https://groups.google.com/forum/#!topic/ansible-devel/A0aX10w0eCw
I'll direct future design questions/suggestions/discussions to the mailing list.
