### ISSUE TITLE
autodetect ANSIBLE_LIBRARY and PYTHONPATH if missing

### ISSUE THREAD

**Issue by lubko** [ansible/ansible#6185]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.5 (devel 6fa898c511) last updated 2014/02/26 13:27:14 (GMT +200)
##### Environment:

Ubuntu / Debian
##### Summary:

I am running ansible directly from the pulled source, and it bothers me that i need to export these two variables to the system.
I would like to share the work with more people, and i want them to have the least setup barrier. So they can just git pull ansible anywhere, symlink ansible-playbook, to their favorite /bin folder and get going.
Defining ANSIBLE_LIBRARY and PYTHONPATH seems totally unnecessary, because the code is right there, at a known location, relative to the executable.

If the idea would have a chance to be accepted, i will gladly implement it, and provide a pull request.
##### Steps To Reproduce:

```
$ /opt/ansible/bin/ansible --version
```
##### Expected Results:

```
ansible 1.5 (devel 6fa898c511) last updated 2014/02/26 13:27:14 (GMT +200)
```
##### Actual Results:

```
Traceback (most recent call last):
  File "/opt/ansible/bin/ansible", line 24, in <module>
    from ansible.runner import Runner
ImportError: No module named ansible.runner
```

**Comment by mpdehaan** [comment]
I'm interested.   How might this work?

**Comment by mpdehaan** [comment]
I'm going to close this ticket as we have the pull request open to track the idea -- this is just housekeeping, not saying no to the idea or anything.  Thanks!
