### ISSUE TITLE
autodetect ANSIBLE_HOSTS relative to 'pwd' in git fashion

### ISSUE THREAD

**Issue by lubko** [ansible/ansible#6186]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.5 (devel 6fa898c511) last updated 2014/02/26 13:27:14 (GMT +200)
##### Environment:

Ubuntu / Debian
##### Summary:

Im working with a lot of projects each having a set of dedicated servers. Managed by ansible, each have they configuration stored in a separate inventory folder/git-repository.
The default '/etc/ansible/hosts' does not help, because i have more hosts files, and my /etc is not versioned.
Defining -i with every command is annoying and clutters the command line
Exporting ANSIBLE_HOSTS is the best, but needs to be done for every terminal i open.

I would like ansible and ansible-playbook to behave pretty much like git does.
All my ansible configurations have inventory folder with the file "hosts" in its root,
just like git has .git in the root of each repo.
If i am in a terminal, cd in an ansible inventory folder or subfolder, ansible can detect the hosts file alone.
It will look for 'hosts' file in current directory, if not found, it will loop cd.. until it finds the file or reaches / and fails.

If /etc/ansible/hosts exists, it would still be primarily used to maintain backward compatibility.

I'm willing to work on this feature.
##### Steps To Reproduce:

```
user@host:/my/inventory/folder$ ansible all -m ping
```
##### Expected Results:

```
myserver | success >> {
    "changed": false, 
    "ping": "pong"
}
```
##### Actual Results:

```
ERROR: Unable to find an inventory file, specify one with -i ?
```

**Comment by mpdehaan** [comment]
I'm not in favor of this specific ticket because if you are in "/etc" it would assume "hosts" was an ansible inventory file, and that would not work well.

The filename in Ansible for an inventory is not of any fixed and unique name.

Sorry about that!

**Comment by lubko** [comment]
If you are in /etc/
and '/etc/ansible/hosts' exists or -i is defined or ANSIBLE_HOSTS is set
it would behave the same as before and use the specified file,
otherwise it will end up with failure just like now, only the error message would be different
"ERROR: Invalid ini entry: localhost - need more than 1 value to unpack"
instead of
"ERROR: Unable to find an inventory file, specify one with -i ?"
which does not seem that bad to me.

Every tutorial suggests to call this file 'hosts' so it became natural for me, but it could be detecting any other filename as well, be it "ansible_hosts_autoload" or any other new convention. I would be happy to hear your suggestions.

**Comment by hkhamm** [comment]
I had this issue using Ansible 1.6.5 installed via Homebrew in OS X. Using 'unset ANSIBLE_HOSTS' did not fix my problem. I fixed it by uninstalling the Homebrew version, then installing from pip.

**Comment by doukasd** [comment]
@hkhamm just wanted to say your comment saved me hours of pain. I've been getting weird and undocumented errors like "**ERROR: Unable to find an inventory file, specify one with -i**" and "**FAILED => module ping not found**" etc. and just a "**brew uninstall ansible**" and "**sudo pip install ansible**" fixed them all in a few seconds.

**Comment by ggarnier** [comment]
@doukasd same here. Is this a bug in the version installed from Homebrew?

**Comment by doukasd** [comment]
I guess it's either a buggy version or more probably it seems to be improperly installed by brew.

**Comment by lubko** [comment]
btw, i gave up on this ever being resolved.
i am using direnv ( https://github.com/zimbatm/direnv ) now and can recommend

**Comment by esteban-uo** [comment]
@doukasd installing it with pip also fixed it for me, thank you!

**Comment by coloradopioneer** [comment]
@hkhamm @doukasd using 1.8.4, pip fixed it from using homebrew, apparently homebrew is still having this issue. Thanks for the heads up, it was getting annoying setting the -i path every time!

**Comment by nathando** [comment]
yeah it is still a problem. But setting the ANSIBLE_HOSTS variable to '/etc/ansible/hosts' fixed it

**Comment by andywenk** [comment]
@doukasd I think it's the latter. I made the same experience like @esteban-uo did. Installing ansible via pip results in being able to use it with the standard path to the hosts file in `/etc/ansible/hosts`
