### ISSUE TITLE
Role vars and role defaults are not available in hostvars.

### ISSUE THREAD

**Issue by maxromanovsky** [ansible/ansible#6189]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.5 
##### Environment:

Debian 7
##### Summary:

Role vars and role defaults are not available in `hostvars`.
##### Steps To Reproduce:

Consider host `a` in group `appservers`. If host `a` has role `foo` and this role has some variable in `roles/foo/defaults/main.yml` or `roles/foo/vars/main.yml` then this role is not available in `hostvars` during the following iteration:

``` HTML+Django
{% for host in groups['appservers'] %}
        {{ hostvars[host]|to_nice_json }}
    {% endfor %}
```
##### Expected Results:

Variable is available in hostvars
##### Actual Results:

Variable is missing in hostvars

**Comment by bcoca** [comment]
just access them directly, they are not host specific so it makes little
sense to put them in hostvars.

**Comment by maxromanovsky** [comment]
@bcoca Correct me if I'm wrong but role default vars (from `roles/foo/defaults/main.yml`) could be overridden on per-group or per-host basis.
If that's correct then I want to receive effective value of the variable for the specific host.

**Comment by mpdehaan** [comment]
Yeah I understand this point.

In this case those variables should be available in hostvars when they get overridden, but they might not always be overridden.

Hostvars is also the way you get at a variable name programatically

The solution here would be to blend the inject hash every time when attempting to access hostvars.   

Wouldn't need to keep it in memory but would just need to make the proxy class make it available as such.

**Comment by maxromanovsky** [comment]
@mpdehaan Thanks for your response!
I'm sorry, but I didn't get it. I'm neither Python developer nor have any knowledge of Ansible internals.
Is there any solution from the Ansible plays side?

**Comment by mpdehaan** [comment]
Sorry for the late response, there is a large ticket queue.

Yep!

Basically if you want to get a variable and it's inventory specific or global, you don't have to care and can just say {{ varname }}

However in the example above you want to iterate variables that are not in hostvars, this also exists as "vars" and is accessible as a dictionary and can be similarly enumerated, but is not keyed on a host by host basis.

For general questions like this (especially if you want a quick response) asking on ansible-project or ansible-devel is going to be better most of the time.

Let us know on the list if you have any further questions -- I've thought about this one and I don't think we want to duplicate all of those variables in each hostvars,as it would consume a lot of extra memory the way fork operations are done.

**Comment by ghost** [comment]
Just discovered that those are available as a 'defaults' dict.

**Comment by hryamzik** [comment]
@nfubh do you mean `{{ defaults }}`? Mine is empty even inside a role.

@bcoca what if you have to iterate over variables matching pattern?

```
{% for k,v in hostvars[inventory_hostname].iteritems() %}
{% if k|match("^node_exporter_collector_.*") %}
{{ k }}={{ v }}
{% endif %}
{% endfor %}
```

Or you have to deal with defaults for other host.

**Comment by ghost** [comment]
@hryamzik Sorry, I don't remember exactly.. Anyway, I restrained myself later on from playing around too much with all these internals.

**Comment by TomaszKlosinski** [comment]
Why this ticket is closed? I still would like to see this feature.. @bcoca what do you mean by accessing them directly? By include_vars from the other role?

**Comment by darkweaver87** [comment]
+1 from host X I'll like to access value of a key that host Y has overrided

**Comment by yajo** [comment]
This problem still exists and is indeed counter-intuitive. It took me days until I found this issue. :disappointed: 

It should be fixed or, at least, documented.
