### ISSUE TITLE
Copy module does not apply owner and group to directories

### ISSUE THREAD

**Issue by amoe** [ansible/ansible#6194]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.5 (devel 33857855ad) last updated 2014/02/26 17:10:07 (GMT +100)
```
##### Environment:

Running Ansible from: Debian 7 (Wheezy)
Managing: CentOS 6.5
##### Summary:

When using the copy module with an source value that is a directory, and attempting to use the `owner` and `group` options of the file module, the options are applied correctly to any files within the copied directory, but they are not applied to the directory itself or further directories within this directory.
##### Steps To Reproduce:

Run this playbook task against the host.

```
- copy: src=/etc/emacs dest=/tmp/test-copy owner=daemon group=daemon mode=500
```
##### Expected Results:

I expect `/tmp/test-copy` to have ownership `daemon` and group `daemon`.  I expect `/tmp/test-copy/emacs` and any subdirectories to have that ownership also.
##### Actual Results:

```
# ls -ld /tmp/test-copy/
drwxr-xr-x. 3 root root 4096 Feb 26 17:17 /tmp/test-copy/
# ls -ld /tmp/test-copy/emacs
drwxr-xr-x. 3 root root 4096 Feb 26 17:17 /tmp/test-copy/emacs
# ls -ld /tmp/test-copy/emacs/site-start.d
drwxr-xr-x. 2 root root 4096 Feb 26 17:17 /tmp/test-copy/emacs/site-start.d
# ls -ld /tmp/test-copy/emacs/site-start.el 
-r-x------. 1 daemon daemon 412 Feb 26 17:17 /tmp/test-copy/emacs/site-start.el
```

**Comment by mpdehaan** [comment]
This could be a little tricky as along the path all the paths may need different permissions.

In this case, it may be better to be explicit with a second set and add a note to the docs if recursing permissions will only apply to the files?
