### ISSUE TITLE
ansible-test --venv fails to find its library

### ISSUE THREAD

**Issue by abadger** [ansible/ansible#61946]
##### SUMMARY
When installed from the ansible-2.9 PPA https://launchpad.net/~ansible/+archive/ubuntu/ansible-2.9  or from the nightly ansible rpms for RHEL7, ansible-test --venv fails to find its internal libraries

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

bin/ansible-test

##### ANSIBLE VERSION

```paste below
2.9.0beta1 devel
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

Ubuntu18 or CentOS7.  I suspect that this is irrespective of the OS but may be related to how we are presently packaging.  Ubuntu18 PPA and CentOS7 are both using python-2.7 with the separate python-virtualenv package at this time.

##### STEPS TO REPRODUCE

I did these steps in a fresh centos7 VM:

Create a yum repo file for the nightlies:
```
$ cat ansible-nightly.repo                                         (08:59:07)
[ansible-nightly]
name=Nightly Ansible packaging - $basearch
baseurl=https://releases.ansible.com/ansible/rpm/nightly/devel/epel-7-$basearch/
failovermethod=priority
enabled=0
#gpgcheck=1
#gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
```
use the ansible-nightly repo to install ansible-test
```
sudo yum install ansible-test --enablerepo=ansible-nightly --nogpgcheck
# ansible-test package and ansible package will be installed
$ ansible --version
ansible 2.10.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/badger/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
$ git clone git://github.com/ansible/ansible
$ cd ansible
$ ansible-test sanity --venv --test pep8 lib/ansible/module_utils/basic.py
Traceback (most recent call last):
  File "/usr/bin/ansible-test", line 28, in <module>
    main()
  File "/usr/bin/ansible-test", line 22, in main
    from ansible_test._internal.cli import main as cli_main
ImportError: No module named ansible_test._internal.cli
ERROR: Command "/usr/bin/env ANSIBLE_TEST_CONTENT_ROOT=/home/badger/ansible LC_ALL=en_US.UTF-8 /var/tmp/tmpYdP0oT/python2.7 /usr/bin/ansible-test sanity --test pep8 lib/ansible/module_utils/basic.py --metadata metadata-X1O5jT.json --truncate 117 --color yes --requirements" returned exit status 1.
```

##### EXPECTED RESULTS
ansible-test works with the --venv switch

##### ACTUAL RESULTS
I believe this is the venv directory: ```~/ansible/test/results/.tmp/delegation/python2.7```   

Contents of site-packages there:
```
[pts/0@centos7-master ~/ansible/test/results/.tmp/delegation/python2.7]$ ls -l lib/python2.7/site-packages 
total 20
-rw-rw-r--.  1 badger badger  126 Sep  5 14:39 easy_install.py
-rw-rw-r--.  1 badger badger  315 Sep  5 14:39 easy_install.pyc
drwxrwxr-x. 10 badger badger 4096 Sep  5 14:39 pip
drwxrwxr-x.  2 badger badger  155 Sep  5 14:39 pip-9.0.1.dist-info
drwxrwxr-x.  4 badger badger   74 Sep  5 14:39 pkg_resources
drwxrwxr-x.  4 badger badger 4096 Sep  5 14:39 setuptools
drwxrwxr-x.  2 badger badger  199 Sep  5 14:39 setuptools-28.8.0.dist-info
drwxrwxr-x.  5 badger badger 4096 Sep  5 14:39 wheel
drwxrwxr-x.  2 badger badger  174 Sep  5 14:39 wheel-0.29.0.dist-info
```

Possible cause:  ansible and/or ansible_test needs to be installed into the venv before ansible-test is re-invoked?

**Comment by goneri** [comment]
`delegate_venv()` use `SUPPORTED_PYTHON_VERSIONS` to know what what Python version should be used. In my case, 2.7 and 3.6 are available. But the rpm provides the `ansible_test` package only for 3.6. It's the opposite with the Debian package.

As a result, command fails with: `ImportError: No module named ansible_test._internal.cli` when it try to call `ansible-test` with Python 2.7.

I guess we should filter `SUPPORTED_PYTHON_VERSIONS` and only expose those with a`ansible_test` package available.
