### ISSUE TITLE
user: add user fails if "usergroup" already exists

### ISSUE THREAD

**Issue by muffl0n** [ansible/ansible#6210]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5 (devel c11e2100e0) last updated 2014/02/27 12:27:01 (GMT -400)
##### Environment:

Ubuntu 12.04.4 LTS
##### Summary:

Adding a user fails if a group with the same name as the user being created already exists.
##### Steps To Reproduce:
- create group "test" on remote system
- run playbook adding user "test"

```
- hosts: remote
  tasks:

  - name: ensure user test is present
    user: name=test uid=1112 home=/tmp/testuser
```
##### Expected Results:

User "test" is created
##### Actual Results:

Execution of playbook fails

```
ansible-playbook -i test test-user.yml -vv                 
PLAY [remote] *****************************************************************

GATHERING FACTS ***************************************************************
<remote> REMOTE_MODULE setup
ok: [remote]

TASK: [ensure user test is present] *******************************************
<remote> REMOTE_MODULE user name=test uid=1112 home=/tmp/testuser
failed: [remote] => {"failed": true, "name": "test", "rc": 9}
msg: useradd: group test exists - if you want to add this user to that group, use -g.


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/test-user.retry

remote                     : ok=1    changed=0    unreachable=0    failed=1
```

I'm not quite sure how to solve this. There is an option in useradd that controls if the "usergroup" (group with the same name as the user) should be created. 

```
By default, a group will also be created for the new user (see -g, -N, -U, and USERGROUPS_ENAB).
```

Unfortunately it has no fallback if the group already exists.

So maybe the user module should check if the group already exists and set option "-g" accordingly. Or maybe there should be another option to the user module if the usergroup should be created at all. But then there might be side-effects with the already existent option "group".

**Comment by mpdehaan** [comment]
Hmm, I thought this was already well handled.  In queue to repro, thanks!

**Comment by jimi-c** [comment]
The above patch should resolve the issue for you, let us know if you continue to see any problems along these lines. Thanks!

**Comment by muffl0n** [comment]
Works like a charm! Thanks for the fix!
