### ISSUE TITLE
managing archlinux hosts fails because of python2/3

### ISSUE THREAD

**Issue by gangelop** [ansible/ansible#6212]
##### Issue Type:

Bug Report
##### Ansible Version:

`ansible 1.4.5`
##### Environment:

Running from: Archlinux or Ubuntu 12.04
Managing: Archlinux
##### Summary:

When managing Archlinux hosts, ansible tries to run things with `/usr/bin/python` which on archlinux is python version 3, instead of 2 which ansible presumes. 
##### Steps To Reproduce:

`ansible archlinux_host -vvvv -m ping`
##### Actual Results:

```
<localhost> ESTABLISH CONNECTION FOR USER: george
<localhost> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/george/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'localhost', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1393536199.84-19596407208882 && chmod a+rx $HOME/.ansible/tmp/ansible-1393536199.84-19596407208882 && echo $HOME/.ansible/tmp/ansible-1393536199.84-19596407208882'"]
<localhost> REMOTE_MODULE setup 
<localhost> PUT /tmp/tmp6ONlWs TO /home/george/.ansible/tmp/ansible-1393536199.84-19596407208882/setup
<localhost> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/george/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'localhost', "/bin/sh -c '/usr/bin/python /home/george/.ansible/tmp/ansible-1393536199.84-19596407208882/setup; rm -rf /home/george/.ansible/tmp/ansible-1393536199.84-19596407208882/ >/dev/null 2>&1'"]
localhost | FAILED >> {
    "failed": true, 
    "msg": "  File \"/home/george/.ansible/tmp/ansible-1393536199.84-19596407208882/setup\", line 213\r\n    except ValueError, e:\r\n                     ^\r\nSyntaxError: invalid syntax\r\nOpenSSH_6.5, OpenSSL 1.0.1f 6 Jan 2014\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 30362\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to localhost closed.\r\n", 
    "parsed": false
}

```

relevant part:

`/bin/sh -c '/usr/bin/python /home/george/.ansible/tmp/ansible-1393536199.84-19596407208882    /setup`
##### Extra Info:

On the archlinux hosts, /usr/bin/python is a symlink to python3.

```
$ file /usr/bin/python
/usr/bin/python: symbolic link to `python3'
```

 When I link `/usr/bin/python`  to `python2` _ansible works_, which confirms my diagnosis. Ansible is looking at the wrong python.

**Comment by gangelop** [comment]
##### Possible Solution

A possible solution to this bug would be to make ansible look on the managed host for `$(which python2)` and try and use that. If it doesn't exist, then default to `python`.

I'm not familiar with ansible's code but I'll take a look at it :)

**Comment by mpdehaan** [comment]
Hi Iathan,

This is not a bug actually and we already have a good way to handle it.

What you need to do is set the ansible_python_interpreter variable in inventory.

You can read about this here:

http://docs.ansible.com/faq.html#how-do-i-handle-python-pathing-not-having-a-python-2-x-in-usr-bin-python-on-a-remote-machine

and also:

http://docs.ansible.com/intro_inventory.html#id10

Hope this helps and feel free to stop by the list if you have further questions!

**Comment by gangelop** [comment]
I rarely feel so relieved to be so wrong! I can now do things, and stuff. tyvm

also,

This really needs to be in the [arch wiki](https://wiki.archlinux.org/index.php?title=Special%3ASearch&search=ansible). I _might_ look into that tomorrow.

**Comment by mpdehaan** [comment]
Yeah that would be great!   Thanks!
