### ISSUE TITLE
postgresql support for dumping the database

### ISSUE THREAD

**Issue by zkanda** [ansible/ansible#6219]
##### Issue Type:

"Feature Idea”,
##### Ansible Version:

Future version of ansible
##### Environment:

N/A
##### Summary:

Supporting a simple database dump for postgresql

**Comment by mpdehaan** [comment]
This could be done with the shell module now as a basic workaround.

I'm not entirely sure it needs to be a module.

Thoughts?

**Comment by zkanda** [comment]
As much as possible we like to do it the ansible way..
and considering that {other db} have it, why not do it with postgre too?

**Comment by mpdehaan** [comment]
This should be doable by just calling the "shell" module, I'm thinking we probably don't need another module for this.

If you'd like to discuss on the development list, feel free to start a thread.
