### ISSUE TITLE
Remove Latin phrases from the docs

### ISSUE THREAD

**Issue by acozine** [ansible/ansible#62224]
##### SUMMARY
Latin words and phrases like `e.g.` or `etc.` are easily understood by native English speakers and speakers of European languages who speak some English. They are harder to understand for speakers of Asian languages who speak some English. They are also tricky for automated translation.

Add a row to the Style Guide cheat-sheet about avoiding Latin words and phrases.
Remove existing Latin words and phrases from the documentation.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
docs.ansible.com

##### ANSIBLE VERSION
all

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

**Comment by medmedchiheb** [comment]
i would like to work on this issue
