### ISSUE TITLE
Unclear how to use inventory plugins in collections

### ISSUE THREAD

**Issue by rambleraptor** [ansible/ansible#62231]
##### SUMMARY

I've been unable to get inventory plugins working inside of collections. The inventory plugin in ansible/ansible always takes precedence.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

collections

##### ANSIBLE VERSION

```paste below
devel
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

I've got a inventory.gcp.yml file that I run with `ansible-inventory --list -i inventory.gcp.yml`. I've got a collection called google.cloud installed into my collections path. Here are the various things I've tried.

```yaml
plugin: gcp_compute
...
```
Result: Runs the ansible/ansible inventory plugin.

```yaml
collections:
- google.cloud
plugin: gcp_compute
...
```
Result: Runs the ansible/ansible inventory plugin

```yaml
plugin: google.cloud.gcp_compute
...
```

Result: Plugin not found, errors out.

(I've also tried with `google.cloud.plugins.inventory.gcp_compute` and `google.cloud.inventory.gcp_compute` to no avail)

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by s-hertel** [comment]
@rambleraptor Make sure the NAME in your inventory plugin in the collection uses the FQCN - `NAME = 'google.cloud.gcp_compute'` and that your config file uses it too `plugin: google.cloud.gcp_compute`.

If you're using a collection adjacent to a playbook, use the `--playbook-dir` flag with `ansible-inventory`. If you're using a general collection make sure the collection is in an expected path https://github.com/ansible/ansible/blob/devel/lib/ansible/config/base.yml#L218-L226.

Either `auto` (which is whitelisted by default) or the specific plugin should be whitelisted, e.g.:
```
# ansible.cfg
[inventory]
enable_plugins = google.cloud.gcp_compute
```

I added a bit of documentation in #62465. If you have any feedback it would be appreciated.

**Comment by rambleraptor** [comment]
The documentation is fantastic. Exactly what I was looking for. Thanks so much!
