### ISSUE TITLE
Unicode char no-break space u'\xa0' causes python error 

### ISSUE THREAD

**Issue by snilard** [ansible/ansible#6227]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.4.5
##### Environment:

Mac OS X 10.7.5 with python 2.7.1
##### Summary:

No-break space (u'\xa0' ) character in task body causes python error when variable inserting is performed.
##### Steps To Reproduce:

Place non-break space to task body with used variable and you will get python error.

```
version: 2.1.1

- name: Example
  command: echo {{ version }}
```

Browser will not reproduce this character. Insert it to end of command line, on my system it is by option (alt) + space.
##### Actual Results:

```
TASK: [ruby| Example] ******************************************************** 
fatal: [***********] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 394, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 485, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 679, in _executor_internal_inner
    module_args = template.template(self.basedir, module_args, inject, fail_on_undefined=self.error_on_undefined_vars)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/template.py", line 319, in template
    varname = template_from_string(basedir, varname, vars, fail_on_undefined)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/template.py", line 521, in template_from_string
    data = data.decode('utf-8')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 16: ordinal not in range(128)
```

The bug is in ansible/utils/teplate.py on line 521 in unicode handling.
    data = data.decode('utf-8')

**Comment by mpdehaan** [comment]
Can you see if this still occurs in 1.5, which just released yesterday?

Thanks!

**Comment by snilard** [comment]
I updated my python to 2.7.6 and ansible to 1.5. No change. Same error message but with different python path.

**Comment by jctanner** [comment]
@snilard I'm not quite sure how to construct a test for this, but I believe this patch would fix it ...

```
diff --git a/lib/ansible/utils/template.py b/lib/ansible/utils/template.py
index fc4ff9f..65c44a6 100644
--- a/lib/ansible/utils/template.py
+++ b/lib/ansible/utils/template.py
@@ -310,7 +310,11 @@ def template_from_string(basedir, data, vars, fail_on_undefined=False):
             if os.path.exists(filesdir):
                 basedir = filesdir

-        data = data.decode('utf-8')
+        if isinstance(data, unicode):
+            try:
+                data = data.decode('utf-8')
+            except UnicodeEncodeError, e:
+                pass
         try:
             t = environment.from_string(data)
         except Exception, e:
```

Please apply that, and retest. If it does not work, copy an example playbook to gist.github.com that would reproduce the issue.

**Comment by snilard** [comment]
@jctanner Your patch work well. No error.

**Comment by jctanner** [comment]
@snilard I applied the patch to devel, thanks for testing!

**Comment by apollo13** [comment]
@jctanner I have a hard time understanding this fix, why would one ever run`decode` on unicode? Looking at the top of the function, we explicitelly decode from utf-8 already -- this somewhat smells to me.

**Comment by dagwieers** [comment]
@apollo13 Indeed, this doesn't seem correct. It's only masking the problem.
I am debugging a problem where a UTF-8 document has CP1252 characters mixed into it.
Obviously the input is incorrect, but it shouldn't be interpreted as UTF-8, or being masked like this.

Using:

```
decode('utf8', 'ignore')
```

is probably better if the error is going to be silenced.
