### ISSUE TITLE
copy module: owner & mode?

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#624]
Documentation of the `copy` module suggests in the example that _owner_, _group_, and _mode_ can be specified, even though these options aren't explicitly mentioned.

Looking through the source of `library/copy` suggests they aren't supported.

I feel they ought to be.

**Comment by mpdehaan** [comment]
Ah, but they totally are.

They are provided by the file module, which is automatically called by ansible after the copy module, in such a way that you don't need to know about it.

Same is true for template.

(In this way, we prevent duplicating code)

**Comment by jpmens** [comment]
I still have a lot to learn...

**Comment by mpdehaan** [comment]
Yeah I suspect most people to just use it and not read the src :)  It's all good.
