### ISSUE TITLE
"ansible-vault encrypt" will not accept multiple files at once

### ISSUE THREAD

**Issue by psynix** [ansible/ansible#6241]
##### Issue Type:

Bug Report
##### Ansible Version:

v1.5
##### Environment:

OS X (Mavericks)
##### Summary:

Contrary to the [documentation](http://docs.ansible.com/playbooks_vault.html#encrypting-unencrypted-files), ansible-vault won't accept multiple files:
##### Steps To Reproduce:

```
ansible-vault encrypt *.yml
```
##### Expected Results:

Password prompt with no error message
##### Actual Results:

```
ERROR: 'create' does not accept more than one filename
```

**Comment by jctanner** [comment]
@psynix ansible-vault accepts multiple **positional** arguments, but not fileglobs.

```
ansible-vault encrypt a.yml b.yml c.yml d.yml
```

If someone were to submit a pull request to accept fileglobs, I would definitely review and merge it in.
