### ISSUE TITLE
Jinja templates won't place # character for commenting in and out

### ISSUE THREAD

**Issue by hyperfocus1338** [ansible/ansible#6245]
##### Issue Type:

Bug Report
##### Ansible Version:

v1.5
##### Environment:

Host: Mac (OSX) Mavericks
Guest: Ubuntu 13.10

I'm using vagrant with the ansible provisioner
##### Summary:

I love the jinja templates functionality, I want to manage all my configuration files with it. It takes some upfront work to convert all the values in a configuration file to jinja variables but after that you can manage your configuration file with a clean list of options, without having to manage the configuration file itself with it's configuration syntax and comment clutter.

I use it for managing the core nginx configuration, serverblocks, php-fpm.conf, pool configurations and many other configuration files. 

However jinja isn't placing the # character in my configuration files, which would allow me to comment/uncomment certain options in the configuration from within the variable file.
##### Steps To Reproduce:

Try to place # character with a {{ variable }}

So for example:

variable: # (inside a variable file)

{{ variable }} (inside a configuration file)
##### Expected Results:

I want the {{ variable }} declaration in a configuration file to turn into a # character.

So simply placing the # character on the location you've defined the {{ variable }}
##### Actual Results:

It doesn't place the # character, instead it places "None"

Also, I would rather have a {{ variable }} place literally nothing instead of replacing it with "None" since "None" causes issues in configuration files and nothing doesn't.

**Comment by hyperfocus1338** [comment]
Discovered a bug in Ansibot, I did fill in the issue type ;)

Edit: Oops forgot to add 4x #'s before the titles.

**Comment by mpdehaan** [comment]
Can you share a bit more about what the template contains ?

Thanks!

**Comment by hyperfocus1338** [comment]
I have updated the description.

**Comment by mpdehaan** [comment]
Sorry for the late response, we've got quite a backlog and are powering through it.

"variable: # (inside a variable file)"

You will need to quote this bit and then will be ok.

variable: "# foo"

otherwise you've commented out the line.  

So this should not be a bug.

If you are doing this directly in the INI file, you can # the #.
