### ISSUE TITLE
Feature Request: RHEL iptables module 

### ISSUE THREAD

**Issue by aaron868** [ansible/ansible#6246]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.5 (devel a8a9b6c545) last updated 2014/02/28 17:35:54 (GMT -400)
##### Environment:

Centos 6
##### Summary:

Please add an iptables module. I saw that a former request for this has been closed. I recommend you reconsider because you need this for Ansible Galaxy.
##### Steps To Reproduce:

Roles often require certain ports to be open (mysql, email, web, etc.). Ansible needs a standard way to do this. If there isn't a standard way then either each role has to create its own method (very ugly) or they ignore it. If they ignore it then it would be hard to consider it production quality.
##### Expected Results:

There should be a way to configure the ports using variables so no changes are required to the Galaxy roles files (this is generally required for Galaxy). For example, in an email role there should be a way to set which of the possible ports (SSL and non-SSL) should be open.

The module also needs to be a bit unusual because it is global. The handler action should only be applied after all the roles are done independent of grouping. This way the firewall rules are only applied once even if many roles change the port settings.

iptables rule order is important. Some rules have to be at the end.

The firewall module should support at least the major commercial vendors: RHEL and SUSE.
##### Actual Results:

Not currently provided.

**Comment by jctanner** [comment]
@aaron868 we have tried to establish a pattern of using "when:" statements in roles to define OS specific tasks. Take a look at this for an example ...

https://github.com/bennojoy/openldap_server/blob/master/tasks/install_ldap.yml

If a ticket for a generic firewall module was closed previously, please start a discussion on the ansible-devel mailing list instead of using the issue tracker to reopen the discussion.

**Comment by aaron868** [comment]
The ldap role you linked to doesn't address the firewall issue at all. Since the need for a firewall module is obvious I find this response unexpected.
