### ISSUE TITLE
ansible 1.5 => Incorrect permissions on ACCELERATE_KEYS_DIR (~/.fireball.keys)

### ISSUE THREAD

**Issue by maxamillion** [ansible/ansible#6254]
##### Issue Type:

“Bug Report”
##### Ansible Version:

1.5
##### Environment:

RHEL 6
##### Summary:

Setup EPEL on RHEL6, `yum -y install ansible` (1.4.3 is latest in stable repo at the time of this writing), run a playbook using accelerated mode, `yum update -y ansible --enaberepo=epel-testing` to update to ansible 1.5, rerun that same playbook, get the error in the above comment.
##### Steps To Reproduce:

Setup EPEL on RHEL6, `yum -y install ansible` (1.4.3 is latest in stable repo at the time of this writing), run a playbook using accelerated mode, `yum update -y ansible --enaberepo=epel-testing` to update to ansible 1.5, rerun that same playbook, get the error in the above comment.

Playbook used is here https://github.com/maxamillion/ansible-maxamillion.so
##### Expected Results:

I expect something that worked in Ansible 1.4.3 that executes with zero deprecation warning to work unmodified in Ansible 1.5, plus or minus some deprecation warnings.
##### Actual Results:

```
$ ansible-playbook site.yml -i inventory.txt

 PLAY [all] ********************************************************************

 GATHERING FACTS ***************************************************************
 fatal: [maxamillion.so] => Incorrect permissions on ACCELERATE_KEYS_DIR (~/.fireball.keys)

 TASK: [common | Install Packages] *********************************************
 FATAL: no hosts matched or all hosts have already failed -- aborting


 PLAY RECAP ********************************************************************
             to retry, use: --limit @/home/admiller/site.retry

 maxamillion.so             : ok=0    changed=0    unreachable=1    failed=0
```

**Comment by mpdehaan** [comment]
This is kind of a feature (to make sure your key permissions are locked down), but I agree the error message is pretty terrible.  It should tell you how to correct the permissions so they are less open.

@jimi-c let me know if you agree and if we can just upgrade the error message?

**Comment by mgcrea** [comment]
Encountering the same issue, looks like ansible creates files with wrong chmod:

``` bash
GATHERING FACTS *************************************************************** 
fatal: [cubieboard-a] => Incorrect permissions on ACCELERATE_KEYS_FILE (/Users/olivier/.fireball.keys/192.168.0.48)
fatal: [raspberry-a] => Incorrect permissions on ACCELERATE_KEYS_FILE (/Users/olivier/.fireball.keys/192.168.0.105)
fatal: [cubieboard-b] => Incorrect permissions on ACCELERATE_KEYS_FILE (/Users/olivier/.fireball.keys/192.168.0.60)
```

Ansible just created thoses files but it looks like it can't use them.

**Comment by mgcrea** [comment]
Fixed it manually but I'm encountering this instead:

``` bash
fatal: [cubieboard-a] => Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-tmp-1394734003.38-21829377411504 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1394734003.38-21829377411504 && echo $HOME/.ansible/tmp/ansible-tmp-1394734003.38-21829377411504, exited with result 2
fatal: [cubieboard-b] => Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-tmp-1394734003.38-27773932306161 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1394734003.38-27773932306161 && echo $HOME/.ansible/tmp/ansible-tmp-1394734003.38-27773932306161, exited with result 2
```

Looks like I'm encountering this https://github.com/ansible/ansible/issues/6447

**Comment by jctanner** [comment]
@maxamillion and @mgcrea I encountered the "incorrect permissions" issue by running accelerate from an older version of ansible and then with the latest version. Can you confirm if either deleting .fireball.keys or moving it out of the way resolves the permission problem in current devel?

**Comment by jimi-c** [comment]
The error messages have been improved per the above discussion. The other issues appear to have been resolved via a separate commit or are the result of mixing accelerate versions, so this is should be resolved. If you run into this problem again, please let us know. Thanks!
