### ISSUE TITLE
trying to pull devel branch gives a 1.4.5 distribution

### ISSUE THREAD

**Issue by dmartitx** [ansible/ansible#6257]
##### Issue Type:

Bug Report
##### Ansible Version:

1.4.5
##### Environment:

CentOs 6.4
##### Summary:

Trying to upgrade ansible with git clone
##### Steps To Reproduce:

mb-dmarti:ansible dmarti$ rm -rf ansible
mb-dmarti:ansible dmarti$ git clone git://github.com/ansible/ansible.git
##### Expected Results:

Expected to upgrade to a level 1.5 ansible
##### Actual Results:

mb-dmarti:ansible dmarti$ ls
ansible         lynx-ansible        lynx-ansible.tar.gz lynx-elasticsearch  playground
mb-dmarti:ansible dmarti$ rm -rf ansible
mb-dmarti:ansible dmarti$ git clone git://github.com/ansible/ansible.git
Cloning into 'ansible'...
remote: Reusing existing pack: 49546, done.
remote: Counting objects: 135, done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 49681 (delta 78), reused 81 (delta 51)
Receiving objects: 100% (49681/49681), 15.93 MiB | 4.24 MiB/s, done.
Resolving deltas: 100% (30025/30025), done.
Checking connectivity... done
mb-dmarti:ansible dmarti$ ansible --version
ansible 1.4.5
mb-dmarti:ansible dmarti$ git config --list
user.name=dmartitx
user.email=dmarti@21ct.com

**Comment by jctanner** [comment]
@dmartitx can you clarify a bit more on how you are trying to "upgrade" ansible?

Simply cloning the repo does not alter the files in locations installed via system packages unless you are using hacking/env-setup.

**Comment by dmartitx** [comment]
I remove my /opt/ansible/ansible directory then issue this git command:
git clone https://github.com/ansible/ansible.git

Thanks!

Dave Marti
Solutions Engineer

21CT, Inc.
6011 W. Courtyard Drive
Bldg. 5, Suite 300
Austin, Texas 78730

Main: 512.682.4700
Direct: 512.682.4777
Fax: 512.682-4706

Email: dmarti@21ct.com
URL: http://www.21ct.com

**Comment by jctanner** [comment]
@dmartitx what is the output from "which ansible" ?

**Comment by dmartitx** [comment]
mb-dmarti:lynx-ansible dmarti$ which ansible
/opt/ansible/ansible/bin/ansible
mb-dmarti:lynx-ansible dmarti$ ansible --version
ansible 1.4.5

Thanks!

Dave Marti
Solutions Engineer

21CT, Inc.
6011 W. Courtyard Drive
Bldg. 5, Suite 300
Austin, Texas 78730

Main: 512.682.4700
Direct: 512.682.4777
Fax: 512.682-4706

Email: dmarti@21ct.com
URL: http://www.21ct.com

**Comment by mpdehaan** [comment]
Hi Dave,

We're pretty sure there's no problem here (everything on the devel branch says 1.5) and since this is Q&A territory, can you please move this over to Ansible-project mailing list?

This allows more people to help you, and also helps us keep our issue tracker better organized.  

Likely you just have a crossed up install where you need to remove your prior installation, or source the hacking/env-setup file if you are running from source.

It is very important that you _source_ this file, rather than just executing it.

Thanks!

--Michael
