### ISSUE TITLE
Ansible jinja templates replacing "on" with "True" which results in broken configuration files

### ISSUE THREAD

**Issue by hyperfocus1338** [ansible/ansible#6268]
##### Issue Type:

Bug Report / Undesirable behaviour
##### Ansible Version:

ansible 1.5
##### Environment:

Host: Mac (OSX) Mavericks
Guest: Ubuntu 13.10

I'm using vagrant with the ansible provisioner
##### Summary:

For easier management and commenting of several options in my Nginx configuration file I make every option a jinja variable so that I can manage the options inside a variables file. 

This allows me to comment the variable file with notes on what each option does, instead of cluttering the configuration file itself. I also have a separate http and https configuration for which I want the changes to be synchronized, which I'm trying to accomplish using jinja variables.

Currently jinja is not "exactly" placing the values you're giving it. Also see: https://github.com/ansible/ansible/issues/6245

I would prefer that a jinja variable would exactly place what it's told to instead of changing the values in some occasions.

Thank you for your time. If you need more information just let me know.
##### Steps To Reproduce:

So for example the following variable:

gzip: on

In this nginx configuration snippet:

gzip   {{ gzip }};
##### Expected Results:

Expected: 

gzip  on;
##### Actual Results:

Turns into

gzip   True;

Instead of

gzip  on;

**Comment by mpdehaan** [comment]
In YAML, on is going to get encoded to True if it's left bare.

You can fix this by quoting the value "on"

```
gzip: "on"
```

There's nothing to be done about this in Ansible, so you'll have to remember this trick.

See the YAML spec if you would like more info.  Thanks!

**Comment by hyperfocus1338** [comment]
That's fine Michael, thank you once again.
