### ISSUE TITLE
How to Disable logging on remote hosts

### ISSUE THREAD

**Issue by bengen** [ansible/ansible#6269]
ex:
Mar  4 20:00:19 app01 ansible-setup: Invoked with filter=\* fact_path=/etc/ansible/facts.d 
Mar  4 20:00:22 app01 ansible-command: Invoked with executable=None shell=True args=/usr/bin/python /root/.serveragent/hostPortProcess.py  removes=None creates=None chdir=None 

tail -f /var/log/user.log 

How to Disable logging on remote hosts?

**Comment by mpdehaan** [comment]
Hi bengen,

This bug tracker is for bug reports as well as pull requests and the like, and is not a support forum.

For that, stop by ansible-project@googlegroups.com or #ansible on irc.freenode.net

To answer your question, you can set "no_log: True" as a task parameter, as well as on the play itself.

```
- hosts: foo
  no_log: True
  tasks:
     -
```

no_log can also be set at the task level as well.

Thanks!
