### ISSUE TITLE
improve output in with_items mode

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#627]
Currently using with_items doesn't tell you what item you are using in non-verbose mode.

what should happen is inside of executor_internal_inner, on success, we should add the message (msg) there, saying what the value of "item" is.

This way, it can be used for all types of values fed into with_items. Given a module might have reason to return a message even if it doesn't fail, we could just set this as:

item: "$item"

Additionally, we would like to show this data even if not in verbose mode, so we probably want to modify callbacks.py such that if an item is set, it looks more like this:

ok: [localhost] => (item=$item) => {...}

Which we can do by seeing if the "item" key is in the return results.

This way no modules have to be customized to show what "item" they are running against, it just works, and with_items output is more logical.

**Comment by goozbach** [comment]
Originally found in #626.
