### ISSUE TITLE
sudo connection to centos failed since :"Moving {ssh,paramiko}_alt connection types to be the defaults"

### ISSUE THREAD

**Issue by do3cc** [ansible/ansible#6276]
Hi,

the CentOS version  in question is:
CentOS release 6.5 (Final)
sudo is
1.8.6p3
ssh is
5.3p1

when running a playbook with -K to ask for the sudo password, we get an exception when trying to gather facts from a centos machine. Here is the debug output:

```
<xxx.lala.de> EXEC ['ssh', '-C', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'P
referredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=do3cc', '-o', 'ConnectTimeout=60', 'xxx.lala.de', '/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, 
key=cpitfdbbwhlgpxqzenbikdgwractajkx] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-cpitfdbbwhlgpxqzenbikdgwractajkx; /usr/bin/python\'"\'"\'\'']
fatal: [xxx.lala.de] => ssh connection closed waiting for sudo password prompt
```

We are using the source checkout of ansible so with bisect we found out that the error appeared in this commit:
https://github.com/ansible/ansible/commit/df13b19fe1a085b016f1fce2b96f4b4ed39734db

Changing the has_pipelining variable from True to False again here:
https://github.com/ansible/ansible/commit/df13b19fe1a085b016f1fce2b96f4b4ed39734db#diff-73e049b63f15557dcdcf6ad06422c3f7L48

Made the whole thing work again. It seems that there is no ansible.cfg parameter available to control this variable. For now we just use 1.4.5

**Comment by mpdehaan** [comment]
There is an ansible.cfg to control pipelining and pipelining is off by default, but definitely want to explore.

Can we see your ansible.cfg?

**Comment by do3cc** [comment]
My fault. I have checked the ansible.cfg on the wrong server. Now that I wanted to cat the cfg again, I did it on the right one and saw that tunneling was still enabled. Removing that configuration element, CentOS does not fail any more.
Sorry for the noise
