### ISSUE TITLE
proftpd service restart bug

### ISSUE THREAD

**Issue by mcantsin** [ansible/ansible#6286]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.4
##### Environment:

Ansible on GNU/Linux Ubuntu 14.04 (trusy tahr)
Remote server on GNU/Linux Ubuntu 12.04 (precise pangolin)
##### Summary:

I get a bug with proftpd service restart. When the service is running, ansible shuts it down and starts it when its down. - So it's not a "restart" but a "state change".
##### Steps To Reproduce:

When I run
  ansible -m service -a "name=proftpd state=restarted"
then ansible tells me
  success >> {
  "changed": true,
  "name": "proftpd",
  "state": "started
but proftpd log says
  ProFTPD 1.3.5rc3 standalone mode SHUTDOWN
and when I run the same command again I get
  success >> {
  "changed": true,
  "name": "proftpd",
  "state": "started
and proftpd log says
  ProFTPD 1.3.5rc3 (devel) (built Thu Jul 4 2013 23:21:00 UTC) standalone mode STARTUP
... and so on.
##### Expected Results:

restarting the service and not state change.
##### Actual Results:

n/a

**Comment by mpdehaan** [comment]
This is very likely to be a problem with the init script itself, and not the service module, though this _may_ be a 14.04 issue.

Most likely the "status" command from the service is missing or unreliable.

To fix this, use the "pattern" argument to the service module.

Can you check and see what the status of the script returns (and possibly doing some light debugging with ./hacking/test-module in a checkout on the remote box to try and run the module directly?)

Thanks!

**Comment by mcantsin** [comment]
@mpdehaan thanks.

**Comment by mpdehaan** [comment]
I'm going to close this one due to no extra info on the above.  Feel free to reopen if you have figured out that the script is ok with return codes and such.

Thanks!

**Comment by DavidFetrow** [comment]
Problem is also in 12.04. 

Init script likely most (all) of problem. Can at least add
PidFile             /var/run/proftpd.pid
to proftpd.conf running in Standalone mode.

Without that no /var/run/proftpd.pid using default settings.
