### ISSUE TITLE
Shell module adding the escape character in command line

### ISSUE THREAD

**Issue by gary-lopez** [ansible/ansible#62887]
##### SUMMARY
When trying to pass a variable to a shell command with double quotes in the command, the command comes out with the escape character in front of the double quotes. In tail the command fails

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
shell

##### ANSIBLE VERSION
ansible 2.8.2

```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below
DEFAULT_HOST_LIST(/my-ansible/playbooks/ansible.cfg) = [u'/my-ansible/playbooks/hosts']
DEFAULT_LOG_PATH(/my-ansible/playbooks/ansible.cfg) = /var/log/ansible.log
DEFAULT_MANAGED_STR(/my-ansible/playbooks/ansible.cfg) = Ansible managed: This file is managed by Ansible, all changes will be lost.
DEFAULT_REMOTE_USER(/my-ansible/playbooks/ansible.cfg) = ansible
HOST_KEY_CHECKING(/my-ansible/playbooks/ansible.cfg) = False

```

##### OS / ENVIRONMENT

RHEL7.7

##### STEPS TO REPRODUCE
vars/main.yml
build_ou = 'ou=example, ou=com'
 

```yaml
- name: bind server
1. shell: ' {{ command }} -u {{ user }}@{{ domain}} -k {{ keytab }} join -c "{{ build_ou }}" {{ domain}}'
2.  shell: ' {{ command }} -u {{ user }}@{{ domain}} -k {{ keytab }} join -c \"{{ build_ou }}\" {{ domain}}'
```

##### EXPECTED RESULTS

"cmd": "command -u user@domain -k bind.keytab join -c "ou=example, ou=com" domain",

##### ACTUAL RESULTS

1.  "cmd": "command -u user@domain -k bind.keytab join -c \"ou=example, ou=com\" domain",
2.  "cmd": "command -u user@domain -k bind.keytab join -c \\\"ou=example, ou=com\\\" domain"

```paste below

```

**Comment by gary-lopez** [comment]
ACTUAL RESULTS
"cmd": "command -u user@domain -k bind.keytab join -c \"ou=example, ou=com\" domain",
"cmd": "command -u user@domain -k bind.keytab join -c \\\"ou=example, ou=com\\\" domain"

**Comment by gary-lopez** [comment]
There are three escape characters showing up and its getting removed when I submit.
\\\\\\\" and not just \\"

**Comment by samdoran** [comment]
We JSON serialize the data when it is displayed, so the extra escape characters are only for display purposes. They are not actually sent to the command.

To discuss this further, please reach out on IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
