### ISSUE TITLE
Notifications in parametrized roles

### ISSUE THREAD

**Issue by grossws** [ansible/ansible#6312]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5
##### Environment:

Host: Arch Linux, 
Target: Centos 6.
But it isn't related to issue.
##### Summary:

I have similar case to issue #4853. If I use parameter set with role like

``` yaml
# in site.yml
- hosts: all
  roles:
  - { role: test, test_param: var1 }
  - { role: test, test_param: var2 }
```

And `defaults/main.yml` like:

``` yaml
# in roles/test/defaults/main.yml
some:
  param: "{{ test_param }}"
```

I can use `test_param` from role but not the variable (`some.param`) in role's defauls to parametrize handler name.
##### Steps To Reproduce:

Other files:

``` yaml
# in roles/test/tasks/main.yml
- name: do something
  debug: msg="action for {{ some.param }}"
  notify: handle1 {{ test_param }}

- name: do someting else
  debug: msg="action for {{ some.param }}"
  notify: handle2 {{ some.param }}
```

``` yaml
# in roles/test/handlers/main.yml

# this handler will be called once for *each* test role, as expected
- name: handle1 {{ test_param }}
  debug: msg="working handler for {{ test_param }}"

# this handler will be called only once for two roles
# but calling once for *each* test role is expected
- name: handle2 {{ some.param }}
  debug: msg="broken handler for {{ some.param }}"
```
##### Expected Results:

Each handler should be called twice (once for each role apply). 

Handler names should be 
- `handle1 var1`, 
- `handle2 var1`,
- `handle1 var2`, 
- `handle2 var2`.
##### Actual Results:

First handler `handle1 {{ test_param }}` works as expected: called twice with parametrized names.

Second handler is called once for first role appliance. Its name is `handle2 {{ some.param }}` (with unevalueated parameter name).

So execution looks like:
- `handle1 var1`,
- `handle1 var2`,
- `handle2 {{ some.param }}`.

**Comment by grossws** [comment]
Ticket updated to fit into template, mentioned by your ansibot =)

**Comment by mpdehaan** [comment]
Here's the key part:

```
I can use test_param from role but not the variable (some.param) in role's defauls to     parametrize handler name.
```

Basically this going to be a thing.  The reason being is the default variables are at inventory scope, and handlers need to be at task scope and applied consistently to all objects in the system.

The workaround here would be to move the some.param you are using for notification into vars/ or passing it as a roles parameter.

It's not going to be possible to correct this particular thing because the task objects (which handlers are tasks) don't get evaluated on that level.

Sorry for the confusion!

**Comment by grossws** [comment]
I think, info about this behavior should be added to documentation, FGJ =)
