### ISSUE TITLE
Subversion module discloses SVN password on failure

### ISSUE THREAD

**Issue by siboulet** [ansible/ansible#6316]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

CentOS 5.8
##### Summary:

When a subversion module task fails, the SVN password is disclosed in the failure message. This may ultimately end up in log and/or failure email report.
##### Steps To Reproduce:

Create a simple Playbook containing a Subversion task:
- subversion: repo=http://{{deploy_svn_host}}/svn/{{repo}}/trunk revision={{rev}} dest=/var/www username={{deploy_svn_user}} password={{deploy_svn_password}}
##### Expected Results:

The password should be obfuscated. It is in the TASK report line, but not in the failure JSON detail.
##### Actual Results:

TASK: [subversion repo=http://{{deploy_svn_host}}/svn/{{repo}}/trunk revision={{rev}} dest=/var/www/ username={{deploy_svn_user}} **password={{deploy_svn_password}}]** **\* 
failed: [some-server] => {"cmd": ["/usr/bin/svn", "--non-interactive", "--trust-server-cert", "--no-auth-cache", "--username", "some-user", **"--password", "top-secret-password"**, "switch", "http://svn.somecompany.com/svn/someproject/trunk", "/var/www"], "failed": true, "rc": 1}

**Comment by mpdehaan** [comment]
Thanks for the report, we are working on removing this detail now and this will be included in the next dot release.

**Comment by jimi-c** [comment]
@siboulet the above patch should resolve the issue for you. Please let us know if you continue having any problems with this. Thanks!
