### ISSUE TITLE
ansible-playbook lost --limit options

### ISSUE THREAD

**Issue by ovcharenko** [ansible/ansible#6321]
##### Issue Type:

BugReport
##### Ansible Version:

ansible 0.6
##### Environment:

N/A
##### Summary:

I noticed what there is no --limit option anymore. Is it by design or by mistake? How to limit host execution list now?
##### Steps To Reproduce:

ansible-playbook hosts.yaml --limit=host1,host2
##### Expected Results:

It works.
##### Actual Results:

```
ansible-playbook: error: no such option: --limit
```

**Comment by jimi-c** [comment]
I'm assuming the 0.6 in your bug report above is a typo, however I am unable to reproduce this. On the devel branch running a playbook from another issue I had created:

<pre>
$ ansible-playbook 6047.yml -u test --limit=ubuntu1204
PLAY [all] ******************************************************************** 
GATHERING FACTS *************************************************************** 
ok: [192.168.x.x]
TASK: [apt pkg=python-keyczar state=installed] ******************************** 
ok: [192.168.x.x]
PLAY [all] ******************************************************************** 
GATHERING FACTS *************************************************************** 
ok: [192.168.x.x]
TASK: [command date] ********************************************************** 
changed: [192.168.x.x]
PLAY RECAP ******************************************************************** 
192.168.x.x            : ok=4    changed=1    unreachable=0    failed=0   
</pre>

I've also tried a comma-separated list like you used, but it works for me each time. Could you please verify your version, and if you could also try with the latest code from github I'd appreciate it.

**Comment by ovcharenko** [comment]
@jimi-c thanks for quick reply. Latest dev version works just fine.
