### ISSUE TITLE
Handlers defined in role dependencies don't work in subsequent plays

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#6322]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

Ubuntu, Debian
##### Summary:

Handlers that are defined in a role that is a dependency of another role, which is called in a play, are not working in subsequent plays. It seems that role dependencies are also not correctly executed. 
##### Steps To Reproduce:

Using `git bisect` I've determined that bug has been introduced in https://github.com/ansible/ansible/pull/6299

Example playbook that shows the bug in action: https://github.com/drybjed/ansible-dependent-handler-test
##### Expected Results:

```
% ansible-playbook -i hosts play.yml 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [dependency | Create directory] ***************************************** 
ok: [localhost]

TASK: [role | Touch role file] ************************************************ 
changed: [localhost]

NOTIFIED: [dependency | Dependent handler] ************************************ 
changed: [localhost]

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [dependency | Create directory] ***************************************** 
changed: [localhost]

TASK: [role | Touch role file] ************************************************ 
changed: [localhost]

NOTIFIED: [dependency | Dependent handler] ************************************ 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=8    changed=5    unreachable=0    failed=0
```
##### Actual Results:

```
% ansible-playbook -i hosts play.yml

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [dependency | Create directory] ***************************************** 
ok: [localhost]

TASK: [role | Touch role file] ************************************************ 
changed: [localhost]

NOTIFIED: [dependency | Dependent handler] ************************************ 
changed: [localhost]

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [role | Touch role file] ************************************************ 
failed: [localhost] => {"changed": true, "cmd": ["touch", "/tmp/second_test/role_file"], "delta": "0:00:00.003374", "end": "2014-03-06 23:32:30.535035", "item": "", "rc": 1, "start": "2014-03-06 23:32:30.531661"}
stderr: touch: cannot touch '/tmp/second_test/role_file': No such file or directory
ERROR: change handler (Dependent handler) is not defined
```

**Comment by jimi-c** [comment]
Thanks, looking at this now.

**Comment by jimi-c** [comment]
So as of the above patch, this behavior is the intended result. In order for your handler to work, you just need to add a `meta/main.yml` file with `allow_duplicates: yes` set in it so that the second play can run it.

**Comment by jimi-c** [comment]
@drybjed now, it does look like the handler not being defined is an issue, since the role data is not shared across plays now, and the second play doesn't load it.

**Comment by jimi-c** [comment]
@drybjed we've decided to partially rollback the commit that broke this, so your issue should be resolved. Let me know if you have any more problems with this. Thanks!

**Comment by drybjed** [comment]
@jimi-c Thanks, everything seems to work now. As for `allow_duplicates: yes`, I thought from [reading the documentation](http://docs.ansible.com/playbooks_roles.html#role-dependencies) that one role dependency was limited to current play. But if it's applied to entire playbook run, that's OK. I suppose adding this setting to roles that are designed to be run multiple times shouldn't hurt.

**Comment by jimi-c** [comment]
@drybjed it was, but that had been changed by the above feature, the idea being that sometimes common roles are re-applied when a second play is run. That has now been backed out, since it was pointed out that the patch I submitted did not account for the (likely) chance that the lists of hosts across plays would not be the same. You should not need to add `allow_duplicates` to your meta now, unless you want them to be run multiple times by different roles within the same play.
