### ISSUE TITLE
"hosts: myservers[-1]" no longer works to address last host in group

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#6331]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5
##### Environment:

OSX
##### Summary:

I've done some bisecting, and after ca0ec80 , I'm no longer able to address the last server in group with myserver[-1] in a playbook.  It is simply skipped stating:
##### Steps To Reproduce:

inventory:

```
[riak_cluster]
10.42.0.6
10.42.0.7
10.42.0.8
```

playbook:

```
- hosts: riak_cluster[-1]
  tasks:
  - name: debug
    debug: msg="foo"
```
##### Expected Results:

the debug message would be displayed  for 10.42.0.8
##### Actual Results:

```
skipping: no hosts matched
```

**Comment by jimi-c** [comment]
The above patch should fix the issue for you. Please let us know if you run into any further problems with this. Thanks!
