### ISSUE TITLE
systemd service backend can fail to detect services not running

### ISSUE THREAD

**Issue by charles-dyfis-net** [ansible/ansible#6341]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.5 + PR #6339 
##### Environment:

Arch (Rolling Release / No Version Number).

systemd 208-11
##### Summary:

The `service` module should be able to correctly determine that systemd services reported as dead are not running.
##### Steps To Reproduce:

...on a system wherein the `eth0` Ethernet interface does not have an associated dhcpcd service running, apply:

```
- service: name=dhcpcd@eth0 state: started enabled:yes
```
##### Expected Results:

The relevant service should be started and enabled, or an error should be detected.
##### Actual Results:

Even when the service is down, if it is enabled, this task responds with:

```
ok: [localhost]
```

Inspection with `strace` shows that `servicectl status dhcpcd@eth0` is being invoked after an attempt to start the service, with the following output:

```
dhcpcd@ens3.service - dhcpcd on ens3
  Loaded: loaded (/usr/lib/systemd/system/dhcpcd@.service: enabled)
  Active: inactive (dead)
```

It is expected that this `inactive` result would cause the operation to be detected as a failure.

**Comment by mpdehaan** [comment]
Thanks, there's another ticket dealing with @services (another mentions dhcpd specifically) and is probably related to that issue.

**Comment by charles-dyfis-net** [comment]
I filed a pull request with a fix for a similar issue, but they aren't in fact identical.

**Comment by charles-dyfis-net** [comment]
...this one actually looks like an old PR which was rejected for reasons related to a different portion of its functionality should fix it: https://github.com/ansible/ansible/pull/5038

**Comment by charles-dyfis-net** [comment]
...strike that; it's not is-enabled but is-active that's the appropriate replacement here, and that PR doesn't go so far as to use both.

**Comment by charles-dyfis-net** [comment]
This issue appears to be completely unrelated to `@services`, but rather caused by `LinuxService.get_service_status()` assuming that systemctl returns LSB-compliant exit status codes -- which it very much does not -- or that it makes certain guarantees about strings contained in output -- which it also does not.

(There are similar issues with `service_enable()` and `service_control()` assuming that nonzero exit status will be provided on errors, which systemctl does not do).

A `SystemDService` class separate from `LinuxService` is probably the right long-term approach.

**Comment by np** [comment]
I'm also affected by this issue and these commits fixes the issue. After a quick review these two commits looks good to me.

**Comment by jimi-c** [comment]
The above pull request has been merged, so this issue should be resolved. Please let us know if you continue to run into this problem going forward. Thanks!
