### ISSUE TITLE
Unify "call this module after this module" logic

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#635]
In many places in the Runner code we call the file module after another module to allow setting the mode/owner/etc.   This logic should be streamlined, such that any module can set the following in the returns:

daisychain: "module_name"

And the Runner code will automatically call the next module with the arguments provided to the first.   This requires of course that our new magic module boilerplate never yell about invalid module options, which I think is ok.

**Comment by jpmens** [comment]
As in like this?

```
127.0.0.1 | success >> {
    "changed": true, 
    "daisychain": "file", 
    "dest": "/tmp/u/plain.text", 
    "md5sum": "5ca6779de69ecfa6e504d6d7871e9958", 
    "msg": "OK unknown octets", 
    "src": "/var/folders/jA/jA4IbxFXGJ0KSmsooRhDAU+++TI/-Tmp-/tmpGQhDs2", 
    "url": "http://localhost/~jpm/plain.text"
}
```

Doesn't seem to work for me on local connection.

Or is the operative keyword _should_ be streamlined, i.e. is not yet? ;)

**Comment by mpdehaan** [comment]
Exactly, not implemented yet, hence the ticket to remind me about the idea.

But it will work exactly like that.

**Comment by bradobro** [comment]
Just click on github's "Auto-implement and Close" button. Real time saver. :)

**Comment by mpdehaan** [comment]
done
