### ISSUE TITLE
Assemble module should put a newline between each file

### ISSUE THREAD

**Issue by pgehres** [ansible/ansible#6353]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5 / devel @ 04a6dc6d12
##### Environment:

Unrelated but
Host: OS 10.9.1, 
Target: Centos 6.5
##### Summary:

The assemble module (as of 3b2d409) ensures that a newline is placed after any delimiter usage but the module does not put a newline between each of the files. Without putting a blank line in each file (which can easily get accidentally removed) the first line of each file is concatenated with the last line of the preceding file.  This breaks a lot of configuration files that are "assembled" (e.g. iptables in my case).
##### Expected Results:

I would expect a newline between fragments.
##### Actual Results:

The first line of each file is concatenated with the last line of the preceding file 
##### Steps To Reproduce:

Try the assemble module

**Comment by mpdehaan** [comment]
I'm a bit confused by this one as if the delimiter always adds a newline, there should be a newline between assembled files.

Can you help explain further how to reproduce this by showing some file snippets, task lines, and output?

**Comment by pgehres** [comment]
Sure. I'll work on that. To clarify, the delimiter is an optional parameter. Simply adding a " " as the delimiter doesn't work as python evaluates that to False (if delimeter: ... ).

**Comment by pgehres** [comment]
Also, since you agree that assemble should put a newline between files, I'll submit a pull request as well.

**Comment by pgehres** [comment]
Test playbooks at https://github.com/pgehres/ansible-playbooks-test

The output I get is:

```
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT-A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT-A INPUT -m state --state NEW -m udp -p udp --dport 123 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 4848 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 5099 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 5666 -j ACCEPT-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
```

my expected output would be

```
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT
-A INPUT -m state --state NEW -m udp -p udp --dport 123 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 4848 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 5099 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 5666 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
```

**Comment by pgehres** [comment]
@mpdehaan Do you need anything else?

**Comment by mpdehaan** [comment]
I think we have enough info, thanks!

**Comment by mpdehaan** [comment]
I'm not seeing this behavior on the development branch.

This is to say I am not seeing file A rammed against file B in any case, they are always seperated by at least one blank line.

This seems true whether delimiter is used or not.

The most recent change here was made on March 6th and seems to have corrected the above report.

```
# git show 9f2999df7963777e39334a789611eaa0f38442c3
commit 9f2999df7963777e39334a789611eaa0f38442c3
Author: James Cammarata <jcammarata@ansibleworks.com> 
Date:   Thu Mar 6 09:44:56 2014 -0600

Un-escape newlines in delimiters for assemble module
```

Let me know if things work for you, thanks!!!

**Comment by pgehres** [comment]
@mpdehaan I'm still seeing the same output.  I created https://github.com/pgehres/ansible-playbooks-test which is what I am using to test.

**Comment by jimi-c** [comment]
The above commit was merged, so this issue should be resolved. If you continue seeing any problems related to this issue, or if you have any further questions, let us know. Thanks!
