### ISSUE TITLE
Please install python-apt package.

### ISSUE THREAD

**Issue by ashleyconnor** [ansible/ansible#6356]
##### Issue Type:

Bug Report
##### Ansible Version:

**Ansible version `devel` pulled today 09/03/2014**
##### Environment:

Host is OSX Mavericks, running Ubuntu 12.04 LTS Vagrant on 1.4.3 on latest VirtualBox v4.3.8, python 2.7.5 locally and 2.7.3 on VM.
##### Summary:

I'm attempting to run this simple [provisioning script](https://github.com/jlund/mazer-rackham/) but I'm encountering errors.
##### Steps To Reproduce:
1. Pull the above repo
2. Follow the instructions in the repos readme
##### Expected Results:

A provisioned server running a Sinatra App on port 8080
##### Actual Results:

**Could not import python modules: apt, apt_pkg. Please install python-apt package.**
##### Other Details:

So I SSH'd into my Vagrant instance and ran `sudo apt-get install python-apt` but it was already installed. I re-installed it and attempted to run the provisioning again but it failed.

I then SSH'd in again and ran the Python interpreter:

```
>>> import apt
>>> import apt_pkg
>>> import aptsources.distro
>>> distro = aptsources.distro.get_distro()
```

No errors...

The only thing I can think of is that these commands are being run locally and not on the server and therefore will fail since I'm running OSX with none of these packages installed.

Full error output is below:

```
[default] Running provisioner: ansible...

PLAY [imgur-display-servers] **************************************************

GATHERING FACTS ***************************************************************
<127.0.0.1> REMOTE_MODULE setup
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1394367792.4-182603371802867 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1394367792.4-182603371802867 && echo $HOME/.ansible/tmp/ansible-tmp-1394367792.4-182603371802867']
<127.0.0.1> PUT /var/folders/00/zhwt92hd48j5r_r4jqr7xb1h0000gn/T/tmpcWRGHw TO /Users/ashleyconnor/.ansible/tmp/ansible-tmp-1394367792.4-182603371802867/setup
<127.0.0.1> EXEC ['/bin/sh', '-c', '/usr/bin/python /Users/ashleyconnor/.ansible/tmp/ansible-tmp-1394367792.4-182603371802867/setup; rm -rf /Users/ashleyconnor/.ansible/tmp/ansible-tmp-1394367792.4-182603371802867/ >/dev/null 2>&1']
ok: [127.0.0.1]

TASK: [common | Upgrade apt packages] *****************************************
<127.0.0.1> REMOTE_MODULE apt upgrade=yes update_cache=yes
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1394367797.1-273022421468376 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1394367797.1-273022421468376 && echo $HOME/.ansible/tmp/ansible-tmp-1394367797.1-273022421468376']
<127.0.0.1> PUT /var/folders/00/zhwt92hd48j5r_r4jqr7xb1h0000gn/T/tmpyDG1aT TO /Users/ashleyconnor/.ansible/tmp/ansible-tmp-1394367797.1-273022421468376/apt
<127.0.0.1> EXEC ['/bin/sh', '-c', '/usr/bin/python /Users/ashleyconnor/.ansible/tmp/ansible-tmp-1394367797.1-273022421468376/apt; rm -rf /Users/ashleyconnor/.ansible/tmp/ansible-tmp-1394367797.1-273022421468376/ >/dev/null 2>&1']
failed: [127.0.0.1] => {"failed": true, "item": ""}
msg: Could not import python modules: apt, apt_pkg. Please install python-apt package.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/ashleyconnor/imgur-display-setup.retry

127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by mpdehaan** [comment]
So the apt modules are run on your remote host, if you are attempting to run them versus -c local or local_action you should not do this.

Looking at the above output, it does not seem like you are logging in, and this is a function of how you are using the vagrant provisioner.

Since the vagrant provisioner is not part of Ansible, this is not really an Ansible problem, and may just be a case of you needing to tweak your vagrant file.

In any case, feel free to ask questions about this on the ansible list if you can't find help vagrant folks or prefer it, but this is not a bug in Ansible.

You may also wish to ask the "mazer" author as well, about how he runs it in his environment, as this is also not our script.

**Comment by ashleyconnor** [comment]
I believe you are right.

I've had connection issues with Vagrant and rather than fix them it looks like I've simply got the ansible commands to run locally.

My apologies for this ticket. It's hard to know what's at fault with so many moving parts.

**Comment by ashleyconnor** [comment]
So I had 5 keys in my `ssh-agent` and despite the explicit option of using the vagrant ssh key it still insisted on looping through keys in my agent before reaching max_tries conveniently before getting to the right key.

To check you have this problem:
Run `ssh-add -l` - if this list is > 5 you need to remove keys or disable the agent.

To fix:
Run `ssh-add -d ~/.ssh/X` where `X` is the key you want to remove.
