### ISSUE TITLE
git module should accept the ssh config

### ISSUE THREAD

**Issue by tsh56** [ansible/ansible#6358]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5
##### Environment:

OSX 10.9.2 -> Ubuntu 12.04
##### Summary:

Prior to version 1.5 I had used my ssh config as a way to set StrictHostKeyChecking=no for a particular host I was performing git clones against. In 1.5 the git module added an accept_hostkey parameter. Now my ssh config is not checked prior to the git module checking of the host key, so the clone fails even though I have an ssh config which should allow the operation to succeed. It would seem appropriate for my ssh config to be properly respected.
##### Steps To Reproduce:

Add the following lines to .ssh/config for a host that does not have a known hosts entry. Then attempt to perform a git clone against that host using anisble.

-Host [hostname]
-       StrictHostKeyChecking no
##### Expected Results:

The clone should succeed assuming the ssh config is respected.
##### Actual Results:

The clone fails because it checks the known host without respect to the ssh config.

**Comment by mpdehaan** [comment]
So the git module isn't going to parse your SSH config to determine if for a particular host it is going to need to check the host key or not.  That's not going to happen.   

You could add the accept_hostkey option to add the key, for sure.

Alternatively, you could add the key.

Alternatively, we could add an option that says accept_hostkey=ignore or something like that.

But the module definitely isn't going to try to figure out your SSH config, because that's a lot of work to ask it to do.

You should also consider turning on host key checking for your remote nodes -- it's a good idea!

**Comment by tsh56** [comment]
First you are correct that having a populated known hosts file is the correct solution, and I ended up doing that.

With that said some of the options anisble provides around ssh are the exact point of having an ssh config file. Implementing features that go against the ssh config feels counterproductive. I should be able to configure an ssh config to my liking and not worry about convincing ansible that ssh will succeed.  The host checks are incorrect as i noted in defect 6357. This hybrid approach of providing some ssh options without fully understanding ssh configs leads to cases where task failures occur unnecessarily. Some sanity checks which don't take the config into consideration fail, when the ssh command would actually succeed. It would be nice to able to turn all the sanity checks off completely and to be able to rely on a properly written ssh config file.

**Comment by mpdehaan** [comment]
"With that said some of the options anisble provides around ssh are the exact point of having an ssh config file."

I don't disagree with this, though Ansible using SSH as transport to get to the remote host and then _using_ SSH on the remote node are kind of different things (unless you are forwarding your keys, which is generally not suggested).

I would not expect for the majority of our users to have configured .ssh/config at all on the remote machines -- usually they'll be managing a large number of dumb compute nodes, web servers, databases, etc.

While it doesn't solve the question of reading the file, the module docs also suggest that:

```
    - Add the hostkey for the repo url if not already added.
          If ssh_args contains "-o StrictHostKeyChecking=no", this
          parameter is ignored.
```

So you can pass ssh_args into the git module and it will be ok.

**Comment by jctanner** [comment]
@tsh56 for clarification purposes, where is the ssh config? Is it on the remote host or on your control host? Where is the task actually running (control/remote) ?

**Comment by bryanlarsen** [comment]
Here's my solution to the problem:

```
- copy: src=ssh-knownhost dest=/srv/clara/bin/ mode=0755
- command: "/srv/clara/bin/ssh-knownhost github.com 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48 ad:1c:08:a4:40:e3:6f:9c:f5:66:26:5d:4b:33:5d:8c"
```

where ssh-knownhost is http://www.daemonology.net/blog/ssh-knownhost

which suggests that adding the functionality from ssh-knownhost to ansible is probably a good idea.

**Comment by mpdehaan** [comment]
There's also the accept_hostkey=yes/no now that can be used to solve this problem without disabling the key check, so I'm going to close this one as having a good solution in place.

Thank you!
