### ISSUE TITLE
Docker python issue

### ISSUE THREAD

**Issue by Sunitha82** [ansible/ansible#63584]
Please raise issues via the [new interface](https://github.com/ansible/ansible/issues/new/choose)
Hello

I am trying to run a play book from host(ansible VM) to pull an image from docker host,  I tried pip install docker still it not working, can you please help.

failed to import the required python library (docker sdk for python: docker (python >= 2.7) or docker-py (python 2.6)) on host's python /usr/bin/python3. please read module documentation and install in the appropriate location, for example via pip install docker or pip install docker-py (python 2.6). the error was: no module named  request.exceptions")

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
