### ISSUE TITLE
setup_mysql8 integration test role fails when run with the test group

### ISSUE THREAD

**Issue by samdoran** [ansible/ansible#63590]
##### SUMMARY

When the `setup_mysql8` role is run as part of the `shippable/posix/group1/`, the service fails to start and the test fails.

Example failure output from [this run](https://app.shippable.com/github/ansible/ansible/runs/146941/68/tests):
```
{
"changed": false, 
"msg": "Unable to start service mysqld: Job for mysqld.service failed because the control process exited with error code. See \"systemctl status mysqld.service\" and \"journalctl -xe\" for details.\n"
}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`test/integration/targets/setup_mysql8`
##### ANSIBLE VERSION

```paste below
2.10
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Run `ansible-test integration --docker centos7 shippable/posix/group1/`

##### EXPECTED RESULTS

Tests pass

##### ACTUAL RESULTS

Tests fail

```
{
"changed": false, 
"msg": "Unable to start service mysqld: Job for mysqld.service failed because the control process exited with error code. See \"systemctl status mysqld.service\" and \"journalctl -xe\" for details.\n"
}
```
```

**Comment by samdoran** [comment]
These tests were added in https://github.com/ansible/ansible/pull/63454

**Comment by felixfontein** [comment]
Will reopen when nightly CI run does not pass (because of this).

**Comment by felixfontein** [comment]
It looks like all errors in https://app.shippable.com/github/ansible/ansible/runs/147001/summary/console are unrelated to the MySQL tests, so it should be fine now.
