### ISSUE TITLE
Return 'NA' for ansible_virtualization_* if no virtualization found

### ISSUE THREAD

**Issue by mriedelumab** [ansible/ansible#6369]
##### Issue Type:

Bug Report / Feature Request
##### Ansible Version:

$ ansible --version
ansible 1.4.3
##### Environment:

CentOS 6.5, Python 2.6.6 
##### Summary:

When Ansible runs "setup" to gather facts about a system, if the remote Linux system is not a virtualization host or virtualization guest, the "ansible_virtualization" facts do not get set at all, causing group_by and other conditional tests to fail or act erratically.
##### Steps To Reproduce:

1) Set up CentOS using a bare-metal "Minimum" install
2) Run "ansible <host> -m setup"
3) No "ansible_virtualization" facts are returned
4) Try using "ansible_virtualization" facts as a conditional, and ansible will fail on a KeyError or something else.
##### Expected Results:

The setup module should always return "ansible_virtualization" facts, even if they are "NA". This would be consistent with other setup module facts.
##### Actual Results:

"ansible_virtualization" are not set at all on bare-metal machines w/o virtualization, so using these facts fail in conditionals or group_by scenarios.

Patch:

``` patch
--- setup_1_4_3 2014-03-10 09:59:55.841818426 -0400
+++ setup_workingcopy   2014-03-10 10:00:59.972412587 -0400
@@ -2032,6 +2032,11 @@
                 self.facts['virtualization_role'] = 'host'
                 return

+   # Virtualization = 'NA' if none of the above
+   self.facts['virtualization_type'] = 'NA'
+   self.facts['virtualization_role'] = 'NA'
+   return
+
 class HPUXVirtual(Virtual):
     """
     This is a HP-UX specific subclass of Virtual. It defines
```

In cases where no virtualization can be found, Ansible should return 'NA' for those values so group_by and other tests don't fail with KeyError exceptions. This behavior is consistent with other Ansible facts, such as "ansible_bios_version," etc.

**Comment by mpdehaan** [comment]
Since you have a patch here, if you would like to submit this, please submit this as a github pull request rather than a bug ticket.

Read https://help.github.com/articles/using-pull-requests for how to contribute code to the project.

Thanks!

**Comment by mriedelumab** [comment]
Thanks- I tried doing that based on the Contribution documentation, but I think I did it wrong the first time.  I think I got it this time, pull request #6372. Thanks!

**Comment by mpdehaan** [comment]
Closing since this was merged, thanks!
