### ISSUE TITLE
Using $HOME in ansible.cfg [defaults] hostfile = doesn't work

### ISSUE THREAD

**Issue by pjz** [ansible/ansible#6373]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5
##### Environment:

Ubuntu Precise
##### Summary:

I tried setting

hostfile = $HOME/.ansible/hosts
and it didn't work at all; I got 'ERROR: Unable to find an inventory file, specify one with -i ?'. Changing it to hostfile = /home/pjz/.ansible/hosts fixed it, but was clearly suboptimal; why is environment substitution done in some cases (remote_tmp defaults to $HOME/.ansible/tmp) but not others? 
##### Steps To Reproduce:

In ansible.cfg, set 

```
hostfile = $HOME/.ansible/hosts
```

Then put a host definition there and try using it with, for example, `ansible all -m ping`
##### Expected Results:

I expect to see the usual ping output
##### Actual Results:

```
ERROR: Unable to find an inventory file, specify one with -i ?
```

**Comment by mpdehaan** [comment]
Basically this is expecting an os.path.expandvars to be executed here around the inventory path.

This seems reasonable though there may have been problems checking earlier.

Seems like an easy patch if this is something you would like to work on!

**Comment by pjz** [comment]
Well, so the larger question is whether other paths (all paths?) in the ansible.cfg should be wrapped in os.path.expandvars?

**Comment by gergelyimre** [comment]
Problem is still there in ansible 1.7 (devel 8a6cfa1a23). The example ansible.cfg uses $HOME so I thought I use it to set the hostfile to "hostfile = $HOME/whatever". But it doesn't work. It does work with ~/whatever (thanks to rob in #ansible on IRC for the tip.
If it's not fixed maybe it should be changed in the example (and in the docs).
