### ISSUE TITLE
apt-module returns failure for both absent/present

### ISSUE THREAD

**Issue by pjan** [ansible/ansible#6386]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.1
##### Environment:

Ubuntu 12.04
##### Summary:

Started cutting up the big chunk of roles I have, and putting them on Galaxy. I meanwhile also upgraded to 1.5. I run into issues I never had before, especially with the apt module, returning:

for 

```
- name: Vim | Make sure vim-tiny is uninstalled
  apt: pkg=vim-tiny state=absent
```

I ssh'd into the machine, and put in the command in the console/terminal, and it didn't give any problems. (It fails on remote, vagrant and travis)
##### Steps To Reproduce:

run Ansibles.vim from galaxy
##### Expected Results:

Clean pass / no errors
##### Actual Results:

```
TASK: [Ansibles.vim | Vim | Make sure vim-tiny is uninstalled] **************** 
failed: [AnsiblesBox] => {"cmd": ["DEBIAN_FRONTEND=noninteractive", "DEBIAN_PRIORITY=critical", "/usr/bin/apt-get", "-q", "-y", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "remove", "vim-tiny"], "failed": true, "item": "", "rc": 2}
msg: [Errno 2] No such file or directory
```

**Comment by mpdehaan** [comment]
Thanks, we have already gotten a report of this and are looking into this.   See #6385
