### ISSUE TITLE
APT module fails : [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by python-consulting** [ansible/ansible#6387]
##### Summary:

The APT module fails at basic commands (installation of package, upgrade, etc.)
##### Steps To Reproduce:

Step to reproduce :
- Install ansible system wide with pip on debian wheezy
- add hosts
- run: ansible all -m apt -a "pkg=iperf"
##### Expected Results:

Installation of iperf 
##### Actual Results:

X.X.X.X | FAILED >> {
"cmd": [
        "DEBIAN_FRONTEND=noninteractive", 
        "DEBIAN_PRIORITY=critical", 
        "/usr/bin/apt-get", 
        "-y", 
        "-o", 
        "Dpkg::Options::=--force-confdef", 
        "-o", 
        "Dpkg::Options::=--force-confold", 
        "install", 
        "iperf"
    ], 
    "failed": true, 
    "msg": "[Errno 2] No such file or directory", 
    "rc": 2
}

After some digging, it appears that when subprocess module is passed environment variables the return value is "[Errno 2] No such file or directory".

I tried the following in a python interactive shell

import subprocess

> > > subprocess.check_output(["/usr/bin/aptitude", 
> > > ...         "-y", 
> > > ...         "-o", 
> > > ...         "Dpkg::Options::=--force-confdef", 
> > > ...         "-o", 
> > > ...         "Dpkg::Options::=--force-confold", 
> > > ...         "safe-upgrade"
> > > ...     ]
> > > ... )

and 

import subprocess

> > > subprocess.check_output(["/usr/bin/aptitude", 
> > > ...         "DEBIAN_FRONTEND=noninteractive", 
> > > ...         "DEBIAN_PRIORITY=critical",
> > > ...         "-y", 
> > > ...         "-o", 
> > > ...         "Dpkg::Options::=--force-confdef", 
> > > ...         "-o", 
> > > ...         "Dpkg::Options::=--force-confold", 
> > > ...         "safe-upgrade"
> > > ...     ]
> > > ... )

the second one fails as ansible.

What do I do wrong as I do not think nobody could not notice this error ?

**Comment by mpdehaan** [comment]
Thanks, we have already gotten a report of this and are looking into this.   See #6385
