### ISSUE TITLE
apt_key module broken since 1.5.1

### ISSUE THREAD

**Issue by pcraston** [ansible/ansible#6389]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.1
##### Environment:

Ubuntu 12.04
##### Summary:

Since upgrading to Ansible 1.5.1 apt-key module fails with error:

```
failed: [192.168.56.135] => {"failed": true, "item": "", "traceback": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1394535647.18-78800933797653/apt_key\", line 144, in download_key\n    return rs
p.read()\nAttributeError: 'NoneType' object has no attribute 'read'\n"}
msg: error getting key id from url
```

Here's the task:

```
- name: Add postgres repository key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present
  environment:
    http_proxy: <proxy server address>
```
##### Steps To Reproduce:

Upgrade to 1.5.1. Downgrading to 1.5 resolves the issue

**Comment by mpdehaan** [comment]
Thanks, we have already gotten a report of this and are looking into this.   See #6385

**Comment by jdauphant** [comment]
Hi @mpdehaan, 

I think this issue is different from #6385 .
It maybe link to the fact that @jimi-c have change the way of retreiving file by url in some module to introduce cert validation.
https://github.com/ansible/ansible/commit/9730157525c8cd539c2f657f40c34b73bb189e44#diff-20

The bug is still present in 1.5.3 .

**Comment by jdauphant** [comment]
This line exactly : https://github.com/ansible/ansible/commit/9730157525c8cd539c2f657f40c34b73bb189e44#diff-1c0cf6cc5a1cf1bb47db3812f9a734b7L136

**Comment by jimi-c** [comment]
@jdauphant it appears to be fixed in devel though, which is why we've closed it.

**Comment by jdauphant** [comment]
@jimi-c You have right, it's corrected in the devel. Thanks.
