### ISSUE TITLE
when running a tag, all tasks from the play where the tag exists are run

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#6393]
##### Issue Type:

Bug report in tag handling 
##### Ansible Version:

Latest devel, as per git bisect, bug was introduced in 6577ff5f85bf27048739013d91066c7b4e1dd466
##### Environment:

Ubuntu, but N/A
##### Summary:

When running a larger playbooks contanin multiple plays with different tags, and running it with specifying a particular tag, all tasks in those plays that contain (tasks with) that tag are ran, instead of only those tasks that have the specific tag.
##### Steps To Reproduce:

```
  1 - name: Restart Tomcat Servers                                                  
  2   hosts: tomcat                                                                 
  3   gather_facts: False                                                           
  4   tasks:                                                                        
  5   - name: trigger stop                                                          
  6     debug: var=tomcat_version                                                   
  7     changed_when: True                                                          
  8     notify:                                                                     
  9     - stop_tomcat                                                               
 10     tags: stop                                                                  
 11   - name: trigger start                                                         
 12     debug: var=tomcat_version                                                   
 13     changed_when: True                                                          
 14     notify:                                                                     
 15     - start_tomcat                                                              
 16     tags: start                                                                 
 17   handlers:                                                                     
 18   - include: handlers/tomcat.yml   
```

running `ansible-playbook util-tomcat-restart.yml -t stop` will run both trigger tasks, not just the stop task.
##### Expected Results:

Run only the tasks that have a particular tag.
##### Actual Results:

All tasks from the play that contain some tasks with a given tag are ran.

**Comment by mpdehaan** [comment]
@jimi-c giving this one to you, appears to only affect the devel branch, but marking priority.  Need to be careful on any changes to tags as that seems to be a problem area.

**Comment by DSpeichert** [comment]
I am having the same problem, all tasks within playbook's roles are run.

**Comment by jctanner** [comment]
I am unable to reproduce this without using roles so far.

**Comment by jimi-c** [comment]
The above patch should resolve the issue for you. If you continue to have problems with this, please let us know. Thanks!

**Comment by srgvg** [comment]
Solved, thanks!
