### ISSUE TITLE
ansible_ssh_user incorrect when using local_action

### ISSUE THREAD

**Issue by landtuna** [ansible/ansible#6396]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5

ii  ansible                                                              1.5.2-saucy-unstable1                         all
##### Environment:

Ubuntu 13.10
##### Summary:

ansible_ssh_user evaluates to the local user when using a local_action. I would expect it to be the current remote user. ansible_ssh_host works as expected.
##### Steps To Reproduce:

https://gist.github.com/landtuna/41f07861eb7a27b06932
##### Expected Results:

In the gist above, I would expect ansible_ssh_user to evaluate to guest@127.0.0.1.
##### Actual Results:

The output is in the gist.

**Comment by landtuna** [comment]
The workaround I'm currently using is to capture ansible_ssh_user in an earlier task using a registered variable.

**Comment by mpdehaan** [comment]
Well, there is no remote user as it's a local action, so it's evaluating as you, but I can see this is a bit of a grey area.

Have you looked into using the synchronize module?

**Comment by landtuna** [comment]
I'd argue that there's still a remote machine, since the play is running in the context of being associated with a remote host. Ignoring the motivation for doing an rsync, it would be reasonable to use ansible_ssh_user and ansible_ssh_host along with local_action to keep a record on the local machine of remote machines accessed.

Another reason this is a bug and not just a quirk is that ansible_ssh_user and ansible_ssh_host are not consistent. Either both should refer to the local machine, or both should refer to the remote machine.

**Comment by ef4** [comment]
I think there's a better workaround, which is to explicitly say you want the `ansible_ssh_user` of the current target host, as opposed to the `ansible_ssh_user` for the host where the local_action is running:

```
hostvars[inventory_hostname]['ansible_ssh_user']
```

**Comment by jctanner** [comment]
@landtuna the implication of combining local action, command and rsync is that you are attempting to delegate the task to 127.0.0.1 as yourself. That is just how local action is designed. That is also one of the reasons the synchronize module does automatic local delegation, so that it can handle the complexities of what the remote host and username should be.

Please take a look at the synchronize docs as I think it will resolve this situation for you.
