### ISSUE TITLE
Incorrect warning with with_fileglob

### ISSUE THREAD

**Issue by jefferai** [ansible/ansible#6407]
When using the following with_fileglob statement:

with_fileglob: "{{ bootstrap_location }}/debs/*"

I get the following:

[WARNING]: It is unneccessary to use '{{' in loops, leave variables in loop expressions bare.

(Note: "unnecessary" is also misspelled in the warning message -- it should have one c, not two.)

However, this cannot be right; without the {{ }} there's no way it would know what to substitute. mdehann in #ansible confirmed this.

---

Much later edit:

Before anyone protests, note that I am following the instructions of the bot extremely literally...and that it has already been acknowledged/triaged/resolution suggested and intended by @mpdehaan 
##### Issue Type:

What kind of ticket is this?  You can say â€œBug Reportâ€, â€œFeature Ideaâ€, â€œFeature Pull Requestâ€, â€œNew Module Pull Requestâ€, â€œBugfix Pull Requestâ€, â€œDocumentation Reportâ€, or â€œDocs Pull Requestâ€.
##### Ansible Version:

Please supply the verbatim output from running â€œansible --versionâ€. 
##### Environment:

What OS are you running Ansible from and what OS are you managing?  Examples include RHEL 5/6, Centos 5/6, Ubuntu 12.04/13.10, *BSD, Solaris.  If this is a generic feature request or it doesnâ€™t apply, just say â€œN/Aâ€. 
##### Summary:

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.
##### Steps To Reproduce:

If this is a bug ticket, please enter the steps you use to reproduce the problem in the space below.  If this is a feature request, please enter the steps you would use to use the feature.  If an example playbook is useful, please include a short reproducer inline, indented by four spaces.  If a longer one is necessary, please link one uploaded to gist.github.com. 
##### Expected Results:

Please enter your expected results in this space.  When running the steps supplied above, what would you expect to happen?  If showing example output, indent your output by four spaces so it will render correctly in GitHub. 
##### Actual Results:

Please enter your actual results in this space.  When running the steps supplied above, what actually happened?  If showing example output, indent your output by four spaces so it will render correctly in GitHub.

**Comment by mpdehaan** [comment]
Basically what i've suggested is if the line doesn't end in "}}" we should not print the warning.

Should be an easy addition.

**Comment by bcoca** [comment]
with_fileglob: bootstrap_location + "/debs/*"

**Comment by mpdehaan** [comment]
Good point there.   I still think I can prune the warning though, it was intended to prevent stuff like:

with_items: "{{ alist }}"

where you can just more elegantly do:

with_items: alist

**Comment by jefferai** [comment]
@bcoca good to know, but the intent of the warning seems to be preventing the case @mpdehaan described: with_fileglob: {{ bootstrap_location }}

**Comment by jefferai** [comment]
Of course, I could fail to refresh the page before commenting.

**Comment by mpdehaan** [comment]
I'm guessing this warning not fire if "|" is found in the expression.

**Comment by mpdehaan** [comment]
Also, for this:

when: "{{ foo | filter }}"

etc

**Comment by abadger** [comment]
@mpdehaan I implemented this as "Only emit a warning if it consists of a single variable to expand".  Let me know if that wasn't what you intended.
