### ISSUE TITLE
EC2 Facts completely broken in 1.5.2

### ISSUE THREAD

**Issue by jlafon** [ansible/ansible#6411]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.2
##### Environment:

Ubuntu 12.04
##### Summary:

ec2_facts broken

It appears that the ec2_facts module is completely broken in Ansible 1.5.2.
It's actually hard coded to fail ([look here](https://github.com/ansible/ansible/blob/devel/library/cloud/ec2_facts#L73)) by calling `json_fail` explicitly. 
Here is the [commit](https://github.com/ansible/ansible/commit/9730157525c8cd539c2f657f40c34b73bb189e44#diff-ef5f5a0c411564a5983d80947e14979fL73). Removing that line doesn't fix the problem either.

Is there no testing framework that tests these modules?
##### Steps To Reproduce:

On any ec2 machine: ansible -m ec2_facts localhost
##### Expected Results:

I expected the normal ec2_facts to appear
##### Actual Results:

user@ip-<redacted>:~# ansible -m ec2_facts localhost -i ansible_hosts -c local
localhost | FAILED >> {
    "failed": true, 
    "msg": "url is http://169.254.169.254/latest/meta-data/"
}

**Comment by mpdehaan** [comment]
Ow, very disappointed that this debug comment got left in.

We have some integration tests that we are expanding though this is not added yet.

We will update this very soon and see about a dot release.

**Comment by mpdehaan** [comment]
Removing errant code now, and will ask @jctanner to help test

**Comment by mpdehaan** [comment]
See fix applied on https://github.com/ansible/ansible/commit/a689e42d32cba58808ed5d3a56d35ff9b2962fa1

The workaround would be replace ec2_facts from the version on the development branch for now

We want to fix up some problems caused by recent SSL validation upgrades (different issue) so our plan is to include both this and that ticket in a 1.5.3 update, which we should be targetting for _approximately_ tomorrow.

**Comment by jlafon** [comment]
Wow, thanks for the fast response! I'll test the new release tomorrow as well.

**Comment by mpdehaan** [comment]
Thanks, getting more integration tests wired into the system is going to be a major goal for us in 1.6 -- so we can detect things like this more automatically, while still testing the real cloud APIs (so not just units)

Help testing is much appreciated!

**Comment by jctanner** [comment]
@jlafon that last patch should fix the issue for you. I've tested against an official amazon linux AMI and got a clean diff between the output with the patch and from 1.5.0.
