### ISSUE TITLE
Role's default variables aren't rendered in task names.

### ISSUE THREAD

**Issue by sashka** [ansible/ansible#6413]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.2
##### Environment:

N/A
##### Summary:

Default value of a role variable doesn't render in a task name.
##### Steps To Reproduce:

Sample playbook and role are in this gist: https://gist.github.com/sashka/9496666
##### Expected Results:

```
TASK: [locale | create /etc/locale.gen for {{locale}}] ************************ 
```
##### Actual Results:

```
TASK: [locale | create /etc/locale.gen for blabla ] ************************ 
```

**Comment by mpdehaan** [comment]
This is because they are inventory scoped and may be different per host, so can't go in a header.

Working as designed!

**Comment by sashka** [comment]
OK, thanks.
