### ISSUE TITLE
route53: No ec2_argument_keys_spec()

### ISSUE THREAD

**Issue by devoncrouse** [ansible/ansible#6414]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.0 devel
##### Summary:

I'm a little confused; it looks like ec2_argument_spec() -> ec2_argument_keys_spec() in this PR: https://github.com/ansible/ansible/pull/5917

But in devel, it still has the old name despite the merge. The Route53 module (at least), is now referencing the new name, however, and errors as a result.

**Comment by mpdehaan** [comment]
This is probably the result of the merge push today on the development branch to get some old PRs in.  I am flagging this as priority to fix on the development branch, though this should I believe not be applied to the release branch.

**Comment by devoncrouse** [comment]
https://github.com/ansible/ansible/commit/b9a7352e0a8e2cd8a72e29a7cc9a800bc83155c8

^ Looks like (part of) the culprit

**Comment by mpdehaan** [comment]
Yep, I have this on deck for the team to look at this tomorrow.   Should you have a good test platform available (sadly I don't right now at this time and where I'm at), I'd definitely be able to merge a quick pull request.  I don't think we want to revert so much as fix the errant methods.

Thanks!

**Comment by devoncrouse** [comment]
No problem. This solves the problem for me, though I'm not sure if there's more cleanup that should be happening here...

https://github.com/ansible/ansible/pull/6415

**Comment by jctanner** [comment]
Confirmed the mixed up function names:

```
jtanner@u1204:~/ansible/library/cloud$ fgrep ec2_argument *
cloudformation:    argument_spec = ec2_argument_spec()
ec2:    argument_spec = ec2_argument_spec()
ec2_ami:    argument_spec = ec2_argument_spec()
ec2_eip:    argument_spec = ec2_argument_spec()
ec2_elb:    argument_spec = ec2_argument_spec()
ec2_elb_lb:    argument_spec = ec2_argument_spec()
ec2_group:    argument_spec = ec2_argument_spec()
ec2_key:    argument_spec = ec2_argument_spec()
ec2_tag:    argument_spec = ec2_argument_spec()
ec2_vol:    argument_spec = ec2_argument_spec()
ec2_vpc:    argument_spec = ec2_argument_spec()
elasticache:    argument_spec = ec2_argument_spec()
rds:    argument_spec = ec2_argument_spec()
rds_param_group:    argument_spec = ec2_argument_spec()
rds_subnet_group:    argument_spec = ec2_argument_spec()
route53:    argument_spec = ec2_argument_keys_spec()
s3:    argument_spec = ec2_argument_keys_spec()

jtanner@u1204:~/ansible/library/cloud$ fgrep ec2_argument ~/ansible/lib/ansible/module_utils/ec2.py 
def ec2_argument_spec():
```

**Comment by jctanner** [comment]
Fixed by https://github.com/ansible/ansible/pull/6415
