### ISSUE TITLE
list of things to include in 1st edition of community contrib repo

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#642]

**Comment by bradobro** [comment]
Repository deployment for those of us that have to use Mercurial sometimes:

https://github.com/bradobro/ansible-module-mercurial.git

**Comment by bradobro** [comment]
FWIW, the readme we edited:

https://github.com/bradobro/ansible-contrib/blob/master/README.md

**Comment by mpdehaan** [comment]
Ah, thanks...

**Comment by mpdehaan** [comment]
should add ansible-vagrant
jkleint's hadoop stuff
michael's earlier monitoring example
skvidal's automation scriptey thing and ansible-command

doc wise:
blog posts from jpmens, cocoy, mark

etc

**Comment by jpmens** [comment]
FWIW:
- [Install/remove packages with Zypper (bash module)](https://github.com/jpmens/ansible-zypp)

**Comment by jpmens** [comment]
And since @mpdehaan asked above, here are my postings:
- [Configuration management with Ansible. (intro)](http://jpmens.net/2012/06/06/configuration-management-with-ansible/)
- [Shell scripts as Ansible modules](http://jpmens.net/2012/07/05/shell-scripts-as-ansible-modules/)
- [Ansible: pull instead of push](http://jpmens.net/2012/07/14/ansible-pull-instead-of-push/) (with  [sample repository](https://github.com/jpmens/n-repo))
- [Generating facts](http://jpmens.net/2012/07/15/ansible-it-s-a-fact/)

**Comment by mpdehaan** [comment]
Michael's original postings to coloandcloud, michaeldehaan.net, and high scalability

**Comment by bradobro** [comment]
Just to be clear, this isn't a readme about  a module. It's readme about ansible-contrib policy that you vetted on our last try.

https://github.com/bradobro/ansible-contrib/blob/master/README.md

**Comment by mpdehaan** [comment]
We're not going to have a policy so much as just be a list of links.

**Comment by bradobro** [comment]
Good, sort I didn't catch that.

--Brad Olson (from phone)
On Jul 23, 2012 8:21 AM, "Michael DeHaan" <
reply@reply.github.com>
wrote:

**Comment by jkleint** [comment]
My Hadoop stuff is here:
https://github.com/jkleint/ansible-contrib/tree/master/playbooks/hadoop_jkleint

Let me know if we're going to go git submodule, as right now it's just a fork.

**Comment by mpdehaan** [comment]
Mark's LAMP stuff here:

https://github.com/fourkitchens/server-playbooks

**Comment by marktheunissen** [comment]
Those playbooks of mine don't contain any new modules. I'm working on a few for contrib but they aren't ready yet.

What about lineinfile module that was mentioned on the list?

https://github.com/azemon/ansible/blob/lineinfile/library/lineinfile

**Comment by jpmens** [comment]
Module for homebrew on Mac by nocturnal https://gist.github.com/3170079

**Comment by mpdehaan** [comment]
this exists now at github.com/ansible/ansible-resources, if people want to make updates they can submit pull requests there.

Thanks everyone
