### ISSUE TITLE
Cloning git repository fails with ansible 1.5.2

### ISSUE THREAD

**Issue by fago** [ansible/ansible#6431]
##### Summary:

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.
##### Steps To Reproduce:

Since the update from 1.4.4 to 1.5.2 (via the ubuntu PPAs) cloning a Git repository started failing. It turns out the directory gets cloned correctly, but ls-remote command fails now. When executing the command manually in the cloned Git directory it works, but when executing it manually elsewhere it produces the same error. 
Maybe ansible executes the command without chaing the working directory?

That's the configuration which worked previously as is: (drush_version defaults to "6.x")

```
- name: Drush | Cloning drush Git repo
  git: repo=https://github.com/drush-ops/drush.git
       dest=/opt/drush.git
       version={{ drush_version }}
```
##### Expected Results:

Task runs through as it should ;-)
##### Actual Results:

Error message:

```
failed: host] => {"cmd": ["/usr/bin/git", "ls-remote", "origin", "-h", "refs/heads/6.x"], "failed": true, "item": "", "rc": 128}
stderr: fatal: 'origin' does not appear to be a git repository
fatal: The remote end hung up unexpectedly

msg: fatal: 'origin' does not appear to be a git repository
fatal: The remote end hung up unexpectedly
```

**Comment by fago** [comment]
Updated description to match the template.

**Comment by mpdehaan** [comment]
This doesn't appear to be running through the new get_url code or anything so _may_ be a problem with github.

We'll see if we can reproduce this.

**Comment by mpdehaan** [comment]
This works for me on both 1.5.2 and the devel branch.

As we were seeing issues with github yesterday (lots) and some intermittent this morning, I expect this was github failing.  If you are still seeing problems, let me know.

This seems to align with what I'm seeing on https://status.github.com/messages

**Comment by jlaska** [comment]
I wonder if this may still be a problem.  Github appears to be operating normally, and I'm hitting the reported problem.

```
TASK: [update project using git and accept hostkey] ***************************
failed: [localhost] => {"cmd": "/usr/bin/git ls-remote origin -h refs/heads/master", "failed": true, "rc": 128}
stderr: fatal: 'origin' does not appear to be a git repository
fatal: The remote end hung up unexpectedly

msg: fatal: 'origin' does not appear to be a git repository
fatal: The remote end hung up unexpectedly

FATAL: all hosts have already failed -- aborting
```

**Comment by patricksmith** [comment]
I'm still seeing this issue, using a bitbucket repo, so I believe it is not tied to github. After looking into the code some, I think I have a viable solution in https://github.com/ansible/ansible/pull/6446.

**Comment by pesterhazy** [comment]
I'm also seeing the issue, i.e. the problem pointed out by @patricksmith. The problem is fixed in the current git version.

**Comment by fago** [comment]
Confirming this is working with 1.5.3 again - thanks!

**Comment by jscheid** [comment]
Is there a timeline for a 1.6.1 release with a fix for this?

**Comment by jctanner** [comment]
@jscheid 1.6 has not yet released and 1.5.4 will likely be the next incremental bugfix release.

**Comment by jscheid** [comment]
@jctanner that's confusing, a tarball for 1.6 is available for download at http://releases.ansible.com/ansible/ and it's the current version on MacPorts.

```
$ port info ansible | head -1
ansible @1.6 (sysutils)
```

EDIT: it looks like you've pulled the tarball now, for what it's worth I _think_ this will break MacPorts. See https://trac.macports.org/changeset/118046

**Comment by jlaska** [comment]
@jscheid Apologies for the mistake. It appears that an interim development build was mistakenly uploaded to releases.ansible.com.  The development build has been removed.  The latest stable ansible release continues to be 1.5.3.

**Comment by jscheid** [comment]
@jlaska no problem, but perhaps you want to let the MacPorts guys know. The ticket in question looks to be https://trac.macports.org/ticket/42941 (see 2nd comment)
