### ISSUE TITLE
Implicit localhost does not work with this simple example.

### ISSUE THREAD

**Issue by HelloGrayson** [ansible/ansible#6442]
##### Issue Type:

Bug  Report
##### Ansible Version:

ansible 1.5.2
##### Environment:

OSX 10.9.1
##### Summary:

Playbook errors out on this simple implicit localhost example.
##### Steps To Reproduce:

Create a playbook called `test.yml` with these contents:

```

---
- name: implicit localhost test...
  hosts: localhost
  tasks:
  - debug: msg="hello world"
```

Then run the file like so:

```
ansible-playbook test.yml
```
##### Expected Results:

```
TASK: [debug msg="hello world"] ***********************************************
ok: [localhost] => {
    "msg": "hello world"
}
```
##### Actual Results:

```
ERROR: provided hosts list is empty
```

**Comment by mpdehaan** [comment]
This works for me on the devel branch.

Can you share what is in your host file (/etc/ansible/hosts unless specified by an environment variable?)

**Comment by HelloGrayson** [comment]
`/etc/ansible/hosts` is empty. here is my ansible.cfg

```
[defaults]
remote_user = ubuntu
hostfile = ./inventory/ec2.py
host_key_checking = False

[ssh_connection]
pipelining = True
```

**Comment by HelloGrayson** [comment]
@mpdehaan were you able to reproduce using my `ansible.cfg`?

**Comment by HelloGrayson** [comment]
Just verified that this still does not work with 1.5.3

**Comment by mpdehaan** [comment]
Empty or missing?

**Comment by HelloGrayson** [comment]
@mpdehaan `/etc/ansible/hosts` does not exist. I installed ansible with pip on OSX.

**Comment by vadimkuznetsov** [comment]
If the hosts is empty, i.e. size 0 or  nova.py --list returns {}, then ansible-playbook fails with 
ERROR: provided hosts list is empty.
if hosts file has even garbage line, for example 300.300.300.300, then implicit localhost is present.

**Comment by jorgebastida** [comment]
Similar situation running a simple playbook which creates a vpc on aws using the `ec2_vpc` module. It works fine until I terminate the only server running on this account. I get `ERROR: provided hosts list is empty` thereafter. Booting a new empty server solves the problem.

**Comment by ScottSturdivant** [comment]
Seeing the same thing on Ansible 1.7.2 with an empty host list returned by the ec2.py dynamic inventory.  My use case is that I have AWS vars defined in group_vars/all.  As I'm creating my AWS infrastructure from the ground up, one of the first things I'm doing is creating VPCs, which will run against localhost.  This fails with the message: `ERROR: provided hosts list is empty.`

As others have pointed out, a non-empty host list solves this, but I shouldn't have to spin up an EC2 node just to run an action against localhost...  If I have a dummy inventory for localhost, then I have to duplicate the vars I've defined for AWS for them to apply to this new dummy inventory.  Yuck.  Would be nice if implicit localhost applied to dynamic inventory scripts also.

**Comment by c42f** [comment]
I've just hit this problem as well with ansible-1.8.2.  test.yml failes with a nonempty but commented out hosts file (/etc/ansible/hosts):

```
# no hosts declared here!
```

On the other hand, running the test.yml playbook succeeds with the following junk file:

```
[foo]
bar.org
```

It seems possible that this is related to the special case handling of localhost in `ansible.inventory.Inventory.list_hosts()`.  For example, with an empty hosts file, I get

```
$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ansible.inventory
>>> ansible.inventory.Inventory().list_hosts(pattern='all')
[]
>>> ansible.inventory.Inventory().list_hosts(pattern='localhost')
['localhost']
```

**Comment by gmalouf** [comment]
The ideal thing is for the ec2 script to include the implicit localhost as others have commented.  A nice alternative in my opinion would be for the inventory location to be configurable via ansible.cfg - i.e. specify a directory rather than a file.

**Comment by bcoca** [comment]
you can set hostfile = /path/to/dir in ansible.cfg

**Comment by gmalouf** [comment]
@bcoca I can confirm this works for picking up localhost with that script present - I set the hostfile property to point to /etc/ansible.

**Comment by bcoca** [comment]
now ansible will return warning on empty inventory via #9913

**Comment by khaderkool** [comment]
Any help is appreciated!!
ansible 2.0.2.0
I am new to Anisble, 
I am getting this error when I try use echo/copy module
command: 
        ansible raleigh -m shell -a 'echo $TERM' --verbose
        ansible atlanta -m copy -a "src=/home/prod/install.log dest=/tmp/hosts" --verbose
error:
       Using /etc/ansible/ansible.cfg as config file
       [WARNING]: provided hosts list is empty, only localhost is available
/etc/ansible/ansible.cfg
    inventory      = /etc/ansible/hosts
/etc/ansible/hosts
  [droplets]
    host1 ansible_ssh_host=169.14.7.126
    host2 ansible_ssh_host=169.14.7.127
But when I run ping module (ansible -m ping all) everything looks good
