### ISSUE TITLE
dnsmadeeasy module: regression in creating records

### ISSUE THREAD

**Issue by mcornick** [ansible/ansible#6457]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.2 installed via pip
##### Environment:

running from Mac OS X 10.9.2, managing Centos 6.5
##### Summary:

There has been a regression in the dnsmadeeasy module since Ansible 1.5. A task which ensures that an A record is present raises an exception.
##### Steps To Reproduce:

Install Ansible 1.5.2 and dopy. Create a role using the files at https://gist.github.com/markcornick/9516792. Run a play using this role against localhost.
##### Expected Results:

The play completes without errors, and an A record is created in the specified zone on DNS Made Easy. (This is the behavior of Ansible 1.5.)
##### Actual Results:

The play does not complete without errors, and an A record is not created:

```
PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [provisioning | create ansible ssh key] ********************************* 
ok: [localhost]

TASK: [provisioning | create ams2] ******************************************** 
ok: [localhost]

TASK: [provisioning | add ams2 to inventory] ********************************** 
ok: [localhost]

TASK: [provisioning | add ams2 to dns] **************************************** 
failed: [localhost] => {"failed": true, "item": "", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/mcornick/.ansible/tmp/ansible-tmp-1394659215.01-276422353786404/dnsmadeeasy", line 1658, in <module>
    main()
  File "/Users/mcornick/.ansible/tmp/ansible-tmp-1394659215.01-276422353786404/dnsmadeeasy", line 265, in main
    current_record = DME.getRecordByName(record_name)
  File "/Users/mcornick/.ansible/tmp/ansible-tmp-1394659215.01-276422353786404/dnsmadeeasy", line 187, in getRecordByName
    self._instMap('record')
  File "/Users/mcornick/.ansible/tmp/ansible-tmp-1394659215.01-276422353786404/dnsmadeeasy", line 200, in _instMap
    for result in getattr(self, 'get' + type.title() + 's')():
  File "/Users/mcornick/.ansible/tmp/ansible-tmp-1394659215.01-276422353786404/dnsmadeeasy", line 192, in getRecords
    return self.query(self.record_url, 'GET')['data']
TypeError: 'bool' object has no attribute '__getitem__'


FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
This is likely related to the failure handling around URLs that we have fixed elsewhere.

@jimi-c can you look at the basics around this?

**Comment by jimi-c** [comment]
@markcornick the above patch should resolve the issue for you, and we will include it in 1.5.3. Please let us know if you continue having problems with this module. Thanks!
