### ISSUE TITLE
ask_sudo_pass in the config is causing --sudo 

### ISSUE THREAD

**Issue by makimotoz** [ansible/ansible#6467]
##### Issue Type:

Bug report 
##### Ansible Version:

ansible 1.5.2
##### Environment:

Master centos 6.4. Manages rhel 5.5
##### Summary:

When using ask_sudo_pass in the config ("ask_sudo_pass  = True") I get auth issues in _some_ boxes.
Once the directive is set to false in the cfg file, that works without issues.
##### Steps To Reproduce:

set ask_sudo_pass  = True in the .cfg file and do any task that does not require actual sudo access on the remote box
##### Expected Results:

no auth issues
##### Actual Results:

```
$ ansible commando -m ping -K
sudo password:
previous known host file not found
commando | FAILED => Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p /tmp/ansible-1392202978.96-158385720428034 && chmod a+rx /tmp/ansible-1392202978.96-158385720428034 && echo /tmp/ansible-1392202978.96-158385720428034, exited with result 1: mkdir: cannot create directory `/tmp/ansible-1392202978.96-158385720428034':
```

**Comment by jctanner** [comment]
Confirming this is the wrong behavior per 506178542d04a15647467e4f055bfbf8ade1c70e

Reproduced on devel:

```
jtanner@u1204:~/issues/6467-sudo-broken$ cat inventory 
el6.lab.net
jtanner@u1204:~/issues/6467-sudo-broken$ ansible -vvvv el6.lab.net -i inventory -m ping
sudo password: 
<el6.lab.net> ESTABLISH CONNECTION FOR USER: jtanner
<el6.lab.net> REMOTE_MODULE ping
<el6.lab.net> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jtanner/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'el6.lab.net', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1395082508.26-32477581179168 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1395082508.26-32477581179168 && echo $HOME/.ansible/tmp/ansible-tmp-1395082508.26-32477581179168'"]
<el6.lab.net> PUT /tmp/tmp2xQAEY TO /home/jtanner/.ansible/tmp/ansible-tmp-1395082508.26-32477581179168/ping
<el6.lab.net> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jtanner/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'el6.lab.net', '/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=iywnqumnknicczzoglpfyrltapreozrt] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-iywnqumnknicczzoglpfyrltapreozrt; /usr/bin/python /home/jtanner/.ansible/tmp/ansible-tmp-1395082508.26-32477581179168/ping; rm -rf /home/jtanner/.ansible/tmp/ansible-tmp-1395082508.26-32477581179168/ >/dev/null 2>&1\'"\'"\'\'']
el6.lab.net | success >> {
    "changed": false, 
    "ping": "pong"
}
```

ansible-playbook appears to work properly.

**Comment by jctanner** [comment]
@makimotoz should be fixed in devel now. Thanks for the report!

**Comment by jf** [comment]
@jctanner cc @mpdehaan:

If I could just chime in very quickly (this issue was brought to my attention by @sivel at #7264): 5061785 is **`ansible-playbook`-specific**, where multiple tasks may be involved, _and "sudo: true" may not be in play for all tasks_, and hence it makes sense to (as per that commit message) 'Don't turn on sudo for all tasks when setting the sudo_user or ask_sudo_pass'). Does this logic carry over to `ansible`, when there is only 1 and only 1 task to run?

**Comment by jimi-c** [comment]
@jf you probably want to ask questions like this on the mailing list in the future, as we don't typically watch or respond to old issues (there's just too much noise with the level of activity here). That being said, yes it should carry over as the logic is in the core code and not in the bin/\* scripts like ansible or ansible-playbook. Looking through the code for bin/ansible, it does not appear that it was doing the same thing (I do not see `options.sudo =` anywhere.
