### ISSUE TITLE
Missing manpages for ansible-galaxy and ansible-vault

### ISSUE THREAD

**Issue by hlieberman** [ansible/ansible#6471]
##### Issue Type:

Documentation Report
##### Ansible Version:

Latest devel branch
##### Environment:

N/A
##### Summary:

There are missing man1 pages for the new ansible-galaxy and ansible-vault commands.  These files should be created or generated from asciidoc.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
I agree, flagging this as a priority thing to take care of.

**Comment by jimi-c** [comment]
Didn't mean to close this, just reference it from my commit. The man page for `ansible-galaxy` has been created.
