### ISSUE TITLE
Request to set_keepalive in paramiko_ssh

### ISSUE THREAD

**Issue by brdo** [ansible/ansible#6476]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5
##### Environment:

Running ansible on Ubuntu 10.04 64-bit 2.6.32-48-generic
managing client on Ubuntu 10.04 64-bit 2.6.38-16-server
##### Summary:

During a package install via ansible's apt module the package I'm installing reconfigures iptables which momentarily causes a disruption in ansible's SSH session  The result of this causes ansible to hang indefinitely and never finish the apt command. My client I'm trying to configure is Ubuntu 10.04. In order to fix this I added line 188 below to runner/connection_plugins/paramiko_ssh.py

187:            chan = self.ssh.get_transport().open_session()
188-            self.ssh.get_transport().set_keepalive( 5 )

Is there another way to do this using ansible.cfg or ssh config, or would ansible care to incorporate this change?
##### Steps To Reproduce:

The package I'm installing is software I cannot share, however I believe the root of the issue is iptables reconfiguration during an SSH session.
##### Expected Results:

I expect the ansible apt command to exit promptly after completing the action.  For some reason the session doesn't close unless I set_keepalive.
##### Actual Results:

The ansible apt command hung indefinitely and never exited.  NOTE: This is not a problem for every other package I've installed, so its definitely unique the package I'm installing.

**Comment by mpdehaan** [comment]
" I'm installing reconfigures iptables which momentarily causes a disruption in ansible's SSH session"

This can technically be handled with using "async" in fire and forget mode for this task, using a poll interval of 0, and then using "wait_for" to wait for the connection to come back online again.

Though if you'd like to submit a pull request for this we'd be happy to test it to see if it causes any ill effects with initial connections and slow attempts to diagnose that a host doesn't exist or things like that.

**Comment by mpdehaan** [comment]
I'm going to close this feature request ticket but if you would like to submit a pull request (since you have the above patch already) it can be in the queue for us to test and review.

Thank you!

**Comment by brdo** [comment]
Thank you I will
