### ISSUE TITLE
script module feature

### ISSUE THREAD

**Issue by kevintsai** [ansible/ansible#6485]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.6
##### Environment:

N/A
##### Summary:

I'm using bash script files as template a lot.  
Is it possible to make `script` module can be transferring via templates?

Current solution:  

```
- template: src=build_and_install_git.j2.sh dest=/tmp/build_and_install_git.sh
- shell: /tmp/build_and_install_git.sh
```

Hope `script` module can combine them like:  

```
- script: 
    src=build_and_install_git.j2.sh dest=/tmp/build_and_install_git.sh
    /tmp/build_and_install_git.sh
```

I would like to know if you consider this useful.

**Comment by mpdehaan** [comment]
So if you want to template something and then transfer it you could work around this by using
- local_action: template ...
- script: ...

To push the templated version.

We're unlikely to insert a new module to template the script for this reason.

Stop by the project list if you have questions and we can share more info. 

Thanks!
