### ISSUE TITLE
[Feature Idea] Ansible Galaxy - GalaxyFile

### ISSUE THREAD

**Issue by patrickheeney** [ansible/ansible#6490]
##### Issue Type:

Feature Idea
##### Ansible Version:

1.6+
##### Environment:

N/A
##### Summary:

This feature was originally proposed on [google groups](https://groups.google.com/forum/#!topic/ansible-devel/7AVJJL7_LEU) and will be summed up here for tracking purposes. 

At a high level this will provide the same functionality that a puppetfile does to librarian-puppet. In ansible terms this would be a pure YAML based document that contains instructions for ansible-galaxy to download, install, and update roles. This would allow for an familiar and convenient way to manage your galaxy roles, private / public / forked git roles, or even ones located on the file system. The galaxyfile could look something like this:

```
roles:
   - { source: galaxy, name: "foo.bar_role", version: "1234" }
   - { source: git, repo: "...", version: "1234" }
   - { source: file, path: "..." }
```

Upon running a command like `ansible-galaxy install -f galaxyfile.yml`, ansible galaxy would run through the galaxyfile and install the relevant versions from galaxy, git, or on your local file system. The `ansible-galaxy update` command would re-run this process and update any roles that are not tied to specific version.
##### Notes on Implementation
- Ansible GIT module should have all support functions moved to `module_utils/git.py` so that galaxy can use them. Look at basic.py or ec2.py for implementation on existing modules.
- Ansible galaxy when using a galaxy based role can hit the galaxy API to first check if an update is needed before downloading and installing. 
- The GIT based version would require git to be installed on the local machine in order to clone and checkout the version we want. Updates would be a simple git pull. 
- The file based version should could verify the checksum and cache is locally so on future updates it does not need to be re-installed. Look to leverage some functionality from the unarchive module.
- Ansible Galaxy `-f` option should remain backwards compatible with the comma delimitated format. It could just detect a `.yml` extension to load the new role parser.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
So yes, this was posted at Google Groups and had assumed you were building -- as this should be the case and I don't want to fragment the discussion, I don't think we need the feature ticket here in the issue tracker -- let's continue discussion on the list and if you want to submit a pull request we can discuss any details on that too.

Thanks!

**Comment by patrickheeney** [comment]
@mpdehaan, The last reply on the google groups discussion was from James Cammarata that said:

> Since the ansible-galaxy command is in the core repository for ansible, could you please open a new issue on github to keep track of this request?

Which way should I handle this?
