### ISSUE TITLE
ERROR! 'stat' is not a valid attribute for a Play  cannot get stat to work even with sample pulled from online

### ISSUE THREAD

**Issue by dpierce377** [ansible/ansible#65082]
Please raise issues via the [new interface](https://github.com/ansible/ansible/issues/new/choose)

**Comment by jborean93** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by dpierce377** [comment]
Sorry, my company does not allow me to access Google groups.

**Comment by jborean93** [comment]
The issue is that you are trying to run a list of tasks when it expects a play. There are alternatives to getting help with Ansible such as IRC but that and Google Groups are the only official sources of help for Ansible. GitHub is only used for bug support which this is not a bug.

**Comment by dpierce377** [comment]
[cid:image001.png@01D59F94.D6DC36B0]

From: Pierce, David A
Sent: Tuesday, November 19, 2019 4:22 PM
To: 'ansible/ansible' <reply@reply.github.com>
Subject: RE: [ansible/ansible] ERROR! 'stat' is not a valid attribute for a Play cannot get stat to work even with sample pulled from online (#65082)

Sorry, my company does not allow me to access Google groups.
