### ISSUE TITLE
Only first tag in role dependencies is used

### ISSUE THREAD

**Issue by ef4** [ansible/ansible#6517]
##### Issue Type:

Bug Report
##### Ansible Version:

Bug was introduced by 04a6dc6d12802a3d5de28a00773c5e4be794a1d2
##### Environment:

Debian Wheezy i686
##### Summary:

If you apply tags to multiple role dependencies, all but the first tag are ignored by ansible-playbook.
##### Steps To Reproduce:

`play.yml`

```

---
- hosts: bug_test
  roles:
  - bugtest
```

`roles/bugtest/meta/main.yml`

```

---
dependencies:
  - { role: other1, tags: tag1 }
  - { role: other2, tags: tag2 
```

`roles/other{1,2}/tasks/main.yml`

```

---
- debug: msg="Hello"
```
##### Expected Results:

`ansible-playbook play.yml --tags tag2` should work.
##### Actual Results:

`ERROR: tag(s) not found in playbook: tag2.  possible values: tag1`

**Comment by mpdehaan** [comment]
cc @jimi-c

**Comment by jimi-c** [comment]
Looking at this now.

**Comment by jimi-c** [comment]
The above patch should resolve the issue. If you continue having problems with this, please let us know. Thanks!
