### ISSUE TITLE
sysctl module always reports absent keys as changed

### ISSUE THREAD

**Issue by lfrancke** [ansible/ansible#6519]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

Managed OS: CentOS 6.5
##### Summary:

Any time an `absent` key is used this will result in a `changed` result even if it doesn't exist in sysctl.conf anymore.
##### Steps To Reproduce:

```
- name: Ensure that key does not exist
  sysctl: name=foobar state=absent
```

This happens due to this piece of code in `library/system/sysctl`:

```
        if self.file_values[thisname] is None and self.args['state'] == "present":
            self.changed = True
            self.write_file = True
        elif self.file_values[thisname] != self.args['value']:
            self.changed = True
            self.write_file = True
        if self.args['sysctl_set']:            
            if self.proc_value is None:
                self.changed = True
            elif not self._values_is_equal(self.proc_value, self.args['value']):
                self.changed = True 
                self.set_proc = True
```

The first `elif` branch will always be true for things that do not exist in the sysctl file. `self.file_values[thisname]` will be `None` as made sure by this piece of code

```
        if thisname not in self.file_values:
            self.file_values[thisname] = None
```

And `self.args['value']` will be the empty string '' instead of `None` due to this code in `_parse_values`:

```
       if value is None:
            return ''
```
##### Expected Results:

Don't report a `changed` result
##### Actual Results:

`changed`

**Comment by jctanner** [comment]
@lfrancke the patch above should fix the issue for you. Please let me know your test results.
