### ISSUE TITLE
git checkout always returns status changed

### ISSUE THREAD

**Issue by r0bj** [ansible/ansible#6526]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

Ubuntu 13.10
##### Summary:

git checkout always returns status changed, even if there was no changes at all:

```
- git: >
    repo=ssh://git@git.domain.it/git/zabbix-frontend.git
    dest=/usr/share/zabbix
    key_file=/home/{{ ansible_ssh_user }}/.ssh/id_rsa-domain_git
    accept_hostkey=yes
```

```
<z01> ESTABLISH CONNECTION FOR USER: user
<z01> REMOTE_MODULE git repo=ssh:********@git.domain.it/git/zabbix-frontend.git dest=/usr/share/zabbix key_file=/home/user/.ssh/id_rsa-domain_git accept_hostkey=yes
<z01> EXEC ['ssh', '-C', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/user/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'z01', '/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=xxx] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-xxx; /usr/bin/python\'"\'"\'\'']
changed: [z01] => {"after": "424fe2468c62068c7c106392f7e1fe8bcd72f60c", "before": "424fe2468c62068c7c106392f7e1fe8bcd72f60c", "changed": true, "item": "", "msg": "Local modifications exist"}
```
##### Steps To Reproduce:

Execute git module on some repository.
##### Expected Results:

Second time the checkout is executed then git module return no changed status.
##### Actual Results:

git checkout always returns status changed.

**Comment by patrickheeney** [comment]
When you run `git status` in that destination directory, do you have any changes? The message seems to imply your repo has local modifications which might be the reason it is always returning changed.

**Comment by r0bj** [comment]
You're right, there was one untracked symlink in local filesystem which cause this behaviour.

Please feel free to close this issue.
