### ISSUE TITLE
git integration tests require a github_ssh_private_key variable

### ISSUE THREAD

**Issue by patrickheeney** [ansible/ansible#6528]
##### Issue Type:

Bug Report
##### Ansible Version:

N/A
##### Environment:

N/A
##### Summary:

I am unable to run the GIT integration tests due to the fact they require a variable `github_ssh_private_key` to work. 

Per @jctanner on IRC:

> jtanner|mac: open a bug, that test shouldn't have special requirements
> jtanner|mac: the test is supposed to be public, so it shouldn't require a specific key

If it does need a key, perhaps all the tests could have a credentials.yml file, not just cloud providers so that we can easily add the keys and other information globally. It would also be helpful to have have instructions on how to setup and use the credentials.yml in the test/readme file.
##### Steps To Reproduce:

On a new install: `cd test/integration ; TEST_FLAGS='-t test_git' make`
##### Expected Results:

GIT tests would be executed, not skipped.
##### Actual Results:

Tests are skipped or fail because of `Permission denied (publickey)`.

**Comment by mpdehaan** [comment]
So basically we should just |default this and skip the test when there is no private key supplied.

**Comment by patrickheeney** [comment]
I believe it does skip some now. One issue I have is I don't know how to supply the private key, in what format, and the documentation did not cover this anywhere. To make this process easier I was hoping there could be a global credentials.yml file that is used for all tests, not just ec2. Fill out the necessary vars in credentials.yml and `cd test/integration; make` and they will all work.

**Comment by mpdehaan** [comment]
I agree that documentation on the credentials file additions is too sparse and needs some work.   Should be covered in integration/README.md ideally.

cc @jlaska

**Comment by jlaska** [comment]
@patrickheeney currently, there is a `credentials.template` file which is intended to outline all supported credential values.  The `Makefile` will refer you to the template if `credentials.yml` is not found.  

I've updated (750d9e2d59da531ac522e77dbb1f94ae2c8b5a5a) the `Makefile` to include `credentials.yml`, if found, in other make targets.  This change allows credentials to be used for all makefile targets.

Please note, credentials are still required for cloud tests.

```
# make cloud
No credentials.yml file found.  A file named 'credentials.yml' is needed to provide credentials needed to run cloud tests.  See sample 'credentials.template' file.
make: *** [credentials.yml] Error 1
```

The `credentials.template` file [currently lists supported values](https://github.com/ansible/ansible/blob/devel/test/integration/credentials.template).  Let me know if you have suggestions for improving the wording.

**Comment by mpdehaan** [comment]
Ok the following documentation upgrades should be sufficient, and jlaska indicates the git tests will continue without this setting.   Let me know if there are further issues/questions, thanks!

**Comment by patrickheeney** [comment]
This is great thank you. Will report back if I have any problems. Looking forward to writing and running some tests!
