### ISSUE TITLE
apt module can't install python-apt and silently fails

### ISSUE THREAD

**Issue by athoune** [ansible/ansible#6530]
##### Issue Type:

Bug report.
##### Ansible Version:

ansible 1.5.3
##### Environment:

OSX 10.9.2 managing a Debian 7.
##### Summary:

**apt** module doesn't install lazily **python-apt**
##### Steps To Reproduce:

Use apt module without python-apt installed.
##### Expected Results:

python-apt should be installed, and the playbook  not interrupted.
##### Actual Results:

There is no specific error, just a catch-all : `Could not import python modules: apt, apt_pkg. Please install python-apt package.`
##### Diagnostic:

`module.run_command('apt-get update && apt-get install python-apt -y -q')`
This command doesn't works :
`invalid output was: (100, '', 'E: The update command takes no arguments\n')`
Splitting the command fix the bug:

```
module.run_command('apt-get update')
module.run_command('apt-get install python-apt -y -q')
```

Some assertions should be nice.
Do you want a pull request for this?

**Comment by mpdehaan** [comment]
This is already fixed on the development branch and will be included in a future dot release.

The solution is to use the raw module to install python-apt via a shell command for now, or otherwise see that it is preinstalled.
