### ISSUE TITLE
Change sanatize_output to allow module-based privatization

### ISSUE THREAD

**Issue by jschwanz** [ansible/ansible#6533]
##### Issue Type:

Feature Idea
##### Ansible Version:

Ansible 1.5.2
##### Environment:

N/A
##### Summary:

Currently the way for module developers to have their inputs sanitized for logging is to modify the private_keys list to include their new parameter names, or to use the two blessed parameter names. This would allow module developers to add a value to the argument_spec (e.g. private=True) to choose which parameters to sanitize.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
"no_log=True" on the argument_spec already exists here and keeps things being logged in syslog.
