### ISSUE TITLE
Ansible inventory allows groups to have same name as hosts

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#6545]
##### Issue Type

Bug Report
##### Ansible Version:

ansible 1.6 (devel 9da26da335) last updated 2014/03/18 11:15:04 (GMT +1000)
##### Environment:

N/A
##### Summary:

If you define a group containing another group without the :children, then the intended group is a host, but will also become a group when defining its contents. 

The net result is that the host that should inherit characteristics of several layers of parents will not inherit those characteristics as the definitions will be:

grandparent -> parent(host)
parent(group) -> host

rather than
grandparent -> parent -> host

I believe that it should not be possible to define a group with the same name as a host (or at least a warning suggesting it might not be what you want should happen)
##### Steps To Reproduce:

See https://gist.github.com/willthames/9614054 
##### Expected Results:

See https://gist.github.com/willthames/9614054
##### Actual Results:

See https://gist.github.com/willthames/9614054

**Comment by mpdehaan** [comment]
This has probably always been a thing, I agree it should probably not be a thing such that if you define one when the other exists it's an error, but it's probably not in the super-urgent status category of bug reports.

Since Serge is working on some inventory upgrades, let's wait until this is done and applied and we can see about whether this can be dealt with efficiently.

**Comment by willthames** [comment]
Agreed - it just caught us out earlier ("why isn't this host inheriting the properties of the parent groups") and it was a very subtle one that would be good to flag. Happy to leave it until the dust settles behind Serge - at least it's documented for now.

**Comment by jkramarz** [comment]
@willthames having the groups and hosts named in the same way introduces also another interesting feature: #6314 :-)

**Comment by bcoca** [comment]
this is something we can fix when implementing https://github.com/ansible/proposals/issues/41, as of now both the inventory base class and each type of inventory source implements their own logic, it requires a major refactor to fix this (which the proposal already has)

**Comment by bcoca** [comment]
^ actually found way around it, at least to emit a warning, which should be enough for users to know there 'might' be a problem. If we want a way to avoid this in the first place or error 'on add' we still need the refactor.
