### ISSUE TITLE
Bug when resetting current directory

### ISSUE THREAD

**Issue by jeromew** [ansible/ansible#6546]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel 84908a57fc) last updated 2014/03/18 07:41:29 (GMT +000)
##### Environment:

control machine: fedora 19
remote centos 6.4
##### Summary:

I just hit a bug introduced by 
https://github.com/ansible/ansible/commit/a348f672389e6f1883d6afbe90ef76831e200bc0 a few days ago.

This patch does

```
# store the pwd
prev_dir = os.getcwd()
...
# reset the pwd
os.chdir(prev_dir)
```

but I am in a case where prev_dir=/home/userA and the module is executed with a sudo_user=userB

so when trying to revert the password I get : 

```
File "/tmp/ansible-tmp-1395131805.74-169742664365120/git", line 1626, in run_command
    os.chdir(prev_dir)
OSError: [Errno 13] Permission denied: '/home/userA'
```
##### Steps To Reproduce:

```
- name: Install Node Version Manager
  git: repo=git://github.com/creationix/nvm.git
       dest=/home/{{ u }}/nvm
  sudo_user: "{{u}}"
```
##### Expected Results:

ansible should not break because user {{u}} does not have rights on the prev_dir.
##### Actual Results:

```
File "/tmp/ansible-tmp-1395131805.74-169742664365120/git", line 1626, in run_command
    os.chdir(prev_dir)
OSError: [Errno 13] Permission denied: '/home/userA'
```

**Comment by jimi-c** [comment]
The above patch should fix the issue you're seeing. If you continue to run into this problem, please let us know. Thanks!
