### ISSUE TITLE
rhn_register module failing with 1.5.3 

### ISSUE THREAD

**Issue by mpontes** [ansible/ansible#6548]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

Ansible 1.5.3 on OS X, running against CentOS 6.5 hosts managed by Spacewalk.
##### Summary:

Module rhn_register module stopped working for me in Ansible 1.5.3 on CentOS 6.5 hosts connecting to a Spacewalk server. Worked in 1.5.
##### Steps To Reproduce:

```
rhn_register: state=present activationkey={{ spacewalk_key }} server_url={{ spacewalk_url }}
```
##### Expected Results:

```
ok: [***host****] => {"changed": false, "item": "", "msg": "System already registered."}
```
##### Actual Results:

```
Traceback (most recent call last):
  File "/home/mpontes/.ansible/tmp/ansible-tmp-1395139130.65-131190767219818/rhn_register", line 88, in <module>
    class Rhn(RegistrationBase):
NameError: name 'RegistrationBase' is not defined
```

Regression was probably introduced by a02641c0202a64.

**Comment by jctanner** [comment]
I'm running reposync on my fresh spacewalk server, so it'll be a while before I can thoroughly test any fixes.

**Comment by jctanner** [comment]
@mpontes 324a943e1278c63a16b8424b3e7f2a0872197efe should resolve the issue for you. Please let me know your test results.

**Comment by dirtyharrycallahan** [comment]
Will there be a dot release to fix 1.5.3?

**Comment by mpontes** [comment]
Working for me as of 324a943e1278, thanks.

**Comment by jctanner** [comment]
@dirtyharrycallahan yes, but we haven't set a date at this point.
