### ISSUE TITLE
Pipe lookup plugin giving "No such file or directory" in 1.5.1

### ISSUE THREAD

**Issue by dhorbach** [ansible/ansible#6550]
##### Issue Type:

Bug report
##### Ansible Version:

Ansible 1.5.1 - 1.5.3
##### Environment:

Centos 6.4 
##### Summary:

Pipe lookup plugin is no longer works since 1.5.1

Git bisect:

a02641c0202a643c9d70475789e3f0d8261ae2ee is the first bad commit
commit a02641c0202a643c9d70475789e3f0d8261ae2ee
Author: James Tanner tanner.jc@gmail.com
Date:   Mon Mar 10 16:11:24 2014 -0500

```
Force command action to not be executed by the shell unless specifically enabled
```

:040000 040000 a91b184f4f2c2dc5f355338de101f6332557239f b9a44328ce8e0a0ef2ed3b6c8feac380faa2d9d7 M      lib
:040000 040000 60db10f82ffe0ed5ef836aa5c9b393c5d262d7eb 8c3a9c8545c2e8f10d9ddf72704ce255bd437e58 M      library

```
- hosts: localhost
  gather_facts: false

  vars:
    lookup_var: '{{ lookup("pipe", "dirname /tmp") }}'
  tasks:
    - name: Test
      debug: var={{ lookup_var }}

```
##### Steps To Reproduce:

Add variable with lookup plugin
##### Expected Results:

Pipe lookup is working as expected
##### Actual Results:
```
Traceback (most recent call last):
  File "/opt/ansible/bin/ansible-playbook", line 307, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/opt/ansible/bin/ansible-playbook", line 247, in main
    pb.run()
  File "/opt/ansible/lib/ansible/playbook/**init**.py", line 247, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/opt/ansible/lib/ansible/playbook/play.py", line 99, in **init**
    ds = template(basedir, ds, self.vars)
  File "/opt/ansible/lib/ansible/utils/template.py", line 349, in template
    d[k] = template(basedir, v, vars, lookup_fatal, depth, expand_lists, fail_on_undefined=fail_on_undefined)
  File "/opt/ansible/lib/ansible/utils/template.py", line 349, in template
    d[k] = template(basedir, v, vars, lookup_fatal, depth, expand_lists, fail_on_undefined=fail_on_undefined)
  File "/opt/ansible/lib/ansible/utils/template.py", line 321, in template
    varname = template_from_string(basedir, varname, vars, fail_on_undefined)
  File "/opt/ansible/lib/ansible/utils/template.py", line 562, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 8, in root
  File "/usr/lib/python2.7/site-packages/Jinja2-2.6-py2.7.egg/jinja2/runtime.py", line 180, in call
    return **obj(_args, *_kwargs)
  File "/opt/ansible/lib/ansible/utils/template.py", line 554, in my_lookup
    return lookup(_args, basedir=basedir, *_kwargs)
  File "/opt/ansible/lib/ansible/utils/template.py", line 91, in lookup
    ran = instance.run(_args, inject=vars, *_kwargs)
  File "/opt/ansible/lib/ansible/runner/lookup_plugins/pipe.py", line 35, in run
    p = subprocess.Popen(term, cwd=self.basedir, shell=False, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by mpdehaan** [comment]
Please see if this is a problem in 1.5.3 and let us know. 

1.5.1 has had several problems which required updates.

**Comment by dhorbach** [comment]
Same problem with 1.5.3

$ ansible --version
ansible 1.5.3

**Comment by lied** [comment]
For me it works fine when there is no parameter to the command:

`lookup('pipe', 'date')` // works
`lookup('pipe', 'ls')` // works

`lookup('pipe', 'date +%Y')` // fails
`lookup('pipe', 'ls group_vars')` // fails

**Comment by jctanner** [comment]
Reproduced on ansible 1.6 (devel 3f5440f7df) last updated 2014/03/18 12:01:21 (GMT -400)

```
jtanner@u1204:~/issues/6550-lookup-broken$ cat site.yml 
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - debug: msg="{{ lookup('pipe', 'date') }}"
    - debug: msg="{{ lookup('pipe', 'ls') }}"
    - debug: msg="{{ lookup('pipe', 'ls /tmp') }}"
jtanner@u1204:~/issues/6550-lookup-broken$ ansible-playbook -i inventory -vvvv site.yml 

PLAY [localhost] ************************************************************** 

TASK: [debug msg="Tue Mar 18 12:05:34 EDT 2014"] ****************************** 
ok: [localhost] => {
    "msg": "Tue Mar 18 12:05:34 EDT 2014"
}

TASK: [debug msg="ansible.cfg
inventory
site.yml"] **************************** 
ok: [localhost] => {
    "msg": "ansible.cfg\ninventory\nsite.yml"
}
Traceback (most recent call last):
  File "/home/jtanner/ansible/bin/ansible-playbook", line 309, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/jtanner/ansible/bin/ansible-playbook", line 249, in main
    pb.run()
  File "/home/jtanner/ansible/lib/ansible/playbook/__init__.py", line 281, in run
    if not self._run_play(play):
  File "/home/jtanner/ansible/lib/ansible/playbook/__init__.py", line 658, in _run_play
    if not self._run_task(play, task, False):
  File "/home/jtanner/ansible/lib/ansible/playbook/__init__.py", line 399, in _run_task
    self.callbacks.on_task_start(template(play.basedir, name, task.module_vars, lookup_fatal=False, filter_fatal=False), is_handler)
  File "/home/jtanner/ansible/lib/ansible/utils/template.py", line 108, in template
    varname = template_from_string(basedir, varname, vars, fail_on_undefined)
  File "/home/jtanner/ansible/lib/ansible/utils/template.py", line 338, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 9, in root
  File "/usr/lib/python2.7/dist-packages/jinja2/runtime.py", line 180, in call
    return __obj(*args, **kwargs)
  File "/home/jtanner/ansible/lib/ansible/utils/template.py", line 330, in my_lookup
    return lookup(*args, basedir=basedir, **kwargs)
  File "/home/jtanner/ansible/lib/ansible/utils/template.py", line 91, in lookup
    ran = instance.run(*args, inject=vars, **kwargs)
  File "/home/jtanner/ansible/lib/ansible/runner/lookup_plugins/pipe.py", line 35, in run
    p = subprocess.Popen(term, cwd=self.basedir, shell=False, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by ramondelafuente** [comment]
I see this was solved by setting shell=True; 

A similar problem with ansible-vault could be solved in the same way: https://github.com/ansible/ansible/pull/6580

I did not know if there where other implications to setting the shell to True, so I decided against it. If it's an OK practice, I could rewrite the pull request.

**Comment by ralovely** [comment]
Hi.
I ran into the same issue.
Any chance to see this bug fix in 1.5.4 or will we have to wait 1.6 ?

Thanks.

**Comment by jjshoe** [comment]
@ralovely - If you look at 49807877fa4e69f6047efa4f7885a3d454a9d6eb you'll see it's pretty easy to fork 1.5.4 and apply the fix yourself if it's critical.

**Comment by ralovely** [comment]
Thanks @jjshoe 
I saw that. Easy enough indeed.
Knowing for when it is planned would help make this decision since we'd have to propagate to the whole team's machines.

**Comment by eproxus** [comment]
Downgraded to 1.5.0 but now I get `fatal: [server] => AES256 cipher could not be found` when using Vault files. This means our playbooks are now incompatible with 1.5.0 because of the vault error, and with 1.5.1+ because of the pipe errors. Any solutions for this?

**Comment by ramondelafuente** [comment]
@eproxus If you don't mind hacking the source untill the fix is released, this is the actual change: https://github.com/ansible/ansible/commit/49807877fa4e69f6047efa4f7885a3d454a9d6eb

In the file _lib/ansible/runner/lookup_plugins/pipe.py_ on line _35_

p = subprocess.Popen(term, cwd=self.basedir, **shell=False**, stdin=subprocess.PIPE, stdout=subprocess.PIPE)

Change to:

p = subprocess.Popen(term, cwd=self.basedir, **shell=True**, stdin=subprocess.PIPE, stdout=subprocess.PIPE)

**Comment by jimbocoder** [comment]
This has been pretty annoying to my team for a while now, though at least it's really simple to fix.  Requesting enthusiastically that it makes its way into the very next release!

**Comment by suprememoocow** [comment]
:+1: on getting this released as soon as possible

**Comment by jjshoe** [comment]
@jimbocoder @suprememoocow it's released now, if you use the development branch. Otherwise, you'll have to wait until the next release. If you want the fix now but don't want to use the development branch you'll need to manually apply it. Working with a team and don't want them to have to do work to get it? Use a local_action. You could also maintain your own fork. 

I for one don't want development rushed to production for one little bug.

**Comment by suprememoocow** [comment]
Hi @jjshoe, sorry, didn't intend to come across as being pushy or wanting to shortcut your release process, but simply looking forward to seeing this being released in due course. I'll investigate the `local_action` workaround in the mean time, but I don't think it'll work for me - I'll probably get the team to patch their ansible installations for now.

**Comment by jjshoe** [comment]
@suprememoocow it's not my release process, I'm not a maintainer, it's just you can have this solved in less time than it takes to comment on this issue. IMHO I'd add an ansible patches role, and use copy as a local action to install any patches. You'll have to do a little logic to handle where to find it on say linux vs osx, but still trivial to accomplish.

**Comment by joerick** [comment]
FWIW, if anyone wants work around this bug for now, the following is working for me:

```
 {{ lookup('pipe', [['git','rev-parse', 'HEAD']]) }}
```

Note the double square brackets. However, looks like the next release of ansible will break this, so be warned.
