### ISSUE TITLE
Treating tabs after the keywords not as an error

### ISSUE THREAD

**Issue by fbruetting** [ansible/ansible#65513]
### SUMMARY
I get that YAML is totally about indentation and tabs may make that mistakable – which is why you handle tabs at errors and I don’t want to discuss this. BUT: After the keywords (i.e. after their colon) it doesn’t make any difference if there are tabs or spaces, as it’s just important that there is any amount of whitespace between keywords and their value.

Currently, tabs behind the keywords are treated as errors – would you please not handle this as an error? As this totally is 100% **no** error and would never cause any ambiguities. It’s really a big pain, having to use massive amounts of useless spaces for indentation. This would help all tab users without a single downside for the YAML parser.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
yaml parser

##### ADDITIONAL INFORMATION

![Bildschirmfoto von 2019-12-04 18-20-04](https://user-images.githubusercontent.com/10520767/70165619-82f8d200-16c3-11ea-9934-b3d80ecb71b7.png)

**Comment by sivel** [comment]
This is not a function of Ansible, this is a function of pyyaml which is a YAML parser built to adhere to the YAML spec.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
