### ISSUE TITLE
issues with mount using mac and smbfs: option not supported, No such file or directory: '/etc/fstab'

### ISSUE THREAD

**Issue by darKoram** [ansible/ansible#6560]
##### Issue Type:

bug
##### Ansible Version:

ansible 1.6 (improve_openstack ae03aef9df) last updated 2014/03/15 12:51:06 (GMT -500)
##### Environment:

mac maverics
##### Summary:

I'm not sure if ansible mount is supposed to support smb mounts, but if so...

mount on a mac using smbfs requires the user first run 
sudo vifs  

Then ansible complains of 
msg: Error mounting /Volumes/Temp/Departmental_Shares: mount_smbfs: -o defaults: option not supported
##### Steps To Reproduce:
- local_action: mount src="{{Departmental_Shares}}"
               name="{{local_Departmental_Shares}}"
               fstype=smbfs state=mounted
  no_log: True
  sudo: yes
##### Expected Results:

I would expect to be able to use mount to accomplish the same as the commandline
mount -t smbfs '//username:userpass@myserver/PUBLIC' /smb/public

additionally, it would be nice if it could supply userpass from -K
Currently i pass it in with -e which is why i have the no_log
##### Actual Results:

There seem to be a couple of rough edges.

First, mac does not have /etc/fstab by default and you will get the following error:

TASK: [mount src="{{Departmental_Shares}}" name="{{local_Departmental_Shares}}" fstype=smbfs state=mounted] **\* 
failed: [localhost] => {"failed": true, "item": "", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/kbroughton/.ansible/tmp/ansible-tmp-1395165349.37-246234924856875/mount", line 1393, in <module>
    main()
  File "/Users/kbroughton/.ansible/tmp/ansible-tmp-1395165349.37-246234924856875/mount", line 296, in main
    name, changed = set_mount(**args)
  File "/Users/kbroughton/.ansible/tmp/ansible-tmp-1395165349.37-246234924856875/mount", line 115, in set_mount
    for line in open(args['fstab'], 'r').readlines():
IOError: [Errno 2] No such file or directory: '/etc/fstab'

After running sudo vifs and running the playbook again i see:

TASK: [mount src="{{filer_01_Departmental_Shares}}" name="{{local_filer_01_Departmental_Shares}}" fstype=smbfs state=mounted] **\* 
failed: [localhost] => {"failed": true, "item": ""}
msg: Error mounting /Volumes/Temp/Departmental_Shares: mount_smbfs: -o defaults: option not supported

**Comment by darKoram** [comment]
I noticed i'm pulling off an experimental branch.  I can submit again if necessary, but it is only openstack modules affected in the branch.

**Comment by jimi-c** [comment]
Hi @darKoram, it appears this issue should be refiled on the ansible-core-modules repository. If this issue is still a problem for you, could you please re-open it there? Thanks!
