### ISSUE TITLE
docs:  remove ansible-examples/language-examples and move into docs

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#6566]
##### Issue Type:

Docs Report
##### Ansible Version:

1.6
##### Environment:

N/A
##### Summary:

This section of ansible-examples is not like the others, and is not extended when new language things come out.  It's time to remove this and make sure anything inside is well covered in the docs, like the ec2 example is useful and should be shown there.
##### Steps To Reproduce:

N/A
##### Expected Results:

NA
##### Actual Results:

NA

**Comment by jimi-c** [comment]
Closing, as we will be addressing doc cleanup/updates at a later date and via the input of our technical writer.
