### ISSUE TITLE
ansible-galaxy install user experience is disastrous if you use roles and collections

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#65673]
##### SUMMARY

If I create one `requirements.yml` file which lists all my Ansible dependencies for a given project, including roles and collections from Galaxy, and try to install the dependencies using `ansible-galaxy`, it results in an unexpected and unintuitive behavior.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

ansible-galaxy

##### ANSIBLE VERSION

```
ansible 2.9.5
  config file = /Users/jgeerling/Downloads/blend-test/ansible.cfg
  configured module search path = ['/Users/jgeerling/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.6 (default, Feb  9 2020, 13:28:08) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/Users/jgeerling/Downloads/blend-test/ansible.cfg) = True
COLLECTIONS_PATHS(/Users/jgeerling/Downloads/blend-test/ansible.cfg) = ['/Users/jgeerling/Downloads/blend-test']
DEFAULT_ROLES_PATH(/Users/jgeerling/Downloads/blend-test/ansible.cfg) = ['/Users/jgeerling/Downloads/blend-test/roles']
```

##### OS / ENVIRONMENT

- macOS Catalina and Ubuntu

##### STEPS TO REPRODUCE

Create a new playbook project directory (e.g. 'example'). Inside the directory, create a `requirements.yml` file with the contents:

```yaml
---
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.java
    version: 1.9.7

collections:
  # Install a collection from Ansible Galaxy.
  - name: geerlingguy.php_roles
    version: 0.9.5
    source: https://galaxy.ansible.com
```

Run:

    ansible-galaxy install -r requirements.yml

##### EXPECTED RESULTS

All my project dependencies are installed as listed in the `requirements.yml` file.

##### ACTUAL RESULTS

```
$ ansible-galaxy install -r requirements.yml
- downloading role 'java', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-java/archive/1.9.7.tar.gz
- extracting geerlingguy.java to /Users/jgeerling/.ansible/roles/geerlingguy.java
- geerlingguy.java (1.9.7) was installed successfully

$ echo $?
0
```

This command works, and results in only the defined _role_ to install. So after being confused as to why the _collection_ doesn't get installed, I read through the Collections documentation and find that, if I want collections installed, I have to run a separate command. To illustrate:

```
# This will only install roles (and give no warning that collections were detected but not installed).
$ ansible-galaxy install -r requirements.yml

# This results in the same behavior as above.
$ ansible-galaxy role install -r requirements.yml

# This will only install collections (and give no warning that roles were detected but not installed).
$ ansible-galaxy collection install -r requirements.yml
```

Because most of my projects will either require roles or roles and collections in the `requirements.yml` file in the coming months/years (and will likely remain that way for the next few years as many roles on Galaxy that I depend on are not making the jump to Collections (especially simpler ones that are minimally maintained), this UX is kind of difficult to stomach, as now I'll need to make sure to have users do _two_ things every time they use or update one of my playbook projects (and CI will also need to run two commands).

It would make more sense to me to have the following behavior:

```
# Installs everything in requirements.yml (collections and roles).
$ ansible-galaxy install -r requirements.yml

# Only installs roles in requirements.yml (displays warning that there are also collections present in the file, if there are any).
$ ansible-galaxy role install -r requirements.yml

# Only installs collections in requirements.yml (displays warning that there are also roles present in the file, if there are any).
$ ansible-galaxy collection install -r requirements.yml
```

**Comment by geerlingguy** [comment]
Aside: Having roles use the key `src`, while collections use `name`, plus the optional `source` key for a galaxy server to use as the source server, adds an additional layer of confusion.

It seems like it would make a _lot_ more sense for both to use `name` for the _name_ of the role or collection, and maybe _type_ if you really wanted to specify if it's a role or collection. As it stands, roles and collections _cannot_ share a namespace + name in AH or Galaxy, so I don't see why there are two different standards to try to remember when it comes to specifying community content in Ansible requirements files.

**Comment by geerlingguy** [comment]
I was informed that to have a split-dependency-type requirements.yml file, I have to put roles under `roles:` and collections under `collections:`, like so:

```yaml
---
roles:
  # Install a role from Ansible Galaxy.
  - src: geerlingguy.java
    version: 1.9.6

collections:
  # Install a collection from Ansible Galaxy.
  - name: geerlingguy.php_roles
    version: 0.9.3
    source: https://galaxy.ansible.com
```

This indeed made the `ansible-galaxy install -r requirements.yml` command execute successfully, however, there was no indication that all dependencies were _not_ installed.

Therefore, I ask / propose:

  1. Why can't `ansible-galaxy install` install all the content inside a requirements file?
  1. Failing that, it should throw an error immediately upon seeing more than one type of dependency in the same file, stating you must run `ansible-galaxy role install` and `ansible-galaxy collection install` separately.

Also, the roles documentation doesn't have any mention of a `roles` definition in the `requirements.yml` file, but it looks like to inform Ansible (2.9+) of multiple types of content in a single file, you have to separate roles out under the `roles:` list, and collections into a `collections:` list.

See docs for:

  - [Roles requirements.yml](https://galaxy.ansible.com/docs/using/installing.html#installing-multiple-roles-from-a-file) (no mention of a `roles` section in requirements)
  - [Collection requirements.yml](https://docs.ansible.com/ansible/devel/user_guide/collections_using.html#install-multiple-collections-with-a-requirements-file)

**Comment by pabelanger** [comment]
+1

I would suggest we also version the requirements file now:

version: "2.0"
collections:
  - name: geerlingguy.php_roles
roles:
  - name: nginx.nginx

**Comment by geerlingguy** [comment]
FWIW, I just tested using `name` for roles and that seems to work as well as `src`. So that's nice, at least—you can have some consistency between the parameters for the two already:

```yaml
---
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.java
    version: 1.9.6
```

I did not test this with Ansible < 2.8 though, not sure when it was possible to start using the `name` parameter for roles.

**Comment by cristian04** [comment]
Im dealing with a related issue.

Ansible version:

```
$ ansible-galaxy --version
ansible-galaxy 2.9.4
  config file = /Users/cristian.russo/mac-dev-playbook/ansible.cfg
  configured module search path = ['/Users/cristian.russo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/cristian.russo/mac-dev-playbook/lib/python3.7/site-packages/ansible
  executable location = /Users/cristian.russo/mac-dev-playbook/bin/ansible-galaxy
  python version = 3.7.3 (default, Dec 13 2019, 19:58:14) [Clang 11.0.0 (clang-1100.0.33.17)]
```

Ansible-galaxy installing from a requirements file
```
$ ansible-galaxy install -r requirements.yml 
[WARNING]: - geerlingguy.dotfiles was NOT installed successfully: Unknown error
when attempting to call Galaxy at 'https://galaxy.ansible.com/api/api':
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
unable to get local issuer certificate (_ssl.c:1056)>

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

Installing manually
```
ansible-galaxy install geerlingguy.dotfiles
[WARNING]: - geerlingguy.dotfiles was NOT installed successfully: Unknown error
when attempting to call Galaxy at 'https://galaxy.ansible.com/api/api':
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
unable to get local issuer certificate (_ssl.c:1056)>

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by geerlingguy** [comment]
Today I got frustrated again when I had the following `requirements.yml`:

```yaml
---
collections:
  - name: community.kubernetes
    version: 0.9.0
```

And ran `ansible-galaxy install -r requirements.yml`.

There was no output, no success or error, nothing, just a blank line and back to my prompt.

I would imagine there should be _some_ sort of error message or something, saying "there was no content found" (though IMO it should install all collections when you call it without [collection|role]).

**Comment by geerlingguy** [comment]
I just rewrote the issue summary because the _original_ original issue was a simple bug in the documentation in a place outside the collections doc. But the UX issue still exists, and I'd call it a bug in the fact that when installing any content from Galaxy, there are weird behaviors that I wouldn't expect using the various `ansible-galaxy install` incantations, and definitely lead to new users struggling with the interface and `requirements.yml` files in general.

My principle is: if it's really hard for me to figure out a way to teach people how to do something simple, the UX could probably be improved—and I think of all the things surrounding collections, this is what irks me the most (since Galaxy roles are not going to vanish once 2.10 comes out, and many if not most users will have roles _and_ collections going forward... perhaps indefinitely, unless roles are officially deprecated at some point (I hope they're not?)).

**Comment by jborean93** [comment]
I've tried to try and simplify some of the behaviour around just `ansible-galaxy install` with a requirements file in https://github.com/ansible/ansible/pull/67843. I think follows the behaviour around what you have specified when `role` or `collection` is not set on the ansible-galaxy arg. The only caveat where this will not work is if someone specified a custom install path with `-p`, in that case it just deal with the roles in a requirements file.

It also adds a message in case both types are found but ansible-galaxy can only install 1.
