### ISSUE TITLE
git module ssh_opts uses default tempfile location instead of DEFAULT_REMOTE_TMP

### ISSUE THREAD

**Issue by rob-knox-ck** [ansible/ansible#6567]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5
##### Environment:

RHEL 6.5
##### Summary:

I am trying to utilize the key_file option but am encountering file permission issues because it is creating & attempting to execute a bash script under /tmp, which I do not have mounted as an executable filesystem for security.

It seems that the temp file should be getting created in DEFAULT_REMOTE_TMP instead.
##### Steps To Reproduce:
1. Mount your /tmp filesystem with noexec
2. Attempt to run a git fetch and explicitly specify a key_file:

```
ansible \
-i inventory/development "127.0.0.1" \
-m git \
-a "repo=git@github.com:dummy/dummy.git dest=/var/git-checkouts/dummy/ ssh_opts='-i ~/.ssh/github.key'"
```
##### Expected Results:

```
127.0.0.1 | SUCCESS >> {
"after": "4cecc65b0f88025f300bf5ee3f17ab5534asef3", 
"before": "4cecc65b0f88025f300bf5ee3f17ab512135se3",
"changed": true, 
"item": ""
}
```
##### Actual Results:

```
127.0.0.1 | FAILED >> {
    "cmd": "/usr/bin/git ls-remote origin -h refs/heads/master", 
    "failed": true, 
    "msg": "fatal: cannot exec '/tmp/tmp6KE768': Permission denied\nfatal: unable to fork", 
    "rc": 128, 
    "stderr": "fatal: cannot exec '/tmp/tmp6KE768': Permission denied\nfatal: unable to fork\n", 
    "stdout": ""
}
```

**Comment by jctanner** [comment]
@knoxr the above patch moves the script into the same path as the module, so if your modules are executable in that path, the git wrapper is definitely going to be executable too.

**Comment by rob-knox-ck** [comment]
Thanks for the quick fix!
