### ISSUE TITLE
ansible-galaxy collection install --upgrade <collection> 

### ISSUE THREAD

**Issue by pabelanger** [ansible/ansible#65699]
##### SUMMARY

Please add the ability for ansible-galaxy to upgrade an installed collection, this could be controlled via the --upgrade flag to install (this is like how pip works). 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ansible-galaxy CLI
##### ADDITIONAL INFORMATION

```
$ ansible-galaxy collection install ibm.qradar
Process install dependency map
Starting collection install process
Installing 'ibm.qradar:0.0.7' to '/home/pabelanger/.ansible/collections/ansible_collections/ibm/qradar'

$ ansible-galaxy collection install ibm-qradar-0.0.8.tar.gz 
Process install dependency map
Starting collection install process
Skipping 'ibm.qradar' as it is already installed

```

**Comment by geerlingguy** [comment]
+1 - Though I'm 50/50 on whether to recommend `--upgrade` (how pip works) or use `ansible-galaxy collection upgrade [name]` (as this feels more like the current UX of the CLI... or maybe that's just me?).

It would also be nice if this could be used for the use case:

  1. I ran `ansible-galaxy collection install -r requirements.yml` with collections, and collection `some.thing` is version `1.2.3`.
  1. I updated `requirements.yml` and set version to `1.3.0`
  1. I run `ansible-galaxy collection install -r requirements.yml` (maybe with `--upgrade`?)

After that last operation, the role `some.thing` should be at version `1.3.0`.

**Comment by pabelanger** [comment]
> +1 - Though I'm 50/50 on whether to recommend `--upgrade` (how pip works) or use `ansible-galaxy collection upgrade [name]` (as this feels more like the current UX of the CLI... or maybe that's just me?).
> 
> It would also be nice if this could be used for the use case:
> 
> 1. I ran `ansible-galaxy collection install -r requirements.yml` with collections, and collection `some.thing` is version `1.2.3`.
> 2. I updated `requirements.yml` and set version to `1.3.0`
> 3. I run `ansible-galaxy collection install -r requirements.yml` (maybe with `--upgrade`?)
> 
> After that last operation, the role `some.thing` should be at version `1.3.0`.

I could go either way on --upgrade or collection upgrade. I slightly prefer --upgrade or -U as it is a flag to toggle, not new command.

I am in agreement on your workflow example.

**Comment by jborean93** [comment]
@geerlingguy you can use `--force` to achieve your scenario right now. It will remove the older collection and install the newer one if a version is specified and does not match the already installed one. The `--force-with-deps` is like `--force` but will apply to the collections dependencies as well.

What doesn't work is a way to just blindly upgrade all collections to the latest version, you need to specify a version for `--force` to install the newer one.

**Comment by geerlingguy** [comment]
That’s how it works with roles currently too, but it’s quite annoying for a few reasons, two  of which I remember discussing in an old Galaxy issue about this same problem:

  1. Unlike every other dep/package manager in the world, I’m not able to run an update command, so figuring out the “--force” hack is not that great a UX.
  1. Assuming I have a lot of collections, it’s annoying to have to wait the 1+ minutes it takes the CLI to serially download each one, one by one.

**Comment by pabelanger** [comment]
To me, while --force works, it isn't ideal. The keyword 'force' to me is pretty dangerous, eg rm -rf /.

Where I see --upgrade, much like pip, which will upgrade a collection, while validating the collection fits into the constraint system.

**Comment by geerlingguy** [comment]
I'm also not sure if it goes here or elsewhere, but I created this dumb-but-saving-lots-of-time playbook [`ansible-requirements-updater`](https://github.com/geerlingguy/ansible-requirements-updater), and it actually updates all the requirements in my `requirements.yml` file, similar to what something like `composer update [package]` would do in a `.lock` file in the PHP world. That kind of feature may or may not be feasible without a proper lock/freeze file like what's mentioned in https://github.com/ansible/galaxy/issues/1358 though.

**Comment by rendhalver** [comment]
How about adding a `--upgrade` option to install.
So we could then rely on the `requirements.yml` file as the source of truth about what is installed.
This would be especially useful when running this as part of a CI pipeline or some other automation.

**Comment by apollo13** [comment]
@rendhalver `--upgrade` would work well for case where no version is specified. But if I explicitly specify a version with the collection I'd want it to upgrade/downgrade regardless of `--upgrade` (or `--force`) for that matter since I (imo) provided strong intent.

I have written more about this in ansible/proposals#181 -- please also share your thoughts there.

**Comment by wolftales** [comment]
is this the proposed command: 
`ansible-galaxy collection install <collection-name> --upgrade`

If my intent were to upgrade, that doesn't seem very initiative to me. I'd vote for:
`ansible-galaxy collection upgrade <collection-name>`

**Comment by jorhett** [comment]
this seems inconsistent with Ansible overall. Instead of creating a new UI why not be consistent with existing Ansible?

If the version differs then it should be fixed, no?  If the version is "present" then it should simply be there, etc.

**Comment by jborean93** [comment]
Was implemented with https://github.com/ansible/ansible/pull/73336 and will be in ansible-base 2.11. The changes reflect the behaviour of `pip` so it's `install -U` or `install --upgrade` to upgrade a collection. The `install` command will also upgrade the collection anyway if you specify a version constraint that doesn't match what is locally installed.
