### ISSUE TITLE
Unable to replace a file by a link

### ISSUE THREAD

**Issue by MiLk** [ansible/ansible#6576]
##### Environment:

Running from OSX 10.8.5
Managing CentOS 6.4
##### Summary:

The PR #6506 introduces a bug in the file module.
I'm no more able to symlink if the destination already exists and is a file.

The related changes is here https://github.com/bcoca/ansible/commit/2d25577e1104101c67bb5ac41790693780a6d51b#diff-5f4d0f7caf93b28e329795633ae2ce2eR299
##### Steps To Reproduce:

If discovered the bug with this task:

```
- name: Set the timezone to UTC
  file: src=/usr/share/zoneinfo/UTC dest=/etc/localtime state=link owner=root group=root force=yes
```
##### Expected Results:

The existing file should be replaced by a link.
##### Actual Results:

```
failed: [hostname] => {"failed": true, "gid": 0, "group": "root", "item": "", "mode": "0777", "owner": "root", "path": "/etc/localtime", "size": 23, "state": "link", "uid": 0}
msg: Error while linking: [Errno 17] File exists
```

By reverting the changes between the lines 299 and 309, it works.

**Comment by bcoca** [comment]
I'll take a look, this was part of my attempt to add atomicity to linking. By os.rename docs this should only fail on windows, but I probably missed a step.

**Comment by MiLk** [comment]
#6578 fixes the bug.
Thank you.
