### ISSUE TITLE
Procédure de mise à jour vers 2.9 ansible

### ISSUE THREAD

**Issue by Tya848** [ansible/ansible#65768]
Bonjour;

Je voulais upgrade ansible de 2.7 vers le 2.9 mais je ne trouve pas une procédure détaillée pour la suivre. Pouvez vous m'aider SVP?

Merci :)

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
