### ISSUE TITLE
ansible-vault 1.5.3 cannot decrypt files from 1.5.0

### ISSUE THREAD

**Issue by zytek** [ansible/ansible#6579]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.3
1.6
##### Environment:

OS X
##### Summary:

ansible-vault 1.5.3 (tested also HEAD) cannot decrypt files encrypted with ansible-vault 1.5.0.
##### Steps To Reproduce:

Try to decrypt file encrypted with ansible 1.5.0
##### Expected Results:

File decrypted.
##### Actual Results:

```
ERROR: Decryption failed
```

**Comment by mpdehaan** [comment]
We have unit tests for this, so this is interesting. 

Is there any chance you might have specified the wrong password?  (i.e. can you check decryption with the older version, etc?)

**Comment by mpdehaan** [comment]
also, can you test 'edit' as well as 'decrypt' ?

**Comment by zytek** [comment]
I have checked both edit, decrypt and also using password from file. 
Same issue on my friend's box.

Bonus issue: even when we encrypt files again with new vault (1.1, AES256) then ansible-playbook with --vault-password-file fails. Running more tests now, will update with command output.

**Comment by jctanner** [comment]
@zytek how are you installing ansible and testing the various versions?

Can we also see the output of these two commands?

```
python -c "import site; print site.getsitepackages()"
python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
```

**Comment by zytek** [comment]
Seems like it does not work only with long passwords.
Password in file has 50 chars. Works fine with 3 letter password.

```
bash-3.2$ brew switch ansible 1.5.0
Cleaning /usr/local/Cellar/ansible/1.5.0
Cleaning /usr/local/Cellar/ansible/HEAD
101 links created for /usr/local/Cellar/ansible/1.5.0
bash-3.2$ ansible --version
ansible 1.5
bash-3.2$ ansible-vault --vault-password-file=/Users/zytek/work/secure/ansible/vault_main_pass create test
bash-3.2$ cat test 
$ANSIBLE_VAULT;1.0;AES
53616c7465645f5f4390a0ca2764a1bedecb4304b6d7f528e95f6a20af89038941c37ce2ac970cc5
bfbef6aa0d4a63b799452df478ad58a72259851738bbff2ed45729c6231e4219d879dd0b1eb02f0f
e64931037c68cb469b2e17d7e3a987fc
bash-3.2$ brew switch ansible HEAD
Cleaning /usr/local/Cellar/ansible/1.5.0
Cleaning /usr/local/Cellar/ansible/HEAD
108 links created for /usr/local/Cellar/ansible/HEAD
bash-3.2$ ansible-vault --vault-password-file=/Users/zytek/work/secure/ansible/vault_main_pass decrypt test
ERROR: Decryption failed
bash-3.2$ ansible-vault --vault-password-file=/Users/zytek/work/secure/ansible/vault_main_pass edit test
ERROR: Decryption failed
bash-3.2$ ansible-vault --vault-password-file=/Users/zytek/work/secure/ansible/vault_main_pass create test2
bash-3.2$ cat test2
$ANSIBLE_VAULT;1.1;AES256
39623564633763646665363239386430396637306633306366346366643436336337303664363937
3564366664333066306336343161333634366236386334370a636633383039306435366461333335
33326261306563383464626335633230653332376438353265373133393238633236323331616231
6234373361383136300a326133376334666537386562663136326263636538316336393339626131
3637
bash-3.2$ ansible-vault --vault-password-file=/Users/zytek/work/secure/ansible/vault_main_pass decrypt test2
Decryption successful
```

**Comment by zytek** [comment]
@jctanner 

```
bash-3.2$ python -c "import site; print site.getsitepackages()"
['/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/Library/Python/2.7/site-packages']
bash-3.2$ python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
/Library/Python/2.7/site-packages
```

**Comment by zytek** [comment]
Short password test from file:

```
bash-3.2$ brew switch ansible 1.5.0
Cleaning /usr/local/Cellar/ansible/1.5.0
Cleaning /usr/local/Cellar/ansible/HEAD
rm p101 links created for /usr/local/Cellar/ansible/1.5.0
bash-3.2$ echo -n 123 > password
bash-3.2$ cat password 
123bash-3.2$ 
bash-3.2$ 
bash-3.2$ ansible-vault --vault-password-file=password create test-short
bash-3.2$ brew switch ansible HEAD
Cleaning /usr/local/Cellar/ansible/1.5.0
Cleaning /usr/local/Cellar/ansible/HEAD
108 links created for /usr/local/Cellar/ansible/HEAD
bash-3.2$ ansible-vault --vault-password-file=password decrypt test-short
Decryption successful
```

**Comment by zytek** [comment]
@jctanner @mpdehaan 

I have found the real bug - treating newline in vault password file.

```
bash-3.2$ echo 123 > password
bash-3.2$ ansible-vault --vault-password-file=password create test-newline
bash-3.2$ ansible-vault --vault-password-file=password edit test-newline
bash-3.2$ brew switch ansible HEAD
Cleaning /usr/local/Cellar/ansible/1.5.0
Cleaning /usr/local/Cellar/ansible/HEAD
108 links created for /usr/local/Cellar/ansible/HEAD
bash-3.2$ ansible-vault --vault-password-file=password edit test-newline
ERROR: Decryption failed
```

**Comment by zytek** [comment]
```
bash-3.2$ hexdump password 
0000000 31 32 33 0a                                    
0000004
```

**Comment by jctanner** [comment]
@zytek there's a newline char in the password it's self?

**Comment by zytek** [comment]
@jctanner 
yes. So the real "bug" is that it is treated differently by new version of ansible.

**Comment by jctanner** [comment]
@zytek taking a look now

**Comment by jctanner** [comment]
@zytek reproduced, working on a fix.

**Comment by jctanner** [comment]
Confirmed that newline chars in the password will work properly for encrypting and decrypting AES256.

**Comment by jctanner** [comment]
@zytek is the newline char at the end of the password?

**Comment by zytek** [comment]
@jctanner yes, as with this usecase:

```
[airbase:~]$ echo 123 > test 
[airbase:~]$ hexdump test
0000000 31 32 33 0a                                    
0000004
```

**Comment by jctanner** [comment]
@zytek this should be fixed in devel for you. If you do get a chance in the future, please update all your files to the AES256 cipher. Simply rekey'ing them with the same password will update them in place.

**Comment by zytek** [comment]
@jctanner 
Your fix breaks ansible in a pretty hardcore way. :/

Firstly, previous behaviour, although incompatible with 1.5.0, was "user friendly".
Consider this scenario:
1. User encrypts a file with ansible-vault encrypt file
2. ansible-vault prompts for password, user enters "123"
3. User now wants to store his password in a file and uses vim to create password-file. Vim by default leaves newline in this file so it is impossible to use it to decrypt. The only simple way is to use "echo -n password > file". This is really annoying and striping was actually good behaviour.. but incompatible.

Now the hardcore part: when testing this I have found that ansible-vault LEAVES EMPTY FILE AFTER DECRYPTING with password file ending with a newline. 

```
[airbase:~/tmp]$ ansible-vault encrypt testhotfix  
Vault password: 
Confirm Vault password: 
Encryption successful
[airbase:~/tmp]$ vim password                                                                                                                 
[airbase:~/tmp]$ hexdump password                                                                                                       
0000000 31 32 33 0a
0000004
[airbase:~/tmp]$ ansible-vault --vault-password-file=password decrypt testhotfix                  
ERROR: must be string or buffer, not None
[airbase:~/tmp]$ cat testhotfix                                                                                                                  
[airbase:~/tmp]$ 
```

**Comment by jctanner** [comment]
@zytek ok, it's going to have to disallow newlines at the end of the password. I have put the strip back into ansible-vault and moved it to the utils function so that the other cli tools have the same behavior.

**Comment by zytek** [comment]
@jctanner 

```
[airbase:~/tmp]$ echo test test > testfix2
[airbase:~/tmp]$ ansible-vault encrypt testfix2 
Vault password: 
Confirm Vault password: 
ERROR: 'NoneType' object has no attribute 'strip'
```

**Comment by jctanner** [comment]
@zytek are you trying to specify a blank password?

**Comment by zytek** [comment]
@jctanner no, "123"

**Comment by jctanner** [comment]
@zytek oops, sorry about that ... git pull and retry?

**Comment by zytek** [comment]
It still ZEROES file when I type empty password.

```
[airbase:~/tmp]$ echo test test > testfix3
[airbase:~/tmp]$ ansible-vault encrypt testfix3 
Vault password:  <---- 123 typed
Confirm Vault password: 
Encryption successful
[airbase:~/tmp]$ ansible-vault decrypt testfix3 
Vault password: <--- empty password typed
ERROR: must be string or buffer, not None
[airbase:~/tmp]$ ansible-vault decrypt testfix3
Vault password: <--- proper password typed
ERROR: testfix3 is not encrypted
[airbase:~/tmp]$ cat testfix3 
[airbase:~/tmp]$
```

**Comment by jctanner** [comment]
@zytek pull and retry again please.

This is what I tested for b8f627d1d543eb3acb181e0ff7c7a50bc6717402 ...

```
jtanner@u1204:~/issues/6579-vault-password-newline/test$ touch testfix4
jtanner@u1204:~/issues/6579-vault-password-newline/test$ cat testfix4
jtanner@u1204:~/issues/6579-vault-password-newline/test$ ansible-vault encrypt testfix4
Vault password:  <redhat>
Confirm Vault password:  <redhat>
Encryption successful
jtanner@u1204:~/issues/6579-vault-password-newline/test$ cat testfix4
$ANSIBLE_VAULT;1.1;AES256
62303566613336343435333633613664623139396537386437313962663530353664383135613135
6261653931303034386261336638366363313939373364610a383035636433336366313732316465
38303163343836353864633664353963656139363462343964626264373965626136323938356238
6137636166353536650a643465613534396531646334376162383564626464366335373761323234
6430
jtanner@u1204:~/issues/6579-vault-password-newline/test$ cp testfix4 testfix4.enc
jtanner@u1204:~/issues/6579-vault-password-newline/test$ ansible-vault decrypt testfix4
Vault password: <BLANK>
ERROR: Decryption failed
jtanner@u1204:~/issues/6579-vault-password-newline/test$ cat testfix4
$ANSIBLE_VAULT;1.1;AES256
62303566613336343435333633613664623139396537386437313962663530353664383135613135
6261653931303034386261336638366363313939373364610a383035636433336366313732316465
38303163343836353864633664353963656139363462343964626264373965626136323938356238
6137636166353536650a643465613534396531646334376162383564626464366335373761323234
6430
```

**Comment by zytek** [comment]
Works fine with ansible-vault

So, this will still be incompatible with 1.5.0 regarding newlines, right ? Worth mentioning in the docs probably?

Tommorow I'll test also with other CLI tools.

**Comment by jctanner** [comment]
@zytek correct, it's going to remain impossible to decrypt a 1.0 file encrypted with a newline char at the end of the password. However, we do expect users to upgrade to 1.1/AES256 so perhaps we should suggest decrypting all files on a 1.5.0 box and then re-encrypting on a 1.5.x 

However, I think you've caught some other issues here which weren't really tested previously. I'm glad those are now fixed.

**Comment by madrobby** [comment]
I'm on latest `devel` and using `--vault-password-file=xxxxx` no longer works, I get `ERROR: Decryption failed`. The same password, when typed in manually when using `ansible-vault edit blah.yml` works fine.

Note that I've encrypted the file with the same version (latest `devel`).

Version info: `ansible 1.6 (devel f82ac9f8e9) last updated 2014/03/22 20:02:55 (GMT -400)`

**Comment by zytek** [comment]
@madrobby  Can you reproduce command line flow that can show your error ? I am not having issues after @jctanner updates.

**Comment by zytek** [comment]
@madrobby @jctanner There is still issue with newline in password file. 

@jctanner 
Please revert changes in ansible and ansible-playbook
https://github.com/ansible/ansible/commit/409044155d2b6df49f63cc24d347e8cd715fe6a5

You have to strip input from file.

**Comment by madrobby** [comment]
I've tried with and without a newline in the file, same result. Unfortunately I'm sick in bed, but I'll try to repro once I feel better.

**Comment by zytek** [comment]
https://github.com/ansible/ansible/pull/6681
