### ISSUE TITLE
Expose Ansible version to the playbooks

### ISSUE THREAD

**Issue by FiloSottile** [ansible/ansible#6583]
##### Issue Type:

Feature Idea
##### Ansible Version:

`ansible 1.5.3`
##### Environment:

N/A
##### Summary:

It would be needed to have the Ansible version available from the playbooks in a variable, like `ansible_version` that evaluates to `1.5.3`.

There have been some issues recently that make my roles compatible only with the latest Ansible, and I'd like to enforce this.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
closing this since there's a pull request now.  Thanks!
