### ISSUE TITLE
Synchronize module  doesn't read user from ssh config

### ISSUE THREAD

**Issue by pgehres** [ansible/ansible#6590]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

Unrelated but
Host: OS 10.9.1, 
Target: Centos 6.4
##### Summary:

When using the synchronize module, rsync is attempting to use my local username on the remote server instead of utilizing the ssh config settings.  For example, my laptop user is peter.gehres, but I am pgehres on the production servers.
##### Expected Results:

I would expect that the synchronize module behaves the same way as all other tasks.
##### Actual Results:

```
ansible-playbook -i ec2.py site-aws.yml -l role_name --sudo -v

failed: [foo.bar.com] => {"cmd": "rsync --delay-updates -FF --compress --timeout=10 --recursive --rsh 'ssh  -o StrictHostKeyChecking=no' --rsync-path 'sudo rsync' --out-format='<<CHANGED>>%i %n%L' files/fonts peter.gehres@foo.bar.com:/path/to/files", "failed": true, "item": "", "rc": 255}

msg: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```

rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at /SourceCache/rsync/rsync-42/rsync/io.c(452) [sender=2.6.9]

I looked through the module code to see if I could determine where it was getting added, but it appears it is already in module.params before any code is executed in the synchronize module.
##### Steps To Reproduce:

Attempt to use synchronize on a host where your local username is not the same as the remote username and where ~/.ssh/config is used to set ssh parameters for connecting to the remote host.  I was using  --sudo but not -u or --private-key

**Comment by jctanner** [comment]
@pgehres synchronize has an action plugin where most of this logic occurs.

Please post an example playbook to demonstrate how you are trying to use the module so that I can see what attributes/hosts/usernames/sudo are being set.

**Comment by pgehres** [comment]
Aha.

```
- name: deploy custom fonts
  synchronize:
    src: files/fonts
    dest: /opt/atlassian/atlassian-confluence-5.0.3/confluence/files
    archive: false
    recursive: true
```

Is the task.  

```
- hosts: tag_appdynamics_docs
  roles:
    - common
    - ldap-client
    - docs
```

Is the entire play.

**Comment by pgehres** [comment]
I'll take a look at the action plugin as well.

**Comment by jctanner** [comment]
@pgehres can I see the -vvvv playbook output for the synchronize task?

**Comment by pgehres** [comment]
```
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1395279191.66-25243619658997 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1395279191.66-25243619658997 && echo $HOME/.ansible/tmp/ansible-tmp-1395279191.66-25243619658997']
<127.0.0.1> PUT /var/folders/br/vvckr2m13d12mzkgrsqstpp9g3gdkb/T/tmpkaro8q TO /Users/peter.gehres/.ansible/tmp/ansible-tmp-1395279191.66-25243619658997/synchronize
<127.0.0.1> EXEC ['/bin/sh', '-c', '/usr/bin/python /Users/peter.gehres/.ansible/tmp/ansible-tmp-1395279191.66-25243619658997/synchronize; rm -rf /Users/peter.gehres/.ansible/tmp/ansible-tmp-1395279191.66-25243619658997/ >/dev/null 2>&1']
failed: [remotehost] => {"cmd": "rsync --delay-updates -FF --compress --timeout=10 --recursive --rsh 'ssh  -o StrictHostKeyChecking=no' --rsync-path 'sudo rsync' --out-format='<<CHANGED>>%i %n%L' files/fonts peter.gehres@remotehost:/opt/atlassian/atlassian-confluence-5.0.3/confluence/files", "failed": true, "item": "", "rc": 255}
msg: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at /SourceCache/rsync/rsync-42/rsync/io.c(452) [sender=2.6.9]
```

**Comment by jctanner** [comment]
@pgehres what is the correct login for "remotehost" and where is that defined?

**Comment by mpdehaan** [comment]
Synchronize is basically just a wrapper around the following:

```
local_action: rsync ... 
```

In cases where you know more than what the module knows, it's just trying to be helpful, and if you do know EXACTLY what arguments you want to rsync, local_action rsync is going to be the better way to go.

In this case I suspect it's just adding on the username based on the current user and it's a toss up to say whether this should come from your SSH config or not -- and many users won't have this here.

When in doubt and you know rsync, advanced users can skip synchronize altogether.

A more complete example:

```
local_action: rsync -avz directory/ root@{{ inventory_hostname }}:/path/ --delete # and any other flags you want
```

(And this was also what people used before the synchronize module shortcut)

**Comment by pgehres** [comment]
@mpdehaan I see where you are coming from, but using the wrapper does have advantages.  For example, our automation runs as root, but we run locally with --sudo.  Synchronize handles that very well, local_action: rsync does not.

I guess my assumption would have been to not automatically add anything not specified as users would use "remote_user" or other options to override, correct?

**Comment by pgehres** [comment]
@jctanner is is pgehres@remotehost

It defined in my ssh config.

**Comment by jctanner** [comment]
@pgehres is there a specific section in the config for that host or is there a global username set for all hosts? Could we see a sample?

**Comment by pgehres** [comment]
The relevant sections are

```
ServerAliveInterval 30
VerifyHostKeyDNS ask

User pgehres

Host *.us-west-2.compute.amazonaws.com
        User pgehres
        ProxyCommand /usr/bin/ssh -q -W %h:%p usw2.amazon-bastion.com
```

**Comment by mpdehaan** [comment]
"For example, our automation runs as root, but we run locally with --sudo"

With respect to operating solutions, you could still pass the sudo options to the task here, of course.

```
- local_action: ...
  sudo: True
  sudo_user: foo
```

While I assume we could run a ssh invocation to inquire about the user (we definitely don't want to parse the file), this then makes the synchronize plugin a bit more connection mode aware than we wish, as with Paramiko the SSH config isn't utilized.

**Comment by pgehres** [comment]
```
- local_action: ...
  sudo: True
  sudo_user: foo
```

needlessly defines thing that we use nowhere else to work around things.  In fact, won't that sudo apply to the local connection?

I didn't mean to suggest that synchronize should parse the ssh config, in fact, I just want it to omit the username unless the task or the playbook explicitly defines the username that should be used to connect.  That way rsync itself uses the proper options.

**Comment by jctanner** [comment]
@pgehres this was actually a simple fix for your specific issue. I've added a "set_remote_user" parameter in the synchronize module, which is True by default. If you set it to "no"/False, it will not prefix the inventory username on the remote host:path. It does not change any other behaviors, so it should not cause conflicts for how other people are using the module.

**Comment by pgehres** [comment]
@jctanner thanks a bunch.  Will this go out in the next 1.5.X as a bugfix?

**Comment by jctanner** [comment]
@pgehres this is new functionality for the module, so it's a feature rather than a bug. It will most likely be in EDIT: 1.6.

**Comment by pgehres** [comment]
That is true, yes, but it is blocking our team (AppDynamics) from using the module. 1.6 is several months out, yes?

**Comment by tgerla** [comment]
Hi Peter, hit us up at http://support.ansible.com/ and we can help you out.
