### ISSUE TITLE
Unclear how to avoid entering --api-key on CLI when publishing Ansible Galaxy Collections

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#65933]
##### SUMMARY

As I begin publishing multiple collections, I'm finding it annoying to have to specify `--api-key` on the command line every time I run:

    ansible-galaxy collection publish ./geerlingguy-collection-1.2.3.tar.gz --api-key=[key goes here]

This not only requires me looking up the key in my password manager or on Galaxy, it also requires the key to be entered in plain text in a command that is then stored in my `history` file, unless I wipe it out.

Therefore, I'd like to specify the token via environment variable, or some other file that can be included. Ideally an environment variable, so I don't have to set up a configuration file for Ansible Galaxy (which is already the default server).

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
galaxy

##### ANSIBLE VERSION

```paste below
ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/jgeerling/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.5 (default, Nov  3 2019, 23:06:46) [Clang 11.0.0 (clang-1100.0.33.12)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /tmp/ansible-ssh-%%h-%%p-%%r
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 20
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/Users/jgeerling/Dropbox/VMs/roles']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
INTERPRETER_PYTHON(env: ANSIBLE_PYTHON_INTERPRETER) = /usr/local/bin/python3
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

N/A

##### ADDITIONAL INFORMATION

There are two relevant documentation pages:

  - [Galaxy Developer Guide](https://docs.ansible.com/ansible/latest/galaxy/dev_guide.html)
  - [Using Collections](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#configuring-the-ansible-galaxy-client)

It seems that both refer to a `token` with regard to Galaxy / Automation Hub, but only the collections guide mentions `--api-key`, and only relating to CLI usage. It seems that the `--api-key` is the same as the `token`, so the verbiage can be quite confusing (maybe the CLI needs to be updated to allow `--token` if they are indeed the same thing?

It also looks like, according to the documentation, I might be able to set:

    ANSIBLE_GALAXY_SERVER_RELEASE_GALAXY_TOKEN=[my token / api key]

But it also looks like that might be a magic variable that is only used if I add an entry for a galaxy server like `[galaxy_server.release_galaxy]` in my `ansible.cfg` file.

**Comment by geerlingguy** [comment]
From some investigation, it seems like I may be able to create a file at `~/.ansible/galaxy_token` with the format:

```yaml
token: [my token here]
```

**Comment by pabelanger** [comment]
From what I figured out a while back, --api-key === token. As a result, we create the following cfg file in our CI jobs:

  https://github.com/ansible/ansible-zuul-jobs/blob/master/roles/upload-ansible-collection-fork/templates/ansible.cfg.j2

Depending on the location of publish, we pass in new url and token

We then do:
```
$ ANSIBLE_CONFIG=/tmp/random_file ansible-galaxy collection publish foo.tar.gz
$ sred /tmp/random_file
```

Hope that helps

**Comment by geerlingguy** [comment]
Opened follow-up issue https://github.com/ansible/ansible/issues/65955 for the CLI change, specifically (since this ticket is more docs-focused).

**Comment by samccann** [comment]
Looking through the docs, I see:
https://docs.ansible.com/ansible/devel/reference_appendices/config.html?highlight=token#galaxy-token
 Which talks about both an ansible.cfg setting (GALAXY_TOKEN) and an environment variable setting (ANSIBLE_GALAXY_TOKEN).  Right below that there are similar settings for the token path to a file that stores the token.

**Comment by geerlingguy** [comment]
@samccann - Unfortunately, it looks like that token is not used by the `collection publish` command (at least that's my understanding). That is only used for role-based work.

**Comment by samccann** [comment]
@geerlingguy  too good to be true I suppose. Thanks for checking. My next question (for you and @jborean93 )  Is the following an accurate example?

[galaxy]
server_list = release_galaxy


[galaxy_server.release_galaxy]
url=https://galaxy.ansible.com/
token=my_token

(As in the token works only under the server list as you mentioned in one of your earlier comments?)

**Comment by samccann** [comment]
...and trying for an accurate example for using the path to a token file, would that be:

[galaxy]
server_list = release_galaxy

[galaxy_server.release_galaxy]
url=https://galaxy.ansible.com/
token_path=~/my_token_file

(But if you use the default location of ~/.ansible/galaxy_token , then you wouldn't need any of that in your ansible.cfg and you could just use the following command:

 ansible-galaxy collection publish path/to/my_namespace-my_collection-1.0.0.tar.gz

**Comment by jborean93** [comment]
Let's try to clear up some confusion, there are 3 ways to specify the token/api_key for authenticating when publishing a collection (or importing a role).

1. Using the `--api-key` argument with `ansible-galaxy`. This is named `--api-key` in collections because that is what it was named for the role commands and I just brought it across. We could add an alias for `--token` to align it all in a separate PR
    * If using this method, the token only applies to a server specified with `--server` or with [GALAXY_SERVER](https://docs.ansible.com/ansible/devel/reference_appendices/config.html?highlight=token#galaxy-server) (default if none specified)
    * Any servers defined in `ansible.cfg` under `server_list` will not use this value hence the note at the end of [this section](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#configuring-the-ansible-galaxy-client)

2. Adding `token: <token>` to `~/.ansible/galaxy_token`, this path is configurable with [GALAXY_TOKEN_PATH](https://docs.ansible.com/ansible/devel/reference_appendices/config.html?highlight=token#galaxy-token-path) as it was in some other location before 2.9

    * Once again this does not apply to any servers in the `ansible.cfg` server list. It only applies to `--server` or [GALAXY_SERVER](https://docs.ansible.com/ansible/devel/reference_appendices/config.html?highlight=token#galaxy-server) in the absence of any server_list entries in `ansible.cfg`

3. Specifying a server list in `ansible.cfg` and setting `token=<token>` for the server specified

    * Set by `token` in each `[galaxy_server.<name>]` entry
    * Automation Hub can also use `username` and `password` for basic auth but not Galaxy
    * Technically you can set this through env vars but they won't apply if you don't have `server_list` and `url` applied so not really ideal if all you want to do is specify a password with the default server

What cannot be done

* [GALAXY_TOKEN](https://docs.ansible.com/ansible/devel/reference_appendices/config.html?highlight=token#galaxy-token) is unfortunately named but it is **not** the token for Galaxy authentication. It is used by `ansible-galaxy login` to authenticate with your GitHub account and populate the file `~/.ansible/galaxy_token` with your actual Galaxy token
    * This is something that has been part of ansible-galaxy for many releases and potentially something that Galaxy wants to deprecate because it's only part of the V1 API, I have no idea if it will stay or go in the future
* Set `token_path` in the ansible.cfg as @samccann has suggested, if this is in the docs anywhere it should not be
    * The only valid options for each server entry are under [Galaxy server list configuration options here](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#configuring-the-ansible-galaxy-client)

Hopefully that explains things a bit more.

**Comment by samccann** [comment]
@geerlingguy @jborean93  - please take a look at the WIP PR. I think the info needs to be in more than one location, but want to be sure I captured the options correctly first....thanks.

**Comment by jborean93** [comment]
@samccann thanks for working on that, the changes seem fine but I'm potentially hesitant on actually documeting the `~/.ansible/galaxy_token` option. My personal thoughts is it adds further complication and it may go away at some future point in time.

**Comment by samccann** [comment]
ok I'll remove it for now @jborean93 unless someone else screams.  Meanwhile, do the same two other token/api-key descriptions also work for ansible-galaxy collection install?

**Comment by jborean93** [comment]
For Galaxy it doesn’t matter as the install steps can work unauthenticated but it would be needed for Automation Hub.
