### ISSUE TITLE
Documentation claims cpanm module is « New in version 1.0. » though it is not in any release since then.

### ISSUE THREAD

**Issue by JeanFred** [ansible/ansible#6594]
##### Issue Type:

Documentation Report
##### Ansible Version:

ansible 1.4.4
##### Environment:

N/A
##### Summary:

The [cpanm module documentation](http://docs.ansible.com/cpanm_module.html) claims that is « new in version 1.0 »; but said module is not part of any release tagged on GitHub.

According to [the history of the file](https://github.com/ansible/ansible/commits/devel/library/packaging/cpanm), it only exists in the develop branch.

The docs should be amended to make it clear that the cpanm module is not yet included in the Ansible releases.
##### Steps To Reproduce:

On the documentation side:
- Visit [cpanm module documentation](http://docs.ansible.com/cpanm_module.html)
- It is indicated that the `cpanm` module is included since 1.0

On the execution side:
Try using the `cpanm` step in a playbook.

```
  - name: Install Perl package with CPAN
    cpanm: name=Dancer
```
##### Expected Results:

On the documentation side:
- The cpanm module documentation should not state the module is included as it is not 

On the execution side:
- Ansible should install the package using the `cpanm` module. 
##### Actual Results:

Ansible (tested on 1.4.4 and 1.5.3) outputs the following:
    ERROR: cpanm is not a legal parameter in an Ansible task or handler

**Comment by mpdehaan** [comment]
This is actualy part of 1.6, what happened was someone copied the module boilerplate, and we need to update it to say 1.6 and push a new docs build.

Thanks for the heads up, I'll do this shortly.

**Comment by mpdehaan** [comment]
Pushing shortly, thanks for the heads up!

**Comment by JeanFred** [comment]
Thanks for getting this done so quickly!
