### ISSUE TITLE
encrypted /files support (ansible-vault, files/copy modules)

### ISSUE THREAD

**Issue by zytek** [ansible/ansible#6596]
##### Issue Type:

Feature Idea
##### Ansible Version:

N/A
##### Environment:

N/A
##### Summary:

add "encrypted=Boolean" parameter to copy/files modules so when True, files would be decrypted using ansible-vault prior to copying.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
Since they will be unencrypted on the remote anyway I don't think we're going to do this.

**Comment by zytek** [comment]
@mpdehaan 

It's unfortunate.

Our use case is that our remote servers are "secure" vel "trusted", but we would like to store our ansible roles on github/bitbucket which aren't trusted.

**Comment by ruudk** [comment]
I really want to do this to. I want to store an encrypted template on Github and have it auto decrypted on copying to the server.

**Comment by renaudguerin** [comment]
Add another vote, I wondered for a while why this wasn't working !

I finally managed to work around this by templating my config file and moving the secrets in it into variables, but I can see situations where this would be a bit ugly (server certificates in variables, really ?) or not possible at all.

**Comment by pkoro** [comment]
+1 for such a feature. It would help in handling sensitive files (i.e. certificate files) as mentioned previously also on this thread.

**Comment by ryanolson** [comment]
+1

**Comment by sbocahu** [comment]
+1.

**Comment by maheshbr** [comment]
+1

**Comment by wyrdangel** [comment]
+1  I too would like to be able to put things in our company github repo for a particular project without exposing it completely or having to do annoying and hacky-feeling workarounds in order to do so.

**Comment by raboof** [comment]
Can this be achieved with #8110 ?

**Comment by wyrdangel** [comment]
Yes I think so.  Bocca pointed me at this a couple days ago as well..so thank you both!

**Comment by mpdehaan** [comment]
Please see the above comment.
