### ISSUE TITLE
Ansible fetch only fetch specific file from directory not entire directory contents

### ISSUE THREAD

**Issue by vkkothawale** [ansible/ansible#66165]
Hi Team

While working with ansible fetch feature which is one of the best feature I found in ansible, I found that ansible fetch will only pull in the single file form remote machine it can not fetch (pull) entire directory contents form remote machine which I found while running playbook I got below message

fetch cannot work on directories, not transferring, ignored"

Is this some kind of ansible fetch drawback or will this be resolve in new feature ?

Please let me know 

Thanks,
Vivek

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
