### ISSUE TITLE
"[Errno 2] No such file or directory" error when 'validate' parameter on template module sets ENV variable

### ISSUE THREAD

**Issue by rwehner** [ansible/ansible#6621]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

Running ansible from CentOS 6.5
Managing CentOS 6.5
##### Summary:

When using the 'validate' parameter on the template module it produces an "[Errno 2] No such file or directory" error if the 'validate' argument includes setting a variable.
I suspect this is related to the recent security work around shell variable handling. Perhaps similar to https://github.com/ansible/ansible/issues/6385?
##### Steps To Reproduce:

Install Ansible 1.5.3
Run ansible-playbook with a template task that uses a 'validate' that sets a shell variable. The playbook [here](https://gist.github.com/rwehner/9696857) produces the error. We set the PATH in this way since visudo is at different locations on Linux and Solaris.
##### Expected Results:

No error produced and the shell command in the 'validate' parameter is run as it was in the 1.4 releases.
##### Actual Results:

```
$ ansible-playbook test_sudo.yml

PLAY [localhost] **************************************************************

TASK: [Install sudoers file] **************************************************
failed: [localhost] => {"cmd": ["PATH=/usr/sbin:/usr/local/sbin", "visudo", "-cf", "/usr/local/rpcm/.ansible/tmp/ansible-tmp-1395438209.82-186195729410123/source"], "failed": true, "rc": 2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/usr/local/rpcm/test_sudo.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1


```

**Comment by rwehner** [comment]
Updated description with appropriate template format.

**Comment by mpdehaan** [comment]
What is happening here is the validate command here is not being passed through the shell such that any arguments supplied are treated securely (for instance, such that if you referenced {{ user_input }} it couldn't invoke rm -rf, and so forth).

What you can do here, however, is path visudo explicitly, or also set the 'environment' keyword in Ansible.

We should likely indicate in the docs that this command cannot rely on shell functions.

**Comment by rwehner** [comment]
OK. I'll change break my tasks into two (one for Solaris and one for Linux with different explicit paths to visudo).

I've created a PR that hopefully updates the docs to include this information in an acceptable way. https://github.com/ansible/ansible/pull/6652

Thanks for the quick response.

**Comment by mpdehaan** [comment]
Closing since the above was already merged in, thank you!
