### ISSUE TITLE
Return error for groups.webservers

### ISSUE THREAD

**Issue by 5sfayas** [ansible/ansible#66297]
Please raise issues via the [new interface](https://github.com/ansible/ansible/issues/new/choose)
  uri: url=http://{{item}} return_content=yes
      with_items: groups.vm1
      register: app_index

above code return error like below

failed: [localhost] (item=groups.vm1) => {"ansible_loop_var": "item", "changed": false, "content": "", "elapsed": 0, "item": "groups.vm1", "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno -2] Name or service not known>", "redirected": false, "status": -1, "url": "http://groups.vm1"}

how do i pass my inventory groups to uri//localhost

**Comment by mkrizek** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
