### ISSUE TITLE
copy fails

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#663]
The copy module is failing for me  (devel branch, sha `153f3932b5dcd4f8b3dc8d41e5d7f7d28c4a1ec8`):

```
$ ansible -i ansible_hosts controller -m copy -u vagrant -a "src=playbooks/keystone/files/ntp.conf dest=/home/vagrant/ntp.conf"
192.168.206.130 | FAILED >> {
    "failed": true,
    "msg": "Source playbooks/keystone/files/ntp.conf failed to transfer"
}
```

If I switch back to the master branch, it succeeds:

```
$ ansible -i ansible_hosts controller -m copy -u vagrant -a "src=playbooks/keystone/files/ntp.conf dest=/home/vagrant/ntp.conf"
192.168.206.130 | success >> {
    "changed": true,
    "dest": "/home/vagrant/ntp.conf",
    "group": "vagrant",
    "md5sum": "a6551ead5e2b835d77160ae3cd192f64",
    "mode": "0664",
    "path": "/home/vagrant/ntp.conf",
    "src": "/home/vagrant/.ansible/tmp/ansible-1343095017.07-37899660367022/ntp.conf",
    "state": "file",
    "user": "vagrant"
}
```

**Comment by goozbach** [comment]
it appears to only happen when the dest file does not exist.

Something with the file module and the copy module fighting over what/when a file exists?

**Comment by jpmens** [comment]
Something wrong indeed: changed == false

```
$ rm /tmp/ff1
$ ansible 127.0.0.1 -v -c local -m copy -a 'src=JP dest=/tmp/ff1'
127.0.0.1 | success >> {
    "changed": false, 
    "group": "wheel", 
    "mode": "0644", 
    "path": "/tmp/ff1", 
    "state": "file", 
    "user": "jpm"
}
```

**Comment by mpdehaan** [comment]
fixed

**Comment by jpmens** [comment]
I don't see any difference after pull to dd6399b5aeac248fac6a884f60306e5b536642e6

```
$ rm /tmp/ff1
$ ansible 127.0.0.1 -v -c local -m copy -a 'src=JP dest=/tmp/ff1 mode=0600'
127.0.0.1 | success >> {
    "changed": false, 
    "group": "wheel", 
    "mode": "0644", 
    "path": "/tmp/ff1", 
    "state": "file", 
    "user": "jpm"
}
$ ls -l /tmp/ff1
-rw-r--r--  1 jpm  wheel  33 Jul 24 12:52 /tmp/ff1
```
1. `changed` still false
2. file modes incorrect.

**Comment by jpmens** [comment]
And note I passed `mode=0600` on the command line, but message says `0644`

**Comment by mpdehaan** [comment]
you are too fast, there was also something with the callbacks that I just pushed.

**Comment by jpmens** [comment]
Shouted because of the "fixed" :)

**Comment by jpmens** [comment]
Unless you're still working on this, `file` still sets incorrect permissions. (see example above).

**Comment by mpdehaan** [comment]
Not working on it now

**Comment by mpdehaan** [comment]
please open a new bug as this is different from the original

you will probably need to debug around the 'results2' stuff in Runner/**init**.py to see what the file module is being called with and seeing what it returns.  It may there is just a problem in the file module that can be found with hacking/test-module 

Note that hacking/test-module does not understand daisy chaining

**Comment by lorin** [comment]
I still have this problem with 263432d

```
$ ansible -i ansible_hosts controller -m copy -u vagrant -a "src=playbooks/keystone/files/ntp.conf dest=/home/vagrant/ntp.conf" --private-key=vagrant_private_key
192.168.206.130 | FAILED >> {
    "failed": true,
    "module": "copy",
    "msg": "Source playbooks/keystone/files/ntp.conf failed to transfer"
}
```

**Comment by mpdehaan** [comment]
Figured out the problem, because the tests were running on localhost, they were not sending over the new temp destination and it was still passing.

Tested it now and you can see in the output that the "src' is the temp path and not the actual path on the ansible "controller" machine.

Pull and see if you're fixed up.

**Comment by lorin** [comment]
Happy, happy, joy, joy:

```
$ ansible -i ansible_hosts controller -m copy  -u vagrant -a "src=playbooks/keystone/files/ntp.conf dest=/home/vagrant/ntp.conf" --private-key=vagrant_private_key
192.168.206.130 | success >> {
    "changed": true,
    "dest": "/home/vagrant/ntp.conf",
    "group": "vagrant",
    "md5sum": "a6551ead5e2b835d77160ae3cd192f64",
    "mode": "0664",
    "module": "copy",
    "path": "/home/vagrant/ntp.conf",
    "src": "/home/vagrant/.ansible/tmp/ansible-1343183155.4-176392428151450/ntp.conf",
    "state": "file",
    "user": "vagrant"
}
```

**Comment by binduwavell** [comment]
A year later, I appear to be seeing this same issue with the latest public release and also with a version I just pulled from github. If src is a relative path I get this error, if src is an absolute path this is working. Are there still known issues here?

Following is the playbook I'm using (linode.yml):

``` yaml
# password is this4now was generated with 'mkpasswd this4now'
---
- name: setup an ubuntu dev machine on linode
  hosts: linode
  user: root
  tasks:
  - name: add dev user with password to sudo group
    action: user name=dev password=ZrzFbFPOLTjZE
  - name: test copy
    action: copy src=files/etc/sudoers.d/dev.sudoer dest=/tmp/dev.sudoer
```

the file "files/etc/sudoers.d/dev.sudoer" exists in the directory where I'm running ansible-playbook from. This is the same directory where linode.yml exists.

**Comment by mpdehaan** [comment]
While info is appreciated, commenting on closed tickets is a great way to get a comment lost.

If you are seeing a problem open a new bug please, or bring up your question on the mailing list (preferred).

Thanks!

**Comment by mpdehaan** [comment]
Please make sure you also include the actual output of the playbook in the ticket/email too.

**Comment by binduwavell** [comment]
mpdehaan, I'm a newb, I posted the output to a pastebin per a request from IRC
