### ISSUE TITLE
yum package fails to install (or error) possibly when in the format xxx-xxx-xxx

### ISSUE THREAD

**Issue by mattsoftware** [ansible/ansible#6633]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel f82ac9f8e9) last updated 2014/03/23 09:19:06 (GMT +1000)
##### Environment:

Running ansible on OpenSuse ...

> cat /etc/issue
> Welcome to openSUSE 13.1 "Bottle" - Kernel \r (\l).

Managing Centos6 box...

> cat /etc/issue
> CentOS release 6.5 (Final)
> Kernel \r on an \m
##### Summary:

I am trying to install perl-ExtUtils-Embed and the yum command always succeeds but the package never gets installed.
##### Steps To Reproduce:
- yum: name=perl-ExtUtils-Embed state=installed
##### Expected Results:

the perl-ExtUtils-Embed package is installed on the remote system
##### Actual Results:

The package is not installed.

On further investigation it appears the remote command returns this to ansible:
{"msg": "", "changed": false, "results": ["perl-ExtUtils-Embed: Nothing to do"], "rc": 0}

I have also traced down the yum command being executed as:
['/usr/bin/yum', '-d', '2', '-y', 'downgrade', 'perl-ExtUtils-Embed']

I believe this is a result of the script checking the version of whats in the repo, compared with the version of whats being asked to install, and the script getting confused with the multiple dashes (I think its expecting to install the version 'Embed'). It then thinks we want an older version, trying a downgrade, but because the package isn't installed, there is nothing to do.

I am out of time trying to debug this issue any further.

**Comment by mpdehaan** [comment]
Note to us:  Likely worth testing this on 1.5.3 and without the last several commits to library/packaging/yum on devel.

**Comment by jimi-c** [comment]
This only affects the devel branch, and appears to be related to the yum downgrade support recently added (cbd1da645756e6d6fbd255bde37d9be452c547fe).

**Comment by jimi-c** [comment]
I've gone ahead and reverted the above commit, so this issue should be resolved. Please let us know if you continue seeing the above problem. Thanks!

**Comment by mattsoftware** [comment]
Issue is resolved, thank you.
