### ISSUE TITLE
pip setuptools tests fail

### ISSUE THREAD

**Issue by jamescassell** [ansible/ansible#66401]
##### SUMMARY

failure related to pip https://app.shippable.com/github/ansible/ansible/runs/155767/73/console that also failed on the nightly ci_complete run https://app.shippable.com/github/ansible/ansible/runs/155736/73/console
`ERROR: Package 'setuptools' requires a different Python: 2.7.12 not in '>=3.5'`

Passed on Saturday morning: https://app.shippable.com/github/ansible/ansible/runs/155712/73/console
Failure from Sunday morning: https://app.shippable.com/github/ansible/ansible/runs/155736/73/console

Possibly the same issue: https://app.shippable.com/github/ansible/ansible/runs/155777/87/console `08:23 ERROR: Package 'setuptools' requires a different Python: 2.7.12 not in '>=3.5'`

cc @felixfontein

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

tests

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by felixfontein** [comment]
Might be related to the newest setuptools release [45.0.0](https://pypi.org/project/setuptools/#history) from Saturday (Jan 12).

**Comment by felixfontein** [comment]
I've created a WIP which restricts setuptools to 44.0.0 for the tasks which fail: #66405

**Comment by felixfontein** [comment]
Tests pass, so it's no longer a WIP.

**Comment by felixfontein** [comment]
resolved_by_pr #66426
