### ISSUE TITLE
not_in_host_file does not check for readability of /etc/ssh/ssh_known_hosts

### ISSUE THREAD

**Issue by beberlei** [ansible/ansible#6644]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.2 (release1.5.3 f0a89d5bdf) last updated 2014/03/13 13:07:43 (GMT +200)
##### Environment:

Doesn't matter.
##### Summary:

not_in_host_file does not check for readability of /etc/ssh/ssh_known_hosts, leading to exception when file is not readable.

https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/known_hosts.py#L83
##### Steps To Reproduce:

Use git module with accept_hostkey on a non root user. Change /etc/ssh/ssh_known_hosts to 0600 before running.
##### Expected Results:

Skipping reading the /etc/ssh/ssh_known_hosts
##### Actual Results:

This file is not readable for my user, causing an exception:

```
line 1711, in not_in_host_file
    host_fh = open(hf)
IOError: [Errno 13] Permission denied: '/etc/ssh/ssh_known_hosts
```

**Comment by jimi-c** [comment]
The above patch should resolve the issue for you. If you continue seeing this problem, please let us know. Thanks!
