### ISSUE TITLE
Newly created files are owned by remote_user instead of the sudo_user

### ISSUE THREAD

**Issue by DXist** [ansible/ansible#6647]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.3. 
##### Environment:

N/A
##### Summary:

Template command doesn't respect sudo context from task include / single task.
##### Steps To Reproduce:

Create task file for a role:

```
# roles/common/tasks/main.yml

---
- include: mytasks.yml
  sudo: yes
  sudo_user: root
```

Create task with template command.

```
# roles/common/tasks/mytasks.yml

---
- template: src=mytasks.yml dest=/tmp/mytasks.yml

```
##### Expected Results:

The owner of  created /tmp/mytasks.yml should be root.
##### Actual Results:

/tmp/mytasks.yml owner is `remote_user`.

**Comment by mpdehaan** [comment]
We can think about this one, but it's always a very good idea to set an explicit owner when you have something particular in mind (edited description)

**Comment by mpdehaan** [comment]
@jimi-c indicates this may be an issue about sudo not being applied to the include.   Which is possible.

**Comment by jimi-c** [comment]
@DXist the sudo/sudo_user should be moved to your tasks in the included yaml. We do not currently apply some options when the include statement is used, though we should, so I'm editing the subject of this issue to reflect what's really going on.

**Comment by bcoca** [comment]
The file is copied to the server as remote_user, if the destination is on the same partition, rename is done so permissions are preserved, if destination is on diff partition, copy + rename is done, in which case permissions will be those of user making the copy (sudo_user).
 #6593 sets permissions if target already exists, we just need to do the same for when target does not exist to 'current user'.

**Comment by DXist** [comment]
> We can think about this one, but it's always a very good idea to set an explicit owner when you have something particular in mind (edited description)

@mpdehaan  I  design my playbooks to work in different environments. Some of them don't need sudo. I expect template task will use sensible defaults depending on current remote_user/sudo_user/su_user context.

> @jimi-c indicates this may be an issue about sudo not being applied to the include. Which is possible.

@mpdehaan  sudo applies to all tasks in include but there is an issue template owner/group

**Comment by jimi-c** [comment]
@DXist I've merged in the PR @bcoca referenced above, could you please retry this using the latest pull and see if it resolves the issue you're seeing?

**Comment by bcoca** [comment]
that will solve one case (target exists) but not the other (target does not exist)

**Comment by DXist** [comment]
Owner is set to `remote_user` in both cases - when there is no file and when there is a file owned by `remote_user`.

**Comment by jimi-c** [comment]
@DXist could you include the output of your playbook running with -vvvv and ANSIBLE_SSH_PIPELINING=no exported?

**Comment by jimi-c** [comment]
The above patch should fix the issue, if you're using the development branch. I've also changed the subject back, as it did end up being related to the way atomic_move() was working with new files rather than something related to include/sudo. If you continue having problems with this, please let us know. Thanks!

**Comment by DXist** [comment]
This patch did things as expected -  user/group of newly created file is root/wheel. Thank you!
