### ISSUE TITLE
vars_files prefetching is problematic and inconsistent

### ISSUE THREAD

**Issue by FiloSottile** [ansible/ansible#6651]
##### Issue Type:

Bug Report
##### Ansible Version:

`ansible 1.5.3`
##### Environment:

OS X
##### Summary:

The **vars_files** are pre-fetched for ALL the plays in a playbook at startup, meaning that if one of the plays creates one of those files, and a later play uses it, execution will fail.
##### Steps To Reproduce:

This is a minimal playbook presenting the issue.

```
- hosts: localhost
  tasks:
    - copy: 'dest="./bar.yml" content="EMPTY: --"'

- hosts: localhost
  vars_files:
    - "bar.yml"
  tasks:
    - debug: msg=foo
```
##### Expected Results:

Since by the time play 1 is executed _bar.yml_ exists (created by play 0), the playbook should run fine.

That is, **the vars_files should be checked and inspected when their play starts, not at startup**.
##### Actual Results:

```
$ ansible-playbook -i inventory.ini test.yml
ERROR: file could not read: .../bar.yml
```
### Partial workaround

This is the inconsistence. If the vars_files item is a list, then _could not read_ errors are ignored. So this is possible:

```
- hosts: localhost
  tasks:
    - copy: 'dest="./bar.yml" content="EMPTY: --"'

- hosts: localhost
  vars_files:
    - ["NOT_EXISTING_HACK", "bar.yml"]
  tasks:
    - debug: msg=foo
```

HOWEVER, if the bar.yml syntax is not valid the playbook will anyway fail at start, not allowing play 0 to fix it before play 1 executes, and also meaning that **edits by play 0 will be silently discarded, since play 1 will run the pre-fetched version**. This can be a nasty bug to find.

```
$ ansible-playbook -i inventory.ini test.yml
ERROR: .../bar.yml must be stored as a dictionary/hash
```

This shows that the only thing ignored with this workaround is the _could not read_ error.

Thanks.

**Comment by mpdehaan** [comment]
Sorry about this not doing what you like, though this is not a bug so much as the way it works, i.e. a design goal.

Plays should not create data for use later in the playbook.

Plays are parsed and then run as objects.

**Comment by FiloSottile** [comment]
Ok, I understand.

Wanted to check if it was intended.

Anyway, I think this should be documented. It can surprise.

Can I ask if there is a reason to this design decision besides performance?
