### ISSUE TITLE
what is the platform type os for WLC ?, how can my playbook identify wlc devices along with the hosts file. Please suggests ? thx

### ISSUE THREAD

**Issue by abdulbaazit** [ansible/ansible#66523]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by abdulbaazit** [comment]
what is the platform type os for WLC ?, how can my playbook identify wlc devices along with the hosts file. Please suggests ? thx

**Comment by justjais** [comment]
@abdulbaazit I believe by WLC you're trying to manage Cisco WLC config, if yes please ref: [aireos_config](https://docs.ansible.com/ansible/latest/modules/aireos_config_module.html).

And, if you have any further queries we have a dedicated Working Group for network. You can find other people interested in this in #ansible-network on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community.

Closing the issue as this isn't ansible issue.
