### ISSUE TITLE
Copy module fails after recent commits on devel branch

### ISSUE THREAD

**Issue by greenbrian** [ansible/ansible#6682]
##### Issue type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel a8064a78f3) last updated 2014/03/25 11:17:49 (GMT -500)
##### Environment:

RHEL 5.8
##### Summary:

Simple file copy fails with Python error in recent devel branch, succeeds in 1.5.2 release.

Playbook

```

---
- hosts: n7ltl501
  tasks:
  - name: copy test
    copy: src=/local/temp/installs/test dest=/local/testfile
```

Ansible version

```
$ ansible --version
ansible 1.6 (devel a8064a78f3) last updated 2014/03/25 11:17:49 (GMT -500)
```

Failure:

```
]$ ansible-playbook test.yml -i inv/TEST

PLAY [n7ltl501] ***************************************************************

GATHERING FACTS ***************************************************************
ok: [n7ltl501]

TASK: [copy test] *************************************************************
failed: [n7ltl501] => {"failed": true, "md5sum": "d68ba817e9aa3034436617554da0d2ad", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "<stdin>", line 1394, in <module>
  File "<stdin>", line 213, in main
  File "<stdin>", line 1242, in atomic_move
UnboundLocalError: local variable 'st' referenced before assignment


PLAY RECAP ********************************************************************
           to retry, use: --limit @/REDACTED/test.retry

n7ltl501                   : ok=1    changed=0    unreachable=0    failed=1
```

If on 1.5.2, it succeeds just fine.

```
$ ansible --version
ansible 1.5.2 (devel a9762357f9) last updated 2014/03/25 11:29:55 (GMT -500)

$ ansible-playbook test.yml -i inv/TEST

PLAY [n7ltl501] ***************************************************************

GATHERING FACTS ***************************************************************
ok: [n7ltl501]

TASK: [copy test] *************************************************************
changed: [n7ltl501]

PLAY RECAP ********************************************************************
n7ltl501                   : ok=2    changed=1    unreachable=0    failed=0

```

This is on RHEL 5.8 using Python 2.7.5 and uses host based authentication, which I've been using for a while now. I've tried various parameters to the copy with no change.

For reference, my ssh config details:

```
[ssh_connection]
pipelining = True
ssh_args=-o HostbasedAuthentication=yes -o PasswordAuthentication=no -o ControlMaster=auto -o ControlPath=/tmp/ansible-ssh-%h-%p-%r
```

**Comment by jimi-c** [comment]
@greenbrian could you try the following patch? I believe it will correct your issue but want to make sure before committing it:

<pre>
diff --git a/lib/ansible/module_utils/basic.py b/lib/ansible/module_utils/basic.py
index 2dcb9cd..4bdb3fc 100644
--- a/lib/ansible/module_utils/basic.py
+++ b/lib/ansible/module_utils/basic.py
@@ -966,11 +966,12 @@ class AnsibleModule(object):
         it uses os.rename to ensure this as it is an atomic operation, rest of the function is
         to work around limitations, corner cases and ensure selinux context is saved if possible'''
         context = None
+        dest_stat = None
         if os.path.exists(dest):
             try:
-                st = os.stat(dest)
-                os.chmod(src, st.st_mode & 07777)
-                os.chown(src, st.st_uid, st.st_gid)
+                dest_stat = os.stat(dest)
+                os.chmod(src, dest_stat.st_mode & 07777)
+                os.chown(src, dest_stat.st_uid, dest_stat.st_gid)
             except OSError, e:
                 if e.errno != errno.EPERM:
                     raise
@@ -1005,9 +1006,8 @@ class AnsibleModule(object):
                 if self.selinux_enabled():
                     self.set_context_if_different(
                         tmp_dest.name, context, False)
-                # Reset owners, they are not preserved by shutil.copy2(), which
-                # is what shutil.move() falls back to.
-                os.chown(tmp_dest.name, st.st_uid, st.st_gid)
+                if dest_stat:
+                    os.chown(tmp_dest.name, dest_stat.st_uid, dest_stat.st_gid)
                 os.rename(tmp_dest.name, dest)
             except (shutil.Error, OSError, IOError), e:
                 self.cleanup(tmp_dest.name)
</pre>

**Comment by greenbrian** [comment]
Seems to work, thanks.

**Comment by jimi-c** [comment]
Great, that's been merged into devel now. Thanks!
