### ISSUE TITLE
faster and more pythonic : replace dict() by {}

### ISSUE THREAD

**Issue by davidfischer-ch** [ansible/ansible#6685]
##### Issue Type:

Enhancement
##### Ansible Version:

ansible 1.6
##### Environment:

Ubuntu 13.10 amd64
##### Summary:

Using the pythonic {} instead of dict() to construct Python dictionaries is faster and more elegant.
http://doughellmann.com/2012/11/12/the-performance-impact-of-using-dict-instead-of-in-cpython-2-7-2.html
##### Steps To Reproduce:

```
git clone https://github.com/ansible/ansible
grep -r 'dict(' ansible/ | wc
2150  8924  195104
```
##### Expected Results:

It works, but faster.
##### Actual Results:

It works, but slower.

**Comment by mpdehaan** [comment]
If you have performance benchmarks where this is generating a real world problem, I'd be interested in seeing them, but we are using dict() because of readability.

I think most of the time we spend will be in network time (like yum updates) so this is probably not going to be a major concern.
