### ISSUE TITLE
Maybe a recursive import : ImportError cannot import name template

### ISSUE THREAD

**Issue by davidfischer-ch** [ansible/ansible#6687]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

Ubuntu 13.10 amd64
##### Summary:

Unable to import some modules of Ansible.
I fixed this in the closed pull request (https://github.com/ansible/ansible/pull/6654).
##### Steps To Reproduce:
- Install Ansible from GitHub devel branch.
- Execute this tinny python code: from ansible.callbacks import AggregateStats
##### Expected Results:

Expected to import.
##### Actual Results:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ansible/callbacks.py", line 18, in <module>
    import utils
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/__init__.py", line 29, in <module>
    from ansible.utils import template
ImportError: cannot import name template
```

**Comment by mpdehaan** [comment]
Shouldn't affect main ansible CLI or API operation, but I agree this should not be a problem.

On the other hand, I'm not really keen on the "from **future**" imports.

**Comment by davidfischer-ch** [comment]
This relative import statement also ensure that the modules are imported from the neighbour directories and not from any potential other installation of Ansible (registered in the path).
