### ISSUE TITLE
apt-key module does not update expired keys

### ISSUE THREAD

**Issue by josephtate** [ansible/ansible#6693]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.5
```

Git id is 14499e8bf3ed10f7818ec67e1f865d68e4a2a60b
##### Environment:

Running from Ubuntu 14/04 (alpha) managing Ubuntu 12/04. Both are x86_64.
##### Summary:

If an old key is present (previously uploaded, etc.), the apt-key module doesn't download new a new copy of it. If the old key is expired, a subsequent apt command will fail with 
    msg: '/usr/bin/apt-get dist-upgrade' failed: E: There are problems and -y was used without --force-yes
##### Steps To Reproduce:

For example, if you have 

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.10 (GNU/Linux)

mQENBE2AOZoBCACzWTHwaCCaqAssCKt9B4qcLIlTbY8zC3ZfZvQ/spwjmpdCK5Ny
4U8+WOllyjeHL/oXb5qJRLf+KgGJW8Pa0OsVWO9puoW3bTs2VmgjOya7nbN9FHip
bqJQVsMnbo12EPYtjCfv8f/P4iRNYmv9cTOaCwssA19DnLxWfEzXEK8SNgRgKSPC
EffyUc/TwBOAny2unJvTprPOdfX7tsrECU6DroWd64y69d+TJ+3jHrOD3Dg1YpNO
IFYJI6OfZT+zuAMc1ip7oHUAyHupGjpah05YjzFWYyoepR/5gCzNZTvuDMzDvD+S
08K0cklwKMwXYtT3Zzx2MzstbsxVFOyA8/mVABEBAAG0KERhdGFkb2cgUGFja2Fn
ZXMgPHBhY2thZ2VAZGF0YWRvZ2hxLmNvbT6JAT4EEwECACgFAk2AOZoCGwMFCQWj
moAGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJECJq6YDHp9pSObsH/2DyYgiM
P2r3FOiqH5ntsv4xvUNzc1V3bt/SCsLJWsv/9KrzTHnUxBsARmdW3xlyAEoR7YsV
erJK8ggbSW4BXarQuwvPhKOK0ujJ34xj2iVy8YSjtZhj6Y9UN+7OMr5vCyrlTrBk
IQkprNMAFH5hKAfXBM21ZX3VuCJ4xTC54lfDPI0RHAb7vzkp66lW7/HmCkhuTWzV
eaUZUM3ObGRX4s/oRKwTDXMRCAgxq219Oc0JPpZX4Jjpl/JzedkQOQBDCd8A2/XK
RXxhR59vPR09KaE8gyoaTj3jCQKds9kzYlXVVTXt27GKJj/VysznFUGBb7XQ4zJm
QF/owdADOimE9we5AQ0ETYA5mgEIAMr+xUQo8SwZJ3w9YcjsJlA6ISQwOwQF3QH9
3KqmgnC/WHbmwI/MV3XpvQT8dpp0asadPccn3xBqpvhYWTtkw57i0YvJfadyTKDJ
Q3R1PlsINxtucAfc1oAV50UjeWNlkLl/idhicaYd2V5oPistc5d0CfQqO/TDtzpX
5xxm+cXH4b1jIlNBAGybdcAJmvqkQlzpLQdY9pYz2H9T+E4CLKrmrNDONBM6tBfX
CctHtJ6xxjpESP8juSoMykx1uCH/cCjC/eyuFAS4CGYres/4+nQi3/M1USmua9L0
qH76KLu0jiuGpfk5E0ZQFEQkIByjRdOwIUZQ0k5kfgIwvEmMFGEAEQEAAYkBJQQY
AQIADwUCTYA5mgIbDAUJBaOagAAKCRAiaumAx6faUj6UB/9tlzrp5vFe6DOK8deZ
HH+hbEiOrw9WFXgHRDAREiFpENX+izjvSvxAaAoBNa//gAC1nSP6wIHAsGv7Ngqs
ZfXIqf5+pUZFJ+ZuCmIzJvT7j2ZLvSO9iq0DDIH1IwpzFDS/twPxdY3z9MkNbGdy
kKT+SilpQ7q9owbaWGVXhdUhv4UiaQPUv8m0qsZP4TQiLpK0QmxtGETDp/x6JlUu
rf96RjMz+KF8zO4S2sdiS71w1Azpo4YxATbKJIiNCHotpeQEA7b/A6W3N3E0LEZx
5B4Gkwhcf0LfcUzrTmNwrH98KXAYGYfGScOSuFdKx0/16rTdhjGBUYZ1CYGST7ZV
XGBg
=ULp6
-----END PGP PUBLIC KEY BLOCK-----
```

installed at /etc/apt/trusted.gpg.d/datadog.gpg, and then try to run
`apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x226AE980C7A7DA52 id=C7A7DA52 state=present keyring=/etc/apt/trusted.gpg.d/datadog.gpg`

You will not get the updated, non-expired key from the key server.
##### Expected Results:

I would expect that the old key (verified using apt-key fingerprints) would show a new key.
##### Actual Results:

Output from the command -vvv: note changed: false.

```
TASK: [common | Download ddog key] ******************************************** 
<solo.example.com> ESTABLISH CONNECTION FOR USER: root
<solo.example.com> EXEC ['ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jtate/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'solo.example.com', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1395787849.82-278212025348487 && chmod a+rx $HOME/.ansible/tmp/ansible-1395787849.82-278212025348487 && echo $HOME/.ansible/tmp/ansible-1395787849.82-278212025348487'"]
<solo.example.com> REMOTE_MODULE apt_key url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x226AE980C7A7DA52 id=C7A7DA52 state=present keyring=/etc/apt/trusted.gpg.d/datadog.gpg
<solo.example.com> PUT /tmp/tmp8HQUWk TO /root/.ansible/tmp/ansible-1395787849.82-278212025348487/apt_key
<solo.example.com> EXEC ['ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jtate/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'solo.example.com', "/bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-1395787849.82-278212025348487/apt_key; rm -rf /root/.ansible/tmp/ansible-1395787849.82-278212025348487/ >/dev/null 2>&1'"]
ok: [solo.example.com] => {"changed": false, "item": ""}
```

The old key is not replaced.

A later update command fails:

```
TASK: [common | Upgrade all the packages on the system] *********************** 
<solo.crunch.io> ESTABLISH CONNECTION FOR USER: root
<solo.crunch.io> EXEC ['ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jtate/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'solo.crunch.io', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1395787855.46-170897896010325 && chmod a+rx $HOME/.ansible/tmp/ansible-1395787855.46-170897896010325 && echo $HOME/.ansible/tmp/ansible-1395787855.46-170897896010325'"]
<solo.crunch.io> REMOTE_MODULE apt upgrade=dist update_cache=yes cache_valid_time=1200
<solo.crunch.io> PUT /tmp/tmpnsHRFa TO /root/.ansible/tmp/ansible-1395787855.46-170897896010325/apt
<solo.crunch.io> EXEC ['ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jtate/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'solo.crunch.io', "/bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-1395787855.46-170897896010325/apt; rm -rf /root/.ansible/tmp/ansible-1395787855.46-170897896010325/ >/dev/null 2>&1'"]
failed: [solo.crunch.io] => {"failed": true, "item": ""}
stdout: Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be upgraded:
  datadog-agent openssh-client openssh-server
3 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 5616 kB of archives.
After this operation, 51.2 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  datadog-agent

msg: '/usr/bin/apt-get dist-upgrade' failed: E: There are problems and -y was used without --force-yes
```

**Comment by josephtate** [comment]
Template applied

**Comment by mpdehaan** [comment]
The key module is designed to be (cough) idempotent (cough) in that it shouldn't hit the URL every single time to make sure the key is downloaded.

Though I can probably see something like a force=yes being addable, so I'll mark this as a feature idea as I can see that being useful/important.

(reasoning -- Imagine 500 hits on that URL once for each server for a 500 server infra, etc... it's kind of rough on the datadog server if everyone does this, etc).

**Comment by josephtate** [comment]
It is expired keys that I'm most concerned about. Checking the local
keyring to see if the configured key is expired does not require a network
request. If it is expired then go out and refetch the key. If no updated
key is available, error out.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by VojtechMyslivec** [comment]
Hi @mpdehaan. Is it possible to open this issue again or should I open a new one?

I have encountered same problem – gpg key expired and I need to update it.

I need to workaround it with Ansible ad-hoc command removing this key and then run playbook again.

Thanks

edit: sorry, re-open is probably not available. I will create a new issue
