### ISSUE TITLE
copy chains to file incorrectly (mode= is incorrect)

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#671]
```
$ rm /tmp/ff1
$ ansible 127.0.0.1 -v -c local -m copy -a 'src=JP dest=/tmp/ff1 mode=0600'
127.0.0.1 | success >> {
    "changed": true, 
    "dest": "/tmp/ff1", 
    "group": "wheel", 
    "md5sum": "f805a1c8bd9e3adec9b6a94844d00941", 
    "mode": "0644", 
    "module": "copy", 
    "path": "/tmp/ff1", 
    "src": "/Users/jpm/.ansible/tmp/ansible-1343138359.16-236375388664908/JP", 
    "state": "file", 
    "user": "jpm"
}
$ ls -l /tmp/ff1
-rw-r--r--  1 jpm  wheel  33 Jul 24 15:59 /tmp/ff1
```

@mpdehaan said:

> > you will probably need to debug around the 'results2' stuff in Runner/init.py to see what the file module is being called with and seeing what it returns. It may there is just a problem in the file module that can be found with hacking/test-module Note that hacking/test-module does not understand daisy chaining

**Comment by mpdehaan** [comment]
in execute_copy try changing:

```
  self.module_args = "src=%s dest=%s" % (tmp_src, dest)
        return self._execute_module(conn, tmp, 'copy', self.module_args, inject=inject).daisychain('file')
```

to

```
        return self._execute_module(conn, tmp, 'copy', self.module_args, inject=inject).daisychain('file')
```

and see if that fixes it.   Looks like it is internally throwing away other arguments.   This is probably also true of other places where we do daisychain('file')

**Comment by jpmens** [comment]
That does it. Thanks. (I'd have _never_ found that.)
Also fixes a bug in get_url, where permissions weren't set correctly.
PR en-route.

**Comment by jpmens** [comment]
Fixed in https://github.com/ansible/ansible/pull/673
