### ISSUE TITLE
authorized_key key_option not matching

### ISSUE THREAD

**Issue by ahelal** [ansible/ansible#6716]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5 and ansible 1.6 (devel 605156c904) l
##### Environment:

Running from Mac OSX 
Managing Ubuntu-12.04
##### Summary:

I am trying to add permitopen="ip:port" to authorized_keys file using the authorized_keys module.
##### Steps To Reproduce:

You would need to define 

```
- name: Deploy user
  authorized_key: 
     user="user"
     key="{{user_key}}"
     key_options='no-pty,permitopen="localhost:2313"'
```
##### Expected Results:

It should not fail and deploy to the authorized_keys file 
##### Actual Results:

I get an error 
msg: invalid option string: no-pty,permitopen=localhost:10050
##### Possible issue

It seems the issue is in the regexp https://github.com/ansible/ansible/blob/devel/library/system/authorized_key#L214

**Comment by DavidWittman** [comment]
@ahelal I'm not able to reproduce this issue using on Ansible 1.5.3 on Mac OS X managing an Ubuntu 14.04 VM.

Why is your error message reporting a different port than is shown in the example task which you provided?

**Comment by ahelal** [comment]
@DavidWittman It seems its fixed with the following commit https://github.com/ansible/ansible/commit/684d46b1707f9ff7cda6007b7399d1a614c6b9fd I tried with current development. Will consider this issue closed.
