### ISSUE TITLE
authorized_key adds trailing white space to keys

### ISSUE THREAD

**Issue by dkanbier** [ansible/ansible#67170]
##### SUMMARY

The authorized_key module adds a trailing white space to key entries when no comments are defined, which causes issues with SSH Signed Certificate logins on RHEL6.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
authorized_key

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
$
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux 6 and 7

##### STEPS TO REPRODUCE

Run this playbook:

```yaml
- name: Set authorized keys
  authorized_key:
    user: root
    key: https://github.com/charlie.keys
    manage_dir: no 
    path: /tmp/charlies.keys
```

##### EXPECTED RESULTS

There should be keys in /tmp/charlies.keys without trailing whitespaces.

##### ACTUAL RESULTS

The keys are present but have a trailing whitespace:

```paste below
$ cat -E /tmp/charlies.keys 
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvXbDjLXmYKySDg1By8ZD3a3cZ97bmqVpSZ9VSh/MgKlWVrd+1+Vg8fiNI5gXKJjKxZTvPAmF/M+SPmL9JylPqK9c4ujqVQmdytpYatLCZJXMqgxc9MdLNDUusFMZ3lB1uVvA55oU6MB1msv3gsqLnl4/WuaA2DPFRWOWXHUy4wNgcqIHwd5vgfNJKMgOOGWcBCV/NTDx55dbgrEdanLZ7/bK9FLeA11MIc64ogC1JSc9pUb/Ws+uRBxi+1R8ZaLBWOkAOvNKAwJ/dtFpy/0Y5O4oBDHD3MjuMnwr/4NlGtFeclqLDEIJA6rh2fhsRdSa66OoUR1GTWCzTPeK1cMSb $
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwJBq7EwYOF2H+bnUnj1CSeiEgHPae9wkgBP24KI+PJc7RSCDiwg4lTPyzM2bR0PF28nVTPMJZbxU7jHAyF4UI73Yqh4H4LvJZpwT8HOUMiCnIYiccklswWg4KkCdL7mcsxxdD6hxRm7tmoszM2aSnb8Fn2Oyvq+o3M+O72L72xzqWQ/aKRei1x8ZG50l3Mx38m6E/RTy3rY+ey01uLi2g42WePbULVS5+p3rUdfEFKliOTePl21FSbxAcJFGGzmPM6ATRdWf8J5SZT+7chEO9TG6jGKQbW13UG+N96Tn75nbMbCeHzNcDnPPTyRcSs3m9NyIjYcjC6gX9IWPeFoRD $
```

**Comment by dkanbier** [comment]
I think the cause is on this line in the authorized_key source:
https://github.com/ansible/ansible/blob/c3635532d3047ff944761005790d4be1111a8f72/lib/ansible/modules/system/authorized_key.py#L518

I believe this will always output a space after the key, even if there is no comment supplied.

**Comment by Shrews** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/ansible.posix

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
