### ISSUE TITLE
Module defaults group for vmware_*

### ISSUE THREAD

**Issue by xenlo** [ansible/ansible#67388]
##### SUMMARY
It could be helpful to have a [module defaults group](https://docs.ansible.com/ansible/latest/user_guide/playbooks_module_defaults.html#module-defaults-groups) for `vmware_*` modules.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- All vmware modules: `vmware_*`

##### ADDITIONAL INFORMATION
Several arguments are repeated each time for when using the vmware modules:
-    datacenter_name
-    esxi_hostname
-    hostname
-    hosts
-    password
-    username
-    validate_certs
-    …

I'm convinced that defining those as Module defaults will help to have simpler playbooks.

**Comment by sivel** [comment]
This is something that we cannot likely address right now.  The `vmware` modules, as well as most all modules are about to be removed from this repository and into a standalone collection.

Unfortunately, right now, content from collections do not support module defaults groups.  See https://github.com/ansible/ansible/issues/59864

As such, any additions to this repo, would simply be removed in several weeks.  When #59864 is addressed, we hope that collections will be able to define their own groups.

**Comment by xenlo** [comment]
I just learn from @bcoca that vmware modules are planned (v2.10) to move from Ansible core into Collection. 
So this Feature request is not that relevant…
