### ISSUE TITLE
Add ability to install a collection ignoring dependencies

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#67399]
##### SUMMARY

I recently tried installing the `community.general` collection for a test scenario I'm building, using the command `ansible-galaxy collection install -s https://sivel.eng.ansible.com/api community.general`, to get a particular filter that's going to be in it. When I tried installing it, two different things happened that are undesirable:

  1. It attempted to install all the additional following collections:
    - cisco.meraki
    - cisco.ucs
    - netapp.ontap
    - junipernetworks.junos
    - community.amazon
    - ansible.netcommon
    - cisco.mso
    - f5networks.f5_modules
    - gavinfish.azuretest
    - azure.azcollection
    - cisco.aci
    - google.cloud
    - community.kubernetes
  2. It ran into a bug owing to the fact that I have `community.kubernetes` checked out locally, using `version: 0.9.0` in the `galaxy.yml` and don't have a `MANIFEST.json` file locally (since it's a git clone and not a project downloaded via galaxy); it gave the message `TypeError: '<' not supported between instances of 'str' and 'int'`.

It would be nice if I could pass a flag like `--ignore-deps` or something like `--no-optional` (with those extra things being listed as 'optional' dependencies or something), because I don't really want or need a ton of networking collections present on my system.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ansible-galaxy

##### ADDITIONAL INFORMATION

Maybe the new command would be something like:

```
ansible-galaxy collection install --ignore-deps -s https://sivel.eng.ansible.com/api community.general
```

And it would result in the collection (and no dependencies) being installed in `community/general`, and that's it.

**Comment by geerlingguy** [comment]
Separately, for point #2 above, here's the stack trace from `-vvv`:

```
...
Processing requirement collection 'community.kubernetes' - as dependency of community.general
Collection requirement 'community.kubernetes' is the name of a collection
Collection 'community.kubernetes' obtained from server cmd_arg https://sivel.eng.ansible.com/api
ERROR! Unexpected Exception, this is probably a bug: '<' not supported between instances of 'str' and 'int'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 123, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 375, in run
    context.CLIARGS['func']()
  File "/usr/local/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 837, in execute_install
    no_deps, force, force_deps)
  File "/usr/local/lib/python3.7/site-packages/ansible/galaxy/collection.py", line 430, in install_collections
    validate_certs, force, force_deps, no_deps)
  File "/usr/local/lib/python3.7/site-packages/ansible/galaxy/collection.py", line 790, in _build_dependency_map
    parent=parent)
  File "/usr/local/lib/python3.7/site-packages/ansible/galaxy/collection.py", line 851, in _get_collection_info
    existing[0].add_requirement(to_text(collection_info), requirement)
  File "/usr/local/lib/python3.7/site-packages/ansible/galaxy/collection.py", line 114, in add_requirement
    new_versions = set(v for v in self.versions if self._meets_requirements(v, requirement, parent))
  File "/usr/local/lib/python3.7/site-packages/ansible/galaxy/collection.py", line 114, in <genexpr>
    new_versions = set(v for v in self.versions if self._meets_requirements(v, requirement, parent))
  File "/usr/local/lib/python3.7/site-packages/ansible/galaxy/collection.py", line 223, in _meets_requirements
    if not op(LooseVersion(version), LooseVersion(requirement)):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/version.py", line 70, in __ge__
    c = self._cmp(other)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
```

And it looks like this is because the command is comparing `*` to a version number and that might be what's failing.

**Comment by geerlingguy** [comment]
Related: https://github.com/ansible/ansible/blob/devel/lib/ansible/galaxy/collection.py#L224

**Comment by geerlingguy** [comment]
I just noticed/remembered that `ansible-galaxy install --help` shows:

```
  -n, --no-deps         Don't download roles listed as dependencies.
  --force-with-deps     Force overwriting an existing role and its
                        dependencies.
```

But it seems those don't apply to `ansible-galaxy collection install`...

**Comment by jborean93** [comment]
Sorry I know we talked about this offline but `--no-deps` will install the collection without trying to install the dependencies.

**Comment by geerlingguy** [comment]
@jborean93 - And to follow up on the 2nd point in the original issue (`TypeError: '<' not supported between instances of 'str' and 'int'`), was that fixed in devel? I believe someone else may have had a better test case that they found another related bug and both were fixed.

**Comment by jborean93** [comment]
Yep it was fixed with https://github.com/ansible/ansible/pull/67405 and a backport PR opened at https://github.com/ansible/ansible/pull/67413. @samdoran was able to replicate the TypeError by manually editing the version in the `MANIFEST.json` to a float value like `"version": 1.0.0`.
