### ISSUE TITLE
Blank output from the shell module under peculiar circumstances (probably not limited to that module)

### ISSUE THREAD

**Issue by trantor** [ansible/ansible#6742]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

Control: Ubuntu 12.04 Target/s: Ubuntu/Debian
UTF-8 locale on both control and target
##### Summary:

I've noticed how certain commands run through the shell module returned an OK exit status with, however, no standard output, when the same command run by hand on the target machine produces output as expected.

Git bisect leads to the commit fixing issue #4821, which concerns the encoding of module output, as far as i can see.

The specific command run through the shell module returned a mixture of UTF-8, ASCII and ISO-8859-1 encoded characters, and trying to run the same command with ansible code obtained from resetting to the commit preceding the fix for issue #4821 resulted in an exception.

Unfortunately the blank output, whilst maybe preferrable to an exception, can be quite confusing to the user, not to mention quite unhelpful.
##### Steps To Reproduce:
- Create a file with iso-8859-1 encoded characters on the target machine.
- Run a command which outputs the contents of the aforementioned file to the standard output through the ansible shell module

Otherwise, as an example:
- Save the contents of [this gist](https://gist.githubusercontent.com/trantor/9891925/raw/a6206b53c65b0bbf817b2ec44ca32a9f1fe37daf/testfile)
  as /tmp/testfile on a target machine
- Run «grep TEST /tmp/testfile» as argument to the shell command. It should output the first line of the file, instead it outputs nothing.
##### Expected Results:
- OK status
- Contents of the remote file in the module stdout
##### Actual Results:
- OK status
- Blank module output

**Comment by mpdehaan** [comment]
Can you link us to the file in questiona nd an example command?

Also, can you tell us what OSes are involved?  The previous involved Windows in the bug report, so this is why I'm asking.

Thanks!

**Comment by mpdehaan** [comment]
nm on the OS question, see above.

**Comment by trantor** [comment]
Save the contents of this gist
https://gist.githubusercontent.com/trantor/9891925/raw/a6206b53c65b0bbf817b2ec44ca32a9f1fe37daf/testfile
as /tmp/testfile on a target machine

Then run «grep TEST /tmp/testfile» as argument to the shell command.
It should output the first line of the line, instead it outputs nothing.

**Comment by alozovskoy** [comment]
It outputs nothing because Ansible didn't work with non-english characters in unicode. I also discovered this bug in https://github.com/ansible/ansible/issues/6772

**Comment by trantor** [comment]
By non-english I assume you mean characters outside the ASCII range? My problem is with non-unicode characters in the standard output of commands executed remotely.

**Comment by trantor** [comment]
News?

**Comment by alozovskoy** [comment]
Check this: https://github.com/ansible/ansible/issues/6842. I think that this issue must resolved you problem.

**Comment by trantor** [comment]
Thanks @alozovskoy and @jimi-c .
To @mpdehaan : I can confirm that the fix for #6842 also fixes issue #6742.
