### ISSUE TITLE
[Docker] AttributeError: 'bool' object has no attribute 'strip'

### ISSUE THREAD

**Issue by ruudk** [ansible/ansible#6744]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.3
##### Environment:

Running from Mac OS X 10.9.2 and executing on Ubuntu 12.4.4 LTS
##### Summary:

Trying to run an docker container fails and throws an error: `AttributeError: 'bool' object has no attribute 'strip'`
##### Steps To Reproduce:

``` yaml
- name: initialize ruudk/zbar
  docker: image=ruudk/zbar command=zbarimg
```
##### Expected Results:

Docker container should run
##### Actual Results:

```
fatal: [web1] => failed to parse: SUDO-SUCCESS-aoufzrjwdrylbmdanuecztrtjqjynbfj
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1396026342.4-190777332793281/docker", line 1812, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1396026342.4-190777332793281/docker", line 656, in main
    running_containers = manager.get_running_containers()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1396026342.4-190777332793281/docker", line 514, in get_running_containers
    for i in self.get_deployed_containers():
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1396026342.4-190777332793281/docker", line 501, in get_deployed_containers
    running_command = i['Command'].strip()
AttributeError: 'bool' object has no attribute 'strip'
```

**Comment by joshuaconner** [comment]
That's pretty weird. Can you post the output from running `docker ps` on that machine?

**Comment by ruudk** [comment]
```
vagrant web1.dev $ sudo docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

```

**Comment by joshuaconner** [comment]
I'm not able to replicate this on a test machine (you can see my playbook and output here: https://gist.github.com/joshuaconner/1b1fe742087d77fcaadb). 

Could you post the output from `docker ps -a` also?

**Comment by ruudk** [comment]
I cleared all my docker images and docker containers and tried again and it worked. So I guess it was a docker thingy. 

Thanks for checking this out @joshuaconner!

**Comment by joshuaconner** [comment]
You're welcome - feel free to update here (post your `docker ps -a` output) if you run into it again.
