### ISSUE TITLE
git module fails when credentials required - broken ForwardAgent? (ed: using Vagrant)

### ISSUE THREAD

**Issue by jhogendorn** [ansible/ansible#6760]
##### Issue Type:

Bug Report
##### Ansible Version:

```
% ansible --version
ansible 1.5.3
```
##### Environment:

OSX Mavericks host, Ubuntu 12.04 target running in Vagrant
##### Summary:

This task:

```
- name: Clone Dotfiles
  git: repo=git@github.com:jhogendorn/dotfiles.git dest={{ ansible_env['HOME'] }}/.dotfiles force=yes update=yes accept_hostkey=yes
```

when aimed at this vagrant test machine, 12.04 ubuntu LTS:

```
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
    ansible.host_key_checking = false
    ansible.start_at_task = "Clone Dotfiles"
    ansible.verbose = 'vvvv'

  end
end
```

with this ansible.cfg:

```
[ssh_connection]
ssh_args = -o ForwardAgent=yes
```

does not forward credentials, failing with this message:

```
TASK: [dotfiles | Clone Dotfiles] *********************************************
failed: [default] => {"cmd": ["/usr/bin/git", "ls-remote", "git@github.com:jhogendorn/dotfiles.git", "-h", "refs/heads/HEAD"], "failed": true, "item": "", "rc": 128}
stderr: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

msg: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

FATAL: all hosts have already failed -- aborting
```

I have also tried utilising all the options detailed in this [stackoverflow post](http://stackoverflow.com/questions/20952689/ansible-ssh-forwarding-doesnt-seem-to-work-with-vagrant/22265442#22265442) to no avail.

I'm not sure if this is an ansible or a vagrant or an ssh bug, but lets start here. There seems to be lots of noise on the googles for this issue but no-one seems to have a definitive answer.
##### Steps To Reproduce:

Attempt to pull a repository that needs credentials using the ansible git module aimed at a vagrant instance.
##### Expected Results:

It should pass credentials from my host through in order to pull the repository.
##### Actual Results:

Fails on a permissions error, as my credentials from the host are not forwarded.

**Comment by mpdehaan** [comment]
This very well may be a question about your vagrant configuration -- and the vagrant provisioner is maintained as part of vagrant.

If you can reproduce this without vagrant and doing forwarding, please let us know.

In the meantime, since this is in the "support" category let's move this over to a mailing list.
