### ISSUE TITLE
mysql modules do not get 'login_host' from ~/.my.cnf?

### ISSUE THREAD

**Issue by coreylane** [ansible/ansible#6761]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.5.3
##### Environment:

Running Ansible on Mac OSX Mavericks managing CentOS 6
##### Summary:

Hello,

It would be cool if the mysql_db and mysql_user modules read the `host` line from ~/.my.cnf similarly to how it currently reads `user` and `password`. This would prevent having to use the 'login_host' parameter when interacting with a remote database server.

Has this been discussed or mentioned before? 

```
[root@web01 ~]# cat ~/.my.cnf
# Ansible managed: ~/ansible-playbooks/magento/templates/root_.my.cnf.j2 modified on 2014-03-29 23:47:45 by ceddybu on MK423ZDRVG
# web01
[client]
user=root
password=test666
host=192.168.150.10
```
##### Expected Results:

The mysql module set login_host based on the ~/.my.cnf

**Comment by mpdehaan** [comment]
Sounds reasonable I guess, feel free to send along a pull request.  As this is not something we're actively going to work on, I'm going to close this ticket but feature additions would be welcomed.

**Comment by genofire** [comment]
I create a PR (after 4 years without a fix - i did not think anybody will do it)
