### ISSUE TITLE
python autoinstall

### ISSUE THREAD

**Issue by TheTesla** [ansible/ansible#67712]
##### SUMMARY

auto unstall the dependency python on remote

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ansible base

##### ADDITIONAL INFORMATION

On some linux distros python is not installed. Ansible cannot configure remotes not having python installes. Ansible should run:

apt update
apt install python

e. g. on ubuntu remotes to install the required dependencies.

```yaml

```

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. Unfortunately we have no plans to add such a feature.  We would recommend that you create a bootstrap playbook for your target OS, and use the `raw` or `script` modules to prepare your systems to be managed by Ansible

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
