### ISSUE TITLE
Allow ansible-galaxy to "git init" roles

### ISSUE THREAD

**Issue by chikamichi** [ansible/ansible#6773]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.6 (devel f82ac9f8e9) last updated 2014/03/22 17:11:12 (GMT +200)
##### Environment:

Linux **\* 3.5.0-47-generic #71-Ubuntu SMP Wed Feb 19 00:00:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
##### Summary:

I don't know where to provide feedback about `ansible-galaxy`, an issue might be inappropriate: feel free to move/remove.

When installing roles from the galaxy using `ansible-galaxy`, I often find myself willing to edit the roles (README typos, code kinks…). This requires manually setting a git tracking (`git init`, `git add remote upstream [github-url-as-seen-on-the-galaxy]`).

`ansible-galaxy` could be configured using an Ansible option (disabled by default) to do just that, so that contributing to the galaxy codebase is made even easier.

I guess the added origin should be named `upstream`, as illustrated by the [GitHub help page on the subject](https://help.github.com/articles/syncing-a-fork) so that people can easily fork (=> `git add remote origin git@github.com:me/fork`), edit, and send PR to the upstream.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
I'd consider pull requests for something like this.

**Comment by chikamichi** [comment]
Good to know. Thank you for your feedback!
