### ISSUE TITLE
ERROR: Failure: ImportError (No module named passlib.hash)

### ISSUE THREAD

**Issue by lc3t35** [ansible/ansible#6776]
##### Issue Type:

“Documentation Report”
##### Ansible Version:

ansible 1.6 (devel 51727e81ac) last updated 2014/03/31 16:47:56 (GMT +200)
##### Environment:

OS X 10.8.5
Python 2.7.2
##### Summary:

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.
##### Steps To Reproduce:

When i run "make tests" after cloning the source, i have the following error 

```
ERROR: Failure: ImportError (No module named passlib.hash)
```
##### Expected Results:

Tests pass
##### Actual Results:

ERROR: Failure: ImportError (No module named passlib.hash)

To have the tests pass from the source, you need to install passlib

```
pip install passlib
make tests
....
----------------------------------------------------------------------
Ran 146 tests in 8.115s
```

I suggest to modify in the documentation

```
sudo pip install paramiko PyYAML jinja2 httplib2 passlib
```

**Comment by mpdehaan** [comment]
Yep, agree we should tweak the docs about this.

**Comment by mpdehaan** [comment]
Added to testing/README.md.

Thanks!
