### ISSUE TITLE
[rax] it'd be nice if the module returned info about servers that are already running, in addition to info about the servers it starts

### ISSUE THREAD

**Issue by joshuaconner** [ansible/ansible#6778]
##### Issue Type:

Bug report 
##### Ansible Version:

ansible 1.6 (devel efba8b4771) last updated 2014/03/31 10:51:21 (GMT -700)
##### Environment:

Running from OSX 10.9
##### Summary:

Basically if you run the `rax` module with the `exact_count` option set to `yes`, the module will only return info about servers it has started. It would be nice if, in addition to that, it returned info about all of the matched servers, including ones that are already running.

That way, you can create in-memory host groups _a la_ https://github.com/ansible/ansible-examples/blob/master/language_features/eucalyptus-ec2.yml
##### Steps To Reproduce:

I've created a gist with a simple playbook and output from running said playbook here: https://gist.github.com/joshuaconner/dca192736971d74e80a8
##### Expected Results:

`rax` would return info about instances that are already running in addition to info about instances it has created.
##### Actual Results:

`rax` only returns info about instances it creates. See again the gist here:
https://gist.github.com/joshuaconner/dca192736971d74e80a8, Note that 
- in the first task, the length of the "instances" array is 1 (this is correct) 
- in the second task the "instances" array is empty (even though one instance in the group is running)
- in the third task the length of the "instances" array is 1 (even though **two** instances in the group are now running)

If you'd like, I'd be happy to either a) take this to the mailing list or b) put together a PR. Let me know, thanks!

**Comment by joshuaconner** [comment]
(cc @sivel, who I think has done most of the work on this module and was super helpful in helping me to get it working with our OpenStack install, though this particular issue isn't OpenStack-specific)

**Comment by sivel** [comment]
This will refactoring to work. Currently, existing servers don't get passed into the 'create' function, only a list of names of servers to create and the details required to create them.

Due to this only newly created instances are available.

I'll look into making these changes.  However, you might want to look into using the rax.py inventory script if you are not already using it.  The inventory script will query the API and return host groups based on the 'group' attribute you used during creation.

**Comment by bmcsheehy** [comment]
Speaking of the rax.py inventory script. It would be nice if the inventory script returned host data for systems in Gen1, NextGen / Perf Tier. As of now it appears to exclude anything in Gen1.

**Comment by joshuaconner** [comment]
@bmcsheehy Open an issue about it? :)

**Comment by bmcsheehy** [comment]
Will do :)

**Comment by mpdehaan** [comment]
It would be better if you can submit a pull request.

Hint, hint.

**Comment by joshuaconner** [comment]
As @sivel noted, it's a pretty significant refactor of the module to get it to show existing servers, and I didn't want to step on any toes. I'm happy to work on it if nobody's opposed!

**Comment by sivel** [comment]
I did work on this a little earlier today, I just didn't have time to post back.  Work thus far can be found at https://github.com/sivel/ansible/compare/rax-untouched

I'm a little on the fence about how things are handled when servers are deleted.  When you are adding more, it seems OK to include them in the `instances` key, but when deleting, it seems strange.

With the above branch, when you delete a server, `instances` would contain both the kept and the deleted servers, and really the only identifier is `rax_status`.

**Comment by joshuaconner** [comment]
That is awesome! 

One way to maybe get around the weirdness on delete would be to add some more keys to the `results` dict: for `running` and `stopped` instances or something? You seem to have a solid handle on it though.

**Comment by sivel** [comment]
I think the approach I am going to take is that `instances` will only contain servers that are:
1. successfully created during the run
2. servers matching the group
3. servers that were not just deleted

So when servers are deleted, they will not show up in `instances`, they will only be available via `success`, `timeout` or `error` in such a case.

There is also a slight behavior change with create, in that it will not include servers who entered an error state or timed out while waiting.  `instances` in this case will only include already created matching servers and servers just created successfully.

**Comment by Trozz** [comment]
Can this be closed as the PR from @sivel has been merged?

**Comment by sivel** [comment]
Yes, this can be closed.
