### ISSUE TITLE
[rax] rax.py inventory script not returning any Gen1 data

### ISSUE THREAD

**Issue by bmcsheehy** [ansible/ansible#6779]
##### Issue Type:

Feature Idea
##### Ansible Version:

1.5
##### Environment:

N/A
##### Summary:

It appears the rax.py inventory module excludes data for any systems that are hosted within the Gen1 cloud at Rackspace. For users who have systems deployed across different cloud tiers at rax (Gen1, NextGen, Perf), it precludes them from treating the rax.py inventory script response as the authoritative resource for all cloud servers hosted within rax. 

Is there any possibility of adding data for systems hosted in Gen1 to the output of rax.py?
##### Steps To Reproduce:

Deploy systems in Gen1, NextGen and or Perf and run the rax.py invetory script and compare the output with the systems you have deployed in Gen1 and NextGen/Perf. You will see that only the NextGen / Perf systems are returned in the output. 
##### Expected Results:

It would be ideal if the rax.py script returned a JSON object containing all systems hosted within RAX cloud.
##### Actual Results:

N/A

**Comment by sivel** [comment]
This is not something we will be working on.  First Gen, ultimately has an EOL in the not too distant future.  No currently maintained SDKs are designed to manage First Gen resources.

Additionally, all rax modules in ansible are designed to operate against OpenStack clouds, specifically in most cases the Rackspace Public Cloud Next Gen and performance tiers.

All scripts in the plugins directory of ansible are examples, so if this is something you are looking for, I'd recommend creating a local fork of rax.py that provides this functionality for you.

**Comment by bmcsheehy** [comment]
Thanks for that info. We'll fork / mod the inventory script to suit our needs. Thanks.
