### ISSUE TITLE
Add documentation to assist with determining where issues should go

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#67939]
##### SUMMARY

We are now in a new era of ansible/ansible maintenance, according to this timeline:

> **Where do I file issues against Ansible 2.10?**
> It depends on when you file the issue due to where we are in the migration process:
>     Before **2020-03-02**:
>         All issues: ansible/ansible project on GitHub
>     Between **2020-03-02 and 2020-03-23**: Please ask. The project repositories will be constantly changing
>     After **2020-03-23**:
>         ansible-base issues: ansible/ansible project on GitHub
>         Collections specific issues: ansible-collections/{namespace}.{collection} or in the partner owned GitHub repository

Source: https://groups.google.com/forum/#!msg/ansible-devel/oKqgCeYTs-M/cHrOgMw8CAAJ

It may be helpful—especially since there will be many people who have ignored and/or not seen the public postings at all—to have a docs page that helps people determine where they should file a given issue.

It should basically be an expansion of the above quoted text, and the most important thing (in my mind) would be some detailed note about _how to verify a bug or issue is related to ansible-base, or something else_.

E.g. right now if I run a playbook and it has a problem, the way I validate whether it's an ansible-base issue or something else is:

  1. `pip3 uninstall ansible`
  2. `pip3 install git+https://github.com/ansible-collection-migration/ansible-base`
  3. Run playbook again using this base version
  4. Determine if error still exists (and is not related to missing content)
  5. After finished, `pip3 uninstall ansible` then `pip3 install ansible` to get back to the full ACD version.

Now, this wouldn't necessarily be the best way to test for things in the future, but the general idea is we need a way for people to determine if their problem is related to:

  1. Local environment issues / things out of our control (e.g. support request, better to go elsewhere like ansible-project mailing list, Stack Exchange, IRC, etc.)
  2. A collection (point to collection project link from Galaxy page or I guess Automation Hub?)
  3. Ansible base (point to ansible/ansible repo).

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

Collection migration and post-migration tasks

##### ANSIBLE VERSION

N/A

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### ADDITIONAL INFORMATION

N/A

**Comment by geerlingguy** [comment]
Just noting that the [community guide](https://docs.ansible.com/ansible/latest/community/index.html) links to:

  - [Reporting a bug](https://docs.ansible.com/ansible/latest/community/reporting_bugs_and_features.html#reporting-bugs)
  - [Requesting a feature](https://docs.ansible.com/ansible/latest/community/reporting_bugs_and_features.html#requesting-a-feature)

That entire page ("Reporting Bugs And Requesting Features") probably needs to be rewritten in light of the collection migration.

**Comment by geerlingguy** [comment]
The docs page [Information for submitting a group of modules](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_in_groups.html#developing-modules-in-groups) probably also needs a full rewrite.

**Comment by samccann** [comment]
Triaged in #ansible-docs today.  Besides addressing the pages listed here that need updating, we will tell developers/users if they are in the docs and see a problem, use the link that will go back to the collection on Galaxy to find if there is an issue tracker listed.

**Comment by jctanner** [comment]
We are not considering this a blocker for 2.10 base release.

**Comment by samccann** [comment]
@jctanner similar question on this PR and what prompted the above comment of not being a blocker. This one as a P1 label, so wondering if that needs to be removed as well here so as not to mess up your tracking on ansible-base?

**Comment by jctanner** [comment]
@samccann nope not your fault. We had added it to our board and then decided otherwise after team discussion.

**Comment by acozine** [comment]
Partial fix in #70488.

**Comment by samccann** [comment]
@geerlingguy - a lot has changed since this ticket was opened.  Can you elaborate if there is more to do on this issue or if we can close it?

**Comment by geerlingguy** [comment]
@samccann - It looks like the [reporting bugs](https://docs.ansible.com/ansible/devel/community/reporting_bugs_and_features.html#reporting-bugs) and other docs are in a much better place today. Anything I'd find would be tiny changes that I don't think would need any kind of meta issue now.

I think we can close this out :)

**Comment by samccann** [comment]
great, thanks!
