### ISSUE TITLE
variable conflict with 'role_name' value

### ISSUE THREAD

**Issue by sean-abbott** [ansible/ansible#6800]
##### Issue Type:

Bug Report
##### Ansible Version:

1.4.5
1.5.3
##### Environment:

ubuntu 10.04, python 2.6.
Ansible installed via rquillo ppa
Ansible installed via git clone+hacking/setup.env
##### Summary:

double variable usage in play.py, with one clobbering the other
##### Steps To Reproduce:

Relevant roles here:
https://github.com/qkslvrwolf/ansible_roles
stack trace and error description here:  http://pastebin.com/Vi1ujErt
    snippet calling roles:

```
    ---
    - hosts: jenkins_slaves
      sudo: yes
      roles: 
        - { role: lunabuild_jenkins_slave_reference }
```
##### Expected Results:

The role will run
##### Actual Results:

```
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 269, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 169, in main
    play = ansible.playbook.Play(pb, play_ds, play_basedir)
  File "/home/seabbott/workspace/fresh_ansible_venv/lib/python2.6/site-packages/ansible/playbook/play.py", line 141, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/home/seabbott/workspace/fresh_ansible_venv/lib/python2.6/site-packages/ansible/playbook/play.py", line 550, in _load_tasks
    x['role_name'] = new_role
TypeError: 'str' object does not support item assignment
```

**Comment by mpdehaan** [comment]
Can you please share a minimal example?

It sounds like you defined a variable named 'role_name', in which case this is reserved, and you shouldn't do this.

I would agree it might be nice that there is a warning about reserved variables, and there's a ticket open about this one.

Let us know.

**Comment by sean-abbott** [comment]
In play.py (in versions 1.5.3 and 1.4.5):

In version 1.4.5:
430:  for x in tasks:
537:                  for x in data:

In version 1.5.3:
503:  for x in tasks:
590:                  for x in data:

The second x clobbers the first, as it is inside the loop.

This results in a TypeError, because the inner line attempts to reference x as a dictionary, but x has been assigned a a string key from data at that point.

I haven't quite been able to figure out what is being assigned where, yet

**Comment by sean-abbott** [comment]
Ok, I took a stab at making a fairly simple example.  You can create an inventory any test machine, and point this playbook at it.

https://github.com/qkslvrwolf/ansible_roles

You'll need ansible_error_test, level_1_role, level_2_role, and l2_includes_role.

Just change the role in the error.yml playbook depending on what you want to try.  The level_1_role works, the level_2_role gives you on error (that clearly demostrates that x was overridden incorrectly), and and l2_includes show what happens when you have both role dependency and includes in a task main.yml

There's another little oddity.  We have 
for x in tasks
  ...
  items = ['']
  ....
  for item in items:

And items is never referenced between it assigning to a list with a single empty string and being used in a for loop.

**Comment by jimi-c** [comment]
The above patch should fix this issue, and will be included in the next major release. If you continue to have any problems regarding this issue, please let us know.

Regarding the "for item in items" issue, it does appear that the loop will only ever execute once, so could probably be removed. If you'd like to open a separate issue for that, please feel free to do so.

Thanks!
