### ISSUE TITLE
sysctl module

### ISSUE THREAD

**Issue by jasonmader** [ansible/ansible#6806]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel 811553930a) last updated 2014/03/31 13:09:21 (GMT -400)
##### Environment:

SLES 11 SP 3
##### Summary:

Module sysctl makes incorrect changes to sysctl parameters. I've tested it with a single entry depicted below.
##### Steps To Reproduce:

```
tasks:
- sysctl: name=kernel.sysrq value=0
```

```
# Controls the System Request debugging functionality of the kernel
kernel.sysrq = 0
```
##### Expected Results:

```
TASK: [sysctl name=kernel.sysrq value=0] **************************************
ok: [master] => {"changed": false}
```
##### Actual Results:

```
PLAY [master] *****************************************************************

GATHERING FACTS ***************************************************************
ok: [master]

TASK: [sysctl name=kernel.sysrq value=0] **************************************
changed: [master] => {"changed": true}

PLAY RECAP ********************************************************************
master           : ok=2    changed=1    unreachable=0    failed=0
```

```
master # sysctl kernel.sysrq
kernel.sysrq = 1
```

**Comment by jimi-c** [comment]
Looks like 0e8c7b1c broke this.

**Comment by jimi-c** [comment]
The above patch should fix the issue for you, and will be included in the next major release. If you continue seeing problems related to this issue, or if you have any further questions, please let us know. Thanks!
