### ISSUE TITLE
rsync error going from Ubuntu < 14.04 to 14.04

### ISSUE THREAD

**Issue by simonjgreen** [ansible/ansible#6809]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

Ubuntu 12.04 and Ubuntu 14.04
##### Summary:

Synchronize module does not work going TO Ubuntu 14.04 from anything older than Ubuntu 14.04
##### Steps To Reproduce:

templates/dotfiles contains around 350 files. This does not reproduce when copying, say, 1 file.

simon@ubuntu:~/BuildTools/ansible$ ansible all -m synchronize -a "src=templates/dotfiles dest=/tmp/test" -i hosts/simonTest -u wirehive -k
SSH password:
wirehive@10.10.10.159's password:
10.10.10.159 | FAILED >> {
    "cmd": "rsync --delay-updates -FF --compress --timeout=10 --archive --rsh 'ssh  -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' templates/dotfiles wirehive@10.10.10.159:/tmp/test",
    "failed": true,
    "msg": "unknown message 0:0 [sender]\nrsync error: error in rsync protocol data stream (code 12) at io.c(441) [sender=3.0.9]\n",
    "rc": 12
}
##### Expected Results:

Should copy!
##### Actual Results:

rsync error: error in rsync protocol data stream (code 12) at io.c(441) [sender=3.0.9]

**Comment by mpdehaan** [comment]
See http://rsync.samba.org/issues.html and search for io.c

Ultimately I'm not sure this is our ticket since the system is calling out to rsync.

**Comment by shiinee** [comment]
I'm running into the same issue and the culprit seems to be the `--timeout=10` option added by Ansible.

**Run rsync command using playbook:**

```
$ ansible-playbook -vv systemd.yml
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
<10.252.105.160> REMOTE_MODULE setup
ok: [10.252.105.160]

TASK: [copy source files] *****************************************************
failed: [10.252.105.160] => {"cmd": "rsync --delay-updates -FF --compress --timeout=10 --archive --rsh 'ssh  -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' /Users/skyler/systemdtest/../le_codez/systemd/ root@10.252.105.160:/root/systemd/", "failed": true, "rc": 12}
msg: unknown message 0:0 [sender]
rsync error: error in rsync protocol data stream (code 12) at /SourceCache/rsync/rsync-42/rsync/io.c(306) [sender=2.6.9]


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/skyler/systemd.retry

10.252.105.160             : ok=1    changed=0    unreachable=0    failed=1
```

**Run rsync command manually:**

```
$ rsync --delay-updates -FF --compress --timeout=10 --archive --rsh 'ssh  -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' /Users/skyler/systemdtest/../le_codez/systemd/ root@10.252.105.160:/root/systemd/
unknown message 0:0 [sender]
rsync error: error in rsync protocol data stream (code 12) at /SourceCache/rsync/rsync-42/rsync/io.c(306) [sender=2.6.9]
```

**Run rsync command manually, without timeout option:**

```
$ rsync --delay-updates -FF --compress --archive --rsh 'ssh  -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' /Users/skyler/systemdtest/../le_codez/systemd/ root@10.252.105.160:/root/systemd/
$ #worked!
```

I can send a pull request to remove the timeout option.

**Comment by jimi-c** [comment]
The above pull request was merged, and should correct the above issue. If you continue seeing any problems related to this issue, or if you have any further questions please let us know. Thanks!
