### ISSUE TITLE
apt_key module page inconstancy.

### ISSUE THREAD

**Issue by mshenhera** [ansible/ansible#6813]
##### Issue Type:

“Documentation Report”
##### Ansible Version:

1.5.4 
##### Environment:

Ubuntu 12.04
##### Summary:

apt_key module page (http://docs.ansible.com/apt_key_module.html) refers to keyserver parameter. However it is not implemented in current stable branch (1.5.x). It would be great to notice on the page that such parameter was added in 1.6.
##### Steps To Reproduce:

Write apt_key module with keyserver parameter, for example
- name:  import the public GPG Key
  apt_key:
    id=XXXXXXXXX
    keyserver=http://keyserver.ubuntu.com
    state=present
##### Expected Results:

apt_key module page  points the version new parameter was added.
##### Actual Results:

Ansible returns error:
failed: [hostname] => {"failed": true, "item": ""}
msg: unsupported parameter for module: keyserver

**Comment by mpdehaan** [comment]
BTW, docs for Ansible are contained in the docsite directory of the source if you ever want to submit a pull request.  The source for the docs however is in the "library" directory, so hop into "library/packaging/apt_key" and you can add a "version_added" attribute.

If you don't want to do this though we can take care of it, just pointing it out in case you were interested in making other contributions to docs.

Thanks!

**Comment by mpdehaan** [comment]
Fixed, thanks!

**Comment by mpdehaan** [comment]
(Will appear in the next docs push)
