### ISSUE TITLE
win_certificate_store has no function to check for existing certificates or perform enrollments

### ISSUE THREAD

**Issue by dubblies** [ansible/ansible#68280]
##### SUMMARY
no "get" capabilities - I cannot query for existing certificates or see their data

##### ISSUE TYPE
Please finish out the functionality here and if possible adopt Powershell for the Test-Path functionality at minimum if not full get-certificate functionality for enrollment as well

##### COMPONENT NAME
win_certificate_store

**Comment by Akasurde** [comment]
Issue migrated to https://github.com/ansible-collections/ansible.windows/issues/33
