### ISSUE TITLE
Issue with host group union in inventory when using inventory directories

### ISSUE THREAD

**Issue by ggillies** [ansible/ansible#6834]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4
##### Environment:

Fedora 20 all updates
##### Summary:

When using an inventory directory that contains multiple files (or a script to generate a dynamic inventory) the ability to select hosts by the union of two host groups works inconsistently
##### Steps To Reproduce:

I have an inventory directory with four files

file1
file2
file3
file4

the contents of each file are

file1

```
[australia]
host1
```

file2

```
[australia]
host2
```

file3

```
[devel]
host2
```

file4

```
[devel]
host3

[america]
host3
```

But when I run some commands I get what I expect

```
$ ansible -i inventory -m setup --list-hosts 'all'
    host1
    host2
    host3

$ ansible -i inventory -m setup --list-hosts 'australia'
    host1
    host2

$ ansible -i inventory -m setup --list-hosts 'devel'
    host2
    host3

$ ansible -i inventory -m setup --list-hosts 'australia:america'
    host1
    host2
    host3
```

But the following command doesn't work (according to my understanding)

```
$ ansible -i inventory -m setup --list-hosts 'australia:&devel'
No hosts matched
```

But note the following works

```
$ ansible -i inventory -m setup --list-hosts 'america:&devel'
    host3
```

It seems like unless you put everything into the one file, host group union is inconsistent?
##### Expected Results:

Expected that the output would look like this

```
$ ansible -i inventory -m setup --list-hosts 'australia:&devel'
    host2
```
##### Actual Results:

Host2 is never returned as being a valid host for australia:&devel

```
$ ansible -i inventory -m setup --list-hosts 'australia:&devel'
No hosts matched
```

**Comment by mpdehaan** [comment]
So just to be clear --list-host doesn't take an option, Ansible normally is written as

ansible <hostname> -m module -a args [--flags]

Though this shouldn't change the question.

The problem above is that you are keeping things in different inventories -- file1, file2, file3, file4.

To select the different inventory file instead of "-i inventory", you need to do "-i file4" to select the america one, which is I bet why you are getting "no hosts matched"

Can you confirm?

**Comment by srgvg** [comment]
@mpdehaan I don't understand your logic saying
"The problem above is that you are keeping things in different inventories -- file1, file2, file3, file4."

This is a use case for `ansible.inventory.InventoryDir()`, so I see no reason why @ggillies should target a specific inventory file within that directory.

I tested @ggillies inventory myself, and got the same result for `australia:&devel`: "No hosts matched".

same with your suggestion:

```
$ ansible -i inventory/file4 --list-hosts 'australia:&devel'
No hosts matched
```

Now I tested this with my `inventorytree` patch #6379 (https://github.com/sergevanginderachter/ansible/tree/inventorytree):

```
$ ansible -i inventory --list-hosts 'australia:&devel'
    host2
```

Which gives the expected result :)

To give an idea of the inventory parsing, using my inventory tree script in both cases:
- latest ansible devel:

```
$ ansible-inventory --tree -i inventory/
[0] all 
|--[1] host1 
|--[1] host2 
|--[1] host2 
|--[1] host3 
|--[1] ungrouped 
|--[1] australia 
|  |--[2] host1 
|  |--[2] host1 
|  |--[2] host2 
|--[1] devel 
|  |--[2] host2 
|  |--[2] host2 
|  |--[2] host3 
|--[1] america 
|  |--[2] host3 
|  |--[2] host3 
```
- with my `inventorytree` patch:

```
$ ansible-inventory --tree -i inventory/
[0] all 
|--[1] ungrouped 
|--[1] australia 
|  |--[2] host1 
|  |--[2] host2 
|--[1] devel 
|  |--[2] host2 
|  |--[2] host3 
|--[1] america 
|  |--[2] host3 
```

(the number between brackets bing the group.depth)

**Comment by ggillies** [comment]
@mpdehaan thanks for taking a look. I understand --list-hosts takes no argument, but you still need to specify the host pattern to use ansible on, which is what the last argument is

```
Usage: ansible <host-pattern> [options]
```

As for your question, I'm a little confused, if I point it to specific files in the inventory directory, it works or doesn't work how I would expect, I understand that. My confusion is that I thought that if I pointed to an inventory that was a directory, all the files in that directory should essentially be merged together, though it doesn't look like this is the case

**Comment by mpdehaan** [comment]
Ah, inventory dirs.  This changes things.  Fair enough.

**Comment by srgvg** [comment]
Given that my patch was merged in the mean time, this should be an easy close now.

**Comment by bcoca** [comment]
tested and can confirm this now works
