### ISSUE TITLE
synchronize action should maybe force the connection for hosts named localhost (edited title)

### ISSUE THREAD

**Issue by jorgenschaefer** [ansible/ansible#6840]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel 317c2f4bc0) last updated 2014/04/03 12:41:29 (GMT +200)
##### Environment:

openSUSE 12.2 (x86_64)
##### Summary:

Using the synchronize action while deploying to a VM listening on localhost confuses ansible as it tries to unnecessarily delegate to localhost, and also forgets to clear the port.
##### Steps To Reproduce:

I'm running a simple playbook to deploy some software to a VM running on localhost:2222.

Inventory file:

```
[localvm]
localhost ansible_ssh_user=root ansible_ssh_port=2222
```

tasks/main.yml:

```
- name: Install via rsync
  synchronize: src=../pkg dest=/srv/pkg/
```

This fails because it tries to connect to 127.0.0.1:2222 with my current username. What is happening, apparently, is that it assumes I'm doing a delegate action and tries to connect to localhost with my current username, but retains the faulty port. There is no need to delegate at all.
##### Expected Results:

I'd assume it would simply run `rsync` locally, without delegation, to deploy to the VM.
##### Actual Results:

It fails because it tries to run an ssh connection to `<username>@127.0.0.1` port 2222, which does not work because `<username>` does not exist on the VM, and port 2222 is the VM. It would succeed on port 22, but that's not necessary.

The following change also makes the above work for me, so it is indeed some bogus delegation business. (The second hunk is only necessary because the first change removes the `conn.delegate` attribute.)

```
--- a/lib/ansible/runner/action_plugins/synchronize.py
+++ b/lib/ansible/runner/action_plugins/synchronize.py
@@ -81,7 +81,7 @@ class ActionModule(object):
         self.transport_overridden = False

         if inject.get('delegate_to') is None:
-            inject['delegate_to'] = '127.0.0.1'
+            # inject['delegate_to'] = '127.0.0.1'
             # IF original transport is not local, override transport and disable sudo.
             if self.original_transport != 'local':
                 inject['ansible_connection'] = 'local'
@@ -136,11 +136,11 @@ class ActionModule(object):

         # CHECK DELEGATE HOST INFO
         use_delegate = False
-        if conn.delegate != conn.host:
-            if 'hostvars' in inject:
-                if conn.delegate in inject['hostvars'] and self.original_transport != 'local':
-                    # use a delegate host instead of localhost
-                    use_delegate = True
+        # if conn.delegate != conn.host:
+        #     if 'hostvars' in inject:
+        #         if conn.delegate in inject['hostvars'] and self.original_transport != 'local':
+        #             # use a delegate host instead of localhost
+        #             use_delegate = True

         # COMPARE DELEGATE, HOST AND TRANSPORT
         process_args = False
```

**Comment by mpdehaan** [comment]
Thanks this is an interesting case.

In this case localhost isn't implicitly managed by a local connection and you have told it that the way to reach localhost is 2222.

Sounds like you might be using Vagrant, BTW, which often can be confusing with synchronize due to the way Vagrant works.   Shelling out to local_action: rsync ... can often be easier.   Usually with Vagrant inventory I would expect it to have generated some host aliases that weren't in there with localhost and port 2222 more like:

my_vm ansible_ssh_host=127.0.0.1 ansible_ssh_port=22222

In which case you could still define localhost seperately and wouldn't have this problem (basically where Ansible is doing what you ask it, but it's non-intuitive)

Anyway, the solution here is this:

localhost ansible_ssh_user=root ansible_ssh_port=2222 ansible_connection=local

OR

to define the VM seperately, with a different alias
- hosts:  myvms
  tasks:
  - synchronize: ....

(In which case, you don't even need to bother defining localhost in inventory at all)

Because we don't infer any magic about the hostname, if it's explicitly in the inventory file.

Removing the code you suggested will break some other things in ungood ways, and while this may seem a bit complex, it can't really do artificial intelligence on how you are using it, so it's making a best attempt.

We should definitely not comment out those lines of code above, but we might want to consider assuming 'localhost' means '-c local' only for the synchronize module, and nowhere else.

Leaving this open so we can take a look.

**Comment by jorgenschaefer** [comment]
Just to clarify: I did not mean to suggest commenting out this piece of code, it was just an attempt to show what makes the problem go away to make it easier to identify. Sorry for being unclear.

I am not using vagrant, but a qemu setup using some self-written scripts.

Using a different alias and setting `ansible_ssh_host` does work, though. Thank you!

The second suggested solution using `ansible_connection=local` does not work, because it then tries to access the host machine for other tasks instead of executing them on the VM. The workaround I posted only works because it changes the connection type to local for the rsync command only, not for other possible actions.

I'm a bit confused as to what it is trying to be smart about (I haven't used delegation at all), so I can't really comment on a sensible way to treat this problem. Maybe adding a caveat in the inventory file documentation about using localhost for local VMs would be enough?

**Comment by mpdehaan** [comment]
Most people using VMs would be connecting to them on their bridged or NAT'd address versus localhost and a port, so I don't think this is appropriate for a docs thing.

We'll take a look regardless.

**Comment by jctanner** [comment]
@jorgenschaefer "set_remote_user" has also been added as a parameter to the synchronize module. This should give you the ability to prevent the user@ prefix on the remote url.

**Comment by jorgenschaefer** [comment]
@jctanner, this is not related to the remote URL at all (I think that one's actually completely correct).

The synchronize action in my scenario figures it needs to execute rsync using delegation, so instead of simply running `rsync …`, it tries to ssh to localhost so it can run the rsync there. The ssh there fails, so rsync is not even run.

**Comment by jctanner** [comment]
@jorgenschaefer I think I need to see the ansible-playbook -vvvv output for the task.

Also, did you write the inventory by hand or is it the one vagrant generated?

**Comment by jorgenschaefer** [comment]
> @jorgenschaefer I think I need to see the ansible-playbook -vvvv output for the task.

I created a minimal reproduction setup. Doesn't even need a VM, just an sshd on localhost that listens on two ports. For this case, I allowed root logins to my local host and opened both ports 22 and 2222. (You just need an ssh with two ports on localhost and run ansible as a different user than the configure `ansible_ssh_user`.)

```
$ cat inventory 
[localvm]
localhost ansible_ssh_user=root ansible_ssh_port=2222
$ cat playbook.yml 
- hosts: localvm
  tasks:
  - name: Install via rsync
    synchronize: src=. dest=/tmp/test/
```

After this, the following output happens:

```
$ ansible-playbook -vvvv -i inventory playbook.yml -k
SSH password: 

PLAY [localvm] **************************************************************** 

GATHERING FACTS *************************************************************** 
<localhost> ESTABLISH CONNECTION FOR USER: root
<localhost> REMOTE_MODULE setup
<localhost> EXEC ['sshpass', '-d4', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/forcer/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=2222', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'localhost', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1397234895.86-75214523191902 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1397234895.86-75214523191902 && echo $HOME/.ansible/tmp/ansible-tmp-1397234895.86-75214523191902'"]
<localhost> PUT /home/forcer/tmp/tmpWDSlVS TO /root/.ansible/tmp/ansible-tmp-1397234895.86-75214523191902/setup
<localhost> EXEC ['sshpass', '-d4', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/forcer/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=2222', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'localhost', "/bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1397234895.86-75214523191902/setup; rm -rf /root/.ansible/tmp/ansible-tmp-1397234895.86-75214523191902/ >/dev/null 2>&1'"]
ok: [localhost]

TASK: [Install via rsync] ***************************************************** 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: forcer
<127.0.0.1> EXEC ['sshpass', '-d7', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/forcer/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=2222', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'ConnectTimeout=10', '127.0.0.1', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1397234897.77-241860681517484 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1397234897.77-241860681517484 && echo $HOME/.ansible/tmp/ansible-tmp-1397234897.77-241860681517484'"]
fatal: [localhost] => Authentication failure.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/forcer/playbook.retry

localhost                  : ok=1    changed=0    unreachable=1    failed=0   
```

As you can see, ansible try to ssh to forcer@localhost ("ESTABLISH CONNECTION FOR USER: forcer", where "forcer" is my username). It should not do that. It can just run rsync, it does not need to ssh to localhost first. _Additionally_, it gets confused about the port.

Changing the inventory to rename the host works:

```
$ cat inventory 
[localvm]
loc ansible_ssh_user=root ansible_ssh_port=2222 ansible_ssh_host=localhost
```

```
$ ansible-playbook -vvvv -i inventory playbook.yml -k
SSH password: 

PLAY [localvm] **************************************************************** 

GATHERING FACTS *************************************************************** 
<localhost> ESTABLISH CONNECTION FOR USER: root
<localhost> REMOTE_MODULE setup
<localhost> EXEC ['sshpass', '-d4', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/forcer/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=2222', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'localhost', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1397235054.88-208157418558348 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1397235054.88-208157418558348 && echo $HOME/.ansible/tmp/ansible-tmp-1397235054.88-208157418558348'"]
<localhost> PUT /home/forcer/tmp/tmpn3Rs7a TO /root/.ansible/tmp/ansible-tmp-1397235054.88-208157418558348/setup
<localhost> EXEC ['sshpass', '-d4', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/forcer/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=2222', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'localhost', "/bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1397235054.88-208157418558348/setup; rm -rf /root/.ansible/tmp/ansible-tmp-1397235054.88-208157418558348/ >/dev/null 2>&1'"]
ok: [loc]

TASK: [Install via rsync] ***************************************************** 
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1397235056.76-128224693423130 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1397235056.76-128224693423130 && echo $HOME/.ansible/tmp/ansible-tmp-1397235056.76-128224693423130']
<127.0.0.1> PUT /home/forcer/tmp/tmpMSK1Hh TO /home/forcer/.ansible/tmp/ansible-tmp-1397235056.76-128224693423130/synchronize
<127.0.0.1> EXEC ['/bin/sh', '-c', '/home/forcer/.virtualenvs/ansible/bin/python /home/forcer/.ansible/tmp/ansible-tmp-1397235056.76-128224693423130/synchronize; rm -rf /home/forcer/.ansible/tmp/ansible-tmp-1397235056.76-128224693423130/ >/dev/null 2>&1']
root@localhost's password: 
changed: [loc] => {"changed": true, "cmd": "rsync --delay-updates -FF --compress --timeout=10 --archive --rsh 'ssh  -o StrictHostKeyChecking=no -o Port=2222' --out-format='<<CHANGED>>%i %n%L' /home/forcer/Projects/ansible-6840/. root@localhost:/tmp/test/", "msg": "cd+++++++++ ./\n<f+++++++++ inventory\n<f+++++++++ playbook.yml\n", "rc": 0, "stdout_lines": ["cd+++++++++ ./", "<f+++++++++ inventory", "<f+++++++++ playbook.yml"]}

PLAY RECAP ******************************************************************** 
loc                        : ok=2    changed=1    unreachable=0    failed=0   
```

In this case, ansible does not try to "ESTABLISH CONNECTION FOR USER: forcer", it just does "EXEC". Which is what I expected.

> Also, did you write the inventory by hand or is it the one vagrant generated?

I am not using vagrant. I wrote this inventory file by hand.

**Comment by jctanner** [comment]
@jorgenschaefer thanks, I think that clears it up for me and I have reproduced. Let me see if i can manipulate the action plugin to handle this situation without breaking other usecases.

**Comment by jctanner** [comment]
@jorgenschaefer this patch seems to be working for me without breaking existing tests ...

```
diff --git a/lib/ansible/runner/action_plugins/synchronize.py b/lib/ansible/runner/action_plugins/synchronize.py
index 6333176..2b3f318 100644
--- a/lib/ansible/runner/action_plugins/synchronize.py
+++ b/lib/ansible/runner/action_plugins/synchronize.py
@@ -80,13 +80,11 @@ class ActionModule(object):
         self.original_sudo = self.runner.sudo
         self.transport_overridden = False

-        if inject.get('delegate_to') is None:
-            inject['delegate_to'] = '127.0.0.1'
-            # IF original transport is not local, override transport and disable sudo.
-            if self.original_transport != 'local':
-                inject['ansible_connection'] = 'local'
-                self.transport_overridden = True
-                self.runner.sudo = False
+        # abide by delegates and override non-local connections                    
+        if inject.get('delegate_to') is None and self.original_transport != 'local':
+            inject['ansible_connection'] = 'local'
+            self.transport_overridden = True
+            self.runner.sudo = False

     def run(self, conn, tmp, module_name, module_args,
         inject, complex_args=None, **kwargs):
@@ -136,11 +134,13 @@ class ActionModule(object):

         # CHECK DELEGATE HOST INFO
         use_delegate = False
-        if conn.delegate != conn.host:
-            if 'hostvars' in inject:
-                if conn.delegate in inject['hostvars'] and self.original_transport != 'local':
-                    # use a delegate host instead of localhost
-                    use_delegate = True
+        #import epdb; epdb.st()
+        if hasattr(conn, 'delegate'):
+            if conn.delegate != conn.host:
+                if 'hostvars' in inject:
+                    if conn.delegate in inject['hostvars'] and self.original_transport != 'local':
+                        # use a delegate host instead of localhost
+                        use_delegate = True

         # COMPARE DELEGATE, HOST AND TRANSPORT                             
         process_args = False
```

I will have to change the assertion that delegate was set in the synchronize unit tests, but that should be fine. 

Please try this patch on your machine and let me know if I've fixed the right issue.

**Comment by jorgenschaefer** [comment]
This indeed fixes the problem for me. Thank you!

And sorry for not providing a good test case with output right away … I should know better! :-D

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
