### ISSUE TITLE
Support for non-standard known_hosts file in network_cli

### ISSUE THREAD

**Issue by cisco-abrandel** [ansible/ansible#68413]
##### SUMMARY
Would be nice to be able to specify where to look for an additional known_hosts file for the network_cli connection module. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

network_cli

##### ADDITIONAL INFORMATION

Lets say I am using Jenkins to automatically deploy changes to the network, and this is all handled via a 
Jenkinsfile checked into source control, along with a known_hosts file also checked into source control. It would be nice you could specify a custom location to check for additional known_hosts entries, such that I could point to the file kept in the source control repo.

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible.

The `network_cli` connection plugin is now being maintained in the `ansible.netcommon` collection. The GitHub repository for this new collection can be found at https://github.com/ansible-collections/netcommon

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
