### ISSUE TITLE
ERROR! couldn't resolve module/action 'sysctl'

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#68416]
#67460 ### SUMMARY
ERROR! couldn't resolve module/action 'sysctl'. This often indicates a misspelling, missing collection, or incorrect module path.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
sysctl.py 

##### ANSIBLE VERSION

```paste below
ansible --version
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
ansible 2.10.0.dev0
  config file = /Users/tanner/projects/py3-ansible/src/playbooks.git/real-time.com-NEW/ansible.cfg
  configured module search path = ['/Users/tanner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/py3-ansible/src/ansible/lib/ansible
  executable location = /Users/tanner/projects/py3-ansible/src/ansible/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:03) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### CONFIGURATION
```paste below
$ ansible-config dump --only-changed
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
```

##### OS / ENVIRONMENT
management host macOS 10.14.6

##### STEPS TO REPRODUCE

```yaml
- name: tweaks to sysctl.conf
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  loop: "{{ query('dict', sysctl_conf) }}"
  when:
    - sysctl_conf is defined
    - sysctl_conf != ""
```

##### EXPECTED RESULTS
Task would run successfully

##### ACTUAL RESULTS

```paste below
ERROR! couldn't resolve module/action 'sysctl'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/Users/tanner/projects/py3-ansible/src/playbooks.git/roles/bootstrap/tasks/main.yml': line 122, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: tweaks to sysctl.conf
  ^ here
```
Looking at the stable-2.9 branch I find system module sysctl.py at `https://github.com/ansible/ansible/blob/stable-2.9/lib/ansible/modules/system/sysctl.py`

But the recent rebase I just pulled seems to have lost(?) this module?

My local pull
```
$ find . -name "*sysctl*"
./lib/ansible/module_utils/facts/__pycache__/sysctl.cpython-37.pyc
./lib/ansible/module_utils/facts/virtual/__pycache__/sysctl.cpython-37.pyc
./lib/ansible/module_utils/facts/virtual/sysctl.py
./lib/ansible/module_utils/facts/sysctl.py
```
Even trying to find the file on the devel branch via github `https://github.com/ansible/ansible/find/devel` fails

<img width="429" alt="File_Finder_·_GitHub" src="https://user-images.githubusercontent.com/6723257/77363965-a2bf0f00-6d21-11ea-92ed-f225a413dd34.png">

https://docs.ansible.com/ansible/latest/modules/sysctl_module.html says it's [stableinterface] and I didn't read anything says it was changing.

**Comment by sivel** [comment]
The following post to ansible-project is probably a worthwhile read:

https://groups.google.com/d/msg/ansible-project/eXsoOKEd0Mk/XTgbnPWbCAAJ

As well as this one from today to ansible-devel:

https://groups.google.com/d/msg/ansible-devel/RQ2d7htGwo0/SM7xA4T4AwAJ

The TL;DR is that as of today, we have moved 95% of all modules and plugins from this repository and into their own smaller collection repositories.  That module moved to https://github.com/ansible-collections/ansible.posix

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
