### ISSUE TITLE
Issue with printing unicode characters

### ISSUE THREAD

**Issue by alozovskoy** [ansible/ansible#6842]
##### Summary:

Ansible doesn't print non-english characters
##### Steps To Reproduce:

```
ansible@localhost:~$ ansible local -a "echo Тест"
localhost | success | rc=0 >>


ansible@localhost:~$ ansible local -a "echo Ϧ"
localhost | success | rc=0 >>


ansible@localhost:~$ ansible local -a "echo Test"
localhost | success | rc=0 >>
Test

ansible@localhost:~$ ansible local -a "echo Д_Test"
localhost | success | rc=0 >>


ansible@localhost:~$ 
```
##### Expected Results:

No one characters is print on stdout.
##### Actual Results:

I want to seen results of echo commands. Print this symbols in my host worked well.

```
ansible@localhost:~$ echo Тест
Тест
ansible@localhost:~$ echo Ϧ
Ϧ
ansible@localhost:~$ echo Д_Test
Д_Test
ansible@localhost:~$
```

**Comment by jimi-c** [comment]
The above commit should resolve the issue for you, and will be included in the next major release. If you continue seeing any problems related to this issue, or if you have any further questions, please let us know. Thanks!

**Comment by alozovskoy** [comment]
Thanks a lot, it works very well (i used dev branch)!!

```
ansible@localhost:~$ ansible local -a "echo Д_Test"
localhost | success | rc=0 >>
Д_Test

ansible@localhost:~$ ansible local -a "echo Ϧ"
localhost | success | rc=0 >>
Ϧ

ansible@localhost:~$ 
```
