### ISSUE TITLE
Recent cron documentation commit contradicts implementation

### ISSUE THREAD

**Issue by dirtyharrycallahan** [ansible/ansible#6844]
##### Issue Type:

Bug Report
##### Ansible Version:

development
##### Environment:

N/A
##### Summary:

commit 79c245f31f49a181067fc74eb1195ed76a3bf3f0 a cron documentation change appears to be incorrect.  It does not look like name is required by the module.
##### Steps To Reproduce:

code review
##### Expected Results:

documentation matches implementation
##### Actual Results:

documentation does not match implementation

**Comment by mpdehaan** [comment]
You're right, someone didn't notice the last example in EXAMPLES.

Fixed it, and will appear in next docs push correct.

Thanks!
