### ISSUE TITLE
Role deduplication and dependencies

### ISSUE THREAD

**Issue by jbguerraz** [ansible/ansible#68463]
##### SUMMARY
When a role is excluded due to deduplication, its dependencies are still executed when they're  set as `allow_duplicates`.

dependency graph: http://tiny.cc/qydwlz
playbook run gist: https://gist.github.com/jbguerraz/7165cce6b39ea05798486ba545139f3c

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
roles

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = None
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib64/python3.6/site-packages/ansible
  executable location = /usr/lib/python-exec/python3.6/ansible
  python version = 3.6.9 (default, Nov  4 2019, 05:05:26) [GCC 8.2.0]
```

##### CONFIGURATION

```paste below
None
```

##### OS / ENVIRONMENT

Linux (Gentoo)

##### STEPS TO REPRODUCE

run https://github.com/jbguerraz/ansibledependencies/dependencies

```yaml
git clone https://github.com/jbguerraz/ansibledependencies
cd ansibledependencies/dependencies
ansible-playbook playbook.yaml
```

##### EXPECTED RESULTS

`library-1` dependencies won't be executed multpile times

##### ACTUAL RESULTS

`library-1` dependencies are executed multpile times

**Comment by jbguerraz** [comment]
actually the `allow_duplicates: true` is used because the variable used as value of the dependency variable isn't substituted prior to comparison for deduplication logic ( cf https://github.com/jbguerraz/ansibledependencies/blob/master/roles/job-builder/meta/main.yaml#L2 ); which maybe worth a distinct issue ?

**Comment by sivel** [comment]
`allow_duplicates: true` explicitly states that the role can be executed multiple times ignoring deduplication.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
