### ISSUE TITLE
vmware_guest_find slow

### ISSUE THREAD

**Issue by markatdxb** [ansible/ansible#68484]
##### SUMMARY

running vmware_guest_find takes extensive long time - in out environment with 4000+ VMs it takes around 7 minutes to get the results. Running for example PowerCLI query takes a second to get the result. Is there any way to improve the performance of this module for large environments?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vmware_guest_find

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by sky-joker** [comment]
Hi @markatdxb

Thank you for this reporting!  
The Ansible VMware modules have moved into Collections.  
Could you please re-create this issue the following repo.

https://github.com/ansible-collections/vmware

**Comment by Akasurde** [comment]
Issue migrated to https://github.com/ansible-collections/vmware/issues/77
