### ISSUE TITLE
ansible-playbook: /usr/bin/python: can't open file No such file or directory (needs info)

### ISSUE THREAD

**Issue by chernesk** [ansible/ansible#6851]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible v1.5.4., but on my host machine, I tested with 1.3, 1.4 and 1.5
##### Environment:

Running from Mac OS Mavericks, but have also tried it on Ubuntu 12.04LTS

Managing: Ubuntu 12.04LTS
##### Summary:

I am manging about six hosts with the same playbook. I'm using the "best practices"layout. Four of the six hosts are just fine and everything runs great. Two hosts exhibit the same issue, noted below:

```
GATHERING FACTS ***************************************************************
REMOTE_MODULE setup CHECKMODE=True
failed: [host] => {"failed": true, "parsed": false}
invalid output was: /usr/bin/python: can't open file '/home/username/.ansible/tmp/ansible-tmp-1396553083.73-60097722574226/setup': [Errno 2] No such file or directory
```

I run the exact name ansible-playbook command on the servers that work and the servers that don't:

ansible-playbook -i servers/server-group -u myusername site.yml -vv -K
##### Steps To Reproduce:

I run this command:

```
ansible-playbook -i servers/server-group -u myusername site.yml -vv -K
```

against two servers (individually), and I run the same command with a different inventory file against others, and it works just fine.
##### Expected Results:

All hosts should behave the same way.
##### Actual Results:

All hosts were initially built with the same playbook. Working back through the hosts updating some items in the playbook and two hosts fail now.

**Comment by mpdehaan** [comment]
This sounds like a permissions problem on your remote host or they don't have a configured homedir rather than a bug to me.  This is going to take some debugging on your end, but you should fiddle with remote temp paths and look around.

I assume you had the same problem with previous versions?

**Comment by chernesk** [comment]
I'll do that. I've looked at permissions, but I'll mess around with the remote temp paths.

Yes, I went back and installed 1.3, up through devel and it's the same problem. Just didn't know where to start because the .ansible directory is there and accessible and writeable by the user, but was getting this on two hosts only.

The unconfigured homedir sounds like a good place to start. 

Thank you! Appreciate your input!

**Comment by chernesk** [comment]
Thanks for taking the time to discuss this with me, Michael. 

Turns out my issue was AppArmor related for some of the policies we have. After changing users and having no luck, I changed the user to something totally different and unique and then searched across all of our logs and saw the denial.

Again, appreciate your time.

**Comment by raushan-0822** [comment]
Run this command. It will start working 
sudo ln -sf /usr/local/bin/ansible /usr/bin/ansible

**Comment by Chepkeitany** [comment]
@raushan-0822 I get an error `ln: /usr/bin/ansible: Operation not permitted`
