### ISSUE TITLE
[Ansible : 1.5.3] - notify list of handlers as variables

### ISSUE THREAD

**Issue by sebastienalbert** [ansible/ansible#6853]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3 (release1.5.3 157b783521) last updated 2014/03/27 15:54:18 (GMT +200)
##### Environment:

CentOS 6
##### Summary:

When I initialize a variable of type list "tmcAdmin_Update_Notify" ansible the action that triggers the notification causes an error: 

ERROR: change handler (['handler_1', 'handler_2']) is not defined 

What is the syntax to set a variable as the one below in the notify: 
my_var: 
   - handler_1 
   - handler_2
##### Steps To Reproduce:

ansible-playbook -i hosts --limit=bt1sssbg site.yml -t tmcAdmin --verbose
## site.yml file :
- hosts: testbedUH
  
  vars:
  tmcAdmin_Update_Notify:
  - handler_1
  - handler_2
  
  tasks:
  - include: tmcAdmin.yml
    tags: tmcAdmin
  
  handlers:
  - name: handler_1
    action: shell echo "handler_1"
    tags: tmcAdmin
  - name: handler_2
    action: shell echo "handler_2"
    tags: tmcAdmin
## tmcAdmin.yml
# Actions :
- name: Besoin mettre a jour composant TMC_ADMIN
  action: bytel-installer name=TMC_ADMIN version={{ TMC_ADMIN_version }} state=updated path={{ ansibleTemp_path }} args="-t {{ tomcatVersion }}"
  notify: $tmcAdmin_Update_Notify
##### Expected Results:

No error :)
##### Actual Results:

ERROR: change handler (['handler_1', 'handler_2']) is not defined

**Comment by sivel** [comment]
Duplicate of #6755

**Comment by sebastienalbert** [comment]
It's great
