### ISSUE TITLE
Multiline-string malformation in processesed task.args

### ISSUE THREAD

**Issue by weshouman** [ansible/ansible#68643]
##### SUMMARY
Multiline-string malformation upon use of variables

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Any custom module

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/project/venv/lib/python3.5/site-packages/ansible
  executable location = /home/user/project/venv/bin/ansible
  python version = 3.5.2 (default, Oct  8 2019, 13:06:37) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/home/user/.ansible/roles']
```

##### OS / ENVIRONMENT

Ubuntu 16.04
Expected to affect any environment

##### STEPS TO REPRODUCE

```tasks/main.yml```
```yaml
    - name: Issue
      sample_module:
        custom_arg: >-
          [
            {
              "arg1": true,
            },
            {
              "arg2": "{{ sample_module_var }}"
            }
          ]
```
```vars/main.yml```
```yaml
sample_module_var: surprise
```
```action_/main.yml```
```python
# -*- coding: utf-8 -*-

from ansible.plugins.action import ActionBase

class ActionModule(ActionBase):

    def run(self, tmp=None, task_vars=None):
        if task_vars is None:
            task_vars = dict()

        result = super(ActionModule, self).run(tmp, task_vars)
        del tmp  # tmp no longer has any effect

        print(self._task.args)
        if ("custom_arg") in self._task.args:
            custom_arg = self._task.args["custom_arg"]
            print(custom_arg)
            # shows a list instead of a string
            # and in a more complex scenario, using another action_plugin, namely ansible-synology-dsm, it shows a list instead of an ansible.parsing.yaml.objects.AnsibleUnicode
            print(type(custom_arg))

        result['failed'] = False

        return result
```

Important Note: using ```{{ sample_module_var }}``` instead of ```"{{ sample_module_var }}"```or even using a normal variable inside double quotes we get the string type but it is syntactically incorrect for the application to remove the double quotation.

##### EXPECTED RESULTS

To receive, inside the sample_module, the following ```self._task.args``` 
```
{'custom_arg': '[\n  {\n    "arg1": true,\n  },\n  {\n    "arg2": "surprise"\n  }\n]'}
```
##### ACTUAL RESULTS

We receive, inside the sample_module, the following ```self._task.args``` 
```
{'custom_arg': [{'arg1': True}, {'arg2': 'surprise'}]}
```
And upon removing the double quotes as tested above we get the following ```self._task.args```
```
{'custom_arg': '[\n  {\n    "arg1": true,\n  },\n  {\n    "arg2": surprise\n  }\n]'}
```

##### Exact Location of failure
```/home/user/project/venv/lib/python3.5/site-packages/ansible/template/__init__.py```: def template(): ~550
Most probably it's in the recursive call at ```result = self.do_template(``` ~603

**Comment by sivel** [comment]
This behavior while unexpected by users, is expected due to historic behavior that cannot be changed.  It is explained in https://github.com/ansible/ansible/issues/34595#issuecomment-356091161

Ultimately `custom_args` will be transformed into a python literal, if it must be templated.

**Comment by sivel** [comment]
There is no way to ensure that ansible won't munge the value with the way you are building your module.  There are a few options:

1. Don't rely on the output format to match the input format. Detect if it is a string, or a `list`/`dict`. If it is a `list`/`dict`, use `json.dumps` to turn it back into a string. But again, the input format, and the output format may differ
1. Don't supply data that looks like python literals via argument value. Use a path to a template file as the value, that can then be templated, read into a variable, and used, instead of templating directly in the playbook. Any templating that occurs directly in the playbook, that results in a value that resembles a python literal, will be converted to a python literal if possible.

**Comment by weshouman** [comment]
Here are 2 workarounds in case someone hits the same issue

### Static Workaround
Use this one to transform the specific custom_arg into string instead of a python literal
```
import json
...
class ActionModule(ActionBase):

    def run(self, tmp=None, task_vars=None):
...
        if ("custom_arg") in self._task.args:
            custom_arg = self._task.args["custom_arg"]
            if (isinstance(custom_arg, dict)):
                json_str = json.dumps(custom_arg)
                self._task.args["custom_arg"] = json_str

```

### Generic Workaround
Use this one to change all dictionaries into strings
```
import json
...
...
class ActionModule(ActionBase):

    def run(self, tmp=None, task_vars=None):
...
        self._task.args = stringify(self._task.args)
...
def stringify(keystore):
    for key in keystore:
        elem = keystore[key]
        if (isinstance(elem, dict)):
            stringified = stringify(elem)
            json_str = json.dumps(stringified)
            keystore[key] = json_str
            return keystore
        else:
            print("elem: " + str(elem))
            return elem

```

**Comment by sivel** [comment]
Closing per above.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
