### ISSUE TITLE
Add option to wipe authorized_keys before adding to it

### ISSUE THREAD

**Issue by alimony** [ansible/ansible#6868]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.6 (devel 264b58f3ef) last updated 2014/04/05 23:36:30 (GMT +200)
##### Environment:

N/A
##### Summary:

It would be nice with an option in the `authorized_key` module to exclude everything from the `authorized_keys` file except what has been specified as `state=present` in the task. The use case is that you give access to a bunch of users, but then want to revoke access for one user in that bunch, meaning the key should be removed from all hosts. This needs to happen in one operation, or everyone will be locked out. Which is why this can't be done in a separate task beforehand.

My solution for now is to keep two folders of keys, one with enabled keys and one with disabled ones. The first folder is used in one task with `state=present`, while the other one is in a similar task but with `state=absent`. When someone should be removed, I just move their key from one folder to the other and run the task again.
##### Steps To Reproduce:

Specifying an option along the lines of `truncate_first=True` would empty the file before adding keys to it, if and only if, `state=present` is specified.
##### Expected Results:

An `authorized_keys` file on the host with all specified keys in it, but nothing else.
##### Actual Results:

Any keys that should be removed must explicitly be specified through `state=absent`.

**Comment by mpdehaan** [comment]
Ansible doesn't keep track of what resources are in the file or are not, because of the way it works.

Thus, if you want to do this I highly recommend just keeping the authorized keys file in the repo and using the "copy" commmand to place it.

Stop by the user's list if you would like to discuss more.

Thanks!
