### ISSUE TITLE
ini_file module changes all option names to lower case

### ISSUE THREAD

**Issue by andreasf** [ansible/ansible#6875]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3, same in HEAD
##### Environment:

N/A
##### Summary:

ConfigParser by default changes all option names to lower case. This can make the ini file invalid for case-sensitive applications, e.g. XDG .desktop files.

While ConfigParser seems to be a bad choice for ini_file in general (see other issues) and probably should be swapped out at some point, this issue can be fixed easily by overriding ConfigParser.optionxform.
##### Steps To Reproduce:
1. use ini_file to change an option of a XDG .desktop file, e.g.
   `ini_file: dest=/usr/share/applications/google-chrome.desktop section="Desktop Entry" \
   option="Exec" value="/usr/bin/google-chrome-unstable --incognito %U`
2. observe that all option names were changed to lower case
##### Expected Results:

Only the given option should be changed
##### Actual Results:

All option names are changed to lower case, possibly rendering the file invalid

**Comment by relaxnow** [comment]
Still experiencing this in 1.6.3, I think the wrong commit was merged?
