### ISSUE TITLE
sanity test with docker exiting abruptly if tests dir is not present in collections

### ISSUE THREAD

**Issue by anshulbehl** [ansible/ansible#68819]
##### SUMMARY

tar: /home/abehl/.ansible/collections/ansible_collections/opensvc/cluster/tests: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
ERROR: Command "tar oxzf /tmp/ansible-result-YfvJZN.tgz -C /home/abehl/.ansible/collections/ansible_collections/opensvc/cluster/tests" returned exit status 2.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible-test

##### ANSIBLE VERSION

```paste below
ansible 2.9.6.post0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/abehl/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/abehl/work/src/anshul_ansible/new_ansible/ansible/lib/ansible
  executable location = /home/abehl/work/src/anshul_ansible/new_ansible/ansible/bin/ansible
  python version = 2.7.17 (default, Oct 21 2019, 17:20:57) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Fedora release 30 (Thirty)

##### STEPS TO REPRODUCE

Run `ansible-test sanity --docker` on a collection without tests/ dir

```yaml

```

##### EXPECTED RESULTS

Should not exit abruptly

##### ACTUAL RESULTS

```paste below
tar: /home/abehl/.ansible/collections/ansible_collections/opensvc/cluster/tests: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
ERROR: Command "tar oxzf /tmp/ansible-result-YfvJZN.tgz -C /home/abehl/.ansible/collections/ansible_collections/opensvc/cluster/tests" returned exit status 2.

```

**Comment by anshulbehl** [comment]
@mattclay @JohnLieske

**Comment by mattclay** [comment]
I've confirmed this. The issue occurs with `--docker` when `ansible-test` attempts to download test results from the container and there isn't an existing `tests` directory. I'm working on a fix.

**Comment by mattclay** [comment]
The fix has been merged.

**Comment by anshulbehl** [comment]
@mattclay Should this be backported to 2.9?
We will be accepting certification requests for 2.9 till 2.10 GA is out and till that point the issue will exist if this is not backported.
