### ISSUE TITLE
yml inheritance in variable files

### ISSUE THREAD

**Issue by 0x46616c6b** [ansible/ansible#6882]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4 
##### Environment:

N/A
##### Summary:

I have a huge role for all my webservers and their hosted sites. The variables for each vhosts are stored as a associative array. For the default values I created a list of key-value pairs. These default options are used in every single vhost config and only the settings I need to overwrite must be changed. This is very smart and simple for new features, but I can't extract these default values to the `all.yml` file in group_vars. It seems that yml will parsed before configs are merged or something else. In the same host_vars file the yml inheritance works well.
##### Steps To Reproduce:

The config should looks like this:

all.yml

```
vhosts_defaults: &vhosts_defaults
  enabled: True
  # many other options
```

example.com

```
vhosts:
  - {
    <<: *vhosts_defaults,
    host: www1.example.com,
    # many other options
  },
  # many other hosts
```
##### Expected Results:

No errors.
##### Actual Results:

```
fatal: [example.com] => Syntax Error while loading YAML script, /home/ansible/ansible_dev/host_vars/example.com.yml
Note: The error may actually appear before this position: line 47, column 9

  - {
    <<: *vhosts_defaults,
        ^
```

**Comment by mpdehaan** [comment]
So this is just coming from the YAML parser, so doing things in YAML format that require data in other files is not going to be a thing.

In other words, each individual file must still be valid YAML.

**Comment by 0x46616c6b** [comment]
Of course it comes from the parser, but the problem is, that the reference ti `vhosts_defaults` is in another file (all.yml) and their must be merged before i can extends from it. For this I wish it is possible to do so (reference from another file upper in hierarchy).

**Comment by 0x46616c6b** [comment]
I must push it again: **YAML inheritance works not with group-/host-vars inheritance in Ansible.** I must put the configuration from which i want to inherit in the same file. Push it to the group variable file or in all does not work. That is **not** a syntax problem.
