### ISSUE TITLE
[Debconf module] ability to use "debconf-set-selections file/with/preseeds"

### ISSUE THREAD

**Issue by kiranos** [ansible/ansible#6886]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.5.4
##### Environment:

Debian 7
##### Summary:

I'm investigating to use ansible and look through some of the core modules to find out what I have to write for myself.

I've sumbled on the debconf module. In the examples at http://docs.ansible.com/debconf_module.html I dont see to apply a preseed file

What I have today is a bash script that preseeds a lot of phpmyadmin installation settings.

the command is: 

```
debconf-set-selections /opt/phpmyadmin/phpmyadmin_preseed
```

and the preseed file contains:

```
cat  /opt/phpmyadmin/phpmyadmin_preseed

phpmyadmin      phpmyadmin/app-password-confirm password
phpmyadmin      phpmyadmin/mysql/admin-pass     password
phpmyadmin      phpmyadmin/password-confirm     password
phpmyadmin      phpmyadmin/setup-password       password
# MySQL application password for phpmyadmin:
phpmyadmin      phpmyadmin/mysql/app-pass       password
etc..
```

```
DEBIAN_FRONTEND=noninteractive apt-get install phpmyadmin -y
```

Is this possible today with debconf? or will it be made availabe?

Thanks
##### Expected Results:

Import file of preseed commands with debconf-set-selections so installation with 

```
DEBIAN_FRONTEND=noninteractive apt-get install phpmyadmin -y
```

ends ok with the options I've pre set.
##### Actual Results:

cant find use of file in docs

**Comment by bcoca** [comment]
you can probably use with_file: with the current debconf module, but it
currently does not have the feature built in (though I do plan to add it).

**Comment by mpdehaan** [comment]
FYI:

The apt module already passes non-interactivity parameters so you don't have to do this manually by setting anything up with debconf.  As such, if you are doing this to install packages, it's not required.

For running the rest of the debconf commands, it would take either multiple tasks or you could use the 'shell' command to just run the command you have above.

Pull requests to allow it to take an input file would likely be accepted!

**Comment by mpdehaan** [comment]
FYI, in the future, the users list, ansible-project@googlegroups.com, is a great place to ask questions!

**Comment by kiranos** [comment]
@bcoca thanks, I'll use the command module until debconf has file support, when it does I'd love to test it out, phpmyadmin has a huge list of options so it really makes it easier if a preseed file could parse them all in one go.

@mpdehaan great I'll keep the mailinglist in mind.

**Comment by gundalow** [comment]
@kiranos Note the following if you are going to be setting passwords https://github.com/ansible/ansible/pull/6808
