### ISSUE TITLE
Debian 7 mkpasswd instructions are not correct for generating the crypted password

### ISSUE THREAD

**Issue by kiranos** [ansible/ansible#6888]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4
##### Environment:

Debian 7
##### Summary:

FAQ: How do I generate crypted passwords for the user module?

```
mkpasswd --method=SHA-512
```

This doesnt work in Debian7 the generated crypt password doesnt allow login.

Instead remove the need for set the user's password to be crypted and instead use chpasswd. It Will remove some confusion how to encrypt the password etc beforehand, see there is a FAQ for this specificly so it would help alot to remove this step.
##### Steps To Reproduce:

```
mkpasswd --method=SHA-512 testing
$6$/w5s3AApbbO$3N6zGg0T/xrgKvwo1veLsBXyRZaFp4K92arfI9P5mYuaV.6s3W/aQJQvdlBkOqsVQ4C7qGPdahdV0zdMi8QNm/

ansible test -m user -a "uid=2001 name=testing password=$6$/w5s3AApbbO$3N6zGg0T/xrgKvwo1veLsBXyRZaFp4K92arfI9P5mYuaV.6s3W/aQJQvdlBkOqsVQ4C7qGPdahdV0zdMi8QNm/ shell=/bin/false home=/home/testing"

ssh testing@192.168.0.2
testing@192.168.0.2's password: 
Permission denied, please try again.
```

Instead you could do it like this:

```
useradd -u 1000 -s /bin/false -d /home/test -m test
echo test:123456789 | chpasswd 

cat /etc/shadow |grep test
test:$6$aVWkAvG/$jzxRTAqqbsivNu1f3.aNAK9MlLVy6Ebob9MR50ynXjxGNY3EdwfFseAJKWb7sde4TRZTxKqhpHYRqYytz.3f61:16168:0:99999:7:::
```
##### Expected Results:

You can now push the password as is and chpasswd will encrypt it for you and set it right.

**Comment by mpdehaan** [comment]
There may be other ways to fix the problem.  Nevertheless, thank you for the bug report and we'll investigate.

**Comment by jimi-c** [comment]
@kiranos what is the `ENCRYPT_METHOD` value set to in your `/etc/login.defs` file?

**Comment by kiranos** [comment]
@jimi-c 

```
cat /etc/login.defs |grep ENCRYPT_METHOD
# This variable is deprecated. You should use ENCRYPT_METHOD.
ENCRYPT_METHOD SHA512
# Only used if ENCRYPT_METHOD is set to SHA256 or SHA512.
```

**Comment by jimi-c** [comment]
@kiranos I believe the issue then would be the fact that you're setting the shell to `/bin/false`. I tested the mkpasswd method on my test debian7 box and did not have any issues.

**Comment by kiranos** [comment]
Hi @jimi-c false is just for test, here is a new case:

Its seems like its the import that goes wrong:

created with ansible:

```
ansible test -m user -a "uid=2003 name=test1 password=$6$9Q2621cZOJz9$RE7zqCFfUUoiL8jxF69kMTrKMIYriBlpZpP3DYFvtjui7bonIJ7wVSFGQq.dKGuA3N6NiHVLmZV58PAflj26g1 shell=/bin/false home=/home/test1"
ansible test -m user -a "uid=2004 name=test2 password=$6$lux0CgRdXuk$XYK8aMA4yTvXLNOZX/wq2kr8NUsFSavfcHmpRvw6GJwAJmZnvrPu26Jp5A2AZueyI1Ekuh0aeexCTyNh8eT1W1 shell=/bin/false home=/home/test2"
ansible test -m user -a "uid=2005 name=test3 password="$6$S1LSa4iE.D4$0MKa03MBYx2Yqq/LDKyRbaOBoAjiS7vyu86ghXsFlaxS3h3t96YWlk9p/28HwEUbslcvhvFkwPJY2VJjg8v7x1" shell=/bin/false home=/home/test3"
ansible test -m user -a "uid=2010 name=test9 password='$6$S1LSa4iE.D4$0MKa03MBYx2Yqq/LDKyRbaOBoAjiS7vyu86ghXsFlaxS3h3t96YWlk9p/28HwEUbslcvhvFkwPJY2VJjg8v7x1' shell=/bin/false home=/home/test9"


test1:Q2621cZOJz9.dKGuA3N6NiHVLmZV58PAflj26g1:16168:0:99999:7:::
test2:/wq2kr8NUsFSavfcHmpRvw6GJwAJmZnvrPu26Jp5A2AZueyI1Ekuh0aeexCTyNh8eT1W1:16168:0:99999:7:::
test3:.D4-suMKa03MBYx2Yqq/LDKyRbaOBoAjiS7vyu86ghXsFlaxS3h3t96YWlk9p/28HwEUbslcvhvFkwPJY2VJjg8v7x1:16168:0:99999:7:::
test9:.D4-suMKa03MBYx2Yqq/LDKyRbaOBoAjiS7vyu86ghXsFlaxS3h3t96YWlk9p/28HwEUbslcvhvFkwPJY2VJjg8v7x1:16168:0:99999:7:::
```

created with useradd && passwd user

```
test5:$6$u.Wvw7Uf$HhwqzEfUvE7BVGUlAdqa0YShtZdY59NcLUrTuGq1HUivZzt8le32VXhAwJMh64PSW7OP07rSLxuagf/yWICgV0:16168:0:99999:7:::
test6:$6$d/.GJrB2$QJogQezZT8WWey8JW.FVntGjNP9qgH/h6l/l4f4xId9RyvNA.G8gPGh62IylYil4svA.c35lnOKe6mfxp1GKx0:16168:0:99999:7:::
```

these two have the same lenght as the root password hash, so the imports from ansible very alot in lenght while the ordinary way of setting passwords has a fixed lenght. (and work)

update test1's password: passwd test1

and the new entry is as below and now I can login.

```
test1:$6$TD7gz2Kk$mFEPQymUiQ1AzBrjZXz.ncHEordlIZOv2DOrtHC5HBbRurE.dbl4RSbpSpTb1ZKMfgOtwEnxIg8sj00BH/u8w.:16168:0:99999:7:::
```

so my imports doesnt add the correct value in /etc/passwd.

**Comment by jimi-c** [comment]
Failing that, the issue may be due to the fact that you're running the ansible command above with double quotes, but your shell may be interpreting the `$'s` in the password string as variables, so you should wrap the module arguments (-a) in single quotes.

**Comment by kiranos** [comment]
@jimi-c thanks! last worked:

```
ansible test -m user -a 'uid=2013 name=kiranos password=$6$ZFgHm8r9BiR6TC$eyclBoMudculI3i1J//WaXT0sQV4PfAeAPySY1uYpI0eiFfvaTA6K.Qzdn51OnuP0.IbSnZYQisAQ/BPzNgaq. shell=/bin/false home=/home/kiranos'
```

So now I can use this option! but still it would be good if we could remove the need to hash the password, and push the password as is. as described above with "echo test:123456789 | chpasswd " or is there a limitation to this?

Again thanks for quick replies

**Comment by jimi-c** [comment]
Generally people do not like the idea of having to enter their passwords in plain text, which is why the module was designed to work with the encrypted value. Glad it was an easy fix!

**Comment by kiranos** [comment]
ok great thanks!
