### ISSUE TITLE
Gathering facts fails if a cifs mount is present on the remote machine

### ISSUE THREAD

**Issue by stinos** [ansible/ansible#6891]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.6
##### Environment:

Debian 7
##### Summary:

The setup script hangs on gathering mount facts when a cifs drive is mounted
##### Steps To Reproduce:

mount a windows share with these options in fstab:

```
//<address>/<share>  /mnt/net  cifs  rw,uid=1000,gid=1000,user=<id>,password=<pass>
```
##### Expected Results:

ansible should probably skip unreadable mounts
##### Actual Results:

the _get_mount_facts_ function in the setup script to hang on the line containing _os.statvfs_

**Comment by mpdehaan** [comment]
Hmm, I would have expected more reports of this -- we'll investigate.

Thanks!

**Comment by jimi-c** [comment]
I have merged in the above pull request, which should correct this issue for you. If you continue to see problems related to this issue, or if you have any further questions, please let us know. Thanks!

**Comment by stinos** [comment]
I can confirm #6900 fixes this problem, thanks!
