### ISSUE TITLE
lineinfile, race condition, concurrency when delegate to localhost

### ISSUE THREAD

**Issue by jimr6007** [ansible/ansible#68919]
##### SUMMARY
same as #64899 and #30413

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lineinfile

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jrichard/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(/home/rundeck/ansible.cfg) = True
CACHE_PLUGIN(/home/rundeck/ansible.cfg) = redis
CACHE_PLUGIN_CONNECTION(/home/rundeck/ansible.cfg) = localhost:6379:0
CACHE_PLUGIN_TIMEOUT(/home/rundeck/ansible.cfg) = 86400
COMMAND_WARNINGS(/home/rundeck/ansible.cfg) = False
DEFAULT_CALLBACK_WHITELIST(/home/rundeck/ansible.cfg) = [u'profile_tasks']
DEFAULT_FORKS(/home/rundeck/ansible.cfg) = 50
DEFAULT_GATHERING(/home/rundeck/ansible.cfg) = smart
DEFAULT_GATHER_SUBSET(/home/rundeck/ansible.cfg) = [u'!facter', u'all']
DEFAULT_HOST_LIST(/home/rundeck/ansible.cfg) = [u'/home/rundeck/ansible-inventory']
DEFAULT_STDOUT_CALLBACK(/home/rundeck/ansible.cfg) = skippy
DEFAULT_TIMEOUT(/home/rundeck/ansible.cfg) = 30
HOST_KEY_CHECKING(/home/rundeck/ansible.cfg) = False
```

##### OS / ENVIRONMENT

CentOS Linux release 7.7.1908
Linux 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

make a playbook that:
1) delegates to local host and run_once "create a temp file"
2) run a shell command against many hosts and capture stdout to var
3) delegate to local host, dump var result, stdout, for each host, to the local temp file referenced in step one

```yaml

```

##### ACTUAL RESULTS

it works as expected about 75% of the time but occasionally the output for one or two hosts will not make it to the local file even though -vvv output shows "line appended", apparently okay

```paste below

```

**Comment by jimr6007** [comment]
maybe I am trying to do something that is an "anti-pattern" ?

trying to sort of "create a report" by creating a local file on the control machine, trying to run a shell command on a bunch of hosts and dump the result of each shell command on each host to this local file on the control machine.

is there a different/better way I should be thinking about how to do something like this?

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.


this is a known issue when any 2 or more processes try to edit the same file simultaneously, in this case you can either use a play with `serial: 1` or set `throttle: 1` on the task to force serialization.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
