### ISSUE TITLE
Can't delete a vlan tag assigned to a network

### ISSUE THREAD

**Issue by luca-af** [ansible/ansible#68941]
##### SUMMARY

If I create a VLAN Tag for a network I can't delete it, but I have to delete the network and recreate it without the tag. 

If I use the web console I can easily remove a vlan tag on a network.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ovirt_network

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### STEPS TO REPRODUCE

Create a network with a vlan tag and test with any values (or no value), get Error or no action.

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ovirt/ovirt-ansible-collection

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
