### ISSUE TITLE
Centos7 cannot use the service module

### ISSUE THREAD

**Issue by sandaawa** [ansible/ansible#68996]
#### Centos7 cannot use the service module
- version:2.6.20
When I use the service module in centos6, I can restart the service, but when I use the service module in centos7, I will report an error
```
[opsuser@184-bushuji ansible]$ ansible cim_zhu -m service -a "name=CIM_V6 state=reloaded"
 [WARNING]: The service (CIM_V6) is actually an init script but the system is managed by systemd

192.169.138.236 | FAILED! => {
    "changed": false, 
    "msg": "Unable to start service CIM_V6: Failed to start CIM_V6.service: Interactive authentication required.\nSee system logs and 'systemctl status CIM_V6.service' for details.\n"
}

```
Is there anyone to help me, please

**Comment by mkrizek** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
