### ISSUE TITLE
`ansible_date_time.tz` gives an invalid Timezone `CEST`

### ISSUE THREAD

**Issue by ericcitaire** [ansible/ansible#69004]
##### SUMMARY

`ansible_date_time.tz` gives an invalid Timezone `CEST`.

In [lib/ansible/module_utils/facts/system/date_time.py, line 55](
https://github.com/ansible/ansible/blob/d3cab602a5b4578d5623bc5d4322681294abf2c2/lib/ansible/module_utils/facts/system/date_time.py#L55), `tz` should be assigned a valid Timezone name.

Actually it is assigned `time.strftime("%Z")`, which returns `CEST` when the current Timezone is `CET` and it is summer time.

It should be assigned `time.tzname[0]` (see [Python documentation](https://docs.python.org/3/library/time.html#time.tzname)).

Proposal :

```python
tz, _ = time.tzname
date_time_facts['tz'] = tz
```

References :

* https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
* https://www.iana.org/time-zones
* `ls -l /usr/share/zoneinfo`
* `date`, executed on April 17, at 14:57 GMT (16:57 in Paris)  :
  * `TZ=Europe/Paris date` prints *Fri Apr 17 **16:57:03 CEST** 2020* 👍 
  * `TZ=CET date` prints *Fri Apr 17 **16:57:03 CEST** 2020* 👍 
  * `TZ=CEST date` prints *Fri Apr 17 **14:57:03 CEST** 2020* 👎 
  * `TZ=FOO date` prints *Fri Apr 17 14:57:03 **FOO** 2020* 👎 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

facts

##### ANSIBLE VERSION

```
ansible 2.9.5
  config file = None
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/venv/local/lib/python2.7/site-packages/ansible
  executable location = /home/ubuntu/venv/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

* Configure the target host Timezone to be `Europe/Paris`
* Set system time to sometime in the *summer*
* Run `ansible -m setup -a filter=ansible_date_time`

##### EXPECTED RESULTS

```
localhost | SUCCESS => {
    "ansible_facts": {
        "ansible_date_time": {
            ...
            "tz": "CET", 
            ...
        }
    }, 
    "changed": false
}
```

##### ACTUAL RESULTS

```
localhost | SUCCESS => {
    "ansible_facts": {
        "ansible_date_time": {
            ...
            "tz": "CEST", 
            ...
        }
    }, 
    "changed": false
}
```

**Comment by sivel** [comment]
I was about to add `easyfix` to this issue, and then I realized that it's not really easy without additional context.  We cannot simply change the `tz` value at this point.  That would break backwards compatibility for users who are expecting it to be the local DST timezone.

As such, we would need to introduce another key, that holds the local non DST timezone.

Options are:

1. Create a new key that holds the `tzname` tuple
1. Create a new key that holds the local non DST timezone
1. Create 2 new keys, that are descriptive of being DST vs non DST

**Comment by ericcitaire** [comment]
Here is a workaround that works for me :

```yaml
- stat:
    path: /etc/localtime
  register: etc_localtime

- set_fact:
    timezone: "{{ etc_localtime.stat.lnk_source | regex_replace('^/usr/share/zoneinfo/', '') }}"
  when: etc_localtime.stat.exists and etc_localtime.stat.islnk and etc_localtime.stat.lnk_source is match("/usr/share/zoneinfo/.*")
```

IMO, this workaround gives a better result, since it returns `Europe/Paris` while Python `time.tzname` would return `('CET', 'CEST')`.
