### ISSUE TITLE
Allow specification of collections in configuration file to avoid having to use FQCN everywhere

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#69005]
##### SUMMARY

Currently, the documentation for collections moved outside of Ansible core are considering changing all examples to always use the FQCN for all invocations: https://github.com/ansible-collections/overview/issues/40

This means that even for modules which would work the same in Ansible 2.9 and earlier and in ACD/pip-installed Ansible, the examples would all be like:

```yaml
- name: Manage database users.
  community.general.mysql_user:
    _options here_
```

With redirection enabled, one could use `mysql` instead of `community.general.mysql` in ACD/pip-installed Ansible.

Or, even if using ansible-base, you can—at the _play_ level, inherited by play tasks but [not role tasks currently](https://github.com/ansible/ansible/issues/68198)—add a `collections` key listing all the collections the play uses, and module names would be mapped to the correct module in a given collection:

```yaml
- hosts: all

  collections:
    - community.general

  tasks:
    - name: Manage database users.
      mysql_user:
        _options here_
```

It was noted in some previous discussion, I believe by @dagwieers, that you would need to define `collections` once on _every_ play in a playbook, which is a bit of an inconvenience (and, additionally, since roles don't inherit play collections (see earlier linked issue), you'd also have to specify it inside every role's metadata as well).

It would be much easier if we could define the collections a project depends on (all plays in all playbooks, all roles, all inventory plugins, `ansible` cli invocations, etc.) in the config file.

Currently, I add an `ansible.cfg` file to almost every project I build to override other defaults for each project, and I would propose adding a `collections` list of some sort, but failing that, some other configuration file for a project would be nice to have, so we don't have to specify collections in many places or always use the FQCN everywhere.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

collections

##### ADDITIONAL INFORMATION

This feature request came about while discussing the possibility of new modules in ACD/'pip-installed ansible' collections being added to ansible/ansible's routing metadata, so users of ACD wouldn't basically be locked into either:

  - Only using modules that were created in Ansible 2.9 and earlier
  - Having to override the ACD-distributed collection and manually install a duplicated copy of a collection like `community.general` just to use one new module in that ACD-distributed collection that is not listed in core's routing metadata.

(One concrete example of this is the `k8s_exec` module, which was added to the `community.kubernetes` collection but is not currently accounted for in the [core routing.yml file](https://github.com/ansible/ansible/blob/devel/lib/ansible/config/routing.yml#L3238-L3251).)

**Comment by sivel** [comment]
As previously indicated elsewhere, we don't intend on adding this functionality to ansible.cfg, but we are entertaining the idea of a separate project config that would allow this.  This is however not scoped to occur in the 2.10 release.

We are no longer adding new config options to ansible.cfg that fundamentally changes how a playbook operates, which would require a specific ansible.cfg to even allow the playbook to function.

**Comment by geerlingguy** [comment]
@sivel - That makes sense, though `ansible.cfg` overrides are so frequently necessary to make certain playbooks work (at least, the way I work with Ansible) that I'd still have a custom one with every project alongside another project-specific config file. But it would be nice to have a YAML-based config file for more project or playbook-specific settings, working with ini-style is not super fun.

**Comment by nitzmahone** [comment]
@geerlingguy and that's exactly the reason the global collections search order isn't in `ansible.cfg`- it kills content portability (or requires that you "burn" your ansible.cfg in every project, preventing global config). Making a new place to define that that's "part of the content" is still a bit of a compromise that comes with some drawbacks, but it's one we want to explore.

**Comment by nitzmahone** [comment]
(also tangentially related to a discussion @thaumos and I were having recently about "should ACD allow everything it contains to be used unqualified?")- my vote was "no", because that makes content written under ACD not work anywhere else.

**Comment by jimi-c** [comment]
Per the above discussion it appears that we won't be adding this feature, however I'll defer to @nitzmahone and @thaumos as to whether or not we'll close this feature request.

**Comment by samdoran** [comment]
Closing per above discussion. This may end up in "project config" rather than global config.
