### ISSUE TITLE
ansible-pull gives spurious inventory warning

### ISSUE THREAD

**Issue by wallacms** [ansible/ansible#69014]
##### SUMMARY
When ansible-pull creates the ansible command to pull the repo, assuming no additional command line arguments have been supplied, it constructs both an --inventory argument and a --limit argument.  The --inventory argument has only 'localhost,' while the --limit argument has 'localhost,<hostname>,127.0.0.1'.  This is guaranteed to produce the warning:
[WARNING]: Could not match supplied host pattern, ignoring: <hostname>

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-pull

##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mwallace/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 9.2.1 20191008]
```

##### CONFIGURATION

```paste below
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Linux ccm-lc-fin-304 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

sudo ansible-pull -U <git repo url>

```yaml

```

##### EXPECTED RESULTS

I expect this to run with no warnings

##### ACTUAL RESULTS

I get the warning:
[WARNING]: Could not match supplied host pattern, ignoring: <hostname>

```paste below

```

**Comment by wallacms** [comment]
A related question, cli/pull.py logs the ansible command it uses to checkout at level vvvv, but it logs the command when it runs ansible-playbook at debug (so it only prints if debug is compiled in).  Why the difference?

**Comment by sivel** [comment]
For some reason, your `--limit` is being built incorrectly:

```
'localhost,,127.0.0.1'
```

This is created via this code:

```
        node = platform.node()
        host = socket.getfqdn()
        limit_opts = 'localhost,%s,127.0.0.1' % ','.join(set([host, node, host.split('.')[0], node.split('.')[0]]))
```

This indicates that on your host, `platform.node()` and `socket.getfqdn()` are both returning `''`.  This causes an erroneous empty string.

I suppose we could improve the logic slightly to remove empty items, but this really sounds like a problem with the host itself.

**Comment by bcoca** [comment]
```
diff --git a/lib/ansible/cli/pull.py b/lib/ansible/cli/pull.py
index bcbe64a23d..3db5a22fba 100755
--- a/lib/ansible/cli/pull.py
+++ b/lib/ansible/cli/pull.py
@@ -168,7 +168,11 @@ class PullCLI(CLI):
         # Now construct the ansible command
         node = platform.node()
         host = socket.getfqdn()
-        limit_opts = 'localhost,%s,127.0.0.1' % ','.join(set([host, node, host.split('.')[0], node.split('.')[0]]))
+        hostnames = ','.join(set([host, node, host.split('.')[0], node.split('.')[0]]))
+        if hostnames:
+            limit_opts = 'localhost,%s,127.0.0.1' % hostnames
+        else:
+            limit_opts = 'localhost,127.0.0.1'
         base_opts = '-c local '
         if context.CLIARGS['verbosity'] > 0:
             base_opts += ' -%s' % ''.join(["v" for x in range(0, context.CLIARGS['verbosity'])])
```
