### ISSUE TITLE
ansible-doc --json for community.general results in "wrong" filename

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansible#69033]
##### SUMMARY
For example the filename returned by `ansible-doc --json community.general.znode` is `.../ansible-collections/ansible_collections/community/general/plugins/modules/znode.py`, while it should be `.../ansible-collections/ansible_collections/community/general/plugins/modules/clustering/znode.py`.

(This breaks the namespace extraction code for changelog generation.)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-doc

##### ANSIBLE VERSION
```paste below
devel
```

**Comment by felixfontein** [comment]
CC @bcoca

**Comment by bcoca** [comment]
known issue, since 'routing' is not in yet, it points to the file you gave it (which currently is a symlink), otherwise you would have to type `ansible-doc --json community.general.clustering.znode`

**Comment by felixfontein** [comment]
I specified the module name that `--list` gave me. Does `--list` only find the symlinks then?

**Comment by bcoca** [comment]
it can ONLY get the symlinks, since routing is not working yet. Once added, I'll update ansilbe-doc to read routing, but then a 'conflict' might arise since the symlinks also exist (need to figure out how to deal with that).

**Comment by felixfontein** [comment]
For changelog generation, I added code which does recursive symlink resolving to find out the "real" module path.

**Comment by gundalow** [comment]
> it can ONLY get the symlinks, since routing is not working yet. Once added, I'll update ansilbe-doc to read routing, but then a 'conflict' might arise since the symlinks also exist (need to figure out how to deal with that).

@bcoca once routing PR is merged I plan on removing the symlink from community.general and community.network. Is that the right thing for me to do?

**Comment by felixfontein** [comment]
@gundalow I'm not sure, that would make it very hard to use the collection from 2.9. Maybe we should wait with that for the 2.0.0 release of the collection, so that users have at least a chance to upgrade to another released ansible(-base) version before 2.9 support is dropped.

**Comment by bcoca** [comment]
^ as @felixfontein  points out, 'the right thing'TM depends on if you want to keep 2.9 compatibility or not. 

No matter if you keep symlinks or not, when i update ansible-doc, should I display the alias? the redirect target? both?

**Comment by nitzmahone** [comment]
maybe fixed by #74963

**Comment by felixfontein** [comment]
I think it's actually fixed by that. I remember having suddenly seen the 'real' paths in the `--metadata-dump` output while using Brian's branch.

**Comment by s-hertel** [comment]
Closing as per above
