### ISSUE TITLE
ec2_group doesn't accept port ranges

### ISSUE THREAD

**Issue by hexsel** [ansible/ansible#6903]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel 519f1c781c) last updated 2014/04/04 18:07:27 (GMT -700)
##### Environment:

N/A 
##### Summary:

When creating groups using [ec2_groups](http://docs.ansible.com/ec2_group_module.html), the rules require "from_port" and "to_port".  These don't allow port ranges to be defined (only exact numeric matches).
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
Another comment from a user on the mailing list
"  Not sure if it matters, but the ec2_group help page does mention an "all" setting, it just doesn't seem to be working."

**Comment by danvaida** [comment]
@hexsel did you manage to get this working? I am setting something like
rules_egress:
        - proto: all
          from_port: 0
          to_port: 65535
          cidr_ip: 0.0.0.0/0

And it works just fine ;)

**Comment by hexsel** [comment]
I'm not sure, but I think these 2 commits (ec2_group has had lots of commits in the last month) have something to do with it:
https://github.com/ansible/ansible/commit/713657d6840fe5ea40fb11418eb749bd7199b8ce#diff-317f4cc0ba915fbd7bd5ac28fdadc031
https://github.com/ansible/ansible/commit/1ef0402f037b332610e8d4b9c568818f7ec50ea3#diff-317f4cc0ba915fbd7bd5ac28fdadc031

I don't have access to the system from here, and that short project ended anyway.  I will take your word for it and close the issue as solved.
