### ISSUE TITLE
Ansible-vault in INI style inventory file?

### ISSUE THREAD

**Issue by su-hy** [ansible/ansible#69039]
##### SUMMARY

Hey, this page show INI style hosts file using ansible-vault to encrypt passwords:
https://docs.ansible.com/ansible/latest/network/user_guide/network_best_practices_2.5.html

But this page says that it is not possible to do it like that:
https://docs.ansible.com/ansible/latest/network/getting_started/first_inventory.html

"This is an example using an extract from a YAML inventory, as the INI format does not support inline vaults"

Which one is correct?

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

**Comment by sivel** [comment]
The documentation in https://docs.ansible.com/ansible/latest/network/user_guide/network_best_practices_2.5.html#groups-and-variables-in-an-inventory-file is incorrect.  `!vault` can only be used from within YAML files

**Comment by Akasurde** [comment]
resolved_by_pr #71246
