### ISSUE TITLE
Add SRV Record to win_dns_record Module

### ISSUE THREAD

**Issue by CSimpiFoN** [ansible/ansible#69041]
##### SUMMARY
It would be great to manage SRV records too on Windows DNS server with win_dns_record module

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_dns_record

##### ADDITIONAL INFORMATION
Extend the functionality of win_dns_module

``
- name: SRV example
  win_dns_record:
    name: "metrics.node"
    type: "SRV"
    value: "db1"
    port: "9100"
    zone: "example.com"
```

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.windows

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by CSimpiFoN** [comment]
Thank you!
