### ISSUE TITLE
Broken link for OpenStack Inventory Plugin at devel branch

### ISSUE THREAD

**Issue by tchellomello** [ansible/ansible#69042]
##### SUMMARY

Broken link for OpenStack Inventory Plugin  at devel branch. The correct file is expected to be present on stable-2.9 branch.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

plugin: inventory
https://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#openstack

##### ADDITIONAL INFORMATION

If you look at the documentation at https://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#openstack, the docs-latest is pointing OpenStack inventory to the git code, however, due to a code re-org, the plugin is not there anymore. 

However, we can see it on the stable-2.9 code: 
https://github.com/ansible/ansible/blob/stable-2.9/contrib/inventory/openstack.yml

**Comment by sivel** [comment]
For documentation issues for Tower please open an issue with your support team, or send an email to docs@ansible.com.

See https://github.com/ansible/ansible/pull/68905 for how this was resolved for the docs in this repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
