### ISSUE TITLE
[1/1]Provide a way for users to find the new locations for inventory scripts

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#69051]
##### SUMMARY

In releases prior to 2.10, we pointed users directly to the inventory script location in github. Those scripts have now moved, some to their own related collections, may to community.general, where they may move again.

It would be good to provide a docs page that lists the inventory scripts and their new locations.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

docs.ansible.com
##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

**Comment by samccann** [comment]
@sivel provided a quick script that may help with this:
```
from urllib.request import urlopen
import json
import os
f = urlopen(
    'https://sivel.eng.ansible.com/api/v1/collections/provides',
    data=json.dumps({'path': '^scripts\/inventory\/.+\.py'}).encode()
)
data = json.load(f)
for collection, info in data.items():
    ci = info['manifest']['collection_info']
    for fobj in info['files']:
        script = os.path.splitext(os.path.basename(fobj['name']))[0]
        if script == '__init__':
            continue
        print('{}: {}'.format(script, 'https://galaxy.ansible.com/{namespace}/{name}'.format(**ci)))


```
With a  current output that looks like:
ec2: https://galaxy.ansible.com/community/aws
rhv: https://galaxy.ansible.com/community/general
cobbler: https://galaxy.ansible.com/community/general
lxd: https://galaxy.ansible.com/community/general

**Comment by sivel** [comment]
Just for clarity, for anyone who stumbles upon this issue, and subsequently the above API.  This API, while we intend for it to be stable, isn't a replacement for galaxy and we don't intend on Ansible actually using this API.  It's more for "internal" tool and process building.

**Comment by samccann** [comment]
- this can be a note to say most have moved to community.general, with one in AWS, but users should use plugins instead.
