### ISSUE TITLE
ansible_ssh_pass  parsing error

### ISSUE THREAD

**Issue by jaywayjayway** [ansible/ansible#69066]
##### SUMMARY

when my password end with`.` (only  number ) and   put  `ansible_ssh_pass ` in  host like this:
```
[test]
172.16.49.70 ansible_ssh_user=root ansible_ssh_port=22  ansible_ssh_pass='123456.'

```
If will be error 

```
172.16.49.70 | UNREACHABLE! => {
    "changed": false,
    "msg": "Invalid/incorrect password: Permission denied, please try again.",
    "unreachable": true
}
```
but when I configue like this:
```
[test]
172.16.49.70 ansible_ssh_user=root ansible_ssh_port=22  
[all:vars]
ansible_ssh_pass='123456.'
```

it will be `OK`.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below


[root@work ~]#  ansible --version
ansible 2.9.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dz/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
[root@work ~]#

```

##### CONFIGURATION

```paste below




```

##### OS / ENVIRONMENT

CentOS7

##### STEPS TO REPRODUCE

```yaml

```
I debug it , I find it parsing error .
![image](https://user-images.githubusercontent.com/5195170/79836292-8d053e00-83e2-11ea-86e2-5459f92440c0.png)

##### ACTUAL RESULTS

```paste below

```

**Comment by sivel** [comment]
This limitation is described in the `ini` inventory plugin documentation at https://docs.ansible.com/ansible/latest/plugins/inventory/ini.html :

> When declared inline with the host, INI values are processed by Python’s ast.literal_eval function (https://docs.python.org/2/library/ast.html#ast.literal_eval) and interpreted as Python literal structures (strings, numbers, tuples, lists, dicts, booleans, None).
As such, this is roughly what happens from a python perspective:

```pycon
>>> import ast
>>> from shlex import split as shlex_split
>>> line = "172.16.49.70 ansible_ssh_user=root ansible_ssh_port=22  ansible_ssh_pass='123456.'"
>>> tokens = shlex_split(line, comments=True)
>>> for token in tokens:
...     if '=' not in token:
...         continue
...     name, value = token.split('=', 1)
...     try:
...         value = ast.literal_eval(value)
...     except Exception:
...         pass
...     print('{}: {!r}'.format(name, value))
...
ansible_ssh_user: 'root'
ansible_ssh_port: 22
ansible_ssh_pass: 123456.0
```

As you have found, and as shown above `123456.` is converted to a `float`.

However, as you indicate, using a `:vars` section will work, or you can switch to using a YAML file in `host_vars/all.yml` to define these values.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
