### ISSUE TITLE
gcp_container_node_pool shielded instance config is missing

### ISSUE THREAD

**Issue by markmcdowell** [ansible/ansible#69067]
##### SUMMARY

Specifying shielded instance config is not exposed by the module. See
https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/NodeConfig#ShieldedInstanceConfig

It's also missing from https://github.com/GoogleCloudPlatform/magic-modules/blob/master/products/container/api.yaml

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gcp_container_node_pool

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /Users/Mark/Developer/reactivemarkets/github/deployment/ansible/ansible.cfg
  configured module search path = ['/Users/Mark/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/Mark/Developer/reactivemarkets/github/deployment/ansible/venv/lib/python3.7/site-packages/ansible
  executable location = /Users/Mark/Developer/reactivemarkets/github/deployment/ansible/venv/bin/ansible
  python version = 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) [Clang 6.0 (clang-600.0.57)]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(ansible.cfg) = ['timer']
DEFAULT_HOST_LIST(ansible.cfg) = ['/']
DEFAULT_ROLES_PATH(ansible.cfg) = ['/']
RETRY_FILES_ENABLED(ansible.cfg) = False
(END)
```

##### OS / ENVIRONMENT
Mac OSX

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/ansible_collections_google

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
