### ISSUE TITLE
ansible-2.9.7 copy task is very slow and synchronize is not  an option

### ISSUE THREAD

**Issue by XeS0r** [ansible/ansible#69072]
##### SUMMARY

The copy module is very slow copying files recursively. This is even visible if you copy 10 empty files. And using synchronize is not an option because ansible devs decided that use_ssh_args=no is a good default choice. And we need it for Proxyjumps to kvm guests. In my opinion this does not make sense because all other modules simply use ssh_args and synchronize is the only one I'm aware that not use them by default. And really no one will modify roles owned by someone else only to use his customized ssh_args. That does not make sense at all. But even if this will be fixed in synchronize it is not working properly on sles 12 and sles 15.2.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

```
copy module
```

##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = None
  configured module search path = ['/home/auser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/auser/.local/lib/python3.7/site-packages/ansible
  executable location = /home/auser/.local/bin/ansible
  python version = 3.7.0 (default, Sep 11 2018, 13:35:39) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Reproduce:
```bash
mkdir files;
touch files/random-files.{1..10}
cat <<-EOF > site.yml
- hosts: servers
  tasks:
    - name: "Copy files to remote"
      copy:
        src: "files/"
        dest: "~/"
        mode: preserve
EOF
ansible-playbook -vv -i hosts site.yml
```

##### EXPECTED RESULTS

A lot faster copy function. At least something that is capable to copy a small amount of files recursively.

##### ACTUAL RESULTS

Copy process is slow as hell. If the amount of files and file size change this is even worse.

```paste below

```

**Comment by sivel** [comment]
This is expected, and a limitation of the copy module.  Each file is independently copied via effectively a re-execution of the copy task.

For recursive file copies, you will need to evaluate other means.  If the `synchronize` module is not working for you, we recommend utilizing a `command` or `shell` task to directly call `rsync`.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
