### ISSUE TITLE
mysql_user module of ansible not working as expected with ansible engine 2.9.6-1

### ISSUE THREAD

**Issue by nitinkansal1984** [ansible/ansible#69076]
##### SUMMARY
Below is the piece of code failing to create mysql user.

- hosts: localhost
  tasks:
    - add_host: hostname=abc.example.com group=remotehost
- hosts: remotehost
  remote_user: ansible
  tasks:
    - name: create user and grant specific access to a DB
      mysql_user:
        name="username"
        password="password"
        host="localhost"
        check_implicit_admin=yes
        priv="dbname.*:ALL,GRANT"
        login_user="mysql"
        login_password="password"
        login_host="abc.example.com"
      with_items:
        - "10.11.12.13"
        - "abc"
        - "abc.example.com"
        - "%"
I am running the above script. The user mysql has full privilege to mysql. when I run the playbook with ansible engine version 2.7.9, it worked fine, but throwing error as below when run against ansible engine version 2.9.6

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: _mysql_exceptions.OperationalError: (1142, "SELECT command denied to user ''@'abc.example.com' for table 'user'")

 PyMySQL version 0.9.3 is installed on my ansible control machine.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mysql_user
##### ANSIBLE VERSION

```paste below
2.9.6
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

7.7

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
