### ISSUE TITLE
Docs regarding dynamic inventory do not include fully workable steps

### ISSUE THREAD

**Issue by jamesfreeman959** [ansible/ansible#69075]
##### SUMMARY

I have been trying to follow the latest process for working with the EC2 dynamic inventory script on Ansible 2.9.6 - although the documentation correctly references the move of this module to ansible-collections, even when you pull the dynamic inventory scripts from these locations, they do not run. There appears to be a dependency issue.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

docs/docsite/rst/user_guide/intro_dynamic_inventory.rst

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS 7.7, no browser involved.

##### ADDITIONAL INFORMATION

In Ansible <=2.8, you could just download the ec2.py and ec2.ini files and run them without issue. Now although the documentation suggests that you still do this (with the appropriately updated links to community.aws), the ec2.py script no longer runs, and instead bails out with a missing module error:
```
 ansible -i ec2.py -m ping all
[WARNING]:  * Failed to parse /root/ec2.py with script plugin: Inventory script
(/root/ec2.py) had an execution error: Traceback (most recent call last):
File "/root/ec2.py", line 172, in <module>     from
ansible_collections.amazon.aws.plugins.module_utils import ec2 as ec2_utils
ImportError: No module named
ansible_collections.amazon.aws.plugins.module_utils
[WARNING]:  * Failed to parse /root/ec2.py with ini plugin: /root/ec2.py:3:
Error parsing host definition ''''': No closing quotation
[WARNING]: Unable to parse /root/ec2.py as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
```
It looks like there's a pre-requisite step involved to get the required module into place for this script to import, but this isn't documented either here, or on the community.aws site. I attempted:
```
ansible-galaxy collection install community.aws
```
However the error remains - though I doubt that the ec2.py script (or more to the point Python) knows to look in ~/.ansible/collections/ansible_collections/amazon/aws.

I'd suggest this is a documentation issue, as I presume that if you know how to get the collection installed for the inventory to use then it will work as before?

**Comment by sivel** [comment]
The new locations of the scripts are dependent on having installed the collection that it is part of in many cases.  If you are using Ansible 2.9, it's probably best/easiest to just download the scripts from the stable-2.9 branch or from one of the 2.9.x tags:

https://github.com/ansible/ansible/tree/stable-2.9/contrib/inventory

The devel process and utilizing many of the collections in thier current state, are dependent on Ansible 2.10 which is still in development.

**Comment by gundalow** [comment]
@jamesfreeman959 hey,
Thanks for raising this. I think there are a few we can do to improve this.
1) Review the inventory scripts, some have ended up in community.general, whereas they should be in other repos 
2) Review docs, as you've mentioned above 
3) Google search for old URLs, and see if we can update them. 
4) Add a `contrib/README.md` file, pointing to the new locations

**Comment by abadger** [comment]
I think that inventory script like this won't work using `ansible-galaxy collection install` because the module_utils inside of the collection won't be on the PYTHONPATH at all.

Potential solutions?

* Probably the best solution is for ansible to expose its collection finding code in some way.  Then the inventory scripts can be modified to use that API to find the module_utils.  However, this is work that wasn't scheduled... it would require API exposure from core and porting of scripts from the collection maintainers.
* Install the collections into the PYTHONPATH.  I think that if the collections are installed into the PYTHONPATH (for instance, /usr/lib/python3.7/site-packages/ansible_collections/community/aws/ ), then the script will work.
  * Caveat: This ill work on python3.  Python2 does not have the python3 style namespace package support which would allow the script to work.  Maybe the scripts could have their shebang line changed to /usr/bin/python3 and the documentation could be updated to say that they require Python3.
  * This isn't great as it makes the script dependent on how the collection was installed.  And further, the install method would not be what we're recommending people use to install collections.
    * Crazy Eddy idea: change ansible-galaxy to install to PYTHONPATH.  Then the recommendation on how to install is still the same.

**Comment by abadger** [comment]
Third potential solution:
* Modify the inventory scripts to duplicate the code that's in the module_utils.

**Comment by DouglasHeriot** [comment]
Another issue with the inventory docs: example of enabling caching uses `jsonfile`.
https://docs.ansible.com/ansible/devel/plugins/cache.html

It says that:

> You can use any cache plugin shipped with Ansible to cache inventory, but you cannot use a cache plugin inside a collection

Well, `jsonfile` has been moved to the `community.general` collection so no longer works. The only cache plugin part of ansible base is `memory`, which is a bit useless for dynamic inventories.

Will there be a way in 2.10 to use cache plugins from a collection?

**Comment by jamesfreeman959** [comment]
@gundalow thanks so much - I'm currently editing and updating a book for Ansible 2.9, and that's how I came across this. Unfortunately it looks like it'll all change again in 2.10 if I'm understanding correctly, but we'll cross that bridge when it comes to it.

If you'd like me to flag up anything I find (and have found so far) I'm happy to help you.

@abadger really appreciate your input - I had similar thoughts to you and I had a go at setting PYTHONPATH, but to no avail, and I concluded:
1. I'm on a deadline and didn't have time right now to figure it out (otherwise I would have persevered)
2. I'm pretty sure that it wasn't intended that an install of Ansible 2.10 (or 2.9) would require you to mess with PYTHONPATH - that seems like a fairly poor user experience, though as you say there are ways to install the collection that don't require this. I love the whole "Crazy Eddy idea" - I'm going to borrow that term if I may :)

@DouglasHeriot - sorry to hear that you've found problems with the cache plugin - I feel like there's a few things end-users need to learn about the changes coming up in 2.10, which hopefully will all come in due course. 2.9 feels like it's stuck between two worlds.

**Comment by gundalow** [comment]
@DouglasHeriot Thanks for the info on cache plugin info, I've raised a separate issue for that in https://github.com/ansible/ansible/issues/69092

**Comment by abadger** [comment]
@jamesfreeman959 yeah, I think that PYTHONPATH should work but the end user probably shouldn't be responsible for setting it. It feels like the script either needs to be able to ask ansible where the module_utils or overall collection is installed (and then use)  (option 1) or installation should put the collection into a place that the script will work (option 2). (or the script modified to not rely on the module_utils, option 3).

You should be able to mess with PYTHONPATH to get it to work.  But I did find it to require quite a few steps.  Here's what I did to test (WARNING: the ansible-base package that I install here was just for testing.  You'll want to uninstall it afterwards otherwise it might prevent installing the real ansible-2.10 later):

``` sh
$ python3.8 -m pip install --user --upgrade --extra-index-url  https://toshio.fedorapeople.org/ansible/acd/   ansible-base
$ # Since the module_utils live in amazon.aws, it seems like community.aws needs to have a collection level dependency on it?
$ ansible-galaxy collection install community.aws amazon.aws -p ~/tmp/collection_path
$ # This needs to be some python3 version but doesn't need to be the same version as
$ # ansible runs as.  You will need to make sure the deps are installed (python3 -m pip install boto)
$ sed -i '1 s@^.*$@#!/usr/bin/env python3@' ~/tmp/collection_path/ansible_collections/community/aws/scripts/inventory/ec2.py
$ # Perhaps the mode of the scripts should be changed in the collections?
$ chmod 0755 ~/tmp/collection_path/ansible_collections/community/aws/scripts/inventory/ec2.py
$ # Edit ec2.ini.... I don't have any ec2 hosts so I didn't actually do that.
$ # I did verify that the next command waits for the script to talk to amazon
$ # instead of raising an ImportError.
$ PYTHONPATH='/home/badger/tmp/collection_path'  ansible localhost -m ping -i ~/tmp/collection_path/ansible_collections/community/aws/scripts/inventory/ec2.py
```

I do not recommend documenting this sequence of steps as our solution.  It's just information to show how all the parts interact.

**Comment by flowerysong** [comment]
For this particular inventory script (`ec2.py`) it might just be time to dump it entirely. It relies on the deprecated boto libraray, and its replacement (the `aws_ec2` inventory plugin) has been around for a while.

**Comment by jillr** [comment]
Historically we've refrained from deprecating this script as it has also been included with Tower.  With the move to collections this is no longer as limiting factor as Tower will not run inventory scripts from collections (if still included it would be vendored aiui).  So we are free to begin a deprecation process on `ec2.py`, in favor of the plugin.

**Comment by DouglasHeriot** [comment]
> ```shell
> $ chmod 0755 ~/tmp/collection_path/ansible_collections/community/aws/scripts/inventory/ec2.py
> ```

@abadger I've run into this collections permissions issue as well. I think it's fixed in #68415 but I haven't tested it myself.

**Comment by glennschmidt** [comment]
Btw the currently published docs don't even contain a working link to the ec2.py script..

https://docs.ansible.com/ansible/latest/user_guide/intro_dynamic_inventory.html#inventory-script-example-aws-ec2
links to
https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory/ec2.py
which is a 404

**Comment by mxhr** [comment]
@glennschmidt Yeah, it looks like they got removed or something.

I was able to locate them elsewhere, when looking through a doc page itself on github:
https://raw.githubusercontent.com/ansible-collections/community.aws/master/scripts/inventory/ec2.py

https://raw.githubusercontent.com/ansible-collections/community.aws/master/scripts/inventory/ec2.ini

**Comment by samdoran** [comment]
Docs have been updated to reference the ec2 inventory plugin the collection.
