### ISSUE TITLE
Help with ios_command module

### ISSUE THREAD

**Issue by Omarhegqzy** [ansible/ansible#69096]
Please raise issues via the [new interface](https://github.com/ansible/ansible/issues/new/choose)

Hello, i have 2 switches. I wanted to run a command (show arp) and check a specific output if exist or not on both. Then, i wanted to run a command (show arp) and display the output. 

The problem is that since the output i'm inspecting on first task doesn't exist on switch1 .... the next task (show cdp ne) is not performed for switch 1..... i don't know why this dependency. I thought that there shouldn't be dependencies between tasks this way. How to overcome?

---

- hosts: SWITCHES

  tasks:

  - name: run show and check to see if output contains value
    ios_command:
      commands: "show arp"
      wait_for: result[0] contains aabb.cc00.3000

  - name: Get Shows 
    ios_command:
      commands: "show arp"
    register: Output

  - name: Display Output
    debug:
      msg: "{{ Output.stdout_lines[0] }}"

Output:
----------

PLAY [SWITCHES] ******************************************************************************************

TASK [run show version and check to see if output contains IOS] ******************************************
ok: [switch2]
fatal: [switch1]: FAILED! => {"changed": false, "failed_conditions": ["result[0] contains aabb.cc00.3000"], "msg": "One or more conditional statements have not been satisfied"}

TASK [Get Shows] *****************************************************************************************
ok: [switch2]

TASK [Display Output] ************************************************************************************
ok: [switch2] => {
    "msg": [
        "Protocol  Address          Age (min)  Hardware Addr   Type   Interface", 
        "Internet  192.168.0.1             0   342c.c4ad.9a81  ARPA   Ethernet0/0", 
        "Internet  192.168.0.157           -   aabb.cc00.3000  ARPA   Ethernet0/0", 
        "Internet  192.168.0.248           0   d4d2.5287.83ef  ARPA   Ethernet0/0"
    ]
}

PLAY RECAP ***********************************************************************************************
switch1                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
switch2                    : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by Shrews** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
