### ISSUE TITLE
Supervisorctl doesnot support start,stop and restart all processes with ansible .

### ISSUE THREAD

**Issue by khamarshaikh** [ansible/ansible#69094]
##### SUMMARY
Supervisorctl doesnot support start,stop and restart all processes with ansible .

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
supervisorctl

##### ADDITIONAL INFORMATION
Ideally command line supports start , stop and restart supervisorctl all processes using 
```
sudo supervisorctl start all
```
But using the ansible module processes should be listed in items to take any action.

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
