### ISSUE TITLE
Collection roles cannot call stand alone roles

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#69101]
##### SUMMARY
A role within a collection, cannot easily call a standalone role

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/playbook/role/definition.py

##### ANSIBLE VERSION

```paste below
2.9
2.10
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Assume a collection role like the following:

collections/ansible_collections/ns/col/roles/nscolrole/tasks/main.yml
```
- include_role:
    name: standalone
```

And a standalone like:

roles/standalone/tasks/main.yml
```
- debug:
    msg: standalone
```

You can work around this, by explicitly adding `ansible.legacy` to the collection search for the `include_role` like:

```
- include_role:
    name: standalone
  collections:
    - ansible.legacy
```

##### ACTUAL RESULTS
```
TASK [include_role : standalone] *************************************************************************************
ERROR! the role 'standalone' was not found in ns.col:ansible.builtin

The error appears to be in '/Users/matt/projects/ansibledev/playbooks/ericsysmin/collections/ansible_collections/ns/col/roles/nscolrole/tasks/main.yml': line 2, column 11, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- include_role:
    name: standalone
          ^ here
```

**Comment by thaumos** [comment]
@geerlingguy , @tima, and @s-hertel, one to keep watch on.

**Comment by ericsysmin** [comment]
@ericsysmin watching as well. Thanks, @sivel
