### ISSUE TITLE
vsphere_copy argument 'port' is not customizable

### ISSUE THREAD

**Issue by tobit6795** [ansible/ansible#69103]
Tested ansible version: 2.9.2
VMWare Host Version: 6.0 (which isn't really relevant)

So like in the other vmware modules (vmware_guest) there is an argument called `port` when you want to access the API over a different port than 443 (i used 8443 via ssh forwarding).
This works quite well with the vmware_guest module. But not as excpected with vsphere_copy. i just got an 301 Error.
I took a look at the source code and couldnt find a section where the argument `port` were passed.
After i changed my ssh tunnel to be forwarded to localhost:443, the module worked right away, even when i specified `port` to be on port 8443.
I also tested the use of environmental variables btw, but without any success.

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/vmware

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
