### ISSUE TITLE
Add `from_toml` and `to_toml` filter plugins to official Ansible distribution

### ISSUE THREAD

**Issue by Teebor-Choka** [ansible/ansible#69120]
##### SUMMARY
Ansible uses dicts to store data internally. When this data should be translated into/from textual form (e.g. to create a configuration file with a specified format), filter plugins are used. Ansible features filters for the most common formats used, but lacks a direct TOML filter support.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
filter plugins

##### ADDITIONAL INFORMATION
External filter plugins for TOML exist, but due to the prevalance of TOML configuration files it would be beneficial for core Ansible plugins to include the `from_toml` and `to_toml` filter plugins, e.g. in roles to read the existing TOML configurations or write TOML configurations into files.

```yaml
- name: to_toml filter plugin example
  vars:
    test:
      a: "b"
  debug:
    msg: "{{ test | to_toml }}"

- name: load a file
  slurp:
    src: /path/to/a.toml
  register: toml_file

- name: from_toml filter plugin example
  debug:
    msg: "{{ toml_file | b64decode | from_toml }}"
```

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. We are no longer adding new plugins to this repository at this time.  The alternative is pushing new plugins into collections.  You can find these filters in the following collection:

https://galaxy.ansible.com/sivel/toiletwater

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
