### ISSUE TITLE
ecs_taskdefinition should support docker health check

### ISSUE THREAD

**Issue by everops-nick** [ansible/ansible#69130]
I think this is pretty self explanatory. Docker health checks have been available in ECS for a few years now.

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.aws

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
