### ISSUE TITLE
Python site-packages using virtualenv

### ISSUE THREAD

**Issue by flysen** [ansible/ansible#69148]
##### SUMMARY
Python module not found when using `localhost` in inventory file.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-playbook python3 in virtualenv using jmespath

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /ansible-dev/swap/ansible.cfg
  configured module search path = ['/ansible-dev/swap/library']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.6 (default, Feb 26 2020, 20:54:15) [GCC 7.3.1 20180712 (Red Hat 7.3.1-6)]
```

##### CONFIGURATION

```
ANSIBLE_SSH_ARGS(/ansible-dev/swap/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null
DEFAULT_KEEP_REMOTE_FILES(env: ANSIBLE_KEEP_REMOTE_FILES) = True
DEFAULT_MODULE_PATH(/ansible-dev/swap/ansible.cfg) = ['/ansible-dev/swap/library']
DEFAULT_ROLES_PATH(/ansible-dev/swap/ansible.cfg) = ['/ansible-dev/swap/roles']
DEFAULT_STDOUT_CALLBACK(/ansible-dev/swap/ansible.cfg) = debug
HOST_KEY_CHECKING(/ansible-dev/swap/ansible.cfg) = False
RETRY_FILES_ENABLED(/ansible-dev/swap/ansible.cfg) = False
```

##### OS / ENVIRONMENT

- Linux 565130333f44 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Amazon Linux release 2 (Karoo)
- docker

##### STEPS TO REPRODUCE

- Install Ansible "outside" virtual environment `/usr/bin/python3 -m pip install ansible`
- Install python3 virtual environment `python3 -m venv /usr/local/kaas_virtualenv`
- Install a python module into virtual environment `/usr/local/kaas_virtualenv/bin/python3 -m pip install jmespath`

**playbook.yaml**

```yaml
---
- hosts: control_host
  gather_facts: yes
  become: no
  environment:
    PYTHONPATH: "/usr/local/kaas_virtualenv/lib/python3.7/site-packages"

  vars:
    my_users:
      - password: 123
        username: broker
      - password: 321
        username: broker2
      - password: 213
        username: broker3

  tasks:
    - name: print users
      debug:
        msg: "users = {{ my_users|json_query('[*].username') }}"
```

**server_inventory**

```yaml
[control_host]
localhost

[control_host:vars]
ansible_connection=local
ansible_python_interpreter=/usr/local/kaas_virtualenv/bin/python3
```

##### EXPECTED RESULTS
`ansible-playbook -i server_inventory playbook.yaml`
```
PLAY [control_host] ***********************

TASK [Gathering Facts] ***********************
ok: [localhost]

TASK [print users] ***********************
ok: [localhost] => {}

MSG:

users = ['broker', 'broker2', 'broker3']

PLAY RECAP ***********************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

##### ACTUAL RESULTS

Missing `jmespath`

```
bash-4.2# ansible-playbook -i server_inventory playbook.yaml -vvvv
ansible-playbook 2.9.6
  config file = /ansible-dev/swap/ansible.cfg
  configured module search path = ['/ansible-dev/swap/library']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.7.6 (default, Feb 26 2020, 20:54:15) [GCC 7.3.1 20180712 (Red Hat 7.3.1-6)]
Using /ansible-dev/swap/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /ansible-dev/swap/server_inventory as it did not pass its verify_file() method
script declined parsing /ansible-dev/swap/server_inventory as it did not pass its verify_file() method
auto declined parsing /ansible-dev/swap/server_inventory as it did not pass its verify_file() method
Set default localhost to localhost
Parsed /ansible-dev/swap/server_inventory inventory source with ini plugin
Loading callback plugin debug of type stdout, v2.0 from /usr/local/lib/python3.7/site-packages/ansible/plugins/callback/debug.py

PLAYBOOK: playbook.yaml ***********************
Positional arguments: playbook.yaml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/ansible-dev/swap/server_inventory',)
forks: 5
1 plays in playbook.yaml

PLAY [control_host] ***********************

TASK [Gathering Facts] ***********************
task path: /ansible-dev/swap/playbook.yaml:2
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1587713210.496898-92940637298090 `" && echo ansible-tmp-1587713210.496898-92940637298090="` echo /root/.ansible/tmp/ansible-tmp-1587713210.496898-92940637298090 `" ) && sleep 0'
Using module file /usr/local/lib/python3.7/site-packages/ansible/modules/system/setup.py
<localhost> PUT /root/.ansible/tmp/ansible-local-3398m567tl8a/tmprytb4g6g TO /root/.ansible/tmp/ansible-tmp-1587713210.496898-92940637298090/AnsiballZ_setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1587713210.496898-92940637298090/ /root/.ansible/tmp/ansible-tmp-1587713210.496898-92940637298090/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'PYTHONPATH=/usr/local/kaas_virtualenv/lib/python3.7/site-packages /usr/local/kaas_virtualenv/bin/python3 /root/.ansible/tmp/ansible-tmp-1587713210.496898-92940637298090/AnsiballZ_setup.py && sleep 0'
ok: [localhost]
META: ran handlers

TASK [print users] ***********************
task path: /ansible-dev/swap/playbook.yaml:18
fatal: [localhost]: FAILED! => {}

MSG:

You need to install "jmespath" prior to running json_query filter

PLAY RECAP **********************
```

Checking pythom module with virtualenv **activated**:

```
(kaas_virtualenv) bash-4.2# python -c "import jmespath"
(kaas_virtualenv) bash-4.2#
```

Checking pythom module with virtualenv **deactivated**:

```
bash-4.2# python -c "import jmespath"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named jmespath
bash-4.2#
```

The only place where python module exist:

```
bash-4.2# find / -name jmespath
/usr/local/kaas_virtualenv/lib/python3.7/site-packages/jmespath
bash-4.2#
```

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by gustmoge** [comment]
I consider this as a bug and not a user question. Ansible should use the python modules located in the place specified by ansible_python_intrepreter, even if the connection is local. Ansible behaves unpredictable in this use case.

Ansible finds jmespath if environment PYTHONPATH=/usr/local/kaas_virtualenv/lib/python3.7/site-packages is exported. But it does not use the one in the environment: statment.

**Comment by sivel** [comment]
Filter plugins are not affected by `ansible_python_interpreter`. Filter plugins run within the main ansible process, which uses the python that ansible was installed with.

**Comment by gustmoge** [comment]
Thank you for your answer, but that is not entirely true. If you run the same filter but on a remote host (connection=ssh) it uses the ansible_python_interprer and therefore finds the jmespath. 
In my point of view this is an inconsistent behaviour. Please point me to documentation. 
We tried to set the https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-filter-plugin-path but success there either.

**Comment by bcoca** [comment]
@gustmoge incorrect, filters ALWAYS run on the controller, since templating ONLY happens on the controller, otherwise it would require jinja2 + passing all inventory +all variables to the remote, which we don't do for many reasons.
