### ISSUE TITLE
Multi msg debug module call should print messages verbatimly when `debug` stdout_callback plugin is used

### ISSUE THREAD

**Issue by brlin-tw** [ansible/ansible#69149]
Issue moved to [Multi msg debug module call should print messages verbatimly when `debug` stdout_callback plugin is used · Issue #16 · ansible-collections/ansible.posix](https://github.com/ansible-collections/ansible.posix/issues/16).

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/ansible.posix

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
