### ISSUE TITLE
K8s module doesn't use context namespace which oblige complexity in code

### ISSUE THREAD

**Issue by elafontaine** [ansible/ansible#69193]
https://github.com/ansible/ansible/issues/51242#issuecomment-546444097

##### SUMMARY
`kubectl` and `oc` are assuming a default namespace on resources for which you do not define a "metadata.namespace" attribute.  This is the default behaviour of `kubectl` as it use the one defined in the configuration required to authenticate to the kubernetes clusters (the context).  

A use case to have the namespace *not* specified on the resource being passed is that you might want to deploy those resources in differents namepaces depending on the `context` you're in (test namespace, production namespace, dev namespace, etc.).  

This is a pretty usual case where you want to ensure the resource work for a certain scenario in a development cluster and then move to a production cluster which uses a different namespace.  It ease the code complexity as you use the `kubectl` context (which uses "default" by default, but you can point to the namespace you want).

A more extended use case is to have a test cases within the same cluster you're using ; a user with namespaced rights on the namespace but with no access to the cluster wide.  The `context` is namespaced and it's able to do pretty much anything a cluster-admin would be able to do, but only on that namespace (create and patch of a namespace but only that namespace).  This enable to limit the blast radius of an error to only that namespace but still test the behaviour of your code.  It will also prevent extended access into other namespace.

I would like to re-open the [discussion](https://github.com/ansible/ansible/issues/51242) as I believe those strategy are relevants ones in combination with i.e. gitlab kubernetes integration which define a `context` for you to execute kubectl commands which encompass the namespace as well (as is the case with `kubectl` and `oc`).
It's also not an expected behaviour when you have a resource that you were able to deploy with kubectl and oc but not with ansible.

If the decision stays to be "it has to be explicitly defined and maintain in code", than I believe the [documentation should be also explicit](https://docs.ansible.com/ansible/latest/modules/k8s_module.html#parameter-namespace) and be updated to say that all resource requiring a namespace will have to get the namespace defined within "resource definition" or "namespace" field.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
k8s module should use namespace from context when it's not passed to continue behaviour of the wrapper it's supposed to use. (aka `kubectl` and `oc`).

##### ADDITIONAL INFORMATION

```yaml
- name: a ConfigMap for an app without metadata.namespace specified
  k8s:
    state: present
    definition: "{{ lookup('template', 'cm.yaml.j2') }}"
```

**Comment by elafontaine** [comment]
I typed this in 5 minute, so I'm sorry if it may be seen as harmful, but it is not my intention.  Please let me know the place where it might be offensive and I'll adjust them.  

I understand that ansible is open-source and that it's hard to maintain such a product (been using it since 1.0 on solaris servers (yup, patched the ansible on solaris to be able to use it)).

**Comment by mkrizek** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/kubernetes.

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by elafontaine** [comment]
Thanks @mkrizek , I'll open it over there :).
