### ISSUE TITLE
template and copy module not supported 'state' param

### ISSUE THREAD

**Issue by shirou** [ansible/ansible#6929]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4
##### Environment:

Ubuntu 13.10
##### Summary:

template and copy module produce "msg: unsupported parameter for module: state" if use 'state' param. 'state' param is in the file module and from the document, copy and template module can use file param.
##### Steps To Reproduce:

```
    - template: src=test_tmpl.j2 dest=/tmp/ham state=absent
    - copy: src=test_tmpl.j2 dest=/tmp/spam state=absent
```

both failed.
##### Expected Results:

same as file module like absent to delete.
##### Actual Results:

```
failed: [local] => {"failed": true}
msg: unsupported parameter for module: state
```

**Comment by jctanner** [comment]
@shirou  state should be removed the next time we build docs. Thanks!

**Comment by frio** [comment]
As at the 1st of July, `state` is still in the docs for [copy](http://docs.ansible.com/copy_module.html).  I've lost a wee bit of time poring over this.  Please rebuild the docs.

**Comment by gaastonsr** [comment]
So state is not a supported parameter for copy? oh my god. I lost time fixing this too.

Please rebuild the docs.

**Comment by adammenges** [comment]
Same here. Please rebuild the docs.

**Comment by geerlingguy** [comment]
Another ditto :+1: for rebuilding the docs...

**Comment by monooso** [comment]
Add me to the list of people who lost time to this. Please update the (otherwise excellent) documentation.

**Comment by patrickmacarthur** [comment]
It appears that the docs have been rebuilt; however, commit cb13b3036201455ac24bfe8bd10f26eaee777378 appears to have reverted the documentation change made by commit dfdc3b82a02500c8431f24968c94fe99f2cecf86 which fixed this issue.

**Comment by viiiincent** [comment]
Good find @generalpenguin89.  Plus need removing https://github.com/ansible/ansible/blob/devel/library/files/file#L37-L40 from the file module's doc.

**Comment by Lekensteyn** [comment]
Another one bites in the dust.

**Comment by jagibson** [comment]
Any explanation for why state isn't supported?  I want to be able to uninstall my changes, and without state I have to add extra code and use the file module instead.

**Comment by gaastonsr** [comment]
I recommend you to open a new issue if you think it should be supported.
