### ISSUE TITLE
Same-named roles in separate Ansible collections result in first role running every time

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#69307]
##### SUMMARY

If I have two roles, both named `install` (or anything else), in two separate collections, and I use `include_role` to include one, then the other, the first role is actually run _both_ times.

If I use the top level `roles` keyword, only the first role is run; it basically ignores the second role entirely.

This happens whether invoking the role by FQCN _or_ using the `collections` keyword.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

collections
roles

##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = /Users/jgeerling/Downloads/ansible-test/ansible.cfg
  configured module search path = ['/Users/jgeerling/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.7 (default, Apr  9 2020, 17:13:06) [Clang 11.0.3 (clang-1103.0.32.29)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/Users/jgeerling/Downloads/ansible-test/ansible.cfg) = True
COLLECTIONS_PATHS(/Users/jgeerling/Downloads/ansible-test/ansible.cfg) = ['/Users/jgeerling/Downloads/ansible-test']
```

##### OS / ENVIRONMENT

macOS 10.15.4

##### STEPS TO REPRODUCE

Create a new playbook directory. Create an `ansible.cfg` file with the following contents:

```
[defaults]
nocows = True
collections_paths = ./
```

Create the directory `ansible_collections` and `cd` into it.

Run:

    ansible-galaxy collection init local.test
    ansible-galaxy collection init local.test_two

Change directories into each of those collections' `roles` directories, and run the following (once in each collection):

    ansible-galaxy role init myrole

Then edit both roles' `tasks/main.yml` file, adding a task like the following:

```yaml
---
- debug:
    msg: "This is local.test.myrole"
```

(Change the msg to `"This is local.test_two.myrole"` for the second collection.)

Create a new playbook in the main playbook directory alongside `ansible.cfg` called `main.yml` with the following:

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: no

  # Note: The following fails by only running the first role once.
  # roles:
  #   - local.test.myrole
  #   - local.test_two.myrole

  tasks:
    - include_role:
        name: local.test.myrole
    - include_role:
        name: local.test_two.myrole
```

##### EXPECTED RESULTS

Each of the `myrole` roles should run, one after the other.

##### ACTUAL RESULTS

When used with `include_role`, `local.test.myrole` is run twice in a row:

```
PLAY [localhost] *******************************************************************************************************

TASK [include_role : local.test.myrole] ********************************************************************************

TASK [myrole : debug] **************************************************************************************************
ok: [127.0.0.1] => {
    "msg": "This is local.test.myrole"
}

TASK [include_role : local.test_two.myrole] ****************************************************************************

TASK [myrole : debug] **************************************************************************************************
ok: [127.0.0.1] => {
    "msg": "This is local.test.myrole"
}

PLAY RECAP *************************************************************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
```

When used with the `roles` keyword, the invocation of `local.test.myrole` is run, and the invocation of `local.test_two.myrole` is completely ignored:

```
PLAY [localhost] *******************************************************************************************************

TASK [myrole : debug] **************************************************************************************************
ok: [127.0.0.1] => {
    "msg": "This is local.test.myrole"
}

PLAY RECAP *************************************************************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
```

**Comment by geerlingguy** [comment]
I believe @rockaut initially mentioned this to me over the weekend, and then I went to do a little testing with some of my PHP roles, and noticed the same thing happening. It seems like it is a common pattern to have roles named somewhat generically, e.g. `install` or `setup` or `users`, and as people start moving those roles into collections (`my.collection.install`), and more than one collection has the same-named role, things get a bit messy.

**Comment by sivel** [comment]
This has been resolved in devel/2.10, but due to additional features added to make it more useful, it will not be backported.

Can you test whether this works correctly for you in devel?

**Comment by geerlingguy** [comment]
It looks like this is fixed in 2.10. The question is—if we're encouraging more people to move their roles (whether in Galaxy or local) into collections, this is going to start hitting a lot more people in 2.9...

**Comment by rockaut** [comment]
Thank you @geerlingguy for opening the issue as I forgot about it.

If this isn't backported it would be at least useful to mention the issue in the docs somehow. Or more specific the workaround as it's pretty simple: just split the roles in separate plays:

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - include_role:
        name: local.test.myrole

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - include_role:
        name: local.test_two.myrole
```

**Comment by geerlingguy** [comment]
@jimi-c / @sivel - This is marked `waiting_on_contributor`, and I can confirm everything works fine on devel, but I was wondering if you could point to where it was fixed in devel (PR or issue?); just glancing around the closed issues and PRs and couldn't find anything related to keywords like "same name role collection" or "collection not running role identical", but I'm guessing I'm just missing the right keyword.

**Comment by sivel** [comment]
I don't know why this was marked as `waiting_on_contributor`, unless that contributor is me.  But there are still no plans to backport the fix to stable-2.9.

**Comment by geerlingguy** [comment]
Also regarding the workaround ("just split the roles in separate plays"); that is likely going to be very difficult for a number of playbooks, as it would require rearchitecting the play entirely, especially if you rely on sharing certain variables with different parts of the play and/or require installers (or whatever other roles that are duplicate) to run in a certain order, with tasks and potentially other roles in between.

But it is good to know there's a workaround, in case you run into this problem and can't work around it in any other way.

**Comment by geerlingguy** [comment]
It looks like the fix was in here: https://github.com/ansible/ansible/pull/68213

**Comment by jimi-c** [comment]
Per triage, we marked it as waiting since it's something we want, but not a P3 priority. If it's fixed, we can close it and open a new PR to backport it to 2.9.

**Comment by geerlingguy** [comment]
@jimi-c - This issue is fixed in 2.10 (I can confirm that), but the fact that it's broken in 2.9 means I am blocked with moving any of my roles into collections (or, generally, using any roles in any collections), because doing so will start causing this issue to crop up with the many users who are still on 2.9 (and will be, probably, for a while).

**Comment by nitzmahone** [comment]
I'm still +1 for backport, but I don't have time to do it right now, and I think that's kinda where we're all at right now.

**Comment by sivel** [comment]
The backport has been merged: https://github.com/ansible/ansible/pull/70074

Closing this issue.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
