### ISSUE TITLE
package module does not replicate apt behaviour of installing all packages in list "at once"

### ISSUE THREAD

**Issue by zytek** [ansible/ansible#69331]
##### SUMMARY

When installing multiple packages via `apt` module, using list syntax - those are installed "at once". But when using `package` abstraction it seems like `apt` is run for each package in list, separately. Because first package has post-install hooks then upon running second apt - it fails as lock is still held by post-install scripts.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
package

##### ANSIBLE VERSION
```paste below
ansible 2.9.6
```

##### OS / ENVIRONMENT

target: Ubuntu Bionic 18.04 LTS

##### STEPS TO REPRODUCE

Package installatiion from `ansible-chrony` role (from Galaxy)
```yaml
- name: 'Install Chrony'
  become: yes
  package:
    name: 'chrony'
    state: 'present'
  tags:
    - 'chrony-install'
    - 'chrony'
```

##### EXPECTED RESULTS

Both packages installed

##### ACTUAL RESULTS

Error on installation, due to apt holding lock for /var/lib/dpkg/lock-frontend
As seen in error message - `apt` was invoked with just one package name, instead of both packages as once

```
[default]: FAILED! => {"cache_update_time": 1588668343, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'chrony'' failed: E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)\nE: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?\n", "rc": 100, "stderr": "E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)\nE: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?\n", "stderr_lines": ["E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)", "E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?"], "stdout": "", "stdout_lines": []}
```

I've managed to capture ps tree right after installation task failed.
As seen - postinst hooks are still being run

```
root      1726 15.3  1.1 178304 87348 ?        S    09:38   0:00          |           \\_ /usr/bin/python3
root      1737 21.5  0.7 116012 62136 ?        S    09:38   0:00          |               \\_ /usr/bin/apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install chrony
root      1811  1.0  0.0  17512  4232 pts/0    Ss+  09:38   0:00          |                   \\_ /usr/bin/dpkg --force-confdef --force-confold --status-fd 42 --configure --pending
root      1812  0.0  0.0   4624  1684 pts/0    S+   09:38   0:00          |                       \\_ /bin/sh /var/lib/dpkg/info/chrony.postinst configure
root      2094  0.0  0.0   4624  1704 pts/0    S+   09:38   0:00          |                           \\_ /bin/sh /usr/sbin/invoke-rc.d chrony start
```

**Comment by mkrizek** [comment]
You only provided one package which is `chrony` - `name: 'chrony'` which is a string, not a list. Can you elaborate?

needs_info

**Comment by zytek** [comment]
@mkrizek 🤦  you are right. My eyes lied to me and I confused it with tags.

So the reason of package installation failure must be different. How come can this task fail (on apt-lock) but just after it I do see `chrony` postinst running? Any ideas how to debug that?

There is another role run before, making sure that linux-aws is in `latest`. Nothing more, as ansible-chrony is one of the first roles applied to this freshy started instance (packer provisioning). 

This is my way of "catching" this postinst hook:
```
- name: 'Install Chrony'
  become: yes
  package:
    name: 'chrony'
    state: 'present'
  tags:
    - 'chrony-install'
    - 'chrony'
  ignore_error true
  register: chron


- name: ps
  become: yes
  command: ps auxwf
  register: resultps
  when: chron is failed

- debug: msg="{{ resultps.stdout }}"

- name: exit
  command: exit 1
```

**Comment by mkrizek** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
