### ISSUE TITLE
How to  pass params from Ansible to Jenkins Job triggered by Ansible Playbook?

### ISSUE THREAD

**Issue by MimoJSRepo** [ansible/ansible#69379]
Hello everyone,

I checked Ansible documentation, I did not find answers there or anywhere of how I can pass params to the Jenkins Job,so these params should be as an input params to this Jenkins Job and they will be used in that Job, So is there a way to make this happen?

Thank you already for your answers

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by MimoJSRepo** [comment]
That is complicated steps, I wish there could be simpler ways
