### ISSUE TITLE
ovirt_quota : can't set cluster level quotas because it can't decide if global or cluster quotas

### ISSUE THREAD

**Issue by SLoeuillet** [ansible/ansible#69430]
##### SUMMARY
Can't set cluster level quotas with ansible 2.9.7 and ovirtsdk 4.3.4 against RHV 4.3.9 : it can't 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ovirt_quota

##### ANSIBLE VERSION
'''
ansible 2.9.7
config file = None
configured module search path = ['/home/OAD/sloeuillet/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /home/OAD/sloeuillet/venv/lib/python3.6/site-packages/ansible
executable location = /home/OAD/sloeuillet/venv/bin/ansible
python version = 3.6.9 (default, Sep 11 2019, 16:40:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
'''

##### CONFIGURATION
''''''

##### OS / ENVIRONMENT
'''RHEL 7.8 to RHV-M 4.3.9 (based on RHEL 7.8)
Python 3.6
Ansible 2.9.7
ovirt-sdk-python 4.4.3'''

##### STEPS TO REPRODUCE
'''

- name: create quotas
  ovirt_quota:
    auth: "{{ ovirt_auth }}"
    data_center: "{{ rhv_datacenter }}"
    name: "{{ quota.key }}"
    state: "{{ quota.value.state | default('present') }}"

    clusters:
    - name: "{{ quota.value.cluster }}"
      memory: "{{ quota.value.mem | default(128) }}"
      cpu: 10

  with_dict: "{{ rhv_quota }}"
  loop_control:
    loop_var: quota

'''

'''yaml
rhv_quota:
test_cpu_10pct:
cluster: PDCLQAT
cpu: 10
memory: 20.0
'''

##### EXPECTED RESULTS
Set cluster level quotas

##### ACTUAL RESULTS
Complains it can't decide if this quota is for the datacenter (global) or local to cluster

```The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ovirt_quota_payload_C4PPZF/ansible_ovirt_quota_payload.zip/ansible/modules/cloud/ovirt/ovirt_quota.py", line 290, in main
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/services.py", line 20025, in add
    return self._internal_add(limit, headers, query, wait)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 232, in _internal_add
    return future.wait() if wait else future
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 55, in wait
    return self._code(response)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 229, in callback
    self._check_fault(response)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 132, in _check_fault
    self._raise_error(response, body)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 118, in _raise_error
    raise error
Error: Fault reason is "Operation Failed". Fault detail is "[Cannot edit Quota. Limitation can not be configured as specific and general for the same Quota. Please choose whether the limitation should be enforced on the Data Center (global) or for specific storage domain or cluster.]". HTTP response code is 409.
```

Because it seems it does't know if it should set up quota globally (datacenter param is mandatory) or per cluster

**Comment by mkrizek** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ovirt/ovirt-ansible-collection.

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
