### ISSUE TITLE
[ansible.cfg] Add vault_password_file option

### ISSUE THREAD

**Issue by ruudk** [ansible/ansible#6947]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.5.4
##### Environment:

Ubuntu 14.04
##### Summary:

I'm using vaults and have the password stored inside a vault-password-file. I don't like to add the `--vault-password-file=~/.ansible_vault_password.txt` to it every time I run commands (like `ansible` and `ansible-vault`). Would be great if it would read this setting out of `ansible.cfg`
##### Steps To Reproduce:

Add `vault_password_file=file.txt` to `ansible.cfg`

**Comment by gerhard** [comment]
Not sure if this is the best place to post this, but I've put together a quick bash wrapper script around `ansible-vault` that leverages OS X's built-in keychain to store the vault password:

``` sh
#!/usr/bin/env bash

tmpfile=$(mktemp -t vault)

ensure_tmpfile_gets_removed() {
  rm -f $tmpfile
}

trap ensure_tmpfile_gets_removed EXIT

echo $(security find-generic-password -a ansible_vault -w) > $tmpfile

command="$1"
shift
args=$@

ansible-vault $command $args --vault-password-file $tmpfile
```

I have a single ansible_vault password, but it would be trivial to add a password per-file for the more paranoid.

**Comment by ruudk** [comment]
That's awesome :)

**Comment by resmo** [comment]
+1

**Comment by mpdehaan** [comment]
(I do disagree with this needing to be a config option since different projects may have multiple vault password files)

Rather, this can be easily solved with bash aliases.

I do like the above script idea a lot, how about contributing a PR to add it to examples

**Comment by resmo** [comment]
ok, I see, makes sense.

**Comment by ljsommer** [comment]
This would be an incredibly useful feature. Storing this value in a config file is useful on its own but adding vault password files to inventory groups, roles, etc would save a lot of time.

**Comment by adrianlzt** [comment]
+1

**Comment by sivel** [comment]
Also see #7649

**Comment by Petrox** [comment]
```
(I do disagree with this needing to be a config option since different projects may have multiple vault password files)
Rather, this can be easily solved with bash aliases.
```

Different project may have multiple vault password files: true
That's why we've got different ansible.cfg for each project (thus making versioning easier).

So +1 for "Add vault_password_file=file.txt to ansible.cfg"

(Nearly all commandline options should have a cfg alternative. If you don't want to use it, you can, but if someone needs that, it's his/her decision to do.)
