### ISSUE TITLE
'Permission denied' error when copying with sudo

### ISSUE THREAD

**Issue by rightaway** [ansible/ansible#6948]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.4
##### Environment:

Ubuntu 13.10
##### Summary:

When I copy a file using sudo, I get a permission denied error. This is a local setup, where I'm setting up my local machine. So the `src` and `dest` files below are both on the same system. I've seen some similar issues reported, and they were asked to see if they own their `~/.ansible` directory. My `~/.ansible` directory and everything within it is owned by the user I run ansible with, and which also has full access to `sudo`.
##### Steps To Reproduce:

```
- name: Copy file
  sudo: true
  copy: src=/etc/mpd.conf dest=~/.mpd/mpd.conf force=no
```

```
$ ll /etc/mpd.conf 
-rw-r----- 1 mpd audio 16355 2013-05-02 11:09:18 /etc/mpd.conf
```
##### Expected Results:

The file should be copied from /etc/mpd.conf to ~/.mpd/mpd.conf. Running `sudo cp /etc/mpd.conf ~/.mpd/mpd.conf` with the same user I'm running ansible as works fine.
##### Actual Results:

```
fatal: [localhost] => Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 532, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 629, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 815, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/action_plugins/copy.py", line 158, in run
    local_md5 = utils.md5(source_full)
  File "/usr/lib/pymodules/python2.7/ansible/utils/__init__.py", line 570, in md5
    infile = open(filename, 'rb')
IOError: [Errno 13] Permission denied: u'/etc/mpd.conf'


FATAL: all hosts have already failed -- aborting
```

**Comment by jimi-c** [comment]
I believe I see the issue now. The copy module operates by copying the file locally to a remote host only - it does not copy a remote file to another location on the same host. So most likely you'd need to run the ansible-playbook command via sudo too as the current user cannot access the src path you've specified.

That being said, the above traceback should be handled more gracefully, so we'll get that fixed.

**Comment by jimi-c** [comment]
The above patch should correct the issue for you. If you continue seeing any problems related to this issue, or if you have any further questions, please let us know. Thanks!

**Comment by drew1kun** [comment]
I am having the same issue with ansible 2.5. using `become: yes` I assumed that the user should become a root on both local and managed hosts. Is it supposed to work this way or is there any workaround?
