### ISSUE TITLE
Improper traceback when specifying collections namespace

### ISSUE THREAD

**Issue by fosterseth** [ansible/ansible#69503]
##### SUMMARY

I get the same traceback as here
https://github.com/ansible/ansible/issues/69054

```
File "/home/nikos/.local/lib/python3.8/site-packages/ansible/playbook/collectionsearch.py", line 31, in _ensure_default_collection
    collection_list.append('ansible.legacy')
AttributeError: 'AnsibleUnicode' object has no attribute 'append'
```
if my playbook has

```
collections:
    ansible.posix
```
instead of the correct way (with a dash)

```
collections:
    - ansible.posix
```

I get the above traceback

The error is expected of course, but this comment mentions that it should not error at this location

https://github.com/ansible/ansible/issues/69054#issuecomment-616891498 @sivel 

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
```

**Comment by sivel** [comment]
cc @Shrews, oy, looks like another code path.  We might need to shift some more code around.

**Comment by Shrews** [comment]
Hi @fosterseth,

I'm unable to reproduce this. The fix was merged to the devel branch a couple of weeks ago (commit sha ff47d3). Are you certain your repo has this commit? If so, can you provide a simple playbook to reproduce this?

needs_info

**Comment by fosterseth** [comment]
@Shrews @sivel 

thanks for the information -- seems our build did not have this commit. I checked out a local copy of devel and seems everything is fine. I'll close the issue
