### ISSUE TITLE
New feature for log sniffing tools

### ISSUE THREAD

**Issue by AshishVarshneyy** [ansible/ansible#69505]
**SUMMARY**

This feature provides execution time in milliseconds of whole playbook and individual task in a log file in specific formate, that helps log sniffing and monitoring tool to set monitoring and alert related to time.

**ISSUE TYPE**
- Feature Idea

**COMPONENT NAME**
ansible/plugins/callback/logger_runtime.py

**ADDITIONAL INFORMATION**

This feature helps log sniffing tools to set monitoring based on execution time of whole playbook and individual task. 

ansible.cfg
```
callback_whitelist = logger_runtime
```

**Comment by sivel** [comment]
Hi!

Thank you very much for your submission to Ansible. It sincerely means a lot to us that you've taken the time to contribute.

Per recent announcements at AnsibleFest Atlanta 2019, going forward we are no longer accepting new one off modules/plugins, or modules/plugins that create a new category.

However, we recommend looking into providing this functionality through Ansible Galaxy via Ansible Collections. You can find more information about collections at https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html.

I recommend potentially submitting this feature to https://github.com/ansible-collections/community.general

Thank you once again for this and your interest in Ansible!

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by AshishVarshneyy** [comment]
Thank you for your reponse. I will submit new feature in  https://github.com/ansible-collections/community.general
