### ISSUE TITLE
make rpm looks for differently named tar file on devel branch

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#69539]
##### SUMMARY

When building an Ansible rpm using make from the devel branch, it looks for a differently named tar file.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

make rpm
##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Feb 28 2020, 00:00:00) [GCC 10.0.1 20200216 (Red Hat 10.0.1-0.8)
```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 10
```

##### OS / ENVIRONMENT

Fedora 32

##### STEPS TO REPRODUCE

https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-on-rhel-centos-or-fedora
```yaml
$ git clone https://github.com/ansible/ansible.git
$ cd ./ansible
$ make rpm
```

##### EXPECTED RESULTS

no failures

##### ACTUAL RESULTS

```paste below
error: Bad source: /home/user/ansible-rpm/ansible/rpm-build/ansible-2.10.0.dev0.tar.gz: No such file or directory
```
The tar file that is created is named rpm-build/ansible-base-2.10.0.dev0.tar.gz
Building from stable-2.9 does not cause this error.

**Comment by relrod** [comment]
@ldarmbuster Thanks for the report. We are actually dropping support for `make rpm` from 2.10 onward, we just haven't dropped it from the repo yet. For release, we recommend installing from your distro's package manager (the rpm spec for ansible in Fedora and EPEL can be found [here](https://src.fedoraproject.org/rpms/ansible). For development, `pip` (perhaps in a `pyenv` environment) is what most people use.
