### ISSUE TITLE
SSH Windows - Fails to decode stderr when pipelining is disabled

### ISSUE THREAD

**Issue by jborean93** [ansible/ansible#69550]
##### SUMMARY
When using SSH against a Windows host with PowerShell v5 the stderr when pipelining is not being used contains a nested CLIXML message in the stderr. We should be able to handle this correctly and not fail.

Currently I can only explicitly disable pipelining for Windows as it should always be enabled but there is a report where this has happened in the wild so it's not unheard of https://github.com/ansible/awx/issues/6990.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ssh
powershell

##### ANSIBLE VERSION
```paste below
devel
```

##### CONFIGURATION
Not sure yet, need to figure out how pipelining was disabled on the Windows case.

##### OS / ENVIRONMENT
Targeting Windows Server with PowerShell v5 and the SSH default shell is `powershell.exe`

##### STEPS TO REPRODUCE
Not sure yet, can only replicate by connecting to SSH on a WIndows host and manually changing https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/ssh.py#L464 to False.

##### EXPECTED RESULTS
Works just fine

##### ACTUAL RESULTS
Fails because the stderr looks like (see nested CLIXML header)
```paste below
b'#< CLIXML\r\n#< CLIXML\r\n<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs><Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">2</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>')
```

**Comment by jborean93** [comment]
The code that controls whether pipelining is used is https://github.com/ansible/ansible/blob/6fffb0607bf47113496b3e2ffc6ad02779bb495c/lib/ansible/plugins/action/__init__.py#L278-L296.

Going through condition by condition

* [self._connection.has_pipelining](https://github.com/ansible/ansible/blob/6fffb0607bf47113496b3e2ffc6ad02779bb495c/lib/ansible/plugins/action/__init__.py#L285) - Should be `True` based on https://github.com/ansible/ansible/blob/6fffb0607bf47113496b3e2ffc6ad02779bb495c/lib/ansible/plugins/connection/ssh.py#L448
* [self._play_context.pipelining or self._connection.always_pipeline_modules](https://github.com/ansible/ansible/blob/6fffb0607bf47113496b3e2ffc6ad02779bb495c/lib/ansible/plugins/action/__init__.py#L286) - Will be `True` as [always_pipeline_modules = True](https://github.com/ansible/ansible/blob/6fffb0607bf47113496b3e2ffc6ad02779bb495c/lib/ansible/plugins/connection/ssh.py#L464) is set when using `ansible_shell_type=powershell|cmd`
* [module_style == "new"](https://github.com/ansible/ansible/blob/6fffb0607bf47113496b3e2ffc6ad02779bb495c/lib/ansible/plugins/action/__init__.py#L287) - The PowerShell modules come under the "new" umbrella
* [not C.DEFAULT_KEEP_REMOTE_FILES](https://github.com/ansible/ansible/blob/6fffb0607bf47113496b3e2ffc6ad02779bb495c/lib/ansible/plugins/action/__init__.py#L288) - This config option is `False` by default
* [not wrap_async or self._connection.always_pipeline_modules](https://github.com/ansible/ansible/blob/6fffb0607bf47113496b3e2ffc6ad02779bb495c/lib/ansible/plugins/action/__init__.py#L289) - `always_pipeline_modules` is `True` for the powershell|cmd shell plugin
* [ (self._connection.become.name if self._connection.become else '') != 'su',](https://github.com/ansible/ansible/blob/6fffb0607bf47113496b3e2ffc6ad02779bb495c/lib/ansible/plugins/action/__init__.py#L291) - The `su` become plugin doesn't work on Windows so shouldn't be set

So while normally this would never happen, pipelining could be disabled on Windows if

* A binary module is used
* `C.DEFAULT_KEEP_REMOTE_FILES` is set to `True`
* `ansible_become_method: su` is set

So it's technically possible to happen it's definitely not a normal use case. We should still fix up the CLIXML parsing to deal with this scenario though.

**Comment by DanielFarrarCO** [comment]
@jborean93 Thanks for helping with this, confirmed I was getting that error in Windows 2016 because "keep_remote_files" was enabled.
