### ISSUE TITLE
ImportError: No module named pkg_resources

### ISSUE THREAD

**Issue by Mulkave** [ansible/ansible#6957]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.5.3
##### Environment:

On a Vagrant box _(Vagrant 1.5.1)_ on **Mac OS X 19.9.2** running **CentOS release 6.5 (Final)** installed with `yum install ansible`
##### Summary:

When running `ansible-playbook -i development development.yml` returns this error:

``` python
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 22, in <module>
    import pkg_resources
ImportError: No module named pkg_resources
```
##### Steps To Reproduce:

Run `ansible-playbook -i development development.yml`

Where the `development` is something like:

```
[servers]
localhost    ansible_connection=local    ansible_ssh_user=root    ansible_ssh_port=8022
```

and `development.yml` would be:

```

---
-   hosts: all
    sudo: yes
    tasks:
    -   name: install ansible
        yum: name=ansible state=present
        tags: ansible
```

The purpose is to install ansible on a Docker container through ssh. _note: ssh access is working correctly._
##### Expected Results:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [default]

TASK: [install ansible] ******************************************************* 
ok: [default]

PLAY RECAP ******************************************************************** 
default                    : ok=2    changed=0    unreachable=0    failed=0  
```
##### Actual Results:

``` python
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 22, in <module>
    import pkg_resources
ImportError: No module named pkg_resources
```

**Comment by vmanyushin** [comment]
`yum install python-setuptools` should solve your problem

**Comment by Mulkave** [comment]
Solved. Thanks!

**Comment by rgarrigue** [comment]
For information I had the same problem on CentOS 6.5 installing ansible 1.5.3 from epel. Ansible's packaging/rpm/ansible.spec is missing "Requires: python-setuptools" for RHEL > 5

**Comment by RRTUKADIYA** [comment]
**ImportError: No module named pkg_resources:** the solution is to reinstall python pip using the following  Command are under.

**Step: 1** Login in root user.

    sudo su root
**Step: 2** Uninstall python-pip package if existing.

    apt-get purge -y python-pip
**Step: 3** Download files using wget command(File download in `pwd` )

    wget https://bootstrap.pypa.io/get-pip.py
**Step: 4** Run python file.

    python ./get-pip.py
**Step: 5** Finaly exicute installation  command.  

    apt-get install python-pip

**Note:** User must be root.
