### ISSUE TITLE
[mount] Allow "boot" option on all Linux via "noauto"

### ISSUE THREAD

**Issue by darkdragon-001** [ansible/ansible#69588]
##### SUMMARY
Currently `boot` option only applies to _Solaris_. It would be nice to support it on a wider range of operating systems.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
mount

##### ADDITIONAL INFORMATION
- A network share might not be available at boot.
- Non-root mounting is possible when such an entry is present at `fstab`.
- It also allows to circumvent the problem that there is no module which allows mounting without editing fstab (#48134).

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/ansible.posix

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by darkdragon-001** [comment]
Sorry for posting it at the wrong place and thanks for your kind and helpful hints! Moved to ansible-collections/ansible.posix#28.
