### ISSUE TITLE
apt's name argument is not documented

### ISSUE THREAD

**Issue by ktosiek** [ansible/ansible#6960]
##### Issue Type:

Documentation Report
##### Ansible Version:

ansible 1.6 (devel b0556ab1fb) last updated 2014/04/12 08:36:16 (GMT +200)
##### Environment:

N/A
##### Summary:

Apt module has no documented "name" argument. Yum module and the recommendations for module development suggest it should.

**Comment by mpdehaan** [comment]
This is the same as the "pkg" argument, as it is an alias.  I agree we should just show "name" as that's what we more commonly use.

**Comment by mpdehaan** [comment]
Fixed and will be included in next docs update -- thanks!
