### ISSUE TITLE
Unable to set dconf string values using native dconf module

### ISSUE THREAD

**Issue by jamesfreeman959** [ansible/ansible#69644]
##### SUMMARY

I am trying to write a playbook to set the VNC password using dconf for a new server build. It works if I use the dconf CLI tool in the shell, but when I attempt to replicate this in a playbook using the Ansible dconf module, I receive an error about the value I am writing. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

dconf

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = None
  configured module search path = ['/Users/james/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.9/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Mar 11 2020, 00:28:52) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Playbook being run on macOS 10.14.6
Target OS is "CentOS Linux release 8.1.1911 (Core)"

##### STEPS TO REPRODUCE

Success (run directly on CentOS host):
```
$ echo -n test | base64
dGVzdA==
$ dconf write /org/gnome/desktop/remote-access/vnc-password \'dGVzdA==\'
```

Failure - run from playbook:
```
TASK [setvnc : Set VNC password] ******************************************************************************************************************************************************************************
fatal: [test1]: FAILED! => {"changed": false, "msg": "dconf failed while write the value with error: error: The connection is closed\n\nUsage:\n  dconf write KEY VALUE \n\nWrite a new value to a key\n\nArguments:\n  KEY         A key path (starting, but not ending with '/')\n  VALUE       The value to write (in GVariant format)\n\n"}
```

```yaml
- name: Set VNC password
  dconf:
    key: /org/gnome/desktop/remote-access/vnc-password
    value: "'dGVzdA=='"
    state: present
```

##### EXPECTED RESULTS

Appropriate dconf value should be set

##### ACTUAL RESULTS

Playbook hits an error when it comes to set this value.

```paste below
fatal: [test1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "key": "/org/gnome/desktop/remote-access/vnc-password",
            "state": "present",
            "value": "'dGVzdA=='"
        }
    },
    "msg": "dconf failed while write the value with error: error: The connection is closed\n\nUsage:\n  dconf write KEY VALUE \n\nWrite a new value to a key\n\nArguments:\n  KEY         A key path (starting, but not ending with '/')\n  VALUE       The value to write (in GVariant format)\n\n"
}
```

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
