### ISSUE TITLE
Bug: elasticache failure with stacktrace

### ISSUE THREAD

**Issue by mjschultz** [ansible/ansible#6964]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

Ubuntu 12.04
##### Summary:

I have a playbook that starts by asserting that a (named) elasticache instance exists for my AWS account but it fails when it reaches a line that tries to process the security groups (VPC security groups I believe--mine is not in a VPC).
##### Steps To Reproduce:

Here is the task in I'm using:

```
- name: Create elasticache
  local_action:
    module: elasticache
    name: "my-cache"
    state: "present"
    engine: "redis"
    cache_engine_version: "2.6.13"
    node_type: "cache.m1.small"
    num_nodes: "1"
    cache_port: "6379"
    cache_security_groups:
    - "default"
    region: "us-east-1"
    wait: "yes"
  register: elasticache
```
##### Expected Results:

Ansible asserts the elasticache endpoint exists and fills the appropriate variables.
##### Actual Results:

It fails with the following traceback:

``` python
Traceback (most recent call last):
  File "/tmp/ansible-tmp-1397251727.44-74449341587325/elasticache", line 1905, in <module>
    main()
  File "/tmp/ansible-tmp-1397251727.44-74449341587325/elasticache", line 531, in main
    elasticache_manager.ensure_present()
  File "/tmp/ansible-tmp-1397251727.44-74449341587325/elasticache", line 189, in ensure_present
    self.sync()
  File "/tmp/ansible-tmp-1397251727.44-74449341587325/elasticache", line 291, in sync
    if self._requires_modification():
  File "/tmp/ansible-tmp-1397251727.44-74449341587325/elasticache", line 398, in _requires_modification
    for sg in self.data['SecurityGroups']:
TypeError: 'NoneType' object is not iterable
```

Sure enough, going to the python interpreter and running the boto commands gives something like:

```
{
    u'DescribeCacheClustersResponse': {
        u'DescribeCacheClustersResult': {
            u'CacheClusters': [
                {
                    [...],
                    u'SecurityGroups': None
                }
            ]
        }
    }
}
```

**Comment by mjschultz** [comment]
I assume a simple `if self.data['SecurityGroups']:` prior to that would protect against this. Hopefully I can test that out and submit a PR, but there may be a better way.

**Comment by mpdehaan** [comment]
Closing per the above, thank you!
