### ISSUE TITLE
PlaybookExecutor in for loop gives KeyError: 'Requested entry (plugin_type: shell plugin: sh setting: environment ) was not defined in configuration.'

### ISSUE THREAD

**Issue by lexluter1988** [ansible/ansible#69655]
##### SUMMARY
This is more like HowToQuestion. 
So, if I have 2 servers, ssh keys on them, and one playbook.
I run PlaybookExecutor in for loop on them and first one goes fine.
But second just failed at TASK [Gathering Facts]  before even ssh to host.
If I reverse servers, the one who goes first will become fine.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
python api

##### ANSIBLE VERSION
ansible 2.8.5
python 3.5

##### CONFIGURATION
ansible-config dump --only-changed gives nothing

##### OS / ENVIRONMENT
ubuntu 16.04

##### STEPS TO REPRODUCE

This is not 1 on 1 code, cause cannot reproduce production environment.
So I am looking on advice what tweaks or additional env variables could help.
Or where to look.

```python
#!/usr/bin/env python

from ansible import context
from ansible.module_utils.common.collections import ImmutableDict
from ansible.parsing.dataloader import DataLoader
from ansible.utils.display import Display
from ansible.vars.manager import VariableManager
from ansible.inventory.manager import InventoryManager
from ansible.executor.playbook_executor import PlaybookExecutor


class AnsibleRunner:
    def __init__(self, hostname='localhost,'):
        self.loader = DataLoader()

        self.inventory = InventoryManager(loader=self.loader, sources=hostname)
        self.display = Display()
        self.display.verbosity = 2

        context.CLIARGS = ImmutableDict(
            connection='local',
            verbosity=2,
            module_path=None,
            forks=10,
            become=None,
            become_method=None,
            become_user=None,
            host_key_checking=False,
            check=False,
            listhosts=None,
            listtasks=None,
            listtags=None,
            syntax=None,
            start_at_task=None
        )

        self.variable_manager = VariableManager(loader=self.loader, inventory=self.inventory)

        self.passwords = {}

    def run_playbook_file(self, file):
        pbex = PlaybookExecutor(playbooks=[file],
                                inventory=self.inventory,
                                variable_manager=self.variable_manager,
                                loader=self.loader,
                                passwords=self.passwords)

        results = pbex.run()
        return results

servers =  ['localhost,', 'otherhost,']
for i in servers:
    runner = AnsibleRunner(i)
    runner.run_playbook_file('./helloworld.yml')

```

```yaml
- hosts: all
  tasks:
     - shell: echo "hello world!"
```

!important: if I do `servers.reverse()` again the one who goes first will be ok, second - not.
definitely not the servers issue.
maybe something in cache should be hard cleaned.

##### ACTUAL RESULTS
```
venv/lib/python3.5/site-packages/ansible/config/manager.py", line 481, in get_config_value_and_origin
    raise AnsibleError('Requested entry (%s) was not defined in configuration.' % to_native(_get_entry(plugin_type, plugin_name, config)))
ansible.errors.AnsibleError: Requested entry (plugin_type: shell plugin: sh setting: environment ) was not defined in configuration.
```

**Comment by sivel** [comment]
Internal Ansible API
====================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us
to have an active community that is willing to submit feedback so that we may
continue to make Ansible better.

The internal Python API is considered an unsupported aspect of Ansible and this
is not considered a bug unless there is an issue with an Ansible binary
(`ansible`, `ansible-playbook`, `ansible-doc`, etc) or an issue with an external
API such as are provided for the development of plugins (modules, dynamic
inventories, callbacks, strategies, etc).

Thank you once again for this and your interest in Ansible!
