### ISSUE TITLE
Agent forwarding combined with ssh transport fails.

### ISSUE THREAD

**Issue by ggeldenhuis** [ansible/ansible#697]
I ssh from desktop to management server where ansible is run.
Ansible runs on Oracle Linux 5.8

Settings on desktop:
ForwardAgent=yes

The agentforwarding is working because I can ssh to another host that has my key.

running the following command fails:
ansible all -m ping -u adm_geldenhuisg --connection=ssh -v

ukdc1-om-pkg01.mgt.worldpaypp.local | FAILED => Traceback (most recent call last):
  File "/home/adm_geldenhuisg/ansible/lib/ansible/runner/**init**.py", line 444, in _executor
    exec_rc = self._executor_internal(host)
  File "/home/adm_geldenhuisg/ansible/lib/ansible/runner/__init__.py", line 484, in _executor_internal
    return self._executor_internal_inner(host, inject, port)
  File "/home/adm_geldenhuisg/ansible/lib/ansible/runner/__init__.py", line 565, in _executor_internal_inner
    result = self._execute_normal_module(conn, tmp, module_name, inject=inject)
  File "/home/adm_geldenhuisg/ansible/lib/ansible/runner/__init__.py", line 250, in _execute_normal_module
    exec_rc = self._execute_module(conn, tmp, module_name, self.module_args, inject=inject)
  File "/home/adm_geldenhuisg/ansible/lib/ansible/runner/__init__.py", line 212, in _execute_module
    (remote_module_path, is_new_style) = self._copy_module(conn, tmp, module_name, inject)
  File "/home/adm_geldenhuisg/ansible/lib/ansible/runner/__init__.py", line 692, in _copy_module
    self._transfer_str(conn, tmp, module, module_data)
  File "/home/adm_geldenhuisg/ansible/lib/ansible/runner/__init__.py", line 197, in _transfer_str
    conn.put_file(afile, remote)
  File "/home/adm_geldenhuisg/ansible/lib/ansible/runner/connection/ssh.py", line 122, in put_file
    stdout, stderr = p.communicate("put %s %s\n" % (in_path, out_path))
  File "/usr/lib64/python2.6/subprocess.py", line 691, in communicate
    return self._communicate(input)
  File "/usr/lib64/python2.6/subprocess.py", line 1222, in _communicate
    bytes_written = os.write(self.stdin.fileno(), chunk)
OSError: [Errno 32] Broken pipe

The ANSIBLE_HOSTS variable has been set and exported. It containst exactly one host with the fqdn specified.

**Comment by ggeldenhuis** [comment]
ssh -v
OpenSSH_4.3p2, OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008

**Comment by mpdehaan** [comment]
This is using SFTP, can you also also sftp to this host?

```
def put_file(self, in_path, out_path):
    ''' transfer a file from local to remote '''
    if not os.path.exists(in_path):
        raise errors.AnsibleFileNotFound("file or module does not exist: %s" % in_path)
    sftp_cmd = ["sftp"] + self.common_args + [self.host]
    p = subprocess.Popen(sftp_cmd, stdin=subprocess.PIPE,
                         stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = p.communicate("put %s %s\n" % (in_path, out_path))
    if p.returncode != 0:
        raise errors.AnsibleError("failed to transfer file to %s:\n%s\n%s" % (out_path, stdout, stderr))
```

**Comment by ggeldenhuis** [comment]
I don't understand the question. Are you saying it is using sftp instead of ssh and therefore failing or is sftp suppose to be working and because it is not, it is failing?

**Comment by mpdehaan** [comment]
I am saying when your code is failing, it is currently executing sftp.

I am asking whether your sftp works from the command line.

**Comment by ggeldenhuis** [comment]
sftp <hostname> succeeds and gets me the a ftp prompt on the remote server. I have confirmed the existance of the connection by checking netstat listed connections before, during and after.

**Comment by mpdehaan** [comment]
and does running "put" using a file name on your local machine suceed?

**Comment by ggeldenhuis** [comment]
Indeed it does

sftp> put tempfile
Uploading tempfile to /home/adm_geldenhuisg/tempfile
tempfile                                                                    100%    6     0.0KB/s   00:00  
sftp>

**Comment by mpdehaan** [comment]
So the sftp command as ansible is running it is:

```
sftp_cmd = ["sftp"] + self.common_args + [self.host]
```

If you add some debug in the code to print out what "sftp_cmd" is you will get the full argument string.  

Right below that line

```
print "SFTP command=%s" % sftp_cmd
```

 How about trying to see what exactly that outputs, and what that shows when you execute it manually?   it seems that this is what is dying.   It might be additional options are the problem here, and truth be told the code here REALLY should be outputing the command when it fails so you can easily debug it, and we need to fix that.

Thanks for helping debug!

**Comment by ggeldenhuis** [comment]
It's refusing to bring up the same error now... I am not sure what went wrong... it appears to be working now but I get json error.
ImportError: No module named simplejson
which I am fixing my installing the package.

If I manage to recreate the error, I will post more details. I did manage to recreate it but only in the same session and did not try creating a new session.

It would be super cool if I could specify -vvv and get the command being executed. You have mentioned it as outstanding so I am just belaboring the point.

**Comment by mpdehaan** [comment]
Yeah maybe it was getting the wrong user passed in or something, the
error handling should be nicer though, should not present a traceback
in that case.

Having a --vv would be excellent, open a feature ticket for that please?

On Thu, Jul 26, 2012 at 10:23 AM, gjngeldenhuis
reply@reply.github.com
wrote:
