### ISSUE TITLE
1.5.4 :: Precedence issue for variables in arrays and group_vars/all 

### ISSUE THREAD

**Issue by akuznecov** [ansible/ansible#6979]
Hello,
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.4
##### Environment

:: host :: ArchLinux / Debian 7
:: managed :: N/A or any
##### Summary:

Just got issue with variables built on value of other variable defined in global vars (group_vars/all) and then overrided in playbook
Overriden variable value is OK, but array items are not OK - they are still using old-global value
##### Steps To Reproduce:

Part of group_vars/all file:

``` yaml
webserver_root: '/var/www'
webserver_user: 'nginx'
```

Example playbook for debug on local box:

``` yaml
- name: 'Test precedence in array'
  hosts: 127.0.0.1
  connection: local

  vars:

    webserver_root: '/data/www'

    instances:
      - name: "dev"
        docroot: "{{webserver_root}}/dev"
      - name: "stage"
        docroot: "{{webserver_root}}/stage"

  tasks:
   - name: 'debug webserver_root'
     debug: msg="{{ webserver_root }}"

   - name: 'debug instances/items'
     debug: msg="{{ item.docroot }}"
     with_items: instances

   - name: 'debug instances single item'
     debug: msg="{{ instances[0].docroot }}"
```
##### Expected Results:

1.5.3 output is OK and expected: http://pastebin.com/6Nx4QYpf
##### Actual Results:

For 1.5.4 output is: http://pastebin.com/rnk8u5EX
As you see, `items` and `instances[0]` use old value of `webserver_root`

I hope that problem is understandable :)

**Comment by mpdehaan** [comment]
vars_files values should beat inventory, can you clarify where the "old global value" is set and where the variable you are overriding is set?

Thanks!

**Comment by akuznecov** [comment]
1. 'Old global value' is set on `group_vars/all` file
2. New value set on playbook level

vars_files is not set at all

**Comment by jctanner** [comment]
@akuznecov are you able to test against devel? I recently refactored and wrote unit tests for vars_files to assert proper behavior. 

https://github.com/ansible/ansible/tree/devel/hacking#env-setup

**Comment by akuznecov** [comment]
@jctanner just installed devel and got same results as for 1.5.4  :(
http://pastebin.com/FtgwnRD4

**Comment by jctanner** [comment]
@akuznecov sorry, just noticed that your description has nothing to do with the "vars_files" keyword.

**Comment by jimi-c** [comment]
Doing a git bisect shows this is the result of 12b12bba925713eff48c70f4c52b087be226b9ee, where we split up the setup and hostvars caches. I'll dig into this now.

**Comment by jimi-c** [comment]
@akuznecov I believe the above patch should resolve the issue for you. In my testing with your example above the output is correct when the patch is applied.

**Comment by akuznecov** [comment]
@jimi-c, confirm. Works well with devel version
Thanks a lot!

**Comment by jimi-c** [comment]
Thank you!
