### ISSUE TITLE
ios_facts l3_interfaces utils.py normalize_interface returning incorrect or no interface name

### ISSUE THREAD

**Issue by epicanthal** [ansible/ansible#69820]
##### SUMMARY

When gathering ios_facts l3_interfaces:
1.  the wrong interface name is returned if the interface 'description' contains the word 'interface' followed by a space then any word that begins with the two letters that indicate an abbreviated interface type.
2. no ipv4 information is returned if the the interface 'description' contains the word 'interface' followed by a space then any word that does NOT indicate an abbreviated interface type.

My guess is somewhere in [l3_interfaces](https://github.com/ansible/ansible/blob/stable-2.9/lib/ansible/module_utils/network/ios/facts/l3_interfaces/l3_interfaces.py) with how the name is being [determined](https://github.com/ansible/ansible/blob/5192f68f3a056765bbdb6614aea478e4bd977335/lib/ansible/module_utils/network/ios/facts/l3_interfaces/l3_interfaces.py#L87) with the call to [normalize_interface](https://github.com/ansible/ansible/blob/5192f68f3a056765bbdb6614aea478e4bd977335/lib/ansible/module_utils/network/ios/utils/utils.py#L163) the word 'interface' is being picked-up from within the 'description' directive.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_facts
utils.py
normalize_interface

##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = /var/lib/awx/projects/net_compliance/ansible.cfg
  configured module search path = ['/var/lib/awx/projects/net_compliance/library', '/usr/lib/python2.7/site-packages/napalm_ansible/modules', '/usr/lib/python2.7/site-packages/ntc-ansible/library']
  ansible python module location = /root/.local/lib/python3.8/site-packages/ansible
  executable location = /root/.local/bin/ansible
  python version = 3.8.2 (default, May  1 2020, 00:22:45) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(env: ANSIBLE_SSH_PIPELINING) = True
DEFAULT_ACTION_PLUGIN_PATH(/var/lib/awx/projects/net_compliance/ansible.cfg) = ['/usr/lib/python2.7/site-packages/napalm_ansible/plugins/action']
DEFAULT_CALLBACK_WHITELIST(/var/lib/awx/projects/net_compliance/ansible.cfg) = ['profile_roles', 'profile_tasks', 'timer']
DEFAULT_FILTER_PLUGIN_PATH(/var/lib/awx/projects/net_compliance/ansible.cfg) = ['/var/lib/awx/projects/net_compliance/filter_plugins']
DEFAULT_GATHER_TIMEOUT(/var/lib/awx/projects/net_compliance/ansible.cfg) = 30
DEFAULT_HOST_LIST(/var/lib/awx/projects/net_compliance/ansible.cfg) = ['/var/lib/awx/projects/net_compliance/inventory']
DEFAULT_MODULE_PATH(/var/lib/awx/projects/net_compliance/ansible.cfg) = ['/var/lib/awx/projects/net_compliance/library', '/usr/lib/python2.7/site-packages/napalm_ansible/modules', '/usr/lib/python2.7/site-pack
DEFAULT_ROLES_PATH(/var/lib/awx/projects/net_compliance/ansible.cfg) = ['/var/lib/awx/projects/net_compliance/roles']
DEFAULT_STDOUT_CALLBACK(/var/lib/awx/projects/net_compliance/ansible.cfg) = debug
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /etc/ansible/vault_password
HOST_KEY_CHECKING(/var/lib/awx/projects/net_compliance/ansible.cfg) = False
INVENTORY_ENABLED(/var/lib/awx/projects/net_compliance/ansible.cfg) = ['host_list', 'ini', 'yaml', 'script', 'constructed']
PARAMIKO_HOST_KEY_AUTO_ADD(/var/lib/awx/projects/net_compliance/ansible.cfg) = True
PERSISTENT_COMMAND_TIMEOUT(/var/lib/awx/projects/net_compliance/ansible.cfg) = 300
PERSISTENT_CONNECT_TIMEOUT(/var/lib/awx/projects/net_compliance/ansible.cfg) = 300
```

##### OS / ENVIRONMENT

    "ansible_facts": {
        "ansible_net_api": "cliconf",
        "ansible_net_gather_network_resources": [
            "l3_interfaces"
        ],
        "ansible_net_gather_subset": [
            "default"
        ],
        "ansible_net_iostype": "IOS",
        "ansible_net_model": "WS-C3850-12X48U",
        "ansible_net_stacked_models": [
            "WS-C3850-12X48U"
        ],
        "ansible_net_system": "ios",
        "ansible_net_version": "16.3.6"

##### STEPS TO REPRODUCE

Begin with:
1.  Create a vlan interface
2.  Assign a valid ip address and mask

Two Cases:
_**Case1**_:  set a 'description' that contains the word 'interface' followed by a space then any word that begins with two letters that would normally identify an interface type, e.g. 'fo' == FortyGigabitEthernet:

***Notice here within the description is 'interface fo'

```
interface Vlan1
 description this interface for testing
 ip address 10.1.1.10 255.255.255.0
end
```

_**Case2**_:  set a 'description' that contains the word 'interface' followed by a space then any word that DOES NOT begin with two letters that would normally identify an interface type:

***Notice here within the description is 'interface is'

```
interface Vlan1
 description this interface is for testing
 ip address 10.1.1.10 255.255.255.0
end
```

```yaml
- name: Test l3_interface name error
  hosts: ios
  gather_facts: no

  vars:

  tasks:
  - name: Gather ios_facts
    ios_facts:
      gather_subset:
        - min
      gather_network_resources:
        - l3_interfaces
```

##### EXPECTED RESULTS

```
"ansible_network_resources": {
    "l3_interfaces": [
        .......abbreviated.....
        {
            "ipv4": [
                 {
                      "address": "10.1.1.10 255.255.255.0"
                  }
             ],
                      "name": "Vlan1"
         }
    ]
}
```

##### ACTUAL RESULTS

_**Case1**_:
```paste below
"ansible_network_resources": {
    "l3_interfaces": [
        .......abbreviated.....
        {
             "ipv4": [
                  {
                       "address": "10.1.1.10 255.255.255.0"
                  }
             ],
                      "name": "FortyGigabitEthernet"
        }
   ]
}
```

_**Case2**_:
```
"ansible_network_resources": {
    "l3_interfaces": [
        .......abbreviated.....
       {
            "name": "Vlan1"
       }
    ]
}
```

**Comment by jimi-c** [comment]
Thank you very much for your interest in Ansible. 

We're sorry for the inconvenience, however this module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/cisco.ios. Please re-submit this issue there so it can be properly reviewed. 

If you have further questions please stop by IRC or the mailing list: 

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
   * IRC: #ansible or #ansible-devel on irc.freenode.net

Thanks!
