### ISSUE TITLE
unable to ping host nodes from jenkins.

### ISSUE THREAD

**Issue by madhavs2k5** [ansible/ansible#69825]
Hi I am able to ping to my host nodes from control node through putty.
But, if i try to do the same from jenkins then i am facing the below issue..
can you please help me in resolving it.

172.31.15.11 | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).", 
    "unreachable": true
}
<172.31.43.19> (255, '', 'Permission denied (publickey,gssapi-keyex,gssapi-with-mic).\r\n')
172.31.43.19 | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).", 
    "unreachable": true

![image](https://user-images.githubusercontent.com/42546679/83492767-aacac600-a4ab-11ea-967a-51a5c5b37029.png)

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
