### ISSUE TITLE
ansible-playbook cannot find module support code and fail in try/except block when collections is not installed 

### ISSUE THREAD

**Issue by whowutwut** [ansible/ansible#69821]
##### SUMMARY

When a collections is **NOT** installed on the machine, import of a module_utils inside a 
 `try/except` block causes ansible-playbook failure with:

```
fatal: [localhost]: FAILED! => {"msg": "Could not find imported module support code for my_test.  Looked for either helloWorld.py or my_utils.py"}
```

I _think_ that there's actually something else wrong, where it's maybe not throwing the ImportError? I'm not sure...

What I want to do is run the modules directly from a clone of a repo that contains roles/playbooks/plugins, as well as executing the roles on a machine where it's install via collections with a .tar.gz file. 

In the modules we have written, to support collections, we changed the  import statement `from ansible.module_utils.xxx` to `from ansible_collections.namespace.xxx.plugins.module_utils` and if the collections is installed, everything works fine.   If the collection is NOT installed, of course it doesn't find it....  So then I wanted to wrap this import in `try/except` blocks to support both, and that's where I hit this problem.    Running this same try/except logic through `python -m` works, fails under `ansible-playbook`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

collections

##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible/lib/ansible
  executable location = /root/ansible/bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
# ansible-config dump --only-changed
[WARNING]: You are running the development version of Ansible. You should only run
Ansible from "devel" if you are modifying the Ansible engine, or trying out features
under development. This is a rapidly changing source of code and can become unstable at
any point.
#
```

##### OS / ENVIRONMENT

RHEL 7.7, x86_64

##### STEPS TO REPRODUCE

1. Create a collection called `victor.testing`... 
```
ansible-galaxy collection init victor.testing
cd victor/testing
mkdir -p plugins/modules
touch plugins/modules/my_test.py
mkdir -p plugins/module_utils
touch plugins/module_utils/my_utils.py
# create some symlinks relative to this victor/testing path
ln -s plugins/modules library
ln -s plugins/module_utils module_utils
```
   
2. Copy the my_test.py from sample here [developing_modules_general](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html#starting-a-new-module) into `vi plugins/modules/my_test.py`

3. Create simple `vi plugins/module_utils/my_utils.py` file

```python
#!/usr/bin/python

def helloWorld():
    msg="Hello World Return Message"
    print(msg)
    return(msg)

def main():
    helloWorld()

if __name__ == "__main__":
    main()
```

4.  Make some changes to the `plugins/modules/my_test.py` file on the imports...  at line 70 add

```
from ansible.module_utils.basic import AnsibleModule
try:
   from ansible_collections.victor.testing.plugins.module_utils.my_utils import helloWorld
except:
   try:
      from ansible.module_utils.my_utils import helloWorld
   except ImportError:
      from my_utils import helloWorld
```

5. Then run the playbook...  `ansible-playbook test.yml` where test.yml is below... 

```yaml
---
- hosts: localhost

  tasks:
  - name: Test the my_test module.
    my_test:
      name: 'hello'
      new: true
    register: testout
  - name: Debug the my_test module's output
    debug:
      msg: '{{ testout }}'
```

##### EXPECTED RESULTS

Running under ansible playbook, the import on `ansible_collection.victor.testing.plugins.module_utils...` should throw an exception since the collection is NOT installed and those files DO NOT exist 

Then it should fall into an except block if there is any defined and continue. 

##### ACTUAL RESULTS

This msg comes out:
```
fatal: [localhost]: FAILED! => {"msg": "Could not find imported module support code for my_test.  Looked for either helloWorld.py or my_utils.py"}
``` 

I think it's misleading.  If i remove the `plugins` from the line: `from ansible_collections.victor.testing.plugins.module_utils.my_utils import helloWorld` ..  the import does fails and it falls through and continues and works to import relative to the playbook path..   so possibly something with "plugins" in the path??

Also if I copy  this collection into `~/.ansible/collections/ansible_collections/`, than everything works too...    

```paste below
# ansible-playbook test.yml
[WARNING]: You are running the development version of Ansible. You should only run
Ansible from "devel" if you are modifying the Ansible engine, or trying out features
under development. This is a rapidly changing source of code and can become unstable at
any point.
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the
implicit localhost does not match 'all'

PLAY [localhost] ************************************************************************

TASK [Gathering Facts] ******************************************************************
ok: [localhost]

TASK [Test the my_test module.] *********************************************************
fatal: [localhost]: FAILED! => {"msg": "Could not find imported module support code for my_test.  Looked for either helloWorld.py or my_utils.py"}

PLAY RECAP ******************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

That task output `-vvvv` 

```
TASK [Test the my_test module.] *********************************************************
task path: /tmp/DEFECT/victor/testing/test.yml:8
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1591067577.83-22610-145602814348747 && echo ansible-tmp-1591067577.83-22610-145602814348747="` echo /root/.ansible/tmp/ansible-tmp-1591067577.83-22610-145602814348747 `" ) && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1591067577.83-22610-145602814348747/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "msg": "Could not find imported module support code for my_test.  Looked for either helloWorld.py or my_utils.py"
}
```

`python -m` seems to be OK

```
# ./run.python
+ PYTHONPATH=/root/ansible/lib:./library:./module_utils
+ python -m my_test ./args.json
attempt ansible collections...
exception from collections...
attempt ansible.module_utils...
attempt regular import...
Hello World Return Message

{"invocation": {"module_args": {"new": true, "name": "hello"}}, "message": "Hello World Return Message", "changed": true, "original_message": "hello"}
```

**Comment by whowutwut** [comment]
Some more data here, kind of interesting...   If we take ansible_collections out of the imports statement completely...  

```
try:
    from my_utils import helloWorld
    mymsg = "from my_utils"
except BaseException:
    from ansible.module_utils.my_utils import helloWorld
    mymsg = "from ansible.module.utils"
```

This works running: `python -m` .... 
```
# ./run.python
+ PYTHONPATH=/root/ansible/lib:./library:./module_utils
+ python -m my_test ./args.json
from my_utils

{"invocation": {"module_args": {"new": true, "name": "hello"}}, "message": "from my_utils", "changed": true, "original_message": "hello"}
```

and under `ansible-playbook`.... 
```

TASK [Debug the my_test module's output] ********************************************************************************************
ok: [localhost] => {
    "msg": {
        "changed": true,
        "failed": false,
        "message": "from ansible.module.utils", <-----
        "original_message": "hello"
    }
}
```

And changing nothing but adding `from ansible_collections` at the end of the try/except...

```
try:
    from my_utils import helloWorld
    mymsg = "from my_utils"
except BaseException:
    try:
        from ansible.module_utils.my_utils import helloWorld
        mymsg = "from ansible.module.utils"
    except BaseException:
        from ansible_collections.victor.testing.plugins.module_utils.my_utils import  helloWorld
        mymsg = "from ansible_collections"
```

We hit the above error.... 
```

TASK [Test the my_test module.] *****************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "Could not find imported module support code for my_test.  Looked for either helloWorld.py or my_utils.py"}
```

Copying collections dir to `~/.ansible/`  ..   `cp -r victor ~/.ansible/collections/ansible_collections/`  allows the playbook to run through.... but it does not import from ansible_collections....  👇 

```
TASK [Debug the my_test module's output] ********************************************************************************************
ok: [localhost] => {
    "msg": {
        "changed": true,
        "failed": false,
        "message": "from ansible.module.utils", <-------- import from ansible.module_utils
        "original_message": "hello"
    }
}
```

So it seems that any mention of `ansible_collections` cause some sort of pre-processing of the files and fails if it's not installed?  

Is this by design? 

Now thinking this was possibly done on purpose to force the use of collections purely when mentioned in the import?

**Comment by sivel** [comment]
The ansiballz contruction code does not support try/except blocks around module_utils imports, nor are there plans to support this.  As such, you cannot write a module that will work with both collections and without.  You will need to maintain 2 copies of the module.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by whowutwut** [comment]
Thank you for the confirmation!
