### ISSUE TITLE
Talend module

### ISSUE THREAD

**Issue by callumjelliott** [ansible/ansible#69830]
##### SUMMARY
Talend (ESB and Batch integration tool - ESB and Batch integration tool - https://www.talend.com/products/talend-open-studio/) integration with Ansible via a specific module

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Talend TAC integration

##### ADDITIONAL INFORMATION
Talend has a administration API called MetaServlet (https://help.talend.com/reader/wt3LuroKJjOAVRRWmlnFsw/FGEUR1zvb4mnG6REP5s8~g) which allows management of it's services and jobs via https calls.  Is anyone currently building a module for this to integrate with Ansible?  If not, it's something I may make a start on, if anyone else is interested in helping?

**Comment by sivel** [comment]
Hi!

Thank you very much for your submission to Ansible. It sincerely means a lot to us that you've taken the time to contribute.

Per recent announcements at AnsibleFest Atlanta 2019, going forward we are no longer accepting new modules or plugins in this repository.

However, we recommend looking into providing this functionality through Ansible Galaxy via Ansible Collections. You can find more information about collections at https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html.

You may wish to submit this idea to https://github.com/ansible-collections/community.general

Thank you once again for this and your interest in Ansible!

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
