### ISSUE TITLE
Variables overrides even hash-behaviour was set to other than default

### ISSUE THREAD

**Issue by dalisoft** [ansible/ansible#69839]
##### SUMMARY
Variables are not merged, just overrides, even i'm set [hash-behaviour](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-hash-behaviour) to `merge` and `combine`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- Variables
- Include_Vars
- Tasks

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = None
  configured module search path = ['/home/dalisoft/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/linuxbrew/.linuxbrew/Cellar/ansible/2.9.9/libexec/lib/python3.8/site-packages/ansible
  executable location = /home/linuxbrew/.linuxbrew/bin/ansible
  python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]

```

##### CONFIGURATION

```paste below
[defaults]
interpreter_python = auto
hash_behaviour = merge

```

##### OS / ENVIRONMENT

OS: Ubuntu 20.04
Network: Local

##### STEPS TO REPRODUCE

1. Go-to or Clone [this](https://github.com/dalisoft/config/tree/feat/apt-working)
2. Run `sh run-ansible.sh YOUR_PASS` (**I don't need your password, just for playbook**)

NOTE: **Please don't run this playbook on your working machine, this may override your configurations of machine**

##### EXPECTED RESULTS
Getting merged `apt_items` in `debug` [here](https://github.com/dalisoft/config/blob/feat/apt-working/ansible/vars/apt.yml#L15)

```bash
TASK [debug] ********************************************************************************************************************************************************************************************
ok: [127.0.0.1] => {
    "list_merged": [
        "fish",
        "curl",
        "wget",
        "cmake",
        "git",
        "git-lfs",
        "htop",
        "ripgrep",
        "nano",
        "neovim",
        "tmux",
        "nodejs",
        "yarn",
        "golang-go",
        "docker-ce",
        "docker-ce-cli",
        "containerd.io",
        "docker-compose",
        "firefox",
        "krita",
        "octave",
        "vlc",
        "codium",
        "adoptopenjdk-8-hotspot"
    ]
}
```

##### ACTUAL RESULTS
As written [here](https://github.com/dalisoft/config/blob/feat/apt-working/ansible/vars/apt.yml#L15), you should get merged/combined result, but i getting only last defined variable from [here](https://github.com/dalisoft/config/blob/feat/apt-working/ansible/vars/desktop/debian/apt.yml#L2)

```bash
TASK [debug] ********************************************************************************************************************************************************************************************
ok: [127.0.0.1] => {
    "apt_items": [
        "firefox",
        "krita",
        "octave",
        "vlc",
        "codium",
        "adoptopenjdk-8-hotspot"
    ]
}
```

**Comment by sivel** [comment]
`hash_behaviour` has been deprecated, and as such, we are no longer addressing any issues related to it's use.

In the future, the behavior you are looking for will not work at all, as such, you should not rely on automatic merging of data, and instead you will need to explicitly merge using the `combine` filter, or to not merge/combine data at all.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
