### ISSUE TITLE
at_module fails when using become_user due to tmpdir path

### ISSUE THREAD

**Issue by mfettig** [ansible/ansible#69843]
##### SUMMARY
When using the 'at' module with become_user the command fails to run at the specified time since it cannot cd to the ansible-moduletmp directory

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
at

##### ANSIBLE VERSION

```
ansible 2.8.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'profile_tasks']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### STEPS TO REPRODUCE
```yaml
- hosts: webservers
  become: yes
  become_user: www
  tasks:
    - name: Schedule deletion of file
      at:
        command: /bin/rm -f /path/to/file
        count: 1
        units: minutes
```

##### EXPECTED RESULTS
The at job should run successfully

##### ACTUAL RESULTS
After executing that playbook check the at job on the remote server with `at -c <jobNumber>`, it will have a block like this:

```
cd /home/www/\.ansible/tmp/ansible\-moduletmp\-1591113713\.1\-INQokB || {
	 echo 'Execution directory inaccessible' >&2
	 exit 1
}
${SHELL:-/bin/sh} << 'marcinDELIMITER20f59fd4'
/bin/rm -f /path/to/file

marcinDELIMITER20f59fd4
```
It seems that the tmp directory specified no longer exists when the at job tries to run and so it fails every time.

This seems to be specific to using become_user. When using remote_user instead there is no problem - 'at -c <jobNumber>' shows this instead:
```
cd /home/www || {
	 echo 'Execution directory inaccessible' >&2
	 exit 1
}
${SHELL:-/bin/sh} << 'marcinDELIMITER1a17d519'
/bin/rm -f /path/to/file
marcinDELIMITER1a17d519
```
Maybe this is just a documentation issue that the at module cannot work with become_user?

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/ansible.posix

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
