### ISSUE TITLE
ansible-lint crashes with command module

### ISSUE THREAD

**Issue by jorisdobbelsteen** [ansible/ansible#69852]
##### SUMMARY
One step invokes command module using list of arguments passed using argv.
Running the step with ansible-playbook works correctly. However, using ansible-lint to detect common errors fails for this construction.

Output is:
```
  File "/usr/lib/python2.7/site-packages/ansiblelint/rules/CommandsInsteadOfArgumentsRule.py", line 54, in matchtask
    first_cmd_arg = task["action"]["__ansible_arguments__"][0]
IndexError: list index out of range
```

##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
ansible_list, specifically rule 304.

##### ANSIBLE VERSION
```
ansible 2.9.9
  config file = /home/joris/joris2k/ansible.cfg
  configured module search path = [u'/home/joris/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/home/joris/joris2k/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/joris/joris2k/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s
DEFAULT_GATHERING(/home/joris/joris2k/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/joris/joris2k/ansible.cfg) = [u'/home/joris/joris2k/hosts']
DEFAULT_ROLES_PATH(/home/joris/joris2k/ansible.cfg) = [u'/home/joris/joris2k/roles']
INTERPRETER_PYTHON(/home/joris/joris2k/ansible.cfg) = auto
```

##### OS / ENVIRONMENT
CentOS 7

##### STEPS TO REPRODUCE
This requires two files in order to cause the crash.

Create file bug.yml
```
---
- name: Invoke mediawiki install
  command:
    argv:
      - "/usr/bin/echo"
      - "{{ mediawiki_code_dir }}/maintenance/install.php"
```

Create file bug2.yml
```
---
- hosts: all
  tasks:
  - import_tasks: bug.yml
```

Now invoke `ansible-lint bug2.yml`.

##### EXPECTED RESULTS
No error. ansible-lint should not find a issue (as this follows example in documentation)

##### ACTUAL RESULTS
Invoke `ansible-lint -vvvv bug2.yml`
```
Examining bug2.yml of type playbook
Examining /home/joris/joris2k/bug.yml of type tasks
Traceback (most recent call last):
  File "/usr/bin/ansible-lint", line 9, in <module>
    load_entry_point('ansible-lint==3.5.1', 'console_scripts', 'ansible-lint')()
  File "/usr/lib/python2.7/site-packages/ansiblelint/__main__.py", line 176, in main
    matches.extend(runner.run())
  File "/usr/lib/python2.7/site-packages/ansiblelint/__init__.py", line 243, in run
    skip_list=self.skip_list))
  File "/usr/lib/python2.7/site-packages/ansiblelint/__init__.py", line 139, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File "/usr/lib/python2.7/site-packages/ansiblelint/__init__.py", line 70, in matchtasks
    result = self.matchtask(file, task)
  File "/usr/lib/python2.7/site-packages/ansiblelint/rules/CommandsInsteadOfArgumentsRule.py", line 54, in matchtask
    first_cmd_arg = task["action"]["__ansible_arguments__"][0]
IndexError: list index out of range
```

Invoke `ansible-lint -vvvv bug.yml` actually passes:
```
Examining bug.yml of type playbook
```

**Comment by mkrizek** [comment]
Should This Be Filed Elsewhere?
===============================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be something that should be filed against another project or bug tracker:

   * https://github.com/ansible/ansible-lint

If you can stop by the tracker or forum for one of those projects, we'd appreciate it.  

Should you still wish to discuss things further, or if you disagree with our thought process, please stop by one of our two mailing lists:

  * https://groups.google.com/forum/#!forum/ansible-project
  * https://groups.google.com/forum/#!forum/ansible-devel

We'd be happy to discuss things.

Thank you once again!
