### ISSUE TITLE
Persistent spot instances need stopping ability

### ISSUE THREAD

**Issue by jeyrichman** [ansible/ansible#69863]
Hi, I want to be able to stop spot instances like I can do via AWS CLI, AWS SDKs, AWS CloudFormation, AWS Lambda.
This is described here:
https://aws.amazon.com/about-aws/whats-new/2017/09/amazon-ec2-spot-can-now-stop-and-start-your-spot-instances/

And I believe the following needs to be updated:
https://github.com/ansible/ansible/blob/6f83b9aff42331e15c55a171de0a8b001208c18c/lib/ansible/modules/cloud/amazon/ec2.py#L1200

I'm talking about ec2 module specifically instance_initiated_shutdown_behavior: "terminate" should accept value "stop" for spot instances
https://docs.ansible.com/ansible/latest/modules/ec2_module.html#parameter-instance_initiated_shutdown_behavior

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/amazon.aws

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
