### ISSUE TITLE
CISCO IOS upgrade Reload-task issue

### ISSUE THREAD

**Issue by ammarkazmi55** [ansible/ansible#69878]
##### SUMMARY
Hi, i was writing a playbook for upgrading cisco router's IOS.
i have different plays in my playbook.
i am able to upload the image to router successfully but then in reload-play named(reboot ios device) it waits for exact 10 minutes and displays it as "successful", where in actual router stays online(no reboot happens).

when i try to run that reload-play(reboot ios device) in a separate playbook(only for rebooting router) with same code, it works fine. 
but it is not working when i try to run it in main play book(COPY_TFTP_IMAGE)

i tried to search different forums but couldn't get any help.

##### ISSUE TYPE
i am not sure if it is a bug or what.

##### COMPONENT NAME
i am using awx. i have installed/built it on centOS VM in VMWare work station.
[root@localhost ~]# python --version
Python 3.6.8
[root@localhost ~]# ansible --version
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]

##### ANSIBLE VERSION
```[root@localhost ~]# ansible --version
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]


```

##### CONFIGURATION

```[root@localhost ~]# ansible-config dump --only-changed
[root@localhost ~]#


```

##### OS / ENVIRONMENT
i am working on cisco 1800 series router. and the ios i am working on is ,
c1841-advipservicesk9-mz.123-14.T4.bin

##### STEPS TO REPRODUCE

---
- name: COPY_TFTP_IMAGE
  connection: network_cli
  hosts: ROUTER
  gather_facts: false

  tasks:

  tasks:

    - name: Gather facts (ops)
      ios_facts:
      when: ansible_network_os == 'ios'

    - name: UPGRADE IOS IMAGE IF NOT COMPLIANT
      block:
      - name: COPY OVER IOS IMAGE
        cli_command:
          command: 'copy tftp flash:'
          check_all: True
          prompt:
            - 'Address or name of remote host'
            - 'Source filename'
            - 'Destination filename'
          answer:
            - '192.168.0.139'
            - 'c1841-advipservicesk9-mz.123-14.T4.bin'
            - 'c1841-advipservicesk9-mz.123-14.T4.bin'
      - name: config mode
        cli_command:
          command: 'conf t'

      - name: Delete OLD BOOT SEQUENCE
        cli_command:
          command: 'no boot system'

      - name: SET BOOT SEQUENCE
        cli_command:
          command: 'boot system flash:c1841-advipservicesk9-mz.123-14.T4.bin'

      - name: Exit FROM Config Mode
        cli_command:
          command: 'exit'

      when: ansible_net_version != compliant_ios_version

    - name: reboot ios device
      cli_command:
        command: 'reload'
        prompt:
          - 'Save?'
          - 'confirm'
        answer:
         - 'y'
         - 'y'

    - name: reset the connection
      meta: reset_connection

    - name: WAIT FOR ROUTER TO RETURN
      wait_for_connection:
        delay: 90

    - name: GATHER ROUTER FACTS FOR VERIFICATION
      ios_facts:

    - name: ASSERT THAT THE IOS VERSION IS CORRECT
      assert:
        that:
          - compliant_ios_version == ansible_net_version
        fail_msg: " Latest image is not installed "
        success_msg: " Latest image installed "

```

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
it should reboot the router and then perform the image check if the image we have uploaded in installed and boot sequence is set to the newly uploaded image.


##### ACTUAL RESULTS
it shows it completes the play book, but router never rebooted. and in the end image check reported as failed as router didn't reboot and old image remains there when we gather-facts.
below output of my playbook.

PLAY [COPY_TFTP_IMAGE] *********************************************************


TASK [Gather facts (ops)] ******************************************************

[WARNING]: default value for `gather_subset` will be changed to `min` from
`!config` v2.11 onwards
ok: [192.168.0.249]


TASK [COPY OVER IOS IMAGE] *****************************************************

ok: [192.168.0.249]

TASK [config mode] 
*************************************************************

ok: [192.168.0.249]

TASK [Delete OLD BOOT SEQUENCE] 
************************************************

ok: [192.168.0.249]

TASK [SET BOOT SEQUENCE] 
*******************************************************

ok: [192.168.0.249]

TASK [Exit FROM Config Mode] 
***************************************************

ok: [192.168.0.249]

TASK [reboot ios device] 
*******************************************************

ok: [192.168.0.249]

TASK [WAIT FOR ROUTER TO RETURN] 
***********************************************

ok: [192.168.0.249]

TASK [GATHER ROUTER FACTS FOR VERIFICATION] 
************************************

ok: [192.168.0.249]

TASK [ASSERT THAT THE IOS VERSION IS CORRECT] **********************************

fatal: [192.168.0.249]: FAILED! => {
    
"assertion": "compliant_ios_version == ansible_net_version",
    
"changed": false,
    
"evaluated_to": false,
    
"msg": " Latest image is not installed "
}



PLAY RECAP *********************************************************************

192.168.0.249              : ok=9    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   



<!--- Paste verbatim command output between quotes -->
```[root@localhost ~]# ansible-config dump --only-changed
[root@localhost ~]#

```

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/cisco.ios

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
