### ISSUE TITLE
Use Ansible to Install SharePoint Server Updates

### ISSUE THREAD

**Issue by raikhan-mussin** [ansible/ansible#69876]
Hello!
My name is Raikhan.

Maybe someone used Ansible to install Microsoft updates?

We configured Ansible to install Microsoft updates, and this works successfully for all updates, except for SharePoint Server 2013 updates. When we run playbook to install SharePoint Server updates - nothing happens and there are no understandable errors. The server uses UAC, but we tried to work with elevated privileges and also added parameters to the playbook to temporarily disable and enable UAC in the registry. Nothing helps.

Maybe you have fresh thoughts and ideas?

Thanks!
![Ansible - SharePointUpdates](https://user-images.githubusercontent.com/37528587/83736673-cd0f4000-a673-11ea-871b-64d755119123.png)

**Comment by mkrizek** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by raikhan-mussin** [comment]
> 
> # List Information
> 
> Hi!
> 
> Thanks very much for your interest in Ansible. It sincerely means a lot to us.
> 
> This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
> 
>     * IRC: #ansible on irc.freenode.net
> 
>     * mailing list: https://groups.google.com/forum/#!forum/ansible-project
> 
> 
> If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.
> 
> Thank you once again and we look forward to seeing you on the list or IRC. Thanks!

Ок, thanks!
