### ISSUE TITLE
nxos_interfaces doesn't delete virtual interfaces when using state: deleted

### ISSUE THREAD

**Issue by ajsiersema** [ansible/ansible#69894]
##### SUMMARY

Deleting a virtual interface doesn't actually delete the interface from the configuration, but seems to treat it like physical interfaces, it will keep saying changed and will keep sending
```
    "commands": [
        "interface Vlan42",
        "no mtu"
    ],
```

nxos_l3_interfaces explicitly documents that it won't delete virtual interfaces. Which feels counter intuitive to me, but if *_l3_interfaces is about interface attributes and *_interfaces about the actual interface(s) I'd at least expected that after adding another task using nxos_interfaces that this module would remove the virtual interface from the configuration.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nxos_interfaces

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
```

##### CONFIGURATION

```paste below
(no changes)
```

##### OS / ENVIRONMENT

CentOS 8
Cisco Nexus9000 C9300v Chassis
NXOS: version 9.3(3)

##### STEPS TO REPRODUCE

```yaml
- nxos_interfaces:
    config:
      - name: "Vlan42"
        state: deleted
```

##### EXPECTED RESULTS

commands issued:
```
no interface Vlan42
```

##### ACTUAL RESULTS

Interface stays present in configuration, actual commands sent to the switch:
```
    "commands": [
        "interface Vlan42",
        "no mtu"
    ],
```

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/nxos

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
