### ISSUE TITLE
nxos_interfaces doesn't detect virtual interfaces or virtual interface state

### ISSUE THREAD

**Issue by ajsiersema** [ansible/ansible#69893]
##### SUMMARY

Changing the administrative status of a virtual switch interface (SVI or L3 interface) for interfaces in shutdown mode (enabled: no) to enabled: yes doesn't work. 
Changing the configuration for these has no effect:
 ``` 
  system default switchport shutdown
  system default interface-vlan autostate
```

```
show int vl42
   Vlan667 is down (Administratively down), line protocol is down, autostate disabled

show running-config interface Vlan42 all
  interface Vlan42
     no description
     shutdown
```

however without the 'all' the SVI won't show the shutdown whereas regular interfaces will:

```
show running-config | section ^interface
interface Vlan42
   ip address 1.2.3.1/24
interface Ethernet1/1
  shutdown
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nxos_interfaces
ansible/module_utils/network/nxos/facts/interfaces/interfaces.py

'all' is missing from the 2nd show run command for section interface
(included here to show the fix):
```diff
             data = connection.get("show running-config all | incl 'system default switchport'")
-            data += connection.get('show running-config | section ^interface')
+            data += connection.get('show running-config all | section ^interface')

```

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
```

##### CONFIGURATION

```paste below
(no changes)
```

##### OS / ENVIRONMENT

CentOS 8
Cisco Nexus9000 C9300v Chassis
NXOS: version 9.3(3)

##### STEPS TO REPRODUCE

```yaml
- nxos_interfaces:
    config:
      - name: "Vlan42"
        enabled: yes
```

##### EXPECTED RESULTS

'no shutdown' command issues for interfaces that are Administratively down.

##### ACTUAL RESULTS

Interface stays in shutdown, no command issued.

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/nxos

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
