### ISSUE TITLE
Syntax errors with Jinja2 control structures in tasks file

### ISSUE THREAD

**Issue by azmng** [ansible/ansible#69896]
Hi Ansible community,

I am observing syntax error on attempt to use Jinja2 control structures in the tasks file:

**Code**
/opt/ansible/roles/network/tasks/network.yml:
```
{% if publicavailable|default(False) == False and public|default("") == "" and datacenter != "XXX" and datacenter != "YYY" %}
{% set private_interface = ansible_default_ipv4.interface %}
{% else %}
{% set private_interface = ansible_default_ipv4.interface|regex_replace('\d+','')|string + (ansible_default_ipv4.interface|regex_replace('\D+','')|int+1)|string %}
{% endif %}
- name: alias interface on private servers
  template:
    src: if_internal_eth.j2
    dest: /etc/network/interfaces.d/if_{{ private_interface }}_0.cfg
    owner: root
    group: root
    mode: 0644
  when: 'datacenter != "XXX" and datacenter != "YYY" and vlan_prefix2|default("") != ""'
```
**Error**
```
fatal: [host.domain.tld]: FAILED! => {"reason": "Syntax Error while loading YAML.
  found character that cannot start any token

The error appears to have been in /opt/ansible/roles/network/tasks/network.yml: line 52, column 2, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


{% if publicavailable|default(False) == False and public|default(\"\") == \"\" and datacenter != \"XXX\" and datacenter != \"YYY\" %}
 ^ here
"}
```
**Versions**
ansible 2.5.10
python version = 2.7.12
Ubuntu 16.04.3 LTS

Kindly advise!
Thank you,
Alex

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
