### ISSUE TITLE
Ansible loop does not generate any stdout

### ISSUE THREAD

**Issue by deepakramanath** [ansible/ansible#69899]
##### SUMMARY
Ansible loop does not produce any stdout even with verbosity on. This leads to confusion about the successful execution. Surprising this is only noted on the CentOS 7

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.9
  config file = /home/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION

```
DEFAULT_ASK_PASS(/home/ansible/ansible.cfg) = False
DEFAULT_REMOTE_PORT(/home/ansible/ansible.cfg) = 22
DEFAULT_REMOTE_USER(/home/ansible/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/home/ansible/ansible.cfg) = [u'/home/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/ansible/ansible.cfg) = counter_enabled
DEFAULT_TIMEOUT(/home/ansible/ansible.cfg) = 240
DISPLAY_SKIPPED_HOSTS(/home/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/home/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

CentOS Linux release 7.8.2003 (Core)

##### STEPS TO REPRODUCE

```
- name: Print new users being created
  debug:
    msg: "{{ item }}"
  loop:
    - 'user-1'
    - 'user-2'

- name: Create Users
  become: yes
  command: useradd -m "{{ item }}"
  loop:
    - 'user-1'
    - 'user-2'

```

##### EXPECTED RESULTS

Print the stdout of the execution. However, the behaviour is as expected (shows the stdout of the execution) on a Fedora 30

##### ACTUAL RESULTS

```
TASK 1/1 [Gathering Facts] *******************************************************************************************************************************
task path: /home/ansible/ansible-project/playbooks/test_playbook.yml:2
ok: 1/1 [test_box]
META: ran handlers

TASK 2/1 [test_role : Print new users being created] *****************************************************************************************************
task path: /home/ansible/roles/test_role/tasks/loop_testing.yml:2

TASK 3/1 [test_role : Create Users] **********************************************************************************************************************
task path: /home/ansible/roles/test_role/tasks/loop_testing.yml:9
META: ran handlers
META: ran handlers

PLAY RECAP ***********************************************************************************************************************************************
test_box                 : ok=3    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   


```

**Comment by Shrews** [comment]
Your configuration indicates that you are using the `counter_enabled` stdout callback on the CentOS machine which will modify the output being seen. You can change this in your ansible config file by setting `stdout_callback = default` which will set the callback plugin back to the default, giving you the output you expect.

Can you try the above change and let us know if that corrects the problem for you?

needs_info

**Comment by imjoseangel** [comment]
Agree with @Shrews 

IMHO I think this issue should be closed.

**Comment by jimi-c** [comment]
Hi @deepakramanath, per the above we're going to go ahead and close this now.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
   * IRC: #ansible or #ansible-devel on irc.freenode.net

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by deepakramanath** [comment]
What I noticed is that having `stdout_callback = counter_enabled`  does not print any `stdout` only when used with loops.  Otherwise, it does not affect the `stdout`. I still consider this as a bug when `stdout_callback = counter_enabled` behaviour is particularly not well documented.

**Comment by sivel** [comment]
If you wish to file a bug for the `counter_enabled` callback plugin, you can do so at https://github.com/ansible-collections/community.general
