### ISSUE TITLE
Feature request: -vvv

### ISSUE THREAD

**Issue by ggeldenhuis** [ansible/ansible#699]
From a discussion in #697, it would be very handy to have the -v verbosity flag become more verbose if specified multiple times. For example if I specify -vvv it should show the commands it executes or some higher level of detail. -vvv is a bit ambiguous though so a -v flag that takes a level would be more "precise" and that way you could specify specific levels that you would like to see. 389 directory server has a bitmapped flag that allows me to very easily select multiple different levels of logs. For example if I specified 600 I would see debug stream r and if specified 640 I would see debug stream r and w.

**Comment by mpdehaan** [comment]
--verbose already exists, I think the best way to do this is the way that arguments stack, which I believe optparse handles, so -v is verbose -vv is the same as -v -v, etc.

Right now -v could be what it does now (mostly applies to playbooks) and individual SSH commands run would be -vvv and -vv would probably be undefined for now.

I don't see us doing the bitmapped stream thing

**Comment by mpdehaan** [comment]
see my latest email to the list

in short

-v extends playbook output only
-vv has some minimal usage now and will be expanded later
-vvv shows a lot about what SSH operations are occuring
