### ISSUE TITLE
Scaleway inventory plugin custom string variables are not added to inventory

### ISSUE THREAD

**Issue by filviu** [ansible/ansible#69904]
##### SUMMARY

When adding custom variables to the `variables:` section of the scaleway inventory plugin string variables are ignored but numerical variables are passed along.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

scaleway

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = PATH_REDACTED/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(PATH_REDACTED/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(PATH_REDACTED/ansible.cfg) = full_skip
DEFAULT_VAULT_PASSWORD_FILE(PATH_REDACTED/ansible.cfg) = PATH_REDACTED/.NAME_REDACTED
INTERPRETER_PYTHON(PATH_REDACTED/ansible.cfg) = auto_silent
INVENTORY_ENABLED(PATH_REDACTED/ansible.cfg) = ['host_list', 'script', 'auto', 'yaml', 'ini', 'toml']
```

##### OS / ENVIRONMENT

WSL 2 -> Debian 10.4 -> Python 3

##### STEPS TO REPRODUCE

I created a minimal configuration to use scaleway as an inventory source and I wanted to attach custom variables to hosts coming from this source. I noticed that string variables are not passed on.

```yaml
plugin: scaleway
oauth_token: xxx-xxx-xxx-xxx
hostnames:
  - hostname
regions:
  - ams1
  - par1
variables:
  ansible_host: public_ip.address
  ansible_port: 12345
  state: state
  str_foo1: "bar"
  str_foo2: 'bar'
  str_foo3: bar
  num_foo: 123
```

##### EXPECTED RESULTS

I expected at least one of the str_foo variables to appear in `hostvars`

##### ACTUAL RESULTS

```bash
ansible-inventory --list -i hosts-scaleway.yml
[DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad characters in group names by default, this will change, but still be user configurable on 
deprecation. This feature will be removed in version 2.10. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
{
    "_meta": {
        "hostvars": {
            "REDACTED_HOSTNAME": {
                "ansible_host": "REDACTED_IP",
                "ansible_port": "12345",
                "arch": "x86_64",
                "commercial_type": "DEV1-S",
                "hostname": "REDACTED_HOSTNAME",
                "id": "REDACTED_IP",
                "num_foo": "123",
                "organization": "REDACTED_ORG",
                "private_ipv4": "REDACTED_PRIVATEIP",
                "public_ipv4": "REDACTED_PUBLICIP",
                "state": "running",
                "tags": []
            },
```
As you can see `num_foo` is added but none of the `str_foo` variables. I expected either all or none (if custom variables are not supported)

**Comment by mkrizek** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general.

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
