### ISSUE TITLE
ec2_group doesn't allow for target of prefix list - update

### ISSUE THREAD

**Issue by johnpetersjr** [ansible/ansible#69923]
> please re-open issue. 
> it was closed by mistake.
> [this](https://github.com/ryansb/ansible/commit/cb95191d3f589f8ac8f5c594bcf68dad155df37b)  commit has nothing to do with the issue.
> 
> _Originally posted by @BOPOHA in https://github.com/ansible/ansible/issues/31383#issuecomment-484289243_
> 

Was this ever implemented?  I don't see any documentation on this. 

I have the same need - to put a private link of an S3 VPC endpoint as a target egress rule in my security group.

**Comment by mkrizek** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/amazon.aws.

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
