### ISSUE TITLE
"vmware_vm_shell" equivalent capability for Red Hat Virtualization

### ISSUE THREAD

**Issue by shamaljayalath** [ansible/ansible#69958]
##### SUMMARY

Hi Team, We have a customer looking at migrating from VMware to Red Hat virtualization and wanted to use Ansible as their automation platform.

The issue is when provisioning Windows VM on RHV using Windows template via Ansible, for Ansible to communicate further with Guest OS (Windows) WinRM needs to be enabled.

With VMware we used the "vmware_vm_shell" to talk to Windows guest and enabled WinRM and upon enabling WinRM Ansible could connect to the guest OS and carry on with the rest of the configuration.

- name: Enable WinRM to be used with Ansible 
      local_action:
        module: vmware_vm_shell
        hostname: "{{ vcenter_server }}"
        username: Administrator@vsphere.local
        password: "{{ vsphere_password }}" 
        vm_username: Administrator
        vm_password: "{{ vm_password }}"
        vm_id: "{{ vm_name }}"
        vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
        vm_shell_args: "{{ item }}" 
      with_items:
        - '-command "& {Set-ExecutionPolicy Unrestricted}"'
        - '-command "& {Invoke-Expression ((New-Object System.Net.Webclient).DownloadString(\"https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1\"))}"'
        - '-command "& {Set-ExecutionPolicy RemoteSigned}"'

Given "vmware_vm_shell" is not applicable on RHV, how do we enable WinRM during the provisioning of new VM ? Enabling WinRM on the template is less desirable and we would like to configure on the fly.

Having module something similar to "vmware_vm_shell" for RHV would also give us alternative ways to connect to VM if connecting via WinRM/SSH is not an option due to security.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by shamaljayalath** [comment]
Just to highlight second question, how do you recommend enabling WinRM on a Windows VM during running on Red Hat Virtualization  via Ansible playbook ?

**Comment by Akasurde** [comment]
Issue migrated to https://github.com/ansible-collections/community.general/issues/485
