### ISSUE TITLE
ansible ignore some lines on pushing prefix-set configuration 

### ISSUE THREAD

**Issue by RehabRezek** [ansible/ansible#69980]
Hello,
i'm trying to push this prefix-set configuration on cisco ioxr with ansible 
```
prefix-set SWH22
  10.7.182.0/24,
  # EnodeB-S1-SADAT
  10.77.183.0/24,
  # EnodeB-S1-
  10.7.186.0/24,
  # EnodeB-S1-Bosh
  10.77.187.0/24,
  # test
  10.77.188.0/24
end-set
```
which are  ip and comment for each prefix-set 
but in every time ansible ignore the comment line and only ips are pushing to device 
any help if someone tried to push prefix-set before!?

**Comment by Akasurde** [comment]
Issue migrated to https://github.com/ansible-collections/cisco.iosxr/issues/36
