### ISSUE TITLE
issue with handlers with variables in the names

### ISSUE THREAD

**Issue by jjshoe** [ansible/ansible#6999]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

N/A
##### Summary:

Parent task unable to call handlers of child
##### Steps To Reproduce:

```
production.yml
roles/
  upstart/
    tasks/
      main.yml
    templates/
      upstart.conf.j2
  graphite-web/
    handlers/
      main.yml
    meta/
      main.yml
```

roles/upstart/tasks/main.yml:

```
- name: config | {{ name }} | upstart template
  sudo: yes
  template: src=upstart.conf.j2 dest=/etc/init/{{ name }}.conf
  ignore_errors: true
  notify: restart {{ name }}
```

roles/upstart/templates/upstart.conf.j2:

```
description '{{ name }} upstart script'
author 'Joel'

start on (local-filesystems and net-device-up)
stop on shutdown

instance "{{ name }}"

respawn
respawn limit 5 60
limit nofile 165962 165962

script
  {{script}}
end script
```

roles/graphite-web/handlers/main.yml:

```
- name: restart graphite
  sudo: yes
  service: name=graphite-web state=restarted
```

roles/graphite-web/meta/main.yml:

```

---
dependencies:
  - { role: upstart, name: graphite-web, script: "/bin/true" }
```
##### Expected Results:

Play should run without errors, roles/upstart/tasks/main.yml should be able to call a notify on roles/graphite-web/handlers/main.yml
##### Actual Results:

ERROR: change handler (restart graphite-web) is not defined
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by mpdehaan** [comment]
This is a result of the handler name having a variable in it most likely.  We can investigate.

**Comment by rbu** [comment]
Does PR #6755 fix this?

**Comment by lberruti** [comment]
I think that isn't an ansible bug.
You should change:

```
- name: restart graphite
  sudo: yes
  service: name=graphite-web state=restarted
```

with:

```
- name: restart graphite-web
  sudo: yes
  service: name=graphite-web state=restarted
```

**Comment by bcoca** [comment]
closing as this seems like a name mismatch error, not a ansible bug.
