### ISSUE TITLE
`ansible-galaxy collection install` explodes for some collections on `devel`

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansible#70009]
#### SUMMARY

Installing `amazon.aws` collection fails on ansible/ansible@devel, supposedly because of the embedded symlinks:
```console
ERROR! Unexpected Exception, this is probably a bug: "filename 'tests/unit/mod
ules/placebo_recordings/aws_direct_connect_link_aggregation_group/nonexistent_
lag_status' not found"
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible-galaxy CLI

##### ANSIBLE VERSION

devel

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

Running the install should be enough:

```console
$ ANSIBLE_DEBUG=1 ansible-galaxy -vvvv collection install amazon.aws
```

##### EXPECTED RESULTS

The collection install should succeed.

##### ACTUAL RESULTS

```python-traceback
Exception, this is probably a bug: "filename 'tests/unit/modules/placebo_recordings/aws_direct_connect_link_aggregation_group/nonexistent_lag_status' not found"
the full traceback was:
Traceback (most recent call last):
  File "/home/bcoca/work/ansible/bin/ansible-galaxy", line 123, in <module>
    exit_code = cli.run()
  File "/home/bcoca/work/ansible/lib/ansible/cli/galaxy.py", line 490, in run
    context.CLIARGS['func']()
  File "/home/bcoca/work/ansible/lib/ansible/cli/galaxy.py", line 1057, in execute_install
    self._execute_install_collection(collection_requirements, collection_path)
  File "/home/bcoca/work/ansible/lib/ansible/cli/galaxy.py", line 1079, in _execute_install_collection
    no_deps, force, force_with_deps, allow_pre_release=allow_pre_release)
  File "/home/bcoca/work/ansible/lib/ansible/galaxy/collection.py", line 675, in install_collections
    collection.install(output_path, b_temp_path)
  File "/home/bcoca/work/ansible/lib/ansible/galaxy/collection.py", line 250, in install
    self.install_artifact(b_collection_path, b_temp_path)
  File "/home/bcoca/work/ansible/lib/ansible/galaxy/collection.py", line 275, in install_artifact
    _extract_tar_dir(collection_tar, file_name, b_collection_path)
  File "/home/bcoca/work/ansible/lib/ansible/galaxy/collection.py", line 1387, in _extract_tar_dir
    tar_member = tar.getmember(to_native(dirname, errors='surrogate_or_strict'))
  File "/usr/lib/python3.7/tarfile.py", line 1752, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'tests/unit/modules/placebo_recordings/aws_direct_connect_link_aggregation_group/nonexistent_lag_status' not found"
```

**Comment by bcoca** [comment]
bisect: d30fc6c0b359f631130b0e979d9a78a7b3747d48 is the first bad commit

**Comment by webknjaz** [comment]
￼So we should probably cc @jborean93.

**Comment by samdoran** [comment]
As @sivel pointed out, the issue is the actual member in the tar file contains a trailing slash while the call does not:

```
In [18]: t.getmember('tests/unit/modules/placebo_recordings/aws_direct_connect_link_aggregation_group/nonexistent_lag_status/')
Out[18]: <TarInfo 'tests/unit/modules/placebo_recordings/aws_direct_connect_link_aggregation_group/nonexistent_lag_status/' at 0x10c7b4400>
```

**Comment by samdoran** [comment]
What's curious is there are no paths in the `FILES.json` that end with `/` but the archive itself contains some members with trailing slashes:

```
tests/unit/modules/placebo_recordings/aws_direct_connect_link_aggregation_group/nonexistent_lag_status/
tests/unit/modules/placebo_recordings/aws_direct_connect_link_aggregation_group/lag_exists_using_name/
tests/unit/modules/placebo_recordings/aws_direct_connect_link_aggregation_group/delete_lag_with_connections/
tests/unit/modules/placebo_recordings/aws_direct_connect_link_aggregation_group/delete_nonexistent_lag/
tests/unit/modules/placebo_recordings/aws_direct_connect_link_aggregation_group/delete_lag_with_connections_without_force_delete/
tests/unit/modules/placebo_recordings/aws_direct_connect_link_aggregation_group/nonexistent_lag_does_not_exist/
```

I wonder why only some dirs in the archive contain the trailing slash.

**Comment by samdoran** [comment]
I know this tarfile is a bit old. I'd be curious to know the Ansible version used to generate it since I generated a new tarfile with `ansible-galaxy collection build ansible.aws` using `devel` and the commit before https://github.com/ansible/ansible/commit/d30fc6c0b359f631130b0e979d9a78a7b3747d48 and didn't get any tarfile members with trailing slashes. 😕

**Comment by webknjaz** [comment]
> I wonder why only some dirs in the archive contain the trailing slash.

Maybe it's symlinks vs real dirs?

**Comment by samdoran** [comment]
Could be. I would like to look at the code at the time the tarfile was created. I didn't see any tags in `ansible-collections/ansible.aws`.

**Comment by webknjaz** [comment]
> I didn't see any tags in `ansible-collections/ansible.aws`.

Yep, that's what confused me.

**Comment by samdoran** [comment]
I just built the archive with 2.9.9 and didn't get and dirs with trailing slashes. I wonder if it could be symlinks that pointed to references with a trailing slash.

```
lrwxr-xr-x   1 sdoran  staff    13B Jun 11 12:20 test@ -> data_pipeline
lrwxr-xr-x   1 sdoran  staff    12B Jun 11 12:20 test2@ -> ec2_vpc_vpn/
```

I'll test.

**Comment by samdoran** [comment]
No, still don't get members with trailing slashes (created archive with `ansible-galaxy collection build amazon.aws` on Ansible 2.9.9).

```
In [91]: t_with_links.getmember('tests/unit/modules/placebo_recordings/test')
Out[91]: <TarInfo 'tests/unit/modules/placebo_recordings/test' at 0x10dab0ac0>

In [92]: t_with_links.getmember('tests/unit/modules/placebo_recordings/test2')
Out[92]: <TarInfo 'tests/unit/modules/placebo_recordings/test2' at 0x10dadadc0>
```

**Comment by samdoran** [comment]
Anyway, rather than investigate why we have _some_ dirs with trailing `/` in the archive, maybe we could just handle them.

I'm not sure how the `tarfile` library works, but it could have to do with underlying things on my system as to why I can't create tar files with the trailing `/`, or my version of Python, or my version of `tarfile`. Still too many variables.

**Comment by s-hertel** [comment]
changing this line seems to have caused it https://github.com/ansible/ansible/pull/69959/files#diff-2de3c8cc3e7fae814d02b3058f0c8f9eL273

**Comment by samdoran** [comment]
@s-hertel Nice find! Seems that before it was flexible because it accepted dirs with or without the trailing slash. Now, it has to match the member name exactly. Seems like `_extract_tar` should be where the bugfix is.

I would still like to know how to actually create a tar where the `tarfile` library returns the member with a trailing slash, but that's not terribly important at this point.

**Comment by gundalow** [comment]
I wonder if it would be wortg extending the integration tests in ansible/ansible to include various a hand crafted tarball which contains symlinks, trailing slashes, various file modes then ensure `ansible-galaxy install` extracts the files correctly.

**Comment by webknjaz** [comment]
@gundalow that tarball was created two months ago and nobody knows how, there's not even a tag in the repo. So it's hard to know what commit what used in that collection *and* what version of ansible-galaxy was used. Sam mentioned earlier that we're having difficulties reproducing the collection creation part.
But yeah, the general idea is reasonable.

**Comment by jborean93** [comment]
We current do have an integration test for most of those scenarios, the only ones we don’t have is this problem and file modes (there is a unit test for that though).

**Comment by s-hertel** [comment]
I'm able to reproduce by git cloning the current amazon.aws repository, building the collection with latest devel, and then trying to install it.
