### ISSUE TITLE
os_image fails with "openstacksdk is required for this module" when openstacksdk is installed

### ISSUE THREAD

**Issue by cbutterfield** [ansible/ansible#70022]
The is a previous bug report about this that is locked.  That is really where I would like to put this comment.  I've run into this problem in several environments, all of which are RedHat derived - Fedora-31, Fedora-32, CentOS-7 (OpenStack-Train).  Oddly it seems that things were working OK until recently, but I'm not 100% sure of that.

I ONLY run into this when invoking os_server is parallel, not in one operation at a time mode.

In the other ticket - https://github.com/ansible/ansible/issues/68616 - There are hints at various workarounds (e.g. yum install futures - or whatever package has python2/3 futures support) but these do not work for me.  There is a reference that "os_server" has been moved to another group, but that group doesn't seem to have a very good way to search for issues - I could find NO reference to this particular issue at their site.

Lastly, this affects quite a number of distros - and none of them use pip directory, just yum/dnf, although perhaps that invokes pip under the hood.  So references to pip, pipenv, virtualenv etc just don't seem like a good idea - it seems they might not play well with the yum/dnf package management.  Not sure, but the pip/pipenv/virtualenv world is just an approach to package management that I'm not conversant with.

I would love to know the following:
1) What package owns the root cause ?  Is is ansible, or os_server, or something else?
2) Is there a usable workaround for this problem until some upstream solutions makes its way to the distros I have mentioned?  I would settle for modest edits to a modest number of python files if that would help.  But I never read any details of what exactly was going on, just "AHA I see whats happening" but not an explanation that I could find.

Can anybody that understands the root cause, the various workarounds for yum folks and perhaps who to report the problem to chime in with your suggestions?
Thanks!
--Charlie Butterfield

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://opendev.org/openstack/ansible-collections-openstack.git

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by cbutterfield** [comment]
OK I created what they call a story (presumably an allusion to user stories) as https://storyboard.openstack.org/#!/story/2007798
