### ISSUE TITLE
[2]Correct the format of the module names in the test collection

### ISSUE THREAD

**Issue by acozine** [ansible/ansible#70030]
Related to the [June 11 Core IRC meeting.](https://github.com/ansible/community/issues/541#issuecomment-642816342)

##### SUMMARY
In the meeting we agreed that the DOCUMENTATION sections of plugins in collections should use "short form" names, not FQCNs. However, the tests contain mocked collection-based plugins with FQCNs, for example, [here](https://github.com/ansible/ansible/blob/devel/test/integration/targets/ansible-doc/collections/ansible_collections/testns/testcol/plugins/vars/noop_vars_plugin.py#L5).

- [ ] Identify all test plugins with this issue
- [ ] Update them to use short-form names
- [ ] Fix any tests that fail as a result of the change

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
collections
tests

##### ANSIBLE VERSION
2.10

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

**Comment by abadger** [comment]
These are the four I found:

* test/integration/targets/ansible-doc/collections/ansible_collections/testns/testcol/plugins/cache/notjsonfile.py:    cache: testns.testcol.notjsonfile
* test/integration/targets/ansible-doc/collections/ansible_collections/testns/testcol/plugins/inventory/statichost.py:    inventory: testns.testcol.statichost
* test/integration/targets/ansible-doc/collections/ansible_collections/testns/testcol/plugins/lookup/noop.py:    lookup: testns.testcol.noop
* test/integration/targets/ansible-doc/collections/ansible_collections/testns/testcol/plugins/vars/noop_vars_plugin.py:    vars: testns.testcol.noop_vars_plugin

**Comment by samccann** [comment]
Closing this as the Ansible community has adopted FQCN everywhere in docs.
