### ISSUE TITLE
Pip module failed with no module named pip._internal.main

### ISSUE THREAD

**Issue by xoxys** [ansible/ansible#70055]
#### SUMMARY
Using the pip module failed with a traceback error:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named pip._internal.main
fatal: [centos7-droneci]: FAILED! => {"changed": false, "module_stderr": "Shared connection to x.x.x.x closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1592091024.9097793-23223-187212082774892/AnsiballZ_pip\", line 6, in <module>\r\n    from pip._internal.main import main\r\nImportError: No module named pip._internal.main\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

This error occurs even with a very basic playbook like this:

```
- name: test
  hosts: all

  tasks:
    - pip:
        name: requests
```

The playbook was executed on Fedora 32 to a CentOS 7 target host. Pip is installed on the remote system and working properly. Manually `pip install requests` works without issues. Using pip3 executable it is also not working.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
pip

##### ANSIBLE VERSION
```
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['~/ansible/custom_modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.8.3 (default, May 15 2020, 00:00:00) [GCC 10.1.1 20200507 (Red Hat 10.1.1-1)]
```

##### OS / ENVIRONMENT
Fedora 32; Ansible installed with DNF

##### EXPECTED RESULTS
Install given package

**Comment by xoxys** [comment]
Sorry for the noise, I got it to work... I had a (missed) virtualenv folder `~/ansible/custom_modules` within my `custom_modules` folder. After removing it everything is working as expected.

If you like so, we could close the issue, but I don't know if this is really the expected result.

**Comment by mkrizek** [comment]
The traceback provided indicates that the failure was `from pip._internal.main import main` coming from `AnsiballZ_pip`. However there does not appear to be `from pip._internal.main import main` line anywhere in the Ansible codebase.

Does your `'~/ansible/custom_modules'` contain `pip.py` module containing that line by any chance?

needs_info

**Comment by xoxys** [comment]
As I say the issue was related to a subfolder called `env` containing a python virtaulenv. This folder contains a file called `pip` but not `pip.py`.  After deleting the virtualenv subdir everything was working again.

**Comment by mkrizek** [comment]
From the info provided I am going to assume Ansible picked up the custom module called `pip` from `~/ansible/custom_modules`. As such it was an issue with the custom module library rather than in Ansible itself.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by xoxys** [comment]
@mkrizek As I say it is NOT a custom module called `pip` it is a file which will be called `pip` which is part of a default python virtualenv directory. I'm fine with closing the issue, I was just not really sure if this is the intended behavior. Afaik ansible moduls should only loaded from the top level custom module directory, or are subfolders officially supported?

**Comment by mkrizek** [comment]
> As I say it is NOT a custom module called pip it is a file which is called pip which is part of a default python virtualenv directory. 

I understand but if the file is a Python executable Ansible really can't know if it's an Ansible custom module or a file from virtualenv until it runs it so as far as Ansible is concerned it is a custom module, just not a valid one.

> I'm fine with closing the issue, I was just not really sure if this is the intended behavior. Afaik ansible modules should only loaded from the top level custom module directory, or are subfolders officially supported? So regarding this my expectation was subfolders should not affect modules

I don't think it is something that is "officially supported" but AFAIK if `pip` was in a valid python (sub)path for import then it would be considered as a custom module and therefore used as such.
