### ISSUE TITLE
Host variables from host_vars directory not available in hostvars variable

### ISSUE THREAD

**Issue by qpfiffer** [ansible/ansible#7006]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

```
λ:~ cat /etc/issue
Debian GNU/Linux jessie/sid \n \l
```
##### Summary:

I have access to variables defined in the host_vars directory from the role context but they are not available from the hostvars context.
##### Steps To Reproduce:

`host_vars/random_host.yml`:

``` yaml
random_name: test
```

`random_role.yml`:

``` yaml
...
tasks:
  - name: Help
    fail: msg="{{hostvars}} random_test {{random_test}}"
...
```

Result:

```
TASK: [Help] ****************************************************************** 
ok: [random_host] => {
    "msg": { Random junk here that doesn't include my host variable } random_test test
```
##### Expected Results:

I would like it if I could access my `host_vars/` defined variables from the hostvars variable.
##### Actual Results:

See above.

**Comment by mpdehaan** [comment]
This may already be fixed via variable improvements in 1.6, can you check this against devel?  (If this occurs there I'll bump the priority of this one).

Thanks!

**Comment by qpfiffer** [comment]
Does not appear fix as of 632eb18333f5da96375655d71897e33b3c0e9c1a. Same result.

**Comment by jimi-c** [comment]
The above commit should resolve this issue for you, and will be included in the next major release. If you continue seeing any problems related to this issue, or if you have any further questions, please let us know. Thanks!

**Comment by qpfiffer** [comment]
Thanks buddy.
