### ISSUE TITLE
copy module failing to copy to nfs filesystem with SELinux

### ISSUE THREAD

**Issue by IronTetsubo** [ansible/ansible#7009]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4
##### Environment:

RHEL 5/6
##### Summary:

When copying files to NFS, they fail with the following error:

failed: [myhost] => {"cur_context": ["system_u", "object_r", "nfs_t", "s0"], "failed": true, "gid": 0, "group": "root", "input_was": ["system_u", "object_r", "usr_t", "s0"], "md5sum": "mymd5sum", "mode": "0644", "new_context": ["system_u", "object_r", "usr_t", "s0"], "owner": "root", "path": "/my/nfs/mount", "secontext": "system_u:object_r:nfs_t:s0", "size": 1234, "state": "file", "uid": 0}
msg: invalid selinux context
##### Steps To Reproduce:

Use copy module to copy a file to an nfs mount.
##### Expected Results:

The file is copied to the nfs mount.
##### Actual Results:

Error message from above:

failed: [myhost] => {"cur_context": ["system_u", "object_r", "nfs_t", "s0"], "failed": true, "gid": 0, "group": "root", "input_was": ["system_u", "object_r", "usr_t", "s0"], "md5sum": "mymd5sum", "mode": "0644", "new_context": ["system_u", "object_r", "usr_t", "s0"], "owner": "root", "path": "/my/nfs/mount", "secontext": "system_u:object_r:nfs_t:s0", "size": 1234, "state": "file", "uid": 0}
msg: invalid selinux context

I just ran into issue #5632 - "invalid selinux context" with template over ZFS and NFS. The "fix" there was to add better debugging output, but that wasn't really a fix because it's still failing. the core of the issue seems to be that one cannot change context on NFS mounts (for the most part). Ansible should check for contexts of “nfs_t”, and not bother trying to change context if that's the case. I worked around this by forcing the context of the entire mount to the context ansible was trying to set, but that's not a great workaround because if ansible decides to set different contexts based on the files I'm copying over, one or the other will fail. Note I have selinux set to permissive, so the problem is not with selinux (per se).

There are a few potential fixes:
- have some way of allowing users to control the selinux context in the playbook/copy module. this would then let me override ansible and force the "nfs_t" context when copying to nfs. Not great as a user experience because I have to track when/if I'm copying to nfs, but better than nothing. Worth noting this use case in the docs if this is indeed the appropriate fix as it wouldn't be obvious from the error message.
- detecting if a file is destined for a nfs mount, and if so, skip the attempt to change selinux context. this seems to be the approach that puppet took, from my googling: http://projects.puppetlabs.com/issues/1681

**Comment by bcoca** [comment]
i think it should still fail as selinux context will have been changed
unintentionally, but should be a clear message why, also a
ignore_selinux_nfs=true flag for those that REALLY want the update w/o
caring about that consequence.
​

**Comment by IronTetsubo** [comment]
a simpler fix along the path you suggest, bcoca, is having a flag in the copy module that has the copy module skip trying to set the selinux context. This allows the fix to be more flexible than just working for nfs. Of course, worth noting in the copy module docs that said flag would be required for any copies to nfs.

**Comment by jimi-c** [comment]
@IronTetsubo / @bcoca I've pushed up a patch (currently untested) to try and work around this. I currently do not have an NFS mount point with SElinux so I thought I'd see if one of you could test this while I get that setup.

The patch works by checking to see first if the path is on an NFS mount point, and then determines the given selinux context for that mount (from the options in /proc/mounts). The default context per the Red Hat docs are what is shown above in your output.

**Comment by IronTetsubo** [comment]
yup, will try now, let you know.

**Comment by IronTetsubo** [comment]
Okay. so, I duplicated the issue (removed my workaround of forcing the nfs mount to the usr_t context, and found some interesting results. See https://gist.github.com/IronTetsubo/11017902 for the details. For context, "host1" is a rhel 6.5 box, "host2" is a rhel 5.10 box.
- First, I found that this works on rhel5, because by default files on the nfs mount are a context of system_u:object_r:usr_t:s0 instead of system_u:object_r:nfs_t:s0. I didn't realize this before, not sure why I didn't catch that. It still has the same underlying issue (can't chcon nfs files) on rhel5, but it wasn't causing an issue for me. You can see that in the pre-patch output. Point being, I don't think you can default to a context of nfs_t, at least on a rhel5 box. EDIT - this is wrong, see second point. It wasn't working on rhel5, it was just masked because I didn't remount properly. You can default to a context of nfs_t, just not rely on the /proc/mounts data.
- Second, post patch, another task started failing, where it tries to ensure the dir is in place using the file module. this worked fine (on both rhel6 and rhel5) prior to the patch. The directory already existed (from a prior playbook run), and I validated that it does indeed have the usr_t context (on the rhel5 box, the rhel6 box it has nfs_t). It turns out this was due to the fact that I didn't remount the nfs mount on the rhel5 box after removing the context option from /etc/fstab through ansible (see issue #7010). But! it does mean that /proc/mounts is an unreliable source of info - after setting the context in the fstab and remounting, /proc/mounts didn't get updated:

$ grep nfs /proc/mounts
nfs:/export /path nfs rw,sync,vers=3,rsize=32768,wsize=32768,acregmin=0,acregmax=0,acdirmin=0,acdirmax=0,hard,noac,proto=tcp,timeo=600,retrans=2,sec=sys,addr=nfs 0 0
$ grep nfs /etc/fstab
nfs:/export /path nfs rw,bg,hard,nointr,rsize=32768,wsize=32768,tcp,noac,vers=3,timeo=600,actimeo=0,context=system_u:object_r:usr_t:s0 0 0
$ ls -Z /path
drwxr-xr-x  root    root       system_u:object_r:usr_t          file

You may want to rely on /etc/mtab instead? Or otherwise find a better source of data. Let me know if that doesn't make sense, or you need more info.

Let me know if you need more debugging output, or want me to test another patch.

**Comment by jimi-c** [comment]
Perhaps then the proper thing to do would be to just get the context from the mount point itself, rather than rely on either file as one or the other could be wrong.

**Comment by jimi-c** [comment]
@IronTetsubo I've updated my patch to base the selinux context off of the context for the mount point, which should give us an accurate context no matter what the actual mounts say.

**Comment by IronTetsubo** [comment]
Yup, looks good! tested it out, and indeed it's setting the context properly to nfs_t in the case where it's copying to nfs. with this, my playbook succeeds without the workaround (force the context of my nfs mount to usr_t). Thanks! +1 for commit, for what little that's worth. :)

**Comment by jimi-c** [comment]
Great, I've merged the above patch into the devel branch. Thanks!

**Comment by ctgaff** [comment]
This same error occurs with a cifs mount.

"secontext": "system_u:object_r:cifs_t:s0"
"2014-10-29 02:15:43,854 p=32173 u=root |  msg: invalid selinux context"

**Comment by ghost** [comment]
The same error occurs also with an vxfs (Veritas Cluster Filesystem) mount when using the template module

"secontext": "unconfined_u:object_r:vxfs_t:s0"
msg: invalid selinux context
