### ISSUE TITLE
[openstack] no module os_volume_info

### ISSUE THREAD

**Issue by bmillemathias-1a** [ansible/ansible#70097]
##### SUMMARY

There is no openstack module to retrieve the volume info for a specific or a set of volumes.
My use-case would be
- delete all dangling volumes
- create a volume with a set of metadata, then after, look for this and  attach it to a server matching the same key in the metadata.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

openstack

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. The OpenStack plugins are no longer maintained in this repository and have been migrated to https://opendev.org/openstack/ansible-collections-openstack.git

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
