### ISSUE TITLE
`ansible-galaxy collection list` vs site-packages

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#70147]
##### SUMMARY
`ansible-base collection list` doesn't show the packages installed by the new `ansible` package

As a workaround, you need to do:

```
COLLECTION_INSTALL=$(python -c 'import ansible, os.path ; print("%s/../ansible_collections" % os.path.dirname(ansible.__file__))')
ansible-galaxy collection list -p "$COLLECTION_INSTALL"
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-galaxy

##### ANSIBLE VERSION
```paste below
2.10 beta1
```

##### CONFIGURATION
```paste below

```

##### STEPS TO REPRODUCE

1. Install Ansible 2.10.0a1
  https://pypi.python.org/packages/source/a/ansible/ansible-2.10.0a1.tar.gz

2. `ansible-galaxy collection list`

##### ACTUAL RESULTS

```paste below

```

**Comment by jborean93** [comment]
Just an FYI install will also probably be affected and believe the collections aren’t installed as I think the detection mechanism is the same between the two.

**Comment by sivel** [comment]
Not saying anything about whether it should or not, but this has been known for a while, and the original listing functionality was added before this feature.  This will require switching from reading the config in `ansible-galaxy collection` to using `AnsibleCollectionFinder`.

> Just an FYI install will also probably be affected and believe the collections aren’t installed as I think the detection mechanism is the same between the two.

This is probably ok. I don't know that we want new installs consulting those packages collections. At least that is my 2 cents.

**Comment by abadger** [comment]
I concur with sivel on how we want installing to work.  At least, that's how I imagined installing working in my mind up until this point.

**Comment by sivel** [comment]
I think this is all we need to make this list the collections:

```diff
diff --git a/lib/ansible/cli/galaxy.py b/lib/ansible/cli/galaxy.py
index ba2a1a129e..4807b478c9 100644
--- a/lib/ansible/cli/galaxy.py
+++ b/lib/ansible/cli/galaxy.py
@@ -43,6 +43,7 @@ from ansible.parsing.dataloader import DataLoader
 from ansible.parsing.yaml.loader import AnsibleLoader
 from ansible.playbook.role.requirement import RoleRequirement
 from ansible.template import Templar
+from ansible.utils.collection_loader import AnsibleCollectionConfig
 from ansible.utils.display import Display
 from ansible.utils.plugin_docs import get_versioned_doclink
 
@@ -1262,7 +1263,7 @@ class GalaxyCLI(CLI):
 
         collections_search_paths = set(context.CLIARGS['collections_path'])
         collection_name = context.CLIARGS['collection']
-        default_collections_path = C.config.get_configuration_definition('COLLECTIONS_PATHS').get('default')
+        default_collections_path = AnsibleCollectionConfig.collection_paths
 
         warnings = []
         path_found = False
```

**Comment by abadger** [comment]
The patch does not seem to fix collection list:
```
[pts/141@peru /srv/ansible/antsibull2]$ ansible-galaxy collection list          *[master-to-main-rename]  (07:03:59)
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are
modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code
and can become unstable at any point.
[pts/141@peru /srv/ansible/antsibull2]$
```

I have time to get a little more diagnostic info this morning....

**Comment by abadger** [comment]
Discussed with sivel and I have a working fix now.

**Comment by abadger** [comment]
Alright... @sdoran and I discussed this heavily in slack with input from bcoca, shrews, shertel, and sivel (sivel wasn't there for the end).  It changed my mind about whether install should know about site-packages.  Here's the summary:

* download, init, build, and publish are not about the collections on the system at all so they don't need to care about collection_path and whether site-packages is in there.

* list and verify should both take site-packages into account (they're similar in that they're both giving information about things that are available for use inside a playbook.)

* install deals with what's usable inside of a playbook but it's a little different:
  * We **do** want site-packages to be used when figuring out if we should install something vs already installed (reading the current state of the system).  In this context, site-packages is just another directory in the collection search path.
  * There is an annoyance factor here when someone wants to upgrade a collection that's in site-packages.  However, this annoyance exists for a collection installed into any collection path... So we probably need to solve the upgrade use-case as a general problem, not specifically for site-packages.
  * We **do not** want to install to place collections into site-packages (changing the current state of the system).  We currently achieve this by placing site-packages last in the collection search path.

**Comment by abadger** [comment]
@gundalow does this block release?

**Comment by abadger** [comment]
I ask because I think I'm stretched too thin.  My PR implements everything that we care about knowing about site-packages but it reveals that the install/upgrade case needs to be redesigned somewhat.  If we're going to address that, I'll probably need an extra hand to help work on that.

**Comment by gundalow** [comment]
I wonder if it's OK for ansible-base 2.10 that  `ansible-galaxy collection lists` works, though install doesn't

**Comment by samdoran** [comment]
We discussed this it the [IRC Meeting on 2020-07-02 ](https://meetbot.fedoraproject.org/ansible-meeting/2020-07-02/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues543.2020-07-02-15.05.html).

The consensus was that `list` and `verify` will look at `site-packages` in the short term and `install` will completely ignore `site-packages`, even for dependency resolution. Longer term, we can look at implementing a more nuanced and comprehensive solution that includes handling upgrades better.

We will need to add documentation that explains why there is the potential to end up with duplicate collections. For instance, if `community.general` v0.0.8 exists in `site-packages`, and `ansible-galaxy collection install [some collection]` depends on `community.general` v0.0.8, [some collection] as well as `community.general` will be installed into the first `COLLECTIONS_PATHS` directory. This would mean there would be two copies in `ansible-galaxy collection list`: one in `site-packages` and the other in the first `COLLECTIONS_PATHS` directory. That is expected for the short term solution.

**Comment by jamescassell** [comment]
Sounds like a good way to get stuck on an old version of a collection. The new version is "installed" but because once upon a time I installed something depending on community.general, I'm now stuck with that old version (without explicitly upgrading the installed collections.)

**Comment by jborean93** [comment]
Fixed with https://github.com/ansible/ansible/pull/70173. This only includes the short term fix to have `list` show collections in site-packages.
