### ISSUE TITLE
apt_key fails if key id is too long

### ISSUE THREAD

**Issue by berle** [ansible/ansible#7018]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4 (Also applies to head)
##### Environment:

Ubuntu 12.04
##### Summary:

apt_key will fail to find a key in the keychain if the id specified is too long, due to apt-key list not printing keys with their full fingerprint.
##### Steps To Reproduce:

```

---
- name: Add MariaDB key
  apt_key: id="0xcbcb082a1bb943db" url="http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xcbcb082a1bb943db"
```
##### Expected Results:

Key added and verified.
##### Actual Results:

```
msg: key does not seem to have been added
```
##### Suggested Fix:

Perhaps a better way to check for the presence of the key would be apt-key export, which supports using up to the full fingerprint?

**Comment by jjshoe** [comment]
Unable to reproduce when passing in the correct id:

```
---
- name: Add MariaDB key
  sudo: yes
  apt_key: id="1BB943DB" url="http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xcbcb082a1bb943db"
```

**Comment by jjshoe** [comment]
https://github.com/ansible/ansible/pull/7022

**Comment by berle** [comment]
How is that the "correct id" when the apt-key utility itself happily accepts the longer version? If the apt_key module requires a very specific key format, it should give an error if the user does not provide this format. It's not a user-error, nor is it intuitively wrong in any way to specify the key id in a format that apt-key actually allows.

**Comment by jjshoe** [comment]
apt-key list shows 8 digit, not 16 digit. It's possible to skip apt-key, and go straight to gpg, then do logic based on 8 digit vs 16 digit keys, but that would require a large re-write when the 8 digit key will do.

**Comment by berle** [comment]
Yes, I've already explained that in the initial bug report, so there's no need to explain it again. I also suggested how to work around the problem in a way that don't even require making any significant changes, still using apt-key, so I'm not really sure why you're suggesting the only way to fix this is to use gpg directly. Sigh...

**Comment by andreasf** [comment]
I just ran into the same issue. Since only the last 8 digits seem to be interesting, how about:

```
diff --git a/library/packaging/apt_key b/library/packaging/apt_key
index 2308d34..77bbac4 100644
--- a/library/packaging/apt_key
+++ b/library/packaging/apt_key
@@ -210,6 +210,7 @@ def main():
             _ = int(key_id, 16)
             if key_id.startswith('0x'):
                 key_id = key_id[2:]
+            key_id = key_id[-8:].upper()
         except ValueError:
             module.fail_json(msg="Invalid key_id", id=key_id)
```

@jjshoe you could add that [-8:] to your fix for #7022.

**Comment by jjshoe** [comment]
It's not really a "fix" per say, but it's worth sending a PR for. As you can see the submitter closed this issue.

I say it's not a fix, as you could still get a key collision, which is why ultimately logic should be added to support both 8 and 16 digit keys.

**Comment by jjshoe** [comment]
Note, to get 16 digit keys, you need to skip apt-key, and go straight to gpg with --keyid-format long or perhaps even --keyid-format 0xlong
