### ISSUE TITLE
ec_vpc seems broken in devel branch

### ISSUE THREAD

**Issue by evanccnyc** [ansible/ansible#7024]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

Mac OS X 10.7
##### Summary:

ec2_vpc seems broken in devel branch. 
##### Steps To Reproduce:

Use the following ansible code:

```
- hosts: local
  connection: local
  gather_facts: False
  tasks:
  - name: "Provision VPC in {{ aws_region }}"
    local_action:
          module: ec2_vpc
          region: us-east-1
          aws_access_key: XXXX
          aws_secret_key:XXXX
          state: present
          cidr_block: 10.1.0.0/16
          subnets:
                  - cidr: 10.1.10.0/24
                    az: us-east-1a
                  - cidr: 10.1.20.0/24
                    az: us-east-1a
                  - cidr: 10.1.11.0/24
                    az: us-east-1b
                  - cidr: 10.1.21.0/24
                    az: us-east-1b
          internet_gateway: True
          route_tables:
                  - subnets:
                          - 10.1.10.0/24
                          - 10.1.11.0/24
                    routes:
                          - dest: 0.0.0.0/0
                            gw: igw
          wait: yes # Important if you're going to deploy into it now!
    register: vpc
    retries: 5
    tags:
      - vpcsetup
```
##### Expected Results:

Creation of VPC
##### Actual Results:

```
PLAY [local] ****************************************************************** 

TASK: [aws | Provision VPC in us-east-1] ************************************** 
<127.0.0.1> REMOTE_MODULE ec2_vpc cidr_block=10.1.0.0/16 state=present region=us-east-1 aws_access_key=XXXX aws_secret_key=XXXXX
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1397664653.9-270143053036387 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1397664653.9-270143053036387 && echo $HOME/.ansible/tmp/ansible-tmp-1397664653.9-270143053036387']
<127.0.0.1> PUT /var/folders/g6/8qw3hxds44q_xp5hrb82f65h0000gn/T/tmpx43Cfv TO /Users/ecarter/.ansible/tmp/ansible-tmp-1397664653.9-270143053036387/ec2_vpc
<127.0.0.1> EXEC ['/bin/sh', '-c', '/usr/bin/python /Users/ecarter/.ansible/tmp/ansible-tmp-1397664653.9-270143053036387/ec2_vpc; rm -rf /Users/ecarter/.ansible/tmp/ansible-tmp-1397664653.9-270143053036387/ >/dev/null 2>&1']
failed: [127.0.0.1] => {"failed": true, "item": "", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/ecarter/.ansible/tmp/ansible-tmp-1397664653.9-270143053036387/ec2_vpc", line 1966, in <module>
    main()
  File "/Users/ecarter/.ansible/tmp/ansible-tmp-1397664653.9-270143053036387/ec2_vpc", line 599, in main
    (vpc_dict, new_vpc_id, subnets_changed, changed) = create_vpc(module, vpc_conn)
  File "/Users/ecarter/.ansible/tmp/ansible-tmp-1397664653.9-270143053036387/ec2_vpc", line 278, in create_vpc
    previous_vpc = find_vpc(module, vpc_conn, id, cidr_block)
  File "/Users/ecarter/.ansible/tmp/ansible-tmp-1397664653.9-270143053036387/ec2_vpc", line 240, in find_vpc
    if set(resource_tags.items()).issubset(set(vpc_tags.items())):
AttributeError: 'NoneType' object has no attribute 'items'


FATAL: all hosts have already failed -- aborting
```

It looks like if i add resource_tags: { tag1: value1} it works even though the documentation says its not required.

**Comment by jimi-c** [comment]
I believe this patch should fix your issue, if you'd like to test it out:

<pre>
diff --git a/library/cloud/ec2_vpc b/library/cloud/ec2_vpc
index 44d207b..2136a1d 100644
--- a/library/cloud/ec2_vpc
+++ b/library/cloud/ec2_vpc
@@ -223,7 +223,7 @@ def find_vpc(module, vpc_conn, vpc_id=None, cidr=None):
 
     found_vpcs = []
 
-    resource_tags = module.params.get('resource_tags')
+    resource_tags = module.params.get('resource_tags', dict())
 
     # Check for existing VPC by cidr_block or id
     if vpc_id is not None:
@@ -306,7 +306,7 @@ def create_vpc(module, vpc_conn):
     # Done with base VPC, now change to attributes and features.
 
     # Add resource tags
-    vpc_spec_tags = module.params.get('resource_tags')
+    vpc_spec_tags = module.params.get('resource_tags', dict())
     vpc_tags = dict((t.name, t.value) for t in vpc_conn.get_all_tags(filters={'resource-id': vpc.id}))
 
     if not set(vpc_spec_tags.items()).issubset(set(vpc_tags.items())):
</pre>

**Comment by evanccnyc** [comment]
Still getting the same error with the patch applied.

**Comment by jimi-c** [comment]
Revised patch:

<pre>
diff --git a/library/cloud/ec2_vpc b/library/cloud/ec2_vpc
index 44d207b..1bd569f 100644
--- a/library/cloud/ec2_vpc
+++ b/library/cloud/ec2_vpc
@@ -237,7 +237,7 @@ def find_vpc(module, vpc_conn, vpc_id=None, cidr=None):
             vpc_tags = dict((t.name, t.value) for t in vpc_conn.get_all_tags(filters={'resource-id': vpc.id}))
 
             # If the supplied list of ID Tags match a subset of the VPC Tags, we found our VPC
-            if set(resource_tags.items()).issubset(set(vpc_tags.items())):
+            if resource_tags and set(resource_tags.items()).issubset(set(vpc_tags.items())):
                 found_vpcs.append(vpc)
 
     found_vpc = None
@@ -309,7 +309,7 @@ def create_vpc(module, vpc_conn):
     vpc_spec_tags = module.params.get('resource_tags')
     vpc_tags = dict((t.name, t.value) for t in vpc_conn.get_all_tags(filters={'resource-id': vpc.id}))
 
-    if not set(vpc_spec_tags.items()).issubset(set(vpc_tags.items())):
+    if vpc_spec_tags and not set(vpc_spec_tags.items()).issubset(set(vpc_tags.items())):
         new_tags = {}
 
         for (key, value) in set(vpc_spec_tags.items()): 
</pre>

**Comment by evanccnyc** [comment]
Revised patch works for both with resource_tags and without.

**Comment by jimi-c** [comment]
The above commit has been merged into the devel branch, and will be included in the next major release. If you continue seeing any problems related to this issue, or if you have any further questions, please let us know. Thanks!
