### ISSUE TITLE
vmware_vm_inventory add ability to filter returned inventory and inventory groups based on tags

### ISSUE THREAD

**Issue by kendrickluong** [ansible/ansible#70286]
##### SUMMARY
The bundled vmware_vm_inventory plugin does not support features such as filtering vms returned from vmware or dynamically creating inventory groups based on tags. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
vmware_vm_inventory

##### ADDITIONAL INFORMATION
The ansible community seems to have a newer version of this plugin (not sure if its been forked) https://github.com/ansible-collections/vmware/blob/master/plugins/inventory/vmware_vm_inventory.py as we are using this in a corporate production environment it would be preferred if we could pull this down as a bundled plugin.

**Comment by Akasurde** [comment]
Issue migrated to https://github.com/ansible-collections/vmware/issues/261
