### ISSUE TITLE
setup module fails on older OpenSuSE (<12?)

### ISSUE THREAD

**Issue by gmassen** [ansible/ansible#7032]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

OpenSuSE 10-13
##### Summary:

setup module failes on older OpenSuSE versions. Reason: /etc/SuSE-release has only 2 lines instead of 3 as assumed by get_distribution_facts(). The missing line is "CODENAME".
##### Steps To Reproduce:

Get any SuSE distrib, and strip "CODENAME" from /etc/SuSE-release if present. 
##### Expected Results:

No error.
##### Actual Results:

fatal Error: IndexError: list index out of range
line 330, in get_distribution_facts
  self.facts['distribution_release'] = data[2].split('=')[1].strip() 

Fix: check if data[2] exists before assigning.

Note (FYI): the current (13.1) OpenSuSE has this in SuSE-release:"/etc/SuSE-release is deprecated and will be removed in the future, use /etc/os-release instead"

**Comment by Logos01** [comment]
Submitted Pull Request  #7198 to resolve this issue.

**Comment by jimi-c** [comment]
The above pull request has been merged in, and should address this issue. Please let us know if you have any further problems regarding this issue, or if you have any other questions. Thanks!
