### ISSUE TITLE
docker-compose module will modify fact

### ISSUE THREAD

**Issue by bingzhangdai** [ansible/ansible#70325]
##### SUMMARY

docker-compose module will accidentally modify the gathered facts.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_compose

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = /mnt/c/Users/bingzhang/source/repos/cloud-deploy/ansible.cfg
  configured module search path = ['/home/david/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/mnt/c/Users/bingzhang/source/repos/cloud-deploy/ansible.cfg) = True
CACHE_PLUGIN(/mnt/c/Users/bingzhang/source/repos/cloud-deploy/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/mnt/c/Users/bingzhang/source/repos/cloud-deploy/ansible.cfg) = .cache/ansible
CACHE_PLUGIN_TIMEOUT(/mnt/c/Users/bingzhang/source/repos/cloud-deploy/ansible.cfg) = 2592000
DEFAULT_GATHERING(/mnt/c/Users/bingzhang/source/repos/cloud-deploy/ansible.cfg) = smart
DEFAULT_STDOUT_CALLBACK(/mnt/c/Users/bingzhang/source/repos/cloud-deploy/ansible.cfg) = debug
HOST_KEY_CHECKING(/mnt/c/Users/bingzhang/source/repos/cloud-deploy/ansible.cfg) = False
INTERPRETER_PYTHON(/mnt/c/Users/bingzhang/source/repos/cloud-deploy/ansible.cfg) = auto
```

##### OS / ENVIRONMENT

**Local**:
`Linux DAVID-SB2 4.4.0-19041-Microsoft #1-Microsoft Fri Dec 06 14:06:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux`
Python: 3.6.9
**remote**
`Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux`
Python: 3.7.3

##### STEPS TO REPRODUCE

Using `fact_caching = jsonfile` and `fact_caching_connection=.cache/ansible` in ansible.cfg. Then, the gathered facts will be dumped to file in json format.

After running the follow task, (template content does not matter)
```yaml
- name: start mysql with docker-compose
  docker_compose:
    project_name: mysql
    definition: "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"
```
The fact was modified in file. There will be some unwanted lines in the fact cache file, (ignored many other lines in json)
```json
{
    "mysql": {
        "mysql": {
            "cmd": [
                "--default-authentication-plugin=mysql_native_password"
            ],
            "image": "mysql:latest",
            "labels": {
                "com.docker.compose.config-hash": "0905123f394bff41b3f7671207eea058737e4b4b5819a51e3480fd7d552e625c",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "mysql",
                "com.docker.compose.project.config_files": "/tmp/ansible_rmqdfge/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/tmp/ansible_rmqdfge",
                "com.docker.compose.service": "mysql",
                "com.docker.compose.version": "1.26.0"
            },
            "networks": {
                "labo": {
                    "IPAddress": "172.18.0.3",
                    "IPPrefixLen": 16,
                    "aliases": [
                        "db",
                        "database",
                        "mysql",
                        "8cd98486aa72"
                    ],
                    "globalIPv6": "",
                    "globalIPv6PrefixLen": 0,
                    "links": null,
                    "macAddress": "02:42:ac:12:00:03"
                }
            },
            "state": {
                "running": true,
                "status": "running"
            }
        }
    }
}
```
Just because I have an variable with name `mysql`. When rerunning the playbook, the task will fail because `mysql` variable is overwritten by the fact which is read from cache file.

After deleting the cache file, ansible will regather fact and the task will succeed. But next time the playbook will fail again due to the above issue.

##### EXPECTED RESULTS

No lines added to the fact cache file.

##### ACTUAL RESULTS

The fact cache file is modified by docker_compose module.

The added lines have already been pasted.

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
