### ISSUE TITLE
Tags Referecncing a non-tagged variable

### ISSUE THREAD

**Issue by schnipdip** [ansible/ansible#70335]
##### SUMMARY
When running a playbook and calling a specific task within the playbook with 'tags', it's referencing a tasks variables that has no affiliation with the tagged task. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Module: Tags

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```
Play /> ansible-playbook install_pscache.yml --tags 'pscache_template_push'
```
![image](https://user-images.githubusercontent.com/23109762/85900675-3515f980-b7ce-11ea-8399-fe3ab09a4ec8.png)
Task being executed

![image](https://user-images.githubusercontent.com/23109762/85900706-419a5200-b7ce-11ea-81ad-96de3cd01ce8.png)
Error

![image](https://user-images.githubusercontent.com/23109762/85900726-4a8b2380-b7ce-11ea-9b56-551d132e5589.png)
Potential Problem Task

No other given error information when ran with verbosity ( -vvv ).
`current_version_pscache' gets the state of `win_reg_stat`. It's checks to see if the application is installed or not. This reduces the amount of artifacts and unnecessary code execution. It's not a needed variable for `Push Templated PSCACHE Scripts`.

Result:
- Looking for variables that aren't assigned at this task.

Possible Resolution:
- The playbook executes flawlessly when the entire playbook is executed.

UPDATE 6/25/2020:
I was able to get it to work, but only partially. The error is referencing back to a task called:
![image](https://user-images.githubusercontent.com/23109762/85900786-62fb3e00-b7ce-11ea-89d9-8b62bc322f4b.png)

This task is then inheriting current_version_pscache.exists and current_version_pscache.value from:
![image](https://user-images.githubusercontent.com/23109762/85900812-70b0c380-b7ce-11ea-9ee4-3b56397420e9.png)

My major concern right now is :
![image](https://user-images.githubusercontent.com/23109762/85900836-7dcdb280-b7ce-11ea-95e7-0c868a5d9792.png)

This task does not have any conditionals. Therefore, the expected working command should be:
```
Play /> ansible-playbook install_pscache.yml --tags 'pscache_template_push'
```
Not,
```
Play /> ansible-playbook install_pscache.yml --tags 'pscache_check, pscache_template_push

```

##### OS / ENVIRONMENT
RHEL 7

##### EXPECTED RESULTS
 play skips all other tasks in the playbook and executes the "Push Templated PSCACHE Scripts" task.

##### ACTUAL RESULTS

```paste below
Looking for variables that aren't assigned at this task.
```

**Comment by sivel** [comment]
The problem is that `meta` tasks do not support `tags`.  As such your `meta` task is not excluded when using `--tags` on the CLI.

Duplicate of https://github.com/ansible/ansible/issues/64558

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
