### ISSUE TITLE
loop_control pause does not pause the execution of the tasks included using include_tasks

### ISSUE THREAD

**Issue by kruge002** [ansible/ansible#70354]
##### SUMMARY
The "include_tasks" feature with a loop having a loop_control with a pause only pauses the inclusion of the tasks. It does not pause the execution of these tasks which starts after the last task has been included. 
Current behaviour: Include first - Pause - Include second - Pause - Include third - Execute first - Execute second - Execute third.
Expected behaviour: Include first - Execute first - Pause - Include second - Execute second - Pause - Include third - Execute third.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
include_tasks

##### ANSIBLE VERSION
```
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
```
```

##### OS / ENVIRONMENT
CentOS 7

##### STEPS TO REPRODUCE
Run the main playbook defined below:
```
ansible-playbook main.yml
```

```yaml
# main.yml
---
- hosts: localhost
  tasks:

  - debug:
      msg: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S-%N') }}"

  - include_tasks: inner.yml
    loop:
      [1, 2, 3, 4, 5]
    loop_control:
      pause: 2

# inner.yml
- debug:
    msg: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S-%N') }}"
```

##### EXPECTED RESULTS
The pause of the loop_control should separate the execution of the included tasks. You would expect the following sequence of events: Include first task - Execute first task - Pause - Include second task - Execute second task - Pause - Include third task - Execute third task - and so on ...

##### ACTUAL RESULTS
The pause of the loop_control is delaying the inclusion of the tasks only without these tasks being executed yet, The execution of the included tasks only starts after the last task of the loop is included.

The loop has 5 items pausing 2 seconds for each item. The loop_control forces 4 pauses between the 5 items resulting in 8 seconds total wait time. You will notice an 8 seconds delay between the start of the include_tasks and the execution of the first task. The delay between the execution of each task is only tens of seconds.

```
PLAY [localhost] ************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ****************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "2020-06-29-10-52-52-139227299"
}

TASK [include_tasks] ********************************************************************************************************************************************************************************************************************
included: /home/ansible/inner.yml for localhost
included: /home/ansible/inner.yml for localhost
included: /home/ansible/inner.yml for localhost
included: /home/ansible/inner.yml for localhost
included: /home/ansible/inner.yml for localhost

TASK [debug] ****************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "2020-06-29-10-53-00-287204580"
}

TASK [debug] ****************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "2020-06-29-10-53-00-365647232"
}

TASK [debug] ****************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "2020-06-29-10-53-00-448474854"
}

TASK [debug] ****************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "2020-06-29-10-53-00-529006580"
}

TASK [debug] ****************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "2020-06-29-10-53-00-611855457"
}

PLAY RECAP ******************************************************************************************************************************************************************************************************************************
localhost                  : ok=12   changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by sivel** [comment]
This is expected, although to understand why, requires a better understanding of what includes are.

Includes themselves are fake tasks, that are actually just triggers to execute functionality within the execution engine of Ansible.

As such, the `include_tasks` is the actual task, but because it's not a real task, it short circuits the task executor code.  Even if we were to address this currently, it would only introduce a pause between telling Ansible to include the file, and not in executing the tasks within the include.

Roughly the steps of executing an include are:

1. queue the `include_tasks` task
1. In `TaskExecutor` short circuit executing, and just return a special result
1. In `StrategyBase` detect the special result from above
    1. Locate the file specified in the include
    1. Parse the task file
    1. Insert the included tasks into the play iterator
1. Retrieve tasks from play iterator, queue those tasks
1. Back to `TaskExecutor`

To implement this would require a complete overhaul of the include processing, which we have a proposal for at https://github.com/ansible/proposals/issues/136

Closing this in favor of the above proposal.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
