### ISSUE TITLE
zabbix_host fails when try to create with SNMP interface and zabbix 5

### ISSUE THREAD

**Issue by evgenyidf** [ansible/ansible#70383]
##### SUMMARY
Zabbix 5 API has changed their API and now when you add SNMP interfaces, SNMP `details` should be provided too:
```
        "interfaces": [
            {
                "type": 2,
                "main": 1,
                "useip": 1,
                "ip": "10.200.200.6",
                "dns": "",
                "port": "161",
                "details": {
                    "version": 2,
                    "community": "public"
                }
            }
        ],
```
Please update `ansible/modules/monitoring/zabbix/zabbix_host.py`

For reference:
https://www.zabbix.com/forum/zabbix-help/401836-version-5-0-api-host-create
https://docs.ansible.com/ansible/latest/modules/zabbix_host_module.html
https://www.zabbix.com/documentation/current/manual/api/reference/hostinterface/create

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_host monitoring module

##### ANSIBLE VERSION

```paste below
2.9.9
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Mac OS
Python 3.6

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS
Host created/updated

##### ACTUAL RESULTS
Host not updated, ansible fails with error:
```
    "msg": "Failed to create host XXXX.host: (u'Error -32602: Invalid params., Incorrect arguments passed to function. while sending 
    { "params": {"status": 0, "proxy_hostid": 10328, "name": "XXXX.host", "interfaces": [{"ip": "", "useip": 0, "dns": "XXXX.host", "main": 1, "type": 2, "port": "161"}], "tls_connect": 1, "tls_accept": 1, "host": "XXXX.host", "groups": [{"groupid": "21"}]}, "jsonrpc": "2.0", "method": "host.create", "auth": "xxxxx", "id": 1}', -32602)"
}
```

**Comment by Shrews** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.zabbix

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
