### ISSUE TITLE
variable value truncation

### ISSUE THREAD

**Issue by fadishei** [ansible/ansible#7038]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.4, 1.6
##### Environment:

Ubuntu 12.04
##### Summary:

Using the template action, in a very specific case, the variable value is truncated by one last character. I could not find a general rule for the occurrence of this behavior, but in my case a variable value of "21.20" is substituted with "21.2" on the remote host.
##### Steps To Reproduce:

It is easy to reproduce. Define a host like:
`host1 var1=21.20`
Then use the variable var1 inside a template and try to use the template in a playbook.
##### Expected Results:

to see 21.20 in the expanded template on remote host
##### Actual Results:

will see 21.2 in the expanded template on remote host

**Comment by mpdehaan** [comment]
This is because the variable is automatically coerced into an integer.

To avoid this quote the value 

var="21.20"

OR

use group_vars and host_vars files, where you should also quote the value.

**Comment by fadishei** [comment]
Thanks. Using host_vars AND quoting works. But just quoting the value in hosts file still leads to coercing.
