### ISSUE TITLE
ansible-playbook:: allow cli to override `Host:` declaration

### ISSUE THREAD

**Issue by adriansev** [ansible/ansible#70452]
did not find

##### SUMMARY

`--hosts` argument to ansible-playbook that would override the `hosts:` declaration from yml file

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible-playbook

##### ADDITIONAL INFORMATION
this would allow a usage like
`ansible-playbook --host MY_OTHER_HOST_MAYBE_A_TEST_VM playbook_for_production_server.yml`
moreover, this would allow an empty `hosts:` specification in playbooks that not only that would force the usage of `--hosts`
argument but would allow to arbitrary play the playbook

**Comment by gabops** [comment]
Hello,

You have the **--limit** option to limit a host or a subset of hosts. But in case that, for some reason, you want to target a totally different host that does not belong to the targeted one in playbook, the approach I've used and I've seen is:

In playbook:
```yaml
- hosts: "{{ target | default('webservers') }}
```
Then, when calling the playbook:
```bash
ansible-playbook playbook.yml -e target='MY_OTHER_HOST_MAYBE_A_TEST_VM'
```

That way, if no "-e target=" is specified, the playbook will run normally over the hosts defined on the value passed to 'default'.


I hope this helps.

Regards.

**Comment by adriansev** [comment]
Yes, thanks, i was aware of this possibility but it's quite cumbersome to use in cli .. i use (because it seems easier to me) a bash wrapper that would create a temporary playbook with the value of `hosts:` replaced by the provided argument.
My proposal is just for easier usage, as workarounds exists already.
Thanks!

**Comment by bcoca** [comment]
Already possible, with trivial prep:
`ansible-playbook -e myhosts=somethingelse`

with play.yml
```
- hosts: ' {{myhosts|default("normaltarget")}}'
```

**Comment by samdoran** [comment]
Closing per above.
