### ISSUE TITLE
Mysql privs do not support new MariaDB 10.5 permissions like "REPLICATION SLAVE ADMIN"

### ISSUE THREAD

**Issue by robin-anil** [ansible/ansible#70469]
##### SUMMARY
Here are the new permission specified in MariaDB 10.5 
https://mariadb.com/kb/en/grant/#global-privileges

##### COMPONENT NAME
mysql_user

##### ANSIBLE VERSION
```
ansible 2.9.10
  config file = /Users/robinanil/work/production/managed-vms/mariadb-staging/ansible.cfg
  configured module search path = ['/Users/robinanil/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.10/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.3 (default, May 27 2020, 20:54:22) [Clang 11.0.3 (clang-1103.0.32.59)]
```

**Comment by Akasurde** [comment]
Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general

Migrated this issue in the above repository - https://github.com/ansible-collections/community.general/issues/617.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
