### ISSUE TITLE
Windows install of Ansible using pip fails because of pwd module

### ISSUE THREAD

**Issue by s-celles** [ansible/ansible#7049]
##### Issue Type:

Bug Report
##### Ansible Version:

any
##### Environment:

Windows 7 with Cygwin and Anaconda Python
##### Summary:

Windows install of Ansible using pip raises ImportError: no module named pwd
##### Steps To Reproduce:

After having a running python distribution under Window
open command line and type

> pip install ansible
##### Expected Results:

Ansible should be installed
##### Actual Results:

> pip install ansible

raises an Error
ImportError: no module named pwd

> pip install pwd

raises
Could not find any downloads that satisfy the requirement pwd

Maybe it could be fixed shadowing pwd 
see http://stackoverflow.com/questions/16529166/how-to-shadow-python-builtin-pwd-module

```
try:
    import pwd
except ImportError:
    import winpwd as pwd
```

Kind regards

**Comment by mpdehaan** [comment]
cygwin is not a supported platform for Ansible, this has been discussed quite a few times and is not a bug.

We'll do proper windows support in the future, but it won't involve installing cygwin to run Ansible from a windows host and will likely only allow managing windows nodes

I'd suggest installing Linux in a VM.

**Comment by mrichman** [comment]
I have the same issue, and I'm not using cygwin. I just installed the official Python 2.7 installer, then ran  `python get-pip.py` to install `pip`. When running `pip install ansible`, I get the above error "ImportError: No module named pwd".

**Comment by tknerr** [comment]
I'm wondering whether there is no `pwd` compatibility module for windows platforms. Haven't  found one so far at least...

Could be even a minimalistic implementation which only supports the use cases / methods that ansible requires.

Being able run ansible on windows would be super useful in a DevOps context where devs are working mainly on a windows platform. I've seen that case quite often recently.

(feels like the olde / early days of chef where it would only run JRuby + lots of additional hacks on windows)

**Comment by cchurch** [comment]
This PR at least gets beyond the pwd issue, but there are other parts that won't work after installation: https://github.com/ansible/ansible/pull/9210/files

However, [Windows](https://github.com/ansible/ansible-examples/pull/26#issuecomment-25829875) [is](https://groups.google.com/d/msg/ansible-project/d_hBTtHWUHY/lWG_zRHD-7QJ) [not](https://groups.google.com/d/msg/ansible-project/ayJ3nd0YTIc/lUShF2VsVEEJ) [supported](https://groups.google.com/d/msg/ansible-project/ayJ3nd0YTIc/AGkmwRTxNhwJ) [as](https://groups.google.com/d/msg/ansible-project/9HNH0GVwHPw/jfd1Eyn3IY8J) [a](https://github.com/ansible/ansible/issues/9576#issuecomment-63496846) [control](https://groups.google.com/d/msg/ansible-project/8VaFZM6kx10/dt0gshzT-zIJ) [machine](https://groups.google.com/d/msg/ansible-devel/oO4xIX51_LM/NyMa2UDTXHcJ), and probably won't be unless Microsoft buys Ansible.

**Comment by ghost** [comment]
+1
