### ISSUE TITLE
Conditional wild card usage

### ISSUE THREAD

**Issue by sandeep444033** [ansible/ansible#70505]
Is there any way I can use the wild cards or regex in when statements,

when: ansible_distribution_major_version|int == 6 or ansible_fqdn == "test[0-1][0-9].example.com"

I actually do not want to pass hostname of my server in vars section. Will this regex work with in conjunction with Ansible facts ? During my playbook execution time, it need to interpret my hostname of the server from fact ansible_fqdn.

hosts: localhost
tasks:
name: debug
debug:
msg: "passed"
when: "ansible_distribution_major_version|int == 6 or ansible_fqdn | regex_search('test[0-9][0-1]-[0-9][0-9].example.com')"

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
