### ISSUE TITLE
Task level timeout desperately needed

### ISSUE THREAD

**Issue by zaphodbb** [ansible/ansible#70510]
##### SUMMARY

NOTE: I was instructed by our RedHat TAM to open this RFE despite similarities to issue 33180.

We need a task level timeout,  Any individual task in Ansible should be able to have a timeout assigned to it.

Similar to https://github.com/ansible/ansible/issues/33180 but possibly simpler to implement,   In a large fleet, the common occurrence of Ansible just hanging indefinitely because of a hung NFS mount or a corrupted RPM database, for example, makes the product nearly unusable.

While implementing this "feature" at the module level would be nice (as requested in issue 33180), implementing a simple timeout at the task level would provide essentially the same functionality in an optional manner (if not present, default is None) while allowing users to determine the proper timeout for their environment/task at hand without impact to modules at all.

If the task timeout is exceeded, the hung host(s) are marked as failed on this task with a "task timed out" error message and the job continues on for the remaining hosts.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

The task object itself, core Ansible functionality.

##### ADDITIONAL INFORMATION

Tasks running modules like "setup" could be executed with a timeout as appropriate for the environment allowing playbooks being executed in large environments to continue on healthy hosts while providing helpful error indicators on hosts with unexpected issues.  For example, setup / gather facts will always hang indefinitely if there's a NFS issue.  If this is applicable in your environment of, say, 1000 servers, instead, running the setup module as a task with a timeout, a few hosts with NFS issues will timeout / fail while all remaining 900+ servers are processed as expected without further intervention.

This is in contrast with the current state where the playbook completely stops processing and hangs indefinitely until / unless someone is babysitting the job, finds the related SSH process and thereby affected host and manually kills the SSH process - which results in the same thing - a failed host.  The problem here is that it is a completely manual effort to identify and kill hung processes when the entire point of Ansible is getting rid of manual processes.

```yaml
- name: Gather facts with a timeout if you have hosts that hang on this module sometimes
  setup:
  task_timeout: 30

- name: Gather facts without a timeout if that works for you
  setup:
```

**Comment by sivel** [comment]
This feature was recently implemented in https://github.com/ansible/ansible/pull/69284 and will be included in the Ansible 2.10 release.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by zaphodbb** [comment]
holy cow, great, sorry we missed that fact in our discussions of the issue. THANK YOU!!!

**Comment by sivel** [comment]
No problem at all.
