### ISSUE TITLE
Can't use dash (#) sign in inventory file

### ISSUE THREAD

**Issue by mgcrea** [ansible/ansible#7053]
##### Issue Type:

Bug Report
##### Ansible Version:

``` bash
$ ansible --version
ansible 1.5.4
```
##### Environment:

OSX-10.9
##### Summary:

I have a `ValueError: No closing quotation` when I try to use a dash (#) in one of my inventory (for the `ansible_sudo_pass` field). Tried various escaping options without luck.
##### Steps To Reproduce:

N/A
##### Expected Results:

No error
##### Actual Results:

 `ValueError: No closing quotation`

Thanks.

**Comment by jctanner** [comment]
@mgcrea can you show an example line for an inventory file?

**Comment by mgcrea** [comment]
@jctanner 

``` yaml
[bar]
bar-a ansible_ssh_user=foo ansible_ssh_host=192.168.0.2 ansible_ssh_port=22 ansible_sudo_pass="foobar#12345"
```

**Comment by jimi-c** [comment]
@mgcrea this does appear to be a bug, but really it would be better to put your sudo password inside a vault-encrypted file rather than in a plain-text inventory file. Please refer to https://docs.ansible.com for instructions on using ansible-vault if you're not familiar with it.

**Comment by mpdehaan** [comment]
Can be solved with a # in front of the comment character, which is how we solved this problem.

Also easy to use these in group_vars or host_vars files instead, which I prefer to variables directly in inventory.

In any event, not a bug per se, just needs the escape character.

**Comment by mgcrea** [comment]
@mpdehaan do you mean escaping `#` with another `#`?

``` yaml
bar-a ansible_ssh_user=foo ansible_ssh_host=192.168.0.2 ansible_ssh_port=22 ansible_sudo_pass="foobar##12345"
```

does not work. Could you give an example? Thanks!

**Comment by new23d** [comment]
\# works. Ansible 1.9.1 though.
