### ISSUE TITLE
Don't set LANG to C on modules which don't need it

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#7060]
##### Issue Type:

Improvement
##### Ansible Version:

1.6
##### Environment:

N/A
##### Summary:

Modules should not set LANG to C, unless it is really needed. This is especially important for modules like `command` and `shell`.

This issue is a follow up to the following forum discussion https://groups.google.com/forum/#!topic/ansible-project/XwJmFPfMfo0
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
I believe this workaround is available, but I completely agree with the above.  (Needs testing):

```
- shell: /usr/bin/foo
  env:
     LANG: your_language_here
```

Equivalently

```
- shell: /usr/bin/foo
  env: "{{ env }}"
```

I would suggest we probably code it for shell and command right now but think more about the larger question for the future.

**Comment by kustodian** [comment]
I looked at what is the easiest way to accomplish this and I think it would be best to add one more parameter to `AnsibleModule` class constructor e.g. `set_default_lang=True`, so if a module doesn't want the `LANG` to be set, they would just pass `set_default_lang=False`.

In the future, we could easily set this to `False` by default and only set it to `True` in modules that require `LANG` to be `C`.

Also I'm not sure if `LANG` could be unset, so it might be a good idea to also check if it is empty and set it to default in that case.

I could throw in a pull request in the next few days if you like this idea?

**Comment by kustodian** [comment]
Please ignore my commit above, I haven't tested anything. I removed that commit, so it should remove it from this issue until I test everything.

**Comment by kustodian** [comment]
Commit 993aa96424e9eafd59fc879f9551b0c10f976e20 should be fine. I tried running `echo $LANG` with the `shell` module (since `command` module runs the `shell` module) and it worked as expected. By default it printed the default system `LANG`. Then I tried setting `LANG` with what you suggested as a workaround, but it is not `env`, but `environment`:

```
- shell: /usr/bin/foo
  environment:
     LANG: your_language_here
```

and it set the `LANG` to what was configured by the `environment`, which is also expected.

I also tried running `setup` module and it printed that `LANG=c`, which means all other modules will still use `c` by default.

**Comment by mpdehaan** [comment]
cc @jimi-c just made some changes here - https://github.com/ansible/ansible/commit/c115c34a1f5d570422b2560cc3ff0ce0ebe53dff - though this clearly isn't the solution fix (assumes English)

Just linking for future record.

**Comment by kustodian** [comment]
I'm not sure if that commit is a good idea. Setting default `LANG` to `en_US.UTF-8` could bring a lot of regression problems in other modules. If I understand correctly the reason why Ansible sets `LANG=c` is because some modules throw errors if the `LANG` is different than `c`.

Maybe a better option would be to merge this pull request and modify the `subversion` module to pass `set_default_lang=False`. It should solve all the problems with `subversion` module and it won't cause any possible problems in other modules.

Also should I added setting `LC_CTYPE` as well?

**Comment by jimi-c** [comment]
@kustodian my feeling on this was that LANG=C is essentially an ASCII environment, and where en_us.UTF-8 is a superset of ASCII it should not cause problems. For those who had internationalization issues before when LANG=C they were most likely having to set the default_lang variable in ansible.cfg already, so I thought this would at least prevent a large class of unicode errors.

**Comment by kustodian** [comment]
I just remember that @mpdehaan said once in the forums, what is the reasoning behind LANG=C, that some modules caused errors, or output different results in different language settings, so they set a default LANG=C to resolve this problem. Maybe you are right, maybe everything will work with en_us.UTF-8, but we don't know and this could cause a lot of regression problems, which we don't need, so why not just leave LANG=C on all modules and just modify modules which have problems to use the default system. Don't get me wrong, I'm all that en_US.UTF-8 is the default LANG, since I had a few problems because of this which took me some time to figure out why they are happening, but I would rather play it safe.

This is probably @mpdehaan decision, to leave `C` as default, or change it to `en_US.UTF-8`, but some modules like `command` (and probably `subversion`) would benefit more if they didn't set LANG at all, but use the system default.

**Comment by kustodian** [comment]
I just realized that only some modules have problems with some languages, so if we allow changing default LANG in ansible.cfg, that means a user could still break those modules. We should probably reconsider and make it possible for some modules to override the default `LANG` and set a LANG which works for them. Of course this would mean that we would need to go over history to find which modules are that, but would also mean that some new modules could have problems.

In my opinion Ansible should not set LANG and use the default system LANG for all modules, except those modules which we know have problems with some languages, those modules should set LANG which works for them.

We have two solutions to this problem:
1. If we know which modules have problems and we don't think there will be regression problems:
   - drop ANSIBLE_MODULE_LANG and make the system LANG the default
   - make it possible for modules to set their LANG (we will identify which modules will need this)
2. If we are not sure what modules will have problems and we would like to minimize regression bugs:
   - leave the default LANG=C
   - make it possible for modules to set their LANG (we will identify which modules will need this)
   - make it possible for modules to use default system LANG (e.g. `command` module)

What do you think about this?

**Comment by jimi-c** [comment]
So after discussing further, I think we're going to handle it as follows:

We will modify the `_compute_environment_string()` function in `runner/__init__.py` to add the proper localization environment. This will allow users to override the environment per-task if they so choose, but we will continue to default to something sane (probably en_US.UTF-8).

**Comment by kustodian** [comment]
So I guess this one can be closed then.

**Comment by jimi-c** [comment]
Yep, just merged the above, so this is now closed. Thanks!
