### ISSUE TITLE
s3_bucket_notification need support for sns and sqs

### ISSUE THREAD

**Issue by TC-robV** [ansible/ansible#70672]
##### ISSUE TYPE
- Feature Idea
s3_bucket_notification currently only supports adding events that go to lambda. s3 events can also go to sns or sqs.

##### COMPONENT NAME

s3_bucket_notification

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.aws

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
