### ISSUE TITLE
Inventory Script won't parse results

### ISSUE THREAD

**Issue by bile0026** [ansible/ansible#70698]
##### SUMMARY
ansible-inventory fails with really vague error when you aren't using a .ini for your variable import. If you try and use statically defined variables the import fails. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible-inventory

##### ANSIBLE VERSION

```
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/zjbiles/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```
no changes
```

##### OS / ENVIRONMENT

CentOS 8

##### STEPS TO REPRODUCE

Run import script to return json/dict data as follows:
```
{
  "_meta": {
    "hostvars": {}
  },
  "Firewalls": {
    "hosts": [
      "fw01",
      "fw02"
    ]
  }
}
```

```yaml

```

##### EXPECTED RESULTS

Expected that inventory parses to be used in a playbook also.

##### ACTUAL RESULTS

Inventory fails to parse and error does not lead you to solution at all. 

```
[user@host github]$ ansible-inventory -i import.py --list -vvvvv
ansible-inventory 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/user/Documents/github/import.py as it did not pass its verify_file() method
auto declined parsing /home/user/Documents/github/import.py as it did not pass its verify_file() method
yaml declined parsing /home/user/Documents/github/import.py as it did not pass its verify_file() method
toml declined parsing /home/user/Documents/github/import.py as it did not pass its verify_file() method
[WARNING]:  * Failed to parse /home/user/Documents/github/import.py with script plugin: failed to parse executable inventory script results from
/home/user/Documents/github/import.py: Expecting value: line 1 column 1 (char 0) /usr/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS
request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings   InsecureRequestWarning)
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/script.py", line 161, in parse
    raise AnsibleParserError(to_native(e))
[WARNING]:  * Failed to parse /home/user/Documents/github/import.py with ini plugin: /home/user/Documents/github/import.py:3: Expected key=value host variable
assignment, got: argparse
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/ini.py", line 138, in parse
    raise AnsibleParserError(e)
[WARNING]: Unable to parse /home/user/Documents/github/import.py as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}
```

**Comment by sivel** [comment]
The error is described within this `WARNING`:

```
[WARNING]:  * Failed to parse /home/user/Documents/github/import.py with script plugin: failed to parse executable inventory script results from
/home/user/Documents/github/import.py: Expecting value: line 1 column 1 (char 0) /usr/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS
request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings   InsecureRequestWarning)
```

```
Expecting value: line 1 column 1 (char 0)
```

This indicates that the inventory script returned a zero length string.

You would need to execute that script using `python github.py --list` to try and determine why specifically it is failing.

The only message that the `github.py` script is providing on `stderr` is an insecure HTTPS warning from urllib3/requests.

**Comment by bcoca** [comment]
closing as per above

**Comment by bile0026** [comment]
> The error is described within this `WARNING`:
> 
> ```
> [WARNING]:  * Failed to parse /home/user/Documents/github/import.py with script plugin: failed to parse executable inventory script results from
> /home/user/Documents/github/import.py: Expecting value: line 1 column 1 (char 0) /usr/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS
> request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings   InsecureRequestWarning)
> ```
> 
> ```
> Expecting value: line 1 column 1 (char 0)
> ```
> 
> This indicates that the inventory script returned a zero length string.
> 
> You would need to execute that script using `python github.py --list` to try and determine why specifically it is failing.
> 
> The only message that the `github.py` script is providing on `stderr` is an insecure HTTPS warning from urllib3/requests.

It will run it by itself ```python import.py --list``` it provides the correct output. It's only when the .ini file does not exist, and it's using ansible-inventory/playbook it fails. The output provided in the "steps to reproduce" section is the output of ```python import.py --list```.
