### ISSUE TITLE
Template module - variables in dest cause the remainder of the line to stay unparsed

### ISSUE THREAD

**Issue by cwstrommer** [ansible/ansible#707]
OS: Debian stable, on both overlord and client. 
Ansible:  Most recent devel build as of 07/27, 4pm EST

Using this task

```
action: template src=/var/lib/ansible/templates/restore_script.j2 dest=/opt/vz_scripts/202_to_${some_var}.sh owner=root group=root mode=0755
```

everything after the _dest_ tag does not appear to be parsed.  The --verbose output is 

```
{"changed": false, "dest": "/opt/vz_scripts/202_to_203.sh", "group": "root", "md5sum": "7c59a3c9a163ab01eeafcc85743752aa", "mode": "0644", "module": "template", "path": "/opt/vz_scripts/202_to_203.sh", "src": "/var/tmp/ansible-1343420855.95-16654591168669/source", "state": "file",  "user": "root"}
```

Notice that it has _mode_ set to 0644, whereas the play indicates 0755.  Experiments with changing the user and group tags also produced similar results.  Moving a tag before _dest_ causes it to be parsed again.  For example 

```
action: template mode=0755 src=/var/lib/ansible/templates/restore_script.j2 dest=/opt/vz_scripts/202_to_${some_var}.sh owner=root group=root
```

changes the mode appropriately.   

Changing the variable syntax to jinja ( {{ }} instead of ${ } ) does not have any effect. 

The copy module is not affected.

**Comment by mpdehaan** [comment]
got a fix coming, stay tuned

**Comment by mpdehaan** [comment]
changes pushed, it wasn't EXACTLY about variables, but it was reasonably weird.  Should be good to go.
