### ISSUE TITLE
vmware_guest limitation?

### ISSUE THREAD

**Issue by ReinerNippes** [ansible/ansible#70751]
##### SUMMARY
vmware_guest task creates only 5 guest at a time. 

when i want create, let's say, 10 vmware guest only 5 guests are create before another bunch of 5 guests are created. 

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```paste below
ansible 2.9
```

##### ADDITIONAL INFORMATION
is that a limitation of the ansible module vmware_guest or a vmware vcenter feature.

where can change this number? how to create 10 guests parallel?

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/vmware

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
