### ISSUE TITLE
ovirt4.py fails fedora 32 

### ISSUE THREAD

**Issue by brianmillett** [ansible/ansible#70756]
##### SUMMARY

System, Fedora 32
Python => Python 3.8.3

Running the sample dynamic inventory file for ovirt (contrib/inventory/ovirt4.py), ovir4.py fails with the following error:
Traceback (most recent call last):
  File "./ovirt4.py", line 257, in <module>
    main()
  File "./ovirt4.py", line 242, in main
    connection = create_connection()
  File "./ovirt4.py", line 119, in create_connection
    config = configparser.SafeConfigParser(
  File "/usr/lib64/python3.8/configparser.py", line 1228, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib64/python3.8/configparser.py", line 639, in __init__
    self._read_defaults(defaults)
  File "/usr/lib64/python3.8/configparser.py", line 1219, in _read_defaults
    self.read_dict({self.default_section: defaults})
  File "/usr/lib64/python3.8/configparser.py", line 754, in read_dict
    self.set(section, key, value)
  File "/usr/lib64/python3.8/configparser.py", line 1200, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/lib64/python3.8/configparser.py", line 1185, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

contrib/inventory/ovirt4.py

Diff of patch to make it work

[brian@smeagol]$ diff -wruN ovirt4.py~ ovirt4.py
--- ovirt4.py~	2020-07-19 15:11:19.458776776 -0500
+++ ovirt4.py	2020-07-20 10:39:59.028799191 -0500
@@ -116,13 +116,13 @@
     config_path = os.environ.get('OVIRT_INI_PATH', default_path)
 
     # Create parser and add ovirt section if it doesn't exist:
-    config = configparser.SafeConfigParser(
+    config = configparser.ConfigParser(
         defaults={
             'ovirt_url': os.environ.get('OVIRT_URL'),
             'ovirt_username': os.environ.get('OVIRT_USERNAME'),
             'ovirt_password': os.environ.get('OVIRT_PASSWORD'),
             'ovirt_ca_file': os.environ.get('OVIRT_CAFILE', ''),
-        }
+        }, allow_no_value=True
     )
     if not config.has_section('ovirt'):
         config.add_section('ovirt')

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This script is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by brianmillett** [comment]
Awesome, thanks
