### ISSUE TITLE
Backport ANSIBLE_COLLECTIONS_PATH variable to 2.9

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#70750]
##### SUMMARY

I realized that Ansible 2.10 prints the following deprecation warning if you use the `ANSIBLE_COLLECTIONS_PATHS` variable in your `ansible.cfg` or environment:

```
[DEPRECATION WARNING]: ANSIBLE_COLLECTIONS_PATHS option, all PATH-type options 
are singular PATH , use the "ANSIBLE_COLLECTIONS_PATH" environment variable 
instead. This feature will be removed in version 2.14. Deprecation warnings can
 be disabled by setting deprecation_warnings=False in ansible.cfg.
```

The annoying thing is most people didn't really even _start using_ collections until 2.9 (and many people still don't). And the only way to set this option in 2.9 is with `ANSIBLE_COLLECTIONS_PATHS`. But 2.10 and later will show this deprecation warning, which is really annoying since I know _I_ can't yet write playbooks that drop 2.8 and 2.9 compatibility.

So as a but of an olive branch to make the transition to this new variable name easier, it would be nice if I could set `ANSIBLE_COLLECTIONS_PATH` in Ansible 2.9, so I could write playbooks that are compatible with both 2.9 and 2.10+, without getting deprecation warnings in 2.10+.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Configuration settings.

##### ADDITIONAL INFORMATION

N/A

**Comment by geerlingguy** [comment]
(PR reference https://github.com/ansible/ansible/pull/70007)

**Comment by sivel** [comment]
Ansible 2.9 has entered into security only fixes.  We have un-deprecated `ANSIBLE_COLLECTIONS_PATHS` for the time being.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
