### ISSUE TITLE
authorized_key no longer showing key

### ISSUE THREAD

**Issue by francisco1844** [ansible/ansible#7075]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel ae29e43) last updated 2014/04/19 14:46:18 (GMT +000)
##### Environment:

Ansible running from Ubuntu 12.04 and managing same.
The exact same version of ansible running from a FreeBSD server does not have the issue. They key is populated and displays properly. On both instances the key is copied properly so it seems is only a display issue.
##### Summary:

Ansible does not report key value.
The behavior was not present on development branch as of a week ago or so. I had last git pulled about 4/14 and as I recall the key was showing properly back then.
##### Steps To Reproduce:

key="{{lookup('file','path-to-valid-key-file') }}
##### Expected Results:

'Key': ssh-dss AAAAB3NzaC1kc3MAAACBAPmCqz4gy7Z4i+CT6FhhPqMHKvdqTeIA57QSOSEOhllcRzfj4uOHWTTaF79OR/txC2f8hFbUgBb8RhH2c24nLfG9M3erHissh7fpmkfCH6u8SQb505oKl1n/er27vh29Aoxc9A6ZQVlwnYwBj0rH/Ix3fuUGzv4QLGIKCD8WQLinAAAAFQCzGkHbDCU87G+aTuoUSF1vnNihdwAAAIBeUL53G0KZHGKv5isLGqVe7qodajZ9uv4EPIr8FqVGxLxlVt5488u7Q0Dig/ejfeg/kHgWIBH9Zs/EGs7h/sFeYPcCjHxy9Xva0CNNhYKHOgwOMsuOsEK9CYfrijXFQB+rq7IObvPF4K+SLq//tzOduElg89y0vItTKjybY0bMvwAAAIBpXjQg2B63ArAPIheVVWtuWUjOfM9If0ViLQiyX61Uu2aat7bHXOpgerWN2NiuEwA6RcKShJSTS4CWMbB4+1lJaiZX2WT8Q3L+4mbMlrLy+Dh9obWb/waxli94wa3qiZsku5N19rvIZ99SiRZ9VFbM76wdAnxVU8pMFzRUUDlLUg== comment
##### Actual Results:

'Key': None

**Comment by mpdehaan** [comment]
Can you please provide more steps to show where your keyfile exists relative to your task and role structure,  as well as the permissions  on the file?

**Comment by francisco1844** [comment]
Upon further research this is just a case of 7075 (https://github.com/ansible/ansible/issues/7075).
It was not finding the key.. but it was not failing.

Closing.
