### ISSUE TITLE
onyx_interface module does not support link speeds faster than 100G

### ISSUE THREAD

**Issue by velomatt** [ansible/ansible#70845]
##### SUMMARY
The onyx_interface module does not support link speeds faster than 100G. The latest Onyx switches (SN3000, SN4000) support 200G or 400G link speed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
onyx_interface.py

##### ANSIBLE VERSION
"ansible 2.9.10"

##### OS / ENVIRONMENT
"CentOS Linux release 7.4.1708 (Core)"

##### STEPS TO REPRODUCE
"- name: Configure MTU and link speed for Eth1/1
  onyx_interface:
    name: Eth1/1
    speed: 200G"

##### EXPECTED RESULTS
Interface should be configured.

##### ACTUAL RESULTS
Task failure.

"failed: [x.x.x.x] => changed=false 
  interface: 1/1
  msg: 'value of speed must be one of: 1G, 10G, 25G, 40G, 50G, 56G, 100G, got: 200G'"

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.network

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
