### ISSUE TITLE
Redirect 2.4 traffic to maintained version of the docs

### ISSUE THREAD

**Issue by acozine** [ansible/ansible#70877]
##### SUMMARY
We are still seeing significant traffic to certain pages in the 2.4 documentation. Ansible 2.4 is no longer maintained, so we should encourage users to review more recent documentation.

Traffic to https://docs.ansible.com/ansible/2.4/playbooks_loops.html#looping-over-the-inventory is likely caused by a link from https://www.reddit.com/r/ansible/comments/8l9033/looping_through_ip_addresses_in_a_group_in_your/. 
Consider redirecting from the 2.4 page to https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
docs.ansible.com

##### ANSIBLE VERSION
multiple versions

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

**Comment by acozine** [comment]
This page may also be a source for traffic to old pages: https://wiki.freephile.org/wiki/Ansible

**Comment by acozine** [comment]
Also this page: https://www.slideshare.net/DonghuKIM2/ansible-with-oci-221441463

**Comment by MarkusTeufelberger** [comment]
I get the 2.4 version of module documentation quite often in Google search results by the way. It is not trivial to switch to the most current version from there, there are only links that drop you into the landing page of the latest docs.

**Comment by dariodsa** [comment]
Wouldn't probably be better to make a pop-up window with the following message.

**Comment by samccann** [comment]
After discussion, we decided not to put  the redirect in for  the 2.4 page as that would prevent anyone from ever accessing that page. We already have an EOL banner at the top with a link to /latest/ to make it obvious this is old old documentation.
