### ISSUE TITLE
lastest git pull: No module named color

### ISSUE THREAD

**Issue by skliarie** [ansible/ansible#709]
Hi,

I installed latest git pull (as of 2012-07-29) onto an ubuntu 10.04 based machine and got following error:
# ansible-playbook cm_pubkeys.yml

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 30, in <module>
    from ansible.color import ANSIBLE_COLOR, stringc
ImportError: No module named color

**Comment by mpdehaan** [comment]
Plenty of people are running this already, I suspect you've done a make install previously and are running this out of checkout elsewhere.

Try "source ./hacking/env-setup" or make install again

**Comment by skliarie** [comment]
You were right - I had old 0.3 ubuntu package installed... It would be nice if the installation warn me about that...
