### ISSUE TITLE
openbsd interfaces detection

### ISSUE THREAD

**Issue by faust64** [ansible/ansible#7093]
##### Actual Results: list of interfaces plus some out-of-nowhere nic

Here is a sample patch for system/setup (get_interfaces_info from GenericBsdIfconfigNetwork):

1735 was:
if re.match('^\S', line) and len(words) > 3:
1735 becomes:
if words[0] == 'pass':
   continue
elif re.match('^\S', line) and len(words) > 3:

Regards.

**Comment by jimi-c** [comment]
Could you send us a pull request with the above fix contained there? That way you'll get credit for the fix. Also add 'Fixes #7093' on a line by itself in the commit message and it will auto-close this if/when we merge that PR in. Thanks!
