### ISSUE TITLE
ansible task fails when using su as become_method to another non-root user

### ISSUE THREAD

**Issue by luckeyca** [ansible/ansible#70956]
##### SUMMARY

when using su as become_method to become another non-root user, task fails.
please try both simple password and complex password with special characters

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible core become_method su.

##### ANSIBLE VERSION

```paste below
[vagrant@rhel7 ~]$ ansible --version
ansible 2.9.10
  config file = /home/vagrant/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
[vagrant@rhel7 ~]$ ansible-config dump --only-changed
ANSIBLE_FORCE_COLOR(/home/vagrant/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/vagrant/ansible.cfg) = True
ANSIBLE_SSH_RETRIES(/home/vagrant/ansible.cfg) = 3
DEFAULT_CALLBACK_WHITELIST(/home/vagrant/ansible.cfg) = [u'profile_tasks']
DEFAULT_LOCAL_TMP(/home/vagrant/ansible.cfg) = /tmp/ansible-local-19358hmMPqR
DEFAULT_STDOUT_CALLBACK(/home/vagrant/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/vagrant/ansible.cfg) = 40
DIFF_ALWAYS(/home/vagrant/ansible.cfg) = True
HOST_KEY_CHECKING(/home/vagrant/ansible.cfg) = False


```

##### OS / ENVIRONMENT

[vagrant@rhel7 ~]$ uname -a
Linux rhel7 3.10.0-1127.10.1.el7.x86_64 #1 SMP Tue May 26 15:05:43 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

create test inventory file with one remote host.

inv.ini
remote_host_a

run the sample playbook as below:

ansible-playbook test.yml --ask-become-pass (also tried to use ansible_become_pass variable with the same result).

```yaml

---
- hosts: all
  become: yes
  become_method: su

  tasks:
  - name: test ansible su bug
    command: 'ls -l /tmp'
    become_user: dx-admin
    become_method: su
    register: st_test

  - debug:
      msg: "{{ st_test }}"

```

##### EXPECTED RESULTS

list all files under /tmp

##### ACTUAL RESULTS

```paste below

TASK [test ansible su bug] **********************************************************************************************************************************
Wednesday 29 July 2020  15:34:59 +0100 (0:00:12.130)       0:00:12.225 ********
fatal: [remote_host_a]: FAILED! =>
  msg: Incorrect su password


```

**Comment by sivel** [comment]
Does this work when becoming `root` from a normal user with `become_method: su`?  There is a known issue that the `local` connection plugin does not work with `su`.

Ref: https://github.com/ansible/ansible/issues/38696

**Comment by luckeyca** [comment]
I don't believe this is related to the local connection issue due to 2 reasons:
1. the local_connection bug failed on waiting for authentication while my issues is su and/or sudo authentication/password failure. 
2. where the sample playbook I put here does use localhost as "hosts", I ran into this issue when trying to deploy a playbook to remote host in production environment. To avoid confusion. I re-did the test with a remote machine with the same results. also will update the test playbook for clarification.

**Comment by luckeyca** [comment]
never mind. it's not a bug, rather than how ansible work as intended. when become non root user from the connection user, the become password would be different from the become password for the root account which was required for the tasks above.
