### ISSUE TITLE
Potential logic issue in TaskExecutor with undefined loop and false conditional

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#70981]
##### SUMMARY
While looking to remove the `incidental_postgresql_user` target, I found a situation that was only covered by those tests.

See https://github.com/ansible/ansible/pull/70506/files#diff-8004bc1613f5bb4139ae0810c5490cba

The code flow:

https://github.com/ansible/ansible/blob/5e1a9689837d404fd9d2db3429acf499cf1a3d2b/lib/ansible/executor/task_executor.py#L111-L116

->

https://github.com/ansible/ansible/blob/5e1a9689837d404fd9d2db3429acf499cf1a3d2b/lib/ansible/executor/task_executor.py#L152-L155

-> 

https://github.com/ansible/ansible/blob/5e1a9689837d404fd9d2db3429acf499cf1a3d2b/lib/ansible/executor/task_executor.py#L456-L458

And then we effectively throw away `self._loop_eval_error`, which would only be used if the conditional evaluation raised `AnsibleError`.

I'm undecided on what behavior is desirable, and whether the current is fine.  It seems unexpected to me at the moment.

So effectively, an undefined error evaluating the loop, is ignored if then `when` conditional successfully evaluates as `False`.

Related: https://github.com/ansible/ansible/issues/45189

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/executor/task_executor.py

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by sivel** [comment]
Based on the referenced issue (https://github.com/ansible/ansible/issues/45189) I find history that I was concerned about this previously.

I understand that we cannot change the behavior at this point it seems.

Maybe we just close this.  Looking for opinions.

FWIW, this is the code I was trying to cover, that seems to have likely been added just for this case as well:

https://github.com/ansible/ansible/blob/5e1a9689837d404fd9d2db3429acf499cf1a3d2b/lib/ansible/playbook/included_file.py#L71-L73

**Comment by Akasurde** [comment]
Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/vmware

Migrated this issue in the above repository - https://github.com/ansible-collections/vmware/issues/327.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by Akasurde** [comment]
False positive for migration candidate, please ignore close.

**Comment by sivel** [comment]
As mentioned above, I'm closing this anyway.  This is a feature, that we say isn't supported, but I see no way to remove it.
