### ISSUE TITLE
AttributeError: Values instance has no attribute 'verbose'

### ISSUE THREAD

**Issue by skliarie** [ansible/ansible#710]
I tried both ansible 0.5 and the git version (2012-07-28). In both installations I get the following error:

$ ansible-playbook cm_pubkeys.yml 
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 105, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-playbook", line 62, in main
    playbook_cb = callbacks.PlaybookCallbacks(verbose=options.verbose)
AttributeError: Values instance has no attribute 'verbose'

On another machine the same command works properly.

**Comment by mpdehaan** [comment]
0.5 has been fine for quite some time with hundreds of people running it.

I suspect you've done a make install previously and are running this out of checkout elsewhere.

Try "source ./hacking/env-setup" or make install again

**Comment by skliarie** [comment]
You were right - I had old 0.3 ubuntu package installed... It would be nice if the installation warn me about that...
