### ISSUE TITLE
template module's error messages too terse and confusing; generic solution - add --traceback switch?

### ISSUE THREAD

**Issue by pfalcon** [ansible/ansible#7103]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.6 (devel f1ce9abe0d) last updated 2014/04/21 21:05:18 (GMT +300)
##### Environment:

Ubuntu 12.04
##### Summary:

I'm suffering following error message when working with "template" action:

```
fatal: [tcwg.ci.linaro.org] => {'msg': 'files/private/jenkins_ssh_publishers.xml.tcwg-ci', 'failed': True}
```

Supposedly, that gives me, a developer, some hints, but will definitely drive a user (== someone who got a playbook to execute, but didn't write it) nuts.
##### Steps To Reproduce:

In this specific case it happens because jinja2 cannot find file included within template.
##### Expected Results:

More detailed error message.
##### Actual Results:

Reported behavior is caused by the following line:

```
result = dict(failed=True, msg=str(e))
```

The problem, default Python's Exception.**str**() just prints exception "args" attribute (a tuple), try "print AssertionError(1,2,3)", so you don't have any context of what actual error is.

I'm going to submit a patch to fix (or at least improve) that specific case, but I would like to raise a more general question: can we have a mode in Ansible which causes all (or most) tracebacks happening during playbook execution to be fully printed, instead of just error messages which may be too terse. 
This would be similar to django-admin's switch --traceback.

Having tracebacks would help debugging playbook much.

**Comment by mpdehaan** [comment]
Template includes are known to be a little off right now, there are a few tickets on this.

**Comment by pfalcon** [comment]
What about idea for --traceback switch, is it viable? I may imagine it would be a bit of chore to get complete coverage for it, but can be done gradually, just need to know it's otherwise fits Ansible paradigm.

**Comment by mpdehaan** [comment]
I'd rather not have a traceback switch.

**Comment by pfalcon** [comment]
Ok, closing. Hope that pull request #7105 is still useful.
