### ISSUE TITLE
The Ansible provided random jinja2 filter should be renamed

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#7113]
##### Issue Type:

Bug Report
##### Ansible Version:

`ansible 1.6 (devel d88ac5e24d) last updated 2014/04/22 11:14:36 (GMT -500)`
##### Environment:

Control: Mac OS, virtualenv, python 2.7.5

Target: N/A
##### Summary:

The recently added `random` filter should be renamed.

As it exists now, it overrides the built in `random` filter from jinja2, meaning that anyone who may have already been using the jinja2 `random` filter, will experience issues or unexpected results once they upgrade to 1.6.

http://jinja.pocoo.org/docs/templates/#random

This works as expected in 1.5.x but fails in 1.6 (devel) due to the addition of the random filter in #6917 

This has already caused issue for at least 1 person as evidenced by the last comment on #6917 
##### Steps To Reproduce:

``` yaml

---
- hosts: all
  vars:
    foo:
      - bar
      - baz
  tasks:
    - debug:
        msg: "{{ foo|random }}"
```
1.  Try using the jinja2 random filter to select a random item from a provided sequence
##### Expected Results:

A random item from a provided sequence should be output
##### Actual Results:

`fatal: [localhost] => an unexpected type error occured. Error was int() argument must be a string or a number, not 'list'`

**Comment by jimi-c** [comment]
Hrm, perhaps we should extend the existing to function similarly to the default? ie. if the target variable is a sequence return a random value from it, otherwise function the way the current filter does. That way, those are are using it now won't have their functionality broken either.

**Comment by sivel** [comment]
I believe that would be a good solution, and should be relatively easy to implement.  The random filter in jinja2 looks like:

```
    try:
        return random.choice(seq)
    except IndexError:
        return environment.undefined('No random item, sequence was empty.')
```

I assume in our filter we could test 'end' with 'isdigit', and based on that run `random.choice` as opposed to the current functionality.  Probably some other things to take into account, with the other args that our random filter takes.

**Comment by jimi-c** [comment]
This should work:

<pre>
diff --git a/lib/ansible/runner/filter_plugins/core.py b/lib/ansible/runner/filter_plugins/core.py
index 8557a42..293ebc4 100644
--- a/lib/ansible/runner/filter_plugins/core.py
+++ b/lib/ansible/runner/filter_plugins/core.py
@@ -181,9 +181,20 @@ def version_compare(value, version, operator='eq', strict=False):
     except Exception, e:
         raise errors.AnsibleFilterError('Version comparison: %s' % e)
 
-def rand(end, start=0, step=1):
+def rand(end, start=None, step=None):
     r = SystemRandom()
-    return r.randrange(start, end, step)
+    if isinstance(end, (int, long)):
+        if not start:
+            start = 0
+        if not step:
+            step = 1
+        return r.randrange(start, end, step)
+    elif hasattr(end, '__iter__'):
+        if start or step:
+            raise errors.AnsibleFilterError('start and step can only be used with integer values')
+        return r.choice(end)
+    else:
+        raise errors.AnsibleFilterError('random can only be used on sequences and integers')
 
 class FilterModule(object):
     ''' Ansible core jinja2 filters '''
</pre>

Whether we want to care about the parameters passed in (start, step) if it's a sequence is up for debate. It would make the above much simpler if we did not.

**Comment by sivel** [comment]
@jimi-c This works for me. Here is the playbook I tested with

``` yaml
---
- hosts: all
  vars:
    foo:
      - bar
      - baz
  tasks:
    - debug:
        msg: "{{ foo|random }}"

    - debug:
        msg: "{{ 100|random }}"
```

**Comment by sivel** [comment]
We probably need to update documentation as well.

**Comment by bcoca** [comment]
sorry, my brain took a vacation that day. I swear I searched for random filter in jinja before creating it.

@jimi-c we might just want to check that the object is a sequence, might be simpler patch

**Comment by jimi-c** [comment]
@bcoca that's what the hasattr() call does, that way it can catch things that might be iterable but not necessarily a list or tuple, seemed just as easy to me.

**Comment by bcoca** [comment]
What I was trying to say, we should just detect if it is a sequence or not
and then run jinja2's random (ignoring other params) or pass it to
randomrange and handle returned exceptions as ansible errors. This creates
(imho) simpler and cleaner code, as your note also states, by ignore extra
info when not needed.
​

**Comment by jimi-c** [comment]
It looks like the jinja2 filter is do_random(), but takes a jinja2 environment as one of the parameters. I think it's probably either easier to rename it as originally requested (I didn't realize this was fairly new, so the impact would be minimal) or to run with the patch above. Thoughts?

**Comment by bcoca** [comment]
Yes, patch is very recent, i'm fine either way, whatever works for the most
folks.​

**Comment by jimi-c** [comment]
Sold :) I merged in the above with the docs update as well.
