### ISSUE TITLE
Buiild reverse dictionary with duplicate values in the original dictionary

### ISSUE THREAD

**Issue by papiveron** [ansible/ansible#71163]
Hi,

I have a `ansible` dictionary fact `vm_templates` looking like this :

     {
            "HostedEngine": "00000000-0000-0000-0000-000000000000", 
            "cpu-node0": "2d826ed8-1dbe-4b10-93a1-5ac9734462cb", 
            "cpu-node1": "2d826ed8-1dbe-4b10-93a1-5ac9734462cb", 
            "cpu-node2": "2d826ed8-1dbe-4b10-93a1-5ac9734462cb", 
            "cpu-node3": "2d826ed8-1dbe-4b10-93a1-5ac9734462cb", 
            "fp_gpu-node0": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "fp_gpu-node1": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "fp_gpu-node10": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "fp_gpu-node11": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "fp_gpu-node2": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "fp_gpu-node3": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "fp_gpu-node4": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "fp_gpu-node5": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "fp_gpu-node6": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "fp_gpu-node7": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "fp_gpu-node8": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "fp_gpu-node9": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "hp_gpu-node0": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "hp_gpu-node1": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "hp_gpu-node2": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "hp_gpu-node3": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "hp_gpu-node4": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "hp_gpu-node5": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "hp_gpu-node6": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "hp_gpu-node7": "a08901c0-50a5-4e2f-b6d7-b11b69a32613", 
            "infra-vm": "00000000-0000-0000-0000-000000000000"
        }

I would like to build a flipping dictionary from the above one, taking into account keys with duplicate values. 
So I would like to associate each value from the first dictionary with its keys in a list, and keys having duplicate values in the old dictionary will be in the same list value.

Here is the result I'm trying to get, using `ansible` :

     {
            "00000000-0000-0000-0000-000000000000": ["HostedEngine", "infra-vm"], 
            "2d826ed8-1dbe-4b10-93a1-5ac9734462cb": ["cpu-node0", "cpu-node1", "cpu-node2", "cpu-node3"], 
           "a08901c0-50a5-4e2f-b6d7-b11b69a32613": ["fp_gpu-node0", "fp_gpu-node1", "fp_gpu-node10", "fp_gpu-node11", "fp_gpu-node2", "fp_gpu-node3", "fp_gpu-node4", "fp_gpu-node5", "fp_gpu-node6", "fp_gpu-node7", "fp_gpu-node8", "fp_gpu-node9", "hp_gpu-node0", "hp_gpu-node1", "hp_gpu-node2", "hp_gpu-node3", "hp_gpu-node4", "hp_gpu-node5", "hp_gpu-node6", "hp_gpu-node7"]
     }

In python I would have written something like :

    reverse_templates = {} 
  

    for key, value in vm_template.items(): 
        if value not in reverse_templates: 
            reverse_templates[value] = [key] 
        else: 
            reverse_templates[value].append(key)

 
  Here is what I tried in `ansible`, which doesn't work : 

    - name: "Associate each template with related VMs list"
      set_fact:
        reverse_templates: "{{reverse_templates|default({})|combine({item.value:{% if item.value not in reverse_teplates %}value[item.key]{% else %}reverse_templates[item.value] + [item.key]{% endif %}})}}"
      loop: "{{lookup('dict', vm_templates)}}"

Here is the error :
```
TASK [Associate each template with related VMs list] *******************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "template error while templating string: unexpected '%'. String: {{reverse_templates|default({})|combine({item.value:{% if item.value not in reverse_teplates %}value[item.key]{% else %}reverse_templates[item.value] + [item.key]{% endif %}})}}"}
```

Please any good approach to get there using `ansible`?

Regards

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
