### ISSUE TITLE
cron: task does not correctly add env vars anymore

### ISSUE THREAD

**Issue by stroeder** [ansible/ansible#71226]
##### SUMMARY
cron: task does not correctly add env vars anymore

##### ISSUE TYPE
- Bug Report (regression in 2.9.12)

##### COMPONENT NAME
ansible core

##### ANSIBLE VERSION
2.9.12

##### STEPS TO REPRODUCE
Try to add a CRON entry with argument env:

Example: https://gitlab.com/ae-dir/ansible-ae-dir-server/-/blob/master/tasks/cron.yml#L4

##### EXPECTED RESULTS
Env vars are added to crontab entry (like in ansible 2.9.11).

##### ACTUAL RESULTS
Env vars are missing in crontab entry.

**Comment by Akasurde** [comment]
@stroeder Do you think this will solve your issue? https://github.com/ansible/ansible/pull/71207

**Comment by stroeder** [comment]
> @stroeder Do you think this will solve your issue? #71207

It seems that the one-line change in cron.py in https://github.com/ansible/ansible/pull/71207/commits/f9faba3c6909481cb03d9e583fc1f8bc0fdf5b1b# fixes it.

**Comment by Akasurde** [comment]
@stroeder Thanks.

**Comment by Akasurde** [comment]
resolved_by_pr #71207

**Comment by relrod** [comment]
Closing per above.
