### ISSUE TITLE
Unable to delete files using ansible shell module

### ISSUE THREAD

**Issue by rohit-devops-test** [ansible/ansible#71237]
I am unable to delete the files using ansible shell module. If I run the command(rm -rf) directly on linux server then it is deleting the files but the same is not working from shell module.
My palybook is not throwing any error and task is shown completed successfully but in actual files are not getting deleted.

Here is my playbook:- 
`
- hosts: myhost
  become: yes
  gather_facts: no
  user: ansible
  vars:
   ansible_become_password: 'lk121'
  tasks:
   - set_fact:
      var_01: /home/guj/bang
   - shell: rm -rf "{{ item }}"
     with_items:
      - "{{var_01}}/servers/*/logs/access*log*"
      - "{{var_01}}/servers/*/logs/*log*"
      - "{{var_01}}/servers/*/tmp"
      - "{{var_01}}/servers/*/cache"
     register: del_var_01_files
     delegate_to: guj01_machine

`

Please help me on this.

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
