### ISSUE TITLE
Issuing reboot command with sudo fails

### ISSUE THREAD

**Issue by jwboyer** [ansible/ansible#7124]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

Fedora 20
##### Summary:

Reboot commands to remote machines seem to fail with an odd SUDO-SUCCESS parse message
##### Steps To Reproduce:

ansible <host> -vv --sudo -a /sbin/reboot
##### Expected Results:

Machine reboots
##### Actual Results:

```
[jwboyer@vader kernel]$ ansible sb --sudo -vv -a "/sbin/reboot"
<sb> REMOTE_MODULE command /sbin/reboot
sb | FAILED >> {
    "failed": true, 
    "msg": "SUDO-SUCCESS-vtmrycslvdhqbpiocsicnaixsbrlaseq\r\n", 
    "parsed": false
}
[jwboyer@vader kernel]$ 
```

The machine actually reboots, but ansible appears to think the command failed.  I found issue #5533 that has a similar "SUDO-SUCCESS-<blah>" issue, but that is currently closed and I'm not sure it's the same.

Help?

**Comment by ralphbean** [comment]
Just adding in here that I'm getting the following, similar error _without_ trying to sudo:

```
❯ ansible myhost -a "/sbin/reboot"
myhost | FAILED >> {
    "failed": true, 
    "msg": "", 
    "parsed": false
}
❯ rpm -qa | grep ansible
ansible-1.5.4-1.fc20.noarch
```

**Comment by mpdehaan** [comment]
Yeah you have to run this async because it will be wanting to a response

Using the "at" module could also be a solution.

**Comment by mpdehaan** [comment]
(Basically think about the reboot command happening before a JSON response can be returned)

**Comment by mpdehaan** [comment]
If there are questions about how to implement this, please stop by the mailing list -- didn't want to be short here.

Thanks!!!

**Comment by jwboyer** [comment]
OK, thanks.  FWIW, I did look at the at module, but it presents the same problem that just using 'shutdown -r 1' does.  Neither shutdown nor the at module has a unit granularity in seconds, so whatever I'm doing is forced to wait at least 1 minute.  Call me impatient :)
