### ISSUE TITLE
disable animation in ansible-galaxy collection install

### ISSUE THREAD

**Issue by xoxys** [ansible/ansible#71397]
##### SUMMARY
There is a loading animation used when running `ansible-galaxy collection install ...` command. While this is not a big deal for manual executions in a shell, it is cluttering the log output of some CI servers (probably caused by the non-tty environment). The result will look like this (using molecule to test an Ansible role on Drone CI):

![image](https://user-images.githubusercontent.com/3391958/90900360-9b338d00-e3c9-11ea-8f84-970c19cbd4ce.png)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-galaxy

##### ANSIBLE VERSION
```
ansible 2.9.12
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Aug  4 2020, 04:11:56) [GCC 9.3.0]
```

**Comment by samdoran** [comment]
This should be disabled automatically if `stdout` is not a TTY. Is the CI system `tee`ing the output or somehow creating a TTY?

In ansible-base 2.10, this can disable this by setting `GALAXY_DISPLAY_PROGRESS=0`. https://docs.ansible.com/ansible/devel/reference_appendices/config.html#galaxy-display-progress

To discuss this further, please reach out on IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by xoxys** [comment]
> This should be disabled automatically if `stdout` is not a TTY. Is the CI system `tee`ing the output or somehow creating a TTY?

Not sure about this part, but as long as it could be disabled in 2.10 anyway that's fine for me.
