### ISSUE TITLE
service_facts fix for Ansible 2.8.14

### ISSUE THREAD

**Issue by dennis3d15** [ansible/ansible#71465]
Hi,

We are still using Ansible 2.8.14 because upgrading will break stuff we are using.

For the install of Docker on Ubuntu 20.04 we use the service_facts check in the playbook, only the service_facts does not work for Ubuntu 20.04.

We found a fix on github https://github.com/ansible/ansible/pull/68211 but this is not for Ansible 2.8.14.

Is it possible to make this work for Ansible 2.8.14?

**Comment by sivel** [comment]
Ansible 2.8 is no longer receiving bug fixes.  See https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-release-cycle

Ansible 2.8 will only receive security fixes going forward, until 2.11 is released.

You will need to upgrade, or maintain your own modified copy of the `service_facts` module.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
