### ISSUE TITLE
Cannot install ansible with pip on OSX

### ISSUE THREAD

**Issue by brendanfalkowski** [ansible/ansible#7146]
##### Issue Type:

Documentation Report
##### Ansible Version:

Cannot install Ansible yet
##### Environment:

Mac OS X Mavericks (10.9.2)
##### Summary:

Trying to install Ansible on Mac OS X Mavericks (10.9.2) so I can setup a testing environment in Vagrant. I'm a frontend developer — brace yourself. I don't have Homebrew or MacPorts installed. I read pip is the best way to install Ansible, and to avoid other package managers. Have been Googling/reading for about 3 hours, but no luck.
##### Steps To Reproduce:

Here is exactly what I did, as per:
http://docs.ansible.com/intro_installation.html#latest-releases-via-pip

```
sudo easy_install pip
```

This executed fine.

```
pip --version
pip 1.5.4 from /Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg (python 2.7)
```

FYI: Python is also bone-stock OSX.

```
python --version
Python 2.7.5
```

Then came the problem:

```
sudo pip install ansible
```

Which leads to this error output:
https://gist.github.com/brendanf/11240002

Is there some assumed dependency that I'm missing? This is basically an unmodified Mac except for NodeJS and git being installed. I apologize up front, but the StackOverflow answers I found about gcc, cflags, and clang flew right over my head.

The docs suggest after two commands it works so I must be doing something obvious incorrectly. Appreciate any help.
##### Expected Results:

Ansible installs.
##### Actual Results:

Ansible does not install.

**Comment by joshuaswarren** [comment]
When you get to the step 'sudo pip install ansible', do this instead:

``` shell
sudo su -
export CFLAGS=-Qunused-arguments
export CPPFLAGS=-Qunused-arguments 
pip install ansible
exit
```

That last line is to just make sure you log out of the root account before you break anything accidentally. 

This doesn't appear to be ansible-specific, and instead appears to be caused by the version of clang that Mavericks is using and the default settings in it. So if you encounter a similar problem with a 'pip install' command in the future, this _should_ resolve it.

**Comment by brendanfalkowski** [comment]
Well, that totally worked. Thanks @joshuaswarren! I did read that Mavericks has an issue with clang, but didn't know what to do with that info.

Ironically, I did try executing those export commands (as my user account not as root... d'oh). Reference: http://stackoverflow.com/a/22427311/1497746

@ansibot: It would be really useful to update the documentation as I'd expect every OSX user would experience this problem as long as the Mavericks/clang issue is present.

**Comment by mpdehaan** [comment]
Hmm, interesting, we're actually _NOT_ getting a lot of reports from this, as I imagine OS X users are largely installing from source (source ./hacking/env-setup) or homebrew.   Still, we should make a note to improve docs as people will definitely try this.

We can just add the CFLAGS= and CPPFLAGS= to the pip install ansible line to keep it simple.

Thanks for the heads up!

**Comment by jjshoe** [comment]
@mpdehaan - I hit this on osx but didn't think of making an issue, as @joshuaswarren stated, this affects more than ansible, so I think it's second nature for us folks to set the env vars and move on.

**Comment by brendanfalkowski** [comment]
Thanks for the help. I figured it was some configuration that was obscure to me, but obvious to somebody familiar with installing packages. I understand what those *FLAGS do now, but I probably never would have reached that conclusion on my own.
