### ISSUE TITLE
Getting Error in ansible 

### ISSUE THREAD

**Issue by psdileep** [ansible/ansible#71481]
##### SUMMARY
I am new to ansible and trying to set up 1 ansible controller and 2 target systems.

When I tried to setup ansible in my system, getting below error 

##### ISSUE TYPE
- Bug Report

root@controller-node:~# ansible 1.7.2
 [WARNING] Ansible is in a world writable directory (/root), ignoring it as an ansible.cfg source.
ERROR: Invalid ini entry: playbook.yml - need more than 1 value to unpack
root@controller-node:~# ansible -m ping -i hosts all -vvv
 [WARNING] Ansible is in a world writable directory (/root), ignoring it as an ansible.cfg source.
<localhost> ESTABLISH CONNECTION FOR USER: root
<localhost> REMOTE_MODULE ping
<localhost> EXEC ['ssh', '-C', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'localhost', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp && mkdir $HOME/.ansible/tmp/ansible-tmp-1598509409.95-51826524703201 && echo $HOME/.ansible/tmp/ansible-tmp-1598509409.95-51826524703201'"]
localhost | FAILED => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue
root@controller-node:~# ping localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.017 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.060 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.056 ms

##### ANSIBLE VERSION

```paste below

```root@controller-node:~# ansible --version
 [WARNING] Ansible is in a world writable directory (/root), ignoring it as an ansible.cfg source.
ansible 1.7.2


##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below

oot@controller-node:~# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

##### OS / ENVIRONMENT
<!--- Provide all relevant information below, e.g. target OS versions, network device firmware, etc. -->
oot@controller-node:~# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

##### STEPS TO REPRODUCE
<!--- Describe exactly how to reproduce the problem, using a minimal test-case -->

<!--- Paste example playbooks or commands between quotes below -->
```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by mkrizek** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by psdileep** [comment]
Thank you
