### ISSUE TITLE
Do you all have a a branching and release policy?

### ISSUE THREAD

**Issue by reselbobasg** [ansible/ansible#71568]
I am doing an article on branching and release policies for the most popular open-source projects. To say Ansible is not popular is an extreme understatement.

Thus, I ask, do you have have a branching and release policy/pattern that I can read? Or is it a matter of convention and tribal knowledge? If so, what is the policy/pattern?

Thanks in advance,
Bob Reselman

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible-devel on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
