### ISSUE TITLE
Host SSH key not recognized when trying to SSH into remote repository using Ansible playbook

### ISSUE THREAD

**Issue by atlantis-droid** [ansible/ansible#71575]
Host SSH key not recognized when trying to SSH into remote repository using Ansible playbook.  Remote repository was verified to have the correct SSH key from host, but still wouldn't recognize host when trying to clone from the repository.  Ran Ansible on 15 hosts, 13 were successful, 1 failed to clone from remote repo even though they were configured the same.  Here is the actual error received.  Can anyone help, please?  Thx

fatal: [Host]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin 'ssh:<path_to_repo>' /local_path", "msg": "FIPS mode initialized\r\nDisabling GSSAPIKeyExchange. Not usable in FIPS mode\r\nPermission denied                 (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.", "rc": 128, "stderr": "FIPS mode initialized\r\nDisabling GSSAPIKeyExchange. Not usable in FIPS mode\r\nPermission denied (public key).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the corr                ect access rights\nand the repository exists.\n", "stderr_lines": ["FIPS mode initialized", "Disabling GSSAPIKeyExchange. Not usable in FIPS mode", "Permission denied (publickey).", "fatal: Could not read from remote repository.", "", "Please make sure you have the correct access rights", "and the repository exists."], "stdout": "Cloning into '/local_path'...\n", "stdout_lines": ["Cloning into '/local_path'..."]}

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
