### ISSUE TITLE
Tighten up documentation about the file module ("Introduction To Ad-Hoc Command", "File Transfer")

### ISSUE THREAD

**Issue by jf** [ansible/ansible#7164]
##### Issue Type:

Documentation Report
##### Ansible Version:

N/A
##### Environment:

N/A
##### Summary:

Hi guys, I found myself a bit confused by the writeup on the `file` module (in "Introduction To Ad-Hoc Commands"; http://docs.ansible.com/intro_adhoc.html#file-transfer). What's happening right now is that you have a segment of text right before talking about `file`, which is talking in a very active tone... and then suddenly the language switches into a totally passive tone when talking about `file`. Can really throw a reader off (while I want to keep my brain engaged, and able to recognize and focus on the important details).

I think the following could be done to further tighten up the doc around `file`:
1. make the language a bit more active where it makes sense (flows better, reads betters, and keeps the brain engaged).
2. emphasize or highlight (and this is the bit that was hard to get out of a straight reading of the text) the fact that for changing ownership/permissions, the file has to first of all _exist_ on the target system.

So, as opposed to:

---

The `file` module allows changing ownership and permissions on files. These same options can be passed directly to the copy module as well:

---

Let's use:

---

The `file` module allows changing ownership and permissions on _existing_ files. These same options can be passed directly to the copy module as well:

---

or (more active; I'm up for whether to italicize "existing"):

---

The `file` module allows you to change ownership and permissions on existing files. These same options can be passed directly to the copy module as well:

---

And then instead of:

---

The `file` module can also create directories, similar to `mkdir -p`:

---

how about a more active:

---

The `file` module can also be used to create directories, similar to `mkdir -p`:

---

or (even more active):

---

You can also use the `file` module to create directories, similar to `mkdir -p`:

---

I think overall, while this may look like a very small change, its effect overall is to make for a much better doc. What do you think?
##### Steps To Reproduce:

N/A
##### Expected Results:

A better explanation on the `file` module.
##### Actual Results:

See summary.

**Comment by mpdehaan** [comment]
Your suggestions increase verbosity and I disagree with taking it 2nd person.

This is very preference based, we're not going to take any action here, sorry.

**Comment by jf** [comment]
Sure, Michael, I understand. Just so I'm clear, I hope you didnt misread my proposed changes as adding a whole block of text? I wish i could space things out properly, but it's not possible in the markup here. I'm proposing adding 1-4 words for 2 paragraphs (for example, add 1 word ("existing"), or 3 words ("you to ... existing") for 1 paragraph, and 3 or 4 words ("be used to", vs "You can also use") for another). Thanks for reviewing this.
