### ISSUE TITLE
possible issue with vars_files using fact based paths when used with the debug module

### ISSUE THREAD

**Issue by daniellawrence** [ansible/ansible#7166]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.6
$ git rev-parse HEAD
f2db4602035dab03cb2ba8e64191258b015559d
```
##### Environment:

Linux managing Linux (localhost)
##### Summary:

`vars_files` favour static file paths over file paths using the jinja2 notation.
##### Steps To Reproduce:

```
playbook.yaml

---
- hosts: all
  gather_facts: True
  vars_files:
    - "host_{{ansible_hostname}}.yaml" 
    - default.yaml
    -  "host_{{ansible_hostname}}.yaml"      
  tasks:
    - debug: msg="vars_file lookup for foo='{{foo}}' bar='{{bar}}'"


default.yaml 

---
foo: default_foo


host_xps13z.yaml

---
foo: host_xps13z_foo
bar: host_xps13z_bar
```

$ ansible-playbook playbook.yaml
##### Expected Results:

I expect both `foo` and `bar` variables that printed in the debug message with contain the values from the 'host_xps13z.yaml' file.

```
$ ansible-playbook playbook.yaml
PLAY [all] ******************************************************************** 
GATHERING FACTS *************************************************************** 
ok: [localhost]
localhost: importing /tmp/ansible_bug/host_xps13z.yaml
localhost: importing /tmp/ansible_bug/host_xps13z.yaml
TASK: [debug msg="vars_file lookup for foo='{{foo}}' bar='{{bar}}'"] ********** 
ok: [localhost] => {
    "msg": "vars_file lookup for foo='host_xps13z_foo' bar='host_xps13z_bar'"
}
PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

`bar` is correct printing the value from `host_xps13z.yaml` file, however `foo` is printing the value from the `default.yaml` file.

```
$ ansible-playbook playbook.yaml
PLAY [all] ******************************************************************** 
GATHERING FACTS *************************************************************** 
ok: [localhost]
localhost: importing /tmp/ansible_bug/host_xps13z.yaml
localhost: importing /tmp/ansible_bug/host_xps13z.yaml
TASK: [debug msg="vars_file lookup for foo='{{foo}}' bar='{{bar}}'"] ********** 
ok: [localhost] => {
    "msg": "vars_file lookup for foo='default_foo' bar='host_xps13z_bar'"
}
PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

Hardcoding the `vars_files`, adding in host_xps13z.yaml gives me the expected results, where in both values are sources from the `host_xps13z.yaml` file.

```
vars_files:                                                                                             
   - "host_{{ansible_hostname}}.yaml"                                                                    
   - "host_xps13z.yaml"                                                                                  
   - default.yaml                                                                                        
   - "host_xps13z.yaml"                                                                                  
   - "host_{{ansible_hostname}}.yaml"      
```

**Comment by daniellawrence** [comment]
Reading over the code and throwing in lots of debug statements, I found that by ignorantly commenting out https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/play.py#L814 fixes the issue.

Hopefully that is helpful.

**Comment by jimi-c** [comment]
@daniellawrence variables based on host vars are always a lower priority than those that are not, since those variables are read in later (see http://docs.ansible.com/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable for more details on variable precedence). Variables based on host data are considered "inventory" variables, even when they're defined in the vars_files section, and for that reason end up being in a lower level than those that are not.

I would recommend putting your inventory variables in host_vars or group_vars as described in that documentation, to clearly delineate where they belong.

If you have any further questions regarding this, please let us know. Thanks!
