### ISSUE TITLE
recovering from decryption failed error

### ISSUE THREAD

**Issue by luckyinfil** [ansible/ansible#71667]
I'm currently using vault encrypted variables within the hosts file and decrypting them at runtime using the --ask-vault-pass flag. When the password is entered successfully to decrypt the vault, everything works as expected.

However, when the password is entered incorrectly causing a "decryption failed" error, is there a way to pre-identify this and recover from it? ie: by asking for user input?

put another way, is there a way to have accomplish "when: variable is defined and decryption has failed"?

@adnichols  the message is a result of ansible-vault failing to decrypt a vars file, make sure you either pass in a vault password or do not include a vaulted file.

The error has been made clearer in current devel via 0f73fb0d6fce6c01e79a68267d184290408b429d, so closing this ticket as that should make obvious which file caused the issue.

_Originally posted by @bcoca in https://github.com/ansible/ansible/issues/14337#issuecomment-189026325_

**Comment by mkrizek** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
