### ISSUE TITLE
vmware_vm_shell reports an issue "VMwareTools is not installed or is not running in the guest. VMware Tools are necessary to run this module."

### ISSUE THREAD

**Issue by jxu6619** [ansible/ansible#71676]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by jxu6619** [comment]
The guest is VM with RHEL8.2

**Comment by jxu6619** [comment]
And open-vm-tools-11.0.0-4.el8.x86_64 is installed. 
vmtoolksd is also running. Why vmware_vm_shell repots this error? thanks
]# systemctl status vmtoolsd
● vmtoolsd.service - Service for virtual machines hosted on VMware
   Loaded: loaded (/usr/lib/systemd/system/vmtoolsd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-09-08 15:57:10 MDT; 1h 46min ago
     Docs: http://github.com/vmware/open-vm-tools
 Main PID: 1013 (vmtoolsd)
    Tasks: 2 (limit: 23789)
   Memory: 4.6M
   CGroup: /system.slice/vmtoolsd.service
           └─1013 /usr/bin/vmtoolsd

**Comment by Akasurde** [comment]
Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/vmware

Migrated this issue in the above repository - https://github.com/ansible-collections/vmware/issues/385.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
