### ISSUE TITLE
Document that ./library path can be also created at role level

### ISSUE THREAD

**Issue by Ernest0x** [ansible/ansible#7178]
##### Issue Type:

Documentation Report
##### Ansible Version:

1.5.3
##### Environment:

N/A
##### Summary:

Document that ./library path can be also created at role level
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
Thanks, this is fixed on the development branch and will appear on the site shortly.
