### ISSUE TITLE
Add support for using SCP with Paramiko

### ISSUE THREAD

**Issue by hozn** [ansible/ansible#7179]
##### Issue Type:

Feature Pull Request
##### Ansible Version:

1.5.5
##### Environment:

Linux (CentOS 6.x, CentOS 5.x)
##### Summary:

This is a feature request based on the Google Groups discussion: https://groups.google.com/d/msg/Ansible-project/pjFYB8tBGgE/4kjiEeQAH2AJ

I will submit a pull request for this once I've had more time to play with the implementation I proposed.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by jimi-c** [comment]
@hozn I'm going to go ahead and close this, just send us the PR when it's ready. Thanks!
