### ISSUE TITLE
validate-modules for plugins: author: required with same conditions as for modules, or optional, or other conditions?

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansible#71794]
##### SUMMARY
This is not a bug, but a discussion issue for one aspect of #71734 ([WIP] Extend validate-modules to also validate plugins). It provides details on one of the points in https://github.com/ansible/community/issues/560#issuecomment-691529907.

For modules, the `author` field is required to follow a very specific form:
https://github.com/ansible/ansible/blob/d63d8803836df3231ba66f6e3a54576169d9f3a0/test/lib/ansible_test/_data/sanity/validate-modules/validate_modules/schema.py#L25-L32

This is not followed by plugins (since they were not validated). Some plugins have no author entry at all, others have unsupported strings (`Ericsson IPOS OAM team` for cliconf plugin community.network.eric_eccli, the `ansible.builtin.varnames` lookup has `Ansible Core`, ...).

I would suggest to use the same rules as for modules, i.e. require the authors field and use the same validation as for modules.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-test validate-modules

##### ANSIBLE VERSION
2.11

bot_skip

**Comment by sivel** [comment]
!component =test/lib/ansible_test/_data/sanity/validate-modules/validate_modules/main.py

**Comment by samdoran** [comment]
Per discussion today, the author string should be uniformly enforced across modules and plugins. Plugins that fail this validation should be fixed.

**Comment by jborean93** [comment]
Closing as per the above comment.
