### ISSUE TITLE
Not connected with our application servers using Ansible

### ISSUE THREAD

**Issue by amitgeit** [ansible/ansible#71871]
I am working for our application for bounce (start/stop) but i am not connected with application host.

I tried ping command, which you sent and it works...

[webadmin@vlodjumpts00 ~]$ ping 8.8.8.8

PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.

64 bytes from 8.8.8.8: icmp_seq=1 ttl=112 time=10.6 ms

[webadmin@vlodjumpts00 ~]$ mirrorlist.centos.org

-bash: mirrorlist.centos.org: command not found

I want to use this for our organization.. if i ran "ansible all -m ping" command. facing error, below is details:

[aa63457@vlodjumpts00 bin]$ ansible all -m ping

[DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad characters in group names by default, this will

change, but still be user configurable on deprecation. This feature will be removed in version 2.10. Deprecation warnings can be

disabled by setting deprecation_warnings=False in ansible.cfg.

[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

RTE3EPAdmin | UNREACHABLE! => {

    "changed": false,

    "msg": "Failed to connect to the host via ssh: ###############################################################################\n# CenturyLink computers and the CenturyLink computer network are CenturyLink  #\n# property. Only authorized persons may use them and only for legal and proper#\n# purposes as determined solely by CenturyLink. You consent to the monitoring #\n# of their use. You must use CenturyLink computers and the network in         #\n# accordance with the CenturyLink Code of Conduct, subject to discipline for  #\n# misuse. Customer use is governed by the CenturyLink Acceptable Use Policy.  #\n###############################################################################\nUse CTL credentials (login/password) on this server.\nAUTH-NOTICE:\nAUTH-NOTICE: Use your cuid as your username\nAUTH-NOTICE:\nPermission denied (publickey,password).",

    "unreachable": true

}

localhost | SUCCESS => {

    "ansible_facts": {

        "discovered_interpreter_python": "/usr/bin/python"

    },

    "changed": false,

    "ping": "pong"

}

Please help me... what i need to do this. Actually, we don't have UN/PWD for hosts file for connecting host machine..

localhost   ansible_connection=local

[RTE3VFO]

RTE3VFOAdmin     ansible_host=vlddwblasts001.test.intranet

RTE3VFOManaged   ansible_host=vlddwblasts002.test.intranet

[RTE3EP]

RTE3EPAdmin     ansible_host=vlddwblasts002.test.intranet

RTE3EPManaged   ansible_host=vlddwblasts003.test.intranet

[RTE3RES]

RTE3RESAdmin    ansible_host=vlddwblasts003.test.intranet

RTE3RESAManaged ansible_host=vlddwblasts004.test.intranet

[RTE3ORCH]

RTE3ORCHAdmin   ansible_host=vlddwblasts004.test.intranet

RTE3ORCHManaged ansible_host=vlddwblasts005.test.intranet

[RTE3EASE]

RTE3EASEAdmin  ansible_host=vlddwblasts005.test.intranet

RTE3EASEManaged ansible_host=vlddwblasts006.test.intranet

[RTE3RTS]

RTE3RTSAdmin ansibke_host=vlddwblasts006.test.intranet

[EASE-ASR-Test2:children]

RTE3VFO

RTE3EP

RTE3RES

RTE3ORCH

RTE3EASE

RTE3RTS

and the directory structure is:

[webadmin@vlodjumpts00 ansible]$ pwd

/etc/ansible

[webadmin@vlodjumpts00 ansible]$ ll

total 84

-rw------- 1 webadmin webadmin   607 Jul 12  2017 1

-rw-r--r-- 1 webadmin webadmin 17910 Sep 19 09:55 ansible.cfg

-rw-r--r-- 1 root     root     19985 Dec  8  2019 ansible.cfg.rpmnew

-rw------- 1 webadmin webadmin   213 Jul  3  2017 easeasr-rte2-ease.yml

-rwxr-xr-x 1 webadmin webadmin  1034 Sep 19 09:16 ease-hosts

-rwxr-xr-x 1 webadmin webadmin  1647 Sep 19 10:50 hosts

-rw------- 1 webadmin webadmin  2679 Jul  3  2017 hosts.bkp

-rw------- 1 webadmin webadmin   273 Jul  6  2017 lineinsfile_tst.yml

drwx------ 4 webadmin webadmin  4096 Nov  2  2017 playbooks

drwxr-xr-x 3 root     root        19 Dec  8  2019 roles

-rwxr-xr-x 1 webadmin webadmin  7321 Nov  2  2017 servmix_hosts

-rw------- 1 webadmin webadmin   208 Sep 19 10:55 test.yml

-rw------- 1 webadmin webadmin   122 Sep 19 10:54 vars.yaml

************************
We are not connected directly to host... fist login our jump server and than ssh host...

jump server is "vmdcltctws217" port using =22, connection type=ssh

and then enter with our UN/PWD

after that we did sudo for connection to host server..

sudo su - easesqa

and then ssh host server like..

vlddwblasts001.test.intranet

then we run start/stop command from here..

please help

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by amitgeit** [comment]
Thank you, i posted my qns..
