### ISSUE TITLE
let the service module take a ps aux pattern if no status is provided

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#719]
A lot of init scripts are really terrible, so we should do what some other config systems do to allow for checking status without relying on the init script.

Let the service module take a pattern like:

service name=foo ensure=running pattern="super_service_3000"

And if that string is found in service output, assume it is running by checking "ps aux" (possibly with some other flags too?) and not using the status command.   If no pattern is provided, check service status as normal.

(In this case, the status command should also not be checked when the service is complete)

**Comment by sfromm** [comment]
i have some code for this i'm testing.  feel free to assign.

**Comment by sfromm** [comment]
For pattern, I was thinking a simple string.  Should this accept a regex?

**Comment by mpdehaan** [comment]
I can't think of any reason a string wouldn't work as usually it's going to be a program name.   We could always do regexes later.

**Comment by mpdehaan** [comment]
works great, thanks!
