### ISSUE TITLE
'copy' module logs despite no_log: true

### ISSUE THREAD

**Issue by jf** [ansible/ansible#7193]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel a482e1583d) last updated 2014/04/29 01:53:48 (GMT +800)
##### Environment:

Ubuntu 12.04.4
##### Summary:

'copy' module logs on the remote despite no_log: true. This is not the case for other modules (service, command, shell). I would submit a patch, except that I'm still figuring out the source.
##### Steps To Reproduce:

Create a play with a copy task, and set no_log: true. Run the play, and you'll see that the copy task is still logged on the remote.
##### Expected Results:

No log on the remote for the copy task.
##### Actual Results:

The copy task is logged on the remote.

**Comment by maxim** [comment]
Looks like still happens in Ansible 1.6.6

**Comment by jimi-c** [comment]
@maxim this may be true, due to the fact that internally the copy module may switch over to using the file module, so this same fix may need to be applied there. Please open a new issue for this, and include a sample that helps reproduce this if you can, so we can track it down quicker. Thanks!
