### ISSUE TITLE
[setup module] add support to retrieve default locale.

### ISSUE THREAD

**Issue by kiranos** [ansible/ansible#7216]
##### Issue Type:

Feature Idea
##### Ansible Version:

Ansible v1.5.4
##### Environment:

Debian 7
##### Summary:

Add support to retrieve system default locale from setup module
##### Steps To Reproduce:

Not possible to get current system locale as a facts variable.
##### Expected Results:

Retrieve this variable and use it with conditional when so we dont have to blindly run change locale on each run.
##### Actual Results:

Have to retrieve current locale with script or likewise.

**Comment by mpdehaan** [comment]
We would be open to patches for this though it's unlikely to be something we are going to work on.

Please feel free to submit a pull request!
