### ISSUE TITLE
Ansible secret has special character " : " in it, when the password is being decrypted and read via ansible_vault it is unable to read as is.

### ISSUE THREAD

**Issue by tmohamme** [ansible/ansible#72204]
##### SUMMARY

I have a secret that I use to connect to ldap, however that secret has a colon in it : , when ansible-vault decrypts the password.yml file it throws an exception 

yaml.scanner.ScannerError: mapping values are not allowed here
  in "<byte string>", line 1, column 22:
    ldappass: abc123:
                                 ^

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /Users/smohamme/ansible_liquibase/ansible.cfg
  configured module search path = ['/Users/smohamme/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:03) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### CONFIGURATION

```paste below
DEFAULT_VAULT_PASSWORD_FILE(/Users/smohamme/ansible_liquibase/ansible.cfg) = /Users/smohamme/.vault_pass
INVENTORY_ENABLED(/Users/smohamme/ansible_liquibase/ansible.cfg) = ['host_list', 'script', 'auto', 'yaml', 'ini', 'toml']
INVENTORY_IGNORE_EXTS(/Users/smohamme/ansible_liquibase/ansible.cfg) = ['.pyc', '.pyo', '.swp', '.bak', '~', '.rpm', '.md', '.txt', '~', '.orig', '.ini', '.cfg', '.retry']

```

##### OS / ENVIRONMENT

macos

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
