### ISSUE TITLE
Vault should warn when passing stdin strings with newlines

### ISSUE THREAD

**Issue by jeffwarnica** [ansible/ansible#72229]
##### SUMMARY

Vault should warn when passing stdin strings with newlines

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vault

##### ADDITIONAL INFORMATION

I've personally lost hours of debugging time because I've `echo "password" |ansible-vault encrypt_string`.  As vault already gives some handy feedback on interactive strings, it is reasonable to give a warning when it receives a string on STDIN that ends in a \n (which is "never" correct).

```
echo "password" |ansible-vault encrypt_string #bad
echo "password" -n |ansible-vault encrypt_string #good

```

**Comment by sivel** [comment]
This appears to already have a PR open for it. There is no need to open a feature idea as well:

https://github.com/ansible/ansible/pull/72141

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
