### ISSUE TITLE
ansible-playbook hangs on giant /etc/ansible/hosts file

### ISSUE THREAD

**Issue by zxwing** [ansible/ansible#7227]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.3
##### Environment:

CentOS 6.4
##### Summary:

ansible-playbook will hang if /etc/ansible/hosts file contains massive entries
##### Steps To Reproduce:
1. add large number of entries to /etc/ansible/hosts file, for example, 500,000 entries
2. run any playbook by ansible-playbook
##### Expected Results:

playbook should run as normally as when /etc/ansible/hosts is in small size 
##### Actual Results:

ansible-playbook hangs > 6 minutes

**Comment by srgvg** [comment]
```
$ for m in A B C D E ; do echo "[$m]"; for n in `seq 1 100000`; do echo host$m$n; done ; done > hosts
$ time ansible -i hosts --list-hosts all
```

I killed it after 30 minutes :)

The same command with 5,000 hosts:
real    0m1.933s
user    0m1.607s
sys 0m0.099s

With 50,000 hosts:

real    2m27.510s
user    2m25.220s
sys 0m0.804s

This of course just parses an ini files, and no variables yet.

If you have that many hosts, IMHO, you need to
- use dynamic inventory
- only give subset of the hosts you want to act on to ansible

I can't imagine you'd want to run a playbook on (more than) 5k hosts at once.

**Comment by jimi-c** [comment]
@zxwing is this an actual use-case?

**Comment by srgvg** [comment]
@jimi-c according to #7226 it appeared by mistakenly adding that much hosts in the hosts file :)

**Comment by mpdehaan** [comment]
Not a real world use case.

**Comment by zxwing** [comment]
@jimi-c @sergevanginderachter @mpdehaan yes I made this by a mistake, but it's INDEED a real world case! Our product manages huge cloud, some customer runs > 30, 000 hosts(I don't know the number of VM), they are currently using internal configuration management tool to configure VM. Who knows if someday they will switch to Ansible? 

From last scalability test of openstack from IBM, they run 75, 000 VMs on 320 hosts,if we apply this number to 30,000 hosts, it's 7,031,250 VMs!

In last two years, I have seriously evaluated Puppet, Salt, Ansible. IMO, Ansbile is the one that really knows configuration management. Puppet is unnecessary complex. Salt is less complex but its master-minion setup screws up large deployment, it doesn't even have a official way to upgrade its own minion. And Salt's confusing return code design stops thirdparty software from integrating with it, you don't have reliable way to check success or failure. Ansible is dead simple! All things are tasks , you can build whatever you want based on task, and agent-less architecture relieves upgrade burden, native openssh shuts up mouth of picky security guy. 

If we don't treat this bug seriously, it will prevent Ansible from large cloud ready. And I don't think this bug is too hard to fix. Parsing data larger than your memory sounds like a question for graduate in interview.

**Comment by srgvg** [comment]
@zxwing for the record: (1) I'm not ansible staff, just a community member and contributor, I follow up here b/c inventory is a topic of interest to me ; (2) if you want to further discuss this, better take this to the list, as people from ansible normally don't follow up on closed tickets.

That being said, as of now I understand those numbers are not a real world use case, at this moment, and in practice. It could become one, if you evolve towards it.

In my opinion:
- given that many hosts, and how ansible parses its full inventory with each instance, this is bound to give performance issues;
- managing that many hosts with INI files will never scale; though I suspect delivering that much hosts with an inventory script will yield the same problems
  Keep in mind that ansible loads everything in memory, and runs from there.

So the solution here, IMHO, would be to manage inventory with a separate solution(*), which allows you to load inventory in ansible through an inventory script, but _limited_ to a small subset, the subset where you will effectively running ansible on.

(*) to the best of my knowlegdge, such a thing doesn't exist so far.
