### ISSUE TITLE
ec2_vol task crashes

### ISSUE THREAD

**Issue by binarytemple** [ansible/ansible#7228]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (upstreamdevel d2819e22e3) last updated 2014/04/29 18:31:36 (GMT +100)
##### Environment:

OSX -> Amazon Ubuntu 12.04 64bit
##### Summary:

Task crashes with error message
##### Steps To Reproduce:

Create Amazon tasks as shown in snippet
##### Expected Results:

Create and attach volume
##### Actual Results:

Crash with stack trace as given above.

**Comment by binarytemple** [comment]
Have created pull request to fix. 
https://github.com/ansible/ansible/pull/7230
Someone must have refactored at some stage but left old var names laying around, this would never have happened if Ansible was written in Scala ;-)

**Comment by jimi-c** [comment]
The above has been merged in, so this problem should now be fixed. Thanks!
