### ISSUE TITLE
Docs refer "vars_files" before their definition

### ISSUE THREAD

**Issue by AndreiPashkin** [ansible/ansible#7241]
##### Issue Type:

Documentation Report
##### Ansible Version:

1.5.3
##### Environment:

N/A
##### Summary:

[Here](http://docs.ansible.com/playbooks_roles.html#roles), docs says:

> Now that you have learned about vars_files...

But actually, "vars_files", not mentioned in any of previous chapters. Their definition takes place [here](http://docs.ansible.com/playbooks_variables.html#variable-file-separation) - in next chapter.

**Comment by jxn** [comment]
I just found this.  Can we get a doc update to take care of it?  At least link to where vars_files are explained before they are referenced?
