### ISSUE TITLE
encoding for postgresql is set to SQL_ASCII

### ISSUE THREAD

**Issue by tomscytale** [ansible/ansible#7246]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.5
##### Environment:

Ubuntu 12.04
##### Summary:

when installing postgresql-9.1 using  `pkg=postgresql state=present` all databases are configured with an encoding of `SQL_ASCII`
##### Steps To Reproduce:

``` yaml
- name: install basic database packages
  action: apt pkg={{ item }} state=present
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
```
##### Expected Results:

```
postgres@demo:~$ psql -c "\l" postgres
                                   List of databases
    Name     |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-------------+----------+----------+-------------+-------------+-----------------------
 postgres    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
             |          |          |             |             | postgres=CTc/postgres
 template1   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | postgres=CTc/postgres+
             |          |          |             |             | =c/postgres
```
##### Actual Results:

after this I get

```
postgres=# \l
                              List of databases
    Name     |  Owner   | Encoding  | Collate | Ctype |   Access privileges   
-------------+----------+-----------+---------+-------+-----------------------
 postgres    | postgres | SQL_ASCII | C       | C     | 
 template0   | postgres | SQL_ASCII | C       | C     | =c/postgres          +
             |          |           |         |       | postgres=CTc/postgres
 template1   | postgres | SQL_ASCII | C       | C     | =c/postgres          +
             |          |           |         |       | postgres=CTc/postgres
```

which is not very desirable
### Fix

I do `apt-get purge postgresql-9.1 && apt-get install postgresql-9.1` and i then see

```
postgres@demo:~$ psql -c "\l" postgres
                                   List of databases
    Name     |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-------------+----------+----------+-------------+-------------+-----------------------
 postgres    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
             |          |          |             |             | postgres=CTc/postgres
 template1   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | postgres=CTc/postgres+
             |          |          |             |             | =c/postgres
```

which is what you expect to get when installing using `apt-get`
so why does ansible install with an unexpected encoding?
looks like it's because the local is unset when ansible runs the package manager
other configuration management systems report similar errors:
http://stackoverflow.com/questions/15949783/postgresql-is-being-installed-with-sql-ascii-using-puppet  
https://github.com/saltstack/salt/issues/4543

in order to get ansible to do the right thing I have to do this:

``` yaml
- name: install basic database packages
  action: apt pkg={{ item }} state=present
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
  environment:
    LC_ALL: en_US.UTF-8
```

and of course setting the database encoding explicitly is also good:

``` yaml
- name: Create Database.
  sudo_user: postgres
  postgresql_db: >
    name={{ database.name }}
    owner={{ database.user }}
    encoding=UTF8
    lc_collate=en_US.UTF-8
    lc_ctype=en_US.UTF-8
```

explicitely setting the encoding for a database is always a good idea of course, still tho - I don't think having `postgres`, `template0` and `template1` with an encoding of `SQL_ASCII` is a good thing.

**Comment by jimi-c** [comment]
In 1.6, we are now setting LANG to `en_US.UTF-8`, which should have the same effect as the above. We will be releasing 1.6 in the near future, so you can test with the latest pull from the devel branch to verify whether it resolves your issue.

**Comment by tomscytale** [comment]
yes this seems to work fine

**Comment by jimi-c** [comment]
Great, thanks for following up. If you have any further questions, let us know.

**Comment by rommsen** [comment]
I am just leaving this here because this made me lose a couple of hours. Maybe someone can make use of this.

No matter what I did, server and database encoding were set to ASCII. Setting the locale via the environment parameter was not helping either. Finally I found, that /etc/default/locale was not set on my servers so even a manual apt-get install postgresql was giving me the wrong results. I added the file via a template and from there on everything went fine:

``` yml
# default_locale is something like en_US.UTF-8
LANG="{{ default_locale }}"
LC_ALL="{{ default_locale }}"
```

System: Ubuntu 14.04
Ansible: 1.9.1

**Comment by dgsb** [comment]
This issue can still be produced when the playbook is played mac os X hosts, python 3.5.2, postgresql 9.1 and remote target debian 7.
This works perfectly fine when the postgresql is 9.4 and the os target is debian 8
