### ISSUE TITLE
ec2_vpc not idempotent in devel without resource_tags

### ISSUE THREAD

**Issue by psa** [ansible/ansible#7248]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel c0f92317ef) last updated 2014/05/01 18:13:25 (GMT +000)
##### Environment:

Ubuntu 12.04
##### Summary:

`ec2_vpc` creates new VPCs every time it is run unless `resource_tags` are specified at the VPC level.
This is listed as optional so it should match on `cidr_block` and no `resource_tags` but it does not.
##### Steps To Reproduce:

ansible-playbook the following, twice.

```

---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: "Creating px_test VPC"
    local_action:
      module: ec2_vpc
      state: present
      cidr_block: 172.22.0.0/16
      region: us-east-1
      subnets:
        - cidr: 172.22.2.0/24
          az: us-east-1a
          resource_tags: { "Name": "us-east-1a.test" }
        - cidr: 172.22.3.0/24
          az: us-east-1a
          resource_tags: { "Name": "us-east-1a.test2" }
      internet_gateway: True
      route_tables:
          - subnets:
              - 172.22.2.0/24
              - 172.22.3.0/24
            routes:
              - dest: 0.0.0.0/0
                gw: igw
    register: vpc

  - debug: var=vpc
  - debug: var=vpc.subnets[0]
```
##### Expected Results:

A single VPC should be created. No changes should occur on the second and subsequent runs.
##### Actual Results:

A VPC is created every time the playbook is run.
##### Workaround:

Add `resource_tags` to the VPC configuration.

**Comment by mpdehaan** [comment]
When you say "not idempotent" can you illustrate the problem with a better description?

(See the issue template for "actual vs expected", thanks!

**Comment by psa** [comment]
Does the updated description help?

**Comment by jimi-c** [comment]
@psa I believe this is working as intended. The "uniqueness" of the vpc is based on the resource tags set on itself, not on its child subnets, so having the resource_tags set at the higher level rather than on the subnet (where they are used mainly for informative uses in AWS itself) is the way to go. It may be worth updating the docs slightly to reflect this, if you do find it confusing.

**Comment by psa** [comment]
Not having `resource_tags` is a uniqueness factor. So a VPC with no `resource_tags` is specific in the same way as one that has a tag of `Name` set to some particular value.

**Comment by mpdehaan** [comment]
It's not, unfortunately.  You have to tag the resources to make things workable here as that's what the module keys off of. 

I agree with the intellectual argument that "no tags should be treated as tags", but that really can't be applied here, alas.

**Comment by psa** [comment]
I would argue then that `resource_tags` should be a required argument. In order to have consistent behavior, it's required so it should be forced in code to avoid having nasty surprises for those who upgrade from 1.5 to 1.6 (or just happen to not yet understand that it's required even if the code isn't forcing the issue).
