### ISSUE TITLE
apt: upgrade=[safe | full | dist] ignores "default_release" parameter

### ISSUE THREAD

**Issue by bfqrst** [ansible/ansible#7265]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible 1.5.4, 1.5.5, 1.6
##### Environment:

Managing machine OS: OS X Mavericks
Target machine OS: Debian Wheezy
##### Summary:

Suppose you add the Wheezy backports repo via apt_repository to the target system and want to perform any of the safe-upgrade, dist-upgrade, full-upgrade INCLUDING the backports repo, the latter will be ignored. This is due to the fact that in the upgrade function of the apt module lacks a check for the default_release parameter. The install function on the other hand has such a check which will correctly install packages from alternative repos when passed.
##### Steps To Reproduce:

In my playbook I add the backports repo and want to perform the safe-upgrade:

```
    - name: Add Wheezy Backports
      apt_repository: repo='deb http://ftp.de.debian.org/debian wheezy-backports main' state=present update_cache=yes
    - name: Initial safe-upgrade of the system (including wheezy-backports)
      apt: upgrade=safe default_release=wheezy-backports update_cache=yes dpkg_options=force-confold
```
##### Expected Results:

The expected result would be that all upgradable packages (including those from backports, since default_release was passed) are installed and the second run of the task would leave me with a "green" OK result. In apt-get as well as in aptitude terms that would translate to the "-t alternative_repo" switch on the target machine.
##### Actual Results:

Only the upgradable packages from the default repo are installed and whatever repo is passed to the default_release parameter is ignored. Shelling to the target machine and manually firing the apt-get or aptitude commands, proves that there are still upgradable packages.

**Comment by jimi-c** [comment]
The above PR has been merged, which should address this issue. If you continue seeing any problems related to this, please let us know. Thanks!
