### ISSUE TITLE
Failed to import the required Python library (pexpect) on sejenk01's Python /usr/bin/python.

### ISSUE THREAD

**Issue by pr07pr07** [ansible/ansible#72679]
##### SUMMARY

We are getting below errors if using the except module in the ansible playbooks.
`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named ptyprocess
fatal: [sejenk01]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (pexpect) on sejenk01's Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}`

##### PLAYBOOK:
- name: Creating a OSB domain
  expect:
      command: "{{ wldt_home }}/weblogic-deploy/bin/createDomain.sh  -run_rcu -oracle_home {{ oracle_home }} -domain_parent {{ domainParentDir }} -domain_type OSB -model_file {{ oracle_jinja_templates }}/OsbDomainModel.yaml -rcu_db {{ connection_string }} -rcu_prefix {{ schema_prefix }} -rcu_db_user {{ db_user }}"
      responses:
         'Enter the RCU database SYS user password': "{{ db_password }}"
         'Please enter the RCU Schema password': "{{ schema_password }}"
      timeout: 1200

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/prathapdasari/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Jun  5 2020, 22:59:21) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
PrathapDasaris-MacBook-Pro:ansible-wdt prathapdasari$ 

python --version
Python 2.7.5

##### OS / ENVIRONMENT

Linux sefmw01 4.1.12-124.39.5.1.el7uek.x86_64 #2 SMP Tue Jun 9 20:03:37 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux

##### EXPECTED RESULTS
it should be completed on remote servers without any errors.

**Comment by jborean93** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

Fix the import error so the module can actually run. If a module cannot import what is required how would you expect it to work.

**Comment by prathapdasari** [comment]
I will communicate with you on a mailing asap
