### ISSUE TITLE
acl recursive

### ISSUE THREAD

**Issue by aarnaud** [ansible/ansible#7276]
Hi,

Could you add recursive option for acl module?

http://docs.ansible.com/acl_module.html

Thanks.

**Comment by mpdehaan** [comment]
This would make it very difficult to track changed states.

If you'd like this, I'd suggest shelling out to the command or shell module and calling setfacl instead.

**Comment by aarnaud** [comment]
Thanks, 

Yes, I already use command for this.

It's future feature idea for this modue.
