### ISSUE TITLE
Variables passed via role dependency don't override variables defined as set_fact in previous play

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#7277]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible 1.6 (devel)
##### Environment:

Debian/Ubuntu
##### Summary:

I'm using a role which supports variables passed via role dependencies and uses set_fact to configure missing variables dynamically during playbook execution. I've found out that running multiple plays involving that role generates different results, breaking idempotency.
##### Steps To Reproduce:

Example role with more explanation can be found here: https://github.com/drybjed/ansible-setfact-dependency
##### Expected Results:

Using that specific role combination should generate the same results both when it is run as a separate play, or during subsequent plays.
##### Actual Results:

Running that role combination makes Ansible behave differently when it's run as a separate play and breaks idempotency when it is included in a larger playbook with multiple plays.

**Comment by mpdehaan** [comment]
Sorry, I'm finding this language very dense and the playbook is quite detailed.  Can you please work this down to an absolutely minimal example?

I'm not even sure we have a bug here but there's simply too much information "this blocks all connections", etc...

Let's limit discussion to what is actually being discussed and try to boil things down to something minimal.

Thanks!

**Comment by drybjed** [comment]
@mpdehaan Don't feel sorry :) I don't think it's really a bug either, more like a consequence of variable persistence across plays. Anyway, I've found a [solution](https://github.com/drybjed/ansible-setfact-dependency/commit/200c51c20fcaca9ed343cb94a0add59eb94a7655) to this problem with additional variable and conditions, which makes a role behave consistently across plays. Case closed.
