### ISSUE TITLE
--limit does not work with intersecting hostgroups

### ISSUE THREAD

**Issue by ThStock** [ansible/ansible#7281]
##### Issue Type:

Bug Report, Feature Idea
##### Ansible Version:

ansible 1.5.5
##### Environment:

N/A
##### Summary:

I'll be nice, if the `--limit` switch, will limit task execution to the given hostgroup, also when both hostgroups consists of the same hosts
##### Steps To Reproduce:

Inventory:

```
[webservers]
webAA

[webservers-with-cache]
webAA
webBB
```

Playbook:

``` yml

---
- hosts: webservers
  remote_user: a
  tasks:
  - shell: id
- hosts: webservers-with-cache
  remote_user: b
  tasks:
  - shell: uname -a
```

``` shell
$ ansible-playbook  -v -i ... --limit webservers playbook.yml
```
##### Expected Results:

```
PLAY [webservers] *************************************************************

GATHERING FACTS ***************************************************************
ok: [webAA]

TASK: [shell id] **************************************************************
changed: [webAA] => {"changed": true, "cmd": "id ", 
"delta": "0:00:00.004137", "end": "2014-05-05 18:31:23.507347", "rc": 0,
"start": "2014-05-05 18:31:23.503210", "stderr": "", 
"stdout": "uid=1000(a) gid=1000(a) groups=1000(a)"}

PLAY RECAP ********************************************************************
webAA              : ok=2    changed=1    unreachable=0    failed=0
```
##### Actual Results:

```
PLAY [webservers] *************************************************************

GATHERING FACTS ***************************************************************
ok: [webAA]

TASK: [shell id] **************************************************************
changed: [webAA] => {"changed": true, "cmd": "id ", 
"delta": "0:00:00.004137", "end": "2014-05-05 18:31:23.507347", "rc": 0, 
"start": "2014-05-05 18:31:23.503210", "stderr": "", 
"stdout": "uid=1000(a) gid=1000(a) groups=1000(a)"}

PLAY [webservers-with-cache] **************************************************

GATHERING FACTS ***************************************************************
ok: [webAA]

TASK: [shell uname -a] ********************************************************
changed: [webAA] => {"changed": true, "cmd": "uname -a ", 
"delta": "0:00:00.002848", "end": "2014-05-05 18:31:25.982012", "rc": 0, 
"start": "2014-05-05 18:31:25.979164", "stderr": "", 
"stdout": "Linux ... 2.6.18-371.3.1.el5 #1 SMP Mon Nov 11 03:23:58 ES.."}

PLAY RECAP ********************************************************************
webAA              : ok=4    changed=2    unreachable=0    failed=0
```

**Comment by jimi-c** [comment]
I'm not quite sure this is an issue. The limit is a list of hosts, which also happens to be in the second group, so I would expect it to run on that host in the second play.

**Comment by ThStock** [comment]
Hmm what do you think, it is best solution for me:
- work with inventories ala `stage-webservers`, `stage-webservers-with-cache`, `live-webservers`, `live-webservers-with-cache`, ... ?
- add additional hostnames for one host (feels not good)?
- use two playbooks combined ala `ansible-playbook -i stage --limit webAA webserver.yml 
  && ansible-playbook -i stage --limit webAA webserver-with-cache.yml`?

According to [Patterns](http://docs.ansible.com/intro_patterns.html) docs I would assume the reported behavior with:

> The following patterns address one or more groups. Groups separated by a colon indicate an “OR” configuration. This means the host may be in either one group or the other:
> 
> ```
> webservers
> webservers:dbservers
> ```

`$ ansible-playbook -i ... --limit webservers:webservers-with-cache all-webservers.yml` or `$ ansible-playbook -i ...  all-webservers.yml`

btw: for me it feels a little bit like this ;-) :-D

``` python
>>> webservers = ["webAA"]
>>> print map(lambda x: "Setup webserver on " + x , webservers)
['Setup webserver on webAA', 'Enable caching on webAA']
```

**Comment by mpdehaan** [comment]
Limit is operational, this would be best served by a post to the users-list to discuss how "--limit" works since this is still in "Q&A" mode.

Thanks!
