### ISSUE TITLE
Update testing Prs with Azure pipelines details

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#72868]
##### SUMMARY

ansible/ansible is using Azure pipelines for CI on PRs now. Need to update this page to remove shippable details and add pipelines details - 
https://docs.ansible.com/ansible/devel/dev_guide/testing.html#testing-within-github-shippable

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

docs.ansible.com
##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

**Comment by samccann** [comment]
should basically be s/shippable/azure pipelines/ and possibly updating the bot commands to request re-run.

**Comment by AppyDev** [comment]
Is this issue already resolved?

**Comment by samccann** [comment]
It looks like it as - https://docs.ansible.com/ansible/devel/dev_guide/testing.html#testing-within-github-azure-pipelines

Thanks @AppyDev for noticing!

If you are looking for some ways to help out with Ansible documentation, these two, while old, are still looking for help:
https://github.com/ansible/ansible/issues/35520
https://github.com/ansible/ansible/issues/59449

Feel free to post questions in those issues if you need help, or come to #ansible-docs on IRC anytime for assistance!
