### ISSUE TITLE
Provide GPG signatures for releases

### ISSUE THREAD

**Issue by hlieberman** [ansible/ansible#7286]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.6 (master 812851cb8b) last updated 2014/05/06 01:23:59 (GMT +000)
##### Environment:

N/A
##### Summary:

In this day and age where security is at the forefront, and considering the critical role that Ansible plays in many different infrastructures, it would be good to have a GPG signature to verify the release tarballs that are available for download.

The version that gets packaged into Debian is secure by GPG signatures after its upload, but for my fellow maintainers - and for non-Debian derivative users - it would be good to know that we're getting the right thing.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
This is unlikely to be provided at this time.   However, you are welcome to download particular  releases directly from git (using a release or tag) and build them yourself if you are concerned with signatures from the build system or do not want to get them from an OS distribution.
