### ISSUE TITLE
Playbook filter not working in content of collections in galaxy.ansible.com

### ISSUE THREAD

**Issue by javeedf** [ansible/ansible#72948]
##### SUMMARY
go to https://galaxy.ansible.com/dellemc/enterprise_sonic
click on content, there is filter for roles, playbooks, modules and plugins. unselect all and select only playbook.

It is expected to list the available playbooks in playbooks directory for the collections, but it is not working

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible galaxy

##### ANSIBLE VERSION
ansible.galaxy.com

##### STEPS TO REPRODUCE
go to https://galaxy.ansible.com/dellemc/enterprise_sonic
click on content, there is filter for roles, playbooks, modules and plugins. unselect all and select only playbook.

It is expected to list the available playbooks in playbooks directory for the collections, but it is not working

##### EXPECTED RESULTS
go to https://galaxy.ansible.com/dellemc/enterprise_sonic
click on content, there is filter for roles, playbooks, modules and plugins. unselect all and select only playbook.

It is expected to list the available playbooks in playbooks directory for the collections, but it is not working

##### ACTUAL RESULTS
It is expected to list the available playbooks in playbooks directory for the collections, but it is not working

![image](https://user-images.githubusercontent.com/11018703/101929351-bc302000-3bfc-11eb-81cc-eb6d5828df03.png)

**Comment by sivel** [comment]
This repository does not service galaxy.ansible.com.  To report bugs for galaxy.ansible.com please use https://github.com/ansible/galaxy

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
