### ISSUE TITLE
ansible.builtin.command docs for 2.9 and 2.10 both claim "cmd" option exists, but Ansible says it doesn't if FQCN is used

### ISSUE THREAD

**Issue by angwe** [ansible/ansible#72951]
When using "ansible.builtin.command" to designate running a command, the "cmd:" option throws this error:

```
fatal: [w.x.y.z]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.builtin.command) module: cmd Supported parameters include: _raw_params, _uses_shell, argv, chdir, creates, executable, removes, stdin, stdin_add_newline, strip_empty_ends, warn"}
```

When switching to non-FQCN form - "command" - it works fine.

Running Ansible Engine 2.9 from the RHEL 8 supported Ansible Repo via RH Satellite.

```
[user@server ansible]$ ansible --version
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
[user@server ansible]$
```

**Comment by sivel** [comment]
This has been resolved in https://github.com/ansible/ansible/pull/71824 and will be included in the 2.9.16 and 2.10.4 releases that are scheduled for Dec 14, 2020.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
