### ISSUE TITLE
global name 'distro' is not defined in Ubuntu container

### ISSUE THREAD

**Issue by esamattis** [ansible/ansible#7295]
When I try to run a playbook in a Ubuntu Trusty container using LXC (on precise host) I get following error:

```
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: SUDO-SUCCESS-qkcdrotssfnuyxbcqqxbaxmgprxhppgk
Traceback (most recent call last):
  File "/home/ci/.ansible/tmp/ansible-tmp-1399375966.29-78394529212607/apt_repository", line 1794, in <module>
    main()
  File "/home/ci/.ansible/tmp/ansible-tmp-1399375966.29-78394529212607/apt_repository", line 385, in main
    if isinstance(distro, aptsources.distro.UbuntuDistribution):
NameError: global name 'distro' is not defined
```

Full log https://gist.github.com/epeli/aca368dfc5ce72dd3edb

This happens when I try to run the playbook over SSH or locally. I have configured the user `ci` to be able to use sudo without a password.

The playbook is fairly basic

``` yaml
- hosts: localhost
  sudo: yes
  tasks: 
    - apt_repository: repo='deb http://example.com trusty main restricted universe multiverse' state=present
   ...
```

The playbook runs fine on a KVM based Trusty installation.

I'm using Ansible version 1.5.5.

**Comment by esamattis** [comment]
Oh, I just didn't have `python-apt` installed. The error message could be better.

**Comment by jimi-c** [comment]
Yeah looks like a bug in the error handler. We'll look into this.

**Comment by jimi-c** [comment]
I've pushed the above commit to address this. Please let us know if you continue having any further problems related to this issue. Thanks!

**Comment by esamattis** [comment]
Whoah, thanks for the super fast fix! :)

**Comment by espoal** [comment]
I think it broke something. The same playbook works on 12.04 ansible install but fails on recent 14.04 install, on this command. I will check harder and eventually report.

**Comment by jimi-c** [comment]
@servermeta if so, please open a new issue for it. Thanks!
