### ISSUE TITLE
Search for templates within the role directory for template lookup

### ISSUE THREAD

**Issue by landryb** [ansible/ansible#7297]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel c6f3a0a4cc) last updated 2014/05/02 09:59:57 (GMT +200)
##### Environment:

Debian/OpenBSD
##### Summary:

Make ansible also search for templates within the role directory for template lookup
##### Steps To Reproduce:

A bit similar to issue 2697, i've just spent 2 hours trying the example from the virt module:

```
- name: define guests in libvirt
  virt: name={{item.name}}
    command=define
    xml="{{ lookup('template', 'libvirt_guest_template.xml.j2') }}"
    uri=lxc:///
    with_items: lxc_guests
```

Problem is, my libvirt_guest_template.xml.j2 is in the corresponding template directory of the role where my task is.
##### Expected Results:

In that case, xml should be the content of the template, with the item values replaced.
##### Actual Results:

xml is empty. I need to use

```
lookup('template', '../templates/libvirt_guest_template.xml.j2')
```

for the task to reach the proper template file.

**Comment by mpdehaan** [comment]
Sorry about this confusion, however, Lookup plugins dig inside the files directory, this is also true of the template lookup.
