### ISSUE TITLE
authorized_key skipping during --check

### ISSUE THREAD

**Issue by jasonmader** [ansible/ansible#7300]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

From OS X managing SLES11SP3
##### Summary:

When **authorized_key** module should be reporting a change to the authorized_keys file, it’s instead reporting skipping.
##### Steps To Reproduce:

```
- authorized_key: user=root key="{{item}}" state=present
  with_file: id_rsa.pub
```

`ansible-playbook site.yml -C`
##### Expected Results:

```
TASK: [master | authorized_key user=root key="" state=present] ***************
changed: [master] => (item=ssh-rsa AAAA…)
```
##### Actual Results:

```
TASK: [master | authorized_key user=root key="" state=present] ***************
skipping: [master] => (item=ssh-rsa AAAA…)
```

**Comment by jimi-c** [comment]
Do you have any options with the key beyond just the regular key data itself?

**Comment by jasonmader** [comment]
None.

**Comment by mpdehaan** [comment]
This means this module doesn't support check mode yet
