### ISSUE TITLE
Templar._finalize replaces None by '', making it impossible for a jinja2 expression to return None

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansible#73010]
##### SUMMARY
There's special handling code in `Templar._finalize` which returns `''` instead of `None` (https://github.com/ansible/ansible/blob/252685092cacdd0f8b485ed6f105ec7acc29c7a4/lib/ansible/template/__init__.py#L982). This makes it impossible for Jinja2 expressions to evaluate to `None`. For example:

```.yaml
- hosts: localhost
  gather_facts: no
  tasks:
    - set_fact:
        test: "{{ none }}"
```
If you run that with `-v`, you get
```
ok: [localhost] => {"ansible_facts": {"test": ""}, "changed": false}
```
Clearly `""` is not `None`.

(This has been previously reported as https://github.com/ansible/ansible/issues/44503, though in that case a workaround solved that problem which is not applicable here. The current problem comes from https://github.com/ansible-collections/community.postgresql/issues/31, where the module's interface accepts `null`/`none` as a valid value - namely SQL's `NULL`. So there is no work-around in this case.)

I'm pretty sure that there is a valid (and important) reason why `Templar._finalize` behaves the way, but as shown in this issue, it has pretty bad side-effects :-)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
templar

##### ANSIBLE VERSION
```paste below
devel
```

**Comment by felixfontein** [comment]
Despite me claiming "there is no workaround", there is one: use the [DEFAULT_JINJA2_NATIVE configuration](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-jinja2-native). With it being set, I correctly obtain:
```
ok: [localhost] => {"ansible_facts": {"test": null}, "changed": false}
```

**Comment by sivel** [comment]
I cannot see us changing this behavior due to backwards compatibility.  There will be people relying on it, and switching to jinja2 native is our recommendation.

See:

* https://github.com/ansible/ansible/issues/41392
* https://github.com/ansible/ansible/issues/57438

**Comment by Andersson007** [comment]
great! @felixfontein @sivel thanks for the clue

**Comment by felixfontein** [comment]
I'm looking forward to when DEFAULT_JINJA2_NATIVE finally switches the default to `true`. Maybe for ansible-core 3.0.0? :-)

(As long as it is possible to set it back to `false`, it would be an acceptable breaking change IMO.)

**Comment by Shrews** [comment]
Since we do not intend to change this behavior, and given the above comments, I'm going to close this issue.
