### ISSUE TITLE
Ubuntu 20.04 - Ubuntu Focal repository not exist in PPA Launchpad

### ISSUE THREAD

**Issue by ionutnechita** [ansible/ansible#73049]
Hi Ansible Team,

I observe this issue:
apt-get update
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Get:2 http://ro.archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Ign:3 http://ppa.launchpad.net/ansible/ansible/ubuntu focal InRelease
Hit:4 http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease
Hit:5 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal InRelease
Hit:6 https://dl.yarnpkg.com/debian stable InRelease
Hit:7 http://ppa.launchpad.net/longsleep/golang-backports/ubuntu focal InRelease
Hit:8 https://download.docker.com/linux/ubuntu focal InRelease
Get:9 http://ro.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Err:10 http://ppa.launchpad.net/ansible/ansible/ubuntu focal Release
  404  Not Found [IP: xxx.xxx.xxx.xxx]
Get:11 http://ro.archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Hit:12 https://deb.nodesource.com/node_14.x focal InRelease
Hit:13 https://packagecloud.io/github/git-lfs/ubuntu focal InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/ansible/ansible/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/.

I notice in dists that there is no folder for the focal, Ubuntu 20.04.
Could you introduce this one too?
This issue is an impediment for me.

Thanks.

**Comment by sivel** [comment]
Duplicate of https://github.com/ansible/ansible/issues/70935
