### ISSUE TITLE
Weird problem with network reuse of TCP ports from apps started from ansible

### ISSUE THREAD

**Issue by smooge** [ansible/ansible#7307]
So we have been running into an issue in our ansible rollout that hasn't occurred before sometime in mid April. About that time we started getting conflicts with services reusing the 5099 fireball port if those processes were started from ansible.

In the latest case, I set up a new hardware box and ran the ansible jobs which load up various services like iscsid, nrpe, etc. All of these usually pull a port from the 10000->65536 when started by themselves, but everyone of them pulled 5099 as their listening port. I had to end up stopping about a dozen processes before I could run ansible again.

What I am wanting to know is if this is known or seen anywhere else and if there is some flag we might have setup which is triggering this that we could turn off.

Thanks.

ansible-1.5.3-2.el6.noarch # From EPEL.

**Comment by smooge** [comment]
Fix that closes file descriptors seems to fix the problem in current testing. Will try more tomorrow to confirm. Thank youl

**Comment by jimi-c** [comment]
Great. I'm going to look into whether we should default that to True in the function declaration, as I believe it's always bad form to leak file descriptors into child processes.
