### ISSUE TITLE
Static/dynamic inventory combination broken by linode.pyc?

### ISSUE THREAD

**Issue by jimmcslim** [ansible/ansible#7308]
I'm combining a static hosts file with the linode.py dynamic inventory plugin in an inventory subdirectory pointed to by ansible.cfg (`hostfile=./inventory`).

The linode.py is marked as executable. A linode.ini also sits in that directory as required by linode.py.

When I run `ansible all --list-hosts` the first time, the names of all hosts both in the static inventory and in my Linode account are listed. The Python interpreter creates linode.pyc in the inventory subdirectory. When I run list-hosts a second time I get;

`ERROR: Invalid ini entry: m - need more than 1 value to unpack`

If I delete the generated linode.pyc bytecode file created by the first run then the command works again, but of course the bytecode file comes back!

Mac OS X 10.9.2, Python 2.7.5 (running out of a virtualenv setup for ansible).

**Comment by jimmcslim** [comment]
Similarly I can run `ansible all -i inventory/linode.py --list-hosts` repeatedly with no issues, or `ansible all -i inventory/hosts --list-hosts` with no issues.

Running `ansible all -i inventory --list-hosts` triggers my error (if linode.pyc bytecode file is present, ok otherwise).

**Comment by jimmcslim** [comment]
I'm working around this for the moment by modifying the first line of `linode.py` to specify `-B` (suppress byte code generation) `#!/usr/bin/env python -B`.

**Comment by srgvg** [comment]
Given that this script is run as a sub process - as a python script, and not imported like a module - I would expect no .pyc file to be generated, at least that is what I see here.

**Comment by jimi-c** [comment]
The above patch should resolve this issue. If you continue having any problems related to this, please let us know. Thanks!
