### ISSUE TITLE
--ask-pass option doesn't work at OSX machines, out of the box.

### ISSUE THREAD

**Issue by alexanderjardim-zz** [ansible/ansible#7316]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel b6b76fe7f2) last updated 2014/05/06 09:29:29 (GMT -200)
##### Environment:

OSX 
13.1.0 Darwin Kernel Version 13.1.0: Wed Apr  2 23:52:02 PDT 2014; root:xnu-2422.92.1~2/RELEASE_X86_64 x86_64
##### Summary:

Option --ask-pass does not work out of the box at OSX systems, as sshpass is not a standard package on it.
##### Steps To Reproduce:

On an OSX machine without sshpass installed (this the default state of OSX)
Run the following command:
`ansible all -u <user> --ask-pass -i <inventory> -m ping`
##### Expected Results:

You should be prompted for the user password.
##### Actual Results:

You get an error like
`fatal: [ip] => to use the 'ssh' connection type with passwords, you must install the sshpass program`

**Comment by jimi-c** [comment]
@alexanderjardim this is normal, as we do not make the askpass package a requirement of the ansible package itself. If you have any further questions regarding this, please let us know. Thanks!
