### ISSUE TITLE
Bug Report: failed to parse: No JSON object could be decoded

### ISSUE THREAD

**Issue by skyler** [ansible/ansible#7319]
##### Issue Type:

Bug Report
##### Ansible Version:

`ansible 1.7 (devel 393124e462) last updated 2014/05/07 11:04:25 (GMT -400)`

but this was also occurring on 1.6.
##### Environment:
- Running `ansible-playbook` from CentOS release 6.5 (Final) x86_64 
- Running against CentOS release 6.3 (Final) x86_64
##### Summary:

Notifying my `reload uwsgi` handler causes a Python exception to occur and the process is aborted.
##### Steps To Reproduce:

Run this handler

```
- name: reload uwsgi
  service: name=uwsgi state=reloaded
```
##### Expected Results:

I expect the service to reload. Reloading the service myself via `initctl reload uwsgi` works without error.
##### Actual Results:

```
NOTIFIED: [uwsgi_base | reload uwsgi] *****************************************
fatal: [192.168.33.12] => failed to parse: SUDO-SUCCESS-uvagmkwaxcmtntabwufxqcfqnucqlxic
Traceback (most recent call last):
  File "/home/skyler/.ansible/tmp/ansible-tmp-1399475247.8-270183899845871/service", line 2411, in <module>
    main()
  File "/home/skyler/.ansible/tmp/ansible-tmp-1399475247.8-270183899845871/service", line 1198, in main
    service.get_service_status()
  File "/home/skyler/.ansible/tmp/ansible-tmp-1399475247.8-270183899845871/service", line 509, in get_service_status
    rc, status_stdout, status_stderr = self.service_control()
  File "/home/skyler/.ansible/tmp/ansible-tmp-1399475247.8-270183899845871/service", line 750, in service_control
    rc_state, stdout, stderr = self.execute_command("%s %s %s" % (self.action, self.name, arguments), daemonize=True)
  File "/home/skyler/.ansible/tmp/ansible-tmp-1399475247.8-270183899845871/service", line 250, in execute_command
    return json.loads(data)
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by jimi-c** [comment]
Hrm, I know we had fixed some issues regarding scripts that spat out some garbage during the init, though it appears this may be a similar situation.

**Comment by jimi-c** [comment]
@skyler what init script are you using for uwsgi?

**Comment by skyler** [comment]
One that I created. It's simple:

```
# Emperor uWSGI script

description "uWSGI Emperor"
start on runlevel [2345]
stop on runlevel [06]

exec /usr/local/bin/uwsgi --uid uwsgi --gid nginx --emperor /etc/uwsgi/sites --vassals-include /etc/uwsgi/default.ini --die-on-term --vacuum
```

uWSGI is pretty chatty when it starts up--at least it is when I run that `exec` command on the terminal.

**Comment by jimi-c** [comment]
That's odd, I can't reproduce this. I added a few options (`--log-syslog --cheaper-busyness-verbose`) to the above command to increase the logging verbosity and see this in /var/log/messages:

<pre>
May  7 15:28:38 centos65 ansible-<stdin>: Invoked with name=uwsgi pattern=None enabled=None state=reloaded sleep=None arguments= runlevel=default 
May  7 15:28:38 centos65 uwsgi: waiting for Emperor death...
May  7 15:28:38 centos65 uwsgi: [emperor] *** RAGNAROK EVOKED ***
May  7 15:28:38 centos65 uwsgi: Wed May  7 15:28:38 2014 - The Emperor is buried.
May  7 15:28:39 centos65 uwsgi: The Emperor has been buried (pid: 6942)
May  7 15:28:39 centos65 uwsgi: ...gracefully killing workers...
....
May  7 15:28:39 centos65 uwsgi: *** starting uWSGI Emperor ***
May  7 15:28:39 centos65 uwsgi: *** Python threads support is disabled. You can enable it with --enable-threads ***
May  7 15:28:39 centos65 uwsgi: Python main interpreter initialized at 0x11aa420
May  7 15:28:39 centos65 uwsgi: your mercy for graceful operations on workers is 60 seconds
May  7 15:28:39 centos65 uwsgi: *** Operational MODE: no-workers ***
May  7 15:28:39 centos65 uwsgi: gracefully (RE)spawned uWSGI master process (pid: 6941)
</pre>

And the ansible playbook that ran it shows normal output:

<pre>
$ ansible-playbook 7319.yml -vv
PLAY [centos65] *************************************************************** 
TASK: [reload uwsgi] ********************************************************** 
<192.168.122.120> REMOTE_MODULE service name=uwsgi state=reloaded
changed: [192.168.122.120] => {"changed": true, "name": "uwsgi", "state": "started"}
PLAY RECAP ******************************************************************** 
192.168.122.120            : ok=1    changed=1    unreachable=0    failed=0   
</pre>

I also tried the same playbook using `sudo: yes` with a non-root user, but no difference in output.

I did install uWSGI via pip, and based on your paths above it would appear you've installed yours directly from source or some other method? I wonder if that's the main difference here, though whenever I run the `initctl` commands directly I'm not seeing any odd output. Just the following:

<pre>
[root@centos65 ~]# initctl restart uwsgi
uwsgi start/running, process 6941
[root@centos65 ~]# initctl reload uwsgi
[root@centos65 ~]# 
</pre>

**Comment by skyler** [comment]
Yes, I compiled uWSGI from source. One thing that I didn't note (that I should have) is that I have `ask_sudo_pass = true` in `ansible.cfg` however, for this specific host, I do not require a sudo password so when prompted I just hit enter and don't provide a password.

**Comment by jimi-c** [comment]
But when you run the initctl commands, do you see any additional output?

**Comment by skyler** [comment]
```
[vagrant@localhost init]$ whoami
vagrant
[vagrant@localhost init]$ sudo su
[root@localhost init]# initctl stop uwsgi
uwsgi stop/waiting
[root@localhost init]# initctl start uwsgi
uwsgi start/running, process 11675
[root@localhost init]# initctl reload uwsgi
[root@localhost init]# initctl restart uwsgi
uwsgi start/running, process 11684
[root@localhost init]#
```

**Comment by skyler** [comment]
Please let me know if I can provide any additional information.

**Comment by jimi-c** [comment]
@skyler can you run your ansible command with `ANSIBLE_KEEP_REMOTE_FILES=yes` pre-pended to the command? That will leave the module on the target system, after which time you can run it directly on the vagrant system. Could you run it that way and copy/paste the output here?

**Comment by aabdnn** [comment]
From my laptop I ran:

$ ANSIBLE_KEEP_REMOTE_FILES=1 ansible bastion3.hadoop.ripe.net -sK -m service -a 'name=hdfs-sync state=restarted'
sudo password: 
bastion3.hadoop.ripe.net | FAILED => failed to parse: 
SUDO-SUCCESS-kmznivmdzmspomcdaqzgxkbtmnuxohxf
Traceback (most recent call last):
  File "/tmp/ansible-tmp-1399973714.05-163067361684244/service", line 2411, in <module>
    main()
  File "/tmp/ansible-tmp-1399973714.05-163067361684244/service", line 1198, in main
    service.get_service_status()
  File "/tmp/ansible-tmp-1399973714.05-163067361684244/service", line 509, in get_service_status
    rc, status_stdout, status_stderr = self.service_control()
  File "/tmp/ansible-tmp-1399973714.05-163067361684244/service", line 750, in service_control
    rc_state, stdout, stderr = self.execute_command("%s %s %s" % (self.action, self.name, arguments), daemonize=True)
  File "/tmp/ansible-tmp-1399973714.05-163067361684244/service", line 250, in execute_command
    return json.loads(data)
  File "/usr/lib64/python2.6/json/**init**.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Next, I logged into bastion3.hadoop.ripe.net, and ran:

# python ansible-tmp-1399973714.05-163067361684244/service

{"state": "started", "changed": true, "name": "hdfs-sync"}

The module does run, and does do what I expected it to do.

**Comment by jimi-c** [comment]
Hrm, so in both of your cases, you seem to be hitting the code that is wanting to daemonize the process. @arhbkb in your case, does hdfs-sync have a proper init script of some kind? I'm unclear as to why this section of code would be reached with @skyler's init script when it does not for my test case.

**Comment by jimi-c** [comment]
On a hunch, could one of you try the following patch?

<pre>
diff --git a/library/system/service b/library/system/service
index ec622ac..f883e00 100644
--- a/library/system/service
+++ b/library/system/service
@@ -209,7 +209,7 @@ class Service(object):
             # Start the command
             if isinstance(cmd, basestring):
                 cmd = shlex.split(cmd)
-            p = subprocess.Popen(cmd, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, preexec_fn=lambda: os.close(pipe[1]))
+            p = subprocess.Popen(cmd, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, close_fds=True, preexec_fn=lambda: os.close(pipe[1]))
             stdout = ""
             stderr = ""
             fds = [p.stdout, p.stderr]
</pre>

We had an issue with the accelerate daemon where processes launched while daemonized were inheriting the file descriptors, which can cause problems for later executions.

**Comment by aabdnn** [comment]
@jimi-c my upstart script looks like this:

start on stopped rc
stop on runlevel [016]

pre-start script
    set +e # don't complain about already started jobs
    start hdfs-sync-instance URL='amqps://server1#hdfs-sync'
    start hdfs-sync-instance URL='amqps://server2#hdfs-sync'
    start hdfs-sync-instance URL='amqps://server3#hdfs-sync'
    start hdfs-sync-instance URL='amqps://server4#hdfs-sync'
    exit 0
end script

If I log into the server, and type "start hdfs-sync", this upstart script actually invokes 4 instances, as shown above. I then have 5 jobs in the "start/running" state. However, only the instances have PIDs, whereas the spawner, hdfs-sync, has no PID:

$ initctl list|grep hdfs
hdfs-sync-instance (amqps://server1#hdfs-sync) start/running, process 28003
hdfs-sync-instance (amqps://server2#hdfs-sync) start/running, process 28012
hdfs-sync-instance (amqps://server3#hdfs-sync) start/running, process 28007
hdfs-sync-instance (amqps://server4#hdfs-sync) start/running, process 28018
hdfs-sync start/running

I won't write out the contents of the "hdfs-sync-instance" script, but it has a "stop on stopping hdfs-sync" stanza. This allows me to "stop hdfs-sync" or "restart hdfs-sync" to stop or restart the instances.

In upstart land, it is okay for a running job to have no PID. Is it possible that this is confusing Ansible?

**Comment by aabdnn** [comment]
@jimi-c I just tried your patch. It has made no difference, and I get the same error message "No JSON object could be decoded".

**Comment by jimi-c** [comment]
@arhbkb after digging through the code a bit more, I'm wondering if the code where data is read/written to the pipes is running into a situation where partial reads/writes are happening. In that same execute_command(), could you increase the buffer sizes for all read calls to something quite a bit larger than the 4096 used currently and see if that resolves the issue? If so, I can come up with a patch that will try handle those more robustly.

**Comment by aabdnn** [comment]
I changed the 3 read() calls in execute_command() to use a buffer of size 65536. It did not help. I still get the exact same error.

**Comment by skyler** [comment]
@jimi-c sorry for taking so long to reply. As you asked, I ran

```
ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook web.yml -i local
```

Which failed with this traceback:

```
NOTIFIED: [uwsgi_base | reload uwsgi] *****************************************
changed: [localhost]
fatal: [192.168.33.12] => failed to parse: SUDO-SUCCESS-tccostycxxmgehxljqzyreeoilbwkclp
Traceback (most recent call last):
  File "/home/skyler/.ansible/tmp/ansible-tmp-1400160533.78-90187794857028/service", line 2411, in <module>
    main()
  File "/home/skyler/.ansible/tmp/ansible-tmp-1400160533.78-90187794857028/service", line 1198, in main
    service.get_service_status()
  File "/home/skyler/.ansible/tmp/ansible-tmp-1400160533.78-90187794857028/service", line 509, in get_service_status
    rc, status_stdout, status_stderr = self.service_control()
  File "/home/skyler/.ansible/tmp/ansible-tmp-1400160533.78-90187794857028/service", line 750, in service_control
    rc_state, stdout, stderr = self.execute_command("%s %s %s" % (self.action, self.name, arguments), daemonize=True)
  File "/home/skyler/.ansible/tmp/ansible-tmp-1400160533.78-90187794857028/service", line 250, in execute_command
    return json.loads(data)
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

(same as before, I believe).

I then logged into the box and ran:

```
[vagrant@localhost ~]$ sudo su
[root@localhost vagrant]# python /home/skyler/.ansible/tmp/ansible-tmp-1400160533.78-90187794857028/service
{"state": "started", "changed": true, "name": "uwsgi"}
```

which you can see worked without an error. This is without applying your patch. Not sure if this adds anything new.

**Comment by jimi-c** [comment]
@skyler thanks, pretty much confirms what @arhbkb mentioned above. Could you try one more test, which would be to run that command over ssh but not through ansible? There's something definitely off in regards to the way that daemonizing code is getting the JSON data.

**Comment by skyler** [comment]
@jimi-c here you go:

```
~/ansible/local (master)> ssh skyler@192.168.33.12 <<'END'
> sudo su
> python /home/skyler/.ansible/tmp/ansible-tmp-1400160533.78-90187794857028/service
> END
Pseudo-terminal will not be allocated because stdin is not a terminal.
skyler@192.168.33.12's password:
{"state": "started", "changed": true, "name": "uwsgi"}
~/ansible/local (master)>
```

**Comment by aabdnn** [comment]
I've just updated to ansible 1.6.2, and this problem is still affecting me. How else can I (or anyone else) help?

**Comment by jimi-c** [comment]
@arhbkb or @skyler, was this working in a previous version, like 1.5 or 1.4? If you can find a version that did not have this issue, we could use `git bisect` to try and identify the commit that started causing problems. If either of you are on IRC, you can ping me there (`jimi|ansible`) and I can walk you through bisect.

**Comment by aabdnn** [comment]
I just tried 1.4.5, and 1.5.0. With these versions, trying to restart a service fails with:

bastion3.hadoop.ripe.net | FAILED >> {
    "failed": true, 
    "msg": "/bin/sh: stop: command not found\n/bin/sh: start: command not found\n"
}

With 1.5.5, I get the "No JSON object could be decoded" error. With the earlier versions, it looks like ansible could not find "stop" and "start" because PATH did not contain /sbin. However, in a minor release in 1.5, that appears to have been fixed.

But please, please, let me stress that the service module _DOES_ work for many upstart-managed services, but fails for just some.

**Comment by jimi-c** [comment]
Ok, I think at this point we need to have a clean setup with steps to reproduce this, for instance please create a new VM, document your installation steps, extra packages, etc. and then the playbook you run on the system to reproduce it. I think that's the only way we're going to pin this down. @arhbkb or @skyler, would one of you be able to provide that?

**Comment by leth** [comment]
I think we're seeing something similar:

```
TASK: [python | Install apt package(s)] *************************************** 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> REMOTE_MODULE apt pkg=python-dev,python-setuptools,python-software-properties,python-pip,build-essential state=latest
<127.0.0.1> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ForwardAgent=yes', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jenkins/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=2206', '-o', 'IdentityFile=/home/jenkins/.vagrant.d/insecure_private_key', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '127.0.0.1', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1401981445.77-144592281645790 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1401981445.77-144592281645790 && echo $HOME/.ansible/tmp/ansible-tmp-1401981445.77-144592281645790'"]
<127.0.0.1> PUT /tmp/tmpQlqn0s TO /home/vagrant/.ansible/tmp/ansible-tmp-1401981445.77-144592281645790/apt
<127.0.0.1> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ForwardAgent=yes', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jenkins/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=2206', '-o', 'IdentityFile=/home/jenkins/.vagrant.d/insecure_private_key', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '127.0.0.1', u'/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=klxfyowsydpxkyecwvdxkhlzepvxsjhk] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-klxfyowsydpxkyecwvdxkhlzepvxsjhk; LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1401981445.77-144592281645790/apt; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1401981445.77-144592281645790/ >/dev/null 2>&1\'"\'"\'\'']
failed: [ttvm.local] => (item=python-dev,python-setuptools,python-software-properties,python-pip,build-essential) => {"failed": true, "item": "python-dev,python-setuptools,python-software-properties,python-pip,build-essential", "parsed": false}
invalid output was: SUDO-SUCCESS-klxfyowsydpxkyecwvdxkhlzepvxsjhk
OpenSSH_5.9p1 Debian-5ubuntu1.4, OpenSSL 1.0.1 14 Mar 2012
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_request_forwards: requesting forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 8702
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Control master terminated unexpectedly
Shared connection to 127.0.0.1 closed.
```

It looks like a problem with the SSH connection sharing...

**Comment by jimi-c** [comment]
Hrm, perhaps the ControlMaster is timing out on long actions for some reason? @leth I see in your example above it looks like you're installing several packages.

**Comment by jimi-c** [comment]
Either that or maybe a firewall is terminating the connection?

**Comment by mpdehaan** [comment]
Seems like in this situation we should catch the exception and log the partial output regardless, but that's not relative to the root cause of the above.

**Comment by bartmcleod** [comment]
I was getting  a similar error with Ansible 1.5.4 when trying to add a repository for the latest php version at this task:
 <code>\- name: add repository for latest php
apt_repository: repo='ppa:ondrej/php5' state=present</code>

Then, when I took a closer look, it appeared I had a typo in the repository name. This was enough to trigger the following error (which looks much like what you have above):
<code>
fatal: [default] => failed to parse: SUDO-SUCCESS-zxuilacwkhkzhcqhyvgqqcumigfexeca
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1404168688.02-72667960863768/apt_repository", line 1509, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1404168688.02-72667960863768/apt_repository", line 394, in main
    sourceslist.add_source(repo)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1404168688.02-72667960863768/apt_repository", line 333, in add_source
    info = self._get_ppa_info(ppa_owner, ppa_name)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1404168688.02-72667960863768/apt_repository", line 302, in _get_ppa_info
    return self._get_ppa_info_curl(lp_api)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1404168688.02-72667960863768/apt_repository", line 315, in _get_ppa_info_curl
    return json.loads(lp_page)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
</code>
When I corrected the typo, everything went just fine. It was hard from the error message to detect the fact that I had made a typo.

**Comment by skyler** [comment]
@jimi-c I can try to create a new VM and document my steps, some time within the next few weeks. I've meant to set aside time to do this but haven't had the opportunity. This isn't too pressing of an issue for me because it doesn't happen for my live CentOS servers, only for my local VM that I use to test my playbooks against. It means I can't fully test playbooks locally, which is a problem, but it's not holding anything up in my org at the moment so it's low priority for me right now. In the meantime I can provide you with any other information you might need.

**Comment by jimi-c** [comment]
@skyler sounds good.

**Comment by jimi-c** [comment]
Hey @skyler, just following up on this to see if there's been any new developments. Thanks!

**Comment by mpdehaan** [comment]
Hi @skler, Any updates?

**Comment by skyler** [comment]
No, none, sorry. At work we're just launching our app so I haven't had time to do anything other than that.

Should be able to get something to you this week though.

**Comment by skyler** [comment]
I haven't done the work of setting up a VM from scratch, but testing another role just now I got a similar error.

```

TASK: [supervisor | start supervisor] *****************************************
fatal: [192.168.33.12] => failed to parse: SUDO-SUCCESS-jhzyatzgpiapvwsgivaeerszxbtysmgo
Traceback (most recent call last):
  File "/home/skyler/.ansible/tmp/ansible-tmp-1407789795.23-188642643136975/service", line 2584, in <module>
    main()
  File "/home/skyler/.ansible/tmp/ansible-tmp-1407789795.23-188642643136975/service", line 1196, in main
    service.get_service_status()
  File "/home/skyler/.ansible/tmp/ansible-tmp-1407789795.23-188642643136975/service", line 507, in get_service_status
    rc, status_stdout, status_stderr = self.service_control()
  File "/home/skyler/.ansible/tmp/ansible-tmp-1407789795.23-188642643136975/service", line 748, in service_control
    rc_state, stdout, stderr = self.execute_command("%s %s %s" % (self.action, self.name, arguments), daemonize=True)
  File "/home/skyler/.ansible/tmp/ansible-tmp-1407789795.23-188642643136975/service", line 250, in execute_command
    return json.loads(data)
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/vagrant/web.retry

192.168.33.12              : ok=63   changed=6    unreachable=1    failed=0
```

And then logging into the host and executing the script I get

```
python /home/skyler/.ansible/tmp/ansible-tmp-1407789795.23-188642643136975/service
{"msg": "start: Unable to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n", "failed": true}
```

"Unable to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory" would be a better error to display than "No JSON object could be decode,"

**Comment by jimi-c** [comment]
@skyler that's interesting, it's not liking the '\n' in that string. Looking at the JSON spec, control characters must be escaped (ie. `\\n`) so we can look into doing that before calling json.loads().

**Comment by skyler** [comment]
@mpdehaan unfortunately I haven't had time to build a box from scratch and test from that. In short, only 80% of my config is in Ansible right now, notably Python 2.7 isn't because at the moment I need to compile it with some flags because I'm using this on CentOS, and a standard 2.7 install doesn't play nicely with CentOS 6.5. So it would take time to set up this test environment which I just haven't been able to dedicate yet.

Anyway, this is another task that's causing my error (the first was uWSGI):

```
- name: start supervisor
  service: name=supervisor state=started
```

I noticed if I set `enabled=yes`, then that produces this error:

```
TASK: [supervisor | start supervisor] *****************************************
failed: [192.168.33.12] => {"failed": true}
msg: cannot detect command to enable service supervisor, typo or init system potentially unknown

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/vagrant/web.retry

192.168.33.12              : ok=63   changed=6    unreachable=0    failed=1
```

Notably both these errors happen when trying to start an Upstart service. Maybe this will help.

**Comment by jimi-c** [comment]
@skyler I just so happened to merge in a patch yesterday to the devel branch which should resolve the supervisor issue. The issue appears to have been related to the fact that upstart on CentOS 6 is quite a bit out of date, and did not support the "manual" param (instead you have to use "start on manual").

**Comment by johnhamelink** [comment]
This error exists for me on ansible 1.7.1 installed from pip on archlinux:

```
TASK: [Install Gem Prerequisites] ********************************************* 
failed: [alloa.app.example.com] => (item=libpq-dev,nodejs) => {"failed": true, "item": "libpq-dev,nodejs", "parsed": false}
invalid output was: SUDO-SUCCESS-jmypmdwoaanmpsjispueepmzehlonoof
Segmentation fault (core dumped)
```

Rebooting the server solves the problem for me, but obviously that's not an ideal solution...

**Comment by mpdehaan** [comment]
I think you guys are seeing different issues - especially because you have a core dump, let's keep this issue on topic about the service module.

The sudo success part is actually noise.

Let's figure out the core dump on arch seperately and figure out why it is doing that.

**Comment by leopepe** [comment]
I have the same problem regarding the message "mux_client_read_packet: read header failed: Broken pipe".

I have researched about it and find no objective conclusions pointing out the root of the problem. After a couple of tests I realize that the problem is linked to SSH multiplexing behavior. My network has a very lazy latency (more than 10 seconds). Analysing ansible parrameters of the connection attempted It's possible to see that ansible overrides the timeout configuration o ssh_config to 10 seconds.
It might be possible that the error occurs in some cases due to network latency.

I have tried higher timeout limits but the problem stills the same. The error happens independently of the timeout set. I tried 60 seconds of timeout and the problem happens within 21 seconds. 

Not sure the root cause of the problem yet. :(

**Comment by leth** [comment]
@mpdehaan Perhaps if this string is a red-herring ansible should remove it from the output to avoid people looking in the wrong place for the problem.

**Comment by jimi-c** [comment]
@leth I believe we have done so already in the devel branch. We recently added better detection code to catch tracebacks, which were one of the main reasons the SUDO-SUCCESS error would be seen. Additional code was added to check for an un-caught SUDO-SUCCESS too, so hopefully we'll see better output that will get to the root cause rather than this generic message.

**Comment by evgeny-goldin** [comment]
Hi, I'm getting this error with Ansible 1.8.2 but only when running long-lasting Gatling stress-test simulations:

```
failed: [54.154.191.110] => (item=ArtifactoryGet50) => {"failed": true, "item": "ArtifactoryGet50", "parsed": false}
SUDO-SUCCESS-ligvhvwixbgbwixjokonfnwtpwrvnskz
```

I can reproduce it very reliably. Could this help? If yes - I can set up a proper example but later as for now I need to move on and bypass this problem by running simulations outside Ansible.

**Comment by skyler** [comment]
In the latest devel version, this is the output I get when this happens. I believe it's the same issue.
```
NOTIFIED: [uwsgi_base | reload uwsgi] *****************************************
failed: [192.168.33.12] => {"failed": true, "parsed": false}
SUDO-SUCCESS-sqkkggdsaxdfspwggwosmqfakfsykxfz
{"msg": "[Errno 2] No such file or directory", "failed": true, "cmd": "initctl version", "rc": 2}
{"msg": "uwsgi: unrecognized service\n", "failed": true}
```

Version info:
```
ansible-playbook 1.9 (devel 8f06ba2bc1) last updated 2015/02/05 14:06:23 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 600fc15b42) last updated 2015/02/05 14:09:13 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 77485f6c6a) last updated 2015/02/05 14:09:19 (GMT -400)
  v2/ansible/modules/core: (detached HEAD 600fc15b42) last updated 2015/02/05 14:09:26 (GMT -400)
  v2/ansible/modules/extras: (detached HEAD 77485f6c6a) last updated 2015/02/05 14:09:32 (GMT -400)
  configured module search path = /home/vagrant/ansible/src/library:/usr/share/ansible/:/home/vagrant/ansible/src/library
```

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). 

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
