### ISSUE TITLE
Wrong Ansible version returned

### ISSUE THREAD

**Issue by wtout** [ansible/ansible#73218]
##### SUMMARY

The command ansible --version returns the wrong version that is installed. The problem has been observed with versions 2.10.3 and 2.10.5

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.10.4
  config file = None
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/lib/python3.6/site-packages/ansible
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS Linux release 7.8.2003 (Core)

##### STEPS TO REPRODUCE

- Install latest version (2.10.5) of Ansible using pip3:
  pip3 install --user ansible

Installation output:
[ansible@ansible ~]$ pip3 install --user ansible
Collecting ansible
  Using cached https://files.pythonhosted.org/packages/9e/aa/59e93180a54701c8e0c803729d860a8010b6a07cede54c63e47fa6681cb0/ansible-2.10.5.tar.gz
Collecting ansible-base<2.11,>=2.10.4 (from ansible)
  Using cached https://files.pythonhosted.org/packages/2d/e0/3eabf1be1211f653c73bc7827084c301aaefc6d8fc73e33572172cf0306b/ansible-base-2.10.4.tar.gz
Requirement already satisfied: jinja2 in ./.local/lib/python3.6/site-packages (from ansible-base<2.11,>=2.10.4->ansible)
Requirement already satisfied: PyYAML in ./.local/lib/python3.6/site-packages (from ansible-base<2.11,>=2.10.4->ansible)
Requirement already satisfied: cryptography in ./.local/lib/python3.6/site-packages (from ansible-base<2.11,>=2.10.4->ansible)
Requirement already satisfied: packaging in ./.local/lib/python3.6/site-packages (from ansible-base<2.11,>=2.10.4->ansible)
Requirement already satisfied: MarkupSafe>=0.23 in ./.local/lib/python3.6/site-packages (from jinja2->ansible-base<2.11,>=2.10.4->ansible)
Requirement already satisfied: cffi>=1.12 in ./.local/lib/python3.6/site-packages (from cryptography->ansible-base<2.11,>=2.10.4->ansible)
Requirement already satisfied: six>=1.4.1 in ./.local/lib/python3.6/site-packages (from cryptography->ansible-base<2.11,>=2.10.4->ansible)
Requirement already satisfied: pyparsing>=2.0.2 in ./.local/lib/python3.6/site-packages (from packaging->ansible-base<2.11,>=2.10.4->ansible)
Requirement already satisfied: pycparser in ./.local/lib/python3.6/site-packages (from cffi>=1.12->cryptography->ansible-base<2.11,>=2.10.4->ansible)
Installing collected packages: ansible-base, ansible
  Running setup.py install for ansible-base ... done
  Running setup.py install for ansible ... done
Successfully installed ansible-2.10.5 ansible-base-2.10.4

```yaml

```

##### EXPECTED RESULTS

[ansible@ansible ~]$ ansible --version
ansible 2.10.5
  config file = None
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/lib/python3.6/site-packages/ansible
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

##### ACTUAL RESULTS

[ansible@ansible ~]$ ansible --version
ansible 2.10.4
  config file = None
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/lib/python3.6/site-packages/ansible
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```paste below

```

**Comment by sivel** [comment]
The `ansible` command is provided by the `ansible-base` package, and returns the version of the `ansible-base` package.

See https://github.com/ansible/ansible/pull/72287 for work being done to clarify that the version is not of the "ansible" package.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
