### ISSUE TITLE
Role vars overriding each other (Ansible 1.6.0)

### ISSUE THREAD

**Issue by hkariti** [ansible/ansible#7321]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

Running from Ubuntu 12.10, managing Ubuntu 13.10
##### Summary:

If two roles define a variable in their vars/ directory, the value that's defined in the role that is listed last will be used for ALL the roles.
##### Steps To Reproduce:

Create two roles:

```
roles/test1
├── tasks
│   └── main.yml
└── vars
    └── main.yml
roles/test2
├── tasks
│   └── main.yml
└── vars
    └── main.yml
```

test1/vars/main.yml:

```

---
variable: test1
```

test2/vars/main.yml:

```

---
variable: test2
```

both tasks files contain this:

```

---
- debug: msg="Variable is {{variable}}"
```

Now create this playbook:

```
- hosts: localhost
  roles:
     - test1
     - test2
```
##### Expected Results:

```
TASK: [test1 | debug msg="Variable is  test1"] ******************************** 
ok: [localhost] => {
    "item": "", 
    "msg": "Variable is  test1"
}

TASK: [test2 | debug msg="Variable is  test2"] ******************************** 
ok: [localhost] => {
    "item": "", 
    "msg": "Variable is  test2"
}
```
##### Actual Results:

```
TASK: [test1 | debug msg="Variable is  test1"] ******************************** 
ok: [localhost] => {
    "item": "", 
    "msg": "Variable is  test2"
}

TASK: [test2 | debug msg="Variable is  test2"] ******************************** 
ok: [localhost] => {
    "item": "", 
    "msg": "Variable is  test2"
}
```

**Comment by jimi-c** [comment]
Using your examples above, I am unable to reproduce this on 1.6 or the devel branch:

<pre>
# ansible-playbook 7321.yml 
PLAY [localhost] ************************************************************** 
TASK: [7321_1 | debug msg="Variable is test1"] ******************************** 
ok: [127.0.0.1] => {
    "item": "", 
    "msg": "Variable is test1"
}
TASK: [7321_2 | debug msg="Variable is test2"] ******************************** 
ok: [127.0.0.1] => {
    "item": "", 
    "msg": "Variable is test2"
}
PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   
</pre>

Could you double check your playbooks for any typos or other mistakes?

**Comment by jimi-c** [comment]
Please note that outside of the roles, the behavior you've described is normal. All variables have a global scope outside of roles, so if you access the variable in another role where the variable is not defined, or from the main play, you'll get the value of the last role to be included.

**Comment by hkariti** [comment]
Outside of roles I agree. I'll have to check my playbook again when I'm
near a computer. I got the reported result on two different machines as
well, so I'm surprised you can't reproduce it.

**Comment by hkariti** [comment]
Ok, apparently this only happens if gathering facts. Rerun without the `gather_facts: no` line.

**Comment by jimi-c** [comment]
Ok yes, I see this. Thanks for pinpointing it, I'll look into this ASAP.

**Comment by bcoca** [comment]
This might be related to the new gather facts behavior,  test to see if
changing the gathering setting in ansible.cfg to 'smart' brings back the
old behavior.
​

**Comment by hkariti** [comment]
both `smart` and `implicit` produce the wrong results.

**Comment by jimi-c** [comment]
I thought smart was the default?

**Comment by bcoca** [comment]
no, Micheal changed it to implicit.​

**Comment by jimi-c** [comment]
Looks like this commit is the culprit: e83a494e41133f0dd36bf84b7315b3231ba9e11b

**Comment by sivel** [comment]
@jimi-c I also ran into an issue yesterday with e83a494e41133f0dd36bf84b7315b3231ba9e11b also.

I had a variable defined in vars/main.yml in a role.  Attempting to change this variable with set_fact within that role would fail to actually change the variable.

**Comment by bcoca** [comment]
IIRC that commit restored proper vars override order​

**Comment by jimi-c** [comment]
@bcoca it did, so unfortunately I'm going to have to figure out another way to correct that.

**Comment by jimi-c** [comment]
Ok, I believe I figured this one out (finally). This patch is working to fix both issues:

<pre>
diff --git a/lib/ansible/playbook/play.py b/lib/ansible/playbook/play.py
index 639f4c0..b41c676 100644
--- a/lib/ansible/playbook/play.py
+++ b/lib/ansible/playbook/play.py
@@ -855,5 +855,4 @@ class Play(object):
 
         # finally, update the VARS_CACHE for the host, if it is set
         if host is not None:
-            self.playbook.VARS_CACHE[host].update(self.vars)
             self.playbook.VARS_CACHE[host].update(self.playbook.extra_vars)
diff --git a/lib/ansible/runner/__init__.py b/lib/ansible/runner/__init__.py
index feda312..639c040 100644
--- a/lib/ansible/runner/__init__.py
+++ b/lib/ansible/runner/__init__.py
@@ -570,9 +570,11 @@ class Runner(object):
         hostvars = HostVars(combined_cache, self.inventory, vault_password=self.vault_pass)
 
         # use combined_cache and host_variables to template the module_vars
+        # we update the inject variables with the data we're about to template
+        # since some of the variables we'll be replacing may be contained there too
         module_vars_inject = utils.combine_vars(combined_cache.get(host, {}), host_variables)
+        module_vars_inject.update(self.module_vars)
         module_vars = template.template(self.basedir, self.module_vars, module_vars_inject)
-
         inject = {}
         inject = utils.combine_vars(inject, self.default_vars)
         inject = utils.combine_vars(inject, host_variables)
</pre>

**Comment by jimi-c** [comment]
I've gone ahead and merged the above patch in, so this should be resolved. Please let us know if you continue seeing any problems related to this. Thanks!

**Comment by hkariti** [comment]
Seems to work .Thank you!

**Comment by vvo** [comment]
Wooaa lose a lot of time on this issue, thanks for resolution
