### ISSUE TITLE
apt_repository module error and usage of proxies when behind a firewall

### ISSUE THREAD

**Issue by jcftang** [ansible/ansible#7322]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6
##### Environment:

Ubuntu 12.04 on all hosts and master machine where ansible is run
##### Summary:

apt_repository fails add a repo and tries to connect directly to internet and does not use proxies from environment as expected.
##### Steps To Reproduce:

Have this in a playbook, this is executed as root so there are no modifications to the environment.
- apt_repository: repo="ppa:rquillo/ansible" state=present

I also have my https_proxy variables set in /etc/environment
##### Expected Results:

apt_repository should get the keys via the https_proxy set in the environment and then add the repository.
##### Actual Results:

<pre>
TASK: [common | apt_repository repo="ppa:rquillo/ansible" state=present] ******
failed: [myhost.tcd.ie] => {"failed": true, "item": ""}
msg: Failed to connect to launchpad.net:443.
</pre>

I suspect when pycurl was removed as a dependancy this started to happen.

**Comment by jimi-c** [comment]
That's odd, according to https://docs.python.org/2/library/urllib2.html if the `*_proxy` environment variables are set, then they will be used. I'll look into this.

**Comment by jcftang** [comment]
To clarify, the playbooks that I am running haven't changed hugely just minor additions/removals of packages in my environment, the only thing that has changed has been the ansible versions. I can roll back to 1.5.5 or earlier to see where the problems first appeared, I upgraded from 1.5.3 up to 1.6 in the last day or so.

**Comment by jcftang** [comment]
Looking at ansible/module_utils/urls.py, the fetch_url defaults with user_proxy=False, the apt_repository module in line ~316 (response, info = fetch_url(self.module, lp_api, headers=headers)  doesn't seem to check if a proxy should be used or not, but I guess that should be done helper and not the module itself.

**Comment by dcajacob** [comment]
I've seen this too, but on earlier versions of ansible.  Manually running a pip install on the remote worked when a proxy is set, but it always failed with ansible.

**Comment by jimi-c** [comment]
@jcftang unfortunately, I can't reproduce this. I've installed squid on a test VM (ubuntu 14.04) and exported http/https_proxy as follows:

<pre>
$ env | grep proxy
http_proxy=http://localhost:3128
https_proxy=http://localhost:3128
</pre>

When I run the command `ansible -m apt_repository -a 'repo="ppa:rquillo/ansible" state=present' -i localhost, -c local all`, I see the connection go through squid (tailing the access.log for squid) as expected without having to set the proxy anywhere else.

To further debug this, can you write up a quick playbook that executes the above `env | grep proxy` command via a shell to make sure your environment settings are being picked up correctly? You say that the proxy is configured in `/etc/environment`, but is that on the local machine running ansible or he target machine you're managing (or both)?

**Comment by jcftang** [comment]
@jimi-c Yes, both machines are ubuntu (the master and the target) and have the proxies set in the /etc/environment file, I'm also executing things as root so it shouldn't be a problem with sudo not passing the environment variables.

Here's the output from running env | grep proxy via the shell module

<pre>
$ ansible-playbook -l 134.226.xxx.yyy -i hosts.production common.yml -vvvv
PLAY [all] ********************************************************************
GATHERING FACTS ***************************************************************
<134.226.xxx.yyy> ESTABLISH CONNECTION FOR USER: root
<134.226.xxx.yyy> REMOTE_MODULE setup
<134.226.xxx.yyy> EXEC ['ssh', '-C', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'ForwardAgent=yes', '-o', 'StrictHostKeyChecking=no', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '134.226.xxx.yyy', u"/bin/sh -c 'LC_CTYPE=en_US.UTF-8
LANG=en_US.UTF-8 /usr/bin/python'"]
ok: [134.226.xxx.yyy]
TASK: [shell env | grep proxy] ************************************************
<134.226.xxx.yyy> ESTABLISH CONNECTION FOR USER: root
<134.226.xxx.yyy> REMOTE_MODULE command env | grep proxy #USE_SHELL
<134.226.xxx.yyy> EXEC ['ssh', '-C', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'ForwardAgent=yes', '-o', 'StrictHostKeyChecking=no', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '134.226.xxx.yyy', u"/bin/sh -c 'LC_CTYPE=en_US.UTF-8
LANG=en_US.UTF-8 /usr/bin/python'"]
changed: [134.226.xxx.yyy] => {"changed": true, "cmd": "env | grep proxy ", "delta": "0:00:00.003480", "end": "2014-05-15 09:39:18.835543", "rc": 0, "start": "2014-05-15 09:39:18.832063", "stderr": "", "stdout": "HTTPS_PROXY=http://proxy.tchpc.tcd.ie:8080\nhttps_proxy=http://proxy.tchpc.tcd.ie:8080\nhttp_proxy=http://proxy.tchpc.tcd.ie:8080\nftp_proxy=http://proxy.tchpc.tcd.ie:8080\nFTP_PROXY=http://proxy.tchpc.tcd.ie:8080\nHTTP_PROXY=http://proxy.tchpc.tcd.ie:8080"}
PLAY RECAP ********************************************************************
134.226.xxx.yyy            : ok=2    changed=1    unreachable=0    failed=0
</pre>

**Comment by jimi-c** [comment]
And the proxy you have listed is reachable on that port from the host you're trying? Beyond that, can you run a tcpdump on the target system while ansible is running to see if the packets are in fact being sent to the proxy or to the ubuntu servers? Everything I'm seeing says those environment variables should be used automatically by the urllib\* calls, and it appears you're setting them correctly.

**Comment by jcftang** [comment]
The proxy server does work and is contactable by my target machines (as I can run the apt module to install things)

I ran a tcpdump to see if the target ever connects to the proxy by doing this...

<pre>
# tcpdump ip host proxy.tchpc.tcd.ie and not port ssh
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
</pre>

It never connects out to the proxy server when I try and add a repository. I'm a little overrun with other stuff right now, but I will see if I can do a git bisect tomorrow as well to see where this first occurred.

**Comment by jimi-c** [comment]
@jcftang that'd be great, thanks!

**Comment by jcftang** [comment]
I ran a bisect. The first bad commit is....

<pre>
7af8a33def34519de5ca390c47bdbd432d7b7ee2 is the first bad commit
commit 7af8a33def34519de5ca390c47bdbd432d7b7ee2
Author: Matt Martz <matt@sivel.net>
Date:   Mon Mar 17 11:31:04 2014 -0500
    remove dependency on pycurl from apt_repository by using module_utils/urls.py instead
:040000 040000 b40a4775f0fd1f3b29ddc7911fe733bd6a35f937 b805e7c315aa23d86a4900159655cfd6bd46e484 M  library
bisect run success
</pre>

I can paste the output of the bisect to a gist if you require it.

**Comment by jimi-c** [comment]
Nope, that's all I need.

**Comment by jcftang** [comment]
@jimi-c Just in case if you do, the output is here at https://gist.github.com/jcftang/8b0da6bca30b04d1cccd

hope the above helps.

**Comment by jimi-c** [comment]
Thanks, unfortunately knowing it was that commit is not helpful. I just tried again with this playbook:

<pre>
- hosts: ubuntu1204
  tasks:
  - apt_repository: repo="ppa:rquillo/ansible" state=present
    environment:
      http_proxy: 'http://192.168.122.113:3128'
      https_proxy: 'http://192.168.122.113:3128'
</pre>

since I noticed earlier I was trying with 14.04, which did not match your system exactly. However, the result was the same:

<pre>
TASK: [apt_repository repo="ppa:rquillo/ansible" state=present] *************** 
changed: [192.168.122.110]
</pre>

with the traffic being seen through the squid proxy on .113:

<pre>
1400181195.103    838 192.168.122.110 TCP_MISS/200 1181 GET http://keyserver.ubuntu.com/pks/lookup? - HIER_DIRECT/91.189.89.49 application/pgp-keys
... lots more output ...
</pre>

Can you try with the same syntax I have above, using the environment option to directly specify things for the task? Beyond that, I believe there is something in your environment preventing the proxies settings from being picked up properly.

**Comment by jcftang** [comment]
@jimi-c Was thinking that bisect didn't really help... anyway, here's that output...

<pre>
 $ ansible-playbook -l 134.226.xxx.yyy -i hosts.production common.yml -vvvv
 PLAY [all] ********************************************************************
 GATHERING FACTS ***************************************************************
 <134.226.xxx.yyy> ESTABLISH CONNECTION FOR USER: root
 <134.226.xxx.yyy> REMOTE_MODULE setup
 <134.226.xxx.yyy> EXEC ['ssh', '-C', '-vvv', '-o', 'ControlMaster=auto', '-o',                      'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'ForwardAgent=yes', '-   o', 'StrictHostKeyChecking=no', '-o', 'KbdInteractiveAuthentication=no', '-o',                      'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o',                  'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '134.226.xxx.yyy', u"/   bin/sh -c 'LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/python'"]
 ok: [134.226.xxx.yyy]
 TASK: [apt_repository repo="ppa:rquillo/ansible" state=present] ***************
 <134.226.xxx.yyy> ESTABLISH CONNECTION FOR USER: root
 <134.226.xxx.yyy> REMOTE_MODULE apt_repository repo="ppa:rquillo/ansible" state=present
 <134.226.xxx.yyy> EXEC ['ssh', '-C', '-vvv', '-o', 'ControlMaster=auto', '-o',                      'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'ForwardAgent=yes', '-   o', 'StrictHostKeyChecking=no', '-o', 'KbdInteractiveAuthentication=no', '-o',                      'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o',                  'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '134.226.xxx.yyy', u"/   bin/sh -c 'LC_CTYPE=en_US.UTF-8 http_proxy=http://proxy.tchpc.tcd.ie:8080 https_proxy=http://proxy. tchpc.tcd.ie:8080 LANG=en_US.UTF-8 /usr/bin/python'"]
 failed: [134.226.xxx.yyy] => {"failed": true}
 msg: Failed to connect to launchpad.net:443.
 FATAL: all hosts have already failed -- aborting
 PLAY RECAP ********************************************************************
            to retry, use: --limit @/home/jtang/common.retry
 134.226.xxx.yyy            : ok=1    changed=0    unreachable=0    failed=1
</pre>

**Comment by jimi-c** [comment]
Well it did eliminate any later patches from being the problem, so at least we know it's at least in the original implementation. Unfortunately it looks like you're seeing the exact same output.

**Comment by jimi-c** [comment]
The above patch should resolve this issue. Please let us know if you continue having any problems related to this issue. Thanks!

**Comment by jcftang** [comment]
@jimi-c just verified that the patch has fixed the issue on my end. Thanks!

**Comment by dcajacob** [comment]
I tried catting env to a file as you suggested.  There is no proxy env variable set.  However, if I SSH into the machine, proxy is set and I even have it set in my host_vars file for the specific machine...

I am running 1.7.1 at this point, by the way.

**Comment by dcajacob** [comment]
Disregard.  I misunderstood the nature of the manner in which proxy variables can be used in ansible.  I thought it would apply to the whole play or role.  I see now that it is really on a per-task basis.  I could really use a whole play or role setting, so maybe I'll code that up and submit it.

**Comment by fullergalway** [comment]
Note to others encountering this issue for Ubuntu when using sudo, try adding this into /etc/sudoers:
    Defaults env_keep="no_proxy http_proxy https_proxy"

**Comment by avoidik** [comment]
Why it was closed? Pretty much the same issue here https://github.com/ansible/ansible/issues/31691
