### ISSUE TITLE
docker module traces with KeyError: 'Ghost'

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#7330]
##### Issue Type:

Bug report
##### Ansible Version:

1.6
##### Environment:

Workstation: Archlinux
Managed node: Ubuntu Precise (12.04)
##### Summary:

Trying to install a private docker registry which results in a Python stack trace thrown as "KeyError: 'Ghost'".
##### Steps To Reproduce:

```
- hosts: all
  tasks:
    - name: Install private docker registry
      docker: image='samalba/docker-registry' name=registry detach=true ports=5000:5000
```
##### Expected Results:

Running docker container.
##### Actual Results:

Ansible breaks with Python stacktrace. In fact the container is running properly but the Ansible run breaks.

```
Traceback (most recent call last):
File "/tmp/ansible/kusch/ansible-tmp-1399540829.6-154372885089505/docker", line 1922, in <module>
main()
File "/tmp/ansible/kusch/ansible-tmp-1399540829.6-154372885089505/docker", line 713, in main
facts = manager.get_running_containers()
File "/tmp/ansible/kusch/ansible-tmp-1399540829.6-154372885089505/docker", line 527, in get_running_containers
  if i['State']['Running'] == True and i['State']['Ghost'] == False:
KeyError: 'Ghost'
```

**Comment by etehtsea** [comment]
I have similar problem after upgrade to ansible 1.6.

```
failed: [docker-01.vbox] => {"failed": true, "parsed": false}
invalid output was: SUDO-SUCCESS-imajjsytebmqcqkoxmgplauttreznkcq
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1399546185.36-39970679925453/docker", line 1922, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1399546185.36-39970679925453/docker", line 704, in main
    containers = manager.create_containers(delta)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1399546185.36-39970679925453/docker", line 546, in create_containers
    if docker.utils.compare_version('1.10', self.client.version()['ApiVersion']) < 0:
KeyError: 'ApiVersion'
```

**Comment by mpdehaan** [comment]
What version is your docker python module?  Is it at the latest version?

**Comment by etehtsea** [comment]
I've got first error with ansible 1.5.5/docker 0.11.1 and latter with ansible 1.6.1/docker 0.9.1.

ansible 1.5.5/docker 0.9.1 is the working combination.

**Comment by jimi-c** [comment]
The ApiVersion issue appears to be addressed by the pull request in https://github.com/ansible/ansible/pull/7351. The "Ghost" issue itself should have been resolved by a PR merged in last week.

**Comment by jimi-c** [comment]
@spul have you had a chance to look at the PR #7351 to see if it will address your issue?

**Comment by ghost** [comment]
Hi, didn't have any chance to test/get back to you earlier. b82813b4 does not fix this issue for me.
Additional information (from Vagrant VM, Ubuntu 12.04 (precise) as managed node):
- Docker version 0.11.1, build fb99f99
- docker-py installed from git master branch at https://github.com/dotcloud/docker-py
  - currently version 0.3.2-dev

**Comment by jimi-c** [comment]
@spul thanks.

**Comment by discordianfish** [comment]
@spul Have you tried it with the latest ansible? If so, what (I suppose new) error do you get?

**Comment by CaptTofu** [comment]
I also get this error, latest code.

**Comment by CaptTofu** [comment]
https://github.com/ansible/ansible/pull/7445

Fixed! My day has greatly improved!

**Comment by mitchyg** [comment]
CaptTofu, the dict .get() will not throw a KeyError, so you shouldn't need the has_key() check?

Either way changing the line from:

```
if i['State']['Running'] == True and i['State']['Ghost'] == False:
```

to

```
if i['State']['Running'] == True and i['State'].get('Ghost', False) == False:
```

Solved the problem for me.

**Comment by CaptTofu** [comment]
I’ll modify my change.

**Comment by rubycut** [comment]
@mitchyg   Can we merge your oneliner? This issue makes whole module broken.

**Comment by ghost** [comment]
Oneliner from @mitchyg fixes this issue for me. I'd go for a merge :)

**Comment by jimi-c** [comment]
This should have been fixed in ea71c0c317850dcccdce35a610a03a8947f2b56b, if someone could confirm that?

**Comment by rubycut** [comment]
@jimi-c   I added this to my production ansible installed from package and it worked:
`if i['State']['Running'] == True and i['State'].get('Ghost', False) == False:`

you only added parentheses around that so I assume it works, but this commit you mentioned is not yet merged.

**Comment by jimi-c** [comment]
@rubycut it is merged in devel:

<pre>
git show ea71c0c317850dcccdce35a610a03a8947f2b56b
commit ea71c0c317850dcccdce35a610a03a8947f2b56b
Author: Johannes 'fish' Ziemke <github@freigeist.org>
Date:   Thu May 8 23:17:48 2014 +0200
    Fix: Remove check for Ghost state
    
    This fixed the just committed change handling non existent Ghost state.
diff --git a/library/cloud/docker b/library/cloud/docker
index 93566c4..f9aabf2 100644
--- a/library/cloud/docker
+++ b/library/cloud/docker
@@ -524,7 +524,7 @@ class DockerManager:
     def get_running_containers(self):
         running = []
         for i in self.get_deployed_containers():
-            if i['State']['Running'] == True and i['State'].get('Ghost', False):
+            if i['State']['Running'] == True and i['State'].get('Ghost', False) == False:
                 running.append(i)
 
         return running
</pre>

Or were you just meaning that it has not been merged into 1.6.x? We will be releasing 1.6.2 soon, which will include this fix.

**Comment by rubycut** [comment]
Yes, I was mentioning that 94776b9 was not merged, but  ea71c0c is merged to devel, so I guess we can close this issue.

**Comment by jimi-c** [comment]
Ok, closing this. If there are any further questions, please let us know. Thanks!

**Comment by antonio** [comment]
This is is still failing for me using the `devel` branch, see below

```
TASK: [start the database container] ******************************************
failed: [192.168.231.150] => {"failed": true, "parsed": false}
invalid output was:
SUDO-SUCCESS-sqxrmublmtlzfteoumzhonupcyghaupi
Traceback (most recent call last):
  File "/home/antonio/.ansible/tmp/ansible-tmp-1402486747.14-259714596075111/docker", line 1922, in <module>
    main()
  File "/home/antonio/.ansible/tmp/ansible-tmp-1402486747.14-259714596075111/docker", line 713, in main
    facts = manager.get_running_containers()
  File "/home/antonio/.ansible/tmp/ansible-tmp-1402486747.14-259714596075111/docker", line 527, in get_running_containers
    if i['State']['Running'] == True and i['State']['Ghost'] == False:
KeyError: 'Ghost'
```

The corresponding line in the playbook being

```
- name: start the database container
  docker: image=database state=running
```

/cc @rubycut @jimi-c

**Comment by antonio** [comment]
Oops, looks like I have both 1.6.1 and 1.6.3 installed and it's picking the old one, I'm sorry for the noise!

**Comment by MichaelBaydoun** [comment]
I need to add 10 lines to the middle of a file where the rest of the file is
dynamic
Since it¹s dynamic I need to use something like lineinfile
I¹d rather invoke lineinfile 10 times as that seems messy

Suggestions?

**Comment by CaptTofu** [comment]
What about using a template?

**Comment by jimi-c** [comment]
@IndyMichaelB this type of question is better suited for the mailing list, and definitely should not be posted on old issues.
