### ISSUE TITLE
Can't see docker build output when run from an ansible playbook

### ISSUE THREAD

**Issue by HeisenbergTT** [ansible/ansible#7331]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.5
##### Environment:

MAC OS X mavericks 
##### Summary:

Hi,

I am not able to see any output from ansible when I run a docker build command using ansible, even with the -vvvv flag on.

Thanks in advance.

Playbook command:

```
- name:  Docker build
  shell: docker build -t image .
```
##### Steps To Reproduce:

Playbook command:

```
- name:  Docker build
  shell: docker build -t image .
```
##### Expected Results:

I expect seeing the docker build output in my terminal, especially when running ansible with -vvvv.
##### Actual Results:

I see minimal output, making it difficult to debug.

**Comment by jimi-c** [comment]
Are you not seeing output on errors, or just in general?

**Comment by mpdehaan** [comment]
The docker build call is not going to return anything until it's done, this is just a realtime output question.

I would consider doing dockerfiles that call ansible instead and go through the docker commands.

**Comment by krisskross** [comment]
I have the same problem.
