### ISSUE TITLE
Fact from vars/main.yml in role not able to be modified by set_fact

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#7332]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.7 (devel 77a47dbb2d) last updated 2014/05/07 16:24:13 (GMT -500)
```
##### Environment:

Control: Mac OS, virtualenv, python 2.7.5

Target: N/A
##### Summary:

When a var is set in `vars/main.yml`, attempting to update that fact in a task within the role fails to actual update the fact.

The git bisect yields e83a494e41133f0dd36bf84b7315b3231ba9e11b

Commenting out the line added from the above offending commit resolves the issue.

Just for cross linking purposes, there is another issue that seems to be affected by this same commit: #7321
###### Role structure

```
test
├── tasks
│   └── main.yml
└── vars
    └── main.yml
```
###### vars/main.yml

```
test_fact: apples
```
###### tasks/main.yml

```
- debug:
    var: test_fact

- set_fact:
    test_fact: oranges

- debug:
    var: test_fact
```
###### test.yml (playbook)

```

---
- hosts: localhost
  connection: local
  roles:
    - test
```
1. Run the above playbook and role
##### Expected Results:

The second debug task shows "oranges"

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [test | debug ] *********************************************************
ok: [localhost] => {
    "item": "",
    "test_fact": "apples"
}

TASK: [test | set_fact ] ******************************************************
ok: [localhost]

TASK: [test | debug ] *********************************************************
ok: [localhost] => {
    "item": "",
    "test_fact": "oranges"
}

PLAY RECAP ********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0
```
##### Actual Results:

The second debug task shows "apples"

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [test | debug ] *********************************************************
ok: [localhost] => {
    "item": "",
    "test_fact": "apples"
}

TASK: [test | set_fact ] ******************************************************
ok: [localhost]

TASK: [test | debug ] *********************************************************
ok: [localhost] => {
    "item": "",
    "test_fact": "apples"
}

PLAY RECAP ********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0
```

**Comment by sivel** [comment]
I have validated that the proposed patch in https://github.com/ansible/ansible/issues/7321#issuecomment-42582580 does fix this issue.

**Comment by jimi-c** [comment]
Merged the above in to resolve, thanks!

**Comment by drfickle** [comment]
In case anyone else runs into this, this also affected variables set with the vars: statement. I have confirmed that the patch referenced here, applied against 1.6.1, also fixes my issue.
