### ISSUE TITLE
include_role task vars always public if brought in from static role

### ISSUE THREAD

**Issue by smemsh** [ansible/ansible#73378]
##### SUMMARY
if a static role (included by play `roles` keyword) has its own `include_role` task, it appears to behave as `import_role` insofar as task vars are public (set in subsequent tasks), disregarding the `public: false` task arg

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION

```paste below
ansible 2.9.17
  config file = None
  configured module search path = [u'/home/scott/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.18 (default, Apr 20 2020, 20:30:41) [GCC 9.3.0]
```

##### CONFIGURATION

tested with stock default config

##### OS / ENVIRONMENT
ubuntu20 recent

##### STEPS TO REPRODUCE
```
==> testplay.yml <==
#
---

- hosts: localhost
  roles:
    - test
  tasks:
    - debug:
        var: testvar

==> roles/test/tasks/main.yml <==
#
---

- include_role:
    name: test2
    public: false
  vars:
    testvar: bar

==> roles/test2/tasks/main.yml <==
#
---

- meta: noop
```

##### EXPECTED RESULTS

`testvar` should be undefined when attempting to debug print it in the following task, as it was declared as private to the include_role.

##### ACTUAL RESULTS

`testvar` is printed with contents `bar` as though it were public

```
 $ ansible-playbook -i localhost, -c local testplay.yml

PLAY [localhost] ***********************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************
ok: [localhost]

TASK [include_role : test2] ************************************************************************************************************

TASK [debug] ***************************************************************************************************************************
ok: [localhost] => {
    "testvar": "foo"
}
```

**Comment by smemsh** [comment]
from #ansible 2021-01-26 19:12 UTC:

> < smemsh> hello.  if a static role (included by play 'roles' keyword) has its own include_role task, is this run dynamically or not? ie, is it effectively an import_role because the parent role was included statically?
> <@sivel> smemsh: `roles:` and `import_role` are pre-processor macros that run at playbook parsing time, and the contents are merged into the Play.
> <@sivel> As such, it would merge the `include_task` into the play, but not process it
> <@sivel> so it will still be dynamic
> <@sivel> err, include_role
> <@sivel> so it would stay as include_role until the task executor reaches it
> <@sivel> then it would be processed and merged in
> < smemsh> that's what i would think.  but such a task does not respect 'public' and the variables act like it was import_role.  https://pastebin.com/zqFYdnHt demonstrates.  the 'testvar' is printed with its contents as though it were public

**Comment by sivel** [comment]
Directly copy/pasted your reproducer, and I cannot reproduce the behavior you describe:

```
$ ansible-playbook 73378.yml -vv
ansible-playbook 2.9.17
  config file = None
  configured module search path = ['/Users/matt/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/matt/projects/ansibledev/ansible/lib/ansible
  executable location = /Users/matt/projects/ansibledev/ansible/bin/ansible-playbook
  python version = 3.9.0 (default, Oct  6 2020, 11:36:19) [Clang 12.0.0 (clang-1200.0.32.2)]
No config file found; using defaults

[SNIP]

PLAYBOOK: 73378.yml **************************************************************************************************
1 plays in 73378.yml

PLAY [localhost] *****************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************
task path: /Users/matt/projects/ansibledev/playbooks/73378/73378.yml:1
ok: [localhost]
META: ran handlers

TASK [include_role : test2] ******************************************************************************************
task path: /Users/matt/projects/ansibledev/playbooks/73378/roles/test/tasks/main.yml:1
META: noop

TASK [debug] *********************************************************************************************************
task path: /Users/matt/projects/ansibledev/playbooks/73378/73378.yml:6
ok: [localhost] => {
    "testvar": "VARIABLE IS NOT DEFINED!: 'testvar' is undefined"
}
META: ran handlers
META: ran handlers

PLAY RECAP ***********************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

I can only reproduce it if I set `public: true` on the `include_role`.

**Comment by smemsh** [comment]
uhh, you are right, I tried it in a new directory, it's not doing it.  don't understand the difference.  there are other roles and plays in the dir where i can reproduce it, but there's no config file and `ansible-config dump --only-changed` is showing empty.

sorry to waste your time, will close this for now and try to figure out how it's different and update ticket once I figure out.  thanks.

**Comment by smemsh** [comment]
ok, so there was a defaults file that I missed:
```
# roles/test/defaults/main.yml 
---

testvar: foo
```
removing this changes the behavior, sorry about that, I think this is correct behavior, because the parent role is setting the default in the namespace of child roles that it's calling.

If there's a way to delete github tickets so this doesn't index, please do...
