### ISSUE TITLE
hash_behaviour = merge does not merge when using inventory variables in vars_files' path

### ISSUE THREAD

**Issue by mpontes** [ansible/ansible#7345]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.1
##### Environment:

N/A
##### Summary:

Using an inventory variable as part of the path in vars_files imports breaks the merge hash_behaviour in Ansible 1.6 and up. Hashes will replace each other instead of merging. This was working in Ansible 1.5.x.
##### Steps To Reproduce:

test.yml:

```

---
- name: test hash behaviour merge
  hosts: localhost

  vars_files:
    - "{{inv_var}}var_file_1"
    - "{{inv_var}}var_file_2"

  tasks:
    - local_action: debug msg="{{ item }}"
      with_dict: hash_var
```

var_file_1:

```
hash_var:
  var_one: one
```

var_file_2:

```
hash_var:
  var_two: two
```

ansible.cfg:

```
[defaults]
hash_behaviour = merge
```

inv:

```
[me]
localhost

[all:vars]
inv_var="./"
```
##### Expected Results:

This is what happens in Ansible 1.5.5, which is the expected result:

```
% ansible-playbook -v test.yml -i inv

PLAY [test hash behaviour merge] ********************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]
localhost: importing /Users/mpontes/hashtest/var_file_1
localhost: importing /Users/mpontes/hashtest/var_file_2

TASK: [debug msg="{{item}}"] ************************************************** 
ok: [localhost] => (item={'value': 'one', 'key': 'var_one'}) => {
    "item": {
        "key": "var_one", 
        "value": "one"
    }, 
    "msg": "{'key': 'var_one', 'value': 'one'}"
}
ok: [localhost] => (item={'value': 'two', 'key': 'var_two'}) => {
    "item": {
        "key": "var_two", 
        "value": "two"
    }, 
    "msg": "{'key': 'var_two', 'value': 'two'}"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

In Ansible 1.6.1:

```
% ansible-playbook -v test.yml -i inv

PLAY [test hash behaviour merge] ********************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]
localhost: importing /Users/mpontes/hashtest/var_file_1
localhost: importing /Users/mpontes/hashtest/var_file_2

TASK: [debug msg="{{item}}"] ************************************************** 
ok: [localhost] => (item={'value': 'two', 'key': 'var_two'}) => {
    "item": {
        "key": "var_two", 
        "value": "two"
    }, 
    "msg": "{'key': 'var_two', 'value': 'two'}"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

If you remove {{inv_var}} from test.yml, things work as expected in 1.6. Oddly enough, the "importing" lines only appear when using a variable, I'm not sure if this is on purpose.

I realize this is a bit of an edge case, but I'm relying on inventory variables in the path on vars_files imports to be able to have per-group, per-inventory variables. group_vars are useless to me because they are the same amongst all inventories (I'm using different inventories for production, QA and development, with the same groups), and inventory variables, besides being more limited, they are also the same amongst all groups. What I'm doing is setting an inventory variable with the name of the inventory itself (Ansible only exposes inventory_dir and inventory_file) and using it in vars_files, with paths such as "inv_vars/{{ inventory }}/something".

**Comment by jimi-c** [comment]
This offending commit appears to be 4eb626825be313f68d5cb94c5f5a9440534da829, still digging into exactly why.

**Comment by jimi-c** [comment]
I have merged in the above fix, which resolves the issue for me in testing. If you continue having problems related to this issue, please let us know. Thanks!
