### ISSUE TITLE
ignore_errors fails to work when synchronize attempts to transfer a missing file

### ISSUE THREAD

**Issue by dcajacob** [ansible/ansible#7354]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.1
##### Environment:

Ubuntu 14.04
##### Summary:

This seems to be a regression between 1.5.5 (at least) and 1.6 and above.  ignore_errors fails to ignore if source file is missing in synchronize command.
##### Steps To Reproduce:

Example:

```
- name: copy custom directory/file structure
  synchronize: src=config/{{ inventory_hostname }}/folder dest=~/
  ignore_errors: yes
```

In 1.5.5, this task fails if the source folder does not exist, but the error is ignored and the play moves on.  However, in 1.6 and above, the task fails and stops the play altogether.
##### Expected Results:

If the source file is missing, the task will fail, but ignore_errors: yes should ensure that the play continues.

```
TASK: blah ************** 
failed: error message
...ignoring
```
##### Actual Results:

The task fails and the play errors out altogether.

```
TASK: blah *************** 
fatal: [hostname] => input file not found at ... config/hostname/folder

FATAL: all hosts have already failed -- aborting
```

**Comment by jimi-c** [comment]
I am not able to reproduce this with a slightly modified playbook:

<pre>
- hosts: localhost
  connection: local
  tasks:
  - name: copy custom directory/file structure
    local_action: synchronize src=config/{{ inventory_hostname }}/folder dest=~/test7354
    ignore_errors: yes
  - name: show message
    debug: msg="here we are"
</pre>

I see the debug message printed after the synchronize error is ignored.
Even without using local action, I see something similar using the following:

<pre>
- hosts: centos65
  tasks:
  - name: copy custom directory/file structure
    local_action: synchronize src=config/{{ inventory_hostname }}/folder dest=~/test7354
    ignore_errors: yes
  - name: show message
    debug: msg="here we are"
</pre>

Since my localhost is not setup for ssh, I get an error about not being able to connect to the host, but the error is ignored still.

Are you using any other options, such as serial that might cause the task to fail?

**Comment by dcajacob** [comment]
I am not using any other options.  I am not using local_action either.

**Comment by sstreiner** [comment]
I'm having the same issue with ignore_errors. any news regarding this matter?

**Comment by kcghost** [comment]
I tried to reproduce this issue with the latest Ansible from sources (bbaf80322711a23dfd1ea0b85fa84e61aa9db200) on Ubuntu 14.04 (both target and source).
I made the directory config, but not config/default/folder.
I used the following playbook:

```
---
- hosts: all
  tasks:
  - name: copy custom directory/file structure
    synchronize: src=config/{{ inventory_hostname }}/folder dest=~/
    ignore_errors: yes
  - name: Ping
    ping: 
```

But I got the correct behaviour:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [default]

TASK: [copy custom directory/file structure] ********************************** 
failed: [default] => {"cmd": "rsync --delay-updates -FF --compress --archive --rsh 'ssh -i /home/user/.vagrant.d/insecure_private_key -o StrictHostKeyChecking=no -o Port=2200' --out-format='<<CHANGED>>%i %n%L' \"config/default/folder\" \"vagrant@127.0.0.1:~/\"", "failed": true, "rc": 23}
msg: rsync: change_dir "/home/user//ubuntu_14_04//config/default" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]

...ignoring

TASK: [Ping] ****************************************************************** 
ok: [default]

PLAY RECAP ******************************************************************** 
default                    : ok=3    changed=0    unreachable=0    failed=0 
```

**Comment by mpdehaan** [comment]
We've got two people who could not repro this, so I am thinking we are ok in recent versions, if you are still seeing problems we will need some more info.  Can you stop by ansible-project?  Thanks!
