### ISSUE TITLE
Ansible "docker" module crashes if a container has no name

### ISSUE THREAD

**Issue by xb** [ansible/ansible#7363]
This line https://github.com/ansible/ansible/commit/4defd9a15a30be68330bfadf28b78c005506e149#diff-c2983e7efb083bc8a8ce86d6b1bcd059R510

```
name_matches = (name and name in i['Names'])
```

causes a crash

```
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1399851023.18-262414625752435/docker", line 1922, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1399851023.18-262414625752435/docker", line 678, in main
    running_containers = manager.get_running_containers()
  File "/root/.ansible/tmp/ansible-tmp-1399851023.18-262414625752435/docker", line 526, in get_running_containers
    for i in self.get_deployed_containers():
  File "/root/.ansible/tmp/ansible-tmp-1399851023.18-262414625752435/docker", line 510, in get_deployed_containers
    name_matches = (name and name in i['Names'])
TypeError: argument of type 'NoneType' is not iterable
```

in case there is a container with no name

```
# docker ps --all
CONTAINER ID        IMAGE                          COMMAND             CREATED             STATUS              PORTS               NAMES
3613dc57ed0b        foo/bar                        true                14 minutes ago                                                                  
#
```

**Comment by jimi-c** [comment]
I believe this patch should resolve your issue, if you'd like to test it out:

<pre>
diff --git a/library/cloud/docker b/library/cloud/docker
index f9aabf2..7cab18f 100644
--- a/library/cloud/docker
+++ b/library/cloud/docker
@@ -507,7 +507,9 @@ class DockerManager:
             running_image, running_tag = self.get_split_image_tag(i['Image'])
             running_command = i['Command'].strip()
 
-            name_matches = (name and name in i['Names'])
+            name_matches = False
+            if i["Names"]:
+                name_matches = (name and name in i['Names'])
             image_matches = (running_image == image)
             tag_matches = (not tag or running_tag == tag)
             # if a container has an entrypoint, `command` will actually equal
</pre>

**Comment by jimi-c** [comment]
I've gone ahead and merged in the above commit. If you continue experiencing any further problems related to this issue, please let us know. Thanks!
