### ISSUE TITLE
Please switch from fcntl to portalocker

### ISSUE THREAD

**Issue by guilt** [ansible/ansible#73641]
fnctl is a Unix-ish implementation and not portable. Would love to see you guys use a more portable (layered) approach to ansible, so we could try implementing these playbooks on Windows and other platforms as well.

https://github.com/WoLpH/portalocker

##### SUMMARY

Please migrate from fcntl calls to portalocker calls

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- core module

##### ADDITIONAL INFORMATION

```python
import portalocker

with portalocker.Lock('some_file.lock', 'rb+', timeout=60) as fh:
   do_stuff()
```

**Comment by sivel** [comment]
What issues are you running into that such a change would actually improve?  We do not actually utilize any file locking within this repository.  We do have a helper class, but it is not in active use.

**Comment by guilt** [comment]
https://github.com/ansible/ansible/search?q=fcntl

We use this in a lot of places, and fcntl is not importable on anything other than Unix in Python. (CLI, vault, FileLock class etc) So, that's the reason I brought it up.

**Comment by sivel** [comment]
We take adding extra dependencies very cautiously.  In addition we do not support running ansible from windows hosts, nor do we have plans to do so.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
