### ISSUE TITLE
synchronize module: basedir references inventory instead of playbook

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#7366]
##### Issue Type:

Bug Report
##### Ansible Version:

Bug exists in -devel and in 1.6.0 and 1.6.1
Still works in 1.5.5

bisect: 2492c2714a8dfe5dc8de083580a5dcafd61ddb47 is the first bad commit
##### Environment:

Ubuntu 12.04
##### Summary:

The synchronize module uses the playbook basedir as base reference for local paths.
Now, it looks for inventory dir as it's basepath, which breaks playbooks with relative paths.

According to 2492c2714a8dfe5dc8de083580a5dcafd61ddb47 (@jimi-c 's commit Fixes #5307 set relative paths to the files dir for roles and the inventory dir for non-role tasks) this is intended behaviour, though I fail to see why the inventory should be the base dir, and not the playbook?
##### Steps To Reproduce:

This action lives in a playbook plays/cbb.yml and we have dirs plays/files/cbb/jms/...

```
action: synchronize src=files/cbb/jms/ dest=/opt/jboss/server/all/deploy-hasingleton/jms/
```

Note: This is part of a plain playbook _without_ roles.
##### Expected Results:

```
ok: [cbb] => {"changed": false, "cmd": "rsync --delay-updates -FF --compress --timeout=10 --archive --rsh 'ssh  -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' files/cbb/jms/ root@cbb:/opt/jboss/server/all/deploy-hasingleton/jms/", "msg": "", "rc": 0}
```
##### Actual Results:

```
failed: [cbb] => {"cmd": "rsync --delay-updates -FF --compress --archive --rsh 'ssh  -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' /home/serge/src/acd/ansible-data/inventory/files/cbb/jms/ root@cbb:/opt/jboss/server/all/deploy-hasingleton/jms/", "failed": true, "rc": 23}
rsync: change_dir "/home/serge/src/acd/ansible-data/inventory/files/cbb/jms" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1070) [sender=3.0.9]
```

**Comment by jimi-c** [comment]
I've merged in the above PR which should address this issue. Please let us know if you continue to have any problems regarding this issue. Thanks!

**Comment by DaveQB** [comment]
Just wanted to report I am having this issue.
I am running 1.6.10 from ubuntu PPA. 

If I set a full path as the src I am ok, otherwise it tries to prepend /root/ to my src path.
This makes my configs not as portable from system to system, not that moving the ansible files is commonly done (my ansible Pi server went down and I am using my desktop in the interim.)
