### ISSUE TITLE
AnsibleModule class should raise errors on unknown arguments

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#737]
(A) If any argument isn't in the argument_spec or any of the aliases, it's invalid, so call fail_json to catch typos

(B) If any argument IS in the module spec, and is not specified, set it to None in module.params rather than just omitting it.   Will make module code simpler.

**Comment by mpdehaan** [comment]
I've pushed changes for this, so closing.

I have another ticket open about teaching module code to denote when things are mutally exclusive or required together, which can wait for 0.7

**Comment by Ernest0x** [comment]
These changes introduce a bug. I have opened issue #746 for that purpose.

**Comment by mpdehaan** [comment]
which I've closed just now, thanks!
