### ISSUE TITLE
Since 1.6.0 `template` always does `chown`, causing 'Operation not permitted'

### ISSUE THREAD

**Issue by TallGirlVanessa** [ansible/ansible#7372]
After upgrading to 1.6.0, I can no longer use the `template` module to write to folders I can't `chown`. I isolated this with `git bisect` to commit 8f778a83dfaaea142663b878bafd84be3afee3f6: looks like the `template` module now does a `chown` whether or not the play specifies the destination's owner/group.

This is a problem since our deploy script is sudoed to a non-root user: I first noticed this issue when I tried to deploy to one of our integration environments. Surprisingly, it broke on my local machine as well: we develop using Parallels VMs managed by Vagrant, which keep our code in a Parallels shared folder which is very lenient with permissions (the files appear to be owned by whoever is trying to access them at the time :smiley:). Turns out this arrangement (a mount of type `prl_fs`) does not permit `chown`, even by root. Could you please prevent `template` from using `chown` when owner/group is not specified?

Example plays:

```
- name: Deploy | Create Flask instance folder
  file: path={{ code_home }}/instance state=directory

- name: Deploy | Write Ansible-customized config
  template: src=config_from_ansible.py.jinja2 dest={{ code_home}}/instance/config_from_ansible.py
```

Result:

```
__________________________________________________________
< TASK: deploy_web | Deploy | Create Flask instance folder >
 ----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


ok: [33.33.33.50] => {"changed": false, "gid": 1000, "group": "vagrant", "item": "", "mode": "0755", "owner": "vagrant", "path": "/var/www/bridge-it/instance", "size": 102, "state": "directory", "uid": 1000}
 _____________________________________________________________
< TASK: deploy_web | Deploy | Write Ansible-customized config >
 -------------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


failed: [33.33.33.50] => {"failed": true, "item": ""}
msg: Could not replace file: /home/vagrant/.ansible/tmp/ansible-tmp-1399918533.3-108641875157900/source to /var/www/bridge-it/instance/config_from_ansible.py: [Errno 1] Operation not permitted: '/var/www/bridge-it/instance/.config_from_ansible.py.11003.1399918533.48'

FATAL: all hosts have already failed -- aborting
```

Gist of `-vvvv` located here: https://gist.github.com/garaden/d967534d99a7c6304ded.

**Comment by mpdehaan** [comment]
While I agree this is important, I'd much rather see a check that doesn't call chown when we know it will fail, or that handles the error condition instead, as there is some ownership preservation that seems to need to be intact.

Alternative approaches also would be fine -- anyway, agree this is important -- just saying we shouldn't just remove the chown.

**Comment by TallGirlVanessa** [comment]
Cool, thanks for prioritizing this! Ansible 1.4.5 is working for me at the moment (that's the other version in Homebrew) but it'd be nice to get back on the upgrade train.

The less heavy-handed approaches you suggested sound fine to me; as long as my use case is covered I'll be happy!

**Comment by jimi-c** [comment]
Is the destination on the shared file system? If so, that would be the problem. The chown is required to ensure that the file's owner/group match what the previous file's were specifically for the case where the user/group are not specified.

**Comment by TallGirlVanessa** [comment]
I'm confused. What are you suggesting/arguing for/against?

**Comment by jimi-c** [comment]
@garaden I am asking if the dest= portion (which includes the `{{code_home}}` variable) is on the shared file system. Since it includes that variable, it appears that it does? That would be the problem, as it's replacing a file that exists it's trying to make sure that the original owner/group are preserved. In your case, since the remote is mounted in such a way that all files are owned by the same user/group, then we could add a check to only call chown() if the destination stat info doesn't match the source, but in 99.99% of most use-cases it will.

I'll work on a patch for that.

**Comment by jimi-c** [comment]
Here is a preliminary patch, if you'd like to test it:

<pre>
diff --git a/lib/ansible/module_utils/basic.py b/lib/ansible/module_utils/basic.py
index c0b00d3..f33c97f 100644
--- a/lib/ansible/module_utils/basic.py
+++ b/lib/ansible/module_utils/basic.py
@@ -985,6 +985,7 @@ class AnsibleModule(object):
             if self.selinux_enabled():
                 context = self.selinux_default_context(dest)
 
+        src_stat = os.stat(src)
         creating = not os.path.exists(dest)
 
         try:
@@ -1010,7 +1011,7 @@ class AnsibleModule(object):
                 if self.selinux_enabled():
                     self.set_context_if_different(
                         tmp_dest.name, context, False)
-                if dest_stat:
+                if dest_stat and (src_stat.st_uid != dest_stat.st_uid or src_stat.st_gid != dest_stat.st_gid):
                     os.chown(tmp_dest.name, dest_stat.st_uid, dest_stat.st_gid)
                 os.rename(tmp_dest.name, dest)
             except (shutil.Error, OSError, IOError), e:
</pre>

**Comment by TallGirlVanessa** [comment]
@jimi-c Gotcha. I just double-checked, and it turns out I'm _not_ seeing the issue in our integration environment, only on my local VM (and only when the dest is a shared folder). Must have imagined that one/assumed only the super-user can chown, even if the owner specified in the chown is the current owner.

I guess Parallels is just particularly draconian about this and refuses to allow chowns to succeed, no matter how innocuous. Wonder if I should follow up with them, since this is kinda silly. Or is that a Unix convention for NFS shares and such?

Thanks for your patch, I'll test it now.

**Comment by TallGirlVanessa** [comment]
It didn't work (same error as before) but I think we're on the right track. Unfortunately the src file did have different ownership than the dest file, so the chown still happened. I'd send a patch but when I tried stat-ing the temp file instead I didn't succeed, which is probably for the best given the nature of the temp files. I think I'm just missing the correct `os` method, but I've got to head out for the day so that's a problem for tomorrow.

**Comment by jimi-c** [comment]
Hrm, that definitely complicates things. I know in some situations things like smbfs used to fail a chown, since NTFS didn't support that, but beyond that I'm not sure what we can do in this situation. Does prl_fs not have any mount options regarding this?

**Comment by TallGirlVanessa** [comment]
I don't think it does, but here's a patch that works:

``` diff
diff --git a/lib/ansible/module_utils/basic.py b/lib/ansible/module_utils/basic.py
index c0b00d3..8b3b94b 100644
--- a/lib/ansible/module_utils/basic.py
+++ b/lib/ansible/module_utils/basic.py
@@ -1010,7 +1010,8 @@ class AnsibleModule(object):
                 if self.selinux_enabled():
                     self.set_context_if_different(
                         tmp_dest.name, context, False)
-                if dest_stat:
+                tmp_dest_stat = os.fstat(tmp_dest.fileno())
+                if dest_stat and (tmp_dest_stat.st_uid != dest_stat.st_uid or tmp_dest_stat.st_gid != dest_stat.st_gid):
                     os.chown(tmp_dest.name, dest_stat.st_uid, dest_stat.st_gid)
                 os.rename(tmp_dest.name, dest)
             except (shutil.Error, OSError, IOError), e:
```

I was just stat-ing the tempfile incorrectly before (with `os.stat` instead of `os.fstat`).

**Comment by TallGirlVanessa** [comment]
Nvm, I was just being dumb last night and trying to stat it with the full path. This is better, I think:

``` diff
diff --git a/lib/ansible/module_utils/basic.py b/lib/ansible/module_utils/basic.py
index c0b00d3..c98774a 100644
--- a/lib/ansible/module_utils/basic.py
+++ b/lib/ansible/module_utils/basic.py
@@ -1010,7 +1010,8 @@ class AnsibleModule(object):
                 if self.selinux_enabled():
                     self.set_context_if_different(
                         tmp_dest.name, context, False)
-                if dest_stat:
+                tmp_dest_stat = os.stat(tmp_dest.name)
+                if dest_stat and (tmp_dest_stat.st_uid != dest_stat.st_uid or tmp_dest_stat.st_gid != dest_stat.st_gid):
                     os.chown(tmp_dest.name, dest_stat.st_uid, dest_stat.st_gid)
                 os.rename(tmp_dest.name, dest)
             except (shutil.Error, OSError, IOError), e:
```

**Comment by jimi-c** [comment]
I went ahead and tweaked my patch as you showed above and merged it in. If you continue seeing any problems related to this issue please let us know. Thanks!

**Comment by chadfurman** [comment]
I'm still getting this.  I'm running 'template' on an NFS box with user/group set to vagrant.  No idea how to fix, please advice.

Ansible 1.7.2  vagrant 1.7.4

**Comment by TallGirlVanessa** [comment]
Hrm. I'm not quite sure what situation you're describing. This was a long time ago for me, but I think this was my situation:
- Guest OS: precise64 (Ubuntu 12.04)
- Provider: Parallels
- Ansible sudo user: vagrant
- `template` destination: a Parallels shared folder, not using NFS
- `template` user/group arguments: not used

The issue was that Ansible was chowning the temporary file generated from the template, even though it already had the user/group it needed to, on a file system (`prl_fs`) that does not permit chown under any circumstances.

If I understand correctly, you're using an NFS shared folder instead? I've never used those, so I'm not sure how they're different, though I assume they don't do the `prl_fs` witchery where the files appear to be owned by whomever's looking at them. I also don't know whether chown is allowed.

Could you send me the bullets above for you?

**Comment by tigrus** [comment]
Finally.. Are there any way to avoid `chown` command in template?
