### ISSUE TITLE
Redirect in documentation is broken for aws_s3_module from latest when going to 2.9 in the dropdown

### ISSUE THREAD

**Issue by ammygill** [ansible/ansible#73841]
### Summary

When finding documentation on the aws_s3_module:

https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_s3_module.html

Clicking the dropdown and changing the value to 2.9 redirects the documentation here:
https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_s2.9_module.html
which results in the 404 error.

The correct documentation is located here:
https://docs.ansible.com/ansible/2.9/collections/amazon/aws/aws_s3_module.html

It appears as though the redirect notices the 3 in the aws_s3_module part of the URL and tries to swap in 2.9 instead.

### Issue Type

Documentation Report

### Component Name

docs

### Ansible Version

```console (paste below)
$ ansible --version
The issue is in the online documentation.
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
The issue is in the online documentation hyperlink
```

### OS / Environment

all

**Comment by Akasurde** [comment]
!component =docs/docsite/_themes/sphinx_rtd_theme/ansible_versions.html

**Comment by Akasurde** [comment]
This line https://github.com/ansible/ansible/blob/1d5110db6fc91aae310c2a916cccf787e18b3011/docs/docsite/_themes/sphinx_rtd_theme/ansible_versions.html#L16 is replacing version s3 with 2.9 incorrectly.
