### ISSUE TITLE
Included playbooks not able to access variables from vars_files

### ISSUE THREAD

**Issue by j-manu** [ansible/ansible#7384]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.1 (existed in 1.5 also)
##### Environment:

NA
##### Summary:

Variables defined in vars is available to included playbooks but variables included via vars_files is not.
##### Steps To Reproduce:

Playbooks and associates files are available in - https://github.com/j-manu/debug/tree/master/ansible

Run `ansible-playbook -i inventory site.yml`
##### Expected Results:

```
PLAY [all] ********************************************************************

TASK: [Access var from vars list] *********************************************
ok: [localhost] => {
    "msg": "App version is 1.1"
}

TASK: [Access var from included vars file] ************************************
ok: [localhost] => {
    "msg": "App name is Debug App"
}

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```
##### Actual Results:

```
PLAY [all] ********************************************************************

TASK: [Access var from vars list] *********************************************
ok: [localhost] => {
    "msg": "App version is 1.1"
}

TASK: [Access var from included vars file] ************************************
fatal: [localhost] => One or more undefined variables: 'app_name' is undefined

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/manu/site.retry

localhost                  : ok=1    changed=0    unreachable=1    failed=0
```

**Comment by HeisenbergTT** [comment]
I have updated ansible, rebuilt and installed and I still get this error, I am basically using the-ansibles package with minimal modifications

When it tries to check to see if the required users are present I get this error:

failed: [vm1.dev] => (item=$users) => {"failed": true, "item": "$users"}
msg: Boolean {{item.append}} not in either boolean list

FATAL: all hosts have already failed -- aborting

Jeff

**Comment by jimi-c** [comment]
The above patch hasn't been merged in to the devel branch yet, so you would have to pull in my patch manually right now. Once I do some further testing, I will merge it in.

**Comment by jimi-c** [comment]
@HeisenbergTT I've gone ahead and merged the above in, so if you re-pull now you should see the fix in place. If you continue seeing any problems related to this issue, let us know. Thanks!
