### ISSUE TITLE
Async task should not wait for time-out if "creates=" condition is met

### ISSUE THREAD

**Issue by edrozenberg** [ansible/ansible#7390]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

Ansible master: Mac OSX 10.9.3
Ansible clients/hosts: Slackware64 Linux 14.1
##### Summary:

If a task is async and has a "creates=" condition, it waits for one period of poll time even if the condition is true.

Desired behavior: if the "creates=" condition is met, do not wait at all, skip the task immediately.
##### Steps To Reproduce:

Example - the task below will wait 10 seconds even if the "creates=" condition is met:

```
- name: kernel and modules compile
  command: >
    make -j25 bzImage modules 
    chdir={{ kernel_build_dir }}
    creates={{ kernel_build_dir }}/vmlinux
  async: 1800
  poll: 10
```
##### Expected Results:

Should skip task immediately rather than waiting for one period of timeout
##### Actual Results:

Waited for 10 seconds before skipping task

```
TASK: [build | kernel and modules compile] ************************************ 
skipping: [work1]
<job 919947773496.26974> finished on work1
```

**Comment by mpdehaan** [comment]
The async implementation is independent of what parameters the modules takes, it works for all modules, etc.

As such, there's really not a way to do what you want with "creates=" here, and this is not what creates= does as is mentioned in the docs anyway

Creates will choose to not do the build when the file already exists, it does not abort a program early when the file did not prexist at the point when the file does exist.

If you have more questions on this, please stop by ansible-project.

Thanks!
