### ISSUE TITLE
make deb fails 'cp -r packaging/debian ./'

### ISSUE THREAD

**Issue by bernpuc** [ansible/ansible#7397]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.1
##### Environment:

Ubuntu 14.04
##### Summary:

Compiling from source fails when making a debian package
##### Steps To Reproduce:

Download ansible-1.6.1.tar.gz and unpack.
cd ansible_1.6.1
make deb
##### Expected Results:

Output indicating where the deb package file is located in filesystem.
##### Actual Results:

...[Lots of output removed]...
creating dist
Creating tar archive
removing 'ansible-1.6.1' (and everything under it)
cp -r packaging/debian ./
cp: cannot stat ‘packaging/debian’: No such file or directory
make: **\* [deb] Error 1

**Comment by bernpuc** [comment]
Works as expected on Ubuntu 10.04.

**Comment by bernpuc** [comment]
It works in one ubuntu 10.04 server, but not a second one.  Likely there is a missing package.  But, I build other debian packages on both these servers.

**Comment by bernpuc** [comment]
Nevermind about the OS version.  The ansible-devel release works because the packaging/debian directory exists.  The 1.6.1 and 1.5.4 tarball releases are missing that directory.

**Comment by jimi-c** [comment]
Typically the tarballs are used only for running setup.py. The full packaging builds are done via git checkouts only. If you have any further questions regarding this, please let us know. Thanks!

**Comment by bernpuc** [comment]
Thanks. all set.
