### ISSUE TITLE
STDERR is not being displayed when a module cannot run

### ISSUE THREAD

**Issue by tima** [ansible/ansible#740]
I found this error after trying to run a script using python 2.4 without simplejson installed.

The bug here is that error was not reported where I could see it would inserting debugging code in the core. It looks like _low_level_exec_command is not detecting and passing the stderr along. Only stdout gets passed which in my case was blank and really uninformative.

I tried to use blame to figure out where it may have gone wrong and this was the only clue:

```
# sudo mode paramiko doesn't capture stderr, so not relaying here either...
```

For things like local, and I assume ssh, this is not the case and stderr is return, but that wasn't worked in. I'm not sure what the right thing to do here without discussion though. Looking the use of _low_level_exec_command in runner/__init__.py it expects a single string return, not a dict or two strings or an exception.

**Comment by mpdehaan** [comment]
fixed per above
