### ISSUE TITLE
failed_when dependent on register fails with module that doesn't support check mode

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#7405]
##### Issue Type:

“Bug Report”
##### Ansible Version:

1.6
##### Environment:

Centos 6
##### Summary:

This is a follow up to  #6845. As far as I can see from the commit, it doesn't fix the problem with `failed_when`, only with `changed_when`.

**Comment by jimi-c** [comment]
I went ahead and replicated the fix from #6845 for the failed_when statement as well. Since no reproduction steps were provided, please let us know if this does not fully address the issue, along with the steps you're using to reproduce it. Thanks!
