### ISSUE TITLE
SSH Connection without Target /tmp directory (Linux System without Bash)

### ISSUE THREAD

**Issue by lmayorga1980** [ansible/ansible#74080]
### Summary

I am trying to connect to a system based on Ubuntu Linux that has proprietary prompt(no access to bash or linux commands but some proprietary commands) and I can ssh normally using `ssh` client but I get this error when connecting `ansible-playbook`.

### Issue Type

Feature Idea

### Component Name

ssh

### Additional Information

```
Failed to create temporary directory.In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in "/tmp", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p "` echo Unknown command 'bin'./.ansible/tmp `"&& mkdir "` echo Unknown command 'bin'./.ansible/tmp/ansible-tmp-1617152132.351016-21261-93895301584373 `" && echo ansible-tmp-1617152132.351016-21261-93895301584373="` echo Unknown command 'bin'./.ansible/tmp/ansible-tmp-1617152132.351016-21261-93895301584373 `" ), exited with result 1, stdout output: Unknown command 'bin'.
, stderr output: OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/user1/.ssh/config
debug1: /Users/user1/.ssh/config line 5: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 47: Applying options for *
debug2: resolve_canonicalize: hostname 10.10.104.12 is address
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 21266
debug3: mux_client_request_session: session request sent
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 1
```

**Comment by lmayorga1980** [comment]
Is it possible to avoid the temporal directory completely?

**Comment by s-hertel** [comment]
List Information
================

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

You can use the `raw` command to run commands on the remote or you need a set of specific setup modules.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
