### ISSUE TITLE
Alternatives module: "'NoneType' object has no attribute 'startswith'"

### ISSUE THREAD

**Issue by emilbayes** [ansible/ansible#7414]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.6.1
```
##### Environment:

Local system: OS X 10.9.2
Remote system: Scientific Linux 6 with Python 2.6.6 
##### Summary:

Using the `alternatives` module to modify the Java version used.
##### Steps To Reproduce:

I have the following playbook:

``` yml
- name: Ensure correct Java version (1.7.0_51)
  sudo: yes
  alternatives: name=java path=/usr/java/jdk1.7.0_51/jre/bin/java
```
## 
##### Actual Results:

I get the following error:

```
fatal: [n-62-13-9] => failed to parse: 
SUDO-SUCCESS-zjbqvuyvsqakqwxtemyoeuacxcaiclja
Traceback (most recent call last):
  File "/tmp/.ansible/ansible-tmp-1400141346.08-105156899172498/alternatives", line 1307, in <module>
    main()
  File "/tmp/.ansible/ansible-tmp-1400141346.08-105156899172498/alternatives", line 119, in main
    check_rc=True
  File "/tmp/.ansible/ansible-tmp-1400141346.08-105156899172498/alternatives", line 1199, in run_command
    args = [ os.path.expandvars(os.path.expanduser(x)) for x in args ]
  File "/usr/lib64/python2.6/posixpath.py", line 251, in expanduser
    if not path.startswith('~'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by jimi-c** [comment]
This is happening because the link value is not being specified, however it appears to be required for the "update-alternatives --install" call on the system.

**Comment by jimi-c** [comment]
The above patch should address this issue. If you continue having problems, please let us know. Thanks!
