### ISSUE TITLE
[Bug Report + fix] uri module traceback when status == 304

### ISSUE THREAD

**Issue by ashemedai** [ansible/ansible#7416]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.1
##### Environment:

N/A
##### Summary:

uri module changes in 1.6.0 introduced faulty Python logic.
##### Steps To Reproduce:

Try to use uri where the host yields a 304 status code.
##### Expected Results:

A successful deployment.
##### Actual Results:

The uri module in 1.6.0/1.6.1 contains this code:

``` python
    # Write the file out if requested
    if dest is not None:
        if resp['status'] == 304:
            status_code = 304
            changed = False
```

and later on:

``` python
    if resp['status'] not in status_code:
        module.fail_json(msg="Status code was not " + str(status_code), content=content, **uresp)
```

Of course, due to setting status_code to 304 before, you will trigger a TypeError traceback in the form of (the initial 2 lines are from my debugging print statements):

``` python
status_code: 304
resp[status]: 304
Traceback (most recent call last):
  File "/home/jeroenr/.ansible/tmp/ansible-tmp-1400142562.3-221554703955560/uri", line 1618, in <module>
    main()
  File "/home/jeroenr/.ansible/tmp/ansible-tmp-1400142562.3-221554703955560/uri", line 438, in main
    if resp['status'] not in status_code:
TypeError: argument of type 'int' is not iterable
```

This was introduced in 5d51837 and it means that uri is broken in 1.6.0 and 1.6.1 when 304 statuses are returned.

That particular commit makes me scratch my head a bit, since I wonder if it is clean design to overload the variable, which initially was simply an integer, to be both a single integer as well as a list. This seems a recipe for mistakes waiting to happen. Especially since the argument_spec for status_code says default is [200], a list. So maybe singular integer are just plain not acceptable anymore, but then the documentation needs to be updated/adjusted accordingly as well.

Anyway, a possible fix can be to have something like this:

``` python
    # Write the file out if requested
    if dest is not None:
        if resp['status'] == 304:
            status_code = 304
            changed = False
```

to:

``` python
    # Write the file out if requested
    if dest is not None:
        if resp['status'] == 304:
            status_code = [304]
            changed = False
```

**Comment by mpdehaan** [comment]
Thanks for the report.

In the future, rather than saying "contains faulty logic" can you relate what the bug is in the description (such as uri module 304 causes traceback)?  Thanks!

**Comment by jimi-c** [comment]
The above commit should resolve this issue for you. If you continue having any problems related to this issue, please let us know. Thanks!

**Comment by ashemedai** [comment]
Thanks James, will do.
