### ISSUE TITLE
Wrong sudo_flags used (or error in docs)

### ISSUE THREAD

**Issue by hkariti** [ansible/ansible#7418]
##### Issue Type:

Documentation Report
##### Ansible Version:

ansible 1.7 (ec2_hostname_variable 172fdf9e6a) last updated 2014/05/14 12:57:21 (GMT +300)
##### Environment:

Ubuntu 13.10
##### Summary:

The [docs](http://docs.ansible.com/intro_configuration.html#sudo-flags) say that `sudo_flags` defaults to preserving the environment, but the flag actually passed is `-H`, which doesn't do that at all. The correct flag is `-E`.

Is this an error in the docs or a bug?
##### Steps To Reproduce:

`cat docsite/rst/intro_configuration.rst  | grep environment | grep preserve`

`man sudo | grep environment | grep preserve`
##### Expected Results:

The two docs agree with each other.
##### Actual Results:

They do not.

**Comment by mpdehaan** [comment]
It preserves the home dir, not the environment, so the docs need to be updated.

**Comment by hkariti** [comment]
It actually _sets_ the HOME variable to the destination user's homedir:

```
$ sudo bash -c 'echo $HOME'                                                
/home/hkariti
$ sudo -H bash -c 'echo $HOME'                                             
/root
```

**Comment by bcoca** [comment]
from man page on ubuntu:
     -H          The -H (HOME) option requests that the security policy set
the HOME environment variable to the home directory of the target user
(root by default) as specified by the password database.  Depending on the
policy, this may be the default behavior.

​so it forces resetting HOME to the user you sudo into, not preserve it
(unless I'm reading it wrong). Most machines have this as a default policy
but it is not guaranteed.

**Comment by muffl0n** [comment]
:+1: for updating the docs. Took me some time to figure out that the docs are wrong.
