### ISSUE TITLE
Colon in shell/command module options causes ansible to hang

### ISSUE THREAD

**Issue by davestern** [ansible/ansible#7423]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.6.1
##### Environment:

Mac OS X 10.9.2
##### Summary:

I've searched and RTFM'ed quite a bit for the issues with colons and YAML and haven't found a solution to my issue yet. 
ansible task hangs when there is a colon in the shell or command module options.
##### Steps To Reproduce:

The base task I've tried is this (the debug tag is used to isolate this task for testing)

```
- name: Enable Heroku Toolbelt `pipeline` command
  shell: heroku labs:enable pipelines
  tags:
    - debug
```

ansible hangs without doing anything else or returning on running this task. Here's the output:

```
$ ansible-playbook -i hosts playbook.yml -t debug

PLAY [<removed>] ******************************************************************

GATHERING FACTS ***************************************************************
ok: [<hostname removed>]

TASK: [<removed> | Enable Heroku Toolbelt `pipeline` command] *********************
```

Without the colon in `labs:enable`, the heroku command is executed as expected, but it is the incorrect command - the colon is necessary. **Of important note** is the fact that if I add another argument after "pipelines", the command is also executed, but incorrectly. 

So the following does not hang and works as expected, but it is incorrect syntax, so I can't use it as a workaround:

```
- name: Enable Heroku Toolbelt `pipeline` command
  shell: heroku labs:enable pipelines other
  tags:
    - debug
```
##### Expected Results:

```
Enabling pipelines for account@domain.com... done
```
##### Actual Results:

```
$ ansible-playbook -i hosts playbook.yml -t debug

PLAY [<removed>] ******************************************************************

GATHERING FACTS ***************************************************************
ok: [<hostname removed>]

TASK: [<removed> | Enable Heroku Toolbelt `pipeline` command] *********************
```

I have tried all of the following as a replacement for the `shell...` line, all of which hang and do not return like the first version of the task:

```
command: heroku labs:enable pipelines

shell: "heroku labs:enable pipelines"

shell: heroku "labs:enable" pipelines

shell: heroku 'labs:enable' pipelines

shell: >
    heroku labs:enable pipelines

shell: heroku labs{{":"}}enable pipelines

action: shell heroku labs:enable pipelines

action: shell heroku "labs:enable" pipelines

```

This version runs, but produces an error:

```
action: shell "heroku labs:enable pipelines"
...
stderr: /bin/sh: 1: heroku labs:enable pipelines: not found
```

At this point, I don't really have any ideas on how to run this other than create a shell wrapper with the command in it.

**Comment by jimi-c** [comment]
The proper quoting should be `shell: "heroku labs:enable pipelines"`. What does that command show when run via the command line? Is it waiting for input of some kind?

**Comment by davestern** [comment]
I tried that as noted above in the `Actual Results` section. It still hangs. 
`shell: "heroku labs:enable pipelines other"`
 (or any string after "pipelines") executes (with a heroku error)

**Comment by jimi-c** [comment]
I just tried with this playbook on an Ubuntu 14.04 system:

<pre>
- hosts: ubuntu1404
  tasks:
  - shell: "heroku labs:enable pipelines"
</pre>

with the following result:

<pre>
TASK: [shell heroku labs:enable pipelines] ************************************ 
<192.168.122.113> REMOTE_MODULE command heroku labs:enable pipelines #USE_SHELL
changed: [192.168.122.113] => {"changed": true, "cmd": "heroku labs:enable pipelines ", "delta": "0:00:00.953194", "end": "2014-05-15 14:42:34.446127", "rc": 0, "start": "2014-05-15 14:42:33.492933", "stderr": "", "stdout": "Enabling pipelines for jimi@xxxxxxxxxx... done\nWARNING: This feature is experimental and may change or be removed without notice.\nFor more information see: https://devcenter.heroku.com/articles/using-pipelines-to-deploy-between-applications"}
</pre>

What version of the heroku toolbelt/gem do you have installed? Perhaps that's prompting for user authentication or some other info?

**Comment by davestern** [comment]
Interesting, the version on the remote server did need an upgrade and now I can see the process running on the remote side. So it appears this issue is not related to the colon in the command. I'll have to see if it's a ruby or other issue. Thanks.

**Comment by jimi-c** [comment]
No problem, if you have any further questions let us know. Thanks!
