### ISSUE TITLE
ansible collection shows multiple duplicate version

### ISSUE THREAD

**Issue by savitojs** [ansible/ansible#74239]
### Summary

ansible collection shows multiple duplicate version with redhat.openshift collections installed.

```
$ ansible-galaxy collection list | grep kubernetes

community.kubernetes          1.2.0  
kubernetes.core               1.2.0  
community.kubernetes          1.2.0  
kubernetes.core               1.2.0  
kubernetes.core  1.2.1
```

### Issue Type

Feature Idea

### Component Name

ansible-collections

### Ansible Version

```console
$ ansible --version

ansible 2.10.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/savsingh/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/savsingh/virtualenvs/openshfit-test2/lib64/python3.6/site-packages/ansible
  executable location = /home/savsingh/virtualenvs/openshfit-test2/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

### Configuration

```console
$ ansible-config dump --only-changed

No output
```

### OS / Environment

RHEL 8.2

### Steps to Reproduce

```yaml (paste below)

$ pip install ansible
$ pip install openshift

$ ansible-galaxy collection list | grep kubernetes

community.kubernetes          1.2.0  
kubernetes.core               1.2.0  
community.kubernetes          1.2.0  
kubernetes.core               1.2.0

$ ansible-galaxy collection install redhat.openshift

$ ansible-galaxy collection list | grep kubernetes

community.kubernetes          1.2.0  
kubernetes.core               1.2.0  
community.kubernetes          1.2.0  
kubernetes.core               1.2.0  
kubernetes.core  1.2.1

```

### Expected Results

`ansible-galaxy collection install` should check the existing version and upgrade it. It seems like its dependency map has issues.

### Actual Results

```console
Shows multiple duplicate versions


$ ansible-galaxy collection list | grep kubernetes

community.kubernetes          1.2.0  
kubernetes.core               1.2.0  
community.kubernetes          1.2.0  
kubernetes.core               1.2.0  
kubernetes.core  1.2.1
```
```


### Code of Conduct

I agree to follow the Ansible Code of Conduct

**Comment by savitojs** [comment]
cc @Akasurde

**Comment by sivel** [comment]
The "ansible" package bundles a number of collections, and as they are managed by the "ansible" package, they are not modified using the `ansible-galaxy` CLI tool.

`ansible-galaxy collection list` will list them, but not modify them.

Additionally, listing collections, lists all installed collections on all search paths, not only the one that ansible will use.

This behavior is expected.

**Comment by sivel** [comment]
We would potentially accept a feature request to add a CLI flag that would restrict list to only the collections that would be used, and not all installed.  The default would need to remain the same as it is now.

**Comment by henriqueccapozzi** [comment]
@sivel i would like to try to implement the CLI flag you suggested.

How does this look for a solution:

`ansible-galaxy collection list --only-used`

Also,
How will ansible determine the collections it'll use? 
**Note**: I didn't researched this yet so if the answer is not straight or simple is okay not to answer.
Naturally i'll do the proper research before trying to submit a PR

**Comment by bcoca** [comment]
collections work on a 'first found' basis, the precedence is 'adjacent' + configured paths in order

**Comment by henriqueccapozzi** [comment]
@savitojs from what you originally suggested the ansible-galaxy CLI should overwrite the collection with the same name lower version number...

I was not able to reproduce the exact situation you pointed out but my consideration would be the bellow


replacing `/tmp/collections` with the appropriated path

```bash
$ export ANSIBLE_COLLECTIONS_PATHS=/tmp/collections
$ ansible-galaxy collection list
$ ansible-galaxy collection install kubernetes.core:==1.2.0
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/download/kubernetes-core-1.2.0.tar.gz to /home/henrique/.ansible/tmp/ansible-local-97681vhjz3pxy/tmpiasu15rq/kubernetes-core-1.2.0-z_yw6a3w
Installing 'kubernetes.core:1.2.0' to '/tmp/collections/ansible_collections/kubernetes/core'
kubernetes.core:1.2.0 was installed successfully


$ ansible-galaxy collection list                           

# /tmp/collections/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 1.2.0  


$ ansible-galaxy collection install kubernetes.core        
Starting galaxy collection install process
Nothing to do. All requested collections are already installed. If you want to reinstall them, consider using `--force`.


$ ansible-galaxy collection install kubernetes.core --force
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/download/kubernetes-core-1.2.1.tar.gz to /home/henrique/.ansible/tmp/ansible-local-97765yo5cs9d3/tmpjfruxr9w/kubernetes-core-1.2.1-d1fkv5b1
Installing 'kubernetes.core:1.2.1' to '/tmp/collections/ansible_collections/kubernetes/core'
kubernetes.core:1.2.1 was installed successfully


```
After your done upgrading the role you want remember to unset the `ANSIBLE_COLLECTIONS_PATHS` environmental variable in case other roles you need are not in the path you choose

But personally i would change the `ANSIBLE_COLLECTIONS_PATHS` for a specific location before running the 
`ansible-galaxy install`

That way when you run your ansible* command, you will have full control over the available collections

**Comment by henriqueccapozzi** [comment]
@bcoca I started some tests related to adding the `--only-used`  CLI flag and have the following question

When you say 'adjacent' path, is that `~/.ansible/collections` ?

**Comment by bcoca** [comment]
no, that is a 'configured path', when saying 'adjacent', it means relative to playbook file, just like roles and plugins work (roles/, library/ , filter_plugins/, etc).

An example for listing w/o adjacent https://github.com/bcoca/std/blob/devel/list_collections.py (mostly there for those using older ansible versions)

**Comment by henriqueccapozzi** [comment]
Alright, initially i though it was that, but i could not see the adjacent path being reference in the `lib/ansible/cli/galaxy.py` file or in the invocation off the `ansible-galaxy collection ...` command

But running a playbook will actually look for the collection and work as you said

I oppened #74942 to address this point and will propose a PR to add the adjacent path to ansible-galaxy commands


@bcoca, does it seems like i'm missing something?

**Comment by bcoca** [comment]
Yes, see `--playbook-dir` for adhoc/console and others that don't use a playbook, 'adjacent' needs something to be adjacent to. Since ansible-galaxy does not use a playbook, there is nothing to be adjacent to.

**Comment by henriqueccapozzi** [comment]
Got it, based on what you said related to `--playbook-dir` option, it doesn't seem a very good option to add the CLI flag `--only-used`
since the imported collection can change based on the path from a playbook is being called the `--only-used` flag can lead to confusion
