### ISSUE TITLE
wait_for_connection should not fail when ignore_unreachable=true

### ISSUE THREAD

**Issue by goshansp** [ansible/ansible#74300]
### Summary

`wait_for_connection` will cause an entire play to fail, if a host is unreachable, despite `ignore_unreachable=true`.  According  [ignore_unreachable documentation](https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#id4) unreachable hosts should not cause the task to fail.

### Issue Type

Bug Report

### Component Name

wait_for_connection

### Ansible Version

```console
ansible 2.10.4
  config file = None
  configured module search path = ['/home/hp/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/hp/.local/lib/python3.9/site-packages/ansible
  executable location = /home/hp/.local/bin/ansible
  python version = 3.9.2 (default, Feb 20 2021, 00:00:00) [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Fedora 33, RHEL 8

### Steps to Reproduce

```
---
- hosts: all
  ignore_unreachable: true
  tasks:
   - name: sets failed
     wait_for_connection:
       timeout: 1
```

### Expected Results

```console
PLAY RECAP failed=0
```

### Actual Results

```console
PLAY RECAP failed=1
```

### Code of Conduct

I agree to follow the Ansible Code of Conduct

**Comment by goshansp** [comment]
Should line 111 be removed from https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/wait_for_connection.py ?

**Comment by jborean93** [comment]
The `wait_for_connection` handles unreachable hosts and I think you need `ignore_errors: true` instead here because it's seen as a failed task and not an unreachable host where the errors are being handled. I'm not sure we can change the behaviour so it also respects `ignore_unreachable` but that would require some further investigation.

Are you able to see if `ignore_errors` helps in this case?

**Comment by goshansp** [comment]
wow @jborean93 that was impressive responsiveness, much appreciated. my usecase does not allow `ignore_errors` as we would like to detect killing the canaries at the end of the play. apparently `wait_for_connection` cannot simply return `unreachable` instead of `failed`.

**Comment by jborean93** [comment]
Yea I don't think it will be possible without breaking the existing use cases of people that have `ignore_errors: true` on the task.

**Comment by goshansp** [comment]
for example `gather_facts` and `ping` adhere to `ignore_unreachable` by not causing failed=1 and i grow in confidence that `wait_for_connection` behave the same.

**Comment by goshansp** [comment]
@jborean93 do you think the PR is complete and will not break existing use cases this way? please let me now if you can refer someone to merge it or if you see room for improvement. thanks for you valuable contributions.

**Comment by goshansp** [comment]
switching from ```wait_for_connection``` to ```ping``` seems to fix my issue. further i think ```wait_for_connection``` is not behaving according documentation nor intuitive and it should be deprecated. from my understanding ```wait_for_connection``` can be completely replaced using ```ping/until/retries```.
