### ISSUE TITLE
ansible-playbook --step mode

### ISSUE THREAD

**Issue by ingtarius** [ansible/ansible#7433]
##### Issue Type:

“Documentation Report”
##### Ansible Version:

ansible 1.5.5
##### Environment:

N/A
##### Summary:

Please, add more information about --step option. Like:

  --step                one-step-at-a-time: confirm (y = yes) each task before running, reject (n = no) or skip (c = continue) step mode and run all tasks
##### Expected Results:

More information about this option

**Comment by mpdehaan** [comment]
This is really just a command line flag, so we ought to make sure it's reflected in the manpages, certaintly.

Did you mean to say the error message didn't indicate that c=continue?

If so, we should fix that in the program, rather than (just) the docs.

Thanks!

**Comment by ingtarius** [comment]
No, my point is: when you use --step flag, ansible wait your input for each step - y, n or c ("C" is not clear, and i cant find any entry in docs about) My shoot was - y mean yes, n - no, and c mean cancel. Actually it means continue and run all lower tasks with "yes" option.
Thanks for "when" option for role, i kept all enviroment in save :)
And if you just add this information in help menu it will be ok.

**Comment by sheldonh** [comment]
As per #11667, the `--step` flag is currently ignored in devel.
