### ISSUE TITLE
sudo and executable option do not work as expected (by me)

### ISSUE THREAD

**Issue by chef2gare** [ansible/ansible#7434]
##### Environment:

running ansible on gentoo to manage gentoo, but it's not revelant in this case.
##### Summary:

when using the executable option in config file, ansible append this to all command.

my sudoers file looks like:
user ALL=NOPASSWD: /bin/su
i understand that ansible would like to have something more like /bin/sh or ALL.
##### Steps To Reproduce:

so i tried the executable option this way:
 executable = /bin/su
and ran :
ansible -vvvv spof -m ping --sudo
##### Actual Results:

and get this result :
EXEC ['ssh', '...ssh options...', 'spof', "/bin/su -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1400268469.95-169172113109278 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1400268469.95-169172113109278 && echo $HOME/.ansible/tmp/ansible-tmp-1400268469.95-169172113109278'"]

and, obviously, freeze

so i changed the runner/connection_plugins/ssh.py :
269         if su and su_user:
270             sudocmd, prompt, success_key = utils.make_su_cmd(su_user, executable, cmd)
271             ssh_cmd.append(sudocmd)
272         elif not self.runner.sudo or not sudoable:
273             prompt = None
274             #if executable:
275             #    ssh_cmd.append(executable + ' -c ' + pipes.quote(cmd))
276             #else:
277             #    ssh_cmd.append(cmd)
278             ssh_cmd.append(cmd)
279         else:
280             sudocmd, prompt, success_key = utils.make_sudo_cmd(sudo_user, executable, cmd)
281             ssh_cmd.append(sudocmd)
##### Expected Results:

and it now works as i expected :
     EXEC ['ssh', '... ssh options...', 'spof', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1400269829.16-10735200365884 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1400269829.16-10735200365884 && echo $HOME/.ansible/tmp/ansible-tmp-1400269829.16-10735200365884']
     EXEC ['ssh', '... ssh options ...', 'spof', u'/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=lyblqznqzgedkdqlwxggscttekmomkom] password: " -u root /bin/su -c \'"\'"\'echo SUDO-SUCCESS-lyblqznqzgedkdqlwxggscttekmomkom; LC_CTYPE=C LANG=C /usr/bin/python /home/niko/.ansible/tmp/ansible-tmp-1400269829.16-10735200365884/ping; rm -rf /home/niko/.ansible/tmp/ansible-tmp-1400269829.16-10735200365884/ >/dev/null 2>&1\'"\'"\'\'']
spof | success >> {
    "changed": false, 
    "ping": "pong"
}

**Comment by bcoca** [comment]
You have the option to use su instead of sudo in ansible, making su the
'sudo executable' will not work as the optoins passed are not compatible.

here is when it was added https://github.com/ansible/ansible/pull/5694

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
Yes, don't change the sudo executable to su, use the native su support and you'll be fine.

Please stop by the users list if you need more help with this.

Thanks!
