### ISSUE TITLE
Variables defined in roles are taking precedence over those in group_vars

### ISSUE THREAD

**Issue by craigmarvelley** [ansible/ansible#7441]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.1
##### Environment:

OS X 10.9.2
##### Summary:

I'm running a playbook against an ec2 instance which has groups defined via ec2 tags. Say I have a tag called `tag_name_foo` - I have a corresponding file at `<playbook_dir>/group_vars/tag_name_foo` with some overrides for variables defined in various roles.

I have verified that variables from the group vars file are being loaded by Ansible, but where a variable has also been defined in a `main.yml` file associated with a role, when the playbook runs the variable takes its value from the role file, not the group_vars file. If I remove the variable from the role file, it does have the value in the group file. I believe from the documentation it should be the other way around, so it seems that the precedence is wrong here?
##### Steps To Reproduce:

Define some variables in a role. Place a host in a group and in a file with the corresponding group name, under a group_vars directory, change the values of the variables in the role file. Run the playbook (I'm doing so against an ec2 instance, but have verified it against a static inventory with a Virtualbox VM). Output the values via the `debug` module.
##### Expected Results:

The variables should have the corresponding values specified in the group_vars files as according to http://docs.ansible.com/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable.
##### Actual Results:

The variables have the values from the role variable file located at  `<role>/vars/main.yml`.

**Comment by mpdehaan** [comment]
This is working as designed as explicit vars passed to roles beat inventory variables.

Seems like you want to set defaults/ instead of vars/.

Stop by the mailing list if you'd like to discuss further and we can help you out.

**Comment by craigmarvelley** [comment]
Wow, I'd not spotted defaults in the docs. That'll do, cheers.
