### ISSUE TITLE
ansible-playbook doesn't accept IPv6 address in inventory

### ISSUE THREAD

**Issue by gonzzor** [ansible/ansible#7446]
##### Environment:

Running ansible on Fedora 20. Trying to connect to Ubuntu 14.04.
##### Summary:

There seem to be an issue where ansible-playbook doesn't recognize hosts with pure IPv6 address but ansible does.

Jmainguy on #ansible@freenode found out that fqdn works. So by giving the ipv6 address a name using /etc/hosts I could get ansible-playbook to work.
##### Steps To Reproduce:

```
$ cat hosts
2001:db8::56c

$ ansible --version
ansible 1.7 (devel cbea442ec2) last updated 2014/05/18 21:11:37 (GMT +200)

$ ansible -i hosts -m ping --ask-pass -u root all
SSH password:
2001:db8::56c | success >> {
    "changed": false,
    "ping": "pong"
}

$ cat ping.yml

---
- hosts: all
  tasks:
    ping:

$ ansible-playbook --version
ansible-playbook 1.7 (devel cbea442ec2) last updated 2014/05/18 21:11:37 (GMT +200)

$ ansible-playbook -i hosts  --ask-pass -u root -vvvv ping.yml  
SSH password:

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ********************************************************************
```
##### Expected Results:

Working ping result when using ansible-playbook.
##### Actual Results:

Non-working ansible-playbook. :(

**Comment by jimi-c** [comment]
The patch above is a preliminary fix for this issue, however it requires more testing to ensure there are no unintended side-effects (all unit and integration tests pass currently).

**Comment by jimi-c** [comment]
I have merged the above patch in, so this issue should be resolved. If you continue having problems related to this, or if you have any further questions, please let us know. Thanks!

**Comment by narqo** [comment]
I have exactly the same problem with ansible 1.9.2. 

`ansible -i "my:ip:v:6," all -m ping` works fine, but when I try to call `ansible-playbook` with the same inventory I get "no hosts matched" error

**Comment by andrewrothstein** [comment]
@narqo are you still having a problem with this?

**Comment by narqo** [comment]
I think I've managed to deal with the problem, but I don't remember any details.
