### ISSUE TITLE
Service module fails silently on 1.6 when locale en_US.utf-8 is not enabled on target

### ISSUE THREAD

**Issue by Gu1** [ansible/ansible#7448]
##### Issue Type:

Bug report
##### Ansible Version:

1.6.x
##### Environment:

Debian 7
##### Summary:

I'm having problems with the service module on ansible 1.6.x. The module silently fails: it reports the service as successfully started or stopped while they actually are not.

I bissected the issue and commit c115c34a1f5d570422b2560cc3ff0ce0ebe53dff seem to be responsible.

My servers usually don't have the en_US.utf8 locale enabled, and when I enable it, the service are indeed started by ansible as expected.

This locale behavior should be at least documented somewhere...
##### Steps To Reproduce:

```
ansible target -m service -a "name=service_name state=started"
```

on a server (debian wheezy in my case) with en_US.utf8 locale disabled
##### Expected Results:

service should be started
##### Actual Results:

service is not started...

**Comment by mpdehaan** [comment]
In queue for reproducing this, can you please share what service you are managing?

**Comment by Gu1** [comment]
The service I was trying to start (unsuccessfully) is libvirt-bin. I also tried to stop the ssh service to see if only libvirt-bin was in cause, but no more luck, so I guess it affects every service ?.

**Comment by jimi-c** [comment]
@Gu1 you can set "module_lang" in your ansible.cfg to the proper locale if you do not have `en_US.UTF-8` on those systems.

**Comment by jimi-c** [comment]
@Gu1 I've merged in the above patch which should help address this situation. Going forward, if the locale specified is not valid for the system, the module will revert back to the 'C' locale automatically. If you continue having any problems regarding this issue, please let us know. Thanks!

**Comment by Gu1** [comment]
Thanks for the quick response. I don't think your commit completely fixes the problem, though.
The local set through setlocale() is not passed down to processes executed by the modules, AFAIU.

```
$ ssh 127.0.0.1 -p 2222 'grep "^[^#]" /etc/locale.gen'
fr_FR.UTF-8 UTF-8
$ pip install git+https://github.com/ansible/ansible.git
<snip>
$ ansible -vv 127.0.0.1:2222 -K -i hosts_local -m shell -a "env"
sudo password: 
<127.0.0.1> REMOTE_MODULE command env #USE_SHELL
127.0.0.1 | success | rc=0 >>
(...)
LC_CTYPE=en_US.UTF-8
LANG=en_US.UTF-8
(...)
```

**Comment by jimi-c** [comment]
@Gu1 you're correct. I've just pushed another commit that also sets the environment variables when the locale is reset to 'C'. My testing shows this works:

<pre>
$ ANSIBLE_MODULE_LANG=de_DE.UTF-8 ansible -vv -m shell -a "env|grep LANG" ubuntu1404
<192.168.122.113> REMOTE_MODULE command env|grep LANG #USE_SHELL
192.168.122.113 | success | rc=0 >>
LANG=C
</pre>

The commit is https://github.com/ansible/ansible/commit/0ac74aaf59d1ea028804f19cf34c5af4ede3618f
