### ISSUE TITLE
pip installing ansible in a virtualenv tries to write data to a global directory.

### ISSUE THREAD

**Issue by jcdyer** [ansible/ansible#7450]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.6.1
##### Environment:
- OS: debian/jessie
- python: 2.7.6
- pip: 1.5.4
##### Summary:

When running `pip install ansible` in a new virtualenv, the build tries to install data files to /usr/share, which of course is shared with installations of other versions in other virtualenvs.  It also requires permissions that the user probably doesn't have.

Ansible should instead keep its shared files inside the virtualenv.
##### Steps To Reproduce:

(with python, pip, virtualenv, and virtualenvwrapper installed)
(as user without write permission to /usr/share)

$ mkvirtualenv tmp
$ pip install ansible # currently ==1.6.1
##### Expected Results:

Ansible gets installed.
##### Actual Results:

pip errors out when running install_data

Output (snipped):

```
[...]
running install_data

copying ./library/commands/shell -> /usr/share/ansible/commands
error: could not delete '/usr/share/ansible/commands/shell': Permission denied
----------------------------------------
```

**Comment by mpdehaan** [comment]
Hi,

Ansible is a systems application, not just a python library, so it likes to use certain LSB paths.   It will read your ansible.cfg and environment variables (see setup.py) to attempt to install them in those locations, but it's recommended you either install ansible globally or just run it from source with "source ./hacking/env-setup"
