### ISSUE TITLE
Support Jinja2 in ansible playbooks

### ISSUE THREAD

**Issue by snilard** [ansible/ansible#7459]
##### Issue Type:

Feature Idea
##### Ansible Version:

N/A
##### Environment:

N/A
##### Summary:

I would like to be able to use Jinja2 scripting in ansible playbook.
For example I would like to write this:

```
state={% if pg_backup is 'on' %} present {% else %} absent {% endif %}
```

I know that I can handle this by 2 tasks and contitionals but It looks strange.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by jimi-c** [comment]
Thanks for your suggestion, however we are not currently looking to use jinja2 style syntax as above directly in any fields (except for `when:`, which uses jinja2 syntax). We aim to keep playbook syntax as clean as possible while avoiding programmatic things like the above, which belong in templates. Thanks!
