### ISSUE TITLE
error with undefined value while error_on_undefined_vars: False

### ISSUE THREAD

**Issue by mgcrea** [ansible/ansible#7460]
##### Issue Type:

Bug Report
##### Ansible Version:

``` bash
$ ansible --version
ansible 1.6.1
```
##### Environment:

``` bash
$ uname -a
Darwin 0x6D6763726561 13.2.0 Darwin Kernel Version 13.2.0: Thu Apr 17 23:03:13 PDT 2014; root:xnu-2422.100.13~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin
```
##### Summary:

error with undefined value while error_on_undefined_vars: False
##### Steps To Reproduce:

I've been using conditionals to target docker containers lately, and ended up with something like this:

``` bash
## Configure service
- include: configure-upstart.yml
  when: ansible_cmdline.user != 'docker'
- include: configure-supervisor.yml
  when: ansible_cmdline.user == 'docker'
```

However this fails with the error `error while evaluating conditional: ansible_cmdline.user != 'docker'` on non-docker containers, probably because of the fact that the var is undefined.

I'm using an ansible.cfg in the same directory with:

``` ini
[defaults]
error_on_undefined_vars: False
```
##### Expected Results:

I'm expecting `undefined != 'docker'` to be truthy and not fail in that case.
##### Actual Results:

 `error while evaluating conditional: ansible_cmdline.user != 'docker'`

**Comment by mpdehaan** [comment]
I don't really view this as a bug as there is no way for this conditional to have meaning.

It does mean template ops like {{ foo }} will leave blanks and such.

To be honest, I see this "error_on_undefined_vars" (which is no longer the default) to be something that _may_ be deprecated in the future - as there's almost no case where it's a good thing.

It was just legacy behavior that we continued to support to avoid a compatibility change long ago, but it's been off by default for a long time.

Anwyay, the conditional needs the variable.

You can do:

when: foo is defined and foo == 2

and such, and that will work.
