### ISSUE TITLE
All 'hardware/*.py' fact gathering silently fails when get_mount_info() throws an exception

### ISSUE THREAD

**Issue by agunnerson-ibm** [ansible/ansible#74657]
### Summary

When `hardware/linux.py` is gathering facts, if `get_mount_info()` (inside `get_mount_facts()`) fails and `res.successful()` returns false, then it tries to call `res.get()` on the result:

https://github.com/ansible/ansible/blob/d1c49f2e1c991b56060267b38751dad4ba703bdb/lib/ansible/module_utils/facts/hardware/linux.py#L576-L577

However, `multiprocessing.pool.AsyncResult.get()` is defined to reraise the exception, not return it: https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.AsyncResult.get

This causes the entire `hardware` fact gathering to fail due to the reraised exception. Additionally, this exception gets eaten by the following handler. The `sys.stderr.write` doesn't seem to print to the controller's terminal. I had to remove it in order to see the stack trace.

https://github.com/ansible/ansible/blob/d1c49f2e1c991b56060267b38751dad4ba703bdb/lib/ansible/module_utils/facts/ansible_collector.py#L75-L77

The end result is that whenever `get_mount_info()` on the async pool fails, the exception is reraised outside of the `multiprocessing` context and _all_ of the `hardware/*.py` facts get silently dropped.

### Issue Type

Bug Report

### Component Name

facts

### Ansible Version

```console
ansible 2.10.9
  config file = None
  configured module search path = ['/home/jenkins/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]
```

### Configuration

```console
(no output)
```

### OS / Environment

Controller:
* Alpine Linux 3.13.5
* Python 3.8

All target hosts:
* CentOS 7
* Python 2.7

### Steps to Reproduce

```yaml
    - name: Gather hardware facts
      setup:
        gather_subset: '!all,!min,hardware'

    - name: DEBUG - Dump host vars state if fact gathering does not include mount information
      debug:
        var: ansible_facts
      when: ansible_mounts is not defined
```
With this playbook, it may take many reruns to reproduce the issue (need `get_mount_info()` to fail). It may be easier to simply edit `hardware/linux.py` to make `get_mount_info()` always throw an exception since the issue is in the error handling code.

### Expected Results

When `get_mount_info()` fails, the exception information should show up in the `['info']['note']` field of the mountpoint fact. (Additionally, I think that any hard failures during fact gathering should have some error printed to the screen instead of being silently ignored.)

### Actual Results

```console
When `get_mount_info()` fails, all `hardware` facts are silently ignored/dropped.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by bcoca** [comment]
top of my head, something like this should ensure this works:
```
diff --git a/lib/ansible/module_utils/facts/hardware/linux.py b/lib/ansible/module_utils/facts/hardware/linux.py
index 0829d495c9..a152b6b998 100644
--- a/lib/ansible/module_utils/facts/hardware/linux.py
+++ b/lib/ansible/module_utils/facts/hardware/linux.py
@@ -25,7 +25,7 @@ import re
 import sys
 import time

-from multiprocessing import cpu_count
+from multiprocessing import cpu_count, TimeoutError as mpTimeoutError
 from multiprocessing.pool import ThreadPool

 from ansible.module_utils._text import to_text
@@ -567,14 +567,22 @@ class LinuxHardware(Hardware):
             for mount in results:
                 res = results[mount]['extra']
                 if res.ready():
-                    if res.successful():
-                        mount_size, uuid = res.get()
-                        if mount_size:
-                            results[mount]['info'].update(mount_size)
-                        results[mount]['info']['uuid'] = uuid or 'N/A'
-                    else:
-                        # give incomplete data
-                        errmsg = to_text(res.get())
+                    errmsg = ''
+                    try:
+                        if res.successful():
+                            mount_size, uuid = res.get()
+                            if mount_size:
+                                results[mount]['info'].update(mount_size)
+                            results[mount]['info']['uuid'] = uuid or 'N/A'
+                        else:
+                            # give incomplete data
+                            errmsg = to_text(res.get())
+                    except mpTimeoutError as e:
+                        raise timeout.TimeoutError(to_native(e))
+                    except Exception as e:
+                        errmsg = to_text(e)
+
+                    if errmsg:
                         self.module.warn("Error prevented getting extra info for mount %s: %s." % (mount, errmsg))
                         results[mount]['info']['note'] = 'Could not get extra information: %s.' % (errmsg)
```

**Comment by bcoca** [comment]
I do not have a reproducer though ... so not sure how to test this w/o making a 'bad nfs mount' ... which really is not something we want in CI

**Comment by agunnerson-ibm** [comment]
Thanks for the PR! I'll give it a try in our environment.

I'm not sure if it would be appropriate for CI, but would it make sense to implement a dummy FUSE filesystem using python-fuse that only has a `statfs` hook which always fails?
