### ISSUE TITLE
alternatives: /usr/sbin/update-alternatives is not valid on all distributions

### ISSUE THREAD

**Issue by ThomasNunninger** [ansible/ansible#7465]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.6
##### Environment:

Running: Ubuntu 12.04.4 LTS
Managed: Ubuntu 14.04 LTS
##### Summary:

Module alternatives uses wrong binary path on Ubuntu 14.04.
##### Steps To Reproduce:

Sorry, I'm new to ansible and I don't know how to write a reproducible script in a short time.
##### Expected Results:

/usr/bin/update-alternatives is used instead of /usr/sbin/update-alternatives
##### Actual Results:

```
failed: [server.local] => {"cmd": "/usr/sbin/update-alternatives --query editor", "failed": true, "item": "", "rc": 2}
msg: [Errno 2] No such file or directory
```

**Comment by jimi-c** [comment]
I have merged in the patch above, which should resolve this issue. Please let us know if you continue having any problems related to this. Thanks!
