### ISSUE TITLE
in a playbook, if "user:" is not set, assume the current user

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#747]
this should be true for playbooks and ONLY playbooks.

If "user:" is ommited and we are logged in as "bob", assume "user: bob".  Assume nothing about sudo and sudo_user.   If we have "-vvv" by then, we should mention connection details.

/usr/bin/ansible's "-u" is entrenched at this point, and "user:" was formerly a required element, so we would not want to break anyone by changing this.  This also has the advantage of not messing with any of the connection types and so forth.

(It has been proposed that we read the user from SSH config, though I don't like this because it assumes you would be logging in from one and only one user, which isn't nice if there is no SSH config that talks about that host, among other reasons, and leaves the SSH connection type having the fun of parsing the file or requiring paramiko to do it, both of which are heinous)

**Comment by willthames** [comment]
Note that the ssh connection type will already read .ssh/config (and indeed /etc/ssh/config), as it uses the ssh command under the hood. 

The default of what to do if there is no User specified for a Host in the ssh config is the difficult choice - I think using logged in user is better than the current default of root.

**Comment by mpdehaan** [comment]
That's what the above says, use logged in user if "user:" is not present.

**Comment by mpdehaan** [comment]
done, changed -u as well, was easier
