### ISSUE TITLE
accept_hostkey in git module doesnt call ssh-keyscan

### ISSUE THREAD

**Issue by landryb** [ansible/ansible#7474]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.6 (devel c6f3a0a4cc) last updated 2014/05/02 09:59:57 (GMT +200)
##### Environment:

Debian wheezy
##### Summary:

accept_hostkey in git module doesnt do what it's supposed to (ie fetch the server host key at first connection)
##### Steps To Reproduce:

```
- name: checkout mapfiles
  tags: git
  git: repo=ssh://{{ git_server }}/var/git/wms dest={{ mapserver_mapfile_dir }} accept_hostkey=yes version=ortho-2013
```

with that playbook/task snippet, and having no .ssh/known_hosts file on the remote server / git client, ansible waits forever. when ctrl-c'ed, it shows the confirmation message asking the user to validate the git_server key fingerprint. ssh-keyscan is installed, and i can manually run it as ssy-keyscan -t rsa git.server, it correctly prints the server key.
##### Expected Results:

It should add the remote server key to .ssh/known_hosts, and proceed with the checkout/clone.
##### Actual Results:

timeouts... also tried with an empty known_hosts file, same problem. If i manually ssh to the server from the ansible target to add the key to known_hosts, ansible does the git clone fine. I looked at the code in ansible/lib/ansible/module_utils/known_hosts.py and library/source_control/git and didnt find a possible reason for this broken behaviour.

**Comment by mpdehaan** [comment]
In queue to reproduce, thanks!

**Comment by landryb** [comment]
Maybe this isnt catched by the integration tests, since by default those are skipped (when: github_ssh_private_key is defined) .. unless jenkins has a key setupped ?

```
~/ansible/test/integration #ansible-playbook -i inventory non_destructive.yml --extra-vars='output_dir=/tmp/ansible-test' -t test_git
TASK: [test_git | checkout ssh://git@github.com repo without accept_hostkey (expected fail)] *** 
failed: [testhost] => {"failed": true, "item": ""}
msg: github.com has an unknown hostkey. Set accept_hostkey to True or manually add the hostkey prior to running the git module
...ignoring

TASK: [test_git | assert ] **************************************************** 
ok: [testhost]

TASK: [test_git | checkout git@github.com repo with accept_hostkey (expected pass)] *** 
skipping: [testhost]
```

**Comment by landryb** [comment]
Note that in the meantime, i can workaround it by adding this task before the git task, but that's a bit awkward :) 

```
- name: ssh-keyscan the git server #https://github.com/ansible/ansible/issues/7474
  shell: ssh-keyscan -H -t dsa {{git_server}} >> ~/.ssh/known_hosts 2>&1
```

with that, the git task succeeds.

**Comment by jimi-c** [comment]
@landryb have you tried this with the current devel branch? I'm not able to reproduce the issue, though I have also tested on release1.6.0 and can't reproduce it their either. On the test system:

<pre>
testing@ubuntu1204:~$ rm -f ~/.ssh/known_hosts 
testing@ubuntu1204:~$ cat ~/.ssh/known_hosts 
cat: /home/testing/.ssh/known_hosts: No such file or directory
</pre>

Running this playbook:

<pre>
- hosts: ubuntu1204
  gather_facts: no
  remote_user: testing
  tasks:
  - name: remove the repo directory
    file: path=~/test_role state=absent force=yes
  - git: repo=git@github.com:jimi-c/test_role.git dest=~/test_role accept_hostkey=yes version="v0.1"
</pre>

Where I have added a deploy key to that repo, for the testing user on the above system. I get the following results:

<pre>
$ ansible-playbook -vv 7474.yml 
PLAY [ubuntu1204] ************************************************************* 
TASK: [remove the repo directory] ********************************************* 
<192.168.122.110> REMOTE_MODULE file path=~/test_role state=absent force=yes
changed: [192.168.122.110] => {"changed": true, "path": "/home/testing/test_role", "state": "absent"}
TASK: [git repo=git@github.com:jimi-c/test_role.git dest=~/test_role accept_hostkey=yes version="v0.1"] *** 
<192.168.122.110> REMOTE_MODULE git repo=git@github.com:jimi-c/test_role.git dest=~/test_role accept_hostkey=yes version="v0.1"
changed: [192.168.122.110] => {"after": "4e739a34719654db7b04896966e2354e1256ea5d", "before": null, "changed": true}
PLAY RECAP ******************************************************************** 
192.168.122.110            : ok=3    changed=2    unreachable=0    failed=0   
</pre>

Are there any other configuration settings on your system that might be preventing this from working?

**Comment by jimi-c** [comment]
I forgot to mention, after running that playbook, I'm seeing the known_hosts file again with an entry for github.com, so it accepted the hostkey correctly.

**Comment by landryb** [comment]
with git HEAD, without .ssh/config, and as root connecting from a wheezy to a lenny container.. i have a passphraseless key to connect to 10.0.0.4 of course. interestingly, when using the ip in the git module with that small playbook, it asks me the question (with or without -vv) whereas in my $work playbooks, it doesnt ask it at all and silently waits for it, but maybe that's because i'm not running it on localhost. On the latter, i'm also using ansible_ssh_host for each hosts in my inventory, if that can matter.

```
services-wheezy:/tmp #mv ~/.ssh/known_hosts{,-no}
services-wheezy:/tmp #ssh 10.0.0.4
The authenticity of host '10.0.0.4 (10.0.0.4)' can't be established.
RSA key fingerprint is 34:4a:36:e7:18:8b:46:a3:64:a2:56:ea:2d:77:39:05.
Are you sure you want to continue connecting (yes/no)? ^C
services-wheezy:/tmp #cat t.yml 
- hosts: localhost
  gather_facts: no
  tasks:
  - git: repo=10.0.0.4:/var/git/wms dest=/tmp/wms  accept_hostkey=yes
services-wheezy:/tmp #ansible-playbook -vv t.yml 

PLAY [localhost]     ************************************************************** 

TASK: [git repo=10.0.0.4:/var/git/wms dest=/tmp/wms accept_hostkey=yes] ******* 
<localhost> REMOTE_MODULE git repo=10.0.0.4:/var/git/wms   dest=/tmp/wms accept_hostkey=yes
The authenticity of host '10.0.0.4 (10.0.0.4)' can't be established.
RSA key fingerprint is 34:4a:36:e7:18:8b:46:a3:64:a2:56:ea:2d:77:39:05.
Are you sure you want to continue connecting (yes/no)? 
```

**Comment by landryb** [comment]
Note that the remote git host has both a dsa and an rsa key, and is running OpenSSH_5.1p1 Debian-5, OpenSSL 0.9.8g 19 Oct 2007

**Comment by jimi-c** [comment]
And you say there is no `.ssh/config` file present for the above? What happens if you accept the host key in the first step, I'm assuming it works fine?

**Comment by landryb** [comment]
Yes, without .ssh/config. If i accept the host key when manually ssh'ing or when running ansible, the following ansible runs work fine as the key was added to known_hosts.

**Comment by jimi-c** [comment]
The above pull request should address this issue. If you continue having problems regarding this issue, please let us know. Thanks!

**Comment by landryb** [comment]
Just a minor nit then - it doesnt work in the case where git repo is ip:path (ie without any user@ spec, which shouldnt be mandatory ?) but it now works with user@ip:path .. do we want to allow ip:path, implying git over ssh as the user running the command ?

**Comment by jimi-c** [comment]
We could expand that, though it's probably best to usually specify the git url with the proper protocol anyway.

**Comment by mattjbray** [comment]
3fb3e7e fails with repos like `ssh://git@github.com/ansible/ansible.git`.

urlparse gives us back `git@github.com`, and then we get:
`failed to add git@github.com hostkey: getaddrinfo git@github.com: Name or service not known`. 

We need to strip the `git@` part.  #7789 does this.

**Comment by mtotheikle** [comment]
This fix does not work for git submodules. Has anyone encountered this?

**Comment by udondan** [comment]
As well it does not work if you have defined the git host in `.ssh/config` and just call it with `git hostname:path/repo.git`

Works:
`git user@hostname:path/repo.git`

Works not:
`git hostname:path/repo.git`, even though the user is defined in `.ssh/config`

**Comment by taraspos** [comment]
Still facing the issue when trying to clone project from bitbucket.

**Comment by franklinwise** [comment]
this is an issue for me in Ansible 1.9.1 with git::ssh://git@github.com/owner/repo

**Comment by Bersam** [comment]
Same here, for github and bitbucket repos.

**Comment by Rylon** [comment]
Ditto, I've tried a couple of permutations of the URL, for example with and without `ssh://` and also tried using `ssh-keyscan` to pre-seed the fingerprint, but to no avail. Does anyone have any suggestions?

**Comment by galindro** [comment]
Same problem here. Why this ticket was closed??

**Comment by fastinetserver** [comment]
Same problem on ansible 1.9.4 (under ubuntu-desktop 12.04 64 bit).
Task to reproduce:
    - name: clone the site from git repo
      git: repo=gl:{{project_name}} dest="/home/someuser/git/{{project_name}}" accept_hostkey=yes key_file=~/.ssh/private_key

So i use this workaround:
    - name: Add gl to known_hosts (workaround to avoid frozen git clone task)
      command: ssh -oStrictHostKeyChecking=no gl
    - name: clone the site from git repo
      git: repo=gl:{{project_name}} dest="/home/someuser/git/{{project_name}}" accept_hostkey=yes key_file=~/.ssh/private_key

**Comment by galindro** [comment]
@fastinetserver , please, post you answer here: https://github.com/ansible/ansible-modules-core/issues/1343

**Comment by kha0s178** [comment]
The same problem (no any submodules, pure git repo).
ansible 2.1.0.0
task example:

```
  - name: Cloning sources from GitLab
    git: repo="ssh://git@{{ gitlab_host }}:{{ gitlab_port }}/root/repo.git"
         dest=/tmp/zzz
         key_file=~/.ssh/id_rsa
         accept_hostkey=yes
         force=yes
```

I used two workarounds:
`ssh_opts="-o StrictHostKeyChecking=no"`
or such task before:

```
- name: manual add remote to known_hosts
  known_hosts: path='/etc/ssh/ssh_known_hosts'
               name='{{ gitlab_host }}'
               key="{{ lookup('pipe', 'ssh-keyscan -H -p {{ gitlab_port }} {{ gitlab_host }}') }}"
```

But this is wrong way. accept_hostkey=yes sould work, but still doesn't. I think that it is because of git custom ssh port.
UPD: Looked in module_utils/known_hosts.py
Yep, there in `add_host_key` function:

```
keyscan_cmd = module.get_bin_path('ssh-keyscan', True)
...
this_cmd = "%s -t %s %s" % (keyscan_cmd, key_type, fqdn)
```

There missed `-p` parameter for non-standart SSH port. Wrong git url parsing.

**Comment by stuaxo** [comment]
@kha0s178 

Any chance of a pull request that adds the -p?  Seems like quite an omission that this is broken !
