### ISSUE TITLE
user module should not need to run usermod when user already exists and it only modifies the ssh key

### ISSUE THREAD

**Issue by simonft** [ansible/ansible#7475]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

Ubuntu linux 12.04  on both 
##### Summary:

The following play will fail if the user is running a process:

```
- name: make an ssh key for jenkins user
  user: name=jenkins
        generate_ssh_key=yes
```

with the error: 

```
failed: [trex.wsli.us] => {"failed": true, "item": "", "name": "jenkins", "rc": 8}
msg: usermod: user jenkins is currently logged in
```

Since the user already exists, all it needs to do is generate the ssh key, however it still tries to run usermod and fails.
##### Steps To Reproduce:
1. Add the following to a playbook:

```
- name: make an ssh key for jenkins user
  user: name=jenkins
        generate_ssh_key=yes
```
1. Create a jenkins user on a machine
2. In a separate terminal, log in as jenkins on the machine
3. In the original terminal, run the playbook. 
##### Expected Results:

Play succeeds, key is created
##### Actual Results:

Play fails with error

**Comment by jimi-c** [comment]
I've tried reproducing this with another user, however it's not running into the same issue. When logged in as user `testing`, I can run your sample playbook above (edited for that user of course) just fine. I'm wondering if this something related to the way the jenkins user is configured? I'll install jenkins and try again specifically with that user.

**Comment by jimi-c** [comment]
Yeah, same result. On the system as the jenkins user:

<pre>
jenkins@ubuntu1204:~$ id
uid=108(jenkins) gid=114(jenkins) groups=114(jenkins)
</pre>

and running your sample playbook:

<pre>
$ cat 7475.yml 
- hosts: ubuntu1204
  gather_facts: no
  tasks:
  - name: make an ssh key for the jenkins user
    user: name=jenkins
          generate_ssh_key=yes
$ ansible-playbook 7475.yml 
PLAY [ubuntu1204] ************************************************************* 
TASK: [make an ssh key for the jenkins user] ********************************** 
ok: [192.168.122.110]
PLAY RECAP ******************************************************************** 
192.168.122.110            : ok=1    changed=0    unreachable=0    failed=0   
</pre>

My guess is that the module is detecting some difference there and is trying to correct it. Could you share the output of `getent passwd jenkins` from that system?

**Comment by simonft** [comment]
It's no longer happening for me. I'm assuming I was doing something silly. Thanks for the help.

**Comment by jimi-c** [comment]
No problem, let us know if you find anything else or if you have any further questions. Thanks!

**Comment by MikeiLL** [comment]
I'm getting the same error, and I have to confess, I'm not terribly at home with provisioning yet. I'm using a Vagrant-ansible setup from a public repository and the main playbook looks like this:

```
---
- hosts: all
  user: vagrant
  sudo: true
  sudo_user: root

  roles:
    - role: ansible-nginx
    - role: ansible-softwares
    - role: ansible-mongodb
    - role: DavidWittman.redis
    - role: ansible-nodejs
    - role: ansible-nodejs-apps
      apps:
        enabled:
          - "/myapp"
```

The output 

```
TASK: [DavidWittman.redis | install dependencies] ***************************** 
ok: [default] => (item=gcc,make,libc6-dev)

TASK: [DavidWittman.redis | install dependencies] ***************************** 
skipping: [default]

TASK: [DavidWittman.redis | enable overcommit in sysctl] ********************** 
ok: [default]

TASK: [DavidWittman.redis | add redis user] *********************************** 
failed: [default] => {"failed": true, "name": "redis", "rc": 8}
msg: usermod: user redis is currently logged in
```

I'm using ansible version 1.9 and just reinstalled from this repo. Any insights you can offer?

**Comment by shaleh** [comment]
I just ran into a problem like the redis issue above.

One of our playbooks set a user's home directory as /tmp. Not a good idea. This went unnoticed for a while. When we fixed the home directory and set "createhome=yes" we now get errors because the user exists. The Ansible code does not detect the user exists but the home directory is wrong and just fix the home directory. The work around is to either remove and recreate the user or to detect the user exists and create the home directory as a separate task. But this seems like something the user module should just handle.

We are also on 1.9.

**Comment by davidak** [comment]
I got the same error:

```
TASK [antoiner77.caddy : Create Caddy user] ************************************
fatal: [caddy-test.basecom.de]: FAILED! => {"changed": false, "failed": true, "msg": "usermod: user www-data is currently used by process 1444\n", "name": "www-data", "rc": 8}
```

```
- name: Create Caddy user
  user: name={{ caddy_user }} system=yes createhome=yes home={{ caddy_home }}
```

from https://github.com/antoiner77/caddy-ansible/blob/master/tasks/main.yml#L5

`caddy_user` is www-data and PHP-FPM is running with it.

**Comment by pavelnemirovsky** [comment]
+ 1

**Comment by frock81** [comment]
I ran into this problem too. Just in case someone else stumble upon this. From `usermod` manual:

```
CAVEATS
       You must make certain that the named user is not executing any processes when this command is
       being executed if the user's numerical user ID, the user's name, or the user's home directory
       is being changed.  usermod checks this on Linux, but only check if the user is logged in
       according to utmp on other architectures.
```

References:

- https://linux.die.net/man/8/usermod
- https://unix.stackexchange.com/questions/233614/when-trying-to-change-username-terminal-tells-me-user-is-currently-used-by-proc
