### ISSUE TITLE
copy: show error message instead of trace when validate doesn't contain %s

### ISSUE THREAD

**Issue by php-coder** [ansible/ansible#7483]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.1
##### Environment:

N/A
##### Summary:

Ansible should show correct error message when validate parameter doesn't contain %s specifier.
##### Steps To Reproduce:

```
- name: don't show version on error page
  copy: >
    dest=/etc/nginx/conf.d/server_tokens.conf
    content="server_tokens off;\n"
    validate="nginx -t"
```
##### Expected Results:

Message with error should be shown.
##### Actual Results:

```
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1400701232.68-201098736271552/copy", line 1401, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1400701232.68-201098736271552/copy", line 207, in main
    (rc,out,err) = module.run_command(validate % src)
TypeError: not all arguments converted during string formatting
```

**Comment by jjshoe** [comment]
Thanks @php-coder I'll dig into this!

**Comment by jimi-c** [comment]
@jjshoe what is the relevant commit? When we do a major release, we fork it straight off of devel so if it was in devel before 1.6.0 was tagged it should be in there.

**Comment by jjshoe** [comment]
@jimi-c ignore me, will edit comment, I believe it was post 1.6.1.

**Comment by jimi-c** [comment]
@jjshoe no problem. We're gearing up for a 1.6.2 release, just let me know the commit and I can make sure it's included in 1.6.2. Thanks!

**Comment by jjshoe** [comment]
@jimi-c:

https://github.com/ansible/ansible/commit/a34478d6f38324346da543523a5c844cb394f1eb

This would go well with it too:

https://github.com/ansible/ansible/pull/7149

**Comment by bcoca** [comment]
closing as this seems to have been fixed in https://github.com/ansible/ansible-modules-core/commit/6f0808b2
