### ISSUE TITLE
script module drops stdout if it contains any non-printable characters

### ISSUE THREAD

**Issue by nirvinehh** [ansible/ansible#7486]
##### Summary:

When using the script module, stdout gets dropped (replaced with '') if it contains non-printable characters.  They should be stripped instead.
##### Steps To Reproduce:

``` bash
    $ cat script.sh
    echo -e \\a critical information

    $ ansible -i $target, -m script -a script.sh $target
```
##### Expected Results:

``` bash
$ ansible -i $target, -m script -a script.sh $target
$target | success >> {
    "changed": true,
    "rc": 0,
    "stderr": "",
    "stdout": " critical information\r\n"
}
```
##### Actual Results:

``` bash
    $ cat script.sh
    echo -e \\a critical information

    $ ansible -i $target, -m script -a script.sh $target
    $target | success >> {
        "changed": true,
        "rc": 0,
        "stderr": "",
        "stdout": ""
    }
```

I believe the problem lies in the following line (879 in lib/ansible/runner/**init**.py):

``` python
                    if not string_functions.isprintable(data['stdout']):
                                            data['stdout'] = ''
```

The correct action is probably to clean the string instead.  I'll whip up a pull request, but please review thoroughly.

**Comment by nirvinehh** [comment]
Any progress on this?

**Comment by aiman** [comment]
I have this problem as well. For example, `rm -v` produces Unicode apostrophes:

``` bash
$ rm -v /tmp/foo
removed ‘/tmp/foo’
```

This results in zero-length Ansible `stdout`.

One workaround is to pipe the output of the command through `tr`:

``` bash
#!/bin/bash
rm -v /tmp/foo | tr --delete --complement '[:print:]'
```

Alternatively this can be done for the entire script using process substitution:

``` bash
#!/bin/bash

# save stdout to fd3
exec 3>&1

# redirect stdout through tr using process substitution
exec 1> >(tr --delete --complement "[:print:]")

# ...commands...
rm -v /tmp/foo

# restore stdout and close fd3
exec 1>&3 3>&-
```
