### ISSUE TITLE
add_host task is not run (or skipped) for all hosts in the list

### ISSUE THREAD

**Issue by kristous** [ansible/ansible#7488]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

Debian GNU/Linux 7.5 (wheezy), Ubuntu 12.04
##### Summary:

add_host task is not executed or at least skipped for every host in the hostlist.
If run against only one host with it works as expected.
If run against multiple hosts only the first from ansible hosts file will be added to the group or skipped.
##### Steps To Reproduce:
- hosts: hostlist
  user: "{{ ssh_user }}"
  sudo: yes
  tasks:
  - name: stat /tmp/dummy
    stat: path=/tmp/dummy
    register: dummy
  - name: add to dummygroup
    add_host: name="{{ inventory_hostname }}" groups=dummygroup
    when: dummy.stat.exists is defined and dummy.stat.exists == true
##### Expected Results:

At least a skipped for every host in the list
##### Actual Results:

ansible-playbook bug.yml -v

PLAY [hostlist] ******************************************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [host3.example.com]
ok: [host2.example.com]
ok: [host1.example.com]

TASK: [stat /tmp/dummy] ******************************************************\* 
ok: [host3.example.com] => {"changed": false, "stat": {"exists": false}}
ok: [host2.example.com] => {"changed": false, "stat": {"atime": 1400734828.0029335, "ctime": 1400560489.169877, "dev": 64769, "exists": true, "gid": 0, "inode": 5769287, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "md5": "d41d8cd98f00b204e9800998ecf8427e", "mode": "0644", "mtime": 1400560489.169877, "nlink": 1, "pw_name": "root", "rgrp": true, "roth": true, "rusr": true, "size": 0, "uid": 0, "wgrp": false, "woth": false, "wusr": true, "xgrp": false, "xoth": false, "xusr": false}}
ok: [host1.example.com] => {"changed": false, "stat": {"exists": false}}

TASK: [add to reboot_hosts] **************************************************\* 
skipping: [host1.example.com]

PLAY RECAP *******************************************************************\* 
host2.example.com               : ok=2    changed=0    unreachable=0    failed=0  
host1.example.com                : ok=2    changed=0    unreachable=0    failed=0  
host3.example.com      : ok=2    changed=0    unreachable=0    failed=0

**Comment by sivel** [comment]
This is the expected behavior of add_host. add_host is what is called a host loop bypass plugin, that only executes on the first host in the list.  For more details see https://github.com/ansible/ansible/issues/6912#issuecomment-39957335

What you may want instead is to use group_by.

**Comment by jimi-c** [comment]
@sivel is correct, this is expected behavior. Internally, the add_host action plugin receives the list of hosts, rather than iterating over each host. If you have any further questions regarding the use of add_host or group_by, please direct them to the mailing list. Thanks!
