### ISSUE TITLE
Add state=present to file module (rather than state=touch)

### ISSUE THREAD

**Issue by hjwp** [ansible/ansible#7490]
##### Summary:

cf discussion on #4097.  Although `state=touch` works pretty well, something called `state=present` would be more useful for (what I think is) a very common use case.
##### Actual Results: n/a

The example is: making sure that a log file is present, and has the correct perms to be written to by a program.

What's desired is that ansible should create the file, and give it the correct permissions, if it doesn't exist.  This is already achieved by the `state=touch` option. 

However, `touch` has a couple of undesirable side-effects in this use case.  Firstly, it does a `touch` even when the file does already exist and has the correct perms, which causes spurious updates to the log files last modified & accessed perms.  Secondly, ansible registers the step as "changed" every time it's run, even though, as far as I cared, there was nothing that needed to be done.  This makes it hard to, eg, drive a correct handler notification from the step.

So, a minor enhancement proposal, but a useful one I think.

**Comment by mpdehaan** [comment]
This can be done with:

copy: content="" dest=/path/to/file force=no # plus optional args like mode, etc

**Comment by hjwp** [comment]
Is there a way of specifying owner and permissions with `copy`?  It doesn't look like it from [the docs](http://docs.ansible.com/copy_module.html)

**Comment by jimi-c** [comment]
All of the `files/` modules (file, copy, template, etc.) take the owner and other parameters as defined in the file module itself. There is an open issue to address showing that information on those module docs pages as well.

**Comment by illenseer** [comment]
@mpdehaan but `copy` with `force=no` does not ensure correct owner, group and mode for the file, when the file is already present, then you still need `file` to do that. And IMO it is better to just declare it once and not twice. Also if you have to declare it twice there is potential space for mistakes and inconsistencies when someone updates it.

**Comment by jimi-c** [comment]
@illenseer copy also takes those same owner/permissions/etc. attributes. As I noted above, there is an open issue to reflect that in the documentation.

**Comment by illenseer** [comment]
@jimi-c yes, I know, but with `force=no` it won't enforce owner/permissions/etc. If the file is present `copy` does nothing at all.

**Comment by bencord0** [comment]
It appears that I'm late to this discussion.

My current workaround is to combine the command and file modules. (This is with ansible-1.8.2, latest in pypi.)
- command: touch /var/log/something.log creates=/var/log/something.log
- file: path=/var/log/something.log state=file owner=someone group=collective mode=0644

Which would be much nicer if there was a file: state=present.

Requirements:
- If the log file doesn't exist, doesn't have the right permissions, the daemon can't run (and the daemon can't create the log file).
- If the file exists, the permissions should be checked and corrected if necessary (triggering changed=true). If permissions are correct, no action should be taken and changed=false.
- If the file doesn't exist, creating an empty file if fine. But always creating an empty file is bad in all other cases, as that would wiped the log.
- I don't care about the timestamps. Setting changed=true because of timestamps is a stupid behaviour in this case. That behaviour immediately causes the entire host to be marked as changed and could trigger further hooks! The host will never converge.

I believe that this is much closer to the state=file behaviour, except that the outcome isn't dependent on the prior existence (or not) of the path.

**Comment by jnojr** [comment]
I have to agree... state=present would be nice.  I'm using state=touch, but that always shows as "changed" in the output, when nothing useful has actually changed.  touching when not necessary isn't clean, and neither is stringing other commands together to wind up with the result you could (and should be able to) get from one.

Please do add this.

**Comment by holms** [comment]
@mpdehaan  I'd vote for that too =/ I mean your described method is a hack.

**Comment by assarbad** [comment]
Same here: +1 for the `state=present` proposal.

**Comment by nethernet** [comment]
\+ 1. I would love to see that option available 'out-of-the-box' rather than implementing 'ugly' hacks.

**Comment by deltaraven** [comment]
+1. I too am implementing @bencord0's hack.

**Comment by dave-kong** [comment]
+1 to state=present. ensuring the existence of some file is very much a common operation.

**Comment by jpbarbosa** [comment]
+1 to state=present (linked issue: https://github.com/ansible/ansible-modules-core/issues/170)

**Comment by jacobweber** [comment]
Any way to get this re-opened? This seems like a pretty common need, and using "copy" doesn't ensure that the mode/owner is set correctly.

**Comment by Petrox** [comment]
@mpdehaan:

Could you please tell me what is the current official solution (not hack), if someone wants
- a logfile to exist with zero or more bytes in it (starts with zero, but it should not be enforced / truncated)
- given ownership and rights (even with correct acl setting https://github.com/ansible/ansible-modules-core/issues/192)
- change only when the file ownership or rights needs to be changed, or create if missing (see: copy with force=no does not ensure correct owner)
- no touching (no changed state report) if no change needed to those rights or ownership and the file exists

This should be a oneliner I believe, but we've only got closed issues and no correct, full, official solution.

Thank you.

**Comment by jimi-c** [comment]
@Petrox, mpdehaan is no longer affiliated with the project. The official method is still state=touch. If you do not want the task to show up as changed use `changed_when: false` on the task as well.

I am going to go ahead and lock this thread. If anyone has any further questions, please direct them to the mailing list.

**Comment by samdoran** [comment]
This can be done in Ansible >= 2.7.0 by preserving both modification and access time:

```yaml
- file:
    path: /tmp/empty
    state: touch
    modification_time: preserve
    access_time: preserve
```
