### ISSUE TITLE
[rax_*] Deal with rate limits

### ISSUE THREAD

**Issue by smola** [ansible/ansible#7492]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.6
##### Environment:

N/A
##### Summary:

rax_\* should deal with rate limits.

I'm hitting rate limits on rax Cloud DNS API calls. That makes the whole playbook fail instead of retrying. It would be nice to have some throttling settings or respect the "Reply-After" response header and retry after the specified amount of time (or both).

Rate limits example:

http://docs.rackspace.com/cdns/api/v1.0/cdns-devguide/content/Rate_Limits-d1e1222.html
##### Steps To Reproduce:

Just go over rate limits playbook fails.
##### Expected Results:

When rate limit is found, it should retry after the amount of time specified by the API response. API calls might be throttled to mitigate the issue.
##### Actual Results:

Playbook fails. Example:

```
failed: [bran] => (item=bitsnbrains.com) => {"failed": true, "item": "bitsnbrains.com"}
msg: OverLimit Retry...
```

**Comment by smola** [comment]
Note that this can be mitigated by using `serial: 1` on the playbook.

**Comment by mpdehaan** [comment]
cc @sivel - any thoughts on this one?

I'm perhaps just suggesting a quick docs note and an acceptable serial: N suggestion.

**Comment by sivel** [comment]
@mpdehaan yes, it is our recommendation to use serial with rax_dns.  I will add notes to rax_dns and rax_dns_record and submit a pull request soon.

**Comment by mpdehaan** [comment]
Closing per sivel's docs change.

Thanks!
