### ISSUE TITLE
Add a new key, value using Ansible consul_kv

### ISSUE THREAD

**Issue by akimran82** [ansible/ansible#74934]
### Summary

I have a new key, value pair which I'd like to add to a remote consul. With the current setup, values are updated for an existing key. But new key, value pairs are not added. This is the setup I have :

`
- name: default values to consul
  include_vars:
    file: consul_values.yml
    name: default

- name: populate default values into consul
  consul_kv:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    recurse: true
    host: "{{ consul_url }}"
    port: "{{ consul_port }}"
    scheme: "{{ consul_scheme }}"
  with_dict: "{{ default }}"
`

### Issue Type

Feature Idea

### Component Name

consul

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mkrizek** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general.

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.libera.chat
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
