### ISSUE TITLE
Remote user specified in task does not override remote_user set in the play

### ISSUE THREAD

**Issue by thevman** [ansible/ansible#7493]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.7 (devel 10414145b2) last updated 2014/05/22 09:30:11 (GMT -400)

The issue also affects release1.6.1
##### Environment:

Running from Amazon Linux and trying to connect to Amazon Linx and Ubuntu12.04
##### Summary:

I'm writing my first playbook to send pings to all machines in my ecosystem. Some machines use the ec2-user and others use the ubuntu user. While I am using 'when' to check for the OS, I find that when I put in remote_user at the 'hosts' level, that's the one that always takes effect and the remote_user defined in task is irrelevant.
##### Steps To Reproduce:

Here's my playbook:

```
- hosts: all
  remote_user: ec2-user
  tasks:
    - name: test connection ec2 user
      ping:
      remote_user: ec2-user
      when: ansible_os_family == "Amazon"
    - name: test ubuntu connection
      ping:
      remote_user: ubuntu
      when: ansible_os_family == "Ubuntu"
```

Save the above as first_playbook.yml

Run the following command: 

```
ansible-playbook first_playbook.yml -f 10 -vvvv
```
##### Expected Results:

All servers should be contacted i.e. I should be getting: 

ESTABLISH CONNECTION FOR USER: _username_

for all users.
##### Actual Results:

I'm getting 'unreachable' for the ubuntu servers.

Analysis of the failures shows that ansible is still trying to connect using ec2-user for the ubuntu machines:

debug1: Control socket "/home/_some_user_/.ansible/cp/ansible-ssh-_ip_-ec2-user" does not exist

**Comment by jimi-c** [comment]
Thanks, I've updated the title a bit to reflect the issue you're describing.

**Comment by bcoca** [comment]
your problem occurs at fact gathering, the system does this before any
tasks unless you explicitly disable it.

1) disable fact gathering
2) create 2 setup tasks (fact gathering) one with each remote_user and
ignore_errors=true
3) now ping tasks should work
​

**Comment by thevman** [comment]
So I modified my playbook to look like this:

```
- hosts: all
  gather_facts: no
  tasks:
    - name: setup task for amazon machines
      setup:
      remote_user: ec2-user
      ignore_errors: True
    - name: setup task for ubuntu machines
      setup:
      remote_user: ubuntu
      ignore_errors: True
    - name: test connection ec2 user
      ping:
      remote_user: ec2-user
      when: ansible_distribution == "Amazon"
    - name: test ubuntu connection
      ping:
      remote_user: ubuntu
      when: ansible_distribution == "Ubuntu"
```

I'm using it against a simple hosts file which has two servers: One Ubuntu and one Amazon Linux. Here's the output I get:

```
$ ansible-playbook -i ~/myansiblehosts first_playbook.yml -f 10

PLAY [all] ********************************************************************

TASK: [setup task for amazon machines] ****************************************
fatal: [10.0.2.83] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue
ok: [10.0.2.17]

TASK: [setup task for ubuntu machines] ****************************************
fatal: [10.0.2.17] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/`user`/first_playbook.retry

10.0.2.17                  : ok=1    changed=0    unreachable=1    failed=0
10.0.2.83                  : ok=0    changed=0    unreachable=1    failed=0


```

**Comment by bcoca** [comment]
I think you misunderstand what is happening here.

ignore_errors applies to task errors, not connection errors, so the
machines are being taken out of the play due to connection errors at each
setup task that is incompatible, with out ever reaching the ping tasks. The
remote_user is correctly being overridden at task level but that means that
it will fail on the wrong machine target, taking it out of the remainder of
the play.

​

**Comment by bcoca** [comment]
the following will give you the results you expected:
- hosts: all
  gather_facts: yes
  remote_user: ec2-user
  tasks:
  - name: test connection ec2 user
    ping:
- hosts: all
  gather_facts: yes
  remote_user: ubuntu
  tasks:
  - name: test connection ubuntu user
    ping:​

I would change ping to a group_by: in each and you'll have what you need to
do things based on the success of each.

**Comment by thevman** [comment]
So I tried that...

Apparently, if it's in the same file, It still won't recognize the failed hosts for another play:

```
$ ansible-playbook -i ~/myansiblehosts first_playbook.yml -f 10

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
fatal: [10.0.2.83] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue
ok: [10.0.2.17]

TASK: [test connection ec2 user] **********************************************
ok: [10.0.2.17]

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
fatal: [10.0.2.17] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue

TASK: [test connection ubuntu user] *******************************************
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/<user>/first_playbook.retry

10.0.2.17                  : ok=2    changed=0    unreachable=1    failed=0
10.0.2.83                  : ok=0    changed=0    unreachable=1    failed=0

```

Am I missing something here?

**Comment by bcoca** [comment]
No, I did not realize that it kept the memory across plays. All plays in
the same invocation should have this issue (even if in diff files) as they
get compiled into the same playbook object each run.​

**Comment by thevman** [comment]
so where does that leave us? is this an ansible issue or of my being a noob?

**Comment by bcoca** [comment]
Well ... its how ansible works, what you are doing is not the norm​, but I
see how some people would need this to work.

Most of us use the groups/inventory source to setup the remote_user and
don't do 'discovery'. But this might be something we want working. Maybe a
switch to not exclude hosts for whole run, just for current play?

**Comment by thevman** [comment]
So is there a variable I can use to not exclude hosts when they fail?
Vineet

**Comment by bcoca** [comment]
not yet, I was musing about adding one, not sure if it makes sense as this seems to be a rare corner case.

**Comment by thevman** [comment]
How do other users solve this problem? Surely having multiple OS-es in an environment can't be that uncommon. Do people use mutiple playbooks? One per OS ? But if what you said in a previous post is true then it won't work even in different files.
We're using a python script to generate our hosts file. In an amazon auto-scaling environment with constantly changing ips, that was the best way to keep our hosts file current.

I'm open to an alternate architecture which follows standards.

Vineet

**Comment by bcoca** [comment]
so I would suggest this :

```
- hosts: all
  remote_user: ec2-user
  tasks:
    - name: make those that work part of ec2 group
      group_by: key=ec2

- hosts: all
  remote_user: ubuntu
  tasks:
    - name: group by ubuntu user
      group_by: key=ubuntu

- hosts: ubuntu
   remote_user: ubuntu # or can be set in group_vars/ubuntu
   .....

- hosts: ec2
   remote_user: ec2
   .....

```

The first 2 plays will create the groups as gather_facts will fail for the servers the user does not work for, after that you can use the groups to set the remote_user on subsequent plays.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
