### ISSUE TITLE
Accelerated mode fails while gathering facts (can't reproduce?)

### ISSUE THREAD

**Issue by marceldegraaf** [ansible/ansible#7494]
##### Issue Type:

Bug Report (possibly related to #6190)
##### Ansible Version:

`ansible-playbook 1.6.1`
##### Environment:

OS/X Mavericks
##### Summary:

Accelerated mode fails with an error while gathering facts, saying that `python-keyczar` is required on the control machine: `python-keyczar must be installed on the control machine to use accelerated modes`

However, `python-keyczar` has been installed (from [this page](https://code.google.com/p/keyczar/downloads/detail?name=keyczar-python-0.71d-09062013.tar.gz&can=2&q=), with `python setup.py install`) and seems to be working; `python -E -c 'from keyczar.keys import AesKey'` does not error on both the control machine and the remote host.
##### Steps To Reproduce:
1. Create a playbook with at least one play that has `accelerated: true`. Make sure to disable `requiretty` in your remote host's sudo configuration.
2. Run your playbook with `ansible-playbook`
3. Observe the error in your console: `fatal: [example.com] => python-keyczar must be installed on the control machine to use accelerated modes`
##### Expected Results:

The playbook executes with accelerated mode enabled.
##### Actual Results:

See _Steps to reproduce_

**Comment by jimi-c** [comment]
What is the OS of the managed host, along with the versions of pycrypto and keyczar installed there?

**Comment by marceldegraaf** [comment]
The remote host is Ubuntu 13.10. Python module versions:

```
pycrypto==2.6
python-keyczar==0.6b
```

**Comment by mpdehaan** [comment]
Would you be running that side in a virtualenv or using a different python interpreter?

(is ansible_python_interpreter set to anything?)

**Comment by mpdehaan** [comment]
This is probably still in "post a question to ansible-project and try to debug it" territory seeing we haven't gotten many complaints about accelerated mode.

Still curious and could use more background info if you could supply it.

**Comment by marceldegraaf** [comment]
Nope, as far as I know I'm just using the standard Python interpreter that came with Ubuntu. I would love to provide more background info, but I'm not sure what would be useful. Can you let me know what you need?

**Comment by marceldegraaf** [comment]
@mpdehaan can you let me know what info you need? It would be nice if we could get accelerated mode working here, because currently a deploy with Ansible is quite slow.

**Comment by jimi-c** [comment]
@marceldegraaf what is the output of `python --version`, and if you open a python shell with that default version and run `import Crypto` and `import keyczar` you don't get any errors?

<pre>
root@ubuntu1310:~# python
Python 2.7.5+ (default, Sep 19 2013, 13:48:49) 
[GCC 4.8.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyczar
>>> import Crypto
>>> 
</pre>

**Comment by marceldegraaf** [comment]
@jimi-c thanks for your reply, I'll get back to you in the coming week.

**Comment by mpdehaan** [comment]
Hi,

I'm closing this one as we haven't seen any activity in some time.

If you have continued problems with this one on a recent version of Ansible (i.e. 1.7), please feel free to open a new ticket.   Thank you!
