### ISSUE TITLE
'when' not working with 'with_items'

### ISSUE THREAD

**Issue by eviekassela** [ansible/ansible#7497]
##### Issue Type:

“Bug Report”
##### Ansible Version:

1.6
##### Environment:

Ubuntu 13.10
##### Summary:

'when' doesn't seem to work when used together with 'with_items'.
##### Steps To Reproduce:

I have this task in a play for group 'dbservers':

name: test
debug: msg='{{ is_master }}'
sudo: true
sudo_user: postgres
when: is_master
with_items: groups['dbservers'][1::]

I wrote this because I wanted only master ( which is groups['dbservers'][0] with hostname 'pgserver-1' ) to show the message for every slave. 
##### Expected Results:

TASK: [database | test] ******************************************************\* 
<....> ESTABLISH CONNECTION FOR USER: root
<....> ESTABLISH CONNECTION FOR USER: root
skipping: [pgserver-2] => (item=pgserver-2)
ok: [pgserver-1] => (item=pgserver-2) => {
    "item": "pgserver-2", 
    "msg": "True"
}
##### Actual Results:

With 1 master and 1 slave it doesn't work:

TASK: [database | test] ******************************************************\* 
<....> ESTABLISH CONNECTION FOR USER: root
<....> ESTABLISH CONNECTION FOR USER: root
ok: [pgserver-2] => (item=pgserver-2) => {
    "item": "pgserver-2", 
    "msg": "False"
}
ok: [pgserver-1] => (item=pgserver-2) => {
    "item": "pgserver-2", 
    "msg": "True"
}

The first message shouldn't be shown but be skipped. It's like something isn't working with 'when' but is_master is correctly evaluated.

**Comment by mpdehaan** [comment]
when works with_items fine.

"with_items: groups['dbservers'][1::]"

This isn't valid syntax.

Please stop by ansible-project for help type questions.

Thanks!

**Comment by eviekassela** [comment]
I posted it here because i don't think that syntax is the problem. I have used when and with_items successfully in other tasks with different conditions and loops. 
But i also tried it with this: " with_items: ['pgserver-2'] " and get the same output. Is this invalid syntax too? 'When' seems to be the problem as if it doesn't recognise 'True'.
