### ISSUE TITLE
`synchronize` module: Trailing slash in `src` does not have the same effect as with rsync

### ISSUE THREAD

**Issue by tamakisquare** [ansible/ansible#7502]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.1 
##### Environment:

Mac OS X 1.7.5 (Lion) 
##### Summary:

What I want to achieve is to sync the contents of a directory on the control machine, `src=src_dir/`, to the target directory on the remote host, `dest=/dest_dir/`. To achieve this with _rsync_, the slash at the end of `src=src_dir/` is a must. Without the trailing slash, a new folder named `src_dir` will be created in the `dest` directory.

Since the **synchronize** module claims to be a wrapper around rsync, so I assume it would behave the same as mentioned above. With or without the trailing slash for `src`, however, a new directory named as the `src` always gets created in the `dest` directory.

I am not sure if what I have observed should be classified as a bug or a behaviour intended as designed for the synchronize module. I shall leave this decision to the community.
##### Steps To Reproduce:

```
- name: Sync foo/ to the remote
  synchronize: >
    src=foo/
    dest=/target_dir/
```
##### Expected Results:

The contents of the `foo/` directory are completely synced to the `/target_dir/` directory on the remote host.  
##### Actual Results:

A new directory named `foo/` is created in the `/target_dir/` directory on the remote host.

**Comment by jimi-c** [comment]
This has been resolved in issue https://github.com/ansible/ansible/issues/7296 and will be included in 1.6.2. Thanks!
