### ISSUE TITLE
bug with su command with ask_su_pass

### ISSUE THREAD

**Issue by schors** [ansible/ansible#7503]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.1
##### Environment:

FreeBSD 9.2-RELEASE amd64
FreeBSD 10.0-RELEASE amd64
##### Summary:

FreeBSD su prompt ends with a colon and not a whitespace. Ansible option "-S" on FreeBSD does not work ever.
lib/ansible/utils/init.py line 955
prompt = 'assword: ' with whitespace....
##### Steps To Reproduce:

Command:
ansible any_frebsd_host -m setup -S --ask-su-pass
freezes and falls off on timeout
##### Expected Results:

Conclusion facts
##### Actual Results:

I can not wait for timeout

**Comment by jimi-c** [comment]
Hi, could you please fill out the template as requested, and be sure to include a sample playbook that reproduces the error on your system? Thanks!

**Comment by mpdehaan** [comment]
See above for a related ticket regarding su that may wish to be worked in concert.
