### ISSUE TITLE
auto scaling policy failing due to object error

### ISSUE THREAD

**Issue by LuisFelipeSiqueira** [ansible/ansible#7506]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.1
##### Environment:

OSX Mavericks managing Ubuntu Precise nodes from Amazon EC2.  Issue is reproducible from Ubuntu controller as well.
##### Summary:

With this security policy declaration

  0 - name: Define webscaling_policy (on)
  1   local_action:
  2     module: ec2_scaling_policy
  3     name: web-frontend-policy
  4     asg_name: web-frontend
  5     state: present
  6   tags:
  7     - allon
  8     - scaling_on

I am failing with this error

TASK: [scaling | Define webscaling_policy (on)] ******************************\* 
failed: [localhost] => {"failed": true, "item": "", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/luis/.ansible/tmp/ansible-tmp-1400800399.51-71773184177311/ec2_scaling_policy", line 1533, in <module>
    main()
  File "/Users/luis/.ansible/tmp/ansible-tmp-1400800399.51-71773184177311/ec2_scaling_policy", line 1528, in main
    create_scaling_policy(connection, module)
  File "/Users/luis/.ansible/tmp/ansible-tmp-1400800399.51-71773184177311/ec2_scaling_policy", line 1440, in create_scaling_policy
    scalingPolicies = connection.get_all_policies(as_group=asg_name,policy_names=[sp_name])
AttributeError: 'NoneType' object has no attribute 'get_all_policies'
##### Steps To Reproduce:

Run the above playbook and try to establish  web scaling policy
##### Expected Results:

Expected results are the scaling policy or group to be created.
##### Actual Results:

TASK: [scaling | Define webscaling_policy (on)] ******************************\* 
failed: [localhost] => {"failed": true, "item": "", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/luis/.ansible/tmp/ansible-tmp-1400800399.51-71773184177311/ec2_scaling_policy", line 1533, in <module>
    main()
  File "/Users/luis/.ansible/tmp/ansible-tmp-1400800399.51-71773184177311/ec2_scaling_policy", line 1528, in main
    create_scaling_policy(connection, module)
  File "/Users/luis/.ansible/tmp/ansible-tmp-1400800399.51-71773184177311/ec2_scaling_policy", line 1440, in create_scaling_policy
    scalingPolicies = connection.get_all_policies(as_group=asg_name,policy_names=[sp_name])
AttributeError: 'NoneType' object has no attribute 'get_all_policies'

**Comment by mpdehaan** [comment]
This seems like a case where you'll need to update your boto.

I agree that we should add a version check to the module or catch this AttributeError and raise an error about the boto version.

**Comment by LuisFelipeSiqueira** [comment]
Hello Michael,

Thank you for answering.  

Lou:infrastructure luis$ pip freeze|grep boto
boto==2.28.0
Lou:infrastructure luis$ ansible --version
ansible 1.6.1
Lou:infrastructure luis$ 

My boto library is up to date, is there a specific known working version?

Regards,
Luis

On May 23, 2014, at 05:54 AM, Michael DeHaan notifications@github.com wrote:

This seems like a case where you'll need to update your boto.
I agree that we should add a version check to the module or catch this AttributeError and raise an error about the boto version.

**Comment by LuisFelipeSiqueira** [comment]
Hello,

I'm still failing with everything up to date.  legit bug?

Lou:infrastructure luis$ pip freeze|grep boto boto==2.28.0 Lou:infrastructure luis$ ansible --version ansible 1.6.1 Lou:infrastructure luis$

**Comment by jimi-c** [comment]
This was failing due to the fact that there is no region specified. I have merged in the above patch to catch this failed connection condition going forward, however there does also appear to be a documentation issue, where that modules docs are not pulling in the commong AWS documentation bits (which includes the documentation field for region there). I'll get that fixed separately. 

Thanks!
