### ISSUE TITLE
Issue with delegate_to combined with with_items

### ISSUE THREAD

**Issue by therigu** [ansible/ansible#7510]
On devel, a task like:

```
- debug: msg=test
  delegate_to: '{{ item }}'
  with_items: groups.admin
```

gives

```
<> ESTABLISH CONNECTION FOR USER: ubuntu
<> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/ubuntu/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', u'', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1400837443.04-113553911105689 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1400837443.04-113553911105689 && echo $HOME/.ansible/tmp/ansible-tmp-1400837443.04-113553911105689'"]
fatal: [qa-c-2] => SSH encountered an unknown error. The output was:
OpenSSH_5.9p1 Debian-5ubuntu1.4, OpenSSL 1.0.1 14 Mar 2012
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket "/home/ubuntu/.ansible/cp/ansible-ssh--22-ubuntu" does not exist
debug2: ssh_connect: needpriv 0
ssh: Could not resolve hostname : Name or service not known
```

It looks like the {{ item }} is expanded to the empty string.

A git bisect suggests 2e2e5d53 is to blame.

**Comment by mpdehaan** [comment]
Thanks! please comment on the ticket rather than on commits in the future -- makes things easier to find.   I agree we should add a test for this one.

**Comment by therigu** [comment]
Sorry, not sure what you mean - is there a related ticket already?

I investigated a little more. `self.module_vars` contains `item: ''` and hence `module_vars` ends up with `delegate_to: ''`.  A quick fix that worked for all cases in my playbook was:

```
diff --git a/lib/ansible/runner/__init__.py b/lib/ansible/runner/__init__.py
index adc9b7b..a171e26 100644
--- a/lib/ansible/runner/__init__.py
+++ b/lib/ansible/runner/__init__.py
@@ -580,7 +580,13 @@ class Runner(object):
         # we update the inject variables with the data we're about to template
         # since some of the variables we'll be replacing may be contained there too
         module_vars_inject = utils.combine_vars(combined_cache.get(host, {}), host_variables)
-        module_vars_inject.update(self.module_vars)
+
+        module_vars_with_item = self.module_vars.copy()
+
+        if 'item' in module_vars_with_item:
+            del module_vars_with_item['item']
+
+        module_vars_inject.update(module_vars_with_item)
         module_vars = template.template(self.basedir, self.module_vars, module_vars_inject)

         inject = {}
```

**Comment by jimi-c** [comment]
@therigu could you send us that in a PR so you get proper attribution? Thanks!

**Comment by jimi-c** [comment]
An alternative way to fix this would be to copy the module_vars as you do and update that with the inject, which should also prevent this issue.

**Comment by jimi-c** [comment]
Here's what I'm talking about, I believe this patch should also resolve the issue:

<pre>
diff --git a/lib/ansible/runner/__init__.py b/lib/ansible/runner/__init__.py
index adc9b7b..9526ecb 100644
--- a/lib/ansible/runner/__init__.py
+++ b/lib/ansible/runner/__init__.py
@@ -580,7 +580,7 @@ class Runner(object):
         # we update the inject variables with the data we're about to template
         # since some of the variables we'll be replacing may be contained there too
         module_vars_inject = utils.combine_vars(combined_cache.get(host, {}), host_variables)
-        module_vars_inject.update(self.module_vars)
+        module_vars_inject = utils.combine_vars(self.module_vars, module_vars_inject)
         module_vars = template.template(self.basedir, self.module_vars, module_vars_inject)
 
         inject = {}
</pre>

**Comment by jimi-c** [comment]
I've gone ahead and merged in my fix above, which should resolve this issue. If you continue having problems related to this, please let us know. Thanks!

**Comment by fuzzy-id** [comment]
The merge does not seem to have fixed the issue see  https://github.com/ansible/ansible/issues/7535
