### ISSUE TITLE
Allow mysql_db dump command to use --single-transaction option

### ISSUE THREAD

**Issue by jaikdean** [ansible/ansible#7512]
When running a MySQL dump, tables are locked by default. If dumping a large table, this means any other queries on this table will be queued up, making it unsuitable for backing up live databases.

There is an option [--single-transaction](http://dev.mysql.com/doc/refman/5.6/en/mysqldump.html#option_mysqldump_single-transaction) which will perform a non-locking dump when working with InnoDB (the default storage engine) tables.

It would be useful to be able to specify this option.

**Comment by mpdehaan** [comment]
That sounds great, how about submitting a pull request? 

Thanks!

**Comment by razvanphp** [comment]
So what happened to this issue? Why was it closed?

I just tried dump with ansible 2.0 and it seems he's trying to lock the tables, something I don't want. How can we change this?

**Comment by joshtrichards** [comment]
@razvanphp It appears that single_transaction was added in Ansible 2.1 - http://docs.ansible.com/ansible/mysql_db_module.html
