### ISSUE TITLE
`ansible.parsing.yaml.loader.AnsibleLoader` behaves inconsistently on different platforms

### ISSUE THREAD

**Issue by andras-kth** [ansible/ansible#75212]
### Summary

Depending on the availability of `CParser` (essentially `libyaml`), `AnsibleLoader` behaves differently, since the C and Python implementations are **NOT** equivalent.  This creates portability issues for playbooks and tasks, since what works on one platform may not work on another.  _One possible fix is to prefer correctness over speed and always use the Python implementation._

I created a [repo](https://github.com/mehes-kth/ansible-yaml-loader-issue) with an example that shows how `CParser` displays different behavior for two theoretically equivalent tasks that only differ in _how_ the contents of a field are specified: either as an easy-to-read "literal" block or as a hard-to-read quoted string.

On most Linux hosts, `libyaml` is available and the -apparently faulty- `CParser` implementation will be used, which forces the use of the less readable version for portability.

BTW: This "form" for filing bug reports is overly restrictive and will produce odd results.
BTW#2: There is NO "prompt line" in some of the entry fields where the instruction are referring to one.

### Issue Type

Bug Report

### Component Name

ansible.parsing.yaml.loader.AnsibleLoader

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.2]
  config file = None
  configured module search path = ['$HOME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = $HOME/ansible-yaml-loader-issue/with{,out}-libyaml/lib/python3.8/site-packages/ansible
  ansible collection location = $HOME/.ansible/collections:/usr/share/ansible/collections
  executable location = $HOME/ansible-yaml-loader-issue/with{,out}-libyaml/bin/ansible
  python version = 3.8.11 (default, Jun 28 2021, 19:02:52) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 3.0.1
  libyaml = VARIES (that's the whole point)
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Largely irrelevant.  The presence of `libyaml` will break certain playbooks/tasks on any OS.

I'm doing my testing on an M1 MacBook Air with the following setup:
```console
user@host:~/ansible-yaml-loader-issue$ uname -v
Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101
user@host:~/ansible-yaml-loader-issue$
```

### Steps to Reproduce

The following script will set up two virtual environments **with** and **without** `libyaml` and run a simple test in each trying to apply both the _easy-to-read_ and the _hard-to-read_ versions of essentially the same task.
```
$ git clone git@github.com:mehes-kth/ansible-yaml-loader-issue.git
$ ./ansible-yaml-loader-issue/run.me
```
If your existing environment includes `libyaml`, a faster way to demonstrate the same is to run
```
$ ./ansible-yaml-loader-issue/loader.py ./ansible-yaml-loader-issue/roles/*/tasks/main.yaml
```

### Expected Results

Both the C and Python implementations produce the same output for both tasks.

### Actual Results

```console
The C implementation fails on the literal block with an incorrect error,
but works with the quoted string.

The Python implementation handles both versions correctly.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by bcoca** [comment]
FYI, given the choice i would disable the python parser fallback and make the C parser a hard requirement.

**Comment by mehes-kth** [comment]
> FYI, given the choice i would disable the python parser fallback and make the C parser a hard requirement.

Interesting; especially, considering that 
1.  the C implementation is not available on all platforms
    (I'm running on an M1 MacBook Air, where the default installation does *not* appear to include `libyam`); 
2.  the C implementation produces incorrect results.

> I would also open an issue here https://github.com/yaml/libyaml/issues/

Please do!

**Comment by sivel** [comment]
> Please do!

We don't intend on doing so.  If you were so inclined to resolve this issue, you may wish to do so.

On another note, I honestly don't believe we are going to change anything here.  Not using the C implementation isn't going to happen, and I strongly doubt we'll disable a fallback to the Python implementation.

I'd recommend adding some CI based linting step that requires the C extension and validates all files can be properly parsed if this is a concern.

**Comment by mehes-kth** [comment]
> > Please do!
> 
> We don't intend on doing so.  If you were so inclined to resolve this issue, you may wish to do so.

Considering that it's your "product"/project that includes a broken component, that has a working fallback,
which you don't intend to use, I'd sort of expect that you'd want to do something about it, but I can certainly
file a bug report for you, if that helps.

> On another note, I honestly don't believe we are going to change anything here. Not using the C implementation isn't going to happen, and I strongly doubt we'll disable a fallback to the Python implementation.

That's fine.  I would've expected you to want to resolve the breakage with `libyaml`, but hey...


> I'd recommend adding some CI based linting step that requires the C extension and validates all files can be properly parsed if this is a concern.

Since it's the C extension that doesn't work properly, that suggestion isn't exactly meaningful.
On the other hand, forcibly deleting `$LIBDIR/python*/site-packages/yaml/_yaml*.{so,dll}` might help.

**Comment by nitzmahone** [comment]
Closing the Ansible issue, since ultimately this is a packaging issue for pyyaml and Python wheels on some platforms.
