### ISSUE TITLE
EC2 Example to terminate an instance fails

### ISSUE THREAD

**Issue by jmoretti** [ansible/ansible#7525]
##### Summary:

Working with the example listed on the EC2 module page to create an EC2 instance, register the result as a variable, and then use the variable's instance_ids list to terminate the instances is failing for the reason that is documented in #4197.
##### Steps To Reproduce:

``` python
# Launch instances, runs some tasks
# and then terminate them

- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: "ansibletest"
    instance_type: m1.small
    security_group: "test"
    image: "ami-b08b6cd8"
    region: us-east-1
  tasks:
    - name: Launch instance
      local_action: ec2 key_name={{ keypair }} group={{ security_group }} instance_type={{ instance_type }} image={{ image }} wait=true region={{ region }}
      register: ec2
    - name: Add new instance to host group
      local_action: add_host hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.instances
    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances


- name: Terminate instances
  hosts: localhost
  gather_facts: False
  vars:
    region: us-east-1
  tasks:
      - name: Terminate instances that were previously launched
        local_action: ec2 state='absent' instance_ids='{{ ec2.instance_ids }}' region={{ region }}
```
##### Actual Results:

```
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidInstanceID.Malformed</Code><Message>Invalid id: "[ui-34048367]"</Message></Error></Errors><RequestID>cdec6640-fac9-4d3c-aecb-ab56bfb18b92</RequestID></Response>
```

**Comment by mpdehaan** [comment]
Note:  this is not related to the linked ticket, here though, it does seem there should be a join on a "," or it should use complex args

The linked ticket misunderstood ways arguments could be passed.

**Comment by jmoretti** [comment]
@mpdehaan Thank you for sharing Ansible!  I attempted to find the root cause of this issue, but I don't have much Python experience, and I am not fully versed in Ansible's structure.  Figuring this was a unicode conversion issue, I tracked the problem to the same block of code referenced in the linked ticket (from lib/ansible/module_common.py):

``` Python
   def _load_params(self):
       ''' read the input and return a dictionary and the arguments string '''
       args = MODULE_ARGS
       sys.stderr.write("**JM** args : %r" % (args))
       items   = shlex.split(args)
       sys.stderr.write("**JM** items : %r" % (items))
       params = {}
       for x in items:
           try:
               (k, v) = x.split("=",1)
           except Exception, e:
               self.fail_json(msg="this module requires key=value arguments (%s)" % (items))
           params[k] = v
       params2 = json.loads(MODULE_COMPLEX_ARGS)
       params2.update(params)
       return (params2, args)
```

The stderr output is:

``` Python
**JM** args : instance_ids=[u'i-f17fe4a1'] region=us-east-1 state='absent'
**JM** items : ['instance_ids=[ui-f17fe4a1]', 'region=us-east-1', 'state=absent’]
```

It seems to me that shlex is the culprit here, but I wouldn't begin to claim to know the Pythonic way or the overall best location in the Ansible code to address the issue.

**Comment by jimi-c** [comment]
I believe the instance_ids need to be passed in via complex args above, since they are an array and the standard key=value argument method you are using.

To use the key=value method, you must pass the ids through the jinja2 `join` filter:

<pre>
  tasks:
      - name: Terminate instances that were previously launched
        local_action: ec2 state='absent' instance_ids='{{ ec2.instance_ids|join(",") }}' region={{ region }}</pre>

This will turn the argument into `instance_ids=id1,id2,id3`, and the parameter parsing in the module will know to turn it back into a list based on the fact that it is set to `type='list'`. 

If you have any further questions, please let us know. Thanks!
