### ISSUE TITLE
Error "Failed to connect to the host via ssh: PLEASE HELP 

### ISSUE THREAD

**Issue by gRach1997** [ansible/ansible#75328]
### Summary

Good afternoon, colleagues. I'm trying to run the software version check playbook on the switch. But when I try to connect via ssh, I get the error "Failed to connect to the host via ssh:
sh-4.4# ansible-playbook show_version.yml

PLAY [Showversion] *******************************************************************************************

TASK [Showversion] *******************************************************************************************
fatal: [10.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: \r\n***************************************************************\r\nLANTRACE\r\nWARNING - MONITORED ACTIONS AND ACCESSES \r\nDATANET\r\n\r\n\r\nStation's information:\r\nZavokzalna_7a_str_p.2_Boryspil\r\n\r\n - \r\nFloor / Row / Rack / Sub-Rack\r\n / / / \r\nDC power supply:\r\nPower Source A: Floor / Row / Rack / Electrical circuit\r\n / / / \r\n\r\n\r\nNumber of LP: \r\nPosition MUX: \r\nIP LAN: \r\nNote: \r\n***************************************************************\r\nShared connection to 10.0.0.1 closed.", "unreachable": true}

PLAY RECAP ***************************************************************************************************
10.0.0.1 : ok=0 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0

When executing a playbook with the -vvv switch, I get the following result:
sh-4.4# ansible-playbook show_version.yml -vvv
ansible-playbook 2.9.18
config file = /etc/ansible/ansible.cfg
configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.6/site-packages/ansible
executable location = /usr/bin/ansible-playbook
python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
Skipping callback 'actionable', as we already have a stdout callback.
Skipping callback 'counter_enabled', as we already have a stdout callback.
Skipping callback 'debug', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'full_skip', as we already have a stdout callback.
Skipping callback 'json', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'null', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Skipping callback 'selective', as we already have a stdout callback.
Skipping callback 'skippy', as we already have a stdout callback.
Skipping callback 'stderr', as we already have a stdout callback.
Skipping callback 'unixy', as we already have a stdout callback.
Skipping callback 'yaml', as we already have a stdout callback.

PLAYBOOK: show_version.yml ***********************************************************************************
1 plays in show_version.yml

PLAY [Showversion] *******************************************************************************************
META: ran handlers

TASK [Showversion] *******************************************************************************************
task path: /var/lib/awx/projects/show_version/show_version.yml:8
<10.0.0.1> ESTABLISH SSH CONNECTION FOR USER: asoxx
<10.0.0.1> SSH: EXEC sshpass -d9 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="asoxx"' -o ConnectTimeout=10 -o ControlPath=/var/lib/awx/.ansible/cp/a075732807 -tt 10.0.0.1 'show version'
<10.0.0.1> (255, b'', b"\r\n***************************************************************\r\nLANTRACE\r\nWARNING - MONITORED ACTIONS AND ACCESSES \r\nDATANET\r\n\r\n\r\nStation's information:\r\nZavokzalna_7a_str_p.2_Boryspil\r\n\r\n - \r\nFloor / Row / Rack / Sub-Rack\r\n / / / \r\nDC power supply:\r\nPower Source A: Floor / Row / Rack / Electrical circuit\r\n / / / \r\n\r\n\r\nNumber of LP: \r\nPosition MUX: \r\nIP LAN: \r\nNote: \r\n***************************************************************\r\nShared connection to 10.0.0.1 closed.\r\n")
fatal: [10.0.0.1]: UNREACHABLE! => {
"changed": false,
"msg": "Failed to connect to the host via ssh: \r\n***************************************************************\r\nLANTRACE\r\nWARNING - MONITORED ACTIONS AND ACCESSES \r\nDATANET\r\n\r\n\r\nStation's information:\r\nZavokzalna_7a_str_p.2_Boryspil\r\n\r\n - \r\nFloor / Row / Rack / Sub-Rack\r\n / / / \r\nDC power supply:\r\nPower Source A: Floor / Row / Rack / Electrical circuit\r\n / / / \r\n\r\n\r\nNumber of LP: \r\nPosition MUX: \r\nIP LAN: \r\nNote: \r\n***************************************************************\r\nShared connection to 10.0.0.1 closed.",
"unreachable": true
}

PLAY RECAP ***************************************************************************************************
10.0.0.1 : ok=0 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0

### Issue Type

Bug Report

### Component Name

show version on switch

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.2] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

### OS / Environment

Ubuntu 20

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

I expected the output to be like this:
sh-4.4# ansible-playbook show_version.yml

PLAY [Showversion] *******************************************************************************************

TASK [Showversion] *******************************************************************************************
sw0-ap#show version
Unit 1
Serial Number: 406000938
Hardware Version: R01
Chip Device ID: Marvell 98DX106-B0, 88E6095[F]
EPLD Version: 0.07
Number of Ports: 28
Main Power Status: Up
Redundant Power Status: Not present

Agent (Master)
Unit ID: 1
Loader Version: 1.0.4.1
Boot ROM Version: 1.2.1.3
Operation Code Version: 1.4.20.32

PLAY RECAP ***************************************************************************************************
10.254.18.27 : ok=0 changed=0 unreachable=0 failed=0 skipped=0 rescued=0 ignored=0

### Actual Results

```console
sh-4.4# ansible-playbook show_version.yml

PLAY [Showversion] *******************************************************************************************

TASK [Showversion] *******************************************************************************************
fatal: [10.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: \r\n***************************************************************\r\nLANTRACE\r\nWARNING - MONITORED ACTIONS AND ACCESSES \r\nDATANET\r\n\r\n\r\nStation's information:\r\nZavokzalna_7a_str_p.2_Boryspil\r\n\r\n - \r\nFloor / Row / Rack / Sub-Rack\r\n / / / \r\nDC power supply:\r\nPower Source A: Floor / Row / Rack / Electrical circuit\r\n / / / \r\n\r\n\r\nNumber of LP: \r\nPosition MUX: \r\nIP LAN: \r\nNote: \r\n***************************************************************\r\nShared connection to 10.0.0.1 closed.", "unreachable": true}

PLAY RECAP ***************************************************************************************************
10.0.0.1 : ok=0 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by Akasurde** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs, and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
