### ISSUE TITLE
No facts gathered on templated hosts

### ISSUE THREAD

**Issue by karasjoh000** [ansible/ansible#75330]
### Summary

When running: 
```yaml 
- hosts: "k8s_bootstrap_control,{{ groups['mons'][0] }}"
  become: true
  roles: 
    - role: rook
  tags: ["rook"]
```
No facts get gathered on `{{ groups['mons'][0] }}` and need to do a separate `setup` call. 

### Issue Type

Bug Report

### Component Name

facts

### Ansible Version

```console
$ ansible --version
 
ansible 2.9.6
  config file = /home/john/Projects/common-infra/ansible.cfg
  configured module search path = ['/home/john/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

### Configuration

```console
$ ansible-config dump --only-changed

DEFAULT_FORKS(<PATH>/ansible.cfg) = 50
DEFAULT_TIMEOUT(<PATH>/ansible.cfg) = 1200
```
```bash


### OS / Environment

NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Steps to Reproduce

```yaml 
- hosts: "k8s_bootstrap_control,{{ groups['mons'][0] }}"
  become: true
  roles: 
    - role: rook
  tags: ["rook"]
```

### Expected Results

facts gathered for `{{ groups['mons'][0] }}` not just `k8s_bootstrap_control` 

### Actual Results

```console
TASK [rook : debug] ********************************************************************************************************************************************************************************************************************************************************************
skipping: [ceph01]
fatal: [control_01]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_default_ipv4'\n\nThe error appears to be in '<PATH>/main.yml': line 77, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: debug\n  ^ here\n"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
We have tested and templated or not is irrelevant for fact gathering, lacking detail this seems like a mismatch of expectations between hosts for which you gathered facts and those from which you read facts.

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by karasjoh000** [comment]
@bcoca this is not a bug and expected behavior?
