### ISSUE TITLE
Fix apt parameter documentation

### ISSUE THREAD

**Issue by time-palominodb** [ansible/ansible#754]
time_palominodb: The documentation (http://ansible.github.com/modules.html) again leaving me confused. For module "apt" parameter "purge" it mentions setting (parameter?) "state" to removed. But parameter "state" appears to only take absent|present|latest? I think that means the "state" parameter is missing some info, but maybe the "purge" parameter is mis-stating something.

mdehaan: eh, removed==absent ;; I was trying to standardize the aliases/docs and missed something

I might recommend the following verbiage:

'purge=yes' will purge configuration files if module paramater 'state=removed’.

**Comment by time-palominodb** [comment]
Duh - I mean verbiage:
'purge=yes' will purge configuration files if module paramater 'state=absent’.

**Comment by mpdehaan** [comment]
BTW, docs project is over at https://github.com/ansible/ansible.github.com for future reference in filing docs bugs

**Comment by mpdehaan** [comment]
the answer is that absent is standard nomenclature, and removed should not be in the docs, and is an old alias we keep around

**Comment by mpdehaan** [comment]
docs pushed
