### ISSUE TITLE
include_tasks serach path behaviour when interpolating filename

### ISSUE THREAD

**Issue by ticktockhouse** [ansible/ansible#75412]
### Summary

When trying to use a file in a role with `include_tasks` where the name of the file is interpolated, ansible doesn't find the file under `my-role/tasks/<interpolated file name`.yml as expected

### Issue Type

Bug Report

### Component Name

ansible.builtin.include_tasks

### Ansible Version

```console
ansible --version
ansible [core 2.11.2] 
  config file = /path/to/ansible/ansible.cfg
  configured module search path = ['/home/jerry/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jerry/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/jerry/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/jerry/.local/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
CACHE_PLUGIN(/path/to/ansible/ansible.cfg) = memory
DEFAULT_BECOME(/path/to/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/path/to/ansible/ansible.cfg) = ['/path/to/ansible/inventories']
DEFAULT_LOAD_CALLBACK_PLUGINS(/path/to/ansible/ansible.cfg) = True
DEFAULT_ROLES_PATH(/path/to/ansible/ansible.cfg) = ['/home/jerry/free-code/ansible/roles', '/path/to/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/path/to/ansible/ansible.cfg) = yaml
```

### OS / Environment

Target Host: CentOS7
Ansible Controller: Ubuntu 20.04

### Steps to Reproduce

I am using `include_tasks` in a role to include tasks under the `tasks` directory, e.g.:
`tasks/main.yml`:
```
- include_tasks: blah.yml
- include_tasks: apache-{{ ansible_os_family }}.yml
```
Directory listing of `tasks/`:
```
tasks/
├── apache-Redhat.yml
├── blah.yml
└── main.yml
```

Ansible finds the first task file within the role's directory structure as expected, but not the second one, instead it appears to search for the file at the path where the top-level playbook (which calls the role) is located:
```
TASK [my-role : Include blah] **********************************************
task path: /path/to/ansible/roles/my-role/tasks/main.yml:8
included: /path/to/ansible/roles/my-role/tasks/blah.yml for my-host

TASK [my-role : debug] *****************************************************
task path: /path/to/ansible/roles/my-role/tasks/blah.yml:1
ok: [my-host] => 
  msg: I am blah

TASK [my-role : Include apache modifications] ******************************
task path: /path/to/ansible/roles/my-role/tasks/main.yml:11
fatal: [my-host]: FAILED! => 
  reason: Could not find or access '/path/to/ansible/apache-RedHat.yml' on the Ansible Controller
```

### Expected Results

It seems that the interpolated file should be searched for under `my-role/tasks`, but that doesn't appear to be the case

### Actual Results

```console
Role failed because: `reason: Could not find or access '/path/to/ansible/apache-RedHat.yml' on the Ansible Controller`
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
Can you provide a directory listing of your `tasks` dir?

**Comment by ticktockhouse** [comment]
@sivel I have updated the original comment, many thanks :)

**Comment by sivel** [comment]
`apache-Redhat.yml` != `apache-RedHat.yml` 

Your file uses a lowercase `h`, but needs to be `H` to match.

**Comment by jborean93** [comment]
Closing as per the above.

**Comment by ticktockhouse** [comment]
D'oh! Thanks for pointing that out. I would still argue that the error message is a little confusing, though, as it makes it seem that it's not looking in the `tasks/` directory
