### ISSUE TITLE
unarchive unnecessarily requires gnu tar

### ISSUE THREAD

**Issue by abh** [ansible/ansible#75441]
### Summary

5+ years ago it appears `tar` on didn't support the required `-C` option, so the unarchive module errors out on macOS and other platforms that come with "bsdtar".

"bsdtar" got support for `-C` in 2018 and this version is on macOS and FreeBSD (and I am guessing the other platforms with BSD user land).

### Issue Type

Bug Report

### Component Name

unarchive

### Ansible Version

```console
$ ansible --version
ansible 2.10.11
  config file = /Users/ask/.ansible.cfg
  configured module search path = ['/Users/ask/.ansible/plugins/modules', '/opt/local/share/ansible/plugins/modules']
  ansible python module location = /opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ansible
  executable location = /opt/local/bin/ansible
  python version = 3.9.6 (default, Jul  5 2021, 01:04:38) [Clang 12.0.5 (clang-1205.0.22.9)]
```

### Configuration

```console
$ ansible-config dump --only-changed
CACHE_PLUGIN(/Users/ask/.ansible.cfg) = memory
DEFAULT_ACTION_PLUGIN_PATH(/Users/ask/.ansible.cfg) = ['/usr/share/ansible_plugins/action_plugins']
DEFAULT_CALLBACK_PLUGIN_PATH(/Users/ask/.ansible.cfg) = ['/usr/share/ansible_plugins/callback_plugins']
DEFAULT_CONNECTION_PLUGIN_PATH(/Users/ask/.ansible.cfg) = ['/usr/share/ansible_plugins/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/Users/ask/.ansible.cfg) = ['/usr/share/ansible_plugins/filter_plugins']
DEFAULT_FORKS(/Users/ask/.ansible.cfg) = 5
DEFAULT_GATHERING(/Users/ask/.ansible.cfg) = implicit
DEFAULT_HOST_LIST(/Users/ask/.ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_LOOKUP_PLUGIN_PATH(/Users/ask/.ansible.cfg) = ['/usr/share/ansible_plugins/lookup_plugins']
DEFAULT_MANAGED_STR(/Users/ask/.ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_POLL_INTERVAL(/Users/ask/.ansible.cfg) = 15
DEFAULT_TIMEOUT(/Users/ask/.ansible.cfg) = 10
DEFAULT_TRANSPORT(/Users/ask/.ansible.cfg) = smart
DEFAULT_VARS_PLUGIN_PATH(/Users/ask/.ansible.cfg) = ['/usr/share/ansible_plugins/vars_plugins']
```

### OS / Environment

macOS 11.5.1

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

Unarchive works with the OS supplied tar.

### Actual Results

```console
FAILED! => {"changed": false, "msg": "Failed to find handler for \"/Users/ask/.ansible/tmp/ansible-tmp-1628491534.1004171-13564-8155916051917/source\". Make sure the required command to extract the file is installed. Command \"/usr/bin/unzip\" could not handle archive. Command \"/usr/bin/tar\" detected as tar type bsd. GNU tar required."}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by abh** [comment]
Old related issue https://github.com/ansible/ansible-modules-core/pull/4037

**Comment by sivel** [comment]
bsd tar also doesn't support `--diff` which is used to determine whether or not anything should be extracted from the archive.

**Comment by abh** [comment]
@sivel isn't that a "nice to have" optimization? Glancing at the code I thought it already handled diff not being available (or easily could be made to handle that).

**Comment by ht-0** [comment]
I have stumbled on this yesterday writing several roles that were designed to use `ansible.builtin.unarchive`.

I think `ansible.builtin.unarchive` should provide a parameter that, when set, would consciously allow user to unpack archive and overwrite all destination files when using BSD tar.

Otherwise user is forced to double the work and write tasks to copy **and** unpack archive with `ansible.builtin.command` provided with tar.

**Comment by mkrizek** [comment]
> Otherwise user is forced to double the work and write tasks to copy **and** unpack archive with `ansible.builtin.command` provided with tar.

Another option is to install gnu tar.

**Comment by nitzmahone** [comment]
The BSD tar implementation is new enough that we can't just assume it's there, and maintaining a bespoke diff impl is definitely a nonstarter. Closing as per above.

**Comment by yaazkal** [comment]
> Another option is to install gnu tar.

Could be, but from the FreeBSD user perspective, why install another tool that does what a tool that comes with the OS does?

Anyway installing gnu tar will require an _extra task_ 

@abh What I do at the moment due the lack of bsdtar support is to use the `command` module and turning off the warning about using the `unarchive` module. Here an [example](https://github.com/yaazkal/ansible-role-bastille/blob/b39f8fafd6a38262e49875218c2994cdc637d235/tasks/main.yml#L34)

**Comment by bcoca** [comment]
as per above, the two tools do NOT do the exact same thing, having the builtin --diff is a major feature the unarchive module relies on and having a duplicate implementation in python to support is far from optimal.
