### ISSUE TITLE
Module subversion - 'export=False' doesn't work, gives errors

### ISSUE THREAD

**Issue by edrozenberg** [ansible/ansible#7548]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
git 2014-05-26
##### Environment:

Running on Mac OSX 10.9.3 managing Slackware64 14.1
##### Summary:

In the subversion module, setting 'export=False' does an export anyway and gives errors instead of doing a proper checkout. The 'export' parameter has to be completely omitted in order for a checkout to be done successfully.

In addition the documentation (http://docs.ansible.com/subversion_module.html) needs to be updated to show proper information under 'default' and 'choices' columns for the export parameter.
##### Steps To Reproduce:

```
name: jcc svn checkout and update source
subversion: >
    repo=http://svn.apache.org/repos/asf/lucene/pylucene/trunk/jcc
    dest=/usr/local/src/jcc--svn
    export=False
```
##### Expected Results:

Expected a proper svn checkout to happen to the dest
##### Actual Results:

It did what appears to be an export rather than a checkout (there is no .svn directory in the dest) and gave errors:
## First run errors

```
TASK: [build | jcc svn checkout and update source] **************************** 
failed: [work1] => {"cmd": "/usr/bin/svn --non-interactive --trust-server-cert --no-auth-cache info /usr/local/src/jcc/jcc--svn", "failed": true, "item": "", "rc": 1}
stderr: svn: E155007: '/usr/local/src/jcc/jcc--svn' is not a working copy
msg: svn: E155007: '/usr/local/src/jcc/jcc--svn' is not a working copy
```
## Second and subsequent run errors

```
TASK: [build | jcc svn checkout and update source] **************************** 
failed: [work1] => {"failed": true, "item": ""}
msg: ERROR: /usr/local/src/jcc/jcc--svn folder already exists, but its not a subversion repository.
```

**Comment by mpdehaan** [comment]
Looks to be an issue with boolean handling.

The default value of export is False, so you won't have to pass it in unless you want to set export=True (so easy workaround, regardless)

**Comment by edrozenberg** [comment]
Hello Michael,

Sure, that makes sense. Ideally it should work with
an explicit ‘export=False’ as well but for now I’m
ok leaving it out to get my script to work, not a
problem.

Regards,
—Ed

**Comment by jimi-c** [comment]
I have pushed the above patch which should correct this issue. Please let us know if you have any further problems regarding this issue. Thanks!

**Comment by edrozenberg** [comment]
Thanks James!

The documentation (http://docs.ansible.com/subversion_module.html) could be improved slightly to show the default and choices values for export, I could probably do that once I teach myself git.

Also many bools in Ansible use yes/no values, whereas export uses True/False. No big deal I suppose since it's a bool variable and either works.

In the code (library/source_control/subversion) it's also visible ( yes/no vs True/False) - 
force=dict(default='yes', type='bool'),
export=dict(default=False, required=False, type='bool'),

Regards,
--Ed

**Comment by jimi-c** [comment]
Interesting, since the doc was set to "  default: False" it was being parsed as a boolean by the documentation generator. I've modified that to ensure it shows up correctly and will kick off a documentation update shortly. Thanks!
