### ISSUE TITLE
Docs survey feedback: move modules to the top of the collection docs template

### ISSUE THREAD

**Issue by acozine** [ansible/ansible#75510]
### Summary

Modules are, for most collections, the most frequently used plugins. In the current collection docs template, plugins are listed in alphabetical order, so other plugin types (callback, inventory, lookup) appear closer to the top of the page. 

Make modules the first category in the plugin list.

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/collections

### Ansible Version

```console
$ ansible --version
N/A
```

### Configuration

```console
$ ansible-config dump --only-changed
N/A
```

### OS / Environment

N/A

### Additional Information

None needed.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by acozine** [comment]
Hm. Perhaps this should be filed in a different repo. The template is now at https://github.com/ansible-community/antsibull/blob/main/antsibull/data/docsite/plugins_by_collection.rst.j2.

**Comment by ariordan-redhat** [comment]
Created an issue in the Antsibull repo: https://github.com/ansible-community/antsibull/issues/331

**Comment by samccann** [comment]
Issue resolved by https://github.com/ansible-community/antsibull/pull/336
