### ISSUE TITLE
regex_replace filter error (was: with inventory_hostname)

### ISSUE THREAD

**Issue by hkariti** [ansible/ansible#7551]
##### Issue Type:

Bug Report
##### Ansible Version

ansible 1.7 (devel e43ae3c0f7) last updated 2014/05/26 17:29:21 (GMT +300)

The root cause is here since 1.5.5 at least though
##### Environment

N/A
##### Summary

Probably a bigger bug with templating, but only regex_replace is bitten by this afaik.

Passing ansible variables to functions in jinja2 templates can fail the playbook if they raise the wrong exception when these variables are undefined. This is caused by a wrong handling by Ansible of the exception raised.

The exception is handled at `lib/ansible/utils/template.py` line 345:

``` python
except TypeError, te:
   if 'StrictUndefined' in str(te):
       raise errors.AnsibleUndefinedVariable(
            "Unable to look up a name or access an attribute in template string. " + \
            "Make sure your variable name does not contain invalid characters like '-'."
        )
    else:
        raise errors.AnsibleError("an unexpected type error occured. Error was %s" % te)
```

However, in the regex_replace example, `re.sub` raises a different `TypeError` than what Ansible expects, leading to the `AnsibleError` being raised.

I worked around this by adding useless lines that use `regex_parse`'s parameters before `re.sub`, leading to the expected exception to be raised:

``` python
def regex_replace(value='', pattern='', replacement='', ignorecase=False):
    str(value) # useless
    # continue regex_replace...
```
##### Steps to reproduce

This playbook:

```
- hosts: all
  gather_facts: no
  tasks:
     - debug: msg={{ inventory_hostname | regex_replace('a', 'b') }}
```
##### Expected Result

Playbooks succeeds.
##### Actual Result

```
PLAY [all] ******************************************************************** 
ERROR: an unexpected type error occured. Error was expected string or buffer
```

**Comment by mpdehaan** [comment]
There's nothing magical about inventory_hostname here and it's actually defined.

We can look into what's going on here, of course, though I think your premise in the middle of this ticket is probably in fact not it, and there's something else afoot.

**Comment by hkariti** [comment]
You're right, there's nothing magical about inventory_hostname. It'll
behave the same with any variable I bet.

But it is not defined on the first call to this function. I definitely saw
this exception being raised and caught when my workaround was in place.

**Comment by jimi-c** [comment]
The issue here was that, on the first pass of templating the title, the value passed into the regex_replace filter was or type jinja2.runtime.StrictUndefined, which the re module did not like. Massaging the value into a string when it's not already a basestring type resolves the issue, so I've merged the above patch in. If you have any further questions regarding this, please let us know. Thanks!

**Comment by hkariti** [comment]
Thanks for the fix! However it doesn't prevent future cases like this from happening, especially if people write custom jinja filters and they start failing inexplicably. Is there a way to avoid calling filters with jinja2.StrictUndefined objects, and just handle the 'undefined variable' errors in advance?
