### ISSUE TITLE
Add a stable version for the Python API

### ISSUE THREAD

**Issue by ccrvlh** [ansible/ansible#75572]
### Summary

It would be great if there was a stable release for a Python SDK/API.
As much as the current workflow of CLI + YAML files is great, and really flexible, being able to dynamically create playbooks in a more Pythonic way would be amazing.

I've seen a couple of examples in the documentation, but with not much documentation about it and with a disclaimer that this is for "internal use only" and not production-ready. I understand there might be some trade-offs between SDK stability and Ansible YAML nature progress, but maybe having a stable API, even it was not covering 100% of the tasks and builtin features would be great with little downside, opening up a whole new way of using Ansible. It's fair to have a "Core SDK", and it's ok if it has only X% coverage of Ansible's capabilities.

As much as it would be possible to dynamically write YAML files in Python (or any other language for that matter), this is a less then optimal workaround, and given that the code base is almost entirely written in Python, I would think  that improving the documentation for the SDK and increasing stability wouldn't be extremely disrupting.

Would love to hear your thoughts on that, and would be more than happy to contribute as well.
And of course, thank you so much, amazing program and platform.

### Issue Type

Feature Idea

### Component Name

sdk

### Additional Information

This example is perfect, and it's in the documentation.
It would be great for this to be stable.

```python
    host_list = ['localhost', 'www.example.com', 'www.google.com']
    # since the API is constructed for CLI it expects certain options to always be set in the context object
    context.CLIARGS = ImmutableDict(connection='smart', module_path=['/to/mymodules', '/usr/share/ansible'], forks=10, become=None,
                                    become_method=None, become_user=None, check=False, diff=False)
    # required for
    # https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/manager.py#L204
    sources = ','.join(host_list)
    if len(host_list) == 1:
        sources += ','

    # initialize needed objects
    loader = DataLoader()  # Takes care of finding and reading yaml, json and ini files
    passwords = dict(vault_pass='secret')

    # Instantiate our ResultsCollectorJSONCallback for handling results as they come in. Ansible expects this to be one of its main display outlets
    results_callback = ResultsCollectorJSONCallback()

    # create inventory, use path to host config file as source or hosts in a comma separated string
    inventory = InventoryManager(loader=loader, sources=sources)

    # variable manager takes care of merging all the different sources to give you a unified view of variables available in each context
    variable_manager = VariableManager(loader=loader, inventory=inventory)

    # instantiate task queue manager, which takes care of forking and setting up all objects to iterate over host list and tasks
    # IMPORTANT: This also adds library dirs paths to the module loader
    # IMPORTANT: and so it must be initialized before calling `Play.load()`.
    tqm = TaskQueueManager(
        inventory=inventory,
        variable_manager=variable_manager,
        loader=loader,
        passwords=passwords,
        stdout_callback=results_callback,  # Use our custom callback instead of the ``default`` callback plugin, which prints to stdout
    )

    # create data structure that represents our play, including tasks, this is basically what our YAML loader does internally.
    play_source = dict(
        name="Ansible Play",
        hosts=host_list,
        gather_facts='no',
        tasks=[
            dict(action=dict(module='shell', args='ls'),register='shell_out'),
            dict(action=dict(module='debug', args=dict(msg='{{shell_out.stdout}}'))),
            dict(action=dict(module='command', args=dict(cmd='/usr/bin/uptime'))),
        ]
    )
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by lowercase00** [comment]
@nitzmahone I'm guessing this should be challenging for you guys since it would directly affect the logic behind the engine that deals with the CLI. I even considering making something like "PyAnsible" to help interact with the source code, so would be great to hear your thoughts and insights regarding the challenges and why this hasn't been incorporated in Ansible's plans yet. Thanks!
