### ISSUE TITLE
Error when adding user to CentOS with missing shadow entry for user

### ISSUE THREAD

**Issue by agibson2** [ansible/ansible#75591]
### Summary

If you setup ansible to create a user and put the option to not expire "expires: -1", If the user already exists on a system but has a missing shadow entry, you get an error when trying to do something internally in user.py with a blank value.  Since there is no /etc/shadow entry, I suspect it is getting '' for expires and then trying to convert that to an int to compare to what I defined in the playbook.  This user was created without the normal system utilities I believe which is why it didn't get the /etc/shadow entry for the user.  Obviously the /etc/shadow entry should be created for the expiration and such to be set using the system utilities but it appears that Linux libraries and such do not require the entry to be there so maybe this is a valid state that should be dealt with.  Ansible should be able to set it to -1 by the normal system utilities which would create the /etc/shadow entry for the user.

ansible/modules/system/user.py\", line 799, in modify_user_usermod\r\n    \r\nValueError: invalid literal for int() with base 10: ''\r\n",

It would appear it is getting empty values for password expiration and then trying to convert empty string to int.

```
           if self.expires is not None:

            current_expires = int(self.user_password()[1])"
```

### Issue Type

Bug Report

### Component Name

user

### Ansible Version

```console
$ ansible --version
ansible 2.9.21
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/agibson/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

### Configuration

```console
$ ansible-config dump --only-changed

Nothing is returned by that command.
```

### OS / Environment

CentOS 7
$ cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

### Steps to Reproduce

Prepare the system by adding a user using adduser shell command and then remove the users shadow line entry from /etc/shadow using 'vipw -s' command.

```yaml (paste below)
- name: Add persistent user accounts
  user:
    name: testuser
    password: '$6$mysecretsalt$qJbapG68nyRab3gxvKWPUcs2g3t0oMHSHMnSKecYNpSi3CuZm.GbBqXO8BE6EI6P1JUefhA0qvD7b5LSh./PU1'
    comment: Test user
    expires: -1
```

### Expected Results

I expected the user to be seen as already created and then change the expiration to not expire "-1" which would create the missing /etc/shadow entry for the user.

### Actual Results

```console
ansible/modules/system/user.py\", line 799, in modify_user_usermod\r\n    \r\nValueError: invalid literal for int() with base 10: ''\r\n",
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mkrizek** [comment]
We should fix the traceback to be something more user friendly.

**Comment by Akasurde** [comment]
resolved_by_pr https://github.com/ansible/ansible/pull/75194
