### ISSUE TITLE
The Ansible Contributor Summit 09.21 registration is open

### ISSUE THREAD

**Issue by Andersson007** [ansible/ansible#75641]
### Summary

We are happy to announce that the [registration](https://ansiblecs202109.eventbrite.com/?aff=github) (free) for the Ansible Contributor Summit is open.

The Summit will consist of two days - before and after two days of the [Ansible Fest](https://www.ansible.com/ansiblefest) that will also happen virtually this year.

Which day should you attend?

##### Day 1 (Tuesday, September 28)

If you are wondering what it means to "contribute" to Ansible, or if you have been using Ansible for a while and are thinking of ways to get more involved with the project and community, then Day 1 is for you!

Among other topics, there will be:

- Ask a maintainer session (Interactive session covering what it means to be/become a collection maintainer, their roles, responsibilities, how open source projects work/operate, and more).
- Group instructor-led class in setting up a development environment (The main purpose of the session is to help you set up a minimalistic but complete Ansible collection development environment).
- Interactive self-passed instruqt scenarios that help you learn different aspects of development.

##### Day 2 (Friday, October 1)

If you have already been contributing or participating in our previous Contributor Summits, you are still welcome to attend Day 1, however we think that Day 2 will be more interesting for you.

Among other topics, there will be:

- Welcome and announcements.
- Matrix, the new communication format.
- Different presentations by Core, Cloud, Network, and other teams.

##### Hackathon (Tuesday to Friday)

In addition, we will be running a Hackathon throughout the week.

- This is for anyone with an interest in contributing to Ansible (with a focus on Collections), including those who have never contributed and are unsure of how to get started, existing contributors and maintainers, etc. all are welcome!
- Resources (people, labs, docs, etc) will be available to help people through the entire process.

More details will be available soon. Please register [here](https://ansiblecs202109.eventbrite.com/?aff=github) so that you will be informed of the updates!

See you at the summit!

**Comment by Andersson007** [comment]
bot_skip

**Comment by dericcrago** [comment]
[AnsibleFest]: https://www.ansible.com/ansiblefest
[Ansible Contributor Summit]: https://ansiblecs202109.eventbrite.com/?aff=github
[Hackathon]: https://hackmd.io/@ansible-community/contrib-summit-202109#Hackathon
[Ansible Contributor Summit 2021.09 HackMD]: https://hackmd.io/@ansible-community/contrib-summit-202109

**Reminder - [AnsibleFest] and [Ansible Contributor Summit] are 1 week away!**

In case you missed it, we will also be having a **[Hackathon]** throughout the entire **[Ansible Contributor Summit]** and **[AnsibleFest]**. This is a great opportunity to collaborate in real time with other members of the Ansible Community!

For more info and the latest updates, please see the **[Ansible Contributor Summit 2021.09 HackMD]**.

**Comment by Andersson007** [comment]
[Ansible Contributor Summit]: https://ansiblecs202109.eventbrite.com/?aff=github
[Hackathon]: https://hackmd.io/@ansible-community/contrib-summit-202109#Hackathon
[Ansible Contributor Summit 2021.09 HackMD]: https://hackmd.io/@ansible-community/contrib-summit-202109

**Reminder** - Day 1 of the [Ansible Contributor Summit] and the [Hackathon] start tomorrow (Tuesday, 28 September 2021)!

For more info and the latest updates, please see the **[Ansible Contributor Summit 2021.09 HackMD]**.

**Comment by Andersson007** [comment]
[Ansible Contributor Summit]: https://ansiblecs202109.eventbrite.com/?aff=github
[Hackathon]: https://hackmd.io/@ansible-community/contrib-summit-202109#Hackathon
[Ansible Contributor Summit 2021.09 HackMD]: https://hackmd.io/@ansible-community/contrib-summit-202109

**Reminder** - Day 2 of the [Ansible Contributor Summit] and the last day of the [Hackathon] start tomorrow (Friday, 1 October 2021)!

For more info and the latest updates, please see the **[Ansible Contributor Summit 2021.09 HackMD]**.

**Comment by Andersson007** [comment]
thanks everyone who attended!
