### ISSUE TITLE
Run Ansible against EC2 inventory by Amazon Machine Image (AMI) ID.

### ISSUE THREAD

**Issue by JoeyGAtNi** [ansible/ansible#7566]
##### Issue Type:

Feature Pull Request
##### Ansible Version:

ansible 1.7 (devel 617e7eaf5b) last updated 2014/05/27 16:58:45 (GMT +000)
##### Environment:

Ubuntu 12.04
##### Summary:

Update ec2.py inventory script to include groups by Amazon Machine Image (AMI) ID. This is useful to run ansible commands against a specific image... such as a webserver that needs a security update.

**Comment by mpdehaan** [comment]
We don't want to clutter up the inventory script to provide groups by AMI ID by default, because there are already a giant ton of groups being generated.

I would accept this being configurable, default _off_.

Pull requests would be considered.
