### ISSUE TITLE
reuse of existing modules

### ISSUE THREAD

**Issue by hans-d** [ansible/ansible#7570]
##### Issue Type:

Question / Feature Idea / Documentation Report
##### Ansible Version:

ansible 1.5.4
##### Environment:

Ubuntu 14.04 / N/A
##### Summary:

Im looking at how to write a module that can reuse other modules, eg to reload a service using the service module, or depending on some configuration reload a service using supervisorctl. Another variant could be to have a generic system pack manager that uses apt or yum.

How can I execute any given module from another, set the required parameters for that module at runtime with some kind of pre-processing, and do some post-processing of the results?
##### Steps To Reproduce:

A module containing something like (pseudo code):

```
result = execute.module ('service', { with: some params })
new_result = do_something with result or not (result)
return new_result
```
##### Expected Results:

Call form module A into module B, for module B it would if a normal playbook task was executed

**Comment by bcoca** [comment]
this is more a 'ansible-devel' question​, there are ways to use common code
between modules but not really a module chaining facility.

**Comment by jimi-c** [comment]
I agree with @bcoca, this should be a discussion on ansible-devel. We reserve Github issues for bugs and feature requests only. Thanks!
