### ISSUE TITLE
running ansible-playbook reports syntax error without any reference

### ISSUE THREAD

**Issue by hans-d** [ansible/ansible#7572]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4
##### Environment:

Ubuntu 14.04
##### Summary:

Currently trying to debug some playbook with various roles after getting `ERROR: with is not a legal parameter in an Ansible task or handler`

Running `ansible-playbook test.yml --check -vvvv` or `ansible-playbook test.yml --check-syntax` does not provide any information re which file, line or anything else that might help finding the illegal parameter.

This is the case with many reported errors.
##### Steps To Reproduce:

playbook:

```
- hosts: 127.0.0.1
  connection: local
  roles:
    - test
```

test/tasks/main.yml

```
- name: example
  command: echo {{ item }}
  with: [ some, value ]
```
##### Expected Results:

In addition to the error, at least the file name, and possibly more details (line or structure where it was found)
##### Actual Results:

```
ERROR: with is not a legal parameter in an Ansible task or handler
```

without any reference to where the error is encountered

**Comment by jimi-c** [comment]
Based on the error, it seems like you have a `with:` when you either meant `with_items` or some other loop type, or maybe you just meant `when:` instead?

**Comment by hans-d** [comment]
@jimi-c correct, that was the underlying issue.
However, I would like to get some context with the error to help me correcting the issue. That is an issue with many of the error messages from ansible I have seen sofar.

**Comment by hans-d** [comment]
updated description

**Comment by jimi-c** [comment]
This has been suggested in the past, however the main difficulty in showing the line/column with these types of errors is that they occur after the YAML has been parsed and we're just dealing with a raw data structure, so it's very difficult to map that back to a file. Based on that, I'm going to go ahead and close this, if you have any further questions, please let us know. Thanks!
