### ISSUE TITLE
Two options for EC2 inventory

### ISSUE THREAD

**Issue by JoeyGAtNi** [ansible/ansible#7574]
##### Issue Type:

Feature Pull Request
##### Ansible Version:

ansible 1.7 (devel 617e7eaf5b) last updated 2014/05/27 16:58:45 (GMT +000)
##### Environment:

Ubuntu 12.04
##### Summary:

Provide options for EC2 inventory. First commit (d7017d906b47972210fd74e7b18d7318685624f2) only adds option to group inventory based on AMI IDs. Second commit (0c956de9bdeaf801de532bc6acfb244de52fb327) provides option to pick which groups are desired.

For example, if the user only wants groups based on AMI ID and security group, the user can set this in the ec2.ini.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
I'm curious why this is appearing already merged and this is not a pull request itself.   Weird.

**Comment by JoeyGAtNi** [comment]
Weird indeed. Anyway, the pull request is https://github.com/ansible/ansible/pull/7573.

**Comment by mpdehaan** [comment]
Thanks, I've filed a GitHub support ticket about this, so let's not merge this right away so they can take a look.

Otherwise this seems fine.

**Comment by mpdehaan** [comment]
GitHub has responded that when referencing a SHA you have to do username/SHA, which I find super confusing and non-intuitive.   That's a bug on their end though.   Good to go.

**Comment by bcoca** [comment]
closing through alternative PR meged  #10211
