### ISSUE TITLE
yum: expected string of buffer

### ISSUE THREAD

**Issue by wgj** [ansible/ansible#758]
Running the yum module results in unexpected error. 
CentOS 6 master-server
CentOS 5 client-servers

Note: wasn't sure of the yum's syntax

[wes@mgmt001 ~]$ ansible vulcan.domain.com -i host -m yum -a "pkg=htop state=installed"
vulcan.domain.com | FAILED >> {
    "failed": true, 
    "module": "yum", 
    "msg": "expected string or buffer"
}

[wes@mgmt001 ~]$ ansible vulcan.domain.com -i host -m yum -a "name=htop state=present"
vulcan.domain.com | FAILED >> {
    "failed": true, 
    "module": "yum", 
    "msg": "expected string or buffer"
}

[root@mgmt001 ansible]# git status
 On branch devel
nothing to commit (working directory clean)
[root@mgmt001 ansible]# git pull
Already up-to-date.

**Comment by mpdehaan** [comment]
This was fixed last night, but probably right after you submitted it, can you pull and see if you still see this?

If that still occurs we can reopen it, but I've done installs/removals so you should be good to go.
