### ISSUE TITLE
Give ansible-vault the option --vault-password-file

### ISSUE THREAD

**Issue by eproxus** [ansible/ansible#7580]
##### Issue Type:

Feature Idea
##### Ansible Version:

`ansible 1.6.2`
##### Environment:

N/A
##### Summary:

Add the flag ``--vault-password-file` to `ansible-vault` so the same password file can be used both in editing the vault file and using it.
##### Steps To Reproduce:

```
$ ansible-vault --vault-password-file MYFILE vars.yml
```
##### Expected Results:

```
$ ansible-vault --vault-password-file MYFILE vars.yml
[File opened in $EDITOR]
```
##### Actual Results:

```
$ ansible-vault --vault-password-file MYFILE vars.yml
Usage: ansible-vault [create|decrypt|edit|encrypt|rekey] [--help] [options] file_name

Options:
  -h, --help  show this help message and exit

See 'ansible-vault <command> --help' for more information on a specific command
```

**Comment by mpdehaan** [comment]
This exists:

https://github.com/ansible/ansible/blob/devel/bin/ansible-vault

You need to issue a subcommand first though, which is why it is telling you to do something else.

ansible-vault edit filename.yml --vault-password-file foo

etc

**Comment by eproxus** [comment]
Ah, didn't realize the sub commands had their own flags. Thanks!
