### ISSUE TITLE
Conditional include order

### ISSUE THREAD

**Issue by hans-d** [ansible/ansible#7589]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.2
##### Environment:

Ubuntu 14.04
##### Summary:

When having nested conditional results, where in the first include a variable like `test.sub` is defined, and that variable is used in the second conditional include it fails on the first step of the 3rd file as the variable is not defined.

It seems that the include condition is ordered incorrectly.

When explicitly adding the original condition before the new condition, eg `test1 == 1 and test.sub == 1` than it works fine.

Using simple variables, eg `test_sub` vs `test.sub` there is no fail situation. 

Seems related to #4469.
##### Steps To Reproduce:

```
# playbook
- hosts: 127.0.0.1
  connection: local
  roles: [ test ]

# test/tasks/

---  # main.yml
- debug: var=test1
- debug: var=test2
- debug: var=test
- include: test1.yml
  when: test1 == 1

--- # test1.yml
- debug: msg="test1"
- set_fact:
    test:
      sub: '{{ test2 }}'
- include: test2.yml
  when: test.sub == 1

--- # test2.yml
- debug: msg="test2"
- command: echo "got here!"
  when: test3 == 1

# execute
ansible-playbook test.yml  --extra-vars '{ "test1": 0, "test2": 0 }'
```
##### Expected Results:

```
TASK: [test | debug msg="test2"] **********************************************
skipping: [127.0.0.1]
```
##### Actual Results:

relevant part:

```
TASK: [test | debug msg="test2"] **********************************************
fatal: [127.0.0.1] => error while evaluating conditional: test.sub == 1
```

full result:

```
PLAY [127.0.0.1] **************************************************************

GATHERING FACTS ***************************************************************
ok: [127.0.0.1]

TASK: [test | debug var=test1] ************************************************
ok: [127.0.0.1] => {
    "item": "",

    "test1": "0"

}

TASK: [test | debug var=test2] ************************************************
ok: [127.0.0.1] => {
    "item": "",

    "test2": "0"

}

TASK: [test | debug var=test] *************************************************
ok: [127.0.0.1] => {
    "item": "",

    "test": "{{ test }}"

}

TASK: [test | debug msg="test1"] **********************************************
skipping: [127.0.0.1]

TASK: [test | set_fact ] ******************************************************
skipping: [127.0.0.1]

TASK: [test | debug msg="test2"] **********************************************
fatal: [127.0.0.1] => error while evaluating conditional: test.sub == 1

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/hans/test.retry

127.0.0.1                  : ok=4    changed=0    unreachable=1    failed=0
```

**Comment by mpdehaan** [comment]
Just as clarification, includes don't actually decide whether to run the include or not, they apply the conditionals in a stack so conditionals are fed to everything.

We'll look into this as I don't think many people do it this way, usually they have just had a conditional on a role or include and a conditional on the task, but I would expect the above to be functional the way you have it.

Need to confirm to be sure.

**Comment by jimi-c** [comment]
I believe this is expected, and results from the fact that as @mpdehaan noted the YAML is all parsed ahead of time, and includes are always brought in regardless of the conditionals assigned to them. This  means that when the set_fact task is not run as a result of the conditional, the variable `test.sub` is not available for checking in the next conditional, thus the error. You can get around this with the following minor change:

<pre>
- include: test2.yml
  when: test is defined and test.sub
</pre>

Also note that since the jinja2 conditionals use python syntax, you don't have to check for `== 1`, just checking its python "truthiness" is enough.

If you have any further questions about this, please let us know. Thanks!
