### ISSUE TITLE
ec2_group Errors when using self referencing groups

### ISSUE THREAD

**Issue by jimbydamonk** [ansible/ansible#7592]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

N/A
##### Summary:

This playbook:

```

---
- hosts: localhost
  vars:
    vpc_id: <<REMOVED>>
  tasks:
    - name: Test self referencing security group 
      local_action:
        module: ec2_group
        name: 'self_referencing_group'
        description: 'Default Security Group'
        region: 'eu-west-1'
        vpc_id: '{{ vpc_id }}'
        rules:
          - proto: udp 
            from_port: 0 
            to_port: 65535
            group_name: 'self_referencing_group'
        rules_egress:
          - proto: all 
            from_port: -1 
            to_port: -1
            cidr_ip: 0.0.0.0/0
```

returns

```
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/205708/.ansible/tmp/ansible-tmp-1401392813.67-129993790148010/ec2_group", line 1739, in <module>
    main()
  File "/Users/205708/.ansible/tmp/ansible-tmp-1401392813.67-129993790148010/ec2_group", line 267, in main
    group_id, ip, target_group_created = get_target_from_rule(rule, name, groups)
  File "/Users/205708/.ansible/tmp/ansible-tmp-1401392813.67-129993790148010/ec2_group", line 153, in get_target_from_rule
    group_id = group.id
NameError: global name 'group' is not defined


FATAL: all hosts have already failed -- aborting
```

This seems to have beed introduced with commit  77d7165dde0b5f5642ec3667854d55ca2482602c

By moving the code to the function get_target_from_rule, the code loses access to group. 
##### Steps To Reproduce:

Edit above playbook with a vpc id and run 
##### Expected Results:

Security group created with appropriate rules. 
##### Actual Results:

```
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/205708/.ansible/tmp/ansible-tmp-1401392813.67-129993790148010/ec2_group", line 1739, in <module>
    main()
  File "/Users/205708/.ansible/tmp/ansible-tmp-1401392813.67-129993790148010/ec2_group", line 267, in main
    group_id, ip, target_group_created = get_target_from_rule(rule, name, groups)
  File "/Users/205708/.ansible/tmp/ansible-tmp-1401392813.67-129993790148010/ec2_group", line 153, in get_target_from_rule
    group_id = group.id
NameError: global name 'group' is not defined
```

FATAL: all hosts have already failed -- aborting

**Comment by zytek** [comment]
Is this similar? ec2_group does not work for me after updating from 1.5.5 to 1.6.1 or 1.6.2:

```
failed: [localhost] => {"failed": true, "item": "", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/zytek/.ansible/tmp/ansible-tmp-1401797825.12-88121342787413/ec2_group", line 1715, in <module>
    main()
  File "/Users/zytek/.ansible/tmp/ansible-tmp-1401797825.12-88121342787413/ec2_group", line 248, in main
    group_id, ip, target_group_created = get_target_from_rule(rule, name, groups)
  File "/Users/zytek/.ansible/tmp/ansible-tmp-1401797825.12-88121342787413/ec2_group", line 144, in get_target_from_rule
    module.fail_json(msg="group %s will be automatically created by rule %s and no description was provided" % (group_name, rule))
NameError: global name 'module' is not defined


FATAL: all hosts have already failed -- aborting
```

**Comment by jimbydamonk** [comment]
Yes. Same thing. When the code was moved, the module is not passed it. 
The module is not in the function's namespace. 
The main method defines module at line 142 (https://github.com/ansible/ansible/commit/77d7165dde0b5f5642ec3667854d55ca2482602c#diff-317f4cc0ba915fbd7bd5ac28fdadc031L142)

**Comment by jimi-c** [comment]
I've pushed the above patch to the devel branch, which should correct both of the above issues. Please let us know if you continue seeing any problems related to this. Thanks!

**Comment by jimbydamonk** [comment]
Looks good! works for me.

**Comment by jaytaylor** [comment]
Note: This can also happen when you're trying to create new groups with one or more sets of circular referencing rules.

When provisioning a new AWS cluster, if there are circular security-group
references (e.g. x-sg references y-sg and vice-versa) this will prevent the successful security-group initialization.

Workaround: Comment out the circular security-group rules when seeding them for the first time.

**Comment by mdaize** [comment]
Sorry to re-address this, but we have run into this same issue presently. The current solution is to run a second time as the first time it creates a blank security group after presenting an error. 

Because you need to create the security group before you can reconcile its' rules, would it not be better to refactor it so that it creates all the groups before applying the rules to each?

**Comment by jimi-c** [comment]
@matthewdaize could you please open a new issue on ansible/ansible-modules-core for this? Thanks!
