### ISSUE TITLE
Docs: Wrap code examples in code-block elements in 9 files in user_guide

### ISSUE THREAD

**Issue by ariordan-redhat** [ansible/ansible#75977]
**Assigned to @NarayanAdithya**

### Summary

**Problem**:
Throughout the Ansible docs, there are instances where example code is preceded with a lead-in sentence ending in `::`.
Translation programs then attempt to translate this code, which we don't want.

**Solution:**
Wrap code  in a `.. code-block:: <lexer>` element, so that translation processes know to skip this content.
For a list of allowed values for _`<lexer>`_ , refer to [Syntax highlighting - Pygments](https://docs.ansible.com/ansible/latest/dev_guide/style_guide/index.html#syntax-highlighting-pygments).

**Scope:**
The following files in the User Guide contain a number of lead-in sentences ending with `::`:

intro_dynamic_inventory.rst: 2 sentences
intro_inventory.rst: 1 sentence
playbooks_intro.rst: 2
playbooks_python_version.rst: 2
playbooks_lookups.rst: 1
playbook_pathing.rst: 1
windows_usage.rst: 2
windows_faq.rst: 1
windows_dsc.rst: 1

To identify the line numbers affected, navigate to the `docs/docsite/rst/user_guide/` directory  and use the following `grep` command:
```
$ grep -rn "^[[:blank:]]*[^[:blank:]\.\.].*::$" ./<filename.rst>
```

**Example:**

Before:
```
* If the file has a unique title, use that for the main page anchor::

   .. _unique_page::

```

After:
```
*  If the file has a unique title, use that for the main page anchor.

  .. code-block:: rst
   
    .. _unique_page::

```

This problem has been addressed in some other guides; view these merged PRs to help get you started:
- Network Guide: [#75850](https://github.com/ansible/ansible/pull/75850/files) 
- Developer Guide: [#75849](https://github.com/ansible/ansible/pull/75849/files) 

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/user_guide/intro_dynamic_inventory.rst

### Ansible Version

```console
n/a
```

### Configuration

```console
n/a
```

### OS / Environment

n/a

### Additional Information

When example code is wrapped in a `code-block` element, translation programs do not attempt to translate the code.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by NarayanAdithya** [comment]
@ariordan-redhat , hey I have figured out the places i have to change, but how do I identify what type of code follows?

**Comment by NarayanAdithya** [comment]
@meowlena I just wanted to confirm If what I am doing is correct, from what I understand I have to change the following line 123 in docs/docsite/rst/user_guide/intro_dynamic_inventory.rst 

```
Download the latest version of the OpenStack dynamic inventory script and make it executable::

    wget https://raw.githubusercontent.com/openstack/ansible-collections-openstack/master/scripts/inventory/openstack_inventory.py
    chmod +x openstack_inventory.py
```
to 

```
Download the latest version of the OpenStack dynamic inventory script and make it executable.

.. code_block:: bash

    wget https://raw.githubusercontent.com/openstack/ansible-collections-openstack/master/scripts/inventory/openstack_inventory.py
    chmod +x openstack_inventory.py

```

For some instanced I am able to figure out what the lexer is for some I am confused, so do i ask the doubt here ? @meowlena @ariordan-redhat

**Comment by NarayanAdithya** [comment]
I went to all the instances assigned to me , I couldn't figure out the lexers to be used for following instances:

1. File: playbook_pathing.rst line number 30 
2. File: windows_usage.rst line number 405

I am confused only about the above 2 instances, rest I have completed. So if you could tell me about this I could make the PR.
