### ISSUE TITLE
extends_documentation_fragment should use FQCN

### ISSUE THREAD

**Issue by thedoubl3j** [ansible/ansible#75983]
### Summary

currently, a collection can depend on the doc fragment inside of itself but moving forward, some collection maintainers may want to pull the doc fragment from another "base" collection. Example being a storage provider having a base collection that interacts directly with their hardware and then other collections that interact with their api/hardware on cloud providers. Some maintainers are already doing this but currently there is no enforcement/requirement of the FQCN be called for the doc fragment. 

Going forward, this might cause issues for other downstream products that are building documentation and need to resolve collection dependencies (ex: Automation Hub) so requiring FQCN for extending doc fragments will solve that issue before any arise. 

### Issue Type

Feature Idea

### Component Name

ansible-test

### Additional Information

```yaml (paste below)
ansible-test sanity --validate-modules
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mattclay** [comment]
@thedoubl3j Can you provide, or link to, an example of the behavior you would like to see detected by the sanity tests?

**Comment by thedoubl3j** [comment]
@mattclay we are going to have a conversation with @gundalow to confirm if other tooling covers this or the addition is warranted. will update accordingly
