### ISSUE TITLE
yum docs: strange skip_broken description

### ISSUE THREAD

**Issue by richlv** [ansible/ansible#76036]
### Summary

In https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html , skip_broken description says:

Skip packages with broken dependencies(devsolve) and are causing problems.

a) Missing space before the opening parenthesis.
b) The sentence seems weird - not fully sure what it tries to convey. Perhaps "Skip packages with broken dependencies (devsolve) and packages that are causing problems." ?

### Issue Type

Documentation Report

### Component Name

yum

### Ansible Version

```console
latest
```

### Configuration

```console
Not relevant
```

### OS / Environment

Not relevant

### Additional Information

Readable docs

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by jaydesl** [comment]
Shall I jump on this?
