### ISSUE TITLE
Python3 on Amazon Linux hosts

### ISSUE THREAD

**Issue by satellite-no** [ansible/ansible#76118]
### Summary

Hi,
I'm not sure if this is truly a bug, but I feel like it would be.  On Amazon Linux 2 (AMI 2) hosts Ansible fails to recognize the existents of Python3 and always falls back on Python2.  This is working as intended from what I can tell in the docs the bug is that the auto discovery doesn't recognize that AMI 2 is a CentOS/RHEL based OS and use those parameters.  The only way around this currently is to set the interpreter statically which I then have to manage on many different systems.  It would be nice if Ansible recognized AMI 2 and used Python3 on it vs using the fall back or allow custom dictionary for `INTERPRETER_PYTHON_DISTRO_MAP` (unless you can and i'm using it wrong).

### Issue Type

Bug Report

### Component Name

pip

### Ansible Version

```console
$ ansible --version
ansible 2.10.13
  config file = /opt/dev/user/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/python3-virtualenvs/py39venv-ansible-latest/lib/python3.9/site-packages/ansible
  executable location = /opt/python3-virtualenvs/py39venv-ansible-latest/bin/ansible
  python version = 3.9.1 (default, Dec 17 2020, 15:23:46) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/opt/dev/user/ansible/ansible.cfg) = True
ANSIBLE_SSH_RETRIES(/opt/dev/user/ansible/ansible.cfg) = 3
DEFAULT_FORKS(/opt/dev/user/ansible/ansible.cfg) = 10
DEFAULT_GATHERING(/opt/dev/user/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/opt/dev/user/ansible/ansible.cfg) = ['/opt/ansible/inventories']
DEFAULT_STDOUT_CALLBACK(/opt/dev/user/ansible/ansible.cfg) = skippy
DEFAULT_VAULT_PASSWORD_FILE(/opt/dev/user/ansible/ansible.cfg) = /opt/ansible/vault-env.py
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
INTERPRETER_PYTHON(/opt/dev/user/ansible/ansible.cfg) = auto_silent
RETRY_FILES_ENABLED(/opt/dev/user/ansible/ansible.cfg) = False
```

### OS / Environment

NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

### Steps to Reproduce

```
ansible 'hf1.akorn*' -m ping  -i /opt/ansible/inventories/splunk_automation/ -vvvv
```

### Expected Results

"discovered_interpreter_python": "/usr/bin/python3"

### Actual Results

```console
<target.host> Attempting python interpreter discovery
<target.host> ESTABLISH SSH CONNECTION FOR USER: None
<target.host> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/117b4e444a target.host '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
<target.host> (0, b'PLATFORM\nLinux\nFOUND\n/usr/bin/python\n/usr/bin/python3.7\n/usr/bin/python2.7\n/usr/bin/python3\n/usr/bin/python\nENDFOUND\n'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by flowerysong** [comment]
Still not a bug. It may be getting the correct answer for Amazon Linux 2 by a method you consider incorrect, but it's still the correct answer. If you want to use Python 3 on distros where that is not the default, that is within your power.
