### ISSUE TITLE
interpreter_python_distro_map option inaccessible

### ISSUE THREAD

**Issue by lihu-zhong** [ansible/ansible#76112]
### Summary

the ansible.cfg option "INTERPRETER_PYTHON_DISTRO_MAP" is a dictionary, but ansible only supports ini-format config files. It is not possible to express a valid override value for this option. Without this option, I don't see a way to update the default interpreter without disabling autodiscovery completely. Either yaml support or some hack that allows parsing inline json could resolve this. Simply adding a `vars` for this value could provide an easy short-term workaround.

I'm happy to write this patch if I get confirmation on which direction to go in.

### Issue Type

Bug Report

### Component Name

lib/ansible/config/manager.py

### Ansible Version

```console
Tip of devel as of 2021-10-21 (e40a0e5c90)
```

### Configuration

```console
N/A
```

### OS / Environment

N/A

### Steps to Reproduce

N/A

### Expected Results

I expect all documented config options to be accessible

### Actual Results

```console
documented config option is not accessible.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by lbenezriravin** [comment]
@sivel I'm not sure those options, even when released, solve this problem. setting ansible_python_interpreter disables all fallback behavior, which is not desired.
