### ISSUE TITLE
apt_repository module requires gpg to be installed target, but docs don't mention

### ISSUE THREAD

**Issue by zoredache** [ansible/ansible#76133]
### Summary

The `apt_repository` will fail with a somewhat confusing error if gnugp, and dirmngr manager are not installed.  Neither of these packages are Required/Essential/Important, and may not be already installed in minimal systems that you might want to run `apt_repository` on.

The fix might be to just include `gnupg` in the requirements section of the docs.

### Issue Type

Documentation Report

### Component Name

apt_repository

### Ansible Version

```console
$  ansible --version
ansible [core 2.11.4]
  config file = ...
  configured module search path = ...
  ansible python module location = ...
  ansible collection location = ...
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Mostly a docs issue so this is N/A. But apt_repository applies to Debian, Ubuntu, and forks.

### Additional Information

Tells people that need gnupg when using apt_repository.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by tigerblue77** [comment]
I transformed my
```bash
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
```
to
```bash
gpg --keyserver keyserver.ubuntu.com --recv 93C4A3FD7BB9C367 && \
gpg --export 93C4A3FD7BB9C367 > /usr/share/keyrings/ansible-archive-keyring.gpg
```
thanks to [this topic](https://www.reddit.com/r/linux/comments/ud9wg0/install_ansible_using_gpg_instead_of_aptkey_which/). Don't hesitate to suggest improvments :)

**Comment by samccann** [comment]
@bcoca the docs fix here seems quite simple - add gpg to the requirements on the `apt_repository` module. But I'm unsure if you want to keep this ticket open for a bugfix to change apt_key to something else because it's deprecated?

**Comment by bcoca** [comment]
since then i've updated apt_repository to use gpg in case apt-key is not present so 'requirements: apt-key or gpg

**Comment by samccann** [comment]
Documentation fix:

Add a line above https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/apt_repository.py#L102
That says:
- apt-key or gpg

**Comment by tigerblue77** [comment]
@bcoca As apt-key is deprecated, you should probably only use gpg and install it automatically if needed

**Comment by akamanzi** [comment]
@samccann @bcoca I can update the requirements section if that's the fix and if no one has taken on this issue

**Comment by samccann** [comment]
Sounds good, thanks @akamanzi !!

**Comment by akamanzi** [comment]
@samccann, check PR #78586
