### ISSUE TITLE
Notify handlers are executed on unchanged hosts

### ISSUE THREAD

**Issue by miklosn** [ansible/ansible#7620]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.2
##### Environment:

OS X

Installed through pip.
##### Summary:

Version 1.6.2 executes notify handlers on all hosts, in my case it restarts services on all servers whether they have configuration changes or not.

Reverting to 1.6.1 fixes the issue.
##### Steps To Reproduce:

Please see https://gist.github.com/miklosn/ce01bfd92b2349ea0f4f
##### Expected Results:

Expected results would be, as it is the case with 1.6.1, to execute these actions only on hosts that changed.

```
TASK: [bacula-fd configuration] ***********************************************
ok: [host4.local]
ok: [host3.local]
ok: [host2.local]
ok: [host5.local]
changed: [host1.local]
ok: [host6.local]
ok: [host7.local]

NOTIFIED: [restart bacula-fd] *************************************************
ok: [host3.local]
changed: [host1.local]
ok: [host2.local]
ok: [host4.local]
ok: [host6.local]
ok: [host7.local]
ok: [host5.local]
```
##### Actual Results:

```
TASK: [bacula-fd configuration] ***********************************************
ok: [host4.local]
ok: [host3.local]
ok: [host2.local]
ok: [host5.local]
changed: [host1.local]
ok: [host6.local]
ok: [host7.local]

NOTIFIED: [restart bacula-fd] *************************************************
changed: [host3.local]
changed: [host1.local]
changed: [host2.local]
changed: [host4.local]
changed: [host6.local]
changed: [host7.local]
changed: [host5.local]
```

**Comment by miklosn** [comment]
Nevermind, it is a duplicate.
:/

**Comment by mpdehaan** [comment]
This is already fixed on the development branch, FWIW, and will be included in the next dot release.

**Comment by siboulet** [comment]
#7559
