### ISSUE TITLE
Set some environment variables before calling dynamic inventory script

### ISSUE THREAD

**Issue by rmt** [ansible/ansible#7622]
##### Issue Type:

Feature Idea
##### Ansible Version:

1.6.2
##### Environment:

CentOS 5 & 6
##### Summary:

I'd like to see the environment variables **ANSIBLE_HOST_PATTERN** set for ad-hoc ansible calls and **ANSIBLE_PLAYBOOK** set for playbooks before the inventory script is called.

Today we use wrapper scripts that set these environment variables.  It would be nice to have them available as a standard feature.

The purpose is to allow smarter inventory scripts that can better know the requirements of the current call/playbook and can tailor their output to the required host patterns, as well as providing invaluable sanity checks (eg. ensure playbooks don't set overly broad host patterns, or mix & match unrelated groups of hosts).

As a real life example: exporting all of our hosts in JSON format with groups for all the top-level host tags and including host vars generates almost 20MB worth of JSON (plus unnecessary network traffic and load on our databases).  Caching is not a reasonable option for us, as most playbooks are triggered after events which have invalidated the cache.  By using the above environment variables, our inventory script outputs around 100K for our largest applications & playbooks, and it runs _significantly_ faster.

**Comment by mpdehaan** [comment]
Ansible doesn't set environment variables based on user inputs.  It does occasionally set some magic variables, that start with "ansible_".

Inventory scripts can be fed parameters by setting environmental parameters.

For instance, if you have a database and you want to select a customer, you might do

INVENTORY_CUSTOMER=1234 ansible-playbook [-i inventory] ...

In any case, there are multiple ways to solve this problem and supply input to your inventory script.  Please stop by ansible-devel if you'd like to discuss further.

**Comment by rmt** [comment]
If it's ok, I'd prefer to continue here instead of splitting the conversation.

Given our requirement to dynamically generate a subset of our inventory based on the specific host patterns used in the playbook, it sounds like our current approach, whereby a wrapper script sets environment variables and the inventory script parses the playbook to limit the hosts returned from our CMDB, is the recommended approach?

Or can you recommend a better approach for our situation?

For the record: in playbooks we use specially formatted comments to map group names to (our) inventory queries. eg. "#group# myapp_staging_london: app=myapp,role=web,env=st,dc=lon01,state=up". For ad-hoc calls, the inventory query is passed directly on the command line.

_SCRATCH THAT: I'm not expecting a response here_
