### ISSUE TITLE
Incorrect docs for ec2_elb_lb, scheme and subnet options

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#7631]
##### Issue Type:

Incorrect Docs
##### Ansible Version:

1.6.x
##### Environment:

N/A
##### Summary:

The docs state that the scheme and subnet are available in the ec2_elb_lb module in Ansible 1.6.  I see no reference to those options in the code in 1.6, 1.6.1, 1.6.2, but it is in devel.  Docs string in module on devel branch do not show a "version added" string for "scheme" and state that "subnet" was added in 1.6.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by jimi-c** [comment]
The above patch should correct this issue. Thanks!
