### ISSUE TITLE
'future annotations' requires python 3.7 or lsater

### ISSUE THREAD

**Issue by nkadel** [ansible/ansible#76348]
### Summary

ansible-core 2.12 includes 'future annotations' syntax, which is not compatible with python 3.6, the base python 3 of RHEL 7 and RHEL 8. python 3.8 is available from 'AppStream' for RHEL 8, but is not even available in EPEL for RHEL 7. It is available as an SCL package for RHEL 7, but building up the dependencies for the updated ansible core becomes much more painful that way.

### Issue Type

Bug Report

### Component Name

ansible-core

### Ansible Version

```console
ansible-core-2.12.0.tar.gz
```

### Configuration

```console
Irrelevant, issue is at compilation time on RHEL 7 and RHEL 8
```

### OS / Environment

RHEL 7 and RHEL 8, also CentOS 7 and CentOs 8

### Steps to Reproduce

Attempt to build mock-core-2.12.0 from Fedora SRPM on RHEL 7 host, with dependencies built from https://github.com/nkadel/ansiblerepo/ .

### Expected Results

Successful SRPM build on RHEL 7.

### Actual Results

```console
byte-compiling /builddir/build/BUILDROOT/ansible-core-2.12.0-1.el7.x86_64/usr/lib/pytho
n3.6/site-packages/ansible_test/_internal/cli/parsers/host_config_parsers.py to host_co
nfig_parsers.cpython-36.pyc
  File "/usr/lib/python3.6/site-packages/ansible/playbook/play_context.py", line 202
    if (attr_val := getattr(task, attr, None)) is not None:
                 ^
SyntaxError: invalid syntax
  File "/usr/lib/python3.6/site-packages/ansible/utils/_junit_xml.py", line 5
SyntaxError: future feature annotations is not defined
  File "/usr/lib/python3.6/site-packages/ansible_test/_i
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by nkadel** [comment]
Since RHEL 8  and CentOS 8 are being rejected by many developers and companies, it would make sense to either port python 3.8 to RHEL 7 more gracefully or discard this incompatible syntax in ansible-core.

**Comment by mkrizek** [comment]
ansible-core 2.12 requires Python 3.8+ on the control node as stated in https://github.com/ansible/ansible/blob/stable-2.12/changelogs/CHANGELOG-v2.12.rst#id3.

**Comment by nkadel** [comment]
So what is the plan for RPM based deployment? Discard RHEL 7 as being supporteD? And there are various setups that currently install a local ansible setup to apply configuration changes to "localhost". Will EPEL on RHEL 7 be limited to "ansible-2.9"? I admit to startlement that software supported by Red Hat directly, with the former "ansible.com" services and Ansible Tower in particular, will not be able to operate on RHEL 7. Is the incompatibility buying anything useful?

**Comment by sivel** [comment]
If you wish to install ansible-core 2.12 on RHEL7 you will be responsible for also installing Python 3.8.  SCLs may have Python 3.8 available, but I cannot attest to that, but it would also require you to build a custom RPM to rely on an use that SCL as the base.

RHEL7 is not Supported (capital S) as a control node for ansible-core 2.12+.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
