### ISSUE TITLE
Module homebrew_cask error: "msg: Error: Unknown command: cask"

### ISSUE THREAD

**Issue by Mayeu** [ansible/ansible#7637]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.2
##### Environment:

Running from Archlinux (up-to-date), managing Mac OS X 10.9
##### Summary:

Using the module `homebrew_cask` I get the following error on a clean Mac OS X:

```
failed: [xxxxx] => (item=firefox) => {"failed": true, "item": "firefox"}
msg: Error: Unknown command: cask
```

To make it work I had to add the following to my env: `PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"`.
##### Steps To Reproduce:
- Get a fresh Mac OS X installation
- Install Homebrew and Caskroom
- create a task like this:

```
- name: install caskroom application
  sudo: no                                                          
  homebrew_cask: name=firefox state=present
```
##### Expected Results:

```
ok: [xxxxx] => (item=firefox) => {"changed": false, "item": "firefox", "msg": "Cask already installed: firefox"}
```
##### Actual Results:

```
failed: [xxxxx] => (item=firefox) => {"failed": true, "item": "firefox"}
msg: Error: Unknown command: cask
```

Forcing the env (as describe in summary) solve this. So it seems that this module just assume some environment setup that are not the default in Mac OS X, and fail to acknowledge, document or warn about such modification.

**Comment by danieljaouen** [comment]
I think what's happening here is that Homebrew is searching your `PATH` for the executable `brew-cask.rb` (which is installed to `/usr/local/bin`).  If `/usr/local/bin` is not in your `PATH`, brew won't be able to find the cask executable.  The solution to this would be to ensure that `/usr/local/bin` is in your `PATH` before running the `homebrew_cask` module.

**Comment by jimbojsb** [comment]
+1

**Comment by utinajero** [comment]
+1 I'm having the same issue on ansible 1.6.6. I do have /usr/local/bin in my $PATH.

**Comment by danieljaouen** [comment]
I can guarantee that this is a `PATH` issue.  Maybe your local machine (i.e., the machine on which you run the `ansible-playbook` command) has a different `PATH` variable than the remote machine (i.e., the machine on which `ansible-playbook`'s tasks are run).

This can occur, for example, if you're running iTerm2 with a non-login shell and that shell's `PATH` differs from the default shell's `PATH`.  This was the case for me as I run the fish shell locally but my login shell is bash, so I had to export a modified `PATH` variable in my `~/.bashrc`.

**Comment by danieljaouen** [comment]
From what I can tell, @dedalusj's patch would fix this issue by automatically prefixing `/usr/local/bin` onto the `PATH` in all cases.  So if any Ansible maintainer is reading this, that can be safely merged in.

**Comment by utinajero** [comment]
Thanks for your help @danieljaouen. I copied my `~/.bash_profile` into my `~/.bashrc` and its working now.
