### ISSUE TITLE
Introduce a Galaxyfile to manage dependencies in an isolated file

### ISSUE THREAD

**Issue by nickjj** [ansible/ansible#7643]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.5+
##### Environment:

N/A
##### Summary:

I would really like to see `ansible-galaxy install` work without having to supply a massive list of roles. It would be interesting if it tried to detect a `Galaxyfile` in the directory it was ran from but also allowed you to supply a path to a `Galaxyfile` with an `-i` flag or whatever makes sense.

I ended up having to implement the most basic version of this to fulfill the needs of a tool I'm writing which generates an ansible play book and inventory.

This is the `Galaxyfile`:
https://github.com/nickjj/orats/blob/master/lib/orats/templates/includes/Galaxyfile

Parsing it is also trivial because I didn't try to make the file nice. It just replaces newlines with spaces and then I send the whole command to `ansible-galaxy install`.

It would be great if a standard/core `Galaxyfile` existed so everyone uses the same format.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by jimi-c** [comment]
This already works. You can simply pass a file to `ansible-galaxy install` with the `-r ROLES_FILE` option. The format is exactly as you've noted: `username.rolename[,version]`. In fact, here's the output using your file exactly:

<pre>
# ansible-galaxy install -r test_rolefile.txt 
 downloading role 'user', owned by nickjj
 - downloading role from https://github.com/nickjj/ansible-user/archive/v0.1.0.tar.gz
 - extracting nickjj.user to /etc/ansible/roles/nickjj.user
nickjj.user was installed successfully
 downloading role 'security', owned by nickjj
 - downloading role from https://github.com/nickjj/ansible-security/archive/v0.1.1.tar.gz
 - extracting nickjj.security to /etc/ansible/roles/nickjj.security
nickjj.security was installed successfully
 downloading role 'postgres', owned by nickjj
 - downloading role from https://github.com/nickjj/ansible-postgres/archive/v0.1.1.tar.gz
 - extracting nickjj.postgres to /etc/ansible/roles/nickjj.postgres
nickjj.postgres was installed successfully
 downloading role 'ruby', owned by nickjj
 - downloading role from https://github.com/nickjj/ansible-ruby/archive/v0.1.3.tar.gz
 - extracting nickjj.ruby to /etc/ansible/roles/nickjj.ruby
nickjj.ruby was installed successfully
 downloading role 'nodejs', owned by nickjj
 - downloading role from https://github.com/nickjj/ansible-nodejs/archive/v0.1.1.tar.gz
 - extracting nickjj.nodejs to /etc/ansible/roles/nickjj.nodejs
nickjj.nodejs was installed successfully
 downloading role 'nginx', owned by nickjj
 - downloading role from https://github.com/nickjj/ansible-nginx/archive/v0.1.3.tar.gz
 - extracting nickjj.nginx to /etc/ansible/roles/nickjj.nginx
nickjj.nginx was installed successfully
 downloading role 'rails', owned by nickjj
 - downloading role from https://github.com/nickjj/ansible-rails/archive/v0.1.9.tar.gz
 - extracting nickjj.rails to /etc/ansible/roles/nickjj.rails
nickjj.rails was installed successfully
 downloading role 'whenever', owned by nickjj
 - downloading role from https://github.com/nickjj/ansible-whenever/archive/v0.1.0.tar.gz
 - extracting nickjj.whenever to /etc/ansible/roles/nickjj.whenever
nickjj.whenever was installed successfully
 downloading role 'pumacorn', owned by nickjj
 - downloading role from https://github.com/nickjj/ansible-pumacorn/archive/v0.1.1.tar.gz
 - extracting nickjj.pumacorn to /etc/ansible/roles/nickjj.pumacorn
nickjj.pumacorn was installed successfully
 downloading role 'sidekiq', owned by nickjj
 - downloading role from https://github.com/nickjj/ansible-sidekiq/archive/v0.1.1.tar.gz
 - extracting nickjj.sidekiq to /etc/ansible/roles/nickjj.sidekiq
nickjj.sidekiq was installed successfully
 downloading role 'monit', owned by nickjj
 - downloading role from https://github.com/nickjj/ansible-monit/archive/v0.1.2.tar.gz
 - extracting nickjj.monit to /etc/ansible/roles/nickjj.monit
nickjj.monit was installed successfully
 downloading role 'redis', owned by DavidWittman
 no version specified, installing master
 - downloading role from https://github.com/DavidWittman/ansible-redis/archive/master.tar.gz
 - extracting DavidWittman.redis to /etc/ansible/roles/DavidWittman.redis
DavidWittman.redis was installed successfully
</pre>

Thanks, and let us know if you have any further questions regarding this!

**Comment by nickjj** [comment]
Interesting, I can't believe I missed that in the docs.
