### ISSUE TITLE
svr4pkg module: Doesn't properly report failures.

### ISSUE THREAD

**Issue by yeroc** [ansible/ansible#7645]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel 6bc056e012) last updated 2014/06/02 14:42:33 (GMT -600)
##### Environment:

Solaris 10/11
##### Summary:

pkgadd failures aren't properly reported as errors but instead the status returned is "changed".
##### Steps To Reproduce:

Given a trivial task with invalid parameters:

```
- name: Install Non-Existant Package
  svr4pkg: name="somename" src="" state=present
```
##### Expected Results:

The task should report a "failed" status.
##### Actual Results:

Actually the task reports a "changed" status:

```
changed: [dbload-solaris] => {"changed": true, "item": "", "name": "somename", "state": "present", "stderr": "pkgadd: ERROR: the path <> is invalid!\n"}
```

**Comment by jimi-c** [comment]
The above PR was merged in, and should correct this. Please let us know if you continue to see any problems related to this issue. Thanks!
