### ISSUE TITLE
ansible-galaxy collection list - option list missing

### ISSUE THREAD

**Issue by Mixer9** [ansible/ansible#76497]
### Summary

When trying to list ansible galaxy collections I get an error saying that list isn't a valid option. How am I supposed to list what I have without it?  The docs say it should work.

### Issue Type

Bug Report

### Component Name

ansible-galaxy

### Ansible Version

```console
$ ansible --version
ansible 2.9.23
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'timer']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 180
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

### OS / Environment

RHEL 7

### Steps to Reproduce

"-bash-4.2$ ansible-galaxy collection list
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: u'list' (choose from 'init', 'build', 'publish', 'install')"

### Expected Results

I expected to get a list of galaxy collections installed

### Actual Results

```console
Error saying that list wasn't an option.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by jborean93** [comment]
The `list` sub command for `ansible-galaxy collection` was added in Ansible 2.10 whereas your version indicates you are running with 2.9.x. See the version specific docs for 2.9 to see what commands are available there https://docs.ansible.com/ansible/2.9/cli/ansible-galaxy.html.

Unfortunately at your version there is no way to list the collections installed using `ansible-galaxy` and you need to manually enumerate the directories to figure out what is there. One of our devs came up with a basic gist that will also work for people still on older Ansible versions https://github.com/bcoca/std/blob/devel/list_collections.py.
