### ISSUE TITLE
Form Factor check in setup module needs guard around index

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#765]
List index out of range reported on:

   # From smolt and DMI spec
FORM_FACTOR = [ "Unknown", "Other", "Unknown", "Desktop",
"Low Profile Desktop", "Pizza Box", "Mini Tower", "Tower",
"Portable", "Laptop", "Notebook", "Hand Held", "Docking Station",
"All In One", "Sub Notebook", "Space-saving", "Lunch Box",
"Main Server Chassis", "Expansion Chassis", "Sub Chassis",
"Bus Expansion Chassis", "Peripheral Chassis", "RAID Chassis",
"Rack Mount Chassis", "Sealed-case PC", "Multi-system",
"CompactPCI", "AdvancedTCA" ]

If the form factor is not in the list, don't explode.

**Comment by mpdehaan** [comment]
Form factor was 28, should catch the list index being out of range and set to unknown and add the key for 28 if known.

**Comment by sfromm** [comment]
Are you working on a fix for this?  If not, I can take it.

**Comment by mpdehaan** [comment]
Not now, that would be great!
