### ISSUE TITLE
Empty "vars:" section prevent to set a dynamic host target in an included playbook

### ISSUE THREAD

**Issue by sterfield** [ansible/ansible#7658]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.1
##### Environment:

Debian Wheezy
##### Summary:

When using a include playbook, and passing variables to it, if one of your variable is used to provide dynamic "hosts", and you provide an empty "vars:" section in the playbook having a dynamic "hosts" target, then ansible will failed.
##### Steps To Reproduce:
- create a first playbook:

```

---
- include: showing.yml
  vars:
    target: "127.0.0.1"
    my_var: "Show me!"
```
- create a second playbook:

```

---
- hosts: "{{ target }}"
  connection: local
  vars:
  tasks:
    - debug: msg="{{ my_var }}"
```
- launch the first playbook:

```
$> ansible-playbook -i ./inventory setting.yml
```
##### Expected Results:

The ansible execution expand the 'target' variable sent by the first playbook, and execute the content of the second playbook on each host / groups pointed by the 'target' variable
##### Actual Results:

The ansible execution of the second playbook will not happen, showing a "skipping: no hosts matched"

```
PLAY [{{target}}] ************************************************************* 
skipping: no hosts matched

PLAY RECAP ******************************************************************** 
```
##### Additional information

Now, that's the funny part. IF you remove the empty "vars:" section in the second playbook, it'll work as expected:

```

---
- hosts: "{{ target }}"
  connection: local
  tasks:
    - debug: msg="{{ my_var }}"
```

```
PLAY [127.0.0.1] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [debug msg="Show me!"] ************************************************** 
ok: [127.0.0.1] => {
    "msg": "Show me!"
}

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   
```

Also, having a non-empty "vars:" section solve the issue.

**Comment by jimi-c** [comment]
I have merged in the above patch, which corrects this issue based on your example. If you continue seeing any problems related to this error, please let us know. Thanks!
