### ISSUE TITLE
apt module add upgrade?

### ISSUE THREAD

**Issue by preyk-work** [ansible/ansible#766]
Hi,

would it be possible to enhance the apt module to be able to do apt-get upgrade? noninteractive is already there, perhaps -y could be added and it should be ok mostly. or do you expect some other problems? (people should know what they deal with by using this).

**Comment by mpdehaan** [comment]
This is state=latest and is already supported

**Comment by preyk-work** [comment]
sorry, i meant globally

**Comment by mpdehaan** [comment]
command or shell module can already do this.

**Comment by RaymiiOrg** [comment]
@mpdehaan Now ansible has yum, apt and pacman, would it be possible to implement something to do a full upgrade? `$pkg_mgr` package=all state=latest?

**Comment by mpdehaan** [comment]
It would have to be done for each individual module but I'm not opposed to
'all' being special.

Make it so!

**Comment by RaymiiOrg** [comment]
Not exactly the 'all' package, but an upgrade option to the module (Pull request #1973).
