### ISSUE TITLE
Template language in strings is wrongly detected as YAML

### ISSUE THREAD

**Issue by eproxus** [ansible/ansible#7671]
##### Issue Type:

Bug Report
##### Ansible Version:

`ansible 1.6.2`
##### Environment:

OS X 10.9.3
##### Summary:

When using template language in strings, Ansible wrongly detect it as YAML syntax and issues an error instead of creating a new string (only tested in `debug` tasks).
##### Steps To Reproduce:

```
- debug: msg="{{var}}: test"
```
##### Expected Results:

```
TASK: [role | debug msg="{{var}}: test"] ***
ok: [host] => {
    "item": "",
    "msg": "value_of_var: test"
}
```
##### Actual Results:

```
ERROR: Syntax Error while loading YAML script, /Users/user/ansible/roles/role/tasks/main.yml
Note: The error may actually appear before this position: line 1, column 22


- debug: msg="{{var}}: test"
                     ^
This one looks easy to fix. YAML thought it was looking for the start of a
hash/dictionary and was confused to see a second "{".  Most likely this was
meant to be an ansible template evaluation instead, so we have to give the
parser a small hint that we wanted a string instead. The solution here is to
just quote the entire value.

[...output capped]
```

**Comment by jimi-c** [comment]
This is not a bug, it's a YAML parsing issue. YAML does not like to have colons in the middle of lines that are not fully quoted. The solution is to fully quote the entire line, as the error message mentions:

<pre>
- debug: 'msg="{{var}}: test"'
</pre> 

If you have any further questions regarding this, please let us know. Thanks!

**Comment by eproxus** [comment]
Ah, missed that part. Thanks for pointing it out.
