### ISSUE TITLE
Key auth on paramiko 2.9.0+ fails to connect to older hosts

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible#76737]
### Summary

Connecting via ssh key-based auth to older hosts that are not configured for rsa-sha2 algorithms and/or `server-sig-algs` extension  fails with `Authentication failed` when using paramiko 2.9.0+, but works on previous versions of paramiko.

This includes the vyos and ios test VMs used by ansible-test's networking, but would apply to any host with an older ssh server and/or config.

https://www.paramiko.org/changelog.html#2.9.0 calls out that support for rsa-sha2 algorithms was added, and that they need to be disabled for older hosts that don't support either the new algorithms or the `server-sig-algs` extension (to tell it so). A further review of the docs and code shows that only the first algorithm is tried when the extension is not supported.

### Issue Type

Bug Report

### Component Name

paramiko_ssh

### Ansible Version

```console
$ ansible --version
(all-> 2.12.1 with paramiko 2.9.0+)
```

### Configuration

```console
NA
```

### OS / Environment

NA

### Steps to Reproduce

Use the paramiko_ssh connection to connect to a host with sha1 publickey auth that is not configured to accept sha2 keys and does not support the `server-sig-algs` extension (eg, AWS vyos, ios AMIs as of 2022-01-10).

### Expected Results

Successful connection

### Actual Results

```console
`Failed to authenticate: Authentication failed.`
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by nitzmahone** [comment]
Paramiko's `SSHClient` added support for `disabled_algorithms` back in their ~2.6 release, which can be manipulated to allow new versions of paramiko to connect to hosts so configured, but the `paramiko_ssh` connection plugin doesn't currently have a way to pass it in. The dict that needs to be passed to allow ansible-test's rsa-sha1 keys to connect successfully to vyos is `disabled_algorithms=dict(pubkeys=['rsa-sha2-256', 'rsa-sha2-512'])`, but non-YAML inventories can't easily build dictionaries.

Perhaps we'd need one list-type arg for each controllable algorithm type, eg `disabled_kex_algorithms`, `disabled_pubkey_algorithms`, etc. This is still quite brittle to further changes in paramiko, since the docs say `When the server does not send server-sig-algs, Paramiko will attempt the first algorithm in the above list.`, meaning one must have a priori knowledge of the order of algorithms tried for a given paramiko version, and disable everything *above* the one that actually needs to be used.

**Comment by alex-pimperton** [comment]
Is there any manual work-around for this or is it waiting a decision on the best way to go for a bugfix? (Assuming I can't update the client cipher support)

**Comment by sivel** [comment]
The workaround is to downgrade to an older paramiko.  As of now, there is no active work being done to add a work around in the paramiko plugin.  Assuming that code changes are made to the paramiko plugin to support this, it is likely to only show up in the next major version, which could very well be 2.14 at this point.

**Comment by alex-pimperton** [comment]
Thanks, this is an AWX environment so I’ll raise it there. 

I’m guessing it will need a custom EE with a downgraded version of Paramiko.

**Comment by sivel** [comment]
> Is there a plan to push workaround for this (limit paramiko version), until paramiko ssh logic itself is rewritten?

We do not have a hard dependency on paramiko in ansible-core.  If it is being auto installed, that would indicate that the package you are using has decided to specify it as a dependency.

It will be up to users to specify a set of constraints that match their requirements on a specific version of paramiko.

**Comment by eleksis** [comment]
Ah, i see..it's a requirement of cisco.ios collection. And they already downgraded paramiko in latest version. Thanks for reply.
