### ISSUE TITLE
Cannot delegate_to with connection: docker

### ISSUE THREAD

**Issue by singpolyma** [ansible/ansible#76778]
### Summary

Trying to use delegate_to with `connection: docker` produces an error.  Removing the delegate_to it works fine.

### Issue Type

Bug Report

### Component Name

delegate_to

### Ansible Version

```console
$ ansible --version

ansible 2.10.8
  config file = None
  configured module search path = ['/home/singpolyma/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

```
$ cat /etc/issue
Ubuntu 18.04.6 LTS \n \l

$ uname -a
Linux REDACTED 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Steps to Reproduce

```yaml (paste below)
- become: true
  hosts: all
  tasks:
  - apt:
      update_cache: true
  - command:
      cmd: echo hai
    delegate_to: "container-name"
    connection: docker
```

### Expected Results

It should run a command inside a container.

### Actual Results

```console
UNREACHABLE! => {"changed": false, "msg": "Failed to create temporary directory.In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp `\"&& mkdir \"` echo ~/.ansible/tmp/ansible-tmp-1642452724.8971472-123454-5127813474037 `\" && echo ansible-tmp-1642452724.8971472-123454-5127813474037=\"` echo ~/.ansible/tmp/ansible-tmp-1642452724.8971472-123454-5127813474037 `\" ), exited with result 1", "unreachable": true}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by bcoca** [comment]
does the host you delegate to already have `ansible_connection` set?

**Comment by singpolyma** [comment]
No, but I have realized that maybe it is trying to connect to docker on my local machine where I run ansible instead of the docker on the remote host, and maybe that's my issue?  Using a non-existent container name gives me the same error.

**Comment by bcoca** [comment]
the 'docker' connection plugin assumes the host running ansible contains the docker instances

**Comment by singpolyma** [comment]
@bcoca Yeah, ok, it seems that's the problem.  Not a very clear error message when the problem is "container not found" ...

**Comment by bcoca** [comment]
The error is correct, the plugin does not handle remotes. In most cases this should reflect that the container is down/does not exist/is misspelled, not that it is running on the wrong host. 

In any case, that plugin does not reside in this repo anymore https://github.com/ansible-collections/community.docker/issues

**Comment by singpolyma** [comment]
Sure, just that "cannot create temporary directory" does not really indicate to me that the container is not found.

In any case, you're right that this is the wrong repo anyway.  Sorry about that.
