### ISSUE TITLE
connection_details.rst uses ansible_user and remote_user interchangeably without explaining the differences (if any) between these settings

### ISSUE THREAD

**Issue by m8ram** [ansible/ansible#76786]
### Summary

The examples in  connection_details.rst  in the section Setting a remote user use a mix of `remote_user` and `ansible_user`.
It does not explain why it uses one or the other.

I couldn't find any official reference saying that they are interchangeable or not. Some reports on StackOverlow indicate that there might be subtle differences. E.g. [Ansible remote_user vs ansible_user](https://stackoverflow.com/questions/36668756/ansible-remote-user-vs-ansible-user).

I believe a lot of people would like to know which of these to use or when to use one or the other.

### Issue Type

Documentation Report

### Component Name

ansible/docs/docsite/rst/user_guide/connection_details.rst

### Ansible Version

```console
n/a (using 2.9)
```

### Configuration

```console
n/a
```

### OS / Environment

n/a (RHEL 8)

### Additional Information

Having official documentation on this will allow all users to make an informed decision.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
fwiw, this is mostly documented at https://docs.ansible.com/ansible-core/2.12/collections/ansible/builtin/ssh_connection.html#parameter-remote_user

They are the same option, just with different names depending on if you use it in a config file, as a play keyword, or as a variable.

This page then describes precedence:

https://docs.ansible.com/ansible-core/2.12/reference_appendices/general_precedence.html

1. Configuration settings
2. Command-line options
3. Playbook keywords
4. Variables

Where variables has the highest precedence.
