### ISSUE TITLE
Copy Module fails because of shlex on an unicode string

### ISSUE THREAD

**Issue by gottwald** [ansible/ansible#768]
I have a strange error with the actual devel branch copy module.

Ansible Job in the playbook looks like this:

```
- name: Install Motd
  action: copy src=../../../_global/files/etc_motd.tail dest=/etc/motd.tail owner=root group=root mode=644
```

It fails with this message:

```
failed: [deploytest.mrz.tfag.de] => {"failed": true, "module": "copy", "msg": "src and dest are required"}
```

To debug this i inserted a few print statements in lib/ansible/runner/**init**.py and lib/ansible/utils.py.

The return value of utils.parsekv looks strange (omitted the underscore in method name because of github markdown) :

```
['s\x00r\x00c\x00=\x00.\x00.\x00/\x00.\x00.\x00/\x00.\x00.\x00/\x00_\x00g\x00l\x00o\x00b\x00a\x00l\x00/\x00f\x00i\x00l\x00e\x00s\x00/\x00e\x00t\x00c\x00_\x00m\x00o\x00t\x00d\x00.\x00t\x00a\x00i\x00l\x00', '\x00d\x00e\x00s\x00t\x00=\x00/\x00e\x00t\x00c\x00/\x00m\x00o\x00t\x00d\x00.\x00t\x00a\x00i\x00l\x00', '\x00o\x00w\x00n\x00e\x00r\x00=\x00r\x00o\x00o\x00t\x00', '\x00g\x00r\x00o\x00u\x00p\x00=\x00r\x00o\x00o\x00t\x00', '\x00m\x00o\x00d\x00e\x00=\x006\x004\x004\x00']
```

It's a unicode String and below python 2.7.3 shlex cannot deal with unicode.

If i convert it to string or ASCII with setting the variable by hand then everything works fine.

But I have really no clue how the self.module_args variable becomes unicode.

Anyone an Idea?

**Comment by mpdehaan** [comment]
I've reverted an offending commit, pull again and you should be good
