### ISSUE TITLE
Clarify namespace selection and new collection requests

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#76828]
### Summary

Based on a discussion in the Ansible community channel, we should clarify documentation to tighten up instructions for contributors looking to create their first collections.

Some items that came up in the thread:

- How to reserve a namespace.
- How to choose a 'good' namespace
- Where to host the collection source (in ansible-collections, in a corp github, etc)

This is exacerbated by the fact we have collection contributor docs in multiple places. We are focusing on bringing those docs into one set of guides to help with this.
- 

### Issue Type

Documentation Report

### Component Name

https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/community/collection_development_process.rst

### Ansible Version

```console
$ ansible --version
5
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Fedora 34

### Additional Information

This will make the job easier for new collection contributors.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by jborean93** [comment]
@samccann is this still something that still needs to be addressed or can the issue be closed?

**Comment by samccann** [comment]
@jborean93 yes we do still need this level of detail in the docs.

In general, we need to port over the docs still on ansible-collections/overview, but the naming stuff is covered - https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#naming and needs to be in our docs.

**Comment by samccann** [comment]
Duplicate of https://github.com/ansible/ansible/issues/60282
