### ISSUE TITLE
Can't install on Win7 via pip - Long Path error

### ISSUE THREAD

**Issue by mrx23dot** [ansible/ansible#76838]
### Summary

Could we keep path names short? 
Also path seperators seems to be mixed, suggested to do os.path.abspath() on them.

`pip install ansible`
Collecting ansible
  Downloading ansible-4.10.0.tar.gz (36.8 MB)
     |████████████████████████████████| 36.8 MB 473 kB/s

```
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\me75467\\AppData\\Local\\Temp\\pip-install-qewllma2\\ansible_d7ca3162bd034b6ebf06e7728a0f3e08\\ansible_collections/amazon/aws/tests/unit/plugins/modules/placebo_recordings/cloudformation/client_request_token_s3_stack/cloudformation.DescribeStackEvents_1.json'
HINT: This error might have occurred since this system does not have Windows Long Path support enabled. You can find information on how to enable this at https://pip.pypa.io/warnings/enable-long-paths
```

I have never ever had this problem, but installed thousands of pip libs.

### Issue Type

Bug Report

### Component Name

pip

### Ansible Version

```console
$ ansible --version
4.10.0, couldn't finish install
```

### Configuration

```console
$ ansible-config dump --only-changed

4.10.0, couldn't finish install
```

### OS / Environment

- Python 3.6.8 x64
- pip 21.3.1
- Win7 x64

### Steps to Reproduce

pip install ansible

### Expected Results

It should install effortlessly.

### Actual Results

```console
Fails with Windows Long Path error, see above.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
Per the error, you must enable long paths https://pip.pypa.io/warnings/enable-long-paths

Additionally, Windows is not supported as a control node, so pip installing ansible on Windows is an unsupported operation.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by mrx23dot** [comment]
Yeah that's for win10, win7 cannot have >255 chars in path.
I started a discussion for this in mailing list.
Cheers
