### ISSUE TITLE
FreeBSD ports fail to install

### ISSUE THREAD

**Issue by francisco1844** [ansible/ansible#7691]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel aaa16acdf1) last updated 2014/06/07 16:34:23 (GMT +000)
##### Environment:

Running ansible from ubuntu and managing FreeBSD 10 machine.
##### Summary:

Installing FreeBSD ports causes the program to crash.
So far has failed while trying to install nginx and apache 2.4
##### Steps To Reproduce:

portinstall: name=www/nginx
##### Expected Results:

Port should be installed.
##### Actual Results:

failed: [t1] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1402158888.34-20696508689981/portinstall", line 1425, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1402158888.34-20696508689981/portinstall", line 200, in main
    install_packages(module, pkgs, p["use_packages"])
  File "/root/.ansible/tmp/ansible-tmp-1402158888.34-20696508689981/portinstall", line 170, in install_packages
    matches = matching_packages(module, package)
  File "/root/.ansible/tmp/ansible-tmp-1402158888.34-20696508689981/portinstall", line 104, in matching_packages
    occurrences = int(parts[0])
ValueError: invalid literal for int() with base 10: 'www/nginx'

FATAL: all hosts have already failed -- aborting

**Comment by francisco1844** [comment]
Issue confirmed now with a third port.. postfix.
So far every port I have tried to install has failed: apache 2.4, nginx and postfix

Installation from pkg works though.

**Comment by weirdbricks** [comment]
I believe I am running into the same issue on Ansible 1.6.3 - in my case I am running it on FreeBSD 10 and managing another FreeBSD 10 host

**Command to repro:**
 ansible all -m portinstall -a "name=sysutils/moosefs-chunkserver state=present"

**Error:**
192.168.2.16 | FAILED >> {
    "failed": true,
    "msg": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1403615219.1-62299228992420/portinstall\", line 1425, in <module>\r\n    main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1403615219.1-62299228992420/portinstall\", line 200, in main\r\n    install_packages(module, pkgs, p[\"use_packages\"])\r\n  File \"/root/.ansible/tmp/ansible-tmp-1403615219.1-62299228992420/portinstall\", line 170, in install_packages\r\n    matches = matching_packages(module, package)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1403615219.1-62299228992420/portinstall\", line 104, in matching_packages\r\n    occurrences = int(parts[0])\r\nValueError: invalid literal for int() with base 10: 'sysutils/moosefs-chunkserver'\r\n",
    "parsed": false
}

**Comment by francisco1844** [comment]
Sadly because ports install is "just a module" the error was categorized as P3.. even if it makes ansible nearly unusable in FreeBSD.

**Comment by bcoca** [comment]
I believe that is because you have the alternative of using pkgng​, from
the code this looks like an issue when trying to get package version, which
has always been a 'fun' problem on freebsd.

I'll try to carve out some time this weekend, I'll probably be able to fix
it.

**Comment by francisco1844** [comment]
Pkgng is not an option for packages where one needs to change the default configurations.
In my case, that usually means the core ports that I plan to run in a machine.. apache, postgresql, postfix, mysql, php.

**Comment by bcoca** [comment]
I understand that, but it is not immediately obvious to those not used to
using FreeBSD​, which is why i think the priority is low on this ticket.

**Comment by sidred** [comment]
See #7929 for fix. The shell piping needs use_unsafe_shell set to True

**Comment by jimi-c** [comment]
The above #7942 has been merged, and this issue should be resolved. Please let us know if you continue seeing any problems related to this. Thanks!
