### ISSUE TITLE
zfs module incompatible with new "share.nfs" and "share.smb" properties

### ISSUE THREAD

**Issue by toddmowen** [ansible/ansible#7696]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.2 
##### Environment:

Managing Solaris 11.1.
##### Summary:

The version of ZFS released with Solaris 11.1 replaced the "sharenfs" and "sharesmb" properties with a hierarchy of share.\* properties (see [docs](http://docs.oracle.com/cd/E26502_01/html/E29007/gayne.html)). This breaks Ansible's zfs module.
##### Steps To Reproduce:

```
tasks:
- name: Setup /export/opencws as ZFS filesystem
  zfs: name=rpool/export/opencsw state=present sharenfs=on
```
##### Expected Results:

First run: create the specified ZFS filesystem, with NFS sharing enabled.

Second run: do nothing.
##### Actual Results:

First run: as expected.

Second run:

```
invalid output was: Traceback (most recent call last):
  File "/tmp/ansible-tmp-1402197494.77-156175913445546/zfs", line 1617, in <module>
    main()
  File "/tmp/ansible-tmp-1402197494.77-156175913445546/zfs", line 398, in main
    zfs.set_properties_if_changed()
  File "/tmp/ansible-tmp-1402197494.77-156175913445546/zfs", line 306, in set_properties_if_changed
    if current_properties[prop] != value:
KeyError: 'sharenfs'
```
##### Explanation:

With the new version of ZFS (specificially, pools running pool version 34 or higher), filesystem creation continues to work correctly because "sharenfs" and "sharesmb" are aliased to "share.nfs" and "share.smb" respectively.

But rerunning the task (expected to make no changes) fails because the Ansible module expects to find the property "sharenfs" in the output of "zfs get -H all", which actually looks like this:

```
...
rpool/export/opencsw    shadow  none    -
rpool/export/opencsw    share.* ...     local
rpool/export/opencsw    snapdir hidden  default
...
```

Notice that the actual value of share.nfs isn't even displayed. It can be obtained by running "zfs get -H share.all".

**Comment by toddmowen** [comment]
A possible fix would be to look for "share.*" in the output of `zfs get all`. If found, run `zfs get share.all` and merge the output into the dictionary.

**Comment by jimi-c** [comment]
@toddmowen would you like to work on that? Just send us a PR if so, and reference this issue in it.

**Comment by jimi-c** [comment]
The above pull request has been merged in, so this should now be resolved. Please let us know if you continue seeing any problems in regard to this issue. Thanks!
