### ISSUE TITLE
Lazy/Immadiate variable evaluation and Special Escaping

### ISSUE THREAD

**Issue by Roxyrob** [ansible/ansible#76999]
### Summary

Lazy/Immadiate `hidden` Evaluation of variables (set_fact, loop, others?) and lack of simple constant string type make very difficult and costly manage string that simply are to be leave as are.

### Issue Type

Bug Report

### Component Name

Templating

### Ansible Version

```console
ansible [core 2.12.2]
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
DEFAULT_LOAD_CALLBACK_PLUGINS = True
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = yaml
HOST_KEY_CHECKING = False
```

### OS / Environment

CentOS 8

### Steps to Reproduce

I need to save on a system a string containing special characters like brackets ({{ }}), point (.) and single quotes ('), leaving that as is. Lazy Evaluation for variables help me so debug message for `case1 (Lazy Evaluation)` show that classic/generic escaping sequence works fine I 

<pre>
---
- name: Test
  hosts: localhost
  gather_facts: False

  vars:
    ### Classic/Generic Lazy Evaluation variable
    ldap_cfg:
      ldapad:
        group_filter: "{{ '{{.UserDN}}' }}"

  tasks:
    - name: case1 (Lazy Evaluation)
      debug:
        msg: "{{ ldap_cfg.ldapad.group_filter }}"

<b>running playbook returns</b>
TASK [Case1 (Lazy Evaluation)]        ******************************************************************************************************
ok: [localhost] =>
  <b>msg: '{{.UserDN}}'</b>      <== (OK)
</pre>

The issue start using a **loop** (also set_fact will do tha same Immediate Evaluation):

<pre>
---
- name: Test
  hosts: localhost
  gather_facts: False

  vars:
    ### Classic/Generic Lazy Evaluation variable
    ldap_cfg:
      ldapad:
        group_filter: "{{ '{{.UserDN}}' }}"

  tasks:
    - name: case2 (Lazy Evaluation + loop)
      debug:
        msg: "{{ item_ldap.value.group_filter }}"
      loop: "{{ ldap_cfg| dict2items }}"
      loop_control:
        loop_var: item_ldap
</pre>

### Expected Results

<pre>
---
- name: Test
  hosts: localhost
  gather_facts: False

  vars:
    ### Classic/Generic Lazy Evaluation variable
    ldap_cfg:
      ldapad:
        group_filter: "{{ '{{.UserDN}}' }}"

  tasks:
    - name: case2 (Lazy Evaluation + loop)
      debug:
        msg: "{{ item_ldap.value.group_filter }}"
      loop: "{{ ldap_cfg| dict2items }}"
      loop_control:
        loop_var: item_ldap

<b>running playbook returns</b>
TASK [Case2 (Lazy Evaluation + loop)] ******************************************************************************************************
ok: [localhost] =>
  <b>msg: '{{.UserDN}}'</b>      <== (OK)
</pre>

### Actual Results

<pre>
<b>running playbook returns</b>
TASK [Case2 (Lazy Evaluation + loop)] ******************************************************************************************************
fatal: [localhost]: FAILED! =>
  msg: 'An unhandled exception occurred while templating ''{''key'': ''ldapad'', ''value'': {''group_filter'': ''{{.UserDN}}''}}''. Error was a <class ''ansible.errors.AnsibleError''>, original message: <b>template error while templating string: unexpected ''.''. String: {{.UserDN}}'</b>
</pre>
<br><br>

After some research and try cycles I found a working solution using **regex_replace filter** and **Literal/Folded YAML style** variable:

<pre>
---
- name: Test
  hosts: localhost
  gather_facts: False

  vars:
    ### Tricks with 2 level Lazy Evaluation variable
    ldap_cfg:
      ldapad:
        group_filter: |-
          {{ '{{ "{{.UserDN}}" }}'|regex_replace('"', "'") }}

  tasks:
    - debug:
        msg: "{{ ldap_cfg.ldapad.group_filter }}"

    - debug:
        msg: "{{ item_ldap.value.group_filter }}"
      loop: "{{ ldap_cfg| dict2items }}"
      loop_control:
        loop_var: item_ldap

<b>running playbook returns</b>
TASK [Case1 (Lazy Evaluation)]        ******************************************************************************************************
ok: [localhost] =>
  <b>msg: '{{ ''{{.UserDN}}'' }}'</b>

TASK [Case2 (Lazy Evaluation + loop)] ******************************************************************************************************
ok: [localhost] => (item={'key': 'ldapad', 'value': {'group_filter': '{{.UserDN}}'}}) =>
  <b>msg: '{{.UserDN}}'</b>
</pre>

This is tricky and works only for a 2 level of Lazy Evaluation variables but what about using a dict as generic configuration useb by different tasks/lpaybooks/roles that can introduce other level of evaluation ?

Shouldn’t this be considered a bug as Ansible should allow one to define a string unaltered throughout its lifecycle without static mechanisms like this and complex escaping sequence that could introduce errors as well ?

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by bcoca** [comment]
I don't think you're issue is about lazy evaluation but evaluation at all, your escaping 'survives' one round of evaluation but is stripped when 're evaluated'. Use `!unsafe` as a 'sticky' way to prevent evaluation and ensure it survives any number of evaluations.
```
  vars:
    ### Classic/Generic Lazy Evaluation variable
    ldap_cfg:
      ldapad:
        group_filter: !unsafe '{{.UserDN}}'
```

**Comment by Roxyrob** [comment]
Hi @bcoca,
that's not completely clear for me as it seem a mix. Initial variables assignment comply with Lazy Evaluation as per [Ansible Glossary - Lazy Evaluation](https://docs.ansible.com/ansible/latest/reference_appendices/glossary.html#term-Lazy-Evaluation) that tells:
<pre>
... Ansible evaluates any variables in playbooks content at the <b>last possible second.</b>
</pre>

then loop and set_fact [ansible.builtin.set_fact](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/set_fact_module.html#notes) (and probably others) make an `Immediate variables templating/evaluation`:

<pre>
...Unlike normal ‘lazy’ variables, the value gets evaluated and templated on assignment...
</pre>

 I see also many proposals to try to control explicitly this behavior (`!immediate`, `!nonlazy`, `!now`, etc.) to try to have more control on the way:
* #15439
* #10374

You're right about `!unsafe` [Advanced Syntax - Unsafe or raw strings](https://docs.ansible.com/ansible/latest/user_guide/playbooks_advanced_syntax.html#unsafe-or-raw-strings) but this only works on strings on which you have to completely avoid assignment not e.g. for mixed strings like this:

<pre>
hashi_vault_role: "GRANT ALL PRIVILEGES ON {{dbname}}.* TO '{{name}}' @'%';"
</pre>

where `'{{name}}'` is hashicorp vault specific syntax that should remain as is (`!unsafe`), but to `{{dbname}}` should be assigned a value dynamically not always under direct control (on `last second` surviving to N intermediate potentially out of control templating/immediate assignment ?).

As example I can define as below to allow lazy evaluation of the first one and survive one level of evaluation of the second one:

<pre>
hashi_vault_role: "GRANT ALL PRIVILEGES ON {{ dbname }}.* TO '{{'{{name}}'}}'@'%';"
</pre>

I find there is really weak control on all this, expecially thinking about variables travelling on the way inside roles code, etc. thinking about this I'm not sure if using such a strings construction is a good way. If so probably a more clear standards would be beneficial.

**Comment by bcoca** [comment]
- Ansible does wait till 'last second' in the context that it won't pass that variable to Jinja until it is referenced, once referenced there is no 'lazy' inside the Jinja2 expression (though some are working on that feature #56116 but this is hacking Jinja's inner workings)
- Lazy still does not handle your problem as it is 'non recursive evaluation' that you want, even in a Jinja lazy context, you would end up with this issue. We have limited the recursion somewhat but it is still present as a var can contain an expression that contains more vars and expressions and (since we are lazy) we need to recursively resolve them.
-  Yes, you cannot use `!unsafe` on a string in which you want interpolation, why you use is on the 'parts' and assemble the string you need from that.

```
hashi_vault_role: "GRANT ALL PRIVILEGES ON {{ dbname }}.* TO {{hashi_name}}@'%';"
hashi_name: !unsafe '{{name}}'}
```
