### ISSUE TITLE
Update vendored distro library

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#77027]
### Summary

Distro 1.7.0 was recently released. See https://github.com/ansible/ansible/pull/76121#issuecomment-1040620534

We should evaluate updating our vendored copy for 2.13.

### Issue Type

Feature Idea

### Component Name

lib/ansible/module_utils/distro

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
Biggest concern:

* Dropped support for EOL Pythons 2.7, 3.4 and 3.5 (https://github.com/python-distro/distro/pull/281/files)

It looks like the above change, now uses type hints that will be incompatible for us

So we may need to stick with out current version, and maintain backports from `distro`.

As such, we need to evaluate what backports make sense, and keep a running list in comments at the top of our vendored file.  See `lib/ansible/module_utils/compat/selectors.py` for examples of a backport list.

**Comment by mattclay** [comment]
We should probably update how we track/report on this vendored library. The closed issue https://github.com/ansible/ansible/issues/77392 was created as a result of the update-bundled sanity test, so we're likely to get another duplicate again when we switch to 2.15 development unless we update our process.

**Comment by MarkusTeufelberger** [comment]
Can there be a split, so hosts with Python>=3.6 get distro 1.7.0 and others get the legacy version?

**Comment by sivel** [comment]
> Can there be a split, so hosts with Python>=3.6 get distro 1.7.0 and others get the legacy version?

I don't think that would not be a good idea.  Depending on the Python version you target, you could get completely different results.

**Comment by MarkusTeufelberger** [comment]
As long as they are stable...?

**Comment by MarkusTeufelberger** [comment]
Modern distros won't be running old python versions and old distros would still be (dis)covered by the legacy branch of the distro library anyways. When Python2 support on target hosts is finally removed in a few decades(?), the new library would already be in use and ready to go unmodified.

I mean, it is also not the nicest solution, but definitely a working one - if someone has 2 Python versions on one target host and runs modules randomly against them there could also be all kinds of other issues.

**Comment by sivel** [comment]
Resolved by https://github.com/ansible/ansible/pull/79227
