### ISSUE TITLE
collection name with dash not installable from galaxy.ansible.com

### ISSUE THREAD

**Issue by azrdev** [ansible/ansible#77039]
### Summary

I try to install the collection https://galaxy.ansible.com/mrlesmithjr/manage-lvm which contains a dash/hyphen in the name. The galaxy description page instructs to run `ansible-galaxy install mrlesmithjr.manage-lvm` which fails:
~~~sh
$ ansible-galaxy collection download 'mrlesmithjr.manage-lvm'
ERROR! Neither the collection requirement entry key 'name', nor 'source' point to a concrete resolvable collection artifact. Also 'name' is not an FQCN. A valid collection name must be in the format <namespace>.<collection>. Please make sure that the namespace and the collection name  contain characters from [a-zA-Z0-9_] only.

Could not find mrlesmithjr.manage-lvm.
~~~
This happened in our AWX using ansible2.9 , and was reproduced in a virtualenv with ansible 5.3

The author of said collection has already been aware of the issue, apparently: https://github.com/mrlesmithjr/ansible-manage-lvm/pull/72

Related issue https://github.com/ansible/galaxy/issues/2622 lets me think the restrictions have been fastened in the last months, maybe without affecting existing content?

### Issue Type

Bug Report

### Component Name

galaxy

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jbiegert/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/ansible/venv/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/jbiegert/.ansible/collections:/usr/share/ansible/collections
  executable location = venv/bin/ansible
  python version = 3.9.10 (main, Jan 17 2022, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

* Fedora 35
* AWX19.3 default-EE

### Steps to Reproduce

```
ansible-galaxy install mrlesmithjr.manage-lvm
```

### Expected Results

collection to be installed successfully

### Actual Results

```console
ERROR! Neither the collection requirement entry key 'name', nor 'source' point to a concrete resolvable collection artifact. Also 'name' is not an FQCN. A valid collection name must be in the format <namespace>.<collection>. Please make sure that the namespace and the collection name  contain characters from [a-zA-Z0-9_] only.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
That galaxy entry is not a collection.  It is a role.  As such, it cannot be installed via `ansible-galaxy collection install`.

You want to use `ansible-galaxy role install mrlesmithjr.manage-lvm`

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by azrdev** [comment]
sorry, wasn't aware that galaxy still had roles. makes totally sense, thanks for the explanation!
