### ISSUE TITLE
Spaces in SSH key path break Ansible

### ISSUE THREAD

**Issue by skoop** [ansible/ansible#7713]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.3
##### Environment:

OSX
##### Summary:

It seems that when the path to the SSH key contains spaces, these are not correctly escaped, effectively breaking Ansible. This issue was reported before: https://github.com/ansible/ansible/issues/6559 but was closed by the reporter for some reason. 
##### Steps To Reproduce:

I have my project set up in an OSX disk image for security reasons. This is automatically mounted by OSX into /Volumes/Disk Image/. In our project, an SSH key is defined in the base box that I need to specify to Ansible when running ansible-playbook. My command is:

```
ansible-playbook --private-key="/Volumes/Disk Image/project/key/id_rsa" --user=vagrant --limit="web" --inventory-file=ansible/inventory/my-dev ansible/vagrant-server.yml -vvvv
```

I've extracted this command from vagrant provision, since vagrant provision failed to report to me what the exist issue is. The vagrant provision command output:

```
==> web: Running provisioner: ansible...
ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false PYTHONUNBUFFERED=1 ansible-playbook --private-key=/Volumes/Disk Image/project/key/id_rsa --user=vagrant --limit='web' --inventory-file=ansible/inventory/my-dev -v ansible/vagrant-server.yml

PLAY [web] ********************************************************************

GATHERING FACTS ***************************************************************
fatal: [172.31.222.222] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue

TASK: [default | updating] ****************************************************
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ********************************************************************
       to retry, use: --limit @/Users/stefan/vagrant-server.retry

172.31.222.222             : ok=0    changed=0    unreachable=1    failed=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Running the ansible-playbook directly with -vvvv gives me an error:

```
PLAY [web] ********************************************************************

GATHERING FACTS ***************************************************************
<172.31.222.222> ESTABLISH CONNECTION FOR USER: vagrant
<172.31.222.222> REMOTE_MODULE setup
<172.31.222.222> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/stefan/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'IdentityFile=/Volumes/Disk Image/project/key/id_rsa', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '172.31.222.222', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1402403433.84-2316867755000 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1402403433.84-2316867755000 && echo $HOME/.ansible/tmp/ansible-tmp-1402403433.84-2316867755000'"]
fatal: [172.31.222.222] => SSH encountered an unknown error. The output was:
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
command-line line 0: garbage at end of line; "Image/project/key/id_rsa".


TASK: [default | updating] ****************************************************
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ********************************************************************
       to retry, use: --limit @/Users/stefan/vagrant-server.retry

172.31.222.222             : ok=0    changed=0    unreachable=1    failed=0
```

As you can see, the error specifies the last part of the key path, after the space. So I set up a symlink with no spaces in it, and I refer to that instead. My command is now:

```
ansible-playbook --private-key="/Users/stefan/php/customer/project/key/id_rsa" --user=vagrant --limit="web" --inventory-file=ansible/inventory/peter-dev ansible/vagrant-server.yml -vvvv
```

Now Ansible starts running correctly. 

My guess is that somewhere the paths are passed on without proper escaping or quoting, which causes the above issue. 
##### Expected Results:

Ansible will run the playbook correctly on the specified machine 
##### Actual Results:

An error because the SSH key path is not complete. See the reproduction steps, it contains all information.

**Comment by ebastos** [comment]
I wonder if that would fix it:

https://github.com/ebastos/ansible/commit/a65fd0633847fb86b5e9682f847ffbd7346cc04b

**Comment by jimi-c** [comment]
@ebastos yes, you can send us that as a PR.

**Comment by skoop** [comment]
@ebastos could you send the PR? I would love to see this fixed in the next release, since I'm actually running into this bug for my day-to-day project right now.

**Comment by ebastos** [comment]
@skoop That was merged last week:
https://github.com/ansible/ansible/pull/7726

**Comment by skoop** [comment]
oh! sorry, I completely missed that. I guess this issue can be closed then. I was confused by the status of the issue :)

**Comment by jimi-c** [comment]
My apologies, I didn't realize this was not auto-closed. Closing now, thanks!
