### ISSUE TITLE
Putty and Open SSH work to Sonicwall Appliance, but Ansible Fails to Send RAW CLI commands.

### ISSUE THREAD

**Issue by ichheissebrent** [ansible/ansible#77156]
### Summary

When I attempt to issue raw SSH commands using Ansible 2.12.2, the session seems to just hang. 

Detailed Description:
- I am attempting to automate Sonicwall firewall configuration, using the 'raw' module. End goal is to simply push updated Address Objects.
- OS of Ansible control node = Ubuntu
- Ansible Version = 2.12.2
- I CAN log in to the endpoints via Putty, or OpenSSH
- However when attempting to send an ad-hoc command via Terminal, or run a play, the session hangs, and test CLI command is never sent. 
- On the sonicwall end, I can see a successful admin user login, but it also show that no commands are ever issued.

Eventually the Sonicwall kills the connection due to inactivity timeout.

I've attached copies of the Hosts file, ansible config file, and terminal output of the ad-hoc command and "ansible --version"

Any Idea what's going on here? 

Thank you!!

[Example Raw Ad Hoc Command.txt](https://github.com/ansible/ansible/files/8153854/Example.Raw.Ad.Hoc.Command.txt)
[Hosts.txt](https://github.com/ansible/ansible/files/8153855/Hosts.txt)
[ansible config.txt](https://github.com/ansible/ansible/files/8153856/ansible.config.txt)

### Issue Type

Bug Report

### Component Name

raw

### Ansible Version

```console
$ ansible --version
brent@brent-VirtualBox:~/Desktop$ ansible --version
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/brent/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/brent/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

### Configuration

```console
ansible-config dump --only-changed
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

### OS / Environment

Ubuntu 20.04.4 is the control node.

Sonicwall endpoints of various firmware versions are the targets. All support SSH. One test unit is on 6.5.4.7-83n, the other is 5.9.2.7-5o.

### Steps to Reproduce

Issue terminal command of the following, with a Sonicwall appliance as the target.

ansible #.#.#.# -m raw -a 'show cli' -u admin -k -vvv

### Expected Results

I expected the raw ad-hoc command to display the output of 'show cli.'  This did not happen.

### Actual Results

```console
brent@brent-VirtualBox:~/Desktop$ ansible 11.11.11.11 -m raw -a 'show cli' -u admin -k -vvv
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/brent/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/brent/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
SSH password: 
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
META: ran handlers
<11.11.11.11> ESTABLISH SSH CONNECTION FOR USER: admin
<11.11.11.11> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="admin"' -o ConnectTimeout=10 -o 'ControlPath="/home/brent/.ansible/cp/d2e87c051b"' -tt 11.11.11.11 'show cli'
<11.11.11.11> (255, b"\r\r\n                                                                      \r\nCopyright (c) 2012 Dell | SonicWALL, Inc.                             \r\n                                                                      \r\n                                                                      \r\n\r\r\nUsing username 'admin'.\r\nPassword:\r\n\r\nadmin@NOC Testlab Sonicwall> \r\n% Session timed out.\r\n", b'Shared connection to 11.11.11.11 closed.\r\n')

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ichheissebrent** [comment]
Apologies for that. I've corrected the post.

**Comment by mkrizek** [comment]
It seems that you cannot use `show cli` with the `raw` module on this device and you should probably use suitable networking module.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.libera.chat
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
