### ISSUE TITLE
Running ansible-playbook with vault option in combination with other options does not work

### ISSUE THREAD

**Issue by mhauck** [ansible/ansible#7716]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.7 (devel 9f0d496d67) last updated 2014/06/04 18:39:43 (GMT +000)
##### Environment:

Ubuntu 12.04 LTS
##### Summary:

Corresponding to https://groups.google.com/forum/#!topic/ansible-project/EpHxbSkD1JA,
the ansible-playbook command does not work if it contains a combinatino of a vault option such as 
--vault-password-file or --ask-vault-pass
and an option such as
--list-tasks, --list-hosts or --syntax-check
##### Steps To Reproduce:

Execute an arbitrary playbook:

ansible-playbook -i inventory/test playbook.yml --list-tasks --vault-password-file ~/.vault_pass.txt
##### Expected Results:

```
playbook: playbook.yml

    play #1 (webservers):
        Example task
        ...
```
##### Actual Results:

```
playbook: playbook.yml

ERROR: A vault password must be specified to decrypt data
```

**Comment by jimi-c** [comment]
Funny you should bring this up, I just merged in a patch to correct exactly this issue. So if you're using the devel branch, this should be corrected. This fix will be included in the next major release (1.7). Thanks!
