### ISSUE TITLE
ipaddr filter is not auto-detected with ansible-core & collection

### ISSUE THREAD

**Issue by yw5vruox7dr** [ansible/ansible#77223]
### Summary

`ipaddr` is located in `ansible.utils` (former `ansible.netcommon`).

* When only ansible-core and the collection (`ansible.utils`) are installed the filter `ipaddr()` is not auto-detected. You have to use the whole FQCN (`ansible.utils.ipaddr`).
* When using `ansible` package the FQCN is not necessary - you can just use `ipaddr()`

This MR was intended to fix this problem in the past: https://github.com/ansible/ansible/pull/67684

### Issue Type

Bug Report

### Component Name

ipaddr

### Ansible Version

```console
$ bash-4.4# ansible --version
ansible [core 2.11.3.post0] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
```

### Configuration

```console
bash-4.4# ansible-config dump --only-changed
bash-4.4#
```

### OS / Environment

awx-ee image
CentOS Stream 8

### Steps to Reproduce

```
podman run --rm -it quay.io/ansible/awx-ee bash

./test.yml
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: netaddr
      debug:
        msg: "{{ '10.0.0.10/24' | ipaddr('network') }}"

pip3 install ipaddr

#ansible-galaxy collection install ansible.netcommon
ansible-galaxy collection install ansible.utils

ansible-playbook test.yml 
```

### Expected Results

FQCN is auto-detected.
```console
TASK [netaddr]
ok: [localhost] => {
    "msg": "10.0.0.0"
}
```

### Actual Results

```console
TASK [netaddr] 
fatal: [localhost]: FAILED! => {"msg": "template error while templating string: no filter named 'ipaddr'. String: {{ '10.0.0.10/24' | ipaddr('network') }}"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
fwiw, we cannot simply update the routing, if we do, users who are using an older version of netcommon will suddenly stop working.  You will need to also have netcommon installed to use the short name.  Otherwise, you need to use FQCN.
