### ISSUE TITLE
uri receives a chunked big answer even though it shouldn't

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#77262]
### Summary

- uri sometimes receives incomplete answer under a normal network environment
- the size of the whole expected answer is around 200 kB.
- all timeouts are set around 1h to make sure uri has enough time to receive the big answer
- uri always reports "transfer_encoding: chunked" even when it is not chunked
- This issue happens when used over networking devices, I haven't checked when used over computing devices.
- This issue does not happen when smaller answers are received.
- This post follows [a discussion](https://groups.google.com/g/ansible-project/c/SaRnoe1dacI) with @sivel 

### Issue Type

Bug Report

### Component Name

uri

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /opt
  executable location = /usr/local/bin/ansible
  python version = 3.9.10 (main, Feb 22 2022, 13:54:07) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = redis
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = localhost:<port>:0:<password>
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 259200
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/opt']
DEFAULT_EXECUTABLE(/etc/ansible/ansible.cfg) = /bin/bash
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 1000
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 120
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = replace
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_PRIVATE_ROLE_VARS(/etc/ansible/ansible.cfg) = False
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 180
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = ssh
ENABLE_TASK_DEBUGGER(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = True
INJECT_FACTS_AS_VARS(/etc/ansible/ansible.cfg) = True
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 3599
PERSISTENT_CONNECT_RETRY_TIMEOUT(/etc/ansible/ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 3600
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
SHOW_CUSTOM_STATS(/etc/ansible/ansible.cfg) = True
```

### OS / Environment

- Controller: Ubuntu 21.10 impish
- Host: CSR 1kv 17.3.1a

### Steps to Reproduce

```
- name: Sending GET to <url> with uri
  ansible.builtin.uri:
        body: ''
        body_format: 'json'
        force_basic_auth: yes
        headers:
          Accept: application/yang-data+json
          Content-Type: application/yang-data+json
        method: GET
        return_content: yes
        status_code: "100,101,102,200,201,202,203,204,205,206,207,208,226,300,301,302,303,304,305,307,308"
        timeout: 3600
        url: "https://172.21.126.182/restconf/data/ietf-netconf-monitoring:netconf-state?content=nonconfig"
        url_password: password
        url_username: admin
        validate_certs: false
  register: return_uri_restconf_json
```

### Expected Results

The whole unchunked answer should be received.

### Actual Results

```console
- The answer is received after a few seconds.
- return_uri_restconf_json.json is not defined showing that the response is chunked

task path: main.yml:219
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/bash -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/bash -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1646997777.3538132-2700276-93994275105673 `" && echo ansible-tmp-1646997777.3538132-2700276-93994275105673="` echo /root/.ansible/tmp/ansible-tmp-1646997777.3538132-2700276-93994275105673 `" ) && sleep 0'
Using module file /usr/local/lib/python3.9/dist-packages/ansible/modules/uri.py
<localhost> PUT /root/.ansible/tmp/ansible-local-269044374_5i0rc/tmps9ux33ea TO /root/.ansible/tmp/ansible-tmp-1646997777.3538132-2700276-93994275105673/AnsiballZ_uri.py
<localhost> EXEC /bin/bash -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1646997777.3538132-2700276-93994275105673/ /root/.ansible/tmp/ansible-tmp-1646997777.3538132-2700276-93994275105673/AnsiballZ_uri.py && sleep 0'
<localhost> EXEC /bin/bash -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1646997777.3538132-2700276-93994275105673/AnsiballZ_uri.py && sleep 0'
<localhost> EXEC /bin/bash -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1646997777.3538132-2700276-93994275105673/ > /dev/null 2>&1 && sleep 0'
ok: [CSR1000v-17.3.1a -> localhost] => changed=false
  cache_control: private, no-cache, must-revalidate, proxy-revalidate
  connection: close
  content: |-
    {
      "ietf-netconf-monitoring:netconf-state": {
        "capabilities": {
...
        },
        "datastores": {
          "datastore": [
            {
              "name": "running",
              "tailf-netconf-monitoring:transaction-id": "1646-983921-976163"
            },
            {
              "name": "candidate"
            }
          ]
        },
        "schemas": {
...
        },
        "sessions": {
          "session": [
            {
              "session-id": 26,
              "transport": "tailf-netconf-monitoring:rest-http",
              "username": "admin",
              "source-host": "172.21.0.1",
              "login-time": "2022-03-11T11:22:57+00:00",
              "tailf-netconf-monitoring:transaction": [
                {
  content_type: application/yang-data+json
  cookies: {}
  cookies_string: ''
  date: Fri, 11 Mar 2022 11:22:57 GMT
  elapsed: 0
  invocation:
    module_args:
      attributes: null
      body: ''
      body_format: json
      ca_path: null
      client_cert: null
      client_key: null
      creates: null
      dest: null
      follow_redirects: safe
      force: false
      force_basic_auth: true
      group: null
      headers:
        Accept: application/yang-data+json
        Content-Type: application/yang-data+json
      http_agent: ansible-httpget
      method: GET
      mode: null
      owner: null
      remote_src: false
      removes: null
      return_content: true
      selevel: null
      serole: null
      setype: null
      seuser: null
      src: null
      status_code:
      - 100
      - 101
      - 102
      - 200
      - 201
      - 202
      - 203
      - 204
      - 205
      - 206
      - 207
      - 208
      - 226
      - 300
      - 301
      - 302
      - 303
      - 304
      - 305
      - 307
      - 308
      timeout: 120
      unix_socket: null
      unredirected_headers: []
      unsafe_writes: false
      url: https://172.21.126.182/restconf/data/ietf-netconf-monitoring:netconf-state?content=nonconfig
      url_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      url_username: admin
      use_gssapi: false
      use_proxy: true
      validate_certs: false
  msg: OK (unknown bytes)
  pragma: no-cache
  redirected: false
  server: openresty
  status: 200
  transfer_encoding: chunked
  url: https://172.21.126.182/restconf/data/ietf-netconf-monitoring:netconf-state?content=nonconfig
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
> * uri always reports "transfer_encoding: chunked" even when it is not chunked

How do you know this?  As mentioned, python3 tries to read all chunks and return a single body transparently for you.

If that header is set, then the server did in fact respond with a `chunked` `Transfer-Encoding`.

We just interact with the stdlib python modules, and they claim to handle this transparently.  I don't think there is anything for ansible to do here.

**Comment by jean-christophe-manciot** [comment]
> How do you know this? As mentioned, python3 tries to read all chunks and return a single body transparently for you.

This [post](https://groups.google.com/g/ansible-project/c/SaRnoe1dacI) clearly shows that uri sets 'transfer_encoding: chunked' for the first answer for which the size is ... ~ 160 bytes.
The controller is directly connected to the networking device which runs as a VM inside the host on a virtuel switch.
The connection type being virtual Ethernet with a mtu of 1500, there should not be any reason for the network device to chunk that response.

**Comment by sivel** [comment]
> there should not be any reason for the network device to chunk that response

I'm afraid ansible has nothing to do with that.  You'll have to take that up with the network device manufacturer.

**Comment by jean-christophe-manciot** [comment]
Maybe, but that does not explain the core issue here.

**Comment by sivel** [comment]
> Maybe, but that does not explain the core issue here (when the answer is really chunked).

What is the core issue?

**Comment by jborean93** [comment]
I'm not sure how that is a problem with `uri`, it receives the payload that was returned to it, it can't really control how the server returns except by requesting the right data which is based on the headers you provide to it.

**Comment by jean-christophe-manciot** [comment]
@jborean93 
Have you made tests with uri making a single request for a large amount of data forcing the server to chunk its answer into multiple responses?

**Comment by jborean93** [comment]
That's the point we are trying to explain, Ansible just returns what it is given to it in the response. If the server returns the chunked response then that's what Ansible will return. AFAIK Ansible itself isn't returning the chunked response because it hasn't processed all the data, rather that's exactly what was in the response from the server. The `uri` module can't really do much about that as this behaviour is defined by the server. Similar to how `command` and `shell` can't add any smarts around detecting if a change happened as it's entirely dependent on the command being run.

**Comment by jean-christophe-manciot** [comment]
> Ansible just returns what it is given to it in the response. 

According to Matt Martz, "Looking at the CPython code for http.client, `.read()` should be fully consuming all of the chunks."
Unless I misinterpret that, it means that:
- either there is an issue in some library which does not fetches **all** the chunks
- or the server returns only the first chunk even if it is properly asked to return all the rest as well

Hence my question again:
Have you made tests with uri making a single request to a networking device for a large amount of data forcing the server to chunk its answer into multiple responses?

**Comment by sivel** [comment]
In either case, neither of those issues are a result of ansible, and nothing that we control.  As mentioned before there is nothing for us to do here.  You may wish to open a bug report with the network vendor, and or cpython.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
