### ISSUE TITLE
Allow to configure the ciphersuite for SSL context 

### ISSUE THREAD

**Issue by gmuloc** [ansible/ansible#77412]
### Summary

Python 3.10 changed the default set of supported ciphers: https://docs.python.org/3/library/ssl.html#ssl.SSLContext / https://github.com/python/cpython/blob/e91b0a7139d4a4cbd2351ccb5cd021a100cf42d2/Modules/_ssl.c#L170

When the client ansible tries to connect to a client which does not support any of these ciphers the handshake will fail with the following exchange:
* Ansible ---- Client Hello ------> Client
* Client ------ Handshake Failure -----> Ansible

In Python SSL library, it is possible to modify the list of usable ciphers using the `set_ciphers` command. However currently ansible (via the usage of httpapi connectors) does not allow to modify the list of the ciphersuite and so the default Python ones are being used.

(Note that there does not seem to be a workaround to modify the default list of cipher leveraging environment variables.)

This idea is to add the possibility to pass some string to the `urls.py` code to be able to set the allowed ciphers and overwrite the python default if need be.

Note: this is indeed asking to use "considered-less-secure" ciphers but can be useful in some cases / with some legacy devices when using Python 3.10 and above.

### Issue Type

Feature Idea

### Component Name

module_utils/url.py

### Additional Information

Testing against my current device using Python 3.10 - modifying the current code at:

https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/urls.py#L1419

```python
          if HAS_SSLCONTEXT and not validate_certs:
              # In 2.7.9, the default context validates certificates
              context = SSLContext(ssl.PROTOCOL_SSLv23)
              if ssl.OP_NO_SSLv2:
                  context.options |= ssl.OP_NO_SSLv2
              context.options |= ssl.OP_NO_SSLv3
              context.verify_mode = ssl.CERT_NONE
              context.check_hostname = False
[...]
```

With

```python
          if HAS_SSLCONTEXT and not validate_certs:
              # In 2.7.9, the default context validates certificates
              context = SSLContext(ssl.PROTOCOL_SSLv23)
              if ssl.OP_NO_SSLv2:
                  context.options |= ssl.OP_NO_SSLv2
              context.options |= ssl.OP_NO_SSLv3
              context.verify_mode = ssl.CERT_NONE
              context.check_hostname = False
              # Allow all ciphers rather than only Python 3.10 default
              context.set_ciphers("DEFAULT")
```

Allows me to avoid the SSL Handshake issue

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
Resolved by https://github.com/ansible/ansible/pull/78650
