### ISSUE TITLE
Make --ask-sudo-pass an option in the inventory file

### ISSUE THREAD

**Issue by gitaarik** [ansible/ansible#7742]
I have a server that will always need a sudo password. Every time I run the playbook I have to supply `--ask-sudo-pass` to the `ansible-playbook` command. It would be more convenient if I could put something like `ansible_ask_sudo_pass=yes` in the inventory files, just like the other parameters:

http://docs.ansible.com/intro_inventory.html#list-of-behavioral-inventory-parameters

The same goes for `--ask-pass` for ssh passphrases.

**Comment by jimi-c** [comment]
Since asking for sudo passwords is a global option, it wouldn't make much sense to put it in inventory as a per-host item. You can however set `ask_sudo_pass = True` in your `ansible.cfg` under the `[defaults]` section, or `export ANSIBLE_ASK_SUDO_PASS=True` to accomplish the same thing.

Please let us know if you have any further questions regarding this. Thanks!

**Comment by gitaarik** [comment]
Hey @jimi-c, thanks for the information about the global config settings. However, I have **some** servers that need a sudo password, and others that don't.

So it would be nice if you could specify in the inventory files wether a server requires a sudo password or not.

**Comment by gitaarik** [comment]
Hey @jimi-c, could you still give an explanation? Thanks

**Comment by jimi-c** [comment]
Yes. Right now, if you specify a sudo password, it is only used as needed. Since we handle the sudo password prompt upfront before any systems are touched, this feature request would require a pretty major change internally while providing little extra benefit to most users, and as I noted above you can accomplish the same thing via ansible.cfg options.

**Comment by gitaarik** [comment]
I can't see how adding an option `ansible_ask_sudo_pass=yes` to the inventory file is a major change. If I manage to make the change, would you review a pull request for it?

**Comment by jimi-c** [comment]
Yes, we would review it.

**Comment by gitaarik** [comment]
I took a look and I understand why it isn't easy. The problem I think is that the inventory file could be vault protected, so the vault password should be asked before the inventory file is read. And the functionality to ask the vault password is the same as the other parameters like `--ask-sudo-pass`. So that can't be moved to somewhere **after** the inventory file has been read.

Also we only know what hosts are being matched inside the playbook. And apparently you can supply multiple playbooks on the command line and it loops through them and plays them after each other, so there's no way to know what hosts we will get beforehand.

Does what I described look correct to you? I might take another look at it some time to see if I can find a clever solution.

**Comment by jimi-c** [comment]
Yes, that's the gist of it. And if you can find a simpler way that's not overly invasive to do what you're looking for, as I said we'll definitely review it. Thanks!

**Comment by groggemans** [comment]
For other people coming here from google, you can use vars_prompt and prompt into ansible_sudo_pass to solve this!

``` yaml
vars_prompt:
  - name: "ansible_sudo_pass"
    prompt: "Sudo password"
    private: yes
```

**Comment by survietamine** [comment]
thanks groggemans, with my recent version ansible_become_pass in vars_prompt does the job!

**Comment by OPSJono** [comment]
I was looking for a way to force the user to enter the sudo password at the time of running a playbook.
Adding @groggemans suggestion to my playbook does the job perfectly. Thanks!

**Comment by klml** [comment]
thx @groggemans would you copy and paste this question and your answer to stackoverflow? I even red over, but this fixed my problem.

**Comment by groggemans** [comment]
@klml https://stackoverflow.com/questions/50217255/how-to-prompt-for-sudo-password-with-ansible/50217256
