### ISSUE TITLE
Ansible 2.9.27 sometimes renders template into subdirectory 'filename'/'filename'.j2

### ISSUE THREAD

**Issue by igorfraa** [ansible/ansible#77536]
### Summary

When using ansible.builtin.template, **sometimes** (say 1 in 200 times) template being rendered, but every file goes into subdirectory with '.j2' suffix added to filename like in the template source:

`/opt/docker/clickhouse/config/config.xml/config.xml.j2`

Which it is meant to be 
`/opt/docker/clickhouse/config/config.xml`

File contents is rendered correctly however.

It seams the issue affects all the templates in a single task, not a whole play.

However I can not reproduce the issue intentionally. On a second play file paths appear to be correct.

### Issue Type

Bug Report

### Component Name

ansible.builtin.template

### Ansible Version

```console
$ ansible --version
ansible 2.9.27
  config file = None
  configured module search path = ['/Users/.../.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.10/site-packages/ansible
  executable location = /opt/homebrew/bin/ansible
  python version = 3.10.2 (main, Feb  2 2022, 05:51:25) [Clang 13.0.0 (clang-1300.0.29.3)]
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_FORCE_COLOR(/Users/user/Project/my-ansible-placeholder/ops/deploy/ansible.cfg) = True
ANSIBLE_PIPELINING(/Users/user/Project/my-ansible-placeholder/ops/deploy/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/Users/user/Project/my-ansible-placeholder/ops/deploy/ansible.cfg) = -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o C>
DEFAULT_BECOME(/Users/user/Project/my-ansible-placeholder/ops/deploy/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/Users/user/Project/my-ansible-placeholder/ops/deploy/ansible.cfg) = ['profile_tasks']
DEFAULT_HOST_LIST(/Users/user/Project/my-ansible-placeholder/ops/deploy/ansible.cfg) = ['/Users/user/Project/my-ansible-placeholder/ops/deploy/inventories/dev']
DEFAULT_JINJA2_EXTENSIONS(/Users/user/Project/my-ansible-placeholder/ops/deploy/ansible.cfg) = jinja2.ext.loopcontrols
DEFAULT_LOAD_CALLBACK_PLUGINS(/Users/user/Project/my-ansible-placeholder/ops/deploy/ansible.cfg) = True
DEFAULT_MANAGED_STR(/Users/user/Project/my-ansible-placeholder/ops/deploy/ansible.cfg) = Ansible managed
DEFAULT_ROLES_PATH(/Users/user/Project/my-ansible-placeholder/ops/deploy/ansible.cfg) = ['/Users/user/Project/my-ansible-placeholder/ops/deploy/galaxy-roles'] 
DEFAULT_STDOUT_CALLBACK(/Users/user/Project/my-ansible-placeholder/ops/deploy/ansible.cfg) = yaml
```

### OS / Environment

Issue was seen on:
macOS Monterey 12.3, Ubuntu LTS 18, Ubuntu LTS 20
Python versions 3.5 through 3.10

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

A template rendered into
```/file/path/filename```

### Actual Results

```console
A template rendered into a subdirectory named after the expected filename:
/file/path/filename/filename.j2```
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by s-hertel** [comment]
@igorfraa We need a reproducer to be able to investigate this. Please test against 2.12 to verify this is still an issue on newer versions since 2.9 is only accepting security fixes. I'm closing this since there's not enough actionable information.

**Comment by igorfraa** [comment]
@s-hertel 

Please advise me on the method to reproduce this.

The issue seems to happen in 1:100 - 1:1000 times (may be 1:10000) considering my ordinary task uses 50 template steps per run.  

I do not think I can migrate to 2.10+ for my production task, but I can deploy a VPS, and launch a bunch of deployments. Though this does not guarantee a reproducible scenario.
