### ISSUE TITLE
Add ssh agent authentication for vault. 

### ISSUE THREAD

**Issue by dopry** [ansible/ansible#7756]
To streamline interacting with vault files and deployments it would be nice if SSH Agent based authentication could be used for vault access.

Currently deploying with Jenkins we use a manually create password file in the workspace. It would be really nice if it could use the ssh key we store in the config.

**Comment by srgvg** [comment]
I'm not an encryption expert by any means, but AFAIK, SSH keys do not allow to encrypt data.
Do you have any pointer on how this could be implemented, that shows I'm wrong?

FYI, There's a PR in queue to implement GPG key encryption with vault.

**Comment by mpdehaan** [comment]
This doesn't seem to make much sense to me either, stop by ansible-devel for a discussion perhaps.

**Comment by dopry** [comment]
I think the more salient point is it would be nice to have a more
accessible non-interactive method of decrypting the vault files instead of
the current .vault-file stored in plain text for people utilizing Ansible
as a part of the continuous integration environment. I understand that
SSH-Agent and private keys are not useful for encryption, after all the
decryption key is public.  I am advocating that it be used as a way of
authenticating users for whom the file should be decrypted, and used in
conjunction with some other encryption method.

Then again something more common like GPG support would be nice. I don't
think I realized the vault pass was used as the encryption key. I was
thinking it was used as authentication for some reason, but that doesn't
really make sense when I think about it,

On Sat, Jun 14, 2014 at 4:29 PM, Michael DeHaan notifications@github.com
wrote:

> Closed #7756 https://github.com/ansible/ansible/issues/7756.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible/issues/7756#event-131452434.

## 

Darrel O'Pry
The Spry Group, LLC.
http://www.spry-group.com
718-355-9767 x101
