### ISSUE TITLE
SSH control socket files disappearing

### ISSUE THREAD

**Issue by evanccnyc** [ansible/ansible#7759]
Getting a lot of these errors happening at random times. Wasnt having this happen before. The Control socket files seem to be disappearing. 

fatal: [xxxx] => SSH encountered an unknown error. The output was:
OpenSSH_5.6p1, OpenSSL 0.9.8y 5 Feb 2013
debug1: Reading configuration data /Users/xxx/.ssh/config
debug1: Reading configuration data /etc/ssh_config
debug1: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket "/Users/xxx/.ansible/cp/ansible-xxxx-ubuntu" does not exist
debug2: ssh_connect: needpriv 0
debug1: Connecting to xxxxx [xxxx] port 22.
debug2: fd 3 setting O_NONBLOCK
debug1: connect to address xxxx port 22: Operation timed out
ssh: connect to host xxxx port 22: Operation timed out

**Comment by mpdehaan** [comment]
Can you please provide more information about your ansible version, operating systems, and how to reproduce this problem?

**Comment by evanccnyc** [comment]
Looks like it was an error on my end. I set the ssh timeout longer for ansible and it fixed the problem.

**Comment by RobeDevOps** [comment]
I have a 45s to timeout... for me it is too longer !!
