### ISSUE TITLE
Incorrect hostname setting for RHEL7

### ISSUE THREAD

**Issue by rmarchei** [ansible/ansible#7763]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

Managing RHEL 7
##### Summary:

To set the hostname on RHEL7 Ansible edits the /etc/sysconfig/network file (RedHatStrategy) but it should use the hostnamectl command, like the FedoraStrategy
##### Steps To Reproduce:

Use the hostname module to set hostname on a RHEL7
##### Expected Results:

Hostname is changed using hostnamectl and nothing is written on /etc/sysconfig/network
##### Actual Results:

Ansible writes the HOSTNAME variable on /etc/sysconfig/network but this doesn't change the "static hostname" as shown by the hostnamectl command.

**Comment by jimi-c** [comment]
Merged, thanks!
