### ISSUE TITLE
Revamp the Ansible Getting Started Guide

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#77681]
### Summary

Rewrite the [Ansible Getting Started guide](https://docs.ansible.com/ansible/latest/user_guide/intro_getting_started.html) with a focus on simplifying the introduction to Ansible for new users. This guide should streamline the new user experience to get them to the point of being able to create simple but usable playbooks, and my include links to tutorials to further the user experience.

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/user_guide/intro_getting_started.rst

### Ansible Version

```console
$ ansible --version
2.13
```

### Configuration

```console
$ ansible-config dump --only-changed
none
```

### OS / Environment

linux

### Additional Information

The goal is to gather feedback from new users on where they hit difficulties and try to address those in this revamped guide, where possible.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by AndreasDavour** [comment]
I'm not a new user, but I have some input.

I think the question on how to revamp this guide is determined by the scope. The Network Getting Started Guide is covering a lot of bases, a proper guide. The more general getting started is really just a teaser, and not really a guide. 

Also, as a teaser it has issues, like repeating the -u user option multiple times, and not really explaining what's going on when running an ad-hoc command with -a but skipping the -m which is used when showing ping. 

For a proper guide, the network one looks like a better jumping off point than what we have in the other document.

**Comment by acozine** [comment]
See also https://github.com/ansible/ansible/pull/59163/files (to crib good material from and to close when the new guide is done).
