### ISSUE TITLE
unarchive module not compatible with Solaris tar

### ISSUE THREAD

**Issue by toddmowen** [ansible/ansible#7777]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel 3fb3e7e6dc) last updated 2014/06/15 10:16:24 (GMT +900)
##### Environment:

Managing Solaris 11.1 host
##### Summary:

The unarchive module depends on the "-C" (directory) option to tar, but Solaris tar does not support this. More precisely, it supports "-C" only for archive creation, not extraction.

Additionally, ansible does not detect that the operation has failed, nor is the error message from tar included in the output, even with a "-v" flag to ansible.
##### Steps To Reproduce:

Given some tar file:

```
$ tar cf magic.tar -C /etc magic
```

Run this task, targetting a remote Solaris 11 host:

```
- unarchive: src=magic.tar dest=/tmp
```
##### Expected Results:

The file "magic" should be extracted to /tmp on the remote machine.
##### Actual Results:

The file is not extracted. But ansible still reports "changed=1" and "failed=0".

```
$ ansible-playbook -v tarbug.yml

PLAY [tmp-dls3] *************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [tmp-dls3]

TASK: [unarchive src=magic.tar dest=/tmp] ************************************* 
changed: [tmp-dls3] => {"changed": true, "check_results": {"cmd": "/usr/sbin/tar -v -C \"/tmp\" --diff -zf \"/tmp/ansible-tmp-1402806867.64-82752862062629/source\"", "err": "Usage: tar {c|r|t|u|x}[BDeEFhilmnopPTvw@/[0-7]][bf][X...] [j|z|Z] [blocksize] [tarfile] [size] [exclude-file...] {file | -I include-file | -C directory file}...\n", "out": "", "rc": 1, "unarchived": false}, "dest": "/tmp", "gid": 3, "group": "sys", "handler": "TgzFile", "mode": "01777", "owner": "root", "size": 510, "src": "/tmp/ansible-tmp-1402806867.64-82752862062629/source", "state": "directory", "uid": 0}

PLAY RECAP ******************************************************************** 
tmp-dls3                   : ok=2    changed=1    unreachable=0    failed=0   
```

Notice also that the verbose output does _not_ include the command used for extraction. It does, however, show the command used for checking whether the files are already unarchived (this fails, because Solaris tar does not support "--diff" either, but that is not a problem and should just mean the unarchiving is unconditional).

**Comment by jimi-c** [comment]
Closing #7778 closed this, which is fine. We'll get to #7782 shortly.
