### ISSUE TITLE
Backport to Ansible2.9 "config lookup can query plugin settings #74186"

### ISSUE THREAD

**Issue by 24-komal** [ansible/ansible#77784]
### Summary

#74186

### Issue Type

Feature Idea

### Component Name

ansible

### Additional Information

#74186

Backport request for Ansible 2.9 

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by nitzmahone** [comment]
Sorry, 2.9 has reached end-of-life and will not receive further backports- time to upgrade!
