### ISSUE TITLE
ansible-vault requests cryptography library to be installed despite it being installed already

### ISSUE THREAD

**Issue by aj-sx** [ansible/ansible#77878]
### Summary

When I try to encrypt a string with "ansible-vault encrypt_string abc" command from ansible 5.8.0 (ansible-core 2.12.5), I get the following output:

`ERROR! ansible-vault requires the cryptography library in order to function`

ansible has been installed with `pip install ansible` into a fresh virtual environment with Python 3.8. I get this issue also with the latest 6.0.0a3 pre-release.

Sidenote:  I still have virtual environments with Python 3.6 where ansible-vault still works fine, which I restored from my previous MacBook with Intel chip. I migrated to a MacBook with M1 chip (arc64) from an older Intel based MacBook Pro (x86_64). They are being emulated by Rosetta 2 technology on arm64 architecture. 

Since the fresh virtual environments on arm64 don't work, but the pre-existing virtual environments from x86 work fine, I assume it is an incompatibility with the arm64 architecture.

### Issue Type

Bug Report

### Component Name

ansible-vault

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.5]
  config file = /Users/ajagel/git/atlassian-cloud-backup-deployment/ansible.cfg
  configured module search path = ['/Users/****/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/****/.virtualenvs/ansible-tools/lib/python3.8/site-packages/ansible
  ansible collection location = /Users/****/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/****/.virtualenvs/ansible-tools/bin/ansible
  python version = 3.8.13 (default, Mar 31 2022, 15:23:33) [Clang 13.1.6 (clang-1316.0.21.2)]
  jinja version = 3.1.2
  libyaml = False
```

### Configuration

```console
$ ansible-config dump --only-changed -t all
ANSIBLE_PIPELINING(/Users/****/git/atlassian-cloud-backup-deployment/ansible.cfg) = True
DEFAULT_GATHERING(/Users/****/git/atlassian-cloud-backup-deployment/ansible.cfg) = explicit
DEFAULT_POLL_INTERVAL(/Users/****/git/atlassian-cloud-backup-deployment/ansible.cfg) = 5
DEFAULT_STRATEGY(/Users/****/git/atlassian-cloud-backup-deployment/ansible.cfg) = linear
DEFAULT_TIMEOUT(/Users/****/git/atlassian-cloud-backup-deployment/ansible.cfg) = 5
DEFAULT_VAULT_PASSWORD_FILE(/Users/****/git/atlassian-cloud-backup-deployment/ansible.cfg) = /Users/****/git/atlassian-cloud-backup-deployment/.vault_pass

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

local:
_____
pipelining(/Users/****/git/atlassian-cloud-backup-deployment/ansible.cfg) = True

psrp:
____
pipelining(/Users/****/git/atlassian-cloud-backup-deployment/ansible.cfg) = True

ssh:
___
timeout(/Users/****/git/atlassian-cloud-backup-deployment/ansible.cfg) = 5

winrm:
_____
pipelining(/Users/****/git/atlassian-cloud-backup-deployment/ansible.cfg) = True

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
====
```

### OS / Environment

MacOS 12.3.1 (21E258) on Apple M1 Pro (arc64)

### Steps to Reproduce

# preparation
python -m venv .venv
source .venv/bin/activate
pip install ansible==5.8.0

# execution
ansible-vault encrypt_string abc

### Expected Results

I expected the given string to be encrypted with the vault password given at .vault_pass (configured in ansible.cfg).

The output should actually look liek this:

`!vault |
          $ANSIBLE_VAULT;1.1;AES256
          63393462313361323862383661303231336363616564353635633362396362663338636261666361
          6230313032333362303364333964373739633637366165610a383336656464643633333161663434
          37376139613034356163316233303835313262313638313433373431363637363263346637396435
          3031633562396238380a306166343862353161373531343231376536376235326338393239316261
          6164
Encryption successful`

I got that from an old virtual environment with Python 3.6 and ansible 4.8 (ansible-core 2.11.6) which still works.

### Actual Results

```console
$ ansible-vault encrypt_string -vvvv abc
ansible-vault [core 2.12.5]
  config file = /Users/****/git/atlassian-cloud-backup-deployment/ansible.cfg
  configured module search path = ['/Users/****/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/****/.virtualenvs/ansible-tools/lib/python3.8/site-packages/ansible
  ansible collection location = /Users/****/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/****/.virtualenvs/ansible-tools/bin/ansible-vault
  python version = 3.8.13 (default, Mar 31 2022, 15:23:33) [Clang 13.1.6 (clang-1316.0.21.2)]
  jinja version = 3.1.2
  libyaml = False
Using /Users/****/git/atlassian-cloud-backup-deployment/ansible.cfg as config file
encrypt_vault_id=None
ERROR! ansible-vault requires the cryptography library in order to function
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by aj-sx** [comment]
I've now tried to run a playbook with an encrypted variable in one of the var files and I also run into the same error in the step, where that encrypted variable is used. So the automatic decryption of variables is broken as well for me.

Here is the step error:

> fatal: [atlassian-cloud-backup-dev]: FAILED! => {"msg": "ansible-vault requires either the cryptography library (preferred) or pycrypto in order to function."}

**Comment by sivel** [comment]
Ultimately this is not an ansible-core issue.  We attempt to import cryptography, but likely due to the fact that you are still attempting to use a Python compiled C extension that was dynamically linked against an x86, the dependency is non functional and raises an exception.

You can attempt to use this code to figure out the error, but in the end, I'm afraid you are ultimately going to need to remove and recreate your virtual environment.

```python
from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes, padding
from cryptography.hazmat.primitives.hmac import HMAC
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import (Cipher as C_Cipher, algorithms, modes)
default_backend()
```

Or if you want a really long 1 liner:

```shell
python3 -c 'from cryptography.exceptions import InvalidSignature; from cryptography.hazmat.backends import default_backend; from cryptography.hazmat.primitives import hashes, padding; from cryptography.hazmat.primitives.hmac import HMAC; from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC; from cryptography.hazmat.primitives.ciphers import (Cipher as C_Cipher, algorithms, modes); default_backend();'
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by sivel** [comment]
Have you tried running the python code I provided in the venv that is having issues to diagnose the actual cause of the problem?

**Comment by aj-sx** [comment]
When executing your provided code I get the following error:
```
$ python3 -c 'from cryptography.exceptions import InvalidSignature; from cryptography.hazmat.backends import default_backend; from cryptography.hazmat.primitives import hashes, padding; from cryptography.hazmat.primitives.hmac import HMAC; from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC; from cryptography.hazmat.primitives.ciphers import (Cipher as C_Cipher, algorithms, modes); default_backend();'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/****/.virtualenvs/atlassian-cloud-backup-deployment/lib/python3.8/site-packages/cryptography/hazmat/primitives/hmac.py", line 12, in <module>
    from cryptography.hazmat.backends.openssl.hmac import _HMACContext
  File "/Users/****/.virtualenvs/atlassian-cloud-backup-deployment/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/Users/****/.virtualenvs/atlassian-cloud-backup-deployment/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 63, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/Users/****/.virtualenvs/atlassian-cloud-backup-deployment/lib/python3.8/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: dlopen(/Users/****/.virtualenvs/atlassian-cloud-backup-deployment/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_ffi_prep_closure'
```

**Comment by mkrizek** [comment]
> symbol not found in flat namespace '_ffi_prep_closure'

The above error message indicates some kind of linking issue so 

> Ultimately this is not an ansible-core issue.

still stands.

You might find a solution in https://stackoverflow.com/questions/66035003/installing-cryptography-on-an-apple-silicon-m1-mac or similar whatever page Google/$other_search_engine finds when searching for the error message.

**Comment by aj-sx** [comment]
[This solution](https://stackoverflow.com/a/72022463/18290585) actually helped me, thank you. I needed to re-install python with brew specific environment variables and re-create the virtual environment.
