### ISSUE TITLE
allow a step to happen locally on the ansible computer, relative to a remote host

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#779]
so we already have a local connection type, but this is not about that.

roughly, I might want to be able to do stuff like this in the middle of a play, running a step on behalf of a host

   tasks:
       - ... # something remote
       - action: command /usr/bin/schedule_outage_window ${inventory_hostname}
         local_task: True
       - ... # something remote

So basically you could easily start and stop an outage window within a play.

note that this could be anything and if there are 50 hosts in the play, this runs 50 times, but against 127.0.0.1, whether it is in inventory or not, and automatically uses the local connection type.   It probably does not sudo the local connection, or maybe follows sudo behavior of the play.   Unsure.

**Comment by mpdehaan** [comment]
thinking it's still the same connection type but some parameter like "delegate_to_host: host" added to the play settings

**Comment by tima** [comment]
Instead of adding a new term to the playbook instructions, why not allow a connection:local on a tasks?

**Comment by mpdehaan** [comment]
you're sort of right here, in that connection local does exactly this, and talks to the local machine, but what if you need to tell a monitoring server something and it's on another machine?  In that case, it's not a local op.

Another example might be speaking to a load balancer to take a host out of a pool and then put it back after some plays are done.

NOTE TO SELF:  make sure this can be applied to the task as well as the play.   In fact, I think it might be a task thing and not a play thing altogether.

**Comment by mpdehaan** [comment]
done, see mailing list, docs pending

'delegate_to'
