### ISSUE TITLE
Incorrect python-devel package name in Kerberos system requirements for windows remote management

### ISSUE THREAD

**Issue by m8ram** [ansible/ansible#77908]
### Summary

The section on installing the kerberos system requirements mentions `python-devel` for RHEL/Centos/fedora.
On RHEL8 at least the package name needs to be python36-devel, python38-devel or python39-devel depending on the version of python used by ansible. The version installed from Red Hat's repos will use python3.6 AFAICT.

### Issue Type

Documentation Report

### Component Name

ansible/docs/docsite/rst/user_guide/windows_winrm.rst

### Ansible Version

```console
ansible --version
ansible 2.9.27
  config file = /home/bram.mertens/workspace/clean-abxcfg/ansible.cfg
  configured module search path = ['/home/bram.mertens/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Sep  9 2021, 07:49:02) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
```

### Configuration

```console
not applicable
```

### OS / Environment

RHEL8

### Additional Information

Adding this will allow users to install the right package and use the winrm modules.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by samccann** [comment]
Verified on Fedora 36 and RHEL 8 that 'dnf install python3-devel' does the right thing.

The docs change is to change:
# Via Yum (RHEL/Centos/Fedora)
    yum -y install gcc python-devel krb5-devel krb5-libs krb5-workstation

to 
# Via dnf (RHEL/Centos/Fedora)
    dnf -y install gcc python3-devel krb5-devel krb5-libs krb5-workstation

In this file - https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/user_guide/windows_winrm.rst

**Comment by DesmondSanctity** [comment]
The link for the file to be corrected is not showing any information. It says the page has been moved and the new link isn't pointing to anything. Please check

**Comment by DesmondSanctity** [comment]
@samccann please this is still pending on the correct link to file. Thanks
