### ISSUE TITLE
docker volumes_from not working

### ISSUE THREAD

**Issue by paimpozhil** [ansible/ansible#7794]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

Ubuntu 14.04 
##### Summary:

volumes_from in the docker module does not create any change on the created containers
##### Steps To Reproduce:

https://github.com/paimpozhil/WhatPanel/blob/master/ansible/installwhatpanel.yml 
run this playbook 
##### Expected Results:

2 containers .. the paimpozhil/whatpanel container should be mounting volumes from paimpozhil/data
##### Actual Results:

2 containers without the volumes being mounted

=== original ticket:

any ideas?

Im running docker 1.0 on ubuntu 14.04 on both machines

Is this related to https://github.com/ansible/ansible/pull/6956

**Comment by zjeraar** [comment]
I have the same issue, docker 1.0.1 on ubuntu 14.04 and ansible 1.6.5.

---- edit
Sorry, I don't have the issue, thought I had, but it's working for me.

**Comment by discordianfish** [comment]
There was an issue with an older docker-py version, but that should be fixed by now. But I also run into that issue so this time it looks different. Here is a play to reproduce this:

`````` ---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: "create test-data container"
      docker:
        image: busybox
        name: test-data
        volumes: /data
        command: /bin/true
    - name: "creat test container"
      docker:
        image: busybox
        name: test
        volumes_from: test
        command: sleep 3600```
``````

**Comment by jimi-c** [comment]
@discordianfish it appears you have a typo in that playbook? The volumes_from is set to the same name as the container you're creating. When running your sample, if I change it to the name of the first container, it works as expected:

<pre>
$ docker inspect test-data-7794
...
    "Volumes": {
        "/data": "/var/lib/docker/vfs/dir/6804e41c5ed83f05c342b8a6e5516494053eb63aae1f0266817f78ea3705cc2c"
    },
$ docker inspect test-7794
    "Volumes": {
        "/data": "/var/lib/docker/vfs/dir/6804e41c5ed83f05c342b8a6e5516494053eb63aae1f0266817f78ea3705cc2c"
    },
</pre>

Based on the above, it would appear that the issue has been resolved?

**Comment by discordianfish** [comment]
@jimi-c I think my issue was related to something else, but I can confirm I'm not affected (anymore)

**Comment by jimi-c** [comment]
@discordianfish yeah, with docker it's hard to say sometimes, as the API changed so frequently before 1.0. So I'll go ahead and close this out now, and if the same issue pops up again or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you!
