### ISSUE TITLE
Installing ansible from git on a machine with python 2 and python 3

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#7796]
##### Issue Type:

Bug Report
##### Ansible Version:

Source checked out on 16 June 2014 from git.
##### Environment:

Gentoo 64-bit.
##### Summary:

Trying to install ansible from git source according to instructions located at http://docs.ansible.com/intro_installation.html
At the step: "source ./hacking/env-setup", the script assumes that /usr/bin/python points to python2 when in fact it points to python3. python2 is located at /usr/bin/python2
##### Steps To Reproduce:

On a system with both python2 and python3 installed, clone git repository and follow installation instructions.
##### Expected Results:

Error-free execution
##### Actual Results:

http://i.imgur.com/gNlGNce.png

**Comment by mpdehaan** [comment]
This is a user/python question and not a bug, please stop by IRC or ansible-project for help.

Thanks!

**Comment by ghost** [comment]
Ok. I feel that me having to change my system instead of being able to tell ansible where it should look for python is a deficiency in ansible.
