### ISSUE TITLE
Jinja variable handling inconsistencies

### ISSUE THREAD

**Issue by droopy4096** [ansible/ansible#7799]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.3 and 1.6.2
##### Environment:

Fedora 19, Centos 6
##### Summary:

Jinja templates resolve playbook variables differently from the playbook itself. Playbook variables resolve properly recursive references to other variables whereas Jinja templates do not.

Another issue is that templates do not "see" variables defined in "defaults": when variable is only defined in defaults and not anywhere else it results in error like this:

```
{'msg': "One or more undefined variables: 'dict object' has no attribute 'fact_var'", 'failed': True}
```
##### Steps To Reproduce:

sample playbook:

https://gist.github.com/droopy4096/ccd4b8415b1969a3e9bd
##### Expected Results:

```
# cat /tmp/template.txt 
Simple var
Simple var
192.168.0.123

Var extraction:

   Simple var
   Simple var
   192.168.0.123
   192.168.0.123
```
##### Actual Results:

```
# cat /tmp/template.txt 
Simple var
Simple var
192.168.0.138

Var extraction:

   Simple var
  {{simple_var}}
  {{ansible_default_ipv4.address}}
  192.168.0.138
```

**Comment by jimi-c** [comment]
The role defaults issue is due to the fact that the variable is not in the host variables list, it is a global outside of those specifically, so referencing it in that way I would expect it to return an error. I am looking into the other templating issues though.

**Comment by jimi-c** [comment]
So the issue here is that you're essentially trying to use a variable as a key into a dictionary, which is not going to work. You could do `myvars[variable]`, where the variable contains the name of the field you want, however in the case you show the variable is already rendered to its final value, so it does not make sense to use it in this way. Simply using it directly (as you do above outside of the for loop) should work, with no need to try and access it inside hostvars.

If you have any further questions, please let us know. Thanks!

**Comment by droopy4096** [comment]
Not sure about meaning of the last comment, but, since doing the trick like:

```
- hosts: keystone
  tasks:
    - set_fact: nested_var={{ nested_var }}
```

works and allows me to keep template intact - I consider this a bug, since it is being resolved properly in playbook, and subsequently becomes useful in templates. Can you please post a sample code that will work for me to confirm that this indeed resolves reported bug?

**Comment by jimi-c** [comment]
The above works for you because set_fact adds the variable to the hostvars cache for each host in the inventory. Before that, the variable is in the global pool of variables but not specifically in the hostvars cache, which is why we do not consider this a bug.
