### ISSUE TITLE
Issue using folder instead of filename in dest argument of get_url module

### ISSUE THREAD

**Issue by pkoro** [ansible/ansible#780]
The following error is generated when using as destination a folder (instead of a filename) in the get_url module:

{"changed": true, "daisychain_args": {"dest": "/tmp", "mode": "0644", "path": "/tmp/epel-release-5-4.noarch.rpm", "url": "http://ftp.ntua.gr/pub/linux/fedora-epel/5/i386//epel-release-5-4.noarch.rpm"}, "dest": "/tmp/epel-release-5-4.noarch.rpm", "failed": true, "group": "root", "md5sum": "3b3280f24c2afacf75e70f2284569161", "mode": "01777", "module": "get_url", "msg": "OK (12232 bytes)", "owner": "root", "path": "/tmp", "src": "/tmp/tmpAbXxIJ", "state": "directory", "url": "http://ftp.ntua.gr/pub/linux/fedora-epel/5/i386//epel-release-5-4.noarch.rpm"}

The operation on the node completes without error (the file is downloaded) plus when re-running the playbook everything works OK. The problem is that the first time (when the file does not yet exist) the error above is generated which breaks the playbook. 

Command line used is the following:

action: get_url url=${epel_release_url}/${epel_release_name} dest=/tmp mode=0644

The target node is Centos-5 (x86_64) light installation (packages installed are: @core,openssh-clients, python-simplejson and yum-utils). 

Current workaround is to explicitly define the filename in the dest argument:

action: get_url url=${epel_release_url}/${epel_release_name} dest=/tmp/${epel_release_name} mode=0644

**Comment by jpmens** [comment]
There's something wrong with both `mode` and `state` ... We've seen this before -- I thought it was fixed when @mpdehaan fixed the daisychaining into `file`.

Will try to look; can't at the moment though.

**Comment by mpdehaan** [comment]
It's most interesting that "state=directory" is being passed when it should be state=file, but also that "msg=" is not being set by the file module if the file module is really returning the error.   The error should be coming from there, I would suspect, but it seems to _not_ be.   There is no daisy-chaining in the test-module script, sot hat will be the easiest way to start checking.

**Comment by mpdehaan** [comment]
fixed it.    Something rather subtle with daisy-chain not passing the filename and indicating things were a file and not a directory, and then masking the result.

git pull and you should be good to go.   Thanks!
