### ISSUE TITLE
The documentation of the hostname module says /etc/hostname is not updated but…

### ISSUE THREAD

**Issue by fclaerho** [ansible/ansible#78029]
### Summary

The documentation of the hostname module, in the notes section (https://docs.ansible.com/ansible/latest/collections/ansible/builtin/hostname_module.html?highlight=hostname#notes) says that the file `/etc/hostname` is not updated BUT (at least) if we choose the systemd strategy, this module calls `hostnamectl --static set-hostname` which DOES modify the file. And looking at the source code, there's also a classic file strategy which modifies the file as well.

Could this note be removed from the documentation as it seems wrong and misleading? or is there something more to it that is not detailed in the documentation?

### Issue Type

Documentation Report

### Component Name

lib/ansible/modules/hostname.py

### Ansible Version

```console
N/A
```

### Configuration

```console
N/A
```

### OS / Environment

N/A

### Additional Information

Fixing this would prevent people to both call the hostname module plus the template module to write the `/etc/hostname` file.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by flowerysong** [comment]
Pleas take a closer look at the note. `/etc/hosts` and `/etc/hostname` are *not* the same file.

**Comment by fclaerho** [comment]
Oh wow. I've read this doc 10 times and every time I misread it as /etc/hostname. My bad!
