### ISSUE TITLE
Playbook: Failed to reload sysctl: net.ipv4.ip_forward

### ISSUE THREAD

**Issue by clasik** [ansible/ansible#7805]
##### Issue Type:

Playbook: Failed to reload sysctl: net.ipv4.ip_forward
##### Ansible Version:

1.6.2
##### Environment:

Amazon EC2
CentOS-6.5-GA-03.3-f4325b48-37b0-405a-9847-236c64622e3e-ami-6be4dc02.2 (ami-8997afe0)
##### Summary:

I am trying to install OpenShift Origin on Amazon EC2. I followed this guide: https://www.openshift.com/blogs/deploying-highly-available-openshift-origin-clusters-with-ansible
Step by step guide.
##### Steps To Reproduce:

I configured the file "group_vars / all": ec2_access_key: "XXXXXXXXXXXXXXX" ec2_secret_key: "XXXXxxxxxxXXXXXXXXXXXX" keypair: "my_key_pair" instance_type: "t1.micro" image: "ami-bf5021d6" group: "default" count: 2

And execute: 
ansible-playbook -i ec2hosts ec2.yml -e id=openshiftv1 -e ansible_ssh_private_key_file=my_key_pair.pem --user root -vvvv
##### Expected Results:

PaaS Openshift Origin, installed and configured.
##### Actual Results:

I have this errors the 2 nodos:
failed: [ec2-54-00-00-159.compute-1.amazonaws.com] => {"failed": true, "item": ""}
msg: Failed to reload sysctl: net.ipv4.ip_forward = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.default.accept_source_route = 0
kernel.sysrq = 0
kernel.core_uses_pid = 1
net.ipv4.tcp_syncookies = 1
kernel.msgmnb = 65536
kernel.msgmax = 65536
kernel.shmmax = 68719476736
kernel.shmall = 4294967296
kernel.sem = 250 32000 32 4096
net.ipv4.ip_local_port_range = 15000 35530
net.netfilter.nf_conntrack_max = 1048576
error: "net.bridge.bridge-nf-call-ip6tables" is an unknown key
error: "net.bridge.bridge-nf-call-iptables" is an unknown key
error: "net.bridge.bridge-nf-call-arptables" is an unknown key

**Comment by jimi-c** [comment]
This is more of a mailing list question than a bug, could you please re-ask this question there? Thanks!

**Comment by soichih** [comment]
I am having the same problem. I wonder why this is not considered a bug?

After looking into this a bit more deeply, it seems that, Ansible fails if "sysctl -p" command fails to apply all rules - sort of.. pre-existing problem with /etc/sysctl.conf. If Ansible was able to add options specified by the user and successfully set it on the kernel, it should consider the operation as successfull, even though there are some bogus entries in /etc/sysctl.conf.. It's not Ansible or Ansible user's fault and should be ignored.

**Comment by timesking** [comment]
Where can I follow this problem? I met the same problem.
