### ISSUE TITLE
Add some intro to execution environments to the user guide and dev guides

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#78074]
### Summary

While execution environments have their own docs, it would be good to at least mention them and what they are useful for in the main ansible docs, specifically for users who may not know about them yet, and collection developers, who may want to create their own.
NOTE - this should be focused on community-available execution envronments, not those shipped with enterprise products per se.

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/dev_guide/developing_collections_distributing.rst

### Ansible Version

```console
$ ansible --version
2.14
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by jborean93** [comment]
@samccann is this something that still needs to be done?

**Comment by samccann** [comment]
yes but a bit on hold because the are redesigning the builder for EEs and I'm clueless enough to not know if that impacts how users use 'em as well. But I could probably do a quick fix for this if I think a bit

**Comment by jborean93** [comment]
All good, this just came up in the backlog cycle and was wondering if it still needed to be opened.

**Comment by samccann** [comment]
Closing in favor of https://github.com/ansible-community/community-team/issues/161

**Comment by samccann** [comment]
if it ends up we need something here in ansible/ansible, I'll open up a fresh issue when the time comes.
