### ISSUE TITLE
git module tries to scan ssh host fingerprint with https:// URL

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#7812]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible 1.7 (devel)
##### Environment:

Debian
##### Summary:

Commit https://github.com/ansible/ansible/commit/3fb3e7e6dce046bec9d2e8c52756f368d18702c8 changed the way Ansible handles known_hosts URLs (related to issue https://github.com/ansible/ansible/issues/7474). Now `git` module tries to scan SSH fingerprint with repository URLs not related to SSH (for example `https://gitlab.com/gitlab-org/gitlab-shell.git`). If hostname is not known to SSH, `git` module fails and asks to use `accept_hostkey` option.
##### Steps To Reproduce:

Example git module task:

```
ansible localhost -m git -a 'repo=https://gitlab.com/gitlab-org/gitlab-shell.git dest=/tmp/gitlab'
```
##### Expected Results:

```
test | success >> {
    "after": "ca425566d0266a1786019153757e283d7d246450", 
    "before": "ca425566d0266a1786019153757e283d7d246450", 
    "changed": false
}
```
##### Actual Results:

```
localhost | FAILED >> {
    "failed": true, 
    "msg": "gitlab.com has an unknown hostkey. Set accept_hostkey to True or manually add the hostkey prior to running the git module"
}
```

**Comment by jimi-c** [comment]
I have merged in the above pull request to address this. Please let us know if you continue seeing any problems related to this issue. Thanks!

**Comment by drybjed** [comment]
`git` module works correctly again. Thanks!

**Comment by drybjed** [comment]
@jimi-c: the same problem showed up again, this time with `git://` URLs, like `git://github.com/ansible/ansible.git`.

**Comment by abadger** [comment]
@drybjed Just merged a PR that should fix the other non-ssh URLs: https://github.com/ansible/ansible/pull/10204
