### ISSUE TITLE
Add note about package managers

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#78187]
### Summary

Recent user noted they had to dig into the source code to realize a package manager module didn't support all the plugins of that package manager.  While each module should note this, we can also mention it at:
https://docs.ansible.com/ansible/latest/user_guide/intro_adhoc.html#managing-packages

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/user_guide/intro_adhoc.rst

### Ansible Version

```console
$ ansible --version
2.14
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by samccann** [comment]
Documentation fix:

Add the following text to https://github.com/ansible/ansible/blame/devel/docs/docsite/rst/user_guide/intro_adhoc.rst#L116 : 

Package management modules support common functions to install, remove, and generally manage packages. Some specific functions for a package manager might not be present in the Ansible module since  they are not part of general package management.

**Comment by DesmondSanctity** [comment]
I have raised a PR for this issue here https://github.com/ansible/ansible/pull/78260
