### ISSUE TITLE
ansible.builtin.include_tasks tagging incoherency

### ISSUE THREAD

**Issue by EmptyByte** [ansible/ansible#78234]
### Summary

Take the following code snippet:    
``` - name: Include | Patch
      ansible.builtin.include_tasks:
        file: "rhel{{ ansible_facts['distribution_major_version'] }}_patch.yml"
        apply:
          tags:
            - never
            - patch
      tags: [never, patch]
```

The tags options with include_tasks is counter productive. 

The tags here is indented at the include_tasks level so should apply **only** on the include statement not the tasks file What you could do is add a `tags: inherit` for that purpose. As to really pass these tags out to the included tasks file.

```- name: Include | Patch
      ansible.builtin.include_tasks:
        file: "rhel{{ ansible_facts['distribution_major_version'] }}_patch.yml"
        tags: inherit
      tags: [never, patch]`
```

That way all tasks are executed but if you want to run only tasks in that file that have these tags you can add `tags: inherit` option. So the tags will also apply. 

### Issue Type

Feature request

### Component Name

ansible.builtin.include_tasks

### Ansible Version

```console
$ ansible --version
Latest
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
N/A
```

### OS / Environment

RHEL 8

### Steps to Reproduce

` - name: Include | Patch
      ansible.builtin.include_tasks:
        file: "rhel{{ ansible_facts['distribution_major_version'] }}_patch.yml"
        apply:
          tags:
            - never
            - patch
      tags: [never, patch]`

### Expected Results

See description above.

### Actual Results

```console
included tasks are ignored if the same tags are not applied to all tasks in the include_tasks file. Absolutely counter-production.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mkrizek** [comment]
Thank you very much for your interest in Ansible. We have no plans to implement this feature at this time.

As an alternative you can use YAML anchors and/or variables to achieve the same functionality.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.libera.chat
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
