### ISSUE TITLE
Importing `ansible.template`'s `Templar` into another ansible collection module fails

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#78258]
### Summary

I'm trying to include built-in template processing capabilities into one of the ansible's ServiceNow modules (meaning, I want to use templar for this, which is defined in ansible core here: https://github.com/ansible/ansible/blob/0590ce065ce51c208bce863365fa981cd931ce93/lib/ansible/template/__init__.py#L679. The module is located in `/plugins/modules` folder).

So I want to include templar in my ServiceNow module by saying `from ansible.template import Templar` in python. After running playbook with the specified import (pretty sure the problem is not with any specific playbook, but more with the import), I get the following error:

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/92620429/178946876-34e59084-e0d3-42eb-be06-e3648ef1fb35.png">

The (almost) exact same thing happens when importing `ansible.parsing.dataloader`'s DataLoader (calling `import ansible.parsing.dataloader`) in module. Same happens if I try to execute the same imports in `/plugins/module_utils` folder.

I'm assuming the problem is something with the path in which I'm importing objects from ansible core, since the import seems to be possible in `/tests/unit/plugins/inventory/` folder. Here: https://github.com/ansible-collections/servicenow.itsm/blob/46e2df9561607ecc675e0ee0714fc830f9ec2a6a/tests/unit/plugins/inventory/test_now.py#L17. 

Any idea if imports from ansible core into other collections' `/plugins/module` folder is even possible? If the answer is yes, how to create such an import? If no, is it possible to obtain the functionality of Templar and DataLoader by creating class that inherits from mixin classes built in ansible core and which ones? 

Any help would be appreciated.

### Issue Type

Bug Report

### Component Name

module, import

### Ansible Version

```console
$ ansible --version

ansible 2.10.17
  config file = None
  configured module search path = ['/Users/tjazerzen/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tjazerzen/Documents/XLAB/ansible_projects/venv/lib/python3.9/site-packages/ansible
  executable location = /Users/tjazerzen/Documents/XLAB/ansible_projects/venv/bin/ansible
  python version = 3.9.13 (main, May 24 2022, 21:13:51) [Clang 13.1.6 (clang-1316.0.21.2)]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

COLLECTIONS_PATHS(env: ANSIBLE_COLLECTIONS_PATH) = ['/Users/tjazerzen/Documents/XLAB/ansible_projects']
```

### OS / Environment

OS X.

### Steps to Reproduce

1. Say `from ansible.template import Templar` in arbitrary module inside ansible collection in `/plugins/modules` folder.

2. Build playbook to run that script (content is not important, it just has to be syntactically correct). In my example, it would have been this: 
<img width="584" alt="image" src="https://user-images.githubusercontent.com/92620429/178951420-b604340c-9817-496f-bee8-5020f8fc5afb.png">

3. Run the playbook.

### Expected Results

I expected import would have been executed successfully.

### Actual Results

```console
`The full traceback is:
Traceback (most recent call last):
  File "/Users/tjazerzen/.ansible/tmp/ansible-tmp-1657791214.521861-8474-81880761610839/AnsiballZ_api.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/tjazerzen/.ansible/tmp/ansible-tmp-1657791214.521861-8474-81880761610839/AnsiballZ_api.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/tjazerzen/.ansible/tmp/ansible-tmp-1657791214.521861-8474-81880761610839/AnsiballZ_api.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.servicenow.itsm.plugins.modules.api', init_globals=None, run_name='__main__', alter_sys=True)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 225, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/folders/9s/v0gzy6497956yzhn8x7gf8mh0000gn/T/ansible_servicenow.itsm.api_payload_sic1ms05/ansible_servicenow.itsm.api_payload.zip/ansible_collections/servicenow/itsm/plugins/modules/api.py", line 198, in <module>
  File "/Users/tjazerzen/Documents/XLAB/ansible_projects/venv/lib/python3.9/site-packages/ansible/template/__init__.py", line 51, in <module>
    from ansible.module_utils.compat.importlib import import_module
ModuleNotFoundError: No module named 'ansible.module_utils.compat.importlib'
`
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mkrizek** [comment]
Ansible modules can only import from `module_utils`. Templating always happens on the controller as opposed to modules which are executed on the target machine(s). Technically you could use `Templar` in the corresponding action plugin to your module.

**Comment by tjazsch** [comment]
Nevermind, found example in kubernetes.core module (where template is read). Thank you. Closing the issue.
