### ISSUE TITLE
If python discovery fails due to a connection error, it defaults to /usr/bin/python and then continues to try to execute the intended command regardless

### ISSUE THREAD

**Issue by jnm27** [ansible/ansible#78264]
### Summary

When the auto discovery method is used, python discovery happens first, and then the task command is executed.

However, if there is a connection problem, depending on the timing of when the connection gets restored, the python discovery could fail due to an AnsibleConnectionFailure, ignore it, and return /usr/bin/python. Then, the task command is executed with the wrong python interpreter.

It should be that if the python discovery fails (at least due to Connection failures - you could decide there are other cases where this should occur), that the command immediately fails. Or at least have an option to allow this behavior.

Here is the informal code change that we made to enable this behavior in /usr/local/lib/python3.8/site-packages/ansible/executor/interpreter_discovery.py:

```
@@ -14,6 +14,7 @@
 from ansible.module_utils.distro import LinuxDistribution
 from ansible.utils.display import Display
 from ansible.utils.plugin_docs import get_versioned_doclink
+from ansible.errors import AnsibleConnectionFailure
 from distutils.version import LooseVersion
 from traceback import format_exc

@@ -146,6 +147,8 @@
         return platform_interpreter
     except NotImplementedError as ex:
         display.vvv(msg=u'Python interpreter discovery fallback ({0})'.format(to_text(ex)), host=host)
+    except AnsibleConnectionFailure as ex:
+        raise ex
     except Exception as ex:
         if not is_silent:
             display.warning(msg=u'Unhandled error in Python interpreter discovery for host {0}: {1}'.format(host, to_text(ex)))
```

Simply allow the exception to fall-through to fail the task with a connection error, which will fail the task appropriately or allow the connection plugins to handle it appropriately.

### Issue Type

Bug Report

### Component Name

interpreter_python.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.5]
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.6 (default, Jan 22 2021, 11:41:28) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.0.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

RHEL8

### Steps to Reproduce

```yaml (paste below)
ansible <host> -m ping -vvv
```
on a host that is down

### Expected Results

if the discovery fails due to a connection problem, the task fails

### Actual Results

```console
if the discovery fails due to a connection problem, it tries to execute the rest of the task anyway
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mattclay** [comment]
@jnm27 Do you want to open a PR with your proposed fix?

**Comment by sivel** [comment]
I think we probably want to switch out `AnsibleConnectionFailure` for a more generic `AnsibleError`

**Comment by jnm27** [comment]
It is a real connection failure though; that type of exception is useful for me. Up to you though.

**Comment by Akasurde** [comment]
@jnm27 Would you be interested in opening a PR with your findings? Let us know. Thanks.,

**Comment by jnm27** [comment]
@Akasurde I don't have time right now to open a PR but I have implemented this patch in our baseline which has worked for us.

```--- /usr/local/lib/python3.8/site-packages/ansible/executor/interpreter_discovery.py    2022-08-12 03:40:14.601235102 +0000
+++ interpreter_discovery.py    2022-08-12 03:45:26.613729000 +0000
@@ -14,6 +14,7 @@
 from ansible.module_utils.distro import LinuxDistribution
 from ansible.utils.display import Display
 from ansible.utils.plugin_docs import get_versioned_doclink
+from ansible.errors import AnsibleConnectionFailure
 from ansible.module_utils.compat.version import LooseVersion
 from ansible.module_utils.facts.system.distribution import Distribution
 from traceback import format_exc
@@ -150,6 +151,8 @@
         return platform_interpreter
     except NotImplementedError as ex:
         display.vvv(msg=u'Python interpreter discovery fallback ({0})'.format(to_text(ex)), host=host)
+    except AnsibleConnectionFailure as ex:
+        raise ex
     except Exception as ex:
         if not is_silent:
             display.warning(msg=u'Unhandled error in Python interpreter discovery for host {0}: {1}'.format(host, to_text(ex)))
```

**Comment by jnm27** [comment]
Thanks @Akasurde
