### ISSUE TITLE
ec2_group with wide open rule can't be run multiple times

### ISSUE THREAD

**Issue by mpeters** [ansible/ansible#7832]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.2
##### Environment:

Ansible running on Fedora 20. EC2 API is the target.
##### Summary:

If you have a wide open security rule for a group (-1 for proto, from_port and to_port with a cidr of 0.0.0.0/0) it can only be run once. Subsequent run will fail.
##### Steps To Reproduce:

I have the following as part of a playbook that makes sure we have the
appropriate security groups setup and all of them work just fine
except this one:

``` yaml
- name: Create wide-open testing security group
  local_action:
    module: ec2_group
    name: 'WIDE OPEN'
    description: 'WIDE OPEN for TESTING ONLY!'
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    state: present
    rules:
      # everything from anywhere
      - proto: -1
        from_port: -1
        to_port: -1
        cidr_ip: 0.0.0.0/0
```

The first time I run the playbook with this task it works just fine.
But every time it's run after that it fails. Other rules in other ec2_group tasks in this same playbook execute as expected when run multiple times.
##### Expected Results:

It should recognize that the rule already exists like it does every other rule and just skip it.
##### Actual Results:

It fails with the following error:

```
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/mpeters/.ansible/tmp/ansible-tmp-1403183990.17-2723736991339/ec2_group", line 1754, in <module>
    main()
  File "/home/mpeters/.ansible/tmp/ansible-tmp-1403183990.17-2723736991339/ec2_group", line 268, in main
    group.authorize(rule['proto'], rule['from_port'], rule['to_port'], ip, grantGroup)
  File "/usr/lib/python2.7/site-packages/boto/ec2/securitygroup.py", line 204, in authorize
    dry_run=dry_run)
  File "/usr/lib/python2.7/site-packages/boto/ec2/connection.py", line 3144, in authorize_security_group
    params, verb='POST')
   File "/usr/lib/python2.7/site-packages/boto/connection.py", line 1196, in get_status
    raise self.ResponseError(response.status, response.reason, body)
```

boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
    <?xml version="1.0" encoding="UTF-8"?>
    <Response><Errors><Error><Code>InvalidPermission.Duplicate</Code><Message>the specified rule "peer: 0.0.0.0/0, ALL, ALLOW" already exists</Message></Error></Errors><RequestID>40ddc890-fa3a-4528-9cf8-10cf47f3e4d6</RequestID></Response>

**Comment by mpeters** [comment]
This seems to happen with more restrictive rules as well. A rule like this will trigger it:

``` yaml
       - proto: tcp
         from_port: 8000
         to_port: 65000
         cidr_ip: 200.60.40.200/32
```

I think it has trouble when the from_port and to_port are not the same.

**Comment by jimi-c** [comment]
I could not get the second example to reproduce the error, however the above patch I've merged in resolves the original issue. If you continue seeing any problems with this, please let us know. Thanks!
