### ISSUE TITLE
Array manipulation inside quote is treated as plain string

### ISSUE THREAD

**Issue by okozachenko1203** [ansible/ansible#78343]
### Summary

When I try to append string elements to an array in `set_fact`, it is treated as plain text.
#### Version
```
ansible >=6.0.0
ansible-core: 2.13.1, 2.13.2
```
#### Task body is;
```
- set_fact:
    _test: "[] + ['a'] + ['b'] + ['c']"
- debug:
    msg: "{{ _test }}"

```
The result is;
```
TASK [set_fact] ****************************************************************
ok: [ctl1]

TASK [debug] *******************************************************************
ok: [ctl1] => {
    "msg": "[] + ['c'] + ['b'] + ['a']"
}
```
Expected result is
```
TASK [set_fact] ****************************************************************
ok: [ctl1]

TASK [debug] *******************************************************************
ok: [ctl1] => {
    "msg": [
        "c",
        "b",
        "a"
    ]
}
```

When I use `ansible<6.0.0`, it works as expected.

### Issue Type

Bug Report

### Component Name

set_fact

### Ansible Version

```console
ansible >=6.0.0
ansible-core: 2.13.1, 2.13.2
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
# returns empty
```

### OS / Environment

Ubuntu focal

### Steps to Reproduce

```yaml (paste below)
tasks:
  - set_fact:
      _test: "[] + ['a'] + ['b'] + ['c']"
  - debug:
      msg: "{{ _test }}"
```

### Expected Results

I expect array `[a,b,c]`.

### Actual Results

```console
It returns `[] + ['c'] + ['b'] + ['a']`.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by bcoca** [comment]
it is plain text, use `{{ }}` to force 'evaluation':
```
  _test: "{{[] + ['a'] + ['b'] + ['c']}}"
```

**Comment by okozachenko1203** [comment]
> it is plain text, use `{{ }}` to force 'evaluation':
> 
> ```
>   _test: "{{[] + ['a'] + ['b'] + ['c']}}"
> ```

@bcoca well, i think it is wrong syntax.
```
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected key

The error appears to be in '/root/.ansible/collections/ansible_collections/vexxhost/atmosphere/playbooks/test.yml': line 18, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

        _test: "{{[] + ['a'] + ['b'] + ['c']}}"
    - debug:
    ^ here

```

**Comment by flowerysong** [comment]
It's treated as a plain string because it *is* a plain string. This used to work because of a bug in Ansible's expression processing which was fixed in ansible-core 2.13 and noted in the porting guide: https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_6.html#playbook

**Comment by okozachenko1203** [comment]
aha, ok
@bcoca @flowerysong  thanks.

**Comment by okozachenko1203** [comment]
```
- set_fact:
    _test: "{{[] + [item/32]}}"
  loop: "{{ host_list }}"

- debug:
    msg: "{{ _test }}"
```
In this case, how i can distinguish `item` variable with string suffix `/32`?

**Comment by okozachenko1203** [comment]
ok, so i did it. No need to mention template boundary again inside it.
