### ISSUE TITLE
active path of the pipe lookup_plugin changed

### ISSUE THREAD

**Issue by ramondelafuente** [ansible/ansible#7834]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.1
##### Environment:

OSX  10.9.3
##### Summary:

When setting a variable to the value "{{ lookup('pipe', 'pwd') }}" in the root of a playbook, and then using that variable inside a role, the working directory for the command has changed between ansible versions 1.5 and 1.6
##### Steps To Reproduce:

Here's a test repo: https://github.com/ramondelafuente/ansible-lookup-plugin-tests
Run with `ansible --version && ansible-playbook -i testing/hosts testing/playbook.yml`

There's not so much "expected results", it's more about "something changed, was this intended". I'll post the results from version 1.5.5 as 'expected' and version 1.6.0 as 'actual'
##### Expected Results:

**In Ansible v1.5.5**

```
TASK: [test_role_with_files | task_in_role_wit_files_variable] ****************
    "local_file_name": "/Users/fzz/Projects/future500/vps-provisioning/testing"
TASK: [test_role_with_files | task_in_role_with_files_lookup_plugin] **********
    "msg": "/Users/fzz/Projects/future500/vps-provisioning/testing/test_role_with_files/files"
TASK: [test_role_without_files | task_in_role_without_files_variable] *********
    "local_file_name": "/Users/fzz/Projects/future500/vps-provisioning/testing"
TASK: [test_role_without_files | task_in_role_without_files_lookup_plugin] ****
    "msg": "/Users/fzz/Projects/future500/vps-provisioning/testing/test_role_without_files/tasks"
TASK: [task_in_playbook_with_variable] ****************************************
    "local_file_name": "/Users/fzz/Projects/future500/vps-provisioning/testing"
TASK: [task_in_playbook_with_lookup_plugin] ***********************************
    "msg": "/Users/fzz/Projects/future500/vps-provisioning/testing"
```
##### Actual Results:

**In Ansible v1.6.1**

```
TASK: [test_role_with_files | task_in_role_wit_files_variable] **************** 
    "local_file_name": "/Users/fzz/Projects/future500/vps-provisioning/testing/test_role_with_files/files"
TASK: [test_role_with_files | task_in_role_with_files_lookup_plugin] ********** 
    "msg": "/Users/fzz/Projects/future500/vps-provisioning/testing/test_role_with_files/files"
TASK: [test_role_without_files | task_in_role_without_files_variable] ********* 
    "local_file_name": "/Users/fzz/Projects/future500/vps-provisioning/testing/test_role_without_files/tasks"
TASK: [test_role_without_files | task_in_role_without_files_lookup_plugin] **** 
    "msg": "/Users/fzz/Projects/future500/vps-provisioning/testing/test_role_without_files/tasks"
TASK: [task_in_playbook_with_variable] **************************************** 
    "local_file_name": "/Users/fzz/Projects/future500/vps-provisioning/testing"
TASK: [task_in_playbook_with_lookup_plugin] *********************************** 
    "msg": "/Users/fzz/Projects/future500/vps-provisioning/testing"
```

**Comment by mpdehaan** [comment]
It should be role aware so I'd consider this a bug fix - let me know if you disagree.

Please stop by ansible-project if you have user questions that you are not sure are bugs or not so we can have a discussion, otherwise we end up with a lot of tickets to sort through that are really Q&A.

Thanks!

**Comment by ramondelafuente** [comment]
I agree - I think. But it's still a BC break so I thought I'd bring it up. I did so on ansible-devel, because it's core code. 

I find it a bit unfriendly that I was asked by @jimi-c on ansible-devel to open an issue, only to be told I opened an unneccesary ticket. Stop confusing me ;-)
