### ISSUE TITLE
Setting dir vs file permissions with "file state=directory mode=0775 recurse=yes"

### ISSUE THREAD

**Issue by pfalcon** [ansible/ansible#7839]
##### Issue Type:

Bug Report, submitted on James Cammarata's suggestion, based on the thread https://groups.google.com/forum/#!searchin/ansible-project/Setting$20dir$20vs$20file$20permissions/ansible-project/nsJrGs3kA48/f5_mLA1h4VUJ
##### Ansible Version:

```
$ ansible --version
ansible 1.6.2
```
##### Environment:

Ubuntu 12.04
##### Summary:

Based on the google groups thread linked above, "file state=directory mode=0775 recurse=yes" action is supposed to set mode _only_ on directories, recursively. Actual behavior is that all files are set to the specified mode, which effectively marks them as executable, which is not intended effect.

Note that besides making recurse=yes apply mode only to dir, another approach is to support symbolic permission modes, like POSIX chmod command does (e.g. "g+X" will set group (and only group) directory permission to "x" (i.e. searchable), without affecting files' permissions).
##### Steps To Reproduce:

I used following task:

```
 - name: Set download dir permissions
   file: dest={{www_dir}} state=directory
         owner=linaro-ci-publish group=bot-publishers
         mode=0775
         recurse=yes
   sudo: yes
```

`{{www_dir}}` contains, among others, following file:

```
-rw-rw-r--  1 www-data www-data   11 Mar 20  2013 HEADER.html
```
##### Expected Results:

I expected the file above to retain its permissions after the task is run.
##### Actual Results:

Actually file became:

```
 -rwxrwxr-x  1 linaro-ci-publish bot-publishers   11 Mar 20  2013 HEADER.html
```

**Comment by mpdehaan** [comment]
"Based on the google groups thread linked above, "file state=directory mode=0775 recurse=yes" action is supposed to set mode only on directories, recursively"

I do not agree this was stated, I would say rather it's undefined right now.

**Comment by pfalcon** [comment]
I'm quoting @jimi-c on that: as a follow up to that thread, sent unfortunately  just to me, he suggested (hope it's not considered private to be quoted here):

> The docs are correct, however this appears to be a bug. Please open a
> github issue for it and we will correct it.
> Thanks!

So, I just hope this ticket will allow to come to conclusion on this matter (the real solution would be to support symbolic modes).

**Comment by holms** [comment]
well when we gonna have directory only permissions please? chef and puppet has it.. how can we even survive without this? I thought just adding g+rwX will help but it's not

```
TASK: [file path=/var/www/project owner=www group=www mode=g+rwX recurse=yes] ***
failed: [web] => {"details": "invalid literal for int() with base 8: 'g+rwX'", "failed": true, "gid": 1001, "group": "www", "mode": "0755", "owner": "www", "path": "/var/www/project", "size": 4096, "state": "directory", "uid": 1003}
msg: mode needs to be something octalish
```

**Comment by cmhamill** [comment]
A pull request providing this functionality is already in the queue, FYI: https://github.com/ansible/ansible/pull/5220

**Comment by mpdehaan** [comment]
"Based on the google groups thread linked above, "file state=directory mode=0775 recurse=yes" action is supposed to set mode only on directories, recursively"

This feels weird with respect to chmod.

**Comment by cmhamill** [comment]
I'd personally expect "file state=directory mode=0775 recurse=yes" to set the directory and all its children (files and directory) to mode 0775, on the grounds that that's what I told it to do.

I still vote for supporting symbolic modes, which will be unambiguous and allow "file state=directory mode='u=rwX,g=rX,o=rX' recurse=yes".

**Comment by 1stvamp** [comment]
Echoing what others have stated, if I translate the file task above into a chmod shell command: `chmod -R 0777`
That will indeed affect all children directories **and** files.
Retaining this functionality, for parity which chmod, and adding symbolic modes would be the logical way forward.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

Based on the above discussion, and the fact that we have merged in #5220 now, we are going to close this ticket. As noted, `chmod -R` would indeed affect all files and directories, though now with the symbolic mode support the results of this can be more finely controlled than before.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by fcntl** [comment]
> As noted, chmod -R would indeed affect all files and directories

So fucking what? Fuck chmod and fuck the retards who think not being able to set file vs dir permissions is useful. This fucking bullshit is what make people hate open source elitists who don't give a fuck what their users want.

**Comment by xdfil** [comment]
> So fucking what?

Agreed. chmod -R isn't the only way to set permissions recursively. So what does that have to do with the capabilities of the file module? What good is an automation language that is more difficult to use than a native shell script?

Real Unix admins use `find /path -type d -exec chmod 0775 {} \; && find /path -type f -exec chmod 0644 {} \;` we don't just set all files to executable with `chmod -R`

How about an option on the file module called `dir_mode` that allows an alternate mode for directories?

**Comment by ebikt** [comment]
xdaxdb: Or maybe `file_mode` wich will affect all non-directory entries, so that `mode` will be coherent with the toplevel directory.
