### ISSUE TITLE
Ansible doesn't like empty (like, commented out) var files

### ISSUE THREAD

**Issue by pfalcon** [ansible/ansible#7843]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.6.2
```
##### Environment:

Ubuntu 12.04
##### Summary:

Suppose you had a group var file (`group_vars/foo`) with one variable defined. Suppose for some time, you know longer need that var to be defined, but expect later it to be needed again (and/or you just want to document why var is so far not needed, for the benefit of your colleagues). But Ansible suddenly starts to error out on such var file (which now consists only of comments).
##### Steps To Reproduce:

We have group_vars/ec2. Due to #7841, we had to change it to:

```
# Production instances now use real usernames, so use --user=
# ansible_ssh_user: ubuntu
```
##### Expected Results:

Ansible happy as before.
##### Actual Results:

Now if we run playbook using that var file, it leads to following error:

```
ERROR: /home/pfalcon/devel/linaro/linaro-jenkins-tools/ansible/group_vars/ec2 must be stored as a dictionary/hash
```

**Comment by mpdehaan** [comment]
Data files need to be valid YAML

You can fix this by just having a file that starts with "---".

**Comment by pfalcon** [comment]
Thanks for hint, but with following var file:

```
---
# Production instances now use real usernames, so use --user=
# ansible_ssh_user: ubuntu
```

I get exactly the same error:

```
PLAY [jenkins-generic] ******************************************************** 
ERROR: /home/pfalcon/devel/linaro/linaro-jenkins-tools/ansible/group_vars/ec2 must be stored as a dictionary/hash
```

**Comment by nocive** [comment]
+1

**Comment by pfalcon** [comment]
So, can this ticket be reopened please? @jimi-c ?

**Comment by jimi-c** [comment]
I went ahead and pushed a quick fix for this. Let us know if you continue seeing any issues related to this. Thanks!

**Comment by a-buck** [comment]
Hi @jimi-c  sorry to comment on such an old thread, but did this ever get merged? I am experiencing the same issue now

**Comment by jimi-c** [comment]
It should have been, yes, per my comment above. With which version of Ansible are you seeing this occur?

**Comment by Oneiroi** [comment]
Ansible 2.1 returns this error `must be stored as a dictionary/hash` when attempting to include a large YAML file.

```
>>> import yaml
>>> yaml.safe_load('cis.yml')
>>> yaml.safe_load(open('cis.yml'))
{'cis': {'disallowed_services': ['chargen-dgram', 'chargen-stream', 'daytime-dgram'
... snipped for brevity ...
```

Each line has a comment indicating which section of the CIS standard the variable belongs e.g.

```
$ cat cis.yml
---
cis:
  disallowed_filesystems:
    - cramfs               #1.1.18
    - freevxfs             #1.1.19
    - jffs2                #1.1.20
    - hfs                  #1.1.21
    - hfsplus              #1.1.22
    - squashfs             #1.1.23
    - udf                  #1.1.24
... snipped for brevity ...
```

@mpdehaan as can be seen this is completely valid YAML and is loaded without issue, can you comment on what the issue is as I do not think it is related to the comments in the YAML.

UPDATE: Opening with yaml as per above and saving out again (to remove the comments) results in the same error

**Comment by Oneiroi** [comment]
After further analysis the error was presented as it could not locate the variable file to be included, and was not an issue with the YAML itself. The error message is miss leading in this regard.
