### ISSUE TITLE
Remove FAQ about not having Ansible as wheels

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#78485]
### Summary

Ansible as wheels has been supported since 2.13 so remove the FAQ entry at https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#why-don-t-you-ship-ansible-in-wheel-format-or-other-packaging-format

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/reference_appendices/faq.rst

### Ansible Version

```console
$ ansible --version
2.13
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by samccann** [comment]
Docs fix:
Remove https://github.com/ansible/ansible/blame/devel/docs/docsite/rst/reference_appendices/faq.rst#L712 through L719 (aka the whole section including anchor).

**Comment by akamanzi** [comment]
@samccann, Can I take on this issue? looks like an easy fix and would be my first contribution.

**Comment by samccann** [comment]
@akamanzi yes please do! Thanks!

**Comment by akamanzi** [comment]
@samccann, can you check/review (if you get the chance) PR #78524 made for this issue and advise if it has the correct/desired changes.

Thank you

**Comment by samccann** [comment]
Closed by https://github.com/ansible/ansible/pull/78524
