### ISSUE TITLE
Python 3 page in appendix is outdated

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#78493]
### Summary

This page still has older python versions listed:
https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html

Specifically this note is incorrect:
"On the controller we support Python 3.5 or greater and Python 2.7 or greater. Module-side, we support Python 3.5 or greater and Python 2.6 or greater."

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/reference_appendices/python_3_support.rst

### Ansible Version

```console
$ ansible --version
2.14
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by samccann** [comment]
Once https://github.com/ansible/ansible/pull/78468 is merged, we can reuse the python tables there to clarify requirements.

**Comment by Aysha-py** [comment]
@samccann Hi, I am from the Ansible writers community, is this issue still open? I want to make contributions to it.

**Comment by samccann** [comment]
Hi @Aysha-py ! Yes this is still available.  The specific changes are:

1. Change note at https://github.com/ansible/ansible/blame/devel/docs/docsite/rst/reference_appendices/python_3_support.rst#L9  to:
```
See :ref:`Control Node Requirements <control_node_requirements>` and :ref:`Managed Node Requirements <managed_node_requirements>` for the specific versions supported.
```

Change line https://github.com/ansible/ansible/blame/devel/docs/docsite/rst/reference_appendices/python_3_support.rst#L21 to:
`  python version = 3.10.5 (main, Jun  9 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)] (/usr/bin/python)`

**Comment by Aysha-py** [comment]
Hi Sandra, Sorry for the late reply. I would revert back to you if I have
any questions. Thank you. Regards
