### ISSUE TITLE
content argument of copy module doesn't add end of line character

### ISSUE THREAD

**Issue by ryan-lane** [ansible/ansible#7855]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.3
##### Environment:

Ubuntu 14.04
##### Summary:

When using content='blah' for a file, the file will have 'blah' with no end of line character, which is generally an invalid file.
##### Steps To Reproduce:

``` yaml
- name: Add world to /tmp/hello
  copy: dest=/tmp/hello content='world'
```
##### Expected Results:

/tmp/hello:

```
world<end-of-line>
```
##### Actual Results:

/tmp/hello:

```
world
```

**Comment by jimi-c** [comment]
The content is verbatum, so just add a '\n' to it if you want a newline. Files without newlines are not "generally invalid", as there are plenty of config files that do not end with a newline. If you have any further questions regarding this, please let us know. Thanks!

**Comment by ryan-lane** [comment]
http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_205

POSIX states that text files should end with a newline to specify end of file. It might be a problem for this to be the default for people writing binary into their files via content (do people actually do this?) but for the vast majority of cases the module is likely writing POSIX in-compliant files.

**Comment by jimi-c** [comment]
Feel free to send in a PR to check for a newline at the end of content, and to add one if it doesn't exist.
