### ISSUE TITLE
check_mode for unarchive module is not supported for gzipped tar files

### ISSUE THREAD

**Issue by pc-explore** [ansible/ansible#78564]
### Summary

The documentation on https://docs.ansible.com/ansible/latest/collections/ansible/builtin/unarchive_module.html states that the module fully supports check-mode.
But the fact is that check-mode is not supported when it concerns a gzipped tar file cfr. https://github.com/ansible/ansible-modules-core/blob/00911a75ad6635834b6d28eef41f197b2f73c381/files/unarchive.py#L591
I was mislead by the '_fully_ supported' and noticed that the step was skipped in check-mode.
Wouldn't it make sense to adapt the documentation accordingly ?

### Issue Type

Documentation Report

### Component Name

https://github.com/ansible/ansible-modules-core/blob/00911a75ad6635834b6d28eef41f197b2f73c381/files/unarchive.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.6]
  config file = ansible.cfg
  configured module search path = ['/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/<user>/.ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 2.11.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Debian 11

### Additional Information

When the documentation is adapted, it is clear for everyone that unarchiving gzipped tar files is not check_mode compatible.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by samccann** [comment]
Documentation fix:
1. Change **full** to **partial** at https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/unarchive.py#L126
2. Below that, add - details: Not supported for gzipped tar files.
