### ISSUE TITLE
env-setup only works in current process

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#7862]
I'm following the instructions from the Ansible docs to install from source. The env-setup script only modifies the $PATH variable in the current process, so the `ansible` command doesn't run globally. Should the instructions include additional steps to make this work?

**Comment by jimi-c** [comment]
We assume a little bit of general knowledge in regards to running from source, so if you'd like to always have the ansible\* commands available globally from source install you should add the `source /path/to/ansible/hacking/env-setup` command to either your .bash_profile. To make that globally accessible to all users, just add it the proper config file in /etc for your distribution (ie. /etc/profile.d/ansible.sh). The setup for OSX would of course be a little different.

If you have any further questions regarding this, please direct them to the mailing list. Thanks!
