### ISSUE TITLE
Expose task ignored status to CallbackBase

### ISSUE THREAD

**Issue by jhg03a** [ansible/ansible#78684]
### Summary

I'm working on my own custom callback plugin derivative of the stock json_file plugin.  As it stands within the `v2_playbook_on_stats` function, I can know for any given task what the state is via the boolean values aligning with the change verbs (changed, failed, etc) and the AggregateStats object.  However, there are verbs in the AggregateStats block which are missing from the properties of the task.  Most importantly I'd very much like an ignored boolean to be present so that I can tell the difference between tasks that failed fatally or failed but were ignored.  I believe exposing these additional verb states could aid other callback plugin developers to expose more finessed output to reflect what actually happened during their execution. 

### Issue Type

Feature Idea

### Component Name

CallbackBase

### Additional Information

As a callback plugin developer from within `v2_playbook_on_stats` I'd like to find a new boolean at the path: `self.results[0].tasks[0].hosts['my_host'].ignored`

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by bcoca** [comment]
you already get this info when the on_failed method gets called, the play does not keep track after that, but you could do so in the callback itself

**Comment by jhg03a** [comment]
Can you pass data from on_failed to on_stats?

**Comment by bcoca** [comment]
you can keep data in the callback object itself that is set in one and readable in the other, plenty of plugins do this, like those that take time measurements

**Comment by jhg03a** [comment]
Ah ha, yep, you right.  That solves my issue, thanks!
