### ISSUE TITLE
Get stdout using loop

### ISSUE THREAD

**Issue by alozovskoy** [ansible/ansible#7873]
How i can get stdout using loop (f.e. for with_sequence statement)?

An example of how I want to use it:
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  
  tasks:
  - name: "TEST"
    command: curl -o /dev/null --silent --head --write-out "%{http_code}" http://host"{{ item }}":80
    register: status
    with_sequence: count=4
  - debug: msg="{{ item.stdout }}"

**Comment by jimi-c** [comment]
Hi, we like to reserve github for bugs and feature requests. General usage questions should be asked on the ansible-project group/mailing list. Thanks!
