### ISSUE TITLE
Amazon EC2 modules equals sign instead of colon yaml syntax and unable to get the VPC module working

### ISSUE THREAD

**Issue by hyperfocus1338** [ansible/ansible#7879]
##### Issue Type:

“Bug Report”, “Feature Idea”, “Documentation Report”
##### Ansible Version:

ansible 1.6.3
##### Environment:

Ubuntu 14.04 trusty tahr
##### Summary:

Basically unable to get VPC to do what I want it to do in multiple ways, and question about the different ways on how to write ansible scripts.

I think that most (not all) ec2 module example syntax is inconsistent (colon instead of key=value) with the rest of the ansible module examples syntax. Which in turn is making the process of creating your own playbooks a little bit confusing.

I'm using this for syntax highlighting in sublime text, which works beautifully for the key=value syntax but not for the ':' syntax: https://github.com/clifford-github/sublime-ansible

It's possible to write the Ansible syntax like the way I am used to in other examples (i.e. using '=' instead of ':' as seperators), but not so easily in all occassions.

Why is it that most (not all) ec2 module examples are written with ':' instead of '=' ? And is it possible to rewrite all examples with the equals sign (key=value) syntax? Is there anything I would need to be aware of? Usually it works, but it's not always as easy to do.
##### Steps To Reproduce:

I have pasted the errors with examples in the below gist: https://gist.github.com/hyperfocus1337/a373a081ee9bce6deace

So the main issues I am facing is that I'm not sure how I would declare resource_tags (a dictionary) with the '=' syntax, which results in: msg: this module requires key=value arguments.

And with both the '=' and ':' syntax I'm getting: TypeError: 'NoneType' object is not iterable.
##### Expected Results:

Would like to create the VPC with the options declared in the play, but it ended in errors I don't know how to deal with.
##### Actual Results:

It resulted in errors described above.

**Comment by mpdehaan** [comment]
Hi hyperfocus1337,

For questions, we prefer folks ask them on ansible-project rather than filing a bug report.  It may be you have a bug.

Complex arguments in Ansible (colons and native yaml vs key=value) are available for all modules and are the easiest ways to pass structured data.   

If you can post the question to ansible-project we'll get you sorted out.   It may be there is a case where we need to catch a particular error, and that part would be a bug since we like to catch tracebacks.
