### ISSUE TITLE
Unable to intercept fqcn modules via action plugins

### ISSUE THREAD

**Issue by ryaner** [ansible/ansible#78857]
### Summary

**Note:** First off I am not 100% that this is a bug. It could very well be that the short name behaviour that we and other uses is an unintended consequence, and if so confirmation of the same is probably enough. If we should be able to intercept, some guidance on how we should go about modifying the task executor would be appreciated and we can PR based on that.

Currently we have a number of action plugins which intercept upstream plugins to do things like inject passwords, or guard certain functions for our environment. General [prerequisite work before modules execute](https://docs.ansible.com/ansible/latest/plugins/action.html) as per the docs.

Example would be the [jira plugin](https://docs.ansible.com/ansible/latest/collections/community/general/jira_module.html) where we inject username and password for users instead of requiring it in definition or playbook header.

Our action plugin lives at `plugins/action/jira.py` and gets call when a user calls jira via the shortname. If a user switches over the the fqcn of `community.general.jira`, our action plugin no longer intercepts the call, reverting back to the [`normal` action plugin](https://github.com/ansible/ansible/blob/86b86398f0e0c61df615d1fcf7643f01a1084327/lib/ansible/executor/task_executor.py#L1120).

### Issue Type

Bug Report

### Component Name

task_executor

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.4]
  config file = /usr/share/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/library']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /usr/lib/python3.8/site-packages/ansible_collections
  executable location = /usr/bin/ansible
  python version = 3.8.13 (default, Apr 28 2022, 12:34:52) [GCC 8.3.1 20190311 (Red Hat 8.3.1-3)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CALLBACKS_ENABLED(/usr/share/ansible/ansible.cfg) = ['syslog', 'timer', 'yaml']
COLLECTIONS_PATHS(/usr/share/ansible/ansible.cfg) = ['/usr/lib/python3.8/site-packages/ansible_collections']
COLOR_VERBOSE(/usr/share/ansible/ansible.cfg) = bright blue
DEFAULT_ACTION_PLUGIN_PATH(/usr/share/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/action']
DEFAULT_CALLBACK_PLUGIN_PATH(/usr/share/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/callback']
DEFAULT_FILTER_PLUGIN_PATH(/usr/share/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/filter']
DEFAULT_GATHERING(/usr/share/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/usr/share/ansible/ansible.cfg) = ['/usr/share/ansible/inventory/consort.yml']
DEFAULT_INVENTORY_PLUGIN_PATH(/usr/share/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/inventory']
DEFAULT_LOAD_CALLBACK_PLUGINS(/usr/share/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/usr/share/ansible/ansible.cfg) = /root/.ansible/logs/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/usr/share/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/lookup']
DEFAULT_MODULE_PATH(/usr/share/ansible/ansible.cfg) = ['/usr/share/ansible/library']
DEFAULT_MODULE_UTILS_PATH(/usr/share/ansible/ansible.cfg) = ['/usr/share/ansible/module_utils']
DEFAULT_ROLES_PATH(/usr/share/ansible/ansible.cfg) = ['/usr/share/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/usr/share/ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/usr/share/ansible/ansible.cfg) = 15
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /root/.ansible/.vault_pass.key
INVENTORY_CACHE_PLUGIN(/usr/share/ansible/ansible.cfg) = jsonfile
INVENTORY_CACHE_PLUGIN_CONNECTION(/usr/share/ansible/ansible.cfg) = /root/.ansible/cache
RETRY_FILES_ENABLED(/usr/share/ansible/ansible.cfg) = False
TRANSFORM_INVALID_GROUP_CHARS(/usr/share/ansible/ansible.cfg) = ignore

CONNECTION:
==========

ssh:
___
pipelining(/usr/share/ansible/ansible.cfg) = True
ssh_args(/usr/share/ansible/ansible.cfg) = -C -o ServerAliveInterval=5 -o ServerAliveCountMax=2 -o ControlMaster=auto -o ControlPersist=120s -o PreferredAuthentications=publickey,password -o UserKnownHostsFile=/dev/null -o StrictHostKe
timeout(/usr/share/ansible/ansible.cfg) = 15

INVENTORY:
=========

consort:
_______
cache_connection(/usr/share/ansible/ansible.cfg) = /root/.ansible/cache
cache_plugin(/usr/share/ansible/ansible.cfg) = jsonfile
```

### OS / Environment

Centos 7 Docker container

### Steps to Reproduce

Action plugin intercepts
```yaml (paste below)
jira:
    issue: 'TEST-1'
    operation: comment
    comment: A comment added by Ansible
```

Action plugin doe *not* intercept
```
community.general.jira:
    issue: 'TEST-1'
    operation: comment
    comment: A comment added by Ansible
```

### Expected Results

A way to have action plugins intercept fqcn module calls when action plugins are stored in the top level action plugins directory.

### Actual Results

```console
`ansible.legacy.normal` is the action plugin handler called instead of the `jira` top level action plugin.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
This is not a bug, and is expected behavior.  When using the short name, it will see your action plugin, and then call the module which will use the module redirect list, and ultimately redirect to the collection.

There is no way to accomplish this using an FQCN.  You would need to add the `jira` action plugin to the collection itself, or alternatively you have a few options:

1. PREFERRED: Use `module_defaults` instead of using an action plugin
2. Create your own collection with the jira action plugin, and enforce that users call your collection for the action plugin which can then defer to the community.general module

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
