### ISSUE TITLE
The dnf module needs to be adapted for dnf5

### ISSUE THREAD

**Issue by gotmax23** [ansible/ansible#78898]
### Summary

YUM/DNF is being rewritten again in C++. The rewrite is dubbed [dnf5](https://github.com/rpm-software-management/dnf5). It has a lot of user and performance benefits, but the new Swig libdnf5 Python bindings are incompatible with the current python3-dnf that the `dnf`  module relies on.

dnf5 does not yet have a stable release, but there is a testing [Copr](https://copr.fedorainfracloud.org/coprs/rpmsoftwaremanagement/dnf5-unstable/). I wanted to create an issue to track this now, as there are plans to replace the current dnf with dnf5 in Fedora in the relatively near future. Currently, there are two Fedora Change Proposals regarding dnf5.

Fedoda 38 (current Rawhide; final release targeted for next spring): microdnf will be replaced with dnf5. This means that (lib)dnf5 and the current dnf will both be available [[link]](https://fedoraproject.org/wiki/Changes/MajorUpgradeOfMicrodnf). FESCO approved this Change earlier this year.

There is also a F39 Change Proposal about making dnf5 the default, but that's up in the air, so I won't speculate too much about it [[link]](https://fedoraproject.org/wiki/Changes/ReplaceDnfWithDnf5). This proposal has not been approved by FESCo, but to summarize: my understanding is that python3-dnf will still be available, but the history database won't be shared between that and dnf5. Either way, the dnf module needs to be ported if we want Fedora to remain a viable Ansible target. dnf5 will presumably trickle into RHEL at some point. Given the API differences, it might be best to just create a new dnf5 module.

### Issue Type

Feature Idea

### Component Name

dnf

### Additional Information

See above.

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by bcoca** [comment]
having developed modules against moving targets before, i would wait until this has at least been deployed before even starting development.

**Comment by sivel** [comment]
We've had some initial discussions about this. Our intention would be to have a `dnf5` module created, which we can abstract a little potentially in the `dnf` action plugin.

I think it's still up in the air who will ultimately be responsible for its development. I cannot necessarily state now that the core team will be the responsible party.  My preference would be to have someone who is more of an expert in dnf5 be the implementer.

**Comment by mkrizek** [comment]
As a note, @j-mracek and I have discussed the initial plan for creating a new module for `dnf5`.

**Comment by gotmax23** [comment]
We'll probably get an exception to update ansible-core 2.16 in Fedora 39. Fedora 39 will have Python 3.12 like Fedora 37 had Python 3.11. Unless the situation changes, we'll have to temporarily patch ansible-test 2.15 to run with Python 3.12, and then we'll ship the first pre-release of ansible-core 2.16.
