### ISSUE TITLE
make create user more awesome

### ISSUE THREAD

**Issue by biffhero** [ansible/ansible#789]
When running the create user command, we are seeing that there is a change every time the command is run.

According to the inimitiable sfromm, the reason this is happening is because we are running on CentOS 5.8, and so the spwd library from python isn't being used.  Therefore sfromm will have to make a special corner case for RHEL5 / CentOS5, where Python is 2.4, and not 2.5 or higher, to read and write /etc/shadow by hand.

**Comment by sfromm** [comment]
i have some code for this, but need to test it on a variety of platforms for pushing it up to github.

**Comment by biffhero** [comment]
I am glad to test on CentOS5.8 and some debian / ubuntu.

**Comment by sfromm** [comment]
@biffhero Please test the change in #804 and let me know if it resolves this issue.  I've tested on centos5, centos6, and debian, but would appreciate further testing.
