### ISSUE TITLE
Poor documentation of lookup plugins (especially with_file)

### ISSUE THREAD

**Issue by picomancer** [ansible/ansible#7890]
##### Issue Type:

Documentation Report
##### Ansible Version:

```
ansible 1.7 (devel 9631309433) last updated 2014/06/22 17:53:14 (GMT -400)
```
##### Environment:

Linux Mint 16 Petra (based on Ubuntu 13.10 Saucy)
##### Summary:

with_file is mentioned in an example in the authorized_key documentation, but the documentation has no more information on what with_file is or does.
##### Steps To Reproduce:

```
grep -R with_file .
```
##### Expected Results:

Filename where I can find detailed documentation on with_file.
##### Actual Results:

Little useful information.
##### Detailed discussion:

I see with_file in an example in the authorized_key documentation, but with_file doesn't seem to be documented anywhere in the official documentation.  Grepping for "with_file" doesn't show anything like an implementation.

If with_file has been removed (or deprecated), this fact should be noted somewhere in the documentation, and all other mentions of with_file should (eventually) be removed.

If with_file is not going to be removed (or deprecated), then it should be documented somewhere.

AFAICT the source files in lib/ansible/runner/lookup_plugins are accessed by appending "with_" to the filename, so the "with_file" command is implemented by lib/ansible/runner/lookup_plugins/file.py, the "with_items" command is implemented by lib/ansible/runner/lookup_plugins/items.py, etc.  I eventually figured out the logic which implements this is in lib/ansible/playbook/task.py, but the behavior doesn't seem to be documented either.

Issues #1855 and #3494 may be slightly related.  As of this writing, the with_file example is in the live docs at http://docs.ansible.com/authorized_key_module.html

**Comment by mpdehaan** [comment]
This is documented here, as Googling would point out.

http://docs.ansible.com/playbooks_loops.html

Patches to improve documentation crosslinking are always welcome.

We have said nothing about deprecation.

**Comment by picomancer** [comment]
- Go to http://docs.ansible.com/playbooks_loops.html
- Ctrl+F `with_file`
- Find three instances of `with_fileglob` but no instances of `with_file`.

I have to disagree.  `with_file` isn't documented there.

But I think I now understand what it does -- it's a loop where the `item` template variable assumes the contents of each listed file.  I'll add that information to the documentation and write a pull request.

**Comment by msabramo** [comment]
I think this should be reopened.

As @picomancer points out, http://docs.ansible.com/playbooks_loops.html documents `with_fileglob` but not `with_file`.

Furthermore, I just upgraded from ansible 1.6.6 to ansible 1.7.1 and now it's complaining about `with_file`.

```
$ ansible-playbook --version
ansible-playbook 1.7.1

$ ansible-playbook --syntax-check roles/vagrant/tasks/main.yml

playbook: roles/vagrant/tasks/main.yml

ERROR: with_file is not a legal parameter at this level in an Ansible Playbook
```

Note that searching the docs for `with_file` yields mentions of both `with_file` and `with_fileglob` but the latter one is described in detail and the former is not:

```
$ ag 'with_file' docsite
docsite/rst/developing_plugins.rst
31:Language constructs like "with_fileglob" and "with_items" are implemented via lookup plugins.  Just like other plugin types, you can write your own.

docsite/rst/glossary.rst
162:but there are also lookup plugins like "with_file" which loads data from a file, and even ones for querying environment variables,

docsite/rst/playbooks_lookups.rst
46:If the file exists previously, it will retrieve its contents, behaving just like with_file. Usage of variables like "{{ inventory_hostname }}" in the filepath can be used to set

docsite/rst/playbooks_loops.rst
97:``with_fileglob`` matches all files in a single directory, non-recursively, that match a pattern.  It can
110:          with_fileglob:
113:.. note:: When using a relative path with ``with_fileglob`` in a role, Ansible resolves the path relative to the `roles/<rolename>/files` directory.
```

Cc: @sontek, @aconrad, @sudarkoff

**Comment by pjz** [comment]
@msabramo I'm told you should just open a new issue
