### ISSUE TITLE
Docs: Replace yes/no in boolean examples with true/false in playbook guide

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#78921]
### Summary

Based on the [steering committee vote to use true/false for booleans,](https://github.com/ansible-community/community-topics/discussions/120) we are going through the guides to adapt to this change.

This issue requests these changes in the `docs/docsite/rst/playbooks_guide/` files.

Changes are: change `yes` to `true`  and `no` to `false`

must be lowercase. Please open one PR to handle these changes. It should impact 38 files. NOTE - ansibot does not like PRs over 50 files.

The following grep will help you find these occurrences from the `docs/docsite/rst/playbooks/` directory:
`grep -R '\: \(yes\|no\)$' --exclude-dir=locales`

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/playbook_guide/index.rst

### Ansible Version

```console
$ ansible --version
2.14
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by samccann** [comment]
Grep results in the following list:
playbook_guide/playbooks_blocks.rst:      ignore_errors: yes
playbook_guide/playbooks_blocks.rst:          changed_when: yes
playbook_guide/playbooks_checkmode.rst:      check_mode: no
playbook_guide/playbooks_checkmode.rst:      check_mode: yes
playbook_guide/playbooks_checkmode.rst:      diff: no
playbook_guide/playbooks_conditionals.rst:          persistent: yes
playbook_guide/playbooks_debugger.rst:      gather_facts: no
playbook_guide/playbooks_debugger.rst:      gather_facts: yes
playbook_guide/playbooks_error_handling.rst:      ignore_errors: yes
playbook_guide/playbooks_error_handling.rst:      ignore_unreachable: yes
playbook_guide/playbooks_error_handling.rst:      ignore_unreachable: yes
playbook_guide/playbooks_error_handling.rst:        ignore_unreachable: no
playbook_guide/playbooks_loops.rst:        append_privs: yes
playbook_guide/playbooks_loops.rst:        extended: yes
playbook_guide/playbooks_loops.rst:        extended: yes
playbook_guide/playbooks_loops.rst:        extended_allitems: no
playbook_guide/playbooks_privilege_escalation.rst:      become: yes
playbook_guide/playbooks_privilege_escalation.rst:      become: yes
playbook_guide/playbooks_privilege_escalation.rst:      become: yes
playbook_guide/playbooks_privilege_escalation.rst:     become: yes
playbook_guide/playbooks_privilege_escalation.rst:     become: yes
playbook_guide/playbooks_privilege_escalation.rst:   ansible_become: yes
playbook_guide/playbooks_privilege_escalation.rst:           authorize: yes
playbook_guide/playbooks_privilege_escalation.rst:      become: yes
playbook_guide/playbooks_privilege_escalation.rst:      remote_src: yes
playbook_guide/playbooks_privilege_escalation.rst:      ansible_become: yes
playbook_guide/playbooks_privilege_escalation.rst:    become: yes
playbook_guide/playbooks_privilege_escalation.rst:    become: yes
playbook_guide/playbooks_prompts.rst:          private: no
playbook_guide/playbooks_prompts.rst:       private: yes
playbook_guide/playbooks_prompts.rst:       confirm: yes
playbook_guide/playbooks_prompts.rst:       unsafe: yes
playbook_guide/playbooks_prompts.rst:       private: yes
playbook_guide/playbooks_tags.rst:       enabled: yes
playbook_guide/playbooks_tags.rst:         enabled: yes
playbook_guide/playbooks_tags.rst:         enabled: yes
playbook_guide/playbooks_vars_facts.rst:      gather_facts: no
playbook_guide/playbooks_vars_facts.rst:          recurse: yes

**Comment by aarjavpatni** [comment]
Hi there!
I'm interested in working on this. Can I be assigned it?

**Comment by aloner-pro** [comment]
Could you assign me this. This is my first time in open-source.

**Comment by aarjavpatni** [comment]
It's mine as well. And I'm working on it already!

**Comment by Praveenvira** [comment]
Can you please assign me this. I will do my best. For replace to boolean examples.

**Comment by samccann** [comment]
Hi folks - looks like @suven-p already opened a PR to fix this one. Please do check the issue queue at https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest as we are continuing to open more issues for Hacktoberfest this week!
