### ISSUE TITLE
Docs:os_guide: replace yes/no with true/false for booleans

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#78923]
### Summary

Based on the [steering committee vote to use true/false for booleans,](https://github.com/ansible-community/community-topics/discussions/120) we are going through the guides to adapt to this change.

This issue requests these changes in the `docs/docsite/rst/os_guide/` files.

Changes are: change `yes` to `true`  and `no` to `false`

must be lowercase. Please open one PR to handle thse changes. It should impact 15 files. NOTE - ansibot does not like PRs over 50 files.

The following grep will help you find these occurrences from the `docs/docsite/rst/os_guide/` directory:
`grep -R '\: \(yes\|no\)$' --exclude-dir=locales`

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/os_guide.index.rst

### Ansible Version

```console
$ ansible --version
none
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by samccann** [comment]
grep results in the following list:
os_guide/windows_dsc.rst:      Anonymous: no
os_guide/windows_dsc.rst:      Basic: yes
os_guide/windows_dsc.rst:      Digest: no
os_guide/windows_dsc.rst:      Windows: yes
os_guide/windows_dsc.rst:      no_log: yes
os_guide/windows_dsc.rst:        Windows: yes
os_guide/windows_dsc.rst:          Anonymous: no
os_guide/windows_dsc.rst:          Basic: yes
os_guide/windows_dsc.rst:          Digest: no
os_guide/windows_dsc.rst:          Windows: yes
os_guide/windows_setup.rst:      gather_facts: no
os_guide/windows_usage.rst:        update_password: no
os_guide/windows_usage.rst:        password_never_expires: yes
os_guide/windows_usage.rst:        reorganize: yes
os_guide/windows_usage.rst:        password_never_expires: no

**Comment by samccann** [comment]
@jborean93 Do you know if we can change the booleans in https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/os_guide/windows_dsc.rst to use `true/false` ? It seems the ones in the list above that start with a capital letter are not actually Ansible booleans but Windows...

**Comment by kalashjain23** [comment]
Hey! I would like to take up on this issue. Can you please assign this to me?

**Comment by jborean93** [comment]
@samccann you sure can as these are booleans sent from Ansible to the remote host. I'm not 100% sure you mean by the ones starting with capital letters. If you are talking about things like `Anonymous`, `Basic`, that's just the key name expected by the module for DSC.

**Comment by samccann** [comment]
@jborean93 cool thanks!

**Comment by samccann** [comment]
@kalashjain23 - we don't have the ability to assign outside the ansible org but consider it yours. Hacktoberfest doesn't officially start until Saturday so we won't see your PR til Monday. Put  Fixes #78923 in the description when you open the PR and it will link back to this. And thanks!

**Comment by kalashjain23** [comment]
> @kalashjain23 - we don't have the ability to assign outside the ansible org but consider it yours. Hacktoberfest doesn't officially start until Saturday so we won't see your PR til Monday. Put Fixes #78923 in the description when you open the PR and it will link back to this. And thanks!

OK! Awesome… I'll make a PR when Hacktoberfest starts!
Thank you so much!

**Comment by kalashjain23** [comment]
<a href="https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/os_guide/intro_bsd.rst#debug-the-discovery-of-python">Here</a>, there's one line as `ansible_become=yes` (twice in the whole file) which is not in the grep results shown above.
Should I change that too?

**Comment by Praveenvira** [comment]
Can you please assign me this. I will do my best. Replace yes/no with true/false for booleans.

**Comment by samccann** [comment]
@kalashjain23 yes please do change any other occurrences. Not sure why grep didn't find them :-)

**Comment by kalashjain23** [comment]
Please tell if there are some more changes to be made! :)
