### ISSUE TITLE
Docs: various files - replace boolean yes/no with true/false

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#78925]
### Summary

Based on the [steering committee vote to use true/false for booleans,](https://github.com/ansible-community/community-topics/discussions/120) we are going through the guides to adapt to this change.

This issue requests these changes to the files listed in a followon comment.

Changes are: change `yes` to `true`  and `no` to `false`

must be lowercase. Please open one PR to handle these changes. It should impact 6 files. NOTE - ansibot does not like PRs over 50 files.

The following grep was used to create the list.
`grep -R '\: \(yes\|no\)$' --exclude-dir=locales`

NOTE: there are multiple issues open to change these booleans so please limit your changes to the list below so we do not have clashing PRs.

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/dev_guide/developing_modules_general_windows.rstt

### Ansible Version

```console
$ ansible --version
2.14
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by prayatharth** [comment]
hi there I have fixed all the listed occurences
@samccann

**Comment by samccann** [comment]
@prayatharth thanks. Can you create the PR and in the description say - Fixes #78925  
That will link to this issue. We won't merge any PRs until Monday because hacktoberfest doesn't officially start until Saturday.

And thanks!

**Comment by prayatharth** [comment]
@samccann  okay I am creating a PR then.

**Comment by prayatharth** [comment]
I wanted to ask something @samccann  that whether my PR counts from the day I created it or when it gets merged in the repo.

Like which of it is regarding  hacktoberfest .

**Comment by samccann** [comment]
@prayatharth I don't have much experience myself with what participants have to do, but I looked at their website and see:
`Have 4 pull/merge requests accepted between October 1 and October 31 to complete Hacktoberfest`

So as long as it doesn't get merged before Saturday, you should be fine. And 90% of the merges are by me...and I won't be back til Monday so there's a very small risk of it merging before Hacktoberfest starts.

**Comment by prayatharth** [comment]
@samccann 
 Thank you for the assurance

**Comment by sujal-goswami** [comment]
hey samccann is this issue still open or not, is yes then I want to work on it for hacktoberfest.
