### ISSUE TITLE
Docs: scenario guides: Replace yes/no booleans with true/false

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#78922]
### Summary

Based on the [steering committee vote to use true/false for booleans,](https://github.com/ansible-community/community-topics/discussions/120) we are going through the guides to adapt to this change.

This issue requests these changes in the `docs/docsite/rst/scenario_guides/` files.

Changes are: change `yes` to `true`  and `no` to `false`

must be lowercase. Please open one PR to handle these changes. It should impact 16 files. NOTE - ansibot does not like PRs over 50 files.

The following grep will help you find these occurrences from the `docs/docsite/rst/scenario_guides/` directory:
`grep -R '\: \(yes\|no\)$' --exclude-dir=locales`

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/scenario_guides/index.rst

### Ansible Version

```console
$ ansible --version
2.14
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by samccann** [comment]
grep results in the following list:
guide_gce.rst:     gather_facts: no
guide_gce.rst:     gather_facts: no
guide_azure.rst:      gather_facts: no
guide_rax.rst:            wait: yes
guide_rax.rst:            exact_count: yes
guide_rax.rst:            wait: yes
guide_rax.rst:            wait: yes
guide_rax.rst:            exact_count: yes
guide_rax.rst:            wait: yes
guide_rax.rst:            wait: yes
guide_rax.rst:            exact_count: yes
guide_rax.rst:            wait: yes
guide_rax.rst:                return_content: yes
guide_scaleway.rst:      gather_facts: no
guide_scaleway.rst:      gather_facts: no
guide_aci.rst:      gather_facts: no

**Comment by J-F-Far** [comment]
I would like to take this one on.
