### ISSUE TITLE
ansible-playbook: error: the following arguments are required: playbook

### ISSUE THREAD

**Issue by thummim** [ansible/ansible#78939]
### Summary

When i try to set an inventory by using ansible-playbook -i comman, it does not work

### Issue Type

Bug Report

### Component Name

Ansible-playbook

### Ansible Version

```console
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/thummim/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
```

### Configuration

```console
not working neither
```

### OS / Environment

ubuntu 20.04

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

Set an inventory

### Actual Results

```console
ubuntu@ubuntu:/etc/ansible$ sudo vi inventory.yaml
ubuntu@ubuntu:/etc/ansible$ ansible-playbook -i inventory.yaml
usage: ansible-playbook [-h] [--version] [-v] [-k] [--private-key PRIVATE_KEY_FILE] [-u REMOTE_USER] [-c CONNECTION] [-T TIMEOUT] [--ssh-common-args SSH_COMMON_ARGS]
                        [--sftp-extra-args SFTP_EXTRA_ARGS] [--scp-extra-args SCP_EXTRA_ARGS] [--ssh-extra-args SSH_EXTRA_ARGS] [--force-handlers] [--flush-cache] [-b] [--become-method BECOME_METHOD]
                        [--become-user BECOME_USER] [-K] [-t TAGS] [--skip-tags SKIP_TAGS] [-C] [--syntax-check] [-D] [-i INVENTORY] [--list-hosts] [-l SUBSET] [-e EXTRA_VARS] [--vault-id VAULT_IDS]
                        [--ask-vault-pass | --vault-password-file VAULT_PASSWORD_FILES] [-f FORKS] [-M MODULE_PATH] [--list-tasks] [--list-tags] [--step] [--start-at-task START_AT_TASK]
                        playbook [playbook ...]
ansible-playbook: error: the following arguments are required: playbook
ubuntu@ubuntu:/etc/ansible$ ansible-playbook: error: the following arguments are required: playbook
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by thummim** [comment]
lib/ansible does not exists :(

**Comment by mkrizek** [comment]
> ansible-playbook: error: the following arguments are required: playbook

The message is clear, you need to pass the file containing the playbook to run. You only provided inventory file.

**Comment by mkrizek** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
