### ISSUE TITLE
health_check_period being set to 0 by default makes ASG instances being terminated immediately

### ISSUE THREAD

**Issue by fdv** [ansible/ansible#7898]
##### Issue Type:

Bug report
##### Ansible Version:

`ansible 1.7` and `ansible 1.6`
##### Environment:

N/A
##### Summary:

When creating an autoscaling group using the `ec2_asg` module, it is impossible to specify `health_check_period`, which is then set to 0.

According to Boto documentation, `health_check_period` refers to:

> Length of time in seconds after a new EC2 instance comes into service that Auto Scaling starts checking its health.

When set to 0, AWS health check will actually wait 0 seconds, which is way too fast for the instance to launch. 
##### Steps To Reproduce:

Just create an ASG and try to have the instance survive for more than 5 minutes.
##### Expected Results:

Instance should not spawn and be killed immmediately.
##### Actual Results:

Every launched instance within the autoscaling group is immediately killed after boot.

**Comment by jimi-c** [comment]
The above PR has been merged in, which should address this issue. Please let us know if you continue seeing any problems related to this. Thanks!
