### ISSUE TITLE
Docs: Replace Latin terms in network/user_guide platform files with English terms

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#78998]
### Summary

Our [style guide](https://docs.ansible.com/ansible/latest/dev_guide/style_guide/index.html#avoid-using-latin-phrases) notes that we should not use Latin terms (e.g, via, etc) in our documentation. This issue specifically asks to replace these with the noted English equivalents from that style guide table for all occurrences in the docs/docsite/rst/network/user_guide directory. 

Use `grep -R -e 'etc\.' -e 'i\.e ' -e 'e\.g\. ' -e 'via ' -e 'vs\(\.\)\? ' -e versus --exclude-dir=locales`  in the docs/docsite/rst/network/user_guide/ directory to find these.

List of all effected files are in a follow-on comment. NOTE: these are only the platform_* files included here to limit the scope of the PR that fixes these.

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/network/user_guide/index.rst

### Ansible Version

```console
$ ansible --version
none
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by samccann** [comment]
For the month of October, we will address hacktoberfest PRs on a first come-first mergeable basis as there is no way for us to assign issues to an individual contributor. Thanks for your interest in helping the Ansible documentation effort!

**Comment by samccann** [comment]
NOTE: These platform files include tables that are notoriously sensitive to spacing issues. As such, replace all occurrences of `via` with `by` to ensure the tables remain well-formed.

**Comment by samccann** [comment]
50 files that need to change:
grep -R -e 'etc\.' -e 'i\.e ' -e 'e\.g\. ' -e 'via ' -e 'vs\(\.\)\? ' -e versus platform* --exclude-dir=locales 
platform_ce.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_cnos.rst:    Indirect Access       via a bastion (jump host)
platform_cnos.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_dellos10.rst:    Indirect Access       via a bastion (jump host)
platform_dellos10.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_dellos6.rst:    Indirect Access       via a bastion (jump host)
platform_dellos6.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_dellos9.rst:    Indirect Access       via a bastion (jump host)
platform_dellos9.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_enos.rst:    Indirect Access       via a bastion (jump host)
platform_enos.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_eos.rst:    Indirect Access       via a bastion (jump host)                   via a web proxy
platform_eos.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_eric_eccli.rst:    Indirect Access       via a bastion (jump host)
platform_eric_eccli.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_exos.rst:    Indirect Access       via a bastion (jump host)                   via a web proxy
platform_exos.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_frr.rst:    Indirect Access       via a bastion (jump host)
platform_frr.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_icx.rst:    Indirect Access       via a bastion (jump host)
platform_icx.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_ios.rst:    Indirect Access       via a bastion (jump host)
platform_ios.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_iosxr.rst:    Indirect Access       via a bastion (jump host)                   via a bastion (jump host)
platform_iosxr.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_iosxr.rst:To enable NETCONF on a new switch via Ansible, use the ``cisco.iosxr.iosxr_netconf`` module through the CLI connection. Set up your platform-level variables just like in the CLI example above, then run a playbook task like this:
platform_ironware.rst:    Indirect Access       via a bastion (jump host)
platform_ironware.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_junos.rst:    Indirect Access       via a bastion (jump host)                   via a bastion (jump host)
platform_junos.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_junos.rst:To enable NETCONF on a new switch via Ansible, use the ``junipernetworks.junos.junos_netconf`` module through the CLI connection. Set up your platform-level variables just like in the CLI example above, then run a playbook task like this:
platform_netconf_enabled.rst:    Indirect Access       via a bastion (jump host)
platform_netconf_enabled.rst:To enable NETCONF on a new switch via Ansible, use the platform specific module via the CLI connection or set it manually.
platform_netvisor.rst:    Indirect Access       via a bastion (jump host)
platform_netvisor.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_nos.rst:    Indirect Access       via a bastion (jump host)
platform_nos.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_nxos.rst:    Indirect Access       via a bastion (jump host)                   via a web proxy
platform_nxos.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_nxos.rst:Before you can use NX-API to connect to a switch, you must enable NX-API. To enable NX-API on a new switch via Ansible, use the ``nxos_nxapi`` module via the CLI connection. Set up group_vars/nxos.yml just like in the CLI example above, then run a playbook task like this:
platform_routeros.rst:    Indirect Access       via a bastion (jump host)
platform_routeros.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_slxos.rst:    Indirect Access       via a bastion (jump host)
platform_slxos.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_voss.rst:    Indirect Access       via a bastion (jump host)
platform_voss.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_vyos.rst:    Indirect Access       via a bastion (jump host)
platform_vyos.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.
platform_weos4.rst:    Indirect Access       via a bastion (jump host)
platform_weos4.rst:- If you are accessing your host through a bastion/jump host, you cannot include your SSH password in the ``ProxyCommand`` directive. To prevent secrets from leaking out (for example in ``ps`` output), SSH does not support providing passwords via environment variables.

**Comment by ishan-siddiqui** [comment]
> NOTE: These platform files include tables that are notoriously sensitive to spacing issues. As such, a simple search/replace will NOT work. Most of the changes can still be search/replace as follows:
> 
> * `via a bastion (jump host)`  - replace with `by a bastion (jump host) `
> * `via a web proxy` - replace with `by a web proxy `
> 
> It's likely hard to tell here, but you want an extra space at the end of the replacement phrase so the table rows and columns do not get out of alignment. If they are, you will see the CI tests report these problems and you can fix each one with that extra space.
> 
> Any other terms not in a table can be a simple search/replace.

Hey! So should we do a space after the word or the entire sentence?
