### ISSUE TITLE
Docs: Replace latin terms with english in the playbook_guide directory

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#79006]
### Summary

Our [style guide](https://docs.ansible.com/ansible/latest/dev_guide/style_guide/index.html#avoid-using-latin-phrases) notes that we should not use Latin terms (e.g, via, etc) in our documentation. This issue specifically asks to replace these with the noted English equivalents from that style guide table for all occurrences in the docs/docsite/rst/playbook_guide/ directory .

Use `grep -R -e 'etc\.' -e 'i\.e ' -e 'e\.g\. ' -e 'via ' -e 'vs\(\.\)\? ' -e versus `  in the docs/docsite/rst/playbook_guide/ directory to find these.

List of all effected files are in a follow-on comment. 

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/playbook_guide/index.rst

### Ansible Version

```console
$ ansible --version
2.14
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by samccann** [comment]
For the month of October, we will address hacktoberfest PRs on a first come-first mergeable basis as there is no way for us to assign issues to an individual contributor. Thanks for your interest in helping the Ansible documentation effort!

**Comment by samccann** [comment]
List of impacted files:
grep -R -e 'etc\.' -e 'i\.e ' -e 'e\.g\. ' -e 'via ' -e 'vs\(\.\)\? ' -e versus 
playbooks_intro.rst:There's also a `clever playbook <https://github.com/ansible/ansible-examples/blob/master/language_features/ansible_pull.yml>`_ available to configure ``ansible-pull`` via a crontab from push mode.
playbooks_loops.rst:For role authors, writing roles that allow loops, instead of dictating the required ``loop_var`` value, you can gather the value via the following
playbooks_python_version.rst:methods return a list.  Jinja2 returns that to Ansible via a string
playbooks_reuse.rst:  - A role contains a set of related tasks, variables, defaults, handlers, and even modules or other plugins in a defined file-tree. Unlike variables files, task files, or playbooks, roles can be easily uploaded and shared via Ansible Galaxy. See :ref:`playbooks_reuse_roles` for details about creating and using roles.

**Comment by smeet07** [comment]
There is usage of these terms in different directories also, should I also replace those as well?

**Comment by samccann** [comment]
Hi @smeet07 ! No, please only change these. There are multiple issues open to change them all since the ansible CI doesn't like it if a PR has more than 50 files. So we opened issues per directory.
