### ISSUE TITLE
vars_files not importing existing file?

### ISSUE THREAD

**Issue by micafer** [ansible/ansible#7901]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible 1.5.4, 1.5.5, 1.6.0 and 1.6.1
##### Environment:

Ubuntu 12.04. 
##### Summary:

In the specified versions, a "vars_files" section defined like this example do not find the files to include. The same example used with versions older or equal than 1.5.3 and versions 1.6.2 and 1.6.3 it works correctly.

``` yml

---
- hosts: front
  sudo: true
  vars_files:
  - - utils/vars/{{ ansible_distribution }}.yml
    - utils/vars/os_defaults.yml

  tasks:
  - debug: msg="{{some_var}}"
```
##### Steps To Reproduce:

Use ansible-playbook command with this playbook:

``` yml

---
- hosts: front
  sudo: true
  vars_files:
  - - utils/vars/{{ ansible_distribution }}.yml
    - utils/vars/os_defaults.yml

  tasks:
  - debug: msg="{{some_var}}"
```

Create a file named Ubuntu.yml in the "utils/vars/" dir and define a variable named "some_var" with any value. Also create an "os_defaults.yml" file in the same dir and set the same variable "some_var" with other value.

You will obtain a result like that:

```
PLAY [front] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [158.42.105.15]
158.42.105.15: not importing file: /tmp/conf/utils/vars/{{ansible_distribution}}.yml

TASK: [debug msg="0"] ********************************************************* 
ok: [158.42.105.15] => {
    "msg": "0"
}

PLAY RECAP ******************************************************************** 
158.42.105.15              : ok=2    changed=0    unreachable=0    failed=0   
```
##### Expected Results:

```
PLAY [front] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [158.42.105.15]
158.42.105.15: importing /tmp/conf/utils/vars/Ubuntu.yml

TASK: [debug msg="False"] ***************************************************** 
ok: [158.42.105.15] => {
    "msg": "1"
}

PLAY RECAP ******************************************************************** 
158.42.105.15              : ok=2    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

```
PLAY [front] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [158.42.105.15]
158.42.105.15: not importing file: /tmp/conf/utils/vars/{{ansible_distribution}}.yml

TASK: [debug msg="0"] ********************************************************* 
ok: [158.42.105.15] => {
    "msg": "0"
}

PLAY RECAP ******************************************************************** 
158.42.105.15              : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by mpdehaan** [comment]
We have tests for vars_files and I'm sure this is operational and probably a pathing issue on your end, can you please ask for some debugging help on ansible-project ?

We will be needing to see a playbook repo in entirity rather than just the copy/paste portions to know where files sit relative to one another.

Thanks!

**Comment by micafer** [comment]
I have tested several times and it fails, and it is not a path issue because with different versions of ansible (as I said in the issue) it works.

I will show the steps to reproduce the error:

Use an Ubuntu 12.04 minimal installation.
Then perform this steps:

```
sudo apt-get update
sudo apt-get -y install python-pip sshpass
sudo pip install ansible==1.5.5
```

Then create the file Ubuntu.yml with this content:

```
some_var: 1
```

Then create the file os_defaults.yml:

```
some_var: 0
```

Also create the /etc/ansible/ansible.cfg file as:

```
[defaults]
host_key_checking=False
transport=paramiko
```

Then set the ip of the machine in invent.cfg.

Create the playbook file pr.yml as:

``` yml
---
- hosts: all
  vars_files:
  - - "{{ ansible_distribution }}.yml"
    - os_defaults.yml

  tasks:
  - debug: msg="{{some_var}}"
```

Finally call ansible-playbook command:

```
#ansible-playbook -k pr.yml -i invent.cfg

SSH password: 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [158.42.105.25]
158.42.105.25: not importing file: /home/ubuntu/{{ansible_distribution}}.yml

TASK: [debug msg="0"] ********************************************************* 
ok: [158.42.105.25] => {
    "msg": "0"
}

PLAY RECAP ******************************************************************** 
158.42.105.25              : ok=2    changed=0    unreachable=0    failed=0   
```

And it fails.

Now install one of the versions that it works, for example 1.5.3.

```
sudo pip install ansible==1.5.3
```

And call again the ansible-playbook command:

```
#ansible-playbook -k pr.yml -i invent.cfg

SSH password: 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [158.42.105.25]
158.42.105.25: importing /home/ubuntu/Ubuntu.yml

TASK: [debug msg="0"] ********************************************************* 
ok: [158.42.105.25] => {
    "msg": "1"
}

PLAY RECAP ******************************************************************** 
158.42.105.25              : ok=2    changed=0    unreachable=0    failed=0   
```

It works.

**Comment by mpdehaan** [comment]
Reopening this so we can make sure we have a test for conditional vars_files with a fact inside of it, I thought we did.   Will find out.

**Comment by jimi-c** [comment]
Looking into this, it appears that you have an extra dash leading the first vars_files entry. On 1.6.1, this does cause the vars files inclusion to fail, however on more recent versions this works just fine. Removing the extra dash causes the above playbooks to work fine even on 1.6.1 and earlier too.

We do have a vars_files test in the variable precedence integration test, so I'm going to go ahead and close this out. If you have any further questions regarding this, please let us know. Thanks!
