### ISSUE TITLE
vsphere_guest: values are being evaluated as strings, not int

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#7903]
##### Issue Type:

Bug Report 
##### Ansible Version:

ansible 1.7 (devel 65a8ffef6e) last updated 2014/06/23 08:42:27 (GMT -400)
##### Environment:

OSX 10.9 / RHEL 6.5
##### Summary:

when specifying variables for memory, num_cpus in vsphere_guest, they are being evaluated as strings, and not integers
##### Steps To Reproduce:

specify memory_mb, num_cpus in vsphere_guest:
    vm_hardware:
      memory_mb: "{{ memory_mb }}"
      num_cpus: "{{ num_cpus }}

try reducing the amount of memory on a VM, the if statemets to see if the playbook value is less than the vm value don't evaluate to true, thus the configuration doesn't get changed
##### Expected Results:

the configuration would get changed 
##### Actual Results:

the module fails

**Comment by jimi-c** [comment]
The patch you have above looks good. Please send us that as a PR and we'll get it merged in.

**Comment by jimi-c** [comment]
Whoops, didn't see you had already. I've merged that in, so this issue should be resolved. Thanks!
