### ISSUE TITLE
Docs: Add code-block wrappers to code examples in implicit_localhost.rst

### ISSUE THREAD

**Issue by ariordan-redhat** [ansible/ansible#79031]
### Summary

*Problem**:
Throughout the Ansible docs, there are instances where example code is preceded with a lead-in sentence ending in `::`.
Translation programs then attempt to translate this code, which we don't want.

**Solution:**
Enclose code  in a `.. code-block:: <lexer>` element, so that translation processes know to skip this content.
For a list of allowed values for _`<lexer>`_ , refer to [Syntax highlighting - Pygments](https://docs.ansible.com/ansible/latest/dev_guide/style_guide/index.html#syntax-highlighting-pygments).

**Scope:**
In the `implicit_localhost.rst ` file in the `docs/docsite/rst/inventory/` directory, there are 2 instances of lead-in sentences ending with `::`. Use the following `grep` command to identify the files and line numbers:

```
$ grep -rn --include "*.rst" "^[[:blank:]]*[^[:blank:]\.\.].*::$" .
```
$ grep -rn --include "*.rst" "^[[:blank:]]*[^[:blank:]\.\.].*::$" . | grep developing_collections_distributing.rst
```

**Example:**

Before:
```
Before running ``ansible-playbook``, run the following command to enable logging::

    export ANSIBLE_LOG_PATH=~/ansible.log

```

After:
```
Before running ``ansible-playbook``, run the following command to enable logging:

.. code-block:: shell

    export ANSIBLE_LOG_PATH=~/ansible.log

```

This problem has been addressed in some other guides; view these merged PRs to help get you started:
- Network Guide: [#75850](https://github.com/ansible/ansible/pull/75850/files) 
- Developer Guide: [#75849](https://github.com/ansible/ansible/pull/75849/files) 


### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/inventory/implicit_localhost.rst

### Ansible Version

```console
n/a
```

### Configuration

```console
n/a
```

### OS / Environment

n/a

### Additional Information

When example code is enclosed within a code-block element, translation programs do not attempt to translate the code.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by 12-malak** [comment]
@ariordan-redhat Hi, I would like to work on this. Please assign me.

**Comment by ariordan-redhat** [comment]
Thanks, @12-malak

**Comment by arneja-arnav** [comment]
Hey @ariordan-redhat may i work on this as well?

**Comment by 12-malak** [comment]
@ariordan-redhat  New PR pushed #79084

**Comment by 12-malak** [comment]
@ariordan-redhat New PR pushed with requested changes #79086
