### ISSUE TITLE
ec2 occasionally fails with traceback and InvalidInstanceID.NotFound

### ISSUE THREAD

**Issue by mpeters** [ansible/ansible#7906]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel 52c7d50f1e) last updated 2014/06/23 15:30:30 (GMT -400)
##### Environment:

Ansible is running on Fedora 12 targetting the AWS API.
##### Summary:

I'm using the ec2 module a script that runs it multiple times. Sometimes in loops and sometimes by itself. It occasionally fails with a traceback with an XML error code of "InvalidInstanceID.NotFound".
##### Steps To Reproduce:

It happens randomly and I don't see a pattern. It can happen when a single ec2 task is run or in a loop where most succeed but where one or two will fail.
##### Expected Results:

Each run should consistently succeed or fail.
##### Actual Results:

It fails randomly with a traceback like this:

```
invalid output was: Traceback (most recent call last):
  File "/home/mpeters/.ansible/tmp/ansible-tmp-1403554377.3-196775236290782/ec2", line 2666, in <module>
    main()
  File "/home/mpeters/.ansible/tmp/ansible-tmp-1403554377.3-196775236290782/ec2", line 1167, in main
    (tagged_instances, instance_dict_array, new_instance_ids, changed) = enforce_count(module, ec2)
  File "/home/mpeters/.ansible/tmp/ansible-tmp-1403554377.3-196775236290782/ec2", line 672, in enforce_count
    = create_instances(module, ec2, override_count=to_create)
  File "/home/mpeters/.ansible/tmp/ansible-tmp-1403554377.3-196775236290782/ec2", line 924, in create_instances
    res_list = ec2.get_all_instances(instids)
  File "/usr/lib/python2.7/site-packages/boto/ec2/connection.py", line 575, in get_all_instances
    max_results=max_results)
  File "/usr/lib/python2.7/site-packages/boto/ec2/connection.py", line 656, in get_all_reservations
    [('item', Reservation)], verb='POST')
  File "/usr/lib/python2.7/site-packages/boto/connection.py", line 1157, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidInstanceID.NotFound</Code><Message>The instance ID 'i-c643d794' does not exist</Message></Error></Errors><RequestID>1a08b741-19d1-4a83-a28e-0855745fe1d7</RequestID></Response>
```

Note that in none of the tasks am I actually passing an instance ID, so it's definitely getting that from the AWS API after it creates the instance, but then can't find it again.

**Comment by mpeters** [comment]
I think the problem is that my playbook did not specify `wait` because it didn't actually need the machines to be up (at least not logically). But I was specifying `instance_tags` which are separate API calls that require that the machine be found. So maybe `instance_tags` should have an implicit `wait` ?

**Comment by mpeters** [comment]
Actually, I take that back. I still think `instance_tags` should have an implicit `wait`, but my tasks actually do use `wait` themselves, so that won't solve my problem.

**Comment by mpeters** [comment]
This can be fixed with pull request #7907

**Comment by jimi-c** [comment]
Closing, as the above pull request has been merged in. Thanks!

**Comment by bkeroackdsc** [comment]
@jimi-c Still getting this error sporadically on 1.8.2.
