### ISSUE TITLE
ec2_asg fails when setting tags on existing autoscale group

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#7910]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel bbaf803227) last updated 2014/06/23 17:14:16 (GMT -400)
##### Environment:

OSX Mavericks 
##### Summary:

ec2_asg fails when tags are defined if the auto scale is already created.
##### Steps To Reproduce:

Create autoscae group, define tags:

```
- name: create autoscale groups
  local_action:
    module: ec2_asg
    name: myapp
    load_balancers: myapplb
    availability_zones: us-east-1c
    launch_config_name: myapplc
    min_size: 1
    max_size: 2
    desired_capacity: 2
    region: us-east-1
    tags:
    - role: myapp
  tags: autoscale_group
```
##### Expected Results:

Nothing should happen since the tags were already set on creation of the AutoScale Group.
##### Actual Results:

```
TASK: [myapp_infra | create autoscale groups] *********************************
<127.0.0.1> REMOTE_MODULE ec2_asg launch_config_name=myapp load_balancers=myapp max_size=4 desired_capacity=2 min_size=2 region=us-east-1 name=myapp availability_zones=us-east-1c,us-east-1d
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/jmartin/.ansible/tmp/ansible-tmp-1403571985.84-5800189009382/ec2_asg", line 1803, in <module>
    main()
  File "/Users/jmartin/.ansible/tmp/ansible-tmp-1403571985.84-5800189009382/ec2_asg", line 1799, in main
    create_autoscaling_group(connection, module)
  File "/Users/jmartin/.ansible/tmp/ansible-tmp-1403571985.84-5800189009382/ec2_asg", line 1703, in create_autoscaling_group
    if ( not tag['key'] in existing_tag_map or
KeyError: 'key'


FATAL: all hosts have already failed -- aborting
```

**Comment by jimi-c** [comment]
This patch may resolve the issue:

<pre>
diff --git a/library/cloud/ec2_asg b/library/cloud/ec2_asg
index 71c3535..0a5b726 100755
--- a/library/cloud/ec2_asg
+++ b/library/cloud/ec2_asg
@@ -209,6 +209,8 @@ def create_autoscaling_group(connection, module):
             existing_tags = as_group.tags
             existing_tag_map = dict((tag.key, tag) for tag in existing_tags)
             for tag in set_tags:
+                if 'key' not in tag:
+                    continue
                 if ( not tag['key'] in existing_tag_map or
                      existing_tag_map[tag['key']].value != tag['value'] or
                      ('propagate_at_launch' in tag and
</pre>

**Comment by jsmartin** [comment]
Works for me, thanks!

**Comment by jimi-c** [comment]
Great, merged that in.
