### ISSUE TITLE
Unable to install collection with type: git

### ISSUE THREAD

**Issue by kennedyjosh** [ansible/ansible#79168]
### Summary

I'm trying to install some collections using `ansible-galaxy install -r requirements.yml` but am unable to install a specific version from a git repository.

### Issue Type

Bug Report

### Component Name

galaxy

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.5]
  config file = /Users/josh/Code/server/ansible.cfg
  configured module search path = ['/Users/josh/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/josh/Code/server/hapy/venv/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/josh/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/josh/Code/server/hapy/venv/bin/ansible
  python version = 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
DEFAULT_HOST_LIST(/Users/josh/Code/server/ansible.cfg) = ['/Users/josh/Code/server/ansible/inventory_aws_ec2.yml']
DISPLAY_SKIPPED_HOSTS(/Users/josh/Code/server/ansible.cfg) = False
HOST_KEY_CHECKING(/Users/josh/Code/server/ansible.cfg) = False
INTERPRETER_PYTHON(/Users/josh/Code/server/ansible.cfg) = python

CALLBACK:
========

default:
_______
display_skipped_hosts(/Users/josh/Code/server/ansible.cfg) = False
pretty_results(/Users/josh/Code/server/ansible.cfg) = True

minimal:
_______
pretty_results(/Users/josh/Code/server/ansible.cfg) = True

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/Users/josh/Code/server/ansible.cfg) = False
ssh_args(/Users/josh/Code/server/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ForwardAgent=yes

ssh:
___
host_key_checking(/Users/josh/Code/server/ansible.cfg) = False
ssh_args(/Users/josh/Code/server/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ForwardAgent=yes
```

### OS / Environment

macOS 12.5

### Steps to Reproduce

requirements.yml
```yaml (paste below)
collections:
  - name: https://github.com/ansible-collections/amazon.aws.git
    type: git
    version: 395d4fda1ec549020d070d4465835166094e4777
  - name: community.aws
    version: 3.5.0

```

### Expected Results

I expect the collection to be installed at the specified git commit tag with no issues. 

### Actual Results

```console
% ansible-galaxy install -r ansible/requirements.yml 
Starting galaxy collection install process
Process install dependency map
Cloning into '/Users/josh/.ansible/tmp/ansible-local-44490z57uazrk/tmpztxrx5cz/amazon.aws48wn3_f9'...
remote: Enumerating objects: 18877, done.
remote: Counting objects: 100% (2652/2652), done.
remote: Compressing objects: 100% (799/799), done.
remote: Total 18877 (delta 2008), reused 2345 (delta 1810), pack-reused 16225
Receiving objects: 100% (18877/18877), 15.95 MiB | 4.49 MiB/s, done.
Resolving deltas: 100% (14006/14006), done.
Note: switching to '395d4fda1ec549020d070d4465835166094e4777'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 395d4fda ec2_instance: fix to handle create instance in specified AZ (#1150)
ERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:
* amazon.aws:>=3.4.0 (dependency of community.aws:3.5.0)
* amazon.aws:6.0.0-dev0 (dependency of "virtual collection Git repo")
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by kennedyjosh** [comment]
This is related to #79109 but it doesn't look like the proposed solution in #79112 fixes the issue addressed here.

From what I can understand, it seems like there is currently no way to install a collection from git via ansible-galaxy.

**Comment by kennedyjosh** [comment]
@s-hertel I noticed you marked this P3. I suppose that's fair since this isn't an issue that should block release but I'm concerned this issue may not get addressed as there are currently 300+ issues marked P3 and some of the oldest ones date back to 2015. Is there anything short of fixing the bug myself that I can do to get this addressed quicker (or ever)? One of my playbooks is blocked on this issue – I'm currently having to wait for the next release of `amazon.aws` which could take a while.

**Comment by sivel** [comment]
fwiw, we do not have any priority higher than P3 that doesn't block a release.  As such, P3 is the highest priority we have for any non-critical bugs.  P1 and P2 will block a release, and this doesn't qualify for that.

Additionally, even though there is a draft PR, this is rather complex and not easily addressed.  Even should we get to a fix, the earliest you would see it would be December 5, although I'm not committing to any resolution by that time.  At a minimum, I believe you can work around this by simply supplying the `--pre` flag during install.

**Comment by kennedyjosh** [comment]
I agree that P3 is the correct priority for this. Perhaps there is some argument to be made to differentiate among the issues currently in P3 (making issues stale, or adding another level P4) but I haven't been in the Ansible community long enough to formally propose such a system.  

Unfortunately adding the `--pre` tag results in the same error (I tried `ansible-galaxy collection install -r requirements.yml --pre`). 

I also didn't realize the next possible release for this would be as far out as Dec 5 – thanks for the info. I'll have to figure out some semi-permanent way to deal with this then..

**Comment by s-hertel** [comment]
@kennedyjosh It shouldn't fail with the exact same error, I would expect a different stack trace at minimum. The simple example you provided works for me with `--pre` (tested on 2.13.5).

```
$ ansible-galaxy collection install -r test_reqs.yml -p collections/ --pre
Starting galaxy collection install process
Process install dependency map
Cloning into '/home/liveuser/.ansible/tmp/ansible-local-170675zdsu_dym/tmpgczofv5k/amazon.aws1x0p8vvo'...
...
Starting collection install process
Downloading https://galaxy.ansible.com/download/community-aws-3.5.0.tar.gz to /home/liveuser/.ansible/tmp/ansible-local-170675zdsu_dym/tmpgczofv5k/community-aws-3.5.0-66v_o519
Installing 'community.aws:3.5.0' to '/home/liveuser/ansible/collections/ansible_collections/community/aws'
community.aws:3.5.0 was installed successfully
Installing 'amazon.aws:6.0.0-dev0' to '/home/liveuser/ansible/collections/ansible_collections/amazon/aws'
Created collection for amazon.aws:6.0.0-dev0 at /home/liveuser/ansible/collections/ansible_collections/amazon/aws
amazon.aws:6.0.0-dev0 was installed successfully
```

Installing from a git repo is a shortcut that mimics building the collection, so you could add several tasks to do it the proper way:
* clone the collection
* checkout the right commit
* build the collection
* cleanup clone

And then install the tarfile. This will still let you use dependency resolution to make sure everything is compatible with each other.

You could also disable dependency resolution with `--no-deps` to work around the issue, but then you'd need to manage dependencies.

More labels won't impact the fix for this. The only way to speed up a patch would be to open the PR. There are not many P3 issues for  `ansible-galaxy collection` anyway, and I tend to go through the queue taking into account the topic, not just age.

**Comment by kennedyjosh** [comment]
Thanks – I tried this with the `-p` flag and it worked, so I tried `rm -rf`ing my collections dir and running the command again without `-p` flag and that worked! I'm sort of ashamed I didn't think of that earlier. Though you're right, it would have been easy to create a playbook to install the package as well.

**Comment by webknjaz** [comment]
@kennedyjosh this should be fixed with https://github.com/ansible/ansible/pull/81606.
