### ISSUE TITLE
state=restarted not working as expected

### ISSUE THREAD

**Issue by valentinogagliardi** [ansible/ansible#7918]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.3
##### Environment:

Ansible running on CentOS 6.5 x86_64 to target an Ubuntu Trusty x86_64.
##### Summary:

Given a template task which trigger a `restart proftpd` seems that ProFTPD is killed but not restarted subsequently.
##### Steps To Reproduce:

```
- name: Configure Custom Directives for ProFTPD
  template: src=custom.j2
            dest={{ proftpd_include_conf }}/custom.conf
            owner=root
            group=root
            owner=0644
  notify:
   - restart proftpd
```
##### Expected Results:

The handler must restart the service.
##### Actual results:

ProFTPD is killed but not restarted

![proftpd_bug_handler](https://cloud.githubusercontent.com/assets/6078736/3377201/152dc21e-fbdd-11e3-9498-70b07d911297.png)

**Comment by mpdehaan** [comment]
Sounds like this is an issue with the init script here.

**Comment by valentinogagliardi** [comment]
**Update**: I've found that ProFTPD is restarted correctly if the tasks run two times. The first time the template is applied, ProFTPD is not restarted, but if I introduce a line in the template to trigger the handler on a second run ProFTPD is restarted. In every case `service proftpd restart` works fine on the command line inside the machine.

Thanks for the follow up. Not sure what's going on here but I've seen the same issue with Ansible 1.6.5 and PHP5-FPM service. I will update this issue as soon I've more clues.

**Comment by valentinogagliardi** [comment]
I can confirm that this is a bug in ProFTPD. https://bugs.launchpad.net/ubuntu/+source/proftpd-dfsg/+bug/1293416 

My apologies for this dumb bug report.
