### ISSUE TITLE
module homebrew: msg: unsupported parameter for module: upgrade_all

### ISSUE THREAD

**Issue by utinajero** [ansible/ansible#7924]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.3
##### Environment:

OSX 10.9.3
##### Summary:

I am trying to upgrade all installed brew apps. I looked at the module and tried replacing upgrade_all=yes with upgrade=yes and ran into the same issue. Bug with the module I think. 
##### Steps To Reproduce:

This is the playbook I ran. 
- homebrew: update_homebrew=yes upgrade=yes
##### Expected Results:

I expected for homebrew apps to be upgraded and marked OK. 
##### Actual Results:

failed with: msg: unsupported parameter for module: upgrade

output:
utinajero:osx admin$ ansible-playbook -i inventory brew_playbook.yml

PLAY [osx] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [installing ansible via homebrew] ***************************************
failed: [localhost] => {"failed": true}
msg: unsupported parameter for module: upgrade

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/admin/brew_playbook.retry

localhost                  : ok=1    changed=0    unreachable=0    failed=1

**Comment by jkordish** [comment]
This one has been recently bothering me as well ++

**Comment by danieljaouen** [comment]
This has already been merged into `devel` (though the option has changed from `upgrade` to `upgrade_all`).  If you want to use this feature, you can always run Ansible from a git checkout (as described here: https://github.com/ansible/ansible/tree/devel/hacking )

**Comment by utinajero** [comment]
This has been fixed in Ansible 1.7 :D
