### ISSUE TITLE
Docs request: ssh_args in Ansible Configuration Settings

### ISSUE THREAD

**Issue by jamesbraza** [ansible/ansible#79264]
### Summary

In the FAQ there's a section talking about `ssh_args`: https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-get-ansible-to-notice-a-dead-target-in-a-timely-manner

However, when you go to the config reference: https://docs.ansible.com/ansible/latest/reference_appendices/config.html#ansible-configuration-settings

There is no mention of `ssh_args`.  Can we add `ssh_args` to the Ansible Configuration Settings page?

It seems in 2.4 it was documented, not sure why it went away: https://docs.ansible.com/ansible/2.4/intro_configuration.html#ssh-args

### Issue Type

Documentation Report

### Component Name

unsure

### Ansible Version

```console
$ ansible --version

"latest" in docs
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

n/a
```

### OS / Environment

n/a

### Additional Information

n/a

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
Since that configuration is plugin specific, it is documented with the plugin that consumes it, such as:

https://docs.ansible.com/ansible-core/2.13/collections/ansible/builtin/ssh_connection.html#parameter-ssh_args

**Comment by jamesbraza** [comment]
Ah I see, and the good news is the plugin is built-in! 😄 

I would request then that here: https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-get-ansible-to-notice-a-dead-target-in-a-timely-manner

We name the plugin that houses `ssh_args`, so things are clear that `ssh_args` comes from a plugin.  What do you think?

> You can add `-o ServerAliveInterval=NumberOfSeconds` in `ssh_args` from the `ssh connection` plugin's section of `ansible.cfg`.

**Comment by samccann** [comment]
Documentation fix:

Change https://github.com/ansible/ansible/blame/devel/docs/docsite/rst/reference_appendices/faq.rst#L141 to include the suggestion from https://github.com/ansible/ansible/issues/79264#issuecomment-1297707005
