### ISSUE TITLE
ansible-doc should show defaults

### ISSUE THREAD

**Issue by jiphex** [ansible/ansible#7938]
##### Issue Type:

Feature Idea
##### Ansible Version:

All with ansible-doc
##### Environment:

n/a
##### Summary:

The ansible-doc command doesn't include the default option when displaying the list of choices, meaning that this has to be looked up elsewhere.
##### Steps To Reproduce:
- Run (for example): `ansible-doc user`
##### Expected Results:

The ansible-doc command should show the default option in the list of choices for each module argument.
##### Actual Results:

The ansible-doc command shows only the list of choices, and not the default option.

**Comment by resmo** [comment]
could not reproduce anymore. closing
