### ISSUE TITLE
Ansible: cannot connect to the LXD server (due to python version)

### ISSUE THREAD

**Issue by omani** [ansible/ansible#79473]
### Summary

the lxd inventory plugin (and also molecule with lxd but that is another topic) does not work with python > 3.9.

python 3.10 breaks the LXD module due to SSL verification errors.

### Issue Type

Bug Report

### Component Name

lxd inventory plugin

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.11]
  config file = None
  configured module search path = ['/home/sun/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sun/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/sun/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/sun/.local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
empty response
```

### OS / Environment

Ubuntu 20.04.5 LTS

### Steps to Reproduce

start a new LXD container with alpine 3.16.
```
lxc launch images:alpine/3.16 a1
```
install python3 (will install python 3.10):
```
lxc shell a1
apk update
apk add python3
```

run a simple lxd inventory plugin or molecule, or anything that uses lxd connection plugin and it will throw an error that it cannot connect to the remote LXD server.

but now do the above steps with **alpine 3.15** (which only has **python 3.9.15**) and everything will work.

### Expected Results

a connection to a remote LXD host via https URL.

### Actual Results

```console
LXDRaiseException "cannot connect to LXD server".
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by omani** [comment]
been a long time I debugged this. but iirc it had something to do with the change of the ssl context in python 3.10. and you had to use `ssl._create_default_https_context = ssl._create_unverified_context` to make it work.

cant remember anymore.
anyway, Im using alpine/3.15 for my ansible environments since then and have no problem with this bug anymore.

but since I didnt see anyone mention this bug that it is actually due to python 3.10, I thought I should mention it for future people coming from google etc.

**Comment by mkrizek** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general.

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.libera.chat
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
