### ISSUE TITLE
Deprecation warnings in docs/docsite/requirements.txt

### ISSUE THREAD

**Issue by oraNod** [ansible/ansible#79513]
### Summary

Got deprecation notes while installing doc requirements:

  DEPRECATION: straight.plugin is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

  DEPRECATION: sh is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

  DEPRECATION: sphinx-intl is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

### Issue Type

Documentation Report

### Component Name

docs/docsite/requirements.txt

### Ansible Version

```console
ansible [core 2.14.0]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Fedora 36

### Additional Information

N/A

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by samccann** [comment]
Possibly related to https://github.com/orgs/ansible-community/projects/4/views/4.

I'll test some package updates locally and see if this 'solves' the above problem or not.

**Comment by mattclay** [comment]
@oraNod What command(s) are you running, and in what environment, to see the deprecation warnings?

**Comment by oraNod** [comment]
@mattclay Hi, I got the deprecation statements when running `pip install -r docs/docsite/requirements.txt` before doing `make coredocs` in a virtual environment.

As it happens I can't seem to reproduce the deprecations now. I'll have another look but hopefully am not just making extra noise. Thanks in advance for help/guidance.

**Comment by mattclay** [comment]
@oraNod That warning from `pip` requires use of pip 22.3 or later (although it will become an error with pip 23.1). It only occurs if `wheel` is not installed in your environment already. However, adding `wheel` to the requirements file doesn't resolve the issue. It must already be installed.

**Comment by oraNod** [comment]
Thanks again for the help @mattclay 

As we talked about in chat, this a general Python issue that anyone will encounter if they're using outdated packages like we are. Unfortunately there's nothing we can do in the requirements file itself.

I'll close the PR that I opened against this for now and will open a new PR to document this somewhere for users.

**Comment by felixfontein** [comment]
straight.plugin is gone (#80084). sh might also be gone eventually, see https://github.com/ansible-community/antsibull-core/issues/34.
