### ISSUE TITLE
Should a module's documentation link to the module's source code?

### ISSUE THREAD

**Issue by nickjj** [ansible/ansible#7961]
##### Issue Type:

Documentation enhancement
##### Ansible Version:

N/A
##### Environment:

N/A
##### Summary:

I think it would be a great enhancement if each module had a link directly to the source code.

For example:
http://docs.ansible.com/service_module.html

It could have a "Source code" link or button somewhere that points to:
https://github.com/ansible/ansible/blob/devel/library/system/service

Use case:
I often find myself wanting to see the implementation details of a module to learn more about it and to also casually teach myself python. It would be a pretty big time saver if I could just instantly view the source of a module.

Implementation:
Not sure exactly but they seem to be categorized in both the source code and generated docs. Maybe you can use the file path to automatically build the links?
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
Sometimes the module source spans between action plugins and module sources, so it's not always possible, but regardless I do not neccessarily want users to feel they _need_ to grok the source code to use the tool.   There are also functions available in module_utils that would not directly be linked, so people would need to understand other things in the tree.

While I understand the idea and think it clever, I think it perhaps sets the wrong message about being a developer focused versus user focused tool.

If you hop into the "library/" directory of the checkout you'll see most everything you are after.
