### ISSUE TITLE
'assemble' module

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#80]
usage:

```
- copy ...
- template ...
- assemble src=/path/to/directory dest=/path/to/file.conf
```

Assembles a file out of a list of conf.d style files for where the system does not support a conf.d, src files are sorted alphabetically.

Should include Runner magic so "file" module is automatically applied after running assemble so we can set mode/ownership/etc in one step.

**Comment by sfromm** [comment]
I'll take this.

**Comment by mpdehaan** [comment]
implemented, so I can close this one, thanks!
