### ISSUE TITLE
issue with selinux in setup module.

### ISSUE THREAD

**Issue by goozbach** [ansible/ansible#800]
when SELINUX is disabled in the config file /etc/sysconfig/selinux, _AND_ the selinux state is still passive (before the reboot), the setup module dies.

GATHERING FACTS ********************\* 
fatal: [kvm1.schmoozecom.net] => failed to parse: Traceback (most recent call last):

  File "/var/tmp/ansible-1344382729.48-131665223189175/setup", line 850, in <module>

```
main()
```

  File "/var/tmp/ansible-1344382729.48-131665223189175/setup", line 655, in main

```
data = run_setup(module)
```

  File "/var/tmp/ansible-1344382729.48-131665223189175/setup", line 603, in run_setup

```
facts = ansible_facts()
```

  File "/var/tmp/ansible-1344382729.48-131665223189175/setup", line 592, in ansible_facts

```
facts.update(Facts().populate())
```

  File "/var/tmp/ansible-1344382729.48-131665223189175/setup", line 62, in **init**

```
self.get_selinux_facts()
```

  File "/var/tmp/ansible-1344382729.48-131665223189175/setup", line 128, in get_selinux_facts

```
(rc, configmode) = selinux.selinux_getenforcemode()
```

OSError: [Errno 0] Error

It looks like an issue with the selinux python module but I couldn't track it down past the _selinux.so python import.

**Comment by mpdehaan** [comment]
A try/except OSError around this is probably reasonable.   You could set the selinux state to unknown or something.

**Comment by sfromm** [comment]
I submitted #802, which wraps all the selinux calls with try/except.  

@goozbach, I was not able to replicate the above error.  This is on centos-6.3, correct?  And the host is running in permissive mode, but configured in /etc/selinux/config for disabled?  What version of libselinux-python?

And, finally, please let me know if the fix resolves the above error.  :-)  Thanks.

**Comment by mpdehaan** [comment]
Thanks -- Can continue to use this for discussion, let me know if I need to reopen.

**Comment by goozbach** [comment]
The try/except fixed my issue.

I did discover that my config file had changed to an improper format so this problem was one I introduced.

The "bug" was better error handling, we should keep the try/except.

**Comment by sfromm** [comment]
On Wed, Aug 8, 2012 at 12:24 PM, Derek Carter notifications@github.comwrote:

> The try/except fixed my issue.
> 
> I did discover that my config file had changed to an improper format so
> this problem was one I introduced.
> 
> The "bug" was better error handling, we should keep the try/except.
> 
> Okay, with the above information I'm able to replicate the bug.  The fix in
> #802 and #808 seem to resolve this.

Thanks!
