### ISSUE TITLE
Let Ansible work with Firejail

### ISSUE THREAD

**Issue by marek22k** [ansible/ansible#80057]
### Summary

Hello,

Ansible does not work with Firejail of a sandboxing application. It would be great if changes were made accordingly. Since this doesn't seem to be noticed as a bug (for whatever reason), I would like to suggest it as a feature. Details can be found in https://github.com/ansible/ansible/issues/80047 and in https://github.com/ansible/ansible/issues/79702.
The only workaround currently available is to disable Firejail, but this cannot be a permanent solution.

### Issue Type

Feature Idea

### Component Name

ansible

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by bcoca** [comment]
It is not a bug nor does it need a feature because you can already achieve this via configuration as discussed in the previous issues both here and on firejail's issue site. Disabling firejail is not the only way.

**Comment by marek22k** [comment]
I think there is a misunderstanding here. With `ssh_executable="/usr/bin/ssh"` I deactivate Firejail. For Firejail to work, it creates symbolic shortcuts which runs programs with Firejail in `/usr/local/bin`. This leaves the non-sandboxed application in `/usr/bin`. This line would thus disable Firejail.

**Comment by sivel** [comment]
The problem seems to stem from the ControlPath location, it sounds like you either need to disable ControlPersist, or set a path to a different ControlPath.  In any case, this is not something we're going to actively change in Ansible. This is an exercise left to the reader to determine what needs done, and the firejail issue you link includes some info.

**Comment by sivel** [comment]
If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by marek22k** [comment]
Thank you for your patience with me.

**Comment by bcoca** [comment]
Another option is to switch to paramiko as a transport, avoids the whole controlpath issue
