### ISSUE TITLE
ERROR: Ansible requires blocking IO on stdin/stdout/stderr. Non-blocking file handles detected: <stdout>

### ISSUE THREAD

**Issue by yih-redhat** [ansible/ansible#80108]
### Summary

When I run ansible-playbook against target os, I saw this error: ERROR: Ansible requires blocking IO on stdin/stdout/stderr. Non-blocking file handles detected: <stdout> ,  and It only happens on Centos Stream 8, it works well on RHEL and Fedora.

The reason I report this bug is that this error happened 100% in our github CI test on Centos Stream 8 and caused CI result failed, which blocks our pull request to be merged. And the tricky thing is that, when I login the CI runner machine(the same machine) and rerun command, it can succeed. I have no idea but I suspect there must be something wrong there, and I need to find out.

I reported this bug here to see if I can get some help, anyone see this error before? or maybe it is caused by cpu/memory limit?

### Issue Type

Bug Report

### Component Name

ansible-playbook

### Ansible Version

```console
$ ansible --version
[root@centos-stream-8 osbuild-composer]# ansible --version
ansible [core 2.14.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.6 (default, Aug  2 2021, 15:37:19) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
None
```

### OS / Environment

CentOS Stream 8

### Steps to Reproduce

ansible-playbook

### Expected Results

No error

### Actual Results

```console
error happened at line 2444 of https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/jobs/3824249899 , when try to run ansible-playbook command.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
The error you are getting is the result of the stdio file descriptors having been explicitly set to non-blocking. I do not have any specific ideas as to how it might have been done in the case you are seeing.  There are various ways to change this, one such means would be via a python script, that effectively does the opposite of our checks, run before ansible is executed:

```python
import os
import sys

for handle in (sys.stdin, sys.stdout, sys.stderr):
    try:
        fd = handle.fileno()
    except Exception:
        continue

    os.set_blocking(fd, True)
```

We have seen issues where some apps misbehave and errantly leave the stdio file descriptors in non-blocking mode after they have exited, one such case for us was a bug in openssh and ControlPersist.

**Comment by yih-redhat** [comment]
> The error you are getting is the result of the stdio file descriptors having been explicitly set to non-blocking. I do not have any specific ideas as to how it might have been done in the case you are seeing. There are various ways to change this, one such means would be via a python script, that effectively does the opposite of our checks, run before ansible is executed:
> 
> ```python
> import os
> import sys
> 
> for handle in (sys.stdin, sys.stdout, sys.stderr):
>     try:
>         fd = handle.fileno()
>     except Exception:
>         continue
> 
>     os.set_blocking(fd, True)
> ```
> 
> We have seen issues where some apps misbehave and errantly leave the stdio file descriptors in non-blocking mode after they have exited, one such case for us was a bug in openssh and ControlPersist.

Thanks a lot! I will try your script, and hope it works :)

**Comment by yih-redhat** [comment]
hi @sivel , your script works, it solved my problem, thanks!

**Comment by sivel** [comment]
No problem, I'll go ahead and close this out.
