### ISSUE TITLE
hostname module stops working with RH Linux after Fix to get_distribution()

### ISSUE THREAD

**Issue by chestel** [ansible/ansible#8014]
##### Summary:

Commit 2493020d9ff6421666d090d7bb082e92b3613d3e seems to stop the hostname module working for me on Redhat / Oracle Linux 6.
##### Steps To Reproduce:

Test:
from ansible.module_utils.basic import get_distribution
get_distribution()

Old result:
'Red hat enterprise linux server'

New result:
'Red'

Module error with new version:
msg: hostname module cannot be used on platform Linux (Red)
##### Expected Results:

Old result:
'Red hat enterprise linux server'
##### Actual Results:

New result:
'Red'

Module error with new version:
msg: hostname module cannot be used on platform Linux (Red)

Original change was made because @jimi-c says "while testing on the CentOS 7 BETA, I noticed it included a space there, so it was not working for that distribution. So this looks like it's going t be an annoying bug to fix to cover multiple scenarios".

I don't think the space is necessarily the problem with the CentOS 7 BETA. 

I'd propose backing out the get_distribution() change and fixing whatever is complaining about CentOS 7 BETA upstream but I don't have the exact background to the CentOS issue.

Cheers,
Leo

Test:
from ansible.module_utils.basic import get_distribution
get_distribution()

Old result:
'Red hat enterprise linux server'

New result:
'Red'

Module error with new version:
msg: hostname module cannot be used on platform Linux (Red)

commit 2493020d9ff6421666d090d7bb082e92b3613d3e
2  lib/ansible/module_utils/basic.py View
 @@ -129,6 +129,8 @@ def get_distribution():
      if platform.system() == 'Linux':
          try:
              distribution = platform.linux_distribution()[0].capitalize()
-            if " " in distribution:
-                distribution = distribution.split()[0]
            if not distribution and os.path.isfile('/etc/system-release'):
                distribution = platform.linux_distribution(supported_dists=['system'])[0].capitalize()
                if 'Amazon' in distribution:

**Comment by jimi-c** [comment]
I have reverted 2493020d9ff6421666d090d7bb082e92b3613d3e, so we'll figure out another workaround if this is still present in the official CentOS 7 release. Thanks!

**Comment by chestel** [comment]
Thanks Jim!
