### ISSUE TITLE
Integer variable value has trailing zero truncated.

### ISSUE THREAD

**Issue by seanmcconkey** [ansible/ansible#80230]
### Summary

I have 2 vars files containing versions stored as integer values, this is because in some scripts  I need to be able to manipulate those values due to our version numbering differing from the build numbering.

If I have a version of `128.9` or `128.11` these are interpreted correctly and my scripts don't fail, if I use the version number of `128.10` it is interpreted as `128.1` causing the scripts to fail.

You can also reproduce this by taking a string value and using `float` to convert back into an integer and it produces the same result.

### Issue Type

Bug Report

### Component Name

debug

### Ansible Version

```console
ansible [core 2.13.3]
  config file = /home/smcc/github/onprem-ansible/ansible.cfg
  configured module search path = ['/home/smcc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/smcc/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.13 (main, Nov 16 2022, 10:51:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
CACHE_PLUGIN(/home/smcc/github/onprem-ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/smcc/github/onprem-ansible/ansible.cfg) = ./cachedir
CACHE_PLUGIN_TIMEOUT(/home/smcc/github/onprem-ansible/ansible.cfg) = 86400
CALLBACKS_ENABLED(/home/smcc/github/onprem-ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_FORKS(/home/smcc/github/onprem-ansible/ansible.cfg) = 4
DEFAULT_GATHERING(/home/smcc/github/onprem-ansible/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/home/smcc/github/onprem-ansible/ansible.cfg) = ['/home/smcc/github/onprem-ansible/hosts']
DEFAULT_STDOUT_CALLBACK(/home/smcc/github/onprem-ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/smcc/github/onprem-ansible/ansible.cfg) = 30
DISPLAY_SKIPPED_HOSTS(/home/smcc/github/onprem-ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/smcc/github/onprem-ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/smcc/github/onprem-ansible/ansible.cfg) = False

CACHE:
=====

jsonfile:
________
_timeout(/home/smcc/github/onprem-ansible/ansible.cfg) = 86400
_uri(/home/smcc/github/onprem-ansible/ansible.cfg) = /home/smcc/github/onprem-ansible/cachedir

CALLBACK:
========

default:
_______
display_skipped_hosts(/home/smcc/github/onprem-ansible/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/home/smcc/github/onprem-ansible/ansible.cfg) = False

ssh:
___
host_key_checking(/home/smcc/github/onprem-ansible/ansible.cfg) = False
timeout(/home/smcc/github/onprem-ansible/ansible.cfg) = 30
```

### OS / Environment

Alma 8.5

### Steps to Reproduce

**version.yaml**

```version: 128.10```

**docker-vars.yaml**

``` 
---
- images:

    128.10:
            - { hash: '1ae425c8e834', name: web,       group: web,       tarball: 'web.tar.gz' }
  ```

`test-version.yaml`

```
---
- name: Push docker images
  hosts: web

  vars_files:
    - vars/docker-vars.yaml
    - vars/version.yaml

  tasks:

    - debug: msg="{{ version }}"
```

### Expected Results

If you pass a value in as `128.11` it will give the correct output.

Another way to reproduce this is if you take a string value and use `{{ version | float }}`  with `128.10` it does the same thing and truncates the zero, however if given the value of `128.11` produces the correct output.

`ansible-playbook -K  -e version='128.11' test-version.yaml`

```
TASK [debug] ***************************************************************************************************************************
ok: [web] =>
  msg: '128.11'
```

### Actual Results

```console
Using the value `128.10` produces the output, which is clearly incorrect.


TASK [debug] ***************************************************************************************************************************
ok: [web] =>
  msg: '128.1'
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by seanmcconkey** [comment]
This would affect more than the debug module, I've only used that as an example.

**Comment by mkrizek** [comment]
Ansible (Python, Jinja2, yaml, ...) has no way of inferring intended semantics of the value `128.10`, a version in your case. You defined it as a floating point number and it is treated as such:

Python:
```python
% python
>>> 128.10
128.1
>>> 128.10 == 128.1
True
>>> type(128.10)
<class 'float'>
```

Jinja2
```python
>>> from jinja2 import Environment
>>> print(Environment().from_string("{{ v }}").render(v=128.10))
128.1
```

Ansible:
```yaml
- hosts: localhost
  gather_facts: false
  vars:
    version_f: 128.10
    version_s: "128.10"
  tasks:
    - debug:
        var: version_f
    - debug:
        var: version_s
```

```
ok: [localhost] => {
    "version_f": 128.1
}

ok: [localhost] => {
    "version_s": "128.10"
}
```

I suppose you need to define it as a string to preserve the value and then use a [`version` test](https://docs.ansible.com/ansible/devel/collections/ansible/builtin/version_test.html) on that value to manipulate it. Or create a custom plugin (`filter`, `test`, ...) if the `version` test doesn't suit your needs.

**Comment by seanmcconkey** [comment]
@mkrizek thanks for the reply, I suspected it may have been the case, after doing some more reading and some more testing last night. I'll make the change to a string and update my pipeline scripts as well.
