### ISSUE TITLE
"failed to parse" when getting exception in copy module

### ISSUE THREAD

**Issue by yanjost** [ansible/ansible#8032]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.2
also tested on 
- ansible 1.6.6
- ansible 1.7 dev version (1e05688b040a130469d9d2e72cedc2d4d315ff48)
##### Environment:

Run from : Linux 3.11.0-12-generic #19-Ubuntu SMP Wed Oct 9 16:20:46 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
Managing : Linux 2.6.32-431.5.1.el6.x86_64 #1 SMP Fri Jan 10 14:46:43 EST 2014 x86_64 x86_64 x86_64 GNU/Linux
##### Summary:

Ansible is unable to parse the exception message when getting an "Operation not permitted" error in the "copy" module.
##### Steps To Reproduce:

Below is the anonymized trace of execution

<pre>
GATHERING FACTS *************************************************************** 
<host1.domain.net> REMOTE_MODULE setup
<host2.domain.net> REMOTE_MODULE setup
ok: [host1.domain.net]
ok: [host2.domain.net]

TASK: [upload name zip file] ********************************************* 
fatal: [host2.domain.net] => failed to parse: {"msg": "Could not replace file: /home/yannick.jost/.ansible/tmp/ansible-tmp-1404398753.92-188085118133667/source to /mnt/tram/tramdev_app_servers/scratch/install-tram-upload/myapp_name.zip: [Errno 1] Operation not permitted: '/mnt/tram/tramdev_app_servers/scratch/install-tram-upload/.ansible_tmpFF5lVumyapp_name.zip'", "failed": true}
Exception OSError: (2, 'No such file or directory', '/mnt/tram/tramdev_app_servers/scratch/install-tram-upload/.ansible_tmpFF5lVumyapp_name.zip') in <bound method _TemporaryFileWrapper.__del__ of <closed file '<fdopen>', mode 'w+b' at 0xfe7660>> ignored

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/yannick/update.retry

host1.domain.net   : ok=1    changed=0    unreachable=0    failed=0   
host2.domain.net   : ok=1    changed=0    unreachable=1    failed=0   
</pre>

Here is the part of the playbook that does the upload

``` yaml
- name: upload {{ app_name }} zip file
  copy: src={{ source_file }} dest={{ upload_dir }} force=yes
  register: upload_result
  ignore_errors: True
```
##### Expected Results:

Exception should be catched and execution should continue, registering the failure into the "upload_result" variable
##### Actual Results:

Ansible stops execution with a fatal error

**Comment by mpdehaan** [comment]
This is basically a permissions problem.   The failed to parse bit is from the traceback - I do agree it should be caught.

**Comment by dbourguignon** [comment]
@mpdehaan in our case, the "failed to parse" part is kind of expected in some case, as you say, the trouble is to catch it properly

**Comment by yanjost** [comment]
@dbourguignon I don't think it's expected. The correct behavior would be for Ansible to catch properly the original exception and simply mark the operation as "failed". The original error is not a "parse error" but more precisely an "access denied" error.

**Comment by yanjost** [comment]
The error _may_ be located in module_utils/basic.py:atomic_move

**Comment by jimi-c** [comment]
I'm having trouble reproducing this. I'm assuming this is a non-privileged user going to another non-privileged user's directory? Can you give more details about the environment, such as the user permissions on the directories and the file (if it exists) inside that dir? Also assuming selinux is not a factor?

**Comment by mpdehaan** [comment]
Hi,

I'm closing this one as we haven't seen any activity in some time.

If you have continued problems with this one on a recent version of Ansible (i.e. 1.7), please feel free to open a new ticket.   Thank you!
