### ISSUE TITLE
ansible_memfree_mb fact combines disk-cache use of memory

### ISSUE THREAD

**Issue by juliedavila** [ansible/ansible#8035]
##### Summary:

I setup a play to alert whenever memory utilization is dangerously high. I immediately received a handful of alerts and was a bit concerned until I realized it takes into account memory being used by the disk cache and not 'real' memory utilization.
##### Steps To Reproduce:

To reproduce just compare the ansible_memfree_mb fact, which in my example is 

```
        "ansible_memfree_mb": 10550,
        "ansible_memtotal_mb": 15042,
```

with the return value of running

```
free -m
```
##### Actual Results:

In my case returns

```
             total       used       free     shared    buffers     cached
Mem:         15042       4483      10559        139        231       2859
-/+ buffers/cache:       1393      13649
Swap:            0          0          0
```

As you can see, the ansible_facts are correct but misleading, in this case saying only 10gb are free when in fact I have 13gb that are useable.

Perhaps this could be added as a ansible_nocache_memfree_mb fact?

**Comment by mpdehaan** [comment]
Sounds like an RFE for another fact yes.   I might have preferences on a shorter name.

**Comment by juliedavila** [comment]
What's RFE? and yeah, agreed on the name.

**Comment by jimi-c** [comment]
@nousdefions RFE = "request for enhancement". And I see nothing wrong with `ansible_memfree_minus_buffers_and_cache_mb`... :) Really, it almost sounds like this might be better as a dictionary-type fact, like:

<pre>
'ansible_memory': {
   'real': {
      'total': 15042,
      'free': 10559,
      ...
   },
   'nocache': {
      'used': 1393,
      'free': 13649
   },
   'swap': {
      'total': 0,
      'used': 0,
      'free': 0
   }
}
</pre>

Just a thought.

**Comment by juliedavila** [comment]
Ha! Hilarious and yes the dictionary-type makes sense.

**Comment by juliedavila** [comment]
Fixed issue here https://github.com/ansible/ansible/pull/8071

**Comment by jimi-c** [comment]
Yes, I'm going to go ahead and close this, and we'll track the fix in the PR. Thanks!
