### ISSUE TITLE
Add guidelines on when to include install instructions in the installation guide

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#80353]
### Summary

https://docs.ansible.com/ansible/latest/installation_guide/installation_distros.html lists installation instructions for projects outside of Ansible.  The Ansible team maintains only the `pip install` instructions.

As such, this page needs two additions:

- A note to say these instructions are provided by their respective communities. Any bugs/issues should be filed with that community to update these instructions. Ansible maintains only the ``pip install`` instructions.

- A note to describe what distro maintainers need to do to get their install instructions on this page. Something like the following:

Install instructions are included here only for distros with reasonably up to date version of ansible and follow Ansible policies and version constraints. The distribution MUST ensure that ``ansible-core`` and ``ansible`` are synced.
Maintainers MUST include a way to contact them with their instructions here. We also encourage maintainers to join the `Ansible Packaging <https://matrix.to/#/#packaging:ansible.com`_ matrix room.

### Issue Type

Documentation Report

### Component Name

installation_guide/installation_distros.rst

### Ansible Version

```console
$ ansible --version
2.15
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by samccann** [comment]
Related to https://github.com/ansible/ansible/pull/80308

**Comment by MansoorAhmed2000** [comment]
Has this issue been resolved? Or can I still contribute in closing this issue? Also in the comment above which @samccann made stating does "respective communities" refer to distro maintainers? Also is there a particular format these notes have to included, if yes could you point me to them. This will be my attempt contributing anything to open source projects/repositories.
Thanks

**Comment by samccann** [comment]
Closed by https://github.com/ansible/ansible/pull/80389
