### ISSUE TITLE
Add link to changelogs in install guide

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#80367]
### Summary

A user requested that we include the core version in the install guide for installing Ansible. We do have this detail at the top of the porting guides as well as in the Release/Maintenance section where we list out [all the changelogs ](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-community-changelogs)along with maintained/unmaintained status and the included core version.

We should link to that from the install guide.

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/installation_guide/intro_installation.rst

### Ansible Version

```console
$ ansible --version
2.15
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by samccann** [comment]
Docs fix required in two files:

 - Add an anchor at https://github.com/ansible/ansible/blame/devel/docs/docsite/rst/reference_appendices/release_and_maintenance.rst#L74 so we can link to that section.  Something like .. _ansible_changelogs:
 

` Add a sentence below https://github.com/ansible/ansible/blame/devel/docs/docsite/rst/installation_guide/intro_installation.rst#L69 to say something like:

See the :ref:\`Ansible package release status table <ansible_changelogs>\` for the \`\`ansible-core\`\` version included in the package.

**Comment by WeiXinFam-Insta** [comment]
Hi! Is anyone assigned to this issue? I would like to pick up this issue.

**Comment by samccann** [comment]
Thanks @WeiXinFam-Insta !  Just assigned to you and thanks for the help!

**Comment by WeiXinFam-Insta** [comment]
When I was running `rstcheck intro_installation.rst`, I noticed that there are quite a few dangling anchors. Should I clean these up as part of my PR?
```intro_installation.rst:112: (INFO/1) Duplicate implicit target name: "installing ansible".
intro_installation.rst:6: (INFO/1) Duplicate explicit target name: "argcomplete documentation".
intro_installation.rst:1: (INFO/1) Hyperlink target "installation-guide" is not referenced.
intro_installation.rst:2: (INFO/1) Hyperlink target "intro-installation-guide" is not referenced.
intro_installation.rst:13: (INFO/1) Hyperlink target "control-node-requirements" is not referenced.
intro_installation.rst:20: (INFO/1) Hyperlink target "managed-node-requirements" is not referenced.
intro_installation.rst:32: (INFO/1) Hyperlink target "node-requirements-summary" is not referenced.
intro_installation.rst:61: (INFO/1) Hyperlink target "getting-ansible" is not referenced.
intro_installation.rst:63: (INFO/1) Hyperlink target "what-version" is not referenced.
intro_installation.rst:109: (INFO/1) Hyperlink target "pip-install" is not referenced.
intro_installation.rst:126: (INFO/1) Hyperlink target "pip-upgrade" is not referenced.
intro_installation.rst:154: (INFO/1) Hyperlink target "development-install" is not referenced.
intro_installation.rst:167: (INFO/1) Hyperlink target "from-pip-devel" is not referenced.
intro_installation.rst:180: (INFO/1) Hyperlink target "from-source" is not referenced.
intro_installation.rst:228: (INFO/1) Hyperlink target "shell-completion" is not referenced.```

**Comment by samccann** [comment]
Can you explain dangling anchors? We tend to put anchors above every heading, whether we use them or not. It makes it easier on future PRS to link to them w/o having to change two files at once.  That way some contributors can just use the Edit on GitHub button to add a link to an existing anchor.

**Comment by samccann** [comment]
Fixed by https://github.com/ansible/ansible/pull/80391
