### ISSUE TITLE
Mac OS X Ansible - python-apt not possible?

### ISSUE THREAD

**Issue by davidjpeacock** [ansible/ansible#8037]
##### Issue Type:

Feature Request
##### Ansible Version:

ansible 1.6.5
##### Environment:

My situation is that I have a Mac OS X 10.9 machine which I am running Ansible from.  I want to manage Ubuntu 12.04 hosts.
##### Summary:

Forgive me if this is a duplicate (I find it hard to imagine I'm the first to encounter this) but I have spent a lot of time searching for an answer.

My situation is that I have a Mac OS X 10.9 machine which I am running Ansible from.  I want to manage Ubuntu hosts, ergo they require apt.  I'm unable to find out how to install the python-apt or aptitude modules on my Mac, which of course means I cannot do rudimentary package management on the remote Ubuntu hosts, which ultimately means I'm unable to use Ansible to provision my systems.
##### Steps To Reproduce:

N/A - Self explanatory.
##### Expected Results:

Expected to be able to use apt: related modules in playbooks.
##### Actual Results:

Apparently unable to use apt module from a Mac OS X machine when managing Ubuntu machines.

**Comment by bcoca** [comment]
the modules are required on the target (managed machines), not on the Mac.
You can manage machines different from your workstation
(yum/apt/pkgng/portage/etc)

**Comment by davidjpeacock** [comment]
Hmmm curious.  Thanks so much for the answer.  I clearly got something wrong!  I'll investigate.  Thanks again. :-)
