### ISSUE TITLE
ini_file module backup option works incorrectly

### ISSUE THREAD

**Issue by nifr** [ansible/ansible#8046]
##### Issue Type:

 Bug Report
##### Ansible Version:

1.6.6
##### Environment:

Ubuntu 14.04 Desktop => Ubuntu 14.04 Server
##### Summary:

Instead of backing up the current state of the ini-file **before** modification ... the `ini_file` module creates a backup of the modified file itself which makes the functionality kind of useless.
##### Steps To Reproduce:

```
- name: "Create php.ini section foo"
  sudo: yes
  ini_file: backup=yes  dest="/etc/php5/cli/php.ini" section="foo"
```
##### Expected Results:

`ini_file` creates a backup of the current ini-file.
##### Actual Results:

`ini_file` creates a backup of the modified ini-file.

**Comment by mpdehaan** [comment]
the "backup" facility in Ansible in general really needs to be make a remote backup storing each file in a tree based on the hostname, or just be stricken in general.

**Comment by mpdehaan** [comment]
Closing this and opening ticket to track remote backup idea, which I think is the way I want to fix this.  We'll make it high priority enough.   Thanks!
