### ISSUE TITLE
Update Tools and Programs document

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#80479]
### Summary

Change the tools and program page based on [community feedback](https://github.com/ansible-community/community-topics/issues/220).

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/community/other_tools_and_programs.rst

### Ansible Version

```console
$ ansible --version
2.16
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by samccann** [comment]
Repeating the general guidelines:

General guideline - use https://github.com/ansible-community/awesome-ansible as the full curated list. Use this page only for the tools the community maintains. Anything valid we remove from this docs page should be added to awesome ansible.

Other feedback:

- return the list to alphabetical order
- add pycharm link
- remove Jetbrains as not actively maintained
- add toc to top of page
- add disclaimer to all tools etc that aren't maintained by the community (vscode, ara, etc)
- update link to awesome ansible to -https://github.com/ansible-community/awesome-ansible

**Comment by JaroslavKlech** [comment]
I will create a PR for this issue.
