### ISSUE TITLE
ini_file module changes all option names to lower case

### ISSUE THREAD

**Issue by relaxnow** [ansible/ansible#8050]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.3, same in HEAD
##### Environment:

N/A
##### Summary:

See #6875 a patch was made and something else was merged mistakenly so the issue still exists. Copied over issue content because I can't reopen.

ConfigParser by default changes all option names to lower case. This can make the ini file invalid for case-sensitive applications, e.g. XDG .desktop files.

While ConfigParser seems to be a bad choice for ini_file in general (see other issues) and probably should be swapped out at some point, this issue can be fixed easily by overriding ConfigParser.optionxform.
##### Steps To Reproduce:

use ini_file to change an option of a XDG .desktop file, e.g.
ini_file: dest=/usr/share/applications/google-chrome.desktop section="Desktop Entry" \ option="Exec" value="/usr/bin/google-chrome-unstable --incognito %U

observe that all option names were changed to lower case
##### Expected Results:

Only the given option should be changed
##### Actual Results:

All option names are changed to lower case, possibly rendering the file invalid

**Comment by jimi-c** [comment]
I've gone ahead and cherry-picked the original fix from @andreasf's repo, so this issue should be resolved. Please let us know if you continue seeing any problems related to this. Thanks!
