### ISSUE TITLE
Docker API error: client and server don't have same version (client : 1.12, server: 1.10)

### ISSUE THREAD

**Issue by ykxpb** [ansible/ansible#8056]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.6
##### Environment:

ansible on osx 10.9 13.2.0 Darwin Kernel Version 13.2.
docker on ubuntu 14.04, vagrant.
##### Summary:

when close the container with ansible playbook, it give the error msg:
msg: Docker API error: client and server don't have same version (client : 1.12, server: 1.10)
##### Steps To Reproduce:

ansible task:

```
- name: close container
  sudo: true
  sudo_user: root
  docker: image={{ docker }} state=absent
```
##### Expected Results:

container closed.
##### Actual Results:

msg: Docker API error: client and server don't have same version (client : 1.12, server: 1.10)

**Comment by ykxpb** [comment]
sorry, my fault，docker server should be the latest.

**Comment by tcurdt** [comment]
Hm. How did you fix it?

```
msg: Docker API error: client and server don't have same version (client : 1.15, server: 1.12)

$ boot2docker version
Boot2Docker-cli version: v1.3.1
Git commit: 57ccdb8

$ docker version
Client version: 1.3.1
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 4e9bbfa
OS/Arch (client): darwin/amd64
Server version: 1.3.1
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 4e9bbfa

$ ansible --version
ansible 1.7.2
```

Not sure I see the problem in my case.
