### ISSUE TITLE
Support specifying an endpoint type in glance_image

### ISSUE THREAD

**Issue by ericwb** [ansible/ansible#8057]
##### Issue Type:

Feature Idea
##### Ansible Version:

1.6.6
##### Environment:

Ubuntu 12.04.4
##### Summary:

In our environment, the publicURL for glance is https with a self-signed certificate and the internalURL is plain http. So we require an option to specify the endpoint type to use for importing the image.
##### Steps To Reproduce:

n/a
##### Expected Results:

n/a
##### Actual Results:

n/a

**Comment by jimi-c** [comment]
Merged in the above, so closing this. Thanks!
