### ISSUE TITLE
Ansible reboot not working

### ISSUE THREAD

**Issue by blindshare** [ansible/ansible#80580]
### Summary

I created a simple playbook to reboot some machines after "apt upgrade" when they need to restart.
But the playbook fails without any apparent reason.

### Issue Type

Bug Report

### Component Name

reboot

### Ansible Version

```console
$ ansible --version

ansible [core 2.12.10]
  config file = /data/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/ansusr/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

DEFAULT_ASK_PASS(/data/ansible/ansible.cfg) = False
DEFAULT_HOST_LIST(/data/ansible/ansible.cfg) = ['/data/ansible/hosts']
DEFAULT_LOG_PATH(/data/ansible/ansible.cfg) = /data/ansible/logs/ansible.log
DEFAULT_REMOTE_PORT(/data/ansible/ansible.cfg) = 22
DEFAULT_TRANSPORT(/data/ansible/ansible.cfg) = smart
DEPRECATION_WARNINGS(/data/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/data/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/data/ansible/ansible.cfg) = False

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/data/ansible/ansible.cfg) = False

ssh:
___
host_key_checking(/data/ansible/ansible.cfg) = False
pipelining(/data/ansible/ansible.cfg) = True
port(/data/ansible/ansible.cfg) = 22

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

sh:
__
remote_tmp(/data/ansible/ansible.cfg) = $HOME/.ansible/tmp
```

### OS / Environment

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"

### Steps to Reproduce

ansible-playbook -l testsrv tools/reboot.yaml

reboot.yaml:
```
---
- name: Reboot '{{ host }}'
  gather_facts: false
  become: yes
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
```

### Expected Results

rebooting the target machines

### Actual Results

```console
ERROR! 'ansible.builtin.reboot' is not a valid attribute for a Play

The error appears to be in '/data/ansible/tools/reboot.yaml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: Reboot '{{ host }}'
  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mkrizek** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by mkrizek** [comment]
You need to put the task under `tasks` which is completely missing in your playbook, hence the error message:
```
ERROR! 'ansible.builtin.reboot' is not a valid attribute for a Play
```

**Comment by blindshare** [comment]
> You need to put the task under `tasks` which is completely missing in your playbook, hence the error message:
> 
> ```
> ERROR! 'ansible.builtin.reboot' is not a valid attribute for a Play
> ```

Hi, this surprisingly worked ! Although this is never mentioned in any examples I've seen so far. Not even in the official Ansible docu ( [link](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/reboot_module.html) )

Anyway. It works now.
