### ISSUE TITLE
RFE: check mode is configured by default setting it in ansible.cfg

### ISSUE THREAD

**Issue by sugitk** [ansible/ansible#80582]
### Summary

When we develop a playbook, we would like to avoid the actual execution before having confident.  However it needs "ansible-playbook --check" command option, hence sometimes we forget the option and the playbook is executed unexpectedly.

So could you consider to set the "check mode" in `ansible.cfg` by default?

### Issue Type

Feature Idea

### Component Name

config

### Additional Information

(none)

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by nitzmahone** [comment]
There are several other things that we'd have to do to support this- probably adding envvars and `--no-check-mode` to the CLIs to reverse the effect. Probably not something we'll get to anytime soon, but we're not opposed to the idea.

**Comment by BendingBender** [comment]
This would be a really nice addition, indeed.
