### ISSUE TITLE
Whenever I attempt to set something with dconf, I'm receiving the error message "Argument 1 does not allow None" as a value.

### ISSUE THREAD

**Issue by zoliky** [ansible/ansible#80596]
### Summary

Since upgrading to Fedora Workstation version 38, when attempting to use the dconf module to modify settings related to the GNOME desktop environment, Ansible fails with an error message stating that "Argument 1 does not allow None." This error was not occurring prior to the upgrade.

### Issue Type

Bug Report

### Component Name

community.general.dconf

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/zoliky/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/zoliky/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 13.0.1 20230208 (Red Hat 13.0.1-0)] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg

$ cat /etc/ansible/ansible.cfg 

# Since Ansible 2.12 (core):
# To generate an example config file (a "disabled" one with all default settings, commented out):
#               $ ansible-config init --disabled > ansible.cfg
#
# Also you can now have a more complete file by including existing plugins:
# ansible-config init --disabled -t all > ansible.cfg

# For previous versions of Ansible you can check for examples in the 'stable' branches of each version
# Note that this file was always incomplete  and lagging changes to configuration settings

# for example, for 2.9: https://github.com/ansible/ansible/blob/stable-2.9/examples/ansible.cfg
```

### OS / Environment

Fedora 38 Workstation

### Steps to Reproduce

```yaml (paste below)
- name: gnome | appearance | copy wallpapers
  tags: gnome,gnome-wallpaper
  become_user: zoliky
  copy:
    src: wallpapers/
    dest: /home/zoliky/Pictures/
    mode: 0644

- name: gnome | appearance | set wallpaper <--- When Ansible reaches this stage, it throws an error and stops
  tags: gnome,gnome-wallpaper
  become_user: zoliky
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///home/zoliky/Pictures/0004.jpg'"

- name: gnome | appearance | set wallpaper position
  tags: gnome,gnome-wallpaper
  become_user: zoliky
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"

```
$ sudo ansible-pull -U https://github.com/zoliky/ansible.git

### Expected Results

 I expect Ansible to modify the setting using dconf.

### Actual Results

```console
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: Argument 1 does not allow None as a value
fatal: [localhost]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/var/tmp/ansible-tmp-1682080853.3367283-6372-148542091289808/AnsiballZ_dconf.py", line 107, in <module>
        _ansiballz_main()
      File "/var/tmp/ansible-tmp-1682080853.3367283-6372-148542091289808/AnsiballZ_dconf.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/var/tmp/ansible-tmp-1682080853.3367283-6372-148542091289808/AnsiballZ_dconf.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.dconf', init_globals=dict(_module_fqn='ansible_collections.community.general.plugins.modules.dconf', _modlib_path=modlib_path),
      File "<frozen runpy>", line 226, in run_module
      File "<frozen runpy>", line 98, in _run_module_code
      File "<frozen runpy>", line 88, in _run_code
      File "/tmp/ansible_dconf_payload_llrz389w/ansible_dconf_payload.zip/ansible_collections/community/general/plugins/modules/dconf.py", line 437, in <module>
      File "/tmp/ansible_dconf_payload_llrz389w/ansible_dconf_payload.zip/ansible_collections/community/general/plugins/modules/dconf.py", line 429, in main
      File "/tmp/ansible_dconf_payload_llrz389w/ansible_dconf_payload.zip/ansible_collections/community/general/plugins/modules/dconf.py", line 337, in write
      File "/tmp/ansible_dconf_payload_llrz389w/ansible_dconf_payload.zip/ansible_collections/community/general/plugins/modules/dconf.py", line 291, in variants_are_equal
    TypeError: Argument 1 does not allow None as a value
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mkrizek** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general.

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.libera.chat
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by David-Else** [comment]
@zoliky Hi, did you ever fix this or find out what the problem was? I am having the exact same problem with Fedora 38 and am looking for a solution, thanks!

**Comment by zoliky** [comment]
Run these two commands:

```
1. $ ansible-galaxy collection install community.general

2. $ sudo cp /home/zoliky/.ansible/collections/ansible_collections/community/general/plugins/modules/dconf.py /usr/lib/python3.11/site-packages/ansible_collections/community/general/plugins/modules/dconf.py
```

**Comment by zoliky** [comment]
You're right. The solution I provided is more of a hack, and not one that I'm particularly fond of. From my observations, it seems that the root of the problem may lie with Fedora, possibly related to how they package Ansible. Interestingly, I've found that this issue only arises with the Fedora 38 version of Ansible, whereas things worked fine with Fedora 37.

**Comment by zoliky** [comment]
I intially inspired from Jay Lacroix's @LearnLinuxTV config https://github.com/LearnLinuxTV/personal_ansible_desktop_configs

It appears that the culprit in this case is launching ansible with sudo, which is causing the error. I have now switched to running ansible using a normal user and have added the following line to `ansible.cfg` to prompt for the root password.

```
[privilege_escalation]
become_ask_pass = True
```

The I add this line for each task that require root privileges

`become: true`

and remove all the `become_user: yourusername` lines since you run ansible as normal user it defaults to your user anyway.

Another issue with running ansible using sudo is that ansible always reports the `HOME` and `ansible_user_id` variables as root, which is not ideal. Therefore, the solution in this case is to run ansible as a regular user and use the flag that prompts for the root password `become_ask_pass = True` when ansible is launched.
