### ISSUE TITLE
importlib-resources conditional requirements break RPM dependency generation

### ISSUE THREAD

**Issue by nkadel** [ansible/ansible#80608]
### Summary

Building RPMs for ansible-core 2.15.0b2 on RHEL 8, RPM is confused by the conditional requirement for importlib-resources for python < 3.10. Since ansible-core is now being built with python 3.11, which already includes importlib-resources, the flaw is in rpm correctly processing the requirement with the "if" condition in requirements.txt.

### Issue Type

Bug Report

### Component Name

requirements.txt

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.0b2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/nkadel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/nkadel/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Feb 16 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3.11)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### OS / Environment

RHEL 8
RPMs built from my tools at https://github.com/nkadel/ansiblerepo/

### Steps to Reproduce

Build RPMs from unpatched ansible-core-2.15.0b2.tar.gz tarball on RHEL 8.
Try to install RPM. The incorrect, rpmbuild generated importlib-resources dependencies will block deployment 

$ rpm -qp ansible-core-2.15.0-0.1b2.el8.noarch.rpm  --requires
...
python3.11dist(importlib-resources) >= 5.0
python3.11dist(importlib-resources) < 5.1
...

### Expected Results

Successful yum install

### Actual Results

```console
Failed yum install on RHEL 8:
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides python3.11dist(importlib-resources) >= 5.0 needed by ansible-core-2.15.0-0.1b2.el8.noarch
  - nothing provides python3.11dist(importlib-resources) < 5.1 needed by ansible-core-2.15.0-0.1b2.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by nkadel** [comment]
Simply deleting the requirement line for RHEL 8, and relying on the already existing resource in the python 3.11 being used, seems to resolve the issue.

**Comment by flowerysong** [comment]
It's not clear to me what part of this you believe to be a bug in Ansible. Your package build process that you maintain is failing to handle a [correctly specified](https://peps.python.org/pep-0508/#environment-markers) Python dependency, because of a bug either in your process or in `rpm` (which is not part of Ansible.)

**Comment by nkadel** [comment]
It's a heads-up for any ansible package builder dealing with RHEL 8 or its variants. It seems to be a correctly supported feature in modern in more recent python releases and rpm, but the base python used by RPM on RHEL 8 is python 3.6. Since ansible is owned by Red Hat, it's a heads up for the packagers. Fortunately, this one is easy to work around, as follows in the ansible-core.spec file:

# RPM dependency generation confused by dependencies on RHEL 8,
# python 3.11 has this module built in
%if 0%{?el8}
sed -i.bak 's/^importlib_resources /#importlib_resources /g' requirements.txt
%endif
. 
You're probably in a better position than I am to get Red Hat to update rpm dependency on RHEL 8 generation to handle conditionals correctly. I work with people who are cautious, and reluctant, to update critical services like ansible configuration management to the leading operating system. It's a reason I publish backports of leading edge tools.

**Comment by sivel** [comment]
As the ansible core does not manage the PRM builds of ansible-core, I will close this issue.  I have reported this to the folks responsible for the ansible-core package for downstream builds.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
