### ISSUE TITLE
User module, password hash is truncated

### ISSUE THREAD

**Issue by madchap** [ansible/ansible#8061]
##### Issue Type: Bug Report

What kind of ticket is this?  You can say “Bug Report”, “Feature Idea”, “Feature Pull Request”, “New Module Pull Request”, “Bugfix Pull Request”, “Documentation Report”, or “Docs Pull Request”.
##### Ansible Version: ansible 1.6.2

Please supply the verbatim output from running “ansible --version”. 
##### Environment: Centos 6.5

What OS are you running Ansible from and what OS are you managing?  Examples include RHEL 5/6, Centos 5/6, Ubuntu 12.04/13.10, *BSD, Solaris.  If this is a generic feature request or it doesn’t apply, just say “N/A”. 
##### Summary:

The password function of the user module doesn't work as expect, and seems to truncate the password hash.
##### Steps To Reproduce:

See first comment.
##### Expected Results:

The password hash ends up complete on the target system.
##### Actual Results:

The password hash is truncated, and user login doesn't work.

**Comment by madchap** [comment]
Actually, in this case, it is not even just the beginning. The end shadow line should indeed be:

root:$6$rounds=40000$g8YNeDpj8dcXogjV$tI5WCEdedPZHoyEEfldWyt5ChXb.hjACIG/dx3dvkZu/tVgr7r./ogY7lrEsPv9ou/jFPUpd5Ru6Bdqv72XxF/:16259:0:99999:7:::

**Comment by jimi-c** [comment]
Could you please show a small sample playbook that replicates this issue? I cannot reproduce this on the latest devel branch, so you may want to try updating to either 1.6.6 or devel to test and see if this issue has already been addressed.

**Comment by madchap** [comment]
You could just run this ad-hoc task:

ansible srvpdmzsql01 -m user -a "password=$6$rounds=40000$g8YNeDpj8dcXogjV$tI5WCEdedPZHoyEEfldWyt5ChXb.hjACIG/dx3dvkZu/tVgr7r./ogY7lrEsPv9ou/jFPUpd5Ru6Bdqv72XxF/ name=root"

**Comment by jimi-c** [comment]
Are you always running this as an ad-hoc command? If so, your issue there is that you're wrapping the -a arguments in double-quotes, but that string contains $'s, meaning they're most likely being interpreted as shell variables. When I wrap the -a arguments in single-quotes, the above command works as expected:

<pre>
$ echo '$6$rounds=40000$g8YNeDpj8dcXogjV$tI5WCEdedPZHoyEEfldWyt5ChXb.hjACIG/dx3dvkZu/tVgr7r./ogY7lrEsPv9ou/jFPUpd5Ru6Bdqv72XxF/' | wc -c
120
$ ansible ubuntu1404 -m user -a 'password=$6$rounds=40000$g8YNeDpj8dcXogjV$tI5WCEdedPZHoyEEfldWyt5ChXb.hjACIG/dx3dvkZu/tVgr7r./ogY7lrEsPv9ou/jFPUpd5Ru6Bdqv72XxF/ name=testing'
192.168.122.113 | success >> {
    "append": false, 
    "changed": true, 
    "comment": "testing,,,", 
    "group": 1000, 
    "home": "/home/testing", 
    "move_home": false, 
    "name": "testing", 
    "password": "NOT_LOGGING_PASSWORD", 
    "shell": "/bin/bash", 
    "state": "present", 
    "uid": 1000
}
$ ssh 192.168.122.113
Welcome to Ubuntu 14.04 LTS (GNU/Linux 3.13.0-24-generic x86_64)
 * Documentation:  https://help.ubuntu.com/
Last login: Wed Jul  9 11:43:18 2014 from 192.168.122.1
root@ubuntu1404:~# grep testing /etc/shadow | cut -f2 -d ':' | wc -c
120
</pre>

**edit** I made the same mistake when checking the output... both are 120 characters though, as shown above.

**Comment by madchap** [comment]
Doh! Thanks for this... it works better indeed.

Cheers.
fred
