### ISSUE TITLE
Docker module - pull authenticated images

### ISSUE THREAD

**Issue by pixie79** [ansible/ansible#8063]
##### Issue Type:

Bugfix Pull Request
##### Ansible Version:

ansible 1.6.5
##### Environment:

N/A
##### Summary:

Using the current docker module form the library you can not use private repositories for storing images as you can not pull these onto the servers. It looks like the logic was started but not completed. So I have a patch here which works and allows people to pull an image from a private repository.
##### Steps To Reproduce:

Steps to reproduce are have the following settings in your playbook:
- docker:
  image: "{{ docker_registry }}/private_user/redis:latest"
  name: "redis_master{{ env_suffix }}"
  command: "master"
  ports:
  - 9080:9080
  - 9081:9081
    volumes:
  - /chat:/chat
  - /log:/log
    user: "{{ docker_username }}"
    password: "{{ docker_password }}"
    email: "{{ docker_email }}"
##### Expected Results:

When you run the playbook I expect that image to be pulled from the private registry and run. 
##### Actual Results:

Ansible exits with a 403 error from the registry as there are no permissions to access the repository.

If you include the a new variable of 'registry' (which could default to the image name before the first '/' if you want.) You can then add a hock that if 'user' is supplied then login to the registry before trying to pull the image. The linked patch allows the above to work correctly and pulls the image correctly.

https://gist.github.com/pixie79/94dbf8458fa86dc34936

Thanks

Mark

**Comment by jimi-c** [comment]
Could you please send us that patch as a github pull request? It's much easier to merge and preserve attribution that way.

**Comment by pixie79** [comment]
Hi,

I have submitted a pull request (first time it have made one so i hope it is correct)

https://github.com/ansible/ansible/pull/8095

Thanks

Mark

**Comment by jimi-c** [comment]
Great, I'm going to go ahead and close this, and we'll track the PR there. Thanks!
