### ISSUE TITLE
Module mysql_db:  missing db message does not match param in docs

### ISSUE THREAD

**Issue by wrosario** [ansible/ansible#8065]
##### Issue Type:

“Docs Pull Request” or "“Bugfix Pull Request”
##### Ansible Version:

1.7
##### Environment:

Centos 6.5 
##### Summary:

Running module mysql_db with missing db name return error message that does not match the module documentation.
##### Steps To Reproduce:

The following test 

```
- name: test with no parameters 
  mysql_db:
  register: result
  ignore_errors: true
```

`result` the following message: `missing required arguments: db`

Looking at the documentation for mysql_db module, there is no db parameter on the docs http://docs.ansible.com/mysql_db_module.html
##### Expected Results:

Module parameters message should match the documentation online. One of the following suggestions below:
1. `result` should return:  `missing required arguments: name` 
2. update the mysql_db_module.html parameter from `name` to `db` or make it more clear that name is a db alias.
##### Actual Results:

`result` the following message:   `missing required arguments: db`

**Comment by Jmainguy** [comment]
Created pull request to address this bug report. https://github.com/ansible/ansible/pull/8072
