### ISSUE TITLE
Module mysql_db: import state return misleading message when db not found

### ISSUE THREAD

**Issue by wrosario** [ansible/ansible#8066]
##### Issue Type:

 “Docs Pull Request”.
##### Ansible Version:

1.7
##### Environment:

Centos 6.5
##### Summary:

Running module mysql_db with state of import and with a missing database name on mysql return connection error message.
##### Steps To Reproduce:

The following test

```
- name: test state import for a database name with target and missing database
  mysql_db: name=datadump state=import target=/tmp/datadump.sql.bz2
  register: result
  ignore_errors: true
```
##### Expected Results:

Perhaps tell the user that the database name does not exist on mysql 

`result` return the following message:  `msg: database name that you are trying to import does not exist`
##### Actual Results:

`result` return the following message:  `msg: unable to connect, check login_user and login_password are correct, or alternatively check ~/.my.cnf contains credentials`

**Comment by Jmainguy** [comment]
This has previously been reported. #6214 . Recommend closing this as a duplicate, or merging the information as it is captured nicely in this report.

**Comment by wrosario** [comment]
closing issue as dup.
