### ISSUE TITLE
vsphere module not finding datacenter

### ISSUE THREAD

**Issue by dfederlein** [ansible/ansible#8067]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel 366b39cfc1) last updated 2014/07/07 10:46:37 (GMT -700)
##### Environment:

OSX 10.9.3 
##### Summary:

The goal is to create a VM on a large vSphere cluster, in a specific datacenter, in a specific folder.
##### Steps To Reproduce:
- using the Playbook below -
- manually create a VM on vSphere called “ansibletestvm”
- run playbook
- expected results = VM already exists & ansible playbook reports no changes and sucessfully completes the run
- edit playbook - set “guest: ansiblecreatevm”
- run playbook
##### Expected Results:
1. Ansible verifies VM does not exists
2. Ansible creates VM on vSphere cluster
##### Actual Results:
1. Ansible errors out with following:

<localhost> REMOTE_MODULE vsphere_guest password=VALUE_HIDDEN state=present guest=ansiblecreatevm vcenter_hostname=prdasvmw02.gsm1900.org username=Cliverm
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1404760410.46-75812875617325 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1404760410.46-75812875617325 && echo $HOME/.ansible/tmp/ansible-tmp-1404760410.46-75812875617325']
<localhost> PUT /var/folders/3c/lxfy48s918zdv2dk70qpgtlm0000gp/T/tmp887Hcg TO /Users/chrisl/.ansible/tmp/ansible-tmp-1404760410.46-75812875617325/vsphere_guest
<localhost> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/chrisl/.ansible/tmp/ansible-tmp-1404760410.46-75812875617325/vsphere_guest; rm -rf /Users/chrisl/.ansible/tmp/ansible-tmp-1404760410.46-75812875617325/ >/dev/null 2>&1']
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/chrisl/.ansible/tmp/ansible-tmp-1404760410.46-75812875617325/vsphere_guest", line 2515, in <module>
    main()
  File "/Users/chrisl/.ansible/tmp/ansible-tmp-1404760410.46-75812875617325/vsphere_guest", line 1203, in main
    state=state
  File "/Users/chrisl/.ansible/tmp/ansible-tmp-1404760410.46-75812875617325/vsphere_guest", line 602, in create_vm
    v in vsphere_client.get_datacenters().items() if v == datacenter][0]
IndexError: list index out of range

FATAL: all hosts have already failed -- aborting

**Comment by dfederlein** [comment]
Second report added from another source.

**Comment by jimi-c** [comment]
The above patch has been merged in, which should address this issue. Thanks!
