### ISSUE TITLE
mysql_db module ignoring the login_port 

### ISSUE THREAD

**Issue by wrosario** [ansible/ansible#8070]
##### Issue Type:

“Bug Report”
##### Ansible Version:

1.7
##### Environment:

Centos 6.5
##### Summary:

Running module mysql_db with login_port parameter connect to database regardless of the port being used. mysql_db is running on port 3306
##### Steps To Reproduce:

The following test:

```
- name: test mysql_db login_port param
  mysql_db: name=dbname state=present login_port=99999 
  register: result
```
##### Expected Results:

It should fail to connect to port 99999, since mysql is not running on port 99999.
##### Actual Results:

`result` give the following message: `ok: [testhost] => {
    "result": {
        "changed": true, 
        "db": "dbnmae", 
        "invocation": {
            "module_args": "name=dbname state=present login_port=99999", 
            "module_name": "mysql_db"
        }
    }
}``

**Comment by jimi-c** [comment]
The above pull request has been merged in, which should resolve this issue. Thanks!
