### ISSUE TITLE
vault-id with vault_password_file config setting not working

### ISSUE THREAD

**Issue by m-kratochvil** [ansible/ansible#80784]
### Summary

When I execute:
```
ansible-vault view --vault-id <specific-vault-id> <encrypted-secrets-file>
```
with the `vault_password_file` config setting in place and pointing to a shell script, `ansible-vault` fails to call the script file as one would expect according to the documentation (with the `--vault-id <id>` as an argument).

Firstly, I believe my report is related to existing feature request #80119 but I didn't want to "pollute" someone else's issue hence opening a separate one here. I am actually at odds whether what I found is a bug or should be a feature request. I hope someone from the community devs will have a chance to take a look and suggest.

I use vault-id to encrypt my file with secrets. For purposes of this report, the vault id is `shared` and the file with secrets is `shared_vault.yaml`
I have a shell script that produces the password for decrypting the file (named `ansivault-client.sh`).

My goal is simple, I'd like to execute ansible-* commands such as the one above and have ansible automatically call a script file defined in `vault_password_file` config setting with the `--vault-id <vault-id>` as an argument.

I am basing my expectation on the documentation [HERE](https://docs.ansible.com/ansible/latest/vault_guide/vault_managing_passwords.html#storing-vault-passwords:~:text=keyring%2Dclient.py-,Ansible%20executes,-the%20client%20script). Everything works fine when the config setting `vault_password_file` is **NOT** set and I execute:
```
ansible-vault view --vault-id shared@ansivault-client.sh vars/shared_vault.yaml -vvvvv

ansible-vault [core 2.14.4]
  <omitted>
Reading vault password file: ansivault-client.sh
The vault password file /home/michal/cloud/ansivault-client.sh is a client script.
Executing vault password client script: /home/michal/cloud/ansivault-client.sh --vault-id shared
Found a vault_id (shared) in the vaulttext
We have a secret associated with vault id (shared), will try to use to decrypt vars/shared_vault.yaml
Trying to use vault secret=(ClientScriptVaultSecret(filename='/home/michal/cloud/ansivault-client.sh', vault_id='shared')) id=shared to decrypt vars/shared_vault.yaml
Trying secret ClientScriptVaultSecret(filename='/home/michal/cloud/ansivault-client.sh', vault_id='shared') for vault_id=shared
Decrypt of "vars/shared_vault.yaml" successful with secret=ClientScriptVaultSecret(filename='/home/michal/cloud/ansivault-client.sh', vault_id='shared') and vault_id=shared
```
`ansible-vault` correctly calls the script with `--vault-id shared` argument and the password is returned.

This is nice, but I want to simplify things and not have to specify the script explicitly in CLI, but have it supplied by the `vault_password_file` config setting. Once I set this configuration setting (or use the env var `ANSIBLE_VAULT_PASSWORD_FILE`), the expected behavior breaks because I can't specify the `vault-id` anymore. My expectation and understanding is that I should be able to simply do:
```
ansible-vault view --vault-id shared vars/shared_vault.yaml -vvvvv
```
and `ansible-vault` should again call the script with the argument `--vault-id shared` as in the previous example.

But the CLI is parsed differently in this example, the `shared` keyword is not treated as a vault id, but as the actual source of the password and vault id is considered missing.

So `ansible-vault` looks for script file named `shared` which doesn't exist. It then calls the correct script `ansivault-client.sh` as it is defined in the config setting, but since the vault-id was not provided, it uses `--vault-id default` as argument to the script which fails, as there is no password called `default` in my pass store. 

Here's the output:
```
ansible-vault [core 2.14.4]
  <omitted>
Reading vault password file: shared
[WARNING]: Error getting vault password file (None): The vault password file /home/michal/cloud/shared was not found
Reading vault password file: /home/michal/cloud/ansivault-client.sh
The vault password file /home/michal/cloud/ansivault-client.sh is a client script.
Executing vault password client script: /home/michal/cloud/ansivault-client.sh --vault-id default
[WARNING]: Error in vault password file loading (default): Vault password client script /home/michal/cloud/ansivault-client.sh returned non-zero (1) when getting secret for vault-id=default:
b'Error: default is not in the password store.\n'
```

It would be great if the behavior of ansible-* commands calling the script could be made consistent whether the config setting `vault_password_file` is used or not. In the end ansible-* commands should call the script with `--vault-id <id>` in both cases.

### Issue Type

Bug Report

### Component Name

ansible-vault

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.4]
  config file = ansible.cfg
  configured module search path = ['/home/michal/plugins/modules']
  ansible python module location = /home/michal/.venvs/cloud/lib/python3.10/site-packages/ansible
  ansible collection location = /home/michal/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/michal/.venvs/ccloudnet/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/home/michal/.venvs/ccloudnet/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CACHE_PLUGIN(/home/michal/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/michal/ansible.cfg) = .cache/
CACHE_PLUGIN_TIMEOUT(/home/michal/ansible.cfg) = 3600
CALLBACKS_ENABLED(/home/michal/ansible.cfg) = ['profile_tasks']
CONFIG_FILE() = /home/michal/ansible.cfg
DEFAULT_FILTER_PLUGIN_PATH(/home/michal/ansible.cfg) = ['/home/michal/plugins/filters']
DEFAULT_HOST_LIST(/home/michal/ansible.cfg) = ['/home/michal/inventories']
DEFAULT_INVENTORY_PLUGIN_PATH(/home/michal/ansible.cfg) = ['/home/michal/plugins/inventories']
DEFAULT_JINJA2_EXTENSIONS(/home/michal/ansible.cfg) = jinja2.ext.do,jinja2.ext.i18n
DEFAULT_LOG_PATH(/home/michal/ansible.cfg) = /home/michal/ansible.log
DEFAULT_MODULE_PATH(/home/michal/ansible.cfg) = ['/home/michal/plugins/modules']
DEFAULT_ROLES_PATH(/home/michal/ansible.cfg) = ['/home/michal/roles.galaxy', '/home/michal/roles']
DEFAULT_TIMEOUT(/home/michal/ansible.cfg) = 120
DEFAULT_VAULT_PASSWORD_FILE(/home/michal/ansible.cfg) = /home/michal/ansivault-client.sh
DIFF_CONTEXT(/home/michal/ansible.cfg) = 11
HOST_KEY_CHECKING(/home/michal/ansible.cfg) = False
INTERPRETER_PYTHON(/home/michal/ansible.cfg) = auto
INVENTORY_ENABLED(/home/michal/ansible.cfg) = ['yaml', 'script']
INVENTORY_UNPARSED_IS_FAILED(/home/michal/ansible.cfg) = True
MAX_FILE_SIZE_FOR_DIFF(/home/michal/ansible.cfg) = 2048000
PARAMIKO_LOOK_FOR_KEYS(/home/michal/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/michal/ansible.cfg) = 120
TRANSFORM_INVALID_GROUP_CHARS(/home/michal/ansible.cfg) = never

CACHE:
=====

jsonfile:
________
_timeout(/home/michal/ansible.cfg) = 3600
_uri(/home/michal/ansible.cfg) = /home/michal/.cache

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/home/michal/ansible.cfg) = False
look_for_keys(/home/michal/ansible.cfg) = False
record_host_keys(/home/michal/ansible.cfg) = False

ssh:
___
host_key_checking(/home/michal/ansible.cfg) = False
timeout(/home/michal/ansible.cfg) = 120

INVENTORY:
=========

netbox_additionals:
__________________
cache_connection(/home/michal/ansible.cfg) = .cache/
cache_plugin(/home/michal/ansible.cfg) = jsonfile
cache_timeout(/home/michal/ansible.cfg) = 3600
```

### OS / Environment

Ubuntu server 22.04 LTS

### Steps to Reproduce

1. Encrypt a secrets file using specific vault id.
2. Set the configuration setting `vault_password_file` to a script that provides the decryption password.

Then execute:
```yaml (paste below)
ansible-vault view --vault-id <vault-id> <encrypted-secretes-file>
```

### Expected Results

I expected `ansible-vault` to call the script file defined in the configuration setting `vault_password_file` with argument `--vault-id <vault-id>`

### Actual Results

```console
`ansible-vault` looks for script file named <vault-id> which doesn't exist. It then calls the correct script as defined in the config setting `vault_password_file`, but since from ansible perspective the vault-id was not provided, it uses `--vault-id default` as argument to the script , which fails, as there is no password called `default` in the pass store.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by m-kratochvil** [comment]
Thanks for the quick answer @flowerysong and the hint about specifying the whole pair ID/script in one place.
Can you please give me an example how such configuration should look like? I failed to find any example or documentation on how to correctly configure such pair.

The only way I was able to make it work with single vault ID is with following configuration:
```
[defaults]
vault_password_file = ansivault-client.sh
vault_identity = shared
```

However, this doesn't help me, as I have three vault IDs, each with different password and if I set:
```
[defaults]
vault_password_file = ansivault-client.sh
vault_identity_list = shared,lb,private
```
the behavior is again the same as I described before, instead of using the vault IDs from the list as vault IDs, ansible is looking for files named `shared`, `lb` and `private`. This seems to directly contradict the documentation [HERE](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-vault-identity-list)

Thanks,
Michal

**Comment by flowerysong** [comment]
As I said, you have to tell it the whole pair not separate it out. `vault_identity_list` takes a list of vault identities in the same format that they're specified in for `--vault-id`, and has the same semantics.
```
[defaults]
vault_identity_list = shared@ansivault-client.sh,lb@ansivault-client.sh,private@ansivault-client.sh
```

**Comment by m-kratochvil** [comment]
This works like a charm, thank you for clarifying the way this has to be configured. I simply failed to figure this one out myself, it tends to get confusing. Cheers!
