### ISSUE TITLE
Inventory - script module errors on seemingly valid JSON returns

### ISSUE THREAD

**Issue by cidrbl0ck** [ansible/ansible#80800]
### Summary

*Disclaimer, my Python still are horrible and what I have coded in this BR is after ~1 month of trial and error, the community and ChatGPT*

In trying to use Phpipam as the source of truth for Networking related devices this is an inventory script to do so. The information [here](https://dpaste.org/ZptXC)

TL;DR Script (first block in link) uses pymysql to perform query against db 'phpipam' and returns JSON (3rd block in link) when ran manually. Then when using Ansible-Inventory (2nd block), then again from within Execution Environment image (4th block). Custom EE has had RH Insights, IBM*, and Open-Shift collections and Python modules removed. Also has had Meraki, and Cisco collections added.
Then lastly (final block) the error from the Controller when attempting to Sync.

Now the way I understand it, the Controller uses `ansible-inventory` when performing a sync.. but there must be some difference since a-i returns good info and no errors but the Controller fails entirely.
It's this difference that I'm looking to ascertain.

### Issue Type

Bug Report

### Component Name

script.py

### Ansible Version

```console
$ ansible --version
config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/bin/ansible-inventory
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
bash-4.4# ansible-config dump --only-changed
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### OS / Environment

Controller -> Custom EE based on ansible_automation_platform23/ee-supported-rhel8

### Steps to Reproduce

```
ansible-inventory -vvvv -i new_test.py --list

```
Inventory Source -> Sync

### Expected Results

I expect the Controller to product the same JSON results as ansible-inventory then ingest them.

### Actual Results

```console
ansible-inventory [core 2.14.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/bin/ansible-inventory
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /runner/project/new_test.py as it did not pass its verify_file() method
auto declined parsing /runner/project/new_test.py as it did not pass its verify_file() method
yaml declined parsing /runner/project/new_test.py as it did not pass its verify_file() method
toml declined parsing /runner/project/new_test.py as it did not pass its verify_file() method
[WARNING]:  * Failed to parse /runner/project/new_test.py with script plugin:
failed to parse executable inventory script results from
/runner/project/new_test.py: Expecting value: line 1 column 1 (char 0).
Expecting value: line 1 column 1 (char 0)
  File "/usr/lib/python3.9/site-packages/ansible/inventory/manager.py", line 293, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.9/site-packages/ansible/plugins/inventory/script.py", line 150, in parse
    raise AnsibleParserError(to_native(e))
[WARNING]:  * Failed to parse /runner/project/new_test.py with ini plugin:
/runner/project/new_test.py:5: Expected key=value host variable assignment,
got: os
  File "/usr/lib/python3.9/site-packages/ansible/inventory/manager.py", line 293, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.9/site-packages/ansible/plugins/inventory/ini.py", line 137, in parse
    raise AnsibleParserError(e)
[WARNING]: Unable to parse /runner/project/new_test.py as an inventory source
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by cidrbl0ck** [comment]
* I threw all pertinent code/errors into the Dpaste link. If preferred I can edit and paste it all into the Issue.

**Comment by sivel** [comment]
This is the error as reported by the script plugin:

```
[WARNING]:  * Failed to parse /runner/project/new_test.py with script plugin:
failed to parse executable inventory script results from
/runner/project/new_test.py: Expecting value: line 1 column 1 (char 0).
Expecting value: line 1 column 1 (char 0)
  File "/usr/lib/python3.9/site-packages/ansible/inventory/manager.py", line 293, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.9/site-packages/ansible/plugins/inventory/script.py", line 150, in parse
    raise AnsibleParserError(to_native(e))
```

This indicates that the inventory script that it executed returned an empty string to stdout:

```pycon
>>> import json
>>> json.loads('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sivel/git/pyenv/pyenv/versions/3.11.2/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sivel/git/pyenv/pyenv/versions/3.11.2/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sivel/git/pyenv/pyenv/versions/3.11.2/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by cidrbl0ck** [comment]
Thanks Sivel, Good to know. Now the question is, why was it empty.

**Comment by sivel** [comment]
I imagine you'll have to figure that out, by likely adding much more logging to your script, including logging out what it is supposed to be printing via `--list`, and whether or not it is even getting to that `if myargs.list:`.

**Comment by cidrbl0ck** [comment]
Im not asking you to debug what I did but.. did I do this wrong in some fashion? You saw the outputs in my dpaste link yeah? Looks to me like it's returning precisely what it needs to.  Why would ansible-inventory process the file w/o complaint but the Controller does not?

**Comment by sivel** [comment]
You may want to contact Red Hat support in regards to your issue with your Controller.  Since it appears that is the scenario in which the script does not seem to be working, it may be related to the architecture of Controller.  They may have experience or suggestions on how to troubleshoot the inventory script within that environment.  Controller will use a container to execute your inventory script, due to isolation.  So it's not just running it on the same host where AAP Controller is installed, or at least not within that exact environment.

**Comment by cidrbl0ck** [comment]
Right, right.. that's why I ran the script both directly and using ansible-inventory from within the execution environment image that's tied to this Inventory.  I was told in the Ansible-user channel in Matrix that it's using ansible-inventory under the hood and that if a-i provides the right JSON output, then that should just be that.

I still have an open case so I do have a support eng trying to help out.. depends on how you interpret this problem it could or could not be outside of their supportable items.

But assuming the Controller is just running ```ansible-inventory -i script.py --list``` and based off what I showed in that paste link.. then in your opinion it should be working?

**Comment by cidrbl0ck** [comment]
I admit I knee-jerked that response, I apologise. No you did not misread..

**Comment by bcoca** [comment]
Well, the CLI part works (which is what this issue repo handles), but clearly there is still an issue, it just seems to be part of how awx/AAP controller work and that is handled in different issue sites.  That is why I closed the issue here, there is not much else we can do and we've already redirected you to the proper queue/teams to handle the issue.

But the simple answer is 'yes', the basic test for a 'working' inventory script/plugin is getting the expected results via `ansible-inventory`, that is one of it's primary functions.

**Comment by cidrbl0ck** [comment]
And because I just added an edit above.. to be clear what I'm doing is providing a correct `Ansible Inventory JSON` yeah?

**Comment by cidrbl0ck** [comment]
Thanks Brian, I'll def take a look at that. Part of the problem, at least in my case, is the not knowing precisely where to find help since the paid product relies so much on project like these. Finding multiple different things seemingly for the same feature/error/configuration, and having a possible half dozen sources for that information (Ansible-Core/CLI, AWS, Tower, AAP, etc)
For instance the JSON output formats I've found.. some include all: with just groups, some with groups and hosts and some with just hosts. The modules docs page is what I'd consider as gospel and in the case of the `script module` shockingly empty.

Either way thanks for your time, and thanks @sivel too!
