### ISSUE TITLE
Ansible windows with PowerShell - ValueError: zero length field name in format

### ISSUE THREAD

**Issue by vlak** [ansible/ansible#8083]
##### Issue Type:

Bug Report / Documentation Report
##### Ansible Version:

ansible 1.7 (devel 746f52c5aa) last updated 2014/07/01 22:04:51 (GMT +000)
##### Environment:

N/A
##### Summary:

Running PowerShell commands against windows nodes produces ValueError: zero length field name in format
##### Steps To Reproduce:
- Configure winrm/PowerShell on remote windows node
- run: ansible windows -m setup
##### Expected Results:

Command should succeed with failure / error message
##### Actual Results:

Traceback (most recent call last):
File "/root/projects/ansible/lib/ansible/runner/connection_plugins/winrm.py", line 150, in exec_command
result = self.winrm_exec(cmd_parts[0], cmd_parts[1:], from_exec=True)
File "/root/projects/ansible/lib/ansible/runner/connection_plugins/winrm.py", line 121, in winrm_exec
vvvv('WINRM RESULT %r' % response, host=self.host)
File "/usr/lib/python2.6/site-packages/winrm/__init.py", line 12, in repr
self.status_code, self.std_out[:20], self.std_err[:20])
ValueError: zero length field name in format

It is because the code in repr() of winrm/init.py has omitted positional argument specifier in the format string which will work only in Python 2.7 & above but not in Python 2.6, which is the suggested version in Ansible docs.

I fixed the above by changing the line to:

return '<Response code {0}, out "{1}", err "{2}">'.format(......)

May be the document should be updated to insist on Python 2.7 or above - or fix the code

**Comment by cchurch** [comment]
Fixed it in my fork of pywinrm:
`pip install http://github.com/cchurch/pywinrm/archive/master.zip#egg=pywinrm`

**Comment by jimi-c** [comment]
As @cchurch noted above, this is a known issue with pywinrm, which can be addressed by installing our fork. We are working on getting that merged into pywinrm's mainline, so in the future this will not be an issue. Thanks!
