### ISSUE TITLE
Reduce sanity test ignores

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#80840]
### Summary

As of the time of writing this issue, there are 246 ignores in `tests/sanity/ignore.txt`

While some are necessary, there is room for reducing this list by addressing the real issues.

Many `validate-modules` and `pylint` ignores can likely be addressed.

### Issue Type

Feature Idea

### Component Name

ansible

**Comment by sivel** [comment]
As issues or pull requests are created to address this, please add them to the `ansible-core 2.16` project, and provide a link to them as a comment in this issue.

**Comment by Akasurde** [comment]
- https://github.com/ansible/ansible/pull/80854

**Comment by Akasurde** [comment]
https://github.com/ansible/ansible/pull/80855

**Comment by Akasurde** [comment]
bot_skip
