### ISSUE TITLE
ansible.builtin.expect does not actually support "null" timeout

### ISSUE THREAD

**Issue by brianhelba** [ansible/ansible#80982]
### Summary

#40429 added documentation
> Use C(null) to disable timeout.

However, when something like
```yaml
ansible.builtin.expect:
  timeout: null
```
is actually specified, an error results:
> msg: 'argument ''timeout'' is of type <class ''NoneType''> and we were unable to convert to int: <class ''NoneType''> cannot be converted to an int'

It appears that the `timeout` argument is expected to always be an `int`: https://github.com/ansible/ansible/blob/08a647214f493262a1650317da96e18c0c2514e7/lib/ansible/modules/expect.py#L150 .

### Issue Type

Bug Report

### Component Name

ansible.builtin.expect

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.0]
  python version = 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Linux

### Steps to Reproduce

```yaml (paste below)
ansible.builtin.expect:
  timeout: null
```

### Expected Results

`timeout: null` should be accepted.

### Actual Results

```console
msg: 'argument ''timeout'' is of type <class ''NoneType''> and we were unable to convert to int: <class ''NoneType''> cannot be converted to an int'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by brianhelba** [comment]
It seems like there are 3 options for resolving this:
* The simplest fix is to revert #40429.
* Alternatively, it would be ideal if [`ArgumentSpec`](https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#argument-spec) had a way to allow `null` / `None` input values. However, it seems that while the default fallback value is `None`, it does not allow explicit input of `None`. Please let me know if this is mistaken.
* To preserve the functionality, the semantics of `timeout` could be changed, so that a value of `0` will disable the timeout. Internally, the `0` can be changed to `None` when calling `pexpect.run`.

**Comment by sivel** [comment]
You are correct that https://github.com/ansible/ansible/pull/40429 was never right, and as such, is incorrect documentation.

But that doesn't preclude a feature request to make it reality.

**Comment by ambrice** [comment]
I don't know whether timeout: null ever "worked" correctly but in 2.14.5 I had timeout: null per the documentation and it didn't throw any errors, and updating to 2.15.0 broke things for me.

**Comment by bcoca** [comment]
iirc that is due to a fix, none/null was always accepted, now it is only accepted if it is the default or part of 'choices'
