### ISSUE TITLE
ansible does not tell you no hosts are specified

### ISSUE THREAD

**Issue by ggeldenhuis** [ansible/ansible#81]
Trying to be a bit more clear.

I have a filed called ansible_hosts in my home directory.

I have a exported variable called: $ANSIBLE_HOSTS that points to this file.

If I run:
ansible-playbook playbooks/build-auth-main.yml

from within my home directory without setting the ANSIBLE_HOSTS variable ansible runs and gives the following output:

PLAY [auth01.clean.io] ****************************

SETUP PHASE ****************************

TASK: [Ensure 389 Directory Server is installed] *********

PLAY RECAP **********************

so the server called auth01.clean.io is specified in the playbook. As I understand ansible, ansible will only "know" about hosts specified in hosts files. Now since I have not pointed ansible to any host files or have a file in a default location /etc/ansible/... I am expecting ansible to tell me that I am trying to run a playbook against a host it knows nothing about.

**Comment by mpdehaan** [comment]
ansible should just say "warning: no hosts matched" in this case.  It used to do this, it just needs to be reinstated

**Comment by mpdehaan** [comment]
done!
