### ISSUE TITLE
Issue with host_vars and group_vars

### ISSUE THREAD

**Issue by markotitel** [ansible/ansible#8100]
##### Issue Type:

 “Bug Report”
##### Ansible Version:

Branch: devel 
Commit: https://github.com/ansible/ansible/commit/fbdb10d8a5ad790b8971c13f56167f98d4b87eea 
##### Environment:

Vagrant 1.6.3
Image: hashicorp/precise64
##### Summary:

Vagrant provisions a box and starts "shell" provisioner, it just starts a "bootstrap" script.
Which installs some deps and checksout ansible from github. After that ansible-playbook is run and no variables defined in group_vars or host_vars are available.
##### Steps To Reproduce:

Create $dir to reproduce the bug.
Create vagrant file inside $dir https://gist.github.com/markotitel/27d4632eff22be8d73b0.
Create `provisioning` dir.
Create bootstrap.sh https://gist.github.com/markotitel/39c2bea1083021a98bb0

Create `group_vars/all` and add a var

```

---
var: needsWork
```

Create `hosts` 

```
[server]
192.168.50.12
```

Create `site.yml`

```

---
- hosts: server
  user: vagrant
  sudo: yes

  tasks:
    - command: echo {{ var }}
```

Issue vagrant up
##### Expected Results:

```
==> default: GATHERING FACTS *************************************************************** 
==> default: ok: [192.168.50.12]
==> default: 
==> default: TASK: [command echo {{var}}] ************************************************** 
==> default: changed: [192.168.50.12]
```
##### Actual Results:

```
GATHERING FACTS *************************************************************** 
==> default: ok: [192.168.50.12]
==> default: 
==> default: TASK: [command echo {{var}}] ************************************************** 
==> default: fatal: [192.168.50.12] => One or more undefined variables: 'var' is undefined
==> default: 
==> default: FATAL: all hosts have already failed -- aborting
```

**Comment by jimi-c** [comment]
I will bisect to determine which commit from the last week caused this.

**Comment by jimi-c** [comment]
I have been unable to produce a working result, even backing up all the way to 1.6.0. I'm not sure why this would be solved by a pip install of a supported version versus running from source, so I'd like to confirm which commit you were using when you got this working.

**Comment by markotitel** [comment]
Hi,
pip install solves issue because it does not install latest commit Ansible. (right?)

After git clone if I checkout to eg this commit `f5122b8bfcd688bb9f133a26729d0f5eb0e9566d` and then start ansible all works fine.

**Comment by srgvg** [comment]
OK, so there is a bug where host_group_vars is not loaded when relative to the playbook path (as opposed to inventory path.) Looking into.

**Comment by jimi-c** [comment]
The above PR has been merged in, which should resolve this issue. Thanks!
