### ISSUE TITLE
Jinja2 variable start/end strings can't be overridden

### ISSUE THREAD

**Issue by HitScan** [ansible/ansible#8101]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6
##### Environment:

Ubuntu 12.04
##### Summary:

Using the #jinja2:variable_start_string: '[%' , variable_end_string: '%]' template override mentioned in the docs does not work. Variables using [% var %] are not replaced, and jinja will fail on constructs like {{ ... } ... } , which would be ignored if the override were honored.
##### Steps To Reproduce:

Define var to be some value, insert #jinja2:variable_start_string: '[%' , variable_end_string: '%]' at the top of a template, include {{ var }} and [% var %] in the template.
##### Expected Results:

{{ var }} present in the final template output, [% var %] replaced with the value of var.
##### Actual Results:

{{ var }} will be replaced with the value of var and [% var %] is ignored. This still happens on a fresh devel clone.

**Comment by sivel** [comment]
This was partially restored recently in de64bbdc

However, it has been documented for some time now in the documentation for the `template` module (since 488ef22f) that using `variable_start_string` and `variable_end_string` were possible and I have seen this recommended to resolve issues in a large number of instances.

I can definitely see this as a problem.

**Comment by bcoca** [comment]
This PR should fix it https://github.com/ansible/ansible/pull/8040

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by jimi-c** [comment]
Yes, closing this as we knowingly broke this feature in the near term due to security concerns. We'll revisit this at a later date with @bcoca's patch above. Thanks!

**Comment by HitScan** [comment]
With every mention of this feature being removed from docs.ansible.com is it safe to assume it's not coming back to core any time soon/at all? I can work around this in my specific case (ejabberd config files), but others may not be so lucky.
