### ISSUE TITLE
unarchive module checks the creates argument too late

### ISSUE THREAD

**Issue by jonhadfield** [ansible/ansible#8115]
##### Issue Type:

Bugfix Pull Request
##### Ansible Version:

ansible 1.7 (devel 8a6cfa1a23)
##### Environment:

N/A
##### Summary:

Similar to #7357 (now closed), the action plugin performs the copy before the code in the module checks the creates argument.
##### Steps To Reproduce:

```
ansible myserver -m unarchive -a "src=jre1.7.0_55.tar.gz dest=/apps/ creates=/apps/jre1.7.0_55/bin/java"
```
##### Expected Results:

Ansible should skip the task before copying the file, as suggested in module documentation.
##### Actual Results:

An unnecessary file copy to the target machine and then the task is skipped.

**Comment by mpdehaan** [comment]
Closing this just as we have the other pull request which is linked with this one.

Other PR seems good.  Thanks!
