### ISSUE TITLE
Load included role vars files from defaults folder

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#8121]
##### Summary:

Currently, [include_vars](http://docs.ansible.com/include_vars_module.html) will include variables files from within a role's `vars` directory automatically. It would be beneficial to multi-platform or more complex roles to also search for include files within the `defaults` directory, so certain variables could be overridden by playbooks using the roles.
##### Steps To Reproduce:
1. View the layout of the [geerlingguy.java](https://github.com/geerlingguy/ansible-role-java) role.
2. When running the role, some users need to override the platform-specific default "java_packages".
3. Currently, Ansible only loads the included vars files inside the role's `vars` folder—but if these files (`Debian.yml` and `RedHat.yml`) are used, users can't easily override the variables. If the files within the `defaults` folder are used, users can still override the variables within their playbook without resorting to adding additional configuration files (like using `group_by` to set up their infrastructure).
##### Expected Results:

Ansible looks for the included vars files inside the role's `vars` directory, and also inside the role's `defaults` directory.
##### Actual Results:

Ansible only looks for the included vars files inside the role's `vars` directory. Included files inside `defaults` are ignored.

**Comment by geerlingguy** [comment]
Another note: In Ansible 1.5.x, I remember being able to have a setup like the following:

Role:

```
/vars/Debian.yml - 'php_example' variable
/vars/RedHat.yml - 'php_example' variable
/defaults/main.yml - empty 'php_example' variable
```

Playbook:

```
'php_example' variable which would override what was in Debian/RedHat.yml
```

As of 1.6.6, it seems this no longer works—the variables inside vars/Debian.yml and vars/RedHat.yml are overriding the variables I have in my playbook's included vars file.

**Comment by mwilliammyers** [comment]
:+1:

**Comment by jimi-c** [comment]
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!

**Comment by geerlingguy** [comment]
@jimi-c - So, uh... I _think_ I'm following the process, but I'm unclear on how the issues vs. PR thing works—I submitted this PR (https://github.com/ansible/proposals/pull/21), but do I also create an issue with the exact same contents?

Or was I supposed to create an issue first, then work on details there... _then_ create the PR?

**Comment by jimi-c** [comment]
Yep looks good. I think we do need to tweak that - I'm not sure what the benefit of having an issue and a PR is... but that's what we agreed on at he time :)

**Comment by jimi-c** [comment]
Really the main motivation is that approved proposals get put on the roadmap, and time is dedicated to working on them (as opposed to random feature_ideas, which (obviously) can sit around with no action on them for quite a while.

**Comment by geerlingguy** [comment]
Thanks! And yeah, that's the nature of software development :)
