### ISSUE TITLE
Ansible as a project scaffolding/bootstrapping tool

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#8125]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.7
##### Environment:

N/A
##### Summary:

Ansible would make a great project scaffolding and initialization tool for bootstrapping new projects. Presently I'm using http://yeoman.io for bootstrapping new web app projects. It occurred to me that 100% of what Yeoman does could be done 150% better with Ansible. The idea is to pull down project scaffolds as ansible-galaxy roles. There are only two tiny features that would make this possible:
- Ability to run globally installed roles ad-hoc in a new folder
- Ability to access the pwd from where the ad-hoc command was run as a variable in the role's playbooks

Then I could just do something like...

```
$ mkdir myProject && cd myProject
$ ansible-playbook --role="rvangundy.webapp"
```

And this would take me through prompts and begin populating myProject with templated project files and folders, as well as install global prerequisites like Vagrant, VirtualBox, etc... (this is one area Yeoman falls behind).

Would love to make a PR but need to learn Python first...

**Comment by jimi-c** [comment]
I believe there is no barrier to doing this currently with a regular playbook that used --extra-args to specify the target directory, and the inventory host would simply be localhost. I suggest you take this to the ansible-project mailing list for discussion, since we typically reserve github issues for bugs and features, rather than discussions. Thanks!

**Comment by jangondol** [comment]
@rvangundy See also https://stackoverflow.com/a/25585743/1332977 for an idea how to locally execute roles from Ansible Galaxy, even without creating inventory files or writing playbooks to disk. If you customize / extend my StackOverflow solution (e.g. with `--extra-args` as @jimi-c suggested) and wrap the result in a Bash function (saved in `.bashrc`) then your function can elegantly do what you originally intended. I think that this could indeed open up new interesting uses for Ansible (i.e., project bootstrapping).
