### ISSUE TITLE
mysql_db module does not expand directory 

### ISSUE THREAD

**Issue by wrosario** [ansible/ansible#8128]
##### Issue Type:

 “Bug Report”
##### Ansible Version:

"1.7" 
##### Environment:

 Centos 6.5
##### Summary:

Using mysql_db fail to expand directory when using the state import.
##### Steps To Reproduce:

```
- name: create output test directory
  file: name={{output_dir}} state=directory
```

```
- name: test state import a database 
  mysql_db: name={{ db_name }} state=import target={{output_dir}}/data.sql
```
##### Expected Results:

Since output_dir directory was created under /root/ansible_testing, myslq_db should expand from ~/ansible_testing/data.sql to /root/ansible_testing/data.sql during the state=import.
##### Actual Results:

```
failed: [testhost] => {"failed": true}
msg: /bin/sh: ~/ansible_testing/data.sql: No such file or directory
```

**Comment by jimi-c** [comment]
I've pushed the above patch which should resolve this issue. Thanks!
