### ISSUE TITLE
Special characters inside password paramerers (inventory file)

### ISSUE THREAD

**Issue by ArkaGPL** [ansible/ansible#8137]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.7 
##### Environment:

Localhost : Debian Wheezy 7.2 3.2.0-4-amd64 
Remotehost : Debian Lenny 5.0.7
##### Summary:

When you put a password with special characters inside host inventory file it breaks everything after it and even if you put the password parameter at the end the login result in a authentication failure.
##### Steps To Reproduce:

Inside hosts inventory file:

Case 1:

```
server ansible_ssh_host=192.168.0.1 ansible_ssh_port=2222 ansible_ssh_user=myuser ansible_su_pass=th!s-P4ssw0rd#
```

or Case 2 this which breaks ansible_ssh_user:

```
server ansible_ssh_host=192.168.0.1 ansible_ssh_port=2222 ansible_su_pass=th!s-P4ssw0rd# ansible_ssh_user=myuser
```
##### Expected Results:

Passwords should work even with special characters (!-# didn't try enough to find which one is the issue).
##### Actual Results:

Case 1:

```
ansible server -m raw --su --su-user=root -a "whoami"
server | FAILED | rc=1 >>

su: Authentication failure
```

Case 2:

```
server | FAILED => SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh
```

**Comment by mpdehaan** [comment]
You can escape a comment (#) in the inventory file with "#" or also use group_vars.

If this doesn't address your problem please let us know.

**Comment by ArkaGPL** [comment]
server ansible_ssh_host=192.168.0.1 ansible_ssh_port=2222 ansible_ssh_user=myuser ansible_su_pass=th!s-P4ssw0rd##

This doesn't work, even with three #. # inside passwords are not so rare and this confusion may be met by many others (https://github.com/ansible/ansible/issues/7053).

**Comment by new23d** [comment]
\# works. Ansible 1.9.1 though.
