### ISSUE TITLE
Error when using vault filter: do_vault() got an unexpected keyword argument ''vault_id'

### ISSUE THREAD

**Issue by obaranov** [ansible/ansible#81420]
### Summary

In the documentation for https://docs.ansible.com/ansible/latest/collections/ansible/builtin/vault_filter.html, you can see the `vault_id` parameter should be available. But the implementation of that filter expects the `vaultid` parameter:  https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/encryption.py#L20

The same name collision happens for the unvault filter.

So when calling a task with vault filter and `vault_id` parameter I'm getting and error (see Actual Result)

### Issue Type

Bug Report

### Component Name

pip

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.1]
  python version = 3.11.4 (main, Jun  7 2023, 00:00:00) [GCC 13.1.1 20230511 (Red Hat 13.1.1-2)] (/home/obaranov/.virtualenvs/aapqaprov/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
N/A
```

### OS / Environment

Fedora 38

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: '{{ "secret"|ansible.builtin.vault("test", vault_id="test") }}'


```

### Expected Results

The `vault` filter documentation should give a proper parameter name, or `do_vault` should expose `vault_id` parameter instead of `vaultid`. I think the documentation fix is preferable to keep compatibility. 

### Actual Results

```console
fatal: [localhost]: FAILED! => 
  msg: 'Unexpected templating type error occurred on ({{ "secret"|ansible.builtin.vault("test", vault_id="test") }}): do_vault() got an unexpected keyword argument ''vault_id''. do_vault() got an unexpected keyword argument ''vault_id'''
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by webknjaz** [comment]
Bugfix PR: https://github.com/ansible/ansible/pull/81422
