### ISSUE TITLE
INI format inventory throws "invalid decimal literal"

### ISSUE THREAD

**Issue by pcfe** [ansible/ansible#81457]
### Summary

The following minimal inventory

```ini
gitlab-runner-01            ansible_host=gitlab-runner-01.internal.pcfe.net  ansible_user=root
zimaboard-01                ansible_host=zimaboard-01.internal.pcfe.net      ansible_user=ansible
```

Makes ansible complain

```text
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
```

But I fail to understand why.

As soon as I adjust the entries as follows (non numerical char right before the `.`), it stops complaining but of course that does not help me as the DNS names are then wrong.

```ini
gitlab-runner-01            ansible_host=gitlab-runner-01foo.internal.pcfe.net  ansible_user=root
zimaboard-01                ansible_host=zimaboard-01bar.internal.pcfe.net      ansible_user=ansible
```

### Issue Type

Bug Report

### Component Name

ini plugin

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.8]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/pcfe/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/pcfe/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.4 (main, Jun  7 2023, 00:00:00) [GCC 13.1.1 20230511 (Red Hat 13.1.1-2)] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### OS / Environment

pcfe@t3600 ~ $ cat /etc/os-release 
NAME="Fedora Linux"
VERSION="38 (KDE Plasma)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (KDE Plasma)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="KDE Plasma"
VARIANT_ID=kde

pcfe@t3600 ~ $ rpm -qf $(which ansible)
ansible-core-2.14.8-1.fc38.noarch
pcfe@t3600 ~ $ rpm -V ansible-core-2.14.8-1.fc38.noarch
pcfe@t3600 ~ $ 

### Steps to Reproduce

```bash
pcfe@t3600 ~ $ pwd
/home/pcfe
pcfe@t3600 ~ $ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
pcfe@t3600 ~ $ rpm -qf /etc/ansible/ansible.cfg 
ansible-core-2.14.8-1.fc38.noarch
pcfe@t3600 ~ $ rpm -V ansible-core-2.14.8-1.fc38.noarch
pcfe@t3600 ~ $ cat ~/tmp/inventory.ini 
gitlab-runner-01            ansible_host=gitlab-runner-01.internal.pcfe.net  ansible_user=root
zimaboard-01                ansible_host=zimaboard-01.internal.pcfe.net      ansible_user=ansible
pcfe@t3600 ~ $ ansible -i ~/tmp/inventory.ini -m ping all
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
gitlab-runner-01 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
zimaboard-01 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
pcfe@t3600 ~ $ 
```

### Expected Results

I would like to understand what makes Ansible complain about this minimal INI type inventory.
If there is nothing I did wrong in the inventory, then I would like Ansible to please not complain about invalid decimal literals.

Additionally, if there is something invalid in my INI format inventory, then it would be nice if Ansible was more specific (affected line number, pointer to which part of some spec I violate) towards the user.
Not every user might be comfortable zeroing in on such inventory lines with for example `git bisect` (which is how I found the two offending lines in my full inventory).

### Actual Results

```console
pcfe@t3600 ~ $ ls -l /home/pcfe/.ansible/plugins /home/pcfe/.ansible/collections 
ls: cannot access '/home/pcfe/.ansible/plugins': No such file or directory
ls: cannot access '/home/pcfe/.ansible/collections': No such file or directory
pcfe@t3600 ~ $ cat ~/tmp/inventory.ini 
gitlab-runner-01            ansible_host=gitlab-runner-01.internal.pcfe.net  ansible_user=root
zimaboard-01                ansible_host=zimaboard-01.internal.pcfe.net      ansible_user=ansible
pcfe@t3600 ~ $ ansible -i ~/tmp/inventory.ini -m ping all -vvvv
ansible [core 2.14.8]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/pcfe/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/pcfe/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.4 (main, Jun  7 2023, 00:00:00) [GCC 13.1.1 20230511 (Red Hat 13.1.1-2)] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/pcfe/tmp/inventory.ini as it did not pass its verify_file() method
script declined parsing /home/pcfe/tmp/inventory.ini as it did not pass its verify_file() method
auto declined parsing /home/pcfe/tmp/inventory.ini as it did not pass its verify_file() method
yaml declined parsing /home/pcfe/tmp/inventory.ini as it did not pass its verify_file() method
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
Parsed /home/pcfe/tmp/inventory.ini inventory source with ini plugin
[…]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by bcoca** [comment]
its because it looks like a decimal + operation (intended case `10.1 - 923.312`) .. this is a match done internally by Python when we ask it to try to 'type' the variable.

**Comment by sivel** [comment]
fwiw, the message you were getting is just a warning, it didn't seem to affect anything.  We may be able to suppress the warning though.

If we fail to parse the value with `ast.literal_eval` we allow it to remain a string by catching the exceptions that happen, but appears as though python is still emitting a warning.

**Comment by pcfe** [comment]
Patch confirmed working. Thank you.

After editing `/usr/lib/python3.11/site-packages/ansible/plugins/inventory/ini.py` (owned by `ansible-core-2.14.8-1.fc38.noarch`) as per posted patch

```bash
pcfe@t3600 ~ $ cat ~/tmp/inventory.ini
gitlab-runner-01            ansible_host=gitlab-runner-01.internal.pcfe.net  ansible_user=root
zimaboard-01                ansible_host=zimaboard-01.internal.pcfe.net      ansible_user=ansible
pcfe@t3600 ~ $ ansible -i ~/tmp/inventory.ini -m ping all
gitlab-runner-01 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
zimaboard-01 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
```
