### ISSUE TITLE
netscaler module auth and json decode errors.

### ISSUE THREAD

**Issue by freewilll** [ansible/ansible#8152]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.3
##### Environment:

N/A
##### Summary:

There seem to be two bugs in the netscaler module:
1. The http basic auth headers aren't being sent
2. The JSON decode function expects a file handle, not a string
##### Steps To Reproduce:

ansible -i inventory ... -m netscaler -a "name=... nsc_host=... user=... password=... action=enable validate_certs=no type=server"
##### Expected Results:

success
##### Actual Results:

Errors:

Issue 1:
The output I got initially was:
'NoneType' object has no attribute 'read'

Issue 2:
Then I fixed the headers error, and got
'str' object has no attribute 'read'

**Comment by freewilll** [comment]
Here's what works for me:

Issue 1:
response, info = fetch_url(self.module, request_url, data=data_json)
should be:
response, info = fetch_url(self.module, request_url, data=data_json, headers=headers)

Issue 2:
return json.load(response.read())
should be:
return json.load(response)

**Comment by mpdehaan** [comment]
This is working for some folks but it may be related to your configuration.

If you would like to submit a pull request that would be a great!

**Comment by miguelcnf** [comment]
I've actually come across this today. 

Both fixes @willangenent mentioned are required due to:
- we need the authentication headers to be passed as the nitro api requires it
- json.load already performs a .read() on the fp so we can't pass it as an argument

Would be happy to PR this if no one else does.

**Comment by freewilll** [comment]
Here it is: https://github.com/ansible/ansible/pull/8187

**Comment by mpdehaan** [comment]
Closing per above, thanks for tracking down the commit!
