### ISSUE TITLE
supervisorctl restart problem using 'service'

### ISSUE THREAD

**Issue by holms** [ansible/ansible#8155]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.4
##### Environment:

Ubuntu 14.04 LTS (GNU/Linux 3.13.0-24-generic x86_64)
##### Summary:

Unable to restart servicectl with "service" resource. Using command on server gives no problem at all. When provisioning - it fails.
##### Steps To Reproduce:

Any dummy config of supervisor will do.

```
    # Supervisor config for gunicorn
    - supervisorctl: name='gunicorn' state=stopped config=/etc/supervisor/conf.d/gunicorn.conf
    - supervisorctl: name='gunicorn' state=started config=/etc/supervisor/conf.d/gunicorn.conf
```
##### Expected Results:

Should work without a problem as it works on server:

```
root@api:~# supervisorctl stop gunicorn
gunicorn: stopped
root@api:~# supervisorctl start gunicorn
gunicorn: started
```
##### Actual Results:

```
TASK: [supervisorctl name='gunicorn' state=started config=/etc/supervisor/conf.d/gunicorn.conf] ***
failed: [54.203.xxx.xxx] => {"failed": true}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/holms/prod.retry
```

I've tried to add sleep, but this didn't help at all.

**Comment by mpdehaan** [comment]
You're filing this on 1.5.4, which is quite dated, however that should not be a factor.

Ultimately we know about this as we had similar problems with supervisorctl on Ubuntu for Ansible Tower and had to work around it.

issue a manual start/stop and it's good, or manually execute the supervisorctl command vs using the service script.

This is an upstream bug in Ubuntu, unfortunately, and they should fix it eventually.
- shell: supervisorctl stop
- shell: supervisorctl start

Is the recommended approach for this service for now.

(For those interested, Fedora/RHEL/CentOS does not have this problem)

**Comment by holms** [comment]
@mpdehaan Thanks for verifying this. Not be rude or smtng, but how does chef handles this? servicectl restart works fine in there with their provided resource? Used multiple times already.
