### ISSUE TITLE
Very jargonny domain specific "info box", about collections: FQCN

### ISSUE THREAD

**Issue by christopherreay** [ansible/ansible#81588]
### Summary

Each time I read an info block like this:

> Note
> 
> This vars plugin is part of `ansible-core` and included in all Ansible installations. In most cases, you can use the short plugin name host_group_vars even without specifying the collections: keyword. However, we recommend you use the FQCN for easy linking to the plugin documentation and to avoid conflicting with other collections that may have the same vars plugin name.

I think: "What does this actually mean"?, and "Why doesnt it actually tell me what to do"? and "Why are there no links in this info box"?

A positive, clear message might look like this:

> Note
> 
> This vars plugin is part of `ansible-core` and included in all Ansible installations. In most cases, you can identify the plugin with `host_group_vars` however we recommend you use the full identifier `ansible-core/host_group_vars`, which is then an (FQCN)[Link to FQCN meaning] for easy linking to the plugin documentation and to avoid conflicting with other collections that may have the same vars plugin name.

You can see here Ive had to guess what the "collections: keyword" means by context, and I have no idea what FQCN means, except that it is obviously an "absolute path" to something in ansible. I shouldnt have to think that much to understand what this means. Its an info note. Its something that anyone familiar with Ansible would already know, but it is written in ansible jargon.

cheers :)

### Issue Type

Documentation Report

### Component Name

generic site wide issue

### Ansible Version

```console
latest documentation
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
n/a
```

### OS / Environment

n/a

### Additional Information

This kind of information is targeted at new users, but it is written in jargon, with no links to the jargon.
It requires that the user infer a concrete meaning though there is no value gained from explaining it solely as an abstraction.
It would be easier to understand if it was clear in the concrete, and would not be any longer as a piece of text.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mkrizek** [comment]
This should be reported against https://github.com/ansible/ansible-documentation.

**Comment by christopherreay** [comment]
OK done ty
