### ISSUE TITLE
Settings in the inventory file are interpreted as numbers

### ISSUE THREAD

**Issue by Drarok** [ansible/ansible#8161]
##### Issue Type:

Bug Report
##### Ansible Version:
ansible 2.2
ansible 1.6.6
##### Environment:

N/A
##### Summary:

When parsing variables in the inventory file that look like exponential numeric values, the string "inf" is output in a template instead of the variable's string value.
##### Steps To Reproduce:

In my inventory file, I had something like the following:

```
127.0.0.1 my_var=1234e567
```

When outputting my_var in a template (`{{ my_var }}`), I would only get the string "inf". The reason appears to me that the variable is interpreted as an exponential-notation number, which then is infinite.

Note that wrapping the value in quotes in the inventory file has no effect on this bug.

Possibly related to #8137.
##### Expected Results:

I would expect the same results from placing my variable in the inventory file as putting the variables into host_vars or other files.
##### Actual Results:

The string "inf" is output when variables appear to contain exponential numeric values.
## Workaround

Putting the value into host_vars is a work around for this bug. (Thanks to benno in #ansible on freenode.)

**Comment by bcoca** [comment]
this is the yaml translation as 123e10 is exponential notation​, quote it
or use !str pragma

**Comment by Drarok** [comment]
@bcoca: quoting it had no effect, I did try that. Not heard of the !str pragma, I'll take a look. I still think this should be treated as a bug, though, since the parsing behaviour is different to other files in the same area.

**Comment by bcoca** [comment]
Not really a bug, it is a YAML "feature" yaml.org/spec/current.html

 !!str is used to force a string type when it is ambiguous, strings that
are all numbers with the letter "e" in them  can be interpreted as a number
with an exponent (shorthand way to write large numbers).
​

**Comment by Drarok** [comment]
But this issue doesn't occur in the host_vars YAML files, only in the inventory file?

**Comment by bcoca** [comment]
sorry, misinterpreted the issue, its not the YAML parser it is the python
ast library, which is what is used to interpret the variables in the ini
file. !!str will not work here, not sure there is a way around it aside
from moving it elsewhere.

**Comment by mpdehaan** [comment]
Yay for scientific notation!

As an easy workaround, I'd move this to group_vars/groupname or host_vars/hostname where this won't try to auto-convert variables.  It's a cleaner place to keep variables anyway (IMHO) and also allows for structured data.

I suppose we could add some code that checks to see if the value contains letters and not try to run it through the ast path.

**Comment by pbthorste** [comment]
One way around this is to define the variable in the inventory file as a string with whitespace, and then use the trim method from jinja2

```
[my-server]
server.com my_numeric_var=' 123 '
```

And when referencing the variable in a playbook:

`- debug: msg="numeric var is: {{ my_numeric_var|trim }}`

**Comment by bcoca** [comment]
closing as there are  workarounds and we don't want to remove 'type discovery' from ini inventory.
