### ISSUE TITLE
Connection reset by peer on an AIX host provisioning

### ISSUE THREAD

**Issue by mpailloncy** [ansible/ansible#8164]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.2
##### Environment:

Linux host : Debian 7.5 with python 2.7.3 and Ansible 1.6.2
AIX host : AIX 6.1 with python 2.7.2
##### Summary:

I would like to provision an AIX host using Ansible installed on a Linux host.
##### Steps To Reproduce:

```
$> ansible -i myhosts aix -m ping -vvvv
```
##### Expected Results:

Ansible should be able to execute ping module on the AIX host.
##### Actual Results:

```
<aix> ESTABLISH CONNECTION FOR USER: myuser
<aix> REMOTE_MODULE ping
<aix> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/ansible/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=myuser', '-o', 'ConnectTimeout=10', 'aix', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1405515992.16-30163890915163 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1405515992.16-30163890915163 && echo $HOME/.ansible/tmp/ansible-tmp-1405515992.16-30163890915163'"]
<aix> PUT /tmp/tmpb1NMJ5 TO /ansible/.ansible/tmp/ansible-tmp-1405515992.16-30163890915163/ping

aix | FAILED => failed to transfer file to /ansible/.ansible/tmp/ansible-tmp-1405515992.16-30163890915163/ping:
Couldn't read packet: Connection reset by peer

```

**Comment by mpdehaan** [comment]
Hard to say what's going on with your network, but this is unlikely to be an ansible problem.

Can you please stop by ansible-project for some help?

**Comment by masseybradley** [comment]
Hey! If possible, I would like to re-open this ticket for review. I agree that the original error seems to be a network configuration issue however it is indeed impossible to use the ping module towards an AIX system. It appears that the ping command executes on the remote server however the command fails with an rc=1:

<beaix> ESTABLISH CONNECTION FOR USER: oracle
<beaix> REMOTE_MODULE command ping
<beaix> EXEC ['sshpass', '-d6', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/tinytox/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'User=oracle', '-o', 'ConnectTimeout=10', 'beaix', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1445416354.51-240225455300208 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1445416354.51-240225455300208 && echo $HOME/.ansible/tmp/ansible-tmp-1445416354.51-240225455300208'"]
<beaix> PUT /tmp/tmpnITYuI TO /export/.ansible/tmp/ansible-tmp-1445416354.51-240225455300208/command
<beaix> EXEC ['sshpass', '-d6', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/tinytox/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'User=user', '-o', 'ConnectTimeout=10', 'beaix', u"/bin/sh -c 'LANG=en_US.utf8 LC_CTYPE=en_US.utf8 /usr/bin/python /export/.ansible/tmp/ansible-tmp-1445416354.51-240225455300208/command; rm -rf /export/.ansible/tmp/ansible-tmp-1445416354.51-240225455300208/ >/dev/null 2>&1'"]
beaix | FAILED | rc=1 >>
usage: ping [-dDLnqrRv] [-a address_family] [-c count] [-w timeout]
	[-f | -i wait] [-I a.b.c.d] [-l preload] [-o interface]
	[-p pattern] [-s packet_size] [-S IPv6_hostname_or_address]
	[-T ttl] host [data size] [npackets]

**Comment by masseybradley** [comment]
Hey! If possible, I would like to re-open this ticket for review. I agree that the original error seems to be a network configuration issue however it is indeed impossible to use the ping module towards an AIX system. It appears that the ping command executes on the remote server however the command fails with an rc=1:

ESTABLISH CONNECTION FOR USER: user
REMOTE_MODULE command ping
EXEC ['sshpass', '-d6', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/tinytox/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'User=oracle', '-o', 'ConnectTimeout=10', 'beaix', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1445416354.51-240225455300208 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1445416354.51-240225455300208 && echo $HOME/.ansible/tmp/ansible-tmp-1445416354.51-240225455300208'"]
PUT /tmp/tmpnITYuI TO /export/.ansible/tmp/ansible-tmp-1445416354.51-240225455300208/command
EXEC ['sshpass', '-d6', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/tinytox/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'User=user', '-o', 'ConnectTimeout=10', 'beaix', u"/bin/sh -c 'LANG=en_US.utf8 LC_CTYPE=en_US.utf8 /usr/bin/python /export/.ansible/tmp/ansible-tmp-1445416354.51-240225455300208/command; rm -rf /export/.ansible/tmp/ansible-tmp-1445416354.51-240225455300208/ >/dev/null 2>&1'"]
beaix | FAILED | rc=1 >>
usage: ping [-dDLnqrRv] [-a address_family] [-c count] [-w timeout]
[-f | -i wait] [-I a.b.c.d] [-l preload] [-o interface]
[-p pattern] [-s packet_size] [-S IPv6_hostname_or_address]
[-T ttl] host [data size] [npackets]
