### ISSUE TITLE
Recent commit breaks mysql_db

### ISSUE THREAD

**Issue by pakal** [ansible/ansible#8173]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.7 (devel 7c2cb58673) last updated 2014/07/17 21:13:43 (GMT +300)
##### Environment:

Ubuntu 14.04
##### Summary:

Following commit 
https://github.com/ansible/ansible/commit/ac73822405eebaf50fb94195e4ea315ba5805463 , mysql_db module is broken, as it expands a path variable ("target = os.path.expandvars(os.path.expanduser(target))") which might be None.
##### Steps To Reproduce:

Have a task:
- name: remove the test database
  mysql_db: login_user=root login_password={{ root_db_password }} login_host="localhost" name=test state=absent
##### Expected Results:

Mysql "test" db should be successfully removed
##### Actual Results:

TASK: [mariadb | remove the test database] ************************************
<localhost> REMOTE_MODULE mysql_db login_user=root login_password=VALUE_HIDDEN login_host="localhost" name=test state=absent
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1405622599.7-264047426097829 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1405622599.7-264047426097829 && echo $HOME/.ansible/tmp/ansible-tmp-1405622599.7-264047426097829']
<localhost> PUT /tmp/tmpoveRoF TO /home/vagrant/.ansible/tmp/ansible-tmp-1405622599.7-264047426097829/mysql_db
<localhost> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=zvwghqgmekczeshuforhkaacgttfypll] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-zvwghqgmekczeshuforhkaacgttfypll; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1405622599.7-264047426097829/mysql_db; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1405622599.7-264047426097829/ >/dev/null 2>&1'"'"''
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: SUDO-SUCCESS-zvwghqgmekczeshuforhkaacgttfypll

Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1405622599.7-264047426097829/mysql_db", line 1664,
in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1405622599.7-264047426097829/mysql_db", line 286, in main
    target = os.path.expandvars(os.path.expanduser(target))
  File "/usr/lib/python2.7/posixpath.py", line 261, in expanduser
    if not path.startswith('~'):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by mpdehaan** [comment]
While I appreciate the bug report, this does not include information about how to trigger the error.

Can you please supply this so we can add an appropriate test?  (mysql integration tests are underway in another branch).

Thanks!

**Comment by pakal** [comment]
Right, here is the expected issue format, above.

**Comment by drybjed** [comment]
Confirming the issue with `mysql_db` module. Example playbook:

```
---
- hosts: all
  sudo: True
  tasks:
    - apt: name={{ item }} state=latest install_recommends=no
      with_items: [ 'mysql-server', 'python-mysqldb' ]
    - mysql_db: name=test state=present
    - mysql_db: name=test state=absent
```

**Comment by Jmainguy** [comment]
Fails for me as well. I am looking into which commit broke it.

**Comment by pakal** [comment]
it's due to commit https://github.com/ansible/ansible/commit/ac73822405eebaf50fb94195e4ea315ba5805463

**Comment by Jmainguy** [comment]
Thank you pakal, you are correct. I have submitted a fix for that pull request. Give it a shot and let me know if you see any errors. Basically it was breaking before because target was not specified, so it was trying to expand variables where target=None. Now it will only try to expand the variables when target != None, ie it is defined.

**Comment by pakal** [comment]
Yep that seems to be it B-)

**Comment by jimi-c** [comment]
Sorry about that, and thanks for the fix @Jmainguy.
