### ISSUE TITLE
git module does not update origin remote when repo url changes

### ISSUE THREAD

**Issue by jgornick** [ansible/ansible#8177]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.6
##### Environment:

OS X 10.9.4
##### Summary:

If you've previously cloned/updated a git repository using the git module and move the repository to a different address, the git module is unable to update the url for the origin remote and tries to update via the old repo address.
##### Steps To Reproduce:
- Clone a repository into a directory using the git module
- Update using the same repository
- Move the repository to another location
- Update the repo url in the git module and try to update the source code
##### Expected Results:

The source from the new repository address is used to update.
##### Actual Results:

The git module never changes the origin remote url which then causes an error if you've transferred or moved the repository to a new url.

The git module seems to reference the origin remote name, but doesn't update the remote url if it's changed.

**Comment by mpdehaan** [comment]
I'm going to link this to #4658 and this can be tracked together.

For those interested, pull requests to fix changing the origin would be very welcome.   I agree it should be possible.
