### ISSUE TITLE
service Module Fails To Stop All PostgreSQL Clusters

### ISSUE THREAD

**Issue by Combatjuan** [ansible/ansible#8183]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.1
##### Environment:

Ubuntu Server 12.04, 64bit
##### Summary:

I ran into a situation where:
ansible <host> -m service -a "name=postgresql state=stopped"

returned status "Ok" but upon further examination, two postgresql clusters were still running.  Examining the box, this was revelead:

user@host:~# service postgresql status
9.2/B (port 5433): down
9.3/A (port 5442): online
9.3/B (port 5432): online

In my case, the 9.2 cluster didn't need to exist anymore, so I removed the package and /etc/postgresql/9.2 folder then reran status.  As expected it showed:

user@host:~# service postgresql status
9.3/A (port 5442): online
9.3/B (port 5432): online

The same service module command then properly stopped postgresql.  I haven't looked at the source yet, but I suspect that it sees a line with 'down' (or possibly the first line includes 'down'?), it assumes that the service is stopped.
##### Steps To Reproduce:

Create multiple postgresql clusters.  Stop the first one such that it is not running.  Set the postgresql service to status stopped with the service module.  Observe how some of the clusters are not stopped.
##### Expected Results:

When the service is set to "stopped", ensure that all clusters are stopped (this is what happens when you run "service postgresql stop").
When the service is set to "started", ensure that all clusters are started (which is what happens when you run "service postgresql start").

If something else happens, it's an error.
##### Actual Results:

The cluster that was stopped remains stopped, other clusters remain running.

**Comment by mpdehaan** [comment]
Sounds like an issue with the init script you are calling to me, not ansible.

Feel free to stop by ansible-project for advice if you like, but the service module just interacts with the OS facility.

**Comment by mevinbabuc** [comment]
I'm having a similar issue. I have two postgresql instances running 9.1 and 9.4. the 9.4 instance is in stopped state, It fails to stop 9.1 on running the ansible script.
