### ISSUE TITLE
ansible-base overwriting ansible-core

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#81865]
### Summary

If pip tries to install ansible-core and ansible-base, ansible-base winns and overwrites files of ansible-core. Most noticeable almost all the plugins.

Can we change the ansible-core package in a way that it doesn't allow being installed simultaneously to ansible-base? Or so that it at least "winns"?

### Issue Type

Bug Report

### Component Name

packaging

### Ansible Version

```console
$ ansible --version
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

PIP

### Steps to Reproduce

Kinda syntetic, but it's the simplest testcase, so...

run `pip install -r requirements.txt`
with this requirements.txt file:

```
ansible-base>=2.10.17
ansible-core>=2.15.4
```

Simplest test to see the overwritten files is to now uninstall ansible-base. It'll remove the files it overwrote and ansible-core even though it reports being installed is now not only "just" outdated but completely broken.

### Expected Results

I expect either pip failing to install one of these two packages, OR a true side by side install.

### Actual Results

```console
ansible-base overwriting ansible-core and thereby replacing new code with almost two years old one.
One example for files that get overwritten are the plugins (like e.g. first_found.py).
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by webknjaz** [comment]
> I expect either pip failing to install one of these two packages, OR a true side by side install.

That's a known bug in pip. Nothing we can do about it.

**Comment by sivel** [comment]
The reasons why this is the way it is are varied and many.  But the short of it is that it's just not feasible to do within python packaging and pip specifically.  We had some hacky work arounds in the past using `setup.py` that looked for other "distributions" that provided the python ansible namespace.  Unfortunately python packaging is moving towards declarative packaging, and not running dynamic code during install, and with pip caching wheels, that dynamic code could only ever run once, and we need to distribute python wheels.

pip doesn't support any type of mechanism for packages to obsolete or conflict with other package names providing the same namespace, so ultimately, without support from pip, we cannot do anything.

Furthermore, ansible-base should be forgotten about, and never touched or used any longer.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by agowa** [comment]
> Furthermore, ansible-base should be forgotten about, and never touched or used any longer.

that was exactly the issue. I completely ignored it, but didn't work, as it takes precedence over the newer ansible-core, so I got screwed by it still being in the requirements.txt of an older project...

Tbh, it has been there for a long time, I don't even want to think about how many tasks will fail once I remove it and all plugins, modules, ... are at the current version as they should be and not just as I thought they are...
