### ISSUE TITLE
ansible does not use ~/.ssh/config user variable ?

### ISSUE THREAD

**Issue by sprhawk** [ansible/ansible#8198]
##### Issue Type:

ansible ad-hoc command cannot use ~/.ssh/config user variable to execute ssh connection
##### Ansible Version:

ansible 1.7 (devel 7c2cb58673)
##### Environment:

OSX 10.9.4
##### Summary:

I have to use following inventory:
[office]
server-host ansible_ssh_user=remote-user-name

 it doesn't use User config in ~/.ssh/config

**Comment by mpdehaan** [comment]
No, it doesn't.  For more elaboration stop by ansible-project, but the general idea is that we're a config management system and you may need to connect via multiple user accounts, so Ansible has it's own defaults.

You can also specify this easily in a playbook with the "remote_user" directive.
