### ISSUE TITLE
clean up playbook summary output

### ISSUE THREAD

**Issue by ggeldenhuis** [ansible/ansible#82]
When running a playbook I get the following:

auth01.example.com                : ok=   5 changed=   0 unreachable=   1 failed=   0

I think it would be more readable if it looked like:

auth01.example.com               : ok=5    changed=0    unreachable=1    failed=0

or even:
auth01.example.com               : ok=5,    changed=0,    unreachable=1,    failed=0

**Comment by mpdehaan** [comment]
ok, I think you're saying you don't like my width controls on the output that keeps things in neat columns when the results go over 1 digit.

I am not sure I want to change this, because then the word 'failed', 'changed', etc, would not always line up.

I could see maybe printing a header and making it tabular, sure.

**Comment by ggeldenhuis** [comment]
The problem is that on my console there is significant space between the equals sign and the number. This means that the number is next the next category so it is confusing to read. Unfortunately the formatting engine in github removes this space so it looks more readable than it really is... I have not used ansible in relation to the use case you mention as motivation for the current formatting, but would agree that it would be a good reason.

**Comment by mpdehaan** [comment]
I'll consider some sort of table output.

**Comment by mpdehaan** [comment]
here's the start of a decent function via a stackoverflow post:

http://stackoverflow.com/questions/5909873/python-pretty-printing-ascii-tables

we'll do something like that

**Comment by mpdehaan** [comment]
not planning on doing this any more seeing I've been using this format for a while and it seems fine to me, patches to do the above are welcome however.
