### ISSUE TITLE
Windows RM commands timeout at 60 seconds, failing long running commands

### ISSUE THREAD

**Issue by uxp** [ansible/ansible#8206]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7 (f0aab11)
##### Environment:

Host: Mac OS X 10.9.4 (13E28)

Client: Microsoft Windows NT 6.3.9600.0 (Server 2012-r2)
##### Summary:

Command connections timeout at 60 seconds, making some commands unusable (win_get_url with large files, for example)
##### Steps To Reproduce:

This should be a sufficiently basic `Vagrantfile` (for vmware fusion, customize as needed). Vagrant 1.6+ needed for Vagrant Cloud support. Simply run `vagrant up`, specifying the provider as needed, while in the directory containing the following two files.

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "win-server-2012-r2-std-sql"

  # https://vagrantcloud.com/hplogsdon/win-server-2012-r2-std
  config.vm.box = "hplogsdon/win-server-2012-r2-std"

  config.vm.provider :vmware_fusion do |v, override|
    v.gui = false
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
    v.vmx["cpuid.coresPerSocket"] = "1"
    v.vmx["ethernet0.virtualDev"] = "vmxnet3"
    v.vmx["RemoteDisplay.vnc.enabled"] = "false"
    v.vmx["RemoteDisplay.vnc.port"] = "5900"
    v.vmx["scsi0.virtualDev"] = "lsisas1068"
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "vagrant.yml"
    ansible.limit = 'all'
    ansible.verbose = "vvvv"
  end
```

The most basic example playbook: save as `vagrant.yml` in the same directory as the above `Vagrantfile`.

```

---
- hosts: all
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_pass: vagrant
    ansible_ssh_port: 5985
    ansible_connection: winrm
  tasks:
    - name: Fetch SQL Server installer
      win_get_url:
        url: "http://download.microsoft.com/download/8/D/D/8DD7BDBA-CEF7-4D8E-8C16-D9F69527F909/ENU/x64/SQLEXPRWT_x64_ENU.exe"
        dest: 'C:\Windows\Temp\SQLEXPRWT_x64_ENU.exe'
```
##### Expected Results:

After a couple minutes, the SQL Server express installer should exist in the `C:\Windows\Temp\` folder.
##### Actual Results:

After exactly 60 seconds, Ansible outputs this stack trace:

```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ansible-1.7-py2.7.egg/ansible/runner/connection_plugins/winrm.py", line 147, in exec_command
    result = self._winrm_exec(cmd_parts[0], cmd_parts[1:], from_exec=True)
  File "/Library/Python/2.7/site-packages/ansible-1.7-py2.7.egg/ansible/runner/connection_plugins/winrm.py", line 116, in _winrm_exec
    response = Response(self.protocol.get_command_output(self.shell_id, command_id))
  File "/Library/Python/2.7/site-packages/winrm/protocol.py", line 277, in get_command_output
    self._raw_get_command_output(shell_id, command_id)
  File "/Library/Python/2.7/site-packages/winrm/protocol.py", line 293, in _raw_get_command_output
    rs = self.send_message(xmltodict.unparse(rq))
  File "/Library/Python/2.7/site-packages/winrm/protocol.py", line 173, in send_message
    return self.transport.send_message(message)
  File "/Library/Python/2.7/site-packages/winrm/transport.py", line 90, in send_message
    raise WinRMTransportError(error_message)
WinRMTransportError: Bad HTTP response returned from server. Code 500
fatal: [win-server-2012-r2-std-sql] => failed to exec cmd PowerShell -NoProfile -NonInteractive -EncodedCommand [..Snipped..]
```

**Comment by mpdehaan** [comment]
Thanks for the report.

You can leave out the vagrant info in future bug reports, the ansible playbook is enough for us, and not everyone is using vagrant.

**Comment by uxp** [comment]
Actually, this might need to be pushed upstream to pywinrm. Looks like they're hardcoding the 60 seconds, despite having a set_timeout method on their protocol class.

**Comment by cchurch** [comment]
pywinrm upstream hasn't accepted my other pull request (https://github.com/diyan/pywinrm/pull/19) so I'll most likely be the one making this change on my fork (https://github.com/cchurch/pywinrm) to support Ansible.

**Comment by cchurch** [comment]
# Closing This Ticket

Hi!

We believe these recent commits to the upstream [pywinrm](https://github.com/diyan/pywinrm) project should resolve this question or problem for you:

https://github.com/diyan/pywinrm/commit/df049454a9309280866e0156805ccda12d71c93a

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
