### ISSUE TITLE
Official Dockerfile and Build

### ISSUE THREAD

**Issue by ToBeReplaced** [ansible/ansible#8212]
##### Issue Type:

Feature Idea
##### Ansible Version:

N/A
##### Environment:

N/A
##### Summary:

Ansible should support its own official build with the [Docker Hub Registry](https://registry.hub.docker.com/).

Ansible is an excellent tool for orchestrating containerized systems. Unfortunately, making sure that the host machine has all of the required dependencies installed to run the range of modules can be tricky. In particular, there are some modules that rely on python modules that may not be available on the host's distribution, and so running a virtualenv is required.

By supporting its own official build, ansible could sidestep this issue by installing all of the required dependencies independent of the host's distribution. Moreover, this could allow hosts to upgrade Ansible more rapidly instead of waiting for a new release on the host's distribution.

The end result would be to be able to run commands like:
`docker run --rm -v /path/to/my/data:data:ro ansible:1.7 ansible-playbook -i production site.yaml`

This would run `ansible-playbook -i production site.yaml` with ansible version 1.7 in a read-only copy of the directory at /path/to/my/data in an environment that has all of the module dependencies like `docker-py`, `python-keyczar`, `pymongo`, `urllib`, etc.

Another side effect of this would be to be able to lock-down version numbers for all of the modules ansible depends on that are outside of ansible's control, reducing the potential bug footprint.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by ToBeReplaced** [comment]
As this is receiving the lowest priority, here's an example that is fully functioning as per above for my use case. I would imagine that any failing cases would be quickly ironed out by users.

``` Dockerfile
# Use centos for confidence in system packages on rebuild
FROM centos:centos7

# Create a virtualenv for ansible
RUN ["yum", "install", "-y", "python-virtualenv"]
RUN ["virtualenv", "venv"]

# pycurl requires curl-config
RUN ["yum", "install", "-y", "libcurl-devel"]
# MySQL-python requires mysql_config
RUN ["yum", "install", "-y", "mariadb-devel"]
# psycopg2 requires postgresql-devel
RUN ["yum", "install", "-y", "postgresql-devel"]
# libvirt-python requires libvirt-devel
RUN ["yum", "install", "-y", "libvirt-devel"]
# ovirt-engine-sdk-python requires libxml2-devel and libxslt-devel
RUN ["yum", "install", "-y", "libxml2-devel", "libxslt-devel"]
# python-glanceclient requires libffi-devel
RUN ["yum", "install", "-y", "libffi-devel"]
# python-glanceclient requires gcc
RUN ["yum", "install", "-y", "gcc"]

# We use ADD instead of COPY for docker < 1.0
ADD requirements_freeze.txt requirements.txt

# Add the virtualenv's bin directory to PATH
ENV PATH /venv/bin/:$PATH

# Install ansible's module dependencies
RUN ["pip", "install", "-r", "requirements.txt"]
```

Corresponding requirements.txt:

```
# Ansible version
ansible==1.6.6

# Cloud Modules
apache-libcloud==0.15.1
azure==0.8.1
boto==2.31.1
docker-py==0.3.2
dopy==0.2.3
libvirt-python==1.2.5
linode-python==1.0
ovirt-engine-sdk-python==3.4.3.0
pycurl==7.19.5
pyrax==1.9.0
pysphere==0.1.8
python-glanceclient==0.13.1
python-keystoneclient==0.9.0
python-novaclient==2.18.1
python-neutronclient==2.3.5
python-quantumclient==2.2.4.3

# Database Modules
MySQL-python==1.2.4
psycopg2==2.5.3
pymongo==2.7.1
redis==2.10.1

# Utilities Modules
# TODO: pyzmq requires libzmq-devel which is not available on centos
# pyzmq==14.3.1
python-keyczar==0.71c
```

Generated requirements_freeze.txt:

```
Babel==1.3
Jinja2==2.7.3
MarkupSafe==0.23
MySQL-python==1.2.4
PyYAML==3.11
ansible==1.6.6
apache-libcloud==0.15.1
azure==0.8.1
boto==2.31.1
cffi==0.8.6
cliff==1.6.1
cmd2==0.6.7
cryptography==0.5.2
docker-py==0.3.2
dopy==0.2.3
ecdsa==0.11
iso8601==0.1.10
jsonpatch==1.7
jsonpointer==1.4
jsonschema==2.3.0
keyring==3.8
libvirt-python==1.2.5
linode-python==1.0
lxml==3.3.5
mock==1.0.1
netaddr==0.7.12
os-diskconfig-python-novaclient-ext==0.1.2
os-networksv2-python-novaclient-ext==0.21
os-virtual-interfacesv2-python-novaclient-ext==0.15
oslo.config==1.3.0
ovirt-engine-sdk-python==3.4.3.0
paramiko==1.14.0
pbr==0.9.0
prettytable==0.7.2
psycopg2==2.5.3
pyOpenSSL==0.14
pyasn1==0.1.7
pycparser==2.10
pycrypto==2.6.1
pycurl==7.19.5
pymongo==2.7.1
pyparsing==2.0.2
pyrax==1.9.0
pysphere==0.1.8
python-glanceclient==0.13.1
python-keyczar==0.71c
python-keystoneclient==0.9.0
python-neutronclient==2.3.5
python-novaclient==2.18.1
python-quantumclient==2.2.4.3
pytz==2014.4
rackspace-auth-openstack==1.3
rackspace-novaclient==1.4
rax-default-network-flags-python-novaclient-ext==0.2.4
rax-scheduled-images-python-novaclient-ext==0.2.2
redis==2.10.1
requests==2.2.1
simplejson==3.5.3
six==1.7.3
stevedore==0.15
warlock==1.1.0
websocket-client==0.11.0
wsgiref==0.1.2
```

Usage: Place Dockerfile and requirements_freeze.txt into a folder. Run:

`docker build -t ansible:1.6.6 <path/to/folder>`. 

Then, if your playbooks are in `<playbook-dir>`, you can run ansible with: 

`docker run --rm -v <playbook-dir>:data:ro ansible:1.6.6 ansible-playbook -i data/production data/site.yaml`

**Comment by mpdehaan** [comment]
I'm not sure this still makes a lot of sense but am open to thoughts to the contrary.

Ansible as a control machine can be installed with only one command "pip install ansible" (or a git clone).

Given we could provide an image, but that image would have to exist for every OS combo for using ansible as a provisioner, which is something we don't want to be in the business of maintaining. 

I would welcome more discussion on perhaps ansible-devel however.

**Comment by jlmitch5** [comment]
@mpdehaan Is ansible-devel on freenode? this is a loaded question because I just checked and it's not ;)  the better question is if ansible-devel is externally-facing?

**Comment by ToBeReplaced** [comment]
@jlmitch5 It's a google group. I created a post for this issue:
https://groups.google.com/forum/#!topic/ansible-devel/j__ZH-0KbmQ
