### ISSUE TITLE
patch breaks usage of .ssh/config

### ISSUE THREAD

**Issue by bcoca** [ansible/ansible#8216]
##### Issue Type:

regression
##### Ansible Version:

current devel as of  0f91add86f7d30e6d895e01bbfddb93a3b5e48df (works in 1.6.6)
##### Environment:

All
##### Summary:

this patch 0f91add86f7d30e6d895e01bbfddb93a3b5e48df always sets user for the ssh command, which will then avoid using .ssh/config, it reverts an old patch of mine that enables .ssh/config when not setting remote user in ansible
##### Steps To Reproduce:

Setup user at .ssh/config for a host then do not set the user in ansible, when it was working it would pick up the user from the config.
##### Expected Results:

ssh in as user set in config
##### Actual Results:

always ssh as current user

**Comment by Jmainguy** [comment]
I can confirm it is not currently reading from .ssh/config when a user is not specified.

**Comment by ciupicri** [comment]
I can confirm that's the commit to blame.

**Comment by Jmainguy** [comment]
If self.common_args += ["-o", "User=" is explicitly defined, then it will not read from ~/.ssh/config.

However if this is reverted, it will go back to the functionality as follows.

If --user is not defined when running ansible, it will not be defined defined in the runner code, and it will check ~/.ssh/config, if not defined in there it will use the current user. If --user is defined when running ansible then it will use that user.

**Comment by bcoca** [comment]
yes, that is exactly how it was working since i first made this patch
around 0.6

**Comment by jimi-c** [comment]
I thought we had another issue for this, however I can't seem to find it now. I'll go ahead and revert that commit as I have seen a report of this somewhere else at least.

**Comment by Jmainguy** [comment]
#7170 is the report you are thinking of I believe.

**Comment by jimi-c** [comment]
@Jmainguy ahh yes, there it was, it was on the original PR. I've gone ahead and reverted this now. Thanks!
