### ISSUE TITLE
variable interpolation in user: field not working

### ISSUE THREAD

**Issue by cigor** [ansible/ansible#822]
if the user field in a playbook is a variable ($someuser or the like) no interpolation happens. Regardless if the variable is set via vars: vars_files: or --extra-vars

conflicts with Documentation http://ansible.github.com/playbooks2.html#passing-variables-on-the-command-line

$ ansible --version
ansible 0.7 (devel 093bbd1c82) last updated 2012/08/09 10:56:18 (GMT +200)

**Comment by mpdehaan** [comment]
ok, that's a more generic bug -- and easier to explain and fix, thanks.

**Comment by mpdehaan** [comment]
I may be commenting on the wrong thing with the above, I know hosts: $hosts works and will investigate

**Comment by mpdehaan** [comment]
Fixed in 07f459f -- I did not make all fields work, but I fixed user.  Should be good to go!  Thanks!
