### ISSUE TITLE
"first_available_file" does not work with fatal message "One or more undefined variables: 'item' is undefined"

### ISSUE THREAD

**Issue by dragon3** [ansible/ansible#8220]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.3 - 1.6.6
##### Environment:

Mac OSX 10.9.4, Linux
##### Summary:

I use "first_available_file" on copy and template modules, but since 1.6.3 it's does not work.
When I tried "git bisect" to find a commit which made this problem, I found it:

```
b99ea2723a793c3e81c8319b9d8db7828f881839 is the first bad commit
```

This commit was related #7535.

And I tried to fix this problem, so I found that the following change on release1.6.6 works for me.

```
diff --git a/lib/ansible/playbook/play.py b/lib/ansible/playbook/play.py
index d2a09ec..1af9b07 100644
--- a/lib/ansible/playbook/play.py
+++ b/lib/ansible/playbook/play.py
@@ -572,6 +572,7 @@ class Play(object):
                     new_role = x['role_name']

                 mv = task_vars.copy()
+                mv['item'] = ''
                 for t in tokens[1:]:
                     (k,v) = t.split("=", 1)
                     mv[k] = template(self.basedir, v, mv)
```

But I'm not sure it is correct and it has side effects.
##### Steps To Reproduce:

I create a following simple inventroy structure to reproduce this.

```
.
├── hosts
├── roles
│   └── role1
│       ├── files
│       │   ├── file1.txt
│       │   └── file2.txt
│       └── tasks
│           └── main.yml
└── site.yml
```

hosts

```
[local]
localhost
```

site.yml

```

---
- name: test
  hosts: local
  connection: local
  gather_facts: false
  roles:
    - role1
```

roles/roles1/tasks/main.yml

```

---
- name: copy file
  copy: src={{ item }} dest=/tmp/{{ item }}
  first_available_file:
    - file2.txt
    - file1.txt
```
##### Expected Results:

```
$ ansible-playbook -i hosts site.yml -v

PLAY [test] *******************************************************************

TASK: [role1 | copy file] *****************************************************
ok: [localhost] => {"changed": false, "dest": "/tmp/file2.txt", "gid": 20, "group": "staff", "item": "", "md5sum": "5149d403009a139c7e085405ef762e1a", "mode": "0644", "owner": "foobar", "path": "/tmp/file2.txt", "size": 6, "state": "file", "uid": 501}

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```
##### Actual Results:

```
$ ansible-playbook -i hosts site.yml -v

PLAY [test] *******************************************************************

TASK: [role1 | copy file] *****************************************************
fatal: [localhost] => One or more undefined variables: 'item' is undefined

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/foobar/site.retry

localhost                  : ok=0    changed=0    unreachable=1    failed=0
```

**Comment by jimi-c** [comment]
I have a slightly different fix for this, to ensure that we don't re-break 7535 or anything else similar:

<pre>
diff --git a/lib/ansible/playbook/task.py b/lib/ansible/playbook/task.py
index bd9b0d0..3865349 100644
--- a/lib/ansible/playbook/task.py
+++ b/lib/ansible/playbook/task.py
@@ -257,6 +257,10 @@ class Task(object):
         # make first_available_file accessable to Runner code
         if self.first_available_file:
             self.module_vars['first_available_file'] = self.first_available_file
+            # make sure that the 'item' variable is set when using
+            # first_available_file (issue #8220)
+            if 'item' not in module_vars:
+                module_vars['item'] = ''
 
         if self.items_lookup_plugin is not None:
             self.module_vars['items_lookup_plugin'] = self.items_lookup_plugin
</pre>

If you can test that, I'll get it merged in.

**Comment by dragon3** [comment]
@jimi-c Thank you for your quick reply.

I tried to apply your patch to release1.6.6 branch, so I confirmed it works correctly.
:+1:

**Comment by tksmd** [comment]
@jimi-c and @dragon3 Great thanks, this patch worked well for me too.

BTW, it doesn't change the result but should we update self.module_vars instead of module_vars to clarify which variable to be updated ? 

```
            if 'item' not in self.module_vars:
                self.module_vars['item'] = ''
```

**Comment by jimi-c** [comment]
@tksmd yes you're correct, that was a typo on my part. I'll correct that before I merge it in.

**Comment by jimi-c** [comment]
Fixed and merged, thanks!

**Comment by dragon3** [comment]
Thanks!
