### ISSUE TITLE
Replacement patterns in _clean_data() cause invalid JSON for highly-nested data structures

### ISSUE THREAD

**Issue by dltj** [ansible/ansible#8228]
##### Issue Type:

Bug Report caused by [3761bc113295e20771544491d007f1d328f40b99] committed by @jimi-c
##### Ansible Version:

```
$ ansible --version
ansible 1.6.6
```
##### Environment:

Management host: MacOSX 10.9.4 with Python 2.7.8
Target host: Ubuntu 12.04.4 LTS with Python 2.7.3
##### Summary:

The regex replacement pattern at https://github.com/ansible/ansible/commit/3761bc113295e20771544491d007f1d328f40b99#diff-cea96e7ed2dad65a7b37c9b9daa86d62R320 will cause invalid JSON to be stored in playbook variables.  For instance, it is possible for JSON to contain `}}}` and this function will cause it to be replaced with `#}}`.
##### Steps To Reproduce:

The target host is running Drupal. A task runs the shell command `drush vget --format=json` resulting in this output that contains a highly nested data structure.  This can be simulated with this task:

```
- name: Simulate nested JSON structure
  shell: echo '{"php_storage":{"default":{"class":"Drupal\\Component\\PhpStorage\\FileReadOnlyStorage"}}}'
  register: sitesvars
  with_dict: sites
  changed_when: False
```

Running `debug var=sitesvars` as the next task shows the value of `stdout` as:

```
"stdout": "{\"php_storage\":{\"default\":{\"class\":\"Drupal\\Component\\PhpStorage\\FileReadOnlyStorage\"#}}"
```

Note how the end of the string has been changed. 
##### Expected Results:

The JSON in the variable to be unmodified.
##### Actual Results:

In a task that attempts to parse `stdout` -- for example `(item.stdout|from_json)` -- Ansible dies with this traceback:

```
fatal: [10.11.12.16] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible-1.6.6-py2.7.egg/ansible/runner/__init__.py", line 536, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/site-packages/ansible-1.6.6-py2.7.egg/ansible/runner/__init__.py", line 668, in _executor_internal
    complex_args=complex_args
  File "/usr/local/lib/python2.7/site-packages/ansible-1.6.6-py2.7.egg/ansible/runner/__init__.py", line 728, in _executor_internal_inner
    if not utils.check_conditional(cond, self.basedir, inject, fail_on_undefined=self.error_on_undefined_vars):
  File "/usr/local/lib/python2.7/site-packages/ansible-1.6.6-py2.7.egg/ansible/utils/__init__.py", line 222, in check_conditional
    conditional = template.template(basedir, presented, inject)
  File "/usr/local/lib/python2.7/site-packages/ansible-1.6.6-py2.7.egg/ansible/utils/template.py", line 113, in template
    varname = template_from_string(basedir, varname, vars, fail_on_undefined)
  File "/usr/local/lib/python2.7/site-packages/ansible-1.6.6-py2.7.egg/ansible/utils/template.py", line 333, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 10, in root
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid \escape: line 1 column 43 (char 42)
```

**Comment by mpdehaan** [comment]
Can you provide an example playbook that demonstrates this issue without needing a drush install?

**Comment by mpdehaan** [comment]
FYI, here's the easiest way to JSONify a datastructure.

assuming a foo defined in vars (or elsewhere) as YAML, such as:

foo: { x: y: [1,2,3,4] }

In your statement:

{{ foo | to_json }}

Much easier than trying to quote all that stuff, JSON is bad enough with quoting already :)

Also if you are doing shell echo, the copy/template module may be appropriate as well.

**Comment by dltj** [comment]
This playbook replicates the problem without drush but with the JSON encoded in a string:

```
- name: Demonstration of issue 8228
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Simulate nested JSON structure
    shell: echo '{"foo":{"bar":{"baz":"oops"}}}'
    register: examplevar
    changed_when: False

  - debug: var=examplevar

  - name: Cause stack trace
    shell: echo "Blah"
    when: "'foo' in (examplevar.stdout|from_json)"
```

I couldn't use `to_json` because it "pretty prints" the JSON into the variable (with newlines between the components of the JSON variable) so the `}}}` string doesn't occur.

**Comment by mpdehaan** [comment]
Good point, that.  

Seems like we'll want a non pretty version as well.

**Comment by mpdehaan** [comment]
We've applied various fixes on the development branch which are parsing related.  While I haven't had time to see the above concern, newlines are preserved much better in shell commands and the like and such now.

We have new integration test facilities in the test/integration/roles/test_good_parsing directory and we can also add this as a test to verify.

**Comment by dltj** [comment]
Thanks for looking into this.  I hope the problem isn't being misinterpreted.  The issue isn't that `to_json` is inserting newlines into variables.  The `}}}` string is a legitimate fragment in a variable full of JSON, so we need to avoid transforming it into something that isn't valid (as the modified code (https://github.com/ansible/ansible/commit/3761bc113295e20771544491d007f1d328f40b99#diff-cea96e7ed2dad65a7b37c9b9daa86d62R320) is doing).

**Comment by mpdehaan** [comment]
Thanks, I understand now.

There's an entirely new implementation of parsing on 1.6.9 now, but we'll still check this out.

**Comment by jimi-c** [comment]
I have merged in the above patch, which should resolve this issue. If you continue seeing any problems related to this issue, please let us know. Thanks!

**Comment by dltj** [comment]
Thanks, @jimi-c -- that patch fixed the problem both in the sample playbook in this issue and on our specific instance.
