### ISSUE TITLE
Feature Idea: Allow plays to use tags as defined in tasks

### ISSUE THREAD

**Issue by purduemike** [ansible/ansible#8231]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.6.6
##### Environment:

N/A
##### Summary:

The request here is to allow using a tag, as defined in a task, from a play. 
##### Steps To Reproduce:

I want to be able to create a playbook called start_all.yml which should look something like this:
- hosts: webservers
  use_tag: web_start
  roles:
  - { role: web }
- hosts: dbservers
  use_tag: db_start
  roles:
  - { role: db }

In this situation, I would only be using the tasks, within the web role, which are tagged with web_start.  Same goes for the db role, but only for tasks tagged with the db_start tag.
##### Expected Results:

The expected result, from the playbook above, is that we run the tasks that would start web and database servers.
##### Actual Results:

This would not work at the moment because the use_tag parameter in a play doesn't exist.
##### Additional Information:

This feature would allow you to:
    1) more efficiently reuse tasks
    2) not have to know the exact names of the tags you need to call at the command prompt.  Example: ansible-playbook -i staging_env deploy.yml --tags "web_start,db_start".  Remembering the correct tags to call a that command prompt can be difficult, especially if you're a member of Ops that doesn't use ansible all the time.

This is the one feature that is keeping me from rolling ansible out to the wider Ops team.

Here is a related question from google groups:
https://groups.google.com/forum/#!topic/ansible-project/sTDVuMtRPOg

Thank you!

**Comment by mpdehaan** [comment]
Discussed on the mailing list, we'd be open to pull requests though are unlikely to implement this one.

Code submissions would be welcome.
