### ISSUE TITLE
MS has extended the support for Windows Server 2012 R2 so the support in ansible should continue.

### ISSUE THREAD

**Issue by mhallin2** [ansible/ansible#82338]
### Summary

MS has extended the support for Windows Server 2012 R2
https://techcommunity.microsoft.com/t5/windows-it-pro-blog/windows-server-2012-r2-extended-security-updates/ba-p/3976610
into Oct 2026 so it support for the product needs to remain

### Issue Type

Bug Report

### Component Name

Ansible Core

### Ansible Version

```console
N/A
```

### Configuration

```console
No config changes are needed.
```

### OS / Environment

Windows Server 2012 R2

### Steps to Reproduce

Don't think this needs a reproduce step

### Expected Results

Support for Windows Server 2012 R2 remains until Ocr 2026

### Actual Results

```console
this not a code issue this is that the support needs to remain as it is
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by jborean93** [comment]
This is Extended Support which you have to pay for (or at least with Azure is included in their existing costs). We did not support Server 2008 and 2008 R2 during the same ESU phase which will be the same for Server 2012 and 2012 R2.
