### ISSUE TITLE
Add parameter `follow_redirects` to the list of `url_argument_spec`

### ISSUE THREAD

**Issue by monsdar** [ansible/ansible#82335]
### Summary

Modules from external collections like [`community.general.rundeck_project`](https://github.com/ansible-collections/community.general/blob/1b9d437be8d085b714f2c38208b30401e7dcf2d9/plugins/module_utils/rundeck.py#L21) use the [`module_utils.url_argument_spec`](https://github.com/ansible/ansible/blob/3a42a0036875c8cab6a62ab9ea67a365e1dd4781/lib/ansible/module_utils/urls.py#L1101) function to extend their parameters with the ones Ansible provides. They use the implementation behind [`ansible.builtin.uri`] so that makes sense.

This feature request is about adding the missing parameter [`follow_redirects`](https://github.com/ansible/ansible/blob/3a42a0036875c8cab6a62ab9ea67a365e1dd4781/lib/ansible/modules/uri.py#L611).

Adding this parameter would allow to use modules that build upon the ansible-uri implementation to follow redirects as well, e.g. when the service they're trying to reach is located behind a reverse proxy.

Reference:
* This forum post: https://forum.ansible.com/t/reuse-code-from-modules-in-other-collections/2699
* This issue: https://github.com/ansible-collections/community.general/issues/7670

### Issue Type

Feature Idea

### Component Name

uri

### Additional Information

-

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by Akasurde** [comment]
resolved_by_pr https://github.com/ansible/ansible/pull/84442
