### ISSUE TITLE
in 1.6.7 fail on copy of dir with owner field set

### ISSUE THREAD

**Issue by scottnonnenberg** [ansible/ansible#8247]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible 1.6.6 and Ansible 1.6.7
##### Environment:

OSX Maverics to Ubuntu 14.04
##### Summary:

If you do a copy of a directory with the owner field set, it will calculate the proper target location incorrectly (without the nested directory) and then give a 'file not found' error. It works when you get rid of the owner field.
##### Steps To Reproduce:

I'm using this task in a role:

``` yaml
- name: update nginx configuration - certs
  copy:
    src: '{{nginx_config_base}}/certs'
    dest: /etc/nginx/
    owner: www-data
    group: www-data
    mode: 0600
  when: certs.stat.exists
  notify: reload nginx
```
##### Expected Results:

Successful copy.
##### Actual Results:

I get this crash:

``` text
failed: [dload1] => {"failed": true, "md5sum": "REDACTED", "parsed": false}
invalid output was: 
SUDO-SUCCESS-asdfqewrwqersards
Traceback (most recent call last):
  File "/home/manager/.ansible/tmp/ansible-tmp-1406051845.21-124371332072741/file", line 1493, in <module>
    main()
  File "/home/manager/.ansible/tmp/ansible-tmp-1406051845.21-124371332072741/file", line 171, in main
    changed = module.set_fs_attributes_if_different(file_args, changed)
  File "/home/manager/.ansible/tmp/ansible-tmp-1406051845.21-124371332072741/file", line 784, in set_fs_attributes_if_different
    file_args['path'], file_args['owner'], changed
  File "/home/manager/.ansible/tmp/ansible-tmp-1406051845.21-124371332072741/file", line 697, in set_owner_if_different
    orig_uid, orig_gid = self.user_and_group(path)
  File "/home/manager/.ansible/tmp/ansible-tmp-1406051845.21-124371332072741/file", line 624, in user_and_group
    st = os.lstat(filename)
OSError: [Errno 2] No such file or directory: '/etc/nginx/blog_scottnonnenberg.pem'
```

**Comment by mpdehaan** [comment]
The changes in 1.6.7 are really only related to argument parsing so I'm a bit skeptical this occured 1.6.6 to 1.6.7, but we'll investigate what this bug might be.

**Comment by nathanhruby** [comment]
Unsure where in the stream this bug was introduced, but happening for me with 1.6.8 now.  My last upgrade was 1.6.6 -> 1.6.8 on the 23rd and as far as I can tell I didn't experience this in 1.6.6

**Comment by nathanhruby** [comment]
Possibly related: #8271

**Comment by jimi-c** [comment]
I believe this is the same issue as #8271, as noted above. Please test with the latest 1.6.10, which does now include this fix.

**Comment by scottnonnenberg** [comment]
Yep! This works in 1.6.10 and doesn't work in 1.6.9. Thanks, guys!

**Comment by scottnonnenberg** [comment]
By the way, I can switch versions really easily because I'm just checking my git repo out to various tags. :0)
