### ISSUE TITLE
make file module more explicitly explicit with respect to recursion

### ISSUE THREAD

**Issue by biffhero** [ansible/ansible#825]
With this as the action...

```
  action: file path=/usr/ssn owner=ssn group=ssn state=directory
```

And with the user "ssn" already on the host, the entire /usr/ssn/\* tree was set to user ssn, group ssn.  There were directories there which were root.root which had to be restored.  The expected behavior was that only /usr/ssn/ would be set to ssn.ssn.  I suppose there might be an assumption going on here, where the "chown -R" makes sense in some cases, and not in others.  I think this should be optional.

Thanks for a great module, it's way better than doing a system call.

Rob

**Comment by mpdehaan** [comment]
recurse=yes|no seems useful, though change detection for changed=True/False would be hard in this case.

I'd be ok with not seeing anything recurse and the command module being needed for that if someone really wants to execute a -R

**Comment by mpdehaan** [comment]
closing per above
