### ISSUE TITLE
rax_scaling_group cannot find image by name, throws error

### ISSUE THREAD

**Issue by guymatz** [ansible/ansible#8250]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel 75e5b6401c) last updated 2014/07/22 17:30:15 (GMT -400)
##### Environment:

Ubuntu 14.04
##### Summary:

rax_scaling_group does not behave properly when an image name is used.  Works fine when an image ID is used
##### Steps To Reproduce:

attempt to create a rackspace auto_scaling_group with an image name, e.g.:
local_action:
        module: rax_scaling_group
        image: "{{ item.value.image|default('CentOS 6.5') }}"
##### Expected Results:

Autoscaling group created with the specificed image
##### Actual Results:

NameError: global name 'cs' is not defined

Line 181 of rax_scaling_group references a variable, cs, which is not previously created

**Comment by sivel** [comment]
Thanks for the report. I'll look into this within the next 7 days.
