### ISSUE TITLE
unarchive (and others?) broken when called in K=V mode

### ISSUE THREAD

**Issue by matthewbsimon** [ansible/ansible#8254]
##### Ansible Version: 1.6.8+

ansible 1.6.8
ansible 1.7 (devel d2a130971a) last updated 2014/07/22 20:11:41 (GMT -400)
##### Environment:

OSX 10.9.3
RHEL 6.5
##### Summary:

As of 1.6.8 and later, the unarchive module fails with the erroneous error "msg: duplicate parameter: src" when the parameters are specified in k=v format
I looked into this a little, and it seems to me that both the original src argument(app.tgz) and the transformed  src argument (/Users/matthewbsimon/.ansible/tmp/ansible-tmp-1406078247.21-209950653970379/source) flow into module_utils/basic.py _load_params, and then the newly introduced security fix catches it. I don't know enough to fix this  - please help!
## file: example.yml
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - shell: "touch app.tgz"
  - unarchive: src=app.tgz dest=/tmp

bash$ ansible-playbook -i 'localhost,' example.yml 
##### Actual Results:

failed: [localhost] => {"failed": true}
msg: duplicate parameter: src (value=/Users/matthewbsimon/.ansible/tmp/ansible-tmp-1406127477.01-217277799953399/source)

FATAL: all hosts have already failed -- aborting

**Comment by mpdehaan** [comment]
Fix merged into the development branch just now.   Should we do a 1.6.9 to pull in some more fixes - which is expected - this will also be included.

Workaround would be to run from development for the short term or apply https://github.com/ansible/ansible/commit/f9f37a507053f97968d0f69fdc588eec639291fb

**Comment by mpdehaan** [comment]
cc @jimi-c

**Comment by wimvanleuven** [comment]
Just applied this fix on my ansible installation until the fix rolls in via apt.
