### ISSUE TITLE
unarchive broken in 1.6.8 and later

### ISSUE THREAD

**Issue by frikkelfuzz** [ansible/ansible#8257]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.8
##### Environment:

debian wheezy
##### Summary:

unarchive fails with "duplicate parameter src"
##### Steps To Reproduce:

ansible wheezy1 -m unarchive -a "src=roles/tomcat/files/tomcat7-pocket.tar dest=/var/lib"
##### Expected Results:

success
##### Actual Results:

wheezy1 | FAILED >> {
    "failed": true, 
    "msg": "duplicate parameter: src (value=/root/.ansible/tmp/ansible-tmp-1406098204.14-81045059317860/source)"
}

**Comment by mpdehaan** [comment]
This is already fixed on the development branch.  It only breaks in certain modes, and this fix will be applied in a future 1.6.9 likely out today.

See commit in #8263 which is applied.
