### ISSUE TITLE
dnf allowerasing does not work if updating all the packages

### ISSUE THREAD

**Issue by flo-renaud** [ansible/ansible#82616]
### Summary

I am using the dnf module with allowerasing:true to update all my packages (name: '*') but the option allowerasing is not taken into account.
If a single package name is specified (name: dogtag-pki-server), allowerasing is properly enforced.

### Issue Type

Bug Report

### Component Name

dnf

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.1 (main, Dec 18 2023, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
EDITOR(env: EDITOR) = /usr/bin/vim
```

### OS / Environment

# cat /etc/redhat-release 
Fedora release 39 (Thirty Nine)

### Steps to Reproduce

This can be demonstrated using the package dogtag-pki-base with the following playbook:
```
# cat playbook.yml 
---
- name: "Demonstrate ansible dnf issue"
  hosts: localhost
  connection: local
  tasks:
  - name: "install freeipa server"
    dnf:
      name: "freeipa-server"
      state: latest
  - name: "configure custom COPR repo (@pki/master)"
    shell: "dnf copr enable -y @pki/master"
  - name: check pki version before upgrade all
    shell: "dnf list installed dogtag-pki-base"
    register: pkg_before
  - debug:
      var: pkg_before.stdout_lines
  - name: update all packages with allowerasing
    dnf:
      name: '*'
      state: latest
      allowerasing: true
  - name: check pki version after upgrade all
    shell: "dnf list installed dogtag-pki-base"
    register: pkg_after
  - debug:
      var: pkg_after.stdout_lines
  - name: update pki packages with allowerasing
    dnf:
      name: 'pki-server'
      state: latest
      allowerasing: true
  - name: check pki version after upgrade pki
    shell: "dnf list installed dogtag-pki-base"
    register: pkg_after_pki
  - debug:
      var: pkg_after_pki.stdout_lines
```

The output is the following and shows that dnf udpate all with allowerasing does not upgrade the dogtag-pki-base package, while dnf upgrade dogtag-pki-base works as expected.
```
# ansible-playbook playbook.yml
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [Demonstrate ansible dnf issue] *******************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [install freeipa server] **************************************************
changed: [localhost]

TASK [configure custom COPR repo (@pki/master)] ********************************
changed: [localhost]

TASK [check pki version before upgrade all] ************************************
changed: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "pkg_before.stdout_lines": [
        "Installed Packages",
        "dogtag-pki-base.noarch                  11.4.3-2.fc39.1                  @fedora"
    ]
}

TASK [update all packages with allowerasing] ***********************************
changed: [localhost]

TASK [check pki version after upgrade all] *************************************
changed: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "pkg_after.stdout_lines": [
        "Installed Packages",
        "dogtag-pki-base.noarch                  11.4.3-2.fc39.1                  @fedora"
    ]
}

TASK [update pki packages with allowerasing] ***********************************
changed: [localhost]

TASK [check pki version after upgrade pki] *************************************
changed: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "pkg_after_pki.stdout_lines": [
        "Installed Packages",
        "dogtag-pki-base.noarch 11.5.0-0.2.alpha5.20240125160718UTC.2268461f.fc39 @copr:copr.fedorainfracloud.org:group_pki:master"
    ]
}

PLAY RECAP *********************************************************************
localhost                  : ok=11   changed=7    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```

### Expected Results

I would expect this command to update the dogtag-pki-base package:
  - name: update all packages with allowerasing
    dnf:
      name: '*'
      state: latest
      allowerasing: true

### Actual Results

```console
The package is not updated
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mkrizek** [comment]
I was really confused by this bug report until I saw https://github.com/freeipa/freeipa-pr-ci/pull/499 where the need for `--best` option is mentioned.

The issue here appears to stem from the fact that:
1. `nobest` option does not affect the `best` config value unless it is set to `true` [0]. In other words, if you do not set the `nobest` option to `true` then the default value that the [distribution](https://dnf.readthedocs.io/en/latest/conf_ref.html#conf-distribution-specific-label) sets is used, which is `best=false` for Fedora 39 - and that is why your package is not updated.
2. the `dnf` module does not implement the `best` option that could be used to overwrite the distribution default value.

I believe the fix here would be to introduce the `best` option and set the default value for both `best` and `nobest` (for this it might be a breaking change) to "unset" and leave the default for whatever the distribution default value is.

Also, there is no `nobest` option for `dnf5`, so `best` should be added there as well, and leaving `nobest` for backwards compatibility and feature parity with `dnf`.

[0]
https://github.com/ansible/ansible/blob/7a0c321054bf3f9c238f09a8c29f140b255112c1/lib/ansible/modules/dnf.py#L682-L683
