### ISSUE TITLE
Regression: ansible-doc no longer shows attributes for roles

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansible#82639]
### Summary

This was removed as part of https://github.com/ansible/ansible/commit/bec27fb4c0a40c5f8bbcf26a475704227d65ee73#diff-9732216f79978750789dbeb4c2ed1280d841c4211306ecb1b5c70e3db3fcb2f7L1198.

I guess this was a mistake.

### Issue Type

Bug Report

### Component Name

ansible-doc

### Ansible Version

```console
latest devel
```

### Configuration

```console
-
```

### OS / Environment

-

### Steps to Reproduce

-

### Expected Results

-

### Actual Results

```console
-
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by bcoca** [comment]
I thought that was a typo, how are attributes being used in roles?

**Comment by felixfontein** [comment]
I guess the same as for plugins and modules: to show properties of roles. You could for example have a property `idempotent` for a collection of roles which indicates which of the roles are idempotent and which aren't.

I haven't used it personally in roles yet, but I remember that someone complained that antsibull-docs isn't accepting attributes while ansible-doc does.

The code for showing attributes in roles also have been around since ansible-core 2.14.

**Comment by bcoca** [comment]
I know the code was there, but i had assumed it was a mistake since we have not created any type of attributes for roles nor had ever intended the facility to extend to them. 

If they are actually in use I would like to see the cases and then discuss if we actually want this at the 'role spec' level, which is different from role level.

**Comment by mkrizek** [comment]
During the core triage meeting it was discussed that adding `attributes` was a mistake in the first place and we have no plans on adding it back.

Closing as per https://github.com/ansible/ansible/pull/81796, continuing the discussion there.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.libera.chat
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by felixfontein** [comment]
Seriously, this is a huge mistake.
