### ISSUE TITLE
lineinfile module changes owner of file

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#8268]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.6
##### Environment:

Ubuntu 14.04 -> Centos 5
##### Summary:

If you use the `lineinfile` module to edit a file and if the file belongs to a different user than the user running Ansible, `lineinfile` will change the owner of the file to the user running Ansible, but it would leave the permissions untouched.
##### Steps To Reproduce:

Create a file with none default permissions, e.g. `600` and set the owner to some user (e.g. `nginx`). Run Ansible as `root` to edit that file with the `lineinfile` module. 
##### Expected Results:

It would be expected that all the permissions and ownership stay the same, and it only edits the file.
##### Actual Results:

The file will be edited, permissions will stay the same (600), but the new owner of the file will be `root`.

**Comment by mpdehaan** [comment]
cc @bcoca, atomic move is your baby, thoughts?

**Comment by kustodian** [comment]
This could cause a lot of problems if you are editing files with restricted permissions which make it possible for the file to only be readable by the owner. I almost put some Postgres databases offline because of this, because `pg_ident.conf` has 600 and is owned by `postgres`, but after the replacement of text, the owner became `root` and when I restated Postgres, it reported that it doesn't have permissions so it started rejecting connections which use pg_ident.conf.

**Comment by bcoca** [comment]
I'll look into it, it seems some recent update changed the old behavior of
copying the existing permissions/ownership onto the new file.​

**Comment by bcoca** [comment]
I have not been able to reproduce this:

```
ls -l /var/tmp/text.txt
-rw-------  1 bcoca bcoca      6 Jul 26 10:13 test.txt
```

play:

```
- hosts: localhost
  connection: local
  tasks:
    - lineinfile: dest=/var/tmp/test.txt regexp="^test" line='test'
state=present
```

ran as root, then
​```
ls -l /var/tmp/text.txt
-rw-------  1 bcoca bcoca      11 Jul 26 10:14 test.txt

```
```

**Comment by kustodian** [comment]
I ran the module with the ansible command, not using a playbook.

**Comment by bcoca** [comment]
that should make no difference, I ran it anyways, cannot reproduce the
problem​

**Comment by kustodian** [comment]
I'll try it out later on and give you the steps. What I did though is that I removed a line from /var/lib/pgsql/9.1/data/pg_ident.conf which has a mode 600 and was owned by postgres:postgres. Also the pgsql directory has a 700 and it belongs to  postgres:postgres and that directory is a separate file system (it's on a separate partition), maybe that could be a problem? I ran everything as root, as you did in your test.

**Comment by kustodian** [comment]
I can't reproduce it now myself either.

Only thing I have as a proof it had happened is this log in postgres:

```
2014-07-21 15:00:23 CEST [18508]: [10-1] LOG:  could not open usermap file "/var/lib/pgsql/9.1/data/pg_ident.conf": Permission denied
```

I'm closing this until I find a repro for it.
