### ISSUE TITLE
yum module can't do list

### ISSUE THREAD

**Issue by biffhero** [ansible/ansible#827]
This command

ansible-playbook -e"hl=nagios-server pkg=nagios " /etc/ansible/playbooks/yum/setup.yml

with this task line

```
- name: yum_command      # action: yum name=${pkg} list=available
  action: yum list=${pkg}
```

returned this error

failed: [contactvm2] => {"failed": true, "item": "", "module": "yum", "msg": "value of list must be one of: installed,updates,available,repos,pkgspec, got: nagios"}

**Comment by mpdehaan** [comment]
should be fixed by https://github.com/ansible/ansible/pull/826 .. let me know if not
