### ISSUE TITLE
Doc: Add fstype arg to the mount examples

### ISSUE THREAD

**Issue by ps-jay** [ansible/ansible#8274]
##### Issue Type:

Docs Pull Request
##### Ansible Version:

ansible 1.6.7
##### Environment:

N/A
##### Summary:

fstype is a required arg in the mount module, the documentation examples should reflect that.
Pull request: https://github.com/ansible/ansible/pull/8273
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
This is not a docs pull request, so I'm closing this one.

Also the original pull request ticket is enough, don't need a ticket referencing the pull request as this just makes the ticket system more busy :)

Thanks!
