### ISSUE TITLE
Pipe stdout from containers created by docker module

### ISSUE THREAD

**Issue by rightaway** [ansible/ansible#8280]
##### Issue Type:

Feature request
##### Ansible Version:

1.6.3
##### Environment:

Ubuntu 14.04
##### Summary:

If I start several containers using docker module (use ansible to put them into running state), I can't pipe the stdout anywhere. For this I would have to use a shell command, to do something like `docker run ... | logger`, but using a shell command removes the advantages and declarative convenience of using the docker module.

It would be nice to have some option to the docker module that would specify where the output of the logs could be piped to, or a fifo named pipe.

This allows for getting the logs directly from stdout from the docker containers onto a single process like 'logger' on the host and then possibly sending them over the network, so that no logs are stored to disk, saving disk writes.
##### Steps To Reproduce:

Run a docker container with docker module.
##### Expected Results:

Should be able to specify where the stdout of that container gets piped to, a program like 'logger', or a file like '/my/named/pipe'. This way the syslog or anything on the host can listen on /my/named/pipe and do what it wants with the logs, potentially not writing a log to disk anywhere on the host machine.
##### Actual Results:

Logs can't be forwarded without writing to disk.

**Comment by mpdehaan** [comment]
The shell command can entirely do pipes.

If you have a module, the mechanism for saving data is the register command.

I don't really see this being an option for an ansible module because it would be, well, a bit weird, especially if Docker specific, but I'm open to more discussions.

Stop by ansible-project to share with the wider group, perhaps?

**Comment by kovacshuni** [comment]
@rightaway i understand you.
Any tips on this since then? Still the shell command?
