### ISSUE TITLE
Not providing optional arg "vg_options" to lvg module causes traceback

### ISSUE THREAD

**Issue by ps-jay** [ansible/ansible#8285]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.7
##### Environment:

Red Hat Enterprise Linux Server release 6.5 (Santiago)
##### Summary:

When using the lvg module, if vg_options is not provided then Ansible will crash with a traceback.
##### Steps To Reproduce:

Play:

```
- name: Create the data LVM VG
  lvg: vg=data pvs=/dev/xvda2 pesize=32
```

Traceback:

```
TASK: [partitioning | Create the data LVM VG] *********************************
failed: [testwebpost21] => {"failed": true, "parsed": false}
invalid output was: SUDO-SUCCESS-ieypxlylttyivekkfyplwlhjtktktnub
Traceback (most recent call last):
  File "/home/ec2-user/.ansible/tmp/ansible-tmp-1406270471.12-134934980308379/lvg", line 1460, in <module>
    main()
  File "/home/ec2-user/.ansible/tmp/ansible-tmp-1406270471.12-134934980308379/lvg", line 119, in main
    vgoptions = module.params.get('vg_options', '').split()
AttributeError: 'NoneType' object has no attribute 'split'
```
##### Expected Results:

I expect this play to work.
I expect not to have to provide the vg_options arg, since it is documented as optional (and appears to be optional in the source code too)
##### Actual Results:

Ansible crashes with a traceback - as above in the "Steps To Reproduce" section.
##### Known workaround:

Provide vg_options as an empty string, for example:

```
- name: Create the data LVM VG
  lvg: vg=data pvs=/dev/xvda2 pesize=32 vg_options=""
```

**Comment by srgvg** [comment]
I believe this problem was fixed in the devel tree (upcoming 1.7)

**Comment by mpdehaan** [comment]
Can you please check on the 1.7 branch and let us know if this fixes it for you?

you can do a git checkout and "source ./hacking/env-setup" to try it from there.

Thanks!

**Comment by ps-jay** [comment]
Sure, will do.

**Comment by ps-jay** [comment]
Confirmed fixed in the devel branch.

```
> ansible --version
ansible 1.7 (devel d51e10a3f4) last updated 2014/07/28 04:13:38 (GMT +000)
```

**Comment by ps-jay** [comment]
Apologies for the duplication of https://github.com/ansible/ansible/pull/6859
