### ISSUE TITLE
Parse error when using spaces in parameterized include

### ISSUE THREAD

**Issue by wrosario** [ansible/ansible#8296]
##### Issue Type:

 “Bug Report”
##### Ansible Version:

1.7
##### Environment:

Centos 6.5 
##### Summary:

Using spaces in parameterized include will cause a parsing error.
##### Steps To Reproduce:

Here is the step to reproduce

```
# ============================================================
# create mysql user and verify user is added to the mysql database
#
- name: create mysql user state=present (expect changed=true)
  mysql_user: name={{ user_name_1 }} password={{ user_password_1 }} state=present
  register: result

- include: assert_user.yml user_name={{ user_name_1 }} state=present changed=true 
```
##### Expected Results:

Able to run task when using spaces in parameterized include.
##### Actual Results:

Output code when trying to run task above:

```
[root@vm2 integration]# vi roles/test_mysql_user/tasks/main.yml 
[root@vm2 integration]# ansible-playbook destructive.yml -i inventory -e @integration_config.yml -v --tags "test_mysql_user"
Traceback (most recent call last):
  File "/root/z/ansible/bin/ansible-playbook", line 309, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/root/z/ansible/bin/ansible-playbook", line 249, in main
    pb.run()
  File "/root/z/ansible/lib/ansible/playbook/__init__.py", line 293, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/root/z/ansible/lib/ansible/playbook/play.py", line 152, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/root/z/ansible/lib/ansible/playbook/play.py", line 587, in _load_tasks
    loaded = self._load_tasks(data, mv, default_vars, included_sudo_vars, list(included_additional_conditions), original_file=include_filename, role_name=new_role)
  File "/root/z/ansible/lib/ansible/playbook/play.py", line 575, in _load_tasks
    (k,v) = t.split("=", 1)
ValueError: need more than 1 value to unpack

```

**Comment by vjanelle** [comment]
Seeing the same thing here, with roughly the same usage.

**Comment by vjanelle** [comment]
Downgrading to 1.6.8 makes everything work again.

**Comment by mpdehaan** [comment]
You won't need to downgrade (nor do you want to, given other parser fixes on 1.6.9/10), just go ahead and remove the spaces inside the {{ .. }}

Regardless, we'll fix this on devel very soon.

**Comment by jimi-c** [comment]
I have merged in the above patch, which should resolve this issue. Please let us know if you continue to see any problems related to this issue. Thanks!

**Comment by rafecolton** [comment]
Any idea when this is slated for release?  If not soon, could it perhaps be released as a patch?

Thanks!

**Comment by jimi-c** [comment]
@rafecolton we're looking at releasing 1.7 in the next couple of weeks. Until then, you should be able to get around this simply be removing any spaces in between the `{{` and `}}`.

If you really want to use this patch, you can  apply it manually. You'll also want to grab 6e814566de36558a52bcb19ab4231e572cf5a63b as well, as there is another bug related to this fixed there.

**Comment by rafecolton** [comment]
@jimi-c will do, thanks!

**Comment by Athena88-zz** [comment]
got this ERROR: Invalid ini entry: ayosditoticket.com - need more than 1 value to unpack
xxxxxxx:ansible-playbooks xxxxxxx$ export ANSIBLE_HOST_KEY_CHECKING=False
xxxxxxxx:ansible-playbooks xxxxxxx$ ansible all -m ping -u root
ERROR: Invalid ini entry: ayosditoticket.com - need more than 1 value to unpack

i'm v 1.7

**Comment by jimi-c** [comment]
@Athena88 that error is unrelated to this issue, however it is most likely because you have something in your list of inventory vars in your INI which is not in the form `key=value`. Please take any further questions to the mailing lists:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
