### ISSUE TITLE
keystone_user documentation lists invalid option

### ISSUE THREAD

**Issue by ericwb** [ansible/ansible#8299]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.3
##### Environment:

Ubuntu 12.04.4
##### Summary:

The keystone_user documentation on the ansible website lists "description" as an option.  It should be "tenant_description" after looking at the code on git.
##### Steps To Reproduce:

Just try to use the keystone_user module with description.
##### Expected Results:

I'd expect description to work.
##### Actual Results:

Ansible run fails with:

failed: [controller01] => {"failed": true}
msg: unsupported parameter for module: description

**Comment by mpdehaan** [comment]
Something you would like to submit a pull request for?

(Not required, just asking, because you've already been through the code in git...  it's the DOCUMENTATION block in that file that needs to change, so it's pretty straightforward)

Thanks!

**Comment by ericwb** [comment]
Sure, I'll submit a patch.
