### ISSUE TITLE
copy and template modules should produce English exceptions when arguments are not supplied

### ISSUE THREAD

**Issue by ggeldenhuis** [ansible/ansible#83]
I don't think this would be easily changable but I am reporting it anyway:

this line in a playbook is wrong:
    action: copy /root/conf/sysctl.conf /etc/sysctl.conf

but the error message is:

TASK: [Configure Sysctl.conf] *********

unreachable: [auth01.example.com] => Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/runner.py", line 497, in _executor
    return self._executor_internal(host)
  File "/usr/lib/python2.6/site-packages/ansible/runner.py", line 520, in _executor_internal
    result = self._execute_copy(conn, host, tmp)
  File "/usr/lib/python2.6/site-packages/ansible/runner.py", line 421, in _execute_copy
    source = options['src']
KeyError: 'src'

it should tell me there is a syntax error and not that the server is unreachable. 

Maybe a pre-flight syntax check abbility would be usefull/handy... but maybe a bit unfair to ask for so early in the projects life.

**Comment by mpdehaan** [comment]
agreed

**Comment by mpdehaan** [comment]
Implemented in latest git for the copy, template, and also the new 'fetch' module.
