### ISSUE TITLE
Cannot specify two different ports to the same host in inventory

### ISSUE THREAD

**Issue by pieterbreed** [ansible/ansible#8306]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.8
##### Environment:

ubuntu 14.04 for both controller and destination
##### Summary:

When the inventory file contains the same host, but with two different ports, it looks like only the latest port is used for all connections to that host. (This is bad when you're exposing different VMs on separate ports)
##### Steps To Reproduce:

We are running two distinct virtual machines on the same host and we are trying to connect via different ports. This is what the inventory looks like: 

```
[jenkins]
pieterbr1-w7.gray.net ansible_ssh_port=2200 

[jenkins-linux-slaves]
pieterbr1-w7.gray.net ansible_ssh_port=2201 
```

When we specify a playbook to run against `jenkins` it will try and connect to port `2201` instead of `2200`
##### Expected Results:

We expect a playbook running against hosts `jenkins` to correct to `pieterbr1-w7.gray.net:2200`
##### Actual Results:

The connections are made against `pieterbr1-w7.gray.net:2201` instead

**Comment by jimi-c** [comment]
This is expected behavior, you must specify a different hostname for each host in inventory. Instead of doing it this way, you should give each VM a different name in your host inventory and use the ansible_ssh_host=127.0.0.1 (or whatever IP you want to use) option as well as the port. If you have any further questions regarding this, please use the ansible-project group/mailing list. Thanks!

**Comment by sgnn7** [comment]
@jimi-c I'm having problems with this too and I think that the expected behavior here is wrong. What if you want the same script to try multiple ports for the connection (this is my use case) since you don't know what state of configuration they're in?

Ex:

```
[some_group]
user@foo.com:5555 #not configured
user@foo.com:1234 #port changed
```

If you want minimal configuration on clean VMs, this is a very real use case and with current code*, this is not possible. Per your comment though I don't see why this functionality addition is something that shouldn't be added since different user for the same host "hashes" to a different connection - adding the port in the hash shouldn't be a big deal.

Some more cases:

```
user1@foo.com # working
user2@foo.com # working
user1@foo.com:1234 # not working
user2@foo.com:1234 # not working
```

Edit: *- it's not that ti's not possible to do but the inventory becomes real messy.

**Comment by uptownhr** [comment]
i also disagree that this should be the expected behavior... I know it's possible to give fake hostnames but there are many services and servers that are bound to the same host through different ports. Why not support this case?

**Comment by millerf** [comment]
I have the same problem. I am using a reverse ssh connection from my many servers onto one single server for managment purposes and I am running the ansible script form the server (as I can't do the double connection from my machine). So I am a bit at a loss there... My only solution is to add many loops in the hosts file ...

**Comment by millerf** [comment]
Nevermind. I found a very nice workaround. Testing it now.

http://stackoverflow.com/questions/26527458/ansible-multiple-hosts-with-port-forwarding

**Comment by YumaInaura** [comment]
I think one resolution is change ssh config on control machine.
And fix inventory.

```
Host graynetfirst
  HostName pieterbr1-w7.gray.net
  Port 2200 

Host graynetsecond
  HostName pieterbr1-w7.gray.net
  Port 2201
```

```
[jenkins]
graynetfirst

[jenkins-linux-slaves]
graynetsecond
```

**Comment by bcoca** [comment]
This is what jimi-c was reffering to:
```
[jenkins]
graynetfirst ansible_host=pieterbr1-w7.gray.net ansible_port:2200

[jenkins-linux-slaves]
graynetsecond ansible_host=pieterbr1-w7.gray.net ansible_port:2201
```

**Comment by bcoca** [comment]
This is what jimi-c was reffering to:
```
[jenkins]
graynetfirst ansible_host=pieterbr1-w7.gray.net ansible_port:2200

[jenkins-linux-slaves]
graynetsecond ansible_host=pieterbr1-w7.gray.net ansible_port:2201
```

**Comment by bcoca** [comment]
This is what jimi-c was reffering to:
```
[jenkins]
graynetfirst ansible_host=pieterbr1-w7.gray.net ansible_port:2200

[jenkins-linux-slaves]
graynetsecond ansible_host=pieterbr1-w7.gray.net ansible_port:2201
```

**Comment by bcoca** [comment]
This is what jimi-c was reffering to:
```
[jenkins]
graynetfirst ansible_host=pieterbr1-w7.gray.net ansible_port:2200

[jenkins-linux-slaves]
graynetsecond ansible_host=pieterbr1-w7.gray.net ansible_port:2201
```

**Comment by bcoca** [comment]
This is what jimi-c was reffering to:
```
[jenkins]
graynetfirst ansible_host=pieterbr1-w7.gray.net ansible_port:2200

[jenkins-linux-slaves]
graynetsecond ansible_host=pieterbr1-w7.gray.net ansible_port:2201
```

**Comment by bcoca** [comment]
This is what jimi-c was reffering to:
```
[jenkins]
graynetfirst ansible_host=pieterbr1-w7.gray.net ansible_port:2200

[jenkins-linux-slaves]
graynetsecond ansible_host=pieterbr1-w7.gray.net ansible_port:2201
```

**Comment by bcoca** [comment]
This is what jimi-c was reffering to:
```
[jenkins]
graynetfirst ansible_host=pieterbr1-w7.gray.net ansible_port:2200

[jenkins-linux-slaves]
graynetsecond ansible_host=pieterbr1-w7.gray.net ansible_port:2201
```

**Comment by bcoca** [comment]
This is what jimi-c was reffering to:
```
[jenkins]
graynetfirst ansible_host=pieterbr1-w7.gray.net ansible_port:2200

[jenkins-linux-slaves]
graynetsecond ansible_host=pieterbr1-w7.gray.net ansible_port:2201
```

**Comment by bcoca** [comment]
This is what jimi-c was reffering to:
```
[jenkins]
graynetfirst ansible_host=pieterbr1-w7.gray.net ansible_port:2200

[jenkins-linux-slaves]
graynetsecond ansible_host=pieterbr1-w7.gray.net ansible_port:2201
```

**Comment by bcoca** [comment]
This is what jimi-c was reffering to:
```
[jenkins]
graynetfirst ansible_host=pieterbr1-w7.gray.net ansible_port:2200

[jenkins-linux-slaves]
graynetsecond ansible_host=pieterbr1-w7.gray.net ansible_port:2201
```

**Comment by bcoca** [comment]
This is what jimi-c was reffering to:
```
[jenkins]
graynetfirst ansible_host=pieterbr1-w7.gray.net ansible_port:2200

[jenkins-linux-slaves]
graynetsecond ansible_host=pieterbr1-w7.gray.net ansible_port:2201
```
