### ISSUE TITLE
task timeout failure should indicate timeout for programatic use

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#83158]
### Summary

When using the `timeout` keyword, when a task fails due to timeout, we should provide a `timeout` or similar key in the task result.  Right now it is just `failed=True, msg=msg`.

AAPRFE-1208

### Issue Type

Feature Idea

### Component Name

lib/ansible/executor/task_executor.py

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by bcoca** [comment]
This is the msg
```
 msg = 'The %s action failed to execute in the expected time frame (%d) and was terminated' % (self._task.action, self._task.timeout)
```
Not sure what else is needed? a traceback? the time taken?

**Comment by sivel** [comment]
Instead of inspecting the msg, we should just add a new `timeout=True` or similar to the response. 

The original ask was a new callback event, but we instead said we could just add a new key that can be inspected by the current callback events.
