### ISSUE TITLE
Duplication in error message

### ISSUE THREAD

**Issue by jnojr** [ansible/ansible#8319]
##### Actual Results: Duplicate info in error message:

ERROR: Syntax Error while loading YAML script, roundcube.yml
Note: The error may actually appear before this position: line 129, column 28

```
command: /usr/sbin/setsebool -P httpd_can_network_connect_db 1
when: "{{rc_db_host}}" == "localhost"
                       ^
```

We could be wrong, but this one looks like it might be an issue with 
unbalanced quotes.  If starting a value with a quote, make sure the 
line ends with the same set of quotes.  For instance this arbitrary 
example:

```
foo: "bad" "wolf"
```

Could be written as:

```
foo: '"bad" "wolf"'
```

We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they 
start a value. For instance:            

```
with_items:
  - {{ foo }}
```

Should be written as:

```
with_items:
  - "{{ foo }}"      
```

We could be wrong, but this one looks like it might be an issue with 
unbalanced quotes.  If starting a value with a quote, make sure the 
line ends with the same set of quotes.  For instance this arbitrary 
example:

```
foo: "bad" "wolf"
```

Could be written as:

```
foo: '"bad" "wolf"'
```

**Comment by mpdehaan** [comment]
So we'll look into the duplicate message but here's how to write your conditional:

```
when: "{{rc_db_host}}" == "localhost"
```

Should be:

```
when: "rc_db_host == 'localhost'"
```

**Comment by mpdehaan** [comment]
These above messages are about different instances of the same thing, not the same text.

Your "with_items" if foo is actually a list can be further shortened:

"with_items: foo"

In either case, ansible is trying to help with YAML syntax errors, prior to parsing, and you have two of them.

For further questions and/or help, please stop by the ansible-project mailing list or IRC and we'd be glad to answer questions.

Thanks!
