### ISSUE TITLE
Ansible-pull fails if inventory has not been downloaded

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#8324]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel aee940aaca) last updated 2014/07/29 12:05:46 (GMT +1000)
##### Environment:

N/A
##### Summary:

ansible-pull does not work if the inventory has not yet been downloaded. 
##### Steps To Reproduce:

You want to run ansible-pull to download a remote repository and then run a playbook using inventory in that playbook

```
ansible-pull -d /var/tmp/ansible-playbooks -i /var/tmp/ansible-playbooks/inventory/hosts -U http://git.internal/ansible-playbooks -m git path/to/playbook.yml
```
##### Expected Results:

A successful ansible-pull run
##### Actual Results:

Starting ansible-pull at 2014-07-29 12:09:48
ERROR: Unable to find an inventory file, specify one with -i ?

**Comment by willthames** [comment]
Reversing bb1941a906e3 resolves this issue - it would be good to have a solution to this that solves this problem and the python interpreter problem referenced in that commit. Perhaps @alexclear could help with this.

**Comment by mpdehaan** [comment]
This behavior (using -i settings) seems quite desirable to me and not a bug.

If you'd like to discuss, please stop by ansible-devel.

I'm not sure what you mean about the python-interpreter question.

**Comment by willthames** [comment]
You're misreading the bug report.

You're quite correct, the -i behaviour is desirable and no longer working.

It was broken by the referenced commit related to python interpreter - I
don't understand the intent but it broke Ansible pull behaviour that had
been working for a year.

**Comment by apicht** [comment]
I was relying on the ability to reference an inventory file contained in the git repo that ansible-pull is checking out. This worked on 1.6.10 and broke after upgrading to 1.7.1. My workaround is to wget the inventory file from github using a static link. Not quite as nice.

**Comment by gvenka008c** [comment]
I am passing my inventory (static + dynamic info) using the -i option as shown below.

ansible-pull -U git@github.com:XPlat/caps-sps.git -d /home/gvenka008c/caps-sps --key-file=/home/gvenka008c/.ssh/gvenka008c /home/gvenka008c/caps-sps/jenkins_mesos/ansible/jenkins_mesos_icinga.yml -i /home/gvenka008c/caps-sps/jenkins_mesos/ansible/inventory -vvvv

But I am seeing the below output. Any thoughts?

Loaded callback default of type stdout, v2.0
3 plays in /home/gvenka008c/caps-sps/jenkins_mesos/ansible/jenkins_mesos_icinga.yml

PLAY ***************************************************************************
skipping: no hosts matched

PLAY ***************************************************************************
skipping: no hosts matched

PLAY ***************************************************************************
skipping: no hosts matched

PLAY RECAP *********************************************************************
