### ISSUE TITLE
docker: ports does not add firewall forward rules

### ISSUE THREAD

**Issue by itatabitovski** [ansible/ansible#8328]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6
##### Environment:

Debian 7.6
kernel 3.14-0.bpo.1-amd64
docker-py==0.4.0
##### Summary:

docker: ports=8080:80 does not add any rules in the FORWARD chain.

Running the same from the command line works and adds the firewall rules
docker -p 8080:80

This seems related
https://github.com/docker/docker-py/issues/141

I tried to create the container manually with docker-py and the firewall rules were added.

```
container = c.create_container('search-service',ports=[(80,'tcp')], environment=["ADDRESS=0.0.0.0"])
c.start(container, port_bindings={80:('0.0.0.0', 8080)})
```
##### Steps To Reproduce:

Use the docker module to create docker container and make sure to use the ports option as well.
Run the same from the command line with the -p option.

Compare the iptables -L FORWARD outputs.
##### Expected Results:

Add a rule in the FORWARD chain when using the docker module in ansible.
##### Actual Results:

The container is started properly, but no rule was added in the FORWARD chain.

**Comment by itatabitovski** [comment]
Works correctly but requires expose= to be also configured.
With expose= configured, the iptables rule is added

**Comment by nfelsen** [comment]
Thanks @itatabitovski, I've been trying for way too many hours to get that to work... that is just super not obvious

**Comment by thekantian** [comment]
+1 for this issue needing more docs or a more clear behavior, also spent more time then i'd like to admit debugging this behavior!
