### ISSUE TITLE
connection types should be actual plugins

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#833]
Meaning if I drop more plugins in a directory, they should register and be usable.

Having to reference the valid plugins in the config file (pending) may be ok.

**Comment by willthames** [comment]
Had a bit of a think about this, and while it's easy to subclass ParamikoConnection, it doesn't make much sense to do so as it conflates transport and privilege escalation. I wonder if there should be an underlying transport mechanism (paramiko, local, ssh) with a command layer on top (unprivileged, sudo, su). 

Another key question is how the plugin would handle the rest of the needed pluggability - adding and handling command line options. 

None of this is essential - as I say, I have already subclassed ParamikoConnection and can reuse sudo_user, sudo_pass etc. but it's worth considering before this is implemented.

**Comment by mpdehaan** [comment]
Not interested in that.  These things go together, and necessarily.

You may be able to get arbitrary options from the config file when I get done, TBD.

**Comment by mpdehaan** [comment]
Connection types are now pluggable.  See mailing list.
