### ISSUE TITLE
Solaris facts fail when forced only IPv4 stack

### ISSUE THREAD

**Issue by nudzo** [ansible/ansible#8330]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.10
##### Environment:

Solaris
##### Summary:

When IPv4 only stack forced with /etc/default/inet_type having:

```
DEFAULT_IP=IP_VERSION4
```

Solaris do not report IPV4 or IPV6 flags on network interfaces and this run facts module to fail in:

```
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1406623296.03-247022719817805/setup", line 3715, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1406623296.03-247022719817805/setup", line 134, in main
    data = run_setup(module)
  File "/root/.ansible/tmp/ansible-tmp-1406623296.03-247022719817805/setup", line 78, in run_setup
    facts = ansible_facts(module)
  File "/root/.ansible/tmp/ansible-tmp-1406623296.03-247022719817805/setup", line 3655, in ansible_facts
    facts.update(Network(module).populate())
  File "/root/.ansible/tmp/ansible-tmp-1406623296.03-247022719817805/setup", line 3017, in populate
    interfaces, ips = self.get_interfaces_info(ifconfig_path)
  File "/root/.ansible/tmp/ansible-tmp-1406623296.03-247022719817805/setup", line 3334, in get_interfaces_info
    current_if = self.parse_interface_line(words, current_if, interfaces)
  File "/root/.ansible/tmp/ansible-tmp-1406623296.03-247022719817805/setup", line 3379, in parse_interface_line
    current_if[v].append({'flags': flags, 'mtu': words[3]})
UnboundLocalError: local variable 'v' referenced before assignment
```

Found in Solaris10, but most probably affects all Solaris versions and its derivates. If there's no IPV4 nor IPV6 flag, it would assume it is like IPV4 present.
##### Steps To Reproduce:

Set  /etc/default/inet_type containing:

```
DEFAULT_IP=IP_VERSION4
```

and run ansible hostname -m setup
##### Expected Results:

Module facts do pass and collect facts.
##### Actual Results:

Python exception

**Comment by mpdehaan** [comment]
Something you might like to work on, perhaps?  If not, that's fine, and we can attack.

**Comment by nudzo** [comment]
I can look at that, but presently I'm pretty busy next month. Hopefully then I can contribute with some preliminary version of module for managing Solaris zones too.

**Comment by jimi-c** [comment]
I believe this should fix it:

<pre>
diff --git a/lib/ansible/module_utils/facts.py b/lib/ansible/module_utils/facts.py
index c1eaaaa..72f73d6 100644
--- a/lib/ansible/module_utils/facts.py
+++ b/lib/ansible/module_utils/facts.py
@@ -2042,8 +2042,7 @@ class SunOSNetwork(GenericBsdIfconfigNetwork, Network):
         else:
             current_if = interfaces[device]
         flags = self.get_options(words[1])
-        if 'IPv4' in flags:
-            v = 'ipv4'
+        v = 'ipv4'
         if 'IPv6' in flags:
             v = 'ipv6'
         current_if[v].append({'flags': flags, 'mtu': words[3]})
</pre>

**Comment by jimi-c** [comment]
I've gone ahead and merged the above commit in. If you continue seeing any problems related to this, please let us know. Thanks!
