### ISSUE TITLE
Tasks run in serial when using same ansible_ssh_host with different ansible_ssh_port's.

### ISSUE THREAD

**Issue by PriceChild** [ansible/ansible#8333]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.10
##### Environment:

Debian Sid managing Centos 6
##### Summary:

A standard environment when running using Vagrant is that it creates an inventory file at .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory with something like the following:

> $ cat example-hosts-broken
> www1 ansible_ssh_host=127.0.0.1 ansible_ssh_port=2222 ansible_ssh_user=root
> www2 ansible_ssh_host=127.0.0.1 ansible_ssh_port=2200 ansible_ssh_user=root
> db1 ansible_ssh_host=127.0.0.1 ansible_ssh_port=2201 ansible_ssh_user=root
> db2 ansible_ssh_host=127.0.0.1 ansible_ssh_port=2202 ansible_ssh_user=root`

When using this inventory file, all actions seem to take place in a serial fashion. i.e. tasks take 4x as long as they should!
##### Steps To Reproduce:

Using the hosts file above, run something like `ansible all -m shell -a "sleep 5 && uptime" -f 10 -i example-hosts-broken` and note that the output is delayed by at least 5 seconds between each report despite `-f 10` and no serial keyword. Note that it takes 5 seconds for each vm to report.
##### Expected Results:

If you run it against dedicated addresses, without reusing them, you get expected behaviour returning after 5 seconds:

> $ cat example-hosts
> www1 ansible_ssh_host=192.168.33.21 ansible_ssh_user=root
> www2 ansible_ssh_host=192.168.33.22 ansible_ssh_user=root
> db1 ansible_ssh_host=192.168.33.41 ansible_ssh_user=root
> db2 ansible_ssh_host=192.168.33.42 ansible_ssh_user=root
> $ ansible all -m shell -a "sleep 5 && uptime" -f 10 -i example-hosts
> db1 | success | rc=0 >>
>  12:17:09 up 59 min,  0 users,  load average: 0.00, 0.01, 0.00
> 
> db2 | success | rc=0 >>
>  12:17:17 up 59 min,  0 users,  load average: 0.04, 0.03, 0.00
> 
> www2 | success | rc=0 >>
>  12:17:09 up  1:00,  0 users,  load average: 0.00, 0.00, 0.00
> 
> www1 | success | rc=0 >>
>  12:17:09 up  1:01,  0 users,  load average: 0.00, 0.00, 0.00

(Again, vm's clocks aren't perfect but they all returned at the same time, at 5 seconds)

I would expect this behaviour in the above example too.
##### Actual Results:

> $ ansible all -m shell -a "sleep 5 && uptime" -f 10 -i example-hosts-broken 
> db1 | success | rc=0 >>
>  12:15:40 up 58 min,  0 users,  load average: 0.01, 0.02, 0.00
> 
> www2 | success | rc=0 >>
>  12:15:45 up 59 min,  0 users,  load average: 0.00, 0.00, 0.00
> 
> www1 | success | rc=0 >>
>  12:15:51 up 59 min,  0 users,  load average: 0.00, 0.00, 0.00
> 
> db2 | success | rc=0 >>
>  12:16:03 up 58 min,  0 users,  load average: 0.01, 0.02, 0.00

(VM clocks aren't perfect above, but there are 5 seconds between each report.)

**Comment by mpdehaan** [comment]
The vagrant integration is not something we maintain, but please stop by ansible-project if you'd like some help exploring what may be going on here.

**Comment by PriceChild** [comment]
Hey @mpdehaan thanks for looking at this. I think you should reopen the bug though as I don't think it has any relation to Vagrant, it just so happens that that is how I discovered it.

Please try using my examples (without vagrant even, just spin up some locally forwarded ports)

**Comment by PriceChild** [comment]
At the suggestion of ariedler in #ansible, I tried adding a bunch of aliases into /etc/hosts:

> $ grep test /etc/hosts
> 192.168.33.21 1.test 2.test 3.test
> 192.168.33.21 4.test
> $ cat inventory 
> 1.test ansible_ssh_user=root
> 2.test ansible_ssh_user=root
> 3.test ansible_ssh_user=root
> 4.test ansible_ssh_user=root

But running on this and all hosts returned at the same time, within 5 seconds:

> $ ansible all -m shell -a "sleep 5 && uptime" -f 10 -i inventory 
> 2.test | success | rc=0 >>
>  14:22:19 up 23 min,  0 users,  load average: 0.00, 0.03, 0.01
> 
> 4.test | success | rc=0 >>
>  14:22:19 up 23 min,  0 users,  load average: 0.00, 0.03, 0.01
> 
> 1.test | success | rc=0 >>
>  14:22:19 up 23 min,  0 users,  load average: 0.00, 0.03, 0.01
> 
> 3.test | success | rc=0 >>
>  14:22:19 up 23 min,  0 users,  load average: 0.00, 0.03, 0.01

so it appears to be an issue with the use of the ansible_ssh_host variable and not an inherent problem with identical destinations.

**Comment by PriceChild** [comment]
`ANSIBLE_HOST_KEY_CHECKING=False` removes the issue... but all of the keys have already been accepted so this still shouldn't be happening. At least we have a lead.

**Comment by PriceChild** [comment]
known_hosts hashes are in the format `[host]:port`, not simply `host` when a non-standard port is specified. I'm guessing ssh's not_in_host_file() needs updating to reflect this and I'll see if I can confirm/submit a pull request.

**Comment by PriceChild** [comment]
https://gist.github.com/PriceChild/e591cade8661150ad343 seems to fix my usecase but no doubt breaks others... will look more carefully tomorrow.
