### ISSUE TITLE
stacktrace instead of proper error for "when: inventory_hostname in groups['doesnotexist']" in a Template

### ISSUE THREAD

**Issue by bubba-h57** [ansible/ansible#8336]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6 
##### Environment:

Ubuntu 12.04
##### Summary:

This is similar to issue https://github.com/ansible/ansible/issues/4730 which has been resolved.

Referring to a variable `groups.doesnotexist` within a template triggers a stacktrace instead of a proper error.
##### Steps To Reproduce:

 Create a template containing

``` yaml
{% if inventory_hostname in groups.doesnotexist %}
testing
{% endif %}
```

and simply call it with
`- template: src=test.j2 dest=/tmp/test.txt`
##### Expected Results:

`fatal: [some.host.com] => error while evaluating conditional: inventory_hostname in groups.doesnotexist`
##### Actual Results:

`fatal: [some.host.com] => {'msg': "argument of type 'StrictUndefined' is not iterable", 'failed': True}`

**Comment by mpdehaan** [comment]
Thanks!

Can you please include the stack trace?

We'll likely just want to say "template error" and give the string message with the line number in the template.

**Comment by mpdehaan** [comment]
Hi,

I'm closing this one as we haven't seen any activity in some time.

If you have continued problems with this one on a recent version of Ansible (i.e. 1.7), please feel free to open a new ticket.   Thank you!

**Comment by bubba-h57** [comment]
I added the stack trace as you asked .. was there something else you wanted me to do in order to progress the bug that I'm ignorant of?

**Comment by davidvasandani** [comment]
I experienced the same issue. Is there anything I can provide to get this ticket reopened?
