### ISSUE TITLE
unarchive in pull and push mode with 

### ISSUE THREAD

**Issue by MartenVijn** [ansible/ansible#8346]
##### Issue Type:

 “Feature Idea”,
##### Ansible Version:

ansible 1.6.10
##### Environment:

Ubuntu 14.4
##### Summary:

Currently is seems that unarchive behaves differently in push or pull mode
##### Steps To Reproduce:

In the same playbook

unarchive =>  push mode does not work with option copy=no

oke=> unarchive: src=files/tarbal.tgz dest=/tmp/ creates=/tmp/my_dir 
not oke => unarchive: src=files/tarbal.tgz dest=/tmp/ creates=/tmp/my_dir copy=no

unarchive =>  pull mode does only work with option copy=no
oke=> unarchive: src=files/tarbal.tgz dest=/tmp/ copy=no creates=/tmp/my_dir
not oke=> unarchive: src=files/tarbal.tgz dest=/tmp/ creates=/tmp/my_dir
##### Expected Results:

IHMO those 4 lines could be 1, making unarchive working the the same in push and pull modus. 
##### Actual Results:

workaround it:
name: roll tarbal.tgz
    unarchive: src=files/tarbal.tgz dest=/tmp/ copy=no creates=/tmp/my_dir
    when: ansible_hostname == 'localhost'
    unarchive: src=files/tarbal.tgz dest=/tmp creates=/tmp/my_dir
    when: ansible_hostname != 'localhost'

**Comment by mpdehaan** [comment]
Unarchive would need to be passed the copy=no if you were using it it with ansible-pull, but no, it's not different, it just running locally, as with "-c local".

In that case, the scp/sftp becomes a local copy command, but that's it.

For follow up questions, feel free to stop by ansible-project.

Thanks!

**Comment by MartenVijn** [comment]
On Jul 30, 2014, at 3:08 PM, Michael DeHaan notifications@github.com wrote:

> Unarchive would need to be passed the copy=no if you were using it it with ansible-pull, but no, it's not different, it just running locally, as with "-c local".
> 
> In that case, the scp/sftp becomes a local copy command, but that's it.
> 
>  in the pull version would copy=no, the module won’t find the file. nor files/ nor in
> roles/<Role>/files 

cheers,
Marten
