### ISSUE TITLE
old sudo problem

### ISSUE THREAD

**Issue by jdavisp3** [ansible/ansible#835]
Some older sudo's do not accept the -- command line switch. I'm happy to work on this, but what is the appropriate way to change the behavior -- command line switch, env var, yaml config, something else?

**Comment by mpdehaan** [comment]
What platform are you attempting to run /usr/bin/ansible or /usr/bin/ansible-playbook on?

**Comment by jdavisp3** [comment]
It is centos 5. And by 'ssh', I meant 'sudo'! Why do all these programs have to start with 's' :)

**Comment by mpdehaan** [comment]
hmm.  I don't know.   Find something that works in terms of command line flags and then see if we can just use that generically everywhere?   It is strange that no one has reported this before, with a fair amount of EL5 still out there and people using sudo.

I'll paste this in IRC also to see if anyone has ideas.

**Comment by jdavisp3** [comment]
Right now I'm just not passing the double dashes to sudo and that is working so far. But I do like the idea of using them if they are available.

**Comment by mpdehaan** [comment]
seems ok on CentOS 6.3, pushed this change, I imagine people will yell if it breaks them and we can deal with it then.

**Comment by jdavisp3** [comment]
Thanks very much!
