### ISSUE TITLE
setup module fails with "ValueError: No escaped character" (some OpenSuSE systems)

### ISSUE THREAD

**Issue by timricese** [ansible/ansible#8352]
##### Issue Type:

Bug report
##### Ansible Version:

1.6.10
##### Environment:

Ubuntu 14.04 local, OpenSuse 11.1 x64 remote.
##### Summary:

setup/gathering facts fails on one of our OpenSuSE 11.1 servers. Strangely it works on the other 29 supposedly identicle configured servers...

setting posix=False in the shlex.split() function appears to make things work again.. but this shouldnt be neccesary i guess?

mght not be relevant but the system locale is sv_se (Sweden).

Running Ansible 1.6.10, Python 2.7.6 locally and Python 2.7.8 on the remote
##### Steps To Reproduce:

run setup or any playbook that gathers facts on this particular remote host.
##### Expected Results:

facts about the remote host
##### Actual Results:

critical error.

---

< GATHERING FACTS >

---

```
    \   ^__^
     \  (oo)\_______
        (__)\       )\/\
            ||----w |
            ||     ||
```

failed: [xxxxxxxxxxx] => {"failed": true, "parsed": false}
invalid output was: 
SUDO-SUCCESS-eefnvjdxozefnzmgawkdnpvlwdarkijg
Traceback (most recent call last):
  File "/home/tiri01/.ansible/tmp/ansible-tmp-1406724952.28-260095855254133/setup", line 3715, in <module>
    main()
  File "/home/tiri01/.ansible/tmp/ansible-tmp-1406724952.28-260095855254133/setup", line 134, in main
    data = run_setup(module)
  File "/home/tiri01/.ansible/tmp/ansible-tmp-1406724952.28-260095855254133/setup", line 78, in run_setup
    facts = ansible_facts(module)
  File "/home/tiri01/.ansible/tmp/ansible-tmp-1406724952.28-260095855254133/setup", line 3653, in ansible_facts
    facts.update(Facts().populate())
  File "/home/tiri01/.ansible/tmp/ansible-tmp-1406724952.28-260095855254133/setup", line 1476, in **init**
    self.get_cmdline()
  File "/home/tiri01/.ansible/tmp/ansible-tmp-1406724952.28-260095855254133/setup", line 1683, in get_cmdline
    for piece in shlex.split(data):
  File "/opt/python2.7/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/opt/python2.7/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/opt/python2.7/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/opt/python2.7/lib/python2.7/shlex.py", line 191, in read_token
    raise ValueError, "No escaped character"
ValueError: No escaped character

**Comment by jimi-c** [comment]
Is this machine or any of the others on a Windows domain? My first guess, based on the error, is that there's a DOMAIN\user somewhere that's being brought into the output from a shell command gathering data for the facts, and shlex is assuming it's supposed to be an escape character (but of course it isn't).

**Comment by jimi-c** [comment]
Actually that's probably not the issue - I see it's in the "get_cmdline" function, which is just reading `/proc/cmdline`. Could you share what the content of that is on the problematic system?

**Comment by timricese** [comment]
The content of /proc/cmdline is

root=/dev/disk/by-id/scsi-3600508e000000000b3bc389ef1557109-part1
resume=/dev/disk/by-id/scsi-3600508e00000000088a6c2300a3c7b0f-part1
splash=silent \

That trailing backslash isnt on any of the other supposedly identicle
servers

**Comment by jimi-c** [comment]
That would be the cause of the error then. We can wrap the fact check in a try/except, but beyond that you'll need to resolve the issue with the trailing character.

**Comment by jimi-c** [comment]
I've pushed the above patch, which should resolve this error. If you see any further problems regarding this issue, please let us know. Thanks!

**Comment by simplyali241** [comment]
For me, this error was occuring when I created config.txt under Roaming as mentioned in the Documentation with wrong slashes.
e.g. 
Incorrect: -o  "D:\SIMPLYALI\AMS\Pers\YoutubeDLVID"
Correct: -o "D:/SIMPLYALI/AMS/Pers/YoutubeDLVID/%(title)s-%(id)s.%(ext)s"

The issue was resolved for me.

Let know if it helps.
[config.txt](https://github.com/ansible/ansible/files/701285/config.txt)
