### ISSUE TITLE
pip install -e (editable) of ansible doesn't work

### ISSUE THREAD

**Issue by msabramo** [ansible/ansible#8355]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

N/A
##### Summary:

pip install -e (editable) of ansible doesn't work

More details below
##### Steps To Reproduce:

More details below.
##### Expected Results:

More details below.
##### Actual Results:

More details below.

This is an inconvenience when trying to hack on ansible.

Steps to reproduce:
1. Starting state: I have ansible installed and `ansible-playbook` executes fine.
2. Create a virtualenv and activate it:
   `
   virtualenv py27.venv && source py27.venv/bin/activate
   `
3. Install ansible from pip as editable:

```
pip install -e 'git+git@github.com:ansible/ansible.git@devel#egg=ansible'
```

Results in:

```
Successfully installed ansible
Cleaning up...
```

So far so good. It pulls down commit 189824dd76eb94574972fe54b390634854b2592d.
4. Try to run ansible-playbook

```
ansible-playbook
```

Results in:

```
Traceback (most recent call last):
  File "/Users/marca/dev/surveymonkey/smstack/py27.venv/bin/ansible-playbook", line 10, in <module>
    execfile(__file__)
  File "/Users/marca/dev/surveymonkey/smstack/py27.venv/src/ansible/bin/ansible-playbook", line 28, in <module>
    import ansible.playbook
ImportError: No module named ansible.playbook
```

Also something strange happens when uninstalling -- the executable file `ansible-playbook` gets left around, which causes problems.
1. Uninstall editable ansible

```
pip uninstall ansible
```

Results in

```
Uninstalling ansible:
  /Users/marca/dev/surveymonkey/smstack/py27.venv/lib/python2.7/site-packages/ansible.egg-link
Proceed (y/n)? y
  Successfully uninstalled ansible
```
1. Run `ansible-playbook` again
   Results in

```
Traceback (most recent call last):
  File "/Users/marca/dev/surveymonkey/smstack/py27.venv/bin/ansible-playbook", line 5, in <module>
    from pkg_resources import require
  File "/Users/marca/dev/surveymonkey/smstack/py27.venv/lib/python2.7/site-packages/pkg_resources.py", line 2829, in <module>
    working_set = WorkingSet._build_master()
  File "/Users/marca/dev/surveymonkey/smstack/py27.venv/lib/python2.7/site-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/Users/marca/dev/surveymonkey/smstack/py27.venv/lib/python2.7/site-packages/pkg_resources.py", line 742, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/marca/dev/surveymonkey/smstack/py27.venv/lib/python2.7/site-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: ansible==1.7
```

This is because the executable script did not get removed:

```
❯ ls -l py27.venv/bin/ansible-playbook
-rwxr-xr-x+ 1 marca  staff  445 Jul 30 07:34 py27.venv/bin/ansible-playbook*
```

so you have to manually clean up:

```
❯ rm py27.venv/bin/ansible-playbook
remove py27.venv/bin/ansible-playbook? y
```

and then `ansible-playbook` works again:

```
❯ ansible-playbook --version
ansible-playbook 1.6.5
```

By contrast, a non-editable pip install works fine, but it's inconvenient when debugging and hacking on ansible code.

```
❯ pip install https://github.com/ansible/ansible/archive/devel.zip
...
Successfully installed ansible
Cleaning up...

❯ hash -r

❯ which ansible-playbook
/Users/marca/dev/surveymonkey/smstack/py27.venv/bin/ansible-playbook

❯ ansible-playbook --version
ansible-playbook 1.7
```

This suggests that ansible is doing something unusual with Python packaging that is confusing pip somewhat in the case of editable packages.

**Comment by msabramo** [comment]
Also see http://stackoverflow.com/questions/11597103/modify-setup-py-to-support-pip-install-from-github

**Comment by msabramo** [comment]
This little hack kind of makes thinks work:

```
 ❯ ansible-playbook --version
Traceback (most recent call last):
  File "/Users/marca/dev/surveymonkey/smstack/py27.venv/bin/ansible-playbook", line 10, in <module>
    execfile(__file__)
  File "/Users/marca/dev/surveymonkey/smstack/py27.venv/src/ansible/bin/ansible-playbook", line 28, in <module>
    import ansible.playbook
ImportError: No module named ansible.playbook

 ❯ ln -s lib/ansible .

 ❯ ansible-playbook --version
ansible-playbook 1.7 (devel 189824dd76) last updated 2014/07/30 08:32:35 (GMT -700)
```

but not completely because ansible can't find its modules:

```
❯ ansible-playbook deploy.yml --extra-vars "hosts=mt5-profileweb role=profileweb is_legacy=true"  --tags=create_user_group --check
ERROR: apt is not a legal parameter in an Ansible task or handler
```

ansible can't find its modules I think so it thinks that `apt` is an illegal parameter. Note that I added more info to the above error message in https://github.com/ansible/ansible/pull/8354

**Comment by msabramo** [comment]
It looks like `python setup.py develop` in the git checkout directory also results in `ImportError: No module named ansible.playbook` (not surprising since `pip install -e` is probably doing the same thing).

**Comment by msabramo** [comment]
The following is a hack to workaround the `ERROR: apt is not a legal parameter in an Ansible task or handler` error mentioned above:

```
❯ ln -s /Users/marca/dev/surveymonkey/smstack/py27.venv/src/ansible/library /Users/marca/dev/surveymonkey/smstack/py27.venv/share/ansible
```

**Comment by mpdehaan** [comment]
See the official docs for supported instructions about how to run from checkout.

http://docs.ansible.com/intro_installation.html#running-from-source

As ansible is a complete application and not just a python library it does not make sense to install the libraries into the homedir, but it's easy to get this going with the above instructions.

**Comment by msabramo** [comment]
Since you're willing to look at https://github.com/ansible/ansible/pull/8367, maybe this issue should be reopened so it can get closed when that PR is merged or declined? Your call.

**Comment by msabramo** [comment]
Note: #8367 was merged, so `pip install -e` should work now.
