### ISSUE TITLE
fix paramiko connection and raw module against hosts that don't have a shell

### ISSUE THREAD

**Issue by sfromm** [ansible/ansible#837]
In paramiko_ssh.py, the exec_command() method has the following, starting at line 87:

```
    if not self.runner.sudo or not sudoable:                                                                                    
        quoted_command = '"$SHELL" -c ' + pipes.quote(cmd)                                                                      
        vvv("EXEC %s" % quoted_command, host=self.host)                                                                         
        chan.exec_command(quoted_command)              
```

The problem with the above is when using the raw module.  When connecting to devices that do not have a $SHELL, the above command will fail.  It also doesn't match the argument supplied to the raw module.

In comparison, the ssh connection type (ssh.py) does not modify the supplied command, starting at line 96:

```
        ssh_cmd.append(cmd)                                                                                                     
        vvv("EXEC %s" % ssh_cmd, host=self.host)                                                                                
        p = subprocess.Popen(ssh_cmd, stdin=subprocess.PIPE,                                                                    
                             stdout=subprocess.PIPE, stderr=subprocess.STDOUT)           
```

Since the connection modules are not module aware, should this modify the quoted_command variable to:

```
        quoted_command = pipes.quote(cmd)
```

**Comment by mpdehaan** [comment]
So when I tried this, things are quite unhappy for both the command module and raw on regular Linux.

I don't know how to best hack this, host variable set to "ansible_noshell : True" ?   Gross, but it would work.
