### ISSUE TITLE
Feature: way to run 'shell' always

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#8374]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.6.10
##### Environment:

N/A
##### Summary:

The 'shell' module is currently skipped when using `ansible-playbook --check`. However this means failures if the shell command is actually just probing the system and the registered output is being used to decide which subsequent tasks to run.
##### Steps To Reproduce:

```
- shell: nfdump -V || true
  register: nfdump_check

- include: build_nfdump.yml
  when: nfdump_version not in nfdump_check.stdout
```
##### Expected Results:

I would like there to be a way to force the shell command to be run in all circumstances, otherwise the subsequent conditional fails.

Arguably the above test should be done using a "custom fact" module, but that involves substantially more work than a one-line shell command to extract the information of interest.
##### Actual Results:

Works with `ansible`, but when running `ansible --check` gives:

```
fatal: [X.X.X] => error while evaluating conditional: nfdump_version not in nfdump_check.stdout
```

**Comment by mpdehaan** [comment]
this is the "always_run: True" keyword, please search the docs and you'll find an example about using it.

Thanks!

**Comment by candlerb** [comment]
OK, I [found it](http://docs.ansible.com/playbooks_checkmode.html#running-a-task-in-check-mode) now.

I was looking in http://docs.ansible.com/shell_module.html and that's why I couldn't find it.

Suggestion:
1. Have a page listing keywords which are common to _all_ modules (I don't think such a page exists - for example, `always_run` only seems to be mentioned in `docsite/rst/playbooks_checkmode.rst`)
2. Include a link to this page from every module page

**Comment by candlerb** [comment]
Moved to #8376
