### ISSUE TITLE
Document options which are common to all modules

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#8376]
##### Issue Type:

Documentation report
##### Ansible Version:

ansible 1.6.10
##### Environment:

N/A
##### Summary:

There are a number of options which are common to all modules. AFAICS they are not currently listed together in a single place. These include things like `always_run` (playbooks_checkmode.rst), `changed_when` (playbooks_error_handling.rst), and probably a load of others.

I suggest:
- List all the common options on one page, with links to the pages where each one is described
- Every module page has a link to this page, preferably below the table of module options
##### Steps To Reproduce:

Go the the [shell module](http://docs.ansible.com/shell_module.html) page and try to work out how to make a shell command run unconditionally (even with `--check`) or not return a "changed" status.
##### Expected Results:

All options to shell module are findable from this page
##### Actual Results:

Only options specific to shell are shown

**Comment by mpdehaan** [comment]
These are actually not options to the module so these should not appear on the module docs, but we have talked about an index of keywords before (and I think there's a ticket for it) sot hat could go there.
