### ISSUE TITLE
mount module: -o remount fails with nfs

### ISSUE THREAD

**Issue by robinro** [ansible/ansible#8377]
##### Summary:

Using the mount module: With nfs (both 3 and 4), the -o remount fails.

Thus the mount module should detect nfs (or remote filesystems in general?) and switch to umount/mount instead of remount if the dir is mounted previously.
In general remount seems to be intended for modifying options, not paths, like changing an nfs mount from server1 to server2, so maybe this change could be extended even further.
##### Steps To Reproduce:

use the mount module to change the hostname of an existing and active nfs mount
##### Expected Results:

old mount is unmounted and replaced by new mount
##### Actual Results:

module fails

**Comment by mpdehaan** [comment]
Can you share the lines you have in your playbook?

Also can you test with the latest version of Ansible, which is 1.6.10?

Thanks!

**Comment by mpdehaan** [comment]
Hi,

I'm closing this one as we haven't seen any activity in some time.

If you have continued problems with this one on a recent version of Ansible (i.e. 1.7), please feel free to open a new ticket.   Thank you!

**Comment by Rtzq0** [comment]
This problem is still present as recently as 1.9.4.

Mount an nfs mount with ansible, then change your opts variabl and run your playbook again. Ansible will print the unsupported mount option error because as per http://linux.die.net/man/8/mount.nfs -o remount is unsupported.
