### ISSUE TITLE
mount module does nothing if /etc/fstab agrees, even when mounted state doesn't agree

### ISSUE THREAD

**Issue by robinro** [ansible/ansible#8379]
##### Summary:

The mount module does nothing if /etc/fstab agrees, even when mounted state doesn't agree.
It assumes that if /etc/fstab is fine and the directory is an active mountpoint everything is fine. Instead it should check what is actually mounted there.

In combination with #8377 this leads to a situation, where when running ansible twice, the first try changes /etc/fstab but the mount fails, so ansible fails. Then on a second run /etx/fstab is fine and another filesystem is still mounted, so ansible returns 'ok'.
##### Steps To Reproduce:

**before running ansible:**
    mount server1:/mnt /mnt
    in /etc/fstab: "server2:/mnt /mnt"

**ansible:**
    mount: src=server2:/mnt name=/mnt state=mounted
##### Expected Results:

remount new destination as requested
##### Actual Results:

ansible does nothing (result=ok), because after realizing that /etc/fstab is fine it only checks whether the destination is mounted.

**Comment by mpdehaan** [comment]
Can you please share the lines from your playbook and also test with the latest ansible, which is 1.6.10?

I think this ticket could also be summarized as "can't change one mount point to mount something else", basically, would that be correct?

**Comment by mpdehaan** [comment]
Hi,

I'm closing this one as we haven't seen any activity in some time.

If you have continued problems with this one on a recent version of Ansible (i.e. 1.7), please feel free to open a new ticket.   Thank you!
