### ISSUE TITLE
Unneeded bashism when retrieving remote md5 prevents fetch (at least) from working whith other shells

### ISSUE THREAD

**Issue by sbocahu** [ansible/ansible#839]
The test builtin command of bash ( [[ ) is used to retrieve a md5 sum of a remote file. Bash shouldn't be needed on remote servers (IMHO) and it is absolutely not necessary in this case. It prevents fetch (at least) module from working on systems that do not use bash (Debian has dash for example, or BSD / other unix)

Here is a small patch to address this issue: https://gist.github.com/3314097

Thanks

**Comment by mpdehaan** [comment]
sounds reasonable, please submit this as a pull request and I'll take it.

see: https://help.github.com/articles/using-pull-requests/
