### ISSUE TITLE
Exponential regex time in filter_leading_non_json_lines

### ISSUE THREAD

**Issue by gnosek** [ansible/ansible#8392]
##### Summary:

`filter_leading_non_json_lines` effectively does

```
re.match(".*\w+=\w+.*", line)
```

for every line of output. This has abysmal performance in case of large Base64-encoded data (which ultimately does not match the regex but _does_ match the .*\w+= part).

Replacing the match with

```
re.search("\w=\w", line)
```

drops the complexity back to linear, and actually usable with large diffs from the template module (a 150 KB Base64 diff kept Ansible spinning at 100% cpu for minutes).

Benchmarked by the script below:

```
1 0.000257 0.000086
2 0.000009 0.000005
4 0.000007 0.000005
8 0.000008 0.000005
16 0.000009 0.000005
32 0.000016 0.000006
64 0.000042 0.000007
128 0.000135 0.000011
256 0.000493 0.000017
512 0.001824 0.000029
1024 0.006999 0.000052
2048 0.028296 0.000124
4096 0.112752 0.000206
8192 0.443359 0.000394
16384 1.787814 0.000757
32768 7.093293 0.001488
^C
```
##### Steps To Reproduce:

```
import re
import time

def time_num_reps(n):
    now = time.time()
    bool(re.match(".*\w+=\w+.*", "x" * n + "="))
    match = time.time() - now
    now = time.time()
    bool(re.search("\w=\w", "x" * n + "="))
    search = time.time() - now
    print '{0} {1:.6f} {2:.6f}'.format(n, match, search)

if __name__ == '__main__':
    n = 1
    while True:
        time_num_reps(n)
        n *= 2
```

To reproduce via Ansible, make the template module return a _large_ diff (w/ -D option). Ansible will hang spinning 100% CPU in sre_match.
##### Expected Results:

A large diff on screen
##### Actual Results:

100% CPU for minutes

**Comment by gnosek** [comment]
Pull request here: https://github.com/ansible/ansible/pull/8393

**Comment by mpdehaan** [comment]
Closing this ticket as we have the pull request to track and don't need 2 tickets - thank you!
