### ISSUE TITLE
multiline modules issue with "|" and ">" and newline preservation

### ISSUE THREAD

**Issue by bcoca** [ansible/ansible#8394]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel c93b89fa63)
##### Environment:

Ubuntu 12.04, 14.04
##### Summary:

Previously working multiline tasks stopped working
##### Steps To Reproduce:

In a play:

```
    - name: Set timezone variables
      copy: |
            content='America/New_York
            '
            dest=/tmp/timezone
```
##### Expected Results:

timezone file gets updated
##### Actual Results:

```
failed: [localhost] => {"failed": true}                                                                                                                                    
msg: src (or content) and dest are required                                                                                                                                

FATAL: all hosts have already failed -- Aborting                                                                                                                                                                                     
```

changing the  | to a > makes it work again, but this code had been working for a looong time (I'll run bisect when i have time to see what caused the issue)

**Comment by mpdehaan** [comment]
Thanks for the report. 

Please don't bother with the bisect, various parser changes have been required for security fixes.   It seems the ">" is the proper answer but we can explore this one.

**Comment by jimi-c** [comment]
I've pushed the above commit, which should resolve this issue. If you continue seeing any problems related to this issue, please let us know. Thanks!

**Comment by bcoca** [comment]
tested with play that initially gave me issues, all works! thanks!
