### ISSUE TITLE
Make ansible galaxy support installation from git repo with submodules

### ISSUE THREAD

**Issue by btmc** [ansible/ansible#83996]
### Summary

I need to install a collection from git source, which has another git repo as submodule inside.

On running `ansible-galaxy install` I get only main repo contents in collections path (with necessary metadata files added), but the submodule contents is absent, which makes automating the installation procedure troublesome.

This probably happens as currently ansible runs `git clone` command (followed by `git checkout`), with no additional cli parameters or option to define some ([link](https://github.com/ansible/ansible/blob/v2.17.4/lib/ansible/galaxy/collection/concrete_artifact_manager.py#L430)).

Unfortunately, there is no way to configure git to have `git clone` initialize submodules by default, and it doesn't seem to be possible to alias it some way (either in shell or git).

The matter is further complicated as this checkout is being done by ansible to a temporary directory first, and `.git` metadata is not copied to the final collection destination, so there is no chance to run additional git commands on it, or use hooks.

My current workaround is replacing `git` binary with shell wrapper, which adds this cli parameter to `git clone` calls.

Please add support for this case.

Or maybe there is a solution I've missed, any help will be welcome.

### Issue Type

Feature Idea

### Component Name

ansible-galaxy

### Additional Information

It would make possible to install collections from git repos with submodules, which is probably not a wide-spread case, but may be needed.

If this feature is realized as a more general ability to configure git command parameters, it might be useful for some other cases as well.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
Support for git repos is purposefully minimal, and only supports a small subset of features.  We just merged a documentation PR that recommends for any realm of more complex requirements, to just git clone the repo into the correct location:

https://github.com/ansible/ansible-documentation/pull/1894

If you have further questions please stop by our forum or Matrix:

   * Forum: https://forum.ansible.com/
   * Matrix: https://matrix.to/#/#users:ansible.com
