### ISSUE TITLE
Allow a role's main file to have the same name as the role, instead of being called main.yml

### ISSUE THREAD

**Issue by ansible-feedback** [ansible/ansible#84063]
### Summary

I've started breaking things out into roles, and all of the tabs in my code editor are named `main.yml`.

The `vars/` folder uses `main.yml`, the `tasks/` folder uses `main.yml`, and when editing multiple roles, it's `main.yml` all across the top of the editor which is very hard to work with.

Can we make it optional to call the main file the same name as the role folder name and have it auto-include like `main.yml` does?  

So if you have an `nginx` role, it would be:

```
  roles/nginx/vars/nginx-vars.yml
  roles/nginx/tasks/nginx-tasks.yml
```

And an `apache` role would be:

```
  roles/apache/vars/apache-vars.yml
  roles/apache/tasks/apache-tasks.yml
```

That way Ansible can find the role's main file using a pattern match, but every single file isn't called `main.yml`?

This would make it much easier to find which tab is which with multiple tabs open by giving each file a unique and meaningful name instead of calling them all main.

### Issue Type

Feature Idea

### Component Name

core

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mkrizek** [comment]
You can already do this by using `tasks_from` when using `include_role`/`import_role` https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_role_module.html#parameter-tasks_from / https://docs.ansible.com/ansible/latest/collections/ansible/builtin/import_role_module.html#parameter-tasks_from.

If you have further questions please stop by the Ansible Forum:

* [Ansible Forum](https://forum.ansible.com)

See this page for a complete and up to date list of communication channels and their purposes:

* <https://docs.ansible.com/ansible/latest/community/communication.html>

**Comment by ansible-feedback** [comment]
That's not the same.

This request is to make a file act the same as `main.yml`, by naming it
the same name as the role name, and **without** using
include_role/tasks_from.

You would just use:

```
roles:
  - my-role
```

...to include the role, and Ansible would find and use `/roles/my-
role/tasks/my-role.yml`, without the need to specify any specific
files.

**Comment by s-hertel** [comment]
Depending on the editor you use, there may be an option to customize the tab names (vim lets me configure all the things). It's complicated enough that there may be `main`, `main.yml`, `main.yaml`, and `main.json` files side by side. Adding another convention would have to have less precedence than the existing behavior in order to preserve backwards-compatibility, and making up for the deficiencies of an editor does not seem like a good reason to further complicate it.
