### ISSUE TITLE
lineinfile module change the default behavior without documentation.

### ISSUE THREAD

**Issue by kevintsai** [ansible/ansible#8417]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

CentOS 6.5
##### Steps To Reproduce:

```
Before Ansible 1.7
line='export PS1="\u@\h\$ "'

Ansible 1.7
line='export PS1="\\u@\\h\\$ "'
```
##### Summary:

Before Ansible 1.7, the `line` parameter doesn't include the regexp function.
Now, Ansible 1.7's `line` include the regexp function without documentation.
for me, it's a bug.
it made my hundred of servers broken the configuration !!!!
Please please please don't change the default behavior of that, add a new option in it! 
Cause it will become nightmare to your fan.
Especially users may use both Ansible versions with same recipes to run the deploy job.
I hope you hear the voice from your fan. Big Thanks.

**Comment by mpdehaan** [comment]
The regexp parameter is documented on http://docs.ansible.com/lineinfile_module.html, I do see the "version_added" attribute does not appear to be present, which I'm taking care of now.  Thanks for the report.

**Comment by mpdehaan** [comment]
https://github.com/ansible/ansible/blob/devel/library/files/lineinfile

**Comment by mpdehaan** [comment]
Corrected link:  https://github.com/ansible/ansible/commit/c5f92597e41f8f6bf0eea83f9ea5e58c1273724f
