### ISSUE TITLE
Cannot undefine a variable?

### ISSUE THREAD

**Issue by axos88** [ansible/ansible#8423]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.6.10
##### Environment:

N/A
##### Summary:

I would like to be able to install packages either to their latest version, or a version defined.
I tried doing something like this, but there seems to be no way around this issue:
- name: install dependent pip packages
  pip: name={{item.name}} version={% if item.version is defined }} {item.version }} {% else %} {{ ???? }}  {% endif %} state={% if item.version is defined }} { ???? }} {% else %} latest {% endif %}
  with_items:
  - name: carbon
     state: latest
  - name: whisper
     state: latest
  - name: Twisted
    version: 11.1.0

Even if this worked, it's ugly.
##### Steps To Reproduce:

My preferred way to do this would be an defined filter (like the ? ... : operator in many languages ), which would be similar to the default filter, but would return its first argument if the first argument is defined and the second if not.

pip: name={{item.name}} version={{item.version | defined(item.version, 'undefined')}} state={{item.version | defined(undefined, 'latest')}}
##### Expected Results:

carbon and whisper installed to latest, 
twisted installed to supplied version

**Comment by mpdehaan** [comment]
This has been discussed on the mailing list a few times about having an omit parameter.

The above syntax is not what we'll be supporting to be sure.

The proposal for which we have a pull request for is:

{{ foo | omit }}

Which would allow not passing the argument if foo is false or none.

Similarly {{ omit }} would work as a value.

This is likely something we'll include for 1.8

**Comment by axos88** [comment]
While this makes this problem possible to solve, it is not enough for a clean solution.

It can solve the part of the version with version={{item.version | omit }}, but a complex and ugly if-else-end is needed for the state part. The state needs to be latest in case version is empty, and present in case version is set. So our condition variable is different than our result
