### ISSUE TITLE
Ansible using SFTP for running remote tasks

### ISSUE THREAD

**Issue by majksner** [ansible/ansible#8428]
Hi,
##### Issue Type:

Issue
##### Ansible Version:

Ansible 1.6.10
##### Environment:

Running Ansible on OSX, managing Ubuntu 14.04
##### Summary:

I have strange issue using Ansible. When I run playbook on vagrant machine it doesn't use SFTP and it works really fast, however when I run same playbook on EC2 instance it uses SFTP for each task somehow (see image below). Both vagrant machine and EC2 Instance have same sudoers file. I'm not sure what I'm missing here. 

![screen shot 2014-08-04 at 4 12 41 pm](https://cloud.githubusercontent.com/assets/512355/3798114/75823ea0-1be1-11e4-9c1f-92c5c4a5fd7e.png)

I'm using OSX latest version, latest version of Ansible, both remote systems where playbook is executed are Ubuntu 14.04 with exactly the same configurations.

**Comment by mpdehaan** [comment]
Ansible will use either OpenSSH or Paramiko.  The OpenSSH support can be configured to use either SFTP or SCP, as configured in ansible.cfg as governed by the setting "#scp_if_ssh = True"

The default is to use SFTP.

If you have questions about this we'd be glad to explain more, stop by ansible-project list or IRC if you like.
