### ISSUE TITLE
Variable is not parsed if another String is in {{ }}

### ISSUE THREAD

**Issue by iljabauer** [ansible/ansible#8429]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6. 
##### Environment:

Host: MacOSX
Slave: Ubuntu 14.04 LTS
##### Summary:

If {{string}} is used in a command then a following variable use like {{variable}} will not be parsed and replaced with the value.
##### Steps To Reproduce:

Following examples are not working (app_name is set to a value like "db"):
- vars:
   app_name: db
- command: "docker inspect -f '{{.NetworkSettings.IPAddress}}' {{app_name}}"
- command: "docker inspect -f '{{.NetworkSettings.IPAddress}}' {{app_name}}"
##### Expected Results:

The result command should be:
docker inspect -f '{{.NetworkSettings.IPAddress}}' db
##### Actual Results:

docker inspect -f '{# .NetworkSettings.IPAddress #}' {# app_name #}

**Comment by mpdehaan** [comment]
Yep, invalid variable detection is a thing and you'll have to do some escaping here.

You can escape this using {% raw %}{{ this shall not be parsed }}{% endraw %}

And should also be able to say {{ which I think reads a little better, but maybe not :)

If you are still having trouble, stop by ansible-project and we can discuss.  Thanks!

**Comment by iljabauer** [comment]
Thank you! This resolved the issue. Maybe we should add this to documentation. Also if I write {{something}} and this variable does not exist. This should be failing with a suggestion for escaping
