### ISSUE TITLE
ini_file module failing with traceback due to "allow_no_value" option to ConfigParser

### ISSUE THREAD

**Issue by mpeters** [ansible/ansible#8430]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel 24f6f656cc)
##### Environment:

Host is Fedora 20, target machine is CentOS 6.5. Python on host is 2.7.5 and on target is 2.6.6.
##### Summary:

Using a simple ini_file task like this

```
ini_file: dest=/etc/php.ini section=Date option=date.timezone value=UTC
```

Results in an error/traceback like this:

```
fatal: [new_host] => failed to parse: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1407164524.25-99162126047534/ini_file", line 1507, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1407164524.25-99162126047534/ini_file", line 193, in main
    changed = do_ini(module, dest, section, option, value, state, backup)
  File "/root/.ansible/tmp/ansible-tmp-1407164524.25-99162126047534/ini_file", line 97, in do_ini
    cp = ConfigParser.ConfigParser(allow_no_value=True)
TypeError: __init__() got an unexpected keyword argument 'allow_no_value'
```

I believe this is caused by the merger of #8400 added the `allow_no_value` parameter which doesn't appear to be a valid value in python 2.6.6.
##### Steps To Reproduce:

Try to use the ini_file module on a python < 2.7
##### Expected Results:

It should have worked without an error.
##### Actual Results:

It creates the above traceback.

**Comment by mpdehaan** [comment]
Ok I'll undo this.

**Comment by mpdehaan** [comment]
I've reverted this and we can take a PR to make it only apply when possible.  Thanks!
