### ISSUE TITLE
Typo in intro_dynamic_inventory.rst

### ISSUE THREAD

**Issue by jgdef** [ansible/ansible#8437]
Parenthetical comment from the documentation file:

note: Cobbler was originally written by Michael DeHaan and is now lead by James Cammarata, who also works for Ansible, Inc

s/lead/led
##### Issue Type:

Documentation Report
##### Ansible Version:

builduser@buildbot:~$ ansible --version
ansible 1.1
##### Environment:

Ubuntu 14.04 (Trusty Tahr)
##### Summary:

Typo in ansible documentation.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
I'm told this is how the Roman civilization collapsed.  Will take care of it.

**Comment by mpdehaan** [comment]
Note you really should update your Ansible, Ansible is at 1.6.10 now and the 1.1 version feels pretty ancient by comparison.
