### ISSUE TITLE
Update "raw" command example

### ISSUE THREAD

**Issue by jamarcus-deloitte** [ansible/ansible#844]
Hi,
On this page http://ansible.github.com/modules.html
This line: ansible newhost.example.com raw -a "yum install python-simplejson"

Needs to be updated (I think) to: ansible newhost.example.com -m raw -a "yum install python-simplejson"

This is based on a question I posted on the list.

James

**Comment by mpdehaan** [comment]
I'll make the update, thanks

FYI -- docs project is ansible/ansible.github.com, so in the future please file docs tickets there instead.
