### ISSUE TITLE
dynamic inventory / hostvars with shell vars not working w/ 1.6

### ISSUE THREAD

**Issue by saschalucas** [ansible/ansible#8452]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.10
##### Environment:

SLES 11.3
##### Summary:

Inventory variables containing shell variables get mangled when inventory type is dynamic
##### Steps To Reproduce:

please see my fist comment
##### Expected Results:

please see my fist comment
##### Actual Results:

please see my fist comment

**Comment by mpdehaan** [comment]
Hi, thanks for the submission.

I think you are asking about things like ${foo} in the shell and we had a ticket about this recently and it should be resolved in the most recent development branch.

We definitely could use more detailed examples of what's going on, can you please supply steps to reproduce, expected results, and actual results?

Also, if you can help test on the development branch we would appreciate it.

Thank you!

cc @jimi-c

**Comment by mpdehaan** [comment]
Found the mailing list thread.

Yep, this is fixed on the development branch.  1.7.0 is coming out this week, so you should be all set.

Thanks for the heads up!
