### ISSUE TITLE
Bad documentation in Copy module.

### ISSUE THREAD

**Issue by edthedev** [ansible/ansible#8457]
##### Issue Type:

Documentation Report
##### Ansible Version:

1.7
##### Environment:

N/A
##### Summary:

The web documentation from the 'copy' command, in the 'state' section, contains the sentence:

"If file, the file will NOT be created if it does not exist, see the copy or template module if you want that behavior."

Thanks docs, but this _is_ the 'copy' module, and yes I do want that behavior...
##### Steps To Reproduce:

See http://docs.ansible.com/copy_module.html.
Scroll down to the 'state' section. Read the contents of the 'comments' column.
##### Expected Results:

Should describe how to produce an Ansible command where, if the file does to be created does not exist, Ansible creates the file. Should _not_ refer to 'copy' as if that was a different command, because it's the same command as we're currently reading about.
##### Actual Results:

Refers to itself in the third person form, with signs that it thinks itself is actually someone else.
Does not describe how to produce an Ansible command where, if the file to be created does not exist, Ansible creates the file.

**Comment by mpdehaan** [comment]
Already fixed just now.   What happened was there was reuse of stuff from file common parameters and I've removed this, so it should now be good.

It was also affecting things like the the 'recurse' parameter.

We're backed by CloudFlare so you might see a while before it updates:

http://docs.ansible.com/copy_module.html

**Comment by mpdehaan** [comment]
If you stil lthink there are docs problems on this, please let us know, BTW!
