### ISSUE TITLE
Jsonified result in display output

### ISSUE THREAD

**Issue by cliffano** [ansible/ansible#8466]
##### Issue Type:

Feature Idea
##### Ansible Version:

1.6.10
##### Environment:

N/A
##### Summary:

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.  Thanks!
##### Steps To Reproduce:

Is there any obvious reason why Ansible chose to display string jsonified result in lots of its displays? e.g. in lib/ansible/callbacks.py

```
    if item:
        msg = "failed: [%s] => (item=%s) => %s" % (host, item, utils.jsonify(results2))
    else:
        msg = "failed: [%s] => %s" % (host, utils.jsonify(results2))
    display(msg, color='red', runner=self.runner)
```

Feature idea:

add the following result display options
1. human readable format, new line per field, and each \n in the value is converted into line feed
2. hide the result altogether
3. keep the jsonified result string

I'm currently using a callback plugin to display the result in an easy to read manner https://gist.github.com/cliffano/9868180 , but the jsonified result is still displayed.
So not only that it doubles the result output, but large jsonified result also clutters the output.
##### Expected Results:
1. human  readable format
   
   TASK: [Do something] *********************************\* 
   changed: [somehost] => 
   
   changed: true
   cmd: ./blah.sh
   stdout: some output with large text here and lots of new lines
2. hide the result
   
   TASK: [Do something] *********************************\* 
   changed: [somehost]
3. keep the jsonified string
   
   TASK: [Do something] *********************************\* 
   changed: [somehost] => {"changed": true, "cmd": "./blah.sh", "stdout": "some output with large text here and lots of new lines"}
##### Actual Results:

TASK: [Do something] *********************************\* 
changed: [somehost] => {"changed": true, "cmd": "./blah.sh", "stdout": "some output with large text here and lots of new lines"}

**Comment by mpdehaan** [comment]
Hi,

This sounds like an interesting idea.

We'd like to have it discussed a bit with the larger group to see what people's thoughts are.

Can you stop by the ansible development mailing list and we can think about how this might work and what the implications might be?

Initially I don't think I would want to make things configurable per task, but maybe even use something structured (I'm not sure if it's YAML) by default as a config option, and maybe it's that way by default, I'm not sure yet.

But yes, I think we should explore this.

Link to the mailing list:  https://groups.google.com/forum/#!forum/ansible-devel

Thanks!

**Comment by dustymabe** [comment]
Did a mailing list discussion about this ever take place? If so is there a link to it and maybe even a summary?

**Comment by dustymabe** [comment]
Also FYI: this looks similar to https://github.com/ansible/ansible-modules-core/issues/1075

**Comment by cliffano** [comment]
@dustymabe Yes it's similar to 1075, based on the comments on the plugin gist https://gist.github.com/cliffano/9868180 and my blog post http://blog.cliffano.com/2014/04/06/human-readable-ansible-playbook-log-output-using-callback-plugin/, it is clearly something that lots of users want in core.

The discussion didn't take place on the mailing list and unfortunately I was busy with other things that time soon after.

Closing this issue in favour of 1075.
