### ISSUE TITLE
install with pip missing modules

### ISSUE THREAD

**Issue by mixmastamyk** [ansible/ansible#847]
I installed ansible .6 with pip on Ubuntu, but it can't find the command modules:

```
sudo pip install https://github.com/downloads/ansible/ansible/ansible-0.6.tar.gz
```

Looks like they are installed via make install, but it doesn't get run.  I had to download and unpack them myself manually.

```
xxxxx | FAILED => module command not found in /usr/share/ansible
```

I don't understand why they are supposed to be in /usr/share, but rather than installing them to there manually to get lost, letting pip install them in dist-packages with everything else automatically seems friendlier.  Should make the getting started page a lot shorter as well.

**Comment by mpdehaan** [comment]
Ansible is not meant to be installed with pip because it is a full application and not a library.

There are various issues with older issues of setup tools on older platforms that prevent doing this, namely the 'extra_files' part doesn't work on old platforms.    If you can fix this with a pull request and verify that works on RHEL 5 (with will require a python 2.6 install from EPEL, BTW), be my guest.

**Comment by mixmastamyk** [comment]
> Ansible is not meant to be installed with pip because it is a full application and not a library.

pip (and predecessors) can install applications... fabric for example works.  And installing ansible with pip works just fine, with one exception...  one folder of modules has been forgotten.  Should be a simple matter to include it.  I'll give it a try.

It should also be cross platform, I don't use rhel but don't anticipate problems.  Could you point out where the code is to locate the modules?

**Comment by mpdehaan** [comment]
code shouldn't have to change, what you are talking about is probably a change to setup.py

**Comment by mixmastamyk** [comment]
Ok, I think I have it working.  I had to give up on using git though, couldn't get my changes to push to server.

I had to:
1. move the library folder to lib/ansible/library
2. make it a package, create **init**.py
3. rename modules to .py
4. patch:
- lib/ansible/constants.py  - change default path
- lib/ansible/runner/**init**.py - look for .py
- setup.py - add library package.

And the result:

```
> ansible all -i ./ansible_hosts.txt -a "w" -u username -k 
SSH password: 
myhost | success | rc=0 >>
00:23:52 up 59 min,  2 users,  load average: 0.26, 0.18, 0.16
USER     TTY      FROM              LOGIN@   IDLE   JCPU   PCPU WHAT
username tty1                      23:27   54:39   0.89s  0.83s -bash
username pts/0    192.168.2.103    00:23    0.00s  0.09s  0.00s w
```

now how to attach a file?

**Comment by mpdehaan** [comment]
Gave up on using git?   It's easy, you can do it :)

https://help.github.com/articles/using-pull-requests/

We are not going to rename modules to *.py or make a package -- libraries are NOT exclusively python.  That's what extra_files is for, and bugs with extra_files is why we don't do it.

**Comment by mixmastamyk** [comment]
Mailed an archive with my changes to the gmail address in the code.

**Comment by mpdehaan** [comment]
Yeah, appreciate it, but I don't take tar balls, everybody has to follow the same process.   Also see previous comment -- renaming things as ".py" isn't an option, and we _REALLY_ have to make sure things install fine on Enterprise Linux 5 as well as recent Linux.   (These folks get python2.6 from EPEL).

**Comment by mixmastamyk** [comment]
I don't use git, but rather hg, but hg-git won't push.  There is a explanation here but I don't understand it:  https://github.com/schacon/hg-git/issues/61

Hmm, that would have been nice to know beforehand, but still... there could be more than one place for modules, perhaps a real path?

**Comment by mpdehaan** [comment]
yeah, you should use git.  I have to use hg at work.  It's only fair :)  

--module-path already exists, it takes multiple paths.

**Comment by mixmastamyk** [comment]
I'm reasonably sure all these requirements could be met with few clever lines of python and a bit of positive thinking.  If rhel can't be fixed, the existing installation shouldn't need to be harmed.

Done right a pip-based install can work just about everywhere, even OSX and Windows, removing roadblocks and opening up possibilities for ansible as well as its user base tremendously.  In a larger sense, it's not good enough to just be open source these days.  User friendliness (including installation) is also a requirement.

p.s.  the setup.py directive from the docs I can find appears to be data_files.

**Comment by mpdehaan** [comment]
We are getting quite a lot of traction in lots of places, don't assume that
everyone is just trying pip or unwilling to read instructions -- pip
targets _python developers_ who are a very small cross section of the
possible user base.

Anyway, show me something that doesn't break the RPM and where "make
install" still works on RHEL 5 platforms, and I'll consider it.    That
must continue to work everywhere.

**Comment by cnf** [comment]
[Ansible can be installed via “pip”, the Python package manager.](http://docs.ansible.com/intro_installation.html#latest-releases-via-pip)

What do you mean "Ansible is not meant to be installed with pip because it is a full application and not a library." I find this quite important...

**Comment by mixmastamyk** [comment]
At the time I wrote this bug, it couldn't be, or the package there didn't work.  At a later date another developer apparently fixed the issue.  
At the point above, mpd may not have completely understood the issue and was being difficult.

**Comment by cnf** [comment]
I also noted how old this issue is after I posted. I seem to be having the same problem again with 1.7.2 though.

**Comment by Kahn** [comment]
This issue seems to have cropped up again in 2.0.0 after installing with "pip install https://github.com/ansible/ansible/archive/v1_last.zip". I can only assume this is because of the modules split away from core.

```
swilson:ansible swilson$ ansible --version
ansible 2.0.0
  configured module search path = None
```

Time to drop pip from the install methods docs?

**Comment by sivel** [comment]
pip is a sufficient way to install Ansible.  However you should not use github zip files.  Only install from pypi or releases.ansible.com

Otherwise you can install the repo directly via pip which handles submodules:

`pip install git+https://github.com/ansible/ansible.git@v1_last#egg=ansible`
