### ISSUE TITLE
ansible 0.7 ssh layer fails with dropbear 0.48.1-2

### ISSUE THREAD

**Issue by SleeplessAnnoyedNerd** [ansible/ansible#848]
Well,  I'm not sure if it is ansible "fault" or just an odd behaviour of dropbear 0.48.1-2 (on Debian). But if one uses ansible with ssh layer (`ANSIBLE_TRANSPORT=ssh`) it fails like so:

```
$ ansible ahost -m ping
wd18s | FAILED => Traceback (most recent call last):
  File "/Users/dietmar/Applications/ansible/lib/ansible/runner/__init__.py", line 448, in _executor
    exec_rc = self._executor_internal(host)
  File "/Users/dietmar/Applications/ansible/lib/ansible/runner/__init__.py", line 494, in _executor_internal
    return self._executor_internal_inner(host, inject, port)
  File "/Users/dietmar/Applications/ansible/lib/ansible/runner/__init__.py", line 595, in _executor_internal_inner
    self._delete_remote_files(conn, tmp)
  File "/Users/dietmar/Applications/ansible/lib/ansible/runner/__init__.py", line 178, in _delete_remote_files
    raise Exception("not going to happen")
Exception: not going to happen
```

Further investigation showed that _nothing_ is read from stdout (it's always empty). On the server side one finds following log entry:

```
Aug 11 10:59:17 ahost dropbear[22165]: exit after auth (root): Disconnect received
```

After some deep thinking ( :) ) I found the solution:

```
diff --git a/lib/ansible/runner/connection/ssh.py b/lib/ansible/runner/connection/ssh.py
index 3f20a54..c7532c9 100644
--- a/lib/ansible/runner/connection/ssh.py
+++ b/lib/ansible/runner/connection/ssh.py
@@ -96,12 +96,12 @@ class SSHConnection(object):
                                  stdout=subprocess.PIPE, stderr=subprocess.STDOUT)

         # We can't use p.communicate here because the ControlMaster may have stdout open as well
-        p.stdin.close()
         stdout = ''
         while p.poll() is None:
             rfd, wfd, efd = select.select([p.stdout], [], [p.stdout], 1)
             if p.stdout in rfd:
                 stdout += os.read(p.stdout.fileno(), 1024)
+        p.stdin.close()
         # older versions of ssh generate this error which we ignore
         stdout=stdout.replace("tcgetattr: Invalid argument\n", "")
         # suppress Ubuntu 10.04/12.04 error on -tt option
```

At least for me it doesn't seem to break anything (means still working for OpenSSH sshd). And somehow I feel that it's more correct that way anyways. But YMMV.

Interestingly dropbear 0.45-2sarge0 doesn't have that problem. (So, it's dropbear's fault. ;) )

**Comment by mpdehaan** [comment]
This doesn't seem to hurt anything, so you can send a pull request for this if you like.

**Comment by arunthampi** [comment]
I keep getting this error in v0.7.1 as well as in the devel branch, it is intermittent but very frustrating :(

**Comment by mpdehaan** [comment]
I've replied on the list and backported a fix on the 0.7 release branch (also tagged 0.7.2).

I apologize for the uselessness of the original error message.  It was originally written as a development safeguard to prevent a super-early version of Ansible from deleting "/" and wasn't something I expected a user to see.  Thankfully, it did it's job.

Check out the backport and let me know if it works for you.

**Comment by velniukas** [comment]
This is still broken intermittently on the 0.7.2 release and devel branches- when running on cygwin. Using openssh

**Comment by mpdehaan** [comment]
@velniukas -- when you say running on cygwin, do you mean trying to contact
a Windows host or running from one?   Please run the same md command you
get when running -v -v -v over ssh and run it manually to see what kind of
output you are getting.
Most of our users are running from macs or Linux machines, so you may wish
to just install ansible on a head management node and avoid the cygwin
route.

**Comment by velniukas** [comment]
Running from cygwin - contacting a RHEL 5.5 host. Unfortunately its for an
enterprise, so windows is part of their toolchain. But I'll raise the point.

**Comment by mpdehaan** [comment]
Roger that.  One sec. working on a workaround that will also dump the error
so you can report it to me.

**Comment by mpdehaan** [comment]
Ah, sorry, I'm confusing tickets.  I'm thinking of the remote md5 error.   Sorry for confusion.

@velniukas please see if you can help debug and also that 0.7.2 is installed correctly, as this fix should have resolved the unicode problem already.   You may also wish to switch connection types between SSH and paramiko.
