### ISSUE TITLE
The async property of a task doesn't seem to evaluate jinja2 tags when using a loop

### ISSUE THREAD

**Issue by AntelopeSalad** [ansible/ansible#8499]
##### Issue Type:

Bug report
##### Ansible Version:

devel (current)
##### Environment:

Debian Wheezy
##### Summary:

This is related to a previous commit that half way fixed it: https://github.com/ansible/ansible/commit/e19ed3424d849fd3c0b36503014a99704bf7d574

The error persists when trying to access `item` using `with_items` instead of a non-looped variable.

**Possibly related issue but no steps included**:
If you remove the variables and try to use an async property using `with_items` then ansible will "red text" error you with: lookup plugins (with_*) cannot be used with async tasks.
##### Steps To Reproduce:

```
# defaults/main.yml
async_services:
  - name: 'dummyproc'
    async: 30

# foo.yml

---

- hosts: all
  remote_user: root

  tasks:

  - name: Restart a few async services
    service: name={{ item.name }} state='restarted'
    async: '{{ item.async | default(45) }}'
    poll: 0
    with_items: async_services
```
##### Expected Results:

The task would work with an async value of 30 seconds.
##### Actual Results:

Python donkey punched me in the face.

```
Traceback (most recent call last):
  File "/home/nick/src/tmp/ansible/bin/ansible-playbook", line 309, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/nick/src/tmp/ansible/bin/ansible-playbook", line 249, in main
    pb.run()
  File "/home/nick/src/tmp/ansible/lib/ansible/playbook/__init__.py", line 293, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/home/nick/src/tmp/ansible/lib/ansible/playbook/play.py", line 153, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/home/nick/src/tmp/ansible/lib/ansible/playbook/play.py", line 589, in _load_tasks
    loaded = self._load_tasks(data, mv, default_vars, included_sudo_vars, list(included_additional_conditions), original_file=include_filename, role_name=new_role)
  File "/home/nick/src/tmp/ansible/lib/ansible/playbook/play.py", line 589, in _load_tasks
    loaded = self._load_tasks(data, mv, default_vars, included_sudo_vars, list(included_additional_conditions), original_file=include_filename, role_name=new_role)
  File "/home/nick/src/tmp/ansible/lib/ansible/playbook/play.py", line 597, in _load_tasks
    role_name=role_name
  File "/home/nick/src/tmp/ansible/lib/ansible/playbook/task.py", line 213, in __init__
    self.async_seconds = int(self.async_seconds)
ValueError: invalid literal for int() with base 10: '{{ item.async }}'
```

**Comment by jimi-c** [comment]
Re-opening, as this is still an issue when using with_ loops and `{{item}}`.

**Comment by AntelopeSalad** [comment]
I updated the original ticket's contents along with the title.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0).

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
