### ISSUE TITLE
utils._clean_data extremely slow when handling large strings

### ISSUE THREAD

**Issue by leth** [ansible/ansible#8511]
##### Issue Type:

Bug Report
##### Ansible Version:

devel branch HEAD
##### Environment:

Ubuntu 14.04 and OSX
##### Summary:

Unarchive task seems to hang.
Looking at a process listing, the tar command finishes, and then the ansible task process stays pegged at 100% CPU
##### Steps To Reproduce:
1. Create large tar archive.
   (Listing of our tar file contents: https://gist.github.com/leth/bc059d52be90b1ef9e14 )
2. unarchive tar using ansible
3. Watch
##### Expected Results:

I'd expect this to complete within reasonable time
##### Actual Results:

This task does not ever seem to complete

**Comment by mpdehaan** [comment]
# Information Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

We have some questions we'd like to know about before we can get this request queued up.   If you can help answer them, we'd greatly appreciate it:
- when you say devel branch head, please include the output of ansible --version
- how long did you wait?
- the code in question moves the file and then is executing the GNU toolchain tools here, so this seems curious to us that it would hang.  See https://github.com/ansible/ansible/blob/devel/library/files/unarchive
  - If you have any python development skills, some help debugging the problem in your environment may be useful, as our integration tests for the unarchive module are not detecting problems at this time.  

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively
we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!  
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgot about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which is very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by leth** [comment]
> when you say devel branch head, please include the output of ansible --version

`ansible 1.8 (devel d4cedfc7f1) last updated 2014/08/08 14:54:24 (GMT +100)`

> how long did you wait?

Our jenkins server has hung on this step for hours. I've not waited that long locally.

> the code in question moves the file and then is executing the GNU toolchain tools here, so this seems curious to us that it would hang. See https://github.com/ansible/ansible/blob/devel/library/files/unarchive
> If you have any python development skills, some help debugging the problem in your environment may be useful, as our integration tests for the unarchive module are not detecting problems at this time.

I've tried running it locally using the module development tools, and have narrowed it down somewhat:

It **does not** occur when I run it from:

```
hacking/test-module -m library/files/unarchive -a "src=/tmp/testmanager_modules.tar.bz2 dest=/tmp/testmanager copy=no"
```

It **does** occur when I run it from:

```
ansible localhost -vv -c local -i 'localhost,' -m unarchive -a "src=/tmp/testmanager_modules.tar.bz2 dest=/tmp/testmanager copy=no"
```

**Comment by leth** [comment]
I've stuck it under a debugger and it's spending all of its time in the _clean_data utils, trying to remove jinja2 tags from the stdout.
Incidentally there are 4074207 characters in stdout.

Perhaps more efficient string manipulation code is needed.

**Comment by leth** [comment]
[Changing to cStringIO](https://gist.github.com/leth/842a373fcf1ec8a4ca9b) results in a considerable speed improvement on this call:

```
ansible.utils._clean_data('{{ }}'*1000000, from_remote=True)
```

However I suspect an approach which delegated the string parsing to c-land (e.g. through parser or regex libraries) would be a lot faster than parsing the whole string character-by-character in python.

**Comment by jimi-c** [comment]
@leth could you send us that in a PR? Thanks!

**Comment by leth** [comment]
I think other approaches would be faster and better in the long run; I'll do some benchmarking.

As an aside; why are jinja2 templates removed from the output like this? If I understand the code correctly it's replacing tags with comments. Would it not be simpler to disable template interpolation, or use a jinja2 API to excape the whole string?

**Comment by jimi-c** [comment]
@leth this function is used to clean jinja2 out of data that may be returned from external sources, such as remote custom facts or from lookups. This data may be stored in a variable that is then run through the templating engine, which can lead to unsafe evaluations, so we strip them out.

**Comment by leth** [comment]
Okay. Would escaping them be an acceptable alternative to converting them into comments?

## I'm hoping jinja might have an optimised function for escaping strings. 

Sent from my phone. Please excuse my brevity.

**Comment by leth** [comment]
I'll be posting a PR for this shortly; I've got a new regex-based version which is super fast.

[Here's gist showing the benchmarking stats](https://gist.github.com/leth/1f2ba2d6b961fabe5d60).

I wouldn't be surprised if this speeds up ansible noticably.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

The above commit in #8536 has been merged in, and should resolve this problem for you. This will be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
