### ISSUE TITLE
Variables defined in a role aren't evaluated in the module command/shell 

### ISSUE THREAD

**Issue by guillaumevincent** [ansible/ansible#8514]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.7
##### Environment:

Running from OS X version 10.9.4 and managing: Ubuntu 14.04
##### Summary:

The variables defined in a role aren't evaluated in the module command or module shell.
##### Steps To Reproduce:

Create a simple role with `vars/main.yml':

```

---
commandFoo: "NODE_ENV=production echo"
```

Create a simple task in `tasks/main.yml':

```

---
- command: "{{ commandFoo }}"
```

or

```

---
- shell: "{{ commandFoo }}"
```
##### Expected Results:

TASK: [bug | command echo] ***************************************************\* 
changed: [hostname]
##### Actual Results:

TASK: [bug | command NODE_ENV=production echo] *******************************\* 
fatal: [hostname] => A variable inserted a new parameter into the module args. Be sure to quote variables if they contain equal signs (for example: "{{var}}").

**Comment by Jmainguy** [comment]
I tested on latest devel, shell works fine, command returns 

failed: [sl.soh.re] => {"cmd": "NODE_ENV=production echo", "failed": true, "rc": 2}
msg: [Errno 2] No such file or directory

I am not sure if this is how command should function or not.

**Comment by mpdehaan** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:
- variables for shell tasks aren't evaluated in roles

However, however what is happening is that:
- ansible is detecting you are adding equal signs to a shell command via a variable
- it is protecting you from possible command injection of arguments

We would suggest:
- not passing environment variables on the shell line
- instead using the environment keyword as per http://docs.ansible.com/playbooks_environment.html
- if you ever have to pass a shell argument containing an equals sign, consider "{{ foo | quote }}", but this is different from the environment suggestion above.

In the future, this might be a topic more well suited for the user list, and you can also ask on the list if you would like more clarification:
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
