### ISSUE TITLE
ipv4 in facts changes between dict and array on different platforms

### ISSUE THREAD

**Issue by jefferai** [ansible/ansible#8519]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

OSX 10.9 and Ubuntu 14.04
##### Summary:

I've been finding that the "ipv4" value is not predictable across platforms. From "ansible -m setup localhost" on an OSX machine:

```
"ansible_utun1": {
            "device": "utun1",
            "flags": [
                "UP",
                "POINTOPOINT",
                "RUNNING",
                "MULTICAST"
            ],
            "ipv4": [
                {
                    "address": "172.19.41.132",
                    "broadcast": "0xffffffff",
                    "netmask": "172.19.41.132",
                    "network": "172.19.41.132"
                }
            ],
            "ipv6": [],
```

Notice that `ipv4` is an array, even with only one element. `ipv6` is an empty array. Note that `ipv6` always exists even if empty.

On a Linux box:

```
"ansible_br0": {
            "active": true,
            "device": "br0",
            "id": "8000.6805ca0e7341",
            "interfaces": [
                "p4p1"
            ],
            "ipv4": {
                "address": "10.88.5.227",
                "netmask": "255.255.248.0",
                "network": "10.88.0.0"
            },
            "ipv6": [
                {
                    "address": "fe80::6a05:caff:fe0e:7341",
                    "prefix": "64",
                    "scope": "link"
                }
            ],

    ...........

"ansible_virbr0": {
            "active": false,
            "device": "virbr0",
            "id": "8000.000000000000",
            "interfaces": [],
            "ipv4": {
                "address": "192.168.122.1",
                "netmask": "255.255.255.0",
                "network": "192.168.122.0"
            },
            "macaddress": "3e:6a:6d:b3:31:90",
```

Note that `ipv4` is not an array, but a dict. If there is no IPv6 address, `ipv6` does not exist.

Would it be possible to make this behavior more predictable? I'm less concerned about the missing `ipv6` entries on Linux, but swapping between a dict and array between Linux and OSX requires handling that possibility in my code, and it's unclear why the difference should exist to begin with.
##### Steps To Reproduce:

Run the setup module.
##### Expected Results:

`ipv4` and `ipv6` behave the same across platforms.
##### Actual Results:

See above output.

**Comment by mpdehaan** [comment]
Definitely agree, but we need to be careful about breaking playbooks here.

I like the idea that things are always lists when there can be more than one.

**Comment by jefferai** [comment]
I'm going to add another thing I just found here, but feel free to tell me to put it in a different issue:

`mtu` is a string on OSX and an int on Linux.

**Comment by bcoca** [comment]
I'm going to close this ticket as too many people depend on the formats and I don't believe we can change them at this point.
