### ISSUE TITLE
rax_files_objects module fails when deploying to vagrant box

### ISSUE THREAD

**Issue by benkantor** [ansible/ansible#8523]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

I'm running Ansible on Ubuntu 14.04

I'm deploying to a vagrant box running Centos 6.5
##### Summary:

I'm encountering a 'failed to parse' error while trying to use the rax_files_objects module to download a 500MB sql dump to a vagrant box. When I run the same playbook on a non-vagrant Centos server, I encounter no problems. I've also noticed that this problem only occurs with large files. I was able to get the module to work when downloading a small text file to the box. I also have no problems manually downloading the file to the box using the Rackspace API.
##### Steps To Reproduce:
1. Upload a file of at least 250MB to Rackspace Cloud Files.
2. Launch a vagrant box using a Centos 6.5 image
3. Run a playbook with the following task:

Code: 

```
- name: upload sql dump
  rax_files_objects:
    container: staging
    src: dump.sql
    dest: ~/.
    username: "{{ rackspace_username }}"
    api_key: "{{ rackspace_apikey }}"
```
##### Expected Results:

```
 __________________________________________
< TASK: databases-master | upload sql dump >
 ------------------------------------------
  \
   \   \_\_    _/_/
    \      \__/
           (oo)\_______
           (__)\       )\/\
               ||----w |
               ||     ||


<127.0.0.1> REMOTE_MODULE rax_files_objects container=staging api_key=################ username=myUsername src=dump.sql dest='~/.'
changed: [database] => {"changed": true, "container": "staging", "msg": "1 objects downloaded to /home/vagrant", "requested_downloaded": ["dump.sql"], "success": true}
```
##### Actual Results:

```
__________________________________________
< TASK: databases-master | upload sql dump >
------------------------------------------
  \
   \   \_\_    _/_/
    \      \__/
           (oo)\_______
           (__)\       )\/\
               ||----w |
               ||     ||


 <127.0.0.1> REMOTE_MODULE rax_files_objects container=staging api_key=#################### username=myUsername src=dump.sql  dest='~/.'
fatal: [database] => failed to parse: /home/vagrant/.ansible/tmp/ansible-tmp-1407508861.64-251274921645507/rax_files_objects:332: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
   module.fail_json(msg=e.message)
{"msg": "", "failed": true}

FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
# Should This Be Filed Elsewhere?

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us.

This appears to be something that should be filed against another project or bug tracker, and let us explain our reasons for thinking this:

```
* The Vagrant ansible plugin is part of the Vagrant project, not ansible
* It may be doing some interesting things with the way it's doing communications, though this is unclear
* Some more debugging may be required on your end to help isolate this as multiple projects are involved.
```

If you can stop by the tracker or forum for one of those projects, we'd appreciate it.

Should you still wish to discuss things further, or if you disagree with our thought process, please stop by one of our two mailing lists:
- https://groups.google.com/forum/#!forum/ansible-project
- https://groups.google.com/forum/#!forum/ansible-devel

We'd be happy to discuss things.

Thank you once again!

**Comment by angstwad** [comment]
@mpdehaan   The problem is that the Python output can't be parsed by the YAML parser because of the ":" in the string.. I think.  I think it can be solved by escaping/quoting.
