### ISSUE TITLE
GitHub and Ansigle-galaxy markdown incompatibility

### ISSUE THREAD

**Issue by ihrwein** [ansible/ansible#8540]
When I tried to "upload" my role to ansible-galaxy, I saw some differences between GitHub's and ansible-galaxy's markdown rendering.

I used some indented YAML code blocks in an enumeration. GitHub rendered them fine, but ansible-galaxy rendered the whole block into one line.

I just suspect these are the cause of the problem, because I managed to solve it with https://github.com/ihrwein/ansible-syslog-ng/commit/bdefe16e7c9ca3165875965e2b0781c9e6956027.

**Comment by mpdehaan** [comment]
Hi @ihrwein,

We're aware of this one and are tracking this in a seperate issue tracker as galaxy.ansible.com does not have one at the moment, and some improvements are slated in the near future.

Thank you for the report!
