### ISSUE TITLE
bug: msg: unsupported parameter for module: recurse

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#8551]
##### Issue Type:

“Bug Report”
##### Ansible Version:

1.7.0 and devel branch
##### Environment:

Running on Ubuntu 14.04 against CentOS 6.5
##### Summary:

IMHO there is a split off between documentation and functionality in the copy module: In commit https://github.com/ansible/ansible/commit/cc1d1ad0420a53de21fef9e521355a46682cf930 @mpdehaan added `recurse` but running copy task with `recurse=yes` prints error: 

```
msg: unsupported parameter for module: recurse
```

**Comment by mpdehaan** [comment]
You're correct, I'll remove this, the way recursion works is if source is a directory.
