### ISSUE TITLE
ansible running handler from a different role

### ISSUE THREAD

**Issue by jfchevrette** [ansible/ansible#8553]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.0
##### Environment:

Running from OSX, managing CentOS/RHEL servers
##### Summary:

Ansible will run a handler from a different role if it has the same name and if this role is parsed first (ansible seem to load roles alphabetically?)
##### Steps To Reproduce:

https://gist.github.com/jfchevrette/b8f5edcd94b32284d53f

Basically I created two test roles: first and second. Each has one task that ensures a file content is epoch (wanted to ensure the task was in a changed state everytime I run the test playbook). 

In my playbook, I set roles with a tag. (I'm pretty sure this is a valid/supported syntax, is it?)

If I run the playbook and specify the 'first' tag, the role task and handler are executed.
If I run it with the 'second' tag, the second task is executed and the 'first' role handler is executed.
##### Expected Results:

When I set a tag on a role, I only expect the tasks from that role to execute. I also expect the same for the handlers.

**Comment by jfchevrette** [comment]
If I run with no tags, only the 'first' role handler is executed. I get that both handlers have the same name but since they are under different roles I would expect both to run as they may both be useful.

For instance in my example I would expect this:

```
NOTIFIED: [first | my notify] *************************************************

NOTIFIED: [second | my notify] *************************************************
```

**Comment by mpdehaan** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:
- handlers will run from different roles

However, however what is happening is that:
- handlers are a global namespace
- it's possible for handlers defined in one role to be shared by many roles
- it is possible to define a handler twice without problem, for instance "restart apache", and the system will take the latest definition

We would suggest:
- handlers be named with unique names

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
