### ISSUE TITLE
Allow handler to be executed even if playbook run multiple times

### ISSUE THREAD

**Issue by asmartin** [ansible/ansible#8559]
##### Summary:

I would like the ability to have a dependent role's status re-evaluated each time it is called. That way, if a dependent role is called multiple times (e.g by different dependent roles), it won't get skipped.
##### Steps To Reproduce:

When developing a set of roles for apache, I've run into this issue:
https://groups.google.com/forum/#!topic/Ansible-project/xcjUnfFKK6A

The basic setup of these roles is 4 different roles for apache:
apache2 - this is the base role that contains the apache2 config, installs and configures apache
apache2-php - this role adds mod_php, php.ini, etc
apache2-ssl - this role adds an SSL certificate and forces all traffic to SSL
apache2-all - includes all of the above

This is nice because some servers only need a subset of this functionality, so I can just include the appropriate features as needed. I've bundled these together using role dependencies, e.g apache2-php/meta/main.yml contains the following:

```
dependencies:
  - { role: apache2 }
```

This is nice because then I need to only maintain the apache template file in a single location, inside of the apache2 role, and just set variables in the other roles if I want to add/change content on it.

This works well, except that in order for the variables to be overridden and included together at the correct point, I have this situation in the apache2-ssl meta/main.yml files:

```
dependencies:
  - { role: apache2-php, when: include_php == True }
  - { role: apache2, when: include_php == False }
```

I would like to be able to add a variable that allows resetting the dependent role's status, e.g

```
dependencies:
  - { role: apache2-php, when: include_php == True }
  - { role: apache2, reset_dependents: True, when: include_php == False }
```
##### Expected Results:

The problem is that if include_php == False, then the first role dependency (apache2-php), is skipped. What seems to be happening is it recursively marks everything in the apache2 role as skipped as well, including the handler I use to reload apache after updating the config. Then, when it arrives at the second role dependency (apache2), it skips executing any of the handlers in the apache2 role even if they are NOTIFIED because they were marked as skipped previously. 

Would it be possible to add a variable that would reset a role so that whether or not it should be skipped is evaluated each time it is called (similar to the existing allow_duplicates variable)?
##### Actual Results:

The apache2 handler that reloads the apache config is skipped (when called via the apache2 depedent role above), even if there are changes because it was already marked as skipped by the dependent apache2-php call (which was skipped).

**Comment by mpdehaan** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:
- you would like to be able to call duplicate roles

However, however what is happening is that:
- there is a role duplicates feature you might not know about, which is covered as "allow_duplicates" here:  http://docs.ansible.com/playbooks_roles.html#role-dependencies

We would suggest:
- you read up on the allow_duplicates above
- if you still think there's a feature here, we'd like to discuss it further, and suggest stopping by the ansible-project list below, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
