### ISSUE TITLE
msg: No Package matching 'zeromq3' found available, installed or upd

### ISSUE THREAD

**Issue by Ssan79** [ansible/ansible#8567]
##### Issue Type:

 “Bug Report”
##### Ansible Version:

1.4.10
##### Environment:

RHEL 6.4
##### Summary:

while Installing ansible tower 1.4.10 ended up with msg: No Package matching 'zeromq3' found available, installed or updated 

FATAL: all hosts have already failed -- aborting
##### Steps To Reproduce:

But O/S had been installed with Zeromq3 and its depended libraries
##### Expected Results:

Ansible Towers installation done 
##### Actual Results:

failed: [127.0.0.1] => (item=Django14,httpd,mod_wsgi,mod_ssl,libselinux-python,policycoreutils-python,postgresql-server,python-psycopg2,python-setuptools,python-ldap,setools-libs-python,supervisor,git,subversion,mercurial,yum-utils,rabbitmq-server,zeromq3,python-zmq) => {"changed": false, "failed": true, "item": "Django14,httpd,mod_wsgi,mod_ssl,libselinux-python,policycoreutils-python,postgresql-server,python-psycopg2,python-setuptools,python-ldap,setools-libs-python,supervisor,git,subversion,mercurial,yum-utils,rabbitmq-server,zeromq3,python-zmq", "rc": 0, "results": ["Django14-1.4.13-1.el6.noarch providing Django14 is already installed", "httpd-2.2.15-28.el6_4.x86_64 providing httpd is already installed", "mod_wsgi-3.2-3.el6.x86_64 providing mod_wsgi is already installed", "mod_ssl-2.2.15-28.el6_4.x86_64 providing mod_ssl is already installed", "libselinux-python-2.0.94-5.3.el6_4.1.x86_64 providing libselinux-python is already installed", "policycoreutils-python-2.0.83-19.30.el6.x86_64 providing policycoreutils-python is already installed", "postgresql-server-8.4.13-1.el6_3.x86_64 providing postgresql-server is already installed", "python-psycopg2-2.0.14-2.el6.x86_64 providing python-psycopg2 is already installed", "python-setuptools-0.6.10-3.el6.noarch providing python-setuptools is already installed", "python-ldap-2.3.10-1.el6.x86_64 providing python-ldap is already installed", "setools-libs-python-3.3.7-4.el6.x86_64 providing setools-libs-python is already installed", "supervisor-2.1-8.el6.noarch providing supervisor is already installed", "git-1.7.1-3.el6_4.1.x86_64 providing git is already installed", "subversion-1.6.11-9.el6_4.x86_64 providing subversion is already installed", "mercurial-1.4-3.el6.x86_64 providing mercurial is already installed", "yum-utils-1.1.30-14.el6.noarch providing yum-utils is already installed", "rabbitmq-server-3.3.4-1.noarch providing rabbitmq-server is already installed"]}
msg: No Package matching 'zeromq3' found available, installed or updated

FATAL: all hosts have already failed -- aborting

**Comment by mpdehaan** [comment]
Hi, for tower questions, please email support@ansible.com and we'd be happy to help you out.

This is the bug tracker for the main Ansible project, and not tower.

Thanks!
