### ISSUE TITLE
homebrew_cask seems to ignore $HOMEBREW_CASK_OPTS

### ISSUE THREAD

**Issue by dixhuit** [ansible/ansible#8571]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

Mac OS 10.9.4
##### Summary:

homebrew_cask seems to ignore `--appdir` if set in $HOMEBREW_CASK_OPTS.
##### Steps To Reproduce:

Change the directory that Cask app links are created in using:

```
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
```

I've tried setting this variable both via Ansible and before running any playbooks. It doesn't seem to make a difference.

Then run a playbook that installs an app via Cask. E.g:

```
homebrew_cask: name=moom
```

Testing this just using a shell script on the same system works as expected.

NOTE: I'm getting these results testing a playbook that's designed to provision the system it's running on (`connection: local`).
##### Expected Results:

App links created in /Applications (and only there).
##### Actual Results:

App links are created in ~/Applications (and only there). This is the default for Cask.

**Comment by mpdehaan** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:
- the homebrew module doesn't pay attention to a particular environment variable

However, however what is happening is that:
- ansible is a systems management application designed for centralized management
- as such it does not trust user environments that may be inconsistent between 500 different systems

We would suggest:
- the arguments be passed to the cask module
- where something can't be passed to the cask module, use the environment keyword in ansible mentioned here:  http://docs.ansible.com/playbooks_environment.html
  - if you feel the above doesn't solve your problem, stop by the list at the address below

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by ghost** [comment]
OK, thanks. Have opted for `shell: brew cask install moom --appdir=/Applications` for now until #8303 is merged.
