### ISSUE TITLE
Feature Request - add CIDR format netmask info to ansible facts

### ISSUE THREAD

**Issue by edrozenberg** [ansible/ansible#8584]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.8
##### Environment:

Mac OSX 10.9.4 controlling Slackware hosts
##### Summary:

It would be great to have netmask facts also available in CIDR format (ex. "28") in addition to the current dotted format (255.255.x.x). Various config files (such as the Postgres pg_hba.conf) require netmasks in CIDR format.

For now I am using a custom Jinja filter containing the code below but it would certainly be much cleaner and easily available to everyone as standard facts. I looked at the Python code for the facts module but first would need to learn python to be able to submit a pull request for changes there.

```
# Adapted from:
# http://code.activestate.com/recipes/576483-convert-subnetmask-from-cidr-notation-to-dotdecima/

# Convert a dotted (xxx.xxx.xxx.xxx) netmask to CIDR bits (xx) notation
def netmask_to_cidr(netmask):
    return sum([bin(int(x)).count('1') for x in netmask.split('.')])

class FilterModule(object):
    ''' utility filters for operating on ip netmasks '''

    def filters(self):
        return {
            'netmask_to_cidr' : netmask_to_cidr
        }
```
##### Steps To Reproduce:

Get the list of ansible facts from a host. 
##### Expected Results:

Would be great to have these new CIDR format netmask facts added to the standard facts.
##### Actual Results:

There are no CIDR format netmask facts currently.

**Comment by mpdehaan** [comment]
I think I'd be open to a Jinja2 filter to do the conversions but would not want to double up on the fact info, since that creates a lot of extra data just to expose a different format.

How about stopping by ansible-devel so we can discuss?

Thanks!

**Comment by edrozenberg** [comment]
Thanks Michael, I've opened a discussion -
https://groups.google.com/forum/#!topic/ansible-devel/vyXjlsHYCQ8

**Comment by jtognazzi** [comment]
As Michael is open to this filter idea, can you pursue and submit a pull request ?
