### ISSUE TITLE
windows powershell module: Failure to build module command for unicode commands

### ISSUE THREAD

**Issue by brdo** [ansible/ansible#8588]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel d1344ec85d) last updated 2014/08/12 11:19:50 (GMT -700)
##### Environment:

Ubuntu 10.04
##### Summary:

ansible/runner/shell_plugins/powershell.py::ShellModule.build_module_command uses shlex.split on the command to split it into its parts, however this causes additional \x00 characters to be inserted throughout string when the command is unicode and not string.  Tracing the failure up through Runner._execute_command it seems that this happens when the module_name is a unicode object and then the unicode type is propagated to from there.

Ultimately this causes problems for PowerShell when it decodes the string and tries to execute the resulting command.

Example: (Notice how wrapping str() around the cmd fixes the issue)

> > > cmd
> > > u'some command'
> > > shlex.split(cmd,posix=False)
> > > ['s\x00\x00\x00o\x00\x00\x00m\x00\x00\x00e\x00\x00\x00', '\x00\x00\x00c\x00\x00\x00o\x00\x00\x00m\x00\x00\x00m\x00\x00\x00a\x00\x00\x00n\x00\x00\x00d\x00\x00\x00']
> > > shlex.split(str(cmd),posix=False)
> > > ['some', 'command']
##### Steps To Reproduce:

This happens when I run the win_get_url playbook example provided online, it also happened when I tried to run the win_stats example playbook as well.
# Playbook example
- name: Download earthrise.jpg to 'C:\Users\RandomUser\earthrise.jpg'
  win_get_url:
    url: 'http://www.example.com/earthrise.jpg'
    dest: 'C:\Users\RandomUser\earthrise.jpg'
##### Expected Results:

I expect the winrm runner to successfully execute a remote winrm encoded command on the remote machine.  Here is a successful snippet example with my fix in place.

<192.168.140.92> EXEC PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -File "C:\Users\root\AppData\Local\Temp\ansible-tmp-1407904983-167586716176373\win_get_url.ps1" "C:\Users\root\AppData\Local\Temp\ansible-tmp-1407904983-167586716176373\arguments"
<192.168.140.92> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-EncodedCommand', 'UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABVAG4AcgBlAHMAdAByAGkAYwB0AGUAZAAgAC0ARgBpAGwAZQAgACIAQwA6AFwAVQBzAGUAcgBzAFwAcgBvAG8AdABcAEEAcABwAEQAYQB0AGEAXABMAG8AYwBhAGwAXABUAGUAbQBwAFwAYQBuAHMAaQBiAGwAZQAtAHQAbQBwAC0AMQA0ADAANwA5ADAANAA5ADgAMwAtADEANgA3ADUAOAA2ADcAMQA2ADEANwA2ADMANwAzAFwAXAB3AGkAbgBfAGcAZQB0AF8AdQByAGwALgBwAHMAMQAiACAAIgBDADoAXABVAHMAZQByAHMAXAByAG8AbwB0AFwAQQBwAHAARABhAHQAYQBcAEwAbwBjAGEAbABcAFQAZQBtAHAAXABhAG4AcwBpAGIAbABlAC0AdABtAHAALQAxADQAMAA3ADkAMAA0ADkAOAAzAC0AMQA2ADcANQA4ADYANwAxADYAMQA3ADYAMwA3ADMAXABcAGEAcgBnAHUAbQBlAG4AdABzACIA']
<192.168.140.92> WINRM RESULT <Response code 0, out "{ "changed": t", err "">
changed: [192.168.140.92] => (item=ccs-python.msi) => {"changed": true, "item": "ccs-python.msi", "win_get_url": {"dest": "C:\Users\root\Desktop\ccs-python.msi", "url": "http://10.8.28.11/bamboo/buildrepos/WINDOWS/x86/release/devel/latest-release/ccs-python.msi"}}
##### Actual Results:

Instead the winrm command execution fails, here is a failure snippet.

<192.168.140.92> EXEC PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -File "C:\Users\root\AppData\Local\Temp\ansible-tmp-1407904581-170984505940255\win_stat.ps1" "C:\Users\root\AppData\Local\Temp\ansible-tmp-1407904581-170984505940255\arguments"
<192.168.140.92> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-EncodedCommand', 'UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABVAG4AcgBlAHMAdAByAGkAYwB0AGUAZAAgAC0ARgBpAGwAZQAgACIAQwAAAAAAAAA6AAAAAAAAAFwAAAAAAAAAVQAAAAAAAABzAAAAAAAAAGUAAAAAAAAAcgAAAAAAAABzAAAAAAAAAFwAAAAAAAAAcgAAAAAAAABvAAAAAAAAAG8AAAAAAAAAdAAAAAAAAABcAAAAAAAAAEEAAAAAAAAAcAAAAAAAAABwAAAAAAAAAEQAAAAAAAAAYQAAAAAAAAB0AAAAAAAAAGEAAAAAAAAAXAAAAAAAAABMAAAAAAAAAG8AAAAAAAAAYwAAAAAAAABhAAAAAAAAAGwAAAAAAAAAXAAAAAAAAABUAAAAAAAAAGUAAAAAAAAAbQAAAAAAAABwAAAAAAAAAFwAAAAAAAAAYQAAAAAAAABuAAAAAAAAAHMAAAAAAAAAaQAAAAAAAABiAAAAAAAAAGwAAAAAAAAAZQAAAAAAAAAtAAAAAAAAAHQAAAAAAAAAbQAAAAAAAABwAAAAAAAAAC0AAAAAAAAAMQAAAAAAAAA0AAAAAAAAADAAAAAAAAAANwAAAAAAAAA5AAAAAAAAADAAAAAAAAAANAAAAAAAAAA1AAAAAAAAADgAAAAAAAAAMQAAAAAAAAAtAAAAAAAAADEAAAAAAAAANwAAAAAAAAAwAAAAAAAAADkAAAAAAAAAOAAAAAAAAAA0AAAAAAAAADUAAAAAAAAAMAAAAAAAAAA1AAAAAAAAADkAAAAAAAAANAAAAAAAAAAwAAAAAAAAADIAAAAAAAAANQAAAAAAAAA1AAAAAAAAAFwAAAAAAAAAXAAAAAAAAAB3AAAAAAAAAGkAAAAAAAAAbgAAAAAAAABfAAAAAAAAAHMAAAAAAAAAdAAAAAAAAABhAAAAAAAAAHQAAAAAAAAALgBwAHMAMQAiACAAIgAAAAAAAABDAAAAAAAAADoAAAAAAAAAXAAAAAAAAABVAAAAAAAAAHMAAAAAAAAAZQAAAAAAAAByAAAAAAAAAHMAAAAAAAAAXAAAAAAAAAByAAAAAAAAAG8AAAAAAAAAbwAAAAAAAAB0AAAAAAAAAFwAAAAAAAAAQQAAAAAAAABwAAAAAAAAAHAAAAAAAAAARAAAAAAAAABhAAAAAAAAAHQAAAAAAAAAYQAAAAAAAABcAAAAAAAAAEwAAAAAAAAAbwAAAAAAAABjAAAAAAAAAGEAAAAAAAAAbAAAAAAAAABcAAAAAAAAAFQAAAAAAAAAZQAAAAAAAABtAAAAAAAAAHAAAAAAAAAAXAAAAAAAAABhAAAAAAAAAG4AAAAAAAAAcwAAAAAAAABpAAAAAAAAAGIAAAAAAAAAbAAAAAAAAABlAAAAAAAAAC0AAAAAAAAAdAAAAAAAAABtAAAAAAAAAHAAAAAAAAAALQAAAAAAAAAxAAAAAAAAADQAAAAAAAAAMAAAAAAAAAA3AAAAAAAAADkAAAAAAAAAMAAAAAAAAAA0AAAAAAAAADUAAAAAAAAAOAAAAAAAAAAxAAAAAAAAAC0AAAAAAAAAMQAAAAAAAAA3AAAAAAAAADAAAAAAAAAAOQAAAAAAAAA4AAAAAAAAADQAAAAAAAAANQAAAAAAAAAwAAAAAAAAADUAAAAAAAAAOQAAAAAAAAA0AAAAAAAAADAAAAAAAAAAMgAAAAAAAAA1AAAAAAAAADUAAAAAAAAAXAAAAAAAAABcAAAAAAAAAGEAAAAAAAAAcgAAAAAAAABnAAAAAAAAAHUAAAAAAAAAbQAAAAAAAABlAAAAAAAAAG4AAAAAAAAAdAAAAAAAAABzAAAAAAAAACIA']
<192.168.140.92> WINRM RESULT <Response code 1, out "", err "Processing -File 'C'">

failed: [192.168.140.92] => {"failed": true, "parsed": false}
invalid output was: Processing -File 'C' failed because the file does not have a '.ps1' extension. Specify a valid Windows PowerShell script file name, and then try again.

**Comment by cchurch** [comment]
Should be fixed by https://github.com/ansible/ansible/commit/57dee4545b3c34d1e66943def8d5e45ee95d66bd

**Comment by cchurch** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
