### ISSUE TITLE
Using json in docker environment variables

### ISSUE THREAD

**Issue by dlip** [ansible/ansible#8595]
I use json to compact my docker environment variables, the problem is that the env parameter splits on ',' character meaning that more than one key doesn't work. eg

docker: env='options={"foo":"bar"}' //ok

docker: env='options={"foo":"bar","baz":"qux"}' //error because of comma

Is it possible to add an escape for the comma, eg ',,' ?

**Comment by mpdehaan** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
