### ISSUE TITLE
unarchive performance in 1.7

### ISSUE THREAD

**Issue by Lekensteyn** [ansible/ansible#8599]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:
- client: Arch Linux
- server: Ubuntu 14.04, ssh as root user without sudo.
##### Summary:

Before upgrading from 1.6.6, `unarchive` would extract files in a second. After the upgrade, the client takes a full CPU core for 7 minutes to extract 7k+ files.
##### Steps To Reproduce:

The tasks file is pretty basic:

```
# run as ssh user root, without sudo
- name: copy and extract app tarball
  unarchive: src={{app_tarball}}
             dest={{tarball_dest_dirname}}
```
##### Expected Results:

Instant execution in a few seconds.
##### Actual Results:

It takes 7 minutes while hogging a full CPU core. A gdb backtrace showed a trace where the output of `tar --diff` gets concatenated.

**Comment by mpdehaan** [comment]
Hi, we believe this is a duplicate and we have this fixed on the development branch, and this will be part of a 1.7.1 later this week.

That being said, we'll confirm this is indeed a seperate issue.

See https://github.com/ansible/ansible/commit/be0ca219d2a7ac9281c65ca59f20bc194b6efb7f

**Comment by mpdehaan** [comment]
cc @jimi-c

**Comment by Lekensteyn** [comment]
Unless someone is earlier, I will test it later this week.

**Comment by mpdehaan** [comment]
We'll be verifying this today actually.  Thanks!

**Comment by mpdehaan** [comment]
We've confirmed this is fixed on devel, and in fact faster than 1.6.  This will be included in 1.7.1 this week.

Thank you!

**Comment by Lekensteyn** [comment]
Thanks, looking forward to the next version! I am also curious which commit fixed this? The one you linked above?

**Comment by jimi-c** [comment]
@Lekensteyn yes, the commit above from @leth was the one that resolved the issue.
