### ISSUE TITLE
recurse parameter not supported in copy module (ansible 1.7)

### ISSUE THREAD

**Issue by lparsons** [ansible/ansible#8610]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

OS X 10.9.4
##### Summary:

When using the "recurse" parameter in the copy module, I get and error if changes are detected (but no error if there are no changes detected):
`msg: unsupported parameter for module: recurse`
##### Steps To Reproduce:

```
 - name: tool-dependencies
   copy: src="tool-dependencies/" dest="{{ GALAXY_HOME }}/tool-dependencies/" recurse=yes
```
##### Expected Results:

Expected that the contents of the `tool-dependencies` directory would be copied (recursively) to the the `{{ GALAXY_HOME }}/tool-dependencies/` directory on the remote host.
##### Actual Results:

ansible aborted with the following error: `msg: unsupported parameter for module: recurse`

**Comment by lparsons** [comment]
Interesting, it appears this may have been a change in version 1.7, but that the docs are out of sync?  Looking at https://github.com/ansible/ansible/blob/devel/library/files/copy#L35 it seems that recurse is no longer necessary and indeed, this does seem to work when I leave the recurse parameter off.  Perhaps just updating the docs would be sufficient.  

Is there anywhere that one can see these types of changes from version to version?  Changes that break existing roles and playbooks I mean?

**Comment by mpdehaan** [comment]
This is a docs error, related to a build issue that will go away in the next docs rebuild.

To do a recursive copy, just specify a src that is a directory.

This shouldn't break existing roles, and should in fact "just work".

It was available before because of the file module being used _by_ the copy module, but this was ultimately a bit misleading.

**Comment by mpdehaan** [comment]
I'm going to close this one as things are working (and we have tests that do recursive copy), but if you have further questions feel free to stop by ansible-project to discuss.  Thanks!
