### ISSUE TITLE
play vars section bug: special case where vars are not loaded 

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#8617]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8 devel - bisect shows this next commit as the culprit:

```
ac8950fd36d89765fadb9f3e80f101bafb188386 is the first bad commit
commit ac8950fd36d89765fadb9f3e80f101bafb188386
Author: James Cammarata <jimi@sngx.net>
Date:   Mon Aug 11 19:21:39 2014 -0500

    Set special vars in play.vars rather than load_vars

    Also refactors playbook loading code relating to vars in playbooks
    to a sub-function.

    Fixes #8534

:040000 040000 e83f3e601f063aeb98cebf0da8b5014e83350c32 142c7c1d411e944fc7323b8fb6bf1b8563ae128a M  lib
```
##### Environment:

Ubuntu trusty/precise
##### Summary:

A variable defined in the vars section of a play, is not really being loaded.

Running next play snippet, _but_ bug only triggers when I run `ansible-playbook main.yml` which includes the following playbook. If I run that playbook directly as in `ansible-playbook plays/logging.yml` the problem does not come up.

`plays/logging.yml` does contain other plays before the one that fails;

So far I wasn't able to dumb the set down to have a better understanding what exactly triggers this.
##### Steps To Reproduce:

`main.yml` contains `- include: plays/logging.yml`

`plays/logging.yml`:

```
  vars:                                                                         
      kibanatarurl: http://download.elasticsearch.org/kibana/kibana/kibana-latest.zip
      kibanazipname: kibana-latest                                              

  tasks:                                                                        
  - name: ELASTICSEARCH | download kibana                                       
      local_action: uri                                                           
      url={{ kibanatarurl }}                                                    
      dest=tmp/{{ kibanazipname }}.zip                                          
      follow_redirects=yes                                                      
      status_code=200                                                           
```
##### Expected Results:

Task completes.
##### Actual Results:

Task fails:

```
 One or more undefined variables: 'kibanatarurl' is undefined
```

**Comment by srgvg** [comment]
Example playbook to reproduce:

```
[A] serge@goldorak:~/tmp$ ansible-playbook --version
ansible-playbook 1.8 (devel 9edf3a749a) last updated 2014/08/13 15:31:02 (GMT +200)
[A] serge@goldorak:~/tmp$ cat main.yml 
---
- include: logging.yml
[A] serge@goldorak:~/tmp$ cat logging.yml 
- hosts: localhost
  gather_facts: false

  vars:
    myvar: test

  tasks:

  - debug: msg={{myvar}}

[A] serge@goldorak:~/tmp$ ansible-playbook logging.yml 

PLAY [localhost] ************************************************************** 

TASK: [debug msg=test] ******************************************************** 
ok: [localhost] => {
    "msg": "test"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

[A] serge@goldorak:~/tmp$ ansible-playbook main.yml 

PLAY [localhost] ************************************************************** 

TASK: [debug msg={{myvar}}] *************************************************** 
fatal: [localhost] => One or more undefined variables: 'myvar' is undefined

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/serge/main.retry

localhost                  : ok=0    changed=0    unreachable=1    failed=0   
```

**Comment by mpdehaan** [comment]
Can you perhaps upload this as a github repo so we can sort through paths and indentation issues easier?

**Comment by srgvg** [comment]
Example playbook in gist:

https://gist.github.com/sergevanginderachter/f29f9ec5d1ab37d89f27

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
