### ISSUE TITLE
make callbacks modular

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#862]
Goal -- Load modules from a module directory similarly to how cobbler handlers work.

Possible uses include drop in modifications to:

(A) making sound effects (pew pew pew, laser laser!)  ... ok, kidding.  Sort of.
(B) sending email notifications
(C) storing results of things in databases (like facts -- we can make a new fact callback)

**Comment by mpdehaan** [comment]
to preserve compatibility, callbacks should be ABLE to modular, but not the default ones that come with ansible.   This way we don't break any scripts that already use them by moving their paths.

**Comment by tima** [comment]
Like this idea. 

On a somewhat unrelated note -- are the callbacks documented somewhere at this time? I've seen them running through the code, but I don't have a complete sense of where they are and how I could use them.

**Comment by mpdehaan** [comment]
yeah, not really.

They can do pretty much whatever the want when they are called, and it should be _reasonably_ apparent when each is called, but I should work on adding some more comments.

If all this becomes modular (also connection types) -- which it will, we'll have places in the API docs to cover both.

**Comment by mpdehaan** [comment]
I've just made connection types modular (utils.load_plugins function), which should allow us to make callbacks similarly modular using similar code.

**Comment by mpdehaan** [comment]
this is now done, see my latest message to Google Groups.  Will be in the API guide sometime next week probably.
