### ISSUE TITLE
urpmi module behaves differently when python-rpm is installed

### ISSUE THREAD

**Issue by rghe** [ansible/ansible#8626]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.8
##### Environment:

Mageia 4
##### Summary:

from 0d8b81cd95a2f847f083fe03d769e7206415542f, urpmi module uses python-rpm, if present, instead of rpm -q to speed up package searches. Unfortunately search results aren't the same.
The two method are equivalent only when requesting packages with basename (e.g. 'mariadb'), not when specifying a revision (e.g. 'mariadb-5.8.3')
With plain rpm the latter is handled correctly, while using python rpm no match is detected.
Requesting a specific package version imho is an essential feature, thus the mentioned change should be reversed
##### Steps To Reproduce:

create an urpmi task requesting a specific package version, e.g.
    ---
    - hosts: all
      user: root
      tasks:
        - name: mariadb
           urpmi: pkg=mariadb-5.5.38

The requested package will be installed correctly. On subsequent runs the task will fail because the package is already installed, but the urpmi module tries to install again aborting when installation fails.
##### Expected Results:

urpmi module should detect if mariadb-5.5.38 is already installed and skip the installation
##### Actual Results:

```
failed: [host] => (item=mariadb-5.5.38) => {"failed": true, "item": "mariadb-5.5.38"}
msg: 'urpmi mariadb-5.5.38' failed: 
```

**Comment by mpdehaan** [comment]
Closing per the above commit, thank you!

**Comment by ciupicri** [comment]
@rghe , does

```
 python -c 'name="mariadb-5.5.38"; import rpm; print rpm.TransactionSet().dbMatch(rpm.RPMDBI_LABEL, name).count()'
```

work for you i.e. print a non-zero number?

**Comment by rghe** [comment]
Yes.
urpmi module does two searches, however, one by name and one by provides. The first perhaps can use rpmdbi_label, but the latter not. Besides, isn't rpm5 using RPMTAG_NVRA instead of RPMDBI_LABEL ?  This would make mandriva unable to use it without some special handling, not needed with the plain rpm approach.
To tell the truth, I'm not very fond of the rpm python module, I find it too low level.
That said, if someone with better grasp of the rpm python interface wants to step in and make the urpmi module work flawlessy both ways, feel free to do it :-)

**Comment by ciupicri** [comment]
I'm afraid that I'm almost clueless about this topic, especially with Mandriva/rpm5. I've only found something that seemed to worked, so I thought of proposing it hoping it might be of some use.

**Comment by rghe** [comment]
Hei, don't worry, I'm also somewhat groping in the dark with the python rpm interface. Plain rpm just works.
