### ISSUE TITLE
Add option to ansible.unarchive to work like tar --recursive-unlink and --unlink-first

### ISSUE THREAD

**Issue by gae123** [ansible/ansible#8643]
Here is the scenario I want to make work using unarchive. I currently cannot make this work because of the lack of the appropriate option in unarchive.
1. Create a tar file with 2 files
2. From the playbook unarchive into a location on the remote host
3. Recreate the tar file with only 1 file
4. rerun the playbook
5. The remote machine should now have just one file

**Comment by mpdehaan** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by gae123** [comment]
Hi Michael,

this is not a question, it is an RFE, why do you think it is a question?

PK
http://www.gae123.com

On August 16, 2014 at 7:43:32 AM, Michael DeHaan (notifications@github.com) wrote:

List Information

Hi!

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!

**Comment by gae123** [comment]
This is not a user question, it is an RFE for an option in ansible's unarchive module, can you please re-open and classify appropriately?
