### ISSUE TITLE
su using sudo

### ISSUE THREAD

**Issue by rngadam** [ansible/ansible#8650]
##### Summary:

There should be a way to use sudo to su to another user and then execute commands under that user (without that user needing sudo rights).
##### Steps To Reproduce:

If this is a bug ticket, please enter the steps you use to reproduce the problem in the space below.  If this is a feature request, please enter the steps you would use to use the feature.  If an example playbook is useful, please include a short reproducer inline, indented by four spaces.  If a longer one is necessary, linking to one uploaded to gist.github.com would be great.  Much appreciated!

Combination of su and sudo was constrained in this pull request: https://github.com/ansible/ansible/pull/5713

I don't understand why this constraint was put in.

Isn't it legimate to want to use sudo to su to a user that does not have itself sudo rights?

Example:

```
$ sudo su postgres -c "python /tmp/ansible-tmp-1408243501.37-248282758528150/postgresql_user"
{"changed": true, "user": "USERNAME"}
```
##### Expected Results:

I would have expected this configuration to create the equivalent of the command above:

```
- hosts: dbservers
  sudo: yes
  su: yes
  su_user: postgres

  tasks:
  - postgresql_user: name=carevoice password="{{dbpassword}}" role_attr_flags=CREATEDB,NOSUPERUSER
    sudo: no
```
##### Actual Results:

...but of course, because of this constraint it doesn't.

 I get instead:

```
ERROR: sudo params ("sudo", "sudo_user") and su params ("su", "su_user") cannot be used together
```

...running with only su results in blocking at this step:

```
EXEC ['ssh', '-C', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/rngadam/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'test1.censored.co', u'/bin/sh -c \'su postgres -c "/bin/sh -c \'"\'"\'echo SUDO-SUCCESS-jdapvnsiaffhqdymyftqgubnfsxguiyf; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /tmp/ansible-tmp-1408243501.37-248282758528150/postgresql_user\'"\'"\'"\'']
```

which if I kill it on the target server reveals that it is waiting for a password for su to that system user:

```
failed: [test1.kangyu.co] => {"failed": true, "parsed": false}
invalid output was: Password: Terminated
```

su'ing to that user is required because PostgreSQL requires peer authentication for the only privileged user at that point, postgres.

**Comment by jimi-c** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:
- Ansible should support sudo+su.

However, however what is happening is that:
- When the `sudo_user:` option is specified (either at the play level, or per-task), Ansible executes `sudo -u`. This is essentially the same thing as executing `sudo su - <user> /path/to/command`. For example, we commonly use `sudo_user: postgresql` ourselves to specify postresql database commands.

We would suggest:
- Set the `sudo_user:` option as needed. 

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
