### ISSUE TITLE
Using json in docker environment variables

### ISSUE THREAD

**Issue by dlip** [ansible/ansible#8661]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

From Ubuntu 14.04 to CentOS 6.5
##### Summary:

I use json to compact my docker environment variables, the problem is that the docker module parser splits on ',' character to signify a new key/value pair, meaning that more than one key doesn't work. eg

docker: env='options={"foo":"bar"}' //ok

docker: env='options={"foo":"bar","baz":"qux"}' //error because of comma

Is it possible to add an escape for the comma, eg '\,' or ',,' ?

It was commented on in mailing list a solution to try:

I think this is the problem in the module:

```
        env             = dict(type='list'),
```

If it were type='dict' we could do:

docker: 

```
env:

      options: {"foo":"bar","baz":"qux"}
```

   other_arguments_here: 1234

And basically use full YAML, without any splitting magic.
##### Steps To Reproduce:

Run a docker container with JSON as the env options
##### Expected Results:

Should be able to accept json.
##### Actual Results:

Error as it splits on the commas.

**Comment by mpdehaan** [comment]
This was recently fixed as type='dict' on the devel branch.

https://github.com/ansible/ansible/blob/devel/library/cloud/docker#L707

**Comment by sgoings** [comment]
@mpdehaan - I'm still having a similar problem even on the devel branch (HEAD: d63092ea45d70cb14c7633a8183a7a38a2726111)

```
  - name: "Try to inject commas in env strings"
    docker: image="readytalk/tomcat-native:8.0.9"
            state="running"
            env='CATALINA_OPTS="-Dconfig.zookeepers=zookeeper1,zookeeper2"'
```

Causes:

```
fatal: [newman] => failed to parse: Traceback (most recent call last):
  File "/home/sgoings/.ansible/tmp/ansible-tmp-1408553551.73-77442219569203/docker", line 2163, in <module>
    main()
  File "/home/sgoings/.ansible/tmp/ansible-tmp-1408553551.73-77442219569203/docker", line 724, in main
    net             = dict(default=None)
  File "/home/sgoings/.ansible/tmp/ansible-tmp-1408553551.73-77442219569203/docker", line 1086, in __init__
    self._check_argument_types()
  File "/home/sgoings/.ansible/tmp/ansible-tmp-1408553551.73-77442219569203/docker", line 1623, in _check_argument_types
    self.params[k] = dict([x.strip().split("=", 1) for x in value.split(",")])
ValueError: dictionary update sequence element #1 has length 1; 2 is required
```

**Comment by discordianfish** [comment]
Same here. It seems the parser is really naive here: https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L917

It's not even taking quoting into account.

**Comment by stefanfoulis** [comment]
I'm also still having this issue with ansible 1.8.4
