### ISSUE TITLE
Synchronize fails with remote_user

### ISSUE THREAD

**Issue by dopry** [ansible/ansible#8668]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.1
##### Environment:

Ubuntu 14.04.1 Server
##### Summary:

Synchronize fails when connecting to localhost with remote user.
##### Steps To Reproduce:

I'm logged into my workstation as vagant.
I'm executing with ansible-playbook -i inventory/client/hosts deploy.yml -u dopry

_inventory/client/hosts_

[app]
host-01  ansible_ssh_host=162.243.xxx.xxx

[app:vars]
source=/vagrant/master
destination=/srv/master

_deploy.yml_

```

---
hosts: all
remote_user: dopry
tasks:
  - name: copy server files
    synchronize:
      src: "{{ source }}"
      dest: "{{ destination }}"
```
##### Expected Results:

GIVEN I am logged in as **vagrant** and have set the remote user to **dopry**
- [ ] WHEN Ansible executes **local** actions THEN I expect them to run as **vagrant**
- [ ] WHEN Ansible executes **remote** actions THEN I expect them to run as **dopry**
##### Actual Results:

```
<127.0.0.1> ESTABLISH CONNECTION FOR USER: **dopry**
<127.0.0.1> EXEC ['ssh', '-C', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/vagrant/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=dopry', '-o', 'ConnectTimeout=10', '127.0.0.1', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1408351653.54-230338341262097 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1408351653.54-230338341262097 && echo $HOME/.ansible/tmp/ansible-tmp-1408351653.54-230338341262097'"]
fatal: [host-01] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue

FATAL: all hosts have already failed -- aborting
```

It appears to be either trying to do the local part with the remote credentials or trying to do the remote part with the localhost.

**Comment by mpdehaan** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by dopry** [comment]
This isn't a user question. The application is misbehaving.

**Comment by mikebiglan** [comment]
I'm noticing a similar issue in the synchronize module
