### ISSUE TITLE
Docker create container fails with private registry and complex version as image tag

### ISSUE THREAD

**Issue by rickfast** [ansible/ansible#8670]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7
##### Environment:

Running from Ubuntu 14.04 and managing Ubuntu 14.04
##### Summary:

Creating a container for image "172.84.98.33:5000/weather-module-builder:2.1.25" fails with:

```
TASK: [microservices | start docker container] ******************************** 
failed: [172.84.98.33] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1408387501.59-269872748649393/docker", line 2130, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1408387501.59-269872748649393/docker", line 736, in main
    containers = manager.create_containers(delta)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1408387501.59-269872748649393/docker", line 593, in create_containers
    image, tag = self.get_split_full_image_tag(params['image'])
ValueError: too many values to unpack
```

Oddly enough, "1.0.9" as image tag DOES work.
##### Steps To Reproduce:

Variables:

image = 172.84.98.33:5000/weather-module-builder
version = 2.1.25

Playbook step:

```
- name: start docker container
  docker: image="{{ image }}:{{ version }}" env="SERVER_PORT=8888,CONSUL_HOST=10.222.185.199" ports=8888:8888 expose=8888
  register: new_container
```
##### Expected Results:

Expected the Docker container to be created.
##### Actual Results:

```
TASK: [microservices | start docker container] ******************************** 
failed: [172.84.98.33] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
   File "/home/vagrant/.ansible/tmp/ansible-tmp-1408387501.59-269872748649393/docker", line     2130, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1408387501.59-269872748649393/docker", line 736, in main
    containers = manager.create_containers(delta)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1408387501.59-269872748649393/docker", line 593, in create_containers
    image, tag = self.get_split_full_image_tag(params['image'])
ValueError: too many values to unpack
```

**Comment by mpdehaan** [comment]
We've recently fixed some Docker items on 1.7.1 (latest stable release) and the development branch, can you please try there and see if this is still an issue? 

Thanks!

**Comment by rickfast** [comment]
Same issue in 1.7.1.

Tried using latest (1.8) using the new "registry" parameter, and now I'm getting "No such image".

registry = http://rickbot-shoffman-001.cqwm.orbitz.net:5000/
image = weather-module-builder
version = 3.1

```
- name: start docker container
  docker: image="{{ image }}:{{ version }}" registry="{{ registry }}" env="SERVER_PORT=8888,CONSUL_HOST=10.222.185.199" ports=8888:8888 expose=8888
  register: new_container
```

The image certainly exists on my private registry.

**Comment by rickfast** [comment]
So (in 1.8), upon further investigation, anything before a / in the image name gets removed before the docker module tries to pull and image or create a container.  In our case, we're using an organization on docker hub, so we can't pull/create containers.

Image name = orbitz/weather-module-builder (private repo)

This is also the case for private registry as well.  Despite the new registry parameter, I **think** the registry still needs to be in the image name.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
