### ISSUE TITLE
inconsistent behaviour when using ansible_user_id variable along with vars_files and include

### ISSUE THREAD

**Issue by uncreative** [ansible/ansible#8675]
##### Ansible Version: 1.7

$ ansible --version
ansible 1.7
##### Summary:

ansible_user_id variable along with vars_files and include results in inconsistent behaviour
###### file playtest.yml

```

---
- hosts: 127.0.0.1
  connection: local
  vars: 
    overridden: BAD
  vars_files: 
    - "/tmp/{{ ansible_user_id }}_vars.yml"
  tasks:
  - debug: var=overridden
  - include: includeme.yml renamed="{{ overridden }}"
```
###### file includeme.yml

```

---
- debug: var=overridden
- debug: var=renamed
```
###### file /tmp/uncreative_vars.yml (ansible_user_id=uncreative)

```

---
overridden: external
```
##### Expected Results:

I expected renamed to have the same value as overridden. Preferably, external
##### Actual Results:

```
########### file produces
$ ansible-playbook playtest.yml 

PLAY [127.0.0.1] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]
127.0.0.1: importing /tmp/uncreative_vars.yml

TASK: [debug var=overridden] ************************************************** 
ok: [127.0.0.1] => {
    "overridden": "external"
}

TASK: [debug var=overridden] ************************************************** 
ok: [127.0.0.1] => {
    "item": "", 
    "overridden": "external"
}

TASK: [debug var=renamed] ***************************************************** 
ok: [127.0.0.1] => {
    "item": "", 
    "renamed": "BAD"
}

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=4    changed=0    unreachable=0    failed=0   
```

**Comment by mpdehaan** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

Variable precedence is documented here:  http://docs.ansible.com/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

As this appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by uncreative** [comment]
Sorry, this isn't a question. it's a bug report. ansible fails to process variables from vars_files when the vars_files is using {{ ansible_\* }} type of variables to load the external vars. Please re-open
