### ISSUE TITLE
Ansible hangs when running remote su command on non-english client

### ISSUE THREAD

**Issue by 2xyo** [ansible/ansible#8681]
##### Issue Type:

Bug Report
##### Ansible Version:

```
# ansible --version
ansible 1.7
```
###### Ansible

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.5 (wheezy)
Release:        7.5
Codename:       wheezy
```
###### Client

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.5 (wheezy)
Release:        7.5
Codename:       wheezy
```
##### Summary:

su command should work on non-english clients.
##### Steps To Reproduce:

Client : 

```
$ cat > /tmp/locales <<EOF
locales locales/locales_to_be_generated multiselect fr_FR.UTF-8 fr_FR.UTF-8
locales locales/default_environment_locale      select fr_FR.UTF-8
> EOF

$ debconf-set-selections  /tmp/locales
$ DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true dpkg-reconfigure locales 
$ env |grep LANG
LANG=fr_FR.UTF-8

```

Ansible server:

```
$ ansible client-host  -a 'whoami' -u root --su --ask-su-pass -vvvv

<192.168.1.105> ESTABLISH CONNECTION FOR USER: client
<192.168.1.105> REMOTE_MODULE command whoami
<192.168.1.105> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=client', '-o', 'ConnectTimeout=3', '192.168.1.105', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1408442433.74-84227244736453 && echo $HOME/.ansible/tmp/ansible-tmp-1408442433.74-84227244736453'"]
<192.168.1.105> PUT /tmp/tmpHZBWWX TO /home/client/.ansible/tmp/ansible-tmp-1408442433.74-84227244736453/command
<192.168.1.105> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=client', '-o', 'ConnectTimeout=3', '192.168.1.105', u'/bin/sh -c \'su root -c "/bin/sh -c \'"\'"\'echo SUDO-SUCCESS-ebrxyacoauoolprytxhcfkryjcmqlrth; LC_CTYPE=C LANG=C /usr/bin/python /home/client/.ansible/tmp/ansible-tmp-1408442433.74-84227244736453/command; rm -rf /home/client/.ansible/tmp/ansible-tmp-1408442433.74-84227244736453/ >/dev/null 2>&1\'"\'"\'"\'']

^C^C^Cc^C^C^C^C^C^C^C^CTraceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 4, in <module>
  File "/usr/local/bin/ansible", line 4, in <module>
    __import__('pkg_resources').run_script('ansible==1.7', 'ansible')

    __import__('pkg_resources').run_script('ansible==1.7', 'ansible')

192.168.1.105 | FAILED => ssh connection error waiting for sudo or su password prompt
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.7-py2.7.egg/ansible/runner/__init__.py", line 77, in _executor_hook
    result_queue.put(return_data)
  File "<string>", line 2, in put
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ansible-1.7-py2.7.egg/ansible/runner/__init__.py", line 73, in _executor_hook
    while not job_queue.empty():
  File "<string>", line 2, in empty
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe

```
##### Expected Results:

```
192.168.1.105 | success | rc=0 >>
root
```
##### Actual Results:

Ansible hangs on non-english prompt password.

The French prompt password `Mot de passe :` doesn't match the regex defined in  [lib/ansible/utils/**init**.py#L1096](https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/__init__.py#L1096)

**Comment by mpdehaan** [comment]
It's probably going to be nearly impossible to detect all the possible password prompts, but we can probably research whether this is something we can force when invoking sudo to make it predictable.

The alternative approach would be a wider range of password prompts in the regex, which is less desirable.

I definitely agree we should find solutions to this one however, thanks very much for the report!

edit:  having a list of regexes seems like a good idea to me, forcing the language for test purposes may cause problems.

**Comment by jimi-c** [comment]
@2xyo I have created the above patch, which works in my testing. If you could test it on your systems to ensure it resolves your issue, I would appreciate it. Thanks!

**Comment by 2xyo** [comment]
Why not do something simpler like that: 

```
SU_PROMPT_LOCALIZATIONS =  ['Password', '암호', 'Adgangskode', ...]

def check_su_prompt(data):
    return data in SU_PROMPT_LOCALIZATIONS

```

It should be much more faster but it's case sensitive... 
Edit : and it fails with spaces and colon..

**Comment by 2xyo** [comment]
I keep your idea of regex with another approach which improves the performance in the worst case :
[Gist](https://gist.github.com/2xyo/f8a26f759413aa609359)
[Result (ipython notebook)](http://nbviewer.ipython.org/gist/2xyo/f8a26f759413aa609359)

**Comment by jimi-c** [comment]
I have incorporated your suggestions into the patch, with one minor tweak to add ' ?: ?' to each pattern, so that is does not match simple things like `password` when there is no prompt.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
