### ISSUE TITLE
bug when templating delegate_to values with inventory scoped variables

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#8705]
##### Issue Type:

Bug Report
##### Ansible Version:

all versions
##### Environment:

N/A
##### Summary:

There is a bug in the templating code of `delegate_to:` in that, it only happens once per runner proces fork, instead of for every host.
##### Steps To Reproduce:

Test inventory and playbook:

```
$ for n in `seq 0 20`; do echo host$n >> hosts ; done
$ cat test.yml

---
- hosts: all
  gather_facts: false
  connection: local
  tasks:
    - command: sleep 1
      delegate_to: '{{ inventory_hostname }}'
```
##### Expected Results:

`ansible-playbook -i hosts test.yml -f 1` (or whatever value for fork)

TASK: [command sleep 1] ******************************************************\* 
changed: [host1 -> host1]
changed: [host0 -> host0]
changed: [host2 -> host2]
changed: [host4 -> host4]
changed: [host8 -> host8]
changed: [host3 -> host3]
changed: [host6 -> host6]
changed: [host9 -> host9]
changed: [host5 -> host5]
changed: [host14 -> host14]
changed: [host16 -> host16]
changed: [host15 -> host15]
changed: [host10 -> host10]
changed: [host13 -> host13]
changed: [host11 -> host11]
changed: [host18 -> host18]
changed: [host17 -> host17]
changed: [host20 -> host20]
changed: [host19 -> host19]
changed: [host7 -> host7]
changed: [host12 -> host12]
##### Actual Results:

`ansible-playbook -i hosts test.yml -f 1`
TASK: [command sleep 1] ******************************************************\* 
changed: [host0 -> host0]
changed: [host1 -> host0]
changed: [host2 -> host0]
changed: [host3 -> host0]
changed: [host4 -> host0]
changed: [host5 -> host0]
changed: [host6 -> host0]
changed: [host7 -> host0]
changed: [host8 -> host0]
...

`ansible-playbook -i hosts test.yml -f 2`
TASK: [command sleep 1] ******************************************************\* 
changed: [host1 -> host1]
changed: [host0 -> host0]
changed: [host3 -> host0]
changed: [host2 -> host1]
changed: [host5 -> host1]
changed: [host4 -> host0]
changed: [host6 -> host1]
changed: [host7 -> host0]
changed: [host9 -> host0]
...

`ansible-playbook -i hosts test.yml -f 3`
TASK: [command sleep 1] ******************************************************\* 
changed: [host2 -> host2]
changed: [host1 -> host1]
changed: [host0 -> host0]
changed: [host3 -> host2]
changed: [host4 -> host1]
changed: [host5 -> host0]
changed: [host6 -> host2]
changed: [host7 -> host1]
...

The same effect can also be seen by varying the `serial:` option in the play.

**Comment by mpdehaan** [comment]
delegate_to: inventory_hostname is of course the same as not delegating, which I think you know, but yes, this might be a little confusing if someone wants to attach an inventory var to it.

Thanks for the report, I suspect you are the very first person trying this, but it needs to be fixed.

**Comment by srgvg** [comment]
Well, this is just for sake of showing the bug here obviously :) I use this to do an action "on the other cluster node", so that var resolves to somethng different for every host,

fyi use case: doing a health check on the other cluster node before redeploying the current node

**Comment by ktosiek** [comment]
I have the same problem when trying to setup container's settings (which needs delegating that task to the right hypervisor).

example without delegating to self:
playbook.yml

```
- hosts: all
  tasks:
    - shell: echo hi
      delegate_to: '{{ other_host }}'
```

inventory

```
hostA other_host=hostB
hostB other_host=hostC
hostC other_host=hostA
```

This example will break (as in, delegate to wrong host) with -f smaller than play_hosts, I've tested a few cases:

```
-f  | serial | is broken
 3 | none  | no
 2 | none  | yes
 2 |   2   | no
 1 |   2   | yes
```

**Comment by jimi-c** [comment]
@svg / @ktosiek I have created the above patch, which appears to resolve both of your test cases. If one or both of you could test it as well, I'll get it merged in.

**Comment by ktosiek** [comment]
I've checked on current devel (e9229cfeaa7727b) + this patch, and it works. Thank you for fixing this, now I can run my whole deployment with one ansible-playbook invocation ^_^

**Comment by srgvg** [comment]
Thanks @jimi-c this looks good for me.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by ryanschneider** [comment]
Any ETA on this getting into a tagged 1.7.x release?
