### ISSUE TITLE
yum module return fail on uninstall

### ISSUE THREAD

**Issue by AndreasDavour** [ansible/ansible#871]
I tried to make sure some packages were uninstalled. I got a reply which indicated failure, while I expected the task to just skip with nothing to be done.

Is this really how it's supposed to work?

This is the line from the playbook and my ansible version and the output:
- name: Removing packages not needed from RHEL6
  action: yum name=$item state=absent
  with_items:

rpm -qa | grep ansible
ansible-0.7-0.git201208141355.fc17.noarch

TASK: [Removing packages not needed from RHEL6] ********************\* 
<pollapi01.sx1> REMOTE_MODULE yum name=bluez-bluefw,bluez-hcidump,bluez-libs,bluez-utils,cups,gpm,isdn4k-utils,nfs-utils,pcscd,yum-updatesd state=absent
failed: [pollapi01.sx1] => (item=bluez-bluefw,bluez-hcidump,bluez-libs,bluez-utils,cups,gpm,isdn4k-utils,nfs-utils,pcscd,yum-updatesd) => {"changed": false, "failed": true, "item": "bluez-bluefw,bluez-hcidump,bluez-libs,bluez-utils,cups,gpm,isdn4k-utils,nfs-utils,pcscd,yum-updatesd", "module": "yum", "msg": "No Package matching 'bluez-bluefw' found available, installed or updated", "rc": 0, "results": []}

PLAY RECAP ********************\* 
pollapi01.sx1                  : ok=1    changed=0    unreachable=0    failed=1

**Comment by skvidal** [comment]
3 different possible completions for a state=absent
1. remove the pkg that is installed matching the name specified
2. nothing to do b/c the package is already removed
3. error b/c the package you are asking about doesn't exist anywhere, which implies that you typoed it.

I think you hit 3.

**Comment by mpdehaan** [comment]
If it doesn't exist anywhere, then that shouldn't it NOT be an error with state=absent?  

An example would be if I had already removed it, but also removed it from the repo already, and were making EXTRA sure it wasn't installed on all your systems.

**Comment by skvidal** [comment]
On Tue, 14 Aug 2012, Michael DeHaan wrote:

> If it doesn't exist anywhere, then that shouldn't it NOT be an error with state=absent?
> 
> An example would be if I had already removed it, but also removed it from the repo already, and were making EXTRA sure it wasn't installed on all your systems.

So how do I ever tell if the user typo'd the input?

action: yum state=absent name=gilbc

That will just silently work despite it being a fairly obvious typo.

-sv

**Comment by mpdehaan** [comment]
You could probably include some additional text in the return so you could spot it if you used --verbose.  

Idempotent removal strikes me as being super important in the package module relative to typo detection.   Otherwise your playbooks crash the second time through.

**Comment by skvidal** [comment]
they only crash if you remove the repository which also contains the package.
or if the repository purges the package entirely

**Comment by mpdehaan** [comment]
Ok, so if I were to rm the package and do createrepo again, it's ok?  

Lots of cobbler folks do that, and that's what I'm concerned about.

Seems like it still should not be an error, technically that package is gone, which means it worked as designed.

Similarly if I ask for a user named "dmehaan" to not exist, it should trust I know what I mean.

**Comment by skvidal** [comment]
fine. done.

**Comment by mpdehaan** [comment]
should be fixed per change on top of aforementioned merge.
