### ISSUE TITLE
In 1.7.0, file state=directory, is impossible to create relative directory

### ISSUE THREAD

**Issue by Excedrin** [ansible/ansible#8713]
This attempts to create /test instead of /home/foo/test:
ansible local -m file -a 'path=test state=directory'

**Comment by oskarpearson** [comment]
Replicated in Ansible 1.7.1:

ansible --version
ansible 1.7.1

ansible localhost -m file -a 'path=test state=directory'
localhost | FAILED >> {
    "failed": true,
    "msg": "Traceback (most recent call last):\n  File \"/home/oskar/.ansible/tmp/ansible-tmp-1408667308.94-231372927156510/file\", line 1675, in <module>\n    main()\n  File \"/home/oskar/.ansible/tmp/ansible-tmp-1408667308.94-231372927156510/file\", line 216, in main\n    os.mkdir(curpath)\nOSError: [Errno 13] Permission denied: '/test'\n",
    "parsed": false
}

**Comment by sivel** [comment]
This was recently resolved in #8642

**Comment by Excedrin** [comment]
Thanks!
