### ISSUE TITLE
mysql_user doesn't read variables

### ISSUE THREAD

**Issue by giacmir** [ansible/ansible#8718]
I can't use variables with the mysql_user module.

example: 
if I set a var like this
`testname: "my_test_name"`

and then

`mysql_user: name="test_{{ testname }}" password="{{ testpassword }}"`

I have an user with name "test_{{ testname }}" while it was expected "test_my_test_name"

The same happens if I try to pass login_user and login_password. In that case I have an access failure that is not present if I use them in mysql_db.

example:
`mysql_db: login_user={{ root_user }} login_password={{ root_password }} #Works`
`mysql_user: login_user={{ root_user }} login_password={{ root_password }} #unable to connect to database`

I'm using ansible 1.7.1

**Comment by iainlbc** [comment]
Hi Gia,

I can confirm this module works with var's for each param, we use it
with_dict in Vault http://docs.ansible.com/playbooks_vault.html

Can you paste the full mysql_user play you are running to create a user?

Have you tried without quoting "test_{{ testname }}" so it's test_{{
testname }}

Have you checked the mysql users table after running the play?

Here's our implementation:
- name: Ensure enabled users have MySQL accounts and disabled users do not
  mysql_user: login_user=root login_password={{ root_password }} name={{
  item.value.name }} password={{ item.value.password }} state={{
  item.value.state }} priv="{{ item.value.priv }}" host={{ item.value.host }}
  with_dict: mysql_users

Sample dict:

mysql_users:
  user_name:
    name: user_name
    password: some_password
    state: present
    priv:
"some_database._:SELECT,INSERT,UPDATE,DELETE/some_other_db._:SELECT,INSERT,UPDATE,DELETE"
    host: localhost

HTH,

## 

Iain Wright

This email message is confidential, intended only for the recipient(s)
named above and may contain information that is privileged, exempt from
disclosure under applicable law. If you are not the intended recipient, do
not disclose or disseminate the message to anyone except the intended
recipient. If you have received this message in error, or are not the named
recipient(s), please immediately notify the sender by return email, and
delete all copies of this message.

On Fri, Aug 22, 2014 at 3:59 AM, Giacomo Mirabassi <notifications@github.com

**Comment by giacmir** [comment]
Thank you for the promt response and for pointing me the right way. Acually I found an unwanted space in the user password variable call
e.g. {{db_<space>password}}

Removing that space solved the issue.

Thanks
