### ISSUE TITLE
yum module: issue with library/packaging/yum and Duplicate Package Names with disabled repos

### ISSUE THREAD

**Issue by seanmccully** [ansible/ansible#8724]
##### Issue Type:

Bug
##### Ansible Version:

1.6 - 1.7 -- Python 2.6.6/CentOS 6.5
##### Environment:

1.6 - 1.7 -- Python 2.6.6/CentOS 6.5
##### Summary:

Package from a disabled repository is installed when specify disable repository option. Yum Library does not correctly update installed packages when specify enable and disable repo options and repository contain similar package names.
##### Steps To Reproduce:

Enable at least two repos with similar package names. Run ansible yum task installing package by disabling repository A, rerun ansible task.
##### Expected Results:

Package from disabled repository should not be installed.
##### Actual Results:

Package from disabled repository installed.

**Comment by mpdehaan** [comment]
Can you please share the yum line from your ansible playbook?  I'm wanting to see what options you are passing.

Also if you are disabling a repo via a playbook, can you please share those steps?

**Comment by seanmccully** [comment]
```
 - name: Install Apache
    yum: name=httpd disablerepo=fedora enablerepo=testing state=latest
```

-- Note this works for first install, but not on updates.

**Comment by seanmccully** [comment]
Nevermind, I realize this was not an issue with the yum module .....
