### ISSUE TITLE
RFE: support passing new variables directly into the template task

### ISSUE THREAD

**Issue by axos88** [ansible/ansible#8733]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.7.1
##### Environment:

N/A
##### Summary:

Reopening #4546 

Just encountered the problem reported in #4546
Due to openSSL not being able to accept extendedusagetypes from the command line, only from config files, I need to do something similar to this:
- template: src=openssl_config.j2 dest=/tmp/openssl.cnf 
  vars:
    usage: serverAuth
- shell: openssl req -config /tmp/openssl.cnf.....
- template: src=openssl_config.j2 dest=/tmp/openssl.cnf 
  vars:
    usage: clientAuth
- shell: openssl  req -in {{item}} -config /tmp/openssl.cnf .....
  with_items: client_certs

Without being able to manipulate the usage variable passed to the template, one can not reuse the config template.

There was another comment to about 3 weeks ago from @iraksdale

Have to agree with @claco here. I'm using a template to output multiple files based on a with_dict loop, and semantically it kind of sucks to use item.key or item.value all over the template - doesn't make them very reusable.

It would be nice to define "service_name" or "hostname" variables or whatever in the playbook where it's easy to see their relationship to the variable being looped, and have the templates use {{service_name}} instead of having to put "whatever_{{item.key}}" in the templates.

It really hinders the reuse of templates, because it marries them to a particular playbook structure, and the passthrough to the file module could be preserved if you just added a template_vars argument that would make its contents available to the template.

As a new user to ansible, I'd say the lack of this is really counterintuitive. Is it possible to reconsider this decision? I think it adds a lot to the reusability & understandability of templates.
##### Expected Results:

The vars should take precedence over anything that would be passed in to the template engine

**Comment by mpdehaan** [comment]
# Question About This One

Hi!

Thanks very much for this report.
- reopening a ticket like this is not the best way to bring up the issue, but we are open to a discussion on the ansible-devel mailing list.  
- please post there and we're open to discuss
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you once again for this and your interest in Ansible!

**Comment by lindes** [comment]
For what it's worth, the basic functionality you're looking for can be approximated using the `set_fact` task in between `template` tasks, so perhaps something like (and I haven't tested this):

```
- set_fact: usage=serverAuth
- template: src=openssl_config.j2 dest=/tmp/openssl.cnf
- shell: openssl req -config /tmp/openssl.cnf
- set_fact: usage=clientAuth
- template: src=openssl_config.j2 dest=/tmp/openssl.cnf
- shell: openssl req -config /tmp/openssl.cnf
```

**Comment by ghost** [comment]
Do you people even understand how to use parameterized roles? Srzly?

Just have one role that deploy the template. Then have another role include that role, overriding vars as it does so. This is exactly what I did to solve this problem, e.g. my code looks something like this (to deploy a reusable template for supervisord):

```
- name: foo supervisor process  
  include: ../../common/tasks/supervisor.yml  
  vars:  
    filename: somefile  
    program_name: somename  
    program_cmd: /path/to/foo  
    proc_name: foo  
    number_of_processors: 42  
    user: root  
```

Get it? No loops, no item.key or item.value, just plain vars.

**Comment by axos88** [comment]
Dial it back dude. Yes. That is a workaround. But a role is a much higher-level concept than to be used for deploying a template. 
Should I create 29 roles if I have 29 templates to be deployed that way? Don't you feel like it's a little bit (actually a lot) of boilerplate going on there?

**Comment by ghost** [comment]
"Should I create 29 roles if I have 29 templates to be deployed that way?"

What is stopping you using variables to define the source path and target path in the template role? Nothing as far as I can see, my example already using "filename" to define the target path.

Having a role to deploy a set of closely related template with variable substitution from the include statement seems like a perfectly good use of a role to me.

**Comment by dejayc** [comment]
@fcntl Woooosh... That's the sound of @axos88 's point going right over your head.

**Comment by bcoca** [comment]
is this what you want?

```
- template: ...
  vars:
    test1: value1
```

it already works in 2.x

**Comment by axos88** [comment]
Yes, indeed it does. Back when the ticket was opened, 2.0 was not yet ready.

**Comment by rektide** [comment]
can a mod please go back to https://github.com/ansible/ansible/issues/4546 & mention that this works now?
