### ISSUE TITLE
Incorrect git examples?

### ISSUE THREAD

**Issue by bmvzane** [ansible/ansible#8747]
##### Issue Type:

Documentation Report
##### Ansible Version:

1.7.1
##### Environment:

Ubuntu Server 14.04 64 bit, git 1.9.1
##### Summary:

It seems like the protocol "ssh://" is unnecessary for git ssh URLs. Actually, if the repo URL starts with "ssh://" Ansible returns an authentication error.

https://github.com/ansible/ansible/blob/devel/library/source_control/git#L143
##### Steps To Reproduce:

Have Ansible clone a GitHub repository using SSH. Make sure to use the format "ssh://<git url>".
##### Expected Results:

Cloned repository.
##### Actual Results:

failed: [192.168.1.79] => {"cmd": "/usr/bin/git ls-remote ssh:********", "failed": true, "rc": 128}
stderr: ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

msg: ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

FATAL: all hosts have already failed -- aborting

**Comment by chachra** [comment]
I'm facing the same issue.... Any known solution?

**Comment by sivel** [comment]
We explicitly use ssh:// protocol URLs as documented and they work without issues.  In fact they have always been more reliable than not specifying the protocol.

**Comment by chachra** [comment]
Fair enough. But its not working per the bug ?! :-)

**Comment by chachra** [comment]
Might be something specific to what I am doing, so please ignore for now!

**Comment by mpdehaan** [comment]
Hi!

As part of our recent module restructing, modules have been moved to two different repos.   

These are:

https://github.com/ansible/ansible-modules-core
https://github.com/ansible/ansible-modules-extras

Whether a module is in core or extras can be found by consulting the documentation page for the module, where this will be noted at the bottom of the documentation page.

If you can please reopen this ticket on one of the two trackers above, we would appreciate it.

Thank you very much!
