### ISSUE TITLE
check mode causes register: var to be successful

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#8753]
##### Issue Type:

Bug Report
##### Ansible Version:

devel 1.8, 1.7.1
##### Environment:

What OS are you running Ansible from? Ubuntu 14.04 

What OS are you managing? CentOS / Ubuntu 14.04
##### Summary:

Having a playbook where the condition becomes true in check_mode and causes the task to run in check mode while in "live mode" this task is skipped.
##### Steps To Reproduce:

Playbook:

```

---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - command: /bin/false
    register: test_var
    changed_when: false
    ignore_errors: true

  - debug: msg="should be skipped in check_mode"
    when: test_var|success
```

Live mode:

```
ansible-playbook test.yml 

PLAY [localhost] ************************************************************** 

TASK: [command /bin/false] **************************************************** 
failed: [localhost] => {"changed": false, "cmd": ["/bin/false"], "delta": "0:00:00.003600", "end": "2014-08-26 11:55:17.597110", "rc": 1, "start": "2014-08-26 11:55:17.593510", "stdout_lines": [], "warnings": []}
...ignoring

TASK: [debug msg="should be skipped in check_mode"] *************************** 
skipping: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0 
```

Check mode:

```
ansible-playbook test.yml --check

PLAY [localhost] ************************************************************** 

TASK: [command /bin/false] **************************************************** 
skipping: [localhost]
ok: [localhost]

TASK: [debug msg="should be skipped in check_mode"] *************************** 
ok: [localhost] => {
    "msg": "should be skipped in check_mode"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0 
```
##### Expected Results:

debug task should be skipped using --check-mode. 
##### Actual Results:

debug task is going to be executed in check mode.

**Comment by mpdehaan** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:
- check mode doesn't handle conditionals correctly

However, however what is happening is that:
- your task is not registering a result in check mode

We would suggest:
- using 'always_run: True' to make sure the step runs in check mode

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
