### ISSUE TITLE
Vault functionality appears to be broken for 1.7.x

### ISSUE THREAD

**Issue by nocive** [ansible/ansible#8756]
##### Issue Type:

Bug report
##### Ansible Version:

1.7.1 and 1.7.1-1
##### Environment:

Distribution: ArchLinux rolling
Python 2 version: 2.7.8
Python 3 version: 3.4.1
##### Summary:

After upgrading to any of the of 1.7.x versions, vault does not work.
This is valid for both ansible-vault and ansible-playbook.
Might be related to #8752.

Previously working playbook stacktrace:

```
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 309, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 125, in main
    vault_pass = utils.read_vault_file(options.vault_password_file)
AttributeError: 'module' object has no attribute 'read_vault_file'
```

Also broken for ansible-vault but with a different error:

```
Traceback (most recent call last):
  File "/usr/bin/ansible-vault", line 217, in <module>
    main()
  File "/usr/bin/ansible-vault", line 198, in main
    parser = build_option_parser(action)
  File "/usr/bin/ansible-vault", line 63, in build_option_parser
    help="vault password file", default=C.DEFAULT_VAULT_PASSWORD_FILE)
AttributeError: 'module' object has no attribute 'DEFAULT_VAULT_PASSWORD_FILE'
```
##### Steps To Reproduce:

Upgrade to 1.7.x and specify a vault password file with --vault-password-file /vault/password/file to ansible-playbook.
Also potentially manifesting the same problem: ansible-vault edit /some/previously/working/vault/file
##### Expected Results:

`ansible-playbook` should run.
`ansible-vault edit` should be able to edit previously working vault files.
##### Actual Results:

`ansible-playbook` throws an error when --vault-password-file is specified.
`ansible-vault edit` is throwing an error and refusing to edit any previously working vault files.

**Comment by sivel** [comment]
It sounds to me that you have a mixed install.  Some files related to ansible were updated while others were not.  Perhaps only the 'bin' files were updated.

You may need to perform a full uninstall, verify all ansible related files are deleted, and the install again.

**Comment by nocive** [comment]
@sivel You're absolutely right, deleted everything in python's site-packages, reinstalled and voila'!
Going to close the ticket as this is most likely an issue in ArchLinux's package and not in ansible.

Thanks
