### ISSUE TITLE
wait_for ignores ansible_ssh_host if set in inventory

### ISSUE THREAD

**Issue by dwt** [ansible/ansible#8776]
##### Summary:

What it does is that it tries to resolve inventory_hostname via dns, even if it has an ansible_ssh_host set in the inventory. Which of course doesn't work if ansible_ssh_host is set in the inventory.
##### Steps To Reproduce:

playbook:
    - name: Wait for server to come back up
      local_action: "wait_for host={{ inventory_hostname }} port=22  delay=10 state=started"
inventory:
   a_host_name_that_doesnt_resolve_via_dns ansible_ssh_host=some.ip.v4.address ansible_ssh_pass=fnord
##### Expected Results:

I would expect that ansible resolves inventory_hostname to the ansible_ssh_host specified in the inventory.
##### Actual Results:

It does not.
Not sure what the right implementation is, but as a user I expect that if I set a custom IP for a host in the inventory, then ansible should respect that when I refer to that host.

**Comment by mpdehaan** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:
- wait_for should understand the ansible_ssh_host

However, however what is happening is that:
- the wait_for module does obey ansible_ssh_host and will be called where that is set, however the inventory_hostname is just a string, and doesn't refer to an object in Ansible.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by dwt** [comment]
Well, thanks for pointing out the misunderstanding.

Could you perhaps document for posterity what the right variable is to refer to the symbolic name in the inventory hostname that will make things like wait_for resolve to an address like ansible_ssh_host on demand?

**Comment by innyso** [comment]
@dwt I am having the same issue. Did you end up finding a solution for it? 

At the moment I am doing a work around by just ping the machine until ping succeed.

**Comment by dwt** [comment]
Sorry, this was some time ago, I'm not entirely sure if we resolved this.

Currently we use this code to do what we want:

```
  - name: Wait for server to come back
    local_action: "wait_for host={{ansible_ssh_host}} port=22  delay=10 state=present"
  - debug: "msg={{ansible_ssh_host}} has rebootet into the rescue system. You can login to it now with ssh password {{host_password.stdout}}"
```
