### ISSUE TITLE
Link in the user module docs doesn't display correctly

### ISSUE THREAD

**Issue by proxypoke** [ansible/ansible#8782]
##### Issue Type:

Documentation Report
##### Ansible Version:

? (docs.ansible.com)
##### Environment:

n/a
##### Summary:

The link to the FAQ entry [How do I generate crypted passwords for the user module?](http://docs.ansible.com/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module) in the [documentation of the user module](http://docs.ansible.com/user_module.html) (in the comment for the "password" parameter) is not displaying correctly.
##### Steps To Reproduce:

Go to http://docs.ansible.com/user_module.html.
##### Expected Results:

The link displays correctly.
##### Actual Results:

It doesn't.

**Comment by dharmabumstead** [comment]
This appears to have been fixed. Closing.
