### ISSUE TITLE
New symbolic perms code not python 2.4 compatible

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#8784]
##### Issue Type:

Bug Report
##### Ansible Version:

`ansible 1.8 (devel f8a30faeee) last updated 2014/08/27 14:33:57 (GMT -500)`
##### Environment:

Control: Mac OS, virtualenv, python 2.7.5

Target: RHEL 5
##### Summary:

As added in fc3597af5d3c0a866ee492f4553c0fe6608fd302 the following lines are not python 2.4 compatible:

https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L616
https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L626
https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L636
##### Steps To Reproduce:
1. ansible all -i rhel5.example.org, -m command -a whoami
##### Expected Results:

```
rhel5.example.org | success | rc=0 >>
sivel
```
##### Actual Results:

```
rhel5.example.org | FAILED >> {
    "failed": true,
    "msg": "SUDO-SUCCESS-rvariyjzhgvfbcvycyizbtzyrvijozvz\r\n  File \"/home/sivel/.ansible/tmp/ansible-tmp-1409169069.66-277569040462994/command\", line 833\r\n    'X': stat.S_IXUSR if apply_X_permission else 0,\r\n                       ^\r\nSyntaxError: invalid syntax\r\nX11 forwarding request failed\r\n",
    "parsed": false
}
```

**Comment by mpdehaan** [comment]
Fixed per the above, thanks.

In the future, we should also use dict() instead of the {} constructor where possible per contributing.md
