### ISSUE TITLE
yum module does not understand release numbers

### ISSUE THREAD

**Issue by aabdnn** [ansible/ansible#8855]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.1
##### Environment:

Running from MacOSX 10.9.4, managing CentOS 6.
##### Summary:

When using the yum module, if I specify a package name as name-version-release, ansible fails to detect the package. If I use only name-version, it works.
##### Steps To Reproduce:

ansible hostname -sK -m yum -a name=centos-release-6-5
##### Expected Results:

```
ns2.ams.authdns.ripe.net | success >> {
    "changed": false, 
    "msg": "", 
    "rc": 0, 
    "results": [
        "centos-release-6-5.el6.centos.11.2.x86_64 providing centos-release-6-5 is already installed"
    ]
}
```
##### Actual Results:

```
ns2.ams.authdns.ripe.net | FAILED >> {
    "changed": false, 
    "failed": true, 
    "msg": "No Package matching 'centos-release-6-5' found available, installed or updated", 
    "rc": 0, 
    "results": []
}
```

**Comment by mpdehaan** [comment]
I think this should be expressed as:

"name=centos-release=6.5"

rather than the dash.

**Comment by mpdehaan** [comment]
I may be wrong on this, we'll verify, the docs say "-" but I believe it takes an equals, in which case this is a docs bug.

We will investigate.

**Comment by jimi-c** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated. In particular, we believe you have said:
- The yum module does not understand release numbers

However, however what is happening is that:
- You are specifying an incomplete release string. If you look at the `rpm -qi` information for centos-release, you will see that the full release is something along the lines of `5.el6.centos.11.2`.

We would suggest:
- Specify the full release number, or use a wild-card (ie. `centos-release-6-5*`).

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
