### ISSUE TITLE
traceback in ansible-galaxy (1.8/tip)

### ISSUE THREAD

**Issue by infowolfe** [ansible/ansible#8884]
It's entirely possible that this is the fault of Rackspace_Automation.drone, and curiously ansible-galaxy list shows Rackspace_Automation.drone as installed afterwards, but the traceback is confusing. System is macos 10.9.4, python 2.7.8 (via brew), ansible via brew's pip (pip install -U git+ssh://git@github.com/ansible/ansible.git#egg=ansible). After further testing (ansible 1.6, 1.7.1 and 1.8-tip on ubuntu 14.04 LTS) it seems that this particular error is a regression. It only seems to occur on 1.8-tip, 1.6, 1.7.1 are both "clean."

macos output:

```
$ ansible-galaxy install --force Rackspace_Automation.drone
- downloading role 'drone', owned by Rackspace_Automation
- downloading role from https://github.com/rack-roles/drone/archive/master.tar.gz
- extracting Rackspace_Automation.drone to /etc/ansible/roles/Rackspace_Automation.drone
- Rackspace_Automation.drone was installed successfully
Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 897, in <module>
    main()
  File "/usr/local/bin/ansible-galaxy", line 891, in main
    fn(args, options, parser)
  File "/usr/local/bin/ansible-galaxy", line 793, in execute_install
    dep = ansible.utils.role_yaml_parse(dep)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/__init__.py", line 419, in role_yaml_parse
    if 'github.com' in role["src"] and 'http' in role["src"] and '+' not in role["src"] and not role["src"].endswith('.tar.gz'):
TypeError: string indices must be integers
```

Ubuntu 14.04 LTS / ansible 1.7.1 output: (as expected)

```
ansible-galaxy install Rackspace_Automation.drone
 downloading role 'drone', owned by Rackspace_Automation
 no version specified, installing master
 - downloading role from https://github.com/rack-roles/drone/archive/master.tar.gz
 - extracting Rackspace_Automation.drone to /etc/ansible/roles/Rackspace_Automation.drone
Rackspace_Automation.drone was installed successfully
 adding dependency: Rackspace_Automation.docker
 adding dependency: Rackspace_Automation.mysql
 downloading role 'docker', owned by Rackspace_Automation
 no version specified, installing master
 - downloading role from https://github.com/rack-roles/docker/archive/master.tar.gz
 - extracting Rackspace_Automation.docker to /etc/ansible/roles/Rackspace_Automation.docker
Rackspace_Automation.docker was installed successfully
 downloading role 'mysql', owned by Rackspace_Automation
 no version specified, installing master
 - downloading role from https://github.com/rack-roles/mysql/archive/master.tar.gz
 - extracting Rackspace_Automation.mysql to /etc/ansible/roles/Rackspace_Automation.mysql
Rackspace_Automation.mysql was installed successfully
```

**Comment by drybjed** [comment]
I can confirm the regression. Downloading role dependencies works on Ansible `v1.7.1`, doesn't work on `v1.7.0` or later. I tried bisecting from current `devel` back to `v1.7.1`, all I've got was:

```
The merge base e90d2573d1ab7a5c1f43ec6817fb86e8e4c294d0 is bad.
This means the bug has been fixed between e90d2573d1ab7a5c1f43ec6817fb86e8e4c294d0 and [268e72318f5aac74c07b6be24afeb2684568aacd].
```

**Comment by mpdehaan** [comment]
A traceback is not technically a regression, it's a traceback.  A regression is a reoccurrence of a prior bug, so I'll update your description.

@drybjed reports this works in 1.7.1, and doesn't work in 1.7.0 or later, though I think he means 1.8 (devel).

I'm flagging this as a priority issue so we can follow up, regardless.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
