### ISSUE TITLE
Catch/report metadata parsing errors from ansible-galaxy CLI

### ISSUE THREAD

**Issue by jameskyle** [ansible/ansible#8892]
##### Issue Type: Bug

ansible-galaxy requirements.txt bug.
##### Ansible Version:

ansible 1.8 
##### Environment:

Host: Mac OS X, Mavericks. 
Target OS: N/A
##### Summary:

If you try to specify a repository on github (or by using scm/git) and that role is not registered with ansible-galaxy, it throws an error.
##### Steps To Reproduce:

Example requirements.yml:

```
- src: https://github.com/jameskyle/ansible-gentoo
  name: gentoo
```

Command:

```
ansible-galaxy install -r requirements.yml
```
##### Expected Results:

Expected the repository found at https://github.com/jameskyle/ansible-gentoo to be retrieved and stored in a local role called 'gentoo'.
##### Actual Results:

Error:

```
$ ansible-galaxy install -r requirements.yml
downloading role 'com/jameskyle/ansible-gentoo', owned by -%20src%3A%20https%3A//github
Sorry, - src: https://github.com/jameskyle/ansible-gentoo was not found on galaxy.ansible.com.
 downloading role 'name%3A%20gentoo', owned by
Sorry, name: gentoo was not found on galaxy.ansible.com.
```

**Comment by jimi-c** [comment]
Hi @jameskyle, my guess is you're using a version of 1.8 that has not been updated to a more recent commit, as this support was added fairly recently. Looking at this with the most recent devel checkout, I actually see a different error:

<pre>
# ansible-galaxy install -r requirements.yml -p roles
- executing: git clone https://github.com/jameskyle/ansible-gentoo gentoo
- executing: git archive --prefix=gentoo/ --output=/tmp/tmpYagmyS.tar HEAD
- error: this role does not appear to have a valid meta/main.yml file.
- gentoo was NOT installed successfully.
- you can use --ignore-errors to skip failed roles.
</pre>

Looking at your `meta/main.yml` on that role, it does have an error on line 8/9:

<pre>
  platforms:
    - name: Gentoo
    versions:
      - all
</pre>

The `versions` (and the list below it) need to be indented further.

If you run `ansible --version` it will print the SHA associated with the github commit you're running against, but if you update and fix your metadata, I believe it will resolve your issue.

**Comment by jameskyle** [comment]
Is there a lint to test my meta? I've been hit with that before.
- update - 

I'll pull the latest 1.8 from ansible repo.

**Comment by jameskyle** [comment]
Ok, after updating I get the same error as you. Fixed the meta issue, but now get:

```
- gentoo was installed successfully
Traceback (most recent call last):
  File "/Users/jkyle/.virtualenvs/ansible/bin/ansible-galaxy", line 900, in <module>
    main()
  File "/Users/jkyle/.virtualenvs/ansible/bin/ansible-galaxy", line 894, in main
    fn(args, options, parser)
  File "/Users/jkyle/.virtualenvs/ansible/bin/ansible-galaxy", line 786, in execute_install
    role_dependencies = role_data['dependencies']
```

   KeyError: 'dependencies'

Though I have dependencies: [] in the main. 

I'll continue to debug my role, but looks like the update to 1.8 devel HEAD negates this bug. :)

**Comment by jimi-c** [comment]
@jameskyle sorry, currently there's no lint for galaxy metadata. When roles are added to Galaxy proper, there is error checking done there which can catch errors, however with this new functionality of grabbing directly from repos that step is skipped. We could add some better error catching around the YAML parsing, though that would be more useful to the role developer rather than the person installing the role.

**Comment by jimi-c** [comment]
Since this was a data issue, I've demoted it to a P3 and also updated the title to reflect the new direction.

Thanks!

**Comment by gildegoma** [comment]
For the records, I just put my two :credit_card: :money_with_wings: about @jameskyle last's comment:

> ```
>  ...
> File "/Users/jkyle/.virtualenvs/ansible/bin/ansible-galaxy", line 786, in execute_install
>     role_dependencies = role_data['dependencies']
> ```
> 
> KeyError: 'dependencies'
> 
> Though I have dependencies: [] in the main.

I was also bitten by this, when I unintentionally indented the `dependencies` key as a YAML child of `galaxy_info`, which is wrong as illustrated by https://github.com/jameskyle/ansible-gentoo/commit/092e683597f0af7eddc8e8f8b9755b3468b6fd05 fix.

For sure having a linter or embedded syntax checker would save lots of debugging time+hassle, so :+1: for this issue, though I think it is more a feature request rather than a bug.

**Comment by jameskyle** [comment]
Totally a feature.

**Comment by bcoca** [comment]
This has been fixed, not sure at which point, but using the original ticket's requirements.yml this works w/o issues:
```
ansible-galaxy install -r requirements.yml  -p /var/tmp/
- extracting gentoo to /var/tmp/gentoo
- gentoo was installed successfully
```
as such, i'm going to just close this ticket
