### ISSUE TITLE
Pass args to inventory script?

### ISSUE THREAD

**Issue by mgwilliams** [ansible/ansible#89]
I have a patch that allows passing args via ansible-playlist to an inventory script. It looks like this:

``` bash
ansible-playlist -i inventory.py --host-args some-arg
```

This as far as I can think, however, requires a change to the inventory scripts, as the patch calls the script like so:

To list groups/hosts:

```
inventory.py -l some-arg
```

And to get the host:

```
inventory.py -h the-host
```

At the moment args are only passed when getting the list -- I'm not sure whether there would be a use case for passing the args with -h (probably would need to be a separate CLI option, or maybe meta data passed back from the listing could be used).

The immediate use case for passing args to -l is to allow more dynamic generation of the hosts list.

**Comment by mpdehaan** [comment]
your pull request is about this topic so I think I can close this one.
