### ISSUE TITLE
Vagrant inventory plugin reports 127.0.0.1 for every machine instead of machine name

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#8913]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel 8cc3543918) last updated 2014/09/06 21:33:19 (GMT -400)
##### Environment:

N/A
##### Summary:

The vagrant inventory plugin reports every vagrant host as `127.0.0.1`, which means that it doesn't work when working with multiple vagrant virtual machines.
##### Steps To Reproduce:
1. Create a multi-machine Vagrantfile , for example:

```
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "vagrant1" do |vagrant1|
    vagrant1.vm.box = "ubuntu/trusty64"
  end
  config.vm.define "vagrant2" do |vagrant2|
    vagrant2.vm.box = "ubuntu/trusty64"
  end
  config.vm.define "vagrant3" do |vagrant3|
    vagrant3.vm.box = "ubuntu/trusty64"
  end
end
```
1. Bring up the vagrant machines

```
vagrant up
```
1. Run the inventory script

```
./vagrant.py --list
```
##### Expected Results:

```
{"vagrant": ["vagrant1", "vagrant2", "vagrant3"]}
```
##### Actual Results:

```
{"vagrant": ["127.0.0.1", "127.0.0.1", "127.0.0.1"]}
```

**Comment by mpdehaan** [comment]
When you say vagrant inventory plugin are you referring to the plugin in plugins/ in the source tree?

I'm believing not too many people use that one.

If you're asking about Vagrant itself, we don't maintain the vagrant provisioner.

**Comment by lorin** [comment]
I'm referring to the plugins file in the source tree: `plugins/inventory/vagrant.py`

I can submit a fix, unless you'd prefer to just delete it, but I think it makes a nice, simple example of a dynamic inventory script, even if it doesn't get much actual use in production.

**Comment by jimi-c** [comment]
I am unable to reproduce this with my setup, however it is quite different from the typical Vagrant setup (I'm using the kvm provider on Linux). Can you share the details of your vagrant and virtualbox versions, as well as any other details that might help us reproduce this?

Here is the output on my system, using the openstack-ansible example (https://github.com/openstack-ansible/openstack-ansible):

<pre>
# /etc/ansible/vagrant.py --list
{"vagrant": ["192.168.121.40", "192.168.121.190", "192.168.121.31", "192.168.121.75"]}
</pre>

**Comment by michalgasek** [comment]
Just checked and can confirm the bug.

```
$ uname -a
Darwin michal-mbp 13.3.0 Darwin Kernel Version 13.3.0: Tue Jun  3 21:27:35 PDT 2014; root:xnu-2422.110.17~1/RELEASE_X86_64 x86_64

$ ansible --version
ansible 1.6.10

$ vagrant --version
Vagrant 1.6.5

$ vboxmanage -v
4.3.6r91406

$ cat Vagrantfile
VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.6.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"

  (1..3).each do |i|
    config.vm.define "appserver0#{i}" do |appserver|
      appserver.vm.network :private_network, ip: "172.16.0.1#{i}"

      appserver.vm.provider "virtualbox" do |v|
        v.name = "appserver0#{i}"
      end
    end
  end

end
```

After `vagrant up`:

```
$ vagrant global-status
id       name        provider   state    directory                                                    
------------------------------------------------------------------------------------------------------  
08fe66d  appserver01 virtualbox running  /Users/michal/Projects/testing/vagrant_inventory 
07ac6f5  appserver02 virtualbox running  /Users/michal/Projects/testing/vagrant_inventory 
47d3a7c  appserver03 virtualbox running  /Users/michal/Projects/testing/vagrant_inventory
```

```
$ ./vagrant.py --list
{"vagrant": ["127.0.0.1", "127.0.0.1", "127.0.0.1"]}
```

From what I noticed in `vagrant.py`, it uses `vagrant ssh-config` command.

```
$ vagrant ssh-config
Host appserver01
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/michal/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL

Host appserver02
  HostName 127.0.0.1
  User vagrant
  Port 2200
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/michal/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL

Host appserver03
  HostName 127.0.0.1
  User vagrant
  Port 2201
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/michal/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL
```

**Comment by michalgasek** [comment]
I did some more research on this and I believe it will be hard to get this fixed (not even sure how one could get this right, suggestions?).
Question is whether it's Ansible's or actually Vagrant's "bug". Vagrant forces VMs running with VirtualBox provider to always use NAT as their 1st network interface (see https://github.com/mitchellh/vagrant/issues/3619).

I assume that using this NAT it sets up SSH configuration and does some "magic" and port forwarding (host -> guest) so that `vagrant ssh` can work smoothly. Even when one tries to add extra public/private network interfaces Vagrant will still use 127.0.0.1:[forwarded_port] instead of public/private IP assigned. This results in `vagrant ssh-config` reporting every VM running with `HostName 127.0.0.1` but different port (forwarded one - see my previous comment)...

**Comment by lorin** [comment]
@michalgasek We could always configure the plugin to set the `ansible_ssh_port` as one of the host variables. For example:

```
$./vagrant.py --host vagrant
{ "ansible_ssh_host": "127.0.0.1", "ansible_ssh_port": 2222,
  "ansible_ssh_user": "vagrant"}
```

**Comment by michalgasek** [comment]
@lorin we could, this will however make host_vars & group_vars unusable when working with multi machine environment if I'm not wrong?

**Comment by lorin** [comment]
@michalgasek  It works if Ansible identifies the hosts by their vagrant aliases. Say you have three machines in your Vagrantfile, vagrant1, vagrant2, and vagrant3. Then 

```
$ ./vagrant.py --list
{"vagrant": ["vagrant1", "vagrant2", "vagrant3"]}
```

And:

```
$ ./vagrant.py --host vagrant1
{"ansible_ssh_host": "127.0.0.1", "ansible_ssh_port": "2222", 
"ansible_ssh_private_key_file": "/Users/lorinhochstein/.vagrant.d/insecure_private_key", 
"ansible_ssh_user": "vagrant"}
```

I've actually got a local implementation of this that works for the VirutalBox backend (not sure about the other ones): https://gist.github.com/lorin/4cae51e123b596d5c60d

**Comment by michalgasek** [comment]
Ah, I see, cool! Send a pull request please if you are willing to fix it in devel, I can do some tests also (I'm using multi-machine vagrant setups with VirtualBox although for everyday I just use static inventories).

**Comment by bcoca** [comment]
needs_contributor

**Comment by lorin** [comment]
It looks like multi-vm support was added in 8113409d3454fe834e0e380d3246ff480201ce0e. Closing this out.
