### ISSUE TITLE
Ansible Galaxy (requirements file feature): Cloning git repositories via SSH failed

### ISSUE THREAD

**Issue by pschirch** [ansible/ansible#8937]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8 (devel)

Last check with: _ansible 1.8 (devel dc1f233e8d) last updated 2014/09/09 11:05:00 (GMT +200)_
##### Environment:

**Host:** Ubuntu 14.04 LTS
##### Summary:

We want to use the new **[role requirements file feature](http://docs.ansible.com/galaxy.html#advanced-control-over-role-requirements-files)** to share internal organization ansible roles over our gitlab server. Cloning git repositories via SSH currently doesn't work. The [Ansible Project Google Group](https://groups.google.com/forum/?hl=de#!topic/ansible-project/Bz-Zy4aK4tU) advised to define such repositories as follows:

``` yaml

---
- src: ssh://git@github.com:geerlingguy/ansible-role-php.git
  path: roles
```
##### Steps To Reproduce:
- create an `requirements.yml` file

``` yaml

---
- src: ssh://git@github.com:geerlingguy/ansible-role-php.git
  path: roles

```
- install requirements

``` bash
ansible-galaxy install -r requirements.yml
```
##### Expected Results:

Cloning repositories via SSH succesfully.
##### Actual Results:

``` bash
- downloading role from ssh://git@github.com:geerlingguy/ansible-role-php.git
- error: failed to download the file.
- ansible-role-php was NOT installed successfully.
- you can use --ignore-errors to skip failed roles.
```

**Comment by mpdehaan** [comment]
I'd probably use http:// for anonymous github downloads, not SSH.

Though in this case we can check and see what's up, that would be the ideal solution.

**Comment by pschirch** [comment]
My steps to reproduce the issue using SSH with Github - correct, but only to simplify matters. In my organization we use [Gitlab](https://about.gitlab.com/) (_open source software to collaborate on code_) to share our internal ansible roles. Every colleague can clone this repositories via SSH (_we do not  provide anonymous [Gitlab](https://about.gitlab.com/) downloads, because our security policy_).

Certainly I can use HTTP authentication:

``` yaml
---
- src: git+https://ourgitlabhost/example-group/example-role.git
  path: roles
```

But the `ansible-galaxy install -r requirements.yml` command requires username and password for every defined repository. Using SSH you add your private key to the ssh agent **only once**. 

Furthermore it should be possible cloning private repos from Github or other code collaboration platforms. In this case you also usually use SSH to take advantage from adding your private key once.

**Comment by jimi-c** [comment]
Currently ansible-galaxy only works with pure http/https URLs (it downloads the files with urllib2). We will have to extend this to shell out to git to do an actual clone.

**Comment by jimi-c** [comment]
cc @willthames

**Comment by willthames** [comment]
@jimi-c I'm pretty sure it uses git clone to get the stuff. This should all just work, and my original test cases included an ssh url (but I removed it because noone else would have ssh access to repos under my control). 

I'll take a look.

**Comment by willthames** [comment]
The problem here is that the 'magic code' that tells ansible-galaxy that github.com URLs are generally git repos (except when they're tar.gz archives) works only for URLs that contain `github.com/` (and not `github.com:`)
https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/__init__.py#L401

If you put `git+` at the start of your URL, it should work fine.

**Comment by pschirch** [comment]
If you mean this:

``` yaml
---
- src: git+://git@ourgitlabhost:example-group/example-ansible-role.git
  path: roles
```

it doesn't work.

Please consider my steps to reproduce. Use `git@github.com:geerlingguy/ansible-role-php.git` in your `requirements.yml` and try to clone via SSH.

**Comment by willthames** [comment]
You didn't follow my instructions. 

It should be

```
---
- src: git+ssh://git@ourgitlabhost:example-group/example-ansible-role.git
  path: roles
```

Basically put `git+` in front of a URL that `git clone` will work with.

**Comment by willthames** [comment]
Equally

```
---
- src: ssh://git@ourgitlabhost:example-group/example-ansible-role.git
  path: roles
  scm: git
```

should work too.

**Comment by pschirch** [comment]
Both definitions results in:

``` bash
- executing: git clone ssh://git@github.com:geerlingguy/ansible-role-php.git/ 
- command git clone ssh://git@github.com:geerlingguy/ansible-role-php.git/  failed
  in directory /tmp/tmpI7vZGQ
-  was NOT installed successfully.
- you can use --ignore-errors to skip failed roles.
```

**Comment by pschirch** [comment]
I checked out [latest devel](https://github.com/ansible/ansible/commit/a9b5b1bf55728b5d9dd38dc614be491a2c4217f0)  to try it again, but `ansible-galaxy` command only returns:

``` bash
- the specified role path /etc/ansible/roles does not exist
```

**Comment by mscherer** [comment]
I think that's a different issue. Maybe roles path should be auto created when it doesn't exist ?

**Comment by willthames** [comment]
See #8950 for the directory path not existing

If running `git clone ssh://git@path/to/repo` doesn't work, then the problem lies with your git URL, not ansible-galaxy. Not sure if the trailing slash in your URL is the problem here.

**Comment by willthames** [comment]
Ok, the problem is that an ssh URL looks slightly different to the ssh clone path you get from github.

Direct copy from github clone repo path
`git@github.com:geerlingguy/ansible-role-php.git`

Actual URL that works
`ssh://git@github.com/geerlingguy/ansible-role-php.git`

You have to replace the `:` with a `/`. And it needs to be a URL (i.e. contain `://`) otherwise ansible-galaxy assumes it's a filesystem path.

We could probably improve the ssh URL documentation - this is just how git clone works, it seems.

**Comment by pschirch** [comment]
I can confirm this, both repository definitions works correctly when using the adjusted URL:

**Option A**

``` yaml
---
- src: git+ssh://git@ourgitlabhost/example-group/example-ansible-role.git
  path: roles
```

**Option B**

``` yaml
---
- src: ssh://git@ourgitlabhost/example-group/example-ansible-role.git
  path: roles
  scm: git
```

Improving documentation sounds nice. But this SSH URL pattern is using by many code collaboration tools (_like Github, Gitlab, Jira, ..._). Shouldn't `ansible-galaxy` implement this pattern too?

Thank you for your patience.

**Comment by willthames** [comment]
Hi,
Does Jira really have git urls - that's clearly a part of Jira I'm unfamiliar with! I'm pretty sure the ssh URL pattern used is exactly that used by Stash. 

To be honest, I haven't put much effort into telling the difference between a git ssh repo and a filesystem path - the path that comes out of github doesn't start `ssh://` and so the current code thinks it's a file.

Looking for e.g. an `@` in the role name could be another approach. I know @mscherer has some improvements in mind in repo detection, it shouldn't be a hard fix.

**Comment by willthames** [comment]
Allowing that kind of ssh clone path was actually a one-line change. Although I added some tests too.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by rdonkin** [comment]
The working `git+ssh://` URL format doesn't seem to have made it into the docs.  It would be great if the [Ansible Galaxy doc page](http://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html) included an example of a working `git+ssh://` URL.

**Comment by freeeflyer** [comment]
no but the doc clearly states : 

```
# from GitLab or other git-based scm
- src: git@gitlab.company.com:mygroup/ansible-base.git
  scm: git
  version: "0.1"  # quoted, so YAML doesn't parse this as a floating-point value
```
