### ISSUE TITLE
backup=yes not expected result when using with_items

### ISSUE THREAD

**Issue by aw** [ansible/ansible#8939]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.10
##### Environment:

Debian Linux 7.6 amd64
##### Summary:

At the end of this task, the backup file only contains the changes from the last `with_items` entry, and not the previous changes made to the file.

I'm wondering if this is because the backup file has the exact same timestamp on each change?

`sshd_config.2014-09-09@10\:25~`
##### Steps To Reproduce:

```
- name: Modify the /etc/ssh/sshd_config
  lineinfile: >
    state=present
    backup=yes
    dest=/etc/ssh/sshd_config
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - { regexp: '^Port 22', line: 'Port 5222' }
    - { regexp: '^ServerKeyBits 2048', line: 'ServerKeyBits 4096' }
    - { regexp: '^PermitRootLogin yes', line: 'PermitRootLogin no' }
    - { regexp: '^ListenAddress', line: 'ListenAddress ::1' }
  tags:
    - ssh
```
##### Expected Results:

A proper backup file with all the changes from this task.
##### Actual Results:

```
# diff /etc/ssh/sshd_config.2014-09-09@10\:25~ /etc/ssh/sshd_config 
88a89
> ListenAddress ::1
```

**Comment by mpdehaan** [comment]
There seems to be some confusion above about what this does.

This is actually executing the "backup" command once per each item in the loop.  The backup file will contain the timestamp, so it should be generating 4 backups.

The backup parameter is something that is going to be deprecated in future versions of Ansible, possibly with a remote backup replacement.

As such, I wouldn't expect it to make one backup here, as it's asking for 4.  The last one will contain only the last.

If you'd like to discuss this further, you're welcome to stop by ansible-project.

**Comment by aw** [comment]
No thanks.
