### ISSUE TITLE
host_vars  looks for files in host_files instead of host_vars

### ISSUE THREAD

**Issue by AndreasDavour** [ansible/ansible#894]
In my playbook I have:
  vars_files:
    - /etc/ansible/host_files/${ansible_hostname}

```
  with_items: $host_packages
```

and in that path I have the file named as the target host with:
host_packages: [ perl, ruby ]

But!

http://ansible.github.com/patterns.html
under the paragraph "Splitting Out Host and Group Specific Data"
refers to /etc/ansible/host_vars/foosball

Am I misunderstanding how things should work, or do we have a mismatch between code and docs? I read the docs and was under the impression I could have a host_vars: directive in my playbook. Might be worth making that clearer.

**Comment by sbocahu** [comment]
.../host_vars/hostname and ../group_vars/groupname are loaded automatically if they exist.
In addition to those per-host and per-file configuration file, you can load extra files with vars_files.

also, a list in yaml is defined that way:

```
var:
  - item1
  - item2
```

There is no bug here.

**Comment by mpdehaan** [comment]
Yep -- no bug here.  

With the inception of the "host_vars" and "group_vars" built in support, you have no need to add a vars_files load based on ansible_hostname.  This is intended to help people to stop thinking about facts and vars_files unless they really need something complicated.   You could continue to do what you are doing, but it's not needed anymore.

**Comment by tetherit** [comment]
I don't get it, I have a client.crt and client.key (openvpn openssl certificates) - I am placing them in: host_files/hostname/openvpn-certs/ -- but it seems when I do a copy, that directory is not looked in?

Where would I put host specific files like this?
