### ISSUE TITLE
ansible-galaxy should not need roles directory to exist

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#8950]
Commit aa46fcf09 introduces a check to ensure that `roles_path` exists. 

However, previously, if roles_path did not exist, it just created the directories anyway. 
https://github.com/ansible/ansible/blob/devel/bin/ansible-galaxy#L547
On that basis I'm not sure that the check for whether the directory exists is in the right place (it's nice to just blow away the roles directory entirely sometimes and reinstall from rolesfile)

I would like to understand the reason for this commit (it doesn't seem to be linked to an issue or PR)

cc @jimi-c

**Comment by jimi-c** [comment]
For some reason when I was testing this yesterday, it was throwing an error when the roles path did not exist. I can retest that and check your PR against it.

Thanks!

**Comment by willthames** [comment]
You may well have been taking a different path through the code that does require the check. 

As long as any new fix works with `cd test/integration; make test_galaxy`, it should be good.

**Comment by abadger** [comment]
Started discusssion in the pull request of this so closing this issue and we can continue there.
