### ISSUE TITLE
Add support for ansible_ssh_proxy

### ISSUE THREAD

**Issue by aleemb** [ansible/ansible#8963]
As per the discussion on [ansible-project](https://groups.google.com/forum/#!topic/ansible-project/PdJmnVMhHn0) it would be nice to have a feature for connecting to machines via a bastion server. This would rid the need for configuring an SSH agent or setting up `.ssh/config`.

Personally, I find this would be more useful since AWS now defaults to VPC deployments and this is something all AWS+Ansible users will increasingly run into.

**Comment by mpdehaan** [comment]
Yep, that would be perhaps interesting.

Is this something you'd like to work on, perhaps?

**Comment by tzz** [comment]
I don't know Python well enough to attempt this, but wanted to add my vote of support for this ticket.

**Comment by MattRogish** [comment]
:+1:

**Comment by gamename** [comment]
Excellent idea.  I can really use this.
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by erictchiu** [comment]
Michael, can you point us to where this is handled in the ansible codebase so we can collaborate on the proxy code?

**Comment by bcoca** [comment]
Closing this in favor of  #9477 #9122
