### ISSUE TITLE
Docker image name parsing can produce incorrect results

### ISSUE THREAD

**Issue by bensymonds** [ansible/ansible#8983]
##### Issue Type:

Bug Report
##### Ansible Version:

`ansible 1.8`
`devel`@`1c3039f079b6157b3348a2e4c9636a20070df150`
##### Environment:

N/A
##### Summary:

This was broken in https://github.com/ansible/ansible/commit/1c3039f079b6157b3348a2e4c9636a20070df150.

One way of specifying a docker image is:

```
hostname:port/image:tag
```

The above commit attempts to find the tag name by splitting once on `:` and taking the second part. This of course produces `port/image:tag`, which is wrong. Either you need to split multiple times on `:` and take the last part, or `rsplit` or something.
##### Steps To Reproduce:

Tricky to test because you need to specify a registry with a port. Assuming you have one running at hostname `registry` on port 80, with an image called `foo` with tag `v1`:

```
ansible localhost -m docker -a 'image=registry:80/foo:v1 state=running command=hostname'
```
##### Expected Results:

Image downloads and runs. Ansible command succeeds.
##### Actual Results:

```
localhost | FAILED >> {
    "failed": true,
    "msg": "failed to pull the specified image: registry:80/foo:v1"
}
```

**Comment by mscherer** [comment]
Looking at the code, I wonder how this would work since there is a explicit registry parameter to give the registry, and it doesn't seems to take in account anything from image parameters.

**Comment by bensymonds** [comment]
Yeah I was a bit bemused when the `registry` module parameter was added, because the description of it ("The remote registry URL to use for pulling images") looked wrong. Reading the module code, I see that the `registry` is used for authentication, so that makes it an "index", not a "registry" - see http://docs.docker.com/reference/api/hub_registry_spec/. Where you authenticate and where you pull the image from are two different things in Docker. So the parameter might be better named `index`. Then the actual image is pulled from a "registry" determined by the `image` parameter.

I do find this all quite confusing though, as I think do a lot of the Docker community! Possibly because it's still a bit of a work-in-progress on the Docker side (i.e. they are still figuring out how the index/registry/image ecosystem should work).

**Comment by jimi-c** [comment]
@bensymonds I thought we had just fixed this, though we'll take a look into it. I was under the impression that the way we did it now was to split on the `/`, take the second part and then split on the `:`, so as to avoid splitting on the port separator incorrectly.

**Comment by abadger** [comment]
Thanks for reporting this!  I tried to get fancy about the text handling but then left out a step without realizing.  Looking at the code again, the fancy approach isn't as clear as being more straightforward.  I'll revise that at the same time as I fix the issue.

**Comment by bensymonds** [comment]
No worries! This area of Docker is pretty messy anyway. I'm hoping they'll improve it to be a little easier to use in future.

**Comment by abadger** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by gesellix** [comment]
Looking at the commit I'm not sure if all edge case will work. Have a look at the actual Docker implementation at https://github.com/docker/docker/blob/master/pkg/parsers/parsers.go#L72

What happens with a repository url like `registry:80/user/foo:tag`?

**Comment by gesellix** [comment]
oops, sorry, I didn't read the last comment. I'll head over to the mailing lists.
