### ISSUE TITLE
"backup=yes" on lineinfile task using "with_items" block only preserves final change

### ISSUE THREAD

**Issue by EvanK** [ansible/ansible#9027]
##### Issue Type:

Bug Report
##### Ansible Version:
- ansible 1.8 (devel c6b26ff7c7) last updated 2014/09/16 16:36:02 (GMT +000)
##### Environment:

Ubuntu 14.04 (64bit)
##### Summary:

A `lineinfile` task that uses `with_items` to make several edits at once, and `backup=yes` to create backups generates a single backup file. The problem is that said backup file preserves only the change from the final item.

My best guess is that each item -- as it is applied -- generates a timestamped backup, blindly overwriting any existing backup with the same timestamp (since they all occur within less than a second of each other).
##### Steps To Reproduce:

This example task modifies several directives from a mod_pagespeed config file.

```
- name:           Configure for downstream cache
  lineinfile:     dest=/etc/apache2/mods-available/pagespeed.conf regexp="^(\s*)#?\s*?(ModPagespeedDownstreamCache{{ item.pattern }}$" line="\1\2 {{ item.replacement }}" backrefs=yes backup=yes
  with_items:
    - { pattern: "PurgeLocationPrefix)( http.*)?", replacement: "http://localhost:80" }
    - { pattern: "PurgeMethod) [A-Za-z]+", replacement: "PURGE" }
    - { pattern: "RewrittenPercentageThreshold) [0-9]+", replacement: "95" }
  sudo:           yes
```

These are the relevant lines from said config, _before_ running the task:

```
$ cat /etc/apache2/mods-available/pagespeed.conf | grep ModPagespeedDownstreamCache
    # ModPagespeedDownstreamCachePurgeLocationPrefix and
    # ModPagespeedDownstreamCacheRebeaconingKey are deliberately left empty here
    # ModPagespeedDownstreamCachePurgeLocationPrefix
    # ModPagespeedDownstreamCachePurgeMethod PURGE
    # ModPagespeedDownstreamCacheRewrittenPercentageThreshold 95
    # ModPagespeedDownstreamCacheRebeaconingKey
```

And this is the output of the task itself:

```
TASK: [pagespeed | Configure for downstream cache] ****************** 
changed: [local.example.com] => (item={'pattern': 'PurgeLocationPrefix)( http.*)?', 'replacement': 'http://localhost:80'})
changed: [local.example.com] => (item={'pattern': 'PurgeMethod) [A-Za-z]+', 'replacement': 'PURGE'})
changed: [local.example.com] => (item={'pattern': 'RewrittenPercentageThreshold) [0-9]+', 'replacement': '95'})
```
##### Expected Results:

I'd expect a single backup taken before _any_ of the items are applied:

```
$ diff -u /etc/apache2/mods-available/pagespeed.conf.* /etc/apache2/mods-available/pagespeed.conf
--- /etc/apache2/mods-available/pagespeed.conf.bak  2014-09-16 16:54:32.993739932 +0000
+++ /etc/apache2/mods-available/pagespeed.conf  2014-09-16 16:45:45.275891893 +0000
@@ -110,9 +110,9 @@
     # ModPagespeedDownstreamCacheRebeaconingKey are deliberately left empty here
     # in order to force the webmaster to choose appropriate value for these.
     #
-    # ModPagespeedDownstreamCachePurgeLocationPrefix
-    # ModPagespeedDownstreamCachePurgeMethod PURGE
-    # ModPagespeedDownstreamCacheRewrittenPercentageThreshold 95
+    ModPagespeedDownstreamCachePurgeLocationPrefix http://localhost:80
+    ModPagespeedDownstreamCachePurgeMethod PURGE
+    ModPagespeedDownstreamCacheRewrittenPercentageThreshold 95
     # ModPagespeedDownstreamCacheRebeaconingKey

     # Other defaults (cache sizes and thresholds):
```
##### Actual Results:

The backup file only preserves the _final_ item changed in the file:

```
$ diff -u /etc/apache2/mods-available/pagespeed.conf.2014-09-16@16:45~ /etc/apache2/mods-available/pagespeed.conf
--- /etc/apache2/mods-available/pagespeed.conf.2014-09-16@16:45~    2014-09-16 16:45:45.171887000 +0000
+++ /etc/apache2/mods-available/pagespeed.conf  2014-09-16 16:45:45.275891893 +0000
@@ -112,7 +112,7 @@
     #
     ModPagespeedDownstreamCachePurgeLocationPrefix http://localhost:80
     ModPagespeedDownstreamCachePurgeMethod PURGE
-    # ModPagespeedDownstreamCacheRewrittenPercentageThreshold 95
+    ModPagespeedDownstreamCacheRewrittenPercentageThreshold 95
     # ModPagespeedDownstreamCacheRebeaconingKey

     # Other defaults (cache sizes and thresholds):
```

**Comment by EvanK** [comment]
After a bit more digging, I think this is a limitation of [`module.backup_local`](https://github.com/ansible/ansible/blob/b376e208c7d9e2fddd19ed964628c5d99bb71150/lib/ansible/module_utils/basic.py#L1225)

Perhaps it should skip the backup operation if `backupdest` already exists?

**Comment by mpdehaan** [comment]
Honestly the backup feature needs to be ripped out and replaced with a generic remote backup solution.   This is going to be the answer here, longer term.

What's happening here is it's making a backup with each change, and that's not keeping some of the older ones around.

As we already have a note to make backup do actual remote backups, I'm going to close this one -- though I completely agree it's suboptimal in it's present state.

Hope this is understandable!

Thanks!

**Comment by EvanK** [comment]
That makes sense.

Have you considered some sort of git-based backup? Say, creating a new repo (if one doesn't exist) at provision start, and then each backup call adding a commit noting the role/task where the file was modified...and then adding a tag at the end of each provision.

Just a thought (and certainly not well thought out at a spitballing stage)
