### ISSUE TITLE
ansible-vault returns zero exit code when called with an unknown command

### ISSUE THREAD

**Issue by jscheid** [ansible/ansible#9029]
**Issue Type:**

Bug Report

**Ansible Version:**

1.7.1, also HEAD (b376e208c7d9e2fddd19ed964628c5d99bb71150)

**Environment:**

Tested on OS X 10.9, but other environments are probably also affected.

**Summary:**

`ansible-vault` returns a zero exit code when called with an unknown command, such as when trying to use the `view` command in version 1.7.1. It should return a non-zero exit code instead.

**Steps To Reproduce:**

```
$ ansible-vault foo ; echo $?
Usage: ansible-vault [create|decrypt|edit|encrypt|rekey|view] [--help] [options] file_name

Options:
  -h, --help  show this help message and exit

See 'ansible-vault <command> --help' for more information on a specific command.

0
```

**Expected Results:**

Non-zero exit code, indicating failure.

**Actual Results:**

Zero exit code, indicating success.

**Comment by bcoca** [comment]
In current devel it now returns a 5 exit code (invalid options passed) so I'm closing this ticket as it has been resolved.
