### ISSUE TITLE
Ability to dump host_variables

### ISSUE THREAD

**Issue by uvizhe** [ansible/ansible#9036]
##### Issue Type:

“Feature Idea”
##### Ansible Version:

c6b26ff7c79cd73c98b161022044f3678ab7378d
##### Summary:

Hi,
I need to dump all the vars available at certain steps of playbook so I tried to follow [this tip](https://coderwall.com/p/13lh6w).
At first it looks like it does what I need but then I noticed that dumping `vars` gives me variables specified only in role's vars file and no vars inherited from `group_vars/`.
Inspecting `lib/ansible/runner/__init__.py` I see this:

```
# use combined_cache and host_variables to template the module_vars                  
# we update the inject variables with the data we're about to template               
# since some of the variables we'll be replacing may be contained there too          
module_vars_inject = utils.combine_vars(host_variables, combined_cache.get(host, {}))
module_vars_inject = utils.combine_vars(self.module_vars, module_vars_inject)        
module_vars = template.template(self.basedir, self.module_vars, module_vars_inject)
```

and I see that vars inherited from `group_vars` are contained in `host_variables`.
Now I'm in doubt whether they should get in `module_vars` here and there's just a bug at this point
or they should not and then I'd like to add them later to `inject` dict like it's done with `module_vars`:

```
inject['vars']        = self.module_vars
```

**Comment by uvizhe** [comment]
Since there's no way to completely delete the issue I decided not to close it and wait for an answer instead of duplicating the question to mail-list.

**Comment by uvizhe** [comment]
Even better if there will be a way to dump all vars from `inject`.

**Comment by jimi-c** [comment]
Hi @uvizhe, this is definitely more of a mailing list question. I'd recommend moving this discussion to ansible-devel for now, where we can discuss this.

Thanks!
