### ISSUE TITLE
group_by putting hosts in the wrong group

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#9037]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible-playbook 1.8 (devel e9229cfeaa) last updated 2014/09/17 11:15:48 (GMT +200)
##### Environment:

N/A
##### Summary:

It seems that something in commit 4a9cf3f3f2924d9543fd17413da255d78c45cc09 broke group_by.  After this commit, group_by is not places hosts in the correct groups.
##### Steps To Reproduce:

inventory

```
[myhosts]
host1 var="foo"
host2 var="foo"
host3 var="bar"
```

playbook

```
- hosts: myhosts
  tasks:
  - set_fact: testfact="group_{{ var }}"
  - group_by: key={{ testfact }}
```
##### Expected Results:

This should function the same way on 1.8 as it does on 1.7.1, which is:

```
PLAY [myhosts] ****************************************************************

GATHERING FACTS ***************************************************************
ok: [host2]
ok: [host3]
ok: [host1]

TASK: [set_fact testfact="group_{{ var }}"] ***********************************
ok: [host1] => {"ansible_facts": {"testfact": "group_foo"}}
ok: [host2] => {"ansible_facts": {"testfact": "group_foo"}}
ok: [host3] => {"ansible_facts": {"testfact": "group_bar"}}

TASK: [group_by key={{ testfact }}] *******************************************
changed: [host1] => {"changed": true, "groups": {"group_bar": ["host3"], "group_foo": ["host1", "host2"]}}
```

As you can see, two groups are created, **group_foo** and **group_bar**, and contain the correct hosts.
##### Actual Results:

```
PLAY [myhosts] ****************************************************************

GATHERING FACTS ***************************************************************
ok: [host1]
ok: [host3]
ok: [host2]

TASK: [set_fact testfact="group_{{ var }}"] ***********************************
ok: [host1] => {"ansible_facts": {"testfact": "group_foo"}}
ok: [host2] => {"ansible_facts": {"testfact": "group_foo"}}
ok: [host3] => {"ansible_facts": {"testfact": "group_bar"}}

TASK: [group_by key={{ testfact }}] *******************************************
changed: [host1] => {"changed": true, "groups": {"group_foo": ["host1", "host2", "host3"]}}
```

As you can see all hosts are added into **group_foo**.

**Comment by jimi-c** [comment]
@jsmartin I believe this was addressed via ed3c9c40ca8b52f54e3ae1cf23184e7f5b2df262, which I ran across on my own during more testing. I've tested the above sample and the output now matches the expected, so I'm closing this.

Thanks!
