### ISSUE TITLE
Add documentation for --step and --start-at-task

### ISSUE THREAD

**Issue by jimi-c** [ansible/ansible#9041]
##### Issue Type:

Documentation Report
##### Ansible Version:

N/A
##### Environment:

N/A
##### Summary:

The documentation site is missing docs on several command line options like `--step` and `--start-at-task`. There may be others.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by bcoca** [comment]
closing this as we have a PR to track it
