### ISSUE TITLE
Consider documenting and recommending YAML Hash over the custom key/value format.

### ISSUE THREAD

**Issue by damncabbage** [ansible/ansible#9067]
##### Issue Type:

Bug Report / Documentation Report
##### Ansible Version:

Ansible 1.7.1
##### Environment:

Ubuntu 14.04 host and target
##### Summary:

The `example: "foo=bar baz={{ quux }}"` format recommended throughout the docs breaks in ways that to defend against would be infeasible (or in some cases, impossible).
##### Steps to Reproduce:

Please consider this example playbook (variable declarations at bottom):

``` yaml
# site.yml
- hosts: exhost
  tasks:
    # Broken.
    - copy: "dest=/tmp/1.txt content={{ contains_quote }}"

    # Also broken.
    - copy: dest=/tmp/2.txt content="{{ contains_quote }}"

    # "Fixed" by swapping quotes, but...
    - copy: dest=/tmp/3.txt content='{{ contains_quote }}'

    # Also broken
    - copy: dest=/tmp/4.txt content='{{ contains_alt_quote }}'

  vars:
    contains_quote: 'Hello"World'
    contains_alt_quote: "Hello'World"
```

We can twiddle each of the variables for each particular example, but also consider that these variables could be:
- Written in a vars file that someone _else_ on your team is managing,
- The result of a file lookup, or
- Populated dynamically by a var_plugin.

(Please note that `copy` / `content=` themselves are examples; this could've easily been `- campfire: room=example subscription=example token=example msg="{{ contains_quote }}"` or something.)
##### Expected Results:

Failure. The custom key-value format is not viable for the mentioned cases. It arguably should not be recommended at all, or **at the very least** not for anything involving the use of variables or anything else that is Jinja2-interpolated.

Instead, using plain YAML hashes works reliably, regardless of the values to be interpolated:

``` yaml
- copy:
    dest: "/tmp/5.txt"
    content: "{{ contains_quote }}"
- copy:
    dest: "/tmp/6.txt"
    content: '{{ contains_alt_quote }}'

# Inline example:
- copy: { dest: "/tmp/7.txt", content: "{{ contains_quote }}" }
```
##### Actual Results:

For each failing example respectively:

```
TASK: [copy dest=/tmp/1.txt content={{ contains_quote }}] *********************
fatal: [exhost] => error parsing argument string 'dest=/tmp/1.txt content=Hello"World', try quoting the entire line.

TASK: [copy dest=/tmp/2.txt content="{{ contains_quote }}"] *******************
fatal: [exhost] => error parsing argument string 'dest=/tmp/2.txt content="Hello"World"', try quoting the entire line.

TASK: [copy dest=/tmp/4.txt content='{{ contains_alt_quote }}'] ***************
fatal: [exhost] => error parsing argument string 'dest=/tmp/4.txt content='Hello'World'', try quoting the entire line.

TASK: [campfire room=example subscription=example token=example msg="{{ contains_quote }}"] ***
fatal: [exhost] => error parsing argument string 'room=example subscription=example token=example msg="Hello"World"', try quoting the entire line
```

**Comment by redbaron** [comment]
wow, didn't even know about this syntax. Using it fixes the problem I have in #9172  with copy module.

**Comment by damncabbage** [comment]
That's fine. I ran across it while looking at the https://github.com/debops set of ansible-\* playbooks; thank them. :smile:

**Comment by mpdehaan** [comment]
This has been a frequent list topic and isn't going to happen.

I'm sorry if you disagree but you are completely welcome to use this other format if you like.

The content thing is just a small case, but I would recommend just using the "src" parameter for copy most of the time, or even the template module for most people as at some point you are likely going to want to push a larger file.

**Comment by damncabbage** [comment]
> The content thing is just a small case, but I would recommend just using the "src" parameter ...

I specifically said:

> (Please note that `copy` / `content=` themselves are examples; this could've easily been
> `- campfire: room=example subscription=example token=example msg="{{ contains_quote }}"`
> or something.)

... for this very reason.

Regardless, I respect your decision. Thanks for clarifying this.

**Comment by mpdehaan** [comment]
To be clear, I'm fine with showing this in the copy docs, I don't want to show it _everywhere_ in the application.

**Comment by mpdehaan** [comment]
Yeah this could go on the YAML Syntax page w/o changing the above examples
everywhere I think.

We certaintly do use it when passing structured data in the EC2 docs.
