### ISSUE TITLE
service module 'enabled' always reports as changed

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#9074]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (latest devel)
##### Environment:

Centos 6.5
##### Summary:

When `enabled` parameter of the `service` module is used, the module always reports as changed. This works without any problems on Ansible 1.7.
##### Steps To Reproduce:

You can use this playbook:

```

---
- hosts: test
  tasks:
    - service: name=ntpd enabled=yes
```
##### Expected Results:

It should report as unchanged:

```
PLAY [test] ************************************************************

TASK: [service name=ntpd enabled=yes] *****************************************
ok: [test]

PLAY RECAP ********************************************************************
test                : ok=1    changed=0    unreachable=0    failed=0
```
##### Actual Results:

It always reports as changed, no matter how many time your run the playbook:

```
PLAY [test] ************************************************************

TASK: [service name=ntpd enabled=yes] *****************************************
changed: [test]

PLAY RECAP ********************************************************************
test                : ok=1    changed=1    unreachable=0    failed=0

```

**Comment by mscherer** [comment]
Git bisect show this appeared on 8dfc54b51780

**Comment by mscherer** [comment]
Fix on https://github.com/ansible/ansible/pull/9084

**Comment by resmo** [comment]
:+1:

**Comment by abadger** [comment]
#9084 has been merged.  Which should fix the issue reported here.  Please let us know via the mailing list or a new bug report if the problem recurs.  Thanks!

**Comment by randombk** [comment]
Hi, this error is occuring again for me.

Ansible version: 1.9.3

Environment: Debian Jessie x64

**Comment by mscherer** [comment]
Hi, As said in the last comment, can you open a new bug ?

**Comment by goldyfruit** [comment]
Same issue here.
@randombk did you create the issue ?

**Comment by emielmolenaar** [comment]
Same issue here.
@randombk did you create the issue ?
