### ISSUE TITLE
galaxy: x.x.xx versions not listed in correct order

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#9083]
##### Issue Type:

Bug Report
##### Ansible Version:

N/A
##### Environment:

N/A
##### Summary:

I just released version 1.2.10 of my PHP role on Galaxy ([link](https://galaxy.ansible.com/list#/roles/432)), and noticed that the version history on Galaxy is not in chronological order, but is in a semantic version order that doesn't account for double-digit versions.

So 1.2.10 should be above 1.2.9 (etc.) in the list...
##### Steps To Reproduce:

Create a role, submit to Galaxy, release enough point releases to have double-digits, see non-chronological ordering.
##### Expected Results:

The listing should show:

```
1.2.10  9/21/14 3:16 AM
1.2.9   9/2/14 2:36 PM
1.2.8   8/5/14 1:19 PM
...
1.2.1   5/15/14 2:09 AM
...
1.0.0   3/5/14 1:49 PM
```
##### Actual Results:

```
1.2.9   9/2/14 2:36 PM
1.2.8   8/5/14 1:19 PM
...
1.2.2   5/15/14 2:10 AM
1.2.10  9/21/14 3:16 AM
1.2.1   5/15/14 2:09 AM
...
1.0.0   3/5/14 1:49 PM
```

**Comment by mpdehaan** [comment]
Versions are actually just tags but I agree that should be sorted by date.   As we keep galaxy in a seperate tracker, I'll record this over there.

Thanks!

**Comment by geerlingguy** [comment]
Thanks for the prompt response!
