### ISSUE TITLE
bug: service module regression in devel

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#9094]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8-devel only
##### Environment:

What OS are you running Ansible from: Ubuntu 14.04

What OS are you managing?  Centos 6
##### Summary:

this commit e294e31fd3e083cbf19e26fd551ed4f7e2f38e37 seems to cause, 

`service: name=example-service state=started changed=yes`

 always returns `changed`. The same task before this commit don't report changed. 
##### Expected Results:

should not report changed.
##### Actual Results:

reports changed.

**Comment by akuznecov** [comment]
duplicate of https://github.com/ansible/ansible/issues/9074

**Comment by resmo** [comment]
confirm fix for #9074 fixes problem

**Comment by abadger** [comment]
#9084 has been merged which should fix this issue.  Please let us know via the mailing list or a new bug report if this issue is still occurring.  Thanks!
