### ISSUE TITLE
validate should not require presence of %s

### ISSUE THREAD

**Issue by jooadam** [ansible/ansible#9112]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.1
##### Environment:

Controlling machine is Ubuntu 12.04, controlled is Ubuntu 14.04.
##### Summary:

The `template` module’s `validate` parameter requires the presence of %s in the value, which in certain cases prevents it to be used to check the syntax of included files. Virtual host files in Nginx, for example, must be tested through the including file.
##### Steps To Reproduce:

```
- name:   site configuration is in place
  action: template src=nginx/site dest=/etc/nginx/sites-available/ validate="nginx -t -c /etc/nginx/nginx.conf"
```
##### Expected Results:

The specified file is validated.
##### Actual Results:

```
msg: validate must contain %s: nginx -t -c /etc/nginx/nginx.conf
```

Right now, the only workaround I was able to come up with was using `nginx -t -c /etc/nginx/nginx.conf -p %s`, which makes me shiver.

**Comment by bcoca** [comment]
I think you miss the purpose of validate, it works against the temporary
file BEFORE putting it into place, to avoid putting bad configs for
services which cannot be easily backed out from (sudo).​

If you make it validate the final target, you are only validating the
current (before your modification) configuration file.

**Comment by jooadam** [comment]
You’re right, I wasn’t aware of that. This complicates the situation, the problem, however, remains. Perhaps a `validate-after` parameter could check an arbitrary file after putting the new one in place, and on error revert to the previous state?

**Comment by bcoca** [comment]
that would also require a backup, this complicates the actions and requires
many more moving parts.​

**Comment by jooadam** [comment]
Indeed, a backup is needed for that. I don’t know how much this complicates the implementation.

**Comment by bcoca** [comment]
at this point I would say you want to create several tasks
1. puts the file into place, using backup=yes, runs a 'validation handler'
2 the validation run, calls a 'rollback' handler
3 the rollback handler moves the backup back into place
​

**Comment by jooadam** [comment]
Another tool the configuration of which currently cannot be validated is Upstart, as `init-checkconf` will claim that `File must end in .conf`.

**Comment by bcoca** [comment]
Not all tools allow for a config file as a parameter, it also does not work
for when the config is separated in multiple files. These are known
limitations, it was not meant to work for every possible scenario.​

Most cases are should be easily recoverable, in the case of sudoers this
could prevent you from accessing the box, which was the main reason for
this feature, also I had cake envy
http://jpmens.net/2013/02/12/sudo-bake-me-a-cake/.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:
- validate shouldn't need a %s

However, however what is happening is that:
- validate is used to copy files over or not, and fits some other specific use cases
- it requires the name of the file 
- but there are still other ways to test and validate in ansible without using this parameter

We would suggest:
- breaking this up into multiple steps in Ansible, using one task to copy the item over
- validate it
- then move it over if the validation passes

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by Hubbitus** [comment]
You may do some trick there like:

```
    validate: bash -c 'nginx -t -c /dev/stdin <<< "events {worker_connections 1;} http { include %s; }"'
```

**Comment by METAJIJI** [comment]
Simpler solution `validate: 'nginx -t #%s'`

**Comment by bcoca** [comment]
@Hubbitus that will test the 'previous' configuration, not the new one
