### ISSUE TITLE
Skipped tasks still register or modify variables... but shouldn't?

### ISSUE THREAD

**Issue by nathansoz** [ansible/ansible#9123]
Issue Type:

Bug report

Ansible Version:

ansible 1.7.1

Environment:

Fedora 20

Summary:

If you have two tasks (say one is run when a == 1 and the other is run when a == 2) that register to the same variable, the variable gets overwritten even when the task is skipped. See my example below if this explanation is unclear.

Steps To Reproduce:
- name: get user home
  shell: sudo su - {{ ssh_user }} -c 'echo $HOME'
  register: ssh_user_home
  when: ssh_user != "root"
- name: get root home
  shell: 'echo $HOME'
  register: ssh_user_home
  when: ssh_user == "root"

Expected Results:

I would expect ssh_user_home to be equal to the ssh_user's home that is passed in.

Actual Results:

ssh_user_home is correct for root, but incorrect for any other user. This is because ssh_user_home gets overwritten by the second task, even if it is skipped. I would expect a skipped task to not register or modify variables.

**Comment by sivel** [comment]
It is the expected behavior that a skipped task will still register a result.  A skipped task will register a 'skipped' attribute, so that you can inspect whether the task was skipped or not in a subsequent task.

Typically you should use different variables to avoid the problem you are encountering.

**Comment by nathansoz** [comment]
That makes sense. I didn't know if it was an expected behavior. I was just using the same variable to avoid duplicating code. It is easily worked around.
