### ISSUE TITLE
debug module: msg is truncated after the occurrence of a space character

### ISSUE THREAD

**Issue by Ernest0x** [ansible/ansible#9124]
## Issue Type:

 Bug Report
## Ansible Version:

1.7.1
## Environment:

Archlinux
## Summary:

Using the debug module with the 'ansible' tool, if you supply a msg parameter with a value that contains spaces, it will display a truncated msg, starting eating the string from the first occurrence of a space character.
## Steps To Reproduce:

```
ansible -m debug -a msg="test1 test2" localhost
```
## Expected Results:

```
localhost | success >> {
    "msg": "test1 test2"
}
```
## Actual Results:

```
localhost | success >> {
    "msg": "test1"
}
```

**Comment by Ernest0x** [comment]
However, it works as expected when "overquoting" like this:

```
ansible -m debug -a msg="\"test1 test2\"" localhost
```

**Comment by sivel** [comment]
This appears to be due to how optparse handles command line arguments.

Proper quoting to get the results you are expecting is:

```
ansible -m debug -a 'msg="test1 test2"' localhost
```

With your example, what you get directly from optparse is:

```
msg=test1 test2
```

notice the above has quotes removed.

**Comment by Ernest0x** [comment]
@sivel yes, that must be the reason. So I guess, this can be closed. Thanks
