### ISSUE TITLE
ansible_connection not available as a variable inside play

### ISSUE THREAD

**Issue by tongpu** [ansible/ansible#9134]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.7.2
##### Environment:

Ubuntu 12.04
##### Summary:

Variable `ansible_connection` not set when `ansible-playbook` called with `-c` parameter or `connection: chroot` is set within a playbook. When `ansible_connection` is set in the inventory file the variable is set as expected.

I would like to use `ansible_connection != chroot` to disable certain handlers when deploying to a chroot. 
##### Steps To Reproduce:

`ansible-playbook -c chroot chroot.yml`
- chroot.yml

```
- hosts: /tmp/chroot
  tasks:
    - debug: var=ansible_connection
```
##### Expected Results:

```
TASK: [debug var=ansible_connection] ****************************************** 
ok: [/tmp/chroot] => {
    "ansible_connection": "chroot"
}
```
##### Actual Results:

```
TASK: [debug var=ansible_connection] ****************************************** 
ok: [/tmp/chroot] => {
    "ansible_connection": "{{ ansible_connection }}"
}
```

**Comment by jimi-c** [comment]
Hi @tongpu, I've updated the title to more accurately reflect the issue here. Also, this is more of a feature request than a bug, so I've modified the type as well.

Thanks!

**Comment by jbd** [comment]
I'm using ansible 2.0.0.2 and it looks to have been corrected.

**Comment by jimi-c** [comment]
@jbd thanks for bringing this to my attention, I'll go ahead and close it now.

Thanks!
