### ISSUE TITLE
No documentation for `with_file` lookup plug-in

### ISSUE THREAD

**Issue by msabramo** [ansible/ansible#9160]
##### Issue Type:

Documentation Report
##### Ansible Version:

ansible-playbook 1.7.1
##### Environment:

N/A
##### Summary:

`with_file` not documented
##### Steps To Reproduce:

Go to http://docs.ansible.com/playbooks_loops.html and look for `with_file`. 
##### Expected Results:

Expect to find documentation of `with_file`. 
##### Actual Results:

Searching for `with_file`, http://docs.ansible.com/playbooks_loops.html has 3 instances for `with_fileglob` but **there are none for `with_file`**. 

```
$ curl -s http://docs.ansible.com/playbooks_loops.html | grep with_file | wc -l
       3

$ curl -s http://docs.ansible.com/playbooks_loops.html | grep with_file | grep -v with_fileglob | wc -l
       0
```

Also, searching the entire `docsite` directory for `with_file` yields mentions of both `with_file` and `with_fileglob` but the latter one is described in detail and the former is not:

```
$ git log -n 1
commit 6af5455edcd843a31a0b20eb103f37445b582672
Author: James Cammarata <jimi@sngx.net>
Date:   Thu Sep 25 19:22:35 2014 -0500

    Default 'smart' connection to paramiko for OSX platforms

    Due to the long-standing bug in sshpass, which can crash OSX.

    Fixes #5007

$ ag 'with_file[^g]' docsite
docsite/rst/glossary.rst
162:but there are also lookup plugins like "with_file" which loads data from a file, and even ones for querying environment variables,

docsite/rst/playbooks_lookups.rst
46:If the file exists previously, it will retrieve its contents, behaving just like with_file. Usage of variables like "{{ inventory_hostname }}" in the filepath can be used to set
```
##### Details

This was originally pointed out by @picomancer in https://github.com/ansible/ansible/issues/7890 but this issue was closed (1).

[1] @pjz suggested that I open another issue, saying he was "told" I should do that, so I'm guessing someone at Ansible said that, or maybe someone is just really interested in this issue :) - anyway apologies if opening an issue for this is the wrong thing to do)

Cc: @sontek, @aconrad, @sudarkoff, @picomancer, @mpdehaan, @pjz

**Comment by astorije** [comment]
:+1:

**Comment by sankalp-khare** [comment]
+1

**Comment by micxer** [comment]
Well, now it's open and nothing happened for months. I just stumbled upon the example in `authorized_key` as well. Is it that complex to explain, how `with_file` is actually working?

**Comment by debugloop** [comment]
@micxer I think `with_file` is just like `with_items`, but it is putting the contents of `lookup( 'file', {{ item }})` into the regular `{{ item }}` variable. I.e., if you want `with_files` with globbing, you can use `with_fileglob` and write `lookup( 'file', {{ item }})` into the command.

**Comment by pjz** [comment]
...sure, so shouldn't that go in the docs somewhere?

**Comment by debugloop** [comment]
Yes it should. As I said I _think_ it works that way, but someone should check the code first before wrong stuff is documented.

**Comment by jesselang** [comment]
Does #12953 resolve this issue? Certainly appears to.

**Comment by bcoca** [comment]
hmm #12953 is wrong, with_file iterates of the contents of files

**Comment by bcoca** [comment]
hmm rest of doc is correct, its just that first phrase that is misleading

**Comment by bcoca** [comment]
closing as per above
