### ISSUE TITLE
wheel packages have wrong paths to modules

### ISSUE THREAD

**Issue by aabdnn** [ansible/ansible#9169]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.7.2
##### Environment:

N/A
##### Summary:

If you build a wheel package of ansible, the modules all end up in the root path of the wheel. If anyone then installs this wheel on a different system, the modules get installed into <sys.prefix>/lib/python/site-packages/usr/share/ansible instead of <sys.prefix>/share/ansible. As a consequence, ansible cannot find its modules and cannot run. 
##### Steps To Reproduce:

Install the latest virtualenv (1.11.6), pip (1.5.6) and wheel (0.24), and then run:

pip wheel --no-deps ansible==1.7.2
virtualenv /path/to/newvirtualenv
source /path/to/newvirtualenv/bin/activate
pip install wheelhouse/ansible-1.7.2-py2-none-any.whl
ansible hostname -m ping
##### Expected Results:

I expect ansible to ping the host and give me some output.
##### Actual Results:

hostname | FAILED => module ping not found in /Users/anandb/library/Accounts:/Users/anandb/library/Address Book Plug-Ins:/Users/anandb/library/Application Scripts:/Users/anandb/library/Application Support:/Users/anandb/library/Assistants:/Users/anandb/library/Audio:/Users/anandb/library/Autosave Information:/Users/anandb/library/Caches:/Users/anandb/library/Calendars:/Users/anandb/library/ColorPickers:/Users/anandb/library/Colors:/Users/anandb/library/Compositions:/Users/anandb/library/Containers:/Users/anandb/library/Cookies:/Users/anandb/library/Developer:/Users/anandb/library/Dictionaries:/Users/anandb/library/F5Networks:/Users/anandb/library/Facebook:/Users/anandb/library/Favorites:/Users/anandb/library/Filters:/Users/anandb/library/FontCollections:/Users/anandb/library/Fonts:/Users/anandb/library/Fonts Disabled:/Users/anandb/library/GameKit:/Users/anandb/library/Google:/Users/anandb/library/Group Containers:/Users/anandb/library/IdentityServices:/Users/anandb/library/iMovie:/Users/anandb/library/Input Methods:/Users/anandb/library/Internet Accounts:/Users/anandb/library/Internet Plug-Ins:/Users/anandb/library/iTunes:/Users/anandb/library/Keyboard Layouts:/Users/anandb/library/Keychains:/Users/anandb/library/LaunchAgents:/Users/anandb/library/Logs:/Users/anandb/library/Mail:/Users/anandb/library/Messages:/Users/anandb/library/Metadata:/Users/anandb/library/Mobile Documents:/Users/anandb/library/Mozilla:/Users/anandb/library/PreferencePanes:/Users/anandb/library/Preferences:/Users/anandb/library/Printers:/Users/anandb/library/PubSub:/Users/anandb/library/Python:/Users/anandb/library/Receipts:/Users/anandb/library/Safari:/Users/anandb/library/Saved Application State:/Users/anandb/library/Screen Savers:/Users/anandb/library/ScriptingAdditions:/Users/anandb/library/Services:/Users/anandb/library/Social:/Users/anandb/library/Sounds:/Users/anandb/library/Spelling:/Users/anandb/library/SyncedPreferences:/Users/anandb/library/Thunderbird:/Users/anandb/library/Twitter:/Users/anandb/library/VirtualBox:/Users/anandb/library/Voices:/Users/anandb/library/WebKit:/Users/anandb/library:/Users/anandb/venvs/testing/share/ansible

**Comment by aabdnn** [comment]
I'd like to offer some additional notes, because I have been poking into ansible's setup.py and its interaction with wheel. So the main issue is that if "install_path" is absolute, ie "/usr/share/ansible", then the wheel packager will naturally place the modules in the wheel package's root directory. But this tells wheel that those files must be installed into lib/python/site-packages.

If we want the wheel packager to package up the modules correctly, then "install_path" needs to be relative, for example "share/ansible". This allows the wheel packager to place all the modules files into the "ansible-1.7.2.data/data" directory in the wheel, and as a consequence, instructs pip to install the files into <virtualenv>/share/ansible correctly. This info is all taken from PEP 427.

Now, I don't know what the correct FINAL solution should be, but essentially, the setting of DEFAULT_MODULE_PATH in constants.py should lead to setting "install_path" in setup.py to a relative directory (share/ansible) so that wheel can build a proper wheel package of ansible.

**Comment by jimi-c** [comment]
Hi @arhbkb, this is essentially the same issue that has caused problems with virtualenv. As part of the recently announced module moves, the modules will going forward not be located in /usr/share/ansible any further, so this should not be an issue in the near future.

As a result of these pending changes, we're going to go ahead and close this issue for now, and you can re-open it if, after the module relocation work is done, any issues with wheel packages remain.

Thanks!
