### ISSUE TITLE
"invalid output was: SUDO-SUCCESS" problem

### ISSUE THREAD

**Issue by Romanowiczmarek** [ansible/ansible#9174]
##### Issue Type:

Bug Report
##### Ansible Version:

Vagrant 1.6.5
##### Environment:

NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"
##### Summary:

I have seen a couple of issues regarding SUDO-SUCCESS problem when ansible playbooks fail. In my case I have multiple playbooks and multiple roles running on localhost and I get the same SUDO-SUCCESS error in different parts. When I tried to debug it I realised that parse_json function inside utils/init.py tries to strip out output buffer of all non-JSON elements in line 435

data = filter_leading_non_json_lines(raw_data)

However in my case I get a buffer consisting of only SUDO-SUCCESS message as an output from a role which leads parse_json function to raise an exception in 451. It is somewhat weird that usually when I do vagrant provision on the same playbook the second time everything seems to work and SUDO-SUCCESS message contains a JSON file. Has anyone else encountered the same problem? As in such consistency that second running solves an issue?

PS/ My line numbers may differ by more lesse 5 since I added a couple of print statements.
##### Steps To Reproduce:

It is hard to give an example playbook to reproduce this bug since I encountered it in our private project and we are yet to discover a faster way to test it and reproduce it.
##### Expected Results:

Second run:
GATHERING FACTS **************************************************************\* 
REMOTE_MODULE setup

SUDO-SUCCESS-wqilcjstmcdtxsigcdaogxgrjouehwsg
{"verbose_override": true, "changed": false, "ansible_facts": {"ohai_chef_packages": {"chef": {"chef_root": "/usr/lib/ruby/vendor_ruby", "version": "11.8.2"}, "ohai": {"version": "6.14.0", "ohai_root": "/usr/lib/ruby/vendor_ruby/ohai"}}, "facter_operatingsystem": "Ubuntu", "ansible_virtualization_type": "virtualbox", "facter_hostname": "ansibleVagrantBox", "module_setup": true, "facter_memoryfree_mb": "287.79", "ohai_block_device": {"ram14": {"removable": "0", "size": "131072"}, "ram15": {"removable": "0", "size": "131072"}, "ram12": {"removable": "0", "size": "131072"}, "ram13": {"removable": "0", "size": "131072"}, "ram10": {"removable": "0", "size": "131072"}, "ram11": {"removable": "0", "size": "131072"}, "ram8": {"removable": "0", "size": "131072"}, "ram9": {"removable": "0", "size": "131072"}, "ram4": {"removable": "0", "size": "131072"}, "ram5": {"removable": "0", "size": "131072"}, "ram6": {"removable": "0", "size": "131072"}, "ram7": {"removable": "0", "size": "131072"}, "ram0": {"removable": "0", "size": "131072"}, "ram1": {"removable": "0", "size": "131072"}, "ram2": {"removable": "0", "size": "131072"}, "ram3": {"removable": "0", "size": "131072"}, "sda": {"vendor": "ATA", "removable": "0", "rev": "1.0", "state": "running", "timeout": "30", "model": "VBOX HARDDISK", "size": "83886080"}, "loop3": {"removable": "0", "size": "0"}, "loop2": {"removable": "0", "size": "0"}, "loop1": {"removable": "0", "size": "0"}, "loop0": {"removable": "0", "size": "0"}, "loop7": {"removable": "0", "size": "0"}, "loop6": {"removable": "0", "size": "0"}, "loop5": {"removable": "0", "size": "0"}, "loop4": {"removable": "0", "size": "0"}}, "ansible_distribution_version": "14.04", "facter_sshfp_rsa": "SSHFP 1 1 779ed88a4afa9a93985f33881d45e2663ad0bc77\nSSHFP 1 2 b5e386d47616473b6fa5656a11a3054b926291f6ba1baddd9a130c0670a25179", "ansible_env": {"USERNAME": "root", "LANG": "en_US.UTF-8", "SUDO_GID": "1000", "SHELL": "/bin/bash", "SUDO_COMMAND": "/bin/sh -c echo SUDO-SUCCESS-wqilcjstmcdtxsigcdaogxgrjouehwsg; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1411764943.91-79158741471377/setup; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1411764943.91-79158741471377/ >/dev/null 2>&1", "SUDO_UID": "1000", "LC_CTYPE": "en_US.UTF-8", "TERM": "xterm-256color", "MAIL": "/var/mail/root", "PWD": "/home/vagrant", "LOGNAME": "root", "USER": "root", "HOME": "/root", "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "SUDO_USER": "vagrant"}, "facter_boardproductname": "VirtualBox", "facter_lsbmajdistrelease": "14", "ansible_userspace_bits": "64", "ansible_architecture": "x86_64", "ohai_command": {"ps": "ps -ef"}, "ansible_default_ipv4": {"macaddress": "08:00:27:ea:db:a0", "network": "10.0.2.0", "mtu": 1500, "alias": "eth0", "netmask": "255.255.255.0", "address": "10.0.2.15", "interface": "eth0", "type": "ether", "gateway": "10.0.2.2"}, "ansible_swapfree_mb": 0, "ansible_default_ipv6": {}, "facter_netmask_eth1": "255.255.255.0", "facter_uuid": "76308519-1E17-4A50-A86C-35EF40132995", "ansible_cmdline": {"root": "UUID=c3994e45-967a-42fd-8d97-edcf2001e6ea", "ro": true, "BOOT_IMAGE": "/boot/vmlinuz-3.13.0-36-generic", "console": "ttyS0"}, "ansible_selinux": false, "ohai_fqdn": "ansibleVagrantBox", "ansible_os_family": "Debian", "ansible_userspace_architecture": "x86_64", "ansible_product_uuid": "76308519-1E17-4A50-A86C-35EF40132995", "facter_osfamily": "Debian", "facter_memorytotal": "1.95 GB", "ansible_pkg_mgr": "apt", "facter_filesystems": "ext2,ext3,ext4,vfat", "ansible_distribution": "Ubuntu", "facter_puppetversion": "3.4.3", "facter_lsbdistrelease": "14.04", "ansible_all_ipv6_addresses": ["fe80::a00:27ff:feea:dba0", "fe80::a00:27ff:fec7:9584"], "facter_operatingsystemrelease": "14.04", "ansible_kernel": "3.13.0-36-generic", "facter_bios_version": "VirtualBox", "ohai_hostname": "ansibleVagrantBox", "ohai_idletime": "14 minutes 49 seconds", "facter_boardmanufacturer": "Oracle Corporation", "facter_architecture": "amd64", "facter_macaddress_eth1": "08:00:27:c7:95:84", "facter_sshfp_ecdsa": "SSHFP 3 1 2b2f5db3a5cf721dd30ef34d86628e48761c4198\nSSHFP 3 2 e91e68046588d25840fe70da522e5097b265eb68ef4b6e49034f488c0a704d9c", "ohai_cpu": {"1": {"family": "6", "core_id": "1", "vendor_id": "GenuineIntel", "flags": ["fpu", "vme", "de", "pse", "tsc", "msr", "pae", "mce", "cx8", "apic", "sep", "mtrr", "pge", "mca", "cmov", "pat", "pse36", "clflush", "mmx", "fxsr", "sse", "sse2", "ht", "syscall", "nx", "rdtscp", "lm", "constant_tsc", "rep_good", "nopl", "pni", "ssse3", "lahf_lm"], "mhz": "2093.996", "stepping": "7", "cache_size": "6144 KB", "cores": "2", "model": "42", "model_name": "Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz", "physical_id": "0"}, "0": {"family": "6", "core_id": "0", "vendor_id": "GenuineIntel", "flags": ["fpu", "vme", "de", "pse", "tsc", "msr", "pae", "mce", "cx8", "apic", "sep", "mtrr", "pge", "mca", "cmov", "pat", "pse36", "clflush", "mmx", "fxsr", "sse", "sse2", "ht", "syscall", "nx", "rdtscp", "lm", "constant_tsc", "rep_good", "nopl", "pni", "ssse3", "lahf_lm"], "mhz": "2093.996", "stepping": "7", "cache_size": "6144 KB", "cores": "2", "model": "42", "model_name": "Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz", "physical_id": "0"}, "total": 2, "real": 1}, "ansible_product_serial": "0", "ansible_form_factor": "Other", "ansible_user_id": "root", "facter_ipaddress_lo": "127.0.0.1", "facter_manufacturer": "innotek GmbH", "ohai_current_user": "vagrant", "facter_memorysize": "1.95 GB", "facter_path": "/

and so on.
##### Actual Results:

Example from Gathering facts stage:

First run:
GATHERING FACTS **************************************************************\* 
REMOTE_MODULE setup

SUDO-SUCCESS-zeydvfomlnxulshkacvpqtpxwipkfgtv

( nothing here, this causes the error )

**Comment by sivel** [comment]
Typically, you should only see that string, when a module failed and caused a stacktrace.

**Comment by Romanowiczmarek** [comment]
Yes, I changed the code so that I can see what is happening and why my roles are failing at random places.

**Comment by mpdehaan** [comment]
Can you please supply the output as requested by ansibot above?

Thanks!

**Comment by Romanowiczmarek** [comment]
Sometimes I get this output as well:

{'msg': 'SUDO-SUCCESS-pqitrhuqzpinjvsehpfcpjqhlymesatc\r\nOpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011\ndebug1: Reading configuration data /etc/ssh_config\r\ndebug1: /etc/ssh_config line 20: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 15367\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Control master terminated unexpectedly\r\nShared connection to 127.0.0.1 closed.\r\n', 'failed': True, 'parsed': False}
failed: [ansibleVagrantBox] => {"failed": true, "parsed": false}
invalid output was: SUDO-SUCCESS-pqitrhuqzpinjvsehpfcpjqhlymesatc
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 15367
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Control master terminated unexpectedly
Shared connection to 127.0.0.1 closed.

**Comment by Romanowiczmarek** [comment]
It seems like the problem was in a reboot command sent just before that one with which ssh could not cope returning Broken pipe message.

Does it sound feasible?

**Comment by bauruine** [comment]
Could be this bug. https://bugs.launchpad.net/ubuntu/+source/openssh/+bug/1334916

**Comment by jsternberg** [comment]
We hit this a lot. While the bug is probably with the upstream openssh package, is there any workaround for this problem that we could use in the interim?

**Comment by bauruine** [comment]
@jsternberg remove ControlMaster= and ControlPersist= from your ssh_args.

**Comment by bcoca** [comment]
using ```sleep 2 && reboot``` seems to avoid this issue

**Comment by jimi-c** [comment]
@Romanowiczmarek I believe your root cause was correct, though the devel/v2 code should handle this a bit better.

For all other reports, this error is pretty generic, as it previously mainly occured when the parsing/reading from the remote host failed for some reason (which could have actually been many reasons, as you may see by searching for SUDO-SUCCESS in our issue queue). If you are still having regular problems with this in the current devel, please let us know via a new issue.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
