### ISSUE TITLE
latest ansible fails w/o a default module path

### ISSUE THREAD

**Issue by bcoca** [ansible/ansible#9183]
##### Issue Type:

ansible-doc, ansible and ansible-playbook fail when there is no ansible.cfg or it is missing the module path (even one not pointing at modules)
##### Ansible Version:

ansible 1.8 (devel ffee9a8fe0) last updated 2014/09/26 18:59:06 (GMT -400)
running from checkout (and yes it has the new submodules)
##### Environment:

Tested on Gentoo and Ubuntu 14, no targets involved as this pertains to main module loading
##### Summary:

Invoking ansible fails when you don't have an ansible.cfg or if it lacks the entry with module paths (#library=/dev/null)
##### Steps To Reproduce:

without an ansible.cfg do either of the following
# >ansible-doc -l

or 
# >ansible -m setup -i 'localhost,' all -c local
##### Expected Results:

ansible-doc -l, should return module list, the other should return the system facts
##### Actual Results:

for ansible-doc -l:

```
Traceback (most recent call last):
  File "/home/bcoca/work/ansible/bin/ansible-doc", line 295, in <module>
    main()
  File "/home/bcoca/work/ansible/bin/ansible-doc", line 226, in main
    paths = utils.plugins.module_finder._get_paths()
  File "/home/bcoca/work/ansible/lib/ansible/utils/plugins.py", line 129, in _get_paths
    configured_paths = self.config.split(os.pathsep)
AttributeError: 'NoneType' object has no attribute 'split'
```

for ansible -m setup:

```
localhost | FAILED => Traceback (most recent call last):
  File "/home/bcoca/work/ansible/lib/ansible/runner/__init__.py", line 567, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/bcoca/work/ansible/lib/ansible/runner/__init__.py", line 717, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/home/bcoca/work/ansible/lib/ansible/runner/__init__.py", line 949, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/home/bcoca/work/ansible/lib/ansible/runner/action_plugins/normal.py", line 57, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/home/bcoca/work/ansible/lib/ansible/runner/__init__.py", line 448, in _execute_module
    ) = self._configure_module(conn, module_name, args, inject, complex_args)
  File "/home/bcoca/work/ansible/lib/ansible/runner/__init__.py", line 1216, in _configure_module
    module_path = utils.plugins.module_finder.find_plugin(module_name, module_suffixes)
  File "/home/bcoca/work/ansible/lib/ansible/utils/plugins.py", line 175, in find_plugin
    for i in self._get_paths():
  File "/home/bcoca/work/ansible/lib/ansible/utils/plugins.py", line 129, in _get_paths
    configured_paths = self.config.split(os.pathsep)
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by bcoca** [comment]
bisect points at 7f6ab89b5b9ad4f84b19d1b14c2d03cb91e720bf, so this seems to only affect those of us using hacking/env-setup. 

The library default does not even need to be correct, it just has to exist or the plugins.py should be modified to allow for it to be missing (aka, check for None).

**Comment by fxlv** [comment]
Indeed this is broken by default on `ansible 1.8 (devel ffee9a8fe0) last updated 2014/09/27 23:13:27 (GMT +300)`

Setting `library=/dev/null` in ansible.cfg helps.

**Comment by mpdehaan** [comment]
Hi!

A change has been applied for this ticket on the development branch, which should resolve this item for you.

If you believe this ticket is not resolved, or have further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments on closed tickets, though the mailing list is a great way to get involved or discuss this one further.

Thanks!
