### ISSUE TITLE
Condition ignored when including another play

### ISSUE THREAD

**Issue by thomasvnoort** [ansible/ansible#9198]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible-playbook --version
ansible-playbook 1.7.2
```

and

```
$ ansible-playbook --version
ansible-playbook 1.8 (devel 0354d19f73) last updated 2014/09/29 12:00:04 (GMT +200)
  lib/ansible/modules/core:  not found - use git submodule update --init lib/ansible/modules/core
  lib/ansible/modules/extras:  not found - use git submodule update --init lib/ansible/modules/extras
  configured module search path = /usr/local/share/ansible
```
##### Environment:

N/A
##### Summary:

Including another play using a condition seems to completely ignore the condition.
##### Steps To Reproduce:

Consider a parent play, child play, and a hosts file.

parent.yml:

```
- include: child.yml
  when: false
```

child.yml

```
- hosts: all
  tasks:
    - debug: msg=hello
```

hosts:

```
localhost
```

Run it:

```
$ ansible-playbook parent.yml -i hosts

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [debug msg=hello] *******************************************************
ok: [localhost] => {
    "msg": "hello"
}

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```
##### Expected Results:

I'd expect the child play to be skipped completely. This does seem to work when including roles, I'd expect to see the same behaviour for plays.
##### Actual Results:

The condition seems to be ignored and the play is executed regardless of the false condition.

**Comment by bcoca** [comment]
first, conditionals don't work on include/roles, they are transposed to the
tasks included
second, there is no conditional at play level other than matching hosts

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by thomasvnoort** [comment]
I know that conditionals on task includes are propagated to the tasks, I assumed this to work in the same fashion for play includes. But I finally found the [documentation](http://docs.ansible.com/playbooks_conditionals.html#applying-when-to-roles-and-includes) explaining this:

```
Note this does not work with playbook includes, just task includes.
```

It might be nice to warn the user for such unused fields. Since the current behaviour is intentional, I'll close the ticket.
