### ISSUE TITLE
group_vars/ only working in ansible-playbook

### ISSUE THREAD

**Issue by jhoekx** [ansible/ansible#920]
Variable definitions in the group_vars/ folder are only read in playbook mode. They are not used when using `ansible`.

I have multiple groups with `ansible_python_interpreter` defined as a group variable. YAML-to-INI conversion converted these groups to have their variables in group_vars/<group> and would subsequently fail when running a command on all of them through `ansible`.

**Comment by mpdehaan** [comment]
This is because groups_vars content is loaded as part of vars_files code.   I'm not going to fix this, but will accept a patch.

Meanwhile, you could use the [foo:vars] method of defining group vars and it would be fine.

**Comment by mpdehaan** [comment]
you'll need to do something like:

if not self.is_playbook:
    play = # somehow fake out a play object
    play.update_vars_files_for_host(...)
