### ISSUE TITLE
Automation for ansible-modules-core and ansible-modules-extras may be incorrectly flagging some PRs as being for modules

### ISSUE THREAD

**Issue by msabramo** [ansible/ansible#9208]
##### Issue Type:

Bug Report
##### Ansible Version:

N/A
##### Environment:

N/A
##### Summary:

See https://github.com/ansible/ansible/pull/9128

I think the bot message there (https://github.com/ansible/ansible/pull/9128#issuecomment-57216677) is not applicable to this PR. My PR targets a file called `module_utils/facts.py` which is not a module; it's part of the Ansible core and it's in the `ansible`repo and **not** in the `ansible-modules-core` or `ansible-modules-extras` repos.
##### Steps To Reproduce:

File a PR for a file in the `module_utils` directory of ansible.
##### Expected Results:

The PR should eventually be reviewed by a human. It should not be closed by a bot.
##### Actual Results:

 A bot says that it should be in the `ansible-modules-core` or `ansible-modules-extras` repos and automatically closes the PR. https://github.com/ansible/ansible/pull/9128#issuecomment-57216677

---

See https://github.com/ansible/ansible/pull/9128

I think the bot message there is not applicable to this PR. My PR targets a file called `module_utils/facts.py` which is not a module; it's part of the Ansible core and it's in the `ansible`repo and **not** in the `ansible-modules-core` or `ansible-modules-extras` repos.

Both of the commands below return nothing:

```
$ find ansible-modules-core -name 'facts.py' -o -name 'module_utils'

$ find ansible-modules-extras -name 'facts.py' -o -name 'module_utils'
```

So I'm thinking that perhaps a script flagged this in error because it had the word "module" in it?

And https://github.com/ansible/ansible/pull/9128 should probably be reopened.

**Comment by jimi-c** [comment]
Hi @msabramo, that PR appears to have been marked with the module tag due to the fact that it modified the module_utils/ code (which remains in core).

Thanks!
