### ISSUE TITLE
Execute different task order in role, if different action specified then default

### ISSUE THREAD

**Issue by holms** [ansible/ansible#9211]
##### Issue Type:

Feature Idea
##### Ansible Version:

Ansible 1.7.2
##### Environment:

Ubuntu 14.04
##### Summary:

This issue been discussed multiple times in freenode #ansible channel. This is a case-study which requires solution, and current behavior is not satisfying many people. Please discuss how this can be done more precisely. I'm just a regular ansible user, who migrated from chef recently I have a huge wish to have this feature.

Literally, I want to include _concrete_ task from role, or _order of tasks_ from role, if I require so. Behavior is quite similar to chef, where roles includes recipes of cookbooks. 

Currently one of the way of doing this, is to pass some kind of action variable, and then in `include` statement, check that variable using `while` statement. So something like 

```
- include: deploy.yml
  when: env in ["deploy"]
```

This brings a trouble: When launching provisioning you'll see 300 skip messages of other include statements.  You _need_ multiple playbooks! This is extremely uncomfortable :). 

Ideally, how I see it, you call ansible-playbook with some specified action, let's say _deploy_ action. And you have one playbook which calls role, where role decides what tasks to include if some non-default action is detected.

Some people solved this in interesting way: (Thanks to @malinoff)

```
$ cat playbooks/install.yml 

---
- hosts: glassfish
  roles:
    - role: glassfish/install
      tags: glassfish

- hosts: gateway
  roles:
    - role: gateway/install
      tags: gateway


$ cat playbooks/configure.yml 

---
- hosts: glassfish
  roles:
    - role: glassfish/configure
      tags: glassfish

- hosts: gateway
  roles:
    - role: gateway/configure
      tags: gateway


$ cat playbooks/deploy.yml 

---
- hosts: glassfish
  roles:
    - role: glassfish/install
      tags: glassfish
    - role: glassfish/configure
      tags: glassfish

- hosts: gateway
  roles:
    - role: gateway/install
      tags: gateway
    - role: gateway/configure
      tags: gateway
```

In this situation we have 3 actions: deploy, install, configure. We specify tag for the project we want to do actions over, and we still need to create playbook for each action! (Btw I've never seen a `role/myappname/role_name/` behavior before, looks l33t).

We can use tags in roles rights? But then we'll end up with having a tag for each role, which makes this even more painful to maintain. 

In the end I just want to say "hey deploy all these servers", and deploy action of all roles will be activated. This probably requires some kind of naming policy. Maybe you can come out with better idea, but this case-study should be simple to use. As simple as including task from role to playbook (I know we can do this, but we loosing path's, if global path applies, then whole role becomes non-portable anymore). 

Summary:
- Having variable under include statement with 300 skip messages not ant option. And you still need multiple playbooks for different actions
- Having tags for each role will be painful for anyone who'll use it with many roles, if we write roles for ourselves then fine, but re-using other will be trouble some.
- Including task from role into playbook, we lose local path's of roles, if task will have global paths, the portability of role is lost. And you still need multiple playbooks for different actions

**Comment by jimi-c** [comment]
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!
