### ISSUE TITLE
Allow inventory_hostnames in lookups

### ISSUE THREAD

**Issue by hkariti** [ansible/ansible#9218]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.8 (devel 313f26f866) last updated 2014/10/01 08:23:43 (GMT +000)
##### Environment:

N/A
##### Summary

`inventory_hostnames` can't be used currently as a lookup, so instead of doing this:

```
local_servers: '{{ lookup("inventory_hostnames", "servers:&this_region") }}'
```

I do this:

```
local_servers: '{{ groups.servers | intersect(groups.this_region) | list }} '
```

Which is a bit... odd. It also doesn't support more advanced queries.

**Comment by jimi-c** [comment]
Hi @hkariti, I'm a little unclear as to what you're trying to accomplish here. Lookups are typically used to pull information in from external sources, while the inventory_hostname is an internal variable, which should already be set.

Can you share your use-case for this, and why you believe it should be a lookup plugin?

**Comment by hkariti** [comment]
My usecase is generating configuration in a multi-dc setup. I have a
hostgroup per role and a hostgroup per ec2 region (i.e. dc), and i'd like
to get a list of some role's hosts in the current host's region. For
example the app servers' configs need the list of the db servers,  but only
the ones in their region.

As I see it I have two options - generate a hostgroup for every role-region
combination and construct the hostgroup name dynamically to use it
(something like groups['db-' + ec2_region] ), or query the inventory to
create that list ('db:&' + ec2_region). I chose the second option, because
it seems much simpler. Problem is I can't really query the inventory to
create lists in any way. The closest thing I have is this lookup, but it
must be used as a loop.

I hope I was clear. Is querying the inventory into variables a big no-no in
some way?

**Comment by hkariti** [comment]
I just realized I forgot an 's' throughout my original description. I meant `inventory_hostnames`, not hostname. It's a lookup plugin that already exists to query the inventory, but it only works as a loop (`with_inventory_hostnames`) and not as a lookup.

**Comment by jimi-c** [comment]
Ahh, that makes more sense, thanks!

**Comment by jimi-c** [comment]
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!

**Comment by jimi-c** [comment]
One additional comment here: why not use the `ansible_play_hosts` variable with another loop? Seems like that's really what you want here.

**Comment by AquaL1te** [comment]
Was this feature ever implemented and explored further? I would like to loop over all the hostnames in my inventory, inside a jinja template. It seems there is just this transparent 'with_inventory_hostnames' inside a task? This surely must be possible inside a template query + loop as well, right? I've been experimenting, but nothing works so far.

Would [this](https://docs.ansible.com/ansible/2.5/user_guide/playbooks_loops.html#looping-over-the-inventory) be possible inside a jinja template?
