### ISSUE TITLE
ansible-galaxy fails due to invalid filename

### ISSUE THREAD

**Issue by rawtaz** [ansible/ansible#9236]
##### Issue Type:

Bug Report
##### Ansible Version:

HEAD, installed using `brew install --HEAD ansible` right before filing this bug.

```
$ ansible --version
ansible 1.8
  configured module search path = None
```
##### Environment:

OS X 10.9.5
##### Summary:

Installing a role using `ansible-galaxy` without specifying the "version" part of the role name fails due to an invalid file path being used for the download.
##### Steps To Reproduce:

The command `ansible-galaxy install Mayeu.sensu` fails due to "master" not being part of the requested filename. It is the same with other roles I tried to install as well, so it's most likely not specific to this sensu role from Mayeu.

```
$ ansible-galaxy install Mayeu.sensu
- downloading role 'sensu', owned by Mayeu
- downloading role from https://github.com/Mayeu/ansible-playbook-sensu/archive/.tar.gz
- error: failed to download the file.
- Mayeu.sensu was NOT installed successfully.
- you can use --ignore-errors to skip failed roles.
```

Specifying a "version" by `ansible-galaxy install Mayeu.sensu,master` makes it work:

```
$ ansible-galaxy install Mayeu.sensu,master
- downloading role 'sensu', owned by Mayeu
- downloading role from https://github.com/Mayeu/ansible-playbook-sensu/archive/master.tar.gz
- extracting Mayeu.sensu to /Users/rawtaz/ansible/roles/Mayeu.sensu
- Mayeu.sensu was installed successfully
```

Removing the role works fine.
##### Expected Results:

See above.
##### Actual Results:

See above.

**Comment by rawtaz** [comment]
I updated the issue with the template mentioned by the bot. Please note that the bot says to put the template in the "description" of the ticket. It is a bit unclear what field it is referring to here, since there's no "description" field in the issue form. I am naturally assuming it doesn't mean the title field, so I put it in the comment field. I think you should clarify that text from the bot though so it matches the issue form :)

**Comment by rawtaz** [comment]
Similar issue with this role as well (seems it doesn't automatically default to version "master")

```
$ ansible-galaxy install DavidWittman.redis

- downloading role 'redis', owned by DavidWittman
role is {'scm': None, 'src': 'DavidWittman.redis', 'version': '', 'name': 'DavidWittman.redis'}
- the specified version () was not found in the list of available versions ([{u'release_date': u'2014-09-10T19:41:07Z', u'id': 1520, u'name': u'1.0.2'}, {u'release_date': u'2014-08-21T19:49:04Z', u'id': 1339, u'name': u'1.0.1'}, {u'release_date': u'2014-05-27T22:58:36Z', u'id': 1194, u'name': u'1.0.0'}]).
- you can use --ignore-errors to skip failed roles.


$ ansible-galaxy install DavidWittman.redis,master
- downloading role 'redis', owned by DavidWittman
- downloading role from https://github.com/DavidWittman/ansible-redis/archive/master.tar.gz
- extracting DavidWittman.redis to /Users/rawtaz/ansible/roles/DavidWittman.redis
- DavidWittman.redis was installed successfully
```

**Comment by rawtaz** [comment]
I noticed that when ansible-galaxy deals with dependencies, it fails regardless of whether or not one specified the version in the initial role install:

```
$ ansible-galaxy install savagegus.consul,master
- downloading role 'consul', owned by savagegus
- downloading role from https://github.com/jivesoftware/ansible-consul/archive/master.tar.gz
- extracting savagegus.consul to /Users/rawtaz/ansible/roles/savagegus.consul
- savagegus.consul was installed successfully
- adding dependency: franklinkim.nginx
- downloading role 'nginx', owned by franklinkim
role is {'scm': None, 'src': u'franklinkim.nginx', 'version': '', 'name': u'franklinkim.nginx'}
- the specified version () was not found in the list of available versions ([{u'release_date': u'2014-08-19T15:22:13Z', u'id': 1319, u'name': u'1.0.0'}]).
- you can use --ignore-errors to skip failed roles.
```

**Comment by mpdehaan** [comment]
Hi, we've got a few other instances of this ticket in the system tracking this bug and will look at this very soon on the devel branch.

I'm going to reference this one with https://github.com/ansible/ansible/issues/9173 and we can resolve both problems at the same time.

Thanks!

**Comment by abadger** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
