### ISSUE TITLE
Support --init-file for shell module

### ISSUE THREAD

**Issue by chriswhelan** [ansible/ansible#9240]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.7.1
##### Environment:

N/A
##### Summary:

I've run into an issue where I need access to some functionality which is normally initialized in a .bashrc file from an Ansible playbook.  I'm generally in agreement with Ansible's approach to avoid relying on anything in the environment of the remote host, so whilst something like https://github.com/ansible/ansible/issues/4854 would solve my problem, I'm wondering if there's a better way.

Ansible allows me to configure environment variables in a portable way using the syntax:
    environment:
      some_var: my_value

Sometimes though, this isn't sufficient - in my case I need to make certain bash _functions_ available that are normally loaded in .bashrc, so configuring variables alone isn't going to give me a working environment.

Rather than running an interactive shell and relying on the machine's environment, could we add an option to the shell module which would allow me to specify a script that would be sourced into the environment before my shell command is executed?
##### Steps To Reproduce:

```
- name: Do something with a shell function
  shell: my_function 123
  args:
    executable: /bin/bash
  init_file: .initrc
```
##### Expected Results:

This would then launch the shell using:
    /bin/bash --init-file=.initrc
##### Actual Results:

```
-bash: my_function: command not found
```

This feature could still be abused of course, by specifying init_file: ~/.bashrc, which would introduce the same reliance on the local environment that Ansible is designed to avoid.  Ideally though I would be able to specify a template file from my playbook which is copied to the remote machine to initialise the environment instead of relying on runcoms on the target machine.

The main problem I can see with this is that --init-file is a bash specific argument, so this wouldn't be very portable.  One alternative would be to simulate the same behaviour by running "source $init_file" before invoking the shell command.

N.B. I'll look into implementing this, but wanted to raise the issue first to see if there was a better solution

**Comment by zatekusen** [comment]
+1, This feature will be really useful in some cases.

**Comment by mpdehaan** [comment]
Thanks for the suggestion, Ansible's philosophy around reliable centralized management is very important to us, and relying on the user's shell does not lead to a reliable centralized management system.  

For readers finding this ticket, please see http://docs.ansible.com/playbooks_environment.html for how to set environment variables.

It's ok to set up a user's shell, but we can't rely on it, and it will result in spotty deployments.

If you do need something like that, you could of course work around it by using the "script" module, and in the source of the "script", you could source whatever you needed - so it's still possible.

We're just going to want to control this practice and reduce keyword sprawl in this area.

**Comment by pjnagel** [comment]
@mpdehaan 

The advice to use environment variables does not help in all cases. Ruby RVM, for example, depends on shell function(s) to work, not just environment variables. See #4854 for RVM users struggling with this issue.

Further, if the concern is that relying on the contents of the shell profile is brittle in the light of the ansible philosophy, then that can be addressed by managing the shell profile itself with ansible.

I can understand the philosophy of disabling login shells by default, but the option to choose to enable them would be very much appreciated.
