### ISSUE TITLE
wait_for with exclude_hosts fails to parse the options correctly

### ISSUE THREAD

**Issue by arothian** [ansible/ansible#9244]
##### Ansible Version:

ansible 1.8 (devel 43eb821d3f) last updated 2014/10/01 16:52:07 (GMT -400)
  lib/ansible/modules/core: (detached HEAD db5668b84c) last updated 2014/10/01 16:52:11 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 110250d344) last updated 2014/10/01 16:52:16 (GMT -400)
  configured module search path = ansible-1.7.2/library
##### Environment:

Ubuntu 14.04, managing Centos 6
##### Summary:

The wait_for module has a new exclude_hosts option as part of the drained state (#7260). Using these new options causes a Traceback error.
##### Steps To Reproduce:

Use the wait_for module in a task such as below
`wait_for: host={{ ansible_hostname }} port=8080 state=drained exclude_hosts=somehost1,somehost2`
##### Expected Results:

The wait_for processes on the managed nodes without error.
##### Actual Results:

The wait_for module fails to parse the exclude_hosts option

```
Traceback (most recent call last):
   File "/home/monk/.ansible/tmp/ansible-tmp-1412198038.01-173699330634982/wait_for", line  1967, in <module>
    main()
   File "/home/monk/.ansible/tmp/ansible-tmp-1412198038.01-173699330634982/wait_for", line 326, in     main
    exclude_hosts = params['exclude_hosts'].split(',')
AttributeError: 'list' object has no attribute 'split'
```

**Comment by mpdehaan** [comment]
Sounds like since this has transitioned to "type='list'" the split code can and should be removed down this particular path.

Thanks for the report!

**Comment by bcoca** [comment]
closing this and keeping track in PR https://github.com/ansible/ansible-modules-core/pull/303
