### ISSUE TITLE
When used in playbook, stat module cannot run against local file

### ISSUE THREAD

**Issue by rcp** [ansible/ansible#9251]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.7
##### Environment:

CentOS 6.5 x86_64
##### Summary:

stat won't give me an md5 of a local file
##### Steps To Reproduce:

I have a playbook with the following (elided) structure:
site.yml
roles
  common
    files
      printers.conf
    tasks
      main.yml
      config-cups.yml
    handlers
      main.yml

See stackoverflow question http://stackoverflow.com/q/26168051/761374 for the complete contents of config-cups.yml.

The key parts of config-cups.yml however are the following four tasks
    - stat: path=printers.conf
      register: locst
    - stat: path=/etc/cups/printers.conf
      register: remst
    - name: ensure cups is stopped
      service: name=cups state=stopped
      when: locst.stat.md5 ne remst.stat.md5
    - name: Configure printers
      tags: configuration
      copy: >
        src=printers.conf
        dest=/etc/cups/printers.conf
        mode=600 owner=root group=lp

In the 1st task, the stat module fails to match path=printers.conf against the file "roles/common/files/printers.conf". However in the 4th task, the copy module does match against the local file in the "src=printers.conf".

I believe it is wrong that stat cannot run against local files. Either
1) "stat" should have an alternate parameter to specify the local files, or
2) "stat path" parameter should be allowed to match against the local playbook's files/ tree
##### Expected Results:

Expected the "when: locst.stat.md5 ne remst.stat.md5" conditional to produce a boolean, and control whether to stop the cups service.
##### Actual Results:

Received the error "fatal: [hostxxxx] => error while evaluating conditional: locst.stat.md5 ne remst.stat.md5"

**Comment by bcoca** [comment]
try running the stat with either delegate_to: localhost or connection: local

Brian Coca

**Comment by mpdehaan** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
