### ISSUE TITLE
ansible-playbook attempts to log to /var/log/ansible.log when no log_path is configured

### ISSUE THREAD

**Issue by drawks** [ansible/ansible#9253]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

Debian 7.0
##### Summary:

According to http://docs.ansible.com/intro_configuration.html#log-path if no log_path is specified ansible will log via syslog. However with a completely stock 1.7.2 build all attempts to run ansible-playbook raise a traceback:

This is problematic because it essentially breaks syslog logging which cannot be explicitly enabled. And by default in a typical system configuration ansible-playbook will not work out of the box without customizing the configuration.
##### Steps To Reproduce:
1. Install ansible from tarball.
2. Run an ansible-playbook as a user without privileges to write to /var/log
##### Expected Results:

The wording from the documentation is a little fuzzy, but I expect that ansible-playbook will (log nothing on the host from which it is run OR ansible-playbook will log via syslog locally) AND will log module arguments via syslog on the machines being managed by the playbook 
##### Actual Results:

```
 Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 309, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 253, in main
    playbook_cb.on_stats(pb.stats)
  File "/usr/lib/python2.7/dist-packages/ansible/callbacks.py", line 697, in on_stats
    call_callback_module('playbook_on_stats', stats)
  File "/usr/lib/python2.7/dist-packages/ansible/callbacks.py", line 176, in call_callback_module
    method(*args, **kwargs)
  File "/home/drawks/ansible/callback_plugins/human.py", line 147, in playbook_on_stats
    easy_stats(stats)
  File "/home/drawks/ansible/callback_plugins/human.py", line 79, in easy_stats
    with open(LOG_PATH, 'a') as fd:
IOError: [Errno 13] Permission denied: '/var/log/ansible.log'
```

**Comment by mpdehaan** [comment]
"However with a completely stock 1.7.2 "

How did you install ansible? 

Check that you don't have an /etc/ansible/ansible.cfg that may have configured this or a ansible.cfg in your working dir, etc.

**Comment by drawks** [comment]
Completely stock ansible is a debian package built from the 1.7.2 source tarball on github. There is only a single ansible.crfg file in play on the machine, `/etc/ansible/ansible.cfg` and it absolutely doesn't set log_path.

```
# logging is off by default unless this path is defined
# if so defined, consider logrotate
#log_path = /var/log/ansible.log
```

**Comment by mpdehaan** [comment]
Thanks!

**Comment by jimi-c** [comment]
@drawks configuration files in local directories would be `.ansible.cfg` - can you confirm there are none of those present? I've been trying to reproduce this, and have not yet been able to. I also checked the various machines I test on and none of them have a `/var/log/ansible.log` file present.

Finally, if no other files are found, could you share your ansible.cfg if any modifications were made to it?

**Comment by drawks** [comment]
Here's the entire diff of my ansible config vs the one shipped in 1.7.2

```
18c18
< forks          = 5
---
> forks          = 25
```

I can confirm with 100% certainty that there are no other configs being loaded in my environment. I can easily reproduce this with a super minimal playbook that just attempts to run "echo foo" on a single host with no other config specified.

```
$ ansible-playbook example.yml -s -v

PLAY [systest-2] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [systest-2]
fatal: [systest-2] => Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 561, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 666, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 962, in _executor_internal_inner
    self.callbacks.on_ok(host, data)
  File "/usr/lib/python2.7/dist-packages/ansible/callbacks.py", line 537, in on_ok
    super(PlaybookRunnerCallbacks, self).on_ok(host, host_result)
  File "/usr/lib/python2.7/dist-packages/ansible/callbacks.py", line 344, in on_ok
    call_callback_module('runner_on_ok', host, res)
  File "/usr/lib/python2.7/dist-packages/ansible/callbacks.py", line 176, in call_callback_module
    method(*args, **kwargs)
  File "/home/drawks/ansible/callback_plugins/human.py", line 93, in runner_on_ok
    easy_reader(res)
  File "/home/drawks/ansible/callback_plugins/human.py", line 58, in easy_reader
    with open(LOG_PATH,'a') as fd:
IOError: [Errno 13] Permission denied: '/var/log/ansible.log'


TASK: [example | test] ******************************************************** 
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ******************************************************************** 
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 309, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 253, in main
    playbook_cb.on_stats(pb.stats)
  File "/usr/lib/python2.7/dist-packages/ansible/callbacks.py", line 697, in on_stats
    call_callback_module('playbook_on_stats', stats)
  File "/usr/lib/python2.7/dist-packages/ansible/callbacks.py", line 176, in call_callback_module
    method(*args, **kwargs)
  File "/home/drawks/ansible/callback_plugins/human.py", line 147, in playbook_on_stats
    easy_stats(stats)
  File "/home/drawks/ansible/callback_plugins/human.py", line 79, in easy_stats
    with open(LOG_PATH, 'a') as fd:
IOError: [Errno 13] Permission denied: '/var/log/ansible.log'
```

And rerunning after touching /var/log/ansible.log and making it writable

```
$ sudo touch /var/log/ansible.log ; sudo chmod 666 /var/log/ansible.log
drawks@blaster:~/ansible$ ansible-playbook example.yml -s -v

PLAY [systest-2] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [systest-2]
Remote logging failed

TASK: [example | test] ******************************************************** 
changed: [systest-2] => {"changed": true, "cmd": ["echo", "foo"], "delta": "0:00:00.003038", "end": "2014-10-06 09:53:52.323711", "rc": 0, "start": "2014-10-06 09:53:52.320673", "stderr": "", "stdout": "foo"}
Remote logging failed

PLAY RECAP ******************************************************************** 
Remote logging failed
systest-2                  : ok=2    changed=1    unreachable=0    failed=0 
```

I'm note sure what the "remote logging failed" output is meant to indicate as it would appear that syslog on the managed hosts did receive the the events as specified would happen in the docs:

```
/var/log/user.log:Oct  6 09:53:49 systest-2 ansible-setup: Invoked with filter=* fact_path=/etc/ansible/facts.d 
/var/log/user.log:Oct  6 09:53:52 systest-2 ansible-command: Invoked with executable=None shell=False args=echo foo removes=None creates=None chdir=None
```

**Comment by jimi-c** [comment]
I just noticed this:

<pre>
  File "/home/drawks/ansible/callback_plugins/human.py", line 58, in easy_reader
    with open(LOG_PATH,'a') as fd:
</pre>

We do not ship a `human.py` callback, so this sounds like something custom you or someone else has written?

**Comment by drawks** [comment]
You are absolutely correct! Another team member had dropped the callback in the default environment. I hadn't realized it was loading by default. Sorry much for the bogus issue report.

**Comment by drawks** [comment]
I feel like a boob.

**Comment by jimi-c** [comment]
No worries, sorry for not catching that sooner :)
