### ISSUE TITLE
a module parameter of list type should return an empty list given an empty string

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#9254]
##### Issue Type:

Bugfix
##### Ansible Version:

ansible-playbook 1.8 (devel 05994cd900) last updated 2014/09/30 10:45:21 (GMT -400)
  lib/ansible/modules/core: (detached HEAD db5668b84c) last updated 2014/09/29 10:46:25 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 110250d344) last updated 2014/09/28 10:24:25 (GMT -400)
  configured module search path = None
##### Environment:

N/A
##### Summary:

If I have a module that takes has a parameter that is of list type and that paramter is given an empty string, it should return an empty list.
##### Steps To Reproduce:

sample module:

```
#!/usr/bin/python
def main():

    module = AnsibleModule(
        argument_spec = dict(
            aliases     = dict(required=False, type='list'),
        )
    )

    aliases     = module.params['aliases']
    result = {}
    result['aliases'] = aliases
    module.exit_json(**result)

# import module snippets
from ansible.module_utils.basic import *
main()
```

ansible command:

```
ansible -i hosts -m tester -a 'aliases=""' localhost --connection=local
```
##### Expected Results:

```
localhost | success >> {
    "aliases": [],
    "changed": false
}
```
##### Actual Results:

```
localhost | success >> {
    "aliases": [
        ""
    ],
    "changed": false
}
```

**Comment by hypergig** [comment]
a good workaround for now is something like...

`aliases = list() if aliases == [''] else aliases`

**Comment by mpdehaan** [comment]
Except we don't allow ternary statements like that in our source :)

All being said, I'm not so sure, I think this may be a great case for the "default" statement, or a conditional.

An empty string is not a list, it might be a typo, etc.

aliases: "{{ supplied_value | default(omit) }}"

Requires 1.8 IIRC.

**Comment by hypergig** [comment]
Why does everyone hate ternary statements?  They are like the redheaded stepchildren of the programing world :)

@mpdehaan I hear you, but if you send a module a `""` as a parameter value and parameter is of type list, I think the expectation is that you are sending an empty list right? You certainly don't expect it to be a list of one element and that element is an empty string?

**Comment by bcoca** [comment]
I like ternary statements, even have a PR to add a ternary filter, that
said, I think you should return an empty list [ ] vs an empty string, but
you ARE setting it to an empty string so the default for list will not kick
in and assume a list of 1 element, the empty string.

try:

ansible -i hosts -m tester  localhost --connection=local

**Comment by mmoya** [comment]
I was bitten by this. I agree with @hypergig that if I pass an empty value to a _list_ argument, it should be parsed as `[]` instead of `['']`.

Regarding the ternary op, not necessary if you just do:

```
roles = module.params['roles']
if roles == ['']:
    roles = list()
```

Am I missing something?

**Comment by franklinwise** [comment]
+1

**Comment by jimi-c** [comment]
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!
