### ISSUE TITLE
Bug Report(?): Should not register a variable if 'when' fails

### ISSUE THREAD

**Issue by mikebiglan** [ansible/ansible#9257]
##### Issue Type:

Bug Report?
##### Ansible Version:

1.7.1
##### Environment:

Mac OSX
##### Summary:

Came across some cases where the repro below gave some surprising results. My thought is that this should not affect the variable in the case that `when` is false. Maybe there's another construct that I'm missing, or that's needed.
##### Steps To Reproduce:

```
- shell: echo 'abc'
  register: variable
  when: "1==0"
- debug: msg="{{variable}}"
```
##### Expected Results:

I would have expected variable to be undefined (or unchanged if previously defined). 
##### Actual Results:

Instead it was set to "msg": "{u'skipped': True, u'changed': False}"

**Comment by mikebiglan** [comment]
Updated

**Comment by sivel** [comment]
It is the expected behavior that a skipped task will still register a result. A skipped task will register a 'skipped' attribute, so that you can inspect whether the task was skipped or not in a subsequent task.

**Comment by mikebiglan** [comment]
One case where I was trying to do this was to create a switch like statement. For example, if x is 1, set y to abc; if x is 2, set y to def. The best I could come up was using the command module to do this in bash or python, then register the result -- but that seemed hard to read and clunky.

I may just be missing a set of core modules or strategies to manipulate/register variables.

**Comment by mpdehaan** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
