### ISSUE TITLE
ansible-galaxy info is a no-op

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#9258]
##### Summary:

`ansible-galaxy info` doesn't do anything.
##### Steps To Reproduce:

```
ansible-galaxy install zzet.rbenv
ansible-galaxy info zzet.rbenv
```
##### Expected Results:

Output some information about the zzet.rbenv role.
##### Actual Results:

Nothing

It looks like the "info" function simply hasn't been implemented, see
 https://github.com/ansible/ansible/blob/cef2a8795f4517be65ce9f80080cff3dadac9d6c/bin/ansible-galaxy#L672-L679

**Comment by mpdehaan** [comment]
Yep, we should remove this from the CLI or make it do something.   Thanks for finding this.

**Comment by bcoca** [comment]
closing this ticket and switching tracking to the PR
