### ISSUE TITLE
Ansible Galaxy UI does not display imported app version with patch number > 9

### ISSUE THREAD

**Issue by rafecolton** [ansible/ansible#9265]
For example, https://galaxy.ansible.com/list#/roles/1428 displays `v0.2.9` as the latest release when the latest release is actually `v0.2.12`

_NOTE:_ The bug only affects the UI, role downloads still work as expected.

**Comment by jimi-c** [comment]
Hi @rafecolton, I've moved this to our internal bug tracker for Galaxy, so I'm going to close this here.

Thanks!

**Comment by rafecolton** [comment]
Thanks for following up!
