### ISSUE TITLE
Small fix to documentation on developing modules

### ISSUE THREAD

**Issue by CaptTofu** [ansible/ansible#9275]
##### Issue Type:

Documentation "docsite/rst/developing_modules.rst" refers to incorrectly-named repositories for extras and core modules. Documentation says "module-extras" where it should say "modules-extras". Also, the example shows a file without the .py extension, which is now the standard for ansible modules.
##### Ansible Version:

commit 05644686de229e29f348f37ba22adbddd0d6dbfe
##### Environment:

Ubuntu 13.04
##### Summary:

Documentation fix pertaining to naming of module repos
##### Steps To Reproduce:

view docsite/rst/developing_modules.rst
##### Expected Results:

Document says:

-Ok, let's get going with an example.  We'll use Python.  For starters, save this as a file named `time`::
.
-    ANSIBLE_LIBRARY=~/ansible-module-core:~/ansible-module-extras

Document should say

+Ok, let's get going with an example.  We'll use Python.  For starters, save this as a file named `time.py`::
-    ANSIBLE_LIBRARY=~/ansible-modules-core:~/ansible-modules-extras
##### Actual Results:

Documentation.

**Comment by CaptTofu** [comment]
Please see pull request at: https://github.com/ansible/ansible/pull/9276

**Comment by jimi-c** [comment]
Hi @CaptTofu, since you've opened a PR for this, I'm going to go ahead and close this issue.

Thanks!
