### ISSUE TITLE
unarchive - owner option

### ISSUE THREAD

**Issue by profhase** [ansible/ansible#9289]
##### Issue Type:

Bug Report + Feature Idea
##### Ansible Version:

1.7.2
##### Environment:

ubuntu 12.04
##### Summary:

The `unarchive` module seems to have the `owner` option (At least there is no error message if the owner option is set). This options does not have any effect.

I would suggest to implement the `owner` option or at least to let ansible throw an error.
##### Steps To Reproduce:

```
- name: myarc| extract
  unarchive:
   src=mytar.tar.gz
   dest=/opt/
   owner=tomcat
  sudo: yes
  sudo_user: root
```
##### Expected Results:

either:

```
failed: [mymachine] => {"failed": true}
msg: unsupported parameter for module: owner
```

or that the unarchived file is owned by `tomcat`.
##### Actual Results:

```
ok: [mymachine]
```

and the extracted file is owned by `root`.

**Comment by vjestin** [comment]
Hi,

I posted a similar [issue](https://github.com/ansible/ansible-modules-core/issues/234) in ansible-modules-core.

This one might be closed.

**Comment by mpdehaan** [comment]
Hi!

As part of our recent module restructing, modules have been moved to two different repos.   

These are:

https://github.com/ansible/ansible-modules-core
https://github.com/ansible/ansible-modules-extras

Whether a module is in core or extras can be found by consulting the documentation page for the module, where this will be noted at the bottom of the documentation page.

If you can please reopen this ticket on one of the two trackers above, we would appreciate it.

Thank you very much!
