### ISSUE TITLE
If ssh or rsync are not installed on the system, misleading "file not found" errors occur.

### ISSUE THREAD

**Issue by ShawnMilo** [ansible/ansible#9305]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.2
##### Environment:

Ubuntu 14.04 Docker image.
##### Summary:

If ssh is not installed, trying to run a command blows up with a traceback with OSError error code 2. It says "file not found." This is misleading and doesn't help the user determine the problem.

A similar problem occurs if synchronize is used without rsync installed, except there is no traceback, so it's worse.
##### Steps To Reproduce:

Run a simple playbook on a Docker container based on the official Ubuntu 14.04 image. It doesn't have openssh-client or rsync installed by default.
##### Expected Results:

Playbook executed successfully.
##### Actual Results:

ssh missing: OSError, error code 2
rsync missing: OSError, error code 2

**Comment by ShawnMilo** [comment]
There is a pull request for this here:
https://github.com/ansible/ansible/pull/9304

**Comment by abadger** [comment]
Fixed in devel and cherry-picked to stable-2.0.
