### ISSUE TITLE
Ansible is ignoring -u option

### ISSUE THREAD

**Issue by alozovskoy** [ansible/ansible#9308]
##### Ansible Version:

ansible 1.7.2 (release1.7.2 d3c28fee87) last updated 2014/10/04 20:52:50 (GMT +400)
##### Environment:

Red Hat Enterprise Linux Server release 5.5 (Tikanga)
##### Summary:

Ansible is ignoring -u option when i used it (see example).
##### Steps To Reproduce:

```
$ grep remote_user ~/.ansible.cfg
remote_user = root
```

```
$ cat inventory_file
[grp]
somehost

[grp:var]
ansible_ssh_user=root
```

```
$ ansible -i inventory_file grp -m shell -a "whoami" -u someuser
```
##### Expected Results:

```
$ ansible grp -m shell -a "whoami" -u someuser
somehost | success | rc=0 >>
someuser
```
##### Actual Results:

```
$ ansible grp -m shell -a "whoami" -u someuser
somehost | success | rc=0 >>
root
```

**Comment by mpdehaan** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:
- -u is being ignored

However, however what is happening is that:
- the -u sets a default for what to use where it's not set somewhere else

We would suggest:
- not using the inventory variable
- setting the user explicitly in the playbook

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
