### ISSUE TITLE
HTTPS docs are down.

### ISSUE THREAD

**Issue by nifr** [ansible/ansible#9311]
##### Issue Type:

Documentation Report
##### Ansible Version:

All
##### Environment:

All OS , All browsers
##### Summary:

All HTTPS sites at docs.ansible.com currently throw  a 404 and redirect to cloudflare.
##### Steps To Reproduce:

The documentation at https://docs.vagrantup.com links to https://docs.ansible.com.

Click a link that directs to docs.ansible.com
##### Expected Results:

See the docs ?
##### Actual Results:

Cloudflare 404 error.

![docs.ansible.com via HTTPS error](http://s18.postimg.org/dfo8diobt/ansible_https_down_cloudflare.png)

**Comment by mpdehaan** [comment]
I suppose somebody could be replacing ansible docs with BAD ANSIBLE DOCS, but OMG, the horror:)

Thanks for the report.   As this is the issue tracker for the project and not the infrastructure, I'm making a note of this elsewhere.

Much appreciated.

**Comment by fuzzy-id** [comment]
+1 for this feature!

There is absolutely no excuse not to enable https on a server. Especially for a site advertising a tool which aids system administration…

**Comment by tgerla** [comment]
This has been fixed!
