### ISSUE TITLE
Can not  filter the ansible facts 

### ISSUE THREAD

**Issue by canshen-yottaa** [ansible/ansible#9314]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

mac os 
##### Summary:

I can not  filter  the network interface ipaddress with ansible facts 
##### Expected Results:
# ansible -i hosts all -m setup -a "filter=ansible_eth0" -l shencan-rabbitmq-eu-01

 shencan-rabbitmq-eu-01 | success >> {
    "ansible_facts": {
        "ansible_eth0": {
            "active": true,
            "device": "eth0",
            "ipv4": {
                "address": "10.54.1.104",
                "netmask": "255.255.255.0",
                "network": "10.54.1.0"
            },
            "ipv6": [
                {
                    "address": "fe80::412:d7ff:fe49:2b57",
                    "prefix": "64",
                    "scope": "link"
                }
            ],
            "macaddress": "06:12:d7:49:2b:57",
            "module": "xen_netfront",
            "mtu": 1500,
            "promisc": false,
            "type": "ether"
        }
    },
    "changed": false
}
#### can not filter ipaddress
# ansible -i hosts all -m setup -a "filter=ansible_eth0.ipv4.address" -l shencan-rabbitmq-eu-01

shencan-rabbitmq-eu-01 | success >> {
    "ansible_facts": {},
    "changed": false
} 
or 
# ansible -i hosts all -m setup -a "filter=ansible_eth0['ipv4']['address']" -l shencan-rabbitmq-eu-01

shencan-rabbitmq-eu-01 | success >> {
    "ansible_facts": {},
    "changed": false
}

**Comment by mpdehaan** [comment]
Hi.   The filter can only be used on the basic prefixes, not the "deep" stuff like you are passing in in that last example.

As such, it doesn't know what you want to do when feeding it that syntax.

**Comment by tganzeboom** [comment]
Has this already been addressed?

**Comment by karthi81** [comment]
"deep" filter available from Ansible facts?
