### ISSUE TITLE
pip install ansible gets confused by .ansible.cfg

### ISSUE THREAD

**Issue by cnf** [ansible/ansible#9318]
When I `pip install ansible` with library set in `~/.ansible.cfg`, no modules get installed.

```
python 2.7.6
ansible 1.7.1 and 1.7.2
using virtualenvwrapper
```

Normally, I get a `~/.virtualenvwrapper/Ansible/share/ansible` directory with all the modules. If the `~/.ansible.cfg` file is set, I only get an empty `~/.virtualenvwrapper/Ansible/~` (mind the last tilde)

**Comment by mpdehaan** [comment]
Devel installs this much differently in 1.8 which should resolve all the issues you have with this.

Can you check this out on the development branch and if you have questions stop by ansible-devel?

Thanks!
