### ISSUE TITLE
'make deb' does not include all modules from 'ansible/ansible-modules-extras` repository

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#9319]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible devel (`617352a`)
##### Environment:

Ubuntu, Debian
##### Summary:

After cloning fresh Ansible git tree from GitHub and using provided `make deb` command to create Debian package of Ansible 1.8, two directories with modules from `ansible/ansible-modules-extras` repository are missing from generated packages.
##### Steps To Reproduce:

```
$ git clone --recursive https://github.com/ansible/ansible
$ cd ansible
$ make deb
$ sudo dpkg -i deb-build/unstable/ansible_*.deb
```
##### Expected Results:

```
$ find deb-build/unstable/ansible-1.8/lib/ansible/modules/extras -type d | sort
deb-build/unstable/ansible-1.8/lib/ansible/modules/extras
deb-build/unstable/ansible-1.8/lib/ansible/modules/extras/cloud
deb-build/unstable/ansible-1.8/lib/ansible/modules/extras/database
deb-build/unstable/ansible-1.8/lib/ansible/modules/extras/messaging
deb-build/unstable/ansible-1.8/lib/ansible/modules/extras/monitoring
deb-build/unstable/ansible-1.8/lib/ansible/modules/extras/net_infrastructure
deb-build/unstable/ansible-1.8/lib/ansible/modules/extras/notification
deb-build/unstable/ansible-1.8/lib/ansible/modules/extras/packaging
deb-build/unstable/ansible-1.8/lib/ansible/modules/extras/source_control
deb-build/unstable/ansible-1.8/lib/ansible/modules/extras/system
deb-build/unstable/ansible-1.8/lib/ansible/modules/extras/web_infrastructure
```
##### Actual Results:

```
$ find /usr/share/pyshared/ansible/modules/extras -type d | sort
/usr/share/pyshared/ansible/modules/extras
/usr/share/pyshared/ansible/modules/extras/cloud
/usr/share/pyshared/ansible/modules/extras/database
/usr/share/pyshared/ansible/modules/extras/messaging
/usr/share/pyshared/ansible/modules/extras/monitoring
/usr/share/pyshared/ansible/modules/extras/net_infrastructure
/usr/share/pyshared/ansible/modules/extras/notification
/usr/share/pyshared/ansible/modules/extras/system
/usr/share/pyshared/ansible/modules/extras/web_infrastructure
```

**Comment by jimi-c** [comment]
Hi @drybjed, I just tested this out on an Ubuntu 14.04 machine and was unable to reproduce it. I even checked the file counts and compared it to what is currently in `lib/modules/extras`, which match up:

<pre>
root@ubuntu1404:~/new_ansible# find deb-build/unstable/ansible-1.8/lib/ansible/modules/extras -type f | wc -l
113
root@ubuntu1404:~/new_ansible# find lib/ansible/modules/extras -type f | wc -l
113
</pre>

So maybe this was some transient error, or some versions of git require a second call to `git submodules update --init` before the submodules are cloned correctly?

**Comment by drybjed** [comment]
@jimi-c Some time after posting this issue I've checked `devel` branch and indeed, all modules are now included in the Debian package, so I think it was a transient error.

**Comment by jimi-c** [comment]
@drybjed excellent, thanks for the follow up. Definitely let us know if you see that happen again.

Thanks!

**Comment by vincentvdk** [comment]
It seems that the cloud modules in "core" are not installed by the package. I'm running Ubuntu 14.04 and devel branch.

**Comment by srgvg** [comment]
$ dpkg -c deb-build/unstable/ansible_1.8-0.git201411050225~unstable_all.deb  | grep cloud
drwxr-xr-x root/root         0 2014-11-05 13:53 ./usr/share/pyshared/ansible/modules/extras/cloud/
-rw-r--r-- root/root     14190 2014-11-05 09:33 ./usr/share/pyshared/ansible/modules/extras/cloud/ovirt.py
-rw-r--r-- root/root     13870 2014-09-30 10:55 ./usr/share/pyshared/ansible/modules/extras/cloud/virt.py

**Comment by vincentvdk** [comment]
That seems to be the "extra's" which i do have. But not the "core" cloud modules (amazon, docker, etc...)

**Comment by jimi-c** [comment]
Based on @drybjed's experience, this would seem to be an issue with the sequence of commands. @vincentvdk, please make sure you run a `git submodule update --init` before running the `make deb` command to see if that helps.

**Comment by srgvg** [comment]
my example was based on a fully updated tree

**Comment by srgvg** [comment]
```
ls deb-build/unstable/ansible-1.8/lib/ansible/modules/*/cloud/
deb-build/unstable/ansible-1.8/lib/ansible/modules/core/cloud/:
amazon  azure  digital_ocean  docker  google  __init__.py  linode  openstack  rackspace  vmware

deb-build/unstable/ansible-1.8/lib/ansible/modules/extras/cloud/:
__init__.py  ovirt.py  virt.py
```

Sounds like an issue with an extra subdir in the modules dir?

**Comment by vincentvdk** [comment]
looks like it.

**Comment by bcoca** [comment]
weird, it does not affect packaging, which also has subcategories now

On Wed, Nov 5, 2014 at 8:56 AM, Vincent Van der Kussen <
notifications@github.com> wrote:

> looks like it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible/issues/9319#issuecomment-61809864.

## 

Brian Coca

**Comment by bcoca** [comment]
damn, my fault

had not realized that setup.py had been changed to use **init**.py and .py
in modules to build ansible (now I understand why modules had extensions
added).

fixing it

On Wed, Nov 5, 2014 at 10:57 AM, Brian Coca bcoca@ansible.com wrote:

> weird, it does not affect packaging, which also has subcategories now
> 
> On Wed, Nov 5, 2014 at 8:56 AM, Vincent Van der Kussen <
> notifications@github.com> wrote:
> 
> > looks like it.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ansible/ansible/issues/9319#issuecomment-61809864.
> 
> ## 
> 
> Brian Coca

## 

Brian Coca

**Comment by bcoca** [comment]
https://github.com/ansible/ansible-modules-core/pull/276 should fix this, other subcategories worked cause Micheal did them and was aware of the **init**.py requirement

**Comment by bcoca** [comment]
#9489 updated main to pick up the fix in core modules

**Comment by vincentvdk** [comment]
Just tested this. cloud modules in core are now installed by package. Thanks
