### ISSUE TITLE
Double chdir: failed on relative paths

### ISSUE THREAD

**Issue by nordicdyno** [ansible/ansible#9322]
1s cwd: https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L1439

2nd cwd in the same codeflow: https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L1444
(cwd for Popen set in https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L1431)

I'm novice in Ansible and not sure is it bug or not, but I've had a some "funny" moments try to implement my own Ansible module with `module.run_command` method.

**Comment by mpdehaan** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a code related question, and we'd like to direct these kinds of things to the mailing list:
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
