### ISSUE TITLE
ec2_groups subsequent runs fail

### ISSUE THREAD

**Issue by lcc2207** [ansible/ansible#9327]
Is anyone else seeing subsequent runs fail on the ec2_group module in a private VPC?  This seems to work fine in the default VPC.

**Comment by mpdehaan** [comment]
Hi,

I'm sorry for the late response our normal info bot isn't running right now.

This looks like this is related to ec2 modules, can you reopen this ticket over at https://github.com/ansible/ansible-modules-core and fill out the info in https://github.com/ansible/ansible/blob/devel/ISSUE_TEMPLATE.md ?

Thanks!!!
