### ISSUE TITLE
Ansible fails during gather facts on OpenSuSE 13.1

### ISSUE THREAD

**Issue by marcinpraczko** [ansible/ansible#9330]
Hi,

I just run ansible setup module on OpenSuSE 13.1 and ansible crashed during gathering facts:

```
GATHERING FACTS *************************************************************** 
failed: [localhost] => {"failed": true, "parsed": false}
...
  File "/usr/lib64/python2.7/re.py", line 142, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer
```

As I can see, this is related with wrong parsing /etc/SuSE-release file.

Ansible branch: devel: Just checked out with commit: 617352a38e93ea291a80d383079ea6e5cd93798e

**Comment by marcinpraczko** [comment]
Added pull request: #9331 which fixed issue on my environment:

```
cat /etc/SuSE-release
openSUSE 13.1 (x86_64)
VERSION = 13.1
CODENAME = Bottle
```

**Comment by marcinpraczko** [comment]
From my point of view would be very nice to write unitest for this as well, especially that distros changes how "release" details are handle.

I was thinking about creating some subfolder and copy files like /etc/SuSE-release there, then test whether files are correctly parsed.

I am happy work on uni-test on this if you will point me to right place in terms of uni-test structure. 

Best regards.

**Comment by mpdehaan** [comment]
Unit tests don't really make sense in this case, but integration tests do. 

See what we have already in tests/integration ...

**Comment by mpdehaan** [comment]
I'm going to close this ticket as #9331 already tracks this issue and this simplifies things, thanks!
