### ISSUE TITLE
ansible should warn the user when an unsupported jinja2 filter is used

### ISSUE THREAD

**Issue by wu-lee** [ansible/ansible#9333]
##### Issue Type:

Bug Report / Feature Request
##### Ansible Version:

```
$ ansible --version
ansible 1.8 (devel 2eda9a3a47) last updated 2014/10/10 18:43:36 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 5af8d55b03) last updated 2014/10/10 18:43:44 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 681db4ce2c) last updated 2014/10/10 18:43:45 (GMT +100)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/08 10:13:54 (GMT +100)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/08 10:14:38 (GMT +100)
  configured module search path = /home/nick/i/gitworking/controllis/ansible/ansible/library:library/modules
```
##### Environment:

Ubuntu 12.0.4
##### Summary:

Ansible does not catch invalid filters when they are used in Jinja2.  Either no error results, or an arbitrary and typically perplexing one if the resulting string is not acceptable for the case in question.
##### Steps To Reproduce:

An example working playbook, test.yml:

```

---
- name: test
  hosts: all

  vars:
path: /tmp/deleteme

  tasks:
- name: test 
  action: file
      path="{{ path }}"
      state=directory
```

Run like this (assuming localhost is defined in ansible_hosts):

```
ansible-playbook -c local -l localhost test.yml -v
```

Success:

```
PLAY [test] ******************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [test] ****************************************************************** 
ok: [localhost] => {"changed": false, "gid": 1000, "group": "nick", "mode": "0775", "owner": "nick", "path": "/tmp/deleteme", "size": 4096, "state": "directory", "uid": 1000}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

A directory should have appeared, /etc/deleteme.  Remove it and modify the playbook to add a filter 'nonesuch'which is not currently implemented, like this:

```

---
- name: test
  hosts: all

  vars:
path: /tmp/deleteme

  tasks:
- name: test 
  action: file
      path="{{ path | nonesuch }}"
      state=directory
```

(In my case, what happened was the reverse, I ran a playbook using a custom filter on another installtion which did not have that filter installed.  The result is equivalent.)

Run it as above.  Apparent success in this case, there is no error:

```
PLAY [test] ******************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [test] ****************************************************************** 
changed: [localhost] => {"changed": true, "gid": 1000, "group": "nick", "mode": "0775", "owner": "nick", "path": "{# path | nonesuch #}", "size": 4096, "state": "directory", "uid": 1000}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
```

However, there also is not a directory where you'd expect at /tmp/deleteme.  Instead, ansible has created a directory in the current directory, literally called "{{ path | nonesuch }}"!

Notice the output includes "{# path | nonesuch #}" as the literal value of "path".   The "{# ... #}" delimiters are perplexing, as there is no obvious reason why ansible produced this string rather than "{{ ... }}". It's not clear if ansible is attempting to signify something with this substitution; in hindsight I suspect this is just the manifestation of an implementation detail.

Inspection of my playbook did not immediately show the problem because the filter I had used appeared to be legitimate.

If you change the example to make the error in different contexts, the result may be a knock-on error, such as "with_items expects a list", depending on the context.  Or it may silently do something unexpected, as above.  This is the worst case!
##### Expected Results:

I would expect ansible to halt and emit an error, telling me that I had tried to use a filter which jinja2 did not know about.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
