### ISSUE TITLE
git module cannot clone ansible devel branch

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#9334]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible v1.7.2, Ansible devel
##### Environment:

Ubuntu, Debian
##### Summary:

`git` module fails with an error while cloning current `devel` Ansible branch. Stable version clones correctly.
##### Steps To Reproduce:

```
ansible -i inventory localhost -m git -a 'repo=https://github.com/ansible/ansible.git dest=~/src/github.com/ansible-devel/ansible version=devel update=yes recursive=yes'
```
##### Expected Results:

```
localhost | success >> {
    "after": "d3c28fee8739c93821d4f639b2931f5a3592eb8e", 
    "before": null, 
    "changed": true
}
```
##### Actual Results:

```
localhost | FAILED >> {
    "failed": true, 
    "msg": "Failed to init/update submodules: fatal: Needed a single revision\nUnable to find current origin/master revision in submodule path 'lib/ansible/modules/core'\n"
}
```

**Comment by tribloom** [comment]
I am also seeing this fail.
- name: Install Ansible from source
  git: accept_hostkey=yes dest=/home/user/ansible repo=git://github.com/ansible/ansible.git

**Comment by Gerst20051** [comment]
that's wierd...

**Comment by mpdehaan** [comment]
As this is a module related ticket, please file these at https://github.com/ansible/ansible-modules-core .

Thanks!
