### ISSUE TITLE
Callbacks should have a check mode

### ISSUE THREAD

**Issue by rafecolton** [ansible/ansible#9342]
##### Issue Type:

Feature Idea
##### Ansible Version:

`ansible 1.7.2`
##### Environment:

Running on Mac OS X against Ubuntu 14.04
##### Summary:

Ansible callbacks should have a way to handle check mode just like modules currently do.

/cc @jszwedko

**Comment by mpdehaan** [comment]
I don't know what this means really, can you stop by ansible-devel to discuss?

Thanks!

**Comment by jszwedko** [comment]
@mpdehaan Sure thing! https://groups.google.com/forum/#!topic/ansible-devel/sqJbFzoynfY
