### ISSUE TITLE
Docker containers aren't detected as such

### ISSUE THREAD

**Issue by gquintard** [ansible/ansible#9349]
On more recent docker versions, libcontainer is used instead of lxc, and so ansible_virtualization_type is not filled correctly.

Here's a patch proposition, checking /proc/1/cgroup for '/docker/' as well as '/lxc/'. It may be a bit brutal though.

http://pastebin.com/mWXGWGEp

**Comment by mpdehaan** [comment]
Can you please submit this as a pull request instead of a gist?

We'd be glad to have it.

Thanks!
