### ISSUE TITLE
service module, "check" instead of "status" for checking state on OpenBSD

### ISSUE THREAD

**Issue by gangelop** [ansible/ansible#9364]
##### Issue Type:

Feature Idea
##### Ansible Version:

`ansible 1.7.2`
##### Environment:

running from: N/A
applied on: OpenBSD
##### Summary:

The `service` module uses the `status` command of service scripts to check their status. However, on OpenBSD, rc scripts by default use the operations defined in `rc.subr(8)`. So instead of `status` used in linux, in OpenBSD we have `check`.

From [man 8 rc.subr](http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man8/rc.subr.8?query=rc.subr&sec=8)

```
 check
    Call rc_check. Return 0 if the daemon is running or 1 if it is not.
```

Maybe the `service` module can be made to run `check` instead of `status` for OpenBSD hosts so I don't have to define process patterns for all the services. Maybe this also applies to other BSDs? I've only checked OpenBSD.

**Comment by mpdehaan** [comment]
As this is a module related ticket, please file these at https://github.com/ansible/ansible-modules-core .

Thanks!

**Comment by gangelop** [comment]
done https://github.com/ansible/ansible-modules-core/issues/200
