### ISSUE TITLE
Templated variables are evaluated too early

### ISSUE THREAD

**Issue by hkariti** [ansible/ansible#9393]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel 43b3eecf52) last updated 2014/10/21 14:16:58 (GMT +300)
  lib/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/05 10:14:39 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/05 10:14:46 (GMT +300)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/07 10:31:50 (GMT +300)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/07 10:31:55 (GMT +300)
  configured module search path = None
##### Environment:

Ubuntu 14.04
##### Summary:

This issue is a more broad case of #9242. It seems like templated variables are evaluated as soon as possible during parsing, and if the variables in the template change after this initial parsing they are not re-evaluated, and so their value isn't updated.

Related ansible-project thread: https://groups.google.com/forum/#!topic/ansible-project/EunpeCL45k8
##### Steps to reproduce

inventory:

```
localhost ansible_connection=local
[all:vars]
var=one
```

vars_file:

```
var2: "{{var}}"

mapping:
  one: 1
  two: 2
```

override_mapping.yml:

```

---
- name: Overriding mapping key
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars_file
  vars:
    value: "{{mapping[var]}}"
  tasks:
    - debug: var=var
    - debug: var=var2
    - debug: var=value
```

default_inventory_var.yml:

```

---
- name: Default value for inventory variable
  hosts: localhost
  gather_facts: no
  vars:
    var2: "{{ var  | default('none') }}"
  tasks:
    - debug: var=var
    - debug: var=var2
```

commands:

```
# Test overriding mapping key with -e
ansible-playbook -i inv override_mapping.yml -e var=two

# Test default value of variable defined in inventory
ansible-playbook -i inv default_inventory_var.yml
```
##### Expected Results:

```
PLAY [Overriding mapping key] ************************************************* 

TASK: [debug var=var] ********************************************************* 
ok: [localhost] => {
    "var": "two"
}

TASK: [debug var=var2] ******************************************************** 
ok: [localhost] => {
    "var2": "two"
}

TASK: [debug var=value] ******************************************************* 
ok: [localhost] => {
    "value": "2"
}

PLAY [Default value for inventory variable] ************************************* 

TASK: [debug var=var] ********************************************************* 
ok: [localhost] => {
    "var": "one"
}

TASK: [debug var=var2] ******************************************************** 
ok: [localhost] => {
    "var2": "one"
}
```
##### Actual results:

```
PLAY [Overriding mapping key] ************************************************* 

TASK: [debug var=var] ********************************************************* 
ok: [localhost] => {
    "var": "two"
}

TASK: [debug var=var2] ******************************************************** 
ok: [localhost] => {
    "var2": "one"
}

TASK: [debug var=value] ******************************************************* 
ok: [localhost] => {
    "value": "1"
}

PLAY [Default value for inventory variable] ************************************* 

TASK: [debug var=var] ********************************************************* 
ok: [localhost] => {
    "var": "one"
}

TASK: [debug var=var2] ******************************************************** 
ok: [localhost] => {
    "var2": "none"
}
```

**Comment by mpdehaan** [comment]
Hi, "-e" has the highest precedence in Ansible as described in http://docs.ansible.com/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable so it looks like this is more of a misunderstanding.

If you have further questions, can you stop by ansible-project list?

Thanks!
