### ISSUE TITLE
ansible-vault edit results in ERROR: global name 'data' is not defined

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#9399]
##### Ansible Version: $ ansible --version

ansible 1.8 (devel 707474a43a) last updated 2014/10/22 02:15:27 (GMT -500)
  lib/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/07 14:28:03 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/07 14:28:06 (GMT -500)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/07 14:28:11 (GMT -500)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/07 14:28:15 (GMT -500)
  configured module search path = None
##### Environment:

OSX 10.9.5
Python 2.7.5

$ pip list
ecdsa (0.11)
httplib2 (0.9)
isodate (0.5.0)
Jinja2 (2.7.3)
MarkupSafe (0.23)
paramiko (1.15.1)
passlib (1.6.2)
pip (1.5.6)
pycrypto (2.6.1)
pywinrm (0.0.3)
PyYAML (3.11)
setuptools (3.6)
wsgiref (0.1.2)
xmltodict (0.9.0)
##### Summary:

Attempting to edit an encrypted vault results in an error.
##### Steps To Reproduce:

$ ansible-vault  create ~/tmp/blah
$ cat ~/tmp/blah
$ANSIBLE_VAULT;1.1;AES256
64343865373339636535303136333130623665643332333033646661343637656630626563316231
3230333030343335353034643330383236653235643139640a366561326337303735666139626434
36323832663664353065333935366635323062663135363766396130623333343530633931643532
3862393630633331320a393332636132386139613536653835373665336636336566633832633831
6466

$ ansible-vault  edit ~/tmp/blah
Vault password:
ERROR: global name 'data' is not defined

 ansible-vault  --debug edit ~/tmp/blah
Vault password:
Traceback (most recent call last):
  File "/Users/tanner/projects/ansible.git/ansible/bin/ansible-vault", line 225, in main
    fn(args, options, parser)
  File "/Users/tanner/projects/ansible.git/ansible/bin/ansible-vault", line 156, in execute_edit
    this_editor.edit_file()
  File "/Users/tanner/projects/ansible.git/ansible/lib/ansible/utils/vault.py", line 255, in edit_file
    self._edit_file_helper(existing_data=dec_data)
  File "/Users/tanner/projects/ansible.git/ansible/lib/ansible/utils/vault.py", line 192, in _edit_file_helper
    self.write_data(data, tmp_path)
NameError: global name 'data' is not defined

ERROR: global name 'data' is not defined
##### Expected Results:

Ability to edit encrypted vault
##### Actual Results:

$ ansible-vault  edit ~/tmp/blah
Vault password:
ERROR: global name 'data' is not defined

**Comment by basictheprogram** [comment]
Don't know much about git (sorry) but I think this is the patch you need to fix this problem.

```
diff --git a/lib/ansible/utils/vault.py b/lib/ansible/utils/vault.py
index 506c085..50b686c 100644
--- a/lib/ansible/utils/vault.py
+++ b/lib/ansible/utils/vault.py
@@ -189,7 +189,7 @@ class VaultEditor(object):
         _, tmp_path = tempfile.mkstemp()

         if existing_data:
-            self.write_data(data, tmp_path)
+            self.write_data(existing_data, tmp_path)

         # drop the user into an editor on the tmp file
         call(self._editor_shell_command(tmp_path))
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
