### ISSUE TITLE
get_url module documentation incorrect

### ISSUE THREAD

**Issue by alexintel** [ansible/ansible#9403]
##### Issue Type:

Documentation Report
##### Ansible Version:

ansible 1.7.2 / ALL
##### Environment:

ALL
##### Summary:

http://docs.ansible.com/get_url_module.html
- 'mode' parameter undocumented, but listed in examples section
- 'timeout' parameter does not work
##### Steps To Reproduce:

``` ruby
- name: download config from URL
  sudo: yes
  get_url: url=url_to_download
           dest=/tmp/settings.conf
           force=yes
           mode=0644
           timeout=10
```
##### Expected Results:

expect file to be downloaded, duh!
##### Actual Results:

failed: [127.0.0.1] => {"failed": true}
msg: unsupported parameter for module: timeout

**Comment by sivel** [comment]
The `timeout` option as documented was added in ansible 1.8 which has yet to be released.

```
timeout no  10  
Timeout for URL request (added in Ansible 1.8)
```

As for `mode`, that is described as an `others` parameter: 

```
others  no      
all arguments accepted by the file module also work here
```

**Comment by mpdehaan** [comment]
Module tickets should be filed on the modules repo.  Can you please open this here:

https://github.com/ansible/ansible-modules-core

**Comment by alexintel** [comment]
Thank you for clarification!
