### ISSUE TITLE
git module ignore recursive option on update

### ISSUE THREAD

**Issue by ka2er** [ansible/ansible#9409]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.2
##### Environment:

Centos 6
##### Summary:

When using git module with recursive=no the option is used on initial clone but ignore on subsequent checkout if new commits are available
##### Steps To Reproduce:

use a task like :

name: sync front with prepub branch (www) git: repo="{{local_git}}" dest={{git_root}} version={{git_branch_name}} recursive=no
run the task a first time,
add commits to your branch,
run a second time
##### Expected Results:

submodule are always ignored 
##### Actual Results:

submodule aren't ignore after initial clone if they are new commits available

**Comment by mpdehaan** [comment]
There are lots of duplicate reports on this one, work is in progress.

In the future please file module related tickets at https://github.com/ansible/ansible-modules-core

Thanks!
