### ISSUE TITLE
SyntaxError: invalid syntax on "with open" on python-2.4.3

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#9413]
##### Ansible Version: $ ansible --version

ansible 1.8 (devel c86851be2c) last updated 2014/10/24 00:41:56 (GMT -500)
  lib/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/07 14:28:03 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/07 14:28:06 (GMT -500)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/07 14:28:11 (GMT -500)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/07 14:28:15 (GMT -500)
  configured module search path = None
##### Environment:

Control host
OSX 10.9.5
Python 2.7.5

Remote host
CentOS release 5.11 (Final)
Python 2.4.3
##### Summary:
- name: set hostname
  sudo: yes
  hostname: name={{hostname}}
  tags: common

failed: [hostname] => {"failed": true, "parsed": false}

SUDO-SUCCESS-jfgkjtdgalqvbjndubjbbdsatsojqexi
  File "/home/ansible/.ansible/tmp/ansible-tmp-1414129524.27-258463616464227/hostname", line 1826
    with open(self.HOSTNAME_FILE, 'r') as f:
            ^
SyntaxError: invalid syntax
##### Expected Results:

Hostname play should set the hostname.
##### Actual Results:

  File "/home/ansible/.ansible/tmp/ansible-tmp-1414129524.27-258463616464227/hostname", line 1826
    with open(self.HOSTNAME_FILE, 'r') as f:
            ^
SyntaxError: invalid syntax

Very similar to these issues:

https://github.com/ansible/ansible/issues/9080
https://github.com/ansible/ansible/issues/5044

**Comment by ienliven** [comment]
I thought ansible hosts requires Python 2.4, this is a feature from Python 2.5+. 

Got same error:

TASK: [hostname name={{ inventory_hostname }}] ********************************
failed: [appserver-1] => {"failed": true, "parsed": false}
  File "/root/.ansible/tmp/ansible-tmp-1415326823.76-43865982221474/hostname", line 1826
    with open(self.HOSTNAME_FILE, 'r') as f:
            ^
SyntaxError: invalid syntax

FATAL: all hosts have already failed -- aborting

**Comment by bcoca** [comment]
@ienliven correct, that is why this is a bug

**Comment by basictheprogram** [comment]
```
with open(self.HOSTNAME_FILE, 'r') as f:
```

Would need to be replaced with something like this

```
f = open(self.HOSTNAME_FILE, 'r')
try:
    # do stuff with f
finally:
    f.close()
```

This is what I did to resolve(?) the problem, for each "with open" I replaced it with code similar to this:

```
def get_permanent_hostname(self):
    f = open(self.HOSTNAME_FILE, 'r') 
    try:
        for line in f:
            line = line.strip()
            if line.startswith('hostname='):
                return line[10:].strip('"')
        return None
    except Exception, err:
        self.module.fail_json(msg="failed to read hostname: %s" % str(err))
    finally:
        f.close()
```

**Comment by bcoca** [comment]
@basictheprogram want to submit that in a PR?

**Comment by basictheprogram** [comment]
I know PR probably means Pull Request but I'm a git newbie (bzr guy). Give me some time to figure out how to do a PR and I'll do it or give me a URL/whitepaper/HOWTO and I'll work things from there. Let me look at the test suite doc to make sure my changes don't break something, cause a regression, and actually fix the problem listed here. :-)

**Comment by kevinconway** [comment]
@basictheprogram 
Just happened by this issue. You may want to check out [GitHub bootcamp](https://help.github.com/categories/bootcamp/) for getting bootstrapped with git and [the help doc on pull requests](https://help.github.com/articles/using-pull-requests/) for getting your pull request out there. If you want a deeper dive you can always use something like [the git book](http://git-scm.com/book/en/v2).

It's a shame there isn't a `__future__` available in 2.4 for this...

**Comment by bcoca** [comment]
fixed in https://github.com/ansible/ansible-modules-core/commit/e4b696890127e88d9fbd616d829a0b3f5515e731

**Comment by vikjainbestbuy** [comment]
Done the changes in the ansible.cfg file but having same error.


[defaults]

remote_tmp = /tmp/ansible-$USER
# some basic default values...
hostfile = inventory

 

fatal: [vxpim]: FAILED! => {
"changed": false,
"module_stderr": "OpenSSH_7.4p1, OpenSSL 1.0.2k-fips 26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 72: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 18138\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to vxpim closed.\r\n",
"module_stdout": " File \"/tmp/ansible-vikjain/ansible-tmp-1552938297.39-143951237435117/AnsiballZ_setup.py\", line 39\r\n with open(module, 'wb') as f:\r\n ^\r\nSyntaxError: invalid syntax\r\n",
"msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
"rc": 1
}
