### ISSUE TITLE
fetch: should use hostname instead of ip for directory name

### ISSUE THREAD

**Issue by mwarkentin** [ansible/ansible#9415]
##### Summary:

As per the [Ansible Project discussion](https://groups.google.com/forum/?nomobile=true#!msg/ansible-project/ky01x1PY_H8/70c5jGGJolgJ) with @jimi-c and @mpdehaan, `fetch` should be using `inventory_hostname` rather than `conn.host` to name the download directory.

In the meantime, you can use this as a workaround:

`- fetch: src=/etc/hosts dest="/tmp/{{inventory_hostname}}/" flat=yes`
##### Steps To Reproduce:
- Create a task which uses the `fetch` module to pull down a file from one or more remote hosts
##### Expected Results:

File system tree is built using the hostname: 
![](https://s3.amazonaws.com/snaps.michaelwarkentin.com/scan-fs.yml__waveapps_2014-10-24_11-35-04.png)
##### Actual Results:

File system tree is built using the host ip: 
![](https://s3.amazonaws.com/snaps.michaelwarkentin.com/scan-fs.yml__waveapps_2014-10-24_11-36-32.png)

**Comment by bcoca** [comment]
closed via merge
