### ISSUE TITLE
EL 6.6 connection ControlPersist issues

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#9417]
##### Issue Type:

Bug Report
##### Ansible Version:

All
##### Environment:

RHEL 6.6 control machines only with pipelining
##### Summary:

Yay RHEL 6.6 has control persist.

Oh no, they screwed it up!

It seems we need to, if the connection type is 'smart' or 'ssh', inside of Runner, check the OS.  If we are on RHEL 6.X and have selected 'ssh' (either directly of via 'smart') we should ignore the user's pipelining request if pipelining is on and issue a warning.

As per:

https://groups.google.com/d/msgid/ansible-project/alpine.LRH.2.02.1410151654210.28571%40pikachu.3ti.be
##### Steps To Reproduce:

see mailing list
##### Expected Results:

see mailing list
##### Actual Results:

see mailing list

**Comment by abadger** [comment]
reportedly, this is occurring when running ansible on RHEL6 to manage another host.  It is not happening when running on another host to manage RHEL6.

**Comment by abadger** [comment]
Red Hat bugzilla report against openssh: https://bugzilla.redhat.com/show_bug.cgi?id=1160487

The patch linked there appears to fix the issues (Fedora Infrastructure has tested it).

**Comment by abadger** [comment]
Bug has been fixed: https://rhn.redhat.com/errata/RHBA-2014-1854.html

**Comment by abadger** [comment]
Confirmed problem occurred on a centos6 host with: openssh-clients.x86_64 0:5.3p1-104.el6

Problem went away once upgraded to: openssh-clients.x86_64 0:5.3p1-104.el6_6.1

Closing ticket as this is now taken care of.
