### ISSUE TITLE
facts to gather CIDR aswell as netmask for my IPv4

### ISSUE THREAD

**Issue by kiranos** [ansible/ansible#9435]
##### Issue Type:

Feature Idea
##### Ansible Version:

1.7
##### Environment:

Debian
##### Summary:

I would like facts to gather CIDR aswell as netmask for my IPv4, Its useful for alot of config files where it doesnt take 255.255.255.0 but rather only allow /24, like quagga's ospfd.conf
##### Steps To Reproduce:

check facts with -m setup
##### Expected Results:

I want to get:

```
"ansible_default_ipv4": {
   "address": "192.168.0.161",
   "alias": "bond0",
   "gateway": "192.168.0.1",
   "interface": "bond0",  
   "macaddress": "01:01:03:00:23:05",
   "mtu": 1500,
   "netmask": "255.255.254.0",
   "cidr": "/23",
   "network": "192.168.0.0",
   "type": "bonding"
},
```
##### Actual Results:

```
"ansible_default_ipv4": {
   "address": "192.168.0.161",
   "alias": "bond0",
   "gateway": "192.168.0.1",
   "interface": "bond0",  
   "macaddress": "01:01:03:00:23:05",
   "mtu": 1500,
   "netmask": "255.255.254.0",
   "network": "192.168.0.0",
   "type": "bonding"
},
```

**Comment by jmrodri** [comment]
Can this be a simple calculation or lookup of the netmask into CIDR? Seems pretty doable.

**Comment by mpdehaan** [comment]
Yeah I feel this should be a lookup plugin using python-netaddr most likely.

Feel free to stop by ansible-devel list if you'd like to discuss, I think this is the 2nd time I've heard about a request for something like this, and that seems to be the right place for it.

Thanks!

**Comment by bcoca** [comment]
a filter that provides this is going to be resubmitted as per #9373
