### ISSUE TITLE
certain upstart service on Amazon Linux fails with enabled=yes with ansible 1.7.2

### ISSUE THREAD

**Issue by ngrennan-banjo** [ansible/ansible#9441]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.2
##### Environment:

Amazon Linux AMI release 2014.09
##### Summary:

I have the same issue as #7715, with ansible 1.7.2. It looks like the patch wasn't forward ported. I tested the commit on 1.7.2, and it works properly.
##### Steps To Reproduce:

Use Amazon Linux
Create a service in /etc/init/beaver.service. Do not create a /etc/init.d/beaver script.

In a task write:
-  name: start beaver 
  action: service name=beaver state=started enabled=yes
##### Expected Results:

Service enabled
##### Actual Results:

myhost | FAILED >> {
"failed": true, 
"msg": "cannot detect command to enable service beaver, typo or init system potentially unknown"
}

**Comment by mpdehaan** [comment]
Thanks for the report, in the future, since this is a module, please report this to https://github.com/ansible/ansible-modules-core.

**Comment by bcoca** [comment]
closing as this is in the wrong repo and the issue also seems to have been solved in the proper repo
