### ISSUE TITLE
rax.py plugin error: AttributeError: 'NoneType' object has no attribute 'servers'

### ISSUE THREAD

**Issue by devx** [ansible/ansible#9453]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.1
##### Environment:

Linux  3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
##### Summary:

When using dynamic inventory rax.py plugin using a account that doesn't have access to UK servers it returns a  **'NoneType'** error.

<pre><code>
ansible -i /etc/ansible/rax.py all --list-hosts
Traceback (most recent call last):
  File "/etc/ansible/rax.py", line 284, in <module>
    main()
  File "/etc/ansible/rax.py", line 277, in main
    _list(regions)
  File "/etc/ansible/rax.py", line 161, in _list
    for server in cs.servers.list():
AttributeError: 'NoneType' object has no attribute 'servers'
</code></pre>

I added some debug symbols to my local version to test and here is the output.

```
./rax.py --list
SYD
<novaclient.v1_1.client.Client object at 0x7f25afd17810>
IAD
<novaclient.v1_1.client.Client object at 0x7f25afd09690>
DFW
<novaclient.v1_1.client.Client object at 0x7f25afcb8d10>
LON
None
Traceback (most recent call last):
  File "./rax.py", line 286, in <module>
    main()
  File "./rax.py", line 279, in main
    _list(regions)
  File "./rax.py", line 163, in _list
    for server in cs.servers.list():
AttributeError: 'NoneType' object has no attribute 'servers'
```
##### Steps To Reproduce:

Download the plugin rax.py (tested versions 1.71, 1.72, devel), and setup your credentials

```
ansible -i /etc/ansible/rax.py all --list-hosts
```
##### Expected Results:

List of all servers available in all reagions
##### Actual Results:

```
ansible -i /etc/ansible/rax.py all --list-hosts
Traceback (most recent call last):
  File "/etc/ansible/rax.py", line 284, in <module>
    main()
  File "/etc/ansible/rax.py", line 277, in main
    _list(regions)
  File "/etc/ansible/rax.py", line 161, in _list
    for server in cs.servers.list():
AttributeError: 'NoneType' object has no attribute 'servers'
```
##### Workaround:

To get around this set the variable to the region you want.

```
root@ans-test:~# RAX_REGION=ord ansible -i /etc/ansible/rax.py all --list-hosts
No hosts matched
root@ans-test:~# RAX_REGION=iad ansible -i /etc/ansible/rax.py all --list-hosts
    ww-ans-dev1
```

**Comment by sivel** [comment]
This is known and we are working on a pull request that will have this fixed soon.

**Comment by devx** [comment]
Thanks for the update, I looked for a similar bug but I didn't find a bug report. Maybe I did not look hard enough.  Since you are working on the pull request, I won't bother fixing it.

**Comment by sivel** [comment]
It is set for inclusion in #9307

**Comment by mpdehaan** [comment]
Closing this since tracked by the other ticket.

Thanks!
