### ISSUE TITLE
service: nginx enabled=yes not enabling service ansible 1.7.2

### ISSUE THREAD

**Issue by oppianmatt** [ansible/ansible#9456]
# Issue Type:

Bug Report
# Ansible Version:

1.7.2

1.6.6
# Environment:

Destination: Ubuntu 12.04.4 LTS

Control hosts: Mac OSX and Ubuntu 12.04.4 LTS
# Summary:

When trying to enable nginx, which is a typical init.d startup script. It appears to not have any affect. 

Have tried with both ansible versions and with Mac OSX and Ubuntu 12.04 control hosts. Destination host is a Ubuntu 12.04
# Steps To Reproduce:

Install nginx from deb and it will create a /etc/init.d/nginx script

In a task write:

```
  - name: start nginx on boot
    service: name=nginx state=started enabled=yes
    tags: nginx_boot
```

Run the playbook.

```
ansible-playbook site.yaml -i inventory/prod -l host02.example.com -t nginx_boot
```
# Expected Results:

Service enabled
# Actual Results:

Reports changed every time:

```
TASK: [nginx | start nginx on boot] *******************************************
changed: [host02.example.com]
```

chkconfig and rc.d directories unchanged:

```
root@host02:/etc# chkconfig nginx
nginx  off

root@host02:/etc# ls rc*/*nginx*
rc0.d/K00nginx  rc1.d/K00nginx  rc2.d/K00nginx  rc3.d/K00nginx  rc4.d/K00nginx  rc5.d/K00nginx  rc6.d/K00nginx
```

**Comment by mpdehaan** [comment]
Hi can you please open this ticket on the modules repo instead of the main project?  This one should be http://github.com/ansible/ansible-modules-core.

Thanks!
