### ISSUE TITLE
 [bug report] host-pattern rule do not compatible with older versions

### ISSUE THREAD

**Issue by iambocai** [ansible/ansible#9459]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

Centos 6
##### Summary:

in older versions,  list_host  = re.search(group.name)  +  re.search(host.name)
in version 1.7.2,  list_host  = re.search(group.name)  +  re.match(host.name)

this difference may made by mistake and should be fixed. (see [here](https://github.com/iambocai/ansible/commit/f475c5a6e927bb69eb0487a43291cf7304be8e54) )
##### Steps To Reproduce:

prepare a host file(at /tmp/test.hosts) with follow lines:

>    sd-a-fe01.bj
>    sd-a-fe02.bj
>    sd-a-fe03.bj
>    sd-a-fe04.bj
>    sd-b-fe01.bj
##### Expected Results:

>  [iambocai@sd-a-cs01 tmp]$ ansible -i /tmp/test.hosts '~a-fe'  --list
>    sd-a-fe01.bj
>    sd-a-fe02.bj
>    sd-a-fe03.bj
>    sd-a-fe04.bj
##### Actual Results:

>  [iambocai@sd-a-cs01 tmp]$ ansible -i /tmp/test.hosts '~a-fe' --list
>    No host matched

**Comment by sivel** [comment]
See https://github.com/ansible/ansible/issues/8614

**Comment by mpdehaan** [comment]
Closing per above.

Thanks!
