### ISSUE TITLE
Enhancement requests to the template module

### ISSUE THREAD

**Issue by aedwardstx** [ansible/ansible#9466]
I am working to use Ansible as a configuration management platform for Cisco networking gear.  It would be handy to be able to compile a template without the need to SSH to the local or remote host -- simply write the compiled template to the specified path on the local machine for later use.  

It would also be nice to be able to compile a template, not write it to a file at all, and just return the text as a variable to be used elsewhere in the playbook. For example, if you wanted to compare a router's running configuration (registered from raw commands) to a compiled template (registered from template) with a custom comparison module that takes the two variables as arguments.

**Comment by sivel** [comment]
Both of these things are doable. Look at running the template module with `local_action` to perform the task locally without needing SSH (also you could target `hosts: localhost` with `connection: local`)

To get the results I a template into a var look at the "template" lookup plugin:  http://docs.ansible.com/playbooks_lookups.html

**Comment by sivel** [comment]
Also, issues for modules should be added for the respective repo: https://github.com/ansible/ansible-modules-core

**Comment by mpdehaan** [comment]
yeah, please stop by ansible-devel for a discussion on this one.

It would be better to use the APIs and not the template module, as Cisco gear is very much non-Linuxey.

I can share some refefences to other things done with JunOS, Arista, and Cumulus as well at that time.
