### ISSUE TITLE
Ansible unable to connect to any servers after OpenSSH update

### ISSUE THREAD

**Issue by d3solutions** [ansible/ansible#9478]
Hi,

We're running CentOS 6.6 and just ran yum update, which included these libs:
openssh-5.3p1-104.el6.x86_64
openssh-clients-5.3p1-104.el6.x86_64

We're now unable to connect to any of our servers via ansible.  All ansible playbooks die with this message (IP's and usernames changed):

debug3: muxserver_listen: temporary control path /home/username/.ansible/cp/ansible-ssh-192.192.192.192-22-username.IyQtfRZAXUUasdA4ic
muxserver_listen bind(): Operation not permitted

We're still able to ssh directly into our servers (without ansible) with no issue.

Any suggestions?

**Comment by jimsmith** [comment]
What troubleshooting steps have you done ?
What does debugging -vvvv using ansible show ?

UPDATE:
http://superuser.com/questions/686066/muxserver-listen-bind-no-such-file-or-directory-using-todo-txt-over-ssh-on

Let me know if this is any use, as I am interested in this issue as I was about to yum update EC2 estate but holding off now.

**Comment by d3solutions** [comment]
@jimsmith thanks for looking into this!  It's causing a big problem for us
and I'm sure we're not alone.

I also found this thread, which may be related (I didn't see an associated
bug report)
https://groups.google.com/forum/#!msg/ansible-project/QUdxNK1zEH0/rQKnO827FUgJ

Troubleshooting steps

1) Restored my server vm to a previous snapshot
2) Confirmed that ansible was working normally
3) Ran "yum update openssh"
4) This installed the following RPM's:

openssh-5.3p1-104.el6.x86_64.rpm
openssh-clients-5.3p1-104.el6.x86_64.rpm
openssh-server-5.3p1-104.el6.x86_64.rpm

5) Ran ansible again
6) Confirmed that ansible stopped working as a result of the openssh updates

---

Debugging -vvvv output below

GATHERING FACTS

---

<192.192.192.192> ESTABLISH CONNECTION FOR USER: username

<192.192.192.192> REMOTE_MODULE setup

<192.192.192.192> EXEC ['ssh', '-C', '-tt', '-vvv', '-o',
'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o',
'ControlPath=/home/username/.ansible/cp/ansible-ssh-%h-%p-%r', '-o',
'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o',
'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey',
'-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10',
'192.192.192.192', "/bin/sh -c 'mkdir -p
$HOME/.ansible/tmp/ansible-tmp-1415135400.46-207371963589222 && chmod a+rx
$HOME/.ansible/tmp/ansible-tmp-1415135400.46-207371963589222 && echo
$HOME/.ansible/tmp/ansible-tmp-1415135400.46-207371963589222'"]

fatal: [dev1] => SSH encountered an unknown error. The output was:

OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013

debug1: Reading configuration data /home/username/.ssh/config

debug1: Reading configuration data /etc/ssh/ssh_config

debug1: Applying options for *

debug1: auto-mux: Trying existing master

debug1: Control socket
"/home/username/.ansible/cp/ansible-ssh-192.192.192.192-22-username" does
not exist

debug2: ssh_connect: needpriv 0

debug1: Connecting to 192.192.192.192 [192.192.192.192] port 22.

debug2: fd 3 setting O_NONBLOCK

debug1: fd 3 clearing O_NONBLOCK

debug1: Connection established.

debug3: timeout: 10000 ms remain after connect

debug1: identity file /home/username/.ssh/identity type -1

debug1: identity file /home/username/.ssh/identity-cert type -1

debug3: Not a RSA1 key file /home/username/.ssh/id_rsa.

debug2: key_type_from_name: unknown key type '-----BEGIN'

debug3: key_read: missing keytype

debug3: key_read: missing whitespace

debug3: key_read: missing whitespace

debug3: key_read: missing whitespace

debug3: key_read: missing whitespace

debug3: key_read: missing whitespace

debug3: key_read: missing whitespace

debug3: key_read: missing whitespace

debug3: key_read: missing whitespace

debug3: key_read: missing whitespace

debug3: key_read: missing whitespace

debug3: key_read: missing whitespace

debug3: key_read: missing whitespace

debug3: key_read: missing whitespace

debug2: key_type_from_name: unknown key type '-----END'

debug3: key_read: missing keytype

debug1: identity file /home/username/.ssh/id_rsa type 1

debug1: identity file /home/username/.ssh/id_rsa-cert type -1

debug1: identity file /home/username/.ssh/id_dsa type -1

debug1: identity file /home/username/.ssh/id_dsa-cert type -1

debug1: identity file /home/username/.ssh/id_ecdsa type -1

debug1: identity file /home/username/.ssh/id_ecdsa-cert type -1

debug1: Remote protocol version 2.0, remote software version OpenSSH_5.3

debug1: match: OpenSSH_5.3 pat OpenSSH*

debug1: Enabling compatibility mode for protocol 2.0

debug1: Local version string SSH-2.0-OpenSSH_5.3

debug2: fd 3 setting O_NONBLOCK

debug1: SSH2_MSG_KEXINIT sent

debug3: Wrote 960 bytes for a total of 981

debug1: SSH2_MSG_KEXINIT received

debug2: kex_parse_kexinit:
diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1

debug2: kex_parse_kexinit: ssh-rsa-cert-v01@openssh.com,
ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,
ssh-dss-cert-v00@openssh.com,ssh-rsa,ssh-dss

debug2: kex_parse_kexinit:
aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,
rijndael-cbc@lysator.liu.se

debug2: kex_parse_kexinit:
aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,
rijndael-cbc@lysator.liu.se

debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,umac-64@openssh.com
,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com
,hmac-sha1-96,hmac-md5-96

debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,umac-64@openssh.com
,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com
,hmac-sha1-96,hmac-md5-96

debug2: kex_parse_kexinit: zlib@openssh.com,zlib,none

debug2: kex_parse_kexinit: zlib@openssh.com,zlib,none

debug2: kex_parse_kexinit:

debug2: kex_parse_kexinit:

debug2: kex_parse_kexinit: first_kex_follows 0

debug2: kex_parse_kexinit: reserved 0

debug2: kex_parse_kexinit:
diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1

debug2: kex_parse_kexinit: ssh-rsa,ssh-dss

debug2: kex_parse_kexinit:
aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,
rijndael-cbc@lysator.liu.se

debug2: kex_parse_kexinit:
aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,
rijndael-cbc@lysator.liu.se

debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,umac-64@openssh.com
,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com
,hmac-sha1-96,hmac-md5-96

debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,umac-64@openssh.com
,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com
,hmac-sha1-96,hmac-md5-96

debug2: kex_parse_kexinit: none,zlib@openssh.com

debug2: kex_parse_kexinit: none,zlib@openssh.com

debug2: kex_parse_kexinit:

debug2: kex_parse_kexinit:

debug2: kex_parse_kexinit: first_kex_follows 0

debug2: kex_parse_kexinit: reserved 0

debug2: mac_setup: found hmac-md5

debug1: kex: server->client aes128-ctr hmac-md5 zlib@openssh.com

debug2: mac_setup: found hmac-md5

debug1: kex: client->server aes128-ctr hmac-md5 zlib@openssh.com

debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(1024<1024<8192) sent

debug1: expecting SSH2_MSG_KEX_DH_GEX_GROUP

debug3: Wrote 24 bytes for a total of 1005

debug2: dh_gen_key: priv key bits set: 131/256

debug2: bits set: 503/1024

debug1: SSH2_MSG_KEX_DH_GEX_INIT sent

debug1: expecting SSH2_MSG_KEX_DH_GEX_REPLY

debug3: Wrote 144 bytes for a total of 1149

debug3: check_host_in_hostfile: host 192.192.192.192 filename
/home/username/.ssh/known_hosts

debug3: check_host_in_hostfile: host 192.192.192.192 filename
/home/username/.ssh/known_hosts

debug3: check_host_in_hostfile: match line 84

debug1: Host '192.192.192.192' is known and matches the RSA host key.

debug1: Found key in /home/username/.ssh/known_hosts:84

debug2: bits set: 512/1024

debug1: ssh_rsa_verify: signature correct

debug2: kex_derive_keys

debug2: set_newkeys: mode 1

debug1: SSH2_MSG_NEWKEYS sent

debug1: expecting SSH2_MSG_NEWKEYS

debug3: Wrote 16 bytes for a total of 1165

debug2: set_newkeys: mode 0

debug1: SSH2_MSG_NEWKEYS received

debug1: SSH2_MSG_SERVICE_REQUEST sent

debug3: Wrote 48 bytes for a total of 1213

debug2: service_accept: ssh-userauth

debug1: SSH2_MSG_SERVICE_ACCEPT received

debug2: key: /home/username/.ssh/identity ((nil))

debug2: key: /home/username/.ssh/id_rsa (0x7fc48d2f8020)

debug2: key: /home/username/.ssh/id_dsa ((nil))

debug2: key: /home/username/.ssh/id_ecdsa ((nil))

debug3: Wrote 64 bytes for a total of 1277

debug1: Authentications that can continue:
publickey,gssapi-keyex,gssapi-with-mic,password

debug3: start over, passed a different list
publickey,gssapi-keyex,gssapi-with-mic,password

debug3: preferred gssapi-with-mic,gssapi-keyex,hostbased,publickey

debug3: authmethod_lookup gssapi-with-mic

debug3: remaining preferred: gssapi-keyex,hostbased,publickey

debug3: authmethod_is_enabled gssapi-with-mic

debug1: Next authentication method: gssapi-with-mic

debug3: Trying to reverse map address 192.192.192.192.

debug1: Unspecified GSS failure.  Minor code may provide more information

Cannot determine realm for numeric host address

debug1: Unspecified GSS failure.  Minor code may provide more information

Cannot determine realm for numeric host address

debug1: Unspecified GSS failure.  Minor code may provide more information

debug1: Unspecified GSS failure.  Minor code may provide more information

Cannot determine realm for numeric host address

debug2: we did not send a packet, disable method

debug3: authmethod_lookup gssapi-keyex

debug3: remaining preferred: hostbased,publickey

debug3: authmethod_is_enabled gssapi-keyex

debug1: Next authentication method: gssapi-keyex

debug1: No valid Key exchange context

debug2: we did not send a packet, disable method

debug3: authmethod_lookup publickey

debug3: remaining preferred: ,publickey

debug3: authmethod_is_enabled publickey

debug1: Next authentication method: publickey

debug1: Trying private key: /home/username/.ssh/identity

debug3: no such identity: /home/username/.ssh/identity

debug1: Offering public key: /home/username/.ssh/id_rsa

debug3: send_pubkey_test

debug2: we sent a publickey packet, wait for reply

debug3: Wrote 240 bytes for a total of 1517

debug1: Server accepts key: pkalg ssh-rsa blen 149

debug2: input_userauth_pk_ok: SHA1 fp
e4:22:fb:99:49:03:1b:d0:29:d7:4c:b3:dd:10:9d:33:86:17:f5:a6

debug3: sign_and_send_pubkey: RSA
e4:22:fb:99:49:03:1b:d0:29:d7:4c:b3:dd:10:9d:33:86:17:f5:a6

debug1: read PEM private key done: type RSA

debug3: Wrote 384 bytes for a total of 1901

debug1: Enabling compression at level 6.

debug1: Authentication succeeded (publickey).

debug1: setting up multiplex master socket

debug3: muxserver_listen: temporary control path
/home/username/.ansible/cp/ansible-ssh-192.192.192.192-22-username.DRIYXKg7M1MYnTQf

muxserver_listen bind(): Operation not permitted

**Comment by ienliven** [comment]
SELinux maybe? not allowing ssh client to bind a port.

**Comment by d3solutions** [comment]
@jimsmith yes, that solved the problem!

in /etc/ansible/ansible.cfg I had this line:
#ssh_args = -o ControlMaster=auto -o ControlPersist=60s

It looks like it's commented out, which is part of what confused me, but based on my tests these are the default values, even if the line is commented out.

I changed that line to:
ssh_args = 

and everything seems to be working now (based on some quick tests).

Thanks for the help!

**Comment by onurbrc** [comment]
Hi Everyone, hi @jimsmith,

I'm having the same issue with openssh.
I've tried the ssh_args = (blank) and with these parameters : 
ssh_args = -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=~/.ssh/%h-%p-%r

I'm trying to run : 

**ansible-playbook ping.yml -c paramiko -vvvv**

and it gives me the output:


$ ansible-playbook ping.yml -vvvv
Using /etc/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.6/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: ping.yml *************************************************************
1 plays in ping.yml

PLAY [Test01] ******************************************************************

TASK [Collecting Bigip_facts] **************************************************
task path: /home/ansible/ping.yml:7
Using module file /usr/lib/python2.6/site-packages/ansible/modules/extras/network/f5/bigip_facts.py
<F5-03> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO F5-03
Using module file /usr/lib/python2.6/site-packages/ansible/modules/extras/network/f5/bigip_facts.py
<F5-04> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO F5-04
Using module file /usr/lib/python2.6/site-packages/ansible/modules/extras/network/f5/bigip_facts.py
<F5-02> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO F5-02
Using module file /usr/lib/python2.6/site-packages/ansible/modules/extras/network/f5/bigip_facts.py
<F5-01> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO F5-01
fatal: [F5-03]: UNREACHABLE! => {
    "changed": false,
    **"msg": "[Errno -2] Name or service not known",**
    "unreachable": true
}
fatal: [F5-01]: UNREACHABLE! => {
    "changed": false,
    **"msg": "[Errno -2] Name or service not known",**
    "unreachable": true
}
fatal: [F5-04]: UNREACHABLE! => {
    "changed": false,
    **"msg": "[Errno -2] Name or service not known",**
    "unreachable": true
}
fatal: [F5-02]: UNREACHABLE! => {
    "changed": false,
    **"msg": "[Errno -2] Name or service not known",**
    "unreachable": true
}
        to retry, use: --limit @/home/ansible/ping.retry

PLAY RECAP *********************************************************************
F5-01                      : ok=0    changed=0    unreachable=1    failed=0
F5-02                      : ok=0    changed=0    unreachable=1    failed=0
F5-03                      : ok=0    changed=0    unreachable=1    failed=0
F5-04                      : ok=0    changed=0    unreachable=1    failed=0

And I've tried with **-c paramiko**, it gives the output : 

$ ansible-playbook ping.yml -vvvv
Using /etc/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.6/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: ping.yml *************************************************************
1 plays in ping.yml

PLAY [Test01] ******************************************************************

TASK [Collecting Bigip_facts] **************************************************
task path: /home/ansible/ping.yml:7
Using module file /usr/lib/python2.6/site-packages/ansible/modules/extras/network/f5/bigip_facts.py
Using module file /usr/lib/python2.6/site-packages/ansible/modules/extras/network/f5/bigip_facts.py
Using module file /usr/lib/python2.6/site-packages/ansible/modules/extras/network/f5/bigip_facts.py
<F5-04> ESTABLISH SSH CONNECTION FOR USER: root
<F5-02> ESTABLISH SSH CONNECTION FOR USER: root
<F5-03> ESTABLISH SSH CONNECTION FOR USER: root
<F5-04> SSH: EXEC ssh -vvv -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o 'ControlPath=~/.ssh/%h-%p-%r' -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 F5-04 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1488786734.05-208200452390733 `" && echo ansible-tmp-1488786734.05-208200452390733="` echo ~/.ansible/tmp/ansible-tmp-1488786734.05-208200452390733 `" ) && sleep 0'"'"''
Using module file /usr/lib/python2.6/site-packages/ansible/modules/extras/network/f5/bigip_facts.py
<F5-01> ESTABLISH SSH CONNECTION FOR USER: root
<F5-02> SSH: EXEC ssh -vvv -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o 'ControlPath=~/.ssh/%h-%p-%r' -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 F5-02 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1488786734.05-186836740221344 `" && echo ansible-tmp-1488786734.05-186836740221344="` echo ~/.ansible/tmp/ansible-tmp-1488786734.05-186836740221344 `" ) && sleep 0'"'"''
<F5-03> SSH: EXEC ssh -vvv -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o 'ControlPath=~/.ssh/%h-%p-%r' -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 F5-03 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1488786734.05-159991349415960 `" && echo ansible-tmp-1488786734.05-159991349415960="` echo ~/.ansible/tmp/ansible-tmp-1488786734.05-159991349415960 `" ) && sleep 0'"'"''
<F5-01> SSH: EXEC ssh -vvv -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o 'ControlPath=~/.ssh/%h-%p-%r' -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 F5-01 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1488786734.05-58082822612973 `" && echo ansible-tmp-1488786734.05-58082822612973="` echo ~/.ansible/tmp/ansible-tmp-1488786734.05-58082822612973 `" ) && sleep 0'"'"''
fatal: [F5-04]: UNREACHABLE! => {
    "changed": false,
    **"msg": "Failed to connect to the host via ssh: OpenSSH_5.3p1, OpenSSL 1.0.1e-fips** 11 Feb 2013\ndebug1: Reading configuration data /home/ansible/.ssh/config\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/home/ansible/.ssh/F5-04-22-root\" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\nssh: Could not resolve hostname F5-04: Name or service not known\r\n",
    "unreachable": true
}
fatal: [F5-03]: UNREACHABLE! => {
    "changed": false,
    **"msg": "Failed to connect to the host via ssh: OpenSSH_5.3p1, OpenSSL 1.0.1e-fips** 11 Feb 2013\ndebug1: Reading configuration data /home/ansible/.ssh/config\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/home/ansible/.ssh/F5-03-22-root\" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\nssh: Could not resolve hostname F5-03: Name or service not known\r\n",
    "unreachable": true
}
fatal: [F5-02]: UNREACHABLE! => {
    "changed": false,
    **"msg": "Failed to connect to the host via ssh: OpenSSH_5.3p1, OpenSSL 1.0.1e-fips** 11 Feb 2013\ndebug1: Reading configuration data /home/ansible/.ssh/config\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/home/ansible/.ssh/F5-02-22-root\" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\nssh: Could not resolve hostname F5-02: Name or service not known\r\n",
    "unreachable": true
}
fatal: [F5-01]: UNREACHABLE! => {
    "changed": false,
    **"msg": "Failed to connect to the host via ssh: OpenSSH_5.3p1, OpenSSL 1.0.1e-fips** 11 Feb 2013\ndebug1: Reading configuration data /home/ansible/.ssh/config\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/home/ansible/.ssh/F5-01-22-root\" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\nssh: Could not resolve hostname F5-01: Name or service not known\r\n",
    "unreachable": true
}
        to retry, use: --limit @/home/ansible/ping.retry

PLAY RECAP *********************************************************************
F5-01                      : ok=0    changed=0    unreachable=1    failed=0
F5-02                      : ok=0    changed=0    unreachable=1    failed=0
F5-03                      : ok=0    changed=0    unreachable=1    failed=0
F5-04                      : ok=0    changed=0    unreachable=1    failed=0

I have the last update of the openssh indicated above. After the ssh-copy-id procedure, I can connect my ansible machine to my clients using just ssh root@F5-[01] without password.

I'm using ansible 2.2 in a RedHat 6
I have installed Python 2.6 and Python3

Could you give any suggestions? Thank you in advance.
