### ISSUE TITLE
Ansible 1.7 - delegate_to is ignored and tasks are run on each inventory host?

### ISSUE THREAD

**Issue by laymonk** [ansible/ansible#9488]
Hi,

I have 5 hosts matched in an inventory file, but want to run a given task just on one of them .. but however I set the host to be delegated to, the task gets run against all hosts  .. 

The surprise is that the task is executed for each of the hosts and output shows the task is applied to each host and is actually run and results in changed status .. 

Even hard-coding the inventory_hostname (avoiding the use of a variable) still results in task being run on each host .. and a resultant changed status per host.

I have seen other issues raised about delegate_to, but none of them seen to be exactly what I am seeing .. for instance: [# 9405](https://github.com/ansible/ansible/issues/9405), [# 8705](https://github.com/ansible/ansible/issues/8705)

Perhaps I am missing something?  Or delegate_to is really not working ?

____________ example______________
## Inventory

hosta
hostb
hostc
hostd
hoste
etc
## vars_file

migrate_host:  hosta.{{subdomain}}
# Playbook:

tasks:
- debug: msg="Migrate host is {{ migrate_host }}"
- name:  run only on migrate host
  shell: blah blah
  delegate_to: "{{ migrate_host }}" 

---

**Comment by michalgasek** [comment]
Have you tried adding `run_once: true` ? http://docs.ansible.com/playbooks_delegation.html#run-once
I think this might be what you want to achieve here.

**Comment by laymonk** [comment]
Michalgasek, thanks for the suggestion .. and yes, that would be the easy way out and would only run on the first inventory host.  I could just as well have used groups['servers'][0] which would work more or less like run_once.

In any case, while run_once is available on my local workstation, the version of ansible we run on our CI servers is earlier than when run_once was introduced.

But I wanted to randomize how a node was selected, and I still have not figured out why I couldn't get it to work ..

**Comment by bcoca** [comment]
I think you misunderstood how delegate_to works, it will run the task on the delegated host PER host in the play, not just once. As others have mentioned this is what run_once is for, since it is not available in your version there you can use:

```
when: inventory_hostname == play_hosts[0]
```

which will run the tasks for the first host in the play.

I'm closing this because it is not as much a bug as a question on how to use ansible, you can post these to IRC or to the ansible-project@googlegroups.com list
