### ISSUE TITLE
bzr: ERROR: exceptions.TypeError: readline() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#9493]
##### Issue Type:

Bug Report
##### Ansible Version:

$ ansible --version
ansible 1.8 (devel cbad867f24) last updated 2014/11/05 16:35:15 (GMT -500)
  lib/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/07 14:28:03 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/07 14:28:06 (GMT -500)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/07 14:28:11 (GMT -500)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/07 14:28:15 (GMT -500)
  configured module search path = None
##### Environment:

Running from OSX 10.9.5 with Python 2.7.5

Managing Ubuntu 12.04.5 LTS with Python 2.7.3
##### Summary:

bzr play with stacked=yes results in bzr: ERROR: exceptions.TypeError: readline() takes exactly 1 argument (2 given)
##### Steps To Reproduce:
- name: bzr branch --stacked lp:bzrtools
  bzr: name=lp:bzrtools dest=~"{{ansible_user}}"/.bazaar/plugins/bzrtools stacked=yes
##### Expected Results:

Update the bzr branch located at ~"{{ansible_user}}"/.bazaar/plugins/bzrtools
##### Actual Results:

bzr: ERROR: exceptions.TypeError: readline() takes exactly 1 argument (2 given)

To be honest I don't know if this error is coming from the the ansible bzr module or the bzr program itself. I'm still debugging the problem but I'm opening this issue in case others run into the problem.

**Comment by basictheprogram** [comment]
What's odd is executing the command by hand works.  Ansible throws this out stderr:

failed: [ansible-test.mydomain.com] => {"cmd": "/usr/bin/bzr branch --stacked lp:bzrtools /home/ansible/.bazaar/plugins/bzrtools", "failed": true, "rc": 4}
stderr: bzr: ERROR: exceptions.TypeError: readline() takes exactly 1 argument (2 given)

As the ansible user, issuing the following command at the shell things work as expected.

$ /usr/bin/bzr branch --stacked lp:bzrtools /home/ansible/.bazaar/plugins/bzrtools/
<snip the download of files, checksum, etc.>
$ echo $?
0

**Comment by mpdehaan** [comment]
Hi!

As part of our recent module restructing, modules have been moved to two different repos.   

These are:

https://github.com/ansible/ansible-modules-core
https://github.com/ansible/ansible-modules-extras

Whether a module is in core or extras can be found by consulting the documentation page for the module, where this will be noted at the bottom of the documentation page.

If you can please reopen this ticket on one of the two trackers above, we would appreciate it.

Thank you very much!
