### ISSUE TITLE
SSH Private Key stat issue

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#9507]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.8 (devel cbad867f24) last updated 2014/11/05 15:11:38 (GMT -500)
```
##### Environment:

Control: Mac OS, virtualenv, python 2.7.5

Target: N/A
##### Summary:

In #8020 functionality was added to error if the private key is group or world readable.

This has unfortunately broken things for us.

Our inventory script, grabs private keys from our CMDB, loads them into ssh-agent and then deletes them from disk.  OpenSSH allows this, as it doesn't need the physical file since the key is loaded into ssh-agent.

Unfortunately, since we no don't keep the key on disk, the stat fails and ansible fails to continue running.

I am thinking we could just add a try/except and if the stat fails we could allow it to continue instead of raising an exception.
##### Steps To Reproduce:
1. `eval $(ssh-agent)`
2. `ssh-add /path/to/private/key`
3. `rm /path/to/private/key`
4. Run ansible with `--private-key` pointing at the now non-existent `/path/to/private/key`
##### Expected Results:

Ansible runs as it did previously
##### Actual Results:

```
  File "/Users/matt/python_venvs/ansibledev/ansible/lib/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/Users/matt/python_venvs/ansibledev/ansible/lib/ansible/runner/__init__.py", line 755, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/Users/matt/python_venvs/ansibledev/ansible/lib/ansible/runner/__init__.py", line 918, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file)
  File "/Users/matt/python_venvs/ansibledev/ansible/lib/ansible/runner/connection.py", line 39, in connect
    st = os.stat(private_key_file)
OSError: [Errno 2] No such file or directory: '/var/folders/p3/b_15nft95md8kpmv32twplhr0000gn/T/tmpZLcufI'
```

**Comment by bcoca** [comment]
should be fixed by the PR just merged above
