### ISSUE TITLE
Ansible 1.8 (devel) shell/command & checkmode produce conflicting results

### ISSUE THREAD

**Issue by jfchevrette** [ansible/ansible#9508]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible-playbook 1.8 (devel 394ebe7947) last updated 2014/11/06 12:40:23 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 63e81cfc2e) last updated 2014/11/03 11:06:51 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD a0df36c6ab) last updated 2014/11/03 11:06:53 (GMT -400)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/11/03 11:06:54 (GMT -400)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/11/03 11:06:56 (GMT -400)
  configured module search path = None
```
##### Environment:

OS X 10.10 client
CentOS 6.6 server/hosts
##### Summary:

When running a command or shell task with --check it procuded two conflicting results 
##### Steps To Reproduce:
1. Create a playbook with a command or shell action.
2. Run the playbook with --check
##### Actual Results:

```
TASK: [some task] *************************************************************
skipping: [s001]
ok: [s001] => {"msg": "check mode not supported for command", "skipped": true}
skipping: [s002]
ok: [s002] => {"msg": "check mode not supported for command", "skipped": true}
```
##### Expected Results:

```
TASK: [some task] *************************************************************
skipping: [s001]
skipping: [s002]
```

**Comment by bcoca** [comment]
command and shell do not support check mode, all modules that do not support check mode will return skipped

**Comment by jfchevrette** [comment]
My bad I inverted the expected/actual results when I opened the issue. I fixed it in the original .

Basically, each shell/command task will return two lines, a Skipped and a OK line. I believe it should only return the Skipped line for consistency with other modules especially when you parse playbook runs (as json or via a plugin)

**Comment by bcoca** [comment]
so it returns 'skipping', which it does, but that is OK as it is in check mode. Not sure what you want to fix.

**Comment by bcoca** [comment]
for example, this is what i get from running hostname under check mode:

```
skipping: [localhost]
ok: [localhost] => {"changed": false, "msg": "remote module does not support check mode", "skipped": true}
```

**Comment by jfchevrette** [comment]
IMO this would be more consistent with tasks that are skipped because their when: conditions are false...

```
skipping: [localhost] => {"changed": false, "msg": "remote module does not support check mode", "skipped": true}
```

**Comment by drzraf** [comment]
when shell or command is given a "when" clause, then the result of the "when" evaluation should definitely be part of the output in --check mode

**Comment by SupremeGit** [comment]
So, a year and a half later, and people are still playing russian roulette. 

Sp. people are expected to run ansible scripts on production machines, when the check mode does not even reliably tell you which tasks will run?

Unbelievable.

**Comment by bcoca** [comment]
Actually, this has been fixed already

```
- hosts: localhost
  gather_facts: false
  tasks:
    - hostname: name=lola
      when: false
```

when run:

```
ansible-playbook play.yml -vvvvv --check
```

results:

```
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional check failed",
    "skipped": true
}
 _
```

**Comment by bcoca** [comment]
@SupremeGit  before assuming the 'unbelivable' on tickets, please see if the issues still apply, this is the 3rd such case in which you leave very strong comments on things that were already addressed.

**Comment by SupremeGit** [comment]
I searched for this info. I did not find it. instead, i ended up here, where other people had noted the issue, and it appeared their valid concerns had been ignored.

When are people going to understand, that if it is not documented, it may as well not be implemented.
