### ISSUE TITLE
ansible -u does not override username

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#9517]
##### Issue Type:

Bug Report
##### Ansible Version:

Tested with:

ansible 1.7.2
##### Environment:

Ubuntu 14.04.1 server amd64
##### Summary:

`ansible -u <username>` does not override ansible_ssh_user set in `group_vars/all` or in inventory.
##### Steps To Reproduce:

```
$ cat hosts.local
host1.ws.nsrc.org ansible_ssh_user=root

$ ansible host1.ws.nsrc.org -u foo -vvvv -m setup
<host1.ws.nsrc.org> ESTABLISH CONNECTION FOR USER: root
```
##### Expected Results:

That the command-line `-u` option would override the ansible_ssh_user - or that the documentation would make it clear that `-u` does _not_ have any effect if ansible_ssh_user is set anywhere for that host.

The manual page just says:

```
       -u USERNAME, --user=USERNAME
           Use this remote USERNAME instead of the current user.
```
##### Actual Results:

See above

**Comment by bcoca** [comment]
Actually, this is expected, to override the ansible_ssh_user from the command line you need to pass it as an extra var

```
-e 'ansible_ssh_user=USERNAME'
```

**Comment by candlerb** [comment]
1. Expected but not documented?
2. Could not the `-u` option set the ansible_ssh_user variable instead of whatever it currently does? Or are there distinct use cases for `-u` and `-e 'ansible_ssh_user=USERNAME'`

**Comment by bcoca** [comment]
1.  might not be as prominent as it should, any suggestions?
2.  This behavior has been consistent for the life of ansible, changing it now will probably break existing workflows.

**Comment by candlerb** [comment]
`docs/man/man1/ansible.1` currently says:

```
\fB\-u\fR \fIUSERNAME\fR, \fB\-\-user=\fR\fIUSERNAME\fR
.RS 4
Use this remote
\fIUSERNAME\fR
instead of the current user\&.
```

`docs/man/man1/ansible-playbook.1` currently says:

```
\fB\-u\fR \fIUSERNAME\fR, \fB\-\-user=\fR\fIUSERNAME\fR
.RS 4
Use this remote user name on playbook steps that do not indicate a user name to run as\&.
```

Assuming the `-u` flag works the same on both commands, I suggest they both say something along these lines:

"Use this remote user name instead of the current user on tasks that do not indicate a user name to run as. If the variable ansible_ssh_user is set, this option does _not_ override it. To do that you should use "-e 'ansible_ssh_user=USERNAME'"

**Comment by candlerb** [comment]
Oops, slight problem with the suggested documentation fix: the `ansible` command does not implement the `-e` flag at all. Only `ansible-playbook` has this.

Therefore, if you inventory contains

```
foo.example.com ansible_username=bar
```

(or the same setting in host_vars or group_vars) then there appears to be no way to run `ansible` as a different user, since the `-u` option does not override this setting.
