### ISSUE TITLE
facts.d doesn't accept YAML format facts variables contrary to documentation

### ISSUE THREAD

**Issue by dk-dkopen** [ansible/ansible#9519]
Issue Type: Bug Report / Documentation discrepancy / Missing feature

Ansible Version: 1.5.4

Environment: Linux - Ubuntu 14.04 - n/a - not relevant really

Summary:

Documentation http://docs.ansible.com/playbooks_variables.html#local-facts-facts-d claims that facts.d support YAML format, which is not the case.
( elsewhere - http://docs.ansible.com/setup_module.html - documentation correctly claims json and ini only )
This is evident from module_utils/facts.py - get_local_facts() code contains no attempt to load YAML.
Only json and ini formats are attempted.
https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts.py#L192-L202

Steps To Reproduce: Add to facts.d a file in YAML format - even including "---" as the first line.

Expected Results: File gets loaded into facts variables

Actual Results: has value "error loading fact - please check content"

Suggested solutions -
- implement YAML support - e.g. if first line is "---", attempt parsing YAML
- if not possible, update documentation accordingly

**Comment by juliedavila** [comment]
Have you tried with the latest version of Ansible?

**Comment by bcoca** [comment]
closed by #9548 

we can look at this as a future feature if we implement error free yaml module loading to deal with systems that lack that python module.

**Comment by dk-dkopen** [comment]
Good, at least it won't lead people to trying YAML.
Agreed - implementation can be treated separately as a feature.
Thanks!

**Comment by jjaone** [comment]
I have a problem loading this test.fact file in my playbook:
```
#!/bin/bash
cat <<EOF
{
  "devenv_enabled": "true"
  "mdbenv_enabled": "true"
  "dataenv_enabled": "true"
  "mmtenv_enabled": "true"
}
EOF
```
but the play complains:
```
ok: [myhost] => {
    "ansible_local": {
        "test": "error loading fact - please check content
```
Is the issue related to this?

**Comment by tagwint** [comment]
Did you make sure your test.fact set executable permission set?
I had "error loading fact - please check content" too before I did.
