### ISSUE TITLE
vagrant ansible issue " ansible provisioner: * The following settings shouldn't exist: hosts"

### ISSUE THREAD

**Issue by waleedsaud** [ansible/ansible#9521]
INFO global: Vagrant version: 1.6.5
INFO global: Ruby version: 2.0.0
INFO global: RubyGems version: 2.0.14
INFO global: VAGRANT_EXECUTABLE="/opt/vagrant/bin/../embedded/gems/gems/vagrant-1.6.5/bin/vagrant"
INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/opt/vagrant/bin/../embedded"
INFO global: VAGRANT_INSTALLER_VERSION="2"
INFO global: VAGRANT_DETECTED_OS="Linux"
INFO global: VAGRANT_INSTALLER_ENV="1"
INFO global: VAGRANT_INTERNAL_BUNDLERIZED="1"
INFO global: VAGRANT_LOG="debug"
INFO global: Plugins:
INFO global: - bundler = 1.6.6
INFO global: - mime-types = 1.25.1
INFO global: - rdoc = 4.0.0
INFO global: - rest-client = 1.6.8
INFO global: - vagrant-login = 1.0.1
INFO global: - vagrant-share = 1.1.1
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/arch/plugin.rb
INFO manager: Registered plugin: Arch guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/suse/plugin.rb
INFO manager: Registered plugin: SUSE guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/fedora/plugin.rb
INFO manager: Registered plugin: Fedora guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/windows/plugin.rb
INFO manager: Registered plugin: Windows guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/funtoo/plugin.rb
INFO manager: Registered plugin: Funtoo guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/omnios/plugin.rb
INFO manager: Registered plugin: OmniOS guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/smartos/plugin.rb
INFO manager: Registered plugin: SmartOS guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/netbsd/plugin.rb
INFO manager: Registered plugin: NetBSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/pld/plugin.rb
INFO manager: Registered plugin: PLD Linux guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/mint/plugin.rb
INFO manager: Registered plugin: Mint guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/nixos/plugin.rb
INFO manager: Registered plugin: NixOS guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/esxi/plugin.rb
INFO manager: Registered plugin: ESXi guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/redhat/plugin.rb
INFO manager: Registered plugin: RedHat guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/solaris/plugin.rb
INFO manager: Registered plugin: Solaris guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/gentoo/plugin.rb
INFO manager: Registered plugin: Gentoo guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/debian/plugin.rb
INFO manager: Registered plugin: Debian guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/ubuntu/plugin.rb
INFO manager: Registered plugin: Ubuntu guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/coreos/plugin.rb
INFO manager: Registered plugin: CoreOS guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/darwin/plugin.rb
INFO manager: Registered plugin: Darwin guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/tinycore/plugin.rb
INFO manager: Registered plugin: TinyCore Linux guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/freebsd/plugin.rb
INFO manager: Registered plugin: FreeBSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/linux/plugin.rb
INFO manager: Registered plugin: Linux guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/openbsd/plugin.rb
INFO manager: Registered plugin: OpenBSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/guests/solaris11/plugin.rb
INFO manager: Registered plugin: Solaris 11 guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/kernel_v2/plugin.rb
INFO manager: Registered plugin: kernel
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/provisioners/ansible/plugin.rb
INFO manager: Registered plugin: ansible
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/provisioners/puppet/plugin.rb
INFO manager: Registered plugin: puppet
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/provisioners/chef/plugin.rb
INFO manager: Registered plugin: chef
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/provisioners/salt/plugin.rb
INFO manager: Registered plugin: salt
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/provisioners/file/plugin.rb
INFO manager: Registered plugin: file
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/provisioners/docker/plugin.rb
INFO manager: Registered plugin: docker
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/provisioners/cfengine/plugin.rb
INFO manager: Registered plugin: CFEngine Provisioner
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/provisioners/shell/plugin.rb
INFO manager: Registered plugin: shell
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/communicators/winrm/plugin.rb
INFO manager: Registered plugin: winrm communicator
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/communicators/ssh/plugin.rb
INFO manager: Registered plugin: ssh communicator
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/kernel_v1/plugin.rb
INFO manager: Registered plugin: kernel
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/destroy/plugin.rb
INFO manager: Registered plugin: destroy command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/status/plugin.rb
INFO manager: Registered plugin: status command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/suspend/plugin.rb
INFO manager: Registered plugin: suspend command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/up/plugin.rb
INFO manager: Registered plugin: up command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/box/plugin.rb
INFO manager: Registered plugin: box command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/reload/plugin.rb
INFO manager: Registered plugin: reload command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/resume/plugin.rb
INFO manager: Registered plugin: resume command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/help/plugin.rb
INFO manager: Registered plugin: help command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/ssh_config/plugin.rb
INFO manager: Registered plugin: ssh-config command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/rdp/plugin.rb
INFO manager: Registered plugin: rdp command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/init/plugin.rb
INFO manager: Registered plugin: init command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/halt/plugin.rb
INFO manager: Registered plugin: halt command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/plugin/plugin.rb
INFO manager: Registered plugin: plugin command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/list-commands/plugin.rb
INFO manager: Registered plugin: list-commands command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/version/plugin.rb
INFO manager: Registered plugin: version command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/global-status/plugin.rb
INFO manager: Registered plugin: global-status command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/ssh/plugin.rb
INFO manager: Registered plugin: ssh command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/package/plugin.rb
INFO manager: Registered plugin: package command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/provision/plugin.rb
INFO manager: Registered plugin: provision command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/synced_folders/nfs/plugin.rb
INFO manager: Registered plugin: NFS synced folders
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/synced_folders/rsync/plugin.rb
INFO manager: Registered plugin: RSync synced folders
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/synced_folders/smb/plugin.rb
INFO manager: Registered plugin: SMB synced folders
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/providers/virtualbox/plugin.rb
INFO manager: Registered plugin: VirtualBox provider
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/providers/hyperv/plugin.rb
INFO manager: Registered plugin: Hyper-V provider
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/providers/docker/plugin.rb
INFO manager: Registered plugin: docker-provider
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/hosts/arch/plugin.rb
INFO manager: Registered plugin: Arch host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/hosts/windows/plugin.rb
INFO manager: Registered plugin: Windows host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/hosts/bsd/plugin.rb
INFO manager: Registered plugin: BSD host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/hosts/redhat/plugin.rb
INFO manager: Registered plugin: Red Hat host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/hosts/gentoo/plugin.rb
INFO manager: Registered plugin: Gentoo host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/hosts/opensuse/plugin.rb
INFO manager: Registered plugin: OpenSUSE host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/hosts/darwin/plugin.rb
INFO manager: Registered plugin: Mac OS X host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/hosts/freebsd/plugin.rb
INFO manager: Registered plugin: FreeBSD host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/hosts/slackware/plugin.rb
INFO manager: Registered plugin: Slackware host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/hosts/null/plugin.rb
INFO manager: Registered plugin: null host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/hosts/linux/plugin.rb
INFO manager: Registered plugin: Linux host
INFO global: Loading plugins!
INFO manager: Registered plugin: vagrant-login
INFO manager: Registered plugin: vagrant-share
INFO vagrant: vagrant invoked: ["up", "--debug"]
DEBUG vagrant: Creating Vagrant environment
INFO environment: Environment initialized (#Vagrant::Environment:0x00000001ea2198)
INFO environment: - cwd: /home/waleed/opengeo-playbook
INFO environment: Home path: /home/waleed/.vagrant.d
INFO environment: Local data path: /home/waleed/opengeo-playbook/.vagrant
DEBUG environment: Creating: /home/waleed/opengeo-playbook/.vagrant
INFO environment: Running hook: environment_plugins_loaded
INFO runner: Preparing hooks for middleware sequence...
INFO runner: 1 hooks defined.
INFO runner: Running action: #Vagrant::Action::Builder:0x00000002342630
INFO environment: Running hook: environment_load
INFO runner: Preparing hooks for middleware sequence...
INFO runner: 1 hooks defined.
INFO runner: Running action: #Vagrant::Action::Builder:0x000000024e0b40
INFO cli: CLI: [] "up" []
DEBUG cli: Invoking command class: VagrantPlugins::CommandUp::Command []
DEBUG command: 'Up' each target VM...
INFO loader: Set :root = #Pathname:/home/waleed/opengeo-playbook/Vagrantfile
DEBUG loader: Populating proc cache for #Pathname:/home/waleed/opengeo-playbook/Vagrantfile
DEBUG loader: Load procs for pathname: /home/waleed/opengeo-playbook/Vagrantfile
INFO loader: Loading configuration in order: [:home, :root]
DEBUG loader: Loading from: root (evaluating)
DEBUG loader: Upgrading config from version 1 to 2
DEBUG loader: Upgrading config to version 2
DEBUG provisioner: Provisioner defined: ansible
DEBUG loader: Upgraded to version 2 with 1 warnings and 0 errors
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG command: Getting target VMs for command. Arguments:
DEBUG command: -- names: ["default"]
DEBUG command: -- options: {:provider=>nil}
DEBUG command: Finding machine that match name: default
INFO base: VBoxManage path: VBoxManage
INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "--version"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: 4.3.10_Ubuntur93012
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG meta: Finding driver for VirtualBox version: 4.3.10
INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_4_3
INFO base: VBoxManage path: VBoxManage
INFO environment: Getting machine: default (virtualbox)
INFO environment: Uncached load of machine.
INFO base: VBoxManage path: VBoxManage
INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "--version"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: 4.3.10_Ubuntur93012
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG meta: Finding driver for VirtualBox version: 4.3.10
INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_4_3
INFO base: VBoxManage path: VBoxManage
INFO loader: Set "15738940_machine_default" = []
INFO loader: Loading configuration in order: [:home, :root, "15738940_machine_default"]
DEBUG loader: Loading from: root (cache)
DEBUG loader: Configuration loaded successfully, finalizing and returning
INFO box_collection: Box found: precise32_cloudimage (virtualbox)
INFO loader: Set :"20766620_precise32_cloudimage_virtualbox" = #Pathname:/home/waleed/.vagrant.d/boxes/precise32_cloudimage/0/virtualbox/Vagrantfile
DEBUG loader: Populating proc cache for #Pathname:/home/waleed/.vagrant.d/boxes/precise32_cloudimage/0/virtualbox/Vagrantfile
DEBUG loader: Load procs for pathname: /home/waleed/.vagrant.d/boxes/precise32_cloudimage/0/virtualbox/Vagrantfile
INFO loader: Loading configuration in order: [:"20766620_precise32_cloudimage_virtualbox", :home, :root, "15738940_machine_default"]
DEBUG loader: Loading from: 20766620_precise32_cloudimage_virtualbox (evaluating)
DEBUG loader: Upgrading config from version 1 to 2
DEBUG loader: Upgrading config to version 2
DEBUG loader: Upgraded to version 2 with 0 warnings and 0 errors
DEBUG loader: Loading from: root (cache)
DEBUG loader: Configuration loaded successfully, finalizing and returning
INFO interface: warn: There were warnings and/or errors while loading your Vagrantfile
for the machine 'default'.

Your Vagrantfile was written for an earlier version of Vagrant,
and while Vagrant does the best it can to remain backwards
compatible, there are some cases where things have changed
significantly enough to warrant a message. These messages are
shown below.

Warnings:

```
config.vm.customize calls are VirtualBox-specific. If you're
using any other provider, you'll have to use config.vm.provider in a
v2 configuration block.

INFO machine: Initializing machine: default
INFO machine: - Provider: VagrantPlugins::ProviderVirtualBox::Provider
INFO machine: - Box: #Vagrant::Box:0x000000023f9628
INFO machine: - Data dir: /home/waleed/opengeo-playbook/.vagrant/machines/default/virtualbox
DEBUG virtualbox: Instantiating the driver for machine ID: nil
INFO base: VBoxManage path: VBoxManage
INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "--version"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: 4.3.10_Ubuntur93012
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG meta: Finding driver for VirtualBox version: 4.3.10
INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_4_3
INFO base: VBoxManage path: VBoxManage
INFO command: With machine: default (#, @name="stderr", @level=0, @formatter=#, @out=#IO:<STDERR>>], @additive=true, @name="vagrant", @path="", @parent=#, @level=1, @trace=false>, @level=1, @trace=false>, @machine=#, @driver=#, @name="stderr", @level=0, @formatter=#, @out=#IO:<STDERR>>], @additive=true, @name="vagrant", @path="", @parent=#, @level=1, @trace=false>, @level=1, @trace=false>, @level=1, @trace=false>, @interrupted=false, @vboxmanage_path="VBoxManage", @uuid=nil, @version="4.3.10", @driver=#, @name="stderr", @level=0, @formatter=#, @out=#IO:<STDERR>>], @additive=true, @name="vagrant", @path="", @parent=#, @level=1, @trace=false>, @level=1, @trace=false>, @interrupted=false, @vboxmanage_path="VBoxManage", @uuid=nil>>, @cap_logger=#, @name="stderr", @level=0, @formatter=#, @out=#IO:<STDERR>>], @additive=true, @name="vagrant", @path="", @parent=#, @level=1, @trace=false>, @level=1, @trace=false>, @cap_host_chain=[[:virtualbox, #<#Class:0x000000016eebb8:0x00000001941730>]], @cap_args=[#], @cap_caps={:virtualbox=>##Proc:0x000000016eabf8@/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/providers/virtualbox/plugin.rb:27, :nic_mac_addresses=>#Proc:0x000000016eaab8@/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/providers/virtualbox/plugin.rb:32, :public_address=>#Proc:0x00000001af02c0@/opt/vagrant/embedded/gems/gems/vagrant-share-1.1.1/lib/vagrant-share.rb:39}, @results_cache={}>, :hyperv=>##Proc:0x0000000256b600@/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/providers/hyperv/plugin.rb:25}, @results_cache={}>, :docker=>##Proc:0x00000001704378@/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/providers/docker/plugin.rb:54}, @results_cache={}>}>)
INFO interface: info: Bringing machine 'default' up with 'virtualbox' provider...
INFO batch_action: Enabling parallelization by default.
INFO batch_action: Disabling parallelization because provider doesn't support it: virtualbox
INFO batch_action: Batch action will parallelize: false
INFO batch_action: Starting action: #Vagrant::Machine:0x000000023f96c8 up {:destroy_on_error=>true, :parallel=>true, :provision_ignore_sentinel=>false, :provision_types=>nil}
INFO machine: Calling action: up on provider VirtualBox (new VM)
DEBUG environment: Attempting to acquire process-lock: machine-action-f816ad74e17431d1e2fa98ce302312a4
DEBUG environment: Attempting to acquire process-lock: dotlock
INFO environment: Acquired process lock: dotlock
INFO environment: Released process lock: dotlock
INFO environment: Acquired process lock: machine-action-f816ad74e17431d1e2fa98ce302312a4
INFO host: Autodetecting host type for [#]
DEBUG host: Trying: arch
DEBUG host: Trying: redhat
DEBUG host: Trying: gentoo
DEBUG host: Trying: opensuse
DEBUG host: Trying: darwin
DEBUG host: Trying: freebsd
DEBUG host: Trying: slackware
DEBUG host: Trying: windows
DEBUG host: Trying: bsd
DEBUG host: Trying: null
DEBUG host: Trying: linux
INFO host: Detected: linux!
INFO runner: Preparing hooks for middleware sequence...
INFO runner: 1 hooks defined.
INFO runner: Running action: #Vagrant::Action::Builder:0x00000001e00910
INFO warden: Calling IN action: #VagrantPlugins::ProviderVirtualBox::Action::CheckVirtualbox:0x00000001f0b580
INFO base: VBoxManage path: VBoxManage
INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "--version"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: 4.3.10_Ubuntur93012
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG meta: Finding driver for VirtualBox version: 4.3.10
INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_4_3
INFO base: VBoxManage path: VBoxManage
INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "list", "hostonlyifs"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
INFO warden: Calling IN action: #Vagrant::Action::Builtin::Call:0x00000001f0b6c0
INFO runner: Preparing hooks for middleware sequence...
INFO runner: 1 hooks defined.
INFO runner: Running action: #Vagrant::Action::Builder:0x000000026e6070
INFO warden: Calling IN action: #VagrantPlugins::ProviderVirtualBox::Action::Created:0x000000026eb3e0
INFO machine: New machine ID: nil
DEBUG virtualbox: Instantiating the driver for machine ID: nil
INFO base: VBoxManage path: VBoxManage
INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "--version"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: 4.3.10_Ubuntur93012
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG meta: Finding driver for VirtualBox version: 4.3.10
INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_4_3
INFO base: VBoxManage path: VBoxManage
INFO warden: Calling OUT action: #VagrantPlugins::ProviderVirtualBox::Action::Created:0x000000026eb3e0
INFO runner: Preparing hooks for middleware sequence...
INFO runner: 1 hooks defined.
INFO runner: Running action: #Vagrant::Action::Warden:0x00000001712928
INFO warden: Calling IN action: #
INFO warden: Calling IN action: #Vagrant::Action::Builtin::HandleBox:0x00000001712450
INFO handle_box: Machine already has box. HandleBox will not run.
INFO warden: Calling IN action: #
INFO warden: Calling IN action: #Vagrant::Action::Builtin::ConfigValidate:0x00000001f0b670
ERROR warden: Error occurred: There are errors in the configuration of this machine. Please fix
the following errors and try again:
```

ansible provisioner:

```
The following settings shouldn't exist: hosts

INFO warden: Beginning recovery process...
INFO warden: Calling recover: #Vagrant::Action::Builtin::Call:0x00000001f0b6c0
INFO warden: Beginning recovery process...
INFO warden: Recovery complete.
INFO warden: Recovery complete.
ERROR warden: Error occurred: There are errors in the configuration of this machine. Please fix
the following errors and try again:
```

ansible provisioner:

```
The following settings shouldn't exist: hosts

INFO warden: Beginning recovery process...
INFO warden: Recovery complete.
INFO warden: Beginning recovery process...
INFO warden: Recovery complete.
ERROR warden: Error occurred: There are errors in the configuration of this machine. Please fix
the following errors and try again:
```

ansible provisioner:

```
The following settings shouldn't exist: hosts

INFO warden: Beginning recovery process...
INFO warden: Recovery complete.
INFO warden: Beginning recovery process...
INFO warden: Recovery complete.
INFO warden: Beginning recovery process...
INFO warden: Recovery complete.
INFO environment: Released process lock: machine-action-f816ad74e17431d1e2fa98ce302312a4
INFO environment: Running hook: environment_unload
INFO runner: Preparing hooks for middleware sequence...
INFO runner: 1 hooks defined.
INFO runner: Running action: #Vagrant::Action::Builder:0x00000001e8a908
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::ConfigInvalid: There are errors in the configuration of this machine. Please fix
the following errors and try again:
```

ansible provisioner:

```
The following settings shouldn't exist: hosts

ERROR vagrant: There are errors in the configuration of this machine. Please fix
the following errors and try again:
```

ansible provisioner:

```
The following settings shouldn't exist: hosts
```

ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/config_validate.rb:18:in call' /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:incall'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:95:in block in finalize_action' /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:incall'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in call' /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/handle_box.rb:56:incall'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in call' /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:95:inblock in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in call' /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:incall'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in call' /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:inblock in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in busy' /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:inrun'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/call.rb:53:in call' /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:incall'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in call' /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:incall'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in call' /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:inblock in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in busy' /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:inrun'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:196:in action_raw' /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:173:inblock in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:474:in lock' /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:incall'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in action' /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/batch_action.rb:82:inblock (2 levels) in run'
INFO interface: error: There are errors in the configuration of this machine. Please fix
the following errors and try again:

ansible provisioner:

```
The following settings shouldn't exist: hosts
```

[0;31mThere are errors in the configuration of this machine. Please fix
the following errors and try again:

ansible provisioner:

```
The following settings shouldn't exist: hosts
```

[0m
INFO interface: Machine: error-exit ["Vagrant::Errors::ConfigInvalid", "There are errors in the configuration of this machine. Please fix\nthe following errors and try again:\n\nansible provisioner:\n\* The following settings shouldn't exist: hosts\n\n"]

**Comment by bcoca** [comment]
I'm not sure this is ansible issue, that error messages seems to be from vagrant itself

**Comment by jsmartin** [comment]
Yeah, this is a vagrant issue.   It seems like you have incorrect ansible provisioner settings.   Specifically you have a string "hosts" somewhere in your Vagrantfile.  https://docs.vagrantup.com/v2/provisioning/ansible.html

**Comment by bcoca** [comment]
closing as this should be filed with the vagrant project
